Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/r_main.c File Reference
r_main.c File Reference
#include <stdlib.h>
#include <math.h>
#include "doomdef.h"
#include "d_loop.h"
#include "m_bbox.h"
#include "m_menu.h"
#include "r_local.h"
#include "r_sky.h"
Macros
#define FIELDOFVIEW 2048
#define DISTMAP 2
Functions
void R_AddPointToBox (int x, int y, fixed_t *box)
int R_PointOnSide (fixed_t x, fixed_t y, node_t *node)
int R_PointOnSegSide (fixed_t x, fixed_t y, seg_t *line)
angle_t R_PointToAngle (fixed_t x, fixed_t y)
angle_t R_PointToAngle2 (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2)
fixed_t R_PointToDist (fixed_t x, fixed_t y)
void R_InitPointToAngle (void)
fixed_t R_ScaleFromGlobalAngle (angle_t visangle)
void R_InitTables (void)
void R_InitTextureMapping (void)
void R_InitLightTables (void)
void R_SetViewSize (int blocks, int detail)
void R_ExecuteSetViewSize (void)
void R_Init (void)
subsector_t * R_PointInSubsector (fixed_t x, fixed_t y)
void R_SetupFrame (player_t *player)
void R_RenderPlayerView (player_t *player)
Variables
int viewangleoffset
int validcount = 1
lighttable_t * fixedcolormap
lighttable_t ** walllights
int centerx
int centery
fixed_t centerxfrac
fixed_t centeryfrac
fixed_t projection
int framecount
int sscount
int linecount
int loopcount
fixed_t viewx
fixed_t viewy
fixed_t viewz
angle_t viewangle
fixed_t viewcos
fixed_t viewsin
player_t * viewplayer
int detailshift
angle_t clipangle
int viewangletox [FINEANGLES/2]
angle_t xtoviewangle [SCREENWIDTH+1]
lighttable_t * scalelight [LIGHTLEVELS][MAXLIGHTSCALE]
lighttable_t * scalelightfixed [MAXLIGHTSCALE]
lighttable_t * zlight [LIGHTLEVELS][MAXLIGHTZ]
int extralight
void(* colfunc)(void)
void(* basecolfunc)(void)
void(* fuzzcolfunc)(void)
void(* transcolfunc)(void)
void(* spanfunc)(void)
boolean setsizeneeded
int setblocks
int setdetail
Macro Definition Documentation
DISTMAP
#define DISTMAP 2
Definition at line 608 of file r_main.c.
FIELDOFVIEW
#define FIELDOFVIEW 2048
Definition at line 43 of file r_main.c.
Function Documentation
R_AddPointToBox()
void R_AddPointToBox (int x, int y, fixed_t * box)
Definition at line 123 of file r_main.c.
 {
     if (x< box[BOXLEFT])
     box[BOXLEFT] = x;
     if (x> box[BOXRIGHT])
     box[BOXRIGHT] = x;
     if (y< box[BOXBOTTOM])
     box[BOXBOTTOM] = y;
     if (y> box[BOXTOP])
     box[BOXTOP] = y;
 }
References BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, x, and y.
R_ExecuteSetViewSize()
void R_ExecuteSetViewSize (void)
Definition at line 667 of file r_main.c.
 {
     fixed_t cosadj;
     fixed_t dy;
     int     i;
     int     j;
     int     level;
     int     startmap;
     setsizeneeded = false;
     if (setblocks == 11)
     {
     scaledviewwidth = SCREENWIDTH;
     viewheight = SCREENHEIGHT;
     }
     else
     {
     scaledviewwidth = setblocks*32;
     viewheight = (setblocks*168/10)&~7;
     }
     detailshift = setdetail;
     viewwidth = scaledviewwidth>>detailshift;
     centery = viewheight/2;
     centerx = viewwidth/2;
     centerxfrac = centerx<<FRACBITS;
     centeryfrac = centery<<FRACBITS;
     projection = centerxfrac;
     if (!detailshift)
     {
     colfunc = basecolfunc = R_DrawColumn;
     fuzzcolfunc = R_DrawFuzzColumn;
     transcolfunc = R_DrawTranslatedColumn;
     spanfunc = R_DrawSpan;
     }
     else
     {
     colfunc = basecolfunc = R_DrawColumnLow;
     fuzzcolfunc = R_DrawFuzzColumnLow;
     transcolfunc = R_DrawTranslatedColumnLow;
     spanfunc = R_DrawSpanLow;
     }
     R_InitBuffer (scaledviewwidth, viewheight);
     R_InitTextureMapping ();
     // psprite scales
     pspritescale = FRACUNIT*viewwidth/SCREENWIDTH;
     pspriteiscale = FRACUNIT*SCREENWIDTH/viewwidth;
     // thing clipping
     for (i=0 ; i<viewwidth ; i++)
     screenheightarray[i] = viewheight;
     // planes
     for (i=0 ; i<viewheight ; i++)
     {
     dy = ((i-viewheight/2)<<FRACBITS)+FRACUNIT/2;
     dy = abs(dy);
     yslope[i] = FixedDiv ( (viewwidth<<detailshift)/2*FRACUNIT, dy);
     }
     for (i=0 ; i<viewwidth ; i++)
     {
     cosadj = abs(finecosine[xtoviewangle[i]>>ANGLETOFINESHIFT]);
     distscale[i] = FixedDiv (FRACUNIT,cosadj);
     }
     // Calculate the light levels to use
     //  for each level / scale combination.
     for (i=0 ; i< LIGHTLEVELS ; i++)
     {
     startmap = ((LIGHTLEVELS-1-i)*2)*NUMCOLORMAPS/LIGHTLEVELS;
     for (j=0 ; j<MAXLIGHTSCALE ; j++)
     {
         level = startmap - j*SCREENWIDTH/(viewwidth<<detailshift)/DISTMAP;
         if (level < 0)
         level = 0;
         if (level >= NUMCOLORMAPS)
         level = NUMCOLORMAPS-1;
         scalelight[i][j] = colormaps + level*256;
     }
     }
 }
References abs, ANGLETOFINESHIFT, basecolfunc, centerx, centerxfrac, centery, centeryfrac, colfunc, colormaps, detailshift, DISTMAP, distscale, finecosine, FixedDiv(), FRACBITS, FRACUNIT, fuzzcolfunc, i, j, LIGHTLEVELS, MAXLIGHTSCALE, NUMCOLORMAPS, projection, pspriteiscale, pspritescale, R_DrawColumn(), R_DrawColumnLow(), R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawSpan(), R_DrawSpanLow(), R_DrawTranslatedColumn(), R_DrawTranslatedColumnLow(), R_InitBuffer(), R_InitTextureMapping(), scaledviewwidth, scalelight, SCREENHEIGHT, screenheightarray, SCREENWIDTH, setblocks, setdetail, setsizeneeded, spanfunc, startmap, transcolfunc, viewheight, viewwidth, xtoviewangle, and yslope.
Referenced by D_Display(), D_DoomLoop(), and G_DoLoadGame().
R_Init()
void R_Init (void)
Definition at line 767 of file r_main.c.
 {
     R_InitData ();
     printf (".");
     R_InitPointToAngle ();
     printf (".");
     R_InitTables ();
     // viewwidth / viewheight / detailLevel are set by the defaults
     printf (".");
     R_SetViewSize (screenblocks, detailLevel);
     R_InitPlanes ();
     printf (".");
     R_InitLightTables ();
     printf (".");
     R_InitSkyMap ();
     R_InitTranslationTables ();
     printf (".");
     framecount = 0;
 }
References detailLevel, framecount, printf, R_InitData(), R_InitLightTables(), R_InitPlanes(), R_InitPointToAngle(), R_InitSkyMap(), R_InitTables(), R_InitTranslationTables(), R_SetViewSize(), and screenblocks.
Referenced by D_DoomMain().
R_InitLightTables()
void R_InitLightTables (void)
Definition at line 610 of file r_main.c.
 {
     int     i;
     int     j;
     int     level;
     int     startmap;
     int     scale;
     // Calculate the light levels to use
     //  for each level / distance combination.
     for (i=0 ; i< LIGHTLEVELS ; i++)
     {
     startmap = ((LIGHTLEVELS-1-i)*2)*NUMCOLORMAPS/LIGHTLEVELS;
     for (j=0 ; j<MAXLIGHTZ ; j++)
     {
         scale = FixedDiv ((SCREENWIDTH/2*FRACUNIT), (j+1)<<LIGHTZSHIFT);
         scale >>= LIGHTSCALESHIFT;
         level = startmap - scale/DISTMAP;
         if (level < 0)
         level = 0;
         if (level >= NUMCOLORMAPS)
         level = NUMCOLORMAPS-1;
         zlight[i][j] = colormaps + level*256;
     }
     }
 }
References colormaps, DISTMAP, FixedDiv(), FRACUNIT, i, j, LIGHTLEVELS, LIGHTSCALESHIFT, LIGHTZSHIFT, MAXLIGHTZ, NUMCOLORMAPS, scale, SCREENWIDTH, startmap, and zlight.
Referenced by R_Init().
R_InitPointToAngle()
void R_InitPointToAngle (void)
Definition at line 422 of file r_main.c.
 {
     // UNUSED - now getting from tables.c
 #if 0
     int i;
     long    t;
     float   f;
 //
 // slope (tangent) to angle lookup
 //
     for (i=0 ; i<=SLOPERANGE ; i++)
     {
     f = atan( (float)i/SLOPERANGE )/(3.141592657*2);
     t = 0xffffffff*f;
     tantoangle[i] = t;
     }
 #endif
 }
References atan, f, i, SLOPERANGE, t, and tantoangle.
Referenced by R_Init().
R_InitTables()
void R_InitTables (void)
Definition at line 505 of file r_main.c.
 {
     // UNUSED: now getting from tables.c
 #if 0
     int     i;
     float   a;
     float   fv;
     int     t;
     // viewangle tangent table
     for (i=0 ; i<FINEANGLES/2 ; i++)
     {
     a = (i-FINEANGLES/4+0.5)*PI*2/FINEANGLES;
     fv = FRACUNIT*tan (a);
     t = fv;
     finetangent[i] = t;
     }
     // finesine table
     for (i=0 ; i<5*FINEANGLES/4 ; i++)
     {
     // OPTIMIZE: mirror...
     a = (i+0.5)*PI*2/FINEANGLES;
     t = FRACUNIT*sin (a);
     finesine[i] = t;
     }
 #endif
 }
References FINEANGLES, finesine, finetangent, FRACUNIT, i, sin, t, and tan.
Referenced by R_Init().
R_InitTextureMapping()
void R_InitTextureMapping (void)
Definition at line 540 of file r_main.c.
 {
     int         i;
     int         x;
     int         t;
     fixed_t     focallength;
     // Use tangent table to generate viewangletox:
     //  viewangletox will give the next greatest x
     //  after the view angle.
     //
     // Calc focallength
     //  so FIELDOFVIEW angles covers SCREENWIDTH.
     focallength = FixedDiv (centerxfrac,
                 finetangent[FINEANGLES/4+FIELDOFVIEW/2] );
     for (i=0 ; i<FINEANGLES/2 ; i++)
     {
     if (finetangent[i] > FRACUNIT*2)
         t = -1;
     else if (finetangent[i] < -FRACUNIT*2)
         t = viewwidth+1;
     else
     {
         t = FixedMul (finetangent[i], focallength);
         t = (centerxfrac - t+FRACUNIT-1)>>FRACBITS;
         if (t < -1)
         t = -1;
         else if (t>viewwidth+1)
         t = viewwidth+1;
     }
     viewangletox[i] = t;
     }
     // Scan viewangletox[] to generate xtoviewangle[]:
     //  xtoviewangle will give the smallest view angle
     //  that maps to x.
     for (x=0;x<=viewwidth;x++)
     {
     i = 0;
     while (viewangletox[i]>x)
         i++;
     xtoviewangle[x] = (i<<ANGLETOFINESHIFT)-ANG90;
     }
     // Take out the fencepost cases from viewangletox.
     for (i=0 ; i<FINEANGLES/2 ; i++)
     {
     t = FixedMul (finetangent[i], focallength);
     t = centerx - t;
     if (viewangletox[i] == -1)
         viewangletox[i] = 0;
     else if (viewangletox[i] == viewwidth+1)
         viewangletox[i]  = viewwidth;
     }
     clipangle = xtoviewangle[0];
 }
References ANG90, ANGLETOFINESHIFT, centerx, centerxfrac, clipangle, FIELDOFVIEW, FINEANGLES, finetangent, FixedDiv(), FixedMul(), FRACBITS, FRACUNIT, i, t, viewangletox, viewwidth, x, and xtoviewangle.
Referenced by R_ExecuteSetViewSize().
R_PointInSubsector()
subsector_t* R_PointInSubsector (fixed_t x, fixed_t y)
Definition at line 794 of file r_main.c.
 {
     node_t* node;
     int     side;
     int     nodenum;
     // single subsector is a special case
     if (!numnodes)
     return subsectors;
     nodenum = numnodes-1;
     while (! (nodenum & NF_SUBSECTOR) )
     {
     node = &nodes[nodenum];
     side = R_PointOnSide (x, y, node);
     nodenum = node->children[side];
     }
     return &subsectors[nodenum & ~NF_SUBSECTOR];
 }
References NF_SUBSECTOR, nodes, numnodes, R_PointOnSide(), subsectors, x, and y.
Referenced by G_CheckSpot(), P_CheckPosition(), P_NightmareRespawn(), P_RespawnSpecials(), P_SetThingPosition(), and P_TeleportMove().
R_PointOnSegSide()
int R_PointOnSegSide (fixed_t x, fixed_t y, seg_t * line)
Definition at line 199 of file r_main.c.
 {
     fixed_t lx;
     fixed_t ly;
     fixed_t ldx;
     fixed_t ldy;
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     lx = line->v1->x;
     ly = line->v1->y;
     ldx = line->v2->x - lx;
     ldy = line->v2->y - ly;
     if (!ldx)
     {
     if (x <= lx)
         return ldy > 0;
     return ldy < 0;
     }
     if (!ldy)
     {
     if (y <= ly)
         return ldx < 0;
     return ldx > 0;
     }
     dx = (x - lx);
     dy = (y - ly);
     // Try to quickly decide by looking at sign bits.
     if ( (ldy ^ ldx ^ dx ^ dy)&0x80000000 )
     {
     if  ( (ldy ^ dx) & 0x80000000 )
     {
         // (left is negative)
         return 1;
     }
     return 0;
     }
     left = FixedMul ( ldy>>FRACBITS , dx );
     right = FixedMul ( dy , ldx>>FRACBITS );
     if (right < left)
     {
     // front side
     return 0;
     }
     // back side
     return 1;
 }
References FixedMul(), FRACBITS, x, and y.
Referenced by R_DrawSprite().
R_PointOnSide()
int R_PointOnSide (fixed_t x, fixed_t y, node_t * node)
Definition at line 146 of file r_main.c.
 {
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     if (!node->dx)
     {
     if (x <= node->x)
         return node->dy > 0;
     return node->dy < 0;
     }
     if (!node->dy)
     {
     if (y <= node->y)
         return node->dx < 0;
     return node->dx > 0;
     }
     dx = (x - node->x);
     dy = (y - node->y);
     // Try to quickly decide by looking at sign bits.
     if ( (node->dy ^ node->dx ^ dx ^ dy)&0x80000000 )
     {
     if  ( (node->dy ^ dx) & 0x80000000 )
     {
         // (left is negative)
         return 1;
     }
     return 0;
     }
     left = FixedMul ( node->dy>>FRACBITS , dx );
     right = FixedMul ( dy , node->dx>>FRACBITS );
     if (right < left)
     {
     // front side
     return 0;
     }
     // back side
     return 1;
 }
References FixedMul(), FRACBITS, x, and y.
Referenced by R_PointInSubsector(), and R_RenderBSPNode().
R_PointToAngle()
angle_t R_PointToAngle (fixed_t x, fixed_t y)
Definition at line 276 of file r_main.c.
 {
     x -= viewx;
     y -= viewy;
     if ( (!x) && (!y) )
     return 0;
     if (x>= 0)
     {
     // x >=0
     if (y>= 0)
     {
         // y>= 0
         if (x>y)
         {
         // octant 0
         return tantoangle[ SlopeDiv(y,x)];
         }
         else
         {
         // octant 1
         return ANG90-1-tantoangle[ SlopeDiv(x,y)];
         }
     }
     else
     {
         // y<0
         y = -y;
         if (x>y)
         {
         // octant 8
         return -tantoangle[SlopeDiv(y,x)];
         }
         else
         {
         // octant 7
         return ANG270+tantoangle[ SlopeDiv(x,y)];
         }
     }
     }
     else
     {
     // x<0
     x = -x;
     if (y>= 0)
     {
         // y>= 0
         if (x>y)
         {
         // octant 3
         return ANG180-1-tantoangle[ SlopeDiv(y,x)];
         }
         else
         {
         // octant 2
         return ANG90+ tantoangle[ SlopeDiv(x,y)];
         }
     }
     else
     {
         // y<0
         y = -y;
         if (x>y)
         {
         // octant 4
         return ANG180+tantoangle[ SlopeDiv(y,x)];
         }
         else
         {
          // octant 5
         return ANG270-1-tantoangle[ SlopeDiv(x,y)];
         }
     }
     }
     return 0;
 }
References ANG180, ANG270, ANG90, SlopeDiv(), tantoangle, viewx, viewy, x, and y.
Referenced by R_AddLine(), R_CheckBBox(), R_PointToAngle2(), and R_ProjectSprite().
R_PointToAngle2()
angle_t R_PointToAngle2 (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2)
Definition at line 362 of file r_main.c.
 {
     viewx = x1;
     viewy = y1;
     return R_PointToAngle (x2, y2);
 }
References R_PointToAngle(), viewx, viewy, and y1().
Referenced by A_FaceTarget(), A_Punch(), A_Saw(), A_Tracer(), P_DamageMobj(), P_DeathThink(), P_HitSlideLine(), P_LookForPlayers(), P_SpawnMissile(), S_AdjustSoundParams(), and ST_updateFaceWidget().
R_PointToDist()
fixed_t R_PointToDist (fixed_t x, fixed_t y)
Definition at line 376 of file r_main.c.
 {
     int     angle;
     fixed_t dx;
     fixed_t dy;
     fixed_t temp;
     fixed_t dist;
     fixed_t     frac;
     dx = abs(x - viewx);
     dy = abs(y - viewy);
     if (dy>dx)
     {
     temp = dx;
     dx = dy;
     dy = temp;
     }
     // Fix crashes in udm1.wad
     if (dx != 0)
     {
         frac = FixedDiv(dy, dx);
     }
     else
     {
     frac = 0;
     }
     angle = (tantoangle[frac>>DBITS]+ANG90) >> ANGLETOFINESHIFT;
     // use as cosine
     dist = FixedDiv (dx, finesine[angle] );
     return dist;
 }
References abs, ANG90, ANGLETOFINESHIFT, DBITS, finesine, FixedDiv(), tantoangle, viewx, viewy, x, and y.
Referenced by R_StoreWallRange().
R_RenderPlayerView()
void R_RenderPlayerView (player_t * player)
Definition at line 863 of file r_main.c.
 {
     R_SetupFrame (player);
     // Clear buffers.
     R_ClearClipSegs ();
     R_ClearDrawSegs ();
     R_ClearPlanes ();
     R_ClearSprites ();
     // check for new console commands.
     NetUpdate ();
     // The head node is the last node output.
     R_RenderBSPNode (numnodes-1);
     // Check for new console commands.
     NetUpdate ();
     R_DrawPlanes ();
     // Check for new console commands.
     NetUpdate ();
     R_DrawMasked ();
     // Check for new console commands.
     NetUpdate ();
 }
References NetUpdate(), numnodes, R_ClearClipSegs(), R_ClearDrawSegs(), R_ClearPlanes(), R_ClearSprites(), R_DrawMasked(), R_DrawPlanes(), R_RenderBSPNode(), and R_SetupFrame().
Referenced by D_Display().
R_ScaleFromGlobalAngle()
fixed_t R_ScaleFromGlobalAngle (angle_t visangle)
Definition at line 449 of file r_main.c.
 {
     fixed_t     scale;
     angle_t     anglea;
     angle_t     angleb;
     int         sinea;
     int         sineb;
     fixed_t     num;
     int         den;
     // UNUSED
 #if 0
 {
     fixed_t     dist;
     fixed_t     z;
     fixed_t     sinv;
     fixed_t     cosv;
     sinv = finesine[(visangle-rw_normalangle)>>ANGLETOFINESHIFT];
     dist = FixedDiv (rw_distance, sinv);
     cosv = finecosine[(viewangle-visangle)>>ANGLETOFINESHIFT];
     z = abs(FixedMul (dist, cosv));
     scale = FixedDiv(projection, z);
     return scale;
 }
 #endif
     anglea = ANG90 + (visangle-viewangle);
     angleb = ANG90 + (visangle-rw_normalangle);
     // both sines are allways positive
     sinea = finesine[anglea>>ANGLETOFINESHIFT];
     sineb = finesine[angleb>>ANGLETOFINESHIFT];
     num = FixedMul(projection,sineb)<<detailshift;
     den = FixedMul(rw_distance,sinea);
     if (den > num>>16)
     {
     scale = FixedDiv (num, den);
     if (scale > 64*FRACUNIT)
         scale = 64*FRACUNIT;
     else if (scale < 256)
         scale = 256;
     }
     else
     scale = 64*FRACUNIT;
     return scale;
 }
References abs, ANG90, ANGLETOFINESHIFT, detailshift, finecosine, finesine, FixedDiv(), FixedMul(), FRACUNIT, num, projection, rw_distance, rw_normalangle, scale, and viewangle.
Referenced by R_StoreWallRange().
R_SetupFrame()
void R_SetupFrame (player_t * player)
Definition at line 823 of file r_main.c.
 {
     int     i;
     viewplayer = player;
     viewx = player->mo->x;
     viewy = player->mo->y;
     viewangle = player->mo->angle + viewangleoffset;
     extralight = player->extralight;
     viewz = player->viewz;
     viewsin = finesine[viewangle>>ANGLETOFINESHIFT];
     viewcos = finecosine[viewangle>>ANGLETOFINESHIFT];
     sscount = 0;
     if (player->fixedcolormap)
     {
     fixedcolormap =
         colormaps
         + player->fixedcolormap*256*sizeof(lighttable_t);
     walllights = scalelightfixed;
     for (i=0 ; i<MAXLIGHTSCALE ; i++)
         scalelightfixed[i] = fixedcolormap;
     }
     else
     fixedcolormap = 0;
     framecount++;
     validcount++;
 }
References mobj_s::angle, ANGLETOFINESHIFT, colormaps, player_s::extralight, extralight, finecosine, finesine, player_s::fixedcolormap, fixedcolormap, framecount, i, MAXLIGHTSCALE, player_s::mo, scalelightfixed, sscount, validcount, viewangle, viewangleoffset, viewcos, viewplayer, viewsin, viewx, viewy, player_s::viewz, viewz, walllights, mobj_s::x, and mobj_s::y.
Referenced by R_RenderPlayerView().
R_SetViewSize()
void R_SetViewSize (int blocks, int detail)
Definition at line 654 of file r_main.c.
 {
     setsizeneeded = true;
     setblocks = blocks;
     setdetail = detail;
 }
References detail, setblocks, setdetail, and setsizeneeded.
Referenced by M_ChangeDetail(), M_SizeDisplay(), and R_Init().
Variable Documentation
basecolfunc
void(* basecolfunc) (void) (void)
Definition at line 110 of file r_main.c.
Referenced by R_DrawVisSprite(), and R_ExecuteSetViewSize().
centerx
int centerx
Definition at line 56 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), and R_InitTextureMapping().
centerxfrac
fixed_t centerxfrac
Definition at line 59 of file r_main.c.
Referenced by R_ClearPlanes(), R_DrawPSprite(), R_ExecuteSetViewSize(), R_InitTextureMapping(), and R_ProjectSprite().
centery
int centery
Definition at line 57 of file r_main.c.
Referenced by R_DrawColumn(), R_DrawColumnLow(), R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawTranslatedColumn(), R_DrawTranslatedColumnLow(), and R_ExecuteSetViewSize().
centeryfrac
fixed_t centeryfrac
Definition at line 60 of file r_main.c.
Referenced by R_DrawVisSprite(), R_ExecuteSetViewSize(), R_RenderMaskedSegRange(), and R_StoreWallRange().
clipangle
angle_t clipangle
Definition at line 87 of file r_main.c.
Referenced by R_AddLine(), R_CheckBBox(), and R_InitTextureMapping().
colfunc
void(* colfunc) (void) (void)
Definition at line 109 of file r_main.c.
Referenced by R_DrawMaskedColumn(), R_DrawPlanes(), R_DrawVisSprite(), R_ExecuteSetViewSize(), and R_RenderSegLoop().
detailshift
int detailshift
Definition at line 82 of file r_main.c.
Referenced by R_DrawPlanes(), R_DrawPSprite(), R_DrawVisSprite(), R_ExecuteSetViewSize(), R_ProjectSprite(), R_ScaleFromGlobalAngle(), and R_StoreWallRange().
extralight
int extralight
Definition at line 105 of file r_main.c.
Referenced by R_AddSprites(), R_DrawPlanes(), R_DrawPlayerSprites(), R_RenderMaskedSegRange(), R_SetupFrame(), and R_StoreWallRange().
fixedcolormap
lighttable_t* fixedcolormap
Definition at line 53 of file r_main.c.
Referenced by R_DrawPSprite(), R_MapPlane(), R_ProjectSprite(), R_RenderMaskedSegRange(), R_SetupFrame(), and R_StoreWallRange().
framecount
int framecount
Definition at line 64 of file r_main.c.
Referenced by R_Init(), and R_SetupFrame().
fuzzcolfunc
void(* fuzzcolfunc) (void) (void)
Definition at line 111 of file r_main.c.
Referenced by R_DrawVisSprite(), and R_ExecuteSetViewSize().
linecount
int linecount
Definition at line 67 of file r_main.c.
Referenced by sort_main().
loopcount
int loopcount
Definition at line 68 of file r_main.c.
projection
fixed_t projection
Definition at line 61 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), R_ProjectSprite(), R_ScaleFromGlobalAngle(), and R_StoreWallRange().
scalelight
lighttable_t* scalelight[LIGHTLEVELS][MAXLIGHTSCALE]
Definition at line 100 of file r_main.c.
Referenced by R_AddSprites(), R_DrawPlayerSprites(), R_ExecuteSetViewSize(), R_RenderMaskedSegRange(), and R_StoreWallRange().
scalelightfixed
lighttable_t* scalelightfixed[MAXLIGHTSCALE]
Definition at line 101 of file r_main.c.
Referenced by R_SetupFrame().
setblocks
int setblocks
Definition at line 649 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), and R_SetViewSize().
setdetail
int setdetail
Definition at line 650 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), and R_SetViewSize().
setsizeneeded
boolean setsizeneeded
Definition at line 648 of file r_main.c.
Referenced by D_Display(), G_DoLoadGame(), R_ExecuteSetViewSize(), and R_SetViewSize().
spanfunc
void(* spanfunc) (void) (void)
Definition at line 113 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), and R_MapPlane().
sscount
int sscount
Definition at line 66 of file r_main.c.
Referenced by R_SetupFrame(), and R_Subsector().
transcolfunc
void(* transcolfunc) (void) (void)
Definition at line 112 of file r_main.c.
Referenced by R_DrawVisSprite(), and R_ExecuteSetViewSize().
validcount
int validcount = 1
Definition at line 50 of file r_main.c.
Referenced by P_BlockLinesIterator(), P_CheckPosition(), P_CheckSight(), P_CrossSubsector(), P_NoiseAlert(), P_PathTraverse(), P_RecursiveSound(), P_TeleportMove(), R_AddSprites(), and R_SetupFrame().
viewangle
angle_t viewangle
Definition at line 74 of file r_main.c.
Referenced by R_AddLine(), R_CheckBBox(), R_ClearPlanes(), R_DrawPlanes(), R_MapPlane(), R_ScaleFromGlobalAngle(), R_SetupFrame(), and R_StoreWallRange().
viewangleoffset
int viewangleoffset
Definition at line 47 of file r_main.c.
Referenced by InitConnectData(), R_DrawMasked(), and R_SetupFrame().
viewangletox
int viewangletox[FINEANGLES/2]
Definition at line 93 of file r_main.c.
Referenced by R_AddLine(), R_CheckBBox(), and R_InitTextureMapping().
viewcos
fixed_t viewcos
Definition at line 76 of file r_main.c.
Referenced by R_ProjectSprite(), R_SetupFrame(), and R_StoreWallRange().
viewplayer
player_t* viewplayer
Definition at line 79 of file r_main.c.
Referenced by R_DrawPlayerSprites(), R_DrawPSprite(), and R_SetupFrame().
viewsin
fixed_t viewsin
Definition at line 77 of file r_main.c.
Referenced by R_ProjectSprite(), R_SetupFrame(), and R_StoreWallRange().
viewx
fixed_t viewx
Definition at line 70 of file r_main.c.
Referenced by R_CheckBBox(), R_MapPlane(), R_PointToAngle(), R_PointToAngle2(), R_PointToDist(), R_ProjectSprite(), R_RenderBSPNode(), R_SetupFrame(), and R_StoreWallRange().
viewy
fixed_t viewy
Definition at line 71 of file r_main.c.
Referenced by R_CheckBBox(), R_MapPlane(), R_PointToAngle(), R_PointToAngle2(), R_PointToDist(), R_ProjectSprite(), R_RenderBSPNode(), R_SetupFrame(), and R_StoreWallRange().
viewz
fixed_t viewz
Definition at line 72 of file r_main.c.
Referenced by G_CheckSpot(), P_Ticker(), R_DrawPlanes(), R_ProjectSprite(), R_RenderMaskedSegRange(), R_SetupFrame(), R_StoreWallRange(), and R_Subsector().
walllights
lighttable_t** walllights extern
Definition at line 86 of file r_segs.c.
Referenced by R_RenderMaskedSegRange(), R_RenderSegLoop(), R_SetupFrame(), and R_StoreWallRange().
xtoviewangle
angle_t xtoviewangle[SCREENWIDTH+1]
Definition at line 98 of file r_main.c.
Referenced by R_DrawPlanes(), R_ExecuteSetViewSize(), R_InitTextureMapping(), R_MapPlane(), R_RenderSegLoop(), and R_StoreWallRange().
zlight
lighttable_t* zlight[LIGHTLEVELS][MAXLIGHTZ]
Definition at line 102 of file r_main.c.
Referenced by R_DrawPlanes(), and R_InitLightTables().