Fennix: Userspace/apps/base/busybox/util-linux/volume_id/unused_lvm.c File Reference
unused_lvm.c File Reference
#include "volume_id_internal.h"
Data Structures
struct lvm1_super_block
struct lvm2_super_block
Macros
#define LVM1_SB_OFF 0x400
#define LVM2_LABEL_ID "LABELONE"
#define LVM2LABEL_SCAN_SECTORS 4
Functions
int FAST_FUNC volume_id_probe_lvm1 (struct volume_id *id, uint64_t off)
int FAST_FUNC volume_id_probe_lvm2 (struct volume_id *id, uint64_t off)
Variables
struct lvm1_super_block PACKED
Data Structure Documentation
lvm1_super_block
struct lvm1_super_block
Definition at line 29 of file unused_lvm.c.
Data Fields
uint8_t id[2]
lvm2_super_block
struct lvm2_super_block
Definition at line 33 of file unused_lvm.c.
Data Fields
uint32_t crc_xl
uint8_t id[8]
uint32_t offset_xl
uint64_t sector_xl
uint8_t type[8]
Macro Definition Documentation
LVM1_SB_OFF
#define LVM1_SB_OFF 0x400
Definition at line 41 of file unused_lvm.c.
LVM2_LABEL_ID
#define LVM2_LABEL_ID "LABELONE"
Definition at line 62 of file unused_lvm.c.
LVM2LABEL_SCAN_SECTORS
#define LVM2LABEL_SCAN_SECTORS 4
Definition at line 63 of file unused_lvm.c.
Function Documentation
volume_id_probe_lvm1()
int FAST_FUNC volume_id_probe_lvm1 (struct volume_id * id, uint64_t off)
Definition at line 43 of file unused_lvm.c.
 {
     struct lvm1_super_block *lvm;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     lvm = volume_id_get_buffer(id, off + LVM1_SB_OFF, 0x800);
     if (lvm == NULL)
         return -1;
     if (lvm->id[0] != 'H' || lvm->id[1] != 'M')
         return -1;
 //  volume_id_set_usage(id, VOLUME_ID_RAID);
 //  id->type = "LVM1_member";
     return 0;
 }
References dbg, lvm1_super_block::id, LVM1_SB_OFF, NULL, off, and volume_id_get_buffer().
volume_id_probe_lvm2()
int FAST_FUNC volume_id_probe_lvm2 (struct volume_id * id, uint64_t off)
Definition at line 65 of file unused_lvm.c.
 {
     const uint8_t *buf;
     unsigned soff;
     struct lvm2_super_block *lvm;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     buf = volume_id_get_buffer(id, off, LVM2LABEL_SCAN_SECTORS * 0x200);
     if (buf == NULL)
         return -1;
     for (soff = 0; soff < LVM2LABEL_SCAN_SECTORS * 0x200; soff += 0x200) {
         lvm = (struct lvm2_super_block *) &buf[soff];
         if (memcmp(lvm->id, LVM2_LABEL_ID, 8) == 0)
             goto found;
     }
     return -1;
  found:
 //  memcpy(id->type_version, lvm->type, 8);
 //  volume_id_set_usage(id, VOLUME_ID_RAID);
 //  id->type = "LVM2_member";
     return 0;
 }
References buf, dbg, found, lvm2_super_block::id, LVM2_LABEL_ID, LVM2LABEL_SCAN_SECTORS, memcmp(), NULL, off, and volume_id_get_buffer().
Variable Documentation
PACKED
struct lvm2_super_block PACKED