Fennix: Userspace/musl/src/include/time.h File Reference
time.h File Reference
#include "../../include/time.h"
Functions
hidden int __clock_gettime (clockid_t, struct timespec *)
hidden int __clock_nanosleep (clockid_t, int, const struct timespec *, struct timespec *)
hidden char * __asctime_r (const struct tm *, char *)
hidden struct tm * __gmtime_r (const time_t *restrict, struct tm *restrict)
hidden struct tm * __localtime_r (const time_t *restrict, struct tm *restrict)
hidden size_t __strftime_l (char *restrict, size_t, const char *restrict, const struct tm *restrict, locale_t)
Function Documentation
__asctime_r()
hidden char* __asctime_r (const struct tm * , char *)
Referenced by asctime().
__clock_gettime()
hidden int __clock_gettime (clockid_t clk, struct timespec * ts)
Definition at line 59 of file clock_gettime.c.
 {
     int r;
 #ifdef VDSO_CGT_SYM
     int (*f)(clockid_t, struct timespec *) =
         (int (*)(clockid_t, struct timespec *))vdso_func;
     if (f) {
         r = f(clk, ts);
         if (!r) return r;
         if (r == -EINVAL) return __syscall_ret(r);
         /* Fall through on errors other than EINVAL. Some buggy
          * vdso implementations return ENOSYS for clocks they
          * can't handle, rather than making the syscall. This
          * also handles the case where cgt_init fails to find
          * a vdso function to use. */
     }
 #endif
 #ifdef SYS_clock_gettime64
     r = -ENOSYS;
     if (sizeof(time_t) > 4)
         r = __syscall(SYS_clock_gettime64, clk, ts);
     if (SYS_clock_gettime == SYS_clock_gettime64 || r!=-ENOSYS)
         return __syscall_ret(r);
     long ts32[2];
     r = __syscall(SYS_clock_gettime, clk, ts32);
 #ifdef SYS_gettimeofday
     if (r==-ENOSYS && clk==CLOCK_REALTIME) {
         r = __syscall(SYS_gettimeofday, ts32, 0);
         ts32[1] *= 1000;
     }
 #endif
     if (!r) {
         ts->tv_sec = ts32[0];
         ts->tv_nsec = ts32[1];
         return r;
     }
     return __syscall_ret(r);
 #else
     r = __syscall(SYS_clock_gettime, clk, ts);
 #ifdef SYS_gettimeofday
     if (r == -ENOSYS) {
         if (clk == CLOCK_REALTIME) {
             __syscall(SYS_gettimeofday, ts, 0);
             ts->tv_nsec = (int)ts->tv_nsec * 1000;
             return 0;
         }
         r = -EINVAL;
     }
 #endif
     return __syscall_ret(r);
 #endif
 }
References __syscall, __syscall_ret(), CLOCK_REALTIME, EINVAL, ENOSYS, f, SYS_clock_gettime, SYS_clock_gettime64, timespec::tv_nsec, and timespec::tv_sec.
Referenced by __randname(), __timedwait_cp(), clock(), time(), and timespec_get().
__clock_nanosleep()
hidden int __clock_nanosleep (clockid_t clk, int flags, const struct timespec * req, struct timespec * rem)
Definition at line 8 of file clock_nanosleep.c.
 {
     if (clk == CLOCK_THREAD_CPUTIME_ID) return EINVAL;
 #ifdef SYS_clock_nanosleep_time64
     time_t s = req->tv_sec;
     long ns = req->tv_nsec;
     int r = -ENOSYS;
     if (SYS_clock_nanosleep == SYS_clock_nanosleep_time64 || !IS32BIT(s))
         r = __syscall_cp(SYS_clock_nanosleep_time64, clk, flags,
             ((long long[]){s, ns}), rem);
     if (SYS_clock_nanosleep == SYS_clock_nanosleep_time64 || r!=-ENOSYS)
         return -r;
     long long extra = s - CLAMP(s);
     long ts32[2] = { CLAMP(s), ns };
     if (clk == CLOCK_REALTIME && !flags)
         r = __syscall_cp(SYS_nanosleep, &ts32, &ts32);
     else
         r = __syscall_cp(SYS_clock_nanosleep, clk, flags, &ts32, &ts32);
     if (r==-EINTR && rem && !(flags & TIMER_ABSTIME)) {
         rem->tv_sec = ts32[0] + extra;
         rem->tv_nsec = ts32[1];
     }
     return -r;
 #else
     if (clk == CLOCK_REALTIME && !flags)
         return -__syscall_cp(SYS_nanosleep, req, rem);
     return -__syscall_cp(SYS_clock_nanosleep, clk, flags, req, rem);
 #endif
 }
References __syscall_cp, CLAMP, CLOCK_REALTIME, CLOCK_THREAD_CPUTIME_ID, EINTR, EINVAL, ENOSYS, flags, IS32BIT, s, SYS_clock_nanosleep, SYS_clock_nanosleep_time64, timespec::tv_nsec, and timespec::tv_sec.
Referenced by nanosleep(), and thrd_sleep().
__gmtime_r()
hidden struct tm* __gmtime_r (const time_t * restrict, struct tm * restrict)
Referenced by gmtime().
__localtime_r()
hidden struct tm* __localtime_r (const time_t * restrict, struct tm * restrict)
Referenced by localtime().
__strftime_l()
hidden size_t __strftime_l (char * restrict, size_t , const char * restrict, const struct tm * restrict, locale_t)