Fennix: Userspace/musl/src/mman/mremap.c File Reference
mremap.c File Reference
#include <unistd.h>
#include <sys/mman.h>
#include <errno.h>
#include <stdint.h>
#include <stdarg.h>
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
static void dummy (void)
weak_alias (dummy, __vm_wait)
void * __mremap (void *old_addr, size_t old_len, size_t new_len, int flags,...)
weak_alias (__mremap, mremap)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file mremap.c.
Function Documentation
__mremap()
void* __mremap (void * old_addr, size_t old_len, size_t new_len, int flags, ...)
Definition at line 12 of file mremap.c.
 {
     va_list ap;
     void *new_addr = 0;
     if (new_len >= PTRDIFF_MAX) {
         errno = ENOMEM;
         return MAP_FAILED;
     }
     if (flags & MREMAP_FIXED) {
         __vm_wait();
         va_start(ap, flags);
         new_addr = va_arg(ap, void *);
         va_end(ap);
     }
     return (void *)syscall(SYS_mremap, old_addr, old_len, new_len, flags, new_addr);
 }
References __vm_wait(), ap, ENOMEM, errno, flags, MAP_FAILED, PTRDIFF_MAX, syscall(), va_arg, va_end, and va_start.
Referenced by realloc().
dummy()
static void dummy (void) static
Definition at line 9 of file mremap.c.
 { }
weak_alias() [1/2]
weak_alias (__mremap , mremap)
weak_alias() [2/2]
weak_alias (dummy , __vm_wait)