Fennix: Userspace/apps/base/utest/userspace_test.c File Reference
userspace_test.c File Reference
#include <stdint.h>
#include <stddef.h>
#include <dirent.h>
#include <sys/wait.h>
#include <string.h>
#include <errno.h>
#include <sys/inotify.h>
#include <fcntl.h>
#include <pty.h>
#include <stdlib.h>
#include <signal.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/reboot.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <time.h>
#include <pwd.h>
Data Structures
struct Elf32_auxv_t
struct Elf64_auxv_t
union Elf32_auxv_t.a_un
union Elf64_auxv_t.a_un
Macros
#define _POSIX_C_SOURCE 200809L
#define _POSIX_SOURCE
#define _GNU_SOURCE
#define AT_NULL 0
#define AT_IGNORE 1
#define AT_EXECFD 2
#define AT_PHDR 3
#define AT_PHENT 4
#define AT_PHNUM 5
#define AT_PAGESZ 6
#define AT_BASE 7
#define AT_FLAGS 8
#define AT_ENTRY 9
#define AT_NOTELF 10
#define AT_UID 11
#define AT_EUID 12
#define AT_GID 13
#define AT_EGID 14
#define AT_PLATFORM 15
#define AT_HWCAP 16
#define AT_CLKTCK 17
#define AT_SECURE 23
#define AT_BASE_PLATFORM 24
#define AT_RANDOM 25
#define AT_HWCAP2 26
#define AT_EXECFN 31
#define AT_SYSINFO 32
#define AT_SYSINFO_EHDR 33
#define AT_L1I_CACHESHAPE 34
#define AT_L1D_CACHESHAPE 35
#define AT_L2_CACHESHAPE 36
#define AT_L3_CACHESHAPE 37
#define AT_L1I_CACHESIZE 40
#define AT_L1I_CACHEGEOMETRY 41
#define AT_L1D_CACHESIZE 42
#define AT_L1D_CACHEGEOMETRY 43
#define AT_L2_CACHESIZE 44
#define AT_L2_CACHEGEOMETRY 45
#define AT_L3_CACHESIZE 46
#define AT_L3_CACHEGEOMETRY 47
#define AT_MINSIGSTKSZ 51
#define EVENT_SIZE (sizeof(struct inotify_event))
#define BUF_LEN (1024 * (EVENT_SIZE + 16))
#define Elf_auxv_t Elf32_auxv_t
#define loop
#define __musl_SYS_brk 12
Functions
static __inline long __musl_syscall1 (long n, long a1)
long __musl_syscall_ret (unsigned long r)
void test_passwd ()
void * __libc_sbrk (intptr_t increment)
void test_brk ()
void test_time ()
void test_args (int argc, char *argv[], char *envp[])
void test_stdio ()
void test_file ()
void test_ptmx ()
void test_system ()
void signalHandler (int signo)
void test_signal ()
void test_execve_fork ()
void test_dirent ()
char * create_file ()
char * create_directory ()
void test_watch_file ()
void test_watch_directory ()
void shutdown_linux ()
void reboot_linux ()
void self_fork_exec ()
void fork_bomb ()
void fork_bomb_syscall ()
int main (int argc, char *argv[], char *envp[])
Variables
struct passwd * p = NULL
static void * heap_end = NULL
int sigRec = 0
Data Structure Documentation
Elf32_auxv_t
struct Elf32_auxv_t
Definition at line 62 of file abi.h.
Data Fields
uint32_t a_type
union Elf32_auxv_t a_un
union Elf32_auxv_t a_un
union Elf32_auxv_t a_un
union Elf32_auxv_t a_un
Elf64_auxv_t
struct Elf64_auxv_t
Definition at line 71 of file abi.h.
Data Fields
uint64_t a_type
union Elf64_auxv_t a_un
union Elf64_auxv_t a_un
union Elf64_auxv_t a_un
union Elf64_auxv_t a_un
Elf32_auxv_t.a_un
union Elf32_auxv_t.a_un
Definition at line 974 of file elf.h.
Data Fields
uint32_t a_val
uint32_t a_val
uint32_t a_val
uint32_t a_val
Elf64_auxv_t.a_un
union Elf64_auxv_t.a_un
Definition at line 981 of file elf.h.
Data Fields
uint64_t a_val
uint64_t a_val
uint64_t a_val
uint64_t a_val
Macro Definition Documentation
__musl_SYS_brk
#define __musl_SYS_brk 12
Definition at line 93 of file userspace_test.c.
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 18 of file userspace_test.c.
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 1 of file userspace_test.c.
_POSIX_SOURCE
#define _POSIX_SOURCE
Definition at line 2 of file userspace_test.c.
AT_BASE
#define AT_BASE 7
Definition at line 30 of file userspace_test.c.
AT_BASE_PLATFORM
#define AT_BASE_PLATFORM 24
Definition at line 42 of file userspace_test.c.
AT_CLKTCK
#define AT_CLKTCK 17
Definition at line 40 of file userspace_test.c.
AT_EGID
#define AT_EGID 14
Definition at line 37 of file userspace_test.c.
AT_ENTRY
#define AT_ENTRY 9
Definition at line 32 of file userspace_test.c.
AT_EUID
#define AT_EUID 12
Definition at line 35 of file userspace_test.c.
AT_EXECFD
#define AT_EXECFD 2
Definition at line 25 of file userspace_test.c.
AT_EXECFN
#define AT_EXECFN 31
Definition at line 45 of file userspace_test.c.
AT_FLAGS
#define AT_FLAGS 8
Definition at line 31 of file userspace_test.c.
AT_GID
#define AT_GID 13
Definition at line 36 of file userspace_test.c.
AT_HWCAP
#define AT_HWCAP 16
Definition at line 39 of file userspace_test.c.
AT_HWCAP2
#define AT_HWCAP2 26
Definition at line 44 of file userspace_test.c.
AT_IGNORE
#define AT_IGNORE 1
Definition at line 24 of file userspace_test.c.
AT_L1D_CACHEGEOMETRY
#define AT_L1D_CACHEGEOMETRY 43
Definition at line 55 of file userspace_test.c.
AT_L1D_CACHESHAPE
#define AT_L1D_CACHESHAPE 35
Definition at line 49 of file userspace_test.c.
AT_L1D_CACHESIZE
#define AT_L1D_CACHESIZE 42
Definition at line 54 of file userspace_test.c.
AT_L1I_CACHEGEOMETRY
#define AT_L1I_CACHEGEOMETRY 41
Definition at line 53 of file userspace_test.c.
AT_L1I_CACHESHAPE
#define AT_L1I_CACHESHAPE 34
Definition at line 48 of file userspace_test.c.
AT_L1I_CACHESIZE
#define AT_L1I_CACHESIZE 40
Definition at line 52 of file userspace_test.c.
AT_L2_CACHEGEOMETRY
#define AT_L2_CACHEGEOMETRY 45
Definition at line 57 of file userspace_test.c.
AT_L2_CACHESHAPE
#define AT_L2_CACHESHAPE 36
Definition at line 50 of file userspace_test.c.
AT_L2_CACHESIZE
#define AT_L2_CACHESIZE 44
Definition at line 56 of file userspace_test.c.
AT_L3_CACHEGEOMETRY
#define AT_L3_CACHEGEOMETRY 47
Definition at line 59 of file userspace_test.c.
AT_L3_CACHESHAPE
#define AT_L3_CACHESHAPE 37
Definition at line 51 of file userspace_test.c.
AT_L3_CACHESIZE
#define AT_L3_CACHESIZE 46
Definition at line 58 of file userspace_test.c.
AT_MINSIGSTKSZ
#define AT_MINSIGSTKSZ 51
Definition at line 60 of file userspace_test.c.
AT_NOTELF
#define AT_NOTELF 10
Definition at line 33 of file userspace_test.c.
AT_NULL
#define AT_NULL 0
Definition at line 23 of file userspace_test.c.
AT_PAGESZ
#define AT_PAGESZ 6
Definition at line 29 of file userspace_test.c.
AT_PHDR
#define AT_PHDR 3
Definition at line 26 of file userspace_test.c.
AT_PHENT
#define AT_PHENT 4
Definition at line 27 of file userspace_test.c.
AT_PHNUM
#define AT_PHNUM 5
Definition at line 28 of file userspace_test.c.
AT_PLATFORM
#define AT_PLATFORM 15
Definition at line 38 of file userspace_test.c.
AT_RANDOM
#define AT_RANDOM 25
Definition at line 43 of file userspace_test.c.
AT_SECURE
#define AT_SECURE 23
Definition at line 41 of file userspace_test.c.
AT_SYSINFO
#define AT_SYSINFO 32
Definition at line 46 of file userspace_test.c.
AT_SYSINFO_EHDR
#define AT_SYSINFO_EHDR 33
Definition at line 47 of file userspace_test.c.
AT_UID
#define AT_UID 11
Definition at line 34 of file userspace_test.c.
BUF_LEN
#define BUF_LEN (1024 * (EVENT_SIZE + 16))
Definition at line 63 of file userspace_test.c.
Elf_auxv_t
#define Elf_auxv_t Elf32_auxv_t
Definition at line 86 of file userspace_test.c.
EVENT_SIZE
#define EVENT_SIZE (sizeof(struct inotify_event))
Definition at line 62 of file userspace_test.c.
loop
#define loop
Value:
    while (1) \
        ;
Definition at line 89 of file userspace_test.c.
Function Documentation
__libc_sbrk()
void* __libc_sbrk (intptr_t increment)
Definition at line 141 of file userspace_test.c.
 {
     if (heap_end == NULL)
     {
         heap_end = (void *)__musl_syscall1(__musl_SYS_brk, 0);
         printf("SYS_brk(0) = %p\n", heap_end);
         heap_end = (void *)__musl_syscall1(__musl_SYS_brk, (long)heap_end + 0x2000);
         printf("Adding 0x2000 to heap_end: %p\n", heap_end);
     }
     if (increment == 0)
     {
         printf("Returning heap_end: %p\n", heap_end);
         return heap_end;
     }
     void *old_heap_end = heap_end;
     long ret = __musl_syscall1(__musl_SYS_brk, (long)heap_end + increment);
     printf("SYS_brk(%p) = %p\n", (void *)((long)heap_end + increment), (void *)ret);
     if (ret == 0)
     {
         heap_end = (void *)__musl_syscall1(__musl_SYS_brk, 0);
         printf("SYS_brk(0) = %p\n", heap_end);
         return old_heap_end;
     }
     return (void *)__musl_syscall_ret(ret);
 }
References __musl_SYS_brk, __musl_syscall1(), __musl_syscall_ret(), heap_end, NULL, and printf.
Referenced by test_brk().
__musl_syscall1()
static __inline long __musl_syscall1 (long n, long a1) static
Definition at line 95 of file userspace_test.c.
 {
     unsigned long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(n), "D"(a1)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, and n.
Referenced by __libc_sbrk().
__musl_syscall_ret()
long __musl_syscall_ret (unsigned long r)
Definition at line 105 of file userspace_test.c.
 {
     if (r > -4096UL)
     {
         errno = -r;
         return -1;
     }
     return r;
 }
References errno.
Referenced by __libc_sbrk().
create_directory()
char* create_directory ()
Definition at line 506 of file userspace_test.c.
 {
     char *path;
     if (p == NULL)
     {
         path = malloc(20);
         sprintf(path, "/watched_directory");
     }
     else
     {
         path = malloc(strlen(p->pw_dir) + 20);
         sprintf(path, "%s/watched_directory", p->pw_dir);
     }
     if (mkdir(path, 0777) < 0)
     {
         perror("mkdir");
         fflush(stdout);
         fflush(stderr);
         return path;
     }
     return path;
 }
References fflush(), malloc, mkdir(), NULL, p, perror(), passwd::pw_dir, sprintf(), stderr, stdout, and strlen.
Referenced by test_watch_directory().
create_file()
char* create_file ()
Definition at line 477 of file userspace_test.c.
 {
     FILE *fp;
     char *path;
     if (p == NULL)
     {
         path = malloc(20);
         sprintf(path, "/watched_file.txt");
         fp = fopen(path, "w");
     }
     else
     {
         path = malloc(strlen(p->pw_dir) + 20);
         sprintf(path, "%s/watched_file.txt", p->pw_dir);
         fp = fopen(path, "w");
     }
     if (fp == NULL)
     {
         perror("fopen");
         fflush(stdout);
         fflush(stderr);
         return path;
     }
     fclose(fp);
     return path;
 }
References fclose(), fflush(), fopen(), malloc, NULL, p, perror(), passwd::pw_dir, sprintf(), stderr, stdout, and strlen.
Referenced by test_watch_file().
fork_bomb()
void fork_bomb ()
Definition at line 688 of file userspace_test.c.
 {
     while (1)
     {
         printf("[%d] Forking...\n", getpid());
         int pid = fork();
         if (pid != 0)
             printf("[%d] Forked\n", pid);
         else
             printf("[%d] Child\n", getpid());
         sleep(5);
     }
 }
References fork(), getpid(), pid, printf, and sleep().
fork_bomb_syscall()
void fork_bomb_syscall ()
Definition at line 702 of file userspace_test.c.
 {
 #ifdef __x86_64__
     while (1)
     {
         printf("[%d] Forking...\n", getpid());
         unsigned long pid;
         __asm__ __volatile__("syscall" : "=a"(pid)
                              : "a"(57 /* x86_64 SYS_fork */)
                              : "rcx", "r11", "memory");
         if (pid != 0)
             printf("[%ld] Forked\n", pid);
         else
             printf("[%d] Child\n", getpid());
         sleep(5);
     }
 #endif
 }
References __asm__(), getpid(), pid, printf, and sleep().
main()
int main (int argc, char * argv[], char * envp[])
Definition at line 721 of file userspace_test.c.
 {
     if (argv[1] != NULL && strcmp(argv[1], "loop") == 0)
     {
         printf("[%d] Looping...\n", getpid());
         while (1)
             ;
     }
     printf("- Testing userspace...\n");
     // printf("Press RETURN to start tests...\n");
     // char key = 0;
     // while (key != '\n' && key != '\r')
     //  key = getchar();
     // self_fork_exec();
     // fork_bomb();
     // fork_bomb_syscall();
     test_passwd();
     test_brk();
     test_time();
     test_signal();
     test_ptmx();
     test_args(argc, argv, envp);
     // test_stdio();
     test_system();
     test_file();
     test_dirent();
     test_execve_fork();
     test_watch_file();
     test_watch_directory();
     // shutdown_linux();
     // reboot_linux();
     int status = 0;
     pid_t wpid;
     printf("Waiting for child processes to exit...\n");
     while ((wpid = wait(&status)) > 0)
         sleep(2);
     sync();
     printf("Userspace tests complete!\n");
     pid_t pid = fork();
     if (pid < 0)
     {
         perror("fork");
         fflush(stdout);
         fflush(stderr);
         return 1;
     }
     else if (pid == 0)
     {
         printf("Starting utest_linux...\n");
         char *args[] = {"/bin/utest_linux", NULL};
         int ret = execv(args[0], args);
         perror("execv");
         fflush(stdout);
         fflush(stderr);
         return ret;
     }
     waitpid(pid, &status, 0);
     // check if exited normally, or crashed
     if (WIFSIGNALED(status))
     {
         int signal = WTERMSIG(status);
         printf("utest_linux exited with signal: %s\n", strsignal(signal));
         return signal;
     }
     else if (WIFEXITED(status))
     {
         int exitCode = WEXITSTATUS(status);
         if (exitCode != 0)
         {
             printf("utest_linux exited with code: %d\n", exitCode);
             return exitCode;
         }
     }
     else
     {
         printf("utest_linux exited abnormally\n");
         return 1;
     }
     return 0;
 }
References argc, argv, execv(), fflush(), fork(), getpid(), NULL, perror(), pid, printf, signal, sleep(), status, stderr, stdout, strcmp, strsignal(), sync(), test_args(), test_brk(), test_dirent(), test_execve_fork(), test_file(), test_passwd(), test_ptmx(), test_signal(), test_system(), test_time(), test_watch_directory(), test_watch_file(), wait(), waitpid(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
reboot_linux()
void reboot_linux ()
Definition at line 659 of file userspace_test.c.
 {
     printf("- Testing reboot\n");
     sync();
     reboot(RB_AUTOBOOT);
 }
References printf, RB_AUTOBOOT, reboot(), and sync().
self_fork_exec()
void self_fork_exec ()
Definition at line 666 of file userspace_test.c.
 {
     while (1)
     {
         int pid = fork();
         // if (pid >= 10)
         // {
         //  printf("[%d] Forked %d times, exiting...\n", getpid(), pid);
         //  kill(getpid(), SIGTERM);
         // }
         if (pid != 0)
             continue;
         printf("[%d] Executing utest(%d)...\n", getpid(), getppid());
         char *a[] = {"/bin/utest", "loop", NULL};
         int b = execv(a[0], a);
         printf("Failed to execute utest: %d\n", b);
     }
 }
References execv(), fork(), getpid(), getppid(), NULL, pid, and printf.
shutdown_linux()
void shutdown_linux ()
Definition at line 652 of file userspace_test.c.
 {
     printf("- Testing shutdown\n");
     sync();
     reboot(RB_POWER_OFF);
 }
References printf, RB_POWER_OFF, reboot(), and sync().
signalHandler()
void signalHandler (int signo)
Definition at line 372 of file userspace_test.c.
 {
     if (signo == SIGUSR1)
         printf("Signal received\n");
     else
         printf("Unknown signal received %d\n", signo);
     sigRec = 1;
 }
References printf, sigRec, and SIGUSR1.
Referenced by test_signal().
test_args()
void test_args (int argc, char * argv[], char * envp[])
Definition at line 250 of file userspace_test.c.
 {
     printf("- Testing args\n");
     printf("%p %p %p\n",
            (void *)(uintptr_t)&argc,
            (void *)&argv,
            (void *)&envp);
     printf("I have %d arguments\n", argc);
     for (int i = 0; i < argc; i++)
         printf("argv[%d] = (%p) %s\n", i, argv[i], argv[i]);
     int envc = 0;
     while (envp[envc] != NULL)
         envc++;
     printf("I have %d environment variables\n", envc);
     for (int i = 0; i < envc; i++)
         printf("envp[%d] = (%p) %s\n", i, envp[i], envp[i]);
     Elf64_auxv_t *auxv;
     char **e = envp;
     while (*e++ != NULL)
         ;
     for (auxv = (Elf64_auxv_t *)e; auxv->a_type != AT_NULL; auxv++)
         printf("auxv: %ld %#lx\n", auxv->a_type, auxv->a_un.a_val);
 }
References Elf64_auxv_t::a_type, Elf64_auxv_t::a_un, argc, argv, AT_NULL, i, NULL, and printf.
Referenced by main().
test_brk()
void test_brk ()
Definition at line 172 of file userspace_test.c.
 {
     printf("- Testing brk\n");
     void *current_brk = __libc_sbrk(0);
     printf("Initial break address: %p\n", current_brk);
     void *new_brk = __libc_sbrk(0x1000);
     if (new_brk == (void *)-1)
     {
         perror("Error extending heap");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     printf("Heap extended successfully.\n");
     printf("New break address: %p\n", new_brk);
     if (__libc_sbrk(current_brk - new_brk) == (void *)-1)
     {
         perror("Error reducing heap");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     printf("Heap reduced successfully.\n");
     printf("Current break address after reduction: %p\n", __libc_sbrk(0));
     void *extended_brk = __libc_sbrk(0x1000);
     if (extended_brk == (void *)-1)
     {
         perror("Error extending heap after reduction");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     printf("Heap extended successfully after reduction.\n");
     printf("New break address after extension: %p\n", extended_brk);
     __libc_sbrk(-0x1000);
 }
References __libc_sbrk(), fflush(), perror(), printf, stderr, and stdout.
Referenced by main().
test_dirent()
void test_dirent ()
Definition at line 449 of file userspace_test.c.
 {
     printf("- Testing dirent\n");
     DIR *dir;
     struct dirent *entry;
     dir = opendir("/etc");
     if (dir == NULL)
     {
         perror("opendir");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     printf("Contents of the directory:\n");
     int i = 0;
     while ((entry = readdir(dir)) != NULL)
     {
         printf("%s  ", entry->d_name);
         if (++i % 5 == 0)
             printf("\n");
     }
     closedir(dir);
 }
References closedir(), dir, fflush(), i, NULL, opendir(), perror(), printf, readdir(), stderr, and stdout.
Referenced by main().
test_execve_fork()
void test_execve_fork ()
Definition at line 395 of file userspace_test.c.
 {
     printf("- Testing execve and fork\n");
     pid_t pid = fork();
     if (pid == 0) // Child process
     {
         pid_t pid2 = fork();
         if (pid2 == 0) // Child process
         {
             char *shebangArgs[] = {"/test.sh", NULL};
             execv(shebangArgs[0], shebangArgs);
             perror("execv");
             fflush(stdout);
             fflush(stderr);
             exit(EXIT_SUCCESS);
         }
         printf("Creating shell process\n");
         char *args[] = {"/bin/echo", "Hello World from echo!", NULL};
         execv(args[0], args);
         perror("execv");
         fflush(stdout);
         fflush(stderr);
         exit(EXIT_SUCCESS);
     }
     else if (pid > 0)
     {
         printf("Waiting for child process %d to exit\n", pid);
         int status;
         waitpid(pid, &status, 0);
         printf("status=%#x\n", status);
         int exited = WIFEXITED(status);
         if (exited)
         {
             int exitCode = WEXITSTATUS(status);
             if (exitCode != 0)
                 printf("Child process exited with code: %d\n", exitCode);
         }
         else
         {
             printf("Execution failed. (exited=%d, status=%#x)\n", exited, status);
             return;
         }
     }
     else
     {
         perror("fork");
         fflush(stdout);
         fflush(stderr);
         return;
     }
 }
References execv(), exit(), EXIT_SUCCESS, fflush(), fork(), NULL, perror(), pid, printf, status, stderr, stdout, waitpid(), WEXITSTATUS, and WIFEXITED.
Referenced by main().
test_file()
void test_file ()
Definition at line 309 of file userspace_test.c.
 {
     printf("- Testing file operations\n");
     FILE *test = fopen("/etc/passwd", "r");
     if (test == NULL)
     {
         perror("fopen");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     printf("/etc/passwd contents: ");
     char ch;
     while (1)
     {
         ch = fgetc(test);
         if (ch == EOF)
         {
             printf("\n");
             break;
         }
         putchar(ch);
     }
     fclose(test);
 }
References EOF, fclose(), fflush(), fgetc, fopen(), NULL, perror(), printf, putchar, stderr, stdout, and test.
Referenced by main().
test_passwd()
void test_passwd ()
Definition at line 117 of file userspace_test.c.
 {
     printf("- Testing passwd\n");
     p = getpwuid(getuid());
     if (p == NULL)
     {
         perror("getpwuid");
         fflush(stdout);
         fflush(stderr);
     }
     else
     {
         printf("name: %s\n", p->pw_name);
         printf("passwd: %s\n", p->pw_passwd);
         printf("uid: %d\n", p->pw_uid);
         printf("gid: %d\n", p->pw_gid);
         printf("gecos: %s\n", p->pw_gecos);
         printf("dir: %s\n", p->pw_dir);
         printf("shell: %s\n", p->pw_shell);
     }
 }
References fflush(), getpwuid, getuid, NULL, p, perror(), printf, passwd::pw_dir, passwd::pw_gecos, passwd::pw_gid, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, stderr, and stdout.
Referenced by main().
test_ptmx()
void test_ptmx ()
Definition at line 337 of file userspace_test.c.
 {
     printf("- Testing PTMX\n");
     int master, slave;
     char buffer[256];
     if (openpty(&master, &slave, NULL, NULL, NULL) == -1)
     {
         perror("openpty");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     write(master, "Hello, pty!\n", 12);
     ssize_t bytesRead = read(slave, buffer, sizeof(buffer));
     if (bytesRead > 0)
     {
         buffer[bytesRead] = '\0';
         printf("Received from pty: %s", buffer);
     }
     close(master);
     close(slave);
 }
References close(), fflush(), master, NULL, openpty(), perror(), printf, read(), slave, stderr, stdout, and write().
Referenced by main().
test_signal()
void test_signal ()
Definition at line 381 of file userspace_test.c.
 {
     printf("- Testing Signals\n");
     signal(SIGUSR1, signalHandler);
     signal(SIGUSR2, signalHandler);
     printf("Sending SIGUSR1...\n");
     kill(getpid(), SIGUSR1);
     printf("Sending SIGUSR2...\n");
     kill(getpid(), SIGUSR2);
     printf("Signal sent\n");
     while (!sigRec)
         sleep(1);
 }
References getpid(), kill(), printf, signal, signalHandler(), sigRec, SIGUSR1, SIGUSR2, and sleep().
Referenced by main().
test_stdio()
void test_stdio ()
Definition at line 281 of file userspace_test.c.
 {
     printf("- Testing stdin\n");
     pid_t pid = fork();
     if (pid < 0)
     {
         perror("fork");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     else if (pid != 0)
         return;
     printf("Type a character: ");
     char c = getchar();
     printf("You typed: %c (%#x)\n", c, c);
     char *line = NULL;
     size_t len = 0;
     ssize_t read;
     printf("Type a line: ");
     read = getline(&line, &len, stdin);
     printf("You typed: %s (%ld bytes)\n", line, read);
     free(line);
     exit(EXIT_SUCCESS);
 }
References c, exit(), EXIT_SUCCESS, fflush(), fork(), free, getchar, getline(), len, NULL, perror(), pid, printf, read(), stderr, stdin, and stdout.
test_system()
void test_system ()
Definition at line 364 of file userspace_test.c.
 {
     printf("- Testing system()\n");
     int ret = system("echo Hello, world!");
     printf("system() returned %d\n", ret);
 }
References printf, and system().
Referenced by main().
test_time()
void test_time ()
Definition at line 217 of file userspace_test.c.
 {
     printf("- Testing time\n");
     struct tm time = {0};
     int Year = 2024;
     int Month = 1;
     int Day = 1;
     int Hour = 0;
     int Minute = 0;
     int Second = 0;
     time.tm_year = Year - 1900;
     time.tm_mon = Month - 1;
     time.tm_mday = Day;
     time.tm_hour = Hour;
     time.tm_min = Minute;
     time.tm_sec = Second;
     if (time.tm_year < 0)
         time.tm_year = 0;
     time_t t = mktime(&time);
     if (t != (time_t)-1)
         stime(&t);
     else
     {
         perror("mktime");
         fflush(stdout);
         fflush(stderr);
     }
 }
References fflush(), mktime(), perror(), printf, stderr, stdout, stime(), t, and time().
Referenced by main().
test_watch_directory()
void test_watch_directory ()
Definition at line 591 of file userspace_test.c.
 {
     printf("- Testing directory watching\n");
     pid_t pid = fork();
     if (pid < 0)
     {
         perror("fork");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     else if (pid != 0)
         return;
     char *path = create_directory();
     int fd, wd;
     char *buffer = malloc(BUF_LEN);
     fd = inotify_init();
     if (fd < 0)
     {
         perror("inotify_init");
         exit(EXIT_FAILURE);
     }
     wd = inotify_add_watch(fd, path,
                            IN_OPEN | IN_CREATE | IN_DELETE | IN_MODIFY);
     if (wd < 0)
     {
         perror("inotify_add_watch");
         exit(EXIT_FAILURE);
     }
     printf("Watching for changes in the directory...\n");
     while (1)
     {
         ssize_t len = read(fd, buffer, BUF_LEN);
         if (len < 0)
         {
             perror("read");
             exit(EXIT_FAILURE);
         }
         struct inotify_event *event = (struct inotify_event *)buffer;
         if (event->mask & IN_CREATE)
             printf("File created: %s\n", event->name);
         else if (event->mask & IN_DELETE)
             printf("File deleted: %s\n", event->name);
         else if (event->mask & IN_MODIFY)
             printf("File modified: %s\n", event->name);
         else if (event->mask & IN_OPEN)
             printf("File opened: %s\n", event->name);
         else
             printf("Unknown event!\n");
     }
     inotify_rm_watch(fd, wd);
     close(fd);
     exit(EXIT_SUCCESS);
 }
References BUF_LEN, close(), create_directory(), exit(), EXIT_FAILURE, EXIT_SUCCESS, fd, fflush(), fork(), IN_CREATE, IN_DELETE, IN_MODIFY, IN_OPEN, inotify_add_watch(), inotify_init(), inotify_rm_watch(), len, malloc, perror(), pid, printf, read(), stderr, stdout, and inotify_event::wd.
Referenced by main().
test_watch_file()
void test_watch_file ()
Definition at line 531 of file userspace_test.c.
 {
     printf("- Testing file watching\n");
     pid_t pid = fork();
     if (pid < 0)
     {
         perror("fork");
         fflush(stdout);
         fflush(stderr);
         return;
     }
     else if (pid != 0)
         return;
     char *path = create_file();
     int fd, wd;
     char *buffer = malloc(BUF_LEN);
     fd = inotify_init();
     if (fd < 0)
     {
         perror("inotify_init");
         exit(EXIT_FAILURE);
     }
     wd = inotify_add_watch(fd, path,
                            IN_OPEN | IN_MODIFY | IN_CLOSE);
     if (wd < 0)
     {
         perror("inotify_add_watch");
         exit(EXIT_FAILURE);
     }
     printf("Watching for changes in file.txt...\n");
     while (1)
     {
         ssize_t len = read(fd, buffer, BUF_LEN);
         if (len < 0)
         {
             perror("read");
             exit(EXIT_FAILURE);
         }
         struct inotify_event *event = (struct inotify_event *)buffer;
         if (event->mask & IN_MODIFY)
             printf("File modified!\n");
         else if (event->mask & IN_OPEN)
             printf("File opened!\n");
         else if (event->mask & IN_CLOSE)
             printf("File closed!\n");
         else
             printf("Unknown event!\n");
     }
     inotify_rm_watch(fd, wd);
     close(fd);
     exit(EXIT_SUCCESS);
 }
References BUF_LEN, close(), create_file(), exit(), EXIT_FAILURE, EXIT_SUCCESS, fd, fflush(), fork(), IN_CLOSE, IN_MODIFY, IN_OPEN, inotify_add_watch(), inotify_init(), inotify_rm_watch(), len, malloc, perror(), pid, printf, read(), stderr, stdout, and inotify_event::wd.
Referenced by main().
Variable Documentation
heap_end
void* heap_end = NULL static
Definition at line 140 of file userspace_test.c.
Referenced by __libc_sbrk().
p
struct passwd* p = NULL
Definition at line 115 of file userspace_test.c.
Referenced by create_directory(), create_file(), and test_passwd().
sigRec
int sigRec = 0
Definition at line 371 of file userspace_test.c.
Referenced by signalHandler(), and test_signal().