Fennix: Userspace/apps/base/bash/examples/loadables/fdflags.c File Reference
fdflags.c File Reference
#include <config.h>
#include <fcntl.h>
#include <errno.h>
#include "bashansi.h"
#include <stdio.h>
#include "loadables.h"
Macros
#define FD_CLOEXEC 1
#define O_APPEND 0
#define O_ASYNC 0
#define O_SYNC 0
#define O_NONBLOCK 0
#define O_FSYNC 0
#define O_DSYNC 0
#define O_RSYNC 0
#define O_ALT_IO 0
#define O_DIRECT 0
#define O_NOATIME 0
#define O_NOSIGPIPE 0
#define ALLFLAGS
#define O_CLOEXEC ((~ALLFLAGS) ^ ((~ALLFLAGS) & ((~ALLFLAGS) - 1)))
#define N_FLAGS (sizeof (file_flags) / sizeof (file_flags[0]))
Functions
static int getallflags ()
static int getflags (int fd, int p)
static void printone (int fd, int p, int verbose)
static int parseflags (char *s, int *p, int *n)
static void setone (int fd, char *v, int verbose)
static int getmaxfd ()
int fdflags_builtin (WORD_LIST *list)
Variables
struct {
const char * name
int value
} file_flags []
int errno
char * fdflags_doc []
struct builtin fdflags_struct
Macro Definition Documentation
ALLFLAGS
#define ALLFLAGS
Value:
    (O_APPEND|O_ASYNC|O_SYNC|O_NONBLOCK|O_FSYNC|O_DSYNC|\
    O_RSYNC|O_ALT_IO|O_DIRECT|O_NOATIME|O_NOSIGPIPE)
FD_CLOEXEC
#define FD_CLOEXEC 1
Definition at line 36 of file fdflags.c.
N_FLAGS
#define N_FLAGS (sizeof (file_flags) / sizeof (file_flags[0]))
Definition at line 115 of file fdflags.c.
O_ALT_IO
#define O_ALT_IO 0
O_APPEND
#define O_APPEND 0
O_ASYNC
#define O_ASYNC 0
O_CLOEXEC
#define O_CLOEXEC ((~ALLFLAGS) ^ ((~ALLFLAGS) & ((~ALLFLAGS) - 1)))
O_DIRECT
#define O_DIRECT 0
O_DSYNC
#define O_DSYNC 0
O_FSYNC
#define O_FSYNC 0
O_NOATIME
#define O_NOATIME 0
O_NONBLOCK
#define O_NONBLOCK 0
O_NOSIGPIPE
#define O_NOSIGPIPE 0
O_RSYNC
#define O_RSYNC 0
O_SYNC
#define O_SYNC 0
Function Documentation
fdflags_builtin()
int fdflags_builtin (WORD_LIST * list)
Definition at line 281 of file fdflags.c.
 {
   int opt, maxfd, i, num, verbose, setflag;
   char *setspec;
   WORD_LIST *l;
   intmax_t inum;
   setflag = verbose = 0;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "s:v")) != -1)
     {
       switch (opt)
     {
     case 's':
       setflag = 1;
       setspec = list_optarg;
       break;
     case 'v':
       verbose = 1;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   /* Maybe we could provide some default here, but we don't yet. */
   if (list == 0 && setflag)
     return (EXECUTION_SUCCESS);
   if (list == 0)
     {
       maxfd = getmaxfd ();
       if (maxfd < 0)
     {
       builtin_error ("can't get max fd: %s", strerror (errno));
       return (EXECUTION_FAILURE);
     }
       for (i = 0; i < maxfd; i++)
     printone (i, 0, verbose);
       return (EXECUTION_SUCCESS);
     }
   opt = EXECUTION_SUCCESS;
   for (l = list; l; l = l->next)
     {
       if (legal_number (l->word->word, &inum) == 0 || inum < 0)
     {
       builtin_error ("%s: invalid file descriptor", l->word->word);
       opt = EXECUTION_FAILURE;
       continue;
     }
       num = inum;       /* truncate to int */
       if (setflag)
     setone (num, setspec, verbose);
       else
     printone (num, 1, verbose);
     }
   return (opt);
 }
References builtin_error(), builtin_usage(), CASE_HELPOPT, errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, getmaxfd(), i, internal_getopt(), l, legal_number(), list(), list_optarg, loptend, num, opt, printone(), reset_internal_getopt(), setone(), strerror(), and verbose.
getallflags()
static int getallflags () static
Definition at line 123 of file fdflags.c.
 {
   int i, allflags;
   for (i = allflags = 0; i < N_FLAGS; i++)
     allflags |= file_flags[i].value;
   return allflags;
 }
References file_flags, i, N_FLAGS, and value.
Referenced by getflags().
getflags()
static int getflags (int fd, int p) static
Definition at line 133 of file fdflags.c.
 {
   int c, f;
   int allflags;
   if ((c = fcntl(fd, F_GETFD)) == -1)
     {
       if (p)
     builtin_error("can't get status for fd %d: %s", fd, strerror(errno));
       return -1;
     }
   if ((f = fcntl(fd, F_GETFL)) == -1)
     {
       if (p)
     builtin_error("Can't get flags for fd %d: %s", fd, strerror(errno));
       return -1;
     }
   if (c)
     f |= O_CLOEXEC;
   return f & getallflags();
 }
References builtin_error(), c, errno, f, F_GETFD, F_GETFL, fcntl(), fd, getallflags(), O_CLOEXEC, p, and strerror().
Referenced by printone(), and setone().
getmaxfd()
static int getmaxfd () static
Definition at line 260 of file fdflags.c.
 {
   int maxfd, ignore;
 #ifdef F_MAXFD
   maxfd = fcntl (0, F_MAXFD);
   if (maxfd > 0)
     return maxfd;
 #endif
   maxfd = getdtablesize ();
   if (maxfd <= 0)
     maxfd = HIGH_FD_MAX;
   for (maxfd--; maxfd > 0; maxfd--)
     if (fcntl (maxfd, F_GETFD, &ignore) != -1)
       break;
   return maxfd;
 }
References F_GETFD, fcntl(), getdtablesize(), HIGH_FD_MAX, and ignore().
Referenced by fdflags_builtin().
parseflags()
static int parseflags (char * s, int * p, int * n) static
Definition at line 188 of file fdflags.c.
 {
   int f, *v;
   size_t i;
   f = 0;
   *p = *n = 0;
   for (s = strtok(s, ","); s; s = strtok(NULL, ","))
     {
       switch (*s)
         {
     case '+':
       v = p;
       s++;
       break;
     case '-':
       v = n;
       s++;
       break;
     default:
       v = &f;
       break;
     }
       for (i = 0; i < N_FLAGS; i++)
     if (strcmp(s, file_flags[i].name) == 0)
       {
         *v |= file_flags[i].value;
         break;
       }
       if (i == N_FLAGS)
     builtin_error("invalid flag `%s'", s);
     }
   return f;
 }
References builtin_error(), f, file_flags, i, n, N_FLAGS, NULL, p, s, strcmp, and strtok().
Referenced by setone().
printone()
static void printone (int fd, int p, int verbose) static
Definition at line 159 of file fdflags.c.
 {
   int f;
   size_t i;
   if ((f = getflags(fd, p)) == -1)
     return;
   printf ("%d:", fd);
   for (i = 0; i < N_FLAGS; i++)
     {
       if (f & file_flags[i].value)
     {
       printf ("%s%s", verbose ? "+" : "", file_flags[i].name);
       f &= ~file_flags[i].value;
     }
       else if (verbose)
     printf ( "-%s", file_flags[i].name);
       else
     continue;
       if (f || (verbose && i != N_FLAGS - 1))
     putchar (',');
     }
   printf ("\n");
 }
References f, fd, file_flags, getflags(), i, N_FLAGS, p, printf, putchar, value, and verbose.
Referenced by fdflags_builtin().
setone()
static void setone (int fd, char * v, int verbose) static
Definition at line 227 of file fdflags.c.
 {
   int f, n, pos, neg, cloexec;
   f = getflags(fd, 1);
   if (f == -1)
     return;
   parseflags(v, &pos, &neg);
   cloexec = -1;
   if ((pos & O_CLOEXEC) && (f & O_CLOEXEC) == 0)
     cloexec = FD_CLOEXEC;
   if ((neg & O_CLOEXEC) && (f & O_CLOEXEC))
     cloexec = 0;
   if (cloexec != -1 && fcntl(fd, F_SETFD, cloexec) == -1)
     builtin_error("can't set status for fd %d: %s", fd, strerror(errno));
   pos &= ~O_CLOEXEC;
   neg &= ~O_CLOEXEC;
   f &= ~O_CLOEXEC;
   n = f;
   n |= pos;
   n &= ~neg;
   if (n != f && fcntl(fd, F_SETFL, n) == -1)
     builtin_error("can't set flags for fd %d: %s", fd, strerror(errno));
 }
References builtin_error(), errno, f, F_SETFD, F_SETFL, fcntl(), fd, FD_CLOEXEC, getflags(), n, O_CLOEXEC, parseflags(), pos, and strerror().
Referenced by fdflags_builtin().
Variable Documentation
errno
int errno extern
Referenced by fdflags_builtin(), getflags(), and setone().
fdflags_doc
char* fdflags_doc[]
Initial value:
=
{
  "Display and modify file descriptor flags.",
  "",
  "Display or, if the -s option is supplied, set flags for each file",
  "descriptor supplied as an argument.  If the -v option is supplied,",
  "the display is verbose, including each settable option name in the",
  "form of a string such as that accepted by the -s option.",
  "",
  "The -s option accepts a string with a list of flag names, each preceded",
  "by a `+' (set) or `-' (unset).  Those changes are applied to each file",
  "descriptor supplied as an argument.",
  "",
  "If no file descriptor arguments are supplied, the displayed information",
  "consists of the status of flags for each of the shell's open files.",
  (char *)NULL
}
Definition at line 346 of file fdflags.c.
fdflags_struct
struct builtin fdflags_struct
Initial value:
= {
    "fdflags",
    fdflags_builtin,
    BUILTIN_ENABLED,
    fdflags_doc,
    "fdflags [-v] [-s flags_string] [fd ...]",
    0
}
Definition at line 346 of file fdflags.c.
const { ... } file_flags[]
Referenced by getallflags(), parseflags(), and printone().