Fennix: Userspace/apps/base/busybox/archival/libarchive/bz/bzlib.c File Reference
bzlib.c File Reference
Macros
#define ADD_CHAR_TO_BLOCK(zs, zchh0)
Functions
static void prepare_new_block (EState *s)
static ALWAYS_INLINE void init_RL (EState *s)
static int isempty_RL (EState *s)
static void BZ2_bzCompressInit (bz_stream *strm, int blockSize100k)
static void add_pair_to_block (EState *s)
static void flush_RL (EState *s)
static void copy_input_until_stop (EState *s)
static void copy_output_until_stop (EState *s)
static void handle_compress (bz_stream *strm)
static int BZ2_bzCompress (bz_stream *strm, int action)
static void BZ2_bzCompressEnd (bz_stream *strm)
Macro Definition Documentation
ADD_CHAR_TO_BLOCK
#define ADD_CHAR_TO_BLOCK (zs, zchh0)
Value:
{ \
    uint32_t zchh = (uint32_t)(zchh0); \
    /*-- fast track the common case --*/ \
    if (zchh != zs->state_in_ch && zs->state_in_len == 1) { \
        uint8_t ch = (uint8_t)(zs->state_in_ch); \
        BZ_UPDATE_CRC(zs, zs->blockCRC, ch); \
        zs->inUse[zs->state_in_ch] = 1; \
        zs->block[zs->nblock] = (uint8_t)ch; \
        zs->nblock++; \
        zs->state_in_ch = zchh; \
    } \
    else \
    /*-- general, uncommon cases --*/ \
    if (zchh != zs->state_in_ch || zs->state_in_len == 255) { \
        if (zs->state_in_ch < 256) \
            add_pair_to_block(zs); \
        zs->state_in_ch = zchh; \
        zs->state_in_len = 1; \
    } else { \
        zs->state_in_len++; \
    } \
}
Definition at line 161 of file bzlib.c.
Function Documentation
add_pair_to_block()
static void add_pair_to_block (EState * s) static
Definition at line 120 of file bzlib.c.
 {
     int32_t i;
     uint8_t ch = (uint8_t)(s->state_in_ch);
     for (i = 0; i < s->state_in_len; i++) {
         BZ_UPDATE_CRC(s, s->blockCRC, ch);
     }
     s->inUse[s->state_in_ch] = 1;
     switch (s->state_in_len) {
         case 3:
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             /* fall through */
         case 2:
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             /* fall through */
         case 1:
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             break;
         default:
             s->inUse[s->state_in_len - 4] = 1;
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             s->block[s->nblock] = (uint8_t)ch; s->nblock++;
             s->block[s->nblock] = (uint8_t)(s->state_in_len - 4);
             s->nblock++;
             break;
     }
 }
References BZ_UPDATE_CRC, i, and s.
Referenced by flush_RL().
BZ2_bzCompress()
static int BZ2_bzCompress (bz_stream * strm, int action) static
Definition at line 303 of file bzlib.c.
 {
     /*Bool progress;*/
     EState* s;
     s = strm->state;
     switch (s->mode) {
         case BZ_M_RUNNING:
             if (action == BZ_RUN) {
                 /*progress =*/ handle_compress(strm);
                 /*return progress ? BZ_RUN_OK : BZ_PARAM_ERROR;*/
                 return BZ_RUN_OK;
             }
 #ifdef FLUSH_IS_UNUSED
             else
             if (action == BZ_FLUSH) {
                 //#s->avail_in_expect = strm->avail_in;
                 s->mode = BZ_M_FLUSHING;
                 goto case_BZ_M_FLUSHING;
             }
 #endif
             else
             /*if (action == BZ_FINISH)*/ {
                 //#s->avail_in_expect = strm->avail_in;
                 s->mode = BZ_M_FINISHING;
                 goto case_BZ_M_FINISHING;
             }
 #ifdef FLUSH_IS_UNUSED
  case_BZ_M_FLUSHING:
         case BZ_M_FLUSHING:
             /*if (s->avail_in_expect != s->strm->avail_in)
                 return BZ_SEQUENCE_ERROR;*/
             /*progress =*/ handle_compress(strm);
             if (s->avail_in_expect > 0 || !isempty_RL(s) || s->state_out_pos < s->posZ)
                 return BZ_FLUSH_OK;
             s->mode = BZ_M_RUNNING;
             return BZ_RUN_OK;
 #endif
  case_BZ_M_FINISHING:
         /*case BZ_M_FINISHING:*/
         default:
             /*if (s->avail_in_expect != s->strm->avail_in)
                 return BZ_SEQUENCE_ERROR;*/
             /*progress =*/ handle_compress(strm);
             /*if (!progress) return BZ_SEQUENCE_ERROR;*/
             //#if (s->avail_in_expect > 0 || !isempty_RL(s) || s->state_out_pos < s->posZ)
             //# return BZ_FINISH_OK;
             if (s->strm->avail_in > 0 || !isempty_RL(s) || s->state_out_pos < s->posZ)
                 return BZ_FINISH_OK;
             /*s->mode = BZ_M_IDLE;*/
             return BZ_STREAM_END;
     }
     /* return BZ_OK; --not reached--*/
 }
References BZ_FINISH_OK, BZ_FLUSH, BZ_FLUSH_OK, BZ_M_FINISHING, BZ_M_FLUSHING, BZ_M_RUNNING, BZ_RUN, BZ_RUN_OK, BZ_STREAM_END, handle_compress(), isempty_RL(), s, and strm.
Referenced by IF_DESKTOP().
BZ2_bzCompressEnd()
static void BZ2_bzCompressEnd (bz_stream * strm) static
Definition at line 364 of file bzlib.c.
 {
     EState* s;
     s = strm->state;
     free(s->arr1);
     free(s->arr2);
     //free(s->ftab);       // made it array member of s
     //free(s->crc32table); // ditto
     free(s);
 }
References free, s, and strm.
BZ2_bzCompressInit()
static void BZ2_bzCompressInit (bz_stream * strm, int blockSize100k) static
Definition at line 88 of file bzlib.c.
 {
     unsigned n;
     EState* s;
     s = xzalloc(sizeof(EState));
     s->strm = strm;
     n        = 100000 * blockSize100k;
     s->arr1  = xmalloc(n                    * sizeof(uint32_t));
     s->mtfv  = (uint16_t*)s->arr1;
     s->ptr   = (uint32_t*)s->arr1;
     s->arr2  = xmalloc((n + BZ_N_OVERSHOOT) * sizeof(uint32_t));
     s->block = (uint8_t*)s->arr2;
     crc32_filltable(s->crc32table, 1);
     s->state             = BZ_S_INPUT;
     s->mode              = BZ_M_RUNNING;
     s->blockSize100k     = blockSize100k;
     s->nblockMAX         = n - 19;
     strm->state          = s;
     /*strm->total_in     = 0;*/
     strm->total_out      = 0;
     init_RL(s);
     prepare_new_block(s);
 }
References BZ_M_RUNNING, BZ_N_OVERSHOOT, BZ_S_INPUT, crc32_filltable(), init_RL(), n, prepare_new_block(), s, strm, xmalloc, and xzalloc().
copy_input_until_stop()
static void copy_input_until_stop (EState * s) static
Definition at line 188 of file bzlib.c.
 {
     /*Bool progress_in = False;*/
 #ifdef SAME_CODE_AS_BELOW
     if (s->mode == BZ_M_RUNNING) {
         /*-- fast track the common case --*/
         while (1) {
             /*-- no input? --*/
             if (s->strm->avail_in == 0) break;
             /*-- block full? --*/
             if (s->nblock >= s->nblockMAX) break;
             /*progress_in = True;*/
             ADD_CHAR_TO_BLOCK(s, (uint32_t)(*(uint8_t*)(s->strm->next_in)));
             s->strm->next_in++;
             s->strm->avail_in--;
             /*s->strm->total_in++;*/
         }
     } else
 #endif
     {
         /*-- general, uncommon case --*/
         while (1) {
             /*-- no input? --*/
             if (s->strm->avail_in == 0) break;
             /*-- block full? --*/
             if (s->nblock >= s->nblockMAX) break;
         //# /*-- flush/finish end? --*/
         //# if (s->avail_in_expect == 0) break;
             /*progress_in = True;*/
             ADD_CHAR_TO_BLOCK(s, *(uint8_t*)(s->strm->next_in));
             s->strm->next_in++;
             s->strm->avail_in--;
             /*s->strm->total_in++;*/
         //# s->avail_in_expect--;
         }
     }
     /*return progress_in;*/
 }
References ADD_CHAR_TO_BLOCK, BZ_M_RUNNING, and s.
Referenced by handle_compress().
copy_output_until_stop()
static void copy_output_until_stop (EState * s) static
Definition at line 231 of file bzlib.c.
 {
     /*Bool progress_out = False;*/
     while (1) {
         /*-- no output space? --*/
         if (s->strm->avail_out == 0) break;
         /*-- block done? --*/
         if (s->state_out_pos >= s->posZ) break;
         /*progress_out = True;*/
         *(s->strm->next_out) = *s->state_out_pos++;
         s->strm->avail_out--;
         s->strm->next_out++;
         s->strm->total_out++;
     }
     /*return progress_out;*/
 }
References s.
Referenced by handle_compress().
flush_RL()
static void flush_RL (EState * s) static
Definition at line 153 of file bzlib.c.
 {
     if (s->state_in_ch < 256) add_pair_to_block(s);
     init_RL(s);
 }
References add_pair_to_block(), init_RL(), and s.
Referenced by handle_compress().
handle_compress()
static void handle_compress (bz_stream * strm) static
Definition at line 254 of file bzlib.c.
 {
     /*Bool progress_in  = False;*/
     /*Bool progress_out = False;*/
     EState* s = strm->state;
     while (1) {
         if (s->state == BZ_S_OUTPUT) {
             /*progress_out |=*/ copy_output_until_stop(s);
             if (s->state_out_pos < s->posZ) break;
             if (s->mode == BZ_M_FINISHING
             //# && s->avail_in_expect == 0
              && s->strm->avail_in == 0
              && isempty_RL(s))
                 break;
             prepare_new_block(s);
             s->state = BZ_S_INPUT;
 #ifdef FLUSH_IS_UNUSED
             if (s->mode == BZ_M_FLUSHING
              && s->avail_in_expect == 0
              && isempty_RL(s))
                 break;
 #endif
         }
         if (s->state == BZ_S_INPUT) {
             /*progress_in |=*/ copy_input_until_stop(s);
             //#if (s->mode != BZ_M_RUNNING && s->avail_in_expect == 0) {
             if (s->mode != BZ_M_RUNNING && s->strm->avail_in == 0) {
                 flush_RL(s);
                 BZ2_compressBlock(s, (s->mode == BZ_M_FINISHING));
                 s->state = BZ_S_OUTPUT;
             } else
             if (s->nblock >= s->nblockMAX) {
                 BZ2_compressBlock(s, 0);
                 s->state = BZ_S_OUTPUT;
             } else
             if (s->strm->avail_in == 0) {
                 break;
             }
         }
     }
     /*return progress_in || progress_out;*/
 }
References BZ2_compressBlock(), BZ_M_FINISHING, BZ_M_FLUSHING, BZ_M_RUNNING, BZ_S_INPUT, BZ_S_OUTPUT, copy_input_until_stop(), copy_output_until_stop(), flush_RL(), isempty_RL(), prepare_new_block(), s, and strm.
Referenced by BZ2_bzCompress().
init_RL()
static ALWAYS_INLINE void init_RL (EState * s) static
Definition at line 72 of file bzlib.c.
 {
     s->state_in_ch = 256;
     s->state_in_len = 0;
 }
References s.
Referenced by BZ2_bzCompressInit(), and flush_RL().
isempty_RL()
static int isempty_RL (EState * s) static
Definition at line 80 of file bzlib.c.
 {
     return (s->state_in_ch >= 256 || s->state_in_len <= 0);
 }
References s.
Referenced by BZ2_bzCompress(), and handle_compress().
prepare_new_block()
static void prepare_new_block (EState * s) static
Definition at line 54 of file bzlib.c.
 {
     int i;
     s->nblock = 0;
     //indexes into s->zbits[], initialzation moved to init of s->zbits
     //s->posZ = s->zbits; // was: s->numZ = 0;
     //s->state_out_pos = s->zbits;
     BZ_INITIALISE_CRC(s->blockCRC);
     /* inlined memset would be nice to have here */
     for (i = 0; i < 256; i++)
         s->inUse[i] = 0;
     s->blockNo++;
 }
References BZ_INITIALISE_CRC, i, and s.
Referenced by BZ2_bzCompressInit(), and handle_compress().