Fennix: Userspace/apps/base/busybox/util-linux/volume_id/erofs.c File Reference
erofs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct erofs_super_block
Macros
#define EROFS_SUPER_MAGIC_V1 0xE0F5E1E2
#define EROFS_SUPER_OFFSET 1024
#define EROFS_FEATURE_COMPAT_SB_CHKSUM 0x00000001
Functions
int FAST_FUNC volume_id_probe_erofs (struct volume_id *id)
Variables
struct erofs_super_block PACKED
Data Structure Documentation
erofs_super_block
struct erofs_super_block
Definition at line 24 of file erofs.c.
Data Fields
uint8_t blkszbits
uint32_t blocks
uint64_t build_time
uint32_t build_time_nsec
uint32_t checksum
uint32_t feature_compat
uint32_t feature_incompat
uint64_t inos
uint32_t magic
uint32_t meta_blkaddr
uint8_t reserved
uint8_t reserved2[44]
uint16_t root_nid
uint8_t uuid[16]
uint8_t volume_name[16]
uint32_t xattr_blkaddr
Macro Definition Documentation
EROFS_FEATURE_COMPAT_SB_CHKSUM
#define EROFS_FEATURE_COMPAT_SB_CHKSUM 0x00000001
Definition at line 21 of file erofs.c.
EROFS_SUPER_MAGIC_V1
#define EROFS_SUPER_MAGIC_V1 0xE0F5E1E2
Definition at line 19 of file erofs.c.
EROFS_SUPER_OFFSET
#define EROFS_SUPER_OFFSET 1024
Definition at line 20 of file erofs.c.
Function Documentation
volume_id_probe_erofs()
int FAST_FUNC volume_id_probe_erofs (struct volume_id * id)
Definition at line 45 of file erofs.c.
 {
     struct erofs_super_block *sb;
     BUILD_BUG_ON(sizeof(struct erofs_super_block) != 128);
     dbg("erofs: probing at offset 0x%llx", EROFS_SUPER_OFFSET);
     sb = volume_id_get_buffer(id, EROFS_SUPER_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (sb->magic != cpu_to_le32(EROFS_SUPER_MAGIC_V1))
         return -1;
     IF_FEATURE_BLKID_TYPE(id->type = "erofs");
     volume_id_set_label_string(id, sb->volume_name,
         MIN(sizeof(sb->volume_name), VOLUME_ID_LABEL_SIZE));
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     return 0;
 }
References BUILD_BUG_ON, cpu_to_le32, dbg, EROFS_SUPER_MAGIC_V1, EROFS_SUPER_OFFSET, erofs_super_block::magic, MIN, erofs_super_block::uuid, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), volume_id_set_uuid(), and erofs_super_block::volume_name.
Variable Documentation
PACKED
struct erofs_super_block PACKED