Fennix: Userspace/musl/include/netinet/ether.h File Reference
ether.h File Reference
#include <netinet/if_ether.h>
Functions
char * ether_ntoa (const struct ether_addr *)
struct ether_addr * ether_aton (const char *)
char * ether_ntoa_r (const struct ether_addr *, char *)
struct ether_addr * ether_aton_r (const char *, struct ether_addr *)
int ether_line (const char *, struct ether_addr *, char *)
int ether_ntohost (char *, const struct ether_addr *)
int ether_hostton (const char *, struct ether_addr *)
Function Documentation
ether_aton()
struct ether_addr* ether_aton (const char * x)
Definition at line 25 of file ether.c.
 {
     static struct ether_addr a;
     return ether_aton_r (x, &a);
 }
References ether_aton_r(), and x.
ether_aton_r()
struct ether_addr* ether_aton_r (const char * x, struct ether_addr * p_a)
Definition at line 5 of file ether.c.
 {
     struct ether_addr a;
     char *y;
     for (int ii = 0; ii < 6; ii++) {
         unsigned long int n;
         if (ii != 0) {
             if (x[0] != ':') return 0; /* bad format */
             else x++;
         }
         n = strtoul (x, &y, 16);
         x = y;
         if (n > 0xFF) return 0; /* bad byte */
         a.ether_addr_octet[ii] = n;
     }
     if (x[0] != 0) return 0; /* bad format */
     *p_a = a;
     return p_a;
 }
References ether_addr::ether_addr_octet, n, strtoul(), x, and y.
Referenced by ether_aton(), get_dest_addr(), nameif_parse_selector(), and read_staticlease().
ether_hostton()
int ether_hostton (const char * hostname, struct ether_addr * e)
Definition at line 55 of file ether.c.
 {
     return -1;
 }
Referenced by get_dest_addr().
ether_line()
int ether_line (const char * l, struct ether_addr * e, char * hostname)
Definition at line 45 of file ether.c.
 {
     return -1;
 }
ether_ntoa()
char* ether_ntoa (const struct ether_addr * p_a)
Definition at line 40 of file ether.c.
{
     static char x[18];
     return ether_ntoa_r (p_a, x);
 }
References ether_ntoa_r(), and x.
Referenced by get_dest_addr().
ether_ntoa_r()
char* ether_ntoa_r (const struct ether_addr * p_a, char * x)
Definition at line 31 of file ether.c.
{
     char *y;
     y = x;
     for (int ii = 0; ii < 6; ii++) {
         x += sprintf (x, ii == 0 ? "%.2X" : ":%.2X", p_a->ether_addr_octet[ii]);
     }
     return y;
 }
References ether_addr::ether_addr_octet, sprintf(), x, and y.
Referenced by ether_ntoa().
ether_ntohost()
int ether_ntohost (char * hostname, const struct ether_addr * e)
Definition at line 50 of file ether.c.
 {
     return -1;
 }