Fennix: Drivers/library/vm.c File Reference
vm.c File Reference
#include <vm.h>
Functions
int __strcmp (const char *l, const char *r)
void __cpuid (uint32_t Function, uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
bool __CheckHypervisorBit ()
bool __VMwareBackdoorHypervisors ()
bool IsVMwareBackdoorAvailable ()
Function Documentation
__CheckHypervisorBit()
bool __CheckHypervisorBit ()
Definition at line 37 of file vm.c.
 {
     uint32_t eax, ebx, ecx, edx;
     __cpuid(0x1, &eax, &ebx, &ecx, &edx);
     if (!(ecx & (1 << 31)))
         return false; /* Hypervisor not detected */
     return true;
 }
References __cpuid().
Referenced by IsVMwareBackdoorAvailable().
__cpuid()
void __cpuid (uint32_t Function, uint32_t * eax, uint32_t * ebx, uint32_t * ecx, uint32_t * edx)
Definition at line 28 of file vm.c.
 {
     asmv("cpuid"
          : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx)
          : "a"(Function));
 }
References asmv().
Referenced by __CheckHypervisorBit(), and __VMwareBackdoorHypervisors().
__strcmp()
int __strcmp (const char * l, const char * r)
Definition at line 20 of file vm.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
References l.
Referenced by __VMwareBackdoorHypervisors().
__VMwareBackdoorHypervisors()
bool __VMwareBackdoorHypervisors ()
Definition at line 46 of file vm.c.
 {
     const char hv[13] = {0};
     uint32_t eax, ebx, ecx, edx;
     __cpuid(0x40000000, &eax, &ebx, &ecx, &edx);
     *(uint32_t *)hv = ebx;
     *(uint32_t *)(hv + 4) = ecx;
     *(uint32_t *)(hv + 8) = edx;
     if (__strcmp(hv, "VMwareVMware") != 0 &&
         __strcmp(hv, "KVMKVMKVM") != 0 &&
         __strcmp(hv, "TCGTCGTCGTCG") != 0)
     {
         return false;
     }
     return true;
 }
References __cpuid(), and __strcmp().
Referenced by IsVMwareBackdoorAvailable().
IsVMwareBackdoorAvailable()
bool IsVMwareBackdoorAvailable ()
Definition at line 65 of file vm.c.
 {
     if (!__CheckHypervisorBit())
         return false;
     if (!__VMwareBackdoorHypervisors())
         return false;
     struct
     {
         union
         {
             uint32_t ax;
             uint32_t magic;
         };
         union
         {
             uint32_t bx;
             size_t size;
         };
         union
         {
             uint32_t cx;
             uint16_t command;
         };
         union
         {
             uint32_t dx;
             uint16_t port;
         };
         uint32_t si;
         uint32_t di;
     } cmd;
     cmd.si = cmd.di = 0;
     cmd.bx = ~0x564D5868;
     cmd.command = 0xA;
     cmd.magic = 0x564D5868;
     cmd.port = 0x5658;
     asmv("in %%dx, %0"
          : "+a"(cmd.ax), "+b"(cmd.bx),
            "+c"(cmd.cx), "+d"(cmd.dx),
            "+S"(cmd.si), "+D"(cmd.di));
     if (cmd.bx != 0x564D5868 ||
         cmd.ax == 0xFFFFFFFF)
         return false;
     return true;
 }
References __CheckHypervisorBit(), __VMwareBackdoorHypervisors(), asmv(), cmd, port, and size.