Fennix: Userspace/mlibc/options/ansi/include/wchar.h File Reference
wchar.h File Reference
#include <stdarg.h>
#include <bits/null.h>
#include <bits/size_t.h>
#include <bits/wchar_t.h>
#include <bits/wchar.h>
#include <bits/wint_t.h>
#include <bits/mbstate.h>
Macros
#define __need___va_list
#define WEOF 0xffffffffU
Typedefs
typedef struct __mlibc_file_base FILE
typedef struct __mlibc_mbstate mbstate_t
Functions
int fwprintf (FILE *__restrict, const wchar_t *__restrict,...)
int fwscanf (FILE *__restrict, const wchar_t *__restrict,...)
int vfwprintf (FILE *__restrict, const wchar_t *__restrict, __gnuc_va_list)
int vfwscanf (FILE *__restrict, const wchar_t *__restrict, __gnuc_va_list)
int swprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict,...)
int swscanf (wchar_t *__restrict, size_t, const wchar_t *__restrict,...)
int vswprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict, __gnuc_va_list)
int vswscanf (wchar_t *__restrict, size_t, const wchar_t *__restrict, __gnuc_va_list)
int wprintf (const wchar_t *__restrict,...)
int wscanf (const wchar_t *__restrict,...)
int vwprintf (const wchar_t *__restrict, __gnuc_va_list)
int vwscanf (const wchar_t *__restrict, __gnuc_va_list)
wint_t fgetwc (FILE *)
wchar_t * fgetws (wchar_t *__restrict, int, FILE *__restrict)
wint_t fputwc (wchar_t, FILE *)
int fputws (const wchar_t *__restrict, FILE *__restrict)
int fwide (FILE *, int)
wint_t getwc (FILE *)
wint_t getwchar (void)
wint_t putwc (wchar_t, FILE *)
wint_t putwchar (wchar_t)
wint_t ungetwc (wint_t, FILE *)
double wcstod (const wchar_t *__restrict, wchar_t **__restrict)
float wcstof (const wchar_t *__restrict, wchar_t **__restrict)
long double wcstold (const wchar_t *__restrict, wchar_t **__restrict)
long wcstol (const wchar_t *__restrict, wchar_t **__restrict, int)
long long wcstoll (const wchar_t *__restrict, wchar_t **__restrict, int)
unsigned long wcstoul (const wchar_t *__restrict, wchar_t **__restrict, int)
unsigned long long wcstoull (const wchar_t *__restrict, wchar_t **__restrict, int)
wchar_t * wcscpy (wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcsncpy (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wmemcpy (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wmemmove (wchar_t *, const wchar_t *, size_t)
wchar_t * wcscat (wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcsncat (wchar_t *__restrict, const wchar_t *__restrict, size_t)
int wcscmp (const wchar_t *, const wchar_t *)
int wcscoll (const wchar_t *, const wchar_t *)
int wcsncmp (const wchar_t *, const wchar_t *, size_t)
int wcsxfrm (wchar_t *__restrict, const wchar_t *__restrict, size_t)
int wmemcmp (const wchar_t *, const wchar_t *, size_t)
wchar_t * wcschr (const wchar_t *, wchar_t)
size_t wcscspn (const wchar_t *, const wchar_t *)
wchar_t * wcspbrk (const wchar_t *, const wchar_t *)
wchar_t * wcsrchr (const wchar_t *, wchar_t)
size_t wcsspn (const wchar_t *, const wchar_t *)
wchar_t * wcsstr (const wchar_t *, const wchar_t *)
wchar_t * wcstok (wchar_t *__restrict, const wchar_t *__restrict, wchar_t **__restrict)
wchar_t * wmemchr (const wchar_t *, wchar_t, size_t)
size_t wcslen (const wchar_t *)
wchar_t * wmemset (wchar_t *, wchar_t, size_t)
size_t wcsftime (wchar_t *__restrict, size_t, const wchar_t *__restrict, const struct tm *__restrict)
wint_t btowc (int c)
int wctob (wint_t)
int mbsinit (const mbstate_t *)
size_t mbrlen (const char *__restrict, size_t, mbstate_t *__restrict)
size_t mbrtowc (wchar_t *__restrict, const char *__restrict, size_t, mbstate_t *__restrict)
size_t wcrtomb (char *__restrict, wchar_t, mbstate_t *__restrict)
size_t mbsrtowcs (wchar_t *__restrict, const char **__restrict, size_t, mbstate_t *__restrict)
size_t mbsnrtowcs (wchar_t *__restrict, const char **__restrict, size_t, size_t, mbstate_t *__restrict)
size_t wcsrtombs (char *__restrict, const wchar_t **__restrict, size_t, mbstate_t *__restrict)
size_t wcsnrtombs (char *__restrict, const wchar_t **__restrict, size_t, size_t, mbstate_t *__restrict)
int wcwidth (wchar_t wc)
int wcswidth (const wchar_t *, size_t)
wchar_t * wcsdup (const wchar_t *s)
int wcsncasecmp (const wchar_t *, const wchar_t *, size_t)
Macro Definition Documentation
__need___va_list
#define __need___va_list
Definition at line 6 of file wchar.h.
WEOF
#define WEOF 0xffffffffU
Definition at line 16 of file wchar.h.
Typedef Documentation
FILE
typedef struct __mlibc_file_base FILE
Definition at line 1 of file wchar.h.
mbstate_t
typedef struct __mlibc_mbstate mbstate_t
Definition at line 1 of file wchar.h.
Function Documentation
btowc()
wint_t btowc (int c)
Definition at line 21 of file wchar-stubs.cpp.
                     {
     if(c == EOF)
         return WEOF;
     char nc = c;
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     if(auto e = cc->promote_wtranscode(nc, wc); e != mlibc::charcode_error::null)
         return WEOF;
     return wc;
 }
fgetwc()
wint_t fgetwc (FILE * f)
Definition at line 58 of file fgetwc.c.
 {
     wint_t c;
     FLOCK(f);
     c = __fgetwc_unlocked(f);
     FUNLOCK(f);
     return c;
 }
References __fgetwc_unlocked(), c, f, FLOCK, and FUNLOCK.
fgetws()
wchar_t* fgetws (wchar_t * __restrict, int , FILE * __restrict)
fputwc()
wint_t fputwc (wchar_t c, FILE * f)
Definition at line 31 of file fputwc.c.
 {
     FLOCK(f);
     c = __fputwc_unlocked(c, f);
     FUNLOCK(f);
     return c;
 }
References __fputwc_unlocked(), c, f, FLOCK, and FUNLOCK.
fputws()
int fputws (const wchar_t * __restrict, FILE * __restrict)
fwide()
int fwide (FILE * f, int mode)
Definition at line 5 of file fwide.c.
 {
     FLOCK(f);
     if (mode) {
         if (!f->locale) f->locale = MB_CUR_MAX==1
             ? C_LOCALE : UTF8_LOCALE;
         if (!f->mode) f->mode = mode>0 ? 1 : -1;
     }
     mode = f->mode;
     FUNLOCK(f);
     return mode;
 }
References C_LOCALE, f, FLOCK, FUNLOCK, MB_CUR_MAX, and UTF8_LOCALE.
fwprintf()
int fwprintf (FILE * __restrict, const wchar_t * __restrict, ...)
fwscanf()
int fwscanf (FILE * __restrict, const wchar_t * __restrict, ...)
getwc()
wint_t getwc (FILE * f)
Definition at line 4 of file getwc.c.
 {
     return fgetwc(f);
 }
References f, and fgetwc().
getwchar()
wint_t getwchar (void)
Definition at line 4 of file getwchar.c.
 {
     return fgetwc(stdin);
 }
References fgetwc(), and stdin.
mbrlen()
size_t mbrlen (const char * __restrict, size_t mb_limit, mbstate_t * __restrict)
Definition at line 44 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     if(!stp)
         stp = &mbrlen_state;
     if(!mbs) {
         *stp = __MLIBC_MBSTATE_INITIALIZER;
         return 0;
     }
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{&wc, &wc + 1};
     if(auto e = cc->decode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null)
         __ensure(!"decode_wtranscode() errors are not handled");
     return nseq.it - mbs;
 }
mbrtowc()
size_t mbrtowc (wchar_t * __restrict, const char * __restrict, size_t mb_limit, mbstate_t * __restrict)
Definition at line 62 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     if(!stp)
         stp = &mbrtowc_state;
     if(!mbs) {
         *stp = __MLIBC_MBSTATE_INITIALIZER;
         return 0;
     }
     wchar_t temp = 0;
     if(!wcp)
         wcp = &temp;
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{wcp, wcp + 1};
     if(auto e = cc->decode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         if(e == mlibc::charcode_error::input_underflow)
             return static_cast<size_t>(-2);
         __ensure(e == mlibc::charcode_error::illegal_input);
         errno = EILSEQ;
         return static_cast<size_t>(-1);
     }else{
         if (*mbs) {
             return nseq.it - mbs;
         } else {
             *stp = __MLIBC_MBSTATE_INITIALIZER;
             *wcp = 0;
             return 0;
         }
     }
 }
mbsinit()
int mbsinit (const mbstate_t * stp)
Definition at line 38 of file wchar-stubs.cpp.
{
     if(!stp)
         return -1;
     return !stp->__progress && !stp->__shift;
 }
mbsnrtowcs()
size_t mbsnrtowcs (wchar_t * __restrict, const char ** __restrict, size_t mb_limit, size_t wc_limit, mbstate_t * __restrict)
Definition at line 147 of file wchar-stubs.cpp.
{
     __ensure(mbsp);
     auto cc = mlibc::current_charcode();
     __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
     mlibc::code_seq<const char> nseq{*mbsp, (*mbsp) + mb_limit};
     mlibc::code_seq<wchar_t> wseq{wcs, wcs + wc_limit};
     if(!stp)
         stp = &mbsrtowcs_state;
     if(!wcs) {
         size_t size;
         if(auto e = cc->decode_wtranscode_length(nseq, &size, st); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->decode_wtranscode(nseq, wseq, st); e != mlibc::charcode_error::null) {
         __ensure(!"decode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = wseq.it - wcs;
         if(n < wc_limit) // Null-terminate resulting wide string.
             wcs[n] = 0;
         *mbsp = nullptr;
         return n;
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{wchar-stubs.cpp}::mbsrtowcs_state, n, mlibc::null, and size.
Referenced by wms_write().
mbsrtowcs()
size_t mbsrtowcs (wchar_t * __restrict, const char ** __restrict, size_t wc_limit, mbstate_t * __restrict)
Definition at line 117 of file wchar-stubs.cpp.
{
     __ensure(mbsp);
     auto cc = mlibc::current_charcode();
     __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
     mlibc::code_seq<const char> nseq{*mbsp, nullptr};
     mlibc::code_seq<wchar_t> wseq{wcs, wcs + wc_limit};
     if(!stp)
         stp = &mbsrtowcs_state;
     if(!wcs) {
         size_t size;
         if(auto e = cc->decode_wtranscode_length(nseq, &size, st); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->decode_wtranscode(nseq, wseq, st); e != mlibc::charcode_error::null) {
         __ensure(!"decode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = wseq.it - wcs;
         if(n < wc_limit) // Null-terminate resulting wide string.
             wcs[n] = 0;
         *mbsp = nullptr;
         return n;
     }
 }
putwc()
wint_t putwc (wchar_t c, FILE * f)
Definition at line 4 of file putwc.c.
 {
     return fputwc(c, f);
 }
References c, f, and fputwc().
putwchar()
wint_t putwchar (wchar_t c)
Definition at line 4 of file putwchar.c.
 {
     return fputwc(c, stdout);
 }
References c, fputwc(), and stdout.
swprintf()
int swprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, ...)
swscanf()
int swscanf (wchar_t * __restrict, size_t , const wchar_t * __restrict, ...)
ungetwc()
wint_t ungetwc (wint_t c, FILE * f)
Definition at line 8 of file ungetwc.c.
 {
     unsigned char mbc[MB_LEN_MAX];
     int l;
     locale_t *ploc = &CURRENT_LOCALE, loc = *ploc;
     FLOCK(f);
     if (f->mode <= 0) fwide(f, 1);
     *ploc = f->locale;
     if (!f->rpos) __toread(f);
     if (!f->rpos || c == WEOF || (l = wcrtomb((void *)mbc, c, 0)) < 0 ||
         f->rpos < f->buf - UNGET + l) {
         FUNLOCK(f);
         *ploc = loc;
         return WEOF;
     }
     if (isascii(c)) *--f->rpos = c;
     else memcpy(f->rpos -= l, mbc, l);
     f->flags &= ~F_EOF;
     FUNLOCK(f);
     *ploc = loc;
     return c;
 }
References __toread(), c, CURRENT_LOCALE, f, F_EOF, FLOCK, FUNLOCK, fwide(), isascii, MB_LEN_MAX, memcpy, UNGET, wcrtomb(), and WEOF.
vfwprintf()
int vfwprintf (FILE * __restrict, const wchar_t * __restrict, __gnuc_va_list)
Referenced by fwprintf(), vswprintf(), and vwprintf().
vfwscanf()
int vfwscanf (FILE * __restrict, const wchar_t * __restrict, __gnuc_va_list)
Referenced by fwscanf(), vswscanf(), and vwscanf().
vswprintf()
int vswprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, __gnuc_va_list)
Referenced by swprintf().
vswscanf()
int vswscanf (wchar_t * __restrict, size_t , const wchar_t * __restrict, __gnuc_va_list)
Referenced by swscanf().
vwprintf()
int vwprintf (const wchar_t * __restrict, __gnuc_va_list)
vwscanf()
int vwscanf (const wchar_t * __restrict, __gnuc_va_list)
Referenced by wscanf().
wcrtomb()
size_t wcrtomb (char * __restrict, wchar_t wc, mbstate_t * __restrict)
Definition at line 95 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     // wcrtomb() always takes a mbstate_t.
     __ensure(stp);
     // TODO: Implement the following case:
     __ensure(mbs);
     mlibc::code_seq<const wchar_t> wseq{&wc, &wc + 1};
     mlibc::code_seq<char> nseq{mbs, mbs + 4}; // TODO: Replace 4 by some named constant.
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = nseq.it - mbs;
         if(!n) // Null-terminate resulting wide string.
             *mbs = 0;
         return n;
     }
 }
wcscat()
wchar_t* wcscat (wchar_t * __restrict, const wchar_t * __restrict)
wcschr()
wchar_t* wcschr (const wchar_t * s, wchar_t c)
Definition at line 297 of file string-stubs.cpp.
{
     if(!c)
         return (wchar_t *)s + wcslen(s);
     for(; *s && *s != c; s++);
     return *s ? (wchar_t *)s : 0;
 }
wcscmp()
int wcscmp (const wchar_t * l, const wchar_t * r)
Definition at line 3 of file wcscmp.c.
 {
     for (; *l==*r && *l && *r; l++, r++);
     return *l < *r ? -1 : *l > *r;
 }
References r.
Referenced by __wcscoll_l().
wcscoll()
int wcscoll (const wchar_t * l, const wchar_t * r)
Definition at line 11 of file wcscoll.c.
 {
     return __wcscoll_l(l, r, CURRENT_LOCALE);
 }
References __wcscoll_l(), CURRENT_LOCALE, and r.
wcscpy()
wchar_t* wcscpy (wchar_t * __restrict, const wchar_t * __restrict)
wcscspn()
size_t wcscspn (const wchar_t * s, const wchar_t * c)
Definition at line 3 of file wcscspn.c.
 {
     const wchar_t *a;
     if (!c[0]) return wcslen(s);
     if (!c[1]) return (s=wcschr(a=s, *c)) ? s-a : wcslen(a);
     for (a=s; *s && !wcschr(c, *s); s++);
     return s-a;
 }
References c, wcschr(), and wcslen().
wcsdup()
wchar_t* wcsdup (const wchar_t * s)
Definition at line 757 of file wchar-stubs.cpp.
{
     size_t len = wcslen(s);
     wchar_t *ret = (wchar_t *) malloc(sizeof(wchar_t) * (len + 1));
     if(!ret)
         return NULL;
     wmemcpy(ret, s, len + 1);
     return ret;
 }
References len, malloc, NULL, ret, wcslen(), and wmemcpy().
Referenced by main().
wcsftime()
size_t wcsftime (wchar_t * __restrict, size_t , const wchar_t * __restrict, const struct tm * __restrict)
Definition at line 348 of file time-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: wcsftime is a stub" << frg::endlog;
     return 0;
 }
wcslen()
size_t wcslen (const wchar_t * s)
Definition at line 457 of file Convert.cpp.
 {
     size_t len = 0;
     while (s[len] != L'\0')
     {
         if (s[++len] == L'\0')
             return len;
         if (s[++len] == L'\0')
             return len;
         if (s[++len] == L'\0')
             return len;
         ++len;
     }
     return len;
 }
wcsncasecmp()
int wcsncasecmp (const wchar_t * s1, const wchar_t * s2, size_t n)
Definition at line 766 of file wchar-stubs.cpp.
{
     for(size_t i = 0; i < n; i++) {
         wint_t c1 = towlower(s1[i]);
         wint_t c2 = towlower(s2[i]);
         if(c1 == L'\0' && c2 == L'\0')
             return 0;
         if(c1 < c2)
             return -1;
         if(c1 > c2)
             return 1;
     }
     return 0;
 }
References i, L, n, r, s1, s2, and towlower().
Referenced by main(), wcscasecmp(), and wcsncasecmp_l().
wcsncat()
wchar_t* wcsncat (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wcsncmp()
int wcsncmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 3 of file wcsncmp.c.
 {
     for (; n && *l==*r && *l && *r; n--, l++, r++);
     return n ? (*l < *r ? -1 : *l > *r) : 0;
 }
References n, and r.
wcsncpy()
wchar_t* wcsncpy (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wcsnrtombs()
size_t wcsnrtombs (char * __restrict, const wchar_t ** __restrict, size_t wc_limit, size_t mb_limit, mbstate_t * __restrict)
Definition at line 205 of file wchar-stubs.cpp.
{
     __ensure(wcsp && "wcsrtombs() with null input");
     auto cc = mlibc::current_charcode();
     mlibc::code_seq<char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<const wchar_t> wseq{*wcsp, (*wcsp) + wc_limit};
     if(!stp)
         stp = &wcsrtombs_state;
     if(!mbs) {
         size_t size;
         if(auto e = cc->encode_wtranscode_length(wseq, &size, *stp); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         *wcsp = wseq.it;
         size_t n = nseq.it - mbs;
         if(n < mb_limit) // Null-terminate resulting narrow string.
             mbs[n] = 0;
         return n;
     }
 }
References __ensure, mlibc::current_charcode(), n, mlibc::null, size, and anonymous_namespace{wchar-stubs.cpp}::wcsrtombs_state.
wcspbrk()
wchar_t* wcspbrk (const wchar_t * s, const wchar_t * b)
Definition at line 3 of file wcspbrk.c.
 {
     s += wcscspn(s, b);
     return *s ? (wchar_t *)s : NULL;
 }
References b, NULL, and wcscspn().
wcsrchr()
wchar_t* wcsrchr (const wchar_t * s, wchar_t c)
Definition at line 307 of file string-stubs.cpp.
{
     const wchar_t *p;
     for(p = s + wcslen(s); p >= s && *p != c; p--);
     return p >= s ? (wchar_t *)p : 0;
 }
wcsrtombs()
size_t wcsrtombs (char * __restrict, const wchar_t ** __restrict, size_t len, mbstate_t * __restrict)
Definition at line 475 of file Convert.cpp.
 {
     UNUSED(ps);
     size_t count = 0;
     while (len > 0)
     {
         wchar_t wc = **src;
         if (wc == L'\0')
             break;
         if (wc < 0x80)
         {
             if (dst)
                 *dst++ = (char)wc;
             count++;
             len--;
         }
         else if (wc < 0x800)
         {
             if (dst)
             {
                 *dst++ = (char)(0xC0 | (wc >> 6));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 2;
             len -= 2;
         }
         else if (wc < 0x10000)
         {
             if (dst)
             {
                 *dst++ = (char)(0xE0 | (wc >> 12));
                 *dst++ = (char)(0x80 | ((wc >> 6) & 0x3F));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 3;
             len -= 3;
         }
         else
         {
             if (dst)
             {
                 *dst++ = (char)(0xF0 | (wc >> 18));
                 *dst++ = (char)(0x80 | ((wc >> 12) & 0x3F));
                 *dst++ = (char)(0x80 | ((wc >> 6) & 0x3F));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 4;
             len -= 4;
         }
         (*src)++;
     }
     if (dst)
         *dst = '\0';
     return count;
 }
wcsspn()
size_t wcsspn (const wchar_t * s, const wchar_t * c)
Definition at line 3 of file wcsspn.c.
 {
     const wchar_t *a;
     for (a=s; *s && wcschr(c, *s); s++);
     return s-a;
 }
References c, and wcschr().
wcsstr()
wchar_t* wcsstr (const wchar_t * , const wchar_t *)
Referenced by wcswcs().
wcstod()
double wcstod (const wchar_t * __restrict, wchar_t ** __restrict)
wcstof()
float wcstof (const wchar_t * __restrict, wchar_t ** __restrict)
wcstok()
wchar_t* wcstok (wchar_t * __restrict, const wchar_t * __restrict, wchar_t ** __restrict)
wcstol()
long wcstol (const wchar_t * __restrict, wchar_t ** __restrict, int)
Referenced by main().
wcstold()
long double wcstold (const wchar_t * __restrict, wchar_t ** __restrict)
wcstoll()
long long wcstoll (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstoul()
unsigned long wcstoul (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstoull()
unsigned long long wcstoull (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcswidth()
int wcswidth (const wchar_t * wcs, size_t n)
Definition at line 745 of file wchar-stubs.cpp.
{
     int ret = 0;
     for(size_t i = 0; i < n && wcs[i]; i++) {
         int cols = wcwidth(wcs[i]);
         if (cols < 0)
             return -1;
         ret += cols;
     }
     return ret;
 }
References i, k, n, ret, and wcwidth().
wcsxfrm()
int wcsxfrm (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wctob()
int wctob (wint_t wc)
Definition at line 33 of file wchar-stubs.cpp.
                      {
     // TODO: Revisit this once we have character encoding functions.
     return wc;
 }
wcwidth()
int wcwidth (wchar_t wc)
Definition at line 726 of file wchar-stubs.cpp.
{
     // NOTE: created by hand, there isn't anything identifiable other than
     // general Cf category code to identify these, and some characters in Cf
     // category code are of non-zero width.
     if (ucs == 0 || ucs == 0x034F || (0x200B <= ucs && ucs <= 0x200F) ||
         ucs == 0x2028 || ucs == 0x2029 || (0x202A <= ucs && ucs <= 0x202E) ||
         (0x2060 <= ucs && ucs <= 0x2063)) {
         return 0;
     }
     // C0/C1 control characters.
     if (ucs < 32 || (0x07F <= ucs && ucs < 0x0A0)) return -1;
     // Combining characters with zero width.
     if (intable(ZERO_WIDTH, sizeof(ZERO_WIDTH) / sizeof(struct width_interval), ucs)) return 0;
     return intable(WIDE_EASTASIAN, sizeof(WIDE_EASTASIAN) / sizeof(struct width_interval), ucs) ? 2 : 1;
 }
References anonymous_namespace{wchar-stubs.cpp}::intable(), table, anonymous_namespace{wchar-stubs.cpp}::WIDE_EASTASIAN, wtable, and anonymous_namespace{wchar-stubs.cpp}::ZERO_WIDTH.
Referenced by assertWidthIs(), and wcswidth().
wmemchr()
wchar_t* wmemchr (const wchar_t * s, wchar_t c, size_t n)
Definition at line 3 of file wmemchr.c.
 {
     for (; n && *s != c; n--, s++);
     return n ? (wchar_t *)s : 0;
 }
References c, and n.
Referenced by twoway_wcsstr(), and wcsnlen().
wmemcmp()
int wmemcmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 3 of file wmemcmp.c.
 {
     for (; n && *l==*r; n--, l++, r++);
     return n ? (*l < *r ? -1 : *l > *r) : 0;
 }
References n, and r.
Referenced by twoway_wcsstr().
wmemcpy()
wchar_t* wmemcpy (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wmemmove()
wchar_t* wmemmove (wchar_t * dest, const wchar_t * src, size_t n)
Definition at line 264 of file string-stubs.cpp.
{
     memmove(dest, src, n * sizeof(wchar_t));
     return dest;
 }
wmemset()
wchar_t* wmemset (wchar_t * d, wchar_t c, size_t n)
Definition at line 331 of file string-stubs.cpp.
{
     wchar_t *ret = d;
     while(n--)
         *d++ = c;
     return ret;
 }
wprintf()
int wprintf (const wchar_t * __restrict, ...)
wscanf()
int wscanf (const wchar_t * __restrict, ...)