Fennix: APIC::APIC Class Reference
APIC::APIC Class Reference
#include <apic.hpp>
Public Member Functions
uint32_t Read (uint32_t Register)
void Write (uint32_t Register, uint32_t Value)
void IOWrite (uint64_t Base, uint32_t Register, uint32_t Value)
uint32_t IORead (uint64_t Base, uint32_t Register)
void EOI ()
void RedirectIRQs (uint8_t CPU=0)
void WaitForIPI ()
void ICR (InterruptCommandRegister icr)
void SendInitIPI (int CPU)
void SendStartupIPI (int CPU, uint64_t StartupAddress)
uint32_t IOGetMaxRedirect (uint32_t APICID)
void RawRedirectIRQ (uint8_t Vector, uint32_t GSI, uint16_t Flags, uint8_t CPU, int Status)
void RedirectIRQ (uint8_t CPU, uint8_t IRQ, int Status)
APIC (int Core)
~APIC ()
uint32_t Read (uint32_t Register)
void Write (uint32_t Register, uint32_t Value)
void IOWrite (uint64_t Base, uint32_t Register, uint32_t Value)
uint32_t IORead (uint64_t Base, uint32_t Register)
void EOI ()
void RedirectIRQs (int CPU=0)
void WaitForIPI ()
void IPI (uint8_t CPU, InterruptCommandRegisterLow icr)
void SendInitIPI (uint8_t CPU)
void SendStartupIPI (uint8_t CPU, uint64_t StartupAddress)
uint32_t IOGetMaxRedirect (uint32_t APICID)
void RawRedirectIRQ (uint16_t Vector, uint32_t GSI, uint16_t Flags, int CPU, int Status)
void RedirectIRQ (int CPU, uint16_t IRQ, int Status)
APIC (int Core)
~APIC ()
Data Fields
decltype(x2APICSupported) & x2APIC = x2APICSupported
Private Attributes
bool x2APICSupported = false
uint64_t APICBaseAddress = 0
Detailed Description
Definition at line 345 of file apic.hpp.
Constructor & Destructor Documentation
APIC() [1/2]
APIC::APIC::APIC (int Core)
Definition at line 290 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         APIC_BASE BaseStruct = {.raw = rdmsr(MSR_APIC_BASE)};
         uint64_t BaseLow = BaseStruct.ABALow;
         uint64_t BaseHigh = BaseStruct.ABAHigh;
         this->APICBaseAddress = BaseLow << 12u | BaseHigh << 32u;
         trace("APIC Address: %#lx", this->APICBaseAddress);
         Memory::Virtual().Map((void *)this->APICBaseAddress,
                               (void *)this->APICBaseAddress,
                               Memory::RW | Memory::PCD);
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
             CPU::x86::AMD::CPUID0x00000001 cpuid;
             cpuid.Get();
             if (cpuid.ECX.x2APIC)
             {
                 this->x2APICSupported = cpuid.ECX.x2APIC;
                 debug("x2APIC is supported");
             }
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
             CPU::x86::Intel::CPUID0x00000001 cpuid;
             cpuid.Get();
             if (cpuid.ECX.x2APIC)
             {
                 this->x2APICSupported = cpuid.ECX.x2APIC;
                 debug("x2APIC is supported");
             }
         }
         BaseStruct.AE = 1;
         wrmsr(MSR_APIC_BASE, BaseStruct.raw);
         if (this->x2APICSupported)
         {
             BaseStruct.EXTD = 1;
             wrmsr(MSR_APIC_BASE, BaseStruct.raw);
         }
         if (!this->x2APICSupported)
         {
             this->Write(APIC_TPR, 0x0);
             this->Write(APIC_DFR, 0xF0000000);
             this->Write(APIC_LDR, this->Read(APIC_ID));
         }
         else
         {
             wrmsr(MSR_X2APIC_TPR, 0x0);
         }
         ACPI::MADT *madt = (ACPI::MADT *)PowerManager->GetMADT();
         for (size_t i = 0; i < madt->nmi.size(); i++)
         {
             if (madt->nmi[i]->processor != 0xFF &&
                 Core != madt->nmi[i]->processor)
                 break;
             uint32_t nmi = 0x402;
             if (madt->nmi[i]->flags & 2)
                 nmi |= 1 << 13;
             if (madt->nmi[i]->flags & 8)
                 nmi |= 1 << 15;
             if (madt->nmi[i]->lint == 0)
             {
                 if (this->x2APICSupported)
                     wrmsr(MSR_X2APIC_LVT_LINT0, nmi);
                 else
                     this->Write(APIC_LINT0, nmi);
             }
             else if (madt->nmi[i]->lint == 1)
             {
                 if (this->x2APICSupported)
                     wrmsr(MSR_X2APIC_LVT_LINT1, nmi);
                 else
                     this->Write(APIC_LINT1, nmi);
             }
         }
         /* Setup the spurious interrupt vector */
         Spurious svr{};
         if (this->x2APICSupported)
             svr.raw = uint32_t(rdmsr(MSR_X2APIC_SIVR));
         else
             svr.raw = this->Read(APIC_SVR);
         svr.VEC = IRQ223;
         svr.ASE = 1;
         if (this->x2APICSupported)
             wrmsr(MSR_X2APIC_SIVR, svr.raw);
         else
             this->Write(APIC_SVR, svr.raw);
         static int once = 0;
         if (!once++)
         {
             // Disable PIT
             outb(0x43, 0x28);
             outb(0x40, 0x0);
             // Disable PIC
             outb(0x21, 0xFF);
             outb(0xA1, 0xFF);
         }
     }
References APIC::APIC_DFR, APIC::APIC_ID, APIC::APIC_LDR, APIC::APIC_LINT0, APIC::APIC_LINT1, APIC::APIC_SVR, APIC::APIC_TPR, x32::cpuid(), debug, Power::Power::GetMADT(), i, CPU::x86::IRQ223, Memory::Virtual::Map(), CPU::x64::MSR_APIC_BASE, CPU::x64::MSR_X2APIC_LVT_LINT0, CPU::x64::MSR_X2APIC_LVT_LINT1, CPU::x64::MSR_X2APIC_SIVR, CPU::x64::MSR_X2APIC_TPR, ACPI::MADT::nmi, outb(), Memory::PCD, PowerManager, Memory::RW, strcmp, trace, CPU::Vendor(), SysDbg::Write(), x86_CPUID_VENDOR_AMD, and x86_CPUID_VENDOR_INTEL.
~APIC() [1/2]
APIC::APIC::~APIC ()
Definition at line 399 of file apic.cpp.
 {}
APIC() [2/2]
APIC::APIC::APIC (int Core)
~APIC() [2/2]
APIC::APIC::~APIC ()
Member Function Documentation
EOI() [1/2]
void APIC::APIC::EOI ()
Definition at line 108 of file apic.cpp.
     {
         Memory::SwapPT swap =
             Memory::SwapPT(KernelPageTable, thisPageTable);
         if (this->x2APICSupported)
             wrmsr(MSR_X2APIC_EOI, 0);
         else
             this->Write(APIC_EOI, 0);
     }
References APIC::APIC_EOI, KernelPageTable, CPU::x64::MSR_X2APIC_EOI, swap(), thisPageTable, and SysDbg::Write().
Referenced by Interrupts::MainInterruptHandler().
EOI() [2/2]
void APIC::APIC::EOI ()
ICR()
void APIC::APIC::ICR (InterruptCommandRegister icr)
Definition at line 139 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         if (x2APICSupported)
         {
             assert(icr.MT != LowestPriority);
             assert(icr.MT != DeliveryMode);
             assert(icr.MT != ExtINT);
             wrmsr(MSR_X2APIC_ICR, icr.raw);
             this->WaitForIPI();
         }
         else
         {
             this->Write(APIC_ICRHI, icr.split.High);
             this->Write(APIC_ICRLO, icr.split.Low);
             this->WaitForIPI();
         }
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, assert, APIC::DeliveryMode, APIC::ExtINT, APIC::LowestPriority, CPU::x64::MSR_X2APIC_ICR, and SysDbg::Write().
IOGetMaxRedirect() [1/2]
uint32_t APIC::APIC::IOGetMaxRedirect (uint32_t APICID)
Definition at line 212 of file apic.cpp.
     {
         ACPI::MADT::MADTIOApic *ioapic = ((ACPI::MADT *)PowerManager->GetMADT())->ioapic[APICID];
         uint32_t TableAddress = (this->IORead(ioapic->Address, GetIOAPICVersion));
         IOAPICVersion ver = {.raw = TableAddress};
         return ver.MLE + 1;
     }
References ACPI::MADT::MADTIOApic::Address, APIC::GetIOAPICVersion, Power::Power::GetMADT(), and PowerManager.
IOGetMaxRedirect() [2/2]
uint32_t APIC::APIC::IOGetMaxRedirect (uint32_t APICID)
IORead() [1/2]
uint32_t APIC::APIC::IORead (uint64_t Base, uint32_t Register)
Definition at line 97 of file apic.cpp.
     {
         debug("APIC::IORead(%#lx, %#lx)", Base, Register);
         CPU::MemBar::Barrier();
         *((volatile uint32_t *)(((uintptr_t)Base))) = Register;
         CPU::MemBar::Barrier();
         uint32_t ret = *((volatile uint32_t *)(((uintptr_t)Base + 16)));
         CPU::MemBar::Barrier();
         return ret;
     }
References CPU::MemBar::Barrier(), and debug.
IORead() [2/2]
uint32_t APIC::APIC::IORead (uint64_t Base, uint32_t Register)
IOWrite() [1/2]
void APIC::APIC::IOWrite (uint64_t Base, uint32_t Register, uint32_t Value)
Definition at line 87 of file apic.cpp.
     {
         debug("APIC::IOWrite(%#lx, %#lx, %#lx)", Base, Register, Value);
         CPU::MemBar::Barrier();
         *((volatile uint32_t *)(((uintptr_t)Base))) = Register;
         CPU::MemBar::Barrier();
         *((volatile uint32_t *)(((uintptr_t)Base + 16))) = Value;
         CPU::MemBar::Barrier();
     }
References CPU::MemBar::Barrier(), and debug.
IOWrite() [2/2]
void APIC::APIC::IOWrite (uint64_t Base, uint32_t Register, uint32_t Value)
IPI()
void APIC::APIC::IPI (uint8_t CPU, InterruptCommandRegisterLow icr)
Definition at line 132 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         if (x2APICSupported)
         {
             wrmsr(MSR_X2APIC_ICR, s_cst(uint32_t, icr.raw));
             this->WaitForIPI();
         }
         else
         {
             this->Write(APIC_ICRHI, (CPU << 24));
             this->Write(APIC_ICRLO, s_cst(uint32_t, icr.raw));
             this->WaitForIPI();
         }
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, CPU::x32::MSR_X2APIC_ICR, and SysDbg::Write().
RawRedirectIRQ() [1/2]
void APIC::APIC::RawRedirectIRQ (uint16_t Vector, uint32_t GSI, uint16_t Flags, int CPU, int Status)
Definition at line 200 of file apic.cpp.
     {
         uint64_t Value = Vector;
         int64_t IOAPICTarget = -1;
         for (uint64_t i = 0; ((ACPI::MADT *)PowerManager->GetMADT())->ioapic[std::size_t(i)] != 0; i++)
             if (((ACPI::MADT *)PowerManager->GetMADT())->ioapic[std::size_t(i)]->GSIBase <= GSI)
                 if (((ACPI::MADT *)PowerManager->GetMADT())->ioapic[std::size_t(i)]->GSIBase + IOGetMaxRedirect(s_cst(uint32_t, i)) > GSI)
                 {
                     IOAPICTarget = i;
                     break;
                 }
         if (IOAPICTarget == -1)
         {
             error("No ISO table found for I/O APIC");
             return;
         }
         // TODO: IOAPICRedirectEntry Entry = {.raw = 0};
         if (Flags & ActiveHighLow)
             Value |= (1 << 13);
         if (Flags & EdgeLevel)
             Value |= (1 << 15);
         if (!Status)
             Value |= (1 << 16);
         Value |= (((uintptr_t)CPU) << 56);
         uint32_t IORegister = (GSI - ((ACPI::MADT *)PowerManager->GetMADT())->ioapic[std::size_t(IOAPICTarget)]->GSIBase) * 2 + 16;
         this->IOWrite(((ACPI::MADT *)PowerManager->GetMADT())->ioapic[std::size_t(IOAPICTarget)]->Address,
                       IORegister, (uint32_t)Value);
         this->IOWrite(((ACPI::MADT *)PowerManager->GetMADT())->ioapic[std::size_t(IOAPICTarget)]->Address,
                       IORegister + 1, (uint32_t)(Value >> 32));
     }
References APIC::ActiveHighLow, APIC::EdgeLevel, error, Flags, Power::Power::GetMADT(), i, and PowerManager.
RawRedirectIRQ() [2/2]
void APIC::APIC::RawRedirectIRQ (uint8_t Vector, uint32_t GSI, uint16_t Flags, uint8_t CPU, int Status)
Definition at line 220 of file apic.cpp.
     {
         int64_t IOAPICTarget = -1;
         ACPI::MADT *madt = (ACPI::MADT *)PowerManager->GetMADT();
         for (size_t i = 0; i < madt->ioapic.size(); i++)
         {
             if (madt->ioapic[i]->GSIBase <= GSI)
             {
                 if (madt->ioapic[i]->GSIBase + IOGetMaxRedirect(uint32_t(i)) > GSI)
                 {
                     IOAPICTarget = i;
                     break;
                 }
             }
         }
         if (IOAPICTarget == -1)
         {
             error("No ISO table found for I/O APIC");
             return;
         }
         IOAPICRedirectEntry Entry{};
         Entry.VEC = Vector;
         Entry.DES = CPU;
         if (Flags & ActiveHighLow)
             Entry.IPP = 1;
         if (Flags & EdgeLevel)
             Entry.TGM = 1;
         if (!Status)
             Entry.M = 1;
         uint32_t IORegister = (GSI - madt->ioapic[IOAPICTarget]->GSIBase) * 2 + 16;
         this->IOWrite(madt->ioapic[IOAPICTarget]->Address,
                       IORegister, Entry.split.Low);
         this->IOWrite(madt->ioapic[IOAPICTarget]->Address,
                       IORegister + 1, Entry.split.High);
     }
References APIC::ActiveHighLow, APIC::EdgeLevel, Entry(), error, Flags, Power::Power::GetMADT(), i, ACPI::MADT::ioapic, and PowerManager.
Read() [1/2]
uint32_t APIC::APIC::Read (uint32_t Register)
Definition at line 49 of file apic.cpp.
     {
 #ifdef DEBUG
         if (Register != APIC_ICRLO &&
             Register != APIC_ICRHI &&
             Register != APIC_ID)
             debug("APIC::Read(%#lx) [x2=%d]",
                   Register, x2APICSupported ? 1 : 0);
 #endif
         if (unlikely(x2APICSupported))
             assert(!"x2APIC is not supported");
         CPU::MemBar::Barrier();
         uint32_t ret = *((volatile uint32_t *)((uintptr_t)APICBaseAddress + Register));
         CPU::MemBar::Barrier();
         return ret;
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, APIC::APIC_ID, assert, CPU::MemBar::Barrier(), debug, and unlikely.
Referenced by GetCurrentCPU(), and APIC::Timer::Timer().
Read() [2/2]
uint32_t APIC::APIC::Read (uint32_t Register)
RedirectIRQ() [1/2]
void APIC::APIC::RedirectIRQ (int CPU, uint16_t IRQ, int Status)
Definition at line 239 of file apic.cpp.
     {
         for (uint64_t i = 0; i < ((ACPI::MADT *)PowerManager->GetMADT())->iso.size(); i++)
             if (((ACPI::MADT *)PowerManager->GetMADT())->iso[std::size_t(i)]->IRQSource == IRQ)
             {
                 debug("[ISO %d] Mapping to source IRQ%#d GSI:%#lx on CPU %d",
                       i, ((ACPI::MADT *)PowerManager->GetMADT())->iso[std::size_t(i)]->IRQSource,
                       ((ACPI::MADT *)PowerManager->GetMADT())->iso[std::size_t(i)]->GSI,
                       CPU);
                 this->RawRedirectIRQ(((ACPI::MADT *)PowerManager->GetMADT())->iso[std::size_t(i)]->IRQSource + 0x20,
                                      ((ACPI::MADT *)PowerManager->GetMADT())->iso[std::size_t(i)]->GSI,
                                      ((ACPI::MADT *)PowerManager->GetMADT())->iso[std::size_t(i)]->Flags,
                                      CPU, Status);
                 return;
             }
         debug("Mapping IRQ%d on CPU %d", IRQ, CPU);
         this->RawRedirectIRQ(IRQ + 0x20, IRQ, 0, CPU, Status);
     }
References debug, Power::Power::GetMADT(), i, and PowerManager.
RedirectIRQ() [2/2]
void APIC::APIC::RedirectIRQ (uint8_t CPU, uint8_t IRQ, int Status)
Definition at line 262 of file apic.cpp.
     {
         ACPI::MADT *madt = (ACPI::MADT *)PowerManager->GetMADT();
         for (uint64_t i = 0; i < madt->iso.size(); i++)
             if (madt->iso[i]->IRQSource == IRQ)
             {
                 debug("[ISO %d] Mapping to source IRQ%#d GSI:%#lx on CPU %d",
                       i, madt->iso[i]->IRQSource, madt->iso[i]->GSI, CPU);
                 this->RawRedirectIRQ(madt->iso[i]->IRQSource + 0x20,
                                      madt->iso[i]->GSI,
                                      madt->iso[i]->Flags,
                                      CPU, Status);
                 return;
             }
         debug("Mapping IRQ%d on CPU %d", IRQ, CPU);
         this->RawRedirectIRQ(IRQ + 0x20, IRQ, 0, CPU, Status);
     }
References debug, Power::Power::GetMADT(), i, ACPI::MADT::iso, and PowerManager.
RedirectIRQs() [1/2]
void APIC::APIC::RedirectIRQs (int CPU = 0)
Definition at line 259 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         debug("Redirecting IRQs...");
         for (uint8_t i = 0; i < 16; i++)
             this->RedirectIRQ(CPU, i, 1);
         debug("Redirecting IRQs completed.");
     }
References debug, and i.
RedirectIRQs() [2/2]
void APIC::APIC::RedirectIRQs (uint8_t CPU = 0)
Definition at line 281 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         debug("Redirecting IRQs...");
         for (uint8_t i = 0; i < 16; i++)
             this->RedirectIRQ(CPU, i, 1);
         debug("Redirecting IRQs completed.");
     }
References debug, and i.
SendInitIPI() [1/2]
void APIC::APIC::SendInitIPI (int CPU)
Definition at line 158 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         InterruptCommandRegister icr{};
         if (x2APICSupported)
         {
             icr.x2.MT = INIT;
             icr.x2.L = Assert;
             icr.x2.DES = uint8_t(CPU);
             wrmsr(MSR_X2APIC_ICR, icr.raw);
             this->WaitForIPI();
         }
         else
         {
             icr.MT = INIT;
             icr.L = Assert;
             icr.DES = uint8_t(CPU);
             this->Write(APIC_ICRHI, icr.split.High);
             this->Write(APIC_ICRLO, icr.split.Low);
             this->WaitForIPI();
         }
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, Assert, APIC::INIT, CPU::x64::MSR_X2APIC_ICR, and SysDbg::Write().
SendInitIPI() [2/2]
void APIC::APIC::SendInitIPI (uint8_t CPU)
Definition at line 148 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         if (x2APICSupported)
         {
             InterruptCommandRegisterLow icr = {.raw = 0};
             icr.DeliveryMode = INIT;
             icr.Level = Assert;
             wrmsr(MSR_X2APIC_ICR, s_cst(uint32_t, icr.raw));
             this->WaitForIPI();
         }
         else
         {
             InterruptCommandRegisterLow icr = {.raw = 0};
             icr.DeliveryMode = INIT;
             icr.Level = Assert;
             this->Write(APIC_ICRHI, (CPU << 24));
             this->Write(APIC_ICRLO, s_cst(uint32_t, icr.raw));
             this->WaitForIPI();
         }
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, Assert, APIC::INIT, CPU::x32::MSR_X2APIC_ICR, and SysDbg::Write().
SendStartupIPI() [1/2]
void APIC::APIC::SendStartupIPI (int CPU, uint64_t StartupAddress)
Definition at line 184 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         InterruptCommandRegister icr{};
         if (x2APICSupported)
         {
             icr.x2.VEC = s_cst(uint8_t, StartupAddress >> 12);
             icr.x2.MT = Startup;
             icr.x2.L = Assert;
             icr.x2.DES = uint8_t(CPU);
             wrmsr(MSR_X2APIC_ICR, icr.raw);
             this->WaitForIPI();
         }
         else
         {
             icr.VEC = s_cst(uint8_t, StartupAddress >> 12);
             icr.MT = Startup;
             icr.L = Assert;
             icr.DES = uint8_t(CPU);
             this->Write(APIC_ICRHI, icr.split.High);
             this->Write(APIC_ICRLO, icr.split.Low);
             this->WaitForIPI();
         }
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, Assert, CPU::x64::MSR_X2APIC_ICR, APIC::Startup, and SysDbg::Write().
SendStartupIPI() [2/2]
void APIC::APIC::SendStartupIPI (uint8_t CPU, uint64_t StartupAddress)
Definition at line 170 of file apic.cpp.
     {
         SmartCriticalSection(APICLock);
         if (x2APICSupported)
         {
             InterruptCommandRegisterLow icr = {.raw = 0};
             icr.Vector = s_cst(uint8_t, StartupAddress >> 12);
             icr.DeliveryMode = Startup;
             icr.Level = Assert;
             wrmsr(MSR_X2APIC_ICR, s_cst(uint32_t, icr.raw));
             this->WaitForIPI();
         }
         else
         {
             InterruptCommandRegisterLow icr = {.raw = 0};
             icr.Vector = s_cst(uint8_t, StartupAddress >> 12);
             icr.DeliveryMode = Startup;
             icr.Level = Assert;
             this->Write(APIC_ICRHI, (CPU << 24));
             this->Write(APIC_ICRLO, s_cst(uint32_t, icr.raw));
             this->WaitForIPI();
         }
     }
References APIC::APIC_ICRHI, APIC::APIC_ICRLO, Assert, CPU::x32::MSR_X2APIC_ICR, APIC::Startup, and SysDbg::Write().
WaitForIPI() [1/2]
void APIC::APIC::WaitForIPI ()
Definition at line 118 of file apic.cpp.
     {
         if (this->x2APICSupported)
         {
             ErrorStatusRegister esr{};
             esr.raw = uint32_t(rdmsr(MSR_X2APIC_ESR));
             UNUSED(esr);
             /* FIXME: Not sure if this is required or
                 how to implement it. */
         }
         else
         {
             InterruptCommandRegister icr{};
             do
             {
                 icr.split.Low = this->Read(APIC_ICRLO);
                 CPU::Pause();
             } while (icr.DS != Idle);
         }
     }
References APIC::APIC_ICRLO, APIC::Idle, CPU::x64::MSR_X2APIC_ESR, CPU::Pause(), APIC::ErrorStatusRegister::raw, and UNUSED.
WaitForIPI() [2/2]
void APIC::APIC::WaitForIPI ()
Write() [1/2]
void APIC::APIC::Write (uint32_t Register, uint32_t Value)
Definition at line 67 of file apic.cpp.
     {
 #ifdef DEBUG
         if (Register != APIC_EOI &&
             Register != APIC_TDCR &&
             Register != APIC_TIMER &&
             Register != APIC_TICR &&
             Register != APIC_ICRLO &&
             Register != APIC_ICRHI)
             debug("APIC::Write(%#lx, %#lx) [x2=%d]",
                   Register, Value, x2APICSupported ? 1 : 0);
 #endif
         if (unlikely(x2APICSupported))
             assert(!"x2APIC is not supported");
         CPU::MemBar::Barrier();
         *((volatile uint32_t *)(((uintptr_t)APICBaseAddress) + Register)) = Value;
         CPU::MemBar::Barrier();
     }
References APIC::APIC_EOI, APIC::APIC_ICRHI, APIC::APIC_ICRLO, APIC::APIC_TDCR, APIC::APIC_TICR, APIC::APIC_TIMER, assert, CPU::MemBar::Barrier(), debug, and unlikely.
Referenced by APIC::Timer::Timer().
Write() [2/2]
void APIC::APIC::Write (uint32_t Register, uint32_t Value)
Field Documentation
APICBaseAddress
uint64_t APIC::APIC::APICBaseAddress = 0 private
Definition at line 349 of file apic.hpp.
x2APIC
decltype(x2APICSupported) & APIC::APIC::x2APIC = x2APICSupported
Definition at line 352 of file apic.hpp.
Referenced by GetCurrentCPU(), and APIC::Timer::Timer().
x2APICSupported
bool APIC::APIC::x2APICSupported = false private
Definition at line 348 of file apic.hpp.
The documentation for this class was generated from the following files:
Kernel/arch/amd64/cpu/apic.hpp
Kernel/arch/amd64/cpu/apic.cpp