Fennix: Lynx/UEFI/src/Memory/VirtualMemoryManager.cpp File Reference
VirtualMemoryManager.cpp File Reference
#include "memory.hpp"
Namespaces
Memory
Functions
void printf (const char *format,...)
void * memset (void *dest, int c, size_t n)
Function Documentation
memset()
void* memset (void * dest, int c, size_t n)
Definition at line 5 of file VirtualMemoryManager.cpp.
 {
     unsigned int i;
     for (i = 0; i < n; i++)
         ((char *)dest)[i] = c;
     return dest;
 }
Referenced by Video::Display::ClearBuffer(), Video::Display::CreateBuffer(), Vector< ACPI::MADT::MADTNmi * >::remove(), and Video::Display::Scroll().
printf()
void printf (const char * format, ...)
Definition at line 53 of file Lynx.c.
 {
     va_list args;
     va_start(args, format);
     printf_(format, args);
     va_end(args);
 }
References printf_(), va_end, and va_start.