Fennix: Userspace/musl/src/network/res_query.c File Reference
res_query.c File Reference
#include <resolv.h>
#include <netdb.h>
Macros
#define _BSD_SOURCE
Functions
int res_query (const char *name, int class, int type, unsigned char *dest, int len)
weak_alias (res_query, res_search)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file res_query.c.
Function Documentation
res_query()
int res_query (const char * name, int class, int type, unsigned char * dest, int len)
Definition at line 5 of file res_query.c.
 {
     unsigned char q[280];
     int ql = __res_mkquery(0, name, class, type, 0, 0, 0, q, sizeof q);
     if (ql < 0) return ql;
     int r = __res_send(q, ql, dest, len);
     if (r<12) {
         h_errno = TRY_AGAIN;
         return -1;
     }
     if ((dest[3] & 15) == 3) {
         h_errno = HOST_NOT_FOUND;
         return -1;
     }
     if ((dest[3] & 15) == 0 && !dest[6] && !dest[7]) {
         h_errno = NO_DATA;
         return -1;
     }
     return r;
 }
References __res_mkquery(), __res_send(), h_errno, len, and type.
Referenced by res_querydomain().
weak_alias()
weak_alias (res_query , res_search)