Fennix: Userspace/apps/base/busybox/libbb/compare_string_array.c File Reference
compare_string_array.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC is_prefixed_with (const char *string, const char *key)
char *FAST_FUNC is_suffixed_with (const char *string, const char *key)
int FAST_FUNC index_in_str_array (const char *const string_array[], const char *key)
int FAST_FUNC index_in_strings (const char *strings, const char *key)
int FAST_FUNC index_in_substrings (const char *strings, const char *key)
const char *FAST_FUNC nth_string (const char *strings, int n)
Function Documentation
index_in_str_array()
int FAST_FUNC index_in_str_array (const char *const string_array[], const char * key)
Definition at line 52 of file compare_string_array.c.
 {
     int i;
     for (i = 0; string_array[i] != 0; i++) {
         if (strcmp(string_array[i], key) == 0) {
             return i;
         }
     }
     return -1;
 }
References i, and strcmp.
Referenced by get_variable().
index_in_strings()
int FAST_FUNC index_in_strings (const char * strings, const char * key)
Definition at line 64 of file compare_string_array.c.
 {
     int j, idx = 0;
     while (*strings) {
         /* Do we see "key\0" at current position in strings? */
         for (j = 0; *strings == key[j]; ++j) {
             if (*strings++ == '\0') {
                 //bb_error_msg("found:'%s' i:%u", key, idx);
                 return idx; /* yes */
             }
         }
         /* No.  Move to the start of the next string. */
         while (*strings++ != '\0')
             continue;
         idx++;
     }
     return -1;
 }
References idx, j, and strings.
Referenced by arp_del(), arp_set(), bootchartd_main(), brctl_main(), chat_main(), dd_main(), do_set(), download_one_url(), eval6(), expand(), fill_package_struct(), find_cmd(), find_control(), find_mode(), find_param(), ignore(), init(), ip_parse_common_args(), ipaddr_list_or_flush(), ipaddr_modify(), iproute_get(), iproute_list_or_flush(), is_builtin_exclude(), last_main(), mpstat_main(), mt_main(), parse_args(), parse_inittab(), parse_meminfo(), parse_one_line(), parse_params(), parse_propagation(), print_class(), print_qdisc(), process_action(), process_config_line(), process_irq_counts(), process_timer_stats(), read_interfaces(), rfkill_main(), set_environ(), set_mode(), set_shell(), slattach_main(), udhcp_option_idx(), and vlan_parse_opt().
index_in_substrings()
int FAST_FUNC index_in_substrings (const char * strings, const char * key)
Definition at line 101 of file compare_string_array.c.
 {
     int matched_idx = -1;
     const int len = strlen(key);
     if (len) {
         int idx = 0;
         while (*strings) {
             if (strncmp(strings, key, len) == 0) {
                 if (strings[len] == '\0')
                     return idx; /* exact match */
                 if (matched_idx >= 0)
                     return -1; /* ambiguous match */
                 matched_idx = idx;
             }
             strings += strlen(strings) + 1; /* skip NUL */
             idx++;
         }
     }
     return matched_idx;
 }
References idx, len, strings, strlen, and strncmp().
Referenced by date_main(), do_add_or_delete(), do_ipaddr(), do_iplink(), do_ipneigh(), do_iproute(), do_iprule(), do_iptunnel(), do_set(), ifconfig_main(), ip_parse_common_args(), ipneigh_list_or_flush(), iproute_list_or_flush(), iproute_modify(), iprule_modify(), ls_main(), nud_state_a2n(), rtnl_rtntype_a2n(), scan_recursive(), tc_main(), and vlan_parse_opt().
is_prefixed_with()
char* FAST_FUNC is_prefixed_with (const char * string, const char * key)
Definition at line 12 of file compare_string_array.c.
 {
 #if 0   /* Two passes over key - probably slower */
     int len = strlen(key);
     if (strncmp(string, key, len) == 0)
         return string + len;
     return NULL;
 #else   /* Open-coded */
     while (*key != '\0') {
         if (*key != *string)
             return NULL;
         key++;
         string++;
     }
     return (char*)string;
 #endif
 }
References len, NULL, string, strlen, and strncmp().
Referenced by add_probe(), add_symbols_from(), base_device(), compile_fs_type(), device_already_active(), fbsplash_main(), find_action(), find_iface_state(), findfs_main(), fsck_device(), fstype_matches(), get_block_backed_filesystems(), get_header_cpio(), get_header_tar(), get_irqs_from_stat(), get_old_name(), handle_incoming_and_exit(), if_redefined(), ipaddr_modify(), is_builtin_exclude(), is_ide_cdrom_or_tape(), last_main(), lbb_prepare(), load_crontab(), loadkmap_main(), main(), make_device(), may_wakeup(), modinfo(), modprobe_main(), nameif_parse_selector(), parse_and_add_kcmdline_module_options(), parse_conf(), parse_module(), parse_one_line(), patch_main(), process_pax_hdr(), process_timer_stats(), pwdx_main(), query(), read_interfaces(), resolve_mount_spec(), rtc_adjtime_is_utc(), run_pipe(), setarch_main(), singlemount(), skip_dev_pfx(), stack_machine(), str2sockaddr(), strip_unsafe_prefix(), table_lookup(), unpack_ar_archive(), and update_passwd().
is_suffixed_with()
char* FAST_FUNC is_suffixed_with (const char * string, const char * key)
Definition at line 35 of file compare_string_array.c.
 {
     size_t key_len = strlen(key);
     ssize_t len_diff = strlen(string) - key_len;
     if (len_diff >= 0) {
         string += len_diff;
         if (strcmp(string, key) == 0) {
             return (char*)string;
         }
     }
     return NULL;
 }
References NULL, strcmp, string, and strlen.
Referenced by config_file_action(), tar_main(), and ts_main().
nth_string()
const char* FAST_FUNC nth_string (const char * strings, int n)
Definition at line 123 of file compare_string_array.c.
 {
     while (n) {
         if (*strings++ == '\0') {
             if (*strings == '\0') /* reached end of strings */
                 break;
             n--;
         }
     }
     return strings;
 }
References n, and strings.
Referenced by adjtimex_main(), brctl_main(), do_display(), get_optname(), get_spd(), ionice_main(), ll_proto_n2a(), lsscsi_main(), policy_name(), print_linkinfo(), print_serial_flags(), shell_builtin_ulimit(), uart_type(), and vlan_parse_opt().