Fennix: Userspace/mlibc/sysdeps/managarm/include/mlibc/posix-pipe.hpp File Reference
posix-pipe.hpp File Reference
#include <signal.h>
#include <stdint.h>
#include <string.h>
#include <cstddef>
#include <hel.h>
#include <hel-syscalls.h>
#include <helix/ipc-structs.hpp>
Data Structures
struct SignalGuard
struct ElementHandle
struct Queue
Functions
MemoryAllocator & getSysdepsAllocator ()
HelSimpleResult * parseSimple (ElementHandle &element)
HelInlineResult * parseInline (ElementHandle &element)
HelLengthResult * parseLength (ElementHandle &element)
HelHandleResult * parseHandle (ElementHandle &element)
HelHandle getPosixLane ()
HelHandle * cacheFileTable ()
HelHandle getHandleForFd (int fd)
void clearCachedInfos ()
template<typename ... Args>
auto exchangeMsgsSync (HelHandle descriptor, Args &&...args)
Variables
thread_local Queue globalQueue
Function Documentation
cacheFileTable()
HelHandle* cacheFileTable ()
Definition at line 92 of file entry.cpp.
{
     // TODO: Make sure that this is signal-safe (it is called e.g. by sys_clock_get()).
     pthread_once(&has_cached_infos, &actuallyCacheInfos);
     return cachedFileTable;
 }
References anonymous_namespace{entry.cpp}::actuallyCacheInfos(), anonymous_namespace{entry.cpp}::cachedFileTable, fileTable, anonymous_namespace{entry.cpp}::has_cached_infos, posixLane, and pthread_once().
Referenced by getHandleForFd(), and getPosixLane().
clearCachedInfos()
void clearCachedInfos ()
Definition at line 105 of file entry.cpp.
{
     has_cached_infos = PTHREAD_ONCE_INIT;
 }
References anonymous_namespace{entry.cpp}::has_cached_infos, and PTHREAD_ONCE_INIT.
exchangeMsgsSync()
template<typename ... Args> auto exchangeMsgsSync (HelHandle descriptor, Args &&... args)
Definition at line 282 of file posix-pipe.hpp.
{
     auto results = helix_ng::createResultsTuple(args...);
     auto actions = helix_ng::chainActionArrays(args...);
     HEL_CHECK(helSubmitAsync(descriptor, actions.data(),
         actions.size(), globalQueue.getQueue(), 0, 0));
     auto element = globalQueue.dequeueSingle();
     void *ptr = element.data();
     [&]<size_t ...p>(std::index_sequence<p...>) {
         (results.template get<p>().parse(ptr, element), ...);
     } (std::make_index_sequence<std::tuple_size_v<decltype(results)>>{});
     return results;
 }
References ElementHandle::data(), Queue::dequeueSingle(), Queue::getQueue(), globalQueue, and p.
Referenced by mlibc::ioctl_drm(), mlibc::sys_chroot(), mlibc::sys_fallocate(), mlibc::sys_flock(), mlibc::sys_getrusage(), mlibc::sys_inotify_add_watch(), mlibc::sys_memfd_create(), mlibc::sys_mkfifoat(), mlibc::sys_mount(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
getHandleForFd()
HelHandle getHandleForFd (int fd)
Definition at line 98 of file entry.cpp.
{
     if (fd >= 512)
         return 0;
     return cacheFileTable()[fd];
 }
References cacheFileTable(), and fd.
Referenced by __mlibc_getPassthrough(), mlibc::ioctl_drm(), mlibc::sys_fallocate(), and mlibc::sys_flock().
getPosixLane()
HelHandle getPosixLane ()
Definition at line 87 of file entry.cpp.
{
     cacheFileTable();
     return __mlibc_posix_lane;
 }
References __mlibc_posix_lane, and cacheFileTable().
Referenced by mlibc::sys_chroot(), mlibc::sys_getrusage(), mlibc::sys_inotify_add_watch(), mlibc::sys_memfd_create(), mlibc::sys_mkfifoat(), mlibc::sys_mount(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
getSysdepsAllocator()
MemoryAllocator& getSysdepsAllocator ()
Definition at line 78 of file entry.cpp.
{
     // use frg::eternal to prevent a call to __cxa_atexit().
     // this is necessary because __cxa_atexit() call this function.
     static frg::eternal<VirtualAllocator> virtualAllocator;
     static frg::eternal<MemoryPool> heap{virtualAllocator.get()};
     static frg::eternal<MemoryAllocator> singleton{&heap.get()};
     return singleton.get();
 }
Referenced by mlibc::ioctl_drm(), Queue::Queue(), mlibc::sys_chroot(), mlibc::sys_fallocate(), mlibc::sys_flock(), mlibc::sys_getrusage(), mlibc::sys_inotify_add_watch(), mlibc::sys_memfd_create(), mlibc::sys_mkfifoat(), mlibc::sys_mount(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
parseHandle()
HelHandleResult* parseHandle (ElementHandle & element) inline
Definition at line 265 of file posix-pipe.hpp.
{
     auto result = reinterpret_cast<HelHandleResult *>(element.data());
     element.advance(sizeof(HelHandleResult));
     return result;
 }
References ElementHandle::advance(), ElementHandle::data(), and mlibc::result.
parseInline()
HelInlineResult* parseInline (ElementHandle & element) inline
Definition at line 253 of file posix-pipe.hpp.
{
     auto result = reinterpret_cast<HelInlineResult *>(element.data());
     element.advance(sizeof(HelInlineResult) + ((result->length + 7) & ~size_t(7)));
     return result;
 }
References ElementHandle::advance(), ElementHandle::data(), and mlibc::result.
parseLength()
HelLengthResult* parseLength (ElementHandle & element) inline
Definition at line 259 of file posix-pipe.hpp.
{
     auto result = reinterpret_cast<HelLengthResult *>(element.data());
     element.advance(sizeof(HelLengthResult));
     return result;
 }
References ElementHandle::advance(), ElementHandle::data(), and mlibc::result.
parseSimple()
HelSimpleResult* parseSimple (ElementHandle & element) inline
Definition at line 247 of file posix-pipe.hpp.
{
     auto result = reinterpret_cast<HelSimpleResult *>(element.data());
     element.advance(sizeof(HelSimpleResult));
     return result;
 }
References ElementHandle::advance(), ElementHandle::data(), and mlibc::result.
Variable Documentation
globalQueue
thread_local Queue globalQueue extern
Definition at line 23 of file entry.cpp.
Referenced by exchangeMsgsSync().