Fennix Userspace: Userspace/musl/src/network/recvmmsg.c File Reference
recvmmsg.c File Reference
#include <sys/socket.h>
#include <limits.h>
#include <errno.h>
#include <time.h>
#include "syscall.h"
Macros
#define _GNU_SOURCE
#define IS32BIT(x) !((x)+0x80000000ULL>>32)
#define CLAMP(x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Functions
hidden void __convert_scm_timestamps (struct msghdr *, socklen_t)
int recvmmsg (int fd, struct mmsghdr *msgvec, unsigned int vlen, unsigned int flags, struct timespec *timeout)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file recvmmsg.c.
CLAMP
#define CLAMP (x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Definition at line 9 of file recvmmsg.c.
IS32BIT
#define IS32BIT (x) !((x)+0x80000000ULL>>32)
Definition at line 8 of file recvmmsg.c.
Function Documentation
__convert_scm_timestamps()
void __convert_scm_timestamps (struct msghdr * msg, socklen_t csize)
Definition at line 10 of file recvmsg.c.
 {
     if (SCM_TIMESTAMP == SCM_TIMESTAMP_OLD) return;
     if (!msg->msg_control || !msg->msg_controllen) return;
     struct cmsghdr *cmsg, *last=0;
     long tmp;
     long long tvts[2];
     int type = 0;
     for (cmsg=CMSG_FIRSTHDR(msg); cmsg; cmsg=CMSG_NXTHDR(msg, cmsg)) {
         if (cmsg->cmsg_level==SOL_SOCKET) switch (cmsg->cmsg_type) {
         case SCM_TIMESTAMP_OLD:
             if (type) break;
             type = SCM_TIMESTAMP;
             goto common;
         case SCM_TIMESTAMPNS_OLD:
             type = SCM_TIMESTAMPNS;
         common:
             memcpy(&tmp, CMSG_DATA(cmsg), sizeof tmp);
             tvts[0] = tmp;
             memcpy(&tmp, CMSG_DATA(cmsg) + sizeof tmp, sizeof tmp);
             tvts[1] = tmp;
             break;
         }
         last = cmsg;
     }
     if (!last || !type) return;
     if (CMSG_SPACE(sizeof tvts) > csize-msg->msg_controllen) {
         msg->msg_flags |= MSG_CTRUNC;
         return;
     }
     msg->msg_controllen += CMSG_SPACE(sizeof tvts);
     cmsg = CMSG_NXTHDR(msg, last);
     cmsg->cmsg_level = SOL_SOCKET;
     cmsg->cmsg_type = type;
     cmsg->cmsg_len = CMSG_LEN(sizeof tvts);
     memcpy(CMSG_DATA(cmsg), &tvts, sizeof tvts);
 }
References CMSG_DATA, CMSG_FIRSTHDR, cmsghdr::cmsg_len, CMSG_LEN, cmsghdr::cmsg_level, CMSG_NXTHDR, CMSG_SPACE, cmsghdr::cmsg_type, common(), last, memcpy(), msghdr::msg_control, msghdr::msg_controllen, MSG_CTRUNC, msghdr::msg_flags, SCM_TIMESTAMP, SCM_TIMESTAMP_OLD, SCM_TIMESTAMPNS, SCM_TIMESTAMPNS_OLD, SOL_SOCKET, and type.
Referenced by recvmmsg(), and recvmsg().
recvmmsg()
int recvmmsg (int fd, struct mmsghdr * msgvec, unsigned int vlen, unsigned int flags, struct timespec * timeout)
Definition at line 13 of file recvmmsg.c.
 {
 #if LONG_MAX > INT_MAX
     struct mmsghdr *mh = msgvec;
     unsigned int i;
     for (i = vlen; i; i--, mh++)
         mh->msg_hdr.__pad1 = mh->msg_hdr.__pad2 = 0;
 #endif
 #ifdef SYS_recvmmsg_time64
     time_t s = timeout ? timeout->tv_sec : 0;
     long ns = timeout ? timeout->tv_nsec : 0;
     int r = __syscall_cp(SYS_recvmmsg_time64, fd, msgvec, vlen, flags,
             timeout ? ((long long[]){s, ns}) : 0);
     if (SYS_recvmmsg == SYS_recvmmsg_time64 || r!=-ENOSYS)
         return __syscall_ret(r);
     if (vlen > IOV_MAX) vlen = IOV_MAX;
     socklen_t csize[vlen];
     for (int i=0; i<vlen; i++) csize[i] = msgvec[i].msg_hdr.msg_controllen;
     r = __syscall_cp(SYS_recvmmsg, fd, msgvec, vlen, flags,
         timeout ? ((long[]){CLAMP(s), ns}) : 0);
     for (int i=0; i<r; i++)
         __convert_scm_timestamps(&msgvec[i].msg_hdr, csize[i]);
     return __syscall_ret(r);
 #else
     return syscall_cp(SYS_recvmmsg, fd, msgvec, vlen, flags, timeout);
 #endif
 }
References __convert_scm_timestamps(), __syscall_cp, __syscall_ret(), CLAMP, ENOSYS, fd, flags, i, s, SYS_recvmmsg, SYS_recvmmsg_time64, syscall_cp, and timeout().
Referenced by __recvmmsg_time32().