Fennix Userspace: Userspace/apps/base/busybox/libbb/perror_nomsg.c File Reference
perror_nomsg.c File Reference
#include "platform.h"
Functions
void bb_perror_msg (const char *s,...) FAST_FUNC
void FAST_FUNC bb_perror_nomsg (void)
Function Documentation
bb_perror_msg()
void bb_perror_msg (const char * s, ...)
Definition at line 11 of file perror_msg.c.
 {
     va_list p;
     va_start(p, s);
     /* Guard against "<error message>: Success" */
     bb_verror_msg(s, p, errno ? strerror(errno) : NULL);
     va_end(p);
 }
References bb_verror_msg(), errno, NULL, p, s, strerror(), va_end, and va_start.
Referenced by ask_and_unlink(), bb_ioctl_or_warn(), bb_make_directory(), bb_perror_nomsg(), bb_simple_perror_msg(), builtin_cd(), builtin_source(), change_attributes(), chdir_or_warn(), copy_file(), cp_mv_stat2(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), data_extract_all(), determine_optimal_seed_len(), do_modprobe(), do_stat(), do_stop(), do_syslogd(), edir(), enslave(), execvp_or_die(), hash_file(), inetd_main(), install_main(), kill_main(), list_attributes(), load_fs_info(), logdir_open(), lsattr_args(), lsattr_dir_proc(), make_device(), match(), mountpoint_main(), mv_main(), nc_main(), network_ioctl(), new_init_module(), open3_or_warn(), open_list_and_close(), open_trunc_or_warn(), passwd_main(), pause1cannot(), pause2cannot(), perror_on_device(), prepare_socket_fd(), print_matchpathcon(), process_one(), remove_file(), remove_ids(), rename_or_warn(), renice_main(), restore(), rmdir_main(), run(), run_parts_main(), scan_recursive(), set_if_down(), set_if_up(), singlemount(), sysctl_act_on_setting(), tail_main(), transformer_write(), truncate_main(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), umount_main(), up_iface(), update_passwd(), warn(), warn2(), warn2_cannot(), warn_opendir(), write_and_stats(), and xset1().
bb_perror_nomsg()
void FAST_FUNC bb_perror_nomsg (void)
Definition at line 19 of file perror_nomsg.c.
 {
     bb_perror_msg(0);
 }
References bb_perror_msg().
Referenced by update_passwd().