Fennix Userspace: Userspace/apps/base/busybox/networking/route.c File Reference
route.c File Reference
#include <net/route.h>
#include <net/if.h>
#include "libbb.h"
#include "inet_common.h"
Macros
#define RTF_UP 0x0001 /* route usable */
#define RTF_GATEWAY 0x0002 /* destination is a gateway */
#define RTF_HOST 0x0004 /* host entry (net otherwise) */
#define RTF_REINSTATE 0x0008 /* reinstate route after tmout */
#define RTF_DYNAMIC 0x0010 /* created dyn. (by redirect) */
#define RTF_MODIFIED 0x0020 /* modified dyn. (by redirect) */
#define RTF_MTU 0x0040 /* specific MTU for this route */
#define RTF_MSS RTF_MTU /* Compatibility :-(*/
#define RTF_WINDOW 0x0080 /* per route window clamping */
#define RTF_IRTT 0x0100 /* Initial round trip time */
#define RTF_REJECT 0x0200 /* Reject route */
#define RTF_NONEXTHOP 0x00200000 /* route with no nexthop */
#define HAVE_NEW_ADDRT 1
#define mask_in_addr(x) (((struct sockaddr_in *)&((x).rt_genmask))->sin_addr.s_addr)
#define full_mask(x) (x)
#define RTACTION_ADD 1
#define RTACTION_DEL 2
#define NET_FLAG 1
#define HOST_FLAG 2
#define KW_TAKES_ARG 020
#define KW_SETS_FLAG 040
#define KW_IPVx_METRIC 020
#define KW_IPVx_NETMASK 021
#define KW_IPVx_GATEWAY 022
#define KW_IPVx_MSS 023
#define KW_IPVx_WINDOW 024
#define KW_IPVx_IRTT 025
#define KW_IPVx_DEVICE 026
#define KW_IPVx_FLAG_ONLY 040
#define KW_IPVx_REJECT 040
#define KW_IPVx_MOD 041
#define KW_IPVx_DYN 042
#define KW_IPVx_REINSTATE 043
#define IPV4_MASK (RTF_UP|RTF_GATEWAY|RTF_HOST|RTF_REINSTATE|RTF_DYNAMIC|RTF_MODIFIED)
#define IPV6_MASK (RTF_UP|RTF_GATEWAY|RTF_HOST|RTF_DEFAULT|RTF_ADDRCONF|RTF_CACHE|RTF_REJECT|RTF_NONEXTHOP)
#define ROUTE_OPT_A 0x01
#define ROUTE_OPT_n 0x02
#define ROUTE_OPT_e 0x04
#define ROUTE_OPT_INET6 0x08 /* Not an actual option. See below. */
Functions
static int kw_lookup (const char *kwtbl, char ***pargs)
static NOINLINE void INET_setroute (int action, char **args)
static const IF_FEATURE_IPV6 (uint32_t flagvals[] ALIGN4=)
static void set_flags (char *flagstr, int flags)
void FAST_FUNC bb_displayroutes (int noresolve, int netstatfmt)
int route_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char tbl_hash_net_host[] ALIGN1
static const uint16_t flags_ipvx[] ALIGN2
Macro Definition Documentation
full_mask
#define full_mask (x) (x)
Definition at line 68 of file route.c.
HAVE_NEW_ADDRT
#define HAVE_NEW_ADDRT 1
Definition at line 63 of file route.c.
HOST_FLAG
#define HOST_FLAG 2
Definition at line 81 of file route.c.
IPV4_MASK
#define IPV4_MASK (RTF_UP|RTF_GATEWAY|RTF_HOST|RTF_REINSTATE|RTF_DYNAMIC|RTF_MODIFIED)
Definition at line 476 of file route.c.
IPV6_MASK
#define IPV6_MASK (RTF_UP|RTF_GATEWAY|RTF_HOST|RTF_DEFAULT|RTF_ADDRCONF|RTF_CACHE|RTF_REJECT|RTF_NONEXTHOP)
Definition at line 477 of file route.c.
KW_IPVx_DEVICE
#define KW_IPVx_DEVICE 026
Definition at line 98 of file route.c.
KW_IPVx_DYN
#define KW_IPVx_DYN 042
Definition at line 103 of file route.c.
KW_IPVx_FLAG_ONLY
#define KW_IPVx_FLAG_ONLY 040
Definition at line 100 of file route.c.
KW_IPVx_GATEWAY
#define KW_IPVx_GATEWAY 022
Definition at line 94 of file route.c.
KW_IPVx_IRTT
#define KW_IPVx_IRTT 025
Definition at line 97 of file route.c.
KW_IPVx_METRIC
#define KW_IPVx_METRIC 020
Definition at line 92 of file route.c.
KW_IPVx_MOD
#define KW_IPVx_MOD 041
Definition at line 102 of file route.c.
KW_IPVx_MSS
#define KW_IPVx_MSS 023
Definition at line 95 of file route.c.
KW_IPVx_NETMASK
#define KW_IPVx_NETMASK 021
Definition at line 93 of file route.c.
KW_IPVx_REINSTATE
#define KW_IPVx_REINSTATE 043
Definition at line 104 of file route.c.
KW_IPVx_REJECT
#define KW_IPVx_REJECT 040
Definition at line 101 of file route.c.
KW_IPVx_WINDOW
#define KW_IPVx_WINDOW 024
Definition at line 96 of file route.c.
KW_SETS_FLAG
#define KW_SETS_FLAG 040
Definition at line 90 of file route.c.
KW_TAKES_ARG
#define KW_TAKES_ARG 020
Definition at line 89 of file route.c.
mask_in_addr
#define mask_in_addr (x) (((struct sockaddr_in *)&((x).rt_genmask))->sin_addr.s_addr)
Definition at line 67 of file route.c.
NET_FLAG
#define NET_FLAG 1
Definition at line 80 of file route.c.
ROUTE_OPT_A
#define ROUTE_OPT_A 0x01
Definition at line 654 of file route.c.
ROUTE_OPT_e
#define ROUTE_OPT_e 0x04
Definition at line 656 of file route.c.
ROUTE_OPT_INET6
#define ROUTE_OPT_INET6 0x08 /* Not an actual option. See below. */
Definition at line 657 of file route.c.
ROUTE_OPT_n
#define ROUTE_OPT_n 0x02
Definition at line 655 of file route.c.
RTACTION_ADD
#define RTACTION_ADD 1
Definition at line 75 of file route.c.
RTACTION_DEL
#define RTACTION_DEL 2
Definition at line 76 of file route.c.
RTF_DYNAMIC
#define RTF_DYNAMIC 0x0010 /* created dyn. (by redirect) */
Definition at line 50 of file route.c.
RTF_GATEWAY
#define RTF_GATEWAY 0x0002 /* destination is a gateway */
Definition at line 47 of file route.c.
RTF_HOST
#define RTF_HOST 0x0004 /* host entry (net otherwise) */
Definition at line 48 of file route.c.
RTF_IRTT
#define RTF_IRTT 0x0100 /* Initial round trip time */
Definition at line 57 of file route.c.
RTF_MODIFIED
#define RTF_MODIFIED 0x0020 /* modified dyn. (by redirect) */
Definition at line 51 of file route.c.
RTF_MSS
#define RTF_MSS RTF_MTU /* Compatibility :-(*/
Definition at line 54 of file route.c.
RTF_MTU
#define RTF_MTU 0x0040 /* specific MTU for this route */
Definition at line 52 of file route.c.
RTF_NONEXTHOP
#define RTF_NONEXTHOP 0x00200000 /* route with no nexthop */
Definition at line 59 of file route.c.
RTF_REINSTATE
#define RTF_REINSTATE 0x0008 /* reinstate route after tmout */
Definition at line 49 of file route.c.
RTF_REJECT
#define RTF_REJECT 0x0200 /* Reject route */
Definition at line 58 of file route.c.
RTF_UP
#define RTF_UP 0x0001 /* route usable */
Definition at line 46 of file route.c.
RTF_WINDOW
#define RTF_WINDOW 0x0080 /* per route window clamping */
Definition at line 56 of file route.c.
Function Documentation
bb_displayroutes()
void FAST_FUNC bb_displayroutes (int noresolve, int netstatfmt)
Definition at line 491 of file route.c.
 {
     char devname[64], flags[16], *sdest, *sgw;
     unsigned long d, g, m;
     int r;
     int flgs, ref, use, metric, mtu, win, ir;
     struct sockaddr_in s_addr;
     struct in_addr mask;
     FILE *fp = xfopen_for_read("/proc/net/route");
     printf("Kernel IP routing table\n"
         "Destination     Gateway         Genmask         Flags %s Iface\n",
             netstatfmt ? "  MSS Window  irtt" : "Metric Ref    Use");
     /* Skip the first line. */
     r = fscanf(fp, "%*[^\n]\n");
     if (r < 0) {
         /* Empty line, read error, or EOF. Yes, if routing table
          * is completely empty, /proc/net/route has no header.
          */
         goto ERROR;
     }
     while (1) {
         r = fscanf(fp, "%63s%lx%lx%X%d%d%d%lx%d%d%d\n",
                 devname, &d, &g, &flgs, &ref, &use, &metric, &m,
                 &mtu, &win, &ir);
         if (r != 11) {
  ERROR:
             if ((r < 0) && feof(fp)) { /* EOF with no (nonspace) chars read. */
                 break;
             }
             bb_simple_perror_msg_and_die(bb_msg_read_error);
         }
         if (!(flgs & RTF_UP)) { /* Skip interfaces that are down. */
             continue;
         }
         set_flags(flags, (flgs & IPV4_MASK));
 #ifdef RTF_REJECT
         if (flgs & RTF_REJECT) {
             flags[0] = '!';
         }
 #endif
         memset(&s_addr, 0, sizeof(struct sockaddr_in));
         s_addr.sin_family = AF_INET;
         s_addr.sin_addr.s_addr = d;
         sdest = INET_rresolve(&s_addr, (noresolve | 0x8000), m); /* 'default' instead of '*' */
         s_addr.sin_addr.s_addr = g;
         sgw = INET_rresolve(&s_addr, (noresolve | 0x4000), m); /* Host instead of net */
         mask.s_addr = m;
         /* "%15.15s" truncates hostnames, do we really want that? */
         printf("%-15.15s %-15.15s %-16s%-6s", sdest, sgw, inet_ntoa(mask), flags);
         free(sdest);
         free(sgw);
         if (netstatfmt) {
             printf("%5d %-5d %6d %s\n", mtu, win, ir, devname);
         } else {
             printf("%-6d %-2d %7d %s\n", metric, ref, use, devname);
         }
     }
     fclose(fp);
 }
References AF_INET, bb_msg_read_error, bb_simple_perror_msg_and_die(), ERROR, fclose(), feof, flags, free, fscanf(), g, inet_ntoa(), INET_rresolve(), IPV4_MASK, memset(), printf(), RTF_REJECT, RTF_UP, in_addr::s_addr, set_flags(), and xfopen_for_read().
Referenced by netstat_main(), and route_main().
IF_FEATURE_IPV6()
static const IF_FEATURE_IPV6 (uint32_t flagvals[] ALIGN4) static
Definition at line 453 of file route.c.
 { /* Must agree with flagchars[]. */
     RTF_UP,
     RTF_GATEWAY,
     RTF_HOST,
     RTF_REINSTATE,
     RTF_DYNAMIC,
     RTF_MODIFIED,
 #if ENABLE_FEATURE_IPV6
     RTF_DEFAULT,
     RTF_ADDRCONF,
     RTF_CACHE,
     RTF_REJECT,
     RTF_NONEXTHOP, /* this one doesn't fit into 16 bits */
 #endif
 };
References RTF_ADDRCONF, RTF_CACHE, RTF_DEFAULT, RTF_DYNAMIC, RTF_GATEWAY, RTF_HOST, RTF_MODIFIED, RTF_NONEXTHOP, RTF_REINSTATE, RTF_REJECT, and RTF_UP.
Referenced by str2sockaddr(), and xsocket().
INET_setroute()
static NOINLINE void INET_setroute (int action, char ** args) static
Definition at line 161 of file route.c.
 {
     /* char buffer instead of bona-fide struct avoids aliasing warning */
     char rt_buf[sizeof(struct rtentry)];
     struct rtentry *const rt = (void *)rt_buf;
     const char *netmask = NULL;
     int skfd, isnet, xflag;
     /* Grab the -net or -host options.  Remember they were transformed. */
     xflag = kw_lookup(tbl_hash_net_host, &args);
     /* If we did grab -net or -host, make sure we still have an arg left. */
     if (*args == NULL) {
         bb_show_usage();
     }
     /* Clean out the RTREQ structure. */
     memset(rt, 0, sizeof(*rt));
     {
         const char *target = *args++;
         char *prefix;
         /* recognize x.x.x.x/mask format. */
         prefix = strchr(target, '/');
         if (prefix) {
             int prefix_len;
             prefix_len = xatoul_range(prefix+1, 0, 32);
             mask_in_addr(*rt) = htonl( ~(0xffffffffUL >> prefix_len));
             *prefix = '\0';
 #if HAVE_NEW_ADDRT
             rt->rt_genmask.sa_family = AF_INET;
 #endif
         } else {
             /* Default netmask. */
             netmask = "default";
         }
         /* Prefer hostname lookup if -host flag (xflag==1) was given. */
         isnet = INET_resolve(target, (struct sockaddr_in *) &rt->rt_dst,
                              (xflag & HOST_FLAG));
         if (isnet < 0) {
             bb_error_msg_and_die("resolving %s", target);
         }
         if (prefix) {
             /* do not destroy prefix for process args */
             *prefix = '/';
         }
     }
     if (xflag) {        /* Reinit isnet if -net or -host was specified. */
         isnet = (xflag & NET_FLAG);
     }
     /* Fill in the other fields. */
     rt->rt_flags = ((isnet) ? RTF_UP : (RTF_UP | RTF_HOST));
     while (*args) {
         int k = kw_lookup(tbl_ipvx, &args);
         const char *args_m1 = args[-1];
         if (k & KW_IPVx_FLAG_ONLY) {
             rt->rt_flags |= flags_ipvx[k & 3];
             continue;
         }
 #if HAVE_NEW_ADDRT
         if (k == KW_IPVx_METRIC) {
             rt->rt_metric = xatoul(args_m1) + 1;
             continue;
         }
 #endif
         if (k == KW_IPVx_NETMASK) {
             struct sockaddr mask;
             if (mask_in_addr(*rt)) {
                 bb_show_usage();
             }
             netmask = args_m1;
             isnet = INET_resolve(netmask, (struct sockaddr_in *) &mask, 0);
             if (isnet < 0) {
                 bb_error_msg_and_die("resolving %s", netmask);
             }
             rt->rt_genmask = full_mask(mask);
             continue;
         }
         if (k == KW_IPVx_GATEWAY) {
             if (rt->rt_flags & RTF_GATEWAY) {
                 bb_show_usage();
             }
             isnet = INET_resolve(args_m1,
                         (struct sockaddr_in *) &rt->rt_gateway, 1);
             rt->rt_flags |= RTF_GATEWAY;
             if (isnet) {
                 if (isnet < 0) {
                     bb_error_msg_and_die("resolving %s", args_m1);
                 }
                 bb_error_msg_and_die("gateway %s is a NETWORK", args_m1);
             }
             continue;
         }
         if (k == KW_IPVx_MSS) { /* Check valid MSS bounds. */
             rt->rt_flags |= RTF_MSS;
             rt->rt_mss = xatoul_range(args_m1, 64, 32768);
             continue;
         }
         if (k == KW_IPVx_WINDOW) {  /* Check valid window bounds. */
             rt->rt_flags |= RTF_WINDOW;
             rt->rt_window = xatoul_range(args_m1, 128, INT_MAX);
             continue;
         }
 #ifdef RTF_IRTT
         if (k == KW_IPVx_IRTT) {
             rt->rt_flags |= RTF_IRTT;
             rt->rt_irtt = xatoul(args_m1);
             rt->rt_irtt *= (bb_clk_tck() / 100);    /* FIXME */
 #if 0                   /* FIXME: do we need to check anything of this? */
             if (rt->rt_irtt < 1 || rt->rt_irtt > (120 * HZ)) {
                 bb_error_msg_and_die("bad irtt");
             }
 #endif
             continue;
         }
 #endif
         /* Device is special in that it can be the last arg specified
          * and doesn't require the dev/device keyword in that case. */
         if (!rt->rt_dev && ((k == KW_IPVx_DEVICE) || (!k && !*++args))) {
             /* Don't use args_m1 here since args may have changed! */
             rt->rt_dev = args[-1];
             continue;
         }
         /* Nothing matched. */
         bb_show_usage();
     }
 #ifdef RTF_REJECT
     if ((rt->rt_flags & RTF_REJECT) && !rt->rt_dev) {
         rt->rt_dev = (char*)"lo";
     }
 #endif
     /* sanity checks.. */
     if (mask_in_addr(*rt)) {
         uint32_t mask = mask_in_addr(*rt);
         mask = ~ntohl(mask);
         if ((rt->rt_flags & RTF_HOST) && mask != 0xffffffff) {
             bb_error_msg_and_die("netmask %.8x and host route conflict",
                                  (unsigned int) mask);
         }
         if (mask & (mask + 1)) {
             bb_error_msg_and_die("bogus netmask %s", netmask);
         }
         mask = ((struct sockaddr_in *) &rt->rt_dst)->sin_addr.s_addr;
         if (mask & ~(uint32_t)mask_in_addr(*rt)) {
             bb_simple_error_msg_and_die("netmask and route address conflict");
         }
     }
     /* Fill out netmask if still unset */
     if ((action == RTACTION_ADD) && (rt->rt_flags & RTF_HOST)) {
         mask_in_addr(*rt) = 0xffffffff;
     }
     /* Create a socket to the INET kernel. */
     skfd = xsocket(AF_INET, SOCK_DGRAM, 0);
     if (action == RTACTION_ADD)
         xioctl(skfd, SIOCADDRT, rt);
     else
         xioctl(skfd, SIOCDELRT, rt);
     if (ENABLE_FEATURE_CLEAN_UP) close(skfd);
 }
References AF_INET, bb_clk_tck(), bb_error_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), close(), full_mask, HOST_FLAG, htonl(), INET_resolve(), INT_MAX, k, KW_IPVx_DEVICE, KW_IPVx_FLAG_ONLY, KW_IPVx_GATEWAY, KW_IPVx_IRTT, KW_IPVx_METRIC, KW_IPVx_MSS, KW_IPVx_NETMASK, KW_IPVx_WINDOW, kw_lookup(), mask_in_addr, memset(), NET_FLAG, netmask, ntohl(), NULL, prefix(), rtentry::rt_dev, rtentry::rt_dst, rtentry::rt_flags, rtentry::rt_gateway, rtentry::rt_genmask, rtentry::rt_irtt, rtentry::rt_metric, rtentry::rt_window, RTACTION_ADD, RTF_GATEWAY, RTF_HOST, RTF_IRTT, RTF_MSS, RTF_REJECT, RTF_UP, RTF_WINDOW, sockaddr::sa_family, SIOCADDRT, SIOCDELRT, skfd, SOCK_DGRAM, strchr(), target, xflag, xioctl, and xsocket().
Referenced by route_main().
kw_lookup()
static int kw_lookup (const char * kwtbl, char *** pargs) static
Definition at line 139 of file route.c.
 {
     if (**pargs) {
         do {
             if (strcmp(kwtbl + 1, **pargs) == 0) { /* Found a match. */
                 *pargs += 1;
                 if (kwtbl[0] & KW_TAKES_ARG) {
                     if (!**pargs) { /* No more args! */
                         bb_show_usage();
                     }
                     *pargs += 1; /* Calling routine will use args[-1]. */
                 }
                 return kwtbl[0];
             }
             kwtbl += strlen(kwtbl) + 1;
         } while (*kwtbl);
     }
     return 0;
 }
References bb_show_usage(), KW_TAKES_ARG, strcmp, and strlen().
Referenced by INET_setroute(), and route_main().
route_main()
int route_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 667 of file route.c.
 {
     unsigned opt;
     int what;
     char *family;
     char **p;
     /* First, remap '-net' and '-host' to avoid getopt problems. */
     p = argv;
     while (*++p) {
         if (strcmp(*p, "-net") == 0 || strcmp(*p, "-host") == 0) {
             p[0][0] = '#';
         }
     }
     opt = getopt32(argv, "A:ne", &family);
     if ((opt & ROUTE_OPT_A) && strcmp(family, "inet") != 0) {
 #if ENABLE_FEATURE_IPV6
         if (strcmp(family, "inet6") == 0) {
             opt |= ROUTE_OPT_INET6; /* Set flag for ipv6. */
         } else
 #endif
         bb_show_usage();
     }
     argv += optind;
     /* No more args means display the routing table. */
     if (!*argv) {
         int noresolve = (opt & ROUTE_OPT_n) ? 0x0fff : 0;
 #if ENABLE_FEATURE_IPV6
         if (opt & ROUTE_OPT_INET6)
             INET6_displayroutes();
         else
 #endif
             bb_displayroutes(noresolve, opt & ROUTE_OPT_e);
         fflush_stdout_and_exit_SUCCESS();
     }
     /* Check verb.  At the moment, must be add, del, or delete. */
     what = kw_lookup(tbl_verb, &argv);
     if (!what || !*argv) {      /* Unknown verb or no more args. */
         bb_show_usage();
     }
 #if ENABLE_FEATURE_IPV6
     if (opt & ROUTE_OPT_INET6)
         INET6_setroute(what, argv);
     else
 #endif
         INET_setroute(what, argv);
     return EXIT_SUCCESS;
 }
References argv, bb_displayroutes(), bb_show_usage(), EXIT_SUCCESS, fflush_stdout_and_exit_SUCCESS(), getopt32(), INET_setroute(), kw_lookup(), opt, optind, p, ROUTE_OPT_A, ROUTE_OPT_e, ROUTE_OPT_INET6, ROUTE_OPT_n, and strcmp.
set_flags()
static void set_flags (char * flagstr, int flags) static
Definition at line 479 of file route.c.
 {
     int i;
     for (i = 0; (*flagstr = flagchars[i]) != 0; i++) {
         if (flags & flagvals[i]) {
             ++flagstr;
         }
     }
 }
References flags, and i.
Referenced by bb_displayroutes().
Variable Documentation
ALIGN1
const char tbl_verb [] ALIGN1 static
Initial value:
=
    "\001#net\0"
    "\002#host\0"
Definition at line 84 of file route.c.
ALIGN2
const uint16_t flags_ipvx [] ALIGN2 static
Initial value:
= {
    RTF_REJECT,
    RTF_MODIFIED,
    RTF_DYNAMIC,
    RTF_REINSTATE
}
Definition at line 130 of file route.c.