Fennix: Drivers/library/crt/crt0.cpp File Reference
crt0.cpp File Reference
#include <driver.h>
#include <errno.h>
Macros
#define KCALL extern "C" __attribute__((used))
#define KernelFunction(Name)
#define DefineFunction(ReturnType, Name, ...)
#define DefineWrapper(Name)
Typedefs
typedef void(* CallPtr) (void)
Functions
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
int DriverProbe ()
int _start (dev_t id)
int _final ()
DefineFunction (void, KernelPrint, const char *format,...)
DefineFunction (void, KernelLog, const char *format,...)
DefineWrapper (RegisterInterruptHandler)
DefineWrapper (OverrideInterruptHandler)
DefineWrapper (UnregisterInterruptHandler)
DefineWrapper (UnregisterAllInterruptHandlers)
DefineWrapper (AllocateMemory)
DefineWrapper (FreeMemory)
DefineWrapper (AppendMapFlag)
DefineWrapper (RemoveMapFlag)
DefineWrapper (MapPages)
DefineWrapper (UnmapPages)
DefineWrapper (MemoryCopy)
DefineWrapper (MemorySet)
DefineWrapper (MemoryMove)
DefineWrapper (StringLength)
DefineWrapper (strstr)
DefineWrapper (EnterCriticalSection)
DefineWrapper (LeaveCriticalSection)
DefineWrapper (CreateKernelProcess)
DefineWrapper (CreateKernelThread)
DefineWrapper (GetCurrentProcess)
DefineWrapper (KillProcess)
DefineWrapper (KillThread)
DefineWrapper (Yield)
DefineWrapper (Sleep)
DefineWrapper (RegisterFileSystem)
DefineWrapper (UnregisterFileSystem)
DefineWrapper (PIC_EOI)
DefineWrapper (IRQ_MASK)
DefineWrapper (IRQ_UNMASK)
DefineWrapper (PS2Wait)
DefineWrapper (PS2WriteCommand)
DefineWrapper (PS2WriteData)
DefineWrapper (PS2ReadData)
DefineWrapper (PS2ReadStatus)
DefineWrapper (PS2ReadAfterACK)
DefineWrapper (PS2ClearOutputBuffer)
DefineWrapper (PS2ACKTimeout)
DefineWrapper (RegisterDevice)
DefineWrapper (UnregisterDevice)
DefineWrapper (ReportInputEvent)
DefineWrapper (InitializePCI)
DefineWrapper (GetPCIDevices)
DefineWrapper (GetBAR)
DefineWrapper (iLine)
DefineWrapper (iPin)
Variables
dev_t DriverID = -1
CallPtr __init_array_start [0]
CallPtr __init_array_end [0]
CallPtr __fini_array_start [0]
CallPtr __fini_array_end [0]
Macro Definition Documentation
DefineFunction
#define DefineFunction (ReturnType, Name, ...)
Value:
    KernelFunction(Name);                     \
    KCALL ReturnType Name(__VA_ARGS__)
Definition at line 61 of file crt0.cpp.
DefineWrapper
#define DefineWrapper (Name)
Value:
    KernelFunction(Name);                                                             \
    KCALL long Name(long arg0, long arg1, long arg2, long arg3, long arg4, long arg5) \
    {                                                                                 \
        return __##Name(DriverID, arg0, arg1, arg2, arg3, arg4, arg5);                \
    }
Definition at line 65 of file crt0.cpp.
KCALL
#define KCALL extern "C" __attribute__((used))
Definition at line 54 of file crt0.cpp.
KernelFunction
#define KernelFunction (Name)
Value:
    KCALL long __##Name(dev_t id,                                    \
                        long arg0 = 0, long arg1 = 0, long arg2 = 0, \
                        long arg3 = 0, long arg4 = 0, long arg5 = 0);
Definition at line 56 of file crt0.cpp.
Typedef Documentation
CallPtr
typedef void(* CallPtr) (void)
Definition at line 28 of file crt0.cpp.
Function Documentation
_final()
int _final ()
Definition at line 42 of file crt0.cpp.
 {
     int err = DriverFinal();
     for (CallPtr *func = __fini_array_start; func != __fini_array_end; func++)
         (*func)();
     return err;
 }
References __fini_array_end, __fini_array_start, DriverFinal(), err(), and func().
_start()
int _start (dev_t id)
Definition at line 32 of file crt0.cpp.
 {
     DriverID = id;
     for (CallPtr *func = __init_array_start; func != __init_array_end; func++)
         (*func)();
     return 0;
 }
References __init_array_end, __init_array_start, DriverID, and func().
DefineFunction() [1/2]
DefineFunction (void , KernelLog , const char * format, ...)
Definition at line 80 of file crt0.cpp.
 {
     __builtin_va_list args;
     __builtin_va_start(args, format);
     __KernelLog(DriverID, (long)format, (long)args);
     __builtin_va_end(args);
 }
References DriverID.
DefineFunction() [2/2]
DefineFunction (void , KernelPrint , const char * format, ...)
Definition at line 72 of file crt0.cpp.
 {
     __builtin_va_list args;
     __builtin_va_start(args, format);
     __KernelPrint(DriverID, (long)format, (long)args);
     __builtin_va_end(args);
 }
References DriverID.
DefineWrapper() [1/45]
DefineWrapper (AllocateMemory)
DefineWrapper() [2/45]
DefineWrapper (AppendMapFlag)
DefineWrapper() [3/45]
DefineWrapper (CreateKernelProcess)
DefineWrapper() [4/45]
DefineWrapper (CreateKernelThread)
DefineWrapper() [5/45]
DefineWrapper (EnterCriticalSection)
DefineWrapper() [6/45]
DefineWrapper (FreeMemory)
DefineWrapper() [7/45]
DefineWrapper (GetBAR)
DefineWrapper() [8/45]
DefineWrapper (GetCurrentProcess)
DefineWrapper() [9/45]
DefineWrapper (GetPCIDevices)
DefineWrapper() [10/45]
DefineWrapper (iLine)
DefineWrapper() [11/45]
DefineWrapper (InitializePCI)
DefineWrapper() [12/45]
DefineWrapper (iPin)
DefineWrapper() [13/45]
DefineWrapper (IRQ_MASK)
DefineWrapper() [14/45]
DefineWrapper (IRQ_UNMASK)
DefineWrapper() [15/45]
DefineWrapper (KillProcess)
DefineWrapper() [16/45]
DefineWrapper (KillThread)
DefineWrapper() [17/45]
DefineWrapper (LeaveCriticalSection)
DefineWrapper() [18/45]
DefineWrapper (MapPages)
DefineWrapper() [19/45]
DefineWrapper (MemoryCopy)
DefineWrapper() [20/45]
DefineWrapper (MemoryMove)
DefineWrapper() [21/45]
DefineWrapper (MemorySet)
DefineWrapper() [22/45]
DefineWrapper (OverrideInterruptHandler)
DefineWrapper() [23/45]
DefineWrapper (PIC_EOI)
DefineWrapper() [24/45]
DefineWrapper (PS2ACKTimeout)
DefineWrapper() [25/45]
DefineWrapper (PS2ClearOutputBuffer)
DefineWrapper() [26/45]
DefineWrapper (PS2ReadAfterACK)
DefineWrapper() [27/45]
DefineWrapper (PS2ReadData)
DefineWrapper() [28/45]
DefineWrapper (PS2ReadStatus)
DefineWrapper() [29/45]
DefineWrapper (PS2Wait)
DefineWrapper() [30/45]
DefineWrapper (PS2WriteCommand)
DefineWrapper() [31/45]
DefineWrapper (PS2WriteData)
DefineWrapper() [32/45]
DefineWrapper (RegisterDevice)
DefineWrapper() [33/45]
DefineWrapper (RegisterFileSystem)
DefineWrapper() [34/45]
DefineWrapper (RegisterInterruptHandler)
DefineWrapper() [35/45]
DefineWrapper (RemoveMapFlag)
DefineWrapper() [36/45]
DefineWrapper (ReportInputEvent)
DefineWrapper() [37/45]
DefineWrapper (Sleep)
DefineWrapper() [38/45]
DefineWrapper (StringLength)
DefineWrapper() [39/45]
DefineWrapper (strstr)
DefineWrapper() [40/45]
DefineWrapper (UnmapPages)
DefineWrapper() [41/45]
DefineWrapper (UnregisterAllInterruptHandlers)
DefineWrapper() [42/45]
DefineWrapper (UnregisterDevice)
DefineWrapper() [43/45]
DefineWrapper (UnregisterFileSystem)
DefineWrapper() [44/45]
DefineWrapper (UnregisterInterruptHandler)
DefineWrapper() [45/45]
DefineWrapper (Yield)
DriverEntry()
int DriverEntry ()
A device may fail, but if the other one works, we can still use it.
This is the main function of the driver. This function should be used to initialize the PCI device and allocate resources.
If we have another driver using the PS/2 mouse, we need to override its interrupt handler.
Definition at line 22 of file main.c.
 { return cxx_Initialize(); }
References Absolute(), CreateKernelThread(), cxx_Initialize(), DebugLog, DisplayScaleThread(), dst_id, dst_pid, DualChannel, EFAULT, ENODEV, GetCurrentProcess(), InitializeKeyboard(), InitializeMouse(), INPUT_TYPE_MOUSE, InterruptHandler(), KernelLog(), KernelPrint(), MasterInterruptHandler(), MESSAGE_TCLO, MessageClose(), MouseDevID, MouseOps, NULL, OpenMessageChannel(), OverrideInterruptHandler(), PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_ENABLE_PORT_1, PS2_CMD_ENABLE_PORT_2, PS2_CMD_READ_CONFIG, PS2_CMD_TEST_CONTROLLER, PS2_CMD_TEST_PORT_1, PS2_CMD_TEST_PORT_2, PS2_CMD_WRITE_CONFIG, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_ENABLE_DATA_REPORTING, PS2_MOUSE_CMD_SET_DEFAULTS, PS2_TEST_PASSED, v0::PS2ClearOutputBuffer(), v0::PS2ReadData(), v0::PS2WriteCommand(), v0::PS2WriteData(), PS2_CONFIGURATION::Raw, v0::RegisterDevice(), RegisterInterruptHandler(), SlaveInterruptHandler(), tb_ctx, test, and ToolboxSupported.
DriverFinal()
int DriverFinal ()
This function is called when the driver is unloaded. This function should be used to stop the PCI device and free any resources.
Definition at line 23 of file main.c.
 { return cxx_Finalize(); }
References cxx_Finalize(), dst_id, dst_pid, FinalizeKeyboard(), FinalizeMouse(), FreeMemory(), KillThread(), MasterInterruptHandler(), MessageClose(), MouseDevID, PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, v0::PS2WriteCommand(), v0::PS2WriteData(), Relative(), SlaveInterruptHandler(), tb_ctx, ToolboxContext::TCLOChannel, ToolboxSupported, v0::UnregisterDevice(), and UnregisterInterruptHandler().
Referenced by _final().
DriverPanic()
int DriverPanic ()
This function is called when the kernel panics. This function should be used to stop the driver from sending interrupts or anything else that is not safe to do when the kernel panics.
Definition at line 24 of file main.c.
 { return cxx_Panic(); }
References cxx_Panic(), PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, v0::PS2WriteCommand(), v0::PS2WriteData(), and Relative().
DriverProbe()
int DriverProbe ()
This is the first function that is called when the driver is loaded.
This function is to test if the driver is compatible with the hardware. Example: Like if there is a PCI device that the driver is for, or a CPU feature that etc.
Return 0 if the driver is compatible with the hardware. Otherwise, return a value that is not 0.
Note: In this function you cannot use variables that have constructors or destructors. Before DriverEntry, the constructors are called and after DriverFinalize, the destructors are called.
Definition at line 25 of file main.c.
 { return cxx_Probe(); }
References __intStub(), cxx_Probe(), DetectPS2Keyboard(), DetectPS2Mouse(), DetectUART(), Device1ID, Device2ID, ENODEV, GetPS2DeviceName(), IsATAPresent(), IsKeyboard(), IsMouse(), IsVMwareBackdoorAvailable(), KernelLog(), KernelPrint(), RegisterInterruptHandler(), uart, and UnregisterAllInterruptHandlers().
Variable Documentation
__fini_array_end
CallPtr __fini_array_end[0]
Definition at line 30 of file crt0.cpp.
Referenced by _final().
__fini_array_start
CallPtr __fini_array_start[0] (void)
Definition at line 30 of file crt0.cpp.
Referenced by __libc_fini_array(), _final(), BeforeShutdown(), and libc_exit_fini().
__init_array_end
CallPtr __init_array_end[0] (void)
Definition at line 29 of file crt0.cpp.
Referenced by _start().
__init_array_start
CallPtr __init_array_start[0] (void)
Definition at line 29 of file crt0.cpp.
Referenced by __libc_init_array(), _start(), Entry(), and libc_start_init().
DriverID
dev_t DriverID = -1
Definition at line 21 of file crt0.cpp.
Referenced by _start(), and DefineFunction().