Fennix: Kernel/include/syscalls.hpp File Reference
syscalls.hpp File Reference
#include <types.h>
Data Structures
struct SyscallsFrame
Macros
#define SysFrm SyscallsFrame
Typedefs
typedef struct SyscallsFrame SyscallsFrame
Functions
uintptr_t HandleNativeSyscalls (SyscallsFrame *Frame)
uintptr_t HandleLinuxSyscalls (SyscallsFrame *Frame)
void InitializeSystemCalls ()
Initialize syscalls for the current CPU. (Function is available on x32, x64 & aarch64)
Data Structure Documentation
SyscallsFrame
struct SyscallsFrame
Definition at line 23 of file syscalls.hpp.
Macro Definition Documentation
SysFrm
#define SysFrm SyscallsFrame
Definition at line 66 of file syscalls.hpp.
Typedef Documentation
SyscallsFrame
typedef struct SyscallsFrame SyscallsFrame
Function Documentation
HandleLinuxSyscalls()
uintptr_t HandleLinuxSyscalls (SyscallsFrame * Frame)
Definition at line 4259 of file syscall.cpp.
 {
 #if defined(a64)
     if (Frame->rax > sizeof(LinuxSyscallsTableAMD64) / sizeof(SyscallData))
     {
         fixme("Syscall %d not implemented",
               Frame->rax);
         return -linux_ENOSYS;
     }
     SyscallData Syscall = LinuxSyscallsTableAMD64[Frame->rax];
     long (*call)(SysFrm *, long, ...) = r_cst(long (*)(SysFrm *, long, ...),
                                               Syscall.Handler);
     if (unlikely(!call))
     {
         fixme("Syscall %s(%d) not implemented",
               Syscall.Name, Frame->rax);
         return -linux_ENOSYS;
     }
     debug("> [%d:\"%s\"]( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
           Frame->rax, Syscall.Name,
           Frame->rdi, Frame->rsi, Frame->rdx,
           Frame->r10, Frame->r8, Frame->r9);
     long sc_ret = call(Frame,
                        Frame->rdi, Frame->rsi, Frame->rdx,
                        Frame->r10, Frame->r8, Frame->r9);
     debug("< [%ld:\"%s\"] = %ld", Frame->rax, Syscall.Name, sc_ret);
     return sc_ret;
 #elif defined(a32)
     if (Frame->eax > sizeof(LinuxSyscallsTableI386) / sizeof(SyscallData))
     {
         fixme("Syscall %d not implemented",
               Frame->eax);
         return -linux_ENOSYS;
     }
     SyscallData Syscall = LinuxSyscallsTableI386[Frame->eax];
     long (*call)(SysFrm *, long, ...) = r_cst(long (*)(SysFrm *, long, ...),
                                               Syscall.Handler);
     if (unlikely(!call))
     {
         fixme("Syscall %s(%d) not implemented",
               Syscall.Name, Frame->eax);
         return -linux_ENOSYS;
     }
     debug("> [%d:\"%s\"]( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
           Frame->eax, Syscall.Name,
           Frame->ebx, Frame->ecx, Frame->edx,
           Frame->esi, Frame->edi, Frame->ebp);
     int sc_ret = call(Frame,
                       Frame->ebx, Frame->ecx, Frame->edx,
                       Frame->esi, Frame->edi, Frame->ebp);
     debug("< [%d:\"%s\"] = %d", Frame->eax, Syscall.Name, sc_ret);
     return sc_ret;
 #elif defined(aa64)
     return -linux_ENOSYS;
 #endif
 #if defined(a64)
     UNUSED(LinuxSyscallsTableI386);
 #elif defined(a32)
     UNUSED(LinuxSyscallsTableAMD64);
 #endif
 }
References call(), debug, fixme, SyscallData::Handler, linux_ENOSYS, LinuxSyscallsTableAMD64, LinuxSyscallsTableI386, SyscallData::Name, SysFrm, unlikely, and UNUSED.
Referenced by SystemCallsHandler().
HandleNativeSyscalls()
uintptr_t HandleNativeSyscalls (SyscallsFrame * Frame)
Referenced by SystemCallsHandler().
InitializeSystemCalls()
void InitializeSystemCalls ()
Initialize syscalls for the current CPU. (Function is available on x32, x64 & aarch64)
Definition at line 29 of file syscalls.cpp.
 {
 }
References GDT_KERNEL_CODE, GDT_KERNEL_DATA, CPU::x64::MSR_EFER, CPU::x64::MSR_LSTAR, CPU::x64::MSR_STAR, CPU::x64::MSR_SYSCALL_MASK, and SystemCallHandlerStub().
Referenced by Interrupts::Initialize().