Fennix: Userspace/musl/src/linux/settimeofday.c File Reference
settimeofday.c File Reference
#include <sys/time.h>
#include <time.h>
#include <errno.h>
#include "syscall.h"
Macros
#define _BSD_SOURCE
Functions
int settimeofday (const struct timeval *tv, const struct timezone *tz)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file settimeofday.c.
Function Documentation
settimeofday()
int settimeofday (const struct timeval * tv, const struct timezone * tz)
Definition at line 7 of file settimeofday.c.
 {
     if (!tv) return 0;
     if (tv->tv_usec >= 1000000ULL) return __syscall_ret(-EINVAL);
     return clock_settime(CLOCK_REALTIME, &((struct timespec){
         .tv_sec = tv->tv_sec, .tv_nsec = tv->tv_usec * 1000}));
 }
References __syscall_ret(), clock_settime(), EINVAL, timeval::tv_sec, and timeval::tv_usec.
Referenced by __settimeofday_time32(), and stime().