Fennix Kernel: vfs::Virtual Class Reference
vfs::Virtual Class Reference
#include <filesystem.hpp>
Data Structures
struct CacheNode
struct FSMountInfo
Public Member Functions
bool PathIsRelative (const char *Path)
bool PathIsAbsolute (const char *Path)
dev_t EarlyReserveDevice ()
int LateRegisterFileSystem (dev_t Device, FileSystemInfo *fsi, Inode *Root)
dev_t RegisterFileSystem (FileSystemInfo *fsi, Inode *Root)
int UnregisterFileSystem (dev_t Device)
void AddRoot (Inode *Root)
FileNode * GetRoot (size_t Index)
FileNode * Create (FileNode *Parent, const char *Name, mode_t Mode)
FileNode * ForceCreate (FileNode *Parent, const char *Name, mode_t Mode)
FileNode * Mount (FileNode *Parent, Inode *Node, const char *Path)
int Unmount (const char *Path)
FileNode * GetByPath (const char *Path, FileNode *Parent)
std::string GetByNode (FileNode *Node)
FileNode * CreateLink (const char *Path, FileNode *Parent, const char *Target)
FileNode * CreateLink (const char *Path, FileNode *Parent, FileNode *Target)
bool PathExists (const char *Path, FileNode *Parent)
int Remove (FileNode *Node)
void Initialize ()
Virtual ()
~Virtual ()
Data Fields
vfsInode * FileSystemRoots = nullptr
std::unordered_map< ino_t, FileNode * > FileRoots
Private Member Functions
NewLock (VirtualLock)
FileNode * CacheSearchReturnLast (FileNode *Parent, const char **Path)
FileNode * CacheRecursiveSearch (FileNode *Root, const char *NameOrPath, bool IsName)
FileNode * CacheLookup (const char *Path)
FileNode * CreateCacheNode (FileNode *Parent, Inode *Node, const char *Name, mode_t Mode)
int RemoveCacheNode (FileNode *Node)
Private Attributes
std::unordered_map< dev_t, FSMountInfo > DeviceMap
std::atomic_bool RegisterLock = false
Detailed Description
Definition at line 95 of file filesystem.hpp.
Data Structure Documentation
vfs::Virtual::CacheNode
struct vfs::Virtual::CacheNode
Definition at line 106 of file filesystem.hpp.
Data Fields
FileNode * fn
atomic_int References
vfs::Virtual::FSMountInfo
struct vfs::Virtual::FSMountInfo
Definition at line 100 of file filesystem.hpp.
Data Fields
FileSystemInfo * fsi
Inode * Root
Constructor & Destructor Documentation
Virtual()
vfs::Virtual::Virtual ()
Definition at line 223 of file virtual.cpp.
     {
         SmartLock(VirtualLock);
         FileSystemRoots = new vfsInode;
         FileSystemRoots->Node.Index = -1;
         FileSystemRoots->Node.Mode = S_IRWXU |
                                      S_IRWXG |
                                      S_IROTH | S_IXOTH |
                                      S_IFDIR;
         FileSystemRoots->Node.Flags = I_FLAG_ROOT | I_FLAG_MOUNTPOINT | I_FLAG_CACHE_KEEP;
         FileSystemRoots->Node.Offset = INT32_MAX;
         FileSystemRoots->Name = "<ROOT>";
         FileSystemInfo *fsi = new FileSystemInfo;
         fsi->Name = "Virtual Roots";
         fsi->RootName = "ROOT";
         fsi->Flags = I_FLAG_ROOT | I_FLAG_MOUNTPOINT | I_FLAG_CACHE_KEEP;
         fsi->SuperOps = {};
         fsi->Ops.Lookup = __vfs_Lookup;
         fsi->Ops.Create = __vfs_Create;
         fsi->Ops.ReadDir = __vfs_Readdir;
         fsi->Ops.ReadLink = __vfs_ReadLink;
         FileSystemRoots->Node.Device = this->RegisterFileSystem(fsi, &FileSystemRoots->Node);
         FileSystemRoots->Node.SetDevice(0, 0);
     }
References vfs::__vfs_Create(), vfs::__vfs_Lookup(), vfs::__vfs_ReadLink(), InodeOperations::Create, Inode::Device, FileSystemRoots, Inode::Flags, FileSystemInfo::Flags, I_FLAG_CACHE_KEEP, I_FLAG_MOUNTPOINT, I_FLAG_ROOT, Inode::Index, INT32_MAX, InodeOperations::Lookup, Inode::Mode, vfs::vfsInode::Name, FileSystemInfo::Name, vfs::vfsInode::Node, Inode::Offset, FileSystemInfo::Ops, InodeOperations::ReadDir, InodeOperations::ReadLink, RegisterFileSystem(), FileSystemInfo::RootName, S_IFDIR, S_IROTH, S_IRWXG, S_IRWXU, S_IXOTH, and FileSystemInfo::SuperOps.
~Virtual()
vfs::Virtual::~Virtual ()
Definition at line 254 of file virtual.cpp.
     {
     }
Member Function Documentation
AddRoot()
void vfs::Virtual::AddRoot (Inode * Root)
Definition at line 34 of file filesystem.cpp.
     {
         SmartLock(VirtualLock);
         FileSystemRoots->Children.push_back(Root);
     }
References vfs::vfsInode::Children, and FileSystemRoots.
Referenced by TestAndInitializeUSTAR().
CacheLookup()
FileNode * vfs::Virtual::CacheLookup (const char * Path) private
Definition at line 178 of file cache.cpp.
     {
         debug("Cache lookup for \"%s\"", Path);
         FileNode *rootNode = thisProcess ? thisProcess->Info.RootNode : this->GetRoot(0);
         FileNode *ret = CacheRecursiveSearch(rootNode, Path, false);
         if (ret)
             return ret;
         debug("Path \"%s\" not found", Path);
         return nullptr;
     }
References CacheRecursiveSearch(), debug, GetRoot(), ret, and thisProcess.
Referenced by PathExists().
CacheRecursiveSearch()
FileNode * vfs::Virtual::CacheRecursiveSearch (FileNode * Root, const char * NameOrPath, bool IsName) private
Definition at line 97 of file cache.cpp.
     {
         if (Root == nullptr)
             return nullptr;
         debug("%s cache search for \"%s\" in \"%s\"",
               IsName ? "Relative" : "Absolute",
               NameOrPath,
               Root->Path.c_str());
         struct cwk_segment segment;
         if (!cwk_path_get_first_segment(NameOrPath, &segment))
         {
             if (strcmp(NameOrPath, Root->fsi->RootName) == 0)
                 return Root;
             ReturnLogError(nullptr, "Failed to get first segment of path");
         }
         size_t segments = 0;
         while (cwk_path_get_next_segment(&segment))
             segments++;
         if (IsName && segments == 0)
         {
             for (FileNode *fn : Root->Children)
             {
                 if (fn->Name == NameOrPath)
                     return fn;
             }
             ReturnLogError(nullptr, "Failed to find \"%s\" in \"%s\"", NameOrPath, Root->Path.c_str());
         }
         const char *path = NameOrPath;
         if (strncmp(path, "\x06root-", 6) == 0) /* FIXME: deduce the index */
         {
             path += 6;
             while (*path != '\0' && *path != '\x06')
                 path++;
             if (*path == '\x06')
                 path++;
         }
         else
             path = NameOrPath;
         FileNode *__Parent = Root;
         if (this->PathIsAbsolute(path))
         {
             /* Get the root if Root is not the root _? */
             while (__Parent->Parent)
                 __Parent = __Parent->Parent;
         }
         cwk_path_get_first_segment(path, &segment);
         do
         {
             std::string segmentName(segment.begin, segment.size);
             bool found = false;
             for (FileNode *fn : __Parent->Children)
             {
                 if (fn->Name != segmentName)
                     continue;
                 cwk_segment __seg = segment;
                 if (!cwk_path_get_next_segment(&__seg))
                     return fn;
                 __Parent = fn;
                 found = true;
                 break;
             }
             if (!found)
                 break;
         } while (cwk_path_get_next_segment(&segment));
         debug("Failed to find \"%s\" in \"%s\"", NameOrPath, Root->Path.c_str());
         return nullptr;
     }
References cwk_segment::begin, FileNode::Children, cwk_path_get_first_segment(), cwk_path_get_next_segment(), debug, FileNode::fsi, FileNode::Name, FileNode::Parent, cwk_segment::path, FileNode::Path, PathIsAbsolute(), ReturnLogError, FileSystemInfo::RootName, cwk_segment::segments, cwk_segment::size, strcmp(), and strncmp().
Referenced by CacheLookup(), and GetByPath().
CacheSearchReturnLast()
FileNode * vfs::Virtual::CacheSearchReturnLast (FileNode * Parent, const char ** Path) private
Definition at line 29 of file cache.cpp.
     {
         assert(Parent != nullptr);
         struct cwk_segment segment;
         if (!cwk_path_get_first_segment(*Path, &segment))
         {
             if (strcmp(*Path, Parent->fsi->RootName) == 0)
                 return Parent;
             ReturnLogError(nullptr, "Failed to get first segment of path");
         }
         size_t segments = 0;
         while (cwk_path_get_next_segment(&segment))
             segments++;
         if (segments == 0)
             return Parent;
         const char *tmpPath = *Path;
         if (strncmp(tmpPath, "\x06root-", 6) == 0) /* FIXME: deduce the index */
         {
             tmpPath += 6;
             while (*tmpPath != '\0' && *tmpPath != '\x06')
                 tmpPath++;
             if (*tmpPath == '\x06')
                 tmpPath++;
         }
         else
             tmpPath = *Path;
         FileNode *__Parent = Parent;
         if (this->PathIsAbsolute(tmpPath))
         {
             while (__Parent->Parent)
                 __Parent = __Parent->Parent;
         }
         cwk_path_get_first_segment(tmpPath, &segment);
         do
         {
             std::string segmentName(segment.begin, segment.size);
             bool found = false;
             for (FileNode *fn : __Parent->Children)
             {
                 if (fn->Name != segmentName)
                     continue;
                 cwk_segment __seg = segment;
                 assert(cwk_path_get_next_segment(&__seg)); /* There's something wrong */
                 __Parent = fn;
                 found = true;
                 break;
             }
             if (!found)
             {
                 *Path = segment.begin;
                 break;
             }
         } while (cwk_path_get_next_segment(&segment));
         return __Parent;
     }
References assert, cwk_segment::begin, FileNode::Children, cwk_path_get_first_segment(), cwk_path_get_next_segment(), FileNode::fsi, FileNode::Name, FileNode::Parent, PathIsAbsolute(), ReturnLogError, FileSystemInfo::RootName, cwk_segment::segments, cwk_segment::size, strcmp(), and strncmp().
Referenced by GetByPath().
Create()
FileNode * vfs::Virtual::Create (FileNode * Parent, const char * Name, mode_t Mode)
Definition at line 56 of file filesystem.cpp.
     {
         FileNode *existingNode = this->GetByPath(Name, Parent);
         if (existingNode != nullptr)
             ReturnLogError(existingNode, "File %s already exists", Name);
         if (Parent == nullptr)
         {
             assert(thisProcess != nullptr);
             Parent = thisProcess->Info.RootNode;
         }
         auto it = DeviceMap.find(Parent->Node->Device);
         if (it == DeviceMap.end())
             ReturnLogError(nullptr, "Device %d not found", Parent->Node->Device);
         Inode *Node = NULL;
         if (it->second.fsi->Ops.Create == NULL)
             ReturnLogError(nullptr, "Create not supported for %d", it->first);
         int ret = it->second.fsi->Ops.Create(Parent->Node, Name, Mode, &Node);
         if (ret < 0)
             ReturnLogError(nullptr, "Create for %d failed with %d", it->first, ret);
         return this->CreateCacheNode(Parent, Node, Name, Mode);
     }
References assert, CreateCacheNode(), Inode::Device, DeviceMap, GetByPath(), it, Name, FileNode::Node, vfs::Node, NULL, ret, ReturnLogError, and thisProcess.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), DiagnosticDataCollection(), vfs::FileDescriptorTable::FileDescriptorTable(), ForceCreate(), linux_mkdir(), and Tasking::PCB::PCB().
CreateCacheNode()
FileNode * vfs::Virtual::CreateCacheNode (FileNode * Parent, Inode * Node, const char * Name, mode_t Mode) private
Definition at line 191 of file cache.cpp.
     {
         FileNode *fn = new FileNode;
         fn->Name = Name;
         if (Parent)
         {
             fn->Path = Parent->Path + "/" + Name;
             Parent->Children.push_back(fn);
         }
         else
             fn->Path = Name;
         fn->Parent = Parent;
         fn->Node = Node;
         fn->fsi = DeviceMap[Node->Device].fsi;
         if (fn->fsi == nullptr)
             warn("Failed to find filesystem for device %d", Node->Device);
         debug("Created cache node %s", fn->Path.c_str());
         return fn;
     }
References FileNode::Children, debug, DeviceMap, FileNode::fsi, FileNode::Name, Name, FileNode::Node, vfs::Node, FileNode::Parent, FileNode::Path, and warn.
Referenced by Create(), CreateLink(), GetByPath(), GetRoot(), and Mount().
CreateLink() [1/2]
FileNode * vfs::Virtual::CreateLink (const char * Path, FileNode * Parent, const char * Target)
Definition at line 236 of file filesystem.cpp.
     {
         auto it = DeviceMap.find(Parent->Node->Device);
         if (it == DeviceMap.end())
             ReturnLogError(nullptr, "Device %d not found", Parent->Node->Device);
         Inode *Node = NULL;
         if (it->second.fsi->Ops.SymLink == NULL)
             ReturnLogError(nullptr, "SymLink not supported for %d", it->first);
         int ret = it->second.fsi->Ops.SymLink(Parent->Node, Path, Target, &Node);
         if (ret < 0)
             ReturnLogError(nullptr, "SymLink for %d failed with %d", it->first, ret);
         return this->CreateCacheNode(Parent, Node, Path, 0);
     }
References CreateCacheNode(), Inode::Device, DeviceMap, it, FileNode::Node, vfs::Node, NULL, ret, and ReturnLogError.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), CreateLink(), Tasking::PCB::SetExe(), and Tasking::PCB::SetWorkingDirectory().
CreateLink() [2/2]
FileNode * vfs::Virtual::CreateLink (const char * Path, FileNode * Parent, FileNode * Target)
Definition at line 253 of file filesystem.cpp.
     {
         return this->CreateLink(Path, Parent, Target->Path.c_str());
     }
References CreateLink(), and FileNode::Path.
EarlyReserveDevice()
dev_t vfs::Virtual::EarlyReserveDevice ()
Reserve a device number for a filesystem
Note
After this function is called, the filesystem must call LateRegisterFileSystem to release the lock
Definition at line 178 of file virtual.cpp.
     {
         RegisterLock.store(true);
         size_t len = DeviceMap.size();
         return len;
     }
References DeviceMap, len, and RegisterLock.
Referenced by TestAndInitializeUSTAR().
ForceCreate()
FileNode * vfs::Virtual::ForceCreate (FileNode * Parent, const char * Name, mode_t Mode)
Definition at line 83 of file filesystem.cpp.
     {
         fixme("ForceCreate: %s", Name);
         return this->Create(Parent, Name, Mode);
     }
References Create(), vfs::fixme(), and Name.
Referenced by DiagnosticDataCollection(), Initialize(), Driver::Manager::RegisterBlockDevice(), and Driver::Manager::RegisterInputDevice().
GetByNode()
std::string vfs::Virtual::GetByNode (FileNode * Node)
Definition at line 207 of file filesystem.cpp.
     {
         assert(Node != nullptr);
         if (Node->Parent == nullptr)
         {
             if (Node->Node->Flags & I_FLAG_ROOT)
                 return Node->fsi->RootName;
             assert(Node->Parent != nullptr);
         }
         std::string path;
         auto appendPath = [&path](const char *name)
         {
             if (path.size() > 0)
                 path += "/";
             path += name;
         };
         FileNode *current = Node;
         while (current->Parent != nullptr)
         {
             appendPath(current->Name.c_str());
             current = current->Parent;
         }
         return path;
     }
References assert, Inode::Flags, I_FLAG_ROOT, FileNode::Name, vfs::vfsInode::Node, vfs::Node, and FileNode::Parent.
Referenced by KShellThread().
GetByPath()
FileNode * vfs::Virtual::GetByPath (const char * Path, FileNode * Parent)
Definition at line 113 of file filesystem.cpp.
     {
         debug("GetByPath: %s", Path);
         if (Parent == nullptr || this->PathIsAbsolute(Path))
             Parent = thisProcess ? thisProcess->Info.RootNode : this->GetRoot(0);
         if (strcmp(Path, ".") == 0)
             return Parent;
         if (strcmp(Path, "..") == 0)
             return Parent->Parent ? Parent->Parent : Parent;
         FileNode *fn = this->CacheRecursiveSearch(Parent, Path, this->PathIsRelative(Path));
         if (fn)
             return fn;
         if (strncmp(Path, "\x06root-", 6) == 0) /* FIXME: deduce the index */
         {
             Path += 7;
             while (*Path != '\0' && *Path != '\x06')
                 Path++;
             if (*Path == '\x06')
                 Path++;
         }
         FileNode *__Parent = CacheSearchReturnLast(Parent, &Path);
         struct cwk_segment segment;
         if (!cwk_path_get_first_segment(Path, &segment))
         {
             auto it = DeviceMap.find(Parent->Node->Device);
             if (unlikely(it == DeviceMap.end()))
                 ReturnLogError(nullptr, "Device %d not found", Parent->Node->Device);
             if (it->second.fsi->Ops.Lookup == NULL)
                 ReturnLogError(nullptr, "Lookup not supported for %d", it->first);
             Inode *Node = NULL;
             int ret = it->second.fsi->Ops.Lookup(Parent->Node, Path, &Node);
             if (ret < 0)
                 ReturnLogError(nullptr, "Lookup for \"%s\"(%d) failed with %d", Path, it->first, ret);
             if (Parent->Node == Node) /* root / */
             {
                 debug("Returning root (%#lx)", Node);
                 return Parent;
             }
             ReturnLogError(nullptr, "Path has no segments");
         }
         Inode *Node = NULL;
         do
         {
             auto it = DeviceMap.find(__Parent->Node->Device);
             if (unlikely(it == DeviceMap.end()))
                 ReturnLogError(nullptr, "Device %d not found", __Parent->Node->Device);
             if (it->second.fsi->Ops.Lookup == NULL)
                 ReturnLogError(nullptr, "Lookup not supported for %d", it->first);
             std::string segmentName(segment.begin, segment.size);
             int ret = it->second.fsi->Ops.Lookup(__Parent->Node, segmentName.c_str(), &Node);
             if (ret < 0)
                 ReturnLogError(nullptr, "Lookup for \"%s\"(%d) failed with %d", segmentName.c_str(), it->first, ret);
             __Parent = this->CreateCacheNode(__Parent, Node, segmentName.c_str(), 0);
         } while (cwk_path_get_next_segment(&segment));
         FileNode *ret = __Parent;
         if (!ret->IsDirectory())
             return ret;
         auto it = DeviceMap.find(__Parent->Node->Device);
         if (unlikely(it == DeviceMap.end()))
             ReturnLogError(nullptr, "Device %d not found", __Parent->Node->Device);
         size_t dirAllocLen = sizeof(struct kdirent) + strlen(Path);
         struct kdirent *dirent = (struct kdirent *)malloc(dirAllocLen);
         size_t offset = 2; /* Skip . and .. */
         while (it->second.fsi->Ops.ReadDir(Node, dirent, dirAllocLen, offset++, 1) > 0)
         {
             Inode *ChildNode = NULL;
             int luRet = it->second.fsi->Ops.Lookup(Node, dirent->d_name, &ChildNode);
             if (luRet < 0)
             {
                 debug("Lookup for %d failed with %d", it->first, luRet);
                 break;
             }
             this->CreateCacheNode(ret, ChildNode, dirent->d_name, 0);
         }
         free(dirent);
         return ret;
     }
References cwk_segment::begin, CacheRecursiveSearch(), CacheSearchReturnLast(), CreateCacheNode(), cwk_path_get_first_segment(), cwk_path_get_next_segment(), kdirent::d_name, debug, Inode::Device, DeviceMap, free(), GetRoot(), it, malloc(), FileNode::Node, vfs::Node, NULL, FileNode::Parent, PathIsAbsolute(), PathIsRelative(), ret, ReturnLogError, cwk_segment::size, strcmp(), strlen(), strncmp(), thisProcess, and unlikely.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), cmd_cat(), cmd_cd(), cmd_ls(), cmd_tree(), Create(), Execute::ELFObject::ELFObject(), Execute::GetBinaryType(), Driver::Manager::InitializeDaemonFS(), KShellThread(), KernelConsole::LateInit(), linux_chdir(), linux_newfstatat(), linux_open(), linux_openat(), linux_uname(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), Mount(), PathExists(), Tasking::PCB::PCB(), Driver::Manager::PreloadDrivers(), Driver::Manager::RegisterBlockDevice(), Driver::Manager::RegisterInputDevice(), Tasking::PCB::SetExe(), KernelConsole::SetTheme(), Tasking::PCB::SetWorkingDirectory(), Execute::Spawn(), tree_loop(), Unmount(), vfs::FileDescriptorTable::usr_lstat(), and vfs::FileDescriptorTable::usr_stat().
GetRoot()
FileNode * vfs::Virtual::GetRoot (size_t Index)
Definition at line 40 of file filesystem.cpp.
     {
         assert(Index < FileSystemRoots->Children.size());
         auto it = FileRoots.find(Index);
         if (it != FileRoots.end())
             return it->second;
         Inode *rootNode = FileSystemRoots->Children[Index];
         char rootName[128]{};
         snprintf(rootName, sizeof(rootName), "\x06root-%ld\x06", Index);
         FileNode *ret = this->CreateCacheNode(nullptr, rootNode, rootName, 0);
         FileRoots.insert({Index, ret});
         return ret;
     }
References assert, vfs::vfsInode::Children, CreateCacheNode(), FileRoots, FileSystemRoots, it, ret, and snprintf().
Referenced by CacheLookup(), cmd_ls(), cmd_tree(), GetByPath(), Initialize(), Driver::Manager::InitializeDaemonFS(), KernelMainThread(), KShellThread(), and Tasking::TCB::TCB().
Initialize()
void vfs::Virtual::Initialize ()
Definition at line 149 of file virtual.cpp.
     {
         SmartLock(VirtualLock);
         trace("Initializing virtual file system...");
         uint32_t iFlags = I_FLAG_CACHE_KEEP;
         /* d rwx rwx rwx */
         mode_t mode = S_IRWXU |
                       S_IRWXG |
                       S_IRWXO |
                       S_IFDIR;
         FileNode *proc = this->ForceCreate(this->GetRoot(0), "proc", mode);
         FileNode *var = this->ForceCreate(this->GetRoot(0), "var", mode);
         FileNode *log = this->ForceCreate(var, "log", mode);
         proc->Node->Flags = iFlags;
         log->Node->Flags = iFlags;
         /* l rwx rwx rwx */
         mode = S_IRWXU |
                S_IRWXG |
                S_IRWXO |
                S_IFLNK;
         FileNode *self = this->ForceCreate(proc, "self", mode);
         self->Node->Device = FileSystemRoots->Node.Device;
         self->Node->SetDevice(0, 1);
         self->Node->Flags = iFlags;
     }
References Inode::Device, FileSystemRoots, Inode::Flags, ForceCreate(), GetRoot(), I_FLAG_CACHE_KEEP, FileNode::Node, vfs::vfsInode::Node, S_IFDIR, S_IFLNK, S_IRWXG, S_IRWXO, S_IRWXU, and trace.
Referenced by KernelVFS().
LateRegisterFileSystem()
int vfs::Virtual::LateRegisterFileSystem (dev_t Device, FileSystemInfo * fsi, Inode * Root)
Register a filesystem after the device number has been reserved
Definition at line 185 of file virtual.cpp.
     {
         auto it = DeviceMap.find(Device);
         if (it != DeviceMap.end())
             ReturnLogError(-EEXIST, "Device %d already registered", Device);
         Root->Flags |= I_FLAG_ROOT;
         FSMountInfo fsmi{.fsi = fsi, .Root = Root};
         DeviceMap.insert({Device, fsmi});
         RegisterLock.store(false);
         return 0;
     }
References DeviceMap, EEXIST, Inode::Flags, vfs::Virtual::FSMountInfo::fsi, I_FLAG_ROOT, it, RegisterLock, and ReturnLogError.
Referenced by TestAndInitializeUSTAR().
Mount()
FileNode * vfs::Virtual::Mount (FileNode * Parent, Inode * Node, const char * Path)
Definition at line 89 of file filesystem.cpp.
     {
         char *path = strdup(Path);
         char *lastSlash = strrchr(path, '/');
         if (lastSlash == path)
             lastSlash++;
         *lastSlash = '\0';
         FileNode *parentNode = this->GetByPath(path, Parent);
         free(path);
         lastSlash = strrchr(Path, '/');
         lastSlash++;
         return this->CreateCacheNode(parentNode, Node, lastSlash, Node->Mode);
     }
References CreateCacheNode(), free(), GetByPath(), vfs::Node, strdup(), and strrchr().
Referenced by Driver::Manager::InitializeDaemonFS().
NewLock()
vfs::Virtual::NewLock (VirtualLock) private
PathExists()
bool vfs::Virtual::PathExists (const char * Path, FileNode * Parent)
Definition at line 258 of file filesystem.cpp.
     {
         FileNode *fn = this->CacheLookup(Path);
         if (fn)
             return true;
         FileNode *Node = this->GetByPath(Path, Parent);
         if (Node)
             return true;
         return false;
     }
References CacheLookup(), GetByPath(), and vfs::Node.
Referenced by DiagnosticDataCollection(), KShellThread(), and linux_access().
PathIsAbsolute()
bool vfs::Virtual::PathIsAbsolute (const char * Path) inline
Definition at line 127 of file filesystem.hpp.
 { return !PathIsRelative(Path); }
References PathIsRelative().
Referenced by CacheRecursiveSearch(), CacheSearchReturnLast(), GetByPath(), and linux_newfstatat().
PathIsRelative()
bool vfs::Virtual::PathIsRelative (const char * Path)
Definition at line 29 of file filesystem.cpp.
     {
         return cwk_path_is_relative(Path);
     }
References cwk_path_is_relative().
Referenced by GetByPath(), KShellThread(), linux_openat(), and PathIsAbsolute().
RegisterFileSystem()
dev_t vfs::Virtual::RegisterFileSystem (FileSystemInfo * fsi, Inode * Root)
Definition at line 198 of file virtual.cpp.
     {
         RegisterLock.store(true);
         size_t len = DeviceMap.size();
         Root->Flags |= I_FLAG_ROOT;
         FSMountInfo fsmi{.fsi = fsi, .Root = Root};
         DeviceMap.insert({len, fsmi});
         RegisterLock.store(false);
         return len;
     }
References DeviceMap, Inode::Flags, vfs::Virtual::FSMountInfo::fsi, I_FLAG_ROOT, len, and RegisterLock.
Referenced by Driver::Manager::InitializeDaemonFS(), v0::RegisterFileSystem(), and Virtual().
Remove()
int vfs::Virtual::Remove (FileNode * Node)
Definition at line 270 of file filesystem.cpp.
     {
         auto it = DeviceMap.find(Node->Node->Device);
         if (it == DeviceMap.end())
             ReturnLogError(-ENODEV, "Device %d not found", Node->Node->Device);
         if (it->second.fsi->Ops.Remove == NULL)
             ReturnLogError(-ENOTSUP, "Remove not supported for %d", it->first);
         int ret = it->second.fsi->Ops.Remove(Node->Parent->Node, Node->Name.c_str());
         if (ret < 0)
             ReturnLogError(ret, "Remove for %d failed with %d", it->first, ret);
         this->RemoveCacheNode(Node);
         return 0;
     }
References Inode::Device, DeviceMap, ENODEV, ENOTSUP, it, vfs::vfsInode::Name, vfs::vfsInode::Node, vfs::Node, NULL, RemoveCacheNode(), ret, and ReturnLogError.
Referenced by vfs::FileDescriptorTable::RemoveFileDescriptor(), Tasking::PCB::SetExe(), and Tasking::PCB::SetWorkingDirectory().
RemoveCacheNode()
int vfs::Virtual::RemoveCacheNode (FileNode * Node) private
Definition at line 212 of file cache.cpp.
     {
         if (Node == nullptr)
             return -EINVAL;
         if (Node->Parent)
         {
             Node->Parent->Children.erase(std::find(Node->Parent->Children.begin(), Node->Parent->Children.end(), Node));
             // delete Node;
             fixme("Node deletion is disabled for now (for debugging purposes)");
         }
         return 0;
     }
References vfs::vfsInode::Children, EINVAL, vfs::fixme(), and vfs::Node.
Referenced by Remove(), and Unmount().
Unmount()
int vfs::Virtual::Unmount (const char * Path)
Definition at line 104 of file filesystem.cpp.
     {
         FileNode *node = this->GetByPath(Path, nullptr);
         if (node == nullptr)
             ReturnLogError(-ENOENT, "Path %s not found", Path);
         return this->RemoveCacheNode(node);
     }
References ENOENT, GetByPath(), RemoveCacheNode(), and ReturnLogError.
UnregisterFileSystem()
int vfs::Virtual::UnregisterFileSystem (dev_t Device)
Definition at line 209 of file virtual.cpp.
     {
         auto it = DeviceMap.find(Device);
         if (it == DeviceMap.end())
             ReturnLogError(-ENOENT, "Device %d not found", Device);
         if (it->second.fsi->SuperOps.Synchronize)
             it->second.fsi->SuperOps.Synchronize(it->second.fsi, NULL);
         if (it->second.fsi->SuperOps.Destroy)
             it->second.fsi->SuperOps.Destroy(it->second.fsi);
         DeviceMap.erase(it);
         return 0;
     }
References DeviceMap, ENOENT, it, NULL, and ReturnLogError.
Referenced by v0::UnregisterFileSystem().
Field Documentation
DeviceMap
std::unordered_map<dev_t, FSMountInfo> vfs::Virtual::DeviceMap private
Definition at line 112 of file filesystem.hpp.
Referenced by Create(), CreateCacheNode(), CreateLink(), EarlyReserveDevice(), GetByPath(), LateRegisterFileSystem(), RegisterFileSystem(), Remove(), and UnregisterFileSystem().
FileRoots
std::unordered_map<ino_t, FileNode *> vfs::Virtual::FileRoots
Definition at line 124 of file filesystem.hpp.
Referenced by GetRoot().
FileSystemRoots
vfsInode* vfs::Virtual::FileSystemRoots = nullptr
Definition at line 123 of file filesystem.hpp.
Referenced by AddRoot(), GetRoot(), Initialize(), and Virtual().
RegisterLock
std::atomic_bool vfs::Virtual::RegisterLock = false private
Definition at line 113 of file filesystem.hpp.
Referenced by EarlyReserveDevice(), LateRegisterFileSystem(), and RegisterFileSystem().
The documentation for this class was generated from the following files:
Kernel/include/filesystem.hpp
Kernel/storage/cache.cpp
Kernel/storage/filesystem.cpp
Kernel/storage/virtual.cpp