Fennix Kernel: PCNET Namespace Reference
PCNET Namespace Reference
Data Structures
struct BARData
Functions
void WriteRAP32 (uint32_t Value)
void WriteRAP16 (uint16_t Value)
uint32_t ReadCSR32 (uint32_t CSR)
uint16_t ReadCSR16 (uint16_t CSR)
void WriteCSR32 (uint32_t CSR, uint32_t Value)
void WriteCSR16 (uint16_t CSR, uint16_t Value)
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *)
Variables
KernelAPI KAPI
PCIDeviceHeader * PCIBaseAddress
BARData BAR
MediaAccessControl MAC
InternetProtocol::Version4 IP
Data Structure Documentation
PCNET::BARData
struct PCNET::BARData
Definition at line 26 of file pcnet.hpp.
Data Fields
uint16_t IOBase
uint64_t MemoryBase
uint8_t Type
Function Documentation
CallbackHandler()
int PCNET::CallbackHandler (KernelCallback * Data)
Definition at line 77 of file PCNET.cpp.
     {
         switch (Data->Reason)
         {
         case AcknowledgeReason:
         {
             debug("Kernel acknowledged the driver.");
             break;
         }
         case ConfigurationReason:
         {
             debug("Module received configuration data.");
             PCIBaseAddress = reinterpret_cast<PCIDeviceHeader *>(Data->RawPtr);
             if (PCIBaseAddress->VendorID == 0x1022 && PCIBaseAddress->DeviceID == 0x2000)
             {
                 trace("Found AMD PCNET.");
                 uint32_t PCIBAR = ((PCIHeader0 *)PCIBaseAddress)->BAR0;
                 BAR.Type = PCIBAR & 1;
                 BAR.IOBase = (uint16_t)(PCIBAR & (~3));
                 BAR.MemoryBase = PCIBAR & (~15);
             }
             else
                 return DEVICE_NOT_SUPPORTED;
             break;
         }
         case QueryReason:
         {
             memcpy(Data->NetworkCallback.Fetch.Name, (void *)"AMD PCNET", 10);
             Data->NetworkCallback.Fetch.MAC = MAC.ToHex();
             break;
         }
         case SendReason:
         {
             break;
         }
         case StopReason:
         {
             // TODO: Stop the driver.
             debug("Module stopped.");
             break;
         }
         default:
         {
             warn("Unknown reason.");
             break;
         }
         }
         return OK;
     }
References AcknowledgeReason, BAR, ConfigurationReason, Data, debug, DEVICE_NOT_SUPPORTED, PCI::PCIDeviceHeader::DeviceID, PCNET::BARData::IOBase, MAC, memcpy(), PCNET::BARData::MemoryBase, OK, PCIBaseAddress, QueryReason, SendReason, StopReason, MediaAccessControl::ToHex(), trace, PCNET::BARData::Type, PCI::PCIDeviceHeader::VendorID, and warn.
DriverEntry()
int PCNET::DriverEntry (void * Data)
Definition at line 67 of file PCNET.cpp.
     {
         if (!Data)
             return INVALID_KERNEL_API;
         KAPI = *(KernelAPI *)Data;
         if (KAPI.Version.Major < 0 || KAPI.Version.Minor < 0 || KAPI.Version.Patch < 0)
             return KERNEL_API_VERSION_NOT_SUPPORTED;
         return OK;
     }
References Data, INVALID_KERNEL_API, KAPI, KERNEL_API_VERSION_NOT_SUPPORTED, KernelAPI::KAPIVersion::Major, KernelAPI::KAPIVersion::Minor, OK, KernelAPI::KAPIVersion::Patch, and KernelAPI::Version.
Referenced by StartPCNET().
InterruptCallback()
int PCNET::InterruptCallback (CPURegisters *)
Definition at line 127 of file PCNET.cpp.
     {
         return OK;
     }
References OK.
ReadCSR16()
uint16_t PCNET::ReadCSR16 (uint16_t CSR)
Definition at line 49 of file PCNET.cpp.
     {
         WriteRAP32(CSR);
         return inportw(BAR.IOBase + 0x10);
     }
References BAR, PCNET::BARData::IOBase, and WriteRAP32().
ReadCSR32()
uint32_t PCNET::ReadCSR32 (uint32_t CSR)
Definition at line 43 of file PCNET.cpp.
     {
         WriteRAP32(CSR);
         return inportl(BAR.IOBase + 0x10);
     }
References BAR, PCNET::BARData::IOBase, and WriteRAP32().
WriteCSR16()
void PCNET::WriteCSR16 (uint16_t CSR, uint16_t Value)
Definition at line 61 of file PCNET.cpp.
     {
         WriteRAP16(CSR);
         outportw(BAR.IOBase + 0x10, Value);
     }
References BAR, PCNET::BARData::IOBase, and WriteRAP16().
WriteCSR32()
void PCNET::WriteCSR32 (uint32_t CSR, uint32_t Value)
Definition at line 55 of file PCNET.cpp.
     {
         WriteRAP32(CSR);
         outportl(BAR.IOBase + 0x10, Value);
     }
References BAR, PCNET::BARData::IOBase, and WriteRAP32().
WriteRAP16()
void PCNET::WriteRAP16 (uint16_t Value)
Definition at line 41 of file PCNET.cpp.
 { outportw(BAR.IOBase + 0x12, Value); }
References BAR, and PCNET::BARData::IOBase.
Referenced by WriteCSR16().
WriteRAP32()
void PCNET::WriteRAP32 (uint32_t Value)
Definition at line 40 of file PCNET.cpp.
 { outportl(BAR.IOBase + 0x14, Value); }
References BAR, and PCNET::BARData::IOBase.
Referenced by ReadCSR16(), ReadCSR32(), and WriteCSR32().
Variable Documentation
BAR
BARData PCNET::BAR
Definition at line 35 of file PCNET.cpp.
Referenced by CallbackHandler(), PCI::PCI::MapPCIAddresses(), ReadCSR16(), ReadCSR32(), WriteCSR16(), WriteCSR32(), WriteRAP16(), and WriteRAP32().
IP
InternetProtocol::Version4 PCNET::IP
Definition at line 38 of file PCNET.cpp.
KAPI
KernelAPI PCNET::KAPI
Definition at line 32 of file PCNET.cpp.
Referenced by DriverEntry().
MAC
MediaAccessControl PCNET::MAC
Definition at line 37 of file PCNET.cpp.
Referenced by CallbackHandler(), NetworkARP::ARP::ManageDiscoveredAddresses(), MediaAccessControl::operator==(), and NetworkEthernet::Ethernet::Send().
PCIBaseAddress
PCIDeviceHeader* PCNET::PCIBaseAddress
Definition at line 34 of file PCNET.cpp.
Referenced by CallbackHandler().