Fennix Userspace: Userspace/musl/src/misc/getsubopt.c File Reference
getsubopt.c File Reference
#include <stdlib.h>
#include <string.h>
Functions
int getsubopt (char **opt, char *const *keys, char **val)
Function Documentation
getsubopt()
int getsubopt (char ** opt, char *const * keys, char ** val)
Definition at line 4 of file getsubopt.c.
 {
     char *s = *opt;
     int i;
     *val = NULL;
     *opt = strchr(s, ',');
     if (*opt) *(*opt)++ = 0;
     else *opt = s + strlen(s);
     for (i=0; keys[i]; i++) {
         size_t l = strlen(keys[i]);
         if (strncmp(keys[i], s, l)) continue;
         if (s[l] == '=')
             *val = s + l + 1;
         else if (s[l]) continue;
         return i;
     }
     return -1;
 }
References i, keys, NULL, strchr(), strlen(), and strncmp().