Fennix: Userspace/apps/base/busybox/libbb/recursive_action.c File Reference
recursive_action.c File Reference
#include "libbb.h"
Functions
static int FAST_FUNC true_action (struct recursive_state *state UNUSED_PARAM, const char *fileName UNUSED_PARAM, struct stat *statbuf UNUSED_PARAM)
static int recursive_action1 (recursive_state_t *state, const char *fileName)
int FAST_FUNC recursive_action (const char *fileName, unsigned flags, int FAST_FUNC(*fileAction)(struct recursive_state *state, const char *fileName, struct stat *statbuf), int FAST_FUNC(*dirAction)(struct recursive_state *state, const char *fileName, struct stat *statbuf), void *userData)
Function Documentation
recursive_action()
int FAST_FUNC recursive_action (const char * fileName, unsigned flags, int FAST_FUNC(*)(struct recursive_state *state, const char *fileName, struct stat *statbuf) fileAction, int FAST_FUNC(*)(struct recursive_state *state, const char *fileName, struct stat *statbuf) dirAction, void * userData)
Definition at line 162 of file recursive_action.c.
 {
     /* Keeping a part of variables of recusive descent in a "state structure"
      * instead of passing ALL of them down as parameters of recursive_action1()
      * relieves register pressure, both in recursive_action1()
      * and in every file/dirAction().
      */
     recursive_state_t state;
     state.flags = flags;
     state.depth = 0;
     state.userData = userData;
     state.fileAction = fileAction ? fileAction : true_action;
     state.dirAction  =  dirAction ?  dirAction : true_action;
     return recursive_action1(&state, fileName);
 }
References dirAction(), fileAction(), fileName, flags, recursive_action1(), state, and true_action().
Referenced by chcon_main(), chmod_main(), depmod_main(), find_main(), grep_dir(), initial_scan(), lspci_main(), lsusb_main(), process_one(), read_config(), run_parts_main(), and uuidcache_init().
recursive_action1()
static int recursive_action1 (recursive_state_t * state, const char * fileName) static
Definition at line 67 of file recursive_action.c.
 {
     struct stat statbuf;
     unsigned follow;
     int status;
     DIR *dir;
     struct dirent *next;
     follow = ACTION_FOLLOWLINKS;
     if (state->depth == 0)
         follow = ACTION_FOLLOWLINKS | ACTION_FOLLOWLINKS_L0;
     follow &= state->flags;
     status = (follow ? stat : lstat)(fileName, &statbuf);
     if (status < 0) {
 #ifdef DEBUG_RECURS_ACTION
         bb_error_msg("status=%d flags=%x", status, state->flags);
 #endif
         if ((state->flags & ACTION_DANGLING_OK)
          && errno == ENOENT
          && lstat(fileName, &statbuf) == 0
         ) {
             /* Dangling link */
             return state->fileAction(state, fileName, &statbuf);
         }
         goto done_nak_warn;
     }
     /* If S_ISLNK(m), then we know that !S_ISDIR(m).
      * Then we can skip checking first part: if it is true, then
      * (!dir) is also true! */
     if ( /* (!(state->flags & ACTION_FOLLOWLINKS) && S_ISLNK(statbuf.st_mode)) || */
      !S_ISDIR(statbuf.st_mode)
     ) {
         return state->fileAction(state, fileName, &statbuf);
     }
     /* It's a directory (or a link to one, and followLinks is set) */
     if (!(state->flags & ACTION_RECURSE)) {
         return state->dirAction(state, fileName, &statbuf);
     }
     if (!(state->flags & ACTION_DEPTHFIRST)) {
         status = state->dirAction(state, fileName, &statbuf);
         if (status == FALSE)
             goto done_nak_warn;
         if (status == SKIP)
             return TRUE;
     }
     dir = opendir(fileName);
     if (!dir) {
         /* findutils-4.1.20 reports this */
         /* (i.e. it doesn't silently return with exit code 1) */
         /* To trigger: "find -exec rm -rf {} \;" */
         goto done_nak_warn;
     }
     status = TRUE;
     while ((next = readdir(dir)) != NULL) {
         char *nextFile;
         int s;
         nextFile = concat_subpath_file(fileName, next->d_name);
         if (nextFile == NULL)
             continue;
         /* process every file (NB: ACTION_RECURSE is set in flags) */
         state->depth++;
         s = recursive_action1(state, nextFile);
         if (s == FALSE)
             status = FALSE;
         free(nextFile);
         state->depth--;
 //#define RECURSE_RESULT_ABORT -1
 //      if (s == RECURSE_RESULT_ABORT) {
 //          closedir(dir);
 //          return s;
 //      }
     }
     closedir(dir);
     if (state->flags & ACTION_DEPTHFIRST) {
         if (!state->dirAction(state, fileName, &statbuf))
             goto done_nak_warn;
     }
     return status;
  done_nak_warn:
     if (!(state->flags & ACTION_QUIET))
         bb_simple_perror_msg(fileName);
     return FALSE;
 }
References ACTION_DANGLING_OK, ACTION_DEPTHFIRST, ACTION_FOLLOWLINKS, ACTION_FOLLOWLINKS_L0, ACTION_QUIET, ACTION_RECURSE, bb_error_msg(), bb_simple_perror_msg(), closedir(), concat_subpath_file(), dir, ENOENT, errno, FALSE, fileName, free, lstat, next, NULL, opendir(), readdir(), s, S_ISDIR, SKIP, stat::st_mode, stat(), state, status, and TRUE.
Referenced by recursive_action().
true_action()
static int FAST_FUNC true_action (struct recursive_state *state UNUSED_PARAM, const char *fileName UNUSED_PARAM, struct stat *statbuf UNUSED_PARAM) static
Definition at line 24 of file recursive_action.c.
 {
     return TRUE;
 }
References TRUE.
Referenced by recursive_action().