Fennix: Userspace/mlibc/tests/posix/sigsuspend.c File Reference
sigsuspend.c File Reference
#include <assert.h>
#include <unistd.h>
#include <pthread.h>
#include <signal.h>
#include <errno.h>
Functions
static void sig_handler (int sig, siginfo_t *info, void *ctx)
static void * worker (void *arg)
int main ()
Variables
_Atomic int handler_ready = 0
_Atomic int thread_signal_ran = 0
Function Documentation
main()
int main (void)
Definition at line 40 of file sigsuspend.c.
            {
     pthread_t thread;
     assert(!pthread_create(&thread, NULL, &worker, NULL));
     while (!handler_ready)
         ;
     sleep(1);
     assert(!pthread_kill(thread, SIGUSR1));
     assert(!pthread_join(thread, NULL));
     return 0;
 }
References assert, handler_ready, NULL, pthread_create(), pthread_join(), pthread_kill(), SIGUSR1, sleep(), and worker().
sig_handler()
static void sig_handler (int sig, siginfo_t * info, void * ctx) static
Definition at line 10 of file sigsuspend.c.
{
     (void)sig;
     (void)info;
     (void)ctx;
     thread_signal_ran = 1;
 }
References info, thread_signal_ran, and Driver::void().
Referenced by worker().
worker()
static void* worker (void * arg) static
Definition at line 18 of file sigsuspend.c.
{
     (void)arg;
     struct sigaction sa;
     sigemptyset(&sa.sa_mask);
     sa.sa_sigaction = sig_handler;
     sa.sa_flags = SA_SIGINFO;
     assert(!sigaction(SIGUSR1, &sa, NULL));
     handler_ready = 1;
     sigset_t set;
     sigfillset(&set);
     sigdelset(&set, SIGUSR1);
     assert(sigsuspend(&set));
     assert(thread_signal_ran);
     assert(errno == EINTR);
     return NULL;
 }
References mlibc::arg, assert, EINTR, errno, handler_ready, NULL, sigaction::sa_flags, sigaction::sa_mask, sigaction::sa_sigaction, SA_SIGINFO, sig_handler(), sigaction(), sigdelset(), sigemptyset(), sigfillset(), sigsuspend(), SIGUSR1, thread_signal_ran, and Driver::void().
Referenced by main().
Variable Documentation
handler_ready
_Atomic int handler_ready = 0
Definition at line 7 of file sigsuspend.c.
Referenced by main(), and worker().
thread_signal_ran
_Atomic int thread_signal_ran = 0
Definition at line 8 of file sigsuspend.c.
Referenced by sig_handler(), and worker().