Fennix Userspace: Userspace/musl/src/time/clock_gettime.c File Reference
clock_gettime.c File Reference
#include <time.h>
#include <errno.h>
#include <stdint.h>
#include "syscall.h"
#include "atomic.h"
Functions
int __clock_gettime (clockid_t clk, struct timespec *ts)
weak_alias (__clock_gettime, clock_gettime)
Function Documentation
__clock_gettime()
int __clock_gettime (clockid_t clk, struct timespec * ts)
Definition at line 59 of file clock_gettime.c.
 {
     int r;
 #ifdef VDSO_CGT_SYM
     int (*f)(clockid_t, struct timespec *) =
         (int (*)(clockid_t, struct timespec *))vdso_func;
     if (f) {
         r = f(clk, ts);
         if (!r) return r;
         if (r == -EINVAL) return __syscall_ret(r);
         /* Fall through on errors other than EINVAL. Some buggy
          * vdso implementations return ENOSYS for clocks they
          * can't handle, rather than making the syscall. This
          * also handles the case where cgt_init fails to find
          * a vdso function to use. */
     }
 #endif
 #ifdef SYS_clock_gettime64
     r = -ENOSYS;
     if (sizeof(time_t) > 4)
         r = __syscall(SYS_clock_gettime64, clk, ts);
     if (SYS_clock_gettime == SYS_clock_gettime64 || r!=-ENOSYS)
         return __syscall_ret(r);
     long ts32[2];
     r = __syscall(SYS_clock_gettime, clk, ts32);
 #ifdef SYS_gettimeofday
     if (r==-ENOSYS && clk==CLOCK_REALTIME) {
         r = __syscall(SYS_gettimeofday, ts32, 0);
         ts32[1] *= 1000;
     }
 #endif
     if (!r) {
         ts->tv_sec = ts32[0];
         ts->tv_nsec = ts32[1];
         return r;
     }
     return __syscall_ret(r);
 #else
     r = __syscall(SYS_clock_gettime, clk, ts);
 #ifdef SYS_gettimeofday
     if (r == -ENOSYS) {
         if (clk == CLOCK_REALTIME) {
             __syscall(SYS_gettimeofday, ts, 0);
             ts->tv_nsec = (int)ts->tv_nsec * 1000;
             return 0;
         }
         r = -EINVAL;
     }
 #endif
     return __syscall_ret(r);
 #endif
 }
References __syscall, __syscall_ret(), CLOCK_REALTIME, EINVAL, ENOSYS, f, int, r, SYS_clock_gettime, SYS_clock_gettime64, timespec::tv_nsec, and timespec::tv_sec.
Referenced by __randname(), __timedwait_cp(), clock(), time(), and timespec_get().
weak_alias()
weak_alias (__clock_gettime , clock_gettime)