Fennix: Time::TimeStampCounter Class Reference
Time::TimeStampCounter Class Reference
#include <time.hpp>
Public Member Functions
bool Sleep (uint64_t Duration, Units Unit)
uint64_t GetCounter ()
uint64_t CalculateTarget (uint64_t Target, Units Unit)
uint64_t GetNanosecondsSinceClassCreation ()
TimeStampCounter ()
~TimeStampCounter ()
Private Member Functions
uint64_t ConvertUnit (Units Unit)
Private Attributes
uint64_t clk = 0
uint64_t ClassCreationTime = 0
Detailed Description
Definition at line 112 of file time.hpp.
Constructor & Destructor Documentation
TimeStampCounter()
Time::TimeStampCounter::TimeStampCounter ()
Definition at line 65 of file TimeStampCounter.cpp.
     {
 #if defined(a86)
         fixme(""); // FIXME: This is not a good way to measure the clock speed
         uint64_t Start = CPU::Counter();
         TimeManager->Sleep(1, Units::Milliseconds);
         uint64_t End = CPU::Counter();
         this->clk = End - Start;
         this->ClassCreationTime = this->GetCounter();
 #endif
     }
References ClassCreationTime, clk, CPU::Counter(), fixme, GetCounter(), Time::Milliseconds, Time::time::Sleep(), and TimeManager.
~TimeStampCounter()
Time::TimeStampCounter::~TimeStampCounter ()
Definition at line 78 of file TimeStampCounter.cpp.
     {
     }
Member Function Documentation
CalculateTarget()
uint64_t Time::TimeStampCounter::CalculateTarget (uint64_t Target, Units Unit)
Definition at line 51 of file TimeStampCounter.cpp.
     {
 #if defined(a86)
         return this->GetCounter() + (Target * ConvertUnit(Unit)) / this->clk;
 #endif
     }
References clk, ConvertUnit(), and GetCounter().
Referenced by Time::time::CalculateTarget().
ConvertUnit()
uint64_t Time::TimeStampCounter::ConvertUnit (Units Unit) inline private
Definition at line 118 of file time.hpp.
         {
             switch (Unit)
             {
             case Femtoseconds:
                 return 1;
             case Picoseconds:
                 return 1000;
             case Nanoseconds:
                 return 1000000;
             case Microseconds:
                 return 1000000000;
             case Milliseconds:
                 return 1000000000000;
             case Seconds:
                 return 1000000000000000;
             case Minutes:
                 return 1000000000000000000;
             // case Hours:
             //     return 1000000000000000000000;
             // case Days:
             //     return 1000000000000000000000000;
             // case Months:
             //     return 1000000000000000000000000000;
             // case Years:
             //     return 1000000000000000000000000000000;
             default:
                 error("Invalid time unit %d", Unit);
                 return 1;
             }
         }
References error, Time::Femtoseconds, Time::Microseconds, Time::Milliseconds, Time::Minutes, Time::Nanoseconds, Time::Picoseconds, and Time::Seconds.
Referenced by CalculateTarget(), and Sleep().
GetCounter()
uint64_t Time::TimeStampCounter::GetCounter ()
Definition at line 44 of file TimeStampCounter.cpp.
     {
 #if defined(a86)
         return CPU::Counter();
 #endif
     }
References CPU::Counter().
Referenced by CalculateTarget(), Time::time::GetCounter(), GetNanosecondsSinceClassCreation(), Sleep(), and TimeStampCounter().
GetNanosecondsSinceClassCreation()
uint64_t Time::TimeStampCounter::GetNanosecondsSinceClassCreation ()
Definition at line 58 of file TimeStampCounter.cpp.
     {
 #if defined(a86)
         return (this->GetCounter() - this->ClassCreationTime) / this->clk;
 #endif
     }
References ClassCreationTime, clk, and GetCounter().
Referenced by Time::time::GetNanosecondsSinceClassCreation().
Sleep()
bool Time::TimeStampCounter::Sleep (uint64_t Duration, Units Unit)
Definition at line 34 of file TimeStampCounter.cpp.
     {
 #if defined(a86)
         uint64_t Target = this->GetCounter() + (Duration * ConvertUnit(Unit)) / this->clk;
         while (this->GetCounter() < Target)
             CPU::Pause();
         return true;
 #endif
     }
References clk, ConvertUnit(), GetCounter(), and CPU::Pause().
Referenced by Time::time::Sleep().
Field Documentation
ClassCreationTime
uint64_t Time::TimeStampCounter::ClassCreationTime = 0 private
Definition at line 116 of file time.hpp.
Referenced by GetNanosecondsSinceClassCreation(), and TimeStampCounter().
clk
uint64_t Time::TimeStampCounter::clk = 0 private
Definition at line 115 of file time.hpp.
Referenced by CalculateTarget(), GetNanosecondsSinceClassCreation(), Sleep(), and TimeStampCounter().
The documentation for this class was generated from the following files:
Kernel/include/time.hpp
Kernel/Core/Time/TimeStampCounter.cpp