Fennix: Userspace/musl/src/aio/lio_listio.c File Reference
lio_listio.c File Reference
#include <aio.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>
#include "pthread_impl.h"
Data Structures
struct lio_state
Functions
static int lio_wait (struct lio_state *st)
static void notify_signal (struct sigevent *sev)
static void * wait_thread (void *p)
int lio_listio (int mode, struct aiocb *restrict const *restrict cbs, int cnt, struct sigevent *restrict sev)
Data Structure Documentation
lio_state
struct lio_state
Definition at line 7 of file lio_listio.c.
Data Fields
struct aiocb * cbs[]
int cnt
struct sigevent * sev
Function Documentation
lio_listio()
int lio_listio (int mode, struct aiocb *restrict const *restrict cbs, int cnt, struct sigevent *restrict sev)
Definition at line 69 of file lio_listio.c.
 {
     int i, ret;
     struct lio_state *st=0;
     if (cnt < 0) {
         errno = EINVAL;
         return -1;
     }
     if (mode == LIO_WAIT || (sev && sev->sigev_notify != SIGEV_NONE)) {
         if (!(st = malloc(sizeof *st + cnt*sizeof *cbs))) {
             errno = EAGAIN;
             return -1;
         }
         st->cnt = cnt;
         st->sev = sev;
         memcpy(st->cbs, (void*) cbs, cnt*sizeof *cbs);
     }
     for (i=0; i<cnt; i++) {
         if (!cbs[i]) continue;
         switch (cbs[i]->aio_lio_opcode) {
         case LIO_READ:
             ret = aio_read(cbs[i]);
             break;
         case LIO_WRITE:
             ret = aio_write(cbs[i]);
             break;
         default:
             continue;
         }
         if (ret) {
             free(st);
             errno = EAGAIN;
             return -1;
         }
     }
     if (mode == LIO_WAIT) {
         ret = lio_wait(st);
         free(st);
         return ret;
     }
     if (st) {
         pthread_attr_t a;
         sigset_t set, set_old;
         pthread_t td;
         if (sev->sigev_notify == SIGEV_THREAD) {
             if (sev->sigev_notify_attributes)
                 a = *sev->sigev_notify_attributes;
             else
                 pthread_attr_init(&a);
         } else {
             pthread_attr_init(&a);
             pthread_attr_setstacksize(&a, PAGE_SIZE);
             pthread_attr_setguardsize(&a, 0);
         }
         pthread_attr_setdetachstate(&a, PTHREAD_CREATE_DETACHED);
         sigfillset(&set);
         pthread_sigmask(SIG_BLOCK, &set, &set_old);
         if (pthread_create(&td, &a, wait_thread, st)) {
             free(st);
             errno = EAGAIN;
             return -1;
         }
         pthread_sigmask(SIG_SETMASK, &set_old, 0);
     }
     return 0;
 }
References aio_read(), aio_write(), lio_state::cbs, cnt, EAGAIN, EINVAL, errno, free, i, LIO_READ, LIO_WAIT, lio_wait(), LIO_WRITE, malloc, memcpy, PAGE_SIZE, pthread_attr_init(), pthread_attr_setdetachstate(), pthread_attr_setguardsize(), pthread_attr_setstacksize(), pthread_create(), PTHREAD_CREATE_DETACHED, pthread_sigmask(), lio_state::sev, SIG_BLOCK, SIG_SETMASK, sigevent::sigev_notify, sigevent::sigev_notify_attributes, sigfillset(), td, and wait_thread().
lio_wait()
static int lio_wait (struct lio_state * st) static
Definition at line 13 of file lio_listio.c.
 {
     int i, err, got_err = 0;
     int cnt = st->cnt;
     struct aiocb **cbs = st->cbs;
     for (;;) {
         for (i=0; i<cnt; i++) {
             if (!cbs[i]) continue;
             err = aio_error(cbs[i]);
             if (err==EINPROGRESS)
                 break;
             if (err) got_err=1;
             cbs[i] = 0;
         }
         if (i==cnt) {
             if (got_err) {
                 errno = EIO;
                 return -1;
             }
             return 0;
         }
         if (aio_suspend((void *)cbs, cnt, 0))
             return -1;
     }
 }
References aio_error(), aio_suspend(), cnt, EINPROGRESS, EIO, err(), errno, and i.
Referenced by lio_listio(), and wait_thread().
notify_signal()
static void notify_signal (struct sigevent * sev) static
Definition at line 40 of file lio_listio.c.
 {
     siginfo_t si = {
         .si_signo = sev->sigev_signo,
         .si_value = sev->sigev_value,
         .si_code = SI_ASYNCIO,
         .si_pid = getpid(),
         .si_uid = getuid()
     };
     __syscall(SYS_rt_sigqueueinfo, si.si_pid, si.si_signo, &si);
 }
References __syscall, getpid(), getuid, sigevent::sigev_signo, and sigevent::sigev_value.
Referenced by wait_thread().
wait_thread()
static void* wait_thread (void * p) static
Definition at line 52 of file lio_listio.c.
 {
     struct lio_state *st = p;
     struct sigevent *sev = st->sev;
     lio_wait(st);
     free(st);
     switch (sev->sigev_notify) {
     case SIGEV_SIGNAL:
         notify_signal(sev);
         break;
     case SIGEV_THREAD:
         sev->sigev_notify_function(sev->sigev_value);
         break;
     }
     return 0;
 }
References free, lio_wait(), notify_signal(), p, sigevent::sigev_notify, sigevent::sigev_notify_function, and sigevent::sigev_value.
Referenced by lio_listio().