Fennix Userspace: Userspace/apps/base/busybox/archival/bzip2.c File Reference
bzip2.c File Reference
#include "libbb.h"
#include "bb_archive.h"
#include "libarchive/bz/bzlib.h"
#include "libarchive/bz/bzlib_private.h"
#include "libarchive/bz/blocksort.c"
#include "libarchive/bz/bzlib.c"
#include "libarchive/bz/compress.c"
#include "libarchive/bz/huffman.c"
Macros
#define BZIP2_SPEED 5
#define BZ_DEBUG 0
#define BZ_LIGHT_DEBUG 0
#define strm (&bzs)
#define rbuf iobuf
#define wbuf (iobuf + IOBUF_SIZE)
Enumerations
enum { IOBUF_SIZE = 8 * 1024 }
Functions
static IF_DESKTOP (long long)
int bzip2_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BZ_DEBUG
#define BZ_DEBUG 0
Definition at line 93 of file bzip2.c.
BZ_LIGHT_DEBUG
#define BZ_LIGHT_DEBUG 0
Definition at line 95 of file bzip2.c.
BZIP2_SPEED
#define BZIP2_SPEED 5
Definition at line 73 of file bzip2.c.
rbuf
#define rbuf iobuf
strm
#define strm (&bzs)
wbuf
#define wbuf (iobuf + IOBUF_SIZE)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IOBUF_SIZE
Definition at line 112 of file bzip2.c.
      {
     IOBUF_SIZE = 8 * 1024
 };
Function Documentation
bzip2_main()
int bzip2_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 212 of file bzip2.c.
 {
     unsigned opt;
     /* standard bzip2 flags
      * -d --decompress force decompression
      * -z --compress force compression
      * -k --keep     keep (don't delete) input files
      * -f --force    overwrite existing output files
      * -t --test     test compressed file integrity
      * -c --stdout   output to standard out
      * -q --quiet    suppress noncritical error messages
      * -v --verbose  be verbose (a 2nd -v gives more)
      * -s --small    use less memory (at most 2500k)
      * -1 .. -9      set block size to 100k .. 900k
      * --fast        alias for -1
      * --best        alias for -9
      */
     opt = getopt32(argv, "^"
         /* Must match BBUNPK_foo constants! */
         BBUNPK_OPTSTR IF_FEATURE_BZIP2_DECOMPRESS("dt") "zs123456789"
         "\0" "s2" /* -s means -2 (compatibility) */
     );
 #if ENABLE_FEATURE_BZIP2_DECOMPRESS /* bunzip2_main may not be visible... */
     if (opt & (BBUNPK_OPT_DECOMPRESS|BBUNPK_OPT_TEST)) /* -d and/or -t */
         return bunzip2_main(argc, argv);
 #else
     /* clear "decompress" and "test" bits (or bbunpack() can get confused) */
     /* in !BZIP2_DECOMPRESS config, these bits are -zs and are unused */
     option_mask32 = opt & ~(BBUNPK_OPT_DECOMPRESS|BBUNPK_OPT_TEST);
 #endif
     argv += optind;
     return bbunpack(argv, compressStream, append_ext, "bz2");
 }
References append_ext(), argc, argv, bbunpack(), BBUNPK_OPT_DECOMPRESS, BBUNPK_OPT_TEST, BBUNPK_OPTSTR, bunzip2_main(), getopt32(), opt, optind, and option_mask32.
IF_DESKTOP()
static IF_DESKTOP (long long) static
Definition at line 126 of file bzip2.c.
 {
     int n, n2, ret;
     strm->avail_in = rlen;
     strm->next_in = rbuf;
     while (1) {
         strm->avail_out = IOBUF_SIZE;
         strm->next_out = wbuf;
         ret = BZ2_bzCompress(strm, rlen ? BZ_RUN : BZ_FINISH);
         if (ret != BZ_RUN_OK /* BZ_RUNning */
          && ret != BZ_FINISH_OK /* BZ_FINISHing, but not done yet */
          && ret != BZ_STREAM_END /* BZ_FINISHed */
         ) {
             bb_error_msg_and_die("internal error %d", ret);
         }
         n = IOBUF_SIZE - strm->avail_out;
         if (n) {
             n2 = full_write(STDOUT_FILENO, wbuf, n);
             if (n2 != n) {
                 if (n2 >= 0)
                     errno = 0; /* prevent bogus error message */
                 bb_simple_perror_msg(n2 >= 0 ? "short write" : bb_msg_write_error);
                 return -1;
             }
         }
         if (ret == BZ_STREAM_END)
             break;
         if (rlen && strm->avail_in == 0)
             break;
     }
     return 0 IF_DESKTOP( + strm->total_out );
 }
References bb_error_msg_and_die(), bb_msg_write_error, bb_simple_perror_msg(), BZ2_bzCompress(), BZ_FINISH, BZ_FINISH_OK, BZ_RUN, BZ_RUN_OK, BZ_STREAM_END, errno, full_write(), IOBUF_SIZE, n, rbuf, STDOUT_FILENO, strm, and wbuf.
Referenced by bbunpack(), cmp_main(), fork_transformer(), mount_main(), parse_mount_options(), parse_params(), tar_main(), unzip_main(), and wget_main().