Fennix Userspace: Userspace/musl/src/thread/pthread_cancel.c File Reference
pthread_cancel.c File Reference
#include <string.h>
#include "pthread_impl.h"
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
hidden long __cancel ()
hidden long __syscall_cp_asm ()
hidden long __syscall_cp_c ()
long __syscall_cp_asm (volatile void *, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t)
long __syscall_cp_c (syscall_arg_t nr, syscall_arg_t u, syscall_arg_t v, syscall_arg_t w, syscall_arg_t x, syscall_arg_t y, syscall_arg_t z)
static void _sigaddset (sigset_t *set, int sig)
static void cancel_handler (int sig, siginfo_t *si, void *ctx)
void __testcancel ()
static void init_cancellation ()
int pthread_cancel (pthread_t t)
Variables
hidden const char __cp_begin [1]
hidden const char __cp_end [1]
hidden const char __cp_cancel [1]
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file pthread_cancel.c.
Function Documentation
__cancel()
long __cancel ()
Definition at line 8 of file pthread_cancel.c.
 {
     pthread_t self = __pthread_self();
     if (self->canceldisable == PTHREAD_CANCEL_ENABLE || self->cancelasync)
         pthread_exit(PTHREAD_CANCELED);
     self->canceldisable = PTHREAD_CANCEL_DISABLE;
     return -ECANCELED;
 }
References __pthread_self, ECANCELED, PTHREAD_CANCEL_DISABLE, PTHREAD_CANCEL_ENABLE, PTHREAD_CANCELED, and pthread_exit().
Referenced by __syscall_cp_c(), __testcancel(), and cancel_handler().
__syscall_cp_asm() [1/2]
hidden long __syscall_cp_asm ()
Referenced by __syscall_cp_c().
__syscall_cp_asm() [2/2]
long __syscall_cp_asm (volatile void * , syscall_arg_t , syscall_arg_t , syscall_arg_t , syscall_arg_t , syscall_arg_t , syscall_arg_t , syscall_arg_t)
__syscall_cp_c() [1/2]
hidden long __syscall_cp_c ()
__syscall_cp_c() [2/2]
long __syscall_cp_c (syscall_arg_t nr, syscall_arg_t u, syscall_arg_t v, syscall_arg_t w, syscall_arg_t x, syscall_arg_t y, syscall_arg_t z)
Definition at line 21 of file pthread_cancel.c.
 {
     pthread_t self;
     long r;
     int st;
     if ((st=(self=__pthread_self())->canceldisable)
         && (st==PTHREAD_CANCEL_DISABLE || nr==SYS_close))
         return __syscall(nr, u, v, w, x, y, z);
     r = __syscall_cp_asm(&self->cancel, nr, u, v, w, x, y, z);
     if (r==-EINTR && nr!=SYS_close && self->cancel &&
         self->canceldisable != PTHREAD_CANCEL_DISABLE)
         r = __cancel();
     return r;
 }
References __cancel(), __pthread_self, __syscall, __syscall_cp_asm(), EINTR, PTHREAD_CANCEL_DISABLE, r, x, and y.
__testcancel()
void __testcancel ()
Definition at line 75 of file pthread_cancel.c.
 {
     pthread_t self = __pthread_self();
     if (self->cancel && !self->canceldisable)
         __cancel();
 }
References __cancel(), and __pthread_self.
Referenced by __pthread_testcancel().
_sigaddset()
static void _sigaddset (sigset_t * set, int sig) static
Definition at line 40 of file pthread_cancel.c.
 {
     unsigned s = sig-1;
     set->__bits[s/8/sizeof *set->__bits] |= 1UL<<(s&8*sizeof *set->__bits-1);
 }
Referenced by cancel_handler().
cancel_handler()
static void cancel_handler (int sig, siginfo_t * si, void * ctx) static
Definition at line 48 of file pthread_cancel.c.
 {
     pthread_t self = __pthread_self();
     ucontext_t *uc = ctx;
     uintptr_t pc = uc->uc_mcontext.MC_PC;
     a_barrier();
     if (!self->cancel || self->canceldisable == PTHREAD_CANCEL_DISABLE) return;
     _sigaddset(&uc->uc_sigmask, SIGCANCEL);
     if (self->cancelasync) {
         pthread_sigmask(SIG_SETMASK, &uc->uc_sigmask, 0);
         __cancel();
     }
     if (pc >= (uintptr_t)__cp_begin && pc < (uintptr_t)__cp_end) {
         uc->uc_mcontext.MC_PC = (uintptr_t)__cp_cancel;
 #ifdef CANCEL_GOT
         uc->uc_mcontext.MC_GOT = CANCEL_GOT;
 #endif
         return;
     }
     __syscall(SYS_tkill, self->tid, SIGCANCEL);
 }
References __cancel(), __cp_begin, __cp_cancel, __cp_end, __pthread_self, __syscall, _sigaddset(), a_barrier, ctx, PTHREAD_CANCEL_DISABLE, pthread_sigmask(), SIG_SETMASK, and SIGCANCEL.
Referenced by init_cancellation().
init_cancellation()
static void init_cancellation () static
Definition at line 82 of file pthread_cancel.c.
 {
     struct sigaction sa = {
         .sa_flags = SA_SIGINFO | SA_RESTART | SA_ONSTACK,
         .sa_sigaction = cancel_handler
     };
     memset(&sa.sa_mask, -1, _NSIG/8);
     __libc_sigaction(SIGCANCEL, &sa, 0);
 }
References __libc_sigaction(), _NSIG, cancel_handler(), memset(), sigaction::sa_flags, sigaction::sa_mask, SA_ONSTACK, SA_RESTART, SA_SIGINFO, and SIGCANCEL.
Referenced by pthread_cancel().
pthread_cancel()
int pthread_cancel (pthread_t t)
Definition at line 92 of file pthread_cancel.c.
 {
     static int init;
     if (!init) {
         init_cancellation();
         init = 1;
     }
     a_store(&t->cancel, 1);
     if (t == pthread_self()) {
         if (t->canceldisable == PTHREAD_CANCEL_ENABLE && t->cancelasync)
             pthread_exit(PTHREAD_CANCELED);
         return 0;
     }
     return pthread_kill(t, SIGCANCEL);
 }
References a_store, init, init_cancellation(), PTHREAD_CANCEL_ENABLE, PTHREAD_CANCELED, pthread_exit(), pthread_kill(), pthread_self(), SIGCANCEL, and t.
Referenced by main().
Variable Documentation
__cp_begin
hidden const char __cp_begin[1] extern
Referenced by cancel_handler().
__cp_cancel
hidden const char __cp_cancel[1]
Definition at line 46 of file pthread_cancel.c.
Referenced by cancel_handler().
__cp_end
hidden const char __cp_end[1]
Definition at line 46 of file pthread_cancel.c.
Referenced by cancel_handler().