Fennix Userspace: Userspace/apps/base/busybox/libbb/verror_msg.c File Reference
verror_msg.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC bb_verror_msg (const char *s, va_list p, const char *strerr)
void FAST_FUNC bb_error_msg_and_die (const char *s,...)
void FAST_FUNC bb_error_msg (const char *s,...)
void FAST_FUNC bb_simple_error_msg (const char *s)
void FAST_FUNC bb_simple_error_msg_and_die (const char *s)
Variables
smallint logmode = LOGMODE_STDIO
const char * msg_eol = "\n"
Function Documentation
bb_error_msg()
void FAST_FUNC bb_error_msg (const char * s, ...)
Definition at line 175 of file verror_msg.c.
 {
     va_list p;
     va_start(p, s);
     bb_verror_msg(s, p, NULL);
     va_end(p);
 }
References bb_verror_msg(), NULL, p, s, va_end, and va_start.
Referenced by bb_simple_error_msg().
bb_error_msg_and_die()
void FAST_FUNC bb_error_msg_and_die (const char * s, ...)
Definition at line 165 of file verror_msg.c.
 {
     va_list p;
     va_start(p, s);
     bb_verror_msg(s, p, NULL);
     va_end(p);
     xfunc_die();
 }
References bb_verror_msg(), NULL, p, s, va_end, va_start, and xfunc_die().
Referenced by bb_simple_error_msg_and_die().
bb_simple_error_msg()
void FAST_FUNC bb_simple_error_msg (const char * s)
Definition at line 207 of file verror_msg.c.
 {
     bb_error_msg("%s", s);
 }
References bb_error_msg(), and s.
Referenced by arp_del(), arp_set(), awk_main(), bb_BLKGETSIZE_sectors(), change_filedir_context(), chat_main(), check_existence_through_netlink(), check_signature16(), confirm_action(), detect_link(), do_tunnels_list(), doCommands(), get_header_tar(), get_wol_pw(), getNum(), handle_incoming_and_exit(), IF_DESKTOP(), inetd_main(), insertLine(), kill_main(), log_and_exit(), lpqr_main(), malloc_or_warn(), md5_sha1_sum_main(), mod(), ntpd_main(), parse_one_line(), parse_redir_right_fd(), pause_nomem(), powertop_main(), print_linkinfo(), printf_main(), process_event(), process_packet(), process_pax_hdr(), rdate_main(), readcmd(), readLines(), readprofile_main(), receive(), reset_beg_range_to_zero(), rm_main(), rtnl_dump_filter(), rtnl_send_check(), rtnl_talk(), searchLines(), select_and_cluster(), send_offer(), setsockopt_bindtodevice(), show_timerstats(), singlemount(), sleep_main(), string_option_to_env(), su_main(), subCommand(), syntax_error(), test_main(), top_main(), top_up(), udhcp_scan_options(), uevent_main(), unit_main(), unzip_extract(), wait_one(), and write_status_file().
bb_simple_error_msg_and_die()
void FAST_FUNC bb_simple_error_msg_and_die (const char * s)
Definition at line 212 of file verror_msg.c.
 {
     bb_error_msg_and_die("%s", s);
 }
References bb_error_msg_and_die(), and s.
Referenced by add_cmd(), add_split_dependencies(), addgroup_main(), adduser_main(), arithmetic_common(), arp_getdevhw(), arp_main(), arp_set(), bb_copyfd_exact_size(), bb_die_memory_exhausted(), bb_init_module_24(), bbunpack(), chattr_main(), chcon_main(), check_and_close(), check_blocks(), check_magic(), check_under(), chpasswd_main(), compare_keys(), compile_fs_type(), confirm_action(), confirm_or_abort(), cp_main(), create_icmp_socket(), crontab_main(), cut_main(), data_extract_all(), deluser_main(), devmem_main(), die(), die_if_bad_fnamesize(), die_if_bad_username(), diff_main(), do_add(), do_load(), do_loadtable(), do_procinit(), do_stop(), do_subst_command(), dolisten(), download_one_url(), dpkg_main(), eval6(), eval7(), expand_string_to_string(), expr_main(), find_key_in_der_cert(), flash_eraseall_main(), flock_main(), get_address(), get_console_fd_or_die(), get_cred_or_die(), get_free_block(), get_header_ar(), get_header_cpio(), get_header_tar(), get_volume_size_in_bytes(), get_vt_fd(), getcaps(), getenforce_main(), getOctal(), getopt_main(), hmac_begin(), id_main(), IF_DESKTOP(), ifconfig_main(), ifplugd_main(), inc_err(), INET_setroute(), inetd_main(), init_main(), ipaddr_list_or_flush(), ipaddr_modify(), ipcalc_main(), ipneigh_list_or_flush(), iproute_get(), leave_var_nest_level(), ln_main(), loadkmap_main(), login_main(), losetup_main(), lpqr_main(), lzo_check(), lzo_decompress(), lzo_set_method(), make_bad_inode(), mesg_main(), mkfs_ext2_main(), mkfs_minix_main(), mkfs_reiser_main(), mkfs_vfat_main(), mount_it_now(), mount_main(), mpstat_main(), nandwrite_main(), nbdclient_main(), nc_main(), next_arg(), next_good_eraseblock(), ntp_init(), obj_load(), open_tty(), parse_args(), parse_file_cmd(), parse_params(), parse_regex_delim(), parse_speeds(), parse_subst_cmd(), passwd_wrapper(), paste_main(), patch_main(), process_files(), process_server_key(), pstree_main(), push(), puts_maybe_newline(), pw_encrypt(), rc_read(), re_execute_shell(), read_base64(), read_num(), readit(), readprofile_main(), retrieve_file_data(), rewrite(), runcon_compute_new_context(), runcon_main(), seedrng_main(), send_client_key_exchange(), sendmail_main(), set_local_var(), set_status(), set_vars_and_save_old(), setsebool_main(), setup_tables(), signal_handler(), skip(), socket_timeout(), sort_main(), split_main(), stty_main(), su_main(), sulogin_main(), switch_root_main(), tail_main(), tar_main(), tcpudpsvd_main(), timeout(), tls_xread_record(), tr_main(), traceroute_init(), tsort_main(), ubi_tools_main(), ubirename_main(), unpack_ar_archive(), unshare_main(), unzip_extract(), write_status_file(), xargs_main(), xgetpty(), xread(), and xrtnl_dump_filter().
bb_verror_msg()
void FAST_FUNC bb_verror_msg (const char * s, va_list p, const char * strerr)
Definition at line 20 of file verror_msg.c.
 {
     char *msg, *msg1;
     char stack_msg[80];
     int applet_len, strerr_len, msgeol_len, used;
     if (!logmode)
         return;
     if (!s) /* nomsg[_and_die] uses NULL fmt */
         s = ""; /* some libc don't like printf(NULL) */
     applet_len = strlen(applet_name) + 2; /* "applet: " */
     strerr_len = strerr ? strlen(strerr) : 0;
     msgeol_len = strlen(msg_eol);
     /* This costs ~90 bytes of code, but avoids costly
      * malloc()[in vasprintf]+realloc()+memmove()+free() in 99% of cases.
      * ~40% speedup.
      */
     if ((int)sizeof(stack_msg) - applet_len > 0) {
         va_list p2;
         /* It is not portable to use va_list twice, need to va_copy it */
         va_copy(p2, p);
         used = vsnprintf(stack_msg + applet_len, (int)sizeof(stack_msg) - applet_len, s, p2);
         va_end(p2);
         msg = stack_msg;
         used += applet_len;
         if (used < (int)sizeof(stack_msg) - 3 - msgeol_len - strerr_len)
             goto add_pfx_and_sfx;
     }
     used = vasprintf(&msg, s, p);
     if (used < 0)
         return;
     /* This is ugly and costs +60 bytes compared to multiple
      * fprintf's, but is guaranteed to do a single write.
      * This is needed for e.g. httpd logging, when multiple
      * children can produce log messages simultaneously. */
     /* can't use xrealloc: it calls error_msg on failure,
      * that may result in a recursion */
     /* +3 is for ": " before strerr and for terminating NUL */
     msg1 = realloc(msg, applet_len + used + strerr_len + msgeol_len + 3);
     if (!msg1) {
         msg[used++] = '\n'; /* overwrites NUL */
         applet_len = 0;
     } else {
         msg = msg1;
         /* TODO: maybe use writev instead of memmoving? Need full_writev? */
         memmove(msg + applet_len, msg, used);
         used += applet_len;
  add_pfx_and_sfx:
         strcpy(msg, applet_name);
         msg[applet_len - 2] = ':';
         msg[applet_len - 1] = ' ';
         if (strerr) {
             if (s[0]) { /* not perror_nomsg? */
                 msg[used++] = ':';
                 msg[used++] = ' ';
             }
             strcpy(&msg[used], strerr);
             used += strerr_len;
         }
         strcpy(&msg[used], msg_eol);
         used += msgeol_len;
     }
     if (logmode & LOGMODE_STDIO) {
         fflush_all();
         full_write(STDERR_FILENO, msg, used);
     }
 #if ENABLE_FEATURE_SYSLOG
     if (logmode & LOGMODE_SYSLOG) {
         syslog(syslog_level, "%s", msg + applet_len);
     }
 #endif
     if (msg != stack_msg)
         free(msg);
 }
References applet_name, fflush_all(), free, full_write(), logmode, LOGMODE_STDIO, LOGMODE_SYSLOG, memmove(), msg_eol, p, realloc, s, STDERR_FILENO, strcpy(), strlen(), syslog(), va_copy, va_end, vasprintf(), and vsnprintf().
Referenced by bb_error_msg(), bb_error_msg_and_die(), bb_herror_msg(), bb_herror_msg_and_die(), bb_perror_msg(), bb_perror_msg_and_die(), ioctl_or_perror(), ioctl_or_perror_and_die(), and msg_and_die_if_script().
Variable Documentation
logmode
smallint logmode = LOGMODE_STDIO
Definition at line 17 of file verror_msg.c.
Referenced by acpid_main(), adduser_main(), bb_logenv_override(), bb_verror_msg(), chpasswd_main(), cmp_main(), crond_main(), detect_link(), devfsd_main(), dnsd_main(), fakeidentd_main(), ftpd_main(), getty_main(), ifplugd_main(), inetd_main(), ipcalc_main(), klogd_main(), mdev_main(), modprobe_main(), nameif_main(), ntp_init(), ParseField(), passwd_main(), readlink_main(), sulogin_main(), telnetd_main(), udhcpc6_main(), udhcpc_main(), and udhcpd_main().
msg_eol
const char* msg_eol = "\n"
Definition at line 18 of file verror_msg.c.
Referenced by bb_verror_msg(), check_blocks(), do_check(), getty_main(), and write_tables().