Fennix: Userspace/mlibc/options/linux/include/sys/xattr.h File Reference
xattr.h File Reference
#include <sys/types.h>
#include <abi-bits/xattr.h>
Functions
int setxattr (const char *path, const char *name, const void *val, size_t size, int flags)
int lsetxattr (const char *path, const char *name, const void *val, size_t size, int flags)
int fsetxattr (int fd, const char *name, const void *val, size_t size, int flags)
ssize_t getxattr (const char *path, const char *name, void *val, size_t size)
ssize_t lgetxattr (const char *path, const char *name, void *val, size_t size)
ssize_t fgetxattr (int fd, const char *name, void *val, size_t size)
ssize_t listxattr (const char *path, char *list, size_t size)
ssize_t llistxattr (const char *path, char *list, size_t size)
ssize_t flistxattr (int fd, char *list, size_t size)
int removexattr (const char *path, const char *name)
int lremovexattr (const char *path, const char *name)
int fremovexattr (int fd, const char *name)
Function Documentation
fgetxattr()
ssize_t fgetxattr (int fd, const char * name, void * val, size_t size)
Definition at line 64 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fgetxattr, -1);
     ssize_t nread;
     if (int e = sysdep(fd, name, val, size, &nread); e) {
         errno = e;
         return -1;
     }
     return nread;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, name, size, and mlibc::sys_fgetxattr().
Referenced by main().
flistxattr()
ssize_t flistxattr (int fd, char * list, size_t size)
Definition at line 113 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_flistxattr, -1);
     ssize_t nread;
     if (int e = sysdep(fd, list, size, &nread); e) {
         errno = e;
         return -1;
     }
     return nread;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_flistxattr().
Referenced by main().
fremovexattr()
int fremovexattr (int fd, const char * name)
Definition at line 86 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fremovexattr, -1);
     return sysdep(fd, name);
 }
References fd, MLIBC_CHECK_OR_ENOSYS, name, and mlibc::sys_fremovexattr().
Referenced by main().
fsetxattr()
int fsetxattr (int fd, const char * name, const void * val, size_t size, int flags)
Definition at line 29 of file sys-xattr.cpp.
                    {
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fsetxattr, -1);
     if (int e = sysdep(fd, name, val, size, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, flags, MLIBC_CHECK_OR_ENOSYS, name, size, and mlibc::sys_fsetxattr().
Referenced by main().
getxattr()
ssize_t getxattr (const char * path, const char * name, void * val, size_t size)
Definition at line 40 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getxattr, -1);
     ssize_t nread;
     if (int e = sysdep(path, name, val, size, &nread); e) {
         errno = e;
         return -1;
     }
     return nread;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, name, size, and mlibc::sys_getxattr().
Referenced by main().
lgetxattr()
ssize_t lgetxattr (const char * path, const char * name, void * val, size_t size)
Definition at line 52 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_lgetxattr, -1);
     ssize_t nread;
     if (int e = sysdep(path, name, val, size, &nread); e) {
         errno = e;
         return -1;
     }
     return nread;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, name, size, and mlibc::sys_lgetxattr().
Referenced by main().
listxattr()
ssize_t listxattr (const char * path, char * list, size_t size)
Definition at line 91 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_listxattr, -1);
     ssize_t nread;
     if (int e = sysdep(path, list, size, &nread); e) {
         errno = e;
         return -1;
     }
     return nread;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_listxattr().
Referenced by main().
llistxattr()
ssize_t llistxattr (const char * path, char * list, size_t size)
Definition at line 102 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_llistxattr, -1);
     ssize_t nread;
     if (int e = sysdep(path, list, size, &nread); e) {
         errno = e;
         return -1;
     }
     return nread;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_llistxattr().
lremovexattr()
int lremovexattr (const char * path, const char * name)
Definition at line 81 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_lremovexattr, -1);
     return sysdep(path, name);
 }
References MLIBC_CHECK_OR_ENOSYS, name, and mlibc::sys_lremovexattr().
lsetxattr()
int lsetxattr (const char * path, const char * name, const void * val, size_t size, int flags)
Definition at line 18 of file sys-xattr.cpp.
                    {
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_lsetxattr, -1);
     if (int e = sysdep(path, name, val, size, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, name, size, and mlibc::sys_lsetxattr().
removexattr()
int removexattr (const char * path, const char * name)
Definition at line 76 of file sys-xattr.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_removexattr, -1);
     return sysdep(path, name);
 }
References MLIBC_CHECK_OR_ENOSYS, name, and mlibc::sys_removexattr().
Referenced by main().
setxattr()
int setxattr (const char * path, const char * name, const void * val, size_t size, int flags)
Definition at line 7 of file sys-xattr.cpp.
                    {
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setxattr, -1);
     if (int e = sysdep(path, name, val, size, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, name, size, and mlibc::sys_setxattr().
Referenced by main().