Fennix: Kernel/include/cpu.hpp File Reference
cpu.hpp File Reference
#include <types.h>
#include <cpu/x86/cpuid_intel.hpp>
#include <cpu/x86/cpuid_amd.hpp>
#include <cpu/x86/x32/cr.hpp>
#include <cpu/x86/x32/msr.hpp>
#include <cpu/x86/x64/cr.hpp>
#include <cpu/x86/x64/msr.hpp>
#include <cpu/x86/exceptions.hpp>
#include <cpu/x86/interrupts.hpp>
#include <cpu/signatures.hpp>
#include <cpu/membar.hpp>
#include <cstring>
Data Structures
union x32::__packed
MSR_APIC_BASE structure.
union x32::EFLAGS
struct x32::TrapFrame
union x32::DR6
union x32::DR7
struct x32::FXState
union x64::__packed
MSR_APIC_BASE structure.
union x64::RFLAGS
struct x64::TrapFrame
union x64::EFER
union x64::DR6
union x64::DR7
union x64::PageFaultErrorCode
union x64::SelectorErrorCode
struct x64::FXState
struct aarch64::TrapFrame
struct x32::__packed.__unnamed544__
struct x32::EFLAGS.__unnamed546__
struct x32::DR6.__unnamed548__
struct x32::DR7.__unnamed550__
struct x64::__packed.__aligned
struct x64::__packed.__unnamed554__
struct x64::RFLAGS.__unnamed558__
struct x64::EFER.__unnamed580__
struct x64::DR6.__unnamed589__
struct x64::DR7.__unnamed598__
struct x64::PageFaultErrorCode.__unnamed609__
struct x64::SelectorErrorCode.__unnamed623__
Namespaces
CPU
CPU related functions.
x32
x64
aarch64
Macros
#define thisPageTable (Memory::PageTable *)CPU::PageTable()
Typedefs
typedef struct x32::TrapFrame x32::TrapFrame
typedef union x32::DR6 x32::DR6
typedef union x32::DR7 x32::DR7
typedef struct x64::TrapFrame x64::TrapFrame
typedef union x64::EFER x64::EFER
typedef union x64::DR6 x64::DR6
typedef union x64::DR7 x64::DR7
typedef union x64::PageFaultErrorCode x64::PageFaultErrorCode
typedef union x64::SelectorErrorCode x64::SelectorErrorCode
typedef struct aarch64::TrapFrame aarch64::TrapFrame
Enumerations
enum CPU::InterruptsType { CPU::Check , CPU::Enable , CPU::Disable }
Enum for CPU::Interrupts() function.
enum CPU::x86SIMDType {
CPU::SIMD_NONE = (1 << 0) , CPU::SIMD_SSE = (1 << 1) , CPU::SIMD_SSE2 = (1 << 2) , CPU::SIMD_SSE3 = (1 << 3) ,
CPU::SIMD_SSSE3 = (1 << 4) , CPU::SIMD_SSE41 = (1 << 5) , CPU::SIMD_SSE42 = (1 << 6) , CPU::SIMD_AVX = (1 << 7) ,
CPU::SIMD_AVX2 = (1 << 8) , CPU::SIMD_AVX512 = (1 << 9) , CPU::SIMD_AVX512F = (1 << 10) , CPU::SIMD_AVX512CD = (1 << 11) ,
CPU::SIMD_AVX512ER = (1 << 12) , CPU::SIMD_AVX512PF = (1 << 13) , CPU::SIMD_AVX512VL = (1 << 14) , CPU::SIMD_AVX512DQ = (1 << 16) ,
CPU::SIMD_AVX512BW = (1 << 15) , CPU::SIMD_AVX512IFMA = (1 << 17) , CPU::SIMD_AVX512VBMI = (1 << 18) , CPU::SIMD_AVX5124VNNIW = (1 << 19) ,
CPU::SIMD_AVX5124FMAPS = (1 << 20) , CPU::SIMD_AVX512VPOPCNTDQ = (1 << 21) , CPU::SIMD_AVX512VNNI = (1 << 22) , CPU::SIMD_AVX512VBMI2 = (1 << 23) ,
CPU::SIMD_AVX512BITALG = (1 << 24) , CPU::SIMD_AVX512VP2INTERSECT = (1 << 25) , CPU::SIMD_AVX512GFNI = (1 << 26) , CPU::SIMD_AVX512VPCLMULQDQ = (1 << 27) ,
CPU::SIMD_AVX512VAES = (1 << 28)
}
Functions
const char * CPU::Vendor ()
Get CPU vendor identifier.
const char * CPU::Name ()
Get CPU name.
const char * CPU::Hypervisor ()
Get CPU hypervisor vendor.
uint64_t CPU::CheckSIMD ()
Check SIMD support. It will return the highest supported SIMD type.
bool CPU::CheckSIMD (x86SIMDType Type)
Check SIMD support.
static SafeFunction __always_inline void CPU::Pause (bool Loop=false)
Pause the CPU.
static SafeFunction __always_inline void Halt (bool Loop=false)
Halt the CPU.
bool Interrupts (InterruptsType Type=Check)
Check if interrupts are enabled.
void * PageTable (void *PT=nullptr)
Get/Set the CPU's page table.
void InitializeFeatures (int Core)
To be used only once.
uint64_t Counter ()
Get CPU counter value.
static void x32::cpuid (uint32_t Function, uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
CPUID.
static SafeFunction void x32::lgdt (void *gdt)
static SafeFunction void x32::lidt (void *idt)
static SafeFunction void x32::ltr (uint16_t Segment)
static SafeFunction void x32::invlpg (void *Address)
static SafeFunction void x32::fxsave (void *FXSaveArea)
static SafeFunction void x32::fxrstor (void *FXRstorArea)
struct x64::FXState x64::__aligned (16)
static SafeFunction void x64::lgdt (void *gdt)
static SafeFunction void x64::lidt (void *idt)
static SafeFunction void x64::ltr (uint16_t Segment)
static SafeFunction void x64::invlpg (void *Address)
static SafeFunction void x64::cpuid (uint32_t Function, uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
CPUID.
static SafeFunction uint32_t x64::GetHighestLeaf ()
static SafeFunction void x64::fxsave (void *FXSaveArea)
static SafeFunction void x64::fxrstor (void *FXRstorArea)
Variables
struct x32::FXState x32::__packed
uint16_t fcw
FPU control word.
uint16_t fsw
FPU status word.
uint8_t ftw
FPU tag words.
uint8_t Reserved
Reserved (zero)
uint16_t fop
FPU opcode.
uint64_t rip
PFU instruction pointer.
uint64_t rdp
FPU data pointer.
uint32_t mxcsr
SSE control register.
uint32_t mxcsrmask
SSE control register mask.
uint8_t st [8][16]
FPU registers (last 6 bytes reserved)
uint8_t xmm [16][16]
XMM registers.
Data Structure Documentation
x32::__packed
union x32::__packed
MSR_APIC_BASE structure.
See also
MSR_APIC_BASE
Definition at line 220 of file cpu.hpp.
Data Fields
struct __packed __unnamed__
uint64_t raw
x32::EFLAGS
union x32::EFLAGS
Definition at line 245 of file cpu.hpp.
Data Fields
struct EFLAGS __unnamed__
uint32_t raw
x32::TrapFrame
struct x32::TrapFrame
Definition at line 295 of file cpu.hpp.
Data Fields
uint32_t cs
uint32_t eax
uint32_t ebp
uint32_t ebx
uint32_t ecx
uint32_t edi
uint32_t edx
EFLAGS eflags
uint32_t eip
uint32_t ErrorCode
uint32_t esi
uint32_t esp
uint32_t InterruptNumber
uint32_t r3_esp
uint32_t r3_ss
x32::DR6
union x32::DR6
Definition at line 317 of file cpu.hpp.
Data Fields
struct DR6 __unnamed__
uint64_t raw
x32::DR7
union x32::DR7
Definition at line 345 of file cpu.hpp.
Data Fields
struct DR7 __unnamed__
uint32_t raw
x32::FXState
struct x32::FXState
Definition at line 397 of file cpu.hpp.
Data Fields
uint16_t fcw FPU control word.
uint16_t fop FPU opcode.
uint16_t fsw FPU status word.
uint8_t ftw FPU tag words.
uint32_t mxcsr SSE control register.
uint32_t mxcsrmask SSE control register mask.
uint64_t rdp FPU data pointer.
uint8_t Reserved Reserved (zero)
uint64_t rip PFU instruction pointer.
uint8_t st[8][16] FPU registers (last 6 bytes reserved)
uint8_t xmm[16][16] XMM registers.
x64::__packed
union x64::__packed
MSR_APIC_BASE structure.
See also
MSR_APIC_BASE
Definition at line 529 of file cpu.hpp.
Data Fields
struct __packed __unnamed__
struct __packed __aligned
uint64_t raw
uint32_t raw
x64::RFLAGS
union x64::RFLAGS
Definition at line 563 of file cpu.hpp.
Data Fields
struct RFLAGS __unnamed__
uint64_t raw
x64::TrapFrame
struct x64::TrapFrame
Definition at line 615 of file cpu.hpp.
Data Fields
uint64_t cs
uint64_t ErrorCode
uint64_t InterruptNumber
uint64_t r10
uint64_t r11
uint64_t r12
uint64_t r13
uint64_t r14
uint64_t r15
uint64_t r8
uint64_t r9
uint64_t rax
uint64_t rbp
uint64_t rbx
uint64_t rcx
uint64_t rdi
uint64_t rdx
RFLAGS rflags
uint64_t rip
uint64_t rsi
uint64_t rsp
uint64_t ss
x64::EFER
union x64::EFER
Definition at line 644 of file cpu.hpp.
Data Fields
struct EFER __unnamed__
uint64_t raw
x64::DR6
union x64::DR6
Definition at line 674 of file cpu.hpp.
Data Fields
struct DR6 __unnamed__
uint64_t raw
x64::DR7
union x64::DR7
Definition at line 704 of file cpu.hpp.
Data Fields
struct DR7 __unnamed__
uint64_t raw
x64::PageFaultErrorCode
union x64::PageFaultErrorCode
Definition at line 758 of file cpu.hpp.
Data Fields
struct PageFaultErrorCode __unnamed__
uint64_t raw
x64::SelectorErrorCode
union x64::SelectorErrorCode
Definition at line 787 of file cpu.hpp.
Data Fields
struct SelectorErrorCode __unnamed__
uint64_t raw
x64::FXState
struct x64::FXState
Definition at line 808 of file cpu.hpp.
Data Fields
uint16_t fcw FPU control word.
uint16_t fop FPU opcode.
uint16_t fsw FPU status word.
uint8_t ftw FPU tag words.
uint32_t mxcsr SSE control register.
uint32_t mxcsrmask SSE control register mask.
uint64_t rdp FPU data pointer.
uint8_t Reserved Reserved (zero)
uint64_t rip PFU instruction pointer.
uint8_t st[8][16] FPU registers (last 6 bytes reserved)
uint8_t xmm[16][16] XMM registers.
aarch64::TrapFrame
struct aarch64::TrapFrame
Definition at line 932 of file cpu.hpp.
Data Fields
uint64_t elr_el1
uint64_t ErrorCode
uint64_t InterruptNumber
uint64_t sp_el0
uint64_t spsr_el1
uint64_t x19
uint64_t x20
uint64_t x21
uint64_t x22
uint64_t x23
uint64_t x24
uint64_t x25
uint64_t x26
uint64_t x27
uint64_t x28
uint64_t x29
uint64_t x30
x32::__packed.__unnamed544__
struct x32::__packed.__unnamed544__
Definition at line 222 of file cpu.hpp.
Data Fields
uint32_t ApicBaseHi: 32 APIC Base High Address.
uint32_t ApicBaseLo: 20 APIC Base Low Address.
uint32_t BSP: 1 BSP Flag.
If the BSP flag is set to 1, the processor is the bootstrap processor.
uint32_t EN: 1 APIC Global Enable.
uint32_t EXTD: 1 Enable x2APIC mode.
uint32_t Reserved0: 8 Reserved.
uint32_t Reserved1: 1 Reserved.
x32::EFLAGS.__unnamed546__
struct x32::EFLAGS.__unnamed546__
Definition at line 247 of file cpu.hpp.
Data Fields
uint32_t AC: 1 Alignment Check.
uint32_t AF: 1 Auxiliary Carry Flag.
uint32_t AlwaysOne: 1 Reserved.
uint32_t CF: 1 Carry Flag.
uint32_t DF: 1 Direction Flag.
uint32_t ID: 1 ID Flag.
uint32_t IF: 1 Interrupt Enable Flag.
uint32_t IOPL: 2 I/O Privilege Level.
uint32_t NT: 1 Nested Task.
uint32_t OF: 1 Overflow Flag.
uint32_t PF: 1 Parity Flag.
uint32_t Reserved0: 1 Reserved.
uint32_t Reserved1: 1 Reserved.
uint32_t Reserved2: 1 Reserved.
uint32_t RF: 1 Resume Flag.
uint32_t SF: 1 Sign Flag.
uint32_t TF: 1 Trap Flag.
uint32_t VIF: 1 Virtual Interrupt Flag.
uint32_t VIP: 1 Virtual Interrupt Pending.
uint32_t VM: 1 Virtual 8086 Mode.
uint32_t ZF: 1 Zero Flag.
x32::DR6.__unnamed548__
struct x32::DR6.__unnamed548__
Definition at line 319 of file cpu.hpp.
Data Fields
uint64_t B0: 1 Breakpoint #0 Condition Detected.
uint64_t B1: 1 Breakpoint #1 Condition Detected.
uint64_t B2: 1 Breakpoint #2 Condition Detected.
uint64_t B3: 1 Breakpoint #3 Condition Detected.
uint64_t BD: 1 Breakpoint Debug Access Detected.
uint64_t BS: 1 Breakpoint Single Step.
uint64_t BT: 1 Breakpoint Task Switch.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 15 Reserved.
x32::DR7.__unnamed550__
struct x32::DR7.__unnamed550__
Definition at line 347 of file cpu.hpp.
Data Fields
uint32_t G0: 1 Global Exact Breakpoint #0 Enabled.
uint32_t G1: 1 Global Exact Breakpoint #1 Enabled.
uint32_t G2: 1 Global Exact Breakpoint #2 Enabled.
uint32_t G3: 1 Global Exact Breakpoint #3 Enabled.
uint32_t GD: 1 General Detect Enabled.
uint32_t GE: 1 Global Exact Breakpoint Enabled.
uint32_t L0: 1 Local Exact Breakpoint #0 Enabled.
uint32_t L1: 1 Local Exact Breakpoint #1 Enabled.
uint32_t L2: 1 Local Exact Breakpoint #2 Enabled.
uint32_t L3: 1 Local Exact Breakpoint #3 Enabled.
uint32_t LE: 1 Local Exact Breakpoint Enabled.
uint32_t LEN0: 2 Length of Breakpoint #0.
uint32_t LEN1: 2 Length of Breakpoint #1.
uint32_t LEN2: 2 Length of Breakpoint #2.
uint32_t LEN3: 2 Length of Breakpoint #3.
uint32_t Reserved0: 1 Reserved.
uint32_t Reserved1: 2 Reserved.
uint32_t Reserved2: 2 Reserved.
uint32_t RW0: 2 Type of Transaction(s) to Trap.
uint32_t RW1: 2 Type of Transaction(s) to Trap.
uint32_t RW2: 2 Type of Transaction(s) to Trap.
uint32_t RW3: 2 Type of Transaction(s) to Trap.
x64::__packed.__aligned
struct x64::__packed.__aligned
Definition at line 531 of file cpu.hpp.
Data Fields
uint64_t ABAHigh: 32 APIC Base High Address.
uint64_t ABALow: 20 APIC Base Low Address.
uint64_t AE: 1
APIC Enable
uint64_t BSC: 1
Boot Strap CPU Core
uint64_t EXTD: 1
x2APIC Mode Enable
uint64_t Reserved0: 8
Reserved
uint64_t Reserved1: 1
Reserved
uint64_t Reserved2: 12
Reserved
x64::__packed.__unnamed554__
struct x64::__packed.__unnamed554__
Definition at line 555 of file cpu.hpp.
Data Fields
uint64_t AID: 8
uint64_t Reserved: 24
x64::RFLAGS.__unnamed558__
struct x64::RFLAGS.__unnamed558__
Definition at line 565 of file cpu.hpp.
Data Fields
uint64_t AC: 1 Alignment Check.
uint64_t AF: 1 Auxiliary Carry Flag.
uint64_t AlwaysOne: 1 Reserved.
uint64_t CF: 1 Carry Flag.
uint64_t DF: 1 Direction Flag.
uint64_t ID: 1 ID Flag (Allow using CPUID instruction)
uint64_t IF: 1 Interrupt Enable Flag.
uint64_t IOPL: 2 I/O Privilege Level.
uint64_t NT: 1 Nested Task.
uint64_t OF: 1 Overflow Flag.
uint64_t PF: 1 Parity Flag.
uint64_t Reserved0: 1 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 1 Reserved.
uint64_t Reserved3: 10 Reserved.
uint64_t RF: 1 Resume Flag.
uint64_t SF: 1 Sign Flag.
uint64_t TF: 1 Trap Flag.
uint64_t VIF: 1 Virtual Interrupt Flag.
uint64_t VIP: 1 Virtual Interrupt Pending.
uint64_t VM: 1 Virtual 8086 Mode.
uint64_t ZF: 1 Zero Flag.
x64::EFER.__unnamed580__
struct x64::EFER.__unnamed580__
Definition at line 646 of file cpu.hpp.
Data Fields
uint64_t FFXSR: 1 Enable Fast FXSAVE/FXRSTOR.
uint64_t LMA: 1 Indicates long.
uint64_t LME: 1 Enable long mode.
uint64_t LMSLE: 1 Enable Long Mode Segment Limit.
uint64_t NXE: 1 Enable No-Execute Bit.
uint64_t Reserved0: 7 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 32 Reserved.
uint64_t SCE: 1 Enable syscall & sysret instructions in 64-bit mode.
uint64_t SVME: 1 Enable Secure Virtual Machine.
uint64_t TCE: 1 Enable Translation Cache Extension.
x64::DR6.__unnamed589__
struct x64::DR6.__unnamed589__
Definition at line 676 of file cpu.hpp.
Data Fields
uint64_t B0: 1 Breakpoint #0 Condition Detected.
uint64_t B1: 1 Breakpoint #1 Condition Detected.
uint64_t B2: 1 Breakpoint #2 Condition Detected.
uint64_t B3: 1 Breakpoint #3 Condition Detected.
uint64_t BD: 1 Breakpoint Debug Access Detected.
uint64_t BS: 1 Breakpoint Single Step.
uint64_t BT: 1 Breakpoint Task Switch.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 15 Reserved.
uint64_t Reserved3: 32 Reserved.
x64::DR7.__unnamed598__
struct x64::DR7.__unnamed598__
Definition at line 706 of file cpu.hpp.
Data Fields
uint64_t G0: 1 Global Exact Breakpoint #0 Enabled.
uint64_t G1: 1 Global Exact Breakpoint #1 Enabled.
uint64_t G2: 1 Global Exact Breakpoint #2 Enabled.
uint64_t G3: 1 Global Exact Breakpoint #3 Enabled.
uint64_t GD: 1 General Detect Enabled.
uint64_t GE: 1 Global Exact Breakpoint Enabled.
uint64_t L0: 1 Local Exact Breakpoint #0 Enabled.
uint64_t L1: 1 Local Exact Breakpoint #1 Enabled.
uint64_t L2: 1 Local Exact Breakpoint #2 Enabled.
uint64_t L3: 1 Local Exact Breakpoint #3 Enabled.
uint64_t LE: 1 Local Exact Breakpoint Enabled.
uint64_t LEN0: 2 Length of Breakpoint #0.
uint64_t LEN1: 2 Length of Breakpoint #1.
uint64_t LEN2: 2 Length of Breakpoint #2.
uint64_t LEN3: 2 Length of Breakpoint #3.
uint64_t Reserved0: 1 Reserved.
uint64_t Reserved1: 2 Reserved.
uint64_t Reserved2: 2 Reserved.
uint64_t Reserved3: 32 Reserved.
uint64_t RW0: 2 Type of Transaction(s) to Trap.
uint64_t RW1: 2 Type of Transaction(s) to Trap.
uint64_t RW2: 2 Type of Transaction(s) to Trap.
uint64_t RW3: 2 Type of Transaction(s) to Trap.
x64::PageFaultErrorCode.__unnamed609__
struct x64::PageFaultErrorCode.__unnamed609__
Definition at line 760 of file cpu.hpp.
Data Fields
uint64_t I: 1 When set, the page fault was caused by an instruction fetch. This only applies when the No-Execute bit is supported and enabled.
uint64_t P: 1 When set, the page fault was caused by a page-protection violation. When not set, it was caused by a non-present page.
uint64_t PK: 1 When set, the page fault was caused by a protection-key violation. The PKRU register (for user-mode accesses) or PKRS MSR (for supervisor-mode accesses) specifies the protection key rights.
uint64_t R: 1 When set, one or more page directory entries contain reserved bits which are set to 1. This only applies when the PSE or PAE flags in CR4 are set to 1.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 16 Reserved.
uint64_t SGX: 1 When set, the fault was due to an SGX violation. The fault is unrelated to ordinary paging.
uint64_t SS: 1 When set, the page fault was caused by a shadow stack access.
uint64_t U: 1 When set, the page fault was caused while CPL = 3. This does not necessarily mean that the page fault was a privilege violation.
uint64_t W: 1 When set, the page fault was caused by a write access. When not set, it was caused by a read access.
x64::SelectorErrorCode.__unnamed623__
struct x64::SelectorErrorCode.__unnamed623__
Definition at line 789 of file cpu.hpp.
Data Fields
uint64_t External: 1 When set, the exception originated externally to the processor.
uint64_t Idx: 13 The index in the GDT, IDT or LDT.
uint64_t Reserved: 16 Reserved.
uint64_t Table: 2 IDT/GDT/LDT Table.
0b00 - The Selector Index references a descriptor in the GDT.
0b01 - The Selector Index references a descriptor in the IDT.
0b10 - The Selector Index references a descriptor in the LDT.
0b11 - The Selector Index references a descriptor in the IDT.
Macro Definition Documentation
thisPageTable
#define thisPageTable (Memory::PageTable *)CPU::PageTable()
Definition at line 206 of file cpu.hpp.
Function Documentation
Counter()
uint64_t Counter ()
Get CPU counter value.
Halt()
static SafeFunction __always_inline void Halt (bool Loop = false) inline static
Halt the CPU.
Definition at line 177 of file cpu.hpp.
     {
         do
         {
 #if defined(a86)
             asmv("hlt");
 #elif defined(aa64)
             asmv("wfe");
 #endif
         } while (Loop);
     }
References asmv().
Referenced by arm64Entry(), cmd_exit(), cmd_reboot(), cmd_shutdown(), CrashHandler::Handle(), CrashHandler::Handle_x86_32(), CrashHandler::Handle_x86_64(), KernelMainThread(), Main(), Memory::Physical::RequestPages(), StartCPU(), NetworkInterfaceManager::NetworkInterface::StartNetworkStack(), and ThreadDoExit().
InitializeFeatures()
void InitializeFeatures (int Core)
To be used only once.
Interrupts()
bool Interrupts (InterruptsType Type = Check)
Check if interrupts are enabled.
Returns
true If InterruptsType::Check and interrupts are enabled, or if other InterruptsType were executed successfully
false If InterruptsType::Check and interrupts are disabled, or if other InterruptsType failed
PageTable()
void* PageTable (void * PT = nullptr)
Get/Set the CPU's page table.
Parameters
PT The new page table, if empty, the current page table will be returned
Returns
Get: The current page table
Set: The old page table
Referenced by Tasking::Signal::RestoreHandleSignal().
Variable Documentation
fcw
uint16_t fcw
FPU control word.
Definition at line 1 of file cpu.hpp.
fop
uint16_t fop
FPU opcode.
Definition at line 9 of file cpu.hpp.
fsw
uint16_t fsw
FPU status word.
Definition at line 3 of file cpu.hpp.
ftw
uint8_t ftw
FPU tag words.
Definition at line 5 of file cpu.hpp.
mxcsr
uint32_t mxcsr
SSE control register.
Definition at line 15 of file cpu.hpp.
mxcsrmask
uint32_t mxcsrmask
SSE control register mask.
Definition at line 17 of file cpu.hpp.
rdp
uint64_t rdp
FPU data pointer.
Definition at line 13 of file cpu.hpp.
Reserved
uint8_t Reserved
Reserved (zero)
Definition at line 7 of file cpu.hpp.
rip
uint64_t rip
PFU instruction pointer.
Definition at line 11 of file cpu.hpp.
Referenced by undot().
st
uint8_t st[8][16]
FPU registers (last 6 bytes reserved)
Definition at line 19 of file cpu.hpp.
Referenced by __syscall_cp_c(), allocate_new_page(), F_CastTicker(), find_absolute_program(), SymbolResolver::Symbols::GetSymbol(), mailstat(), P_SetMobjState(), P_SpawnMobj(), printf_core(), printfinfo(), printsome(), search_for_command(), sprint_status48(), start_job(), vfscanf(), waitforjob(), and wprintf_core().
xmm
uint8_t xmm[16][16]
XMM registers.
Definition at line 21 of file cpu.hpp.