Fennix: Userspace/apps/base/busybox/networking/libiproute/ll_map.h File Reference
ll_map.h File Reference
Functions
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN int ll_remember_index (const struct sockaddr_nl *who, struct nlmsghdr *n, void *arg) FAST_FUNC
int ll_init_map (struct rtnl_handle *rth) FAST_FUNC
int xll_name_to_index (const char *name) FAST_FUNC
const char * ll_index_to_name (int idx) FAST_FUNC
unsigned ll_index_to_flags (int idx) FAST_FUNC
Function Documentation
ll_index_to_flags()
unsigned ll_index_to_flags (int idx)
Definition at line 123 of file ll_map.c.
 {
     struct idxmap *im;
     if (idx == 0)
         return 0;
     im = find_by_index(idx);
     if (im)
         return im->flags;
     return 0;
 }
References find_by_index(), idxmap::flags, and idx.
Referenced by print_linkinfo().
ll_index_to_name()
const char* ll_index_to_name (int idx)
Definition at line 103 of file ll_map.c.
 {
     //static char nbuf[16];
     return ll_idx_n2a(idx/*, nbuf*/);
 }
References idx, and ll_idx_n2a().
Referenced by ipaddr_list_or_flush(), print_addrinfo(), print_class(), print_linkinfo(), print_neigh(), print_qdisc(), and print_route().
ll_init_map()
int ll_init_map (struct rtnl_handle * rth)
Definition at line 173 of file ll_map.c.
 {
     xrtnl_wilddump_request(rth, AF_UNSPEC, RTM_GETLINK);
     xrtnl_dump_filter(rth, ll_remember_index, NULL);
     return 0;
 }
References AF_UNSPEC, ll_remember_index(), NULL, RTM_GETLINK, xrtnl_dump_filter(), and xrtnl_wilddump_request().
Referenced by do_add_or_delete(), ipaddr_modify(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), and tc_main().
ll_remember_index()
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN int ll_remember_index (const struct sockaddr_nl * who, struct nlmsghdr * n, void * arg)
xll_name_to_index()
int xll_name_to_index (const char * name)
Definition at line 135 of file ll_map.c.
 {
     int ret = 0;
 /* caching is not warranted - no users which repeatedly call it */
 #ifdef UNUSED
     static char ncache[16];
     static int icache;
     struct idxmap *im;
     int i;
     if (name == NULL)
         goto out;
     if (icache && strcmp(name, ncache) == 0) {
         ret = icache;
         goto out;
     }
     if (idxmap) {
         for (i = 0; i < 16; i++) {
             for (im = idxmap[i]; im; im = im->next) {
                 if (strcmp(im->name, name) == 0) {
                     icache = im->index;
                     strcpy(ncache, name);
                     ret = im->index;
                     goto out;
                 }
             }
         }
     }
 #endif
     ret = if_nametoindex(name);
 /* out:*/
     if (ret <= 0)
         bb_error_msg_and_die("can't find device '%s'", name);
     return ret;
 }
References bb_error_msg_and_die(), i, if_nametoindex(), idxmap::index, idxmap::name, idxmap::next, NULL, out(), strcmp, and strcpy.
Referenced by do_add_or_delete(), do_set(), ipaddr_list_or_flush(), ipaddr_modify(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), set_master(), set_netns(), and tc_main().