Fennix: Userspace/musl/src/mman/shm_open.c File Reference
shm_open.c File Reference
#include <sys/mman.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <limits.h>
#include <pthread.h>
Functions
char * __shm_mapname (const char *name, char *buf)
int shm_open (const char *name, int flag, mode_t mode)
int shm_unlink (const char *name)
Function Documentation
__shm_mapname()
char* __shm_mapname (const char * name, char * buf)
Definition at line 9 of file shm_open.c.
 {
     char *p;
     while (*name == '/') name++;
     if (*(p = __strchrnul(name, '/')) || p==name ||
         (p-name <= 2 && name[0]=='.' && p[-1]=='.')) {
         errno = EINVAL;
         return 0;
     }
     if (p-name > NAME_MAX) {
         errno = ENAMETOOLONG;
         return 0;
     }
     memcpy(buf, "/dev/shm/", 9);
     memcpy(buf+9, name, p-name+1);
     return buf;
 }
References __strchrnul(), buf, EINVAL, ENAMETOOLONG, errno, memcpy, NAME_MAX, and p.
Referenced by sem_open(), shm_open(), and shm_unlink().
shm_open()
int shm_open (const char * name, int flag, mode_t mode)
Definition at line 27 of file shm_open.c.
 {
     int cs;
     char buf[NAME_MAX+10];
     if (!(name = __shm_mapname(name, buf))) return -1;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     int fd = open(name, flag|O_NOFOLLOW|O_CLOEXEC|O_NONBLOCK, mode);
     pthread_setcancelstate(cs, 0);
     return fd;
 }
References __shm_mapname(), buf, fd, NAME_MAX, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, open(), PTHREAD_CANCEL_DISABLE, and pthread_setcancelstate().
shm_unlink()
int shm_unlink (const char * name)
Definition at line 38 of file shm_open.c.
 {
     char buf[NAME_MAX+10];
     if (!(name = __shm_mapname(name, buf))) return -1;
     return unlink(name);
 }
References __shm_mapname(), buf, NAME_MAX, and unlink().
Referenced by sem_unlink().