Fennix: Userspace/apps/base/bash/test.c File Reference
test.c File Reference
#include <stdio.h>
#include "bashtypes.h"
#include <errno.h>
#include "posixstat.h"
#include "filecntl.h"
#include "stat-time.h"
#include "bashintl.h"
#include "shell.h"
#include "pathexp.h"
#include "test.h"
#include "builtins/common.h"
#include <glob/strmatch.h>
Macros
#define STRCOLLEQ(a, b) ((a)[0] == (b)[0] && strcoll ((a), (b)) == 0)
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define F_OK 0
#define EQ 0
#define NE 1
#define LT 2
#define GT 3
#define LE 4
#define GE 5
#define NT 0
#define OT 1
#define EF 2
#define TRUE 1
#define FALSE 0
#define SHELL_BOOLEAN(value) (!(value))
#define TEST_ERREXIT_STATUS 2
#define test_exit(val) do { test_error_return = val; sh_longjmp (test_exit_buf, 1); } while (0)
#define advance(f) do { ++pos; if (f && pos >= argc) beyond (); } while (0)
#define unary_advance() do { advance (1); ++pos; } while (0)
#define ANDOR(s) (s[0] == '-' && (s[1] == 'a' || s[1] == 'o') && s[2] == 0)
#define ONE_ARG_TEST(s) ((s)[0] != '\0')
Functions
int sh_stat PARAMS ((const char *, struct stat *))
static void test_syntax_error PARAMS ((char *, char *))
static void beyond ()
static void integer_expected_error (char *pch)
static int expr ()
static int or ()
static int and ()
static int term ()
static int stat_mtime (char *fn, struct stat *st, struct timespec *ts)
static int filecomp (char *s, char *t, int op)
static int arithcomp (char *s, char *t, int op, int flags)
static int patcomp (char *string, char *pat, int op)
int binary_test (char *op, char *arg1, char *arg2, int flags)
static int binary_operator ()
static int unary_operator ()
int unary_test (char *op, char *arg, int flags)
int test_binop (char *op)
int test_unop (char *op)
static int two_arguments ()
static int three_arguments ()
static int posixtest ()
int test_command (int margc, char **margv)
Variables
int errno
static procenv_t test_exit_buf
static int test_error_return
static int pos
static int argc
static char ** argv
static int noeval
Macro Definition Documentation
advance
#define advance (f) do { ++pos; if (f && pos >= argc) beyond (); } while (0)
Definition at line 162 of file test.c.
ANDOR
#define ANDOR (s) (s[0] == '-' && (s[1] == 'a' || s[1] == 'o') && s[2] == 0)
Definition at line 779 of file test.c.
EF
#define EF 2
Definition at line 89 of file test.c.
EQ
#define EQ 0
Definition at line 80 of file test.c.
F_OK
#define F_OK 0
Definition at line 77 of file test.c.
FALSE
#define FALSE 0
Definition at line 96 of file test.c.
GE
#define GE 5
Definition at line 85 of file test.c.
GT
#define GT 3
Definition at line 83 of file test.c.
LE
#define LE 4
Definition at line 84 of file test.c.
LT
#define LT 2
Definition at line 82 of file test.c.
NE
#define NE 1
Definition at line 81 of file test.c.
NT
#define NT 0
Definition at line 87 of file test.c.
ONE_ARG_TEST
#define ONE_ARG_TEST (s) ((s)[0] != '\0')
Definition at line 783 of file test.c.
OT
#define OT 1
Definition at line 88 of file test.c.
R_OK
#define R_OK 4
Definition at line 74 of file test.c.
SHELL_BOOLEAN
#define SHELL_BOOLEAN (value) (!(value))
Definition at line 97 of file test.c.
STRCOLLEQ
#define STRCOLLEQ (a, b) ((a)[0] == (b)[0] && strcoll ((a), (b)) == 0)
Definition at line 71 of file test.c.
TEST_ERREXIT_STATUS
#define TEST_ERREXIT_STATUS 2
Definition at line 99 of file test.c.
test_exit
#define test_exit (val) do { test_error_return = val; sh_longjmp (test_exit_buf, 1); } while (0)
Definition at line 103 of file test.c.
TRUE
#define TRUE 1
Definition at line 95 of file test.c.
unary_advance
#define unary_advance () do { advance (1); ++pos; } while (0)
Definition at line 163 of file test.c.
W_OK
#define W_OK 2
Definition at line 75 of file test.c.
X_OK
#define X_OK 1
Definition at line 76 of file test.c.
Function Documentation
and()
static int and () static
Definition at line 205 of file test.c.
 {
   int value, v2;
   value = term ();
   if (pos < argc && argv[pos][0] == '-' && argv[pos][1] == 'a' && !argv[pos][2])
     {
       advance (0);
       v2 = and ();
       return (value && v2);
     }
   return (value);
 }
References advance, argc, argv, pos, term(), v2, and value.
Referenced by or().
arithcomp()
static int arithcomp (char * s, char * t, int op, int flags) static
Definition at line 335 of file test.c.
 {
   intmax_t l, r;
   int expok;
   if (flags & TEST_ARITHEXP)        /* conditional command */
     {
       int eflag;
       eflag = (shell_compatibility_level > 51) ? 0 : EXP_EXPANDED;
       l = evalexp (s, eflag, &expok);
       if (expok == 0)
     return (FALSE);     /* should probably longjmp here */
       r = evalexp (t, eflag, &expok);
       if (expok == 0)
     return (FALSE);     /* ditto */
     }
   else
     {
       if (legal_number (s, &l) == 0)
     integer_expected_error (s);
       if (legal_number (t, &r) == 0)
     integer_expected_error (t);
     }
   switch (op)
     {
     case EQ: return (l == r);
     case NE: return (l != r);
     case LT: return (l < r);
     case GT: return (l > r);
     case LE: return (l <= r);
     case GE: return (l >= r);
     }
   return (FALSE);
 }
References EQ, evalexp(), EXP_EXPANDED, FALSE, flags, GE, GT, integer_expected_error(), LE, legal_number(), LT, NE, r, shell_compatibility_level, t, and TEST_ARITHEXP.
Referenced by binary_test().
beyond()
static void beyond () static
Definition at line 145 of file test.c.
 {
   test_syntax_error (_("argument expected"), (char *)NULL);
 }
References _, and NULL.
Referenced by expr(), and term().
binary_operator()
static int binary_operator () static
Definition at line 443 of file test.c.
 {
   int value;
   char *w;
   w = argv[pos + 1];
   if ((w[0] == '=' && (w[1] == '\0' || (w[1] == '=' && w[2] == '\0'))) || /* =, == */
       ((w[0] == '>' || w[0] == '<') && w[1] == '\0') ||     /* <, > */
       (w[0] == '!' && w[1] == '=' && w[2] == '\0'))     /* != */
     {
       value = binary_test (w, argv[pos], argv[pos + 2], 0);
       pos += 3;
       return (value);
     }
 #if defined (PATTERN_MATCHING)
   if ((w[0] == '=' || w[0] == '!') && w[1] == '~' && w[2] == '\0')
     {
       value = patcomp (argv[pos], argv[pos + 2], w[0] == '=' ? EQ : NE);
       pos += 3;
       return (value);
     }
 #endif
   if ((w[0] != '-' || w[3] != '\0') || test_binop (w) == 0)
     {
       test_syntax_error (_("%s: binary operator expected"), w);
       /* NOTREACHED */
       return (FALSE);
     }
   value = binary_test (w, argv[pos], argv[pos + 2], 0);
   pos += 3;
   return value;
 }
References _, argv, binary_test(), EQ, FALSE, NE, patcomp(), pos, test_binop(), and value.
Referenced by term(), and three_arguments().
binary_test()
int binary_test (char * op, char * arg1, char * arg2, int flags)
Definition at line 387 of file test.c.
 {
   int patmatch;
   patmatch = (flags & TEST_PATMATCH);
   if (op[0] == '=' && (op[1] == '\0' || (op[1] == '=' && op[2] == '\0')))
     return (patmatch ? patcomp (arg1, arg2, EQ) : STREQ (arg1, arg2));
   else if ((op[0] == '>' || op[0] == '<') && op[1] == '\0')
     {
 #if defined (HAVE_STRCOLL)
       if (shell_compatibility_level > 40 && flags & TEST_LOCALE)
     return ((op[0] == '>') ? (strcoll (arg1, arg2) > 0) : (strcoll (arg1, arg2) < 0));
       else
 #endif
     return ((op[0] == '>') ? (strcmp (arg1, arg2) > 0) : (strcmp (arg1, arg2) < 0));
     }
   else if (op[0] == '!' && op[1] == '=' && op[2] == '\0')
     return (patmatch ? patcomp (arg1, arg2, NE) : (STREQ (arg1, arg2) == 0));
   else if (op[2] == 't')
     {
       switch (op[1])
     {
     case 'n': return (filecomp (arg1, arg2, NT));       /* -nt */
     case 'o': return (filecomp (arg1, arg2, OT));       /* -ot */
     case 'l': return (arithcomp (arg1, arg2, LT, flags));   /* -lt */
     case 'g': return (arithcomp (arg1, arg2, GT, flags));   /* -gt */
     }
     }
   else if (op[1] == 'e')
     {
       switch (op[2])
     {
     case 'f': return (filecomp (arg1, arg2, EF));       /* -ef */
     case 'q': return (arithcomp (arg1, arg2, EQ, flags));   /* -eq */
     }
     }
   else if (op[2] == 'e')
     {
       switch (op[1])
     {
     case 'n': return (arithcomp (arg1, arg2, NE, flags));   /* -ne */
     case 'g': return (arithcomp (arg1, arg2, GE, flags));   /* -ge */
     case 'l': return (arithcomp (arg1, arg2, LE, flags));   /* -le */
     }
     }
   return (FALSE);   /* should never get here */
 }
References arg1, arg2, arithcomp(), EF, EQ, FALSE, filecomp(), flags, GE, GT, LE, LT, NE, NT, OT, patcomp(), shell_compatibility_level, strcmp, strcoll(), STREQ, TEST_LOCALE, and TEST_PATMATCH.
Referenced by binary_operator().
expr()
static int expr () static
Definition at line 170 of file test.c.
 {
   if (pos >= argc)
     beyond ();
   return (FALSE ^ or ());       /* Same with this. */
 }
References argc, beyond(), FALSE, or(), and pos.
Referenced by __assert_fail(), evalexp(), posixtest(), subexpr(), and term().
filecomp()
static int filecomp (char * s, char * t, int op) static
Definition at line 306 of file test.c.
 {
   struct stat st1, st2;
   struct timespec ts1, ts2;
   int r1, r2;
   if ((r1 = stat_mtime (s, &st1, &ts1)) < 0)
     {
       if (op == EF)
     return (FALSE);
     }
   if ((r2 = stat_mtime (t, &st2, &ts2)) < 0)
     {
       if (op == EF)
     return (FALSE);
     }
   switch (op)
     {
     case OT: return (r1 < r2 || (r2 == 0 && timespec_cmp (ts1, ts2) < 0));
     case NT: return (r1 > r2 || (r1 == 0 && timespec_cmp (ts1, ts2) > 0));
     case EF: return (same_file (s, t, &st1, &st2));
     }
   return (FALSE);
 }
References EF, FALSE, NT, OT, r1, r2, same_file(), stat_mtime(), t, and timespec_cmp().
Referenced by binary_test().
integer_expected_error()
static void integer_expected_error (char * pch) static
Definition at line 153 of file test.c.
 {
   test_syntax_error (_("%s: integer expression expected"), pch);
 }
References _.
Referenced by arithcomp().
or()
static int or () static
Definition at line 184 of file test.c.
 {
   int value, v2;
   value = and ();
   if (pos < argc && argv[pos][0] == '-' && argv[pos][1] == 'o' && !argv[pos][2])
     {
       advance (0);
       v2 = or ();
       return (value || v2);
     }
   return (value);
 }
References advance, and(), argc, argv, pos, v2, and value.
Referenced by expr().
PARAMS() [1/2]
static void test_syntax_error PARAMS ((char *, char *)) static
Definition at line 113 of file test.c.
 {
   builtin_error (format, arg);
   test_exit (TEST_ERREXIT_STATUS);
 }
PARAMS() [2/2]
int sh_stat PARAMS ((const char *, struct stat *))
patcomp()
static int patcomp (char * string, char * pat, int op) static
Definition at line 376 of file test.c.
 {
   int m;
   m = strmatch (pat, string, FNMATCH_EXTFLAG|FNMATCH_IGNCASE);
   return ((op == EQ) ? (m == 0) : (m != 0));
 }
References EQ, FNMATCH_EXTFLAG, FNMATCH_IGNCASE, pat, and strmatch().
Referenced by binary_operator(), and binary_test().
posixtest()
static int posixtest () static
Definition at line 822 of file test.c.
 {
   int value;
   switch (argc - 1) /* one extra passed in */
     {
       case 0:
     value = FALSE;
     pos = argc;
     break;
       case 1:
     value = ONE_ARG_TEST(argv[1]);
     pos = argc;
     break;
       case 2:
     value = two_arguments ();
     pos = argc;
     break;
       case 3:
     value = three_arguments ();
     break;
       case 4:
     if (argv[pos][0] == '!' && argv[pos][1] == '\0')
       {
         advance (1);
         value = !three_arguments ();
         break;
       }
     else if (argv[pos][0] == '(' && argv[pos][1] == '\0' && argv[argc-1][0] == ')' && argv[argc-1][1] == '\0')
       {
         advance (1);
         value = two_arguments ();
         pos = argc;
         break;
       }
     /* FALLTHROUGH */
       default:
     value = expr ();
     }
   return (value);
 }
References advance, argc, argv, expr(), FALSE, ONE_ARG_TEST, pos, three_arguments(), two_arguments(), and value.
Referenced by test_command().
stat_mtime()
static int stat_mtime (char * fn, struct stat * st, struct timespec * ts) static
Definition at line 291 of file test.c.
 {
   int r;
   r = sh_stat (fn, st);
   if (r < 0)
     return r;
   *ts = get_stat_mtime (st);
   return 0;
 }
References get_stat_mtime(), r, and sh_stat().
Referenced by filecomp().
term()
static int term () static
Definition at line 239 of file test.c.
 {
   int value;
   if (pos >= argc)
     beyond ();
   /* Deal with leading `not's. */
   if (argv[pos][0] == '!' && argv[pos][1] == '\0')
     {
       value = 0;
       while (pos < argc && argv[pos][0] == '!' && argv[pos][1] == '\0')
     {
       advance (1);
       value = 1 - value;
     }
       return (value ? !term() : term());
     }
   /* A paren-bracketed argument. */
   if (argv[pos][0] == '(' && argv[pos][1] == '\0') /* ) */
     {
       advance (1);
       value = expr ();
       if (argv[pos] == 0) /* ( */
     test_syntax_error (_("`)' expected"), (char *)NULL);
       else if (argv[pos][0] != ')' || argv[pos][1]) /* ( */
     test_syntax_error (_("`)' expected, found %s"), argv[pos]);
       advance (0);
       return (value);
     }
   /* are there enough arguments left that this could be dyadic? */
   if ((pos + 3 <= argc) && test_binop (argv[pos + 1]))
     value = binary_operator ();
   /* Might be a switch type argument -- make sure we have enough arguments for
      the unary operator and argument */
   else if ((pos + 2) <= argc && test_unop (argv[pos]))
     value = unary_operator ();
   else
     {
       value = argv[pos][0] != '\0';
       advance (0);
     }
   return (value);
 }
References _, advance, argc, argv, beyond(), binary_operator(), expr(), NULL, pos, test_binop(), test_unop(), unary_operator(), and value.
Referenced by and().
test_binop()
int test_binop (char * op)
Definition at line 687 of file test.c.
 {
   if (op[0] == '=' && op[1] == '\0')
     return (1);     /* '=' */
   else if ((op[0] == '<' || op[0] == '>') && op[1] == '\0')  /* string <, > */
     return (1);
   else if ((op[0] == '=' || op[0] == '!') && op[1] == '=' && op[2] == '\0')
     return (1);     /* `==' and `!=' */
 #if defined (PATTERN_MATCHING)
   else if (op[2] == '\0' && op[1] == '~' && (op[0] == '=' || op[0] == '!'))
     return (1);
 #endif
   else if (op[0] != '-' || op[1] == '\0' || op[2] == '\0' || op[3] != '\0')
     return (0);
   else
     {
       if (op[2] == 't')
     switch (op[1])
       {
       case 'n':     /* -nt */
       case 'o':     /* -ot */
       case 'l':     /* -lt */
       case 'g':     /* -gt */
         return (1);
       default:
         return (0);
       }
       else if (op[1] == 'e')
     switch (op[2])
       {
       case 'q':     /* -eq */
       case 'f':     /* -ef */
         return (1);
       default:
         return (0);
       }
       else if (op[2] == 'e')
     switch (op[1])
       {
       case 'n':     /* -ne */
       case 'g':     /* -ge */
       case 'l':     /* -le */
         return (1);
       default:
         return (0);
       }
       else
     return (0);
     }
 }
Referenced by binary_operator(), term(), and three_arguments().
test_command()
int test_command (int margc, char ** margv)
Definition at line 876 of file test.c.
 {
   int value;
   int code;
   USE_VAR(margc);
   code = setjmp_nosigs (test_exit_buf);
   if (code)
     return (test_error_return);
   argv = margv;
   if (margv[0] && margv[0][0] == '[' && margv[0][1] == '\0')
     {
       --margc;
       if (margv[margc] && (margv[margc][0] != ']' || margv[margc][1]))
     test_syntax_error (_("missing `]'"), (char *)NULL);
       if (margc < 2)
     test_exit (SHELL_BOOLEAN (FALSE));
     }
   argc = margc;
   pos = 1;
   if (pos >= argc)
     test_exit (SHELL_BOOLEAN (FALSE));
   noeval = 0;
   value = posixtest ();
   if (pos != argc)
     {
       if (pos < argc && argv[pos][0] == '-')
     test_syntax_error (_("syntax error: `%s' unexpected"), argv[pos]);
       else
     test_syntax_error (_("too many arguments"), (char *)NULL);
     }
   test_exit (SHELL_BOOLEAN (value));
 }
References _, argc, argv, FALSE, noeval, NULL, pos, posixtest(), setjmp_nosigs, SHELL_BOOLEAN, test_error_return, test_exit, test_exit_buf, USE_VAR, and value.
test_unop()
int test_unop (char * op)
Definition at line 741 of file test.c.
 {
   if (op[0] != '-' || (op[1] && op[2] != 0))
     return (0);
   switch (op[1])
     {
     case 'a': case 'b': case 'c': case 'd': case 'e':
     case 'f': case 'g': case 'h': case 'k': case 'n':
     case 'o': case 'p': case 'r': case 's': case 't':
     case 'u': case 'v': case 'w': case 'x': case 'z':
     case 'G': case 'L': case 'O': case 'S': case 'N':
     case 'R':
       return (1);
     }
   return (0);
 }
Referenced by term(), two_arguments(), and unary_operator().
three_arguments()
static int three_arguments () static
Definition at line 786 of file test.c.
 {
   int value;
   if (test_binop (argv[pos+1]))
     {
       value = binary_operator ();
       pos = argc;
     }
   else if (ANDOR (argv[pos+1]))
     {
       if (argv[pos+1][1] == 'a')
     value = ONE_ARG_TEST(argv[pos]) && ONE_ARG_TEST(argv[pos+2]);
       else
     value = ONE_ARG_TEST(argv[pos]) || ONE_ARG_TEST(argv[pos+2]);
       pos = argc;
     }
   else if (argv[pos][0] == '!' && argv[pos][1] == '\0')
     {
       advance (1);
       value = !two_arguments ();
       pos = argc;
     }
   else if (argv[pos][0] == '(' && argv[pos+2][0] == ')')
     {
       value = ONE_ARG_TEST(argv[pos+1]);
       pos = argc;
     }
   else
     test_syntax_error (_("%s: binary operator expected"), argv[pos+1]);
   return (value);
 }
References _, advance, ANDOR, argc, argv, binary_operator(), ONE_ARG_TEST, pos, test_binop(), two_arguments(), and value.
Referenced by posixtest().
two_arguments()
static int two_arguments () static
Definition at line 762 of file test.c.
 {
   if (argv[pos][0] == '!' && argv[pos][1] == '\0')
     return (argv[pos + 1][0] == '\0');
   else if (argv[pos][0] == '-' && argv[pos][1] && argv[pos][2] == '\0')
     {
       if (test_unop (argv[pos]))
     return (unary_operator ());
       else
     test_syntax_error (_("%s: unary operator expected"), argv[pos]);
     }
   else
     test_syntax_error (_("%s: unary operator expected"), argv[pos]);
   return (0);
 }
References _, argv, pos, test_unop(), and unary_operator().
Referenced by posixtest(), and three_arguments().
unary_operator()
static int unary_operator () static
Definition at line 480 of file test.c.
 {
   char *op;
   intmax_t r;
   op = argv[pos];
   if (test_unop (op) == 0)
     return (FALSE);
   /* the only tricky case is `-t', which may or may not take an argument. */
   if (op[1] == 't')
     {
       advance (0);
       if (pos < argc)
     {
       if (legal_number (argv[pos], &r))
         {
           advance (0);
           return (unary_test (op, argv[pos - 1], 0));
         }
       else
         return (FALSE);
     }
       else
     return (unary_test (op, "1", 0));
     }
   /* All of the unary operators take an argument, so we first call
      unary_advance (), which checks to make sure that there is an
      argument, and then advances pos right past it.  This means that
      pos - 1 is the location of the argument. */
   unary_advance ();
   return (unary_test (op, argv[pos - 1], 0));
 }
References advance, argc, argv, FALSE, legal_number(), pos, r, test_unop(), unary_advance, and unary_test().
Referenced by term(), and two_arguments().
unary_test()
int unary_test (char * op, char * arg, int flags)
Definition at line 516 of file test.c.
 {
   intmax_t r;
   struct stat stat_buf;
   struct timespec mtime, atime;
   SHELL_VAR *v;
   int aflags;
   switch (op[1])
     {
     case 'a':           /* file exists in the file system? */
     case 'e':
       return (sh_stat (arg, &stat_buf) == 0);
     case 'r':           /* file is readable? */
       return (sh_eaccess (arg, R_OK) == 0);
     case 'w':           /* File is writeable? */
       return (sh_eaccess (arg, W_OK) == 0);
     case 'x':           /* File is executable? */
       return (sh_eaccess (arg, X_OK) == 0);
     case 'O':           /* File is owned by you? */
       return (sh_stat (arg, &stat_buf) == 0 &&
           (uid_t) current_user.euid == (uid_t) stat_buf.st_uid);
     case 'G':           /* File is owned by your group? */
       return (sh_stat (arg, &stat_buf) == 0 &&
           (gid_t) current_user.egid == (gid_t) stat_buf.st_gid);
     case 'N':
       if (sh_stat (arg, &stat_buf) < 0)
     return (FALSE);
       atime = get_stat_atime (&stat_buf);
       mtime = get_stat_mtime (&stat_buf);
       return (timespec_cmp (mtime, atime) > 0);
     case 'f':           /* File is a file? */
       if (sh_stat (arg, &stat_buf) < 0)
     return (FALSE);
       /* -f is true if the given file exists and is a regular file. */
 #if defined (S_IFMT)
       return (S_ISREG (stat_buf.st_mode) || (stat_buf.st_mode & S_IFMT) == 0);
 #else
       return (S_ISREG (stat_buf.st_mode));
 #endif /* !S_IFMT */
     case 'd':           /* File is a directory? */
       return (sh_stat (arg, &stat_buf) == 0 && (S_ISDIR (stat_buf.st_mode)));
     case 's':           /* File has something in it? */
       return (sh_stat (arg, &stat_buf) == 0 && stat_buf.st_size > (off_t) 0);
     case 'S':           /* File is a socket? */
 #if !defined (S_ISSOCK)
       return (FALSE);
 #else
       return (sh_stat (arg, &stat_buf) == 0 && S_ISSOCK (stat_buf.st_mode));
 #endif /* S_ISSOCK */
     case 'c':           /* File is character special? */
       return (sh_stat (arg, &stat_buf) == 0 && S_ISCHR (stat_buf.st_mode));
     case 'b':           /* File is block special? */
       return (sh_stat (arg, &stat_buf) == 0 && S_ISBLK (stat_buf.st_mode));
     case 'p':           /* File is a named pipe? */
 #ifndef S_ISFIFO
       return (FALSE);
 #else
       return (sh_stat (arg, &stat_buf) == 0 && S_ISFIFO (stat_buf.st_mode));
 #endif /* S_ISFIFO */
     case 'L':           /* Same as -h  */
     case 'h':           /* File is a symbolic link? */
 #if !defined (S_ISLNK) || !defined (HAVE_LSTAT)
       return (FALSE);
 #else
       return ((arg[0] != '\0') &&
           (lstat (arg, &stat_buf) == 0) && S_ISLNK (stat_buf.st_mode));
 #endif /* S_IFLNK && HAVE_LSTAT */
     case 'u':           /* File is setuid? */
       return (sh_stat (arg, &stat_buf) == 0 && (stat_buf.st_mode & S_ISUID) != 0);
     case 'g':           /* File is setgid? */
       return (sh_stat (arg, &stat_buf) == 0 && (stat_buf.st_mode & S_ISGID) != 0);
     case 'k':           /* File has sticky bit set? */
 #if !defined (S_ISVTX)
       /* This is not Posix, and is not defined on some Posix systems. */
       return (FALSE);
 #else
       return (sh_stat (arg, &stat_buf) == 0 && (stat_buf.st_mode & S_ISVTX) != 0);
 #endif
     case 't':   /* File fd is a terminal? */
       if (legal_number (arg, &r) == 0)
     return (FALSE);
       return ((r == (int)r) && isatty ((int)r));
     case 'n':           /* True if arg has some length. */
       return (arg[0] != '\0');
     case 'z':           /* True if arg has no length. */
       return (arg[0] == '\0');
     case 'o':           /* True if option `arg' is set. */
       return (minus_o_option_value (arg) == 1);
     case 'v':
 #if defined (ARRAY_VARS)
       aflags = assoc_expand_once ? AV_NOEXPAND : 0;
       if (valid_array_reference (arg, aflags))
     {
       char *t;
       int ret;
       array_eltstate_t es;
       /* Let's assume that this has already been expanded once. */
       /* XXX - TAG:bash-5.2 fix with corresponding fix to execute_cmd.c:
          execute_cond_node() that passes TEST_ARRAYEXP in FLAGS */
       if (shell_compatibility_level > 51)
         /* Allow associative arrays to use `test -v array[@]' to look for
            a key named `@'. */
         aflags |= AV_ATSTARKEYS;    /* XXX */
       init_eltstate (&es);
       t = get_array_value (arg, aflags|AV_ALLOWALL, &es);
       ret = t ? TRUE : FALSE;
       if (es.subtype > 0)   /* subscript is * or @ */
         free (t);
       flush_eltstate (&es);
       return ret;
     }
       else if (legal_number (arg, &r))      /* -v n == is $n set? */
     return ((r >= 0 && r <= number_of_args()) ? TRUE : FALSE);
       v = find_variable (arg);
       if (v && invisible_p (v) == 0 && array_p (v))
     {
       char *t;
       /* [[ -v foo ]] == [[ -v foo[0] ]] */
       t = array_reference (array_cell (v), 0);
       return (t ? TRUE : FALSE);
     }
       else if (v && invisible_p (v) == 0 && assoc_p (v))
     {
       char *t;
       t = assoc_reference (assoc_cell (v), "0");
       return (t ? TRUE : FALSE);
     }
 #else
       v = find_variable (arg);
 #endif
       return (v && invisible_p (v) == 0 && var_isset (v) ? TRUE : FALSE);
     case 'R':
       v = find_variable_noref (arg);
       return ((v && invisible_p (v) == 0 && var_isset (v) && nameref_p (v)) ? TRUE : FALSE);
     }
   /* We can't actually get here, but this shuts up gcc. */
   return (FALSE);
 }
References array_cell, array_p, assoc_cell, assoc_p, atime, AV_ALLOWALL, AV_ATSTARKEYS, AV_NOEXPAND, current_user, user_info::egid, user_info::euid, FALSE, find_variable(), find_variable_noref(), free, get_stat_atime(), get_stat_mtime(), invisible_p, isatty(), legal_number(), lstat, mtime, nameref_p, number_of_args(), r, R_OK, ret, S_IFMT, S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISGID, S_ISLNK, S_ISREG, S_ISSOCK, S_ISUID, S_ISVTX, sh_eaccess(), sh_stat(), shell_compatibility_level, stat::st_gid, stat::st_mode, stat::st_size, stat::st_uid, element_state::subtype, t, timespec_cmp(), TRUE, var_isset, W_OK, and X_OK.
Referenced by unary_operator().
Variable Documentation
argc
int argc static
Definition at line 109 of file test.c.
Referenced by __dls3(), __getopt_long(), __getopt_long_core(), __libc_start_main(), _dlstart_c(), _start_c(), and(), cag_option_prepare(), cat_main(), doomgeneric_Create(), Execute::ELFObject::ELFObject(), execl(), execle(), execlp(), expr(), finfo_main(), getopt(), getopt_long(), getopt_long_only(), libc_start_main_stage2(), main(), or(), ParseConfig(), perl_main(), posixtest(), mlibc::set_startup_data(), sh_getopt(), stdcat(), term(), test_args(), test_command(), three_arguments(), and unary_operator().
argv
char** argv static
Definition at line 110 of file test.c.
Referenced by __dls3(), __execvpe(), __getopt_long(), __getopt_long_core(), __libc_start_main(), Tasking::__no_sanitize(), __no_sanitize(), _dlstart_c(), _start_c(), and(), binary_operator(), bind_args(), cag_option_prepare(), cat_main(), doomgeneric_Create(), Execute::ELFObject::ELFObject(), execl(), execle(), execlp(), execv(), execve(), execvp(), execvpe(), fexecve(), finfo_main(), getopt(), getopt_long(), getopt_long_only(), libc_start_main_stage2(), main(), make_builtin_argv(), or(), parse_long_options(), parse_shell_options(), ParseConfig(), perl_main(), permute(), posix_spawn(), posix_spawnp(), posixtest(), run_cmd(), mlibc::set_startup_data(), sh_getopt(), sh_getopt_restore_state(), Execute::Spawn(), SpawnInit(), stdcat(), mlibc::sys_execve(), targp_parse(), term(), test_args(), test_command(), three_arguments(), two_arguments(), and unary_operator().
errno
int errno extern
noeval
int noeval static
Definition at line 111 of file test.c.
Referenced by test_command().
pos
int pos static
Definition at line 108 of file test.c.
Referenced by __ftello(), __ftello_unlocked(), _rl_char_search_internal(), _rl_revert_all_lines(), and(), binary_operator(), cwk_path_change_basename(), cwk_path_change_extension(), cwk_path_change_segment(), cwk_path_get_relative(), cwk_path_join_and_normalize_multiple(), cwk_path_terminate_output(), do_glob(), std::list< T >::erase(), expand_tilde(), expr(), fgetpos(), fnwidth(), fsetpos(), ftell(), mlibc::get_nameserver(), getentropy(), glob(), history_search_pos(), history_set_pos(), std::list< T >::insert(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), mbschr(), multiboot_main(), noninc_dosearch(), noninc_search_from_pos(), or(), posixtest(), readahead(), rl_character_len(), rl_redisplay(), rl_vi_match(), rl_yank_nth_arg_internal(), saveg_read_pad(), saveg_write_pad(), setone(), strrchr(), sync_file_range(), term(), test_command(), three_arguments(), tre_copy_ast(), tre_tnfa_run_backtrack(), tre_tnfa_run_parallel(), two_arguments(), unary_operator(), vfscanf(), and vfwscanf().
test_error_return
int test_error_return static
Definition at line 102 of file test.c.
Referenced by test_command().
test_exit_buf
procenv_t test_exit_buf static
Definition at line 101 of file test.c.
Referenced by test_command().