Fennix: Userspace/apps/base/busybox/util-linux/volume_id/romfs.c File Reference
romfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct romfs_super
Macros
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_romfs (struct volume_id *id)
Variables
struct romfs_super PACKED
Data Structure Documentation
romfs_super
struct romfs_super
Definition at line 29 of file romfs.c.
Data Fields
uint32_t checksum
uint8_t magic[8]
uint8_t name[]
uint32_t size
Macro Definition Documentation
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_romfs()
int FAST_FUNC volume_id_probe_romfs (struct volume_id * id)
Definition at line 36 of file romfs.c.
 {
 #define off ((uint64_t)0)
     struct romfs_super *rfs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     rfs = volume_id_get_buffer(id, off, 0x200);
     if (rfs == NULL)
         return -1;
     if (memcmp(rfs->magic, "-rom1fs-", 4) == 0) {
         size_t len = strlen((char *)rfs->name);
         if (len) {
 //          volume_id_set_label_raw(id, rfs->name, len);
             volume_id_set_label_string(id, rfs->name, len);
         }
 //      volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
         IF_FEATURE_BLKID_TYPE(id->type = "romfs";)
         return 0;
     }
     return -1;
 }
References dbg, len, romfs_super::magic, memcmp(), romfs_super::name, NULL, off, strlen(), volume_id_get_buffer(), and volume_id_set_label_string().
Variable Documentation
PACKED
struct romfs_super PACKED