Fennix Lynx Bootloader: Memory64::PageMapLevel4 Union Reference
Memory64::PageMapLevel4 Union Reference
#include <memory.hpp>
Public Member Functions
void SetAddress (uintptr_t _Address)
Set PageDirectoryPointerTableEntryPtr address.
uintptr_t GetAddress ()
Get PageDirectoryPointerTableEntryPtr address.
Data Fields
struct {
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
uint64_t CacheDisable: 1
uint64_t Accessed: 1
uint64_t Available0: 1
uint64_t Reserved0: 1
uint64_t Available1: 4
uint64_t Address: 40
uint64_t Available2: 11
uint64_t ExecuteDisable: 1
};
uint64_t raw
Detailed Description
Definition at line 401 of file memory.hpp.
Member Function Documentation
GetAddress()
uintptr_t Memory64::PageMapLevel4::GetAddress () inline
Get PageDirectoryPointerTableEntryPtr address.
Definition at line 429 of file memory.hpp.
         {
             return (this->raw & 0x000FFFFFFFFFF000) >> 12;
         }
Referenced by Memory64::Virtual::Check(), Memory64::Virtual::GetPhysical(), Memory64::Virtual::Map(), and Memory64::Virtual::Unmap().
SetAddress()
void Memory64::PageMapLevel4::SetAddress (uintptr_t _Address) inline
Set PageDirectoryPointerTableEntryPtr address.
Definition at line 421 of file memory.hpp.
         {
             _Address &= 0x000000FFFFFFFFFF;
             this->raw &= 0xFFF0000000000FFF;
             this->raw |= (_Address << 12);
         }
Referenced by Memory64::Virtual::Map().
Field Documentation
struct { ... }
raw
uint64_t Memory64::PageMapLevel4::raw
Definition at line 418 of file memory.hpp.
Referenced by Memory64::Virtual::Check(), and Memory64::Virtual::Map().
The documentation for this union was generated from the following file:
Lynx/FennixLoader/include/memory.hpp