Fennix Userspace: Userspace/musl/src/unistd/setxid.c File Reference
setxid.c File Reference
#include <unistd.h>
#include <signal.h>
#include "syscall.h"
#include "libc.h"
Data Structures
struct ctx
Functions
static void do_setxid (void *p)
int __setxid (int nr, int id, int eid, int sid)
Data Structure Documentation
ctx
struct ctx
Definition at line 7 of file setgroups.c.
Data Fields
int amode
size_t count
int eid
int err
int fd
const char * filename
int id
unsigned long lim[2]
const gid_t * list
int nr
int p
int res
int ret
int sid
Function Documentation
__setxid()
int __setxid (int nr, int id, int eid, int sid)
Definition at line 27 of file setxid.c.
 {
     /* ret is initially nonzero so that failure of the first thread does not
      * trigger the safety kill above. */
     struct ctx c = { .nr = nr, .id = id, .eid = eid, .sid = sid, .ret = 1 };
     __synccall(do_setxid, &c);
     return __syscall_ret(c.ret);
 }
References __synccall(), __syscall_ret(), do_setxid(), ctx::eid, ctx::id, ctx::nr, ctx::ret, and ctx::sid.
Referenced by setegid(), seteuid(), setgid(), setregid(), setresgid(), setresuid(), setreuid(), and setuid().
do_setxid()
static void do_setxid (void * p) static
Definition at line 11 of file setxid.c.
 {
     struct ctx *c = p;
     if (c->ret<0) return;
     int ret = __syscall(c->nr, c->id, c->eid, c->sid);
     if (ret && !c->ret) {
         /* If one thread fails to set ids after another has already
          * succeeded, forcibly killing the process is the only safe
          * thing to do. State is inconsistent and dangerous. Use
          * SIGKILL because it is uncatchable. */
         __block_all_sigs(0);
         __syscall(SYS_kill, __syscall(SYS_getpid), SIGKILL);
     }
     c->ret = ret;
 }
References __block_all_sigs(), __syscall, ctx::eid, ctx::id, ctx::nr, p, ctx::ret, ctx::sid, and SIGKILL.
Referenced by __setxid().