Fennix: Userspace/musl/src/string/strdup.c File Reference
strdup.c File Reference
#include <stdlib.h>
#include <string.h>
Functions
char * strdup (const char *s)
Function Documentation
strdup()
char* strdup (const char * s)
Definition at line 4 of file strdup.c.
 {
     size_t l = strlen(s);
     char *d = malloc(l+1);
     if (!d) return NULL;
     return memcpy(d, s, l+1);
 }
References kmalloc, l, malloc, memcpy, NULL, s, strlen(), and strncpy().
Referenced by _nl_find_domain(), add_new_file(), add_new_symbol(), CheckDirectoryHasIWAD(), conf_read_simple(), D_FindWADByName(), file_lookup(), get_current_dir_name(), getcwd(), glob(), if(), M_GetSaveGameDir(), M_StringDuplicate(), main(), message__new(), mitos(), ParseLine(), process_includes(), realpath(), set_binding_values(), SetVariable(), sym_lookup(), sym_validate_range(), tempnam(), vasprintf(), wstrdup(), and xstrdup().