Fennix: Userspace/mlibc/options/linux/include/utmp.h File Reference
utmp.h File Reference
#include <abi-bits/pid_t.h>
#include <bits/posix/timeval.h>
#include <bits/types.h>
Data Structures
struct exit_status
struct utmp
struct lastlog
Macros
#define EMPTY 0
#define RUN_LVL 1
#define BOOT_TIME 2
#define NEW_TIME 3
#define OLD_TIME 4
#define INIT_PROCESS 5
#define LOGIN_PROCESS 6
#define USER_PROCESS 7
#define DEAD_PROCESS 8
#define ACCOUNTING 9
#define UT_LINESIZE 32
#define UT_NAMESIZE 32
#define UT_HOSTSIZE 256
#define ut_name ut_user
#define ut_time ut_tv.tv_sec
#define ut_xtime ut_tv.tv_sec
#define ut_addr ut_addr_v6[0]
Functions
void setutent (void)
struct utmp * getutent (void)
int getutent_r (struct utmp *, struct utmp **)
void endutent (void)
struct utmp * pututline (const struct utmp *)
struct utmp * getutline (const struct utmp *)
Data Structure Documentation
exit_status
struct exit_status
Definition at line 27 of file utmp.h.
Data Fields
short int e_exit
short int e_termination
utmp
struct utmp
Definition at line 32 of file utmp.h.
Data Fields
char __unused[20]
__mlibc_int32 ut_addr_v6[4]
struct exit_status ut_exit
char ut_host[UT_HOSTSIZE]
char ut_id[4]
char ut_line[UT_LINESIZE]
pid_t ut_pid
long ut_session
struct timeval ut_tv
short ut_type
char ut_user[UT_NAMESIZE]
lastlog
struct lastlog
Definition at line 46 of file utmp.h.
Data Fields
char ll_host[UT_HOSTSIZE]
char ll_line[UT_LINESIZE]
time_t ll_time
Macro Definition Documentation
ACCOUNTING
#define ACCOUNTING 9
Definition at line 21 of file utmp.h.
BOOT_TIME
#define BOOT_TIME 2
Definition at line 14 of file utmp.h.
DEAD_PROCESS
#define DEAD_PROCESS 8
Definition at line 20 of file utmp.h.
EMPTY
#define EMPTY 0
Definition at line 12 of file utmp.h.
INIT_PROCESS
#define INIT_PROCESS 5
Definition at line 17 of file utmp.h.
LOGIN_PROCESS
#define LOGIN_PROCESS 6
Definition at line 18 of file utmp.h.
NEW_TIME
#define NEW_TIME 3
Definition at line 15 of file utmp.h.
OLD_TIME
#define OLD_TIME 4
Definition at line 16 of file utmp.h.
RUN_LVL
#define RUN_LVL 1
Definition at line 13 of file utmp.h.
USER_PROCESS
#define USER_PROCESS 7
Definition at line 19 of file utmp.h.
ut_addr
#define ut_addr ut_addr_v6[0]
Definition at line 58 of file utmp.h.
UT_HOSTSIZE
#define UT_HOSTSIZE 256
Definition at line 25 of file utmp.h.
UT_LINESIZE
#define UT_LINESIZE 32
Definition at line 23 of file utmp.h.
ut_name
#define ut_name ut_user
Definition at line 53 of file utmp.h.
UT_NAMESIZE
#define UT_NAMESIZE 32
Definition at line 24 of file utmp.h.
ut_time
#define ut_time ut_tv.tv_sec
Definition at line 55 of file utmp.h.
ut_xtime
#define ut_xtime ut_tv.tv_sec
Definition at line 57 of file utmp.h.
Function Documentation
endutent()
void endutent (void)
Definition at line 91 of file utmp-stubs.cpp.
                     {
     if(fd >= 0) {
         close(fd);
         fd = -1;
     }
 }
References close(), and fd.
getutent()
struct utmp* getutent (void)
Definition at line 52 of file utmp-stubs.cpp.
{
     struct utmp *result;
     static struct utmp *buf;
     if(buf == NULL) {
         buf = (struct utmp *)malloc(sizeof(struct utmp));
         if(buf == NULL) {
             return NULL;
         }
     }
     if(getutent_r(buf, &result) < 0) {
         return NULL;
     }
     return result;
 }
References buf, getutent_r(), malloc(), NULL, and mlibc::result.
getutent_r()
int getutent_r (struct utmp * buf, struct utmp ** res)
Definition at line 68 of file utmp-stubs.cpp.
{
     int saved_errno = errno;
     if(fd < 0) {
         setutent();
     }
     ssize_t bytes_read = read_last_entry();
     if(bytes_read <= 0) {
         if(bytes_read == 0) {
             errno = saved_errno;
             *res = NULL;
             return -1;
         }
     }
     memcpy(buf, &last_entry, sizeof(struct utmp));
     *res = buf;
     return 0;
 }
References buf, errno, fd, last_entry, memcpy, NULL, read_last_entry(), and setutent().
Referenced by getutent().
getutline()
struct utmp* getutline (const struct utmp *)
Definition at line 103 of file utmp-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pututline()
struct utmp* pututline (const struct utmp *)
Definition at line 98 of file utmp-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setutent()
void setutent (void)
Definition at line 24 of file utmp-stubs.cpp.
                     {
     if(fd < 0) {
         fd = open("/run/utmp", O_RDONLY | O_LARGEFILE | O_CLOEXEC);
         if(fd == -1) {
             return;
         }
     }
     lseek(fd, 0, SEEK_SET);
     offset = 0;
 }
References fd, lseek(), O_CLOEXEC, O_LARGEFILE, O_RDONLY, offset, open(), and SEEK_SET.
Referenced by getutent_r().