Fennix Userspace: SignalGuard Struct Reference
SignalGuard Struct Reference
#include <posix-pipe.hpp>
Public Member Functions
SignalGuard ()
SignalGuard (const SignalGuard &)=delete
~SignalGuard ()
SignalGuard & operator= (const SignalGuard &)=delete
Detailed Description
Definition at line 12 of file posix-pipe.hpp.
Constructor & Destructor Documentation
SignalGuard() [1/2]
SignalGuard::SignalGuard ()
Definition at line 51 of file entry.cpp.
{
     pthread_once(&has_cached_infos, &actuallyCacheInfos);
     if(!__mlibc_cached_thread_page)
         return;
     auto p = reinterpret_cast<unsigned int *>(__mlibc_cached_thread_page);
     if(!__mlibc_gsf_nesting)
         __atomic_store_n(p, 1, __ATOMIC_RELAXED);
     __mlibc_gsf_nesting++;
 }
References anonymous_namespace{entry.cpp}::__mlibc_cached_thread_page, anonymous_namespace{entry.cpp}::__mlibc_gsf_nesting, anonymous_namespace{entry.cpp}::actuallyCacheInfos(), anonymous_namespace{entry.cpp}::has_cached_infos, p, and pthread_once().
SignalGuard() [2/2]
SignalGuard::SignalGuard (const SignalGuard &) delete
~SignalGuard()
SignalGuard::~SignalGuard ()
Definition at line 61 of file entry.cpp.
{
     pthread_once(&has_cached_infos, &actuallyCacheInfos);
     if(!__mlibc_cached_thread_page)
         return;
     auto p = reinterpret_cast<unsigned int *>(__mlibc_cached_thread_page);
     __ensure(__mlibc_gsf_nesting > 0);
     __mlibc_gsf_nesting--;
     if(!__mlibc_gsf_nesting) {
         unsigned int result = __atomic_exchange_n(p, 0, __ATOMIC_RELAXED);
         if(result == 2) {
             HEL_CHECK(helSyscall0(kHelCallSuper + posix::superSigRaise));
         }else{
             __ensure(result == 1);
         }
     }
 }
References __ensure, anonymous_namespace{entry.cpp}::__mlibc_cached_thread_page, anonymous_namespace{entry.cpp}::__mlibc_gsf_nesting, anonymous_namespace{entry.cpp}::actuallyCacheInfos(), anonymous_namespace{entry.cpp}::has_cached_infos, p, and pthread_once().
Member Function Documentation
operator=()
SignalGuard& SignalGuard::operator= (const SignalGuard &) delete
The documentation for this struct was generated from the following files:
Userspace/mlibc/sysdeps/managarm/include/mlibc/posix-pipe.hpp
Userspace/mlibc/sysdeps/managarm/generic/entry.cpp