Fennix Userspace: Userspace/musl/src/stdio/vsscanf.c File Reference
vsscanf.c File Reference
#include "stdio_impl.h"
#include <string.h>
Functions
static size_t string_read (FILE *f, unsigned char *buf, size_t len)
int vsscanf (const char *restrict s, const char *restrict fmt, va_list ap)
weak_alias (vsscanf, __isoc99_vsscanf)
Function Documentation
string_read()
static size_t string_read (FILE * f, unsigned char * buf, size_t len) static
Definition at line 4 of file vsscanf.c.
 {
     char *src = f->cookie;
     size_t k = len+256;
     char *end = memchr(src, 0, k);
     if (end) k = end-src;
     if (k < len) len = k;
     memcpy(buf, src, len);
     f->rpos = (void *)(src+len);
     f->rend = (void *)(src+k);
     f->cookie = src+k;
     return len;
 }
References buf, _IO_FILE::cookie, end, f, k, memchr(), memcpy(), _IO_FILE::rend, _IO_FILE::rpos, and src.
Referenced by vsscanf().
vsscanf()
int vsscanf (const char *restrict s, const char *restrict fmt, va_list ap)
Definition at line 18 of file vsscanf.c.
 {
     FILE f = {
         .buf = (void *)s, .cookie = (void *)s,
         .read = string_read, .lock = -1
     };
     return vfscanf(&f, fmt, ap);
 }
References ap, _IO_FILE::buf, f, s, string_read(), and vfscanf().
weak_alias()
weak_alias (vsscanf , __isoc99_vsscanf)