Fennix Userspace: Userspace/musl/include/sys/eventfd.h File Reference
eventfd.h File Reference
#include <stdint.h>
#include <fcntl.h>
Macros
#define EFD_SEMAPHORE 1
#define EFD_CLOEXEC O_CLOEXEC
#define EFD_NONBLOCK O_NONBLOCK
Typedefs
typedef uint64_t eventfd_t
Functions
int eventfd (unsigned int, int)
int eventfd_read (int, eventfd_t *)
int eventfd_write (int, eventfd_t)
Macro Definition Documentation
EFD_CLOEXEC
#define EFD_CLOEXEC O_CLOEXEC
Definition at line 14 of file eventfd.h.
EFD_NONBLOCK
#define EFD_NONBLOCK O_NONBLOCK
Definition at line 15 of file eventfd.h.
EFD_SEMAPHORE
#define EFD_SEMAPHORE 1
Definition at line 13 of file eventfd.h.
Typedef Documentation
eventfd_t
typedef uint64_t eventfd_t
Definition at line 11 of file eventfd.h.
Function Documentation
eventfd()
int eventfd (unsigned int count, int flags)
Definition at line 6 of file eventfd.c.
 {
     int r = __syscall(SYS_eventfd2, count, flags);
 #ifdef SYS_eventfd
     if (r==-ENOSYS && !flags) r = __syscall(SYS_eventfd, count);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), count, ENOSYS, and flags.
eventfd_read()
int eventfd_read (int fd, eventfd_t * value)
Definition at line 15 of file eventfd.c.
 {
     return (sizeof(*value) == read(fd, value, sizeof(*value))) ? 0 : -1;
 }
References fd, read(), and value.
eventfd_write()
int eventfd_write (int fd, eventfd_t value)
Definition at line 20 of file eventfd.c.
 {
     return (sizeof(value) == write(fd, &value, sizeof(value))) ? 0 : -1;
 }
References fd, value, and write().