Fennix: Userspace/musl/arch/powerpc64/atomic_arch.h File Reference
atomic_arch.h File Reference
Macros
#define a_ll a_ll
#define a_sc a_sc
#define a_ll_p a_ll_p
#define a_sc_p a_sc_p
#define a_barrier a_barrier
#define a_pre_llsc a_barrier
#define a_post_llsc a_post_llsc
#define a_crash a_crash
#define a_clz_64 a_clz_64
Functions
static int a_ll (volatile int *p)
static int a_sc (volatile int *p, int v)
static void * a_ll_p (volatile void *p)
static int a_sc_p (volatile void *p, void *v)
static int a_clz_64 (uint64_t x)
Macro Definition Documentation
a_barrier
#define a_barrier a_barrier
Definition at line 37 of file atomic_arch.h.
a_clz_64
#define a_clz_64 a_clz_64
Definition at line 57 of file atomic_arch.h.
a_crash
#define a_crash a_crash
Definition at line 51 of file atomic_arch.h.
a_ll
#define a_ll a_ll
Definition at line 1 of file atomic_arch.h.
a_ll_p
#define a_ll_p a_ll_p
Definition at line 19 of file atomic_arch.h.
a_post_llsc
#define a_post_llsc a_post_llsc
Definition at line 45 of file atomic_arch.h.
a_pre_llsc
#define a_pre_llsc a_barrier
Definition at line 43 of file atomic_arch.h.
a_sc
#define a_sc a_sc
Definition at line 9 of file atomic_arch.h.
a_sc_p
#define a_sc_p a_sc_p
Definition at line 27 of file atomic_arch.h.
Function Documentation
a_clz_64()
static int a_clz_64 (uint64_t x) inline static
Definition at line 58 of file atomic_arch.h.
 {
     __asm__ ("cntlzd %0, %1" : "=r"(x) : "r"(x));
     return x;
 }
References __asm__(), and x.
a_ll()
static int a_ll (volatile int * p) inline static
Definition at line 2 of file atomic_arch.h.
 {
     int v;
     __asm__ __volatile__ ("lwarx %0, 0, %2" : "=r"(v) : "m"(*p), "r"(p));
     return v;
 }
References __asm__(), and p.
a_ll_p()
static void* a_ll_p (volatile void * p) inline static
Definition at line 20 of file atomic_arch.h.
 {
     void *v;
     __asm__ __volatile__ ("ldarx %0, 0, %2" : "=r"(v) : "m"(*(void *volatile *)p), "r"(p));
     return v;
 }
References __asm__(), and p.
a_sc()
static int a_sc (volatile int * p, int v) inline static
Definition at line 10 of file atomic_arch.h.
 {
     int r;
     __asm__ __volatile__ (
         "stwcx. %2, 0, %3 ; mfcr %0"
         : "=r"(r), "=m"(*p) : "r"(v), "r"(p) : "memory", "cc");
     return r & 0x20000000; /* "bit 2" of "cr0" (backwards bit order) */
 }
References __asm__(), and p.
a_sc_p()
static int a_sc_p (volatile void * p, void * v) inline static
Definition at line 28 of file atomic_arch.h.
 {
     int r;
     __asm__ __volatile__ (
         "stdcx. %2, 0, %3 ; mfcr %0"
         : "=r"(r), "=m"(*(void *volatile *)p) : "r"(v), "r"(p) : "memory", "cc");
     return r & 0x20000000; /* "bit 2" of "cr0" (backwards bit order) */
 }
References __asm__(), and p.