Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/d_event.h File Reference
d_event.h File Reference
#include "doomtype.h"
Data Structures
struct event_t
Enumerations
enum evtype_t {
ev_keydown , ev_keyup , ev_mouse , ev_joystick ,
ev_quit
}
enum buttoncode_t {
BT_ATTACK = 1 , BT_USE = 2 , BT_SPECIAL = 128 , BT_SPECIALMASK = 3 ,
BT_CHANGE = 4 , BT_WEAPONMASK = (8+16+32) , BT_WEAPONSHIFT = 3 , BTS_PAUSE = 1 ,
BTS_SAVEGAME = 2 , BTS_SAVEMASK = (4+8+16) , BTS_SAVESHIFT = 2
}
enum buttoncode2_t {
BT2_LOOKUP = 1 , BT2_LOOKDOWN = 2 , BT2_CENTERVIEW = 4 , BT2_INVUSE = 8 ,
BT2_INVDROP = 16 , BT2_JUMP = 32 , BT2_HEALTH = 128
}
Functions
void D_PostEvent (event_t *ev)
event_t * D_PopEvent (void)
Data Structure Documentation
event_t
struct event_t
Definition at line 42 of file d_event.h.
Data Fields
int data1
int data2
int data3
int data4
evtype_t type
Enumeration Type Documentation
buttoncode2_t
enum buttoncode2_t
Enumerator
BT2_LOOKUP
BT2_LOOKDOWN
BT2_CENTERVIEW
BT2_INVUSE
BT2_INVDROP
BT2_JUMP
BT2_HEALTH
Definition at line 106 of file d_event.h.
 {
     // Player view look up
     BT2_LOOKUP          = 1,
     // Player view look down
     BT2_LOOKDOWN        = 2,
     // Center player's view
     BT2_CENTERVIEW      = 4,
     // Use inventory item
     BT2_INVUSE          = 8,
     // Drop inventory item
     BT2_INVDROP         = 16,
     // Jump up and down
     BT2_JUMP            = 32,
     // Use medkit
     BT2_HEALTH          = 128,
 } buttoncode2_t;
buttoncode_t
enum buttoncode_t
Enumerator
BT_ATTACK
BT_USE
BT_SPECIAL
BT_SPECIALMASK
BT_CHANGE
BT_WEAPONMASK
BT_WEAPONSHIFT
BTS_PAUSE
BTS_SAVEGAME
BTS_SAVEMASK
BTS_SAVESHIFT
Definition at line 74 of file d_event.h.
 {
     // Press "Fire".
     BT_ATTACK       = 1,
     // Use button, to open doors, activate switches.
     BT_USE      = 2,
     // Flag: game events, not really buttons.
     BT_SPECIAL      = 128,
     BT_SPECIALMASK  = 3,
     // Flag, weapon change pending.
     // If true, the next 3 bits hold weapon num.
     BT_CHANGE       = 4,
     // The 3bit weapon mask and shift, convenience.
     BT_WEAPONMASK   = (8+16+32),
     BT_WEAPONSHIFT  = 3,
     // Pause the game.
     BTS_PAUSE       = 1,
     // Save the game at each console.
     BTS_SAVEGAME    = 2,
     // Savegame slot numbers
     //  occupy the second byte of buttons.
     BTS_SAVEMASK    = (4+8+16),
     BTS_SAVESHIFT   = 2,
 } buttoncode_t;
evtype_t
enum evtype_t
Enumerator
ev_keydown
ev_keyup
ev_mouse
ev_joystick
ev_quit
Definition at line 32 of file d_event.h.
 {
     ev_keydown,
     ev_keyup,
     ev_mouse,
     ev_joystick,
     ev_quit
 } evtype_t;
Function Documentation
D_PopEvent()
event_t* D_PopEvent (void)
Definition at line 43 of file d_event.c.
 {
     event_t *result;
     // No more events waiting.
     if (eventtail == eventhead)
     {
         return NULL;
     }
     result = &events[eventtail];
     // Advance to the next event in the queue.
     eventtail = (eventtail + 1) % MAXEVENTS;
     return result;
 }
References eventhead, events, eventtail, MAXEVENTS, and NULL.
Referenced by D_ProcessEvents().
D_PostEvent()
void D_PostEvent (event_t * ev)
Definition at line 35 of file d_event.c.
 {
     events[eventhead] = *ev;
     eventhead = (eventhead + 1) % MAXEVENTS;
 }
References eventhead, events, and MAXEVENTS.
Referenced by I_GetEvent(), and I_UpdateJoystick().