Fennix Userspace: Userspace/apps/base/busybox/coreutils/touch.c File Reference
touch.c File Reference
#include "libbb.h"
Macros
#define reference_file NULL
#define date_str NULL
#define timebuf ((struct timespec*)NULL)
Functions
int touch_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
date_str
#define date_str NULL
reference_file
#define reference_file NULL
timebuf
#define timebuf ((struct timespec*)NULL)
Function Documentation
touch_main()
int touch_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 76 of file touch.c.
 {
     int fd;
     int opts;
     smalluint status = EXIT_SUCCESS;
 #if ENABLE_FEATURE_TOUCH_SUSV3
     char *reference_file;
     char *date_str;
     /* timebuf[0] is atime, timebuf[1] is mtime */
     struct timespec timebuf[2];
 #else
 # define reference_file NULL
 # define date_str       NULL
 # define timebuf        ((struct timespec*)NULL)
 #endif
     enum {
         OPT_c = (1 << 0),
         OPT_h = (1 << 1),
         OPT_r = (1 << 2) * ENABLE_FEATURE_TOUCH_SUSV3,
         OPT_d = (1 << 3) * ENABLE_FEATURE_TOUCH_SUSV3,
         OPT_t = (1 << 4) * ENABLE_FEATURE_TOUCH_SUSV3,
         OPT_a = (1 << 5) * ENABLE_FEATURE_TOUCH_SUSV3,
         OPT_m = (1 << 6) * ENABLE_FEATURE_TOUCH_SUSV3,
     };
 #if ENABLE_LONG_OPTS
     static const char touch_longopts[] ALIGN1 =
         /* name, has_arg, val */
         "no-create\0"        No_argument       "c"
         "no-dereference\0"   No_argument       "h"
         IF_FEATURE_TOUCH_SUSV3("reference\0"        Required_argument "r")
         IF_FEATURE_TOUCH_SUSV3("date\0"             Required_argument "d")
     ;
 #endif
     /* -d and -t both set time. In coreutils,
      * accepted data format differs a bit between -d and -t.
      * We accept the same formats for both
      */
     opts = getopt32long(argv, "^"
         "ch"
         IF_FEATURE_TOUCH_SUSV3("r:d:t:am")
         /*ignored:*/ "f" IF_NOT_FEATURE_TOUCH_SUSV3("am")
         "\0" /* opt_complementary: */
         /* at least one arg: */ "-1"
         /* coreutils forbids -r and -t at once: */ IF_FEATURE_TOUCH_SUSV3(":r--t:t--r")
         /* but allows these combinations: "r--d:d--r:t--d:d--t" */
         , touch_longopts
 #if ENABLE_FEATURE_TOUCH_SUSV3
         , &reference_file
         , &date_str
         , &date_str
 #endif
     );
 #if ENABLE_FEATURE_TOUCH_SUSV3
     timebuf[0].tv_nsec = timebuf[1].tv_nsec = UTIME_NOW;
     if (opts & OPT_r) {
         struct stat stbuf;
         xstat(reference_file, &stbuf);
         timebuf[0].tv_sec = stbuf.st_atime;
         timebuf[1].tv_sec = stbuf.st_mtime;
         timebuf[0].tv_nsec = stbuf.st_atim.tv_nsec;
         timebuf[1].tv_nsec = stbuf.st_mtim.tv_nsec;
     }
     if (opts & (OPT_d|OPT_t)) {
         struct tm tm_time;
         time_t t;
         int check_dst;
         //memset(&tm_time, 0, sizeof(tm_time));
         /* Better than memset: makes "HH:MM" dates meaningful */
         time(&t);
         localtime_r(&t, &tm_time);
         check_dst = parse_datestr(date_str, &tm_time);
         /* Correct any day of week and day of year etc. fields */
         if (check_dst)
             tm_time.tm_isdst = -1;  /* recheck dst unless date is UTC */
         t = validate_tm_time(date_str, &tm_time);
         timebuf[1].tv_sec = timebuf[0].tv_sec = t;
         timebuf[1].tv_nsec = timebuf[0].tv_nsec = 0;
     }
     /* If both -a and -m specified, both times should be set.
      * IOW: set OMIT only if one, not both, of them is given!
      */
     if ((opts & (OPT_a|OPT_m)) == OPT_a)
         timebuf[1].tv_nsec = UTIME_OMIT;
     if ((opts & (OPT_a|OPT_m)) == OPT_m)
         timebuf[0].tv_nsec = UTIME_OMIT;
 #endif
     argv += optind;
     do {
         int result = utimensat(AT_FDCWD, *argv, timebuf,
                 (opts & OPT_h) ? AT_SYMLINK_NOFOLLOW : 0);
         if (result != 0) {
             if (errno == ENOENT) { /* no such file? */
                 if (opts & OPT_c) {
                     /* Creation is disabled, so ignore */
                     continue;
                 }
                 /* Try to create the file */
                 fd = open(*argv, O_RDWR | O_CREAT, 0666);
                 if (fd >= 0) {
                     if (opts & (OPT_r|OPT_d|OPT_t))
                         futimens(fd, timebuf);
                     xclose(fd);
                     continue;
                 }
             }
             status = EXIT_FAILURE;
             bb_simple_perror_msg(*argv);
         }
     } while (*++argv);
     return status;
 }
References ALIGN1, argv, AT_FDCWD, AT_SYMLINK_NOFOLLOW, bb_simple_perror_msg(), date_str, ENOENT, errno, EXIT_FAILURE, EXIT_SUCCESS, fd, futimens(), getopt32long, No_argument, O_CREAT, O_RDWR, open(), OPT_a, OPT_c, OPT_d, OPT_h, OPT_m, OPT_r, OPT_t, optind, parse_datestr(), reference_file, Required_argument, stat::st_atim, stat::st_mtim, status, t, time(), timebuf, tm::tm_isdst, timespec::tv_nsec, UTIME_NOW, UTIME_OMIT, utimensat(), validate_tm_time(), xclose(), and xstat().