Fennix: Userspace/apps/base/busybox/loginutils/add-remove-shell.c File Reference
add-remove-shell.c File Reference
#include "libbb.h"
Macros
#define SHELLS_FILE "/etc/shells"
#define REMOVE_SHELL (ENABLE_REMOVE_SHELL && (!ENABLE_ADD_SHELL || applet_name[0] == 'r'))
#define ADD_SHELL (ENABLE_ADD_SHELL && (!ENABLE_REMOVE_SHELL || applet_name[0] == 'a'))
#define dont_add ((char*)(uintptr_t)1)
Functions
int add_remove_shell_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
ADD_SHELL
#define ADD_SHELL (ENABLE_ADD_SHELL && (!ENABLE_REMOVE_SHELL || applet_name[0] == 'a'))
Definition at line 44 of file add-remove-shell.c.
dont_add
#define dont_add ((char*)(uintptr_t)1)
Definition at line 46 of file add-remove-shell.c.
REMOVE_SHELL
#define REMOVE_SHELL (ENABLE_REMOVE_SHELL && (!ENABLE_ADD_SHELL || applet_name[0] == 'r'))
Definition at line 43 of file add-remove-shell.c.
SHELLS_FILE
#define SHELLS_FILE "/etc/shells"
Definition at line 41 of file add-remove-shell.c.
Function Documentation
add_remove_shell_main()
int add_remove_shell_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 49 of file add-remove-shell.c.
 {
     FILE *orig_fp;
     char *orig_fn;
     char *new_fn;
     struct stat sb;
     sb.st_mode = 0666;
     argv++;
     orig_fn = xmalloc_follow_symlinks(SHELLS_FILE);
     if (!orig_fn)
         return EXIT_FAILURE;
     orig_fp = fopen_for_read(orig_fn);
     if (orig_fp)
         xfstat(fileno(orig_fp), &sb, orig_fn);
     new_fn = xasprintf("%s.tmp", orig_fn);
     /*
      * O_TRUNC or O_EXCL? At the first glance, O_EXCL looks better,
      * since it prevents races. But: (1) it requires a retry loop,
      * (2) if /etc/shells.tmp is *stale*, then retry loop
      * with O_EXCL will never succeed - it should have a timeout,
      * after which it should revert to O_TRUNC.
      * For now, I settle for O_TRUNC instead.
      */
     xmove_fd(xopen3(new_fn, O_WRONLY | O_CREAT | O_TRUNC, sb.st_mode), STDOUT_FILENO);
     /* TODO?
     xfchown(STDOUT_FILENO, sb.st_uid, sb.st_gid);
     */
     if (orig_fp) {
         /* Copy old file, possibly skipping removed shell names */
         char *line;
         while ((line = xmalloc_fgetline(orig_fp)) != NULL) {
             char **cpp = argv;
             while (*cpp) {
                 if (*cpp != dont_add && strcmp(*cpp, line) == 0) {
                     /* Old file has this shell name */
                     if (REMOVE_SHELL) {
                         /* we are remove-shell */
                         /* delete this name by not copying it */
                         goto next_line;
                     }
                     /* we are add-shell */
                     /* mark this name as "do not add" */
                     *cpp = dont_add;
                 }
                 cpp++;
             }
             /* copy shell name from old to new file */
             puts(line);
  next_line:
             free(line);
         }
         if (ENABLE_FEATURE_CLEAN_UP)
             fclose(orig_fp);
     }
     if (ADD_SHELL) {
         char **cpp = argv;
         while (*cpp) {
             if (*cpp != dont_add)
                 puts(*cpp);
             cpp++;
         }
     }
     /* Ensure we wrote out everything */
     if (fclose(stdout) != 0) {
         xunlink(new_fn);
         bb_perror_msg_and_die("%s: write error", new_fn);
     }
     /* Small hole: if rename fails, /etc/shells.tmp is not removed */
     xrename(new_fn, orig_fn);
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(orig_fn);
         free(new_fn);
     }
     return EXIT_SUCCESS;
 }
References ADD_SHELL, argv, bb_perror_msg_and_die(), dont_add, EXIT_FAILURE, EXIT_SUCCESS, fclose(), fileno(), fopen_for_read(), free, line, next_line(), NULL, O_CREAT, O_TRUNC, O_WRONLY, puts(), REMOVE_SHELL, SHELLS_FILE, stat::st_mode, stdout, STDOUT_FILENO, strcmp, xasprintf(), xfstat(), xmalloc_fgetline(), xmalloc_follow_symlinks(), xmove_fd(), xopen3(), xrename(), and xunlink().