Fennix: Userspace/apps/base/busybox/scripts/basic/fixdep.c File Reference
fixdep.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <limits.h>
#include <ctype.h>
#include <arpa/inet.h>
Functions
void usage (void)
void print_cmdline (void)
void grow_config (int len)
int is_defined_config (const char *name, int len)
void define_config (const char *name, int len)
void clear_config (void)
void use_config (char *m, int slen)
void parse_config_file (char *map, size_t len)
int strrcmp (char *s, char *sub)
void do_config_file (char *filename)
void parse_dep_file (void *map, size_t len)
void print_deps (void)
void traps (void)
int main (int argc, char **argv)
Variables
char * target
char * depfile
char * cmdline
char * str_config = NULL
int size_config = 0
int len_config = 0
Function Documentation
clear_config()
void clear_config (void)
Definition at line 196 of file fixdep.c.
 {
     len_config = 0;
     define_config("", 0);
 }
References define_config(), and len_config.
Referenced by parse_dep_file().
define_config()
void define_config (const char * name, int len)
Definition at line 184 of file fixdep.c.
 {
     grow_config(len + 1);
     memcpy(str_config+len_config, name, len);
     len_config += len;
     str_config[len_config++] = '\n';
 }
References grow_config(), len, len_config, memcpy, and str_config.
Referenced by clear_config(), and use_config().
do_config_file()
void do_config_file (char * filename)
Definition at line 283 of file fixdep.c.
 {
     struct stat st;
     int fd;
     void *map;
     fd = open(filename, O_RDONLY);
     if (fd < 0) {
         fprintf(stderr, "fixdep: ");
         perror(filename);
         exit(2);
     }
     fstat(fd, &st);
     if (st.st_size == 0) {
         close(fd);
         return;
     }
     map = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
     if ((long) map == -1) {
         perror("fixdep: mmap");
         close(fd);
         return;
     }
     parse_config_file(map, st.st_size);
     munmap(map, st.st_size);
     close(fd);
 }
References close(), exit(), fd, filename, fprintf(), fstat(), map, MAP_PRIVATE, mmap(), munmap(), NULL, O_RDONLY, open(), parse_config_file(), perror(), PROT_READ, and stderr.
Referenced by parse_dep_file().
grow_config()
void grow_config (int len)
Definition at line 152 of file fixdep.c.
 {
     while (len_config + len > size_config) {
         if (size_config == 0)
             size_config = 2048;
         str_config = realloc(str_config, size_config *= 2);
         if (str_config == NULL)
             { perror("fixdep:malloc"); exit(1); }
     }
 }
References exit(), len, len_config, NULL, perror(), realloc, size_config, and str_config.
Referenced by define_config().
is_defined_config()
int is_defined_config (const char * name, int len)
Definition at line 168 of file fixdep.c.
 {
     const char * pconfig;
     const char * plast = str_config + len_config - len;
     for ( pconfig = str_config + 1; pconfig < plast; pconfig++ ) {
         if (pconfig[ -1] == '\n'
         &&  pconfig[len] == '\n'
         &&  !memcmp(pconfig, name, len))
             return 1;
     }
     return 0;
 }
References len, len_config, memcmp(), and str_config.
Referenced by use_config().
main()
int main (int argc , char ** argv)
Definition at line 399 of file fixdep.c.
 {
     traps();
     if (argc != 4)
         usage();
     depfile = argv[1];
     target = argv[2];
     cmdline = argv[3];
     print_cmdline();
     print_deps();
     return 0;
 }
References argc, argv, cmdline, depfile, print_cmdline(), print_deps(), target, traps(), and usage().
parse_config_file()
void parse_config_file (char * map, size_t len)
Definition at line 226 of file fixdep.c.
 {
     /* modified for bbox */
     unsigned char *end_3 = (unsigned char *)map + len - 3; /* 3 == length of "IF_" */
     unsigned char *end_7 = (unsigned char *)map + len - 7;
     unsigned char *p = (unsigned char *)map;
     unsigned char *q;
     int off;
     for (; p <= end_3; p++) {
         /* Find next identifier's beginning */
         if (!(isalnum(*p) || *p == '_'))
             continue;
         /* Check it */
         if (p < end_7 && p[6] == '_') {
             if (!memcmp(p, "CONFIG", 6)) goto conf7;
             if (!memcmp(p, "ENABLE", 6)) goto conf7;
             if (!memcmp(p, "IF_NOT", 6)) goto conf7;
         }
         /* we have at least 3 chars because of p <= end_3 */
         /*if (!memcmp(p, "IF_", 3)) ...*/
         if (p[0] == 'I' && p[1] == 'F' && p[2] == '_') {
             off = 3;
             goto conf;
         }
         /* This identifier is not interesting, skip it */
         while (p <= end_3 && (isalnum(*p) || *p == '_'))
             p++;
         continue;
     conf7:  off = 7;
     conf:
         p += off;
         for (q = p; q < end_3+3; q++) {
             if (!(isalnum(*q) || *q == '_'))
                 break;
         }
         if (q != p) {
             use_config((char*)p, q - p);
         }
     }
 }
References conf(), isalnum, len, map, memcmp(), off, p, and use_config().
Referenced by do_config_file(), and main().
parse_dep_file()
void parse_dep_file (void * map, size_t len)
Definition at line 314 of file fixdep.c.
 {
     char *m = map;
     char *end = m + len;
     char *p;
     char *s = alloca(len);
     p = memchr(m, ':', len);
     if (!p) {
         fprintf(stderr, "fixdep: parse error\n");
         exit(1);
     }
     memcpy(s, m, p-m); s[p-m] = 0;
     printf("deps_%s := \\\n", target);
     m = p+1;
     clear_config();
     while (m < end) {
         while (m < end && (*m == ' ' || *m == '\\' || *m == '\n' || *m == '\r'))
             m++;
         p = m;
         while (p < end && *p != ' ') p++;
         if (p == end) {
             do p--; while (!isalnum((unsigned char)*p));
             p++;
         }
         memcpy(s, m, p-m); s[p-m] = 0;
         if (strrcmp(s, "include/autoconf.h") &&
             strrcmp(s, "arch/um/include/uml-config.h") &&
             strrcmp(s, ".ver")) {
             printf("  %s \\\n", s);
             do_config_file(s);
         }
         m = p + 1;
     }
     printf("\n%s: $(deps_%s)\n\n", target, target);
     printf("$(deps_%s):\n", target);
 }
References alloca, clear_config(), do_config_file(), end, exit(), fprintf(), isalnum, len, map, memchr(), memcpy, p, printf, s, stderr, strrcmp(), and target.
Referenced by print_deps().
print_cmdline()
void print_cmdline (void)
Definition at line 139 of file fixdep.c.
 {
     printf("cmd_%s := %s\n\n", target, cmdline);
 }
References cmdline, printf, and target.
Referenced by main().
print_deps()
void print_deps (void)
Definition at line 354 of file fixdep.c.
 {
     struct stat st;
     int fd;
     void *map;
     fd = open(depfile, O_RDONLY);
     if (fd < 0) {
         fprintf(stderr, "fixdep: ");
         perror(depfile);
         exit(2);
     }
     fstat(fd, &st);
     if (st.st_size == 0) {
         fprintf(stderr,"fixdep: %s is empty\n",depfile);
         close(fd);
         return;
     }
     map = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
     if ((long) map == -1) {
         perror("fixdep: mmap");
         close(fd);
         return;
     }
     parse_dep_file(map, st.st_size);
     munmap(map, st.st_size);
     close(fd);
 }
References close(), depfile, exit(), fd, fprintf(), fstat(), map, MAP_PRIVATE, mmap(), munmap(), NULL, O_RDONLY, open(), parse_dep_file(), perror(), PROT_READ, and stderr.
Referenced by main().
strrcmp()
int strrcmp (char * s, char * sub)
Definition at line 272 of file fixdep.c.
 {
     int slen = strlen(s);
     int sublen = strlen(sub);
     if (sublen > slen)
         return 1;
     return memcmp(s + slen - sublen, sub, sublen);
 }
References memcmp(), s, strlen, and sub().
Referenced by parse_dep_file().
traps()
void traps (void)
Definition at line 386 of file fixdep.c.
 {
 /* bbox: not needed
     static char test[] __attribute__((aligned(sizeof(int)))) = "CONF";
     if (*(int *)test != INT_CONF) {
         fprintf(stderr, "fixdep: sizeof(int) != 4 or wrong endianess? %#x\n",
             *(int *)test);
         exit(2);
     }
 */
 }
Referenced by main().
usage()
void usage (void)
Definition at line 129 of file fixdep.c.
 {
     fprintf(stderr, "Usage: fixdep <depfile> <target> <cmdline>\n");
     exit(1);
 }
References exit(), fprintf(), and stderr.
Referenced by main().
use_config()
void use_config (char * m, int slen)
Definition at line 205 of file fixdep.c.
 {
     char *s = alloca(slen+1);
     char *p;
     if (is_defined_config(m, slen))
         return;
     define_config(m, slen);
     memcpy(s, m, slen); s[slen] = 0;
     for (p = s; p < s + slen; p++) {
         if (*p == '_')
             *p = '/';
         else
             *p = tolower((int)*p);
     }
     printf("    $(wildcard include/config/%s.h) \\\n", s);
 }
References alloca, define_config(), is_defined_config(), memcpy, p, printf, s, and tolower.
Referenced by parse_config_file().
Variable Documentation
cmdline
char* cmdline
Definition at line 127 of file fixdep.c.
Referenced by InitGameVersion(), main(), multiboot_parse(), and print_cmdline().
depfile
char* depfile
Definition at line 126 of file fixdep.c.
Referenced by main(), and print_deps().
len_config
int len_config = 0
Definition at line 146 of file fixdep.c.
Referenced by clear_config(), define_config(), grow_config(), and is_defined_config().
size_config
int size_config = 0
Definition at line 145 of file fixdep.c.
Referenced by grow_config().
str_config
char* str_config = NULL
Definition at line 144 of file fixdep.c.
Referenced by define_config(), grow_config(), is_defined_config(), and main().
target
char* target
Definition at line 125 of file fixdep.c.
Referenced by A_FatAttack1(), A_FatAttack2(), A_FatAttack3(), A_Fire(), action_compat(), create_links_from_list(), create_or_remember_link(), devmem_main(), download_one_url(), goto_lineno(), INET_setroute(), linux_kill(), linux_tgkill(), main(), mount_or_die(), P_DamageMobj(), P_KillMobj(), P_NoiseAlert(), parse_dep_file(), popmaildir_main(), print_cmdline(), rl_vi_char_search(), sub_append_string(), tls_xread_record(), and xmalloc_realpath_coreutils().