Fennix: Userspace/apps/base/busybox/util-linux/setpriv.c File Reference
setpriv.c File Reference
#include <sys/prctl.h>
#include "libbb.h"
Macros
#define PR_CAPBSET_READ 23
#define PR_SET_NO_NEW_PRIVS 38
#define PR_GET_NO_NEW_PRIVS 39
#define PR_CAP_AMBIENT 47
#define PR_CAP_AMBIENT_IS_SET 1
#define PR_CAP_AMBIENT_RAISE 2
#define PR_CAP_AMBIENT_LOWER 3
Enumerations
enum { OPTBIT_NNP , OPT_NNP = (1 << OPTBIT_NNP) }
Functions
int setpriv_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
PR_CAP_AMBIENT
#define PR_CAP_AMBIENT 47
Definition at line 107 of file setpriv.c.
PR_CAP_AMBIENT_IS_SET
#define PR_CAP_AMBIENT_IS_SET 1
Definition at line 108 of file setpriv.c.
PR_CAP_AMBIENT_LOWER
#define PR_CAP_AMBIENT_LOWER 3
Definition at line 110 of file setpriv.c.
PR_CAP_AMBIENT_RAISE
#define PR_CAP_AMBIENT_RAISE 2
Definition at line 109 of file setpriv.c.
PR_CAPBSET_READ
#define PR_CAPBSET_READ 23
Definition at line 95 of file setpriv.c.
PR_GET_NO_NEW_PRIVS
#define PR_GET_NO_NEW_PRIVS 39
Definition at line 103 of file setpriv.c.
PR_SET_NO_NEW_PRIVS
#define PR_SET_NO_NEW_PRIVS 38
Definition at line 99 of file setpriv.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTBIT_NNP
OPT_NNP
Definition at line 113 of file setpriv.c.
      {
     IF_FEATURE_SETPRIV_DUMP(OPTBIT_DUMP,)
     IF_FEATURE_SETPRIV_CAPABILITIES(OPTBIT_INH,)
     IF_FEATURE_SETPRIV_CAPABILITIES(OPTBIT_AMB,)
     OPTBIT_NNP,
     IF_FEATURE_SETPRIV_DUMP(OPT_DUMP = (1 << OPTBIT_DUMP),)
     IF_FEATURE_SETPRIV_CAPABILITIES(OPT_INH  = (1 << OPTBIT_INH),)
     IF_FEATURE_SETPRIV_CAPABILITIES(OPT_AMB  = (1 << OPTBIT_AMB),)
     OPT_NNP  = (1 << OPTBIT_NNP),
 };
Function Documentation
setpriv_main()
int setpriv_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 289 of file setpriv.c.
 {
     static const char setpriv_longopts[] ALIGN1 =
         IF_FEATURE_SETPRIV_DUMP(
         "dump\0"         No_argument        "d"
         )
         "nnp\0"          No_argument        "\xff"
         "no-new-privs\0" No_argument        "\xff"
         IF_FEATURE_SETPRIV_CAPABILITIES(
         "inh-caps\0"     Required_argument  "\xfe"
         "ambient-caps\0" Required_argument  "\xfd"
         )
         ;
     int opts;
     IF_FEATURE_SETPRIV_CAPABILITIES(char *inh_caps, *ambient_caps;)
     opts = getopt32long(argv, "+"
         IF_FEATURE_SETPRIV_DUMP("d")
         IF_FEATURE_SETPRIV_CAPABILITIES("\xfe:\xfd:"),
         setpriv_longopts
         IF_FEATURE_SETPRIV_CAPABILITIES(, &inh_caps, &ambient_caps)
     );
     argv += optind;
 #if ENABLE_FEATURE_SETPRIV_DUMP
     if (opts & OPT_DUMP) {
         if (argv[0] || (opts - OPT_DUMP) != 0)
             bb_show_usage();
         return dump();
     }
 #endif
     if (opts & OPT_NNP) {
         if (prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0))
             bb_perror_msg_and_die("prctl: %s", "SET_NO_NEW_PRIVS");
     }
 #if ENABLE_FEATURE_SETPRIV_CAPABILITIES
     if (opts & OPT_INH)
         set_inh_caps(inh_caps);
     if (opts & OPT_AMB)
         set_ambient_caps(ambient_caps);
 #endif
     if (!argv[0])
         bb_show_usage();
     BB_EXECVP_or_die(argv);
 }
References ALIGN1, argv, BB_EXECVP_or_die(), bb_perror_msg_and_die(), bb_show_usage(), dump(), getopt32long, No_argument, OPT_NNP, optind, PR_SET_NO_NEW_PRIVS, prctl(), and Required_argument.