Fennix Userspace: Userspace/apps/base/echo/echo.cpp File Reference
echo.cpp File Reference
Functions
static long syscall2 (int sc, long arg1, long arg2)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 11 of file echo.cpp.
 {
     // TODO: Change this to use stdout
     for (int i = 1; i < argc; i++)
     {
         for (int j = 0; argv[i][j]; j++)
             syscall2(1, argv[i][j], 0);
         syscall2(1, ' ', 0);
     }
     return 0;
 }
References i, j, and syscall2().
Referenced by M_SaveDefaultsAlternate().
syscall2()
static long syscall2 (int sc, long arg1, long arg2) inline static
Definition at line 1 of file echo.cpp.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(sc), "D"(arg1), "S"(arg2)
                          : "rcx", "r11", "memory");
     return ret;
 }
References arg1, arg2, and ret.
Referenced by FileOpen(), FreePages(), KrnlFreePages(), ld_load(), ld_main(), liballoc_free(), and main().