Fennix Userspace: Userspace/musl/src/thread/lock_ptc.c File Reference
lock_ptc.c File Reference
#include <pthread.h>
Functions
void __inhibit_ptc ()
void __acquire_ptc ()
void __release_ptc ()
Variables
static pthread_rwlock_t lock = PTHREAD_RWLOCK_INITIALIZER
Function Documentation
__acquire_ptc()
void __acquire_ptc (void)
Definition at line 10 of file lock_ptc.c.
 {
     pthread_rwlock_rdlock(&lock);
 }
References lock, and pthread_rwlock_rdlock().
Referenced by __pthread_create(), pthread_attr_init(), and pthread_getattr_default_np().
__inhibit_ptc()
void __inhibit_ptc (void)
Definition at line 5 of file lock_ptc.c.
 {
     pthread_rwlock_wrlock(&lock);
 }
References lock, and pthread_rwlock_wrlock().
Referenced by dlopen(), fork(), and pthread_setattr_default_np().
__release_ptc()
void __release_ptc (void)
Definition at line 15 of file lock_ptc.c.
 {
     pthread_rwlock_unlock(&lock);
 }
References lock, and pthread_rwlock_unlock().
Referenced by __pthread_create(), dlopen(), fork(), pthread_attr_init(), pthread_getattr_default_np(), and pthread_setattr_default_np().
Variable Documentation
lock
pthread_rwlock_t lock = PTHREAD_RWLOCK_INITIALIZER static
Definition at line 3 of file lock_ptc.c.
Referenced by __acquire_ptc(), __inhibit_ptc(), and __release_ptc().