Fennix: Userspace/apps/base/busybox/miscutils/watchdog.c File Reference
watchdog.c File Reference
#include "libbb.h"
#include <linux/types.h>
#include <linux/watchdog.h>
Macros
#define WDIOC_SETOPTIONS 0x5704
#define WDIOC_SETTIMEOUT 0x5706
#define WDIOC_GETTIMEOUT 0x5707
#define WDIOS_ENABLECARD 2
#define OPT_FOREGROUND (1 << 0)
#define OPT_STIMER (1 << 1)
#define OPT_HTIMER (1 << 2)
Functions
static void shutdown_watchdog (void)
static void shutdown_on_signal (int sig UNUSED_PARAM)
static void watchdog_open (const char *device)
int watchdog_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPT_FOREGROUND
#define OPT_FOREGROUND (1 << 0)
OPT_HTIMER
#define OPT_HTIMER (1 << 2)
OPT_STIMER
#define OPT_STIMER (1 << 1)
WDIOC_GETTIMEOUT
#define WDIOC_GETTIMEOUT 0x5707
Definition at line 62 of file watchdog.c.
WDIOC_SETOPTIONS
#define WDIOC_SETOPTIONS 0x5704
Definition at line 56 of file watchdog.c.
WDIOC_SETTIMEOUT
#define WDIOC_SETTIMEOUT 0x5706
Definition at line 59 of file watchdog.c.
WDIOS_ENABLECARD
#define WDIOS_ENABLECARD 2
Definition at line 65 of file watchdog.c.
Function Documentation
shutdown_on_signal()
static void shutdown_on_signal (int sig UNUSED_PARAM) static
Definition at line 75 of file watchdog.c.
 {
     remove_pidfile_std_path_and_ext("watchdog");
     shutdown_watchdog();
     _exit_SUCCESS();
 }
References _exit_SUCCESS(), remove_pidfile_std_path_and_ext(), and shutdown_watchdog().
Referenced by watchdog_main().
shutdown_watchdog()
static void shutdown_watchdog (void) static
Definition at line 68 of file watchdog.c.
 {
     static const char V = 'V';
     write(3, &V, 1);  /* Magic, see watchdog-api.txt in kernel */
     close(3);
 }
References close(), V, and write().
Referenced by shutdown_on_signal(), and watchdog_open().
watchdog_main()
int watchdog_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 101 of file watchdog.c.
 {
     static const int enable = WDIOS_ENABLECARD;
     static const struct suffix_mult suffixes[] ALIGN_SUFFIX = {
         { "ms", 1 },
         { "", 1000 },
         { "", 0 }
     };
     unsigned opts;
     unsigned stimer_duration; /* how often to restart */
     unsigned htimer_duration = 60000; /* reboots after N ms if not restarted */
     char *st_arg;
     char *ht_arg;
 #define OPT_FOREGROUND  (1 << 0)
 #define OPT_STIMER      (1 << 1)
 #define OPT_HTIMER      (1 << 2)
     opts = getopt32(argv, "^" "Ft:T:" "\0" "=1"/*must have exactly 1 arg*/,
                 &st_arg, &ht_arg
     );
     /* We need to daemonize *before* opening the watchdog as many drivers
      * will only allow one process at a time to do so.  Since daemonizing
      * is not perfect (child may run before parent finishes exiting), we
      * can't rely on parent exiting before us (let alone *cleanly* releasing
      * the watchdog fd -- something else that may not even be allowed).
      */
     if (!(opts & OPT_FOREGROUND))
         bb_daemonize_or_rexec(DAEMON_CHDIR_ROOT, argv);
     /* maybe bb_logenv_override(); here for LOGGING=syslog to work? */
     if (opts & OPT_HTIMER)
         htimer_duration = xatou_sfx(ht_arg, suffixes);
     stimer_duration = htimer_duration / 2;
     if (opts & OPT_STIMER)
         stimer_duration = xatou_sfx(st_arg, suffixes);
     bb_signals(BB_FATAL_SIGS, shutdown_on_signal);
     watchdog_open(argv[optind]);
     /* WDIOC_SETTIMEOUT takes seconds, not milliseconds */
     htimer_duration = htimer_duration / 1000;
     ioctl_or_warn(3, WDIOC_SETOPTIONS, (void*) &enable);
     ioctl_or_warn(3, WDIOC_SETTIMEOUT, &htimer_duration);
 #if 0
     ioctl_or_warn(3, WDIOC_GETTIMEOUT, &htimer_duration);
     printf("watchdog: SW timer is %dms, HW timer is %ds\n",
         stimer_duration, htimer_duration);
 #endif
     write_pidfile_std_path_and_ext("watchdog");
     while (1) {
         /*
          * Make sure we clear the counter before sleeping,
          * as the counter value is undefined at this point -- PFM
          */
         write(3, "", 1); /* write zero byte */
         msleep(stimer_duration);
     }
     return EXIT_SUCCESS; /* - not reached, but gcc 4.2.1 is too dumb! */
 }
References ALIGN_SUFFIX, argv, bb_daemonize_or_rexec, BB_FATAL_SIGS, bb_signals(), DAEMON_CHDIR_ROOT, EXIT_SUCCESS, getopt32(), ioctl_or_warn, msleep(), OPT_FOREGROUND, OPT_HTIMER, OPT_STIMER, optind, printf, shutdown_on_signal(), watchdog_open(), WDIOC_GETTIMEOUT, WDIOC_SETOPTIONS, WDIOC_SETTIMEOUT, WDIOS_ENABLECARD, write(), and write_pidfile_std_path_and_ext().
watchdog_open()
static void watchdog_open (const char * device) static
Definition at line 82 of file watchdog.c.
 {
     /* Use known fd # - avoid needing global 'int fd' */
     xmove_fd(xopen(device, O_WRONLY), 3);
 #if ENABLE_FEATURE_WATCHDOG_OPEN_TWICE
     /* If the watchdog driver can do something other than cause a reboot
      * on a timeout, then it's possible this program may be starting from
      * a state when the watchdog hadn't been previously stopped with
      * the magic write followed by a close.  In this case the driver may
      * not start properly, so always do the proper stop first just in case.
      */
     shutdown_watchdog();
     xmove_fd(xopen(device, O_WRONLY), 3);
 #endif
 }
References device, O_WRONLY, shutdown_watchdog(), xmove_fd(), and xopen().
Referenced by watchdog_main().