Fennix: Userspace/apps/base/busybox/include/volume_id.h File Reference
volume_id.h File Reference
Functions
char * get_devname_from_label (const char *spec)
char * get_devname_from_uuid (const char *spec)
void display_uuid_cache (int scan_devices)
int resolve_mount_spec (char **fsname)
int add_to_uuid_cache (const char *device)
Function Documentation
add_to_uuid_cache()
int add_to_uuid_cache (const char * device)
Definition at line 252 of file get_devname.c.
 {
     char *uuid = uuid; /* for compiler */
     char *label = label;
 #if ENABLE_FEATURE_BLKID_TYPE
     const char *type = type;
 #endif
     int fd;
     fd = open(device, O_RDONLY);
     if (fd < 0)
         return 0;
     /* get_label_uuid() closes fd in all cases (success & failure) */
     if (get_label_uuid(fd, &label, &uuid, &type) == 0) {
         /* uuidcache_addentry() takes ownership of all four params */
         uuidcache_addentry(xstrdup(device), /*ma, mi,*/ label, uuid, type);
         return 1;
     }
     return 0;
 }
References device, fd, get_label_uuid, label, O_RDONLY, open(), type, uuidcache_addentry, and xstrdup().
Referenced by blkid_main(), and uuidcache_check_device().
display_uuid_cache()
void display_uuid_cache (int scan_devices)
Definition at line 232 of file get_devname.c.
 {
     struct uuidCache_s *uc;
     uc = uuidcache_init(scan_devices);
     while (uc) {
         printf("%s:", uc->device);
         if (uc->label[0])
             printf(" LABEL=\"%s\"", uc->label);
         if (uc->uc_uuid[0])
             printf(" UUID=\"%s\"", uc->uc_uuid);
 #if ENABLE_FEATURE_BLKID_TYPE
     if (uc->type)
         printf(" TYPE=\"%s\"", uc->type);
 #endif
         bb_putchar('\n');
         uc = uc->next;
     }
 }
References bb_putchar(), uuidCache_s::device, uuidCache_s::label, uuidCache_s::next, printf, uuidCache_s::uc_uuid, and uuidcache_init().
Referenced by blkid_main().
get_devname_from_label()
char* get_devname_from_label (const char * spec)
Definition at line 277 of file get_devname.c.
 {
     struct uuidCache_s *uc;
     uc = uuidcache_init(/*scan_devices:*/ 1);
     while (uc) {
         if (uc->label[0] && strcmp(spec, uc->label) == 0) {
             return xstrdup(uc->device);
         }
         uc = uc->next;
     }
     return NULL;
 }
References uuidCache_s::device, uuidCache_s::label, uuidCache_s::next, NULL, strcmp, uuidcache_init(), and xstrdup().
Referenced by resolve_mount_spec().
get_devname_from_uuid()
char* get_devname_from_uuid (const char * spec)
Definition at line 291 of file get_devname.c.
 {
     struct uuidCache_s *uc;
     uc = uuidcache_init(/*scan_devices:*/ 1);
     while (uc) {
         /* case of hex numbers doesn't matter */
         if (strcasecmp(spec, uc->uc_uuid) == 0) {
             return xstrdup(uc->device);
         }
         uc = uc->next;
     }
     return NULL;
 }
References uuidCache_s::device, uuidCache_s::next, NULL, strcasecmp, uuidCache_s::uc_uuid, uuidcache_init(), and xstrdup().
Referenced by resolve_mount_spec().
resolve_mount_spec()
int resolve_mount_spec (char ** fsname)
Definition at line 306 of file get_devname.c.
 {
     char *tmp = *fsname;
     if (is_prefixed_with(*fsname, "UUID="))
         tmp = get_devname_from_uuid(*fsname + 5);
     else if (is_prefixed_with(*fsname, "LABEL="))
         tmp = get_devname_from_label(*fsname + 6);
     if (tmp == *fsname)
         return 0; /* no UUID= or LABEL= prefix found */
     if (tmp)
         *fsname = tmp;
     return 1;
 }
References get_devname_from_label(), get_devname_from_uuid(), and is_prefixed_with().