Fennix Userspace: Userspace/musl/src/stdio/__fopen_rb_ca.c File Reference
__fopen_rb_ca.c File Reference
#include "stdio_impl.h"
#include <fcntl.h>
#include <string.h>
Functions
FILE * __fopen_rb_ca (const char *filename, FILE *f, unsigned char *buf, size_t len)
Function Documentation
__fopen_rb_ca()
FILE* __fopen_rb_ca (const char * filename, FILE * f, unsigned char * buf, size_t len)
Definition at line 5 of file __fopen_rb_ca.c.
 {
     memset(f, 0, sizeof *f);
     f->fd = sys_open(filename, O_RDONLY|O_CLOEXEC);
     if (f->fd < 0) return 0;
     __syscall(SYS_fcntl, f->fd, F_SETFD, FD_CLOEXEC);
     f->flags = F_NOWR | F_PERM;
     f->buf = buf + UNGET;
     f->buf_size = len - UNGET;
     f->read = __stdio_read;
     f->seek = __stdio_seek;
     f->close = __stdio_close;
     f->lock = -1;
     return f;
 }
References __stdio_close(), __stdio_read(), __stdio_seek(), __syscall, buf, _IO_FILE::buf, _IO_FILE::buf_size, _IO_FILE::close, f, F_NOWR, F_PERM, F_SETFD, _IO_FILE::fd, FD_CLOEXEC, _IO_FILE::flags, _IO_FILE::lock, memset(), O_CLOEXEC, O_RDONLY, _IO_FILE::read, _IO_FILE::seek, sys_open, and UNGET.
Referenced by __get_resolv_conf(), __lookup_serv(), name_from_hosts(), reverse_hosts(), and reverse_services().