Fennix Userspace: Userspace/musl/src/unistd/dup2.c File Reference
dup2.c File Reference
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include "syscall.h"
Functions
int dup2 (int old, int new)
Function Documentation
dup2()
int dup2 (int old, int new)
Definition at line 6 of file dup2.c.
 {
     int r;
 #ifdef SYS_dup2
     while ((r=__syscall(SYS_dup2, old, new))==-EBUSY);
 #else
     if (old==new) {
         r = __syscall(SYS_fcntl, old, F_GETFD);
         if (r >= 0) return old;
     } else {
         while ((r=__syscall(SYS_dup3, old, new, 0))==-EBUSY);
     }
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), EBUSY, and F_GETFD.
Referenced by daemon(), do_wordexp(), and login_tty().