Fennix: Userspace/musl/include/sys/acct.h File Reference
acct.h File Reference
#include <features.h>
#include <time.h>
#include <stdint.h>
Data Structures
struct acct
struct acct_v3
Macros
#define ACCT_COMM 16
#define AFORK 1
#define ASU 2
#define ACORE 8
#define AXSIG 16
#define ACCT_BYTEORDER (128*(__BYTE_ORDER==__BIG_ENDIAN))
#define AHZ 100
Typedefs
typedef uint16_t comp_t
Functions
int acct (const char *)
Data Structure Documentation
acct
struct acct
Definition at line 16 of file acct.h.
Data Fields
uint32_t ac_btime
char ac_comm[ACCT_COMM+1]
comp_t ac_etime
uint32_t ac_exitcode
char ac_flag
uint16_t ac_gid
comp_t ac_io
comp_t ac_majflt
comp_t ac_mem
comp_t ac_minflt
char ac_pad[10]
comp_t ac_rw
comp_t ac_stime
comp_t ac_swaps
uint16_t ac_tty
uint16_t ac_uid
comp_t ac_utime
acct_v3
struct acct_v3
Definition at line 37 of file acct.h.
Data Fields
uint32_t ac_btime
char ac_comm[ACCT_COMM]
float ac_etime
uint32_t ac_exitcode
char ac_flag
uint32_t ac_gid
comp_t ac_io
comp_t ac_majflt
comp_t ac_mem
comp_t ac_minflt
uint32_t ac_pid
uint32_t ac_ppid
comp_t ac_rw
comp_t ac_stime
comp_t ac_swaps
uint16_t ac_tty
uint32_t ac_uid
comp_t ac_utime
char ac_version
Macro Definition Documentation
ACCT_BYTEORDER
#define ACCT_BYTEORDER (128*(__BYTE_ORDER==__BIG_ENDIAN))
Definition at line 63 of file acct.h.
ACCT_COMM
#define ACCT_COMM 16
Definition at line 12 of file acct.h.
ACORE
#define ACORE 8
Definition at line 61 of file acct.h.
AFORK
#define AFORK 1
Definition at line 59 of file acct.h.
AHZ
#define AHZ 100
Definition at line 64 of file acct.h.
ASU
#define ASU 2
Definition at line 60 of file acct.h.
AXSIG
#define AXSIG 16
Definition at line 62 of file acct.h.
Typedef Documentation
comp_t
typedef uint16_t comp_t
Definition at line 14 of file acct.h.
Function Documentation
acct()
int acct (const char * filename)
Definition at line 5 of file acct.c.
 {
     return syscall(SYS_acct, filename);
 }
References filename, and syscall().
Referenced by do_logging(), and finalize().