Fennix: Userspace/musl/src/stat/fstat.c File Reference
fstat.c File Reference
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include "syscall.h"
Macros
#define _BSD_SOURCE
Functions
int __fstat (int fd, struct stat *st)
weak_alias (__fstat, fstat)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file fstat.c.
Function Documentation
__fstat()
int __fstat (int fd, struct stat * st)
Definition at line 7 of file fstat.c.
 {
     if (fd<0) return __syscall_ret(-EBADF);
     return __fstatat(fd, "", st, AT_EMPTY_PATH);
 }
References __fstatat(), __syscall_ret(), EBADF, and fd.
Referenced by __map_file().
weak_alias()
weak_alias (__fstat , fstat)