Fennix: Userspace/musl/include/termios.h File Reference
termios.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/termios.h>
Macros
#define __NEED_pid_t
#define __NEED_struct_winsize
#define NCCS 32
Typedefs
typedef unsigned char cc_t
typedef unsigned int speed_t
typedef unsigned int tcflag_t
Functions
speed_t cfgetospeed (const struct termios *)
speed_t cfgetispeed (const struct termios *)
int cfsetospeed (struct termios *, speed_t)
int cfsetispeed (struct termios *, speed_t)
int tcgetattr (int, struct termios *)
int tcsetattr (int, int, const struct termios *)
int tcgetwinsize (int, struct winsize *)
int tcsetwinsize (int, const struct winsize *)
int tcsendbreak (int, int)
int tcdrain (int)
int tcflush (int, int)
int tcflow (int, int)
pid_t tcgetsid (int)
Macro Definition Documentation
__NEED_pid_t
#define __NEED_pid_t
Definition at line 10 of file termios.h.
__NEED_struct_winsize
#define __NEED_struct_winsize
Definition at line 11 of file termios.h.
NCCS
#define NCCS 32
Definition at line 19 of file termios.h.
Typedef Documentation
cc_t
typedef unsigned char cc_t
Definition at line 15 of file termios.h.
speed_t
typedef unsigned int speed_t
Definition at line 16 of file termios.h.
tcflag_t
typedef unsigned int tcflag_t
Definition at line 17 of file termios.h.
Function Documentation
cfgetispeed()
speed_t cfgetispeed (const struct termios * tio)
Definition at line 10 of file cfgetospeed.c.
 {
     return cfgetospeed(tio);
 }
References cfgetospeed(), and tio.
Referenced by display_speed(), and slattach_main().
cfgetospeed()
speed_t cfgetospeed (const struct termios * tio)
Definition at line 5 of file cfgetospeed.c.
 {
     return tio->c_cflag & CBAUD;
 }
References CBAUD, and tio.
Referenced by cfgetispeed(), display_speed(), and slattach_main().
cfsetispeed()
int cfsetispeed (struct termios * tio, speed_t speed)
Definition at line 17 of file cfsetospeed.c.
 {
     return speed ? cfsetospeed(tio, speed) : 0;
 }
References cfsetospeed(), and tio.
Referenced by restore_state_and_exit(), set_speed_or_die(), and slattach_main().
cfsetospeed()
int cfsetospeed (struct termios * tio, speed_t speed)
Definition at line 6 of file cfsetospeed.c.
 {
     if (speed & ~CBAUD) {
         errno = EINVAL;
         return -1;
     }
     tio->c_cflag &= ~CBAUD;
     tio->c_cflag |= speed;
     return 0;
 }
References CBAUD, EINVAL, errno, and tio.
Referenced by cfsetispeed(), restore_state_and_exit(), set_speed_or_die(), and slattach_main().
tcdrain()
int tcdrain (int fd)
Definition at line 5 of file tcdrain.c.
 {
     return syscall_cp(SYS_ioctl, fd, TCSBRK, 1);
 }
References fd, syscall_cp, and TCSBRK.
Referenced by getpass(), and init_tty_attrs().
tcflow()
int tcflow (int fd, int action)
Definition at line 4 of file tcflow.c.
 {
     return ioctl(fd, TCXONC, action);
 }
References fd, ioctl(), and TCXONC.
Referenced by rl_restart_output(), and rl_stop_output().
tcflush()
int tcflush (int fd, int queue)
Definition at line 4 of file tcflush.c.
 {
     return ioctl(fd, TCFLSH, queue);
 }
References fd, ioctl(), queue(), and TCFLSH.
Referenced by bb_ask_noecho(), get_logname(), init_tty_attrs(), login_main(), and receive().
tcgetattr()
int tcgetattr (int fd, struct termios * tio)
Definition at line 4 of file tcgetattr.c.
 {
     if (ioctl(fd, TCGETS, tio))
         return -1;
     return 0;
 }
References fd, ioctl(), TCGETS, and tio.
Referenced by bb_ask_noecho(), chat_main(), get_termios_and_make_raw(), get_tty_state(), getpass(), getty_main(), login_main(), main(), make_new_session(), resize_main(), rx_main(), script_main(), set_new_line_discipline(), set_sane_term(), shell_builtin_read(), slattach_main(), start_shell_in_child(), stty_main(), telnet_main(), ttgetattr(), vlock_main(), and xget1().
tcgetsid()
pid_t tcgetsid (int fd)
Definition at line 4 of file tcgetsid.c.
 {
     int sid;
     if (ioctl(fd, TIOCGSID, &sid) < 0)
         return -1;
     return sid;
 }
References fd, ioctl(), and TIOCGSID.
Referenced by getty_main(), and sulogin_main().
tcgetwinsize()
int tcgetwinsize (int fd, struct winsize * wsz)
Definition at line 5 of file tcgetwinsize.c.
 {
     return syscall(SYS_ioctl, fd, TIOCGWINSZ, wsz);
 }
References fd, syscall(), and TIOCGWINSZ.
tcsendbreak()
int tcsendbreak (int fd, int dur)
Definition at line 4 of file tcsendbreak.c.
 {
     /* nonzero duration is implementation-defined, so ignore it */
     return ioctl(fd, TCSBRK, 0);
 }
References fd, ioctl(), and TCSBRK.
Referenced by chat_main(), and microcom_main().
tcsetattr()
int tcsetattr (int fd, int act, const struct termios * tio)
Definition at line 5 of file tcsetattr.c.
 {
     if (act < 0 || act > 2) {
         errno = EINVAL;
         return -1;
     }
     return ioctl(fd, TCSETS+act, tio);
 }
References act(), EINVAL, errno, fd, ioctl(), TCSETS, and tio.
Referenced by bb_ask_noecho(), chat_main(), cleanup(), conf_cleanup(), cookmode(), getch_nowait(), getpass(), main(), microcom_main(), onintr(), openpty(), process_line(), rawmode(), resize_main(), rx_main(), script_main(), set_new_line_discipline(), set_termios_to_raw(), set_tty_cooked(), set_tty_state(), shell_builtin_read(), stty_main(), tcsetattr_serial_or_warn(), tcsetattr_stdin_TCSANOW(), tcsetattr_tty_TCSANOW(), ttsetattr(), and xset1().
tcsetwinsize()
int tcsetwinsize (int fd, const struct winsize * wsz)
Definition at line 5 of file tcsetwinsize.c.
 {
     return syscall(SYS_ioctl, fd, TIOCSWINSZ, wsz);
 }
References fd, syscall(), and TIOCSWINSZ.