Fennix Userspace: Userspace/musl/src/network/inet_ntoa.c File Reference
inet_ntoa.c File Reference
#include <arpa/inet.h>
#include <stdio.h>
Functions
char * inet_ntoa (struct in_addr in)
Function Documentation
inet_ntoa()
char* inet_ntoa (struct in_addr in)
Definition at line 4 of file inet_ntoa.c.
 {
     static char buf[16];
     unsigned char *a = (void *)&in;
     snprintf(buf, sizeof buf, "%d.%d.%d.%d", a[0], a[1], a[2], a[3]);
     return buf;
 }
References buf, and snprintf().
Referenced by accept_builtin(), bb_displayroutes(), d6_read_interface(), dumpleases_main(), hostname_main(), ipcalc_main(), nip_to_a(), nobody_responds_to_arp(), packet4_ok(), perform_release(), recv_pack(), send_packet_verbose(), send_renew(), send_select(), udhcp_read_interface(), udhcpc_main(), and xconnect().