Fennix Userspace: Userspace/mlibc/tests/posix/wordexp.c File Reference
wordexp.c File Reference
#include <assert.h>
#include <limits.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pwd.h>
#include <unistd.h>
#include <wordexp.h>
Data Structures
struct we_test
struct wordexp_return_val
Functions
static const char * wordexp_return_stringify (int val, int *should_free)
int main ()
Variables
struct we_test test_cases []
struct wordexp_return_val wordexp_return_vals []
Data Structure Documentation
we_test
struct we_test
Definition at line 13 of file wordexp.c.
Data Fields
int expected_return
int flags
size_t wordc
const char * words
const char * wordv[16]
wordexp_return_val
struct wordexp_return_val
Definition at line 115 of file wordexp.c.
Data Fields
const char * string
int val
Function Documentation
main()
int main (void)
Definition at line 55 of file wordexp.c.
            {
     wordexp_t we;
     wordexp("$(pwd)", &we, 0);
     char *cwd = getcwd(NULL, 0);
     assert(!strcmp(cwd, we.we_wordv[0]));
     wordfree(&we);
     free(cwd);
     char *home;
     assert(asprintf(&home, "%s/.config", getenv("HOME")) != -1);
     wordexp("$HOME ~ ~/.config", &we, WRDE_REUSE);
     assert(!strcmp(getenv("HOME"), we.we_wordv[0]));
     assert(!strcmp(getenv("HOME"), we.we_wordv[1]));
     assert(!strcmp(home, we.we_wordv[2]));
     free(home);
     wordfree(&we);
     struct passwd *pw = getpwnam("root");
     assert(asprintf(&home, "%s/.config", pw->pw_dir) != -1);
     wordexp("~root ~root/.config", &we, WRDE_REUSE);
     assert(!strcmp(pw->pw_dir, we.we_wordv[0]));
     assert(!strcmp(home, we.we_wordv[1]));
     free(home);
     wordfree(&we);
     size_t i = 0;
     for(struct we_test *test = &test_cases[i]; test->expected_return != -1; test = &test_cases[++i]) {
         wordexp_t test_we;
         int should_free;
         const char *expected = wordexp_return_stringify(test->expected_return, &should_free);
         fprintf(stderr, "TESTCASE %zu: '%s' with flags %d expected to return %s\n", i, test->words, test->flags, expected);
         int test_ret = wordexp(test->words, &test_we, test->flags);
         if(test_ret != test->expected_return) {
             fprintf(stderr, "\twordexp() returned %s, but we expect %s\n", wordexp_return_stringify(test_ret, &should_free), wordexp_return_stringify(test->expected_return, &should_free));
         }
         assert(test_ret == test->expected_return);
         if(test_ret != 0)
             continue;
         assert(test_we.we_wordc == test->wordc);
         for(size_t j = 0; j < 16 && j < test->wordc; j++) {
             assert(test->wordv[j] && test_we.we_wordv[j]);
             assert(!strcmp(test->wordv[j], test_we.we_wordv[j]));
         }
         wordfree(&test_we);
         if (should_free)
             free((void *)expected);
     }
     exit(EXIT_SUCCESS);
 }
References asprintf(), assert, exit(), EXIT_SUCCESS, fprintf(), free, getcwd, getenv, getpwnam(), i, j, NULL, pw, passwd::pw_dir, stderr, strcmp, test, test_cases, wordexp_t::we_wordc, wordexp_t::we_wordv, wordexp(), wordexp_return_stringify(), wordfree(), and WRDE_REUSE.
wordexp_return_stringify()
static const char * wordexp_return_stringify (int val, int * should_free) static
Definition at line 127 of file wordexp.c.
{
     for(size_t i = 0; wordexp_return_vals[i].val != -1 || wordexp_return_vals[i].string; i++) {
         if(wordexp_return_vals[i].val == val) {
             *should_free = 0;
             return wordexp_return_vals[i].string;
         }
     }
     char *unknown;
     assert(asprintf(&unknown, "unknown return value %d", val) != -1);
     *should_free = 1;
     return unknown;
 }
References asprintf(), assert, i, wordexp_return_val::string, unknown, val, wordexp_return_val::val, and wordexp_return_vals.
Referenced by main().
Variable Documentation
test_cases
struct we_test test_cases[]
Referenced by main().
wordexp_return_vals
struct wordexp_return_val wordexp_return_vals[]
Initial value:
= {
    {0, "WRDE_SUCCESS"},
    {WRDE_BADCHAR, "WRDE_BADCHAR"},
    {WRDE_BADVAL, "WRDE_BADVAL"},
    {WRDE_CMDSUB, "WRDE_CMDSUB"},
    {WRDE_SYNTAX, "WRDE_SYNTAX"},
    {-1, NULL},
}
Referenced by wordexp_return_stringify().