Fennix Userspace: Userspace/apps/base/busybox/libbb/nuke_str.c File Reference
nuke_str.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC nuke_str (char *str)
Function Documentation
nuke_str()
void FAST_FUNC nuke_str (char * str)
Definition at line 13 of file nuke_str.c.
 {
     if (str) {
         while (*str)
             *str++ = 0;
         /* or: memset(str, 0, strlen(str)); - not as small as above */
     }
 }
References str.
Referenced by ask_and_check_password_extended(), bb_ask_noecho(), init_main(), new_password(), and string_checker().