Fennix Userspace: Userspace/apps/base/busybox/networking/libiproute/libnetlink.h File Reference
libnetlink.h File Reference
#include <linux/types.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
Data Structures
struct rtnl_handle
Macros
#define rtnl_close(rth) (close((rth)->fd))
#define rtnl_talk(rtnl, n, peer, groups, answer, junk, jarg) rtnl_talk(rtnl, n, answer)
Functions
void xrtnl_open (struct rtnl_handle *rth) FAST_FUNC
void xrtnl_wilddump_request (struct rtnl_handle *rth, int fam, int type) FAST_FUNC
int rtnl_dump_request (struct rtnl_handle *rth, int type, void *req, int len) FAST_FUNC
int xrtnl_dump_filter (struct rtnl_handle *rth, int(*filter)(const struct sockaddr_nl *, struct nlmsghdr *n, void *) FAST_FUNC, void *arg1) FAST_FUNC
int rtnl_talk (struct rtnl_handle *rtnl, struct nlmsghdr *n, pid_t peer, unsigned groups, struct nlmsghdr *answer, int(*junk)(struct sockaddr_nl *, struct nlmsghdr *n, void *), void *jarg) FAST_FUNC
int rtnl_send_check (struct rtnl_handle *rth, const void *buf, int len) FAST_FUNC
static ALWAYS_INLINE void rtnl_send (struct rtnl_handle *rth, const void *buf, int len)
int addattr32 (struct nlmsghdr *n, int maxlen, int type, uint32_t data) FAST_FUNC
int addattr_l (struct nlmsghdr *n, int maxlen, int type, void *data, int alen) FAST_FUNC
int rta_addattr32 (struct rtattr *rta, int maxlen, int type, uint32_t data) FAST_FUNC
int rta_addattr_l (struct rtattr *rta, int maxlen, int type, void *data, int alen) FAST_FUNC
void parse_rtattr (struct rtattr *tb[], int max, struct rtattr *rta, int len) FAST_FUNC
Data Structure Documentation
rtnl_handle
struct rtnl_handle
Definition at line 13 of file libnetlink.h.
Data Fields
uint32_t dump
int fd
struct sockaddr_nl local
struct sockaddr_nl peer
uint32_t seq
Macro Definition Documentation
rtnl_close
#define rtnl_close (rth) (close((rth)->fd))
Definition at line 22 of file libnetlink.h.
rtnl_talk
#define rtnl_talk (rtnl, n, peer, groups, answer, junk, jarg) rtnl_talk(rtnl, n, answer)
Definition at line 30 of file libnetlink.h.
Function Documentation
addattr32()
int addattr32 (struct nlmsghdr * n, int maxlen, int type, uint32_t data)
Definition at line 361 of file libnetlink.c.
 {
     int len = RTA_LENGTH(4);
     struct rtattr *rta;
     if ((int)(NLMSG_ALIGN(n->nlmsg_len + len)) > maxlen) {
         return -1;
     }
     rta = (struct rtattr*)(((char*)n) + NLMSG_ALIGN(n->nlmsg_len));
     rta->rta_type = type;
     rta->rta_len = len;
     move_to_unaligned32(RTA_DATA(rta), data);
     n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len + len);
     return 0;
 }
References move_to_unaligned32, n, RTA_DATA, rtattr::rta_len, rtattr::rta_type, and type.
Referenced by ipaddr_modify(), iproute_get(), iproute_modify(), and iprule_modify().
addattr_l()
int addattr_l (struct nlmsghdr * n, int maxlen, int type, void * data, int alen)
Definition at line 377 of file libnetlink.c.
 {
     int len = RTA_LENGTH(alen);
     struct rtattr *rta;
     if ((int)(NLMSG_ALIGN(n->nlmsg_len + len)) > maxlen) {
         return -1;
     }
     rta = (struct rtattr*)(((char*)n) + NLMSG_ALIGN(n->nlmsg_len));
     rta->rta_type = type;
     rta->rta_len = len;
     memcpy(RTA_DATA(rta), data, alen);
     n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len + len);
     return 0;
 }
References memcpy(), n, RTA_DATA, rtattr::rta_len, rtattr::rta_type, and type.
Referenced by do_add_or_delete(), do_set(), ipaddr_modify(), iproute_get(), iproute_modify(), iprule_modify(), set_master(), set_netns(), vlan_parse_opt(), and vrf_parse_opt().
parse_rtattr()
void parse_rtattr (struct rtattr * tb[], int max, struct rtattr * rta, int len)
Definition at line 426 of file libnetlink.c.
 {
     memset(tb, 0, (max + 1) * sizeof(tb[0]));
     while (RTA_OK(rta, len)) {
         if (rta->rta_type <= max) {
             tb[rta->rta_type] = rta;
         }
         rta = RTA_NEXT(rta, len);
     }
     if (len) {
         bb_error_msg("deficit %d, rta_len=%d!", len, rta->rta_len);
     }
 }
References bb_error_msg(), max, memset(), rtattr::rta_len, RTA_NEXT, RTA_OK, and rtattr::rta_type.
Referenced by ipaddr_list_or_flush(), iproute_get(), ll_remember_index(), print_addrinfo(), print_class(), print_linkinfo(), print_neigh(), print_qdisc(), print_route(), and print_rule().
rta_addattr32()
int rta_addattr32 (struct rtattr * rta, int maxlen, int type, uint32_t data)
Definition at line 393 of file libnetlink.c.
 {
     int len = RTA_LENGTH(4);
     struct rtattr *subrta;
     if (RTA_ALIGN(rta->rta_len + len) > maxlen) {
         return -1;
     }
     subrta = (struct rtattr*)(((char*)rta) + RTA_ALIGN(rta->rta_len));
     subrta->rta_type = type;
     subrta->rta_len = len;
     move_to_unaligned32(RTA_DATA(subrta), data);
     rta->rta_len = NLMSG_ALIGN(rta->rta_len + len);
     return 0;
 }
References move_to_unaligned32, RTA_DATA, rtattr::rta_len, rtattr::rta_type, and type.
Referenced by iproute_modify().
rta_addattr_l()
int rta_addattr_l (struct rtattr * rta, int maxlen, int type, void * data, int alen)
Definition at line 409 of file libnetlink.c.
 {
     struct rtattr *subrta;
     int len = RTA_LENGTH(alen);
     if (RTA_ALIGN(rta->rta_len + len) > maxlen) {
         return -1;
     }
     subrta = (struct rtattr*)(((char*)rta) + RTA_ALIGN(rta->rta_len));
     subrta->rta_type = type;
     subrta->rta_len = len;
     memcpy(RTA_DATA(subrta), data, alen);
     rta->rta_len = NLMSG_ALIGN(rta->rta_len + len);
     return 0;
 }
References memcpy(), RTA_DATA, rtattr::rta_len, rtattr::rta_type, and type.
rtnl_dump_request()
int rtnl_dump_request (struct rtnl_handle * rth, int type, void * req, int len)
Definition at line 92 of file libnetlink.c.
 {
     struct {
         struct nlmsghdr nlh;
         struct msghdr msg;
         struct sockaddr_nl nladdr;
     } s;
     struct iovec iov[2] = { { &s.nlh, sizeof(s.nlh) }, { req, len } };
     memset(&s, 0, sizeof(s));
     s.msg.msg_name = (void*)&s.nladdr;
     s.msg.msg_namelen = sizeof(s.nladdr);
     s.msg.msg_iov = iov;
     s.msg.msg_iovlen = 2;
     /*s.msg.msg_control = NULL; - already is */
     /*s.msg.msg_controllen = 0; - already is */
     /*s.msg.msg_flags = 0; - already is */
     s.nladdr.nl_family = AF_NETLINK;
     s.nlh.nlmsg_len = NLMSG_LENGTH(len);
     s.nlh.nlmsg_type = type;
     s.nlh.nlmsg_flags = NLM_F_ROOT|NLM_F_MATCH|NLM_F_REQUEST;
     /*s.nlh.nlmsg_pid = 0; - already is */
     s.nlh.nlmsg_seq = rth->dump = ++rth->seq;
     return sendmsg(rth->fd, &s.msg, 0);
 }
References AF_NETLINK, rtnl_handle::dump, rtnl_handle::fd, memset(), NLM_F_MATCH, NLM_F_REQUEST, NLM_F_ROOT, s, sendmsg(), rtnl_handle::seq, and type.
Referenced by ipneigh_list_or_flush(), and tc_main().
rtnl_send()
static ALWAYS_INLINE void rtnl_send (struct rtnl_handle * rth, const void * buf, int len) static
Definition at line 39 of file libnetlink.h.
 {
     // Used to be:
     //struct sockaddr_nl nladdr;
     //memset(&nladdr, 0, sizeof(nladdr));
     //nladdr.nl_family = AF_NETLINK;
     //return xsendto(rth->fd, buf, len, (struct sockaddr*)&nladdr, sizeof(nladdr));
     // iproute2-4.2.0 simplified the above to:
     //return send(rth->fd, buf, len, 0);
     // We are using even shorter:
     xwrite(rth->fd, buf, len);
     // and convert to void, inline.
 }
References buf, rtnl_handle::fd, and xwrite().
Referenced by xrtnl_wilddump_request().
rtnl_send_check()
int rtnl_send_check (struct rtnl_handle * rth, const void * buf, int len)
Definition at line 57 of file libnetlink.c.
 {
     struct nlmsghdr *h;
     int status;
     char resp[1024];
     status = write(rth->fd, buf, len);
     if (status < 0)
         return status;
     /* Check for immediate errors */
     status = recv(rth->fd, resp, sizeof(resp), MSG_DONTWAIT|MSG_PEEK);
     if (status < 0) {
         if (errno == EAGAIN) /* if no error, this happens */
             return 0;
         return -1;
     }
     for (h = (struct nlmsghdr *)resp;
         NLMSG_OK(h, status);
         h = NLMSG_NEXT(h, status)
     ) {
         if (h->nlmsg_type == NLMSG_ERROR) {
             struct nlmsgerr *err = (struct nlmsgerr*)NLMSG_DATA(h);
             if (h->nlmsg_len < NLMSG_LENGTH(sizeof(struct nlmsgerr)))
                 bb_simple_error_msg("ERROR truncated");
             else
                 errno = -err->error;
             return -1;
         }
     }
     return 0;
 }
References bb_simple_error_msg(), buf, EAGAIN, err(), errno, rtnl_handle::fd, h, MSG_DONTWAIT, MSG_PEEK, NLMSG_DATA, NLMSG_ERROR, NLMSG_NEXT, NLMSG_OK, recv(), status, and write().
Referenced by flush_update().
rtnl_talk()
int rtnl_talk (struct rtnl_handle * rtnl, struct nlmsghdr * n, pid_t peer, unsigned groups, struct nlmsghdr * answer, int(*)(struct sockaddr_nl *, struct nlmsghdr *n, void *) junk, void * jarg)
xrtnl_dump_filter()
int xrtnl_dump_filter (struct rtnl_handle * rth, int(*)(const struct sockaddr_nl *, struct nlmsghdr *n, void *) FAST_FUNC filter, void * arg1)
xrtnl_open()
void xrtnl_open (struct rtnl_handle * rth)
Definition at line 16 of file libnetlink.c.
 {
     memset(rth, 0, sizeof(*rth));
     rth->fd = xsocket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
     rth->local.nl_family = AF_NETLINK;
     /*rth->local.nl_groups = subscriptions;*/
     xbind(rth->fd, (struct sockaddr*)&rth->local, sizeof(rth->local));
     bb_getsockname(rth->fd, (struct sockaddr*)&rth->local, sizeof(rth->local));
 /* too much paranoia
     if (getsockname(rth->fd, (struct sockaddr*)&rth->local, &addr_len) < 0)
         bb_perror_msg_and_die("getsockname");
     if (addr_len != sizeof(rth->local))
         bb_error_msg_and_die("wrong address length %d", addr_len);
     if (rth->local.nl_family != AF_NETLINK)
         bb_error_msg_and_die("wrong address family %d", rth->local.nl_family);
 */
     rth->seq = time(NULL);
 }
References AF_NETLINK, bb_getsockname(), rtnl_handle::fd, rtnl_handle::local, memset(), NETLINK_ROUTE, NULL, rtnl_handle::seq, SOCK_RAW, time(), xbind(), and xsocket().
Referenced by do_add_or_delete(), ipaddr_list_or_flush(), ipaddr_modify(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), iprule_list(), iprule_modify(), set_master(), set_netns(), and tc_main().
xrtnl_wilddump_request()
void xrtnl_wilddump_request (struct rtnl_handle * rth, int fam, int type)
Definition at line 37 of file libnetlink.c.
 {
     struct {
         struct nlmsghdr nlh;
         struct rtgenmsg g;
     } req;
     req.nlh.nlmsg_len = sizeof(req);
     req.nlh.nlmsg_type = type;
     req.nlh.nlmsg_flags = NLM_F_ROOT|NLM_F_MATCH|NLM_F_REQUEST;
     req.nlh.nlmsg_pid = 0;
     req.nlh.nlmsg_seq = rth->dump = ++rth->seq;
     req.g.rtgen_family = family;
     rtnl_send(rth, (void*)&req, sizeof(req));
 }
References rtnl_handle::dump, g, NLM_F_MATCH, NLM_F_REQUEST, NLM_F_ROOT, rtnl_send(), rtnl_handle::seq, and type.
Referenced by ipaddr_list_or_flush(), ipneigh_list_or_flush(), iproute_list_or_flush(), iprule_list(), and ll_init_map().