Fennix: Userspace/musl/include/threads.h File Reference
threads.h File Reference
#include <features.h>
#include <time.h>
#include <bits/alltypes.h>
Macros
#define thread_local _Thread_local
#define __NEED_cnd_t
#define __NEED_mtx_t
#define TSS_DTOR_ITERATIONS 4
#define ONCE_FLAG_INIT 0
#define thrd_equal(A, B) ((A) == (B))
Typedefs
typedef struct __pthread * thrd_t
typedef int once_flag
typedef unsigned tss_t
typedef int(* thrd_start_t) (void *)
typedef void(* tss_dtor_t) (void *)
Enumerations
enum {
thrd_success = 0 , thrd_busy = 1 , thrd_error = 2 , thrd_nomem = 3 ,
thrd_timedout = 4
}
enum { mtx_plain = 0 , mtx_recursive = 1 , mtx_timed = 2 }
Functions
int thrd_create (thrd_t *, thrd_start_t, void *)
_Noreturn void thrd_exit (int)
int thrd_detach (thrd_t)
int thrd_join (thrd_t, int *)
int thrd_sleep (const struct timespec *, struct timespec *)
void thrd_yield (void)
thrd_t thrd_current (void)
int thrd_equal (thrd_t, thrd_t)
void call_once (once_flag *, void(*)(void))
int mtx_init (mtx_t *, int)
void mtx_destroy (mtx_t *)
int mtx_lock (mtx_t *)
int mtx_timedlock (mtx_t *__restrict, const struct timespec *__restrict)
int mtx_trylock (mtx_t *)
int mtx_unlock (mtx_t *)
int cnd_init (cnd_t *)
void cnd_destroy (cnd_t *)
int cnd_broadcast (cnd_t *)
int cnd_signal (cnd_t *)
int cnd_timedwait (cnd_t *__restrict, mtx_t *__restrict, const struct timespec *__restrict)
int cnd_wait (cnd_t *, mtx_t *)
int tss_create (tss_t *, tss_dtor_t)
void tss_delete (tss_t)
int tss_set (tss_t, void *)
void * tss_get (tss_t)
Macro Definition Documentation
__NEED_cnd_t
#define __NEED_cnd_t
Definition at line 20 of file threads.h.
__NEED_mtx_t
#define __NEED_mtx_t
Definition at line 21 of file threads.h.
ONCE_FLAG_INIT
#define ONCE_FLAG_INIT 0
Definition at line 41 of file threads.h.
thrd_equal
#define thrd_equal (A, B) ((A) == (B))
Definition at line 55 of file threads.h.
thread_local
#define thread_local _Thread_local
Definition at line 12 of file threads.h.
TSS_DTOR_ITERATIONS
#define TSS_DTOR_ITERATIONS 4
Definition at line 25 of file threads.h.
Typedef Documentation
once_flag
typedef int once_flag
Definition at line 15 of file threads.h.
thrd_start_t
typedef int(* thrd_start_t) (void *)
Definition at line 17 of file threads.h.
thrd_t
typedef struct __pthread* thrd_t
Definition at line 11 of file threads.h.
tss_dtor_t
typedef void(* tss_dtor_t) (void *)
Definition at line 18 of file threads.h.
tss_t
typedef unsigned tss_t
Definition at line 16 of file threads.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
thrd_success
thrd_busy
thrd_error
thrd_nomem
thrd_timedout
Definition at line 27 of file threads.h.
      {
     thrd_success  = 0,
     thrd_busy     = 1,
     thrd_error    = 2,
     thrd_nomem    = 3,
     thrd_timedout = 4,
 };
anonymous enum
anonymous enum
Enumerator
mtx_plain
mtx_recursive
mtx_timed
Definition at line 35 of file threads.h.
      {
     mtx_plain     = 0,
     mtx_recursive = 1,
     mtx_timed     = 2,
 };
Function Documentation
call_once()
void call_once (once_flag * flag, void(*)(void) func)
Definition at line 4 of file call_once.c.
 {
     __pthread_once(flag, func);
 }
References __pthread_once().
cnd_broadcast()
int cnd_broadcast (cnd_t * c)
Definition at line 4 of file cnd_broadcast.c.
 {
     /* This internal function never fails, and always returns zero,
      * which matches the value thrd_success is defined with. */
     return __private_cond_signal((pthread_cond_t *)c, -1);
 }
References __private_cond_signal(), and c.
cnd_destroy()
void cnd_destroy (cnd_t * c)
Definition at line 3 of file cnd_destroy.c.
 {
     /* For private cv this is a no-op */
 }
cnd_init()
int cnd_init (cnd_t * c)
Definition at line 3 of file cnd_init.c.
 {
     *c = (cnd_t){ 0 };
     return thrd_success;
 }
References c, and thrd_success.
cnd_signal()
int cnd_signal (cnd_t * c)
Definition at line 4 of file cnd_signal.c.
 {
     /* This internal function never fails, and always returns zero,
      * which matches the value thrd_success is defined with. */
     return __private_cond_signal((pthread_cond_t *)c, 1);
 }
References __private_cond_signal(), and c.
cnd_timedwait()
int cnd_timedwait (cnd_t * __restrict, mtx_t * __restrict, const struct timespec * __restrict)
Referenced by __cnd_timedwait_time32(), and cnd_wait().
cnd_wait()
int cnd_wait (cnd_t * c, mtx_t * m)
Definition at line 3 of file cnd_wait.c.
 {
     /* Calling cnd_timedwait with a null pointer is an extension.
      * It is convenient here to avoid duplication of the logic
      * for return values. */
     return cnd_timedwait(c, m, 0);
 }
References c, and cnd_timedwait().
mtx_destroy()
void mtx_destroy (mtx_t * mtx)
Definition at line 3 of file mtx_destroy.c.
 {
 }
mtx_init()
int mtx_init (mtx_t * m, int type)
Definition at line 4 of file mtx_init.c.
 {
     *m = (mtx_t){
         ._m_type = ((type&mtx_recursive) ? PTHREAD_MUTEX_RECURSIVE : PTHREAD_MUTEX_NORMAL),
     };
     return thrd_success;
 }
References mtx_recursive, PTHREAD_MUTEX_NORMAL, PTHREAD_MUTEX_RECURSIVE, thrd_success, and type.
mtx_lock()
int mtx_lock (mtx_t * m)
Definition at line 4 of file mtx_lock.c.
 {
     if (m->_m_type == PTHREAD_MUTEX_NORMAL && !a_cas(&m->_m_lock, 0, EBUSY))
         return thrd_success;
     /* Calling mtx_timedlock with a null pointer is an extension.
      * It is convenient, here to avoid duplication of the logic
      * for return values. */
     return mtx_timedlock(m, 0);
 }
References a_cas, EBUSY, mtx_timedlock(), PTHREAD_MUTEX_NORMAL, and thrd_success.
mtx_timedlock()
int mtx_timedlock (mtx_t * __restrict, const struct timespec * __restrict)
Referenced by __mtx_timedlock_time32(), and mtx_lock().
mtx_trylock()
int mtx_trylock (mtx_t * m)
Definition at line 4 of file mtx_trylock.c.
 {
     if (m->_m_type == PTHREAD_MUTEX_NORMAL)
         return (a_cas(&m->_m_lock, 0, EBUSY) & EBUSY) ? thrd_busy : thrd_success;
     int ret = __pthread_mutex_trylock((pthread_mutex_t *)m);
     switch (ret) {
     default:    return thrd_error;
     case 0:     return thrd_success;
     case EBUSY: return thrd_busy;
     }
 }
References __pthread_mutex_trylock(), a_cas, EBUSY, PTHREAD_MUTEX_NORMAL, thrd_busy, thrd_error, and thrd_success.
mtx_unlock()
int mtx_unlock (mtx_t * mtx)
Definition at line 4 of file mtx_unlock.c.
 {
     /* The only cases where pthread_mutex_unlock can return an
      * error are undefined behavior for C11 mtx_unlock, so we can
      * assume it does not return an error and simply tail call. */
     return __pthread_mutex_unlock((pthread_mutex_t *)mtx);
 }
References __pthread_mutex_unlock().
thrd_create()
int thrd_create (thrd_t * thr, thrd_start_t func, void * arg)
Definition at line 4 of file thrd_create.c.
 {
     int ret = __pthread_create(thr, __ATTRP_C11_THREAD, (void *(*)(void *))func, arg);
     switch (ret) {
     case 0:      return thrd_success;
     case EAGAIN: return thrd_nomem;
     default:     return thrd_error;
     }
 }
References __ATTRP_C11_THREAD, __pthread_create(), EAGAIN, thrd_error, thrd_nomem, and thrd_success.
thrd_current()
thrd_t thrd_current (void)
thrd_detach()
int thrd_detach (thrd_t)
thrd_equal()
int thrd_equal (thrd_t , thrd_t)
thrd_exit()
_Noreturn void thrd_exit (int result)
Definition at line 5 of file thrd_exit.c.
 {
     __pthread_exit((void*)(intptr_t)result);
 }
References __pthread_exit().
thrd_join()
int thrd_join (thrd_t t, int * res)
Definition at line 5 of file thrd_join.c.
 {
         void *pthread_res;
         __pthread_join(t, &pthread_res);
         if (res) *res = (int)(intptr_t)pthread_res;
         return thrd_success;
 }
References __pthread_join(), t, and thrd_success.
thrd_sleep()
int thrd_sleep (const struct timespec * req, struct timespec * rem)
Definition at line 6 of file thrd_sleep.c.
 {
     int ret = -__clock_nanosleep(CLOCK_REALTIME, 0, req, rem);
     switch (ret) {
     case 0:      return 0;
     case -EINTR: return -1; /* value specified by C11 */
     default:     return -2;
     }
 }
References __clock_nanosleep(), and EINTR.
Referenced by __thrd_sleep_time32().
thrd_yield()
void thrd_yield (void)
Definition at line 4 of file thrd_yield.c.
 {
     __syscall(SYS_sched_yield);
 }
References __syscall.
tss_create()
int tss_create (tss_t * tss, tss_dtor_t dtor)
Definition at line 4 of file tss_create.c.
 {
     /* Different error returns are possible. C glues them together into
      * just failure notification. Can't be optimized to a tail call,
      * unless thrd_error equals EAGAIN. */
     return __pthread_key_create(tss, dtor) ? thrd_error : thrd_success;
 }
References __pthread_key_create(), thrd_error, thrd_success, and GlobalDescriptorTable::tss.
tss_delete()
void tss_delete (tss_t key)
Definition at line 4 of file tss_delete.c.
 {
     __pthread_key_delete(key);
 }
References __pthread_key_delete().
tss_get()
void* tss_get (tss_t)
tss_set()
int tss_set (tss_t k, void * x)
Definition at line 4 of file tss_set.c.
 {
     struct pthread *self = __pthread_self();
     /* Avoid unnecessary COW */
     if (self->tsd[k] != x) {
         self->tsd[k] = x;
         self->tsd_used = 1;
     }
     return thrd_success;
 }
References __pthread_self, k, pthread::self, thrd_success, pthread::tsd, and x.