Fennix Userspace: Userspace/musl/src/time/mktime.c File Reference
mktime.c File Reference
#include "time_impl.h"
#include <errno.h>
Functions
time_t mktime (struct tm *tm)
Function Documentation
mktime()
time_t mktime (struct tm * tm)
Definition at line 4 of file mktime.c.
 {
     struct tm new;
     long opp;
     long long t = __tm_to_secs(tm);
     __secs_to_zone(t, 1, &new.tm_isdst, &new.__tm_gmtoff, &opp, &new.__tm_zone);
     if (tm->tm_isdst>=0 && new.tm_isdst!=tm->tm_isdst)
         t -= opp - new.__tm_gmtoff;
     t -= new.__tm_gmtoff;
     if ((time_t)t != t) goto error;
     __secs_to_zone(t, 0, &new.tm_isdst, &new.__tm_gmtoff, &opp, &new.__tm_zone);
     if (__secs_to_tm(t + new.__tm_gmtoff, &new) < 0) goto error;
     *tm = new;
     return t;
 error:
     errno = EOVERFLOW;
     return -1;
 }
References __secs_to_tm(), __secs_to_zone(), tm::__tm_gmtoff, __tm_to_secs(), tm::__tm_zone, EOVERFLOW, errno, error, and tm::tm_isdst.
Referenced by __mktime32(), and test_time().