Fennix Userspace: Userspace/mlibc/options/glibc/generic/shadow-stubs.cpp File Reference
shadow-stubs.cpp File Reference
#include <shadow.h>
#include <errno.h>
#include <limits.h>
#include <pthread.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
Macros
#define NUM(n) ((n) == -1 ? 0 : -1), ((n) == -1 ? 0 : (n))
#define LINE_LIM 256
Functions
int putspent (const struct spwd *sp, FILE *f)
static long xatol (char **s)
static int __parsespent (char *s, struct spwd *sp)
static void cleanup (void *p)
int getspnam_r (const char *name, struct spwd *sp, char *buf, size_t size, struct spwd **res)
int lckpwdf (void)
int ulckpwdf (void)
struct spwd * getspnam (const char *name)
struct spwd * fgetspent (FILE *)
void endspent (void)
Macro Definition Documentation
LINE_LIM
#define LINE_LIM 256
Definition at line 190 of file shadow-stubs.cpp.
NUM
#define NUM (n) ((n) == -1 ? 0 : -1), ((n) == -1 ? 0 : (n))
Definition at line 22 of file shadow-stubs.cpp.
Function Documentation
__parsespent()
static int __parsespent (char * s, struct spwd * sp) static
Definition at line 46 of file shadow-stubs.cpp.
{
     sp->sp_namp = s;
     if(!(s = strchr(s, ':'))) {
         return -1;
     }
     *s = 0;
     sp->sp_pwdp = ++s;
     if(!(s = strchr(s, ':'))) {
         return -1;
     }
     *s = 0;
     s++;
     sp->sp_lstchg = xatol(&s);
     if(*s != ':') {
         return -1;
     }
     s++;
     sp->sp_min = xatol(&s);
     if(*s != ':') {
         return -1;
     }
     s++;
     sp->sp_max = xatol(&s);
     if(*s != ':') {
         return -1;
     }
     s++;
     sp->sp_warn = xatol(&s);
     if(*s != ':') {
         return -1;
     }
     s++;
     sp->sp_inact = xatol(&s);
     if(*s != ':') {
         return -1;
     }
     s++;
     sp->sp_expire = xatol(&s);
     if(*s != ':') {
         return -1;
     }
     s++;
     sp->sp_flag = xatol(&s);
     if(*s != '\n') {
         return -1;
     }
     return 0;
 }
References spwd::sp_expire, spwd::sp_flag, spwd::sp_inact, spwd::sp_lstchg, spwd::sp_max, spwd::sp_min, spwd::sp_namp, spwd::sp_pwdp, spwd::sp_warn, strchr(), and xatol().
Referenced by getspnam_r().
cleanup()
static void cleanup (void * p) static
Definition at line 103 of file shadow-stubs.cpp.
{
     fclose((FILE *)p);
 }
References fclose(), and p.
Referenced by getspnam_r().
endspent()
void endspent (void)
Definition at line 215 of file shadow-stubs.cpp.
                     {
     mlibc::infoLogger() << "mlibc: endspent is a stub" << frg::endlog;
 }
References mlibc::infoLogger.
fgetspent()
struct spwd* fgetspent (FILE *)
Definition at line 210 of file shadow-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getspnam()
struct spwd* getspnam (const char * name)
Definition at line 192 of file shadow-stubs.cpp.
{
     static struct spwd sp;
     static char *line;
     struct spwd *res;
     int e;
     int orig_errno = errno;
     if(!line) {
         line = (char *)malloc(LINE_LIM);
     }
     if(!line) {
         return 0;
     }
     e = getspnam_r(name, &sp, line, LINE_LIM, &res);
     errno = e ? e : orig_errno;
     return res;
 }
References errno, getspnam_r(), LINE_LIM, malloc(), and name.
getspnam_r()
int getspnam_r (const char * name, struct spwd * sp, char * buf, size_t size, struct spwd ** res)
Definition at line 107 of file shadow-stubs.cpp.
{
     char path[20 + NAME_MAX];
     FILE *f = 0;
     int rv = 0;
     int fd;
     size_t k, l = strlen(name);
     int skip = 0;
     int cs;
     int orig_errno = errno;
     *res = 0;
     /* Disallow potentially-malicious user names */
     if(*name=='.' || strchr(name, '/') || !l) {
         return errno = EINVAL;
     }
     /* Buffer size must at least be able to hold name, plus some.. */
     if(size < l + 100) {
         return errno = ERANGE;
     }
     /* Protect against truncation */
     if(snprintf(path, sizeof path, "/etc/tcb/%s/shadow", name) >= (int)sizeof path) {
         return errno = EINVAL;
     }
     fd = open(path, O_RDONLY|O_NOFOLLOW|O_NONBLOCK|O_CLOEXEC);
     if(fd >= 0) {
         struct stat st = {};
         errno = EINVAL;
         if(fstat(fd, &st) || !S_ISREG(st.st_mode) || !(f = fdopen(fd, "rb"))) {
             pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
             close(fd);
             pthread_setcancelstate(cs, 0);
             return errno;
         }
     } else {
         if(errno != ENOENT && errno != ENOTDIR) {
             return errno;
         }
         f = fopen("/etc/shadow", "rbe");
         if(!f) {
             if(errno != ENOENT && errno != ENOTDIR) {
                 return errno;
             }
             return 0;
         }
     }
     pthread_cleanup_push(cleanup, f);
     while(fgets(buf, size, f) && (k = strlen(buf)) > 0) {
         if(skip || strncmp(name, buf, l) || buf[l] != ':') {
             skip = buf[k - 1] != '\n';
             continue;
         }
         if(buf[k - 1] != '\n') {
             rv = ERANGE;
             break;
         }
         if(__parsespent(buf, sp) < 0) {
             continue;
         }
         *res = sp;
         break;
     }
     pthread_cleanup_pop(1);
     errno = rv ? rv : orig_errno;
     return rv;
 }
References __parsespent(), buf, cleanup(), close(), EINVAL, ENOENT, ENOTDIR, ERANGE, errno, fd, fdopen(), fgets(), fopen(), fstat(), k, name, NAME_MAX, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, O_RDONLY, open(), PTHREAD_CANCEL_DISABLE, pthread_cleanup_pop(), pthread_cleanup_push(), pthread_setcancelstate(), S_ISREG, size, snprintf(), stat::st_mode, strchr(), strlen(), and strncmp().
Referenced by getspnam().
lckpwdf()
int lckpwdf (void)
Definition at line 179 of file shadow-stubs.cpp.
                   {
     mlibc::infoLogger() << "mlibc: lckpwdf is unimplemented like musl" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
putspent()
int putspent (const struct spwd * sp, FILE * f)
Definition at line 24 of file shadow-stubs.cpp.
{
     auto str = [] (char *s) {
         return ((s) ? (s) : "");
     };
     return fprintf(f, "%s:%s:%.*d:%.*d:%.*d:%.*d:%.*d:%.*d:%.*u\n",
         str(sp->sp_namp), str(sp->sp_pwdp), NUM(sp->sp_lstchg),
         NUM(sp->sp_min), NUM(sp->sp_max), NUM(sp->sp_warn),
         NUM(sp->sp_inact), NUM(sp->sp_expire), NUM((int)sp->sp_flag)) < 0 ? -1 : 0;
 }
References fprintf(), NUM, spwd::sp_expire, spwd::sp_flag, spwd::sp_inact, spwd::sp_lstchg, spwd::sp_max, spwd::sp_min, spwd::sp_namp, spwd::sp_pwdp, and spwd::sp_warn.
ulckpwdf()
int ulckpwdf (void)
Definition at line 184 of file shadow-stubs.cpp.
                    {
     mlibc::infoLogger() << "mlibc: ulckpwdf is unimplemented like musl" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
xatol()
static long xatol (char ** s) static
Definition at line 35 of file shadow-stubs.cpp.
{
     long x;
     if(**s == ':' || **s == '\n') {
         return -1;
     }
     for(x = 0; (unsigned int)**s - '0' < 10U; ++*s) {
         x = 10 * x + (**s - '0');
     }
     return x;
 }
References int, and x.
Referenced by __parsespent().