Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/d_iwad.c File Reference
d_iwad.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "config.h"
#include "deh_str.h"
#include "doomkeys.h"
#include "d_iwad.h"
#include "i_system.h"
#include "m_argv.h"
#include "m_config.h"
#include "m_misc.h"
#include "w_wad.h"
#include "z_zone.h"
Macros
#define MAX_IWAD_DIRS 128
Functions
static void AddIWADDir (char *dir)
static boolean DirIsFile (char *path, char *filename)
static char * CheckDirectoryHasIWAD (char *dir, char *iwadname)
static char * SearchDirectoryForIWAD (char *dir, int mask, GameMission_t *mission)
static GameMission_t IdentifyIWADByName (char *name, int mask)
static void BuildIWADDirList (void)
char * D_FindWADByName (char *name)
char * D_TryFindWADByName (char *filename)
char * D_FindIWAD (int mask, GameMission_t *mission)
const iwad_t ** D_FindAllIWADs (int mask)
char * D_SaveGameIWADName (GameMission_t gamemission)
char * D_SuggestIWADName (GameMission_t mission, GameMode_t mode)
char * D_SuggestGameName (GameMission_t mission, GameMode_t mode)
Variables
static const iwad_t iwads []
static boolean iwad_dirs_built = false
static char * iwad_dirs [MAX_IWAD_DIRS]
static int num_iwad_dirs = 0
Macro Definition Documentation
MAX_IWAD_DIRS
#define MAX_IWAD_DIRS 128
Definition at line 58 of file d_iwad.c.
Function Documentation
AddIWADDir()
static void AddIWADDir (char * dir) static
Definition at line 64 of file d_iwad.c.
 {
     if (num_iwad_dirs < MAX_IWAD_DIRS)
     {
         iwad_dirs[num_iwad_dirs] = dir;
         ++num_iwad_dirs;
     }
 }
References dir, iwad_dirs, MAX_IWAD_DIRS, and num_iwad_dirs.
Referenced by BuildIWADDirList().
BuildIWADDirList()
static void BuildIWADDirList (void) static
Definition at line 567 of file d_iwad.c.
 {
 #if ORIGCODE
     char *doomwaddir;
     if (iwad_dirs_built)
     {
         return;
     }
     // Look in the current directory.  Doom always does this.
     AddIWADDir(".");
     // Add DOOMWADDIR if it is in the environment
     doomwaddir = getenv("DOOMWADDIR");
     if (doomwaddir != NULL)
     {
         AddIWADDir(doomwaddir);
     }
     // Add dirs from DOOMWADPATH
     AddDoomWadPath();
 #ifdef _WIN32
     // Search the registry and find where IWADs have been installed.
     CheckUninstallStrings();
     CheckCollectorsEdition();
     CheckSteamEdition();
     CheckDOSDefaults();
     // Check for GUS patches installed with the BFG edition!
     CheckSteamGUSPatches();
 #else
     // Standard places where IWAD files are installed under Unix.
     AddIWADDir("/usr/share/games/doom");
     AddIWADDir("/usr/local/share/games/doom");
 #endif
 #else
     AddIWADDir (FILES_DIR);
     // Don't run this function again.
     iwad_dirs_built = true;
 #endif
 }
References AddIWADDir(), FILES_DIR, getenv, iwad_dirs_built, and NULL.
Referenced by D_FindIWAD(), and D_FindWADByName().
CheckDirectoryHasIWAD()
static char* CheckDirectoryHasIWAD (char * dir, char * iwadname) static
Definition at line 408 of file d_iwad.c.
 {
     char *filename;
     // As a special case, the "directory" may refer directly to an
     // IWAD file if the path comes from DOOMWADDIR or DOOMWADPATH.
     if (DirIsFile(dir, iwadname) && M_FileExists(dir))
     {
         return strdup(dir);
     }
     // Construct the full path to the IWAD if it is located in
     // this directory, and check if it exists.
     if (!strcmp(dir, "."))
     {
         filename = strdup(iwadname);
     }
     else
     {
         filename = M_StringJoin(dir, DIR_SEPARATOR_S, iwadname, NULL);
     }
     printf("Trying IWAD file:%s\n", filename);
     if (M_FileExists(filename))
     {
         return filename;
     }
     free(filename);
     return NULL;
 }
References dir, DIR_SEPARATOR_S, DirIsFile(), filename, free, M_FileExists(), M_StringJoin(), NULL, printf(), strcmp, and strdup().
Referenced by SearchDirectoryForIWAD().
D_FindAllIWADs()
const iwad_t** D_FindAllIWADs (int mask)
Definition at line 755 of file d_iwad.c.
 {
     const iwad_t **result;
     int result_len;
     char *filename;
     int i;
     result = malloc(sizeof(iwad_t *) * (arrlen(iwads) + 1));
     result_len = 0;
     // Try to find all IWADs
     for (i=0; i<arrlen(iwads); ++i)
     {
         if (((1 << iwads[i].mission) & mask) == 0)
         {
             continue;
         }
         filename = D_FindWADByName(iwads[i].name);
         if (filename != NULL)
         {
             result[result_len] = &iwads[i];
             ++result_len;
         }
     }
     // End of list
     result[result_len] = NULL;
     return result;
 }
References arrlen, D_FindWADByName(), filename, i, iwads, malloc, and NULL.
D_FindIWAD()
char* D_FindIWAD (int mask, GameMission_t * mission)
Definition at line 702 of file d_iwad.c.
 {
     char *result;
     char *iwadfile;
     int iwadparm;
     int i;
     // Check for the -iwad parameter
     // Specify an IWAD file to use.
     //
     // @arg <file>
     //
     iwadparm = M_CheckParmWithArgs("-iwad", 1);
     if (iwadparm)
     {
         // Search through IWAD dirs for an IWAD with the given name.
         iwadfile = myargv[iwadparm + 1];
         result = D_FindWADByName(iwadfile);
         if (result == NULL)
         {
             I_Error("IWAD file '%s' not found!", iwadfile);
         }
         *mission = IdentifyIWADByName(result, mask);
     }
     else
     {
         // Search through the list and look for an IWAD
         printf("-iwad not specified, trying a few iwad names\n");
         result = NULL;
         BuildIWADDirList();
         for (i=0; result == NULL && i<num_iwad_dirs; ++i)
         {
             result = SearchDirectoryForIWAD(iwad_dirs[i], mask, mission);
         }
     }
     return result;
 }
References BuildIWADDirList(), D_FindWADByName(), i, I_Error(), IdentifyIWADByName(), iwad_dirs, iwadfile, M_CheckParmWithArgs(), myargv, NULL, num_iwad_dirs, printf(), and SearchDirectoryForIWAD().
Referenced by D_DoomMain().
D_FindWADByName()
char* D_FindWADByName (char * name)
Definition at line 628 of file d_iwad.c.
 {
     char *path;
     int i;
     // Absolute path?
     if (M_FileExists(name))
     {
         return name;
     }
     BuildIWADDirList();
     // Search through all IWAD paths for a file with the given name.
     for (i=0; i<num_iwad_dirs; ++i)
     {
         // As a special case, if this is in DOOMWADDIR or DOOMWADPATH,
         // the "directory" may actually refer directly to an IWAD
         // file.
         if (DirIsFile(iwad_dirs[i], name) && M_FileExists(iwad_dirs[i]))
         {
             return strdup(iwad_dirs[i]);
         }
         // Construct a string for the full path
         path = M_StringJoin(iwad_dirs[i], DIR_SEPARATOR_S, name, NULL);
         if (M_FileExists(path))
         {
             return path;
         }
         free(path);
     }
     // File not found
     return NULL;
 }
References BuildIWADDirList(), DIR_SEPARATOR_S, DirIsFile(), free, i, iwad_dirs, M_FileExists(), M_StringJoin(), NULL, num_iwad_dirs, and strdup().
Referenced by D_FindAllIWADs(), D_FindIWAD(), and D_TryFindWADByName().
D_SaveGameIWADName()
char* D_SaveGameIWADName (GameMission_t gamemission)
Definition at line 794 of file d_iwad.c.
 {
     size_t i;
     // Determine the IWAD name to use for savegames.
     // This determines the directory the savegame files get put into.
     //
     // Note that we match on gamemission rather than on IWAD name.
     // This ensures that doom1.wad and doom.wad saves are stored
     // in the same place.
     for (i=0; i<arrlen(iwads); ++i)
     {
         if (gamemission == iwads[i].mission)
         {
             return iwads[i].name;
         }
     }
     // Default fallback:
     return "unknown.wad";
 }
References arrlen, gamemission, i, iwads, and iwad_t::name.
Referenced by D_DoomMain().
D_SuggestGameName()
char* D_SuggestGameName (GameMission_t mission, GameMode_t mode)
Definition at line 833 of file d_iwad.c.
 {
     int i;
     for (i = 0; i < arrlen(iwads); ++i)
     {
         if (iwads[i].mission == mission
          && (mode == indetermined || iwads[i].mode == mode))
         {
             return iwads[i].description;
         }
     }
     return "Unknown game?";
 }
References arrlen, iwad_t::description, i, indetermined, and iwads.
Referenced by W_CheckCorrectIWAD().
D_SuggestIWADName()
char* D_SuggestIWADName (GameMission_t mission, GameMode_t mode)
Definition at line 818 of file d_iwad.c.
 {
     int i;
     for (i = 0; i < arrlen(iwads); ++i)
     {
         if (iwads[i].mission == mission && iwads[i].mode == mode)
         {
             return iwads[i].name;
         }
     }
     return "unknown.wad";
 }
References arrlen, i, iwads, and iwad_t::name.
D_TryFindWADByName()
char* D_TryFindWADByName (char * filename)
Definition at line 679 of file d_iwad.c.
 {
     char *result;
     result = D_FindWADByName(filename);
     if (result != NULL)
     {
         return result;
     }
     else
     {
         return filename;
     }
 }
References D_FindWADByName(), filename, and NULL.
Referenced by W_ParseCommandLine().
DirIsFile()
static boolean DirIsFile (char * path, char * filename) static
Definition at line 391 of file d_iwad.c.
 {
     size_t path_len;
     size_t filename_len;
     path_len = strlen(path);
     filename_len = strlen(filename);
     return path_len >= filename_len + 1
         && path[path_len - filename_len - 1] == DIR_SEPARATOR
         && !strcasecmp(&path[path_len - filename_len], filename);
 }
References DIR_SEPARATOR, filename, strcasecmp, and strlen().
Referenced by CheckDirectoryHasIWAD(), and D_FindWADByName().
IdentifyIWADByName()
static GameMission_t IdentifyIWADByName (char * name, int mask) static
Definition at line 475 of file d_iwad.c.
 {
     size_t i;
     GameMission_t mission;
     char *p;
     p = strrchr(name, DIR_SEPARATOR);
     if (p != NULL)
     {
         name = p + 1;
     }
     mission = none;
     for (i=0; i<arrlen(iwads); ++i)
     {
         // Check if the filename is this IWAD name.
         // Only use supported missions:
         if (((1 << iwads[i].mission) & mask) == 0)
             continue;
         // Check if it ends in this IWAD name.
         if (!strcasecmp(name, iwads[i].name))
         {
             mission = iwads[i].mission;
             break;
         }
     }
     return mission;
 }
References arrlen, DIR_SEPARATOR, i, iwads, iwad_t::mission, none, NULL, p, strcasecmp, and strrchr().
Referenced by D_FindIWAD().
SearchDirectoryForIWAD()
static char* SearchDirectoryForIWAD (char * dir, int mask, GameMission_t * mission) static
Definition at line 447 of file d_iwad.c.
 {
     char *filename;
     size_t i;
     for (i=0; i<arrlen(iwads); ++i)
     {
         if (((1 << iwads[i].mission) & mask) == 0)
         {
             continue;
         }
         filename = CheckDirectoryHasIWAD(dir, DEH_String(iwads[i].name));
         if (filename != NULL)
         {
             *mission = iwads[i].mission;
             return filename;
         }
     }
     return NULL;
 }
References arrlen, CheckDirectoryHasIWAD(), DEH_String, dir, filename, i, iwads, iwad_t::mission, and NULL.
Referenced by D_FindIWAD().
Variable Documentation
iwad_dirs
char* iwad_dirs[MAX_IWAD_DIRS] static
Definition at line 61 of file d_iwad.c.
Referenced by AddIWADDir(), D_FindIWAD(), and D_FindWADByName().
iwad_dirs_built
boolean iwad_dirs_built = false static
Definition at line 60 of file d_iwad.c.
Referenced by BuildIWADDirList().
iwads
const iwad_t iwads[] static
Initial value:
=
{
    { "doom2.wad",    doom2,     commercial, "Doom II" },
    { "plutonia.wad", pack_plut, commercial, "Final Doom: Plutonia Experiment" },
    { "tnt.wad",      pack_tnt,  commercial, "Final Doom: TNT: Evilution" },
    { "doom.wad",     doom,      retail,     "Doom" },
    { "DOOM1.WAD",    doom,      shareware,  "Doom Shareware" },
    { "chex.wad",     pack_chex, shareware,  "Chex Quest" },
    { "hacx.wad",     pack_hacx, commercial, "Hacx" },
    { "freedm.wad",   doom2,     commercial, "FreeDM" },
    { "freedoom2.wad", doom2,    commercial, "Freedoom: Phase 2" },
    { "freedoom1.wad", doom,     retail,     "Freedoom: Phase 1" },
    { "heretic.wad",  heretic,   retail,     "Heretic" },
    { "heretic1.wad", heretic,   shareware,  "Heretic Shareware" },
    { "hexen.wad",    hexen,     commercial, "Hexen" },
    { "strife1.wad",  strife,    commercial, "Strife" },
}
Definition at line 35 of file d_iwad.c.
Referenced by D_FindAllIWADs(), D_SaveGameIWADName(), D_SuggestGameName(), D_SuggestIWADName(), IdentifyIWADByName(), and SearchDirectoryForIWAD().
num_iwad_dirs
int num_iwad_dirs = 0 static
Definition at line 62 of file d_iwad.c.
Referenced by AddIWADDir(), D_FindIWAD(), and D_FindWADByName().