Fennix: Userspace/musl/src/stat/futimesat.c File Reference
futimesat.c File Reference
#include <sys/time.h>
#include <sys/stat.h>
#include <errno.h>
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
int __futimesat (int dirfd, const char *pathname, const struct timeval times[2])
weak_alias (__futimesat, futimesat)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file futimesat.c.
Function Documentation
__futimesat()
int __futimesat (int dirfd, const char * pathname, const struct timeval times[2])
Definition at line 7 of file futimesat.c.
 {
     struct timespec ts[2];
     if (times) {
         int i;
         for (i=0; i<2; i++) {
             if (times[i].tv_usec >= 1000000ULL)
                 return __syscall_ret(-EINVAL);
             ts[i].tv_sec = times[i].tv_sec;
             ts[i].tv_nsec = times[i].tv_usec * 1000;
         }
     }
     return utimensat(dirfd, pathname, times ? ts : 0, 0);
 }
References __syscall_ret(), dirfd, EINVAL, i, pathname, times(), timespec::tv_nsec, timespec::tv_sec, and utimensat().
Referenced by utimes().
weak_alias()
weak_alias (__futimesat , futimesat)