Fennix: Userspace/apps/base/busybox/console-tools/dumpkmap.c File Reference
dumpkmap.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct kbentry
Macros
#define KDGKBENT 0x4B46 /* gets one entry in translation table */
#define NR_KEYS 128
#define MAX_NR_KEYMAPS 256
#define flags bb_common_bufsiz1
#define flags7 (flags + 7)
Functions
int dumpkmap_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
kbentry
struct kbentry
Definition at line 33 of file dumpkmap.c.
Data Fields
unsigned char kb_index
unsigned char kb_table
unsigned short kb_value
Macro Definition Documentation
flags
#define flags bb_common_bufsiz1
flags7
#define flags7 (flags + 7)
KDGKBENT
#define KDGKBENT 0x4B46 /* gets one entry in translation table */
Definition at line 38 of file dumpkmap.c.
MAX_NR_KEYMAPS
#define MAX_NR_KEYMAPS 256
Definition at line 42 of file dumpkmap.c.
NR_KEYS
#define NR_KEYS 128
Definition at line 41 of file dumpkmap.c.
Function Documentation
dumpkmap_main()
int dumpkmap_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 45 of file dumpkmap.c.
 {
     struct kbentry ke;
     int i, j, fd;
     /* When user accidentally runs "dumpkmap FILE"
      * instead of "dumpkmap >FILE", we'd dump binary stuff to tty.
      * Let's prevent it:
      */
     if (argv[1])
         bb_show_usage();
 /*  bb_warn_ignoring_args(argv[1]);*/
     fd = get_console_fd_or_die();
 #define flags bb_common_bufsiz1
     setup_common_bufsiz();
     /*                     0 1 2 3 4 5 6 7 8 9 a b c=12 */
     memcpy(flags, "bkeymap\1\1\1\0\1\1\1\0\1\1\1\0\1",
     /* Can use sizeof, or sizeof-1. sizeof is even, using that */
     /****/ sizeof("bkeymap\1\1\1\0\1\1\1\0\1\1\1\0\1")
     );
     write(STDOUT_FILENO, flags, 7 + MAX_NR_KEYMAPS);
 #define flags7 (flags + 7)
     for (i = 0; i < 13; i++) {
         if (flags7[i]) {
             for (j = 0; j < NR_KEYS; j++) {
                 ke.kb_index = j;
                 ke.kb_table = i;
                 if (!ioctl_or_perror(fd, KDGKBENT, &ke,
                         "ioctl(KDGKBENT{%d,%d}) failed",
                         j, i)
                 ) {
                     write(STDOUT_FILENO, &ke.kb_value, 2);
                 }
             }
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(fd);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_show_usage(), close(), EXIT_SUCCESS, fd, flags, flags7, get_console_fd_or_die(), i, ioctl_or_perror(), j, kbentry::kb_index, kbentry::kb_table, kbentry::kb_value, KDGKBENT, MAX_NR_KEYMAPS, memcpy, NR_KEYS, STDOUT_FILENO, and write().