Fennix Userspace: Userspace/apps/base/busybox/util-linux/rev.c File Reference
rev.c File Reference
#include "libbb.h"
#include "unicode.h"
Macros
#define CHAR_T char
Functions
static void strrev (CHAR_T *s, int len)
int rev_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CHAR_T
#define CHAR_T char
Definition at line 30 of file rev.c.
Function Documentation
rev_main()
int rev_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 52 of file rev.c.
 {
     int retval;
     size_t bufsize;
     char *buf;
     init_unicode();
     getopt32(argv, "");
     argv += optind;
     if (!argv[0])
         argv = (char **)&bb_argv_dash;
     retval = EXIT_SUCCESS;
     bufsize = 256;
     buf = xmalloc(bufsize);
     do {
         size_t pos;
         FILE *fp;
         fp = fopen_or_warn_stdin(*argv++);
         if (!fp) {
             retval = EXIT_FAILURE;
             continue;
         }
         pos = 0;
         while (1) {
             /* Read one line */
             buf[bufsize - 1] = 1; /* not 0 */
             if (!fgets(buf + pos, bufsize - pos, fp))
                 break; /* EOF/error */
             if (buf[bufsize - 1] == '\0' /* fgets filled entire buffer */
              && buf[bufsize - 2] != '\n' /* and did not read '\n' */
              && !feof(fp)
             ) {
                 /* Line is too long, extend buffer */
                 pos = bufsize - 1;
                 bufsize += 64 + bufsize / 8;
                 buf = xrealloc(buf, bufsize);
                 continue;
             }
             /* Process and print it */
 #if ENABLE_UNICODE_SUPPORT
             {
                 wchar_t *tmp = xmalloc(bufsize * sizeof(wchar_t));
                 /* Convert to wchar_t (might error out!) */
                 int len  = mbstowcs(tmp, buf, bufsize);
                 if (len >= 0) {
                     strrev(tmp, len);
                     /* Convert back to char */
                     wcstombs(buf, tmp, bufsize);
                 }
                 free(tmp);
             }
 #else
             strrev(buf, strlen(buf));
 #endif
             fputs_stdout(buf);
             pos = 0;
         }
         fclose(fp);
     } while (*argv);
     if (ENABLE_FEATURE_CLEAN_UP)
         free(buf);
     fflush_stdout_and_exit(retval);
 }
References argv, bb_argv_dash, buf, EXIT_FAILURE, EXIT_SUCCESS, fclose(), feof, fflush_stdout_and_exit(), fgets, fopen_or_warn_stdin(), fputs_stdout(), free, getopt32(), init_unicode, mbstowcs(), optind, pos, retval, strlen(), strrev(), wcstombs(), xmalloc, and xrealloc.
strrev()
static void strrev (CHAR_T * s, int len) static
Definition at line 34 of file rev.c.
 {
     int i;
     if (len != 0) {
         len--;
         if (len != 0 && s[len] == '\n')
             len--;
     }
     for (i = 0; i < len; i++, len--) {
         CHAR_T c = s[i];
         s[i] = s[len];
         s[len] = c;
     }
 }
References c, CHAR_T, i, and s.
Referenced by rev_main().