Fennix: Userspace/mlibc/options/posix/generic/net-if-stubs.cpp File Reference
net-if-stubs.cpp File Reference
#include <errno.h>
#include <net/if.h>
#include <bits/ensure.h>
#include <mlibc/posix-sysdeps.hpp>
Functions
void if_freenameindex (struct if_nameindex *)
char * if_indextoname (unsigned int index, char *name)
struct if_nameindex * if_nameindex (void)
unsigned int if_nametoindex (const char *name)
Function Documentation
if_freenameindex()
void if_freenameindex (struct if_nameindex *)
Definition at line 7 of file net-if-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
if_indextoname()
char* if_indextoname (unsigned int index, char * name)
Definition at line 12 of file net-if-stubs.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_if_indextoname, NULL);
     if(int e = sysdep(index, name); e) {
         errno = e;
         return NULL;
     }
     return name;
 }
References errno, index(), MLIBC_CHECK_OR_ENOSYS, name, NULL, and mlibc::sys_if_indextoname().
Referenced by main().
if_nameindex()
struct if_nameindex* if_nameindex (void)
Definition at line 23 of file net-if-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
if_nametoindex()
unsigned int if_nametoindex (const char * name)
Definition at line 28 of file net-if-stubs.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_if_nametoindex, 0);
     unsigned int ret = 0;
     if(int e = sysdep(name, &ret); e) {
         errno = e;
         return 0;
     }
     return ret;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, name, ret, and mlibc::sys_if_nametoindex().
Referenced by main().