Fennix Userspace: ConfigItem Class Reference
ConfigItem Class Reference
#include <qconf.h>
Public Member Functions
ConfigItem (QListView *parent, ConfigItem *after, struct menu *m, bool v)
ConfigItem (ConfigItem *parent, ConfigItem *after, struct menu *m, bool v)
ConfigItem (QListView *parent, ConfigItem *after, bool v)
~ConfigItem (void)
void init (void)
void updateMenu (void)
void testUpdateMenu (bool v)
ConfigList * listView () const
ConfigItem * firstChild () const
ConfigItem * nextSibling () const
void setText (colIdx idx, const QString &text)
QString text (colIdx idx) const
void setPixmap (colIdx idx, const QPixmap &pm)
const QPixmap * pixmap (colIdx idx) const
void paintCell (QPainter *p, const QColorGroup &cg, int column, int width, int align)
Data Fields
ConfigItem * nextItem
struct menu * menu
bool visible
bool goParent
Private Types
typedef class QListViewItem Parent
Detailed Description
Definition at line 146 of file qconf.h.
Member Typedef Documentation
Parent
typedef class QListViewItem ConfigItem::Parent private
Definition at line 143 of file qconf.h.
Constructor & Destructor Documentation
ConfigItem() [1/3]
ConfigItem::ConfigItem (QListView * parent, ConfigItem * after, struct menu * m, bool v) inline
Definition at line 149 of file qconf.h.
     : Parent(parent, after), menu(m), visible(v), goParent(false)
     {
         init();
     }
References init().
ConfigItem() [2/3]
ConfigItem::ConfigItem (ConfigItem * parent, ConfigItem * after, struct menu * m, bool v) inline
Definition at line 154 of file qconf.h.
     : Parent(parent, after), menu(m), visible(v), goParent(false)
     {
         init();
     }
References init().
ConfigItem() [3/3]
ConfigItem::ConfigItem (QListView * parent, ConfigItem * after, bool v) inline
Definition at line 159 of file qconf.h.
     : Parent(parent, after), menu(0), visible(v), goParent(true)
     {
         init();
     }
References init().
~ConfigItem()
ConfigItem::~ConfigItem (void)
Definition at line 345 of file qconf.cc.
 {
     if (menu) {
         ConfigItem** ip = (ConfigItem**)&menu->data;
         for (; *ip; ip = &(*ip)->nextItem) {
             if (*ip == this) {
                 *ip = nextItem;
                 break;
             }
         }
     }
 }
References menu::data, for(), and nextItem.
Member Function Documentation
firstChild()
ConfigItem* ConfigItem::firstChild () const inline
Definition at line 175 of file qconf.h.
     {
         return (ConfigItem *)Parent::firstChild();
     }
init()
void ConfigItem::init (void)
Definition at line 328 of file qconf.cc.
 {
     if (menu) {
         ConfigList* list = listView();
         nextItem = (ConfigItem*)menu->data;
         menu->data = this;
         if (list->mode != fullMode)
             setOpen(TRUE);
         sym_calc_value(menu->sym);
     }
     updateMenu();
 }
References menu::data, fullMode, if(), list(), listView(), nextItem, menu::sym, sym_calc_value(), TRUE, and updateMenu().
Referenced by ConfigItem().
listView()
ConfigList* ConfigItem::listView () const inline
Definition at line 171 of file qconf.h.
     {
         return (ConfigList*)Parent::listView();
     }
Referenced by init(), paintCell(), pixmap(), setPixmap(), setText(), testUpdateMenu(), text(), and updateMenu().
nextSibling()
ConfigItem* ConfigItem::nextSibling () const inline
Definition at line 179 of file qconf.h.
     {
         return (ConfigItem *)Parent::nextSibling();
     }
paintCell()
void ConfigItem::paintCell (QPainter * p, const QColorGroup & cg, int column, int width, int align)
Definition at line 312 of file qconf.cc.
 {
     ConfigList* list = listView();
     if (visible) {
         if (isSelected() && !list->hasFocus() && list->mode == menuMode)
             Parent::paintCell(p, list->inactivedColorGroup, column, width, align);
         else
             Parent::paintCell(p, cg, column, width, align);
     } else
         Parent::paintCell(p, list->disabledColorGroup, column, width, align);
 }
References list(), listView(), menuMode, p, visible, and width.
pixmap()
const QPixmap* ConfigItem::pixmap (colIdx idx) const inline
Definition at line 195 of file qconf.h.
     {
         return Parent::pixmap(listView()->mapIdx(idx));
     }
References idx, and listView().
Referenced by ConfigList::contentsMouseReleaseEvent().
setPixmap()
void ConfigItem::setPixmap (colIdx idx, const QPixmap & pm) inline
Definition at line 191 of file qconf.h.
     {
         Parent::setPixmap(listView()->mapIdx(idx), pm);
     }
References idx, and listView().
Referenced by updateMenu().
setText()
void ConfigItem::setText (colIdx idx, const QString & text) inline
Definition at line 183 of file qconf.h.
     {
         Parent::setText(listView()->mapIdx(idx), text);
     }
References idx, listView(), and text().
Referenced by updateMenu().
testUpdateMenu()
void ConfigItem::testUpdateMenu (bool v)
Definition at line 294 of file qconf.cc.
 {
     ConfigItem* i;
     visible = v;
     if (!menu)
         return;
     sym_calc_value(menu->sym);
     if (menu->flags & MENU_CHANGED) {
         /* the menu entry changed, so update all list items */
         menu->flags &= ~MENU_CHANGED;
         for (i = (ConfigItem*)menu->data; i; i = i->nextItem)
             i->updateMenu();
     } else if (listView()->updateAll)
         updateMenu();
 }
References menu::data, menu::flags, i, listView(), MENU_CHANGED, menu::sym, sym_calc_value(), updateMenu(), and visible.
Referenced by ConfigList::updateList(), and ConfigList::updateMenuList().
text()
QString ConfigItem::text (colIdx idx) const inline
Definition at line 187 of file qconf.h.
     {
         return Parent::text(listView()->mapIdx(idx));
     }
References idx, listView(), and text.
Referenced by setText().
updateMenu()
void ConfigItem::updateMenu (void)
Definition at line 177 of file qconf.cc.
 {
     ConfigList* list;
     struct symbol* sym;
     struct property *prop;
     QString prompt;
     int type;
     tristate expr;
     list = listView();
     if (goParent) {
         setPixmap(promptColIdx, list->menuBackPix);
         prompt = "..";
         goto set_prompt;
     }
     sym = menu->sym;
     prop = menu->prompt;
     prompt = QString::fromLocal8Bit(menu_get_prompt(menu));
     if (prop) switch (prop->type) {
     case P_MENU:
         if (list->mode == singleMode || list->mode == symbolMode) {
             /* a menuconfig entry is displayed differently
              * depending whether it's at the view root or a child.
              */
             if (sym && list->rootEntry == menu)
                 break;
             setPixmap(promptColIdx, list->menuPix);
         } else {
             if (sym)
                 break;
             setPixmap(promptColIdx, 0);
         }
         goto set_prompt;
     case P_COMMENT:
         setPixmap(promptColIdx, 0);
         goto set_prompt;
     default:
         ;
     }
     if (!sym)
         goto set_prompt;
     setText(nameColIdx, QString::fromLocal8Bit(sym->name));
     type = sym_get_type(sym);
     switch (type) {
     case S_BOOLEAN:
     case S_TRISTATE:
         char ch;
         if (!sym_is_changable(sym) && !list->showAll) {
             setPixmap(promptColIdx, 0);
             setText(noColIdx, QString::null);
             setText(modColIdx, QString::null);
             setText(yesColIdx, QString::null);
             break;
         }
         expr = sym_get_tristate_value(sym);
         switch (expr) {
         case yes:
             if (sym_is_choice_value(sym) && type == S_BOOLEAN)
                 setPixmap(promptColIdx, list->choiceYesPix);
             else
                 setPixmap(promptColIdx, list->symbolYesPix);
             setText(yesColIdx, "Y");
             ch = 'Y';
             break;
         case mod:
             setPixmap(promptColIdx, list->symbolModPix);
             setText(modColIdx, "M");
             ch = 'M';
             break;
         default:
             if (sym_is_choice_value(sym) && type == S_BOOLEAN)
                 setPixmap(promptColIdx, list->choiceNoPix);
             else
                 setPixmap(promptColIdx, list->symbolNoPix);
             setText(noColIdx, "N");
             ch = 'N';
             break;
         }
         if (expr != no)
             setText(noColIdx, sym_tristate_within_range(sym, no) ? "_" : 0);
         if (expr != mod)
             setText(modColIdx, sym_tristate_within_range(sym, mod) ? "_" : 0);
         if (expr != yes)
             setText(yesColIdx, sym_tristate_within_range(sym, yes) ? "_" : 0);
         setText(dataColIdx, QChar(ch));
         break;
     case S_INT:
     case S_HEX:
     case S_STRING:
         const char* data;
         data = sym_get_string_value(sym);
 #if QT_VERSION >= 300
         int i = list->mapIdx(dataColIdx);
         if (i >= 0)
             setRenameEnabled(i, TRUE);
 #endif
         setText(dataColIdx, data);
         if (type == S_STRING)
             prompt = QString("%1: %2").arg(prompt).arg(data);
         else
             prompt = QString("(%2) %1").arg(prompt).arg(data);
         break;
     }
     if (!sym_has_value(sym) && visible)
         prompt += " (NEW)";
 set_prompt:
     setText(promptColIdx, prompt);
 }
References dataColIdx, expr(), goParent, i, list(), listView(), menu_get_prompt(), mod, modColIdx, symbol::name, nameColIdx, no, noColIdx, null(), P_COMMENT, P_MENU, prompt, menu::prompt, promptColIdx, S_BOOLEAN, S_HEX, S_INT, S_STRING, S_TRISTATE, setPixmap(), setText(), singleMode, property::sym, menu::sym, sym_get_string_value(), sym_get_tristate_value(), sym_get_type(), sym_has_value(), sym_is_changable(), sym_is_choice_value(), sym_tristate_within_range(), symbolMode, TRUE, type, property::type, visible, yes, and yesColIdx.
Referenced by init(), and testUpdateMenu().
Field Documentation
goParent
bool ConfigItem::goParent
Definition at line 204 of file qconf.h.
Referenced by ConfigList::contentsMouseDoubleClickEvent(), ConfigList::contentsMouseReleaseEvent(), ConfigList::keyPressEvent(), and updateMenu().
menu
struct menu* ConfigItem::menu
Definition at line 202 of file qconf.h.
Referenced by ConfigList::changeValue(), ConfigList::contentsMouseDoubleClickEvent(), ConfigList::contentsMouseReleaseEvent(), ConfigMainWindow::goBack(), ConfigList::keyPressEvent(), ConfigLineEdit::keyPressEvent(), ConfigList::setParentMenu(), ConfigList::setValue(), ConfigLineEdit::show(), ConfigList::updateMenuList(), and ConfigList::updateSelection().
nextItem
ConfigItem* ConfigItem::nextItem
Definition at line 201 of file qconf.h.
Referenced by init(), and ~ConfigItem().
visible
bool ConfigItem::visible
Definition at line 203 of file qconf.h.
Referenced by paintCell(), testUpdateMenu(), and updateMenu().
The documentation for this class was generated from the following files:
Userspace/apps/base/busybox/scripts/kconfig/qconf.h
Userspace/apps/base/busybox/scripts/kconfig/qconf.cc