Fennix: Userspace/mlibc/options/posix/include/libgen.h File Reference
libgen.h File Reference
Macros
#define basename basename
Functions
char * basename (char *)
char * dirname (char *)
Macro Definition Documentation
basename
#define basename basename
Definition at line 15 of file libgen.h.
Function Documentation
basename()
char* basename (char * s)
Definition at line 9 of file libgen-stubs.cpp.
{
     // This empty string behavior is specified by POSIX.
     if (!s || !*s)
         return const_cast<char *>(".");
     // Delete trailing slashes.
     // Note that we do not delete the slash at index zero.
     auto i = strlen(s) - 1;
     for(; i && s[i] == '/'; i--)
         s[i] = 0;
     // Find the last non-trailing slash.
     for(; i && s[i - 1] != '/'; i--)
         ;
     return s + i;
 }
References i, and strlen().
dirname()
char* dirname (char * s)
Definition at line 26 of file libgen-stubs.cpp.
{
     if (!s || !(*s))
         return const_cast<char *>(".");
     auto i = strlen(s) - 1;
     // Skip trailing slashes.
     for (; s[i] == '/'; i--)
         if(!i) // Path only consists of slashes.
             return const_cast<char *>("/");
     // Skip the last non-slash path component.
     for (; s[i] != '/'; i--)
         if(!i) // Path only contains a single component.
             return const_cast<char *>(".");
     // Skip slashes.
     for (; s[i] == '/'; i--)
         if(!i) // Path is entry in root directory.
             return const_cast<char *>("/");
     s[i+1] = 0;
     return s;
 }
References i, and strlen().
Referenced by bindtextdomain(), and ObjectRepository::requestObjectWithName().