Fennix Userspace: Userspace/mlibc/options/posix/include/net/if.h File Reference
if.h File Reference
#include <sys/socket.h>
Data Structures
struct if_nameindex
struct ifmap
struct ifreq
struct ifconf
union ifreq.ifr_ifrn
union ifreq.ifr_ifru
union ifconf.ifc_ifcu
Macros
#define IF_NAMESIZE 16
#define IFNAMSIZ IF_NAMESIZE
#define ALTIFNAMSIZ 128
#define IFALIASZ 256
#define ifr_name ifr_ifrn.ifrn_name
#define ifr_hwaddr ifr_ifru.ifru_hwaddr
#define ifr_addr ifr_ifru.ifru_addr
#define ifr_dstaddr ifr_ifru.ifru_dstaddr
#define ifr_broadaddr ifr_ifru.ifru_broadaddr
#define ifr_netmask ifr_ifru.ifru_netmask
#define ifr_flags ifr_ifru.ifru_flags
#define ifr_metric ifr_ifru.ifru_ivalue
#define ifr_mtu ifr_ifru.ifru_mtu
#define ifr_map ifr_ifru.ifru_map
#define ifr_slave ifr_ifru.ifru_slave
#define ifr_data ifr_ifru.ifru_data
#define ifr_ifindex ifr_ifru.ifru_ivalue
#define ifr_bandwidth ifr_ifru.ifru_ivalue
#define ifr_qlen ifr_ifru.ifru_ivalue
#define ifr_newname ifr_ifru.ifru_newname
#define ifc_buf ifc_ifcu.ifcu_buf
#define ifc_req ifc_ifcu.ifcu_req
#define IFF_UP 0x1
#define IFF_BROADCAST 0x2
#define IFF_DEBUG 0x4
#define IFF_LOOPBACK 0x8
#define IFF_POINTOPOINT 0x10
#define IFF_NOTRAILERS 0x20
#define IFF_RUNNING 0x40
#define IFF_NOARP 0x80
#define IFF_PROMISC 0x100
#define IFF_ALLMULTI 0x200
#define IFF_MASTER 0x400
#define IFF_SLAVE 0x800
#define IFF_MULTICAST 0x1000
#define IFF_PORTSEL 0x2000
#define IFF_AUTOMEDIA 0x4000
#define IFF_DYNAMIC 0x8000
#define IFF_LOWER_UP 0x10000
#define IFF_DORMANT 0x20000
#define IFF_ECHO 0x40000
#define IFF_VOLATILE
Functions
void if_freenameindex (struct if_nameindex *)
char * if_indextoname (unsigned int, char *)
struct if_nameindex * if_nameindex (void)
unsigned int if_nametoindex (const char *)
Data Structure Documentation
if_nameindex
struct if_nameindex
Definition at line 16 of file if.h.
Data Fields
unsigned int if_index
char * if_name
ifmap
struct ifmap
Definition at line 21 of file if.h.
Data Fields
unsigned short base_addr
unsigned char dma
unsigned char irq
unsigned long mem_end
unsigned long mem_start
unsigned char port
ifreq
struct ifreq
Definition at line 30 of file if.h.
Data Fields
union ifreq ifr_ifrn
union ifreq ifr_ifru
ifconf
struct ifconf
Definition at line 68 of file if.h.
Data Fields
union ifconf ifc_ifcu
int ifc_len
ifreq.ifr_ifrn
union ifreq.ifr_ifrn
Definition at line 31 of file if.h.
Data Fields
char ifrn_name[IFNAMSIZ]
ifreq.ifr_ifru
union ifreq.ifr_ifru
Definition at line 35 of file if.h.
Data Fields
struct sockaddr ifru_addr
struct sockaddr ifru_broadaddr
char * ifru_data
struct sockaddr ifru_dstaddr
short int ifru_flags
struct sockaddr ifru_hwaddr
int ifru_ivalue
struct ifmap ifru_map
int ifru_mtu
struct sockaddr ifru_netmask
char ifru_newname[IFNAMSIZ]
char ifru_slave[IFNAMSIZ]
ifconf.ifc_ifcu
union ifconf.ifc_ifcu
Definition at line 70 of file if.h.
Data Fields
char * ifcu_buf
struct ifreq * ifcu_req
Macro Definition Documentation
ALTIFNAMSIZ
#define ALTIFNAMSIZ 128
Definition at line 13 of file if.h.
IF_NAMESIZE
#define IF_NAMESIZE 16
Definition at line 11 of file if.h.
IFALIASZ
#define IFALIASZ 256
Definition at line 14 of file if.h.
ifc_buf
#define ifc_buf ifc_ifcu.ifcu_buf
Definition at line 76 of file if.h.
ifc_req
#define ifc_req ifc_ifcu.ifcu_req
Definition at line 77 of file if.h.
IFF_ALLMULTI
#define IFF_ALLMULTI 0x200
Definition at line 97 of file if.h.
IFF_AUTOMEDIA
#define IFF_AUTOMEDIA 0x4000
Definition at line 102 of file if.h.
IFF_BROADCAST
#define IFF_BROADCAST 0x2
Definition at line 89 of file if.h.
IFF_DEBUG
#define IFF_DEBUG 0x4
Definition at line 90 of file if.h.
IFF_DORMANT
#define IFF_DORMANT 0x20000
Definition at line 105 of file if.h.
IFF_DYNAMIC
#define IFF_DYNAMIC 0x8000
Definition at line 103 of file if.h.
IFF_ECHO
#define IFF_ECHO 0x40000
Definition at line 106 of file if.h.
IFF_LOOPBACK
#define IFF_LOOPBACK 0x8
Definition at line 91 of file if.h.
IFF_LOWER_UP
#define IFF_LOWER_UP 0x10000
Definition at line 104 of file if.h.
IFF_MASTER
#define IFF_MASTER 0x400
Definition at line 98 of file if.h.
IFF_MULTICAST
#define IFF_MULTICAST 0x1000
Definition at line 100 of file if.h.
IFF_NOARP
#define IFF_NOARP 0x80
Definition at line 95 of file if.h.
IFF_NOTRAILERS
#define IFF_NOTRAILERS 0x20
Definition at line 93 of file if.h.
IFF_POINTOPOINT
#define IFF_POINTOPOINT 0x10
Definition at line 92 of file if.h.
IFF_PORTSEL
#define IFF_PORTSEL 0x2000
Definition at line 101 of file if.h.
IFF_PROMISC
#define IFF_PROMISC 0x100
Definition at line 96 of file if.h.
IFF_RUNNING
#define IFF_RUNNING 0x40
Definition at line 94 of file if.h.
IFF_SLAVE
#define IFF_SLAVE 0x800
Definition at line 99 of file if.h.
IFF_UP
#define IFF_UP 0x1
Definition at line 88 of file if.h.
IFF_VOLATILE
#define IFF_VOLATILE
Value:
        (IFF_LOOPBACK|IFF_POINTOPOINT|IFF_BROADCAST| \
        IFF_ECHO|IFF_MASTER|IFF_SLAVE|IFF_RUNNING|IFF_LOWER_UP|IFF_DORMANT)
Definition at line 107 of file if.h.
IFNAMSIZ
#define IFNAMSIZ IF_NAMESIZE
Definition at line 12 of file if.h.
ifr_addr
#define ifr_addr ifr_ifru.ifru_addr
Definition at line 53 of file if.h.
ifr_bandwidth
#define ifr_bandwidth ifr_ifru.ifru_ivalue
Definition at line 64 of file if.h.
ifr_broadaddr
#define ifr_broadaddr ifr_ifru.ifru_broadaddr
Definition at line 55 of file if.h.
ifr_data
#define ifr_data ifr_ifru.ifru_data
Definition at line 62 of file if.h.
ifr_dstaddr
#define ifr_dstaddr ifr_ifru.ifru_dstaddr
Definition at line 54 of file if.h.
ifr_flags
#define ifr_flags ifr_ifru.ifru_flags
Definition at line 57 of file if.h.
ifr_hwaddr
#define ifr_hwaddr ifr_ifru.ifru_hwaddr
Definition at line 52 of file if.h.
ifr_ifindex
#define ifr_ifindex ifr_ifru.ifru_ivalue
Definition at line 63 of file if.h.
ifr_map
#define ifr_map ifr_ifru.ifru_map
Definition at line 60 of file if.h.
ifr_metric
#define ifr_metric ifr_ifru.ifru_ivalue
Definition at line 58 of file if.h.
ifr_mtu
#define ifr_mtu ifr_ifru.ifru_mtu
Definition at line 59 of file if.h.
ifr_name
#define ifr_name ifr_ifrn.ifrn_name
Definition at line 51 of file if.h.
ifr_netmask
#define ifr_netmask ifr_ifru.ifru_netmask
Definition at line 56 of file if.h.
ifr_newname
#define ifr_newname ifr_ifru.ifru_newname
Definition at line 66 of file if.h.
ifr_qlen
#define ifr_qlen ifr_ifru.ifru_ivalue
Definition at line 65 of file if.h.
ifr_slave
#define ifr_slave ifr_ifru.ifru_slave
Definition at line 61 of file if.h.
Function Documentation
if_freenameindex()
void if_freenameindex (struct if_nameindex *)
Definition at line 9 of file net-if-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: if_freenameindex is a no-op" << frg::endlog;
 }
References mlibc::infoLogger.
if_indextoname()
char* if_indextoname (unsigned int index, char * name)
Definition at line 13 of file net-if-stubs.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_if_indextoname, NULL);
     if(int e = sysdep(index, name); e) {
         errno = e;
         return NULL;
     }
     return name;
 }
References errno, index(), MLIBC_CHECK_OR_ENOSYS, name, NULL, and mlibc::sys_if_indextoname().
Referenced by main().
if_nameindex()
struct if_nameindex* if_nameindex (void)
Definition at line 24 of file net-if-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: if_nameindex() is a no-op" << frg::endlog;
     errno = ENOSYS;
     return NULL;
 }
References ENOSYS, errno, mlibc::infoLogger, and NULL.
if_nametoindex()
unsigned int if_nametoindex (const char * name)
Definition at line 30 of file net-if-stubs.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_if_nametoindex, 0);
     unsigned int ret = 0;
     if(int e = sysdep(name, &ret); e) {
         errno = e;
         return 0;
     }
     return ret;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, name, ret, and mlibc::sys_if_nametoindex().
Referenced by main().