Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/wi_stuff.h File Reference
wi_stuff.h File Reference
#include "doomdef.h"
Enumerations
enum stateenum_t { NoState = -1 , StatCount , ShowNextLoc }
Functions
void WI_Ticker (void)
void WI_Drawer (void)
void WI_Start (wbstartstruct_t *wbstartstruct)
void WI_End (void)
Enumeration Type Documentation
stateenum_t
enum stateenum_t
Enumerator
NoState
StatCount
ShowNextLoc
Definition at line 28 of file wi_stuff.h.
 {
     NoState = -1,
     StatCount,
     ShowNextLoc,
 } stateenum_t;
Function Documentation
WI_Drawer()
void WI_Drawer (void)
Definition at line 1752 of file wi_stuff.c.
 {
     switch (state)
     {
       case StatCount:
     if (deathmatch)
         WI_drawDeathmatchStats();
     else if (netgame)
         WI_drawNetgameStats();
     else
         WI_drawStats();
     break;
       case ShowNextLoc:
     WI_drawShowNextLoc();
     break;
       case NoState:
     WI_drawNoState();
     break;
     }
 }
References deathmatch, netgame, NoState, ShowNextLoc, StatCount, state, WI_drawDeathmatchStats(), WI_drawNetgameStats(), WI_drawNoState(), WI_drawShowNextLoc(), and WI_drawStats().
Referenced by D_Display().
WI_End()
void WI_End (void)
Definition at line 740 of file wi_stuff.c.
 {
     void WI_unloadData(void);
     WI_unloadData();
 }
References WI_unloadData().
Referenced by G_Ticker().
WI_Start()
void WI_Start (wbstartstruct_t * wbstartstruct)
Definition at line 1818 of file wi_stuff.c.
 {
     WI_initVariables(wbstartstruct);
     WI_loadData();
     if (deathmatch)
     WI_initDeathmatchStats();
     else if (netgame)
     WI_initNetgameStats();
     else
     WI_initStats();
 }
References deathmatch, netgame, WI_initDeathmatchStats(), WI_initNetgameStats(), WI_initStats(), WI_initVariables(), and WI_loadData().
Referenced by G_DoCompleted().
WI_Ticker()
void WI_Ticker (void)
Definition at line 1514 of file wi_stuff.c.
 {
     // counter for general background animation
     bcnt++;
     if (bcnt == 1)
     {
     // intermission music
     if ( gamemode == commercial )
       S_ChangeMusic(mus_dm2int, true);
     else
       S_ChangeMusic(mus_inter, true);
     }
     WI_checkForAccelerate();
     switch (state)
     {
       case StatCount:
     if (deathmatch) WI_updateDeathmatchStats();
     else if (netgame) WI_updateNetgameStats();
     else WI_updateStats();
     break;
       case ShowNextLoc:
     WI_updateShowNextLoc();
     break;
       case NoState:
     WI_updateNoState();
     break;
     }
 }
References bcnt, commercial, deathmatch, gamemode, mus_dm2int, mus_inter, netgame, NoState, S_ChangeMusic(), ShowNextLoc, StatCount, state, WI_checkForAccelerate(), WI_updateDeathmatchStats(), WI_updateNetgameStats(), WI_updateNoState(), WI_updateShowNextLoc(), and WI_updateStats().
Referenced by G_Ticker().