Fennix Userspace: Userspace/musl/src/linux/clock_adjtime.c File Reference
clock_adjtime.c File Reference
#include <sys/timex.h>
#include <time.h>
#include <errno.h>
#include "syscall.h"
Data Structures
struct ktimex64
struct ktimex
Macros
#define IS32BIT(x) !((x)+0x80000000ULL>>32)
Functions
int clock_adjtime (clockid_t clock_id, struct timex *utx)
Data Structure Documentation
ktimex64
struct ktimex64
Definition at line 8 of file clock_adjtime.c.
Data Fields
int __pad0__:32
int __pad1__:32
int __pad2__:32
int __padding[11]
long long calcnt
long long constant
long long errcnt
long long esterror
long long freq
long long jitcnt
long long jitter
long long maxerror
unsigned modes
long long offset
long long ppsfreq
long long precision
int shift
long long stabil
int status
long long stbcnt
int tai
long long tick
long long time_sec
long long time_usec
long long tolerance
ktimex
struct ktimex
Definition at line 24 of file clock_adjtime.c.
Data Fields
int __padding[11]
long calcnt
long constant
long errcnt
long esterror
long freq
long jitcnt
long jitter
long maxerror
unsigned modes
long offset
long ppsfreq
long precision
int shift
long stabil
int status
long stbcnt
int tai
long tick
long time_sec
long time_usec
long tolerance
Macro Definition Documentation
IS32BIT
#define IS32BIT (x) !((x)+0x80000000ULL>>32)
Definition at line 6 of file clock_adjtime.c.
Function Documentation
clock_adjtime()
int clock_adjtime (clockid_t clock_id, struct timex * utx)
Definition at line 37 of file clock_adjtime.c.
 {
     int r = -ENOSYS;
 #ifdef SYS_clock_adjtime64
     struct ktimex64 ktx = {
         .modes = utx->modes,
         .offset = utx->offset,
         .freq = utx->freq,
         .maxerror = utx->maxerror,
         .esterror = utx->esterror,
         .status = utx->status,
         .constant = utx->constant,
         .precision = utx->precision,
         .tolerance = utx->tolerance,
         .time_sec = utx->time.tv_sec,
         .time_usec = utx->time.tv_usec,
         .tick = utx->tick,
         .ppsfreq = utx->ppsfreq,
         .jitter = utx->jitter,
         .shift = utx->shift,
         .stabil = utx->stabil,
         .jitcnt = utx->jitcnt,
         .calcnt = utx->calcnt,
         .errcnt = utx->errcnt,
         .stbcnt = utx->stbcnt,
         .tai = utx->tai,
     };
     r = __syscall(SYS_clock_adjtime64, clock_id, &ktx);
     if (r>=0) {
         utx->modes = ktx.modes;
         utx->offset = ktx.offset;
         utx->freq = ktx.freq;
         utx->maxerror = ktx.maxerror;
         utx->esterror = ktx.esterror;
         utx->status = ktx.status;
         utx->constant = ktx.constant;
         utx->precision = ktx.precision;
         utx->tolerance = ktx.tolerance;
         utx->time.tv_sec = ktx.time_sec;
         utx->time.tv_usec = ktx.time_usec;
         utx->tick = ktx.tick;
         utx->ppsfreq = ktx.ppsfreq;
         utx->jitter = ktx.jitter;
         utx->shift = ktx.shift;
         utx->stabil = ktx.stabil;
         utx->jitcnt = ktx.jitcnt;
         utx->calcnt = ktx.calcnt;
         utx->errcnt = ktx.errcnt;
         utx->stbcnt = ktx.stbcnt;
         utx->tai = ktx.tai;
     }
     if (SYS_clock_adjtime == SYS_clock_adjtime64 || r!=-ENOSYS)
         return __syscall_ret(r);
     if ((utx->modes & ADJ_SETOFFSET) && !IS32BIT(utx->time.tv_sec))
         return __syscall_ret(-ENOTSUP);
 #endif
     if (sizeof(time_t) > sizeof(long)) {
         struct ktimex ktx = {
             .modes = utx->modes,
             .offset = utx->offset,
             .freq = utx->freq,
             .maxerror = utx->maxerror,
             .esterror = utx->esterror,
             .status = utx->status,
             .constant = utx->constant,
             .precision = utx->precision,
             .tolerance = utx->tolerance,
             .time_sec = utx->time.tv_sec,
             .time_usec = utx->time.tv_usec,
             .tick = utx->tick,
             .ppsfreq = utx->ppsfreq,
             .jitter = utx->jitter,
             .shift = utx->shift,
             .stabil = utx->stabil,
             .jitcnt = utx->jitcnt,
             .calcnt = utx->calcnt,
             .errcnt = utx->errcnt,
             .stbcnt = utx->stbcnt,
             .tai = utx->tai,
         };
 #ifdef SYS_adjtimex
         if (clock_id==CLOCK_REALTIME) r = __syscall(SYS_adjtimex, &ktx);
         else
 #endif
         r = __syscall(SYS_clock_adjtime, clock_id, &ktx);
         if (r>=0) {
             utx->modes = ktx.modes;
             utx->offset = ktx.offset;
             utx->freq = ktx.freq;
             utx->maxerror = ktx.maxerror;
             utx->esterror = ktx.esterror;
             utx->status = ktx.status;
             utx->constant = ktx.constant;
             utx->precision = ktx.precision;
             utx->tolerance = ktx.tolerance;
             utx->time.tv_sec = ktx.time_sec;
             utx->time.tv_usec = ktx.time_usec;
             utx->tick = ktx.tick;
             utx->ppsfreq = ktx.ppsfreq;
             utx->jitter = ktx.jitter;
             utx->shift = ktx.shift;
             utx->stabil = ktx.stabil;
             utx->jitcnt = ktx.jitcnt;
             utx->calcnt = ktx.calcnt;
             utx->errcnt = ktx.errcnt;
             utx->stbcnt = ktx.stbcnt;
             utx->tai = ktx.tai;
         }
         return __syscall_ret(r);
     }
 #ifdef SYS_adjtimex
     if (clock_id==CLOCK_REALTIME) return syscall(SYS_adjtimex, utx);
 #endif
     return syscall(SYS_clock_adjtime, clock_id, utx);
 }
References __syscall, __syscall_ret(), ADJ_SETOFFSET, timex::calcnt, ktimex64::calcnt, ktimex::calcnt, CLOCK_REALTIME, timex::constant, ktimex64::constant, ktimex::constant, ENOSYS, ENOTSUP, timex::errcnt, ktimex64::errcnt, ktimex::errcnt, timex::esterror, ktimex64::esterror, ktimex::esterror, timex::freq, ktimex64::freq, ktimex::freq, IS32BIT, timex::jitcnt, ktimex64::jitcnt, ktimex::jitcnt, timex::jitter, ktimex64::jitter, ktimex::jitter, timex::maxerror, ktimex64::maxerror, ktimex::maxerror, timex::modes, ktimex64::modes, ktimex::modes, timex::offset, ktimex64::offset, ktimex::offset, timex::ppsfreq, ktimex64::ppsfreq, ktimex::ppsfreq, timex::precision, ktimex64::precision, ktimex::precision, r, timex::shift, ktimex64::shift, ktimex::shift, timex::stabil, ktimex64::stabil, ktimex::stabil, timex::status, ktimex64::status, ktimex::status, timex::stbcnt, ktimex64::stbcnt, ktimex::stbcnt, SYS_clock_adjtime, SYS_clock_adjtime64, syscall(), timex::tai, ktimex64::tai, ktimex::tai, timex::tick, ktimex64::tick, ktimex::tick, timex::time, ktimex64::time_sec, ktimex::time_sec, ktimex64::time_usec, ktimex::time_usec, timex::tolerance, ktimex64::tolerance, ktimex::tolerance, timeval::tv_sec, and timeval::tv_usec.
Referenced by __clock_adjtime32(), and adjtimex().