Fennix: Userspace/apps/base/busybox/libbb/write.c File Reference
write.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC xopen_xwrite_close (const char *file, const char *str)
Function Documentation
xopen_xwrite_close()
void FAST_FUNC xopen_xwrite_close (const char * file, const char * str)
Definition at line 13 of file write.c.
 {
     int fd = xopen(file, O_WRONLY);
     xwrite_str(fd, str);
     close(fd);
 }
References close(), fd, O_WRONLY, str, xopen(), and xwrite_str().
Referenced by rtcwake_main(), unshare_main(), and wall_main().