Fennix: Userspace/mlibc/sysdeps/lyre/generic/thread.cpp File Reference
thread.cpp File Reference
#include <sys/mman.h>
#include <mlibc/debug.hpp>
#include <errno.h>
#include <mlibc/all-sysdeps.hpp>
#include <bits/ensure.h>
#include <mlibc/tcb.hpp>
Namespaces
mlibc
Macros
#define DEFAULT_STACK 0x400000
Functions
void __mlibc_thread_trampoline (void *(*fn)(void *), Tcb *tcb, void *arg)
int mlibc::sys_prepare_stack (void **stack, void *entry, void *user_arg, void *tcb, size_t *stack_size, size_t *guard_size)
Macro Definition Documentation
DEFAULT_STACK
#define DEFAULT_STACK 0x400000
Definition at line 25 of file thread.cpp.
Function Documentation
__mlibc_thread_trampoline()
void __mlibc_thread_trampoline (void *(*)(void *) fn, Tcb * tcb, void * arg)
Definition at line 8 of file thread.cpp.
{
     if (mlibc::sys_tcb_set(tcb)) {
         __ensure(!"failed to set tcb for new thread");
     }
     while (__atomic_load_n(&tcb->tid, __ATOMIC_RELAXED) == 0) {
         mlibc::sys_futex_wait(&tcb->tid, 0, nullptr);
     }
     tcb->returnValue = fn(arg);
     __atomic_store_n(&tcb->didExit, 1, __ATOMIC_RELEASE);
     mlibc::sys_futex_wake(&tcb->didExit);
     mlibc::sys_thread_exit();
 }
References __ensure, mlibc::arg, Tcb::didExit, Tcb::returnValue, mlibc::sys_futex_wait(), mlibc::sys_futex_wake(), mlibc::sys_tcb_set(), mlibc::sys_thread_exit(), and Tcb::tid.