Fennix: Userspace/musl/src/signal/sigfillset.c File Reference
sigfillset.c File Reference
#include <signal.h>
#include <limits.h>
Functions
int sigfillset (sigset_t *set)
Function Documentation
sigfillset()
int sigfillset (sigset_t * set)
Definition at line 4 of file sigfillset.c.
 {
 #if ULONG_MAX == 0xffffffff
     set->__bits[0] = 0x7ffffffful;
     set->__bits[1] = 0xfffffffcul;
     if (_NSIG > 65) {
         set->__bits[2] = 0xfffffffful;
         set->__bits[3] = 0xfffffffful;
     }
 #else
     set->__bits[0] = 0xfffffffc7ffffffful;
     if (_NSIG > 65) set->__bits[1] = 0xfffffffffffffffful;
 #endif
     return 0;
 }
References _NSIG.
Referenced by __aio_get_queue(), aio_cancel(), forkpty(), init_main(), lio_listio(), mq_notify(), setsignal(), sigprocmask_allsigs(), submit(), and waitproc().