Fennix: Userspace/musl/src/include/sys/mman.h File Reference
mman.h File Reference
#include "../../../include/sys/mman.h"
Functions
hidden void __vm_wait (void)
hidden void __vm_lock (void)
hidden void __vm_unlock (void)
hidden void * __mmap (void *, size_t, int, int, int, off_t)
hidden int __munmap (void *, size_t)
hidden void * __mremap (void *, size_t, size_t, int,...)
hidden int __madvise (void *, size_t, int)
hidden int __mprotect (void *, size_t, int)
hidden const unsigned char * __map_file (const char *, size_t *)
hidden char * __shm_mapname (const char *, char *)
Function Documentation
__madvise()
hidden int __madvise (void * addr, size_t len, int advice)
Definition at line 4 of file madvise.c.
 {
     return syscall(SYS_madvise, addr, len, advice);
 }
References addr, len, and syscall().
Referenced by __bin_chunk().
__map_file()
hidden const unsigned char* __map_file (const char * pathname, size_t * size)
Definition at line 6 of file __map_file.c.
 {
     struct stat st;
     const unsigned char *map = MAP_FAILED;
     int fd = sys_open(pathname, O_RDONLY|O_CLOEXEC|O_NONBLOCK);
     if (fd < 0) return 0;
     if (!__fstat(fd, &st)) {
         map = __mmap(0, st.st_size, PROT_READ, MAP_SHARED, fd, 0);
         *size = st.st_size;
     }
     __syscall(SYS_close, fd);
     return map == MAP_FAILED ? 0 : map;
 }
References __fstat(), __mmap(), __syscall, map, MAP_FAILED, MAP_SHARED, O_CLOEXEC, O_NONBLOCK, O_RDONLY, PROT_READ, size, and sys_open.
Referenced by __get_locale(), dcngettext(), do_catopen(), and do_tzset().
__mmap()
hidden void* __mmap (void * start, size_t len, int prot, int flags, int fd, off_t off)
Definition at line 14 of file mmap.c.
 {
     long ret;
     if (off & OFF_MASK) {
         errno = EINVAL;
         return MAP_FAILED;
     }
     if (len >= PTRDIFF_MAX) {
         errno = ENOMEM;
         return MAP_FAILED;
     }
     if (flags & MAP_FIXED) {
         __vm_wait();
     }
 #ifdef SYS_mmap2
     ret = __syscall(SYS_mmap2, start, len, prot, flags, fd, off/UNIT);
 #else
     ret = __syscall(SYS_mmap, start, len, prot, flags, fd, off);
 #endif
     /* Fixup incorrect EPERM from kernel. */
     if (ret == -EPERM && !start && (flags&MAP_ANON) && !(flags&MAP_FIXED))
         ret = -ENOMEM;
     return (void *)__syscall_ret(ret);
 }
References __syscall, __syscall_ret(), __vm_wait(), EINVAL, ENOMEM, EPERM, errno, flags, len, MAP_ANON, MAP_FAILED, MAP_FIXED, mlibc::off, OFF_MASK, PTRDIFF_MAX, ret, start(), SYS_mmap2, and UNIT.
Referenced by __bin_chunk(), __expand_heap(), __map_file(), __pthread_create(), __simple_malloc(), and malloc().
__mprotect()
hidden int __mprotect (void * addr, size_t len, int prot)
Definition at line 5 of file mprotect.c.
 {
     size_t start, end;
     start = (size_t)addr & -PAGE_SIZE;
     end = (size_t)((char *)addr + len + PAGE_SIZE-1) & -PAGE_SIZE;
     return syscall(SYS_mprotect, start, end-start, prot);
 }
References addr, len, PAGE_SIZE, start(), and syscall().
Referenced by __pthread_create().
__mremap()
hidden void* __mremap (void * old_addr, size_t old_len, size_t new_len, int flags, ...)
Definition at line 12 of file mremap.c.
 {
     va_list ap;
     void *new_addr = 0;
     if (new_len >= PTRDIFF_MAX) {
         errno = ENOMEM;
         return MAP_FAILED;
     }
     if (flags & MREMAP_FIXED) {
         __vm_wait();
         va_start(ap, flags);
         new_addr = va_arg(ap, void *);
         va_end(ap);
     }
     return (void *)syscall(SYS_mremap, old_addr, old_len, new_len, flags, new_addr);
 }
References __vm_wait(), ENOMEM, errno, flags, MAP_FAILED, MREMAP_FIXED, PTRDIFF_MAX, syscall(), va_arg, va_end(), and va_start().
Referenced by realloc().
__munmap()
hidden int __munmap (void * start, size_t len)
Definition at line 7 of file munmap.c.
 {
     __vm_wait();
     return syscall(SYS_munmap, start, len);
 }
References __vm_wait(), len, start(), and syscall().
Referenced by __get_locale(), __pthread_create(), __pthread_timedjoin_np(), dcngettext(), do_tzset(), and unmap_chunk().
__shm_mapname()
hidden char* __shm_mapname (const char * name, char * buf)
Definition at line 9 of file shm_open.c.
 {
     char *p;
     while (*name == '/') name++;
     if (*(p = __strchrnul(name, '/')) || p==name ||
         (p-name <= 2 && name[0]=='.' && p[-1]=='.')) {
         errno = EINVAL;
         return 0;
     }
     if (p-name > NAME_MAX) {
         errno = ENAMETOOLONG;
         return 0;
     }
     memcpy(buf, "/dev/shm/", 9);
     memcpy(buf+9, name, p-name+1);
     return buf;
 }
References __strchrnul(), buf, EINVAL, ENAMETOOLONG, errno, memcpy, name, NAME_MAX, and p.
Referenced by sem_open(), shm_open(), and shm_unlink().
__vm_lock()
hidden void __vm_lock (void)
Definition at line 14 of file vmlock.c.
 {
     a_inc(vmlock);
 }
References a_inc, and vmlock.
Referenced by __pthread_exit(), __pthread_mutex_unlock(), and pshared_barrier_wait().
__vm_unlock()
hidden void __vm_unlock (void)
Definition at line 19 of file vmlock.c.
 {
     if (a_fetch_add(vmlock, -1)==1 && vmlock[1])
         __wake(vmlock, -1, 1);
 }
References __wake(), a_fetch_add, and vmlock.
Referenced by __pthread_exit(), __pthread_mutex_unlock(), and pshared_barrier_wait().
__vm_wait()
hidden void __vm_wait (void)
Definition at line 7 of file vmlock.c.
 {
     int tmp;
     while ((tmp=vmlock[0]))
         __wait(vmlock, vmlock+1, tmp, 1);
 }
References __wait(), and vmlock.
Referenced by __mmap(), __mremap(), __munmap(), __pthread_exit(), pthread_barrier_destroy(), and pthread_mutex_destroy().