Fennix: Userspace/musl/src/complex/catan.c File Reference
catan.c File Reference
#include "complex_impl.h"
Macros
#define MAXNUM 1.0e308
Functions
static double _redupi (double x)
double complex catan (double complex z)
Variables
static const double DP1 = 3.14159265160560607910E0
static const double DP2 = 1.98418714791870343106E-9
static const double DP3 = 1.14423774522196636802E-17
Macro Definition Documentation
MAXNUM
#define MAXNUM 1.0e308
Definition at line 63 of file catan.c.
Function Documentation
_redupi()
static double _redupi (double x) static
Definition at line 69 of file catan.c.
 {
     double t;
     long i;
     t = x/M_PI;
     if (t >= 0.0)
         t += 0.5;
     else
         t -= 0.5;
     i = t;  /* the multiple */
     t = i;
     t = ((x - t * DP1) - t * DP2) - t * DP3;
     return t;
 }
References DP1, DP2, DP3, i, and x.
Referenced by catan().
catan()
double complex catan (double complex z)
Definition at line 86 of file catan.c.
 {
     double complex w;
     double a, t, x, x2, y;
     x = creal(z);
     y = cimag(z);
     x2 = x * x;
     a = 1.0 - x2 - (y * y);
     t = 0.5 * atan2(2.0 * x, a);
     w = _redupi(t);
     t = y - 1.0;
     a = x2 + (t * t);
     t = y + 1.0;
     a = (x2 + t * t)/a;
     w = CMPLX(w, 0.25 * log(a));
     return w;
 }
References _redupi(), atan2, cimag, CMPLX, complex, creal, log, x, and y.
Referenced by catanh().
Variable Documentation
DP1
const double DP1 = 3.14159265160560607910E0 static
Definition at line 65 of file catan.c.
Referenced by _redupi().
DP2
const double DP2 = 1.98418714791870343106E-9 static
Definition at line 66 of file catan.c.
Referenced by _redupi().
DP3
const double DP3 = 1.14423774522196636802E-17 static
Definition at line 67 of file catan.c.
Referenced by _redupi().