Fennix Userspace: Userspace/musl/src/unistd/pipe2.c File Reference
pipe2.c File Reference
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include "syscall.h"
Functions
int pipe2 (int fd[2], int flag)
Function Documentation
pipe2()
int pipe2 (int fd[2], int flag)
Definition at line 6 of file pipe2.c.
 {
     if (!flag) return pipe(fd);
     int ret = __syscall(SYS_pipe2, fd, flag);
     if (ret != -ENOSYS) return __syscall_ret(ret);
     if (flag & ~(O_CLOEXEC|O_NONBLOCK)) return __syscall_ret(-EINVAL);
     ret = pipe(fd);
     if (ret) return ret;
     if (flag & O_CLOEXEC) {
         __syscall(SYS_fcntl, fd[0], F_SETFD, FD_CLOEXEC);
         __syscall(SYS_fcntl, fd[1], F_SETFD, FD_CLOEXEC);
     }
     if (flag & O_NONBLOCK) {
         __syscall(SYS_fcntl, fd[0], F_SETFL, O_NONBLOCK);
         __syscall(SYS_fcntl, fd[1], F_SETFL, O_NONBLOCK);
     }
     return 0;
 }
References __syscall, __syscall_ret(), EINVAL, ENOSYS, F_SETFD, F_SETFL, fd, FD_CLOEXEC, O_CLOEXEC, O_NONBLOCK, and pipe().
Referenced by do_wordexp(), faccessat(), forkpty(), popen(), and posix_spawn().