Fennix: Userspace/apps/base/bash/lib/sh/fmtulong.c File Reference
fmtulong.c File Reference
#include <bashansi.h>
#include <chartypes.h>
#include <errno.h>
#include <bashintl.h>
#include "stdc.h"
#include <typemax.h>
Macros
#define x_digs "0123456789abcdef"
#define X_digs "0123456789ABCDEF"
#define FMTCHAR(x)
#define FL_PREFIX 0x01 /* add 0x, 0X, or 0 prefix as appropriate */
#define FL_ADDBASE 0x02 /* add base# prefix to converted value */
#define FL_HEXUPPER 0x04 /* use uppercase when converting to hex */
#define FL_UNSIGNED 0x08 /* don't add any sign */
#define LONG long
#define UNSIGNED_LONG unsigned long
Functions
char * fmtulong (UNSIGNED_LONG ui, int base, char *buf, size_t len, int flags)
Variables
int errno
Macro Definition Documentation
FL_ADDBASE
#define FL_ADDBASE 0x02 /* add base# prefix to converted value */
Definition at line 70 of file fmtulong.c.
FL_HEXUPPER
#define FL_HEXUPPER 0x04 /* use uppercase when converting to hex */
Definition at line 71 of file fmtulong.c.
FL_PREFIX
#define FL_PREFIX 0x01 /* add 0x, 0X, or 0 prefix as appropriate */
Definition at line 69 of file fmtulong.c.
FL_UNSIGNED
#define FL_UNSIGNED 0x08 /* don't add any sign */
Definition at line 72 of file fmtulong.c.
FMTCHAR
#define FMTCHAR (x)
Value:
  ((x) < 10) ? (x) + '0' \
         : (((x) < 36) ? (x) - 10 + 'a' \
               : (((x) < 62) ? (x) - 36 + 'A' \
                     : (((x) == 62) ? '@' : '_')))
Definition at line 62 of file fmtulong.c.
LONG
#define LONG long
Definition at line 76 of file fmtulong.c.
UNSIGNED_LONG
#define UNSIGNED_LONG unsigned long
Definition at line 77 of file fmtulong.c.
x_digs
#define x_digs "0123456789abcdef"
Definition at line 57 of file fmtulong.c.
X_digs
#define X_digs "0123456789ABCDEF"
Definition at line 58 of file fmtulong.c.
Function Documentation
fmtulong()
char* fmtulong (UNSIGNED_LONG ui, int base, char * buf, size_t len, int flags)
Definition at line 84 of file fmtulong.c.
 {
   char *p;
   int sign;
   LONG si;
   if (base == 0)
     base = 10;
   if (base < 2 || base > 64)
     {
 #if 1
       /* XXX - truncation possible with long translation */
       strncpy (buf, _("invalid base"), len - 1);
       buf[len-1] = '\0';
       errno = EINVAL;
       return (p = buf);
 #else
       base = 10;
 #endif
     }
   sign = 0;
   if ((flags & FL_UNSIGNED) == 0 && (LONG)ui < 0)
     {
       ui = -ui;
       sign = '-';
     }
   p = buf + len - 2;
   p[1] = '\0';
   /* handle common cases explicitly */
   switch (base)
     {
     case 10:
       if (ui < 10)
     {
       *p-- = TOCHAR (ui);
       break;
     }
       /* Favor signed arithmetic over unsigned arithmetic; it is faster on
      many machines. */
       if ((LONG)ui < 0)
     {
       *p-- = TOCHAR (ui % 10);
       si = ui / 10;
     }
       else
         si = ui;
       do
     *p-- = TOCHAR (si % 10);
       while (si /= 10);
       break;
     case 8:
       do
     *p-- = TOCHAR (ui & 7);
       while (ui >>= 3);
       break;
     case 16:
       do
     *p-- = (flags & FL_HEXUPPER) ? X_digs[ui & 15] : x_digs[ui & 15];
       while (ui >>= 4);
       break;
     case 2:
       do
     *p-- = TOCHAR (ui & 1);
       while (ui >>= 1);
       break;
     default:
       do
     *p-- = FMTCHAR (ui % base);
       while (ui /= base);
       break;
     }
   if ((flags & FL_PREFIX) && (base == 8 || base == 16))
     {
       if (base == 16)
     {
       *p-- = (flags & FL_HEXUPPER) ? 'X' : 'x';
       *p-- = '0';
     }
       else if (p[1] != '0')
     *p-- = '0';
     }
   else if ((flags & FL_ADDBASE) && base != 10)
     {
       *p-- = '#';
       *p-- = TOCHAR (base % 10);
       if (base > 10)
         *p-- = TOCHAR (base / 10);
     }
   if (sign)
     *p-- = '-';
   return (p + 1);
 }
References _, base, buf, EINVAL, errno, FL_ADDBASE, FL_HEXUPPER, FL_PREFIX, FL_UNSIGNED, flags, FMTCHAR, len, p, strncpy(), TOCHAR, x_digs, and X_digs.
Referenced by accept_bind_variable(), bind_var_to_int(), number(), pointer(), and sort_index().
Variable Documentation
errno
int errno extern
Referenced by fmtulong().