Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/i_sound.c File Reference
i_sound.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "config.h"
#include "doomfeatures.h"
#include "doomtype.h"
#include "i_sound.h"
#include "i_video.h"
#include "m_argv.h"
#include "m_config.h"
Functions
void I_InitTimidityConfig (void)
static boolean SndDeviceInList (snddevice_t device, snddevice_t *list, int len)
static void InitSfxModule (boolean use_sfx_prefix)
static void InitMusicModule (void)
void I_InitSound (boolean use_sfx_prefix)
void I_ShutdownSound (void)
int I_GetSfxLumpNum (sfxinfo_t *sfxinfo)
void I_UpdateSound (void)
static void CheckVolumeSeparation (int *vol, int *sep)
void I_UpdateSoundParams (int channel, int vol, int sep)
int I_StartSound (sfxinfo_t *sfxinfo, int channel, int vol, int sep)
void I_StopSound (int channel)
boolean I_SoundIsPlaying (int channel)
void I_PrecacheSounds (sfxinfo_t *sounds, int num_sounds)
void I_InitMusic (void)
void I_ShutdownMusic (void)
void I_SetMusicVolume (int volume)
void I_PauseSong (void)
void I_ResumeSong (void)
void * I_RegisterSong (void *data, int len)
void I_UnRegisterSong (void *handle)
void I_PlaySong (void *handle, boolean looping)
void I_StopSong (void)
boolean I_MusicIsPlaying (void)
void I_BindSoundVariables (void)
Variables
int snd_samplerate = 44100
int snd_cachesize = 64 * 1024 * 1024
int snd_maxslicetime_ms = 28
char * snd_musiccmd = ""
static sound_module_t * sound_module = NULL
static music_module_t * music_module = NULL
int snd_musicdevice = SNDDEVICE_SB
int snd_sfxdevice = SNDDEVICE_SB
sound_module_t sound_pcsound_module
music_module_t music_opl_module
int opl_io_port
char * timidity_cfg_path
static int snd_sbport = 0
static int snd_sbirq = 0
static int snd_sbdma = 0
static int snd_mport = 0
static sound_module_t * sound_modules []
Function Documentation
CheckVolumeSeparation()
static void CheckVolumeSeparation (int * vol, int * sep) static
Definition at line 256 of file i_sound.c.
 {
     if (*sep < 0)
     {
         *sep = 0;
     }
     else if (*sep > 254)
     {
         *sep = 254;
     }
     if (*vol < 0)
     {
         *vol = 0;
     }
     else if (*vol > 127)
     {
         *vol = 127;
     }
 }
Referenced by I_StartSound(), and I_UpdateSoundParams().
I_BindSoundVariables()
void I_BindSoundVariables (void)
Definition at line 413 of file i_sound.c.
 {
     extern int use_libsamplerate;
     extern float libsamplerate_scale;
     M_BindVariable("snd_musicdevice",   &snd_musicdevice);
     M_BindVariable("snd_sfxdevice",     &snd_sfxdevice);
     M_BindVariable("snd_sbport",        &snd_sbport);
     M_BindVariable("snd_sbirq",         &snd_sbirq);
     M_BindVariable("snd_sbdma",         &snd_sbdma);
     M_BindVariable("snd_mport",         &snd_mport);
     M_BindVariable("snd_maxslicetime_ms", &snd_maxslicetime_ms);
     M_BindVariable("snd_musiccmd",      &snd_musiccmd);
     M_BindVariable("snd_samplerate",    &snd_samplerate);
     M_BindVariable("snd_cachesize",     &snd_cachesize);
 #ifdef FEATURE_SOUND
     M_BindVariable("use_libsamplerate",   &use_libsamplerate);
     M_BindVariable("libsamplerate_scale", &libsamplerate_scale);
 #endif
     // Before SDL_mixer version 1.2.11, MIDI music caused the game
     // to crash when it looped.  If this is an old SDL_mixer version,
     // disable MIDI.
 }
References M_BindVariable(), snd_cachesize, snd_maxslicetime_ms, snd_mport, snd_musiccmd, snd_musicdevice, snd_samplerate, snd_sbdma, snd_sbirq, snd_sbport, and snd_sfxdevice.
Referenced by D_BindVariables().
I_GetSfxLumpNum()
int I_GetSfxLumpNum (sfxinfo_t * sfxinfo)
Definition at line 231 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         return sound_module->GetSfxLumpNum(sfxinfo);
     }
     else
     {
         return 0;
     }
 }
References sound_module_t::GetSfxLumpNum, NULL, and sound_module.
Referenced by S_StartSound().
I_InitMusic()
void I_InitMusic (void)
Definition at line 327 of file i_sound.c.
 {
     if(music_module != NULL)
     {
         music_module->Init();
     }
 }
References music_module_t::Init, music_module, and NULL.
Referenced by D_DoomMain().
I_InitSound()
void I_InitSound (boolean use_sfx_prefix)
Definition at line 162 of file i_sound.c.
 {
     boolean nosound, nosfx, nomusic;
     // @vanilla
     //
     // Disable all sound output.
     //
     nosound = M_CheckParm("-nosound") > 0;
     // @vanilla
     //
     // Disable sound effects.
     //
     nosfx = M_CheckParm("-nosfx") > 0;
     // @vanilla
     //
     // Disable music.
     //
     nomusic = M_CheckParm("-nomusic") > 0;
     // Initialize the sound and music subsystems.
     if (!nosound && !screensaver_mode)
     {
         // This is kind of a hack. If native MIDI is enabled, set up
         // the TIMIDITY_CFG environment variable here before SDL_mixer
         // is opened.
         if (!nomusic
          && (snd_musicdevice == SNDDEVICE_GENMIDI
           || snd_musicdevice == SNDDEVICE_GUS))
         {
             I_InitTimidityConfig();
         }
         if (!nosfx)
         {
             InitSfxModule(use_sfx_prefix);
         }
         if (!nomusic)
         {
             InitMusicModule();
         }
     }
 }
References I_InitTimidityConfig(), InitMusicModule(), InitSfxModule(), M_CheckParm(), screensaver_mode, snd_musicdevice, SNDDEVICE_GENMIDI, and SNDDEVICE_GUS.
Referenced by D_DoomMain().
I_InitTimidityConfig()
void I_InitTimidityConfig (void)
Definition at line 45 of file dummy.c.
 {
 }
Referenced by I_InitSound().
I_MusicIsPlaying()
boolean I_MusicIsPlaying (void)
Definition at line 400 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         return music_module->MusicIsPlaying();
     }
     else
     {
         return false;
     }
 }
References music_module, music_module_t::MusicIsPlaying, and NULL.
Referenced by S_MusicPlaying().
I_PauseSong()
void I_PauseSong (void)
Definition at line 348 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->PauseMusic();
     }
 }
References music_module, NULL, and music_module_t::PauseMusic.
Referenced by S_PauseSound().
I_PlaySong()
void I_PlaySong (void * handle, boolean looping)
Definition at line 384 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->PlaySong(handle, looping);
     }
 }
References music_module, NULL, and music_module_t::PlaySong.
Referenced by S_ChangeMusic().
I_PrecacheSounds()
void I_PrecacheSounds (sfxinfo_t * sounds, int num_sounds)
Definition at line 319 of file i_sound.c.
 {
     if (sound_module != NULL && sound_module->CacheSounds != NULL)
     {
     sound_module->CacheSounds(sounds, num_sounds);
     }
 }
References sound_module_t::CacheSounds, NULL, and sound_module.
Referenced by S_Init().
I_RegisterSong()
void* I_RegisterSong (void * data, int len)
Definition at line 364 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         return music_module->RegisterSong(data, len);
     }
     else
     {
         return NULL;
     }
 }
References len, music_module, NULL, and music_module_t::RegisterSong.
Referenced by S_ChangeMusic().
I_ResumeSong()
void I_ResumeSong (void)
Definition at line 356 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->ResumeMusic();
     }
 }
References music_module, NULL, and music_module_t::ResumeMusic.
Referenced by S_ResumeSound(), and S_StopMusic().
I_SetMusicVolume()
void I_SetMusicVolume (int volume)
Definition at line 340 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->SetMusicVolume(volume);
     }
 }
References music_module, NULL, and music_module_t::SetMusicVolume.
Referenced by S_SetMusicVolume().
I_ShutdownMusic()
void I_ShutdownMusic (void)
Definition at line 335 of file i_sound.c.
 {
 }
Referenced by S_Shutdown().
I_ShutdownSound()
void I_ShutdownSound (void)
Definition at line 218 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         sound_module->Shutdown();
     }
     if (music_module != NULL)
     {
         music_module->Shutdown();
     }
 }
References music_module, NULL, sound_module_t::Shutdown, music_module_t::Shutdown, and sound_module.
Referenced by S_Shutdown().
I_SoundIsPlaying()
boolean I_SoundIsPlaying (int channel)
Definition at line 307 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         return sound_module->SoundIsPlaying(channel);
     }
     else
     {
         return false;
     }
 }
References NULL, sound_module, and sound_module_t::SoundIsPlaying.
Referenced by S_StopChannel(), and S_UpdateSounds().
I_StartSound()
int I_StartSound (sfxinfo_t * sfxinfo, int channel, int vol, int sep)
Definition at line 286 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         CheckVolumeSeparation(&vol, &sep);
         return sound_module->StartSound(sfxinfo, channel, vol, sep);
     }
     else
     {
         return 0;
     }
 }
References CheckVolumeSeparation(), NULL, sound_module, and sound_module_t::StartSound.
Referenced by S_StartSound().
I_StopSong()
void I_StopSong (void)
Definition at line 392 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->StopSong();
     }
 }
References music_module, NULL, and music_module_t::StopSong.
Referenced by S_StopMusic().
I_StopSound()
void I_StopSound (int channel)
Definition at line 299 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         sound_module->StopSound(channel);
     }
 }
References NULL, sound_module, and sound_module_t::StopSound.
Referenced by S_StopChannel().
I_UnRegisterSong()
void I_UnRegisterSong (void * handle)
Definition at line 376 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->UnRegisterSong(handle);
     }
 }
References music_module, NULL, and music_module_t::UnRegisterSong.
Referenced by S_StopMusic().
I_UpdateSound()
void I_UpdateSound (void)
Definition at line 243 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         sound_module->Update();
     }
     if (music_module != NULL && music_module->Poll != NULL)
     {
         music_module->Poll();
     }
 }
References music_module, NULL, music_module_t::Poll, sound_module, and sound_module_t::Update.
Referenced by S_UpdateSounds().
I_UpdateSoundParams()
void I_UpdateSoundParams (int channel, int vol, int sep)
Definition at line 277 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         CheckVolumeSeparation(&vol, &sep);
         sound_module->UpdateSoundParams(channel, vol, sep);
     }
 }
References CheckVolumeSeparation(), NULL, sound_module, and sound_module_t::UpdateSoundParams.
Referenced by S_UpdateSounds().
InitMusicModule()
static void InitMusicModule (void) static
Definition at line 149 of file i_sound.c.
 {
 #ifdef FEATURE_SOUND
     music_module = &DG_music_module;
 #endif /* FEATURE_SOUND */
 }
References music_module.
Referenced by I_InitSound().
InitSfxModule()
static void InitSfxModule (boolean use_sfx_prefix) static
Definition at line 121 of file i_sound.c.
 {
     int i;
     sound_module = NULL;
     for (i=0; sound_modules[i] != NULL; ++i)
     {
         // Is the sfx device in the list of devices supported by
         // this module?
         if (SndDeviceInList(snd_sfxdevice,
                             sound_modules[i]->sound_devices,
                             sound_modules[i]->num_sound_devices))
         {
             // Initialize the module
             if (sound_modules[i]->Init(use_sfx_prefix))
             {
                 sound_module = sound_modules[i];
                 return;
             }
         }
     }
 }
References i, GlobalDescriptorTable::Init(), NULL, snd_sfxdevice, SndDeviceInList(), sound_module, and sound_modules.
Referenced by I_InitSound().
SndDeviceInList()
static boolean SndDeviceInList (snddevice_t device, snddevice_t * list, int len) static
Definition at line 102 of file i_sound.c.
 {
     int i;
     for (i=0; i<len; ++i)
     {
         if (device == list[i])
         {
             return true;
         }
     }
     return false;
 }
References device, i, len, and list().
Referenced by InitSfxModule().
Variable Documentation
music_module
music_module_t* music_module = NULL static
Definition at line 58 of file i_sound.c.
Referenced by I_InitMusic(), I_MusicIsPlaying(), I_PauseSong(), I_PlaySong(), I_RegisterSong(), I_ResumeSong(), I_SetMusicVolume(), I_ShutdownSound(), I_StopSong(), I_UnRegisterSong(), I_UpdateSound(), and InitMusicModule().
music_opl_module
music_module_t music_opl_module extern
opl_io_port
int opl_io_port extern
snd_cachesize
int snd_cachesize = 64 * 1024 * 1024
Definition at line 44 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_maxslicetime_ms
int snd_maxslicetime_ms = 28
Definition at line 49 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_mport
int snd_mport = 0 static
Definition at line 88 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_musiccmd
char* snd_musiccmd = ""
Definition at line 53 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_musicdevice
int snd_musicdevice = SNDDEVICE_SB
Definition at line 60 of file i_sound.c.
Referenced by I_BindSoundVariables(), I_InitSound(), and S_ChangeMusic().
snd_samplerate
int snd_samplerate = 44100
Definition at line 39 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_sbdma
int snd_sbdma = 0 static
Definition at line 87 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_sbirq
int snd_sbirq = 0 static
Definition at line 86 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_sbport
int snd_sbport = 0 static
Definition at line 85 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_sfxdevice
int snd_sfxdevice = SNDDEVICE_SB
Definition at line 61 of file i_sound.c.
Referenced by I_BindSoundVariables(), and InitSfxModule().
sound_module
sound_module_t* sound_module = NULL static
Definition at line 57 of file i_sound.c.
Referenced by I_GetSfxLumpNum(), I_PrecacheSounds(), I_ShutdownSound(), I_SoundIsPlaying(), I_StartSound(), I_StopSound(), I_UpdateSound(), I_UpdateSoundParams(), and InitSfxModule().
sound_modules
sound_module_t* sound_modules[] static
Initial value:
=
{
    NULL,
}
Definition at line 92 of file i_sound.c.
Referenced by InitSfxModule().
sound_pcsound_module
sound_module_t sound_pcsound_module extern
timidity_cfg_path
char* timidity_cfg_path extern