Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/unxz/xz_private.h File Reference
xz_private.h File Reference
#include "xz_config.h"
Macros
#define DEC_IS_SINGLE(mode) (false)
#define DEC_IS_PREALLOC(mode) (false)
#define DEC_IS_DYNALLOC(mode) ((mode) == XZ_DYNALLOC)
#define DEC_IS_MULTI(mode) (true)
Functions
XZ_EXTERN struct xz_dec_lzma2 *XZ_FUNC xz_dec_lzma2_create (enum xz_mode mode, uint32_t dict_max)
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_lzma2_reset (struct xz_dec_lzma2 *s, uint8_t props)
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_lzma2_run (struct xz_dec_lzma2 *s, struct xz_buf *b)
XZ_EXTERN void XZ_FUNC xz_dec_lzma2_end (struct xz_dec_lzma2 *s)
Macro Definition Documentation
DEC_IS_DYNALLOC
#define DEC_IS_DYNALLOC (mode) ((mode) == XZ_DYNALLOC)
Definition at line 82 of file xz_private.h.
DEC_IS_MULTI
#define DEC_IS_MULTI (mode) (true)
Definition at line 88 of file xz_private.h.
DEC_IS_PREALLOC
#define DEC_IS_PREALLOC (mode) (false)
Definition at line 78 of file xz_private.h.
DEC_IS_SINGLE
#define DEC_IS_SINGLE (mode) (false)
Definition at line 72 of file xz_private.h.
Function Documentation
xz_dec_lzma2_create()
XZ_EXTERN struct xz_dec_lzma2* XZ_FUNC xz_dec_lzma2_create (enum xz_mode mode, uint32_t dict_max)
Definition at line 1103 of file xz_dec_lzma2.c.
 {
     struct xz_dec_lzma2 *s = kmalloc(sizeof(*s), GFP_KERNEL);
     if (s == NULL)
         return NULL;
     s->dict.mode = mode;
     s->dict.size_max = dict_max;
     if (DEC_IS_PREALLOC(mode)) {
         s->dict.buf = vmalloc(dict_max);
         if (s->dict.buf == NULL) {
             kfree(s);
             return NULL;
         }
     } else if (DEC_IS_DYNALLOC(mode)) {
         s->dict.buf = NULL;
         s->dict.allocated = 0;
     }
     return s;
 }
References DEC_IS_DYNALLOC, DEC_IS_PREALLOC, kfree, kmalloc, NULL, s, and vmalloc.
Referenced by xz_dec_init().
xz_dec_lzma2_end()
XZ_EXTERN void XZ_FUNC xz_dec_lzma2_end (struct xz_dec_lzma2 * s)
Definition at line 1165 of file xz_dec_lzma2.c.
 {
     if (DEC_IS_MULTI(s->dict.mode))
         vfree(s->dict.buf);
     kfree(s);
 }
References DEC_IS_MULTI, kfree, s, and vfree.
Referenced by xz_dec_end().
xz_dec_lzma2_reset()
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_lzma2_reset (struct xz_dec_lzma2 * s, uint8_t props)
Definition at line 1127 of file xz_dec_lzma2.c.
 {
     /* This limits dictionary size to 3 GiB to keep parsing simpler. */
     if (props > 39)
         return XZ_OPTIONS_ERROR;
     s->dict.size = 2 + (props & 1);
     s->dict.size <<= (props >> 1) + 11;
     if (DEC_IS_MULTI(s->dict.mode)) {
         if (s->dict.size > s->dict.size_max)
             return XZ_MEMLIMIT_ERROR;
         s->dict.end = s->dict.size;
         if (DEC_IS_DYNALLOC(s->dict.mode)) {
             if (s->dict.allocated < s->dict.size) {
                 vfree(s->dict.buf);
                 s->dict.buf = vmalloc(s->dict.size);
                 if (s->dict.buf == NULL) {
                     s->dict.allocated = 0;
                     return XZ_MEM_ERROR;
                 }
             }
         }
     }
     s->lzma.len = 0;
     s->lzma2.sequence = SEQ_CONTROL;
     s->lzma2.need_dict_reset = true;
     s->temp.size = 0;
     return XZ_OK;
 }
References DEC_IS_DYNALLOC, DEC_IS_MULTI, NULL, s, vfree, vmalloc, XZ_MEM_ERROR, XZ_MEMLIMIT_ERROR, XZ_OK, and XZ_OPTIONS_ERROR.
xz_dec_lzma2_run()
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_lzma2_run (struct xz_dec_lzma2 * s, struct xz_buf * b)
Definition at line 933 of file xz_dec_lzma2.c.
 {
     uint32_t tmp;
     while (b->in_pos < b->in_size || s->lzma2.sequence == SEQ_LZMA_RUN) {
         switch (s->lzma2.sequence) {
         case SEQ_CONTROL:
             /*
              * LZMA2 control byte
              *
              * Exact values:
              *   0x00   End marker
              *   0x01   Dictionary reset followed by
              *          an uncompressed chunk
              *   0x02   Uncompressed chunk (no dictionary reset)
              *
              * Highest three bits (s->control & 0xE0):
              *   0xE0   Dictionary reset, new properties and state
              *          reset, followed by LZMA compressed chunk
              *   0xC0   New properties and state reset, followed
              *          by LZMA compressed chunk (no dictionary
              *          reset)
              *   0xA0   State reset using old properties,
              *          followed by LZMA compressed chunk (no
              *          dictionary reset)
              *   0x80   LZMA chunk (no dictionary or state reset)
              *
              * For LZMA compressed chunks, the lowest five bits
              * (s->control & 1F) are the highest bits of the
              * uncompressed size (bits 16-20).
              *
              * A new LZMA2 stream must begin with a dictionary
              * reset. The first LZMA chunk must set new
              * properties and reset the LZMA state.
              *
              * Values that don't match anything described above
              * are invalid and we return XZ_DATA_ERROR.
              */
             tmp = b->in[b->in_pos++];
             if (tmp == 0x00)
                 return XZ_STREAM_END;
             if (tmp >= 0xE0 || tmp == 0x01) {
                 s->lzma2.need_props = true;
                 s->lzma2.need_dict_reset = false;
                 dict_reset(&s->dict, b);
             } else if (s->lzma2.need_dict_reset) {
                 return XZ_DATA_ERROR;
             }
             if (tmp >= 0x80) {
                 s->lzma2.uncompressed = (tmp & 0x1F) << 16;
                 s->lzma2.sequence = SEQ_UNCOMPRESSED_1;
                 if (tmp >= 0xC0) {
                     /*
                      * When there are new properties,
                      * state reset is done at
                      * SEQ_PROPERTIES.
                      */
                     s->lzma2.need_props = false;
                     s->lzma2.next_sequence
                             = SEQ_PROPERTIES;
                 } else if (s->lzma2.need_props) {
                     return XZ_DATA_ERROR;
                 } else {
                     s->lzma2.next_sequence
                             = SEQ_LZMA_PREPARE;
                     if (tmp >= 0xA0)
                         lzma_reset(s);
                 }
             } else {
                 if (tmp > 0x02)
                     return XZ_DATA_ERROR;
                 s->lzma2.sequence = SEQ_COMPRESSED_0;
                 s->lzma2.next_sequence = SEQ_COPY;
             }
             break;
         case SEQ_UNCOMPRESSED_1:
             s->lzma2.uncompressed
                     += (uint32_t)b->in[b->in_pos++] << 8;
             s->lzma2.sequence = SEQ_UNCOMPRESSED_2;
             break;
         case SEQ_UNCOMPRESSED_2:
             s->lzma2.uncompressed
                     += (uint32_t)b->in[b->in_pos++] + 1;
             s->lzma2.sequence = SEQ_COMPRESSED_0;
             break;
         case SEQ_COMPRESSED_0:
             s->lzma2.compressed
                     = (uint32_t)b->in[b->in_pos++] << 8;
             s->lzma2.sequence = SEQ_COMPRESSED_1;
             break;
         case SEQ_COMPRESSED_1:
             s->lzma2.compressed
                     += (uint32_t)b->in[b->in_pos++] + 1;
             s->lzma2.sequence = s->lzma2.next_sequence;
             break;
         case SEQ_PROPERTIES:
             if (!lzma_props(s, b->in[b->in_pos++]))
                 return XZ_DATA_ERROR;
             s->lzma2.sequence = SEQ_LZMA_PREPARE;
         case SEQ_LZMA_PREPARE:
             if (s->lzma2.compressed < RC_INIT_BYTES)
                 return XZ_DATA_ERROR;
             if (!rc_read_init(&s->rc, b))
                 return XZ_OK;
             s->lzma2.compressed -= RC_INIT_BYTES;
             s->lzma2.sequence = SEQ_LZMA_RUN;
         case SEQ_LZMA_RUN:
             /*
              * Set dictionary limit to indicate how much we want
              * to be encoded at maximum. Decode new data into the
              * dictionary. Flush the new data from dictionary to
              * b->out. Check if we finished decoding this chunk.
              * In case the dictionary got full but we didn't fill
              * the output buffer yet, we may run this loop
              * multiple times without changing s->lzma2.sequence.
              */
             dict_limit(&s->dict, min_t(size_t,
                     b->out_size - b->out_pos,
                     s->lzma2.uncompressed));
             if (!lzma2_lzma(s, b))
                 return XZ_DATA_ERROR;
             s->lzma2.uncompressed -= dict_flush(&s->dict, b);
             if (s->lzma2.uncompressed == 0) {
                 if (s->lzma2.compressed > 0 || s->lzma.len > 0
                         || !rc_is_finished(&s->rc))
                     return XZ_DATA_ERROR;
                 rc_reset(&s->rc);
                 s->lzma2.sequence = SEQ_CONTROL;
             } else if (b->out_pos == b->out_size
                     || (b->in_pos == b->in_size
                         && s->temp.size
                         < s->lzma2.compressed)) {
                 return XZ_OK;
             }
             break;
         case SEQ_COPY:
             dict_uncompressed(&s->dict, b, &s->lzma2.compressed);
             if (s->lzma2.compressed > 0)
                 return XZ_OK;
             s->lzma2.sequence = SEQ_CONTROL;
             break;
         }
     }
     return XZ_OK;
 }
References dict_flush(), dict_limit(), dict_reset(), dict_uncompressed(), xz_buf::in, xz_buf::in_pos, xz_buf::in_size, lzma2_lzma(), lzma_props(), lzma_reset(), min_t, xz_buf::out_pos, xz_buf::out_size, RC_INIT_BYTES, rc_is_finished(), rc_read_init(), rc_reset(), s, XZ_DATA_ERROR, XZ_OK, and XZ_STREAM_END.