Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/d_loop.h File Reference
d_loop.h File Reference
#include "net_defs.h"
Data Structures
struct loop_interface_t
Typedefs
typedef boolean(* netgame_startup_callback_t) (int ready_players, int num_players)
Functions
void D_RegisterLoopCallbacks (loop_interface_t *i)
void NetUpdate (void)
void D_QuitNetGame (void)
void TryRunTics (void)
void D_StartGameLoop (void)
boolean D_InitNetGame (net_connect_data_t *connect_data)
void D_StartNetGame (net_gamesettings_t *settings, netgame_startup_callback_t callback)
Variables
boolean singletics
int gametic
int ticdup
Typedef Documentation
netgame_startup_callback_t
typedef boolean(* netgame_startup_callback_t) (int ready_players, int num_players)
Definition at line 28 of file d_loop.h.
Function Documentation
D_InitNetGame()
boolean D_InitNetGame (net_connect_data_t * connect_data)
Definition at line 452 of file d_loop.c.
 {
     boolean result = false;
 #ifdef FEATURE_MULTIPLAYER
     net_addr_t *addr = NULL;
     int i;
 #endif
     // Call D_QuitNetGame on exit:
     I_AtExit(D_QuitNetGame, true);
     player_class = connect_data->player_class;
 #ifdef FEATURE_MULTIPLAYER
     // @category net
     //
     // Start a multiplayer server, listening for connections.
     //
     if (M_CheckParm("-server") > 0
      || M_CheckParm("-privateserver") > 0)
     {
         NET_SV_Init();
         NET_SV_AddModule(&net_loop_server_module);
         NET_SV_AddModule(&net_sdl_module);
         NET_SV_RegisterWithMaster();
         net_loop_client_module.InitClient();
         addr = net_loop_client_module.ResolveAddress(NULL);
     }
     else
     {
         // @category net
         //
         // Automatically search the local LAN for a multiplayer
         // server and join it.
         //
         i = M_CheckParm("-autojoin");
         if (i > 0)
         {
             addr = NET_FindLANServer();
             if (addr == NULL)
             {
                 I_Error("No server found on local LAN");
             }
         }
         // @arg <address>
         // @category net
         //
         // Connect to a multiplayer server running on the given
         // address.
         //
         i = M_CheckParmWithArgs("-connect", 1);
         if (i > 0)
         {
             net_sdl_module.InitClient();
             addr = net_sdl_module.ResolveAddress(myargv[i+1]);
             if (addr == NULL)
             {
                 I_Error("Unable to resolve '%s'\n", myargv[i+1]);
             }
         }
     }
     if (addr != NULL)
     {
         if (M_CheckParm("-drone") > 0)
         {
             connect_data->drone = true;
         }
         if (!NET_CL_Connect(addr, connect_data))
         {
             I_Error("D_InitNetGame: Failed to connect to %s\n",
                     NET_AddrToString(addr));
         }
         printf("D_InitNetGame: Connected to %s\n", NET_AddrToString(addr));
         // Wait for launch message received from server.
         NET_WaitForLaunch();
         result = true;
     }
 #endif
     return result;
 }
References D_QuitNetGame(), net_connect_data_t::drone, i, I_AtExit(), I_Error(), _net_module_s::InitClient, M_CheckParm(), M_CheckParmWithArgs(), myargv, NET_AddrToString(), NET_CL_Connect(), NET_FindLANServer(), net_loop_client_module, net_loop_server_module, net_sdl_module, NET_SV_AddModule(), NET_SV_Init(), NET_SV_RegisterWithMaster(), NET_WaitForLaunch(), NULL, player_class, net_connect_data_t::player_class, printf, _net_module_s::ResolveAddress, and mlibc::result.
Referenced by D_ConnectNetGame().
D_QuitNetGame()
void D_QuitNetGame (void)
Definition at line 560 of file d_loop.c.
 {
 #ifdef FEATURE_MULTIPLAYER
     NET_SV_Shutdown();
     NET_CL_Disconnect();
 #endif
 }
References NET_CL_Disconnect(), and NET_SV_Shutdown().
Referenced by D_InitNetGame().
D_RegisterLoopCallbacks()
void D_RegisterLoopCallbacks (loop_interface_t * i)
Definition at line 823 of file d_loop.c.
 {
     loop_interface = i;
 }
References i, and loop_interface.
Referenced by D_CheckNetGame().
D_StartGameLoop()
void D_StartGameLoop (void)
Definition at line 305 of file d_loop.c.
 {
     lasttime = GetAdjustedTime() / ticdup;
 }
References GetAdjustedTime(), lasttime, and ticdup.
Referenced by D_DoomLoop().
D_StartNetGame()
void D_StartNetGame (net_gamesettings_t * settings, netgame_startup_callback_t callback)
Definition at line 340 of file d_loop.c.
 {
 #if ORIGCODE
     int i;
     offsetms = 0;
     recvtic = 0;
     settings->consoleplayer = 0;
     settings->num_players = 1;
     settings->player_classes[0] = player_class;
     // @category net
     //
     // Use new network client sync code rather than the classic
     // sync code. This is currently disabled by default because it
     // has some bugs.
     //
     if (M_CheckParm("-newsync") > 0)
         settings->new_sync = 1;
     else
         settings->new_sync = 0;
     // TODO: New sync code is not enabled by default because it's
     // currently broken.
     //if (M_CheckParm("-oldsync") > 0)
     //    settings->new_sync = 0;
     //else
     //    settings->new_sync = 1;
     // @category net
     // @arg <n>
     //
     // Send n extra tics in every packet as insurance against dropped
     // packets.
     //
     i = M_CheckParmWithArgs("-extratics", 1);
     if (i > 0)
         settings->extratics = atoi(myargv[i+1]);
     else
         settings->extratics = 1;
     // @category net
     // @arg <n>
     //
     // Reduce the resolution of the game by a factor of n, reducing
     // the amount of network bandwidth needed.
     //
     i = M_CheckParmWithArgs("-dup", 1);
     if (i > 0)
         settings->ticdup = atoi(myargv[i+1]);
     else
         settings->ticdup = 1;
     if (net_client_connected)
     {
         // Send our game settings and block until game start is received
         // from the server.
         NET_CL_StartGame(settings);
         BlockUntilStart(settings, callback);
         // Read the game settings that were received.
         NET_CL_GetSettings(settings);
     }
     if (drone)
     {
         settings->consoleplayer = 0;
     }
     // Set the local player and playeringame[] values.
     localplayer = settings->consoleplayer;
     for (i = 0; i < NET_MAXPLAYERS; ++i)
     {
         local_playeringame[i] = i < settings->num_players;
     }
     // Copy settings to global variables.
     ticdup = settings->ticdup;
     new_sync = settings->new_sync;
     // TODO: Message disabled until we fix new_sync.
     //if (!new_sync)
     //{
     //    printf("Syncing netgames like Vanilla Doom.\n");
     //}
 #else
     settings->consoleplayer = 0;
     settings->num_players = 1;
     settings->player_classes[0] = player_class;
     settings->new_sync = 0;
     settings->extratics = 1;
     settings->ticdup = 1;
     ticdup = settings->ticdup;
     new_sync = settings->new_sync;
 #endif
 }
References atoi(), callback(), net_gamesettings_t::consoleplayer, drone, net_gamesettings_t::extratics, i, local_playeringame, localplayer, M_CheckParm(), M_CheckParmWithArgs(), myargv, NET_CL_GetSettings(), NET_CL_StartGame(), net_client_connected, NET_MAXPLAYERS, new_sync, net_gamesettings_t::new_sync, net_gamesettings_t::num_players, offsetms, player_class, net_gamesettings_t::player_classes, recvtic, ticdup, and net_gamesettings_t::ticdup.
Referenced by D_CheckNetGame().
NetUpdate()
void NetUpdate (void)
Definition at line 203 of file d_loop.c.
 {
     int nowtime;
     int newtics;
     int i;
     // If we are running with singletics (timing a demo), this
     // is all done separately.
     if (singletics)
         return;
 #ifdef FEATURE_MULTIPLAYER
     // Run network subsystems
     NET_CL_Run();
     NET_SV_Run();
 #endif
     // check time
     nowtime = GetAdjustedTime() / ticdup;
     newtics = nowtime - lasttime;
     lasttime = nowtime;
     if (skiptics <= newtics)
     {
         newtics -= skiptics;
         skiptics = 0;
     }
     else
     {
         skiptics -= newtics;
         newtics = 0;
     }
     // build new ticcmds for console player
     for (i=0 ; i<newtics ; i++)
     {
         if (!BuildNewTic())
         {
             break;
         }
     }
 }
References BuildNewTic(), GetAdjustedTime(), i, lasttime, NET_CL_Run(), NET_SV_Run(), singletics, skiptics, and ticdup.
Referenced by D_Display(), R_RenderPlayerView(), and TryRunTics().
TryRunTics()
void TryRunTics (void)
Definition at line 706 of file d_loop.c.
 {
     int i;
     int lowtic;
     int entertic;
     static int oldentertics;
     int realtics;
     int availabletics;
     int counts;
     // get real tics
     entertic = I_GetTime() / ticdup;
     realtics = entertic - oldentertics;
     oldentertics = entertic;
     // in singletics mode, run a single tic every time this function
     // is called.
     if (singletics)
     {
         BuildNewTic();
     }
     else
     {
         NetUpdate ();
     }
     lowtic = GetLowTic();
     availabletics = lowtic - gametic/ticdup;
     // decide how many tics to run
     if (new_sync)
     {
     counts = availabletics;
     }
     else
     {
         // decide how many tics to run
         if (realtics < availabletics-1)
             counts = realtics+1;
         else if (realtics < availabletics)
             counts = realtics;
         else
             counts = availabletics;
         if (counts < 1)
             counts = 1;
         if (net_client_connected)
         {
             OldNetSync();
         }
     }
     if (counts < 1)
     counts = 1;
     // wait for new tics if needed
     while (!PlayersInGame() || lowtic < gametic/ticdup + counts)
     {
     NetUpdate ();
         lowtic = GetLowTic();
     if (lowtic < gametic/ticdup)
         I_Error ("TryRunTics: lowtic < gametic");
         // Don't stay in this loop forever.  The menu is still running,
         // so return to update the screen
     if (I_GetTime() / ticdup - entertic > 0)
     {
         return;
     }
         I_Sleep(1);
     }
     // run the count * ticdup dics
     while (counts--)
     {
         ticcmd_set_t *set;
         if (!PlayersInGame())
         {
             return;
         }
         set = &ticdata[(gametic / ticdup) % BACKUPTICS];
         if (!net_client_connected)
         {
             SinglePlayerClear(set);
         }
     for (i=0 ; i<ticdup ; i++)
     {
             if (gametic/ticdup > lowtic)
                 I_Error ("gametic>lowtic");
             memcpy(local_playeringame, set->ingame, sizeof(local_playeringame));
             loop_interface->RunTic(set->cmds, set->ingame);
         gametic++;
         // modify command for duplicated tics
             TicdupSquash(set);
     }
     NetUpdate ();   // check for new console commands
     }
 }
References BACKUPTICS, BuildNewTic(), ticcmd_set_t::cmds, gametic, GetLowTic(), i, I_Error(), I_GetTime(), I_Sleep(), ticcmd_set_t::ingame, local_playeringame, loop_interface, memcpy, net_client_connected, NetUpdate(), new_sync, OldNetSync(), PlayersInGame(), loop_interface_t::RunTic, SinglePlayerClear(), singletics, ticdata, ticdup, and TicdupSquash().
Referenced by D_DoomLoop(), and doomgeneric_Tick().
Variable Documentation
gametic
int gametic extern
Definition at line 72 of file d_loop.c.
Referenced by A_Tracer(), BuildNewTic(), D_Display(), G_CheckDemoStatus(), G_DoLoadLevel(), G_Ticker(), M_QuitResponse(), M_SelectEndMessage(), and TryRunTics().
singletics
boolean singletics extern
Definition at line 77 of file d_loop.c.
Referenced by G_TimeDemo(), NetUpdate(), and TryRunTics().
ticdup
int ticdup
Definition at line 78 of file d_loop.h.