Fennix Userspace: Userspace/apps/base/busybox/libbb/duration.c File Reference
duration.c File Reference
#include "libbb.h"
Functions
duration_t FAST_FUNC parse_duration_str (char *str)
Variables
static const struct suffix_mult duration_suffixes[] ALIGN_SUFFIX
Function Documentation
parse_duration_str()
duration_t FAST_FUNC parse_duration_str (char * str)
Definition at line 89 of file duration.c.
 {
     return xatou_range_sfx(str, 0, UINT_MAX, duration_suffixes);
 }
References str, and UINT_MAX.
Referenced by sleep_main(), timeout_main(), top_main(), and watch_main().
Variable Documentation
ALIGN_SUFFIX
const struct suffix_mult duration_suffixes [] ALIGN_SUFFIX static
Initial value:
= {
    { "s", 1 },
    { "m", 60 },
    { "h", 60*60 },
    { "d", 24*60*60 },
    { "", 0 }
}
Definition at line 24 of file duration.c.