Fennix Userspace: Userspace/musl/include/sys/msg.h File Reference
msg.h File Reference
#include <sys/ipc.h>
#include <bits/alltypes.h>
#include <bits/msg.h>
Data Structures
struct msginfo
Macros
#define __NEED_pid_t
#define __NEED_key_t
#define __NEED_time_t
#define __NEED_size_t
#define __NEED_ssize_t
#define __msg_cbytes msg_cbytes
#define MSG_NOERROR 010000
#define MSG_EXCEPT 020000
#define MSG_STAT (11 | (IPC_STAT & 0x100))
#define MSG_INFO 12
#define MSG_STAT_ANY (13 | (IPC_STAT & 0x100))
Typedefs
typedef unsigned long msgqnum_t
typedef unsigned long msglen_t
Functions
int msgctl (int, int, struct msqid_ds *)
int msgget (key_t, int)
ssize_t msgrcv (int, void *, size_t, long, int)
int msgsnd (int, const void *, size_t, int)
Data Structure Documentation
msginfo
struct msginfo
Definition at line 32 of file msg.h.
Data Fields
int msgmap
int msgmax
int msgmnb
int msgmni
int msgpool
unsigned short msgseg
int msgssz
int msgtql
Macro Definition Documentation
__msg_cbytes
#define __msg_cbytes msg_cbytes
Definition at line 23 of file msg.h.
__NEED_key_t
#define __NEED_key_t
Definition at line 11 of file msg.h.
__NEED_pid_t
#define __NEED_pid_t
Definition at line 10 of file msg.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 13 of file msg.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 14 of file msg.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 12 of file msg.h.
MSG_EXCEPT
#define MSG_EXCEPT 020000
Definition at line 26 of file msg.h.
MSG_INFO
#define MSG_INFO 12
Definition at line 29 of file msg.h.
MSG_NOERROR
#define MSG_NOERROR 010000
Definition at line 25 of file msg.h.
MSG_STAT
#define MSG_STAT (11 | (IPC_STAT & 0x100))
Definition at line 28 of file msg.h.
MSG_STAT_ANY
#define MSG_STAT_ANY (13 | (IPC_STAT & 0x100))
Definition at line 30 of file msg.h.
Typedef Documentation
msglen_t
typedef unsigned long msglen_t
Definition at line 19 of file msg.h.
msgqnum_t
typedef unsigned long msgqnum_t
Definition at line 18 of file msg.h.
Function Documentation
msgctl()
int msgctl (int q, int cmd, struct msqid_ds * buf)
Definition at line 10 of file msgctl.c.
 {
 #if IPC_TIME64
     struct msqid_ds out, *orig;
     if (cmd&IPC_TIME64) {
         out = (struct msqid_ds){0};
         orig = buf;
         buf = &out;
     }
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     struct msqid_ds tmp;
     if (cmd == IPC_SET) {
         tmp = *buf;
         tmp.msg_perm.mode *= 0x10000U;
         buf = &tmp;
     }
 #endif
 #ifndef SYS_ipc
     int r = __syscall(SYS_msgctl, q, IPC_CMD(cmd), buf);
 #else
     int r = __syscall(SYS_ipc, IPCOP_msgctl, q, IPC_CMD(cmd), 0, buf, 0);
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     if (r >= 0) switch (cmd | IPC_TIME64) {
     case IPC_STAT:
     case MSG_STAT:
     case MSG_STAT_ANY:
         buf->msg_perm.mode >>= 16;
     }
 #endif
 #if IPC_TIME64
     if (r >= 0 && (cmd&IPC_TIME64)) {
         buf = orig;
         *buf = out;
         IPC_HILO(buf, msg_stime);
         IPC_HILO(buf, msg_rtime);
         IPC_HILO(buf, msg_ctime);
     }
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), buf, IPC_CMD, IPC_HILO, IPC_SET, IPC_STAT, IPC_TIME64, IPCOP_msgctl, ipc_perm::mode, msqid_ds::msg_ctime, msqid_ds::msg_perm, msqid_ds::msg_rtime, MSG_STAT, MSG_STAT_ANY, msqid_ds::msg_stime, and out().
msgget()
int msgget (key_t k, int flag)
Definition at line 5 of file msgget.c.
 {
 #ifndef SYS_ipc
     return syscall(SYS_msgget, k, flag);
 #else
     return syscall(SYS_ipc, IPCOP_msgget, k, flag);
 #endif
 }
References IPCOP_msgget, k, and syscall().
msgrcv()
ssize_t msgrcv (int q, void * m, size_t len, long type, int flag)
Definition at line 5 of file msgrcv.c.
 {
 #ifndef SYS_ipc
     return syscall_cp(SYS_msgrcv, q, m, len, type, flag);
 #else
     return syscall_cp(SYS_ipc, IPCOP_msgrcv, q, len, flag, ((long[]){ (long)m, type }));
 #endif
 }
References IPCOP_msgrcv, and syscall_cp.
msgsnd()
int msgsnd (int q, const void * m, size_t len, int flag)
Definition at line 5 of file msgsnd.c.
 {
 #ifndef SYS_ipc
     return syscall_cp(SYS_msgsnd, q, m, len, flag);
 #else
     return syscall_cp(SYS_ipc, IPCOP_msgsnd, q, len, flag, m);
 #endif
 }
References IPCOP_msgsnd, and syscall_cp.