Fennix Userspace: Userspace/apps/base/busybox/libbb/concat_subpath_file.c File Reference
concat_subpath_file.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC concat_subpath_file (const char *path, const char *f)
Function Documentation
concat_subpath_file()
char* FAST_FUNC concat_subpath_file (const char * path, const char * f)
Definition at line 17 of file concat_subpath_file.c.
 {
     if (f && DOT_OR_DOTDOT(f))
         return NULL;
     return concat_path_file(path, f);
 }
References concat_path_file(), DOT_OR_DOTDOT, f, and NULL.
Referenced by chattr_dir_proc(), copy_file(), du(), recursive_action1(), remove_file(), rmrf(), scan_recursive(), and sysctl_act_recursive().