Fennix Userspace: Userspace/apps/base/busybox/networking/tunctl.c File Reference
tunctl.c File Reference
#include <netinet/in.h>
#include <net/if.h>
#include <linux/if_tun.h>
#include "libbb.h"
Macros
#define TUNSETGROUP _IOW('T', 206, int)
#define IOCTL(a, b, c) ioctl_or_perror_and_die(a, b, c, NULL)
Functions
int tunctl_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
IOCTL
#define IOCTL (a, b, c) ioctl_or_perror_and_die(a, b, c, NULL)
Definition at line 57 of file tunctl.c.
TUNSETGROUP
#define TUNSETGROUP _IOW('T', 206, int)
Definition at line 54 of file tunctl.c.
Function Documentation
tunctl_main()
int tunctl_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 62 of file tunctl.c.
 {
     struct ifreq ifr;
     int fd;
     const char *opt_name = "tap%d";
     const char *opt_device = "/dev/net/tun";
 #if ENABLE_FEATURE_TUNCTL_UG
     const char *opt_user, *opt_group;
     long user = -1, group = -1;
 #endif
     unsigned opts;
     enum {
         OPT_f = 1 << 0, // control device name (/dev/net/tun)
         OPT_t = 1 << 1, // create named interface
         OPT_d = 1 << 2, // delete named interface
 #if ENABLE_FEATURE_TUNCTL_UG
         OPT_u = 1 << 3, // set new interface owner
         OPT_g = 1 << 4, // set new interface group
         OPT_b = 1 << 5, // brief output
 #endif
     };
     opts = getopt32(argv, "^"
             "f:t:d:" IF_FEATURE_TUNCTL_UG("u:g:b")
             "\0"
             "=0:t--d:d--t", // no arguments; t ^ d
             &opt_device, &opt_name, &opt_name
             IF_FEATURE_TUNCTL_UG(, &opt_user, &opt_group)
     );
     // select device
     memset(&ifr, 0, sizeof(ifr));
     ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
     strncpy_IFNAMSIZ(ifr.ifr_name, opt_name);
     // open device
     fd = xopen(opt_device, O_RDWR);
     IOCTL(fd, TUNSETIFF, (void *)&ifr);
     // delete?
     if (opts & OPT_d) {
         IOCTL(fd, TUNSETPERSIST, (void *)(uintptr_t)0);
         printf("Set '%s' nonpersistent\n", ifr.ifr_name);
         return EXIT_SUCCESS;
     }
     // create
 #if ENABLE_FEATURE_TUNCTL_UG
     if (opts & OPT_g) {
         group = xgroup2gid(opt_group);
         IOCTL(fd, TUNSETGROUP, (void *)(uintptr_t)group);
     } else
         user = geteuid();
     if (opts & OPT_u)
         user = xuname2uid(opt_user);
     IOCTL(fd, TUNSETOWNER, (void *)(uintptr_t)user);
 #endif
     IOCTL(fd, TUNSETPERSIST, (void *)(uintptr_t)1);
     // show info
 #if ENABLE_FEATURE_TUNCTL_UG
     if (opts & OPT_b) {
         puts(ifr.ifr_name);
     } else {
         printf("Set '%s' %spersistent", ifr.ifr_name, "");
         printf(" and owned by uid %ld", user);
         if (group != -1)
             printf(" gid %ld", group);
         bb_putchar('\n');
     }
 #else
     puts(ifr.ifr_name);
 #endif
     return EXIT_SUCCESS;
 }
References argv, bb_putchar(), EXIT_SUCCESS, fd, geteuid, getopt32(), ifr, IOCTL, memset(), O_RDWR, OPT_b, OPT_d, OPT_f, OPT_g, OPT_t, OPT_u, printf(), puts(), strncpy_IFNAMSIZ(), TUNSETGROUP, xgroup2gid(), xopen(), and xuname2uid().