Fennix Userspace: Userspace/musl/include/utime.h File Reference
utime.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct utimbuf
Macros
#define __NEED_time_t
Functions
int utime (const char *, const struct utimbuf *)
Data Structure Documentation
utimbuf
struct utimbuf
Definition at line 10 of file utime.h.
Data Fields
time_t actime
time_t modtime
Macro Definition Documentation
__NEED_time_t
#define __NEED_time_t
Definition at line 10 of file utime.h.
Function Documentation
utime()
int utime (const char * filename, const struct utimbuf * times)
Definition at line 9 of file utime-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     struct timespec time[2];
     if(times) {
         time[0].tv_sec = times->actime;
         time[0].tv_nsec = 0;
         time[1].tv_sec = times->modtime;
         time[1].tv_nsec = 0;
     } else {
         time[0].tv_sec = UTIME_NOW;
         time[0].tv_nsec = UTIME_NOW;
         time[1].tv_sec = UTIME_NOW;
         time[1].tv_nsec = UTIME_NOW;
     }
     if (int e = mlibc::sys_utimensat(AT_FDCWD, filename, time, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_utimensat(), time(), times(), UTIME_NOW, and utimensat().
Referenced by __utime_time32().