Fennix: Userspace/apps/base/busybox/libbb/bb_qsort.c File Reference
bb_qsort.c File Reference
#include "libbb.h"
Functions
int bb_pstrcmp (const void *a, const void *b)
void FAST_FUNC qsort_string_vector (char **sv, unsigned count)
Function Documentation
bb_pstrcmp()
int bb_pstrcmp (const void * a, const void * b)
Definition at line 11 of file bb_qsort.c.
 {
     return strcmp(*(char**)a, *(char**)b);
 }
References strcmp.
Referenced by qsort_string_vector().
qsort_string_vector()
void FAST_FUNC qsort_string_vector (char ** sv, unsigned count)
Definition at line 16 of file bb_qsort.c.
 {
     qsort(sv, count, sizeof(char*), bb_pstrcmp);
 }
References bb_pstrcmp(), count, qsort(), and sv.