Fennix Userspace: Userspace/mlibc/options/internal/generic/essential.cpp File Reference
essential.cpp File Reference
#include <string.h>
#include <stdint.h>
Data Structures
struct anonymous_namespace{essential.cpp}::word_helper< T >
Namespaces
anonymous_namespace{essential.cpp}
Typedefs
template<typename T >
using anonymous_namespace{essential.cpp}::word = typename word_helper< T >::word_enum
Functions
template<typename T >
word< T > anonymous_namespace{essential.cpp}::alias_load (const unsigned char *&p)
template<typename T >
void anonymous_namespace{essential.cpp}::alias_store (unsigned char *&p, word< T > value)
void * memcpy (void *dest, const void *src, size_t n)
void * memset (void *dest, int byte, size_t count)
void * memmove (void *dest, const void *src, size_t size)
size_t strlen (const char *s)
Function Documentation
memcpy()
void* memcpy (void * dest, const void * src, size_t n)
Definition at line 100 of file essential.cpp.
{
     for(size_t i = 0; i < n; i++)
         ((char *)dest)[i] = ((const char *)src)[i];
     return dest;
 }
References i, and n.
memmove()
void* memmove (void * dest, const void * src, size_t size)
Definition at line 198 of file essential.cpp.
{
     char *dest_bytes = (char *)dest;
     char *src_bytes = (char *)src;
     if(dest_bytes < src_bytes) {
         for(size_t i = 0; i < size; i++)
             dest_bytes[i] = src_bytes[i];
     }else{
         for(size_t i = 0; i < size; i++)
             dest_bytes[size - i - 1] = src_bytes[size - i - 1];
     }
     return dest;
 }
References i, and size.
Referenced by GetGameName(), LoadDefaultCollection(), realpath(), and wmemmove().
memset()
void* memset (void * dest, int byte, size_t count)
Definition at line 186 of file essential.cpp.
{
     for(size_t i = 0; i < count; i++)
         ((char *)dest)[i] = (char)byte;
     return dest;
 }
References mlibc::count, and i.
Referenced by __FD_ZERO(), ObjectRepository::_fetchFromFile(), accessDtv(), allocateTcb(), AM_clearFB(), BuildNewTic(), calloc(), do_scanf(), G_BuildTiccmd(), G_DoLoadLevel(), G_PlayerFinishLevel(), G_PlayerReborn(), GenerateTextureHashTable(), GetSectorAtNullAddress(), I_Error(), I_InitGraphics(), I_Stretch5x(), initTlsObjects(), LoadResponseFile(), M_ExtractFileBase(), main(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_ReadSaveGameHeader(), P_SpawnMobj(), P_SpawnSpecials(), P_UpdateSpecials(), P_WriteSaveGameHeader(), PadRejectArray(), ParseDMXConfig(), pthread_attr_getaffinity_np(), pthread_barrier_destroy(), pthread_condattr_destroy(), pthread_mutexattr_destroy(), R_CheckPlane(), R_ClearPlanes(), R_FindPlane(), R_GenerateLookup(), R_InitSpriteDefs(), R_PrecacheLevel(), regcomp(), SHA1_Final(), socket_setup(), stpncpy(), mlibc::sys_getrusage(), mlibc::sys_pselect(), tre_mem_alloc_impl(), tre_mem_new_impl(), tre_tnfa_run_backtrack(), tre_tnfa_run_parallel(), verify_decode(), W_GenerateHashTable(), and WritePCXfile().
strlen()
size_t strlen (const char * s)
Definition at line 211 of file essential.cpp.
{
     size_t len = 0;
     for(size_t i = 0; s[i]; i++)
         len++;
     return len;
 }
References i.
Referenced by mlibc::__attribute__(), StreamPrinter::append(), basename(), cht_CheckCheat(), anonymous_namespace{grp-stubs.cpp}::copy_to_buffer(), create_slice(), DirIsFile(), dirname(), do_glob(), ends_with(), EscapeShellString(), anonymous_namespace{pwd-stubs.cpp}::extract_entry(), F_Ticker(), fputs_unlocked(), G_RecordDemo(), getenv(), GetGameName(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), getpwnam_r(), getpwuid_r(), getspnam_r(), glob(), I_Error(), I_PrintBanner(), LoadDefaultCollection(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), M_Drawer(), M_ExtractFileBase(), M_SaveSelect(), M_StrCaseStr(), M_StringConcat(), M_StringCopy(), M_StringDuplicate(), M_StringEndsWith(), M_StringHeight(), M_StringJoin(), M_StringReplace(), M_StringStartsWith(), M_StringWidth(), main(), mkdtemp(), mkostemp(), P_SaveGameFile(), posix_spawn_file_actions_addopen(), PrintDehackedBanners(), puts(), readdir(), readdir_r(), realpath(), regerror(), setlocale(), SHA1_UpdateString(), SplitLine(), stpcpy(), stpncpy(), strcasestr(), strcat(), strdup(), strerror_r(), strlcat(), strlcpy(), strncat(), anonymous_namespace{time.cpp}::strptime_internal(), strrchr(), strxfrm(), mlibc::sys_access(), mlibc::sys_chdir(), mlibc::sys_execve(), mlibc::sys_libc_log(), mlibc::sys_mkdir(), mlibc::sys_open(), mlibc::sys_readlink(), mlibc::sys_rename(), mlibc::sys_stat(), verify_decode(), W_AddFile(), and ZenityErrorBox().