Fennix: vfs::TTYDevice Class Reference
vfs::TTYDevice Class Reference
#include <mounts.hpp>
Public Member Functions
virtual size_t write (uint8_t *Buffer, size_t Size, off_t Offset)
virtual int ioctl (unsigned long Request, void *Argp)
TTYDevice ()
~TTYDevice ()
Public Member Functions inherited from vfs::Node
virtual int open (int Flags, mode_t Mode)
virtual int close ()
virtual size_t read (uint8_t *Buffer, size_t Size, off_t Offset)
virtual ~Node ()
RefNode * CreateReference ()
void RemoveReference (RefNode *Reference)
int Delete (bool Recursive=false)
Node (Node *Parent, const char *Name, NodeType Type, bool NoParent=false, Virtual *fs=nullptr, int *Err=nullptr)
Additional Inherited Members
Data Fields inherited from vfs::Node
class Virtual * vFS = nullptr
Node * Parent = nullptr
const char * Name
const char * FullPath
NodeType Type
ino_t IndexNode
const char * Symlink
Node * SymlinkTarget
mode_t Mode
uid_t UserIdentifier
gid_t GroupIdentifier
dev_t DeviceMajor
dev_t DeviceMinor
time_t AccessTime
time_t ModifyTime
time_t ChangeTime
off_t Size
std::vector< Node * > Children
std::vector< RefNode * > References
Detailed Description
Definition at line 76 of file mounts.hpp.
Constructor & Destructor Documentation
TTYDevice()
vfs::TTYDevice::TTYDevice ()
Definition at line 59 of file tty.cpp.
 : Node(DevFS, "tty", CHARDEVICE) {}
~TTYDevice()
vfs::TTYDevice::~TTYDevice ()
Definition at line 60 of file tty.cpp.
 {}
Member Function Documentation
ioctl()
int vfs::TTYDevice::ioctl (unsigned long Request, void * Argp) virtual
Reimplemented from vfs::Node.
Definition at line 35 of file tty.cpp.
     {
         switch (Request)
         {
         case TIOCGWINSZ:
         {
             struct winsize *ws = (struct winsize *)Argp;
             Video::ScreenBuffer *sb = Display->GetBuffer(0);
             Video::FontInfo fi = Display->GetCurrentFont()->GetInfo();
             fixme("TIOCGWINSZ: stub");
             ws->ws_xpixel = uint16_t(sb->Width);
             ws->ws_ypixel = uint16_t(sb->Height);
             ws->ws_col = uint16_t(sb->Width / fi.Width);
             ws->ws_row = uint16_t(sb->Height / fi.Height);
             break;
         }
         default:
             fixme("Unknown request %#lx", Request);
             return -EINVAL;
         }
         return 0;
     }
References Display, EINVAL, fixme, Video::Display::GetBuffer(), Video::Display::GetCurrentFont(), Video::Font::GetInfo(), Video::FontInfo::Height, Video::ScreenBuffer::Height, TIOCGWINSZ, Video::FontInfo::Width, Video::ScreenBuffer::Width, winsize::ws_col, winsize::ws_row, winsize::ws_xpixel, and winsize::ws_ypixel.
write()
size_t vfs::TTYDevice::write (uint8_t * Buffer, size_t Size, off_t Offset) virtual
Reimplemented from vfs::Node.
Definition at line 26 of file tty.cpp.
     {
         for (size_t i = 0; i < Size; i++)
             putchar(((char *)Buffer)[i]);
         Display->SetBuffer(0); /* FIXME: stub */
         return Size;
     }
References Display, i, putchar, Video::Display::SetBuffer(), and vfs::Node::Size.
The documentation for this class was generated from the following files:
Kernel/include/filesystem/mounts.hpp
Kernel/storage/fs/tty.cpp