Fennix: Userspace/musl/src/internal/syscall.h File Reference
syscall.h File Reference
#include <features.h>
#include <errno.h>
#include <sys/syscall.h>
#include "syscall_arch.h"
Macros
#define SYSCALL_RLIM_INFINITY (~0ULL)
#define SYSCALL_MMAP2_UNIT 4096ULL
#define __SYSCALL_LL_PRW(x) __SYSCALL_LL_O(x)
#define __scc(X) ((long) (X))
#define __syscall1(n, a) __syscall1(n,__scc(a))
#define __syscall2(n, a, b) __syscall2(n,__scc(a),__scc(b))
#define __syscall3(n, a, b, c) __syscall3(n,__scc(a),__scc(b),__scc(c))
#define __syscall4(n, a, b, c, d) __syscall4(n,__scc(a),__scc(b),__scc(c),__scc(d))
#define __syscall5(n, a, b, c, d, e) __syscall5(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e))
#define __syscall6(n, a, b, c, d, e, f) __syscall6(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f))
#define __syscall7(n, a, b, c, d, e, f, g) __syscall7(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f),__scc(g))
#define __SYSCALL_NARGS_X(a, b, c, d, e, f, g, h, n, ...) n
#define __SYSCALL_NARGS(...) __SYSCALL_NARGS_X(__VA_ARGS__,7,6,5,4,3,2,1,0,)
#define __SYSCALL_CONCAT_X(a, b) a##b
#define __SYSCALL_CONCAT(a, b) __SYSCALL_CONCAT_X(a,b)
#define __SYSCALL_DISP(b, ...) __SYSCALL_CONCAT(b,__SYSCALL_NARGS(__VA_ARGS__))(__VA_ARGS__)
#define __syscall(...) __SYSCALL_DISP(__syscall,__VA_ARGS__)
#define syscall(...) __syscall_ret(__syscall(__VA_ARGS__))
#define socketcall(nm, a, b, c, d, e, f) __syscall_ret(__socketcall(nm,a,b,c,d,e,f))
#define socketcall_cp(nm, a, b, c, d, e, f) __syscall_ret(__socketcall_cp(nm,a,b,c,d,e,f))
#define __syscall_cp0(n) (__syscall_cp)(n,0,0,0,0,0,0)
#define __syscall_cp1(n, a) (__syscall_cp)(n,__scc(a),0,0,0,0,0)
#define __syscall_cp2(n, a, b) (__syscall_cp)(n,__scc(a),__scc(b),0,0,0,0)
#define __syscall_cp3(n, a, b, c) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),0,0,0)
#define __syscall_cp4(n, a, b, c, d) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),__scc(d),0,0)
#define __syscall_cp5(n, a, b, c, d, e) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),0)
#define __syscall_cp6(n, a, b, c, d, e, f) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f))
#define __syscall_cp(...) __SYSCALL_DISP(__syscall_cp,__VA_ARGS__)
#define syscall_cp(...) __syscall_ret(__syscall_cp(__VA_ARGS__))
#define __socketcall(nm, a, b, c, d, e, f)
#define __socketcall_cp(nm, a, b, c, d, e, f)
#define SYS_clock_gettime SYS_clock_gettime64
#define SYS_clock_settime SYS_clock_settime64
#define SYS_clock_adjtime SYS_clock_adjtime64
#define SYS_clock_getres SYS_clock_getres_time64
#define SYS_clock_nanosleep SYS_clock_nanosleep_time64
#define SYS_timer_gettime SYS_timer_gettime64
#define SYS_timer_settime SYS_timer_settime64
#define SYS_timerfd_gettime SYS_timerfd_gettime64
#define SYS_timerfd_settime SYS_timerfd_settime64
#define SYS_utimensat SYS_utimensat_time64
#define SYS_pselect6 SYS_pselect6_time64
#define SYS_ppoll SYS_ppoll_time64
#define SYS_recvmmsg SYS_recvmmsg_time64
#define SYS_mq_timedsend SYS_mq_timedsend_time64
#define SYS_mq_timedreceive SYS_mq_timedreceive_time64
#define SYS_rt_sigtimedwait SYS_rt_sigtimedwait_time64
#define SYS_futex SYS_futex_time64
#define SYS_sched_rr_get_interval SYS_sched_rr_get_interval_time64
#define __SC_socket 1
#define __SC_bind 2
#define __SC_connect 3
#define __SC_listen 4
#define __SC_accept 5
#define __SC_getsockname 6
#define __SC_getpeername 7
#define __SC_socketpair 8
#define __SC_send 9
#define __SC_recv 10
#define __SC_sendto 11
#define __SC_recvfrom 12
#define __SC_shutdown 13
#define __SC_setsockopt 14
#define __SC_getsockopt 15
#define __SC_sendmsg 16
#define __SC_recvmsg 17
#define __SC_accept4 18
#define __SC_recvmmsg 19
#define __SC_sendmmsg 20
#define SYS_accept SYS_accept4
#define SO_RCVTIMEO_OLD 20
#define SO_SNDTIMEO_OLD 21
#define SO_TIMESTAMP_OLD 29
#define SO_TIMESTAMPNS_OLD 35
#define SO_TIMESTAMPING_OLD 37
#define SCM_TIMESTAMP_OLD SO_TIMESTAMP_OLD
#define SCM_TIMESTAMPNS_OLD SO_TIMESTAMPNS_OLD
#define SCM_TIMESTAMPING_OLD SO_TIMESTAMPING_OLD
#define SIOCGSTAMP_OLD 0x8906
#define SIOCGSTAMPNS_OLD 0x8907
#define __sys_open2(x, pn, fl) __syscall3(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE)
#define __sys_open3(x, pn, fl, mo) __syscall4(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE, mo)
#define __sys_open_cp2(x, pn, fl) __syscall_cp3(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE)
#define __sys_open_cp3(x, pn, fl, mo) __syscall_cp4(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE, mo)
#define __sys_open(...) __SYSCALL_DISP(__sys_open,,__VA_ARGS__)
#define sys_open(...) __syscall_ret(__sys_open(__VA_ARGS__))
#define __sys_open_cp(...) __SYSCALL_DISP(__sys_open_cp,,__VA_ARGS__)
#define sys_open_cp(...) __syscall_ret(__sys_open_cp(__VA_ARGS__))
Typedefs
typedef long syscall_arg_t
Functions
hidden long __syscall_ret (unsigned long)
hidden long __syscall_cp (syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t, syscall_arg_t)
static long __alt_socketcall (int sys, int sock, int cp, syscall_arg_t a, syscall_arg_t b, syscall_arg_t c, syscall_arg_t d, syscall_arg_t e, syscall_arg_t f)
hidden void __procfdname (char __buf[static 15+3 *sizeof(int)], unsigned)
hidden void * __vdsosym (const char *, const char *)
Macro Definition Documentation
__SC_accept
#define __SC_accept 5
Definition at line 332 of file syscall.h.
__SC_accept4
#define __SC_accept4 18
Definition at line 345 of file syscall.h.
__SC_bind
#define __SC_bind 2
Definition at line 329 of file syscall.h.
__SC_connect
#define __SC_connect 3
Definition at line 330 of file syscall.h.
__SC_getpeername
#define __SC_getpeername 7
Definition at line 334 of file syscall.h.
__SC_getsockname
#define __SC_getsockname 6
Definition at line 333 of file syscall.h.
__SC_getsockopt
#define __SC_getsockopt 15
Definition at line 342 of file syscall.h.
__SC_listen
#define __SC_listen 4
Definition at line 331 of file syscall.h.
__SC_recv
#define __SC_recv 10
Definition at line 337 of file syscall.h.
__SC_recvfrom
#define __SC_recvfrom 12
Definition at line 339 of file syscall.h.
__SC_recvmmsg
#define __SC_recvmmsg 19
Definition at line 346 of file syscall.h.
__SC_recvmsg
#define __SC_recvmsg 17
Definition at line 344 of file syscall.h.
__SC_send
#define __SC_send 9
Definition at line 336 of file syscall.h.
__SC_sendmmsg
#define __SC_sendmmsg 20
Definition at line 347 of file syscall.h.
__SC_sendmsg
#define __SC_sendmsg 16
Definition at line 343 of file syscall.h.
__SC_sendto
#define __SC_sendto 11
Definition at line 338 of file syscall.h.
__SC_setsockopt
#define __SC_setsockopt 14
Definition at line 341 of file syscall.h.
__SC_shutdown
#define __SC_shutdown 13
Definition at line 340 of file syscall.h.
__SC_socket
#define __SC_socket 1
Definition at line 328 of file syscall.h.
__SC_socketpair
#define __SC_socketpair 8
Definition at line 335 of file syscall.h.
__scc
#define __scc (X) ((long) (X))
Definition at line 22 of file syscall.h.
__socketcall
#define __socketcall (nm, a, b, c, d, e, f)
Value:
    __alt_socketcall(SYS_##nm, __SC_##nm, 0, \
    __scc(a), __scc(b), __scc(c), __scc(d), __scc(e), __scc(f))
Definition at line 73 of file syscall.h.
__socketcall_cp
#define __socketcall_cp (nm, a, b, c, d, e, f)
Value:
    __alt_socketcall(SYS_##nm, __SC_##nm, 1, \
    __scc(a), __scc(b), __scc(c), __scc(d), __scc(e), __scc(f))
Definition at line 75 of file syscall.h.
__sys_open
#define __sys_open (...) __SYSCALL_DISP(__sys_open,,__VA_ARGS__)
Definition at line 388 of file syscall.h.
__sys_open2
#define __sys_open2 (x, pn, fl) __syscall3(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE)
Definition at line 382 of file syscall.h.
__sys_open3
#define __sys_open3 (x, pn, fl, mo) __syscall4(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE, mo)
Definition at line 383 of file syscall.h.
__sys_open_cp
#define __sys_open_cp (...) __SYSCALL_DISP(__sys_open_cp,,__VA_ARGS__)
Definition at line 391 of file syscall.h.
__sys_open_cp2
#define __sys_open_cp2 (x, pn, fl) __syscall_cp3(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE)
Definition at line 384 of file syscall.h.
__sys_open_cp3
#define __sys_open_cp3 (x, pn, fl, mo) __syscall_cp4(SYS_openat, AT_FDCWD, pn, (fl)|O_LARGEFILE, mo)
Definition at line 385 of file syscall.h.
__syscall
#define __syscall (...) __SYSCALL_DISP(__syscall,__VA_ARGS__)
Definition at line 44 of file syscall.h.
__syscall1
#define __syscall1 (n, a) __syscall1(n,__scc(a))
Definition at line 30 of file syscall.h.
__syscall2
#define __syscall2 (n, a, b) __syscall2(n,__scc(a),__scc(b))
Definition at line 31 of file syscall.h.
__syscall3
#define __syscall3 (n, a, b, c) __syscall3(n,__scc(a),__scc(b),__scc(c))
Definition at line 32 of file syscall.h.
__syscall4
#define __syscall4 (n, a, b, c, d) __syscall4(n,__scc(a),__scc(b),__scc(c),__scc(d))
Definition at line 33 of file syscall.h.
__syscall5
#define __syscall5 (n, a, b, c, d, e) __syscall5(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e))
Definition at line 34 of file syscall.h.
__syscall6
#define __syscall6 (n, a, b, c, d, e, f) __syscall6(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f))
Definition at line 35 of file syscall.h.
__syscall7
#define __syscall7 (n, a, b, c, d, e, f, g) __syscall7(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f),__scc(g))
Definition at line 36 of file syscall.h.
__SYSCALL_CONCAT
#define __SYSCALL_CONCAT (a, b) __SYSCALL_CONCAT_X(a,b)
Definition at line 41 of file syscall.h.
__SYSCALL_CONCAT_X
#define __SYSCALL_CONCAT_X (a, b) a##b
Definition at line 40 of file syscall.h.
__syscall_cp
#define __syscall_cp (...) __SYSCALL_DISP(__syscall_cp,__VA_ARGS__)
Definition at line 58 of file syscall.h.
__syscall_cp0
#define __syscall_cp0 (n) (__syscall_cp)(n,0,0,0,0,0,0)
Definition at line 50 of file syscall.h.
__syscall_cp1
#define __syscall_cp1 (n, a) (__syscall_cp)(n,__scc(a),0,0,0,0,0)
Definition at line 51 of file syscall.h.
__syscall_cp2
#define __syscall_cp2 (n, a, b) (__syscall_cp)(n,__scc(a),__scc(b),0,0,0,0)
Definition at line 52 of file syscall.h.
__syscall_cp3
#define __syscall_cp3 (n, a, b, c) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),0,0,0)
Definition at line 53 of file syscall.h.
__syscall_cp4
#define __syscall_cp4 (n, a, b, c, d) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),__scc(d),0,0)
Definition at line 54 of file syscall.h.
__syscall_cp5
#define __syscall_cp5 (n, a, b, c, d, e) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),0)
Definition at line 55 of file syscall.h.
__syscall_cp6
#define __syscall_cp6 (n, a, b, c, d, e, f) (__syscall_cp)(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f))
Definition at line 56 of file syscall.h.
__SYSCALL_DISP
#define __SYSCALL_DISP (b, ...) __SYSCALL_CONCAT(b,__SYSCALL_NARGS(__VA_ARGS__))(__VA_ARGS__)
Definition at line 42 of file syscall.h.
__SYSCALL_LL_PRW
#define __SYSCALL_LL_PRW (x) __SYSCALL_LL_O(x)
Definition at line 18 of file syscall.h.
__SYSCALL_NARGS
#define __SYSCALL_NARGS (...) __SYSCALL_NARGS_X(__VA_ARGS__,7,6,5,4,3,2,1,0,)
Definition at line 39 of file syscall.h.
__SYSCALL_NARGS_X
#define __SYSCALL_NARGS_X (a, b, c, d, e, f, g, h, n, ...) n
Definition at line 38 of file syscall.h.
SCM_TIMESTAMP_OLD
#define SCM_TIMESTAMP_OLD SO_TIMESTAMP_OLD
Definition at line 365 of file syscall.h.
SCM_TIMESTAMPING_OLD
#define SCM_TIMESTAMPING_OLD SO_TIMESTAMPING_OLD
Definition at line 367 of file syscall.h.
SCM_TIMESTAMPNS_OLD
#define SCM_TIMESTAMPNS_OLD SO_TIMESTAMPNS_OLD
Definition at line 366 of file syscall.h.
SIOCGSTAMP_OLD
#define SIOCGSTAMP_OLD 0x8906
Definition at line 370 of file syscall.h.
SIOCGSTAMPNS_OLD
#define SIOCGSTAMPNS_OLD 0x8907
Definition at line 373 of file syscall.h.
SO_RCVTIMEO_OLD
#define SO_RCVTIMEO_OLD 20
Definition at line 356 of file syscall.h.
SO_SNDTIMEO_OLD
#define SO_SNDTIMEO_OLD 21
Definition at line 359 of file syscall.h.
SO_TIMESTAMP_OLD
#define SO_TIMESTAMP_OLD 29
Definition at line 362 of file syscall.h.
SO_TIMESTAMPING_OLD
#define SO_TIMESTAMPING_OLD 37
Definition at line 364 of file syscall.h.
SO_TIMESTAMPNS_OLD
#define SO_TIMESTAMPNS_OLD 35
Definition at line 363 of file syscall.h.
socketcall
#define socketcall (nm, a, b, c, d, e, f) __syscall_ret(__socketcall(nm,a,b,c,d,e,f))
Definition at line 47 of file syscall.h.
socketcall_cp
#define socketcall_cp (nm, a, b, c, d, e, f) __syscall_ret(__socketcall_cp(nm,a,b,c,d,e,f))
Definition at line 48 of file syscall.h.
SYS_accept
#define SYS_accept SYS_accept4
Definition at line 352 of file syscall.h.
SYS_clock_adjtime
#define SYS_clock_adjtime SYS_clock_adjtime64
Definition at line 258 of file syscall.h.
SYS_clock_getres
#define SYS_clock_getres SYS_clock_getres_time64
Definition at line 262 of file syscall.h.
SYS_clock_gettime
#define SYS_clock_gettime SYS_clock_gettime64
Definition at line 250 of file syscall.h.
SYS_clock_nanosleep
#define SYS_clock_nanosleep SYS_clock_nanosleep_time64
Definition at line 266 of file syscall.h.
SYS_clock_settime
#define SYS_clock_settime SYS_clock_settime64
Definition at line 254 of file syscall.h.
SYS_futex
#define SYS_futex SYS_futex_time64
Definition at line 316 of file syscall.h.
SYS_mq_timedreceive
#define SYS_mq_timedreceive SYS_mq_timedreceive_time64
Definition at line 306 of file syscall.h.
SYS_mq_timedsend
#define SYS_mq_timedsend SYS_mq_timedsend_time64
Definition at line 302 of file syscall.h.
sys_open
#define sys_open (...) __syscall_ret(__sys_open(__VA_ARGS__))
Definition at line 389 of file syscall.h.
sys_open_cp
#define sys_open_cp (...) __syscall_ret(__sys_open_cp(__VA_ARGS__))
Definition at line 392 of file syscall.h.
SYS_ppoll
#define SYS_ppoll SYS_ppoll_time64
Definition at line 294 of file syscall.h.
SYS_pselect6
#define SYS_pselect6 SYS_pselect6_time64
Definition at line 290 of file syscall.h.
SYS_recvmmsg
#define SYS_recvmmsg SYS_recvmmsg_time64
Definition at line 298 of file syscall.h.
SYS_rt_sigtimedwait
#define SYS_rt_sigtimedwait SYS_rt_sigtimedwait_time64
Definition at line 312 of file syscall.h.
SYS_sched_rr_get_interval
#define SYS_sched_rr_get_interval SYS_sched_rr_get_interval_time64
Definition at line 320 of file syscall.h.
SYS_timer_gettime
#define SYS_timer_gettime SYS_timer_gettime64
Definition at line 270 of file syscall.h.
SYS_timer_settime
#define SYS_timer_settime SYS_timer_settime64
Definition at line 274 of file syscall.h.
SYS_timerfd_gettime
#define SYS_timerfd_gettime SYS_timerfd_gettime64
Definition at line 278 of file syscall.h.
SYS_timerfd_settime
#define SYS_timerfd_settime SYS_timerfd_settime64
Definition at line 282 of file syscall.h.
SYS_utimensat
#define SYS_utimensat SYS_utimensat_time64
Definition at line 286 of file syscall.h.
syscall
#define syscall (...) __syscall_ret(__syscall(__VA_ARGS__))
Definition at line 45 of file syscall.h.
syscall_cp
#define syscall_cp (...) __syscall_ret(__syscall_cp(__VA_ARGS__))
Definition at line 59 of file syscall.h.
SYSCALL_MMAP2_UNIT
#define SYSCALL_MMAP2_UNIT 4096ULL
Definition at line 14 of file syscall.h.
SYSCALL_RLIM_INFINITY
#define SYSCALL_RLIM_INFINITY (~0ULL)
Definition at line 10 of file syscall.h.
Typedef Documentation
syscall_arg_t
typedef long syscall_arg_t
Definition at line 23 of file syscall.h.
Function Documentation
__alt_socketcall()
static long __alt_socketcall (int sys, int sock, int cp, syscall_arg_t a, syscall_arg_t b, syscall_arg_t c, syscall_arg_t d, syscall_arg_t e, syscall_arg_t f) inline static
Definition at line 61 of file syscall.h.
 {
     long r;
     if (cp) r = __syscall_cp(sys, a, b, c, d, e, f);
     else r = __syscall(sys, a, b, c, d, e, f);
     if (r != -ENOSYS) return r;
 #ifdef SYS_socketcall
     if (cp) r = __syscall_cp(SYS_socketcall, sock, ((long[6]){a, b, c, d, e, f}));
     else r = __syscall(SYS_socketcall, sock, ((long[6]){a, b, c, d, e, f}));
 #endif
     return r;
 }
References __syscall, __syscall_cp, c, ENOSYS, f, and sock.
__procfdname()
hidden void __procfdname (char __buf[static 15+3 *sizeof(int)], unsigned)
__syscall_cp()
hidden long __syscall_cp (syscall_arg_t nr, syscall_arg_t u, syscall_arg_t v, syscall_arg_t w, syscall_arg_t x, syscall_arg_t y, syscall_arg_t z)
Definition at line 15 of file __syscall_cp.c.
 {
     return __syscall_cp_c(nr, u, v, w, x, y, z);
 }
References __syscall_cp_c(), w, x, and y.
__syscall_ret()
hidden long __syscall_ret (unsigned long)
Referenced by __clock_gettime(), __dup3(), __fstat(), __fstatat(), __futimesat(), __libc_sigaction(), __lseek(), __membarrier(), __mmap(), __setxid(), _Fork(), brk(), clock_adjtime(), clock_getres(), clock_settime(), clone(), close(), dup2(), epoll_create(), epoll_create1(), epoll_pwait(), eventfd(), faccessat(), fchdir(), fchmod(), fchmodat(), fchown(), fcntl(), fexecve(), getitimer(), getrusage(), getsockopt(), inotify_init1(), ioctl(), mq_timedreceive(), mq_timedsend(), msgctl(), nanosleep(), open(), pclose(), pipe2(), ppoll(), pselect(), readlink(), readlinkat(), recvmmsg(), remove(), sbrk(), sched_getaffinity(), sched_getcpu(), sched_getparam(), sched_getscheduler(), sched_rr_get_interval(), sched_setparam(), sched_setscheduler(), select(), semctl(), semget(), semtimedop(), setgroups(), setitimer(), setrlimit(), setsockopt(), settimeofday(), shmctl(), signalfd(), sigtimedwait(), socket(), sync_file_range(), syscall(), timer_gettime(), timer_settime(), timerfd_gettime(), timerfd_settime(), utimensat(), and wait4().
__vdsosym()
hidden void* __vdsosym (const char * , const char *)