Fennix Userspace: Userspace/apps/base/busybox/scripts/basic/docproc.c File Reference
docproc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/wait.h>
Data Structures
struct symbols
struct symfile
Macros
#define MAXLINESZ 2048
#define MAXFILES 250
#define KERNELDOCPATH "scripts/"
#define KERNELDOC "kernel-doc"
#define DOCBOOK "-docbook"
#define FUNCTION "-function"
#define NOFUNCTION "-nofunction"
Typedefs
typedef void DFL(char *)
typedef void FILEONLY(char *file)
typedef void FILELINE(char *file, char *line)
Functions
void usage (void)
void exec_kernel_doc (char **svec)
void add_new_symbol (struct symfile *sym, char *symname)
struct symfile * add_new_file (char *filename)
struct symfile * filename_exist (char *filename)
void adddep (char *file)
void adddep2 (char *file, char *line)
void noaction (char *line)
void noaction2 (char *file, char *line)
void printline (char *line)
void find_export_symbols (char *filename)
void docfunctions (char *filename, char *type)
void intfunc (char *filename)
void extfunc (char *filename)
void singfunc (char *filename, char *line)
void parse_file (FILE *infile)
int main (int argc, char **argv)
Variables
int exitstatus = 0
DFL * defaultline
FILEONLY * internalfunctions
FILEONLY * externalfunctions
FILEONLY * symbolsonly
FILELINE * singlefunctions
FILELINE * entity_system
struct symfile symfilelist [MAXFILES]
int symfilecnt = 0
Data Structure Documentation
symbols
struct symbols
Definition at line 112 of file docproc.c.
Data Fields
char * name
symfile
struct symfile
Definition at line 117 of file docproc.c.
Data Fields
char * filename
int symbolcnt
struct symbols * symbollist
Macro Definition Documentation
DOCBOOK
#define DOCBOOK "-docbook"
Definition at line 64 of file docproc.c.
FUNCTION
#define FUNCTION "-function"
Definition at line 65 of file docproc.c.
KERNELDOC
#define KERNELDOC "kernel-doc"
Definition at line 63 of file docproc.c.
KERNELDOCPATH
#define KERNELDOCPATH "scripts/"
Definition at line 62 of file docproc.c.
MAXFILES
#define MAXFILES 250
Definition at line 61 of file docproc.c.
MAXLINESZ
#define MAXLINESZ 2048
Definition at line 60 of file docproc.c.
NOFUNCTION
#define NOFUNCTION "-nofunction"
Definition at line 66 of file docproc.c.
Typedef Documentation
DFL
typedef void DFL(char *)
Definition at line 48 of file docproc.c.
FILELINE
typedef void FILELINE(char *file, char *line)
Definition at line 56 of file docproc.c.
FILEONLY
typedef void FILEONLY(char *file)
Definition at line 51 of file docproc.c.
Function Documentation
add_new_file()
struct symfile* add_new_file (char * filename)
Definition at line 135 of file docproc.c.
 {
     symfilelist[symfilecnt++].filename = strdup(filename);
     return &symfilelist[symfilecnt - 1];
 }
References filename, symfile::filename, strdup(), symfilecnt, and symfilelist.
Referenced by find_export_symbols().
add_new_symbol()
void add_new_symbol (struct symfile * sym, char * symname)
Definition at line 127 of file docproc.c.
 {
     sym->symbollist =
       realloc(sym->symbollist, (sym->symbolcnt + 1) * sizeof(char *));
     sym->symbollist[sym->symbolcnt++].name = strdup(symname);
 }
References symbols::name, realloc, strdup(), symfile::symbolcnt, and symfile::symbollist.
Referenced by find_export_symbols().
adddep()
void adddep (char * file)
Definition at line 154 of file docproc.c.
 { printf("\t%s", file); }
References printf().
Referenced by adddep2(), and main().
adddep2()
void adddep2 (char * file, char * line)
Definition at line 155 of file docproc.c.
 { line = line; adddep(file); }
References adddep(), and line.
Referenced by main().
docfunctions()
void docfunctions (char * filename, char * type)
Definition at line 221 of file docproc.c.
 {
     int i,j;
     int symcnt = 0;
     int idx = 0;
     char **vec;
     for (i=0; i <= symfilecnt; i++)
         symcnt += symfilelist[i].symbolcnt;
     vec = malloc((2 + 2 * symcnt + 2) * sizeof(char*));
     if (vec == NULL) {
         perror("docproc: ");
         exit(1);
     }
     vec[idx++] = KERNELDOC;
     vec[idx++] = DOCBOOK;
     for (i=0; i < symfilecnt; i++) {
         struct symfile * sym = &symfilelist[i];
         for (j=0; j < sym->symbolcnt; j++) {
             vec[idx++]     = type;
             vec[idx++] = sym->symbollist[j].name;
         }
     }
     vec[idx++]     = filename;
     vec[idx] = NULL;
     printf("<!-- %s -->\n", filename);
     exec_kernel_doc(vec);
     fflush(stdout);
     free(vec);
 }
References DOCBOOK, exec_kernel_doc(), exit(), fflush(), filename, free, i, idx, j, KERNELDOC, malloc, symbols::name, NULL, perror(), printf(), stdout, symfile::symbolcnt, symfile::symbollist, symfilecnt, symfilelist, and type.
Referenced by extfunc(), and intfunc().
exec_kernel_doc()
void exec_kernel_doc (char ** svec)
Definition at line 79 of file docproc.c.
 {
     pid_t pid;
     int ret;
     char *real_filename;
     int rflen;
     /* Make sure output generated so far are flushed */
     fflush(stdout);
     switch(pid=fork()) {
         case -1:
             perror("vfork"+1);
             exit(1);
         case  0:
             rflen  = strlen(getenv("SRCTREE"));
             rflen += strlen(KERNELDOCPATH KERNELDOC);
             real_filename = alloca(rflen + 1);
             strcpy(real_filename, getenv("SRCTREE"));
             strcat(real_filename, KERNELDOCPATH KERNELDOC);
             execvp(real_filename, svec);
             fprintf(stderr, "exec ");
             perror(real_filename);
             exit(1);
         default:
             waitpid(pid, &ret ,0);
     }
     if (WIFEXITED(ret))
         exitstatus |= WEXITSTATUS(ret);
     else
         exitstatus = 0xff;
 }
References alloca, execvp(), exit(), exitstatus, fflush(), fork(), fprintf(), getenv, KERNELDOC, KERNELDOCPATH, perror(), pid, stderr, stdout, strcat(), strcpy(), strlen(), waitpid(), WEXITSTATUS, and WIFEXITED.
Referenced by docfunctions(), and singfunc().
extfunc()
void extfunc (char * filename)
Definition at line 252 of file docproc.c.
 { docfunctions(filename, FUNCTION);   }
References docfunctions(), filename, and FUNCTION.
Referenced by main().
filename_exist()
struct symfile* filename_exist (char * filename)
Definition at line 141 of file docproc.c.
 {
     int i;
     for (i=0; i < symfilecnt; i++)
         if (strcmp(symfilelist[i].filename, filename) == 0)
             return &symfilelist[i];
     return NULL;
 }
References filename, i, NULL, strcmp, symfilecnt, and symfilelist.
Referenced by find_export_symbols().
find_export_symbols()
void find_export_symbols (char * filename)
Definition at line 167 of file docproc.c.
 {
     FILE * fp;
     struct symfile *sym;
     char line[MAXLINESZ];
     if (filename_exist(filename) == NULL) {
         int rflen = strlen(getenv("SRCTREE")) + strlen(filename);
         char *real_filename = alloca(rflen + 1);
         strcpy(real_filename, getenv("SRCTREE"));
         strcat(real_filename, filename);
         sym = add_new_file(filename);
         fp = fopen(real_filename, "r");
         if (fp == NULL)
         {
             fprintf(stderr, "docproc: ");
             perror(real_filename);
         }
         while (fgets(line, MAXLINESZ, fp)) {
             unsigned char *p;
             unsigned char *e;
             if (((p = (unsigned char *)strstr(line, "EXPORT_SYMBOL_GPL")) != 0) ||
                 ((p = (unsigned char *)strstr(line, "EXPORT_SYMBOL")) != 0)) {
                 /* Skip EXPORT_SYMBOL{_GPL} */
                 while (isalnum(*p) || *p == '_')
                     p++;
                 /* Remove paranteses and additional ws */
                 while (isspace(*p))
                     p++;
                 if (*p != '(')
                     continue; /* Syntax error? */
                 else
                     p++;
                 while (isspace(*p))
                     p++;
                 e = p;
                 while (isalnum(*e) || *e == '_')
                     e++;
                 *e = '\0';
                 add_new_symbol(sym, (char*)p);
             }
         }
         fclose(fp);
     }
 }
References add_new_file(), add_new_symbol(), alloca, fclose(), fgets, filename, filename_exist(), fopen(), fprintf(), getenv, isalnum, isspace, MAXLINESZ, NULL, p, perror(), stderr, strcat(), strcpy(), strlen(), and strstr().
Referenced by main().
intfunc()
void intfunc (char * filename)
Definition at line 251 of file docproc.c.
 {   docfunctions(filename, NOFUNCTION); }
References docfunctions(), filename, and NOFUNCTION.
Referenced by main().
main()
int main (int argc , char ** argv)
Definition at line 337 of file docproc.c.
 {
     FILE * infile;
     if (argc != 3) {
         usage();
         exit(1);
     }
     /* Open file, exit on error */
     infile = fopen(argv[2], "r");
     if (infile == NULL) {
         fprintf(stderr, "docproc: ");
         perror(argv[2]);
         exit(2);
     }
     if (strcmp("doc", argv[1]) == 0)
     {
         /* Need to do this in two passes.
          * First pass is used to collect all symbols exported
          * in the various files.
          * Second pass generate the documentation.
          * This is required because function are declared
          * and exported in different files :-((
          */
         /* Collect symbols */
         defaultline       = noaction;
         internalfunctions = find_export_symbols;
         externalfunctions = find_export_symbols;
         symbolsonly       = find_export_symbols;
         singlefunctions   = noaction2;
         parse_file(infile);
         /* Rewind to start from beginning of file again */
         fseek(infile, 0, SEEK_SET);
         defaultline       = printline;
         internalfunctions = intfunc;
         externalfunctions = extfunc;
         symbolsonly       = printline;
         singlefunctions   = singfunc;
         parse_file(infile);
     }
     else if (strcmp("depend", argv[1]) == 0)
     {
         /* Create first part of dependency chain
          * file.tmpl */
         printf("%s\t", argv[2]);
         defaultline       = noaction;
         internalfunctions = adddep;
         externalfunctions = adddep;
         symbolsonly       = adddep;
         singlefunctions   = adddep2;
         parse_file(infile);
         printf("\n");
     }
     else
     {
         fprintf(stderr, "Unknown option: %s\n", argv[1]);
         exit(1);
     }
     fclose(infile);
     fflush(stdout);
     return exitstatus;
 }
References adddep(), adddep2(), argc, argv, defaultline, exit(), exitstatus, externalfunctions, extfunc(), fclose(), fflush(), find_export_symbols(), fopen(), fprintf(), fseek(), infile, internalfunctions, intfunc(), noaction(), noaction2(), NULL, parse_file(), perror(), printf(), printline(), SEEK_SET, singfunc(), singlefunctions, stderr, stdout, strcmp, symbolsonly, and usage().
noaction()
void noaction (char * line)
Definition at line 156 of file docproc.c.
 { line = line; }
References line.
Referenced by main().
noaction2()
void noaction2 (char * file, char * line)
Definition at line 157 of file docproc.c.
 { file = file; line = line; }
References line.
Referenced by main().
parse_file()
void parse_file (FILE * infile)
Definition at line 293 of file docproc.c.
 {
     char line[MAXLINESZ];
     unsigned char * s;
     while (fgets(line, MAXLINESZ, infile)) {
         if (line[0] == '!') {
             s = (unsigned char *)line + 2;
             switch (line[1]) {
                 case 'E':
                     while (*s && !isspace(*s)) s++;
                     *s = '\0';
                     externalfunctions(line+2);
                     break;
                 case 'I':
                     while (*s && !isspace(*s)) s++;
                     *s = '\0';
                     internalfunctions(line+2);
                     break;
                 case 'D':
                     while (*s && !isspace(*s)) s++;
                     *s = '\0';
                     symbolsonly(line+2);
                     break;
                 case 'F':
                     /* filename */
                     while (*s && !isspace(*s)) s++;
                     *s++ = '\0';
                     /* function names */
                     while (isspace(*s))
                         s++;
                     singlefunctions(line +2, (char*)s);
                     break;
                 default:
                     defaultline(line);
             }
         }
         else {
             defaultline(line);
         }
     }
     fflush(stdout);
 }
References defaultline, externalfunctions, fflush(), fgets, infile, internalfunctions, isspace, MAXLINESZ, s, singlefunctions, stdout, and symbolsonly.
Referenced by main().
printline()
void printline (char * line)
Definition at line 160 of file docproc.c.
 { printf("%s", line); }
References printf().
Referenced by main().
singfunc()
void singfunc (char * filename, char * line)
Definition at line 259 of file docproc.c.
 {
     char *vec[200]; /* Enough for specific functions */
     int i, idx = 0;
     int startofsym = 1;
     vec[idx++] = KERNELDOC;
     vec[idx++] = DOCBOOK;
     /* Split line up in individual parameters preceded by FUNCTION */
     for (i=0; line[i]; i++) {
         if (isspace((unsigned char) line[i])) {
             line[i] = '\0';
             startofsym = 1;
             continue;
         }
         if (startofsym) {
             startofsym = 0;
             vec[idx++] = FUNCTION;
             vec[idx++] = &line[i];
         }
     }
     vec[idx++] = filename;
     vec[idx] = NULL;
     exec_kernel_doc(vec);
 }
References DOCBOOK, exec_kernel_doc(), filename, FUNCTION, i, idx, isspace, KERNELDOC, and NULL.
Referenced by main().
usage()
void usage (void)
Definition at line 68 of file docproc.c.
 {
     fprintf(stderr, "Usage: docproc {doc|depend} file\n");
     fprintf(stderr, "Input is read from file.tmpl. Output is sent to stdout\n");
     fprintf(stderr, "doc: frontend when generating kernel documentation\n");
     fprintf(stderr, "depend: generate list of files referenced within file\n");
 }
References fprintf(), and stderr.
Referenced by main().
Variable Documentation
defaultline
DFL* defaultline
Definition at line 49 of file docproc.c.
Referenced by main(), and parse_file().
entity_system
FILELINE* entity_system
Definition at line 58 of file docproc.c.
exitstatus
int exitstatus = 0
Definition at line 46 of file docproc.c.
Referenced by exec_kernel_doc(), IF_FEATURE_FIND_EXEC(), and main().
externalfunctions
FILEONLY* externalfunctions
Definition at line 53 of file docproc.c.
Referenced by main(), and parse_file().
internalfunctions
FILEONLY* internalfunctions
Definition at line 52 of file docproc.c.
Referenced by main(), and parse_file().
singlefunctions
FILELINE* singlefunctions
Definition at line 57 of file docproc.c.
Referenced by main(), and parse_file().
symbolsonly
FILEONLY* symbolsonly
Definition at line 54 of file docproc.c.
Referenced by main(), and parse_file().
symfilecnt
int symfilecnt = 0
Definition at line 125 of file docproc.c.
Referenced by add_new_file(), docfunctions(), and filename_exist().
symfilelist
struct symfile symfilelist[MAXFILES]
Definition at line 79 of file docproc.c.
Referenced by add_new_file(), docfunctions(), and filename_exist().