Fennix Userspace: Userspace/musl/include/sys/stat.h File Reference
stat.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/stat.h>
Macros
#define __NEED_dev_t
#define __NEED_ino_t
#define __NEED_mode_t
#define __NEED_nlink_t
#define __NEED_uid_t
#define __NEED_gid_t
#define __NEED_off_t
#define __NEED_time_t
#define __NEED_blksize_t
#define __NEED_blkcnt_t
#define __NEED_struct_timespec
#define st_atime st_atim.tv_sec
#define st_mtime st_mtim.tv_sec
#define st_ctime st_ctim.tv_sec
#define S_IFMT 0170000
#define S_IFDIR 0040000
#define S_IFCHR 0020000
#define S_IFBLK 0060000
#define S_IFREG 0100000
#define S_IFIFO 0010000
#define S_IFLNK 0120000
#define S_IFSOCK 0140000
#define S_TYPEISMQ(buf) 0
#define S_TYPEISSEM(buf) 0
#define S_TYPEISSHM(buf) 0
#define S_TYPEISTMO(buf) 0
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)
#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#define S_ISFIFO(mode) (((mode) & S_IFMT) == S_IFIFO)
#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)
#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)
#define S_ISUID 04000
#define S_ISGID 02000
#define S_ISVTX 01000
#define S_IRUSR 0400
#define S_IWUSR 0200
#define S_IXUSR 0100
#define S_IRWXU 0700
#define S_IRGRP 0040
#define S_IWGRP 0020
#define S_IXGRP 0010
#define S_IRWXG 0070
#define S_IROTH 0004
#define S_IWOTH 0002
#define S_IXOTH 0001
#define S_IRWXO 0007
#define UTIME_NOW 0x3fffffff
#define UTIME_OMIT 0x3ffffffe
Functions
int stat (const char *__restrict, struct stat *__restrict)
int fstat (int, struct stat *)
int lstat (const char *__restrict, struct stat *__restrict)
int fstatat (int, const char *__restrict, struct stat *__restrict, int)
int chmod (const char *, mode_t)
int fchmod (int, mode_t)
int fchmodat (int, const char *, mode_t, int)
mode_t umask (mode_t)
int mkdir (const char *, mode_t)
int mkfifo (const char *, mode_t)
int mkdirat (int, const char *, mode_t)
int mkfifoat (int, const char *, mode_t)
int futimens (int, const struct timespec[2])
int utimensat (int, const char *, const struct timespec[2], int)
Macro Definition Documentation
__NEED_blkcnt_t
#define __NEED_blkcnt_t
Definition at line 18 of file stat.h.
__NEED_blksize_t
#define __NEED_blksize_t
Definition at line 17 of file stat.h.
__NEED_dev_t
#define __NEED_dev_t
Definition at line 9 of file stat.h.
__NEED_gid_t
#define __NEED_gid_t
Definition at line 14 of file stat.h.
__NEED_ino_t
#define __NEED_ino_t
Definition at line 10 of file stat.h.
__NEED_mode_t
#define __NEED_mode_t
Definition at line 11 of file stat.h.
__NEED_nlink_t
#define __NEED_nlink_t
Definition at line 12 of file stat.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 15 of file stat.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 19 of file stat.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 16 of file stat.h.
__NEED_uid_t
#define __NEED_uid_t
Definition at line 13 of file stat.h.
S_IFBLK
#define S_IFBLK 0060000
Definition at line 33 of file stat.h.
S_IFCHR
#define S_IFCHR 0020000
Definition at line 32 of file stat.h.
S_IFDIR
#define S_IFDIR 0040000
Definition at line 31 of file stat.h.
S_IFIFO
#define S_IFIFO 0010000
Definition at line 35 of file stat.h.
S_IFLNK
#define S_IFLNK 0120000
Definition at line 36 of file stat.h.
S_IFMT
#define S_IFMT 0170000
Definition at line 29 of file stat.h.
S_IFREG
#define S_IFREG 0100000
Definition at line 34 of file stat.h.
S_IFSOCK
#define S_IFSOCK 0140000
Definition at line 37 of file stat.h.
S_IRGRP
#define S_IRGRP 0040
Definition at line 60 of file stat.h.
S_IROTH
#define S_IROTH 0004
Definition at line 64 of file stat.h.
S_IRUSR
#define S_IRUSR 0400
Definition at line 56 of file stat.h.
S_IRWXG
#define S_IRWXG 0070
Definition at line 63 of file stat.h.
S_IRWXO
#define S_IRWXO 0007
Definition at line 67 of file stat.h.
S_IRWXU
#define S_IRWXU 0700
Definition at line 59 of file stat.h.
S_ISBLK
#define S_ISBLK (mode) (((mode) & S_IFMT) == S_IFBLK)
Definition at line 46 of file stat.h.
S_ISCHR
#define S_ISCHR (mode) (((mode) & S_IFMT) == S_IFCHR)
Definition at line 45 of file stat.h.
S_ISDIR
#define S_ISDIR (mode) (((mode) & S_IFMT) == S_IFDIR)
Definition at line 44 of file stat.h.
S_ISFIFO
#define S_ISFIFO (mode) (((mode) & S_IFMT) == S_IFIFO)
Definition at line 48 of file stat.h.
S_ISGID
#define S_ISGID 02000
Definition at line 54 of file stat.h.
S_ISLNK
#define S_ISLNK (mode) (((mode) & S_IFMT) == S_IFLNK)
Definition at line 49 of file stat.h.
S_ISREG
#define S_ISREG (mode) (((mode) & S_IFMT) == S_IFREG)
Definition at line 47 of file stat.h.
S_ISSOCK
#define S_ISSOCK (mode) (((mode) & S_IFMT) == S_IFSOCK)
Definition at line 50 of file stat.h.
S_ISUID
#define S_ISUID 04000
Definition at line 53 of file stat.h.
S_ISVTX
#define S_ISVTX 01000
Definition at line 55 of file stat.h.
S_IWGRP
#define S_IWGRP 0020
Definition at line 61 of file stat.h.
S_IWOTH
#define S_IWOTH 0002
Definition at line 65 of file stat.h.
S_IWUSR
#define S_IWUSR 0200
Definition at line 57 of file stat.h.
S_IXGRP
#define S_IXGRP 0010
Definition at line 62 of file stat.h.
S_IXOTH
#define S_IXOTH 0001
Definition at line 66 of file stat.h.
S_IXUSR
#define S_IXUSR 0100
Definition at line 58 of file stat.h.
S_TYPEISMQ
#define S_TYPEISMQ (buf) 0
Definition at line 39 of file stat.h.
S_TYPEISSEM
#define S_TYPEISSEM (buf) 0
Definition at line 40 of file stat.h.
S_TYPEISSHM
#define S_TYPEISSHM (buf) 0
Definition at line 41 of file stat.h.
S_TYPEISTMO
#define S_TYPEISTMO (buf) 0
Definition at line 42 of file stat.h.
st_atime
#define st_atime st_atim.tv_sec
Definition at line 25 of file stat.h.
st_ctime
#define st_ctime st_ctim.tv_sec
Definition at line 27 of file stat.h.
st_mtime
#define st_mtime st_mtim.tv_sec
Definition at line 26 of file stat.h.
UTIME_NOW
#define UTIME_NOW 0x3fffffff
Definition at line 70 of file stat.h.
UTIME_OMIT
#define UTIME_OMIT 0x3ffffffe
Definition at line 71 of file stat.h.
Function Documentation
chmod()
int chmod (const char * pathname, mode_t mode)
Definition at line 9 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_chmod, -1);
     if(int e = mlibc::sys_chmod(pathname, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_chmod(), and syscall().
Referenced by make_path().
fchmod()
int fchmod (int fd, mode_t mode)
Definition at line 18 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchmod, -1);
     if(int e = mlibc::sys_fchmod(fd, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __procfdname(), __syscall, __syscall_ret(), AT_FDCWD, buf, EBADF, errno, F_GETFD, int, MLIBC_CHECK_OR_ENOSYS, ret, mlibc::sys_fchmod(), and syscall().
Referenced by here_document_to_fd().
fchmodat()
int fchmodat (int dirfd, const char * pathname, mode_t mode, int flags)
Definition at line 27 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchmodat, -1);
     if(int e = mlibc::sys_fchmodat(dirfd, pathname, mode, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __procfdname(), __syscall, __syscall_ret(), AT_FDCWD, AT_SYMLINK_NOFOLLOW, dirfd, EINVAL, ELOOP, EOPNOTSUPP, errno, flags, fstatat(), int, MLIBC_CHECK_OR_ENOSYS, O_CLOEXEC, O_NOCTTY, O_NOFOLLOW, O_PATH, O_RDONLY, ret, S_ISLNK, stat(), mlibc::sys_fchmodat(), and syscall().
Referenced by lchmod().
fstat()
int fstat (int fd, struct stat * result)
Definition at line 147 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::fd, fd, "", 0, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_stat().
Referenced by __fstat_time32(), __fxstat(), _evalfile(), _nl_load_domain(), _rl_read_file(), fdopendir(), getspnam_r(), getstat(), here_document_to_fd(), history_truncate_file(), isnetconn(), load_library(), main(), noclobber_open(), open_shell_script(), read_history_range(), sem_open(), sh_stat(), and ttyname_r().
fstatat()
int fstatat (int dirfd, const char * __restrict, struct stat * __restrict, int flags)
Definition at line 36 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::fd_path, dirfd, path, flags, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd, errno, mlibc::fd_path, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_stat().
Referenced by __fstatat_time32(), __fxstatat(), fchmodat(), lstat(), and stat().
futimens()
int futimens (int fd, const struct timespec times[2])
Definition at line 45 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     if (int e = mlibc::sys_utimensat(fd, nullptr, times, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_utimensat(), times(), and utimensat().
Referenced by __futimens_time32(), and futimes().
lstat()
int lstat (const char * __restrict, struct stat * __restrict)
Definition at line 137 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::path,
             -1, path, AT_SYMLINK_NOFOLLOW, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_SYMLINK_NOFOLLOW, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::path, and mlibc::sys_stat().
mkdir()
int mkdir (const char * path, mode_t mode)
Definition at line 5 of file sys_stat.c.
 {
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_mkdir(), and syscall().
Referenced by make_path(), and mkdir_builtin().
mkdirat()
int mkdirat (int dirfd, const char * path, mode_t mode)
Definition at line 65 of file sys-stat-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31mmlibc: mkdirat() ignores its mode\e[39m" << frg::endlog;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mkdirat, -1);
     if(int e = mlibc::sys_mkdirat(dirfd, path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd, errno, mlibc::infoLogger, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_mkdirat(), and syscall().
mkfifo()
int mkfifo (const char * path, mode_t mode)
Definition at line 75 of file sys-stat-stubs.cpp.
{
     return mkfifoat(AT_FDCWD, path, mode);
 }
References AT_FDCWD, mkfifoat(), mknod(), and S_IFIFO.
Referenced by mkfifo_builtin().
mkfifoat()
int mkfifoat (int dirfd, const char * path, mode_t mode)
Definition at line 79 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mkfifoat, -1);
     if (int e = mlibc::sys_mkfifoat(dirfd, path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd, errno, mknodat(), MLIBC_CHECK_OR_ENOSYS, S_IFIFO, and mlibc::sys_mkfifoat().
Referenced by mkfifo().
stat()
int stat (const char * __restrict, struct stat * __restrict)
Definition at line 128 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::path, -1, path, 0, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::path, and mlibc::sys_stat().
Referenced by __stat_time32(), __xstat(), _path_isdir(), _rl_print_color_indicator(), append_to_match(), do_glob(), do_nftw(), fchmodat(), ftok(), get_current_dir_name(), getstat(), glob_testdir(), history_do_write(), ln_builtin(), mailstat(), mktemp(), noclobber_open(), read_man_page(), realpath_builtin(), scan_request(), sh_mktmpname(), stat_char(), and ttyname_r().
umask()
mode_t umask (mode_t mode)
Definition at line 103 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_umask, -1);
     mode_t old;
     if (int e = mlibc::sys_umask(mode, &old); e) {
         errno = e;
         return -1;
     }
     return old;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_umask(), and syscall().
Referenced by make_path(), mkdir_builtin(), and mkfifo_builtin().
utimensat()
int utimensat (int dirfd, const char * pathname, const struct timespec times[2], int flags)
Definition at line 113 of file sys-stat-stubs.cpp.
{
     if(pathname == nullptr) {
         errno = EINVAL;
         return -1;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     if (int e = mlibc::sys_utimensat(dirfd, pathname, times, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __syscall, __syscall_ret(), AT_FDCWD, dirfd, EINVAL, ENOSYS, ENOTSUP, errno, flags, i, IS32BIT, MLIBC_CHECK_OR_ENOSYS, NS_SPECIAL, r, s0, s1, mlibc::sys_utimensat(), SYS_utimensat, SYS_utimensat_time64, times(), and UTIME_NOW.
Referenced by __futimesat(), __utimensat_time32(), futimens(), lutimes(), and utime().