Fennix: Userspace/apps/base/bash/subst.c File Reference
subst.c File Reference
#include "config.h"
#include "bashtypes.h"
#include <stdio.h>
#include "chartypes.h"
#include <signal.h>
#include <errno.h>
#include "bashansi.h"
#include "posixstat.h"
#include "bashintl.h"
#include "shell.h"
#include "parser.h"
#include "redir.h"
#include "flags.h"
#include "jobs.h"
#include "execute_cmd.h"
#include "filecntl.h"
#include "trap.h"
#include "pathexp.h"
#include "mailcheck.h"
#include "shmbutil.h"
#include "typemax.h"
#include "builtins/getopt.h"
#include "builtins/common.h"
#include "builtins/builtext.h"
#include <tilde/tilde.h>
#include <glob/strmatch.h>
Macros
#define NEED_FPURGE_DECL
#define DEFAULT_INITIAL_ARRAY_SIZE 112
#define DEFAULT_ARRAY_SIZE 128
#define VT_VARIABLE 0
#define VT_POSPARMS 1
#define VT_ARRAYVAR 2
#define VT_ARRAYMEMBER 3
#define VT_ASSOCVAR 4
#define VT_STARSUB 128 /* $* or ${array[*]} -- used to split */
#define ST_BACKSL 0x01
#define ST_CTLESC 0x02
#define ST_SQUOTE 0x04 /* unused yet */
#define ST_DQUOTE 0x08 /* unused yet */
#define LBRACE '{'
#define RBRACE '}'
#define LPAREN '('
#define RPAREN ')'
#define LBRACK '['
#define RBRACK ']'
#define DOLLAR_AT_STAR(c) ((c) == '@' || (c) == '*')
#define STR_DOLLAR_AT_STAR(s) (DOLLAR_AT_STAR ((s)[0]) && (s)[1] == '\0')
#define VALID_SPECIAL_LENGTH_PARAM(c) ((c) == '-' || (c) == '?' || (c) == '#' || (c) == '@')
#define VALID_INDIR_PARAM(c) ((posixly_correct == 0 && (c) == '#') || (posixly_correct == 0 && (c) == '?') || (c) == '@' || (c) == '*')
#define VALID_PARAM_EXPAND_CHAR(c) (sh_syntaxtab[(unsigned char)c] & CSUBSTOP)
#define SPECIAL_VAR(name, wi)
#define CHECK_STRING_OVERRUN(oind, ind, len, ch)
#define PARAMEXPNEST_MAX 32
#define CQ_RETURN(x) do { no_longjmp_on_fatal_error = oldjmp; return (x); } while (0)
#define issep(c)
#define ifs_whitespace(c) ISSPACE(c)
#define ifs_whitesep(c)
#define islocalsep(c) (local_cmap[(unsigned char)(c)] != 0)
#define ASSIGN_RETURN(r) do { FREE (value); free (name); return (r); } while (0)
#define EXP_CHAR(s) (s == '$' || s == '`' || s == CTLESC || s == '~')
#define ARITH_EXP_CHAR(s) (s == '$' || s == '`' || s == CTLESC || s == '~')
#define RP_LONG_LEFT 1
#define RP_SHORT_LEFT 2
#define RP_LONG_RIGHT 3
#define RP_SHORT_RIGHT 4
#define COMSUB_PIPEBUF 4096
#define UNQUOTED 0
#define PARTIALLY_QUOTED 1
#define WHOLLY_QUOTED 2
#define PREPEND_LIST(nlist, elist) do { nlist->next = elist; elist = nlist; } while (0)
#define WEXP_VARASSIGN 0x001
#define WEXP_BRACEEXP 0x002
#define WEXP_TILDEEXP 0x004
#define WEXP_PARAMEXP 0x008
#define WEXP_PATHEXP 0x010
#define WEXP_ALL (WEXP_VARASSIGN|WEXP_BRACEEXP|WEXP_TILDEEXP|WEXP_PARAMEXP|WEXP_PATHEXP)
#define WEXP_NOVARS (WEXP_BRACEEXP|WEXP_TILDEEXP|WEXP_PARAMEXP|WEXP_PATHEXP)
#define WEXP_SHELLEXP (WEXP_BRACEEXP|WEXP_TILDEEXP|WEXP_PARAMEXP)
Typedefs
typedef WORD_LIST *EXPFUNC PARAMS((char *, int))
Functions
static char *quoted_substring PARAMS ((char *, int, int))
static int quoted_strlen PARAMS ((char *))
static char *expand_string_if_necessary PARAMS ((char *, int, EXPFUNC *))
static WORD_LIST *call_expand_word_internal PARAMS ((WORD_DESC *, int, int, int *, int *))
static WORD_LIST *expand_string_for_rhs PARAMS ((char *, int, int, int, int *, int *))
static WORD_LIST *expand_string_for_pat PARAMS ((char *, int, int *, int *))
static char *quote_escapes_internal PARAMS ((const char *, int))
static WORD_LIST *list_quote_escapes PARAMS ((WORD_LIST *))
static char *make_quoted_char PARAMS ((int))
static int unquoted_substring PARAMS ((char *, char *))
static int unquoted_member PARAMS ((int, char *))
static int do_assignment_internal PARAMS ((const WORD_DESC *, int))
static char *string_extract_verbatim PARAMS ((char *, size_t, int *, char *, int))
static char *string_extract PARAMS ((char *, int *, char *, int))
static char *string_extract_double_quoted PARAMS ((char *, int *, int))
static int skip_single_quoted PARAMS ((const char *, size_t, int, int))
static int skip_double_quoted PARAMS ((char *, size_t, int, int))
static char *extract_delimited_string PARAMS ((char *, int *, char *, char *, char *, int))
static char *extract_heredoc_dolbrace_string PARAMS ((char *, int *, int, int))
static int skip_matched_pair PARAMS ((const char *, int, int, int, int))
static char *pos_params PARAMS ((char *, int, int, int, int))
static char *remove_upattern PARAMS ((char *, char *, int))
static int match_upattern PARAMS ((char *, char *, int, char **, char **))
static char *variable_remove_pattern PARAMS ((char *, char *, int, int))
static char *list_remove_pattern PARAMS ((WORD_LIST *, char *, int, int, int))
static char *parameter_list_remove_pattern PARAMS ((int, char *, int, int))
static char *parameter_brace_remove_pattern PARAMS ((char *, char *, array_eltstate_t *, char *, int, int, int))
static char *string_var_assignment PARAMS ((SHELL_VAR *, char *))
static char *pos_params_assignment PARAMS ((WORD_LIST *, int, int))
static char *string_transform PARAMS ((int, SHELL_VAR *, char *))
static char *list_transform PARAMS ((int, SHELL_VAR *, WORD_LIST *, int, int))
static char *parameter_list_transform PARAMS ((int, int, int))
static char *parameter_brace_transform PARAMS ((char *, char *, array_eltstate_t *, char *, int, int, int, int))
static char *optimize_cat_file PARAMS ((REDIRECT *, int, int, int *))
static char *read_comsub PARAMS ((int, int, int, int *))
static int chk_atstar PARAMS ((char *, int, int, int *, int *))
static WORD_DESC *parameter_brace_expand_word PARAMS ((char *, int, int, int, array_eltstate_t *))
static char *parameter_brace_find_indir PARAMS ((char *, int, int, int))
static WORD_DESC *parameter_brace_expand_rhs PARAMS ((char *, char *, int, int, int, int *, int *))
static int verify_substring_values PARAMS ((SHELL_VAR *, char *, char *, int, intmax_t *, intmax_t *))
static int get_var_and_type PARAMS ((char *, char *, array_eltstate_t *, int, int, SHELL_VAR **, char **))
static char *pos_params_pat_subst PARAMS ((char *, char *, char *, int))
static char *parameter_brace_casemod PARAMS ((char *, char *, array_eltstate_t *, int, char *, int, int, int))
static WORD_DESC *parameter_brace_expand PARAMS ((char *, int *, int, int, int *, int *))
static WORD_DESC *param_expand PARAMS ((char *, int *, int, int *, int *, int *, int *, int))
static WORD_LIST *glob_expand_word_list PARAMS ((WORD_LIST *, int))
static int do_assignment_statements PARAMS ((WORD_LIST *, char *, int))
INLINE char * sub_append_string (char *source, char *target, size_t *indx, size_t *size)
static char * string_extract (char *string, int *sindex, char *charlist, int flags)
static char * string_extract_double_quoted (char *string, int *sindex, int flags)
static int skip_double_quoted (char *string, size_t slen, int sind, int flags)
static char * string_extract_single_quoted (char *string, int *sindex, int allowesc)
static int skip_single_quoted (char *string, size_t slen, int sind, int flags) const
static char * string_extract_verbatim (char *string, size_t slen, int *sindex, char *charlist, int flags)
char * extract_command_subst (char *string, int *sindex, int xflags)
char * extract_arithmetic_subst (char *string, int *sindex)
static char * extract_delimited_string (char *string, int *sindex, char *opener, char *alt_opener, char *closer, int flags)
static char * extract_heredoc_dolbrace_string (char *string, int *sindex, int quoted, int flags)
static char * extract_dollar_brace_string (char *string, int *sindex, int quoted, int flags)
char * de_backslash (char *string)
static int skip_matched_pair (char *string, int start, int open, int close, int flags) const
int skip_to_delim (char *string, int start, char *delims, int flags)
char * string_list_internal (WORD_LIST *list, char *sep)
char * string_list (WORD_LIST *list)
char * ifs_firstchar (int *lenp)
char * string_list_dollar_star (WORD_LIST *list, int quoted, int flags)
char * string_list_dollar_at (WORD_LIST *list, int quoted, int flags)
char * string_list_pos_params (int pchar, WORD_LIST *list, int quoted, int pflags)
WORD_LIST * list_string (char *string, char *separators, int quoted)
char * get_word_from_string (char **stringp, char *separators, char **endptr)
char * strip_trailing_ifs_whitespace (char *string, char *separators, int saw_escape)
static int do_assignment_internal (WORD_DESC *word, int expand) const
int do_assignment (char *string)
int do_word_assignment (WORD_DESC *word, int flags)
int do_assignment_no_expand (char *string)
WORD_LIST * list_rest_of_args ()
char * get_dollar_var_value (intmax_t ind)
char * string_rest_of_args (int dollar_star)
static char * pos_params (char *string, int start, int end, int quoted, int pflags)
static char * expand_string_if_necessary (char *string, int quoted, EXPFUNC *func)
static char * expand_string_to_string_internal (char *string, int quoted, EXPFUNC *func)
char * expand_string_to_string (char *string, int quoted)
char * expand_string_unsplit_to_string (char *string, int quoted)
char * expand_assignment_string_to_string (char *string, int quoted)
static char * quote_string_for_repl (char *string, int flags)
static char * expand_string_for_patsub (char *string, int quoted)
char * expand_arith_string (char *string, int quoted)
char * expand_string_dollar_quote (char *string, int flags)
static WORD_LIST * call_expand_word_internal (WORD_DESC *w, int q, int i, int *c, int *e)
static WORD_LIST * expand_string_internal (char *string, int quoted)
WORD_LIST * expand_string_unsplit (char *string, int quoted)
WORD_LIST * expand_string_assignment (char *string, int quoted)
WORD_LIST * expand_prompt_string (char *string, int quoted, int wflags)
static WORD_LIST * expand_string_leave_quoted (char *string, int quoted)
static WORD_LIST * expand_string_for_rhs (char *string, int quoted, int op, int pflags, int *dollar_at_p, int *expanded_p)
static WORD_LIST * expand_string_for_pat (char *string, int quoted, int *dollar_at_p, int *expanded_p)
WORD_LIST * expand_string (char *string, int quoted)
WORD_LIST * expand_word (WORD_DESC *word, int quoted)
WORD_LIST * expand_word_unsplit (WORD_DESC *word, int quoted)
WORD_LIST * expand_word_leave_quoted (WORD_DESC *word, int quoted)
static char * quote_escapes_internal (char *string, int flags) const
char * quote_escapes (char *string) const
char * quote_rhs (char *string) const
static WORD_LIST * list_quote_escapes (WORD_LIST *list)
char * dequote_escapes (char *string) const
static char * make_quoted_char (int c)
char * quote_string (char *string)
char * dequote_string (char *string)
static WORD_LIST * quote_list (WORD_LIST *list)
WORD_DESC * dequote_word (WORD_DESC *word)
WORD_LIST * dequote_list (WORD_LIST *list)
char * remove_quoted_escapes (char *string)
char * remove_quoted_ifs (char *string)
char * remove_quoted_nulls (char *string)
void word_list_remove_quoted_nulls (WORD_LIST *list)
static char * remove_upattern (char *param, char *pattern, int op)
static char * remove_pattern (char *param, char *pattern, int op)
static int match_upattern (char *string, char *pat, int mtype, char **sp, char **ep)
static int match_pattern (char *string, char *pat, int mtype, char **sp, char **ep)
static int getpatspec (int c, char *value)
static char * getpattern (char *value, int quoted, int expandpat)
static char * list_remove_pattern (WORD_LIST *list, char *pattern, int patspec, int itype, int quoted)
static char * parameter_list_remove_pattern (int itype, char *pattern, int patspec, int quoted)
static char * parameter_brace_remove_pattern (char *varname, char *value, array_eltstate_t *estatep, char *patstr, int rtype, int quoted, int flags)
static char * optimize_cat_file (REDIRECT *r, int quoted, int flags, int *flagp)
static char * read_comsub (int fd, int quoted, int flags, int *rflag)
WORD_DESC * command_substitute (char *string, int quoted, int flags)
static int valid_brace_expansion_word (char *name, int var_is_special)
static int chk_atstar (char *name, int quoted, int pflags, int *quoted_dollar_atp, int *contains_dollar_at)
static WORD_DESC * parameter_brace_expand_word (char *name, int var_is_special, int quoted, int pflags, array_eltstate_t *estatep)
static char * parameter_brace_find_indir (char *name, int var_is_special, int quoted, int find_nameref)
static WORD_DESC * parameter_brace_expand_indir (char *name, int var_is_special, int quoted, int pflags, int *quoted_dollar_atp, int *contains_dollar_at)
static WORD_DESC * parameter_brace_expand_rhs (char *name, char *value, int op, int quoted, int pflags, int *qdollaratp, int *hasdollarat)
static void parameter_brace_expand_error (char *name, char *value, int check_null)
static int valid_length_expression (char *name)
static intmax_t parameter_brace_expand_length (char *name)
static char * skiparith (char *substr, int delim)
static int verify_substring_values (SHELL_VAR *v, char *value, char *substr, int vtype, intmax_t *e1p, intmax_t *e2p)
static int get_var_and_type (char *varname, char *value, array_eltstate_t *estatep, int quoted, int flags, SHELL_VAR **varp, char **valp)
static char * string_var_assignment (SHELL_VAR *v, char *s)
static char * pos_params_assignment (WORD_LIST *list, int itype, int quoted)
static char * string_transform (int xc, SHELL_VAR *v, char *s)
static char * list_transform (int xc, SHELL_VAR *v, WORD_LIST *list, int itype, int quoted)
static char * parameter_list_transform (int xc, int itype, int quoted)
static int valid_parameter_transform (char *xform)
static char * parameter_brace_transform (char *varname, char *value, array_eltstate_t *estatep, char *xform, int rtype, int quoted, int pflags, int flags)
static char * parameter_brace_substring (char *varname, char *value, array_eltstate_t *estatep, char *substr, int quoted, int pflags, int flags)
static int shouldexp_replacement (char *s)
char * pat_subst (char *string, char *pat, char *rep, int mflags)
static char * pos_params_pat_subst (char *string, char *pat, char *rep, int mflags)
static char * parameter_brace_patsub (char *varname, char *value, array_eltstate_t *estatep, char *patsub, int quoted, int pflags, int flags)
static char * pos_params_modcase (char *string, char *pat, int modop, int mflags)
static char * parameter_brace_casemod (char *varname, char *value, array_eltstate_t *estatep, int modspec, char *patspec, int quoted, int pflags, int flags)
static int chk_arithsub (char *s, int len) const
static WORD_DESC * parameter_brace_expand (char *string, int *indexp, int quoted, int pflags, int *quoted_dollar_atp, int *contains_dollar_at)
static WORD_DESC * param_expand (char *string, int *sindex, int quoted, int *expanded_something, int *contains_dollar_at, int *quoted_dollar_at_p, int *had_quoted_null_p, int pflags)
void invalidate_cached_quoted_dollar_at ()
static WORD_LIST * expand_word_internal (WORD_DESC *word, int quoted, int isexp, int *contains_dollar_at, int *expanded_something)
char * string_quote_removal (char *string, int quoted)
void setifs (SHELL_VAR *v)
char * getifs ()
WORD_LIST * word_split (WORD_DESC *w, char *ifs_chars)
static WORD_LIST * word_list_split (WORD_LIST *list)
static void exp_jump_to_top_level (int v)
static WORD_LIST * separate_out_assignments (WORD_LIST *tlist)
WORD_LIST * expand_words (WORD_LIST *list)
WORD_LIST * expand_words_no_vars (WORD_LIST *list)
WORD_LIST * expand_words_shellexp (WORD_LIST *list)
static WORD_LIST * glob_expand_word_list (WORD_LIST *tlist, int eflags)
static WORD_LIST * shell_expand_word_list (WORD_LIST *tlist, int eflags)
static int do_assignment_statements (WORD_LIST *varlist, char *command, int is_nullcmd)
static WORD_LIST * expand_word_list_internal (WORD_LIST *list, int eflags)
Variables
int errno
pid_t last_command_subst_pid = NO_PID
pid_t current_command_subst_pid = NO_PID
SHELL_VAR * ifs_var
char * ifs_value
unsigned char ifs_cmap [UCHAR_MAX+1]
int ifs_is_set
int ifs_is_null
unsigned char ifs_firstc
int inherit_errexit = 0
int assigning_in_environment
WORD_LIST * subst_assign_varlist = (WORD_LIST *)NULL
int no_longjmp_on_fatal_error = 0
int allow_null_glob_expansion
int fail_glob_expansion
int patsub_replacement = 1
struct fd_bitmap * current_fds_to_close
int wordexp_only
int singlequote_translations
int extended_quote
static WORD_LIST * cached_quoted_dollar_at = 0
static WORD_LIST expand_word_error
static WORD_LIST expand_word_fatal
static WORD_DESC expand_wdesc_error
static WORD_DESC expand_wdesc_fatal
static char expand_param_error
static char expand_param_fatal
static char expand_param_unset
static char extract_string_error
static char extract_string_fatal
static int expand_no_split_dollar_star = 0
static WORD_LIST * garglist = (WORD_LIST *)NULL
static int dbstate [PARAMEXPNEST_MAX]
Macro Definition Documentation
ARITH_EXP_CHAR
#define ARITH_EXP_CHAR (s) (s == '$' || s == '`' || s == CTLESC || s == '~')
Definition at line 3824 of file subst.c.
ASSIGN_RETURN
#define ASSIGN_RETURN (r) do { FREE (value); free (name); return (r); } while (0)
CHECK_STRING_OVERRUN
#define CHECK_STRING_OVERRUN (oind, ind, len, ch)
Value:
  if (ind >= len) \
    { \
      oind = len; \
      ch = 0; \
      break; \
    } \
  else \
Definition at line 135 of file subst.c.
COMSUB_PIPEBUF
#define COMSUB_PIPEBUF 4096
Definition at line 6763 of file subst.c.
CQ_RETURN
#define CQ_RETURN (x) do { no_longjmp_on_fatal_error = oldjmp; return (x); } while (0)
Definition at line 2052 of file subst.c.
DEFAULT_ARRAY_SIZE
#define DEFAULT_ARRAY_SIZE 128
Definition at line 77 of file subst.c.
DEFAULT_INITIAL_ARRAY_SIZE
#define DEFAULT_INITIAL_ARRAY_SIZE 112
Definition at line 76 of file subst.c.
DOLLAR_AT_STAR
#define DOLLAR_AT_STAR (c) ((c) == '@' || (c) == '*')
Definition at line 107 of file subst.c.
EXP_CHAR
#define EXP_CHAR (s) (s == '$' || s == '`' || s == CTLESC || s == '~')
Definition at line 3819 of file subst.c.
ifs_whitesep
#define ifs_whitesep (c)
Value:
                                 ((sh_style_split || separators == 0) ? spctabnl (c) \
                                 : ifs_whitespace (c))
Definition at line 3126 of file subst.c.
ifs_whitespace
#define ifs_whitespace (c) ISSPACE(c)
Definition at line 3123 of file subst.c.
islocalsep
#define islocalsep (c) (local_cmap[(unsigned char)(c)] != 0)
Definition at line 3280 of file subst.c.
issep
#define issep (c)
Value:
    (((separators)[0]) ? ((separators)[1] ? isifs(c) \
                          : (c) == (separators)[0]) \
               : 0)
Definition at line 3117 of file subst.c.
LBRACE
#define LBRACE '{'
Definition at line 95 of file subst.c.
LBRACK
#define LBRACK '['
Definition at line 99 of file subst.c.
LPAREN
#define LPAREN '('
Definition at line 97 of file subst.c.
NEED_FPURGE_DECL
#define NEED_FPURGE_DECL
Definition at line 40 of file subst.c.
PARAMEXPNEST_MAX
#define PARAMEXPNEST_MAX 32
Definition at line 1801 of file subst.c.
PARTIALLY_QUOTED
#define PARTIALLY_QUOTED 1
Definition at line 10924 of file subst.c.
PREPEND_LIST
#define PREPEND_LIST (nlist, elist) do { nlist->next = elist; elist = nlist; } while (0)
Definition at line 12157 of file subst.c.
RBRACE
#define RBRACE '}'
Definition at line 96 of file subst.c.
RBRACK
#define RBRACK ']'
Definition at line 100 of file subst.c.
RP_LONG_LEFT
#define RP_LONG_LEFT 1
Definition at line 5141 of file subst.c.
RP_LONG_RIGHT
#define RP_LONG_RIGHT 3
Definition at line 5143 of file subst.c.
RP_SHORT_LEFT
#define RP_SHORT_LEFT 2
Definition at line 5142 of file subst.c.
RP_SHORT_RIGHT
#define RP_SHORT_RIGHT 4
Definition at line 5144 of file subst.c.
RPAREN
#define RPAREN ')'
Definition at line 98 of file subst.c.
SPECIAL_VAR
#define SPECIAL_VAR (name, wi)
Value:
 (*name && ((DIGIT (*name) && all_digits (name)) || \
      (name[1] == '\0' && (sh_syntaxtab[(unsigned char)*name] & CSPECVAR)) || \
      (wi && name[2] == '\0' && VALID_INDIR_PARAM (name[1]))))
Definition at line 125 of file subst.c.
ST_BACKSL
#define ST_BACKSL 0x01
Definition at line 89 of file subst.c.
ST_CTLESC
#define ST_CTLESC 0x02
Definition at line 90 of file subst.c.
ST_DQUOTE
#define ST_DQUOTE 0x08 /* unused yet */
Definition at line 92 of file subst.c.
ST_SQUOTE
#define ST_SQUOTE 0x04 /* unused yet */
Definition at line 91 of file subst.c.
STR_DOLLAR_AT_STAR
#define STR_DOLLAR_AT_STAR (s) (DOLLAR_AT_STAR ((s)[0]) && (s)[1] == '\0')
Definition at line 108 of file subst.c.
UNQUOTED
#define UNQUOTED 0
Definition at line 10923 of file subst.c.
VALID_INDIR_PARAM
#define VALID_INDIR_PARAM (c) ((posixly_correct == 0 && (c) == '#') || (posixly_correct == 0 && (c) == '?') || (c) == '@' || (c) == '*')
Definition at line 117 of file subst.c.
VALID_PARAM_EXPAND_CHAR
#define VALID_PARAM_EXPAND_CHAR (c) (sh_syntaxtab[(unsigned char)c] & CSUBSTOP)
Definition at line 122 of file subst.c.
VALID_SPECIAL_LENGTH_PARAM
#define VALID_SPECIAL_LENGTH_PARAM (c) ((c) == '-' || (c) == '?' || (c) == '#' || (c) == '@')
Definition at line 112 of file subst.c.
VT_ARRAYMEMBER
#define VT_ARRAYMEMBER 3
Definition at line 83 of file subst.c.
VT_ARRAYVAR
#define VT_ARRAYVAR 2
Definition at line 82 of file subst.c.
VT_ASSOCVAR
#define VT_ASSOCVAR 4
Definition at line 84 of file subst.c.
VT_POSPARMS
#define VT_POSPARMS 1
Definition at line 81 of file subst.c.
VT_STARSUB
#define VT_STARSUB 128 /* $* or ${array[*]} -- used to split */
Definition at line 86 of file subst.c.
VT_VARIABLE
#define VT_VARIABLE 0
Definition at line 80 of file subst.c.
WEXP_ALL
#define WEXP_ALL (WEXP_VARASSIGN|WEXP_BRACEEXP|WEXP_TILDEEXP|WEXP_PARAMEXP|WEXP_PATHEXP)
Definition at line 12261 of file subst.c.
WEXP_BRACEEXP
#define WEXP_BRACEEXP 0x002
Definition at line 12254 of file subst.c.
WEXP_NOVARS
#define WEXP_NOVARS (WEXP_BRACEEXP|WEXP_TILDEEXP|WEXP_PARAMEXP|WEXP_PATHEXP)
Definition at line 12265 of file subst.c.
WEXP_PARAMEXP
#define WEXP_PARAMEXP 0x008
Definition at line 12256 of file subst.c.
WEXP_PATHEXP
#define WEXP_PATHEXP 0x010
Definition at line 12257 of file subst.c.
WEXP_SHELLEXP
#define WEXP_SHELLEXP (WEXP_BRACEEXP|WEXP_TILDEEXP|WEXP_PARAMEXP)
Definition at line 12270 of file subst.c.
WEXP_TILDEEXP
#define WEXP_TILDEEXP 0x004
Definition at line 12255 of file subst.c.
WEXP_VARASSIGN
#define WEXP_VARASSIGN 0x001
Definition at line 12253 of file subst.c.
WHOLLY_QUOTED
#define WHOLLY_QUOTED 2
Definition at line 10925 of file subst.c.
Typedef Documentation
PARAMS
typedef WORD_LIST* EXPFUNC PARAMS((char *, int))
Definition at line 147 of file subst.c.
Function Documentation
call_expand_word_internal()
static WORD_LIST* call_expand_word_internal (WORD_DESC * w, int q, int i, int * c, int * e) static
Definition at line 4319 of file subst.c.
 {
   WORD_LIST *result;
   result = expand_word_internal (w, q, i, c, e);
   if (result == &expand_word_error || result == &expand_word_fatal)
     {
       /* By convention, each time this error is returned, w->word has
      already been freed (it sometimes may not be in the fatal case,
      but that doesn't result in a memory leak because we're going
      to exit in most cases). */
       w->word = (char *)NULL;
       last_command_exit_value = EXECUTION_FAILURE;
       exp_jump_to_top_level ((result == &expand_word_error) ? DISCARD : FORCE_EOF);
       /* NOTREACHED */
       return (NULL);
     }
   else
     return (result);
 }
References c, DISCARD, EXECUTION_FAILURE, exp_jump_to_top_level(), expand_word_error, expand_word_fatal, expand_word_internal(), FORCE_EOF, i, last_command_exit_value, NULL, and w.
Referenced by expand_arith_string(), expand_string_assignment(), expand_string_for_pat(), expand_string_for_rhs(), expand_string_internal(), expand_word(), and expand_word_leave_quoted().
chk_arithsub()
static int chk_arithsub (char * s, int len) const static
Definition at line 9487 of file subst.c.
 {
   int i, count;
   DECLARE_MBSTATE;
   i = count = 0;
   while (i < len)
     {
       if (s[i] == LPAREN)
     count++;
       else if (s[i] == RPAREN)
     {
       count--;
       if (count < 0)
         return 0;
     }
       switch (s[i])
     {
     default:
       ADVANCE_CHAR (s, len, i);
       break;
     case '\\':
       i++;
       if (s[i])
         ADVANCE_CHAR (s, len, i);
       break;
     case '\'':
       i = skip_single_quoted (s, len, ++i, 0);
       break;
     case '"':
       i = skip_double_quoted ((char *)s, len, ++i, 0);
       break;
     }
     }
   return (count == 0);
 }
References ADVANCE_CHAR, count, DECLARE_MBSTATE, i, len, LPAREN, RPAREN, s, skip_double_quoted(), and skip_single_quoted().
Referenced by param_expand().
chk_atstar()
static int chk_atstar (char * name, int quoted, int pflags, int * quoted_dollar_atp, int * contains_dollar_at) static
Definition at line 7330 of file subst.c.
 {
   char *temp1;
   if (name == 0)
     {
       if (quoted_dollar_atp)
     *quoted_dollar_atp = 0;
       if (contains_dollar_at)
     *contains_dollar_at = 0;
       return 0;
     }
   /* check for $@ and $* */
   if (name[0] == '@' && name[1] == 0)
     {
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
     *quoted_dollar_atp = 1;
       if (contains_dollar_at)
     *contains_dollar_at = 1;
       return 1;
     }
   else if (name[0] == '*' && name[1] == '\0' && quoted == 0)
     {
       /* Need more checks here that parallel what string_list_pos_params and
      param_expand do. Check expand_no_split_dollar_star and ??? */
       if (contains_dollar_at && expand_no_split_dollar_star == 0)
     *contains_dollar_at = 1;
       return 1;
     }
   /* Now check for ${array[@]} and ${array[*]} */
 #if defined (ARRAY_VARS)
   else if (valid_array_reference (name, 0))
     {
       temp1 = mbschr (name, LBRACK);
       if (temp1 && temp1[1] == '@' && temp1[2] == RBRACK)
     {
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
         *quoted_dollar_atp = 1;
       if (contains_dollar_at)
         *contains_dollar_at = 1;
       return 1;
     }
       /* ${array[*]}, when unquoted, should be treated like ${array[@]},
      which should result in separate words even when IFS is unset. */
       if (temp1 && temp1[1] == '*' && temp1[2] == RBRACK && quoted == 0)
     {
       if (contains_dollar_at)
         *contains_dollar_at = 1;
       return 1;
     }
     }
 #endif
   return 0;
 }
References expand_no_split_dollar_star, LBRACK, mbschr(), Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, and RBRACK.
Referenced by param_expand(), parameter_brace_expand(), and parameter_brace_expand_indir().
command_substitute()
WORD_DESC* command_substitute (char * string, int quoted, int flags)
Definition at line 6919 of file subst.c.
 {
   pid_t pid, old_pid, old_pipeline_pgrp, old_async_pid;
   char *istring, *s;
   int result, fildes[2], function_value, pflags, rc, tflag, fork_flags;
   WORD_DESC *ret;
   sigset_t set, oset;
   istring = (char *)NULL;
   /* Don't fork () if there is no need to.  In the case of no command to
      run, just return NULL. */
   for (s = string; s && *s && (shellblank (*s) || *s == '\n'); s++)
     ;
   if (s == 0 || *s == 0)
     return ((WORD_DESC *)NULL);
   if (*s == '<' && (s[1] != '<' && s[1] != '>' && s[1] != '&'))
     {
       COMMAND *cmd;
       cmd = parse_string_to_command (string, 0);    /* XXX - flags */
       if (cmd && can_optimize_cat_file (cmd))
     {
       tflag = 0;
       istring = optimize_cat_file (cmd->value.Simple->redirects, quoted, flags, &tflag);
       if (istring == &expand_param_error)
         {
           last_command_exit_value = EXECUTION_FAILURE;
           istring = 0;
         }
       else
         last_command_exit_value = EXECUTION_SUCCESS;    /* compat */
       last_command_subst_pid = dollar_dollar_pid;
       dispose_command (cmd);
       ret = alloc_word_desc ();
       ret->word = istring;
       ret->flags = tflag;
       return ret;
     }
       dispose_command (cmd);
     }
   if (wordexp_only && read_but_dont_execute)
     {
       last_command_exit_value = EX_WEXPCOMSUB;
       jump_to_top_level (EXITPROG);
     }
   /* We're making the assumption here that the command substitution will
      eventually run a command from the file system.  Since we'll run
      maybe_make_export_env in this subshell before executing that command,
      the parent shell and any other shells it starts will have to remake
      the environment.  If we make it before we fork, other shells won't
      have to.  Don't bother if we have any temporary variable assignments,
      though, because the export environment will be remade after this
      command completes anyway, but do it if all the words to be expanded
      are variable assignments. */
   if (subst_assign_varlist == 0 || garglist == 0)
     maybe_make_export_env ();   /* XXX */
   /* Flags to pass to parse_and_execute() */
   pflags = (interactive && sourcelevel == 0) ? SEVAL_RESETLINE : 0;
   old_pid = last_made_pid;
   /* Pipe the output of executing STRING into the current shell. */
   if (pipe (fildes) < 0)
     {
       sys_error ("%s", _("cannot make pipe for command substitution"));
       goto error_exit;
     }
 #if defined (JOB_CONTROL)
   old_pipeline_pgrp = pipeline_pgrp;
   /* Don't reset the pipeline pgrp if we're already a subshell in a pipeline or
      we've already forked to run a disk command (and are expanding redirections,
      for example). */
   if ((subshell_environment & (SUBSHELL_FORK|SUBSHELL_PIPE)) == 0)
     pipeline_pgrp = shell_pgrp;
   cleanup_the_pipeline ();
 #endif /* JOB_CONTROL */
   old_async_pid = last_asynchronous_pid;
   fork_flags = (subshell_environment&SUBSHELL_ASYNC) ? FORK_ASYNC : 0;
   pid = make_child ((char *)NULL, fork_flags|FORK_NOTERM);
   last_asynchronous_pid = old_async_pid;
   if (pid == 0)
     {
       /* Reset the signal handlers in the child, but don't free the
      trap strings.  Set a flag noting that we have to free the
      trap strings if we run trap to change a signal disposition. */
       reset_signal_handlers ();
       if (ISINTERRUPT)
     {
       kill (getpid (), SIGINT);
       CLRINTERRUPT;     /* if we're ignoring SIGINT somehow */
     }
       QUIT; /* catch any interrupts we got post-fork */
       subshell_environment |= SUBSHELL_RESETTRAP;
       subshell_environment &= ~SUBSHELL_IGNTRAP;
     }
 #if defined (JOB_CONTROL)
   /* XXX DO THIS ONLY IN PARENT ? XXX */
   set_sigchld_handler ();
   stop_making_children ();
   if (pid != 0)
     pipeline_pgrp = old_pipeline_pgrp;
 #else
   stop_making_children ();
 #endif /* JOB_CONTROL */
   if (pid < 0)
     {
       sys_error (_("cannot make child for command substitution"));
     error_exit:
       last_made_pid = old_pid;
       FREE (istring);
       close (fildes[0]);
       close (fildes[1]);
       return ((WORD_DESC *)NULL);
     }
   if (pid == 0)
     {
       /* The currently executing shell is not interactive. */
       interactive = 0;
 #if defined (JOB_CONTROL)
       /* Invariant: in child processes started to run command substitutions,
      pipeline_pgrp == shell_pgrp. Other parts of the shell assume this. */
       if (pipeline_pgrp > 0 && pipeline_pgrp != shell_pgrp)
     shell_pgrp = pipeline_pgrp;
 #endif
       set_sigint_handler ();    /* XXX */
       free_pushed_string_input ();
       /* Discard  buffered stdio output before replacing the underlying file
      descriptor. */
       fpurge (stdout);
       if (dup2 (fildes[1], 1) < 0)
     {
       sys_error ("%s", _("command_substitute: cannot duplicate pipe as fd 1"));
       exit (EXECUTION_FAILURE);
     }
       /* If standard output is closed in the parent shell
      (such as after `exec >&-'), file descriptor 1 will be
      the lowest available file descriptor, and end up in
      fildes[0].  This can happen for stdin and stderr as well,
      but stdout is more important -- it will cause no output
      to be generated from this command. */
       if ((fildes[1] != fileno (stdin)) &&
       (fildes[1] != fileno (stdout)) &&
       (fildes[1] != fileno (stderr)))
     close (fildes[1]);
       if ((fildes[0] != fileno (stdin)) &&
       (fildes[0] != fileno (stdout)) &&
       (fildes[0] != fileno (stderr)))
     close (fildes[0]);
 #ifdef __CYGWIN__
       /* Let stdio know the fd may have changed from text to binary mode, and
      make sure to preserve stdout line buffering. */
       freopen (NULL, "w", stdout);
       sh_setlinebuf (stdout);
 #endif /* __CYGWIN__ */
       /* This is a subshell environment. */
       subshell_environment |= SUBSHELL_COMSUB;
       /* Many shells do not appear to inherit the -v option for command
      substitutions. */
       change_flag ('v', FLAG_OFF);
       /* When inherit_errexit option is not enabled, command substitution does
      not inherit the -e flag.  It is enabled when Posix mode is enabled */
       if (inherit_errexit == 0)
         {
           builtin_ignoring_errexit = 0;
       change_flag ('e', FLAG_OFF);
         }
       set_shellopts ();
       /* If we are expanding a redirection, we can dispose of any temporary
      environment we received, since redirections are not supposed to have
      access to the temporary environment.  We will have to see whether this
      affects temporary environments supplied to `eval', but the temporary
      environment gets copied to builtin_env at some point. */
       if (expanding_redir)
     {
       flush_temporary_env ();
       expanding_redir = 0;
     }
       remove_quoted_escapes (string);
       /* We want to expand aliases on this pass if we are not in posix mode
      for backwards compatibility. parse_and_execute() takes care of
      setting expand_aliases back to the global value when executing the
      parsed string. We only do this for $(...) command substitution,
      since that is what parse_comsub handles; `` comsubs are processed
      using parse.y:parse_matched_pair(). */
       if (expand_aliases && (flags & PF_BACKQUOTE) == 0)
         expand_aliases = posixly_correct == 0;
       startup_state = 2;    /* see if we can avoid a fork */
       parse_and_execute_level = 0;
       /* Give command substitution a place to jump back to on failure,
      so we don't go back up to main (). */
       result = setjmp_nosigs (top_level);
       /* If we're running a command substitution inside a shell function,
      trap `return' so we don't return from the function in the subshell
      and go off to never-never land. */
       if (result == 0 && return_catch_flag)
     function_value = setjmp_nosigs (return_catch);
       else
     function_value = 0;
       if (result == ERREXIT)
     rc = last_command_exit_value;
       else if (result == EXITPROG || result == EXITBLTIN)
     rc = last_command_exit_value;
       else if (result)
     rc = EXECUTION_FAILURE;
       else if (function_value)
     rc = return_catch_value;
       else
     {
       subshell_level++;
       rc = parse_and_execute (string, "command substitution", pflags|SEVAL_NOHIST);
       /* leave subshell level intact for any exit trap */
     }
       last_command_exit_value = rc;
       rc = run_exit_trap ();
 #if defined (PROCESS_SUBSTITUTION)
       unlink_fifo_list ();
 #endif
       exit (rc);
     }
   else
     {
       int dummyfd;
 #if defined (JOB_CONTROL) && defined (PGRP_PIPE)
       close_pgrp_pipe ();
 #endif /* JOB_CONTROL && PGRP_PIPE */
       close (fildes[1]);
       begin_unwind_frame ("read-comsub");
       dummyfd = fildes[0];
       add_unwind_protect (close, dummyfd);
       /* Block SIGINT while we're reading from the pipe. If the child
      process gets a SIGINT, it will either handle it or die, and the
      read will return. */
       BLOCK_SIGNAL (SIGINT, set, oset);
       tflag = 0;
       istring = read_comsub (fildes[0], quoted, flags, &tflag);
       close (fildes[0]);
       discard_unwind_frame ("read-comsub");
       UNBLOCK_SIGNAL (oset);
       current_command_subst_pid = pid;
       last_command_exit_value = wait_for (pid, JWAIT_NOTERM);
       last_command_subst_pid = pid;
       last_made_pid = old_pid;
 #if defined (JOB_CONTROL)
       /* If last_command_exit_value > 128, then the substituted command
      was terminated by a signal.  If that signal was SIGINT, then send
      SIGINT to ourselves.  This will break out of loops, for instance. */
       if (last_command_exit_value == (128 + SIGINT) && last_command_exit_signal == SIGINT)
     kill (getpid (), SIGINT);
 #endif /* JOB_CONTROL */
       ret = alloc_word_desc ();
       ret->word = istring;
       ret->flags = tflag;
       return ret;
     }
 }
References _, add_unwind_protect(), alloc_word_desc(), begin_unwind_frame(), BLOCK_SIGNAL, builtin_ignoring_errexit, can_optimize_cat_file(), change_flag(), cleanup_the_pipeline(), close(), CLRINTERRUPT, cmd, current_command_subst_pid, discard_unwind_frame(), dispose_command(), dollar_dollar_pid, dup2(), ERREXIT, error_exit, EX_WEXPCOMSUB, EXECUTION_FAILURE, EXECUTION_SUCCESS, exit(), EXITBLTIN, EXITPROG, expand_aliases, expand_param_error, expanding_redir, fileno(), FLAG_OFF, word_desc::flags, flags, flush_temporary_env(), FORK_ASYNC, FORK_NOTERM, fpurge(), FREE, free_pushed_string_input(), freopen(), garglist, getpid(), inherit_errexit, interactive, ISINTERRUPT, jump_to_top_level(), JWAIT_NOTERM, kill(), last_asynchronous_pid, last_command_exit_signal, last_command_exit_value, last_command_subst_pid, last_made_pid, make_child(), maybe_make_export_env(), NULL, optimize_cat_file(), parse_and_execute(), parse_and_execute_level, parse_string_to_command(), PF_BACKQUOTE, pid, pipeline_pgrp, posixly_correct, QUIT, rc, read_but_dont_execute, read_comsub(), remove_quoted_escapes(), reset_signal_handlers(), return_catch, return_catch_flag, return_catch_value, run_exit_trap(), s, set_sigchld_handler(), set_sigint_handler(), setjmp_nosigs, SEVAL_NOHIST, SEVAL_RESETLINE, sh_setlinebuf(), shell_pgrp, shellblank, SIGINT, sourcelevel, startup_state, stderr, stdin, stdout, stop_making_children(), SUBSHELL_ASYNC, SUBSHELL_COMSUB, subshell_environment, SUBSHELL_FORK, SUBSHELL_IGNTRAP, subshell_level, SUBSHELL_PIPE, SUBSHELL_RESETTRAP, subst_assign_varlist, sys_error(), top_level, UNBLOCK_SIGNAL, wait_for(), word_desc::word, and wordexp_only.
Referenced by expand_word_internal(), and param_expand().
de_backslash()
char* de_backslash (char * string)
Definition at line 1999 of file subst.c.
 {
   register size_t slen;
   register int i, j, prev_i;
   DECLARE_MBSTATE;
   slen = strlen (string);
   i = j = 0;
   /* Loop copying string[i] to string[j], i >= j. */
   while (i < slen)
     {
       if (string[i] == '\\' && (string[i + 1] == '`' || string[i + 1] == '\\' ||
                   string[i + 1] == '$'))
     i++;
       prev_i = i;
       ADVANCE_CHAR (string, slen, i);
       if (j < prev_i)
     do string[j++] = string[prev_i++]; while (prev_i < i);
       else
     j = i;
     }
   string[j] = '\0';
   return (string);
 }
References ADVANCE_CHAR, DECLARE_MBSTATE, i, j, and strlen().
Referenced by expand_word_internal().
dequote_escapes()
char* dequote_escapes (char * string) const
Definition at line 4760 of file subst.c.
 {
   const char *s, *send;
   char *t, *result;
   size_t slen;
   int quote_spaces;
   DECLARE_MBSTATE;
   if (string == 0)
     return (char *)0;
   slen = strlen (string);
   send = string + slen;
   t = result = (char *)xmalloc (slen + 1);
   if (strchr (string, CTLESC) == 0)
     return (strcpy (result, string));
   quote_spaces = (ifs_value && *ifs_value == 0);
   s = string;
   while (*s)
     {
       if (*s == CTLESC && (s[1] == CTLESC || s[1] == CTLNUL || (quote_spaces && s[1] == ' ')))
     {
       s++;
       if (*s == '\0')
         break;
     }
       COPY_CHAR_P (t, s, send);
     }
   *t = '\0';
   return result;
 }
References COPY_CHAR_P, CTLESC, CTLNUL, DECLARE_MBSTATE, ifs_value, s, send(), strchr(), strcpy, string, strlen(), t, and xmalloc.
Referenced by execute_intern_function(), get_var_and_type(), mk_env_string(), parameter_brace_find_indir(), remove_quoted_escapes(), and string_transform().
dequote_list()
WORD_LIST* dequote_list (WORD_LIST * list)
Definition at line 4966 of file subst.c.
 {
   register char *s;
   register WORD_LIST *tlist;
   for (tlist = list; tlist; tlist = tlist->next)
     {
       s = dequote_string (tlist->word->word);
       if (QUOTED_NULL (tlist->word->word))
     tlist->word->flags &= ~W_HASQUOTEDNULL;
       free (tlist->word->word);
       tlist->word->word = s;
     }
   return list;
 }
References dequote_string(), word_desc::flags, free, list(), word_list::next, QUOTED_NULL, s, W_HASQUOTEDNULL, word_desc::word, and word_list::word.
Referenced by expand_arith_string(), expand_prompt_string(), expand_string(), expand_string_assignment(), expand_string_unsplit(), expand_word(), expand_word_internal(), expand_word_list_internal(), and expand_word_unsplit().
dequote_string()
char* dequote_string (char * string)
Definition at line 4878 of file subst.c.
 {
   register char *s, *t;
   size_t slen;
   char *result, *send;
   DECLARE_MBSTATE;
   if (string[0] == CTLESC && string[1] == 0)
     internal_debug ("dequote_string: string with bare CTLESC");
   slen = STRLEN (string);
   t = result = (char *)xmalloc (slen + 1);
   if (QUOTED_NULL (string))
     {
       result[0] = '\0';
       return (result);
     }
   /* A string consisting of only a single CTLESC should pass through unchanged */
   if (string[0] == CTLESC && string[1] == 0)
     {
       result[0] = CTLESC;
       result[1] = '\0';
       return (result);
     }
   /* If no character in the string can be quoted, don't bother examining
      each character.  Just return a copy of the string passed to us. */
   if (strchr (string, CTLESC) == NULL)
     return (strcpy (result, string));
   send = string + slen;
   s = string;
   while (*s)
     {
       if (*s == CTLESC)
     {
       s++;
       if (*s == '\0')
         break;
     }
       COPY_CHAR_P (t, s, send);
     }
   *t = '\0';
   return (result);
 }
References COPY_CHAR_P, CTLESC, DECLARE_MBSTATE, internal_debug(), NULL, QUOTED_NULL, s, send(), strchr(), strcpy, string, STRLEN, t, and xmalloc.
Referenced by decode_prompt_string(), dequote_list(), dequote_word(), execute_case_command(), get_var_and_type(), glob_expand_word_list(), parameter_brace_expand_rhs(), and parameter_brace_find_indir().
dequote_word()
WORD_DESC* dequote_word (WORD_DESC * word)
Definition at line 4950 of file subst.c.
 {
   register char *s;
   s = dequote_string (word->word);
   if (QUOTED_NULL (word->word))
     word->flags &= ~W_HASQUOTEDNULL;
   free (word->word);
   word->word = s;
   return word;
 }
References dequote_string(), word_desc::flags, free, QUOTED_NULL, s, W_HASQUOTEDNULL, and word_desc::word.
do_assignment()
int do_assignment (char * string)
Definition at line 3666 of file subst.c.
 {
   WORD_DESC td;
   td.flags = W_ASSIGNMENT;
   td.word = string;
   return do_assignment_internal (&td, 1);
 }
References do_assignment_internal(), string, td, and W_ASSIGNMENT.
do_assignment_internal()
static int do_assignment_internal (WORD_DESC * word, int expand) const static
Definition at line 3545 of file subst.c.
 {
   int offset, appendop, assign_list, aflags, retval;
   char *name, *value, *temp;
   SHELL_VAR *entry;
 #if defined (ARRAY_VARS)
   char *t;
   int ni;
 #endif
   const char *string;
   if (word == 0 || word->word == 0)
     return 0;
   appendop = assign_list = aflags = 0;
   string = word->word;
   offset = assignment (string, 0);
   name = savestring (string);
   value = (char *)NULL;
   if (name[offset] == '=')
     {
       if (name[offset - 1] == '+')
     {
       appendop = 1;
       name[offset - 1] = '\0';
     }
       name[offset] = 0;     /* might need this set later */
       temp = name + offset + 1;
 #if defined (ARRAY_VARS)
       if (expand && (word->flags & W_COMPASSIGN))
     {
       assign_list = ni = 1;
       value = extract_array_assignment_list (temp, &ni);
     }
       else
 #endif
       if (expand && temp[0])
     value = expand_string_if_necessary (temp, 0, expand_string_assignment);
       else
     value = savestring (temp);
     }
   if (value == 0)
     {
       value = (char *)xmalloc (1);
       value[0] = '\0';
     }
   if (echo_command_at_execute)
     {
       if (appendop)
     name[offset - 1] = '+';
       xtrace_print_assignment (name, value, assign_list, 1);
       if (appendop)
     name[offset - 1] = '\0';
     }
 #define ASSIGN_RETURN(r)    do { FREE (value); free (name); return (r); } while (0)
   if (appendop)
     aflags |= ASS_APPEND;
 #if defined (ARRAY_VARS)
   if (t = mbschr (name, LBRACK))
     {
       if (assign_list)
     {
       report_error (_("%s: cannot assign list to array member"), name);
       ASSIGN_RETURN (0);
     }
       aflags |= ASS_ALLOWALLSUB;    /* allow a[@]=value for existing associative arrays */
       entry = assign_array_element (name, value, aflags, (array_eltstate_t *)0);
       if (entry == 0)
     ASSIGN_RETURN (0);
     }
   else if (assign_list)
     {
       if ((word->flags & W_ASSIGNARG) && (word->flags & W_CHKLOCAL))
     aflags |= ASS_CHKLOCAL;
       if ((word->flags & W_ASSIGNARG) && (word->flags & W_ASSNGLOBAL) == 0)
     aflags |= ASS_MKLOCAL;
       if ((word->flags & W_ASSIGNARG) && (word->flags & W_ASSNGLOBAL))
     aflags |= ASS_MKGLOBAL;
       if (word->flags & W_ASSIGNASSOC)
     aflags |= ASS_MKASSOC;
       entry = do_compound_assignment (name, value, aflags);
     }
   else
 #endif /* ARRAY_VARS */
   entry = bind_variable (name, value, aflags);
   if (entry)
     stupidly_hack_special_variables (entry->name);  /* might be a nameref */
   else
     stupidly_hack_special_variables (name);
   /* Return 1 if the assignment seems to have been performed correctly. */
   if (entry == 0 || readonly_p (entry))
     retval = 0;     /* assignment failure */
   else if (noassign_p (entry))
     {
       set_exit_status (EXECUTION_FAILURE);
       retval = 1;   /* error status, but not assignment failure */
     }
   else
     retval = 1;
   if (entry && retval != 0 && noassign_p (entry) == 0)
     VUNSETATTR (entry, att_invisible);
   ASSIGN_RETURN (retval);
 }
References _, ASS_ALLOWALLSUB, ASS_APPEND, ASS_CHKLOCAL, ASS_MKASSOC, ASS_MKGLOBAL, ASS_MKLOCAL, ASSIGN_RETURN, assignment(), att_invisible, bind_variable(), echo_command_at_execute, EXECUTION_FAILURE, expand(), expand_string_assignment(), expand_string_if_necessary(), word_desc::flags, LBRACK, mbschr(), noassign_p, NULL, offset, readonly_p, report_error(), retval, savestring(), set_exit_status(), string, stupidly_hack_special_variables(), t, value, VUNSETATTR, W_ASSIGNARG, W_ASSIGNASSOC, W_ASSNGLOBAL, W_CHKLOCAL, W_COMPASSIGN, word_desc::word, xmalloc, and xtrace_print_assignment().
Referenced by do_assignment(), do_assignment_no_expand(), and do_word_assignment().
do_assignment_no_expand()
int do_assignment_no_expand (char * string)
Definition at line 3689 of file subst.c.
 {
   WORD_DESC td;
   td.flags = W_ASSIGNMENT;
   td.word = string;
   return (do_assignment_internal (&td, 0));
 }
References do_assignment_internal(), string, td, and W_ASSIGNMENT.
do_assignment_statements()
static int do_assignment_statements (WORD_LIST * varlist, char * command, int is_nullcmd) static
Definition at line 12870 of file subst.c.
 {
   WORD_LIST *temp_list;
   char *savecmd;
   sh_wassign_func_t *assign_func;
   int is_special_builtin, is_builtin_or_func, tint;
   /* If the remainder of the words expand to nothing, Posix.2 requires
      that the variable and environment assignments affect the shell's
      environment (do_word_assignment). */
   assign_func = is_nullcmd ? do_word_assignment : assign_in_env;
   tempenv_assign_error = 0;
   is_builtin_or_func = command && (find_shell_builtin (command) || find_function (command));
   /* Posix says that special builtins exit if a variable assignment error
      occurs in an assignment preceding it. (XXX - this is old -- current Posix
      says that any variable assignment error causes a non-interactive shell
      to exit. See the STRICT_POSIX checks below. */
   is_special_builtin = posixly_correct && command && find_special_builtin (command);
   savecmd = this_command_name;
   for (temp_list = varlist; temp_list; temp_list = temp_list->next)
     {
       this_command_name = (char *)NULL;
       assigning_in_environment = is_nullcmd == 0;
       tint = (*assign_func) (temp_list->word, is_builtin_or_func);
       assigning_in_environment = 0;
       this_command_name = savecmd;
       /* Variable assignment errors in non-interactive shells running
      in posix mode cause the shell to exit. */
       if (tint == 0)
     {
       if (is_nullcmd)   /* assignment statement */
         {
           last_command_exit_value = EXECUTION_FAILURE;
 #if defined (STRICT_POSIX)
           if (posixly_correct && interactive_shell == 0)
 #else
           if (posixly_correct && interactive_shell == 0 && executing_command_builtin == 0)
 #endif
             exp_jump_to_top_level (FORCE_EOF);
           else
         exp_jump_to_top_level (DISCARD);
         }
       /* In posix mode, assignment errors in the temporary environment
          cause a non-interactive shell executing a special builtin to
          exit and a non-interactive shell to otherwise jump back to the
          top level. This is what POSIX says to do for variable assignment
          errors, and POSIX says errors in assigning to the temporary
          environment are treated as variable assignment errors.
          (XXX - this is not what current POSIX says - look at the
          STRICT_POSIX defines. */
       else if (posixly_correct)
         {
           last_command_exit_value = EXECUTION_FAILURE;
 #if defined (STRICT_POSIX)
           exp_jump_to_top_level ((interactive_shell == 0) ? FORCE_EOF : DISCARD);
 #else
           if (interactive_shell == 0 && is_special_builtin)
         exp_jump_to_top_level (FORCE_EOF);
           else if (interactive_shell == 0)
         exp_jump_to_top_level (DISCARD);    /* XXX - maybe change later */
           else
         exp_jump_to_top_level (DISCARD);
 #endif
         }
       else
         tempenv_assign_error++;
     }
     }
   return (tempenv_assign_error);
 }
References assign_in_env(), assigning_in_environment, DISCARD, do_word_assignment(), executing_command_builtin, EXECUTION_FAILURE, exp_jump_to_top_level(), find_function(), find_shell_builtin(), find_special_builtin(), FORCE_EOF, interactive_shell, is_special_builtin(), last_command_exit_value, word_list::next, NULL, posixly_correct, tempenv_assign_error, this_command_name, and word_list::word.
Referenced by expand_word_list_internal().
do_word_assignment()
int do_word_assignment (WORD_DESC * word, int flags)
Definition at line 3678 of file subst.c.
 {
   return do_assignment_internal (word, 1);
 }
References do_assignment_internal().
Referenced by do_assignment_statements().
exp_jump_to_top_level()
static void exp_jump_to_top_level (int v) static
Definition at line 12137 of file subst.c.
 {
   set_pipestatus_from_exit (last_command_exit_value);
   /* Cleanup code goes here. */
   expand_no_split_dollar_star = 0;  /* XXX */
   if (expanding_redir)
     undo_partial_redirects ();
   expanding_redir = 0;
   assigning_in_environment = 0;
   if (parse_and_execute_level == 0)
     top_level_cleanup ();           /* from sig.c */
   jump_to_top_level (v);
 }
References assigning_in_environment, expand_no_split_dollar_star, expanding_redir, jump_to_top_level(), last_command_exit_value, parse_and_execute_level, set_pipestatus_from_exit(), top_level_cleanup(), and undo_partial_redirects().
Referenced by call_expand_word_internal(), do_assignment_statements(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), glob_expand_word_list(), parameter_brace_expand_rhs(), and shell_expand_word_list().
expand_arith_string()
char* expand_arith_string (char * string, int quoted)
Definition at line 4019 of file subst.c.
 {
   WORD_DESC td;
   WORD_LIST *list, *tlist;
   size_t slen;
   int i, saw_quote;
   char *ret;
   DECLARE_MBSTATE;
   /* Don't need string length for ADVANCE_CHAR unless multibyte chars possible. */
   slen = (MB_CUR_MAX > 1) ? strlen (string) : 0;
   i = saw_quote = 0;
   while (string[i])
     {
       if (ARITH_EXP_CHAR (string[i]))
     break;
       else if (string[i] == '\'' || string[i] == '\\' || string[i] == '"')
     saw_quote = string[i];
       ADVANCE_CHAR (string, slen, i);
     }
   if (string[i])
     {
       /* This is expanded version of expand_string_internal as it's called by
      expand_string_leave_quoted  */
       td.flags = W_NOPROCSUB|W_NOTILDE; /* don't want process substitution or tilde expansion */
 #if 0   /* TAG: bash-5.2 */
       if (quoted & Q_ARRAYSUB)
     td.flags |= W_NOCOMSUB;
 #endif
       td.word = savestring (string);
       list = call_expand_word_internal (&td, quoted, 0, (int *)NULL, (int *)NULL);
       /* This takes care of the calls from expand_string_leave_quoted and
      expand_string */
       if (list)
     {
       tlist = word_list_split (list);
       dispose_words (list);
       list = tlist;
       if (list)
         dequote_list (list);
     }
       /* This comes from expand_string_if_necessary */
       if (list)
     {
       ret = string_list (list);
       dispose_words (list);
     }
       else
     ret = (char *)NULL;
       FREE (td.word);
     }
   else if (saw_quote && (quoted & Q_ARITH))
     ret = string_quote_removal (string, quoted);
   else if (saw_quote && ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0))
     ret = string_quote_removal (string, quoted);
   else
     ret = savestring (string);
   return ret;
 }
References ADVANCE_CHAR, ARITH_EXP_CHAR, call_expand_word_internal(), DECLARE_MBSTATE, dequote_list(), dispose_words(), FREE, i, list(), MB_CUR_MAX, NULL, Q_ARITH, Q_ARRAYSUB, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, savestring(), string_list(), string_quote_removal(), strlen(), td, W_NOCOMSUB, W_NOPROCSUB, W_NOTILDE, and word_list_split().
Referenced by param_expand(), and verify_substring_values().
expand_assignment_string_to_string()
char* expand_assignment_string_to_string (char * string, int quoted)
Definition at line 3913 of file subst.c.
 {
   return (expand_string_to_string_internal (string, quoted, expand_string_assignment));
 }
References expand_string_assignment(), and expand_string_to_string_internal().
Referenced by assign_in_env(), and heredoc_expand().
expand_prompt_string()
WORD_LIST* expand_prompt_string (char * string, int quoted, int wflags)
Definition at line 4445 of file subst.c.
 {
   WORD_LIST *value;
   WORD_DESC td;
   if (string == 0 || *string == 0)
     return ((WORD_LIST *)NULL);
   td.flags = wflags;
   td.word = savestring (string);
   no_longjmp_on_fatal_error = 1;
   value = expand_word_internal (&td, quoted, 0, (int *)NULL, (int *)NULL);
   no_longjmp_on_fatal_error = 0;
   if (value == &expand_word_error || value == &expand_word_fatal)
     {
       value = make_word_list (make_bare_word (string), (WORD_LIST *)NULL);
       return value;
     }
   FREE (td.word);
   if (value)
     {
       if (value->word)
     {
       remove_quoted_nulls (value->word->word);  /* XXX */
       value->word->flags &= ~W_HASQUOTEDNULL;
     }
       dequote_list (value);
     }
   return (value);
 }
References dequote_list(), expand_word_error, expand_word_fatal, expand_word_internal(), FREE, make_bare_word(), make_word_list(), no_longjmp_on_fatal_error, NULL, remove_quoted_nulls(), savestring(), td, value, and W_HASQUOTEDNULL.
Referenced by decode_prompt_string().
expand_string()
WORD_LIST* expand_string (char * string, int quoted)
Definition at line 4587 of file subst.c.
 {
   WORD_LIST *result;
   if (string == 0 || *string == '\0')
     return ((WORD_LIST *)NULL);
   result = expand_string_leave_quoted (string, quoted);
   return (result ? dequote_list (result) : result);
 }
References dequote_list(), expand_string_leave_quoted(), and NULL.
Referenced by expand_string_to_string(), parameter_brace_expand_error(), and parameter_brace_expand_length().
expand_string_assignment()
WORD_LIST* expand_string_assignment (char * string, int quoted)
Definition at line 4399 of file subst.c.
 {
   WORD_DESC td;
   WORD_LIST *value;
   if (string == 0 || *string == '\0')
     return ((WORD_LIST *)NULL);
   expand_no_split_dollar_star = 1;
 #if 0
   /* Other shells (ksh93) do it this way, which affects how $@ is expanded
      in constructs like bar=${@#0} (preserves the spaces resulting from the
      expansion of $@ in a context where you don't do word splitting); Posix
      interp 888 makes the expansion of $@ in contexts where word splitting
      is not performed unspecified. */
   td.flags = W_ASSIGNRHS|W_NOSPLIT2;        /* Posix interp 888 */
 #else
   td.flags = W_ASSIGNRHS;
 #endif
   td.flags |= (W_NOGLOB|W_TILDEEXP);
   td.word = savestring (string);
   value = call_expand_word_internal (&td, quoted, 0, (int *)NULL, (int *)NULL);
   FREE (td.word);
   expand_no_split_dollar_star = 0;
   if (value)
     {
       if (value->word)
     {
       remove_quoted_nulls (value->word->word);  /* XXX */
       value->word->flags &= ~W_HASQUOTEDNULL;
     }
       dequote_list (value);
     }
   return (value);
 }
References call_expand_word_internal(), dequote_list(), expand_no_split_dollar_star, FREE, NULL, remove_quoted_nulls(), savestring(), td, value, W_ASSIGNRHS, W_HASQUOTEDNULL, W_NOGLOB, W_NOSPLIT2, and W_TILDEEXP.
Referenced by do_assignment_internal(), and expand_assignment_string_to_string().
expand_string_dollar_quote()
char* expand_string_dollar_quote (char * string, int flags)
Definition at line 4175 of file subst.c.
 {
   size_t slen, retind, retsize;
   int sindex, c, translen, peekc, news;
   char *ret, *trans, *send, *t;
   DECLARE_MBSTATE;
   slen = strlen (string);
   send = string + slen;
   sindex = 0;
   retsize = slen + 1;
   ret = xmalloc (retsize);
   retind = 0;
   while (c = string[sindex])
     {
       switch (c)
     {
     default:
       RESIZE_MALLOCED_BUFFER (ret, retind, locale_mb_cur_max + 1, retsize, 64);
       COPY_CHAR_I (ret, retind, string, send, sindex);
       break;
     case '\\':
       RESIZE_MALLOCED_BUFFER (ret, retind, locale_mb_cur_max + 2, retsize, 64);
       ret[retind++] = string[sindex++];
       if (string[sindex])
         COPY_CHAR_I (ret, retind, string, send, sindex);
       break;
     case '\'':
     case '"':
       if (c == '\'')
         news = skip_single_quoted (string, slen, ++sindex, SX_COMPLETE);
       else
         news = skip_double_quoted (string, slen, ++sindex, SX_COMPLETE);
       translen = news - sindex - 1;
       RESIZE_MALLOCED_BUFFER (ret, retind, translen + 3, retsize, 64);
       ret[retind++] = c;
       if (translen > 0)
         {
           strncpy (ret + retind, string + sindex, translen);
           retind += translen;
         }
       if (news > sindex && string[news - 1] == c)
         ret[retind++] = c;
       sindex = news;
       break;
     case CTLESC:
       RESIZE_MALLOCED_BUFFER (ret, retind, locale_mb_cur_max + 2, retsize, 64);
       if (flags)
         ret[retind++] = string[sindex++];
       if (string[sindex])
         COPY_CHAR_I (ret, retind, string, send, sindex);
       break;
     case '$':
       peekc = string[++sindex];
 #if defined (TRANSLATABLE_STRINGS)
       if (peekc != '\'' && peekc != '"')
 #else
       if (peekc != '\'')
 #endif
         {
           RESIZE_MALLOCED_BUFFER (ret, retind, 2, retsize, 16);
           ret[retind++] = c;
           break;
         }
       if (string[sindex + 1] == '\0')   /* don't bother */
         {
           RESIZE_MALLOCED_BUFFER (ret, retind, 3, retsize, 16);
           ret[retind++] = c;
           ret[retind++] = peekc;
           sindex++;
           break;
         }
       if (peekc == '\'')
         {
           /* SX_COMPLETE is the  equivalent of ALLOWESC here */
           /* We overload SX_COMPLETE below */
           news = skip_single_quoted (string, slen, ++sindex, SX_COMPLETE);
           /* Check for unclosed string and don't bother if so */
           if (news > sindex && string[news] == '\0' && string[news-1] != peekc)
         {
           RESIZE_MALLOCED_BUFFER (ret, retind, 3, retsize, 16);
           ret[retind++] = c;
           ret[retind++] = peekc;
           continue;
         }
           t = substring (string, sindex, news - 1);
           trans = ansiexpand (t, 0, news-sindex-1, &translen);
           free (t);
           t = sh_single_quote (trans);
           sindex = news;
         }
 #if defined (TRANSLATABLE_STRINGS)
       else
         {
           news = ++sindex;
           t = string_extract_double_quoted (string, &news, SX_COMPLETE);
           /* Check for unclosed string and don't bother if so */
           if (news > sindex && string[news] == '\0' && string[news-1] != peekc)
         {
           RESIZE_MALLOCED_BUFFER (ret, retind, 3, retsize, 16);
           ret[retind++] = c;
           ret[retind++] = peekc;
           free (t);
           continue;
         }
           trans = locale_expand (t, 0, news-sindex, 0, &translen);
           free (t);
           if (singlequote_translations &&
             ((news-sindex-1) != translen || STREQN (t, trans, translen) == 0))
         t = sh_single_quote (trans);
           else
         t = sh_mkdoublequoted (trans, translen, 0);
           sindex = news;
         }
 #endif /* TRANSLATABLE_STRINGS */
       free (trans);
       trans = t;
       translen = strlen (trans);
       RESIZE_MALLOCED_BUFFER (ret, retind, translen + 1, retsize, 128);
       strcpy (ret + retind, trans);
       retind += translen;
       FREE (trans);
       break;
     }
     }
   ret[retind] = 0;
   return ret;
 }
References ansiexpand(), c, COPY_CHAR_I, CTLESC, DECLARE_MBSTATE, flags, FREE, free, locale_mb_cur_max, RESIZE_MALLOCED_BUFFER, send(), sh_mkdoublequoted(), sh_single_quote(), singlequote_translations, skip_double_quoted(), skip_single_quoted(), strcpy, STREQN, string_extract_double_quoted(), strlen(), strncpy(), substring(), SX_COMPLETE, t, trans, and xmalloc.
expand_string_for_pat()
static WORD_LIST* expand_string_for_pat (char * string, int quoted, int * dollar_at_p, int * expanded_p) static
Definition at line 4559 of file subst.c.
 {
   WORD_DESC td;
   WORD_LIST *tresult;
   int oexp;
   if (string == 0 || *string == '\0')
     return (WORD_LIST *)NULL;
   oexp = expand_no_split_dollar_star;
   expand_no_split_dollar_star = 1;
   td.flags = W_NOSPLIT2;        /* no splitting, remove "" and '' */
   td.word = savestring (string);
   tresult = call_expand_word_internal (&td, quoted, 1, dollar_at_p, expanded_p);
   expand_no_split_dollar_star = oexp;
   free (td.word);
   return (tresult);
 }
References call_expand_word_internal(), expand_no_split_dollar_star, free, NULL, savestring(), td, and W_NOSPLIT2.
Referenced by expand_string_for_patsub(), and getpattern().
expand_string_for_patsub()
static char* expand_string_for_patsub (char * string, int quoted) static
Definition at line 3986 of file subst.c.
 {
   WORD_LIST *value;
   char *ret, *t;
   if (string == 0 || *string == '\0')
     return (char *)NULL;
   value = expand_string_for_pat (string, quoted, (int *)0, (int *)0);
   if (value && value->word)
     {
       remove_quoted_nulls (value->word->word);  /* XXX */
       value->word->flags &= ~W_HASQUOTEDNULL;
     }
   if (value)
     {
       t = (value->next) ? string_list (value) : value->word->word;
       ret = quote_string_for_repl (t, quoted);
       if (t != value->word->word)
     free (t);
       dispose_words (value);
     }
   else
     ret = (char *)NULL;
   return (ret);
 }
References dispose_words(), expand_string_for_pat(), free, NULL, quote_string_for_repl(), remove_quoted_nulls(), string_list(), t, value, and W_HASQUOTEDNULL.
Referenced by parameter_brace_patsub().
expand_string_for_rhs()
static WORD_LIST* expand_string_for_rhs (char * string, int quoted, int op, int pflags, int * dollar_at_p, int * expanded_p) static
Definition at line 4511 of file subst.c.
 {
   WORD_DESC td;
   WORD_LIST *tresult;
   int old_nosplit;
   if (string == 0 || *string == '\0')
     return (WORD_LIST *)NULL;
   /* We want field splitting to be determined by what is going to be done with
      the entire ${parameterOPword} expansion, so we don't want to split the RHS
      we expand here.  However, the expansion of $* is determined by whether we
      are going to eventually perform word splitting, so we want to set this
      depending on whether or not are are going to be splitting: if the expansion
      is quoted, if the OP is `=', or if IFS is set to the empty string, we
      are not going to be splitting, so we set expand_no_split_dollar_star to
      note this to callees.
      We pass through PF_ASSIGNRHS as W_ASSIGNRHS if this is on the RHS of an
      assignment statement. */
   /* The updated treatment of $* is the result of Posix interp 888 */
   /* This was further clarified on the austin-group list in March, 2017 and
      in Posix bug 1129 */
   old_nosplit = expand_no_split_dollar_star;
   expand_no_split_dollar_star = (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) || op == '=' || ifs_is_null == 0;  /* XXX - was 1 */
   td.flags = W_EXPANDRHS;       /* expanding RHS of ${paramOPword} */
   td.flags |= W_NOSPLIT2;       /* no splitting, remove "" and '' */
   if (pflags & PF_ASSIGNRHS)        /* pass through */
     td.flags |= W_ASSIGNRHS;
   if (op == '=')
 #if 0
     td.flags |= W_ASSIGNRHS;        /* expand b in ${a=b} like assignment */
 #else
     td.flags |= W_ASSIGNRHS|W_NOASSNTILDE;      /* expand b in ${a=b} like assignment */
 #endif
   td.word = savestring (string);
   tresult = call_expand_word_internal (&td, quoted, 1, dollar_at_p, expanded_p);
   expand_no_split_dollar_star = old_nosplit;
   free (td.word);
   return (tresult);
 }
References call_expand_word_internal(), expand_no_split_dollar_star, free, ifs_is_null, NULL, PF_ASSIGNRHS, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, savestring(), td, W_ASSIGNRHS, W_EXPANDRHS, W_NOASSNTILDE, and W_NOSPLIT2.
Referenced by parameter_brace_expand_rhs().
expand_string_if_necessary()
static char* expand_string_if_necessary (char * string, int quoted, EXPFUNC * func) static
Definition at line 3830 of file subst.c.
 {
   WORD_LIST *list;
   size_t slen;
   int i, saw_quote;
   char *ret;
   DECLARE_MBSTATE;
   /* Don't need string length for ADVANCE_CHAR unless multibyte chars possible. */
   slen = (MB_CUR_MAX > 1) ? strlen (string) : 0;
   i = saw_quote = 0;
   while (string[i])
     {
       if (EXP_CHAR (string[i]))
     break;
       else if (string[i] == '\'' || string[i] == '\\' || string[i] == '"')
     saw_quote = 1;
       ADVANCE_CHAR (string, slen, i);
     }
   if (string[i])
     {
       list = (*func) (string, quoted);
       if (list)
     {
       ret = string_list (list);
       dispose_words (list);
     }
       else
     ret = (char *)NULL;
     }
   else if (saw_quote && ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0))
     ret = string_quote_removal (string, quoted);
   else
     ret = savestring (string);
   return ret;
 }
References ADVANCE_CHAR, DECLARE_MBSTATE, dispose_words(), EXP_CHAR, i, list(), MB_CUR_MAX, NULL, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, savestring(), string, string_list(), string_quote_removal(), and strlen().
Referenced by do_assignment_internal(), and parameter_brace_patsub().
expand_string_internal()
static WORD_LIST* expand_string_internal (char * string, int quoted) static
Definition at line 4347 of file subst.c.
 {
   WORD_DESC td;
   WORD_LIST *tresult;
   if (string == 0 || *string == 0)
     return ((WORD_LIST *)NULL);
   td.flags = 0;
   td.word = savestring (string);
   tresult = call_expand_word_internal (&td, quoted, 0, (int *)NULL, (int *)NULL);
   FREE (td.word);
   return (tresult);
 }
References call_expand_word_internal(), FREE, NULL, savestring(), and td.
Referenced by expand_string_leave_quoted(), and expand_string_unsplit().
expand_string_leave_quoted()
static WORD_LIST* expand_string_leave_quoted (char * string, int quoted) static
Definition at line 4487 of file subst.c.
 {
   WORD_LIST *tlist;
   WORD_LIST *tresult;
   if (string == 0 || *string == '\0')
     return ((WORD_LIST *)NULL);
   tlist = expand_string_internal (string, quoted);
   if (tlist)
     {
       tresult = word_list_split (tlist);
       dispose_words (tlist);
       return (tresult);
     }
   return ((WORD_LIST *)NULL);
 }
References dispose_words(), expand_string_internal(), NULL, and word_list_split().
Referenced by expand_string().
expand_string_to_string()
char* expand_string_to_string (char * string, int quoted)
Definition at line 3897 of file subst.c.
 {
   return (expand_string_to_string_internal (string, quoted, expand_string));
 }
References expand_string(), and expand_string_to_string_internal().
Referenced by check_mail(), and heredoc_expand().
expand_string_to_string_internal()
static char* expand_string_to_string_internal (char * string, int quoted, EXPFUNC * func) inline static
Definition at line 3873 of file subst.c.
 {
   WORD_LIST *list;
   char *ret;
   if (string == 0 || *string == '\0')
     return ((char *)NULL);
   list = (*func) (string, quoted);
   if (list)
     {
       ret = string_list (list);
       dispose_words (list);
     }
   else
     ret = (char *)NULL;
   return (ret);
 }
References dispose_words(), list(), NULL, string, and string_list().
Referenced by expand_assignment_string_to_string(), expand_string_to_string(), expand_string_unsplit_to_string(), and parameter_brace_patsub().
expand_string_unsplit()
WORD_LIST* expand_string_unsplit (char * string, int quoted)
Definition at line 4372 of file subst.c.
 {
   WORD_LIST *value;
   if (string == 0 || *string == '\0')
     return ((WORD_LIST *)NULL);
   expand_no_split_dollar_star = 1;
   value = expand_string_internal (string, quoted);
   expand_no_split_dollar_star = 0;
   if (value)
     {
       if (value->word)
     {
       remove_quoted_nulls (value->word->word);  /* XXX */
       value->word->flags &= ~W_HASQUOTEDNULL;
     }
       dequote_list (value);
     }
   return (value);
 }
References dequote_list(), expand_no_split_dollar_star, expand_string_internal(), NULL, remove_quoted_nulls(), value, and W_HASQUOTEDNULL.
Referenced by expand_string_unsplit_to_string(), and parameter_brace_patsub().
expand_string_unsplit_to_string()
char* expand_string_unsplit_to_string (char * string, int quoted)
Definition at line 3905 of file subst.c.
 {
   return (expand_string_to_string_internal (string, quoted, expand_string_unsplit));
 }
References expand_string_to_string_internal(), and expand_string_unsplit().
Referenced by execute_env_file().
expand_word()
WORD_LIST* expand_word (WORD_DESC * word, int quoted)
Definition at line 4611 of file subst.c.
 {
   WORD_LIST *result, *tresult;
   tresult = call_expand_word_internal (word, quoted, 0, (int *)NULL, (int *)NULL);
   result = word_list_split (tresult);
   dispose_words (tresult);
   return (result ? dequote_list (result) : result);
 }
References call_expand_word_internal(), dequote_list(), dispose_words(), NULL, and word_list_split().
expand_word_internal()
static WORD_LIST* expand_word_internal (WORD_DESC * word, int quoted, int isexp, int * contains_dollar_at, int * expanded_something) static
Definition at line 10928 of file subst.c.
 {
   WORD_LIST *list;
   WORD_DESC *tword;
   /* The intermediate string that we build while expanding. */
   char *istring;
   /* The current size of the above object. */
   size_t istring_size;
   /* Index into ISTRING. */
   size_t istring_index;
   /* Temporary string storage. */
   char *temp, *temp1;
   /* The text of WORD. */
   register char *string;
   /* The size of STRING. */
   size_t string_size;
   /* The index into STRING. */
   int sindex;
   /* This gets 1 if we see a $@ while quoted. */
   int quoted_dollar_at;
   /* One of UNQUOTED, PARTIALLY_QUOTED, or WHOLLY_QUOTED, depending on
      whether WORD contains no quoting characters, a partially quoted
      string (e.g., "xx"ab), or is fully quoted (e.g., "xxab"). */
   int quoted_state;
   /* State flags */
   int had_quoted_null;
   int has_quoted_ifs;       /* did we add a quoted $IFS character here? */
   int has_dollar_at, temp_has_dollar_at;
   int internal_tilde;
   int split_on_spaces;
   int local_expanded;
   int tflag;
   int pflags;           /* flags passed to param_expand */
   int mb_cur_max;
   int assignoff;        /* If assignment, offset of `=' */
   register unsigned char c; /* Current character. */
   int t_index;          /* For calls to string_extract_xxx. */
   char twochars[2];
   DECLARE_MBSTATE;
   /* OK, let's see if we can optimize a common idiom: "$@". This needs to make sure
      that all of the flags callers care about (e.g., W_HASQUOTEDNULL) are set in
      list->flags. */
   if (STREQ (word->word, "\"$@\"") &&
       (word->flags == (W_HASDOLLAR|W_QUOTED)) &&
       dollar_vars[1])       /* XXX - check IFS here as well? */
     {
       if (contains_dollar_at)
     *contains_dollar_at = 1;
       if (expanded_something)
     *expanded_something = 1;
       if (cached_quoted_dollar_at)
     return (copy_word_list (cached_quoted_dollar_at));
       list = list_rest_of_args ();
       list = quote_list (list);
       cached_quoted_dollar_at = copy_word_list (list);
       return (list);
     }
   istring = (char *)xmalloc (istring_size = DEFAULT_INITIAL_ARRAY_SIZE);
   istring[istring_index = 0] = '\0';
   quoted_dollar_at = had_quoted_null = has_dollar_at = 0;
   has_quoted_ifs = 0;
   split_on_spaces = 0;
   internal_tilde = 0;       /* expanding =~ or :~ */
   quoted_state = UNQUOTED;
   string = word->word;
   if (string == 0)
     goto finished_with_string;
   mb_cur_max = MB_CUR_MAX;
   /* Don't need the string length for the SADD... and COPY_ macros unless
      multibyte characters are possible, but do need it for bounds checking. */
   string_size = (mb_cur_max > 1) ? strlen (string) : 1;
   if (contains_dollar_at)
     *contains_dollar_at = 0;
   assignoff = -1;
   /* Begin the expansion. */
   for (sindex = 0; ;)
     {
       c = string[sindex];
       /* Case on top-level character. */
       switch (c)
     {
     case '\0':
       goto finished_with_string;
     case CTLESC:
       sindex++;
 #if HANDLE_MULTIBYTE
       if (mb_cur_max > 1 && string[sindex])
         {
           SADD_MBQCHAR_BODY(temp, string, sindex, string_size);
         }
       else
 #endif
         {
           temp = (char *)xmalloc (3);
           temp[0] = CTLESC;
           temp[1] = c = string[sindex];
           temp[2] = '\0';
         }
 dollar_add_string:
       if (string[sindex])
         sindex++;
 add_string:
       if (temp)
         {
           istring = sub_append_string (temp, istring, &istring_index, &istring_size);
           temp = (char *)0;
         }
       break;
 #if defined (PROCESS_SUBSTITUTION)
       /* Process substitution. */
     case '<':
     case '>':
       {
            /* XXX - technically this should only be expanded at the start
            of a word */
         if (string[++sindex] != LPAREN || (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) || (word->flags & W_NOPROCSUB))
           {
         sindex--;   /* add_character: label increments sindex */
         goto add_character;
           }
         else
           t_index = sindex + 1; /* skip past both '<' and LPAREN */
         temp1 = extract_process_subst (string, (c == '<') ? "<(" : ">(", &t_index, 0); /*))*/
         sindex = t_index;
         /* If the process substitution specification is `<()', we want to
            open the pipe for writing in the child and produce output; if
            it is `>()', we want to open the pipe for reading in the child
            and consume input. */
         temp = temp1 ? process_substitute (temp1, (c == '>')) : (char *)0;
         FREE (temp1);
         goto dollar_add_string;
       }
 #endif /* PROCESS_SUBSTITUTION */
 #if defined (ARRAY_VARS)
     case '[':       /*]*/
       if ((quoted & Q_ARITH) == 0 || shell_compatibility_level <= 51)
         {
           if (isexp == 0 && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0 && isifs (c) && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) == 0)
         goto add_ifs_character;
           else
         goto add_character;
         }
       else
         {
           temp = expand_array_subscript (string, &sindex, quoted, word->flags);
           goto add_string;
         }
 #endif
     case '=':
       /* Posix.2 section 3.6.1 says that tildes following `=' in words
          which are not assignment statements are not expanded.  If the
          shell isn't in posix mode, though, we perform tilde expansion
          on `likely candidate' unquoted assignment statements (flags
          include W_ASSIGNMENT but not W_QUOTED).  A likely candidate
          contains an unquoted :~ or =~.  Something to think about: we
          now have a flag that says  to perform tilde expansion on arguments
          to `assignment builtins' like declare and export that look like
          assignment statements.  We now do tilde expansion on such words
          even in POSIX mode. */
       if (word->flags & (W_ASSIGNRHS|W_NOTILDE))
         {
           if (isexp == 0 && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0 && isifs (c))
         goto add_ifs_character;
           else
         goto add_character;
         }
       /* If we're not in posix mode or forcing assignment-statement tilde
          expansion, note where the first `=' appears in the word and prepare
          to do tilde expansion following the first `='. We have to keep
          track of the first `=' (using assignoff) to avoid being confused
          by an `=' in the rhs of the assignment statement. */
       if ((word->flags & W_ASSIGNMENT) &&
           (posixly_correct == 0 || (word->flags & W_TILDEEXP)) &&
           assignoff == -1 && sindex > 0)
         assignoff = sindex;
       if (sindex == assignoff && string[sindex+1] == '~')   /* XXX */
         internal_tilde = 1;
       if (word->flags & W_ASSIGNARG)
         word->flags |= W_ASSIGNRHS;     /* affects $@ */
       if (isexp == 0 && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0 && isifs (c))
         {
           has_quoted_ifs++;
           goto add_ifs_character;
         }
       else
         goto add_character;
     case ':':
       if (word->flags & (W_NOTILDE|W_NOASSNTILDE))
         {
           if (isexp == 0 && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0 && isifs (c))
         goto add_ifs_character;
           else
         goto add_character;
         }
       if ((word->flags & (W_ASSIGNMENT|W_ASSIGNRHS)) &&
           (posixly_correct == 0 || (word->flags & W_TILDEEXP)) &&
           string[sindex+1] == '~')
         internal_tilde = 1;
       if (isexp == 0 && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0 && isifs (c))
         goto add_ifs_character;
       else
         goto add_character;
     case '~':
       /* If the word isn't supposed to be tilde expanded, or we're not
          at the start of a word or after an unquoted : or = in an
          assignment statement, we don't do tilde expansion.  We don't
          do tilde expansion if quoted or in an arithmetic context. */
       if ((word->flags & W_NOTILDE) ||
           (sindex > 0 && (internal_tilde == 0)) ||
           (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
         {
           internal_tilde = 0;
           if (isexp == 0 && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0 && isifs (c) && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) == 0)
         goto add_ifs_character;
           else
         goto add_character;
         }
       if (word->flags & W_ASSIGNRHS)
         tflag = 2;
       else if (word->flags & (W_ASSIGNMENT|W_TILDEEXP))
         tflag = 1;
       else
         tflag = 0;
       temp = bash_tilde_find_word (string + sindex, tflag, &t_index);
       internal_tilde = 0;
       if (temp && *temp && t_index > 0)
         {
           temp1 = bash_tilde_expand (temp, tflag);
           if  (temp1 && *temp1 == '~' && STREQ (temp, temp1))
         {
           FREE (temp);
           FREE (temp1);
           goto add_character;       /* tilde expansion failed */
         }
           free (temp);
           temp = temp1;
           sindex += t_index;
           goto add_quoted_string;       /* XXX was add_string */
         }
       else
         {
           FREE (temp);
           goto add_character;
         }
     case '$':
       if (expanded_something)
         *expanded_something = 1;
       local_expanded = 1;
       temp_has_dollar_at = 0;
       pflags = (word->flags & W_NOCOMSUB) ? PF_NOCOMSUB : 0;
       if (word->flags & W_NOSPLIT2)
         pflags |= PF_NOSPLIT2;
       if (word->flags & W_ASSIGNRHS)
         pflags |= PF_ASSIGNRHS;
       if (word->flags & W_COMPLETE)
         pflags |= PF_COMPLETE;
       tword = param_expand (string, &sindex, quoted, expanded_something,
                    &temp_has_dollar_at, &quoted_dollar_at,
                    &had_quoted_null, pflags);
       has_dollar_at += temp_has_dollar_at;
       split_on_spaces += (tword->flags & W_SPLITSPACE);
       if (tword == &expand_wdesc_error || tword == &expand_wdesc_fatal)
         {
           free (string);
           free (istring);
           return ((tword == &expand_wdesc_error) ? &expand_word_error
                              : &expand_word_fatal);
         }
       if (contains_dollar_at && has_dollar_at)
         *contains_dollar_at = 1;
       if (tword && (tword->flags & W_HASQUOTEDNULL))
         had_quoted_null = 1;        /* note for later */
       if (tword && (tword->flags & W_SAWQUOTEDNULL))
         had_quoted_null = 1;        /* XXX */
       temp = tword ? tword->word : (char *)NULL;
       dispose_word_desc (tword);
       /* Kill quoted nulls; we will add them back at the end of
          expand_word_internal if nothing else in the string */
       if (had_quoted_null && temp && QUOTED_NULL (temp))
         {
           FREE (temp);
           temp = (char *)NULL;
         }
       goto add_string;
       break;
     case '`':       /* Backquoted command substitution. */
       {
         t_index = sindex++;
         temp = string_extract (string, &sindex, "`", (word->flags & W_COMPLETE) ? SX_COMPLETE : SX_REQMATCH);
         /* The test of sindex against t_index is to allow bare instances of
            ` to pass through, for backwards compatibility. */
         if (temp == &extract_string_error || temp == &extract_string_fatal)
           {
         if (sindex - 1 == t_index)
           {
             sindex = t_index;
             goto add_character;
           }
         set_exit_status (EXECUTION_FAILURE);
         report_error (_("bad substitution: no closing \"`\" in %s") , string+t_index);
         free (string);
         free (istring);
         return ((temp == &extract_string_error) ? &expand_word_error
                             : &expand_word_fatal);
           }
         if (expanded_something)
           *expanded_something = 1;
         local_expanded = 1;
         if (word->flags & W_NOCOMSUB)
           /* sindex + 1 because string[sindex] == '`' */
           temp1 = substring (string, t_index, sindex + 1);
         else
           {
         de_backslash (temp);
         tword = command_substitute (temp, quoted, PF_BACKQUOTE);
         temp1 = tword ? tword->word : (char *)NULL;
         if (tword)
           dispose_word_desc (tword);
           }
         FREE (temp);
         temp = temp1;
         goto dollar_add_string;
       }
     case '\\':
       if (string[sindex + 1] == '\n')
         {
           sindex += 2;
           continue;
         }
       c = string[++sindex];
       /* "However, the double-quote character ( '"' ) shall not be treated
          specially within a here-document, except when the double-quote
          appears within "$()", "``", or "${}"." */
       if ((quoted & Q_HERE_DOCUMENT) && (quoted & Q_DOLBRACE) && c == '"')
         tflag = CBSDQUOTE;      /* special case */
       else if (quoted & Q_HERE_DOCUMENT)
         tflag = CBSHDOC;
       else if (quoted & Q_DOUBLE_QUOTES)
         tflag = CBSDQUOTE;
       else
         tflag = 0;
       /* From Posix discussion on austin-group list:  Backslash escaping
          a } in ${...} is removed.  Issue 0000221 */
       if ((quoted & Q_DOLBRACE) && c == RBRACE)
         {
           SCOPY_CHAR_I (twochars, CTLESC, c, string, sindex, string_size);
         }
       /* This is the fix for " $@\ " */
       else if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && ((sh_syntaxtab[c] & tflag) == 0) && isexp == 0 && isifs (c))
         {
           RESIZE_MALLOCED_BUFFER (istring, istring_index, 2, istring_size,
                       DEFAULT_ARRAY_SIZE);
           istring[istring_index++] = CTLESC;
           istring[istring_index++] = '\\';
           istring[istring_index] = '\0';
           SCOPY_CHAR_I (twochars, CTLESC, c, string, sindex, string_size);
         }
       else if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && c == 0)
         {
           RESIZE_MALLOCED_BUFFER (istring, istring_index, 2, istring_size,
                       DEFAULT_ARRAY_SIZE);
           istring[istring_index++] = CTLESC;
           istring[istring_index++] = '\\';
           istring[istring_index] = '\0';
           break;
         }
       else if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && ((sh_syntaxtab[c] & tflag) == 0))
         {
           SCOPY_CHAR_I (twochars, '\\', c, string, sindex, string_size);
         }
       else if (c == 0)
         {
           c = CTLNUL;
           sindex--;     /* add_character: label increments sindex */
           goto add_character;
         }
       else
         {
           SCOPY_CHAR_I (twochars, CTLESC, c, string, sindex, string_size);
         }
       sindex++;
 add_twochars:
       /* BEFORE jumping here, we need to increment sindex if appropriate */
       RESIZE_MALLOCED_BUFFER (istring, istring_index, 2, istring_size,
                   DEFAULT_ARRAY_SIZE);
       istring[istring_index++] = twochars[0];
       istring[istring_index++] = twochars[1];
       istring[istring_index] = '\0';
       break;
     case '"':
       /* XXX - revisit this */
       if ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) && ((quoted & Q_ARITH) == 0))
         goto add_character;
       t_index = ++sindex;
       temp = string_extract_double_quoted (string, &sindex, (word->flags & W_COMPLETE) ? SX_COMPLETE : 0);
       /* If the quotes surrounded the entire string, then the
          whole word was quoted. */
       quoted_state = (t_index == 1 && string[sindex] == '\0')
                 ? WHOLLY_QUOTED
                 : PARTIALLY_QUOTED;
       if (temp && *temp)
         {
           tword = alloc_word_desc ();
           tword->word = temp;
           if (word->flags & W_ASSIGNARG)
         tword->flags |= word->flags & (W_ASSIGNARG|W_ASSIGNRHS); /* affects $@ */
           if (word->flags & W_COMPLETE)
         tword->flags |= W_COMPLETE; /* for command substitutions */
           if (word->flags & W_NOCOMSUB)
         tword->flags |= W_NOCOMSUB;
           if (word->flags & W_NOPROCSUB)
         tword->flags |= W_NOPROCSUB;
           if (word->flags & W_ASSIGNRHS)
         tword->flags |= W_ASSIGNRHS;
           temp = (char *)NULL;
           temp_has_dollar_at = 0;   /* does this quoted (sub)string include $@? */
           /* Need to get W_HASQUOTEDNULL flag through this function. */
           /* XXX - preserve Q_ARITH here? */
           list = expand_word_internal (tword, Q_DOUBLE_QUOTES|(quoted&Q_ARITH), 0, &temp_has_dollar_at, (int *)NULL);
           has_dollar_at += temp_has_dollar_at;
           if (list == &expand_word_error || list == &expand_word_fatal)
         {
           free (istring);
           free (string);
           /* expand_word_internal has already freed temp_word->word
              for us because of the way it prints error messages. */
           tword->word = (char *)NULL;
           dispose_word (tword);
           return list;
         }
           dispose_word (tword);
           /* "$@" (a double-quoted dollar-at) expands into nothing,
          not even a NULL word, when there are no positional
          parameters.  Posix interp 888 says that other parts of the
          word that expand to quoted nulls result in quoted nulls, so
          we can't just throw the entire word away if we have "$@"
          anywhere in it.  We use had_quoted_null to keep track */
           if (list == 0 && temp_has_dollar_at)  /* XXX - was has_dollar_at */
         {
           quoted_dollar_at++;
           break;
         }
           /* If this list comes back with a quoted null from expansion,
          we have either "$x" or "$@" with $1 == ''. In either case,
          we need to make sure we add a quoted null argument and
          disable the special handling that "$@" gets. */
           if (list && list->word && list->next == 0 && (list->word->flags & W_HASQUOTEDNULL))
         {
           if (had_quoted_null && temp_has_dollar_at)
             quoted_dollar_at++;
           had_quoted_null = 1;      /* XXX */
         }
           /* If we get "$@", we know we have expanded something, so we
          need to remember it for the final split on $IFS.  This is
          a special case; it's the only case where a quoted string
          can expand into more than one word.  It's going to come back
          from the above call to expand_word_internal as a list with
          multiple words. */
           if (list)
         dequote_list (list);
           if (temp_has_dollar_at)       /* XXX - was has_dollar_at */
         {
           quoted_dollar_at++;
           if (contains_dollar_at)
             *contains_dollar_at = 1;
           if (expanded_something)
             *expanded_something = 1;
           local_expanded = 1;
         }
         }
       else
         {
           /* What we have is "".  This is a minor optimization. */
           FREE (temp);
           list = (WORD_LIST *)NULL;
           had_quoted_null = 1;  /* note for later */
         }
       /* The code above *might* return a list (consider the case of "$@",
          where it returns "$1", "$2", etc.).  We can't throw away the
          rest of the list, and we have to make sure each word gets added
          as quoted.  We test on tresult->next:  if it is non-NULL, we
          quote the whole list, save it to a string with string_list, and
          add that string. We don't need to quote the results of this
          (and it would be wrong, since that would quote the separators
          as well), so we go directly to add_string. */
       if (list)
         {
           if (list->next)
         {
           /* Testing quoted_dollar_at makes sure that "$@" is
              split correctly when $IFS does not contain a space. */
           temp = quoted_dollar_at
                 ? string_list_dollar_at (list, Q_DOUBLE_QUOTES, 0)
                 : string_list (quote_list (list));
           dispose_words (list);
           goto add_string;
         }
           else
         {
           temp = savestring (list->word->word);
           tflag = list->word->flags;
           dispose_words (list);
           /* If the string is not a quoted null string, we want
              to remove any embedded unquoted CTLNUL characters.
              We do not want to turn quoted null strings back into
              the empty string, though.  We do this because we
              want to remove any quoted nulls from expansions that
              contain other characters.  For example, if we have
              x"$*"y or "x$*y" and there are no positional parameters,
              the $* should expand into nothing. */
           /* We use the W_HASQUOTEDNULL flag to differentiate the
              cases:  a quoted null character as above and when
              CTLNUL is contained in the (non-null) expansion
              of some variable.  We use the had_quoted_null flag to
              pass the value through this function to its caller. */
           if ((tflag & W_HASQUOTEDNULL) && QUOTED_NULL (temp) == 0)
             remove_quoted_nulls (temp); /* XXX */
         }
         }
       else
         temp = (char *)NULL;
       if (temp == 0 && quoted_state == PARTIALLY_QUOTED)
         had_quoted_null = 1;    /* note for later */
       /* We do not want to add quoted nulls to strings that are only
          partially quoted; we can throw them away.  The exception to
          this is when we are going to be performing word splitting,
          since we have to preserve a null argument if the next character
          will cause word splitting. */
       if (temp == 0 && quoted_state == PARTIALLY_QUOTED && quoted == 0 && (word->flags & (W_NOSPLIT|W_EXPANDRHS|W_ASSIGNRHS)) == W_EXPANDRHS)
         {
           c = CTLNUL;
           sindex--;
           had_quoted_null = 1;
           goto add_character;
         }
       if (temp == 0 && quoted_state == PARTIALLY_QUOTED && (word->flags & (W_NOSPLIT|W_NOSPLIT2)))
         continue;
     add_quoted_string:
       if (temp)
         {
           temp1 = temp;
           temp = quote_string (temp);
           free (temp1);
           goto add_string;
         }
       else
         {
           /* Add NULL arg. */
           c = CTLNUL;
           sindex--;     /* add_character: label increments sindex */
           had_quoted_null = 1;  /* note for later */
           goto add_character;
         }
       /* break; */
     case '\'':
       if ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
         goto add_character;
       t_index = ++sindex;
       temp = string_extract_single_quoted (string, &sindex, 0);
       /* If the entire STRING was surrounded by single quotes,
          then the string is wholly quoted. */
       quoted_state = (t_index == 1 && string[sindex] == '\0')
                 ? WHOLLY_QUOTED
                 : PARTIALLY_QUOTED;
       /* If all we had was '', it is a null expansion. */
       if (*temp == '\0')
         {
           free (temp);
           temp = (char *)NULL;
         }
       else
         remove_quoted_escapes (temp);   /* ??? */
       if (temp == 0 && quoted_state == PARTIALLY_QUOTED)
         had_quoted_null = 1;    /* note for later */
       /* We do not want to add quoted nulls to strings that are only
          partially quoted; such nulls are discarded.  See above for the
          exception, which is when the string is going to be split.
          Posix interp 888/1129 */
       if (temp == 0 && quoted_state == PARTIALLY_QUOTED && quoted == 0 && (word->flags & (W_NOSPLIT|W_EXPANDRHS|W_ASSIGNRHS)) == W_EXPANDRHS)
         {
           c = CTLNUL;
           sindex--;
           goto add_character;
         }
       if (temp == 0 && (quoted_state == PARTIALLY_QUOTED) && (word->flags & (W_NOSPLIT|W_NOSPLIT2)))
         continue;
       /* If we have a quoted null expansion, add a quoted NULL to istring. */
       if (temp == 0)
         {
           c = CTLNUL;
           sindex--;     /* add_character: label increments sindex */
           goto add_character;
         }
       else
         goto add_quoted_string;
       /* break; */
     case ' ':
       /* If we are in a context where the word is not going to be split, but
          we need to account for $@ and $* producing one word for each
          positional parameter, add quoted spaces so the spaces in the
          expansion of "$@", if any, behave correctly. We still may need to
          split if we are expanding the rhs of a word expansion. */
       if (ifs_is_null || split_on_spaces || ((word->flags & (W_NOSPLIT|W_NOSPLIT2|W_ASSIGNRHS)) && (word->flags & W_EXPANDRHS) == 0))
         {
           if (string[sindex])
         sindex++;
           twochars[0] = CTLESC;
           twochars[1] = c;
           goto add_twochars;
         }
       /* FALLTHROUGH */
     default:
       /* This is the fix for " $@ " */
 add_ifs_character:
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) || (isexp == 0 && isifs (c) && (word->flags & (W_NOSPLIT|W_NOSPLIT2)) == 0))
         {
           if ((quoted&(Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0)
         has_quoted_ifs++;
 add_quoted_character:
           if (string[sindex])   /* from old goto dollar_add_string */
         sindex++;
           if (c == 0)
         {
           c = CTLNUL;
           goto add_character;
         }
           else
         {
 #if HANDLE_MULTIBYTE
           /* XXX - should make sure that c is actually multibyte,
              otherwise we can use the twochars branch */
           if (mb_cur_max > 1)
             sindex--;
           if (mb_cur_max > 1)
             {
               SADD_MBQCHAR_BODY(temp, string, sindex, string_size);
             }
           else
 #endif
             {
               twochars[0] = CTLESC;
               twochars[1] = c;
               goto add_twochars;
             }
         }
         }
       SADD_MBCHAR (temp, string, sindex, string_size);
 add_character:
       RESIZE_MALLOCED_BUFFER (istring, istring_index, 1, istring_size,
                   DEFAULT_ARRAY_SIZE);
       istring[istring_index++] = c;
       istring[istring_index] = '\0';
       /* Next character. */
       sindex++;
     }
     }
 finished_with_string:
   /* OK, we're ready to return.  If we have a quoted string, and
      quoted_dollar_at is not set, we do no splitting at all; otherwise
      we split on ' '.  The routines that call this will handle what to
      do if nothing has been expanded. */
   /* Partially and wholly quoted strings which expand to the empty
      string are retained as an empty arguments.  Unquoted strings
      which expand to the empty string are discarded.  The single
      exception is the case of expanding "$@" when there are no
      positional parameters.  In that case, we discard the expansion. */
   /* Because of how the code that handles "" and '' in partially
      quoted strings works, we need to make ISTRING into a QUOTED_NULL
      if we saw quoting characters, but the expansion was empty.
      "" and '' are tossed away before we get to this point when
      processing partially quoted strings.  This makes "" and $xxx""
      equivalent when xxx is unset.  We also look to see whether we
      saw a quoted null from a ${} expansion and add one back if we
      need to. */
   /* If we expand to nothing and there were no single or double quotes
      in the word, we throw it away.  Otherwise, we return a NULL word.
      The single exception is for $@ surrounded by double quotes when
      there are no positional parameters.  In that case, we also throw
      the word away. */
   if (*istring == '\0')
     {
 #if 0
       if (quoted_dollar_at == 0 && (had_quoted_null || quoted_state == PARTIALLY_QUOTED))
 #else
       if (had_quoted_null || (quoted_dollar_at == 0 && quoted_state == PARTIALLY_QUOTED))
 #endif
     {
       istring[0] = CTLNUL;
       istring[1] = '\0';
       tword = alloc_word_desc ();
       tword->word = istring;
       istring = 0;      /* avoid later free() */
       tword->flags |= W_HASQUOTEDNULL;      /* XXX */
       list = make_word_list (tword, (WORD_LIST *)NULL);
       if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
         tword->flags |= W_QUOTED;
     }
       /* According to sh, ksh, and Posix.2, if a word expands into nothing
      and a double-quoted "$@" appears anywhere in it, then the entire
      word is removed. */
       /* XXX - exception appears to be that quoted null strings result in
      null arguments */
       else  if (quoted_state == UNQUOTED || quoted_dollar_at)
     list = (WORD_LIST *)NULL;
       else
     list = (WORD_LIST *)NULL;
     }
   else if (word->flags & W_NOSPLIT)
     {
       tword = alloc_word_desc ();
       tword->word = istring;
       if (had_quoted_null && QUOTED_NULL (istring))
     tword->flags |= W_HASQUOTEDNULL;
       istring = 0;      /* avoid later free() */
       if (word->flags & W_ASSIGNMENT)
     tword->flags |= W_ASSIGNMENT;   /* XXX */
       if (word->flags & W_COMPASSIGN)
     tword->flags |= W_COMPASSIGN;   /* XXX */
       if (word->flags & W_NOGLOB)
     tword->flags |= W_NOGLOB;   /* XXX */
       if (word->flags & W_NOBRACE)
     tword->flags |= W_NOBRACE;  /* XXX */
       if (word->flags & W_ARRAYREF)
     tword->flags |= W_ARRAYREF;
       if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
     tword->flags |= W_QUOTED;
       list = make_word_list (tword, (WORD_LIST *)NULL);
     }
   else if (word->flags & W_ASSIGNRHS)
     {
       list = list_string (istring, "", quoted);
       tword = list->word;
       if (had_quoted_null && QUOTED_NULL (istring))
     tword->flags |= W_HASQUOTEDNULL;
       free (list);
       free (istring);
       istring = 0;          /* avoid later free() */
       goto set_word_flags;
     }
   else
     {
       char *ifs_chars;
       ifs_chars = (quoted_dollar_at || has_dollar_at) ? ifs_value : (char *)NULL;
       /* If we have $@, we need to split the results no matter what.  If
      IFS is unset or NULL, string_list_dollar_at has separated the
      positional parameters with a space, so we split on space (we have
      set ifs_chars to " \t\n" above if ifs is unset).  If IFS is set,
      string_list_dollar_at has separated the positional parameters
      with the first character of $IFS, so we split on $IFS.  If
      SPLIT_ON_SPACES is set, we expanded $* (unquoted) with IFS either
      unset or null, and we want to make sure that we split on spaces
      regardless of what else has happened to IFS since the expansion,
      or we expanded "$@" with IFS null and we need to split the positional
      parameters into separate words. */
       if (split_on_spaces)
     {
       /* If IFS is not set, and the word is not quoted, we want to split
          the individual words on $' \t\n'. We rely on previous steps to
          quote the portions of the word that should not be split */
       if (ifs_is_set == 0)
         list = list_string (istring, " \t\n", 1);   /* XXX quoted == 1? */
       else
         list = list_string (istring, " ", 1);   /* XXX quoted == 1? */
     }
       /* If we have $@ (has_dollar_at != 0) and we are in a context where we
      don't want to split the result (W_NOSPLIT2), and we are not quoted,
      we have already separated the arguments with the first character of
      $IFS.  In this case, we want to return a list with a single word
      with the separator possibly replaced with a space (it's what other
      shells seem to do).
      quoted_dollar_at is internal to this function and is set if we are
      passed an argument that is unquoted (quoted == 0) but we encounter a
      double-quoted $@ while expanding it. */
       else if (has_dollar_at && quoted_dollar_at == 0 && ifs_chars && quoted == 0 && (word->flags & W_NOSPLIT2))
     {
       tword = alloc_word_desc ();
       /* Only split and rejoin if we have to */
       if (*ifs_chars && *ifs_chars != ' ')
         {
           /* list_string dequotes CTLESCs in the string it's passed, so we
          need it to get the space separation right if space isn't the
          first character in IFS (but is present) and to remove the
          quoting we added back in param_expand(). */
           list = list_string (istring, *ifs_chars ? ifs_chars : " ", 1);
           /* This isn't exactly right in the case where we're expanding
          the RHS of an expansion like ${var-$@} where IFS=: (for
          example). The W_NOSPLIT2 means we do the separation with :;
          the list_string removes the quotes and breaks the string into
          a list, and the string_list rejoins it on spaces. When we
          return, we expect to be able to split the results, but the
          space separation means the right split doesn't happen. */
           tword->word = string_list (list);
         }
       else
         tword->word = istring;
       if (had_quoted_null && QUOTED_NULL (istring))
         tword->flags |= W_HASQUOTEDNULL;    /* XXX */
       if (tword->word != istring)
         free (istring);
       istring = 0;          /* avoid later free() */
       goto set_word_flags;
     }
       else if (has_dollar_at && ifs_chars)
     list = list_string (istring, *ifs_chars ? ifs_chars : " ", 1);
       else
     {
       tword = alloc_word_desc ();
       if (expanded_something && *expanded_something == 0 && has_quoted_ifs)
         tword->word = remove_quoted_ifs (istring);
       else
         tword->word = istring;
       if (had_quoted_null && QUOTED_NULL (istring)) /* should check for more than one */
         tword->flags |= W_HASQUOTEDNULL;    /* XXX */
       else if (had_quoted_null)
         tword->flags |= W_SAWQUOTEDNULL;    /* XXX */
       if (tword->word != istring)
         free (istring);
       istring = 0;          /* avoid later free() */
 set_word_flags:
       if ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) || (quoted_state == WHOLLY_QUOTED))
         tword->flags |= W_QUOTED;
       if (word->flags & W_ASSIGNMENT)
         tword->flags |= W_ASSIGNMENT;
       if (word->flags & W_COMPASSIGN)
         tword->flags |= W_COMPASSIGN;
       if (word->flags & W_NOGLOB)
         tword->flags |= W_NOGLOB;
       if (word->flags & W_NOBRACE)
         tword->flags |= W_NOBRACE;
       if (word->flags & W_ARRAYREF)
         tword->flags |= W_ARRAYREF;
       list = make_word_list (tword, (WORD_LIST *)NULL);
     }
     }
   free (istring);
   return (list);
 }
References _, alloc_word_desc(), bash_tilde_expand(), bash_tilde_find_word(), c, cached_quoted_dollar_at, CBSDQUOTE, CBSHDOC, command_substitute(), copy_word_list(), CTLESC, CTLNUL, de_backslash(), DECLARE_MBSTATE, DEFAULT_ARRAY_SIZE, DEFAULT_INITIAL_ARRAY_SIZE, dequote_list(), dispose_word(), dispose_word_desc(), dispose_words(), dollar_vars, EXECUTION_FAILURE, expand_wdesc_error, expand_wdesc_fatal, expand_word_error, expand_word_fatal, extract_string_error, extract_string_fatal, word_desc::flags, FREE, free, ifs_is_null, ifs_is_set, ifs_value, isifs, list(), list_rest_of_args(), list_string(), LPAREN, make_word_list(), MB_CUR_MAX, node::next, NULL, param_expand(), PARTIALLY_QUOTED, PF_ASSIGNRHS, PF_BACKQUOTE, PF_COMPLETE, PF_NOCOMSUB, PF_NOSPLIT2, posixly_correct, Q_ARITH, Q_DOLBRACE, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_list(), quote_string(), QUOTED_NULL, RBRACE, remove_quoted_escapes(), remove_quoted_ifs(), remove_quoted_nulls(), report_error(), RESIZE_MALLOCED_BUFFER, SADD_MBCHAR, savestring(), SCOPY_CHAR_I, set_exit_status(), sh_syntaxtab, shell_compatibility_level, STREQ, string, string_extract(), string_extract_double_quoted(), string_extract_single_quoted(), string_list(), string_list_dollar_at(), strlen(), sub_append_string(), substring(), SX_COMPLETE, SX_REQMATCH, UNQUOTED, W_ARRAYREF, W_ASSIGNARG, W_ASSIGNMENT, W_ASSIGNRHS, W_COMPASSIGN, W_COMPLETE, W_EXPANDRHS, W_HASDOLLAR, W_HASQUOTEDNULL, W_NOASSNTILDE, W_NOBRACE, W_NOCOMSUB, W_NOGLOB, W_NOPROCSUB, W_NOSPLIT, W_NOSPLIT2, W_NOTILDE, W_QUOTED, W_SAWQUOTEDNULL, W_SPLITSPACE, W_TILDEEXP, WHOLLY_QUOTED, word_desc::word, and xmalloc.
Referenced by call_expand_word_internal(), expand_prompt_string(), and shell_expand_word_list().
expand_word_leave_quoted()
WORD_LIST* expand_word_leave_quoted (WORD_DESC * word, int quoted)
Definition at line 4641 of file subst.c.
 {
   WORD_LIST *result;
   expand_no_split_dollar_star = 1;
   if (ifs_is_null)
     word->flags |= W_NOSPLIT;
   word->flags |= W_NOSPLIT2;
   result = call_expand_word_internal (word, quoted, 0, (int *)NULL, (int *)NULL);
   expand_no_split_dollar_star = 0;
   return result;
 }
References call_expand_word_internal(), expand_no_split_dollar_star, word_desc::flags, ifs_is_null, NULL, W_NOSPLIT, and W_NOSPLIT2.
Referenced by execute_case_command(), and expand_word_unsplit().
expand_word_list_internal()
static WORD_LIST* expand_word_list_internal (WORD_LIST * list, int eflags) static
Definition at line 12961 of file subst.c.
 {
   WORD_LIST *new_list, *temp_list;
   tempenv_assign_error = 0;
   if (list == 0)
     return ((WORD_LIST *)NULL);
   garglist = new_list = copy_word_list (list);
   if (eflags & WEXP_VARASSIGN)
     {
       garglist = new_list = separate_out_assignments (new_list);
       if (new_list == 0)
     {
       if (subst_assign_varlist)
         do_assignment_statements (subst_assign_varlist, (char *)NULL, 1);
       dispose_words (subst_assign_varlist);
       subst_assign_varlist = (WORD_LIST *)NULL;
       return ((WORD_LIST *)NULL);
     }
     }
   /* Begin expanding the words that remain.  The expansions take place on
      things that aren't really variable assignments. */
 #if defined (BRACE_EXPANSION)
   /* Do brace expansion on this word if there are any brace characters
      in the string. */
   if ((eflags & WEXP_BRACEEXP) && brace_expansion && new_list)
     new_list = brace_expand_word_list (new_list, eflags);
 #endif /* BRACE_EXPANSION */
   /* Perform the `normal' shell expansions: tilde expansion, parameter and
      variable substitution, command substitution, arithmetic expansion,
      and word splitting. */
   new_list = shell_expand_word_list (new_list, eflags);
   /* Okay, we're almost done.  Now let's just do some filename
      globbing. */
   if (new_list)
     {
       if ((eflags & WEXP_PATHEXP) && disallow_filename_globbing == 0)
     /* Glob expand the word list unless globbing has been disabled. */
     new_list = glob_expand_word_list (new_list, eflags);
       else
     /* Dequote the words, because we're not performing globbing. */
     new_list = dequote_list (new_list);
     }
   if ((eflags & WEXP_VARASSIGN) && subst_assign_varlist)
     {
       do_assignment_statements (subst_assign_varlist, (new_list && new_list->word) ? new_list->word->word : (char *)NULL, new_list == 0);
       dispose_words (subst_assign_varlist);
       subst_assign_varlist = (WORD_LIST *)NULL;
     }
   return (new_list);
 }
References copy_word_list(), dequote_list(), disallow_filename_globbing, dispose_words(), do_assignment_statements(), garglist, glob_expand_word_list(), list(), NULL, separate_out_assignments(), shell_expand_word_list(), subst_assign_varlist, tempenv_assign_error, WEXP_BRACEEXP, WEXP_PATHEXP, WEXP_VARASSIGN, word_desc::word, and word_list::word.
Referenced by expand_words(), expand_words_no_vars(), and expand_words_shellexp().
expand_word_unsplit()
WORD_LIST* expand_word_unsplit (WORD_DESC * word, int quoted)
Definition at line 4627 of file subst.c.
 {
   WORD_LIST *result;
   result = expand_word_leave_quoted (word, quoted);
   return (result ? dequote_list (result) : result);
 }
References dequote_list(), and expand_word_leave_quoted().
expand_words()
WORD_LIST* expand_words (WORD_LIST * list)
Definition at line 12277 of file subst.c.
 {
   return (expand_word_list_internal (list, WEXP_ALL));
 }
References expand_word_list_internal(), list(), and WEXP_ALL.
Referenced by execute_simple_command().
expand_words_no_vars()
WORD_LIST* expand_words_no_vars (WORD_LIST * list)
Definition at line 12286 of file subst.c.
 {
   return (expand_word_list_internal (list, WEXP_NOVARS));
 }
References expand_word_list_internal(), list(), and WEXP_NOVARS.
Referenced by execute_for_command(), and redirection_expand().
expand_words_shellexp()
WORD_LIST* expand_words_shellexp (WORD_LIST * list)
Definition at line 12293 of file subst.c.
 {
   return (expand_word_list_internal (list, WEXP_SHELLEXP));
 }
References expand_word_list_internal(), list(), and WEXP_SHELLEXP.
extract_arithmetic_subst()
char* extract_arithmetic_subst (char * string, int * sindex)
Definition at line 1299 of file subst.c.
 {
   return (extract_delimited_string (string, sindex, "$[", "[", "]", 0)); /*]*/
 }
References extract_delimited_string().
Referenced by param_expand().
extract_command_subst()
char* extract_command_subst (char * string, int * sindex, int xflags)
Definition at line 1278 of file subst.c.
 {
   char *ret;
   if (string[*sindex] == LPAREN || (xflags & SX_COMPLETE))
     return (extract_delimited_string (string, sindex, "$(", "(", ")", xflags|SX_COMMAND)); /*)*/
   else
     {
       xflags |= (no_longjmp_on_fatal_error ? SX_NOLONGJMP : 0);
       ret = xparse_dolparen (string, string+*sindex, sindex, xflags);
       return ret;
     }
 }
References extract_delimited_string(), LPAREN, no_longjmp_on_fatal_error, SX_COMMAND, SX_COMPLETE, SX_NOLONGJMP, and xparse_dolparen().
Referenced by extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), param_expand(), skip_double_quoted(), and string_extract_double_quoted().
extract_delimited_string()
static char* extract_delimited_string (char * string, int * sindex, char * opener, char * alt_opener, char * closer, int flags) static
Definition at line 1359 of file subst.c.
 {
   int i, c, si;
   size_t slen;
   char *t, *result;
   int pass_character, nesting_level, in_comment;
   int len_closer, len_opener, len_alt_opener;
   DECLARE_MBSTATE;
   slen = strlen (string + *sindex) + *sindex;
   len_opener = STRLEN (opener);
   len_alt_opener = STRLEN (alt_opener);
   len_closer = STRLEN (closer);
   pass_character = in_comment = 0;
   nesting_level = 1;
   i = *sindex;
   while (nesting_level)
     {
       c = string[i];
       /* If a recursive call or a call to ADVANCE_CHAR leaves the index beyond
      the end of the string, catch it and cut the loop. */
       if (i > slen)
     {
       i = slen;
       c = string[i = slen];
       break;
     }
       if (c == 0)
     break;
       if (in_comment)
     {
       if (c == '\n')
         in_comment = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       if (pass_character)   /* previous char was backslash */
     {
       pass_character = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       /* Not exactly right yet; should handle shell metacharacters and
      multibyte characters, too.  See COMMENT_BEGIN define in parse.y */
       if ((flags & SX_COMMAND) && c == '#' && (i == 0 || string[i - 1] == '\n' || shellblank (string[i - 1])))
     {
           in_comment = 1;
           ADVANCE_CHAR (string, slen, i);
           continue;
     }
       if (c == CTLESC || c == '\\')
     {
       pass_character++;
       i++;
       continue;
     }
       /* Process a nested command substitution, but only if we're parsing an
      arithmetic substitution. */
       if ((flags & SX_COMMAND) && string[i] == '$' && string[i+1] == LPAREN)
         {
           si = i + 2;
           t = extract_command_subst (string, &si, flags|SX_NOALLOC);
           CHECK_STRING_OVERRUN (i, si, slen, c);
           i = si + 1;
           continue;
         }
       /* Process a nested OPENER. */
       if (STREQN (string + i, opener, len_opener))
     {
       si = i + len_opener;
       t = extract_delimited_string (string, &si, opener, alt_opener, closer, flags|SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
       /* Process a nested ALT_OPENER */
       if (len_alt_opener && STREQN (string + i, alt_opener, len_alt_opener))
     {
       si = i + len_alt_opener;
       t = extract_delimited_string (string, &si, alt_opener, alt_opener, closer, flags|SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
       /* If the current substring terminates the delimited string, decrement
      the nesting level. */
       if (STREQN (string + i, closer, len_closer))
     {
       i += len_closer - 1;  /* move to last byte of the closer */
       nesting_level--;
       if (nesting_level == 0)
         break;
     }
       /* Pass old-style command substitution through verbatim. */
       if (c == '`')
     {
       si = i + 1;
       t = string_extract (string, &si, "`", flags|SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
       /* Pass single-quoted and double-quoted strings through verbatim. */
       if (c == '\'' || c == '"')
     {
       si = i + 1;
       i = (c == '\'') ? skip_single_quoted (string, slen, si, 0)
               : skip_double_quoted (string, slen, si, 0);
       continue;
     }
       /* move past this character, which was not special. */
       ADVANCE_CHAR (string, slen, i);
     }
   if (c == 0 && nesting_level)
     {
       if (no_longjmp_on_fatal_error == 0)
     {
       last_command_exit_value = EXECUTION_FAILURE;
       report_error (_("bad substitution: no closing `%s' in %s"), closer, string);
       exp_jump_to_top_level (DISCARD);
     }
       else
     {
       *sindex = i;
       return (char *)NULL;
     }
     }
   si = i - *sindex - len_closer + 1;
   if (flags & SX_NOALLOC)
     result = (char *)NULL;
   else
     {
       result = (char *)xmalloc (1 + si);
       strncpy (result, string + *sindex, si);
       result[si] = '\0';
     }
   *sindex = i;
   return (result);
 }
References _, ADVANCE_CHAR, c, CHECK_STRING_OVERRUN, CTLESC, DECLARE_MBSTATE, DISCARD, EXECUTION_FAILURE, exp_jump_to_top_level(), extract_command_subst(), flags, i, last_command_exit_value, LPAREN, no_longjmp_on_fatal_error, NULL, report_error(), shellblank, skip_double_quoted(), skip_single_quoted(), STREQN, string_extract(), strlen(), STRLEN, strncpy(), SX_COMMAND, SX_NOALLOC, t, and xmalloc.
Referenced by extract_arithmetic_subst(), extract_command_subst(), skip_matched_pair(), and skip_to_delim().
extract_dollar_brace_string()
static char* extract_dollar_brace_string (char * string, int * sindex, int quoted, int flags) static
Definition at line 1813 of file subst.c.
 {
   register int i, c;
   size_t slen;
   int pass_character, nesting_level, si, dolbrace_state;
   char *result, *t;
   DECLARE_MBSTATE;
   /* The handling of dolbrace_state needs to agree with the code in parse.y:
      parse_matched_pair().  The different initial value is to handle the
      case where this function is called to parse the word in
      ${param op word} (SX_WORD). */
   dolbrace_state = (flags & SX_WORD) ? DOLBRACE_WORD : DOLBRACE_PARAM;
   if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && (flags & SX_POSIXEXP))
     dolbrace_state = DOLBRACE_QUOTE;
   if (quoted == Q_HERE_DOCUMENT && dolbrace_state == DOLBRACE_QUOTE && (flags & SX_NOALLOC) == 0)
     return (extract_heredoc_dolbrace_string (string, sindex, quoted, flags));
   dbstate[0] = dolbrace_state;
   pass_character = 0;
   nesting_level = 1;
   slen = strlen (string + *sindex) + *sindex;
   i = *sindex;
   while (c = string[i])
     {
       if (pass_character)
     {
       pass_character = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       /* CTLESCs and backslashes quote the next character. */
       if (c == CTLESC || c == '\\')
     {
       pass_character++;
       i++;
       continue;
     }
       if (string[i] == '$' && string[i+1] == LBRACE)
     {
       if (nesting_level < PARAMEXPNEST_MAX)
         dbstate[nesting_level] = dolbrace_state;
       nesting_level++;
       i += 2;
       if (dolbrace_state == DOLBRACE_QUOTE || dolbrace_state == DOLBRACE_WORD)
         dolbrace_state = DOLBRACE_PARAM;
       continue;
     }
       if (c == RBRACE)
     {
       nesting_level--;
       if (nesting_level == 0)
         break;
       dolbrace_state = (nesting_level < PARAMEXPNEST_MAX) ? dbstate[nesting_level] : dbstate[0];    /* Guess using initial state */
       i++;
       continue;
     }
       /* Pass the contents of old-style command substitutions through
      verbatim. */
       if (c == '`')
     {
       si = i + 1;
       t = string_extract (string, &si, "`", flags|SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
       /* Pass the contents of new-style command substitutions and
      arithmetic substitutions through verbatim. */
       if (string[i] == '$' && string[i+1] == LPAREN)
     {
       si = i + 2;
       t = extract_command_subst (string, &si, flags|SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
 #if defined (PROCESS_SUBSTITUTION)
       /* Technically this should only work at the start of a word */
       if ((string[i] == '<' || string[i] == '>') && string[i+1] == LPAREN)
     {
       si = i + 2;
       t = extract_process_subst (string, (string[i] == '<' ? "<(" : ">)"), &si, flags|SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
 #endif
       /* Pass the contents of double-quoted strings through verbatim. */
       if (c == '"')
     {
       si = i + 1;
       i = skip_double_quoted (string, slen, si, 0);
       /* skip_XXX_quoted leaves index one past close quote */
       continue;
     }
       if (c == '\'')
     {
 /*itrace("extract_dollar_brace_string: c == single quote flags = %d quoted = %d dolbrace_state = %d", flags, quoted, dolbrace_state);*/
       if (posixly_correct && shell_compatibility_level > 42 && dolbrace_state != DOLBRACE_QUOTE && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
         ADVANCE_CHAR (string, slen, i);
       else
         {
           si = i + 1;
           i = skip_single_quoted (string, slen, si, 0);
         }
           continue;
     }
 #if defined (ARRAY_VARS)
       if (c == LBRACK && dolbrace_state == DOLBRACE_PARAM)
     {
       si = skipsubscript (string, i, 0);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       if (string[si] == RBRACK)
         c = string[i = si];
     }
 #endif
       /* move past this character, which was not special. */
       ADVANCE_CHAR (string, slen, i);
       /* This logic must agree with parse.y:parse_matched_pair, since they
      share the same defines. */
       if (dolbrace_state == DOLBRACE_PARAM && c == '%' && (i - *sindex) > 1)
     dolbrace_state = DOLBRACE_QUOTE;
       else if (dolbrace_state == DOLBRACE_PARAM && c == '#' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       else if (dolbrace_state == DOLBRACE_PARAM && c == '/' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE2;   /* XXX */
       else if (dolbrace_state == DOLBRACE_PARAM && c == '^' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       else if (dolbrace_state == DOLBRACE_PARAM && c == ',' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       /* This is intended to handle all of the [:]op expansions and the substring/
      length/pattern removal/pattern substitution expansions. */
       else if (dolbrace_state == DOLBRACE_PARAM && strchr ("#%^,~:-=?+/", c) != 0)
     dolbrace_state = DOLBRACE_OP;
       else if (dolbrace_state == DOLBRACE_OP && strchr ("#%^,~:-=?+/", c) == 0)
     dolbrace_state = DOLBRACE_WORD;
     }
   if (c == 0 && nesting_level)
     {
       if (no_longjmp_on_fatal_error == 0)
     {           /* { */
       last_command_exit_value = EXECUTION_FAILURE;
       report_error (_("bad substitution: no closing `%s' in %s"), "}", string);
       exp_jump_to_top_level (DISCARD);
     }
       else
     {
       *sindex = i;
       return ((char *)NULL);
     }
     }
   result = (flags & SX_NOALLOC) ? (char *)NULL : substring (string, *sindex, i);
   *sindex = i;
   return (result);
 }
References _, ADVANCE_CHAR, c, CHECK_STRING_OVERRUN, CTLESC, dbstate, DECLARE_MBSTATE, DISCARD, DOLBRACE_OP, DOLBRACE_PARAM, DOLBRACE_QUOTE, DOLBRACE_QUOTE2, DOLBRACE_WORD, EXECUTION_FAILURE, exp_jump_to_top_level(), extract_command_subst(), extract_heredoc_dolbrace_string(), flags, i, last_command_exit_value, LBRACE, LBRACK, LPAREN, no_longjmp_on_fatal_error, NULL, PARAMEXPNEST_MAX, posixly_correct, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, RBRACE, RBRACK, report_error(), shell_compatibility_level, skip_double_quoted(), skip_single_quoted(), strchr(), string_extract(), strlen(), substring(), SX_NOALLOC, SX_POSIXEXP, SX_WORD, and t.
Referenced by parameter_brace_expand(), skip_double_quoted(), skip_matched_pair(), skip_to_delim(), and string_extract_double_quoted().
extract_heredoc_dolbrace_string()
static char* extract_heredoc_dolbrace_string (char * string, int * sindex, int quoted, int flags) static
Definition at line 1531 of file subst.c.
 {
   register int i, c;
   size_t slen, tlen, result_index, result_size;
   int pass_character, nesting_level, si, dolbrace_state;
   char *result, *t, *send;
   DECLARE_MBSTATE;
   pass_character = 0;
   nesting_level = 1;
   slen = strlen (string + *sindex) + *sindex;
   send = string + slen;
   result_size = slen;
   result_index = 0;
   result = xmalloc (result_size + 1);
   /* This function isn't called if this condition is not true initially. */
   dolbrace_state = DOLBRACE_QUOTE;
   i = *sindex;
   while (c = string[i])
     {
       if (pass_character)
     {
       pass_character = 0;
       RESIZE_MALLOCED_BUFFER (result, result_index, locale_mb_cur_max + 1, result_size, 64);
       COPY_CHAR_I (result, result_index, string, send, i);
       continue;
     }
       /* CTLESCs and backslashes quote the next character. */
       if (c == CTLESC || c == '\\')
     {
       pass_character++;
       RESIZE_MALLOCED_BUFFER (result, result_index, 2, result_size, 64);
       result[result_index++] = c;
       i++;
       continue;
     }
       /* The entire reason we have this separate function right here. */
       if (c == '$' && string[i+1] == '\'')
     {
       char *ttrans;
       int ttranslen;
       if ((posixly_correct || extended_quote == 0) && dolbrace_state != DOLBRACE_QUOTE && dolbrace_state != DOLBRACE_QUOTE2)
         {
           RESIZE_MALLOCED_BUFFER (result, result_index, 3, result_size, 64);
           result[result_index++] = '$';
           result[result_index++] = '\'';
           i += 2;
           continue;
         }
       si = i + 2;
       t = string_extract_single_quoted (string, &si, 1);    /* XXX */
       CHECK_STRING_OVERRUN (i, si, slen, c);
       tlen = si - i - 2;    /* -2 since si is one after the close quote */
       ttrans = ansiexpand (t, 0, tlen, &ttranslen);
       free (t);
       /* needed to correctly quote any embedded single quotes. */
       if (dolbrace_state == DOLBRACE_QUOTE || dolbrace_state == DOLBRACE_QUOTE2)
         {
           t = sh_single_quote (ttrans);
           tlen = strlen (t);
           free (ttrans);
         }
       else if (extended_quote) /* dolbrace_state == DOLBRACE_PARAM */
         {
           /* This matches what parse.y:parse_matched_pair() does */
           t = ttrans;
           tlen = strlen (t);
         }
       RESIZE_MALLOCED_BUFFER (result, result_index, tlen + 1, result_size, 64);
       strncpy (result + result_index, t, tlen);
       result_index += tlen;
       free (t);
       i = si;
       continue;
     }
 #if defined (TRANSLATABLE_STRINGS)
       if (c == '$' && string[i+1] == '"')
     {
       char *ttrans;
       int ttranslen;
       si = i + 2;
       t = string_extract_double_quoted (string, &si, flags);    /* XXX */
       CHECK_STRING_OVERRUN (i, si, slen, c);
       tlen = si - i - 2;    /* -2 since si is one after the close quote */
       ttrans = locale_expand (t, 0, tlen, line_number, &ttranslen);
       free (t);
       t = singlequote_translations ? sh_single_quote (ttrans) : sh_mkdoublequoted (ttrans, ttranslen, 0);
       tlen = strlen (t);
       free (ttrans);
       RESIZE_MALLOCED_BUFFER (result, result_index, tlen + 1, result_size, 64);
       strncpy (result + result_index, t, tlen);
       result_index += tlen;
       free (t);
       i = si;
       continue;
     }
 #endif /* TRANSLATABLE_STRINGS */
       if (c == '$' && string[i+1] == LBRACE)
     {
       nesting_level++;
       RESIZE_MALLOCED_BUFFER (result, result_index, 3, result_size, 64);
       result[result_index++] = c;
       result[result_index++] = string[i+1];
       i += 2;
       if (dolbrace_state == DOLBRACE_QUOTE || dolbrace_state == DOLBRACE_QUOTE2 || dolbrace_state == DOLBRACE_WORD)
         dolbrace_state = DOLBRACE_PARAM;
       continue;
     }
       if (c == RBRACE)
     {
       nesting_level--;
       if (nesting_level == 0)
         break;
       RESIZE_MALLOCED_BUFFER (result, result_index, 2, result_size, 64);
       result[result_index++] = c;
       i++;
       continue;
     }
       /* Pass the contents of old-style command substitutions through
      verbatim. */
       if (c == '`')
     {
       si = i + 1;
       t = string_extract (string, &si, "`", flags); /* already know (flags & SX_NOALLOC) == 0) */
       CHECK_STRING_OVERRUN (i, si, slen, c);
       tlen = si - i - 1;
       RESIZE_MALLOCED_BUFFER (result, result_index, tlen + 3, result_size, 64);
       result[result_index++] = c;
       strncpy (result + result_index, t, tlen);
       result_index += tlen;
       result[result_index++] = string[si];
       free (t);
       i = si + 1;
       continue;
     }
       /* Pass the contents of new-style command substitutions and
      arithmetic substitutions through verbatim. */
       if (string[i] == '$' && string[i+1] == LPAREN)
     {
       si = i + 2;
       t = extract_command_subst (string, &si, flags);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       tlen = si - i - 1;
       RESIZE_MALLOCED_BUFFER (result, result_index, tlen + 4, result_size, 64);
       result[result_index++] = c;
       result[result_index++] = LPAREN;
       strncpy (result + result_index, t, tlen);
       result_index += tlen;
       result[result_index++] = string[si];
       free (t);
       i = si + 1;
       continue;
     }
 #if defined (PROCESS_SUBSTITUTION)
       /* Technically this should only work at the start of a word */
       if ((string[i] == '<' || string[i] == '>') && string[i+1] == LPAREN)
     {
       si = i + 2;
       t = extract_process_subst (string, (string[i] == '<' ? "<(" : ">)"), &si, flags);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       tlen = si - i - 1;
       RESIZE_MALLOCED_BUFFER (result, result_index, tlen + 4, result_size, 64);
       result[result_index++] = c;
       result[result_index++] = LPAREN;
       strncpy (result + result_index, t, tlen);
       result_index += tlen;
       result[result_index++] = string[si];
       free (t);
       i = si + 1;
       continue;
     }
 #endif
       if (c == '\'' && posixly_correct && shell_compatibility_level > 42 && dolbrace_state != DOLBRACE_QUOTE)
     {
       COPY_CHAR_I (result, result_index, string, send, i);
       continue;
     }
       /* Pass the contents of single and double-quoted strings through verbatim. */
       if (c == '"' || c == '\'')
     {
       si = i + 1;
       if (c == '"')
         t = string_extract_double_quoted (string, &si, flags);
       else
         t = string_extract_single_quoted (string, &si, 0);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       tlen = si - i - 2;    /* -2 since si is one after the close quote */
       RESIZE_MALLOCED_BUFFER (result, result_index, tlen + 3, result_size, 64);
       result[result_index++] = c;
       strncpy (result + result_index, t, tlen);
       result_index += tlen;
       result[result_index++] = string[si - 1];
       free (t);
       i = si;
       continue;
     }
       /* copy this character, which was not special. */
       COPY_CHAR_I (result, result_index, string, send, i);
       /* This logic must agree with parse.y:parse_matched_pair, since they
      share the same defines. */
       if (dolbrace_state == DOLBRACE_PARAM && c == '%' && (i - *sindex) > 1)
     dolbrace_state = DOLBRACE_QUOTE;
       else if (dolbrace_state == DOLBRACE_PARAM && c == '#' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       else if (dolbrace_state == DOLBRACE_PARAM && c == '/' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE2;   /* XXX */
       else if (dolbrace_state == DOLBRACE_PARAM && c == '^' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       else if (dolbrace_state == DOLBRACE_PARAM && c == ',' && (i - *sindex) > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       /* This is intended to handle all of the [:]op expansions and the substring/
      length/pattern removal/pattern substitution expansions. */
       else if (dolbrace_state == DOLBRACE_PARAM && strchr ("#%^,~:-=?+/", c) != 0)
     dolbrace_state = DOLBRACE_OP;
       else if (dolbrace_state == DOLBRACE_OP && strchr ("#%^,~:-=?+/", c) == 0)
     dolbrace_state = DOLBRACE_WORD;
     }
   if (c == 0 && nesting_level)
     {
       free (result);
       if (no_longjmp_on_fatal_error == 0)
     {           /* { */
       last_command_exit_value = EXECUTION_FAILURE;
       report_error (_("bad substitution: no closing `%s' in %s"), "}", string);
       exp_jump_to_top_level (DISCARD);
     }
       else
     {
       *sindex = i;
       return ((char *)NULL);
     }
     }
   *sindex = i;
   result[result_index] = '\0';
   return (result);
 }
References _, ansiexpand(), c, CHECK_STRING_OVERRUN, COPY_CHAR_I, CTLESC, DECLARE_MBSTATE, DISCARD, DOLBRACE_OP, DOLBRACE_PARAM, DOLBRACE_QUOTE, DOLBRACE_QUOTE2, DOLBRACE_WORD, EXECUTION_FAILURE, exp_jump_to_top_level(), extended_quote, extract_command_subst(), flags, free, i, last_command_exit_value, LBRACE, line_number, locale_mb_cur_max, LPAREN, no_longjmp_on_fatal_error, NULL, posixly_correct, RBRACE, report_error(), RESIZE_MALLOCED_BUFFER, send(), sh_mkdoublequoted(), sh_single_quote(), shell_compatibility_level, singlequote_translations, strchr(), string_extract(), string_extract_double_quoted(), string_extract_single_quoted(), strlen(), strncpy(), t, and xmalloc.
Referenced by extract_dollar_brace_string().
get_dollar_var_value()
char* get_dollar_var_value (intmax_t ind)
Definition at line 3725 of file subst.c.
 {
   char *temp;
   WORD_LIST *p;
   if (ind < 10)
     temp = dollar_vars[ind] ? savestring (dollar_vars[ind]) : (char *)NULL;
   else  /* We want something like ${11} */
     {
       ind -= 10;
       for (p = rest_of_args; p && ind--; p = p->next)
     ;
       temp = p ? savestring (p->word->word) : (char *)NULL;
     }
   return (temp);
 }
References dollar_vars, NULL, p, rest_of_args, and savestring().
Referenced by parameter_brace_expand_length(), and parameter_brace_expand_word().
get_var_and_type()
static int get_var_and_type (char * varname, char * value, array_eltstate_t * estatep, int quoted, int flags, SHELL_VAR ** varp, char ** valp) static
Definition at line 8250 of file subst.c.
 {
   int vtype, want_indir;
   char *temp, *vname;
   SHELL_VAR *v;
   want_indir = *varname == '!' &&
     (legal_variable_starter ((unsigned char)varname[1]) || DIGIT (varname[1])
                     || VALID_INDIR_PARAM (varname[1]));
   if (want_indir)
     vname = parameter_brace_find_indir (varname+1, SPECIAL_VAR (varname, 1), quoted, 1);
     /* XXX - what if vname == 0 || *vname == 0 ? */
   else
     vname = varname;
   if (vname == 0)
     {
       vtype = VT_VARIABLE;
       *varp = (SHELL_VAR *)NULL;
       *valp = (char *)NULL;
       return (vtype);
     }
   /* This sets vtype to VT_VARIABLE or VT_POSPARMS */
   vtype = STR_DOLLAR_AT_STAR (vname);
   if (vtype == VT_POSPARMS && vname[0] == '*')
     vtype |= VT_STARSUB;
   *varp = (SHELL_VAR *)NULL;
 #if defined (ARRAY_VARS)
   if (valid_array_reference (vname, 0))
     {
       v = array_variable_part (vname, 0, &temp, (int *)0);
       /* If we want to signal array_value to use an already-computed index,
      the caller will set ESTATEP->IND to that index and pass AV_USEIND in
      FLAGS. */
       if (estatep && (flags & AV_USEIND) == 0)
     estatep->ind = INTMAX_MIN;
       if (v && invisible_p (v))
     {
       vtype = VT_ARRAYMEMBER;
       *varp = (SHELL_VAR *)NULL;
       *valp = (char *)NULL;
     }
       if (v && (array_p (v) || assoc_p (v)))
     {
       if (ALL_ELEMENT_SUB (temp[0]) && temp[1] == RBRACK)
         {
           /* Callers have to differentiate between indexed and associative */
           vtype = VT_ARRAYVAR;
           if (temp[0] == '*')
         vtype |= VT_STARSUB;
           *valp = array_p (v) ? (char *)array_cell (v) : (char *)assoc_cell (v);
         }
       else
         {
           vtype = VT_ARRAYMEMBER;
           *valp = array_value (vname, Q_DOUBLE_QUOTES, flags, estatep);
         }
       *varp = v;
     }
       else if (v && (ALL_ELEMENT_SUB (temp[0]) && temp[1] == RBRACK))
     {
       vtype = VT_VARIABLE;
       *varp = v;
       if (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT))
         *valp = value ? dequote_string (value) : (char *)NULL;
       else
         *valp = value ? dequote_escapes (value) : (char *)NULL;
     }
       else
     {
       vtype = VT_ARRAYMEMBER;
       *varp = v;
       *valp = array_value (vname, Q_DOUBLE_QUOTES, flags, estatep);
     }
     }
   else if ((v = find_variable (vname)) && (invisible_p (v) == 0) && (assoc_p (v) || array_p (v)))
     {
       vtype = VT_ARRAYMEMBER;
       *varp = v;
       *valp = assoc_p (v) ? assoc_reference (assoc_cell (v), "0") : array_reference (array_cell (v), 0);
     }
   else
 #endif
     {
       if (value && vtype == VT_VARIABLE)
     {
       *varp = find_variable (vname);
       if (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT))
         *valp = dequote_string (value);
       else
         *valp = dequote_escapes (value);
     }
       else
     *valp = value;
     }
   if (want_indir)
     free (vname);
   return vtype;
 }
References ALL_ELEMENT_SUB, array_cell, array_p, assoc_cell, assoc_p, AV_USEIND, dequote_escapes(), dequote_string(), DIGIT, find_variable(), flags, free, element_state::ind, INTMAX_MIN, invisible_p, legal_variable_starter, NULL, parameter_brace_find_indir(), Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, RBRACK, SPECIAL_VAR, STR_DOLLAR_AT_STAR, VALID_INDIR_PARAM, value, VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, VT_STARSUB, and VT_VARIABLE.
Referenced by parameter_brace_casemod(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), and parameter_brace_transform().
get_word_from_string()
char* get_word_from_string (char ** stringp, char * separators, char ** endptr)
Definition at line 3283 of file subst.c.
 {
   register char *s;
   char *current_word;
   int sindex, sh_style_split, whitesep, xflags;
   unsigned char local_cmap[UCHAR_MAX+1];    /* really only need single-byte chars here */
   size_t slen;
   if (!stringp || !*stringp || !**stringp)
     return ((char *)NULL);
   sh_style_split = separators && separators[0] == ' ' &&
                  separators[1] == '\t' &&
                  separators[2] == '\n' &&
                  separators[3] == '\0';
   memset (local_cmap, '\0', sizeof (local_cmap));
   for (xflags = 0, s = separators; s && *s; s++)
     {
       if (*s == CTLESC) xflags |= SX_NOCTLESC;
       if (*s == CTLNUL) xflags |= SX_NOESCCTLNUL;
       local_cmap[(unsigned char)*s] = 1;    /* local charmap of separators */
     }
   s = *stringp;
   slen = 0;
   /* Remove sequences of whitespace at the beginning of STRING, as
      long as those characters appear in SEPARATORS.  This happens if
      SEPARATORS == $' \t\n' or if IFS is unset. */
   if (sh_style_split || separators == 0)
     for (; *s && spctabnl (*s) && islocalsep (*s); s++);
   else
     for (; *s && ifs_whitespace (*s) && islocalsep (*s); s++);
   /* If the string is nothing but whitespace, update it and return. */
   if (!*s)
     {
       *stringp = s;
       if (endptr)
     *endptr = s;
       return ((char *)NULL);
     }
   /* OK, S points to a word that does not begin with white space.
      Now extract a word, stopping at a separator, save a pointer to
      the first character after the word, then skip sequences of spc,
      tab, or nl as long as they are separators.
      This obeys the field splitting rules in Posix.2. */
   sindex = 0;
   /* Don't need string length in ADVANCE_CHAR unless multibyte chars are
      possible, but need it in string_extract_verbatim for bounds checking */
   slen = STRLEN (s);
   current_word = string_extract_verbatim (s, slen, &sindex, separators, xflags);
   /* Set ENDPTR to the first character after the end of the word. */
   if (endptr)
     *endptr = s + sindex;
   /* Note whether or not the separator is IFS whitespace, used later. */
   whitesep = s[sindex] && ifs_whitesep (s[sindex]);
   /* Move past the current separator character. */
   if (s[sindex])
     {
       DECLARE_MBSTATE;
       ADVANCE_CHAR (s, slen, sindex);
     }
   /* Now skip sequences of space, tab, or newline characters if they are
      in the list of separators. */
   while (s[sindex] && spctabnl (s[sindex]) && islocalsep (s[sindex]))
     sindex++;
   /* If the first separator was IFS whitespace and the current character is
      a non-whitespace IFS character, it should be part of the current field
      delimiter, not a separate delimiter that would result in an empty field.
      Look at POSIX.2, 3.6.5, (3)(b). */
   if (s[sindex] && whitesep && islocalsep (s[sindex]) && !ifs_whitesep (s[sindex]))
     {
       sindex++;
       /* An IFS character that is not IFS white space, along with any adjacent
      IFS white space, shall delimit a field. */
       while (s[sindex] && ifs_whitesep (s[sindex]) && islocalsep(s[sindex]))
     sindex++;
     }
   /* Update STRING to point to the next field. */
   *stringp = s + sindex;
   return (current_word);
 }
References ADVANCE_CHAR, CTLESC, CTLNUL, DECLARE_MBSTATE, ifs_whitesep, ifs_whitespace, islocalsep, memset, NULL, s, separators, spctabnl, string_extract_verbatim(), STRLEN, SX_NOCTLESC, SX_NOESCCTLNUL, and UCHAR_MAX.
getifs()
char* getifs ()
Definition at line 12058 of file subst.c.
 {
   return ifs_value;
 }
References ifs_value.
getpatspec()
static int getpatspec (int c, char * value) static
Definition at line 5709 of file subst.c.
 {
   if (c == '#')
     return ((*value == '#') ? RP_LONG_LEFT : RP_SHORT_LEFT);
   else  /* c == '%' */
     return ((*value == '%') ? RP_LONG_RIGHT : RP_SHORT_RIGHT);
 }
References c, RP_LONG_LEFT, RP_LONG_RIGHT, RP_SHORT_LEFT, RP_SHORT_RIGHT, and value.
Referenced by parameter_brace_remove_pattern().
getpattern()
static char* getpattern (char * value, int quoted, int expandpat) static
Definition at line 5728 of file subst.c.
 {
   char *pat, *tword;
   WORD_LIST *l;
 #if 0
   int i;
 #endif
   /* There is a problem here:  how to handle single or double quotes in the
      pattern string when the whole expression is between double quotes?
      POSIX.2 says that enclosing double quotes do not cause the pattern to
      be quoted, but does that leave us a problem with @ and array[@] and their
      expansions inside a pattern? */
 #if 0
   if (expandpat && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && *tword)
     {
       i = 0;
       pat = string_extract_double_quoted (tword, &i, SX_STRIPDQ);
       free (tword);
       tword = pat;
     }
 #endif
   /* expand_string_for_pat () leaves WORD quoted and does not perform
      word splitting. */
   l = *value ? expand_string_for_pat (value,
                       (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) ? Q_PATQUOTE : quoted,
                       (int *)NULL, (int *)NULL)
          : (WORD_LIST *)0;
   if (l)
     word_list_remove_quoted_nulls (l);
   pat = string_list (l);
   dispose_words (l);
   if (pat)
     {
       tword = quote_string_for_globbing (pat, QGLOB_CVTNULL);
       free (pat);
       pat = tword;
     }
   return (pat);
 }
References dispose_words(), expand_string_for_pat(), free, i, l, NULL, pat, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, Q_PATQUOTE, QGLOB_CVTNULL, quote_string_for_globbing(), string_extract_double_quoted(), string_list(), SX_STRIPDQ, value, and word_list_remove_quoted_nulls().
Referenced by parameter_brace_casemod(), parameter_brace_patsub(), and parameter_brace_remove_pattern().
glob_expand_word_list()
static WORD_LIST* glob_expand_word_list (WORD_LIST * tlist, int eflags) static
Definition at line 12300 of file subst.c.
 {
   char **glob_array, *temp_string;
   register int glob_index;
   WORD_LIST *glob_list, *output_list, *disposables, *next;
   WORD_DESC *tword;
   int x;
   output_list = disposables = (WORD_LIST *)NULL;
   glob_array = (char **)NULL;
   while (tlist)
     {
       /* For each word, either globbing is attempted or the word is
      added to orig_list.  If globbing succeeds, the results are
      added to orig_list and the word (tlist) is added to the list
      of disposable words.  If globbing fails and failed glob
      expansions are left unchanged (the shell default), the
      original word is added to orig_list.  If globbing fails and
      failed glob expansions are removed, the original word is
      added to the list of disposable words.  orig_list ends up
      in reverse order and requires a call to REVERSE_LIST to
      be set right.  After all words are examined, the disposable
      words are freed. */
       next = tlist->next;
       /* If the word isn't an assignment and contains an unquoted
      pattern matching character, then glob it. */
       if ((tlist->word->flags & W_NOGLOB) == 0 &&
       unquoted_glob_pattern_p (tlist->word->word))
     {
       glob_array = shell_glob_filename (tlist->word->word, QGLOB_CTLESC);   /* XXX */
       /* Handle error cases.
          I don't think we should report errors like "No such file
          or directory".  However, I would like to report errors
          like "Read failed". */
       if (glob_array == 0 || GLOB_FAILED (glob_array))
         {
           glob_array = (char **)xmalloc (sizeof (char *));
           glob_array[0] = (char *)NULL;
         }
       /* Dequote the current word in case we have to use it. */
       if (glob_array[0] == NULL)
         {
           temp_string = dequote_string (tlist->word->word);
           free (tlist->word->word);
           tlist->word->word = temp_string;
         }
       /* Make the array into a word list. */
       glob_list = (WORD_LIST *)NULL;
       for (glob_index = 0; glob_array[glob_index]; glob_index++)
         {
           tword = make_bare_word (glob_array[glob_index]);
           glob_list = make_word_list (tword, glob_list);
         }
       if (glob_list)
         {
           output_list = (WORD_LIST *)list_append (glob_list, output_list);
           PREPEND_LIST (tlist, disposables);
         }
       else if (fail_glob_expansion != 0)
         {
           last_command_exit_value = EXECUTION_FAILURE;
           report_error (_("no match: %s"), tlist->word->word);
           exp_jump_to_top_level (DISCARD);
         }
       else if (allow_null_glob_expansion == 0)
         {
           /* Failed glob expressions are left unchanged. */
           PREPEND_LIST (tlist, output_list);
         }
       else
         {
           /* Failed glob expressions are removed. */
           PREPEND_LIST (tlist, disposables);
         }
     }
       else
     {
       /* Dequote the string. */
       temp_string = dequote_string (tlist->word->word);
       free (tlist->word->word);
       tlist->word->word = temp_string;
       PREPEND_LIST (tlist, output_list);
     }
       strvec_dispose (glob_array);
       glob_array = (char **)NULL;
       tlist = next;
     }
   if (disposables)
     dispose_words (disposables);
   if (output_list)
     output_list = REVERSE_LIST (output_list, WORD_LIST *);
   return (output_list);
 }
References _, allow_null_glob_expansion, dequote_string(), DISCARD, dispose_words(), EXECUTION_FAILURE, exp_jump_to_top_level(), fail_glob_expansion, word_desc::flags, free, GLOB_FAILED, last_command_exit_value, list_append(), make_bare_word(), make_word_list(), word_list::next, next, NULL, PREPEND_LIST, QGLOB_CTLESC, report_error(), REVERSE_LIST, shell_glob_filename(), strvec_dispose(), unquoted_glob_pattern_p(), W_NOGLOB, word_desc::word, word_list::word, x, and xmalloc.
Referenced by expand_word_list_internal().
ifs_firstchar()
char* ifs_firstchar (int * lenp)
Definition at line 2866 of file subst.c.
 {
   char *ret;
   int len;
   ret = xmalloc (MB_LEN_MAX + 1);
 #if defined (HANDLE_MULTIBYTE)
   if (ifs_firstc_len == 1)
     {
       ret[0] = ifs_firstc[0];
       ret[1] = '\0';
       len = ret[0] ? 1 : 0;
     }
   else
     {
       memcpy (ret, ifs_firstc, ifs_firstc_len);
       ret[len = ifs_firstc_len] = '\0';
     }
 #else
   ret[0] = ifs_firstc;
   ret[1] = '\0';
   len = ret[0] ? 0 : 1;
 #endif
   if (lenp)
     *lenp = len;
   return ret;
 }
References ifs_firstc, len, MB_LEN_MAX, memcpy, and xmalloc.
invalidate_cached_quoted_dollar_at()
void invalidate_cached_quoted_dollar_at ()
Definition at line 10895 of file subst.c.
 {
   dispose_words (cached_quoted_dollar_at);
   cached_quoted_dollar_at = 0;
 }
References cached_quoted_dollar_at, and dispose_words().
Referenced by pop_dollar_vars(), and remember_args().
list_quote_escapes()
static WORD_LIST* list_quote_escapes (WORD_LIST * list) static
Definition at line 4733 of file subst.c.
 {
   register WORD_LIST *w;
   char *t;
   for (w = list; w; w = w->next)
     {
       t = w->word->word;
       w->word->word = quote_escapes (t);
       free (t);
     }
   return list;
 }
References free, list(), quote_escapes(), t, and w.
Referenced by string_list_dollar_at().
list_remove_pattern()
static char* list_remove_pattern (WORD_LIST * list, char * pattern, int patspec, int itype, int quoted) static
Definition at line 5788 of file subst.c.
 {
   WORD_LIST *new, *l;
   WORD_DESC *w;
   char *tword;
   for (new = (WORD_LIST *)NULL, l = list; l; l = l->next)
     {
       tword = remove_pattern (l->word->word, pattern, patspec);
       w = alloc_word_desc ();
       w->word = tword ? tword : savestring ("");
       new = make_word_list (w, new);
     }
   l = REVERSE_LIST (new, WORD_LIST *);
   tword = string_list_pos_params (itype, l, quoted, 0);
   dispose_words (l);
   return (tword);
 }
References alloc_word_desc(), dispose_words(), l, list(), make_word_list(), NULL, pattern, remove_pattern(), REVERSE_LIST, savestring(), string_list_pos_params(), and w.
Referenced by parameter_list_remove_pattern().
list_rest_of_args()
WORD_LIST* list_rest_of_args ()
Definition at line 3708 of file subst.c.
 {
   register WORD_LIST *list, *args;
   int i;
   /* Break out of the loop as soon as one of the dollar variables is null. */
   for (i = 1, list = (WORD_LIST *)NULL; i < 10 && dollar_vars[i]; i++)
     list = make_word_list (make_bare_word (dollar_vars[i]), list);
   for (args = rest_of_args; args; args = args->next)
     list = make_word_list (make_bare_word (args->word->word), list);
   return (REVERSE_LIST (list, WORD_LIST *));
 }
References args, dollar_vars, i, list(), make_bare_word(), make_word_list(), NULL, rest_of_args, and REVERSE_LIST.
Referenced by expand_word_internal(), param_expand(), parameter_list_remove_pattern(), parameter_list_transform(), pos_params(), pos_params_modcase(), pos_params_pat_subst(), save_bash_argv(), and string_rest_of_args().
list_string()
WORD_LIST* list_string (char * string, char * separators, int quoted)
Definition at line 3130 of file subst.c.
 {
   WORD_LIST *result;
   WORD_DESC *t;
   char *current_word, *s;
   int sindex, sh_style_split, whitesep, xflags, free_word;
   size_t slen;
   if (!string || !*string)
     return ((WORD_LIST *)NULL);
   sh_style_split = separators && separators[0] == ' ' &&
                  separators[1] == '\t' &&
                  separators[2] == '\n' &&
                  separators[3] == '\0';
   for (xflags = 0, s = ifs_value; s && *s; s++)
     {
       if (*s == CTLESC) xflags |= SX_NOCTLESC;
       else if (*s == CTLNUL) xflags |= SX_NOESCCTLNUL;
     }
   slen = 0;
   /* Remove sequences of whitespace at the beginning of STRING, as
      long as those characters appear in IFS.  Do not do this if
      STRING is quoted or if there are no separator characters. We use the
      Posix definition of whitespace as a member of the space character
      class in the current locale. */
 #if 0
   if (!quoted || !separators || !*separators)
 #else
   /* issep() requires that separators be non-null, and always returns 0 if
      separator is the empty string, so don't bother if we get an empty string
      for separators. We already returned NULL above if STRING is empty. */
   if (!quoted && separators && *separators)
 #endif
     {
       for (s = string; *s && issep (*s) && ifs_whitespace (*s); s++);
       if (!*s)
     return ((WORD_LIST *)NULL);
       string = s;
     }
   /* OK, now STRING points to a word that does not begin with white space.
      The splitting algorithm is:
     extract a word, stopping at a separator
     skip sequences of whitespace characters as long as they are separators
      This obeys the field splitting rules in Posix.2. */
   slen = STRLEN (string);
   for (result = (WORD_LIST *)NULL, sindex = 0; string[sindex]; )
     {
       /* Don't need string length in ADVANCE_CHAR unless multibyte chars are
      possible, but need it in string_extract_verbatim for bounds checking */
       current_word = string_extract_verbatim (string, slen, &sindex, separators, xflags);
       if (current_word == 0)
     break;
       free_word = 1;    /* If non-zero, we free current_word */
       /* If we have a quoted empty string, add a quoted null argument.  We
      want to preserve the quoted null character iff this is a quoted
      empty string; otherwise the quoted null characters are removed
      below. */
       if (QUOTED_NULL (current_word))
     {
       t = alloc_word_desc ();
       t->word = make_quoted_char ('\0');
       t->flags |= W_QUOTED|W_HASQUOTEDNULL;
       result = make_word_list (t, result);
     }
       else if (current_word[0] != '\0')
     {
       /* If we have something, then add it regardless.  However,
          perform quoted null character removal on the current word. */
       remove_quoted_nulls (current_word);
       /* We don't want to set the word flags based on the string contents
          here -- that's mostly for the parser -- so we just allocate a
          WORD_DESC *, assign current_word (noting that we don't want to
          free it), and skip all of make_word. */
       t = alloc_word_desc ();
       t->word = current_word;
       result = make_word_list (t, result);
       free_word = 0;
       result->word->flags &= ~W_HASQUOTEDNULL;  /* just to be sure */
       if (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT))
         result->word->flags |= W_QUOTED;
       /* If removing quoted null characters leaves an empty word, note
          that we saw this for the caller to act on. */
       if (current_word == 0 || current_word[0] == '\0')
         result->word->flags |= W_SAWQUOTEDNULL;
     }
       /* If we're not doing sequences of separators in the traditional
      Bourne shell style, then add a quoted null argument. */
       else if (!sh_style_split && !ifs_whitespace (string[sindex]))
     {
       t = alloc_word_desc ();
       t->word = make_quoted_char ('\0');
       t->flags |= W_QUOTED|W_HASQUOTEDNULL;
       result = make_word_list (t, result);
     }
       if (free_word)
     free (current_word);
       /* Note whether or not the separator is IFS whitespace, used later. */
       whitesep = string[sindex] && ifs_whitesep (string[sindex]);
       /* Move past the current separator character. */
       if (string[sindex])
     {
       DECLARE_MBSTATE;
       ADVANCE_CHAR (string, slen, sindex);
     }
       /* Now skip sequences of whitespace characters if they are
      in the list of separators. */
       while (string[sindex] && ifs_whitesep (string[sindex]) && issep (string[sindex]))
     sindex++;
       /* If the first separator was IFS whitespace and the current character
      is a non-whitespace IFS character, it should be part of the current
      field delimiter, not a separate delimiter that would result in an
      empty field.  Look at POSIX.2, 3.6.5, (3)(b). */
       if (string[sindex] && whitesep && issep (string[sindex]) && !ifs_whitesep (string[sindex]))
     {
       sindex++;
       /* An IFS character that is not IFS white space, along with any
          adjacent IFS white space, shall delimit a field. (SUSv3) */
       while (string[sindex] && ifs_whitesep (string[sindex]) && isifs (string[sindex]))
         sindex++;
     }
     }
   return (REVERSE_LIST (result, WORD_LIST *));
 }
References ADVANCE_CHAR, alloc_word_desc(), CTLESC, CTLNUL, DECLARE_MBSTATE, word_desc::flags, free, ifs_value, ifs_whitesep, ifs_whitespace, isifs, issep, make_quoted_char(), make_word_list(), NULL, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, QUOTED_NULL, remove_quoted_nulls(), REVERSE_LIST, s, separators, string_extract_verbatim(), STRLEN, SX_NOCTLESC, SX_NOESCCTLNUL, t, W_HASQUOTEDNULL, W_QUOTED, W_SAWQUOTEDNULL, and word_list::word.
Referenced by expand_word_internal(), and word_split().
list_transform()
static char* list_transform (int xc, SHELL_VAR * v, WORD_LIST * list, int itype, int quoted) static
Definition at line 8512 of file subst.c.
 {
   WORD_LIST *new, *l;
   WORD_DESC *w;
   char *tword;
   int qflags;
   for (new = (WORD_LIST *)NULL, l = list; l; l = l->next)
     {
       tword = string_transform (xc, v, l->word->word);
       w = alloc_word_desc ();
       w->word = tword ? tword : savestring ("");    /* XXX */
       new = make_word_list (w, new);
     }
   l = REVERSE_LIST (new, WORD_LIST *);
   qflags = quoted;
   /* If we are expanding in a context where word splitting will not be
      performed, treat as quoted.  This changes how $* will be expanded. */
   if (itype == '*' && expand_no_split_dollar_star && ifs_is_null)
     qflags |= Q_DOUBLE_QUOTES;      /* Posix interp 888 */
   tword = string_list_pos_params (itype, l, qflags, 0);
   dispose_words (l);
   return (tword);
 }
References alloc_word_desc(), dispose_words(), expand_no_split_dollar_star, ifs_is_null, l, list(), make_word_list(), NULL, Q_DOUBLE_QUOTES, REVERSE_LIST, savestring(), string_list_pos_params(), string_transform(), and w.
Referenced by parameter_list_transform(), and pos_params_assignment().
make_quoted_char()
static char* make_quoted_char (int c) static
Definition at line 4820 of file subst.c.
 {
   char *temp;
   temp = (char *)xmalloc (3);
   if (c == 0)
     {
       temp[0] = CTLNUL;
       temp[1] = '\0';
     }
   else
     {
       temp[0] = CTLESC;
       temp[1] = c;
       temp[2] = '\0';
     }
   return (temp);
 }
References c, CTLESC, CTLNUL, and xmalloc.
Referenced by list_string(), and parameter_brace_expand_rhs().
match_pattern()
static int match_pattern (char * string, char * pat, int mtype, char ** sp, char ** ep) static
Definition at line 5665 of file subst.c.
 {
 #if defined (HANDLE_MULTIBYTE)
   int ret;
   size_t n;
   wchar_t *wstring, *wpat;
   char **indices;
 #endif
   if (string == 0 || pat == 0 || *pat == 0)
     return (0);
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1)
     {
       if (mbsmbchar (string) == 0 && mbsmbchar (pat) == 0)
         return (match_upattern (string, pat, mtype, sp, ep));
       n = xdupmbstowcs (&wpat, NULL, pat);
       if (n == (size_t)-1)
     return (match_upattern (string, pat, mtype, sp, ep));
       n = xdupmbstowcs (&wstring, &indices, string);
       if (n == (size_t)-1)
     {
       free (wpat);
       return (match_upattern (string, pat, mtype, sp, ep));
     }
       ret = match_wpattern (wstring, indices, n, wpat, mtype, sp, ep);
       free (wpat);
       free (wstring);
       free (indices);
       return (ret);
     }
   else
 #endif
     return (match_upattern (string, pat, mtype, sp, ep));
 }
References free, match_upattern(), MB_CUR_MAX, n, NULL, pat, and sp.
Referenced by pat_subst().
match_upattern()
static int match_upattern (char * string, char * pat, int mtype, char ** sp, char ** ep) static
Definition at line 5362 of file subst.c.
 {
   int c, mlen;
   size_t len;
   register char *p, *p1, *npat;
   char *end;
   /* If the pattern doesn't match anywhere in the string, go ahead and
      short-circuit right away.  A minor optimization, saves a bunch of
      unnecessary calls to strmatch (up to N calls for a string of N
      characters) if the match is unsuccessful.  To preserve the semantics
      of the substring matches below, we make sure that the pattern has
      `*' as first and last character, making a new pattern if necessary. */
   /* XXX - check this later if I ever implement `**' with special meaning,
      since this will potentially result in `**' at the beginning or end */
   len = STRLEN (pat);
   if (pat[0] != '*' || (pat[0] == '*' && pat[1] == LPAREN && extended_glob) || pat[len - 1] != '*')
     {
       int unescaped_backslash;
       char *pp;
       p = npat = (char *)xmalloc (len + 3);
       p1 = pat;
       if ((mtype != MATCH_BEG) && (*p1 != '*' || (*p1 == '*' && p1[1] == LPAREN && extended_glob)))
     *p++ = '*';
       while (*p1)
     *p++ = *p1++;
 #if 1
       /* Need to also handle a pattern that ends with an unescaped backslash.
      For right now, we ignore it because the pattern matching code will
      fail the match anyway */
       /* If the pattern ends with a `*' we leave it alone if it's preceded by
      an even number of backslashes, but if it's escaped by a backslash
      we need to add another `*'. */
       if ((mtype != MATCH_END) && (p1[-1] == '*' && (unescaped_backslash = p1[-2] == '\\')))
     {
       pp = p1 - 3;
       while (pp >= pat && *pp-- == '\\')
         unescaped_backslash = 1 - unescaped_backslash;
       if (unescaped_backslash)
         *p++ = '*';
     }
       else if (mtype != MATCH_END && p1[-1] != '*')
     *p++ = '*';
 #else
       if (p1[-1] != '*' || p1[-2] == '\\')
     *p++ = '*';
 #endif
       *p = '\0';
     }
   else
     npat = pat;
   c = strmatch (npat, string, FNMATCH_EXTFLAG | FNMATCH_IGNCASE);
   if (npat != pat)
     free (npat);
   if (c == FNM_NOMATCH)
     return (0);
   len = STRLEN (string);
   end = string + len;
   mlen = umatchlen (pat, len);
   if (mlen > (int)len)
     return (0);
   switch (mtype)
     {
     case MATCH_ANY:
       for (p = string; p <= end; p++)
     {
       if (match_pattern_char (pat, p, FNMATCH_IGNCASE))
         {
           p1 = (mlen == -1) ? end : p + mlen;
           /* p1 - p = length of portion of string to be considered
              p = current position in string
              mlen = number of characters consumed by match (-1 for entire string)
              end = end of string
              we want to break immediately if the potential match len
              is greater than the number of characters remaining in the
              string
           */
           if (p1 > end)
         break;
           for ( ; p1 >= p; p1--)
         {
           c = *p1; *p1 = '\0';
           if (strmatch (pat, p, FNMATCH_EXTFLAG | FNMATCH_IGNCASE) == 0)
             {
               *p1 = c;
               *sp = p;
               *ep = p1;
               return 1;
             }
           *p1 = c;
 #if 1
           /* If MLEN != -1, we have a fixed length pattern. */
           if (mlen != -1)
             break;
 #endif
         }
         }
     }
       return (0);
     case MATCH_BEG:
       if (match_pattern_char (pat, string, FNMATCH_IGNCASE) == 0)
     return (0);
       for (p = (mlen == -1) ? end : string + mlen; p >= string; p--)
     {
       c = *p; *p = '\0';
       if (strmatch (pat, string, FNMATCH_EXTFLAG | FNMATCH_IGNCASE) == 0)
         {
           *p = c;
           *sp = string;
           *ep = p;
           return 1;
         }
       *p = c;
       /* If MLEN != -1, we have a fixed length pattern. */
       if (mlen != -1)
         break;
     }
       return (0);
     case MATCH_END:
       for (p = end - ((mlen == -1) ? len : mlen); p <= end; p++)
     {
       if (strmatch (pat, p, FNMATCH_EXTFLAG | FNMATCH_IGNCASE) == 0)
         {
           *sp = p;
           *ep = end;
           return 1;
         }
       /* If MLEN != -1, we have a fixed length pattern. */
       if (mlen != -1)
         break;
     }
       return (0);
     }
   return (0);
 }
References c, end, extended_glob, FNM_NOMATCH, FNMATCH_EXTFLAG, FNMATCH_IGNCASE, free, len, LPAREN, MATCH_ANY, MATCH_BEG, MATCH_END, p, pat, sp, string, STRLEN, strmatch(), and xmalloc.
Referenced by match_pattern().
optimize_cat_file()
static char* optimize_cat_file (REDIRECT * r, int quoted, int flags, int * flagp) static
Definition at line 6766 of file subst.c.
 {
   char *ret;
   int fd;
   fd = open_redir_file (r, (char **)0);
   if (fd < 0)
     return &expand_param_error;
   ret = read_comsub (fd, quoted, flags, flagp);
   close (fd);
   return ret;
 }
References close(), expand_param_error, fd, flags, open_redir_file(), and read_comsub().
Referenced by command_substitute().
param_expand()
static WORD_DESC* param_expand (char * string, int * sindex, int quoted, int * expanded_something, int * contains_dollar_at, int * quoted_dollar_at_p, int * had_quoted_null_p, int pflags) static
Definition at line 10227 of file subst.c.
 {
   char *temp, *temp1, uerror[3], *savecmd;
   int zindex, t_index, expok, eflag;
   unsigned char c;
   intmax_t number;
   SHELL_VAR *var;
   WORD_LIST *list, *l;
   WORD_DESC *tdesc, *ret;
   int tflag, nullarg;
 /*itrace("param_expand: `%s' pflags = %d", string+*sindex, pflags);*/
   zindex = *sindex;
   c = string[++zindex];
   temp = (char *)NULL;
   ret = tdesc = (WORD_DESC *)NULL;
   tflag = 0;
   /* Do simple cases first. Switch on what follows '$'. */
   switch (c)
     {
     /* $0 .. $9? */
     case '0':
     case '1':
     case '2':
     case '3':
     case '4':
     case '5':
     case '6':
     case '7':
     case '8':
     case '9':
       temp1 = dollar_vars[TODIGIT (c)];
       /* This doesn't get called when (pflags&PF_IGNUNBOUND) != 0 */
       if (unbound_vars_is_error && temp1 == (char *)NULL)
     {
       uerror[0] = '$';
       uerror[1] = c;
       uerror[2] = '\0';
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (uerror);
       return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
       if (temp1)
     temp = (*temp1 && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
           ? quote_string (temp1)
           : quote_escapes (temp1);
       else
     temp = (char *)NULL;
       break;
     /* $$ -- pid of the invoking shell. */
     case '$':
       temp = itos (dollar_dollar_pid);
       break;
     /* $# -- number of positional parameters. */
     case '#':
       temp = itos (number_of_args ());
       break;
     /* $? -- return value of the last synchronous command. */
     case '?':
       temp = itos (last_command_exit_value);
       break;
     /* $- -- flags supplied to the shell on invocation or by `set'. */
     case '-':
       temp = which_set_flags ();
       break;
       /* $! -- Pid of the last asynchronous command. */
     case '!':
       /* If no asynchronous pids have been created, expand to nothing.
      If `set -u' has been executed, and no async processes have
      been created, this is an expansion error. */
       if (last_asynchronous_pid == NO_PID)
     {
       if (expanded_something)
         *expanded_something = 0;
       temp = (char *)NULL;
       if (unbound_vars_is_error && (pflags & PF_IGNUNBOUND) == 0)
         {
           uerror[0] = '$';
           uerror[1] = c;
           uerror[2] = '\0';
           set_exit_status (EXECUTION_FAILURE);
           err_unboundvar (uerror);
           return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
         }
     }
       else
     temp = itos (last_asynchronous_pid);
       break;
     /* The only difference between this and $@ is when the arg is quoted. */
     case '*':       /* `$*' */
       list = list_rest_of_args ();
 #if 0
       /* According to austin-group posix proposal by Geoff Clare in
      <20090505091501.GA10097@squonk.masqnet> of 5 May 2009:
     "The shell shall write a message to standard error and
      immediately exit when it tries to expand an unset parameter
      other than the '@' and '*' special parameters."
       */
       if (list == 0 && unbound_vars_is_error && (pflags & PF_IGNUNBOUND) == 0)
     {
       uerror[0] = '$';
       uerror[1] = '*';
       uerror[2] = '\0';
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (uerror);
       return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
 #endif
       /* If there are no command-line arguments, this should just
      disappear if there are other characters in the expansion,
      even if it's quoted. */
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && list == 0)
     temp = (char *)NULL;
       else if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES|Q_PATQUOTE))
     {
       /* If we have "$*" we want to make a string of the positional
          parameters, separated by the first character of $IFS, and
          quote the whole string, including the separators.  If IFS
          is unset, the parameters are separated by ' '; if $IFS is
          null, the parameters are concatenated. */
       temp = (quoted & (Q_DOUBLE_QUOTES|Q_PATQUOTE)) ? string_list_dollar_star (list, quoted, 0) : string_list (list);
       if (temp)
         {
           temp1 = (quoted & Q_DOUBLE_QUOTES) ? quote_string (temp) : temp;
           if (*temp == 0)
         tflag |= W_HASQUOTEDNULL;
           if (temp != temp1)
         free (temp);
           temp = temp1;
         }
     }
       else
     {
       /* We check whether or not we're eventually going to split $* here,
          for example when IFS is empty and we are processing the rhs of
          an assignment statement.  In that case, we don't separate the
          arguments at all.  Otherwise, if the $* is not quoted it is
          identical to $@ */
       if (expand_no_split_dollar_star && quoted == 0 && ifs_is_set == 0 && (pflags & PF_ASSIGNRHS))
         {
           /* Posix interp 888: RHS of assignment, IFS unset: no splitting,
          separate with space */
           temp1 = string_list_dollar_star (list, quoted, pflags);
           temp = temp1 ? quote_string (temp1) : temp1;
           /* XXX - tentative - note that we saw a quoted null here */
           if (temp1 && *temp1 == 0 && QUOTED_NULL (temp))
         tflag |= W_SAWQUOTEDNULL;
           FREE (temp1);
         }
       else if (expand_no_split_dollar_star && quoted == 0 && ifs_is_null && (pflags & PF_ASSIGNRHS))
         {
           /* Posix interp 888: RHS of assignment, IFS set to '' */
           temp1 = string_list_dollar_star (list, quoted, pflags);
           temp = temp1 ? quote_escapes (temp1) : temp1;
           FREE (temp1);
         }
       else if (expand_no_split_dollar_star && quoted == 0 && ifs_is_set && ifs_is_null == 0 && (pflags & PF_ASSIGNRHS))
         {
           /* Posix interp 888: RHS of assignment, IFS set to non-null value */
           temp1 = string_list_dollar_star (list, quoted, pflags);
           temp = temp1 ? quote_string (temp1) : temp1;
           /* XXX - tentative - note that we saw a quoted null here */
           if (temp1 && *temp1 == 0 && QUOTED_NULL (temp))
         tflag |= W_SAWQUOTEDNULL;
           FREE (temp1);
         }
       /* XXX - should we check ifs_is_set here as well? */
 #  if defined (HANDLE_MULTIBYTE)
       else if (expand_no_split_dollar_star && ifs_firstc[0] == 0)
 #  else
       else if (expand_no_split_dollar_star && ifs_firstc == 0)
 #  endif
         /* Posix interp 888: not RHS, no splitting, IFS set to '' */
         temp = string_list_dollar_star (list, quoted, 0);
       else
         {
           temp = string_list_dollar_at (list, quoted, 0);
           /* Set W_SPLITSPACE to make sure the individual positional
          parameters are split into separate arguments */
 #if 0
           if (quoted == 0 && (ifs_is_set == 0 || ifs_is_null))
 #else   /* change with bash-5.0 */
           if (quoted == 0 && ifs_is_null)
 #endif
         tflag |= W_SPLITSPACE;
           /* If we're not quoted but we still don't want word splitting, make
          we quote the IFS characters to protect them from splitting (e.g.,
          when $@ is in the string as well). */
           else if (temp && quoted == 0 && ifs_is_set && (pflags & PF_ASSIGNRHS))
         {
           temp1 = quote_string (temp);
           free (temp);
           temp = temp1;
         }
         }
       if (expand_no_split_dollar_star == 0 && contains_dollar_at)
         *contains_dollar_at = 1;
     }
       dispose_words (list);
       break;
     /* When we have "$@" what we want is "$1" "$2" "$3" ... This
        means that we have to turn quoting off after we split into
        the individually quoted arguments so that the final split
        on the first character of $IFS is still done.  */
     case '@':       /* `$@' */
       list = list_rest_of_args ();
 #if 0
       /* According to austin-group posix proposal by Geoff Clare in
      <20090505091501.GA10097@squonk.masqnet> of 5 May 2009:
     "The shell shall write a message to standard error and
      immediately exit when it tries to expand an unset parameter
      other than the '@' and '*' special parameters."
       */
       if (list == 0 && unbound_vars_is_error && (pflags & PF_IGNUNBOUND) == 0)
     {
       uerror[0] = '$';
       uerror[1] = '@';
       uerror[2] = '\0';
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (uerror);
       return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
 #endif
       for (nullarg = 0, l = list; l; l = l->next)
     {
       if (l->word && (l->word->word == 0 || l->word->word[0] == 0))
         nullarg = 1;
     }
       /* We want to flag the fact that we saw this.  We can't turn
      off quoting entirely, because other characters in the
      string might need it (consider "\"$@\""), but we need some
      way to signal that the final split on the first character
      of $IFS should be done, even though QUOTED is 1. */
       /* XXX - should this test include Q_PATQUOTE? */
       if (quoted_dollar_at_p && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     *quoted_dollar_at_p = 1;
       if (contains_dollar_at)
     *contains_dollar_at = 1;
       /* We want to separate the positional parameters with the first
      character of $IFS in case $IFS is something other than a space.
      We also want to make sure that splitting is done no matter what --
      according to POSIX.2, this expands to a list of the positional
      parameters no matter what IFS is set to. */
       /* XXX - what to do when in a context where word splitting is not
      performed? Even when IFS is not the default, posix seems to imply
      that we have to expand $@ to all the positional parameters and
      separate them with spaces, which are preserved because word splitting
      doesn't take place.  See below for how we use PF_NOSPLIT2 here. */
       /* These are the cases where word splitting will not be performed. */
       if (pflags & PF_ASSIGNRHS)
     {
       temp = string_list_dollar_at (list, (quoted|Q_DOUBLE_QUOTES), pflags);
       if (nullarg)
         tflag |= W_HASQUOTEDNULL;   /* we know quoting produces quoted nulls */
     }
       /* This needs to match what expand_word_internal does with non-quoted $@
      does with separating with spaces.  Passing Q_DOUBLE_QUOTES means that
      the characters in LIST will be quoted, and PF_ASSIGNRHS ensures that
      they will separated by spaces. After doing this, we need the special
      handling for PF_NOSPLIT2 in expand_word_internal to remove the CTLESC
      quotes. */
       else if (pflags & PF_NOSPLIT2)
         {
 #if defined (HANDLE_MULTIBYTE)
       if (quoted == 0 && ifs_is_set && ifs_is_null == 0 && ifs_firstc[0] != ' ')
 #else
       if (quoted == 0 && ifs_is_set && ifs_is_null == 0 && ifs_firstc != ' ')
 #endif
         /* Posix interp 888 */
         temp = string_list_dollar_at (list, Q_DOUBLE_QUOTES, pflags);
       else
         temp = string_list_dollar_at (list, quoted, pflags);
     }
       else
     temp = string_list_dollar_at (list, quoted, pflags);
       tflag |= W_DOLLARAT;
       dispose_words (list);
       break;
     case LBRACE:
       tdesc = parameter_brace_expand (string, &zindex, quoted, pflags,
                       quoted_dollar_at_p,
                       contains_dollar_at);
       if (tdesc == &expand_wdesc_error || tdesc == &expand_wdesc_fatal)
     return (tdesc);
       temp = tdesc ? tdesc->word : (char *)0;
       /* XXX */
       /* Quoted nulls should be removed if there is anything else
      in the string. */
       /* Note that we saw the quoted null so we can add one back at
      the end of this function if there are no other characters
      in the string, discard TEMP, and go on.  The exception to
      this is when we have "${@}" and $1 is '', since $@ needs
      special handling. */
       if (tdesc && tdesc->word && (tdesc->flags & W_HASQUOTEDNULL) && QUOTED_NULL (temp))
     {
       if (had_quoted_null_p)
         *had_quoted_null_p = 1;
       if (*quoted_dollar_at_p == 0)
         {
           free (temp);
           tdesc->word = temp = (char *)NULL;
         }
     }
       ret = tdesc;
       goto return0;
     /* Do command or arithmetic substitution. */
     case LPAREN:
       /* We have to extract the contents of this paren substitution. */
       t_index = zindex + 1;
       /* XXX - might want to check for string[t_index+2] == LPAREN and parse
      as arithmetic substitution immediately. */
       temp = extract_command_subst (string, &t_index, (pflags&PF_COMPLETE) ? SX_COMPLETE : 0);
       zindex = t_index;
       /* For Posix.2-style `$(( ))' arithmetic substitution,
      extract the expression and pass it to the evaluator. */
       if (temp && *temp == LPAREN)
     {
       char *temp2;
       temp1 = temp + 1;
       temp2 = savestring (temp1);
       t_index = strlen (temp2) - 1;
       if (temp2[t_index] != RPAREN)
         {
           free (temp2);
           goto comsub;
         }
       /* Cut off ending `)' */
       temp2[t_index] = '\0';
       if (chk_arithsub (temp2, t_index) == 0)
         {
           free (temp2);
 #if 0
           internal_warning (_("future versions of the shell will force evaluation as an arithmetic substitution"));
 #endif
           goto comsub;
         }
       /* Expand variables found inside the expression. */
       temp1 = expand_arith_string (temp2, Q_DOUBLE_QUOTES|Q_ARITH);
       free (temp2);
 arithsub:
       /* No error messages. */
       savecmd = this_command_name;
       this_command_name = (char *)NULL;
       eflag = (shell_compatibility_level > 51) ? 0 : EXP_EXPANDED;
       number = evalexp (temp1, eflag, &expok);
       this_command_name = savecmd;
       free (temp);
       free (temp1);
       if (expok == 0)
         {
           if (interactive_shell == 0 && posixly_correct)
         {
           set_exit_status (EXECUTION_FAILURE);
           return (&expand_wdesc_fatal);
         }
           else
         return (&expand_wdesc_error);
         }
       temp = itos (number);
       break;
     }
 comsub:
       if (pflags & PF_NOCOMSUB)
     /* we need zindex+1 because string[zindex] == RPAREN */
     temp1 = substring (string, *sindex, zindex+1);
       else
     {
       tdesc = command_substitute (temp, quoted, pflags&PF_ASSIGNRHS);
       temp1 = tdesc ? tdesc->word : (char *)NULL;
       if (tdesc)
         dispose_word_desc (tdesc);
     }
       FREE (temp);
       temp = temp1;
       break;
     /* Do POSIX.2d9-style arithmetic substitution.  This will probably go
        away in a future bash release. */
     case '[':       /*]*/
       /* Extract the contents of this arithmetic substitution. */
       t_index = zindex + 1;
       temp = extract_arithmetic_subst (string, &t_index);
       zindex = t_index;
       if (temp == 0)
     {
       temp = savestring (string);
       if (expanded_something)
         *expanded_something = 0;
       goto return0;
     }
        /* Do initial variable expansion. */
       temp1 = expand_arith_string (temp, Q_DOUBLE_QUOTES|Q_ARITH);
       goto arithsub;
     default:
       /* Find the variable in VARIABLE_LIST. */
       temp = (char *)NULL;
       for (t_index = zindex; (c = string[zindex]) && legal_variable_char (c); zindex++)
     ;
       temp1 = (zindex > t_index) ? substring (string, t_index, zindex) : (char *)NULL;
       /* If this isn't a variable name, then just output the `$'. */
       if (temp1 == 0 || *temp1 == '\0')
     {
       FREE (temp1);
       temp = (char *)xmalloc (2);
       temp[0] = '$';
       temp[1] = '\0';
       if (expanded_something)
         *expanded_something = 0;
       goto return0;
     }
       /* If the variable exists, return its value cell. */
       var = find_variable (temp1);
       if (var && invisible_p (var) == 0 && var_isset (var))
     {
 #if defined (ARRAY_VARS)
       if (assoc_p (var) || array_p (var))
         {
           temp = array_p (var) ? array_reference (array_cell (var), 0)
                    : assoc_reference (assoc_cell (var), "0");
           if (temp)
         temp = (*temp && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
               ? quote_string (temp)
               : quote_escapes (temp);
           else if (unbound_vars_is_error)
         goto unbound_variable;
         }
       else
 #endif
         {
           temp = value_cell (var);
           temp = (*temp && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
             ? quote_string (temp)
             : ((pflags & PF_ASSIGNRHS) ? quote_rhs (temp)
                            : quote_escapes (temp));
         }
       free (temp1);
       goto return0;
     }
       else if (var && (invisible_p (var) || var_isset (var) == 0))
     temp = (char *)NULL;
       else if ((var = find_variable_last_nameref (temp1, 0)) && var_isset (var) && invisible_p (var) == 0)
     {
       temp = nameref_cell (var);
 #if defined (ARRAY_VARS)
       if (temp && *temp && valid_array_reference (temp, 0))
         {
           chk_atstar (temp, quoted, pflags, quoted_dollar_at_p, contains_dollar_at);
           tdesc = parameter_brace_expand_word (temp, SPECIAL_VAR (temp, 0), quoted, pflags, 0);
           if (tdesc == &expand_wdesc_error || tdesc == &expand_wdesc_fatal)
         return (tdesc);
           ret = tdesc;
           goto return0;
         }
       else
 #endif
       /* y=2 ; typeset -n x=y; echo $x is not the same as echo $2 in ksh */
       if (temp && *temp && legal_identifier (temp) == 0)
         {
           set_exit_status (EXECUTION_FAILURE);
           report_error (_("%s: invalid variable name for name reference"), temp);
           return (&expand_wdesc_error); /* XXX */
         }
       else
         temp = (char *)NULL;
     }
       temp = (char *)NULL;
 unbound_variable:
       if (unbound_vars_is_error)
     {
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (temp1);
     }
       else
     {
       free (temp1);
       goto return0;
     }
       free (temp1);
       set_exit_status (EXECUTION_FAILURE);
       return ((unbound_vars_is_error && interactive_shell == 0)
         ? &expand_wdesc_fatal
         : &expand_wdesc_error);
     }
   if (string[zindex])
     zindex++;
 return0:
   *sindex = zindex;
   if (ret == 0)
     {
       ret = alloc_word_desc ();
       ret->flags = tflag;   /* XXX */
       ret->word = temp;
     }
   return ret;
 }
References _, alloc_word_desc(), array_cell, array_p, assoc_cell, assoc_p, c, chk_arithsub(), chk_atstar(), command_substitute(), dispose_word_desc(), dispose_words(), dollar_dollar_pid, dollar_vars, eflag, err_unboundvar(), evalexp(), EXECUTION_FAILURE, EXP_EXPANDED, expand_arith_string(), expand_no_split_dollar_star, expand_wdesc_error, expand_wdesc_fatal, extract_arithmetic_subst(), extract_command_subst(), find_variable(), find_variable_last_nameref(), word_desc::flags, FREE, free, ifs_firstc, ifs_is_null, ifs_is_set, interactive_shell, internal_warning(), invisible_p, itos(), l, last_asynchronous_pid, last_command_exit_value, LBRACE, legal_identifier(), legal_variable_char, list(), list_rest_of_args(), LPAREN, nameref_cell, NO_PID, NULL, number(), number_of_args(), parameter_brace_expand(), parameter_brace_expand_word(), PF_ASSIGNRHS, PF_COMPLETE, PF_IGNUNBOUND, PF_NOCOMSUB, PF_NOSPLIT2, posixly_correct, Q_ARITH, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, Q_PATQUOTE, quote_escapes(), quote_rhs(), quote_string(), QUOTED_NULL, report_error(), RPAREN, savestring(), set_exit_status(), shell_compatibility_level, SPECIAL_VAR, string_list(), string_list_dollar_at(), string_list_dollar_star(), strlen(), substring(), SX_COMPLETE, this_command_name, TODIGIT, unbound_vars_is_error, value_cell, var_isset, W_DOLLARAT, W_HASQUOTEDNULL, W_SAWQUOTEDNULL, W_SPLITSPACE, which_set_flags(), word_desc::word, and xmalloc.
Referenced by expand_word_internal(), and parameter_brace_expand_word().
parameter_brace_casemod()
static char* parameter_brace_casemod (char * varname, char * value, array_eltstate_t * estatep, int modspec, char * patspec, int quoted, int pflags, int flags) static
Definition at line 9355 of file subst.c.
 {
   int vtype, starsub, modop, mflags, x;
   char *val, *temp, *pat, *p, *lpat, *tt, *oname;
   SHELL_VAR *v;
   if (value == 0)
     return ((char *)NULL);
   oname = this_command_name;
   this_command_name = varname;
   vtype = get_var_and_type (varname, value, estatep, quoted, flags, &v, &val);
   if (vtype == -1)
     {
       this_command_name = oname;
       return ((char *)NULL);
     }
   starsub = vtype & VT_STARSUB;
   vtype &= ~VT_STARSUB;
   modop = 0;
   mflags = 0;
   if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
     mflags |= MATCH_QUOTED;
   if (starsub)
     mflags |= MATCH_STARSUB;
   if (pflags & PF_ASSIGNRHS)
     mflags |= MATCH_ASSIGNRHS;
   p = patspec;
   if (modspec == '^')
     {
       x = p && p[0] == modspec;
       modop = x ? CASE_UPPER : CASE_UPFIRST;
       p += x;
     }
   else if (modspec == ',')
     {
       x = p && p[0] == modspec;
       modop = x ? CASE_LOWER : CASE_LOWFIRST;
       p += x;
     }
   else if (modspec == '~')
     {
       x = p && p[0] == modspec;
       modop = x ? CASE_TOGGLEALL : CASE_TOGGLE;
       p += x;
     }
   lpat = p ? savestring (p) : 0;
   /* Perform the same expansions on the pattern as performed by the
      pattern removal expansions. */
   pat = lpat ? getpattern (lpat, quoted, 1) : 0;
   /* OK, now we do the case modification. */
   switch (vtype)
     {
     case VT_VARIABLE:
     case VT_ARRAYMEMBER:
       temp = sh_modcase (val, pat, modop);
       if (vtype == VT_VARIABLE)
     FREE (val);
       if (temp)
     {
       tt = (mflags & MATCH_QUOTED) ? quote_string (temp) : quote_escapes (temp);
       free (temp);
       temp = tt;
     }
       break;
     case VT_POSPARMS:
       temp = pos_params_modcase (val, pat, modop, mflags);
       if (temp && quoted == 0 && ifs_is_null)
     {
       /* Posix interp 888 */
     }
       else if (temp && (mflags & MATCH_QUOTED) == 0)
     {
       tt = quote_escapes (temp);
       free (temp);
       temp = tt;
     }
       break;
 #if defined (ARRAY_VARS)
     case VT_ARRAYVAR:
       /* If we are expanding in a context where word splitting will not be
      performed, treat as quoted.  This changes how ${A[*]} will be
      expanded to make it identical to $*. */
       if ((mflags & MATCH_STARSUB) && (mflags & MATCH_ASSIGNRHS) && ifs_is_null)
     mflags |= MATCH_QUOTED;     /* Posix interp 888 */
       temp = assoc_p (v) ? assoc_modcase (assoc_cell (v), pat, modop, mflags)
              : array_modcase (array_cell (v), pat, modop, mflags);
       if (temp && quoted == 0 && ifs_is_null)
     {
       /* Posix interp 888 */
     }
       else if (temp && (mflags & MATCH_QUOTED) == 0)
     {
       tt = quote_escapes (temp);
       free (temp);
       temp = tt;
     }
       break;
 #endif
     }
   FREE (pat);
   free (lpat);
   this_command_name = oname;
   return temp;
 }
References array_cell, assoc_cell, assoc_p, CASE_LOWER, CASE_LOWFIRST, CASE_TOGGLE, CASE_TOGGLEALL, CASE_UPFIRST, CASE_UPPER, flags, FREE, free, get_var_and_type(), getpattern(), ifs_is_null, MATCH_ASSIGNRHS, MATCH_QUOTED, MATCH_STARSUB, NULL, p, pat, PF_ASSIGNRHS, pos_params_modcase(), Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_string(), savestring(), sh_modcase(), this_command_name, tt, val, value, VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, VT_STARSUB, VT_VARIABLE, and x.
Referenced by parameter_brace_expand().
parameter_brace_expand()
static WORD_DESC* parameter_brace_expand (char * string, int * indexp, int quoted, int pflags, int * quoted_dollar_atp, int * contains_dollar_at) static
Definition at line 9539 of file subst.c.
 {
   int check_nullness, var_is_set, var_is_null, var_is_special;
   int want_substring, want_indir, want_patsub, want_casemod, want_attributes;
   char *name, *value, *temp, *temp1;
   WORD_DESC *tdesc, *ret;
   int t_index, sindex, c, tflag, modspec, local_pflags, all_element_arrayref;
   intmax_t number;
   array_eltstate_t es;
   temp = temp1 = value = (char *)NULL;
   var_is_set = var_is_null = var_is_special = check_nullness = 0;
   want_substring = want_indir = want_patsub = want_casemod = want_attributes = 0;
   local_pflags = 0;
   all_element_arrayref = 0;
   sindex = *indexp;
   t_index = ++sindex;
   /* ${#var} doesn't have any of the other parameter expansions on it. */
   if (string[t_index] == '#' && legal_variable_starter (string[t_index+1]))     /* {{ */
     name = string_extract (string, &t_index, "}", SX_VARNAME);
   else
 #if defined (CASEMOD_EXPANSIONS)
     /* To enable case-toggling expansions using the `~' operator character
        define CASEMOD_TOGGLECASE in config-top.h */
 #  if defined (CASEMOD_TOGGLECASE)
     name = string_extract (string, &t_index, "#%^,~:-=?+/@}", SX_VARNAME);
 #  else
     name = string_extract (string, &t_index, "#%^,:-=?+/@}", SX_VARNAME);
 #  endif /* CASEMOD_TOGGLECASE */
 #else
     name = string_extract (string, &t_index, "#%:-=?+/@}", SX_VARNAME);
 #endif /* CASEMOD_EXPANSIONS */
   /* Handle ${@[stuff]} now that @ is a word expansion operator.  Not exactly
      the cleanest code ever. */
   if (*name == 0 && sindex == t_index && string[sindex] == '@')
     {
       name = (char *)xrealloc (name, 2);
       name[0] = '@';
       name[1] = '\0';
       t_index++;
     }
   else if (*name == '!' && t_index > sindex && string[t_index] == '@' && string[t_index+1] == RBRACE)
     {
       name = (char *)xrealloc (name, t_index - sindex + 2);
       name[t_index - sindex] = '@';
       name[t_index - sindex + 1] = '\0';
       t_index++;
     }
   ret = 0;
   tflag = 0;
 #if defined (ARRAY_VARS)
   init_eltstate (&es);
 #endif
   es.ind = INTMAX_MIN;  /* XXX */
   /* If the name really consists of a special variable, then make sure
      that we have the entire name.  We don't allow indirect references
      to special variables except `#', `?', `@' and `*'.  This clause is
      designed to handle ${#SPECIAL} and ${!SPECIAL}, not anything more
      general. */
   if ((sindex == t_index && VALID_SPECIAL_LENGTH_PARAM (string[t_index])) ||
       (sindex == t_index && string[sindex] == '#' && VALID_SPECIAL_LENGTH_PARAM (string[sindex + 1])) ||
       (sindex == t_index - 1 && string[sindex] == '!' && VALID_INDIR_PARAM (string[t_index])))
     {
       t_index++;
       temp1 = string_extract (string, &t_index, "#%:-=?+/@}", 0);
       name = (char *)xrealloc (name, 3 + (strlen (temp1)));
       *name = string[sindex];
       if (string[sindex] == '!')
     {
       /* indirect reference of $#, $?, $@, or $* */
       name[1] = string[sindex + 1];
       strcpy (name + 2, temp1);
     }
       else
     strcpy (name + 1, temp1);
       free (temp1);
     }
   sindex = t_index;
   /* Find out what character ended the variable name.  Then
      do the appropriate thing. */
   if (c = string[sindex])
     sindex++;
   /* If c is followed by one of the valid parameter expansion
      characters, move past it as normal.  If not, assume that
      a substring specification is being given, and do not move
      past it. */
   if (c == ':' && VALID_PARAM_EXPAND_CHAR (string[sindex]))
     {
       check_nullness++;
       if (c = string[sindex])
     sindex++;
     }
   else if (c == ':' && string[sindex] != RBRACE)
     want_substring = 1;
   else if (c == '/' /* && string[sindex] != RBRACE */)  /* XXX */
     want_patsub = 1;
 #if defined (CASEMOD_EXPANSIONS)
   else if (c == '^' || c == ',' || c == '~')
     {
       modspec = c;
       want_casemod = 1;
     }
 #endif
   else if (c == '@' && (string[sindex] == 'a' || string[sindex] == 'A') && string[sindex+1] == RBRACE)
     {
       /* special case because we do not want to shortcut foo as foo[0] here */
       want_attributes = 1;
       local_pflags |= PF_ALLINDS;
     }
   /* Catch the valid and invalid brace expressions that made it through the
      tests above. */
   /* ${#-} is a valid expansion and means to take the length of $-.
      Similarly for ${#?} and ${##}... */
   if (name[0] == '#' && name[1] == '\0' && check_nullness == 0 &&
     VALID_SPECIAL_LENGTH_PARAM (c) && string[sindex] == RBRACE)
     {
       name = (char *)xrealloc (name, 3);
       name[1] = c;
       name[2] = '\0';
       c = string[sindex++];
     }
   /* ...but ${#%}, ${#:}, ${#=}, ${#+}, and ${#/} are errors. */
   if (name[0] == '#' && name[1] == '\0' && check_nullness == 0 &&
     member (c, "%:=+/") && string[sindex] == RBRACE)
     {
       temp = (char *)NULL;
       goto bad_substitution;    /* XXX - substitution error */
     }
   /* Indirect expansion begins with a `!'.  A valid indirect expansion is
      either a variable name, one of the positional parameters or a special
      variable that expands to one of the positional parameters. */
   want_indir = *name == '!' &&
     (legal_variable_starter ((unsigned char)name[1]) || DIGIT (name[1])
                     || VALID_INDIR_PARAM (name[1]));
   /* Determine the value of this variable whose name is NAME. */
   /* Check for special variables, directly referenced. */
   if (SPECIAL_VAR (name, want_indir))
     var_is_special++;
   /* Check for special expansion things, like the length of a parameter */
   if (*name == '#' && name[1])
     {
       /* If we are not pointing at the character just after the
      closing brace, then we haven't gotten all of the name.
      Since it begins with a special character, this is a bad
      substitution.  Also check NAME for validity before trying
      to go on. */
       if (string[sindex - 1] != RBRACE || (valid_length_expression (name) == 0))
     {
       temp = (char *)NULL;
       goto bad_substitution;    /* substitution error */
     }
       number = parameter_brace_expand_length (name);
       if (number == INTMAX_MIN && unbound_vars_is_error)
     {
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (name+1);
       free (name);
       return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
       free (name);
       *indexp = sindex;
       if (number < 0)
         return (&expand_wdesc_error);
       else
     {
       ret = alloc_word_desc ();
       ret->word = itos (number);
       return ret;
     }
     }
   /* ${@} is identical to $@. */
   if (name[0] == '@' && name[1] == '\0')
     {
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
     *quoted_dollar_atp = 1;
       if (contains_dollar_at)
     *contains_dollar_at = 1;
       tflag |= W_DOLLARAT;
     }
   /* Process ${!PREFIX*} expansion. */
   if (want_indir && string[sindex - 1] == RBRACE &&
       (string[sindex - 2] == '*' || string[sindex - 2] == '@') &&
       legal_variable_starter ((unsigned char) name[1]))
     {
       char **x;
       WORD_LIST *xlist;
       temp1 = savestring (name + 1);
       number = strlen (temp1);
       temp1[number - 1] = '\0';
       x = all_variables_matching_prefix (temp1);
       xlist = strvec_to_word_list (x, 0, 0);
       if (string[sindex - 2] == '*')
     temp = string_list_dollar_star (xlist, quoted, 0);
       else
     {
       temp = string_list_dollar_at (xlist, quoted, 0);
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
         *quoted_dollar_atp = 1;
       if (contains_dollar_at)
         *contains_dollar_at = 1;
       tflag |= W_DOLLARAT;
     }
       free (x);
       dispose_words (xlist);
       free (temp1);
       *indexp = sindex;
       free (name);
       ret = alloc_word_desc ();
       ret->word = temp;
       ret->flags = tflag;   /* XXX */
       return ret;
     }
 #if defined (ARRAY_VARS)
   /* Process ${!ARRAY[@]} and ${!ARRAY[*]} expansion. */
   if (want_indir && string[sindex - 1] == RBRACE &&
       string[sindex - 2] == RBRACK && valid_array_reference (name+1, 0))
     {
       char *x, *x1;
       temp1 = savestring (name + 1);
       x = array_variable_name (temp1, 0, &x1, (int *)0);
       FREE (x);
       if (ALL_ELEMENT_SUB (x1[0]) && x1[1] == RBRACK)
     {
       temp = array_keys (temp1, quoted, pflags);    /* handles assoc vars too */
       if (x1[0] == '@')
         {
           if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
         *quoted_dollar_atp = 1;
           if (contains_dollar_at)
         *contains_dollar_at = 1;
           tflag |= W_DOLLARAT;
         }
       free (name);
       free (temp1);
       *indexp = sindex;
       ret = alloc_word_desc ();
       ret->word = temp;
       ret->flags = tflag;   /* XXX */
       return ret;
     }
       free (temp1);
     }
 #endif /* ARRAY_VARS */
   /* Make sure that NAME is valid before trying to go on. */
   if (valid_brace_expansion_word (want_indir ? name + 1 : name,
                     var_is_special) == 0)
     {
       temp = (char *)NULL;
       goto bad_substitution;        /* substitution error */
     }
   if (want_indir)
     {
       tdesc = parameter_brace_expand_indir (name + 1, var_is_special, quoted, pflags|local_pflags, quoted_dollar_atp, contains_dollar_at);
       if (tdesc == &expand_wdesc_error || tdesc == &expand_wdesc_fatal)
     {
       temp = (char *)NULL;
       goto bad_substitution;
     }
       /* Turn off the W_ARRAYIND flag because there is no way for this function
      to return the index we're supposed to be using. */
       if (tdesc && tdesc->flags)
     tdesc->flags &= ~W_ARRAYIND;
       /* If the indir expansion contains $@/$*, extend the special treatment
      of the case of no positional parameters and `set -u' to it. */
       if (contains_dollar_at && *contains_dollar_at)
     all_element_arrayref = 1;
     }
   else
     {
       local_pflags |= PF_IGNUNBOUND|(pflags&(PF_NOSPLIT2|PF_ASSIGNRHS));
       tdesc = parameter_brace_expand_word (name, var_is_special, quoted, local_pflags, &es);
     }
   if (tdesc == &expand_wdesc_error || tdesc == &expand_wdesc_fatal)
     {
       tflag = 0;
       tdesc = 0;
     }
   if (tdesc)
     {
       temp = tdesc->word;
       tflag = tdesc->flags;
       dispose_word_desc (tdesc);
     }
   else
     temp = (char *)0;
   if (temp == &expand_param_error || temp == &expand_param_fatal)
     {
       FREE (name);
       FREE (value);
       return (temp == &expand_param_error ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
 #if defined (ARRAY_VARS)
   if (valid_array_reference (name, 0))
     {
       int qflags;
       char *t;
       qflags = quoted;
       /* If in a context where word splitting will not take place, treat as
      if double-quoted.  Has effects with $* and ${array[*]} */
       if (pflags & PF_ASSIGNRHS)
     qflags |= Q_DOUBLE_QUOTES;
       /* We duplicate a little code here */
       t = mbschr (name, LBRACK);
       if (t && ALL_ELEMENT_SUB (t[1]) && t[2] == RBRACK)
     {
       all_element_arrayref = 1;
       if (expand_no_split_dollar_star && t[1] == '*')   /* XXX */
         qflags |= Q_DOUBLE_QUOTES;
     }
       chk_atstar (name, qflags, pflags, quoted_dollar_atp, contains_dollar_at);
     }
 #endif
   var_is_set = temp != (char *)0;
   var_is_null = check_nullness && (var_is_set == 0 || *temp == 0);
   /* XXX - this may not need to be restricted to special variables */
   if (check_nullness)
     var_is_null |= var_is_set && var_is_special && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && QUOTED_NULL (temp);
 #if defined (ARRAY_VARS)
   if (check_nullness)
     var_is_null |= var_is_set &&
            (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) &&
            QUOTED_NULL (temp) &&
            valid_array_reference (name, 0) &&
            chk_atstar (name, 0, 0, (int *)0, (int *)0);
 #endif
   /* Get the rest of the stuff inside the braces. */
   if (c && c != RBRACE)
     {
       /* Extract the contents of the ${ ... } expansion
      according to the Posix.2 rules. */
       value = extract_dollar_brace_string (string, &sindex, quoted, (c == '%' || c == '#' || c =='/' || c == '^' || c == ',' || c ==':') ? SX_POSIXEXP|SX_WORD : SX_WORD);
       if (string[sindex] == RBRACE)
     sindex++;
       else
     goto bad_substitution;      /* substitution error */
     }
   else
     value = (char *)NULL;
   *indexp = sindex;
   /* All the cases where an expansion can possibly generate an unbound
      variable error. */
   if (want_substring || want_patsub || want_casemod || c == '@' || c == '#' || c == '%' || c == RBRACE)
     {
       if (var_is_set == 0 && unbound_vars_is_error && ((name[0] != '@' && name[0] != '*') || name[1]) && all_element_arrayref == 0)
     {
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (name);
       FREE (value);
       FREE (temp);
       free (name);
       return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
     }
   /* If this is a substring spec, process it and add the result. */
   if (want_substring)
     {
       temp1 = parameter_brace_substring (name, temp, &es, value, quoted, pflags, (tflag & W_ARRAYIND) ? AV_USEIND : 0);
       FREE (value);
       FREE (temp);
 #if defined (ARRAY_VARS)
       flush_eltstate (&es);
 #endif
       if (temp1 == &expand_param_error || temp1 == &expand_param_fatal)
         {
           FREE (name);
       return (temp1 == &expand_param_error ? &expand_wdesc_error : &expand_wdesc_fatal);
         }
       ret = alloc_word_desc ();
       ret->word = temp1;
       /* We test quoted_dollar_atp because we want variants with double-quoted
      "$@" to take a different code path. In fact, we make sure at the end
      of expand_word_internal that we're only looking at these flags if
      quoted_dollar_at == 0. */
       if (temp1 &&
           (quoted_dollar_atp == 0 || *quoted_dollar_atp == 0) &&
       QUOTED_NULL (temp1) && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     ret->flags |= W_QUOTED|W_HASQUOTEDNULL;
       else if (temp1 && (name[0] == '*' && name[1] == 0) && quoted == 0 &&
         (pflags & PF_ASSIGNRHS))
     ret->flags |= W_SPLITSPACE; /* Posix interp 888 */
       /* Special handling for $* when unquoted and $IFS is null. Posix interp 888 */
       else if (temp1 && (name[0] == '*' && name[1] == 0) && quoted == 0 && ifs_is_null)
     ret->flags |= W_SPLITSPACE; /* Posix interp 888 */
       FREE (name);
       return ret;
     }
   else if (want_patsub)
     {
       temp1 = parameter_brace_patsub (name, temp, &es, value, quoted, pflags, (tflag & W_ARRAYIND) ? AV_USEIND : 0);
       FREE (value);
       FREE (temp);
 #if defined (ARRAY_VARS)
       flush_eltstate (&es);
 #endif
       if (temp1 == &expand_param_error || temp1 == &expand_param_fatal)
         {
           FREE (name);
       return (temp1 == &expand_param_error ? &expand_wdesc_error : &expand_wdesc_fatal);
         }
       ret = alloc_word_desc ();
       ret->word = temp1;
       if (temp1 &&
           (quoted_dollar_atp == 0 || *quoted_dollar_atp == 0) &&
       QUOTED_NULL (temp1) && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     ret->flags |= W_QUOTED|W_HASQUOTEDNULL;
       /* Special handling for $* when unquoted and $IFS is null. Posix interp 888 */
       else if (temp1 && (name[0] == '*' && name[1] == 0) && quoted == 0 && ifs_is_null)
     ret->flags |= W_SPLITSPACE; /* Posix interp 888 */
       FREE (name);
       return ret;
     }
 #if defined (CASEMOD_EXPANSIONS)
   else if (want_casemod)
     {
       temp1 = parameter_brace_casemod (name, temp, &es, modspec, value, quoted, pflags, (tflag & W_ARRAYIND) ? AV_USEIND : 0);
       FREE (value);
       FREE (temp);
 #if defined (ARRAY_VARS)
       flush_eltstate (&es);
 #endif
       if (temp1 == &expand_param_error || temp1 == &expand_param_fatal)
         {
           FREE (name);
       return (temp1 == &expand_param_error ? &expand_wdesc_error : &expand_wdesc_fatal);
         }
       ret = alloc_word_desc ();
       ret->word = temp1;
       if (temp1 &&
           (quoted_dollar_atp == 0 || *quoted_dollar_atp == 0) &&
       QUOTED_NULL (temp1) && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     ret->flags |= W_QUOTED|W_HASQUOTEDNULL;
       /* Special handling for $* when unquoted and $IFS is null. Posix interp 888 */
       else if (temp1 && (name[0] == '*' && name[1] == 0) && quoted == 0 && ifs_is_null)
     ret->flags |= W_SPLITSPACE; /* Posix interp 888 */
       FREE (name);
       return ret;
     }
 #endif
   /* Do the right thing based on which character ended the variable name. */
   switch (c)
     {
     default:
     case '\0':
 bad_substitution:
       set_exit_status (EXECUTION_FAILURE);
       report_error (_("%s: bad substitution"), string ? string : "??");
       FREE (value);
       FREE (temp);
       free (name);
 #if defined (ARRAY_VARS)
       flush_eltstate (&es);
 #endif
       if (shell_compatibility_level <= 43)
     return &expand_wdesc_error;
       else
     return ((posixly_correct && interactive_shell == 0) ? &expand_wdesc_fatal : &expand_wdesc_error);
     case RBRACE:
       break;
     case '@':
       temp1 = parameter_brace_transform (name, temp, &es, value, c, quoted, pflags, (tflag & W_ARRAYIND) ? AV_USEIND : 0);
       free (temp);
       free (value);
 #if defined (ARRAY_VARS)
       flush_eltstate (&es);
 #endif
       if (temp1 == &expand_param_error || temp1 == &expand_param_fatal)
     {
       free (name);
       set_exit_status (EXECUTION_FAILURE);
       report_error (_("%s: bad substitution"), string ? string : "??");
       return (temp1 == &expand_param_error ? &expand_wdesc_error : &expand_wdesc_fatal);
     }
       ret = alloc_word_desc ();
       ret->word = temp1;
       if (temp1 && QUOTED_NULL (temp1) && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     ret->flags |= W_QUOTED|W_HASQUOTEDNULL;
       /* Special handling for $* when unquoted and $IFS is null. Posix interp 888 */
       else if (temp1 && (name[0] == '*' && name[1] == 0) && quoted == 0 && ifs_is_null)
     ret->flags |= W_SPLITSPACE; /* Posix interp 888 */
       free (name);
       return ret;
     case '#':   /* ${param#[#]pattern} */
     case '%':   /* ${param%[%]pattern} */
       if (value == 0 || *value == '\0' || temp == 0 || *temp == '\0')
     {
       FREE (value);
       break;
     }
       temp1 = parameter_brace_remove_pattern (name, temp, &es, value, c, quoted, (tflag & W_ARRAYIND) ? AV_USEIND : 0);
       free (temp);
       free (value);
 #if defined (ARRAY_VARS)
       flush_eltstate (&es);
 #endif
       ret = alloc_word_desc ();
       ret->word = temp1;
       if (temp1 && QUOTED_NULL (temp1) && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     ret->flags |= W_QUOTED|W_HASQUOTEDNULL;
       /* Special handling for $* when unquoted and $IFS is null. Posix interp 888 */
       else if (temp1 && (name[0] == '*' && name[1] == 0) && quoted == 0 && ifs_is_null)
     ret->flags |= W_SPLITSPACE; /* Posix interp 888 */
       free (name);
       return ret;
     case '-':
     case '=':
     case '?':
     case '+':
       if (var_is_set && var_is_null == 0)
     {
       /* If the operator is `+', we don't want the value of the named
          variable for anything, just the value of the right hand side. */
       if (c == '+')
         {
           /* XXX -- if we're double-quoted and the named variable is "$@",
             we want to turn off any special handling of "$@" --
             we're not using it, so whatever is on the rhs applies. */
           if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
         *quoted_dollar_atp = 0;
           if (contains_dollar_at)
         *contains_dollar_at = 0;
           FREE (temp);
           if (value)
         {
           /* From Posix discussion on austin-group list.  Issue 221
              requires that backslashes escaping `}' inside
              double-quoted ${...} be removed. */
           if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
             quoted |= Q_DOLBRACE;
           ret = parameter_brace_expand_rhs (name, value, c,
                             quoted,
                             pflags,
                             quoted_dollar_atp,
                             contains_dollar_at);
           /* XXX - fix up later, esp. noting presence of
                W_HASQUOTEDNULL in ret->flags */
           free (value);
         }
           else
         temp = (char *)NULL;
         }
       else
         {
           FREE (value);
         }
       /* Otherwise do nothing; just use the value in TEMP. */
     }
       else  /* VAR not set or VAR is NULL. */
     {
       /* If we're freeing a quoted null here, we need to remember we saw
          it so we can restore it later if needed, or the caller can note it.
          The check against `+' doesn't really matter, since the other cases
          don't use or return TFLAG, but it's good for clarity. */
       if (c == '+' && temp && QUOTED_NULL (temp) &&
           (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
         tflag |= W_HASQUOTEDNULL;
       FREE (temp);
       temp = (char *)NULL;
       if (c == '=' && var_is_special)
         {
           set_exit_status (EXECUTION_FAILURE);
           report_error (_("$%s: cannot assign in this way"), name);
           free (name);
           free (value);
 #if defined (ARRAY_VARS)
           flush_eltstate (&es);
 #endif
           return &expand_wdesc_error;
         }
       else if (c == '?')
         {
           parameter_brace_expand_error (name, value, check_nullness);
 #if defined (ARRAY_VARS)
           flush_eltstate (&es);
 #endif
           return (interactive_shell ? &expand_wdesc_error : &expand_wdesc_fatal);
         }
       else if (c != '+')
         {
           /* XXX -- if we're double-quoted and the named variable is "$@",
             we want to turn off any special handling of "$@" --
             we're not using it, so whatever is on the rhs applies. */
           if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && quoted_dollar_atp)
         *quoted_dollar_atp = 0;
           if (contains_dollar_at)
         *contains_dollar_at = 0;
           /* From Posix discussion on austin-group list.  Issue 221 requires
          that backslashes escaping `}' inside double-quoted ${...} be
          removed. */
           if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
         quoted |= Q_DOLBRACE;
           ret = parameter_brace_expand_rhs (name, value, c, quoted, pflags,
                         quoted_dollar_atp,
                         contains_dollar_at);
           /* XXX - fix up later, esp. noting presence of
                W_HASQUOTEDNULL in tdesc->flags */
         }
       free (value);
     }
       break;
     }
   free (name);
 #if defined (ARRAY_VARS)
   flush_eltstate (&es);
 #endif
   if (ret == 0)
     {
       ret = alloc_word_desc ();
       ret->flags = tflag;
       ret->word = temp;
     }
   return (ret);
 }
References _, ALL_ELEMENT_SUB, all_variables_matching_prefix(), alloc_word_desc(), AV_USEIND, c, chk_atstar(), DIGIT, dispose_word_desc(), dispose_words(), err_unboundvar(), EXECUTION_FAILURE, expand_no_split_dollar_star, expand_param_error, expand_param_fatal, expand_wdesc_error, expand_wdesc_fatal, extract_dollar_brace_string(), word_desc::flags, FREE, free, ifs_is_null, element_state::ind, interactive_shell, INTMAX_MIN, itos(), LBRACK, legal_variable_starter, mbschr(), member, NULL, number(), parameter_brace_casemod(), parameter_brace_expand_error(), parameter_brace_expand_indir(), parameter_brace_expand_length(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), parameter_brace_transform(), PF_ALLINDS, PF_ASSIGNRHS, PF_IGNUNBOUND, PF_NOSPLIT2, posixly_correct, Q_DOLBRACE, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, QUOTED_NULL, RBRACE, RBRACK, report_error(), savestring(), set_exit_status(), shell_compatibility_level, SPECIAL_VAR, strcpy, string_extract(), string_list_dollar_at(), string_list_dollar_star(), strlen(), strvec_to_word_list(), SX_POSIXEXP, SX_VARNAME, SX_WORD, t, unbound_vars_is_error, valid_brace_expansion_word(), VALID_INDIR_PARAM, valid_length_expression(), VALID_PARAM_EXPAND_CHAR, VALID_SPECIAL_LENGTH_PARAM, value, W_ARRAYIND, W_DOLLARAT, W_HASQUOTEDNULL, W_QUOTED, W_SPLITSPACE, word_desc::word, x, and xrealloc.
Referenced by param_expand().
parameter_brace_expand_error()
static void parameter_brace_expand_error (char * name, char * value, int check_null) static
Definition at line 7942 of file subst.c.
 {
   WORD_LIST *l;
   char *temp;
   set_exit_status (EXECUTION_FAILURE);  /* ensure it's non-zero */
   if (value && *value)
     {
       l = expand_string (value, 0);
       temp =  string_list (l);
       report_error ("%s: %s", name, temp ? temp : "");  /* XXX was value not "" */
       FREE (temp);
       dispose_words (l);
     }
   else if (check_null == 0)
     report_error (_("%s: parameter not set"), name);
   else
     report_error (_("%s: parameter null or not set"), name);
   /* Free the data we have allocated during this expansion, since we
      are about to longjmp out. */
   free (name);
   FREE (value);
 }
References _, dispose_words(), EXECUTION_FAILURE, expand_string(), FREE, free, l, report_error(), set_exit_status(), string_list(), and value.
Referenced by parameter_brace_expand().
parameter_brace_expand_indir()
static WORD_DESC* parameter_brace_expand_indir (char * name, int var_is_special, int quoted, int pflags, int * quoted_dollar_atp, int * contains_dollar_at) static
Definition at line 7628 of file subst.c.
 {
   char *t;
   WORD_DESC *w;
   SHELL_VAR *v;
   /* See if it's a nameref first, behave in ksh93-compatible fashion.
      There is at least one incompatibility: given ${!foo[0]} where foo=bar,
      bash performs an indirect lookup on foo[0] and expands the result;
      ksh93 expands bar[0].  We could do that here -- there are enough usable
      primitives to do that -- but do not at this point. */
   if (var_is_special == 0 && (v = find_variable_last_nameref (name, 0)))
     {
       if (nameref_p (v) && (t = nameref_cell (v)) && *t)
     {
       w = alloc_word_desc ();
       w->word = savestring (t);
       w->flags = 0;
       return w;
     }
     }
   /* An indirect reference to a positional parameter or a special parameter
      is ok.  Indirect references to array references, as explained above, are
      ok (currently).  Only references to unset variables are errors at this
      point. */
   if (legal_identifier (name) && v == 0)
     {
       report_error (_("%s: invalid indirect expansion"), name);
       w = alloc_word_desc ();
       w->word = &expand_param_error;
       w->flags = 0;
       return (w);
     }
   t = parameter_brace_find_indir (name, var_is_special, quoted, 0);
   chk_atstar (t, quoted, pflags, quoted_dollar_atp, contains_dollar_at);
 #if defined (ARRAY_VARS)
   /* Array references to unset variables are also an error */
   if (t == 0 && valid_array_reference (name, 0))
     {
       v = array_variable_part (name, 0, (char **)0, (int *)0);
       if (v == 0)
     {
       report_error (_("%s: invalid indirect expansion"), name);
       w = alloc_word_desc ();
       w->word = &expand_param_error;
       w->flags = 0;
       return (w);
     }
       else
         return (WORD_DESC *)NULL;
     }
 #endif
   if (t == 0)
     return (WORD_DESC *)NULL;
   if (valid_brace_expansion_word (t, SPECIAL_VAR (t, 0)) == 0)
     {
       report_error (_("%s: invalid variable name"), t);
       free (t);
       w = alloc_word_desc ();
       w->word = &expand_param_error;
       w->flags = 0;
       return (w);
     }
   w = parameter_brace_expand_word (t, SPECIAL_VAR(t, 0), quoted, pflags, 0);
   free (t);
   return w;
 }
References _, alloc_word_desc(), chk_atstar(), expand_param_error, find_variable_last_nameref(), free, legal_identifier(), nameref_cell, nameref_p, NULL, parameter_brace_expand_word(), parameter_brace_find_indir(), report_error(), savestring(), SPECIAL_VAR, t, valid_brace_expansion_word(), and w.
Referenced by parameter_brace_expand().
parameter_brace_expand_length()
static intmax_t parameter_brace_expand_length (char * name) static
Definition at line 7987 of file subst.c.
 {
   char *t, *newname;
   intmax_t number, arg_index;
   WORD_LIST *list;
   SHELL_VAR *var;
   var = (SHELL_VAR *)NULL;
   if (name[1] == '\0')          /* ${#} */
     number = number_of_args ();
   else if (DOLLAR_AT_STAR (name[1]) && name[2] == '\0') /* ${#@}, ${#*} */
     number = number_of_args ();
   else if ((sh_syntaxtab[(unsigned char) name[1]] & CSPECVAR) && name[2] == '\0')
     {
       /* Take the lengths of some of the shell's special parameters. */
       switch (name[1])
     {
     case '-':
       t = which_set_flags ();
       break;
     case '?':
       t = itos (last_command_exit_value);
       break;
     case '$':
       t = itos (dollar_dollar_pid);
       break;
     case '!':
       if (last_asynchronous_pid == NO_PID)
         t = (char *)NULL;   /* XXX - error if set -u set? */
       else
         t = itos (last_asynchronous_pid);
       break;
     case '#':
       t = itos (number_of_args ());
       break;
     }
       number = STRLEN (t);
       FREE (t);
     }
 #if defined (ARRAY_VARS)
   else if (valid_array_reference (name + 1, 0))
     number = array_length_reference (name + 1);
 #endif /* ARRAY_VARS */
   else
     {
       number = 0;
       if (legal_number (name + 1, &arg_index))      /* ${#1} */
     {
       t = get_dollar_var_value (arg_index);
       if (t == 0 && unbound_vars_is_error)
         return INTMAX_MIN;
       number = MB_STRLEN (t);
       FREE (t);
     }
 #if defined (ARRAY_VARS)
       else if ((var = find_variable (name + 1)) && (invisible_p (var) == 0) && (array_p (var) || assoc_p (var)))
     {
       if (assoc_p (var))
         t = assoc_reference (assoc_cell (var), "0");
       else
         t = array_reference (array_cell (var), 0);
       if (t == 0 && unbound_vars_is_error)
         return INTMAX_MIN;
       number = MB_STRLEN (t);
     }
 #endif
       /* Fast path for the common case of taking the length of a non-dynamic
      scalar variable value. */
       else if ((var || (var = find_variable (name + 1))) &&
             invisible_p (var) == 0 &&
         array_p (var) == 0 && assoc_p (var) == 0 &&
         var->dynamic_value == 0)
     number = value_cell (var) ? MB_STRLEN (value_cell (var)) : 0;
       else if (var == 0 && unbound_vars_is_error == 0)
     number = 0;
       else              /* ${#PS1} */
     {
       newname = savestring (name);
       newname[0] = '$';
       list = expand_string (newname, Q_DOUBLE_QUOTES);
       t = list ? string_list (list) : (char *)NULL;
       free (newname);
       if (list)
         dispose_words (list);
       number = t ? MB_STRLEN (t) : 0;
       FREE (t);
     }
     }
   return (number);
 }
References array_cell, array_p, assoc_cell, assoc_p, CSPECVAR, dispose_words(), DOLLAR_AT_STAR, dollar_dollar_pid, expand_string(), find_variable(), FREE, free, get_dollar_var_value(), INTMAX_MIN, invisible_p, itos(), last_asynchronous_pid, last_command_exit_value, legal_number(), list(), MB_STRLEN, NO_PID, NULL, number(), number_of_args(), Q_DOUBLE_QUOTES, savestring(), sh_syntaxtab, string_list(), STRLEN, t, unbound_vars_is_error, value_cell, and which_set_flags().
Referenced by parameter_brace_expand().
parameter_brace_expand_rhs()
static WORD_DESC* parameter_brace_expand_rhs (char * name, char * value, int op, int quoted, int pflags, int * qdollaratp, int * hasdollarat) static
Definition at line 7712 of file subst.c.
 {
   WORD_DESC *w;
   WORD_LIST *l, *tl;
   char *t, *t1, *temp, *vname, *newval;
   int l_hasdollat, sindex, arrayref;
   SHELL_VAR *v;
   array_eltstate_t es;
 /*itrace("parameter_brace_expand_rhs: %s:%s pflags = %d", name, value, pflags);*/
   /* If the entire expression is between double quotes, we want to treat
      the value as a double-quoted string, with the exception that we strip
      embedded unescaped double quotes (for sh backwards compatibility). */
   if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && *value)
     {
       sindex = 0;
       temp = string_extract_double_quoted (value, &sindex, SX_STRIPDQ);
     }
   else
     temp = value;
   w = alloc_word_desc ();
   l_hasdollat = 0;
   l = *temp ? expand_string_for_rhs (temp, quoted, op, pflags, &l_hasdollat, (int *)NULL)
         : (WORD_LIST *)0;
   if (hasdollarat)
     *hasdollarat = l_hasdollat || (l && l->next);
   if (temp != value)
     free (temp);
   /* list_string takes multiple CTLNULs and turns them into an empty word
      with W_SAWQUOTEDNULL set. Turn it back into a single CTLNUL for the
      rest of this function and the caller. */
   for (tl = l; tl; tl = tl->next)
     {
       if (tl->word && (tl->word->word == 0 || tl->word->word[0] == 0) &&
         (tl->word->flags | W_SAWQUOTEDNULL))
     {
       t = make_quoted_char ('\0');
       FREE (tl->word->word);
       tl->word->word = t;
       tl->word->flags |= W_QUOTED|W_HASQUOTEDNULL;
       tl->word->flags &= ~W_SAWQUOTEDNULL;
     }
     }
   if (l)
     {
       /* If l->next is not null, we know that TEMP contained "$@", since that
      is the only expansion that creates more than one word. */
       if (qdollaratp && ((l_hasdollat && quoted) || l->next))
     {
 /*itrace("parameter_brace_expand_rhs: %s:%s: l != NULL, set *qdollaratp", name, value);*/
       *qdollaratp = 1;
     }
       /* The expansion of TEMP returned something.  We need to treat things
       slightly differently if L_HASDOLLAT is non-zero.  If we have "$@",
       the individual words have already been quoted.  We need to turn them
       into a string with the words separated by the first character of
       $IFS without any additional quoting, so string_list_dollar_at won't
       do the right thing.  If IFS is null, we want "$@" to split into
       separate arguments, not be concatenated, so we use string_list_internal
       and mark the word to be split on spaces later.  We use
       string_list_dollar_star for "$@" otherwise. */
       if (l->next && ifs_is_null)
     {
       temp = string_list_internal (l, " ");
       w->flags |= W_SPLITSPACE;
     }
       else if (l_hasdollat || l->next)
     temp = string_list_dollar_star (l, quoted, 0);
       else
     {
       temp = string_list (l);
       if (temp && (QUOTED_NULL (temp) == 0) && (l->word->flags & W_SAWQUOTEDNULL))
         w->flags |= W_SAWQUOTEDNULL;    /* XXX */
     }
       /* If we have a quoted null result (QUOTED_NULL(temp)) and the word is
      a quoted null (l->next == 0 && QUOTED_NULL(l->word->word)), the
      flags indicate it (l->word->flags & W_HASQUOTEDNULL), and the
      expansion is quoted (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
      (which is more paranoia than anything else), we need to return the
      quoted null string and set the flags to indicate it. */
       if (l->next == 0 && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && QUOTED_NULL (temp) && QUOTED_NULL (l->word->word) && (l->word->flags & W_HASQUOTEDNULL))
     {
       w->flags |= W_HASQUOTEDNULL;
 /*itrace("parameter_brace_expand_rhs (%s:%s): returning quoted null, turning off qdollaratp", name, value);*/
       /* If we return a quoted null with L_HASDOLLARAT, we either have a
          construct like "${@-$@}" or "${@-${@-$@}}" with no positional
          parameters or a quoted expansion of "$@" with $1 == ''.  In either
          case, we don't want to enable special handling of $@. */
       if (qdollaratp && l_hasdollat)
         *qdollaratp = 0;
     }
       dispose_words (l);
     }
   else if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) && l_hasdollat)
     {
       /* Posix interp 221 changed the rules on this.  The idea is that
      something like "$xxx$@" should expand the same as "${foo-$xxx$@}"
      when foo and xxx are unset.  The problem is that it's not in any
      way backwards compatible and few other shells do it.  We're eventually
      going to try and split the difference (heh) a little bit here. */
       /* l_hasdollat == 1 means we saw a quoted dollar at.  */
       /* The brace expansion occurred between double quotes and there was
      a $@ in TEMP.  It does not matter if the $@ is quoted, as long as
      it does not expand to anything.  In this case, we want to return
      a quoted empty string.  Posix interp 888 */
       temp = make_quoted_char ('\0');
       w->flags |= W_HASQUOTEDNULL;
 /*itrace("parameter_brace_expand_rhs (%s:%s): returning quoted null", name, value);*/
     }
   else
     temp = (char *)NULL;
   if (op == '-' || op == '+')
     {
       w->word = temp;
       return w;
     }
   /* op == '=' */
   t1 = temp ? dequote_string (temp) : savestring ("");
   free (temp);
   /* bash-4.4/5.0 */
   vname = name;
   if (*name == '!' &&
       (legal_variable_starter ((unsigned char)name[1]) || DIGIT (name[1]) || VALID_INDIR_PARAM (name[1])))
     {
       vname = parameter_brace_find_indir (name + 1, SPECIAL_VAR (name, 1), quoted, 1);
       if (vname == 0 || *vname == 0)
     {
       report_error (_("%s: invalid indirect expansion"), name);
       free (vname);
       free (t1);
       dispose_word (w);
       return &expand_wdesc_error;
     }
       if (legal_identifier (vname) == 0)
     {
       report_error (_("%s: invalid variable name"), vname);
       free (vname);
       free (t1);
       dispose_word (w);
       return &expand_wdesc_error;
     }
     }
   arrayref = 0;
 #if defined (ARRAY_VARS)
   if (valid_array_reference (vname, 0))
     {
       init_eltstate (&es);
       v = assign_array_element (vname, t1, ASS_ALLOWALLSUB, &es);
       arrayref = 1;
       newval = es.value;
     }
   else
 #endif /* ARRAY_VARS */
   v = bind_variable (vname, t1, 0);
   if (v == 0 || readonly_p (v) || noassign_p (v))   /* expansion error  */
     {
       if ((v == 0 || readonly_p (v)) && interactive_shell == 0 && posixly_correct)
     {
       last_command_exit_value = EXECUTION_FAILURE;
       exp_jump_to_top_level (FORCE_EOF);
     }
       else
     {
       if (vname != name)
         free (vname);
       last_command_exit_value = EX_BADUSAGE;
       exp_jump_to_top_level (DISCARD);
     }
     }
   stupidly_hack_special_variables (vname);
   /* "In all cases, the final value of parameter shall be substituted." */
   if (shell_compatibility_level > 51)
     {
       FREE (t1);
 #if defined (ARRAY_VARS)
       if (arrayref)
     {
       t1 = newval;
       flush_eltstate (&es);
     }
       else
         t1 = get_variable_value (v);
 #else
       t1 = value_cell (v);
 #endif
     }
   if (vname != name)
     free (vname);
   /* From Posix group discussion Feb-March 2010.  Issue 7 0000221 */
   /* If we are double-quoted or if we are not going to be performing word
      splitting, we want to quote the value we return appropriately, like
      the other expansions this function handles. */
   w->word = (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) ? quote_string (t1) : quote_escapes (t1);
   /* If we have something that's non-null, but not a quoted null string,
      and we're not going to be performing word splitting (we know we're not
      because the operator is `='), we can forget we saw a quoted null. */
   if (w->word && w->word[0] && QUOTED_NULL (w->word) == 0)
     w->flags &= ~W_SAWQUOTEDNULL;
   /* If we convert a null string into a quoted null, make sure the caller
      knows it. */
   if ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) && QUOTED_NULL (w->word))
     w->flags |= W_HASQUOTEDNULL;
   return w;
 }
References _, alloc_word_desc(), ASS_ALLOWALLSUB, bind_variable(), dequote_string(), DIGIT, DISCARD, dispose_word(), dispose_words(), EX_BADUSAGE, EXECUTION_FAILURE, exp_jump_to_top_level(), expand_string_for_rhs(), expand_wdesc_error, FORCE_EOF, FREE, free, get_variable_value(), ifs_is_null, interactive_shell, l, last_command_exit_value, legal_identifier(), legal_variable_starter, make_quoted_char(), noassign_p, NULL, parameter_brace_find_indir(), posixly_correct, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_string(), QUOTED_NULL, readonly_p, report_error(), savestring(), shell_compatibility_level, SPECIAL_VAR, string_extract_double_quoted(), string_list(), string_list_dollar_star(), string_list_internal(), stupidly_hack_special_variables(), SX_STRIPDQ, t, t1, tl, VALID_INDIR_PARAM, element_state::value, value, value_cell, w, W_HASQUOTEDNULL, W_QUOTED, W_SAWQUOTEDNULL, and W_SPLITSPACE.
Referenced by parameter_brace_expand().
parameter_brace_expand_word()
static WORD_DESC* parameter_brace_expand_word (char * name, int var_is_special, int quoted, int pflags, array_eltstate_t * estatep) static
Definition at line 7396 of file subst.c.
 {
   WORD_DESC *ret;
   char *temp, *tt;
   intmax_t arg_index;
   SHELL_VAR *var;
   int rflags;
   array_eltstate_t es;
   ret = 0;
   temp = 0;
   rflags = 0;
 #if defined (ARRAY_VARS)
   if (estatep)
     es = *estatep;  /* structure copy */
   else
     {
       init_eltstate (&es);
       es.ind = INTMAX_MIN;
     }
 #endif
   /* Handle multiple digit arguments, as in ${11}. */
   if (legal_number (name, &arg_index))
     {
       tt = get_dollar_var_value (arg_index);
       if (tt)
     temp = (*tt && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
           ? quote_string (tt)
           : quote_escapes (tt);
       else
         temp = (char *)NULL;
       FREE (tt);
     }
   else if (var_is_special)      /* ${@} */
     {
       int sindex;
       tt = (char *)xmalloc (2 + strlen (name));
       tt[sindex = 0] = '$';
       strcpy (tt + 1, name);
       ret = param_expand (tt, &sindex, quoted, (int *)NULL, (int *)NULL,
               (int *)NULL, (int *)NULL, pflags);
       /* Make sure we note that we saw a quoted null string and pass the flag back
      to the caller in addition to the value. */
       if ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) && STR_DOLLAR_AT_STAR (name) &&
       ret && ret->word && QUOTED_NULL (ret->word))
     ret->flags |= W_HASQUOTEDNULL;
       free (tt);
     }
 #if defined (ARRAY_VARS)
   else if (valid_array_reference (name, 0))
     {
 expand_arrayref:
       var = array_variable_part (name, 0, &tt, (int *)0);
       /* These are the cases where word splitting will not be performed */
       if (pflags & PF_ASSIGNRHS)
     {
       if (ALL_ELEMENT_SUB (tt[0]) && tt[1] == RBRACK)
         {
           /* Only treat as double quoted if array variable */
           if (var && (array_p (var) || assoc_p (var)))
         temp = array_value (name, quoted|Q_DOUBLE_QUOTES, AV_ASSIGNRHS, &es);
           else
         temp = array_value (name, quoted, 0, &es);
         }
       else
         temp = array_value (name, quoted, 0, &es);
     }
       /* Posix interp 888 */
       else if (pflags & PF_NOSPLIT2)
     {
       /* Special cases, then general case, for each of A[@], A[*], A[n] */
 #if defined (HANDLE_MULTIBYTE)
           if (tt[0] == '@' && tt[1] == RBRACK && var && quoted == 0 && ifs_is_set && ifs_is_null == 0 && ifs_firstc[0] != ' ')
 #else
       if (tt[0] == '@' && tt[1] == RBRACK && var && quoted == 0 && ifs_is_set && ifs_is_null == 0 && ifs_firstc != ' ')
 #endif
         temp = array_value (name, Q_DOUBLE_QUOTES, AV_ASSIGNRHS, &es);
       else if (tt[0] == '@' && tt[1] == RBRACK)
         temp = array_value (name, quoted, 0, &es);
       else if (tt[0] == '*' && tt[1] == RBRACK && expand_no_split_dollar_star && ifs_is_null)
         temp = array_value (name, Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT, 0, &es);
       else if (tt[0] == '*' && tt[1] == RBRACK)
         temp = array_value (name, quoted, 0, &es);
       else
         temp = array_value (name, quoted, 0, &es);
     }
       else if (tt[0] == '*' && tt[1] == RBRACK && expand_no_split_dollar_star && ifs_is_null)
     temp = array_value (name, Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT, 0, &es);
       else
     temp = array_value (name, quoted, 0, &es);
       if (es.subtype == 0 && temp)
     {
       temp = (*temp && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
             ? quote_string (temp)
             : quote_escapes (temp);
       rflags |= W_ARRAYIND;
     }
       /* Note that array[*] and array[@] expanded to a quoted null string by
      returning the W_HASQUOTEDNULL flag to the caller in addition to TEMP. */
       else if (es.subtype == 1 && temp && QUOTED_NULL (temp) && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
     rflags |= W_HASQUOTEDNULL;
       else if (es.subtype == 2 && temp && QUOTED_NULL (temp) && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
     rflags |= W_HASQUOTEDNULL;
       if (estatep)
     *estatep = es;  /* structure copy */
       else
     flush_eltstate (&es);
     }
 #endif
   else if (var = find_variable (name))
     {
       if (var_isset (var) && invisible_p (var) == 0)
     {
 #if defined (ARRAY_VARS)
       /* We avoid a memory leak by saving TT as the memory allocated by
          assoc_to_string or array_to_string and leaving it 0 otherwise,
          then freeing TT after quoting temp. */
       tt = (char *)NULL;
       if ((pflags & PF_ALLINDS) && assoc_p (var))
         tt = temp = assoc_empty (assoc_cell (var)) ? (char *)NULL : assoc_to_string (assoc_cell (var), " ", quoted);
       else if ((pflags & PF_ALLINDS) && array_p (var))
         tt = temp = array_empty (array_cell (var)) ? (char *)NULL : array_to_string (array_cell (var), " ", quoted);
       else if (assoc_p (var))
         temp = assoc_reference (assoc_cell (var), "0");
       else if (array_p (var))
         temp = array_reference (array_cell (var), 0);
       else
         temp = value_cell (var);
 #else
       temp = value_cell (var);
 #endif
       if (temp)
         temp = (*temp && (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)))
               ? quote_string (temp)
               : ((pflags & PF_ASSIGNRHS) ? quote_rhs (temp)
                          : quote_escapes (temp));
       FREE (tt);
     }
       else
     temp = (char *)NULL;
     }
   else if (var = find_variable_last_nameref (name, 0))
     {
       temp = nameref_cell (var);
 #if defined (ARRAY_VARS)
       /* Handle expanding nameref whose value is x[n] */
       if (temp && *temp && valid_array_reference (temp, 0))
     {
       name = temp;
       goto expand_arrayref;
     }
       else
 #endif
       /* y=2 ; typeset -n x=y; echo ${x} is not the same as echo ${2} in ksh */
       if (temp && *temp && legal_identifier (temp) == 0)
         {
       set_exit_status (EXECUTION_FAILURE);
       report_error (_("%s: invalid variable name for name reference"), temp);
       temp = &expand_param_error;
         }
       else
     temp = (char *)NULL;
     }
   else
     temp = (char *)NULL;
   if (ret == 0)
     {
       ret = alloc_word_desc ();
       ret->word = temp;
       ret->flags |= rflags;
     }
   return ret;
 }
References _, ALL_ELEMENT_SUB, alloc_word_desc(), array_cell, array_empty, array_p, assoc_cell, assoc_empty, assoc_p, AV_ASSIGNRHS, EXECUTION_FAILURE, expand_no_split_dollar_star, expand_param_error, find_variable(), find_variable_last_nameref(), word_desc::flags, FREE, free, get_dollar_var_value(), ifs_firstc, ifs_is_null, ifs_is_set, element_state::ind, INTMAX_MIN, invisible_p, legal_identifier(), legal_number(), nameref_cell, NULL, param_expand(), PF_ALLINDS, PF_ASSIGNRHS, PF_NOSPLIT2, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_rhs(), quote_string(), QUOTED_NULL, RBRACK, report_error(), set_exit_status(), STR_DOLLAR_AT_STAR, strcpy, strlen(), element_state::subtype, tt, value_cell, var_isset, W_ARRAYIND, W_HASQUOTEDNULL, word_desc::word, and xmalloc.
Referenced by param_expand(), parameter_brace_expand(), parameter_brace_expand_indir(), and parameter_brace_find_indir().
parameter_brace_find_indir()
static char* parameter_brace_find_indir (char * name, int var_is_special, int quoted, int find_nameref) static
Definition at line 7582 of file subst.c.
 {
   char *temp, *t;
   WORD_DESC *w;
   SHELL_VAR *v;
   int pflags, oldex;
   if (find_nameref && var_is_special == 0 && (v = find_variable_last_nameref (name, 0)) &&
       nameref_p (v) && (t = nameref_cell (v)) && *t)
     return (savestring (t));
   /* If var_is_special == 0, and name is not an array reference, this does
      more expansion than necessary.  It should really look up the variable's
      value and not try to expand it. */
   pflags = PF_IGNUNBOUND;
   /* Note that we're not going to be doing word splitting here */
   if (var_is_special)
     {
       pflags |= PF_ASSIGNRHS;   /* suppresses word splitting */
       oldex = expand_no_split_dollar_star;
       expand_no_split_dollar_star = 1;
     }
   w = parameter_brace_expand_word (name, var_is_special, quoted, pflags, 0);
   if (var_is_special)
     expand_no_split_dollar_star = oldex;
   t = w->word;
   /* Have to dequote here if necessary */
   if (t)
     {
       temp = ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) || var_is_special)
         ? dequote_string (t)
         : dequote_escapes (t);
       free (t);
       t = temp;
     }
   dispose_word_desc (w);
   return t;
 }
References dequote_escapes(), dequote_string(), dispose_word_desc(), expand_no_split_dollar_star, find_variable_last_nameref(), free, nameref_cell, nameref_p, parameter_brace_expand_word(), PF_ASSIGNRHS, PF_IGNUNBOUND, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, savestring(), t, and w.
Referenced by get_var_and_type(), parameter_brace_expand_indir(), and parameter_brace_expand_rhs().
parameter_brace_patsub()
static char* parameter_brace_patsub (char * varname, char * value, array_eltstate_t * estatep, char * patsub, int quoted, int pflags, int flags) static
Definition at line 9109 of file subst.c.
 {
   int vtype, mflags, starsub, delim;
   char *val, *temp, *pat, *rep, *p, *lpatsub, *tt, *oname;
   SHELL_VAR *v;
   if (value == 0)
     return ((char *)NULL);
   oname = this_command_name;
   this_command_name = varname;      /* error messages */
   vtype = get_var_and_type (varname, value, estatep, quoted, flags, &v, &val);
   if (vtype == -1)
     {
       this_command_name = oname;
       return ((char *)NULL);
     }
   starsub = vtype & VT_STARSUB;
   vtype &= ~VT_STARSUB;
   mflags = 0;
   /* PATSUB is never NULL when this is called. */
   if (*patsub == '/')
     {
       mflags |= MATCH_GLOBREP;
       patsub++;
     }
   /* Malloc this because expand_string_if_necessary or one of the expansion
      functions in its call chain may free it on a substitution error. */
   lpatsub = savestring (patsub);
   if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
     mflags |= MATCH_QUOTED;
   if (starsub)
     mflags |= MATCH_STARSUB;
   if (pflags & PF_ASSIGNRHS)
     mflags |= MATCH_ASSIGNRHS;
   /* If the pattern starts with a `/', make sure we skip over it when looking
      for the replacement delimiter. */
   delim = skip_to_delim (lpatsub, ((*patsub == '/') ? 1 : 0), "/", 0);
   if (lpatsub[delim] == '/')
     {
       lpatsub[delim] = 0;
       rep = lpatsub + delim + 1;
     }
   else
     rep = (char *)NULL;
   if (rep && *rep == '\0')
     rep = (char *)NULL;
   /* Perform the same expansions on the pattern as performed by the
      pattern removal expansions. */
   pat = getpattern (lpatsub, quoted, 1);
   if (rep)
     {
       /* We want to perform quote removal on the expanded replacement even if
      the entire expansion is double-quoted because the parser and string
      extraction functions treated quotes in the replacement string as
      special.  THIS IS NOT BACKWARDS COMPATIBLE WITH BASH-4.2. */
       if (shell_compatibility_level > 42 && patsub_replacement == 0)
     rep = expand_string_if_necessary (rep, quoted & ~(Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT), expand_string_unsplit);
       else if (shell_compatibility_level > 42 && patsub_replacement)
     rep = expand_string_for_patsub (rep, quoted & ~(Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT));
       /* This is the bash-4.2 code. */
       else if ((mflags & MATCH_QUOTED) == 0)
     rep = expand_string_if_necessary (rep, quoted, expand_string_unsplit);
       else
     rep = expand_string_to_string_internal (rep, quoted, expand_string_unsplit);
       /* Check whether or not to replace `&' in the replacement string after
      expanding it, since we want to treat backslashes quoting the `&'
      consistently. */
       if (patsub_replacement && rep && *rep && shouldexp_replacement (rep))
     mflags |= MATCH_EXPREP;
     }
   /* ksh93 doesn't allow the match specifier to be a part of the expanded
      pattern.  This is an extension.  Make sure we don't anchor the pattern
      at the beginning or end of the string if we're doing global replacement,
      though. */
   p = pat;
   if (mflags & MATCH_GLOBREP)
     mflags |= MATCH_ANY;
   else if (pat && pat[0] == '#')
     {
       mflags |= MATCH_BEG;
       p++;
     }
   else if (pat && pat[0] == '%')
     {
       mflags |= MATCH_END;
       p++;
     }
   else
     mflags |= MATCH_ANY;
   /* OK, we now want to substitute REP for PAT in VAL.  If
      flags & MATCH_GLOBREP is non-zero, the substitution is done
      everywhere, otherwise only the first occurrence of PAT is
      replaced.  The pattern matching code doesn't understand
      CTLESC quoting CTLESC and CTLNUL so we use the dequoted variable
      values passed in (VT_VARIABLE) so the pattern substitution
      code works right.  We need to requote special chars after
      we're done for VT_VARIABLE and VT_ARRAYMEMBER, and for the
      other cases if QUOTED == 0, since the posparams and arrays
      indexed by * or @ do special things when QUOTED != 0. */
   switch (vtype)
     {
     case VT_VARIABLE:
     case VT_ARRAYMEMBER:
       temp = pat_subst (val, p, rep, mflags);
       if (vtype == VT_VARIABLE)
     FREE (val);
       if (temp)
     {
       tt = (mflags & MATCH_QUOTED) ? quote_string (temp) : quote_escapes (temp);
       free (temp);
       temp = tt;
     }
       break;
     case VT_POSPARMS:
       /* This does the right thing for the case where we are not performing
      word splitting. MATCH_STARSUB restricts it to ${* /foo/bar}, and
      pos_params_pat_subst/string_list_pos_params will do the right thing
      in turn for the case where ifs_is_null. Posix interp 888 */
       if ((pflags & PF_NOSPLIT2) && (mflags & MATCH_STARSUB))
         mflags |= MATCH_ASSIGNRHS;
       temp = pos_params_pat_subst (val, p, rep, mflags);
       if (temp && quoted == 0 && ifs_is_null)
     {
       /* Posix interp 888 */
     }
       else if (temp && quoted == 0 && (pflags & PF_ASSIGNRHS))
     {
       /* Posix interp 888 */
     }
       else if (temp && (mflags & MATCH_QUOTED) == 0)
     {
       tt = quote_escapes (temp);
       free (temp);
       temp = tt;
     }
       break;
 #if defined (ARRAY_VARS)
     case VT_ARRAYVAR:
       /* If we are expanding in a context where word splitting will not be
      performed, treat as quoted.  This changes how ${A[*]} will be
      expanded to make it identical to $*. */
       if ((mflags & MATCH_STARSUB) && (mflags & MATCH_ASSIGNRHS) && ifs_is_null)
     mflags |= MATCH_QUOTED;     /* Posix interp 888 */
       /* these eventually call string_list_pos_params */
       if (assoc_p (v))
     temp = assoc_patsub (assoc_cell (v), p, rep, mflags);
       else
     temp = array_patsub (array_cell (v), p, rep, mflags);
       if (temp && quoted == 0 && ifs_is_null)
     {
       /* Posix interp 888 */
     }
       else if (temp && (mflags & MATCH_QUOTED) == 0)
     {
       tt = quote_escapes (temp);
       free (temp);
       temp = tt;
     }
       break;
 #endif
     }
   FREE (pat);
   FREE (rep);
   free (lpatsub);
   this_command_name = oname;
   return temp;
 }
References array_cell, assoc_cell, assoc_p, expand_string_for_patsub(), expand_string_if_necessary(), expand_string_to_string_internal(), expand_string_unsplit(), flags, FREE, free, get_var_and_type(), getpattern(), ifs_is_null, MATCH_ANY, MATCH_ASSIGNRHS, MATCH_BEG, MATCH_END, MATCH_EXPREP, MATCH_GLOBREP, MATCH_QUOTED, MATCH_STARSUB, NULL, p, pat, pat_subst(), patsub_replacement, PF_ASSIGNRHS, PF_NOSPLIT2, pos_params_pat_subst(), Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_string(), savestring(), shell_compatibility_level, shouldexp_replacement(), skip_to_delim(), this_command_name, tt, val, value, VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, VT_STARSUB, and VT_VARIABLE.
Referenced by parameter_brace_expand().
parameter_brace_remove_pattern()
static char* parameter_brace_remove_pattern (char * varname, char * value, array_eltstate_t * estatep, char * patstr, int rtype, int quoted, int flags) static
Definition at line 5863 of file subst.c.
 {
   int vtype, patspec, starsub;
   char *temp1, *val, *pattern, *oname;
   SHELL_VAR *v;
   if (value == 0)
     return ((char *)NULL);
   oname = this_command_name;
   this_command_name = varname;
   vtype = get_var_and_type (varname, value, estatep, quoted, flags, &v, &val);
   if (vtype == -1)
     {
       this_command_name = oname;
       return ((char *)NULL);
     }
   starsub = vtype & VT_STARSUB;
   vtype &= ~VT_STARSUB;
   patspec = getpatspec (rtype, patstr);
   if (patspec == RP_LONG_LEFT || patspec == RP_LONG_RIGHT)
     patstr++;
   /* Need to pass getpattern newly-allocated memory in case of expansion --
      the expansion code will free the passed string on an error. */
   temp1 = savestring (patstr);
   pattern = getpattern (temp1, quoted, 1);
   free (temp1);
   temp1 = (char *)NULL;     /* shut up gcc */
   switch (vtype)
     {
     case VT_VARIABLE:
     case VT_ARRAYMEMBER:
       temp1 = remove_pattern (val, pattern, patspec);
       if (vtype == VT_VARIABLE)
     FREE (val);
       if (temp1)
     {
       val = (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
             ? quote_string (temp1)
             : quote_escapes (temp1);
       free (temp1);
       temp1 = val;
     }
       break;
 #if defined (ARRAY_VARS)
     case VT_ARRAYVAR:
       temp1 = array_remove_pattern (v, pattern, patspec, starsub, quoted);
       if (temp1 && ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0))
     {
       val = quote_escapes (temp1);
       free (temp1);
       temp1 = val;
     }
       break;
 #endif
     case VT_POSPARMS:
       temp1 = parameter_list_remove_pattern (varname[0], pattern, patspec, quoted);
       if (temp1 && quoted == 0 && ifs_is_null)
     {
       /* Posix interp 888 */
     }
       else if (temp1 && ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0))
     {
       val = quote_escapes (temp1);
       free (temp1);
       temp1 = val;
     }
       break;
     }
   this_command_name = oname;
   FREE (pattern);
   return temp1;
 }
References flags, FREE, free, get_var_and_type(), getpatspec(), getpattern(), ifs_is_null, NULL, parameter_list_remove_pattern(), pattern, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_string(), remove_pattern(), RP_LONG_LEFT, RP_LONG_RIGHT, savestring(), this_command_name, val, value, VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, VT_STARSUB, and VT_VARIABLE.
Referenced by parameter_brace_expand().
parameter_brace_substring()
static char* parameter_brace_substring (char * varname, char * value, array_eltstate_t * estatep, char * substr, int quoted, int pflags, int flags) static
Definition at line 8788 of file subst.c.
 {
   intmax_t e1, e2;
   int vtype, r, starsub;
   char *temp, *val, *tt, *oname;
   SHELL_VAR *v;
   if (value == 0 && ((varname[0] != '@' && varname[0] != '*') || varname[1]))
     return ((char *)NULL);
   oname = this_command_name;
   this_command_name = varname;
   vtype = get_var_and_type (varname, value, estatep, quoted, flags, &v, &val);
   if (vtype == -1)
     {
       this_command_name = oname;
       return ((char *)NULL);
     }
   starsub = vtype & VT_STARSUB;
   vtype &= ~VT_STARSUB;
   r = verify_substring_values (v, val, substr, vtype, &e1, &e2);
   this_command_name = oname;
   if (r <= 0)
     {
       if (vtype == VT_VARIABLE)
     FREE (val);
       return ((r == 0) ? &expand_param_error : (char *)NULL);
     }
   switch (vtype)
     {
     case VT_VARIABLE:
     case VT_ARRAYMEMBER:
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1)
     tt = mb_substring (val, e1, e2);
       else
 #endif
       tt = substring (val, e1, e2);
       if (vtype == VT_VARIABLE)
     FREE (val);
       if (quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT))
     temp = quote_string (tt);
       else
     temp = tt ? quote_escapes (tt) : (char *)NULL;
       FREE (tt);
       break;
     case VT_POSPARMS:
     case VT_ARRAYVAR:
       if (vtype == VT_POSPARMS)
     tt = pos_params (varname, e1, e2, quoted, pflags);
 #if defined (ARRAY_VARS)
         /* assoc_subrange and array_subrange both call string_list_pos_params,
        so we can treat this case just like VT_POSPARAMS. */
       else if (assoc_p (v))
     /* we convert to list and take first e2 elements starting at e1th
        element -- officially undefined for now */
     tt = assoc_subrange (assoc_cell (v), e1, e2, starsub, quoted, pflags);
       else
     /* We want E2 to be the number of elements desired (arrays can be
        sparse, so verify_substring_values just returns the numbers
        specified and we rely on array_subrange to understand how to
        deal with them). */
     tt = array_subrange (array_cell (v), e1, e2, starsub, quoted, pflags);
 #endif
       /* We want to leave this alone in every case where pos_params/
      string_list_pos_params quotes the list members */
       if (tt && quoted == 0 && ifs_is_null)
     {
       temp = tt;    /* Posix interp 888 */
     }
       else if (tt && quoted == 0 && (pflags & PF_ASSIGNRHS))
     {
       temp = tt;    /* Posix interp 888 */
     }
       else if ((quoted & (Q_DOUBLE_QUOTES|Q_HERE_DOCUMENT)) == 0)
     {
       temp = tt ? quote_escapes (tt) : (char *)NULL;
       FREE (tt);
     }
       else
     temp = tt;
       break;
     default:
       temp = (char *)NULL;
     }
   return temp;
 }
References array_cell, assoc_cell, assoc_p, e1, e2, expand_param_error, flags, FREE, get_var_and_type(), ifs_is_null, MB_CUR_MAX, NULL, PF_ASSIGNRHS, pos_params(), Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_string(), substring(), this_command_name, tt, val, value, verify_substring_values(), VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, VT_STARSUB, and VT_VARIABLE.
Referenced by parameter_brace_expand().
parameter_brace_transform()
static char* parameter_brace_transform (char * varname, char * value, array_eltstate_t * estatep, char * xform, int rtype, int quoted, int pflags, int flags) static
Definition at line 8655 of file subst.c.
 {
   int vtype, xc, starsub;
   char *temp1, *val, *oname;
   SHELL_VAR *v;
   xc = xform[0];
   if (value == 0 && xc != 'A' && xc != 'a')
     return ((char *)NULL);
   oname = this_command_name;
   this_command_name = varname;
   vtype = get_var_and_type (varname, value, estatep, quoted, flags, &v, &val);
   if (vtype == -1)
     {
       this_command_name = oname;
       return ((char *)NULL);
     }
   if (xform[0] == 0 || valid_parameter_transform (xform) == 0)
     {
       this_command_name = oname;
       if (vtype == VT_VARIABLE)
     FREE (val);
       return (interactive_shell ? &expand_param_error : &expand_param_fatal);
     }
   starsub = vtype & VT_STARSUB;
   vtype &= ~VT_STARSUB;
   /* If we are asked to display the attributes of an unset variable, V will
      be NULL after the call to get_var_and_type. Double-check here. */
   if ((xc == 'a' || xc == 'A') && vtype == VT_VARIABLE && varname && v == 0)
     v = find_variable (varname);
   temp1 = (char *)NULL;     /* shut up gcc */
   switch (vtype)
     {
     case VT_VARIABLE:
     case VT_ARRAYMEMBER:
       temp1 = string_transform (xc, v, val);
       if (vtype == VT_VARIABLE)
     FREE (val);
       if (temp1)
     {
       val = (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
             ? quote_string (temp1)
             : quote_escapes (temp1);
       free (temp1);
       temp1 = val;
     }
       break;
 #if defined (ARRAY_VARS)
     case VT_ARRAYVAR:
       temp1 = array_transform (xc, v, starsub, quoted);
       if (temp1 && quoted == 0 && ifs_is_null)
     {
         /* Posix interp 888 */
     }
       else if (temp1 && ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0))
     {
       val = quote_escapes (temp1);
       free (temp1);
       temp1 = val;
     }
       break;
 #endif
     case VT_POSPARMS:
       temp1 = parameter_list_transform (xc, varname[0], quoted);
       if (temp1 && quoted == 0 && ifs_is_null)
     {
         /* Posix interp 888 */
     }
       else if (temp1 && ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) == 0))
     {
       val = quote_escapes (temp1);
       free (temp1);
       temp1 = val;
     }
       break;
     }
   this_command_name = oname;
   return temp1;
 }
References expand_param_error, expand_param_fatal, find_variable(), flags, FREE, free, get_var_and_type(), ifs_is_null, interactive_shell, NULL, parameter_list_transform(), Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_escapes(), quote_string(), string_transform(), this_command_name, val, valid_parameter_transform(), value, VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, VT_STARSUB, and VT_VARIABLE.
Referenced by parameter_brace_expand().
parameter_list_remove_pattern()
static char* parameter_list_remove_pattern (int itype, char * pattern, int patspec, int quoted) static
Definition at line 5813 of file subst.c.
 {
   char *ret;
   WORD_LIST *list;
   list = list_rest_of_args ();
   if (list == 0)
     return ((char *)NULL);
   ret = list_remove_pattern (list, pattern, patspec, itype, quoted);
   dispose_words (list);
   return (ret);
 }
References dispose_words(), list(), list_remove_pattern(), list_rest_of_args(), NULL, and pattern.
Referenced by parameter_brace_remove_pattern().
parameter_list_transform()
static char* parameter_list_transform (int xc, int itype, int quoted) static
Definition at line 8545 of file subst.c.
 {
   char *ret;
   WORD_LIST *list;
   list = list_rest_of_args ();
   if (list == 0)
     return ((char *)NULL);
   if (xc == 'A')
     ret = pos_params_assignment (list, itype, quoted);
   else
     ret = list_transform (xc, (SHELL_VAR *)0, list, itype, quoted);
   dispose_words (list);
   return (ret);
 }
References dispose_words(), list(), list_rest_of_args(), list_transform(), NULL, and pos_params_assignment().
Referenced by parameter_brace_transform().
PARAMS() [1/47]
static int quoted_strlen PARAMS ((char *)) static
PARAMS() [2/47]
static int unquoted_substring PARAMS ((char *, char *)) static
PARAMS() [3/47]
static char* parameter_brace_remove_pattern PARAMS ((char *, char *, array_eltstate_t *, char *, int, int, int)) static
PARAMS() [4/47]
static char* parameter_brace_transform PARAMS ((char *, char *, array_eltstate_t *, char *, int, int, int, int)) static
PARAMS() [5/47]
static char* parameter_brace_casemod PARAMS ((char *, char *, array_eltstate_t *, int, char *, int, int, int)) static
PARAMS() [6/47]
static int get_var_and_type PARAMS ((char *, char *, array_eltstate_t *, int, int, SHELL_VAR **, char **)) static
PARAMS() [7/47]
static char* pos_params_pat_subst PARAMS ((char *, char *, char *, int)) static
PARAMS() [8/47]
static char* remove_upattern PARAMS ((char *, char *, int)) static
PARAMS() [9/47]
static int match_upattern PARAMS ((char *, char *, int, char **, char **)) static
PARAMS() [10/47]
static char* variable_remove_pattern PARAMS ((char *, char *, int, int)) static
PARAMS() [11/47]
static WORD_DESC* parameter_brace_expand_rhs PARAMS ((char *, char *, int, int, int, int *, int *)) static
PARAMS() [12/47]
static char* extract_delimited_string PARAMS ((char *, int *, char *, char *, char *, int)) static
PARAMS() [13/47]
static char* string_extract PARAMS ((char *, int *, char *, int)) static
PARAMS() [14/47]
static char* string_extract_double_quoted PARAMS ((char *, int *, int)) static
PARAMS() [15/47]
static WORD_DESC* param_expand PARAMS ((char *, int *, int, int *, int *, int *, int *, int)) static
PARAMS() [16/47]
static char* extract_heredoc_dolbrace_string PARAMS ((char *, int *, int, int)) static
PARAMS() [17/47]
static WORD_DESC* parameter_brace_expand PARAMS ((char *, int *, int, int, int *, int *)) static
PARAMS() [18/47]
static char* expand_string_if_necessary PARAMS ((char *, int, EXPFUNC *)) static
PARAMS() [19/47]
static WORD_LIST* expand_string_for_pat PARAMS ((char *, int, int *, int *)) static
PARAMS() [20/47]
static char* quoted_substring PARAMS ((char *, int, int)) static
PARAMS() [21/47]
static int chk_atstar PARAMS ((char *, int, int, int *, int *)) static
PARAMS() [22/47]
static char* parameter_brace_find_indir PARAMS ((char *, int, int, int)) static
PARAMS() [23/47]
static WORD_DESC* parameter_brace_expand_word PARAMS ((char *, int, int, int, array_eltstate_t *)) static
PARAMS() [24/47]
static WORD_LIST* expand_string_for_rhs PARAMS ((char *, int, int, int, int *, int *)) static
PARAMS() [25/47]
static char* pos_params PARAMS ((char *, int, int, int, int)) static
PARAMS() [26/47]
static char* string_extract_verbatim PARAMS ((char *, size_t, int *, char *, int)) static
PARAMS() [27/47]
static int skip_double_quoted PARAMS ((char *, size_t, int, int)) static
PARAMS() [28/47]
static char* quote_escapes_internal PARAMS ((const char *, int)) static
PARAMS() [29/47]
static int skip_matched_pair PARAMS ((const char *, int, int, int, int)) static
PARAMS() [30/47]
static int skip_single_quoted PARAMS ((const char *, size_t, int, int)) inline static
PARAMS() [31/47]
static int do_assignment_internal PARAMS ((const WORD_DESC *, int)) static
PARAMS() [32/47]
static char* make_quoted_char PARAMS ((int)) static
PARAMS() [33/47]
static int unquoted_member PARAMS ((int, char *)) static
PARAMS() [34/47]
static char* parameter_list_remove_pattern PARAMS ((int, char *, int, int)) static
PARAMS() [35/47]
static char* parameter_list_transform PARAMS ((int, int, int)) static
PARAMS() [36/47]
static char* read_comsub PARAMS ((int, int, int, int *)) static
PARAMS() [37/47]
static char* string_transform PARAMS ((int, SHELL_VAR *, char *)) static
PARAMS() [38/47]
static char* list_transform PARAMS ((int, SHELL_VAR *, WORD_LIST *, int, int)) static
PARAMS() [39/47]
static char* optimize_cat_file PARAMS ((REDIRECT *, int, int, int *)) static
PARAMS() [40/47]
static char* string_var_assignment PARAMS ((SHELL_VAR *, char *)) static
PARAMS() [41/47]
static int verify_substring_values PARAMS ((SHELL_VAR *, char *, char *, int, intmax_t *, intmax_t *)) static
PARAMS() [42/47]
static WORD_LIST* call_expand_word_internal PARAMS ((WORD_DESC *, int, int, int *, int *)) static
PARAMS() [43/47]
static WORD_LIST* list_quote_escapes PARAMS ((WORD_LIST *)) static
PARAMS() [44/47]
static int do_assignment_statements PARAMS ((WORD_LIST *, char *, int)) static
PARAMS() [45/47]
static char* list_remove_pattern PARAMS ((WORD_LIST *, char *, int, int, int)) static
PARAMS() [46/47]
static WORD_LIST* glob_expand_word_list PARAMS ((WORD_LIST *, int)) static
PARAMS() [47/47]
static char* pos_params_assignment PARAMS ((WORD_LIST *, int, int)) static
pat_subst()
char* pat_subst (char * string, char * pat, char * rep, int mflags)
Definition at line 8927 of file subst.c.
 {
   char *ret, *s, *e, *str, *rstr, *mstr, *send;
   int rptr, mtype, rxpand, mlen;
   size_t rsize, l, replen, rslen;
   DECLARE_MBSTATE;
   if (string == 0)
     return (savestring (""));
   mtype = mflags & MATCH_TYPEMASK;
   rxpand = mflags & MATCH_EXPREP;
   /* Special cases:
    *    1.  A null pattern with mtype == MATCH_BEG means to prefix STRING
    *        with REP and return the result.
    *    2.  A null pattern with mtype == MATCH_END means to append REP to
    *        STRING and return the result.
    *    3.  A null STRING with a matching pattern means to append REP to
    *        STRING and return the result.
    *
    * These process `&' in the replacement string, like `sed' does when
    * presented with a BRE of `^' or `$'.
    */
   if ((pat == 0 || *pat == 0) && (mtype == MATCH_BEG || mtype == MATCH_END))
     {
       rstr = (mflags & MATCH_EXPREP) ? strcreplace (rep, '&', "", 2) : rep;
       rslen = STRLEN (rstr);
       l = STRLEN (string);
       ret = (char *)xmalloc (rslen + l + 2);
       if (rslen == 0)
     strcpy (ret, string);
       else if (mtype == MATCH_BEG)
     {
       strcpy (ret, rstr);
       strcpy (ret + rslen, string);
     }
       else
     {
       strcpy (ret, string);
       strcpy (ret + l, rstr);
     }
       if (rstr != rep)
     free (rstr);
       return (ret);
     }
   else if (*string == 0 && (match_pattern (string, pat, mtype, &s, &e) != 0))
     return (mflags & MATCH_EXPREP) ? strcreplace (rep, '&', "", 2)
                    : (rep ? savestring (rep) : savestring (""));
   ret = (char *)xmalloc (rsize = 64);
   ret[0] = '\0';
   send = string + strlen (string);
   for (replen = STRLEN (rep), rptr = 0, str = string; *str;)
     {
       if (match_pattern (str, pat, mtype, &s, &e) == 0)
     break;
       l = s - str;
       if (rep && rxpand)
         {
       int x;
       mlen = e - s;
       mstr = xmalloc (mlen + 1);
       for (x = 0; x < mlen; x++)
         mstr[x] = s[x];
       mstr[mlen] = '\0';
       rstr = strcreplace (rep, '&', mstr, 2);
       free (mstr);
       rslen = strlen (rstr);
         }
       else
     {
       rstr = rep;
       rslen = replen;
     }
       RESIZE_MALLOCED_BUFFER (ret, rptr, (l + rslen), rsize, 64);
       /* OK, now copy the leading unmatched portion of the string (from
      str to s) to ret starting at rptr (the current offset).  Then copy
      the replacement string at ret + rptr + (s - str).  Increment
      rptr (if necessary) and str and go on. */
       if (l)
     {
       strncpy (ret + rptr, str, l);
       rptr += l;
     }
       if (replen)
     {
       strncpy (ret + rptr, rstr, rslen);
       rptr += rslen;
     }
       str = e;      /* e == end of match */
       if (rstr != rep)
     free (rstr);
       if (((mflags & MATCH_GLOBREP) == 0) || mtype != MATCH_ANY)
     break;
       if (s == e)
     {
       /* On a zero-length match, make sure we copy one character, since
          we increment one character to avoid infinite recursion. */
       char *p, *origp, *origs;
       size_t clen;
       RESIZE_MALLOCED_BUFFER (ret, rptr, locale_mb_cur_max, rsize, 64);
 #if defined (HANDLE_MULTIBYTE)
       p = origp = ret + rptr;
       origs = str;
       COPY_CHAR_P (p, str, send);
       rptr += p - origp;
       e += str - origs;
 #else
       ret[rptr++] = *str++;
       e++;      /* avoid infinite recursion on zero-length match */
 #endif
     }
     }
   /* Now copy the unmatched portion of the input string */
   if (str && *str)
     {
       l = send - str + 1;
       RESIZE_MALLOCED_BUFFER (ret, rptr, l, rsize, 64);
       strcpy (ret + rptr, str);
     }
   else
     ret[rptr] = '\0';
   return ret;
 }
References COPY_CHAR_P, DECLARE_MBSTATE, free, l, locale_mb_cur_max, MATCH_ANY, MATCH_BEG, MATCH_END, MATCH_EXPREP, MATCH_GLOBREP, match_pattern(), MATCH_TYPEMASK, p, pat, RESIZE_MALLOCED_BUFFER, s, savestring(), send(), str, strcpy, strcreplace(), strlen(), STRLEN, strncpy(), x, and xmalloc.
Referenced by parameter_brace_patsub(), and pos_params_pat_subst().
pos_params()
static char* pos_params (char * string, int start, int end, int quoted, int pflags) static
Definition at line 3765 of file subst.c.
 {
   WORD_LIST *save, *params, *h, *t;
   char *ret;
   int i;
   /* see if we can short-circuit.  if start == end, we want 0 parameters. */
   if (start == end)
     return ((char *)NULL);
   save = params = list_rest_of_args ();
   if (save == 0 && start > 0)
     return ((char *)NULL);
   if (start == 0)       /* handle ${@:0[:x]} specially */
     {
       t = make_word_list (make_word (dollar_vars[0]), params);
       save = params = t;
     }
   for (i = start ? 1 : 0; params && i < start; i++)
     params = params->next;
   if (params == 0)
     {
       dispose_words (save);
       return ((char *)NULL);
     }
   for (h = t = params; params && i < end; i++)
     {
       t = params;
       params = params->next;
     }
   t->next = (WORD_LIST *)NULL;
   ret = string_list_pos_params (string[0], h, quoted, pflags);
   if (t != params)
     t->next = params;
   dispose_words (save);
   return (ret);
 }
References dispose_words(), dollar_vars, end, h, i, if(), list_rest_of_args(), make_word(), make_word_list(), word_list::next, NULL, start, string_list_pos_params(), and t.
Referenced by parameter_brace_substring().
pos_params_assignment()
static char* pos_params_assignment (WORD_LIST * list, int itype, int quoted) static
Definition at line 8439 of file subst.c.
 {
   char *temp, *ret;
   /* first, we transform the list to quote each word. */
   temp = list_transform ('Q', (SHELL_VAR *)0, list, itype, quoted);
   ret = (char *)xmalloc (strlen (temp) + 8);
   strcpy (ret, "set -- ");
   strcpy (ret + 7, temp);
   free (temp);
   return ret;
 }
References free, list(), list_transform(), strcpy, strlen(), and xmalloc.
Referenced by parameter_list_transform().
pos_params_modcase()
static char* pos_params_modcase (char * string, char * pat, int modop, int mflags) static
Definition at line 9312 of file subst.c.
 {
   WORD_LIST *save, *params;
   WORD_DESC *w;
   char *ret;
   int pchar, qflags, pflags;
   save = params = list_rest_of_args ();
   if (save == 0)
     return ((char *)NULL);
   for ( ; params; params = params->next)
     {
       ret = sh_modcase (params->word->word, pat, modop);
       w = alloc_word_desc ();
       w->word = ret ? ret : savestring ("");
       dispose_word (params->word);
       params->word = w;
     }
   pchar = (mflags & MATCH_STARSUB) == MATCH_STARSUB ? '*' : '@';
   qflags = (mflags & MATCH_QUOTED) == MATCH_QUOTED ? Q_DOUBLE_QUOTES : 0;
   pflags = (mflags & MATCH_ASSIGNRHS) == MATCH_ASSIGNRHS ? PF_ASSIGNRHS : 0;
   /* If we are expanding in a context where word splitting will not be
      performed, treat as quoted.  This changes how $* will be expanded. */
   if (pchar == '*' && (mflags & MATCH_ASSIGNRHS) && ifs_is_null)
     qflags |= Q_DOUBLE_QUOTES;      /* Posix interp 888 */
   ret = string_list_pos_params (pchar, save, qflags, pflags);
   dispose_words (save);
   return (ret);
 }
References alloc_word_desc(), dispose_word(), dispose_words(), ifs_is_null, list_rest_of_args(), MATCH_ASSIGNRHS, MATCH_QUOTED, MATCH_STARSUB, word_list::next, NULL, pat, PF_ASSIGNRHS, Q_DOUBLE_QUOTES, savestring(), sh_modcase(), string_list_pos_params(), w, word_desc::word, and word_list::word.
Referenced by parameter_brace_casemod().
pos_params_pat_subst()
static char* pos_params_pat_subst (char * string, char * pat, char * rep, int mflags) static
Definition at line 9067 of file subst.c.
 {
   WORD_LIST *save, *params;
   WORD_DESC *w;
   char *ret;
   int pchar, qflags, pflags;
   save = params = list_rest_of_args ();
   if (save == 0)
     return ((char *)NULL);
   for ( ; params; params = params->next)
     {
       ret = pat_subst (params->word->word, pat, rep, mflags);
       w = alloc_word_desc ();
       w->word = ret ? ret : savestring ("");
       dispose_word (params->word);
       params->word = w;
     }
   pchar = (mflags & MATCH_STARSUB) == MATCH_STARSUB ? '*' : '@';
   qflags = (mflags & MATCH_QUOTED) == MATCH_QUOTED ? Q_DOUBLE_QUOTES : 0;
   pflags = (mflags & MATCH_ASSIGNRHS) == MATCH_ASSIGNRHS ? PF_ASSIGNRHS : 0;
   /* If we are expanding in a context where word splitting will not be
      performed, treat as quoted. This changes how $* will be expanded. */
   if (pchar == '*' && (mflags & MATCH_ASSIGNRHS) && expand_no_split_dollar_star && ifs_is_null)
     qflags |= Q_DOUBLE_QUOTES;      /* Posix interp 888 */
   ret = string_list_pos_params (pchar, save, qflags, pflags);
   dispose_words (save);
   return (ret);
 }
References alloc_word_desc(), dispose_word(), dispose_words(), expand_no_split_dollar_star, ifs_is_null, list_rest_of_args(), MATCH_ASSIGNRHS, MATCH_QUOTED, MATCH_STARSUB, word_list::next, NULL, pat, pat_subst(), PF_ASSIGNRHS, Q_DOUBLE_QUOTES, savestring(), string_list_pos_params(), w, word_desc::word, and word_list::word.
Referenced by parameter_brace_patsub().
quote_escapes()
char* quote_escapes (char * string) const
Definition at line 4719 of file subst.c.
 {
   return (quote_escapes_internal (string, 0));
 }
References quote_escapes_internal().
Referenced by list_quote_escapes(), param_expand(), parameter_brace_casemod(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), and parameter_brace_transform().
quote_escapes_internal()
static char* quote_escapes_internal (char * string, int flags) const static
Definition at line 4682 of file subst.c.
 {
   const char *s, *send;
   char *t, *result;
   size_t slen;
   int quote_spaces, skip_ctlesc, skip_ctlnul, nosplit;
   DECLARE_MBSTATE;
   slen = strlen (string);
   send = string + slen;
   quote_spaces = (ifs_value && *ifs_value == 0);
   nosplit = (flags & PF_NOSPLIT2);
   for (skip_ctlesc = skip_ctlnul = 0, s = ifs_value; s && *s; s++)
     {
       skip_ctlesc |= (nosplit == 0 && *s == CTLESC);
       skip_ctlnul |= (nosplit == 0 && *s == CTLNUL);
     }
   t = result = (char *)xmalloc ((slen * 2) + 1);
   s = string;
   while (*s)
     {
       if ((skip_ctlesc == 0 && *s == CTLESC) || (skip_ctlnul == 0 && *s == CTLNUL) || (quote_spaces && *s == ' '))
     *t++ = CTLESC;
       COPY_CHAR_P (t, s, send);
     }
   *t = '\0';
   return (result);
 }
References COPY_CHAR_P, CTLESC, CTLNUL, DECLARE_MBSTATE, flags, ifs_value, PF_NOSPLIT2, s, send(), string, strlen(), t, and xmalloc.
Referenced by quote_escapes(), and quote_rhs().
quote_list()
static WORD_LIST* quote_list (WORD_LIST * list) static
Definition at line 4931 of file subst.c.
 {
   register WORD_LIST *w;
   char *t;
   for (w = list; w; w = w->next)
     {
       t = w->word->word;
       w->word->word = quote_string (t);
       if (*t == 0)
     w->word->flags |= W_HASQUOTEDNULL;  /* XXX - turn on W_HASQUOTEDNULL here? */
       w->word->flags |= W_QUOTED;
       free (t);
     }
   return list;
 }
References free, list(), quote_string(), t, w, W_HASQUOTEDNULL, and W_QUOTED.
Referenced by expand_word_internal(), string_list_dollar_at(), and string_list_pos_params().
quote_rhs()
char* quote_rhs (char * string) const
Definition at line 4726 of file subst.c.
 {
   return (quote_escapes_internal (string, PF_NOSPLIT2));
 }
References PF_NOSPLIT2, and quote_escapes_internal().
Referenced by param_expand(), and parameter_brace_expand_word().
quote_string()
char* quote_string (char * string)
Definition at line 4844 of file subst.c.
 {
   register char *t;
   size_t slen;
   char *result, *send;
   if (*string == 0)
     {
       result = (char *)xmalloc (2);
       result[0] = CTLNUL;
       result[1] = '\0';
     }
   else
     {
       DECLARE_MBSTATE;
       slen = strlen (string);
       send = string + slen;
       result = (char *)xmalloc ((slen * 2) + 1);
       for (t = result; string < send; )
     {
       *t++ = CTLESC;
       COPY_CHAR_P (t, string, send);
     }
       *t = '\0';
     }
   return (result);
 }
References COPY_CHAR_P, CTLESC, CTLNUL, DECLARE_MBSTATE, send(), strlen(), t, and xmalloc.
Referenced by expand_word_internal(), param_expand(), parameter_brace_casemod(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), parameter_brace_transform(), and quote_list().
quote_string_for_repl()
static char* quote_string_for_repl (char * string, int flags) static
Definition at line 3925 of file subst.c.
 {
   size_t slen;
   char *result, *t;
   const char *s, *send;
   DECLARE_MBSTATE;
   slen = strlen (string);
   send = string + slen;
   result = (char *)xmalloc (slen * 2 + 1);
   if (string[0] == CTLESC && string[1] == 0)
     {
       result[0] = CTLESC;
       result[1] = '\0';
       return (result);
     }
   /* This is awkward. We want to translate CTLESC-\ to \\ if we will
      eventually send this string through strcreplace(), which we will do
      only if shouldexp_replacement() determines that there is something
      to replace. We can either make sure to escape backslashes here and
      have shouldexp_replacement() signal that we should send the string to
      strcreplace() if it sees an escaped backslash, or we can scan the
      string before copying it and turn CTLESC-\ into \\ only if we encounter
      a CTLESC-& or a &. This does the former and changes shouldexp_replacement().
      If we double the backslashes  here, we'll get doubled backslashes in any
      result that doesn't get passed to strcreplace(). */
   for (s = string, t = result; *s; )
     {
       /* This function's result has to be processed by strcreplace() */
       if (*s == CTLESC && (s[1] == '&' || s[1] == '\\'))
         {
           *t++ = '\\';
           s++;
           *t++ = *s++;
           continue;
         }
       /* Dequote it */
       if (*s == CTLESC)
         {
       s++;
       if (*s == '\0')
         break;
         }
       COPY_CHAR_P (t, s, send);
     }
   *t = '\0';
   return (result);
 }
References COPY_CHAR_P, CTLESC, DECLARE_MBSTATE, s, send(), strlen(), t, and xmalloc.
Referenced by expand_string_for_patsub().
read_comsub()
static char* read_comsub (int fd, int quoted, int flags, int * rflag) static
Definition at line 6784 of file subst.c.
 {
   char *istring, buf[COMSUB_PIPEBUF], *bufp;
   int c, tflag, skip_ctlesc, skip_ctlnul;
   int mb_cur_max;
   size_t istring_index;
   size_t istring_size;
   ssize_t bufn;
   int nullbyte;
 #if defined (HANDLE_MULTIBYTE)
   mbstate_t ps;
   wchar_t wc;
   size_t mblen;
   int i;
 #endif
   istring = (char *)NULL;
   istring_index = istring_size = bufn = tflag = 0;
   skip_ctlesc = ifs_cmap[CTLESC];
   skip_ctlnul = ifs_cmap[CTLNUL];
   mb_cur_max = MB_CUR_MAX;
   nullbyte = 0;
   /* Read the output of the command through the pipe. */
   while (1)
     {
       if (fd < 0)
     break;
       if (--bufn <= 0)
     {
       bufn = zread (fd, buf, sizeof (buf));
       if (bufn <= 0)
         break;
       bufp = buf;
     }
       c = *bufp++;
       if (c == 0)
     {
 #if 1
       if (nullbyte == 0)
         {
           internal_warning ("%s", _("command substitution: ignored null byte in input"));
           nullbyte = 1;
         }
 #endif
       continue;
     }
       /* Add the character to ISTRING, possibly after resizing it. */
       RESIZE_MALLOCED_BUFFER (istring, istring_index, mb_cur_max+1, istring_size, 512);
       /* This is essentially quote_string inline */
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) /* || c == CTLESC || c == CTLNUL */)
     istring[istring_index++] = CTLESC;
       else if ((flags & PF_ASSIGNRHS) && skip_ctlesc && c == CTLESC)
     istring[istring_index++] = CTLESC;
       /* Escape CTLESC and CTLNUL in the output to protect those characters
      from the rest of the word expansions (word splitting and globbing.)
      This is essentially quote_escapes inline. */
       else if (skip_ctlesc == 0 && c == CTLESC)
     istring[istring_index++] = CTLESC;
       else if ((skip_ctlnul == 0 && c == CTLNUL) || (c == ' ' && (ifs_value && *ifs_value == 0)))
     istring[istring_index++] = CTLESC;
 #if defined (HANDLE_MULTIBYTE)
       if ((locale_utf8locale && (c & 0x80)) ||
       (locale_utf8locale == 0 && mb_cur_max > 1 && (unsigned char)c > 127))
     {
       /* read a multibyte character from buf */
       /* punt on the hard case for now */
       memset (&ps, '\0', sizeof (mbstate_t));
       mblen = mbrtowc (&wc, bufp-1, bufn, &ps);
       if (MB_INVALIDCH (mblen) || mblen == 0 || mblen == 1)
         istring[istring_index++] = c;
       else
         {
           istring[istring_index++] = c;
           for (i = 0; i < mblen-1; i++)
         istring[istring_index++] = *bufp++;
           bufn -= mblen - 1;
         }
       continue;
     }
 #endif
       istring[istring_index++] = c;
     }
   if (istring)
     istring[istring_index] = '\0';
   /* If we read no output, just return now and save ourselves some
      trouble. */
   if (istring_index == 0)
     {
       FREE (istring);
       if (rflag)
     *rflag = tflag;
       return (char *)NULL;
     }
   /* Strip trailing newlines from the output of the command. */
   if (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES))
     {
       while (istring_index > 0)
     {
       if (istring[istring_index - 1] == '\n')
         {
           --istring_index;
           /* If the newline was quoted, remove the quoting char. */
           if (istring[istring_index - 1] == CTLESC)
         --istring_index;
         }
       else
         break;
     }
       istring[istring_index] = '\0';
     }
   else
     strip_trailing (istring, istring_index - 1, 1);
   if (rflag)
     *rflag = tflag;
   return istring;
 }
References _, buf, c, COMSUB_PIPEBUF, CTLESC, CTLNUL, fd, flags, FREE, i, ifs_cmap, ifs_value, internal_warning(), locale_utf8locale, MB_CUR_MAX, MB_INVALIDCH, mblen(), mbrtowc(), memset, NULL, PF_ASSIGNRHS, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, RESIZE_MALLOCED_BUFFER, strip_trailing(), and zread().
Referenced by command_substitute(), and optimize_cat_file().
remove_pattern()
static char* remove_pattern (char * param, char * pattern, int op) static
Definition at line 5290 of file subst.c.
 {
   char *xret;
   if (param == NULL)
     return (param);
   if (*param == '\0' || pattern == NULL || *pattern == '\0')    /* minor optimization */
     return (savestring (param));
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1)
     {
       wchar_t *ret, *oret;
       size_t n;
       wchar_t *wparam, *wpattern;
       mbstate_t ps;
       /* XXX - could optimize here by checking param and pattern for multibyte
      chars with mbsmbchar and calling remove_upattern. */
       n = xdupmbstowcs (&wpattern, NULL, pattern);
       if (n == (size_t)-1)
     {
       xret = remove_upattern (param, pattern, op);
       return ((xret == param) ? savestring (param) : xret);
     }
       n = xdupmbstowcs (&wparam, NULL, param);
       if (n == (size_t)-1)
     {
       free (wpattern);
       xret = remove_upattern (param, pattern, op);
       return ((xret == param) ? savestring (param) : xret);
     }
       oret = ret = remove_wpattern (wparam, n, wpattern, op);
       /* Don't bother to convert wparam back to multibyte string if nothing
      matched; just return copy of original string */
       if (ret == wparam)
         {
           free (wparam);
           free (wpattern);
           return (savestring (param));
         }
       free (wparam);
       free (wpattern);
       n = strlen (param);
       xret = (char *)xmalloc (n + 1);
       memset (&ps, '\0', sizeof (mbstate_t));
       n = wcsrtombs (xret, (const wchar_t **)&ret, n, &ps);
       xret[n] = '\0';       /* just to make sure */
       free (oret);
       return xret;
     }
   else
 #endif
     {
       xret = remove_upattern (param, pattern, op);
       return ((xret == param) ? savestring (param) : xret);
     }
 }
References free, MB_CUR_MAX, memset, n, NULL, param, pattern, remove_upattern(), savestring(), strlen(), wcsrtombs(), and xmalloc.
Referenced by list_remove_pattern(), and parameter_brace_remove_pattern().
remove_quoted_escapes()
char* remove_quoted_escapes (char * string)
Definition at line 4986 of file subst.c.
 {
   char *t;
   if (string)
     {
       t = dequote_escapes (string);
       strcpy (string, t);
       free (t);
     }
   return (string);
 }
References dequote_escapes(), free, strcpy, and t.
Referenced by command_substitute(), expand_word_internal(), and named_function_string().
remove_quoted_ifs()
char* remove_quoted_ifs (char * string)
Definition at line 5006 of file subst.c.
 {
   register size_t slen;
   register int i, j;
   char *ret, *send;
   DECLARE_MBSTATE;
   slen = strlen (string);
   send = string + slen;
   i = j = 0;
   ret = (char *)xmalloc (slen + 1);
   while (i < slen)
     {
       if (string[i] == CTLESC)
     {
       i++;
       if (string[i] == 0 || isifs (string[i]) == 0)
         ret[j++] = CTLESC;
       if (i == slen)
         break;
     }
       COPY_CHAR_I (ret, j, string, send, i);
     }
   ret[j] = '\0';
   return (ret);
 }
References COPY_CHAR_I, CTLESC, DECLARE_MBSTATE, i, isifs, j, send(), strlen(), and xmalloc.
Referenced by expand_word_internal().
remove_quoted_nulls()
char* remove_quoted_nulls (char * string)
Definition at line 5039 of file subst.c.
 {
   register size_t slen;
   register int i, j, prev_i;
   DECLARE_MBSTATE;
   if (strchr (string, CTLNUL) == 0)     /* XXX */
     return string;              /* XXX */
   slen = strlen (string);
   i = j = 0;
   while (i < slen)
     {
       if (string[i] == CTLESC)
     {
       /* Old code had j++, but we cannot assume that i == j at this
          point -- what if a CTLNUL has already been removed from the
          string?  We don't want to drop the CTLESC or recopy characters
          that we've already copied down. */
       i++;
       string[j++] = CTLESC;
       if (i == slen)
         break;
     }
       else if (string[i] == CTLNUL)
     {
       i++;
       continue;
     }
       prev_i = i;
       ADVANCE_CHAR (string, slen, i);       /* COPY_CHAR_I? */
       if (j < prev_i)
     {
       do string[j++] = string[prev_i++]; while (prev_i < i);
     }
       else
     j = i;
     }
   string[j] = '\0';
   return (string);
 }
References ADVANCE_CHAR, CTLESC, CTLNUL, DECLARE_MBSTATE, i, j, strchr(), string, and strlen().
Referenced by expand_prompt_string(), expand_string_assignment(), expand_string_for_patsub(), expand_string_unsplit(), expand_word_internal(), list_string(), and word_list_remove_quoted_nulls().
remove_upattern()
static char* remove_upattern (char * param, char * pattern, int op) static
Definition at line 5148 of file subst.c.
 {
   register size_t len;
   register char *end;
   register char *p, *ret, c;
   len = STRLEN (param);
   end = param + len;
   switch (op)
     {
       case RP_LONG_LEFT:    /* remove longest match at start */
     for (p = end; p >= param; p--)
       {
         c = *p; *p = '\0';
         if (strmatch (pattern, param, FNMATCH_EXTFLAG) != FNM_NOMATCH)
           {
         *p = c;
         return (savestring (p));
           }
         *p = c;
       }
     break;
       case RP_SHORT_LEFT:   /* remove shortest match at start */
     for (p = param; p <= end; p++)
       {
         c = *p; *p = '\0';
         if (strmatch (pattern, param, FNMATCH_EXTFLAG) != FNM_NOMATCH)
           {
         *p = c;
         return (savestring (p));
           }
         *p = c;
       }
     break;
       case RP_LONG_RIGHT:   /* remove longest match at end */
     for (p = param; p <= end; p++)
       {
         if (strmatch (pattern, p, FNMATCH_EXTFLAG) != FNM_NOMATCH)
           {
         c = *p; *p = '\0';
         ret = savestring (param);
         *p = c;
         return (ret);
           }
       }
     break;
       case RP_SHORT_RIGHT:  /* remove shortest match at end */
     for (p = end; p >= param; p--)
       {
         if (strmatch (pattern, p, FNMATCH_EXTFLAG) != FNM_NOMATCH)
           {
         c = *p; *p = '\0';
         ret = savestring (param);
         *p = c;
         return (ret);
           }
       }
     break;
     }
   return (param);   /* no match, return original string */
 }
References c, end, FNM_NOMATCH, FNMATCH_EXTFLAG, len, p, param, pattern, RP_LONG_LEFT, RP_LONG_RIGHT, RP_SHORT_LEFT, RP_SHORT_RIGHT, savestring(), STRLEN, and strmatch().
Referenced by remove_pattern().
separate_out_assignments()
static WORD_LIST* separate_out_assignments (WORD_LIST * tlist) static
Definition at line 12165 of file subst.c.
 {
   register WORD_LIST *vp, *lp;
   if (tlist == 0)
     return ((WORD_LIST *)NULL);
   if (subst_assign_varlist)
     dispose_words (subst_assign_varlist);   /* Clean up after previous error */
   subst_assign_varlist = (WORD_LIST *)NULL;
   vp = lp = tlist;
   /* Separate out variable assignments at the start of the command.
      Loop invariant: vp->next == lp
      Loop postcondition:
     lp = list of words left after assignment statements skipped
     tlist = original list of words
   */
   while (lp && (lp->word->flags & W_ASSIGNMENT))
     {
       vp = lp;
       lp = lp->next;
     }
   /* If lp != tlist, we have some initial assignment statements.
      We make SUBST_ASSIGN_VARLIST point to the list of assignment
      words and TLIST point to the remaining words.  */
   if (lp != tlist)
     {
       subst_assign_varlist = tlist;
       /* ASSERT(vp->next == lp); */
       vp->next = (WORD_LIST *)NULL; /* terminate variable list */
       tlist = lp;           /* remainder of word list */
     }
   /* vp == end of variable list */
   /* tlist == remainder of original word list without variable assignments */
   if (!tlist)
     /* All the words in tlist were assignment statements */
     return ((WORD_LIST *)NULL);
   /* ASSERT(tlist != NULL); */
   /* ASSERT((tlist->word->flags & W_ASSIGNMENT) == 0); */
   /* If the -k option is in effect, we need to go through the remaining
      words, separate out the assignment words, and place them on
      SUBST_ASSIGN_VARLIST. */
   if (place_keywords_in_env)
     {
       WORD_LIST *tp;    /* tp == running pointer into tlist */
       tp = tlist;
       lp = tlist->next;
       /* Loop Invariant: tp->next == lp */
       /* Loop postcondition: tlist == word list without assignment statements */
       while (lp)
     {
       if (lp->word->flags & W_ASSIGNMENT)
         {
           /* Found an assignment statement, add this word to end of
          subst_assign_varlist (vp). */
           if (!subst_assign_varlist)
         subst_assign_varlist = vp = lp;
           else
         {
           vp->next = lp;
           vp = lp;
         }
           /* Remove the word pointed to by LP from TLIST. */
           tp->next = lp->next;
           /* ASSERT(vp == lp); */
           lp->next = (WORD_LIST *)NULL;
           lp = tp->next;
         }
       else
         {
           tp = lp;
           lp = lp->next;
         }
     }
     }
   return (tlist);
 }
References dispose_words(), word_desc::flags, word_list::next, NULL, place_keywords_in_env, subst_assign_varlist, tp, vp, W_ASSIGNMENT, and word_list::word.
Referenced by expand_word_list_internal().
setifs()
void setifs (SHELL_VAR * v)
Definition at line 12006 of file subst.c.
 {
   char *t;
   unsigned char uc;
   ifs_var = v;
   ifs_value = (v && value_cell (v)) ? value_cell (v) : " \t\n";
   ifs_is_set = ifs_var != 0;
   ifs_is_null = ifs_is_set && (*ifs_value == 0);
   /* Should really merge ifs_cmap with sh_syntaxtab.  XXX - doesn't yet
      handle multibyte chars in IFS */
   memset (ifs_cmap, '\0', sizeof (ifs_cmap));
   for (t = ifs_value ; t && *t; t++)
     {
       uc = *t;
       ifs_cmap[uc] = 1;
     }
 #if defined (HANDLE_MULTIBYTE)
   if (ifs_value == 0)
     {
       ifs_firstc[0] = '\0'; /* XXX - ? */
       ifs_firstc_len = 1;
     }
   else
     {
       if (locale_utf8locale && UTF8_SINGLEBYTE (*ifs_value))
     ifs_firstc_len = (*ifs_value != 0) ? 1 : 0;
       else
     {
       size_t ifs_len;
       ifs_len = strnlen (ifs_value, MB_CUR_MAX);
       ifs_firstc_len = MBLEN (ifs_value, ifs_len);
     }
       if (ifs_firstc_len == 1 || ifs_firstc_len == 0 || MB_INVALIDCH (ifs_firstc_len))
     {
       ifs_firstc[0] = ifs_value[0];
       ifs_firstc[1] = '\0';
       ifs_firstc_len = 1;
     }
       else
     memcpy (ifs_firstc, ifs_value, ifs_firstc_len);
     }
 #else
   ifs_firstc = ifs_value ? *ifs_value : 0;
 #endif
 }
References ifs_cmap, ifs_firstc, ifs_is_null, ifs_is_set, ifs_value, ifs_var, locale_utf8locale, MB_CUR_MAX, MB_INVALIDCH, MBLEN, memcpy, memset, strnlen(), t, UTF8_SINGLEBYTE, and value_cell.
Referenced by execute_for_command(), initialize_shell_variables(), make_local_variable(), and sv_ifs().
shell_expand_word_list()
static WORD_LIST* shell_expand_word_list (WORD_LIST * tlist, int eflags) static
Definition at line 12787 of file subst.c.
 {
   WORD_LIST *expanded, *orig_list, *new_list, *next, *temp_list, *wcmd;
   int expanded_something, has_dollar_at;
   /* We do tilde expansion all the time.  This is what 1003.2 says. */
   wcmd = new_list = (WORD_LIST *)NULL;
   for (orig_list = tlist; tlist; tlist = next)
     {
       if (wcmd == 0 && (tlist->word->flags & W_ASSNBLTIN))
     wcmd = tlist;
       next = tlist->next;
 #if defined (ARRAY_VARS)
       /* If this is a compound array assignment to a builtin that accepts
          such assignments (e.g., `declare'), take the assignment and perform
          it separately, handling the semantics of declarations inside shell
          functions.  This avoids the double-evaluation of such arguments,
          because `declare' does some evaluation of compound assignments on
          its own. */
       if ((tlist->word->flags & (W_COMPASSIGN|W_ASSIGNARG)) == (W_COMPASSIGN|W_ASSIGNARG))
     expand_declaration_argument (tlist, wcmd);
 #endif
       expanded_something = 0;
       expanded = expand_word_internal
     (tlist->word, 0, 0, &has_dollar_at, &expanded_something);
       if (expanded == &expand_word_error || expanded == &expand_word_fatal)
     {
       /* By convention, each time this error is returned,
          tlist->word->word has already been freed. */
       tlist->word->word = (char *)NULL;
       /* Dispose our copy of the original list. */
       dispose_words (orig_list);
       /* Dispose the new list we're building. */
       dispose_words (new_list);
       last_command_exit_value = EXECUTION_FAILURE;
       if (expanded == &expand_word_error)
         exp_jump_to_top_level (DISCARD);
       else
         exp_jump_to_top_level (FORCE_EOF);
     }
       /* Don't split words marked W_NOSPLIT. */
       if (expanded_something && (tlist->word->flags & W_NOSPLIT) == 0)
     {
       temp_list = word_list_split (expanded);
       dispose_words (expanded);
     }
       else
     {
       /* If no parameter expansion, command substitution, process
          substitution, or arithmetic substitution took place, then
          do not do word splitting.  We still have to remove quoted
          null characters from the result. */
       word_list_remove_quoted_nulls (expanded);
       temp_list = expanded;
     }
       expanded = REVERSE_LIST (temp_list, WORD_LIST *);
       new_list = (WORD_LIST *)list_append (expanded, new_list);
     }
   if (orig_list)
     dispose_words (orig_list);
   if (new_list)
     new_list = REVERSE_LIST (new_list, WORD_LIST *);
   return (new_list);
 }
References DISCARD, dispose_words(), EXECUTION_FAILURE, exp_jump_to_top_level(), expand_word_error, expand_word_fatal, expand_word_internal(), word_desc::flags, FORCE_EOF, last_command_exit_value, list_append(), word_list::next, next, NULL, REVERSE_LIST, W_ASSIGNARG, W_ASSNBLTIN, W_COMPASSIGN, W_NOSPLIT, word_desc::word, word_list::word, word_list_remove_quoted_nulls(), and word_list_split().
Referenced by expand_word_list_internal().
shouldexp_replacement()
static int shouldexp_replacement (char * s) static
Definition at line 8894 of file subst.c.
 {
   size_t slen;
   int sindex, c;
   DECLARE_MBSTATE;
   sindex = 0;
   slen = STRLEN (s);
   while (c = s[sindex])
     {
       if (c == '\\')
     {
       sindex++;
       if (s[sindex] == 0)
         return 0;
       /* We want to remove this backslash because we treat it as special
          in this context. THIS ASSUMES THE STRING IS PROCESSED BY
          strcreplace() OR EQUIVALENT that handles removing backslashes
          preceding the special character. */
       if (s[sindex] == '&')
         return 1;
       if (s[sindex] == '\\')
         return 1;
     }
       else if (c == '&')
     return 1;
       ADVANCE_CHAR (s, slen, sindex);
     }
   return 0;
 }
References ADVANCE_CHAR, c, DECLARE_MBSTATE, s, and STRLEN.
Referenced by parameter_brace_patsub().
skip_double_quoted()
static int skip_double_quoted (char * string, size_t slen, int sind, int flags) static
Definition at line 1023 of file subst.c.
 {
   int c, i;
   char *ret;
   int pass_next, backquote, si;
   DECLARE_MBSTATE;
   pass_next = backquote = 0;
   i = sind;
   while (c = string[i])
     {
       if (pass_next)
     {
       pass_next = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else if (c == '\\')
     {
       pass_next++;
       i++;
       continue;
     }
       else if (backquote)
     {
       if (c == '`')
         backquote = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else if (c == '`')
     {
       backquote++;
       i++;
       continue;
     }
       else if (c == '$' && ((string[i + 1] == LPAREN) || (string[i + 1] == LBRACE)))
     {
       si = i + 2;
       if (string[i + 1] == LPAREN)
         ret = extract_command_subst (string, &si, SX_NOALLOC|(flags&SX_COMPLETE));
       else
         ret = extract_dollar_brace_string (string, &si, Q_DOUBLE_QUOTES, SX_NOALLOC);
       /* These can consume the entire string if they are unterminated */
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si + 1;
       continue;
     }
       else if (c != '"')
     {
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else
     break;
     }
   if (c)
     i++;
   return (i);
 }
References ADVANCE_CHAR, c, CHECK_STRING_OVERRUN, DECLARE_MBSTATE, extract_command_subst(), extract_dollar_brace_string(), flags, i, LBRACE, LPAREN, Q_DOUBLE_QUOTES, SX_COMPLETE, and SX_NOALLOC.
Referenced by chk_arithsub(), expand_string_dollar_quote(), extract_delimited_string(), extract_dollar_brace_string(), skip_matched_pair(), and skip_to_delim().
skip_matched_pair()
static int skip_matched_pair (char * string, int start, int open, int close, int flags) const static
Definition at line 2063 of file subst.c.
 {
   int i, pass_next, backq, si, c, count, oldjmp;
   size_t slen;
   char *temp, *ss;
   DECLARE_MBSTATE;
   slen = strlen (string + start) + start;
   oldjmp = no_longjmp_on_fatal_error;
   no_longjmp_on_fatal_error = 1;
   /* Move to the first character after a leading OPEN. If FLAGS&2, we assume
     that START already points to that character. If not, we need to skip over
     it here. */
   i = (flags & 2) ? start : start + 1;
   count = 1;
   pass_next = backq = 0;
   ss = (char *)string;
   while (c = string[i])
     {
       if (pass_next)
     {
       pass_next = 0;
       if (c == 0)
         CQ_RETURN(i);
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else if ((flags & 1) == 0 && c == '\\')
     {
       pass_next = 1;
       i++;
       continue;
     }
       else if (backq)
     {
       if (c == '`')
         backq = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else if ((flags & 1) == 0 && c == '`')
     {
       backq = 1;
       i++;
       continue;
     }
       else if ((flags & 1) == 0 && c == open)
     {
       count++;
       i++;
       continue;
     }
       else if (c == close)
     {
       count--;
       if (count == 0)
         break;
       i++;
       continue;
     }
       else if ((flags & 1) == 0 && (c == '\'' || c == '"'))
     {
       i = (c == '\'') ? skip_single_quoted (ss, slen, ++i, 0)
               : skip_double_quoted (ss, slen, ++i, 0);
       /* no increment, the skip functions increment past the closing quote. */
     }
       else if ((flags & 1) == 0 && c == '$' && (string[i+1] == LPAREN || string[i+1] == LBRACE))
     {
       si = i + 2;
       if (string[si] == '\0')
         CQ_RETURN(si);
       /* XXX - extract_command_subst here? */
       if (string[i+1] == LPAREN)
         temp = extract_delimited_string (ss, &si, "$(", "(", ")", SX_NOALLOC|SX_COMMAND); /* ) */
       else
         temp = extract_dollar_brace_string (ss, &si, 0, SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si;
       if (string[i] == '\0')    /* don't increment i past EOS in loop */
         break;
       i++;
       continue;
     }
       else
     ADVANCE_CHAR (string, slen, i);
     }
   CQ_RETURN(i);
 }
References ADVANCE_CHAR, c, CHECK_STRING_OVERRUN, close(), count, CQ_RETURN, DECLARE_MBSTATE, extract_delimited_string(), extract_dollar_brace_string(), flags, i, LBRACE, LPAREN, no_longjmp_on_fatal_error, open(), skip_double_quoted(), skip_single_quoted(), start, strlen(), SX_COMMAND, and SX_NOALLOC.
skip_single_quoted()
static int skip_single_quoted (char * string, size_t slen, int sind, int flags) const inline static
Definition at line 1141 of file subst.c.
 {
   register int c;
   DECLARE_MBSTATE;
   c = sind;
   while (string[c] && string[c] != '\'')
     {
       if ((flags & SX_COMPLETE) && string[c] == '\\' && string[c+1] == '\'' && string[c+2])
     ADVANCE_CHAR (string, slen, c);
       ADVANCE_CHAR (string, slen, c);
     }
   if (string[c])
     c++;
   return c;
 }
References ADVANCE_CHAR, c, DECLARE_MBSTATE, flags, and SX_COMPLETE.
Referenced by chk_arithsub(), expand_string_dollar_quote(), extract_delimited_string(), extract_dollar_brace_string(), skip_matched_pair(), and skip_to_delim().
skip_to_delim()
int skip_to_delim (char * string, int start, char * delims, int flags)
Definition at line 2181 of file subst.c.
 {
   int i, pass_next, backq, dquote, si, c, oldjmp;
   int invert, skipquote, skipcmd, noprocsub, completeflag;
   int arithexp, skipcol;
   size_t slen;
   char *temp, open[3];
   DECLARE_MBSTATE;
   slen = strlen (string + start) + start;
   oldjmp = no_longjmp_on_fatal_error;
   if (flags & SD_NOJMP)
     no_longjmp_on_fatal_error = 1;
   invert = (flags & SD_INVERT);
   skipcmd = (flags & SD_NOSKIPCMD) == 0;
   noprocsub = (flags & SD_NOPROCSUB);
   completeflag = (flags & SD_COMPLETE) ? SX_COMPLETE : 0;
   arithexp = (flags & SD_ARITHEXP);
   skipcol = 0;
   i = start;
   pass_next = backq = dquote = 0;
   while (c = string[i])
     {
       /* If this is non-zero, we should not let quote characters be delimiters
      and the current character is a single or double quote.  We should not
      test whether or not it's a delimiter until after we skip single- or
      double-quoted strings. */
       skipquote = ((flags & SD_NOQUOTEDELIM) && (c == '\'' || c =='"'));
       if (pass_next)
     {
       pass_next = 0;
       if (c == 0)
         CQ_RETURN(i);
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else if (c == '\\')
     {
       pass_next = 1;
       i++;
       continue;
     }
       else if (backq)
     {
       if (c == '`')
         backq = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       else if (c == '`')
     {
       backq = 1;
       i++;
       continue;
     }
       else if (arithexp && skipcol && c == ':')
     {
       skipcol--;
       i++;
       continue;
     }
       else if (arithexp && c == '?')
     {
       skipcol++;
       i++;
       continue;
     }
       else if (skipquote == 0 && invert == 0 && member (c, delims))
     break;
       /* the usual case is to use skip_xxx_quoted, but we don't skip over double
      quoted strings when looking for the history expansion character as a
      delimiter. */
       /* special case for programmable completion which takes place before
          parser converts backslash-escaped single quotes between $'...' to
          `regular' single-quoted strings. */
       else if (completeflag && i > 0 && string[i-1] == '$' && c == '\'')
     i = skip_single_quoted (string, slen, ++i, SX_COMPLETE);
       else if (c == '\'')
     i = skip_single_quoted (string, slen, ++i, 0);
       else if (c == '"')
     i = skip_double_quoted (string, slen, ++i, completeflag);
       else if (c == LPAREN && arithexp)
         {
           si = i + 1;
           if (string[si] == '\0')
         CQ_RETURN(si);
       temp = extract_delimited_string (string, &si, "(", "(", ")", SX_NOALLOC); /* ) */
       i = si;
       if (string[i] == '\0')    /* don't increment i past EOS in loop */
         break;
       i++;
       continue;
         }
       else if (c == '$' && ((skipcmd && string[i+1] == LPAREN) || string[i+1] == LBRACE))
     {
       si = i + 2;
       if (string[si] == '\0')
         CQ_RETURN(si);
       if (string[i+1] == LPAREN)
         temp = extract_delimited_string (string, &si, "$(", "(", ")", SX_NOALLOC|SX_COMMAND|completeflag); /* ) */
       else
         temp = extract_dollar_brace_string (string, &si, 0, SX_NOALLOC);
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si;
       if (string[i] == '\0')    /* don't increment i past EOS in loop */
         break;
       i++;
       continue;
     }
 #if defined (PROCESS_SUBSTITUTION)
       else if (skipcmd && noprocsub == 0 && (c == '<' || c == '>') && string[i+1] == LPAREN)
     {
       si = i + 2;
       if (string[si] == '\0')
         CQ_RETURN(si);
       temp = extract_delimited_string (string, &si, (c == '<') ? "<(" : ">(", "(", ")", SX_COMMAND|SX_NOALLOC); /* )) */
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si;
       if (string[i] == '\0')
         break;
       i++;
       continue;
     }
 #endif /* PROCESS_SUBSTITUTION */
 #if defined (EXTENDED_GLOB)
       else if ((flags & SD_EXTGLOB) && extended_glob && string[i+1] == LPAREN && member (c, "?*+!@"))
     {
       si = i + 2;
       if (string[si] == '\0')
         CQ_RETURN(si);
       open[0] = c;
       open[1] = LPAREN;
       open[2] = '\0';
       temp = extract_delimited_string (string, &si, open, "(", ")", SX_NOALLOC); /* ) */
       CHECK_STRING_OVERRUN (i, si, slen, c);
       i = si;
       if (string[i] == '\0')    /* don't increment i past EOS in loop */
         break;
       i++;
       continue;
     }
 #endif
       else if ((flags & SD_GLOB) && c == LBRACK)
     {
       si = i + 1;
       if (string[si] == '\0')
         CQ_RETURN(si);
       temp = extract_delimited_string (string, &si, "[", "[", "]", SX_NOALLOC); /* ] */
       i = si;
       if (string[i] == '\0')    /* don't increment i past EOS in loop */
         break;
       i++;
       continue;
     }
       else if ((skipquote || invert) && (member (c, delims) == 0))
     break;
       else
     ADVANCE_CHAR (string, slen, i);
     }
   CQ_RETURN(i);
 }
References ADVANCE_CHAR, c, CHECK_STRING_OVERRUN, CQ_RETURN, DECLARE_MBSTATE, extended_glob, extract_delimited_string(), extract_dollar_brace_string(), flags, i, LBRACE, LBRACK, LPAREN, member, no_longjmp_on_fatal_error, open(), SD_ARITHEXP, SD_COMPLETE, SD_EXTGLOB, SD_GLOB, SD_INVERT, SD_NOJMP, SD_NOPROCSUB, SD_NOQUOTEDELIM, SD_NOSKIPCMD, skip_double_quoted(), skip_single_quoted(), start, strlen(), SX_COMMAND, SX_COMPLETE, and SX_NOALLOC.
Referenced by make_arith_for_command(), parameter_brace_patsub(), skiparith(), and split_ignorespec().
skiparith()
static char* skiparith (char * substr, int delim) static
Definition at line 8092 of file subst.c.
 {
   int i;
   char delims[2];
   delims[0] = delim;
   delims[1] = '\0';
   i = skip_to_delim (substr, 0, delims, SD_ARITHEXP);
   return (substr + i);
 }
References i, SD_ARITHEXP, and skip_to_delim().
Referenced by verify_substring_values().
string_extract()
static char* string_extract (char * string, int * sindex, char * charlist, int flags) static
Definition at line 795 of file subst.c.
 {
   register int c, i;
   int found;
   size_t slen;
   char *temp;
   DECLARE_MBSTATE;
   slen = (MB_CUR_MAX > 1) ? strlen (string + *sindex) + *sindex : 0;
   i = *sindex;
   found = 0;
   while (c = string[i])
     {
       if (c == '\\')
     {
       if (string[i + 1])
         i++;
       else
         break;
     }
 #if defined (ARRAY_VARS)
       else if ((flags & SX_VARNAME) && c == LBRACK)
     {
       int ni;
       /* If this is an array subscript, skip over it and continue. */
       ni = skipsubscript (string, i, 0);
       if (string[ni] == RBRACK)
         i = ni;
     }
 #endif
       else if (MEMBER (c, charlist))
     {
       found = 1;
       break;
     }
       ADVANCE_CHAR (string, slen, i);
     }
   /* If we had to have a matching delimiter and didn't find one, return an
      error and let the caller deal with it. */
   if ((flags & SX_REQMATCH) && found == 0)
     {
       *sindex = i;
       return (&extract_string_error);
     }
   temp = (flags & SX_NOALLOC) ? (char *)NULL : substring (string, *sindex, i);
   *sindex = i;
   return (temp);
 }
References ADVANCE_CHAR, c, DECLARE_MBSTATE, extract_string_error, flags, found, i, LBRACK, MB_CUR_MAX, MEMBER, NULL, RBRACK, strlen(), substring(), SX_NOALLOC, SX_REQMATCH, and SX_VARNAME.
Referenced by expand_word_internal(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), and parameter_brace_expand().
string_extract_double_quoted()
static char* string_extract_double_quoted (char * string, int * sindex, int flags) static
Definition at line 860 of file subst.c.
 {
   size_t slen;
   char *send;
   int j, i, t;
   unsigned char c;
   char *temp, *ret;     /* The new string we return. */
   int pass_next, backquote, si; /* State variables for the machine. */
   int dquote;
   int stripdq;
   DECLARE_MBSTATE;
   slen = strlen (string + *sindex) + *sindex;
   send = string + slen;
   stripdq = (flags & SX_STRIPDQ);
   pass_next = backquote = dquote = 0;
   temp = (char *)xmalloc (1 + slen - *sindex);
   j = 0;
   i = *sindex;
   while (c = string[i])
     {
       /* Process a character that was quoted by a backslash. */
       if (pass_next)
     {
       /* XXX - take another look at this in light of Interp 221 */
       /* Posix.2 sez:
          ``The backslash shall retain its special meaning as an escape
          character only when followed by one of the characters:
         $   `   "   \   <newline>''.
          If STRIPDQ is zero, we handle the double quotes here and let
          expand_word_internal handle the rest.  If STRIPDQ is non-zero,
          we have already been through one round of backslash stripping,
          and want to strip these backslashes only if DQUOTE is non-zero,
          indicating that we are inside an embedded double-quoted string. */
       /* If we are in an embedded quoted string, then don't strip
          backslashes before characters for which the backslash
          retains its special meaning, but remove backslashes in
          front of other characters.  If we are not in an
          embedded quoted string, don't strip backslashes at all.
          This mess is necessary because the string was already
          surrounded by double quotes (and sh has some really weird
          quoting rules).
          The returned string will be run through expansion as if
          it were double-quoted. */
       if ((stripdq == 0 && c != '"') ||
           (stripdq && ((dquote && (sh_syntaxtab[c] & CBSDQUOTE)) || dquote == 0)))
         temp[j++] = '\\';
       pass_next = 0;
 add_one_character:
       COPY_CHAR_I (temp, j, string, send, i);
       continue;
     }
       /* A backslash protects the next character.  The code just above
      handles preserving the backslash in front of any character but
      a double quote. */
       if (c == '\\')
     {
       pass_next++;
       i++;
       continue;
     }
       /* Inside backquotes, ``the portion of the quoted string from the
      initial backquote and the characters up to the next backquote
      that is not preceded by a backslash, having escape characters
      removed, defines that command''. */
       if (backquote)
     {
       if (c == '`')
         backquote = 0;
       temp[j++] = c;    /* COPY_CHAR_I? */
       i++;
       continue;
     }
       if (c == '`')
     {
       temp[j++] = c;
       backquote++;
       i++;
       continue;
     }
       /* Pass everything between `$(' and the matching `)' or a quoted
      ${ ... } pair through according to the Posix.2 specification. */
       if (c == '$' && ((string[i + 1] == LPAREN) || (string[i + 1] == LBRACE)))
     {
       int free_ret = 1;
       si = i + 2;
       if (string[i + 1] == LPAREN)
         ret = extract_command_subst (string, &si, (flags & SX_COMPLETE));
       else
         ret = extract_dollar_brace_string (string, &si, Q_DOUBLE_QUOTES, 0);
       temp[j++] = '$';
       temp[j++] = string[i + 1];
       /* Just paranoia; ret will not be 0 unless no_longjmp_on_fatal_error
          is set. */
       if (ret == 0 && no_longjmp_on_fatal_error)
         {
           free_ret = 0;
           ret = string + i + 2;
         }
       /* XXX - CHECK_STRING_OVERRUN here? */
       for (t = 0; ret[t]; t++, j++)
         temp[j] = ret[t];
       temp[j] = string[si];
       if (si < i + 2)   /* we went back? */
         i += 2;
       else if (string[si])
         {
           j++;
           i = si + 1;
         }
       else
         i = si;
       if (free_ret)
         free (ret);
       continue;
     }
       /* Add any character but a double quote to the quoted string we're
      accumulating. */
       if (c != '"')
     goto add_one_character;
       /* c == '"' */
       if (stripdq)
     {
       dquote ^= 1;
       i++;
       continue;
     }
       break;
     }
   temp[j] = '\0';
   /* Point to after the closing quote. */
   if (c)
     i++;
   *sindex = i;
   return (temp);
 }
References c, CBSDQUOTE, COPY_CHAR_I, DECLARE_MBSTATE, extract_command_subst(), extract_dollar_brace_string(), flags, free, i, j, LBRACE, LPAREN, no_longjmp_on_fatal_error, Q_DOUBLE_QUOTES, send(), sh_syntaxtab, strlen(), SX_COMPLETE, SX_STRIPDQ, t, and xmalloc.
Referenced by expand_string_dollar_quote(), expand_word_internal(), extract_heredoc_dolbrace_string(), getpattern(), and parameter_brace_expand_rhs().
string_extract_single_quoted()
static char* string_extract_single_quoted (char * string, int * sindex, int allowesc) inline static
Definition at line 1098 of file subst.c.
 {
   register int i;
   size_t slen;
   char *t;
   int pass_next;
   DECLARE_MBSTATE;
   /* Don't need slen for ADVANCE_CHAR unless multibyte chars possible. */
   slen = (MB_CUR_MAX > 1) ? strlen (string + *sindex) + *sindex : 0;
   i = *sindex;
   pass_next = 0;
   while (string[i])
     {
       if (pass_next)
     {
       pass_next = 0;
       ADVANCE_CHAR (string, slen, i);
       continue;
     }
       if (allowesc && string[i] == '\\')
     pass_next++;
       else if (string[i] == '\'')
         break;
       ADVANCE_CHAR (string, slen, i);
     }
   t = substring (string, *sindex, i);
   if (string[i])
     i++;
   *sindex = i;
   return (t);
 }
References ADVANCE_CHAR, DECLARE_MBSTATE, i, MB_CUR_MAX, strlen(), substring(), and t.
Referenced by expand_word_internal(), extract_heredoc_dolbrace_string(), string_extract_verbatim(), and string_quote_removal().
string_extract_verbatim()
static char* string_extract_verbatim (char * string, size_t slen, int * sindex, char * charlist, int flags) static
Definition at line 1166 of file subst.c.
 {
   register int i;
 #if defined (HANDLE_MULTIBYTE)
   wchar_t *wcharlist;
 #endif
   int c;
   char *temp;
   DECLARE_MBSTATE;
   if ((flags & SX_NOCTLESC) && charlist[0] == '\'' && charlist[1] == '\0')
     {
       temp = string_extract_single_quoted (string, sindex, 0);
       --*sindex;    /* leave *sindex at separator character */
       return temp;
     }
   /* This can never be called with charlist == NULL. If *charlist == NULL,
      we can skip the loop and just return a copy of the string, updating
      *sindex */
   if (*charlist == 0)
     {
       temp = string + *sindex;
       c = (*sindex == 0) ? slen : STRLEN (temp);
       temp = savestring (temp);
       *sindex += c;
       return temp;
     }
   i = *sindex;
 #if defined (HANDLE_MULTIBYTE)
   wcharlist = 0;
 #endif
   while (c = string[i])
     {
 #if defined (HANDLE_MULTIBYTE)
       size_t mblength;
 #endif
       if ((flags & SX_NOCTLESC) == 0 && c == CTLESC)
     {
       i += 2;
       CHECK_STRING_OVERRUN (i, i, slen, c);
       continue;
     }
       /* Even if flags contains SX_NOCTLESC, we let CTLESC quoting CTLNUL
      through, to protect the CTLNULs from later calls to
      remove_quoted_nulls. */
       else if ((flags & SX_NOESCCTLNUL) == 0 && c == CTLESC && string[i+1] == CTLNUL)
     {
       i += 2;
       CHECK_STRING_OVERRUN (i, i, slen, c);
       continue;
     }
 #if defined (HANDLE_MULTIBYTE)
       if (locale_utf8locale && slen > i && UTF8_SINGLEBYTE (string[i]))
     mblength = (string[i] != 0) ? 1 : 0;
       else
     mblength = MBLEN (string + i, slen - i);
       if (mblength > 1)
     {
       wchar_t wc;
       mblength = mbtowc (&wc, string + i, slen - i);
       if (MB_INVALIDCH (mblength))
         {
           if (MEMBER (c, charlist))
         break;
         }
       else
         {
           if (wcharlist == 0)
         {
           size_t len;
           len = mbstowcs (wcharlist, charlist, 0);
           if (len == -1)
             len = 0;
           wcharlist = (wchar_t *)xmalloc (sizeof (wchar_t) * (len + 1));
           mbstowcs (wcharlist, charlist, len + 1);
         }
           if (wcschr (wcharlist, wc))
         break;
         }
     }
       else
 #endif
       if (MEMBER (c, charlist))
     break;
       ADVANCE_CHAR (string, slen, i);
     }
 #if defined (HANDLE_MULTIBYTE)
   FREE (wcharlist);
 #endif
   temp = substring (string, *sindex, i);
   *sindex = i;
   return (temp);
 }
References ADVANCE_CHAR, c, CHECK_STRING_OVERRUN, CTLESC, CTLNUL, DECLARE_MBSTATE, flags, FREE, i, len, locale_utf8locale, MB_INVALIDCH, MBLEN, mbstowcs(), mbtowc(), MEMBER, savestring(), string_extract_single_quoted(), STRLEN, substring(), SX_NOCTLESC, SX_NOESCCTLNUL, UTF8_SINGLEBYTE, wcschr(), and xmalloc.
Referenced by get_word_from_string(), and list_string().
string_list()
char* string_list (WORD_LIST * list)
Definition at line 2855 of file subst.c.
 {
   return (string_list_internal (list, " "));
 }
References list(), and string_list_internal().
Referenced by decode_prompt_string(), error_token_from_token(), execute_case_command(), expand_arith_string(), expand_string_for_patsub(), expand_string_if_necessary(), expand_string_to_string_internal(), expand_word_internal(), getpattern(), param_expand(), parameter_brace_expand_error(), parameter_brace_expand_length(), parameter_brace_expand_rhs(), parse_compound_assignment(), redirection_expand(), string_list_pos_params(), and string_rest_of_args().
string_list_dollar_at()
char* string_list_dollar_at (WORD_LIST * list, int quoted, int flags)
Definition at line 2962 of file subst.c.
 {
   char *ifs, *ret;
 #if defined (HANDLE_MULTIBYTE)
 #  if defined (__GNUC__)
   char sep[MB_CUR_MAX + 1];
 #  else
   char *sep = 0;
 #  endif /* !__GNUC__ */
 #else
   char sep[2];
 #endif
   WORD_LIST *tlist;
   /* XXX this could just be ifs = ifs_value; */
   ifs = ifs_var ? value_cell (ifs_var) : (char *)0;
 #if defined (HANDLE_MULTIBYTE)
 #  if !defined (__GNUC__)
   sep = (char *)xmalloc (MB_CUR_MAX + 1);
 #  endif /* !__GNUC__ */
   /* XXX - testing PF_ASSIGNRHS to make sure positional parameters are
      separated with a space even when word splitting will not occur. */
   if (flags & PF_ASSIGNRHS)
     {
       sep[0] = ' ';
       sep[1] = '\0';
     }
   else if (ifs && *ifs)
     {
       if (ifs_firstc_len == 1)
     {
       sep[0] = ifs_firstc[0];
       sep[1] = '\0';
     }
       else
     {
       memcpy (sep, ifs_firstc, ifs_firstc_len);
       sep[ifs_firstc_len] = '\0';
     }
     }
   else
     {
       sep[0] = ' ';
       sep[1] = '\0';
     }
 #else   /* !HANDLE_MULTIBYTE */
   /* XXX - PF_ASSIGNRHS means no word splitting, so we want positional
      parameters separated by a space. */
   sep[0] = ((flags & PF_ASSIGNRHS) || ifs == 0 || *ifs == 0) ? ' ' : *ifs;
   sep[1] = '\0';
 #endif  /* !HANDLE_MULTIBYTE */
   /* XXX -- why call quote_list if ifs == 0?  we can get away without doing
      it now that quote_escapes quotes spaces */
   tlist = (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES|Q_PATQUOTE))
         ? quote_list (list)
         : list_quote_escapes (list);
   ret = string_list_internal (tlist, sep);
 #if defined (HANDLE_MULTIBYTE) && !defined (__GNUC__)
   free (sep);
 #endif
   return ret;
 }
References flags, free, ifs_firstc, ifs_var, list(), list_quote_escapes(), MB_CUR_MAX, memcpy, PF_ASSIGNRHS, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, Q_PATQUOTE, quote_list(), string_list_internal(), value_cell, and xmalloc.
Referenced by expand_word_internal(), param_expand(), parameter_brace_expand(), and string_list_pos_params().
string_list_dollar_star()
char* string_list_dollar_star (WORD_LIST * list, int quoted, int flags)
Definition at line 2905 of file subst.c.
 {
   char *ret;
 #if defined (HANDLE_MULTIBYTE)
 #  if defined (__GNUC__)
   char sep[MB_CUR_MAX + 1];
 #  else
   char *sep = 0;
 #  endif
 #else
   char sep[2];
 #endif
 #if defined (HANDLE_MULTIBYTE)
 #  if !defined (__GNUC__)
   sep = (char *)xmalloc (MB_CUR_MAX + 1);
 #  endif /* !__GNUC__ */
   if (ifs_firstc_len == 1)
     {
       sep[0] = ifs_firstc[0];
       sep[1] = '\0';
     }
   else
     {
       memcpy (sep, ifs_firstc, ifs_firstc_len);
       sep[ifs_firstc_len] = '\0';
     }
 #else
   sep[0] = ifs_firstc;
   sep[1] = '\0';
 #endif
   ret = string_list_internal (list, sep);
 #if defined (HANDLE_MULTIBYTE) && !defined (__GNUC__)
   free (sep);
 #endif
   return ret;
 }
References free, ifs_firstc, list(), MB_CUR_MAX, memcpy, string_list_internal(), and xmalloc.
Referenced by param_expand(), parameter_brace_expand(), parameter_brace_expand_rhs(), string_list_pos_params(), and string_rest_of_args().
string_list_internal()
char* string_list_internal (WORD_LIST * list, char * sep)
Definition at line 2802 of file subst.c.
 {
   register WORD_LIST *t;
   char *result, *r;
   size_t word_len, sep_len, result_size;
   if (list == 0)
     return ((char *)NULL);
   /* Short-circuit quickly if we don't need to separate anything. */
   if (list->next == 0)
     return (savestring (list->word->word));
   /* This is nearly always called with either sep[0] == 0 or sep[1] == 0. */
   sep_len = STRLEN (sep);
   result_size = 0;
   for (t = list; t; t = t->next)
     {
       if (t != list)
     result_size += sep_len;
       result_size += strlen (t->word->word);
     }
   r = result = (char *)xmalloc (result_size + 1);
   for (t = list; t; t = t->next)
     {
       if (t != list && sep_len)
     {
       if (sep_len > 1)
         {
           FASTCOPY (sep, r, sep_len);
           r += sep_len;
         }
       else
         *r++ = sep[0];
     }
       word_len = strlen (t->word->word);
       FASTCOPY (t->word->word, r, word_len);
       r += word_len;
     }
   *r = '\0';
   return (result);
 }
References FASTCOPY, list(), node::next, NULL, savestring(), strlen(), STRLEN, t, and xmalloc.
Referenced by error_token_from_token(), parameter_brace_expand_rhs(), string_list(), string_list_dollar_at(), and string_list_dollar_star().
string_list_pos_params()
char* string_list_pos_params (int pchar, WORD_LIST * list, int quoted, int pflags)
Definition at line 3038 of file subst.c.
 {
   char *ret;
   WORD_LIST *tlist;
   if (pchar == '*' && (quoted & Q_DOUBLE_QUOTES))
     {
       tlist = quote_list (list);
       word_list_remove_quoted_nulls (tlist);
       ret = string_list_dollar_star (tlist, 0, 0);
     }
   else if (pchar == '*' && (quoted & Q_HERE_DOCUMENT))
     {
       tlist = quote_list (list);
       word_list_remove_quoted_nulls (tlist);
       ret = string_list (tlist);
     }
   else if (pchar == '*' && quoted == 0 && ifs_is_null)  /* XXX */
     ret = expand_no_split_dollar_star ? string_list_dollar_star (list, quoted, 0) : string_list_dollar_at (list, quoted, 0);    /* Posix interp 888 */
   else if (pchar == '*' && quoted == 0 && (pflags & PF_ASSIGNRHS))  /* XXX */
     ret = expand_no_split_dollar_star ? string_list_dollar_star (list, quoted, 0) : string_list_dollar_at (list, quoted, 0);    /* Posix interp 888 */
   else if (pchar == '*')
     {
       /* Even when unquoted, string_list_dollar_star does the right thing
      making sure that the first character of $IFS is used as the
      separator. */
       ret = string_list_dollar_star (list, quoted, 0);
     }
   else if (pchar == '@' && (quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)))
     /* We use string_list_dollar_at, but only if the string is quoted, since
        that quotes the escapes if it's not, which we don't want.  We could
        use string_list (the old code did), but that doesn't do the right
        thing if the first character of $IFS is not a space.  We use
        string_list_dollar_star if the string is unquoted so we make sure that
        the elements of $@ are separated by the first character of $IFS for
        later splitting. */
     ret = string_list_dollar_at (list, quoted, 0);
   else if (pchar == '@' && quoted == 0 && ifs_is_null)  /* XXX */
     ret = string_list_dollar_at (list, quoted, 0);  /* Posix interp 888 */
   else if (pchar == '@' && quoted == 0 && (pflags & PF_ASSIGNRHS))
     ret = string_list_dollar_at (list, quoted, pflags); /* Posix interp 888 */
   else if (pchar == '@')
     ret = string_list_dollar_star (list, quoted, 0);
   else
     ret = string_list ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) ? quote_list (list) : list);
   return ret;
 }
References expand_no_split_dollar_star, ifs_is_null, list(), PF_ASSIGNRHS, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, quote_list(), string_list(), string_list_dollar_at(), string_list_dollar_star(), and word_list_remove_quoted_nulls().
Referenced by list_remove_pattern(), list_transform(), pos_params(), pos_params_modcase(), and pos_params_pat_subst().
string_quote_removal()
char* string_quote_removal (char * string, int quoted)
Definition at line 11888 of file subst.c.
 {
   size_t slen;
   char *r, *result_string, *temp, *send;
   int sindex, tindex, dquote;
   unsigned char c;
   DECLARE_MBSTATE;
   /* The result can be no longer than the original string. */
   slen = strlen (string);
   send = string + slen;
   r = result_string = (char *)xmalloc (slen + 1);
   for (dquote = sindex = 0; c = string[sindex];)
     {
       switch (c)
     {
     case '\\':
       c = string[++sindex];
       if (c == 0)
         {
           *r++ = '\\';
           break;
         }
       if (((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) || dquote) && (sh_syntaxtab[c] & CBSDQUOTE) == 0)
         *r++ = '\\';
       /* FALLTHROUGH */
     default:
       SCOPY_CHAR_M (r, string, send, sindex);
       break;
     case '\'':
       if ((quoted & (Q_HERE_DOCUMENT|Q_DOUBLE_QUOTES)) || dquote)
         {
           *r++ = c;
           sindex++;
           break;
         }
       tindex = sindex + 1;
       temp = string_extract_single_quoted (string, &tindex, 0);
       if (temp)
         {
           strcpy (r, temp);
           r += strlen (r);
           free (temp);
         }
       sindex = tindex;
       break;
     case '"':
       dquote = 1 - dquote;
       sindex++;
       break;
     }
     }
     *r = '\0';
     return (result_string);
 }
References c, CBSDQUOTE, DECLARE_MBSTATE, free, Q_DOUBLE_QUOTES, Q_HERE_DOCUMENT, SCOPY_CHAR_M, send(), sh_syntaxtab, strcpy, string_extract_single_quoted(), strlen(), and xmalloc.
Referenced by expand_arith_string(), expand_string_if_necessary(), and make_here_document().
string_rest_of_args()
char* string_rest_of_args (int dollar_star)
Definition at line 3747 of file subst.c.
 {
   register WORD_LIST *list;
   char *string;
   list = list_rest_of_args ();
   string = dollar_star ? string_list_dollar_star (list, 0, 0) : string_list (list);
   dispose_words (list);
   return (string);
 }
References dispose_words(), list(), list_rest_of_args(), string, string_list(), and string_list_dollar_star().
string_transform()
static char* string_transform (int xc, SHELL_VAR * v, char * s) static
Definition at line 8456 of file subst.c.
 {
   char *ret, flags[MAX_ATTRIBUTES], *t;
   int i;
   if (((xc == 'A' || xc == 'a') && v == 0))
     return (char *)NULL;
   else if (xc != 'a' && xc != 'A' && s == 0)
     return (char *)NULL;
   switch (xc)
     {
       /* Transformations that interrogate the variable */
       case 'a':
     i = var_attribute_string (v, 0, flags);
     ret = (i > 0) ? savestring (flags) : (char *)NULL;
     break;
       case 'A':
     ret = string_var_assignment (v, s);
     break;
       case 'K':
       case 'k':
     ret = sh_quote_reusable (s, 0);
     break;
       /* Transformations that modify the variable's value */
       case 'E':
     t = ansiexpand (s, 0, strlen (s), (int *)0);
     ret = dequote_escapes (t);
     free (t);
     break;
       case 'P':
     ret = decode_prompt_string (s);
     break;
       case 'Q':
     ret = sh_quote_reusable (s, 0);
     break;
       case 'U':
     ret = sh_modcase (s, 0, CASE_UPPER);
     break;
       case 'u':
     ret = sh_modcase (s, 0, CASE_UPFIRST);  /* capitalize */
     break;
       case 'L':
     ret = sh_modcase (s, 0, CASE_LOWER);
     break;
       default:
     ret = (char *)NULL;
     break;
     }
   return ret;
 }
References ansiexpand(), CASE_LOWER, CASE_UPFIRST, CASE_UPPER, decode_prompt_string(), dequote_escapes(), flags, free, i, MAX_ATTRIBUTES, NULL, s, savestring(), sh_modcase(), sh_quote_reusable(), string_var_assignment(), strlen(), and t.
Referenced by list_transform(), and parameter_brace_transform().
string_var_assignment()
static char* string_var_assignment (SHELL_VAR * v, char * s) static
Definition at line 8367 of file subst.c.
 {
   char flags[MAX_ATTRIBUTES], *ret, *val;
   int i;
   val = (v && (invisible_p (v) || var_isset (v) == 0)) ? (char *)NULL : sh_quote_reusable (s, 0);
   i = var_attribute_string (v, 0, flags);
   if (i == 0 && val == 0)
     return (char *)NULL;
   ret = (char *)xmalloc (i + STRLEN (val) + strlen (v->name) + 16 + MAX_ATTRIBUTES);
   if (i > 0 && val == 0)
     sprintf (ret, "declare -%s %s", flags, v->name);
   else if (i > 0)
     sprintf (ret, "declare -%s %s=%s", flags, v->name, val);
   else
     sprintf (ret, "%s=%s", v->name, val);
   free (val);
   return ret;
 }
References flags, free, i, invisible_p, MAX_ATTRIBUTES, variable::name, NULL, s, sh_quote_reusable(), sprintf(), strlen(), STRLEN, val, var_isset, and xmalloc.
Referenced by string_transform().
strip_trailing_ifs_whitespace()
char* strip_trailing_ifs_whitespace (char * string, char * separators, int saw_escape)
Definition at line 3382 of file subst.c.
 {
   char *s;
   s = string + STRLEN (string) - 1;
   while (s > string && ((spctabnl (*s) && isifs (*s)) ||
             (saw_escape && *s == CTLESC && spctabnl (s[1]))))
     s--;
   *++s = '\0';
   return string;
 }
References CTLESC, isifs, s, spctabnl, string, and STRLEN.
sub_append_string()
INLINE char* sub_append_string (char * source, char * target, size_t * indx, size_t * size)
Definition at line 741 of file subst.c.
 {
   if (source)
     {
       size_t n, srclen;
       srclen = STRLEN (source);
       if (srclen >= (*size - *indx))
     {
       n = srclen + *indx;
       n = (n + DEFAULT_ARRAY_SIZE) - (n % DEFAULT_ARRAY_SIZE);
       target = (char *)xrealloc (target, (*size = n));
     }
       FASTCOPY (source, target + *indx, srclen);
       *indx += srclen;
       target[*indx] = '\0';
       free (source);
     }
   return (target);
 }
References DEFAULT_ARRAY_SIZE, FASTCOPY, free, n, size, source, STRLEN, target, and xrealloc.
Referenced by decode_prompt_string(), and expand_word_internal().
valid_brace_expansion_word()
static int valid_brace_expansion_word (char * name, int var_is_special) static
Definition at line 7311 of file subst.c.
 {
   if (DIGIT (*name) && all_digits (name))
     return 1;
   else if (var_is_special)
     return 1;
 #if defined (ARRAY_VARS)
   else if (valid_array_reference (name, 0))
     return 1;
 #endif /* ARRAY_VARS */
   else if (legal_identifier (name))
     return 1;
   else
     return 0;
 }
References all_digits(), DIGIT, and legal_identifier().
Referenced by parameter_brace_expand(), and parameter_brace_expand_indir().
valid_length_expression()
static int valid_length_expression (char * name) static
Definition at line 7972 of file subst.c.
 {
   return (name[1] == '\0' ||                    /* ${#} */
       ((sh_syntaxtab[(unsigned char) name[1]] & CSPECVAR) && name[2] == '\0') ||  /* special param */
       (DIGIT (name[1]) && all_digits (name + 1)) || /* ${#11} */
 #if defined (ARRAY_VARS)
       valid_array_reference (name + 1, 0) ||        /* ${#a[7]} */
 #endif
       legal_identifier (name + 1));             /* ${#PS1} */
 }
References all_digits(), CSPECVAR, DIGIT, legal_identifier(), and sh_syntaxtab.
Referenced by parameter_brace_expand().
valid_parameter_transform()
static int valid_parameter_transform (char * xform) static
Definition at line 8629 of file subst.c.
 {
   if (xform[1])
     return 0;
   /* check for valid values of xform[0] */
   switch (xform[0])
     {
     case 'a':       /* expand to a string with just attributes */
     case 'A':       /* expand as an assignment statement with attributes */
     case 'K':       /* expand assoc array to list of key/value pairs */
     case 'k':       /* XXX - for now */
     case 'E':       /* expand like $'...' */
     case 'P':       /* expand like prompt string */
     case 'Q':       /* quote reusably */
     case 'U':       /* transform to uppercase */
     case 'u':       /* transform by capitalizing */
     case 'L':       /* transform to lowercase */
       return 1;
     default:
       return 0;
     }
 }
Referenced by parameter_brace_transform().
verify_substring_values()
static int verify_substring_values (SHELL_VAR * v, char * value, char * substr, int vtype, intmax_t * e1p, intmax_t * e2p) static
Definition at line 8113 of file subst.c.
 {
   char *t, *temp1, *temp2;
   arrayind_t len;
   int expok, eflag;
 #if defined (ARRAY_VARS)
  ARRAY *a;
  HASH_TABLE *h;
 #endif
   /* duplicate behavior of strchr(3) */
   t = skiparith (substr, ':');
   if (*t && *t == ':')
     *t = '\0';
   else
     t = (char *)0;
   temp1 = expand_arith_string (substr, Q_DOUBLE_QUOTES|Q_ARITH);
   eflag = (shell_compatibility_level > 51) ? 0 : EXP_EXPANDED;
   *e1p = evalexp (temp1, eflag, &expok);
   free (temp1);
   if (expok == 0)
     return (0);
   len = -1; /* paranoia */
   switch (vtype)
     {
     case VT_VARIABLE:
     case VT_ARRAYMEMBER:
       len = MB_STRLEN (value);
       break;
     case VT_POSPARMS:
       len = number_of_args () + 1;
       if (*e1p == 0)
     len++;      /* add one arg if counting from $0 */
       break;
 #if defined (ARRAY_VARS)
     case VT_ARRAYVAR:
       /* For arrays, the first value deals with array indices.  Negative
      offsets count from one past the array's maximum index.  Associative
      arrays treat the number of elements as the maximum index. */
       if (assoc_p (v))
     {
       h = assoc_cell (v);
       len = assoc_num_elements (h) + (*e1p < 0);
     }
       else
     {
       a = (ARRAY *)value;
       len = array_max_index (a) + (*e1p < 0);   /* arrays index from 0 to n - 1 */
     }
       break;
 #endif
     }
   if (len == -1)    /* paranoia */
     return -1;
   if (*e1p < 0)     /* negative offsets count from end */
     *e1p += len;
   if (*e1p > len || *e1p < 0)
     return (-1);
 #if defined (ARRAY_VARS)
   /* For arrays, the second offset deals with the number of elements. */
   if (vtype == VT_ARRAYVAR)
     len = assoc_p (v) ? assoc_num_elements (h) : array_num_elements (a);
 #endif
   if (t)
     {
       t++;
       temp2 = savestring (t);
       temp1 = expand_arith_string (temp2, Q_DOUBLE_QUOTES|Q_ARITH);
       free (temp2);
       t[-1] = ':';
       *e2p = evalexp (temp1, eflag, &expok);
       free (temp1);
       if (expok == 0)
     return (0);
       /* Should we allow positional parameter length < 0 to count backwards
      from end of positional parameters? */
 #if 1
       if ((vtype == VT_ARRAYVAR || vtype == VT_POSPARMS) && *e2p < 0)
 #else /* XXX - postponed; this isn't really a valuable feature */
       if (vtype == VT_ARRAYVAR && *e2p < 0)
 #endif
     {
       internal_error (_("%s: substring expression < 0"), t);
       return (0);
     }
 #if defined (ARRAY_VARS)
       /* In order to deal with sparse arrays, push the intelligence about how
      to deal with the number of elements desired down to the array-
      specific functions.  */
       if (vtype != VT_ARRAYVAR)
 #endif
     {
       if (*e2p < 0)
         {
           *e2p += len;
           if (*e2p < 0 || *e2p < *e1p)
         {
           internal_error (_("%s: substring expression < 0"), t);
           return (0);
         }
         }
       else
         *e2p += *e1p;       /* want E2 chars starting at E1 */
       if (*e2p > len)
         *e2p = len;
     }
     }
   else
     *e2p = len;
   return (1);
 }
References _, array_max_index, array_num_elements, assoc_cell, assoc_num_elements, assoc_p, eflag, evalexp(), EXP_EXPANDED, expand_arith_string(), free, h, internal_error(), len, MB_STRLEN, number_of_args(), Q_ARITH, Q_DOUBLE_QUOTES, savestring(), shell_compatibility_level, skiparith(), t, value, VT_ARRAYMEMBER, VT_ARRAYVAR, VT_POSPARMS, and VT_VARIABLE.
Referenced by parameter_brace_substring().
word_list_remove_quoted_nulls()
void word_list_remove_quoted_nulls (WORD_LIST * list)
Definition at line 5088 of file subst.c.
 {
   register WORD_LIST *t;
   for (t = list; t; t = t->next)
     {
       remove_quoted_nulls (t->word->word);
       t->word->flags &= ~W_HASQUOTEDNULL;
     }
 }
References list(), remove_quoted_nulls(), t, and W_HASQUOTEDNULL.
Referenced by getpattern(), shell_expand_word_list(), and string_list_pos_params().
word_list_split()
static WORD_LIST* word_list_split (WORD_LIST * list) static
Definition at line 12089 of file subst.c.
 {
   WORD_LIST *result, *t, *tresult, *e;
   WORD_DESC *w;
   for (t = list, result = (WORD_LIST *)NULL; t; t = t->next)
     {
       tresult = word_split (t->word, ifs_value);
       /* POSIX 2.6: "If the complete expansion appropriate for a word results
      in an empty field, that empty field shall be deleted from the list
      of fields that form the completely expanded command, unless the
      original word contained single-quote or double-quote characters."
      This is where we handle these words that contain quoted null strings
      and other characters that expand to nothing after word splitting. */
       if (tresult == 0 && t->word && (t->word->flags & W_SAWQUOTEDNULL))    /* XXX */
     {
       w = alloc_word_desc ();
       w->word = (char *)xmalloc (1);
       w->word[0] = '\0';
       tresult = make_word_list (w, (WORD_LIST *)NULL);
     }
 #if defined (ARRAY_VARS)
       /* pass W_ARRAYREF through for words that are not split and are
      identical to the original word. */
       if (tresult && tresult->next == 0 && t->next == 0 && (t->word->flags & W_ARRAYREF) && STREQ (t->word->word, tresult->word->word))
     tresult->word->flags |= W_ARRAYREF;
 #endif
       if (result == 0)
         result = e = tresult;
       else
     {
       e->next = tresult;
       while (e->next)
         e = e->next;
     }
     }
   return (result);
 }
References alloc_word_desc(), word_desc::flags, ifs_value, list(), make_word_list(), word_list::next, NULL, STREQ, t, w, W_ARRAYREF, W_SAWQUOTEDNULL, word_desc::word, word_list::word, word_split(), and xmalloc.
Referenced by expand_arith_string(), expand_string_leave_quoted(), expand_word(), and shell_expand_word_list().
word_split()
WORD_LIST* word_split (WORD_DESC * w, char * ifs_chars)
Definition at line 12067 of file subst.c.
 {
   WORD_LIST *result;
   if (w)
     {
       char *xifs;
       xifs = ((w->flags & W_QUOTED) || ifs_chars == 0) ? "" : ifs_chars;
       result = list_string (w->word, xifs, w->flags & W_QUOTED);
     }
   else
     result = (WORD_LIST *)NULL;
   return (result);
 }
References list_string(), NULL, w, and W_QUOTED.
Referenced by word_list_split().
Variable Documentation
allow_null_glob_expansion
int allow_null_glob_expansion
Definition at line 185 of file subst.c.
Referenced by glob_expand_word_list().
assigning_in_environment
int assigning_in_environment
Definition at line 172 of file subst.c.
Referenced by do_assignment_statements(), exp_jump_to_top_level(), find_variable(), find_variable_for_assignment(), find_variable_last_nameref(), find_variable_nameref(), find_variable_no_invisible(), and find_variable_noref().
cached_quoted_dollar_at
WORD_LIST* cached_quoted_dollar_at = 0 static
Definition at line 217 of file subst.c.
Referenced by expand_word_internal(), and invalidate_cached_quoted_dollar_at().
current_command_subst_pid
pid_t current_command_subst_pid = NO_PID
Definition at line 151 of file subst.c.
Referenced by command_substitute().
current_fds_to_close
struct fd_bitmap* current_fds_to_close extern
Definition at line 314 of file execute_cmd.c.
Referenced by execute_command(), and execute_simple_command().
dbstate
int dbstate[PARAMEXPNEST_MAX] static
Definition at line 1802 of file subst.c.
Referenced by extract_dollar_brace_string().
errno
int errno extern
expand_no_split_dollar_star
int expand_no_split_dollar_star = 0 static
Definition at line 230 of file subst.c.
Referenced by chk_atstar(), exp_jump_to_top_level(), expand_string_assignment(), expand_string_for_pat(), expand_string_for_rhs(), expand_string_unsplit(), expand_word_leave_quoted(), list_transform(), param_expand(), parameter_brace_expand(), parameter_brace_expand_word(), parameter_brace_find_indir(), pos_params_pat_subst(), and string_list_pos_params().
expand_param_error
char expand_param_error static
Definition at line 222 of file subst.c.
Referenced by command_substitute(), optimize_cat_file(), parameter_brace_expand(), parameter_brace_expand_indir(), parameter_brace_expand_word(), parameter_brace_substring(), and parameter_brace_transform().
expand_param_fatal
char expand_param_fatal static
Definition at line 222 of file subst.c.
Referenced by parameter_brace_expand(), and parameter_brace_transform().
expand_param_unset
char expand_param_unset static
Definition at line 222 of file subst.c.
expand_wdesc_error
WORD_DESC expand_wdesc_error static
Definition at line 221 of file subst.c.
Referenced by expand_word_internal(), param_expand(), parameter_brace_expand(), and parameter_brace_expand_rhs().
expand_wdesc_fatal
WORD_DESC expand_wdesc_fatal static
Definition at line 221 of file subst.c.
Referenced by expand_word_internal(), param_expand(), and parameter_brace_expand().
expand_word_error
WORD_LIST expand_word_error static
Definition at line 220 of file subst.c.
Referenced by call_expand_word_internal(), expand_prompt_string(), expand_word_internal(), and shell_expand_word_list().
expand_word_fatal
WORD_LIST expand_word_fatal static
Definition at line 220 of file subst.c.
Referenced by call_expand_word_internal(), expand_prompt_string(), expand_word_internal(), and shell_expand_word_list().
extended_quote
int extended_quote extern
Definition at line 310 of file y.tab.c.
Referenced by extract_heredoc_dolbrace_string(), and parse_matched_pair().
extract_string_error
char extract_string_error static
Definition at line 223 of file subst.c.
Referenced by expand_word_internal(), and string_extract().
extract_string_fatal
char extract_string_fatal static
Definition at line 223 of file subst.c.
Referenced by expand_word_internal().
fail_glob_expansion
int fail_glob_expansion
Definition at line 188 of file subst.c.
Referenced by glob_expand_word_list().
garglist
WORD_LIST* garglist = (WORD_LIST *)NULL static
Definition at line 234 of file subst.c.
Referenced by command_substitute(), and expand_word_list_internal().
ifs_cmap
unsigned char ifs_cmap[UCHAR_MAX+1]
Definition at line 156 of file subst.c.
Referenced by read_comsub(), and setifs().
ifs_firstc
unsigned char ifs_firstc
Definition at line 163 of file subst.c.
Referenced by ifs_firstchar(), param_expand(), parameter_brace_expand_word(), setifs(), string_list_dollar_at(), and string_list_dollar_star().
ifs_is_null
int ifs_is_null
Definition at line 157 of file subst.c.
Referenced by expand_string_for_rhs(), expand_word_internal(), expand_word_leave_quoted(), list_transform(), param_expand(), parameter_brace_casemod(), parameter_brace_expand(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), parameter_brace_transform(), pos_params_modcase(), pos_params_pat_subst(), setifs(), and string_list_pos_params().
ifs_is_set
int ifs_is_set
Definition at line 157 of file subst.c.
Referenced by expand_word_internal(), param_expand(), parameter_brace_expand_word(), and setifs().
ifs_value
char* ifs_value
Definition at line 155 of file subst.c.
Referenced by dequote_escapes(), expand_word_internal(), getifs(), list_string(), quote_escapes_internal(), read_comsub(), setifs(), and word_list_split().
ifs_var
SHELL_VAR* ifs_var
Definition at line 154 of file subst.c.
Referenced by setifs(), and string_list_dollar_at().
inherit_errexit
int inherit_errexit = 0
Definition at line 167 of file subst.c.
Referenced by command_substitute(), and posix_initialize().
last_command_subst_pid
pid_t last_command_subst_pid = NO_PID
Definition at line 150 of file subst.c.
Referenced by command_substitute(), decode_prompt_string(), execute_null_command(), and execute_simple_command().
no_longjmp_on_fatal_error
int no_longjmp_on_fatal_error = 0
Definition at line 181 of file subst.c.
Referenced by expand_prompt_string(), expr_streval(), extract_command_subst(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), skip_matched_pair(), skip_to_delim(), and string_extract_double_quoted().
patsub_replacement
int patsub_replacement = 1
Definition at line 192 of file subst.c.
Referenced by parameter_brace_patsub().
singlequote_translations
int singlequote_translations extern
Definition at line 50 of file locale.c.
Referenced by expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), parse_matched_pair(), and read_token_word().
subst_assign_varlist
WORD_LIST* subst_assign_varlist = (WORD_LIST *)NULL
Definition at line 177 of file subst.c.
Referenced by _run_trap_internal(), command_substitute(), expand_word_list_internal(), run_pending_traps(), run_sigchld_trap(), and separate_out_assignments().
wordexp_only
int wordexp_only extern
Definition at line 229 of file shell.c.
Referenced by command_substitute(), and main().