Fennix Kernel: Kernel/Core/UndefinedBehaviorSanitization.c File Reference
UndefinedBehaviorSanitization.c File Reference
#include "ubsan.h"
#include <convert.h>
#include <debug.h>
Macros
#define is_aligned(value, alignment) !(value & (alignment - 1))
Functions
void __asan_report_load1 (void *unknown)
void __asan_report_load2 (void *unknown)
void __asan_report_load4 (void *unknown)
void __asan_report_load8 (void *unknown)
void __asan_report_load16 (void *unknown)
void __asan_report_load_n (void *unknown, uintptr_t size)
void __asan_report_store1 (void *unknown)
void __asan_report_store2 (void *unknown)
void __asan_report_store4 (void *unknown)
void __asan_report_store8 (void *unknown)
void __asan_report_store16 (void *unknown)
void __asan_report_store_n (void *unknown, uintptr_t size)
void __asan_report_load1_noabort (void *unknown)
void __asan_report_load2_noabort (void *unknown)
void __asan_report_load4_noabort (void *unknown)
void __asan_report_load8_noabort (void *unknown)
void __asan_report_load16_noabort (void *unknown)
void __asan_report_load_n_noabort (void *unknown, uintptr_t size)
void __asan_report_store1_noabort (void *unknown)
void __asan_report_store2_noabort (void *unknown)
void __asan_report_store4_noabort (void *unknown)
void __asan_report_store8_noabort (void *unknown)
void __asan_report_store16_noabort (void *unknown)
void __asan_report_store_n_noabort (void *unknown, uintptr_t size)
void __asan_stack_malloc_0 (uintptr_t size)
void __asan_stack_malloc_1 (uintptr_t size)
void __asan_stack_malloc_2 (uintptr_t size)
void __asan_stack_malloc_3 (uintptr_t size)
void __asan_stack_malloc_4 (uintptr_t size)
void __asan_stack_malloc_5 (uintptr_t size)
void __asan_stack_malloc_6 (uintptr_t size)
void __asan_stack_malloc_7 (uintptr_t size)
void __asan_stack_malloc_8 (uintptr_t size)
void __asan_stack_malloc_9 (uintptr_t size)
void __asan_stack_free_0 (void *ptr, uintptr_t size)
void __asan_stack_free_1 (void *ptr, uintptr_t size)
void __asan_stack_free_2 (void *ptr, uintptr_t size)
void __asan_stack_free_3 (void *ptr, uintptr_t size)
void __asan_stack_free_4 (void *ptr, uintptr_t size)
void __asan_stack_free_5 (void *ptr, uintptr_t size)
void __asan_stack_free_6 (void *ptr, uintptr_t size)
void __asan_stack_free_7 (void *ptr, uintptr_t size)
void __asan_stack_free_8 (void *ptr, uintptr_t size)
void __asan_stack_free_9 (void *ptr, uintptr_t size)
void __asan_poison_stack_memory (void *addr, uintptr_t size)
void __asan_unpoison_stack_memory (void *addr, uintptr_t size)
void __asan_before_dynamic_init (const char *module_name)
void __asan_after_dynamic_init (void)
void __asan_register_globals (void *unknown, size_t size)
void __asan_unregister_globals (void)
void __asan_init (void)
void __asan_version_mismatch_check_v8 (void)
void __asan_option_detect_stack_use_after_return (void)
__noreturn void __asan_handle_no_return (void)
bool UBSANMsg (const char *file, uint32_t line, uint32_t column)
void __ubsan_handle_type_mismatch_v1 (struct type_mismatch_v1_data *type_mismatch, uintptr_t pointer)
void __ubsan_handle_add_overflow (struct overflow_data *data)
void __ubsan_handle_sub_overflow (struct overflow_data *data)
void __ubsan_handle_mul_overflow (struct overflow_data *data)
void __ubsan_handle_divrem_overflow (struct overflow_data *data)
void __ubsan_handle_negate_overflow (struct overflow_data *data)
void __ubsan_handle_pointer_overflow (struct overflow_data *data)
void __ubsan_handle_shift_out_of_bounds (struct shift_out_of_bounds_data *data)
void __ubsan_handle_load_invalid_value (struct invalid_value_data *data)
void __ubsan_handle_out_of_bounds (struct array_out_of_bounds_data *data)
void __ubsan_handle_vla_bound_not_positive (struct negative_vla_data *data)
void __ubsan_handle_nonnull_return (struct nonnull_return_data *data)
void __ubsan_handle_nonnull_return_v1 (struct nonnull_return_data *data)
void __ubsan_handle_nonnull_arg (struct nonnull_arg_data *data)
void __ubsan_handle_builtin_unreachable (struct unreachable_data *data)
void __ubsan_handle_invalid_builtin (struct invalid_builtin_data *data)
void __ubsan_handle_missing_return (struct unreachable_data *data)
void __ubsan_vptr_type_cache (uintptr_t *cache, uintptr_t ptr)
void __ubsan_handle_dynamic_type_cache_miss (struct dynamic_type_cache_miss_data *data, uintptr_t ptr)
Variables
const char * Type_Check_Kinds []
Macro Definition Documentation
is_aligned
#define is_aligned (value, alignment) !(value & (alignment - 1))
Definition at line 103 of file UndefinedBehaviorSanitization.c.
Function Documentation
__asan_after_dynamic_init()
void __asan_after_dynamic_init (void)
Definition at line 87 of file UndefinedBehaviorSanitization.c.
 { ubsan("after dynamic init"); }
References ubsan.
__asan_before_dynamic_init()
void __asan_before_dynamic_init (const char * module_name)
Definition at line 86 of file UndefinedBehaviorSanitization.c.
 { ubsan("before dynamic init"); }
References ubsan.
__asan_handle_no_return()
__noreturn void __asan_handle_no_return (void)
Definition at line 96 of file UndefinedBehaviorSanitization.c.
 {
     ubsan("no_return");
     while (1)
         ;
 }
References ubsan.
__asan_init()
void __asan_init (void)
Definition at line 92 of file UndefinedBehaviorSanitization.c.
 { ubsan("init"); }
References ubsan.
__asan_option_detect_stack_use_after_return()
void __asan_option_detect_stack_use_after_return (void)
Definition at line 94 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack use after return"); }
References ubsan.
__asan_poison_stack_memory()
void __asan_poison_stack_memory (void * addr, uintptr_t size)
Definition at line 83 of file UndefinedBehaviorSanitization.c.
 { ubsan("poison stack memory"); }
References ubsan.
__asan_register_globals()
void __asan_register_globals (void * unknown, size_t size)
Definition at line 89 of file UndefinedBehaviorSanitization.c.
 { ubsan("register_globals"); }
References ubsan.
__asan_report_load1()
void __asan_report_load1 (void * unknown)
Definition at line 33 of file UndefinedBehaviorSanitization.c.
 { ubsan("load1"); }
References ubsan.
__asan_report_load16()
void __asan_report_load16 (void * unknown)
Definition at line 37 of file UndefinedBehaviorSanitization.c.
 { ubsan("load16"); }
References ubsan.
__asan_report_load16_noabort()
void __asan_report_load16_noabort (void * unknown)
Definition at line 51 of file UndefinedBehaviorSanitization.c.
 { ubsan("load16"); }
References ubsan.
__asan_report_load1_noabort()
void __asan_report_load1_noabort (void * unknown)
Definition at line 47 of file UndefinedBehaviorSanitization.c.
 { ubsan("load1"); }
References ubsan.
__asan_report_load2()
void __asan_report_load2 (void * unknown)
Definition at line 34 of file UndefinedBehaviorSanitization.c.
 { ubsan("load2"); }
References ubsan.
__asan_report_load2_noabort()
void __asan_report_load2_noabort (void * unknown)
Definition at line 48 of file UndefinedBehaviorSanitization.c.
 { ubsan("load2"); }
References ubsan.
__asan_report_load4()
void __asan_report_load4 (void * unknown)
Definition at line 35 of file UndefinedBehaviorSanitization.c.
 { ubsan("load4"); }
References ubsan.
__asan_report_load4_noabort()
void __asan_report_load4_noabort (void * unknown)
Definition at line 49 of file UndefinedBehaviorSanitization.c.
 { ubsan("load4"); }
References ubsan.
__asan_report_load8()
void __asan_report_load8 (void * unknown)
Definition at line 36 of file UndefinedBehaviorSanitization.c.
 { ubsan("load8"); }
References ubsan.
__asan_report_load8_noabort()
void __asan_report_load8_noabort (void * unknown)
Definition at line 50 of file UndefinedBehaviorSanitization.c.
 { ubsan("load8"); }
References ubsan.
__asan_report_load_n()
void __asan_report_load_n (void * unknown, uintptr_t size)
Definition at line 38 of file UndefinedBehaviorSanitization.c.
 { ubsan("loadn"); }
References ubsan.
__asan_report_load_n_noabort()
void __asan_report_load_n_noabort (void * unknown, uintptr_t size)
Definition at line 52 of file UndefinedBehaviorSanitization.c.
 { ubsan("loadn"); }
References ubsan.
__asan_report_store1()
void __asan_report_store1 (void * unknown)
Definition at line 40 of file UndefinedBehaviorSanitization.c.
 { ubsan("store1"); }
References ubsan.
__asan_report_store16()
void __asan_report_store16 (void * unknown)
Definition at line 44 of file UndefinedBehaviorSanitization.c.
 { ubsan("store16"); }
References ubsan.
__asan_report_store16_noabort()
void __asan_report_store16_noabort (void * unknown)
Definition at line 58 of file UndefinedBehaviorSanitization.c.
 { ubsan("store16"); }
References ubsan.
__asan_report_store1_noabort()
void __asan_report_store1_noabort (void * unknown)
Definition at line 54 of file UndefinedBehaviorSanitization.c.
 { ubsan("store1"); }
References ubsan.
__asan_report_store2()
void __asan_report_store2 (void * unknown)
Definition at line 41 of file UndefinedBehaviorSanitization.c.
 { ubsan("store2"); }
References ubsan.
__asan_report_store2_noabort()
void __asan_report_store2_noabort (void * unknown)
Definition at line 55 of file UndefinedBehaviorSanitization.c.
 { ubsan("store2"); }
References ubsan.
__asan_report_store4()
void __asan_report_store4 (void * unknown)
Definition at line 42 of file UndefinedBehaviorSanitization.c.
 { ubsan("store4"); }
References ubsan.
__asan_report_store4_noabort()
void __asan_report_store4_noabort (void * unknown)
Definition at line 56 of file UndefinedBehaviorSanitization.c.
 { ubsan("store4"); }
References ubsan.
__asan_report_store8()
void __asan_report_store8 (void * unknown)
Definition at line 43 of file UndefinedBehaviorSanitization.c.
 { ubsan("store8"); }
References ubsan.
__asan_report_store8_noabort()
void __asan_report_store8_noabort (void * unknown)
Definition at line 57 of file UndefinedBehaviorSanitization.c.
 { ubsan("store8"); }
References ubsan.
__asan_report_store_n()
void __asan_report_store_n (void * unknown, uintptr_t size)
Definition at line 45 of file UndefinedBehaviorSanitization.c.
 { ubsan("storen"); }
References ubsan.
__asan_report_store_n_noabort()
void __asan_report_store_n_noabort (void * unknown, uintptr_t size)
Definition at line 59 of file UndefinedBehaviorSanitization.c.
 { ubsan("storen"); }
References ubsan.
__asan_stack_free_0()
void __asan_stack_free_0 (void * ptr, uintptr_t size)
Definition at line 72 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 0"); }
References ubsan.
__asan_stack_free_1()
void __asan_stack_free_1 (void * ptr, uintptr_t size)
Definition at line 73 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 1"); }
References ubsan.
__asan_stack_free_2()
void __asan_stack_free_2 (void * ptr, uintptr_t size)
Definition at line 74 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 2"); }
References ubsan.
__asan_stack_free_3()
void __asan_stack_free_3 (void * ptr, uintptr_t size)
Definition at line 75 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 3"); }
References ubsan.
__asan_stack_free_4()
void __asan_stack_free_4 (void * ptr, uintptr_t size)
Definition at line 76 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 4"); }
References ubsan.
__asan_stack_free_5()
void __asan_stack_free_5 (void * ptr, uintptr_t size)
Definition at line 77 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 5"); }
References ubsan.
__asan_stack_free_6()
void __asan_stack_free_6 (void * ptr, uintptr_t size)
Definition at line 78 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 6"); }
References ubsan.
__asan_stack_free_7()
void __asan_stack_free_7 (void * ptr, uintptr_t size)
Definition at line 79 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 7"); }
References ubsan.
__asan_stack_free_8()
void __asan_stack_free_8 (void * ptr, uintptr_t size)
Definition at line 80 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 8"); }
References ubsan.
__asan_stack_free_9()
void __asan_stack_free_9 (void * ptr, uintptr_t size)
Definition at line 81 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack free 9"); }
References ubsan.
__asan_stack_malloc_0()
void __asan_stack_malloc_0 (uintptr_t size)
Definition at line 61 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 0"); }
References ubsan.
__asan_stack_malloc_1()
void __asan_stack_malloc_1 (uintptr_t size)
Definition at line 62 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 1"); }
References ubsan.
__asan_stack_malloc_2()
void __asan_stack_malloc_2 (uintptr_t size)
Definition at line 63 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 2"); }
References ubsan.
__asan_stack_malloc_3()
void __asan_stack_malloc_3 (uintptr_t size)
Definition at line 64 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 3"); }
References ubsan.
__asan_stack_malloc_4()
void __asan_stack_malloc_4 (uintptr_t size)
Definition at line 65 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 4"); }
References ubsan.
__asan_stack_malloc_5()
void __asan_stack_malloc_5 (uintptr_t size)
Definition at line 66 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 5"); }
References ubsan.
__asan_stack_malloc_6()
void __asan_stack_malloc_6 (uintptr_t size)
Definition at line 67 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 6"); }
References ubsan.
__asan_stack_malloc_7()
void __asan_stack_malloc_7 (uintptr_t size)
Definition at line 68 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 7"); }
References ubsan.
__asan_stack_malloc_8()
void __asan_stack_malloc_8 (uintptr_t size)
Definition at line 69 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 8"); }
References ubsan.
__asan_stack_malloc_9()
void __asan_stack_malloc_9 (uintptr_t size)
Definition at line 70 of file UndefinedBehaviorSanitization.c.
 { ubsan("stack malloc 9"); }
References ubsan.
__asan_unpoison_stack_memory()
void __asan_unpoison_stack_memory (void * addr, uintptr_t size)
Definition at line 84 of file UndefinedBehaviorSanitization.c.
 { ubsan("unpoison stack memory"); }
References ubsan.
__asan_unregister_globals()
void __asan_unregister_globals (void)
Definition at line 90 of file UndefinedBehaviorSanitization.c.
 { ubsan("unregister_globals"); }
References ubsan.
__asan_version_mismatch_check_v8()
void __asan_version_mismatch_check_v8 (void)
Definition at line 93 of file UndefinedBehaviorSanitization.c.
 { ubsan("version_mismatch_check_v8"); }
References ubsan.
__ubsan_handle_add_overflow()
void __ubsan_handle_add_overflow (struct overflow_data * data)
Definition at line 188 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Addition overflow.");
 }
References source_location::column, source_location::file, source_location::line, overflow_data::location, ubsan, and UBSANMsg().
__ubsan_handle_builtin_unreachable()
void __ubsan_handle_builtin_unreachable (struct unreachable_data * data)
Definition at line 266 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Unreachable code reached.");
 }
References source_location::column, source_location::file, source_location::line, unreachable_data::location, ubsan, and UBSANMsg().
__ubsan_handle_divrem_overflow()
void __ubsan_handle_divrem_overflow (struct overflow_data * data)
Definition at line 206 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Division overflow.");
 }
References source_location::column, source_location::file, source_location::line, overflow_data::location, ubsan, and UBSANMsg().
__ubsan_handle_dynamic_type_cache_miss()
void __ubsan_handle_dynamic_type_cache_miss (struct dynamic_type_cache_miss_data * data, uintptr_t ptr)
Definition at line 290 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Dynamic type cache miss.");
 }
References source_location::column, source_location::file, source_location::line, dynamic_type_cache_miss_data::location, ubsan, and UBSANMsg().
__ubsan_handle_invalid_builtin()
void __ubsan_handle_invalid_builtin (struct invalid_builtin_data * data)
Definition at line 272 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Invalid builtin.");
 }
References source_location::column, source_location::file, source_location::line, invalid_builtin_data::location, ubsan, and UBSANMsg().
__ubsan_handle_load_invalid_value()
void __ubsan_handle_load_invalid_value (struct invalid_value_data * data)
Definition at line 230 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Invalid load value.");
 }
References source_location::column, source_location::file, source_location::line, invalid_value_data::location, ubsan, and UBSANMsg().
__ubsan_handle_missing_return()
void __ubsan_handle_missing_return (struct unreachable_data * data)
Definition at line 278 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Missing return.");
 }
References source_location::column, source_location::file, source_location::line, unreachable_data::location, ubsan, and UBSANMsg().
__ubsan_handle_mul_overflow()
void __ubsan_handle_mul_overflow (struct overflow_data * data)
Definition at line 200 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Multiplication overflow.");
 }
References source_location::column, source_location::file, source_location::line, overflow_data::location, ubsan, and UBSANMsg().
__ubsan_handle_negate_overflow()
void __ubsan_handle_negate_overflow (struct overflow_data * data)
Definition at line 212 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Negation overflow.");
 }
References source_location::column, source_location::file, source_location::line, overflow_data::location, ubsan, and UBSANMsg().
__ubsan_handle_nonnull_arg()
void __ubsan_handle_nonnull_arg (struct nonnull_arg_data * data)
Definition at line 260 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Non-null argument is null.");
 }
References source_location::column, source_location::file, source_location::line, nonnull_arg_data::location, ubsan, and UBSANMsg().
__ubsan_handle_nonnull_return()
void __ubsan_handle_nonnull_return (struct nonnull_return_data * data)
Definition at line 248 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Non-null return is null.");
 }
References source_location::column, source_location::file, source_location::line, nonnull_return_data::location, ubsan, and UBSANMsg().
__ubsan_handle_nonnull_return_v1()
void __ubsan_handle_nonnull_return_v1 (struct nonnull_return_data * data)
Definition at line 254 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Non-null return is null.");
 }
References source_location::column, source_location::file, source_location::line, nonnull_return_data::location, ubsan, and UBSANMsg().
__ubsan_handle_out_of_bounds()
void __ubsan_handle_out_of_bounds (struct array_out_of_bounds_data * data)
Definition at line 236 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Array out of bounds.");
 }
References source_location::column, source_location::file, source_location::line, array_out_of_bounds_data::location, ubsan, and UBSANMsg().
__ubsan_handle_pointer_overflow()
void __ubsan_handle_pointer_overflow (struct overflow_data * data)
Definition at line 218 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Pointer overflow.");
 }
References source_location::column, source_location::file, source_location::line, overflow_data::location, ubsan, and UBSANMsg().
__ubsan_handle_shift_out_of_bounds()
void __ubsan_handle_shift_out_of_bounds (struct shift_out_of_bounds_data * data)
Definition at line 224 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Shift out of bounds.");
 }
References source_location::column, source_location::file, source_location::line, shift_out_of_bounds_data::location, ubsan, and UBSANMsg().
__ubsan_handle_sub_overflow()
void __ubsan_handle_sub_overflow (struct overflow_data * data)
Definition at line 194 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Subtraction overflow.");
 }
References source_location::column, source_location::file, source_location::line, overflow_data::location, ubsan, and UBSANMsg().
__ubsan_handle_type_mismatch_v1()
void __ubsan_handle_type_mismatch_v1 (struct type_mismatch_v1_data * type_mismatch, uintptr_t pointer)
Definition at line 167 of file UndefinedBehaviorSanitization.c.
 {
     struct source_location *location = &type_mismatch->location;
     if (pointer == 0)
     {
         if (UBSANMsg(location->file, location->line, location->column))
             ubsan("Null pointer access.");
     }
     else if (type_mismatch->alignment != 0 && is_aligned(pointer, type_mismatch->alignment))
     {
         if (UBSANMsg(location->file, location->line, location->column))
             ubsan("Unaligned memory access %#llx.", pointer);
     }
     else
     {
         if (UBSANMsg(location->file, location->line, location->column))
             ubsan("%s address %#llx with insufficient space for object of type %s",
                   Type_Check_Kinds[type_mismatch->type_check_kind], (void *)pointer, type_mismatch->type->name);
     }
 }
References type_mismatch_v1_data::alignment, source_location::column, source_location::file, is_aligned, source_location::line, type_mismatch_v1_data::location, type_descriptor::name, type_mismatch_v1_data::type, type_mismatch_v1_data::type_check_kind, Type_Check_Kinds, ubsan, and UBSANMsg().
__ubsan_handle_vla_bound_not_positive()
void __ubsan_handle_vla_bound_not_positive (struct negative_vla_data * data)
Definition at line 242 of file UndefinedBehaviorSanitization.c.
 {
     if (UBSANMsg(data->location.file, data->location.line, data->location.column))
         ubsan("Variable-length argument is negative.");
 }
References source_location::column, source_location::file, source_location::line, negative_vla_data::location, ubsan, and UBSANMsg().
__ubsan_vptr_type_cache()
void __ubsan_vptr_type_cache (uintptr_t * cache, uintptr_t ptr)
Definition at line 284 of file UndefinedBehaviorSanitization.c.
 {
     ubsan("Vptr type cache.");
     *cache = ptr;
 }
References ubsan.
UBSANMsg()
bool UBSANMsg (const char * file, uint32_t line, uint32_t column)
Definition at line 118 of file UndefinedBehaviorSanitization.c.
 {
     // blacklist
     // if (strstr(file, "liballoc") ||
     //     strstr(file, "cwalk") ||
     //     strstr(file, "AdvancedConfigurationAndPowerInterface") ||
     //     strstr(file, "SystemManagementBIOS"))
     //     return false;
     if (strstr(file, "AdvancedConfigurationAndPowerInterface.cpp") &&
         (line == 17 && column == 47))
         return false;
     if (strstr(file, "SystemManagementBIOS.cpp") &&
         ((line == 30 && column == 21) ||
          (line == 27 && column == 49) ||
          (line == 45 && column == 26)))
         return false;
     if (strstr(file, "cwalk.c") &&
         ((line == 1047 && column == 15)))
         return false;
     if (strstr(file, "liballoc_1_1.c"))
         return false;
     if (strstr(file, "display.hpp") &&
         ((line == 113 && column == 43)))
         return false;
     if (strstr(file, "Xalloc.hpp") &&
         (line == 48 && column == 28))
         return false;
     if (strstr(file, "Task.cpp") &&
         ((line == 839 && column == 22) ||
          (line == 847 && column == 45) ||
          (line == 853 && column == 22) ||
          (line == 859 && column == 32) ||
          (line == 865 && column == 22) ||
          (line == 871 && column == 32) ||
          (line == 877 && column == 22) ||
          (line == 45 && column == 26)))
         return false;
     ubsan("\t\tIn File: %s:%i:%i", file, line, column);
     return true;
 }
References strstr(), and ubsan.
Referenced by __ubsan_handle_add_overflow(), __ubsan_handle_builtin_unreachable(), __ubsan_handle_divrem_overflow(), __ubsan_handle_dynamic_type_cache_miss(), __ubsan_handle_invalid_builtin(), __ubsan_handle_load_invalid_value(), __ubsan_handle_missing_return(), __ubsan_handle_mul_overflow(), __ubsan_handle_negate_overflow(), __ubsan_handle_nonnull_arg(), __ubsan_handle_nonnull_return(), __ubsan_handle_nonnull_return_v1(), __ubsan_handle_out_of_bounds(), __ubsan_handle_pointer_overflow(), __ubsan_handle_shift_out_of_bounds(), __ubsan_handle_sub_overflow(), __ubsan_handle_type_mismatch_v1(), and __ubsan_handle_vla_bound_not_positive().
Variable Documentation
Type_Check_Kinds
const char* Type_Check_Kinds[]
Initial value:
= {
    "Load of",
    "Store to",
    "Reference binding to",
    "Member access within",
    "Member call on",
    "Constructor call on",
    "Downcast of",
    "Downcast of",
    "Upcast of",
    "Cast to virtual base of",
}
Definition at line 105 of file UndefinedBehaviorSanitization.c.
Referenced by __ubsan_handle_type_mismatch_v1().