Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/i_joystick.h File Reference
i_joystick.h File Reference
Macros
#define NUM_VIRTUAL_BUTTONS 10
#define BUTTON_AXIS 0x10000
#define IS_BUTTON_AXIS(axis) ((axis) >= 0 && ((axis) & BUTTON_AXIS) != 0)
#define BUTTON_AXIS_NEG(axis) ((axis) & 0xff)
#define BUTTON_AXIS_POS(axis) (((axis) >> 8) & 0xff)
#define CREATE_BUTTON_AXIS(neg, pos) (BUTTON_AXIS | (neg) | ((pos) << 8))
#define HAT_AXIS 0x20000
#define IS_HAT_AXIS(axis) ((axis) >= 0 && ((axis) & HAT_AXIS) != 0)
#define HAT_AXIS_HAT(axis) ((axis) & 0xff)
#define HAT_AXIS_DIRECTION(axis) (((axis) >> 8) & 0xff)
#define CREATE_HAT_AXIS(hat, direction) (HAT_AXIS | (hat) | ((direction) << 8))
#define HAT_AXIS_HORIZONTAL 1
#define HAT_AXIS_VERTICAL 2
Functions
void I_InitJoystick (void)
void I_ShutdownJoystick (void)
void I_UpdateJoystick (void)
void I_BindJoystickVariables (void)
Macro Definition Documentation
BUTTON_AXIS
#define BUTTON_AXIS 0x10000
Definition at line 33 of file i_joystick.h.
BUTTON_AXIS_NEG
#define BUTTON_AXIS_NEG (axis) ((axis) & 0xff)
Definition at line 39 of file i_joystick.h.
BUTTON_AXIS_POS
#define BUTTON_AXIS_POS (axis) (((axis) >> 8) & 0xff)
Definition at line 40 of file i_joystick.h.
CREATE_BUTTON_AXIS
#define CREATE_BUTTON_AXIS (neg, pos) (BUTTON_AXIS | (neg) | ((pos) << 8))
Definition at line 43 of file i_joystick.h.
CREATE_HAT_AXIS
#define CREATE_HAT_AXIS (hat, direction) (HAT_AXIS | (hat) | ((direction) << 8))
Definition at line 57 of file i_joystick.h.
HAT_AXIS
#define HAT_AXIS 0x20000
Definition at line 48 of file i_joystick.h.
HAT_AXIS_DIRECTION
#define HAT_AXIS_DIRECTION (axis) (((axis) >> 8) & 0xff)
Definition at line 55 of file i_joystick.h.
HAT_AXIS_HAT
#define HAT_AXIS_HAT (axis) ((axis) & 0xff)
Definition at line 53 of file i_joystick.h.
HAT_AXIS_HORIZONTAL
#define HAT_AXIS_HORIZONTAL 1
Definition at line 60 of file i_joystick.h.
HAT_AXIS_VERTICAL
#define HAT_AXIS_VERTICAL 2
Definition at line 61 of file i_joystick.h.
IS_BUTTON_AXIS
#define IS_BUTTON_AXIS (axis) ((axis) >= 0 && ((axis) & BUTTON_AXIS) != 0)
Definition at line 36 of file i_joystick.h.
IS_HAT_AXIS
#define IS_HAT_AXIS (axis) ((axis) >= 0 && ((axis) & HAT_AXIS) != 0)
Definition at line 50 of file i_joystick.h.
NUM_VIRTUAL_BUTTONS
#define NUM_VIRTUAL_BUTTONS 10
Definition at line 25 of file i_joystick.h.
Function Documentation
I_BindJoystickVariables()
void I_BindJoystickVariables (void)
Definition at line 339 of file i_joystick.c.
 {
     int i;
     M_BindVariable("use_joystick",          &usejoystick);
     M_BindVariable("joystick_index",        &joystick_index);
     M_BindVariable("joystick_x_axis",       &joystick_x_axis);
     M_BindVariable("joystick_y_axis",       &joystick_y_axis);
     M_BindVariable("joystick_strafe_axis",  &joystick_strafe_axis);
     M_BindVariable("joystick_x_invert",     &joystick_x_invert);
     M_BindVariable("joystick_y_invert",     &joystick_y_invert);
     M_BindVariable("joystick_strafe_invert",&joystick_strafe_invert);
     for (i = 0; i < NUM_VIRTUAL_BUTTONS; ++i)
     {
         char name[32];
         M_snprintf(name, sizeof(name), "joystick_physical_button%i", i);
         M_BindVariable(name, &joystick_physical_buttons[i]);
     }
 }
References i, joystick_index, joystick_physical_buttons, joystick_strafe_axis, joystick_strafe_invert, joystick_x_axis, joystick_x_invert, joystick_y_axis, joystick_y_invert, M_BindVariable(), M_snprintf(), name, NUM_VIRTUAL_BUTTONS, and usejoystick.
Referenced by D_BindVariables().
I_InitJoystick()
void I_InitJoystick (void)
Definition at line 115 of file i_joystick.c.
 {
 #ifdef ORIGCODE
     if (!usejoystick)
     {
         return;
     }
     if (SDL_Init(SDL_INIT_JOYSTICK) < 0)
     {
         return;
     }
     if (joystick_index < 0 || joystick_index >= SDL_NumJoysticks())
     {
         printf("I_InitJoystick: Invalid joystick ID: %i\n", joystick_index);
         SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
         return;
     }
     // Open the joystick
     joystick = SDL_JoystickOpen(joystick_index);
     if (joystick == NULL)
     {
         printf("I_InitJoystick: Failed to open joystick #%i\n",
                joystick_index);
         SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
         return;
     }
     if (!IsValidAxis(joystick_x_axis)
      || !IsValidAxis(joystick_y_axis)
      || !IsValidAxis(joystick_strafe_axis))
     {
         printf("I_InitJoystick: Invalid joystick axis for joystick #%i "
                "(run joystick setup again)\n",
                joystick_index);
         SDL_JoystickClose(joystick);
         joystick = NULL;
         SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
     }
     SDL_JoystickEventState(SDL_ENABLE);
     // Initialized okay!
     printf("I_InitJoystick: %s\n", SDL_JoystickName(joystick_index));
     I_AtExit(I_ShutdownJoystick, true);
 #endif
 }
References I_AtExit(), I_ShutdownJoystick(), joystick_index, joystick_strafe_axis, joystick_x_axis, joystick_y_axis, NULL, printf(), and usejoystick.
Referenced by D_DoomMain().
I_ShutdownJoystick()
void I_ShutdownJoystick (void)
Definition at line 77 of file i_joystick.c.
 {
 #ifdef ORIGCODE
     if (joystick != NULL)
     {
         SDL_JoystickClose(joystick);
         joystick = NULL;
         SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
     }
 #endif
 }
References NULL.
Referenced by I_InitJoystick().
I_UpdateJoystick()
void I_UpdateJoystick (void)
Definition at line 321 of file i_joystick.c.
 {
 #ifdef ORIGCODE
     if (joystick != NULL)
     {
         event_t ev;
         ev.type = ev_joystick;
         ev.data1 = GetButtonsState();
         ev.data2 = GetAxisState(joystick_x_axis, joystick_x_invert);
         ev.data3 = GetAxisState(joystick_y_axis, joystick_y_invert);
         ev.data4 = GetAxisState(joystick_strafe_axis, joystick_strafe_invert);
         D_PostEvent(&ev);
     }
 #endif
 }
References D_PostEvent(), event_t::data1, event_t::data2, event_t::data3, event_t::data4, ev_joystick, joystick_strafe_axis, joystick_strafe_invert, joystick_x_axis, joystick_x_invert, joystick_y_axis, joystick_y_invert, NULL, and event_t::type.