Fennix Userspace: Userspace/apps/base/busybox/networking/ftpd.c File Reference
ftpd.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <syslog.h>
#include <netinet/tcp.h>
Data Structures
struct globals
Macros
#define FTP_DATACONN 150
#define FTP_NOOPOK 200
#define FTP_TYPEOK 200
#define FTP_PORTOK 200
#define FTP_STRUOK 200
#define FTP_MODEOK 200
#define FTP_ALLOOK 202
#define FTP_STATOK 211
#define FTP_STATFILE_OK 213
#define FTP_HELP 214
#define FTP_SYSTOK 215
#define FTP_GREET 220
#define FTP_GOODBYE 221
#define FTP_TRANSFEROK 226
#define FTP_PASVOK 227
#define FTP_EPSVOK 229
#define FTP_LOGINOK 230
#define FTP_CWDOK 250
#define FTP_RMDIROK 250
#define FTP_DELEOK 250
#define FTP_RENAMEOK 250
#define FTP_PWDOK 257
#define FTP_MKDIROK 257
#define FTP_GIVEPWORD 331
#define FTP_RESTOK 350
#define FTP_RNFROK 350
#define FTP_TIMEOUT 421
#define FTP_BADSENDCONN 425
#define FTP_BADSENDNET 426
#define FTP_BADSENDFILE 451
#define FTP_BADCMD 500
#define FTP_COMMANDNOTIMPL 502
#define FTP_NEEDUSER 503
#define FTP_NEEDRNFR 503
#define FTP_BADSTRU 504
#define FTP_BADMODE 504
#define FTP_LOGINERR 530
#define FTP_FILEFAIL 550
#define FTP_NOPERM 550
#define FTP_UPLOADFAIL 553
#define STR1(s) #s
#define STR(s) STR1(s)
#define STRNUM32(s)
#define STRNUM32sp(s)
#define MSG_OK "Operation successful\r\n"
#define MSG_ERR "Error\r\n"
#define G (*ptr_to_globals)
#define INIT_G()
#define WRITE_OK(a) cmdio_write_ok(STRNUM32sp(a))
#define WRITE_ERR(a) cmdio_write_error(STRNUM32sp(a))
#define mk_const4(a, b, c, d) (((a * 0x100 + b) * 0x100 + c) * 0x100 + d)
#define mk_const3(a, b, c) ((a * 0x100 + b) * 0x100 + c)
Enumerations
enum { SHIFT2 = 0 * BB_LITTLE_ENDIAN + 24 * BB_BIG_ENDIAN , SHIFT1 = 8 * BB_LITTLE_ENDIAN + 16 * BB_BIG_ENDIAN , SHIFT0 = 16 * BB_LITTLE_ENDIAN + 8 * BB_BIG_ENDIAN , SHIFTsp = 24 * BB_LITTLE_ENDIAN + 0 * BB_BIG_ENDIAN }
enum { USE_CTRL_CONN = 1 , LONG_LISTING = 2 }
enum {
const_ALLO = mk_const4('A', 'L', 'L', 'O') , const_APPE = mk_const4('A', 'P', 'P', 'E') , const_CDUP = mk_const4('C', 'D', 'U', 'P') , const_CWD = mk_const3('C', 'W', 'D') ,
const_DELE = mk_const4('D', 'E', 'L', 'E') , const_EPSV = mk_const4('E', 'P', 'S', 'V') , const_FEAT = mk_const4('F', 'E', 'A', 'T') , const_HELP = mk_const4('H', 'E', 'L', 'P') ,
const_LIST = mk_const4('L', 'I', 'S', 'T') , const_MDTM = mk_const4('M', 'D', 'T', 'M') , const_MKD = mk_const3('M', 'K', 'D') , const_MODE = mk_const4('M', 'O', 'D', 'E') ,
const_NLST = mk_const4('N', 'L', 'S', 'T') , const_NOOP = mk_const4('N', 'O', 'O', 'P') , const_PASS = mk_const4('P', 'A', 'S', 'S') , const_PASV = mk_const4('P', 'A', 'S', 'V') ,
const_PORT = mk_const4('P', 'O', 'R', 'T') , const_PWD = mk_const3('P', 'W', 'D') , const_XPWD = mk_const4('X', 'P', 'W', 'D') , const_QUIT = mk_const4('Q', 'U', 'I', 'T') ,
const_REST = mk_const4('R', 'E', 'S', 'T') , const_RETR = mk_const4('R', 'E', 'T', 'R') , const_RMD = mk_const3('R', 'M', 'D') , const_RNFR = mk_const4('R', 'N', 'F', 'R') ,
const_RNTO = mk_const4('R', 'N', 'T', 'O') , const_SIZE = mk_const4('S', 'I', 'Z', 'E') , const_STAT = mk_const4('S', 'T', 'A', 'T') , const_STOR = mk_const4('S', 'T', 'O', 'R') ,
const_STOU = mk_const4('S', 'T', 'O', 'U') , const_STRU = mk_const4('S', 'T', 'R', 'U') , const_SYST = mk_const4('S', 'Y', 'S', 'T') , const_TYPE = mk_const4('T', 'Y', 'P', 'E') ,
const_USER = mk_const4('U', 'S', 'E', 'R') , OPT_l = (1 << 0) , OPT_1 = (1 << 1) , BIT_A = (!BB_MMU) * 2 ,
OPT_A = (1 << (BIT_A + 0)) , OPT_v = (1 << (BIT_A + 1)) , OPT_S = (1 << (BIT_A + 2)) , OPT_w = (1 << (BIT_A + 3)) * ENABLE_FEATURE_FTPD_WRITE
}
Functions
static char * escape_text (const char *prepend, const char *str, unsigned escapee)
static unsigned replace_char (char *str, char from, char to)
static void verbose_log (const char *str)
static void cmdio_write (uint32_t status_str, const char *str)
static void cmdio_write_ok (unsigned status)
static void cmdio_write_error (unsigned status)
static void cmdio_write_raw (const char *p_text)
static void timeout_handler (int sig UNUSED_PARAM)
static void handle_pwd (void)
static void handle_cwd (void)
static void handle_cdup (void)
static void handle_stat (void)
static void handle_feat (unsigned status)
static int port_active (void)
static int pasv_active (void)
static void port_pasv_cleanup (void)
static int ftpdataio_get_pasv_fd (void)
static int get_remote_transfer_fd (const char *p_status_msg)
static int port_or_pasv_was_seen (void)
static unsigned bind_for_passive_mode (void)
static void handle_pasv (void)
static void handle_epsv (void)
static void handle_port (void)
static void handle_rest (void)
static void handle_retr (void)
static int popen_ls (const char *opt)
static void handle_dir_common (int opts)
static void handle_list (void)
static void handle_nlst (void)
static void handle_stat_file (void)
static void handle_size_or_mdtm (int need_size)
static uint32_t cmdio_get_cmd_and_arg (void)
int ftpd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
FTP_ALLOOK
#define FTP_ALLOOK 202
Definition at line 95 of file ftpd.c.
FTP_BADCMD
#define FTP_BADCMD 500
Definition at line 120 of file ftpd.c.
FTP_BADMODE
#define FTP_BADMODE 504
Definition at line 125 of file ftpd.c.
FTP_BADSENDCONN
#define FTP_BADSENDCONN 425
Definition at line 117 of file ftpd.c.
FTP_BADSENDFILE
#define FTP_BADSENDFILE 451
Definition at line 119 of file ftpd.c.
FTP_BADSENDNET
#define FTP_BADSENDNET 426
Definition at line 118 of file ftpd.c.
FTP_BADSTRU
#define FTP_BADSTRU 504
Definition at line 124 of file ftpd.c.
FTP_COMMANDNOTIMPL
#define FTP_COMMANDNOTIMPL 502
Definition at line 121 of file ftpd.c.
FTP_CWDOK
#define FTP_CWDOK 250
Definition at line 107 of file ftpd.c.
FTP_DATACONN
#define FTP_DATACONN 150
Definition at line 89 of file ftpd.c.
FTP_DELEOK
#define FTP_DELEOK 250
Definition at line 109 of file ftpd.c.
FTP_EPSVOK
#define FTP_EPSVOK 229
Definition at line 105 of file ftpd.c.
FTP_FILEFAIL
#define FTP_FILEFAIL 550
Definition at line 127 of file ftpd.c.
FTP_GIVEPWORD
#define FTP_GIVEPWORD 331
Definition at line 113 of file ftpd.c.
FTP_GOODBYE
#define FTP_GOODBYE 221
Definition at line 101 of file ftpd.c.
FTP_GREET
#define FTP_GREET 220
Definition at line 100 of file ftpd.c.
FTP_HELP
#define FTP_HELP 214
Definition at line 98 of file ftpd.c.
FTP_LOGINERR
#define FTP_LOGINERR 530
Definition at line 126 of file ftpd.c.
FTP_LOGINOK
#define FTP_LOGINOK 230
Definition at line 106 of file ftpd.c.
FTP_MKDIROK
#define FTP_MKDIROK 257
Definition at line 112 of file ftpd.c.
FTP_MODEOK
#define FTP_MODEOK 200
Definition at line 94 of file ftpd.c.
FTP_NEEDRNFR
#define FTP_NEEDRNFR 503
Definition at line 123 of file ftpd.c.
FTP_NEEDUSER
#define FTP_NEEDUSER 503
Definition at line 122 of file ftpd.c.
FTP_NOOPOK
#define FTP_NOOPOK 200
Definition at line 90 of file ftpd.c.
FTP_NOPERM
#define FTP_NOPERM 550
Definition at line 128 of file ftpd.c.
FTP_PASVOK
#define FTP_PASVOK 227
Definition at line 103 of file ftpd.c.
FTP_PORTOK
#define FTP_PORTOK 200
Definition at line 92 of file ftpd.c.
FTP_PWDOK
#define FTP_PWDOK 257
Definition at line 111 of file ftpd.c.
FTP_RENAMEOK
#define FTP_RENAMEOK 250
Definition at line 110 of file ftpd.c.
FTP_RESTOK
#define FTP_RESTOK 350
Definition at line 114 of file ftpd.c.
FTP_RMDIROK
#define FTP_RMDIROK 250
Definition at line 108 of file ftpd.c.
FTP_RNFROK
#define FTP_RNFROK 350
Definition at line 115 of file ftpd.c.
FTP_STATFILE_OK
#define FTP_STATFILE_OK 213
Definition at line 97 of file ftpd.c.
FTP_STATOK
#define FTP_STATOK 211
Definition at line 96 of file ftpd.c.
FTP_STRUOK
#define FTP_STRUOK 200
Definition at line 93 of file ftpd.c.
FTP_SYSTOK
#define FTP_SYSTOK 215
Definition at line 99 of file ftpd.c.
FTP_TIMEOUT
#define FTP_TIMEOUT 421
Definition at line 116 of file ftpd.c.
FTP_TRANSFEROK
#define FTP_TRANSFEROK 226
Definition at line 102 of file ftpd.c.
FTP_TYPEOK
#define FTP_TYPEOK 200
Definition at line 91 of file ftpd.c.
FTP_UPLOADFAIL
#define FTP_UPLOADFAIL 553
Definition at line 129 of file ftpd.c.
G
#define G (*ptr_to_globals)
Definition at line 180 of file ftpd.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    /*setup_common_bufsiz();*/ \
    \
    /* Moved to main */ \
    /*strcpy(G.msg_ok  + 4, MSG_OK );*/ \
    /*strcpy(G.msg_err + 4, MSG_ERR);*/ \
} while (0)
Definition at line 183 of file ftpd.c.
mk_const3
#define mk_const3 (a, b, c) ((a * 0x100 + b) * 0x100 + c)
Definition at line 1124 of file ftpd.c.
mk_const4
#define mk_const4 (a, b, c, d) (((a * 0x100 + b) * 0x100 + c) * 0x100 + d)
Definition at line 1123 of file ftpd.c.
MSG_ERR
#define MSG_ERR "Error\r\n"
Definition at line 156 of file ftpd.c.
MSG_OK
#define MSG_OK "Operation successful\r\n"
Definition at line 155 of file ftpd.c.
STR
#define STR (s) STR1(s)
Definition at line 132 of file ftpd.c.
STR1
#define STR1 (s) #s
Definition at line 131 of file ftpd.c.
STRNUM32
#define STRNUM32 (s)
Value:
    (uint32_t)(0 \
    | (('0' + ((s) / 1 % 10)) << SHIFT0) \
    | (('0' + ((s) / 10 % 10)) << SHIFT1) \
    | (('0' + ((s) / 100 % 10)) << SHIFT2) \
)
Definition at line 143 of file ftpd.c.
STRNUM32sp
#define STRNUM32sp (s)
Value:
    (uint32_t)(0 \
    | (' ' << SHIFTsp) \
    | (('0' + ((s) / 1 % 10)) << SHIFT0) \
    | (('0' + ((s) / 10 % 10)) << SHIFT1) \
    | (('0' + ((s) / 100 % 10)) << SHIFT2) \
)
Definition at line 148 of file ftpd.c.
WRITE_ERR
#define WRITE_ERR (a) cmdio_write_error(STRNUM32sp(a))
Definition at line 287 of file ftpd.c.
WRITE_OK
#define WRITE_OK (a) cmdio_write_ok(STRNUM32sp(a))
Definition at line 276 of file ftpd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SHIFT2
SHIFT1
SHIFT0
SHIFTsp
Definition at line 135 of file ftpd.c.
      {
     /* Shift for Nth decimal digit */
     SHIFT2  =  0 * BB_LITTLE_ENDIAN + 24 * BB_BIG_ENDIAN,
     SHIFT1  =  8 * BB_LITTLE_ENDIAN + 16 * BB_BIG_ENDIAN,
     SHIFT0  = 16 * BB_LITTLE_ENDIAN + 8 * BB_BIG_ENDIAN,
     /* And for 4th position (space) */
     SHIFTsp = 24 * BB_LITTLE_ENDIAN + 0 * BB_BIG_ENDIAN,
 };
anonymous enum
anonymous enum
Enumerator
USE_CTRL_CONN
LONG_LISTING
Definition at line 746 of file ftpd.c.
      {
     USE_CTRL_CONN = 1,
     LONG_LISTING = 2,
 };
anonymous enum
anonymous enum
Enumerator
const_ALLO
const_APPE
const_CDUP
const_CWD
const_DELE
const_EPSV
const_FEAT
const_HELP
const_LIST
const_MDTM
const_MKD
const_MODE
const_NLST
const_NOOP
const_PASS
const_PASV
const_PORT
const_PWD
const_XPWD
const_QUIT
const_REST
const_RETR
const_RMD
const_RNFR
const_RNTO
const_SIZE
const_STAT
const_STOR
const_STOU
const_STRU
const_SYST
const_TYPE
const_USER
OPT_l
OPT_1
BIT_A
OPT_A
OPT_v
OPT_S
OPT_w
Definition at line 1125 of file ftpd.c.
      {
     const_ALLO = mk_const4('A', 'L', 'L', 'O'),
     const_APPE = mk_const4('A', 'P', 'P', 'E'),
     const_CDUP = mk_const4('C', 'D', 'U', 'P'),
     const_CWD  = mk_const3('C', 'W', 'D'),
     const_DELE = mk_const4('D', 'E', 'L', 'E'),
     const_EPSV = mk_const4('E', 'P', 'S', 'V'),
     const_FEAT = mk_const4('F', 'E', 'A', 'T'),
     const_HELP = mk_const4('H', 'E', 'L', 'P'),
     const_LIST = mk_const4('L', 'I', 'S', 'T'),
     const_MDTM = mk_const4('M', 'D', 'T', 'M'),
     const_MKD  = mk_const3('M', 'K', 'D'),
     const_MODE = mk_const4('M', 'O', 'D', 'E'),
     const_NLST = mk_const4('N', 'L', 'S', 'T'),
     const_NOOP = mk_const4('N', 'O', 'O', 'P'),
     const_PASS = mk_const4('P', 'A', 'S', 'S'),
     const_PASV = mk_const4('P', 'A', 'S', 'V'),
     const_PORT = mk_const4('P', 'O', 'R', 'T'),
     const_PWD  = mk_const3('P', 'W', 'D'),
     /* Same as PWD. Reportedly used by windows ftp client */
     const_XPWD = mk_const4('X', 'P', 'W', 'D'),
     const_QUIT = mk_const4('Q', 'U', 'I', 'T'),
     const_REST = mk_const4('R', 'E', 'S', 'T'),
     const_RETR = mk_const4('R', 'E', 'T', 'R'),
     const_RMD  = mk_const3('R', 'M', 'D'),
     const_RNFR = mk_const4('R', 'N', 'F', 'R'),
     const_RNTO = mk_const4('R', 'N', 'T', 'O'),
     const_SIZE = mk_const4('S', 'I', 'Z', 'E'),
     const_STAT = mk_const4('S', 'T', 'A', 'T'),
     const_STOR = mk_const4('S', 'T', 'O', 'R'),
     const_STOU = mk_const4('S', 'T', 'O', 'U'),
     const_STRU = mk_const4('S', 'T', 'R', 'U'),
     const_SYST = mk_const4('S', 'Y', 'S', 'T'),
     const_TYPE = mk_const4('T', 'Y', 'P', 'E'),
     const_USER = mk_const4('U', 'S', 'E', 'R'),
 #if !BB_MMU
     OPT_l = (1 << 0),
     OPT_1 = (1 << 1),
 #endif
     BIT_A =        (!BB_MMU) * 2,
     OPT_A = (1 << (BIT_A + 0)),
     OPT_v = (1 << (BIT_A + 1)),
     OPT_S = (1 << (BIT_A + 2)),
     OPT_w = (1 << (BIT_A + 3)) * ENABLE_FEATURE_FTPD_WRITE,
 };
Function Documentation
bind_for_passive_mode()
static unsigned bind_for_passive_mode (void) static
Definition at line 484 of file ftpd.c.
 {
     int fd;
     unsigned port;
     port_pasv_cleanup();
     G.pasv_listen_fd = fd = xsocket(G.local_addr->u.sa.sa_family, SOCK_STREAM, 0);
     setsockopt_reuseaddr(fd);
     set_nport(&G.local_addr->u.sa, 0);
     xbind(fd, &G.local_addr->u.sa, G.local_addr->len);
     xlisten(fd, 1);
     getsockname(fd, &G.local_addr->u.sa, &G.local_addr->len);
     port = get_nport(&G.local_addr->u.sa);
     port = ntohs(port);
     return port;
 }
References fd, G, get_nport(), getsockname(), ntohs(), port, port_pasv_cleanup(), set_nport(), setsockopt_reuseaddr(), SOCK_STREAM, xbind(), xlisten(), and xsocket().
Referenced by handle_epsv(), and handle_pasv().
cmdio_get_cmd_and_arg()
static uint32_t cmdio_get_cmd_and_arg (void) static
Definition at line 1037 of file ftpd.c.
 {
     int len;
     uint32_t cmdval;
     char *cmd;
     alarm(G.timeout);
     free(G.ftp_cmd);
     {
         /* Paranoia. Peer may send 1 gigabyte long cmd... */
         /* Using separate len_on_stk instead of len optimizes
          * code size (allows len to be in CPU register) */
         size_t len_on_stk = 8 * 1024;
         G.ftp_cmd = cmd = xmalloc_fgets_str_len(stdin, "\r\n", &len_on_stk);
         if (!cmd)
             exit(0);
         len = len_on_stk;
     }
     /* De-escape telnet: 0xff,0xff => 0xff */
     /* RFC959 says that ABOR, STAT, QUIT may be sent even during
      * data transfer, and may be preceded by telnet's "Interrupt Process"
      * code (two-byte sequence 255,244) and then by telnet "Synch" code
      * 255,242 (byte 242 is sent with TCP URG bit using send(MSG_OOB)
      * and may generate SIGURG on our side. See RFC854).
      * So far we don't support that (may install SIGURG handler if we'd want to),
      * but we need to at least remove 255,xxx pairs. lftp sends those. */
     /* Then de-escape FTP: NUL => '\n' */
     /* Testing for \xff:
      * Create file named '\xff': echo Hello >`echo -ne "\xff"`
      * Try to get it:            ftpget -v 127.0.0.1 Eff `echo -ne "\xff\xff"`
      * (need "\xff\xff" until ftpget applet is fixed to do escaping :)
      * Testing for embedded LF:
      * LF_HERE=`echo -ne "LF\nHERE"`
      * echo Hello >"$LF_HERE"
      * ftpget -v 127.0.0.1 LF_HERE "$LF_HERE"
      */
     {
         int dst, src;
         /* Strip "\r\n" if it is there */
         if (len != 0 && cmd[len - 1] == '\n') {
             len--;
             if (len != 0 && cmd[len - 1] == '\r')
                 len--;
             cmd[len] = '\0';
         }
         src = strchrnul(cmd, 0xff) - cmd;
         /* 99,99% there are neither NULs nor 255s and src == len */
         if (src < len) {
             dst = src;
             do {
                 if ((unsigned char)(cmd[src]) == 255) {
                     src++;
                     /* 255,xxx - skip 255 */
                     if ((unsigned char)(cmd[src]) != 255) {
                         /* 255,!255 - skip both */
                         src++;
                         continue;
                     }
                     /* 255,255 - retain one 255 */
                 }
                 /* NUL => '\n' */
                 cmd[dst++] = cmd[src] ? cmd[src] : '\n';
                 src++;
             } while (src < len);
             cmd[dst] = '\0';
         }
     }
     if (G.verbose > 1)
         verbose_log(cmd);
     G.ftp_arg = strchr(cmd, ' ');
     if (G.ftp_arg != NULL)
         *G.ftp_arg++ = '\0';
     /* Uppercase and pack into uint32_t first word of the command */
     cmdval = 0;
     while (*cmd)
         cmdval = (cmdval << 8) + ((unsigned char)*cmd++ & (unsigned char)~0x20);
     return cmdval;
 }
References alarm(), cmd, dst, exit(), free, G, NULL, src, stdin, strchr(), strchrnul(), verbose_log(), and xmalloc_fgets_str_len().
Referenced by ftpd_main().
cmdio_write()
static void cmdio_write (uint32_t status_str, const char * str) static
Definition at line 249 of file ftpd.c.
 {
     char *response;
     int len;
     /* FTP uses telnet protocol for command link.
      * In telnet, 0xff is an escape char, and needs to be escaped: */
     response = escape_text((char *) &status_str, str, (0xff << 8) + '\r');
     /* FTP sends embedded LFs as NULs */
     len = replace_char(response, '\n', '\0');
     response[len++] = '\n'; /* tack on trailing '\n' */
     xwrite(STDOUT_FILENO, response, len);
     if (G.verbose > 1)
         verbose_log(response);
     free(response);
 }
References escape_text(), free, G, replace_char(), STDOUT_FILENO, str, verbose_log(), and xwrite().
Referenced by get_remote_transfer_fd(), handle_dir_common(), handle_feat(), and handle_pwd().
cmdio_write_error()
static void cmdio_write_error (unsigned status) static
Definition at line 280 of file ftpd.c.
 {
     *(bb__aliased_uint32_t *) G.msg_err = status;
     xwrite(STDOUT_FILENO, G.msg_err, sizeof("NNN " MSG_ERR) - 1);
     if (G.verbose > 0)
         verbose_log(G.msg_err);
 }
References G, MSG_ERR, status, STDOUT_FILENO, verbose_log(), and xwrite().
cmdio_write_ok()
static void cmdio_write_ok (unsigned status) static
Definition at line 269 of file ftpd.c.
 {
     *(bb__aliased_uint32_t *) G.msg_ok = status;
     xwrite(STDOUT_FILENO, G.msg_ok, sizeof("NNN " MSG_OK) - 1);
     if (G.verbose > 1)
         verbose_log(G.msg_ok);
 }
References G, MSG_OK, status, STDOUT_FILENO, verbose_log(), and xwrite().
cmdio_write_raw()
static void cmdio_write_raw (const char * p_text) static
Definition at line 290 of file ftpd.c.
 {
     xwrite_str(STDOUT_FILENO, p_text);
     if (G.verbose > 1)
         verbose_log(p_text);
 }
References G, STDOUT_FILENO, verbose_log(), and xwrite_str().
Referenced by ftpd_main(), handle_dir_common(), handle_epsv(), handle_feat(), handle_pasv(), handle_size_or_mdtm(), handle_stat(), port_or_pasv_was_seen(), and timeout_handler().
escape_text()
static char* escape_text (const char * prepend, const char * str, unsigned escapee) static
Definition at line 194 of file ftpd.c.
 {
     unsigned retlen, remainlen, chunklen;
     char *ret, *found;
     char append;
     append = (char)escapee;
     escapee >>= 8;
     remainlen = strlen(str);
     retlen = strlen(prepend);
     ret = xmalloc(retlen + remainlen * 2 + 1 + 1);
     strcpy(ret, prepend);
     for (;;) {
         found = strchrnul(str, escapee);
         chunklen = found - str + 1;
         /* Copy chunk up to and including escapee (or NUL) to ret */
         memcpy(ret + retlen, str, chunklen);
         retlen += chunklen;
         if (*found == '\0') {
             /* It wasn't escapee, it was NUL! */
             ret[retlen - 1] = append; /* replace NUL */
             ret[retlen] = '\0'; /* add NUL */
             break;
         }
         ret[retlen++] = escapee; /* duplicate escapee */
         str = found + 1;
     }
     return ret;
 }
References append(), found, memcpy(), retlen, str, strchrnul(), strcpy(), strlen(), and xmalloc.
Referenced by cmdio_write(), and handle_pwd().
ftpd_main()
int ftpd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1173 of file ftpd.c.
 {
 #if ENABLE_FEATURE_FTPD_AUTHENTICATION
     struct passwd *pw = NULL;
     char *anon_opt = NULL;
 #endif
     unsigned abs_timeout;
     unsigned verbose_S;
     smallint opts;
     INIT_G();
     abs_timeout = 1 * 60 * 60;
     verbose_S = 0;
     G.timeout = 2 * 60;
 #if BB_MMU
     opts = getopt32(argv, "^"   "AvS" IF_FEATURE_FTPD_WRITE("w")
         "t:+T:+" IF_FEATURE_FTPD_AUTHENTICATION("a:")
         "\0" "vv:SS",
         &G.timeout, &abs_timeout, IF_FEATURE_FTPD_AUTHENTICATION(&anon_opt,)
         &G.verbose, &verbose_S
     );
 #else
     opts = getopt32(argv, "^" "l1AvS" IF_FEATURE_FTPD_WRITE("w")
         "t:+T:+" IF_FEATURE_FTPD_AUTHENTICATION("a:")
         "\0" "vv:SS",
         &G.timeout, &abs_timeout, IF_FEATURE_FTPD_AUTHENTICATION(&anon_opt,)
         &G.verbose, &verbose_S
     );
     if (opts & (OPT_l|OPT_1)) {
         /* Our secret backdoor to ls: see popen_ls() */
         if (fchdir(3) != 0)
             _exit(127);
         /* memset(&G, 0, sizeof(G)); - ls_main does it */
         /* NB: in this case -A has a different meaning: like "ls -A" */
         return ls_main(/*argc_unused*/ 0, argv);
     }
 #endif
     if (G.verbose < verbose_S)
         G.verbose = verbose_S;
     if (abs_timeout | G.timeout) {
         if (abs_timeout == 0)
             abs_timeout = INT_MAX;
         G.end_time = monotonic_sec() + abs_timeout;
         if (G.timeout > abs_timeout)
             G.timeout = abs_timeout;
     }
     strcpy(G.msg_ok  + 4, MSG_OK );
     strcpy(G.msg_err + 4, MSG_ERR);
     G.local_addr = get_sock_lsa(STDIN_FILENO);
     if (!G.local_addr) {
         /* This is confusing:
          * bb_error_msg_and_die("stdin is not a socket");
          * Better: */
         bb_show_usage();
         /* Help text says that ftpd must be used as inetd service,
          * which is by far the most usual cause of get_sock_lsa
          * failure */
     }
     if (!(opts & OPT_v))
         logmode = LOGMODE_NONE;
     if (opts & OPT_S) {
         /* LOG_NDELAY is needed since we may chroot later */
         openlog(applet_name, LOG_PID | LOG_NDELAY, LOG_DAEMON);
         logmode |= LOGMODE_SYSLOG;
     }
     if (logmode)
         applet_name = xasprintf("%s[%u]", applet_name, (int)getpid());
     //umask(077); - admin can set umask before starting us
     /* Signals */
     bb_signals(0
         /* We'll always take EPIPE rather than a rude signal, thanks */
         + (1 << SIGPIPE)
         /* LIST command spawns chilren. Prevent zombies */
         + (1 << SIGCHLD)
         , SIG_IGN);
     /* Set up options on the command socket (do we need these all? why?) */
     setsockopt_1(STDIN_FILENO, IPPROTO_TCP, TCP_NODELAY);
     setsockopt_keepalive(STDIN_FILENO);
     /* Telnet protocol over command link may send "urgent" data,
      * we prefer it to be received in the "normal" data stream: */
     setsockopt_1(STDIN_FILENO, SOL_SOCKET, SO_OOBINLINE);
     WRITE_OK(FTP_GREET);
     signal(SIGALRM, timeout_handler);
 #if ENABLE_FEATURE_FTPD_AUTHENTICATION
     if (!(opts & OPT_A)) {
         while (1) {
             uint32_t cmdval = cmdio_get_cmd_and_arg();
             if (cmdval == const_USER) {
                 if (anon_opt && strcmp(G.ftp_arg, "anonymous") == 0) {
                     pw = getpwnam(anon_opt);
                     if (pw)
                         break; /* does not even ask for password */
                 }
                 pw = getpwnam(G.ftp_arg);
                 cmdio_write_raw(STR(FTP_GIVEPWORD)" Specify password\r\n");
             } else if (cmdval == const_PASS) {
                 if (check_password(pw, G.ftp_arg) > 0) {
                     break;  /* login success */
                 }
                 cmdio_write_raw(STR(FTP_LOGINERR)" Login failed\r\n");
                 pw = NULL;
             } else if (cmdval == const_QUIT) {
                 WRITE_OK(FTP_GOODBYE);
                 return 0;
             } else {
                 cmdio_write_raw(STR(FTP_LOGINERR)" Login with USER+PASS\r\n");
             }
         }
         WRITE_OK(FTP_LOGINOK);
     }
 #endif
     /* Do this after auth, else /etc/passwd is not accessible */
 #if !BB_MMU
     G.root_fd = -1;
 #endif
     argv += optind;
     if (argv[0]) {
         const char *basedir = argv[0];
 #if !BB_MMU
         G.root_fd = xopen("/", O_RDONLY | O_DIRECTORY);
         close_on_exec_on(G.root_fd);
 #endif
         if (chroot(basedir) == 0)
             basedir = "/";
 #if !BB_MMU
         else {
             close(G.root_fd);
             G.root_fd = -1;
         }
 #endif
         /*
          * If chroot failed, assume that we aren't root,
          * and at least chdir to the specified DIR
          * (older versions were dying with error message).
          * If chroot worked, move current dir to new "/":
          */
         xchdir(basedir);
     }
 #if ENABLE_FEATURE_FTPD_AUTHENTICATION
     if (pw)
         change_identity(pw);
     /* else: -A is in effect */
 #endif
     /* RFC-959 Section 5.1
      * The following commands and options MUST be supported by every
      * server-FTP and user-FTP, except in cases where the underlying
      * file system or operating system does not allow or support
      * a particular command.
      * Type: ASCII Non-print, IMAGE, LOCAL 8
      * Mode: Stream
      * Structure: File, Record*
      * (Record structure is REQUIRED only for hosts whose file
      *  systems support record structure).
      * Commands:
      * USER, PASS, ACCT, [bbox: ACCT not supported]
      * PORT, PASV,
      * TYPE, MODE, STRU,
      * RETR, STOR, APPE,
      * RNFR, RNTO, DELE,
      * CWD,  CDUP, RMD,  MKD,  PWD,
      * LIST, NLST,
      * SYST, STAT,
      * HELP, NOOP, QUIT.
      */
     /* ACCOUNT (ACCT)
      * "The argument field is a Telnet string identifying the user's account.
      * The command is not necessarily related to the USER command, as some
      * sites may require an account for login and others only for specific
      * access, such as storing files. In the latter case the command may
      * arrive at any time.
      * There are reply codes to differentiate these cases for the automation:
      * when account information is required for login, the response to
      * a successful PASSword command is reply code 332. On the other hand,
      * if account information is NOT required for login, the reply to
      * a successful PASSword command is 230; and if the account information
      * is needed for a command issued later in the dialogue, the server
      * should return a 332 or 532 reply depending on whether it stores
      * (pending receipt of the ACCounT command) or discards the command,
      * respectively."
      */
     while (1) {
         uint32_t cmdval = cmdio_get_cmd_and_arg();
         if (cmdval == const_QUIT) {
             WRITE_OK(FTP_GOODBYE);
             return 0;
         }
         else if (cmdval == const_USER)
             /* This would mean "ok, now give me PASS". */
             /*WRITE_OK(FTP_GIVEPWORD);*/
             /* vsftpd can be configured to not require that,
              * and this also saves one roundtrip:
              */
             WRITE_OK(FTP_LOGINOK);
         else if (cmdval == const_PASS)
             WRITE_OK(FTP_LOGINOK);
         else if (cmdval == const_NOOP)
             WRITE_OK(FTP_NOOPOK);
         else if (cmdval == const_TYPE)
             WRITE_OK(FTP_TYPEOK);
         else if (cmdval == const_STRU)
             WRITE_OK(FTP_STRUOK);
         else if (cmdval == const_MODE)
             WRITE_OK(FTP_MODEOK);
         else if (cmdval == const_ALLO)
             WRITE_OK(FTP_ALLOOK);
         else if (cmdval == const_SYST)
             cmdio_write_raw(STR(FTP_SYSTOK)" UNIX Type: L8\r\n");
         else if (cmdval == const_PWD || cmdval == const_XPWD)
             handle_pwd();
         else if (cmdval == const_CWD)
             handle_cwd();
         else if (cmdval == const_CDUP) /* cd .. */
             handle_cdup();
         /* HELP is nearly useless, but we can reuse FEAT for it */
         /* lftp uses FEAT */
         else if (cmdval == const_HELP || cmdval == const_FEAT)
             handle_feat(cmdval == const_HELP
                     ? STRNUM32(FTP_HELP)
                     : STRNUM32(FTP_STATOK)
             );
         else if (cmdval == const_LIST) /* ls -l */
             handle_list();
         else if (cmdval == const_NLST) /* "name list", bare ls */
             handle_nlst();
         /* SIZE is crucial for wget's download indicator etc */
         /* Mozilla, lftp use MDTM (presumably for caching) */
         else if (cmdval == const_SIZE || cmdval == const_MDTM)
             handle_size_or_mdtm(cmdval == const_SIZE);
         else if (cmdval == const_STAT) {
             if (G.ftp_arg == NULL)
                 handle_stat();
             else
                 handle_stat_file();
         }
         else if (cmdval == const_PASV)
             handle_pasv();
         else if (cmdval == const_EPSV)
             handle_epsv();
         else if (cmdval == const_RETR)
             handle_retr();
         else if (cmdval == const_PORT)
             handle_port();
         else if (cmdval == const_REST)
             handle_rest();
 #if ENABLE_FEATURE_FTPD_WRITE
         else if (opts & OPT_w) {
             if (cmdval == const_STOR)
                 handle_stor();
             else if (cmdval == const_MKD)
                 handle_mkd();
             else if (cmdval == const_RMD)
                 handle_rmd();
             else if (cmdval == const_DELE)
                 handle_dele();
             else if (cmdval == const_RNFR) /* "rename from" */
                 handle_rnfr();
             else if (cmdval == const_RNTO) /* "rename to" */
                 handle_rnto();
             else if (cmdval == const_APPE)
                 handle_appe();
             else if (cmdval == const_STOU) /* "store unique" */
                 handle_stou();
             else
                 goto bad_cmd;
         }
 #endif
 #if 0
         else if (cmdval == const_STOR
          || cmdval == const_MKD
          || cmdval == const_RMD
          || cmdval == const_DELE
          || cmdval == const_RNFR
          || cmdval == const_RNTO
          || cmdval == const_APPE
          || cmdval == const_STOU
         ) {
             cmdio_write_raw(STR(FTP_NOPERM)" Permission denied\r\n");
         }
 #endif
         else {
             /* Which unsupported commands were seen in the wild?
              * (doesn't necessarily mean "we must support them")
              * foo 1.2.3: XXXX - comment
              */
 #if ENABLE_FEATURE_FTPD_WRITE
  bad_cmd:
 #endif
             cmdio_write_raw(STR(FTP_BADCMD)" Unknown command\r\n");
         }
     }
 }
References _exit(), applet_name, argv, bb_show_usage(), bb_signals(), change_identity(), check_password(), chroot(), close(), close_on_exec_on(), cmdio_get_cmd_and_arg(), cmdio_write_raw(), const_ALLO, const_APPE, const_CDUP, const_CWD, const_DELE, const_EPSV, const_FEAT, const_HELP, const_LIST, const_MDTM, const_MKD, const_MODE, const_NLST, const_NOOP, const_PASS, const_PASV, const_PORT, const_PWD, const_QUIT, const_REST, const_RETR, const_RMD, const_RNFR, const_RNTO, const_SIZE, const_STAT, const_STOR, const_STOU, const_STRU, const_SYST, const_TYPE, const_USER, const_XPWD, fchdir(), FTP_ALLOOK, FTP_BADCMD, FTP_GIVEPWORD, FTP_GOODBYE, FTP_GREET, FTP_HELP, FTP_LOGINERR, FTP_LOGINOK, FTP_MODEOK, FTP_NOOPOK, FTP_NOPERM, FTP_STATOK, FTP_STRUOK, FTP_SYSTOK, FTP_TYPEOK, G, get_sock_lsa(), getopt32(), getpid(), getpwnam, handle_cdup(), handle_cwd(), handle_epsv(), handle_feat(), handle_list(), handle_nlst(), handle_pasv(), handle_port(), handle_pwd(), handle_rest(), handle_retr(), handle_size_or_mdtm(), handle_stat(), handle_stat_file(), INIT_G, INT_MAX, IPPROTO_TCP, LOG_DAEMON, LOG_NDELAY, LOG_PID, logmode, LOGMODE_NONE, LOGMODE_SYSLOG, ls_main(), monotonic_sec(), MSG_ERR, MSG_OK, NULL, O_DIRECTORY, O_RDONLY, openlog(), OPT_1, OPT_A, OPT_l, OPT_S, OPT_v, OPT_w, optind, pw, setsockopt_1(), setsockopt_keepalive(), SIG_IGN, SIGALRM, SIGCHLD, signal, SIGPIPE, SO_OOBINLINE, SOL_SOCKET, STDIN_FILENO, STR, strcmp, strcpy(), STRNUM32, TCP_NODELAY, timeout_handler(), WRITE_OK, xasprintf(), xchdir(), and xopen().
ftpdataio_get_pasv_fd()
static int ftpdataio_get_pasv_fd (void) static
Definition at line 428 of file ftpd.c.
 {
     int remote_fd;
     remote_fd = accept(G.pasv_listen_fd, NULL, 0);
     if (remote_fd < 0) {
         WRITE_ERR(FTP_BADSENDCONN);
         return remote_fd;
     }
     setsockopt_keepalive(remote_fd);
     return remote_fd;
 }
References accept(), FTP_BADSENDCONN, G, NULL, setsockopt_keepalive(), and WRITE_ERR.
Referenced by get_remote_transfer_fd().
get_remote_transfer_fd()
static int get_remote_transfer_fd (const char * p_status_msg) static
Definition at line 450 of file ftpd.c.
 {
     int remote_fd;
     if (pasv_active())
         /* On error, emits error code to the peer */
         remote_fd = ftpdataio_get_pasv_fd();
     else
         /* Exits on error */
         remote_fd = xconnect_stream(G.port_addr);
     port_pasv_cleanup();
     if (remote_fd < 0)
         return remote_fd;
     cmdio_write(STRNUM32(FTP_DATACONN), p_status_msg);
     return remote_fd;
 }
References cmdio_write(), FTP_DATACONN, ftpdataio_get_pasv_fd(), G, pasv_active(), port_pasv_cleanup(), STRNUM32, and xconnect_stream().
Referenced by handle_dir_common(), and handle_retr().
handle_cdup()
static void handle_cdup (void) static
Definition at line 353 of file ftpd.c.
 {
     G.ftp_arg = (char*)"..";
     handle_cwd();
 }
References G, and handle_cwd().
Referenced by ftpd_main().
handle_cwd()
static void handle_cwd (void) static
Definition at line 343 of file ftpd.c.
 {
     if (!G.ftp_arg || chdir(G.ftp_arg) != 0) {
         WRITE_ERR(FTP_FILEFAIL);
         return;
     }
     WRITE_OK(FTP_CWDOK);
 }
References chdir(), FTP_CWDOK, FTP_FILEFAIL, G, WRITE_ERR, and WRITE_OK.
Referenced by ftpd_main(), and handle_cdup().
handle_dir_common()
static void handle_dir_common (int opts) static
Definition at line 752 of file ftpd.c.
 {
     FILE *ls_fp;
     char *line;
     int ls_fd;
     if (!(opts & USE_CTRL_CONN) && !port_or_pasv_was_seen())
         return; /* port_or_pasv_was_seen emitted error response */
     ls_fd = popen_ls((opts & LONG_LISTING) ? "-lA" : "-1A");
     ls_fp = xfdopen_for_read(ls_fd);
 /* FIXME: filenames with embedded newlines are mishandled */
     if (opts & USE_CTRL_CONN) {
         /* STAT <filename> */
         cmdio_write_raw(STR(FTP_STATFILE_OK)"-File status:\r\n");
         while (1) {
             line = xmalloc_fgetline(ls_fp);
             if (!line)
                 break;
             /* Hack: 0 results in no status at all */
             /* Note: it's ok that we don't prepend space,
              * ftp.kernel.org doesn't do that too */
             cmdio_write(0, line);
             free(line);
         }
         WRITE_OK(FTP_STATFILE_OK);
     } else {
         /* LIST/NLST [<filename>] */
         int remote_fd = get_remote_transfer_fd(" Directory listing");
         if (remote_fd >= 0) {
             while (1) {
                 unsigned len;
                 line = xmalloc_fgets(ls_fp);
                 if (!line)
                     break;
                 /* I've seen clients complaining when they
                  * are fed with ls output with bare '\n'.
                  * Replace trailing "\n\0" with "\r\n".
                  */
                 len = strlen(line);
                 if (len != 0) /* paranoia check */
                     line[len - 1] = '\r';
                 line[len] = '\n';
                 xwrite(remote_fd, line, len + 1);
                 free(line);
             }
         }
         close(remote_fd);
         WRITE_OK(FTP_TRANSFEROK);
     }
     fclose(ls_fp); /* closes ls_fd too */
 }
References close(), cmdio_write(), cmdio_write_raw(), fclose(), free, FTP_STATFILE_OK, FTP_TRANSFEROK, get_remote_transfer_fd(), line, LONG_LISTING, popen_ls(), port_or_pasv_was_seen(), STR, strlen(), USE_CTRL_CONN, WRITE_OK, xfdopen_for_read(), xmalloc_fgetline(), xmalloc_fgets(), and xwrite().
Referenced by handle_list(), handle_nlst(), and handle_stat_file().
handle_epsv()
static void handle_epsv (void) static
Definition at line 528 of file ftpd.c.
 {
     unsigned port;
     char *response;
     port = bind_for_passive_mode();
     response = xasprintf(STR(FTP_EPSVOK)" EPSV ok (|||%u|)\r\n", port);
     cmdio_write_raw(response);
     free(response);
 }
References bind_for_passive_mode(), cmdio_write_raw(), free, FTP_EPSVOK, port, STR, and xasprintf().
Referenced by ftpd_main().
handle_feat()
static void handle_feat (unsigned status) static
Definition at line 391 of file ftpd.c.
 {
     cmdio_write(status, "-Features:");
     cmdio_write_raw(" EPSV\r\n"
             " PASV\r\n"
             " REST STREAM\r\n"
             " MDTM\r\n"
             " SIZE\r\n");
     cmdio_write(status, " Ok");
 }
References cmdio_write(), cmdio_write_raw(), and status.
Referenced by ftpd_main().
handle_list()
static void handle_list (void) static
Definition at line 807 of file ftpd.c.
 {
     handle_dir_common(LONG_LISTING);
 }
References handle_dir_common(), and LONG_LISTING.
Referenced by ftpd_main().
handle_nlst()
static void handle_nlst (void) static
Definition at line 812 of file ftpd.c.
 {
     /* NLST returns list of names, "\r\n" terminated without regard
      * to the current binary flag. Names may start with "/",
      * then they represent full names (we don't produce such names),
      * otherwise names are relative to current directory.
      * Embedded "\n" are replaced by NULs. This is safe since names
      * can never contain NUL.
      */
     handle_dir_common(0);
 }
References handle_dir_common().
Referenced by ftpd_main().
handle_pasv()
static void handle_pasv (void) static
Definition at line 506 of file ftpd.c.
 {
     unsigned port;
     char *addr, *response;
     port = bind_for_passive_mode();
     if (G.local_addr->u.sa.sa_family == AF_INET)
         addr = xmalloc_sockaddr2dotted_noport(&G.local_addr->u.sa);
     else /* seen this in the wild done by other ftp servers: */
         addr = xstrdup("0.0.0.0");
     replace_char(addr, '.', ',');
     response = xasprintf(STR(FTP_PASVOK)" PASV ok (%s,%u,%u)\r\n",
             addr, (int)(port >> 8), (int)(port & 255));
     free(addr);
     cmdio_write_raw(response);
     free(response);
 }
References addr, AF_INET, bind_for_passive_mode(), cmdio_write_raw(), free, FTP_PASVOK, G, port, replace_char(), STR, xasprintf(), xmalloc_sockaddr2dotted_noport(), and xstrdup().
Referenced by ftpd_main().
handle_port()
static void handle_port (void) static
Definition at line 540 of file ftpd.c.
 {
     unsigned port, port_hi;
     char *raw, *comma;
 #ifdef WHY_BOTHER_WE_CAN_ASSUME_IP_MATCHES
     socklen_t peer_ipv4_len;
     struct sockaddr_in peer_ipv4;
     struct in_addr port_ipv4_sin_addr;
 #endif
     port_pasv_cleanup();
     raw = G.ftp_arg;
     /* PORT command format makes sense only over IPv4 */
     if (!raw
 #ifdef WHY_BOTHER_WE_CAN_ASSUME_IP_MATCHES
      || G.local_addr->u.sa.sa_family != AF_INET
 #endif
     ) {
  bail:
         WRITE_ERR(FTP_BADCMD);
         return;
     }
     comma = strrchr(raw, ',');
     if (comma == NULL)
         goto bail;
     *comma = '\0';
     port = bb_strtou(&comma[1], NULL, 10);
     if (errno || port > 0xff)
         goto bail;
     comma = strrchr(raw, ',');
     if (comma == NULL)
         goto bail;
     *comma = '\0';
     port_hi = bb_strtou(&comma[1], NULL, 10);
     if (errno || port_hi > 0xff)
         goto bail;
     port |= port_hi << 8;
 #ifdef WHY_BOTHER_WE_CAN_ASSUME_IP_MATCHES
     replace_char(raw, ',', '.');
     /* We are verifying that PORT's IP matches getpeername().
      * Otherwise peer can make us open data connections
      * to other hosts (security problem!)
      * This code would be too simplistic:
      * lsa = xdotted2sockaddr(raw, port);
      * if (lsa == NULL) goto bail;
      */
     if (!inet_aton(raw, &port_ipv4_sin_addr))
         goto bail;
     peer_ipv4_len = sizeof(peer_ipv4);
     if (getpeername(STDIN_FILENO, &peer_ipv4, &peer_ipv4_len) != 0)
         goto bail;
     if (memcmp(&port_ipv4_sin_addr, &peer_ipv4.sin_addr, sizeof(struct in_addr)) != 0)
         goto bail;
     G.port_addr = xdotted2sockaddr(raw, port);
 #else
     G.port_addr = get_peer_lsa(STDIN_FILENO);
     set_nport(&G.port_addr->u.sa, htons(port));
 #endif
     WRITE_OK(FTP_PORTOK);
 }
References AF_INET, bb_strtou(), errno, FTP_BADCMD, FTP_PORTOK, G, get_peer_lsa(), getpeername(), htons(), inet_aton(), memcmp(), NULL, port, port_pasv_cleanup(), replace_char(), set_nport(), sockaddr_in::sin_addr, STDIN_FILENO, strrchr(), WRITE_ERR, WRITE_OK, and xdotted2sockaddr().
Referenced by ftpd_main().
handle_pwd()
static void handle_pwd (void) static
Definition at line 327 of file ftpd.c.
 {
     char *cwd, *response;
     cwd = xrealloc_getcwd_or_warn(NULL);
     if (cwd == NULL)
         cwd = xstrdup("");
     /* We have to promote each " to "" */
     response = escape_text(" \"", cwd, ('"' << 8) + '"');
     free(cwd);
     cmdio_write(STRNUM32(FTP_PWDOK), response);
     free(response);
 }
References cmdio_write(), escape_text(), free, FTP_PWDOK, NULL, STRNUM32, xrealloc_getcwd_or_warn(), and xstrdup().
Referenced by ftpd_main().
handle_rest()
static void handle_rest (void) static
Definition at line 609 of file ftpd.c.
 {
     /* When ftp_arg == NULL simply restart from beginning */
     G.restart_pos = G.ftp_arg ? XATOOFF(G.ftp_arg) : 0;
     WRITE_OK(FTP_RESTOK);
 }
References FTP_RESTOK, G, WRITE_OK, and XATOOFF.
Referenced by ftpd_main().
handle_retr()
static void handle_retr (void) static
Definition at line 617 of file ftpd.c.
 {
     struct stat statbuf;
     off_t bytes_transferred;
     int remote_fd;
     int local_file_fd;
     off_t offset = G.restart_pos;
     char *response;
     G.restart_pos = 0;
     if (!port_or_pasv_was_seen())
         return; /* port_or_pasv_was_seen emitted error response */
     /* O_NONBLOCK is useful if file happens to be a device node */
     local_file_fd = G.ftp_arg ? open(G.ftp_arg, O_RDONLY | O_NONBLOCK) : -1;
     if (local_file_fd < 0) {
         WRITE_ERR(FTP_FILEFAIL);
         return;
     }
     if (fstat(local_file_fd, &statbuf) != 0 || !S_ISREG(statbuf.st_mode)) {
         /* Note - pretend open failed */
         WRITE_ERR(FTP_FILEFAIL);
         goto file_close_out;
     }
     G.local_file_fd = local_file_fd;
     /* Now deactive O_NONBLOCK, otherwise we have a problem
      * on DMAPI filesystems such as XFS DMAPI.
      */
     ndelay_off(local_file_fd);
     /* Set the download offset (from REST) if any */
     if (offset != 0)
         xlseek(local_file_fd, offset, SEEK_SET);
     response = xasprintf(
         " Opening BINARY connection for %s (%"OFF_FMT"u bytes)",
         G.ftp_arg, statbuf.st_size);
     remote_fd = get_remote_transfer_fd(response);
     free(response);
     if (remote_fd < 0)
         goto file_close_out;
     bytes_transferred = bb_copyfd_eof(local_file_fd, remote_fd);
     close(remote_fd);
     if (bytes_transferred < 0)
         WRITE_ERR(FTP_BADSENDFILE);
     else
         WRITE_OK(FTP_TRANSFEROK);
  file_close_out:
     close(local_file_fd);
     G.local_file_fd = 0;
 }
References bb_copyfd_eof(), close(), free, fstat(), FTP_BADSENDFILE, FTP_FILEFAIL, FTP_TRANSFEROK, G, get_remote_transfer_fd(), ndelay_off(), O_NONBLOCK, O_RDONLY, OFF_FMT, off_t, offset, open(), port_or_pasv_was_seen(), S_ISREG, SEEK_SET, stat::st_mode, stat::st_size, WRITE_ERR, WRITE_OK, xasprintf(), and xlseek().
Referenced by ftpd_main().
handle_size_or_mdtm()
static void handle_size_or_mdtm (int need_size) static
Definition at line 859 of file ftpd.c.
 {
     struct stat statbuf;
     struct tm broken_out;
     char buf[(sizeof("NNN %"OFF_FMT"u\r\n") + sizeof(off_t) * 3)
         | sizeof("NNN YYYYMMDDhhmmss\r\n")
     ];
     if (!G.ftp_arg
      || stat(G.ftp_arg, &statbuf) != 0
      || !S_ISREG(statbuf.st_mode)
     ) {
         WRITE_ERR(FTP_FILEFAIL);
         return;
     }
     if (need_size) {
         sprintf(buf, STR(FTP_STATFILE_OK)" %"OFF_FMT"u\r\n", statbuf.st_size);
     } else {
         gmtime_r(&statbuf.st_mtime, &broken_out);
         sprintf(buf, STR(FTP_STATFILE_OK)" %04u%02u%02u%02u%02u%02u\r\n",
             broken_out.tm_year + 1900,
             broken_out.tm_mon + 1,
             broken_out.tm_mday,
             broken_out.tm_hour,
             broken_out.tm_min,
             broken_out.tm_sec);
     }
     cmdio_write_raw(buf);
 }
References buf, cmdio_write_raw(), FTP_FILEFAIL, FTP_STATFILE_OK, G, OFF_FMT, off_t, S_ISREG, sprintf(), stat::st_mode, stat::st_size, STR, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_year, and WRITE_ERR.
Referenced by ftpd_main().
handle_stat()
static void handle_stat (void) static
Definition at line 360 of file ftpd.c.
 {
     cmdio_write_raw(STR(FTP_STATOK)"-Server status:\r\n"
             " TYPE: BINARY\r\n"
             STR(FTP_STATOK)" Ok\r\n");
 }
References cmdio_write_raw(), FTP_STATOK, and STR.
Referenced by ftpd_main().
handle_stat_file()
static void handle_stat_file (void) static
Definition at line 824 of file ftpd.c.
 {
     handle_dir_common(LONG_LISTING + USE_CTRL_CONN);
 }
References handle_dir_common(), LONG_LISTING, and USE_CTRL_CONN.
Referenced by ftpd_main().
pasv_active()
static int pasv_active (void) inline static
Definition at line 411 of file ftpd.c.
 {
     return (G.pasv_listen_fd > STDOUT_FILENO);
 }
References G, and STDOUT_FILENO.
Referenced by get_remote_transfer_fd(), and port_or_pasv_was_seen().
popen_ls()
static int popen_ls (const char * opt) static
Definition at line 677 of file ftpd.c.
 {
     const char *argv[5];
     struct fd_pair outfd;
     pid_t pid;
     argv[0] = "ftpd";
     argv[1] = opt; /* "-lA" or "-1A" */
     argv[2] = "--";
     argv[3] = G.ftp_arg;
     argv[4] = NULL;
     /* Improve compatibility with non-RFC conforming FTP clients
      * which send e.g. "LIST -l", "LIST -la", "LIST -aL".
      * See https://bugs.kde.org/show_bug.cgi?id=195578 */
     if (ENABLE_FEATURE_FTPD_ACCEPT_BROKEN_LIST
      && G.ftp_arg && G.ftp_arg[0] == '-'
     ) {
         const char *tmp = strchr(G.ftp_arg, ' ');
         if (tmp) /* skip the space */
             tmp++;
         argv[3] = tmp;
     }
     xpiped_pair(outfd);
     /*fflush_all(); - so far we dont use stdio on output */
     pid = BB_MMU ? xfork() : xvfork();
     if (pid == 0) {
 #if !BB_MMU
         int cur_fd;
 #endif
         /* child */
         /* NB: close _first_, then move fd! */
         close(outfd.rd);
         xmove_fd(outfd.wr, STDOUT_FILENO);
         /* Opening /dev/null in chroot is hard.
          * Just making sure STDIN_FILENO is opened
          * to something harmless. Paranoia,
          * ls won't read it anyway */
         close(STDIN_FILENO);
         dup(STDOUT_FILENO); /* copy will become STDIN_FILENO */
 #if BB_MMU
         /* memset(&G, 0, sizeof(G)); - ls_main does it */
         exit(ls_main(/*argc_unused*/ 0, (char**) argv));
 #else
         cur_fd = xopen(".", O_RDONLY | O_DIRECTORY);
         /* On NOMMU, we want to execute a child - copy of ourself
          * in order to unblock parent after vfork.
          * In chroot we usually can't re-exec. Thus we escape
          * out of the chroot back to original root.
          */
         if (G.root_fd >= 0) {
             if (fchdir(G.root_fd) != 0 || chroot(".") != 0)
                 _exit(127);
             /*close(G.root_fd); - close_on_exec_on() took care of this */
         }
         /* Child expects directory to list on fd #3 */
         xmove_fd(cur_fd, 3);
         execv(bb_busybox_exec_path, (char**) argv);
         _exit(127);
 #endif
     }
     /* parent */
     close(outfd.wr);
     return outfd.rd;
 }
References _exit(), argv, BB_MMU, chroot(), close(), dup(), execv(), exit(), fchdir(), G, ls_main(), NULL, O_DIRECTORY, O_RDONLY, opt, pid, fd_pair::rd, STDIN_FILENO, STDOUT_FILENO, strchr(), fd_pair::wr, xfork(), xmove_fd(), xopen(), xpiped_pair, and xvfork.
Referenced by handle_dir_common().
port_active()
static int port_active (void) inline static
Definition at line 405 of file ftpd.c.
 {
     return (G.port_addr != NULL);
 }
References G, and NULL.
Referenced by port_or_pasv_was_seen().
port_or_pasv_was_seen()
static int port_or_pasv_was_seen (void) static
Definition at line 472 of file ftpd.c.
 {
     if (!pasv_active() && !port_active()) {
         cmdio_write_raw(STR(FTP_BADSENDCONN)" Use PORT/PASV first\r\n");
         return 0;
     }
     return 1;
 }
References cmdio_write_raw(), FTP_BADSENDCONN, pasv_active(), port_active(), and STR.
Referenced by handle_dir_common(), and handle_retr().
port_pasv_cleanup()
static void port_pasv_cleanup (void) static
Definition at line 417 of file ftpd.c.
 {
     free(G.port_addr);
     G.port_addr = NULL;
     if (G.pasv_listen_fd > STDOUT_FILENO)
         close(G.pasv_listen_fd);
     G.pasv_listen_fd = -1;
 }
References close(), free, G, NULL, and STDOUT_FILENO.
Referenced by bind_for_passive_mode(), get_remote_transfer_fd(), and handle_port().
replace_char()
static unsigned replace_char (char * str, char from, char to) static
Definition at line 230 of file ftpd.c.
 {
     char *p = str;
     while (*p) {
         if (*p == from)
             *p = to;
         p++;
     }
     return p - str;
 }
References p, and str.
Referenced by cmdio_write(), handle_pasv(), and handle_port().
timeout_handler()
static void timeout_handler (int sig UNUSED_PARAM) static
Definition at line 298 of file ftpd.c.
 {
     off_t pos;
     int sv_errno = errno;
     if ((int)(monotonic_sec() - G.end_time) >= 0)
         goto timed_out;
     if (!G.local_file_fd)
         goto timed_out;
     pos = xlseek(G.local_file_fd, 0, SEEK_CUR);
     if (pos == G.local_file_pos)
         goto timed_out;
     G.local_file_pos = pos;
     alarm(G.timeout);
     errno = sv_errno;
     return;
  timed_out:
     cmdio_write_raw(STR(FTP_TIMEOUT)" Timeout\r\n");
 /* TODO: do we need to abort (as opposed to usual shutdown) data transfer? */
     exit(1);
 }
References alarm(), cmdio_write_raw(), errno, exit(), FTP_TIMEOUT, G, monotonic_sec(), off_t, pos, SEEK_CUR, STR, and xlseek().
Referenced by ftpd_main().
verbose_log()
static void verbose_log (const char * str) static
Definition at line 242 of file ftpd.c.
 {
     bb_error_msg("%.*s", (int)strcspn(str, "\r\n"), str);
 }
References bb_error_msg(), str, and strcspn().
Referenced by cmdio_get_cmd_and_arg(), cmdio_write(), cmdio_write_error(), cmdio_write_ok(), and cmdio_write_raw().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING