Fennix Kernel: Kernel/library/std/errno.cpp File Reference
errno.cpp File Reference
#include <errno.h>
#include <types.h>
#include <debug.h>
#include <atomic>
#include "../../kernel.h"
Functions
__aligned (16) static int errno_value=0
EXTERNC int * __errno_location (void)
char * strerror (int errnum)
Function Documentation
__aligned()
__aligned (16) pure virtual
Definition at line 32 of file syscalls.cpp.
 {
     asmv("swapgs\n");            /* Swap GS to get the gsTCB */
     asmv("mov %rsp, %gs:0x8\n"); /* We save the current rsp to gsTCB->TempStack */
     asmv("mov %gs:0x0, %rsp\n"); /* Get gsTCB->SystemCallStack and set it as rsp */
     asmv("push $0x1b\n");        /* Push user data segment for SyscallsFrame */
     asmv("push %gs:0x8\n");      /* Push gsTCB->TempStack (old rsp) for SyscallsFrame */
     asmv("push %r11\n");         /* Push the flags for SyscallsFrame */
     asmv("push $0x23\n");        /* Push user code segment for SyscallsFrame */
     asmv("push %rcx\n");         /* Push the return address for SyscallsFrame + sysretq (https://www.felixcloutier.com/x86/sysret) */
     /* Push registers */
     asmv("push %rax\n"
          "push %rbx\n"
          "push %rcx\n"
          "push %rdx\n"
          "push %rsi\n"
          "push %rdi\n"
          "push %rbp\n"
          "push %r8\n"
          "push %r9\n"
          "push %r10\n"
          "push %r11\n"
          "push %r12\n"
          "push %r13\n"
          "push %r14\n"
          "push %r15\n");
     /* Set the first argument to the SyscallsFrame pointer */
     asmv("mov %rsp, %rdi\n");
     asmv("mov $0, %rbp\n");
     asmv("call SystemCallsHandler\n");
     /* Pop registers except rax */
     asmv("pop %r15\n"
          "pop %r14\n"
          "pop %r13\n"
          "pop %r12\n"
          "pop %r11\n"
          "pop %r10\n"
          "pop %r9\n"
          "pop %r8\n"
          "pop %rbp\n"
          "pop %rdi\n"
          "pop %rsi\n"
          "pop %rdx\n"
          "pop %rcx\n"
          "pop %rbx\n");
     /* Restore rsp from gsTCB->TempStack */
     asmv("mov %gs:0x8, %rsp\n");
 #ifdef DEBUG
     /* Easier to debug stacks */
     asmv("movq $0, %gs:0x8\n");
 #endif
     asmv("swapgs\n");  /* Swap GS back to the user GS */
     asmv("sti\n");     /* Enable interrupts */
     asmv("sysretq\n"); /* Return to rcx address in user mode */
 }
References asmv().
__errno_location()
EXTERNC int* __errno_location (void)
Definition at line 28 of file errno.cpp.
 {
     if (unlikely(!TaskManager || !thisThread))
         return &errno_value;
     return &thisThread->ErrorNumber;
 }
References TaskManager, thisThread, and unlikely.
strerror()
char* strerror (int errnum)
Definition at line 35 of file errno.cpp.
 {
     if (errnum < 0)
         errnum = -errnum;
     switch (errnum)
     {
     case EOK:
         return (char *)"No error";
     case E2BIG:
         return (char *)"Argument list too long";
     case EACCES:
         return (char *)"Permission denied";
     case EADDRINUSE:
         return (char *)"Address in use";
     case EADDRNOTAVAIL:
         return (char *)"Address not available";
     case EAFNOSUPPORT:
         return (char *)"Address family not supported";
     case EAGAIN:
         return (char *)"Resource unavailable, try again";
     case EALREADY:
         return (char *)"Connection already in progress";
     case EBADF:
         return (char *)"Bad file descriptor";
     case EBADMSG:
         return (char *)"Bad message";
     case EBUSY:
         return (char *)"Device or resource busy";
     case ECANCELED:
         return (char *)"Operation canceled";
     case ECHILD:
         return (char *)"No child processes";
     case ECONNABORTED:
         return (char *)"Connection aborted";
     case ECONNREFUSED:
         return (char *)"Connection refused";
     case ECONNRESET:
         return (char *)"Connection reset";
     case EDEADLK:
         return (char *)"Resource deadlock would occur";
     case EDESTADDRREQ:
         return (char *)"Destination address required";
     case EDOM:
         return (char *)"Mathematics argument out of domain of function";
     case EDQUOT:
         return (char *)"Reserved";
     case EEXIST:
         return (char *)"File exists";
     case EFAULT:
         return (char *)"Bad address";
     case EFBIG:
         return (char *)"File too large";
     case EHOSTUNREACH:
         return (char *)"Host is unreachable";
     case EIDRM:
         return (char *)"Identifier removed";
     case EILSEQ:
         return (char *)"Illegal byte sequence";
     case EINPROGRESS:
         return (char *)"Operation in progress";
     case EINTR:
         return (char *)"Interrupted function";
     case EINVAL:
         return (char *)"Invalid argument";
     case EIO:
         return (char *)"I/O error";
     case EISCONN:
         return (char *)"Socket is connected";
     case EISDIR:
         return (char *)"Is a directory";
     case ELOOP:
         return (char *)"Too many levels of symbolic links";
     case EMFILE:
         return (char *)"File descriptor value too large";
     case EMLINK:
         return (char *)"Too many links";
     case EMSGSIZE:
         return (char *)"Message too large";
     case EMULTIHOP:
         return (char *)"Reserved";
     case ENAMETOOLONG:
         return (char *)"Filename too long";
     case ENETDOWN:
         return (char *)"Network is down";
     case ENETRESET:
         return (char *)"Connection aborted by network";
     case ENETUNREACH:
         return (char *)"Network unreachable";
     case ENFILE:
         return (char *)"Too many files open in system";
     case ENOBUFS:
         return (char *)"No buffer space available";
     case ENODATA:
         return (char *)"No message available on the STREAM head read queue";
     case ENODEV:
         return (char *)"No such device";
     case ENOENT:
         return (char *)"No such file or directory";
     case ENOEXEC:
         return (char *)"Executable file format error";
     case ENOLCK:
         return (char *)"No locks available";
     case ENOLINK:
         return (char *)"Reserved";
     case ENOMEM:
         return (char *)"Not enough space";
     case ENOMSG:
         return (char *)"No message of the desired type";
     case ENOPROTOOPT:
         return (char *)"Protocol not available";
     case ENOSPC:
         return (char *)"No space left on device";
     case ENOSR:
         return (char *)"No STREAM resources";
     case ENOSTR:
         return (char *)"Not a STREAM";
     case ENOSYS:
         return (char *)"Functionality not supported";
     case ENOTCONN:
         return (char *)"The socket is not connected";
     case ENOTDIR:
         return (char *)"Not a directory or a symbolic link to a directory";
     case ENOTEMPTY:
         return (char *)"Directory not empty";
     case ENOTRECOVERABLE:
         return (char *)"State not recoverable";
     case ENOTSOCK:
         return (char *)"Not a socket";
     case ENOTSUP:
         return (char *)"Not supported";
     case ENOTTY:
         return (char *)"Inappropriate I/O control operation";
     case ENXIO:
         return (char *)"No such device or address";
     case EOPNOTSUPP:
         return (char *)"Operation not supported on socket";
     case EOVERFLOW:
         return (char *)"Value too large to be stored in data type";
     case EOWNERDEAD:
         return (char *)"Previous owner died";
     case EPERM:
         return (char *)"Operation not permitted";
     case EPIPE:
         return (char *)"Broken pipe";
     case EPROTO:
         return (char *)"Protocol error";
     case EPROTONOSUPPORT:
         return (char *)"Protocol not supported";
     case EPROTOTYPE:
         return (char *)"Protocol wrong type for socket";
     case ERANGE:
         return (char *)"Result too large";
     case EROFS:
         return (char *)"Read-only file system";
     case ESPIPE:
         return (char *)"Invalid seek";
     case ESRCH:
         return (char *)"No such process";
     case ESTALE:
         return (char *)"Reserved";
     case ETIME:
         return (char *)"Stream ioctl() timeout";
     case ETIMEDOUT:
         return (char *)"Connection timed out";
     case ETXTBSY:
         return (char *)"Text file busy";
     case EWOULDBLOCK:
         return (char *)"Operation would block";
     case EXDEV:
         return (char *)"Cross-device link";
     default:
         return (char *)"Unknown error";
     }
 }
References E2BIG, EACCES, EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, EAGAIN, EALREADY, EBADF, EBADMSG, EBUSY, ECANCELED, ECHILD, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDEADLK, EDESTADDRREQ, EDOM, EDQUOT, EEXIST, EFAULT, EFBIG, EHOSTUNREACH, EIDRM, EILSEQ, EINPROGRESS, EINTR, EINVAL, EIO, EISCONN, EISDIR, ELOOP, EMFILE, EMLINK, EMSGSIZE, EMULTIHOP, ENAMETOOLONG, ENETDOWN, ENETRESET, ENETUNREACH, ENFILE, ENOBUFS, ENODATA, ENODEV, ENOENT, ENOEXEC, ENOLCK, ENOLINK, ENOMEM, ENOMSG, ENOPROTOOPT, ENOSPC, ENOSR, ENOSTR, ENOSYS, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTRECOVERABLE, ENOTSOCK, ENOTSUP, ENOTTY, ENXIO, EOK, EOPNOTSUPP, EOVERFLOW, EOWNERDEAD, EPERM, EPIPE, EPROTO, EPROTONOSUPPORT, EPROTOTYPE, ERANGE, EROFS, ESPIPE, ESRCH, ESTALE, ETIME, ETIMEDOUT, ETXTBSY, EWOULDBLOCK, and EXDEV.
Referenced by cmd_modinfo(), KernelMainThread(), KShellThread(), linux_mmap(), Driver::Manager::LoadAllDrivers(), Driver::Manager::PreloadDrivers(), Driver::Manager::UnloadAllDrivers(), and WriteDiagDataToNode().