Fennix: Userspace/musl/include/libintl.h File Reference
libintl.h File Reference
Macros
#define __USE_GNU_GETTEXT 1
#define __GNU_GETTEXT_SUPPORTED_REVISION(major) ((major) == 0 ? 1 : -1)
#define __fa(n)
Functions
char * gettext (const char *) __fa(1)
char * dgettext (const char *, const char *) __fa(2)
char * dcgettext (const char *, const char *, int) __fa(2)
char * ngettext (const char *, const char *, unsigned long) __fa(1) __fa(2)
char * dngettext (const char *, const char *, const char *, unsigned long) __fa(2) __fa(3)
char * dcngettext (const char *, const char *, const char *, unsigned long, int) __fa(2) __fa(3)
char * textdomain (const char *)
char * bindtextdomain (const char *, const char *)
char * bind_textdomain_codeset (const char *, const char *)
Macro Definition Documentation
__fa
#define __fa (n)
Definition at line 14 of file libintl.h.
__GNU_GETTEXT_SUPPORTED_REVISION
#define __GNU_GETTEXT_SUPPORTED_REVISION (major) ((major) == 0 ? 1 : -1)
Definition at line 9 of file libintl.h.
__USE_GNU_GETTEXT
#define __USE_GNU_GETTEXT 1
Definition at line 8 of file libintl.h.
Function Documentation
bind_textdomain_codeset()
char* bind_textdomain_codeset (const char * domainname, const char * codeset)
Definition at line 6 of file bind_textdomain_codeset.c.
 {
     if (codeset && strcasecmp(codeset, "UTF-8"))
         errno = EINVAL;
     return NULL;
 }
References EINVAL, errno, NULL, and strcasecmp().
bindtextdomain()
char* bindtextdomain (const char * domainname, const char * dirname)
Definition at line 46 of file dcngettext.c.
 {
     struct binding *p, *q;
     if (!domainname) return 0;
     if (!dirname) return gettextdir(domainname, &(size_t){0});
     size_t domlen = strnlen(domainname, NAME_MAX+1);
     size_t dirlen = strnlen(dirname, PATH_MAX);
     if (domlen > NAME_MAX || dirlen >= PATH_MAX) {
         errno = EINVAL;
         return 0;
     }
     LOCK(lock);
     for (p=bindings; p; p=p->next) {
         if (!strcmp(p->domainname, domainname) &&
             !strcmp(p->dirname, dirname)) {
             break;
         }
     }
     if (!p) {
         p = calloc(sizeof *p + domlen + dirlen + 2, 1);
         if (!p) {
             UNLOCK(lock);
             return 0;
         }
         p->next = bindings;
         p->dirlen = dirlen;
         p->domainname = p->buf;
         p->dirname = p->buf + domlen + 1;
         memcpy(p->domainname, domainname, domlen+1);
         memcpy(p->dirname, dirname, dirlen+1);
         a_cas_p(&bindings, bindings, p);
     }
     a_store(&p->active, 1);
     for (q=bindings; q; q=q->next) {
         if (!strcmp(q->domainname, domainname) && q != p)
             a_store(&q->active, 0);
     }
     UNLOCK(lock);
     return (char *)p->dirname;
 }
References a_cas_p, a_store, binding::active, bindings, calloc, binding::dirlen, dirname(), binding::domainname, EINVAL, errno, gettextdir(), LOCK, lock, memcpy, binding::next, p, strcmp, strnlen(), and UNLOCK.
dcgettext()
char* dcgettext (const char * domainname, const char * msgid, int category)
Definition at line 270 of file dcngettext.c.
 {
     return dcngettext(domainname, msgid, 0, 1, category);
 }
References dcngettext(), and binding::domainname.
dcngettext()
char* dcngettext (const char * , const char * , const char * , unsigned long , int)
dgettext()
char* dgettext (const char * domainname, const char * msgid)
Definition at line 280 of file dcngettext.c.
 {
     return dcngettext(domainname, msgid, 0, 1, LC_MESSAGES);
 }
References dcngettext(), binding::domainname, and LC_MESSAGES.
Referenced by gettext().
dngettext()
char* dngettext (const char * , const char * , const char * , unsigned long)
Referenced by ngettext().
gettext()
char* gettext (const char * msgid)
Definition at line 34 of file textdomain.c.
 {
     return dgettext(0, msgid);
 }
References dgettext().
ngettext()
char* ngettext (const char * , const char * , unsigned long)
textdomain()
char* textdomain (const char * domainname)
Definition at line 14 of file textdomain.c.
 {
     if (!domainname) return __gettextdomain();
     size_t domlen = strlen(domainname);
     if (domlen > NAME_MAX) {
         errno = EINVAL;
         return 0;
     }
     if (!current_domain) {
         current_domain = malloc(NAME_MAX+1);
         if (!current_domain) return 0;
     }
     memcpy(current_domain, domainname, domlen+1);
     return current_domain;
 }
References __gettextdomain(), current_domain, EINVAL, errno, malloc, memcpy, and strlen.