Fennix: Userspace/apps/base/busybox/coreutils/sum.c File Reference
sum.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define buf bb_common_bufsiz1
Enumerations
enum { SUM_BSD , PRINT_NAME , SUM_SYSV }
Functions
static unsigned sum_file (const char *file, unsigned type)
int sum_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
buf
#define buf bb_common_bufsiz1
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SUM_BSD
PRINT_NAME
SUM_SYSV
Definition at line 35 of file sum.c.
 { SUM_BSD, PRINT_NAME, SUM_SYSV };
Function Documentation
sum_file()
static unsigned sum_file (const char * file, unsigned type) static
Definition at line 41 of file sum.c.
 {
     unsigned long long total_bytes = 0;
     int fd, r;
     /* The sum of all the input bytes, modulo (UINT_MAX + 1).  */
     unsigned s = 0;
 #define buf bb_common_bufsiz1
     setup_common_bufsiz();
     fd = open_or_warn_stdin(file);
     if (fd == -1)
         return 0;
     while (1) {
         size_t bytes_read = safe_read(fd, buf, COMMON_BUFSIZE);
         if ((ssize_t)bytes_read <= 0) {
             r = (fd && close(fd) != 0);
             if (!bytes_read && !r)
                 /* no error */
                 break;
             bb_simple_perror_msg(file);
             return 0;
         }
         total_bytes += bytes_read;
         if (type >= SUM_SYSV) {
             do s += buf[--bytes_read]; while (bytes_read);
         } else {
             r = 0;
             do {
                 s = (s >> 1) + ((s & 1) << 15);
                 s += buf[r++];
                 s &= 0xffff; /* Keep it within bounds. */
             } while (--bytes_read);
         }
     }
     if (type < PRINT_NAME)
         file = "";
     if (type >= SUM_SYSV) {
         r = (s & 0xffff) + ((s & 0xffffffff) >> 16);
         s = (r & 0xffff) + (r >> 16);
         printf("%u %llu %s\n", s, (total_bytes + 511) / 512, file);
     } else
         printf("%05u %5llu %s\n", s, (total_bytes + 1023) / 1024, file);
     return 1;
 #undef buf
 }
References bb_simple_perror_msg(), buf, bytes_read, close(), fd, open_or_warn_stdin(), PRINT_NAME, printf, s, safe_read(), SUM_SYSV, and type.
Referenced by sum_main().
sum_main()
int sum_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 93 of file sum.c.
 {
     unsigned n;
     unsigned type = SUM_BSD;
     n = getopt32(argv, "sr");
     argv += optind;
     if (n & 1) type = SUM_SYSV;
     /* give the bsd priority over sysv func */
     if (n & 2) type = SUM_BSD;
     if (!argv[0]) {
         /* Do not print the name */
         n = sum_file("-", type);
     } else {
         /* Need to print the name if either
          * - more than one file given
          * - doing sysv */
         type += (argv[1] || type == SUM_SYSV);
         n = 1;
         do {
             n &= sum_file(*argv, type);
         } while (*++argv);
     }
     return !n;
 }
References argv, getopt32(), n, optind, SUM_BSD, sum_file(), SUM_SYSV, and type.