Fennix: Userspace/mlibc/options/posix/include/bits/posix/posix_ctype.h File Reference
posix_ctype.h File Reference
#include <bits/posix/locale_t.h>
Functions
int isalnum_l (int c, locale_t loc)
int isalpha_l (int c, locale_t loc)
int isblank_l (int c, locale_t loc)
int iscntrl_l (int c, locale_t loc)
int isdigit_l (int c, locale_t loc)
int isgraph_l (int c, locale_t loc)
int islower_l (int c, locale_t loc)
int isprint_l (int c, locale_t loc)
int ispunct_l (int c, locale_t loc)
int isspace_l (int c, locale_t loc)
int isupper_l (int c, locale_t loc)
int isxdigit_l (int c, locale_t loc)
int isascii_l (int c, locale_t loc)
int tolower_l (int c, locale_t loc)
int toupper_l (int c, locale_t loc)
Function Documentation
isalnum_l()
int isalnum_l (int c, locale_t loc)
Definition at line 6 of file posix_ctype.cpp.
{
     return isalnum(c);
 }
References c, and isalnum().
isalpha_l()
int isalpha_l (int c, locale_t loc)
Definition at line 10 of file posix_ctype.cpp.
{
     return isalpha(c);
 }
References c, and isalpha().
isascii_l()
int isascii_l (int c, locale_t loc)
Definition at line 54 of file posix_ctype.cpp.
{
     return isascii(c);
 }
References c, and isascii().
isblank_l()
int isblank_l (int c, locale_t loc)
Definition at line 14 of file posix_ctype.cpp.
{
     return isblank(c);
 }
References c, and isblank().
iscntrl_l()
int iscntrl_l (int c, locale_t loc)
Definition at line 18 of file posix_ctype.cpp.
{
     return iscntrl(c);
 }
References c, and iscntrl().
isdigit_l()
int isdigit_l (int c, locale_t loc)
Definition at line 22 of file posix_ctype.cpp.
{
     return isdigit(c);
 }
References c, and isdigit().
isgraph_l()
int isgraph_l (int c, locale_t loc)
Definition at line 26 of file posix_ctype.cpp.
{
     return isgraph(c);
 }
References c, and isgraph().
islower_l()
int islower_l (int c, locale_t loc)
Definition at line 30 of file posix_ctype.cpp.
{
     return islower(c);
 }
References c, and islower().
isprint_l()
int isprint_l (int c, locale_t loc)
Definition at line 34 of file posix_ctype.cpp.
{
     return isprint(c);
 }
References c, and isprint().
ispunct_l()
int ispunct_l (int c, locale_t loc)
Definition at line 38 of file posix_ctype.cpp.
{
     return ispunct(c);
 }
References c, and ispunct().
isspace_l()
int isspace_l (int c, locale_t loc)
Definition at line 42 of file posix_ctype.cpp.
{
     return isspace(c);
 }
References c, and isspace().
isupper_l()
int isupper_l (int c, locale_t loc)
Definition at line 46 of file posix_ctype.cpp.
{
     return isupper(c);
 }
References c, and isupper().
isxdigit_l()
int isxdigit_l (int c, locale_t loc)
Definition at line 50 of file posix_ctype.cpp.
{
     return isxdigit(c);
 }
References c, and isxdigit().
tolower_l()
int tolower_l (int c, locale_t loc)
Definition at line 58 of file posix_ctype.cpp.
{
     return tolower(c);
 }
References c, and tolower.
toupper_l()
int toupper_l (int c, locale_t loc)
Definition at line 62 of file posix_ctype.cpp.
{
     return toupper(c);
 }
References c, and toupper.