Fennix: Userspace/apps/base/bash/lib/readline/keymaps.c File Reference
keymaps.c File Reference
#include "ansi_stdlib.h"
#include <stdio.h>
#include "readline.h"
#include "rlconf.h"
#include "emacs_keymap.c"
#include "vi_keymap.c"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
Functions
Keymap rl_make_bare_keymap (void)
int rl_empty_keymap (Keymap keymap)
Keymap rl_copy_keymap (Keymap map)
Keymap rl_make_keymap (void)
void rl_discard_keymap (Keymap map)
void rl_free_keymap (Keymap map)
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file keymaps.c.
Function Documentation
rl_copy_keymap()
Keymap rl_copy_keymap (Keymap map)
Definition at line 98 of file keymaps.c.
 {
   register int i;
   Keymap temp;
   temp = rl_make_bare_keymap ();
   for (i = 0; i < KEYMAP_SIZE; i++)
     {
       temp[i].type = map[i].type;
       temp[i].function = map[i].function;
     }
   return (temp);
 }
References _keymap_entry::function, i, KEYMAP_SIZE, map, rl_make_bare_keymap(), and _keymap_entry::type.
rl_discard_keymap()
void rl_discard_keymap (Keymap map)
Definition at line 142 of file keymaps.c.
 {
   int i;
   if (map == 0)
     return;
   for (i = 0; i < KEYMAP_SIZE; i++)
     {
       switch (map[i].type)
     {
     case ISFUNC:
       break;
     case ISKMAP:
       rl_discard_keymap ((Keymap)map[i].function);
       xfree ((char *)map[i].function);
       break;
     case ISMACR:
       xfree ((char *)map[i].function);
       break;
     }
     }
 }
References i, ISFUNC, ISKMAP, ISMACR, KEYMAP_SIZE, map, type, and xfree.
Referenced by rl_free_keymap(), and rl_generic_bind().
rl_empty_keymap()
int rl_empty_keymap (Keymap keymap)
Definition at line 83 of file keymaps.c.
 {
   int i;
   for (i = 0; i < ANYOTHERKEY; i++)
     {
       if (keymap[i].type != ISFUNC || keymap[i].function)
     return 0;
     }
   return 1;
 }
References ANYOTHERKEY, i, ISFUNC, and type.
Referenced by rl_generic_bind().
rl_free_keymap()
void rl_free_keymap (Keymap map)
Definition at line 170 of file keymaps.c.
 {
   rl_discard_keymap (map);
   xfree ((char *)map);
 }
References map, rl_discard_keymap(), and xfree.
rl_make_bare_keymap()
Keymap rl_make_bare_keymap (void)
Definition at line 57 of file keymaps.c.
 {
   register int i;
   Keymap keymap;
   keymap = (Keymap)xmalloc (KEYMAP_SIZE * sizeof (KEYMAP_ENTRY));
   for (i = 0; i < KEYMAP_SIZE; i++)
     {
       keymap[i].type = ISFUNC;
       keymap[i].function = (rl_command_func_t *)NULL;
     }
 #if 0
   for (i = 'A'; i < ('Z' + 1); i++)
     {
       keymap[i].type = ISFUNC;
       keymap[i].function = rl_do_lowercase_version;
     }
 #endif
   return (keymap);
 }
References _keymap_entry::function, i, ISFUNC, KEYMAP_SIZE, NULL, rl_do_lowercase_version(), _keymap_entry::type, and xmalloc.
Referenced by rl_copy_keymap(), rl_generic_bind(), rl_make_keymap(), and rl_vi_replace().
rl_make_keymap()
Keymap rl_make_keymap (void)
Definition at line 116 of file keymaps.c.
 {
   register int i;
   Keymap newmap;
   newmap = rl_make_bare_keymap ();
   /* All ASCII printing characters are self-inserting. */
   for (i = ' '; i < 127; i++)
     newmap[i].function = rl_insert;
   newmap[TAB].function = rl_insert;
   newmap[RUBOUT].function = rl_rubout;  /* RUBOUT == 127 */
   newmap[CTRL('H')].function = rl_rubout;
 #if KEYMAP_SIZE > 128
   /* Printing characters in ISO Latin-1 and some 8-bit character sets. */
   for (i = 128; i < 256; i++)
     newmap[i].function = rl_insert;
 #endif /* KEYMAP_SIZE > 128 */
   return (newmap);
 }
References CTRL, _keymap_entry::function, i, rl_insert(), rl_make_bare_keymap(), rl_rubout(), RUBOUT, and TAB.