Fennix Userspace: Userspace/apps/base/busybox/libbb/percent_decode.c File Reference
percent_decode.c File Reference
#include "libbb.h"
Functions
static unsigned hex_to_bin (unsigned char c)
char *FAST_FUNC percent_decode_in_place (char *str, int strict)
Function Documentation
hex_to_bin()
static unsigned hex_to_bin (unsigned char c) static
Definition at line 9 of file percent_decode.c.
 {
     unsigned v;
     v = c - '0';
     if (v <= 9)
         return v;
     /* c | 0x20: letters to lower case, non-letters
      * to (potentially different) non-letters */
     v = (unsigned)(c | 0x20) - 'a';
     if (v <= 5)
         return v + 10;
     return ~0;
 /* For testing:
 void t(char c) { printf("'%c'(%u) %u\n", c, c, hex_to_bin(c)); }
 int main() { t(0x10); t(0x20); t('0'); t('9'); t('A'); t('F'); t('a'); t('f');
 t('0'-1); t('9'+1); t('A'-1); t('F'+1); t('a'-1); t('f'+1); return 0; }
 */
 }
References c.
Referenced by percent_decode_in_place().
percent_decode_in_place()
char* FAST_FUNC percent_decode_in_place (char * str, int strict)
Definition at line 29 of file percent_decode.c.
 {
     /* note that decoded string is always shorter than original */
     char *src = str;
     char *dst = str;
     char c;
     while ((c = *src++) != '\0') {
         unsigned v;
         if (!strict && c == '+') {
             *dst++ = ' ';
             continue;
         }
         if (c != '%') {
             *dst++ = c;
             continue;
         }
         v = hex_to_bin(src[0]);
         if (v > 15) {
  bad_hex:
             if (strict)
                 return NULL;
             *dst++ = '%';
             continue;
         }
         v = (v * 16) | hex_to_bin(src[1]);
         if (v > 255)
             goto bad_hex;
         if (strict && (v == '/' || v == '\0')) {
             /* caller takes it as indication of invalid
              * (dangerous wrt exploits) chars */
             return str + 1;
         }
         *dst++ = v;
         src += 2;
     }
     *dst = '\0';
     return str;
 }
References c, dst, hex_to_bin(), NULL, src, and str.
Referenced by handle_incoming_and_exit(), httpd_main(), and parse_url().