Fennix Kernel: PCI::PCI Class Reference
PCI::PCI Class Reference
#include <pci.hpp>
Public Member Functions
std::vector< PCIDeviceHeader * > & GetDevices ()
void MapPCIAddresses (PCIDeviceHeader *PCIDevice, Memory::PageTable *Table=nullptr)
void EnumerateFunction (uint64_t DeviceAddress, uintptr_t Function)
void EnumerateDevice (uint64_t BusAddress, uintptr_t Device)
void EnumerateBus (uint64_t BaseAddress, uintptr_t Bus)
std::vector< PCIDeviceHeader * > FindPCIDevice (uint8_t Class, uint8_t Subclass, uint8_t ProgIF)
std::vector< PCIDeviceHeader * > FindPCIDevice (int VendorID, int DeviceID)
PCI ()
~PCI ()
Private Attributes
std::vector< PCIDeviceHeader * > Devices
Detailed Description
Definition at line 223 of file pci.hpp.
Constructor & Destructor Documentation
PCI()
PCI::PCI::PCI ()
Definition at line 952 of file PeripheralComponentInterconnect.cpp.
     {
 #if defined(a86)
         if (!PowerManager->GetACPI())
         {
             error("ACPI not found");
             return;
         }
         if (!((ACPI::ACPI *)PowerManager->GetACPI())->MCFG)
         {
             error("MCFG not found");
             return;
         }
         int Entries = s_cst(int, ((((ACPI::ACPI *)PowerManager->GetACPI())->MCFG->Header.Length) - sizeof(ACPI::ACPI::MCFGHeader)) / sizeof(DeviceConfig));
         Memory::Virtual vmm = Memory::Virtual(KernelPageTable);
         for (int t = 0; t < Entries; t++)
         {
             DeviceConfig *NewDeviceConfig = (DeviceConfig *)((uintptr_t)((ACPI::ACPI *)PowerManager->GetACPI())->MCFG + sizeof(ACPI::ACPI::MCFGHeader) + (sizeof(DeviceConfig) * t));
             vmm.Map((void *)NewDeviceConfig->BaseAddress, (void *)NewDeviceConfig->BaseAddress, Memory::PTFlag::RW);
             debug("PCI Entry %d Address:%p BUS:%#x-%#x", t, NewDeviceConfig->BaseAddress,
                   NewDeviceConfig->StartBus, NewDeviceConfig->EndBus);
             for (uintptr_t Bus = NewDeviceConfig->StartBus; Bus < NewDeviceConfig->EndBus; Bus++)
                 EnumerateBus(NewDeviceConfig->BaseAddress, Bus);
         }
 #elif defined(aa64)
         error("PCI not implemented on aarch64");
 #endif
     }
References PCI::DeviceConfig::BaseAddress, debug, PCI::DeviceConfig::EndBus, Entries, error, Power::Power::GetACPI(), KernelPageTable, PowerManager, and PCI::DeviceConfig::StartBus.
~PCI()
PCI::PCI::~PCI ()
Definition at line 983 of file PeripheralComponentInterconnect.cpp.
     {
     }
Member Function Documentation
EnumerateBus()
void PCI::PCI::EnumerateBus (uint64_t BaseAddress, uintptr_t Bus)
Definition at line 912 of file PeripheralComponentInterconnect.cpp.
     {
         uintptr_t Offset = Bus << 20;
         uint64_t BusAddress = BaseAddress + Offset;
         Memory::Virtual(KernelPageTable).Map((void *)BusAddress, (void *)BusAddress, Memory::PTFlag::RW);
         PCIDeviceHeader *PCIDeviceHdr = (PCIDeviceHeader *)BusAddress;
         if (Bus != 0) // TODO: VirtualBox workaround (UNTESTED ON REAL HARDWARE!)
         {
             if (PCIDeviceHdr->DeviceID == 0)
                 return;
             if (PCIDeviceHdr->DeviceID == 0xFFFF)
                 return;
         }
         debug("PCI Bus DeviceID:%#x VendorID:%#x BIST:%#x Cache:%#x Class:%#x Cmd:%#x HdrType:%#x LatencyTimer:%#x ProgIF:%#x RevID:%#x Status:%#x SubClass:%#x ",
               PCIDeviceHdr->DeviceID, PCIDeviceHdr->VendorID, PCIDeviceHdr->BIST,
               PCIDeviceHdr->CacheLineSize, PCIDeviceHdr->Class, PCIDeviceHdr->Command,
               PCIDeviceHdr->HeaderType, PCIDeviceHdr->LatencyTimer, PCIDeviceHdr->ProgIF,
               PCIDeviceHdr->RevisionID, PCIDeviceHdr->Status, PCIDeviceHdr->Subclass);
         for (uintptr_t Device = 0; Device < 32; Device++)
             EnumerateDevice(BusAddress, Device);
     }
References PCI::PCIDeviceHeader::BIST, PCI::PCIDeviceHeader::CacheLineSize, PCI::PCIDeviceHeader::Class, PCI::PCIDeviceHeader::Command, debug, PCI::PCIDeviceHeader::DeviceID, PCI::PCIDeviceHeader::HeaderType, KernelPageTable, PCI::PCIDeviceHeader::LatencyTimer, PCI::PCIDeviceHeader::ProgIF, PCI::PCIDeviceHeader::RevisionID, PCI::PCIDeviceHeader::Status, PCI::PCIDeviceHeader::Subclass, and PCI::PCIDeviceHeader::VendorID.
EnumerateDevice()
void PCI::PCI::EnumerateDevice (uint64_t BusAddress, uintptr_t Device)
Definition at line 898 of file PeripheralComponentInterconnect.cpp.
     {
         uintptr_t Offset = Device << 15;
         uint64_t DeviceAddress = BusAddress + Offset;
         Memory::Virtual(KernelPageTable).Map((void *)DeviceAddress, (void *)DeviceAddress, Memory::PTFlag::RW);
         PCIDeviceHeader *PCIDeviceHdr = (PCIDeviceHeader *)DeviceAddress;
         if (PCIDeviceHdr->DeviceID == 0)
             return;
         if (PCIDeviceHdr->DeviceID == 0xFFFF)
             return;
         for (uintptr_t Function = 0; Function < 8; Function++)
             EnumerateFunction(DeviceAddress, Function);
     }
References PCI::PCIDeviceHeader::DeviceID, and KernelPageTable.
EnumerateFunction()
void PCI::PCI::EnumerateFunction (uint64_t DeviceAddress, uintptr_t Function)
Definition at line 882 of file PeripheralComponentInterconnect.cpp.
     {
         uintptr_t Offset = Function << 12;
         uint64_t FunctionAddress = DeviceAddress + Offset;
         Memory::Virtual(KernelPageTable).Map((void *)FunctionAddress, (void *)FunctionAddress, Memory::PTFlag::RW);
         PCIDeviceHeader *PCIDeviceHdr = (PCIDeviceHeader *)FunctionAddress;
         if (PCIDeviceHdr->DeviceID == 0)
             return;
         if (PCIDeviceHdr->DeviceID == 0xFFFF)
             return;
         Devices.push_back(PCIDeviceHdr);
 #ifdef DEBUG
         e(PCIDeviceHdr);
 #endif
     }
References PCI::PCIDeviceHeader::DeviceID, and KernelPageTable.
FindPCIDevice() [1/2]
std::vector< PCIDeviceHeader * > PCI::PCI::FindPCIDevice (int VendorID, int DeviceID)
Definition at line 943 of file PeripheralComponentInterconnect.cpp.
     {
         std::vector<PCIDeviceHeader *> DeviceFound;
         for (auto var : Devices)
             if (var->VendorID == VendorID && var->DeviceID == DeviceID)
                 DeviceFound.push_back(var);
         return DeviceFound;
     }
FindPCIDevice() [2/2]
std::vector< PCIDeviceHeader * > PCI::PCI::FindPCIDevice (uint8_t Class, uint8_t Subclass, uint8_t ProgIF)
Definition at line 934 of file PeripheralComponentInterconnect.cpp.
     {
         std::vector<PCIDeviceHeader *> DeviceFound;
         for (auto var : Devices)
             if (var->Class == Class && var->Subclass == Subclass && var->ProgIF == ProgIF)
                 DeviceFound.push_back(var);
         return DeviceFound;
     }
Referenced by Driver::Driver::DriverLoadBindPCI(), and FindPCI().
GetDevices()
std::vector<PCIDeviceHeader *>& PCI::PCI::GetDevices () inline
Definition at line 229 of file pci.hpp.
 { return Devices; }
Referenced by cmd_lspci(), and Main().
MapPCIAddresses()
void PCI::PCI::MapPCIAddresses (PCIDeviceHeader * PCIDevice, Memory::PageTable * Table = nullptr)
Definition at line 787 of file PeripheralComponentInterconnect.cpp.
     {
         debug("Header Type: %d", PCIDevice->HeaderType);
         switch (PCIDevice->HeaderType)
         {
         case 0: /* PCI Header 0 */
         {
             uint32_t BAR[6] = {0};
             size_t BARsSize[6] = {0};
             BAR[0] = ((PCIHeader0 *)PCIDevice)->BAR0;
             BAR[1] = ((PCIHeader0 *)PCIDevice)->BAR1;
             BAR[2] = ((PCIHeader0 *)PCIDevice)->BAR2;
             BAR[3] = ((PCIHeader0 *)PCIDevice)->BAR3;
             BAR[4] = ((PCIHeader0 *)PCIDevice)->BAR4;
             BAR[5] = ((PCIHeader0 *)PCIDevice)->BAR5;
             debug("Type: %d; IOBase: %#lx; MemoryBase: %#lx",
                   BAR[0] & 1,
                   BAR[1] & (~3),
                   BAR[0] & (~15));
             /* BARs Size */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 if ((BAR[i] & 1) == 0) /* Memory Base */
                 {
                     ((PCIHeader0 *)PCIDevice)->BAR0 = 0xFFFFFFFF;
                     size_t size = ((PCIHeader0 *)PCIDevice)->BAR0;
                     ((PCIHeader0 *)PCIDevice)->BAR0 = BAR[i];
                     BARsSize[i] = size & (~15);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFFFFFF;
                     debug("BAR%d %#lx size: %d", i, BAR[i], BARsSize[i]);
                 }
                 else if ((BAR[i] & 1) == 1) /* I/O Base */
                 {
                     ((PCIHeader0 *)PCIDevice)->BAR1 = 0xFFFFFFFF;
                     size_t size = ((PCIHeader0 *)PCIDevice)->BAR1;
                     ((PCIHeader0 *)PCIDevice)->BAR1 = BAR[i];
                     BARsSize[i] = size & (~3);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFF;
                     debug("BAR%d %#lx size: %d", i, BAR[i], BARsSize[i]);
                 }
             }
             /* Mapping the BARs */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 if ((BAR[i] & 1) == 0) /* Memory Base */
                 {
                     uintptr_t BARBase = BAR[i] & (~15);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#lx-%#lx", i, BARBase, BARBase + BARSize);
                     Memory::Virtual(Table).Map((void *)BARBase, (void *)BARBase, BARSize,
                                                Memory::PTFlag::RW | Memory::PTFlag::PWT);
                 }
                 else if ((BAR[i] & 1) == 1) /* I/O Base */
                 {
                     uintptr_t BARBase = BAR[i] & (~3);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#x-%#x", i, BARBase, BARBase + BARSize);
                     Memory::Virtual(Table).Map((void *)BARBase, (void *)BARBase, BARSize,
                                                Memory::PTFlag::RW | Memory::PTFlag::PWT);
                 }
             }
             break;
         }
         case 1: /* PCI Header 1 (PCI-to-PCI Bridge) */
         {
             fixme("PCI Header 1 (PCI-to-PCI Bridge) not implemented yet");
             break;
         }
         case 2: /* PCI Header 2 (PCI-to-CardBus Bridge) */
         {
             fixme("PCI Header 2 (PCI-to-CardBus Bridge) not implemented yet");
             break;
         }
         default:
         {
             error("Unknown header type %d", PCIDevice->HeaderType);
             return;
         }
         }
     }
References PCNET::BAR, debug, error, fixme, PCI::PCIDeviceHeader::HeaderType, and size.
Referenced by Driver::Driver::DriverLoadBindPCI().
Field Documentation
Devices
std::vector<PCIDeviceHeader *> PCI::PCI::Devices private
Definition at line 226 of file pci.hpp.
The documentation for this class was generated from the following files:
Kernel/include/pci.hpp
Kernel/Core/PeripheralComponentInterconnect.cpp