Fennix: CPU::x64 Namespace Reference
CPU::x64 Namespace Reference
Namespaces
AMD
EXPERIMENTAL IMPLEMENTATION.
Intel
EXPERIMENTAL IMPLEMENTATION.
Data Structures
union __attribute__
MSR_APIC_BASE structure.
union RFLAGS
struct TrapFrame
union CR0
union CR2
union CR3
union CR4
union CR8
union XCR0
union EFER
union DR7
union PageFaultErrorCode
union SelectorErrorCode
struct FXState
struct __attribute__.__attribute__
struct RFLAGS.__unnamed464__
struct CR0.__unnamed466__
struct CR2.__unnamed468__
struct CR3.__unnamed470__
struct CR4.__unnamed472__
struct CR8.__unnamed474__
struct XCR0.__unnamed476__
struct EFER.__unnamed478__
struct DR7.__unnamed482__
struct PageFaultErrorCode.__unnamed484__
struct SelectorErrorCode.__unnamed486__
Typedefs
typedef struct CPU::x64::TrapFrame TrapFrame
typedef union CPU::x64::CR0 CR0
typedef union CPU::x64::CR2 CR2
typedef union CPU::x64::CR3 CR3
typedef union CPU::x64::CR4 CR4
typedef union CPU::x64::CR8 CR8
typedef union CPU::x64::XCR0 XCR0
typedef union CPU::x64::DR7 DR7
typedef union CPU::x64::PageFaultErrorCode PageFaultErrorCode
typedef union CPU::x64::SelectorErrorCode SelectorErrorCode
Enumerations
enum MSRID {
MSR_MONITOR_FILTER_SIZE = 0x6 , MSR_TIME_STAMP_COUNTER = 0x10 , MSR_PLATFORM_ID = 0x17 , MSR_APIC_BASE = 0x1B ,
MSR_FEATURE_CONTROL = 0x3A , MSR_TSC_ADJUST = 0x3B , MSR_SPEC_CTRL = 0x48 , MSR_PRED_CMD = 0x49 ,
MSR_BIOS_UPDT_TRIG = 0x79 , MSR_BIOS_SIGN_ID = 0x8B , MSR_SGXLEPUBKEYHASH0 = 0x8C , MSR_SGXLEPUBKEYHASH1 = 0x8D ,
MSR_SGXLEPUBKEYHASH2 = 0x8E , MSR_SGXLEPUBKEYHASH3 = 0x8F , MSR_SMM_MONITOR_CTL = 0x9B , MSR_SMBASE = 0x9E ,
MSR_PMC0 = 0xC1 , MSR_PMC1 = 0xC2 , MSR_PMC2 = 0xC3 , MSR_PMC3 = 0xC4 ,
MSR_PMC4 = 0xC5 , MSR_PMC5 = 0xC6 , MSR_PMC6 = 0xC7 , MSR_PMC7 = 0xC8 ,
MSR_UMWAIT_CONTROL = 0xE1 , MSR_MPERF = 0xE7 , MSR_APERF = 0xE8 , MSR_MTRRCAP = 0xFE ,
MSR_ARCH_CAPABILITIES = 0x10A , MSR_FLUSH_CMD = 0x10B , MSR_SYSENTER_CS = 0x17A , MSR_SYSENTER_ESP = 0x175 ,
MSR_SYSENTER_EIP = 0x176 , MSR_MCG_CAP = 0x179 , MSR_MCG_STATUS = 0x17A , MSR_MCG_CTL = 0x17B ,
MSR_PERFEVTSEL0 = 0x186 , MSR_PERFEVTSEL1 = 0x187 , MSR_PERFEVTSEL2 = 0x188 , MSR_PERFEVTSEL3 = 0x189 ,
MSR_PERF_STATUS = 0x198 , MSR_PERF_CTL = 0x199 , MSR_CLOCK_MODULATION = 0x19A , MSR_THERM_INTERRUPT = 0x19B ,
MSR_THERM_STATUS = 0x19C , MSR_MISC_ENABLE = 0x1A0 , MSR_ENERGY_PERF_BIAS = 0x1B0 , MSR_PACKAGE_THERM_STATUS = 0x1B1 ,
MSR_PACKAGE_THERM_INTERRUPT = 0x1B2 , MSR_DEBUGCTL = 0x1D9 , MSR_SMRR_PHYSBASE = 0x1F2 , MSR_SMRR_PHYSMASK = 0x1F3 ,
MSR_PLATFORM_DCA_CAP = 0x1F8 , MSR_CPU_DCA_CAP = 0x1F9 , MSR_DCA_0_CAP = 0x1FA , MSR_MTRR_PHYSBASE0 = 0x200 ,
MSR_MTRR_PHYSMASK0 = 0x201 , MSR_MTRR_PHYSBASE1 = 0x202 , MSR_MTRR_PHYSMASK1 = 0x203 , MSR_MTRR_PHYSBASE2 = 0x204 ,
MSR_MTRR_PHYSMASK2 = 0x205 , MSR_MTRR_PHYSBASE3 = 0x206 , MSR_MTRR_PHYSMASK3 = 0x207 , MSR_MTRR_PHYSBASE4 = 0x208 ,
MSR_MTRR_PHYSMASK4 = 0x209 , MSR_MTRR_PHYSBASE5 = 0x20A , MSR_MTRR_PHYSMASK5 = 0x20B , MSR_MTRR_PHYSBASE6 = 0x20C ,
MSR_MTRR_PHYSMASK6 = 0x20D , MSR_MTRR_PHYSBASE7 = 0x20E , MSR_MTRR_PHYSMASK7 = 0x20F , MSR_MTRR_PHYSBASE8 = 0x210 ,
MSR_MTRR_PHYSMASK8 = 0x211 , MSR_MTRR_PHYSBASE9 = 0x212 , MSR_MTRR_PHYSMASK9 = 0x213 , MSR_MTRR_FIX64K_00000 = 0x250 ,
MSR_MTRR_FIX16K_80000 = 0x258 , MSR_MTRR_FIX16K_A0000 = 0x259 , MSR_MTRR_FIX4K_C0000 = 0x268 , MSR_MTRR_FIX4K_C8000 = 0x269 ,
MSR_MTRR_FIX4K_D0000 = 0x26A , MSR_MTRR_FIX4K_D8000 = 0x26B , MSR_MTRR_FIX4K_E0000 = 0x26C , MSR_MTRR_FIX4K_E8000 = 0x26D ,
MSR_MTRR_FIX4K_F0000 = 0x26E , MSR_MTRR_FIX4K_F8000 = 0x26F , MSR_PAT = 0x277 , MSR_MC0_CTL2 = 0x280 ,
MSR_MC1_CTL2 = 0x281 , MSR_MC2_CTL2 = 0x282 , MSR_MC3_CTL2 = 0x283 , MSR_MC4_CTL2 = 0x284 ,
MSR_MC5_CTL2 = 0x285 , MSR_MC6_CTL2 = 0x286 , MSR_MC7_CTL2 = 0x287 , MSR_MC8_CTL2 = 0x288 ,
MSR_MC9_CTL2 = 0x289 , MSR_MC10_CTL2 = 0x28A , MSR_MC11_CTL2 = 0x28B , MSR_MC12_CTL2 = 0x28C ,
MSR_MC13_CTL2 = 0x28D , MSR_MC14_CTL2 = 0x28E , MSR_MC15_CTL2 = 0x28F , MSR_MC16_CTL2 = 0x290 ,
MSR_MC17_CTL2 = 0x291 , MSR_MC18_CTL2 = 0x292 , MSR_MC19_CTL2 = 0x293 , MSR_MC20_CTL2 = 0x294 ,
MSR_MC21_CTL2 = 0x295 , MSR_MC22_CTL2 = 0x296 , MSR_MC23_CTL2 = 0x297 , MSR_MC24_CTL2 = 0x298 ,
MSR_MC25_CTL2 = 0x299 , MSR_MC26_CTL2 = 0x29A , MSR_MC27_CTL2 = 0x29B , MSR_MC28_CTL2 = 0x29C ,
MSR_MC29_CTL2 = 0x29D , MSR_MC30_CTL2 = 0x29E , MSR_MC31_CTL2 = 0x29F , MSR_MTRR_DEF_TYPE = 0x2FF ,
MSR_FIXED_CTR0 = 0x309 , MSR_FIXED_CTR1 = 0x30A , MSR_FIXED_CTR2 = 0x30B , MSR_PERF_CAPABILITIES = 0x345 ,
MSR_FIXED_CTR_CTRL = 0x38D , MSR_PERF_GLOBAL_STATUS = 0x38E , MSR_PERF_GLOBAL_CTRL = 0x38F , MSR_PERF_GLOBAL_STATUS_RESET = 0x390 ,
MSR_PERF_GLOBAL_STATUS_SET = 0x391 , MSR_PERF_GLOBAL_INUSE = 0x392 , MSR_PEBS_ENABLE = 0x3F1 , MSR_MC0_CTL = 0x400 ,
MSR_MC0_STATUS = 0x401 , MSR_MC0_ADDR = 0x402 , MSR_MC0_MISC = 0x403 , MSR_MC1_CTL = 0x404 ,
MSR_MC1_STATUS = 0x405 , MSR_MC1_ADDR = 0x406 , MSR_MC1_MISC = 0x407 , MSR_MC2_CTL = 0x408 ,
MSR_MC2_STATUS = 0x409 , MSR_MC2_ADDR = 0x40A , MSR_MC2_MISC = 0x40B , MSR_MC3_CTL = 0x40C ,
MSR_MC3_STATUS = 0x40D , MSR_MC3_ADDR = 0x40E , MSR_MC3_MISC = 0x40F , MSR_MC4_CTL = 0x410 ,
MSR_MC4_STATUS = 0x411 , MSR_MC4_ADDR = 0x412 , MSR_MC4_MISC = 0x413 , MSR_MC5_CTL = 0x414 ,
MSR_MC5_STATUS = 0x415 , MSR_MC5_ADDR = 0x416 , MSR_MC5_MISC = 0x417 , MSR_MC6_CTL = 0x418 ,
MSR_MC6_STATUS = 0x419 , MSR_MC6_ADDR = 0x41A , MSR_MC6_MISC = 0x41B , MSR_MC7_CTL = 0x41C ,
MSR_MC7_STATUS = 0x41D , MSR_MC7_ADDR = 0x41E , MSR_MC7_MISC = 0x41F , MSR_MC8_CTL = 0x420 ,
MSR_MC8_STATUS = 0x421 , MSR_MC8_ADDR = 0x422 , MSR_MC8_MISC = 0x423 , MSR_MC9_CTL = 0x424 ,
MSR_MC9_STATUS = 0x425 , MSR_MC9_ADDR = 0x426 , MSR_MC9_MISC = 0x427 , MSR_MC10_CTL = 0x428 ,
MSR_MC10_STATUS = 0x429 , MSR_MC10_ADDR = 0x42A , MSR_MC10_MISC = 0x42B , MSR_MC11_CTL = 0x42C ,
MSR_MC11_STATUS = 0x42D , MSR_MC11_ADDR = 0x42E , MSR_MC11_MISC = 0x42F , MSR_MC12_CTL = 0x430 ,
MSR_MC12_STATUS = 0x431 , MSR_MC12_ADDR = 0x432 , MSR_MC12_MISC = 0x433 , MSR_MC13_CTL = 0x434 ,
MSR_MC13_STATUS = 0x435 , MSR_MC13_ADDR = 0x436 , MSR_MC13_MISC = 0x437 , MSR_MC14_CTL = 0x438 ,
MSR_MC14_STATUS = 0x439 , MSR_MC14_ADDR = 0x43A , MSR_MC14_MISC = 0x43B , MSR_MC15_CTL = 0x43C ,
MSR_MC15_STATUS = 0x43D , MSR_MC15_ADDR = 0x43E , MSR_MC15_MISC = 0x43F , MSR_MC16_CTL = 0x440 ,
MSR_MC16_STATUS = 0x441 , MSR_MC16_ADDR = 0x442 , MSR_MC16_MISC = 0x443 , MSR_MC17_CTL = 0x444 ,
MSR_MC17_STATUS = 0x445 , MSR_MC17_ADDR = 0x446 , MSR_MC17_MISC = 0x447 , MSR_MC18_CTL = 0x448 ,
MSR_MC18_STATUS = 0x449 , MSR_MC18_ADDR = 0x44A , MSR_MC18_MISC = 0x44B , MSR_MC19_CTL = 0x44C ,
MSR_MC19_STATUS = 0x44D , MSR_MC19_ADDR = 0x44E , MSR_MC19_MISC = 0x44F , MSR_MC20_CTL = 0x450 ,
MSR_MC20_STATUS = 0x451 , MSR_MC20_ADDR = 0x452 , MSR_MC20_MISC = 0x453 , MSR_MC21_CTL = 0x454 ,
MSR_MC21_STATUS = 0x455 , MSR_MC21_ADDR = 0x456 , MSR_MC21_MISC = 0x457 , MSR_MC22_CTL = 0x458 ,
MSR_MC22_STATUS = 0x459 , MSR_MC22_ADDR = 0x45A , MSR_MC22_MISC = 0x45B , MSR_MC23_CTL = 0x45C ,
MSR_MC23_STATUS = 0x45D , MSR_MC23_ADDR = 0x45E , MSR_MC23_MISC = 0x45F , MSR_MC24_CTL = 0x460 ,
MSR_MC24_STATUS = 0x461 , MSR_MC24_ADDR = 0x462 , MSR_MC24_MISC = 0x463 , MSR_MC25_CTL = 0x464 ,
MSR_MC25_STATUS = 0x465 , MSR_MC25_ADDR = 0x466 , MSR_MC25_MISC = 0x467 , MSR_MC26_CTL = 0x468 ,
MSR_MC26_STATUS = 0x469 , MSR_MC26_ADDR = 0x46A , MSR_MC26_MISC = 0x46B , MSR_MC27_CTL = 0x46C ,
MSR_MC27_STATUS = 0x46D , MSR_MC27_ADDR = 0x46E , MSR_MC27_MISC = 0x46F , MSR_MC28_CTL = 0x470 ,
MSR_MC28_STATUS = 0x471 , MSR_MC28_ADDR = 0x472 , MSR_MC28_MISC = 0x473 , MSR_VMX_BASIC = 0x480 ,
MSR_VMX_PINBASED_CTLS = 0x481 , MSR_VMX_PROCBASED_CTLS = 0x482 , MSR_VMX_EXIT_CTLS = 0x483 , MSR_VMX_ENTRY_CTLS = 0x484 ,
MSR_VMX_MISC = 0x485 , MSR_VMX_CR0_FIXED0 = 0x486 , MSR_VMX_CR0_FIXED1 = 0x487 , MSR_VMX_CR4_FIXED0 = 0x488 ,
MSR_VMX_CR4_FIXED1 = 0x489 , MSR_VMX_VMCS_ENUM = 0x48A , MSR_VMX_PROCBASED_CTLS2 = 0x48B , MSR_VMX_EPT_VPID_CAP = 0x48C ,
MSR_VMX_TRUE_PINBASED_CTLS = 0x48D , MSR_VMX_TRUE_PROCBASED_CTLS = 0x48E , MSR_VMX_TRUE_EXIT_CTLS = 0x48F , MSR_VMX_TRUE_ENTRY_CTLS = 0x490 ,
MSR_VMX_VMFUNC = 0x491 , MSR_A_PMC0 = 0x4C1 , MSR_A_PMC1 = 0x4C2 , MSR_A_PMC2 = 0x4C3 ,
MSR_A_PMC3 = 0x4C4 , MSR_A_PMC4 = 0x4C5 , MSR_A_PMC5 = 0x4C6 , MSR_A_PMC6 = 0x4C7 ,
MSR_A_PMC7 = 0x4C8 , MSR_MCG_EXT_CTL = 0x4D0 , MSR_SGX_SVN_STATUS = 0x500 , MSR_RTIT_OUTPUT_BASE = 0x560 ,
MSR_RTIT_OUTPUT_MASK_PTRS = 0x561 , MSR_RTIT_CTL = 0x570 , MSR_RTIT_STATUS = 0x571 , MSR_RTIT_CR3_MATCH = 0x572 ,
MSR_RTIT_ADDR0_A = 0x580 , MSR_RTIT_ADDR0_B = 0x581 , MSR_RTIT_ADDR1_A = 0x582 , MSR_RTIT_ADDR1_B = 0x583 ,
MSR_RTIT_ADDR2_A = 0x584 , MSR_RTIT_ADDR2_B = 0x585 , MSR_RTIT_ADDR3_A = 0x586 , MSR_RTIT_ADDR3_B = 0x587 ,
MSR_DS_AREA = 0x600 , MSR_TSC_DEADLINE = 0x6E0 , MSR_PM_ENABLE = 0x770 , MSR_HWP_CAPABILITIES = 0x771 ,
MSR_HWP_REQUEST_PKG = 0x772 , MSR_HWP_INTERRUPT = 0x773 , MSR_HWP_REQUEST = 0x774 , MSR_HWP_STATUS = 0x777 ,
MSR_X2APIC_APICID = 0x802 , MSR_X2APIC_VERSION = 0x803 , MSR_X2APIC_TPR = 0x808 , MSR_X2APIC_PPR = 0x80A ,
MSR_X2APIC_EOI = 0x80B , MSR_X2APIC_LDR = 0x80D , MSR_X2APIC_SIVR = 0x80F , MSR_X2APIC_ISR0 = 0x810 ,
MSR_X2APIC_ISR1 = 0x811 , MSR_X2APIC_ISR2 = 0x812 , MSR_X2APIC_ISR3 = 0x813 , MSR_X2APIC_ISR4 = 0x814 ,
MSR_X2APIC_ISR5 = 0x815 , MSR_X2APIC_ISR6 = 0x816 , MSR_X2APIC_ISR7 = 0x817 , MSR_X2APIC_TMR0 = 0x818 ,
MSR_X2APIC_TMR1 = 0x819 , MSR_X2APIC_TMR2 = 0x81A , MSR_X2APIC_TMR3 = 0x81B , MSR_X2APIC_TMR4 = 0x81C ,
MSR_X2APIC_TMR5 = 0x81D , MSR_X2APIC_TMR6 = 0x81E , MSR_X2APIC_TMR7 = 0x81F , MSR_X2APIC_IRR0 = 0x820 ,
MSR_X2APIC_IRR1 = 0x821 , MSR_X2APIC_IRR2 = 0x822 , MSR_X2APIC_IRR3 = 0x823 , MSR_X2APIC_IRR4 = 0x824 ,
MSR_X2APIC_IRR5 = 0x825 , MSR_X2APIC_IRR6 = 0x826 , MSR_X2APIC_IRR7 = 0x827 , MSR_X2APIC_ESR = 0x828 ,
MSR_X2APIC_LVT_CMCI = 0x82F , MSR_X2APIC_ICR = 0x830 , MSR_X2APIC_LVT_TIMER = 0x832 , MSR_X2APIC_LVT_THERMAL = 0x833 ,
MSR_X2APIC_LVT_PMI = 0x834 , MSR_X2APIC_LVT_LINT0 = 0x835 , MSR_X2APIC_LVT_LINT1 = 0x836 , MSR_X2APIC_LVT_ERROR = 0x837 ,
MSR_X2APIC_INIT_COUNT = 0x838 , MSR_X2APIC_CUR_COUNT = 0x839 , MSR_X2APIC_DIV_CONF = 0x83E , MSR_X2APIC_SELF_IPI = 0x83F ,
MSR_DEBUG_INTERFACE = 0xC80 , MSR_L3_QOS_CFG = 0xC81 , MSR_L2_QOS_CFG = 0xC82 , MSR_QM_EVTSEL = 0xC8D ,
MSR_QM_CTR = 0xC8E , MSR_PQR_ASSOC = 0xC8F , MSR_L3_MASK_0 = 0xC90 , MSR_L2_MASK_0 = 0xD10 ,
MSR_BNDCFGS = 0xD90 , MSR_XSS = 0xDA0 , MSR_PKG_HDC_CTL = 0xDB0 , MSR_PM_CTL1 = 0xDB1 ,
MSR_THREAD_STALL = 0xDB2 , MSR_EFER = 0xC0000080 , MSR_STAR = 0xC0000081 , MSR_LSTAR = 0xC0000082 ,
MSR_CSTAR = 0xC0000083 , MSR_SYSCALL_MASK = 0xC0000084 , MSR_FS_BASE = 0xC0000100 , MSR_GS_BASE = 0xC0000101 ,
MSR_SHADOW_GS_BASE = 0xC0000102 , MSR_TSC_AUX = 0xC0000103 , MSR_CR_PAT = 0x00000277 , MSR_CR_PAT_RESET = 0x0007040600070406ULL
}
enum ISRExceptions {
DivideByZero = 0x0 , Debug = 0x1 , NonMaskableInterrupt = 0x2 , Breakpoint = 0x3 ,
Overflow = 0x4 , BoundRange = 0x5 , InvalidOpcode = 0x6 , DeviceNotAvailable = 0x7 ,
DoubleFault = 0x8 , CoprocessorSegmentOverrun = 0x9 , InvalidTSS = 0xa , SegmentNotPresent = 0xb ,
StackSegmentFault = 0xc , GeneralProtectionFault = 0xd , PageFault = 0xe , x87FloatingPoint = 0x10 ,
AlignmentCheck = 0x11 , MachineCheck = 0x12 , SIMDFloatingPoint = 0x13 , Virtualization = 0x14 ,
Security = 0x1e
}
enum CPUInterrupts {
ISR0 = 0x0 , ISR1 = 0x1 , ISR2 = 0x2 , ISR3 = 0x3 ,
ISR4 = 0x4 , ISR5 = 0x5 , ISR6 = 0x6 , ISR7 = 0x7 ,
ISR8 = 0x8 , ISR9 = 0x9 , ISR10 = 0xa , ISR11 = 0xb ,
ISR12 = 0xc , ISR13 = 0xd , ISR14 = 0xe , ISR15 = 0xf ,
ISR16 = 0x10 , ISR17 = 0x11 , ISR18 = 0x12 , ISR19 = 0x13 ,
ISR20 = 0x14 , ISR21 = 0x15 , ISR22 = 0x16 , ISR23 = 0x17 ,
ISR24 = 0x18 , ISR25 = 0x19 , ISR26 = 0x1a , ISR27 = 0x1b ,
ISR28 = 0x1c , ISR29 = 0x1d , ISR30 = 0x1e , ISR31 = 0x1f ,
IRQ0 = 0x20 , IRQ1 = 0x21 , IRQ2 = 0x22 , IRQ3 = 0x23 ,
IRQ4 = 0x24 , IRQ5 = 0x25 , IRQ6 = 0x26 , IRQ7 = 0x27 ,
IRQ8 = 0x28 , IRQ9 = 0x29 , IRQ10 = 0x2a , IRQ11 = 0x2b ,
IRQ12 = 0x2c , IRQ13 = 0x2d , IRQ14 = 0x2e , IRQ15 = 0x2f ,
IRQ16 = 0x30 , IRQ17 = 0x31 , IRQ18 = 0x32 , IRQ19 = 0x33 ,
IRQ20 = 0x34 , IRQ21 = 0x35 , IRQ22 = 0x36 , IRQ23 = 0x37 ,
IRQ24 = 0x38 , IRQ25 = 0x39 , IRQ26 = 0x3a , IRQ27 = 0x3b ,
IRQ28 = 0x3c , IRQ29 = 0x3d , IRQ30 = 0x3e , IRQ31 = 0x3f ,
IRQ32 = 0x40 , IRQ33 = 0x41 , IRQ34 = 0x42 , IRQ35 = 0x43 ,
IRQ36 = 0x44 , IRQ37 = 0x45 , IRQ38 = 0x46 , IRQ39 = 0x47 ,
IRQ40 = 0x48 , IRQ41 = 0x49 , IRQ42 = 0x4a , IRQ43 = 0x4b ,
IRQ44 = 0x4c , IRQ45 = 0x4d , IRQ46 = 0x4e , IRQ47 = 0x4f ,
IRQ48 = 0x50 , IRQ49 = 0x51 , IRQ50 = 0x52 , IRQ51 = 0x53 ,
IRQ52 = 0x54 , IRQ53 = 0x55 , IRQ54 = 0x56 , IRQ55 = 0x57 ,
IRQ56 = 0x58 , IRQ57 = 0x59 , IRQ58 = 0x5a , IRQ59 = 0x5b ,
IRQ60 = 0x5c , IRQ61 = 0x5d , IRQ62 = 0x5e , IRQ63 = 0x5f ,
IRQ64 = 0x60 , IRQ65 = 0x61 , IRQ66 = 0x62 , IRQ67 = 0x63 ,
IRQ68 = 0x64 , IRQ69 = 0x65 , IRQ70 = 0x66 , IRQ71 = 0x67 ,
IRQ72 = 0x68 , IRQ73 = 0x69 , IRQ74 = 0x6a , IRQ75 = 0x6b ,
IRQ76 = 0x6c , IRQ77 = 0x6d , IRQ78 = 0x6e , IRQ79 = 0x6f ,
IRQ80 = 0x70 , IRQ81 = 0x71 , IRQ82 = 0x72 , IRQ83 = 0x73 ,
IRQ84 = 0x74 , IRQ85 = 0x75 , IRQ86 = 0x76 , IRQ87 = 0x77 ,
IRQ88 = 0x78 , IRQ89 = 0x79 , IRQ90 = 0x7a , IRQ91 = 0x7b ,
IRQ92 = 0x7c , IRQ93 = 0x7d , IRQ94 = 0x7e , IRQ95 = 0x7f ,
IRQ96 = 0x80 , IRQ97 = 0x81 , IRQ98 = 0x82 , IRQ99 = 0x83 ,
IRQ100 = 0x84 , IRQ101 = 0x85 , IRQ102 = 0x86 , IRQ103 = 0x87 ,
IRQ104 = 0x88 , IRQ105 = 0x89 , IRQ106 = 0x8a , IRQ107 = 0x8b ,
IRQ108 = 0x8c , IRQ109 = 0x8d , IRQ110 = 0x8e , IRQ111 = 0x8f ,
IRQ112 = 0x90 , IRQ113 = 0x91 , IRQ114 = 0x92 , IRQ115 = 0x93 ,
IRQ116 = 0x94 , IRQ117 = 0x95 , IRQ118 = 0x96 , IRQ119 = 0x97 ,
IRQ120 = 0x98 , IRQ121 = 0x99 , IRQ122 = 0x9a , IRQ123 = 0x9b ,
IRQ124 = 0x9c , IRQ125 = 0x9d , IRQ126 = 0x9e , IRQ127 = 0x9f ,
IRQ128 = 0xa0 , IRQ129 = 0xa1 , IRQ130 = 0xa2 , IRQ131 = 0xa3 ,
IRQ132 = 0xa4 , IRQ133 = 0xa5 , IRQ134 = 0xa6 , IRQ135 = 0xa7 ,
IRQ136 = 0xa8 , IRQ137 = 0xa9 , IRQ138 = 0xaa , IRQ139 = 0xab ,
IRQ140 = 0xac , IRQ141 = 0xad , IRQ142 = 0xae , IRQ143 = 0xaf ,
IRQ144 = 0xb0 , IRQ145 = 0xb1 , IRQ146 = 0xb2 , IRQ147 = 0xb3 ,
IRQ148 = 0xb4 , IRQ149 = 0xb5 , IRQ150 = 0xb6 , IRQ151 = 0xb7 ,
IRQ152 = 0xb8 , IRQ153 = 0xb9 , IRQ154 = 0xba , IRQ155 = 0xbb ,
IRQ156 = 0xbc , IRQ157 = 0xbd , IRQ158 = 0xbe , IRQ159 = 0xbf ,
IRQ160 = 0xc0 , IRQ161 = 0xc1 , IRQ162 = 0xc2 , IRQ163 = 0xc3 ,
IRQ164 = 0xc4 , IRQ165 = 0xc5 , IRQ166 = 0xc6 , IRQ167 = 0xc7 ,
IRQ168 = 0xc8 , IRQ169 = 0xc9 , IRQ170 = 0xca , IRQ171 = 0xcb ,
IRQ172 = 0xcc , IRQ173 = 0xcd , IRQ174 = 0xce , IRQ175 = 0xcf ,
IRQ176 = 0xd0 , IRQ177 = 0xd1 , IRQ178 = 0xd2 , IRQ179 = 0xd3 ,
IRQ180 = 0xd4 , IRQ181 = 0xd5 , IRQ182 = 0xd6 , IRQ183 = 0xd7 ,
IRQ184 = 0xd8 , IRQ185 = 0xd9 , IRQ186 = 0xda , IRQ187 = 0xdb ,
IRQ188 = 0xdc , IRQ189 = 0xdd , IRQ190 = 0xde , IRQ191 = 0xdf ,
IRQ192 = 0xe0 , IRQ193 = 0xe1 , IRQ194 = 0xe2 , IRQ195 = 0xe3 ,
IRQ196 = 0xe4 , IRQ197 = 0xe5 , IRQ198 = 0xe6 , IRQ199 = 0xe7 ,
IRQ200 = 0xe8 , IRQ201 = 0xe9 , IRQ202 = 0xea , IRQ203 = 0xeb ,
IRQ204 = 0xec , IRQ205 = 0xed , IRQ206 = 0xee , IRQ207 = 0xef ,
IRQ208 = 0xf0 , IRQ209 = 0xf1 , IRQ210 = 0xf2 , IRQ211 = 0xf3 ,
IRQ212 = 0xf4 , IRQ213 = 0xf5 , IRQ214 = 0xf6 , IRQ215 = 0xf7 ,
IRQ216 = 0xf8 , IRQ217 = 0xf9 , IRQ218 = 0xfa , IRQ219 = 0xfb ,
IRQ220 = 0xfc , IRQ221 = 0xfd , IRQ222 = 0xfe , IRQ223 = 0xff
}
Functions
union CPU::x64::EFER __attribute__ ((packed)) EFER
static SafeFunction void lgdt (void *gdt)
static SafeFunction void lidt (void *idt)
static SafeFunction void ltr (uint16_t Segment)
static SafeFunction void invlpg (void *Address)
static SafeFunction void cpuid (uint32_t Function, uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
CPUID.
static SafeFunction uint32_t GetHighestLeaf ()
static SafeFunction uint64_t rdmsr (uint32_t msr)
static SafeFunction void wrmsr (uint32_t msr, uint64_t Value)
static SafeFunction CR0 readcr0 ()
static SafeFunction CR2 readcr2 ()
static SafeFunction CR3 readcr3 ()
static SafeFunction CR4 readcr4 ()
static SafeFunction CR8 readcr8 ()
static SafeFunction XCR0 readxcr0 ()
static SafeFunction void writecr0 (CR0 ControlRegister)
static SafeFunction void writecr2 (CR2 ControlRegister)
static SafeFunction void writecr3 (CR3 ControlRegister)
static SafeFunction void writecr4 (CR4 ControlRegister)
static SafeFunction void writecr8 (CR8 ControlRegister)
static SafeFunction void writexcr0 (XCR0 ControlRegister)
static SafeFunction void fxsave (void *FXSaveArea)
static SafeFunction void fxrstor (void *FXRstorArea)
Data Structure Documentation
CPU::x64::__attribute__
union CPU::x64::__attribute__
MSR_APIC_BASE structure.
See also
MSR_APIC_BASE
Definition at line 2868 of file cpu.hpp.
Data Fields
struct __attribute__ __attribute__
uint64_t raw
CPU::x64::RFLAGS
union CPU::x64::RFLAGS
Definition at line 2893 of file cpu.hpp.
Data Fields
struct RFLAGS __unnamed__
uint64_t raw
CPU::x64::TrapFrame
struct CPU::x64::TrapFrame
Definition at line 2945 of file cpu.hpp.
Data Fields
uint64_t cs
uint64_t ErrorCode
uint64_t InterruptNumber
uint64_t r10
uint64_t r11
uint64_t r12
uint64_t r13
uint64_t r14
uint64_t r15
uint64_t r8
uint64_t r9
uint64_t rax
uint64_t rbp
uint64_t rbx
uint64_t rcx
uint64_t rdi
uint64_t rdx
RFLAGS rflags
uint64_t rip
uint64_t rsi
uint64_t rsp
uint64_t ss
CPU::x64::CR0
union CPU::x64::CR0
Definition at line 2973 of file cpu.hpp.
Data Fields
struct CR0 __unnamed__
uint64_t raw
CPU::x64::CR2
union CPU::x64::CR2
Definition at line 3009 of file cpu.hpp.
Data Fields
struct CR2 __unnamed__
uint64_t raw
CPU::x64::CR3
union CPU::x64::CR3
Definition at line 3019 of file cpu.hpp.
Data Fields
struct CR3 __unnamed__
uint64_t raw
CPU::x64::CR4
union CPU::x64::CR4
Definition at line 3033 of file cpu.hpp.
Data Fields
struct CR4 __unnamed__
uint64_t raw
CPU::x64::CR8
union CPU::x64::CR8
Definition at line 3093 of file cpu.hpp.
Data Fields
struct CR8 __unnamed__
uint64_t raw
CPU::x64::XCR0
union CPU::x64::XCR0
Definition at line 3103 of file cpu.hpp.
Data Fields
struct XCR0 __unnamed__
uint64_t raw
CPU::x64::EFER
union CPU::x64::EFER
Definition at line 3138 of file cpu.hpp.
Data Fields
struct EFER __unnamed__
uint64_t raw
CPU::x64::DR7
union CPU::x64::DR7
Definition at line 3169 of file cpu.hpp.
Data Fields
struct DR7 __unnamed__
uint64_t raw
CPU::x64::PageFaultErrorCode
union CPU::x64::PageFaultErrorCode
Definition at line 3211 of file cpu.hpp.
Data Fields
struct PageFaultErrorCode __unnamed__
uint64_t raw
CPU::x64::SelectorErrorCode
union CPU::x64::SelectorErrorCode
Definition at line 3240 of file cpu.hpp.
Data Fields
struct SelectorErrorCode __unnamed__
uint64_t raw
CPU::x64::FXState
struct CPU::x64::FXState
Definition at line 3261 of file cpu.hpp.
Data Fields
uint16_t fcw FPU control word.
uint16_t fop FPU opcode.
uint16_t fsw FPU status word.
uint8_t ftw FPU tag words.
uint32_t mxcsr SSE control register.
uint32_t mxcsrmask SSE control register mask.
uint64_t rdp FPU data pointer.
uint8_t Reserved Reserved (zero)
uint64_t rip PFU instruction pointer.
uint8_t st[8][16] FPU registers (last 6 bytes reserved)
uint8_t xmm[16][16] XMM registers.
CPU::x64::__attribute__.__attribute__
struct CPU::x64::__attribute__.__attribute__
Definition at line 2870 of file cpu.hpp.
Data Fields
uint32_t ApicBaseHi: 32 APIC Base High Address.
uint32_t ApicBaseLo: 20 APIC Base Low Address.
uint32_t BSP: 1 BSP Flag.
If the BSP flag is set to 1, the processor is the bootstrap processor.
uint32_t EN: 1 APIC Global Enable.
uint32_t EXTD: 1 Enable x2APIC mode.
uint32_t Reserved0: 8 Reserved.
uint32_t Reserved1: 1 Reserved.
CPU::x64::RFLAGS.__unnamed464__
struct CPU::x64::RFLAGS.__unnamed464__
Definition at line 2895 of file cpu.hpp.
Data Fields
uint64_t AC: 1 Alignment Check.
uint64_t AF: 1 Auxiliary Carry Flag.
uint64_t AlwaysOne: 1 Reserved.
uint64_t CF: 1 Carry Flag.
uint64_t DF: 1 Direction Flag.
uint64_t ID: 1 ID Flag.
uint64_t IF: 1 Interrupt Enable Flag.
uint64_t IOPL: 2 I/O Privilege Level.
uint64_t NT: 1 Nested Task.
uint64_t OF: 1 Overflow Flag.
uint64_t PF: 1 Parity Flag.
uint64_t Reserved0: 1 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 1 Reserved.
uint64_t Reserved3: 10 Reserved.
uint64_t RF: 1 Resume Flag.
uint64_t SF: 1 Sign Flag.
uint64_t TF: 1 Trap Flag.
uint64_t VIF: 1 Virtual Interrupt Flag.
uint64_t VIP: 1 Virtual Interrupt Pending.
uint64_t VM: 1 Virtual 8086 Mode.
uint64_t ZF: 1 Zero Flag.
CPU::x64::CR0.__unnamed466__
struct CPU::x64::CR0.__unnamed466__
Definition at line 2975 of file cpu.hpp.
Data Fields
uint64_t AM: 1 Alignment Mask.
uint64_t CD: 1 Cache Disable.
uint64_t EM: 1 Emulation.
uint64_t ET: 1 Extension Type.
uint64_t MP: 1 Monitor Coprocessor.
uint64_t NE: 1 Numeric Error.
uint64_t NW: 1 Not Write-through.
uint64_t PE: 1 Protection Enable.
uint64_t PG: 1 Paging.
uint64_t Reserved0: 10 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 10 Reserved.
uint64_t TS: 1 Task Switched.
uint64_t WP: 1 Write Protect.
CPU::x64::CR2.__unnamed468__
struct CPU::x64::CR2.__unnamed468__
Definition at line 3011 of file cpu.hpp.
Data Fields
uint64_t PFLA Page Fault Linear Address.
CPU::x64::CR3.__unnamed470__
struct CPU::x64::CR3.__unnamed470__
Definition at line 3021 of file cpu.hpp.
Data Fields
uint64_t PCD: 1 Not used if bit 17 of CR4 is 1.
uint64_t PDBR Base of PML4T/PML5T.
uint64_t PWT: 1 Not used if bit 17 of CR4 is 1.
CPU::x64::CR4.__unnamed472__
struct CPU::x64::CR4.__unnamed472__
Definition at line 3035 of file cpu.hpp.
Data Fields
uint32_t CET: 1 Control-flow Enforcement Technology.
uint64_t DE: 1 Debugging Extensions.
uint64_t FSGSBASE: 1 FSGSBASE Enable.
uint64_t LA57: 1 Linear Address 57bit.
uint64_t MCE: 1 Machine Check Enable.
uint64_t OSFXSR: 1 Operating System Support.
uint64_t OSXMMEXCPT: 1 Operating System Support.
uint64_t OSXSAVE: 1 XSAVE and Processor Extended States Enable.
uint64_t PAE: 1 Physical Address Extension.
uint64_t PCE: 1 Performance Monitoring Counter.
uint64_t PCIDE: 1 PCID Enable.
uint64_t PGE: 1 Page Global Enable.
uint64_t PKE: 1 Protection-Key Enable.
uint32_t PKS: 1
uint64_t PSE: 1 Page Size Extensions.
uint64_t PVI: 1 Protected-Mode Virtual Interrupts.
uint64_t Reserved0: 1 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 7 Reserved.
uint64_t SMAP: 1 SMAP Enable.
uint64_t SMEP: 1 SMEP Enable.
uint64_t SMXE: 1 SMX Enable.
uint64_t TSD: 1 Time Stamp Disable.
uint64_t UMIP: 1 User-Mode Instruction Prevention.
uint64_t VME: 1 Virtual-8086 Mode Extensions.
uint64_t VMXE: 1 VMX Enable.
CPU::x64::CR8.__unnamed474__
struct CPU::x64::CR8.__unnamed474__
Definition at line 3095 of file cpu.hpp.
Data Fields
uint64_t TPL: 1 Task Priority Level.
CPU::x64::XCR0.__unnamed476__
struct CPU::x64::XCR0.__unnamed476__
Definition at line 3108 of file cpu.hpp.
Data Fields
uint64_t AVX: 1 AVX support for YMM registers.
uint64_t BNDCSR: 1 MPX support for BNDCFGU and BNDSTATUS registers.
uint64_t BNDREG: 1 MPX support for BND registers.
uint64_t HI16_ZMM: 1 AVX-512 enabled and XSAVE support for upper ZMM registers.
uint64_t LWP: 1 AMD lightweight profiling.
uint64_t OpMask: 1 AVX-512 support for opmask registers.
uint64_t PKRU: 1 XSAVE support for PKRU register.
uint64_t Reserved0: 53 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t SSE: 1 XSAVE support for MXCSR and XMM registers.
uint64_t X87: 1 X87 FPU/MMX/SSE Support (must be 1)
uint64_t ZMM_HI256: 1 AVX-512 enabled and XSAVE support for upper halves of lower ZMM registers.
CPU::x64::EFER.__unnamed478__
struct CPU::x64::EFER.__unnamed478__
Definition at line 3140 of file cpu.hpp.
Data Fields
uint64_t FFXSR: 1 Enable Fast FXSAVE/FXRSTOR.
uint64_t LMA: 1 Indicates long.
uint64_t LME: 1 Enable long mode.
uint64_t LMSLE: 1 Enable Long Mode Segment Limit.
uint64_t NXE: 1 Enable No-Execute Bit.
uint64_t Reserved0: 7 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 32 Reserved.
uint64_t SCE: 1 Enable syscall & sysret instructions in 64-bit mode.
uint64_t SVME: 1 Enable Secure Virtual Machine.
uint64_t TCE: 1 Enable Translation Cache Extension.
CPU::x64::DR7.__unnamed482__
struct CPU::x64::DR7.__unnamed482__
Definition at line 3171 of file cpu.hpp.
Data Fields
uint64_t ConditionsDR0: 1 Conditions for DR0 (16-17)
uint64_t ConditionsDR1: 1 Conditions for DR1 (20-21)
uint64_t ConditionsDR2: 1 Conditions for DR2 (24-25)
uint64_t ConditionsDR3: 1 Conditions for DR3 (28-29)
uint64_t GlobalDR0: 1 Global DR0 Breakpoint (1)
uint64_t GlobalDR1: 1 Global DR1 Breakpoint (3)
uint64_t GlobalDR2: 1 Global DR2 Breakpoint (5)
uint64_t GlobalDR3: 1 Global DR3 Breakpoint (7)
uint64_t LocalDR0: 1 Local DR0 Breakpoint (0)
uint64_t LocalDR1: 1 Local DR1 Breakpoint (2)
uint64_t LocalDR2: 1 Local DR2 Breakpoint (4)
uint64_t LocalDR3: 1 Local DR3 Breakpoint (6)
uint64_t Reserved: 9 Reserved [7 - (16-17)].
uint64_t SizeDR0: 1 Size of DR0 Breakpoint (18-19)
uint64_t SizeDR1: 1 Size of DR1 Breakpoint (22-23)
uint64_t SizeDR2: 1 Size of DR2 Breakpoint (26-27)
uint64_t SizeDR3: 1 Size of DR3 Breakpoint (30-31)
CPU::x64::PageFaultErrorCode.__unnamed484__
struct CPU::x64::PageFaultErrorCode.__unnamed484__
Definition at line 3213 of file cpu.hpp.
Data Fields
uint64_t I: 1 When set, the page fault was caused by an instruction fetch. This only applies when the No-Execute bit is supported and enabled.
uint64_t P: 1 When set, the page fault was caused by a page-protection violation. When not set, it was caused by a non-present page.
uint64_t PK: 1 When set, the page fault was caused by a protection-key violation. The PKRU register (for user-mode accesses) or PKRS MSR (for supervisor-mode accesses) specifies the protection key rights.
uint64_t R: 1 When set, one or more page directory entries contain reserved bits which are set to 1. This only applies when the PSE or PAE flags in CR4 are set to 1.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 16 Reserved.
uint64_t SGX: 1 When set, the fault was due to an SGX violation. The fault is unrelated to ordinary paging.
uint64_t SS: 1 When set, the page fault was caused by a shadow stack access.
uint64_t U: 1 When set, the page fault was caused while CPL = 3. This does not necessarily mean that the page fault was a privilege violation.
uint64_t W: 1 When set, the page fault was caused by a write access. When not set, it was caused by a read access.
CPU::x64::SelectorErrorCode.__unnamed486__
struct CPU::x64::SelectorErrorCode.__unnamed486__
Definition at line 3242 of file cpu.hpp.
Data Fields
uint64_t External: 1 When set, the exception originated externally to the processor.
uint64_t Idx: 13 The index in the GDT, IDT or LDT.
uint64_t Reserved: 16 Reserved.
uint64_t Table: 2 IDT/GDT/LDT Table.
0b00 - The Selector Index references a descriptor in the GDT.
0b01 - The Selector Index references a descriptor in the IDT.
0b10 - The Selector Index references a descriptor in the LDT.
0b11 - The Selector Index references a descriptor in the IDT.
Typedef Documentation
CR0
typedef union CPU::x64::CR0 CPU::x64::CR0
CR2
typedef union CPU::x64::CR2 CPU::x64::CR2
CR3
typedef union CPU::x64::CR3 CPU::x64::CR3
CR4
typedef union CPU::x64::CR4 CPU::x64::CR4
CR8
typedef union CPU::x64::CR8 CPU::x64::CR8
DR7
typedef union CPU::x64::DR7 CPU::x64::DR7
PageFaultErrorCode
typedef union CPU::x64::PageFaultErrorCode CPU::x64::PageFaultErrorCode
SelectorErrorCode
typedef union CPU::x64::SelectorErrorCode CPU::x64::SelectorErrorCode
TrapFrame
typedef struct CPU::x64::TrapFrame CPU::x64::TrapFrame
XCR0
typedef union CPU::x64::XCR0 CPU::x64::XCR0
Enumeration Type Documentation
CPUInterrupts
enum CPU::x64::CPUInterrupts
Enumerator
ISR0
ISR1
ISR2
ISR3
ISR4
ISR5
ISR6
ISR7
ISR8
ISR9
ISR10
ISR11
ISR12
ISR13
ISR14
ISR15
ISR16
ISR17
ISR18
ISR19
ISR20
ISR21
ISR22
ISR23
ISR24
ISR25
ISR26
ISR27
ISR28
ISR29
ISR30
ISR31
IRQ0
IRQ1
IRQ2
IRQ3
IRQ4
IRQ5
IRQ6
IRQ7
IRQ8
IRQ9
IRQ10
IRQ11
IRQ12
IRQ13
IRQ14
IRQ15
IRQ16
IRQ17
IRQ18
IRQ19
IRQ20
IRQ21
IRQ22
IRQ23
IRQ24
IRQ25
IRQ26
IRQ27
IRQ28
IRQ29
IRQ30
IRQ31
IRQ32
IRQ33
IRQ34
IRQ35
IRQ36
IRQ37
IRQ38
IRQ39
IRQ40
IRQ41
IRQ42
IRQ43
IRQ44
IRQ45
IRQ46
IRQ47
IRQ48
IRQ49
IRQ50
IRQ51
IRQ52
IRQ53
IRQ54
IRQ55
IRQ56
IRQ57
IRQ58
IRQ59
IRQ60
IRQ61
IRQ62
IRQ63
IRQ64
IRQ65
IRQ66
IRQ67
IRQ68
IRQ69
IRQ70
IRQ71
IRQ72
IRQ73
IRQ74
IRQ75
IRQ76
IRQ77
IRQ78
IRQ79
IRQ80
IRQ81
IRQ82
IRQ83
IRQ84
IRQ85
IRQ86
IRQ87
IRQ88
IRQ89
IRQ90
IRQ91
IRQ92
IRQ93
IRQ94
IRQ95
IRQ96
IRQ97
IRQ98
IRQ99
IRQ100
IRQ101
IRQ102
IRQ103
IRQ104
IRQ105
IRQ106
IRQ107
IRQ108
IRQ109
IRQ110
IRQ111
IRQ112
IRQ113
IRQ114
IRQ115
IRQ116
IRQ117
IRQ118
IRQ119
IRQ120
IRQ121
IRQ122
IRQ123
IRQ124
IRQ125
IRQ126
IRQ127
IRQ128
IRQ129
IRQ130
IRQ131
IRQ132
IRQ133
IRQ134
IRQ135
IRQ136
IRQ137
IRQ138
IRQ139
IRQ140
IRQ141
IRQ142
IRQ143
IRQ144
IRQ145
IRQ146
IRQ147
IRQ148
IRQ149
IRQ150
IRQ151
IRQ152
IRQ153
IRQ154
IRQ155
IRQ156
IRQ157
IRQ158
IRQ159
IRQ160
IRQ161
IRQ162
IRQ163
IRQ164
IRQ165
IRQ166
IRQ167
IRQ168
IRQ169
IRQ170
IRQ171
IRQ172
IRQ173
IRQ174
IRQ175
IRQ176
IRQ177
IRQ178
IRQ179
IRQ180
IRQ181
IRQ182
IRQ183
IRQ184
IRQ185
IRQ186
IRQ187
IRQ188
IRQ189
IRQ190
IRQ191
IRQ192
IRQ193
IRQ194
IRQ195
IRQ196
IRQ197
IRQ198
IRQ199
IRQ200
IRQ201
IRQ202
IRQ203
IRQ204
IRQ205
IRQ206
IRQ207
IRQ208
IRQ209
IRQ210
IRQ211
IRQ212
IRQ213
IRQ214
IRQ215
IRQ216
IRQ217
IRQ218
IRQ219
IRQ220
IRQ221
IRQ222
IRQ223
Definition at line 2593 of file cpu.hpp.
         {
             /* ISR */
             ISR0 = 0x0,   // Divide-by-zero Error
             ISR1 = 0x1,   // Debug
             ISR2 = 0x2,   // Non-maskable Interrupt
             ISR3 = 0x3,   // Breakpoint
             ISR4 = 0x4,   // Overflow
             ISR5 = 0x5,   // Bound Range Exceeded
             ISR6 = 0x6,   // Invalid Opcode
             ISR7 = 0x7,   // Device Not Available
             ISR8 = 0x8,   // Double Fault
             ISR9 = 0x9,   // Coprocessor Segment Overrun
             ISR10 = 0xa,  // Invalid TSS
             ISR11 = 0xb,  // Segment Not P
             ISR12 = 0xc,  // Stack-Segment Fault
             ISR13 = 0xd,  // General Protection Fault
             ISR14 = 0xe,  // Page Fault
             ISR15 = 0xf,  // Reserved
             ISR16 = 0x10, // x87 Floating-Point Exception
             ISR17 = 0x11, // Alignment Check
             ISR18 = 0x12, // Machine Check
             ISR19 = 0x13, // SIMD Floating-Point Exception
             ISR20 = 0x14, // Virtualization Exception
             ISR21 = 0x15, // Reserved
             ISR22 = 0x16, // Reserved
             ISR23 = 0x17, // Reserved
             ISR24 = 0x18, // Reserved
             ISR25 = 0x19, // Reserved
             ISR26 = 0x1a, // Reserved
             ISR27 = 0x1b, // Reserved
             ISR28 = 0x1c, // Reserved
             ISR29 = 0x1d, // Reserved
             ISR30 = 0x1e, // Security Exception
             ISR31 = 0x1f, // Reserved
             /* IRQ */
             IRQ0 = 0x20,  // Programmable Interrupt Timer Interrupt
             IRQ1 = 0x21,  // Keyboard Interrupt
             IRQ2 = 0x22,  // Cascade (used internally by the two PICs. never raised)
             IRQ3 = 0x23,  // COM2 (if enabled)
             IRQ4 = 0x24,  // COM1 (if enabled)
             IRQ5 = 0x25,  // LPT2 (if enabled)
             IRQ6 = 0x26,  // Floppy Disk
             IRQ7 = 0x27,  // LPT1 / Unreliable "spurious" interrupt (usually)
             IRQ8 = 0x28,  // CMOS real-time clock (if enabled)
             IRQ9 = 0x29,  // Free for peripherals / legacy SCSI / NIC
             IRQ10 = 0x2a, // Free for peripherals / SCSI / NIC
             IRQ11 = 0x2b, // Free for peripherals / SCSI / NIC
             IRQ12 = 0x2c, // PS2 Mouse
             IRQ13 = 0x2d, // FPU / Coprocessor / Inter-processor
             IRQ14 = 0x2e, // Primary ATA Hard Disk
             IRQ15 = 0x2f, // Secondary ATA Hard Disk
             /* Reserved by OS */
             IRQ16 = 0x30, // Reserved for multitasking
             IRQ17 = 0x31,
             IRQ18 = 0x32,
             IRQ19 = 0x33,
             IRQ20 = 0x34,
             IRQ21 = 0x35,
             IRQ22 = 0x36,
             IRQ23 = 0x37,
             IRQ24 = 0x38,
             IRQ25 = 0x39,
             IRQ26 = 0x3a,
             IRQ27 = 0x3b,
             IRQ28 = 0x3c,
             IRQ29 = 0x3d,
             /* Free */
             IRQ30 = 0x3e,
             IRQ31 = 0x3f,
             IRQ32 = 0x40,
             IRQ33 = 0x41,
             IRQ34 = 0x42,
             IRQ35 = 0x43,
             IRQ36 = 0x44,
             IRQ37 = 0x45,
             IRQ38 = 0x46,
             IRQ39 = 0x47,
             IRQ40 = 0x48,
             IRQ41 = 0x49,
             IRQ42 = 0x4a,
             IRQ43 = 0x4b,
             IRQ44 = 0x4c,
             IRQ45 = 0x4d,
             IRQ46 = 0x4e,
             IRQ47 = 0x4f,
             IRQ48 = 0x50,
             IRQ49 = 0x51,
             IRQ50 = 0x52,
             IRQ51 = 0x53,
             IRQ52 = 0x54,
             IRQ53 = 0x55,
             IRQ54 = 0x56,
             IRQ55 = 0x57,
             IRQ56 = 0x58,
             IRQ57 = 0x59,
             IRQ58 = 0x5a,
             IRQ59 = 0x5b,
             IRQ60 = 0x5c,
             IRQ61 = 0x5d,
             IRQ62 = 0x5e,
             IRQ63 = 0x5f,
             IRQ64 = 0x60,
             IRQ65 = 0x61,
             IRQ66 = 0x62,
             IRQ67 = 0x63,
             IRQ68 = 0x64,
             IRQ69 = 0x65,
             IRQ70 = 0x66,
             IRQ71 = 0x67,
             IRQ72 = 0x68,
             IRQ73 = 0x69,
             IRQ74 = 0x6a,
             IRQ75 = 0x6b,
             IRQ76 = 0x6c,
             IRQ77 = 0x6d,
             IRQ78 = 0x6e,
             IRQ79 = 0x6f,
             IRQ80 = 0x70,
             IRQ81 = 0x71,
             IRQ82 = 0x72,
             IRQ83 = 0x73,
             IRQ84 = 0x74,
             IRQ85 = 0x75,
             IRQ86 = 0x76,
             IRQ87 = 0x77,
             IRQ88 = 0x78,
             IRQ89 = 0x79,
             IRQ90 = 0x7a,
             IRQ91 = 0x7b,
             IRQ92 = 0x7c,
             IRQ93 = 0x7d,
             IRQ94 = 0x7e,
             IRQ95 = 0x7f,
             IRQ96 = 0x80,
             IRQ97 = 0x81,
             IRQ98 = 0x82,
             IRQ99 = 0x83,
             IRQ100 = 0x84,
             IRQ101 = 0x85,
             IRQ102 = 0x86,
             IRQ103 = 0x87,
             IRQ104 = 0x88,
             IRQ105 = 0x89,
             IRQ106 = 0x8a,
             IRQ107 = 0x8b,
             IRQ108 = 0x8c,
             IRQ109 = 0x8d,
             IRQ110 = 0x8e,
             IRQ111 = 0x8f,
             IRQ112 = 0x90,
             IRQ113 = 0x91,
             IRQ114 = 0x92,
             IRQ115 = 0x93,
             IRQ116 = 0x94,
             IRQ117 = 0x95,
             IRQ118 = 0x96,
             IRQ119 = 0x97,
             IRQ120 = 0x98,
             IRQ121 = 0x99,
             IRQ122 = 0x9a,
             IRQ123 = 0x9b,
             IRQ124 = 0x9c,
             IRQ125 = 0x9d,
             IRQ126 = 0x9e,
             IRQ127 = 0x9f,
             IRQ128 = 0xa0,
             IRQ129 = 0xa1,
             IRQ130 = 0xa2,
             IRQ131 = 0xa3,
             IRQ132 = 0xa4,
             IRQ133 = 0xa5,
             IRQ134 = 0xa6,
             IRQ135 = 0xa7,
             IRQ136 = 0xa8,
             IRQ137 = 0xa9,
             IRQ138 = 0xaa,
             IRQ139 = 0xab,
             IRQ140 = 0xac,
             IRQ141 = 0xad,
             IRQ142 = 0xae,
             IRQ143 = 0xaf,
             IRQ144 = 0xb0,
             IRQ145 = 0xb1,
             IRQ146 = 0xb2,
             IRQ147 = 0xb3,
             IRQ148 = 0xb4,
             IRQ149 = 0xb5,
             IRQ150 = 0xb6,
             IRQ151 = 0xb7,
             IRQ152 = 0xb8,
             IRQ153 = 0xb9,
             IRQ154 = 0xba,
             IRQ155 = 0xbb,
             IRQ156 = 0xbc,
             IRQ157 = 0xbd,
             IRQ158 = 0xbe,
             IRQ159 = 0xbf,
             IRQ160 = 0xc0,
             IRQ161 = 0xc1,
             IRQ162 = 0xc2,
             IRQ163 = 0xc3,
             IRQ164 = 0xc4,
             IRQ165 = 0xc5,
             IRQ166 = 0xc6,
             IRQ167 = 0xc7,
             IRQ168 = 0xc8,
             IRQ169 = 0xc9,
             IRQ170 = 0xca,
             IRQ171 = 0xcb,
             IRQ172 = 0xcc,
             IRQ173 = 0xcd,
             IRQ174 = 0xce,
             IRQ175 = 0xcf,
             IRQ176 = 0xd0,
             IRQ177 = 0xd1,
             IRQ178 = 0xd2,
             IRQ179 = 0xd3,
             IRQ180 = 0xd4,
             IRQ181 = 0xd5,
             IRQ182 = 0xd6,
             IRQ183 = 0xd7,
             IRQ184 = 0xd8,
             IRQ185 = 0xd9,
             IRQ186 = 0xda,
             IRQ187 = 0xdb,
             IRQ188 = 0xdc,
             IRQ189 = 0xdd,
             IRQ190 = 0xde,
             IRQ191 = 0xdf,
             IRQ192 = 0xe0,
             IRQ193 = 0xe1,
             IRQ194 = 0xe2,
             IRQ195 = 0xe3,
             IRQ196 = 0xe4,
             IRQ197 = 0xe5,
             IRQ198 = 0xe6,
             IRQ199 = 0xe7,
             IRQ200 = 0xe8,
             IRQ201 = 0xe9,
             IRQ202 = 0xea,
             IRQ203 = 0xeb,
             IRQ204 = 0xec,
             IRQ205 = 0xed,
             IRQ206 = 0xee,
             IRQ207 = 0xef,
             IRQ208 = 0xf0,
             IRQ209 = 0xf1,
             IRQ210 = 0xf2,
             IRQ211 = 0xf3,
             IRQ212 = 0xf4,
             IRQ213 = 0xf5,
             IRQ214 = 0xf6,
             IRQ215 = 0xf7,
             IRQ216 = 0xf8,
             IRQ217 = 0xf9,
             IRQ218 = 0xfa,
             IRQ219 = 0xfb,
             IRQ220 = 0xfc,
             IRQ221 = 0xfd,
             IRQ222 = 0xfe,
             IRQ223 = 0xff,
         };
ISRExceptions
enum CPU::x64::ISRExceptions
Enumerator
DivideByZero
Debug
NonMaskableInterrupt
Breakpoint
Overflow
BoundRange
InvalidOpcode
DeviceNotAvailable
DoubleFault
CoprocessorSegmentOverrun
InvalidTSS
SegmentNotPresent
StackSegmentFault
GeneralProtectionFault
PageFault
x87FloatingPoint
AlignmentCheck
MachineCheck
SIMDFloatingPoint
Virtualization
Security
Definition at line 2568 of file cpu.hpp.
         {
             DivideByZero = 0x0,
             Debug = 0x1,
             NonMaskableInterrupt = 0x2,
             Breakpoint = 0x3,
             Overflow = 0x4,
             BoundRange = 0x5,
             InvalidOpcode = 0x6,
             DeviceNotAvailable = 0x7,
             DoubleFault = 0x8,
             CoprocessorSegmentOverrun = 0x9,
             InvalidTSS = 0xa,
             SegmentNotPresent = 0xb,
             StackSegmentFault = 0xc,
             GeneralProtectionFault = 0xd,
             PageFault = 0xe,
             x87FloatingPoint = 0x10,
             AlignmentCheck = 0x11,
             MachineCheck = 0x12,
             SIMDFloatingPoint = 0x13,
             Virtualization = 0x14,
             Security = 0x1e
         };
MSRID
enum CPU::x64::MSRID
Enumerator
MSR_MONITOR_FILTER_SIZE
MSR_TIME_STAMP_COUNTER
MSR_PLATFORM_ID
MSR_APIC_BASE
MSR_FEATURE_CONTROL
MSR_TSC_ADJUST
MSR_SPEC_CTRL
MSR_PRED_CMD
MSR_BIOS_UPDT_TRIG
MSR_BIOS_SIGN_ID
MSR_SGXLEPUBKEYHASH0
MSR_SGXLEPUBKEYHASH1
MSR_SGXLEPUBKEYHASH2
MSR_SGXLEPUBKEYHASH3
MSR_SMM_MONITOR_CTL
MSR_SMBASE
MSR_PMC0
MSR_PMC1
MSR_PMC2
MSR_PMC3
MSR_PMC4
MSR_PMC5
MSR_PMC6
MSR_PMC7
MSR_UMWAIT_CONTROL
MSR_MPERF
MSR_APERF
MSR_MTRRCAP
MSR_ARCH_CAPABILITIES
MSR_FLUSH_CMD
MSR_SYSENTER_CS
MSR_SYSENTER_ESP
MSR_SYSENTER_EIP
MSR_MCG_CAP
MSR_MCG_STATUS
MSR_MCG_CTL
MSR_PERFEVTSEL0
MSR_PERFEVTSEL1
MSR_PERFEVTSEL2
MSR_PERFEVTSEL3
MSR_PERF_STATUS
MSR_PERF_CTL
MSR_CLOCK_MODULATION
MSR_THERM_INTERRUPT
MSR_THERM_STATUS
MSR_MISC_ENABLE
MSR_ENERGY_PERF_BIAS
MSR_PACKAGE_THERM_STATUS
MSR_PACKAGE_THERM_INTERRUPT
MSR_DEBUGCTL
MSR_SMRR_PHYSBASE
MSR_SMRR_PHYSMASK
MSR_PLATFORM_DCA_CAP
MSR_CPU_DCA_CAP
MSR_DCA_0_CAP
MSR_MTRR_PHYSBASE0
MSR_MTRR_PHYSMASK0
MSR_MTRR_PHYSBASE1
MSR_MTRR_PHYSMASK1
MSR_MTRR_PHYSBASE2
MSR_MTRR_PHYSMASK2
MSR_MTRR_PHYSBASE3
MSR_MTRR_PHYSMASK3
MSR_MTRR_PHYSBASE4
MSR_MTRR_PHYSMASK4
MSR_MTRR_PHYSBASE5
MSR_MTRR_PHYSMASK5
MSR_MTRR_PHYSBASE6
MSR_MTRR_PHYSMASK6
MSR_MTRR_PHYSBASE7
MSR_MTRR_PHYSMASK7
MSR_MTRR_PHYSBASE8
MSR_MTRR_PHYSMASK8
MSR_MTRR_PHYSBASE9
MSR_MTRR_PHYSMASK9
MSR_MTRR_FIX64K_00000
MSR_MTRR_FIX16K_80000
MSR_MTRR_FIX16K_A0000
MSR_MTRR_FIX4K_C0000
MSR_MTRR_FIX4K_C8000
MSR_MTRR_FIX4K_D0000
MSR_MTRR_FIX4K_D8000
MSR_MTRR_FIX4K_E0000
MSR_MTRR_FIX4K_E8000
MSR_MTRR_FIX4K_F0000
MSR_MTRR_FIX4K_F8000
MSR_PAT
MSR_MC0_CTL2
MSR_MC1_CTL2
MSR_MC2_CTL2
MSR_MC3_CTL2
MSR_MC4_CTL2
MSR_MC5_CTL2
MSR_MC6_CTL2
MSR_MC7_CTL2
MSR_MC8_CTL2
MSR_MC9_CTL2
MSR_MC10_CTL2
MSR_MC11_CTL2
MSR_MC12_CTL2
MSR_MC13_CTL2
MSR_MC14_CTL2
MSR_MC15_CTL2
MSR_MC16_CTL2
MSR_MC17_CTL2
MSR_MC18_CTL2
MSR_MC19_CTL2
MSR_MC20_CTL2
MSR_MC21_CTL2
MSR_MC22_CTL2
MSR_MC23_CTL2
MSR_MC24_CTL2
MSR_MC25_CTL2
MSR_MC26_CTL2
MSR_MC27_CTL2
MSR_MC28_CTL2
MSR_MC29_CTL2
MSR_MC30_CTL2
MSR_MC31_CTL2
MSR_MTRR_DEF_TYPE
MSR_FIXED_CTR0
MSR_FIXED_CTR1
MSR_FIXED_CTR2
MSR_PERF_CAPABILITIES
MSR_FIXED_CTR_CTRL
MSR_PERF_GLOBAL_STATUS
MSR_PERF_GLOBAL_CTRL
MSR_PERF_GLOBAL_STATUS_RESET
MSR_PERF_GLOBAL_STATUS_SET
MSR_PERF_GLOBAL_INUSE
MSR_PEBS_ENABLE
MSR_MC0_CTL
MSR_MC0_STATUS
MSR_MC0_ADDR
MSR_MC0_MISC
MSR_MC1_CTL
MSR_MC1_STATUS
MSR_MC1_ADDR
MSR_MC1_MISC
MSR_MC2_CTL
MSR_MC2_STATUS
MSR_MC2_ADDR
MSR_MC2_MISC
MSR_MC3_CTL
MSR_MC3_STATUS
MSR_MC3_ADDR
MSR_MC3_MISC
MSR_MC4_CTL
MSR_MC4_STATUS
MSR_MC4_ADDR
MSR_MC4_MISC
MSR_MC5_CTL
MSR_MC5_STATUS
MSR_MC5_ADDR
MSR_MC5_MISC
MSR_MC6_CTL
MSR_MC6_STATUS
MSR_MC6_ADDR
MSR_MC6_MISC
MSR_MC7_CTL
MSR_MC7_STATUS
MSR_MC7_ADDR
MSR_MC7_MISC
MSR_MC8_CTL
MSR_MC8_STATUS
MSR_MC8_ADDR
MSR_MC8_MISC
MSR_MC9_CTL
MSR_MC9_STATUS
MSR_MC9_ADDR
MSR_MC9_MISC
MSR_MC10_CTL
MSR_MC10_STATUS
MSR_MC10_ADDR
MSR_MC10_MISC
MSR_MC11_CTL
MSR_MC11_STATUS
MSR_MC11_ADDR
MSR_MC11_MISC
MSR_MC12_CTL
MSR_MC12_STATUS
MSR_MC12_ADDR
MSR_MC12_MISC
MSR_MC13_CTL
MSR_MC13_STATUS
MSR_MC13_ADDR
MSR_MC13_MISC
MSR_MC14_CTL
MSR_MC14_STATUS
MSR_MC14_ADDR
MSR_MC14_MISC
MSR_MC15_CTL
MSR_MC15_STATUS
MSR_MC15_ADDR
MSR_MC15_MISC
MSR_MC16_CTL
MSR_MC16_STATUS
MSR_MC16_ADDR
MSR_MC16_MISC
MSR_MC17_CTL
MSR_MC17_STATUS
MSR_MC17_ADDR
MSR_MC17_MISC
MSR_MC18_CTL
MSR_MC18_STATUS
MSR_MC18_ADDR
MSR_MC18_MISC
MSR_MC19_CTL
MSR_MC19_STATUS
MSR_MC19_ADDR
MSR_MC19_MISC
MSR_MC20_CTL
MSR_MC20_STATUS
MSR_MC20_ADDR
MSR_MC20_MISC
MSR_MC21_CTL
MSR_MC21_STATUS
MSR_MC21_ADDR
MSR_MC21_MISC
MSR_MC22_CTL
MSR_MC22_STATUS
MSR_MC22_ADDR
MSR_MC22_MISC
MSR_MC23_CTL
MSR_MC23_STATUS
MSR_MC23_ADDR
MSR_MC23_MISC
MSR_MC24_CTL
MSR_MC24_STATUS
MSR_MC24_ADDR
MSR_MC24_MISC
MSR_MC25_CTL
MSR_MC25_STATUS
MSR_MC25_ADDR
MSR_MC25_MISC
MSR_MC26_CTL
MSR_MC26_STATUS
MSR_MC26_ADDR
MSR_MC26_MISC
MSR_MC27_CTL
MSR_MC27_STATUS
MSR_MC27_ADDR
MSR_MC27_MISC
MSR_MC28_CTL
MSR_MC28_STATUS
MSR_MC28_ADDR
MSR_MC28_MISC
MSR_VMX_BASIC
MSR_VMX_PINBASED_CTLS
MSR_VMX_PROCBASED_CTLS
MSR_VMX_EXIT_CTLS
MSR_VMX_ENTRY_CTLS
MSR_VMX_MISC
MSR_VMX_CR0_FIXED0
MSR_VMX_CR0_FIXED1
MSR_VMX_CR4_FIXED0
MSR_VMX_CR4_FIXED1
MSR_VMX_VMCS_ENUM
MSR_VMX_PROCBASED_CTLS2
MSR_VMX_EPT_VPID_CAP
MSR_VMX_TRUE_PINBASED_CTLS
MSR_VMX_TRUE_PROCBASED_CTLS
MSR_VMX_TRUE_EXIT_CTLS
MSR_VMX_TRUE_ENTRY_CTLS
MSR_VMX_VMFUNC
MSR_A_PMC0
MSR_A_PMC1
MSR_A_PMC2
MSR_A_PMC3
MSR_A_PMC4
MSR_A_PMC5
MSR_A_PMC6
MSR_A_PMC7
MSR_MCG_EXT_CTL
MSR_SGX_SVN_STATUS
MSR_RTIT_OUTPUT_BASE
MSR_RTIT_OUTPUT_MASK_PTRS
MSR_RTIT_CTL
MSR_RTIT_STATUS
MSR_RTIT_CR3_MATCH
MSR_RTIT_ADDR0_A
MSR_RTIT_ADDR0_B
MSR_RTIT_ADDR1_A
MSR_RTIT_ADDR1_B
MSR_RTIT_ADDR2_A
MSR_RTIT_ADDR2_B
MSR_RTIT_ADDR3_A
MSR_RTIT_ADDR3_B
MSR_DS_AREA
MSR_TSC_DEADLINE
MSR_PM_ENABLE
MSR_HWP_CAPABILITIES
MSR_HWP_REQUEST_PKG
MSR_HWP_INTERRUPT
MSR_HWP_REQUEST
MSR_HWP_STATUS
MSR_X2APIC_APICID
MSR_X2APIC_VERSION
MSR_X2APIC_TPR
MSR_X2APIC_PPR
MSR_X2APIC_EOI
MSR_X2APIC_LDR
MSR_X2APIC_SIVR
MSR_X2APIC_ISR0
MSR_X2APIC_ISR1
MSR_X2APIC_ISR2
MSR_X2APIC_ISR3
MSR_X2APIC_ISR4
MSR_X2APIC_ISR5
MSR_X2APIC_ISR6
MSR_X2APIC_ISR7
MSR_X2APIC_TMR0
MSR_X2APIC_TMR1
MSR_X2APIC_TMR2
MSR_X2APIC_TMR3
MSR_X2APIC_TMR4
MSR_X2APIC_TMR5
MSR_X2APIC_TMR6
MSR_X2APIC_TMR7
MSR_X2APIC_IRR0
MSR_X2APIC_IRR1
MSR_X2APIC_IRR2
MSR_X2APIC_IRR3
MSR_X2APIC_IRR4
MSR_X2APIC_IRR5
MSR_X2APIC_IRR6
MSR_X2APIC_IRR7
MSR_X2APIC_ESR
MSR_X2APIC_LVT_CMCI
MSR_X2APIC_ICR
MSR_X2APIC_LVT_TIMER
MSR_X2APIC_LVT_THERMAL
MSR_X2APIC_LVT_PMI
MSR_X2APIC_LVT_LINT0
MSR_X2APIC_LVT_LINT1
MSR_X2APIC_LVT_ERROR
MSR_X2APIC_INIT_COUNT
MSR_X2APIC_CUR_COUNT
MSR_X2APIC_DIV_CONF
MSR_X2APIC_SELF_IPI
MSR_DEBUG_INTERFACE
MSR_L3_QOS_CFG
MSR_L2_QOS_CFG
MSR_QM_EVTSEL
MSR_QM_CTR
MSR_PQR_ASSOC
MSR_L3_MASK_0
MSR_L2_MASK_0
MSR_BNDCFGS
MSR_XSS
MSR_PKG_HDC_CTL
MSR_PM_CTL1
MSR_THREAD_STALL
MSR_EFER
Extended Feature Enable Register (0xc0000080)
MSR_STAR
legacy SYSCALL (0xC0000081)
MSR_LSTAR
64bit SYSCALL (0xC0000082)
MSR_CSTAR
compatibility mode SYSCALL (0xC0000083)
MSR_SYSCALL_MASK
EFLAGS mask for syscall (0xC0000084)
MSR_FS_BASE
64bit FS base (0xC0000100)
MSR_GS_BASE
64bit GS base (0xC0000101)
MSR_SHADOW_GS_BASE
SwapGS GS shadow (0xC0000102)
MSR_TSC_AUX
Auxiliary TSC (0xC0000103)
MSR_CR_PAT
MSR_CR_PAT_RESET
Definition at line 2191 of file cpu.hpp.
         {
             MSR_MONITOR_FILTER_SIZE = 0x6,
             MSR_TIME_STAMP_COUNTER = 0x10,
             MSR_PLATFORM_ID = 0x17,
             MSR_APIC_BASE = 0x1B,
             MSR_FEATURE_CONTROL = 0x3A,
             MSR_TSC_ADJUST = 0x3B,
             MSR_SPEC_CTRL = 0x48,
             MSR_PRED_CMD = 0x49,
             MSR_BIOS_UPDT_TRIG = 0x79,
             MSR_BIOS_SIGN_ID = 0x8B,
             MSR_SGXLEPUBKEYHASH0 = 0x8C,
             MSR_SGXLEPUBKEYHASH1 = 0x8D,
             MSR_SGXLEPUBKEYHASH2 = 0x8E,
             MSR_SGXLEPUBKEYHASH3 = 0x8F,
             MSR_SMM_MONITOR_CTL = 0x9B,
             MSR_SMBASE = 0x9E,
             MSR_PMC0 = 0xC1,
             MSR_PMC1 = 0xC2,
             MSR_PMC2 = 0xC3,
             MSR_PMC3 = 0xC4,
             MSR_PMC4 = 0xC5,
             MSR_PMC5 = 0xC6,
             MSR_PMC6 = 0xC7,
             MSR_PMC7 = 0xC8,
             MSR_UMWAIT_CONTROL = 0xE1,
             MSR_MPERF = 0xE7,
             MSR_APERF = 0xE8,
             MSR_MTRRCAP = 0xFE,
             MSR_ARCH_CAPABILITIES = 0x10A,
             MSR_FLUSH_CMD = 0x10B,
             MSR_SYSENTER_CS = 0x17A,
             MSR_SYSENTER_ESP = 0x175,
             MSR_SYSENTER_EIP = 0x176,
             MSR_MCG_CAP = 0x179,
             MSR_MCG_STATUS = 0x17A,
             MSR_MCG_CTL = 0x17B,
             MSR_PERFEVTSEL0 = 0x186,
             MSR_PERFEVTSEL1 = 0x187,
             MSR_PERFEVTSEL2 = 0x188,
             MSR_PERFEVTSEL3 = 0x189,
             MSR_PERF_STATUS = 0x198,
             MSR_PERF_CTL = 0x199,
             MSR_CLOCK_MODULATION = 0x19A,
             MSR_THERM_INTERRUPT = 0x19B,
             MSR_THERM_STATUS = 0x19C,
             MSR_MISC_ENABLE = 0x1A0,
             MSR_ENERGY_PERF_BIAS = 0x1B0,
             MSR_PACKAGE_THERM_STATUS = 0x1B1,
             MSR_PACKAGE_THERM_INTERRUPT = 0x1B2,
             MSR_DEBUGCTL = 0x1D9,
             MSR_SMRR_PHYSBASE = 0x1F2,
             MSR_SMRR_PHYSMASK = 0x1F3,
             MSR_PLATFORM_DCA_CAP = 0x1F8,
             MSR_CPU_DCA_CAP = 0x1F9,
             MSR_DCA_0_CAP = 0x1FA,
             MSR_MTRR_PHYSBASE0 = 0x200,
             MSR_MTRR_PHYSMASK0 = 0x201,
             MSR_MTRR_PHYSBASE1 = 0x202,
             MSR_MTRR_PHYSMASK1 = 0x203,
             MSR_MTRR_PHYSBASE2 = 0x204,
             MSR_MTRR_PHYSMASK2 = 0x205,
             MSR_MTRR_PHYSBASE3 = 0x206,
             MSR_MTRR_PHYSMASK3 = 0x207,
             MSR_MTRR_PHYSBASE4 = 0x208,
             MSR_MTRR_PHYSMASK4 = 0x209,
             MSR_MTRR_PHYSBASE5 = 0x20A,
             MSR_MTRR_PHYSMASK5 = 0x20B,
             MSR_MTRR_PHYSBASE6 = 0x20C,
             MSR_MTRR_PHYSMASK6 = 0x20D,
             MSR_MTRR_PHYSBASE7 = 0x20E,
             MSR_MTRR_PHYSMASK7 = 0x20F,
             MSR_MTRR_PHYSBASE8 = 0x210,
             MSR_MTRR_PHYSMASK8 = 0x211,
             MSR_MTRR_PHYSBASE9 = 0x212,
             MSR_MTRR_PHYSMASK9 = 0x213,
             MSR_MTRR_FIX64K_00000 = 0x250,
             MSR_MTRR_FIX16K_80000 = 0x258,
             MSR_MTRR_FIX16K_A0000 = 0x259,
             MSR_MTRR_FIX4K_C0000 = 0x268,
             MSR_MTRR_FIX4K_C8000 = 0x269,
             MSR_MTRR_FIX4K_D0000 = 0x26A,
             MSR_MTRR_FIX4K_D8000 = 0x26B,
             MSR_MTRR_FIX4K_E0000 = 0x26C,
             MSR_MTRR_FIX4K_E8000 = 0x26D,
             MSR_MTRR_FIX4K_F0000 = 0x26E,
             MSR_MTRR_FIX4K_F8000 = 0x26F,
             MSR_PAT = 0x277,
             MSR_MC0_CTL2 = 0x280,
             MSR_MC1_CTL2 = 0x281,
             MSR_MC2_CTL2 = 0x282,
             MSR_MC3_CTL2 = 0x283,
             MSR_MC4_CTL2 = 0x284,
             MSR_MC5_CTL2 = 0x285,
             MSR_MC6_CTL2 = 0x286,
             MSR_MC7_CTL2 = 0x287,
             MSR_MC8_CTL2 = 0x288,
             MSR_MC9_CTL2 = 0x289,
             MSR_MC10_CTL2 = 0x28A,
             MSR_MC11_CTL2 = 0x28B,
             MSR_MC12_CTL2 = 0x28C,
             MSR_MC13_CTL2 = 0x28D,
             MSR_MC14_CTL2 = 0x28E,
             MSR_MC15_CTL2 = 0x28F,
             MSR_MC16_CTL2 = 0x290,
             MSR_MC17_CTL2 = 0x291,
             MSR_MC18_CTL2 = 0x292,
             MSR_MC19_CTL2 = 0x293,
             MSR_MC20_CTL2 = 0x294,
             MSR_MC21_CTL2 = 0x295,
             MSR_MC22_CTL2 = 0x296,
             MSR_MC23_CTL2 = 0x297,
             MSR_MC24_CTL2 = 0x298,
             MSR_MC25_CTL2 = 0x299,
             MSR_MC26_CTL2 = 0x29A,
             MSR_MC27_CTL2 = 0x29B,
             MSR_MC28_CTL2 = 0x29C,
             MSR_MC29_CTL2 = 0x29D,
             MSR_MC30_CTL2 = 0x29E,
             MSR_MC31_CTL2 = 0x29F,
             MSR_MTRR_DEF_TYPE = 0x2FF,
             MSR_FIXED_CTR0 = 0x309,
             MSR_FIXED_CTR1 = 0x30A,
             MSR_FIXED_CTR2 = 0x30B,
             MSR_PERF_CAPABILITIES = 0x345,
             MSR_FIXED_CTR_CTRL = 0x38D,
             MSR_PERF_GLOBAL_STATUS = 0x38E,
             MSR_PERF_GLOBAL_CTRL = 0x38F,
             MSR_PERF_GLOBAL_STATUS_RESET = 0x390,
             MSR_PERF_GLOBAL_STATUS_SET = 0x391,
             MSR_PERF_GLOBAL_INUSE = 0x392,
             MSR_PEBS_ENABLE = 0x3F1,
             MSR_MC0_CTL = 0x400,
             MSR_MC0_STATUS = 0x401,
             MSR_MC0_ADDR = 0x402,
             MSR_MC0_MISC = 0x403,
             MSR_MC1_CTL = 0x404,
             MSR_MC1_STATUS = 0x405,
             MSR_MC1_ADDR = 0x406,
             MSR_MC1_MISC = 0x407,
             MSR_MC2_CTL = 0x408,
             MSR_MC2_STATUS = 0x409,
             MSR_MC2_ADDR = 0x40A,
             MSR_MC2_MISC = 0x40B,
             MSR_MC3_CTL = 0x40C,
             MSR_MC3_STATUS = 0x40D,
             MSR_MC3_ADDR = 0x40E,
             MSR_MC3_MISC = 0x40F,
             MSR_MC4_CTL = 0x410,
             MSR_MC4_STATUS = 0x411,
             MSR_MC4_ADDR = 0x412,
             MSR_MC4_MISC = 0x413,
             MSR_MC5_CTL = 0x414,
             MSR_MC5_STATUS = 0x415,
             MSR_MC5_ADDR = 0x416,
             MSR_MC5_MISC = 0x417,
             MSR_MC6_CTL = 0x418,
             MSR_MC6_STATUS = 0x419,
             MSR_MC6_ADDR = 0x41A,
             MSR_MC6_MISC = 0x41B,
             MSR_MC7_CTL = 0x41C,
             MSR_MC7_STATUS = 0x41D,
             MSR_MC7_ADDR = 0x41E,
             MSR_MC7_MISC = 0x41F,
             MSR_MC8_CTL = 0x420,
             MSR_MC8_STATUS = 0x421,
             MSR_MC8_ADDR = 0x422,
             MSR_MC8_MISC = 0x423,
             MSR_MC9_CTL = 0x424,
             MSR_MC9_STATUS = 0x425,
             MSR_MC9_ADDR = 0x426,
             MSR_MC9_MISC = 0x427,
             MSR_MC10_CTL = 0x428,
             MSR_MC10_STATUS = 0x429,
             MSR_MC10_ADDR = 0x42A,
             MSR_MC10_MISC = 0x42B,
             MSR_MC11_CTL = 0x42C,
             MSR_MC11_STATUS = 0x42D,
             MSR_MC11_ADDR = 0x42E,
             MSR_MC11_MISC = 0x42F,
             MSR_MC12_CTL = 0x430,
             MSR_MC12_STATUS = 0x431,
             MSR_MC12_ADDR = 0x432,
             MSR_MC12_MISC = 0x433,
             MSR_MC13_CTL = 0x434,
             MSR_MC13_STATUS = 0x435,
             MSR_MC13_ADDR = 0x436,
             MSR_MC13_MISC = 0x437,
             MSR_MC14_CTL = 0x438,
             MSR_MC14_STATUS = 0x439,
             MSR_MC14_ADDR = 0x43A,
             MSR_MC14_MISC = 0x43B,
             MSR_MC15_CTL = 0x43C,
             MSR_MC15_STATUS = 0x43D,
             MSR_MC15_ADDR = 0x43E,
             MSR_MC15_MISC = 0x43F,
             MSR_MC16_CTL = 0x440,
             MSR_MC16_STATUS = 0x441,
             MSR_MC16_ADDR = 0x442,
             MSR_MC16_MISC = 0x443,
             MSR_MC17_CTL = 0x444,
             MSR_MC17_STATUS = 0x445,
             MSR_MC17_ADDR = 0x446,
             MSR_MC17_MISC = 0x447,
             MSR_MC18_CTL = 0x448,
             MSR_MC18_STATUS = 0x449,
             MSR_MC18_ADDR = 0x44A,
             MSR_MC18_MISC = 0x44B,
             MSR_MC19_CTL = 0x44C,
             MSR_MC19_STATUS = 0x44D,
             MSR_MC19_ADDR = 0x44E,
             MSR_MC19_MISC = 0x44F,
             MSR_MC20_CTL = 0x450,
             MSR_MC20_STATUS = 0x451,
             MSR_MC20_ADDR = 0x452,
             MSR_MC20_MISC = 0x453,
             MSR_MC21_CTL = 0x454,
             MSR_MC21_STATUS = 0x455,
             MSR_MC21_ADDR = 0x456,
             MSR_MC21_MISC = 0x457,
             MSR_MC22_CTL = 0x458,
             MSR_MC22_STATUS = 0x459,
             MSR_MC22_ADDR = 0x45A,
             MSR_MC22_MISC = 0x45B,
             MSR_MC23_CTL = 0x45C,
             MSR_MC23_STATUS = 0x45D,
             MSR_MC23_ADDR = 0x45E,
             MSR_MC23_MISC = 0x45F,
             MSR_MC24_CTL = 0x460,
             MSR_MC24_STATUS = 0x461,
             MSR_MC24_ADDR = 0x462,
             MSR_MC24_MISC = 0x463,
             MSR_MC25_CTL = 0x464,
             MSR_MC25_STATUS = 0x465,
             MSR_MC25_ADDR = 0x466,
             MSR_MC25_MISC = 0x467,
             MSR_MC26_CTL = 0x468,
             MSR_MC26_STATUS = 0x469,
             MSR_MC26_ADDR = 0x46A,
             MSR_MC26_MISC = 0x46B,
             MSR_MC27_CTL = 0x46C,
             MSR_MC27_STATUS = 0x46D,
             MSR_MC27_ADDR = 0x46E,
             MSR_MC27_MISC = 0x46F,
             MSR_MC28_CTL = 0x470,
             MSR_MC28_STATUS = 0x471,
             MSR_MC28_ADDR = 0x472,
             MSR_MC28_MISC = 0x473,
             MSR_VMX_BASIC = 0x480,
             MSR_VMX_PINBASED_CTLS = 0x481,
             MSR_VMX_PROCBASED_CTLS = 0x482,
             MSR_VMX_EXIT_CTLS = 0x483,
             MSR_VMX_ENTRY_CTLS = 0x484,
             MSR_VMX_MISC = 0x485,
             MSR_VMX_CR0_FIXED0 = 0x486,
             MSR_VMX_CR0_FIXED1 = 0x487,
             MSR_VMX_CR4_FIXED0 = 0x488,
             MSR_VMX_CR4_FIXED1 = 0x489,
             MSR_VMX_VMCS_ENUM = 0x48A,
             MSR_VMX_PROCBASED_CTLS2 = 0x48B,
             MSR_VMX_EPT_VPID_CAP = 0x48C,
             MSR_VMX_TRUE_PINBASED_CTLS = 0x48D,
             MSR_VMX_TRUE_PROCBASED_CTLS = 0x48E,
             MSR_VMX_TRUE_EXIT_CTLS = 0x48F,
             MSR_VMX_TRUE_ENTRY_CTLS = 0x490,
             MSR_VMX_VMFUNC = 0x491,
             MSR_A_PMC0 = 0x4C1,
             MSR_A_PMC1 = 0x4C2,
             MSR_A_PMC2 = 0x4C3,
             MSR_A_PMC3 = 0x4C4,
             MSR_A_PMC4 = 0x4C5,
             MSR_A_PMC5 = 0x4C6,
             MSR_A_PMC6 = 0x4C7,
             MSR_A_PMC7 = 0x4C8,
             MSR_MCG_EXT_CTL = 0x4D0,
             MSR_SGX_SVN_STATUS = 0x500,
             MSR_RTIT_OUTPUT_BASE = 0x560,
             MSR_RTIT_OUTPUT_MASK_PTRS = 0x561,
             MSR_RTIT_CTL = 0x570,
             MSR_RTIT_STATUS = 0x571,
             MSR_RTIT_CR3_MATCH = 0x572,
             MSR_RTIT_ADDR0_A = 0x580,
             MSR_RTIT_ADDR0_B = 0x581,
             MSR_RTIT_ADDR1_A = 0x582,
             MSR_RTIT_ADDR1_B = 0x583,
             MSR_RTIT_ADDR2_A = 0x584,
             MSR_RTIT_ADDR2_B = 0x585,
             MSR_RTIT_ADDR3_A = 0x586,
             MSR_RTIT_ADDR3_B = 0x587,
             MSR_DS_AREA = 0x600,
             MSR_TSC_DEADLINE = 0x6E0,
             MSR_PM_ENABLE = 0x770,
             MSR_HWP_CAPABILITIES = 0x771,
             MSR_HWP_REQUEST_PKG = 0x772,
             MSR_HWP_INTERRUPT = 0x773,
             MSR_HWP_REQUEST = 0x774,
             MSR_HWP_STATUS = 0x777,
             MSR_X2APIC_APICID = 0x802,
             MSR_X2APIC_VERSION = 0x803,
             MSR_X2APIC_TPR = 0x808,
             MSR_X2APIC_PPR = 0x80A,
             MSR_X2APIC_EOI = 0x80B,
             MSR_X2APIC_LDR = 0x80D,
             MSR_X2APIC_SIVR = 0x80F,
             MSR_X2APIC_ISR0 = 0x810,
             MSR_X2APIC_ISR1 = 0x811,
             MSR_X2APIC_ISR2 = 0x812,
             MSR_X2APIC_ISR3 = 0x813,
             MSR_X2APIC_ISR4 = 0x814,
             MSR_X2APIC_ISR5 = 0x815,
             MSR_X2APIC_ISR6 = 0x816,
             MSR_X2APIC_ISR7 = 0x817,
             MSR_X2APIC_TMR0 = 0x818,
             MSR_X2APIC_TMR1 = 0x819,
             MSR_X2APIC_TMR2 = 0x81A,
             MSR_X2APIC_TMR3 = 0x81B,
             MSR_X2APIC_TMR4 = 0x81C,
             MSR_X2APIC_TMR5 = 0x81D,
             MSR_X2APIC_TMR6 = 0x81E,
             MSR_X2APIC_TMR7 = 0x81F,
             MSR_X2APIC_IRR0 = 0x820,
             MSR_X2APIC_IRR1 = 0x821,
             MSR_X2APIC_IRR2 = 0x822,
             MSR_X2APIC_IRR3 = 0x823,
             MSR_X2APIC_IRR4 = 0x824,
             MSR_X2APIC_IRR5 = 0x825,
             MSR_X2APIC_IRR6 = 0x826,
             MSR_X2APIC_IRR7 = 0x827,
             MSR_X2APIC_ESR = 0x828,
             MSR_X2APIC_LVT_CMCI = 0x82F,
             MSR_X2APIC_ICR = 0x830,
             MSR_X2APIC_LVT_TIMER = 0x832,
             MSR_X2APIC_LVT_THERMAL = 0x833,
             MSR_X2APIC_LVT_PMI = 0x834,
             MSR_X2APIC_LVT_LINT0 = 0x835,
             MSR_X2APIC_LVT_LINT1 = 0x836,
             MSR_X2APIC_LVT_ERROR = 0x837,
             MSR_X2APIC_INIT_COUNT = 0x838,
             MSR_X2APIC_CUR_COUNT = 0x839,
             MSR_X2APIC_DIV_CONF = 0x83E,
             MSR_X2APIC_SELF_IPI = 0x83F,
             MSR_DEBUG_INTERFACE = 0xC80,
             MSR_L3_QOS_CFG = 0xC81,
             MSR_L2_QOS_CFG = 0xC82,
             MSR_QM_EVTSEL = 0xC8D,
             MSR_QM_CTR = 0xC8E,
             MSR_PQR_ASSOC = 0xC8F,
             MSR_L3_MASK_0 = 0xC90,
             MSR_L2_MASK_0 = 0xD10,
             MSR_BNDCFGS = 0xD90,
             MSR_XSS = 0xDA0,
             MSR_PKG_HDC_CTL = 0xDB0,
             MSR_PM_CTL1 = 0xDB1,
             MSR_THREAD_STALL = 0xDB2,
             MSR_EFER = 0xC0000080,
             MSR_STAR = 0xC0000081,
             MSR_LSTAR = 0xC0000082,
             MSR_CSTAR = 0xC0000083,
             MSR_SYSCALL_MASK = 0xC0000084,
             MSR_FS_BASE = 0xC0000100,
             MSR_GS_BASE = 0xC0000101,
             MSR_SHADOW_GS_BASE = 0xC0000102,
             MSR_TSC_AUX = 0xC0000103,
             MSR_CR_PAT = 0x00000277,
             MSR_CR_PAT_RESET = 0x0007040600070406ULL
         };
Function Documentation
__attribute__()
struct CPU::x64::FXState CPU::x64::__attribute__ ((packed))
cpuid()
static SafeFunction void CPU::x64::cpuid (uint32_t Function, uint32_t * eax, uint32_t * ebx, uint32_t * ecx, uint32_t * edx) inline static
CPUID.
Parameters
Function Leaf
eax EAX
ebx EBX
ecx ECX
edx EDX
Definition at line 3333 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("cpuid"
                  : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx)
                  : "a"(Function));
 #endif
         }
References asmv.
Referenced by GetHighestLeaf(), CPU::Hypervisor(), CPU::InitializeFeatures(), CPU::Name(), and CPU::Vendor().
fxrstor()
static SafeFunction void CPU::x64::fxrstor (void * FXRstorArea) inline static
Definition at line 3514 of file cpu.hpp.
         {
 #if defined(__amd64__)
             if (!FXRstorArea || FXRstorArea >= (char *)0xfffffffffffff000)
                 return;
             asmv("fxrstorq (%0)"
                  :
                  : "r"(FXRstorArea)
                  : "memory");
 #endif
         }
References asmv.
Referenced by Tasking::Task::CreateThread(), and CPU::InitializeFeatures().
fxsave()
static SafeFunction void CPU::x64::fxsave (void * FXSaveArea) inline static
Definition at line 3501 of file cpu.hpp.
         {
 #if defined(__amd64__)
             if (!FXSaveArea || FXSaveArea >= (char *)0xfffffffffffff000)
                 return;
             asmv("fxsaveq (%0)"
                  :
                  : "r"(FXSaveArea)
                  : "memory");
 #endif
         }
References asmv.
GetHighestLeaf()
static SafeFunction uint32_t CPU::x64::GetHighestLeaf () inline static
Definition at line 3349 of file cpu.hpp.
         {
             uint32_t eax, ebx, ecx, edx;
             cpuid(0x0, &eax, &ebx, &ecx, &edx);
             return eax;
         }
References cpuid().
invlpg()
static SafeFunction void CPU::x64::invlpg (void * Address) inline static
Definition at line 3314 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("invlpg (%0)"
                  :
                  : "r"(Address)
                  : "memory");
 #endif
         }
References Address, and asmv.
lgdt()
static SafeFunction void CPU::x64::lgdt (void * gdt) inline static
Definition at line 3287 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("lgdt (%0)"
                  :
                  : "r"(gdt));
 #endif
         }
References asmv, and GlobalDescriptorTable::gdt.
Referenced by GlobalDescriptorTable::Init().
lidt()
static SafeFunction void CPU::x64::lidt (void * idt) inline static
Definition at line 3296 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("lidt (%0)"
                  :
                  : "r"(idt));
 #endif
         }
References asmv.
Referenced by InterruptDescriptorTable::Init().
ltr()
static SafeFunction void CPU::x64::ltr (uint16_t Segment) inline static
Definition at line 3305 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("ltr %0"
                  :
                  : "r"(Segment));
 #endif
         }
References asmv.
Referenced by GlobalDescriptorTable::Init().
rdmsr()
static SafeFunction uint64_t CPU::x64::rdmsr (uint32_t msr) inline static
Definition at line 3356 of file cpu.hpp.
         {
             uint32_t Low, High;
 #if defined(__amd64__)
             asmv("rdmsr"
                  : "=a"(Low), "=d"(High)
                  : "c"(msr)
                  : "memory");
 #endif
             return ((uint64_t)Low) | (((uint64_t)High) << 32);
         }
References asmv.
Referenced by APIC::APIC::APIC(), Tasking::Task::CreateThread(), CrashHandler::DisplayDetailsScreen(), GetCurrentCPU(), CrashHandler::Handle(), InitializeSystemCalls(), APIC::APIC::Read(), sys_arch_prctl(), and UserModeExceptionHandler().
readcr0()
static SafeFunction CR0 CPU::x64::readcr0 () inline static
Definition at line 3379 of file cpu.hpp.
         {
             uint64_t Result = 0;
 #if defined(__amd64__)
             asmv("mov %%cr0, %[Result]"
                  : [Result] "=q"(Result));
 #endif
             return (CR0){.raw = Result};
         }
References asmv.
Referenced by CrashHandler::Handle(), CPU::InitializeFeatures(), CrashHandler::UserInput(), and UserModeExceptionHandler().
readcr2()
static SafeFunction CR2 CPU::x64::readcr2 () inline static
Definition at line 3389 of file cpu.hpp.
         {
             uint64_t Result = 0;
 #if defined(__amd64__)
             asmv("mov %%cr2, %[Result]"
                  : [Result] "=q"(Result));
 #endif
             return (CR2){.raw = Result};
         }
References asmv.
Referenced by CrashHandler::DisplayMainScreen(), CrashHandler::Handle(), PageFaultExceptionHandler(), CrashHandler::UserInput(), and UserModeExceptionHandler().
readcr3()
static SafeFunction CR3 CPU::x64::readcr3 () inline static
Definition at line 3399 of file cpu.hpp.
         {
             uint64_t Result = 0;
 #if defined(__amd64__)
             asmv("mov %%cr3, %[Result]"
                  : [Result] "=q"(Result));
 #endif
             return (CR3){.raw = Result};
         }
References asmv.
Referenced by Tasking::Task::CreateProcess(), CrashHandler::Handle(), PageFaultExceptionHandler(), CrashHandler::UserInput(), and UserModeExceptionHandler().
readcr4()
static SafeFunction CR4 CPU::x64::readcr4 () inline static
Definition at line 3409 of file cpu.hpp.
         {
             uint64_t Result = 0;
 #if defined(__amd64__)
             asmv("mov %%cr4, %[Result]"
                  : [Result] "=q"(Result));
 #endif
             return (CR4){.raw = Result};
         }
References asmv.
Referenced by CrashHandler::Handle(), CPU::InitializeFeatures(), CrashHandler::UserInput(), and UserModeExceptionHandler().
readcr8()
static SafeFunction CR8 CPU::x64::readcr8 () inline static
Definition at line 3419 of file cpu.hpp.
         {
             uint64_t Result = 0;
 #if defined(__amd64__)
             asmv("mov %%cr8, %[Result]"
                  : [Result] "=q"(Result));
 #endif
             return (CR8){.raw = Result};
         }
References asmv.
Referenced by CrashHandler::Handle(), CrashHandler::UserInput(), and UserModeExceptionHandler().
readxcr0()
static SafeFunction XCR0 CPU::x64::readxcr0 () inline static
Definition at line 3429 of file cpu.hpp.
         {
             uint64_t Result = 0;
 #if defined(__amd64__)
             asmv("xgetbv"
                  : "=a"(Result)
                  : "c"(0)
                  : "edx");
 #endif
             return (XCR0){.raw = Result};
         }
References asmv.
writecr0()
static SafeFunction void CPU::x64::writecr0 (CR0 ControlRegister) inline static
Definition at line 3441 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("mov %[ControlRegister], %%cr0"
                  :
                  : [ControlRegister] "q"(ControlRegister.raw)
                  : "memory");
 #endif
         }
References asmv, and CPU::x64::CR0::raw.
Referenced by CPU::InitializeFeatures().
writecr2()
static SafeFunction void CPU::x64::writecr2 (CR2 ControlRegister) inline static
Definition at line 3451 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("mov %[ControlRegister], %%cr2"
                  :
                  : [ControlRegister] "q"(ControlRegister.raw)
                  : "memory");
 #endif
         }
References asmv, and CPU::x64::CR2::raw.
writecr3()
static SafeFunction void CPU::x64::writecr3 (CR3 ControlRegister) inline static
Definition at line 3461 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("mov %[ControlRegister], %%cr3"
                  :
                  : [ControlRegister] "q"(ControlRegister.raw)
                  : "memory");
 #endif
         }
References asmv, and CPU::x64::CR3::raw.
writecr4()
static SafeFunction void CPU::x64::writecr4 (CR4 ControlRegister) inline static
Definition at line 3471 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("mov %[ControlRegister], %%cr4"
                  :
                  : [ControlRegister] "q"(ControlRegister.raw)
                  : "memory");
 #endif
         }
References asmv, and CPU::x64::CR4::raw.
Referenced by CPU::InitializeFeatures().
writecr8()
static SafeFunction void CPU::x64::writecr8 (CR8 ControlRegister) inline static
Definition at line 3481 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("mov %[ControlRegister], %%cr8"
                  :
                  : [ControlRegister] "q"(ControlRegister.raw)
                  : "memory");
 #endif
         }
References asmv, and CPU::x64::CR8::raw.
writexcr0()
static SafeFunction void CPU::x64::writexcr0 (XCR0 ControlRegister) inline static
Definition at line 3491 of file cpu.hpp.
         {
 #if defined(__amd64__)
             asmv("xsetbv"
                  :
                  : "a"(ControlRegister.raw), "c"(0)
                  : "edx");
 #endif
         }
References asmv, and CPU::x64::XCR0::raw.
wrmsr()
static SafeFunction void CPU::x64::wrmsr (uint32_t msr, uint64_t Value) inline static
Definition at line 3368 of file cpu.hpp.
         {
             uint32_t Low = Value, High = Value >> 32;
 #if defined(__amd64__)
             asmv("wrmsr"
                  :
                  : "c"(msr), "a"(Low), "d"(High)
                  : "memory");
 #endif
         }
References asmv.
Referenced by APIC::APIC::APIC(), Interrupts::Initialize(), CPU::InitializeFeatures(), InitializeSystemCalls(), APIC::APIC::SendStartupIPI(), sys_arch_prctl(), and APIC::APIC::Write().