Fennix: String Class Reference
String Class Reference
String class String class that can be used to store strings.
#include <string.hpp>
Data Structures
class Iterator
Public Member Functions
String (const char *Str="")
~String ()
int length () const
int capacity () const
const char * c_str () const
void resize (int NewLength)
void concat (const String &Other)
String operator+ (const String &Other) const
String operator+ (const char *Other) const
String & operator= (const String &Other)=default
String & operator= (const char *Other)
String & operator<< (const String &Other)
String & operator<< (const char *Other)
char & operator[] (int Index)
const char & operator[] (int Index) const
bool operator== (const String &Other) const
bool operator!= (const String &Other) const
bool operator== (const char *Other) const
bool operator!= (const char *Other) const
Iterator begin ()
Iterator end ()
Private Attributes
char * m_Data
int m_Length
int m_Capacity
Detailed Description
String class String class that can be used to store strings.
Definition at line 23 of file string.hpp.
Constructor & Destructor Documentation
String()
String::String (const char * Str = "") inline
Definition at line 31 of file string.hpp.
     {
         this->m_Length = strlen(Str);
         this->m_Capacity = this->m_Length + 1;
         this->m_Data = new char[m_Capacity];
         strcpy(m_Data, Str);
         strdbg("New string created: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
     }
References m_Capacity, m_Data, strcpy(), strdbg, and strlen().
~String()
String::~String () inline
Definition at line 40 of file string.hpp.
     {
         strdbg("String deleted: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
         delete[] this->m_Data, this->m_Data = nullptr;
     }
References m_Data, and strdbg.
Member Function Documentation
begin()
Iterator String::begin () inline
Definition at line 220 of file string.hpp.
     {
         strdbg("String iterator begin: %#lx", this->m_Data);
         return Iterator(this->m_Data);
     }
References strdbg.
c_str()
const char* String::c_str () const inline
Definition at line 58 of file string.hpp.
     {
         strdbg("String data: \"%s\"", this->m_Data);
         return this->m_Data;
     }
References m_Data, and strdbg.
Referenced by Execute::ELFInterpreterThreadWrapper(), and Execute::ELFLoadExec().
capacity()
int String::capacity () const inline
Definition at line 52 of file string.hpp.
     {
         strdbg("String capacity: %d", this->m_Capacity);
         return this->m_Capacity;
     }
References m_Capacity, and strdbg.
concat()
void String::concat (const String & Other) inline
Definition at line 84 of file string.hpp.
     {
         int NewLength = this->m_Length + Other.m_Length;
         this->resize(NewLength);
         strcat(m_Data, Other.m_Data);
         strdbg("String concatenated: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
     }
References m_Data, m_Length, resize(), strcat, and strdbg.
Referenced by operator+(), and operator<<().
end()
Iterator String::end () inline
Definition at line 226 of file string.hpp.
     {
         strdbg("String iterator end: %#lx", this->m_Data + this->m_Length);
         return Iterator(this->m_Data + this->m_Length);
     }
References strdbg.
length()
int String::length () const inline
Definition at line 46 of file string.hpp.
     {
         strdbg("String length: %d", this->m_Length);
         return this->m_Length;
     }
References m_Length, and strdbg.
operator!=() [1/2]
bool String::operator!= (const char * Other) const inline
Definition at line 180 of file string.hpp.
     {
         strdbg("String compared: \"%s\" != \"%s\"", this->m_Data, Other);
         return strcmp(this->m_Data, Other) != 0;
     }
References strcmp(), and strdbg.
operator!=() [2/2]
bool String::operator!= (const String & Other) const inline
Definition at line 168 of file string.hpp.
     {
         strdbg("String compared: \"%s\" != \"%s\"", this->m_Data, Other.m_Data);
         return strcmp(this->m_Data, Other.m_Data) != 0;
     }
References m_Data, strcmp(), and strdbg.
operator+() [1/2]
String String::operator+ (const char * Other) const inline
Definition at line 101 of file string.hpp.
     {
         String result = *this;
         result.concat(Other);
         strdbg("String added: \"%s\" (data: %#lx, length: %d, capacity: %d)", result.m_Data, result.m_Data, result.m_Length, result.m_Capacity);
         return result;
     }
References concat(), m_Capacity, m_Data, m_Length, and strdbg.
operator+() [2/2]
String String::operator+ (const String & Other) const inline
Definition at line 93 of file string.hpp.
     {
         String result = *this;
         result.concat(Other);
         strdbg("String added: \"%s\" (data: %#lx, length: %d, capacity: %d)", result.m_Data, result.m_Data, result.m_Length, result.m_Capacity);
         return result;
     }
References concat(), m_Capacity, m_Data, m_Length, and strdbg.
operator<<() [1/2]
String& String::operator<< (const char * Other) inline
Definition at line 143 of file string.hpp.
     {
         this->concat(Other);
         strdbg("String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
         return *this;
     }
References concat(), and strdbg.
operator<<() [2/2]
String& String::operator<< (const String & Other) inline
Definition at line 136 of file string.hpp.
     {
         this->concat(Other);
         strdbg("String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
         return *this;
     }
References concat(), and strdbg.
operator=() [1/2]
String& String::operator= (const char * Other) inline
Definition at line 125 of file string.hpp.
     {
         this->m_Length = strlen(Other);
         this->m_Capacity = this->m_Length + 1;
         delete[] this->m_Data;
         this->m_Data = new char[m_Capacity];
         strcpy(m_Data, Other);
         strdbg("String assigned: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
         return *this;
     }
References m_Capacity, m_Data, strcpy(), strdbg, and strlen().
operator=() [2/2]
String& String::operator= (const String & Other) default
operator==() [1/2]
bool String::operator== (const char * Other) const inline
Definition at line 174 of file string.hpp.
     {
         strdbg("String compared: \"%s\" == \"%s\"", this->m_Data, Other);
         return strcmp(this->m_Data, Other) == 0;
     }
References strcmp(), and strdbg.
operator==() [2/2]
bool String::operator== (const String & Other) const inline
Definition at line 162 of file string.hpp.
     {
         strdbg("String compared: \"%s\" == \"%s\"", this->m_Data, Other.m_Data);
         return strcmp(this->m_Data, Other.m_Data) == 0;
     }
References m_Data, strcmp(), and strdbg.
operator[]() [1/2]
char& String::operator[] (int Index) inline
Definition at line 150 of file string.hpp.
     {
         strdbg("String index: %d", Index);
         return this->m_Data[Index];
     }
References strdbg.
operator[]() [2/2]
const char& String::operator[] (int Index) const inline
Definition at line 156 of file string.hpp.
     {
         strdbg("String index: %d", Index);
         return this->m_Data[Index];
     }
References strdbg.
resize()
void String::resize (int NewLength) inline
Definition at line 64 of file string.hpp.
     {
         strdbg("String resize: %d", NewLength);
         if (NewLength > this->m_Capacity)
         {
             int newCapacity = NewLength + 1;
             char *newData = new char[newCapacity];
             strcpy(newData, this->m_Data);
             strdbg("old: %#lx, new: %#lx", this->m_Data, newData);
             delete[] this->m_Data;
             this->m_Data = newData;
             this->m_Capacity = newCapacity;
         }
         this->m_Length = NewLength;
         this->m_Data[m_Length] = '\0';
         strdbg("String resized: \"%s\" (data: %#lx, length: %d, capacity: %d)", this->m_Data, this->m_Data, this->m_Length, this->m_Capacity);
     }
References m_Data, m_Length, strcpy(), and strdbg.
Referenced by concat().
Field Documentation
m_Capacity
int String::m_Capacity private
Definition at line 28 of file string.hpp.
Referenced by capacity(), operator+(), operator=(), and String().
m_Data
char* String::m_Data private
Definition at line 26 of file string.hpp.
Referenced by c_str(), concat(), operator!=(), operator+(), operator=(), operator==(), resize(), String(), and ~String().
m_Length
int String::m_Length private
Definition at line 27 of file string.hpp.
Referenced by concat(), length(), operator+(), and resize().
The documentation for this class was generated from the following file:
Kernel/include/string.hpp