Fennix: Userspace/mlibc/options/glibc/include/sys/ioctl.h File Reference
ioctl.h File Reference
#include <mlibc-config.h>
#include <abi-bits/ioctls.h>
Macros
#define FIONREAD 0x541B
#define FIONBIO 0x5421
#define FIONCLEX 0x5450
#define FIOCLEX 0x5451
#define SIOCGIFNAME 0x8910
#define SIOCGIFCONF 0x8912
#define SIOCGIFFLAGS 0x8913
#define SIOCSIFFLAGS 0x8914
#define SIOCGIFMTU 0x8921
#define SIOCSIFMTU 0x8922
#define SIOCGIFINDEX 0x8933
#define SIOCPROTOPRIVATE 0x89E0
#define SIOCDEVPRIVATE 0x89F0
Functions
int ioctl (int fd, unsigned long request,...)
Macro Definition Documentation
FIOCLEX
#define FIOCLEX 0x5451
Definition at line 21 of file ioctl.h.
FIONBIO
#define FIONBIO 0x5421
Definition at line 19 of file ioctl.h.
FIONCLEX
#define FIONCLEX 0x5450
Definition at line 20 of file ioctl.h.
FIONREAD
#define FIONREAD 0x541B
Definition at line 18 of file ioctl.h.
SIOCDEVPRIVATE
#define SIOCDEVPRIVATE 0x89F0
Definition at line 32 of file ioctl.h.
SIOCGIFCONF
#define SIOCGIFCONF 0x8912
Definition at line 24 of file ioctl.h.
SIOCGIFFLAGS
#define SIOCGIFFLAGS 0x8913
Definition at line 25 of file ioctl.h.
SIOCGIFINDEX
#define SIOCGIFINDEX 0x8933
Definition at line 29 of file ioctl.h.
SIOCGIFMTU
#define SIOCGIFMTU 0x8921
Definition at line 27 of file ioctl.h.
SIOCGIFNAME
#define SIOCGIFNAME 0x8910
Definition at line 23 of file ioctl.h.
SIOCPROTOPRIVATE
#define SIOCPROTOPRIVATE 0x89E0
Definition at line 31 of file ioctl.h.
SIOCSIFFLAGS
#define SIOCSIFFLAGS 0x8914
Definition at line 26 of file ioctl.h.
SIOCSIFMTU
#define SIOCSIFMTU 0x8922
Definition at line 28 of file ioctl.h.
Function Documentation
ioctl()
int ioctl (int fd, unsigned long request, ...)
Definition at line 9 of file sys-ioctl.cpp.
{
     va_list args;
     va_start(args, request);
     int result;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ioctl, -1);
     void *arg = va_arg(args, void *);
     if(int e = mlibc::sys_ioctl(fd, request, arg, &result); e) {
         errno = e;
         return -1;
     }
     return result;
 }
References mlibc::arg, args, errno, fd, MLIBC_CHECK_OR_ENOSYS, mlibc::request, mlibc::result, mlibc::sys_ioctl(), va_arg, and va_start().
Referenced by login_tty(), tcgetpgrp(), tcgetsid(), and tcsetpgrp().