Fennix Userspace: Userspace/musl/src/thread/pthread_key_create.c File Reference
pthread_key_create.c File Reference
#include "pthread_impl.h"
#include "fork_impl.h"
Functions
static void nodtor (void *dummy)
static void dummy_0 (void)
weak_alias (dummy_0, __tl_lock)
weak_alias (dummy_0, __tl_unlock)
void __pthread_key_atfork (int who)
int __pthread_key_create (pthread_key_t *k, void(*dtor)(void *))
int __pthread_key_delete (pthread_key_t k)
void __pthread_tsd_run_dtors ()
weak_alias (__pthread_key_create, pthread_key_create)
weak_alias (__pthread_key_delete, pthread_key_delete)
Variables
volatile size_t __pthread_tsd_size = sizeof(void *) * PTHREAD_KEYS_MAX
void * __pthread_tsd_main [PTHREAD_KEYS_MAX] = { 0 }
static void(* keys [PTHREAD_KEYS_MAX])(void *)
static pthread_rwlock_t key_lock = PTHREAD_RWLOCK_INITIALIZER
static pthread_key_t next_key
Function Documentation
__pthread_key_atfork()
void __pthread_key_atfork (int who)
Definition at line 24 of file pthread_key_create.c.
 {
     if (who<0) __pthread_rwlock_rdlock(&key_lock);
     else if (!who) __pthread_rwlock_unlock(&key_lock);
     else key_lock = (pthread_rwlock_t)PTHREAD_RWLOCK_INITIALIZER;
 }
References __pthread_rwlock_rdlock(), __pthread_rwlock_unlock(), key_lock, and PTHREAD_RWLOCK_INITIALIZER.
Referenced by fork().
__pthread_key_create()
int __pthread_key_create (pthread_key_t * k, void(*)(void *) dtor)
Definition at line 31 of file pthread_key_create.c.
 {
     pthread_t self = __pthread_self();
     /* This can only happen in the main thread before
      * pthread_create has been called. */
     if (!self->tsd) self->tsd = __pthread_tsd_main;
     /* Purely a sentinel value since null means slot is free. */
     if (!dtor) dtor = nodtor;
     __pthread_rwlock_wrlock(&key_lock);
     pthread_key_t j = next_key;
     do {
         if (!keys[j]) {
             keys[next_key = *k = j] = dtor;
             __pthread_rwlock_unlock(&key_lock);
             return 0;
         }
     } while ((j=(j+1)%PTHREAD_KEYS_MAX) != next_key);
     __pthread_rwlock_unlock(&key_lock);
     return EAGAIN;
 }
References __pthread_rwlock_unlock(), __pthread_rwlock_wrlock(), __pthread_self, __pthread_tsd_main, EAGAIN, j, k, key_lock, keys, next_key, and nodtor().
Referenced by tss_create().
__pthread_key_delete()
int __pthread_key_delete (pthread_key_t k)
Definition at line 56 of file pthread_key_create.c.
 {
     sigset_t set;
     pthread_t self = __pthread_self(), td=self;
     __block_app_sigs(&set);
     __pthread_rwlock_wrlock(&key_lock);
     __tl_lock();
     do td->tsd[k] = 0;
     while ((td=td->next)!=self);
     __tl_unlock();
     keys[k] = 0;
     __pthread_rwlock_unlock(&key_lock);
     __restore_sigs(&set);
     return 0;
 }
References __block_app_sigs(), __pthread_rwlock_unlock(), __pthread_rwlock_wrlock(), __pthread_self, __restore_sigs(), __tl_lock(), __tl_unlock(), k, key_lock, keys, and td.
Referenced by tss_delete().
__pthread_tsd_run_dtors()
void __pthread_tsd_run_dtors ()
Definition at line 77 of file pthread_key_create.c.
 {
     pthread_t self = __pthread_self();
     int i, j;
     for (j=0; self->tsd_used && j<PTHREAD_DESTRUCTOR_ITERATIONS; j++) {
         __pthread_rwlock_rdlock(&key_lock);
         self->tsd_used = 0;
         for (i=0; i<PTHREAD_KEYS_MAX; i++) {
             void *val = self->tsd[i];
             void (*dtor)(void *) = keys[i];
             self->tsd[i] = 0;
             if (val && dtor && dtor != nodtor) {
                 __pthread_rwlock_unlock(&key_lock);
                 dtor(val);
                 __pthread_rwlock_rdlock(&key_lock);
             }
         }
         __pthread_rwlock_unlock(&key_lock);
     }
 }
References __pthread_rwlock_rdlock(), __pthread_rwlock_unlock(), __pthread_self, i, j, key_lock, keys, nodtor(), and val.
Referenced by __pthread_exit(), and cleanup_fromsig().
dummy_0()
static void dummy_0 (void) static
Definition at line 17 of file pthread_key_create.c.
 {
 }
nodtor()
static void nodtor (void * dummy) static
Definition at line 13 of file pthread_key_create.c.
 {
 }
Referenced by __pthread_key_create(), and __pthread_tsd_run_dtors().
weak_alias() [1/4]
weak_alias (__pthread_key_create , pthread_key_create)
weak_alias() [2/4]
weak_alias (__pthread_key_delete , pthread_key_delete)
weak_alias() [3/4]
weak_alias (dummy_0 , __tl_lock)
weak_alias() [4/4]
weak_alias (dummy_0 , __tl_unlock)
Variable Documentation
__pthread_tsd_main
void* __pthread_tsd_main[PTHREAD_KEYS_MAX] = { 0 }
Definition at line 5 of file pthread_key_create.c.
Referenced by __pthread_create(), and __pthread_key_create().
__pthread_tsd_size
volatile size_t __pthread_tsd_size = sizeof(void *) * PTHREAD_KEYS_MAX
Definition at line 4 of file pthread_key_create.c.
Referenced by __pthread_create().
key_lock
pthread_rwlock_t key_lock = PTHREAD_RWLOCK_INITIALIZER static
Definition at line 9 of file pthread_key_create.c.
Referenced by __pthread_key_atfork(), __pthread_key_create(), __pthread_key_delete(), and __pthread_tsd_run_dtors().
keys
void(* keys[PTHREAD_KEYS_MAX])(void *) (void *) static
Definition at line 7 of file pthread_key_create.c.
Referenced by __pthread_key_create(), __pthread_key_delete(), and __pthread_tsd_run_dtors().
next_key
pthread_key_t next_key static
Definition at line 11 of file pthread_key_create.c.
Referenced by __pthread_key_create().