Fennix: Userspace/musl/src/internal/libm.h File Reference
libm.h File Reference
#include <stdint.h>
#include <float.h>
#include <math.h>
#include <endian.h>
#include "fp_arch.h"
Macros
#define WANT_ROUNDING 1
#define WANT_SNAN 0
#define issignalingf_inline(x) 0
#define issignaling_inline(x) 0
#define TOINT_INTRINSICS 0
#define predict_true(x) (x)
#define predict_false(x) (x)
#define fp_barrierf fp_barrierf
#define fp_barrier fp_barrier
#define fp_barrierl fp_barrierl
#define fp_force_evalf fp_force_evalf
#define fp_force_eval fp_force_eval
#define fp_force_evall fp_force_evall
#define FORCE_EVAL(x)
#define asuint(f) ((union{float _f; uint32_t _i;}){f})._i
#define asfloat(i) ((union{uint32_t _i; float _f;}){i})._f
#define asuint64(f) ((union{double _f; uint64_t _i;}){f})._i
#define asdouble(i) ((union{uint64_t _i; double _f;}){i})._f
#define EXTRACT_WORDS(hi, lo, d)
#define GET_HIGH_WORD(hi, d)
#define GET_LOW_WORD(lo, d)
#define INSERT_WORDS(d, hi, lo)
#define SET_HIGH_WORD(d, hi) INSERT_WORDS(d, hi, (uint32_t)asuint64(d))
#define SET_LOW_WORD(d, lo) INSERT_WORDS(d, asuint64(d)>>32, lo)
#define GET_FLOAT_WORD(w, d)
#define SET_FLOAT_WORD(d, w)
Functions
static float eval_as_float (float x)
static double eval_as_double (double x)
static float fp_barrierf (float x)
static double fp_barrier (double x)
static long double fp_barrierl (long double x)
static void fp_force_evalf (float x)
static void fp_force_eval (double x)
static void fp_force_evall (long double x)
hidden int __rem_pio2_large (double *, double *, int, int, int)
hidden int __rem_pio2 (double, double *)
hidden double __sin (double, double, int)
hidden double __cos (double, double)
hidden double __tan (double, double, int)
hidden double __expo2 (double, double)
hidden int __rem_pio2f (float, double *)
hidden float __sindf (double)
hidden float __cosdf (double)
hidden float __tandf (double, int)
hidden float __expo2f (float, float)
hidden int __rem_pio2l (long double, long double *)
hidden long double __sinl (long double, long double, int)
hidden long double __cosl (long double, long double)
hidden long double __tanl (long double, long double, int)
hidden long double __polevll (long double, const long double *, int)
hidden long double __p1evll (long double, const long double *, int)
hidden double __lgamma_r (double, int *)
hidden float __lgammaf_r (float, int *)
hidden float __math_xflowf (uint32_t, float)
hidden float __math_uflowf (uint32_t)
hidden float __math_oflowf (uint32_t)
hidden float __math_divzerof (uint32_t)
hidden float __math_invalidf (float)
hidden double __math_xflow (uint32_t, double)
hidden double __math_uflow (uint32_t)
hidden double __math_oflow (uint32_t)
hidden double __math_divzero (uint32_t)
hidden double __math_invalid (double)
Variables
int __signgam
Macro Definition Documentation
asdouble
#define asdouble (i) ((union{uint64_t _i; double _f;}){i})._f
Definition at line 193 of file libm.h.
asfloat
#define asfloat (i) ((union{uint32_t _i; float _f;}){i})._f
Definition at line 191 of file libm.h.
asuint
#define asuint (f) ((union{float _f; uint32_t _i;}){f})._i
Definition at line 190 of file libm.h.
asuint64
#define asuint64 (f) ((union{double _f; uint64_t _i;}){f})._i
Definition at line 192 of file libm.h.
EXTRACT_WORDS
#define EXTRACT_WORDS (hi, lo, d)
Value:
do {                                              \
  uint64_t __u = asuint64(d);                     \
  (hi) = __u >> 32;                               \
  (lo) = (uint32_t)__u;                           \
} while (0)
Definition at line 195 of file libm.h.
FORCE_EVAL
#define FORCE_EVAL (x)
Value:
    do {                        \
    if (sizeof(x) == sizeof(float)) {         \
        fp_force_evalf(x);                \
    } else if (sizeof(x) == sizeof(double)) { \
        fp_force_eval(x);                 \
    } else {                                  \
        fp_force_evall(x);                \
    }                                         \
} while(0)
Definition at line 180 of file libm.h.
fp_barrier
#define fp_barrier fp_barrier
Definition at line 130 of file libm.h.
fp_barrierf
#define fp_barrierf fp_barrierf
Definition at line 121 of file libm.h.
fp_barrierl
#define fp_barrierl fp_barrierl
Definition at line 139 of file libm.h.
fp_force_eval
#define fp_force_eval fp_force_eval
Definition at line 163 of file libm.h.
fp_force_evalf
#define fp_force_evalf fp_force_evalf
Definition at line 154 of file libm.h.
fp_force_evall
#define fp_force_evall fp_force_evall
Definition at line 172 of file libm.h.
GET_FLOAT_WORD
#define GET_FLOAT_WORD (w, d)
Value:
do {                                              \
  (w) = asuint(d);                                \
} while (0)
Definition at line 223 of file libm.h.
GET_HIGH_WORD
#define GET_HIGH_WORD (hi, d)
Value:
do {                                              \
  (hi) = asuint64(d) >> 32;                       \
} while (0)
Definition at line 202 of file libm.h.
GET_LOW_WORD
#define GET_LOW_WORD (lo, d)
Value:
do {                                              \
  (lo) = (uint32_t)asuint64(d);                   \
} while (0)
Definition at line 207 of file libm.h.
INSERT_WORDS
#define INSERT_WORDS (d, hi, lo)
Value:
do {                                              \
  (d) = asdouble(((uint64_t)(hi)<<32) | (uint32_t)(lo)); \
} while (0)
Definition at line 212 of file libm.h.
issignaling_inline
#define issignaling_inline (x) 0
Definition at line 71 of file libm.h.
issignalingf_inline
#define issignalingf_inline (x) 0
Definition at line 70 of file libm.h.
predict_false
#define predict_false (x) (x)
Definition at line 96 of file libm.h.
predict_true
#define predict_true (x) (x)
Definition at line 95 of file libm.h.
SET_FLOAT_WORD
#define SET_FLOAT_WORD (d, w)
Value:
do {                                              \
  (d) = asfloat(w);                               \
} while (0)
Definition at line 228 of file libm.h.
SET_HIGH_WORD
#define SET_HIGH_WORD (d, hi) INSERT_WORDS(d, hi, (uint32_t)asuint64(d))
Definition at line 217 of file libm.h.
SET_LOW_WORD
#define SET_LOW_WORD (d, lo) INSERT_WORDS(d, asuint64(d)>>32, lo)
Definition at line 220 of file libm.h.
TOINT_INTRINSICS
#define TOINT_INTRINSICS 0
Definition at line 75 of file libm.h.
WANT_ROUNDING
#define WANT_ROUNDING 1
Definition at line 63 of file libm.h.
WANT_SNAN
#define WANT_SNAN 0
Definition at line 65 of file libm.h.
Function Documentation
__cos()
hidden double __cos (double x, double y)
Definition at line 61 of file __cos.c.
 {
     double_t hz,z,r,w;
     z  = x*x;
     w  = z*z;
     r  = z*(C1+z*(C2+z*C3)) + w*w*(C4+z*(C5+z*C6));
     hz = 0.5*z;
     w  = 1.0-hz;
     return w + (((1.0-w)-hz) + (z*r-x*y));
 }
References C1, C2, C3, C4, C5, C6, w, x, and y.
Referenced by cos(), sin(), sin_pi(), sincos(), and sinpi().
__cosdf()
hidden float __cosdf (double x)
Definition at line 26 of file __cosdf.c.
 {
     double_t r, w, z;
     /* Try to optimize for parallel evaluation as in __tandf.c. */
     z = x*x;
     w = z*z;
     r = C2+z*C3;
     return ((1.0+z*C0) + w*C1) + (w*z)*r;
 }
References C0, C1, C2, C3, w, and x.
Referenced by cosf(), sin_pi(), sincosf(), and sinf().
__cosl()
hidden long double __cosl (long double , long double)
__expo2()
hidden double __expo2 (double x, double sign)
Definition at line 8 of file __expo2.c.
 {
     double scale;
     /* note that k is odd and scale*scale overflows */
     INSERT_WORDS(scale, (uint32_t)(0x3ff + k/2) << 20, 0);
     /* exp(x - k ln2) * 2**(k-1) */
     /* in directed rounding correct sign before rounding or overflow is important */
     return exp(x - kln2) * (sign * scale) * scale;
 }
References exp, INSERT_WORDS, k, kln2, scale, and x.
Referenced by cosh(), and sinh().
__expo2f()
hidden float __expo2f (float x, float sign)
Definition at line 8 of file __expo2f.c.
 {
     float scale;
     /* note that k is odd and scale*scale overflows */
     SET_FLOAT_WORD(scale, (uint32_t)(0x7f + k/2) << 23);
     /* exp(x - k ln2) * 2**(k-1) */
     /* in directed rounding correct sign before rounding or overflow is important */
     return expf(x - kln2) * (sign * scale) * scale;
 }
References expf(), k, kln2, scale, SET_FLOAT_WORD, and x.
Referenced by coshf(), and sinhf().
__lgamma_r()
hidden double __lgamma_r (double x, int * signgamp)
Definition at line 170 of file lgamma_r.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t t,y,z,nadj,p,p1,p2,p3,q,r,w;
     uint32_t ix;
     int sign,i;
     /* purge off +-inf, NaN, +-0, tiny and negative arguments */
     *signgamp = 1;
     sign = u.i>>63;
     ix = u.i>>32 & 0x7fffffff;
     if (ix >= 0x7ff00000)
         return x*x;
     if (ix < (0x3ff-70)<<20) {  /* |x|<2**-70, return -log(|x|) */
         if(sign) {
             x = -x;
             *signgamp = -1;
         }
         return -log(x);
     }
     if (sign) {
         x = -x;
         t = sin_pi(x);
         if (t == 0.0) /* -integer */
             return 1.0/(x-x);
         if (t > 0.0)
             *signgamp = -1;
         else
             t = -t;
         nadj = log(pi/(t*x));
     }
     /* purge off 1 and 2 */
     if ((ix == 0x3ff00000 || ix == 0x40000000) && (uint32_t)u.i == 0)
         r = 0;
     /* for x < 2.0 */
     else if (ix < 0x40000000) {
         if (ix <= 0x3feccccc) {   /* lgamma(x) = lgamma(x+1)-log(x) */
             r = -log(x);
             if (ix >= 0x3FE76944) {
                 y = 1.0 - x;
                 i = 0;
             } else if (ix >= 0x3FCDA661) {
                 y = x - (tc-1.0);
                 i = 1;
             } else {
                 y = x;
                 i = 2;
             }
         } else {
             r = 0.0;
             if (ix >= 0x3FFBB4C3) {  /* [1.7316,2] */
                 y = 2.0 - x;
                 i = 0;
             } else if(ix >= 0x3FF3B4C4) {  /* [1.23,1.73] */
                 y = x - tc;
                 i = 1;
             } else {
                 y = x - 1.0;
                 i = 2;
             }
         }
         switch (i) {
         case 0:
             z = y*y;
             p1 = a0+z*(a2+z*(a4+z*(a6+z*(a8+z*a10))));
             p2 = z*(a1+z*(a3+z*(a5+z*(a7+z*(a9+z*a11)))));
             p = y*p1+p2;
             r += (p-0.5*y);
             break;
         case 1:
             z = y*y;
             w = z*y;
             p1 = t0+w*(t3+w*(t6+w*(t9 +w*t12)));    /* parallel comp */
             p2 = t1+w*(t4+w*(t7+w*(t10+w*t13)));
             p3 = t2+w*(t5+w*(t8+w*(t11+w*t14)));
             p = z*p1-(tt-w*(p2+y*p3));
             r += tf + p;
             break;
         case 2:
             p1 = y*(u0+y*(u1+y*(u2+y*(u3+y*(u4+y*u5)))));
             p2 = 1.0+y*(v1+y*(v2+y*(v3+y*(v4+y*v5))));
             r += -0.5*y + p1/p2;
         }
     } else if (ix < 0x40200000) {  /* x < 8.0 */
         i = (int)x;
         y = x - (double)i;
         p = y*(s0+y*(s1+y*(s2+y*(s3+y*(s4+y*(s5+y*s6))))));
         q = 1.0+y*(r1+y*(r2+y*(r3+y*(r4+y*(r5+y*r6)))));
         r = 0.5*y+p/q;
         z = 1.0;    /* lgamma(1+s) = log(s) + lgamma(s) */
         switch (i) {
         case 7: z *= y + 6.0;  /* FALLTHRU */
         case 6: z *= y + 5.0;  /* FALLTHRU */
         case 5: z *= y + 4.0;  /* FALLTHRU */
         case 4: z *= y + 3.0;  /* FALLTHRU */
         case 3: z *= y + 2.0;  /* FALLTHRU */
             r += log(z);
             break;
         }
     } else if (ix < 0x43900000) {  /* 8.0 <= x < 2**58 */
         t = log(x);
         z = 1.0/x;
         y = z*z;
         w = w0+z*(w1+y*(w2+y*(w3+y*(w4+y*(w5+y*w6)))));
         r = (x-0.5)*(t-1.0)+w;
     } else                         /* 2**58 <= x <= inf */
         r =  x*(log(x)-1.0);
     if (sign)
         r = nadj - r;
     return r;
 }
References a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9, f, i, log, p, pi, r1, r2, r3, r4, r5, r6, s0, s1, s2, s3, s4, s5, s6, sin_pi(), t, t0, t1, t10, t11, t12, t13, t14, t2, t3, t4, t5, t6, t7, t8, t9, tc, tf, tt, u0, u1, u2, u3, u4, u5, v1, v2, v3, v4, v5, w, w0, w1, w2, w3, w4, w5, w6, x, and y.
Referenced by lgamma().
__lgammaf_r()
hidden float __lgammaf_r (float x, int * signgamp)
Definition at line 105 of file lgammaf_r.c.
 {
     union {float f; uint32_t i;} u = {x};
     float t,y,z,nadj,p,p1,p2,p3,q,r,w;
     uint32_t ix;
     int i,sign;
     /* purge off +-inf, NaN, +-0, tiny and negative arguments */
     *signgamp = 1;
     sign = u.i>>31;
     ix = u.i & 0x7fffffff;
     if (ix >= 0x7f800000)
         return x*x;
     if (ix < 0x35000000) {  /* |x| < 2**-21, return -log(|x|) */
         if (sign) {
             *signgamp = -1;
             x = -x;
         }
         return -logf(x);
     }
     if (sign) {
         x = -x;
         t = sin_pi(x);
         if (t == 0.0f) /* -integer */
             return 1.0f/(x-x);
         if (t > 0.0f)
             *signgamp = -1;
         else
             t = -t;
         nadj = logf(pi/(t*x));
     }
     /* purge off 1 and 2 */
     if (ix == 0x3f800000 || ix == 0x40000000)
         r = 0;
     /* for x < 2.0 */
     else if (ix < 0x40000000) {
         if (ix <= 0x3f666666) {  /* lgamma(x) = lgamma(x+1)-log(x) */
             r = -logf(x);
             if (ix >= 0x3f3b4a20) {
                 y = 1.0f - x;
                 i = 0;
             } else if (ix >= 0x3e6d3308) {
                 y = x - (tc-1.0f);
                 i = 1;
             } else {
                 y = x;
                 i = 2;
             }
         } else {
             r = 0.0f;
             if (ix >= 0x3fdda618) {  /* [1.7316,2] */
                 y = 2.0f - x;
                 i = 0;
             } else if (ix >= 0x3F9da620) {  /* [1.23,1.73] */
                 y = x - tc;
                 i = 1;
             } else {
                 y = x - 1.0f;
                 i = 2;
             }
         }
         switch(i) {
         case 0:
             z = y*y;
             p1 = a0+z*(a2+z*(a4+z*(a6+z*(a8+z*a10))));
             p2 = z*(a1+z*(a3+z*(a5+z*(a7+z*(a9+z*a11)))));
             p = y*p1+p2;
             r += p - 0.5f*y;
             break;
         case 1:
             z = y*y;
             w = z*y;
             p1 = t0+w*(t3+w*(t6+w*(t9 +w*t12)));    /* parallel comp */
             p2 = t1+w*(t4+w*(t7+w*(t10+w*t13)));
             p3 = t2+w*(t5+w*(t8+w*(t11+w*t14)));
             p = z*p1-(tt-w*(p2+y*p3));
             r += (tf + p);
             break;
         case 2:
             p1 = y*(u0+y*(u1+y*(u2+y*(u3+y*(u4+y*u5)))));
             p2 = 1.0f+y*(v1+y*(v2+y*(v3+y*(v4+y*v5))));
             r += -0.5f*y + p1/p2;
         }
     } else if (ix < 0x41000000) {  /* x < 8.0 */
         i = (int)x;
         y = x - (float)i;
         p = y*(s0+y*(s1+y*(s2+y*(s3+y*(s4+y*(s5+y*s6))))));
         q = 1.0f+y*(r1+y*(r2+y*(r3+y*(r4+y*(r5+y*r6)))));
         r = 0.5f*y+p/q;
         z = 1.0f;    /* lgamma(1+s) = log(s) + lgamma(s) */
         switch (i) {
         case 7: z *= y + 6.0f;  /* FALLTHRU */
         case 6: z *= y + 5.0f;  /* FALLTHRU */
         case 5: z *= y + 4.0f;  /* FALLTHRU */
         case 4: z *= y + 3.0f;  /* FALLTHRU */
         case 3: z *= y + 2.0f;  /* FALLTHRU */
             r += logf(z);
             break;
         }
     } else if (ix < 0x5c800000) {  /* 8.0 <= x < 2**58 */
         t = logf(x);
         z = 1.0f/x;
         y = z*z;
         w = w0+z*(w1+y*(w2+y*(w3+y*(w4+y*(w5+y*w6)))));
         r = (x-0.5f)*(t-1.0f)+w;
     } else                         /* 2**58 <= x <= inf */
         r =  x*(logf(x)-1.0f);
     if (sign)
         r = nadj - r;
     return r;
 }
References a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9, f, i, logf(), p, pi, r1, r2, r3, r4, r5, r6, s0, s1, s2, s3, s4, s5, s6, sin_pi(), t, t0, t1, t10, t11, t12, t13, t14, t2, t3, t4, t5, t6, t7, t8, t9, tc, tf, tt, u0, u1, u2, u3, u4, u5, v1, v2, v3, v4, v5, w, w0, w1, w2, w3, w4, w5, w6, x, and y.
Referenced by lgammaf().
__math_divzero()
hidden double __math_divzero (uint32_t sign)
Definition at line 3 of file __math_divzero.c.
 {
     return fp_barrier(sign ? -1.0 : 1.0) / 0.0;
 }
References fp_barrier.
Referenced by log(), and log2().
__math_divzerof()
hidden float __math_divzerof (uint32_t sign)
Definition at line 3 of file __math_divzerof.c.
 {
     return fp_barrierf(sign ? -1.0f : 1.0f) / 0.0f;
 }
References fp_barrierf.
Referenced by log2f(), and logf().
__math_invalid()
hidden double __math_invalid (double x)
Definition at line 3 of file __math_invalid.c.
 {
     return (x - x) / (x - x);
 }
References x.
Referenced by log(), log2(), pow(), and sqrt().
__math_invalidf()
hidden float __math_invalidf (float x)
Definition at line 3 of file __math_invalidf.c.
 {
     return (x - x) / (x - x);
 }
References x.
Referenced by log2f(), logf(), powf(), and sqrtf().
__math_oflow()
hidden double __math_oflow (uint32_t sign)
Definition at line 3 of file __math_oflow.c.
 {
     return __math_xflow(sign, 0x1p769);
 }
References __math_xflow().
Referenced by exp(), exp2(), exp_inline(), and pow().
__math_oflowf()
hidden float __math_oflowf (uint32_t sign)
Definition at line 3 of file __math_oflowf.c.
 {
     return __math_xflowf(sign, 0x1p97f);
 }
References __math_xflowf().
Referenced by exp2f(), expf(), and powf().
__math_uflow()
hidden double __math_uflow (uint32_t sign)
Definition at line 3 of file __math_uflow.c.
 {
     return __math_xflow(sign, 0x1p-767);
 }
References __math_xflow().
Referenced by exp(), exp2(), exp_inline(), and pow().
__math_uflowf()
hidden float __math_uflowf (uint32_t sign)
Definition at line 3 of file __math_uflowf.c.
 {
     return __math_xflowf(sign, 0x1p-95f);
 }
References __math_xflowf().
Referenced by exp2f(), expf(), and powf().
__math_xflow()
hidden double __math_xflow (uint32_t sign, double y)
Definition at line 3 of file __math_xflow.c.
 {
     return eval_as_double(fp_barrier(sign ? -y : y) * y);
 }
References eval_as_double(), fp_barrier, and y.
Referenced by __math_oflow(), and __math_uflow().
__math_xflowf()
hidden float __math_xflowf (uint32_t sign, float y)
Definition at line 3 of file __math_xflowf.c.
 {
     return eval_as_float(fp_barrierf(sign ? -y : y) * y);
 }
References eval_as_float(), fp_barrierf, and y.
Referenced by __math_oflowf(), and __math_uflowf().
__p1evll()
hidden long double __p1evll (long double x, const long double * P, int n)
Definition at line 81 of file __polevll.c.
 {
     long double y;
     n -= 1;
     y = x + *P++;
     do {
         y = y * x + *P++;
     } while (--n);
     return y;
 }
References n, P, x, and y.
__polevll()
hidden long double __polevll (long double x, const long double * P, int n)
Definition at line 65 of file __polevll.c.
 {
     long double y;
     y = *P++;
     do {
         y = y * x + *P++;
     } while (--n);
     return y;
 }
References n, P, x, and y.
__rem_pio2()
hidden int __rem_pio2 (double x, double * y)
Definition at line 49 of file __rem_pio2.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t z,w,t,r,fn;
     double tx[3],ty[2];
     uint32_t ix;
     int sign, n, ex, ey, i;
     sign = u.i>>63;
     ix = u.i>>32 & 0x7fffffff;
     if (ix <= 0x400f6a7a) {  /* |x| ~<= 5pi/4 */
         if ((ix & 0xfffff) == 0x921fb)  /* |x| ~= pi/2 or 2pi/2 */
             goto medium;  /* cancellation -- use medium case */
         if (ix <= 0x4002d97c) {  /* |x| ~<= 3pi/4 */
             if (!sign) {
                 z = x - pio2_1;  /* one round good to 85 bits */
                 y[0] = z - pio2_1t;
                 y[1] = (z-y[0]) - pio2_1t;
                 return 1;
             } else {
                 z = x + pio2_1;
                 y[0] = z + pio2_1t;
                 y[1] = (z-y[0]) + pio2_1t;
                 return -1;
             }
         } else {
             if (!sign) {
                 z = x - 2*pio2_1;
                 y[0] = z - 2*pio2_1t;
                 y[1] = (z-y[0]) - 2*pio2_1t;
                 return 2;
             } else {
                 z = x + 2*pio2_1;
                 y[0] = z + 2*pio2_1t;
                 y[1] = (z-y[0]) + 2*pio2_1t;
                 return -2;
             }
         }
     }
     if (ix <= 0x401c463b) {  /* |x| ~<= 9pi/4 */
         if (ix <= 0x4015fdbc) {  /* |x| ~<= 7pi/4 */
             if (ix == 0x4012d97c)  /* |x| ~= 3pi/2 */
                 goto medium;
             if (!sign) {
                 z = x - 3*pio2_1;
                 y[0] = z - 3*pio2_1t;
                 y[1] = (z-y[0]) - 3*pio2_1t;
                 return 3;
             } else {
                 z = x + 3*pio2_1;
                 y[0] = z + 3*pio2_1t;
                 y[1] = (z-y[0]) + 3*pio2_1t;
                 return -3;
             }
         } else {
             if (ix == 0x401921fb)  /* |x| ~= 4pi/2 */
                 goto medium;
             if (!sign) {
                 z = x - 4*pio2_1;
                 y[0] = z - 4*pio2_1t;
                 y[1] = (z-y[0]) - 4*pio2_1t;
                 return 4;
             } else {
                 z = x + 4*pio2_1;
                 y[0] = z + 4*pio2_1t;
                 y[1] = (z-y[0]) + 4*pio2_1t;
                 return -4;
             }
         }
     }
     if (ix < 0x413921fb) {  /* |x| ~< 2^20*(pi/2), medium size */
 medium:
         /* rint(x/(pi/2)) */
         fn = (double_t)x*invpio2 + toint - toint;
         n = (int32_t)fn;
         r = x - fn*pio2_1;
         w = fn*pio2_1t;  /* 1st round, good to 85 bits */
         /* Matters with directed rounding. */
         if (predict_false(r - w < -pio4)) {
             n--;
             fn--;
             r = x - fn*pio2_1;
             w = fn*pio2_1t;
         } else if (predict_false(r - w > pio4)) {
             n++;
             fn++;
             r = x - fn*pio2_1;
             w = fn*pio2_1t;
         }
         y[0] = r - w;
         u.f = y[0];
         ey = u.i>>52 & 0x7ff;
         ex = ix>>20;
         if (ex - ey > 16) { /* 2nd round, good to 118 bits */
             t = r;
             w = fn*pio2_2;
             r = t - w;
             w = fn*pio2_2t - ((t-r)-w);
             y[0] = r - w;
             u.f = y[0];
             ey = u.i>>52 & 0x7ff;
             if (ex - ey > 49) {  /* 3rd round, good to 151 bits, covers all cases */
                 t = r;
                 w = fn*pio2_3;
                 r = t - w;
                 w = fn*pio2_3t - ((t-r)-w);
                 y[0] = r - w;
             }
         }
         y[1] = (r - y[0]) - w;
         return n;
     }
     /*
      * all other (large) arguments
      */
     if (ix >= 0x7ff00000) {  /* x is inf or NaN */
         y[0] = y[1] = x - x;
         return 0;
     }
     /* set z = scalbn(|x|,-ilogb(x)+23) */
     u.f = x;
     u.i &= (uint64_t)-1>>12;
     u.i |= (uint64_t)(0x3ff + 23)<<52;
     z = u.f;
     for (i=0; i < 2; i++) {
         tx[i] = (double)(int32_t)z;
         z     = (z-tx[i])*0x1p24;
     }
     tx[i] = z;
     /* skip zero terms, first term is non-zero */
     while (tx[i] == 0.0)
         i--;
     n = __rem_pio2_large(tx,ty,(int)(ix>>20)-(0x3ff+23),i+1,1);
     if (sign) {
         y[0] = -ty[0];
         y[1] = -ty[1];
         return -n;
     }
     y[0] = ty[0];
     y[1] = ty[1];
     return n;
 }
References __rem_pio2_large(), f, i, invpio2, n, pio2_1, pio2_1t, pio2_2, pio2_2t, pio2_3, pio2_3t, pio4, predict_false, t, toint, w, x, and y.
Referenced by cos(), sin(), sincos(), and tan().
__rem_pio2_large()
hidden int __rem_pio2_large (double * x, double * y, int e0, int nx, int prec)
Definition at line 273 of file __rem_pio2_large.c.
 {
     int32_t jz,jx,jv,jp,jk,carry,n,iq[20],i,j,k,m,q0,ih;
     double z,fw,f[20],fq[20],q[20];
     /* initialize jk*/
     jk = init_jk[prec];
     jp = jk;
     /* determine jx,jv,q0, note that 3>q0 */
     jx = nx-1;
     jv = (e0-3)/24;  if(jv<0) jv=0;
     q0 = e0-24*(jv+1);
     /* set up f[0] to f[jx+jk] where f[jx+jk] = ipio2[jv+jk] */
     j = jv-jx; m = jx+jk;
     for (i=0; i<=m; i++,j++)
         f[i] = j<0 ? 0.0 : (double)ipio2[j];
     /* compute q[0],q[1],...q[jk] */
     for (i=0; i<=jk; i++) {
         for (j=0,fw=0.0; j<=jx; j++)
             fw += x[j]*f[jx+i-j];
         q[i] = fw;
     }
     jz = jk;
 recompute:
     /* distill q[] into iq[] reversingly */
     for (i=0,j=jz,z=q[jz]; j>0; i++,j--) {
         fw    = (double)(int32_t)(0x1p-24*z);
         iq[i] = (int32_t)(z - 0x1p24*fw);
         z     = q[j-1]+fw;
     }
     /* compute n */
     z  = scalbn(z,q0);       /* actual value of z */
     z -= 8.0*floor(z*0.125); /* trim off integer >= 8 */
     n  = (int32_t)z;
     z -= (double)n;
     ih = 0;
     if (q0 > 0) {  /* need iq[jz-1] to determine n */
         i  = iq[jz-1]>>(24-q0); n += i;
         iq[jz-1] -= i<<(24-q0);
         ih = iq[jz-1]>>(23-q0);
     }
     else if (q0 == 0) ih = iq[jz-1]>>23;
     else if (z >= 0.5) ih = 2;
     if (ih > 0) {  /* q > 0.5 */
         n += 1; carry = 0;
         for (i=0; i<jz; i++) {  /* compute 1-q */
             j = iq[i];
             if (carry == 0) {
                 if (j != 0) {
                     carry = 1;
                     iq[i] = 0x1000000 - j;
                 }
             } else
                 iq[i] = 0xffffff - j;
         }
         if (q0 > 0) {  /* rare case: chance is 1 in 12 */
             switch(q0) {
             case 1:
                 iq[jz-1] &= 0x7fffff; break;
             case 2:
                 iq[jz-1] &= 0x3fffff; break;
             }
         }
         if (ih == 2) {
             z = 1.0 - z;
             if (carry != 0)
                 z -= scalbn(1.0,q0);
         }
     }
     /* check if recomputation is needed */
     if (z == 0.0) {
         j = 0;
         for (i=jz-1; i>=jk; i--) j |= iq[i];
         if (j == 0) {  /* need recomputation */
             for (k=1; iq[jk-k]==0; k++);  /* k = no. of terms needed */
             for (i=jz+1; i<=jz+k; i++) {  /* add q[jz+1] to q[jz+k] */
                 f[jx+i] = (double)ipio2[jv+i];
                 for (j=0,fw=0.0; j<=jx; j++)
                     fw += x[j]*f[jx+i-j];
                 q[i] = fw;
             }
             jz += k;
             goto recompute;
         }
     }
     /* chop off zero terms */
     if (z == 0.0) {
         jz -= 1;
         q0 -= 24;
         while (iq[jz] == 0) {
             jz--;
             q0 -= 24;
         }
     } else { /* break z into 24-bit if necessary */
         z = scalbn(z,-q0);
         if (z >= 0x1p24) {
             fw = (double)(int32_t)(0x1p-24*z);
             iq[jz] = (int32_t)(z - 0x1p24*fw);
             jz += 1;
             q0 += 24;
             iq[jz] = (int32_t)fw;
         } else
             iq[jz] = (int32_t)z;
     }
     /* convert integer "bit" chunk to floating-point value */
     fw = scalbn(1.0,q0);
     for (i=jz; i>=0; i--) {
         q[i] = fw*(double)iq[i];
         fw *= 0x1p-24;
     }
     /* compute PIo2[0,...,jp]*q[jz,...,0] */
     for(i=jz; i>=0; i--) {
         for (fw=0.0,k=0; k<=jp && k<=jz-i; k++)
             fw += PIo2[k]*q[i+k];
         fq[jz-i] = fw;
     }
     /* compress fq[] into y[] */
     switch(prec) {
     case 0:
         fw = 0.0;
         for (i=jz; i>=0; i--)
             fw += fq[i];
         y[0] = ih==0 ? fw : -fw;
         break;
     case 1:
     case 2:
         fw = 0.0;
         for (i=jz; i>=0; i--)
             fw += fq[i];
         // TODO: drop excess precision here once double_t is used
         fw = (double)fw;
         y[0] = ih==0 ? fw : -fw;
         fw = fq[0]-fw;
         for (i=1; i<=jz; i++)
             fw += fq[i];
         y[1] = ih==0 ? fw : -fw;
         break;
     case 3:  /* painful */
         for (i=jz; i>0; i--) {
             fw      = fq[i-1]+fq[i];
             fq[i]  += fq[i-1]-fw;
             fq[i-1] = fw;
         }
         for (i=jz; i>1; i--) {
             fw      = fq[i-1]+fq[i];
             fq[i]  += fq[i-1]-fw;
             fq[i-1] = fw;
         }
         for (fw=0.0,i=jz; i>=2; i--)
             fw += fq[i];
         if (ih==0) {
             y[0] =  fq[0]; y[1] =  fq[1]; y[2] =  fw;
         } else {
             y[0] = -fq[0]; y[1] = -fq[1]; y[2] = -fw;
         }
     }
     return n&7;
 }
References f, floor, i, init_jk, ipio2, j, k, n, PIo2, prec, scalbn, x, and y.
Referenced by __rem_pio2(), and __rem_pio2f().
__rem_pio2f()
hidden int __rem_pio2f (float x, double * y)
Definition at line 43 of file __rem_pio2f.c.
 {
     union {float f; uint32_t i;} u = {x};
     double tx[1],ty[1];
     double_t fn;
     uint32_t ix;
     int n, sign, e0;
     ix = u.i & 0x7fffffff;
     /* 25+53 bit pi is good enough for medium size */
     if (ix < 0x4dc90fdb) {  /* |x| ~< 2^28*(pi/2), medium size */
         /* Use a specialized rint() to get fn. */
         fn = (double_t)x*invpio2 + toint - toint;
         n  = (int32_t)fn;
         *y = x - fn*pio2_1 - fn*pio2_1t;
         /* Matters with directed rounding. */
         if (predict_false(*y < -pio4)) {
             n--;
             fn--;
             *y = x - fn*pio2_1 - fn*pio2_1t;
         } else if (predict_false(*y > pio4)) {
             n++;
             fn++;
             *y = x - fn*pio2_1 - fn*pio2_1t;
         }
         return n;
     }
     if(ix>=0x7f800000) {  /* x is inf or NaN */
         *y = x-x;
         return 0;
     }
     /* scale x into [2^23, 2^24-1] */
     sign = u.i>>31;
     e0 = (ix>>23) - (0x7f+23);  /* e0 = ilogb(|x|)-23, positive */
     u.i = ix - (e0<<23);
     tx[0] = u.f;
     n  =  __rem_pio2_large(tx,ty,e0,1,0);
     if (sign) {
         *y = -ty[0];
         return -n;
     }
     *y = ty[0];
     return n;
 }
References __rem_pio2_large(), f, i, invpio2, n, pio2_1, pio2_1t, pio4, predict_false, toint, x, and y.
Referenced by cosf(), sincosf(), sinf(), and tanf().
__rem_pio2l()
hidden int __rem_pio2l (long double , long double *)
__sin()
hidden double __sin (double x, double y, int iy)
Definition at line 52 of file __sin.c.
 {
     double_t z,r,v,w;
     z = x*x;
     w = z*z;
     r = S2 + z*(S3 + z*S4) + z*w*(S5 + z*S6);
     v = z*x;
     if (iy == 0)
         return x + v*(S1 + z*r);
     else
         return x - ((z*(0.5*y - v*r) - y) - v*S1);
 }
References S1, S2, S3, S4, S5, S6, w, x, and y.
Referenced by cos(), sin(), sin_pi(), sincos(), and sinpi().
__sindf()
hidden float __sindf (double x)
Definition at line 26 of file __sindf.c.
 {
     double_t r, s, w, z;
     /* Try to optimize for parallel evaluation as in __tandf.c. */
     z = x*x;
     w = z*z;
     r = S3 + z*S4;
     s = z*x;
     return (x + s*(S1 + z*S2)) + s*w*r;
 }
References s, S1, S2, S3, S4, w, and x.
Referenced by cosf(), sin_pi(), sincosf(), and sinf().
__sinl()
hidden long double __sinl (long double , long double , int)
__tan()
hidden double __tan (double x, double y, int odd)
Definition at line 66 of file __tan.c.
 {
     double_t z, r, v, w, s, a;
     double w0, a0;
     uint32_t hx;
     int big, sign;
     GET_HIGH_WORD(hx,x);
     big = (hx&0x7fffffff) >= 0x3FE59428; /* |x| >= 0.6744 */
     if (big) {
         sign = hx>>31;
         if (sign) {
             x = -x;
             y = -y;
         }
         x = (pio4 - x) + (pio4lo - y);
         y = 0.0;
     }
     z = x * x;
     w = z * z;
     /*
      * Break x^5*(T[1]+x^2*T[2]+...) into
      * x^5(T[1]+x^4*T[3]+...+x^20*T[11]) +
      * x^5(x^2*(T[2]+x^4*T[4]+...+x^22*[T12]))
      */
     r = T[1] + w*(T[3] + w*(T[5] + w*(T[7] + w*(T[9] + w*T[11]))));
     v = z*(T[2] + w*(T[4] + w*(T[6] + w*(T[8] + w*(T[10] + w*T[12])))));
     s = z * x;
     r = y + z*(s*(r + v) + y) + s*T[0];
     w = x + r;
     if (big) {
         s = 1 - 2*odd;
         v = s - 2.0 * (x + (r - w*w/(w + s)));
         return sign ? -v : v;
     }
     if (!odd)
         return w;
     /* -1.0/(x+r) has up to 2ulp error, so compute it accurately */
     w0 = w;
     SET_LOW_WORD(w0, 0);
     v = r - (w0 - x);       /* w0+v = r+x */
     a0 = a = -1.0 / w;
     SET_LOW_WORD(a0, 0);
     return a0 + a*(1.0 + a0*w0 + a0*v);
 }
References a0, GET_HIGH_WORD, pio4, pio4lo, s, SET_LOW_WORD, T, w, w0, x, and y.
Referenced by tan().
__tandf()
hidden float __tandf (double x, int odd)
Definition at line 28 of file __tandf.c.
 {
     double_t z,r,w,s,t,u;
     z = x*x;
     /*
      * Split up the polynomial into small independent terms to give
      * opportunities for parallel evaluation.  The chosen splitting is
      * micro-optimized for Athlons (XP, X64).  It costs 2 multiplications
      * relative to Horner's method on sequential machines.
      *
      * We add the small terms from lowest degree up for efficiency on
      * non-sequential machines (the lowest degree terms tend to be ready
      * earlier).  Apart from this, we don't care about order of
      * operations, and don't need to to care since we have precision to
      * spare.  However, the chosen splitting is good for accuracy too,
      * and would give results as accurate as Horner's method if the
      * small terms were added from highest degree down.
      */
     r = T[4] + z*T[5];
     t = T[2] + z*T[3];
     w = z*z;
     s = z*x;
     u = T[0] + z*T[1];
     r = (x + s*u) + (s*w)*(t + w*r);
     return odd ? -1.0/r : r;
 }
References s, t, T, w, and x.
Referenced by tanf().
__tanl()
hidden long double __tanl (long double , long double , int)
eval_as_double()
static double eval_as_double (double x) inline static
Definition at line 110 of file libm.h.
 {
     double y = x;
     return y;
 }
References x, and y.
Referenced by __math_xflow(), exp(), exp2(), exp2_inline(), exp2f(), exp_inline(), expf(), log(), log2(), specialcase(), and sqrt().
eval_as_float()
static float eval_as_float (float x) inline static
Definition at line 104 of file libm.h.
 {
     float y = x;
     return y;
 }
References x, and y.
Referenced by __math_xflowf(), exp2_inline(), exp2f(), expf(), log2f(), logf(), and sqrtf().
fp_barrier()
static double fp_barrier (double x) inline static
Definition at line 131 of file libm.h.
 {
     volatile double y = x;
     return y;
 }
References x, and y.
fp_barrierf()
static float fp_barrierf (float x) inline static
Definition at line 122 of file libm.h.
 {
     volatile float y = x;
     return y;
 }
References x, and y.
fp_barrierl()
static long double fp_barrierl (long double x) inline static
Definition at line 140 of file libm.h.
 {
     volatile long double y = x;
     return y;
 }
References x, and y.
fp_force_eval()
static void fp_force_eval (double x) inline static
Definition at line 164 of file libm.h.
 {
     volatile double y;
     y = x;
 }
References x, and y.
fp_force_evalf()
static void fp_force_evalf (float x) inline static
Definition at line 155 of file libm.h.
 {
     volatile float y;
     y = x;
 }
References x, and y.
fp_force_evall()
static void fp_force_evall (long double x) inline static
Definition at line 173 of file libm.h.
 {
     volatile long double y;
     y = x;
 }
References x, and y.
Variable Documentation
__signgam
int __signgam extern
Definition at line 4 of file signgam.c.
Referenced by lgamma(), lgammaf(), and lgammal().