Fennix: Drivers/library/crt/crt0.c File Reference
crt0.c File Reference
#include <driver.h>
#include <errno.h>
Macros
#define API_MajorRequiredVersion 0
#define API_MinorRequiredVersion 0
#define API_PatchRequiredVersion 0
Typedefs
typedef void(* CallPtr) (void)
Functions
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
int DriverProbe ()
void __IdentifyDriver (dev_t ID, int(*GetDriverInfo)(dev_t, const char *, const char *, const char *, const char *, const char *))
int _entry ()
int _final ()
int _start (__driverAPI *__API)
Variables
__driverAPI * API
CallPtr __init_array_start [0]
CallPtr __init_array_end [0]
CallPtr __fini_array_start [0]
CallPtr __fini_array_end [0]
Macro Definition Documentation
API_MajorRequiredVersion
#define API_MajorRequiredVersion 0
Definition at line 54 of file crt0.c.
API_MinorRequiredVersion
#define API_MinorRequiredVersion 0
Definition at line 55 of file crt0.c.
API_PatchRequiredVersion
#define API_PatchRequiredVersion 0
Definition at line 56 of file crt0.c.
Typedef Documentation
CallPtr
typedef void(* CallPtr) (void)
Definition at line 32 of file crt0.c.
Function Documentation
__IdentifyDriver()
void __IdentifyDriver (dev_t ID, int(*)(dev_t, const char *, const char *, const char *, const char *, const char *) GetDriverInfo)
Referenced by _start().
_entry()
int _entry ()
Definition at line 36 of file crt0.c.
 {
     for (CallPtr *func = __init_array_start; func != __init_array_end; func++)
         (*func)();
     return DriverEntry();
 }
References __init_array_end, __init_array_start, and DriverEntry().
Referenced by _start().
_final()
int _final ()
Definition at line 44 of file crt0.c.
 {
     int err = DriverFinal();
     for (CallPtr *func = __fini_array_start; func != __fini_array_end; func++)
         (*func)();
     return err;
 }
References __fini_array_end, __fini_array_start, DriverFinal(), and err().
Referenced by _start().
_start()
int _start (__driverAPI * __API)
Definition at line 58 of file crt0.c.
 {
     if (unlikely(__API == NULL))
         return -EINVAL;
     if (unlikely(__API->APIVersion.Major != API_MajorRequiredVersion ||
                  __API->APIVersion.Minor != API_MinorRequiredVersion ||
                  __API->APIVersion.Patch != API_PatchRequiredVersion))
         return -EPROTO;
     if (unlikely(__API->RegisterFunction == NULL))
         return -ENOSYS;
     if (unlikely(DriverEntry == NULL ||
                  DriverFinal == NULL ||
                  DriverPanic == NULL ||
                  DriverProbe == NULL ||
                  __IdentifyDriver == NULL))
         return -EFAULT;
     API = __API;
     __API->RegisterFunction(__API->MajorID, _entry, _drf_Entry);
     __API->RegisterFunction(__API->MajorID, _final, _drf_Final);
     __API->RegisterFunction(__API->MajorID, DriverPanic, _drf_Panic);
     __API->RegisterFunction(__API->MajorID, DriverProbe, _drf_Probe);
     __IdentifyDriver(__API->MajorID, __API->GetDriverInfo);
     return 0;
 }
References __IdentifyDriver(), _drf_Entry, _drf_Final, _drf_Panic, _drf_Probe, _entry(), _final(), API, API_MajorRequiredVersion, API_MinorRequiredVersion, API_PatchRequiredVersion, __driverAPI::APIVersion, DriverEntry(), DriverFinal(), DriverPanic(), DriverProbe(), EFAULT, EINVAL, ENOSYS, EPROTO, __driverAPI::GetDriverInfo, __driverAPI::MajorID, NULL, __driverAPI::RegisterFunction, and unlikely.
DriverEntry()
int DriverEntry ()
A device may fail, but if the other one works, we can still use it.
This is the main function of the driver. This function is called when the driver is loaded. This function should be used to initialize the PCI device and allocate resources.
If we have another driver using the PS/2 mouse, we need to override its interrupt handler.
Definition at line 22 of file main.c.
 { return cxx_Initialize(); }
References Absolute(), Driver::CreateKernelThread(), cxx_Initialize(), ddt_Mouse, DebugLog, DisplayScaleThread(), dst_id, DualChannel, EFAULT, ENODEV, InitializeKeyboard(), InitializeMouse(), InterruptHandler(), KPrint(), Log(), MasterInterruptHandler(), MESSAGE_TCLO, MessageClose(), MouseDevID, NULL, OpenMessageChannel(), Driver::OverrideInterruptHandler(), PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_ENABLE_PORT_1, PS2_CMD_ENABLE_PORT_2, PS2_CMD_READ_CONFIG, PS2_CMD_TEST_CONTROLLER, PS2_CMD_TEST_PORT_1, PS2_CMD_TEST_PORT_2, PS2_CMD_WRITE_CONFIG, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_ENABLE_DATA_REPORTING, PS2_MOUSE_CMD_SET_DEFAULTS, PS2_TEST_PASSED, PS2ClearOutputBuffer(), PS2ReadData(), PS2WriteCommand(), PS2WriteData(), PS2_CONFIGURATION::Raw, Driver::RegisterInputDevice(), Driver::RegisterInterruptHandler(), SlaveInterruptHandler(), status, tb_ctx, test, and ToolboxSupported.
Referenced by _entry(), and _start().
DriverFinal()
int DriverFinal ()
This function is called when the driver is unloaded. This function should be used to stop the PCI device and free any resources.
Definition at line 23 of file main.c.
 { return cxx_Finalize(); }
References cxx_Finalize(), ddt_Mouse, dst_id, FinalizeKeyboard(), FinalizeMouse(), FreeMemory(), Driver::KillThread(), MasterInterruptHandler(), MessageClose(), MouseDevID, PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, PS2WriteCommand(), PS2WriteData(), Relative(), SlaveInterruptHandler(), tb_ctx, ToolboxContext::TCLOChannel, ToolboxSupported, Driver::UnregisterInputDevice(), and Driver::UnregisterInterruptHandler().
Referenced by _final(), and _start().
DriverPanic()
int DriverPanic ()
This function is called when the kernel panics. This function should be used to stop the driver from receiving interrupts or anything else that is not safe to do when the kernel panics.
Definition at line 24 of file main.c.
 { return cxx_Panic(); }
References cxx_Panic(), PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, PS2WriteCommand(), PS2WriteData(), and Relative().
Referenced by _start().
DriverProbe()
int DriverProbe ()
This is the first function that is called when the driver is loaded. We can use this function to test if the driver is compatible with the hardware. Like if we have a specific PCI device or if we have a specific CPU feature.
Return 0 if the driver is compatible with the hardware. Otherwise, we return a value from the errno.h header.
Note: In this function you cannot use variables that have constructors or destructors. Before DriverEntry, the constructors are called and after DriverFinalize, the destructors are called.
Definition at line 25 of file main.c.
 { return cxx_Probe(); }
References __intStub(), cxx_Probe(), DetectPS2Keyboard(), DetectPS2Mouse(), Device1ID, Device2ID, ENODEV, GetPS2DeviceName(), IsATAPresent(), IsKeyboard(), IsMouse(), IsVMwareBackdoorAvailable(), KPrint(), Log(), Driver::RegisterInterruptHandler(), and Driver::UnregisterAllInterruptHandlers().
Referenced by _start().
Variable Documentation
__fini_array_end
CallPtr __fini_array_end[0]
Definition at line 34 of file crt0.c.
Referenced by _final().
__fini_array_start
CallPtr __fini_array_start[0] (void) extern
Definition at line 162 of file dynlink.c.
Referenced by _final().
__init_array_end
CallPtr __init_array_end[0] (void)
Definition at line 33 of file crt0.c.
Referenced by _entry().
__init_array_start
CallPtr __init_array_start[0] (void) extern
Definition at line 162 of file dynlink.c.
Referenced by _entry().
API
__driverAPI* API extern
Definition at line 23 of file base.c.
Referenced by _start().