Fennix Userspace: Userspace/apps/base/busybox/libbb/endofname.c File Reference
endofname.c File Reference
#include "libbb.h"
Macros
#define is_name(c) ((c) == '_' || isalpha((unsigned char)(c)))
#define is_in_name(c) ((c) == '_' || isalnum((unsigned char)(c)))
Functions
const char *FAST_FUNC endofname (const char *name)
Macro Definition Documentation
is_in_name
#define is_in_name (c) ((c) == '_' || isalnum((unsigned char)(c)))
Definition at line 14 of file endofname.c.
is_name
#define is_name (c) ((c) == '_' || isalpha((unsigned char)(c)))
Definition at line 13 of file endofname.c.
Function Documentation
endofname()
const char* FAST_FUNC endofname (const char * name)
Definition at line 17 of file endofname.c.
 {
     if (!is_name(*name))
         return name;
     while (*++name) {
         if (!is_in_name(*name))
             break;
     }
     return name;
 }
References is_in_name, and is_name.
Referenced by done_word(), evaluate_string(), goodname(), is_assignment(), isassignment(), parse_stream(), setvar(), shell_builtin_read(), and showvars().