Fennix: Userspace/musl/include/stropts.h File Reference
stropts.h File Reference
Data Structures
struct bandinfo
struct strbuf
struct strpeek
struct strfdinsert
struct strioctl
struct strrecvfd
struct str_mlist
struct str_list
Macros
#define __SID ('S' << 8)
#define I_NREAD (__SID | 1)
#define I_PUSH (__SID | 2)
#define I_POP (__SID | 3)
#define I_LOOK (__SID | 4)
#define I_FLUSH (__SID | 5)
#define I_SRDOPT (__SID | 6)
#define I_GRDOPT (__SID | 7)
#define I_STR (__SID | 8)
#define I_SETSIG (__SID | 9)
#define I_GETSIG (__SID |10)
#define I_FIND (__SID |11)
#define I_LINK (__SID |12)
#define I_UNLINK (__SID |13)
#define I_PEEK (__SID |15)
#define I_FDINSERT (__SID |16)
#define I_SENDFD (__SID |17)
#define I_RECVFD (__SID |14)
#define I_SWROPT (__SID |19)
#define I_GWROPT (__SID |20)
#define I_LIST (__SID |21)
#define I_PLINK (__SID |22)
#define I_PUNLINK (__SID |23)
#define I_FLUSHBAND (__SID |28)
#define I_CKBAND (__SID |29)
#define I_GETBAND (__SID |30)
#define I_ATMARK (__SID |31)
#define I_SETCLTIME (__SID |32)
#define I_GETCLTIME (__SID |33)
#define I_CANPUT (__SID |34)
#define FMNAMESZ 8
#define FLUSHR 0x01
#define FLUSHW 0x02
#define FLUSHRW 0x03
#define FLUSHBAND 0x04
#define S_INPUT 0x0001
#define S_HIPRI 0x0002
#define S_OUTPUT 0x0004
#define S_MSG 0x0008
#define S_ERROR 0x0010
#define S_HANGUP 0x0020
#define S_RDNORM 0x0040
#define S_WRNORM S_OUTPUT
#define S_RDBAND 0x0080
#define S_WRBAND 0x0100
#define S_BANDURG 0x0200
#define RS_HIPRI 0x01
#define RNORM 0x0000
#define RMSGD 0x0001
#define RMSGN 0x0002
#define RPROTDAT 0x0004
#define RPROTDIS 0x0008
#define RPROTNORM 0x0010
#define RPROTMASK 0x001C
#define SNDZERO 0x001
#define SNDPIPE 0x002
#define ANYMARK 0x01
#define LASTMARK 0x02
#define MUXID_ALL (-1)
#define MSG_HIPRI 0x01
#define MSG_ANY 0x02
#define MSG_BAND 0x04
#define MORECTL 1
#define MOREDATA 2
Functions
int isastream (int)
int ioctl (int, int,...)
Data Structure Documentation
bandinfo
struct bandinfo
Definition at line 84 of file stropts.h.
Data Fields
int bi_flag
unsigned char bi_pri
strbuf
struct strbuf
Definition at line 89 of file stropts.h.
Data Fields
char * buf
int len
int maxlen
strpeek
struct strpeek
Definition at line 95 of file stropts.h.
Data Fields
struct strbuf ctlbuf
struct strbuf databuf
unsigned flags
strfdinsert
struct strfdinsert
Definition at line 101 of file stropts.h.
Data Fields
struct strbuf ctlbuf
struct strbuf databuf
int fildes
unsigned flags
int offset
strioctl
struct strioctl
Definition at line 109 of file stropts.h.
Data Fields
int ic_cmd
char * ic_dp
int ic_len
int ic_timout
strrecvfd
struct strrecvfd
Definition at line 116 of file stropts.h.
Data Fields
char __fill[8]
int fd
int gid
int uid
str_mlist
struct str_mlist
Definition at line 123 of file stropts.h.
Data Fields
char l_name[FMNAMESZ+1]
str_list
struct str_list
Definition at line 127 of file stropts.h.
Data Fields
struct str_mlist * sl_modlist
int sl_nmods
Macro Definition Documentation
__SID
#define __SID ('S' << 8)
Definition at line 8 of file stropts.h.
ANYMARK
#define ANYMARK 0x01
Definition at line 72 of file stropts.h.
FLUSHBAND
#define FLUSHBAND 0x04
Definition at line 45 of file stropts.h.
FLUSHR
#define FLUSHR 0x01
Definition at line 42 of file stropts.h.
FLUSHRW
#define FLUSHRW 0x03
Definition at line 44 of file stropts.h.
FLUSHW
#define FLUSHW 0x02
Definition at line 43 of file stropts.h.
FMNAMESZ
#define FMNAMESZ 8
Definition at line 40 of file stropts.h.
I_ATMARK
#define I_ATMARK (__SID |31)
Definition at line 35 of file stropts.h.
I_CANPUT
#define I_CANPUT (__SID |34)
Definition at line 38 of file stropts.h.
I_CKBAND
#define I_CKBAND (__SID |29)
Definition at line 33 of file stropts.h.
I_FDINSERT
#define I_FDINSERT (__SID |16)
Definition at line 24 of file stropts.h.
I_FIND
#define I_FIND (__SID |11)
Definition at line 20 of file stropts.h.
I_FLUSH
#define I_FLUSH (__SID | 5)
Definition at line 14 of file stropts.h.
I_FLUSHBAND
#define I_FLUSHBAND (__SID |28)
Definition at line 32 of file stropts.h.
I_GETBAND
#define I_GETBAND (__SID |30)
Definition at line 34 of file stropts.h.
I_GETCLTIME
#define I_GETCLTIME (__SID |33)
Definition at line 37 of file stropts.h.
I_GETSIG
#define I_GETSIG (__SID |10)
Definition at line 19 of file stropts.h.
I_GRDOPT
#define I_GRDOPT (__SID | 7)
Definition at line 16 of file stropts.h.
I_GWROPT
#define I_GWROPT (__SID |20)
Definition at line 28 of file stropts.h.
I_LINK
#define I_LINK (__SID |12)
Definition at line 21 of file stropts.h.
I_LIST
#define I_LIST (__SID |21)
Definition at line 29 of file stropts.h.
I_LOOK
#define I_LOOK (__SID | 4)
Definition at line 13 of file stropts.h.
I_NREAD
#define I_NREAD (__SID | 1)
Definition at line 10 of file stropts.h.
I_PEEK
#define I_PEEK (__SID |15)
Definition at line 23 of file stropts.h.
I_PLINK
#define I_PLINK (__SID |22)
Definition at line 30 of file stropts.h.
I_POP
#define I_POP (__SID | 3)
Definition at line 12 of file stropts.h.
I_PUNLINK
#define I_PUNLINK (__SID |23)
Definition at line 31 of file stropts.h.
I_PUSH
#define I_PUSH (__SID | 2)
Definition at line 11 of file stropts.h.
I_RECVFD
#define I_RECVFD (__SID |14)
Definition at line 26 of file stropts.h.
I_SENDFD
#define I_SENDFD (__SID |17)
Definition at line 25 of file stropts.h.
I_SETCLTIME
#define I_SETCLTIME (__SID |32)
Definition at line 36 of file stropts.h.
I_SETSIG
#define I_SETSIG (__SID | 9)
Definition at line 18 of file stropts.h.
I_SRDOPT
#define I_SRDOPT (__SID | 6)
Definition at line 15 of file stropts.h.
I_STR
#define I_STR (__SID | 8)
Definition at line 17 of file stropts.h.
I_SWROPT
#define I_SWROPT (__SID |19)
Definition at line 27 of file stropts.h.
I_UNLINK
#define I_UNLINK (__SID |13)
Definition at line 22 of file stropts.h.
LASTMARK
#define LASTMARK 0x02
Definition at line 73 of file stropts.h.
MORECTL
#define MORECTL 1
Definition at line 81 of file stropts.h.
MOREDATA
#define MOREDATA 2
Definition at line 82 of file stropts.h.
MSG_ANY
#define MSG_ANY 0x02
Definition at line 78 of file stropts.h.
MSG_BAND
#define MSG_BAND 0x04
Definition at line 79 of file stropts.h.
MSG_HIPRI
#define MSG_HIPRI 0x01
Definition at line 77 of file stropts.h.
MUXID_ALL
#define MUXID_ALL (-1)
Definition at line 75 of file stropts.h.
RMSGD
#define RMSGD 0x0001
Definition at line 62 of file stropts.h.
RMSGN
#define RMSGN 0x0002
Definition at line 63 of file stropts.h.
RNORM
#define RNORM 0x0000
Definition at line 61 of file stropts.h.
RPROTDAT
#define RPROTDAT 0x0004
Definition at line 64 of file stropts.h.
RPROTDIS
#define RPROTDIS 0x0008
Definition at line 65 of file stropts.h.
RPROTMASK
#define RPROTMASK 0x001C
Definition at line 67 of file stropts.h.
RPROTNORM
#define RPROTNORM 0x0010
Definition at line 66 of file stropts.h.
RS_HIPRI
#define RS_HIPRI 0x01
Definition at line 59 of file stropts.h.
S_BANDURG
#define S_BANDURG 0x0200
Definition at line 57 of file stropts.h.
S_ERROR
#define S_ERROR 0x0010
Definition at line 51 of file stropts.h.
S_HANGUP
#define S_HANGUP 0x0020
Definition at line 52 of file stropts.h.
S_HIPRI
#define S_HIPRI 0x0002
Definition at line 48 of file stropts.h.
S_INPUT
#define S_INPUT 0x0001
Definition at line 47 of file stropts.h.
S_MSG
#define S_MSG 0x0008
Definition at line 50 of file stropts.h.
S_OUTPUT
#define S_OUTPUT 0x0004
Definition at line 49 of file stropts.h.
S_RDBAND
#define S_RDBAND 0x0080
Definition at line 55 of file stropts.h.
S_RDNORM
#define S_RDNORM 0x0040
Definition at line 53 of file stropts.h.
S_WRBAND
#define S_WRBAND 0x0100
Definition at line 56 of file stropts.h.
S_WRNORM
#define S_WRNORM S_OUTPUT
Definition at line 54 of file stropts.h.
SNDPIPE
#define SNDPIPE 0x002
Definition at line 70 of file stropts.h.
SNDZERO
#define SNDZERO 0x001
Definition at line 69 of file stropts.h.
Function Documentation
ioctl()
int ioctl (int fd, int req, ...)
Definition at line 128 of file ioctl.c.
 {
     void *arg;
     va_list ap;
     va_start(ap, req);
     arg = va_arg(ap, void *);
     va_end(ap);
     int r = __syscall(SYS_ioctl, fd, req, arg);
     if (SIOCGSTAMP != SIOCGSTAMP_OLD && req && r==-ENOTTY) {
         for (int i=0; i<sizeof compat_map/sizeof *compat_map; i++) {
             if (compat_map[i].new_req != req) continue;
             union {
                 long long align;
                 char buf[256];
             } u;
             convert_ioctl_struct(&compat_map[i], u.buf, arg, W);
             r = __syscall(SYS_ioctl, fd, compat_map[i].old_req, u.buf);
             if (r<0) break;
             convert_ioctl_struct(&compat_map[i], u.buf, arg, R);
             break;
         }
     }
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ap, buf, compat_map, convert_ioctl_struct(), ENOTTY, fd, i, R, SIOCGSTAMP, SIOCGSTAMP_OLD, va_arg, va_end, va_start, and W.
Referenced by _rl_get_screen_size(), _rl_input_available(), _rl_nchars_available(), arp_del(), bb_BLKGETSIZE_sectors(), bb_ioctl_or_warn(), bb_xioctl(), beep_main(), blockdev_main(), change_attributes(), console_init(), conspy_main(), copy_file(), cttyhack_main(), d6_read_interface(), del_loop(), eject_cdrom(), find_free_vtno(), flash_eraseall_main(), flashcp_main(), get_console_fd_or_die(), get_free_loop(), get_kernel_geometry(), get_label_uuid(), get_new_window_size(), get_sectorsize(), get_terminal_width_height(), get_tty_settings(), get_tty_state(), getty_main(), i2c_smbus_access(), if_fetch(), if_indextoname(), if_nametoindex(), init_exec(), init_wsize(), input_avail(), ioctl_on_skfd(), ioctl_or_perror(), ioctl_or_perror_and_die(), is_whole_disk(), list_attributes(), loadkmap_main(), login_tty(), mkfs_vfat_main(), nameif_main(), nbdclient_main(), nchars_avail(), network_ioctl(), not_vt_fd(), openpty(), query_loop(), resize_main(), rl_gather_tyi(), rl_restart_output(), rl_stop_output(), rl_tty_status(), safe_write_to_pty_decode_iac(), script_main(), serial_ctl(), set_loopdev_params(), set_new_line_discipline(), set_tty_settings(), set_tty_state(), set_winsize(), setsid_main(), slattach_main(), sockatmark(), start_shell_in_child(), sulogin_main(), tcflow(), tcflush(), tcgetattr(), tcgetpgrp(), tcgetsid(), tcsendbreak(), tcsetattr(), tcsetpgrp(), ttgetattr(), ttsetattr(), ttysize_main(), unlockpt(), vfork_child(), and vlock_main().
isastream()
int isastream (int fd)
Definition at line 4 of file isastream.c.
 {
     return fcntl(fd, F_GETFD) < 0 ? -1 : 0;
 }
References F_GETFD, fcntl(), and fd.