Fennix Userspace: Userspace/musl/src/temp/mkostemps.c File Reference
mkostemps.c File Reference
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
Macros
#define _BSD_SOURCE
Functions
int __mkostemps (char *template, int len, int flags)
weak_alias (__mkostemps, mkostemps)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file mkostemps.c.
Function Documentation
__mkostemps()
int __mkostemps (char * template, int len, int flags)
Definition at line 8 of file mkostemps.c.
 {
     size_t l = strlen(template);
     if (l<6 || len>l-6 || memcmp(template+l-len-6, "XXXXXX", 6)) {
         errno = EINVAL;
         return -1;
     }
     flags -= flags & O_ACCMODE;
     int fd, retries = 100;
     do {
         __randname(template+l-len-6);
         if ((fd = open(template, flags | O_RDWR | O_CREAT | O_EXCL, 0600))>=0)
             return fd;
     } while (--retries && errno == EEXIST);
     memcpy(template+l-len-6, "XXXXXX", 6);
     return -1;
 }
References __randname(), EEXIST, EINVAL, errno, fd, flags, l, memcmp(), memcpy(), O_ACCMODE, O_CREAT, O_EXCL, O_RDWR, open(), and strlen().
Referenced by mkostemp(), mkstemp(), and mkstemps().
weak_alias()
weak_alias (__mkostemps , mkostemps)