Fennix: Userspace/apps/base/busybox/shell/cttyhack.c File Reference
cttyhack.c File Reference
#include "libbb.h"
Data Structures
struct vt_stat
struct serial_struct
Enumerations
enum { VT_GETSTATE = 0x5603 }
Functions
int cttyhack_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
vt_stat
struct vt_stat
Definition at line 27 of file fgconsole.c.
Data Fields
unsigned short v_active
unsigned short v_signal
unsigned short v_state
serial_struct
struct serial_struct
Definition at line 188 of file setserial.c.
Data Fields
int baud_base
unsigned short close_delay
unsigned short closing_wait
unsigned short closing_wait2
int custom_divisor
int flags
int hub6
char io_type
unsigned long iomap_base
unsigned char * iomem_base
unsigned short iomem_reg_shift
int irq
int line
unsigned int port
unsigned int port_high
int reserved[1]
char reserved_char[1]
int type
int xmit_fifo_size
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VT_GETSTATE
Definition at line 78 of file cttyhack.c.
 { VT_GETSTATE = 0x5603 }; /* get global vt state info */
Function Documentation
cttyhack_main()
int cttyhack_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 104 of file cttyhack.c.
 {
     int fd;
     char console[sizeof(int)*3 + 16];
     union {
         struct vt_stat vt;
         struct serial_struct sr;
         char paranoia[sizeof(struct serial_struct) * 3];
     } u;
     strcpy(console, "/dev/tty");
     fd = open(console, O_RDWR);
     if (fd < 0) {
         /* We don't have ctty (or don't have "/dev/tty" node...) */
         do {
 #ifdef __linux__
             /* Note that this method does not use _stdin_.
              * Thus, "cttyhack </dev/something" can't be used.
              * However, this method is more reliable than
              * TIOCGSERIAL check, which assumes that all
              * serial lines follow /dev/ttySn convention -
              * which is not always the case.
              * Therefore, we use this method first:
              */
             int s = open_read_close("/sys/class/tty/console/active",
                 console + 5, sizeof(console) - 5);
             if (s > 0) {
                 char *last;
                 /* Found active console via sysfs (Linux 2.6.38+).
                  * It looks like "[tty0 ]ttyS0\n" so zap the newline:
                  */
                 console[4 + s] = '\0';
                 /* If there are multiple consoles,
                  * take the last one:
                  */
                 last = strrchr(console + 5, ' ');
                 if (last)
                     overlapping_strcpy(console + 5, last + 1);
                 break;
             }
             if (ioctl(0, VT_GETSTATE, &u.vt) == 0) {
                 /* this is linux virtual tty */
                 sprintf(console + 8, "S%u" + 1, (int)u.vt.v_active);
                 break;
             }
 #endif
 #ifdef TIOCGSERIAL
             if (ioctl(0, TIOCGSERIAL, &u.sr) == 0) {
                 /* this is a serial console; assuming it is named /dev/ttySn */
                 sprintf(console + 8, "S%u", (int)u.sr.line);
                 break;
             }
 #endif
             /* nope, could not find it */
             console[0] = '\0';
         } while (0);
     }
     argv++;
     if (!argv[0]) {
         if (!console[0])
             return EXIT_FAILURE;
         puts(console);
         return EXIT_SUCCESS;
     }
     if (fd < 0) {
         fd = open_or_warn(console, O_RDWR);
         if (fd < 0)
             goto ret;
     }
     //bb_error_msg("switching to '%s'", console);
     dup2(fd, 0);
     dup2(fd, 1);
     dup2(fd, 2);
     while (fd > 2)
         close(fd--);
     /* Some other session may have it as ctty,
      * try to steal it from them:
      */
     ioctl(0, TIOCSCTTY, 1);
  ret:
     BB_EXECVP_or_die(argv);
 }
References argv, BB_EXECVP_or_die(), close(), dup2(), EXIT_FAILURE, EXIT_SUCCESS, fd, ioctl(), last, O_RDWR, open(), open_or_warn(), open_read_close(), overlapping_strcpy(), puts(), s, sprintf(), strcpy, strrchr(), TIOCGSERIAL, TIOCSCTTY, and VT_GETSTATE.