Fennix: Userspace/apps/base/busybox/networking/netstat.c File Reference
netstat.c File Reference
#include "libbb.h"
#include "inet_common.h"
Data Structures
struct prg_node
struct globals
struct inet_params
union inet_params.localaddr
union inet_params.remaddr
Macros
#define NETSTAT_OPTS
#define NETSTAT_CONNECTED 0x01
#define NETSTAT_LISTENING 0x02
#define NETSTAT_NUMERIC 0x04
#define NETSTAT_TCP 0x10
#define NETSTAT_UDP 0x20
#define NETSTAT_RAW 0x40
#define NETSTAT_UNIX 0x80
#define NETSTAT_ALLPROTO (NETSTAT_TCP|NETSTAT_UDP|NETSTAT_RAW|NETSTAT_UNIX)
#define SO_ACCEPTCON (1<<16) /* performed a listen */
#define SO_WAITDATA (1<<17) /* wait data to read */
#define SO_NOSPACE (1<<18) /* no space to write */
#define ADDR_NORMAL_WIDTH 23
#define ADDR_WIDE 51 /* INET6_ADDRSTRLEN + 5 for the port number */
#define FMT_NET_CONN_DATA "%s %6lu %6lu %-23s %-23s %-12s"
#define FMT_NET_CONN_HEADER "\nProto Recv-Q Send-Q %-23s %-23s State %s\n"
#define PROGNAME_WIDTH 20
#define PROGNAME_WIDTH_STR "20"
#define PROGNAME_BANNER "PID/Program name "
#define PRG_HASH_SIZE 211
#define G (*ptr_to_globals)
#define flags (G.flags)
#define prg_cache_loaded (G.prg_cache_loaded)
#define prg_hash (G.prg_hash)
#define progname_banner ""
#define INIT_G()
#define prg_cache_clear() ((void)0)
#define NOT_NULL_ADDR(A) (A.sin.sin_addr.s_addr)
Enumerations
enum {
OPT_sock_listen = 1 << 0 , OPT_sock_all = 1 << 1 , OPT_extended = 1 << 2 , OPT_noresolve = 1 << 3 ,
OPT_sock_tcp = 1 << 4 , OPT_sock_udp = 1 << 5 , OPT_sock_raw = 1 << 6 , OPT_sock_unix = 1 << 7 ,
OPTBIT_x = 7 , OPT_route = IF_ROUTE((1 << OPTBIT_ROUTE)) + 0 , OPT_wide = IF_FEATURE_NETSTAT_WIDE((1 << OPTBIT_WIDE)) + 0 , OPT_prg = IF_FEATURE_NETSTAT_PRG((1 << OPTBIT_PRG)) + 0
}
enum {
TCP_ESTABLISHED = 1 , TCP_SYN_SENT , TCP_SYN_RECV , TCP_FIN_WAIT1 ,
TCP_FIN_WAIT2 , TCP_TIME_WAIT , TCP_CLOSE , TCP_CLOSE_WAIT ,
TCP_LAST_ACK , TCP_LISTEN , TCP_CLOSING
}
enum socket_state {
SS_FREE = 0 , SS_UNCONNECTED , SS_CONNECTING , SS_CONNECTED ,
SS_DISCONNECTING
}
Functions
static void build_ipv4_addr (char *local_addr, struct sockaddr_in *localaddr)
static const char * get_sname (int port, const char *proto, int numeric)
static char * ip_port_str (struct sockaddr *addr, int port, const char *proto, int numeric)
static int scan_inet_proc_line (struct inet_params *param, char *line)
static void print_inet_line (struct inet_params *param, const char *state_str, const char *proto, int is_connected)
static int FAST_FUNC tcp_do_one (char *line)
static int FAST_FUNC udp_do_one (char *line)
static int FAST_FUNC raw_do_one (char *line)
static int FAST_FUNC unix_do_one (char *line)
static void do_info (const char *file, int FAST_FUNC(*proc)(char *))
int netstat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char *const tcp_state[] ALIGN_PTR
Data Structure Documentation
prg_node
struct prg_node
Definition at line 165 of file netstat.c.
Data Fields
long inode
char name[PROGNAME_WIDTH]
struct prg_node * next
inet_params
struct inet_params
Definition at line 410 of file netstat.c.
Data Fields
unsigned long inode
int local_port
union inet_params localaddr
int rem_port
union inet_params remaddr
unsigned long rxq
int state
unsigned long txq
int uid
inet_params.localaddr
union inet_params.localaddr
Definition at line 412 of file netstat.c.
Data Fields
struct sockaddr sa
struct sockaddr_in sin
inet_params.remaddr
union inet_params.remaddr
Definition at line 412 of file netstat.c.
Data Fields
struct sockaddr sa
struct sockaddr_in sin
Macro Definition Documentation
ADDR_NORMAL_WIDTH
#define ADDR_NORMAL_WIDTH 23
Definition at line 144 of file netstat.c.
ADDR_WIDE
#define ADDR_WIDE 51 /* INET6_ADDRSTRLEN + 5 for the port number */
Definition at line 151 of file netstat.c.
flags
#define flags (G.flags)
Definition at line 187 of file netstat.c.
FMT_NET_CONN_DATA
#define FMT_NET_CONN_DATA "%s %6lu %6lu %-23s %-23s %-12s"
Definition at line 156 of file netstat.c.
FMT_NET_CONN_HEADER
#define FMT_NET_CONN_HEADER "\nProto Recv-Q Send-Q %-23s %-23s State %s\n"
Definition at line 157 of file netstat.c.
G
#define G (*ptr_to_globals)
Definition at line 186 of file netstat.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    flags = NETSTAT_CONNECTED | NETSTAT_ALLPROTO; \
} while (0)
Definition at line 195 of file netstat.c.
NETSTAT_ALLPROTO
#define NETSTAT_ALLPROTO (NETSTAT_TCP|NETSTAT_UDP|NETSTAT_RAW|NETSTAT_UNIX)
Definition at line 100 of file netstat.c.
NETSTAT_CONNECTED
#define NETSTAT_CONNECTED 0x01
Definition at line 92 of file netstat.c.
NETSTAT_LISTENING
#define NETSTAT_LISTENING 0x02
Definition at line 93 of file netstat.c.
NETSTAT_NUMERIC
#define NETSTAT_NUMERIC 0x04
Definition at line 94 of file netstat.c.
NETSTAT_OPTS
#define NETSTAT_OPTS
Value:
    "laentuwx" \
    IF_ROUTE(               "r") \
    IF_FEATURE_NETSTAT_WIDE("W") \
    IF_FEATURE_NETSTAT_PRG( "p")
Definition at line 69 of file netstat.c.
NETSTAT_RAW
#define NETSTAT_RAW 0x40
Definition at line 98 of file netstat.c.
NETSTAT_TCP
#define NETSTAT_TCP 0x10
Definition at line 96 of file netstat.c.
NETSTAT_UDP
#define NETSTAT_UDP 0x20
Definition at line 97 of file netstat.c.
NETSTAT_UNIX
#define NETSTAT_UNIX 0x80
Definition at line 99 of file netstat.c.
NOT_NULL_ADDR
#define NOT_NULL_ADDR (A) (A.sin.sin_addr.s_addr)
Definition at line 505 of file netstat.c.
prg_cache_clear
#define prg_cache_clear () ((void)0)
Definition at line 352 of file netstat.c.
prg_cache_loaded
#define prg_cache_loaded (G.prg_cache_loaded)
Definition at line 188 of file netstat.c.
prg_hash
#define prg_hash (G.prg_hash)
Definition at line 189 of file netstat.c.
PRG_HASH_SIZE
#define PRG_HASH_SIZE 211
Definition at line 171 of file netstat.c.
PROGNAME_BANNER
#define PROGNAME_BANNER "PID/Program name "
Definition at line 163 of file netstat.c.
progname_banner
#define progname_banner ""
Definition at line 193 of file netstat.c.
PROGNAME_WIDTH
#define PROGNAME_WIDTH 20
Definition at line 160 of file netstat.c.
PROGNAME_WIDTH_STR
#define PROGNAME_WIDTH_STR "20"
Definition at line 161 of file netstat.c.
SO_ACCEPTCON
#define SO_ACCEPTCON (1<<16) /* performed a listen */
Definition at line 140 of file netstat.c.
SO_NOSPACE
#define SO_NOSPACE (1<<18) /* no space to write */
Definition at line 142 of file netstat.c.
SO_WAITDATA
#define SO_WAITDATA (1<<17) /* wait data to read */
Definition at line 141 of file netstat.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_sock_listen
OPT_sock_all
OPT_extended
OPT_noresolve
OPT_sock_tcp
OPT_sock_udp
OPT_sock_raw
OPT_sock_unix
OPTBIT_x
OPT_route
OPT_wide
OPT_prg
Definition at line 74 of file netstat.c.
      {
     OPT_sock_listen = 1 << 0, // l
     OPT_sock_all    = 1 << 1, // a
     OPT_extended    = 1 << 2, // e
     OPT_noresolve   = 1 << 3, // n
     OPT_sock_tcp    = 1 << 4, // t
     OPT_sock_udp    = 1 << 5, // u
     OPT_sock_raw    = 1 << 6, // w
     OPT_sock_unix   = 1 << 7, // x
     OPTBIT_x        = 7,
     IF_ROUTE(               OPTBIT_ROUTE,)
     IF_FEATURE_NETSTAT_WIDE(OPTBIT_WIDE ,)
     IF_FEATURE_NETSTAT_PRG( OPTBIT_PRG  ,)
     OPT_route       = IF_ROUTE(               (1 << OPTBIT_ROUTE)) + 0, // r
     OPT_wide        = IF_FEATURE_NETSTAT_WIDE((1 << OPTBIT_WIDE )) + 0, // W
     OPT_prg         = IF_FEATURE_NETSTAT_PRG( (1 << OPTBIT_PRG  )) + 0, // p
 };
anonymous enum
anonymous enum
Enumerator
TCP_ESTABLISHED
TCP_SYN_SENT
TCP_SYN_RECV
TCP_FIN_WAIT1
TCP_FIN_WAIT2
TCP_TIME_WAIT
TCP_CLOSE
TCP_CLOSE_WAIT
TCP_LAST_ACK
TCP_LISTEN
TCP_CLOSING
Definition at line 103 of file netstat.c.
      {
     TCP_ESTABLISHED = 1,
     TCP_SYN_SENT,
     TCP_SYN_RECV,
     TCP_FIN_WAIT1,
     TCP_FIN_WAIT2,
     TCP_TIME_WAIT,
     TCP_CLOSE,
     TCP_CLOSE_WAIT,
     TCP_LAST_ACK,
     TCP_LISTEN,
     TCP_CLOSING, /* now a valid state */
 };
socket_state
enum socket_state
Enumerator
SS_FREE
SS_UNCONNECTED
SS_CONNECTING
SS_CONNECTED
SS_DISCONNECTING
Definition at line 132 of file netstat.c.
              {
     SS_FREE = 0,     /* not allocated                */
     SS_UNCONNECTED,  /* unconnected to any socket    */
     SS_CONNECTING,   /* in process of connecting     */
     SS_CONNECTED,    /* connected to socket          */
     SS_DISCONNECTING /* in process of disconnecting  */
 } socket_state;
Function Documentation
build_ipv4_addr()
static void build_ipv4_addr (char * local_addr, struct sockaddr_in * localaddr) static
Definition at line 373 of file netstat.c.
 {
     sscanf(local_addr, "%X", &localaddr->sin_addr.s_addr);
     localaddr->sin_family = AF_INET;
 }
References AF_INET, in_addr::s_addr, sockaddr_in::sin_addr, sockaddr_in::sin_family, and sscanf().
Referenced by scan_inet_proc_line().
do_info()
static void do_info (const char * file, int FAST_FUNC(*)(char *) proc) static
Definition at line 660 of file netstat.c.
 {
     int lnr;
     FILE *procinfo;
     char *buffer;
     /* _stdin is just to save "r" param */
     procinfo = fopen_or_warn_stdin(file);
     if (procinfo == NULL) {
         return;
     }
     lnr = 0;
     /* Why xmalloc_fgets_str? because it doesn't stop on NULs */
     while ((buffer = xmalloc_fgets_str(procinfo, "\n")) != NULL) {
         /* line 0 is skipped */
         if (lnr && proc(buffer))
             bb_error_msg("%s: bogus data on line %d", file, lnr + 1);
         lnr++;
         free(buffer);
     }
     fclose(procinfo);
 }
References bb_error_msg(), buffer, fclose(), fopen_or_warn_stdin(), free, NULL, and xmalloc_fgets_str().
Referenced by netstat_main().
get_sname()
static const char* get_sname (int port, const char * proto, int numeric) static
Definition at line 379 of file netstat.c.
 {
     if (!port)
         return "*";
     if (!numeric) {
         struct servent *se = getservbyport(port, proto);
         if (se)
             return se->s_name;
     }
     /* hummm, we may return static buffer here!! */
     return itoa(ntohs(port));
 }
References getservbyport(), itoa, ntohs(), port, and servent::s_name.
Referenced by ip_port_str().
ip_port_str()
static char* ip_port_str (struct sockaddr * addr, int port, const char * proto, int numeric) static
Definition at line 392 of file netstat.c.
 {
     char *host, *host_port;
     /* Code which used "*" for INADDR_ANY is removed: it's ambiguous
      * in IPv6, while "0.0.0.0" is not. */
     host = NULL;
     if (!numeric)
         host = xmalloc_sockaddr2host_noport(addr);
     if (!host)
         host = xmalloc_sockaddr2dotted_noport(addr);
     host_port = xasprintf("%s:%s", host, get_sname(htons(port), proto, numeric));
     free(host);
     return host_port;
 }
References addr, free, get_sname(), htons(), NULL, port, xasprintf(), xmalloc_sockaddr2dotted_noport(), and xmalloc_sockaddr2host_noport().
Referenced by print_inet_line().
netstat_main()
int netstat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 684 of file netstat.c.
 {
     unsigned opt;
     INIT_G();
     /* Option string must match NETSTAT_xxx constants */
     opt = getopt32(argv, NETSTAT_OPTS);
     if (opt & OPT_sock_listen) { // -l
         flags &= ~NETSTAT_CONNECTED;
         flags |= NETSTAT_LISTENING;
     }
     if (opt & OPT_sock_all) flags |= NETSTAT_LISTENING | NETSTAT_CONNECTED; // -a
     //if (opt & OPT_extended) // -e
     if (opt & OPT_noresolve) flags |= NETSTAT_NUMERIC; // -n
     //if (opt & OPT_sock_tcp) // -t: NETSTAT_TCP
     //if (opt & OPT_sock_udp) // -u: NETSTAT_UDP
     //if (opt & OPT_sock_raw) // -w: NETSTAT_RAW
     //if (opt & OPT_sock_unix) // -x: NETSTAT_UNIX
 #if ENABLE_ROUTE
     if (opt & OPT_route) { // -r
         bb_displayroutes(flags & NETSTAT_NUMERIC, !(opt & OPT_extended));
         return 0;
     }
 #endif
 #if ENABLE_FEATURE_NETSTAT_WIDE
     G.addr_width = ADDR_NORMAL_WIDTH;
     if (opt & OPT_wide) { // -W
         G.addr_width = ADDR_WIDE;
     }
 #endif
 #if ENABLE_FEATURE_NETSTAT_PRG
     progname_banner = "";
     if (opt & OPT_prg) { // -p
         progname_banner = PROGNAME_BANNER;
         prg_cache_load();
     }
 #endif
     opt &= NETSTAT_ALLPROTO;
     if (opt) {
         flags &= ~NETSTAT_ALLPROTO;
         flags |= opt;
     }
     if (flags & (NETSTAT_TCP|NETSTAT_UDP|NETSTAT_RAW)) {
         printf("Active Internet connections "); /* xxx */
         if ((flags & (NETSTAT_LISTENING|NETSTAT_CONNECTED)) == (NETSTAT_LISTENING|NETSTAT_CONNECTED))
             printf("(servers and established)");
         else if (flags & NETSTAT_LISTENING)
             printf("(only servers)");
         else
             printf("(w/o servers)");
         printf(FMT_NET_CONN_HEADER,
                 IF_FEATURE_NETSTAT_WIDE(G.addr_width,) "Local Address",
                 IF_FEATURE_NETSTAT_WIDE(G.addr_width,) "Foreign Address",
                 progname_banner
         );
     }
     if (flags & NETSTAT_TCP) {
         do_info("/proc/net/tcp", tcp_do_one);
 #if ENABLE_FEATURE_IPV6
         do_info("/proc/net/tcp6", tcp_do_one);
 #endif
     }
     if (flags & NETSTAT_UDP) {
         do_info("/proc/net/udp", udp_do_one);
 #if ENABLE_FEATURE_IPV6
         do_info("/proc/net/udp6", udp_do_one);
 #endif
     }
     if (flags & NETSTAT_RAW) {
         do_info("/proc/net/raw", raw_do_one);
 #if ENABLE_FEATURE_IPV6
         do_info("/proc/net/raw6", raw_do_one);
 #endif
     }
     if (flags & NETSTAT_UNIX) {
         printf("Active UNIX domain sockets ");
         if ((flags & (NETSTAT_LISTENING|NETSTAT_CONNECTED)) == (NETSTAT_LISTENING|NETSTAT_CONNECTED))
             printf("(servers and established)");
         else if (flags & NETSTAT_LISTENING)
             printf("(only servers)");
         else
             printf("(w/o servers)");
         printf("\nProto RefCnt Flags       Type       State         I-Node %sPath\n", progname_banner);
         do_info("/proc/net/unix", unix_do_one);
     }
     prg_cache_clear();
     return 0;
 }
References ADDR_NORMAL_WIDTH, ADDR_WIDE, argv, bb_displayroutes(), do_info(), flags, FMT_NET_CONN_HEADER, G, getopt32(), INIT_G, NETSTAT_ALLPROTO, NETSTAT_CONNECTED, NETSTAT_LISTENING, NETSTAT_NUMERIC, NETSTAT_OPTS, NETSTAT_RAW, NETSTAT_TCP, NETSTAT_UDP, NETSTAT_UNIX, opt, OPT_extended, OPT_noresolve, OPT_prg, OPT_route, OPT_sock_all, OPT_sock_listen, OPT_wide, prg_cache_clear, printf, PROGNAME_BANNER, progname_banner, raw_do_one(), tcp_do_one(), udp_do_one(), and unix_do_one().
print_inet_line()
static void print_inet_line (struct inet_params * param, const char * state_str, const char * proto, int is_connected) static
Definition at line 455 of file netstat.c.
 {
     if ((is_connected && (flags & NETSTAT_CONNECTED))
      || (!is_connected && (flags & NETSTAT_LISTENING))
     ) {
         char *l = ip_port_str(
                 &param->localaddr.sa, param->local_port,
                 proto, flags & NETSTAT_NUMERIC);
         char *r = ip_port_str(
                 &param->remaddr.sa, param->rem_port,
                 proto, flags & NETSTAT_NUMERIC);
         printf(FMT_NET_CONN_DATA,
             proto, param->rxq, param->txq,
             IF_FEATURE_NETSTAT_WIDE(G.addr_width,) l,
             IF_FEATURE_NETSTAT_WIDE(G.addr_width,) r,
             state_str);
 #if ENABLE_FEATURE_NETSTAT_PRG
         if (option_mask32 & OPT_prg)
             printf("%."PROGNAME_WIDTH_STR"s", prg_cache_get(param->inode));
 #endif
         bb_putchar('\n');
         free(l);
         free(r);
     }
 }
References bb_putchar(), flags, FMT_NET_CONN_DATA, free, G, ip_port_str(), l, NETSTAT_CONNECTED, NETSTAT_LISTENING, NETSTAT_NUMERIC, OPT_prg, option_mask32, param, printf, and PROGNAME_WIDTH_STR.
Referenced by raw_do_one(), tcp_do_one(), and udp_do_one().
raw_do_one()
static int FAST_FUNC raw_do_one (char * line) static
Definition at line 533 of file netstat.c.
 {
     int have_remaddr;
     struct inet_params param;
     if (scan_inet_proc_line(&param, line))
         return 1;
     have_remaddr = NOT_NULL_ADDR(param.remaddr);
     print_inet_line(&param, itoa(param.state), "raw", have_remaddr);
     return 0;
 }
References itoa, NOT_NULL_ADDR, param, print_inet_line(), and scan_inet_proc_line().
Referenced by netstat_main().
scan_inet_proc_line()
static int scan_inet_proc_line (struct inet_params * param, char * line) static
Definition at line 422 of file netstat.c.
 {
     int num;
     /* IPv6 /proc files use 32-char hex representation
      * of IPv6 address, followed by :PORT_IN_HEX
      */
     char local_addr[33], rem_addr[33]; /* 32 + 1 for NUL */
     num = sscanf(line,
             "%*d: %32[0-9A-Fa-f]:%X "
             "%32[0-9A-Fa-f]:%X %X "
             "%lX:%lX %*X:%*X "
             "%*X %d %*d %lu ",
             local_addr, &param->local_port,
             rem_addr, &param->rem_port, &param->state,
             &param->txq, &param->rxq,
             &param->uid, &param->inode);
     if (num < 9) {
         return 1; /* error */
     }
     if (strlen(local_addr) > 8) {
 #if ENABLE_FEATURE_IPV6
         build_ipv6_addr(local_addr, &param->localaddr.sin6);
         build_ipv6_addr(rem_addr, &param->remaddr.sin6);
 #endif
     } else {
         build_ipv4_addr(local_addr, &param->localaddr.sin);
         build_ipv4_addr(rem_addr, &param->remaddr.sin);
     }
     return 0;
 }
References build_ipv4_addr(), num, param, sscanf(), and strlen.
Referenced by raw_do_one(), tcp_do_one(), and udp_do_one().
tcp_do_one()
static int FAST_FUNC tcp_do_one (char * line) static
Definition at line 482 of file netstat.c.
 {
     struct inet_params param;
     memset(&param, 0, sizeof(param));
     if (scan_inet_proc_line(&param, line))
         return 1;
     print_inet_line(&param, tcp_state[param.state], "tcp", param.rem_port);
     return 0;
 }
References memset, param, print_inet_line(), and scan_inet_proc_line().
Referenced by netstat_main().
udp_do_one()
static int FAST_FUNC udp_do_one (char * line) static
Definition at line 508 of file netstat.c.
 {
     int have_remaddr;
     const char *state_str;
     struct inet_params param;
     memset(&param, 0, sizeof(param)); /* otherwise we display garbage IPv6 scope_ids */
     if (scan_inet_proc_line(&param, line))
         return 1;
     state_str = "UNKNOWN";
     switch (param.state) {
     case TCP_ESTABLISHED:
         state_str = "ESTABLISHED";
         break;
     case TCP_CLOSE:
         state_str = "";
         break;
     }
     have_remaddr = NOT_NULL_ADDR(param.remaddr);
     print_inet_line(&param, state_str, "udp", have_remaddr);
     return 0;
 }
References memset, NOT_NULL_ADDR, param, print_inet_line(), scan_inet_proc_line(), TCP_CLOSE, and TCP_ESTABLISHED.
Referenced by netstat_main().
unix_do_one()
static int FAST_FUNC unix_do_one (char * line) static
Definition at line 546 of file netstat.c.
 {
     unsigned long refcnt, proto, unix_flags;
     unsigned long inode;
     int type, state;
     int num, path_ofs;
     const char *ss_proto, *ss_state, *ss_type;
     char ss_flags[32];
     /* 2.6.15 may report lines like "... @/tmp/fam-user-^@^@^@^@^@^@^@..."
      * Other users report long lines filled by NUL bytes.
      * (those ^@ are NUL bytes too). We see them as empty lines. */
     if (!line[0])
         return 0;
     path_ofs = 0; /* paranoia */
     num = sscanf(line, "%*p: %lX %lX %lX %X %X %lu %n",
             &refcnt, &proto, &unix_flags, &type, &state, &inode, &path_ofs);
     if (num < 6) {
         return 1; /* error */
     }
     if ((flags & (NETSTAT_LISTENING|NETSTAT_CONNECTED)) != (NETSTAT_LISTENING|NETSTAT_CONNECTED)) {
         if ((state == SS_UNCONNECTED) && (unix_flags & SO_ACCEPTCON)) {
             if (!(flags & NETSTAT_LISTENING))
                 return 0;
         } else {
             if (!(flags & NETSTAT_CONNECTED))
                 return 0;
         }
     }
     switch (proto) {
         case 0:
             ss_proto = "unix";
             break;
         default:
             ss_proto = "??";
     }
     switch (type) {
         case SOCK_STREAM:
             ss_type = "STREAM";
             break;
         case SOCK_DGRAM:
             ss_type = "DGRAM";
             break;
         case SOCK_RAW:
             ss_type = "RAW";
             break;
         case SOCK_RDM:
             ss_type = "RDM";
             break;
         case SOCK_SEQPACKET:
             ss_type = "SEQPACKET";
             break;
         default:
             ss_type = "UNKNOWN";
     }
     switch (state) {
         case SS_FREE:
             ss_state = "FREE";
             break;
         case SS_UNCONNECTED:
             /*
              * Unconnected sockets may be listening
              * for something.
              */
             if (unix_flags & SO_ACCEPTCON) {
                 ss_state = "LISTENING";
             } else {
                 ss_state = "";
             }
             break;
         case SS_CONNECTING:
             ss_state = "CONNECTING";
             break;
         case SS_CONNECTED:
             ss_state = "CONNECTED";
             break;
         case SS_DISCONNECTING:
             ss_state = "DISCONNECTING";
             break;
         default:
             ss_state = "UNKNOWN";
     }
     strcpy(ss_flags, "[ ");
     if (unix_flags & SO_ACCEPTCON)
         strcat(ss_flags, "ACC ");
     if (unix_flags & SO_WAITDATA)
         strcat(ss_flags, "W ");
     if (unix_flags & SO_NOSPACE)
         strcat(ss_flags, "N ");
     strcat(ss_flags, "]");
     printf("%-5s %-6lu %-11s %-10s %-13s %6lu ",
         ss_proto, refcnt, ss_flags, ss_type, ss_state, inode
         );
 #if ENABLE_FEATURE_NETSTAT_PRG
     if (option_mask32 & OPT_prg)
         printf("%-"PROGNAME_WIDTH_STR"s", prg_cache_get(inode));
 #endif
     /* TODO: currently we stop at first NUL byte. Is it a problem? */
     line += path_ofs;
     chomp(line);
     while (*line)
         fputc_printable(*line++, stdout);
     bb_putchar('\n');
     return 0;
 }
References bb_putchar(), chomp(), flags, fputc_printable(), inet_params::inode, NETSTAT_CONNECTED, NETSTAT_LISTENING, num, OPT_prg, option_mask32, printf, PROGNAME_WIDTH_STR, SO_ACCEPTCON, SO_NOSPACE, SO_WAITDATA, SOCK_DGRAM, SOCK_RAW, SOCK_RDM, SOCK_SEQPACKET, SOCK_STREAM, SS_CONNECTED, SS_CONNECTING, SS_DISCONNECTING, SS_FREE, SS_UNCONNECTED, sscanf(), state, stdout, strcat, strcpy, and type.
Referenced by netstat_main().
Variable Documentation
ALIGN_PTR
const char* const tcp_state [] ALIGN_PTR static
Initial value:
= {
    "",
    "ESTABLISHED",
    "SYN_SENT",
    "SYN_RECV",
    "FIN_WAIT1",
    "FIN_WAIT2",
    "TIME_WAIT",
    "CLOSE",
    "CLOSE_WAIT",
    "LAST_ACK",
    "LISTEN",
    "CLOSING"
}
Definition at line 117 of file netstat.c.