Fennix: std::string Class Reference
std::string Class Reference
String class String class that can be used to store strings.
#include <string.hpp>
Data Structures
class iterator
Public Member Functions
string (const char *Str="")
~string ()
size_t length () const
size_t capacity () const
const char * c_str () const
void resize (size_t NewLength)
void concat (const string &Other)
bool empty () const
size_t size () const
void clear ()
size_t find (const char *Str, size_t Pos=0) const
size_t find (const string &Str, size_t Pos=0) const
void erase (int Index, int Count=1)
size_t find_last_not_of (const char *Str, size_t Pos=npos) const
size_t find_first_not_of (const char *Str, size_t Pos=0) const
size_t find_first_of (const char *Str, size_t Pos=0) const
size_t find_last_of (const char *Str, size_t Pos=npos) const
size_t find_first_of (char C, size_t Pos=0) const
size_t find_last_of (char C, size_t Pos=npos) const
size_t substr (const char *Str, size_t Pos=0) const
size_t substr (const string &Str, size_t Pos=0) const
string substr (size_t Pos=0, size_t Count=npos) const
void replace (size_t Pos, size_t Count, const char *Str)
void replace (size_t Pos, size_t Count, const string &Str)
void pop_back ()
string operator+ (const string &Other) const
string operator+ (const char *Other) const
string & operator+= (const string &Other)
string & operator+= (const char *Other)
string & operator+= (char Other)
string & operator= (const string &Other)=default
string & operator= (const char *Other)
string & operator<< (const string &Other)
string & operator<< (const char *Other)
char & operator[] (int Index)
const char & operator[] (int Index) const
char & operator[] (size_t Index)
const char & operator[] (size_t Index) const
bool operator== (const string &Other) const
bool operator!= (const char *Other) const
bool operator!= (const string &Other) const
bool operator== (const char *Other) const
iterator begin ()
iterator end ()
Static Public Attributes
static const size_t npos = -1
Private Attributes
char * Data {}
size_t Length {}
size_t Capacity {}
Detailed Description
String class String class that can be used to store strings.
Definition at line 49 of file string.hpp.
Constructor & Destructor Documentation
string()
std::string::string (const char * Str = "") inline
Definition at line 59 of file string.hpp.
         {
             this->Length = strlen(Str);
             this->Capacity = this->Length + 1;
             this->Data = new char[this->Capacity];
             strcpy(this->Data, Str);
             strdbg("%#lx: New string created: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
         }
References Capacity, Data, Length, strcpy, strdbg, and strlen().
Referenced by substr().
~string()
std::string::~string () inline
Definition at line 69 of file string.hpp.
         {
             strdbg("%#lx: String deleted: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             delete[] this->Data, this->Data = nullptr;
         }
References Capacity, Data, Length, and strdbg.
Member Function Documentation
begin()
iterator std::string::begin () inline
Definition at line 628 of file string.hpp.
         {
             strdbg("%#lx: String iterator begin: %#lx",
                    this, this->Data);
             return iterator(this->Data);
         }
References Data, and strdbg.
c_str()
const char* std::string::c_str () const inline
Definition at line 90 of file string.hpp.
         {
             v_strdbg("%#lx: String data: \"%s\"",
                      this, this->Data);
             return this->Data;
         }
References Data, and v_strdbg.
Referenced by cmd_cat(), VirtualFileSystem::Virtual::Create(), VirtualFileSystem::Virtual::Delete(), find(), VirtualFileSystem::FileDescriptorTable::GetAbsolutePath(), VirtualFileSystem::Virtual::GetPathFromNode(), Driver::Driver::LoadDrivers(), VirtualFileSystem::Virtual::NormalizePath(), VirtualFileSystem::Virtual::Open(), VirtualFileSystem::ReferenceNode::ReferenceNode(), StartKernelShell(), substr(), and VirtualFileSystem::ReferenceNode::~ReferenceNode().
capacity()
size_t std::string::capacity () const inline
Definition at line 83 of file string.hpp.
         {
             v_strdbg("%#lx: String capacity: %d",
                      this, this->Capacity);
             return this->Capacity;
         }
References Capacity, and v_strdbg.
clear()
void std::string::clear () inline
Definition at line 151 of file string.hpp.
         {
             strdbg("%#lx: String clear", this);
             this->resize(0);
         }
References resize(), and strdbg.
Referenced by StartKernelShell().
concat()
void std::string::concat (const string & Other) inline
Definition at line 127 of file string.hpp.
         {
             size_t NewLength = this->Length + Other.Length;
             this->resize(NewLength);
             strcat(this->Data, Other.Data);
             strdbg("%#lx: String concatenated: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
         }
References Capacity, Data, Length, resize(), strcat, and strdbg.
Referenced by operator+(), operator+=(), and operator<<().
empty()
bool std::string::empty () const inline
Definition at line 137 of file string.hpp.
         {
             strdbg("%#lx: String empty: %d",
                    this, this->Length == 0);
             return this->Length == 0;
         }
References Length, and strdbg.
end()
iterator std::string::end () inline
Definition at line 635 of file string.hpp.
         {
             strdbg("%#lx: String iterator end: %#lx",
                    this, this->Data + this->Length);
             return iterator(this->Data + this->Length);
         }
References Data, Length, and strdbg.
erase()
void std::string::erase (int Index, int Count = 1) inline
Definition at line 188 of file string.hpp.
         {
             strdbg("%#lx: String erase: %d, %d",
                    this, Index, Count);
             if (Index < 0 || (size_t)Index >= this->Length)
                 return;
             if (Count < 0)
                 return;
             if ((size_t)(Index + Count) > this->Length)
                 Count = (int)this->Length - Index;
             for (size_t i = Index; i < this->Length - Count; i++)
                 this->Data[i] = this->Data[i + Count];
             this->Length -= Count;
             this->Data[this->Length] = '\0';
             strdbg("%#lx: String erased: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
         }
References Capacity, Data, i, Length, and strdbg.
find() [1/2]
size_t std::string::find (const char * Str, size_t Pos = 0) const inline
Definition at line 157 of file string.hpp.
         {
             strdbg("%#lx: String find: \"%s\", %d",
                    this, Str, Pos);
             if (Pos >= this->Length)
                 return npos;
             for (size_t i = Pos; i < this->Length; i++)
             {
                 bool found = true;
                 for (size_t j = 0; Str[j] != '\0'; j++)
                 {
                     if (this->Data[i + j] != Str[j])
                     {
                         found = false;
                         break;
                     }
                 }
                 if (found)
                     return i;
             }
             return npos;
         }
References Data, found, i, j, Length, npos, and strdbg.
Referenced by find().
find() [2/2]
size_t std::string::find (const string & Str, size_t Pos = 0) const inline
Definition at line 181 of file string.hpp.
         {
             strdbg("%#lx: String find: \"%s\", %d",
                    this, Str.c_str(), Pos);
             return this->find(Str.c_str(), Pos);
         }
References c_str(), find(), and strdbg.
find_first_not_of()
size_t std::string::find_first_not_of (const char * Str, size_t Pos = 0) const inline
Definition at line 234 of file string.hpp.
         {
             strdbg("%#lx: String find_first_not_of: \"%s\", %d",
                    this, Str, Pos);
             if (Pos >= this->Length)
                 return npos;
             for (size_t i = Pos; i < this->Length; i++)
             {
                 bool found = false;
                 for (size_t j = 0; Str[j] != '\0'; j++)
                 {
                     if (this->Data[i] == Str[j])
                     {
                         found = true;
                         break;
                     }
                 }
                 if (!found)
                     return i;
             }
             return npos;
         }
References Data, found, i, j, Length, npos, and strdbg.
find_first_of() [1/2]
size_t std::string::find_first_of (char C, size_t Pos = 0) const inline
Definition at line 306 of file string.hpp.
         {
             strdbg("%#lx: String find_first_of: '%c', %d",
                    this, C, Pos);
             if (Pos >= this->Length)
                 return npos;
             for (size_t i = Pos; i < this->Length; i++)
             {
                 if (this->Data[i] == C)
                     return i;
             }
             return npos;
         }
References C, Data, i, Length, npos, and strdbg.
find_first_of() [2/2]
size_t std::string::find_first_of (const char * Str, size_t Pos = 0) const inline
Definition at line 258 of file string.hpp.
         {
             strdbg("%#lx: String find_first_of: \"%s\", %d",
                    this, Str, Pos);
             if (Pos >= this->Length)
                 return npos;
             for (size_t i = Pos; i < this->Length; i++)
             {
                 bool found = false;
                 for (size_t j = 0; Str[j] != '\0'; j++)
                 {
                     if (this->Data[i] == Str[j])
                     {
                         found = true;
                         break;
                     }
                 }
                 if (found)
                     return i;
             }
             return npos;
         }
References Data, found, i, j, Length, npos, and strdbg.
find_last_not_of()
size_t std::string::find_last_not_of (const char * Str, size_t Pos = npos) const inline
Definition at line 210 of file string.hpp.
         {
             strdbg("%#lx: String find_last_not_of: \"%s\", %d",
                    this, Str, Pos);
             if (Pos == npos)
                 Pos = this->Length - 1;
             for (int i = (int)Pos; i >= 0; i--)
             {
                 bool found = false;
                 for (size_t j = 0; Str[j] != '\0'; j++)
                 {
                     if (this->Data[i] == Str[j])
                     {
                         found = true;
                         break;
                     }
                 }
                 if (!found)
                     return i;
             }
             return npos;
         }
References Data, found, i, j, Length, npos, and strdbg.
find_last_of() [1/2]
size_t std::string::find_last_of (char C, size_t Pos = npos) const inline
Definition at line 321 of file string.hpp.
         {
             strdbg("%#lx: String find_last_of: '%c', %d",
                    this, C, Pos);
             if (Pos == npos)
                 Pos = this->Length - 1;
             for (int i = (int)Pos; i >= 0; i--)
             {
                 if (this->Data[i] == C)
                     return i;
             }
             return npos;
         }
References C, Data, i, Length, npos, and strdbg.
find_last_of() [2/2]
size_t std::string::find_last_of (const char * Str, size_t Pos = npos) const inline
Definition at line 282 of file string.hpp.
         {
             strdbg("%#lx: String find_last_of: \"%s\", %d",
                    this, Str, Pos);
             if (Pos == npos)
                 Pos = this->Length - 1;
             for (int i = (int)Pos; i >= 0; i--)
             {
                 bool found = false;
                 for (int j = 0; Str[j] != '\0'; j++)
                 {
                     if (this->Data[i] == Str[j])
                     {
                         found = true;
                         break;
                     }
                 }
                 if (found)
                     return i;
             }
             return npos;
         }
References Data, found, i, j, Length, npos, and strdbg.
length()
size_t std::string::length () const inline
Definition at line 76 of file string.hpp.
         {
             v_strdbg("%#lx: String length: %d",
                      this, this->Length);
             return this->Length;
         }
References Length, and v_strdbg.
Referenced by StartKernelShell().
operator!=() [1/2]
bool std::string::operator!= (const char * Other) const inline
Definition at line 569 of file string.hpp.
         {
             strdbg("%#lx: String compared: \"%s\" != \"%s\"",
                    this, this->Data, Other);
             return strcmp(this->Data, Other) != 0;
         }
References Data, strcmp, and strdbg.
operator!=() [2/2]
bool std::string::operator!= (const string & Other) const inline
Definition at line 576 of file string.hpp.
         {
             strdbg("%#lx: String compared: \"%s\" != \"%s\"",
                    this, this->Data, Other.Data);
             return strcmp(this->Data, Other.Data) != 0;
         }
References Data, strcmp, and strdbg.
operator+() [1/2]
string std::string::operator+ (const char * Other) const inline
Definition at line 459 of file string.hpp.
         {
             string result = *this;
             result.concat(Other);
             strdbg("%#lx: String added: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, result.Data, result.Data, result.Length, result.Capacity);
             return result;
         }
References Capacity, concat(), Data, Length, and strdbg.
operator+() [2/2]
string std::string::operator+ (const string & Other) const inline
Definition at line 450 of file string.hpp.
         {
             string result = *this;
             result.concat(Other);
             strdbg("%#lx: String added: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, result.Data, result.Data, result.Length, result.Capacity);
             return result;
         }
References Capacity, concat(), Data, Length, and strdbg.
operator+=() [1/3]
string& std::string::operator+= (char Other) inline
Definition at line 484 of file string.hpp.
         {
             const char str[2] = {Other, '\0'};
             this->concat(str);
             strdbg("%#lx: String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             return *this;
         }
References Capacity, concat(), Data, Length, str, and strdbg.
operator+=() [2/3]
string& std::string::operator+= (const char * Other) inline
Definition at line 476 of file string.hpp.
         {
             this->concat(Other);
             strdbg("%#lx: String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             return *this;
         }
References Capacity, concat(), Data, Length, and strdbg.
operator+=() [3/3]
string& std::string::operator+= (const string & Other) inline
Definition at line 468 of file string.hpp.
         {
             this->concat(Other);
             strdbg("%#lx: String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             return *this;
         }
References Capacity, concat(), Data, Length, and strdbg.
operator<<() [1/2]
string& std::string::operator<< (const char * Other) inline
Definition at line 530 of file string.hpp.
         {
             this->concat(Other);
             strdbg("%#lx: String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             return *this;
         }
References Capacity, concat(), Data, Length, and strdbg.
operator<<() [2/2]
string& std::string::operator<< (const string & Other) inline
Definition at line 522 of file string.hpp.
         {
             this->concat(Other);
             strdbg("%#lx: String appended: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             return *this;
         }
References Capacity, concat(), Data, Length, and strdbg.
operator=() [1/2]
string& std::string::operator= (const char * Other) inline
Definition at line 510 of file string.hpp.
         {
             this->Length = strlen(Other);
             this->Capacity = this->Length + 1;
             delete[] this->Data;
             this->Data = new char[this->Capacity];
             strcpy(this->Data, Other);
             strdbg("%#lx: String assigned: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
             return *this;
         }
References Capacity, Data, Length, strcpy, strdbg, and strlen().
operator=() [2/2]
string& std::string::operator= (const string & Other) default
operator==() [1/2]
bool std::string::operator== (const char * Other) const inline
Definition at line 583 of file string.hpp.
         {
             strdbg("%#lx: String compared: \"%s\" == \"%s\"",
                    this, this->Data, Other);
             return strcmp(this->Data, Other) == 0;
         }
References Data, strcmp, and strdbg.
operator==() [2/2]
bool std::string::operator== (const string & Other) const inline
Definition at line 562 of file string.hpp.
         {
             strdbg("%#lx: String compared: \"%s\" == \"%s\"",
                    this, this->Data, Other.Data);
             return strcmp(this->Data, Other.Data) == 0;
         }
References Data, strcmp, and strdbg.
operator[]() [1/4]
char& std::string::operator[] (int Index) inline
Definition at line 538 of file string.hpp.
         {
             strdbg("%#lx: String index: %d", this, Index);
             return this->Data[Index];
         }
References Data, and strdbg.
operator[]() [2/4]
const char& std::string::operator[] (int Index) const inline
Definition at line 544 of file string.hpp.
         {
             strdbg("%#lx: String index: %d", this, Index);
             return this->Data[Index];
         }
References Data, and strdbg.
operator[]() [3/4]
char& std::string::operator[] (size_t Index) inline
Definition at line 550 of file string.hpp.
         {
             strdbg("%#lx: String index: %d", this, Index);
             return this->Data[Index];
         }
References Data, and strdbg.
operator[]() [4/4]
const char& std::string::operator[] (size_t Index) const inline
Definition at line 556 of file string.hpp.
         {
             strdbg("%#lx: String index: %d", this, Index);
             return this->Data[Index];
         }
References Data, and strdbg.
pop_back()
void std::string::pop_back () inline
Definition at line 440 of file string.hpp.
         {
             strdbg("%#lx: String pop_back", this);
             if (this->Length > 0)
             {
                 this->Data[this->Length - 1] = '\0';
                 this->Length--;
             }
         }
References Data, Length, and strdbg.
Referenced by StartKernelShell().
replace() [1/2]
void std::string::replace (size_t Pos, size_t Count, const char * Str) inline
Definition at line 388 of file string.hpp.
         {
             strdbg("%#lx: String replace: %d, %d, \"%s\"",
                    this, Pos, Count, Str);
             if (Pos >= this->Length)
                 return;
             if ((int64_t)Count <= 0)
                 return;
             if (Pos + Count > this->Length)
                 Count = this->Length - Pos;
             size_t NewLength = this->Length - Count + strlen(Str);
             this->resize(NewLength);
             for (size_t i = this->Length - 1; i >= Pos + strlen(Str); i--)
                 this->Data[i] = this->Data[i - strlen(Str) + Count];
             for (unsigned long i = 0; i < strlen(Str); i++)
                 this->Data[Pos + i] = Str[i];
             strdbg("%#lx: String replaced: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
         }
References Capacity, Data, i, Length, resize(), strdbg, and strlen().
replace() [2/2]
void std::string::replace (size_t Pos, size_t Count, const string & Str) inline
Definition at line 414 of file string.hpp.
         {
             strdbg("%#lx: String replace: %d, %d, \"%s\"",
                    this, Pos, Count, Str.Data);
             if (Pos >= this->Length)
                 return;
             if ((int64_t)Count <= 0)
                 return;
             if (Pos + Count > this->Length)
                 Count = this->Length - Pos;
             size_t NewLength = this->Length - Count + Str.Length;
             this->resize(NewLength);
             for (size_t i = this->Length - 1; i >= Pos + Str.Length; i--)
                 this->Data[i] = this->Data[i - Str.Length + Count];
             for (size_t i = 0; i < Str.Length; i++)
                 this->Data[Pos + i] = Str.Data[i];
             strdbg("%#lx: String replaced: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
         }
References Capacity, Data, for(), i, Length, resize(), and strdbg.
resize()
void std::string::resize (size_t NewLength) inline
Definition at line 97 of file string.hpp.
         {
             strdbg("%#lx: String resize: %d",
                    this, NewLength);
             if (NewLength < this->Capacity)
             {
                 this->Length = NewLength;
                 this->Data[this->Length] = '\0';
                 strdbg("%#lx: String resized: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                        this, this->Data, this->Data, this->Length, this->Capacity);
                 return;
             }
             size_t newCapacity = NewLength + 1;
             char *newData = new char[newCapacity];
             strcpy(newData, this->Data);
             strdbg("%#lx: old: %#lx, new: %#lx",
                    this, this->Data, newData);
             delete[] this->Data;
             this->Data = newData;
             this->Length = NewLength;
             this->Capacity = newCapacity;
             strdbg("%#lx: String resized: \"%s\" (data: %#lx, length: %d, capacity: %d)",
                    this, this->Data, this->Data, this->Length, this->Capacity);
         }
References Capacity, Data, Length, strcpy, and strdbg.
Referenced by clear(), concat(), VirtualFileSystem::Virtual::NormalizePath(), replace(), and substr().
size()
size_t std::string::size () const inline
Definition at line 144 of file string.hpp.
         {
             strdbg("%#lx: String size: %d",
                    this, this->Length);
             return this->Length;
         }
References Length, and strdbg.
Referenced by StartKernelShell().
substr() [1/3]
size_t std::string::substr (const char * Str, size_t Pos = 0) const inline
Definition at line 336 of file string.hpp.
         {
             strdbg("%#lx: String substr: \"%s\", %d",
                    this, Str, Pos);
             if (Pos >= this->Length)
                 return npos;
             for (size_t i = Pos; i < this->Length; i++)
             {
                 bool found = true;
                 for (size_t j = 0; Str[j] != '\0'; j++)
                 {
                     if (this->Data[i + j] != Str[j])
                     {
                         found = false;
                         break;
                     }
                 }
                 if (found)
                     return i;
             }
             return npos;
         }
References Data, found, i, j, Length, npos, and strdbg.
Referenced by substr().
substr() [2/3]
size_t std::string::substr (const string & Str, size_t Pos = 0) const inline
Definition at line 360 of file string.hpp.
         {
             strdbg("%#lx: String substr: \"%s\", %d",
                    this, Str.c_str(), Pos);
             return this->substr(Str.c_str(), Pos);
         }
References c_str(), strdbg, and substr().
substr() [3/3]
string std::string::substr (size_t Pos = 0, size_t Count = npos) const inline
Definition at line 367 of file string.hpp.
         {
             strdbg("%#lx: String substr: %d, %d",
                    this, Pos, Count);
             if (Pos >= this->Length)
                 return string();
             if (Count == npos)
                 Count = this->Length - Pos;
             if (Pos + Count > this->Length)
                 Count = this->Length - Pos;
             string ret;
             ret.resize(Count);
             for (size_t i = 0; i < Count; i++)
                 ret.Data[i] = this->Data[Pos + i];
             ret.Data[Count] = '\0';
             return ret;
         }
References Data, i, Length, npos, resize(), strdbg, and string().
Field Documentation
Capacity
size_t std::string::Capacity {} private
Definition at line 54 of file string.hpp.
Referenced by capacity(), concat(), erase(), operator+(), operator+=(), operator<<(), operator=(), replace(), resize(), string(), and ~string().
Data
char* std::string::Data {} private
Definition at line 52 of file string.hpp.
Referenced by begin(), c_str(), concat(), end(), erase(), find(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), operator!=(), operator+(), operator+=(), operator<<(), operator=(), operator==(), operator[](), pop_back(), replace(), resize(), string(), substr(), and ~string().
Length
size_t std::string::Length {} private
Definition at line 53 of file string.hpp.
Referenced by concat(), empty(), end(), erase(), find(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), length(), operator+(), operator+=(), operator<<(), operator=(), pop_back(), replace(), resize(), size(), string(), substr(), and ~string().
npos
const size_t std::string::npos = -1 static
Definition at line 57 of file string.hpp.
Referenced by find(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), and substr().
The documentation for this class was generated from the following file:
Kernel/include_std/std/string.hpp