Fennix Userspace: Userspace/musl/compat/time32/wait3_time32.c File Reference
wait3_time32.c File Reference
#include "time32.h"
#include <string.h>
#include <stddef.h>
#include <sys/wait.h>
Data Structures
struct compat_rusage
Macros
#define _BSD_SOURCE
Functions
pid_t __wait3_time32 (int *status, int options, struct compat_rusage *usage)
Data Structure Documentation
compat_rusage
struct compat_rusage
Definition at line 6 of file getrusage_time32.c.
Data Fields
long ru_idrss
long ru_inblock
long ru_isrss
long ru_ixrss
long ru_majflt
long ru_maxrss
long ru_minflt
long ru_msgrcv
long ru_msgsnd
long ru_nivcsw
long ru_nsignals
long ru_nswap
long ru_nvcsw
long ru_oublock
struct timeval32 ru_stime
struct timeval32 ru_utime
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file wait3_time32.c.
Function Documentation
__wait3_time32()
pid_t __wait3_time32 (int * status, int options, struct compat_rusage * usage)
Definition at line 26 of file wait3_time32.c.
 {
     struct rusage ru;
     int r = wait3(status, options, usage ? &ru : 0);
     if (!r && usage) {
         usage->ru_utime.tv_sec = ru.ru_utime.tv_sec;
         usage->ru_utime.tv_usec = ru.ru_utime.tv_usec;
         usage->ru_stime.tv_sec = ru.ru_stime.tv_sec;
         usage->ru_stime.tv_usec = ru.ru_stime.tv_usec;
         memcpy(&usage->ru_maxrss, &ru.ru_maxrss,
             sizeof(struct compat_rusage) -
             offsetof(struct compat_rusage, ru_maxrss));
     }
     return r;
 }
References memcpy(), offsetof, options, r, mlibc::ru, rusage::ru_maxrss, rusage::ru_stime, rusage::ru_utime, mlibc::status, timeval::tv_sec, timeval::tv_usec, usage(), and wait3().