Fennix: Userspace/apps/base/bash/examples/loadables/tee.c File Reference
tee.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixstat.h"
#include "filecntl.h"
#include <signal.h>
#include "bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Data Structures
struct flist
Macros
#define TEE_BUFSIZE 8192
Typedefs
typedef struct flist FLIST
Functions
char * strerror ()
int tee_builtin (WORD_LIST *list)
Variables
int errno
static FLIST * tee_flist
int interrupt_immediately
char * tee_doc []
struct builtin tee_struct
Data Structure Documentation
flist
struct flist
Definition at line 49 of file tee.c.
Data Fields
int fd
char * fname
struct flist * next
Macro Definition Documentation
TEE_BUFSIZE
#define TEE_BUFSIZE 8192
Definition at line 57 of file tee.c.
Typedef Documentation
FLIST
typedef struct flist FLIST
Function Documentation
strerror()
char* strerror ()
Referenced by tee_builtin().
tee_builtin()
int tee_builtin (WORD_LIST * list)
Definition at line 64 of file tee.c.
 {
   int opt, append, nointr, rval, fd, fflags;
   int n, nr, nw;
   FLIST *fl;
   char *buf, *bp;
   char *t;
   reset_internal_getopt ();
   append = nointr = 0;
   tee_flist = (FLIST *)NULL;
   while ((opt = internal_getopt (list, "ai")) != -1)
     {
       switch (opt)
     {
     case 'a':
       append = 1;
       break;
     case 'i':
       nointr = 1;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (nointr == 0)
     interrupt_immediately++;
   buf = xmalloc (TEE_BUFSIZE);
   /* Initialize output file list. */
   fl = tee_flist = (FLIST *)xmalloc (sizeof(FLIST));
   tee_flist->fd = 1;
   tee_flist->fname = "stdout";
   tee_flist->next = (FLIST *)NULL;
   /* Add file arguments to list of output files. */
   fflags = append ? O_WRONLY|O_CREAT|O_APPEND : O_WRONLY|O_CREAT|O_TRUNC;
   for (rval = EXECUTION_SUCCESS; list; list = list->next)
     {
       fd = open (list->word->word, fflags, 0666);
       if (fd < 0)
         {
           builtin_error ("%s: cannot open: %s", list->word->word, strerror (errno));
           rval = EXECUTION_FAILURE;
         }
       else
         {
           fl->next = (FLIST *)xmalloc (sizeof(FLIST));
           fl->next->fd = fd;
           fl->next->fname = list->word->word;
           fl = fl->next;
           fl->next = (FLIST *)NULL;
         }
       QUIT;
     }
   while ((nr = read(0, buf, TEE_BUFSIZE)) > 0)
     for (fl = tee_flist; fl; fl = fl->next)
       {
     n = nr;
     bp = buf;
     do
       {
         if ((nw = write (fl->fd, bp, n)) == -1)
           {
         builtin_error ("%s: write error: %s", fl->fname, strerror (errno));
         rval = EXECUTION_FAILURE;
         break;
           }
             bp += nw;
             QUIT;
       }
     while (n -= nw);
       }
   if (nr < 0)
     builtin_error ("read error: %s", strerror (errno));
   /* Deallocate resources -- this is a builtin command. */
   tee_flist = tee_flist->next;      /* skip bogus close of stdout */
   while (tee_flist)
     {
       fl = tee_flist;
       if (close (fl->fd) < 0)
     {
       builtin_error ("%s: close_error: %s", fl->fname, strerror (errno));
       rval = EXECUTION_FAILURE;
     }
       tee_flist = tee_flist->next;
       free (fl);
     }
   QUIT;
   return (rval);
 }
References append(), bp, buf, builtin_error(), builtin_usage(), CASE_HELPOPT, close(), errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, flist::fd, fd, flist::fname, free, internal_getopt(), interrupt_immediately, list(), loptend, n, flist::next, fl::next, node::next, NULL, nw, O_APPEND, O_CREAT, O_TRUNC, O_WRONLY, open(), opt, QUIT, read(), reset_internal_getopt(), strerror(), t, TEE_BUFSIZE, tee_flist, write(), and xmalloc.
Variable Documentation
errno
int errno extern
Referenced by tee_builtin().
interrupt_immediately
int interrupt_immediately extern
Definition at line 87 of file sig.c.
Referenced by tee_builtin().
tee_doc
char* tee_doc[]
Initial value:
= {
    "Duplicate standard output.",
    "",
    "Copy standard input to standard output, making a copy in each",
    "filename argument.  If the `-a' option is given, the specified",
    "files are appended to, otherwise they are overwritten.  If the",
    "`-i' option is supplied, tee ignores interrupts.",
    (char *)NULL
}
Definition at line 166 of file tee.c.
tee_flist
FLIST* tee_flist static
Definition at line 55 of file tee.c.
Referenced by tee_builtin().
tee_struct
struct builtin tee_struct
Initial value:
= {
    "tee",
    tee_builtin,
    BUILTIN_ENABLED,
    tee_doc,
    "tee [-ai] [file ...]",
    0
}
Definition at line 166 of file tee.c.