Fennix: Userspace/musl/include/spawn.h File Reference
spawn.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct posix_spawnattr_t
struct posix_spawn_file_actions_t
Macros
#define __NEED_mode_t
#define __NEED_pid_t
#define __NEED_sigset_t
#define POSIX_SPAWN_RESETIDS 1
#define POSIX_SPAWN_SETPGROUP 2
#define POSIX_SPAWN_SETSIGDEF 4
#define POSIX_SPAWN_SETSIGMASK 8
#define POSIX_SPAWN_SETSCHEDPARAM 16
#define POSIX_SPAWN_SETSCHEDULER 32
#define POSIX_SPAWN_USEVFORK 64
#define POSIX_SPAWN_SETSID 128
Functions
int posix_spawn (pid_t *__restrict, const char *__restrict, const posix_spawn_file_actions_t *, const posix_spawnattr_t *__restrict, char *const *__restrict, char *const *__restrict)
int posix_spawnp (pid_t *__restrict, const char *__restrict, const posix_spawn_file_actions_t *, const posix_spawnattr_t *__restrict, char *const *__restrict, char *const *__restrict)
int posix_spawnattr_init (posix_spawnattr_t *)
int posix_spawnattr_destroy (posix_spawnattr_t *)
int posix_spawnattr_setflags (posix_spawnattr_t *, short)
int posix_spawnattr_getflags (const posix_spawnattr_t *__restrict, short *__restrict)
int posix_spawnattr_setpgroup (posix_spawnattr_t *, pid_t)
int posix_spawnattr_getpgroup (const posix_spawnattr_t *__restrict, pid_t *__restrict)
int posix_spawnattr_setsigmask (posix_spawnattr_t *__restrict, const sigset_t *__restrict)
int posix_spawnattr_getsigmask (const posix_spawnattr_t *__restrict, sigset_t *__restrict)
int posix_spawnattr_setsigdefault (posix_spawnattr_t *__restrict, const sigset_t *__restrict)
int posix_spawnattr_getsigdefault (const posix_spawnattr_t *__restrict, sigset_t *__restrict)
int posix_spawnattr_setschedparam (posix_spawnattr_t *__restrict, const struct sched_param *__restrict)
int posix_spawnattr_getschedparam (const posix_spawnattr_t *__restrict, struct sched_param *__restrict)
int posix_spawnattr_setschedpolicy (posix_spawnattr_t *, int)
int posix_spawnattr_getschedpolicy (const posix_spawnattr_t *__restrict, int *__restrict)
int posix_spawn_file_actions_init (posix_spawn_file_actions_t *)
int posix_spawn_file_actions_destroy (posix_spawn_file_actions_t *)
int posix_spawn_file_actions_addopen (posix_spawn_file_actions_t *__restrict, int, const char *__restrict, int, mode_t)
int posix_spawn_file_actions_addclose (posix_spawn_file_actions_t *, int)
int posix_spawn_file_actions_adddup2 (posix_spawn_file_actions_t *, int, int)
Data Structure Documentation
posix_spawnattr_t
struct posix_spawnattr_t
Definition at line 14 of file spawn.h.
Data Fields
sigset_t __def
short int __flags
int __flags
void * __fn
sigset_t __mask
int __pad[16]
char __pad[64 - sizeof(void *)]
pid_t __pgrp
int __pol
int __policy
int __prio
sigset_t __sd
struct sched_param __sp
sigset_t __ss
posix_spawn_file_actions_t
struct posix_spawn_file_actions_t
Definition at line 25 of file spawn.h.
Data Fields
struct __spawn_action * __actions
void * __actions
int __allocated
int __pad[16]
int __pad0[2]
int __used
Macro Definition Documentation
__NEED_mode_t
#define __NEED_mode_t
Definition at line 10 of file spawn.h.
__NEED_pid_t
#define __NEED_pid_t
Definition at line 11 of file spawn.h.
__NEED_sigset_t
#define __NEED_sigset_t
Definition at line 12 of file spawn.h.
POSIX_SPAWN_RESETIDS
#define POSIX_SPAWN_RESETIDS 1
Definition at line 18 of file spawn.h.
POSIX_SPAWN_SETPGROUP
#define POSIX_SPAWN_SETPGROUP 2
Definition at line 19 of file spawn.h.
POSIX_SPAWN_SETSCHEDPARAM
#define POSIX_SPAWN_SETSCHEDPARAM 16
Definition at line 22 of file spawn.h.
POSIX_SPAWN_SETSCHEDULER
#define POSIX_SPAWN_SETSCHEDULER 32
Definition at line 23 of file spawn.h.
POSIX_SPAWN_SETSID
#define POSIX_SPAWN_SETSID 128
Definition at line 25 of file spawn.h.
POSIX_SPAWN_SETSIGDEF
#define POSIX_SPAWN_SETSIGDEF 4
Definition at line 20 of file spawn.h.
POSIX_SPAWN_SETSIGMASK
#define POSIX_SPAWN_SETSIGMASK 8
Definition at line 21 of file spawn.h.
POSIX_SPAWN_USEVFORK
#define POSIX_SPAWN_USEVFORK 64
Definition at line 24 of file spawn.h.
Function Documentation
posix_spawn()
int posix_spawn (pid_t * __restrict, const char * __restrict, const posix_spawn_file_actions_t * , const posix_spawnattr_t * __restrict, char *const * __restrict, char *const * __restrict)
posix_spawn_file_actions_addclose()
int posix_spawn_file_actions_addclose (posix_spawn_file_actions_t * file_actions, int fildes)
Definition at line 335 of file spawn-stubs.cpp.
                     {
     struct fdop *op = (struct fdop *)malloc(sizeof *op);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_CLOSE;
     op->fd = fildes;
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References posix_spawn_file_actions_t::__actions, fdop::cmd, EBADF, ENOMEM, fdop::fd, FDOP_CLOSE, malloc, fdop::next, and fdop::prev.
Referenced by popen().
posix_spawn_file_actions_adddup2()
int posix_spawn_file_actions_adddup2 (posix_spawn_file_actions_t * file_actions, int fildes, int newfildes)
Definition at line 320 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)malloc(sizeof *op);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_DUP2;
     op->srcfd = fildes;
     op->fd = newfildes;
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References posix_spawn_file_actions_t::__actions, fdop::cmd, EBADF, ENOMEM, fdop::fd, FDOP_DUP2, malloc, fdop::next, fdop::prev, and fdop::srcfd.
Referenced by popen().
posix_spawn_file_actions_addopen()
int posix_spawn_file_actions_addopen (posix_spawn_file_actions_t * __restrict, int , const char * __restrict, int , mode_t)
posix_spawn_file_actions_destroy()
int posix_spawn_file_actions_destroy (posix_spawn_file_actions_t * file_actions)
Definition at line 310 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)file_actions->__actions, *next;
     while(op) {
         next = op->next;
         free(op);
         op = next;
     }
     return 0;
 }
References posix_spawn_file_actions_t::__actions, free, and fdop::next.
Referenced by popen().
posix_spawn_file_actions_init()
int posix_spawn_file_actions_init (posix_spawn_file_actions_t * file_actions)
Definition at line 305 of file spawn-stubs.cpp.
{
     file_actions->__actions = 0;
     return 0;
 }
References posix_spawn_file_actions_t::__actions.
Referenced by popen().
posix_spawnattr_destroy()
int posix_spawnattr_destroy (posix_spawnattr_t * attr)
Definition at line 257 of file spawn-stubs.cpp.
{
     return 0;
 }
Referenced by system().
posix_spawnattr_getflags()
int posix_spawnattr_getflags (const posix_spawnattr_t * __restrict, short * __restrict)
posix_spawnattr_getpgroup()
int posix_spawnattr_getpgroup (const posix_spawnattr_t * __restrict, pid_t * __restrict)
posix_spawnattr_getschedparam()
int posix_spawnattr_getschedparam (const posix_spawnattr_t * __restrict, struct sched_param * __restrict)
posix_spawnattr_getschedpolicy()
int posix_spawnattr_getschedpolicy (const posix_spawnattr_t * __restrict, int * __restrict)
posix_spawnattr_getsigdefault()
int posix_spawnattr_getsigdefault (const posix_spawnattr_t * __restrict, sigset_t * __restrict)
posix_spawnattr_getsigmask()
int posix_spawnattr_getsigmask (const posix_spawnattr_t * __restrict, sigset_t * __restrict)
posix_spawnattr_init()
int posix_spawnattr_init (posix_spawnattr_t * attr)
Definition at line 252 of file spawn-stubs.cpp.
{
     *attr = (posix_spawnattr_t){};
     return 0;
 }
References args::attr.
Referenced by system().
posix_spawnattr_setflags()
int posix_spawnattr_setflags (posix_spawnattr_t * attr, short flags)
Definition at line 261 of file spawn-stubs.cpp.
{
     const unsigned all_flags =
             POSIX_SPAWN_RESETIDS |
             POSIX_SPAWN_SETPGROUP |
             POSIX_SPAWN_SETSIGDEF |
             POSIX_SPAWN_SETSIGMASK |
             POSIX_SPAWN_SETSCHEDPARAM |
             POSIX_SPAWN_SETSCHEDULER |
             POSIX_SPAWN_USEVFORK |
             POSIX_SPAWN_SETSID;
     if(flags & ~all_flags)
         return EINVAL;
     attr->__flags = flags;
     return 0;
 }
References posix_spawnattr_t::__flags, args::attr, EINVAL, flags, POSIX_SPAWN_RESETIDS, POSIX_SPAWN_SETPGROUP, POSIX_SPAWN_SETSCHEDPARAM, POSIX_SPAWN_SETSCHEDULER, POSIX_SPAWN_SETSID, POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, and POSIX_SPAWN_USEVFORK.
Referenced by system().
posix_spawnattr_setpgroup()
int posix_spawnattr_setpgroup (posix_spawnattr_t * attr, pid_t pgroup)
Definition at line 300 of file spawn-stubs.cpp.
{
     attr->__pgrp = pgroup;
     return 0;
 }
References posix_spawnattr_t::__pgrp, and args::attr.
posix_spawnattr_setschedparam()
int posix_spawnattr_setschedparam (posix_spawnattr_t * __restrict, const struct sched_param * __restrict)
Definition at line 283 of file spawn-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
posix_spawnattr_setschedpolicy()
int posix_spawnattr_setschedpolicy (posix_spawnattr_t * attr, int schedpolicy)
Definition at line 289 of file spawn-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, and ENOSYS.
posix_spawnattr_setsigdefault()
int posix_spawnattr_setsigdefault (posix_spawnattr_t * __restrict, const sigset_t * __restrict)
posix_spawnattr_setsigmask()
int posix_spawnattr_setsigmask (posix_spawnattr_t * __restrict, const sigset_t * __restrict)
posix_spawnp()
int posix_spawnp (pid_t * __restrict, const char * __restrict, const posix_spawn_file_actions_t * , const posix_spawnattr_t * __restrict, char *const * __restrict, char *const * __restrict)