Fennix Kernel: Xalloc::V1 Class Reference
Xalloc::V1 Class Reference
#include <Xalloc.hpp>
Public Member Functions
void Xstac ()
Execute "stac" instruction if the kernel has SMAP enabled.
void Xclac ()
Execute "clac" instruction if the kernel has SMAP enabled.
void Arrange ()
Arrange the blocks to optimize the memory usage The allocator is not arranged by default to avoid performance issues. This function will defragment the memory and free the unused blocks.
void * malloc (Xsize_t Size)
Allocate a new memory block.
void free (void *Address)
Free a previously allocated block.
void * calloc (Xsize_t NumberOfBlocks, Xsize_t Size)
Allocate a new memory block.
void * realloc (void *Address, Xsize_t Size)
Reallocate a previously allocated block.
V1 (void *BaseVirtualAddress, bool UserMode, bool SMAPEnabled)
Construct a new Allocator object.
~V1 ()
Destroy the Allocator object.
Private Attributes
void * BaseVirtualAddress = nullptr
void * FirstBlock = nullptr
void * LastBlock = nullptr
bool UserMapping = false
bool SMAPUsed = false
Detailed Description
Definition at line 39 of file Xalloc.hpp.
Constructor & Destructor Documentation
V1()
Xalloc::V1::V1 (void * BaseVirtualAddress, bool UserMode, bool SMAPEnabled)
Construct a new Allocator object.
Parameters
BaseVirtualAddress Virtual address to map the pages.
UserMode Map the new pages with USER flag?
SMAPEnabled Does the kernel has Supervisor Mode Access Prevention enabled?
Definition at line 271 of file XallocV1.cpp.
     {
         SmartSMAP;
         Xalloc_lock;
         this->SMAPUsed = SMAPEnabled;
         this->UserMapping = UserMode;
         this->BaseVirtualAddress = BaseVirtualAddress;
         Xalloc_unlock;
     }
References BaseVirtualAddress, SMAPUsed, SmartSMAP, UserMapping, Xalloc_lock, and Xalloc_unlock.
~V1()
Xalloc::V1::~V1 ()
Destroy the Allocator object.
Definition at line 281 of file XallocV1.cpp.
     {
         SmartSMAP;
         Xalloc_lock;
         Xalloc_trace("Destructor not implemented yet.");
         Xalloc_unlock;
     }
References SmartSMAP, Xalloc_lock, Xalloc_trace, and Xalloc_unlock.
Member Function Documentation
Arrange()
void Xalloc::V1::Arrange ()
Arrange the blocks to optimize the memory usage The allocator is not arranged by default to avoid performance issues. This function will defragment the memory and free the unused blocks.
You should call this function when the kernel is idle or when is not using the allocator.
Definition at line 141 of file XallocV1.cpp.
     {
         Xalloc_err("Arrange() is not implemented yet!");
     }
References Xalloc_err.
calloc()
void * Xalloc::V1::calloc (Xsize_t NumberOfBlocks, Xsize_t Size)
Allocate a new memory block.
Parameters
NumberOfBlocks Number of blocks to allocate.
Size Size of the block to allocate.
Returns
void* Pointer to the allocated block.
Definition at line 236 of file XallocV1.cpp.
     {
         if (NumberOfBlocks == 0 || Size == 0)
         {
             Xalloc_warn("The %s%s%s is 0!",
                         NumberOfBlocks == 0 ? "NumberOfBlocks" : "",
                         NumberOfBlocks == 0 && Size == 0 ? " and " : "",
                         Size == 0 ? "Size" : "");
             return nullptr;
         }
         return this->malloc(NumberOfBlocks * Size);
     }
References malloc(), Size, and Xalloc_warn.
Referenced by calloc().
free()
void Xalloc::V1::free (void * Address)
Free a previously allocated block.
Parameters
Address Address of the block to free.
Definition at line 196 of file XallocV1.cpp.
     {
         if (Address == nullptr)
         {
             Xalloc_warn("Attempted to free a null pointer!");
             return;
         }
         SmartSMAP;
         Xalloc_lock;
         Block *CurrentBlock = ((Block *)this->FirstBlock);
         while (CurrentBlock != nullptr)
         {
             if (!CurrentBlock->Check())
             {
                 Xalloc_err("Block %#lx checksum failed!", (Xuint64_t)CurrentBlock);
                 while (Xalloc_StopOnFail)
                     ;
             }
             else if (CurrentBlock->Address == Address)
             {
                 if (CurrentBlock->IsFree)
                 {
                     Xalloc_warn("Attempted to free an already freed pointer!");
                     Xalloc_unlock;
                     return;
                 }
                 CurrentBlock->IsFree = true;
                 Xalloc_unlock;
                 return;
             }
             CurrentBlock = CurrentBlock->Next;
         }
         Xalloc_err("Invalid address %#lx.", Address);
         Xalloc_unlock;
     }
References Address, Xalloc::Block::Address, Xalloc::Block::Check(), FirstBlock, Xalloc::Block::IsFree, Xalloc::Block::Next, SmartSMAP, Xalloc_err, Xalloc_lock, Xalloc_StopOnFail, Xalloc_unlock, and Xalloc_warn.
Referenced by free(), and realloc().
malloc()
void * Xalloc::V1::malloc (Xsize_t Size)
Allocate a new memory block.
Parameters
Size Size of the block to allocate.
Returns
void* Pointer to the allocated block.
Definition at line 146 of file XallocV1.cpp.
     {
         if (Size == 0)
         {
             Xalloc_warn("Attempted to allocate 0 bytes!");
             return nullptr;
         }
         SmartSMAP;
         Xalloc_lock;
         if (this->FirstBlock == nullptr)
         {
             this->FirstBlock = new Block(Size);
             ((Block *)this->FirstBlock)->IsFree = false;
             Xalloc_unlock;
             return ((Block *)this->FirstBlock)->Address;
         }
         Block *CurrentBlock = ((Block *)this->FirstBlock);
         while (CurrentBlock != nullptr)
         {
             if (!CurrentBlock->Check())
             {
                 Xalloc_err("Block %#lx has an invalid checksum! (%#x != %#x)",
                            (Xuint64_t)CurrentBlock, CurrentBlock->Checksum, Xalloc_BlockChecksum);
                 while (Xalloc_StopOnFail)
                     ;
             }
             else if (CurrentBlock->IsFree && CurrentBlock->Size >= Size)
             {
                 CurrentBlock->IsFree = false;
                 Xmemset(CurrentBlock->Address, 0, Size);
                 Xalloc_unlock;
                 return CurrentBlock->Address;
             }
             CurrentBlock = CurrentBlock->Next;
         }
         CurrentBlock = ((Block *)this->FirstBlock);
         while (CurrentBlock->Next != nullptr)
             CurrentBlock = CurrentBlock->Next;
         CurrentBlock->Next = new Block(Size);
         ((Block *)CurrentBlock->Next)->Last = CurrentBlock;
         ((Block *)CurrentBlock->Next)->IsFree = false;
         Xalloc_unlock;
         return ((Block *)CurrentBlock->Next)->Address;
     }
References Address, Xalloc::Block::Address, Block(), Xalloc::Block::Check(), Xalloc::Block::Checksum, FirstBlock, Xalloc::Block::IsFree, Xalloc::Block::Next, Size, Xalloc::Block::Size, SmartSMAP, Xalloc_BlockChecksum, Xalloc_err, Xalloc_lock, Xalloc_StopOnFail, Xalloc_unlock, Xalloc_warn, and Xmemset().
Referenced by calloc(), malloc(), and realloc().
realloc()
void * Xalloc::V1::realloc (void * Address, Xsize_t Size)
Reallocate a previously allocated block.
Parameters
Address Address of the block to reallocate.
Size New size of the block.
Returns
void* Pointer to the reallocated block.
Definition at line 250 of file XallocV1.cpp.
     {
         if (Address == nullptr)
             return this->malloc(Size);
         if (Size == 0)
         {
             this->free(Address);
             return nullptr;
         }
         // SmartSMAP;
         // Xalloc_lock;
         // ...
         // Xalloc_unlock;
         // TODO: Implement realloc
         this->free(Address);
         return this->malloc(Size);
     }
References Address, free(), malloc(), and Size.
Referenced by realloc().
Xclac()
void Xalloc::V1::Xclac ()
Execute "clac" instruction if the kernel has SMAP enabled.
Definition at line 130 of file XallocV1.cpp.
     {
         if (this->SMAPUsed)
         {
 #if defined(a64) || defined(a32)
             asm volatile("clac" ::
                              : "cc");
 #endif
         }
     }
References SMAPUsed.
Referenced by Xalloc::SmartSMAPClass::~SmartSMAPClass().
Xstac()
void Xalloc::V1::Xstac ()
Execute "stac" instruction if the kernel has SMAP enabled.
Definition at line 119 of file XallocV1.cpp.
     {
         if (this->SMAPUsed)
         {
 #if defined(a64) || defined(a32)
             asm volatile("stac" ::
                              : "cc");
 #endif
         }
     }
References SMAPUsed.
Referenced by Xalloc::SmartSMAPClass::SmartSMAPClass().
Field Documentation
BaseVirtualAddress
void* Xalloc::V1::BaseVirtualAddress = nullptr private
Definition at line 42 of file Xalloc.hpp.
Referenced by V1().
FirstBlock
void* Xalloc::V1::FirstBlock = nullptr private
Definition at line 43 of file Xalloc.hpp.
Referenced by free(), and malloc().
LastBlock
void* Xalloc::V1::LastBlock = nullptr private
Definition at line 44 of file Xalloc.hpp.
SMAPUsed
bool Xalloc::V1::SMAPUsed = false private
Definition at line 47 of file Xalloc.hpp.
Referenced by V1(), Xclac(), and Xstac().
UserMapping
bool Xalloc::V1::UserMapping = false private
Definition at line 46 of file Xalloc.hpp.
Referenced by V1().
The documentation for this class was generated from the following files:
Kernel/Core/Memory/HeapAllocators/Xalloc/Xalloc.hpp
Kernel/Core/Memory/HeapAllocators/Xalloc/XallocV1.cpp