Fennix Userspace: Userspace/musl/src/misc/getopt_long.c File Reference
getopt_long.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <limits.h>
#include <getopt.h>
#include <stdio.h>
#include <string.h>
#include "stdio_impl.h"
Macros
#define _GNU_SOURCE
Functions
static void permute (char *const *argv, int dest, int src)
static int __getopt_long_core (int argc, char *const *argv, const char *optstring, const struct option *longopts, int *idx, int longonly)
static int __getopt_long (int argc, char *const *argv, const char *optstring, const struct option *longopts, int *idx, int longonly)
int getopt_long (int argc, char *const *argv, const char *optstring, const struct option *longopts, int *idx)
int getopt_long_only (int argc, char *const *argv, const char *optstring, const struct option *longopts, int *idx)
Variables
int __optpos
int __optreset
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file getopt_long.c.
Function Documentation
__getopt_long()
static int __getopt_long (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * idx, int longonly) static
Definition at line 24 of file getopt_long.c.
 {
     int ret, skipped, resumed;
     if (!optind || __optreset) {
         __optreset = 0;
         __optpos = 0;
         optind = 1;
     }
     if (optind >= argc || !argv[optind]) return -1;
     skipped = optind;
     if (optstring[0] != '+' && optstring[0] != '-') {
         int i;
         for (i=optind; ; i++) {
             if (i >= argc || !argv[i]) return -1;
             if (argv[i][0] == '-' && argv[i][1]) break;
         }
         optind = i;
     }
     resumed = optind;
     ret = __getopt_long_core(argc, argv, optstring, longopts, idx, longonly);
     if (resumed > skipped) {
         int i, cnt = optind-resumed;
         for (i=0; i<cnt; i++)
             permute(argv, skipped, optind-1);
         optind = skipped + cnt;
     }
     return ret;
 }
References __getopt_long_core(), __optpos, __optreset, argc, argv, cnt, i, idx, optind, permute(), and ret.
Referenced by getopt_long(), and getopt_long_only().
__getopt_long_core()
static int __getopt_long_core (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * idx, int longonly) static
Definition at line 53 of file getopt_long.c.
 {
     optarg = 0;
     if (longopts && argv[optind][0] == '-' &&
         ((longonly && argv[optind][1] && argv[optind][1] != '-') ||
          (argv[optind][1] == '-' && argv[optind][2])))
     {
         int colon = optstring[optstring[0]=='+'||optstring[0]=='-']==':';
         int i, cnt, match;
         char *arg, *opt, *start = argv[optind]+1;
         for (cnt=i=0; longopts[i].name; i++) {
             const char *name = longopts[i].name;
             opt = start;
             if (*opt == '-') opt++;
             while (*opt && *opt != '=' && *opt == *name)
                 name++, opt++;
             if (*opt && *opt != '=') continue;
             arg = opt;
             match = i;
             if (!*name) {
                 cnt = 1;
                 break;
             }
             cnt++;
         }
         if (cnt==1 && longonly && arg-start == mblen(start, MB_LEN_MAX)) {
             int l = arg-start;
             for (i=0; optstring[i]; i++) {
                 int j;
                 for (j=0; j<l && start[j]==optstring[i+j]; j++);
                 if (j==l) {
                     cnt++;
                     break;
                 }
             }
         }
         if (cnt==1) {
             i = match;
             opt = arg;
             optind++;
             if (*opt == '=') {
                 if (!longopts[i].has_arg) {
                     optopt = longopts[i].val;
                     if (colon || !opterr)
                         return '?';
                     __getopt_msg(argv[0],
                         ": option does not take an argument: ",
                         longopts[i].name,
                         strlen(longopts[i].name));
                     return '?';
                 }
                 optarg = opt+1;
             } else if (longopts[i].has_arg == required_argument) {
                 if (!(optarg = argv[optind])) {
                     optopt = longopts[i].val;
                     if (colon) return ':';
                     if (!opterr) return '?';
                     __getopt_msg(argv[0],
                         ": option requires an argument: ",
                         longopts[i].name,
                         strlen(longopts[i].name));
                     return '?';
                 }
                 optind++;
             }
             if (idx) *idx = i;
             if (longopts[i].flag) {
                 *longopts[i].flag = longopts[i].val;
                 return 0;
             }
             return longopts[i].val;
         }
         if (argv[optind][1] == '-') {
             optopt = 0;
             if (!colon && opterr)
                 __getopt_msg(argv[0], cnt ?
                     ": option is ambiguous: " :
                     ": unrecognized option: ",
                     argv[optind]+2,
                     strlen(argv[optind]+2));
             optind++;
             return '?';
         }
     }
     return getopt(argc, argv, optstring);
 }
References __getopt_msg(), argc, argv, cnt, colon, option::flag, getopt(), i, idx, j, match(), MB_LEN_MAX, mblen(), option::name, name, optarg, opterr, optind, optopt, required_argument, start(), strlen(), and option::val.
Referenced by __getopt_long().
getopt_long()
int getopt_long (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * idx)
Definition at line 140 of file getopt_long.c.
 {
     return __getopt_long(argc, argv, optstring, longopts, idx, 0);
 }
References __getopt_long(), argc, argv, and idx.
getopt_long_only()
int getopt_long_only (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * idx)
Definition at line 145 of file getopt_long.c.
 {
     return __getopt_long(argc, argv, optstring, longopts, idx, 1);
 }
References __getopt_long(), argc, argv, and idx.
permute()
static void permute (char *const * argv, int dest, int src) static
Definition at line 12 of file getopt_long.c.
 {
     char **av = (char **)argv;
     char *tmp = av[src];
     int i;
     for (i=src; i>dest; i--)
         av[i] = av[i-1];
     av[dest] = tmp;
 }
References argv, and i.
Referenced by __getopt_long().
Variable Documentation
__optpos
int __optpos extern
Definition at line 11 of file getopt.c.
Referenced by __getopt_long(), and getopt().
__optreset
int __optreset
Definition at line 10 of file getopt_long.c.
Referenced by __getopt_long().