Fennix: VirtualFileSystem::File Struct Reference
VirtualFileSystem::File Struct Reference
#include <filesystem.hpp>
Public Member Functions
bool IsOK ()
size_t GetLength ()
std::vector< Node * > GetChildren ()
NodeFlags GetFlags ()
Node * GetNode ()
Special cases only.
Data Fields
char Name [FILENAME_LENGTH]
FileStatus Status
Private Attributes
Node * node
off_t ContextOffset
Friends
class Virtual
Detailed Description
Definition at line 134 of file filesystem.hpp.
Member Function Documentation
GetChildren()
std::vector<Node *> VirtualFileSystem::File::GetChildren () inline
Definition at line 148 of file filesystem.hpp.
         {
             return node->Children;
         }
GetFlags()
NodeFlags VirtualFileSystem::File::GetFlags () inline
Definition at line 153 of file filesystem.hpp.
         {
             return node->Flags;
         }
Referenced by Execute::ELFLoad(), Main(), and Execute::Spawn().
GetLength()
size_t VirtualFileSystem::File::GetLength () inline
Definition at line 143 of file filesystem.hpp.
         {
             return node->Length;
         }
Referenced by BootLogoAnimationThread(), Execute::ELFLoad(), and Recovery::PlayAudio().
GetNode()
Node* VirtualFileSystem::File::GetNode () inline
Special cases only.
Definition at line 159 of file filesystem.hpp.
         {
             return node;
         }
References node.
Referenced by Main().
IsOK()
bool VirtualFileSystem::File::IsOK () inline
Definition at line 138 of file filesystem.hpp.
         {
             return Status == FileStatus::OK;
         }
References OK, and Status.
Referenced by BootLogoAnimationThread(), Execute::GetBinaryType(), Driver::Driver::LoadDrivers(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), Recovery::PlayAudio(), Execute::Spawn(), sys_file_open(), and sys_kernelctl().
Friends And Related Function Documentation
Virtual
friend class Virtual friend
Definition at line 168 of file filesystem.hpp.
Field Documentation
ContextOffset
off_t VirtualFileSystem::File::ContextOffset private
Definition at line 166 of file filesystem.hpp.
Referenced by VirtualFileSystem::Virtual::Seek().
Name
char VirtualFileSystem::File::Name[FILENAME_LENGTH]
Definition at line 136 of file filesystem.hpp.
Referenced by VirtualFileSystem::Virtual::Close(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), VirtualFileSystem::Virtual::Read(), sys_file_close(), sys_file_open(), sys_file_seek(), VirtualFileSystem::Virtual::Unmount(), and VirtualFileSystem::Virtual::Write().
node
Node* VirtualFileSystem::File::node private
Definition at line 165 of file filesystem.hpp.
Referenced by VirtualFileSystem::Virtual::Close(), GetNode(), VirtualFileSystem::Virtual::Open(), VirtualFileSystem::Virtual::Read(), VirtualFileSystem::Virtual::Seek(), VirtualFileSystem::Virtual::Unmount(), and VirtualFileSystem::Virtual::Write().
Status
FileStatus VirtualFileSystem::File::Status
Definition at line 137 of file filesystem.hpp.
Referenced by VirtualFileSystem::Virtual::ConvertNodeToFILE(), Execute::ELFLoad(), IsOK(), Driver::Driver::LoadDrivers(), VirtualFileSystem::Virtual::Mount(), VirtualFileSystem::Virtual::Read(), VirtualFileSystem::Virtual::Seek(), Execute::Spawn(), sys_file_close(), sys_file_open(), and VirtualFileSystem::Virtual::Write().
The documentation for this struct was generated from the following file:
Kernel/include/filesystem.hpp