Fennix: Userspace/mlibc/options/ansi/include/math.h File Reference
math.h File Reference
#include <bits/inline-definition.h>
Macros
#define M_E 2.7182818284590452354
#define M_LOG2E 1.4426950408889634074
#define M_LOG10E 0.43429448190325182765
#define M_LN2 0.69314718055994530942
#define M_LN10 2.30258509299404568402
#define M_PI 3.14159265358979323846
#define M_PI_2 1.57079632679489661923
#define M_PI_4 0.78539816339744830962
#define M_1_PI 0.31830988618379067154
#define M_2_PI 0.63661977236758134308
#define M_2_SQRTPI 1.12837916709551257390
#define M_SQRT2 1.41421356237309504880
#define M_SQRT1_2 0.70710678118654752440
#define FP_ILOGBNAN (-1 - (int)(((unsigned)-1) >> 1))
#define FP_ILOGB0 FP_ILOGBNAN
#define HUGE_VAL (__builtin_huge_val())
#define HUGE_VALF (__builtin_huge_valf())
#define HUGE_VALL (__builtin_huge_vall())
#define INFINITY (__builtin_inff())
#define NAN (__builtin_nanf(""))
#define MATH_ERRNO 1
#define MATH_ERREXCEPT 2
#define math_errhandling 3
#define FP_INFINITE 1
#define FP_NAN 2
#define FP_NORMAL 4
#define FP_SUBNORMAL 8
#define FP_ZERO 16
#define fpclassify(x)
#define isfinite(x) (fpclassify(x) & (FP_NORMAL | FP_SUBNORMAL | FP_ZERO))
#define isnan(x) (fpclassify(x) == FP_NAN)
#define isinf(x) (fpclassify(x) == FP_INFINITE)
#define isnormal(x) (fpclassify(x) == FP_NORMAL)
#define signbit(x) (__builtin_signbit(x))
#define isunordered(x, y) (isnan((x)) ? ((void)(y),1) : isnan((y)))
#define __MLIBC_CHOOSE_COMPARISON(x, y, p)
#define isless(x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_isless)
#define islessequal(x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_islessequal)
#define islessgreater(x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_islessgreater)
#define isgreater(x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_isgreater)
#define isgreaterequal(x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_isgreaterequal)
Typedefs
typedef double double_t
typedef float float_t
Functions
int __fpclassify (double x)
int __fpclassifyf (float x)
int __fpclassifyl (long double x)
__MLIBC_INLINE_DEFINITION int __mlibc_isless (double_t x, double_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessf (float_t x, float_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessl (long double x, long double y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessequal (double_t x, double_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessequalf (float_t x, float_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessequall (long double x, long double y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessgreater (double_t x, double_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessgreaterf (float_t x, float_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_islessgreaterl (long double x, long double y)
__MLIBC_INLINE_DEFINITION int __mlibc_isgreater (double_t x, double_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterf (float_t x, float_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterl (long double x, long double y)
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterequal (double_t x, double_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterequalf (float_t x, float_t y)
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterequall (long double x, long double y)
void sincos (double, double *, double *)
void sincosf (float, float *, float *)
void sincosl (long double, long double *, long double *)
double exp10 (double)
float exp10f (float)
long double exp10l (long double)
double pow10 (double)
float pow10f (float)
long double pow10l (long double)
double acos (double x)
float acosf (float x)
long double acosl (long double x)
double asin (double x)
float asinf (float x)
long double asinl (long double x)
double atan (double x)
float atanf (float x)
long double atanl (long double x)
double atan2 (double x, double y)
float atan2f (float x, float y)
long double atan2l (long double x, long double y)
double cos (double x)
float cosf (float x)
long double cosl (long double x)
double sin (double x)
float sinf (float x)
long double sinl (long double x)
double tan (double x)
float tanf (float x)
long double tanl (long double x)
double acosh (double x)
float acoshf (float x)
long double acoshl (long double x)
double asinh (double x)
float asinhf (float x)
long double asinhl (long double x)
double atanh (double x)
float atanhf (float x)
long double atanhl (long double x)
double cosh (double x)
float coshf (float x)
long double coshl (long double x)
double sinh (double x)
float sinhf (float x)
long double sinhl (long double x)
double tanh (double x)
float tanhf (float x)
long double tanhl (long double x)
double exp (double x)
float expf (float x)
long double expl (long double x)
double exp2 (double x)
float exp2f (float x)
long double exp2l (long double x)
double expm1 (double x)
float expm1f (float x)
long double expm1l (long double x)
double frexp (double x, int *power)
float frexpf (float x, int *power)
long double frexpl (long double x, int *power)
int ilogb (double x)
int ilogbf (float x)
int ilogbl (long double x)
double ldexp (double x, int power)
float ldexpf (float x, int power)
long double ldexpl (long double x, int power)
double log (double x)
float logf (float x)
long double logl (long double x)
double log10 (double x)
float log10f (float x)
long double log10l (long double x)
double log1p (double x)
float log1pf (float x)
long double log1pl (long double x)
double log2 (double x)
float log2f (float x)
long double log2l (long double x)
double logb (double x)
float logbf (float x)
long double logbl (long double x)
double modf (double x, double *integral)
float modff (float x, float *integral)
long double modfl (long double x, long double *integral)
double scalbn (double x, int power)
float scalbnf (float x, int power)
long double scalbnl (long double x, int power)
double scalbln (double x, long power)
float scalblnf (float x, long power)
long double scalblnl (long double x, long power)
double cbrt (double x)
float cbrtf (float x)
long double cbrtl (long double x)
double fabs (double x)
float fabsf (float x)
long double fabsl (long double x)
double hypot (double x, double y)
float hypotf (float x, float y)
long double hypotl (long double x, long double y)
double pow (double x, double y)
float powf (float x, float y)
long double powl (long double x, long double y)
double sqrt (double x)
float sqrtf (float x)
long double sqrtl (long double x)
double erf (double x)
float erff (float x)
long double erfl (long double x)
double erfc (double x)
float erfcf (float x)
long double erfcl (long double x)
double lgamma (double x)
float lgammaf (float x)
long double lgammal (long double x)
double tgamma (double x)
float tgammaf (float x)
long double tgammal (long double x)
double ceil (double x)
float ceilf (float x)
long double ceill (long double x)
double floor (double x)
float floorf (float x)
long double floorl (long double x)
double nearbyint (double x)
float nearbyintf (float x)
long double nearbyintl (long double x)
double rint (double x)
float rintf (float x)
long double rintl (long double x)
long lrint (double x)
long lrintf (float x)
long lrintl (long double x)
long long llrint (double x)
long long llrintf (float x)
long long llrintl (long double x)
double round (double x)
float roundf (float x)
long double roundl (long double x)
long lround (double x)
long lroundf (float x)
long lroundl (long double x)
long long llround (double x)
long long llroundf (float x)
long long llroundl (long double x)
double trunc (double x)
float truncf (float x)
long double truncl (long double x)
double fmod (double x, double y)
float fmodf (float x, float y)
long double fmodl (long double x, long double y)
double remainder (double x, double y)
float remainderf (float x, float y)
long double remainderl (long double x, long double y)
double remquo (double x, double y, int *quotient)
float remquof (float x, float y, int *quotient)
long double remquol (long double x, long double y, int *quotient)
double copysign (double x, double sign)
float copysignf (float x, float sign)
long double copysignl (long double x, long double sign)
double nan (const char *tag)
float nanf (const char *tag)
long double nanl (const char *tag)
double nextafter (double x, double dir)
float nextafterf (float x, float dir)
long double nextafterl (long double x, long double dir)
double nexttoward (double x, long double dir)
float nexttowardf (float x, long double dir)
long double nexttowardl (long double x, long double dir)
double fdim (double x, double y)
float fdimf (float x, float y)
long double fdiml (long double x, long double y)
double fmax (double x, double y)
float fmaxf (float x, float y)
long double fmaxl (long double x, long double y)
double fmin (double x, double y)
float fminf (float x, float y)
long double fminl (long double x, long double y)
double fma (double, double, double)
float fmaf (float, float, float)
long double fmal (long double, long double, long double)
Macro Definition Documentation
__MLIBC_CHOOSE_COMPARISON
#define __MLIBC_CHOOSE_COMPARISON (x, y, p)
Value:
    ( \
    sizeof((x)+(y)) == sizeof(float) ? p##f(x, y) : \
    sizeof((x)+(y)) == sizeof(double) ? p(x, y) : \
    p##l(x, y) )
Definition at line 93 of file math.h.
FP_ILOGB0
#define FP_ILOGB0 FP_ILOGBNAN
Definition at line 24 of file math.h.
FP_ILOGBNAN
#define FP_ILOGBNAN (-1 - (int)(((unsigned)-1) >> 1))
Definition at line 23 of file math.h.
FP_INFINITE
#define FP_INFINITE 1
Definition at line 49 of file math.h.
FP_NAN
#define FP_NAN 2
Definition at line 50 of file math.h.
FP_NORMAL
#define FP_NORMAL 4
Definition at line 51 of file math.h.
FP_SUBNORMAL
#define FP_SUBNORMAL 8
Definition at line 52 of file math.h.
FP_ZERO
#define FP_ZERO 16
Definition at line 53 of file math.h.
fpclassify
#define fpclassify (x)
Value:
    (sizeof(x) == sizeof(double) ? __fpclassify(x) : \
    (sizeof(x) == sizeof(float) ? __fpclassifyf(x) : \
    (sizeof(x) == sizeof(long double) ? __fpclassifyl(x) : \
    0)))
Definition at line 59 of file math.h.
HUGE_VAL
#define HUGE_VAL (__builtin_huge_val())
Definition at line 33 of file math.h.
HUGE_VALF
#define HUGE_VALF (__builtin_huge_valf())
Definition at line 34 of file math.h.
HUGE_VALL
#define HUGE_VALL (__builtin_huge_vall())
Definition at line 35 of file math.h.
INFINITY
#define INFINITY (__builtin_inff())
Definition at line 36 of file math.h.
isfinite
#define isfinite (x) (fpclassify(x) & (FP_NORMAL | FP_SUBNORMAL | FP_ZERO))
Definition at line 65 of file math.h.
isgreater
#define isgreater (x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_isgreater)
Definition at line 101 of file math.h.
isgreaterequal
#define isgreaterequal (x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_isgreaterequal)
Definition at line 102 of file math.h.
isinf
#define isinf (x) (fpclassify(x) == FP_INFINITE)
Definition at line 67 of file math.h.
isless
#define isless (x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_isless)
Definition at line 98 of file math.h.
islessequal
#define islessequal (x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_islessequal)
Definition at line 99 of file math.h.
islessgreater
#define islessgreater (x, y) __MLIBC_CHOOSE_COMPARISON(x, y, __mlibc_islessgreater)
Definition at line 100 of file math.h.
isnan
#define isnan (x) (fpclassify(x) == FP_NAN)
Definition at line 66 of file math.h.
isnormal
#define isnormal (x) (fpclassify(x) == FP_NORMAL)
Definition at line 68 of file math.h.
isunordered
#define isunordered (x, y) (isnan((x)) ? ((void)(y),1) : isnan((y)))
Definition at line 74 of file math.h.
M_1_PI
#define M_1_PI 0.31830988618379067154
Definition at line 16 of file math.h.
M_2_PI
#define M_2_PI 0.63661977236758134308
Definition at line 17 of file math.h.
M_2_SQRTPI
#define M_2_SQRTPI 1.12837916709551257390
Definition at line 18 of file math.h.
M_E
#define M_E 2.7182818284590452354
Definition at line 8 of file math.h.
M_LN10
#define M_LN10 2.30258509299404568402
Definition at line 12 of file math.h.
M_LN2
#define M_LN2 0.69314718055994530942
Definition at line 11 of file math.h.
M_LOG10E
#define M_LOG10E 0.43429448190325182765
Definition at line 10 of file math.h.
M_LOG2E
#define M_LOG2E 1.4426950408889634074
Definition at line 9 of file math.h.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 13 of file math.h.
M_PI_2
#define M_PI_2 1.57079632679489661923
Definition at line 14 of file math.h.
M_PI_4
#define M_PI_4 0.78539816339744830962
Definition at line 15 of file math.h.
M_SQRT1_2
#define M_SQRT1_2 0.70710678118654752440
Definition at line 20 of file math.h.
M_SQRT2
#define M_SQRT2 1.41421356237309504880
Definition at line 19 of file math.h.
MATH_ERREXCEPT
#define MATH_ERREXCEPT 2
Definition at line 42 of file math.h.
math_errhandling
#define math_errhandling 3
Definition at line 43 of file math.h.
MATH_ERRNO
#define MATH_ERRNO 1
Definition at line 41 of file math.h.
NAN
#define NAN (__builtin_nanf(""))
Definition at line 37 of file math.h.
signbit
#define signbit (x) (__builtin_signbit(x))
Definition at line 71 of file math.h.
Typedef Documentation
double_t
typedef double double_t
Definition at line 30 of file math.h.
float_t
typedef float float_t
Definition at line 31 of file math.h.
Function Documentation
__fpclassify()
int __fpclassify (double x)
Definition at line 4 of file __fpclassify.c.
 {
     union {double f; uint64_t i;} u = {x};
     int e = u.i>>52 & 0x7ff;
     if (!e) return u.i<<1 ? FP_SUBNORMAL : FP_ZERO;
     if (e==0x7ff) return u.i<<12 ? FP_NAN : FP_INFINITE;
     return FP_NORMAL;
 }
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, i, and x.
__fpclassifyf()
int __fpclassifyf (float x)
Definition at line 4 of file __fpclassifyf.c.
 {
     union {float f; uint32_t i;} u = {x};
     int e = u.i>>23 & 0xff;
     if (!e) return u.i<<1 ? FP_SUBNORMAL : FP_ZERO;
     if (e==0xff) return u.i<<9 ? FP_NAN : FP_INFINITE;
     return FP_NORMAL;
 }
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, i, and x.
__fpclassifyl()
int __fpclassifyl (long double x)
__mlibc_isgreater()
__MLIBC_INLINE_DEFINITION int __mlibc_isgreater (double_t x, double_t y)
Definition at line 85 of file math.h.
 { return !isunordered(x, y) && x > y; }
References isunordered, x, and y.
__mlibc_isgreaterequal()
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterequal (double_t x, double_t y)
Definition at line 88 of file math.h.
 { return !isunordered(x, y) && x >= y; }
References isunordered, x, and y.
__mlibc_isgreaterequalf()
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterequalf (float_t x, float_t y)
Definition at line 89 of file math.h.
 { return !isunordered(x, y) && x >= y; }
References isunordered, x, and y.
__mlibc_isgreaterequall()
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterequall (long double x, long double y)
Definition at line 90 of file math.h.
 { return !isunordered(x, y) && x >= y; }
References isunordered, x, and y.
__mlibc_isgreaterf()
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterf (float_t x, float_t y)
Definition at line 86 of file math.h.
 { return !isunordered(x, y) && x > y; }
References isunordered, x, and y.
__mlibc_isgreaterl()
__MLIBC_INLINE_DEFINITION int __mlibc_isgreaterl (long double x, long double y)
Definition at line 87 of file math.h.
 { return !isunordered(x, y) && x > y; }
References isunordered, x, and y.
__mlibc_isless()
__MLIBC_INLINE_DEFINITION int __mlibc_isless (double_t x, double_t y)
Definition at line 76 of file math.h.
 { return !isunordered(x, y) && x < y; }
References isunordered, x, and y.
__mlibc_islessequal()
__MLIBC_INLINE_DEFINITION int __mlibc_islessequal (double_t x, double_t y)
Definition at line 79 of file math.h.
 { return !isunordered(x, y) && x <= y; }
References isunordered, x, and y.
__mlibc_islessequalf()
__MLIBC_INLINE_DEFINITION int __mlibc_islessequalf (float_t x, float_t y)
Definition at line 80 of file math.h.
 { return !isunordered(x, y) && x <= y; }
References isunordered, x, and y.
__mlibc_islessequall()
__MLIBC_INLINE_DEFINITION int __mlibc_islessequall (long double x, long double y)
Definition at line 81 of file math.h.
 { return !isunordered(x, y) && x <= y; }
References isunordered, x, and y.
__mlibc_islessf()
__MLIBC_INLINE_DEFINITION int __mlibc_islessf (float_t x, float_t y)
Definition at line 77 of file math.h.
 { return !isunordered(x, y) && x < y; }
References isunordered, x, and y.
__mlibc_islessgreater()
__MLIBC_INLINE_DEFINITION int __mlibc_islessgreater (double_t x, double_t y)
Definition at line 82 of file math.h.
 { return !isunordered(x, y) && x != y; }
References isunordered, x, and y.
__mlibc_islessgreaterf()
__MLIBC_INLINE_DEFINITION int __mlibc_islessgreaterf (float_t x, float_t y)
Definition at line 83 of file math.h.
 { return !isunordered(x, y) && x != y; }
References isunordered, x, and y.
__mlibc_islessgreaterl()
__MLIBC_INLINE_DEFINITION int __mlibc_islessgreaterl (long double x, long double y)
Definition at line 84 of file math.h.
 { return !isunordered(x, y) && x != y; }
References isunordered, x, and y.
__mlibc_islessl()
__MLIBC_INLINE_DEFINITION int __mlibc_islessl (long double x, long double y)
Definition at line 78 of file math.h.
 { return !isunordered(x, y) && x < y; }
References isunordered, x, and y.
acos()
double acos (double x)
Definition at line 60 of file acos.c.
 {
     double z,w,s,c,df;
     uint32_t hx,ix;
     GET_HIGH_WORD(hx, x);
     ix = hx & 0x7fffffff;
     /* |x| >= 1 or nan */
     if (ix >= 0x3ff00000) {
         uint32_t lx;
         GET_LOW_WORD(lx,x);
         if ((ix-0x3ff00000 | lx) == 0) {
             /* acos(1)=0, acos(-1)=pi */
             if (hx >> 31)
                 return 2*pio2_hi + 0x1p-120f;
             return 0;
         }
         return 0/(x-x);
     }
     /* |x| < 0.5 */
     if (ix < 0x3fe00000) {
         if (ix <= 0x3c600000)  /* |x| < 2**-57 */
             return pio2_hi + 0x1p-120f;
         return pio2_hi - (x - (pio2_lo-x*R(x*x)));
     }
     /* x < -0.5 */
     if (hx >> 31) {
         z = (1.0+x)*0.5;
         s = sqrt(z);
         w = R(z)*s-pio2_lo;
         return 2*(pio2_hi - (s+w));
     }
     /* x > 0.5 */
     z = (1.0-x)*0.5;
     s = sqrt(z);
     df = s;
     SET_LOW_WORD(df,0);
     c = (z-df*df)/(s+df);
     w = R(z)*s+c;
     return 2*(df+w);
 }
References c, GET_HIGH_WORD, GET_LOW_WORD, pio2_hi, pio2_lo, R(), SET_LOW_WORD, sqrt(), and x.
acosf()
float acosf (float x)
Definition at line 34 of file acosf.c.
 {
     float z,w,s,c,df;
     uint32_t hx,ix;
     GET_FLOAT_WORD(hx, x);
     ix = hx & 0x7fffffff;
     /* |x| >= 1 or nan */
     if (ix >= 0x3f800000) {
         if (ix == 0x3f800000) {
             if (hx >> 31)
                 return 2*pio2_hi + 0x1p-120f;
             return 0;
         }
         return 0/(x-x);
     }
     /* |x| < 0.5 */
     if (ix < 0x3f000000) {
         if (ix <= 0x32800000) /* |x| < 2**-26 */
             return pio2_hi + 0x1p-120f;
         return pio2_hi - (x - (pio2_lo-x*R(x*x)));
     }
     /* x < -0.5 */
     if (hx >> 31) {
         z = (1+x)*0.5f;
         s = sqrtf(z);
         w = R(z)*s-pio2_lo;
         return 2*(pio2_hi - (s+w));
     }
     /* x > 0.5 */
     z = (1-x)*0.5f;
     s = sqrtf(z);
     GET_FLOAT_WORD(hx,s);
     SET_FLOAT_WORD(df,hx&0xfffff000);
     c = (z-df*df)/(s+df);
     w = R(z)*s+c;
     return 2*(df+w);
 }
References c, GET_FLOAT_WORD, pio2_hi, pio2_lo, R(), SET_FLOAT_WORD, sqrtf(), and x.
acosh()
double acosh (double x)
Definition at line 9 of file acosh.c.
 {
     union {double f; uint64_t i;} u = {.f = x};
     unsigned e = u.i >> 52 & 0x7ff;
     /* x < 1 domain error is handled in the called functions */
     if (e < 0x3ff + 1)
         /* |x| < 2, up to 2ulp error in [1,1.125] */
         return log1p(x-1 + sqrt((x-1)*(x-1)+2*(x-1)));
     if (e < 0x3ff + 26)
         /* |x| < 0x1p26 */
         return log(2*x - 1/(x+sqrt(x*x-1)));
     /* |x| >= 0x1p26 or nan */
     return log(x) + 0.693147180559945309417232121458176568;
 }
References i, log(), log1p(), sqrt(), and x.
acoshf()
float acoshf (float x)
Definition at line 12 of file acoshf.c.
 {
     union {float f; uint32_t i;} u = {x};
     uint32_t a = u.i & 0x7fffffff;
     if (a < 0x3f800000+(1<<23))
         /* |x| < 2, invalid if x < 1 or nan */
         /* up to 2ulp error in [1,1.125] */
         return log1pf(x-1 + sqrtf((x-1)*(x-1)+2*(x-1)));
     if (a < 0x3f800000+(12<<23))
         /* |x| < 0x1p12 */
         return logf(2*x - 1/(x+sqrtf(x*x-1)));
     /* x >= 0x1p12 */
     return logf(x) + 0.693147180559945309417232121458176568f;
 }
References i, log1pf(), logf(), sqrtf(), and x.
acoshl()
long double acoshl (long double x)
acosl()
long double acosl (long double x)
asin()
double asin (double x)
Definition at line 67 of file asin.c.
 {
     double z,r,s;
     uint32_t hx,ix;
     GET_HIGH_WORD(hx, x);
     ix = hx & 0x7fffffff;
     /* |x| >= 1 or nan */
     if (ix >= 0x3ff00000) {
         uint32_t lx;
         GET_LOW_WORD(lx, x);
         if ((ix-0x3ff00000 | lx) == 0)
             /* asin(1) = +-pi/2 with inexact */
             return x*pio2_hi + 0x1p-120f;
         return 0/(x-x);
     }
     /* |x| < 0.5 */
     if (ix < 0x3fe00000) {
         /* if 0x1p-1022 <= |x| < 0x1p-26, avoid raising underflow */
         if (ix < 0x3e500000 && ix >= 0x00100000)
             return x;
         return x + x*R(x*x);
     }
     /* 1 > |x| >= 0.5 */
     z = (1 - fabs(x))*0.5;
     s = sqrt(z);
     r = R(z);
     if (ix >= 0x3fef3333) {  /* if |x| > 0.975 */
         x = pio2_hi-(2*(s+s*r)-pio2_lo);
     } else {
         double f,c;
         /* f+c = sqrt(z) */
         f = s;
         SET_LOW_WORD(f,0);
         c = (z-f*f)/(s+f);
         x = 0.5*pio2_hi - (2*s*r - (pio2_lo-2*c) - (0.5*pio2_hi-2*f));
     }
     if (hx >> 31)
         return -x;
     return x;
 }
References c, fabs(), GET_HIGH_WORD, GET_LOW_WORD, pio2_hi, pio2_lo, r, R(), SET_LOW_WORD, sqrt(), and x.
Referenced by casin().
asinf()
float asinf (float x)
Definition at line 35 of file asinf.c.
 {
     double s;
     float z;
     uint32_t hx,ix;
     GET_FLOAT_WORD(hx, x);
     ix = hx & 0x7fffffff;
     if (ix >= 0x3f800000) {  /* |x| >= 1 */
         if (ix == 0x3f800000)  /* |x| == 1 */
             return x*pio2 + 0x1p-120f;  /* asin(+-1) = +-pi/2 with inexact */
         return 0/(x-x);  /* asin(|x|>1) is NaN */
     }
     if (ix < 0x3f000000) {  /* |x| < 0.5 */
         /* if 0x1p-126 <= |x| < 0x1p-12, avoid raising underflow */
         if (ix < 0x39800000 && ix >= 0x00800000)
             return x;
         return x + x*R(x*x);
     }
     /* 1 > |x| >= 0.5 */
     z = (1 - fabsf(x))*0.5f;
     s = sqrt(z);
     x = pio2 - 2*(s+s*R(z));
     if (hx >> 31)
         return -x;
     return x;
 }
References fabsf(), GET_FLOAT_WORD, pio2, R(), sqrt(), and x.
Referenced by casinf().
asinh()
double asinh (double x)
Definition at line 4 of file asinh.c.
 {
     union {double f; uint64_t i;} u = {.f = x};
     unsigned e = u.i >> 52 & 0x7ff;
     unsigned s = u.i >> 63;
     /* |x| */
     u.i &= (uint64_t)-1/2;
     x = u.f;
     if (e >= 0x3ff + 26) {
         /* |x| >= 0x1p26 or inf or nan */
         x = log(x) + 0.693147180559945309417232121458176568;
     } else if (e >= 0x3ff + 1) {
         /* |x| >= 2 */
         x = log(2*x + 1/(sqrt(x*x+1)+x));
     } else if (e >= 0x3ff - 26) {
         /* |x| >= 0x1p-26, up to 1.6ulp error in [0.125,0.5] */
         x = log1p(x + x*x/(sqrt(x*x+1)+1));
     } else {
         /* |x| < 0x1p-26, raise inexact if x != 0 */
         FORCE_EVAL(x + 0x1p120f);
     }
     return s ? -x : x;
 }
References FORCE_EVAL, i, log(), log1p(), sqrt(), and x.
asinhf()
float asinhf (float x)
Definition at line 4 of file asinhf.c.
 {
     union {float f; uint32_t i;} u = {.f = x};
     uint32_t i = u.i & 0x7fffffff;
     unsigned s = u.i >> 31;
     /* |x| */
     u.i = i;
     x = u.f;
     if (i >= 0x3f800000 + (12<<23)) {
         /* |x| >= 0x1p12 or inf or nan */
         x = logf(x) + 0.693147180559945309417232121458176568f;
     } else if (i >= 0x3f800000 + (1<<23)) {
         /* |x| >= 2 */
         x = logf(2*x + 1/(sqrtf(x*x+1)+x));
     } else if (i >= 0x3f800000 - (12<<23)) {
         /* |x| >= 0x1p-12, up to 1.6ulp error in [0.125,0.5] */
         x = log1pf(x + x*x/(sqrtf(x*x+1)+1));
     } else {
         /* |x| < 0x1p-12, raise inexact if x!=0 */
         FORCE_EVAL(x + 0x1p120f);
     }
     return s ? -x : x;
 }
References FORCE_EVAL, i, log1pf(), logf(), sqrtf(), and x.
asinhl()
long double asinhl (long double x)
asinl()
long double asinl (long double x)
atan()
double atan (double x)
Definition at line 63 of file atan.c.
 {
     double_t w,s1,s2,z;
     uint32_t ix,sign;
     int id;
     GET_HIGH_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     if (ix >= 0x44100000) {   /* if |x| >= 2^66 */
         if (isnan(x))
             return x;
         z = atanhi[3] + 0x1p-120f;
         return sign ? -z : z;
     }
     if (ix < 0x3fdc0000) {    /* |x| < 0.4375 */
         if (ix < 0x3e400000) {  /* |x| < 2^-27 */
             if (ix < 0x00100000)
                 /* raise underflow for subnormal x */
                 FORCE_EVAL((float)x);
             return x;
         }
         id = -1;
     } else {
         x = fabs(x);
         if (ix < 0x3ff30000) {  /* |x| < 1.1875 */
             if (ix < 0x3fe60000) {  /*  7/16 <= |x| < 11/16 */
                 id = 0;
                 x = (2.0*x-1.0)/(2.0+x);
             } else {                /* 11/16 <= |x| < 19/16 */
                 id = 1;
                 x = (x-1.0)/(x+1.0);
             }
         } else {
             if (ix < 0x40038000) {  /* |x| < 2.4375 */
                 id = 2;
                 x = (x-1.5)/(1.0+1.5*x);
             } else {                /* 2.4375 <= |x| < 2^66 */
                 id = 3;
                 x = -1.0/x;
             }
         }
     }
     /* end of argument reduction */
     z = x*x;
     w = z*z;
     /* break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly */
     s1 = z*(aT[0]+w*(aT[2]+w*(aT[4]+w*(aT[6]+w*(aT[8]+w*aT[10])))));
     s2 = w*(aT[1]+w*(aT[3]+w*(aT[5]+w*(aT[7]+w*aT[9]))));
     if (id < 0)
         return x - x*(s1+s2);
     z = atanhi[id] - (x*(s1+s2) - atanlo[id] - x);
     return sign ? -z : z;
 }
References aT, atanhi, atanlo, fabs(), FORCE_EVAL, GET_HIGH_WORD, isnan, s1, s2, and x.
Referenced by atan2(), and R_InitPointToAngle().
atan2()
double atan2 (double x, double y)
Definition at line 46 of file atan2.c.
 {
     double z;
     uint32_t m,lx,ly,ix,iy;
     if (isnan(x) || isnan(y))
         return x+y;
     EXTRACT_WORDS(ix, lx, x);
     EXTRACT_WORDS(iy, ly, y);
     if ((ix-0x3ff00000 | lx) == 0)  /* x = 1.0 */
         return atan(y);
     m = ((iy>>31)&1) | ((ix>>30)&2);  /* 2*sign(x)+sign(y) */
     ix = ix & 0x7fffffff;
     iy = iy & 0x7fffffff;
     /* when y = 0 */
     if ((iy|ly) == 0) {
         switch(m) {
         case 0:
         case 1: return y;   /* atan(+-0,+anything)=+-0 */
         case 2: return  pi; /* atan(+0,-anything) = pi */
         case 3: return -pi; /* atan(-0,-anything) =-pi */
         }
     }
     /* when x = 0 */
     if ((ix|lx) == 0)
         return m&1 ? -pi/2 : pi/2;
     /* when x is INF */
     if (ix == 0x7ff00000) {
         if (iy == 0x7ff00000) {
             switch(m) {
             case 0: return  pi/4;   /* atan(+INF,+INF) */
             case 1: return -pi/4;   /* atan(-INF,+INF) */
             case 2: return  3*pi/4; /* atan(+INF,-INF) */
             case 3: return -3*pi/4; /* atan(-INF,-INF) */
             }
         } else {
             switch(m) {
             case 0: return  0.0; /* atan(+...,+INF) */
             case 1: return -0.0; /* atan(-...,+INF) */
             case 2: return  pi;  /* atan(+...,-INF) */
             case 3: return -pi;  /* atan(-...,-INF) */
             }
         }
     }
     /* |y/x| > 0x1p64 */
     if (ix+(64<<20) < iy || iy == 0x7ff00000)
         return m&1 ? -pi/2 : pi/2;
     /* z = atan(|y/x|) without spurious underflow */
     if ((m&2) && iy+(64<<20) < ix)  /* |y/x| < 0x1p-64, x<0 */
         z = 0;
     else
         z = atan(fabs(y/x));
     switch (m) {
     case 0: return z;              /* atan(+,+) */
     case 1: return -z;             /* atan(-,+) */
     case 2: return pi - (z-pi_lo); /* atan(+,-) */
     default: /* case 3 */
         return (z-pi_lo) - pi; /* atan(-,-) */
     }
 }
References atan(), EXTRACT_WORDS, fabs(), isnan, pi, pi_lo, x, and y.
Referenced by carg(), catan(), and clog().
atan2f()
float atan2f (float x, float y)
Definition at line 22 of file atan2f.c.
 {
     float z;
     uint32_t m,ix,iy;
     if (isnan(x) || isnan(y))
         return x+y;
     GET_FLOAT_WORD(ix, x);
     GET_FLOAT_WORD(iy, y);
     if (ix == 0x3f800000)  /* x=1.0 */
         return atanf(y);
     m = ((iy>>31)&1) | ((ix>>30)&2);  /* 2*sign(x)+sign(y) */
     ix &= 0x7fffffff;
     iy &= 0x7fffffff;
     /* when y = 0 */
     if (iy == 0) {
         switch (m) {
         case 0:
         case 1: return y;   /* atan(+-0,+anything)=+-0 */
         case 2: return  pi; /* atan(+0,-anything) = pi */
         case 3: return -pi; /* atan(-0,-anything) =-pi */
         }
     }
     /* when x = 0 */
     if (ix == 0)
         return m&1 ? -pi/2 : pi/2;
     /* when x is INF */
     if (ix == 0x7f800000) {
         if (iy == 0x7f800000) {
             switch (m) {
             case 0: return  pi/4; /* atan(+INF,+INF) */
             case 1: return -pi/4; /* atan(-INF,+INF) */
             case 2: return 3*pi/4;  /*atan(+INF,-INF)*/
             case 3: return -3*pi/4; /*atan(-INF,-INF)*/
             }
         } else {
             switch (m) {
             case 0: return  0.0f;    /* atan(+...,+INF) */
             case 1: return -0.0f;    /* atan(-...,+INF) */
             case 2: return  pi; /* atan(+...,-INF) */
             case 3: return -pi; /* atan(-...,-INF) */
             }
         }
     }
     /* |y/x| > 0x1p26 */
     if (ix+(26<<23) < iy || iy == 0x7f800000)
         return m&1 ? -pi/2 : pi/2;
     /* z = atan(|y/x|) with correct underflow */
     if ((m&2) && iy+(26<<23) < ix)  /*|y/x| < 0x1p-26, x < 0 */
         z = 0.0;
     else
         z = atanf(fabsf(y/x));
     switch (m) {
     case 0: return z;              /* atan(+,+) */
     case 1: return -z;             /* atan(-,+) */
     case 2: return pi - (z-pi_lo); /* atan(+,-) */
     default: /* case 3 */
         return (z-pi_lo) - pi; /* atan(-,-) */
     }
 }
References atanf(), fabsf(), GET_FLOAT_WORD, isnan, pi, pi_lo, x, and y.
Referenced by cargf(), catanf(), and clogf().
atan2l()
long double atan2l (long double x, long double y)
atanf()
float atanf (float x)
Definition at line 41 of file atanf.c.
 {
     float_t w,s1,s2,z;
     uint32_t ix,sign;
     int id;
     GET_FLOAT_WORD(ix, x);
     sign = ix>>31;
     ix &= 0x7fffffff;
     if (ix >= 0x4c800000) {  /* if |x| >= 2**26 */
         if (isnan(x))
             return x;
         z = atanhi[3] + 0x1p-120f;
         return sign ? -z : z;
     }
     if (ix < 0x3ee00000) {   /* |x| < 0.4375 */
         if (ix < 0x39800000) {  /* |x| < 2**-12 */
             if (ix < 0x00800000)
                 /* raise underflow for subnormal x */
                 FORCE_EVAL(x*x);
             return x;
         }
         id = -1;
     } else {
         x = fabsf(x);
         if (ix < 0x3f980000) {  /* |x| < 1.1875 */
             if (ix < 0x3f300000) {  /*  7/16 <= |x| < 11/16 */
                 id = 0;
                 x = (2.0f*x - 1.0f)/(2.0f + x);
             } else {                /* 11/16 <= |x| < 19/16 */
                 id = 1;
                 x = (x - 1.0f)/(x + 1.0f);
             }
         } else {
             if (ix < 0x401c0000) {  /* |x| < 2.4375 */
                 id = 2;
                 x = (x - 1.5f)/(1.0f + 1.5f*x);
             } else {                /* 2.4375 <= |x| < 2**26 */
                 id = 3;
                 x = -1.0f/x;
             }
         }
     }
     /* end of argument reduction */
     z = x*x;
     w = z*z;
     /* break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly */
     s1 = z*(aT[0]+w*(aT[2]+w*aT[4]));
     s2 = w*(aT[1]+w*aT[3]);
     if (id < 0)
         return x - x*(s1+s2);
     z = atanhi[id] - ((x*(s1+s2) - atanlo[id]) - x);
     return sign ? -z : z;
 }
References aT, atanhi, atanlo, fabsf(), FORCE_EVAL, GET_FLOAT_WORD, isnan, s1, s2, and x.
Referenced by atan2f().
atanh()
double atanh (double x)
Definition at line 4 of file atanh.c.
 {
     union {double f; uint64_t i;} u = {.f = x};
     unsigned e = u.i >> 52 & 0x7ff;
     unsigned s = u.i >> 63;
     double_t y;
     /* |x| */
     u.i &= (uint64_t)-1/2;
     y = u.f;
     if (e < 0x3ff - 1) {
         if (e < 0x3ff - 32) {
             /* handle underflow */
             if (e == 0)
                 FORCE_EVAL((float)y);
         } else {
             /* |x| < 0.5, up to 1.7ulp error */
             y = 0.5*log1p(2*y + 2*y*y/(1-y));
         }
     } else {
         /* avoid overflow */
         y = 0.5*log1p(2*(y/(1-y)));
     }
     return s ? -y : y;
 }
References FORCE_EVAL, i, log1p(), x, and y.
atanhf()
float atanhf (float x)
Definition at line 4 of file atanhf.c.
 {
     union {float f; uint32_t i;} u = {.f = x};
     unsigned s = u.i >> 31;
     float_t y;
     /* |x| */
     u.i &= 0x7fffffff;
     y = u.f;
     if (u.i < 0x3f800000 - (1<<23)) {
         if (u.i < 0x3f800000 - (32<<23)) {
             /* handle underflow */
             if (u.i < (1<<23))
                 FORCE_EVAL((float)(y*y));
         } else {
             /* |x| < 0.5, up to 1.7ulp error */
             y = 0.5f*log1pf(2*y + 2*y*y/(1-y));
         }
     } else {
         /* avoid overflow */
         y = 0.5f*log1pf(2*(y/(1-y)));
     }
     return s ? -y : y;
 }
References FORCE_EVAL, i, log1pf(), x, and y.
atanhl()
long double atanhl (long double x)
atanl()
long double atanl (long double x)
cbrt()
double cbrt (double x)
Definition at line 33 of file cbrt.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t r,s,t,w;
     uint32_t hx = u.i>>32 & 0x7fffffff;
     if (hx >= 0x7ff00000)  /* cbrt(NaN,INF) is itself */
         return x+x;
     /*
      * Rough cbrt to 5 bits:
      *    cbrt(2**e*(1+m) ~= 2**(e/3)*(1+(e%3+m)/3)
      * where e is integral and >= 0, m is real and in [0, 1), and "/" and
      * "%" are integer division and modulus with rounding towards minus
      * infinity.  The RHS is always >= the LHS and has a maximum relative
      * error of about 1 in 16.  Adding a bias of -0.03306235651 to the
      * (e%3+m)/3 term reduces the error to about 1 in 32. With the IEEE
      * floating point representation, for finite positive normal values,
      * ordinary integer divison of the value in bits magically gives
      * almost exactly the RHS of the above provided we first subtract the
      * exponent bias (1023 for doubles) and later add it back.  We do the
      * subtraction virtually to keep e >= 0 so that ordinary integer
      * division rounds towards minus infinity; this is also efficient.
      */
     if (hx < 0x00100000) { /* zero or subnormal? */
         u.f = x*0x1p54;
         hx = u.i>>32 & 0x7fffffff;
         if (hx == 0)
             return x;  /* cbrt(0) is itself */
         hx = hx/3 + B2;
     } else
         hx = hx/3 + B1;
     u.i &= 1ULL<<63;
     u.i |= (uint64_t)hx << 32;
     t = u.f;
     /*
      * New cbrt to 23 bits:
      *    cbrt(x) = t*cbrt(x/t**3) ~= t*P(t**3/x)
      * where P(r) is a polynomial of degree 4 that approximates 1/cbrt(r)
      * to within 2**-23.5 when |r - 1| < 1/10.  The rough approximation
      * has produced t such than |t/cbrt(x) - 1| ~< 1/32, and cubing this
      * gives us bounds for r = t**3/x.
      *
      * Try to optimize for parallel evaluation as in __tanf.c.
      */
     r = (t*t)*(t/x);
     t = t*((P0+r*(P1+r*P2))+((r*r)*r)*(P3+r*P4));
     /*
      * Round t away from zero to 23 bits (sloppily except for ensuring that
      * the result is larger in magnitude than cbrt(x) but not much more than
      * 2 23-bit ulps larger).  With rounding towards zero, the error bound
      * would be ~5/6 instead of ~4/6.  With a maximum error of 2 23-bit ulps
      * in the rounded t, the infinite-precision error in the Newton
      * approximation barely affects third digit in the final error
      * 0.667; the error in the rounded t can be up to about 3 23-bit ulps
      * before the final error is larger than 0.667 ulps.
      */
     u.f = t;
     u.i = (u.i + 0x80000000) & 0xffffffffc0000000ULL;
     t = u.f;
     /* one step Newton iteration to 53 bits with error < 0.667 ulps */
     s = t*t;         /* t*t is exact */
     r = x/s;         /* error <= 0.5 ulps; |r| < |t| */
     w = t+t;         /* t+t is exact */
     r = (r-t)/(w+r); /* r-t is exact; w+r ~= 3*t */
     t = t+t*r;       /* error <= 0.5 + 0.5/3 + epsilon */
     return t;
 }
References B1, B2, i, P0, P1, P2, P3, P4, r, and x.
cbrtf()
float cbrtf (float x)
Definition at line 27 of file cbrtf.c.
 {
     double_t r,T;
     union {float f; uint32_t i;} u = {x};
     uint32_t hx = u.i & 0x7fffffff;
     if (hx >= 0x7f800000)  /* cbrt(NaN,INF) is itself */
         return x + x;
     /* rough cbrt to 5 bits */
     if (hx < 0x00800000) {  /* zero or subnormal? */
         if (hx == 0)
             return x;  /* cbrt(+-0) is itself */
         u.f = x*0x1p24f;
         hx = u.i & 0x7fffffff;
         hx = hx/3 + B2;
     } else
         hx = hx/3 + B1;
     u.i &= 0x80000000;
     u.i |= hx;
     /*
      * First step Newton iteration (solving t*t-x/t == 0) to 16 bits.  In
      * double precision so that its terms can be arranged for efficiency
      * without causing overflow or underflow.
      */
     T = u.f;
     r = T*T*T;
     T = T*((double_t)x+x+r)/(x+r+r);
     /*
      * Second step Newton iteration to 47 bits.  In double precision for
      * efficiency and accuracy.
      */
     r = T*T*T;
     T = T*((double_t)x+x+r)/(x+r+r);
     /* rounding to 24 bits is perfect in round-to-nearest mode */
     return T;
 }
References B1, B2, i, r, T, and x.
cbrtl()
long double cbrtl (long double x)
ceil()
double ceil (double x)
Definition at line 10 of file ceil.c.
 {
     union {double f; uint64_t i;} u = {x};
     int e = u.i >> 52 & 0x7ff;
     double_t y;
     if (e >= 0x3ff+52 || x == 0)
         return x;
     /* y = int(x) - x, where int(x) is an integer neighbor of x */
     if (u.i >> 63)
         y = x - toint + toint - x;
     else
         y = x + toint - toint - x;
     /* special case because of non-nearest rounding modes */
     if (e <= 0x3ff-1) {
         FORCE_EVAL(y);
         return u.i >> 63 ? -0.0 : 1;
     }
     if (y < 0)
         return x + y + 1;
     return x + y;
 }
References FORCE_EVAL, i, toint, x, and y.
ceilf()
float ceilf (float x)
Definition at line 3 of file ceilf.c.
 {
     union {float f; uint32_t i;} u = {x};
     int e = (int)(u.i >> 23 & 0xff) - 0x7f;
     uint32_t m;
     if (e >= 23)
         return x;
     if (e >= 0) {
         m = 0x007fffff >> e;
         if ((u.i & m) == 0)
             return x;
         FORCE_EVAL(x + 0x1p120f);
         if (u.i >> 31 == 0)
             u.i += m;
         u.i &= ~m;
     } else {
         FORCE_EVAL(x + 0x1p120f);
         if (u.i >> 31)
             u.f = -0.0;
         else if (u.i << 1)
             u.f = 1.0;
     }
     return u.f;
 }
References FORCE_EVAL, i, int, and x.
ceill()
long double ceill (long double x)
copysign()
double copysign (double x, double sign)
Definition at line 3 of file copysign.c.
{
     union {double f; uint64_t i;} ux={x}, uy={y};
     ux.i &= -1ULL/2;
     ux.i |= uy.i & 1ULL<<63;
     return ux.f;
 }
References i, x, and y.
Referenced by cproj().
copysignf()
float copysignf (float x, float sign)
Definition at line 4 of file copysignf.c.
 {
     union {float f; uint32_t i;} ux={x}, uy={y};
     ux.i &= 0x7fffffff;
     ux.i |= uy.i & 0x80000000;
     return ux.f;
 }
References i, x, and y.
Referenced by cprojf().
copysignl()
long double copysignl (long double x, long double sign)
cos()
double cos (double x)
Definition at line 45 of file cos.c.
 {
     double y[2];
     uint32_t ix;
     unsigned n;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     /* |x| ~< pi/4 */
     if (ix <= 0x3fe921fb) {
         if (ix < 0x3e46a09e) {  /* |x| < 2**-27 * sqrt(2) */
             /* raise inexact if x!=0 */
             FORCE_EVAL(x + 0x1p120f);
             return 1.0;
         }
         return __cos(x, 0);
     }
     /* cos(Inf or NaN) is NaN */
     if (ix >= 0x7ff00000)
         return x-x;
     /* argument reduction */
     n = __rem_pio2(x, y);
     switch (n&3) {
     case 0: return  __cos(y[0], y[1]);
     case 1: return -__sin(y[0], y[1], 1);
     case 2: return -__cos(y[0], y[1]);
     default:
         return  __sin(y[0], y[1], 1);
     }
 }
References __cos(), __rem_pio2(), __sin(), FORCE_EVAL, GET_HIGH_WORD, n, x, and y.
Referenced by ccos(), ccosh(), cexp(), common(), cpow(), csin(), csinh(), ctan(), ctanh(), jn(), sincos(), sincosf(), and yn().
cosf()
float cosf (float x)
Definition at line 26 of file cosf.c.
 {
     double y;
     uint32_t ix;
     unsigned n, sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     if (ix <= 0x3f490fda) {  /* |x| ~<= pi/4 */
         if (ix < 0x39800000) {  /* |x| < 2**-12 */
             /* raise inexact if x != 0 */
             FORCE_EVAL(x + 0x1p120f);
             return 1.0f;
         }
         return __cosdf(x);
     }
     if (ix <= 0x407b53d1) {  /* |x| ~<= 5*pi/4 */
         if (ix > 0x4016cbe3)  /* |x|  ~> 3*pi/4 */
             return -__cosdf(sign ? x+c2pio2 : x-c2pio2);
         else {
             if (sign)
                 return __sindf(x + c1pio2);
             else
                 return __sindf(c1pio2 - x);
         }
     }
     if (ix <= 0x40e231d5) {  /* |x| ~<= 9*pi/4 */
         if (ix > 0x40afeddf)  /* |x| ~> 7*pi/4 */
             return __cosdf(sign ? x+c4pio2 : x-c4pio2);
         else {
             if (sign)
                 return __sindf(-x - c3pio2);
             else
                 return __sindf(x - c3pio2);
         }
     }
     /* cos(Inf or NaN) is NaN */
     if (ix >= 0x7f800000)
         return x-x;
     /* general argument reduction needed */
     n = __rem_pio2f(x,&y);
     switch (n&3) {
     case 0: return  __cosdf(y);
     case 1: return  __sindf(-y);
     case 2: return -__cosdf(y);
     default:
         return  __sindf(y);
     }
 }
References __cosdf(), __rem_pio2f(), __sindf(), c1pio2, c2pio2, c3pio2, c4pio2, FORCE_EVAL, GET_FLOAT_WORD, n, x, and y.
Referenced by ccosf(), ccoshf(), cexpf(), common(), cpowf(), csinf(), csinhf(), ctanf(), and ctanhf().
cosh()
double cosh (double x)
Definition at line 7 of file cosh.c.
 {
     union {double f; uint64_t i;} u = {.f = x};
     uint32_t w;
     double t;
     /* |x| */
     u.i &= (uint64_t)-1/2;
     x = u.f;
     w = u.i >> 32;
     /* |x| < log(2) */
     if (w < 0x3fe62e42) {
         if (w < 0x3ff00000 - (26<<20)) {
             /* raise inexact if x!=0 */
             FORCE_EVAL(x + 0x1p120f);
             return 1;
         }
         t = expm1(x);
         return 1 + t*t/(2*(1+t));
     }
     /* |x| < log(DBL_MAX) */
     if (w < 0x40862e42) {
         t = exp(x);
         /* note: if x>log(0x1p26) then the 1/t is not needed */
         return 0.5*(t + 1/t);
     }
     /* |x| > log(DBL_MAX) or nan */
     /* note: the result is stored to handle overflow */
     t = __expo2(x);
     return t;
 }
References __expo2(), exp(), expm1(), FORCE_EVAL, i, and x.
Referenced by __mlibc_cchsh(), ccosh(), csinh(), ctan(), and ctanh().
coshf()
float coshf (float x)
Definition at line 3 of file coshf.c.
 {
     union {float f; uint32_t i;} u = {.f = x};
     uint32_t w;
     float t;
     /* |x| */
     u.i &= 0x7fffffff;
     x = u.f;
     w = u.i;
     /* |x| < log(2) */
     if (w < 0x3f317217) {
         if (w < 0x3f800000 - (12<<23)) {
             FORCE_EVAL(x + 0x1p120f);
             return 1;
         }
         t = expm1f(x);
         return 1 + t*t/(2*(1+t));
     }
     /* |x| < log(FLT_MAX) */
     if (w < 0x42b17217) {
         t = expf(x);
         return 0.5f*(t + 1/t);
     }
     /* |x| > log(FLT_MAX) or nan */
     t = __expo2f(x);
     return t;
 }
References __expo2f(), expf(), expm1f(), FORCE_EVAL, i, and x.
Referenced by __mlibc_cchshf(), ccoshf(), csinhf(), ctanf(), and ctanhf().
coshl()
long double coshl (long double x)
cosl()
long double cosl (long double x)
erf()
double erf (double x)
Definition at line 213 of file erf.c.
 {
     double r,s,z,y;
     uint32_t ix;
     int sign;
     GET_HIGH_WORD(ix, x);
     sign = ix>>31;
     ix &= 0x7fffffff;
     if (ix >= 0x7ff00000) {
         /* erf(nan)=nan, erf(+-inf)=+-1 */
         return 1-2*sign + 1/x;
     }
     if (ix < 0x3feb0000) {  /* |x| < 0.84375 */
         if (ix < 0x3e300000) {  /* |x| < 2**-28 */
             /* avoid underflow */
             return 0.125*(8*x + efx8*x);
         }
         z = x*x;
         r = pp0+z*(pp1+z*(pp2+z*(pp3+z*pp4)));
         s = 1.0+z*(qq1+z*(qq2+z*(qq3+z*(qq4+z*qq5))));
         y = r/s;
         return x + x*y;
     }
     if (ix < 0x40180000)  /* 0.84375 <= |x| < 6 */
         y = 1 - erfc2(ix,x);
     else
         y = 1 - 0x1p-1022;
     return sign ? -y : y;
 }
References efx8, erfc2(), GET_HIGH_WORD, pp0, pp1, pp2, pp3, pp4, qq1, qq2, qq3, qq4, qq5, r, x, and y.
erfc()
double erfc (double x)
Definition at line 244 of file erf.c.
 {
     double r,s,z,y;
     uint32_t ix;
     int sign;
     GET_HIGH_WORD(ix, x);
     sign = ix>>31;
     ix &= 0x7fffffff;
     if (ix >= 0x7ff00000) {
         /* erfc(nan)=nan, erfc(+-inf)=0,2 */
         return 2*sign + 1/x;
     }
     if (ix < 0x3feb0000) {  /* |x| < 0.84375 */
         if (ix < 0x3c700000)  /* |x| < 2**-56 */
             return 1.0 - x;
         z = x*x;
         r = pp0+z*(pp1+z*(pp2+z*(pp3+z*pp4)));
         s = 1.0+z*(qq1+z*(qq2+z*(qq3+z*(qq4+z*qq5))));
         y = r/s;
         if (sign || ix < 0x3fd00000) {  /* x < 1/4 */
             return 1.0 - (x+x*y);
         }
         return 0.5 - (x - 0.5 + x*y);
     }
     if (ix < 0x403c0000) {  /* 0.84375 <= |x| < 28 */
         return sign ? 2 - erfc2(ix,x) : erfc2(ix,x);
     }
     return sign ? 2 - 0x1p-1022 : 0x1p-1022*0x1p-1022;
 }
References erfc2(), GET_HIGH_WORD, pp0, pp1, pp2, pp3, pp4, qq1, qq2, qq3, qq4, qq5, r, x, and y.
erfcf()
float erfcf (float x)
Definition at line 154 of file erff.c.
 {
     float r,s,z,y;
     uint32_t ix;
     int sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix>>31;
     ix &= 0x7fffffff;
     if (ix >= 0x7f800000) {
         /* erfc(nan)=nan, erfc(+-inf)=0,2 */
         return 2*sign + 1/x;
     }
     if (ix < 0x3f580000) {  /* |x| < 0.84375 */
         if (ix < 0x23800000)  /* |x| < 2**-56 */
             return 1.0f - x;
         z = x*x;
         r = pp0+z*(pp1+z*(pp2+z*(pp3+z*pp4)));
         s = 1.0f+z*(qq1+z*(qq2+z*(qq3+z*(qq4+z*qq5))));
         y = r/s;
         if (sign || ix < 0x3e800000)  /* x < 1/4 */
             return 1.0f - (x+x*y);
         return 0.5f - (x - 0.5f + x*y);
     }
     if (ix < 0x41e00000) {  /* |x| < 28 */
         return sign ? 2 - erfc2(ix,x) : erfc2(ix,x);
     }
     return sign ? 2 - 0x1p-120f : 0x1p-120f*0x1p-120f;
 }
References erfc2(), GET_FLOAT_WORD, pp0, pp1, pp2, pp3, pp4, qq1, qq2, qq3, qq4, qq5, r, x, and y.
erfcl()
long double erfcl (long double x)
erff()
float erff (float x)
Definition at line 123 of file erff.c.
 {
     float r,s,z,y;
     uint32_t ix;
     int sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix>>31;
     ix &= 0x7fffffff;
     if (ix >= 0x7f800000) {
         /* erf(nan)=nan, erf(+-inf)=+-1 */
         return 1-2*sign + 1/x;
     }
     if (ix < 0x3f580000) {  /* |x| < 0.84375 */
         if (ix < 0x31800000) {  /* |x| < 2**-28 */
             /*avoid underflow */
             return 0.125f*(8*x + efx8*x);
         }
         z = x*x;
         r = pp0+z*(pp1+z*(pp2+z*(pp3+z*pp4)));
         s = 1+z*(qq1+z*(qq2+z*(qq3+z*(qq4+z*qq5))));
         y = r/s;
         return x + x*y;
     }
     if (ix < 0x40c00000)  /* |x| < 6 */
         y = 1 - erfc2(ix,x);
     else
         y = 1 - 0x1p-120f;
     return sign ? -y : y;
 }
References efx8, erfc2(), GET_FLOAT_WORD, pp0, pp1, pp2, pp3, pp4, qq1, qq2, qq3, qq4, qq5, r, x, and y.
erfl()
long double erfl (long double x)
exp()
double exp (double x)
Definition at line 81 of file exp.c.
 {
     double_t hi, lo, c, xx, y;
     int k, sign;
     uint32_t hx;
     GET_HIGH_WORD(hx, x);
     sign = hx>>31;
     hx &= 0x7fffffff;  /* high word of |x| */
     /* special cases */
     if (hx >= 0x4086232b) {  /* if |x| >= 708.39... */
         if (isnan(x))
             return x;
         if (x > 709.782712893383973096) {
             /* overflow if x!=inf */
             x *= 0x1p1023;
             return x;
         }
         if (x < -708.39641853226410622) {
             /* underflow if x!=-inf */
             FORCE_EVAL((float)(-0x1p-149/x));
             if (x < -745.13321910194110842)
                 return 0;
         }
     }
     /* argument reduction */
     if (hx > 0x3fd62e42) {  /* if |x| > 0.5 ln2 */
         if (hx >= 0x3ff0a2b2)  /* if |x| >= 1.5 ln2 */
             k = (int)(invln2*x + half[sign]);
         else
             k = 1 - sign - sign;
         hi = x - k*ln2hi;  /* k*ln2hi is exact here */
         lo = k*ln2lo;
         x = hi - lo;
     } else if (hx > 0x3e300000)  {  /* if |x| > 2**-28 */
         k = 0;
         hi = x;
         lo = 0;
     } else {
         /* inexact if x!=0 */
         FORCE_EVAL(0x1p1023 + x);
         return 1 + x;
     }
     /* x is now in primary range */
     xx = x*x;
     c = x - xx*(P1+xx*(P2+xx*(P3+xx*(P4+xx*P5))));
     y = 1 + (x*c/(2-c) - lo + hi);
     if (k == 0)
         return y;
     return scalbn(y, k);
 }
References c, FORCE_EVAL, GET_HIGH_WORD, half, int, invln2, isnan, k, ln2hi, ln2lo, P1, P2, P3, P4, P5, scalbn(), x, and y.
Referenced by __expo2(), __mlibc_cchsh(), cexp(), cosh(), cpow(), erfc2(), and tgamma().
exp10()
double exp10 (double x)
Definition at line 7 of file exp10.c.
 {
     static const double p10[] = {
         1e-15, 1e-14, 1e-13, 1e-12, 1e-11, 1e-10,
         1e-9, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1,
         1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9,
         1e10, 1e11, 1e12, 1e13, 1e14, 1e15
     };
     double n, y = modf(x, &n);
     union {double f; uint64_t i;} u = {n};
     /* fabs(n) < 16 without raising invalid on nan */
     if ((u.i>>52 & 0x7ff) < 0x3ff+4) {
         if (!y) return p10[(int)n+15];
         y = exp2(3.32192809488736234787031942948939 * y);
         return y * p10[(int)n+15];
     }
     return pow(10.0, x);
 }
References exp2(), i, int, modf(), n, pow(), x, and y.
Referenced by print_exponential_number(), and print_exponential_number_libint().
exp10f()
float exp10f (float x)
Definition at line 7 of file exp10f.c.
 {
     static const float p10[] = {
         1e-7f, 1e-6f, 1e-5f, 1e-4f, 1e-3f, 1e-2f, 1e-1f,
         1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7
     };
     float n, y = modff(x, &n);
     union {float f; uint32_t i;} u = {n};
     /* fabsf(n) < 8 without raising invalid on nan */
     if ((u.i>>23 & 0xff) < 0x7f+3) {
         if (!y) return p10[(int)n+7];
         y = exp2f(3.32192809488736234787031942948939f * y);
         return y * p10[(int)n+7];
     }
     return exp2(3.32192809488736234787031942948939 * x);
 }
References exp2(), exp2f(), i, int, modff(), n, x, and y.
exp10l()
long double exp10l (long double)
exp2()
double exp2 (double x)
Definition at line 331 of file exp2.c.
 {
     double_t r, t, z;
     uint32_t ix, i0;
     union {double f; uint64_t i;} u = {x};
     union {uint32_t u; int32_t i;} k;
     /* Filter out exceptional cases. */
     ix = u.i>>32 & 0x7fffffff;
     if (ix >= 0x408ff000) {  /* |x| >= 1022 or nan */
         if (ix >= 0x40900000 && u.i>>63 == 0) {  /* x >= 1024 or nan */
             /* overflow */
             x *= 0x1p1023;
             return x;
         }
         if (ix >= 0x7ff00000)  /* -inf or -nan */
             return -1/x;
         if (u.i>>63) {  /* x <= -1022 */
             /* underflow */
             if (x <= -1075 || x - 0x1p52 + 0x1p52 != x)
                 FORCE_EVAL((float)(-0x1p-149/x));
             if (x <= -1075)
                 return 0;
         }
     } else if (ix < 0x3c900000) {  /* |x| < 0x1p-54 */
         return 1.0 + x;
     }
     /* Reduce x, computing z, i0, and k. */
     u.f = x + redux;
     i0 = u.i;
     i0 += TBLSIZE / 2;
     k.u = i0 / TBLSIZE * TBLSIZE;
     k.i /= TBLSIZE;
     i0 %= TBLSIZE;
     u.f -= redux;
     z = x - u.f;
     /* Compute r = exp2(y) = exp2t[i0] * p(z - eps[i]). */
     t = tbl[2*i0];       /* exp2t[i0] */
     z -= tbl[2*i0 + 1];  /* eps[i0]   */
     r = t + t * z * (P1 + z * (P2 + z * (P3 + z * (P4 + z * P5))));
     return scalbn(r, k.i);
 }
References FORCE_EVAL, i, k, P1, P2, P3, P4, P5, r, redux, scalbn(), tbl, TBLSIZE, and x.
Referenced by exp10(), exp10f(), log10_of_positive(), log10_of_positive_libint(), pow10_of_int(), and pow10_of_int_libint().
exp2f()
float exp2f (float x)
Definition at line 84 of file exp2f.c.
 {
     double_t t, r, z;
     union {float f; uint32_t i;} u = {x};
     union {double f; uint64_t i;} uk;
     uint32_t ix, i0, k;
     /* Filter out exceptional cases. */
     ix = u.i & 0x7fffffff;
     if (ix > 0x42fc0000) {  /* |x| > 126 */
         if (ix > 0x7f800000) /* NaN */
             return x;
         if (u.i >= 0x43000000 && u.i < 0x80000000) {  /* x >= 128 */
             x *= 0x1p127f;
             return x;
         }
         if (u.i >= 0x80000000) {  /* x < -126 */
             if (u.i >= 0xc3160000 || (u.i & 0x0000ffff))
                 FORCE_EVAL(-0x1p-149f/x);
             if (u.i >= 0xc3160000)  /* x <= -150 */
                 return 0;
         }
     } else if (ix <= 0x33000000) {  /* |x| <= 0x1p-25 */
         return 1.0f + x;
     }
     /* Reduce x, computing z, i0, and k. */
     u.f = x + redux;
     i0 = u.i;
     i0 += TBLSIZE / 2;
     k = i0 / TBLSIZE;
     uk.i = (uint64_t)(0x3ff + k)<<52;
     i0 &= TBLSIZE - 1;
     u.f -= redux;
     z = x - u.f;
     /* Compute r = exp2(y) = exp2ft[i0] * p(z). */
     r = exp2ft[i0];
     t = r * z;
     r = r + t * (P1 + z * P2) + t * (z * z) * (P3 + z * P4);
     /* Scale by 2**k */
     return r * uk.f;
 }
References exp2ft, FORCE_EVAL, i, k, P1, P2, P3, P4, r, redux, TBLSIZE, and x.
Referenced by exp10f().
exp2l()
long double exp2l (long double x)
expf()
float expf (float x)
Definition at line 30 of file expf.c.
 {
     float_t hi, lo, c, xx, y;
     int k, sign;
     uint32_t hx;
     GET_FLOAT_WORD(hx, x);
     sign = hx >> 31;   /* sign bit of x */
     hx &= 0x7fffffff;  /* high word of |x| */
     /* special cases */
     if (hx >= 0x42aeac50) {  /* if |x| >= -87.33655f or NaN */
         if (hx > 0x7f800000) /* NaN */
             return x;
         if (hx >= 0x42b17218 && !sign) {  /* x >= 88.722839f */
             /* overflow */
             x *= 0x1p127f;
             return x;
         }
         if (sign) {
             /* underflow */
             FORCE_EVAL(-0x1p-149f/x);
             if (hx >= 0x42cff1b5)  /* x <= -103.972084f */
                 return 0;
         }
     }
     /* argument reduction */
     if (hx > 0x3eb17218) {  /* if |x| > 0.5 ln2 */
         if (hx > 0x3f851592)  /* if |x| > 1.5 ln2 */
             k = invln2*x + half[sign];
         else
             k = 1 - sign - sign;
         hi = x - k*ln2hi;  /* k*ln2hi is exact here */
         lo = k*ln2lo;
         x = hi - lo;
     } else if (hx > 0x39000000) {  /* |x| > 2**-14 */
         k = 0;
         hi = x;
         lo = 0;
     } else {
         /* raise inexact */
         FORCE_EVAL(0x1p127f + x);
         return 1 + x;
     }
     /* x is now in primary range */
     xx = x*x;
     c = x - xx*(P1+xx*P2);
     y = 1 + (x*c/(2-c) - lo + hi);
     if (k == 0)
         return y;
     return scalbnf(y, k);
 }
References c, FORCE_EVAL, GET_FLOAT_WORD, half, invln2, k, ln2hi, ln2lo, P1, P2, scalbnf(), x, and y.
Referenced by __expo2f(), __mlibc_cchshf(), cexpf(), coshf(), cpowf(), and erfc2().
expl()
long double expl (long double x)
expm1()
double expm1 (double x)
Definition at line 121 of file expm1.c.
 {
     double_t y,hi,lo,c,t,e,hxs,hfx,r1,twopk;
     union {double f; uint64_t i;} u = {x};
     uint32_t hx = u.i>>32 & 0x7fffffff;
     int k, sign = u.i>>63;
     /* filter out huge and non-finite argument */
     if (hx >= 0x4043687A) {  /* if |x|>=56*ln2 */
         if (isnan(x))
             return x;
         if (sign)
             return -1;
         if (x > o_threshold) {
             x *= 0x1p1023;
             return x;
         }
     }
     /* argument reduction */
     if (hx > 0x3fd62e42) {  /* if  |x| > 0.5 ln2 */
         if (hx < 0x3FF0A2B2) {  /* and |x| < 1.5 ln2 */
             if (!sign) {
                 hi = x - ln2_hi;
                 lo = ln2_lo;
                 k =  1;
             } else {
                 hi = x + ln2_hi;
                 lo = -ln2_lo;
                 k = -1;
             }
         } else {
             k  = invln2*x + (sign ? -0.5 : 0.5);
             t  = k;
             hi = x - t*ln2_hi;  /* t*ln2_hi is exact here */
             lo = t*ln2_lo;
         }
         x = hi-lo;
         c = (hi-x)-lo;
     } else if (hx < 0x3c900000) {  /* |x| < 2**-54, return x */
         if (hx < 0x00100000)
             FORCE_EVAL((float)x);
         return x;
     } else
         k = 0;
     /* x is now in primary range */
     hfx = 0.5*x;
     hxs = x*hfx;
     r1 = 1.0+hxs*(Q1+hxs*(Q2+hxs*(Q3+hxs*(Q4+hxs*Q5))));
     t  = 3.0-r1*hfx;
     e  = hxs*((r1-t)/(6.0 - x*t));
     if (k == 0)   /* c is 0 */
         return x - (x*e-hxs);
     e  = x*(e-c) - c;
     e -= hxs;
     /* exp(x) ~ 2^k (x_reduced - e + 1) */
     if (k == -1)
         return 0.5*(x-e) - 0.5;
     if (k == 1) {
         if (x < -0.25)
             return -2.0*(e-(x+0.5));
         return 1.0+2.0*(x-e);
     }
     u.i = (uint64_t)(0x3ff + k)<<52;  /* 2^k */
     twopk = u.f;
     if (k < 0 || k > 56) {  /* suffice to return exp(x)-1 */
         y = x - e + 1.0;
         if (k == 1024)
             y = y*2.0*0x1p1023;
         else
             y = y*twopk;
         return y - 1.0;
     }
     u.i = (uint64_t)(0x3ff - k)<<52;  /* 2^-k */
     if (k < 20)
         y = (x-e+(1-u.f))*twopk;
     else
         y = (x-(e+u.f)+1)*twopk;
     return y;
 }
References c, FORCE_EVAL, i, invln2, isnan, k, ln2_hi, ln2_lo, o_threshold, Q1, Q2, Q3, Q4, Q5, r1, x, and y.
Referenced by cosh(), sinh(), and tanh().
expm1f()
float expm1f (float x)
Definition at line 31 of file expm1f.c.
 {
     float_t y,hi,lo,c,t,e,hxs,hfx,r1,twopk;
     union {float f; uint32_t i;} u = {x};
     uint32_t hx = u.i & 0x7fffffff;
     int k, sign = u.i >> 31;
     /* filter out huge and non-finite argument */
     if (hx >= 0x4195b844) {  /* if |x|>=27*ln2 */
         if (hx > 0x7f800000)  /* NaN */
             return x;
         if (sign)
             return -1;
         if (x > o_threshold) {
             x *= 0x1p127f;
             return x;
         }
     }
     /* argument reduction */
     if (hx > 0x3eb17218) {           /* if  |x| > 0.5 ln2 */
         if (hx < 0x3F851592) {       /* and |x| < 1.5 ln2 */
             if (!sign) {
                 hi = x - ln2_hi;
                 lo = ln2_lo;
                 k =  1;
             } else {
                 hi = x + ln2_hi;
                 lo = -ln2_lo;
                 k = -1;
             }
         } else {
             k  = invln2*x + (sign ? -0.5f : 0.5f);
             t  = k;
             hi = x - t*ln2_hi;      /* t*ln2_hi is exact here */
             lo = t*ln2_lo;
         }
         x = hi-lo;
         c = (hi-x)-lo;
     } else if (hx < 0x33000000) {  /* when |x|<2**-25, return x */
         if (hx < 0x00800000)
             FORCE_EVAL(x*x);
         return x;
     } else
         k = 0;
     /* x is now in primary range */
     hfx = 0.5f*x;
     hxs = x*hfx;
     r1 = 1.0f+hxs*(Q1+hxs*Q2);
     t  = 3.0f - r1*hfx;
     e  = hxs*((r1-t)/(6.0f - x*t));
     if (k == 0)  /* c is 0 */
         return x - (x*e-hxs);
     e  = x*(e-c) - c;
     e -= hxs;
     /* exp(x) ~ 2^k (x_reduced - e + 1) */
     if (k == -1)
         return 0.5f*(x-e) - 0.5f;
     if (k == 1) {
         if (x < -0.25f)
             return -2.0f*(e-(x+0.5f));
         return 1.0f + 2.0f*(x-e);
     }
     u.i = (0x7f+k)<<23;  /* 2^k */
     twopk = u.f;
     if (k < 0 || k > 56) {   /* suffice to return exp(x)-1 */
         y = x - e + 1.0f;
         if (k == 128)
             y = y*2.0f*0x1p127f;
         else
             y = y*twopk;
         return y - 1.0f;
     }
     u.i = (0x7f-k)<<23;  /* 2^-k */
     if (k < 23)
         y = (x-e+(1-u.f))*twopk;
     else
         y = (x-(e+u.f)+1)*twopk;
     return y;
 }
References c, FORCE_EVAL, i, invln2, k, ln2_hi, ln2_lo, o_threshold, Q1, Q2, r1, x, and y.
Referenced by coshf(), sinhf(), and tanhf().
expm1l()
long double expm1l (long double x)
fabs()
double fabs (double x)
Definition at line 4 of file fabs.c.
 {
     union {double f; uint64_t i;} u = {x};
     u.i &= -1ULL/2;
     return u.f;
 }
References i, and x.
Referenced by __mlibc_cchsh(), __mlibc_ctans(), asin(), atan(), atan2(), casin(), csqrt(), ctan(), erfc1(), erfc2(), float_cmp(), j0(), j1(), jn(), pow(), and V_DrawMouseSpeedBox().
fabsf()
float fabsf (float x)
Definition at line 4 of file fabsf.c.
 {
     union {float f; uint32_t i;} u = {x};
     u.i &= 0x7fffffff;
     return u.f;
 }
References i, and x.
Referenced by __mlibc_cchshf(), __mlibc_ctansf(), asinf(), atan2f(), atanf(), casinf(), csqrtf(), ctanf(), erfc1(), erfc2(), j0f(), j1f(), jnf(), and powf().
fabsl()
long double fabsl (long double x)
fdim()
double fdim (double x, double y)
Definition at line 3 of file fdim.c.
 {
     if (isnan(x))
         return x;
     if (isnan(y))
         return y;
     return x > y ? x - y : 0;
 }
References isnan, x, and y.
fdimf()
float fdimf (float x, float y)
Definition at line 3 of file fdimf.c.
 {
     if (isnan(x))
         return x;
     if (isnan(y))
         return y;
     return x > y ? x - y : 0;
 }
References isnan, x, and y.
fdiml()
long double fdiml (long double x, long double y)
Definition at line 10 of file fdiml.c.
 {
     if (isnan(x))
         return x;
     if (isnan(y))
         return y;
     return x > y ? x - y : 0;
 }
References isnan, x, and y.
floor()
double floor (double x)
Definition at line 10 of file floor.c.
 {
     union {double f; uint64_t i;} u = {x};
     int e = u.i >> 52 & 0x7ff;
     double_t y;
     if (e >= 0x3ff+52 || x == 0)
         return x;
     /* y = int(x) - x, where int(x) is an integer neighbor of x */
     if (u.i >> 63)
         y = x - toint + toint - x;
     else
         y = x + toint - toint - x;
     /* special case because of non-nearest rounding modes */
     if (e <= 0x3ff-1) {
         FORCE_EVAL(y);
         return u.i >> 63 ? -1 : 0;
     }
     if (y > 0)
         return x + y - 1;
     return x + y;
 }
References FORCE_EVAL, i, toint, x, and y.
Referenced by __rem_pio2_large(), EV_BuildStairs(), EV_DoDonut(), EV_DoFloor(), P_FindHighestFloorSurrounding(), P_FindLowestFloorSurrounding(), P_UnArchiveSpecials(), sin_pi(), sinpi(), T_MoveFloor(), and tgamma().
floorf()
float floorf (float x)
Definition at line 3 of file floorf.c.
 {
     union {float f; uint32_t i;} u = {x};
     int e = (int)(u.i >> 23 & 0xff) - 0x7f;
     uint32_t m;
     if (e >= 23)
         return x;
     if (e >= 0) {
         m = 0x007fffff >> e;
         if ((u.i & m) == 0)
             return x;
         FORCE_EVAL(x + 0x1p120f);
         if (u.i >> 31)
             u.i += m;
         u.i &= ~m;
     } else {
         FORCE_EVAL(x + 0x1p120f);
         if (u.i >> 31 == 0)
             u.i = 0;
         else if (u.i << 1)
             u.f = -1.0;
     }
     return u.f;
 }
References FORCE_EVAL, i, int, and x.
Referenced by sin_pi().
floorl()
long double floorl (long double x)
fma()
double fma (double x, double y, double z)
Definition at line 53 of file fma.c.
 {
     #pragma STDC FENV_ACCESS ON
     /* normalize so top 10bits and last bit are 0 */
     struct num nx, ny, nz;
     nx = normalize(x);
     ny = normalize(y);
     nz = normalize(z);
     if (nx.e >= ZEROINFNAN || ny.e >= ZEROINFNAN)
         return x*y + z;
     if (nz.e >= ZEROINFNAN) {
         if (nz.e > ZEROINFNAN) /* z==0 */
             return x*y + z;
         return z;
     }
     /* mul: r = x*y */
     uint64_t rhi, rlo, zhi, zlo;
     mul(&rhi, &rlo, nx.m, ny.m);
     /* either top 20 or 21 bits of rhi and last 2 bits of rlo are 0 */
     /* align exponents */
     int e = nx.e + ny.e;
     int d = nz.e - e;
     /* shift bits z<<=kz, r>>=kr, so kz+kr == d, set e = e+kr (== ez-kz) */
     if (d > 0) {
         if (d < 64) {
             zlo = nz.m<<d;
             zhi = nz.m>>64-d;
         } else {
             zlo = 0;
             zhi = nz.m;
             e = nz.e - 64;
             d -= 64;
             if (d == 0) {
             } else if (d < 64) {
                 rlo = rhi<<64-d | rlo>>d | !!(rlo<<64-d);
                 rhi = rhi>>d;
             } else {
                 rlo = 1;
                 rhi = 0;
             }
         }
     } else {
         zhi = 0;
         d = -d;
         if (d == 0) {
             zlo = nz.m;
         } else if (d < 64) {
             zlo = nz.m>>d | !!(nz.m<<64-d);
         } else {
             zlo = 1;
         }
     }
     /* add */
     int sign = nx.sign^ny.sign;
     int samesign = !(sign^nz.sign);
     int nonzero = 1;
     if (samesign) {
         /* r += z */
         rlo += zlo;
         rhi += zhi + (rlo < zlo);
     } else {
         /* r -= z */
         uint64_t t = rlo;
         rlo -= zlo;
         rhi = rhi - zhi - (t < rlo);
         if (rhi>>63) {
             rlo = -rlo;
             rhi = -rhi-!!rlo;
             sign = !sign;
         }
         nonzero = !!rhi;
     }
     /* set rhi to top 63bit of the result (last bit is sticky) */
     if (nonzero) {
         e += 64;
         d = a_clz_64(rhi)-1;
         /* note: d > 0 */
         rhi = rhi<<d | rlo>>64-d | !!(rlo<<d);
     } else if (rlo) {
         d = a_clz_64(rlo)-1;
         if (d < 0)
             rhi = rlo>>1 | (rlo&1);
         else
             rhi = rlo<<d;
     } else {
         /* exact +-0 */
         return x*y + z;
     }
     e -= d;
     /* convert to double */
     int64_t i = rhi; /* i is in [1<<62,(1<<63)-1] */
     if (sign)
         i = -i;
     double r = i; /* |r| is in [0x1p62,0x1p63] */
     if (e < -1022-62) {
         /* result is subnormal before rounding */
         if (e == -1022-63) {
             double c = 0x1p63;
             if (sign)
                 c = -c;
             if (r == c) {
                 /* min normal after rounding, underflow depends
                    on arch behaviour which can be imitated by
                    a double to float conversion */
                 float fltmin = 0x0.ffffff8p-63*FLT_MIN * r;
                 return DBL_MIN/FLT_MIN * fltmin;
             }
             /* one bit is lost when scaled, add another top bit to
                only round once at conversion if it is inexact */
             if (rhi << 53) {
                 i = rhi>>1 | (rhi&1) | 1ull<<62;
                 if (sign)
                     i = -i;
                 r = i;
                 r = 2*r - c; /* remove top bit */
                 /* raise underflow portably, such that it
                    cannot be optimized away */
                 {
                     double_t tiny = DBL_MIN/FLT_MIN * r;
                     r += (double)(tiny*tiny) * (r-r);
                 }
             }
         } else {
             /* only round once when scaled */
             d = 10;
             i = ( rhi>>d | !!(rhi<<64-d) ) << d;
             if (sign)
                 i = -i;
             r = i;
         }
     }
     return scalbn(r, e);
 }
References a_clz_64(), c, num::e, i, num::m, mul(), normalize(), r, scalbn(), num::sign, tiny, x, y, and ZEROINFNAN.
fmaf()
float fmaf (float x, float y, float z)
Definition at line 39 of file fmaf.c.
 {
     #pragma STDC FENV_ACCESS ON
     double xy, result;
     union {double f; uint64_t i;} u;
     int e;
     xy = (double)x * y;
     result = xy + z;
     u.f = result;
     e = u.i>>52 & 0x7ff;
     /* Common case: The double precision result is fine. */
     if ((u.i & 0x1fffffff) != 0x10000000 || /* not a halfway case */
         e == 0x7ff ||                   /* NaN */
         result - xy == z ||                 /* exact */
         fegetround() != FE_TONEAREST)       /* not round-to-nearest */
     {
         /*
         underflow may not be raised correctly, example:
         fmaf(0x1p-120f, 0x1p-120f, 0x1p-149f)
         */
 #if defined(FE_INEXACT) && defined(FE_UNDERFLOW)
         if (e < 0x3ff-126 && e >= 0x3ff-149 && fetestexcept(FE_INEXACT)) {
             feclearexcept(FE_INEXACT);
             /* TODO: gcc and clang bug workaround */
             volatile float vz = z;
             result = xy + vz;
             if (fetestexcept(FE_INEXACT))
                 feraiseexcept(FE_UNDERFLOW);
             else
                 feraiseexcept(FE_INEXACT);
         }
 #endif
         z = result;
         return z;
     }
     /*
      * If result is inexact, and exactly halfway between two float values,
      * we need to adjust the low-order bit in the direction of the error.
      */
 #ifdef FE_TOWARDZERO
     fesetround(FE_TOWARDZERO);
 #endif
     volatile double vxy = xy;  /* XXX work around gcc CSE bug */
     double adjusted_result = vxy + z;
     fesetround(FE_TONEAREST);
     if (result == adjusted_result) {
         u.f = adjusted_result;
         u.i++;
         adjusted_result = u.f;
     }
     z = adjusted_result;
     return z;
 }
References feclearexcept(), fegetround(), feraiseexcept(), fesetround(), fetestexcept(), i, mlibc::result, x, and y.
fmal()
long double fmal (long double , long double , long double)
fmax()
double fmax (double x, double y)
Definition at line 3 of file fmax.c.
 {
     if (isnan(x))
         return y;
     if (isnan(y))
         return x;
     /* handle signed zeros, see C99 Annex F.9.9.2 */
     if (signbit(x) != signbit(y))
         return signbit(x) ? y : x;
     return x < y ? y : x;
 }
References isnan, signbit, x, and y.
fmaxf()
float fmaxf (float x, float y)
Definition at line 3 of file fmaxf.c.
 {
     if (isnan(x))
         return y;
     if (isnan(y))
         return x;
     /* handle signed zeroes, see C99 Annex F.9.9.2 */
     if (signbit(x) != signbit(y))
         return signbit(x) ? y : x;
     return x < y ? y : x;
 }
References isnan, signbit, x, and y.
fmaxl()
long double fmaxl (long double x, long double y)
Definition at line 10 of file fmaxl.c.
 {
     if (isnan(x))
         return y;
     if (isnan(y))
         return x;
     /* handle signed zeros, see C99 Annex F.9.9.2 */
     if (signbit(x) != signbit(y))
         return signbit(x) ? y : x;
     return x < y ? y : x;
 }
References isnan, signbit, x, and y.
fmin()
double fmin (double x, double y)
Definition at line 3 of file fmin.c.
 {
     if (isnan(x))
         return y;
     if (isnan(y))
         return x;
     /* handle signed zeros, see C99 Annex F.9.9.2 */
     if (signbit(x) != signbit(y))
         return signbit(x) ? x : y;
     return x < y ? x : y;
 }
References isnan, signbit, x, and y.
fminf()
float fminf (float x, float y)
Definition at line 3 of file fminf.c.
 {
     if (isnan(x))
         return y;
     if (isnan(y))
         return x;
     /* handle signed zeros, see C99 Annex F.9.9.2 */
     if (signbit(x) != signbit(y))
         return signbit(x) ? x : y;
     return x < y ? x : y;
 }
References isnan, signbit, x, and y.
fminl()
long double fminl (long double x, long double y)
Definition at line 10 of file fminl.c.
 {
     if (isnan(x))
         return y;
     if (isnan(y))
         return x;
     /* handle signed zeros, see C99 Annex F.9.9.2 */
     if (signbit(x) != signbit(y))
         return signbit(x) ? x : y;
     return x < y ? x : y;
 }
References isnan, signbit, x, and y.
fmod()
double fmod (double x, double y)
Definition at line 4 of file fmod.c.
 {
     union {double f; uint64_t i;} ux = {x}, uy = {y};
     int ex = ux.i>>52 & 0x7ff;
     int ey = uy.i>>52 & 0x7ff;
     int sx = ux.i>>63;
     uint64_t i;
     /* in the followings uxi should be ux.i, but then gcc wrongly adds */
     /* float load/store to inner loops ruining performance and code size */
     uint64_t uxi = ux.i;
     if (uy.i<<1 == 0 || isnan(y) || ex == 0x7ff)
         return (x*y)/(x*y);
     if (uxi<<1 <= uy.i<<1) {
         if (uxi<<1 == uy.i<<1)
             return 0*x;
         return x;
     }
     /* normalize x and y */
     if (!ex) {
         for (i = uxi<<12; i>>63 == 0; ex--, i <<= 1);
         uxi <<= -ex + 1;
     } else {
         uxi &= -1ULL >> 12;
         uxi |= 1ULL << 52;
     }
     if (!ey) {
         for (i = uy.i<<12; i>>63 == 0; ey--, i <<= 1);
         uy.i <<= -ey + 1;
     } else {
         uy.i &= -1ULL >> 12;
         uy.i |= 1ULL << 52;
     }
     /* x mod y */
     for (; ex > ey; ex--) {
         i = uxi - uy.i;
         if (i >> 63 == 0) {
             if (i == 0)
                 return 0*x;
             uxi = i;
         }
         uxi <<= 1;
     }
     i = uxi - uy.i;
     if (i >> 63 == 0) {
         if (i == 0)
             return 0*x;
         uxi = i;
     }
     for (; uxi>>52 == 0; uxi <<= 1, ex--);
     /* scale result */
     if (ex > 0) {
         uxi -= 1ULL << 52;
         uxi |= (uint64_t)ex << 52;
     } else {
         uxi >>= -ex + 1;
     }
     uxi |= (uint64_t)sx << 63;
     ux.i = uxi;
     return ux.f;
 }
References i, isnan, x, and y.
fmodf()
float fmodf (float x, float y)
Definition at line 4 of file fmodf.c.
 {
     union {float f; uint32_t i;} ux = {x}, uy = {y};
     int ex = ux.i>>23 & 0xff;
     int ey = uy.i>>23 & 0xff;
     uint32_t sx = ux.i & 0x80000000;
     uint32_t i;
     uint32_t uxi = ux.i;
     if (uy.i<<1 == 0 || isnan(y) || ex == 0xff)
         return (x*y)/(x*y);
     if (uxi<<1 <= uy.i<<1) {
         if (uxi<<1 == uy.i<<1)
             return 0*x;
         return x;
     }
     /* normalize x and y */
     if (!ex) {
         for (i = uxi<<9; i>>31 == 0; ex--, i <<= 1);
         uxi <<= -ex + 1;
     } else {
         uxi &= -1U >> 9;
         uxi |= 1U << 23;
     }
     if (!ey) {
         for (i = uy.i<<9; i>>31 == 0; ey--, i <<= 1);
         uy.i <<= -ey + 1;
     } else {
         uy.i &= -1U >> 9;
         uy.i |= 1U << 23;
     }
     /* x mod y */
     for (; ex > ey; ex--) {
         i = uxi - uy.i;
         if (i >> 31 == 0) {
             if (i == 0)
                 return 0*x;
             uxi = i;
         }
         uxi <<= 1;
     }
     i = uxi - uy.i;
     if (i >> 31 == 0) {
         if (i == 0)
             return 0*x;
         uxi = i;
     }
     for (; uxi>>23 == 0; uxi <<= 1, ex--);
     /* scale result up */
     if (ex > 0) {
         uxi -= 1U << 23;
         uxi |= (uint32_t)ex << 23;
     } else {
         uxi >>= -ex + 1;
     }
     uxi |= sx;
     ux.i = uxi;
     return ux.f;
 }
References i, isnan, x, and y.
fmodl()
long double fmodl (long double x, long double y)
frexp()
double frexp (double x, int * power)
Definition at line 4 of file frexp.c.
 {
     union { double d; uint64_t i; } y = { x };
     int ee = y.i>>52 & 0x7ff;
     if (!ee) {
         if (x) {
             x = frexp(x*0x1p64, e);
             *e -= 64;
         } else *e = 0;
         return x;
     } else if (ee == 0x7ff) {
         return x;
     }
     *e = ee - 0x3fe;
     y.i &= 0x800fffffffffffffull;
     y.i |= 0x3fe0000000000000ull;
     return y.d;
 }
References frexp(), i, x, and y.
Referenced by frexp().
frexpf()
float frexpf (float x, int * power)
Definition at line 4 of file frexpf.c.
 {
     union { float f; uint32_t i; } y = { x };
     int ee = y.i>>23 & 0xff;
     if (!ee) {
         if (x) {
             x = frexpf(x*0x1p64, e);
             *e -= 64;
         } else *e = 0;
         return x;
     } else if (ee == 0xff) {
         return x;
     }
     *e = ee - 0x7e;
     y.i &= 0x807ffffful;
     y.i |= 0x3f000000ul;
     return y.f;
 }
References frexpf(), i, x, and y.
Referenced by frexpf().
frexpl()
long double frexpl (long double x, int * power)
hypot()
double hypot (double x, double y)
Definition at line 22 of file hypot.c.
 {
     union {double f; uint64_t i;} ux = {x}, uy = {y}, ut;
     int ex, ey;
     double_t hx, lx, hy, ly, z;
     /* arrange |x| >= |y| */
     ux.i &= -1ULL>>1;
     uy.i &= -1ULL>>1;
     if (ux.i < uy.i) {
         ut = ux;
         ux = uy;
         uy = ut;
     }
     /* special cases */
     ex = ux.i>>52;
     ey = uy.i>>52;
     x = ux.f;
     y = uy.f;
     /* note: hypot(inf,nan) == inf */
     if (ey == 0x7ff)
         return y;
     if (ex == 0x7ff || uy.i == 0)
         return x;
     /* note: hypot(x,y) ~= x + y*y/x/2 with inexact for small y/x */
     /* 64 difference is enough for ld80 double_t */
     if (ex - ey > 64)
         return x + y;
     /* precise sqrt argument in nearest rounding mode without overflow */
     /* xh*xh must not overflow and xl*xl must not underflow in sq */
     z = 1;
     if (ex > 0x3ff+510) {
         z = 0x1p700;
         x *= 0x1p-700;
         y *= 0x1p-700;
     } else if (ey < 0x3ff-450) {
         z = 0x1p-700;
         x *= 0x1p700;
         y *= 0x1p700;
     }
     sq(&hx, &lx, x);
     sq(&hy, &ly, y);
     return z*sqrt(ly+lx+hy+hx);
 }
References i, sq(), sqrt(), x, and y.
Referenced by cabs().
hypotf()
float hypotf (float x, float y)
Definition at line 4 of file hypotf.c.
 {
     union {float f; uint32_t i;} ux = {x}, uy = {y}, ut;
     float_t z;
     ux.i &= -1U>>1;
     uy.i &= -1U>>1;
     if (ux.i < uy.i) {
         ut = ux;
         ux = uy;
         uy = ut;
     }
     x = ux.f;
     y = uy.f;
     if (uy.i == 0xff<<23)
         return y;
     if (ux.i >= 0xff<<23 || uy.i == 0 || ux.i - uy.i >= 25<<23)
         return x + y;
     z = 1;
     if (ux.i >= (0x7f+60)<<23) {
         z = 0x1p90f;
         x *= 0x1p-90f;
         y *= 0x1p-90f;
     } else if (uy.i < (0x7f-60)<<23) {
         z = 0x1p-90f;
         x *= 0x1p90f;
         y *= 0x1p90f;
     }
     return z*sqrtf((double)x*x + (double)y*y);
 }
References i, sqrtf(), x, and y.
Referenced by cabsf().
hypotl()
long double hypotl (long double x, long double y)
ilogb()
int ilogb (double x)
Definition at line 4 of file ilogb.c.
 {
     #pragma STDC FENV_ACCESS ON
     union {double f; uint64_t i;} u = {x};
     uint64_t i = u.i;
     int e = i>>52 & 0x7ff;
     if (!e) {
         i <<= 12;
         if (i == 0) {
             FORCE_EVAL(0/0.0f);
             return FP_ILOGB0;
         }
         /* subnormal x */
         for (e = -0x3ff; i>>63 == 0; e--, i<<=1);
         return e;
     }
     if (e == 0x7ff) {
         FORCE_EVAL(0/0.0f);
         return i<<12 ? FP_ILOGBNAN : INT_MAX;
     }
     return e - 0x3ff;
 }
References FORCE_EVAL, FP_ILOGB0, FP_ILOGBNAN, i, INT_MAX, and x.
Referenced by logb(), and significand().
ilogbf()
int ilogbf (float x)
Definition at line 4 of file ilogbf.c.
 {
     #pragma STDC FENV_ACCESS ON
     union {float f; uint32_t i;} u = {x};
     uint32_t i = u.i;
     int e = i>>23 & 0xff;
     if (!e) {
         i <<= 9;
         if (i == 0) {
             FORCE_EVAL(0/0.0f);
             return FP_ILOGB0;
         }
         /* subnormal x */
         for (e = -0x7f; i>>31 == 0; e--, i<<=1);
         return e;
     }
     if (e == 0xff) {
         FORCE_EVAL(0/0.0f);
         return i<<9 ? FP_ILOGBNAN : INT_MAX;
     }
     return e - 0x7f;
 }
References FORCE_EVAL, FP_ILOGB0, FP_ILOGBNAN, i, INT_MAX, and x.
Referenced by logbf(), and significandf().
ilogbl()
int ilogbl (long double x)
Referenced by logbl().
ldexp()
double ldexp (double x, int power)
Definition at line 3 of file ldexp.c.
 {
     return scalbn(x, n);
 }
References n, scalbn(), and x.
ldexpf()
float ldexpf (float x, int power)
Definition at line 3 of file ldexpf.c.
 {
     return scalbnf(x, n);
 }
References n, scalbnf(), and x.
ldexpl()
long double ldexpl (long double x, int power)
Definition at line 3 of file ldexpl.c.
 {
     return scalbnl(x, n);
 }
References n, scalbnl(), and x.
lgamma()
double lgamma (double x)
Definition at line 6 of file lgamma.c.
 {
     return __lgamma_r(x, &__signgam);
 }
References __lgamma_r(), __signgam, and x.
lgammaf()
float lgammaf (float x)
Definition at line 6 of file lgammaf.c.
 {
     return __lgammaf_r(x, &__signgam);
 }
References __lgammaf_r(), __signgam, and x.
lgammal()
long double lgammal (long double x)
Definition at line 356 of file lgammal.c.
 {
     return __lgammal_r(x, &__signgam);
 }
References __signgam, and x.
llrint()
long long llrint (double x)
Definition at line 5 of file llrint.c.
 {
     return rint(x);
 }
References rint(), and x.
llrintf()
long long llrintf (float x)
Definition at line 5 of file llrintf.c.
 {
     return rintf(x);
 }
References rintf(), and x.
llrintl()
long long llrintl (long double x)
Definition at line 32 of file llrintl.c.
 {
     return rintl(x);
 }
References rintl(), and x.
llround()
long long llround (double x)
Definition at line 3 of file llround.c.
 {
     return round(x);
 }
References round(), and x.
llroundf()
long long llroundf (float x)
Definition at line 3 of file llroundf.c.
 {
     return roundf(x);
 }
References roundf(), and x.
llroundl()
long long llroundl (long double x)
Definition at line 3 of file llroundl.c.
 {
     return roundl(x);
 }
References roundl(), and x.
log()
double log (double x)
Definition at line 77 of file log.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t hfsq,f,s,z,R,w,t1,t2,dk;
     uint32_t hx;
     int k;
     hx = u.i>>32;
     k = 0;
     if (hx < 0x00100000 || hx>>31) {
         if (u.i<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (hx>>31)
             return (x-x)/0.0; /* log(-#) = NaN */
         /* subnormal number, scale x up */
         k -= 54;
         x *= 0x1p54;
         u.f = x;
         hx = u.i>>32;
     } else if (hx >= 0x7ff00000) {
         return x;
     } else if (hx == 0x3ff00000 && u.i<<32 == 0)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     hx += 0x3ff00000 - 0x3fe6a09e;
     k += (int)(hx>>20) - 0x3ff;
     hx = (hx&0x000fffff) + 0x3fe6a09e;
     u.i = (uint64_t)hx<<32 | (u.i&0xffffffff);
     x = u.f;
     f = x - 1.0;
     hfsq = 0.5*f*f;
     s = f/(2.0+f);
     z = s*s;
     w = z*z;
     t1 = w*(Lg2+w*(Lg4+w*Lg6));
     t2 = z*(Lg1+w*(Lg3+w*(Lg5+w*Lg7)));
     R = t2 + t1;
     dk = k;
     return s*(hfsq+R) + dk*ln2_lo - hfsq + f + dk*ln2_hi;
 }
References i, int, k, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, ln2_hi, ln2_lo, R, t1, t2, and x.
Referenced by __lgamma_r(), acosh(), asinh(), catan(), clog(), cpow(), jn(), log2(), y0(), and y1().
log10()
double log10 (double x)
Definition at line 36 of file log10.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t hfsq,f,s,z,R,w,t1,t2,dk,y,hi,lo,val_hi,val_lo;
     uint32_t hx;
     int k;
     hx = u.i>>32;
     k = 0;
     if (hx < 0x00100000 || hx>>31) {
         if (u.i<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (hx>>31)
             return (x-x)/0.0; /* log(-#) = NaN */
         /* subnormal number, scale x up */
         k -= 54;
         x *= 0x1p54;
         u.f = x;
         hx = u.i>>32;
     } else if (hx >= 0x7ff00000) {
         return x;
     } else if (hx == 0x3ff00000 && u.i<<32 == 0)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     hx += 0x3ff00000 - 0x3fe6a09e;
     k += (int)(hx>>20) - 0x3ff;
     hx = (hx&0x000fffff) + 0x3fe6a09e;
     u.i = (uint64_t)hx<<32 | (u.i&0xffffffff);
     x = u.f;
     f = x - 1.0;
     hfsq = 0.5*f*f;
     s = f/(2.0+f);
     z = s*s;
     w = z*z;
     t1 = w*(Lg2+w*(Lg4+w*Lg6));
     t2 = z*(Lg1+w*(Lg3+w*(Lg5+w*Lg7)));
     R = t2 + t1;
     /* See log2.c for details. */
     /* hi+lo = f - hfsq + s*(hfsq+R) ~ log(1+f) */
     hi = f - hfsq;
     u.f = hi;
     u.i &= (uint64_t)-1<<32;
     hi = u.f;
     lo = f - hi - hfsq + s*(hfsq+R);
     /* val_hi+val_lo ~ log10(1+f) + k*log10(2) */
     val_hi = hi*ivln10hi;
     dk = k;
     y = dk*log10_2hi;
     val_lo = dk*log10_2lo + (lo+hi)*ivln10lo + lo*ivln10hi;
     /*
      * Extra precision in for adding y is not strictly needed
      * since there is no very large cancellation near x = sqrt(2) or
      * x = 1/sqrt(2), but we do it anyway since it costs little on CPUs
      * with some parallelism and it reduces the error for many args.
      */
     w = y + val_hi;
     val_lo += (y - w) + val_hi;
     val_hi = w;
     return val_lo + val_hi;
 }
References i, int, ivln10hi, ivln10lo, k, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, log10_2hi, log10_2lo, R, t1, t2, x, and y.
log10f()
float log10f (float x)
Definition at line 30 of file log10f.c.
 {
     union {float f; uint32_t i;} u = {x};
     float_t hfsq,f,s,z,R,w,t1,t2,dk,hi,lo;
     uint32_t ix;
     int k;
     ix = u.i;
     k = 0;
     if (ix < 0x00800000 || ix>>31) {  /* x < 2**-126  */
         if (ix<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (ix>>31)
             return (x-x)/0.0f; /* log(-#) = NaN */
         /* subnormal number, scale up x */
         k -= 25;
         x *= 0x1p25f;
         u.f = x;
         ix = u.i;
     } else if (ix >= 0x7f800000) {
         return x;
     } else if (ix == 0x3f800000)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     ix += 0x3f800000 - 0x3f3504f3;
     k += (int)(ix>>23) - 0x7f;
     ix = (ix&0x007fffff) + 0x3f3504f3;
     u.i = ix;
     x = u.f;
     f = x - 1.0f;
     s = f/(2.0f + f);
     z = s*s;
     w = z*z;
     t1= w*(Lg2+w*Lg4);
     t2= z*(Lg1+w*Lg3);
     R = t2 + t1;
     hfsq = 0.5f*f*f;
     hi = f - hfsq;
     u.f = hi;
     u.i &= 0xfffff000;
     hi = u.f;
     lo = f - hi - hfsq + s*(hfsq+R);
     dk = k;
     return dk*log10_2lo + (lo+hi)*ivln10lo + lo*ivln10hi + hi*ivln10hi + dk*log10_2hi;
 }
References i, int, ivln10hi, ivln10lo, k, Lg1, Lg2, Lg3, Lg4, log10_2hi, log10_2lo, R, t1, t2, and x.
log10l()
long double log10l (long double x)
log1p()
double log1p (double x)
Definition at line 69 of file log1p.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t hfsq,f,c,s,z,R,w,t1,t2,dk;
     uint32_t hx,hu;
     int k;
     hx = u.i>>32;
     k = 1;
     if (hx < 0x3fda827a || hx>>31) {  /* 1+x < sqrt(2)+ */
         if (hx >= 0xbff00000) {  /* x <= -1.0 */
             if (x == -1)
                 return x/0.0; /* log1p(-1) = -inf */
             return (x-x)/0.0;     /* log1p(x<-1) = NaN */
         }
         if (hx<<1 < 0x3ca00000<<1) {  /* |x| < 2**-53 */
             /* underflow if subnormal */
             if ((hx&0x7ff00000) == 0)
                 FORCE_EVAL((float)x);
             return x;
         }
         if (hx <= 0xbfd2bec4) {  /* sqrt(2)/2- <= 1+x < sqrt(2)+ */
             k = 0;
             c = 0;
             f = x;
         }
     } else if (hx >= 0x7ff00000)
         return x;
     if (k) {
         u.f = 1 + x;
         hu = u.i>>32;
         hu += 0x3ff00000 - 0x3fe6a09e;
         k = (int)(hu>>20) - 0x3ff;
         /* correction term ~ log(1+x)-log(u), avoid underflow in c/u */
         if (k < 54) {
             c = k >= 2 ? 1-(u.f-x) : x-(u.f-1);
             c /= u.f;
         } else
             c = 0;
         /* reduce u into [sqrt(2)/2, sqrt(2)] */
         hu = (hu&0x000fffff) + 0x3fe6a09e;
         u.i = (uint64_t)hu<<32 | (u.i&0xffffffff);
         f = u.f - 1;
     }
     hfsq = 0.5*f*f;
     s = f/(2.0+f);
     z = s*s;
     w = z*z;
     t1 = w*(Lg2+w*(Lg4+w*Lg6));
     t2 = z*(Lg1+w*(Lg3+w*(Lg5+w*Lg7)));
     R = t2 + t1;
     dk = k;
     return s*(hfsq+R) + (dk*ln2_lo+c) - hfsq + f + dk*ln2_hi;
 }
References c, FORCE_EVAL, i, int, k, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, ln2_hi, ln2_lo, R, t1, t2, and x.
Referenced by acosh(), asinh(), and atanh().
log1pf()
float log1pf (float x)
Definition at line 24 of file log1pf.c.
 {
     union {float f; uint32_t i;} u = {x};
     float_t hfsq,f,c,s,z,R,w,t1,t2,dk;
     uint32_t ix,iu;
     int k;
     ix = u.i;
     k = 1;
     if (ix < 0x3ed413d0 || ix>>31) {  /* 1+x < sqrt(2)+  */
         if (ix >= 0xbf800000) {  /* x <= -1.0 */
             if (x == -1)
                 return x/0.0f; /* log1p(-1)=+inf */
             return (x-x)/0.0f;     /* log1p(x<-1)=NaN */
         }
         if (ix<<1 < 0x33800000<<1) {   /* |x| < 2**-24 */
             /* underflow if subnormal */
             if ((ix&0x7f800000) == 0)
                 FORCE_EVAL(x*x);
             return x;
         }
         if (ix <= 0xbe95f619) { /* sqrt(2)/2- <= 1+x < sqrt(2)+ */
             k = 0;
             c = 0;
             f = x;
         }
     } else if (ix >= 0x7f800000)
         return x;
     if (k) {
         u.f = 1 + x;
         iu = u.i;
         iu += 0x3f800000 - 0x3f3504f3;
         k = (int)(iu>>23) - 0x7f;
         /* correction term ~ log(1+x)-log(u), avoid underflow in c/u */
         if (k < 25) {
             c = k >= 2 ? 1-(u.f-x) : x-(u.f-1);
             c /= u.f;
         } else
             c = 0;
         /* reduce u into [sqrt(2)/2, sqrt(2)] */
         iu = (iu&0x007fffff) + 0x3f3504f3;
         u.i = iu;
         f = u.f - 1;
     }
     s = f/(2.0f + f);
     z = s*s;
     w = z*z;
     t1= w*(Lg2+w*Lg4);
     t2= z*(Lg1+w*Lg3);
     R = t2 + t1;
     hfsq = 0.5f*f*f;
     dk = k;
     return s*(hfsq+R) + (dk*ln2_lo+c) - hfsq + f + dk*ln2_hi;
 }
References c, FORCE_EVAL, i, int, k, Lg1, Lg2, Lg3, Lg4, ln2_hi, ln2_lo, R, t1, t2, and x.
Referenced by acoshf(), asinhf(), and atanhf().
log1pl()
long double log1pl (long double x)
log2()
double log2 (double x)
Definition at line 34 of file log2.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t hfsq,f,s,z,R,w,t1,t2,y,hi,lo,val_hi,val_lo;
     uint32_t hx;
     int k;
     hx = u.i>>32;
     k = 0;
     if (hx < 0x00100000 || hx>>31) {
         if (u.i<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (hx>>31)
             return (x-x)/0.0; /* log(-#) = NaN */
         /* subnormal number, scale x up */
         k -= 54;
         x *= 0x1p54;
         u.f = x;
         hx = u.i>>32;
     } else if (hx >= 0x7ff00000) {
         return x;
     } else if (hx == 0x3ff00000 && u.i<<32 == 0)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     hx += 0x3ff00000 - 0x3fe6a09e;
     k += (int)(hx>>20) - 0x3ff;
     hx = (hx&0x000fffff) + 0x3fe6a09e;
     u.i = (uint64_t)hx<<32 | (u.i&0xffffffff);
     x = u.f;
     f = x - 1.0;
     hfsq = 0.5*f*f;
     s = f/(2.0+f);
     z = s*s;
     w = z*z;
     t1 = w*(Lg2+w*(Lg4+w*Lg6));
     t2 = z*(Lg1+w*(Lg3+w*(Lg5+w*Lg7)));
     R = t2 + t1;
     /*
      * f-hfsq must (for args near 1) be evaluated in extra precision
      * to avoid a large cancellation when x is near sqrt(2) or 1/sqrt(2).
      * This is fairly efficient since f-hfsq only depends on f, so can
      * be evaluated in parallel with R.  Not combining hfsq with R also
      * keeps R small (though not as small as a true `lo' term would be),
      * so that extra precision is not needed for terms involving R.
      *
      * Compiler bugs involving extra precision used to break Dekker's
      * theorem for spitting f-hfsq as hi+lo, unless double_t was used
      * or the multi-precision calculations were avoided when double_t
      * has extra precision.  These problems are now automatically
      * avoided as a side effect of the optimization of combining the
      * Dekker splitting step with the clear-low-bits step.
      *
      * y must (for args near sqrt(2) and 1/sqrt(2)) be added in extra
      * precision to avoid a very large cancellation when x is very near
      * these values.  Unlike the above cancellations, this problem is
      * specific to base 2.  It is strange that adding +-1 is so much
      * harder than adding +-ln2 or +-log10_2.
      *
      * This uses Dekker's theorem to normalize y+val_hi, so the
      * compiler bugs are back in some configurations, sigh.  And I
      * don't want to used double_t to avoid them, since that gives a
      * pessimization and the support for avoiding the pessimization
      * is not yet available.
      *
      * The multi-precision calculations for the multiplications are
      * routine.
      */
     /* hi+lo = f - hfsq + s*(hfsq+R) ~ log(1+f) */
     hi = f - hfsq;
     u.f = hi;
     u.i &= (uint64_t)-1<<32;
     hi = u.f;
     lo = f - hi - hfsq + s*(hfsq+R);
     val_hi = hi*ivln2hi;
     val_lo = (lo+hi)*ivln2lo + lo*ivln2hi;
     /* spadd(val_hi, val_lo, y), except for not using double_t: */
     y = k;
     w = y + val_hi;
     val_lo += (y - w) + val_hi;
     val_hi = w;
     return val_lo + val_hi;
 }
References i, int, ivln2hi, ivln2lo, k, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, R, t1, t2, x, and y.
log2f()
float log2f (float x)
Definition at line 28 of file log2f.c.
 {
     union {float f; uint32_t i;} u = {x};
     float_t hfsq,f,s,z,R,w,t1,t2,hi,lo;
     uint32_t ix;
     int k;
     ix = u.i;
     k = 0;
     if (ix < 0x00800000 || ix>>31) {  /* x < 2**-126  */
         if (ix<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (ix>>31)
             return (x-x)/0.0f; /* log(-#) = NaN */
         /* subnormal number, scale up x */
         k -= 25;
         x *= 0x1p25f;
         u.f = x;
         ix = u.i;
     } else if (ix >= 0x7f800000) {
         return x;
     } else if (ix == 0x3f800000)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     ix += 0x3f800000 - 0x3f3504f3;
     k += (int)(ix>>23) - 0x7f;
     ix = (ix&0x007fffff) + 0x3f3504f3;
     u.i = ix;
     x = u.f;
     f = x - 1.0f;
     s = f/(2.0f + f);
     z = s*s;
     w = z*z;
     t1= w*(Lg2+w*Lg4);
     t2= z*(Lg1+w*Lg3);
     R = t2 + t1;
     hfsq = 0.5f*f*f;
     hi = f - hfsq;
     u.f = hi;
     u.i &= 0xfffff000;
     hi = u.f;
     lo = f - hi - hfsq + s*(hfsq+R);
     return (lo+hi)*ivln2lo + lo*ivln2hi + hi*ivln2hi + k;
 }
References i, int, ivln2hi, ivln2lo, k, Lg1, Lg2, Lg3, Lg4, R, t1, t2, and x.
log2l()
long double log2l (long double x)
logb()
double logb (double x)
Definition at line 10 of file logb.c.
 {
     if (!isfinite(x))
         return x * x;
     if (x == 0)
         return -1/(x*x);
     return ilogb(x);
 }
References ilogb(), isfinite, and x.
logbf()
float logbf (float x)
Definition at line 3 of file logbf.c.
 {
     if (!isfinite(x))
         return x * x;
     if (x == 0)
         return -1/(x*x);
     return ilogbf(x);
 }
References ilogbf(), isfinite, and x.
logbl()
long double logbl (long double x)
Definition at line 8 of file logbl.c.
 {
     if (!isfinite(x))
         return x * x;
     if (x == 0)
         return -1/(x*x);
     return ilogbl(x);
 }
References ilogbl(), isfinite, and x.
logf()
float logf (float x)
Definition at line 28 of file logf.c.
 {
     union {float f; uint32_t i;} u = {x};
     float_t hfsq,f,s,z,R,w,t1,t2,dk;
     uint32_t ix;
     int k;
     ix = u.i;
     k = 0;
     if (ix < 0x00800000 || ix>>31) {  /* x < 2**-126  */
         if (ix<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (ix>>31)
             return (x-x)/0.0f; /* log(-#) = NaN */
         /* subnormal number, scale up x */
         k -= 25;
         x *= 0x1p25f;
         u.f = x;
         ix = u.i;
     } else if (ix >= 0x7f800000) {
         return x;
     } else if (ix == 0x3f800000)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     ix += 0x3f800000 - 0x3f3504f3;
     k += (int)(ix>>23) - 0x7f;
     ix = (ix&0x007fffff) + 0x3f3504f3;
     u.i = ix;
     x = u.f;
     f = x - 1.0f;
     s = f/(2.0f + f);
     z = s*s;
     w = z*z;
     t1= w*(Lg2+w*Lg4);
     t2= z*(Lg1+w*Lg3);
     R = t2 + t1;
     hfsq = 0.5f*f*f;
     dk = k;
     return s*(hfsq+R) + dk*ln2_lo - hfsq + f + dk*ln2_hi;
 }
References i, int, k, Lg1, Lg2, Lg3, Lg4, ln2_hi, ln2_lo, R, t1, t2, and x.
Referenced by __lgammaf_r(), acoshf(), asinhf(), catanf(), clogf(), cpowf(), jnf(), y0f(), and y1f().
logl()
long double logl (long double x)
lrint()
long lrint (double x)
Definition at line 42 of file lrint.c.
 {
     return rint(x);
 }
References rint(), and x.
lrintf()
long lrintf (float x)
Definition at line 5 of file lrintf.c.
 {
     return rintf(x);
 }
References rintf(), and x.
lrintl()
long lrintl (long double x)
Definition at line 32 of file lrintl.c.
 {
     return rintl(x);
 }
References rintl(), and x.
lround()
long lround (double x)
Definition at line 3 of file lround.c.
 {
     return round(x);
 }
References round(), and x.
lroundf()
long lroundf (float x)
Definition at line 3 of file lroundf.c.
 {
     return roundf(x);
 }
References roundf(), and x.
lroundl()
long lroundl (long double x)
Definition at line 3 of file lroundl.c.
 {
     return roundl(x);
 }
References roundl(), and x.
modf()
double modf (double x, double * integral)
Definition at line 3 of file modf.c.
 {
     union {double f; uint64_t i;} u = {x};
     uint64_t mask;
     int e = (int)(u.i>>52 & 0x7ff) - 0x3ff;
     /* no fractional part */
     if (e >= 52) {
         *iptr = x;
         if (e == 0x400 && u.i<<12 != 0) /* nan */
             return x;
         u.i &= 1ULL<<63;
         return u.f;
     }
     /* no integral part*/
     if (e < 0) {
         u.i &= 1ULL<<63;
         *iptr = u.f;
         return x;
     }
     mask = -1ULL>>12>>e;
     if ((u.i & mask) == 0) {
         *iptr = x;
         u.i &= 1ULL<<63;
         return u.f;
     }
     u.i &= ~mask;
     *iptr = u.f;
     return x - u.f;
 }
References i, int, and x.
Referenced by exp10().
modff()
float modff (float x, float * integral)
Definition at line 3 of file modff.c.
 {
     union {float f; uint32_t i;} u = {x};
     uint32_t mask;
     int e = (int)(u.i>>23 & 0xff) - 0x7f;
     /* no fractional part */
     if (e >= 23) {
         *iptr = x;
         if (e == 0x80 && u.i<<9 != 0) { /* nan */
             return x;
         }
         u.i &= 0x80000000;
         return u.f;
     }
     /* no integral part */
     if (e < 0) {
         u.i &= 0x80000000;
         *iptr = u.f;
         return x;
     }
     mask = 0x007fffff>>e;
     if ((u.i & mask) == 0) {
         *iptr = x;
         u.i &= 0x80000000;
         return u.f;
     }
     u.i &= ~mask;
     *iptr = u.f;
     return x - u.f;
 }
References i, int, and x.
Referenced by exp10f().
modfl()
long double modfl (long double x, long double * integral)
nan()
double nan (const char * tag)
Definition at line 3 of file nan.c.
 {
     return NAN;
 }
References NAN.
nanf()
float nanf (const char * tag)
Definition at line 3 of file nanf.c.
 {
     return NAN;
 }
References NAN.
nanl()
long double nanl (const char * tag)
Definition at line 3 of file nanl.c.
 {
     return NAN;
 }
References NAN.
nearbyint()
double nearbyint (double x)
Definition at line 6 of file nearbyint.c.
 {
 #ifdef FE_INEXACT
     #pragma STDC FENV_ACCESS ON
     int e;
     e = fetestexcept(FE_INEXACT);
 #endif
     x = rint(x);
 #ifdef FE_INEXACT
     if (!e)
         feclearexcept(FE_INEXACT);
 #endif
     return x;
 }
References feclearexcept(), fetestexcept(), rint(), and x.
nearbyintf()
float nearbyintf (float x)
Definition at line 4 of file nearbyintf.c.
 {
 #ifdef FE_INEXACT
     #pragma STDC FENV_ACCESS ON
     int e;
     e = fetestexcept(FE_INEXACT);
 #endif
     x = rintf(x);
 #ifdef FE_INEXACT
     if (!e)
         feclearexcept(FE_INEXACT);
 #endif
     return x;
 }
References feclearexcept(), fetestexcept(), rintf(), and x.
nearbyintl()
long double nearbyintl (long double x)
Definition at line 11 of file nearbyintl.c.
 {
 #ifdef FE_INEXACT
     #pragma STDC FENV_ACCESS ON
     int e;
     e = fetestexcept(FE_INEXACT);
 #endif
     x = rintl(x);
 #ifdef FE_INEXACT
     if (!e)
         feclearexcept(FE_INEXACT);
 #endif
     return x;
 }
References feclearexcept(), fetestexcept(), rintl(), and x.
nextafter()
double nextafter (double x, double dir)
Definition at line 3 of file nextafter.c.
 {
     union {double f; uint64_t i;} ux={x}, uy={y};
     uint64_t ax, ay;
     int e;
     if (isnan(x) || isnan(y))
         return x + y;
     if (ux.i == uy.i)
         return y;
     ax = ux.i & -1ULL/2;
     ay = uy.i & -1ULL/2;
     if (ax == 0) {
         if (ay == 0)
             return y;
         ux.i = (uy.i & 1ULL<<63) | 1;
     } else if (ax > ay || ((ux.i ^ uy.i) & 1ULL<<63))
         ux.i--;
     else
         ux.i++;
     e = ux.i >> 52 & 0x7ff;
     /* raise overflow if ux.f is infinite and x is finite */
     if (e == 0x7ff)
         FORCE_EVAL(x+x);
     /* raise underflow if ux.f is subnormal or zero */
     if (e == 0)
         FORCE_EVAL(x*x + ux.f*ux.f);
     return ux.f;
 }
References FORCE_EVAL, i, if(), isnan, x, and y.
nextafterf()
float nextafterf (float x, float dir)
Definition at line 3 of file nextafterf.c.
 {
     union {float f; uint32_t i;} ux={x}, uy={y};
     uint32_t ax, ay, e;
     if (isnan(x) || isnan(y))
         return x + y;
     if (ux.i == uy.i)
         return y;
     ax = ux.i & 0x7fffffff;
     ay = uy.i & 0x7fffffff;
     if (ax == 0) {
         if (ay == 0)
             return y;
         ux.i = (uy.i & 0x80000000) | 1;
     } else if (ax > ay || ((ux.i ^ uy.i) & 0x80000000))
         ux.i--;
     else
         ux.i++;
     e = ux.i & 0x7f800000;
     /* raise overflow if ux.f is infinite and x is finite */
     if (e == 0x7f800000)
         FORCE_EVAL(x+x);
     /* raise underflow if ux.f is subnormal or zero */
     if (e == 0)
         FORCE_EVAL(x*x + ux.f*ux.f);
     return ux.f;
 }
References FORCE_EVAL, i, if(), isnan, x, and y.
nextafterl()
long double nextafterl (long double x, long double dir)
Referenced by nexttowardl().
nexttoward()
double nexttoward (double x, long double dir)
Definition at line 9 of file nexttoward.c.
 {
     union {double f; uint64_t i;} ux = {x};
     int e;
     if (isnan(x) || isnan(y))
         return x + y;
     if (x == y)
         return y;
     if (x == 0) {
         ux.i = 1;
         if (signbit(y))
             ux.i |= 1ULL<<63;
     } else if (x < y) {
         if (signbit(x))
             ux.i--;
         else
             ux.i++;
     } else {
         if (signbit(x))
             ux.i++;
         else
             ux.i--;
     }
     e = ux.i>>52 & 0x7ff;
     /* raise overflow if ux.f is infinite and x is finite */
     if (e == 0x7ff)
         FORCE_EVAL(x+x);
     /* raise underflow if ux.f is subnormal or zero */
     if (e == 0)
         FORCE_EVAL(x*x + ux.f*ux.f);
     return ux.f;
 }
References FORCE_EVAL, i, isnan, signbit, x, and y.
nexttowardf()
float nexttowardf (float x, long double dir)
Definition at line 3 of file nexttowardf.c.
 {
     union {float f; uint32_t i;} ux = {x};
     uint32_t e;
     if (isnan(x) || isnan(y))
         return x + y;
     if (x == y)
         return y;
     if (x == 0) {
         ux.i = 1;
         if (signbit(y))
             ux.i |= 0x80000000;
     } else if (x < y) {
         if (signbit(x))
             ux.i--;
         else
             ux.i++;
     } else {
         if (signbit(x))
             ux.i++;
         else
             ux.i--;
     }
     e = ux.i & 0x7f800000;
     /* raise overflow if ux.f is infinite and x is finite */
     if (e == 0x7f800000)
         FORCE_EVAL(x+x);
     /* raise underflow if ux.f is subnormal or zero */
     if (e == 0)
         FORCE_EVAL(x*x + ux.f*ux.f);
     return ux.f;
 }
References FORCE_EVAL, i, isnan, signbit, x, and y.
nexttowardl()
long double nexttowardl (long double x, long double dir)
Definition at line 3 of file nexttowardl.c.
 {
     return nextafterl(x, y);
 }
References nextafterl(), x, and y.
pow()
double pow (double x, double y)
Definition at line 92 of file pow.c.
 {
     double z,ax,z_h,z_l,p_h,p_l;
     double y1,t1,t2,r,s,t,u,v,w;
     int32_t i,j,k,yisint,n;
     int32_t hx,hy,ix,iy;
     uint32_t lx,ly;
     EXTRACT_WORDS(hx, lx, x);
     EXTRACT_WORDS(hy, ly, y);
     ix = hx & 0x7fffffff;
     iy = hy & 0x7fffffff;
     /* x**0 = 1, even if x is NaN */
     if ((iy|ly) == 0)
         return 1.0;
     /* 1**y = 1, even if y is NaN */
     if (hx == 0x3ff00000 && lx == 0)
         return 1.0;
     /* NaN if either arg is NaN */
     if (ix > 0x7ff00000 || (ix == 0x7ff00000 && lx != 0) ||
         iy > 0x7ff00000 || (iy == 0x7ff00000 && ly != 0))
         return x + y;
     /* determine if y is an odd int when x < 0
      * yisint = 0       ... y is not an integer
      * yisint = 1       ... y is an odd int
      * yisint = 2       ... y is an even int
      */
     yisint = 0;
     if (hx < 0) {
         if (iy >= 0x43400000)
             yisint = 2; /* even integer y */
         else if (iy >= 0x3ff00000) {
             k = (iy>>20) - 0x3ff;  /* exponent */
             if (k > 20) {
                 uint32_t j = ly>>(52-k);
                 if ((j<<(52-k)) == ly)
                     yisint = 2 - (j&1);
             } else if (ly == 0) {
                 uint32_t j = iy>>(20-k);
                 if ((j<<(20-k)) == iy)
                     yisint = 2 - (j&1);
             }
         }
     }
     /* special value of y */
     if (ly == 0) {
         if (iy == 0x7ff00000) {  /* y is +-inf */
             if (((ix-0x3ff00000)|lx) == 0)  /* (-1)**+-inf is 1 */
                 return 1.0;
             else if (ix >= 0x3ff00000) /* (|x|>1)**+-inf = inf,0 */
                 return hy >= 0 ? y : 0.0;
             else                       /* (|x|<1)**+-inf = 0,inf */
                 return hy >= 0 ? 0.0 : -y;
         }
         if (iy == 0x3ff00000) {    /* y is +-1 */
             if (hy >= 0)
                 return x;
             y = 1/x;
 #if FLT_EVAL_METHOD!=0
             {
                 union {double f; uint64_t i;} u = {y};
                 uint64_t i = u.i & -1ULL/2;
                 if (i>>52 == 0 && (i&(i-1)))
                     FORCE_EVAL((float)y);
             }
 #endif
             return y;
         }
         if (hy == 0x40000000)    /* y is 2 */
             return x*x;
         if (hy == 0x3fe00000) {  /* y is 0.5 */
             if (hx >= 0)     /* x >= +0 */
                 return sqrt(x);
         }
     }
     ax = fabs(x);
     /* special value of x */
     if (lx == 0) {
         if (ix == 0x7ff00000 || ix == 0 || ix == 0x3ff00000) { /* x is +-0,+-inf,+-1 */
             z = ax;
             if (hy < 0)   /* z = (1/|x|) */
                 z = 1.0/z;
             if (hx < 0) {
                 if (((ix-0x3ff00000)|yisint) == 0) {
                     z = (z-z)/(z-z); /* (-1)**non-int is NaN */
                 } else if (yisint == 1)
                     z = -z;          /* (x<0)**odd = -(|x|**odd) */
             }
             return z;
         }
     }
     s = 1.0; /* sign of result */
     if (hx < 0) {
         if (yisint == 0) /* (x<0)**(non-int) is NaN */
             return (x-x)/(x-x);
         if (yisint == 1) /* (x<0)**(odd int) */
             s = -1.0;
     }
     /* |y| is huge */
     if (iy > 0x41e00000) { /* if |y| > 2**31 */
         if (iy > 0x43f00000) {  /* if |y| > 2**64, must o/uflow */
             if (ix <= 0x3fefffff)
                 return hy < 0 ? huge*huge : tiny*tiny;
             if (ix >= 0x3ff00000)
                 return hy > 0 ? huge*huge : tiny*tiny;
         }
         /* over/underflow if x is not close to one */
         if (ix < 0x3fefffff)
             return hy < 0 ? s*huge*huge : s*tiny*tiny;
         if (ix > 0x3ff00000)
             return hy > 0 ? s*huge*huge : s*tiny*tiny;
         /* now |1-x| is tiny <= 2**-20, suffice to compute
            log(x) by x-x^2/2+x^3/3-x^4/4 */
         t = ax - 1.0;       /* t has 20 trailing zeros */
         w = (t*t)*(0.5 - t*(0.3333333333333333333333-t*0.25));
         u = ivln2_h*t;      /* ivln2_h has 21 sig. bits */
         v = t*ivln2_l - w*ivln2;
         t1 = u + v;
         SET_LOW_WORD(t1, 0);
         t2 = v - (t1-u);
     } else {
         double ss,s2,s_h,s_l,t_h,t_l;
         n = 0;
         /* take care subnormal number */
         if (ix < 0x00100000) {
             ax *= two53;
             n -= 53;
             GET_HIGH_WORD(ix,ax);
         }
         n += ((ix)>>20) - 0x3ff;
         j = ix & 0x000fffff;
         /* determine interval */
         ix = j | 0x3ff00000;   /* normalize ix */
         if (j <= 0x3988E)      /* |x|<sqrt(3/2) */
             k = 0;
         else if (j < 0xBB67A)  /* |x|<sqrt(3)   */
             k = 1;
         else {
             k = 0;
             n += 1;
             ix -= 0x00100000;
         }
         SET_HIGH_WORD(ax, ix);
         /* compute ss = s_h+s_l = (x-1)/(x+1) or (x-1.5)/(x+1.5) */
         u = ax - bp[k];        /* bp[0]=1.0, bp[1]=1.5 */
         v = 1.0/(ax+bp[k]);
         ss = u*v;
         s_h = ss;
         SET_LOW_WORD(s_h, 0);
         /* t_h=ax+bp[k] High */
         t_h = 0.0;
         SET_HIGH_WORD(t_h, ((ix>>1)|0x20000000) + 0x00080000 + (k<<18));
         t_l = ax - (t_h-bp[k]);
         s_l = v*((u-s_h*t_h)-s_h*t_l);
         /* compute log(ax) */
         s2 = ss*ss;
         r = s2*s2*(L1+s2*(L2+s2*(L3+s2*(L4+s2*(L5+s2*L6)))));
         r += s_l*(s_h+ss);
         s2 = s_h*s_h;
         t_h = 3.0 + s2 + r;
         SET_LOW_WORD(t_h, 0);
         t_l = r - ((t_h-3.0)-s2);
         /* u+v = ss*(1+...) */
         u = s_h*t_h;
         v = s_l*t_h + t_l*ss;
         /* 2/(3log2)*(ss+...) */
         p_h = u + v;
         SET_LOW_WORD(p_h, 0);
         p_l = v - (p_h-u);
         z_h = cp_h*p_h;        /* cp_h+cp_l = 2/(3*log2) */
         z_l = cp_l*p_h+p_l*cp + dp_l[k];
         /* log2(ax) = (ss+..)*2/(3*log2) = n + dp_h + z_h + z_l */
         t = (double)n;
         t1 = ((z_h + z_l) + dp_h[k]) + t;
         SET_LOW_WORD(t1, 0);
         t2 = z_l - (((t1 - t) - dp_h[k]) - z_h);
     }
     /* split up y into y1+y2 and compute (y1+y2)*(t1+t2) */
     y1 = y;
     SET_LOW_WORD(y1, 0);
     p_l = (y-y1)*t1 + y*t2;
     p_h = y1*t1;
     z = p_l + p_h;
     EXTRACT_WORDS(j, i, z);
     if (j >= 0x40900000) {                      /* z >= 1024 */
         if (((j-0x40900000)|i) != 0)        /* if z > 1024 */
             return s*huge*huge;         /* overflow */
         if (p_l + ovt > z - p_h)
             return s*huge*huge;         /* overflow */
     } else if ((j&0x7fffffff) >= 0x4090cc00) {  /* z <= -1075 */  // FIXME: instead of abs(j) use unsigned j
         if (((j-0xc090cc00)|i) != 0)        /* z < -1075 */
             return s*tiny*tiny;         /* underflow */
         if (p_l <= z - p_h)
             return s*tiny*tiny;         /* underflow */
     }
     /*
      * compute 2**(p_h+p_l)
      */
     i = j & 0x7fffffff;
     k = (i>>20) - 0x3ff;
     n = 0;
     if (i > 0x3fe00000) {  /* if |z| > 0.5, set n = [z+0.5] */
         n = j + (0x00100000>>(k+1));
         k = ((n&0x7fffffff)>>20) - 0x3ff;  /* new k for n */
         t = 0.0;
         SET_HIGH_WORD(t, n & ~(0x000fffff>>k));
         n = ((n&0x000fffff)|0x00100000)>>(20-k);
         if (j < 0)
             n = -n;
         p_h -= t;
     }
     t = p_l + p_h;
     SET_LOW_WORD(t, 0);
     u = t*lg2_h;
     v = (p_l-(t-p_h))*lg2 + t*lg2_l;
     z = u + v;
     w = v - (z-u);
     t = z*z;
     t1 = z - t*(P1+t*(P2+t*(P3+t*(P4+t*P5))));
     r = (z*t1)/(t1-2.0) - (w + z*w);
     z = 1.0 - (r-z);
     GET_HIGH_WORD(j, z);
     j += n<<20;
     if ((j>>20) <= 0)  /* subnormal output */
         z = scalbn(z,n);
     else
         SET_HIGH_WORD(z, j);
     return s*z;
 }
References bp, cp, cp_h, cp_l, dp_h, dp_l, EXTRACT_WORDS, fabs(), FORCE_EVAL, GET_HIGH_WORD, huge, i, ivln2, ivln2_h, ivln2_l, j, k, L1, L2, L3, L4, L5, L6, lg2, lg2_h, lg2_l, n, ovt, P1, P2, P3, P4, P5, r, s2, scalbn(), SET_HIGH_WORD, SET_LOW_WORD, sqrt(), t1, t2, tiny, two53, x, y, and y1().
Referenced by cpow(), exp10(), and tgamma().
pow10()
double pow10 (double)
pow10f()
float pow10f (float)
pow10l()
long double pow10l (long double)
powf()
float powf (float x, float y)
Definition at line 48 of file powf.c.
 {
     float z,ax,z_h,z_l,p_h,p_l;
     float y1,t1,t2,r,s,sn,t,u,v,w;
     int32_t i,j,k,yisint,n;
     int32_t hx,hy,ix,iy,is;
     GET_FLOAT_WORD(hx, x);
     GET_FLOAT_WORD(hy, y);
     ix = hx & 0x7fffffff;
     iy = hy & 0x7fffffff;
     /* x**0 = 1, even if x is NaN */
     if (iy == 0)
         return 1.0f;
     /* 1**y = 1, even if y is NaN */
     if (hx == 0x3f800000)
         return 1.0f;
     /* NaN if either arg is NaN */
     if (ix > 0x7f800000 || iy > 0x7f800000)
         return x + y;
     /* determine if y is an odd int when x < 0
      * yisint = 0       ... y is not an integer
      * yisint = 1       ... y is an odd int
      * yisint = 2       ... y is an even int
      */
     yisint  = 0;
     if (hx < 0) {
         if (iy >= 0x4b800000)
             yisint = 2; /* even integer y */
         else if (iy >= 0x3f800000) {
             k = (iy>>23) - 0x7f;         /* exponent */
             j = iy>>(23-k);
             if ((j<<(23-k)) == iy)
                 yisint = 2 - (j & 1);
         }
     }
     /* special value of y */
     if (iy == 0x7f800000) {  /* y is +-inf */
         if (ix == 0x3f800000)      /* (-1)**+-inf is 1 */
             return 1.0f;
         else if (ix > 0x3f800000)  /* (|x|>1)**+-inf = inf,0 */
             return hy >= 0 ? y : 0.0f;
         else                       /* (|x|<1)**+-inf = 0,inf */
             return hy >= 0 ? 0.0f: -y;
     }
     if (iy == 0x3f800000)    /* y is +-1 */
         return hy >= 0 ? x : 1.0f/x;
     if (hy == 0x40000000)    /* y is 2 */
         return x*x;
     if (hy == 0x3f000000) {  /* y is  0.5 */
         if (hx >= 0)     /* x >= +0 */
             return sqrtf(x);
     }
     ax = fabsf(x);
     /* special value of x */
     if (ix == 0x7f800000 || ix == 0 || ix == 0x3f800000) { /* x is +-0,+-inf,+-1 */
         z = ax;
         if (hy < 0)  /* z = (1/|x|) */
             z = 1.0f/z;
         if (hx < 0) {
             if (((ix-0x3f800000)|yisint) == 0) {
                 z = (z-z)/(z-z); /* (-1)**non-int is NaN */
             } else if (yisint == 1)
                 z = -z;          /* (x<0)**odd = -(|x|**odd) */
         }
         return z;
     }
     sn = 1.0f; /* sign of result */
     if (hx < 0) {
         if (yisint == 0) /* (x<0)**(non-int) is NaN */
             return (x-x)/(x-x);
         if (yisint == 1) /* (x<0)**(odd int) */
             sn = -1.0f;
     }
     /* |y| is huge */
     if (iy > 0x4d000000) { /* if |y| > 2**27 */
         /* over/underflow if x is not close to one */
         if (ix < 0x3f7ffff8)
             return hy < 0 ? sn*huge*huge : sn*tiny*tiny;
         if (ix > 0x3f800007)
             return hy > 0 ? sn*huge*huge : sn*tiny*tiny;
         /* now |1-x| is tiny <= 2**-20, suffice to compute
            log(x) by x-x^2/2+x^3/3-x^4/4 */
         t = ax - 1;     /* t has 20 trailing zeros */
         w = (t*t)*(0.5f - t*(0.333333333333f - t*0.25f));
         u = ivln2_h*t;  /* ivln2_h has 16 sig. bits */
         v = t*ivln2_l - w*ivln2;
         t1 = u + v;
         GET_FLOAT_WORD(is, t1);
         SET_FLOAT_WORD(t1, is & 0xfffff000);
         t2 = v - (t1-u);
     } else {
         float s2,s_h,s_l,t_h,t_l;
         n = 0;
         /* take care subnormal number */
         if (ix < 0x00800000) {
             ax *= two24;
             n -= 24;
             GET_FLOAT_WORD(ix, ax);
         }
         n += ((ix)>>23) - 0x7f;
         j = ix & 0x007fffff;
         /* determine interval */
         ix = j | 0x3f800000;     /* normalize ix */
         if (j <= 0x1cc471)       /* |x|<sqrt(3/2) */
             k = 0;
         else if (j < 0x5db3d7)   /* |x|<sqrt(3)   */
             k = 1;
         else {
             k = 0;
             n += 1;
             ix -= 0x00800000;
         }
         SET_FLOAT_WORD(ax, ix);
         /* compute s = s_h+s_l = (x-1)/(x+1) or (x-1.5)/(x+1.5) */
         u = ax - bp[k];   /* bp[0]=1.0, bp[1]=1.5 */
         v = 1.0f/(ax+bp[k]);
         s = u*v;
         s_h = s;
         GET_FLOAT_WORD(is, s_h);
         SET_FLOAT_WORD(s_h, is & 0xfffff000);
         /* t_h=ax+bp[k] High */
         is = ((ix>>1) & 0xfffff000) | 0x20000000;
         SET_FLOAT_WORD(t_h, is + 0x00400000 + (k<<21));
         t_l = ax - (t_h - bp[k]);
         s_l = v*((u - s_h*t_h) - s_h*t_l);
         /* compute log(ax) */
         s2 = s*s;
         r = s2*s2*(L1+s2*(L2+s2*(L3+s2*(L4+s2*(L5+s2*L6)))));
         r += s_l*(s_h+s);
         s2 = s_h*s_h;
         t_h = 3.0f + s2 + r;
         GET_FLOAT_WORD(is, t_h);
         SET_FLOAT_WORD(t_h, is & 0xfffff000);
         t_l = r - ((t_h - 3.0f) - s2);
         /* u+v = s*(1+...) */
         u = s_h*t_h;
         v = s_l*t_h + t_l*s;
         /* 2/(3log2)*(s+...) */
         p_h = u + v;
         GET_FLOAT_WORD(is, p_h);
         SET_FLOAT_WORD(p_h, is & 0xfffff000);
         p_l = v - (p_h - u);
         z_h = cp_h*p_h;  /* cp_h+cp_l = 2/(3*log2) */
         z_l = cp_l*p_h + p_l*cp+dp_l[k];
         /* log2(ax) = (s+..)*2/(3*log2) = n + dp_h + z_h + z_l */
         t = (float)n;
         t1 = (((z_h + z_l) + dp_h[k]) + t);
         GET_FLOAT_WORD(is, t1);
         SET_FLOAT_WORD(t1, is & 0xfffff000);
         t2 = z_l - (((t1 - t) - dp_h[k]) - z_h);
     }
     /* split up y into y1+y2 and compute (y1+y2)*(t1+t2) */
     GET_FLOAT_WORD(is, y);
     SET_FLOAT_WORD(y1, is & 0xfffff000);
     p_l = (y-y1)*t1 + y*t2;
     p_h = y1*t1;
     z = p_l + p_h;
     GET_FLOAT_WORD(j, z);
     if (j > 0x43000000)          /* if z > 128 */
         return sn*huge*huge;  /* overflow */
     else if (j == 0x43000000) {  /* if z == 128 */
         if (p_l + ovt > z - p_h)
             return sn*huge*huge;  /* overflow */
     } else if ((j&0x7fffffff) > 0x43160000)  /* z < -150 */ // FIXME: check should be  (uint32_t)j > 0xc3160000
         return sn*tiny*tiny;  /* underflow */
     else if (j == 0xc3160000) {  /* z == -150 */
         if (p_l <= z-p_h)
             return sn*tiny*tiny;  /* underflow */
     }
     /*
      * compute 2**(p_h+p_l)
      */
     i = j & 0x7fffffff;
     k = (i>>23) - 0x7f;
     n = 0;
     if (i > 0x3f000000) {   /* if |z| > 0.5, set n = [z+0.5] */
         n = j + (0x00800000>>(k+1));
         k = ((n&0x7fffffff)>>23) - 0x7f;  /* new k for n */
         SET_FLOAT_WORD(t, n & ~(0x007fffff>>k));
         n = ((n&0x007fffff)|0x00800000)>>(23-k);
         if (j < 0)
             n = -n;
         p_h -= t;
     }
     t = p_l + p_h;
     GET_FLOAT_WORD(is, t);
     SET_FLOAT_WORD(t, is & 0xffff8000);
     u = t*lg2_h;
     v = (p_l-(t-p_h))*lg2 + t*lg2_l;
     z = u + v;
     w = v - (z - u);
     t = z*z;
     t1 = z - t*(P1+t*(P2+t*(P3+t*(P4+t*P5))));
     r = (z*t1)/(t1-2.0f) - (w+z*w);
     z = 1.0f - (r - z);
     GET_FLOAT_WORD(j, z);
     j += n<<23;
     if ((j>>23) <= 0)  /* subnormal output */
         z = scalbnf(z, n);
     else
         SET_FLOAT_WORD(z, j);
     return sn*z;
 }
References bp, cp, cp_h, cp_l, dp_h, dp_l, fabsf(), GET_FLOAT_WORD, huge, i, ivln2, ivln2_h, ivln2_l, j, k, L1, L2, L3, L4, L5, L6, lg2, lg2_h, lg2_l, n, ovt, P1, P2, P3, P4, P5, r, s2, scalbnf(), SET_FLOAT_WORD, sqrtf(), t1, t2, tiny, two24, x, y, and y1().
Referenced by cpowf().
powl()
long double powl (long double x, long double y)
remainder()
double remainder (double x, double y)
Definition at line 5 of file remainder.c.
 {
     int q;
     return remquo(x, y, &q);
 }
References remquo(), x, and y.
remainderf()
float remainderf (float x, float y)
Definition at line 5 of file remainderf.c.
 {
     int q;
     return remquof(x, y, &q);
 }
References remquof(), x, and y.
remainderl()
long double remainderl (long double x, long double y)
Definition at line 10 of file remainderl.c.
 {
     int q;
     return remquol(x, y, &q);
 }
References remquol(), x, and y.
remquo()
double remquo (double x, double y, int * quotient)
Definition at line 4 of file remquo.c.
 {
     union {double f; uint64_t i;} ux = {x}, uy = {y};
     int ex = ux.i>>52 & 0x7ff;
     int ey = uy.i>>52 & 0x7ff;
     int sx = ux.i>>63;
     int sy = uy.i>>63;
     uint32_t q;
     uint64_t i;
     uint64_t uxi = ux.i;
     *quo = 0;
     if (uy.i<<1 == 0 || isnan(y) || ex == 0x7ff)
         return (x*y)/(x*y);
     if (ux.i<<1 == 0)
         return x;
     /* normalize x and y */
     if (!ex) {
         for (i = uxi<<12; i>>63 == 0; ex--, i <<= 1);
         uxi <<= -ex + 1;
     } else {
         uxi &= -1ULL >> 12;
         uxi |= 1ULL << 52;
     }
     if (!ey) {
         for (i = uy.i<<12; i>>63 == 0; ey--, i <<= 1);
         uy.i <<= -ey + 1;
     } else {
         uy.i &= -1ULL >> 12;
         uy.i |= 1ULL << 52;
     }
     q = 0;
     if (ex < ey) {
         if (ex+1 == ey)
             goto end;
         return x;
     }
     /* x mod y */
     for (; ex > ey; ex--) {
         i = uxi - uy.i;
         if (i >> 63 == 0) {
             uxi = i;
             q++;
         }
         uxi <<= 1;
         q <<= 1;
     }
     i = uxi - uy.i;
     if (i >> 63 == 0) {
         uxi = i;
         q++;
     }
     if (uxi == 0)
         ex = -60;
     else
         for (; uxi>>52 == 0; uxi <<= 1, ex--);
 end:
     /* scale result and decide between |x| and |x|-|y| */
     if (ex > 0) {
         uxi -= 1ULL << 52;
         uxi |= (uint64_t)ex << 52;
     } else {
         uxi >>= -ex + 1;
     }
     ux.i = uxi;
     x = ux.f;
     if (sy)
         y = -y;
     if (ex == ey || (ex+1 == ey && (2*x > y || (2*x == y && q%2)))) {
         x -= y;
         q++;
     }
     q &= 0x7fffffff;
     *quo = sx^sy ? -(int)q : (int)q;
     return sx ? -x : x;
 }
References i, int, isnan, x, and y.
Referenced by remainder().
remquof()
float remquof (float x, float y, int * quotient)
Definition at line 4 of file remquof.c.
 {
     union {float f; uint32_t i;} ux = {x}, uy = {y};
     int ex = ux.i>>23 & 0xff;
     int ey = uy.i>>23 & 0xff;
     int sx = ux.i>>31;
     int sy = uy.i>>31;
     uint32_t q;
     uint32_t i;
     uint32_t uxi = ux.i;
     *quo = 0;
     if (uy.i<<1 == 0 || isnan(y) || ex == 0xff)
         return (x*y)/(x*y);
     if (ux.i<<1 == 0)
         return x;
     /* normalize x and y */
     if (!ex) {
         for (i = uxi<<9; i>>31 == 0; ex--, i <<= 1);
         uxi <<= -ex + 1;
     } else {
         uxi &= -1U >> 9;
         uxi |= 1U << 23;
     }
     if (!ey) {
         for (i = uy.i<<9; i>>31 == 0; ey--, i <<= 1);
         uy.i <<= -ey + 1;
     } else {
         uy.i &= -1U >> 9;
         uy.i |= 1U << 23;
     }
     q = 0;
     if (ex < ey) {
         if (ex+1 == ey)
             goto end;
         return x;
     }
     /* x mod y */
     for (; ex > ey; ex--) {
         i = uxi - uy.i;
         if (i >> 31 == 0) {
             uxi = i;
             q++;
         }
         uxi <<= 1;
         q <<= 1;
     }
     i = uxi - uy.i;
     if (i >> 31 == 0) {
         uxi = i;
         q++;
     }
     if (uxi == 0)
         ex = -30;
     else
         for (; uxi>>23 == 0; uxi <<= 1, ex--);
 end:
     /* scale result and decide between |x| and |x|-|y| */
     if (ex > 0) {
         uxi -= 1U << 23;
         uxi |= (uint32_t)ex << 23;
     } else {
         uxi >>= -ex + 1;
     }
     ux.i = uxi;
     x = ux.f;
     if (sy)
         y = -y;
     if (ex == ey || (ex+1 == ey && (2*x > y || (2*x == y && q%2)))) {
         x -= y;
         q++;
     }
     q &= 0x7fffffff;
     *quo = sx^sy ? -(int)q : (int)q;
     return sx ? -x : x;
 }
References i, int, isnan, x, and y.
Referenced by remainderf().
remquol()
long double remquol (long double x, long double y, int * quotient)
Referenced by remainderl().
rint()
double rint (double x)
Definition at line 12 of file rint.c.
 {
     union {double f; uint64_t i;} u = {x};
     int e = u.i>>52 & 0x7ff;
     int s = u.i>>63;
     double_t y;
     if (e >= 0x3ff+52)
         return x;
     if (s)
         y = x - toint + toint;
     else
         y = x + toint - toint;
     if (y == 0)
         return s ? -0.0 : 0;
     return y;
 }
References i, toint, x, and y.
Referenced by llrint(), lrint(), nearbyint(), and scalb().
rintf()
float rintf (float x)
Definition at line 14 of file rintf.c.
 {
     union {float f; uint32_t i;} u = {x};
     int e = u.i>>23 & 0xff;
     int s = u.i>>31;
     float_t y;
     if (e >= 0x7f+23)
         return x;
     if (s)
         y = x - toint + toint;
     else
         y = x + toint - toint;
     if (y == 0)
         return s ? -0.0f : 0.0f;
     return y;
 }
References i, toint, x, and y.
Referenced by llrintf(), lrintf(), nearbyintf(), and scalbf().
rintl()
long double rintl (long double x)
Referenced by llrintl(), lrintl(), and nearbyintl().
round()
double round (double x)
Definition at line 10 of file round.c.
 {
     union {double f; uint64_t i;} u = {x};
     int e = u.i >> 52 & 0x7ff;
     double_t y;
     if (e >= 0x3ff+52)
         return x;
     if (u.i >> 63)
         x = -x;
     if (e < 0x3ff-1) {
         /* raise inexact if x!=0 */
         FORCE_EVAL(x + toint);
         return 0*u.f;
     }
     y = x + toint - toint - x;
     if (y > 0.5)
         y = y + x - 1;
     else if (y <= -0.5)
         y = y + x + 1;
     else
         y = y + x;
     if (u.i >> 63)
         y = -y;
     return y;
 }
References FORCE_EVAL, i, toint, x, and y.
Referenced by llround(), and lround().
roundf()
float roundf (float x)
Definition at line 12 of file roundf.c.
 {
     union {float f; uint32_t i;} u = {x};
     int e = u.i >> 23 & 0xff;
     float_t y;
     if (e >= 0x7f+23)
         return x;
     if (u.i >> 31)
         x = -x;
     if (e < 0x7f-1) {
         FORCE_EVAL(x + toint);
         return 0*u.f;
     }
     y = x + toint - toint - x;
     if (y > 0.5f)
         y = y + x - 1;
     else if (y <= -0.5f)
         y = y + x + 1;
     else
         y = y + x;
     if (u.i >> 31)
         y = -y;
     return y;
 }
References FORCE_EVAL, i, toint, x, and y.
Referenced by llroundf(), and lroundf().
roundl()
long double roundl (long double x)
Referenced by llroundl(), and lroundl().
scalbln()
double scalbln (double x, long power)
Definition at line 5 of file scalbln.c.
 {
     if (n > INT_MAX)
         n = INT_MAX;
     else if (n < INT_MIN)
         n = INT_MIN;
     return scalbn(x, n);
 }
References INT_MAX, INT_MIN, n, scalbn(), and x.
scalblnf()
float scalblnf (float x, long power)
Definition at line 5 of file scalblnf.c.
 {
     if (n > INT_MAX)
         n = INT_MAX;
     else if (n < INT_MIN)
         n = INT_MIN;
     return scalbnf(x, n);
 }
References INT_MAX, INT_MIN, n, scalbnf(), and x.
scalblnl()
long double scalblnl (long double x, long power)
Definition at line 12 of file scalblnl.c.
 {
     if (n > INT_MAX)
         n = INT_MAX;
     else if (n < INT_MIN)
         n = INT_MIN;
     return scalbnl(x, n);
 }
References INT_MAX, INT_MIN, n, scalbnl(), and x.
scalbn()
double scalbn (double x, int power)
Definition at line 4 of file scalbn.c.
 {
     union {double f; uint64_t i;} u;
     double_t y = x;
     if (n > 1023) {
         y *= 0x1p1023;
         n -= 1023;
         if (n > 1023) {
             y *= 0x1p1023;
             n -= 1023;
             if (n > 1023)
                 n = 1023;
         }
     } else if (n < -1022) {
         /* make sure final n < -53 to avoid double
            rounding in the subnormal range */
         y *= 0x1p-1022 * 0x1p53;
         n += 1022 - 53;
         if (n < -1022) {
             y *= 0x1p-1022 * 0x1p53;
             n += 1022 - 53;
             if (n < -1022)
                 n = -1022;
         }
     }
     u.i = (uint64_t)(0x3ff+n)<<52;
     x = y * u.f;
     return x;
 }
References i, n, x, and y.
Referenced by __rem_pio2_large(), exp(), exp2(), fma(), ldexp(), pow(), scalb(), scalbln(), and significand().
scalbnf()
float scalbnf (float x, int power)
Definition at line 4 of file scalbnf.c.
 {
     union {float f; uint32_t i;} u;
     float_t y = x;
     if (n > 127) {
         y *= 0x1p127f;
         n -= 127;
         if (n > 127) {
             y *= 0x1p127f;
             n -= 127;
             if (n > 127)
                 n = 127;
         }
     } else if (n < -126) {
         y *= 0x1p-126f * 0x1p24f;
         n += 126 - 24;
         if (n < -126) {
             y *= 0x1p-126f * 0x1p24f;
             n += 126 - 24;
             if (n < -126)
                 n = -126;
         }
     }
     u.i = (uint32_t)(0x7f+n)<<23;
     x = y * u.f;
     return x;
 }
References i, n, x, and y.
Referenced by expf(), ldexpf(), powf(), scalbf(), scalblnf(), and significandf().
scalbnl()
long double scalbnl (long double x, int power)
Referenced by ldexpl(), and scalblnl().
sin()
double sin (double x)
Definition at line 45 of file sin.c.
 {
     double y[2];
     uint32_t ix;
     unsigned n;
     /* High word of x. */
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     /* |x| ~< pi/4 */
     if (ix <= 0x3fe921fb) {
         if (ix < 0x3e500000) {  /* |x| < 2**-26 */
             /* raise inexact if x != 0 and underflow if subnormal*/
             FORCE_EVAL(ix < 0x00100000 ? x/0x1p120f : x+0x1p120f);
             return x;
         }
         return __sin(x, 0.0, 0);
     }
     /* sin(Inf or NaN) is NaN */
     if (ix >= 0x7ff00000)
         return x - x;
     /* argument reduction needed */
     n = __rem_pio2(x, y);
     switch (n&3) {
     case 0: return  __sin(y[0], y[1], 1);
     case 1: return  __cos(y[0], y[1]);
     case 2: return -__sin(y[0], y[1], 1);
     default:
         return -__cos(y[0], y[1]);
     }
 }
References __cos(), __rem_pio2(), __sin(), FORCE_EVAL, GET_HIGH_WORD, n, x, and y.
Referenced by ccos(), ccosh(), cexp(), common(), cpow(), csin(), csinh(), ctan(), ctanh(), jn(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), R_InitTables(), sincos(), sincosf(), and yn().
sincos()
void sincos (double x, double * sin, double * cos)
Definition at line 16 of file sincos.c.
 {
     double y[2], s, c;
     uint32_t ix;
     unsigned n;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     /* |x| ~< pi/4 */
     if (ix <= 0x3fe921fb) {
         /* if |x| < 2**-27 * sqrt(2) */
         if (ix < 0x3e46a09e) {
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00100000 ? x/0x1p120f : x+0x1p120f);
             *sin = x;
             *cos = 1.0;
             return;
         }
         *sin = __sin(x, 0.0, 0);
         *cos = __cos(x, 0.0);
         return;
     }
     /* sincos(Inf or NaN) is NaN */
     if (ix >= 0x7ff00000) {
         *sin = *cos = x - x;
         return;
     }
     /* argument reduction needed */
     n = __rem_pio2(x, y);
     s = __sin(y[0], y[1], 1);
     c = __cos(y[0], y[1]);
     switch (n&3) {
     case 0:
         *sin = s;
         *cos = c;
         break;
     case 1:
         *sin = c;
         *cos = -s;
         break;
     case 2:
         *sin = -s;
         *cos = -c;
         break;
     case 3:
     default:
         *sin = -c;
         *cos = s;
         break;
     }
 }
References __cos(), __rem_pio2(), __sin(), c, cos(), FORCE_EVAL, GET_HIGH_WORD, n, sin(), x, and y.
sincosf()
void sincosf (float x, float * sin, float * cos)
Definition at line 27 of file sincosf.c.
 {
     double y;
     float_t s, c;
     uint32_t ix;
     unsigned n, sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     /* |x| ~<= pi/4 */
     if (ix <= 0x3f490fda) {
         /* |x| < 2**-12 */
         if (ix < 0x39800000) {
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00100000 ? x/0x1p120f : x+0x1p120f);
             *sin = x;
             *cos = 1.0f;
             return;
         }
         *sin = __sindf(x);
         *cos = __cosdf(x);
         return;
     }
     /* |x| ~<= 5*pi/4 */
     if (ix <= 0x407b53d1) {
         if (ix <= 0x4016cbe3) {  /* |x| ~<= 3pi/4 */
             if (sign) {
                 *sin = -__cosdf(x + s1pio2);
                 *cos = __sindf(x + s1pio2);
             } else {
                 *sin = __cosdf(s1pio2 - x);
                 *cos = __sindf(s1pio2 - x);
             }
             return;
         }
         /* -sin(x+c) is not correct if x+c could be 0: -0 vs +0 */
         *sin = -__sindf(sign ? x + s2pio2 : x - s2pio2);
         *cos = -__cosdf(sign ? x + s2pio2 : x - s2pio2);
         return;
     }
     /* |x| ~<= 9*pi/4 */
     if (ix <= 0x40e231d5) {
         if (ix <= 0x40afeddf) {  /* |x| ~<= 7*pi/4 */
             if (sign) {
                 *sin = __cosdf(x + s3pio2);
                 *cos = -__sindf(x + s3pio2);
             } else {
                 *sin = -__cosdf(x - s3pio2);
                 *cos = __sindf(x - s3pio2);
             }
             return;
         }
         *sin = __sindf(sign ? x + s4pio2 : x - s4pio2);
         *cos = __cosdf(sign ? x + s4pio2 : x - s4pio2);
         return;
     }
     /* sin(Inf or NaN) is NaN */
     if (ix >= 0x7f800000) {
         *sin = *cos = x - x;
         return;
     }
     /* general argument reduction needed */
     n = __rem_pio2f(x, &y);
     s = __sindf(y);
     c = __cosdf(y);
     switch (n&3) {
     case 0:
         *sin = s;
         *cos = c;
         break;
     case 1:
         *sin = c;
         *cos = -s;
         break;
     case 2:
         *sin = -s;
         *cos = -c;
         break;
     case 3:
     default:
         *sin = -c;
         *cos = s;
         break;
     }
 }
References __cosdf(), __rem_pio2f(), __sindf(), c, cos(), FORCE_EVAL, GET_FLOAT_WORD, n, s1pio2, s2pio2, s3pio2, s4pio2, sin(), x, and y.
sincosl()
void sincosl (long double , long double * , long double *)
sinf()
float sinf (float x)
Definition at line 26 of file sinf.c.
 {
     double y;
     uint32_t ix;
     int n, sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     if (ix <= 0x3f490fda) {  /* |x| ~<= pi/4 */
         if (ix < 0x39800000) {  /* |x| < 2**-12 */
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00800000 ? x/0x1p120f : x+0x1p120f);
             return x;
         }
         return __sindf(x);
     }
     if (ix <= 0x407b53d1) {  /* |x| ~<= 5*pi/4 */
         if (ix <= 0x4016cbe3) {  /* |x| ~<= 3pi/4 */
             if (sign)
                 return -__cosdf(x + s1pio2);
             else
                 return __cosdf(x - s1pio2);
         }
         return __sindf(sign ? -(x + s2pio2) : -(x - s2pio2));
     }
     if (ix <= 0x40e231d5) {  /* |x| ~<= 9*pi/4 */
         if (ix <= 0x40afeddf) {  /* |x| ~<= 7*pi/4 */
             if (sign)
                 return __cosdf(x + s3pio2);
             else
                 return -__cosdf(x - s3pio2);
         }
         return __sindf(sign ? x + s4pio2 : x - s4pio2);
     }
     /* sin(Inf or NaN) is NaN */
     if (ix >= 0x7f800000)
         return x - x;
     /* general argument reduction needed */
     n = __rem_pio2f(x, &y);
     switch (n&3) {
     case 0: return  __sindf(y);
     case 1: return  __cosdf(y);
     case 2: return  __sindf(-y);
     default:
         return -__cosdf(y);
     }
 }
References __cosdf(), __rem_pio2f(), __sindf(), FORCE_EVAL, GET_FLOAT_WORD, n, s1pio2, s2pio2, s3pio2, s4pio2, x, and y.
Referenced by ccosf(), ccoshf(), cexpf(), common(), cpowf(), csinf(), csinhf(), ctanf(), and ctanhf().
sinh()
double sinh (double x)
Definition at line 7 of file sinh.c.
 {
     union {double f; uint64_t i;} u = {.f = x};
     uint32_t w;
     double t, h, absx;
     h = 0.5;
     if (u.i >> 63)
         h = -h;
     /* |x| */
     u.i &= (uint64_t)-1/2;
     absx = u.f;
     w = u.i >> 32;
     /* |x| < log(DBL_MAX) */
     if (w < 0x40862e42) {
         t = expm1(absx);
         if (w < 0x3ff00000) {
             if (w < 0x3ff00000 - (26<<20))
                 /* note: inexact and underflow are raised by expm1 */
                 /* note: this branch avoids spurious underflow */
                 return x;
             return h*(2*t - t*t/(t+1));
         }
         /* note: |x|>log(0x1p26)+eps could be just h*exp(x) */
         return h*(t + t/(t+1));
     }
     /* |x| > log(DBL_MAX) or nan */
     /* note: the result is stored to handle overflow */
     t = 2*h*__expo2(absx);
     return t;
 }
References __expo2(), expm1(), i, and x.
Referenced by __mlibc_cchsh(), ccosh(), csinh(), ctan(), and ctanh().
sinhf()
float sinhf (float x)
Definition at line 3 of file sinhf.c.
 {
     union {float f; uint32_t i;} u = {.f = x};
     uint32_t w;
     float t, h, absx;
     h = 0.5;
     if (u.i >> 31)
         h = -h;
     /* |x| */
     u.i &= 0x7fffffff;
     absx = u.f;
     w = u.i;
     /* |x| < log(FLT_MAX) */
     if (w < 0x42b17217) {
         t = expm1f(absx);
         if (w < 0x3f800000) {
             if (w < 0x3f800000 - (12<<23))
                 return x;
             return h*(2*t - t*t/(t+1));
         }
         return h*(t + t/(t+1));
     }
     /* |x| > logf(FLT_MAX) or nan */
     t = 2*h*__expo2f(absx);
     return t;
 }
References __expo2f(), expm1f(), i, and x.
Referenced by __mlibc_cchshf(), ccoshf(), csinhf(), ctanf(), and ctanhf().
sinhl()
long double sinhl (long double x)
sinl()
long double sinl (long double x)
sqrt()
double sqrt (double x)
Definition at line 83 of file sqrt.c.
 {
     double z;
     int32_t sign = (int)0x80000000;
     int32_t ix0,s0,q,m,t,i;
     uint32_t r,t1,s1,ix1,q1;
     EXTRACT_WORDS(ix0, ix1, x);
     /* take care of Inf and NaN */
     if ((ix0&0x7ff00000) == 0x7ff00000) {
         return x*x + x;  /* sqrt(NaN)=NaN, sqrt(+inf)=+inf, sqrt(-inf)=sNaN */
     }
     /* take care of zero */
     if (ix0 <= 0) {
         if (((ix0&~sign)|ix1) == 0)
             return x;  /* sqrt(+-0) = +-0 */
         if (ix0 < 0)
             return (x-x)/(x-x);  /* sqrt(-ve) = sNaN */
     }
     /* normalize x */
     m = ix0>>20;
     if (m == 0) {  /* subnormal x */
         while (ix0 == 0) {
             m -= 21;
             ix0 |= (ix1>>11);
             ix1 <<= 21;
         }
         for (i=0; (ix0&0x00100000) == 0; i++)
             ix0<<=1;
         m -= i - 1;
         ix0 |= ix1>>(32-i);
         ix1 <<= i;
     }
     m -= 1023;    /* unbias exponent */
     ix0 = (ix0&0x000fffff)|0x00100000;
     if (m & 1) {  /* odd m, double x to make it even */
         ix0 += ix0 + ((ix1&sign)>>31);
         ix1 += ix1;
     }
     m >>= 1;      /* m = [m/2] */
     /* generate sqrt(x) bit by bit */
     ix0 += ix0 + ((ix1&sign)>>31);
     ix1 += ix1;
     q = q1 = s0 = s1 = 0;  /* [q,q1] = sqrt(x) */
     r = 0x00200000;        /* r = moving bit from right to left */
     while (r != 0) {
         t = s0 + r;
         if (t <= ix0) {
             s0   = t + r;
             ix0 -= t;
             q   += r;
         }
         ix0 += ix0 + ((ix1&sign)>>31);
         ix1 += ix1;
         r >>= 1;
     }
     r = sign;
     while (r != 0) {
         t1 = s1 + r;
         t  = s0;
         if (t < ix0 || (t == ix0 && t1 <= ix1)) {
             s1 = t1 + r;
             if ((t1&sign) == sign && (s1&sign) == 0)
                 s0++;
             ix0 -= t;
             if (ix1 < t1)
                 ix0--;
             ix1 -= t1;
             q1 += r;
         }
         ix0 += ix0 + ((ix1&sign)>>31);
         ix1 += ix1;
         r >>= 1;
     }
     /* use floating add to find out rounding direction */
     if ((ix0|ix1) != 0) {
         z = 1.0 - tiny; /* raise inexact flag */
         if (z >= 1.0) {
             z = 1.0 + tiny;
             if (q1 == (uint32_t)0xffffffff) {
                 q1 = 0;
                 q++;
             } else if (z > 1.0) {
                 if (q1 == (uint32_t)0xfffffffe)
                     q++;
                 q1 += 2;
             } else
                 q1 += q1 & 1;
         }
     }
     ix0 = (q>>1) + 0x3fe00000;
     ix1 = q1>>1;
     if (q&1)
         ix1 |= sign;
     ix0 += m << 20;
     INSERT_WORDS(z, ix0, ix1);
     return z;
 }
References EXTRACT_WORDS, i, INSERT_WORDS, int, r, s0, s1, t1, tiny, and x.
Referenced by acos(), acosh(), asin(), asinf(), asinh(), common(), csqrt(), hypot(), jn(), pow(), sqrtl(), and yn().
sqrtf()
float sqrtf (float x)
Definition at line 334 of file Convert.cpp.
 {
     if (x < 0.0f)
         return NAN;
     if (x < 1e-7f)
         return 0.0f;
     float guess = x / 2.0f;
     for (short i = 0; i < 10; i++)
     {
         if (guess == 0.0f)
             return 0.0f;
         guess = (guess + x / guess) / 2.0f;
     }
     return guess;
 }
References GET_FLOAT_WORD, i, int, r, SET_FLOAT_WORD, tiny, and x.
sqrtl()
long double sqrtl (long double x)
Definition at line 3 of file sqrtl.c.
 {
     /* FIXME: implement in C, this is for LDBL_MANT_DIG == 64 only */
     return sqrt(x);
 }
References sqrt(), and x.
tan()
double tan (double x)
Definition at line 44 of file tan.c.
 {
     double y[2];
     uint32_t ix;
     unsigned n;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     /* |x| ~< pi/4 */
     if (ix <= 0x3fe921fb) {
         if (ix < 0x3e400000) { /* |x| < 2**-27 */
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00100000 ? x/0x1p120f : x+0x1p120f);
             return x;
         }
         return __tan(x, 0.0, 0);
     }
     /* tan(Inf or NaN) is NaN */
     if (ix >= 0x7ff00000)
         return x - x;
     /* argument reduction */
     n = __rem_pio2(x, y);
     return __tan(y[0], y[1], n&1);
 }
References __rem_pio2(), __tan(), FORCE_EVAL, GET_HIGH_WORD, n, x, and y.
Referenced by R_InitTables().
tanf()
float tanf (float x)
Definition at line 26 of file tanf.c.
 {
     double y;
     uint32_t ix;
     unsigned n, sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     if (ix <= 0x3f490fda) {  /* |x| ~<= pi/4 */
         if (ix < 0x39800000) {  /* |x| < 2**-12 */
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00800000 ? x/0x1p120f : x+0x1p120f);
             return x;
         }
         return __tandf(x, 0);
     }
     if (ix <= 0x407b53d1) {  /* |x| ~<= 5*pi/4 */
         if (ix <= 0x4016cbe3)  /* |x| ~<= 3pi/4 */
             return __tandf((sign ? x+t1pio2 : x-t1pio2), 1);
         else
             return __tandf((sign ? x+t2pio2 : x-t2pio2), 0);
     }
     if (ix <= 0x40e231d5) {  /* |x| ~<= 9*pi/4 */
         if (ix <= 0x40afeddf)  /* |x| ~<= 7*pi/4 */
             return __tandf((sign ? x+t3pio2 : x-t3pio2), 1);
         else
             return __tandf((sign ? x+t4pio2 : x-t4pio2), 0);
     }
     /* tan(Inf or NaN) is NaN */
     if (ix >= 0x7f800000)
         return x - x;
     /* argument reduction */
     n = __rem_pio2f(x, &y);
     return __tandf(y, n&1);
 }
References __rem_pio2f(), __tandf(), FORCE_EVAL, GET_FLOAT_WORD, n, t1pio2, t2pio2, t3pio2, t4pio2, x, and y.
tanh()
double tanh (double x)
Definition at line 7 of file tanh.c.
 {
     union {double f; uint64_t i;} u = {.f = x};
     uint32_t w;
     int sign;
     double_t t;
     /* x = |x| */
     sign = u.i >> 63;
     u.i &= (uint64_t)-1/2;
     x = u.f;
     w = u.i >> 32;
     if (w > 0x3fe193ea) {
         /* |x| > log(3)/2 ~= 0.5493 or nan */
         if (w > 0x40340000) {
             /* |x| > 20 or nan */
             /* note: this branch avoids raising overflow */
             t = 1 - 0/x;
         } else {
             t = expm1(2*x);
             t = 1 - 2/(t+2);
         }
     } else if (w > 0x3fd058ae) {
         /* |x| > log(5/3)/2 ~= 0.2554 */
         t = expm1(2*x);
         t = t/(t+2);
     } else if (w >= 0x00100000) {
         /* |x| >= 0x1p-1022, up to 2ulp error in [0.1,0.2554] */
         t = expm1(-2*x);
         t = -t/(t+2);
     } else {
         /* |x| is subnormal */
         /* note: the branch above would not raise underflow in [0x1p-1023,0x1p-1022) */
         FORCE_EVAL((float)x);
         t = x;
     }
     return sign ? -t : t;
 }
References expm1(), FORCE_EVAL, i, and x.
tanhf()
float tanhf (float x)
Definition at line 3 of file tanhf.c.
 {
     union {float f; uint32_t i;} u = {.f = x};
     uint32_t w;
     int sign;
     float t;
     /* x = |x| */
     sign = u.i >> 31;
     u.i &= 0x7fffffff;
     x = u.f;
     w = u.i;
     if (w > 0x3f0c9f54) {
         /* |x| > log(3)/2 ~= 0.5493 or nan */
         if (w > 0x41200000) {
             /* |x| > 10 */
             t = 1 + 0/x;
         } else {
             t = expm1f(2*x);
             t = 1 - 2/(t+2);
         }
     } else if (w > 0x3e82c578) {
         /* |x| > log(5/3)/2 ~= 0.2554 */
         t = expm1f(2*x);
         t = t/(t+2);
     } else if (w >= 0x00800000) {
         /* |x| >= 0x1p-126 */
         t = expm1f(-2*x);
         t = -t/(t+2);
     } else {
         /* |x| is subnormal */
         FORCE_EVAL(x*x);
         t = x;
     }
     return sign ? -t : t;
 }
References expm1f(), FORCE_EVAL, i, and x.
tanhl()
long double tanhl (long double x)
tanl()
long double tanl (long double x)
tgamma()
double tgamma (double x)
Definition at line 108 of file tgamma.c.
 {
     union {double f; uint64_t i;} u = {x};
     double absx, y;
     double_t dy, z, r;
     uint32_t ix = u.i>>32 & 0x7fffffff;
     int sign = u.i>>63;
     /* special cases */
     if (ix >= 0x7ff00000)
         /* tgamma(nan)=nan, tgamma(inf)=inf, tgamma(-inf)=nan with invalid */
         return x + INFINITY;
     if (ix < (0x3ff-54)<<20)
         /* |x| < 2^-54: tgamma(x) ~ 1/x, +-0 raises div-by-zero */
         return 1/x;
     /* integer arguments */
     /* raise inexact when non-integer */
     if (x == floor(x)) {
         if (sign)
             return 0/0.0;
         if (x <= sizeof fact/sizeof *fact)
             return fact[(int)x - 1];
     }
     /* x >= 172: tgamma(x)=inf with overflow */
     /* x =< -184: tgamma(x)=+-0 with underflow */
     if (ix >= 0x40670000) { /* |x| >= 184 */
         if (sign) {
             FORCE_EVAL((float)(0x1p-126/x));
             if (floor(x) * 0.5 == floor(x * 0.5))
                 return 0;
             return -0.0;
         }
         x *= 0x1p1023;
         return x;
     }
     absx = sign ? -x : x;
     /* handle the error of x + g - 0.5 */
     y = absx + gmhalf;
     if (absx > gmhalf) {
         dy = y - absx;
         dy -= gmhalf;
     } else {
         dy = y - gmhalf;
         dy -= absx;
     }
     z = absx - 0.5;
     r = S(absx) * exp(-y);
     if (x < 0) {
         /* reflection formula for negative x */
         /* sinpi(absx) is not 0, integers are already handled */
         r = -pi / (sinpi(absx) * absx * r);
         dy = -dy;
         z = -z;
     }
     r += dy * (gmhalf+0.5) * r / y;
     z = pow(y, 0.5*z);
     y = r * z * z;
     return y;
 }
References exp(), fact, floor(), FORCE_EVAL, gmhalf, i, INFINITY, int, pi, pow(), r, S(), sinpi(), x, and y.
Referenced by tgammaf().
tgammaf()
float tgammaf (float x)
Definition at line 3 of file tgammaf.c.
 {
     return tgamma(x);
 }
References tgamma(), and x.
tgammal()
long double tgammal (long double x)
trunc()
double trunc (double x)
Definition at line 3 of file trunc.c.
 {
     union {double f; uint64_t i;} u = {x};
     int e = (int)(u.i >> 52 & 0x7ff) - 0x3ff + 12;
     uint64_t m;
     if (e >= 52 + 12)
         return x;
     if (e < 12)
         e = 1;
     m = -1ULL >> e;
     if ((u.i & m) == 0)
         return x;
     FORCE_EVAL(x + 0x1p120f);
     u.i &= ~m;
     return u.f;
 }
References FORCE_EVAL, i, int, and x.
truncf()
float truncf (float x)
Definition at line 3 of file truncf.c.
 {
     union {float f; uint32_t i;} u = {x};
     int e = (int)(u.i >> 23 & 0xff) - 0x7f + 9;
     uint32_t m;
     if (e >= 23 + 9)
         return x;
     if (e < 9)
         e = 1;
     m = -1U >> e;
     if ((u.i & m) == 0)
         return x;
     FORCE_EVAL(x + 0x1p120f);
     u.i &= ~m;
     return u.f;
 }
References FORCE_EVAL, i, int, and x.
truncl()
long double truncl (long double x)