Fennix Userspace: Userspace/apps/base/bash/lib/readline/xmalloc.h File Reference
xmalloc.h File Reference
#include <readline/rlstdc.h>
Macros
#define PTR_T char *
Functions
PTR_T xmalloc (size_t)
PTR_T xrealloc (void *, size_t)
void xfree (void *)
Macro Definition Documentation
PTR_T
#define PTR_T char *
Definition at line 36 of file xmalloc.h.
Function Documentation
xfree()
void xfree (void *)
xmalloc()
PTR_T xmalloc (size_t bytes)
Definition at line 63 of file xmalloc.c.
 {
   PTR_T temp;
   temp = malloc (bytes);
   if (temp == 0)
     memory_error_and_abort ("xmalloc");
   return (temp);
 }
References allocerr(), exit(), EXIT_FAILURE, FINDBRK, fprintf(), internal_warning(), malloc, memory_error_and_abort(), PTR_T, ret, size, and stderr.
Referenced by next_row(), scan_format(), scan_request(), and scan_table().
xrealloc()
PTR_T xrealloc (void * , size_t)