Fennix: Userspace/musl/include/getopt.h File Reference
getopt.h File Reference
Data Structures
struct option
Macros
#define no_argument 0
#define required_argument 1
#define optional_argument 2
Functions
int getopt (int, char *const [], const char *)
int getopt_long (int, char *const *, const char *, const struct option *, int *)
int getopt_long_only (int, char *const *, const char *, const struct option *, int *)
Variables
char * optarg
int optind
int opterr
int optopt
int optreset
Data Structure Documentation
option
struct option
Definition at line 12 of file getopt.h.
Data Fields
int * flag
int has_arg
const char * name
int val
Macro Definition Documentation
no_argument
#define no_argument 0
Definition at line 22 of file getopt.h.
optional_argument
#define optional_argument 2
Definition at line 24 of file getopt.h.
required_argument
#define required_argument 1
Definition at line 23 of file getopt.h.
Function Documentation
getopt()
int getopt (int argc, char * const argv[], const char * optstring)
Definition at line 28 of file getopt.c.
 {
     int i;
     wchar_t c, d;
     int k, l;
     char *optchar;
     if (!optind || __optreset) {
         __optreset = 0;
         __optpos = 0;
         optind = 1;
     }
     if (optind >= argc || !argv[optind])
         return -1;
     if (argv[optind][0] != '-') {
         if (optstring[0] == '-') {
             optarg = argv[optind++];
             return 1;
         }
         return -1;
     }
     if (!argv[optind][1])
         return -1;
     if (argv[optind][1] == '-' && !argv[optind][2])
         return optind++, -1;
     if (!optpos) optpos++;
     if ((k = mbtowc(&c, argv[optind]+optpos, MB_LEN_MAX)) < 0) {
         k = 1;
         c = 0xfffd; /* replacement char */
     }
     optchar = argv[optind]+optpos;
     optpos += k;
     if (!argv[optind][optpos]) {
         optind++;
         optpos = 0;
     }
     if (optstring[0] == '-' || optstring[0] == '+')
         optstring++;
     i = 0;
     d = 0;
     do {
         l = mbtowc(&d, optstring+i, MB_LEN_MAX);
         if (l>0) i+=l; else i++;
     } while (l && d != c);
     if (d != c || c == ':') {
         optopt = c;
         if (optstring[0] != ':' && opterr)
             __getopt_msg(argv[0], ": unrecognized option: ", optchar, k);
         return '?';
     }
     if (optstring[i] == ':') {
         optarg = 0;
         if (optstring[i+1] != ':' || optpos) {
             optarg = argv[optind++];
             if (optpos) optarg += optpos;
             optpos = 0;
         }
         if (optind > argc) {
             optopt = c;
             if (optstring[0] == ':') return ':';
             if (opterr) __getopt_msg(argv[0],
                 ": option requires an argument: ",
                 optchar, k);
             return '?';
         }
     }
     return c;
 }
References __getopt_msg(), __optpos, __optreset, argv, i, k, MB_LEN_MAX, mbtowc(), optarg, opterr, optind, optopt, and optpos.
Referenced by __getopt_long_core(), and main().
getopt_long()
int getopt_long (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * idx)
Definition at line 140 of file getopt_long.c.
 {
     return __getopt_long(argc, argv, optstring, longopts, idx, 0);
 }
References __getopt_long(), argv, and idx.
getopt_long_only()
int getopt_long_only (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * idx)
Definition at line 145 of file getopt_long.c.
 {
     return __getopt_long(argc, argv, optstring, longopts, idx, 1);
 }
References __getopt_long(), argv, and idx.
Variable Documentation
optarg
char* optarg extern
Definition at line 10 of file getopt.c.
Referenced by __getopt_long_core().
opterr
int opterr
Definition at line 10 of file getopt.h.
Referenced by __getopt_long_core().
optind
int optind extern
Definition at line 11 of file getopt.c.
Referenced by __getopt_long(), __getopt_long_core(), and main().
optopt
int optopt
Definition at line 10 of file getopt.h.
Referenced by __getopt_long_core().
optreset
int optreset
Definition at line 10 of file getopt.h.