Fennix: Kernel/subsystem/linux/syscall.cpp File Reference
syscall.cpp File Reference
#include <syscalls.hpp>
#include <static_vector>
#include <signal.hpp>
#include <dumper.hpp>
#include <utsname.h>
#include <rand.hpp>
#include <limits.h>
#include <exec.hpp>
#include <task.hpp>
#include <debug.h>
#include <cpu.hpp>
#include <time.h>
#include <memory.hpp>
#include <ini.h>
#include "include/syscalls_amd64.hpp"
#include "include/syscalls_i386.hpp"
#include "include/signals.hpp"
#include "include/defs.hpp"
#include "include/errno.h"
#include "../../kernel.h"
Data Structures
struct SyscallData
Macros
#define INI_IMPLEMENTATION
#define WCONTINUED 1
#define WNOHANG 2
#define WUNTRACED 4
#define WEXITED 8
#define WNOWAIT 16
#define WSTOPPED 32
Functions
intptr_t ConvertErrnoToLinux (auto err)
int ConvertSignalToLinux (Signals sig)
Signals ConvertSignalToNative (int sig)
unsigned long ConvertMaskToNative (unsigned long mask)
unsigned long ConvertMaskToLinux (unsigned long mask)
void SetSigActToNative (const k_sigaction *linux, SignalAction *native)
void SetSigActToLinux (const SignalAction *native, k_sigaction *linux)
struct kstat KStatToStat (struct linux_kstat linux_stat)
struct linux_kstat StatToKStat (struct kstat stat)
struct kstat OKStatToStat (struct __old_kernel_stat okstat)
struct __old_kernel_stat StatToOKStat (struct kstat stat)
__no_stack_protector void __LinuxForkReturn (void *tableAddr)
static ssize_t linux_read (SysFrm *, int fd, void *buf, size_t count)
static ssize_t linux_write (SysFrm *, int fd, const void *buf, size_t count)
static int linux_open (SysFrm *sf, const char *pathname, int flags, mode_t mode)
static int linux_close (SysFrm *, int fd)
static int linux_stat (SysFrm *, const char *pathname, struct linux_kstat *statbuf)
static int linux_fstat (SysFrm *, int fd, struct linux_kstat *statbuf)
static int linux_lstat (SysFrm *, const char *pathname, struct linux_kstat *statbuf)
static off_t linux_lseek (SysFrm *, int fd, off_t offset, int whence)
static void * linux_mmap (SysFrm *, void *addr, size_t length, int prot, int flags, int fildes, off_t offset)
static int linux_mprotect (SysFrm *, void *addr, size_t len, int prot)
static int linux_munmap (SysFrm *, void *addr, size_t length)
static void * linux_brk (SysFrm *, void *addr)
static int linux_ioctl (SysFrm *, int fd, unsigned long request, void *argp)
static ssize_t linux_pread64 (SysFrm *, int fd, void *buf, size_t count, off_t offset)
static ssize_t linux_pwrite64 (SysFrm *, int fd, const void *buf, size_t count, off_t offset)
static ssize_t linux_readv (SysFrm *sf, int fildes, const struct iovec *iov, int iovcnt)
static ssize_t linux_writev (SysFrm *sf, int fildes, const struct iovec *iov, int iovcnt)
static int linux_access (SysFrm *, const char *pathname, int mode)
static int linux_pipe (SysFrm *, int pipefd[2])
static int linux_madvise (SysFrm *, void *addr, size_t length, int advice)
static int linux_dup (SysFrm *, int oldfd)
static int linux_dup2 (SysFrm *, int oldfd, int newfd)
static int linux_pause (SysFrm *)
static int linux_nanosleep (SysFrm *, const struct timespec *req, struct timespec *rem)
static pid_t linux_getpid (SysFrm *)
static int linux_setitimer (SysFrm *, int which, const struct itimerspec64 *new_value, struct itimerspec64 *old_value)
static int linux_shutdown (SysFrm *, int sockfd, int how)
static pid_t linux_fork (SysFrm *sf)
static pid_t linux_vfork (SysFrm *sf)
__no_sanitize ("undefined") static int linux_execve(SysFrm *sf
if (pPathname==nullptr||pArgv==nullptr||pEnvp==nullptr) return -linux_EFAULT
func ("%s %#lx %#lx", pPathname, pArgv, pEnvp)
for (argvLen=0;MAX_ARG;argvLen++)
for (envpLen=0;MAX_ARG;envpLen++)
for (int i=0;i< argvLen;i++)
if (!file)
file Read ((uint8_t *) shebangMagic, 2, 0)
if (shebangMagic[0]=='#' &&shebangMagic[1]=='!')
if (pcb->Linux.vforked)
if (ret< 0)
cwk_path_get_basename (pPathname, &baseName, nullptr)
pcb Rename (baseName)
pcb SetWorkingDirectory (file->Parent)
pcb SetExe (pPathname)
while (true) ctx -> Yield()
__builtin_unreachable ()
static __noreturn void linux_exit (SysFrm *, int status)
static pid_t linux_wait4 (SysFrm *, pid_t pid, int *wstatus, int options, struct rusage *rusage)
static int linux_kill (SysFrm *, pid_t pid, int sig)
static int linux_uname (SysFrm *, struct utsname *buf)
static int linux_fcntl (SysFrm *, int fd, int cmd, void *arg)
static int linux_creat (SysFrm *, const char *pathname, mode_t mode)
static long linux_getcwd (SysFrm *, char *buf, size_t size)
static int linux_chdir (SysFrm *, const char *path)
static int linux_fchdir (SysFrm *, int fd)
static int linux_mkdir (SysFrm *, const char *pathname, mode_t mode)
static ssize_t linux_readlink (SysFrm *, const char *pathname, char *buf, size_t bufsiz)
static mode_t linux_umask (SysFrm *, mode_t mask)
static int linux_getrusage (SysFrm *, int who, struct rusage *usage)
static uid_t linux_getuid (SysFrm *)
static gid_t linux_getgid (SysFrm *)
static uid_t linux_geteuid (SysFrm *)
static gid_t linux_getegid (SysFrm *)
static pid_t linux_getppid (SysFrm *)
static pid_t linux_getpgid (SysFrm *, pid_t pid)
static int linux_setpgid (SysFrm *, pid_t pid, pid_t pgid)
static int linux_arch_prctl (SysFrm *, int code, unsigned long addr)
static int linux_reboot (SysFrm *, int magic, int magic2, int cmd, void *arg)
static int linux_sigaction (SysFrm *, int signum, const k_sigaction *act, k_sigaction *oldact, size_t sigsetsize)
static int linux_sigprocmask (SysFrm *, int how, const sigset_t *set, sigset_t *oldset, size_t sigsetsize)
static void linux_sigreturn (SysFrm *sf)
static pid_t linux_gettid (SysFrm *)
static int linux_tkill (SysFrm *, int tid, int sig)
static int linux_sched_setaffinity (SysFrm *, pid_t pid, size_t cpusetsize, const cpu_set_t *mask)
static int linux_sched_getaffinity (SysFrm *, pid_t pid, size_t cpusetsize, cpu_set_t *mask)
static pid_t linux_set_tid_address (SysFrm *, int *tidptr)
if (it==fdt->FileMap.end())
if (!fildes.Node->IsDirectory())
if (pDirp==nullptr) return -linux_EFAULT
if (ret > 0) fildes.Offset+
static int linux_clock_gettime (SysFrm *, clockid_t clockid, struct timespec *tp)
static int linux_clock_nanosleep (SysFrm *, clockid_t clockid, int flags, const struct timespec *request, struct timespec *remain)
static __noreturn void linux_exit_group (SysFrm *sf, int status)
static int linux_tgkill (SysFrm *sf, pid_t tgid, pid_t tid, int sig)
static int linux_openat (SysFrm *, int dirfd, const char *pathname, int flags, mode_t mode)
static long linux_newfstatat (SysFrm *, int dirfd, const char *pathname, struct linux_kstat *statbuf, int flag)
static int linux_pipe2 (SysFrm *sf, int pipefd[2], int flags)
static int linux_prlimit64 (SysFrm *, pid_t pid, int resource, const struct rlimit *new_limit, struct rlimit *old_limit)
static ssize_t linux_getrandom (SysFrm *, void *buf, size_t buflen, unsigned int flags)
uintptr_t HandleLinuxSyscalls (SyscallsFrame *Frame)
Variables
const char * rlimitStr []
struct {
int linuxSignal
Signals nativeSignal
SignalDispositions nativeDisposition
} signalMapping []
static_vector< int, __ERRNO_MAX > errnoMap
const char * pathname
const char char *const argv []
const char char *const char *const envp []
PCB * pcb = tcb->Parent
Memory::VirtualMemoryArea * vma = pcb->vma
auto pPathname = vma->UserCheckAndGetAddress(pathname, PAGE_SIZE)
auto pArgv = vma->UserCheckAndGetAddress(argv, 1)
auto pEnvp = vma->UserCheckAndGetAddress(envp, 1)
int argvLen = 0
int envpLen = 0
char ** safeArgv = (char **)pcb->vma->RequestPages(TO_PAGES(argvLen * sizeof(char *)))
char ** safeEnvp = (char **)pcb->vma->RequestPages(TO_PAGES(envpLen * sizeof(char *)))
const char * arg
char * nArg
FileNode * file = fs->GetByPath(pPathname, pcb->CWD)
char shebangMagic [2] {}
int ret
const char * baseName
Tasking::Task * ctx = pcb->GetContext()
int fd
int struct linux_dirent64 * dirp
int struct linux_dirent64 size_t count
vfs::FileDescriptorTable * fdt = pcb->FileDescriptors
auto it = fdt->FileMap.find(fd)
vfs::FileDescriptorTable::Fildes & fildes = it->second
auto pDirp = vma->UserCheckAndGetAddress(dirp)
static SyscallData LinuxSyscallsTableAMD64 []
static SyscallData LinuxSyscallsTableI386 []
Data Structure Documentation
SyscallData
struct SyscallData
Definition at line 50 of file syscall.cpp.
Data Fields
void * Handler
const char * Name
int RequiredID
Macro Definition Documentation
INI_IMPLEMENTATION
#define INI_IMPLEMENTATION
Definition at line 33 of file syscall.cpp.
WCONTINUED
#define WCONTINUED 1
WEXITED
#define WEXITED 8
WNOHANG
#define WNOHANG 2
WNOWAIT
#define WNOWAIT 16
WSTOPPED
#define WSTOPPED 32
WUNTRACED
#define WUNTRACED 4
Function Documentation
__builtin_unreachable()
__builtin_unreachable ()
Referenced by __convert_chk_fail(), __LinuxForkReturn(), abort(), linux_exit(), Memory::Physical::RequestPage(), Memory::Physical::RequestPages(), and CPU::Stop().
__LinuxForkReturn()
__no_stack_protector void __LinuxForkReturn (void * tableAddr)
Definition at line 734 of file syscall.cpp.
 {
 #if defined(a64)
     asmv("movq %0, %%cr3" ::"r"(tableAddr)); /* Load process page table */
     asmv("movq $0, %rax\n");                 /* Return 0 */
     asmv("movq %r8, %rsp\n");                /* Restore stack pointer */
     asmv("movq %r8, %rbp\n");                /* Restore base pointer */
     asmv("swapgs\n");                        /* Swap GS back to the user GS */
     asmv("sti\n");                           /* Enable interrupts */
     asmv("sysretq\n");                       /* Return to rcx address in user mode */
 #elif defined(a32)
 #warning "__LinuxForkReturn not implemented for i386"
 #endif
     __builtin_unreachable();
 }
References __builtin_unreachable(), and asmv().
Referenced by linux_fork(), and linux_vfork().
__no_sanitize()
__no_sanitize ("undefined")
ConvertErrnoToLinux()
intptr_t ConvertErrnoToLinux (auto err) inline
Definition at line 523 of file syscall.cpp.
 {
     intptr_t errc = (intptr_t)err;
     if (errc >= 0)
     {
         debug("no change for %#lx", errc);
         return errc;
     }
     intptr_t ret = errnoMap[-errc];
     debug("converted %s(%ld) to %s(%ld)", nErrnoStr[-errc], -errc, lErrnoStr[ret], ret);
     return -ret;
 }
References debug, err(), errnoMap, and ret.
Referenced by if(), linux_brk(), linux_close(), linux_creat(), linux_dup(), linux_dup2(), linux_fcntl(), linux_fstat(), linux_ioctl(), linux_kill(), linux_lseek(), linux_lstat(), linux_mmap(), linux_newfstatat(), linux_open(), linux_openat(), linux_pause(), linux_pread64(), linux_pwrite64(), linux_read(), linux_readlink(), linux_readv(), linux_sigaction(), linux_stat(), linux_tgkill(), linux_tkill(), linux_write(), and linux_writev().
ConvertMaskToLinux()
unsigned long ConvertMaskToLinux (unsigned long mask)
Definition at line 601 of file syscall.cpp.
 {
     unsigned long ret = 0;
     for (int i = 0; i < 64; i++)
     {
         if (mask & (1ul << i))
         {
             int sig = ConvertSignalToLinux((Signals)(i + 1));
             if (unlikely(sig == SIG_NULL))
                 continue;
             ret |= 1ul << (sig - 1);
         }
     }
     return ret;
     // std::bitset<linux_SIGUNUSED + 1> bitMask(mask);
     // for (int i = 0; i < linux_SIGUNUSED + 1; i++)
     // {
     //  if (bitMask.test(i))
     //      ret |= 1 << (ConvertSignalToLinux(i + 1) - 1);
     // }
 }
References ConvertSignalToLinux(), i, ret, SIG_NULL, and unlikely.
Referenced by KStatToStat(), and linux_sigprocmask().
ConvertMaskToNative()
unsigned long ConvertMaskToNative (unsigned long mask)
Definition at line 578 of file syscall.cpp.
 {
     unsigned long ret = 0;
     for (int i = 0; i < 64; i++)
     {
         if (mask & (1ul << i))
         {
             int sig = ConvertSignalToNative(i + 1);
             if (unlikely(sig == SIG_NULL))
                 continue;
             ret |= 1ul << (sig - 1);
         }
     }
     return ret;
     // std::bitset<SIGNAL_MAX + 1> bitMask(mask);
     // for (int i = 0; i < SIGNAL_MAX + 1; i++)
     // {
     //  if (bitMask.test(i))
     //      ret |= 1 << (ConvertSignalToNative(i + 1) - 1);
     // }
 }
References ConvertSignalToNative(), i, ret, SIG_NULL, and unlikely.
Referenced by linux_sigprocmask(), and SetSigActToNative().
ConvertSignalToLinux()
int ConvertSignalToLinux (Signals sig)
Definition at line 538 of file syscall.cpp.
 {
     if (sig >= SIGRTMIN && sig <= SIGRTMAX)
         return sig; /* We ignore for now */
     foreach (auto &mapping in signalMapping)
     {
         if (mapping.nativeSignal == sig)
         {
             // debug("Converted \"%s\"(%d) to \"%s\"(%d)",
             //    sigStr[mapping.nativeSignal], sig,
             //    lSigStr[mapping.linuxSignal], mapping.linuxSignal);
             return mapping.linuxSignal;
         }
     }
     debug("Unknown signal %d", sig);
     // assert(!"Unknown signal");
     return SIG_NULL;
 }
References debug, SIG_NULL, signalMapping, SIGRTMAX, and SIGRTMIN.
Referenced by ConvertMaskToLinux(), Tasking::Signal::HandleSignal(), linux_wait4(), and Tasking::Signal::MakeExitCode().
ConvertSignalToNative()
Signals ConvertSignalToNative (int sig)
Definition at line 558 of file syscall.cpp.
 {
     if (sig >= linux_SIGRTMIN && sig <= linux_SIGRTMAX)
         return (Signals)sig; /* We ignore for now */
     foreach (auto &mapping in signalMapping)
     {
         if (mapping.linuxSignal == sig)
         {
             // debug("Converted \"%s\"(%d) to \"%s\"(%d)",
             //    lSigStr[mapping.linuxSignal], sig,
             //    sigStr[mapping.nativeSignal], mapping.nativeSignal);
             return mapping.nativeSignal;
         }
     }
     debug("Unknown signal %d", sig);
     // assert(!"Unknown signal");
     return SIG_NULL;
 }
References debug, linux_SIGRTMAX, linux_SIGRTMIN, SIG_NULL, and signalMapping.
Referenced by ConvertMaskToNative(), linux_kill(), linux_sigaction(), linux_tgkill(), and linux_tkill().
cwk_path_get_basename()
cwk_path_get_basename (pPathname , & baseName, nullptr)
for() [1/3]
for (argvLen = 0; MAX_ARG; argvLen++)
Definition at line 1614 of file syscall.cpp.
     {
         if (vma->UserCheck(pArgv[argvLen]) < 0)
             break;
         auto arg = pcb->PageTable->Get(pArgv[argvLen]);
         if (arg == nullptr)
             break;
     }
References argvLen, Memory::PageTable::Get(), Tasking::PCB::PageTable, pArgv, pcb, Memory::VirtualMemoryArea::UserCheck(), and vma.
for() [2/3]
for (envpLen = 0; MAX_ARG; envpLen++)
Definition at line 1625 of file syscall.cpp.
     {
         if (vma->UserCheck(pEnvp[envpLen]) < 0)
             break;
         auto arg = pcb->PageTable->Get(pEnvp[envpLen]);
         if (arg == nullptr)
             break;
     }
References envpLen, Memory::PageTable::Get(), Tasking::PCB::PageTable, pcb, pEnvp, Memory::VirtualMemoryArea::UserCheck(), and vma.
for() [3/3]
for ()
Definition at line 1640 of file syscall.cpp.
     {
         arg = pcb->PageTable->Get(pArgv[i]);
         assert(arg != nullptr);
         size_t len = strlen(arg);
         debug("arg[%d]: %s", i, arg);
         nArg = (char *)pcb->vma->RequestPages(TO_PAGES(len));
         memcpy((void *)nArg, arg, len);
         nArg[len] = '\0';
         safeArgv[i] = nArg;
         if (likely(i < MAX_ARG - 1))
             safeArgv[i + 1] = nullptr;
     }
References assert, debug, Memory::PageTable::Get(), i, len, likely, MAX_ARG, memcpy, nArg, Tasking::PCB::PageTable, pArgv, pcb, Memory::VirtualMemoryArea::RequestPages(), safeArgv, strlen, TO_PAGES, and Tasking::PCB::vma.
func()
func ("%s %#lx %#lx" , pPathname , pArgv , pEnvp)
Referenced by __aeabi_atexit(), __assert_fail(), __cxa_atexit(), __cxa_begin_catch(), __cxa_finalize(), Driver::__fs_Close(), Driver::__fs_Create(), Driver::__fs_Ioctl(), Driver::__fs_Lookup(), Driver::__fs_Open(), Driver::__fs_Read(), Driver::__fs_Write(), __funcs_on_exit(), __funcs_on_quick_exit(), __libc_fini_array(), __libc_init_array(), __rpmalloc_posix_madvise(), __shcall(), __synccall(), _final(), _start(), at_quick_exit(), atexit(), call_once(), clone(), Memory::VirtualMemoryArea::CreateCoWRegion(), Memory::VirtualMemoryArea::DetachAddress(), Memory::VirtualMemoryArea::Fork(), Memory::VirtualAllocation::FreePages(), Memory::VirtualMemoryArea::FreePages(), Memory::VirtualMemoryArea::HandleCoW(), I_AtExit(), Memory::ProgramBreak::InitBrk(), linux_open(), linux_read(), linux_readlink(), linux_write(), Memory::VirtualAllocation::MapTo(), P_BlockLinesIterator(), P_BlockThingsIterator(), P_TraverseIntercepts(), Memory::VirtualAllocation::RequestPages(), Memory::VirtualMemoryArea::RequestPages(), start(), thrd_create(), V_SetPatchClipCallback(), and Memory::VirtualAllocation::VirtualAllocation().
HandleLinuxSyscalls()
uintptr_t HandleLinuxSyscalls (SyscallsFrame * Frame)
Definition at line 4259 of file syscall.cpp.
 {
 #if defined(a64)
     if (Frame->rax > sizeof(LinuxSyscallsTableAMD64) / sizeof(SyscallData))
     {
         fixme("Syscall %d not implemented",
               Frame->rax);
         return -linux_ENOSYS;
     }
     SyscallData Syscall = LinuxSyscallsTableAMD64[Frame->rax];
     long (*call)(SysFrm *, long, ...) = r_cst(long (*)(SysFrm *, long, ...),
                                               Syscall.Handler);
     if (unlikely(!call))
     {
         fixme("Syscall %s(%d) not implemented",
               Syscall.Name, Frame->rax);
         return -linux_ENOSYS;
     }
     debug("> [%d:\"%s\"]( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
           Frame->rax, Syscall.Name,
           Frame->rdi, Frame->rsi, Frame->rdx,
           Frame->r10, Frame->r8, Frame->r9);
     long sc_ret = call(Frame,
                        Frame->rdi, Frame->rsi, Frame->rdx,
                        Frame->r10, Frame->r8, Frame->r9);
     debug("< [%ld:\"%s\"] = %ld", Frame->rax, Syscall.Name, sc_ret);
     return sc_ret;
 #elif defined(a32)
     if (Frame->eax > sizeof(LinuxSyscallsTableI386) / sizeof(SyscallData))
     {
         fixme("Syscall %d not implemented",
               Frame->eax);
         return -linux_ENOSYS;
     }
     SyscallData Syscall = LinuxSyscallsTableI386[Frame->eax];
     long (*call)(SysFrm *, long, ...) = r_cst(long (*)(SysFrm *, long, ...),
                                               Syscall.Handler);
     if (unlikely(!call))
     {
         fixme("Syscall %s(%d) not implemented",
               Syscall.Name, Frame->eax);
         return -linux_ENOSYS;
     }
     debug("> [%d:\"%s\"]( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
           Frame->eax, Syscall.Name,
           Frame->ebx, Frame->ecx, Frame->edx,
           Frame->esi, Frame->edi, Frame->ebp);
     int sc_ret = call(Frame,
                       Frame->ebx, Frame->ecx, Frame->edx,
                       Frame->esi, Frame->edi, Frame->ebp);
     debug("< [%d:\"%s\"] = %d", Frame->eax, Syscall.Name, sc_ret);
     return sc_ret;
 #elif defined(aa64)
     return -linux_ENOSYS;
 #endif
 #if defined(a64)
     UNUSED(LinuxSyscallsTableI386);
 #elif defined(a32)
     UNUSED(LinuxSyscallsTableAMD64);
 #endif
 }
References call(), debug, fixme, SyscallData::Handler, linux_ENOSYS, LinuxSyscallsTableAMD64, LinuxSyscallsTableI386, SyscallData::Name, SysFrm, unlikely, and UNUSED.
Referenced by SystemCallsHandler().
if() [1/9]
if (!fildes.Node-> IsDirectory())
Definition at line 2891 of file syscall.cpp.
     {
         debug("Not a directory");
         return -ENOTDIR;
     }
References debug, and ENOTDIR.
if() [2/9]
if (! file)
Definition at line 1676 of file syscall.cpp.
     {
         error("File not found");
         return -linux_ENOENT;
     }
References error, and linux_ENOENT.
if() [3/9]
if (it = = fdt->FileMap.end())
Definition at line 2884 of file syscall.cpp.
     {
         debug("Invalid fd %d", fd);
         return -linux_EBADF;
     }
References debug, fd, and linux_EBADF.
if() [4/9]
if (pcb->Linux. vforked)
Definition at line 1748 of file syscall.cpp.
     {
         CriticalSection cs;
         pcb->Linux.CallingThread->SetState(Tasking::Ready);
         pcb->Linux.vforked = false;
         pcb->PageTable = KernelPageTable->Fork();
         pcb->vma = new Memory::VirtualMemoryArea(pcb->PageTable);
         pcb->ProgramBreak = new Memory::ProgramBreak(pcb->PageTable, pcb->vma);
         // tcb->Stack = new Memory::StackGuard(true, pcb->vma);
     }
References KernelPageTable, Tasking::PCB::Linux, Tasking::PCB::PageTable, pcb, Tasking::PCB::ProgramBreak, Tasking::Ready, Tasking::PCB::SetState(), and Tasking::PCB::vma.
if() [5/9]
if (pDirp = =nullptr)
if() [6/9]
if (pPathname = =nullptr||pArgv==nullptr||pEnvp==nullptr)
if() [7/9]
if (ret , 0)
References linux_dirent64::d_ino, linux_dirent64::d_name, linux_dirent64::d_off, linux_dirent64::d_reclen, linux_dirent64::d_type, debug, DT_BLK, DT_CHR, DT_DIR, DT_FIFO, DT_LNK, DT_REG, DT_SOCK, pDirp, and ret.
if() [8/9]
if ()
Definition at line 1767 of file syscall.cpp.
     {
         error("Failed to spawn");
         return ConvertErrnoToLinux(ret);
     }
References ConvertErrnoToLinux(), error, and ret.
if() [9/9]
if (shebangMagic [0] = = '#' && shebangMagic[1] == '!')
Definition at line 1685 of file syscall.cpp.
     {
         char *origPath = (char *)pcb->vma->RequestPages(TO_PAGES(strlen(pPathname) + 1));
         memcpy(origPath, pPathname, strlen(pPathname) + 1);
         char *shebang = (char *)pPathname;
         size_t shebangLength = 0;
         constexpr int shebangLengthMax = 255;
         off_t shebangOffset = 2;
         while (true)
         {
             char c;
             if (file->Read((uint8_t *)&c, 1, shebangOffset) == 0)
                 break;
             if (c == '\n' || shebangLength == shebangLengthMax)
                 break;
             shebang[shebangLength++] = c;
             shebangOffset++;
         }
         shebang[shebangLength] = '\0';
         debug("Shebang: %s", shebang);
         char **cSafeArgv = (char **)pcb->vma->RequestPages(TO_PAGES(MAX_ARG));
         int i = 0;
         for (; safeArgv[i] != nullptr; i++)
         {
             size_t argLength = strlen(safeArgv[i]);
             char *cArg = (char *)pcb->vma->RequestPages(TO_PAGES(argLength));
             memcpy((void *)cArg, safeArgv[i], argLength);
             cArg[argLength] = '\0';
             cSafeArgv[i] = cArg;
             debug("cSafeArgv[%d]: %s", i, cSafeArgv[i]);
         }
         cSafeArgv[i] = nullptr;
         char *token = strtok(shebang, " ");
         i = 0;
         while (token != nullptr)
         {
             size_t len = strlen(token);
             char *t_arg = (char *)pcb->vma->RequestPages(TO_PAGES(len));
             memcpy((void *)t_arg, token, len);
             t_arg[len] = '\0';
             safeArgv[i++] = t_arg;
             token = strtok(nullptr, " ");
         }
         safeArgv[i++] = origPath;
         for (int j = 1; cSafeArgv[j] != nullptr; j++)
         {
             safeArgv[i++] = cSafeArgv[j];
             debug("clone: safeArgv[%d]: %s",
                   i, safeArgv[i - 1]);
         }
         safeArgv[i] = nullptr;
         return ConvertErrnoToLinux(linux_execve(sf, safeArgv[0],
                                                 (char *const *)safeArgv,
                                                 (char *const *)safeEnvp));
     }
References ConvertErrnoToLinux(), debug, file, i, j, len, MAX_ARG, memcpy, off_t, pcb, pPathname, FileNode::Read(), Memory::VirtualMemoryArea::RequestPages(), safeArgv, safeEnvp, strlen, strtok(), TO_PAGES, and Tasking::PCB::vma.
KStatToStat()
struct kstat KStatToStat (struct linux_kstat linux_stat)
Definition at line 635 of file syscall.cpp.
 {
     struct kstat stat;
     stat.Device = linux_stat.st_dev;
     stat.Index = linux_stat.st_ino;
     stat.HardLinks = (nlink_t)linux_stat.st_nlink;
     stat.Mode = linux_stat.st_mode;
     stat.UserID = linux_stat.st_uid;
     stat.GroupID = linux_stat.st_gid;
     stat.RawDevice = linux_stat.st_rdev;
     stat.Size = linux_stat.st_size;
     stat.BlockSize = linux_stat.st_blksize;
     stat.Blocks = linux_stat.st_blocks;
     stat.AccessTime = linux_stat.st_atime;
     // stat.st_atime_nsec = linux_stat.st_atime_nsec;
     stat.ModifyTime = linux_stat.st_mtime;
     // stat.st_mtime_nsec = linux_stat.st_mtime_nsec;
     stat.ChangeTime = linux_stat.st_ctime;
     // stat.st_ctime_nsec = linux_stat.st_ctime_nsec;
     return stat;
 }
References ConvertMaskToLinux(), debug, SignalAction::Flags, k_sigaction::flags, k_sigaction::handler, SignalAction::Mask, k_sigaction::mask, SignalAction::Restorer, k_sigaction::restorer, and SignalAction::sa_handler.
Referenced by linux_fstat(), linux_lstat(), linux_newfstatat(), and linux_stat().
linux_access()
static int linux_access (SysFrm * , const char * pathname, int mode) static
Definition at line 1261 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pPathname = vma->UserCheckAndGetAddress(pathname);
     if (pPathname == nullptr)
         return -linux_EFAULT;
     debug("access(%s, %d)", (char *)pPathname, mode);
     if (!fs->PathExists(pPathname, pcb->CWD))
         return -linux_ENOENT;
     stub;
     return 0;
 }
References Tasking::PCB::CWD, debug, fs, linux_EFAULT, linux_ENOENT, vfs::Virtual::PathExists(), pathname, pcb, pPathname, stub, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_arch_prctl()
static int linux_arch_prctl (SysFrm * , int code, unsigned long addr) static
Definition at line 2492 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     if (vma->UserCheck(addr) < 0)
         return -linux_EFAULT;
     switch (code)
     {
     case linux_ARCH_SET_GS:
     {
 #if defined(a64)
         CPU::x64::wrmsr(CPU::x64::MSRID::MSR_GS_BASE, addr);
 #elif defined(a32)
         CPU::x32::wrmsr(CPU::x32::MSRID::MSR_GS_BASE, addr);
 #endif
         return 0;
     }
     case linux_ARCH_SET_FS:
     {
 #if defined(a64)
         CPU::x64::wrmsr(CPU::x64::MSRID::MSR_FS_BASE, addr);
 #elif defined(a32)
         CPU::x32::wrmsr(CPU::x32::MSRID::MSR_FS_BASE, addr);
 #endif
         return 0;
     }
     case linux_ARCH_GET_FS:
     {
 #if defined(a64)
         *r_cst(uint64_t *, addr) =
             CPU::x64::rdmsr(CPU::x64::MSRID::MSR_FS_BASE);
 #elif defined(a32)
         *r_cst(uint64_t *, addr) =
             CPU::x32::rdmsr(CPU::x32::MSRID::MSR_FS_BASE);
 #endif
         return 0;
     }
     case linux_ARCH_GET_GS:
     {
 #if defined(a64)
         *r_cst(uint64_t *, addr) =
             CPU::x64::rdmsr(CPU::x64::MSRID::MSR_GS_BASE);
 #elif defined(a32)
         *r_cst(uint64_t *, addr) =
             CPU::x32::rdmsr(CPU::x32::MSRID::MSR_GS_BASE);
 #endif
         return 0;
     }
     case linux_ARCH_GET_CPUID:
     case linux_ARCH_SET_CPUID:
     case linux_ARCH_GET_XCOMP_SUPP:
     case linux_ARCH_GET_XCOMP_PERM:
     case linux_ARCH_REQ_XCOMP_PERM:
     case linux_ARCH_GET_XCOMP_GUEST_PERM:
     case linux_ARCH_REQ_XCOMP_GUEST_PERM:
     case linux_ARCH_XCOMP_TILECFG:
     case linux_ARCH_XCOMP_TILEDATA:
     case linux_ARCH_MAP_VDSO_X32:
     case linux_ARCH_MAP_VDSO_32:
     case linux_ARCH_MAP_VDSO_64:
     case linux_ARCH_GET_UNTAG_MASK:
     case linux_ARCH_ENABLE_TAGGED_ADDR:
     case linux_ARCH_GET_MAX_TAG_BITS:
     case linux_ARCH_FORCE_TAGGED_SVA:
     {
         fixme("Code %#lx not implemented", code);
         return -linux_ENOSYS;
     }
     default:
     {
         debug("Invalid code %#lx", code);
         return -linux_EINVAL;
     }
     }
 }
References addr, debug, fixme, linux_ARCH_ENABLE_TAGGED_ADDR, linux_ARCH_FORCE_TAGGED_SVA, linux_ARCH_GET_CPUID, linux_ARCH_GET_FS, linux_ARCH_GET_GS, linux_ARCH_GET_MAX_TAG_BITS, linux_ARCH_GET_UNTAG_MASK, linux_ARCH_GET_XCOMP_GUEST_PERM, linux_ARCH_GET_XCOMP_PERM, linux_ARCH_GET_XCOMP_SUPP, linux_ARCH_MAP_VDSO_32, linux_ARCH_MAP_VDSO_64, linux_ARCH_MAP_VDSO_X32, linux_ARCH_REQ_XCOMP_GUEST_PERM, linux_ARCH_REQ_XCOMP_PERM, linux_ARCH_SET_CPUID, linux_ARCH_SET_FS, linux_ARCH_SET_GS, linux_ARCH_XCOMP_TILECFG, linux_ARCH_XCOMP_TILEDATA, linux_EFAULT, linux_EINVAL, linux_ENOSYS, CPU::x32::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, pcb, thisProcess, Memory::VirtualMemoryArea::UserCheck(), Tasking::PCB::vma, and vma.
linux_brk()
static void* linux_brk (SysFrm * , void * addr) static
Definition at line 1121 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     void *ret = pcb->ProgramBreak->brk(addr);
     debug("brk(%#lx) = %#lx", addr, ret);
     return (void *)ConvertErrnoToLinux(ret);
 }
References addr, Memory::ProgramBreak::brk(), ConvertErrnoToLinux(), debug, pcb, Tasking::PCB::ProgramBreak, ret, and thisProcess.
linux_chdir()
static int linux_chdir (SysFrm * , const char * path) static
Definition at line 2260 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const char *pPath = vma->UserCheckAndGetAddress(path);
     if (!pPath)
         return -linux_EFAULT;
     FileNode *n = fs->GetByPath(pPath, pcb->CWD);
     if (!n)
         return -linux_ENOENT;
     pcb->SetWorkingDirectory(n);
     debug("Changed cwd to \"%s\"", n->GetPath().c_str());
     return 0;
 }
References Tasking::PCB::CWD, debug, fs, vfs::Virtual::GetByPath(), linux_EFAULT, linux_ENOENT, n, pcb, Tasking::PCB::SetWorkingDirectory(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_clock_gettime()
static int linux_clock_gettime (SysFrm * , clockid_t clockid, struct timespec * tp) static
Definition at line 2942 of file syscall.cpp.
 {
     static_assert(sizeof(struct timespec) < PAGE_SIZE);
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     timespec *pTp = vma->UserCheckAndGetAddress(tp);
     if (pTp == nullptr)
         return -linux_EFAULT;
     /* FIXME: This is not correct? */
     switch (clockid)
     {
     case linux_CLOCK_REALTIME:
     {
         uint64_t time = TimeManager->GetCounter();
         pTp->tv_sec = time / Time::ConvertUnit(Time::Seconds);
         pTp->tv_nsec = time / Time::ConvertUnit(Time::Nanoseconds);
         debug("time=%ld sec=%ld nsec=%ld",
               time, pTp->tv_sec, pTp->tv_nsec);
         break;
     }
     case linux_CLOCK_MONOTONIC:
     {
         uint64_t time = TimeManager->GetCounter();
         pTp->tv_sec = time / Time::ConvertUnit(Time::Seconds);
         pTp->tv_nsec = time / Time::ConvertUnit(Time::Nanoseconds);
         debug("time=%ld sec=%ld nsec=%ld",
               time, pTp->tv_sec, pTp->tv_nsec);
         break;
     }
     case linux_CLOCK_PROCESS_CPUTIME_ID:
     case linux_CLOCK_THREAD_CPUTIME_ID:
     case linux_CLOCK_MONOTONIC_RAW:
     case linux_CLOCK_REALTIME_COARSE:
     case linux_CLOCK_MONOTONIC_COARSE:
     case linux_CLOCK_BOOTTIME:
     case linux_CLOCK_REALTIME_ALARM:
     case linux_CLOCK_BOOTTIME_ALARM:
     case linux_CLOCK_SGI_CYCLE:
     case linux_CLOCK_TAI:
     {
         fixme("clockid %d is stub", clockid);
         return -linux_ENOSYS;
     }
     default:
     {
         warn("Invalid clockid %#lx", clockid);
         return -linux_EINVAL;
     }
     }
     return 0;
 }
References Time::ConvertUnit(), debug, fixme, Time::time::GetCounter(), linux_CLOCK_BOOTTIME, linux_CLOCK_BOOTTIME_ALARM, linux_CLOCK_MONOTONIC, linux_CLOCK_MONOTONIC_COARSE, linux_CLOCK_MONOTONIC_RAW, linux_CLOCK_PROCESS_CPUTIME_ID, linux_CLOCK_REALTIME, linux_CLOCK_REALTIME_ALARM, linux_CLOCK_REALTIME_COARSE, linux_CLOCK_SGI_CYCLE, linux_CLOCK_TAI, linux_CLOCK_THREAD_CPUTIME_ID, linux_EFAULT, linux_EINVAL, linux_ENOSYS, Time::Nanoseconds, PAGE_SIZE, pcb, Time::Seconds, static_assert, thisProcess, time(), TimeManager, timespec::tv_nsec, timespec::tv_sec, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, and warn.
linux_clock_nanosleep()
static int linux_clock_nanosleep (SysFrm * , clockid_t clockid, int flags, const struct timespec * request, struct timespec * remain) static
Definition at line 2997 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const timespec *pRequest = vma->UserCheckAndGetAddress(request);
     timespec *pRemain = vma->UserCheckAndGetAddress(remain);
     if (pRequest == nullptr)
         return -linux_EFAULT;
     UNUSED(pRemain);
     UNUSED(flags);
     switch (clockid)
     {
     case linux_CLOCK_REALTIME:
     case linux_CLOCK_MONOTONIC:
     {
         uint64_t time = TimeManager->GetCounter();
         uint64_t rqTime = pRequest->tv_sec * Time::ConvertUnit(Time::Seconds) +
                           pRequest->tv_nsec * Time::ConvertUnit(Time::Nanoseconds);
         debug("Sleeping for %ld", rqTime - time);
         if (rqTime > time)
             pcb->GetContext()->Sleep(rqTime - time);
         break;
     }
     case linux_CLOCK_PROCESS_CPUTIME_ID:
     case linux_CLOCK_THREAD_CPUTIME_ID:
     case linux_CLOCK_MONOTONIC_RAW:
     case linux_CLOCK_REALTIME_COARSE:
     case linux_CLOCK_MONOTONIC_COARSE:
     case linux_CLOCK_BOOTTIME:
     case linux_CLOCK_REALTIME_ALARM:
     case linux_CLOCK_BOOTTIME_ALARM:
     case linux_CLOCK_SGI_CYCLE:
     case linux_CLOCK_TAI:
     {
         fixme("clockid %d is stub", clockid);
         return -linux_ENOSYS;
     }
     default:
     {
         warn("Invalid clockid %#lx", clockid);
         return -linux_EINVAL;
     }
     }
     return 0;
 }
References Time::ConvertUnit(), debug, fixme, Tasking::PCB::GetContext(), Time::time::GetCounter(), linux_CLOCK_BOOTTIME, linux_CLOCK_BOOTTIME_ALARM, linux_CLOCK_MONOTONIC, linux_CLOCK_MONOTONIC_COARSE, linux_CLOCK_MONOTONIC_RAW, linux_CLOCK_PROCESS_CPUTIME_ID, linux_CLOCK_REALTIME, linux_CLOCK_REALTIME_ALARM, linux_CLOCK_REALTIME_COARSE, linux_CLOCK_SGI_CYCLE, linux_CLOCK_TAI, linux_CLOCK_THREAD_CPUTIME_ID, linux_EFAULT, linux_EINVAL, linux_ENOSYS, Time::Nanoseconds, pcb, Time::Seconds, Tasking::Task::Sleep(), thisProcess, time(), TimeManager, timespec::tv_nsec, timespec::tv_sec, UNUSED, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, and warn.
linux_close()
static int linux_close (SysFrm * , int fd) static
Definition at line 825 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return ConvertErrnoToLinux(fdt->usr_close(fd));
 }
References ConvertErrnoToLinux(), fd, fdt, Tasking::PCB::FileDescriptors, pcb, thisProcess, and vfs::FileDescriptorTable::usr_close().
linux_creat()
static int linux_creat (SysFrm * , const char * pathname, mode_t mode) static
Definition at line 2231 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return ConvertErrnoToLinux(fdt->usr_creat(pathname, mode));
 }
References ConvertErrnoToLinux(), fdt, Tasking::PCB::FileDescriptors, pathname, pcb, thisProcess, and vfs::FileDescriptorTable::usr_creat().
linux_dup()
static int linux_dup (SysFrm * , int oldfd) static
Definition at line 1300 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return ConvertErrnoToLinux(fdt->usr_dup(oldfd));
 }
References ConvertErrnoToLinux(), fdt, Tasking::PCB::FileDescriptors, pcb, thisProcess, and vfs::FileDescriptorTable::usr_dup().
linux_dup2()
static int linux_dup2 (SysFrm * , int oldfd, int newfd) static
Definition at line 1307 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return ConvertErrnoToLinux(fdt->usr_dup2(oldfd, newfd));
 }
References ConvertErrnoToLinux(), fdt, Tasking::PCB::FileDescriptors, pcb, thisProcess, and vfs::FileDescriptorTable::usr_dup2().
linux_exit()
static __noreturn void linux_exit (SysFrm * , int status) static
Definition at line 1789 of file syscall.cpp.
 {
     TCB *t = thisThread;
     {
         CriticalSection cs;
         trace("Userspace thread %s(%d) exited with code %d (%#x)",
               t->Name,
               t->ID, status,
               status < 0 ? -status : status);
         t->SetState(Tasking::Zombie);
         t->SetExitCode(status);
         if (t->Parent->Linux.vforked)
             t->Parent->Linux.CallingThread->SetState(Tasking::Ready);
     }
     while (true)
         t->GetContext()->Yield();
     __builtin_unreachable();
 }
References __builtin_unreachable(), Tasking::TCB::GetContext(), Tasking::TCB::ID, Tasking::PCB::Linux, Tasking::TCB::Name, Tasking::TCB::Parent, Tasking::Ready, Tasking::TCB::SetExitCode(), Tasking::TCB::SetState(), Tasking::PCB::SetState(), thisThread, trace, Tasking::Task::Yield(), and Tasking::Zombie.
Referenced by linux_exit_group().
linux_exit_group()
static __noreturn void linux_exit_group (SysFrm * sf, int status) static
Definition at line 3049 of file syscall.cpp.
 {
     fixme("status=%d", status);
     linux_exit(sf, status);
 }
References fixme, and linux_exit().
linux_fchdir()
static int linux_fchdir (SysFrm * , int fd) static
Definition at line 2278 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     auto it = fdt->FileMap.find(fd);
     if (it == fdt->FileMap.end())
         return -linux_EBADF;
     pcb->SetWorkingDirectory(it->second.Node);
     debug("Changed cwd to \"%s\"", it->second.Node->GetPath().c_str());
     return 0;
 }
References debug, fd, fdt, Tasking::PCB::FileDescriptors, vfs::FileDescriptorTable::FileMap, it, linux_EBADF, pcb, Tasking::PCB::SetWorkingDirectory(), and thisProcess.
linux_fcntl()
static int linux_fcntl (SysFrm * , int fd, int cmd, void * arg) static
Definition at line 2165 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     switch (cmd)
     {
     case linux_F_DUPFD:
         return ConvertErrnoToLinux(fdt->usr_dup2(fd, s_cst(int, (uintptr_t)arg)));
     case linux_F_GETFD:
         return ConvertErrnoToLinux(fdt->GetFlags(fd));
     case linux_F_SETFD:
         return ConvertErrnoToLinux(fdt->SetFlags(fd, s_cst(int, (uintptr_t)arg)));
     case linux_F_GETFL:
     {
         fixme("F_GETFL is stub?");
         return ConvertErrnoToLinux(fdt->GetFlags(fd));
     }
     case linux_F_SETFL:
     {
         fixme("F_SETFL is stub?");
         int flags = s_cst(int, (uintptr_t)arg);
         if (flags & O_APPEND)
             fdt->SetFlags(fd, fdt->GetFlags(fd) | O_APPEND);
         else
             fdt->SetFlags(fd, fdt->GetFlags(fd) & ~O_APPEND);
         return 0;
     }
     case linux_F_DUPFD_CLOEXEC:
     {
         int ret = fdt->usr_dup2(fd, s_cst(int, (uintptr_t)arg));
         if (ret < 0)
             return ConvertErrnoToLinux(ret);
         auto it = fdt->FileMap.find(fd);
         if (it == fdt->FileMap.end())
             ReturnLogError(-linux_EBADF, "Invalid fd %d", fd);
         it->second.Flags |= linux_FD_CLOEXEC;
         return ret;
     }
     case linux_F_SETOWN:
     case linux_F_GETOWN:
     case linux_F_SETSIG:
     case linux_F_GETSIG:
     case linux_F_GETLK:
     case linux_F_SETLK:
     case linux_F_SETLKW:
     case linux_F_SETOWN_EX:
     case linux_F_GETOWN_EX:
     case linux_F_GETOWNER_UIDS:
     case linux_F_OFD_GETLK:
     case linux_F_OFD_SETLK:
     case linux_F_OFD_SETLKW:
     {
         fixme("cmd %d not implemented", cmd);
         return -linux_ENOSYS;
     }
     default:
     {
         debug("Invalid cmd %#x", cmd);
         return -linux_EINVAL;
     }
     }
 }
References ConvertErrnoToLinux(), debug, fd, fdt, Tasking::PCB::FileDescriptors, vfs::FileDescriptorTable::FileMap, fixme, vfs::FileDescriptorTable::GetFlags(), it, linux_EBADF, linux_EINVAL, linux_ENOSYS, linux_F_DUPFD, linux_F_DUPFD_CLOEXEC, linux_F_GETFD, linux_F_GETFL, linux_F_GETLK, linux_F_GETOWN, linux_F_GETOWN_EX, linux_F_GETOWNER_UIDS, linux_F_GETSIG, linux_F_OFD_GETLK, linux_F_OFD_SETLK, linux_F_OFD_SETLKW, linux_F_SETFD, linux_F_SETFL, linux_F_SETLK, linux_F_SETLKW, linux_F_SETOWN, linux_F_SETOWN_EX, linux_F_SETSIG, linux_FD_CLOEXEC, O_APPEND, pcb, ret, ReturnLogError, vfs::FileDescriptorTable::SetFlags(), thisProcess, and vfs::FileDescriptorTable::usr_dup2().
linux_fork()
static pid_t linux_fork (SysFrm * sf) static
Definition at line 1429 of file syscall.cpp.
 {
     TCB *Thread = thisThread;
     PCB *Parent = Thread->Parent;
     PCB *NewProcess =
         TaskManager->CreateProcess(Parent, Parent->Name,
                                    Parent->Security.ExecutionMode,
                                    true);
     if (unlikely(!NewProcess))
     {
         error("Failed to create process for fork");
         return -linux_EAGAIN;
     }
     NewProcess->Security.ProcessGroupID = Parent->Security.ProcessGroupID;
     NewProcess->Security.SessionID = Parent->Security.SessionID;
     NewProcess->PageTable = Parent->PageTable->Fork();
     NewProcess->vma->Table = NewProcess->PageTable;
     NewProcess->vma->Fork(Parent->vma);
     NewProcess->ProgramBreak->SetTable(NewProcess->PageTable);
     NewProcess->FileDescriptors->Fork(Parent->FileDescriptors);
     NewProcess->Executable = Parent->Executable;
     NewProcess->CWD = Parent->CWD;
     NewProcess->FileCreationMask = Parent->FileCreationMask;
     TCB *NewThread =
         TaskManager->CreateThread(NewProcess,
                                   0,
                                   nullptr,
                                   nullptr,
                                   std::vector<AuxiliaryVector>(),
                                   Thread->Info.Architecture,
                                   Thread->Info.Compatibility,
                                   true);
     if (!NewThread)
     {
         error("Failed to create thread for fork");
         delete NewProcess;
         return -linux_EAGAIN;
     }
     NewThread->Rename(Thread->Name);
     TaskManager->UpdateFrame();
     NewThread->FPU = Thread->FPU;
     NewThread->Stack->Fork(Thread->Stack);
     NewThread->Info.Architecture = Thread->Info.Architecture;
     NewThread->Info.Compatibility = Thread->Info.Compatibility;
     NewThread->Security.IsCritical = Thread->Security.IsCritical;
     NewThread->Registers = Thread->Registers;
 #if defined(a64)
     NewThread->Registers.rip = (uintptr_t)__LinuxForkReturn;
     /* For sysretq */
     NewThread->Registers.rdi = (uintptr_t)NewProcess->PageTable;
     NewThread->Registers.rcx = sf->ReturnAddress;
     NewThread->Registers.r8 = sf->StackPointer;
 #else
 #warning "sys_fork not implemented for other platforms"
 #endif
 #ifdef a86
     NewThread->GSBase = NewThread->ShadowGSBase;
     NewThread->ShadowGSBase = Thread->ShadowGSBase;
     NewThread->FSBase = Thread->FSBase;
 #endif
     debug("ret addr: %#lx, stack: %#lx ip: %#lx", sf->ReturnAddress,
           sf->StackPointer, (uintptr_t)__LinuxForkReturn);
     debug("Forked thread \"%s\"(%d) to \"%s\"(%d)",
           Thread->Name, Thread->ID,
           NewThread->Name, NewThread->ID);
     NewThread->SetState(Tasking::Ready);
     // Parent->GetContext()->Yield();
     return (int)NewProcess->ID;
 }
References __LinuxForkReturn(), Tasking::TaskInfo::Architecture, Tasking::TaskInfo::Compatibility, Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), Tasking::PCB::CWD, debug, error, Tasking::PCB::Executable, Tasking::PCB::FileCreationMask, Tasking::PCB::FileDescriptors, Memory::PageTable::Fork(), vfs::FileDescriptorTable::Fork(), Memory::StackGuard::Fork(), Memory::VirtualMemoryArea::Fork(), Tasking::TCB::ID, Tasking::PCB::ID, Tasking::TCB::Info, linux_EAGAIN, Tasking::TCB::Name, Tasking::PCB::Name, Tasking::PCB::PageTable, Tasking::TCB::Parent, Tasking::PCB::ProgramBreak, Tasking::Ready, Tasking::TCB::Rename(), Tasking::TCB::Security, Tasking::PCB::Security, Tasking::TCB::SetState(), Memory::ProgramBreak::SetTable(), Tasking::TCB::Stack, Memory::VirtualMemoryArea::Table, TaskManager, thisThread, unlikely, Tasking::Task::UpdateFrame(), and Tasking::PCB::vma.
linux_fstat()
static int linux_fstat (SysFrm * , int fd, struct linux_kstat * statbuf) static
Definition at line 857 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pStatbuf = vma->UserCheckAndGetAddress(statbuf);
     if (pStatbuf == nullptr)
         return -linux_EFAULT;
     struct kstat nstat = KStatToStat(*pStatbuf);
     int ret = ConvertErrnoToLinux(fdt->usr_fstat(fd, &nstat));
     *pStatbuf = StatToKStat(nstat);
     return ret;
 }
References ConvertErrnoToLinux(), fd, fdt, Tasking::PCB::FileDescriptors, KStatToStat(), linux_EFAULT, pcb, ret, StatToKStat(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_fstat(), Tasking::PCB::vma, and vma.
linux_getcwd()
static long linux_getcwd (SysFrm * , char * buf, size_t size) static
Definition at line 2238 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     char *pBuf = vma->UserCheckAndGetAddress(buf, size);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     std::string cwd = pcb->CWD->GetPath();
     if (cwd.length() >= size)
     {
         warn("Buffer too small (%ld < %ld)", cwd.length(), size);
         return -linux_ERANGE;
     }
     strncpy(pBuf, cwd.c_str(), cwd.length());
     pBuf[cwd.length()] = '\0';
     debug("cwd: \"%s\" with %ld bytes", cwd.c_str(), cwd.length());
     return cwd.length();
 }
References buf, Tasking::PCB::CWD, debug, FileNode::GetPath(), linux_EFAULT, linux_ERANGE, pcb, size, strncpy(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, and warn.
linux_getegid()
static gid_t linux_getegid (SysFrm *) static
Definition at line 2446 of file syscall.cpp.
 {
     return thisProcess->Security.Effective.GroupID;
 }
References thisProcess.
linux_geteuid()
static uid_t linux_geteuid (SysFrm *) static
Definition at line 2441 of file syscall.cpp.
 {
     return thisProcess->Security.Effective.UserID;
 }
References thisProcess.
linux_getgid()
static gid_t linux_getgid (SysFrm *) static
Definition at line 2436 of file syscall.cpp.
 {
     return thisProcess->Security.Real.GroupID;
 }
References thisProcess.
linux_getpgid()
static pid_t linux_getpgid (SysFrm * , pid_t pid) static
Definition at line 2456 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     if (pid == 0)
         return pcb->Security.ProcessGroupID;
     PCB *target = pcb->GetContext()->GetProcessByID(pid);
     if (!target)
         return -linux_ESRCH;
     return target->Security.ProcessGroupID;
 }
References Tasking::PCB::GetContext(), Tasking::Task::GetProcessByID(), linux_ESRCH, pcb, Tasking::PCB::Security, and thisProcess.
linux_getpid()
static pid_t linux_getpid (SysFrm *) static
Definition at line 1378 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     return pcb->ID;
 }
References Tasking::PCB::ID, pcb, and thisProcess.
linux_getppid()
static pid_t linux_getppid (SysFrm *) static
Definition at line 2451 of file syscall.cpp.
 {
     return thisProcess->Parent->ID;
 }
References thisProcess.
linux_getrandom()
static ssize_t linux_getrandom (SysFrm * , void * buf, size_t buflen, unsigned int flags) static
Definition at line 3324 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     if (flags & linux_GRND_NONBLOCK)
         fixme("GRND_NONBLOCK not implemented");
     if (flags & ~(linux_GRND_NONBLOCK |
                   linux_GRND_RANDOM |
                   linux_GRND_INSECURE))
     {
         warn("Invalid flags %#x", flags);
         return -linux_EINVAL;
     }
     auto pBuf = vma->UserCheckAndGetAddress(buf, buflen);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     if (flags & linux_GRND_RANDOM)
     {
         uint16_t random;
         for (size_t i = 0; i < buflen; i++)
         {
             random = Random::rand16();
             ((uint8_t *)pBuf)[i] = uint8_t(random & 0xFF);
         }
         return buflen;
     }
     return 0;
 }
References buf, fixme, i, linux_EFAULT, linux_EINVAL, linux_GRND_INSECURE, linux_GRND_NONBLOCK, linux_GRND_RANDOM, pcb, Random::rand16(), random(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, and warn.
linux_getrusage()
static int linux_getrusage (SysFrm * , int who, struct rusage * usage) static
Definition at line 2359 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pUsage = vma->UserCheckAndGetAddress(usage);
     if (pUsage == nullptr)
         return -linux_EFAULT;
     switch (who)
     {
     case linux_RUSAGE_SELF:
     {
         size_t kTime = pcb->Info.KernelTime;
         size_t uTime = pcb->Info.UserTime;
         size_t _maxrss = pcb->GetSize();
         pUsage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
         pUsage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
         pUsage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
         pUsage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
         pUsage->ru_maxrss = _maxrss;
         break;
     }
     case linux_RUSAGE_CHILDREN:
     {
         size_t kTime = 0;
         size_t uTime = 0;
         size_t _maxrss = 0;
         foreach (auto child in pcb->Children)
         {
             kTime += child->Info.KernelTime;
             uTime += child->Info.UserTime;
             _maxrss += child->GetSize();
         }
         pUsage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
         pUsage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
         pUsage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
         pUsage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
         pUsage->ru_maxrss = _maxrss;
         break;
     }
     case linux_RUSAGE_THREAD:
     {
         TCB *tcb = thisThread;
         size_t kTime = tcb->Info.KernelTime;
         size_t uTime = tcb->Info.UserTime;
         size_t _maxrss = tcb->GetSize();
         pUsage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
         pUsage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
         pUsage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
         pUsage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
         pUsage->ru_maxrss = _maxrss;
         break;
     }
     default:
         return -linux_EINVAL;
     }
     return 0;
 }
References child(), Tasking::PCB::Children, Tasking::TCB::GetSize(), Tasking::PCB::GetSize(), Tasking::TCB::Info, Tasking::PCB::Info, Tasking::TaskInfo::KernelTime, linux_EFAULT, linux_EINVAL, linux_RUSAGE_CHILDREN, linux_RUSAGE_SELF, linux_RUSAGE_THREAD, pcb, thisProcess, thisThread, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::TaskInfo::UserTime, Tasking::PCB::vma, and vma.
linux_gettid()
static pid_t linux_gettid (SysFrm *) static
Definition at line 2770 of file syscall.cpp.
 {
     return thisThread->ID;
 }
References thisThread.
linux_getuid()
static uid_t linux_getuid (SysFrm *) static
Definition at line 2431 of file syscall.cpp.
 {
     return thisProcess->Security.Real.UserID;
 }
References thisProcess.
linux_ioctl()
static int linux_ioctl (SysFrm * , int fd, unsigned long request, void * argp) static
Definition at line 1129 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pArgp = vma->UserCheckAndGetAddress(argp);
     if (pArgp == nullptr)
         return -linux_EFAULT;
     int ret = ConvertErrnoToLinux(fdt->usr_ioctl(fd, request, pArgp));
     return ret;
 }
References ConvertErrnoToLinux(), fd, fdt, Tasking::PCB::FileDescriptors, linux_EFAULT, pcb, ret, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_ioctl(), Tasking::PCB::vma, and vma.
linux_kill()
static int linux_kill (SysFrm * , pid_t pid, int sig) static
Definition at line 2039 of file syscall.cpp.
 {
     PCB *pcb = thisProcess->GetContext()->GetProcessByID(pid);
     if (!pcb)
         return -linux_ESRCH;
     /* TODO: Check permissions */
     if (sig == 0)
         return 0;
     if (pid == 0)
     {
         bool found = false;
         Signals nSig = ConvertSignalToNative(sig);
         assert(nSig != SIG_NULL);
         foreach (auto proc in pcb->GetContext()->GetProcessList())
         {
             if (proc->Security.ProcessGroupID == thisProcess->Security.ProcessGroupID)
             {
                 debug("Sending signal %s to %s(%d)", lSigStr[sig], proc->Name, proc->ID);
                 proc->SendSignal(nSig);
                 found = true;
             }
         }
         if (!found)
             return -linux_ESRCH;
         return 0;
     }
     if (pid == -1)
     {
         fixme("Sending signal %d to all processes except init", sig);
         return -linux_ENOSYS;
     }
     if (pid < -1)
     {
         fixme("Sending signal %d to process group %d", sig, pid);
         return -linux_ENOSYS;
     }
     Signals nSig = ConvertSignalToNative(sig);
     assert(nSig != SIG_NULL);
     return ConvertErrnoToLinux(pcb->SendSignal(nSig));
 }
References assert, ConvertErrnoToLinux(), ConvertSignalToNative(), debug, fixme, Tasking::PCB::GetContext(), Tasking::Task::GetProcessList(), linux_ENOSYS, linux_ESRCH, pcb, Tasking::PCB::SendSignal(), SIG_NULL, and thisProcess.
linux_lseek()
static off_t linux_lseek (SysFrm * , int fd, off_t offset, int whence) static
Definition at line 892 of file syscall.cpp.
 {
     static_assert(linux_SEEK_SET == SEEK_SET);
     static_assert(linux_SEEK_CUR == SEEK_CUR);
     static_assert(linux_SEEK_END == SEEK_END);
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return ConvertErrnoToLinux(fdt->usr_lseek(fd, offset, whence));
 }
References ConvertErrnoToLinux(), fd, fdt, Tasking::PCB::FileDescriptors, linux_SEEK_CUR, linux_SEEK_END, linux_SEEK_SET, pcb, SEEK_CUR, SEEK_END, SEEK_SET, static_assert, thisProcess, and vfs::FileDescriptorTable::usr_lseek().
linux_lstat()
static int linux_lstat (SysFrm * , const char * pathname, struct linux_kstat * statbuf) static
Definition at line 873 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pPathname = vma->UserCheckAndGetAddress(pathname, PAGE_SIZE);
     auto pStatbuf = vma->UserCheckAndGetAddress(statbuf);
     if (pPathname == nullptr || pStatbuf == nullptr)
         return -linux_EFAULT;
     struct kstat nstat = KStatToStat(*pStatbuf);
     int ret = ConvertErrnoToLinux(fdt->usr_lstat(pPathname, &nstat));
     *pStatbuf = StatToKStat(nstat);
     return ret;
 }
References ConvertErrnoToLinux(), fdt, Tasking::PCB::FileDescriptors, KStatToStat(), linux_EFAULT, PAGE_SIZE, pathname, pcb, pPathname, ret, StatToKStat(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_lstat(), Tasking::PCB::vma, and vma.
linux_madvise()
static int linux_madvise (SysFrm * , void * addr, size_t length, int advice) static
Definition at line 1290 of file syscall.cpp.
 {
     // PCB *pcb = thisProcess;
     // Memory::VirtualMemoryArea *vma = pcb->vma;
     /* TODO: For now we ignore the advice and just return 0 */
     /* "man 2 madvise" for more info */
     stub;
     return 0;
 }
References stub.
linux_mkdir()
static int linux_mkdir (SysFrm * , const char * pathname, mode_t mode) static
Definition at line 2292 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     fixme("semi-stub");
     const char *pPathname = vma->UserCheckAndGetAddress(pathname);
     if (!pPathname)
         return -linux_EFAULT;
     mode &= ~pcb->FileCreationMask & 0777;
     FileNode *n = fs->Create(pcb->CWD, pPathname, mode);
     if (!n)
         return -linux_EEXIST;
     return 0;
 }
References vfs::Virtual::Create(), Tasking::PCB::CWD, Tasking::PCB::FileCreationMask, fixme, fs, linux_EEXIST, linux_EFAULT, n, pathname, pcb, pPathname, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_mmap()
static void* linux_mmap (SysFrm * , void * addr, size_t length, int prot, int flags, int fildes, off_t offset) static
Definition at line 903 of file syscall.cpp.
 {
     if (length == 0)
         return (void *)-linux_EINVAL;
     bool p_None = prot & linux_PROT_NONE;
     bool p_Read = prot & linux_PROT_READ;
     bool p_Write = prot & linux_PROT_WRITE;
     bool p_Exec = prot & linux_PROT_EXEC;
     bool m_Shared = flags & linux_MAP_SHARED;
     bool m_Private = flags & linux_MAP_PRIVATE;
     bool m_Fixed = flags & linux_MAP_FIXED;
     bool m_Anon = flags & linux_MAP_ANONYMOUS;
     UNUSED(p_None);
     UNUSED(m_Anon);
     debug("None:%d Read:%d Write:%d Exec:%d",
           p_None, p_Read, p_Write, p_Exec);
     debug("Shared:%d Private:%d Fixed:%d Anon:%d",
           m_Shared, m_Private, m_Fixed, m_Anon);
     int unknownFlags = flags & ~(linux_MAP_SHARED | linux_MAP_PRIVATE |
                                  linux_MAP_FIXED | linux_MAP_ANONYMOUS);
     if (unknownFlags)
     {
         /* We still have some flags missing afaik... */
         fixme("Unknown flags: %x", unknownFlags);
         /* FIXME: Continue? */
     }
     if (offset % PAGE_SIZE)
         return (void *)-linux_EINVAL;
     if (uintptr_t(addr) % PAGE_SIZE && m_Fixed)
         return (void *)-linux_EINVAL;
     if ((m_Shared && m_Private) ||
         (!m_Shared && !m_Private))
         return (void *)-linux_EINVAL;
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     if (fildes != -1 && !m_Anon)
     {
         fixme("File mapping not fully implemented");
         vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
         auto _fd = fdt->FileMap.find(fildes);
         if (_fd == fdt->FileMap.end())
         {
             debug("Invalid file descriptor %d", fildes);
             return (void *)-linux_EBADF;
         }
         if (p_Read)
         {
             void *pBuf = vma->RequestPages(TO_PAGES(length));
             debug("created buffer at %#lx-%#lx",
                   pBuf, (uintptr_t)pBuf + length);
             uintptr_t mFlags = Memory::US;
             if (p_Write)
                 mFlags |= Memory::RW;
             if (m_Fixed)
             {
                 if (m_Shared)
                     return (void *)-linux_ENOSYS;
                 int mRet = vma->Map(addr, pBuf, length, mFlags);
                 if (mRet < 0)
                 {
                     debug("Failed to map file: %s", strerror(mRet));
                     return (void *)(uintptr_t)ConvertErrnoToLinux(mRet);
                 }
                 off_t oldOff = fdt->usr_lseek(fildes, 0, SEEK_CUR);
                 fdt->usr_lseek(fildes, offset, SEEK_SET);
                 ssize_t ret = fdt->usr_read(fildes, pBuf, length);
                 fdt->usr_lseek(fildes, oldOff, SEEK_SET);
                 if (ret < 0)
                 {
                     debug("Failed to read file");
                     return (void *)ConvertErrnoToLinux(ret);
                 }
                 return addr;
             }
             else
             {
                 int mRet = vma->Map(pBuf, pBuf, length, mFlags);
                 if (mRet < 0)
                 {
                     debug("Failed to map file: %s", strerror(mRet));
                     return (void *)(uintptr_t)ConvertErrnoToLinux(mRet);
                 }
             }
             off_t oldOff = fdt->usr_lseek(fildes, 0, SEEK_CUR);
             fdt->usr_lseek(fildes, offset, SEEK_SET);
             ssize_t ret = fdt->usr_read(fildes, pBuf, length);
             fdt->usr_lseek(fildes, oldOff, SEEK_SET);
             if (ret < 0)
             {
                 debug("Failed to read file");
                 return (void *)ConvertErrnoToLinux(ret);
             }
             return pBuf;
         }
         debug("???");
         return (void *)-linux_ENOSYS;
     }
     void *ret = vma->CreateCoWRegion(addr, length,
                                      p_Read, p_Write, p_Exec,
                                      m_Fixed, m_Shared);
     debug("ret: %#lx", ret);
     return (void *)ret;
 }
References addr, ConvertErrnoToLinux(), Memory::VirtualMemoryArea::CreateCoWRegion(), debug, fdt, fildes, Tasking::PCB::FileDescriptors, vfs::FileDescriptorTable::FileMap, fixme, linux_EBADF, linux_EINVAL, linux_ENOSYS, linux_MAP_ANONYMOUS, linux_MAP_FIXED, linux_MAP_PRIVATE, linux_MAP_SHARED, linux_PROT_EXEC, linux_PROT_NONE, linux_PROT_READ, linux_PROT_WRITE, Memory::VirtualMemoryArea::Map(), off_t, PAGE_SIZE, pcb, Memory::VirtualMemoryArea::RequestPages(), ret, Memory::RW, SEEK_CUR, SEEK_SET, strerror(), thisProcess, TO_PAGES, UNUSED, Memory::US, vfs::FileDescriptorTable::usr_lseek(), vfs::FileDescriptorTable::usr_read(), Tasking::PCB::vma, and vma.
linux_mprotect()
static int linux_mprotect (SysFrm * , void * addr, size_t len, int prot) static
Definition at line 1032 of file syscall.cpp.
 {
     if (len == 0)
         return -linux_EINVAL;
     if (uintptr_t(addr) % PAGE_SIZE)
         return -linux_EINVAL;
     // bool p_None = prot & linux_PROT_NONE;
     bool p_Read = prot & linux_PROT_READ;
     bool p_Write = prot & linux_PROT_WRITE;
     // bool p_Exec = prot & linux_PROT_EXEC;
     PCB *pcb = thisProcess;
     Memory::Virtual vmm = Memory::Virtual(pcb->PageTable);
     for (uintptr_t i = uintptr_t(addr);
          i < uintptr_t(addr) + len;
          i += PAGE_SIZE)
     {
         if (unlikely(vmm.Check((void *)i, Memory::G)))
         {
             warn("%p is a global page", (void *)i);
             return -linux_ENOMEM;
         }
         Memory::PageTableEntry *pte = vmm.GetPTE(addr);
         if (pte == nullptr)
         {
             debug("Page %#lx is not mapped inside %#lx",
                   (void *)i, pcb->PageTable);
             fixme("Page %#lx is not mapped", (void *)i);
             continue;
             return -linux_ENOMEM;
         }
         if (!pte->Present ||
             (!pte->UserSupervisor && p_Read) ||
             (!pte->ReadWrite && p_Write))
         {
             debug("Page %p is not mapped with the correct permissions",
                   (void *)i);
             return -linux_EACCES;
         }
         // pte->Present = !p_None;
         pte->UserSupervisor = p_Read;
         pte->ReadWrite = p_Write;
         // pte->ExecuteDisable = p_Exec;
         debug("Changed permissions of page %#lx to %s %s %s %s",
               (void *)i,
               (prot & linux_PROT_NONE) ? "None" : "",
               p_Read ? "Read" : "",
               p_Write ? "Write" : "",
               (prot & linux_PROT_EXEC) ? "Exec" : "");
 #if defined(a64)
         CPU::x64::invlpg(addr);
 #elif defined(a32)
         CPU::x32::invlpg(addr);
 #elif defined(aa64)
         asmv("dsb sy");
         asmv("tlbi vae1is, %0"
              :
              : "r"(addr)
              : "memory");
         asmv("dsb sy");
         asmv("isb");
 #endif
     }
     return 0;
 }
References addr, asmv(), Memory::Virtual::Check(), debug, fixme, Memory::G, Memory::Virtual::GetPTE(), i, CPU::x32::invlpg(), CPU::x64::invlpg(), len, linux_EACCES, linux_EINVAL, linux_ENOMEM, linux_PROT_EXEC, linux_PROT_NONE, linux_PROT_READ, linux_PROT_WRITE, PAGE_SIZE, Tasking::PCB::PageTable, pcb, thisProcess, unlikely, and warn.
linux_munmap()
static int linux_munmap (SysFrm * , void * addr, size_t length) static
Definition at line 1107 of file syscall.cpp.
 {
     if (uintptr_t(addr) % PAGE_SIZE)
         return -linux_EINVAL;
     if (length == 0)
         return -linux_EINVAL;
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     vma->FreePages((void *)addr, TO_PAGES(length));
     return 0;
 }
References addr, Memory::VirtualMemoryArea::FreePages(), linux_EINVAL, PAGE_SIZE, pcb, thisProcess, TO_PAGES, Tasking::PCB::vma, and vma.
linux_nanosleep()
static int linux_nanosleep (SysFrm * , const struct timespec * req, struct timespec * rem) static
Definition at line 1320 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pReq = vma->UserCheckAndGetAddress(req);
     auto pRem = vma->UserCheckAndGetAddress(rem);
     if (pReq == nullptr || pRem == nullptr)
         return -linux_EFAULT;
     if (pReq->tv_nsec < 0 || pReq->tv_nsec > 999999999)
     {
         debug("Invalid tv_nsec %ld", pReq->tv_nsec);
         return -linux_EINVAL;
     }
     if (pReq->tv_sec < 0)
     {
         debug("Invalid tv_sec %ld", pReq->tv_sec);
         return -linux_EINVAL;
     }
     debug("tv_nsec=%ld tv_sec=%ld",
           pReq->tv_nsec, pReq->tv_sec);
     uint64_t nanoTime = pReq->tv_nsec;
     uint64_t secTime = pReq->tv_sec * 1000000000; /* Nano */
     uint64_t time = TimeManager->GetCounter();
     uint64_t sleepTime = TimeManager->CalculateTarget(nanoTime + secTime, Time::Nanoseconds);
     debug("time=%ld secTime=%ld nanoTime=%ld sleepTime=%ld",
           time, secTime, nanoTime, sleepTime);
     while (time < sleepTime)
     {
         if (pcb->Signals.HasPendingSignal())
         {
             debug("sleep interrupted by signal");
             return -linux_EINTR;
         }
         pcb->GetContext()->Yield();
         time = TimeManager->GetCounter();
     }
     debug("time=     %ld", time);
     debug("sleepTime=%ld", sleepTime);
     if (rem)
     {
         pRem->tv_sec = 0;
         pRem->tv_nsec = 0;
     }
     return 0;
 }
References Time::time::CalculateTarget(), debug, Tasking::PCB::GetContext(), Time::time::GetCounter(), Tasking::Signal::HasPendingSignal(), linux_EFAULT, linux_EINTR, linux_EINVAL, Time::Nanoseconds, pcb, Tasking::PCB::Signals, thisProcess, time(), TimeManager, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, and Tasking::Task::Yield().
linux_newfstatat()
static long linux_newfstatat (SysFrm * , int dirfd, const char * pathname, struct linux_kstat * statbuf, int flag) static
Definition at line 3115 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     if (flag)
         fixme("flag %#x is stub", flag);
     const char *pPathname = vma->UserCheckAndGetAddress(pathname);
     struct linux_kstat *pStatbuf = vma->UserCheckAndGetAddress(statbuf);
     if (pPathname == nullptr || pStatbuf == nullptr)
         return -linux_EFAULT;
     debug("\"%s\" %#lx %#lx", pPathname, pathname, statbuf);
     if (fs->PathIsAbsolute(pPathname))
     {
         debug("path \"%s\" is absolute", pPathname);
         struct kstat nstat = KStatToStat(*pStatbuf);
         int ret = fdt->usr_stat(pPathname, &nstat);
         *pStatbuf = StatToKStat(nstat);
         return ConvertErrnoToLinux(ret);
     }
     switch (dirfd)
     {
     case linux_AT_FDCWD:
     {
         debug("dirfd is AT_FDCWD for \"%s\"", pPathname);
         FileNode *node = fs->GetByPath(pPathname, pcb->CWD);
         if (!node)
             return -linux_ENOENT;
         struct kstat nstat = {};
         int ret = fdt->usr_stat(node->GetPath().c_str(), &nstat);
         *pStatbuf = StatToKStat(nstat);
         return ConvertErrnoToLinux(ret);
     }
     default:
     {
         debug("dirfd is %d for \"%s\"", dirfd, pPathname);
         auto it = fdt->FileMap.find(dirfd);
         if (it == fdt->FileMap.end())
             ReturnLogError(-linux_EBADF, "Invalid fd %d", dirfd);
         vfs::FileDescriptorTable::Fildes &fildes = it->second;
         FileNode *node = fs->GetByPath(pPathname, fildes.Node);
         debug("node: %s", node->GetPath().c_str());
         if (!node)
             return -linux_ENOENT;
         struct kstat nstat = {};
         int ret = fdt->usr_stat(node->GetPath().c_str(), &nstat);
         *pStatbuf = StatToKStat(nstat);
         return ConvertErrnoToLinux(ret);
     }
     }
 }
References ConvertErrnoToLinux(), Tasking::PCB::CWD, debug, dirfd, fdt, fildes, Tasking::PCB::FileDescriptors, vfs::FileDescriptorTable::FileMap, fixme, fs, vfs::Virtual::GetByPath(), it, KStatToStat(), linux_AT_FDCWD, linux_EBADF, linux_EFAULT, linux_ENOENT, vfs::FileDescriptorTable::Fildes::Node, vfs::Virtual::PathIsAbsolute(), pathname, pcb, pPathname, ret, ReturnLogError, StatToKStat(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_stat(), Tasking::PCB::vma, and vma.
linux_open()
static int linux_open (SysFrm * sf, const char * pathname, int flags, mode_t mode) static
Definition at line 794 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const char *pPathname = vma->UserCheckAndGetAddress(pathname, PAGE_SIZE);
     if (pPathname == nullptr)
         return -linux_EFAULT;
     func("%s, %d, %d", pPathname, flags, mode);
     if (flags & 0200000 /* O_DIRECTORY */)
     {
         FileNode *node = fs->GetByPath(pPathname, pcb->CWD);
         if (node == nullptr)
         {
             debug("Couldn't find %s", pPathname);
             return -linux_ENOENT;
         }
         if (!node->IsDirectory())
         {
             debug("%s is not a directory", pPathname);
             return -linux_ENOTDIR;
         }
     }
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return ConvertErrnoToLinux(fdt->usr_open(pPathname, flags, mode));
 }
References ConvertErrnoToLinux(), Tasking::PCB::CWD, debug, fdt, Tasking::PCB::FileDescriptors, fs, func(), vfs::Virtual::GetByPath(), linux_EFAULT, linux_ENOENT, linux_ENOTDIR, PAGE_SIZE, pathname, pcb, pPathname, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_open(), Tasking::PCB::vma, and vma.
linux_openat()
static int linux_openat (SysFrm * , int dirfd, const char * pathname, int flags, mode_t mode) static
Definition at line 3082 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const char *pPathname = vma->UserCheckAndGetAddress(pathname);
     if (pPathname == nullptr)
         return -linux_EFAULT;
     debug("dirfd=%d pathname=%s flags=%#x mode=%#x",
           dirfd, pPathname, flags, mode);
     if (dirfd == linux_AT_FDCWD)
     {
         FileNode *absoluteNode = fs->GetByPath(pPathname, pcb->CWD);
         if (!absoluteNode)
             return -linux_ENOENT;
         const char *absPath = new char[strlen(absoluteNode->Path.c_str()) + 1];
         strcpy((char *)absPath, absoluteNode->Path.c_str());
         int ret = fdt->usr_open(absPath, flags, mode);
         delete[] absPath;
         return ConvertErrnoToLinux(ret);
     }
     if (!fs->PathIsRelative(pPathname))
         return fdt->usr_open(pPathname, flags, mode);
     fixme("dirfd=%d is stub", dirfd);
     return -linux_ENOSYS;
 }
References ConvertErrnoToLinux(), Tasking::PCB::CWD, debug, dirfd, fdt, Tasking::PCB::FileDescriptors, fixme, fs, vfs::Virtual::GetByPath(), linux_AT_FDCWD, linux_EFAULT, linux_ENOENT, linux_ENOSYS, FileNode::Path, vfs::Virtual::PathIsRelative(), pathname, pcb, pPathname, ret, strcpy, strlen, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_open(), Tasking::PCB::vma, and vma.
linux_pause()
static int linux_pause (SysFrm *) static
Definition at line 1314 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     return ConvertErrnoToLinux(pcb->Signals.WaitAnySignal());
 }
References ConvertErrnoToLinux(), pcb, Tasking::PCB::Signals, thisProcess, and Tasking::Signal::WaitAnySignal().
linux_pipe()
static int linux_pipe (SysFrm * , int pipefd[2]) static
Definition at line 1279 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     int *pPipefd = vma->UserCheckAndGetAddress(pipefd);
     debug("pipefd=%#lx", pPipefd);
     fixme("pipefd=[%d, %d]", pPipefd[0], pPipefd[1]);
     return -linux_ENOSYS;
 }
References debug, fixme, linux_ENOSYS, pcb, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
Referenced by linux_pipe2().
linux_pipe2()
static int linux_pipe2 (SysFrm * sf, int pipefd[2], int flags) static
Definition at line 3176 of file syscall.cpp.
 {
     if (flags == 0)
         return linux_pipe(sf, pipefd);
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     int *pPipefd = vma->UserCheckAndGetAddress(pipefd);
     if (pPipefd == nullptr)
         return -linux_EFAULT;
     debug("pipefd=%#lx", pPipefd);
     fixme("pipefd=[%d, %d] flags=%#x", pPipefd[0], pPipefd[1], flags);
     return -linux_ENOSYS;
 }
References debug, fixme, linux_EFAULT, linux_ENOSYS, linux_pipe(), pcb, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_pread64()
static ssize_t linux_pread64 (SysFrm * , int fd, void * buf, size_t count, off_t offset) static
Definition at line 1143 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     void *pBuf = vma->UserCheckAndGetAddress(buf, count);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     off_t oldOff = fdt->usr_lseek(fd, 0, SEEK_CUR);
     fdt->usr_lseek(fd, offset, SEEK_SET);
     ssize_t ret = fdt->usr_read(fd, pBuf, count);
     fdt->usr_lseek(fd, oldOff, SEEK_SET);
     return ConvertErrnoToLinux(ret);
 }
References buf, ConvertErrnoToLinux(), count, fd, fdt, Tasking::PCB::FileDescriptors, linux_EFAULT, off_t, pcb, ret, SEEK_CUR, SEEK_SET, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_lseek(), vfs::FileDescriptorTable::usr_read(), Tasking::PCB::vma, and vma.
linux_prlimit64()
static int linux_prlimit64 (SysFrm * , pid_t pid, int resource, const struct rlimit * new_limit, struct rlimit * old_limit) static
Definition at line 3193 of file syscall.cpp.
 {
     static_assert(sizeof(struct rlimit) < PAGE_SIZE);
     PCB *pcb = nullptr;
     if (likely(pid == 0))
         pcb = thisProcess;
     else
     {
         pcb = thisProcess->GetContext()->GetProcessByID(pid);
         if (pcb == nullptr)
             return -linux_ESRCH;
         fixme("implement CAP_SYS_RESOURCE");
         return -linux_EPERM;
     }
     Memory::VirtualMemoryArea *vma = thisProcess->vma;
     auto pOldLimit = vma->UserCheckAndGetAddress(old_limit);
     auto pNewLimit = vma->UserCheckAndGetAddress(new_limit);
     if (pOldLimit == nullptr && old_limit != nullptr)
         return -linux_EFAULT;
     if (pNewLimit == nullptr && new_limit != nullptr)
         return -linux_EFAULT;
     if (new_limit)
     {
         if (pNewLimit->rlim_cur > pNewLimit->rlim_max)
             return -linux_EINVAL;
     }
     switch (resource)
     {
     case linux_RLIMIT_CPU:
     case linux_RLIMIT_FSIZE:
     case linux_RLIMIT_DATA:
     case linux_RLIMIT_STACK:
     case linux_RLIMIT_CORE:
     case linux_RLIMIT_RSS:
         goto __stub;
     case linux_RLIMIT_NPROC:
     {
         if (old_limit)
         {
             pOldLimit->rlim_cur = pcb->SoftLimits.Threads;
             pOldLimit->rlim_max = pcb->HardLimits.Threads;
             debug("read NPROC limit: {%#lx, %#lx}", pOldLimit->rlim_cur, pOldLimit->rlim_max);
         }
         if (new_limit)
         {
             if (pNewLimit->rlim_max > pcb->HardLimits.Threads && !pcb->Security.CanAdjustHardLimits)
                 return -linux_EPERM;
             debug("setting NPROC limit to {%#lx, %#lx}->{%#lx, %#lx}",
                   pcb->SoftLimits.Threads, pcb->HardLimits.Threads,
                   pNewLimit->rlim_cur, pNewLimit->rlim_max);
             pcb->SoftLimits.Threads = pNewLimit->rlim_cur;
             pcb->HardLimits.Threads = pNewLimit->rlim_max;
         }
         return 0;
     }
     case linux_RLIMIT_NOFILE:
     {
         if (old_limit)
         {
             pOldLimit->rlim_cur = pcb->SoftLimits.OpenFiles;
             pOldLimit->rlim_max = pcb->HardLimits.OpenFiles;
             debug("read NOFILE limit: {%#lx, %#lx}", pOldLimit->rlim_cur, pOldLimit->rlim_max);
         }
         if (new_limit)
         {
             if (pNewLimit->rlim_max > pcb->HardLimits.OpenFiles && !pcb->Security.CanAdjustHardLimits)
                 return -linux_EPERM;
             debug("setting NOFILE limit to {%#lx, %#lx}->{%#lx, %#lx}",
                   pcb->SoftLimits.OpenFiles, pcb->HardLimits.OpenFiles,
                   pNewLimit->rlim_cur, pNewLimit->rlim_max);
             pcb->SoftLimits.OpenFiles = pNewLimit->rlim_cur;
             pcb->HardLimits.OpenFiles = pNewLimit->rlim_max;
         }
         return 0;
     }
     case linux_RLIMIT_MEMLOCK:
         goto __stub;
     case linux_RLIMIT_AS:
     {
         if (old_limit)
         {
             pOldLimit->rlim_cur = pcb->SoftLimits.Memory;
             pOldLimit->rlim_max = pcb->HardLimits.Memory;
             debug("read AS limit: {%#lx, %#lx}", pOldLimit->rlim_cur, pOldLimit->rlim_max);
         }
         if (new_limit)
         {
             if (pNewLimit->rlim_max > pcb->HardLimits.Memory && !pcb->Security.CanAdjustHardLimits)
                 return -linux_EPERM;
             debug("setting AS limit to {%#lx, %#lx}->{%#lx, %#lx}",
                   pcb->SoftLimits.Memory, pcb->HardLimits.Memory,
                   pNewLimit->rlim_cur, pNewLimit->rlim_max);
             pcb->SoftLimits.Memory = pNewLimit->rlim_cur;
             pcb->HardLimits.Memory = pNewLimit->rlim_max;
         }
         return 0;
     }
     case linux_RLIMIT_LOCKS:
     case linux_RLIMIT_SIGPENDING:
     case linux_RLIMIT_MSGQUEUE:
     case linux_RLIMIT_NICE:
     case linux_RLIMIT_RTPRIO:
     case linux_RLIMIT_RTTIME:
     case linux_RLIMIT_NLIMITS:
     __stub:
     {
         fixme("resource %s(%d) is stub", rlimitStr[resource], resource);
         return 0; /* just return 0 */
     }
     default:
     {
         debug("Invalid resource %d", resource);
         return -linux_EINVAL;
     }
     }
 }
References debug, fixme, Tasking::PCB::HardLimits, likely, linux_EFAULT, linux_EINVAL, linux_EPERM, linux_ESRCH, linux_RLIMIT_AS, linux_RLIMIT_CORE, linux_RLIMIT_CPU, linux_RLIMIT_DATA, linux_RLIMIT_FSIZE, linux_RLIMIT_LOCKS, linux_RLIMIT_MEMLOCK, linux_RLIMIT_MSGQUEUE, linux_RLIMIT_NICE, linux_RLIMIT_NLIMITS, linux_RLIMIT_NOFILE, linux_RLIMIT_NPROC, linux_RLIMIT_RSS, linux_RLIMIT_RTPRIO, linux_RLIMIT_RTTIME, linux_RLIMIT_SIGPENDING, linux_RLIMIT_STACK, PAGE_SIZE, pcb, rlimitStr, Tasking::PCB::Security, Tasking::PCB::SoftLimits, static_assert, thisProcess, Tasking::PCB::Threads, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), and vma.
linux_pwrite64()
static ssize_t linux_pwrite64 (SysFrm * , int fd, const void * buf, size_t count, off_t offset) static
Definition at line 1160 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const void *pBuf = vma->UserCheckAndGetAddress(buf, count);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     off_t oldOff = fdt->usr_lseek(fd, 0, SEEK_CUR);
     fdt->usr_lseek(fd, offset, SEEK_SET);
     ssize_t ret = fdt->usr_write(fd, pBuf, count);
     fdt->usr_lseek(fd, oldOff, SEEK_SET);
     return ConvertErrnoToLinux(ret);
 }
References buf, ConvertErrnoToLinux(), count, fd, fdt, Tasking::PCB::FileDescriptors, linux_EFAULT, off_t, pcb, ret, SEEK_CUR, SEEK_SET, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_lseek(), vfs::FileDescriptorTable::usr_write(), Tasking::PCB::vma, and vma.
linux_read()
static ssize_t linux_read (SysFrm * , int fd, void * buf, size_t count) static
Definition at line 750 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     void *pBuf = vma->UserCheckAndGetAddress(buf, count);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     func("%d, %p, %d", fd, buf, count);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = ConvertErrnoToLinux(fdt->usr_read(fd, pBuf, count));
     if (ret >= 0)
         fdt->usr_lseek(fd, ret, SEEK_CUR);
 #ifdef DEBUG
     DumpData("READ", pBuf, ret < 0 ? 0 : ret);
 #endif
     return ret;
 }
References buf, ConvertErrnoToLinux(), count, DumpData(), fd, fdt, Tasking::PCB::FileDescriptors, func(), linux_EFAULT, pcb, ret, SEEK_CUR, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_lseek(), vfs::FileDescriptorTable::usr_read(), Tasking::PCB::vma, and vma.
Referenced by linux_readv().
linux_readlink()
static ssize_t linux_readlink (SysFrm * , const char * pathname, char * buf, size_t bufsiz) static
Definition at line 2310 of file syscall.cpp.
 {
     if (!pathname || !buf)
         return -linux_EINVAL;
     if (bufsiz > PAGE_SIZE)
     {
         warn("bufsiz is too large: %ld", bufsiz);
         return -linux_EINVAL;
     }
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const char *pPath = vma->UserCheckAndGetAddress(pathname);
     char *pBuf = vma->UserCheckAndGetAddress(buf);
     if (pPath == nullptr || pBuf == nullptr)
         return -linux_EFAULT;
     func("%s %#lx %ld", pPath, buf, bufsiz);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->usr_open(pPath, O_RDONLY, 0);
     if (fd < 0)
         return -linux_ENOENT;
     auto it = fdt->FileMap.find(fd);
     if (it == fdt->FileMap.end())
         ReturnLogError(-linux_EBADF, "Invalid fd %d", fd);
     vfs::FileDescriptorTable::Fildes &fildes = it->second;
     FileNode *node = fildes.Node;
     fdt->usr_close(fd);
     if (!node->IsSymbolicLink())
         return -linux_EINVAL;
     return ConvertErrnoToLinux(node->ReadLink(pBuf, bufsiz));
 }
References buf, ConvertErrnoToLinux(), fd, fdt, fildes, Tasking::PCB::FileDescriptors, vfs::FileDescriptorTable::FileMap, func(), it, linux_EBADF, linux_EFAULT, linux_EINVAL, linux_ENOENT, vfs::FileDescriptorTable::Fildes::Node, O_RDONLY, PAGE_SIZE, pathname, pcb, ReturnLogError, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_close(), vfs::FileDescriptorTable::usr_open(), Tasking::PCB::vma, vma, and warn.
linux_readv()
static ssize_t linux_readv (SysFrm * sf, int fildes, const struct iovec * iov, int iovcnt) static
Definition at line 1177 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const struct iovec *pIov = vma->UserCheckAndGetAddress(iov, sizeof(struct iovec) * iovcnt);
     if (pIov == nullptr)
         return -linux_EFAULT;
     ssize_t Total = 0;
     for (int i = 0; i < iovcnt; i++)
     {
         debug("%d: iov[%d]: %p %d", fildes, i, pIov[i].iov_base, pIov[i].iov_len);
         if (!pIov[i].iov_base)
         {
             debug("invalid iov_base");
             return -linux_EFAULT;
         }
         if (pIov[i].iov_len == 0)
         {
             debug("invalid iov_len");
             continue;
         }
         ssize_t n = linux_read(sf, fildes, pIov[i].iov_base, pIov[i].iov_len);
         if (n < 0)
             return ConvertErrnoToLinux(n);
         debug("n: %d", n);
         Total += n;
         if (n < (ssize_t)pIov[i].iov_len)
         {
             debug("break");
             break;
         }
     }
     debug("readv: %d", Total);
     return Total;
 }
References ConvertErrnoToLinux(), debug, fildes, i, iovec::iov_base, iovec::iov_len, linux_EFAULT, linux_read(), n, pcb, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_reboot()
static int linux_reboot (SysFrm * , int magic, int magic2, int cmd, void * arg) static
Definition at line 2570 of file syscall.cpp.
 {
     if (magic != linux_LINUX_REBOOT_MAGIC1 ||
         (magic2 != linux_LINUX_REBOOT_MAGIC2 &&
          magic2 != linux_LINUX_REBOOT_MAGIC2A &&
          magic2 != linux_LINUX_REBOOT_MAGIC2B &&
          magic2 != linux_LINUX_REBOOT_MAGIC2C))
     {
         warn("Invalid magic %#x %#x", magic, magic2);
         return -linux_EINVAL;
     }
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     debug("cmd=%#x arg=%#lx", cmd, arg);
     switch ((unsigned int)cmd)
     {
     case linux_LINUX_REBOOT_CMD_RESTART:
     {
         KPrint("Restarting system.");
         Tasking::Task *ctx = pcb->GetContext();
         ctx->CreateThread(ctx->GetKernelProcess(),
                           Tasking::IP(KST_Reboot))
             ->Rename("Restart");
         return 0;
     }
     case linux_LINUX_REBOOT_CMD_HALT:
     {
         KPrint("System halted.");
         pcb->GetContext()->Panic();
         CPU::Stop();
     }
     case linux_LINUX_REBOOT_CMD_POWER_OFF:
     {
         KPrint("Power down.");
         Tasking::Task *ctx = pcb->GetContext();
         ctx->CreateThread(ctx->GetKernelProcess(),
                           Tasking::IP(KST_Shutdown))
             ->Rename("Shutdown");
         return 0;
     }
     case linux_LINUX_REBOOT_CMD_RESTART2:
     {
         void *pArg = vma->__UserCheckAndGetAddress(arg, sizeof(void *));
         if (pArg == nullptr)
             return -linux_EFAULT;
         KPrint("Restarting system with command '%s'",
                (const char *)pArg);
         Tasking::Task *ctx = pcb->GetContext();
         ctx->CreateThread(ctx->GetKernelProcess(),
                           Tasking::IP(KST_Reboot))
             ->Rename("Restart");
         break;
     }
     case linux_LINUX_REBOOT_CMD_CAD_ON:
     case linux_LINUX_REBOOT_CMD_CAD_OFF:
     case linux_LINUX_REBOOT_CMD_SW_SUSPEND:
     case linux_LINUX_REBOOT_CMD_KEXEC:
     {
         fixme("cmd %#x not implemented", cmd);
         return -linux_ENOSYS;
     }
     default:
     {
         debug("Invalid cmd %#x", cmd);
         return -linux_EINVAL;
     }
     }
     return 0;
 }
References Memory::VirtualMemoryArea::__UserCheckAndGetAddress(), debug, fixme, Tasking::PCB::GetContext(), KPrint(), KST_Reboot(), KST_Shutdown(), linux_EFAULT, linux_EINVAL, linux_ENOSYS, linux_LINUX_REBOOT_CMD_CAD_OFF, linux_LINUX_REBOOT_CMD_CAD_ON, linux_LINUX_REBOOT_CMD_HALT, linux_LINUX_REBOOT_CMD_KEXEC, linux_LINUX_REBOOT_CMD_POWER_OFF, linux_LINUX_REBOOT_CMD_RESTART, linux_LINUX_REBOOT_CMD_RESTART2, linux_LINUX_REBOOT_CMD_SW_SUSPEND, linux_LINUX_REBOOT_MAGIC1, linux_LINUX_REBOOT_MAGIC2, linux_LINUX_REBOOT_MAGIC2A, linux_LINUX_REBOOT_MAGIC2B, linux_LINUX_REBOOT_MAGIC2C, Tasking::Task::Panic(), pcb, CPU::Stop(), thisProcess, Tasking::PCB::vma, vma, and warn.
linux_sched_getaffinity()
static int linux_sched_getaffinity (SysFrm * , pid_t pid, size_t cpusetsize, cpu_set_t * mask) static
Definition at line 2830 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     TCB *tcb;
     if (pid == 0)
         tcb = thisThread;
     else
         tcb = pcb->GetThread(pid);
     if (!tcb)
         return -linux_ESRCH;
     if (cpusetsize < sizeof(cpu_set_t))
         return -linux_EINVAL;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pMask = vma->UserCheckAndGetAddress(mask);
     if (pMask == nullptr && mask != nullptr)
         return -linux_EFAULT;
     CPU_ZERO(pMask);
     for (size_t i = 0; i < MAX_CPU && i < CPU_SETSIZE; ++i)
     {
         if (tcb->Info.Affinity[i])
             CPU_SET(i, pMask);
     }
     return 0;
 }
References Tasking::TaskInfo::Affinity, CPU_SET, CPU_SETSIZE, CPU_ZERO, Tasking::PCB::GetThread(), i, Tasking::TCB::Info, linux_EFAULT, linux_EINVAL, linux_ESRCH, MAX_CPU, pcb, thisProcess, thisThread, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_sched_setaffinity()
static int linux_sched_setaffinity (SysFrm * , pid_t pid, size_t cpusetsize, const cpu_set_t * mask) static
Definition at line 2786 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     TCB *tcb;
     if (pid == 0)
         tcb = thisThread;
     else
         tcb = pcb->GetThread(pid);
     if (!tcb)
         return -linux_ESRCH;
     if (cpusetsize < sizeof(cpu_set_t))
         return -linux_EINVAL;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pMask = vma->UserCheckAndGetAddress(mask);
     if (pMask == nullptr && mask != nullptr)
         return -linux_EFAULT;
     for (size_t i = 0; i < MAX_CPU && i < CPU_SETSIZE; ++i)
     {
         if (CPU_ISSET(i, pMask))
             tcb->Info.Affinity[i] = true;
         else
             tcb->Info.Affinity[i] = false;
     }
 #ifdef DEBUG
     for (size_t i = 0; i < MAX_CPU && i < CPU_SETSIZE; ++i)
     {
         bool isset = CPU_ISSET(i, pMask);
         bool affinity = tcb->Info.Affinity[i];
         if (isset != affinity)
         {
             fixme("sched_setaffinity check failed %d != %d (cpu %d)",
                   isset, affinity, i);
             assert(isset == affinity);
         }
     }
 #endif
     return 0;
 }
References Tasking::TaskInfo::Affinity, assert, CPU_ISSET, CPU_SETSIZE, fixme, Tasking::PCB::GetThread(), i, Tasking::TCB::Info, isset, linux_EFAULT, linux_EINVAL, linux_ESRCH, MAX_CPU, pcb, thisProcess, thisThread, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_set_tid_address()
static pid_t linux_set_tid_address (SysFrm * , int * tidptr) static
Definition at line 2861 of file syscall.cpp.
 {
     if (tidptr == nullptr)
         return -linux_EINVAL;
     Tasking::TCB *tcb = thisThread;
     tcb->Linux.clear_child_tid = tidptr;
     return tcb->ID;
 }
References Tasking::TCB::ID, Tasking::TCB::Linux, linux_EINVAL, and thisThread.
linux_setitimer()
static int linux_setitimer (SysFrm * , int which, const struct itimerspec64 * new_value, struct itimerspec64 * old_value) static
Definition at line 1384 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pNewValue = vma->UserCheckAndGetAddress(new_value);
     auto pOldValue = vma->UserCheckAndGetAddress(old_value);
     if (pNewValue == nullptr)
         return -linux_EFAULT;
     if (pOldValue == nullptr && old_value)
         return -linux_EFAULT;
     switch (which)
     {
     case linux_ITIMER_REAL:
     {
         fixme("ITIMER_REAL not implemented");
         return 0;
     }
     case linux_ITIMER_VIRTUAL:
     {
         fixme("ITIMER_VIRTUAL not implemented");
         return 0;
     }
     case linux_ITIMER_PROF:
     {
         fixme("ITIMER_PROF not implemented");
         return 0;
     }
     default:
         return -linux_EINVAL;
     }
     return 0;
 }
References fixme, linux_EFAULT, linux_EINVAL, linux_ITIMER_PROF, linux_ITIMER_REAL, linux_ITIMER_VIRTUAL, pcb, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
linux_setpgid()
static int linux_setpgid (SysFrm * , pid_t pid, pid_t pgid) static
Definition at line 2469 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     if (pid == 0)
     {
         pcb->Security.ProcessGroupID = pgid;
         return 0;
     }
     PCB *target = pcb->GetContext()->GetProcessByID(pid);
     if (!target)
         return -linux_ESRCH;
     if (pgid == 0)
     {
         target->Security.ProcessGroupID = target->ID;
         return 0;
     }
     target->Security.ProcessGroupID = pgid;
     return 0;
 }
References Tasking::PCB::GetContext(), Tasking::Task::GetProcessByID(), Tasking::PCB::ID, linux_ESRCH, pcb, Tasking::PCB::Security, and thisProcess.
linux_shutdown()
static int linux_shutdown (SysFrm * , int sockfd, int how) static
Definition at line 1423 of file syscall.cpp.
 {
     stub;
     return -linux_ENOSYS;
 }
References linux_ENOSYS, and stub.
linux_sigaction()
static int linux_sigaction (SysFrm * , int signum, const k_sigaction * act, k_sigaction * oldact, size_t sigsetsize) static
Definition at line 2647 of file syscall.cpp.
 {
     if (signum < 1 || signum > linux_SIGRTMAX ||
         signum == linux_SIGKILL || signum == linux_SIGSTOP)
     {
         debug("Invalid signal %d", signum);
         return -linux_EINVAL;
     }
     if (sigsetsize != sizeof(sigset_t))
     {
         warn("Unsupported sigsetsize %d!", sigsetsize);
         return -linux_EINVAL;
     }
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     debug("signum=%d act=%#lx oldact=%#lx", signum, act, oldact);
     if (vma->UserCheck(act) < 0 && act != nullptr)
         return -linux_EFAULT;
     if (vma->UserCheck(oldact) < 0 && oldact != nullptr)
         return -linux_EFAULT;
     auto pAct = pcb->PageTable->Get(act);
     auto pOldact = pcb->PageTable->Get(oldact);
     int ret = 0;
     if (pOldact)
     {
         Signals nSig = ConvertSignalToNative(signum);
         assert(nSig != SIG_NULL);
         SignalAction nSA{};
         SetSigActToNative(pOldact, &nSA);
         ret = pcb->Signals.GetAction(nSig, &nSA);
         SetSigActToLinux(&nSA, pOldact);
     }
     if (unlikely(ret < 0))
         return ConvertErrnoToLinux(ret);
     if (pAct)
     {
         if (pAct->flags & linux_SA_IMMUTABLE)
         {
             warn("Immutable signal %d", signum);
             return -linux_EINVAL;
         }
         Signals nSig = ConvertSignalToNative(signum);
         assert(nSig != SIG_NULL);
         SignalAction nSA{};
         SetSigActToNative(pAct, &nSA);
         ret = pcb->Signals.SetAction(nSig, &nSA);
         SetSigActToLinux(&nSA, (k_sigaction *)pAct);
     }
     return ConvertErrnoToLinux(ret);
 }
References assert, ConvertErrnoToLinux(), ConvertSignalToNative(), debug, Memory::PageTable::Get(), Tasking::Signal::GetAction(), linux_EFAULT, linux_EINVAL, linux_SA_IMMUTABLE, linux_SIGKILL, linux_SIGRTMAX, linux_SIGSTOP, Tasking::PCB::PageTable, pcb, ret, Tasking::Signal::SetAction(), SetSigActToLinux(), SetSigActToNative(), SIG_NULL, Tasking::PCB::Signals, thisProcess, unlikely, Memory::VirtualMemoryArea::UserCheck(), Tasking::PCB::vma, vma, and warn.
linux_sigprocmask()
static int linux_sigprocmask (SysFrm * , int how, const sigset_t * set, sigset_t * oldset, size_t sigsetsize) static
Definition at line 2711 of file syscall.cpp.
 {
     static_assert(sizeof(sigset_t) < PAGE_SIZE);
     if (sigsetsize != sizeof(sigset_t))
     {
         warn("Unsupported sigsetsize %d!", sigsetsize);
         return -linux_EINVAL;
     }
     TCB *tcb = thisThread;
     PCB *pcb = tcb->Parent;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     if (vma->UserCheck(set) < 0 && set != nullptr)
         return -linux_EFAULT;
     if (vma->UserCheck(oldset) < 0 && oldset != nullptr)
         return -linux_EFAULT;
     const sigset_t *pSet = (const sigset_t *)pcb->PageTable->Get((void *)set);
     sigset_t *pOldset = (sigset_t *)pcb->PageTable->Get(oldset);
     debug("how=%#x set=%#lx oldset=%#lx",
           how, pSet ? *pSet : 0, pOldset ? *pOldset : 0);
     if (pOldset)
     {
         *pOldset = tcb->Signals.GetMask();
         *pOldset = ConvertMaskToLinux(*pOldset);
     }
     if (!pSet)
         return 0;
     sigset_t nativeSet = ConvertMaskToNative(*pSet);
     switch (how)
     {
     case SIG_BLOCK:
         tcb->Signals.Block(nativeSet);
         break;
     case SIG_UNBLOCK:
         tcb->Signals.Unblock(nativeSet);
         break;
     case SIG_SETMASK:
         tcb->Signals.SetMask(nativeSet);
         break;
     default:
         warn("Invalid how %#x", how);
         return -linux_EINVAL;
     }
     return 0;
 }
References Tasking::ThreadSignal::Block(), ConvertMaskToLinux(), ConvertMaskToNative(), debug, Memory::PageTable::Get(), Tasking::ThreadSignal::GetMask(), linux_EFAULT, linux_EINVAL, PAGE_SIZE, Tasking::PCB::PageTable, Tasking::TCB::Parent, pcb, Tasking::ThreadSignal::SetMask(), SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK, Tasking::TCB::Signals, static_assert, thisThread, Tasking::ThreadSignal::Unblock(), Memory::VirtualMemoryArea::UserCheck(), Tasking::PCB::vma, vma, and warn.
linux_sigreturn()
static void linux_sigreturn (SysFrm * sf) static
Definition at line 2765 of file syscall.cpp.
 {
     thisProcess->Signals.RestoreHandleSignal(sf, thisThread);
 }
References thisProcess, and thisThread.
linux_stat()
static int linux_stat (SysFrm * , const char * pathname, struct linux_kstat * statbuf) static
Definition at line 837 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pPathname = vma->UserCheckAndGetAddress(pathname, PAGE_SIZE);
     if (pPathname == nullptr)
         return -linux_EFAULT;
     auto pStatbuf = vma->UserCheckAndGetAddress(statbuf);
     if (pStatbuf == nullptr)
         return -linux_EFAULT;
     struct kstat nstat = KStatToStat(*pStatbuf);
     int ret = ConvertErrnoToLinux(fdt->usr_stat(pPathname, &nstat));
     *pStatbuf = StatToKStat(nstat);
     return ret;
 }
References ConvertErrnoToLinux(), fdt, Tasking::PCB::FileDescriptors, KStatToStat(), linux_EFAULT, PAGE_SIZE, pathname, pcb, pPathname, ret, StatToKStat(), thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_stat(), Tasking::PCB::vma, and vma.
linux_tgkill()
static int linux_tgkill (SysFrm * sf, pid_t tgid, pid_t tid, int sig) static
Definition at line 3055 of file syscall.cpp.
 {
     Tasking::TCB *tcb = thisProcess->GetThread(tid);
     if (!tcb || tcb->Linux.tgid != tgid)
     {
         debug("Invalid tgid %d tid %d", tgid, tid);
         tcb = nullptr;
         foreach (auto t in thisProcess->Threads)
         {
             if (t->Linux.tgid == tgid)
             {
                 debug("Found tgid %d tid %d", tgid, t->ID);
                 tcb = t;
                 break;
             }
         }
         if (!tcb)
             return -linux_ESRCH;
     }
     Signals nSig = ConvertSignalToNative(sig);
     assert(nSig != SIG_NULL);
     return ConvertErrnoToLinux(tcb->SendSignal(nSig));
 }
References assert, ConvertErrnoToLinux(), ConvertSignalToNative(), debug, Tasking::TCB::Linux, linux_ESRCH, Tasking::TCB::SendSignal(), SIG_NULL, and thisProcess.
linux_tkill()
static int linux_tkill (SysFrm * , int tid, int sig) static
Definition at line 2775 of file syscall.cpp.
 {
     Tasking::TCB *tcb = thisProcess->GetThread(tid);
     if (!tcb)
         return -linux_ESRCH;
     Signals nSig = ConvertSignalToNative(sig);
     assert(nSig != SIG_NULL);
     return ConvertErrnoToLinux(tcb->SendSignal(nSig));
 }
References assert, ConvertErrnoToLinux(), ConvertSignalToNative(), linux_ESRCH, Tasking::TCB::SendSignal(), SIG_NULL, and thisProcess.
linux_umask()
static mode_t linux_umask (SysFrm * , mode_t mask) static
Definition at line 2350 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     mode_t old = pcb->FileCreationMask;
     pcb->FileCreationMask = mask & 0777;
     debug("old=%#o new=%#o (mask: %#lx)", old, pcb->FileCreationMask, mask);
     return old;
 }
References debug, Tasking::PCB::FileCreationMask, mode_t, pcb, and thisProcess.
linux_uname()
static int linux_uname (SysFrm * , struct utsname * buf) static
Definition at line 2086 of file syscall.cpp.
 {
     assert(sizeof(struct utsname) < PAGE_SIZE);
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     auto pBuf = vma->UserCheckAndGetAddress(buf);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     struct utsname uname =
         {
             /* TODO: This shouldn't be hardcoded */
             .sysname = KERNEL_NAME,
             .nodename = "fennix",
             .release = KERNEL_VERSION,
             .version = KERNEL_VERSION,
 #if defined(a64)
             .machine = "x86_64",
 #elif defined(a32)
             .machine = "i386",
 #elif defined(aa64)
             .machine = "arm64",
 #elif defined(aa32)
             .machine = "arm",
 #endif
         };
     FileNode *rn = fs->GetByPath("/etc/cross/linux", pcb->Info.RootNode);
     if (rn)
     {
         struct kstat st
         {
         };
         rn->Stat(&st);
         char *sh = new char[st.Size];
         rn->Read(sh, st.Size, 0);
         ini_t *ini = ini_load(sh, NULL);
         int section = ini_find_section(ini, "uname", NULL);
         int sysIdx = ini_find_property(ini, section, "sysname", NULL);
         int nodIdx = ini_find_property(ini, section, "nodename", NULL);
         int relIdx = ini_find_property(ini, section, "release", NULL);
         int verIdx = ini_find_property(ini, section, "version", NULL);
         int macIdx = ini_find_property(ini, section, "machine", NULL);
         const char *uSys = ini_property_value(ini, section, sysIdx);
         const char *uNod = ini_property_value(ini, section, nodIdx);
         const char *uRel = ini_property_value(ini, section, relIdx);
         const char *uVer = ini_property_value(ini, section, verIdx);
         const char *uMac = ini_property_value(ini, section, macIdx);
         debug("sysname=%s", uSys);
         debug("nodename=%s", uNod);
         debug("release=%s", uRel);
         debug("version=%s", uVer);
         debug("machine=%s", uMac);
         if (uSys && strcmp(uSys, "auto") != 0)
             strncpy(uname.sysname, uSys, sizeof(uname.sysname));
         if (uNod && strcmp(uNod, "auto") != 0)
             strncpy(uname.nodename, uNod, sizeof(uname.nodename));
         if (uRel && strcmp(uRel, "auto") != 0)
             strncpy(uname.release, uRel, sizeof(uname.release));
         if (uVer && strcmp(uVer, "auto") != 0)
             strncpy(uname.version, uVer, sizeof(uname.version));
         if (uMac && strcmp(uMac, "auto") != 0)
             strncpy(uname.machine, uMac, sizeof(uname.machine));
         ini_destroy(ini);
         delete[] sh;
     }
     else
         warn("Couldn't open /etc/cross/linux");
     memcpy(pBuf, &uname, sizeof(struct utsname));
     return 0;
 }
References assert, buf, debug, fs, vfs::Virtual::GetByPath(), Tasking::PCB::Info, ini_destroy(), ini_find_property(), ini_find_section(), ini_load(), ini_property_value(), linux_EFAULT, memcpy, NULL, PAGE_SIZE, pcb, FileNode::Read(), Tasking::TaskInfo::RootNode, FileNode::Stat(), strcmp, strncpy(), thisProcess, uname(), Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, and warn.
linux_vfork()
static pid_t linux_vfork (SysFrm * sf) static
Definition at line 1508 of file syscall.cpp.
 {
     TCB *Thread = thisThread;
     PCB *Parent = Thread->Parent;
     PCB *NewProcess =
         TaskManager->CreateProcess(Parent, Parent->Name,
                                    Parent->Security.ExecutionMode,
                                    true);
     if (unlikely(!NewProcess))
     {
         error("Failed to create process for vfork");
         return -linux_EAGAIN;
     }
     NewProcess->Security.ProcessGroupID = Parent->Security.ProcessGroupID;
     NewProcess->Security.SessionID = Parent->Security.SessionID;
     NewProcess->PageTable = Parent->PageTable;
     delete NewProcess->vma;
     NewProcess->vma = Parent->vma;
     delete NewProcess->ProgramBreak;
     NewProcess->ProgramBreak = NewProcess->ProgramBreak;
     NewProcess->FileDescriptors->Fork(Parent->FileDescriptors);
     NewProcess->Executable = Parent->Executable;
     NewProcess->CWD = Parent->CWD;
     NewProcess->FileCreationMask = Parent->FileCreationMask;
     TCB *NewThread =
         TaskManager->CreateThread(NewProcess,
                                   0,
                                   nullptr,
                                   nullptr,
                                   std::vector<AuxiliaryVector>(),
                                   Thread->Info.Architecture,
                                   Thread->Info.Compatibility,
                                   true);
     if (!NewThread)
     {
         error("Failed to create thread for fork");
         delete NewProcess;
         return -linux_EAGAIN;
     }
     NewThread->Rename(Thread->Name);
     TaskManager->UpdateFrame();
     NewThread->FPU = Thread->FPU;
     delete NewThread->Stack;
     NewThread->Stack = Thread->Stack;
     NewThread->Info.Architecture = Thread->Info.Architecture;
     NewThread->Info.Compatibility = Thread->Info.Compatibility;
     NewThread->Security.IsCritical = Thread->Security.IsCritical;
     NewThread->Registers = Thread->Registers;
 #if defined(a64)
     NewThread->Registers.rip = (uintptr_t)__LinuxForkReturn;
     /* For sysretq */
     NewThread->Registers.rdi = (uintptr_t)NewProcess->PageTable;
     NewThread->Registers.rcx = sf->ReturnAddress;
     NewThread->Registers.r8 = sf->StackPointer;
 #else
 #warning "sys_fork not implemented for other platforms"
 #endif
 #ifdef a86
     NewThread->GSBase = NewThread->ShadowGSBase;
     NewThread->ShadowGSBase = Thread->ShadowGSBase;
     NewThread->FSBase = Thread->FSBase;
 #endif
     debug("ret addr: %#lx, stack: %#lx ip: %#lx", sf->ReturnAddress,
           sf->StackPointer, (uintptr_t)__LinuxForkReturn);
     debug("Forked thread \"%s\"(%d) to \"%s\"(%d)",
           Thread->Name, Thread->ID,
           NewThread->Name, NewThread->ID);
     {
         CriticalSection cs;
         Thread->SetState(Tasking::Frozen);
         NewProcess->Linux.vforked = true;
         NewProcess->Linux.CallingThread = Thread;
         NewThread->SetState(Tasking::Ready);
     }
     Parent->GetContext()->Yield();
     return (int)NewProcess->ID;
 }
References __LinuxForkReturn(), Tasking::TaskInfo::Architecture, Tasking::TaskInfo::Compatibility, Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), Tasking::PCB::CWD, debug, error, Tasking::PCB::Executable, Tasking::PCB::FileCreationMask, Tasking::PCB::FileDescriptors, vfs::FileDescriptorTable::Fork(), Tasking::Frozen, Tasking::PCB::GetContext(), Tasking::TCB::ID, Tasking::PCB::ID, Tasking::TCB::Info, Tasking::PCB::Linux, linux_EAGAIN, Tasking::TCB::Name, Tasking::PCB::Name, Tasking::PCB::PageTable, Tasking::TCB::Parent, Tasking::PCB::ProgramBreak, Tasking::Ready, Tasking::TCB::Rename(), Tasking::TCB::Security, Tasking::PCB::Security, Tasking::TCB::SetState(), Tasking::TCB::Stack, TaskManager, thisThread, unlikely, Tasking::Task::UpdateFrame(), Tasking::PCB::vma, and Tasking::Task::Yield().
linux_wait4()
static pid_t linux_wait4 (SysFrm * , pid_t pid, int * wstatus, int options, struct rusage * rusage) static
Definition at line 1809 of file syscall.cpp.
 {
     static_assert(sizeof(struct rusage) < PAGE_SIZE);
     /* FIXME: this function is very poorly implemented, the way
         it handles the zombie & coredump processes is very
         inefficient and should be rewritten */
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     if (pid == -1)
     {
         if (pcb->Children.empty())
         {
             debug("No children");
             return -linux_ECHILD;
         }
         std::vector<PCB *> wChilds;
         for (auto child : pcb->Children)
         {
             if (child->State == Tasking::Zombie)
             {
                 if (wstatus != nullptr)
                 {
                     int *pWstatus = pcb->PageTable->Get(wstatus);
                     *pWstatus = 0;
                     bool ProcessExited = true;
                     int ExitStatus = child->ExitCode.load();
                     debug("Process returned %d", ExitStatus);
                     if (ProcessExited)
                         *pWstatus |= ExitStatus << 8;
                 }
                 if (rusage != nullptr)
                 {
                     size_t kTime = child->Info.KernelTime;
                     size_t uTime = child->Info.UserTime;
                     size_t _maxrss = child->GetSize();
                     struct rusage *pRusage = vma->UserCheckAndGetAddress(rusage);
                     if (pRusage == nullptr)
                         return -linux_EFAULT;
                     pRusage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
                     pRusage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
                     pRusage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
                     pRusage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
                     pRusage->ru_maxrss = _maxrss;
                 }
                 child->SetState(Tasking::Terminated);
                 return child->ID;
             }
             if (child->State == Tasking::CoreDump)
             {
                 if (wstatus != nullptr)
                 {
                     int *pWstatus = vma->UserCheckAndGetAddress(wstatus);
                     if (pWstatus == nullptr)
                         return -linux_EFAULT;
                     *pWstatus = 0;
                     bool ProcessExited = true;
                     int ExitStatus = child->ExitCode.load();
                     bool ProcessSignaled = true;
                     bool CoreDumped = true;
                     int TermSignal = child->Signals.GetLastSignal();
                     TermSignal = ConvertSignalToLinux((Signals)TermSignal);
                     assert(TermSignal != SIG_NULL);
                     debug("Process returned %d", ExitStatus);
                     if (ProcessExited)
                         *pWstatus |= ExitStatus << 8;
                     if (ProcessSignaled)
                         *pWstatus |= TermSignal;
                     if (CoreDumped)
                         *pWstatus |= 0x80;
                 }
                 if (rusage != nullptr)
                 {
                     size_t kTime = child->Info.KernelTime;
                     size_t uTime = child->Info.UserTime;
                     size_t _maxrss = child->GetSize();
                     struct rusage *pRusage = vma->UserCheckAndGetAddress(rusage);
                     if (pRusage == nullptr)
                         return -linux_EFAULT;
                     pRusage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
                     pRusage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
                     pRusage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
                     pRusage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
                     pRusage->ru_maxrss = _maxrss;
                 }
                 child->SetState(Tasking::Terminated);
                 return child->ID;
             }
             if (child->State != Tasking::Terminated)
                 wChilds.push_back(child);
         }
         if (wChilds.empty())
         {
             debug("No children");
             return -linux_ECHILD;
         }
         fixme("Waiting for %d children", wChilds.size());
         pid = wChilds.front()->ID;
     }
     if (pid == 0)
     {
         fixme("Waiting for any child process whose process group ID is equal to that of the calling process");
         return -linux_ENOSYS;
     }
     if (pid < -1)
     {
         fixme("Waiting for any child process whose process group ID is equal to the absolute value of pid");
         return -linux_ENOSYS;
     }
     /* Wait for a child process, or any process? */
     PCB *tPcb = pcb->GetContext()->GetProcessByID(pid);
     if (!tPcb)
     {
         warn("Invalid PID %d", pid);
         return -linux_ECHILD;
     }
     if (options)
     {
 #define WCONTINUED 1
 #define WNOHANG 2
 #define WUNTRACED 4
 #define WEXITED 8
 #define WNOWAIT 16
 #define WSTOPPED 32
         fixme("options=%#x", options);
     }
 #ifdef DEBUG
     foreach (auto child in pcb->Children)
         debug("Child: %s(%d)", child->Name, child->ID);
 #endif
     debug("Waiting for %d(%#lx) state %d", pid, tPcb, tPcb->State);
     while (tPcb->State != Tasking::Zombie &&
            tPcb->State != Tasking::CoreDump &&
            tPcb->State != Tasking::Terminated)
         pcb->GetContext()->Yield();
     debug("Waited for %d(%#lx) state %d", pid, tPcb, tPcb->State);
     if (wstatus != nullptr)
     {
         int *pWstatus = vma->UserCheckAndGetAddress(wstatus);
         if (pWstatus == nullptr)
             return -linux_EFAULT;
         *pWstatus = 0;
         bool ProcessExited = true;
         int ExitStatus = tPcb->ExitCode.load();
         bool ProcessSignaled = false;
         bool CoreDumped = false;
         bool ProcessStopped = false;
         bool ProcessContinued = false;
         int TermSignal = 0;
         debug("Process returned %d", ExitStatus);
         if (ProcessExited)
             *pWstatus |= ExitStatus << 8;
         if (ProcessSignaled)
             *pWstatus |= TermSignal;
         if (CoreDumped)
             *pWstatus |= 0x80;
         /* FIXME: Untested */
         if (ProcessStopped)
             *pWstatus |= 0x7F;
         if (ProcessContinued)
             *pWstatus = 0xFFFF;
         debug("wstatus=%#x", *pWstatus);
     }
     if (rusage != nullptr)
     {
         size_t kTime = tPcb->Info.KernelTime;
         size_t uTime = tPcb->Info.UserTime;
         size_t _maxrss = tPcb->GetSize();
         struct rusage *pRusage = vma->UserCheckAndGetAddress(rusage);
         if (pRusage == nullptr)
             return -linux_EFAULT;
         pRusage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
         pRusage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
         pRusage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
         pRusage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
         pRusage->ru_maxrss = _maxrss;
         /* TODO: The rest of the fields */
     }
     return pid;
 }
References assert, child(), Tasking::PCB::Children, ConvertSignalToLinux(), Tasking::CoreDump, debug, fixme, Memory::PageTable::Get(), Tasking::PCB::GetContext(), Tasking::Task::GetProcessByID(), linux_ECHILD, linux_EFAULT, linux_ENOSYS, options, PAGE_SIZE, Tasking::PCB::PageTable, pcb, rusage::ru_maxrss, rusage::ru_stime, rusage::ru_utime, SIG_NULL, static_assert, Tasking::Terminated, thisProcess, timeval::tv_sec, timeval::tv_usec, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, vma, warn, Tasking::Task::Yield(), and Tasking::Zombie.
linux_write()
static ssize_t linux_write (SysFrm * , int fd, const void * buf, size_t count) static
Definition at line 772 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const void *pBuf = vma->UserCheckAndGetAddress(buf, count);
     if (pBuf == nullptr)
         return -linux_EFAULT;
     func("%d, %p, %d", fd, buf, count);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = ConvertErrnoToLinux(fdt->usr_write(fd, pBuf, count));
     if (ret)
         fdt->usr_lseek(fd, ret, SEEK_CUR);
 #ifdef DEBUG
     DumpData("WRITE", (void *)pBuf, ret < 0 ? 0 : ret);
 #endif
     return ret;
 }
References buf, ConvertErrnoToLinux(), count, DumpData(), fd, fdt, Tasking::PCB::FileDescriptors, func(), linux_EFAULT, pcb, ret, SEEK_CUR, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), vfs::FileDescriptorTable::usr_lseek(), vfs::FileDescriptorTable::usr_write(), Tasking::PCB::vma, and vma.
Referenced by linux_writev().
linux_writev()
static ssize_t linux_writev (SysFrm * sf, int fildes, const struct iovec * iov, int iovcnt) static
Definition at line 1219 of file syscall.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     const struct iovec *pIov = vma->UserCheckAndGetAddress(iov, sizeof(struct iovec) * iovcnt);
     if (pIov == nullptr)
         return -linux_EFAULT;
     ssize_t Total = 0;
     for (int i = 0; i < iovcnt; i++)
     {
         debug("%d: iov[%d]: %p %d", fildes, i, pIov[i].iov_base, pIov[i].iov_len);
         if (!pIov[i].iov_base)
         {
             debug("invalid iov_base");
             return -linux_EFAULT;
         }
         if (pIov[i].iov_len == 0)
         {
             debug("invalid iov_len");
             continue;
         }
         ssize_t n = linux_write(sf, fildes, pIov[i].iov_base, pIov[i].iov_len);
         if (n < 0)
             return ConvertErrnoToLinux(n);
         debug("n: %d", n);
         Total += n;
         if (n < (ssize_t)pIov[i].iov_len)
         {
             debug("break");
             break;
         }
     }
     debug("writev: %d", Total);
     return Total;
 }
References ConvertErrnoToLinux(), debug, fildes, i, iovec::iov_base, iovec::iov_len, linux_EFAULT, linux_write(), n, pcb, thisProcess, Memory::VirtualMemoryArea::UserCheckAndGetAddress(), Tasking::PCB::vma, and vma.
OKStatToStat()
struct kstat OKStatToStat (struct __old_kernel_stat okstat)
Definition at line 635 of file syscall.cpp.
 {
     struct kstat stat;
     stat.Device = okstat.st_dev;
     stat.Index = okstat.st_ino;
     stat.HardLinks = okstat.st_nlink;
     stat.Mode = okstat.st_mode;
     stat.UserID = okstat.st_uid;
     stat.GroupID = okstat.st_gid;
     stat.RawDevice = okstat.st_rdev;
     stat.Size = okstat.st_size;
     stat.AccessTime = okstat.st_atime;
     stat.ModifyTime = okstat.st_mtime;
     stat.ChangeTime = okstat.st_ctime;
     return stat;
 }
Read()
file Read ((uint8_t *) shebangMagic, 2 , 0)
Rename()
pcb Rename (baseName)
SetExe()
pcb SetExe (pPathname)
SetSigActToLinux()
void SetSigActToLinux (const SignalAction * native, k_sigaction * linux)
Definition at line 635 of file syscall.cpp.
 {
     linux->handler = native->sa_handler.Handler;
     linux->flags = native->Flags;
     linux->restorer = native->Restorer;
     unsigned long mask = native->Mask.to_ulong();
     mask = ConvertMaskToLinux(mask);
     linux->mask[0] = mask & 0xFFFFFFFF;
     linux->mask[1] = (uint32_t)((mask >> 32) & 0xFFFFFFFF);
     debug("m0:%#lx m1:%#lx | n:%#lx", linux->mask[0], linux->mask[1], native->Mask);
 }
Referenced by linux_sigaction().
SetSigActToNative()
void SetSigActToNative (const k_sigaction * linux, SignalAction * native)
Definition at line 624 of file syscall.cpp.
 {
     native->sa_handler.Handler = linux->handler;
     native->Flags = linux->flags;
     native->Restorer = linux->restorer;
     unsigned long mask = ((unsigned long)linux->mask[1] << 32) | linux->mask[0];
     native->Mask = std::bitset<64>(ConvertMaskToNative(mask));
     debug("m0:%#lx m1:%#lx | n:%#lx", linux->mask[0], linux->mask[1], native->Mask);
 }
References ConvertMaskToNative(), debug, SignalAction::Flags, k_sigaction::flags, k_sigaction::handler, SignalAction::Mask, k_sigaction::mask, SignalAction::Restorer, k_sigaction::restorer, and SignalAction::sa_handler.
Referenced by linux_sigaction().
SetWorkingDirectory()
pcb SetWorkingDirectory (file-> Parent)
StatToKStat()
struct linux_kstat StatToKStat (struct kstat stat)
Definition at line 635 of file syscall.cpp.
 {
     struct linux_kstat linux_stat;
     linux_stat.st_dev = stat.Device;
     linux_stat.st_ino = stat.Index;
     linux_stat.st_nlink = stat.HardLinks;
     linux_stat.st_mode = stat.Mode;
     linux_stat.st_uid = stat.UserID;
     linux_stat.st_gid = stat.GroupID;
     linux_stat.st_rdev = stat.RawDevice;
     linux_stat.st_size = stat.Size;
     linux_stat.st_blksize = stat.BlockSize;
     linux_stat.st_blocks = stat.Blocks;
     linux_stat.st_atime = stat.AccessTime;
     // linux_stat.st_atime_nsec = stat.st_atime_nsec;
     linux_stat.st_mtime = stat.ModifyTime;
     // linux_stat.st_mtime_nsec = stat.st_mtime_nsec;
     linux_stat.st_ctime = stat.ChangeTime;
     // linux_stat.st_ctime_nsec = stat.st_ctime_nsec;
     return linux_stat;
 }
Referenced by linux_fstat(), linux_lstat(), linux_newfstatat(), and linux_stat().
StatToOKStat()
struct __old_kernel_stat StatToOKStat (struct kstat stat)
Definition at line 635 of file syscall.cpp.
 {
     struct __old_kernel_stat okstat;
     okstat.st_dev = (unsigned short)stat.Device;
     okstat.st_ino = (unsigned short)stat.Index;
     okstat.st_nlink = (unsigned short)stat.HardLinks;
     okstat.st_mode = (unsigned short)stat.Mode;
     okstat.st_uid = (unsigned short)stat.UserID;
     okstat.st_gid = (unsigned short)stat.GroupID;
     okstat.st_rdev = (unsigned short)stat.RawDevice;
 #ifdef __i386__
     okstat.st_size = (unsigned long)stat.Size;
     okstat.st_atime = (unsigned long)stat.AccessTime;
     okstat.st_mtime = (unsigned long)stat.ModifyTime;
     okstat.st_ctime = (unsigned long)stat.ChangeTime;
 #else
     okstat.st_size = (unsigned int)stat.Size;
     okstat.st_atime = (unsigned int)stat.AccessTime;
     okstat.st_mtime = (unsigned int)stat.ModifyTime;
     okstat.st_ctime = (unsigned int)stat.ChangeTime;
 #endif
     return okstat;
 }
while()
while (true) -> Yield()
Referenced by rpmalloc_dump_statistics().
Variable Documentation
arg
const char* arg
Definition at line 1638 of file syscall.cpp.
Referenced by __cxa_atexit(), __getopt_long_core(), __pthread_create(), fcntl(), ioctl(), start(), targp_parse(), and tre_ast_new_iter().
argv
const char char* const argv[]
Definition at line 1596 of file syscall.cpp.
Referenced by __dls3(), __execvpe(), __getopt_long(), __getopt_long_core(), __libc_start_main(), Tasking::__no_sanitize(), _dlstart_c(), _start_c(), cag_option_prepare(), doomgeneric_Create(), Execute::ELFObject::ELFObject(), execl(), execle(), execlp(), execv(), execve(), execvp(), fexecve(), getopt(), getopt_long(), getopt_long_only(), KShellThread(), libc_start_main_stage2(), main(), ParseConfig(), permute(), posix_spawn(), posix_spawnp(), Execute::Spawn(), SpawnInit(), targp_parse(), Tasking::TCB::TCB(), and test_args().
argvLen
int argvLen = 0
Definition at line 1613 of file syscall.cpp.
Referenced by for().
baseName
const char* baseName
Definition at line 1773 of file syscall.cpp.
count
int struct linux_dirent64 size_t count
Initial value:
{
    if (unlikely(count < sizeof(struct linux_dirent64)))
    {
        debug("Invalid count %d", count);
        return -linux_EINVAL;
    }
    PCB *pcb = thisProcess
Definition at line 2873 of file syscall.cpp.
Referenced by __do_des(), __synccall(), _crypt_extended_r_uut(), _rpmalloc_global_cache_extract_spans(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_global_cache_extract(), A_PainShootSkull(), BF_crypt(), BF_swap(), des_cipher(), eventfd(), F_DrawPatchCol(), F_TextWrite(), getgroups(), initgroups(), linux_pread64(), linux_pwrite64(), linux_read(), linux_write(), M_ReadFile(), M_WriteFile(), ns_skiprr(), operator new(), operator new[](), P_CheckAmmo(), P_CrossSubsector(), P_LoadBlockMap(), P_PathTraverse(), P_TraverseIntercepts(), preadv(), print_broken_up_decimal(), pthread_barrier_init(), pwritev(), R_DrawColumn(), R_DrawColumnInCache(), R_DrawColumnLow(), R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawSpan(), R_DrawSpanLow(), R_DrawTranslatedColumn(), R_DrawTranslatedColumnLow(), R_SortVisSprites(), R_Subsector(), R_VideoErase(), read(), readv(), sendfile(), setgroups(), std::snprintf(), strncasecmp(), vfs::FileDescriptorTable::usr_read(), vfs::FileDescriptorTable::usr_write(), V_DrawAltTLPatch(), V_DrawPatch(), V_DrawPatchFlipped(), V_DrawShadowedPatch(), V_DrawTLPatch(), V_DrawXlaPatch(), wcsrtombs(), write(), and writev().
ctx
Tasking::Task* ctx = pcb->GetContext()
Definition at line 1780 of file syscall.cpp.
dirp
int struct linux_dirent64* dirp
Definition at line 2873 of file syscall.cpp.
envp
const char char* const char* const envp[]
Initial value:
{
    TCB *tcb = thisThread
Definition at line 1597 of file syscall.cpp.
Referenced by __dls3(), __execvpe(), __init_libc(), __libc_start_main(), Tasking::__no_sanitize(), Execute::ELFObject::ELFObject(), execle(), execve(), fegetenv(), feholdexcept(), fesetenv(), feupdateenv(), fexecve(), KShellThread(), libc_start_main_stage2(), main(), posix_spawn(), posix_spawnp(), Execute::Spawn(), SpawnInit(), Tasking::TCB::TCB(), and test_args().
envpLen
int envpLen = 0
Definition at line 1624 of file syscall.cpp.
Referenced by for().
errnoMap
static_vector<int, __ERRNO_MAX> errnoMap
Definition at line 438 of file syscall.cpp.
Referenced by ConvertErrnoToLinux().
fd
int fd
Definition at line 2873 of file syscall.cpp.
Referenced by __aio_close(), __aio_get_queue(), __aio_unref_queue(), __dls3(), __fdopen(), __fstat(), __fstat_time32(), __fstatat(), __fstatat_time32(), __fstatfs(), __futimens_time32(), __futimes_time32(), __fxstat(), __fxstatat(), __lookup_name(), __lseek(), __map_file(), __mkostemps(), __mmap(), __netlink_enumerate(), __nscd_query(), __procfdname(), __ptsname_r(), __recvmmsg_time32(), __res_msend_rc(), __rpmalloc_mmap(), __rtnetlink_enumerate(), __utimensat_time32(), __xmknodat(), _vsyslog(), accept(), accept4(), vfs::FileDescriptorTable::AddFileDescriptor(), aio_cancel(), bind(), child(), cleanup(), close(), connect(), daemon(), dprintf(), dummy(), dup(), Execute::ELFGetDynamicTag_x86_64(), Execute::ELFGetSections_x86_64(), Execute::ELFGetSymbolType_x86_64(), ELFLookupSymbol(), Execute::ELFLookupSymbol(), Execute::ELFObject::ELFObject(), epoll_ctl(), epoll_pwait(), epoll_wait(), eventfd_read(), eventfd_write(), faccessat(), fallocate(), fchdir(), fchmod(), fchmodat(), fchown(), fchownat(), fcntl(), fdatasync(), fdopendir(), fexecve(), fileno(), flock(), fopen(), vfs::FileDescriptorTable::Fork(), fremovexattr(), fstatat_statx(), fstatvfs(), fsync(), ftruncate(), futimens(), futimes(), Execute::ELFObject::GenerateAuxiliaryVector_x86_64(), getdents(), getpass(), getpeername(), getsockname(), getsockopt(), getspnam_r(), if(), if_indextoname(), if_nametoindex(), inotify_add_watch(), inotify_rm_watch(), io_thread_func(), ioctl(), isastream(), isatty(), linux_close(), linux_fchdir(), linux_fcntl(), linux_fstat(), linux_ioctl(), linux_lseek(), linux_pread64(), linux_pwrite64(), linux_read(), linux_readlink(), linux_write(), listen(), load_library(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), Execute::ELFObject::LoadInterpreter(), lockf(), login_tty(), map_library(), mkdirat(), mkfifoat(), mknodat(), mmap_fixed(), open(), openat(), opendir(), path_open(), pipe(), pipe2(), posix_close(), posix_fadvise(), posix_fallocate(), posix_spawn_file_actions_addclose(), posix_spawn_file_actions_adddup2(), posix_spawn_file_actions_addfchdir_np(), posix_spawn_file_actions_addopen(), pread(), preadv(), pthread_getname_np(), pthread_setname_np(), ptsname(), pwrite(), pwritev(), read(), read_loop(), readahead(), readlinkat(), readv(), recv(), recvfrom(), recvmmsg(), recvmsg(), sem_open(), send(), sendmmsg(), sendmsg(), sendto(), setns(), setsockopt(), shm_open(), shutdown(), signalfd(), socketpair(), Execute::Spawn(), start_tcp(), symlinkat(), sync_file_range(), syncfs(), tcdrain(), tcflow(), tcflush(), tcgetattr(), tcgetpgrp(), tcgetsid(), tcgetwinsize(), tcsendbreak(), tcsetattr(), tcsetpgrp(), tcsetwinsize(), test_stat(), test_watch_directory(), test_watch_file(), timerfd_gettime(), timerfd_settime(), tmpfile(), ttyname(), ttyname_r(), unlinkat(), unlockpt(), vfs::FileDescriptorTable::usr_close(), utimensat(), vdprintf(), vmsplice(), write(), and writev().
fdt
vfs::FileDescriptorTable* fdt = pcb->FileDescriptors
Definition at line 2882 of file syscall.cpp.
Referenced by linux_close(), linux_creat(), linux_dup(), linux_dup2(), linux_fchdir(), linux_fcntl(), linux_fstat(), linux_ioctl(), linux_lseek(), linux_lstat(), linux_mmap(), linux_newfstatat(), linux_open(), linux_openat(), linux_pread64(), linux_pwrite64(), linux_read(), linux_readlink(), linux_stat(), linux_write(), and Execute::Spawn().
fildes
vfs::FileDescriptorTable::Fildes& fildes = it->second
Definition at line 2890 of file syscall.cpp.
Referenced by linux_mmap(), linux_newfstatat(), linux_readlink(), linux_readv(), linux_writev(), and vfs::FileDescriptorTable::usr_fstat().
file
FileNode* file = fs->GetByPath(pPathname, pcb->CWD)
Definition at line 1674 of file syscall.cpp.
Referenced by __assert_fail(), __execvpe(), D_DoomMain(), dlopen(), execlp(), execvp(), if(), LoadResponseFile(), mem_fopen_read(), mem_fopen_write(), posix_spawnp(), vfs::USTAR::ReadArchive(), ReadMusHeader(), rpmalloc_dump_statistics(), WriteDiagDataToNode(), and Z_ChangeTag2().
it
auto it = fdt->FileMap.find(fd)
Definition at line 2883 of file syscall.cpp.
Referenced by Driver::__fs_Close(), Driver::__fs_Ioctl(), Driver::__fs_Open(), Driver::__fs_Read(), Driver::__fs_Write(), alarm(), vfs::Virtual::Create(), vfs::Virtual::CreateLink(), Memory::KernelStackManager::Free(), vfs::Virtual::GetByPath(), vfs::FileDescriptorTable::GetFlags(), vfs::FileDescriptorTable::GetFreeFileDescriptor(), vfs::Virtual::GetRoot(), SymbolResolver::Symbols::GetSymbol(), Tasking::PCB::GetThread(), HUlib_addPrefixToIText(), HUlib_delCharFromIText(), HUlib_drawIText(), HUlib_eraseIText(), HUlib_eraseLineFromIText(), HUlib_initIText(), HUlib_keyInIText(), HUlib_resetIText(), vfs::Virtual::LateRegisterFileSystem(), linux_fchdir(), linux_fcntl(), linux_newfstatat(), linux_readlink(), vfs::USTAR::Lookup(), Interrupts::MainInterruptHandler(), Tasking::Scheduler::Custom::PopProcess(), Driver::Manager::RegisterDevice(), v0::RegisterInterruptHandler(), vfs::Virtual::Remove(), vfs::FileDescriptorTable::RemoveFileDescriptor(), TTY::PTMXDevice::RemovePTY(), Driver::Manager::ReportInputEvent(), Interrupts::SchedulerInterruptHandler(), vfs::FileDescriptorTable::SetFlags(), ualarm(), v0::UnregisterAllInterruptHandlers(), Driver::Manager::UnregisterDevice(), vfs::Virtual::UnregisterFileSystem(), v0::UnregisterInterruptHandler(), vfs::FileDescriptorTable::usr_close(), vfs::FileDescriptorTable::usr_dup(), vfs::FileDescriptorTable::usr_dup2(), vfs::FileDescriptorTable::usr_fstat(), vfs::FileDescriptorTable::usr_ioctl(), vfs::FileDescriptorTable::usr_lseek(), vfs::FileDescriptorTable::usr_read(), and vfs::FileDescriptorTable::usr_write().
LinuxSyscallsTableAMD64
SyscallData LinuxSyscallsTableAMD64[] static
Definition at line 3359 of file syscall.cpp.
Referenced by HandleLinuxSyscalls().
LinuxSyscallsTableI386
SyscallData LinuxSyscallsTableI386[] static
Definition at line 3809 of file syscall.cpp.
Referenced by HandleLinuxSyscalls().
nArg
char* nArg
Definition at line 1639 of file syscall.cpp.
Referenced by for().
pArgv
auto pArgv = vma->UserCheckAndGetAddress(argv, 1)
Definition at line 1606 of file syscall.cpp.
Referenced by for().
pathname
const char* pathname
Definition at line 1595 of file syscall.cpp.
Referenced by __futimesat(), __futimesat_time32(), __map_file(), do_tzset(), fanotify_mark(), inotify_add_watch(), linux_access(), linux_creat(), linux_lstat(), linux_mkdir(), linux_newfstatat(), linux_open(), linux_openat(), linux_readlink(), linux_stat(), load_library(), name_to_handle_at(), vfs::FileDescriptorTable::usr_creat(), vfs::FileDescriptorTable::usr_lstat(), vfs::FileDescriptorTable::usr_open(), and vfs::FileDescriptorTable::usr_stat().
pcb
PCB* pcb = tcb->Parent
Definition at line 1602 of file syscall.cpp.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), Tasking::Scheduler::Custom::CleanupTerminated(), cmd_kill(), v0::CreateKernelProcess(), for(), vfs::FileDescriptorTable::GetFreeFileDescriptor(), if(), Tasking::Signal::InitTrampoline(), v0::KillProcess(), Tasking::Task::KillProcess(), KShellThread(), linux_access(), linux_arch_prctl(), linux_brk(), linux_chdir(), linux_clock_gettime(), linux_clock_nanosleep(), linux_close(), linux_creat(), linux_dup(), linux_dup2(), linux_fchdir(), linux_fcntl(), linux_fstat(), linux_getcwd(), linux_getpgid(), linux_getpid(), linux_getrandom(), linux_getrusage(), linux_ioctl(), linux_kill(), linux_lseek(), linux_lstat(), linux_mkdir(), linux_mmap(), linux_mprotect(), linux_munmap(), linux_nanosleep(), linux_newfstatat(), linux_open(), linux_openat(), linux_pause(), linux_pipe(), linux_pipe2(), linux_pread64(), linux_prlimit64(), linux_pwrite64(), linux_read(), linux_readlink(), linux_readv(), linux_reboot(), linux_sched_getaffinity(), linux_sched_setaffinity(), linux_setitimer(), linux_setpgid(), linux_sigaction(), linux_sigprocmask(), linux_stat(), linux_umask(), linux_uname(), linux_wait4(), linux_write(), linux_writev(), ACPI::DSDT::OnInterruptReceived(), Tasking::Task::PopProcess(), Tasking::Scheduler::Custom::PopProcess(), Tasking::Task::PushProcess(), Tasking::Signal::SendSignal(), Tasking::Task::SignalShutdown(), Memory::VirtualMemoryArea::VirtualMemoryArea(), Tasking::Task::WaitForProcess(), Tasking::Task::WaitForProcessStatus(), and Tasking::PCB::~PCB().
pDirp
auto pDirp = vma->UserCheckAndGetAddress(dirp)
Definition at line 2898 of file syscall.cpp.
Referenced by if().
pEnvp
auto pEnvp = vma->UserCheckAndGetAddress(envp, 1)
Definition at line 1607 of file syscall.cpp.
Referenced by for().
pPathname
auto pPathname = vma->UserCheckAndGetAddress(pathname, PAGE_SIZE)
Definition at line 1605 of file syscall.cpp.
Referenced by if(), linux_access(), linux_lstat(), linux_mkdir(), linux_newfstatat(), linux_open(), linux_openat(), and linux_stat().
ret
return ret
Initial value:
= Execute::Spawn((char *)pPathname,
                             (const char **)safeArgv,
                             (const char **)safeEnvp,
                             pcb, true,
                             pcb->Info.Compatibility)
Definition at line 1761 of file syscall.cpp.
Referenced by __clock_nanosleep_time32(), __fstatat(), __getopt_long(), __libc_sbrk(), __lseek(), __lsysinfo(), __memcpy_chk(), __memmove_chk(), __memset_chk(), __mmap(), __musl_syscall1(), __nanosleep_time32(), __netlink_enumerate(), __pthread_create(), __sigsetjmp_tail(), __strlen(), __syscall0(), __syscall1(), __syscall2(), __syscall3(), __syscall4(), __syscall5(), __syscall6(), __thrd_sleep_time32(), vfs::__vfs_ReadLink(), _Fork(), accept4(), vfs::FileDescriptorTable::AddFileDescriptor(), aio_cancel(), aio_suspend(), asprintf(), vfs::Virtual::CacheLookup(), calloc(), checker(), child(), clock_getcpuclockid(), closedir(), cnd_timedwait(), ConvertErrnoToLinux(), ConvertMaskToLinux(), ConvertMaskToNative(), cookieread(), cookiewrite(), crc32(), vfs::Virtual::Create(), vfs::Virtual::CreateLink(), cxx_Initialize(), dl_iterate_phdr(), do_getaffinity(), do_setgroups(), do_setxid(), dprintf(), faccessat(), fchdir(), fchmod(), fchmodat(), fchown(), fcntl(), fctprintf(), feof(), ferror(), fgetln(), fmtmsg(), fork(), fprintf(), fscanf(), fstatat_statx(), fwprintf(), fwscanf(), vfs::Virtual::GetByPath(), GetCurrentCPU(), getcwd(), getdate(), getentropy(), getgrouplist(), getpriority(), getrlimit(), vfs::Virtual::GetRoot(), Tasking::TCB::GetSize(), Tasking::PCB::GetSize(), vfs::USTAR::GetSize(), if(), io_thread_func(), APIC::APIC::IORead(), KShellThread(), liballoc_alloc(), linux_brk(), linux_fcntl(), linux_fstat(), linux_ioctl(), linux_lstat(), linux_mmap(), linux_newfstatat(), linux_openat(), linux_pread64(), linux_pwrite64(), linux_read(), linux_sigaction(), linux_stat(), linux_write(), lio_listio(), main(), malloc(), Xalloc::V2::malloc(), mbrtoc16(), mbrtoc32(), memcpy(), memset(), mq_unlink(), mtx_timedlock(), mtx_trylock(), CPU::PageTable(), pipe2(), printf(), printf_(), v0::PS2ReadAfterACK(), pshared_barrier_wait(), pthread_sigmask(), ptrace(), raise(), APIC::APIC::Read(), readdir_r(), realloc(), reloc_all(), vfs::Virtual::Remove(), NetworkARP::ARP::Resolve(), scanf(), NetworkARP::ARP::Search(), setlocale(), setlogmask(), setrlimit(), siglongjmp(), signalfd(), sigtimedwait(), std::snprintf(), snprintf(), snprintf_(), sockatmark(), sprintf(), std::sprintf(), sprintf_(), sscanf(), strfmon(), strfmon_l(), vfs::USTAR::StringToInt(), strlen_sse4_2(), strtok(), submit(), swprintf(), swscanf(), vfs::USTAR::SymLink(), syscall0(), syscall1(), syscall2(), syscall3(), syscall4(), syscall5(), syscall6(), system(), SystemCallsHandler(), test_system(), thrd_create(), thrd_sleep(), timespec_get(), tre_tnfa_run_backtrack(), tre_tnfa_run_parallel(), NetworkARP::ARP::Update(), vfs::FileDescriptorTable::usr_stat(), vasprintf(), vfprintf(), vfwprintf(), wmemset(), wprintf(), and wscanf().
rlimitStr
const char* rlimitStr[]
Initial value:
= {
    "RLIMIT_CPU",
    "RLIMIT_FSIZE",
    "RLIMIT_DATA",
    "RLIMIT_STACK",
    "RLIMIT_CORE",
    "RLIMIT_RSS",
    "RLIMIT_NPROC",
    "RLIMIT_NOFILE",
    "RLIMIT_MEMLOCK",
    "RLIMIT_AS",
    "RLIMIT_LOCKS",
    "RLIMIT_SIGPENDING",
    "RLIMIT_MSGQUEUE",
    "RLIMIT_NICE",
    "RLIMIT_RTPRIO",
    "RLIMIT_RTTIME",
    "RLIMIT_NLIMITS",
}
Definition at line 346 of file syscall.cpp.
Referenced by linux_prlimit64().
safeArgv
char** safeArgv = (char **)pcb->vma->RequestPages(TO_PAGES(argvLen * sizeof(char *)))
Definition at line 1635 of file syscall.cpp.
Referenced by for(), and if().
safeEnvp
char** safeEnvp = (char **)pcb->vma->RequestPages(TO_PAGES(envpLen * sizeof(char *)))
Definition at line 1636 of file syscall.cpp.
Referenced by if().
shebangMagic
char shebangMagic[2] {}
Definition at line 1682 of file syscall.cpp.
const { ... } signalMapping[]
Referenced by ConvertSignalToLinux(), and ConvertSignalToNative().
vma
Memory::VirtualMemoryArea * vma = pcb->vma
Definition at line 1603 of file syscall.cpp.
Referenced by for(), Execute::ELFObject::GenerateAuxiliaryVector_x86_64(), v0::GetPCIDevices(), Tasking::PCB::GetSize(), linux_access(), linux_arch_prctl(), linux_chdir(), linux_clock_gettime(), linux_clock_nanosleep(), linux_fstat(), linux_getcwd(), linux_getrandom(), linux_getrusage(), linux_ioctl(), linux_lstat(), linux_mkdir(), linux_mmap(), linux_munmap(), linux_nanosleep(), linux_newfstatat(), linux_open(), linux_openat(), linux_pipe(), linux_pipe2(), linux_pread64(), linux_prlimit64(), linux_pwrite64(), linux_read(), linux_readlink(), linux_readv(), linux_reboot(), linux_sched_getaffinity(), linux_sched_setaffinity(), linux_setitimer(), linux_sigaction(), linux_sigprocmask(), linux_stat(), linux_uname(), linux_wait4(), linux_write(), linux_writev(), Execute::ELFObject::LoadDyn_x86_64(), and Execute::ELFObject::LoadExec_x86_64().