Fennix: Userspace/musl/src/stdio/__towrite.c File Reference
__towrite.c File Reference
#include "stdio_impl.h"
Functions
int __towrite (FILE *f)
hidden void __towrite_needs_stdio_exit ()
Function Documentation
__towrite()
int __towrite (FILE * f)
Definition at line 3 of file __towrite.c.
 {
     f->mode |= f->mode-1;
     if (f->flags & F_NOWR) {
         f->flags |= F_ERR;
         return EOF;
     }
     /* Clear read buffer (easier than summoning nasal demons) */
     f->rpos = f->rend = 0;
     /* Activate write through the buffer. */
     f->wpos = f->wbase = f->buf;
     f->wend = f->buf + f->buf_size;
     return 0;
 }
References EOF, f, F_ERR, and F_NOWR.
Referenced by __fwritex(), __overflow(), and vfprintf().
__towrite_needs_stdio_exit()
hidden void __towrite_needs_stdio_exit ()
Definition at line 20 of file __towrite.c.
 {
     __stdio_exit_needed();
 }
References __stdio_exit_needed().