Fennix: Userspace/musl/src/network/getservbyport.c File Reference
getservbyport.c File Reference
#include <netdb.h>
Macros
#define _GNU_SOURCE
Functions
struct servent * getservbyport (int port, const char *prots)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file getservbyport.c.
Function Documentation
getservbyport()
struct servent* getservbyport (int port, const char * prots)
Definition at line 4 of file getservbyport.c.
 {
     static struct servent se;
     static long buf[32/sizeof(long)];
     struct servent *res;
     if (getservbyport_r(port, prots, &se, (void *)buf, sizeof buf, &res))
         return 0;
     return &se;
 }
References buf, getservbyport_r(), and port.
Referenced by get_sname(), and port_name().