Fennix Userspace: Userspace/mlibc/tests/rtdl/preinit/libfoo.c File Reference
libfoo.c File Reference
#include <stdio.h>
#include <assert.h>
Functions
__attribute__ ((constructor))
int isFooDone ()
Variables
int fooDone = 0
Function Documentation
__attribute__()
__attribute__ ((constructor))
Definition at line 8 of file libfoo.c.
                {
     dprintf(1, "initialization function called in foo\n");
     assert(fooDone == 0);
     fooDone++;
 }
References assert, dprintf(), and fooDone.
isFooDone()
int isFooDone ()
Definition at line 16 of file libfoo.c.
                 {
     return fooDone;
 }
References fooDone.
Referenced by __attribute__(), main(), preInit1(), and preInit2().
Variable Documentation
fooDone
int fooDone = 0
Definition at line 4 of file libfoo.c.
Referenced by __attribute__(), and isFooDone().