Fennix: Userspace/mlibc/options/ansi/musl-generic-math/lgamma.c File Reference
lgamma.c File Reference
#include <math.h>
Functions
double __lgamma_r (double, int *)
double lgamma (double x)
Variables
int __signgam
Function Documentation
__lgamma_r()
double __lgamma_r (double x, int * signgamp)
Definition at line 172 of file lgamma_r.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t t,y,z,nadj,p,p1,p2,p3,q,r,w;
     uint32_t ix;
     int sign,i;
     /* purge off +-inf, NaN, +-0, tiny and negative arguments */
     *signgamp = 1;
     sign = u.i>>63;
     ix = u.i>>32 & 0x7fffffff;
     if (ix >= 0x7ff00000)
         return x*x;
     if (ix < (0x3ff-70)<<20) {  /* |x|<2**-70, return -log(|x|) */
         if(sign) {
             x = -x;
             *signgamp = -1;
         }
         return -log(x);
     }
     if (sign) {
         x = -x;
         t = sin_pi(x);
         if (t == 0.0) /* -integer */
             return 1.0/(x-x);
         if (t > 0.0)
             *signgamp = -1;
         else
             t = -t;
         nadj = log(pi/(t*x));
     }
     /* purge off 1 and 2 */
     if ((ix == 0x3ff00000 || ix == 0x40000000) && (uint32_t)u.i == 0)
         r = 0;
     /* for x < 2.0 */
     else if (ix < 0x40000000) {
         if (ix <= 0x3feccccc) {   /* lgamma(x) = lgamma(x+1)-log(x) */
             r = -log(x);
             if (ix >= 0x3FE76944) {
                 y = 1.0 - x;
                 i = 0;
             } else if (ix >= 0x3FCDA661) {
                 y = x - (tc-1.0);
                 i = 1;
             } else {
                 y = x;
                 i = 2;
             }
         } else {
             r = 0.0;
             if (ix >= 0x3FFBB4C3) {  /* [1.7316,2] */
                 y = 2.0 - x;
                 i = 0;
             } else if(ix >= 0x3FF3B4C4) {  /* [1.23,1.73] */
                 y = x - tc;
                 i = 1;
             } else {
                 y = x - 1.0;
                 i = 2;
             }
         }
         switch (i) {
         case 0:
             z = y*y;
             p1 = a0+z*(a2+z*(a4+z*(a6+z*(a8+z*a10))));
             p2 = z*(a1+z*(a3+z*(a5+z*(a7+z*(a9+z*a11)))));
             p = y*p1+p2;
             r += (p-0.5*y);
             break;
         case 1:
             z = y*y;
             w = z*y;
             p1 = t0+w*(t3+w*(t6+w*(t9 +w*t12)));    /* parallel comp */
             p2 = t1+w*(t4+w*(t7+w*(t10+w*t13)));
             p3 = t2+w*(t5+w*(t8+w*(t11+w*t14)));
             p = z*p1-(tt-w*(p2+y*p3));
             r += tf + p;
             break;
         case 2:
             p1 = y*(u0+y*(u1+y*(u2+y*(u3+y*(u4+y*u5)))));
             p2 = 1.0+y*(v1+y*(v2+y*(v3+y*(v4+y*v5))));
             r += -0.5*y + p1/p2;
         }
     } else if (ix < 0x40200000) {  /* x < 8.0 */
         i = (int)x;
         y = x - (double)i;
         p = y*(s0+y*(s1+y*(s2+y*(s3+y*(s4+y*(s5+y*s6))))));
         q = 1.0+y*(r1+y*(r2+y*(r3+y*(r4+y*(r5+y*r6)))));
         r = 0.5*y+p/q;
         z = 1.0;    /* lgamma(1+s) = log(s) + lgamma(s) */
         switch (i) {
         case 7: z *= y + 6.0;  /* FALLTHRU */
         case 6: z *= y + 5.0;  /* FALLTHRU */
         case 5: z *= y + 4.0;  /* FALLTHRU */
         case 4: z *= y + 3.0;  /* FALLTHRU */
         case 3: z *= y + 2.0;  /* FALLTHRU */
             r += log(z);
             break;
         }
     } else if (ix < 0x43900000) {  /* 8.0 <= x < 2**58 */
         t = log(x);
         z = 1.0/x;
         y = z*z;
         w = w0+z*(w1+y*(w2+y*(w3+y*(w4+y*(w5+y*w6)))));
         r = (x-0.5)*(t-1.0)+w;
     } else                         /* 2**58 <= x <= inf */
         r =  x*(log(x)-1.0);
     if (sign)
         r = nadj - r;
     return r;
 }
References a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9, i, int, log(), p, pi, r, r1, r2, r3, r4, r5, r6, s0, s1, s2, s3, s4, s5, s6, sin_pi(), t0, t1, t10, t11, t12, t13, t14, t2, t3, t4, t5, t6, t7, t8, t9, tc, tf, tt, u0, u1, u2, u3, u4, u5, v1, v2, v3, v4, v5, w0, w1, w2, w3, w4, w5, w6, x, and y.
Referenced by lgamma().
lgamma()
double lgamma (double x)
Definition at line 6 of file lgamma.c.
 {
     return __lgamma_r(x, &__signgam);
 }
References __lgamma_r(), __signgam, and x.
Variable Documentation
__signgam
int __signgam extern
Referenced by lgamma().