Fennix: Userspace/apps/base/bash/lib/sh/mbschr.c File Reference
mbschr.c File Reference
#include <config.h>
#include "bashansi.h"
#include "shmbutil.h"
Functions
char * utf8_mbschr (const char *, int)
char * mbschr (char *s, int c) const
Variables
int locale_mb_cur_max
int locale_utf8locale
Function Documentation
mbschr()
char* mbschr (char * s, int c) const
Definition at line 45 of file mbschr.c.
 {
 #if HANDLE_MULTIBYTE
   char *pos;
   mbstate_t state;
   size_t strlength, mblength;
   if (locale_utf8locale && c < 0x80)
     return (utf8_mbschr (s, c));        /* XXX */
   /* The locale encodings with said weird property are BIG5, BIG5-HKSCS,
      GBK, GB18030, SHIFT_JIS, and JOHAB.  They exhibit the problem only
      when c >= 0x30.  We can therefore use the faster bytewise search if
      c <= 0x30. */
   if ((unsigned char)c >= '0' && locale_mb_cur_max > 1)
     {
       pos = (char *)s;
       memset (&state, '\0', sizeof(mbstate_t));
       strlength = strlen (s);
       while (strlength > 0)
     {
       if (is_basic (*pos))
         mblength = 1;
       else
         {
           mblength = mbrlen (pos, strlength, &state);
           if (mblength == (size_t)-2 || mblength == (size_t)-1 || mblength == (size_t)0)
             mblength = 1;
         }
       if (mblength == 1 && c == (unsigned char)*pos)
         return pos;
       strlength -= mblength;
       pos += mblength;
     }
       return ((char *)NULL);
     }
   else
 #endif
   return (strchr (s, c));
 }
References c, locale_mb_cur_max, locale_utf8locale, mbrlen(), memset, NULL, pos, state, strchr(), strlen(), and utf8_mbschr().
Referenced by absolute_program(), chk_atstar(), do_assignment_internal(), execute_disk_command(), exportable_function_name(), and parameter_brace_expand().
utf8_mbschr()
char* utf8_mbschr (const char * , int)
Referenced by mbschr().
Variable Documentation
locale_mb_cur_max
int locale_mb_cur_max extern
Definition at line 47 of file locale.c.
Referenced by expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), mbschr(), pat_subst(), and sh_charvis().
locale_utf8locale
int locale_utf8locale extern
Definition at line 46 of file locale.c.
Referenced by ansicstr(), cutchars(), mbschr(), read_comsub(), setifs(), sh_backslash_quote(), sh_charvis(), sh_double_quote(), sh_mkdoublequoted(), and string_extract_verbatim().