Fennix Userspace: Userspace/apps/base/bash/CWRU/misc/open-files.c File Reference
open-files.c File Reference
#include <sys/types.h>
#include <fcntl.h>
#include <sys/file.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
Functions
main ()
Function Documentation
main()
main (void)
Definition at line 30 of file open-files.c.
 {
     register int    i;
     for (i = 0; i < getdtablesize(); i++) {
         if (fcntl(i, F_GETFD, 0) != -1)
             fprintf(stderr, "fd %d: open\n", i);
     }
     exit(0);
 }
References exit(), F_GETFD, fcntl(), fprintf(), getdtablesize(), i, and stderr.