Fennix Userspace: Userspace/apps/base/busybox/libbb/speed_table.c File Reference
speed_table.c File Reference
#include "libbb.h"
Data Structures
struct speed_map
Enumerations
enum { NUM_SPEEDS = ARRAY_SIZE(speeds) }
Functions
unsigned FAST_FUNC tty_baud_to_value (speed_t speed)
speed_t FAST_FUNC tty_value_to_baud (unsigned int value)
Variables
static const struct speed_map speeds[] ALIGN4
Data Structure Documentation
speed_map
struct speed_map
Definition at line 11 of file speed_table.c.
Data Fields
unsigned short speed
unsigned short value
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NUM_SPEEDS
Definition at line 122 of file speed_table.c.
 { NUM_SPEEDS = ARRAY_SIZE(speeds) };
Function Documentation
tty_baud_to_value()
unsigned FAST_FUNC tty_baud_to_value (speed_t speed)
Definition at line 124 of file speed_table.c.
 {
     int i = 0;
     do {
         if (speed == speeds[i].speed) {
             if (speeds[i].value & 0x8000u) {
                 return ((unsigned)(speeds[i].value) & 0x7fffU) * 200;
             }
             return speeds[i].value;
         }
     } while (++i < NUM_SPEEDS);
     return 0;
 }
References i, NUM_SPEEDS, speed_map::speed, speeds, and value.
Referenced by display_speed(), and tty_value_to_baud().
tty_value_to_baud()
speed_t FAST_FUNC tty_value_to_baud (unsigned int value)
Definition at line 140 of file speed_table.c.
 {
     int i = 0;
     do {
         if (value == tty_baud_to_value(speeds[i].speed)) {
             return speeds[i].speed;
         }
     } while (++i < NUM_SPEEDS);
     return (speed_t) - 1;
 }
References i, NUM_SPEEDS, speed_map::speed, speeds, tty_baud_to_value(), and value.
Referenced by bcode(), microcom_main(), set_speed_or_die(), slattach_main(), and stty_main().
Variable Documentation
ALIGN4
const struct speed_map speeds [] ALIGN4 static
Definition at line 31 of file speed_table.c.