Fennix Userspace: Userspace/apps/base/busybox/findutils/find.c File Reference
find.c File Reference
#include <fnmatch.h>
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct action
struct pp_locals
Macros
#define FNM_CASEFOLD 0
#define dbg(...) ((void)0)
#define ACTS(name, ...) typedef struct { action a; __VA_ARGS__ } action_##name;
#define ACTF(name)
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define USE_NESTED_FUNCTION 0
#define appp (ppl.appp)
#define cur_group (ppl.cur_group)
#define cur_action (ppl.cur_action)
#define invert_flag (ppl.invert_flag)
#define ALLOC_ACTION(name) (action_##name*)alloc_action(&ppl, sizeof(action_##name), (action_fp) func_##name)
Typedefs
typedef int(* action_fp) (const char *fileName, const struct stat *statbuf, void *) FAST_FUNC
Functions
IF_FEATURE_FIND_EXEC (ACTS(exec, char **exec_argv;unsigned *subst_count;int exec_argc;IF_FEATURE_FIND_EXEC_PLUS(char **filelist;int filelist_idx;int file_len;)))
static int exec_actions (action ***appp, const char *fileName, const struct stat *statbuf)
static char * strcpy_upcase (char *dst, const char *src)
ACTF (print)
static int FAST_FUNC fileAction (struct recursive_state *state IF_NOT_FEATURE_FIND_MAXDEPTH(UNUSED_PARAM), const char *fileName, struct stat *statbuf)
static action * alloc_action (struct pp_locals *ppl, int sizeof_struct, action_fp f)
static action *** parse_params (char **argv)
int find_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
FIX_ALIASING
Data Structure Documentation
action
struct action
Definition at line 432 of file find.c.
Data Fields
action_fp f
pp_locals
struct pp_locals
Definition at line 1081 of file find.c.
Data Fields
action *** appp
unsigned cur_action
unsigned cur_group
Macro Definition Documentation
ACTF
ACTF (name)
Value:
    static int FAST_FUNC func_##name(const char *fileName UNUSED_PARAM, \
        const struct stat *statbuf UNUSED_PARAM, \
        action_##name* ap UNUSED_PARAM)
Definition at line 440 of file find.c.
ACTS
#define ACTS (name, ...) typedef struct { action a; __VA_ARGS__ } action_##name;
Definition at line 439 of file find.c.
ALLOC_ACTION
#define ALLOC_ACTION (name) (action_##name*)alloc_action(&ppl, sizeof(action_##name), (action_fp) func_##name)
appp
#define appp (ppl.appp)
cur_action
#define cur_action (ppl.cur_action)
cur_group
#define cur_group (ppl.cur_group)
dbg
#define dbg (...) ((void)0)
Definition at line 421 of file find.c.
FNM_CASEFOLD
#define FNM_CASEFOLD 0
Definition at line 417 of file find.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 496 of file find.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    BUILD_BUG_ON(sizeof(G) > COMMON_BUFSIZE); \
    /* we have to zero it out because of NOEXEC */ \
    memset(&G, 0, sizeof(G)); \
    IF_FEATURE_FIND_MAXDEPTH(G.minmaxdepth[1] = INT_MAX;) \
    IF_FEATURE_FIND_EXEC_PLUS(G.max_argv_len = bb_arg_max() - 2048;) \
    G.need_print = 1; \
    G.recurse_flags = ACTION_RECURSE; \
} while (0)
Definition at line 497 of file find.c.
invert_flag
#define invert_flag (ppl.invert_flag)
USE_NESTED_FUNCTION
#define USE_NESTED_FUNCTION 0
Definition at line 1078 of file find.c.
Typedef Documentation
action_fp
typedef int(* action_fp) (const char *fileName, const struct stat *statbuf, void *) FAST_FUNC
Definition at line 430 of file find.c.
Function Documentation
ACTF()
ACTF (print)
Definition at line 876 of file find.c.
 {
     puts(fileName);
     return TRUE;
 }
References fileName, puts(), and TRUE.
alloc_action()
static action* alloc_action (struct pp_locals * ppl, int sizeof_struct, action_fp f) static
Definition at line 1087 of file find.c.
 {
     action *ap = xzalloc(sizeof_struct);
     action **app;
     action ***group = &ppl->appp[ppl->cur_group];
     *group = app = xrealloc(*group, (ppl->cur_action+2) * sizeof(ppl->appp[0][0]));
     app[ppl->cur_action++] = ap;
     app[ppl->cur_action] = NULL;
     ap->f = f;
     IF_FEATURE_FIND_NOT( ap->invert = ppl->invert_flag; )
     IF_FEATURE_FIND_NOT( ppl->invert_flag = 0; )
     return ap;
 }
References ap, pp_locals::appp, pp_locals::cur_action, pp_locals::cur_group, f, NULL, xrealloc, and xzalloc().
Referenced by parse_params().
exec_actions()
static int exec_actions (action *** appp, const char * fileName, const struct stat * statbuf) static
Definition at line 513 of file find.c.
 {
     int cur_group;
     int cur_action;
     int rc = 0;
     action **app, *ap;
     /* "action group" is a set of actions ANDed together.
      * groups are ORed together.
      * We simply evaluate each group until we find one in which all actions
      * succeed. */
     /* -prune is special: if it is encountered, then we won't
      * descend into current directory. It doesn't matter whether
      * action group (in which -prune sits) will succeed or not:
      * find * -prune -name 'f*' -o -name 'm*' -- prunes every dir
      * find * -name 'f*' -o -prune -name 'm*' -- prunes all dirs
      *     not starting with 'f' */
     /* We invert TRUE bit (bit 0). Now 1 there means 'failure'.
      * and bitwise OR in "rc |= TRUE ^ ap->f()" will:
      * (1) make SKIP (-prune) bit stick; and (2) detect 'failure'.
      * On return, bit is restored.  */
     cur_group = -1;
     while ((app = appp[++cur_group]) != NULL) {
         rc &= ~TRUE; /* 'success' so far, clear TRUE bit */
         cur_action = -1;
         while (1) {
             ap = app[++cur_action];
             if (!ap) /* all actions in group were successful */
                 return rc ^ TRUE; /* restore TRUE bit */
             rc |= TRUE ^ ap->f(fileName, statbuf, ap);
 #if ENABLE_FEATURE_FIND_NOT
             if (ap->invert) rc ^= TRUE;
 #endif
             dbg("grp %d action %d rc:0x%x", cur_group, cur_action, rc);
             if (rc & TRUE) /* current group failed, try next */
                 break;
         }
     }
     dbg("returning:0x%x", rc ^ TRUE);
     return rc ^ TRUE; /* restore TRUE bit */
 }
References ap, appp, cur_action, cur_group, dbg, fileName, NULL, rc, and TRUE.
Referenced by fileAction().
fileAction()
static int FAST_FUNC fileAction (struct recursive_state *state IF_NOT_FEATURE_FIND_MAXDEPTHUNUSED_PARAM, const char * fileName, struct stat * statbuf) static
Definition at line 985 of file find.c.
 {
     int r;
     int same_fs = 1;
 #if ENABLE_FEATURE_FIND_XDEV
     if (S_ISDIR(statbuf->st_mode) && G.xdev_count) {
         int i;
         for (i = 0; i < G.xdev_count; i++) {
             if (G.xdev_dev[i] == statbuf->st_dev)
                 goto found;
         }
         //bb_error_msg("'%s': not same fs", fileName);
         same_fs = 0;
  found: ;
     }
 #endif
 #if ENABLE_FEATURE_FIND_MAXDEPTH
     if (state->depth < G.minmaxdepth[0]) {
         if (same_fs)
             return TRUE; /* skip this, continue recursing */
         return SKIP; /* stop recursing */
     }
     if (state->depth > G.minmaxdepth[1])
         return SKIP; /* stop recursing */
 #endif
     r = exec_actions(G.actions, fileName, statbuf);
     /* Had no explicit -print[0] or -exec? then print */
     if ((r & TRUE) && G.need_print)
         puts(fileName);
 #if ENABLE_FEATURE_FIND_MAXDEPTH
     if (S_ISDIR(statbuf->st_mode)) {
         if (state->depth == G.minmaxdepth[1])
             return SKIP;
     }
 #endif
     /* -xdev stops on mountpoints, but AFTER mountpoit itself
      * is processed as usual */
     if (!same_fs) {
         return SKIP;
     }
     /* Cannot return 0: our caller, recursive_action(),
      * will perror() and skip dirs (if called on dir) */
     return (r & SKIP) ? SKIP : TRUE;
 }
References exec_actions(), fileName, found, G, i, puts(), S_ISDIR, SKIP, stat::st_dev, stat::st_mode, state, and TRUE.
Referenced by find_main().
find_main()
int find_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1632 of file find.c.
 {
     int i, firstopt;
     char **past_HLP, *saved;
     INIT_G();
     /* "find -type f" + getopt("+HLP") => disaster.
      * Need to avoid getopt running into a non-HLP option.
      * Do this by temporarily storing NULL there:
      */
     past_HLP = argv;
     for (;;) {
         saved = *++past_HLP;
         if (!saved)
             break;
         if (saved[0] != '-')
             break;
         if (!saved[1])
             break; /* it is "-" */
         if (saved[1] == '-' && !saved[2]) {
             /* it is "--" */
             /* Try: find -- /dev/null */
             saved = *++past_HLP;
             break;
         }
         if ((saved+1)[strspn(saved+1, "HLP")] != '\0')
             break;
     }
     *past_HLP = NULL;
     /* "+": stop on first non-option */
     i = getopt32(argv, "+""HLP");
     if (i & (1<<0))
         G.recurse_flags |= ACTION_FOLLOWLINKS_L0 | ACTION_DANGLING_OK;
     if (i & (1<<1))
         G.recurse_flags |= ACTION_FOLLOWLINKS | ACTION_DANGLING_OK;
     /* -P is default and is ignored */
     argv = past_HLP; /* same result as "argv += optind;" */
     *past_HLP = saved;
     for (firstopt = 0; argv[firstopt]; firstopt++) {
         if (argv[firstopt][0] == '-')
             break;
         if (ENABLE_FEATURE_FIND_NOT && LONE_CHAR(argv[firstopt], '!'))
             break;
         if (ENABLE_FEATURE_FIND_PAREN && LONE_CHAR(argv[firstopt], '('))
             break;
     }
     if (firstopt == 0) {
         *--argv = (char*)".";
         firstopt++;
     }
     G.actions = parse_params(&argv[firstopt]);
     argv[firstopt] = NULL;
 #if ENABLE_FEATURE_FIND_XDEV
     if (G.xdev_on) {
         struct stat stbuf;
         G.xdev_count = firstopt;
         G.xdev_dev = xzalloc(G.xdev_count * sizeof(G.xdev_dev[0]));
         for (i = 0; argv[i]; i++) {
             /* not xstat(): shouldn't bomb out on
              * "find not_exist exist -xdev" */
             if (stat(argv[i], &stbuf) == 0)
                 G.xdev_dev[i] = stbuf.st_dev;
             /* else G.xdev_dev[i] stays 0 and
              * won't match any real device dev_t
              */
         }
     }
 #endif
     for (i = 0; argv[i]; i++) {
         if (!recursive_action(argv[i],
                 G.recurse_flags,/* flags */
                 fileAction,     /* file action */
                 fileAction,     /* dir action */
                 NULL)           /* user data */
         ) {
             G.exitstatus |= EXIT_FAILURE;
         }
     }
     IF_FEATURE_FIND_EXEC_PLUS(G.exitstatus |= flush_exec_plus();)
     return G.exitstatus;
 }
References ACTION_DANGLING_OK, ACTION_FOLLOWLINKS, ACTION_FOLLOWLINKS_L0, argv, EXIT_FAILURE, fileAction(), G, getopt32(), i, INIT_G, LONE_CHAR, NULL, parse_params(), recursive_action(), stat::st_dev, stat(), strspn(), and xzalloc().
IF_FEATURE_FIND_EXEC()
IF_FEATURE_FIND_EXEC (ACTS(exec, char **exec_argv; unsigned *subst_count; int exec_argc; IF_FEATURE_FIND_EXEC_PLUS(char **filelist; int filelist_idx; int file_len;)))
Definition at line 466 of file find.c.
                {
     IF_FEATURE_FIND_XDEV(dev_t *xdev_dev;)
     IF_FEATURE_FIND_XDEV(int xdev_count;)
 #if ENABLE_FEATURE_FIND_MAXDEPTH
     int minmaxdepth[2];
 #endif
     action ***actions;
     smallint need_print;
     smallint xdev_on;
     smalluint exitstatus;
     recurse_flags_t recurse_flags;
     IF_FEATURE_FIND_EXEC_PLUS(unsigned max_argv_len;)
 } FIX_ALIASING;
References dev_t, and exitstatus.
Referenced by parse_params().
parse_params()
static action*** parse_params (char ** argv) static
Definition at line 1102 of file find.c.
 {
     enum {
                             OPT_FOLLOW     ,
     IF_FEATURE_FIND_XDEV(   OPT_XDEV       ,)
     IF_FEATURE_FIND_DEPTH(  OPT_DEPTH      ,)
                             PARM_a         ,
                             PARM_o         ,
     IF_FEATURE_FIND_NOT(    PARM_char_not  ,)
 #if ENABLE_DESKTOP
                             PARM_and       ,
                             PARM_or        ,
     IF_FEATURE_FIND_NOT(    PARM_not       ,)
 #endif
                             PARM_print     ,
     IF_FEATURE_FIND_PRINT0( PARM_print0    ,)
     IF_FEATURE_FIND_PRUNE(  PARM_prune     ,)
     IF_FEATURE_FIND_QUIT(   PARM_quit      ,)
     IF_FEATURE_FIND_DELETE( PARM_delete    ,)
     IF_FEATURE_FIND_EMPTY(  PARM_empty     ,)
     IF_FEATURE_FIND_EXEC(   PARM_exec      ,)
     IF_FEATURE_FIND_EXECUTABLE(PARM_executable,)
     IF_FEATURE_FIND_PAREN(  PARM_char_brace,)
     /* All options/actions starting from here require argument */
                             PARM_name      ,
                             PARM_iname     ,
     IF_FEATURE_FIND_PATH(   PARM_path      ,)
 #if ENABLE_DESKTOP
     /* -wholename is a synonym for -path */
     /* We support it because Linux kernel's "make tags" uses it */
     IF_FEATURE_FIND_PATH(   PARM_wholename ,)
 #endif
     IF_FEATURE_FIND_PATH(   PARM_ipath     ,)
     IF_FEATURE_FIND_REGEX(  PARM_regex     ,)
     IF_FEATURE_FIND_TYPE(   PARM_type      ,)
     IF_FEATURE_FIND_PERM(   PARM_perm      ,)
     IF_FEATURE_FIND_MTIME(  PARM_mtime     ,)
     IF_FEATURE_FIND_ATIME(  PARM_atime     ,)
     IF_FEATURE_FIND_CTIME(  PARM_ctime     ,)
     IF_FEATURE_FIND_MMIN(   PARM_mmin      ,)
     IF_FEATURE_FIND_AMIN(   PARM_amin      ,)
     IF_FEATURE_FIND_CMIN(   PARM_cmin      ,)
     IF_FEATURE_FIND_NEWER(  PARM_newer     ,)
     IF_FEATURE_FIND_INUM(   PARM_inum      ,)
     IF_FEATURE_FIND_SAMEFILE(PARM_samefile ,)
     IF_FEATURE_FIND_USER(   PARM_user      ,)
     IF_FEATURE_FIND_GROUP(  PARM_group     ,)
     IF_FEATURE_FIND_SIZE(   PARM_size      ,)
     IF_FEATURE_FIND_CONTEXT(PARM_context   ,)
     IF_FEATURE_FIND_LINKS(  PARM_links     ,)
     IF_FEATURE_FIND_MAXDEPTH(OPT_MINDEPTH,OPT_MAXDEPTH,)
     };
     static const char params[] ALIGN1 =
                             "-follow\0"
     IF_FEATURE_FIND_XDEV(   "-xdev\0"                 )
     IF_FEATURE_FIND_DEPTH(  "-depth\0"                )
                             "-a\0"
                             "-o\0"
     IF_FEATURE_FIND_NOT(    "!\0"       )
 #if ENABLE_DESKTOP
                             "-and\0"
                             "-or\0"
     IF_FEATURE_FIND_NOT(    "-not\0"    )
 #endif
                             "-print\0"
     IF_FEATURE_FIND_PRINT0( "-print0\0" )
     IF_FEATURE_FIND_PRUNE(  "-prune\0"  )
     IF_FEATURE_FIND_QUIT(   "-quit\0"  )
     IF_FEATURE_FIND_DELETE( "-delete\0" )
     IF_FEATURE_FIND_EMPTY(  "-empty\0"  )
     IF_FEATURE_FIND_EXEC(   "-exec\0"   )
     IF_FEATURE_FIND_EXECUTABLE("-executable\0")
     IF_FEATURE_FIND_PAREN(  "(\0"       )
     /* All options/actions starting from here require argument */
                             "-name\0"
                             "-iname\0"
     IF_FEATURE_FIND_PATH(   "-path\0"   )
 #if ENABLE_DESKTOP
     IF_FEATURE_FIND_PATH(   "-wholename\0")
 #endif
     IF_FEATURE_FIND_PATH(   "-ipath\0"  )
     IF_FEATURE_FIND_REGEX(  "-regex\0"  )
     IF_FEATURE_FIND_TYPE(   "-type\0"   )
     IF_FEATURE_FIND_PERM(   "-perm\0"   )
     IF_FEATURE_FIND_MTIME(  "-mtime\0"  )
     IF_FEATURE_FIND_ATIME(  "-atime\0"  )
     IF_FEATURE_FIND_CTIME(  "-ctime\0"  )
     IF_FEATURE_FIND_MMIN(   "-mmin\0"   )
     IF_FEATURE_FIND_AMIN(   "-amin\0"   )
     IF_FEATURE_FIND_CMIN(   "-cmin\0"   )
     IF_FEATURE_FIND_NEWER(  "-newer\0"  )
     IF_FEATURE_FIND_INUM(   "-inum\0"   )
     IF_FEATURE_FIND_SAMEFILE("-samefile\0")
     IF_FEATURE_FIND_USER(   "-user\0"   )
     IF_FEATURE_FIND_GROUP(  "-group\0"  )
     IF_FEATURE_FIND_SIZE(   "-size\0"   )
     IF_FEATURE_FIND_CONTEXT("-context\0")
     IF_FEATURE_FIND_LINKS(  "-links\0"  )
     IF_FEATURE_FIND_MAXDEPTH("-mindepth\0""-maxdepth\0")
     ;
 #if !USE_NESTED_FUNCTION
     struct pp_locals ppl;
 #define appp        (ppl.appp       )
 #define cur_group   (ppl.cur_group  )
 #define cur_action  (ppl.cur_action )
 #define invert_flag (ppl.invert_flag)
 #define ALLOC_ACTION(name) (action_##name*)alloc_action(&ppl, sizeof(action_##name), (action_fp) func_##name)
 #else
     action*** appp;
     unsigned cur_group;
     unsigned cur_action;
     IF_FEATURE_FIND_NOT( bool invert_flag; )
     /* This is the only place in busybox where we use nested function.
      * So far more standard alternatives were bigger. */
     /* Auto decl suppresses "func without a prototype" warning: */
     auto action* alloc_action(int sizeof_struct, action_fp f);
     action* alloc_action(int sizeof_struct, action_fp f)
     {
         action *ap;
         appp[cur_group] = xrealloc(appp[cur_group], (cur_action+2) * sizeof(appp[0][0]));
         appp[cur_group][cur_action++] = ap = xzalloc(sizeof_struct);
         appp[cur_group][cur_action] = NULL;
         ap->f = f;
         IF_FEATURE_FIND_NOT( ap->invert = invert_flag; )
         IF_FEATURE_FIND_NOT( invert_flag = 0; )
         return ap;
     }
 #define ALLOC_ACTION(name) (action_##name*)alloc_action(sizeof(action_##name), (action_fp) func_##name)
 #endif
     cur_group = 0;
     cur_action = 0;
     IF_FEATURE_FIND_NOT( invert_flag = 0; )
     appp = xzalloc(2 * sizeof(appp[0])); /* appp[0],[1] == NULL */
     while (*argv) {
         const char *arg = argv[0];
         int parm = index_in_strings(params, arg);
         const char *arg1 = argv[1];
         dbg("arg:'%s' arg1:'%s' parm:%d PARM_type:%d", arg, arg1, parm, PARM_type);
         if (parm >= PARM_name) {
             /* All options/actions starting from -name require argument */
             if (!arg1)
                 bb_error_msg_and_die(bb_msg_requires_arg, arg);
             argv++;
         }
         /* We can use big switch() here, but on i386
          * it doesn't give smaller code. Other arches? */
 /* Options always return true. They always take effect
  * rather than being processed only when their place in the
  * expression is reached.
  */
         /* Options */
         if (parm == OPT_FOLLOW) {
             dbg("follow enabled: %d", __LINE__);
             G.recurse_flags |= ACTION_FOLLOWLINKS | ACTION_DANGLING_OK;
         }
 #if ENABLE_FEATURE_FIND_XDEV
         else if (parm == OPT_XDEV) {
             dbg("%d", __LINE__);
             G.xdev_on = 1;
         }
 #endif
 #if ENABLE_FEATURE_FIND_MAXDEPTH
         else if (parm == OPT_MINDEPTH || parm == OPT_MINDEPTH + 1) {
             dbg("%d", __LINE__);
             G.minmaxdepth[parm - OPT_MINDEPTH] = xatoi_positive(arg1);
         }
 #endif
 #if ENABLE_FEATURE_FIND_DEPTH
         else if (parm == OPT_DEPTH) {
             dbg("%d", __LINE__);
             G.recurse_flags |= ACTION_DEPTHFIRST;
         }
 #endif
 /* Actions are grouped by operators
  * ( expr )              Force precedence
  * ! expr                True if expr is false
  * -not expr             Same as ! expr
  * expr1 [-a[nd]] expr2  And; expr2 is not evaluated if expr1 is false
  * expr1 -o[r] expr2     Or; expr2 is not evaluated if expr1 is true
  * expr1 , expr2         List; both expr1 and expr2 are always evaluated
  * We implement: (), -a, -o
  */
         /* Operators */
         else if (parm == PARM_a IF_DESKTOP(|| parm == PARM_and)) {
             dbg("%d", __LINE__);
             /* no further special handling required */
         }
         else if (parm == PARM_o IF_DESKTOP(|| parm == PARM_or)) {
             dbg("%d", __LINE__);
             /* start new OR group */
             cur_group++;
             appp = xrealloc(appp, (cur_group+2) * sizeof(appp[0]));
             /*appp[cur_group] = NULL; - already NULL */
             appp[cur_group+1] = NULL;
             cur_action = 0;
         }
 #if ENABLE_FEATURE_FIND_NOT
         else if (parm == PARM_char_not IF_DESKTOP(|| parm == PARM_not)) {
             /* also handles "find ! ! -name 'foo*'" */
             invert_flag ^= 1;
             dbg("invert_flag:%d", invert_flag);
         }
 #endif
         /* Actions */
         else if (parm == PARM_print) {
             dbg("%d", __LINE__);
             G.need_print = 0;
             (void) ALLOC_ACTION(print);
         }
 #if ENABLE_FEATURE_FIND_PRINT0
         else if (parm == PARM_print0) {
             dbg("%d", __LINE__);
             G.need_print = 0;
             (void) ALLOC_ACTION(print0);
         }
 #endif
 #if ENABLE_FEATURE_FIND_PRUNE
         else if (parm == PARM_prune) {
             dbg("%d", __LINE__);
             (void) ALLOC_ACTION(prune);
         }
 #endif
 #if ENABLE_FEATURE_FIND_QUIT
         else if (parm == PARM_quit) {
             dbg("%d", __LINE__);
             (void) ALLOC_ACTION(quit);
         }
 #endif
 #if ENABLE_FEATURE_FIND_DELETE
         else if (parm == PARM_delete) {
             dbg("%d", __LINE__);
             G.need_print = 0;
             G.recurse_flags |= ACTION_DEPTHFIRST;
             (void) ALLOC_ACTION(delete);
         }
 #endif
 #if ENABLE_FEATURE_FIND_EMPTY
         else if (parm == PARM_empty) {
             dbg("%d", __LINE__);
             (void) ALLOC_ACTION(empty);
         }
 #endif
 #if ENABLE_FEATURE_FIND_EXEC
         else if (parm == PARM_exec) {
             int i;
             action_exec *ap;
             IF_FEATURE_FIND_EXEC_PLUS(int all_subst = 0;)
             dbg("%d", __LINE__);
             G.need_print = 0;
             ap = ALLOC_ACTION(exec);
             ap->exec_argv = ++argv; /* first arg after -exec */
             /*ap->exec_argc = 0; - ALLOC_ACTION did it */
             while (1) {
                 if (!*argv) /* did not see ';' or '+' until end */
                     bb_error_msg_and_die(bb_msg_requires_arg, "-exec");
                 // find -exec echo Foo ">{}<" ";"
                 // executes "echo Foo >FILENAME<",
                 // find -exec echo Foo ">{}<" "+"
                 // executes "echo Foo FILENAME1 FILENAME2 FILENAME3...".
                 if ((argv[0][0] == ';' || argv[0][0] == '+')
                  && argv[0][1] == '\0'
                 ) {
 # if ENABLE_FEATURE_FIND_EXEC_PLUS
                     if (argv[0][0] == '+')
                         ap->filelist = xzalloc(sizeof(ap->filelist[0]));
 # endif
                     break;
                 }
                 argv++;
                 ap->exec_argc++;
             }
             if (ap->exec_argc == 0)
                 bb_error_msg_and_die(bb_msg_requires_arg, arg);
             ap->subst_count = xmalloc(ap->exec_argc * sizeof(int));
             i = ap->exec_argc;
             while (i--) {
                 ap->subst_count[i] = count_strstr(ap->exec_argv[i], "{}");
                 IF_FEATURE_FIND_EXEC_PLUS(all_subst += ap->subst_count[i];)
             }
 # if ENABLE_FEATURE_FIND_EXEC_PLUS
             /*
              * coreutils expects {} to appear only once in "-exec +"
              */
             if (all_subst != 1 && ap->filelist)
                 bb_simple_error_msg_and_die("only one '{}' allowed for -exec +");
 # endif
         }
 #endif
 #if ENABLE_FEATURE_FIND_PAREN
         else if (parm == PARM_char_brace) {
             action_paren *ap;
             char **endarg;
             unsigned nested = 1;
             dbg("%d", __LINE__);
             endarg = argv;
             while (1) {
                 if (!*++endarg)
                     bb_simple_error_msg_and_die("unpaired '('");
                 if (LONE_CHAR(*endarg, '('))
                     nested++;
                 else if (LONE_CHAR(*endarg, ')') && !--nested) {
                     *endarg = NULL;
                     break;
                 }
             }
             ap = ALLOC_ACTION(paren);
             ap->subexpr = parse_params(argv + 1);
             *endarg = (char*) ")"; /* restore NULLed parameter */
             argv = endarg;
         }
 #endif
         else if (parm == PARM_name || parm == PARM_iname) {
             action_name *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(name);
             ap->pattern = arg1;
             ap->iname = (parm == PARM_iname);
         }
 #if ENABLE_FEATURE_FIND_PATH
         else if (parm == PARM_path IF_DESKTOP(|| parm == PARM_wholename) || parm == PARM_ipath) {
             action_path *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(path);
             ap->pattern = arg1;
             ap->ipath = (parm == PARM_ipath);
         }
 #endif
 #if ENABLE_FEATURE_FIND_REGEX
         else if (parm == PARM_regex) {
             action_regex *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(regex);
             xregcomp(&ap->compiled_pattern, arg1, 0 /*cflags*/);
         }
 #endif
 #if ENABLE_FEATURE_FIND_TYPE
         else if (parm == PARM_type) {
             action_type *ap;
             ap = ALLOC_ACTION(type);
             ap->type_mask = find_type(arg1);
             dbg("created:type mask:%x", ap->type_mask);
         }
 #endif
 #if ENABLE_FEATURE_FIND_EXECUTABLE
         else if (parm == PARM_executable) {
             (void) ALLOC_ACTION(executable);
         }
 #endif
 #if ENABLE_FEATURE_FIND_PERM
 /* -perm BITS   File's mode bits are exactly BITS (octal or symbolic).
  *              Symbolic modes use mode 0 as a point of departure.
  * -perm -BITS  All of the BITS are set in file's mode.
  * -perm [+/]BITS  At least one of the BITS is set in file's mode.
  */
         else if (parm == PARM_perm) {
             action_perm *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(perm);
             ap->perm_char = arg1[0];
             arg1 = (arg1[0] == '/' ? arg1+1 : plus_minus_num(arg1));
             /*ap->perm_mask = 0; - ALLOC_ACTION did it */
             ap->perm_mask = bb_parse_mode(arg1, ap->perm_mask);
             if (ap->perm_mask == (mode_t)-1)
                 bb_error_msg_and_die("invalid mode '%s'", arg1);
         }
 #endif
 #if ENABLE_FEATURE_FIND_MTIME
         else if (parm == PARM_mtime
 # if ENABLE_FEATURE_FIND_ATIME
          || parm == PARM_atime
 # endif
 # if ENABLE_FEATURE_FIND_CTIME
          || parm == PARM_ctime
 # endif
         ) {
             action_mtime *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(mtime);
 # if ENABLE_FEATURE_FIND_AMIN || ENABLE_FEATURE_FIND_CMIN
             ap->time_type = arg[1];
 # endif
             ap->mtime_char = arg1[0];
             ap->mtime_days = xatoul(plus_minus_num(arg1));
         }
 #endif
 #if ENABLE_FEATURE_FIND_MMIN
         else if (parm == PARM_mmin
 # if ENABLE_FEATURE_FIND_AMIN
          || parm == PARM_amin
 # endif
 # if ENABLE_FEATURE_FIND_CMIN
          || parm == PARM_cmin
 # endif
         ) {
             action_mmin *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(mmin);
 # if ENABLE_FEATURE_FIND_AMIN || ENABLE_FEATURE_FIND_CMIN
             ap->time_type = arg[1];
 # endif
             ap->mmin_char = arg1[0];
             ap->mmin_mins = xatoul(plus_minus_num(arg1));
         }
 #endif
 #if ENABLE_FEATURE_FIND_NEWER
         else if (parm == PARM_newer) {
             struct stat stat_newer;
             action_newer *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(newer);
             xstat(arg1, &stat_newer);
             ap->newer_mtime = stat_newer.st_mtime;
         }
 #endif
 #if ENABLE_FEATURE_FIND_INUM
         else if (parm == PARM_inum) {
             action_inum *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(inum);
             ap->inode_num = xatoul(arg1);
         }
 #endif
 #if ENABLE_FEATURE_FIND_SAMEFILE
         else if (parm == PARM_samefile) {
             action_samefile *ap;
             struct stat stbuf;
             dbg("%d", __LINE__);
             if (G.recurse_flags & (ACTION_FOLLOWLINKS |
                            ACTION_FOLLOWLINKS_L0))
                 xstat(arg1, &stbuf);
             else if (lstat(arg1, &stbuf))
                 bb_perror_msg_and_die("can't stat '%s'", arg1);
             ap = ALLOC_ACTION(samefile);
             ap->inode_num = stbuf.st_ino;
             ap->device = stbuf.st_dev;
         }
 #endif
 #if ENABLE_FEATURE_FIND_USER
         else if (parm == PARM_user) {
             action_user *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(user);
             ap->uid = bb_strtou(arg1, NULL, 10);
             if (errno)
                 ap->uid = xuname2uid(arg1);
         }
 #endif
 #if ENABLE_FEATURE_FIND_GROUP
         else if (parm == PARM_group) {
             action_group *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(group);
             ap->gid = bb_strtou(arg1, NULL, 10);
             if (errno)
                 ap->gid = xgroup2gid(arg1);
         }
 #endif
 #if ENABLE_FEATURE_FIND_SIZE
         else if (parm == PARM_size) {
 /* -size n[bckw]: file uses n units of space
  * b (default): units are 512-byte blocks
  * c: 1 byte
  * k: kilobytes
  * w: 2-byte words
  */
 #if ENABLE_LFS
 #define XATOU_SFX xatoull_sfx
 #else
 #define XATOU_SFX xatoul_sfx
 #endif
             static const struct suffix_mult find_suffixes[] ALIGN_SUFFIX = {
                 { "c", 1 },
                 { "w", 2 },
                 { "", 512 },
                 { "b", 512 },
                 { "k", 1024 },
                 { "", 0 }
             };
             action_size *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(size);
             ap->size_char = arg1[0];
             ap->size = XATOU_SFX(plus_minus_num(arg1), find_suffixes);
         }
 #endif
 #if ENABLE_FEATURE_FIND_CONTEXT
         else if (parm == PARM_context) {
             action_context *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(context);
             /*ap->context = NULL; - ALLOC_ACTION did it */
             /* SELinux headers erroneously declare non-const parameter */
             if (selinux_raw_to_trans_context((char*)arg1, &ap->context))
                 bb_simple_perror_msg(arg1);
         }
 #endif
 #if ENABLE_FEATURE_FIND_LINKS
         else if (parm == PARM_links) {
             action_links *ap;
             dbg("%d", __LINE__);
             ap = ALLOC_ACTION(links);
             ap->links_char = arg1[0];
             ap->links_count = xatoul(plus_minus_num(arg1));
         }
 #endif
         else {
             bb_error_msg("unrecognized: %s", arg);
             bb_show_usage();
         }
         argv++;
     }
     dbg("exiting %s", __func__);
     return appp;
 #undef ALLOC_ACTION
 #undef appp
 #undef cur_action
 #undef invert_flag
 }
References ACTION_DANGLING_OK, ACTION_DEPTHFIRST, ACTION_FOLLOWLINKS, ACTION_FOLLOWLINKS_L0, ALIGN1, ALIGN_SUFFIX, ALLOC_ACTION, alloc_action(), ap, appp, argv, bb_error_msg(), bb_error_msg_and_die(), bb_parse_mode(), bb_perror_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), bb_strtou(), context, count_strstr(), cur_action, cur_group, dbg, errno, f, G, i, IF_DESKTOP(), IF_FEATURE_FIND_EXEC(), index_in_strings(), invert_flag, links, LONE_CHAR, lstat, mmin(), mode_t, mtime, NULL, print, size, stat::st_dev, stat::st_ino, type, xatoi_positive(), XATOU_SFX, xgroup2gid(), xmalloc, xrealloc, xregcomp, xstat(), xuname2uid(), and xzalloc().
Referenced by find_main().
strcpy_upcase()
static char* strcpy_upcase (char * dst, const char * src) static
Definition at line 559 of file find.c.
 {
     char *d = dst;
     while (1) {
         unsigned char ch = *src++;
         if (ch >= 'a' && ch <= 'z')
             ch -= ('a' - 'A');
         *d++ = ch;
         if (ch == '\0')
             break;
     }
     return dst;
 }
References dst, and src.
Variable Documentation
FIX_ALIASING
FIX_ALIASING
Definition at line 495 of file find.c.