Fennix: Userspace/musl/src/time/time_impl.h File Reference
time_impl.h File Reference
#include <time.h>
Functions
hidden int __days_in_month (int, int)
hidden int __month_to_secs (int, int)
hidden long long __year_to_secs (long long, int *)
hidden long long __tm_to_secs (const struct tm *)
hidden const char * __tm_to_tzname (const struct tm *)
hidden int __secs_to_tm (long long, struct tm *)
hidden void __secs_to_zone (long long, int, int *, long *, long *, const char **)
hidden const char * __strftime_fmt_1 (char(*)[100], size_t *, int, const struct tm *, locale_t, int)
Variables
hidden const char __utc []
Function Documentation
__days_in_month()
hidden int __days_in_month (int , int)
__month_to_secs()
hidden int __month_to_secs (int month, int is_leap)
Definition at line 1 of file __month_to_secs.c.
 {
     static const int secs_through_month[] = {
         0, 31*86400, 59*86400, 90*86400,
         120*86400, 151*86400, 181*86400, 212*86400,
         243*86400, 273*86400, 304*86400, 334*86400 };
     int t = secs_through_month[month];
     if (is_leap && month >= 2) t+=86400;
     return t;
 }
References is_leap(), and t.
Referenced by __tm_to_secs(), and rule_to_secs().
__secs_to_tm()
hidden int __secs_to_tm (long long t, struct tm * tm)
Definition at line 11 of file __secs_to_tm.c.
 {
     long long days, secs, years;
     int remdays, remsecs, remyears;
     int qc_cycles, c_cycles, q_cycles;
     int months;
     int wday, yday, leap;
     static const char days_in_month[] = {31,30,31,30,31,31,30,31,30,31,31,29};
     /* Reject time_t values whose year would overflow int */
     if (t < INT_MIN * 31622400LL || t > INT_MAX * 31622400LL)
         return -1;
     secs = t - LEAPOCH;
     days = secs / 86400;
     remsecs = secs % 86400;
     if (remsecs < 0) {
         remsecs += 86400;
         days--;
     }
     wday = (3+days)%7;
     if (wday < 0) wday += 7;
     qc_cycles = days / DAYS_PER_400Y;
     remdays = days % DAYS_PER_400Y;
     if (remdays < 0) {
         remdays += DAYS_PER_400Y;
         qc_cycles--;
     }
     c_cycles = remdays / DAYS_PER_100Y;
     if (c_cycles == 4) c_cycles--;
     remdays -= c_cycles * DAYS_PER_100Y;
     q_cycles = remdays / DAYS_PER_4Y;
     if (q_cycles == 25) q_cycles--;
     remdays -= q_cycles * DAYS_PER_4Y;
     remyears = remdays / 365;
     if (remyears == 4) remyears--;
     remdays -= remyears * 365;
     leap = !remyears && (q_cycles || !c_cycles);
     yday = remdays + 31 + 28 + leap;
     if (yday >= 365+leap) yday -= 365+leap;
     years = remyears + 4*q_cycles + 100*c_cycles + 400LL*qc_cycles;
     for (months=0; days_in_month[months] <= remdays; months++)
         remdays -= days_in_month[months];
     if (months >= 10) {
         months -= 12;
         years++;
     }
     if (years+100 > INT_MAX || years+100 < INT_MIN)
         return -1;
     tm->tm_year = years + 100;
     tm->tm_mon = months + 2;
     tm->tm_mday = remdays + 1;
     tm->tm_wday = wday;
     tm->tm_yday = yday;
     tm->tm_hour = remsecs / 3600;
     tm->tm_min = remsecs / 60 % 60;
     tm->tm_sec = remsecs % 60;
     return 0;
 }
References days_in_month(), DAYS_PER_100Y, DAYS_PER_400Y, DAYS_PER_4Y, INT_MAX, INT_MIN, LEAPOCH, t, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, and tm::tm_year.
Referenced by __gmtime_r(), __localtime_r(), mktime(), and timegm().
__secs_to_zone()
hidden void __secs_to_zone (long long t, int local, int * isdst, long * offset, long * oppoff, const char ** zonename)
Definition at line 365 of file __tz.c.
 {
     LOCK(lock);
     do_tzset();
     if (zi) {
         size_t alt, i = scan_trans(t, local, &alt);
         if (i != -1) {
             *isdst = types[6*i+4];
             *offset = (int32_t)zi_read32(types+6*i);
             *zonename = (const char *)abbrevs + types[6*i+5];
             if (oppoff) *oppoff = (int32_t)zi_read32(types+6*alt);
             UNLOCK(lock);
             return;
         }
     }
     if (!__daylight) goto std;
     /* FIXME: may be broken if DST changes right at year boundary?
      * Also, this could be more efficient.*/
     long long y = t / 31556952 + 70;
     while (__year_to_secs(y, 0) > t) y--;
     while (__year_to_secs(y+1, 0) < t) y++;
     long long t0 = rule_to_secs(r0, y);
     long long t1 = rule_to_secs(r1, y);
     if (!local) {
         t0 += __timezone;
         t1 += dst_off;
     }
     if (t0 < t1) {
         if (t >= t0 && t < t1) goto dst;
         goto std;
     } else {
         if (t >= t1 && t < t0) goto std;
         goto dst;
     }
 std:
     *isdst = 0;
     *offset = -__timezone;
     if (oppoff) *oppoff = -dst_off;
     *zonename = __tzname[0];
     UNLOCK(lock);
     return;
 dst:
     *isdst = 1;
     *offset = -dst_off;
     if (oppoff) *oppoff = -__timezone;
     *zonename = __tzname[1];
     UNLOCK(lock);
 }
References __daylight, __timezone, __tzname, __year_to_secs(), abbrevs, do_tzset(), dst, dst_off, i, local, LOCK, lock, offset, r0, r1, rule_to_secs(), scan_trans(), t, t0, t1, types, UNLOCK, y, zi, and zi_read32().
Referenced by __localtime_r(), and mktime().
__strftime_fmt_1()
hidden const char* __strftime_fmt_1 (char(*) s[100], size_t * l, int f, const struct tm * tm, locale_t loc, int pad)
Definition at line 45 of file strftime.c.
 {
     nl_item item;
     long long val;
     const char *fmt = "-";
     int width = 2, def_pad = '0';
     switch (f) {
     case 'a':
         if (tm->tm_wday > 6U) goto string;
         item = ABDAY_1 + tm->tm_wday;
         goto nl_strcat;
     case 'A':
         if (tm->tm_wday > 6U) goto string;
         item = DAY_1 + tm->tm_wday;
         goto nl_strcat;
     case 'h':
     case 'b':
         if (tm->tm_mon > 11U) goto string;
         item = ABMON_1 + tm->tm_mon;
         goto nl_strcat;
     case 'B':
         if (tm->tm_mon > 11U) goto string;
         item = MON_1 + tm->tm_mon;
         goto nl_strcat;
     case 'c':
         item = D_T_FMT;
         goto nl_strftime;
     case 'C':
         val = (1900LL+tm->tm_year) / 100;
         goto number;
     case 'e':
         def_pad = '_';
     case 'd':
         val = tm->tm_mday;
         goto number;
     case 'D':
         fmt = "%m/%d/%y";
         goto recu_strftime;
     case 'F':
         fmt = "%Y-%m-%d";
         goto recu_strftime;
     case 'g':
     case 'G':
         val = tm->tm_year + 1900LL;
         if (tm->tm_yday < 3 && week_num(tm) != 1) val--;
         else if (tm->tm_yday > 360 && week_num(tm) == 1) val++;
         if (f=='g') val %= 100;
         else width = 4;
         goto number;
     case 'H':
         val = tm->tm_hour;
         goto number;
     case 'I':
         val = tm->tm_hour;
         if (!val) val = 12;
         else if (val > 12) val -= 12;
         goto number;
     case 'j':
         val = tm->tm_yday+1;
         width = 3;
         goto number;
     case 'm':
         val = tm->tm_mon+1;
         goto number;
     case 'M':
         val = tm->tm_min;
         goto number;
     case 'n':
         *l = 1;
         return "\n";
     case 'p':
         item = tm->tm_hour >= 12 ? PM_STR : AM_STR;
         goto nl_strcat;
     case 'r':
         item = T_FMT_AMPM;
         goto nl_strftime;
     case 'R':
         fmt = "%H:%M";
         goto recu_strftime;
     case 's':
         val = __tm_to_secs(tm) - tm->__tm_gmtoff;
         width = 1;
         goto number;
     case 'S':
         val = tm->tm_sec;
         goto number;
     case 't':
         *l = 1;
         return "\t";
     case 'T':
         fmt = "%H:%M:%S";
         goto recu_strftime;
     case 'u':
         val = tm->tm_wday ? tm->tm_wday : 7;
         width = 1;
         goto number;
     case 'U':
         val = (tm->tm_yday + 7U - tm->tm_wday) / 7;
         goto number;
     case 'W':
         val = (tm->tm_yday + 7U - (tm->tm_wday+6U)%7) / 7;
         goto number;
     case 'V':
         val = week_num(tm);
         goto number;
     case 'w':
         val = tm->tm_wday;
         width = 1;
         goto number;
     case 'x':
         item = D_FMT;
         goto nl_strftime;
     case 'X':
         item = T_FMT;
         goto nl_strftime;
     case 'y':
         val = (tm->tm_year + 1900LL) % 100;
         if (val < 0) val = -val;
         goto number;
     case 'Y':
         val = tm->tm_year + 1900LL;
         if (val >= 10000) {
             *l = snprintf(*s, sizeof *s, "+%lld", val);
             return *s;
         }
         width = 4;
         goto number;
     case 'z':
         if (tm->tm_isdst < 0) {
             *l = 0;
             return "";
         }
         *l = snprintf(*s, sizeof *s, "%+.4ld",
             tm->__tm_gmtoff/3600*100 + tm->__tm_gmtoff%3600/60);
         return *s;
     case 'Z':
         if (tm->tm_isdst < 0) {
             *l = 0;
             return "";
         }
         fmt = __tm_to_tzname(tm);
         goto string;
     case '%':
         *l = 1;
         return "%";
     default:
         return 0;
     }
 number:
     switch (pad ? pad : def_pad) {
     case '-': *l = snprintf(*s, sizeof *s, "%lld", val); break;
     case '_': *l = snprintf(*s, sizeof *s, "%*lld", width, val); break;
     case '0':
     default:  *l = snprintf(*s, sizeof *s, "%0*lld", width, val); break;
     }
     return *s;
 nl_strcat:
     fmt = __nl_langinfo_l(item, loc);
 string:
     *l = strlen(fmt);
     return fmt;
 nl_strftime:
     fmt = __nl_langinfo_l(item, loc);
 recu_strftime:
     *l = __strftime_l(*s, sizeof *s, fmt, tm, loc);
     if (!*l) return 0;
     return *s;
 }
References __nl_langinfo_l(), __strftime_l(), tm::__tm_gmtoff, __tm_to_secs(), __tm_to_tzname(), ABDAY_1, ABMON_1, AM_STR, D_FMT, D_T_FMT, DAY_1, f, l, MON_1, number(), pad(), PM_STR, s, snprintf(), string, strlen(), T_FMT, T_FMT_AMPM, tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, tm::tm_year, val, week_num(), and width.
Referenced by __strftime_l(), and __wcsftime_l().
__tm_to_secs()
hidden long long __tm_to_secs (const struct tm * tm)
Definition at line 3 of file __tm_to_secs.c.
 {
     int is_leap;
     long long year = tm->tm_year;
     int month = tm->tm_mon;
     if (month >= 12 || month < 0) {
         int adj = month / 12;
         month %= 12;
         if (month < 0) {
             adj--;
             month += 12;
         }
         year += adj;
     }
     long long t = __year_to_secs(year, &is_leap);
     t += __month_to_secs(month, is_leap);
     t += 86400LL * (tm->tm_mday-1);
     t += 3600LL * tm->tm_hour;
     t += 60LL * tm->tm_min;
     t += tm->tm_sec;
     return t;
 }
References __month_to_secs(), __year_to_secs(), is_leap(), t, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, and tm::tm_year.
Referenced by __strftime_fmt_1(), mktime(), and timegm().
__tm_to_tzname()
hidden const char* __tm_to_tzname (const struct tm * tm)
Definition at line 429 of file __tz.c.
 {
     const void *p = tm->__tm_zone;
     LOCK(lock);
     do_tzset();
     if (p != __utc && p != __tzname[0] && p != __tzname[1] &&
         (!zi || (uintptr_t)p-(uintptr_t)abbrevs >= abbrevs_end - abbrevs))
         p = "";
     UNLOCK(lock);
     return p;
 }
References tm::__tm_zone, __tzname, __utc, abbrevs, abbrevs_end, do_tzset(), LOCK, lock, p, UNLOCK, and zi.
Referenced by __strftime_fmt_1().
__year_to_secs()
hidden long long __year_to_secs (long long year, int * is_leap)
Definition at line 1 of file __year_to_secs.c.
 {
     if (year-2ULL <= 136) {
         int y = year;
         int leaps = (y-68)>>2;
         if (!((y-68)&3)) {
             leaps--;
             if (is_leap) *is_leap = 1;
         } else if (is_leap) *is_leap = 0;
         return 31536000*(y-70) + 86400*leaps;
     }
     int cycles, centuries, leaps, rem;
     if (!is_leap) is_leap = &(int){0};
     cycles = (year-100) / 400;
     rem = (year-100) % 400;
     if (rem < 0) {
         cycles--;
         rem += 400;
     }
     if (!rem) {
         *is_leap = 1;
         centuries = 0;
         leaps = 0;
     } else {
         if (rem >= 200) {
             if (rem >= 300) centuries = 3, rem -= 300;
             else centuries = 2, rem -= 200;
         } else {
             if (rem >= 100) centuries = 1, rem -= 100;
             else centuries = 0;
         }
         if (!rem) {
             *is_leap = 0;
             leaps = 0;
         } else {
             leaps = rem / 4U;
             rem %= 4U;
             *is_leap = !rem;
         }
     }
     leaps += 97*cycles + 24*centuries - *is_leap;
     return (year-100) * 31536000LL + leaps * 86400LL + 946684800 + 86400;
 }
References is_leap(), and y.
Referenced by __secs_to_zone(), __tm_to_secs(), and rule_to_secs().
Variable Documentation
__utc
hidden const char __utc[] extern
Definition at line 27 of file __tz.c.
Referenced by __gmtime_r(), __tm_to_tzname(), do_tzset(), and timegm().