Fennix: Userspace/apps/base/busybox/coreutils/basename.c File Reference
basename.c File Reference
#include "libbb.h"
Functions
int basename_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
basename_main()
int basename_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 51 of file basename.c.
 {
     unsigned opts;
     const char *suffix = NULL;
     /* '+': stop at first non-option */
     opts = getopt32(argv, "^+" "as:"
         "\0" "-1" /* At least one argument */
         , &suffix
     );
     argv += optind;
     do {
         char *s;
         size_t m;
         /* It should strip slash: /abc/def/ -> def */
         s = bb_get_last_path_component_strip(*argv++);
         m = strlen(s);
         if (!opts) {
             if (*argv) {
                 suffix = *argv;
                 if (argv[1])
                     bb_show_usage();
             }
         }
         if (suffix) {
             size_t n = strlen(suffix);
             if ((m > n) && (strcmp(s + m - n, suffix) == 0)) {
                 m -= n;
                 /*s[m] = '\0'; - redundant */
             }
         }
         /* puts(s) will do, but we can do without stdio this way: */
         s[m++] = '\n';
         /* NB: != is correct here: */
         if (full_write(STDOUT_FILENO, s, m) != (ssize_t)m)
             return EXIT_FAILURE;
     } while (opts && *argv);
     return EXIT_SUCCESS;
 }
References argv, bb_get_last_path_component_strip(), bb_show_usage(), EXIT_FAILURE, EXIT_SUCCESS, full_write(), getopt32(), n, NULL, optind, s, STDOUT_FILENO, strcmp, and strlen().