Fennix: Userspace/apps/base/busybox/coreutils/stat.c File Reference
stat.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define buf bb_common_bufsiz1
#define do_stat(filename, format) do_stat(filename)
Typedefs
typedef bool(* statfunc_ptr) (const char *)
Enumerations
enum { OPT_TERSE = (1 << 0) , OPT_DEREFERENCE = (1 << 1) , OPT_FILESYS = (1 << 2) * ENABLE_FEATURE_STAT_FILESYSTEM , OPT_SELINUX = (1 << (2+ENABLE_FEATURE_STAT_FILESYSTEM)) * ENABLE_SELINUX }
Functions
static const char * file_type (const struct stat *st)
static const char * human_time (struct timespec *ts)
static bool do_stat (const char *filename, const char *format)
int stat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
buf
#define buf bb_common_bufsiz1
do_stat
#define do_stat (filename, format) do_stat(filename)
Definition at line 587 of file stat.c.
Typedef Documentation
statfunc_ptr
typedef bool(* statfunc_ptr) (const char *)
Definition at line 120 of file stat.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_TERSE
OPT_DEREFERENCE
OPT_FILESYS
OPT_SELINUX
Definition at line 110 of file stat.c.
      {
     OPT_TERSE       = (1 << 0),
     OPT_DEREFERENCE = (1 << 1),
     OPT_FILESYS     = (1 << 2) * ENABLE_FEATURE_STAT_FILESYSTEM,
     OPT_SELINUX     = (1 << (2+ENABLE_FEATURE_STAT_FILESYSTEM)) * ENABLE_SELINUX,
 };
Function Documentation
do_stat()
static bool do_stat (const char * filename, const char * format) static
Definition at line 589 of file stat.c.
 {
     struct stat statbuf;
 #if ENABLE_SELINUX
     security_context_t scontext = NULL;
     if (option_mask32 & OPT_SELINUX) {
         if ((option_mask32 & OPT_DEREFERENCE
              ? lgetfilecon(filename, &scontext)
              : getfilecon(filename, &scontext)
             ) < 0
         ) {
             bb_simple_perror_msg(filename);
             return 0;
         }
     }
 #endif
     if ((option_mask32 & OPT_DEREFERENCE ? stat : lstat) (filename, &statbuf) != 0) {
         bb_perror_msg("can't stat '%s'", filename);
         return 0;
     }
 #if ENABLE_FEATURE_STAT_FORMAT
     if (format == NULL) {
 # if !ENABLE_SELINUX
         if (option_mask32 & OPT_TERSE) {
             format = "%n %s %b %f %u %g %D %i %h %t %T %X %Y %Z %o";
         } else {
             if (S_ISBLK(statbuf.st_mode) || S_ISCHR(statbuf.st_mode)) {
                 format =
                     "  File: %N\n"
                     "  Size: %-10s\tBlocks: %-10b IO Block: %-6o %F\n"
                     "Device: %Dh/%dd\tInode: %-10i  Links: %-5h"
                     " Device type: %t,%T\n"
                     "Access: (%04a/%10.10A)  Uid: (%5u/%8U)   Gid: (%5g/%8G)\n"
                     "Access: %x\n" "Modify: %y\n" "Change: %z";
             } else {
                 format =
                     "  File: %N\n"
                     "  Size: %-10s\tBlocks: %-10b IO Block: %-6o %F\n"
                     "Device: %Dh/%dd\tInode: %-10i  Links: %h\n"
                     "Access: (%04a/%10.10A)  Uid: (%5u/%8U)   Gid: (%5g/%8G)\n"
                     "Access: %x\n" "Modify: %y\n" "Change: %z";
             }
         }
 # else
         if (option_mask32 & OPT_TERSE) {
             format = (option_mask32 & OPT_SELINUX ?
                 "%n %s %b %f %u %g %D %i %h %t %T %X %Y %Z %o %C\n"
                 :
                 "%n %s %b %f %u %g %D %i %h %t %T %X %Y %Z %o\n"
                 );
         } else {
             if (S_ISBLK(statbuf.st_mode) || S_ISCHR(statbuf.st_mode)) {
                 format = (option_mask32 & OPT_SELINUX ?
                     "  File: %N\n"
                     "  Size: %-10s\tBlocks: %-10b IO Block: %-6o %F\n"
                     "Device: %Dh/%dd\tInode: %-10i  Links: %-5h"
                     " Device type: %t,%T\n"
                     "Access: (%04a/%10.10A)  Uid: (%5u/%8U)   Gid: (%5g/%8G)\n"
                     "   S_Context: %C\n"
                     "Access: %x\n" "Modify: %y\n" "Change: %z"
                     :
                     "  File: %N\n"
                     "  Size: %-10s\tBlocks: %-10b IO Block: %-6o %F\n"
                     "Device: %Dh/%dd\tInode: %-10i  Links: %-5h"
                     " Device type: %t,%T\n"
                     "Access: (%04a/%10.10A)  Uid: (%5u/%8U)   Gid: (%5g/%8G)\n"
                     "Access: %x\n" "Modify: %y\n" "Change: %z"
                     );
             } else {
                 format = (option_mask32 & OPT_SELINUX ?
                     "  File: %N\n"
                     "  Size: %-10s\tBlocks: %-10b IO Block: %-6o %F\n"
                     "Device: %Dh/%dd\tInode: %-10i  Links: %h\n"
                     "Access: (%04a/%10.10A)  Uid: (%5u/%8U)   Gid: (%5g/%8G)\n"
                     "S_Context: %C\n"
                     "Access: %x\n" "Modify: %y\n" "Change: %z"
                     :
                     "  File: %N\n"
                     "  Size: %-10s\tBlocks: %-10b IO Block: %-6o %F\n"
                     "Device: %Dh/%dd\tInode: %-10i  Links: %h\n"
                     "Access: (%04a/%10.10A)  Uid: (%5u/%8U)   Gid: (%5g/%8G)\n"
                     "Access: %x\n" "Modify: %y\n" "Change: %z"
                     );
             }
         }
 # endif
     }
     print_it(format, filename, print_stat, &statbuf IF_SELINUX(, scontext));
 #else   /* FEATURE_STAT_FORMAT */
     if (option_mask32 & OPT_TERSE) {
         printf("%s %llu %llu %lx %lu %lu %llx %llu %lu %lx %lx %lu %lu %lu %lu"
                IF_NOT_SELINUX("\n"),
                filename,
                (unsigned long long) statbuf.st_size,
                (unsigned long long) statbuf.st_blocks,
                (unsigned long) statbuf.st_mode,
                (unsigned long) statbuf.st_uid,
                (unsigned long) statbuf.st_gid,
                (unsigned long long) statbuf.st_dev,
                (unsigned long long) statbuf.st_ino,
                (unsigned long) statbuf.st_nlink,
                (unsigned long) major(statbuf.st_rdev),
                (unsigned long) minor(statbuf.st_rdev),
                (unsigned long) statbuf.st_atime,
                (unsigned long) statbuf.st_mtime,
                (unsigned long) statbuf.st_ctime,
                (unsigned long) statbuf.st_blksize
         );
 # if ENABLE_SELINUX
         if (option_mask32 & OPT_SELINUX)
             printf(" %s\n", scontext);
         else
             bb_putchar('\n');
 # endif
     } else {
         char modestr[12];
         char *linkname = NULL;
         struct passwd *pw_ent;
         struct group *gw_ent;
         gw_ent = getgrgid(statbuf.st_gid);
         pw_ent = getpwuid(statbuf.st_uid);
         if (S_ISLNK(statbuf.st_mode))
             linkname = xmalloc_readlink_or_warn(filename);
         if (linkname) {
             printf("  File: '%s' -> '%s'\n", filename, linkname);
             free(linkname);
         } else {
             printf("  File: '%s'\n", filename);
         }
         printf("  Size: %-10llu\tBlocks: %-10llu IO Block: %-6lu %s\n"
                "Device: %llxh/%llud\tInode: %-10llu  Links: %-5lu",
                (unsigned long long) statbuf.st_size,
                (unsigned long long) statbuf.st_blocks,
                (unsigned long) statbuf.st_blksize,
                file_type(&statbuf),
                (unsigned long long) statbuf.st_dev,
                (unsigned long long) statbuf.st_dev,
                (unsigned long long) statbuf.st_ino,
                (unsigned long) statbuf.st_nlink);
         if (S_ISBLK(statbuf.st_mode) || S_ISCHR(statbuf.st_mode))
             printf(" Device type: %lx,%lx\n",
                    (unsigned long) major(statbuf.st_rdev),
                    (unsigned long) minor(statbuf.st_rdev));
         else
             bb_putchar('\n');
         printf("Access: (%04lo/%10.10s)  Uid: (%5lu/%8s)   Gid: (%5lu/%8s)\n",
                (unsigned long) (statbuf.st_mode & (S_ISUID|S_ISGID|S_ISVTX|S_IRWXU|S_IRWXG|S_IRWXO)),
                bb_mode_string(modestr, statbuf.st_mode),
                (unsigned long) statbuf.st_uid,
                (pw_ent != NULL) ? pw_ent->pw_name : "UNKNOWN",
                (unsigned long) statbuf.st_gid,
                (gw_ent != NULL) ? gw_ent->gr_name : "UNKNOWN");
 # if ENABLE_SELINUX
         if (option_mask32 & OPT_SELINUX)
             printf("   S_Context: %s\n", scontext);
 # endif
         printf("Access: %s\n", human_time(&statbuf.st_atim));
         printf("Modify: %s\n", human_time(&statbuf.st_mtim));
         printf("Change: %s\n", human_time(&statbuf.st_ctim));
     }
 #endif  /* FEATURE_STAT_FORMAT */
     return 1;
 }
References bb_mode_string(), bb_perror_msg(), bb_putchar(), bb_simple_perror_msg(), file_type(), filename, format(), free, getgrgid, getpwuid, group::gr_name, human_time(), lstat, major, minor, NULL, OPT_DEREFERENCE, OPT_SELINUX, OPT_TERSE, option_mask32, printf, passwd::pw_name, S_IRWXG, S_IRWXO, S_IRWXU, S_ISBLK, S_ISCHR, S_ISGID, S_ISLNK, S_ISUID, S_ISVTX, stat::st_atim, stat::st_atime, stat::st_blksize, stat::st_blocks, stat::st_ctim, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtim, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, and xmalloc_readlink_or_warn().
file_type()
static const char* file_type (const struct stat * st) static
Definition at line 123 of file stat.c.
 {
     /* See POSIX 1003.1-2001 XCU Table 4-8 lines 17093-17107
      * for some of these formats.
      * To keep diagnostics grammatical in English, the
      * returned string must start with a consonant.
      */
     if (S_ISREG(st->st_mode))  return st->st_size == 0 ? "regular empty file" : "regular file";
     if (S_ISDIR(st->st_mode))  return "directory";
     if (S_ISBLK(st->st_mode))  return "block special file";
     if (S_ISCHR(st->st_mode))  return "character special file";
     if (S_ISFIFO(st->st_mode)) return "fifo";
     if (S_ISLNK(st->st_mode))  return "symbolic link";
     if (S_ISSOCK(st->st_mode)) return "socket";
 #ifdef S_TYPEISMQ
     if (S_TYPEISMQ(st))        return "message queue";
 #endif
 #ifdef S_TYPEISSEM
     if (S_TYPEISSEM(st))       return "semaphore";
 #endif
 #ifdef S_TYPEISSHM
     if (S_TYPEISSHM(st))       return "shared memory object";
 #endif
 #ifdef S_TYPEISTMO
     if (S_TYPEISTMO(st))       return "typed memory object";
 #endif
     return "weird file";
 }
References S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISLNK, S_ISREG, S_ISSOCK, S_TYPEISMQ, S_TYPEISSEM, S_TYPEISSHM, and S_TYPEISTMO.
Referenced by do_stat().
human_time()
static const char* human_time (struct timespec * ts) static
Definition at line 152 of file stat.c.
 {
     char fmt[sizeof("%Y-%m-%d %H:%M:%S.123456789 %z") + /*paranoia*/ 8];
     /* coreutils 6.3 compat */
 #define buf bb_common_bufsiz1
     setup_common_bufsiz();
     sprintf(stpcpy(fmt, "%Y-%m-%d %H:%M:%S"), ".%09u %%z", (unsigned)ts->tv_nsec);
     strftime(buf, COMMON_BUFSIZE, fmt, localtime(&ts->tv_sec));
     return buf;
 #undef buf
 }
References buf, localtime(), sprintf(), stpcpy(), strftime(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by do_stat().
stat_main()
int stat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 759 of file stat.c.
 {
     IF_FEATURE_STAT_FORMAT(char *format = NULL;)
     int i;
     int ok;
     statfunc_ptr statfunc = do_stat;
 #if ENABLE_FEATURE_STAT_FILESYSTEM || ENABLE_SELINUX
     unsigned opts;
     opts =
 #endif
     getopt32(argv, "^"
         "tL"
         IF_FEATURE_STAT_FILESYSTEM("f")
         IF_SELINUX("Z")
         IF_FEATURE_STAT_FORMAT("c:")
         "\0" "-1" /* min one arg */
         IF_FEATURE_STAT_FORMAT(,&format)
     );
 #if ENABLE_FEATURE_STAT_FILESYSTEM
     if (opts & OPT_FILESYS) /* -f */
         statfunc = do_statfs;
 #endif
 #if ENABLE_SELINUX
     if (opts & OPT_SELINUX) {
         selinux_or_die();
     }
 #endif
     ok = 1;
     argv += optind;
     for (i = 0; argv[i]; ++i)
         ok &= statfunc(argv[i] IF_FEATURE_STAT_FORMAT(, format));
     return (ok ? EXIT_SUCCESS : EXIT_FAILURE);
 }
References argv, do_stat, EXIT_FAILURE, EXIT_SUCCESS, format(), getopt32(), i, NULL, ok, OPT_FILESYS, OPT_SELINUX, optind, and selinux_or_die().