Fennix: Userspace/mlibc/options/posix/generic/strings-stubs.cpp File Reference
strings-stubs.cpp File Reference
#include <strings.h>
#include <string.h>
#include <ctype.h>
#include <bits/ensure.h>
#include <mlibc/strings.hpp>
Namespaces
anonymous_namespace{strings-stubs.cpp}
Functions
char * index (const char *s, int c)
char * rindex (const char *s, int c)
template<typename T >
int anonymous_namespace{strings-stubs.cpp}::ffs_generic (T i)
int ffs (int i)
int ffsl (long i)
int ffsll (long long i)
int strcasecmp (const char *a, const char *b)
int strncasecmp (const char *a, const char *b, size_t size)
Function Documentation
ffs()
int ffs (int i)
Definition at line 44 of file strings-stubs.cpp.
                {
 #ifdef __mlibc_ffs
     return __mlibc_ffs(i);
 #else
     return ffs_generic<int>(i);
 #endif
 }
References i.
Referenced by main().
ffsl()
int ffsl (long i)
Definition at line 59 of file strings-stubs.cpp.
                  {
 #ifdef __mlibc_ffsl
     return __mlibc_ffsl(i);
 #else
     return ffs_generic<long>(i);
 #endif
 }
References i.
Referenced by main().
ffsll()
int ffsll (long long i)
Definition at line 67 of file strings-stubs.cpp.
{
 #ifdef __mlibc_ffsll
     return __mlibc_ffsll(i);
 #else
     return ffs_generic<long long>(i);
 #endif
 }
References i.
Referenced by main().
index()
char* index (const char * s, int c)
Definition at line 9 of file strings-stubs.cpp.
{
     return strchr(s, c);
 }
References c, and strchr().
Referenced by Queue::_numberOf(), Bitmap::Get(), if_indextoname(), InterceptsMemoryOverrun(), main(), Bitmap::operator[](), P_InitSwitchList(), R_MapPlane(), R_ProjectSprite(), R_RenderMaskedSegRange(), R_RenderSegLoop(), resolveInObject(), Bitmap::Set(), mlibc::sys_if_indextoname(), mlibc::sys_ptsname(), and anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt().
rindex()
char* rindex (const char * s, int c)
Definition at line 13 of file strings-stubs.cpp.
{
     return strrchr(s, c);
 }
References c, and strrchr().
Referenced by main().
strcasecmp()
int strcasecmp (const char * a, const char * b)
Definition at line 75 of file strings-stubs.cpp.
{
     size_t i = 0;
     while(true) {
         unsigned char a_byte = tolower(a[i]);
         unsigned char b_byte = tolower(b[i]);
         if(!a_byte && !b_byte)
             return 0;
         // If only one char is null, one of the following cases applies.
         if(a_byte < b_byte)
             return -1;
         if(a_byte > b_byte)
             return 1;
         i++;
     }
 }
References b, i, and tolower.
Referenced by D_DoAdvanceDemo(), DirIsFile(), I_GetMemoryValue(), IdentifyIWADByName(), M_CheckParmWithArgs(), SetMissionForPackName(), and W_AddFile().
strncasecmp()
int strncasecmp (const char * a, const char * b, size_t size)
Definition at line 91 of file strings-stubs.cpp.
{
     return mlibc::strncasecmp(a, b, size);
 }
References b, size, and mlibc::strncasecmp().