Fennix Kernel: Video::Font Class Reference
Video::Font Class Reference
#include <display.hpp>
Public Member Functions
FontInfo GetInfo ()
Font (uintptr_t *Start, uintptr_t *End, FontType Type)
~Font ()
Private Attributes
FontInfo Info
Detailed Description
Definition at line 85 of file display.hpp.
Constructor & Destructor Documentation
Font()
Video::Font::Font (uintptr_t * Start, uintptr_t * End, FontType Type)
Definition at line 24 of file font.cpp.
     {
         trace("Initializing font with start %#lx and end %#lx Type: %d", Start, End, Type);
         this->Info.StartAddress = Start;
         this->Info.EndAddress = End;
         this->Info.Type = Type;
         size_t FontDataLength = End - Start;
         if (Type == FontType::PCScreenFont2)
         {
             this->Info.PSF2Font = new PSF2_FONT;
             PSF2_HEADER *font2 = (PSF2_HEADER *)KernelAllocator.RequestPages(TO_PAGES(FontDataLength + 1));
             memcpy((void *)font2, Start, FontDataLength);
             Memory::Virtual().Map((void *)font2, (void *)font2,
                                   FontDataLength, Memory::PTFlag::RW);
             if (font2->magic[0] != PSF2_MAGIC0 || font2->magic[1] != PSF2_MAGIC1 ||
                 font2->magic[2] != PSF2_MAGIC2 || font2->magic[3] != PSF2_MAGIC3)
             {
                 error("Font2 magic mismatch.");
                 KernelAllocator.FreePages((void *)font2, TO_PAGES(FontDataLength + 1));
                 return;
             }
             this->Info.PSF2Font->Header = font2;
             this->Info.PSF2Font->GlyphBuffer =
                 r_cst(void *, r_cst(uintptr_t, Start) + sizeof(PSF2_HEADER));
             this->Info.Width = font2->width;
             this->Info.Height = font2->height;
         }
         else if (Type == FontType::PCScreenFont1)
         {
             this->Info.PSF1Font = new PSF1_FONT;
             PSF1_HEADER *font1 = (PSF1_HEADER *)Start;
             if (font1->magic[0] != PSF1_MAGIC0 || font1->magic[1] != PSF1_MAGIC1)
                 error("Font1 magic mismatch.");
             uint32_t glyphBufferSize = font1->charsize * 256;
             if (font1->mode == 1) // 512 glyph mode
                 glyphBufferSize = font1->charsize * 512;
             void *glyphBuffer =
                 r_cst(void *, r_cst(uintptr_t, Start) + sizeof(PSF1_HEADER));
             this->Info.PSF1Font->Header = font1;
             this->Info.PSF1Font->GlyphBuffer = glyphBuffer;
             UNUSED(glyphBufferSize); // TODO: Use this in the future?
             // TODO: Get font size.
             this->Info.Width = 16;
             this->Info.Height = 8;
         }
     }
References Video::PSF1_HEADER::charsize, Video::FontInfo::EndAddress, error, Video::_PSF1_FONT::GlyphBuffer, Video::_PSF2_FONT::GlyphBuffer, Video::_PSF1_FONT::Header, Video::_PSF2_FONT::Header, Video::PSF2_HEADER::height, Video::FontInfo::Height, Info, KernelAllocator, Video::PSF1_HEADER::magic, Video::PSF2_HEADER::magic, Memory::Virtual::Map(), memcpy(), Video::PSF1_HEADER::mode, Video::PCScreenFont1, Video::PCScreenFont2, PSF1_MAGIC0, PSF1_MAGIC1, Video::FontInfo::PSF1Font, PSF2_MAGIC0, PSF2_MAGIC1, PSF2_MAGIC2, PSF2_MAGIC3, Video::FontInfo::PSF2Font, Memory::RW, Video::FontInfo::StartAddress, TO_PAGES, trace, Type, Video::FontInfo::Type, UNUSED, Video::PSF2_HEADER::width, and Video::FontInfo::Width.
~Font()
Video::Font::~Font ()
Definition at line 77 of file font.cpp.
     {
     }
Member Function Documentation
GetInfo()
FontInfo Video::Font::GetInfo () inline
Definition at line 91 of file display.hpp.
 { return Info; }
References Info.
Referenced by Video::Display::Display(), CrashHandler::DisplayBottomOverlay(), CrashHandler::DisplayTopOverlay(), vfs::TTYDevice::ioctl(), Main(), and Video::Display::Scroll().
Field Documentation
Info
FontInfo Video::Font::Info private
Definition at line 88 of file display.hpp.
Referenced by Font(), and GetInfo().
The documentation for this class was generated from the following files:
Kernel/include/display.hpp
Kernel/core/video/font.cpp