Fennix: Userspace/apps/base/busybox/libbb/getopt_allopts.c File Reference
getopt_allopts.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC make_all_argv_opts (char **argv)
Function Documentation
make_all_argv_opts()
void FAST_FUNC make_all_argv_opts (char ** argv)
Definition at line 11 of file getopt_allopts.c.
 {
     /* Note: we skip argv[0] */
     while (*++argv) {
         char *p;
         if (argv[0][0] == '-')
             continue;
         /* Neither top nor ps care if "" arg turns into "-" */
         /*if (argv[0][0] == '\0')
             continue;*/
         p = xmalloc(strlen(*argv) + 2);
         *p = '-';
         strcpy(p + 1, *argv);
         *argv = p;
     }
 }
References argv, p, strcpy, strlen(), and xmalloc.
Referenced by ps_main(), and top_main().