Fennix: Userspace/apps/base/busybox/scripts/kconfig/kconfig_load.c File Reference
kconfig_load.c File Reference
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include "lkc.h"
#include "lkc_proto.h"
Macros
#define P(name, type, arg) type (*name ## _p) arg
#define P(name, type, arg)
Functions
void kconfig_load (void)
Macro Definition Documentation
P [1/2]
#define P (name, type, arg) type (*name ## _p) arg
Definition at line 7 of file kconfig_load.c.
P [2/2]
#define P (name, type, arg)
Value:
{                       \
    name ## _p = dlsym(handle, #name);  \
    if ((error = dlerror()))  {     \
        fprintf(stderr, "%s\n", error); \
        exit(1);            \
    }                   \
}
Definition at line 7 of file kconfig_load.c.
Function Documentation
kconfig_load()
void kconfig_load (void)
Definition at line 11 of file kconfig_load.c.
 {
     void *handle;
     char *error;
     handle = dlopen("./libkconfig.so", RTLD_LAZY);
     if (!handle) {
         handle = dlopen("./scripts/kconfig/libkconfig.so", RTLD_LAZY);
         if (!handle) {
             fprintf(stderr, "%s\n", dlerror());
             exit(1);
         }
     }
 #define P(name,type,arg)            \
 {                       \
     name ## _p = dlsym(handle, #name);  \
     if ((error = dlerror()))  {     \
         fprintf(stderr, "%s\n", error); \
         exit(1);            \
     }                   \
 }
 #include "lkc_proto.h"
 #undef P
 }
References dlerror, dlopen, error, exit(), fprintf(), RTLD_LAZY, and stderr.
Referenced by main().