Fennix: Userspace/apps/base/bash/lib/readline/examples/fileman.c File Reference
fileman.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <errno.h>
#include <strings.h>
#include <time.h>
#include <readline/readline.h>
#include <readline/history.h>
Data Structures
struct COMMAND
Functions
char *xmalloc PARAMS ((size_t))
void initialize_readline PARAMS ((void))
void too_dangerous PARAMS ((char *))
int valid_argument PARAMS ((char *, char *))
char * stripwhite ()
COMMAND * find_command ()
char * dupstr (char *s)
int main (int argc, char **argv)
int execute_line (char *line)
COMMAND * find_command (char *name)
char * stripwhite (char *string)
char *command_generator PARAMS ((const char *, int))
char **fileman_completion PARAMS ((const char *, int, int))
void initialize_readline ()
char ** fileman_completion (char *text, int start, int end) const
char * command_generator (char *text, int state) const
int com_list (char *arg)
int com_view (char *arg)
int com_rename (char *arg)
int com_stat (char *arg)
int com_delete (char *arg)
int com_help (char *arg)
int com_cd (char *arg)
int com_pwd (char *ignore)
int com_quit (char *arg)
void too_dangerous (char *caller)
int valid_argument (char *caller, char *arg)
Variables
COMMAND commands []
char * progname
int done
static char syscom [1024]
Data Structure Documentation
COMMAND
struct COMMAND
Definition at line 86 of file fileman.c.
Data Fields
char * doc
rl_icpfunc_t * func
char * name
Function Documentation
com_cd()
int com_cd (char * arg)
Definition at line 443 of file fileman.c.
 {
   if (chdir (arg) == -1)
     {
       perror (arg);
       return 1;
     }
   com_pwd ("");
   return (0);
 }
References chdir(), com_pwd(), and perror().
com_delete()
int com_delete (char * arg)
Definition at line 393 of file fileman.c.
 {
   too_dangerous ("delete");
   return (1);
 }
References too_dangerous().
com_help()
int com_help (char * arg)
Definition at line 403 of file fileman.c.
 {
   register int i;
   int printed = 0;
   for (i = 0; commands[i].name; i++)
     {
       if (!*arg || (strcmp (arg, commands[i].name) == 0))
         {
           printf ("%s\t\t%s.\n", commands[i].name, commands[i].doc);
           printed++;
         }
     }
   if (!printed)
     {
       printf ("No commands match `%s'.  Possibilities are:\n", arg);
       for (i = 0; commands[i].name; i++)
         {
           /* Print in six columns. */
           if (printed == 6)
             {
               printed = 0;
               printf ("\n");
             }
           printf ("%s\t", commands[i].name);
           printed++;
         }
       if (printed)
         printf ("\n");
     }
   return (0);
 }
References commands, i, COMMAND::name, printf, and strcmp.
com_list()
int com_list (char * arg)
Definition at line 329 of file fileman.c.
 {
   if (!arg)
     arg = "";
   sprintf (syscom, "ls -FClg %s", arg);
   return (system (syscom));
 }
References sprintf(), syscom, and system().
com_pwd()
int com_pwd (char * ignore)
Definition at line 458 of file fileman.c.
 {
   char dir[1024], *s;
   s = getcwd (dir, sizeof(dir) - 1);
   if (s == 0)
     {
       printf ("Error getting pwd: %s\n", dir);
       return 1;
     }
   printf ("Current directory is %s\n", dir);
   return 0;
 }
References dir, getcwd, printf, and s.
Referenced by com_cd().
com_quit()
int com_quit (char * arg)
Definition at line 476 of file fileman.c.
 {
   done = 1;
   return (0);
 }
References done.
com_rename()
int com_rename (char * arg)
Definition at line 356 of file fileman.c.
 {
   too_dangerous ("rename");
   return (1);
 }
References too_dangerous().
com_stat()
int com_stat (char * arg)
Definition at line 364 of file fileman.c.
 {
   struct stat finfo;
   if (!valid_argument ("stat", arg))
     return (1);
   if (stat (arg, &finfo) == -1)
     {
       perror (arg);
       return (1);
     }
   printf ("Statistics for `%s':\n", arg);
   printf ("%s has %d link%s, and is %lu byte%s in length.\n",
       arg,
           finfo.st_nlink,
           (finfo.st_nlink == 1) ? "" : "s",
           (unsigned long)finfo.st_size,
           (finfo.st_size == 1) ? "" : "s");
   printf ("Inode Last Change at: %s", ctime (&finfo.st_ctime));
   printf ("      Last access at: %s", ctime (&finfo.st_atime));
   printf ("    Last modified at: %s", ctime (&finfo.st_mtime));
   return (0);
 }
References ctime(), perror(), printf, stat::st_atime, stat::st_ctime, stat::st_mtime, stat::st_nlink, stat::st_size, and valid_argument().
com_view()
int com_view (char * arg)
Definition at line 340 of file fileman.c.
 {
   if (!valid_argument ("view", arg))
     return 1;
 #if defined (__MSDOS__)
   /* more.com doesn't grok slashes in pathnames */
   sprintf (syscom, "less %s", arg);
 #else
   sprintf (syscom, "more %s", arg);
 #endif
   return (system (syscom));
 }
References sprintf(), syscom, system(), and valid_argument().
command_generator()
char* command_generator (char * text, int state) const
Definition at line 288 of file fileman.c.
 {
   static int list_index, len;
   char *name;
   /* If this is a new word to complete, initialize now.  This includes
      saving the length of TEXT for efficiency, and initializing the index
      variable to 0. */
   if (!state)
     {
       list_index = 0;
       len = strlen (text);
     }
   /* Return the next name which partially matches from the command list. */
   while (name = commands[list_index].name)
     {
       list_index++;
       if (strncmp (name, text, len) == 0)
         return (dupstr(name));
     }
   /* If no names matched, then return NULL. */
   return ((char *)NULL);
 }
References commands, dupstr(), len, NULL, state, strlen, strncmp(), and text.
Referenced by fileman_completion().
dupstr()
char* dupstr (char * s)
Definition at line 118 of file fileman.c.
 {
   char *r;
   r = xmalloc (strlen (s) + 1);
   strcpy (r, s);
   return (r);
 }
References s, strcpy, strlen, and xmalloc.
Referenced by command_generator().
execute_line()
int execute_line (char * line)
Definition at line 165 of file fileman.c.
 {
   register int i;
   COMMAND *command;
   char *word;
   /* Isolate the command word. */
   i = 0;
   while (line[i] && whitespace (line[i]))
     i++;
   word = line + i;
   while (line[i] && !whitespace (line[i]))
     i++;
   if (line[i])
     line[i++] = '\0';
   command = find_command (word);
   if (!command)
     {
       fprintf (stderr, "%s: No such command for FileMan.\n", word);
       return (-1);
     }
   /* Get argument to command, if any. */
   while (whitespace (line[i]))
     i++;
   word = line + i;
   /* Call the function. */
   return ((*(command->func)) (word));
 }
References find_command(), fprintf(), i, stderr, and whitespace.
Referenced by main().
fileman_completion()
char** fileman_completion (char * text, int start, int end) const
Definition at line 267 of file fileman.c.
 {
   char **matches;
   matches = (char **)NULL;
   /* If this word is at the start of the line, then it is a command
      to complete.  Otherwise it is the name of a file in the current
      directory. */
   if (start == 0)
     matches = rl_completion_matches (text, command_generator);
   return (matches);
 }
References command_generator(), NULL, rl_completion_matches(), start, and text.
Referenced by initialize_readline().
find_command() [1/2]
COMMAND* find_command ()
Referenced by execute_line().
find_command() [2/2]
COMMAND* find_command (char * name)
Definition at line 205 of file fileman.c.
 {
   register int i;
   for (i = 0; commands[i].name; i++)
     if (strcmp (name, commands[i].name) == 0)
       return (&commands[i]);
   return ((COMMAND *)NULL);
 }
References commands, i, COMMAND::name, NULL, and strcmp.
initialize_readline()
void initialize_readline ()
Definition at line 252 of file fileman.c.
 {
   /* Allow conditional parsing of the ~/.inputrc file. */
   rl_readline_name = "FileMan";
   /* Tell the completer that we want a crack first. */
   rl_attempted_completion_function = fileman_completion;
 }
References fileman_completion(), rl_attempted_completion_function, and rl_readline_name.
Referenced by main().
main()
int main (int argc , char ** argv)
Definition at line 129 of file fileman.c.
 {
   char *line, *s;
   progname = argv[0];
   initialize_readline ();   /* Bind our completer. */
   /* Loop reading and executing lines until the user quits. */
   for ( ; done == 0; )
     {
       line = readline ("FileMan: ");
       if (!line)
         break;
       /* Remove leading and trailing whitespace from the line.
          Then, if there is anything left, add it to the history list
          and execute it. */
       s = stripwhite (line);
       if (*s)
         {
           add_history (s);
           execute_line (s);
         }
       free (line);
     }
   exit (0);
 }
References add_history(), argv, done, execute_line(), exit(), free, initialize_readline(), line, progname, readline(), s, and stripwhite().
PARAMS() [1/6]
void too_dangerous PARAMS ((char *))
PARAMS() [2/6]
int valid_argument PARAMS ((char *, char *))
PARAMS() [3/6]
char* command_generator PARAMS ((const char *, int))
PARAMS() [4/6]
char** fileman_completion PARAMS ((const char *, int, int))
PARAMS() [5/6]
char* xmalloc PARAMS ((size_t))
PARAMS() [6/6]
void initialize_readline PARAMS ((void))
stripwhite() [1/2]
char* stripwhite ()
Referenced by main().
stripwhite() [2/2]
char* stripwhite (char * string)
Definition at line 220 of file fileman.c.
 {
   register char *s, *t;
   for (s = string; whitespace (*s); s++)
     ;
   if (*s == 0)
     return (s);
   t = s + strlen (s) - 1;
   while (t > s && whitespace (*t))
     t--;
   *++t = '\0';
   return s;
 }
References s, strlen, t, and whitespace.
too_dangerous()
void too_dangerous (char * caller)
Definition at line 485 of file fileman.c.
 {
   fprintf (stderr,
            "%s: Too dangerous for me to distribute.  Write it yourself.\n",
            caller);
 }
References fprintf(), and stderr.
Referenced by com_delete(), and com_rename().
valid_argument()
int valid_argument (char * caller, char * arg)
Definition at line 496 of file fileman.c.
 {
   if (!arg || !*arg)
     {
       fprintf (stderr, "%s: Argument required.\n", caller);
       return (0);
     }
   return (1);
 }
References fprintf(), and stderr.
Referenced by com_stat(), and com_view().
Variable Documentation
commands
static const char commands
Initial value:
= {
  { "cd", com_cd, "Change to directory DIR" },
  { "delete", com_delete, "Delete FILE" },
  { "help", com_help, "Display this text" },
  { "?", com_help, "Synonym for `help'" },
  { "list", com_list, "List files in DIR" },
  { "ls", com_list, "Synonym for `list'" },
  { "pwd", com_pwd, "Print the current working directory" },
  { "quit", com_quit, "Quit using Fileman" },
  { "rename", com_rename, "Rename FILE to NEWNAME" },
  { "stat", com_stat, "Print out statistics on FILE" },
  { "view", com_view, "View the contents of FILE" },
  { (char *)NULL, (rl_icpfunc_t *)NULL, (char *)NULL }
}
Definition at line 92 of file fileman.c.
Referenced by com_help(), command_generator(), do_ipaddr(), find_cmd(), find_command(), get_spd(), print_serial_flags(), and tc_main().
done
int done
Definition at line 115 of file fileman.c.
Referenced by __getgr_a(), __getpw_a(), __intscan(), __pthread_cond_timedwait(), aio_cancel(), apply_one_hunk(), BF_crypt(), cbq_print_opt(), com_quit(), cwk_path_join_and_normalize_multiple(), D_Display(), expbackq(), exptilde(), flashcp_main(), inotifyd_main(), main(), microcom_main(), psRsaCrypt(), putgrent(), readtoken1(), wipe_doMelt(), and xsocket_type().
progname
char* progname
Definition at line 112 of file fileman.c.
Referenced by main().
syscom
char syscom[1024] static
Definition at line 325 of file fileman.c.
Referenced by com_list(), and com_view().