Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/d_mode.c File Reference
d_mode.c File Reference
#include "doomtype.h"
#include "d_mode.h"
Functions
boolean D_ValidGameMode (GameMission_t mission, GameMode_t mode)
boolean D_ValidEpisodeMap (GameMission_t mission, GameMode_t mode, int episode, int map)
int D_GetNumEpisodes (GameMission_t mission, GameMode_t mode)
boolean D_ValidGameVersion (GameMission_t mission, GameVersion_t version)
boolean D_IsEpisodeMap (GameMission_t mission)
char * D_GameMissionString (GameMission_t mission)
Variables
struct {
GameMission_t mission
GameMode_t mode
int episode
int map
} valid_modes []
struct {
GameMission_t mission
GameVersion_t version
} valid_versions []
Function Documentation
D_GameMissionString()
char* D_GameMissionString (GameMission_t mission)
Definition at line 182 of file d_mode.c.
 {
     switch (mission)
     {
         case none:
         default:
             return "none";
         case doom:
             return "doom";
         case doom2:
             return "doom2";
         case pack_tnt:
             return "tnt";
         case pack_plut:
             return "plutonia";
         case pack_hacx:
             return "hacx";
         case pack_chex:
             return "chex";
         case heretic:
             return "heretic";
         case hexen:
             return "hexen";
         case strife:
             return "strife";
     }
 }
References doom, doom2, heretic, hexen, none, pack_chex, pack_hacx, pack_plut, pack_tnt, and strife.
Referenced by W_CheckCorrectIWAD().
D_GetNumEpisodes()
int D_GetNumEpisodes (GameMission_t mission, GameMode_t mode)
Definition at line 103 of file d_mode.c.
 {
     int episode;
     episode = 1;
     while (D_ValidEpisodeMap(mission, mode, episode, 1))
     {
         ++episode;
     }
     return episode - 1;
 }
References D_ValidEpisodeMap().
D_IsEpisodeMap()
boolean D_IsEpisodeMap (GameMission_t mission)
Definition at line 161 of file d_mode.c.
 {
     switch (mission)
     {
         case doom:
         case heretic:
         case pack_chex:
             return true;
         case none:
         case hexen:
         case doom2:
         case pack_hacx:
         case pack_tnt:
         case pack_plut:
         case strife:
         default:
             return false;
     }
 }
References doom, doom2, heretic, hexen, none, pack_chex, pack_hacx, pack_plut, pack_tnt, and strife.
D_ValidEpisodeMap()
boolean D_ValidEpisodeMap (GameMission_t mission, GameMode_t mode, int episode, int map)
Definition at line 65 of file d_mode.c.
 {
     int i;
     // Hacks for Heretic secret episodes
     if (mission == heretic)
     {
         if (mode == retail && episode == 6)
         {
             return map >= 1 && map <= 3;
         }
         else if (mode == registered && episode == 4)
         {
             return map == 1;
         }
     }
     // Find the table entry for this mission/mode combination.
     for (i=0; i<arrlen(valid_modes); ++i)
     {
         if (mission == valid_modes[i].mission
          && mode == valid_modes[i].mode)
         {
             return episode >= 1 && episode <= valid_modes[i].episode
                 && map >= 1 && map <= valid_modes[i].map;
         }
     }
     // Unknown mode/mission combination
     return false;
 }
References arrlen, heretic, i, map, registered, retail, and valid_modes.
Referenced by D_GetNumEpisodes().
D_ValidGameMode()
boolean D_ValidGameMode (GameMission_t mission, GameMode_t mode)
Definition at line 50 of file d_mode.c.
 {
     int i;
     for (i=0; i<arrlen(valid_modes); ++i)
     {
         if (valid_modes[i].mode == mode && valid_modes[i].mission == mission)
         {
             return true;
         }
     }
     return false;
 }
References arrlen, i, and valid_modes.
D_ValidGameVersion()
boolean D_ValidGameVersion (GameMission_t mission, GameVersion_t version)
Definition at line 135 of file d_mode.c.
 {
     int i;
     // All Doom variants can use the Doom versions.
     if (mission == doom2 || mission == pack_plut || mission == pack_tnt
      || mission == pack_hacx || mission == pack_chex)
     {
         mission = doom;
     }
     for (i=0; i<arrlen(valid_versions); ++i)
     {
         if (valid_versions[i].mission == mission
          && valid_versions[i].version == version)
         {
             return true;
         }
     }
     return false;
 }
References arrlen, doom, doom2, i, pack_chex, pack_hacx, pack_plut, pack_tnt, and valid_versions.
Variable Documentation
struct { ... } valid_modes[]
Initial value:
= {
    { pack_chex, shareware,  1, 5 },
    { doom,      shareware,  1, 9 },
    { doom,      registered, 3, 9 },
    { doom,      retail,     4, 9 },
    { doom2,     commercial, 1, 32 },
    { pack_tnt,  commercial, 1, 32 },
    { pack_plut, commercial, 1, 32 },
    { pack_hacx, commercial, 1, 32 },
    { heretic,   shareware,  1, 9 },
    { heretic,   registered, 3, 9 },
    { heretic,   retail,     5, 9 },
    { hexen,     commercial, 1, 60 },
    { strife,    commercial, 1, 34 },
}
Referenced by D_ValidEpisodeMap(), and D_ValidGameMode().
struct { ... } valid_versions[]
Initial value:
= {
    { doom,     exe_doom_1_9 },
    { doom,     exe_hacx },
    { doom,     exe_ultimate },
    { doom,     exe_final },
    { doom,     exe_final2 },
    { doom,     exe_chex },
    { heretic,  exe_heretic_1_3 },
    { hexen,    exe_hexen_1_1 },
    { strife,   exe_strife_1_2 },
    { strife,   exe_strife_1_31 },
}
Referenced by D_ValidGameVersion().