Fennix: Userspace/apps/base/busybox/miscutils/partprobe.c File Reference
partprobe.c File Reference
#include <linux/fs.h>
#include "libbb.h"
Macros
#define BLKRRPART _IO(0x12,95)
Functions
int partprobe_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BLKRRPART
#define BLKRRPART _IO(0x12,95)
Definition at line 20 of file partprobe.c.
Function Documentation
partprobe_main()
int partprobe_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 33 of file partprobe.c.
 {
     getopt32(argv, "");
     argv += optind;
     /* "partprobe" with no arguments just does nothing */
     while (*argv) {
         int fd = xopen(*argv, O_RDONLY);
         /*
          * Newer versions of parted scan partition tables themselves and
          * use BLKPG ioctl (BLKPG_DEL_PARTITION / BLKPG_ADD_PARTITION)
          * since this way kernel does not need to know
          * partition table formats.
          * We use good old BLKRRPART:
          */
         ioctl_or_perror_and_die(fd, BLKRRPART, NULL, "%s", *argv);
         close(fd);
         argv++;
     }
     return EXIT_SUCCESS;
 }
References argv, BLKRRPART, close(), EXIT_SUCCESS, fd, getopt32(), ioctl_or_perror_and_die(), NULL, O_RDONLY, optind, and xopen().