Fennix: Userspace/apps/base/busybox/util-linux/acpid.c File Reference
acpid.c File Reference
#include "libbb.h"
#include <syslog.h>
#include <linux/input.h>
Data Structures
struct acpi_event
struct acpi_action
struct globals
Macros
#define EV_SW 0x05
#define EV_KEY 0x01
#define SW_LID 0x00
#define SW_RFKILL_ALL 0x03
#define KEY_POWER 116 /* SC System Power Down */
#define KEY_SLEEP 142 /* SC System Sleep */
#define G (*ptr_to_globals)
#define act_tab (G.act_tab)
#define n_act (G.n_act)
#define evt_tab (G.evt_tab)
#define n_evt (G.n_evt)
#define INIT_G()
Enumerations
enum {
OPT_c = (1 << 0) , OPT_d = (1 << 1) , OPT_e = (1 << 2) , OPT_f = (1 << 3) ,
OPT_l = (1 << 4) , OPT_a = (1 << 5) , OPT_M = (1 << 6) , OPT_p = (1 << 7) * ENABLE_FEATURE_PIDFILE
}
Functions
static void process_event (const char *event)
static const char * find_action (struct input_event *ev, const char *buf)
static void parse_conf_file (const char *filename)
static void parse_map_file (const char *filename)
int acpid_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const struct acpi_event f_evt_tab[] ALIGN_PTR
struct globals FIX_ALIASING
Data Structure Documentation
acpi_event
struct acpi_event
Definition at line 93 of file acpid.c.
Data Fields
const char * desc
uint16_t n_code
uint16_t n_type
const char * s_code
const char * s_type
uint32_t value
acpi_action
struct acpi_action
Definition at line 108 of file acpid.c.
Data Fields
const char * action
const char * key
Macro Definition Documentation
act_tab
#define act_tab (G.act_tab)
Definition at line 125 of file acpid.c.
EV_KEY
#define EV_KEY 0x01
Definition at line 67 of file acpid.c.
EV_SW
#define EV_SW 0x05
Definition at line 64 of file acpid.c.
evt_tab
#define evt_tab (G.evt_tab)
Definition at line 127 of file acpid.c.
G
#define G (*ptr_to_globals)
Definition at line 124 of file acpid.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 129 of file acpid.c.
KEY_POWER
#define KEY_POWER 116 /* SC System Power Down */
Definition at line 76 of file acpid.c.
KEY_SLEEP
#define KEY_SLEEP 142 /* SC System Sleep */
Definition at line 79 of file acpid.c.
n_act
#define n_act (G.n_act)
Definition at line 126 of file acpid.c.
n_evt
#define n_evt (G.n_evt)
Definition at line 128 of file acpid.c.
SW_LID
#define SW_LID 0x00
Definition at line 70 of file acpid.c.
SW_RFKILL_ALL
#define SW_RFKILL_ALL 0x03
Definition at line 73 of file acpid.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_c
OPT_d
OPT_e
OPT_f
OPT_l
OPT_a
OPT_M
OPT_p
Definition at line 82 of file acpid.c.
      {
     OPT_c = (1 << 0),
     OPT_d = (1 << 1),
     OPT_e = (1 << 2),
     OPT_f = (1 << 3),
     OPT_l = (1 << 4),
     OPT_a = (1 << 5),
     OPT_M = (1 << 6),
     OPT_p = (1 << 7) * ENABLE_FEATURE_PIDFILE,
 };
Function Documentation
acpid_main()
int acpid_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 252 of file acpid.c.
 {
     int nfd;
     int opts;
     struct pollfd *pfd;
     const char *opt_dir = "/etc/acpi";
     const char *opt_input = "/dev/input/event";
     const char *opt_logfile = "/var/log/acpid.log";
     const char *opt_action = "/etc/acpid.conf";
     const char *opt_map = "/etc/acpi.map";
 #if ENABLE_FEATURE_PIDFILE
     const char *opt_pidfile = CONFIG_PID_FILE_PATH "/acpid.pid";
 #endif
     INIT_G();
     opts = getopt32(argv, "^"
         "c:de:fl:a:M:"
         IF_FEATURE_PIDFILE("p:")
         IF_FEATURE_ACPID_COMPAT("g:m:s:S:v")
         "\0"
         "df:e--e",
         &opt_dir, &opt_input, &opt_logfile, &opt_action, &opt_map
         IF_FEATURE_PIDFILE(, &opt_pidfile)
         IF_FEATURE_ACPID_COMPAT(, NULL, NULL, NULL, NULL)
     );
     if (!(opts & OPT_f)) {
         /* No -f "Foreground", we go to background */
         bb_daemonize_or_rexec(DAEMON_CLOSE_EXTRA_FDS, argv);
     }
     if (!(opts & OPT_d)) {
         /* No -d "Debug", we log to log file.
          * This includes any output from children.
          */
         xmove_fd(xopen(opt_logfile, O_WRONLY | O_CREAT | O_APPEND), STDOUT_FILENO);
         xdup2(STDOUT_FILENO, STDERR_FILENO);
         /* Also, acpid's messages (but not children) will go to syslog too */
         openlog(applet_name, LOG_PID, LOG_DAEMON);
         logmode = LOGMODE_SYSLOG | LOGMODE_STDIO;
     }
     /* else: -d "Debug", log is not redirected */
     parse_conf_file(opt_action);
     parse_map_file(opt_map);
     xchdir(opt_dir);
     /* We spawn children but don't wait for them. Prevent zombies: */
     bb_signals((1 << SIGCHLD), SIG_IGN);
     // If you enable this, (1) explain why, (2)
     // make sure while(poll) loop below is still interruptible
     // by SIGTERM et al:
     //bb_signals(BB_FATAL_SIGS, record_signo);
     pfd = NULL;
     nfd = 0;
     while (1) {
         int fd;
         char *dev_event;
         dev_event = xasprintf((opts & OPT_e) ? "%s" : "%s%u", opt_input, nfd);
         fd = open(dev_event, O_RDONLY | O_NONBLOCK);
         if (fd < 0) {
             if (nfd == 0)
                 bb_simple_perror_msg_and_die(dev_event);
             break;
         }
         free(dev_event);
         pfd = xrealloc_vector(pfd, 1, nfd);
         pfd[nfd].fd = fd;
         pfd[nfd].events = POLLIN;
         nfd++;
     }
     write_pidfile(opt_pidfile);
     while (safe_poll(pfd, nfd, -1) > 0) {
         int i;
         for (i = 0; i < nfd; i++) {
             const char *event;
             if (!(pfd[i].revents & POLLIN)) {
                 if (pfd[i].revents == 0)
                     continue; /* this fd has nothing */
                 /* Likely POLLERR, POLLHUP, POLLNVAL.
                  * Do not listen on this fd anymore.
                  */
                 close(pfd[i].fd);
                 nfd--;
                 for (; i < nfd; i++)
                     pfd[i].fd = pfd[i + 1].fd;
                 break; /* do poll() again */
             }
             event = NULL;
             if (option_mask32 & OPT_e) {
                 char *buf;
                 int len;
                 buf = xmalloc_reads(pfd[i].fd, NULL);
                 /* buf = "button/power PWRB 00000080 00000000" */
                 len = strlen(buf) - 9;
                 if (len >= 0)
                     buf[len] = '\0';
                 event = find_action(NULL, buf);
                 free(buf);
             } else {
                 struct input_event ev;
                 if (sizeof(ev) != full_read(pfd[i].fd, &ev, sizeof(ev)))
                     continue;
                 if (ev.value != 1 && ev.value != 0)
                     continue;
                 event = find_action(&ev, NULL);
             }
             if (!event)
                 continue;
             /* spawn event handler */
             process_event(event);
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         while (nfd--)
             close(pfd[nfd].fd);
         free(pfd);
     }
     remove_pidfile(opt_pidfile);
     return EXIT_SUCCESS;
 }
References applet_name, argv, bb_daemonize_or_rexec, bb_signals(), bb_simple_perror_msg_and_die(), buf, close(), DAEMON_CLOSE_EXTRA_FDS, EXIT_SUCCESS, fd, find_action(), free, full_read(), getopt32(), i, INIT_G, len, LOG_DAEMON, LOG_PID, logmode, LOGMODE_STDIO, LOGMODE_SYSLOG, NULL, O_APPEND, O_CREAT, O_NONBLOCK, O_RDONLY, O_WRONLY, open(), openlog(), OPT_d, OPT_e, OPT_f, option_mask32, parse_conf_file(), parse_map_file(), pfd, POLLIN, process_event(), remove_pidfile, pollfd::revents, safe_poll(), SIG_IGN, SIGCHLD, STDERR_FILENO, STDOUT_FILENO, strlen, write_pidfile(), xasprintf(), xchdir(), xdup2(), xmalloc_reads(), xmove_fd(), xopen(), and xrealloc_vector.
find_action()
static const char* find_action (struct input_event * ev, const char * buf) static
Definition at line 166 of file acpid.c.
 {
     const char *action = NULL;
     int i;
     // map event
     for (i = 0; i < n_evt; i++) {
         if (ev) {
             if (ev->type == evt_tab[i].n_type && ev->code == evt_tab[i].n_code && ev->value == evt_tab[i].value) {
                 action = evt_tab[i].desc;
                 break;
             }
         }
         if (buf) {
             if (is_prefixed_with(evt_tab[i].desc, buf)) {
                 action = evt_tab[i].desc;
                 break;
             }
         }
     }
     // get action
     if (action) {
         for (i = 0; i < n_act; i++) {
             if (strstr(action, act_tab[i].key)) {
                 action = act_tab[i].action;
                 break;
             }
         }
     }
     return action;
 }
References act_tab, buf, evt_tab, i, is_prefixed_with(), n_act, n_evt, NULL, and strstr().
Referenced by acpid_main().
parse_conf_file()
static void parse_conf_file (const char * filename) static
Definition at line 201 of file acpid.c.
 {
     parser_t *parser;
     char *tokens[2];
     parser = config_open2(filename, fopen_for_read);
     if (parser) {
         while (config_read(parser, tokens, 2, 2, "# \t", PARSE_NORMAL)) {
             act_tab = xrealloc_vector(act_tab, 1, n_act);
             act_tab[n_act].key = xstrdup(tokens[0]);
             act_tab[n_act].action = xstrdup(tokens[1]);
             n_act++;
         }
         config_close(parser);
     } else {
         act_tab = (void*)f_act_tab;
         n_act = ARRAY_SIZE(f_act_tab);
     }
 }
References act_tab, ARRAY_SIZE, config_close(), config_open2(), config_read, filename, fopen_for_read(), n_act, PARSE_NORMAL, parser, xrealloc_vector, and xstrdup().
Referenced by acpid_main().
parse_map_file()
static void parse_map_file (const char * filename) static
Definition at line 222 of file acpid.c.
 {
     parser_t *parser;
     char *tokens[6];
     parser = config_open2(filename, fopen_for_read);
     if (parser) {
         while (config_read(parser, tokens, 6, 6, "# \t", PARSE_NORMAL)) {
             evt_tab = xrealloc_vector(evt_tab, 1, n_evt);
             evt_tab[n_evt].s_type = xstrdup(tokens[0]);
             evt_tab[n_evt].n_type = xstrtou(tokens[1], 16);
             evt_tab[n_evt].s_code = xstrdup(tokens[2]);
             evt_tab[n_evt].n_code = xatou16(tokens[3]);
             evt_tab[n_evt].value = xatoi_positive(tokens[4]);
             evt_tab[n_evt].desc = xstrdup(tokens[5]);
             n_evt++;
         }
         config_close(parser);
     } else {
         evt_tab = (void*)f_evt_tab;
         n_evt = ARRAY_SIZE(f_evt_tab);
     }
 }
References ARRAY_SIZE, config_close(), config_open2(), config_read, evt_tab, filename, fopen_for_read(), n_evt, PARSE_NORMAL, parser, xatoi_positive(), xatou16(), xrealloc_vector, xstrdup(), and xstrtou().
Referenced by acpid_main().
process_event()
static void process_event (const char * event) static
Definition at line 145 of file acpid.c.
 {
     struct stat st;
     char *handler = xasprintf("./%s", event);
     const char *args[] = { "run-parts", handler, NULL };
     // log the event
     bb_simple_error_msg(event);
     // spawn handler
     // N.B. run-parts would require scripts to have #!/bin/sh
     // handler is directory? -> use run-parts
     // handler is file? -> run it directly
     if (0 == stat(event, &st))
         spawn((char **)args + (0==(st.st_mode & S_IFDIR)));
     else
         bb_simple_perror_msg(event);
     free(handler);
 }
References bb_simple_error_msg(), bb_simple_perror_msg(), free, handler(), NULL, S_IFDIR, spawn(), stat(), and xasprintf().
Referenced by acpid_main().
Variable Documentation
ALIGN_PTR
const struct acpi_action f_act_tab [] ALIGN_PTR static
Initial value:
= {
    { "EV_KEY", 0x01, "KEY_POWER", 116, 1, "button/power PWRF 00000080" },
    { "EV_KEY", 0x01, "KEY_POWER", 116, 1, "button/power PWRB 00000080" },
    { "EV_SW", 0x05, "SW_LID", 0x00, 1, "button/lid LID0 00000080" },
}
Definition at line 102 of file acpid.c.
FIX_ALIASING
struct globals FIX_ALIASING