Fennix: ACPI::DSDT Class Reference
ACPI::DSDT Class Reference
#include <acpi.hpp>
Public Member Functions
void Reboot ()
void Shutdown ()
DSDT (ACPI *acpi)
~DSDT ()
Data Fields
bool ACPIShutdownSupported = false
Private Member Functions
void OnInterruptReceived (CPU::TrapFrame *Frame)
Private Attributes
uint32_t SMI_CMD = 0
uint8_t ACPI_ENABLE = 0
uint8_t ACPI_DISABLE = 0
uint32_t PM1a_CNT = 0
uint32_t PM1b_CNT = 0
uint16_t SLP_TYPa = 0
uint16_t SLP_TYPb = 0
uint16_t SLP_EN = 0
uint16_t SCI_EN = 0
uint8_t PM1_CNT_LEN = 0
ACPI * acpi
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 358 of file acpi.hpp.
Constructor & Destructor Documentation
DSDT()
ACPI::DSDT::DSDT (ACPI * acpi)
Definition at line 236 of file dsdt.cpp.
                          : Interrupts::Handler(acpi->FADT->SCI_Interrupt, true)
     {
         /* TODO: AML Interpreter */
         this->acpi = acpi;
         uint64_t Address = ((IsCanonical(acpi->FADT->X_Dsdt) && acpi->XSDTSupported) ? acpi->FADT->X_Dsdt : acpi->FADT->Dsdt);
         uint8_t *S5Address = (uint8_t *)(Address) + 36;
         ACPI::ACPI::ACPIHeader *Header = (ACPI::ACPI::ACPIHeader *)Address;
         Memory::Virtual vmm;
         if (!vmm.Check(Header))
         {
             warn("DSDT is not mapped");
             debug("DSDT: %#lx", Address);
             vmm.Map(Header, Header, Memory::RW);
         }
         size_t Length = Header->Length;
         vmm.Map(Header, Header, Length, Memory::RW);
         while (Length-- > 0)
         {
             if (!memcmp(S5Address, "_S5_", 4))
                 break;
             S5Address++;
         }
         if (Length <= 0)
         {
             warn("_S5_ not present in ACPI");
             return;
         }
         if ((*(S5Address - 1) == 0x08 ||
              (*(S5Address - 2) == 0x08 &&
               *(S5Address - 1) == '\\')) &&
             *(S5Address + 4) == 0x12)
         {
             S5Address += 5;
             S5Address += ((*S5Address & 0xC0) >> 6) + 2;
             if (*S5Address == 0x0A)
                 S5Address++;
             SLP_TYPa = s_cst(uint16_t, *(S5Address) << 10);
             S5Address++;
             if (*S5Address == 0x0A)
                 S5Address++;
             SLP_TYPb = s_cst(uint16_t, *(S5Address) << 10);
             SMI_CMD = acpi->FADT->SMI_CommandPort;
             ACPI_ENABLE = acpi->FADT->AcpiEnable;
             ACPI_DISABLE = acpi->FADT->AcpiDisable;
             PM1a_CNT = acpi->FADT->PM1aControlBlock;
             PM1b_CNT = acpi->FADT->PM1bControlBlock;
             PM1_CNT_LEN = acpi->FADT->PM1ControlLength;
             SLP_EN = 1 << 13;
             SCI_EN = 1;
             KPrint("ACPI Shutdown is supported");
             ACPIShutdownSupported = true;
             {
                 const uint16_t value = /*ACPI_TIMER |*/ ACPI_BUSMASTER | ACPI_GLOBAL |
                                        ACPI_POWER_BUTTON | ACPI_SLEEP_BUTTON | ACPI_RTC_ALARM |
                                        ACPI_PCIE_WAKE | ACPI_WAKE;
                 uint16_t a = s_cst(uint16_t, acpi->FADT->PM1aEventBlock + (acpi->FADT->PM1EventLength / 2));
                 uint16_t b = s_cst(uint16_t, acpi->FADT->PM1bEventBlock + (acpi->FADT->PM1EventLength / 2));
                 debug("SCI Event: %#x [a:%#x b:%#x]", value, a, b);
                 if (acpi->FADT->PM1aEventBlock)
                     outw(a, value);
                 if (acpi->FADT->PM1bEventBlock)
                     outw(b, value);
             }
             {
                 uint16_t a = 0, b = 0;
                 if (acpi->FADT->PM1aEventBlock)
                 {
                     a = inw(s_cst(uint16_t, acpi->FADT->PM1aEventBlock));
                     outw(s_cst(uint16_t, acpi->FADT->PM1aEventBlock), a);
                 }
                 if (acpi->FADT->PM1bEventBlock)
                 {
                     b = inw(s_cst(uint16_t, acpi->FADT->PM1bEventBlock));
                     outw(s_cst(uint16_t, acpi->FADT->PM1bEventBlock), b);
                 }
             }
             ((APIC::APIC *)Interrupts::apic[0])->RedirectIRQ(0, uint8_t(acpi->FADT->SCI_Interrupt), 1);
             return;
         }
         warn("Failed to parse _S5_ in ACPI");
         SCI_EN = 0;
     }
References acpi, ACPI_BUSMASTER, ACPI_DISABLE, ACPI_ENABLE, ACPI_GLOBAL, ACPI_PCIE_WAKE, ACPI_POWER_BUTTON, ACPI_RTC_ALARM, ACPI_SLEEP_BUTTON, ACPI_WAKE, ACPI::ACPI::FADTHeader::AcpiDisable, ACPI::ACPI::FADTHeader::AcpiEnable, ACPIShutdownSupported, Address, Memory::Virtual::Check(), debug, ACPI::ACPI::FADTHeader::Dsdt, ACPI::ACPI::FADT, inw(), ACPI::IsCanonical(), KPrint(), ACPI::ACPI::ACPIHeader::Length, Length, Memory::Virtual::Map(), memcmp(), outw(), PM1_CNT_LEN, PM1a_CNT, ACPI::ACPI::FADTHeader::PM1aControlBlock, ACPI::ACPI::FADTHeader::PM1aEventBlock, PM1b_CNT, ACPI::ACPI::FADTHeader::PM1bControlBlock, ACPI::ACPI::FADTHeader::PM1bEventBlock, ACPI::ACPI::FADTHeader::PM1ControlLength, ACPI::ACPI::FADTHeader::PM1EventLength, Memory::RW, SCI_EN, ACPI::ACPI::FADTHeader::SCI_Interrupt, SLP_EN, SLP_TYPa, SLP_TYPb, SMI_CMD, ACPI::ACPI::FADTHeader::SMI_CommandPort, value, warn, ACPI::ACPI::FADTHeader::X_Dsdt, and ACPI::ACPI::XSDTSupported.
~DSDT()
ACPI::DSDT::~DSDT ()
Definition at line 331 of file dsdt.cpp.
     {
     }
Member Function Documentation
OnInterruptReceived()
void ACPI::DSDT::OnInterruptReceived (CPU::TrapFrame * Frame) private virtual
Reimplemented from Interrupts::Handler.
Definition at line 59 of file dsdt.cpp.
     {
         debug("SCI Handle Triggered");
         uint16_t Event = 0;
         {
             uint16_t a = 0, b = 0;
             if (acpi->FADT->PM1aEventBlock)
             {
                 a = inw(s_cst(uint16_t, acpi->FADT->PM1aEventBlock));
                 outw(s_cst(uint16_t, acpi->FADT->PM1aEventBlock), a);
             }
             if (acpi->FADT->PM1bEventBlock)
             {
                 b = inw(s_cst(uint16_t, acpi->FADT->PM1bEventBlock));
                 outw(s_cst(uint16_t, acpi->FADT->PM1bEventBlock), b);
             }
             Event = a | b;
         }
 #ifdef DEBUG
         char dbgEvStr[128];
         dbgEvStr[0] = '\0';
         if (Event & ACPI_BUSMASTER)
             strcat(dbgEvStr, "BUSMASTER ");
         if (Event & ACPI_GLOBAL)
             strcat(dbgEvStr, "GLOBAL ");
         if (Event & ACPI_POWER_BUTTON)
             strcat(dbgEvStr, "POWER_BUTTON ");
         if (Event & ACPI_SLEEP_BUTTON)
             strcat(dbgEvStr, "SLEEP_BUTTON ");
         if (Event & ACPI_RTC_ALARM)
             strcat(dbgEvStr, "RTC_ALARM ");
         if (Event & ACPI_PCIE_WAKE)
             strcat(dbgEvStr, "PCIE_WAKE ");
         if (Event & ACPI_WAKE)
             strcat(dbgEvStr, "WAKE ");
         if (Event & ACPI_TIMER)
             strcat(dbgEvStr, "ACPI_TIMER ");
         KPrint("SCI Event: %s", dbgEvStr);
 #endif
         if (Event & ACPI_BUSMASTER)
         {
             fixme("ACPI Busmaster");
         }
         else if (Event & ACPI_GLOBAL)
         {
             fixme("ACPI Global");
         }
         else if (Event & ACPI_POWER_BUTTON)
         {
             if (ExceptionLock.load())
             {
                 this->Shutdown();
                 CPU::Stop();
             }
             Tasking::PCB *pcb = thisProcess;
             if (pcb && !pcb->GetContext()->IsPanic())
             {
                 Tasking::Task *ctx = pcb->GetContext();
                 ctx->CreateThread(ctx->GetKernelProcess(),
                                   Tasking::IP(KST_Shutdown))
                     ->Rename("Shutdown");
             }
             else
                 KernelShutdownThread(false);
         }
         else if (Event & ACPI_SLEEP_BUTTON)
         {
             fixme("ACPI Sleep Button");
         }
         else if (Event & ACPI_RTC_ALARM)
         {
             fixme("ACPI RTC Alarm");
         }
         else if (Event & ACPI_PCIE_WAKE)
         {
             fixme("ACPI PCIe Wake");
         }
         else if (Event & ACPI_WAKE)
         {
             fixme("ACPI Wake");
         }
         else if (Event & ACPI_TIMER)
         {
             fixme("ACPI Timer");
         }
         else
         {
             error("ACPI unknown event %#lx on CPU %d",
                   Event, GetCurrentCPU()->ID);
             KPrint("ACPI unknown event %#lx on CPU %d",
                    Event, GetCurrentCPU()->ID);
         }
     }
References acpi, ACPI_BUSMASTER, ACPI_GLOBAL, ACPI_PCIE_WAKE, ACPI_POWER_BUTTON, ACPI_RTC_ALARM, ACPI_SLEEP_BUTTON, ACPI_TIMER, ACPI_WAKE, debug, error, ExceptionLock, ACPI::ACPI::FADT, fixme, Tasking::PCB::GetContext(), GetCurrentCPU(), ID, inw(), Tasking::Task::IsPanic(), KernelShutdownThread(), KPrint(), KST_Shutdown(), outw(), ACPI::ACPI::FADTHeader::PM1aEventBlock, ACPI::ACPI::FADTHeader::PM1bEventBlock, Shutdown(), CPU::Stop(), strcat, and thisProcess.
Reboot()
void ACPI::DSDT::Reboot ()
Definition at line 200 of file dsdt.cpp.
     {
         trace("Rebooting...");
         switch (acpi->FADT->ResetReg.AddressSpace)
         {
         case ACPI_GAS_MMIO:
         {
             *(uint8_t *)(acpi->FADT->ResetReg.Address) = acpi->FADT->ResetValue;
             break;
         }
         case ACPI_GAS_IO:
         {
             outb(s_cst(uint16_t, acpi->FADT->ResetReg.Address), acpi->FADT->ResetValue);
             break;
         }
         case ACPI_GAS_PCI:
         {
             fixme("ACPI_GAS_PCI not supported.");
             /*
                 seg      - 0
                 bus      - 0
                 dev      - (FADT->ResetReg.Address >> 32) & 0xFFFF
                 function - (FADT->ResetReg.Address >> 16) & 0xFFFF
                 offset   - FADT->ResetReg.Address & 0xFFFF
                 value    - FADT->ResetValue
             */
             break;
         }
         default:
         {
             error("Unknown reset register address space: %d", acpi->FADT->ResetReg.AddressSpace);
             break;
         }
         }
     }
References acpi, ACPI_GAS_IO, ACPI_GAS_MMIO, ACPI_GAS_PCI, ACPI::ACPI::GenericAddressStructure::Address, ACPI::ACPI::GenericAddressStructure::AddressSpace, error, ACPI::ACPI::FADT, fixme, outb(), ACPI::ACPI::FADTHeader::ResetReg, ACPI::ACPI::FADTHeader::ResetValue, and trace.
Shutdown()
void ACPI::DSDT::Shutdown ()
Definition at line 155 of file dsdt.cpp.
     {
         trace("Shutting down...");
         if (SCI_EN != 1)
         {
             error("ACPI Shutdown not supported");
             return;
         }
         if (inw(s_cst(uint16_t, PM1a_CNT) & SCI_EN) == 0)
         {
             KPrint("ACPI was disabled, enabling...");
             if (SMI_CMD == 0 || ACPI_ENABLE == 0)
             {
                 error("ACPI Shutdown not supported");
                 KPrint("ACPI Shutdown not supported");
                 return;
             }
             outb(s_cst(uint16_t, SMI_CMD), ACPI_ENABLE);
             uint16_t Timeout = 3000;
             while ((inw(s_cst(uint16_t, PM1a_CNT)) & SCI_EN) == 0 && Timeout-- > 0)
                 ;
             if (Timeout == 0)
             {
                 error("ACPI Shutdown not supported");
                 KPrint("ACPI Shutdown not supported");
                 return;
             }
             if (PM1b_CNT)
             {
                 Timeout = 3000;
                 while ((inw(s_cst(uint16_t, PM1b_CNT)) & SCI_EN) == 0 && Timeout-- > 0)
                     ;
             }
         }
         outw(s_cst(uint16_t, PM1a_CNT), SLP_TYPa | SLP_EN);
         if (PM1b_CNT)
             outw(s_cst(uint16_t, PM1b_CNT), SLP_TYPb | SLP_EN);
     }
References ACPI_ENABLE, error, inw(), KPrint(), outb(), outw(), PM1a_CNT, PM1b_CNT, SCI_EN, SLP_EN, SLP_TYPa, SLP_TYPb, SMI_CMD, and trace.
Referenced by OnInterruptReceived().
Field Documentation
acpi
ACPI* ACPI::DSDT::acpi private
Definition at line 372 of file acpi.hpp.
Referenced by DSDT(), OnInterruptReceived(), and Reboot().
ACPI_DISABLE
uint8_t ACPI::DSDT::ACPI_DISABLE = 0 private
Definition at line 363 of file acpi.hpp.
Referenced by DSDT().
ACPI_ENABLE
uint8_t ACPI::DSDT::ACPI_ENABLE = 0 private
Definition at line 362 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
ACPIShutdownSupported
bool ACPI::DSDT::ACPIShutdownSupported = false
Definition at line 376 of file acpi.hpp.
Referenced by DSDT().
PM1_CNT_LEN
uint8_t ACPI::DSDT::PM1_CNT_LEN = 0 private
Definition at line 370 of file acpi.hpp.
Referenced by DSDT().
PM1a_CNT
uint32_t ACPI::DSDT::PM1a_CNT = 0 private
Definition at line 364 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
PM1b_CNT
uint32_t ACPI::DSDT::PM1b_CNT = 0 private
Definition at line 365 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
SCI_EN
uint16_t ACPI::DSDT::SCI_EN = 0 private
Definition at line 369 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
SLP_EN
uint16_t ACPI::DSDT::SLP_EN = 0 private
Definition at line 368 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
SLP_TYPa
uint16_t ACPI::DSDT::SLP_TYPa = 0 private
Definition at line 366 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
SLP_TYPb
uint16_t ACPI::DSDT::SLP_TYPb = 0 private
Definition at line 367 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
SMI_CMD
uint32_t ACPI::DSDT::SMI_CMD = 0 private
Definition at line 361 of file acpi.hpp.
Referenced by DSDT(), and Shutdown().
The documentation for this class was generated from the following files:
Kernel/include/acpi.hpp
Kernel/core/dsdt.cpp