Fennix Userspace: Userspace/apps/base/bash/lib/readline/readline.h File Reference
readline.h File Reference
#include <readline/rlstdc.h>
#include <readline/rltypedefs.h>
#include <readline/keymaps.h>
#include <readline/tilde.h>
Data Structures
struct undo_list
struct _funmap
struct readline_state
Macros
#define RL_READLINE_VERSION 0x0802 /* Readline 8.2 */
#define RL_VERSION_MAJOR 8
#define RL_VERSION_MINOR 2
#define rl_clear_timeout() rl_set_timeout (0, 0)
#define rl_symbolic_link_hook rl_directory_completion_hook
#define READERR (-2)
#define RL_PROMPT_START_IGNORE '\001'
#define RL_PROMPT_END_IGNORE '\002'
#define NO_MATCH 0
#define SINGLE_MATCH 1
#define MULT_MATCH 2
#define RL_STATE_NONE 0x000000 /* no state; before first call */
#define RL_STATE_INITIALIZING 0x0000001 /* initializing */
#define RL_STATE_INITIALIZED 0x0000002 /* initialization done */
#define RL_STATE_TERMPREPPED 0x0000004 /* terminal is prepped */
#define RL_STATE_READCMD 0x0000008 /* reading a command key */
#define RL_STATE_METANEXT 0x0000010 /* reading input after ESC */
#define RL_STATE_DISPATCHING 0x0000020 /* dispatching to a command */
#define RL_STATE_MOREINPUT 0x0000040 /* reading more input in a command function */
#define RL_STATE_ISEARCH 0x0000080 /* doing incremental search */
#define RL_STATE_NSEARCH 0x0000100 /* doing non-inc search */
#define RL_STATE_SEARCH 0x0000200 /* doing a history search */
#define RL_STATE_NUMERICARG 0x0000400 /* reading numeric argument */
#define RL_STATE_MACROINPUT 0x0000800 /* getting input from a macro */
#define RL_STATE_MACRODEF 0x0001000 /* defining keyboard macro */
#define RL_STATE_OVERWRITE 0x0002000 /* overwrite mode */
#define RL_STATE_COMPLETING 0x0004000 /* doing completion */
#define RL_STATE_SIGHANDLER 0x0008000 /* in readline sighandler */
#define RL_STATE_UNDOING 0x0010000 /* doing an undo */
#define RL_STATE_INPUTPENDING 0x0020000 /* rl_execute_next called */
#define RL_STATE_TTYCSAVED 0x0040000 /* tty special chars saved */
#define RL_STATE_CALLBACK 0x0080000 /* using the callback interface */
#define RL_STATE_VIMOTION 0x0100000 /* reading vi motion arg */
#define RL_STATE_MULTIKEY 0x0200000 /* reading multiple-key command */
#define RL_STATE_VICMDONCE 0x0400000 /* entered vi command mode at least once */
#define RL_STATE_CHARSEARCH 0x0800000 /* vi mode char search */
#define RL_STATE_REDISPLAYING 0x1000000 /* updating terminal display */
#define RL_STATE_DONE 0x2000000 /* done; accepted line */
#define RL_STATE_TIMEOUT 0x4000000 /* done; timed out */
#define RL_STATE_EOF 0x8000000 /* done; got eof on read */
#define RL_SETSTATE(x) (rl_readline_state |= (x))
#define RL_UNSETSTATE(x) (rl_readline_state &= ~(x))
#define RL_ISSTATE(x) (rl_readline_state & (x))
Typedefs
typedef struct undo_list UNDO_LIST
typedef struct _funmap FUNMAP
Enumerations
enum undo_code { UNDO_DELETE , UNDO_INSERT , UNDO_BEGIN , UNDO_END }
Functions
int rl_digit_argument (int, int)
int rl_universal_argument (int, int)
int rl_forward_byte (int, int)
int rl_forward_char (int, int)
int rl_forward (int, int)
int rl_backward_byte (int, int)
int rl_backward_char (int, int)
int rl_backward (int, int)
int rl_beg_of_line (int, int)
int rl_end_of_line (int, int)
int rl_forward_word (int, int)
int rl_backward_word (int, int)
int rl_refresh_line (int, int)
int rl_clear_screen (int, int)
int rl_clear_display (int, int)
int rl_skip_csi_sequence (int, int)
int rl_arrow_keys (int, int)
int rl_previous_screen_line (int, int)
int rl_next_screen_line (int, int)
int rl_insert (int, int)
int rl_quoted_insert (int, int)
int rl_tab_insert (int, int)
int rl_newline (int, int)
int rl_do_lowercase_version (int, int)
int rl_rubout (int, int)
int rl_delete (int, int)
int rl_rubout_or_delete (int, int)
int rl_delete_horizontal_space (int, int)
int rl_delete_or_show_completions (int, int)
int rl_insert_comment (int, int)
int rl_upcase_word (int, int)
int rl_downcase_word (int, int)
int rl_capitalize_word (int, int)
int rl_transpose_words (int, int)
int rl_transpose_chars (int, int)
int rl_char_search (int, int)
int rl_backward_char_search (int, int)
int rl_beginning_of_history (int, int)
int rl_end_of_history (int, int)
int rl_get_next_history (int, int)
int rl_get_previous_history (int, int)
int rl_operate_and_get_next (int, int)
int rl_fetch_history (int, int)
int rl_set_mark (int, int)
int rl_exchange_point_and_mark (int, int)
int rl_vi_editing_mode (int, int)
int rl_emacs_editing_mode (int, int)
int rl_overwrite_mode (int, int)
int rl_re_read_init_file (int, int)
int rl_dump_functions (int, int)
int rl_dump_macros (int, int)
int rl_dump_variables (int, int)
int rl_complete (int, int)
int rl_possible_completions (int, int)
int rl_insert_completions (int, int)
int rl_old_menu_complete (int, int)
int rl_menu_complete (int, int)
int rl_backward_menu_complete (int, int)
int rl_kill_word (int, int)
int rl_backward_kill_word (int, int)
int rl_kill_line (int, int)
int rl_backward_kill_line (int, int)
int rl_kill_full_line (int, int)
int rl_unix_word_rubout (int, int)
int rl_unix_filename_rubout (int, int)
int rl_unix_line_discard (int, int)
int rl_copy_region_to_kill (int, int)
int rl_kill_region (int, int)
int rl_copy_forward_word (int, int)
int rl_copy_backward_word (int, int)
int rl_yank (int, int)
int rl_yank_pop (int, int)
int rl_yank_nth_arg (int, int)
int rl_yank_last_arg (int, int)
int rl_bracketed_paste_begin (int, int)
int rl_reverse_search_history (int, int)
int rl_forward_search_history (int, int)
int rl_start_kbd_macro (int, int)
int rl_end_kbd_macro (int, int)
int rl_call_last_kbd_macro (int, int)
int rl_print_last_kbd_macro (int, int)
int rl_revert_line (int, int)
int rl_undo_command (int, int)
int rl_tilde_expand (int, int)
int rl_restart_output (int, int)
int rl_stop_output (int, int)
int rl_abort (int, int)
int rl_tty_status (int, int)
int rl_history_search_forward (int, int)
int rl_history_search_backward (int, int)
int rl_history_substr_search_forward (int, int)
int rl_history_substr_search_backward (int, int)
int rl_noninc_forward_search (int, int)
int rl_noninc_reverse_search (int, int)
int rl_noninc_forward_search_again (int, int)
int rl_noninc_reverse_search_again (int, int)
int rl_insert_close (int, int)
void rl_callback_handler_install (const char *, rl_vcpfunc_t *)
void rl_callback_read_char (void)
void rl_callback_handler_remove (void)
void rl_callback_sigcleanup (void)
int rl_vi_redo (int, int)
int rl_vi_undo (int, int)
int rl_vi_yank_arg (int, int)
int rl_vi_fetch_history (int, int)
int rl_vi_search_again (int, int)
int rl_vi_search (int, int)
int rl_vi_complete (int, int)
int rl_vi_tilde_expand (int, int)
int rl_vi_prev_word (int, int)
int rl_vi_next_word (int, int)
int rl_vi_end_word (int, int)
int rl_vi_insert_beg (int, int)
int rl_vi_append_mode (int, int)
int rl_vi_append_eol (int, int)
int rl_vi_eof_maybe (int, int)
int rl_vi_insertion_mode (int, int)
int rl_vi_insert_mode (int, int)
int rl_vi_movement_mode (int, int)
int rl_vi_arg_digit (int, int)
int rl_vi_change_case (int, int)
int rl_vi_put (int, int)
int rl_vi_column (int, int)
int rl_vi_delete_to (int, int)
int rl_vi_change_to (int, int)
int rl_vi_yank_to (int, int)
int rl_vi_yank_pop (int, int)
int rl_vi_rubout (int, int)
int rl_vi_delete (int, int)
int rl_vi_back_to_indent (int, int)
int rl_vi_unix_word_rubout (int, int)
int rl_vi_first_print (int, int)
int rl_vi_char_search (int, int)
int rl_vi_match (int, int)
int rl_vi_change_char (int, int)
int rl_vi_subst (int, int)
int rl_vi_overstrike (int, int)
int rl_vi_overstrike_delete (int, int)
int rl_vi_replace (int, int)
int rl_vi_set_mark (int, int)
int rl_vi_goto_mark (int, int)
int rl_vi_check (void)
int rl_vi_domove (int, int *)
int rl_vi_bracktype (int)
void rl_vi_start_inserting (int, int, int)
int rl_vi_fWord (int, int)
int rl_vi_bWord (int, int)
int rl_vi_eWord (int, int)
int rl_vi_fword (int, int)
int rl_vi_bword (int, int)
int rl_vi_eword (int, int)
char * readline (const char *)
int rl_set_prompt (const char *)
int rl_expand_prompt (char *)
int rl_initialize (void)
int rl_discard_argument (void)
int rl_add_defun (const char *, rl_command_func_t *, int)
int rl_bind_key (int, rl_command_func_t *)
int rl_bind_key_in_map (int, rl_command_func_t *, Keymap)
int rl_unbind_key (int)
int rl_unbind_key_in_map (int, Keymap)
int rl_bind_key_if_unbound (int, rl_command_func_t *)
int rl_bind_key_if_unbound_in_map (int, rl_command_func_t *, Keymap)
int rl_unbind_function_in_map (rl_command_func_t *, Keymap)
int rl_unbind_command_in_map (const char *, Keymap)
int rl_bind_keyseq (const char *, rl_command_func_t *)
int rl_bind_keyseq_in_map (const char *, rl_command_func_t *, Keymap)
int rl_bind_keyseq_if_unbound (const char *, rl_command_func_t *)
int rl_bind_keyseq_if_unbound_in_map (const char *, rl_command_func_t *, Keymap)
int rl_generic_bind (int, const char *, char *, Keymap)
char * rl_variable_value (const char *)
int rl_variable_bind (const char *, const char *)
int rl_set_key (const char *, rl_command_func_t *, Keymap)
int rl_macro_bind (const char *, const char *, Keymap)
int rl_translate_keyseq (const char *, char *, int *)
char * rl_untranslate_keyseq (int)
rl_command_func_t * rl_named_function (const char *)
rl_command_func_t * rl_function_of_keyseq (const char *, Keymap, int *)
rl_command_func_t * rl_function_of_keyseq_len (const char *, size_t, Keymap, int *)
int rl_trim_arg_from_keyseq (const char *, size_t, Keymap)
void rl_list_funmap_names (void)
char ** rl_invoking_keyseqs_in_map (rl_command_func_t *, Keymap)
char ** rl_invoking_keyseqs (rl_command_func_t *)
void rl_function_dumper (int)
void rl_macro_dumper (int)
void rl_variable_dumper (int)
int rl_read_init_file (const char *)
int rl_parse_and_bind (char *)
Keymap rl_make_bare_keymap (void)
int rl_empty_keymap (Keymap)
Keymap rl_copy_keymap (Keymap)
Keymap rl_make_keymap (void)
void rl_discard_keymap (Keymap)
void rl_free_keymap (Keymap)
Keymap rl_get_keymap_by_name (const char *)
char * rl_get_keymap_name (Keymap)
void rl_set_keymap (Keymap)
Keymap rl_get_keymap (void)
int rl_set_keymap_name (const char *, Keymap)
void rl_set_keymap_from_edit_mode (void)
char * rl_get_keymap_name_from_edit_mode (void)
int rl_add_funmap_entry (const char *, rl_command_func_t *)
const char ** rl_funmap_names (void)
void rl_initialize_funmap (void)
void rl_push_macro_input (char *)
void rl_add_undo (enum undo_code, int, int, char *)
void rl_free_undo_list (void)
int rl_do_undo (void)
int rl_begin_undo_group (void)
int rl_end_undo_group (void)
int rl_modifying (int, int)
void rl_redisplay (void)
int rl_on_new_line (void)
int rl_on_new_line_with_prompt (void)
int rl_forced_update_display (void)
int rl_clear_visible_line (void)
int rl_clear_message (void)
int rl_reset_line_state (void)
int rl_crlf (void)
void rl_keep_mark_active (void)
void rl_activate_mark (void)
void rl_deactivate_mark (void)
int rl_mark_active_p (void)
int rl_message ()
int rl_show_char (int)
int rl_character_len (int, int)
void rl_redraw_prompt_last_line (void)
void rl_save_prompt (void)
void rl_restore_prompt (void)
void rl_replace_line (const char *, int)
int rl_insert_text (const char *)
int rl_delete_text (int, int)
int rl_kill_text (int, int)
char * rl_copy_text (int, int)
void rl_prep_terminal (int)
void rl_deprep_terminal (void)
void rl_tty_set_default_bindings (Keymap)
void rl_tty_unset_default_bindings (Keymap)
int rl_tty_set_echoing (int)
int rl_reset_terminal (const char *)
void rl_resize_terminal (void)
void rl_set_screen_size (int, int)
void rl_get_screen_size (int *, int *)
void rl_reset_screen_size (void)
char * rl_get_termcap (const char *)
int rl_stuff_char (int)
int rl_execute_next (int)
int rl_clear_pending_input (void)
int rl_read_key (void)
int rl_getc (FILE *)
int rl_set_keyboard_input_timeout (int)
int rl_set_timeout (unsigned int, unsigned int)
int rl_timeout_remaining (unsigned int *, unsigned int *)
void rl_extend_line_buffer (int)
int rl_ding (void)
int rl_alphabetic (int)
void rl_free (void *)
int rl_set_signals (void)
int rl_clear_signals (void)
void rl_cleanup_after_signal (void)
void rl_reset_after_signal (void)
void rl_free_line_state (void)
int rl_pending_signal (void)
void rl_check_signals (void)
void rl_echo_signal_char (int)
int rl_set_paren_blink_timeout (int)
void rl_clear_history (void)
int rl_maybe_save_line (void)
int rl_maybe_unsave_line (void)
int rl_maybe_replace_line (void)
int rl_complete_internal (int)
void rl_display_match_list (char **, int, int)
char ** rl_completion_matches (const char *, rl_compentry_func_t *)
char * rl_username_completion_function (const char *, int)
char * rl_filename_completion_function (const char *, int)
int rl_completion_mode (rl_command_func_t *)
int rl_save_state (struct readline_state *)
int rl_restore_state (struct readline_state *)
Variables
UNDO_LIST * rl_undo_list
FUNMAP ** funmap
const char * rl_library_version
int rl_readline_version
int rl_gnu_readline_p
unsigned long rl_readline_state
int rl_editing_mode
int rl_insert_mode
const char * rl_readline_name
char * rl_prompt
char * rl_display_prompt
char * rl_line_buffer
int rl_point
int rl_end
int rl_mark
int rl_done
int rl_eof_found
int rl_pending_input
int rl_dispatching
int rl_explicit_arg
int rl_numeric_arg
rl_command_func_t * rl_last_func
const char * rl_terminal_name
FILE * rl_instream
FILE * rl_outstream
int rl_prefer_env_winsize
rl_hook_func_t * rl_startup_hook
rl_hook_func_t * rl_pre_input_hook
rl_hook_func_t * rl_event_hook
rl_hook_func_t * rl_signal_event_hook
rl_hook_func_t * rl_timeout_event_hook
rl_hook_func_t * rl_input_available_hook
rl_getc_func_t * rl_getc_function
rl_voidfunc_t * rl_redisplay_function
rl_vintfunc_t * rl_prep_term_function
rl_voidfunc_t * rl_deprep_term_function
Keymap rl_executing_keymap
Keymap rl_binding_keymap
int rl_executing_key
char * rl_executing_keyseq
int rl_key_sequence_length
int rl_erase_empty_line
int rl_already_prompted
int rl_num_chars_to_read
char * rl_executing_macro
int rl_catch_signals
int rl_catch_sigwinch
int rl_change_environment
rl_compentry_func_t * rl_completion_entry_function
rl_compentry_func_t * rl_menu_completion_entry_function
rl_compignore_func_t * rl_ignore_some_completions_function
rl_completion_func_t * rl_attempted_completion_function
const char * rl_basic_word_break_characters
const char * rl_completer_word_break_characters
rl_cpvfunc_t * rl_completion_word_break_hook
const char * rl_completer_quote_characters
const char * rl_basic_quote_characters
const char * rl_filename_quote_characters
const char * rl_special_prefixes
rl_icppfunc_t * rl_directory_completion_hook
rl_icppfunc_t * rl_directory_rewrite_hook
rl_icppfunc_t * rl_filename_stat_hook
rl_dequote_func_t * rl_filename_rewrite_hook
rl_compdisp_func_t * rl_completion_display_matches_hook
int rl_filename_completion_desired
int rl_filename_quoting_desired
rl_quote_func_t * rl_filename_quoting_function
rl_dequote_func_t * rl_filename_dequoting_function
rl_linebuf_func_t * rl_char_is_quoted_p
int rl_attempted_completion_over
int rl_completion_type
int rl_completion_invoking_key
int rl_completion_query_items
int rl_completion_append_character
int rl_completion_suppress_append
int rl_completion_quote_character
int rl_completion_found_quote
int rl_completion_suppress_quote
int rl_sort_completion_matches
int rl_completion_mark_symlink_dirs
int rl_ignore_completion_duplicates
int rl_inhibit_completion
int rl_persistent_signal_handlers
Data Structure Documentation
undo_list
struct undo_list
Definition at line 57 of file readline.h.
Data Fields
int end
struct undo_list * next
int start
char * text
enum undo_code what
_funmap
struct _funmap
Definition at line 68 of file readline.h.
Data Fields
rl_command_func_t * function
const char * name
readline_state
struct readline_state
Definition at line 931 of file readline.h.
Data Fields
rl_completion_func_t * attemptfunc
char * buffer
int buflen
int catchsigs
int catchsigwinch
int done
int edmode
int end
rl_compentry_func_t * entryfunc
rl_compignore_func_t * ignorefunc
FILE * inf
int insmode
Keymap kmap
char * kseq
int kseqlen
rl_command_func_t * lastfunc
char * macro
int mark
rl_compentry_func_t * menuentryfunc
FILE * outf
int pendingin
int point
char * prompt
char reserved[64]
int rlstate
UNDO_LIST * ul
const char * wordbreakchars
Macro Definition Documentation
MULT_MATCH
#define MULT_MATCH 2
Definition at line 892 of file readline.h.
NO_MATCH
#define NO_MATCH 0
Definition at line 890 of file readline.h.
READERR
#define READERR (-2)
Definition at line 882 of file readline.h.
rl_clear_timeout
#define rl_clear_timeout () rl_set_timeout (0, 0)
Definition at line 458 of file readline.h.
RL_ISSTATE
#define RL_ISSTATE (x) (rl_readline_state & (x))
Definition at line 929 of file readline.h.
RL_PROMPT_END_IGNORE
#define RL_PROMPT_END_IGNORE '\002'
Definition at line 886 of file readline.h.
RL_PROMPT_START_IGNORE
#define RL_PROMPT_START_IGNORE '\001'
Definition at line 885 of file readline.h.
RL_READLINE_VERSION
#define RL_READLINE_VERSION 0x0802 /* Readline 8.2 */
Definition at line 42 of file readline.h.
RL_SETSTATE
#define RL_SETSTATE (x) (rl_readline_state |= (x))
Definition at line 927 of file readline.h.
RL_STATE_CALLBACK
#define RL_STATE_CALLBACK 0x0080000 /* using the callback interface */
Definition at line 916 of file readline.h.
RL_STATE_CHARSEARCH
#define RL_STATE_CHARSEARCH 0x0800000 /* vi mode char search */
Definition at line 920 of file readline.h.
RL_STATE_COMPLETING
#define RL_STATE_COMPLETING 0x0004000 /* doing completion */
Definition at line 911 of file readline.h.
RL_STATE_DISPATCHING
#define RL_STATE_DISPATCHING 0x0000020 /* dispatching to a command */
Definition at line 902 of file readline.h.
RL_STATE_DONE
#define RL_STATE_DONE 0x2000000 /* done; accepted line */
Definition at line 923 of file readline.h.
RL_STATE_EOF
#define RL_STATE_EOF 0x8000000 /* done; got eof on read */
Definition at line 925 of file readline.h.
RL_STATE_INITIALIZED
#define RL_STATE_INITIALIZED 0x0000002 /* initialization done */
Definition at line 898 of file readline.h.
RL_STATE_INITIALIZING
#define RL_STATE_INITIALIZING 0x0000001 /* initializing */
Definition at line 897 of file readline.h.
RL_STATE_INPUTPENDING
#define RL_STATE_INPUTPENDING 0x0020000 /* rl_execute_next called */
Definition at line 914 of file readline.h.
RL_STATE_ISEARCH
#define RL_STATE_ISEARCH 0x0000080 /* doing incremental search */
Definition at line 904 of file readline.h.
RL_STATE_MACRODEF
#define RL_STATE_MACRODEF 0x0001000 /* defining keyboard macro */
Definition at line 909 of file readline.h.
RL_STATE_MACROINPUT
#define RL_STATE_MACROINPUT 0x0000800 /* getting input from a macro */
Definition at line 908 of file readline.h.
RL_STATE_METANEXT
#define RL_STATE_METANEXT 0x0000010 /* reading input after ESC */
Definition at line 901 of file readline.h.
RL_STATE_MOREINPUT
#define RL_STATE_MOREINPUT 0x0000040 /* reading more input in a command function */
Definition at line 903 of file readline.h.
RL_STATE_MULTIKEY
#define RL_STATE_MULTIKEY 0x0200000 /* reading multiple-key command */
Definition at line 918 of file readline.h.
RL_STATE_NONE
#define RL_STATE_NONE 0x000000 /* no state; before first call */
Definition at line 895 of file readline.h.
RL_STATE_NSEARCH
#define RL_STATE_NSEARCH 0x0000100 /* doing non-inc search */
Definition at line 905 of file readline.h.
RL_STATE_NUMERICARG
#define RL_STATE_NUMERICARG 0x0000400 /* reading numeric argument */
Definition at line 907 of file readline.h.
RL_STATE_OVERWRITE
#define RL_STATE_OVERWRITE 0x0002000 /* overwrite mode */
Definition at line 910 of file readline.h.
RL_STATE_READCMD
#define RL_STATE_READCMD 0x0000008 /* reading a command key */
Definition at line 900 of file readline.h.
RL_STATE_REDISPLAYING
#define RL_STATE_REDISPLAYING 0x1000000 /* updating terminal display */
Definition at line 921 of file readline.h.
RL_STATE_SEARCH
#define RL_STATE_SEARCH 0x0000200 /* doing a history search */
Definition at line 906 of file readline.h.
RL_STATE_SIGHANDLER
#define RL_STATE_SIGHANDLER 0x0008000 /* in readline sighandler */
Definition at line 912 of file readline.h.
RL_STATE_TERMPREPPED
#define RL_STATE_TERMPREPPED 0x0000004 /* terminal is prepped */
Definition at line 899 of file readline.h.
RL_STATE_TIMEOUT
#define RL_STATE_TIMEOUT 0x4000000 /* done; timed out */
Definition at line 924 of file readline.h.
RL_STATE_TTYCSAVED
#define RL_STATE_TTYCSAVED 0x0040000 /* tty special chars saved */
Definition at line 915 of file readline.h.
RL_STATE_UNDOING
#define RL_STATE_UNDOING 0x0010000 /* doing an undo */
Definition at line 913 of file readline.h.
RL_STATE_VICMDONCE
#define RL_STATE_VICMDONCE 0x0400000 /* entered vi command mode at least once */
Definition at line 919 of file readline.h.
RL_STATE_VIMOTION
#define RL_STATE_VIMOTION 0x0100000 /* reading vi motion arg */
Definition at line 917 of file readline.h.
rl_symbolic_link_hook
#define rl_symbolic_link_hook rl_directory_completion_hook
Definition at line 774 of file readline.h.
RL_UNSETSTATE
#define RL_UNSETSTATE (x) (rl_readline_state &= ~(x))
Definition at line 928 of file readline.h.
RL_VERSION_MAJOR
#define RL_VERSION_MAJOR 8
Definition at line 43 of file readline.h.
RL_VERSION_MINOR
#define RL_VERSION_MINOR 2
Definition at line 44 of file readline.h.
SINGLE_MATCH
#define SINGLE_MATCH 1
Definition at line 891 of file readline.h.
Typedef Documentation
FUNMAP
typedef struct _funmap FUNMAP
UNDO_LIST
typedef struct undo_list UNDO_LIST
Enumeration Type Documentation
undo_code
enum undo_code
Enumerator
UNDO_DELETE
UNDO_INSERT
UNDO_BEGIN
UNDO_END
Definition at line 54 of file readline.h.
 { UNDO_DELETE, UNDO_INSERT, UNDO_BEGIN, UNDO_END };
Function Documentation
readline()
char* readline (const char * prompt)
Definition at line 354 of file readline.c.
 {
   char *value;
 #if 0
   int in_callback;
 #endif
   /* If we are at EOF return a NULL string. */
   if (rl_pending_input == EOF)
     {
       rl_clear_pending_input ();
       return ((char *)NULL);
     }
 #if 0
   /* If readline() is called after installing a callback handler, temporarily
      turn off the callback state to avoid ensuing messiness.  Patch supplied
      by the gdb folks.  XXX -- disabled.  This can be fooled and readline
      left in a strange state by a poorly-timed longjmp. */
   if (in_callback = RL_ISSTATE (RL_STATE_CALLBACK))
     RL_UNSETSTATE (RL_STATE_CALLBACK);
 #endif
   rl_set_prompt (prompt);
   rl_initialize ();
   if (rl_prep_term_function)
     (*rl_prep_term_function) (_rl_meta_flag);
 #if defined (HANDLE_SIGNALS)
   rl_set_signals ();
 #endif
   value = readline_internal ();
   if (rl_deprep_term_function)
     (*rl_deprep_term_function) ();
 #if defined (HANDLE_SIGNALS)
   rl_clear_signals ();
 #endif
 #if 0
   if (in_callback)
     RL_SETSTATE (RL_STATE_CALLBACK);
 #endif
 #if HAVE_DECL_AUDIT_USER_TTY && defined (HAVE_LIBAUDIT_H) && defined (ENABLE_TTY_AUDIT_SUPPORT)
   if (value)
     _rl_audit_tty (value);
 #endif
   return (value);
 }
References _rl_audit_tty(), _rl_meta_flag, EOF, NULL, prompt, readline_internal(), rl_clear_pending_input(), rl_clear_signals(), rl_deprep_term_function, rl_initialize(), RL_ISSTATE, rl_pending_input, rl_prep_term_function, rl_set_prompt(), rl_set_signals(), RL_SETSTATE, RL_STATE_CALLBACK, RL_UNSETSTATE, and value.
Referenced by main(), and rl_gets().
rl_abort()
int rl_abort (int count, int key)
Definition at line 121 of file util.c.
 {
   return (_rl_abort_internal ());
 }
References _rl_abort_internal().
Referenced by _rl_isearch_dispatch().
rl_activate_mark()
void rl_activate_mark (void)
Definition at line 1872 of file text.c.
 {
   mark_active = 1;
   rl_keep_mark_active ();
 }
References mark_active, and rl_keep_mark_active().
Referenced by _rl_isearch_dispatch(), noninc_dosearch(), rl_bracketed_paste_begin(), and rl_exchange_point_and_mark().
rl_add_defun()
int rl_add_defun (const char * name, rl_command_func_t * function, int key)
Definition at line 126 of file bind.c.
 {
   if (key != -1)
     rl_bind_key (key, function);
   rl_add_funmap_entry (name, function);
   return 0;
 }
References rl_add_funmap_entry(), and rl_bind_key().
Referenced by main().
rl_add_funmap_entry()
int rl_add_funmap_entry (const char * name, rl_command_func_t * function)
Definition at line 213 of file funmap.c.
 {
   if (funmap_entry + 2 >= funmap_size)
     {
       funmap_size += 64;
       funmap = (FUNMAP **)xrealloc (funmap, funmap_size * sizeof (FUNMAP *));
     }
   funmap[funmap_entry] = (FUNMAP *)xmalloc (sizeof (FUNMAP));
   funmap[funmap_entry]->name = name;
   funmap[funmap_entry]->function = function;
   funmap[++funmap_entry] = (FUNMAP *)NULL;
   return funmap_entry;
 }
References _funmap::function, funmap, funmap_entry, funmap_size, _funmap::name, NULL, xmalloc, and xrealloc.
Referenced by rl_add_defun(), and rl_initialize_funmap().
rl_add_undo()
void rl_add_undo (enum undo_code, int start, int end, char * text)
Definition at line 88 of file undo.c.
 {
   UNDO_LIST *temp;
   temp = alloc_undo_entry (what, start, end, text);
   temp->next = rl_undo_list;
   rl_undo_list = temp;
 }
References alloc_undo_entry(), end, undo_list::next, rl_undo_list, start, and text.
Referenced by rl_begin_undo_group(), rl_delete_text(), rl_end_undo_group(), rl_insert_text(), and rl_modifying().
rl_alphabetic()
int rl_alphabetic (int c)
Definition at line 73 of file util.c.
 {
   if (_rl_alphabetic_p (c))
     return (1);
   return (_rl_allow_pathname_alphabetic_chars &&
         strchr (pathname_alphabetic_chars, c) != NULL);
 }
rl_arrow_keys()
int rl_arrow_keys (int count, int key)
Definition at line 652 of file text.c.
 {
   int ch;
   RL_SETSTATE(RL_STATE_MOREINPUT);
   ch = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   if (ch < 0)
     return (1);
   switch (_rl_to_upper (ch))
     {
     case 'A':
       rl_get_previous_history (count, ch);
       break;
     case 'B':
       rl_get_next_history (count, ch);
       break;
     case 'C':
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_forward_char (count, ch);
       else
     rl_forward_byte (count, ch);
       break;
     case 'D':
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_backward_char (count, ch);
       else
     rl_backward_byte (count, ch);
       break;
     default:
       rl_ding ();
     }
   return 0;
 }
References _rl_to_upper(), count, MB_CUR_MAX, rl_backward_byte(), rl_backward_char(), rl_byte_oriented, rl_ding(), rl_forward_byte(), rl_forward_char(), rl_get_next_history(), rl_get_previous_history(), rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, and RL_UNSETSTATE.
rl_backward()
int rl_backward (int count, int key)
Definition at line 458 of file text.c.
 {
   return (rl_backward_char (count, key));
 }
References count, and rl_backward_char().
rl_backward_byte()
int rl_backward_byte (int count, int key)
Definition at line 393 of file text.c.
 {
   if (count < 0)
     return (rl_forward_byte (-count, key));
   if (count > 0)
     {
       if (rl_point < count)
     {
       rl_point = 0;
       rl_ding ();
     }
       else
     rl_point -= count;
     }
   if (rl_point < 0)
     rl_point = 0;
   return 0;
 }
References count, rl_ding(), rl_forward_byte(), and rl_point.
Referenced by rl_arrow_keys(), rl_backward_char(), and rl_forward_byte().
rl_backward_char()
int rl_backward_char (int count, int key)
Definition at line 450 of file text.c.
 {
   return (rl_backward_byte (count, key));
 }
References count, and rl_backward_byte().
Referenced by _rl_overwrite_rubout(), _rl_rubout_char(), _rl_vi_change_char(), bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_arrow_keys(), rl_backward(), rl_previous_screen_line(), rl_vi_delete(), rl_vi_movement_mode(), rl_vi_overstrike_delete(), rl_vi_put(), and rl_vi_rubout().
rl_backward_char_search()
int rl_backward_char_search (int count, int key)
Definition at line 1795 of file text.c.
 {
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_data->i1 = BFIND;
       _rl_callback_data->i2 = FFIND;
       _rl_callback_func = _rl_char_search_callback;
       return (0);
     }
 #endif
   return (_rl_char_search (count, BFIND, FFIND));
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_char_search(), _rl_char_search_callback(), BFIND, count, FFIND, __rl_callback_generic_arg::i1, __rl_callback_generic_arg::i2, RL_ISSTATE, and RL_STATE_CALLBACK.
rl_backward_kill_line()
int rl_backward_kill_line (int direction, int key)
Definition at line 265 of file kill.c.
 {
   int orig_point;
   if (direction < 0)
     return (rl_kill_line (1, key));
   else
     {
       if (rl_point == 0)
     rl_ding ();
       else
     {
       orig_point = rl_point;
       rl_beg_of_line (1, key);
       if (rl_point != orig_point)
         rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
         rl_mark = rl_point;
     }
     }
   return 0;
 }
References emacs_mode, rl_beg_of_line(), rl_ding(), rl_editing_mode, rl_kill_line(), rl_kill_text(), rl_mark, and rl_point.
Referenced by rl_kill_line().
rl_backward_kill_word()
int rl_backward_kill_word (int count, int key)
Definition at line 220 of file kill.c.
 {
   int orig_point;
   if (count < 0)
     return (rl_kill_word (-count, key));
   else
     {
       orig_point = rl_point;
       rl_backward_word (count, key);
       if (rl_point != orig_point)
     rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References count, emacs_mode, rl_backward_word(), rl_editing_mode, rl_kill_text(), rl_kill_word(), rl_mark, and rl_point.
Referenced by rl_kill_word().
rl_backward_menu_complete()
int rl_backward_menu_complete (int count, int key)
Definition at line 2987 of file complete.c.
 {
   /* Positive arguments to backward-menu-complete translate into negative
      arguments for menu-complete, and vice versa. */
   return (rl_menu_complete (-count, key));
 }
References count, and rl_menu_complete().
Referenced by rl_menu_complete().
rl_backward_word()
int rl_backward_word (int count, int key)
Definition at line 533 of file text.c.
 {
   int c, p;
   if (count < 0)
     return (rl_forward_word (-count, key));
   while (count)
     {
       if (rl_point == 0)
     return 0;
       /* Like rl_forward_word (), except that we look at the characters
      just before point. */
       p = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_NONZERO);
       c = _rl_char_value (rl_line_buffer, p);
       if (_rl_walphabetic (c) == 0)
     {
       rl_point = p;
       while (rl_point > 0)
         {
           p = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_NONZERO);
           c = _rl_char_value (rl_line_buffer, p);
           if (_rl_walphabetic (c))
         break;
           rl_point = p;
         }
     }
       while (rl_point)
     {
       p = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_NONZERO);
       c = _rl_char_value (rl_line_buffer, p);
       if (_rl_walphabetic (c) == 0)
         break;
       else
         rl_point = p;
     }
       --count;
     }
   return 0;
 }
References _rl_char_value, _rl_walphabetic, c, count, MB_FIND_NONZERO, MB_PREVCHAR, p, rl_forward_word(), rl_line_buffer, and rl_point.
Referenced by _rl_copy_word_as_kill(), bind_arrow_keys_internal(), rl_backward_kill_word(), rl_forward_word(), and rl_transpose_words().
rl_beg_of_line()
int rl_beg_of_line (int count, int key)
Definition at line 465 of file text.c.
 {
   rl_point = 0;
   return 0;
 }
References rl_point.
Referenced by bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_backward_kill_line(), rl_domove_read_callback(), rl_insert_comment(), rl_vi_arg_digit(), rl_vi_back_to_indent(), rl_vi_change_to(), rl_vi_delete_to(), rl_vi_insert_beg(), rl_vi_redo(), and rl_vi_yank_to().
rl_begin_undo_group()
int rl_begin_undo_group (void)
Definition at line 292 of file undo.c.
 {
   rl_add_undo (UNDO_BEGIN, 0, 0, 0);
   _rl_undo_group_level++;
   return 0;
 }
References _rl_undo_group_level, rl_add_undo(), and UNDO_BEGIN.
Referenced by _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_replace_text(), _rl_vi_change_char(), _rl_vi_replace_insert(), _rl_vi_stuff_insert(), insert_all_matches(), rl_kill_full_line(), rl_modifying(), rl_transpose_chars(), rl_transpose_words(), rl_vi_change_case(), rl_vi_overstrike(), rl_vi_start_inserting(), rl_yank_nth_arg_internal(), vi_change_dispatch(), and vi_yank_dispatch().
rl_beginning_of_history()
int rl_beginning_of_history (int count, int key)
Definition at line 542 of file misc.c.
 {
   return (rl_get_previous_history (1 + where_history (), key));
 }
References rl_get_previous_history(), and where_history().
Referenced by rl_fetch_history().
rl_bind_key()
int rl_bind_key (int key, rl_command_func_t * function)
Definition at line 136 of file bind.c.
 {
   char keyseq[4];
   int l;
   if (key < 0 || key > largest_char)
     return (key);
   /* Want to make this a multi-character key sequence with an ESC prefix */
   if (META_CHAR (key) && _rl_convert_meta_chars_to_ascii)
     {
       if (_rl_keymap[ESC].type == ISKMAP)
     {
       Keymap escmap;
       escmap = FUNCTION_TO_KEYMAP (_rl_keymap, ESC);
       key = UNMETA (key);
       escmap[key].type = ISFUNC;
       escmap[key].function = function;
       return (0);
     }
       /* Otherwise, let's just let rl_generic_bind handle the key sequence.
      We start it off with ESC here and let the code below add the rest
      of the sequence. */
       keyseq[0] = ESC;
       l = 1;
       key = UNMETA(key);
       goto bind_keyseq;
     }
   /* If it's bound to a function or macro, just overwrite.  Otherwise we have
      to treat it as a key sequence so rl_generic_bind handles shadow keymaps
      for us.  If we are binding '\' or \C-@ (NUL) make sure to escape it so
      it makes it through the call to rl_translate_keyseq. */
   if (_rl_keymap[key].type != ISKMAP)
     {
       if (_rl_keymap[key].type == ISMACR)
     xfree ((char *)_rl_keymap[key].function);
       _rl_keymap[key].type = ISFUNC;
       _rl_keymap[key].function = function;
     }
   else
     {
       l = 0;
 bind_keyseq:
       if (key == '\\')
     {
       keyseq[l++] = '\\';
       keyseq[l++] = '\\';
     }
       else if (key == '\0')
     {
       keyseq[l++] = '\\';
       keyseq[l++] = '0';
     }
       else
     keyseq[l++] = key;
       keyseq[l] = '\0';
       rl_bind_keyseq (keyseq, function);
     }
   rl_binding_keymap = _rl_keymap;
   return (0);
 }
References _rl_convert_meta_chars_to_ascii, _rl_keymap, ESC, _keymap_entry::function, FUNCTION_TO_KEYMAP, ISFUNC, ISKMAP, ISMACR, l, largest_char, META_CHAR, rl_bind_keyseq(), rl_binding_keymap, _keymap_entry::type, type, UNMETA, and xfree.
Referenced by prepare_terminal_settings(), rl_add_defun(), rl_bind_key_in_map(), rl_parse_and_bind(), and rl_unbind_key().
rl_bind_key_if_unbound()
int rl_bind_key_if_unbound (int key, rl_command_func_t * default_func)
Definition at line 228 of file bind.c.
 {
   char *keyseq;
   keyseq = rl_untranslate_keyseq ((unsigned char)key);
   return (rl_bind_keyseq_if_unbound_in_map (keyseq, default_func, _rl_keymap));
 }
References _rl_keymap, rl_bind_keyseq_if_unbound_in_map(), and rl_untranslate_keyseq().
rl_bind_key_if_unbound_in_map()
int rl_bind_key_if_unbound_in_map (int key, rl_command_func_t * default_func, Keymap kmap)
Definition at line 219 of file bind.c.
 {
   char *keyseq;
   keyseq = rl_untranslate_keyseq ((unsigned char)key);
   return (rl_bind_keyseq_if_unbound_in_map (keyseq, default_func, kmap));
 }
References rl_bind_keyseq_if_unbound_in_map(), and rl_untranslate_keyseq().
rl_bind_key_in_map()
int rl_bind_key_in_map (int key, rl_command_func_t * function, Keymap map)
Definition at line 204 of file bind.c.
 {
   int result;
   Keymap oldmap;
   oldmap = _rl_keymap;
   _rl_keymap = map;
   result = rl_bind_key (key, function);
   _rl_keymap = oldmap;
   return (result);
 }
References _rl_keymap, map, and rl_bind_key().
Referenced by _rl_enable_paren_matching(), and rl_unbind_key_in_map().
rl_bind_keyseq()
int rl_bind_keyseq (const char * keyseq, rl_command_func_t * function)
Definition at line 292 of file bind.c.
 {
   return (rl_generic_bind (ISFUNC, keyseq, (char *)function, _rl_keymap));
 }
References _rl_keymap, ISFUNC, and rl_generic_bind().
Referenced by rl_bind_key(), and rl_parse_and_bind().
rl_bind_keyseq_if_unbound()
int rl_bind_keyseq_if_unbound (const char * keyseq, rl_command_func_t * default_func)
Definition at line 348 of file bind.c.
 {
   return (rl_bind_keyseq_if_unbound_in_map (keyseq, default_func, _rl_keymap));
 }
References _rl_keymap, and rl_bind_keyseq_if_unbound_in_map().
Referenced by bind_arrow_keys_internal(), bind_bracketed_paste_prefix(), bind_termcap_arrow_keys(), and rl_vi_replace().
rl_bind_keyseq_if_unbound_in_map()
int rl_bind_keyseq_if_unbound_in_map (const char * keyseq, rl_command_func_t * default_func, Keymap kmap)
Definition at line 317 of file bind.c.
 {
   rl_command_func_t *func;
   char *keys;
   int keys_len;
   if (keyseq)
     {
       /* Handle key sequences that require translations and `raw' ones that
      don't. This might be a problem with backslashes. */
       keys = (char *)xmalloc (1 + (2 * strlen (keyseq)));
       if (rl_translate_keyseq (keyseq, keys, &keys_len))
     {
       xfree (keys);
       return -1;
     }
       func = rl_function_of_keyseq_len (keys, keys_len, kmap, (int *)NULL);
       xfree (keys);
 #if defined (VI_MODE)
       if (!func || func == rl_do_lowercase_version || func == rl_vi_movement_mode)
 #else
       if (!func || func == rl_do_lowercase_version)
 #endif
     return (rl_bind_keyseq_in_map (keyseq, default_func, kmap));
       else
     return 1;
     }
   return 0;
 }
References keys, NULL, rl_bind_keyseq_in_map(), rl_do_lowercase_version(), rl_function_of_keyseq_len(), rl_translate_keyseq(), rl_vi_movement_mode(), strlen(), xfree, and xmalloc.
Referenced by rl_bind_key_if_unbound(), rl_bind_key_if_unbound_in_map(), and rl_bind_keyseq_if_unbound().
rl_bind_keyseq_in_map()
int rl_bind_keyseq_in_map (const char * keyseq, rl_command_func_t * function, Keymap map)
Definition at line 301 of file bind.c.
 {
   return (rl_generic_bind (ISFUNC, keyseq, (char *)function, map));
 }
References ISFUNC, map, and rl_generic_bind().
Referenced by bind_arrow_keys(), and rl_bind_keyseq_if_unbound_in_map().
rl_bracketed_paste_begin()
int rl_bracketed_paste_begin (int count, int key)
Definition at line 757 of file kill.c.
 {
   int retval, c;
   size_t len, cap;
   char *buf;
   buf = _rl_bracketed_text (&len);
   rl_mark = rl_point;
   retval = rl_insert_text (buf) == len ? 0 : 1;
   if (_rl_enable_active_region)
     rl_activate_mark ();
   xfree (buf);
   return (retval);
 }
References _rl_bracketed_text(), _rl_enable_active_region, buf, c, retval, rl_activate_mark(), rl_insert_text(), rl_mark, rl_point, and xfree.
Referenced by _rl_isearch_dispatch(), _rl_nsearch_dispatch(), and bind_bracketed_paste_prefix().
rl_call_last_kbd_macro()
int rl_call_last_kbd_macro (int count, int ignore)
Definition at line 291 of file macro.c.
 {
   if (current_macro == 0)
     _rl_abort_internal ();
   if (RL_ISSTATE (RL_STATE_MACRODEF))
     {
       rl_ding ();       /* no recursive macros */
       current_macro[--current_macro_index] = '\0';  /* erase this char */
       return 0;
     }
   while (count--)
     _rl_with_macro_input (savestring (current_macro));
   return 0;
 }
References _rl_abort_internal(), _rl_with_macro_input(), count, current_macro, current_macro_index, rl_ding(), RL_ISSTATE, RL_STATE_MACRODEF, and savestring().
Referenced by rl_end_kbd_macro().
rl_callback_handler_install()
void rl_callback_handler_install (const char * prompt, rl_vcpfunc_t * linefunc)
Definition at line 106 of file callback.c.
 {
   rl_set_prompt (prompt);
   RL_SETSTATE (RL_STATE_CALLBACK);
   rl_linefunc = linefunc;
   _rl_callback_newline ();
 }
References _rl_callback_newline(), prompt, rl_linefunc, rl_set_prompt(), RL_SETSTATE, and RL_STATE_CALLBACK.
Referenced by change_prompt(), and main().
rl_callback_handler_remove()
void rl_callback_handler_remove (void)
Definition at line 318 of file callback.c.
 {
   rl_linefunc = NULL;
   RL_UNSETSTATE (RL_STATE_CALLBACK);
   RL_CHECK_SIGNALS ();
   if (in_handler)
     {
       in_handler = 0;
       if (rl_deprep_term_function)
     (*rl_deprep_term_function) ();
 #if defined (HANDLE_SIGNALS)
       rl_clear_signals ();
 #endif
     }
 }
References in_handler, NULL, RL_CHECK_SIGNALS, rl_clear_signals(), rl_deprep_term_function, rl_linefunc, RL_STATE_CALLBACK, and RL_UNSETSTATE.
Referenced by cb_linehandler(), and main().
rl_callback_read_char()
void rl_callback_read_char (void)
Definition at line 127 of file callback.c.
 {
   char *line;
   int eof, jcode;
   static procenv_t olevel;
   if (rl_linefunc == NULL)
     {
       _rl_errmsg ("readline_callback_read_char() called with no handler!");
       abort ();
     }
   eof = 0;
   memcpy ((void *)olevel, (void *)_rl_top_level, sizeof (procenv_t));
 #if defined (HAVE_POSIX_SIGSETJMP)
   jcode = sigsetjmp (_rl_top_level, 0);
 #else
   jcode = setjmp (_rl_top_level);
 #endif
   if (jcode)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
       memcpy ((void *)_rl_top_level, (void *)olevel, sizeof (procenv_t));
       /* If we longjmped because of a timeout, handle it here. */
       if (RL_ISSTATE (RL_STATE_TIMEOUT))
     {
       RL_SETSTATE (RL_STATE_DONE);
       rl_done = 1;
     }
       CALLBACK_READ_RETURN ();
     }
 #if defined (HANDLE_SIGNALS)
   /* Install signal handlers only when readline has control. */
   if (rl_persistent_signal_handlers == 0)
     rl_set_signals ();
 #endif
   do
     {
       RL_CHECK_SIGNALS ();
       if  (RL_ISSTATE (RL_STATE_ISEARCH))
     {
       eof = _rl_isearch_callback (_rl_iscxt);
       if (eof == 0 && (RL_ISSTATE (RL_STATE_ISEARCH) == 0) && RL_ISSTATE (RL_STATE_INPUTPENDING))
         rl_callback_read_char ();
       CALLBACK_READ_RETURN ();
     }
       else if  (RL_ISSTATE (RL_STATE_NSEARCH))
     {
       eof = _rl_nsearch_callback (_rl_nscxt);
       CALLBACK_READ_RETURN ();
     }
 #if defined (VI_MODE)
       /* States that can occur while in state VIMOTION have to be checked
      before RL_STATE_VIMOTION */
       else if (RL_ISSTATE (RL_STATE_CHARSEARCH))
     {
       int k;
       k = _rl_callback_data->i2;
       eof = (*_rl_callback_func) (_rl_callback_data);
       /* If the function `deregisters' itself, make sure the data is
          cleaned up. */
       if (_rl_callback_func == 0)   /* XXX - just sanity check */
         {
           if (_rl_callback_data)
         {
           _rl_callback_data_dispose (_rl_callback_data);
           _rl_callback_data = 0;
         }
         }
       /* Messy case where vi motion command can be char search */
       if (RL_ISSTATE (RL_STATE_VIMOTION))
         {
           _rl_vi_domove_motion_cleanup (k, _rl_vimvcxt);
           _rl_internal_char_cleanup ();
           CALLBACK_READ_RETURN ();
         }
       _rl_internal_char_cleanup ();
     }
       else if (RL_ISSTATE (RL_STATE_VIMOTION))
     {
       eof = _rl_vi_domove_callback (_rl_vimvcxt);
       /* Should handle everything, including cleanup, numeric arguments,
          and turning off RL_STATE_VIMOTION */
       if (RL_ISSTATE (RL_STATE_NUMERICARG) == 0)
         _rl_internal_char_cleanup ();
       CALLBACK_READ_RETURN ();
     }
 #endif
       else if (RL_ISSTATE (RL_STATE_NUMERICARG))
     {
       eof = _rl_arg_callback (_rl_argcxt);
       if (eof == 0 && (RL_ISSTATE (RL_STATE_NUMERICARG) == 0) && RL_ISSTATE (RL_STATE_INPUTPENDING))
         rl_callback_read_char ();
       /* XXX - this should handle _rl_last_command_was_kill better */
       else if (RL_ISSTATE (RL_STATE_NUMERICARG) == 0)
         _rl_internal_char_cleanup ();
       CALLBACK_READ_RETURN ();
     }
       else if (RL_ISSTATE (RL_STATE_MULTIKEY))
     {
       eof = _rl_dispatch_callback (_rl_kscxt);  /* For now */
       while ((eof == -1 || eof == -2) && RL_ISSTATE (RL_STATE_MULTIKEY) && _rl_kscxt && (_rl_kscxt->flags & KSEQ_DISPATCHED))
         eof = _rl_dispatch_callback (_rl_kscxt);
       if (RL_ISSTATE (RL_STATE_MULTIKEY) == 0)
         {
           _rl_internal_char_cleanup ();
           _rl_want_redisplay = 1;
         }
     }
       else if (_rl_callback_func)
     {
       /* This allows functions that simply need to read an additional
          character (like quoted-insert) to register a function to be
          called when input is available.  _rl_callback_data is a
          pointer to a struct that has the argument count originally
          passed to the registering function and space for any additional
          parameters.  */
       eof = (*_rl_callback_func) (_rl_callback_data);
       /* If the function `deregisters' itself, make sure the data is
          cleaned up. */
       if (_rl_callback_func == 0)
         {
           if (_rl_callback_data)
         {
           _rl_callback_data_dispose (_rl_callback_data);
           _rl_callback_data = 0;
         }
           _rl_internal_char_cleanup ();
         }
     }
       else
     eof = readline_internal_char ();
       RL_CHECK_SIGNALS ();
       if (rl_done == 0 && _rl_want_redisplay)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
     }
       /* Make sure application hooks can see whether we saw EOF. */
       if (eof > 0)
     {
       rl_eof_found = eof;
       RL_SETSTATE(RL_STATE_EOF);
     }
       if (rl_done)
     {
       line = readline_internal_teardown (eof);
       if (rl_deprep_term_function)
         (*rl_deprep_term_function) ();
 #if defined (HANDLE_SIGNALS)
       rl_clear_signals ();
 #endif
       in_handler = 0;
       if (rl_linefunc)          /* just in case */
         (*rl_linefunc) (line);
       /* If the user did not clear out the line, do it for him. */
       if (rl_line_buffer[0])
         _rl_init_line_state ();
       /* Redisplay the prompt if readline_handler_{install,remove}
          not called. */
       if (in_handler == 0 && rl_linefunc)
         _rl_callback_newline ();
     }
     }
   while (rl_pending_input || _rl_pushed_input_available () || RL_ISSTATE (RL_STATE_MACROINPUT));
   CALLBACK_READ_RETURN ();
 }
References _rl_arg_callback(), _rl_argcxt, _rl_callback_data, _rl_callback_data_dispose(), _rl_callback_func, _rl_callback_newline(), _rl_dispatch_callback(), _rl_errmsg(), _rl_init_line_state(), _rl_internal_char_cleanup(), _rl_iscxt, _rl_isearch_callback(), _rl_kscxt, _rl_nscxt, _rl_nsearch_callback(), _rl_pushed_input_available(), _rl_top_level, _rl_vi_domove_callback(), _rl_vi_domove_motion_cleanup(), _rl_vimvcxt, _rl_want_redisplay, abort(), CALLBACK_READ_RETURN, __rl_keyseq_context::flags, __rl_callback_generic_arg::i2, in_handler, k, KSEQ_DISPATCHED, line, memcpy(), NULL, procenv_t, readline_internal_char(), readline_internal_teardown(), RL_CHECK_SIGNALS, rl_clear_signals(), rl_deprep_term_function, rl_done, rl_eof_found, RL_ISSTATE, rl_line_buffer, rl_linefunc, rl_pending_input, rl_persistent_signal_handlers, rl_set_signals(), RL_SETSTATE, RL_STATE_CHARSEARCH, RL_STATE_DONE, RL_STATE_EOF, RL_STATE_INPUTPENDING, RL_STATE_ISEARCH, RL_STATE_MACROINPUT, RL_STATE_MULTIKEY, RL_STATE_NSEARCH, RL_STATE_NUMERICARG, RL_STATE_TIMEOUT, RL_STATE_VIMOTION, and setjmp.
Referenced by main().
rl_callback_sigcleanup()
void rl_callback_sigcleanup (void)
Definition at line 355 of file callback.c.
 {
   if (RL_ISSTATE (RL_STATE_CALLBACK) == 0)
     return;
   if (RL_ISSTATE (RL_STATE_ISEARCH))
     _rl_isearch_cleanup (_rl_iscxt, 0);
   else if (RL_ISSTATE (RL_STATE_NSEARCH))
     _rl_nsearch_cleanup (_rl_nscxt, 0);
   else if (RL_ISSTATE (RL_STATE_VIMOTION))
     RL_UNSETSTATE (RL_STATE_VIMOTION);
   else if (RL_ISSTATE (RL_STATE_NUMERICARG))
     {
       _rl_argcxt = 0;
       RL_UNSETSTATE (RL_STATE_NUMERICARG);
     }
   else if (RL_ISSTATE (RL_STATE_MULTIKEY))
     RL_UNSETSTATE (RL_STATE_MULTIKEY);
   if (RL_ISSTATE (RL_STATE_CHARSEARCH))
     RL_UNSETSTATE (RL_STATE_CHARSEARCH);
   _rl_callback_func = 0;
 }
References _rl_argcxt, _rl_callback_func, _rl_iscxt, _rl_isearch_cleanup(), _rl_nscxt, _rl_nsearch_cleanup(), RL_ISSTATE, RL_STATE_CALLBACK, RL_STATE_CHARSEARCH, RL_STATE_ISEARCH, RL_STATE_MULTIKEY, RL_STATE_NSEARCH, RL_STATE_NUMERICARG, RL_STATE_VIMOTION, and RL_UNSETSTATE.
Referenced by _rl_handle_signal().
rl_capitalize_word()
int rl_capitalize_word (int count, int key)
Definition at line 1393 of file text.c.
 {
  return (rl_change_case (count, CapCase));
 }
References CapCase, count, and rl_change_case().
rl_char_search()
int rl_char_search (int count, int key)
Definition at line 1778 of file text.c.
 {
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_data->i1 = FFIND;
       _rl_callback_data->i2 = BFIND;
       _rl_callback_func = _rl_char_search_callback;
       return (0);
     }
 #endif
   return (_rl_char_search (count, FFIND, BFIND));
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_char_search(), _rl_char_search_callback(), BFIND, count, FFIND, __rl_callback_generic_arg::i1, __rl_callback_generic_arg::i2, RL_ISSTATE, and RL_STATE_CALLBACK.
rl_character_len()
int rl_character_len (int c, int pos)
Definition at line 2931 of file display.c.
 {
   unsigned char uc;
   uc = (unsigned char)c;
   if (META_CHAR (uc))
     return ((_rl_output_meta_chars == 0) ? 4 : 1);
   if (uc == '\t')
     {
 #if defined (DISPLAY_TABS)
       return (((pos | 7) + 1) - pos);
 #else
       return (2);
 #endif /* !DISPLAY_TABS */
     }
   if (CTRL_CHAR (c) || c == RUBOUT)
     return (2);
   return ((ISPRINT (uc)) ? 1 : 2);
 }
References _rl_output_meta_chars, c, CTRL_CHAR, ISPRINT, META_CHAR, pos, and RUBOUT.
Referenced by _rl_overwrite_rubout(), and _rl_rubout_char().
rl_check_signals()
void rl_check_signals (void)
Definition at line 612 of file signals.c.
 {
   RL_CHECK_SIGNALS ();
 }
References RL_CHECK_SIGNALS.
rl_cleanup_after_signal()
void rl_cleanup_after_signal (void)
Definition at line 567 of file signals.c.
 {
   _rl_clean_up_for_exit ();
   if (rl_deprep_term_function)
     (*rl_deprep_term_function) ();
   rl_clear_pending_input ();
   rl_clear_signals ();
 }
References _rl_clean_up_for_exit(), rl_clear_pending_input(), rl_clear_signals(), and rl_deprep_term_function.
Referenced by _rl_handle_signal().
rl_clear_display()
int rl_clear_display (int count, int key)
Definition at line 610 of file text.c.
 {
   _rl_clear_screen (1);     /* calls termcap function to clear screen and scrollback buffer */
   rl_forced_update_display ();
   rl_display_fixed = 1;
   return 0;
 }
References _rl_clear_screen(), rl_display_fixed, and rl_forced_update_display().
rl_clear_history()
void rl_clear_history (void)
Definition at line 508 of file misc.c.
 {
   HIST_ENTRY **hlist, *hent;
   register int i;
   UNDO_LIST *ul, *saved_undo_list;
   saved_undo_list = rl_undo_list;
   hlist = history_list ();      /* direct pointer, not copy */
   for (i = 0; i < history_length; i++)
     {
       hent = hlist[i];
       if (ul = (UNDO_LIST *)hent->data)
     {
       if (ul == saved_undo_list)
         saved_undo_list = 0;
       _rl_free_undo_list (ul);
       hent->data = 0;
     }
       _rl_free_history_entry (hent);
     }
   history_offset = history_length = 0;
   rl_undo_list = saved_undo_list;   /* should be NULL */
 }
References _rl_free_history_entry(), _rl_free_undo_list(), _hist_entry::data, history_length, history_list(), history_offset, i, and rl_undo_list.
rl_clear_message()
int rl_clear_message (void)
Definition at line 3066 of file display.c.
 {
   rl_display_prompt = rl_prompt;
   if (msg_saved_prompt)
     {
       rl_restore_prompt ();
       msg_saved_prompt = 0;
     }
   (*rl_redisplay_function) ();
   return 0;
 }
References msg_saved_prompt, rl_display_prompt, rl_prompt, and rl_restore_prompt().
Referenced by _rl_abort_internal(), _rl_arg_callback(), _rl_arg_dispatch(), _rl_arg_overflow(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_nsearch_abort(), _rl_vi_arg_dispatch(), noninc_dosearch(), rl_discard_argument(), and rl_free_line_state().
rl_clear_pending_input()
int rl_clear_pending_input (void)
Definition at line 501 of file input.c.
 {
   rl_pending_input = 0;
   RL_UNSETSTATE (RL_STATE_INPUTPENDING);
   return 0;
 }
References rl_pending_input, RL_STATE_INPUTPENDING, and RL_UNSETSTATE.
Referenced by _rl_abort_internal(), readline(), rl_cleanup_after_signal(), and rl_read_key().
rl_clear_screen()
int rl_clear_screen (int count, int key)
Definition at line 593 of file text.c.
 {
   if (rl_explicit_arg)
     {
       rl_refresh_line (count, key);
       return 0;
     }
   _rl_clear_screen (0);     /* calls termcap function to clear screen */
   rl_keep_mark_active ();
   rl_forced_update_display ();
   rl_display_fixed = 1;
   return 0;
 }
References _rl_clear_screen(), count, rl_display_fixed, rl_explicit_arg, rl_forced_update_display(), rl_keep_mark_active(), and rl_refresh_line().
rl_clear_signals()
int rl_clear_signals (void)
Definition at line 514 of file signals.c.
 {
   sighandler_cxt dummy;
   if (rl_catch_signals && signals_set_flag == 1)
     {
       /* Since rl_maybe_set_sighandler doesn't override a SIG_IGN handler,
      we should in theory not have to restore a handler where
      old_xxx.sa_handler == SIG_IGN.  That's what rl_maybe_restore_sighandler
      does.  Fewer system calls should reduce readline's per-line
      overhead */
       rl_maybe_restore_sighandler (SIGINT, &old_int);
       rl_maybe_restore_sighandler (SIGTERM, &old_term);
 #if defined (SIGHUP)
       rl_maybe_restore_sighandler (SIGHUP, &old_hup);
 #endif
 #if defined (SIGQUIT)
       rl_maybe_restore_sighandler (SIGQUIT, &old_quit);
 #endif
 #if defined (SIGALRM)
       rl_maybe_restore_sighandler (SIGALRM, &old_alrm);
 #endif
 #if defined (SIGTSTP)
       rl_maybe_restore_sighandler (SIGTSTP, &old_tstp);
 #endif /* SIGTSTP */
 #if defined (SIGTTOU)
       rl_maybe_restore_sighandler (SIGTTOU, &old_ttou);
 #endif /* SIGTTOU */
 #if defined (SIGTTIN)
       rl_maybe_restore_sighandler (SIGTTIN, &old_ttin);
 #endif /* SIGTTIN */
       signals_set_flag = 0;
     }
 #if defined (SIGWINCH)
   if (rl_catch_sigwinch && sigwinch_set_flag == 1)
     {
       sigemptyset (&dummy.sa_mask);
       rl_sigaction (SIGWINCH, &old_winch, &dummy);
       sigwinch_set_flag = 0;
     }
 #endif
   return 0;
 }
References old_alrm, old_hup, old_int, old_quit, old_term, old_tstp, old_ttin, old_ttou, rl_catch_signals, rl_catch_sigwinch, rl_maybe_restore_sighandler(), rl_sigaction(), SIGALRM, sigemptyset, SIGHUP, SIGINT, signals_set_flag, SIGQUIT, SIGTERM, SIGTSTP, SIGTTIN, SIGTTOU, SIGWINCH, and sigwinch_set_flag.
Referenced by readline(), rl_callback_handler_remove(), rl_callback_read_char(), and rl_cleanup_after_signal().
rl_clear_visible_line()
int rl_clear_visible_line (void)
Definition at line 2597 of file display.c.
 {
   int curr_line;
   /* Make sure we move to column 0 so we clear the entire line */
   _rl_cr ();
   _rl_last_c_pos = 0;
   /* Move to the last screen line of the current visible line */
   _rl_move_vert (_rl_vis_botlin);
   /* And erase screen lines going up to line 0 (first visible line) */
   for (curr_line = _rl_last_v_pos; curr_line >= 0; curr_line--)
     {
       _rl_move_vert (curr_line);
       _rl_clear_to_eol (_rl_screenwidth);
       _rl_cr ();        /* in case we use space_to_eol() */
     }
   return 0;
 }
References _rl_clear_to_eol(), _rl_cr(), _rl_last_c_pos, _rl_last_v_pos, _rl_move_vert(), _rl_screenwidth, and _rl_vis_botlin.
Referenced by _rl_redisplay_after_sigwinch(), and _rl_refresh_line().
rl_complete()
int rl_complete (int ignore, int invoking_key)
Definition at line 434 of file complete.c.
 {
   rl_completion_invoking_key = invoking_key;
   if (rl_inhibit_completion)
     return (_rl_insert_char (ignore, invoking_key));
 #if 0
   else if (rl_last_func == rl_complete && completion_changed_buffer == 0 && last_completion_failed == 0)
 #else
   else if (rl_last_func == rl_complete && completion_changed_buffer == 0)
 #endif
     return (rl_complete_internal ('?'));
   else if (_rl_complete_show_all)
     return (rl_complete_internal ('!'));
   else if (_rl_complete_show_unmodified)
     return (rl_complete_internal ('@'));
   else
     return (rl_complete_internal (TAB));
 }
References _rl_complete_show_all, _rl_complete_show_unmodified, _rl_insert_char(), completion_changed_buffer, ignore(), last_completion_failed, rl_complete_internal(), rl_completion_invoking_key, rl_inhibit_completion, rl_last_func, and TAB.
Referenced by rl_vi_complete().
rl_complete_internal()
int rl_complete_internal (int what_to_do)
Definition at line 2000 of file complete.c.
 {
   char **matches;
   rl_compentry_func_t *our_func;
   int start, end, delimiter, found_quote, i, nontrivial_lcd;
   char *text, *saved_line_buffer;
   char quote_char;
   int tlen, mlen, saved_last_completion_failed;
   RL_SETSTATE(RL_STATE_COMPLETING);
   saved_last_completion_failed = last_completion_failed;
   set_completion_defaults (what_to_do);
   saved_line_buffer = rl_line_buffer ? savestring (rl_line_buffer) : (char *)NULL;
   our_func = rl_completion_entry_function
         ? rl_completion_entry_function
         : rl_filename_completion_function;
   /* We now look backwards for the start of a filename/variable word. */
   end = rl_point;
   found_quote = delimiter = 0;
   quote_char = '\0';
   if (rl_point)
     /* This (possibly) changes rl_point.  If it returns a non-zero char,
        we know we have an open quote. */
     quote_char = _rl_find_completion_word (&found_quote, &delimiter);
   start = rl_point;
   rl_point = end;
   text = rl_copy_text (start, end);
   matches = gen_completion_matches (text, start, end, our_func, found_quote, quote_char);
   /* nontrivial_lcd is set if the common prefix adds something to the word
      being completed. */
   nontrivial_lcd = matches && compare_match (text, matches[0]) != 0;
   if (what_to_do == '!' || what_to_do == '@')
     tlen = strlen (text);
   xfree (text);
   if (matches == 0)
     {
       rl_ding ();
       FREE (saved_line_buffer);
       completion_changed_buffer = 0;
       last_completion_failed = 1;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       _rl_reset_completion_state ();
       return (0);
     }
   /* If we are matching filenames, the attempted completion function will
      have set rl_filename_completion_desired to a non-zero value.  The basic
      rl_filename_completion_function does this. */
   i = rl_filename_completion_desired;
   if (postprocess_matches (&matches, i) == 0)
     {
       rl_ding ();
       FREE (saved_line_buffer);
       completion_changed_buffer = 0;
       last_completion_failed = 1;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       _rl_reset_completion_state ();
       return (0);
     }
   if (matches && matches[0] && *matches[0])
     last_completion_failed = 0;
   switch (what_to_do)
     {
     case TAB:
     case '!':
     case '@':
       /* Insert the first match with proper quoting. */
       if (what_to_do == TAB)
         {
           if (*matches[0])
         insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
         }
       else if (*matches[0] && matches[1] == 0)
     /* should we perform the check only if there are multiple matches? */
     insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
       else if (*matches[0]) /* what_to_do != TAB && multiple matches */
     {
       mlen = *matches[0] ? strlen (matches[0]) : 0;
       if (mlen >= tlen)
         insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
     }
       /* If there are more matches, ring the bell to indicate.
      If we are in vi mode, Posix.2 says to not ring the bell.
      If the `show-all-if-ambiguous' variable is set, display
      all the matches immediately.  Otherwise, if this was the
      only match, and we are hacking files, check the file to
      see if it was a directory.  If so, and the `mark-directories'
      variable is set, add a '/' to the name.  If not, and we
      are at the end of the line, then add a space.  */
       if (matches[1])
     {
       if (what_to_do == '!')
         {
           display_matches (matches);
           break;
         }
       else if (what_to_do == '@')
         {
           if (nontrivial_lcd == 0)
         display_matches (matches);
           break;
         }
       else if (rl_editing_mode != vi_mode)
         rl_ding (); /* There are other matches remaining. */
     }
       else
     append_to_match (matches[0], delimiter, quote_char, nontrivial_lcd);
       break;
     case '*':
       insert_all_matches (matches, start, &quote_char);
       break;
     case '?':
       /* Let's try to insert a single match here if the last completion failed
      but this attempt returned a single match. */
       if (saved_last_completion_failed && matches[0] && *matches[0] && matches[1] == 0)
     {
       insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
       append_to_match (matches[0], delimiter, quote_char, nontrivial_lcd);
       break;
     }
       if (rl_completion_display_matches_hook == 0)
     {
       _rl_sigcleanup = _rl_complete_sigcleanup;
       _rl_sigcleanarg = matches;
       _rl_complete_display_matches_interrupt = 0;
     }
       display_matches (matches);
       if (_rl_complete_display_matches_interrupt)
         {
           matches = 0;      /* already freed by rl_complete_sigcleanup */
           _rl_complete_display_matches_interrupt = 0;
       if (rl_signal_event_hook)
         (*rl_signal_event_hook) ();     /* XXX */
         }
       _rl_sigcleanup = 0;
       _rl_sigcleanarg = 0;
       break;
     default:
       _rl_ttymsg ("bad value %d for what_to_do in rl_complete", what_to_do);
       rl_ding ();
       FREE (saved_line_buffer);
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       _rl_free_match_list (matches);
       _rl_reset_completion_state ();
       return 1;
     }
   _rl_free_match_list (matches);
   /* Check to see if the line has changed through all of this manipulation. */
   if (saved_line_buffer)
     {
       completion_changed_buffer = strcmp (rl_line_buffer, saved_line_buffer) != 0;
       xfree (saved_line_buffer);
     }
   RL_UNSETSTATE(RL_STATE_COMPLETING);
   _rl_reset_completion_state ();
   RL_CHECK_SIGNALS ();
   return 0;
 }
References _rl_complete_display_matches_interrupt, _rl_complete_sigcleanup(), _rl_find_completion_word(), _rl_free_match_list(), _rl_reset_completion_state(), _rl_sigcleanarg, _rl_sigcleanup, _rl_ttymsg(), append_to_match(), compare_match(), completion_changed_buffer, display_matches(), end, FREE, gen_completion_matches(), i, insert_all_matches(), insert_match(), last_completion_failed, MULT_MATCH, NULL, postprocess_matches(), RL_CHECK_SIGNALS, rl_completion_display_matches_hook, rl_completion_entry_function, rl_copy_text(), rl_ding(), rl_editing_mode, rl_filename_completion_desired, rl_filename_completion_function(), rl_line_buffer, rl_point, RL_SETSTATE, rl_signal_event_hook, RL_STATE_COMPLETING, RL_UNSETSTATE, savestring(), set_completion_defaults(), SINGLE_MATCH, start, strcmp, strlen(), TAB, text, vi_mode, and xfree.
Referenced by rl_complete(), rl_insert_completions(), rl_possible_completions(), and rl_vi_complete().
rl_completion_matches()
char** rl_completion_matches (const char * text, rl_compentry_func_t * entry_function)
Definition at line 2198 of file complete.c.
 {
   register int i;
   /* Number of slots in match_list. */
   int match_list_size;
   /* The list of matches. */
   char **match_list;
   /* Number of matches actually found. */
   int matches;
   /* Temporary string binder. */
   char *string;
   matches = 0;
   match_list_size = 10;
   match_list = (char **)xmalloc ((match_list_size + 1) * sizeof (char *));
   match_list[1] = (char *)NULL;
   while (string = (*entry_function) (text, matches))
     {
       if (RL_SIG_RECEIVED ())
     {
       /* Start at 1 because we don't set matches[0] in this function.
          Only free the list members if we're building match list from
          rl_filename_completion_function, since we know that doesn't
          free the strings it returns. */
       if (entry_function == rl_filename_completion_function)
         {
           for (i = 1; match_list[i]; i++)
         xfree (match_list[i]);
         }
       xfree (match_list);
       match_list = 0;
       match_list_size = 0;
       matches = 0;
       RL_CHECK_SIGNALS ();
     }
       if (matches + 1 >= match_list_size)
     match_list = (char **)xrealloc
       (match_list, ((match_list_size += 10) + 1) * sizeof (char *));
       if (match_list == 0)
     return (match_list);
       match_list[++matches] = string;
       match_list[matches + 1] = (char *)NULL;
     }
   /* If there were any matches, then look through them finding out the
      lowest common denominator.  That then becomes match_list[0]. */
   if (matches)
     compute_lcd_of_matches (match_list, matches, text);
   else              /* There were no matches. */
     {
       xfree (match_list);
       match_list = (char **)NULL;
     }
   return (match_list);
 }
Referenced by gen_completion_matches().
rl_completion_mode()
int rl_completion_mode (rl_command_func_t * cfunc)
Definition at line 475 of file complete.c.
 {
   if (rl_last_func == cfunc && !completion_changed_buffer)
     return '?';
   else if (_rl_complete_show_all)
     return '!';
   else if (_rl_complete_show_unmodified)
     return '@';
   else
     return TAB;
 }
References _rl_complete_show_all, _rl_complete_show_unmodified, completion_changed_buffer, rl_last_func, and TAB.
rl_copy_backward_word()
int rl_copy_backward_word (int count, int key)
Definition at line 500 of file kill.c.
 {
   if (count < 0)
     return (rl_copy_forward_word (-count, key));
   return (_rl_copy_word_as_kill (count, -1));
 }
References _rl_copy_word_as_kill(), count, and rl_copy_forward_word().
Referenced by rl_copy_forward_word().
rl_copy_forward_word()
int rl_copy_forward_word (int count, int key)
Definition at line 491 of file kill.c.
 {
   if (count < 0)
     return (rl_copy_backward_word (-count, key));
   return (_rl_copy_word_as_kill (count, 1));
 }
References _rl_copy_word_as_kill(), count, and rl_copy_backward_word().
Referenced by rl_copy_backward_word().
rl_copy_keymap()
Keymap rl_copy_keymap (Keymap map)
Definition at line 98 of file keymaps.c.
 {
   register int i;
   Keymap temp;
   temp = rl_make_bare_keymap ();
   for (i = 0; i < KEYMAP_SIZE; i++)
     {
       temp[i].type = map[i].type;
       temp[i].function = map[i].function;
     }
   return (temp);
 }
References _keymap_entry::function, i, KEYMAP_SIZE, map, rl_make_bare_keymap(), and _keymap_entry::type.
rl_copy_region_to_kill()
int rl_copy_region_to_kill (int count, int key)
Definition at line 442 of file kill.c.
 {
   return (region_kill_internal (0));
 }
References region_kill_internal().
rl_copy_text()
char* rl_copy_text (int from, int to)
Definition at line 147 of file util.c.
 {
   register int length;
   char *copy;
   /* Fix it if the caller is confused. */
   if (from > to)
     SWAP (from, to);
   length = to - from;
   copy = (char *)xmalloc (1 + length);
   strncpy (copy, rl_line_buffer + from, length);
   copy[length] = '\0';
   return (copy);
 }
References rl_line_buffer, strncpy(), SWAP, and xmalloc.
Referenced by region_kill_internal(), rl_complete_internal(), rl_delete_text(), rl_kill_text(), rl_menu_complete(), rl_modifying(), rl_old_menu_complete(), and rl_transpose_words().
rl_crlf()
int rl_crlf (void)
Definition at line 734 of file terminal.c.
 {
 #if defined (NEW_TTY_DRIVER) || defined (__MINT__)
   if (_rl_term_cr)
     tputs (_rl_term_cr, 1, _rl_output_character_function);
 #endif /* NEW_TTY_DRIVER || __MINT__ */
   putc ('\n', _rl_out_stream);
   return 0;
 }
rl_deactivate_mark()
void rl_deactivate_mark (void)
Definition at line 1879 of file text.c.
 {
   mark_active = 0;
 }
References mark_active.
Referenced by _rl_abort_internal(), _rl_internal_char_cleanup(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_nsearch_dispatch(), readline_internal_setup(), rl_newline(), and rl_restore_state().
rl_delete()
int rl_delete (int count, int key)
Definition at line 1251 of file text.c.
 {
   int xpoint;
   if (count < 0)
     return (_rl_rubout_char (-count, key));
   if (rl_point == rl_end)
     {
       rl_ding ();
       return 1;
     }
   if (count > 1 || rl_explicit_arg)
     {
       xpoint = rl_point;
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_forward_char (count, key);
       else
     rl_forward_byte (count, key);
       rl_kill_text (xpoint, rl_point);
       rl_point = xpoint;
     }
   else
     {
       xpoint = MB_NEXTCHAR (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
       rl_delete_text (rl_point, xpoint);
     }
   return 0;
 }
References _rl_rubout_char(), count, MB_CUR_MAX, MB_FIND_NONZERO, MB_NEXTCHAR, rl_byte_oriented, rl_delete_text(), rl_ding(), rl_end, rl_explicit_arg, rl_forward_byte(), rl_forward_char(), rl_kill_text(), rl_line_buffer, and rl_point.
Referenced by _rl_overwrite_char(), _rl_rubout_char(), bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_delete_or_show_completions(), rl_rubout(), and rl_rubout_or_delete().
rl_delete_horizontal_space()
int rl_delete_horizontal_space (int count, int ignore)
Definition at line 1298 of file text.c.
 {
   int start;
   while (rl_point && whitespace (rl_line_buffer[rl_point - 1]))
     rl_point--;
   start = rl_point;
   while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     rl_point++;
   if (start != rl_point)
     {
       rl_delete_text (start, rl_point);
       rl_point = start;
     }
   if (rl_point < 0)
     rl_point = 0;
   return 0;
 }
References rl_delete_text(), rl_end, rl_line_buffer, rl_point, start, and whitespace.
rl_delete_or_show_completions()
int rl_delete_or_show_completions (int count, int key)
Definition at line 1326 of file text.c.
 {
   if (rl_end != 0 && rl_point == rl_end)
     return (rl_possible_completions (count, key));
   else
     return (rl_delete (count, key));
 }
References count, rl_delete(), rl_end, rl_point, and rl_possible_completions().
rl_delete_text()
int rl_delete_text (int from, int to)
Definition at line 124 of file text.c.
 {
   register char *text;
   register int diff, i;
   /* Fix it if the caller is confused. */
   if (from > to)
     SWAP (from, to);
   /* fix boundaries */
   if (to > rl_end)
     {
       to = rl_end;
       if (from > to)
     from = to;
     }
   if (from < 0)
     from = 0;
   text = rl_copy_text (from, to);
   /* Some versions of strncpy() can't handle overlapping arguments. */
   diff = to - from;
   for (i = from; i < rl_end - diff; i++)
     rl_line_buffer[i] = rl_line_buffer[i + diff];
   /* Remember how to undo this delete. */
   if (_rl_doing_an_undo == 0)
     rl_add_undo (UNDO_DELETE, from, to, text);
   else
     xfree (text);
   rl_end -= diff;
   rl_line_buffer[rl_end] = '\0';
   _rl_fix_mark ();
   return (diff);
 }
References _rl_doing_an_undo, _rl_fix_mark(), diff(), i, rl_add_undo(), rl_copy_text(), rl_end, rl_line_buffer, SWAP, text, UNDO_DELETE, and xfree.
Referenced by _rl_overwrite_rubout(), _rl_replace_text(), _rl_rubout_char(), insert_all_matches(), region_kill_internal(), rl_delete(), rl_delete_horizontal_space(), rl_do_undo(), rl_insert_comment(), rl_kill_text(), rl_transpose_chars(), rl_transpose_words(), rl_vi_yank_pop(), rl_yank_pop(), and vi_change_dispatch().
rl_deprep_terminal()
void rl_deprep_terminal (void)
Definition at line 680 of file rltty.c.
 {
   int tty;
   if (terminal_prepped == 0)
     return;
   /* Try to keep this function from being interrupted. */
   _rl_block_sigint ();
   tty = rl_instream ? fileno (rl_instream) : fileno (stdin);
   if (terminal_prepped & TPX_BRACKPASTE)
     {
       fprintf (rl_outstream, BRACK_PASTE_FINI);
       /* Since the last character in BRACK_PASTE_FINI is \r */
       _rl_last_c_pos = 0;
       if (rl_eof_found && (RL_ISSTATE (RL_STATE_TIMEOUT) == 0))
     fprintf (rl_outstream, "\n");
       else if (_rl_echoing_p == 0)
     fprintf (rl_outstream, "\n");
     }
   if (_rl_enable_keypad)
     _rl_control_keypad (0);
   fflush (rl_outstream);
   if (set_tty_settings (tty, &otio) < 0)
     {
       _rl_release_sigint ();
       return;
     }
   terminal_prepped = 0;
   RL_UNSETSTATE(RL_STATE_TERMPREPPED);
   _rl_release_sigint ();
 }
References _rl_block_sigint(), _rl_control_keypad(), _rl_echoing_p, _rl_enable_keypad, _rl_last_c_pos, _rl_release_sigint(), BRACK_PASTE_FINI, fflush(), fileno(), fprintf(), otio, rl_eof_found, rl_instream, RL_ISSTATE, rl_outstream, RL_STATE_TERMPREPPED, RL_STATE_TIMEOUT, RL_UNSETSTATE, set_tty_settings(), stdin, terminal_prepped, and TPX_BRACKPASTE.
rl_digit_argument()
int rl_digit_argument (int ignore, int key)
Definition at line 226 of file misc.c.
 {
   _rl_arg_init ();
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_arg_dispatch (_rl_argcxt, key);
       rl_message ("(arg: %d) ", rl_arg_sign * rl_numeric_arg);
       return 0;
     }
   else
     {
       rl_execute_next (key);
       return (rl_digit_loop ());
     }
 }
References _rl_arg_dispatch(), _rl_arg_init(), _rl_argcxt, rl_arg_sign, rl_digit_loop(), rl_execute_next(), RL_ISSTATE, rl_message(), rl_numeric_arg, and RL_STATE_CALLBACK.
Referenced by _rl_dispatch_subseq(), rl_trim_arg_from_keyseq(), and rl_vi_arg_digit().
rl_ding()
int rl_ding (void)
Definition at line 756 of file terminal.c.
 {
   if (_rl_echoing_p)
     {
       switch (_rl_bell_preference)
         {
     case NO_BELL:
     default:
       break;
     case VISIBLE_BELL:
       if (_rl_visible_bell)
         {
 #ifdef __DJGPP__
           ScreenVisualBell ();
 #else
           tputs (_rl_visible_bell, 1, _rl_output_character_function);
 #endif
           break;
         }
       /* FALLTHROUGH */
     case AUDIBLE_BELL:
       fprintf (stderr, "\007");
       fflush (stderr);
       break;
         }
       return (0);
     }
   return (-1);
 }
rl_discard_argument()
int rl_discard_argument (void)
Definition at line 281 of file misc.c.
 {
   rl_ding ();
   rl_clear_message ();
   _rl_reset_argument ();
   return 0;
 }
References _rl_reset_argument(), rl_clear_message(), and rl_ding().
rl_discard_keymap()
void rl_discard_keymap (Keymap map)
Definition at line 142 of file keymaps.c.
 {
   int i;
   if (map == 0)
     return;
   for (i = 0; i < KEYMAP_SIZE; i++)
     {
       switch (map[i].type)
     {
     case ISFUNC:
       break;
     case ISKMAP:
       rl_discard_keymap ((Keymap)map[i].function);
       xfree ((char *)map[i].function);
       break;
     case ISMACR:
       xfree ((char *)map[i].function);
       break;
     }
     }
 }
References i, ISFUNC, ISKMAP, ISMACR, KEYMAP_SIZE, map, type, and xfree.
Referenced by rl_free_keymap(), and rl_generic_bind().
rl_display_match_list()
void rl_display_match_list (char ** matches, int len, int max)
Definition at line 1531 of file complete.c.
 {
   int count, limit, printed_len, lines, cols;
   int i, j, k, l, common_length, sind;
   char *temp, *t;
   /* Find the length of the prefix common to all items: length as displayed
      characters (common_length) and as a byte index into the matches (sind) */
   common_length = sind = 0;
   if (_rl_completion_prefix_display_length > 0)
     {
       t = printable_part (matches[0]);
       /* check again in case of /usr/src/ */
       temp = rl_filename_completion_desired ? strrchr (t, '/') : 0;
       common_length = temp ? fnwidth (temp) : fnwidth (t);
       sind = temp ? strlen (temp) : strlen (t);
       if (common_length > max || sind > max)
     common_length = sind = 0;
       if (common_length > _rl_completion_prefix_display_length && common_length > ELLIPSIS_LEN)
     max -= common_length - ELLIPSIS_LEN;
       else if (_rl_colored_completion_prefix <= 0)
     common_length = sind = 0;
     }
 #if defined (COLOR_SUPPORT)
   else if (_rl_colored_completion_prefix > 0)
     {
       t = printable_part (matches[0]);
       temp = rl_filename_completion_desired ? strrchr (t, '/') : 0;
       common_length = temp ? fnwidth (temp) : fnwidth (t);
       sind = temp ? RL_STRLEN (temp+1) : RL_STRLEN (t);     /* want portion after final slash */
       if (common_length > max || sind > max)
     common_length = sind = 0;
     }
 #endif
   /* How many items of MAX length can we fit in the screen window? */
   cols = complete_get_screenwidth ();
   max += 2;
   limit = cols / max;
   if (limit != 1 && (limit * max == cols))
     limit--;
   /* If cols == 0, limit will end up -1 */
   if (cols < _rl_screenwidth && limit < 0)
     limit = 1;
   /* Avoid a possible floating exception.  If max > cols,
      limit will be 0 and a divide-by-zero fault will result. */
   if (limit == 0)
     limit = 1;
   /* How many iterations of the printing loop? */
   count = (len + (limit - 1)) / limit;
   /* Watch out for special case.  If LEN is less than LIMIT, then
      just do the inner printing loop.
        0 < len <= limit  implies  count = 1. */
   /* Sort the items if they are not already sorted. */
   if (rl_ignore_completion_duplicates == 0 && rl_sort_completion_matches)
     qsort (matches + 1, len, sizeof (char *), (QSFUNC *)_rl_qsort_string_compare);
   rl_crlf ();
   lines = 0;
   if (_rl_print_completions_horizontally == 0)
     {
       /* Print the sorted items, up-and-down alphabetically, like ls. */
       for (i = 1; i <= count; i++)
     {
       for (j = 0, l = i; j < limit; j++)
         {
           if (l > len || matches[l] == 0)
         break;
           else
         {
           temp = printable_part (matches[l]);
           printed_len = print_filename (temp, matches[l], sind);
           if (j + 1 < limit)
             {
               if (max <= printed_len)
             putc (' ', rl_outstream);
               else
             for (k = 0; k < max - printed_len; k++)
               putc (' ', rl_outstream);
             }
         }
           l += count;
         }
       rl_crlf ();
 #if defined (SIGWINCH)
       if (RL_SIG_RECEIVED () && RL_SIGWINCH_RECEIVED() == 0)
 #else
       if (RL_SIG_RECEIVED ())
 #endif
         return;
       lines++;
       if (_rl_page_completions && lines >= (_rl_screenheight - 1) && i < count)
         {
           lines = _rl_internal_pager (lines);
           if (lines < 0)
         return;
         }
     }
     }
   else
     {
       /* Print the sorted items, across alphabetically, like ls -x. */
       for (i = 1; matches[i]; i++)
     {
       temp = printable_part (matches[i]);
       printed_len = print_filename (temp, matches[i], sind);
       /* Have we reached the end of this line? */
 #if defined (SIGWINCH)
       if (RL_SIG_RECEIVED () && RL_SIGWINCH_RECEIVED() == 0)
 #else
       if (RL_SIG_RECEIVED ())
 #endif
         return;
       if (matches[i+1])
         {
           if (limit == 1 || (i && (limit > 1) && (i % limit) == 0))
         {
           rl_crlf ();
           lines++;
           if (_rl_page_completions && lines >= _rl_screenheight - 1)
             {
               lines = _rl_internal_pager (lines);
               if (lines < 0)
             return;
             }
         }
           else if (max <= printed_len)
         putc (' ', rl_outstream);
           else
         for (k = 0; k < max - printed_len; k++)
           putc (' ', rl_outstream);
         }
     }
       rl_crlf ();
     }
 }
References _rl_colored_completion_prefix, _rl_completion_prefix_display_length, _rl_internal_pager(), _rl_page_completions, _rl_print_completions_horizontally, _rl_qsort_string_compare(), _rl_screenheight, _rl_screenwidth, cols, complete_get_screenwidth(), count, ELLIPSIS_LEN, fnwidth(), i, j, k, l, limit(), lines, max, print_filename(), printable_part(), putc, qsort(), rl_crlf(), rl_filename_completion_desired, rl_ignore_completion_duplicates, rl_outstream, RL_SIG_RECEIVED, RL_SIGWINCH_RECEIVED, rl_sort_completion_matches, RL_STRLEN, strlen(), strrchr(), and t.
Referenced by display_matches().
rl_do_lowercase_version()
int rl_do_lowercase_version (int ignore1, int ignore2)
Definition at line 1137 of file text.c.
 {
   return 99999;     /* prevent from being combined with _rl_null_function */
 }
Referenced by _rl_dispatch_subseq(), _rl_isearch_dispatch(), _rl_subseq_result(), rl_bind_keyseq_if_unbound_in_map(), rl_generic_bind(), and rl_make_bare_keymap().
rl_do_undo()
int rl_do_undo (void)
Definition at line 167 of file undo.c.
 {
   UNDO_LIST *release, *search;
   int waiting_for_begin, start, end;
   HIST_ENTRY *cur, *temp;
 #define TRANS(i) ((i) == -1 ? rl_point : ((i) == -2 ? rl_end : (i)))
   start = end = waiting_for_begin = 0;
   do
     {
       if (rl_undo_list == 0)
     return (0);
       _rl_doing_an_undo = 1;
       RL_SETSTATE(RL_STATE_UNDOING);
       /* To better support vi-mode, a start or end value of -1 means
      rl_point, and a value of -2 means rl_end. */
       if (rl_undo_list->what == UNDO_DELETE || rl_undo_list->what == UNDO_INSERT)
     {
       start = TRANS (rl_undo_list->start);
       end = TRANS (rl_undo_list->end);
     }
       switch (rl_undo_list->what)
     {
     /* Undoing deletes means inserting some text. */
     case UNDO_DELETE:
       rl_point = start;
       _rl_fix_point (1);
       rl_insert_text (rl_undo_list->text);
       xfree (rl_undo_list->text);
       break;
     /* Undoing inserts means deleting some text. */
     case UNDO_INSERT:
       rl_delete_text (start, end);
       rl_point = start;
       _rl_fix_point (1);
       break;
     /* Undoing an END means undoing everything 'til we get to a BEGIN. */
     case UNDO_END:
       waiting_for_begin++;
       break;
     /* Undoing a BEGIN means that we are done with this group. */
     case UNDO_BEGIN:
       if (waiting_for_begin)
         waiting_for_begin--;
       else
         rl_ding ();
       break;
     }
       _rl_doing_an_undo = 0;
       RL_UNSETSTATE(RL_STATE_UNDOING);
       release = rl_undo_list;
       rl_undo_list = rl_undo_list->next;
       release->next = 0;    /* XXX */
       /* If we are editing a history entry, make sure the change is replicated
      in the history entry's line */
       cur = current_history ();
       if (cur && cur->data && (UNDO_LIST *)cur->data == release)
     {
       temp = replace_history_entry (where_history (), rl_line_buffer, (histdata_t)rl_undo_list);
       xfree (temp->line);
       FREE (temp->timestamp);
       xfree (temp);
     }
       /* Make sure there aren't any history entries with that undo list */
       _hs_replace_history_data (-1, (histdata_t *)release, (histdata_t *)rl_undo_list);
       /* And make sure this list isn't anywhere in the saved line for history */
       if (_rl_saved_line_for_history && _rl_saved_line_for_history->data)
     {
       /* Brute force; no finesse here */
       search = (UNDO_LIST *)_rl_saved_line_for_history->data;
       if (search == release)
         _rl_saved_line_for_history->data = rl_undo_list;
       else
         {
           while (search->next)
         {
           if (search->next == release)
             {
               search->next = rl_undo_list;
               break;
             }
           search = search->next;
         }
         }
     }
       xfree (release);
     }
   while (waiting_for_begin);
   return (1);
 }
References _hs_replace_history_data(), _rl_doing_an_undo, _rl_fix_point(), _rl_saved_line_for_history, cur, current_history(), _hist_entry::data, undo_list::end, end, FREE, if(), _hist_entry::line, undo_list::next, release(), replace_history_entry(), rl_delete_text(), rl_ding(), rl_insert_text(), rl_line_buffer, rl_point, RL_SETSTATE, RL_STATE_UNDOING, rl_undo_list, RL_UNSETSTATE, search(), undo_list::start, start, undo_list::text, _hist_entry::timestamp, TRANS, UNDO_BEGIN, UNDO_DELETE, UNDO_END, UNDO_INSERT, undo_list::what, where_history(), and xfree.
Referenced by _rl_revert_previous_lines(), rl_revert_line(), rl_undo_command(), rl_vi_overstrike_delete(), rl_yank_last_arg(), and vi_yank_dispatch().
rl_downcase_word()
int rl_downcase_word (int count, int key)
Definition at line 1386 of file text.c.
 {
   return (rl_change_case (count, DownCase));
 }
References count, DownCase, and rl_change_case().
rl_dump_functions()
int rl_dump_functions (int count, int key)
Definition at line 2866 of file bind.c.
 {
   if (rl_dispatching)
     fprintf (rl_outstream, "\r\n");
   rl_function_dumper (rl_explicit_arg);
   rl_on_new_line ();
   return (0);
 }
References fprintf(), rl_dispatching, rl_explicit_arg, rl_function_dumper(), rl_on_new_line(), and rl_outstream.
rl_dump_macros()
int rl_dump_macros (int count, int key)
Definition at line 2941 of file bind.c.
 {
   if (rl_dispatching)
     fprintf (rl_outstream, "\r\n");
   rl_macro_dumper (rl_explicit_arg);
   rl_on_new_line ();
   return (0);
 }
References fprintf(), rl_dispatching, rl_explicit_arg, rl_macro_dumper(), rl_on_new_line(), and rl_outstream.
rl_dump_variables()
int rl_dump_variables (int count, int key)
Definition at line 3062 of file bind.c.
 {
   if (rl_dispatching)
     fprintf (rl_outstream, "\r\n");
   rl_variable_dumper (rl_explicit_arg);
   rl_on_new_line ();
   return (0);
 }
References fprintf(), rl_dispatching, rl_explicit_arg, rl_on_new_line(), rl_outstream, and rl_variable_dumper().
rl_echo_signal_char()
void rl_echo_signal_char (int sig)
Definition at line 721 of file signals.c.
 {
   char cstr[3];
   int cslen, c;
   if (_rl_echoctl == 0 || _rl_echo_control_chars == 0)
     return;
   switch (sig)
     {
     case SIGINT:  c = _rl_intr_char; break;
 #if defined (SIGQUIT)
     case SIGQUIT: c = _rl_quit_char; break;
 #endif
 #if defined (SIGTSTP)
     case SIGTSTP: c = _rl_susp_char; break;
 #endif
     default: return;
     }
   if (CTRL_CHAR (c) || c == RUBOUT)
     {
       cstr[0] = '^';
       cstr[1] = CTRL_CHAR (c) ? UNCTRL (c) : '?';
       cstr[cslen = 2] = '\0';
     }
   else
     {
       cstr[0] = c;
       cstr[cslen = 1] = '\0';
     }
   _rl_output_some_chars (cstr, cslen);
 }
References _rl_echo_control_chars, _rl_echoctl, _rl_intr_char, _rl_output_some_chars(), _rl_quit_char, _rl_susp_char, c, CTRL_CHAR, RUBOUT, SIGINT, SIGQUIT, SIGTSTP, and UNCTRL.
Referenced by _rl_handle_signal().
rl_emacs_editing_mode()
int rl_emacs_editing_mode (int count, int key)
Definition at line 745 of file misc.c.
 {
   rl_editing_mode = emacs_mode;
   _rl_set_insert_mode (RL_IM_INSERT, 1); /* emacs mode default is insert mode */
   _rl_keymap = emacs_standard_keymap;
   if (_rl_show_mode_in_prompt)
     _rl_reset_prompt ();
   return 0;
 }
References _rl_keymap, _rl_reset_prompt(), _rl_set_insert_mode(), _rl_show_mode_in_prompt, emacs_mode, emacs_standard_keymap, rl_editing_mode, and RL_IM_INSERT.
rl_empty_keymap()
int rl_empty_keymap (Keymap keymap)
Definition at line 83 of file keymaps.c.
 {
   int i;
   for (i = 0; i < ANYOTHERKEY; i++)
     {
       if (keymap[i].type != ISFUNC || keymap[i].function)
     return 0;
     }
   return 1;
 }
References ANYOTHERKEY, i, ISFUNC, and type.
Referenced by rl_generic_bind().
rl_end_kbd_macro()
int rl_end_kbd_macro (int count, int ignore)
Definition at line 270 of file macro.c.
 {
   if (RL_ISSTATE (RL_STATE_MACRODEF) == 0)
     {
       _rl_abort_internal ();
       return 1;
     }
   current_macro_index -= rl_key_sequence_length;
   if (current_macro_index < 0)
     current_macro_index = 0;
   current_macro[current_macro_index] = '\0';
   RL_UNSETSTATE(RL_STATE_MACRODEF);
   return (rl_call_last_kbd_macro (--count, 0));
 }
References _rl_abort_internal(), count, current_macro, current_macro_index, rl_call_last_kbd_macro(), RL_ISSTATE, rl_key_sequence_length, RL_STATE_MACRODEF, and RL_UNSETSTATE.
rl_end_of_history()
int rl_end_of_history (int count, int key)
Definition at line 549 of file misc.c.
 {
   rl_maybe_replace_line ();
   using_history ();
   rl_maybe_unsave_line ();
   return 0;
 }
References rl_maybe_replace_line(), rl_maybe_unsave_line(), and using_history().
rl_end_of_line()
int rl_end_of_line (int count, int key)
Definition at line 473 of file text.c.
 {
   rl_point = rl_end;
   return 0;
 }
References rl_end, and rl_point.
Referenced by bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_kill_line(), rl_vi_append_eol(), rl_vi_column(), and rl_vi_redo().
rl_end_undo_group()
int rl_end_undo_group (void)
Definition at line 301 of file undo.c.
 {
   rl_add_undo (UNDO_END, 0, 0, 0);
   _rl_undo_group_level--;
   return 0;
 }
References _rl_undo_group_level, rl_add_undo(), and UNDO_END.
Referenced by _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_replace_text(), _rl_vi_change_char(), _rl_vi_done_inserting(), _rl_vi_replace_insert(), _rl_vi_stuff_insert(), insert_all_matches(), rl_kill_full_line(), rl_modifying(), rl_transpose_chars(), rl_transpose_words(), rl_vi_change_case(), rl_vi_overstrike_delete(), rl_yank_nth_arg_internal(), vi_change_dispatch(), and vi_yank_dispatch().
rl_exchange_point_and_mark()
int rl_exchange_point_and_mark (int count, int key)
Definition at line 1837 of file text.c.
 {
   if (rl_mark > rl_end)
     rl_mark = -1;
   if (rl_mark < 0)
     {
       rl_ding ();
       rl_mark = 0;      /* like _RL_FIX_POINT */
       return 1;
     }
   else
     {
       SWAP (rl_point, rl_mark);
       rl_activate_mark ();
     }
   return 0;
 }
References rl_activate_mark(), rl_ding(), rl_end, rl_mark, rl_point, and SWAP.
rl_execute_next()
int rl_execute_next (int c)
Definition at line 492 of file input.c.
 {
   rl_pending_input = c;
   RL_SETSTATE (RL_STATE_INPUTPENDING);
   return 0;
 }
References c, rl_pending_input, RL_SETSTATE, and RL_STATE_INPUTPENDING.
Referenced by _rl_arg_callback(), _rl_isearch_dispatch(), rl_digit_argument(), and rl_insert().
rl_expand_prompt()
int rl_expand_prompt (char * prompt)
Definition at line 585 of file display.c.
 {
   char *p, *t;
   int c;
   /* Clear out any saved values. */
   FREE (local_prompt);
   FREE (local_prompt_prefix);
   local_prompt = local_prompt_prefix = (char *)0;
   local_prompt_len = 0;
   prompt_last_invisible = prompt_invis_chars_first_line = 0;
   prompt_visible_length = prompt_physical_chars = 0;
   if (prompt == 0 || *prompt == 0)
     return (0);
   p = strrchr (prompt, '\n');
   if (p == 0)
     {
       /* The prompt is only one logical line, though it might wrap. */
       local_prompt = expand_prompt (prompt, 0, &prompt_visible_length,
                            &prompt_last_invisible,
                            &prompt_invis_chars_first_line,
                            &prompt_physical_chars);
       local_prompt_prefix = (char *)0;
       local_prompt_len = local_prompt ? strlen (local_prompt) : 0;
       return (prompt_visible_length);
     }
   else
     {
       /* The prompt spans multiple lines. */
       t = ++p;
       c = *t; *t = '\0';
       /* The portion of the prompt string up to and including the
      final newline is now null-terminated. */
       local_prompt_prefix = expand_prompt (prompt, PMT_MULTILINE,
                            &prompt_prefix_length,
                            (int *)NULL,
                            (int *)NULL,
                            (int *)NULL);
       *t = c;
       local_prompt = expand_prompt (p, PMT_MULTILINE,
                        &prompt_visible_length,
                        &prompt_last_invisible,
                        &prompt_invis_chars_first_line,
                        &prompt_physical_chars);
       local_prompt_len = local_prompt ? strlen (local_prompt) : 0;
       return (prompt_prefix_length);
     }
 }
References c, expand_prompt(), FREE, local_prompt, local_prompt_len, local_prompt_prefix, NULL, p, PMT_MULTILINE, prompt, prompt_invis_chars_first_line, prompt_last_invisible, prompt_physical_chars, prompt_prefix_length, prompt_visible_length, strlen(), strrchr(), and t.
Referenced by _rl_reset_prompt(), and rl_set_prompt().
rl_extend_line_buffer()
void rl_extend_line_buffer (int len)
Definition at line 166 of file util.c.
 {
   while (len >= rl_line_buffer_len)
     {
       rl_line_buffer_len += DEFAULT_BUFFER_SIZE;
       rl_line_buffer = (char *)xrealloc (rl_line_buffer, rl_line_buffer_len);
     }
   _rl_set_the_line ();
 }
References _rl_set_the_line(), DEFAULT_BUFFER_SIZE, rl_line_buffer, rl_line_buffer_len, and xrealloc.
Referenced by rl_change_case(), rl_domove_motion_callback(), rl_insert_text(), and rl_replace_line().
rl_fetch_history()
int rl_fetch_history (int count, int c)
Definition at line 653 of file misc.c.
 {
   int wanted, nhist;
   /* Giving an argument of n means we want the nth command in the history
      file.  The command number is interpreted the same way that the bash
      `history' command does it -- that is, giving an argument count of 450
      to this command would get the command listed as number 450 in the
      output of `history'. */
   if (rl_explicit_arg)
     {
       nhist = history_base + where_history ();
       /* Negative arguments count back from the end of the history list. */
       wanted = (count >= 0) ? nhist - count : -count;
       if (wanted <= 0 || wanted >= nhist)
     {
       /* In vi mode, we don't change the line with an out-of-range
          argument, as for the `G' command. */
       if (rl_editing_mode == vi_mode)
         rl_ding ();
       else
         rl_beginning_of_history (0, 0);
     }
       else
         rl_get_previous_history (wanted, c);
     }
   else
     rl_beginning_of_history (count, 0);
   return (0);
 }
References c, count, history_base, rl_beginning_of_history(), rl_ding(), rl_editing_mode, rl_explicit_arg, rl_get_previous_history(), vi_mode, and where_history().
Referenced by rl_vi_fetch_history().
rl_filename_completion_function()
char* rl_filename_completion_function (const char * text, int state)
Definition at line 2456 of file complete.c.
 {
   static DIR *directory = (DIR *)NULL;
   static char *filename = (char *)NULL;
   static char *dirname = (char *)NULL;
   static char *users_dirname = (char *)NULL;
   static int filename_len;
   char *temp, *dentry, *convfn;
   int dirlen, dentlen, convlen;
   int tilde_dirname;
   struct dirent *entry;
   /* If we don't have any state, then do some initialization. */
   if (state == 0)
     {
       /* If we were interrupted before closing the directory or reading
      all of its contents, close it. */
       if (directory)
     {
       closedir (directory);
       directory = (DIR *)NULL;
     }
       FREE (dirname);
       FREE (filename);
       FREE (users_dirname);
       filename = savestring (text);
       if (*text == 0)
     text = ".";
       dirname = savestring (text);
       temp = strrchr (dirname, '/');
 #if defined (__MSDOS__) || defined (_WIN32)
       /* special hack for //X/... */
       if (dirname[0] == '/' && dirname[1] == '/' && ISALPHA ((unsigned char)dirname[2]) && dirname[3] == '/')
         temp = strrchr (dirname + 3, '/');
 #endif
       if (temp)
     {
       strcpy (filename, ++temp);
       *temp = '\0';
     }
 #if defined (__MSDOS__) || (defined (_WIN32) && !defined (__CYGWIN__))
       /* searches from current directory on the drive */
       else if (ISALPHA ((unsigned char)dirname[0]) && dirname[1] == ':')
         {
           strcpy (filename, dirname + 2);
           dirname[2] = '\0';
         }
 #endif
       else
     {
       dirname[0] = '.';
       dirname[1] = '\0';
     }
       /* We aren't done yet.  We also support the "~user" syntax. */
       /* Save the version of the directory that the user typed, dequoting
      it if necessary. */
       if (rl_completion_found_quote && rl_filename_dequoting_function)
     users_dirname = (*rl_filename_dequoting_function) (dirname, rl_completion_quote_character);
       else
     users_dirname = savestring (dirname);
       tilde_dirname = 0;
       if (*dirname == '~')
     {
       temp = tilde_expand (dirname);
       xfree (dirname);
       dirname = temp;
       tilde_dirname = 1;
     }
       /* We have saved the possibly-dequoted version of the directory name
      the user typed.  Now transform the directory name we're going to
      pass to opendir(2).  The directory rewrite hook modifies only the
      directory name; the directory completion hook modifies both the
      directory name passed to opendir(2) and the version the user
      typed.  Both the directory completion and rewrite hooks should perform
      any necessary dequoting.  The hook functions return 1 if they modify
      the directory name argument.  If either hook returns 0, it should
      not modify the directory name pointer passed as an argument. */
       if (rl_directory_rewrite_hook)
     (*rl_directory_rewrite_hook) (&dirname);
       else if (rl_directory_completion_hook && (*rl_directory_completion_hook) (&dirname))
     {
       xfree (users_dirname);
       users_dirname = savestring (dirname);
     }
       else if (tilde_dirname == 0 && rl_completion_found_quote && rl_filename_dequoting_function)
     {
       /* delete single and double quotes */
       xfree (dirname);
       dirname = savestring (users_dirname);
     }
       directory = opendir (dirname);
       /* Now dequote a non-null filename.  FILENAME will not be NULL, but may
      be empty. */
       if (*filename && rl_completion_found_quote && rl_filename_dequoting_function)
     {
       /* delete single and double quotes */
       temp = (*rl_filename_dequoting_function) (filename, rl_completion_quote_character);
       xfree (filename);
       filename = temp;
     }
       filename_len = strlen (filename);
       rl_filename_completion_desired = 1;
     }
   /* At this point we should entertain the possibility of hacking wildcarded
      filenames, like /usr/man/man<WILD>/te<TAB>.  If the directory name
      contains globbing characters, then build an array of directories, and
      then map over that list while completing. */
   /* *** UNIMPLEMENTED *** */
   /* Now that we have some state, we can read the directory. */
   entry = (struct dirent *)NULL;
   while (directory && (entry = readdir (directory)))
     {
       convfn = dentry = entry->d_name;
       convlen = dentlen = D_NAMLEN (entry);
       if (rl_filename_rewrite_hook)
     {
       convfn = (*rl_filename_rewrite_hook) (dentry, dentlen);
       convlen = (convfn == dentry) ? dentlen : strlen (convfn);
     }
       /* Special case for no filename.  If the user has disabled the
          `match-hidden-files' variable, skip filenames beginning with `.'.
      All other entries except "." and ".." match. */
       if (filename_len == 0)
     {
       if (_rl_match_hidden_files == 0 && HIDDEN_FILE (convfn))
         continue;
       if (convfn[0] != '.' ||
            (convfn[1] && (convfn[1] != '.' || convfn[2])))
         break;
     }
       else
     {
       if (complete_fncmp (convfn, convlen, filename, filename_len))
         break;
     }
     }
   if (entry == 0)
     {
       if (directory)
     {
       closedir (directory);
       directory = (DIR *)NULL;
     }
       if (dirname)
     {
       xfree (dirname);
       dirname = (char *)NULL;
     }
       if (filename)
     {
       xfree (filename);
       filename = (char *)NULL;
     }
       if (users_dirname)
     {
       xfree (users_dirname);
       users_dirname = (char *)NULL;
     }
       return (char *)NULL;
     }
   else
     {
       /* dirname && (strcmp (dirname, ".") != 0) */
       if (dirname && (dirname[0] != '.' || dirname[1]))
     {
       if (rl_complete_with_tilde_expansion && *users_dirname == '~')
         {
           dirlen = strlen (dirname);
           temp = (char *)xmalloc (2 + dirlen + D_NAMLEN (entry));
           strcpy (temp, dirname);
           /* Canonicalization cuts off any final slash present.  We
          may need to add it back. */
           if (dirname[dirlen - 1] != '/')
             {
               temp[dirlen++] = '/';
               temp[dirlen] = '\0';
             }
         }
       else
         {
           dirlen = strlen (users_dirname);
           temp = (char *)xmalloc (2 + dirlen + D_NAMLEN (entry));
           strcpy (temp, users_dirname);
           /* Make sure that temp has a trailing slash here. */
           if (users_dirname[dirlen - 1] != '/')
         temp[dirlen++] = '/';
         }
       strcpy (temp + dirlen, convfn);
     }
       else
     temp = savestring (convfn);
       if (convfn != dentry)
     xfree (convfn);
       return (temp);
     }
 }
Referenced by rl_complete_internal(), rl_completion_matches(), rl_menu_complete(), and rl_old_menu_complete().
rl_forced_update_display()
int rl_forced_update_display (void)
Definition at line 2681 of file display.c.
 {
   register char *temp;
   if (visible_line)
     {
       temp = visible_line;
       while (*temp)
     *temp++ = '\0';
     }
   rl_on_new_line ();
   forced_display++;
   (*rl_redisplay_function) ();
   return 0;
 }
References forced_display, rl_on_new_line(), and visible_line.
Referenced by _rl_redisplay_after_sigwinch(), _rl_ttymsg(), display_matches(), redraw_prompt(), rl_clear_display(), rl_clear_screen(), rl_print_last_kbd_macro(), rl_redraw_prompt_last_line(), and rl_resize_terminal().
rl_forward()
int rl_forward (int count, int key)
Definition at line 386 of file text.c.
 {
   return (rl_forward_char (count, key));
 }
References count, and rl_forward_char().
rl_forward_byte()
int rl_forward_byte (int count, int key)
Definition at line 263 of file text.c.
 {
   if (count < 0)
     return (rl_backward_byte (-count, key));
   if (count > 0)
     {
       int end, lend;
       end = rl_point + count;
 #if defined (VI_MODE)
       lend = rl_end > 0 ? rl_end - (VI_COMMAND_MODE()) : rl_end;
 #else
       lend = rl_end;
 #endif
       if (end > lend)
     {
       rl_point = lend;
       rl_ding ();
     }
       else
     rl_point = end;
     }
   if (rl_end < 0)
     rl_end = 0;
   return 0;
 }
References count, end, rl_backward_byte(), rl_ding(), rl_end, rl_point, and VI_COMMAND_MODE.
Referenced by rl_arrow_keys(), rl_backward_byte(), rl_delete(), and rl_forward_char().
rl_forward_char()
int rl_forward_char (int count, int key)
Definition at line 378 of file text.c.
 {
   return (rl_forward_byte (count, key));
 }
References count, and rl_forward_byte().
Referenced by bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_arrow_keys(), rl_delete(), rl_forward(), rl_next_screen_line(), rl_vi_change_case(), and rl_vi_match().
rl_forward_search_history()
int rl_forward_search_history (int sign, int key)
Definition at line 139 of file isearch.c.
 {
   return (rl_search_history (sign, key));
 }
References rl_search_history().
Referenced by _rl_isearch_dispatch().
rl_forward_word()
int rl_forward_word (int count, int key)
Definition at line 481 of file text.c.
 {
   int c;
   if (count < 0)
     return (rl_backward_word (-count, key));
   while (count)
     {
       if (rl_point > rl_end)
     rl_point = rl_end;
       if (rl_point == rl_end)
     return 0;
       /* If we are not in a word, move forward until we are in one.
      Then, move forward until we hit a non-alphabetic character. */
       c = _rl_char_value (rl_line_buffer, rl_point);
       if (_rl_walphabetic (c) == 0)
     {
       rl_point = MB_NEXTCHAR (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
       while (rl_point < rl_end)
         {
           c = _rl_char_value (rl_line_buffer, rl_point);
           if (_rl_walphabetic (c))
         break;
           rl_point = MB_NEXTCHAR (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
         }
     }
       if (rl_point > rl_end)
     rl_point = rl_end;
       if (rl_point == rl_end)
     return 0;
       rl_point = MB_NEXTCHAR (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
       while (rl_point < rl_end)
     {
       c = _rl_char_value (rl_line_buffer, rl_point);
       if (_rl_walphabetic (c) == 0)
         break;
       rl_point = MB_NEXTCHAR (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
     }
       --count;
     }
   return 0;
 }
References _rl_char_value, _rl_walphabetic, c, count, MB_FIND_NONZERO, MB_NEXTCHAR, rl_backward_word(), rl_end, rl_line_buffer, and rl_point.
Referenced by _rl_copy_word_as_kill(), bind_arrow_keys_internal(), rl_backward_word(), rl_change_case(), rl_kill_word(), and rl_transpose_words().
rl_free()
void rl_free (void * mem)
Definition at line 451 of file util.c.
 {
   if (mem)
     free (mem);
 }
References free, and mem.
rl_free_keymap()
void rl_free_keymap (Keymap map)
Definition at line 170 of file keymaps.c.
 {
   rl_discard_keymap (map);
   xfree ((char *)map);
 }
References map, rl_discard_keymap(), and xfree.
rl_free_line_state()
void rl_free_line_state (void)
Definition at line 590 of file signals.c.
 {
   register HIST_ENTRY *entry;
   rl_free_undo_list ();
   entry = current_history ();
   if (entry)
     entry->data = (char *)NULL;
   _rl_kill_kbd_macro ();
   rl_clear_message ();
   _rl_reset_argument ();
 }
References _rl_kill_kbd_macro(), _rl_reset_argument(), current_history(), entry::data, NULL, rl_clear_message(), and rl_free_undo_list().
Referenced by _rl_handle_signal().
rl_free_undo_list()
void rl_free_undo_list (void)
Definition at line 117 of file undo.c.
 {
   UNDO_LIST *release, *orig_list;
   orig_list = rl_undo_list;
   _rl_free_undo_list (rl_undo_list);
   rl_undo_list = (UNDO_LIST *)NULL;
   _hs_replace_history_data (-1, (histdata_t *)orig_list, (histdata_t *)NULL);
 }
rl_function_dumper()
void rl_function_dumper (int print_readably)
Definition at line 2795 of file bind.c.
 {
   register int i;
   const char **names;
   const char *name;
   names = rl_funmap_names ();
   fprintf (rl_outstream, "\n");
   for (i = 0; name = names[i]; i++)
     {
       rl_command_func_t *function;
       char **invokers;
       function = rl_named_function (name);
       invokers = rl_invoking_keyseqs_in_map (function, _rl_keymap);
       if (print_readably)
     {
       if (!invokers)
         fprintf (rl_outstream, "# %s (not bound)\n", name);
       else
         {
           register int j;
           for (j = 0; invokers[j]; j++)
         {
           fprintf (rl_outstream, "\"%s\": %s\n",
                invokers[j], name);
           xfree (invokers[j]);
         }
           xfree (invokers);
         }
     }
       else
     {
       if (!invokers)
         fprintf (rl_outstream, "%s is not bound to any keys\n",
              name);
       else
         {
           register int j;
           fprintf (rl_outstream, "%s can be found on ", name);
           for (j = 0; invokers[j] && j < 5; j++)
         {
           fprintf (rl_outstream, "\"%s\"%s", invokers[j],
                invokers[j + 1] ? ", " : ".\n");
         }
           if (j == 5 && invokers[j])
         fprintf (rl_outstream, "...\n");
           for (j = 0; invokers[j]; j++)
         xfree (invokers[j]);
           xfree (invokers);
         }
     }
     }
   xfree (names);
 }
References _rl_keymap, fprintf(), i, j, name_and_keymap::name, names, rl_funmap_names(), rl_invoking_keyseqs_in_map(), rl_named_function(), rl_outstream, and xfree.
Referenced by rl_dump_functions().
rl_function_of_keyseq()
rl_command_func_t* rl_function_of_keyseq (const char * keyseq, Keymap map, int * type)
Definition at line 872 of file bind.c.
 {
   return _rl_function_of_keyseq_internal (keyseq, strlen (keyseq), map, type);
 }
References _rl_function_of_keyseq_internal(), map, strlen(), and type.
Referenced by _rl_isearch_dispatch().
rl_function_of_keyseq_len()
rl_command_func_t* rl_function_of_keyseq_len (const char * keyseq, size_t len, Keymap map, int * type)
Definition at line 878 of file bind.c.
 {
   return _rl_function_of_keyseq_internal (keyseq, len, map, type);
 }
References _rl_function_of_keyseq_internal(), map, and type.
Referenced by rl_bind_keyseq_if_unbound_in_map().
rl_funmap_names()
const char** rl_funmap_names (void)
Definition at line 251 of file funmap.c.
 {
   const char **result;
   int result_size, result_index;
   /* Make sure that the function map has been initialized. */
   rl_initialize_funmap ();
   for (result_index = result_size = 0, result = (const char **)NULL; funmap[result_index]; result_index++)
     {
       if (result_index + 2 > result_size)
     {
       result_size += 20;
       result = (const char **)xrealloc (result, result_size * sizeof (char *));
     }
       result[result_index] = funmap[result_index]->name;
       result[result_index + 1] = (char *)NULL;
     }
   qsort (result, result_index, sizeof (char *), (QSFUNC *)_rl_qsort_string_compare);
   return (result);
 }
References _rl_qsort_string_compare(), funmap, _funmap::name, NULL, qsort(), rl_initialize_funmap(), and xrealloc.
Referenced by rl_function_dumper(), and rl_list_funmap_names().
rl_generic_bind()
int rl_generic_bind (int type, const char * keyseq, char * data, Keymap map)
Definition at line 379 of file bind.c.
 {
   char *keys;
   int keys_len, prevkey, ic;
   register int i;
   KEYMAP_ENTRY k;
   Keymap prevmap;
   k.function = 0;
   /* If no keys to bind to, exit right away. */
   if (keyseq == 0 || *keyseq == 0)
     {
       if (type == ISMACR)
     xfree (data);
       return -1;
     }
   keys = (char *)xmalloc (1 + (2 * strlen (keyseq)));
   /* Translate the ASCII representation of KEYSEQ into an array of
      characters.  Stuff the characters into KEYS, and the length of
      KEYS into KEYS_LEN. */
   if (rl_translate_keyseq (keyseq, keys, &keys_len))
     {
       xfree (keys);
       return -1;
     }
   prevmap = map;
   prevkey = keys[0];
   /* Bind keys, making new keymaps as necessary. */
   for (i = 0; i < keys_len; i++)
     {
       unsigned char uc = keys[i];
       if (i > 0)
     prevkey = ic;
       ic = uc;
       if (ic < 0 || ic >= KEYMAP_SIZE)
         {
           xfree (keys);
       return -1;
         }
       /* We now rely on rl_translate_keyseq to do this conversion, so this
      check is superfluous. */
 #if 0
       if (META_CHAR (ic) && _rl_convert_meta_chars_to_ascii)
     {
       ic = UNMETA (ic);
       if (map[ESC].type == ISKMAP)
         {
           prevmap = map;
           map = FUNCTION_TO_KEYMAP (map, ESC);
         }
     }
 #endif
       if ((i + 1) < keys_len)
     {
       if (map[ic].type != ISKMAP)
         {
           /* We allow subsequences of keys.  If a keymap is being
          created that will `shadow' an existing function or macro
          key binding, we save that keybinding into the ANYOTHERKEY
          index in the new map.  The dispatch code will look there
          to find the function to execute if the subsequence is not
          matched.  ANYOTHERKEY was chosen to be greater than
          UCHAR_MAX. */
           k = map[ic];
           map[ic].type = ISKMAP;
           map[ic].function = KEYMAP_TO_FUNCTION (rl_make_bare_keymap());
         }
       prevmap = map;
       map = FUNCTION_TO_KEYMAP (map, ic);
       /* The dispatch code will return this function if no matching
          key sequence is found in the keymap.  This (with a little
          help from the dispatch code in readline.c) allows `a' to be
          mapped to something, `abc' to be mapped to something else,
          and the function bound  to `a' to be executed when the user
          types `abx', leaving `bx' in the input queue. */
       if (k.function && ((k.type == ISFUNC && k.function != rl_do_lowercase_version) || k.type == ISMACR))
         {
           map[ANYOTHERKEY] = k;
           k.function = 0;
         }
     }
       else
     {
       if (map[ic].type == ISKMAP)
         {
           prevmap = map;
           map = FUNCTION_TO_KEYMAP (map, ic);
           ic = ANYOTHERKEY;
           /* If we're trying to override a keymap with a null function
          (e.g., trying to unbind it), we can't use a null pointer
          here because that's indistinguishable from having not been
          overridden.  We use a special bindable function that does
          nothing. */
           if (type == ISFUNC && data == 0)
         data = (char *)_rl_null_function;
         }
       if (map[ic].type == ISMACR)
         xfree ((char *)map[ic].function);
       map[ic].function = KEYMAP_TO_FUNCTION (data);
       map[ic].type = type;
     }
       rl_binding_keymap = map;
     }
   /* If we unbound a key (type == ISFUNC, data == 0), and the prev keymap
      points to the keymap where we unbound the key (sanity check), and the
      current binding keymap is empty (rl_empty_keymap() returns non-zero),
      and the binding keymap has ANYOTHERKEY set with type == ISFUNC
      (overridden function), delete the now-empty keymap, take the previously-
      overridden function and remove the override. */
   /* Right now, this only works one level back. */
   if (type == ISFUNC && data == 0 &&
       prevmap[prevkey].type == ISKMAP &&
       (FUNCTION_TO_KEYMAP(prevmap, prevkey) == rl_binding_keymap) &&
       rl_binding_keymap[ANYOTHERKEY].type == ISFUNC &&
       rl_empty_keymap (rl_binding_keymap))
     {
       prevmap[prevkey].type = rl_binding_keymap[ANYOTHERKEY].type;
       prevmap[prevkey].function = rl_binding_keymap[ANYOTHERKEY].function;
       rl_discard_keymap (rl_binding_keymap);
       rl_binding_keymap = prevmap;
     }
   xfree (keys);
   return 0;
 }
References _rl_convert_meta_chars_to_ascii, _rl_null_function(), ANYOTHERKEY, ESC, _keymap_entry::function, FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, ISMACR, k, KEYMAP_SIZE, KEYMAP_TO_FUNCTION, keys, map, META_CHAR, rl_binding_keymap, rl_discard_keymap(), rl_do_lowercase_version(), rl_empty_keymap(), rl_make_bare_keymap(), rl_translate_keyseq(), strlen(), _keymap_entry::type, type, UNMETA, xfree, and xmalloc.
Referenced by rl_bind_keyseq(), rl_bind_keyseq_in_map(), rl_macro_bind(), rl_parse_and_bind(), and rl_set_key().
rl_get_keymap()
Keymap rl_get_keymap (void)
Definition at line 2534 of file bind.c.
 {
   return (_rl_keymap);
 }
References _rl_keymap.
rl_get_keymap_by_name()
Keymap rl_get_keymap_by_name (const char * name)
Definition at line 2448 of file bind.c.
 {
   int i;
   i = _rl_get_keymap_by_name (name);
   return ((i >= 0) ? keymap_names[i].map : (Keymap) NULL);
 }
References _rl_get_keymap_by_name(), i, keymap_names, map, name_and_keymap::name, and NULL.
Referenced by sv_keymap().
rl_get_keymap_name()
char* rl_get_keymap_name (Keymap map)
Definition at line 2468 of file bind.c.
 {
   int i;
   i = _rl_get_keymap_by_map (map);
   return ((i >= 0) ? keymap_names[i].name : (char *)NULL);
 }
References _rl_get_keymap_by_map(), i, keymap_names, map, name_and_keymap::name, and NULL.
Referenced by _rl_get_string_variable_value().
rl_get_keymap_name_from_edit_mode()
char* rl_get_keymap_name_from_edit_mode (void)
Definition at line 2551 of file bind.c.
 {
   if (rl_editing_mode == emacs_mode)
     return "emacs";
 #if defined (VI_MODE)
   else if (rl_editing_mode == vi_mode)
     return "vi";
 #endif /* VI_MODE */
   else
     return "none";
 }
References emacs_mode, rl_editing_mode, and vi_mode.
Referenced by _rl_get_string_variable_value().
rl_get_next_history()
int rl_get_next_history (int count, int key)
Definition at line 559 of file misc.c.
 {
   HIST_ENTRY *temp;
   if (count < 0)
     return (rl_get_previous_history (-count, key));
   if (count == 0)
     return 0;
   rl_maybe_replace_line ();
   /* either not saved by rl_newline or at end of line, so set appropriately. */
   if (_rl_history_saved_point == -1 && (rl_point || rl_end))
     _rl_history_saved_point = (rl_point == rl_end) ? -1 : rl_point;
   temp = (HIST_ENTRY *)NULL;
   while (count)
     {
       temp = next_history ();
       if (!temp)
     break;
       --count;
     }
   if (temp == 0)
     rl_maybe_unsave_line ();
   else
     {
       rl_replace_from_history (temp, 0);
       _rl_history_set_point ();
     }
   return 0;
 }
References _rl_history_saved_point, _rl_history_set_point(), count, next_history(), NULL, rl_end, rl_get_previous_history(), rl_maybe_replace_line(), rl_maybe_unsave_line(), rl_point, and rl_replace_from_history().
Referenced by _rl_isearch_fini(), bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_arrow_keys(), rl_get_previous_history(), rl_history_search_forward(), and rl_history_substr_search_forward().
rl_get_previous_history()
int rl_get_previous_history (int count, int key)
Definition at line 597 of file misc.c.
 {
   HIST_ENTRY *old_temp, *temp;
   int had_saved_line;
   if (count < 0)
     return (rl_get_next_history (-count, key));
   if (count == 0 || history_list () == 0)
     return 0;
   /* either not saved by rl_newline or at end of line, so set appropriately. */
   if (_rl_history_saved_point == -1 && (rl_point || rl_end))
     _rl_history_saved_point = (rl_point == rl_end) ? -1 : rl_point;
   /* If we don't have a line saved, then save this one. */
   had_saved_line = _rl_saved_line_for_history != 0;
   rl_maybe_save_line ();
   /* If the current line has changed, save the changes. */
   rl_maybe_replace_line ();
   temp = old_temp = (HIST_ENTRY *)NULL;
   while (count)
     {
       temp = previous_history ();
       if (temp == 0)
     break;
       old_temp = temp;
       --count;
     }
   /* If there was a large argument, and we moved back to the start of the
      history, that is not an error.  So use the last value found. */
   if (!temp && old_temp)
     temp = old_temp;
   if (temp == 0)
     {
       if (had_saved_line == 0)
     _rl_free_saved_history_line ();
       rl_ding ();
     }
   else
     {
       rl_replace_from_history (temp, 0);
       _rl_history_set_point ();
     }
   return 0;
 }
References _rl_free_saved_history_line(), _rl_history_saved_point, _rl_history_set_point(), _rl_saved_line_for_history, count, history_list(), NULL, previous_history(), rl_ding(), rl_end, rl_get_next_history(), rl_maybe_replace_line(), rl_maybe_save_line(), rl_point, and rl_replace_from_history().
Referenced by _rl_isearch_fini(), bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_arrow_keys(), rl_beginning_of_history(), rl_fetch_history(), rl_get_next_history(), rl_history_search_backward(), rl_history_substr_search_backward(), and set_saved_history().
rl_get_screen_size()
void rl_get_screen_size (int * rows, int * cols)
Definition at line 371 of file terminal.c.
 {
   if (rows)
     *rows = _rl_screenheight;
   if (cols)
     *cols = _rl_screenwidth;
 }
References _rl_screenheight, _rl_screenwidth, cols, and rows.
rl_get_termcap()
char* rl_get_termcap (const char * cap)
Definition at line 669 of file terminal.c.
 {
   register int i;
   if (tcap_initialized == 0)
     return ((char *)NULL);
   for (i = 0; i < NUM_TC_STRINGS; i++)
     {
       if (tc_strings[i].tc_var[0] == cap[0] && strcmp (tc_strings[i].tc_var, cap) == 0)
         return *(tc_strings[i].tc_value);
     }
   return ((char *)NULL);
 }
References i, NULL, NUM_TC_STRINGS, strcmp, tc_strings, _tc_string::tc_value, _tc_string::tc_var, and tcap_initialized.
rl_getc()
int rl_getc (FILE * stream)
Definition at line 803 of file input.c.
 {
   int result;
   unsigned char c;
   int fd;
 #if defined (HAVE_PSELECT)
   sigset_t empty_set;
   fd_set readfds;
 #endif
   fd = fileno (stream);
   while (1)
     {
       RL_CHECK_SIGNALS ();
       /* We know at this point that _rl_caught_signal == 0 */
 #if defined (__MINGW32__)
       if (isatty (fd)
     return (_getch ()); /* "There is no error return." */
 #endif
       result = 0;
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
       /* At this point, if we have pselect, we're using select/pselect for the
      timeouts. We handled MinGW above. */
       FD_ZERO (&readfds);
       FD_SET (fd, &readfds);
 #  if defined (HANDLE_SIGNALS)
       result = _rl_timeout_select (fd + 1, &readfds, NULL, NULL, NULL, &_rl_orig_sigset);
 #  else
       sigemptyset (&empty_set);
       sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &empty_set);
       result = _rl_timeout_select (fd + 1, &readfds, NULL, NULL, NULL, &empty_set);
 #  endif /* HANDLE_SIGNALS */
       if (result == 0)
         _rl_timeout_handle ();      /* check the timeout */
 #endif
       if (result >= 0)
     result = read (fd, &c, sizeof (unsigned char));
       if (result == sizeof (unsigned char))
     return (c);
       /* If zero characters are returned, then the file that we are
      reading from is empty!  Return EOF in that case. */
       if (result == 0)
     return (EOF);
 #if defined (__BEOS__)
       if (errno == EINTR)
     continue;
 #endif
 #if defined (EWOULDBLOCK)
 #  define X_EWOULDBLOCK EWOULDBLOCK
 #else
 #  define X_EWOULDBLOCK -99
 #endif
 #if defined (EAGAIN)
 #  define X_EAGAIN EAGAIN
 #else
 #  define X_EAGAIN -99
 #endif
       if (errno == X_EWOULDBLOCK || errno == X_EAGAIN)
     {
       if (sh_unset_nodelay_mode (fd) < 0)
         return (EOF);
       continue;
     }
 #undef X_EWOULDBLOCK
 #undef X_EAGAIN
 /* fprintf(stderr, "rl_getc: result = %d errno = %d\n", result, errno); */
 handle_error:
       /* If the error that we received was EINTR, then try again,
      this is simply an interrupted system call to read ().  We allow
      the read to be interrupted if we caught SIGHUP, SIGTERM, or any
      of the other signals readline treats specially. If the
      application sets an event hook, call it for other signals.
      Otherwise (not EINTR), some error occurred, also signifying EOF. */
       if (errno != EINTR)
     return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
       /* fatal signals of interest */
 #if defined (SIGHUP)
       else if (_rl_caught_signal == SIGHUP || _rl_caught_signal == SIGTERM)
 #else
       else if (_rl_caught_signal == SIGTERM)
 #endif
     return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
       /* keyboard-generated signals of interest */
 #if defined (SIGQUIT)
       else if (_rl_caught_signal == SIGINT || _rl_caught_signal == SIGQUIT)
 #else
       else if (_rl_caught_signal == SIGINT)
 #endif
         RL_CHECK_SIGNALS ();
 #if defined (SIGTSTP)
       else if (_rl_caught_signal == SIGTSTP)
     RL_CHECK_SIGNALS ();
 #endif
       /* non-keyboard-generated signals of interest */
 #if defined (SIGWINCH)
       else if (_rl_caught_signal == SIGWINCH)
     RL_CHECK_SIGNALS ();
 #endif /* SIGWINCH */
 #if defined (SIGALRM)
       else if (_rl_caught_signal == SIGALRM
 #  if defined (SIGVTALRM)
         || _rl_caught_signal == SIGVTALRM
 #  endif
           )
         RL_CHECK_SIGNALS ();
 #endif  /* SIGALRM */
       if (rl_signal_event_hook)
     (*rl_signal_event_hook) ();
     }
 }
References _rl_caught_signal, _rl_timeout_handle(), _rl_timeout_select(), c, EINTR, EOF, errno, fd, FD_SET, FD_ZERO, fileno(), isatty(), NULL, read(), READERR, RL_CHECK_SIGNALS, RL_ISSTATE, rl_signal_event_hook, RL_STATE_READCMD, sh_unset_nodelay_mode(), SIG_BLOCK, SIGALRM, sigemptyset(), SIGHUP, SIGINT, sigprocmask(), SIGQUIT, SIGTERM, SIGTSTP, SIGVTALRM, SIGWINCH, X_EAGAIN, and X_EWOULDBLOCK.
rl_history_search_backward()
int rl_history_search_backward (int count, int ignore)
Definition at line 658 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_search_forward &&
       rl_last_func != rl_history_search_backward)
     rl_history_search_reinit (ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_previous_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? -1 : 1));
 }
References _rl_history_search_len, abs, ANCHORED_SEARCH, count, ignore(), rl_get_previous_history(), rl_history_search_backward(), rl_history_search_forward(), rl_history_search_internal(), rl_history_search_reinit(), and rl_last_func.
Referenced by bind_termcap_arrow_keys(), rl_history_search_backward(), and rl_history_search_forward().
rl_history_search_forward()
int rl_history_search_forward (int count, int ignore)
Definition at line 640 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_search_forward &&
       rl_last_func != rl_history_search_backward)
     rl_history_search_reinit (ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_next_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? 1 : -1));
 }
References _rl_history_search_len, abs, ANCHORED_SEARCH, count, ignore(), rl_get_next_history(), rl_history_search_backward(), rl_history_search_forward(), rl_history_search_internal(), rl_history_search_reinit(), and rl_last_func.
Referenced by bind_termcap_arrow_keys(), rl_history_search_backward(), and rl_history_search_forward().
rl_history_substr_search_backward()
int rl_history_substr_search_backward (int count, int ignore)
Definition at line 695 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_substr_search_forward &&
       rl_last_func != rl_history_substr_search_backward)
     rl_history_search_reinit (NON_ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_previous_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? -1 : 1));
 }
References _rl_history_search_len, abs, count, ignore(), NON_ANCHORED_SEARCH, rl_get_previous_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_history_substr_search_backward(), rl_history_substr_search_forward(), and rl_last_func.
Referenced by rl_history_substr_search_backward(), and rl_history_substr_search_forward().
rl_history_substr_search_forward()
int rl_history_substr_search_forward (int count, int ignore)
Definition at line 677 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_substr_search_forward &&
       rl_last_func != rl_history_substr_search_backward)
     rl_history_search_reinit (NON_ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_next_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? 1 : -1));
 }
References _rl_history_search_len, abs, count, ignore(), NON_ANCHORED_SEARCH, rl_get_next_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_history_substr_search_backward(), rl_history_substr_search_forward(), and rl_last_func.
Referenced by rl_history_substr_search_backward(), and rl_history_substr_search_forward().
rl_initialize()
int rl_initialize (void)
Definition at line 1173 of file readline.c.
 {
   /* Initialize the timeout first to get the precise start time. */
   _rl_timeout_init ();
   /* If we have never been called before, initialize the
      terminal and data structures. */
   if (rl_initialized == 0)
     {
       RL_SETSTATE(RL_STATE_INITIALIZING);
       readline_initialize_everything ();
       RL_UNSETSTATE(RL_STATE_INITIALIZING);
       rl_initialized++;
       RL_SETSTATE(RL_STATE_INITIALIZED);
     }
   else
     _rl_reset_locale ();    /* check current locale and set locale variables */
   /* Initialize the current line information. */
   _rl_init_line_state ();
   /* We aren't done yet.  We haven't even gotten started yet! */
   rl_done = 0;
   RL_UNSETSTATE(RL_STATE_DONE|RL_STATE_TIMEOUT|RL_STATE_EOF);
   /* Tell the history routines what is going on. */
   _rl_start_using_history ();
   /* Make the display buffer match the state of the line. */
   rl_reset_line_state ();
   /* No such function typed yet. */
   rl_last_func = (rl_command_func_t *)NULL;
   /* Parsing of key-bindings begins in an enabled state. */
   _rl_parsing_conditionalized_out = 0;
 #if defined (VI_MODE)
   if (rl_editing_mode == vi_mode)
     _rl_vi_initialize_line ();
 #endif
   /* Each line starts in insert mode (the default). */
   _rl_set_insert_mode (RL_IM_DEFAULT, 1);
   return 0;
 }
References _rl_init_line_state(), _rl_parsing_conditionalized_out, _rl_reset_locale(), _rl_set_insert_mode(), _rl_start_using_history(), _rl_timeout_init(), _rl_vi_initialize_line(), NULL, readline_initialize_everything(), rl_done, rl_editing_mode, RL_IM_DEFAULT, rl_initialized, rl_last_func, rl_reset_line_state(), RL_SETSTATE, RL_STATE_DONE, RL_STATE_EOF, RL_STATE_INITIALIZED, RL_STATE_INITIALIZING, RL_STATE_TIMEOUT, RL_UNSETSTATE, and vi_mode.
Referenced by _rl_callback_newline(), and readline().
rl_initialize_funmap()
void rl_initialize_funmap (void)
Definition at line 233 of file funmap.c.
 {
   register int i;
   if (funmap_initialized)
     return;
   for (i = 0; default_funmap[i].name; i++)
     rl_add_funmap_entry (default_funmap[i].name, default_funmap[i].function);
   funmap_initialized = 1;
   funmap_program_specific_entry_start = i;
 }
References default_funmap, funmap_initialized, funmap_program_specific_entry_start, i, _funmap::name, and rl_add_funmap_entry().
Referenced by readline_initialize_everything(), rl_funmap_names(), and rl_named_function().
rl_insert()
int rl_insert (int count, int c)
Definition at line 951 of file text.c.
 {
   int r, n, x;
   r = (rl_insert_mode == RL_IM_INSERT) ? _rl_insert_char (count, c) : _rl_overwrite_char (count, c);
   /* XXX -- attempt to batch-insert pending input that maps to self-insert */
   x = 0;
   n = (unsigned short)-2;
   while (_rl_optimize_typeahead &&
      rl_num_chars_to_read == 0 &&
      (RL_ISSTATE (RL_STATE_INPUTPENDING|RL_STATE_MACROINPUT) == 0) &&
      _rl_pushed_input_available () == 0 &&
      _rl_input_queued (0) &&
      (n = rl_read_key ()) > 0 &&
      _rl_keymap[(unsigned char)n].type == ISFUNC &&
      _rl_keymap[(unsigned char)n].function == rl_insert)
     {
       r = (rl_insert_mode == RL_IM_INSERT) ? _rl_insert_char (1, n) : _rl_overwrite_char (1, n);
       /* _rl_insert_char keeps its own set of pending characters to compose a
      complete multibyte character, and only returns 1 if it sees a character
      that's part of a multibyte character but too short to complete one.  We
      can try to read another character in the hopes that we will get the
      next one or just punt.  Right now we try to read another character.
      We don't want to call rl_insert_next if _rl_insert_char has already
      stored the character in the pending_bytes array because that will
      result in doubled input. */
       n = (unsigned short)-2;
       x++;      /* count of bytes of typeahead read, currently unused */
       if (r == 1)   /* read partial multibyte character */
     continue;
       if (rl_done || r != 0)
     break;
     }
   if (n != (unsigned short)-2)      /* -2 = sentinel value for having inserted N */
     {
       /* setting rl_pending_input inhibits setting rl_last_func so we do it
      ourselves here */
       rl_last_func = rl_insert;
       _rl_reset_argument ();
       rl_executing_keyseq[rl_key_sequence_length = 0] = '\0';
       r = rl_execute_next (n);
     }
   return r;
 }
References _rl_input_queued(), _rl_insert_char(), _rl_keymap, _rl_optimize_typeahead, _rl_overwrite_char(), _rl_pushed_input_available(), _rl_reset_argument(), c, count, ISFUNC, n, rl_done, rl_execute_next(), rl_executing_keyseq, RL_IM_INSERT, rl_insert(), rl_insert_mode, RL_ISSTATE, rl_key_sequence_length, rl_last_func, rl_num_chars_to_read, rl_read_key(), RL_STATE_INPUTPENDING, RL_STATE_MACROINPUT, _keymap_entry::type, and x.
Referenced by _rl_enable_paren_matching(), _rl_insert_typein(), _rl_isearch_dispatch(), rl_insert(), and rl_make_keymap().
rl_insert_close()
int rl_insert_close (int count, int invoking_key)
Definition at line 111 of file parens.c.
 {
   if (rl_explicit_arg || !rl_blink_matching_paren)
     _rl_insert_char (count, invoking_key);
   else
     {
 #if defined (HAVE_SELECT)
       int orig_point, match_point, ready;
       struct timeval timer;
       fd_set readfds;
       _rl_insert_char (1, invoking_key);
       (*rl_redisplay_function) ();
       match_point =
     find_matching_open (rl_line_buffer, rl_point - 2, invoking_key);
       /* Emacs might message or ring the bell here, but I don't. */
       if (match_point < 0)
     return 1;
       FD_ZERO (&readfds);
       FD_SET (fileno (rl_instream), &readfds);
       USEC_TO_TIMEVAL (_paren_blink_usec, timer);
       orig_point = rl_point;
       rl_point = match_point;
       (*rl_redisplay_function) ();
 #  if defined (RL_TIMEOUT_USE_SELECT)
       ready = _rl_timeout_select (1, &readfds, (fd_set *)NULL, (fd_set *)NULL, &timer, NULL);
 #  else
       ready = select (1, &readfds, (fd_set *)NULL, (fd_set *)NULL, &timer);
 #  endif
       rl_point = orig_point;
 #else /* !HAVE_SELECT */
       _rl_insert_char (count, invoking_key);
 #endif /* !HAVE_SELECT */
     }
   return 0;
 }
References _paren_blink_usec, _rl_insert_char(), _rl_timeout_select(), count, FD_SET, FD_ZERO, fileno(), find_matching_open(), NULL, rl_blink_matching_paren, rl_explicit_arg, rl_instream, rl_line_buffer, rl_point, select(), and USEC_TO_TIMEVAL.
Referenced by _rl_enable_paren_matching().
rl_insert_comment()
int rl_insert_comment (int count, int key)
Definition at line 1341 of file text.c.
 {
   char *rl_comment_text;
   int rl_comment_len;
   rl_beg_of_line (1, key);
   rl_comment_text = _rl_comment_begin ? _rl_comment_begin : RL_COMMENT_BEGIN_DEFAULT;
   if (rl_explicit_arg == 0)
     rl_insert_text (rl_comment_text);
   else
     {
       rl_comment_len = strlen (rl_comment_text);
       if (STREQN (rl_comment_text, rl_line_buffer, rl_comment_len))
     rl_delete_text (rl_point, rl_point + rl_comment_len);
       else
     rl_insert_text (rl_comment_text);
     }
   (*rl_redisplay_function) ();
   rl_newline (1, '\n');
   return (0);
 }
References _rl_comment_begin, rl_beg_of_line(), RL_COMMENT_BEGIN_DEFAULT, rl_delete_text(), rl_explicit_arg, rl_insert_text(), rl_line_buffer, rl_newline(), rl_point, STREQN, and strlen().
rl_insert_completions()
int rl_insert_completions (int ignore, int invoking_key)
Definition at line 463 of file complete.c.
 {
   rl_completion_invoking_key = invoking_key;
   return (rl_complete_internal ('*'));
 }
References rl_complete_internal(), and rl_completion_invoking_key.
rl_insert_text()
int rl_insert_text (const char * string)
Definition at line 86 of file text.c.
 {
   register int i, l;
   l = (string && *string) ? strlen (string) : 0;
   if (l == 0)
     return 0;
   if (rl_end + l >= rl_line_buffer_len)
     rl_extend_line_buffer (rl_end + l);
   for (i = rl_end; i >= rl_point; i--)
     rl_line_buffer[i + l] = rl_line_buffer[i];
   strncpy (rl_line_buffer + rl_point, string, l);
   /* Remember how to undo this if we aren't undoing something. */
   if (_rl_doing_an_undo == 0)
     {
       /* If possible and desirable, concatenate the undos. */
       if ((l == 1) &&
       rl_undo_list &&
       (rl_undo_list->what == UNDO_INSERT) &&
       (rl_undo_list->end == rl_point) &&
       (rl_undo_list->end - rl_undo_list->start < 20))
     rl_undo_list->end++;
       else
     rl_add_undo (UNDO_INSERT, rl_point, rl_point + l, (char *)NULL);
     }
   rl_point += l;
   rl_end += l;
   rl_line_buffer[rl_end] = '\0';
   return l;
 }
References _rl_doing_an_undo, undo_list::end, i, l, NULL, rl_add_undo(), rl_end, rl_extend_line_buffer(), rl_line_buffer, rl_line_buffer_len, rl_point, rl_undo_list, undo_list::start, string, strlen(), strncpy(), UNDO_INSERT, and undo_list::what.
Referenced by _rl_insert_char(), _rl_insert_typein(), _rl_nsearch_dispatch(), _rl_overwrite_char(), _rl_replace_text(), _rl_vi_change_char(), _rl_vi_stuff_insert(), append_to_match(), change_prompt(), insert_all_matches(), rl_bracketed_paste_begin(), rl_do_undo(), rl_insert_comment(), rl_transpose_chars(), rl_transpose_words(), rl_yank(), rl_yank_nth_arg_internal(), set_deftext(), and vi_change_dispatch().
rl_invoking_keyseqs()
char** rl_invoking_keyseqs (rl_command_func_t * function)
Definition at line 2786 of file bind.c.
 {
   return (rl_invoking_keyseqs_in_map (function, _rl_keymap));
 }
References _rl_keymap, and rl_invoking_keyseqs_in_map().
rl_invoking_keyseqs_in_map()
char** rl_invoking_keyseqs_in_map (rl_command_func_t * function, Keymap map)
Definition at line 2677 of file bind.c.
 {
   register int key;
   char **result;
   int result_index, result_size;
   result = (char **)NULL;
   result_index = result_size = 0;
   for (key = 0; key < KEYMAP_SIZE; key++)
     {
       switch (map[key].type)
     {
     case ISMACR:
       /* Macros match, if, and only if, the pointers are identical.
          Thus, they are treated exactly like functions in here. */
     case ISFUNC:
       /* If the function in the keymap is the one we are looking for,
          then add the current KEY to the list of invoking keys. */
       if (map[key].function == function)
         {
           char *keyname;
           keyname = _rl_get_keyname (key);
           if (result_index + 2 > result_size)
             {
               result_size += 10;
           result = (char **)xrealloc (result, result_size * sizeof (char *));
             }
           result[result_index++] = keyname;
           result[result_index] = (char *)NULL;
         }
       break;
     case ISKMAP:
       {
         char **seqs;
         register int i;
         /* Find the list of keyseqs in this map which have FUNCTION as
            their target.  Add the key sequences found to RESULT. */
         if (map[key].function)
           seqs =
             rl_invoking_keyseqs_in_map (function, FUNCTION_TO_KEYMAP (map, key));
         else
           break;
         if (seqs == 0)
           break;
         for (i = 0; seqs[i]; i++)
           {
         char *keyname = (char *)xmalloc (6 + strlen (seqs[i]));
         if (key == ESC)
           {
             /* If ESC is the meta prefix and we're converting chars
                with the eighth bit set to ESC-prefixed sequences, then
                we can use \M-.  Otherwise we need to use the sequence
                for ESC. */
             if (_rl_convert_meta_chars_to_ascii && map[ESC].type == ISKMAP)
               sprintf (keyname, "\\M-");
             else
               sprintf (keyname, "\\e");
           }
         else
           {
             int c = key, l = 0;
             if (CTRL_CHAR (c) || c == RUBOUT)
               {
             keyname[l++] = '\\';
             keyname[l++] = 'C';
             keyname[l++] = '-';
             c = (c == RUBOUT) ? '?' : _rl_to_lower (UNCTRL (c));
               }
             if (c == '\\' || c == '"')
               keyname[l++] = '\\';
             keyname[l++] = (char) c;
             keyname[l++] = '\0';
           }
         strcat (keyname, seqs[i]);
         xfree (seqs[i]);
         if (result_index + 2 > result_size)
           {
             result_size += 10;
             result = (char **)xrealloc (result, result_size * sizeof (char *));
           }
         result[result_index++] = keyname;
         result[result_index] = (char *)NULL;
           }
         xfree (seqs);
       }
       break;
     }
     }
   return (result);
 }
References _rl_convert_meta_chars_to_ascii, _rl_get_keyname(), _rl_to_lower(), c, CTRL_CHAR, ESC, FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, ISMACR, KEYMAP_SIZE, l, map, NULL, RUBOUT, sprintf(), strcat(), strlen(), type, UNCTRL, xfree, xmalloc, and xrealloc.
Referenced by rl_function_dumper(), and rl_invoking_keyseqs().
rl_keep_mark_active()
void rl_keep_mark_active (void)
Definition at line 1866 of file text.c.
 {
   _rl_keep_mark_active++;
 }
References _rl_keep_mark_active.
Referenced by _rl_refresh_line(), rl_activate_mark(), and rl_clear_screen().
rl_kill_full_line()
int rl_kill_full_line (int count, int key)
Definition at line 290 of file kill.c.
 {
   rl_begin_undo_group ();
   rl_point = 0;
   rl_kill_text (rl_point, rl_end);
   rl_mark = 0;
   rl_end_undo_group ();
   return 0;
 }
References rl_begin_undo_group(), rl_end, rl_end_undo_group(), rl_kill_text(), rl_mark, and rl_point.
rl_kill_line()
int rl_kill_line (int direction, int key)
Definition at line 243 of file kill.c.
 {
   int orig_point;
   if (direction < 0)
     return (rl_backward_kill_line (1, key));
   else
     {
       orig_point = rl_point;
       rl_end_of_line (1, key);
       if (orig_point != rl_point)
     rl_kill_text (orig_point, rl_point);
       rl_point = orig_point;
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References emacs_mode, rl_backward_kill_line(), rl_editing_mode, rl_end_of_line(), rl_kill_text(), rl_mark, and rl_point.
Referenced by rl_backward_kill_line().
rl_kill_region()
int rl_kill_region (int count, int key)
Definition at line 449 of file kill.c.
 {
   int r, npoint;
   npoint = (rl_point < rl_mark) ? rl_point : rl_mark;
   r = region_kill_internal (1);
   rl_point = npoint;
   _rl_fix_point (1);
   return r;
 }
References _rl_fix_point(), region_kill_internal(), rl_mark, and rl_point.
rl_kill_text()
int rl_kill_text (int from, int to)
Definition at line 163 of file kill.c.
 {
   char *text;
   /* Is there anything to kill? */
   if (from == to)
     {
       _rl_last_command_was_kill++;
       return 0;
     }
   text = rl_copy_text (from, to);
   /* Delete the copied text from the line. */
   rl_delete_text (from, to);
   _rl_copy_to_kill_ring (text, from < to);
   _rl_last_command_was_kill++;
   return 0;
 }
References _rl_copy_to_kill_ring(), _rl_last_command_was_kill, rl_copy_text(), rl_delete_text(), and text.
Referenced by _rl_overwrite_rubout(), _rl_rubout_char(), rl_backward_kill_line(), rl_backward_kill_word(), rl_delete(), rl_kill_full_line(), rl_kill_line(), rl_kill_word(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_delete(), rl_vi_rubout(), rl_vi_unix_word_rubout(), vi_change_dispatch(), vi_delete_dispatch(), and vi_yank_dispatch().
rl_kill_word()
int rl_kill_word (int count, int key)
Definition at line 197 of file kill.c.
 {
   int orig_point;
   if (count < 0)
     return (rl_backward_kill_word (-count, key));
   else
     {
       orig_point = rl_point;
       rl_forward_word (count, key);
       if (rl_point != orig_point)
     rl_kill_text (orig_point, rl_point);
       rl_point = orig_point;
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References count, emacs_mode, rl_backward_kill_word(), rl_editing_mode, rl_forward_word(), rl_kill_text(), rl_mark, and rl_point.
Referenced by bind_arrow_keys_internal(), and rl_backward_kill_word().
rl_list_funmap_names()
void rl_list_funmap_names (void)
Definition at line 2576 of file bind.c.
 {
   register int i;
   const char **funmap_names;
   funmap_names = rl_funmap_names ();
   if (!funmap_names)
     return;
   for (i = 0; funmap_names[i]; i++)
     fprintf (rl_outstream, "%s\n", funmap_names[i]);
   xfree (funmap_names);
 }
References fprintf(), i, rl_funmap_names(), rl_outstream, and xfree.
rl_macro_bind()
int rl_macro_bind (const char * keyseq, const char * macro, Keymap map)
Definition at line 357 of file bind.c.
 {
   char *macro_keys;
   int macro_keys_len;
   macro_keys = (char *)xmalloc ((2 * strlen (macro)) + 1);
   if (rl_translate_keyseq (macro, macro_keys, &macro_keys_len))
     {
       xfree (macro_keys);
       return -1;
     }
   rl_generic_bind (ISMACR, keyseq, macro_keys, map);
   return 0;
 }
References ISMACR, map, rl_generic_bind(), rl_translate_keyseq(), strlen(), xfree, and xmalloc.
Referenced by rl_parse_and_bind().
rl_macro_dumper()
void rl_macro_dumper (int print_readably)
Definition at line 2935 of file bind.c.
 {
   _rl_macro_dumper_internal (print_readably, _rl_keymap, (char *)NULL);
 }
References _rl_keymap, _rl_macro_dumper_internal(), and NULL.
Referenced by rl_dump_macros().
rl_make_bare_keymap()
Keymap rl_make_bare_keymap (void)
Definition at line 57 of file keymaps.c.
 {
   register int i;
   Keymap keymap;
   keymap = (Keymap)xmalloc (KEYMAP_SIZE * sizeof (KEYMAP_ENTRY));
   for (i = 0; i < KEYMAP_SIZE; i++)
     {
       keymap[i].type = ISFUNC;
       keymap[i].function = (rl_command_func_t *)NULL;
     }
 #if 0
   for (i = 'A'; i < ('Z' + 1); i++)
     {
       keymap[i].type = ISFUNC;
       keymap[i].function = rl_do_lowercase_version;
     }
 #endif
   return (keymap);
 }
References _keymap_entry::function, i, ISFUNC, KEYMAP_SIZE, NULL, rl_do_lowercase_version(), _keymap_entry::type, and xmalloc.
Referenced by rl_copy_keymap(), rl_generic_bind(), rl_make_keymap(), and rl_vi_replace().
rl_make_keymap()
Keymap rl_make_keymap (void)
Definition at line 116 of file keymaps.c.
 {
   register int i;
   Keymap newmap;
   newmap = rl_make_bare_keymap ();
   /* All ASCII printing characters are self-inserting. */
   for (i = ' '; i < 127; i++)
     newmap[i].function = rl_insert;
   newmap[TAB].function = rl_insert;
   newmap[RUBOUT].function = rl_rubout;  /* RUBOUT == 127 */
   newmap[CTRL('H')].function = rl_rubout;
 #if KEYMAP_SIZE > 128
   /* Printing characters in ISO Latin-1 and some 8-bit character sets. */
   for (i = 128; i < 256; i++)
     newmap[i].function = rl_insert;
 #endif /* KEYMAP_SIZE > 128 */
   return (newmap);
 }
References CTRL, _keymap_entry::function, i, rl_insert(), rl_make_bare_keymap(), rl_rubout(), RUBOUT, and TAB.
rl_mark_active_p()
int rl_mark_active_p (void)
Definition at line 1885 of file text.c.
 {
   return (mark_active);
 }
References mark_active.
Referenced by _rl_internal_char_cleanup(), _rl_isearch_dispatch(), rl_newline(), and rl_redisplay().
rl_maybe_replace_line()
int rl_maybe_replace_line (void)
Definition at line 330 of file misc.c.
 {
   HIST_ENTRY *temp;
   temp = current_history ();
   /* If the current line has changed, save the changes. */
   if (temp && ((UNDO_LIST *)(temp->data) != rl_undo_list))
     {
       temp = replace_history_entry (where_history (), rl_line_buffer, (histdata_t)rl_undo_list);
       xfree (temp->line);
       FREE (temp->timestamp);
       xfree (temp);
     }
   return 0;
 }
Referenced by rl_end_of_history(), rl_get_next_history(), and rl_get_previous_history().
rl_maybe_save_line()
int rl_maybe_save_line (void)
Definition at line 369 of file misc.c.
 {
   if (_rl_saved_line_for_history == 0)
     {
       _rl_saved_line_for_history = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
       _rl_saved_line_for_history->line = savestring (rl_line_buffer);
       _rl_saved_line_for_history->timestamp = (char *)NULL;
       _rl_saved_line_for_history->data = (char *)rl_undo_list;
     }
   return 0;
 }
Referenced by rl_get_previous_history().
rl_maybe_unsave_line()
int rl_maybe_unsave_line (void)
Definition at line 348 of file misc.c.
 {
   if (_rl_saved_line_for_history)
     {
       /* Can't call with `1' because rl_undo_list might point to an undo
      list from a history entry, as in rl_replace_from_history() below. */
       rl_replace_line (_rl_saved_line_for_history->line, 0);
       rl_undo_list = (UNDO_LIST *)_rl_saved_line_for_history->data;
       /* Doesn't free `data'. */
       _rl_free_history_entry (_rl_saved_line_for_history);
       _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
       rl_point = rl_end;    /* rl_replace_line sets rl_end */
     }
   else
     rl_ding ();
   return 0;
 }
Referenced by rl_end_of_history(), and rl_get_next_history().
rl_menu_complete()
int rl_menu_complete (int count, int ignore)
Definition at line 2815 of file complete.c.
 {
   rl_compentry_func_t *our_func;
   int matching_filenames, found_quote;
   static char *orig_text;
   static char **matches = (char **)0;
   static int match_list_index = 0;
   static int match_list_size = 0;
   static int nontrivial_lcd = 0;
   static int full_completion = 0;   /* set to 1 if menu completion should reinitialize on next call */
   static int orig_start, orig_end;
   static char quote_char;
   static int delimiter, cstate;
   /* The first time through, we generate the list of matches and set things
      up to insert them. */
   if ((rl_last_func != rl_menu_complete && rl_last_func != rl_backward_menu_complete) || full_completion)
     {
       /* Clean up from previous call, if any. */
       FREE (orig_text);
       if (matches)
     _rl_free_match_list (matches);
       match_list_index = match_list_size = 0;
       matches = (char **)NULL;
       full_completion = 0;
       RL_SETSTATE(RL_STATE_COMPLETING);
       /* Only the completion entry function can change these. */
       set_completion_defaults ('%');
       our_func = rl_menu_completion_entry_function;
       if (our_func == 0)
     our_func = rl_completion_entry_function
             ? rl_completion_entry_function
             : rl_filename_completion_function;
       /* We now look backwards for the start of a filename/variable word. */
       orig_end = rl_point;
       found_quote = delimiter = 0;
       quote_char = '\0';
       if (rl_point)
     /* This (possibly) changes rl_point.  If it returns a non-zero char,
        we know we have an open quote. */
     quote_char = _rl_find_completion_word (&found_quote, &delimiter);
       orig_start = rl_point;
       rl_point = orig_end;
       orig_text = rl_copy_text (orig_start, orig_end);
       matches = gen_completion_matches (orig_text, orig_start, orig_end,
                     our_func, found_quote, quote_char);
       nontrivial_lcd = matches && compare_match (orig_text, matches[0]) != 0;
       /* If we are matching filenames, the attempted completion function will
      have set rl_filename_completion_desired to a non-zero value.  The basic
      rl_filename_completion_function does this. */
       matching_filenames = rl_filename_completion_desired;
       if (matches == 0 || postprocess_matches (&matches, matching_filenames) == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       FREE (orig_text);
       orig_text = (char *)0;
       completion_changed_buffer = 0;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       return (0);
     }
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       for (match_list_size = 0; matches[match_list_size]; match_list_size++)
         ;
       if (match_list_size == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       match_list_index = 0;
       completion_changed_buffer = 0;
       return (0);
         }
       /* matches[0] is lcd if match_list_size > 1, but the circular buffer
      code below should take care of it. */
       if (*matches[0])
     {
       insert_match (matches[0], orig_start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
       orig_end = orig_start + strlen (matches[0]);
       completion_changed_buffer = STREQ (orig_text, matches[0]) == 0;
     }
       if (match_list_size > 1 && _rl_complete_show_all)
     {
       display_matches (matches);
       /* If there are so many matches that the user has to be asked
          whether or not he wants to see the matches, menu completion
          is unwieldy. */
       if (rl_completion_query_items > 0 && match_list_size >= rl_completion_query_items)
         {
           rl_ding ();
           FREE (matches);
           matches = (char **)0;
           full_completion = 1;
           return (0);
         }
       else if (_rl_menu_complete_prefix_first)
         {
           rl_ding ();
           return (0);
         }
     }
       else if (match_list_size <= 1)
     {
       append_to_match (matches[0], delimiter, quote_char, nontrivial_lcd);
       full_completion = 1;
       return (0);
     }
       else if (_rl_menu_complete_prefix_first && match_list_size > 1)
     {
       rl_ding ();
       return (0);
     }
     }
   /* Now we have the list of matches.  Replace the text between
      rl_line_buffer[orig_start] and rl_line_buffer[rl_point] with
      matches[match_list_index], and add any necessary closing char. */
   if (matches == 0 || match_list_size == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       completion_changed_buffer = 0;
       return (0);
     }
   match_list_index += count;
   if (match_list_index < 0)
     {
       while (match_list_index < 0)
     match_list_index += match_list_size;
     }
   else
     match_list_index %= match_list_size;
   if (match_list_index == 0 && match_list_size > 1)
     {
       rl_ding ();
       insert_match (matches[0], orig_start, MULT_MATCH, &quote_char);
     }
   else
     {
       insert_match (matches[match_list_index], orig_start, SINGLE_MATCH, &quote_char);
       append_to_match (matches[match_list_index], delimiter, quote_char,
                compare_match (orig_text, matches[match_list_index]));
     }
   completion_changed_buffer = 1;
   return (0);
 }
References _rl_complete_show_all, _rl_find_completion_word(), _rl_free_match_list(), _rl_menu_complete_prefix_first, append_to_match(), compare_match(), completion_changed_buffer, count, display_matches(), FREE, gen_completion_matches(), insert_match(), MULT_MATCH, NULL, postprocess_matches(), rl_backward_menu_complete(), rl_completion_entry_function, rl_completion_query_items, rl_copy_text(), rl_ding(), rl_filename_completion_desired, rl_filename_completion_function(), rl_last_func, rl_menu_completion_entry_function, rl_point, RL_SETSTATE, RL_STATE_COMPLETING, RL_UNSETSTATE, set_completion_defaults(), SINGLE_MATCH, STREQ, and strlen().
Referenced by rl_backward_menu_complete().
rl_message()
int rl_message ()
rl_modifying()
int rl_modifying (int start, int end)
Definition at line 310 of file undo.c.
 {
   if (start > end)
     {
       SWAP (start, end);
     }
   if (start != end)
     {
       char *temp = rl_copy_text (start, end);
       rl_begin_undo_group ();
       rl_add_undo (UNDO_DELETE, start, end, temp);
       rl_add_undo (UNDO_INSERT, start, end, (char *)NULL);
       rl_end_undo_group ();
     }
   return 0;
 }
References end, NULL, rl_add_undo(), rl_begin_undo_group(), rl_copy_text(), rl_end_undo_group(), start, SWAP, UNDO_DELETE, and UNDO_INSERT.
Referenced by invert_case_line(), and rl_change_case().
rl_named_function()
rl_command_func_t* rl_named_function (const char * string)
Definition at line 794 of file bind.c.
 {
   register int i;
   rl_initialize_funmap ();
   for (i = 0; funmap[i]; i++)
     if (_rl_stricmp (funmap[i]->name, string) == 0)
       return (funmap[i]->function);
   return ((rl_command_func_t *)NULL);
 }
References _rl_stricmp(), funmap, i, NULL, and rl_initialize_funmap().
Referenced by rl_function_dumper(), rl_parse_and_bind(), and rl_unbind_command_in_map().
rl_newline()
int rl_newline (int count, int key)
Definition at line 1097 of file text.c.
 {
   if (rl_mark_active_p ())
     {
       rl_deactivate_mark ();
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
     }
   rl_done = 1;
   if (_rl_history_preserve_point)
     _rl_history_saved_point = (rl_point == rl_end) ? -1 : rl_point;
   RL_SETSTATE(RL_STATE_DONE);
 #if defined (VI_MODE)
   if (rl_editing_mode == vi_mode)
     {
       _rl_vi_done_inserting ();
       if (_rl_vi_textmod_command (_rl_vi_last_command) == 0)    /* XXX */
     _rl_vi_reset_last ();
     }
 #endif /* VI_MODE */
   /* If we've been asked to erase empty lines, suppress the final update,
      since _rl_update_final calls rl_crlf(). */
   if (rl_erase_empty_line && rl_point == 0 && rl_end == 0)
     return 0;
   if (_rl_echoing_p)
     _rl_update_final ();
   return 0;
 }
References _rl_echoing_p, _rl_history_preserve_point, _rl_history_saved_point, _rl_update_final(), _rl_vi_done_inserting(), _rl_vi_last_command, _rl_vi_reset_last(), _rl_vi_textmod_command(), _rl_want_redisplay, rl_deactivate_mark(), rl_done, rl_editing_mode, rl_end, rl_erase_empty_line, rl_mark_active_p(), rl_point, RL_SETSTATE, RL_STATE_DONE, and vi_mode.
Referenced by _rl_internal_char_cleanup(), rl_insert_comment(), rl_operate_and_get_next(), rl_vi_eof_maybe(), and rl_vi_replace().
rl_next_screen_line()
int rl_next_screen_line (int count, int key)
Definition at line 629 of file text.c.
 {
   int c;
   c = _rl_term_autowrap ? _rl_screenwidth : (_rl_screenwidth + 1);
   return (rl_forward_char (c, key));
 }
References _rl_screenwidth, _rl_term_autowrap, c, and rl_forward_char().
rl_noninc_forward_search()
int rl_noninc_forward_search (int count, int key)
Definition at line 449 of file search.c.
 {
   return noninc_search (1, (key == '?') ? '?' : 0);
 }
References noninc_search().
Referenced by rl_vi_search().
rl_noninc_forward_search_again()
int rl_noninc_forward_search_again (int count, int key)
Definition at line 466 of file search.c.
 {
   int r;
   if (!noninc_search_string)
     {
       rl_ding ();
       return (1);
     }
 #if defined (VI_MODE)
   if (VI_COMMAND_MODE() && key == 'N')
     r = noninc_dosearch (noninc_search_string, 1, SF_PATTERN);
   else
 #endif
     r = noninc_dosearch (noninc_search_string, 1, 0);
   return (r != 1);
 }
References noninc_dosearch(), noninc_search_string, rl_ding(), SF_PATTERN, and VI_COMMAND_MODE.
Referenced by rl_vi_search_again().
rl_noninc_reverse_search()
int rl_noninc_reverse_search (int count, int key)
Definition at line 457 of file search.c.
 {
   return noninc_search (-1, (key == '/') ? '/' : 0);
 }
References noninc_search().
Referenced by rl_vi_search().
rl_noninc_reverse_search_again()
int rl_noninc_reverse_search_again (int count, int key)
Definition at line 488 of file search.c.
 {
   int r;
   if (!noninc_search_string)
     {
       rl_ding ();
       return (1);
     }
 #if defined (VI_MODE)
   if (VI_COMMAND_MODE() && key == 'n')
     r = noninc_dosearch (noninc_search_string, -1, SF_PATTERN);
   else
 #endif
     r = noninc_dosearch (noninc_search_string, -1, 0);
   return (r != 1);
 }
References noninc_dosearch(), noninc_search_string, rl_ding(), SF_PATTERN, and VI_COMMAND_MODE.
Referenced by rl_vi_search_again().
rl_old_menu_complete()
int rl_old_menu_complete (int count, int invoking_key)
Definition at line 2684 of file complete.c.
 {
   rl_compentry_func_t *our_func;
   int matching_filenames, found_quote;
   static char *orig_text;
   static char **matches = (char **)0;
   static int match_list_index = 0;
   static int match_list_size = 0;
   static int orig_start, orig_end;
   static char quote_char;
   static int delimiter;
   /* The first time through, we generate the list of matches and set things
      up to insert them. */
   if (rl_last_func != rl_old_menu_complete)
     {
       /* Clean up from previous call, if any. */
       FREE (orig_text);
       if (matches)
     _rl_free_match_list (matches);
       match_list_index = match_list_size = 0;
       matches = (char **)NULL;
       rl_completion_invoking_key = invoking_key;
       RL_SETSTATE(RL_STATE_COMPLETING);
       /* Only the completion entry function can change these. */
       set_completion_defaults ('%');
       our_func = rl_menu_completion_entry_function;
       if (our_func == 0)
     our_func = rl_completion_entry_function
             ? rl_completion_entry_function
             : rl_filename_completion_function;
       /* We now look backwards for the start of a filename/variable word. */
       orig_end = rl_point;
       found_quote = delimiter = 0;
       quote_char = '\0';
       if (rl_point)
     /* This (possibly) changes rl_point.  If it returns a non-zero char,
        we know we have an open quote. */
     quote_char = _rl_find_completion_word (&found_quote, &delimiter);
       orig_start = rl_point;
       rl_point = orig_end;
       orig_text = rl_copy_text (orig_start, orig_end);
       matches = gen_completion_matches (orig_text, orig_start, orig_end,
                     our_func, found_quote, quote_char);
       /* If we are matching filenames, the attempted completion function will
      have set rl_filename_completion_desired to a non-zero value.  The basic
      rl_filename_completion_function does this. */
       matching_filenames = rl_filename_completion_desired;
       if (matches == 0 || postprocess_matches (&matches, matching_filenames) == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       FREE (orig_text);
       orig_text = (char *)0;
       completion_changed_buffer = 0;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       return (0);
     }
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       for (match_list_size = 0; matches[match_list_size]; match_list_size++)
         ;
       /* matches[0] is lcd if match_list_size > 1, but the circular buffer
      code below should take care of it. */
       if (match_list_size > 1 && _rl_complete_show_all)
     display_matches (matches);
     }
   /* Now we have the list of matches.  Replace the text between
      rl_line_buffer[orig_start] and rl_line_buffer[rl_point] with
      matches[match_list_index], and add any necessary closing char. */
   if (matches == 0 || match_list_size == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       completion_changed_buffer = 0;
       return (0);
     }
   match_list_index += count;
   if (match_list_index < 0)
     {
       while (match_list_index < 0)
     match_list_index += match_list_size;
     }
   else
     match_list_index %= match_list_size;
   if (match_list_index == 0 && match_list_size > 1)
     {
       rl_ding ();
       insert_match (orig_text, orig_start, MULT_MATCH, &quote_char);
     }
   else
     {
       insert_match (matches[match_list_index], orig_start, SINGLE_MATCH, &quote_char);
       append_to_match (matches[match_list_index], delimiter, quote_char,
                compare_match (orig_text, matches[match_list_index]));
     }
   completion_changed_buffer = 1;
   return (0);
 }
References _rl_complete_show_all, _rl_find_completion_word(), _rl_free_match_list(), append_to_match(), compare_match(), completion_changed_buffer, count, display_matches(), FREE, gen_completion_matches(), insert_match(), MULT_MATCH, NULL, postprocess_matches(), rl_completion_entry_function, rl_completion_invoking_key, rl_copy_text(), rl_ding(), rl_filename_completion_desired, rl_filename_completion_function(), rl_last_func, rl_menu_completion_entry_function, rl_point, RL_SETSTATE, RL_STATE_COMPLETING, RL_UNSETSTATE, set_completion_defaults(), and SINGLE_MATCH.
rl_on_new_line()
int rl_on_new_line (void)
Definition at line 2581 of file display.c.
 {
   if (visible_line)
     visible_line[0] = '\0';
   _rl_last_c_pos = _rl_last_v_pos = 0;
   _rl_vis_botlin = last_lmargin = 0;
   if (vis_lbreaks)
     vis_lbreaks[0] = vis_lbreaks[1] = 0;
   visible_wrap_offset = 0;
   return 0;
 }
References _rl_last_c_pos, _rl_last_v_pos, _rl_vis_botlin, last_lmargin, vis_lbreaks, visible_line, and visible_wrap_offset.
Referenced by readline_internal_setup(), rl_dump_functions(), rl_dump_macros(), rl_dump_variables(), rl_forced_update_display(), rl_redisplay(), and rl_reset_line_state().
rl_on_new_line_with_prompt()
int rl_on_new_line_with_prompt (void)
Definition at line 2625 of file display.c.
 {
   int prompt_size, i, l, real_screenwidth, newlines;
   char *prompt_last_line, *lprompt;
   /* Initialize visible_line and invisible_line to ensure that they can hold
      the already-displayed prompt. */
   prompt_size = strlen (rl_prompt) + 1;
   init_line_structures (prompt_size);
   /* Make sure the line structures hold the already-displayed prompt for
      redisplay. */
   lprompt = local_prompt ? local_prompt : rl_prompt;
   strcpy (visible_line, lprompt);
   strcpy (invisible_line, lprompt);
   /* If the prompt contains newlines, take the last tail. */
   prompt_last_line = strrchr (rl_prompt, '\n');
   if (!prompt_last_line)
     prompt_last_line = rl_prompt;
   l = strlen (prompt_last_line);
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     _rl_last_c_pos = _rl_col_width (prompt_last_line, 0, l, 1); /* XXX */
   else
     _rl_last_c_pos = l;
   /* Dissect prompt_last_line into screen lines. Note that here we have
      to use the real screenwidth. Readline's notion of screenwidth might be
      one less, see terminal.c. */
   real_screenwidth = _rl_screenwidth + (_rl_term_autowrap ? 0 : 1);
   _rl_last_v_pos = l / real_screenwidth;
   /* If the prompt length is a multiple of real_screenwidth, we don't know
      whether the cursor is at the end of the last line, or already at the
      beginning of the next line. Output a newline just to be safe. */
   if (l > 0 && (l % real_screenwidth) == 0)
     _rl_output_some_chars ("\n", 1);
   last_lmargin = 0;
   newlines = 0; i = 0;
   while (i <= l)
     {
       _rl_vis_botlin = newlines;
       vis_lbreaks[newlines++] = i;
       i += real_screenwidth;
     }
   vis_lbreaks[newlines] = l;
   visible_wrap_offset = 0;
   rl_display_prompt = rl_prompt;    /* XXX - make sure it's set */
   return 0;
 }
References _rl_col_width, _rl_last_c_pos, _rl_last_v_pos, _rl_output_some_chars(), _rl_screenwidth, _rl_term_autowrap, _rl_vis_botlin, i, init_line_structures(), invisible_line, l, last_lmargin, local_prompt, MB_CUR_MAX, rl_byte_oriented, rl_display_prompt, rl_prompt, strcpy(), strlen(), strrchr(), vis_lbreaks, visible_line, and visible_wrap_offset.
Referenced by readline_internal_setup().
rl_operate_and_get_next()
int rl_operate_and_get_next (int count, int c)
Definition at line 713 of file misc.c.
 {
   /* Accept the current line. */
   rl_newline (1, c);
   saved_history_logical_offset = rl_explicit_arg ? count : where_history () + history_base + 1;
   _rl_saved_internal_startup_hook = _rl_internal_startup_hook;
   _rl_internal_startup_hook = set_saved_history;
   return 0;
 }
References _rl_internal_startup_hook, _rl_saved_internal_startup_hook, c, count, history_base, rl_explicit_arg, rl_newline(), saved_history_logical_offset, set_saved_history(), and where_history().
rl_overwrite_mode()
int rl_overwrite_mode (int count, int key)
Definition at line 771 of file misc.c.
 {
   if (rl_explicit_arg == 0)
     _rl_set_insert_mode (rl_insert_mode ^ 1, 0);
   else if (count > 0)
     _rl_set_insert_mode (RL_IM_OVERWRITE, 0);
   else
     _rl_set_insert_mode (RL_IM_INSERT, 0);
   return 0;
 }
References _rl_set_insert_mode(), count, rl_explicit_arg, RL_IM_INSERT, RL_IM_OVERWRITE, and rl_insert_mode.
Referenced by bind_arrow_keys_internal(), and bind_termcap_arrow_keys().
rl_parse_and_bind()
int rl_parse_and_bind (char * string)
Definition at line 1609 of file bind.c.
 {
   char *funname, *kname;
   register int c, i;
   int key, equivalency, foundmod, foundsep;
   while (string && whitespace (*string))
     string++;
   if (string == 0 || *string == 0 || *string == '#')
     return 0;
   /* If this is a parser directive, act on it. */
   if (*string == '$')
     {
       handle_parser_directive (&string[1]);
       return 0;
     }
   /* If we aren't supposed to be parsing right now, then we're done. */
   if (_rl_parsing_conditionalized_out)
     return 0;
   i = 0;
   /* If this keyname is a complex key expression surrounded by quotes,
      advance to after the matching close quote.  This code allows the
      backslash to quote characters in the key expression. */
   if (*string == '"')
     {
       i = _rl_skip_to_delim (string, 1, '"');
       /* If we didn't find a closing quote, abort the line. */
       if (string[i] == '\0')
         {
           _rl_init_file_error ("%s: no closing `\"' in key binding", string);
           return 1;
         }
       else
         i++;    /* skip past closing double quote */
     }
   /* Advance to the colon (:) or whitespace which separates the two objects. */
   for (; (c = string[i]) && c != ':' && c != ' ' && c != '\t'; i++ );
   if (i == 0)
     {
       _rl_init_file_error ("`%s': invalid key binding: missing key sequence", string);
       return 1;
     }
   equivalency = (c == ':' && string[i + 1] == '=');
   foundsep = c != 0;
   /* Mark the end of the command (or keyname). */
   if (string[i])
     string[i++] = '\0';
   /* If doing assignment, skip the '=' sign as well. */
   if (equivalency)
     string[i++] = '\0';
   /* If this is a command to set a variable, then do that. */
   if (_rl_stricmp (string, "set") == 0)
     {
       char *var, *value, *e;
       int s;
       var = string + i;
       /* Make VAR point to start of variable name. */
       while (*var && whitespace (*var)) var++;
       /* Make VALUE point to start of value string. */
       value = var;
       while (*value && whitespace (*value) == 0) value++;
       if (*value)
     *value++ = '\0';
       while (*value && whitespace (*value)) value++;
       /* Strip trailing whitespace from values of boolean variables. */
       if (find_boolean_var (var) >= 0)
     {
       /* just read a whitespace-delimited word or empty string */
       for (e = value; *e && whitespace (*e) == 0; e++)
         ;
       if (e > value)
         *e = '\0';      /* cut off everything trailing */
     }
       else if ((i = find_string_var (var)) >= 0)
     {
       /* Allow quoted strings in variable values */
       if (*value == '"')
         {
           i = _rl_skip_to_delim (value, 1, *value);
           value[i] = '\0';
           value++;  /* skip past the quote */
         }
       else
         {
           /* remove trailing whitespace */
           e = value + strlen (value) - 1;
           while (e >= value && whitespace (*e))
         e--;
           e++;      /* skip back to whitespace or EOS */
           if (*e && e >= value)
         *e = '\0';
         }
     }
       else
     {
       /* avoid calling rl_variable_bind just to find this out */
       _rl_init_file_error ("%s: unknown variable name", var);
       return 1;
     }
       rl_variable_bind (var, value);
       return 0;
     }
   /* Skip any whitespace between keyname and funname. */
   for (; string[i] && whitespace (string[i]); i++);
   funname = &string[i];
   /* Now isolate funname.
      For straight function names just look for whitespace, since
      that will signify the end of the string.  But this could be a
      macro definition.  In that case, the string is quoted, so skip
      to the matching delimiter.  We allow the backslash to quote the
      delimiter characters in the macro body. */
   /* This code exists to allow whitespace in macro expansions, which
      would otherwise be gobbled up by the next `for' loop.*/
   /* XXX - it may be desirable to allow backslash quoting only if " is
      the quoted string delimiter, like the shell. */
   if (*funname == '\'' || *funname == '"')
     {
       i = _rl_skip_to_delim (string, i+1, *funname);
       if (string[i])
     i++;
       else
     {
       _rl_init_file_error ("`%s': missing closing quote for macro", funname);
       return 1;
     }
     }
   /* Advance to the end of the string.  */
   for (; string[i] && whitespace (string[i]) == 0; i++);
   /* No extra whitespace at the end of the string. */
   string[i] = '\0';
   /* Handle equivalency bindings here.  Make the left-hand side be exactly
      whatever the right-hand evaluates to, including keymaps. */
   if (equivalency)
     {
       return 0;
     }
   if (foundsep == 0)
     {
       _rl_init_file_error ("%s: no key sequence terminator", string);
       return 1;
     }
   /* If this is a new-style key-binding, then do the binding with
      rl_bind_keyseq ().  Otherwise, let the older code deal with it. */
   if (*string == '"')
     {
       char *seq;
       register int j, k, passc;
       seq = (char *)xmalloc (1 + strlen (string));
       for (j = 1, k = passc = 0; string[j]; j++)
     {
       /* Allow backslash to quote characters, but leave them in place.
          This allows a string to end with a backslash quoting another
          backslash, or with a backslash quoting a double quote.  The
          backslashes are left in place for rl_translate_keyseq (). */
       if (passc || (string[j] == '\\'))
         {
           seq[k++] = string[j];
           passc = !passc;
           continue;
         }
       if (string[j] == '"')
         break;
       seq[k++] = string[j];
     }
       seq[k] = '\0';
       /* Binding macro? */
       if (*funname == '\'' || *funname == '"')
     {
       j = strlen (funname);
       /* Remove the delimiting quotes from each end of FUNNAME. */
       if (j && funname[j - 1] == *funname)
         funname[j - 1] = '\0';
       rl_macro_bind (seq, &funname[1], _rl_keymap);
     }
       else
     rl_bind_keyseq (seq, rl_named_function (funname));
       xfree (seq);
       return 0;
     }
   /* Get the actual character we want to deal with. */
   kname = strrchr (string, '-');
   if (kname == 0)
     kname = string;
   else
     kname++;
   key = glean_key_from_name (kname);
   /* Add in control and meta bits. */
   foundmod = 0;
   if (substring_member_of_array (string, _rl_possible_control_prefixes))
     {
       key = CTRL (_rl_to_upper (key));
       foundmod = 1;
     }
   if (substring_member_of_array (string, _rl_possible_meta_prefixes))
     {
       key = META (key);
       foundmod = 1;
     }
   if (foundmod == 0 && kname != string)
     {
       _rl_init_file_error ("%s: unknown key modifier", string);
       return 1;
     }
   /* Temporary.  Handle old-style keyname with macro-binding. */
   if (*funname == '\'' || *funname == '"')
     {
       char useq[2];
       int fl = strlen (funname);
       useq[0] = key; useq[1] = '\0';
       if (fl && funname[fl - 1] == *funname)
     funname[fl - 1] = '\0';
       rl_macro_bind (useq, &funname[1], _rl_keymap);
     }
 #if defined (PREFIX_META_HACK)
   /* Ugly, but working hack to keep prefix-meta around. */
   else if (_rl_stricmp (funname, "prefix-meta") == 0)
     {
       char seq[2];
       seq[0] = key;
       seq[1] = '\0';
       rl_generic_bind (ISKMAP, seq, (char *)emacs_meta_keymap, _rl_keymap);
     }
 #endif /* PREFIX_META_HACK */
   else
     rl_bind_key (key, rl_named_function (funname));
   return 0;
 }
References _rl_init_file_error(), _rl_keymap, _rl_parsing_conditionalized_out, _rl_possible_control_prefixes, _rl_possible_meta_prefixes, _rl_skip_to_delim(), _rl_stricmp(), _rl_to_upper(), c, CTRL, emacs_meta_keymap, find_boolean_var(), find_string_var(), glean_key_from_name(), handle_parser_directive(), i, ISKMAP, j, k, META, rl_bind_key(), rl_bind_keyseq(), rl_generic_bind(), rl_macro_bind(), rl_named_function(), rl_variable_bind(), s, seq, string, strlen(), strrchr(), substring_member_of_array(), value, whitespace, xfree, and xmalloc.
Referenced by _rl_read_init_file().
rl_pending_signal()
int rl_pending_signal (void)
Definition at line 606 of file signals.c.
 {
   return (_rl_caught_signal);
 }
References _rl_caught_signal.
rl_possible_completions()
int rl_possible_completions (int ignore, int invoking_key)
Definition at line 456 of file complete.c.
 {
   rl_completion_invoking_key = invoking_key;
   return (rl_complete_internal ('?'));
 }
References rl_complete_internal(), and rl_completion_invoking_key.
Referenced by rl_delete_or_show_completions().
rl_prep_terminal()
void rl_prep_terminal (int meta_flag)
Definition at line 597 of file rltty.c.
 {
   int tty, nprep;
   TIOTYPE tio;
   if (terminal_prepped)
     return;
   /* Try to keep this function from being INTerrupted. */
   _rl_block_sigint ();
   tty = rl_instream ? fileno (rl_instream) : fileno (stdin);
   if (get_tty_settings (tty, &tio) < 0)
     {
 #if defined (ENOTSUP)
       /* MacOS X and Linux, at least, lie about the value of errno if
      tcgetattr fails. */
       if (errno == ENOTTY || errno == EINVAL || errno == ENOTSUP)
 #else
       if (errno == ENOTTY || errno == EINVAL)
 #endif
     _rl_echoing_p = 1;      /* XXX */
       _rl_release_sigint ();
       return;
     }
   otio = tio;
   if (_rl_bind_stty_chars)
     {
 #if defined (VI_MODE)
       /* If editing in vi mode, make sure we restore the bindings in the
      insertion keymap no matter what keymap we ended up in. */
       if (rl_editing_mode == vi_mode)
     rl_tty_unset_default_bindings (vi_insertion_keymap);
       else
 #endif
     rl_tty_unset_default_bindings (_rl_keymap);
     }
   save_tty_chars (&otio);
   RL_SETSTATE(RL_STATE_TTYCSAVED);
   if (_rl_bind_stty_chars)
     {
 #if defined (VI_MODE)
       /* If editing in vi mode, make sure we set the bindings in the
      insertion keymap no matter what keymap we ended up in. */
       if (rl_editing_mode == vi_mode)
     _rl_bind_tty_special_chars (vi_insertion_keymap, tio);
       else
 #endif
     _rl_bind_tty_special_chars (_rl_keymap, tio);
     }
   prepare_terminal_settings (meta_flag, otio, &tio);
   if (set_tty_settings (tty, &tio) < 0)
     {
       _rl_release_sigint ();
       return;
     }
   if (_rl_enable_keypad)
     _rl_control_keypad (1);
   nprep = TPX_PREPPED;
   if (_rl_enable_bracketed_paste)
     {
       fprintf (rl_outstream, BRACK_PASTE_INIT);
       nprep |= TPX_BRACKPASTE;
     }
   fflush (rl_outstream);
   terminal_prepped = nprep;
   RL_SETSTATE(RL_STATE_TERMPREPPED);
   _rl_release_sigint ();
 }
References _rl_bind_stty_chars, _rl_bind_tty_special_chars(), _rl_block_sigint(), _rl_control_keypad(), _rl_echoing_p, _rl_enable_bracketed_paste, _rl_enable_keypad, _rl_keymap, _rl_release_sigint(), BRACK_PASTE_INIT, EINVAL, ENOTSUP, ENOTTY, errno, fflush(), fileno(), fprintf(), get_tty_settings(), otio, prepare_terminal_settings(), rl_editing_mode, rl_instream, rl_outstream, RL_SETSTATE, RL_STATE_TERMPREPPED, RL_STATE_TTYCSAVED, rl_tty_unset_default_bindings(), save_tty_chars(), set_tty_settings(), stdin, terminal_prepped, tio, TIOTYPE, TPX_BRACKPASTE, TPX_PREPPED, vi_insertion_keymap, and vi_mode.
rl_previous_screen_line()
int rl_previous_screen_line (int count, int key)
Definition at line 620 of file text.c.
 {
   int c;
   c = _rl_term_autowrap ? _rl_screenwidth : (_rl_screenwidth + 1);
   return (rl_backward_char (c, key));
 }
References _rl_screenwidth, _rl_term_autowrap, c, and rl_backward_char().
rl_print_last_kbd_macro()
int rl_print_last_kbd_macro (int count, int ignore)
Definition at line 309 of file macro.c.
 {
   char *m;
   if (current_macro == 0)
     {
       rl_ding ();
       return 0;
     }
   m = _rl_untranslate_macro_value (current_macro, 1);
   rl_crlf ();
   printf ("%s", m);
   fflush (stdout);
   rl_crlf ();
   FREE (m);
   rl_forced_update_display ();
   rl_display_fixed = 1;
   return 0;
 }
References _rl_untranslate_macro_value(), current_macro, fflush(), FREE, printf(), rl_crlf(), rl_ding(), rl_display_fixed, rl_forced_update_display(), and stdout.
rl_push_macro_input()
void rl_push_macro_input (char * macro)
Definition at line 331 of file macro.c.
 {
   _rl_with_macro_input (macro);
 }
References _rl_with_macro_input().
rl_quoted_insert()
int rl_quoted_insert (int count, int key)
Definition at line 1055 of file text.c.
 {
   /* Let's see...should the callback interface futz with signal handling? */
 #if defined (HANDLE_SIGNALS)
   if (RL_ISSTATE (RL_STATE_CALLBACK) == 0)
     _rl_disable_tty_signals ();
 #endif
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_func = _rl_insert_next_callback;
       return (0);
     }
 #endif
   /* A negative count means to quote the next -COUNT characters. */
   if (count < 0)
     {
       int r;
       do
     r = _rl_insert_next (1);
       while (r == 0 && ++count < 0);
       return r;
     }
   return _rl_insert_next (count);
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_disable_tty_signals(), _rl_insert_next(), _rl_insert_next_callback(), count, RL_ISSTATE, and RL_STATE_CALLBACK.
Referenced by _rl_bind_tty_special_chars().
rl_re_read_init_file()
int rl_re_read_init_file (int count, int ignore)
Definition at line 1024 of file bind.c.
 {
   int r;
   r = rl_read_init_file ((const char *)NULL);
   rl_set_keymap_from_edit_mode ();
   return r;
 }
References NULL, rl_read_init_file(), and rl_set_keymap_from_edit_mode().
rl_read_init_file()
int rl_read_init_file (const char * filename)
Definition at line 1041 of file bind.c.
 {
   /* Default the filename. */
   if (filename == 0)
     filename = last_readline_init_file;
   if (filename == 0)
     filename = sh_get_env_value ("INPUTRC");
   if (filename == 0 || *filename == 0)
     {
       filename = DEFAULT_INPUTRC;
       /* Try to read DEFAULT_INPUTRC; fall back to SYS_INPUTRC on failure */
       if (_rl_read_init_file (filename, 0) == 0)
     return 0;
       filename = SYS_INPUTRC;
     }
 #if defined (__MSDOS__)
   if (_rl_read_init_file (filename, 0) == 0)
     return 0;
   filename = "~/_inputrc";
 #endif
   return (_rl_read_init_file (filename, 0));
 }
References _rl_read_init_file(), DEFAULT_INPUTRC, filename, last_readline_init_file, sh_get_env_value(), and SYS_INPUTRC.
Referenced by readline_initialize_everything(), and rl_re_read_init_file().
rl_read_key()
int rl_read_key (void)
Definition at line 752 of file input.c.
 {
   int c, r;
   if (rl_pending_input)
     {
       c = rl_pending_input; /* XXX - cast to unsigned char if > 0? */
       rl_clear_pending_input ();
     }
   else
     {
       /* If input is coming from a macro, then use that. */
       if (c = _rl_next_macro_key ())
     return ((unsigned char)c);
       /* If the user has an event function, then call it periodically. */
       if (rl_event_hook)
     {
       while (rl_event_hook)
         {
           if (rl_get_char (&c) != 0)
         break;
           if ((r = rl_gather_tyi ()) < 0)   /* XXX - EIO */
         {
           rl_done = 1;
           RL_SETSTATE (RL_STATE_DONE);
           return (errno == EIO ? (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF) : '\n');
         }
           else if (r > 0)           /* read something */
         continue;
           RL_CHECK_SIGNALS ();
           if (rl_done)      /* XXX - experimental */
         return ('\n');
           (*rl_event_hook) ();
         }
     }
       else
     {
       if (rl_get_char (&c) == 0)
         c = (*rl_getc_function) (rl_instream);
 /* fprintf(stderr, "rl_read_key: calling RL_CHECK_SIGNALS: _rl_caught_signal = %d\r\n", _rl_caught_signal); */
       RL_CHECK_SIGNALS ();
     }
     }
   return (c);
 }
References _rl_next_macro_key(), c, EIO, EOF, errno, READERR, RL_CHECK_SIGNALS, rl_clear_pending_input(), rl_done, rl_event_hook, rl_gather_tyi(), rl_get_char(), rl_getc_function, rl_instream, RL_ISSTATE, rl_pending_input, RL_SETSTATE, RL_STATE_DONE, and RL_STATE_READCMD.
Referenced by _rl_arg_getchar(), _rl_bracketed_read_key(), _rl_bracketed_text(), _rl_insert_next(), _rl_isearch_dispatch(), _rl_nsearch_dispatch(), _rl_read_bracketed_paste_prefix(), _rl_search_getchar(), _rl_subseq_getchar(), _rl_vi_callback_char_search(), _rl_vi_goto_mark(), _rl_vi_set_mark(), get_y_or_n(), readline_internal_char(), rl_arrow_keys(), rl_insert(), rl_skip_csi_sequence(), rl_vi_char_search(), and rl_vi_overstrike_bracketed_paste().
rl_redisplay()
void rl_redisplay (void)
Definition at line 763 of file display.c.
 {
   int in, out, c, linenum, cursor_linenum;
   int inv_botlin, lb_botlin, lb_linenum, o_cpos;
   int newlines, lpos, temp, n0, num, prompt_lines_estimate;
   char *prompt_this_line;
   char cur_face;
   int hl_begin, hl_end;
   int mb_cur_max = MB_CUR_MAX;
 #if defined (HANDLE_MULTIBYTE)
   WCHAR_T wc;
   size_t wc_bytes;
   int wc_width;
   mbstate_t ps;
   int _rl_wrapped_multicolumn = 0;
 #endif
   if (_rl_echoing_p == 0)
     return;
   /* Block keyboard interrupts because this function manipulates global
      data structures. */
   _rl_block_sigint ();
   RL_SETSTATE (RL_STATE_REDISPLAYING);
   cur_face = FACE_NORMAL;
   /* Can turn this into an array for multiple highlighted objects in addition
      to the region */
   hl_begin = hl_end = -1;
   if (rl_mark_active_p ())
     set_active_region (&hl_begin, &hl_end);
   if (!rl_display_prompt)
     rl_display_prompt = "";
   if (line_structures_initialized == 0)
     {
       init_line_structures (0);
       rl_on_new_line ();
     }
   else if (line_size <= _rl_screenwidth)
     init_line_structures (_rl_screenwidth + 1);
   /* Enable horizontal scrolling automatically for terminals of height 1
      where wrapping lines doesn't work. Disable it as soon as the terminal
      height is increased again if it was automatically enabled. */
   if (_rl_screenheight <= 1)
     {
       if (_rl_horizontal_scroll_mode == 0)
      horizontal_scrolling_autoset = 1;
       _rl_horizontal_scroll_mode = 1;
     }
   else if (horizontal_scrolling_autoset)
     _rl_horizontal_scroll_mode = 0;
   /* Draw the line into the buffer. */
   cpos_buffer_position = -1;
   prompt_multibyte_chars = prompt_visible_length - prompt_physical_chars;
   out = inv_botlin = 0;
   /* Mark the line as modified or not.  We only do this for history
      lines. */
   modmark = 0;
   if (_rl_mark_modified_lines && current_history () && rl_undo_list)
     {
       invis_addc (&out, '*', cur_face);
       invis_nul (&out);
       modmark = 1;
     }
   /* If someone thought that the redisplay was handled, but the currently
      visible line has a different modification state than the one about
      to become visible, then correct the caller's misconception. */
   if (visible_line[0] != invisible_line[0])
     rl_display_fixed = 0;
   /* If the prompt to be displayed is the `primary' readline prompt (the
      one passed to readline()), use the values we have already expanded.
      If not, use what's already in rl_display_prompt.  WRAP_OFFSET is the
      number of non-visible characters (bytes) in the prompt string. */
   /* This is where we output the characters in the prompt before the last
      newline, if any.  If there aren't any embedded newlines, we don't
      write anything. Copy the last line of the prompt string into the line in
      any case */
   if (rl_display_prompt == rl_prompt || local_prompt)
     {
       if (local_prompt_prefix && forced_display)
     _rl_output_some_chars (local_prompt_prefix, strlen (local_prompt_prefix));
       if (local_prompt_len > 0)
     invis_adds (&out, local_prompt, local_prompt_len, cur_face);
       invis_nul (&out);
       wrap_offset = local_prompt_len - prompt_visible_length;
     }
   else
     {
       int pmtlen;
       prompt_this_line = strrchr (rl_display_prompt, '\n');
       if (!prompt_this_line)
     prompt_this_line = rl_display_prompt;
       else
     {
       prompt_this_line++;
       pmtlen = prompt_this_line - rl_display_prompt;    /* temp var */
       if (forced_display)
         {
           _rl_output_some_chars (rl_display_prompt, pmtlen);
           /* Make sure we are at column zero even after a newline,
          regardless of the state of terminal output processing. */
           if (pmtlen < 2 || prompt_this_line[-2] != '\r')
         cr ();
         }
     }
       prompt_physical_chars = pmtlen = strlen (prompt_this_line);   /* XXX */
       invis_adds (&out, prompt_this_line, pmtlen, cur_face);
       invis_nul (&out);
       wrap_offset = prompt_invis_chars_first_line = 0;
     }
 #if defined (HANDLE_MULTIBYTE)
 #define CHECK_INV_LBREAKS() \
       do { \
     if (newlines >= (inv_lbsize - 2)) \
       { \
         inv_lbsize *= 2; \
         inv_lbreaks = (int *)xrealloc (inv_lbreaks, inv_lbsize * sizeof (int)); \
       } \
     if (newlines >= (line_state_invisible->wbsize - 2)) \
       { \
         line_state_invisible->wbsize *= 2; \
         line_state_invisible->wrapped_line = (int *)xrealloc (line_state_invisible->wrapped_line, line_state_invisible->wbsize * sizeof(int)); \
       } \
       } while (0)
 #else
 #define CHECK_INV_LBREAKS() \
       do { \
     if (newlines >= (inv_lbsize - 2)) \
       { \
         inv_lbsize *= 2; \
         inv_lbreaks = (int *)xrealloc (inv_lbreaks, inv_lbsize * sizeof (int)); \
       } \
       } while (0)
 #endif /* !HANDLE_MULTIBYTE */
 #if defined (HANDLE_MULTIBYTE)
 #define CHECK_LPOS() \
       do { \
     lpos++; \
     if (lpos >= _rl_screenwidth) \
       { \
         if (newlines >= (inv_lbsize - 2)) \
           { \
         inv_lbsize *= 2; \
         inv_lbreaks = (int *)xrealloc (inv_lbreaks, inv_lbsize * sizeof (int)); \
           } \
         inv_lbreaks[++newlines] = out; \
         if (newlines >= (line_state_invisible->wbsize - 2)) \
           { \
         line_state_invisible->wbsize *= 2; \
         line_state_invisible->wrapped_line = (int *)xrealloc (line_state_invisible->wrapped_line, line_state_invisible->wbsize * sizeof(int)); \
           } \
         line_state_invisible->wrapped_line[newlines] = _rl_wrapped_multicolumn; \
         lpos = 0; \
       } \
       } while (0)
 #else
 #define CHECK_LPOS() \
       do { \
     lpos++; \
     if (lpos >= _rl_screenwidth) \
       { \
         if (newlines >= (inv_lbsize - 2)) \
           { \
         inv_lbsize *= 2; \
         inv_lbreaks = (int *)xrealloc (inv_lbreaks, inv_lbsize * sizeof (int)); \
           } \
         inv_lbreaks[++newlines] = out; \
         lpos = 0; \
       } \
       } while (0)
 #endif
   /* inv_lbreaks[i] is where line i starts in the buffer. */
   inv_lbreaks[newlines = 0] = 0;
   /* lpos is a physical cursor position, so it needs to be adjusted by the
      number of invisible characters in the prompt, per line.  We compute
      the line breaks in the prompt string in expand_prompt, taking invisible
      characters into account, and if lpos exceeds the screen width, we copy
      the data in the loop below. */
   lpos = prompt_physical_chars + modmark;
 #if defined (HANDLE_MULTIBYTE)
   memset (line_state_invisible->wrapped_line, 0, line_state_invisible->wbsize * sizeof (int));
   num = 0;
 #endif
   /* prompt_invis_chars_first_line is the number of invisible characters (bytes)
      in the first physical line of the prompt.
      wrap_offset - prompt_invis_chars_first_line is usually the number of
      invis chars on the second (or, more generally, last) line. */
   /* This is zero-based, used to set the newlines */
   prompt_lines_estimate = lpos / _rl_screenwidth;
   /* what if lpos is already >= _rl_screenwidth before we start drawing the
      contents of the command line? */
   if (lpos >= _rl_screenwidth)
     {
       temp = 0;
       /* first copy the linebreaks array we computed in expand_prompt */
       while (local_prompt_newlines[newlines+1] != -1)
     {
       temp = local_prompt_newlines[newlines+1];
       inv_lbreaks[++newlines] = temp;
     }
       /* Now set lpos from the last newline */
       if (mb_cur_max > 1 && rl_byte_oriented == 0 && prompt_multibyte_chars > 0)
         lpos = _rl_col_width (local_prompt, temp, local_prompt_len, 1) - (wrap_offset - prompt_invis_chars_first_line);
       else
         lpos -= (_rl_screenwidth * newlines);
     }
   prompt_last_screen_line = newlines;
   /* Draw the rest of the line (after the prompt) into invisible_line, keeping
      track of where the cursor is (cpos_buffer_position), the number of the
      line containing the cursor (lb_linenum), the last line number (lb_botlin
      and inv_botlin).
      It maintains an array of line breaks for display (inv_lbreaks).
      This handles expanding tabs for display and displaying meta characters. */
   lb_linenum = 0;
 #if defined (HANDLE_MULTIBYTE)
   in = 0;
   if (mb_cur_max > 1 && rl_byte_oriented == 0)
     {
       memset (&ps, 0, sizeof (mbstate_t));
       if (_rl_utf8locale && UTF8_SINGLEBYTE(rl_line_buffer[0]))
     {
       wc = (WCHAR_T)rl_line_buffer[0];
       wc_bytes = 1;
     }
       else
     wc_bytes = MBRTOWC (&wc, rl_line_buffer, rl_end, &ps);
     }
   else
     wc_bytes = 1;
   while (in < rl_end)
 #else
   for (in = 0; in < rl_end; in++)
 #endif
     {
       if (in == hl_begin)
     cur_face = FACE_STANDOUT;
       else if (in == hl_end)
     cur_face = FACE_NORMAL;
       c = (unsigned char)rl_line_buffer[in];
 #if defined (HANDLE_MULTIBYTE)
       if (mb_cur_max > 1 && rl_byte_oriented == 0)
     {
       if (MB_INVALIDCH (wc_bytes))
         {
           /* Byte sequence is invalid or shortened.  Assume that the
              first byte represents a character. */
           wc_bytes = 1;
           /* Assume that a character occupies a single column. */
           wc_width = 1;
           memset (&ps, 0, sizeof (mbstate_t));
         }
       else if (MB_NULLWCH (wc_bytes))
         break;          /* Found '\0' */
       else
         {
           temp = WCWIDTH (wc);
           wc_width = (temp >= 0) ? temp : 1;
         }
     }
 #endif
       if (in == rl_point)
     {
       cpos_buffer_position = out;
       lb_linenum = newlines;
     }
 #if defined (HANDLE_MULTIBYTE)
       if (META_CHAR (c) && _rl_output_meta_chars == 0)  /* XXX - clean up */
 #else
       if (META_CHAR (c))
 #endif
     {
       if (_rl_output_meta_chars == 0)
         {
           char obuf[5];
           int olen;
           olen = sprintf (obuf, "\\%o", c);
           if (lpos + olen >= _rl_screenwidth)
         {
           temp = _rl_screenwidth - lpos;
           CHECK_INV_LBREAKS ();
           inv_lbreaks[++newlines] = out + temp;
 #if defined (HANDLE_MULTIBYTE)
           line_state_invisible->wrapped_line[newlines] = _rl_wrapped_multicolumn;
 #endif
           lpos = olen - temp;
         }
           else
         lpos += olen;
           for (temp = 0; temp < olen; temp++)
         {
           invis_addc (&out, obuf[temp], cur_face);
           CHECK_LPOS ();
         }
         }
       else
         {
           invis_addc (&out, c, cur_face);
           CHECK_LPOS();
         }
     }
 #if defined (DISPLAY_TABS)
       else if (c == '\t')
     {
       register int newout;
       newout = out + 8 - lpos % 8;
       temp = newout - out;
       if (lpos + temp >= _rl_screenwidth)
         {
           register int temp2;
           temp2 = _rl_screenwidth - lpos;
           CHECK_INV_LBREAKS ();
           inv_lbreaks[++newlines] = out + temp2;
 #if defined (HANDLE_MULTIBYTE)
           line_state_invisible->wrapped_line[newlines] = _rl_wrapped_multicolumn;
 #endif
           lpos = temp - temp2;
           while (out < newout)
         invis_addc (&out, ' ', cur_face);
         }
       else
         {
           while (out < newout)
         invis_addc (&out, ' ', cur_face);
           lpos += temp;
         }
     }
 #endif
       else if (c == '\n' && _rl_horizontal_scroll_mode == 0 && _rl_term_up && *_rl_term_up)
     {
       invis_addc (&out, '\0', cur_face);
       CHECK_INV_LBREAKS ();
       inv_lbreaks[++newlines] = out;
 #if defined (HANDLE_MULTIBYTE)
       line_state_invisible->wrapped_line[newlines] = _rl_wrapped_multicolumn;
 #endif
       lpos = 0;
     }
       else if (CTRL_CHAR (c) || c == RUBOUT)
     {
       invis_addc (&out, '^', cur_face);
       CHECK_LPOS();
       invis_addc (&out, CTRL_CHAR (c) ? UNCTRL (c) : '?', cur_face);
       CHECK_LPOS();
     }
       else
     {
 #if defined (HANDLE_MULTIBYTE)
       if (mb_cur_max > 1 && rl_byte_oriented == 0)
         {
           register int i;
           _rl_wrapped_multicolumn = 0;
           if (_rl_screenwidth < lpos + wc_width)
         for (i = lpos; i < _rl_screenwidth; i++)
           {
             /* The space will be removed in update_line() */
             invis_addc (&out, ' ', cur_face);
             _rl_wrapped_multicolumn++;
             CHECK_LPOS();
           }
           if (in == rl_point)
         {
           cpos_buffer_position = out;
           lb_linenum = newlines;
         }
           for (i = in; i < in+wc_bytes; i++)
         invis_addc (&out, rl_line_buffer[i], cur_face);
           for (i = 0; i < wc_width; i++)
         CHECK_LPOS();
         }
       else
         {
           invis_addc (&out, c, cur_face);
           CHECK_LPOS();
         }
 #else
       invis_addc (&out, c, cur_face);
       CHECK_LPOS();
 #endif
     }
 #if defined (HANDLE_MULTIBYTE)
       if (mb_cur_max > 1 && rl_byte_oriented == 0)
     {
       in += wc_bytes;
       if (_rl_utf8locale && UTF8_SINGLEBYTE(rl_line_buffer[in]))
         {
           wc = (WCHAR_T)rl_line_buffer[in];
           wc_bytes = 1;
           memset (&ps, 0, sizeof (mbstate_t));  /* re-init state */
         }
       else
         wc_bytes = MBRTOWC (&wc, rl_line_buffer + in, rl_end - in, &ps);
     }
       else
         in++;
 #endif
     }
   invis_nul (&out);
   line_totbytes = out;
   if (cpos_buffer_position < 0)
     {
       cpos_buffer_position = out;
       lb_linenum = newlines;
     }
   /* If we are switching from one line to multiple wrapped lines, we don't
      want to do a dumb update (or we want to make it smarter). */
   if (_rl_quick_redisplay && newlines > 0)
     _rl_quick_redisplay = 0;
   inv_botlin = lb_botlin = _rl_inv_botlin = newlines;
   CHECK_INV_LBREAKS ();
   inv_lbreaks[newlines+1] = out;
 #if defined (HANDLE_MULTIBYTE)
   /* This should be 0 anyway */
   line_state_invisible->wrapped_line[newlines+1] = _rl_wrapped_multicolumn;
 #endif
   cursor_linenum = lb_linenum;
   /* CPOS_BUFFER_POSITION == position in buffer where cursor should be placed.
      CURSOR_LINENUM == line number where the cursor should be placed. */
   /* PWP: now is when things get a bit hairy.  The visible and invisible
      line buffers are really multiple lines, which would wrap every
      (screenwidth - 1) characters.  Go through each in turn, finding
      the changed region and updating it.  The line order is top to bottom. */
   /* If we can move the cursor up and down, then use multiple lines,
      otherwise, let long lines display in a single terminal line, and
      horizontally scroll it. */
   displaying_prompt_first_line = 1;
   if (_rl_horizontal_scroll_mode == 0 && _rl_term_up && *_rl_term_up)
     {
       int nleft, pos, changed_screen_line, tx;
       if (!rl_display_fixed || forced_display)
     {
       forced_display = 0;
       /* If we have more than a screenful of material to display, then
          only display a screenful.  We should display the last screen,
          not the first.  */
       if (out >= _rl_screenchars)
         {
 #if defined (HANDLE_MULTIBYTE)
           if (mb_cur_max > 1 && rl_byte_oriented == 0)
         out = _rl_find_prev_mbchar (invisible_line, _rl_screenchars, MB_FIND_ANY);
           else
 #endif
         out = _rl_screenchars - 1;
         }
       /* The first line is at character position 0 in the buffer.  The
          second and subsequent lines start at inv_lbreaks[N], offset by
          OFFSET (which has already been calculated above).  */
 #define INVIS_FIRST()   (prompt_physical_chars > _rl_screenwidth ? prompt_invis_chars_first_line : wrap_offset)
 #define WRAP_OFFSET(line, offset)  ((line == 0) \
                     ? (offset ? INVIS_FIRST() : 0) \
                     : ((line == prompt_last_screen_line) ? wrap_offset-prompt_invis_chars_first_line : 0))
 #define W_OFFSET(line, offset) ((line) == 0 ? offset : 0)
 #define VIS_LLEN(l) ((l) > _rl_vis_botlin ? 0 : (vis_lbreaks[l+1] - vis_lbreaks[l]))
 #define INV_LLEN(l) (inv_lbreaks[l+1] - inv_lbreaks[l])
 #define VIS_CHARS(line) (visible_line + vis_lbreaks[line])
 #define VIS_FACE(line) (vis_face + vis_lbreaks[line])
 #define VIS_LINE(line) ((line) > _rl_vis_botlin) ? "" : VIS_CHARS(line)
 #define VIS_LINE_FACE(line) ((line) > _rl_vis_botlin) ? "" : VIS_FACE(line)
 #define INV_LINE(line) (invisible_line + inv_lbreaks[line])
 #define INV_LINE_FACE(line) (inv_face + inv_lbreaks[line])
 #define OLD_CPOS_IN_PROMPT() (cpos_adjusted == 0 && \
             _rl_last_c_pos != o_cpos && \
             _rl_last_c_pos > wrap_offset && \
             o_cpos < prompt_last_invisible)
       /* We don't want to highlight anything that's going to be off the top
          of the display; if the current line takes up more than an entire
         screen, just mark the lines that won't be displayed as having a
         `normal' face.
         It's imperfect, but better than display corruption. */
       if (rl_mark_active_p () && inv_botlin > _rl_screenheight)
         {
           int extra;
           extra = inv_botlin - _rl_screenheight;
           for (linenum = 0; linenum <= extra; linenum++)
         norm_face (INV_LINE_FACE(linenum), INV_LLEN (linenum));
         }
       /* For each line in the buffer, do the updating display. */
       for (linenum = 0; linenum <= inv_botlin; linenum++)
         {
           /* This can lead us astray if we execute a program that changes
          the locale from a non-multibyte to a multibyte one. */
           o_cpos = _rl_last_c_pos;
           cpos_adjusted = 0;
           update_line (VIS_LINE(linenum), VIS_LINE_FACE(linenum),
                INV_LINE(linenum), INV_LINE_FACE(linenum),
                linenum,
                VIS_LLEN(linenum), INV_LLEN(linenum), inv_botlin);
           /* update_line potentially changes _rl_last_c_pos, but doesn't
          take invisible characters into account, since _rl_last_c_pos
          is an absolute cursor position in a multibyte locale.  We
          choose to (mostly) compensate for that here, rather than
          change update_line itself.  There are several cases in which
          update_line adjusts _rl_last_c_pos itself (so it can pass
          _rl_move_cursor_relative accurate values); it communicates
          this back by setting cpos_adjusted.  If we assume that
          _rl_last_c_pos is correct (an absolute cursor position) each
          time update_line is called, then we can assume in our
          calculations that o_cpos does not need to be adjusted by
          wrap_offset. */
           if (linenum == 0 && (mb_cur_max > 1 && rl_byte_oriented == 0) && OLD_CPOS_IN_PROMPT())
         _rl_last_c_pos -= prompt_invis_chars_first_line;    /* XXX - was wrap_offset */
           else if (cpos_adjusted == 0 &&
             linenum == prompt_last_screen_line &&
             prompt_physical_chars > _rl_screenwidth &&
             (mb_cur_max > 1 && rl_byte_oriented == 0) &&
             _rl_last_c_pos != o_cpos &&
             _rl_last_c_pos > (prompt_last_invisible - _rl_screenwidth - prompt_invis_chars_first_line)) /* XXX - rethink this last one */
         /* This assumes that all the invisible characters are split
            between the first and last lines of the prompt, if the
            prompt consumes more than two lines. It's usually right */
         /* XXX - not sure this is ever executed */
         _rl_last_c_pos -= (wrap_offset-prompt_invis_chars_first_line);
           /* If this is the line with the prompt, we might need to
          compensate for invisible characters in the new line. Do
          this only if there is not more than one new line (which
          implies that we completely overwrite the old visible line)
          and the new line is shorter than the old.  Make sure we are
          at the end of the new line before clearing. */
           if (linenum == 0 &&
           inv_botlin == 0 && _rl_last_c_pos == out &&
           (wrap_offset > visible_wrap_offset) &&
           (_rl_last_c_pos < visible_first_line_len))
         {
           if (mb_cur_max > 1 && rl_byte_oriented == 0)
             nleft = _rl_screenwidth - _rl_last_c_pos;
           else
             nleft = _rl_screenwidth + wrap_offset - _rl_last_c_pos;
           if (nleft)
             _rl_clear_to_eol (nleft);
         }
 #if 0
           /* This segment is intended to handle the case where the old
          visible prompt has invisible characters and the new line
          to be displayed needs to clear the rest of the old characters
          out (e.g., when printing the i-search prompt): in general,
          the case of the new line being shorter than the old.  We need
          to be at the end of the new line and the old line needs to be
          longer than the current cursor position. It's not perfect,
          since it uses the byte length of the first line, but this will
          at worst result in some extra clear-to-end-of-lines. We can't
          use the prompt length variables because they may not
          correspond to the visible line (see printing the i-search
          prompt above). The tests for differing numbers of invisible
          characters may not matter and can probably be removed. */
           else if (linenum == 0 &&
                linenum == prompt_last_screen_line &&
                _rl_last_c_pos == out &&
                _rl_last_c_pos < visible_first_line_len &&
                visible_wrap_offset &&
                visible_wrap_offset != wrap_offset)
         {
           if (mb_cur_max > 1 && rl_byte_oriented == 0)
             nleft = _rl_screenwidth - _rl_last_c_pos;
           else
             nleft = _rl_screenwidth + wrap_offset - _rl_last_c_pos;
           if (nleft)
             _rl_clear_to_eol (nleft);
         }
 #endif
           /* Since the new first line is now visible, save its length. */
           if (linenum == 0)
         visible_first_line_len = (inv_botlin > 0) ? inv_lbreaks[1] : out - wrap_offset;
         }
       /* We may have deleted some lines.  If so, clear the left over
          blank ones at the bottom out. */
       if (_rl_vis_botlin > inv_botlin)
         {
           char *tt;
           for (; linenum <= _rl_vis_botlin; linenum++)
         {
           tt = VIS_CHARS (linenum);
           _rl_move_vert (linenum);
           _rl_move_cursor_relative (0, tt, VIS_FACE(linenum));
           _rl_clear_to_eol
             ((linenum == _rl_vis_botlin) ? strlen (tt) : _rl_screenwidth);
         }
         }
       _rl_vis_botlin = inv_botlin;
       /* CHANGED_SCREEN_LINE is set to 1 if we have moved to a
          different screen line during this redisplay. */
       changed_screen_line = _rl_last_v_pos != cursor_linenum;
       if (changed_screen_line)
         {
           _rl_move_vert (cursor_linenum);
           /* If we moved up to the line with the prompt using _rl_term_up,
          the physical cursor position on the screen stays the same,
          but the buffer position needs to be adjusted to account
          for invisible characters. */
           if ((mb_cur_max == 1 || rl_byte_oriented) && cursor_linenum == 0 && wrap_offset)
         _rl_last_c_pos += wrap_offset;
         }
       /* Now we move the cursor to where it needs to be.  First, make
          sure we are on the correct line (cursor_linenum). */
       /* We have to reprint the prompt if it contains invisible
          characters, since it's not generally OK to just reprint
          the characters from the current cursor position.  But we
          only need to reprint it if the cursor is before the last
          invisible character in the prompt string. */
       /* XXX - why not use local_prompt_len? */
       nleft = prompt_visible_length + wrap_offset;
       if (cursor_linenum == 0 && wrap_offset > 0 && _rl_last_c_pos > 0 &&
           _rl_last_c_pos < PROMPT_ENDING_INDEX && local_prompt)
         {
           _rl_cr ();
           if (modmark)
         _rl_output_some_chars ("*", 1);
           _rl_output_some_chars (local_prompt, nleft);
           if (mb_cur_max > 1 && rl_byte_oriented == 0)
         _rl_last_c_pos = _rl_col_width (local_prompt, 0, nleft, 1) - wrap_offset + modmark;
           else
         _rl_last_c_pos = nleft + modmark;
         }
       /* Where on that line?  And where does that line start
          in the buffer? */
       pos = inv_lbreaks[cursor_linenum];
       /* nleft == number of characters (bytes) in the line buffer between
          the start of the line and the desired cursor position. */
       nleft = cpos_buffer_position - pos;
       /* NLEFT is now a number of characters in a buffer.  When in a
          multibyte locale, however, _rl_last_c_pos is an absolute cursor
          position that doesn't take invisible characters in the prompt
          into account.  We use a fudge factor to compensate. */
       /* Since _rl_backspace() doesn't know about invisible characters in
          the prompt, and there's no good way to tell it, we compensate for
          those characters here and call _rl_backspace() directly if
          necessary */
       if (wrap_offset && cursor_linenum == 0 && nleft < _rl_last_c_pos)
         {
           /* TX == new physical cursor position in multibyte locale. */
           if (mb_cur_max > 1 && rl_byte_oriented == 0)
         tx = _rl_col_width (&visible_line[pos], 0, nleft, 1) - visible_wrap_offset;
           else
         tx = nleft;
           if (tx >= 0 && _rl_last_c_pos > tx)
         {
               _rl_backspace (_rl_last_c_pos - tx);  /* XXX */
               _rl_last_c_pos = tx;
         }
         }
       /* We need to note that in a multibyte locale we are dealing with
          _rl_last_c_pos as an absolute cursor position, but moving to a
          point specified by a buffer position (NLEFT) that doesn't take
          invisible characters into account. */
       if (mb_cur_max > 1 && rl_byte_oriented == 0)
         _rl_move_cursor_relative (nleft, &invisible_line[pos], &inv_face[pos]);
       else if (nleft != _rl_last_c_pos)
         _rl_move_cursor_relative (nleft, &invisible_line[pos], &inv_face[pos]);
     }
     }
   else              /* Do horizontal scrolling. Much simpler */
     {
 #define M_OFFSET(margin, offset) ((margin) == 0 ? offset : 0)
       int lmargin, ndisp, nleft, phys_c_pos, t;
       /* Always at top line. */
       _rl_last_v_pos = 0;
       /* Compute where in the buffer the displayed line should start.  This
      will be LMARGIN. */
       /* The number of characters that will be displayed before the cursor. */
       ndisp = cpos_buffer_position - wrap_offset;
       nleft  = prompt_visible_length + wrap_offset;
       /* Where the new cursor position will be on the screen.  This can be
      longer than SCREENWIDTH; if it is, lmargin will be adjusted. */
       phys_c_pos = cpos_buffer_position - (last_lmargin ? last_lmargin : wrap_offset);
       t = _rl_screenwidth / 3;
       /* If the number of characters had already exceeded the screenwidth,
      last_lmargin will be > 0. */
       /* If the number of characters to be displayed is more than the screen
      width, compute the starting offset so that the cursor is about
      two-thirds of the way across the screen. */
       if (phys_c_pos > _rl_screenwidth - 2)
     {
       lmargin = cpos_buffer_position - (2 * t);
       if (lmargin < 0)
         lmargin = 0;
       /* If the left margin would be in the middle of a prompt with
          invisible characters, don't display the prompt at all. */
       if (wrap_offset && lmargin > 0 && lmargin < nleft)
         lmargin = nleft;
     }
       else if (ndisp < _rl_screenwidth - 2)     /* XXX - was -1 */
     lmargin = 0;
       else if (phys_c_pos < 1)
     {
       /* If we are moving back towards the beginning of the line and
          the last margin is no longer correct, compute a new one. */
       lmargin = ((cpos_buffer_position - 1) / t) * t;   /* XXX */
       if (wrap_offset && lmargin > 0 && lmargin < nleft)
         lmargin = nleft;
     }
       else
     lmargin = last_lmargin;
       displaying_prompt_first_line = lmargin < nleft;
       /* If the first character on the screen isn't the first character
      in the display line, indicate this with a special character. */
       if (lmargin > 0)
     invisible_line[lmargin] = '<';
       /* If SCREENWIDTH characters starting at LMARGIN do not encompass
      the whole line, indicate that with a special character at the
      right edge of the screen.  If LMARGIN is 0, we need to take the
      wrap offset into account. */
       t = lmargin + M_OFFSET (lmargin, wrap_offset) + _rl_screenwidth;
       if (t > 0 && t < out)
     invisible_line[t - 1] = '>';
       if (rl_display_fixed == 0 || forced_display || lmargin != last_lmargin)
     {
       forced_display = 0;
       o_cpos = _rl_last_c_pos;
       cpos_adjusted = 0;
       update_line (&visible_line[last_lmargin], &vis_face[last_lmargin],
                &invisible_line[lmargin], &inv_face[lmargin],
                0,
                _rl_screenwidth + visible_wrap_offset,
                _rl_screenwidth + (lmargin ? 0 : wrap_offset),
                0);
       if ((mb_cur_max > 1 && rl_byte_oriented == 0) &&
         displaying_prompt_first_line && OLD_CPOS_IN_PROMPT())
         _rl_last_c_pos -= prompt_invis_chars_first_line;    /* XXX - was wrap_offset */
       /* If the visible new line is shorter than the old, but the number
          of invisible characters is greater, and we are at the end of
          the new line, we need to clear to eol. */
       t = _rl_last_c_pos - M_OFFSET (lmargin, wrap_offset);
       if ((M_OFFSET (lmargin, wrap_offset) > visible_wrap_offset) &&
           (_rl_last_c_pos == out) && displaying_prompt_first_line &&
           t < visible_first_line_len)
         {
           nleft = _rl_screenwidth - t;
           _rl_clear_to_eol (nleft);
         }
       visible_first_line_len = out - lmargin - M_OFFSET (lmargin, wrap_offset);
       if (visible_first_line_len > _rl_screenwidth)
         visible_first_line_len = _rl_screenwidth;
       _rl_move_cursor_relative (cpos_buffer_position - lmargin, &invisible_line[lmargin], &inv_face[lmargin]);
       last_lmargin = lmargin;
     }
     }
   fflush (rl_outstream);
   /* Swap visible and non-visible lines. */
   {
     struct line_state *vtemp = line_state_visible;
     line_state_visible = line_state_invisible;
     line_state_invisible = vtemp;
     rl_display_fixed = 0;
     /* If we are displaying on a single line, and last_lmargin is > 0, we
        are not displaying any invisible characters, so set visible_wrap_offset
        to 0. */
     if (_rl_horizontal_scroll_mode && last_lmargin)
       visible_wrap_offset = 0;
     else
       visible_wrap_offset = wrap_offset;
     _rl_quick_redisplay = 0;
   }
   RL_UNSETSTATE (RL_STATE_REDISPLAYING);
   _rl_release_sigint ();
 }
References _rl_backspace(), _rl_block_sigint(), _rl_clear_to_eol(), _rl_col_width, _rl_cr(), _rl_echoing_p, _rl_find_prev_mbchar, _rl_horizontal_scroll_mode, _rl_inv_botlin, _rl_last_c_pos, _rl_last_v_pos, _rl_mark_modified_lines, _rl_move_cursor_relative(), _rl_move_vert(), _rl_output_meta_chars, _rl_output_some_chars(), _rl_quick_redisplay, _rl_release_sigint(), _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_up, _rl_utf8locale, _rl_vis_botlin, c, CHECK_INV_LBREAKS, CHECK_LPOS, cpos_adjusted, cpos_buffer_position, cr(), CTRL_CHAR, current_history(), displaying_prompt_first_line, FACE_NORMAL, FACE_STANDOUT, fflush(), forced_display, horizontal_scrolling_autoset, i, init_line_structures(), inv_face, inv_lbreaks, INV_LINE, INV_LINE_FACE, INV_LLEN, invis_addc(), invis_adds(), invis_nul(), invisible_line, last_lmargin, line_size, line_state_invisible, line_state_visible, line_structures_initialized, line_totbytes, local_prompt, local_prompt_len, local_prompt_newlines, local_prompt_prefix, M_OFFSET, MB_CUR_MAX, MB_FIND_ANY, MB_INVALIDCH, MB_NULLWCH, MBRTOWC, memset(), META_CHAR, modmark, norm_face(), num, obuf, OLD_CPOS_IN_PROMPT, out(), pos, PROMPT_ENDING_INDEX, prompt_invis_chars_first_line, prompt_last_invisible, prompt_last_screen_line, prompt_multibyte_chars, prompt_physical_chars, prompt_visible_length, rl_byte_oriented, rl_display_fixed, rl_display_prompt, rl_end, rl_line_buffer, rl_mark_active_p(), rl_on_new_line(), rl_outstream, rl_point, rl_prompt, RL_SETSTATE, RL_STATE_REDISPLAYING, rl_undo_list, RL_UNSETSTATE, RUBOUT, set_active_region(), sprintf(), strlen(), strrchr(), t, tt, UNCTRL, update_line(), UTF8_SINGLEBYTE, VIS_CHARS, vis_face, VIS_FACE, VIS_LINE, VIS_LINE_FACE, VIS_LLEN, visible_first_line_len, visible_line, visible_wrap_offset, WCHAR_T, and wrap_offset.
Referenced by readline_internal_setup().
rl_redraw_prompt_last_line()
void rl_redraw_prompt_last_line (void)
Definition at line 2699 of file display.c.
 {
   char *t;
   t = strrchr (rl_display_prompt, '\n');
   if (t)
     redraw_prompt (++t);
   else
     rl_forced_update_display ();
 }
References redraw_prompt(), rl_display_prompt, rl_forced_update_display(), strrchr(), and t.
Referenced by _rl_refresh_line().
rl_refresh_line()
int rl_refresh_line (int ignore1, int ignore2)
Definition at line 582 of file text.c.
 {
   _rl_refresh_line ();
   rl_display_fixed = 1;
   return 0;
 }
References _rl_refresh_line(), and rl_display_fixed.
Referenced by change_prompt(), rl_clear_screen(), and rl_tty_status().
rl_replace_line()
void rl_replace_line (const char * text, int clear_undo)
Definition at line 212 of file text.c.
 {
   int len;
   len = strlen (text);
   if (len >= rl_line_buffer_len)
     rl_extend_line_buffer (len);
   strcpy (rl_line_buffer, text);
   rl_end = len;
   if (clear_undo)
     rl_free_undo_list ();
   _rl_fix_point (1);
 }
References _rl_fix_point(), rl_end, rl_extend_line_buffer(), rl_free_undo_list(), rl_line_buffer, rl_line_buffer_len, strcpy(), strlen(), and text.
Referenced by _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_revert_previous_lines(), rl_maybe_unsave_line(), and rl_replace_from_history().
rl_reset_after_signal()
void rl_reset_after_signal (void)
Definition at line 578 of file signals.c.
 {
   if (rl_prep_term_function)
     (*rl_prep_term_function) (_rl_meta_flag);
   rl_set_signals ();
 }
References _rl_meta_flag, rl_prep_term_function, and rl_set_signals().
Referenced by _rl_handle_signal().
rl_reset_line_state()
int rl_reset_line_state (void)
Definition at line 3079 of file display.c.
 {
   rl_on_new_line ();
   rl_display_prompt = rl_prompt ? rl_prompt : "";
   forced_display = 1;
   return 0;
 }
References forced_display, rl_display_prompt, rl_on_new_line(), and rl_prompt.
Referenced by rl_initialize().
rl_reset_screen_size()
void rl_reset_screen_size (void)
Definition at line 380 of file terminal.c.
 {
   _rl_get_screen_size (fileno (rl_instream), 0);
 }
References _rl_get_screen_size(), fileno(), and rl_instream.
rl_reset_terminal()
int rl_reset_terminal (const char * terminal_name)
Definition at line 686 of file terminal.c.
 {
   _rl_screenwidth = _rl_screenheight = 0;
   _rl_init_terminal_io (terminal_name);
   return 0;
 }
References _rl_init_terminal_io(), _rl_screenheight, and _rl_screenwidth.
rl_resize_terminal()
void rl_resize_terminal (void)
Definition at line 392 of file terminal.c.
 {
   int width, height;
   width = _rl_screenwidth;
   height = _rl_screenheight;
   _rl_get_screen_size (fileno (rl_instream), 1);
   if (_rl_echoing_p && (width != _rl_screenwidth || height != _rl_screenheight))
     {
       if (CUSTOM_REDISPLAY_FUNC ())
     rl_forced_update_display ();
       else if (RL_ISSTATE(RL_STATE_REDISPLAYING) == 0)
     _rl_redisplay_after_sigwinch ();
     }
 }
References _rl_echoing_p, _rl_get_screen_size(), _rl_redisplay_after_sigwinch(), _rl_screenheight, _rl_screenwidth, CUSTOM_REDISPLAY_FUNC, fileno(), height(), rl_forced_update_display(), rl_instream, RL_ISSTATE, RL_STATE_REDISPLAYING, and width.
Referenced by _rl_signal_handler(), and main().
rl_restart_output()
int rl_restart_output (int count, int key)
Definition at line 740 of file rltty.c.
 {
 #if defined (__MINGW32__)
   return 0;
 #else /* !__MING32__ */
   int fildes = fileno (rl_outstream);
 #if defined (TIOCSTART)
 #if defined (apollo)
   ioctl (&fildes, TIOCSTART, 0);
 #else
   ioctl (fildes, TIOCSTART, 0);
 #endif /* apollo */
 #else /* !TIOCSTART */
 #  if defined (TERMIOS_TTY_DRIVER)
 #    if defined (__ksr1__)
   if (ksrflow)
     {
       ksrflow = 0;
       tcflow (fildes, TCOON);
     }
 #    else /* !ksr1 */
   tcflow (fildes, TCOON);       /* Simulate a ^Q. */
 #    endif /* !ksr1 */
 #  else /* !TERMIOS_TTY_DRIVER */
 #    if defined (TCXONC)
   ioctl (fildes, TCXONC, TCOON);
 #    endif /* TCXONC */
 #  endif /* !TERMIOS_TTY_DRIVER */
 #endif /* !TIOCSTART */
   return 0;
 #endif /* !__MINGW32__ */
 }
References fileno(), ioctl(), rl_outstream, tcflow(), TCOON, TCXONC, and TIOCSTART.
Referenced by _rl_clean_up_for_exit(), and prepare_terminal_settings().
rl_restore_prompt()
void rl_restore_prompt (void)
Definition at line 3114 of file display.c.
 {
   FREE (local_prompt);
   FREE (local_prompt_prefix);
   FREE (local_prompt_newlines);
   local_prompt = saved_local_prompt;
   local_prompt_prefix = saved_local_prefix;
   local_prompt_len = saved_local_length;
   local_prompt_newlines = saved_local_prompt_newlines;
   prompt_prefix_length = saved_prefix_length;
   prompt_last_invisible = saved_last_invisible;
   prompt_visible_length = saved_visible_length;
   prompt_invis_chars_first_line = saved_invis_chars_first_line;
   prompt_physical_chars = saved_physical_chars;
   /* can test saved_local_prompt to see if prompt info has been saved. */
   saved_local_prompt = saved_local_prefix = (char *)0;
   saved_local_length = 0;
   saved_last_invisible = saved_visible_length = saved_prefix_length = 0;
   saved_invis_chars_first_line = saved_physical_chars = 0;
   saved_local_prompt_newlines = 0;
 }
References FREE, local_prompt, local_prompt_len, local_prompt_newlines, local_prompt_prefix, prompt_invis_chars_first_line, prompt_last_invisible, prompt_physical_chars, prompt_prefix_length, prompt_visible_length, saved_invis_chars_first_line, saved_last_invisible, saved_local_length, saved_local_prefix, saved_local_prompt, saved_local_prompt_newlines, saved_physical_chars, saved_prefix_length, and saved_visible_length.
Referenced by _rl_arg_callback(), _rl_arg_dispatch(), _rl_arg_overflow(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_nsearch_abort(), _rl_nsearch_dosearch(), redraw_prompt(), and rl_clear_message().
rl_restore_state()
int rl_restore_state (struct readline_state * sp)
Definition at line 1499 of file readline.c.
 {
   if (sp == 0)
     return -1;
   rl_point = sp->point;
   rl_end = sp->end;
   rl_mark = sp->mark;
   the_line = rl_line_buffer = sp->buffer;
   rl_line_buffer_len = sp->buflen;
   rl_undo_list = sp->ul;
   rl_prompt = sp->prompt;
   rl_readline_state = sp->rlstate;
   rl_done = sp->done;
   _rl_keymap = sp->kmap;
   rl_last_func = sp->lastfunc;
   rl_insert_mode = sp->insmode;
   rl_editing_mode = sp->edmode;
   rl_executing_keyseq = sp->kseq;
   rl_key_sequence_length = sp->kseqlen;
   rl_instream = sp->inf;
   rl_outstream = sp->outf;
   rl_pending_input = sp->pendingin;
   rl_executing_macro = sp->macro;
   rl_catch_signals = sp->catchsigs;
   rl_catch_sigwinch = sp->catchsigwinch;
   rl_completion_entry_function = sp->entryfunc;
   rl_menu_completion_entry_function = sp->menuentryfunc;
   rl_ignore_some_completions_function = sp->ignorefunc;
   rl_attempted_completion_function = sp->attemptfunc;
   rl_completer_word_break_characters = sp->wordbreakchars;
   rl_deactivate_mark ();
   return (0);
 }
References _rl_keymap, rl_attempted_completion_function, rl_catch_signals, rl_catch_sigwinch, rl_completer_word_break_characters, rl_completion_entry_function, rl_deactivate_mark(), rl_done, rl_editing_mode, rl_end, rl_executing_keyseq, rl_executing_macro, rl_ignore_some_completions_function, rl_insert_mode, rl_instream, rl_key_sequence_length, rl_last_func, rl_line_buffer, rl_line_buffer_len, rl_mark, rl_menu_completion_entry_function, rl_outstream, rl_pending_input, rl_point, rl_prompt, rl_readline_state, rl_undo_list, sp, and the_line.
rl_reverse_search_history()
int rl_reverse_search_history (int sign, int key)
Definition at line 131 of file isearch.c.
 {
   return (rl_search_history (-sign, key));
 }
References rl_search_history().
Referenced by _rl_isearch_dispatch().
rl_revert_line()
int rl_revert_line (int count, int key)
Definition at line 330 of file undo.c.
 {
   if (rl_undo_list == 0)
     rl_ding ();
   else
     {
       while (rl_undo_list)
     rl_do_undo ();
 #if defined (VI_MODE)
       if (rl_editing_mode == vi_mode)
     rl_point = rl_mark = 0;     /* rl_end should be set correctly */
 #endif
     }
   return 0;
 }
References rl_ding(), rl_do_undo(), rl_editing_mode, rl_mark, rl_point, rl_undo_list, and vi_mode.
Referenced by readline_internal_teardown().
rl_rubout()
int rl_rubout (int count, int key)
Definition at line 1188 of file text.c.
 {
   if (count < 0)
     return (rl_delete (-count, key));
   if (!rl_point)
     {
       rl_ding ();
       return 1;
     }
   if (rl_insert_mode == RL_IM_OVERWRITE)
     return (_rl_overwrite_rubout (count, key));
   return (_rl_rubout_char (count, key));
 }
References _rl_overwrite_rubout(), _rl_rubout_char(), count, rl_delete(), rl_ding(), RL_IM_OVERWRITE, rl_insert_mode, and rl_point.
Referenced by _rl_bind_tty_special_chars(), _rl_isearch_dispatch(), rl_make_keymap(), and rl_vi_replace().
rl_rubout_or_delete()
int rl_rubout_or_delete (int count, int key)
Definition at line 1288 of file text.c.
 {
   if (rl_end != 0 && rl_point == rl_end)
     return (_rl_rubout_char (count, key));
   else
     return (rl_delete (count, key));
 }
References _rl_rubout_char(), count, rl_delete(), rl_end, and rl_point.
rl_save_prompt()
void rl_save_prompt (void)
Definition at line 3093 of file display.c.
 {
   saved_local_prompt = local_prompt;
   saved_local_prefix = local_prompt_prefix;
   saved_prefix_length = prompt_prefix_length;
   saved_local_length = local_prompt_len;
   saved_last_invisible = prompt_last_invisible;
   saved_visible_length = prompt_visible_length;
   saved_invis_chars_first_line = prompt_invis_chars_first_line;
   saved_physical_chars = prompt_physical_chars;
   saved_local_prompt_newlines = local_prompt_newlines;
   local_prompt = local_prompt_prefix = (char *)0;
   local_prompt_len = 0;
   local_prompt_newlines = (int *)0;
   prompt_last_invisible = prompt_visible_length = prompt_prefix_length = 0;
   prompt_invis_chars_first_line = prompt_physical_chars = 0;
 }
References local_prompt, local_prompt_len, local_prompt_newlines, local_prompt_prefix, prompt_invis_chars_first_line, prompt_last_invisible, prompt_physical_chars, prompt_prefix_length, prompt_visible_length, saved_invis_chars_first_line, saved_last_invisible, saved_local_length, saved_local_prefix, saved_local_prompt, saved_local_prompt_newlines, saved_physical_chars, saved_prefix_length, and saved_visible_length.
Referenced by _rl_arg_init(), _rl_isearch_init(), _rl_make_prompt_for_search(), redraw_prompt(), and rl_message().
rl_save_state()
int rl_save_state (struct readline_state * sp)
Definition at line 1459 of file readline.c.
 {
   if (sp == 0)
     return -1;
   sp->point = rl_point;
   sp->end = rl_end;
   sp->mark = rl_mark;
   sp->buffer = rl_line_buffer;
   sp->buflen = rl_line_buffer_len;
   sp->ul = rl_undo_list;
   sp->prompt = rl_prompt;
   sp->rlstate = rl_readline_state;
   sp->done = rl_done;
   sp->kmap = _rl_keymap;
   sp->lastfunc = rl_last_func;
   sp->insmode = rl_insert_mode;
   sp->edmode = rl_editing_mode;
   sp->kseq = rl_executing_keyseq;
   sp->kseqlen = rl_key_sequence_length;
   sp->inf = rl_instream;
   sp->outf = rl_outstream;
   sp->pendingin = rl_pending_input;
   sp->macro = rl_executing_macro;
   sp->catchsigs = rl_catch_signals;
   sp->catchsigwinch = rl_catch_sigwinch;
   sp->entryfunc = rl_completion_entry_function;
   sp->menuentryfunc = rl_menu_completion_entry_function;
   sp->ignorefunc = rl_ignore_some_completions_function;
   sp->attemptfunc = rl_attempted_completion_function;
   sp->wordbreakchars = rl_completer_word_break_characters;
   return (0);
 }
References _rl_keymap, rl_attempted_completion_function, rl_catch_signals, rl_catch_sigwinch, rl_completer_word_break_characters, rl_completion_entry_function, rl_done, rl_editing_mode, rl_end, rl_executing_keyseq, rl_executing_macro, rl_ignore_some_completions_function, rl_insert_mode, rl_instream, rl_key_sequence_length, rl_last_func, rl_line_buffer, rl_line_buffer_len, rl_mark, rl_menu_completion_entry_function, rl_outstream, rl_pending_input, rl_point, rl_prompt, rl_readline_state, rl_undo_list, and sp.
rl_set_key()
int rl_set_key (const char * keyseq, rl_command_func_t * function, Keymap map)
Definition at line 308 of file bind.c.
 {
   return (rl_generic_bind (ISFUNC, keyseq, (char *)function, map));
 }
References ISFUNC, map, and rl_generic_bind().
rl_set_keyboard_input_timeout()
int rl_set_keyboard_input_timeout (int u)
Definition at line 352 of file input.c.
 {
   int o;
   o = _keyboard_input_timeout;
   if (u >= 0)
     _keyboard_input_timeout = u;
   return (o);
 }
References _keyboard_input_timeout.
Referenced by _rl_input_queued().
rl_set_keymap()
void rl_set_keymap (Keymap map)
Definition at line 2527 of file bind.c.
 {
   if (map)
     _rl_keymap = map;
 }
References _rl_keymap, and map.
Referenced by sv_keymap().
rl_set_keymap_from_edit_mode()
void rl_set_keymap_from_edit_mode (void)
Definition at line 2540 of file bind.c.
 {
   if (rl_editing_mode == emacs_mode)
     _rl_keymap = emacs_standard_keymap;
 #if defined (VI_MODE)
   else if (rl_editing_mode == vi_mode)
     _rl_keymap = vi_insertion_keymap;
 #endif /* VI_MODE */
 }
References _rl_keymap, emacs_mode, emacs_standard_keymap, rl_editing_mode, vi_insertion_keymap, and vi_mode.
Referenced by readline_initialize_everything(), and rl_re_read_init_file().
rl_set_keymap_name()
int rl_set_keymap_name (const char * name, Keymap map)
Definition at line 2477 of file bind.c.
 {
   int i, ni, mi;
   /* First check whether or not we're trying to rename a builtin keymap */
   mi = _rl_get_keymap_by_map (map);
   if (mi >= 0 && mi < NUM_BUILTIN_KEYMAPS)
     return -1;
   /* Then reject attempts to set one of the builtin names to a new map */
   ni = _rl_get_keymap_by_name (name);
   if (ni >= 0 && ni < NUM_BUILTIN_KEYMAPS)
     return -1;
   /* Renaming a keymap we already added */
   if (mi >= 0)  /* XXX - could be >= NUM_BUILTIN_KEYMAPS */
     {
       xfree (keymap_names[mi].name);
       keymap_names[mi].name = savestring (name);
       return mi;
     }
   /* Associating new keymap with existing name */
   if (ni >= 0)
     {
       keymap_names[ni].map = map;
       return ni;
     }
   for (i = 0; keymap_names[i].name; i++)
     ;
   if (keymap_names == builtin_keymap_names)
     {
       keymap_names = xmalloc ((i + 2) * sizeof (struct name_and_keymap));
       memcpy (keymap_names, builtin_keymap_names, i * sizeof (struct name_and_keymap));
     }
   else
     keymap_names = xrealloc (keymap_names, (i + 2) * sizeof (struct name_and_keymap));
   keymap_names[i].name = savestring (name);
   keymap_names[i].map = map;
   keymap_names[i+1].name = NULL;
   keymap_names[i+1].map = NULL;
   return i;
 }
References _rl_get_keymap_by_map(), _rl_get_keymap_by_name(), builtin_keymap_names, i, keymap_names, name_and_keymap::map, map, memcpy(), name_and_keymap::name, NULL, NUM_BUILTIN_KEYMAPS, savestring(), xfree, xmalloc, and xrealloc.
rl_set_mark()
int rl_set_mark (int count, int key)
Definition at line 1830 of file text.c.
 {
   return (_rl_set_mark_at_pos (rl_explicit_arg ? count : rl_point));
 }
References _rl_set_mark_at_pos(), count, rl_explicit_arg, and rl_point.
rl_set_paren_blink_timeout()
int rl_set_paren_blink_timeout (int u)
Definition at line 100 of file parens.c.
 {
   int o;
   o = _paren_blink_usec;
   if (u > 0)
     _paren_blink_usec = u;
   return (o);
 }
References _paren_blink_usec.
rl_set_prompt()
int rl_set_prompt (const char * prompt)
Definition at line 341 of file readline.c.
 {
   FREE (rl_prompt);
   rl_prompt = prompt ? savestring (prompt) : (char *)NULL;
   rl_display_prompt = rl_prompt ? rl_prompt : "";
   rl_visible_prompt_length = rl_expand_prompt (rl_prompt);
   return 0;
 }
References FREE, NULL, prompt, rl_display_prompt, rl_expand_prompt(), rl_prompt, rl_visible_prompt_length, and savestring().
Referenced by readline(), and rl_callback_handler_install().
rl_set_screen_size()
void rl_set_screen_size (int rows, int cols)
Definition at line 365 of file terminal.c.
 {
   _rl_set_screen_size (rows, cols);
 }
References _rl_set_screen_size(), cols, and rows.
Referenced by get_new_window_size().
rl_set_signals()
int rl_set_signals (void)
Definition at line 408 of file signals.c.
 {
   sighandler_cxt dummy;
   SigHandler *oh;
 #if defined (HAVE_POSIX_SIGNALS)
   static int sigmask_set = 0;
   static sigset_t bset, oset;
 #endif
 #if defined (HAVE_POSIX_SIGNALS)
   if (rl_catch_signals && sigmask_set == 0)
     {
       sigemptyset (&bset);
       sigaddset (&bset, SIGINT);
       sigaddset (&bset, SIGTERM);
 #if defined (SIGHUP)
       sigaddset (&bset, SIGHUP);
 #endif
 #if defined (SIGQUIT)
       sigaddset (&bset, SIGQUIT);
 #endif
 #if defined (SIGALRM)
       sigaddset (&bset, SIGALRM);
 #endif
 #if defined (SIGTSTP)
       sigaddset (&bset, SIGTSTP);
 #endif
 #if defined (SIGTTIN)
       sigaddset (&bset, SIGTTIN);
 #endif
 #if defined (SIGTTOU)
       sigaddset (&bset, SIGTTOU);
 #endif
       sigmask_set = 1;
     }
 #endif /* HAVE_POSIX_SIGNALS */
   if (rl_catch_signals && signals_set_flag == 0)
     {
 #if defined (HAVE_POSIX_SIGNALS)
       sigemptyset (&_rl_orig_sigset);
       sigprocmask (SIG_BLOCK, &bset, &_rl_orig_sigset);
 #endif
       rl_maybe_set_sighandler (SIGINT, rl_signal_handler, &old_int);
       rl_maybe_set_sighandler (SIGTERM, rl_signal_handler, &old_term);
 #if defined (SIGHUP)
       rl_maybe_set_sighandler (SIGHUP, rl_signal_handler, &old_hup);
 #endif
 #if defined (SIGQUIT)
       rl_maybe_set_sighandler (SIGQUIT, rl_signal_handler, &old_quit);
 #endif
 #if defined (SIGALRM)
       oh = rl_set_sighandler (SIGALRM, rl_signal_handler, &old_alrm);
       if (oh == (SigHandler *)SIG_IGN)
     rl_sigaction (SIGALRM, &old_alrm, &dummy);
 #if defined (HAVE_POSIX_SIGNALS) && defined (SA_RESTART)
       /* If the application using readline has already installed a signal
      handler with SA_RESTART, SIGALRM will cause reads to be restarted
      automatically, so readline should just get out of the way.  Since
      we tested for SIG_IGN above, we can just test for SIG_DFL here. */
       if (oh != (SigHandler *)SIG_DFL && (old_alrm.sa_flags & SA_RESTART))
     rl_sigaction (SIGALRM, &old_alrm, &dummy);
 #endif /* HAVE_POSIX_SIGNALS */
 #endif /* SIGALRM */
 #if defined (SIGTSTP)
       rl_maybe_set_sighandler (SIGTSTP, rl_signal_handler, &old_tstp);
 #endif /* SIGTSTP */
 #if defined (SIGTTOU)
       rl_maybe_set_sighandler (SIGTTOU, rl_signal_handler, &old_ttou);
 #endif /* SIGTTOU */
 #if defined (SIGTTIN)
       rl_maybe_set_sighandler (SIGTTIN, rl_signal_handler, &old_ttin);
 #endif /* SIGTTIN */
       signals_set_flag = 1;
 #if defined (HAVE_POSIX_SIGNALS)
       sigprocmask (SIG_SETMASK, &_rl_orig_sigset, (sigset_t *)NULL);
 #endif
     }
   else if (rl_catch_signals == 0)
     {
 #if defined (HAVE_POSIX_SIGNALS)
       sigemptyset (&_rl_orig_sigset);
       sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &_rl_orig_sigset);
 #endif
     }
 #if defined (SIGWINCH)
   if (rl_catch_sigwinch && sigwinch_set_flag == 0)
     {
       rl_maybe_set_sighandler (SIGWINCH, rl_sigwinch_handler, &old_winch);
       sigwinch_set_flag = 1;
     }
 #endif /* SIGWINCH */
   return 0;
 }
References NULL, old_alrm, old_hup, old_int, old_quit, old_term, old_tstp, old_ttin, old_ttou, rl_catch_signals, rl_catch_sigwinch, rl_maybe_set_sighandler(), rl_set_sighandler(), rl_sigaction(), rl_signal_handler(), sighandler_cxt::sa_flags, SA_RESTART, SIG_BLOCK, SIG_DFL, SIG_IGN, SIG_SETMASK, sigaddset(), SIGALRM, sigemptyset, SIGHUP, SIGINT, signals_set_flag, sigprocmask(), SIGQUIT, SIGTERM, SIGTSTP, SIGTTIN, SIGTTOU, SIGWINCH, and sigwinch_set_flag.
Referenced by _rl_callback_newline(), readline(), rl_callback_read_char(), and rl_reset_after_signal().
rl_set_timeout()
int rl_set_timeout (unsigned int secs, unsigned int usecs)
Definition at line 557 of file input.c.
 {
   timeout_duration.tv_sec = secs + usecs / USEC_PER_SEC;
   timeout_duration.tv_usec = usecs % USEC_PER_SEC;
   return 0;
 }
References timeout_duration, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
rl_show_char()
int rl_show_char (int c)
Definition at line 2904 of file display.c.
 {
   int n = 1;
   if (META_CHAR (c) && (_rl_output_meta_chars == 0))
     {
       fprintf (rl_outstream, "M-");
       n += 2;
       c = UNMETA (c);
     }
 #if defined (DISPLAY_TABS)
   if ((CTRL_CHAR (c) && c != '\t') || c == RUBOUT)
 #else
   if (CTRL_CHAR (c) || c == RUBOUT)
 #endif /* !DISPLAY_TABS */
     {
       fprintf (rl_outstream, "C-");
       n += 2;
       c = CTRL_CHAR (c) ? UNCTRL (c) : '?';
     }
   putc (c, rl_outstream);
   fflush (rl_outstream);
   return n;
 }
References _rl_output_meta_chars, c, CTRL_CHAR, fflush(), fprintf(), META_CHAR, n, putc, rl_outstream, RUBOUT, UNCTRL, and UNMETA.
rl_skip_csi_sequence()
int rl_skip_csi_sequence (int count, int key)
Definition at line 638 of file text.c.
 {
   int ch;
   RL_SETSTATE (RL_STATE_MOREINPUT);
   do
     ch = rl_read_key ();
   while (ch >= 0x20 && ch < 0x40);
   RL_UNSETSTATE (RL_STATE_MOREINPUT);
   return (ch < 0);
 }
References rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, and RL_UNSETSTATE.
rl_start_kbd_macro()
int rl_start_kbd_macro (int ignore1, int ignore2)
Definition at line 246 of file macro.c.
 {
   if (RL_ISSTATE (RL_STATE_MACRODEF))
     {
       _rl_abort_internal ();
       return 1;
     }
   if (rl_explicit_arg)
     {
       if (current_macro)
     _rl_with_macro_input (savestring (current_macro));
     }
   else
     current_macro_index = 0;
   RL_SETSTATE(RL_STATE_MACRODEF);
   return 0;
 }
References _rl_abort_internal(), _rl_with_macro_input(), current_macro, current_macro_index, rl_explicit_arg, RL_ISSTATE, RL_SETSTATE, RL_STATE_MACRODEF, and savestring().
rl_stop_output()
int rl_stop_output (int count, int key)
Definition at line 777 of file rltty.c.
 {
 #if defined (__MINGW32__)
   return 0;
 #else
   int fildes = fileno (rl_instream);
 #if defined (TIOCSTOP)
 # if defined (apollo)
   ioctl (&fildes, TIOCSTOP, 0);
 # else
   ioctl (fildes, TIOCSTOP, 0);
 # endif /* apollo */
 #else /* !TIOCSTOP */
 # if defined (TERMIOS_TTY_DRIVER)
 #  if defined (__ksr1__)
   ksrflow = 1;
 #  endif /* ksr1 */
   tcflow (fildes, TCOOFF);
 # else
 #   if defined (TCXONC)
   ioctl (fildes, TCXONC, TCOON);
 #   endif /* TCXONC */
 # endif /* !TERMIOS_TTY_DRIVER */
 #endif /* !TIOCSTOP */
   return 0;
 #endif /* !__MINGW32__ */
 }
References fileno(), ioctl(), rl_instream, tcflow(), TCOOFF, TCOON, TCXONC, and TIOCSTOP.
rl_stuff_char()
int rl_stuff_char (int key)
Definition at line 468 of file input.c.
 {
   if (ibuffer_space () == 0)
     return 0;
   if (key == EOF)
     {
       key = NEWLINE;
       rl_pending_input = EOF;
       RL_SETSTATE (RL_STATE_INPUTPENDING);
     }
   ibuffer[push_index++] = key;
 #if 0
   if (push_index >= ibuffer_len)
 #else
   if (push_index > ibuffer_len)
 #endif
     push_index = 0;
   return 1;
 }
References EOF, ibuffer, ibuffer_len, ibuffer_space(), NEWLINE, push_index, rl_pending_input, RL_SETSTATE, and RL_STATE_INPUTPENDING.
Referenced by _rl_isearch_dispatch(), _rl_vi_arg_dispatch(), rl_gather_tyi(), and rl_vi_subst().
rl_tab_insert()
int rl_tab_insert (int count, int key)
Definition at line 1088 of file text.c.
 {
   return (_rl_insert_char (count, '\t'));
 }
References _rl_insert_char(), and count.
rl_tilde_expand()
int rl_tilde_expand (int ignore, int key)
Definition at line 180 of file util.c.
 {
   register int start, end;
   char *homedir, *temp;
   int len;
   end = rl_point;
   start = end - 1;
   if (rl_point == rl_end && rl_line_buffer[rl_point] == '~')
     {
       homedir = tilde_expand ("~");
       _rl_replace_text (homedir, start, end);
       xfree (homedir);
       return (0);
     }
   else if (start >= 0 && rl_line_buffer[start] != '~')
     {
       for (; start >= 0 && !whitespace (rl_line_buffer[start]); start--)
         ;
       start++;
     }
   else if (start < 0)
     start = 0;
   end = start;
   do
     end++;
   while (whitespace (rl_line_buffer[end]) == 0 && end < rl_end);
   if (whitespace (rl_line_buffer[end]) || end >= rl_end)
     end--;
   /* If the first character of the current word is a tilde, perform
      tilde expansion and insert the result.  If not a tilde, do
      nothing. */
   if (rl_line_buffer[start] == '~')
     {
       len = end - start + 1;
       temp = (char *)xmalloc (len + 1);
       strncpy (temp, rl_line_buffer + start, len);
       temp[len] = '\0';
       homedir = tilde_expand (temp);
       xfree (temp);
       _rl_replace_text (homedir, start, end);
       xfree (homedir);
     }
   return (0);
 }
References _rl_replace_text(), end, rl_end, rl_line_buffer, rl_point, start, strncpy(), tilde_expand(), whitespace, xfree, and xmalloc.
Referenced by rl_vi_tilde_expand().
rl_timeout_remaining()
int rl_timeout_remaining (unsigned int * secs, unsigned int * usecs)
Definition at line 614 of file input.c.
 {
   struct timeval current_time;
   /* Return -1 when timeout is unset. */
   if (timerisunset (&timeout_point))
     {
       errno = 0;
       return -1;
     }
   /* Return -1 on error. errno is set by gettimeofday. */
   if (gettimeofday(&current_time, 0) != 0)
     return -1;
   /* Return 0 when timeout has already expired. */
   /* could use timercmp (&timeout_point, &current_time, <) here */
   if (current_time.tv_sec > timeout_point.tv_sec ||
     (current_time.tv_sec == timeout_point.tv_sec &&
      current_time.tv_usec >= timeout_point.tv_usec))
     return 0;
   if (secs && usecs)
     {
       *secs = timeout_point.tv_sec - current_time.tv_sec;
       *usecs = timeout_point.tv_usec - current_time.tv_usec;
       if (timeout_point.tv_usec < current_time.tv_usec)
     {
       (*secs)--;
       *usecs += USEC_PER_SEC;
     }
     }
   return 1;
 }
References errno, gettimeofday(), timeout_point, timerisunset, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
rl_translate_keyseq()
int rl_translate_keyseq (const char * seq, char * array, int * len)
Definition at line 523 of file bind.c.
 {
   register int i, l, temp;
   int has_control, has_meta;
   unsigned char c;
   has_control = 0;
   has_meta = 0;
   /* When there are incomplete prefixes \C- or \M- (has_control || has_meta)
      without base character at the end of SEQ, they are processed as the
      prefixes for '\0'.
   */
   for (i = l = 0; (c = seq[i]) || has_control || has_meta; i++)
     {
       /* Only backslashes followed by a non-null character are handled
      specially.  Trailing backslash (backslash followed by '\0') is
      processed as a normal character.
       */
       if (c == '\\' && seq[i + 1] != '\0')
     {
       c = seq[++i];
       /* Handle \C- and \M- prefixes. */
       if (c == 'C' && seq[i + 1] == '-')
         {
           i++;
           has_control = 1;
           continue;
         }
       else if (c == 'M' && seq[i + 1] == '-')
         {
           i++;
           has_meta = 1;
           continue;
         }
       /* Translate other backslash-escaped characters.  These are the
          same escape sequences that bash's `echo' and `printf' builtins
          handle, with the addition of \d -> RUBOUT.  A backslash
          preceding a character that is not special is stripped. */
       switch (c)
         {
         case 'a':
           c = '\007';
           break;
         case 'b':
           c = '\b';
           break;
         case 'd':
           c = RUBOUT;   /* readline-specific */
           break;
         case 'e':
           c = ESC;
           break;
         case 'f':
           c = '\f';
           break;
         case 'n':
           c = NEWLINE;
           break;
         case 'r':
           c = RETURN;
           break;
         case 't':
           c = TAB;
           break;
         case 'v':
           c = 0x0B;
           break;
         case '\\':
           c = '\\';
           break;
         case '0': case '1': case '2': case '3':
         case '4': case '5': case '6': case '7':
           i++;
           for (temp = 2, c -= '0'; ISOCTAL ((unsigned char)seq[i]) && temp--; i++)
             c = (c * 8) + OCTVALUE (seq[i]);
           i--;  /* auto-increment in for loop */
           c &= largest_char;
           break;
         case 'x':
           i++;
           for (temp = 2, c = 0; ISXDIGIT ((unsigned char)seq[i]) && temp--; i++)
             c = (c * 16) + HEXVALUE (seq[i]);
           if (temp == 2)
             c = 'x';
           i--;  /* auto-increment in for loop */
           c &= largest_char;
           break;
         default:    /* backslashes before non-special chars just add the char */
           c &= largest_char;
           break;    /* the backslash is stripped */
         }
     }
       /* Process \C- and \M- flags */
       if (has_control)
     {
       /* Special treatment for C-? */
       c = (c == '?') ? RUBOUT : CTRL (_rl_to_upper (c));
       has_control = 0;
     }
       if (has_meta)
     {
       c = META (c);
       has_meta = 0;
     }
       /* If convert-meta is turned on, convert a meta char to a key sequence  */
       if (META_CHAR (c) && _rl_convert_meta_chars_to_ascii)
     {
       array[l++] = ESC; /* ESC is meta-prefix */
       array[l++] = UNMETA (c);
     }
       else
     array[l++] = (c);
       /* Null characters may be processed for incomplete prefixes at the end of
      sequence */
       if (seq[i] == '\0')
     break;
     }
   *len = l;
   array[l] = '\0';
   return (0);
 }
References _rl_convert_meta_chars_to_ascii, _rl_to_upper(), c, CTRL, ESC, HEXVALUE, i, ISOCTAL, ISXDIGIT, l, largest_char, META, META_CHAR, NEWLINE, OCTVALUE, RETURN, RUBOUT, seq, TAB, and UNMETA.
Referenced by _rl_reset_region_color(), rl_bind_keyseq_if_unbound_in_map(), rl_generic_bind(), rl_macro_bind(), sv_emacs_modestr(), sv_isrchterm(), sv_vicmd_modestr(), and sv_viins_modestr().
rl_transpose_chars()
int rl_transpose_chars (int count, int key)
Definition at line 1603 of file text.c.
 {
 #if defined (HANDLE_MULTIBYTE)
   char *dummy;
   int i;
 #else
   char dummy[2];
 #endif
   int char_length, prev_point;
   if (count == 0)
     return 0;
   if (!rl_point || rl_end < 2)
     {
       rl_ding ();
       return 1;
     }
   rl_begin_undo_group ();
   if (rl_point == rl_end)
     {
       rl_point = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_NONZERO);
       count = 1;
     }
   prev_point = rl_point;
   rl_point = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_NONZERO);
 #if defined (HANDLE_MULTIBYTE)
   char_length = prev_point - rl_point;
   dummy = (char *)xmalloc (char_length + 1);
   for (i = 0; i < char_length; i++)
     dummy[i] = rl_line_buffer[rl_point + i];
   dummy[i] = '\0';
 #else
   dummy[0] = rl_line_buffer[rl_point];
   dummy[char_length = 1] = '\0';
 #endif
   rl_delete_text (rl_point, rl_point + char_length);
   rl_point = _rl_find_next_mbchar (rl_line_buffer, rl_point, count, MB_FIND_NONZERO);
   _rl_fix_point (0);
   rl_insert_text (dummy);
   rl_end_undo_group ();
 #if defined (HANDLE_MULTIBYTE)
   xfree (dummy);
 #endif
   return 0;
 }
References _rl_find_next_mbchar, _rl_fix_point(), count, i, MB_FIND_NONZERO, MB_PREVCHAR, rl_begin_undo_group(), rl_delete_text(), rl_ding(), rl_end, rl_end_undo_group(), rl_insert_text(), rl_line_buffer, rl_point, xfree, and xmalloc.
rl_transpose_words()
int rl_transpose_words (int count, int key)
Definition at line 1539 of file text.c.
 {
   char *word1, *word2;
   int w1_beg, w1_end, w2_beg, w2_end;
   int orig_point, orig_end;
   orig_point = rl_point;
   orig_end = rl_end;
   if (!count)
     return 0;
   /* Find the two words. */
   rl_forward_word (count, key);
   w2_end = rl_point;
   rl_backward_word (1, key);
   w2_beg = rl_point;
   rl_backward_word (count, key);
   w1_beg = rl_point;
   rl_forward_word (1, key);
   w1_end = rl_point;
   /* Do some check to make sure that there really are two words. */
   if ((w1_beg == w2_beg) || (w2_beg < w1_end))
     {
       rl_ding ();
       rl_point = orig_point;
       return 1;
     }
   /* Get the text of the words. */
   word1 = rl_copy_text (w1_beg, w1_end);
   word2 = rl_copy_text (w2_beg, w2_end);
   /* We are about to do many insertions and deletions.  Remember them
      as one operation. */
   rl_begin_undo_group ();
   /* Do the stuff at word2 first, so that we don't have to worry
      about word1 moving. */
   rl_point = w2_beg;
   rl_delete_text (w2_beg, w2_end);
   rl_insert_text (word1);
   rl_point = w1_beg;
   rl_delete_text (w1_beg, w1_end);
   rl_insert_text (word2);
   /* This is exactly correct since the text before this point has not
      changed in length. */
   rl_point = w2_end;
   rl_end = orig_end;        /* just make sure */
   /* I think that does it. */
   rl_end_undo_group ();
   xfree (word1);
   xfree (word2);
   return 0;
 }
References count, rl_backward_word(), rl_begin_undo_group(), rl_copy_text(), rl_delete_text(), rl_ding(), rl_end, rl_end_undo_group(), rl_forward_word(), rl_insert_text(), rl_point, and xfree.
rl_trim_arg_from_keyseq()
int rl_trim_arg_from_keyseq (const char * keyseq, size_t len, Keymap map)
Definition at line 889 of file bind.c.
 {
   register int i, j, parsing_digits;
   unsigned char ic;
   Keymap map0;
   if (map == 0)
     map = _rl_keymap;
   map0 = map;
   /* The digits following the initial one (e.g., the binding to digit-argument)
     or the optional `-' in a binding to digit-argument or universal-argument
     are not added to rl_executing_keyseq. This is basically everything read by
     rl_digit_loop. The parsing_digits logic is here in case they ever are. */
   for (i = j = parsing_digits = 0; keyseq && i < len; i++)
     {
       ic = keyseq[i];
       if (parsing_digits)
     {
       if (_rl_digit_p (ic))
         {
           j = i + 1;
           continue;
         }
       parsing_digits = 0;
     }
       if (map[ic].type == ISKMAP)
     {
       if (i + 1 == len)
         return -1;
       map = FUNCTION_TO_KEYMAP (map, ic);
       continue;
     }
       if (map[ic].type == ISFUNC)
     {
 #if defined (VI_MODE)
       if (map[ic].function != rl_digit_argument && map[ic].function != rl_universal_argument && map[ic].function != rl_vi_arg_digit)
 #else
       if (map[ic].function != rl_digit_argument && map[ic].function != rl_universal_argument)
 #endif
         return (j);
       /* We don't bother with a keyseq that is only a numeric argument */
       if (i + 1 == len)
         return -1;
       parsing_digits = 1;
       /* This logic should be identical to rl_digit_loop */
       /* We accept M-- as equivalent to M--1, C-u- as equivalent to C-u-1
          but set parsing_digits to 2 to note that we saw `-' */
       if (map[ic].function == rl_universal_argument && (i + 1 == '-'))
         {
           i++;
           parsing_digits = 2;
         }
       if (map[ic].function == rl_digit_argument && ic == '-')
         {
           parsing_digits = 2;
         }
       map = map0;
       j = i + 1;
     }
     }
   /* If we're still parsing digits by the time we get here, we don't allow a
      key sequence that consists solely of a numeric argument */
   return -1;
 }
References _rl_digit_p(), _rl_keymap, FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, j, map, rl_digit_argument(), rl_universal_argument(), rl_vi_arg_digit(), and type.
rl_tty_set_default_bindings()
void rl_tty_set_default_bindings (Keymap kmap)
Definition at line 910 of file rltty.c.
 {
   rltty_set_default_bindings (kmap);
 }
References rltty_set_default_bindings().
Referenced by readline_default_bindings(), and reset_default_bindings().
rl_tty_set_echoing()
int rl_tty_set_echoing (int u)
Definition at line 724 of file rltty.c.
 {
   int o;
   o = _rl_echoing_p;
   _rl_echoing_p = u;
   return o;
 }
References _rl_echoing_p.
rl_tty_status()
int rl_tty_status (int count, int key)
Definition at line 133 of file util.c.
 {
 #if defined (TIOCSTAT)
   ioctl (1, TIOCSTAT, (char *)0);
   rl_refresh_line (count, key);
 #else
   rl_ding ();
 #endif
   return 0;
 }
References count, ioctl(), rl_ding(), and rl_refresh_line().
rl_tty_unset_default_bindings()
void rl_tty_unset_default_bindings (Keymap kmap)
Definition at line 920 of file rltty.c.
 {
   /* Don't bother before we've saved the tty special chars at least once. */
   if (RL_ISSTATE(RL_STATE_TTYCSAVED) == 0)
     return;
   RESET_SPECIAL (_rl_tty_chars.t_erase);
   RESET_SPECIAL (_rl_tty_chars.t_kill);
 #  if defined (VLNEXT) && defined (TERMIOS_TTY_DRIVER)
   RESET_SPECIAL (_rl_tty_chars.t_lnext);
 #  endif /* VLNEXT && TERMIOS_TTY_DRIVER */
 #  if defined (VWERASE) && defined (TERMIOS_TTY_DRIVER)
   RESET_SPECIAL (_rl_tty_chars.t_werase);
 #  endif /* VWERASE && TERMIOS_TTY_DRIVER */
 }
References RESET_SPECIAL, RL_ISSTATE, RL_STATE_TTYCSAVED, _rl_tty_chars::t_erase, _rl_tty_chars::t_kill, _rl_tty_chars::t_lnext, and _rl_tty_chars::t_werase.
Referenced by reset_default_bindings(), and rl_prep_terminal().
rl_unbind_command_in_map()
int rl_unbind_command_in_map (const char * command, Keymap map)
Definition at line 278 of file bind.c.
 {
   rl_command_func_t *func;
   func = rl_named_function (command);
   if (func == 0)
     return 0;
   return (rl_unbind_function_in_map (func, map));
 }
References map, rl_named_function(), and rl_unbind_function_in_map().
rl_unbind_function_in_map()
int rl_unbind_function_in_map (rl_command_func_t * func, Keymap map)
Definition at line 254 of file bind.c.
 {
   register int i, rval;
   for (i = rval = 0; i < KEYMAP_SIZE; i++)
     {
       if (map[i].type == ISFUNC && map[i].function == func)
     {
       map[i].function = (rl_command_func_t *)NULL;
       rval = 1;
     }
       else if (map[i].type == ISKMAP)       /* TAG:readline-8.1 */
     {
       int r;
       r = rl_unbind_function_in_map (func, FUNCTION_TO_KEYMAP (map, i));
       if (r == 1)
         rval = 1;
     }
     }
   return rval;
 }
References FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, KEYMAP_SIZE, map, NULL, and type.
Referenced by rl_unbind_command_in_map().
rl_unbind_key()
int rl_unbind_key (int key)
Definition at line 240 of file bind.c.
 {
   return (rl_bind_key (key, (rl_command_func_t *)NULL));
 }
References NULL, and rl_bind_key().
rl_unbind_key_in_map()
int rl_unbind_key_in_map (int key, Keymap map)
Definition at line 247 of file bind.c.
 {
   return (rl_bind_key_in_map (key, (rl_command_func_t *)NULL, map));
 }
References map, NULL, and rl_bind_key_in_map().
rl_undo_command()
int rl_undo_command (int count, int key)
Definition at line 349 of file undo.c.
 {
   if (count < 0)
     return 0;   /* Nothing to do. */
   while (count)
     {
       if (rl_do_undo ())
     count--;
       else
     {
       rl_ding ();
       break;
     }
     }
   return 0;
 }
References count, rl_ding(), and rl_do_undo().
Referenced by rl_vi_undo().
rl_universal_argument()
int rl_universal_argument (int count, int key)
Definition at line 246 of file misc.c.
 {
   _rl_arg_init ();
   rl_numeric_arg *= 4;
   return (RL_ISSTATE (RL_STATE_CALLBACK) ? 0 : rl_digit_loop ());
 }
References _rl_arg_init(), rl_digit_loop(), RL_ISSTATE, rl_numeric_arg, and RL_STATE_CALLBACK.
Referenced by _rl_arg_dispatch(), _rl_vi_arg_dispatch(), and rl_trim_arg_from_keyseq().
rl_unix_filename_rubout()
int rl_unix_filename_rubout (int count, int key)
Definition at line 339 of file kill.c.
 {
   int orig_point, c;
   if (rl_point == 0)
     rl_ding ();
   else
     {
       orig_point = rl_point;
       if (count <= 0)
     count = 1;
       while (count--)
     {
       c = rl_line_buffer[rl_point - 1];
       /* First move backwards through whitespace */
       while (rl_point && whitespace (c))
         {
           rl_point--;
           c = rl_line_buffer[rl_point - 1];
         }
       /* Consume one or more slashes. */
       if (c == '/')
         {
           int i;
           i = rl_point - 1;
           while (i > 0 && c == '/')
         c = rl_line_buffer[--i];
           if (i == 0 || whitespace (c))
         {
           rl_point = i + whitespace (c);
           continue; /* slashes only */
         }
           c = '/';
         }
       while (rl_point && (whitespace (c) || c == '/'))
         {
           rl_point--;
           c = rl_line_buffer[rl_point - 1];
         }
       while (rl_point && (whitespace (c) == 0) && c != '/')
         {
           rl_point--;   /* XXX - multibyte? */
           c = rl_line_buffer[rl_point - 1];
         }
     }
       rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References c, count, emacs_mode, i, rl_ding(), rl_editing_mode, rl_kill_text(), rl_line_buffer, rl_mark, rl_point, and whitespace.
rl_unix_line_discard()
int rl_unix_line_discard (int count, int key)
Definition at line 406 of file kill.c.
 {
   if (rl_point == 0)
     rl_ding ();
   else
     {
       rl_kill_text (rl_point, 0);
       rl_point = 0;
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References emacs_mode, rl_ding(), rl_editing_mode, rl_kill_text(), rl_mark, and rl_point.
Referenced by _rl_bind_tty_special_chars(), _rl_nsearch_dispatch(), rl_vi_overstrike_kill_line(), and rl_vi_replace().
rl_unix_word_rubout()
int rl_unix_word_rubout (int count, int key)
Definition at line 307 of file kill.c.
 {
   int orig_point;
   if (rl_point == 0)
     rl_ding ();
   else
     {
       orig_point = rl_point;
       if (count <= 0)
     count = 1;
       while (count--)
     {
       while (rl_point && whitespace (rl_line_buffer[rl_point - 1]))
         rl_point--;
       while (rl_point && (whitespace (rl_line_buffer[rl_point - 1]) == 0))
         rl_point--;     /* XXX - multibyte? */
     }
       rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References count, emacs_mode, rl_ding(), rl_editing_mode, rl_kill_text(), rl_line_buffer, rl_mark, rl_point, and whitespace.
Referenced by _rl_bind_tty_special_chars(), _rl_isearch_dispatch(), and _rl_nsearch_dispatch().
rl_untranslate_keyseq()
char* rl_untranslate_keyseq (int seq)
Definition at line 685 of file bind.c.
 {
   static char kseq[16];
   int i, c;
   i = 0;
   c = seq;
   if (META_CHAR (c))
     {
       kseq[i++] = '\\';
       kseq[i++] = 'M';
       kseq[i++] = '-';
       c = UNMETA (c);
     }
   else if (c == ESC)
     {
       kseq[i++] = '\\';
       c = 'e';
     }
   else if (CTRL_CHAR (c))
     {
       kseq[i++] = '\\';
       kseq[i++] = 'C';
       kseq[i++] = '-';
       c = _rl_to_lower (UNCTRL (c));
     }
   else if (c == RUBOUT)
     {
       kseq[i++] = '\\';
       kseq[i++] = 'C';
       kseq[i++] = '-';
       c = '?';
     }
   if (c == ESC)
     {
       kseq[i++] = '\\';
       c = 'e';
     }
   else if (c == '\\' || c == '"')
     {
       kseq[i++] = '\\';
     }
   kseq[i++] = (unsigned char) c;
   kseq[i] = '\0';
   return kseq;
 }
References _rl_to_lower(), c, CTRL_CHAR, ESC, i, META_CHAR, RUBOUT, seq, UNCTRL, and UNMETA.
Referenced by fcopy(), rl_bind_key_if_unbound(), and rl_bind_key_if_unbound_in_map().
rl_upcase_word()
int rl_upcase_word (int count, int key)
Definition at line 1379 of file text.c.
 {
   return (rl_change_case (count, UpCase));
 }
References count, rl_change_case(), and UpCase.
rl_username_completion_function()
char* rl_username_completion_function (const char * text, int state)
Definition at line 2266 of file complete.c.
 {
 #if defined (__WIN32__) || defined (__OPENNT)
   return (char *)NULL;
 #else /* !__WIN32__ && !__OPENNT) */
   static char *username = (char *)NULL;
   static struct passwd *entry;
   static int namelen, first_char, first_char_loc;
   char *value;
   if (state == 0)
     {
       FREE (username);
       first_char = *text;
       first_char_loc = first_char == '~';
       username = savestring (&text[first_char_loc]);
       namelen = strlen (username);
 #if defined (HAVE_GETPWENT)
       setpwent ();
 #endif
     }
 #if defined (HAVE_GETPWENT)
   while (entry = getpwent ())
     {
       /* Null usernames should result in all users as possible completions. */
       if (namelen == 0 || (STREQN (username, entry->pw_name, namelen)))
     break;
     }
 #endif
   if (entry == 0)
     {
 #if defined (HAVE_GETPWENT)
       endpwent ();
 #endif
       return ((char *)NULL);
     }
   else
     {
       value = (char *)xmalloc (2 + strlen (entry->pw_name));
       *value = *text;
       strcpy (value + first_char_loc, entry->pw_name);
       if (first_char == '~')
     rl_filename_completion_desired = 1;
       return (value);
     }
 #endif /* !__WIN32__ && !__OPENNT */
 }
rl_variable_bind()
int rl_variable_bind (const char * name, const char * value)
Definition at line 2072 of file bind.c.
 {
   register int i;
   int   v;
   /* Check for simple variables first. */
   i = find_boolean_var (name);
   if (i >= 0)
     {
       *boolean_varlist[i].value = bool_to_int (value);
       if (boolean_varlist[i].flags & V_SPECIAL)
     hack_special_boolean_var (i);
       return 0;
     }
   i = find_string_var (name);
   /* For the time being, string names without a handler function are simply
      ignored. */
   if (i < 0 || string_varlist[i].set_func == 0)
     {
       if (i < 0)
     _rl_init_file_error ("%s: unknown variable name", name);
       return 0;
     }
   v = (*string_varlist[i].set_func) (value);
   if (v != 0)
     _rl_init_file_error ("%s: could not set value to `%s'", name, value);
   return v;
 }
References _rl_init_file_error(), bool_to_int(), boolean_varlist, find_boolean_var(), find_string_var(), flags, hack_special_boolean_var(), i, string_varlist, V_SPECIAL, and value.
Referenced by main(), and rl_parse_and_bind().
rl_variable_dumper()
void rl_variable_dumper (int print_readably)
Definition at line 3031 of file bind.c.
 {
   int i;
   char *v;
   for (i = 0; boolean_varlist[i].name; i++)
     {
       if (print_readably)
         fprintf (rl_outstream, "set %s %s\n", boolean_varlist[i].name,
                    *boolean_varlist[i].value ? "on" : "off");
       else
         fprintf (rl_outstream, "%s is set to `%s'\n", boolean_varlist[i].name,
                    *boolean_varlist[i].value ? "on" : "off");
     }
   for (i = 0; string_varlist[i].name; i++)
     {
       v = _rl_get_string_variable_value (string_varlist[i].name);
       if (v == 0)   /* _rl_isearch_terminators can be NULL */
     continue;
       if (print_readably)
         fprintf (rl_outstream, "set %s %s\n", string_varlist[i].name, v);
       else
         fprintf (rl_outstream, "%s is set to `%s'\n", string_varlist[i].name, v);
     }
 }
References _rl_get_string_variable_value(), boolean_varlist, fprintf(), i, name_and_keymap::name, rl_outstream, string_varlist, and value.
Referenced by rl_dump_variables().
rl_variable_value()
char* rl_variable_value (const char * name)
Definition at line 2054 of file bind.c.
 {
   register int i;
   /* Check for simple variables first. */
   i = find_boolean_var (name);
   if (i >= 0)
     return (*boolean_varlist[i].value ? "on" : "off");
   i = find_string_var (name);
   if (i >= 0)
     return (_rl_get_string_variable_value (string_varlist[i].name));
   /* Unknown variable names return NULL. */
   return (char *)NULL;
 }
References _rl_get_string_variable_value(), boolean_varlist, find_boolean_var(), find_string_var(), i, NULL, string_varlist, and value.
Referenced by parser_if().
rl_vi_append_eol()
int rl_vi_append_eol (int count, int key)
Definition at line 760 of file vi_mode.c.
 {
   rl_end_of_line (1, key);
   rl_vi_append_mode (1, key);
   return (0);
 }
References rl_end_of_line(), and rl_vi_append_mode().
rl_vi_append_mode()
int rl_vi_append_mode (int count, int key)
Definition at line 752 of file vi_mode.c.
 {
   _rl_vi_append_forward (key);
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References _rl_vi_append_forward(), rl_arg_sign, and rl_vi_start_inserting().
Referenced by rl_vi_append_eol(), and rl_yank_nth_arg_internal().
rl_vi_arg_digit()
int rl_vi_arg_digit (int count, int c)
Definition at line 917 of file vi_mode.c.
 {
   if (c == '0' && rl_numeric_arg == 1 && !rl_explicit_arg)
     return (rl_beg_of_line (1, c));
   else
     return (rl_digit_argument (count, c));
 }
References c, count, rl_beg_of_line(), rl_digit_argument(), rl_explicit_arg, and rl_numeric_arg.
Referenced by _rl_dispatch_subseq(), and rl_trim_arg_from_keyseq().
rl_vi_back_to_indent()
int rl_vi_back_to_indent (int count, int key)
Definition at line 1750 of file vi_mode.c.
 {
   rl_beg_of_line (1, key);
   while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     rl_point++;
   return (0);
 }
References rl_beg_of_line(), rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_first_print().
rl_vi_bracktype()
int rl_vi_bracktype (int c)
Definition at line 1984 of file vi_mode.c.
 {
   switch (c)
     {
     case '(': return  1;
     case ')': return -1;
     case '[': return  2;
     case ']': return -2;
     case '{': return  3;
     case '}': return -3;
     default:  return  0;
     }
 }
References c.
Referenced by rl_vi_match().
rl_vi_bWord()
int rl_vi_bWord (int count, int ignore)
Definition at line 557 of file vi_mode.c.
 {
   while (count-- && rl_point > 0)
     {
       /* If we are at the start of a word, move back to whitespace so
      we will go back to the start of the previous word. */
       if (!whitespace (rl_line_buffer[rl_point]) &&
       whitespace (rl_line_buffer[rl_point - 1]))
     rl_point--;
       while (rl_point > 0 && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_backup_point ();
       if (rl_point > 0)
     {
       do
         _rl_vi_backup_point ();
       while (rl_point > 0 && !whitespace (rl_line_buffer[rl_point]));
       if (rl_point > 0) /* hit whitespace */
         rl_point++;
       if (rl_point < 0)
         rl_point = 0;
     }
     }
   return (0);
 }
References _rl_vi_backup_point(), count, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_prev_word().
rl_vi_bword()
int rl_vi_bword (int count, int ignore)
Definition at line 649 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point > 0)
     {
       int prev_is_ident, cur_is_ident;
       /* If we are at the start of a word, move back to whitespace
      so we will go back to the start of the previous word. */
       if (!whitespace (rl_line_buffer[rl_point]) &&
       whitespace (rl_line_buffer[rl_point - 1]))
     if (--rl_point == 0)
       break;
       /* If this character and the previous character are `opposite', move
      back so we don't get messed up by the rl_point++ down there in
      the while loop.  Without this code, words like `l;' screw up the
      function. */
       cur_is_ident = _rl_isident (rl_line_buffer[rl_point]);
       opoint = _rl_vi_backup_point ();
       prev_is_ident = _rl_isident (rl_line_buffer[rl_point]);
       if ((cur_is_ident && !prev_is_ident) || (!cur_is_ident && prev_is_ident))
     ;   /* leave point alone, we backed it up one character */
       else
     rl_point = opoint;
       while (rl_point > 0 && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_backup_point ();
       if (rl_point > 0)
     {
       opoint = rl_point;
       if (_rl_isident (rl_line_buffer[rl_point]))
         do
           opoint = _rl_vi_backup_point ();
         while (rl_point > 0 && _rl_isident (rl_line_buffer[rl_point]));
       else
         do
           opoint = _rl_vi_backup_point ();
         while (rl_point > 0 && !_rl_isident (rl_line_buffer[rl_point]) &&
            !whitespace (rl_line_buffer[rl_point]));
       if (rl_point > 0)
         rl_point = opoint;
       if (rl_point < 0)
         rl_point = 0;
     }
     }
   return (0);
 }
References _rl_isident, _rl_vi_backup_point(), count, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_prev_word().
rl_vi_change_case()
int rl_vi_change_case (int count, int ignore)
Definition at line 981 of file vi_mode.c.
 {
   int c, p;
   /* Don't try this on an empty line. */
   if (rl_point >= rl_end)
     return (0);
   c = 0;
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     return (_rl_vi_change_mbchar_case (count));
 #endif
   while (count-- && rl_point < rl_end)
     {
       if (_rl_uppercase_p (rl_line_buffer[rl_point]))
     c = _rl_to_lower (rl_line_buffer[rl_point]);
       else if (_rl_lowercase_p (rl_line_buffer[rl_point]))
     c = _rl_to_upper (rl_line_buffer[rl_point]);
       else
     {
       /* Just skip over characters neither upper nor lower case. */
       rl_forward_char (1, c);
       continue;
     }
       /* Vi is kind of strange here. */
       if (c)
     {
       p = rl_point;
       rl_begin_undo_group ();
       rl_vi_delete (1, c);
       if (rl_point < p) /* Did we retreat at EOL? */
         rl_point++;
       _rl_insert_char (1, c);
       rl_end_undo_group ();
       rl_vi_check ();
     }
       else
     rl_forward_char (1, c);
     }
   return (0);
 }
References _rl_insert_char(), _rl_lowercase_p(), _rl_to_lower(), _rl_to_upper(), _rl_uppercase_p(), c, count, MB_CUR_MAX, p, rl_begin_undo_group(), rl_byte_oriented, rl_end, rl_end_undo_group(), rl_forward_char(), rl_line_buffer, rl_point, rl_vi_check(), and rl_vi_delete().
rl_vi_change_char()
int rl_vi_change_char (int count, int key)
Definition at line 2062 of file vi_mode.c.
 {
   int c;
   char mb[MB_LEN_MAX+1];
   if (_rl_vi_redoing)
     {
       strncpy (mb, _rl_vi_last_replacement, MB_LEN_MAX);
       c = (unsigned char)_rl_vi_last_replacement[0];    /* XXX */
       mb[MB_LEN_MAX] = '\0';
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_func = _rl_vi_callback_change_char;
       return (0);
     }
 #endif
   else
     {
       c = _rl_vi_callback_getchar (mb, MB_LEN_MAX);
       if (c < 0)
     return -1;
 #ifdef HANDLE_MULTIBYTE
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     strncpy (_rl_vi_last_replacement, mb, MB_LEN_MAX);
       else
 #endif
     _rl_vi_last_replacement[0] = c;
       _rl_vi_last_replacement[MB_LEN_MAX] = '\0';   /* just in case */
     }
   if (c < 0)
     return -1;
   return (_rl_vi_change_char (count, c, mb));
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_vi_callback_change_char(), _rl_vi_callback_getchar(), _rl_vi_change_char(), _rl_vi_last_replacement, _rl_vi_redoing, c, count, MB_CUR_MAX, MB_LEN_MAX, rl_byte_oriented, RL_ISSTATE, RL_STATE_CALLBACK, and strncpy().
rl_vi_change_to()
int rl_vi_change_to (int count, int key)
Definition at line 1471 of file vi_mode.c.
 {
   int c, r;
   _rl_vimotion_cxt *savecxt;
   savecxt = 0;
   if (_rl_vi_redoing)
     {
       savecxt = _rl_vimvcxt;
       _rl_vimvcxt = _rl_mvcxt_alloc (VIM_CHANGE, key);
     }
   else if (_rl_vimvcxt)
     _rl_mvcxt_init (_rl_vimvcxt, VIM_CHANGE, key);
   else
     _rl_vimvcxt = _rl_mvcxt_alloc (VIM_CHANGE, key);
   _rl_vimvcxt->start = rl_point;
   rl_mark = rl_point;
   if (_rl_uppercase_p (key))
     {
       _rl_vimvcxt->motion = '$';
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing && _rl_vi_last_motion != 'c') /* `cc' is special */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing)      /* handle redoing `cc' here */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       rl_mark = rl_end;
       rl_beg_of_line (1, key);
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       r = vidomove_dispatch (_rl_vimvcxt);
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       RL_SETSTATE (RL_STATE_VIMOTION);
       return (0);
     }
 #endif
   else
     r = rl_vi_domove (key, &c);
   if (r < 0)
     {
       rl_ding ();
       r = -1;   /* normalize return value */
     }
   _rl_mvcxt_dispose (_rl_vimvcxt);
   _rl_vimvcxt = savecxt;
   return r;
 }
References _rl_mvcxt_alloc(), _rl_mvcxt_dispose(), _rl_mvcxt_init(), _rl_uppercase_p(), _rl_vi_last_motion, _rl_vi_redoing, _rl_vimvcxt, c, __rl_vimotion_context::motion, rl_beg_of_line(), rl_ding(), rl_domove_motion_callback(), rl_end, RL_ISSTATE, rl_mark, rl_point, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove(), __rl_vimotion_context::start, vidomove_dispatch(), and VIM_CHANGE.
Referenced by rl_vi_subst().
rl_vi_char_search()
int rl_vi_char_search (int count, int key)
Definition at line 1802 of file vi_mode.c.
 {
   int c;
 #if defined (HANDLE_MULTIBYTE)
   static char *target;
   static int tlen;
 #else
   static char target;
 #endif
   if (key == ';' || key == ',')
     {
       if (_rl_cs_orig_dir == 0)
     return 1;
 #if defined (HANDLE_MULTIBYTE)
       if (_rl_vi_last_search_mblen == 0)
     return 1;
 #else
       if (_rl_vi_last_search_char == 0)
     return 1;
 #endif
       _rl_cs_dir = (key == ';') ? _rl_cs_orig_dir : -_rl_cs_orig_dir;
     }
   else
     {
       switch (key)
     {
     case 't':
       _rl_cs_orig_dir = _rl_cs_dir = FTO;
       break;
     case 'T':
       _rl_cs_orig_dir = _rl_cs_dir = BTO;
       break;
     case 'f':
       _rl_cs_orig_dir = _rl_cs_dir = FFIND;
       break;
     case 'F':
       _rl_cs_orig_dir = _rl_cs_dir = BFIND;
       break;
     }
       if (_rl_vi_redoing)
     {
       /* set target and tlen below */
     }
 #if defined (READLINE_CALLBACKS)
       else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_data->i1 = _rl_cs_dir;
       _rl_callback_data->i2 = key;
       _rl_callback_func = _rl_vi_callback_char_search;
       RL_SETSTATE (RL_STATE_CHARSEARCH);
       return (0);
     }
 #endif
       else
     {
 #if defined (HANDLE_MULTIBYTE)
       c = _rl_read_mbchar (_rl_vi_last_search_mbchar, MB_LEN_MAX);
       if (c <= 0)
         return -1;
       _rl_vi_last_search_mblen = c;
 #else
       RL_SETSTATE(RL_STATE_MOREINPUT);
       c = rl_read_key ();
       RL_UNSETSTATE(RL_STATE_MOREINPUT);
       if (c < 0)
         return -1;
       _rl_vi_last_search_char = c;
 #endif
     }
     }
 #if defined (HANDLE_MULTIBYTE)
   target = _rl_vi_last_search_mbchar;
   tlen = _rl_vi_last_search_mblen;
 #else
   target = _rl_vi_last_search_char;
 #endif
 #if defined (HANDLE_MULTIBYTE)
   return (_rl_char_search_internal (count, _rl_cs_dir, target, tlen));
 #else
   return (_rl_char_search_internal (count, _rl_cs_dir, target));
 #endif
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_char_search_internal(), _rl_cs_dir, _rl_cs_orig_dir, _rl_vi_callback_char_search(), _rl_vi_last_search_char, _rl_vi_redoing, BFIND, BTO, c, count, FFIND, FTO, __rl_callback_generic_arg::i1, __rl_callback_generic_arg::i2, MB_LEN_MAX, RL_ISSTATE, rl_read_key(), RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_CHARSEARCH, RL_STATE_MOREINPUT, RL_UNSETSTATE, and target.
rl_vi_check()
int rl_vi_check (void)
Definition at line 1041 of file vi_mode.c.
 {
   if (rl_point && rl_point == rl_end)
     _rl_vi_backup ();
   return (0);
 }
References _rl_vi_backup(), rl_end, and rl_point.
Referenced by _rl_internal_char_cleanup(), and rl_vi_change_case().
rl_vi_column()
int rl_vi_column (int count, int key)
Definition at line 1050 of file vi_mode.c.
 {
   if (count > rl_end)
     rl_end_of_line (1, key);
   else
     {
       rl_point = 0;
       rl_point = _rl_forward_char_internal (count - 1);
     }
   return (0);
 }
References _rl_forward_char_internal(), count, rl_end, rl_end_of_line(), and rl_point.
rl_vi_complete()
int rl_vi_complete (int ignore, int key)
Definition at line 385 of file vi_mode.c.
 {
   if ((rl_point < rl_end) && (!whitespace (rl_line_buffer[rl_point])))
     {
       if (!whitespace (rl_line_buffer[rl_point + 1]))
     rl_vi_end_word (1, 'E');
       _rl_vi_advance_point ();
     }
   if (key == '*')
     rl_complete_internal ('*'); /* Expansion and replacement. */
   else if (key == '=')
     rl_complete_internal ('?'); /* List possible completions. */
   else if (key == '\\')
     rl_complete_internal (TAB); /* Standard Readline completion. */
   else
     rl_complete (0, key);
   if (key == '*' || key == '\\')
     rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References _rl_vi_advance_point(), rl_arg_sign, rl_complete(), rl_complete_internal(), rl_end, rl_line_buffer, rl_point, rl_vi_end_word(), rl_vi_start_inserting(), TAB, and whitespace.
rl_vi_delete()
int rl_vi_delete (int count, int key)
Definition at line 1665 of file vi_mode.c.
 {
   int end;
   if (count < 0)
     return (rl_vi_rubout (-count, key));
   if (rl_end == 0)
     {
       rl_ding ();
       return 1;
     }
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     end = _rl_find_next_mbchar (rl_line_buffer, rl_point, count, MB_FIND_NONZERO);
   else
     end = rl_point + count;
   if (end >= rl_end)
     end = rl_end;
   rl_kill_text (rl_point, end);
   if (rl_point > 0 && rl_point == rl_end)
     rl_backward_char (1, key);
   return (0);
 }
References _rl_find_next_mbchar, count, end, MB_CUR_MAX, MB_FIND_NONZERO, rl_backward_char(), rl_byte_oriented, rl_ding(), rl_end, rl_kill_text(), rl_line_buffer, rl_point, and rl_vi_rubout().
Referenced by _rl_vi_change_char(), rl_vi_change_case(), and rl_vi_rubout().
rl_vi_delete_to()
int rl_vi_delete_to (int count, int key)
Definition at line 1372 of file vi_mode.c.
 {
   int c, r;
   _rl_vimotion_cxt *savecxt;
   savecxt = 0;
   if (_rl_vi_redoing)
     {
       savecxt = _rl_vimvcxt;
       _rl_vimvcxt = _rl_mvcxt_alloc (VIM_DELETE, key);
     }
   else if (_rl_vimvcxt)
     _rl_mvcxt_init (_rl_vimvcxt, VIM_DELETE, key);
   else
     _rl_vimvcxt = _rl_mvcxt_alloc (VIM_DELETE, key);
   _rl_vimvcxt->start = rl_point;
   rl_mark = rl_point;
   if (_rl_uppercase_p (key))
     {
       _rl_vimvcxt->motion = '$';
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing && _rl_vi_last_motion != 'd') /* `dd' is special */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing)      /* handle redoing `dd' here */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       rl_mark = rl_end;
       rl_beg_of_line (1, key);
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       r = vidomove_dispatch (_rl_vimvcxt);
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       RL_SETSTATE (RL_STATE_VIMOTION);
       return (0);
     }
 #endif
   else
     r = rl_vi_domove (key, &c);
   if (r < 0)
     {
       rl_ding ();
       r = -1;
     }
   _rl_mvcxt_dispose (_rl_vimvcxt);
   _rl_vimvcxt = savecxt;
   return r;
 }
References _rl_mvcxt_alloc(), _rl_mvcxt_dispose(), _rl_mvcxt_init(), _rl_uppercase_p(), _rl_vi_last_motion, _rl_vi_redoing, _rl_vimvcxt, c, __rl_vimotion_context::motion, rl_beg_of_line(), rl_ding(), rl_domove_motion_callback(), rl_end, RL_ISSTATE, rl_mark, rl_point, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove(), __rl_vimotion_context::start, vidomove_dispatch(), and VIM_DELETE.
rl_vi_domove()
int rl_vi_domove (int x, int * ignore)
Definition at line 1341 of file vi_mode.c.
 {
   int r;
   _rl_vimotion_cxt *m;
   m = _rl_vimvcxt;
   *ignore = m->motion = rl_vi_domove_getchar (m);
   if (m->motion < 0)
     {
       m->motion = 0;
       return -1;
     }
   return (rl_domove_read_callback (m));
 }
References _rl_vimvcxt, ignore(), __rl_vimotion_context::motion, rl_domove_read_callback(), and rl_vi_domove_getchar().
Referenced by rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
rl_vi_editing_mode()
int rl_vi_editing_mode (int count, int key)
Definition at line 733 of file misc.c.
 {
 #if defined (VI_MODE)
   _rl_set_insert_mode (RL_IM_INSERT, 1);    /* vi mode ignores insert mode */
   rl_editing_mode = vi_mode;
   rl_vi_insert_mode (1, key);
 #endif /* VI_MODE */
   return 0;
 }
References _rl_set_insert_mode(), rl_editing_mode, RL_IM_INSERT, rl_vi_insert_mode(), and vi_mode.
rl_vi_end_word()
int rl_vi_end_word (int count, int key)
Definition at line 524 of file vi_mode.c.
 {
   if (count < 0)
     {
       rl_ding ();
       return 1;
     }
   if (_rl_uppercase_p (key))
     rl_vi_eWord (count, key);
   else
     rl_vi_eword (count, key);
   return (0);
 }
References _rl_uppercase_p(), count, rl_ding(), rl_vi_eWord(), and rl_vi_eword().
Referenced by rl_vi_complete().
rl_vi_eof_maybe()
int rl_vi_eof_maybe (int count, int c)
Definition at line 769 of file vi_mode.c.
 {
   return (rl_newline (1, '\n'));
 }
References rl_newline().
rl_vi_eWord()
int rl_vi_eWord (int count, int ignore)
Definition at line 586 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point < (rl_end - 1))
     {
       if (whitespace (rl_line_buffer[rl_point]) == 0)
     _rl_vi_advance_point ();
       /* Move to the next non-whitespace character (to the start of the
      next word). */
       while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_advance_point ();
       if (rl_point && rl_point < rl_end)
     {
       opoint = rl_point;
       /* Skip whitespace. */
       while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
         opoint = _rl_vi_advance_point ();   /* XXX - why? */
       /* Skip until whitespace. */
       while (rl_point < rl_end && !whitespace (rl_line_buffer[rl_point]))
         opoint = _rl_vi_advance_point ();
       /* Move back to the last character of the word. */
       rl_point = opoint;
     }
     }
   return (0);
 }
References _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_end_word().
rl_vi_eword()
int rl_vi_eword (int count, int ignore)
Definition at line 703 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point < (rl_end - 1))
     {
       if (whitespace (rl_line_buffer[rl_point]) == 0)
     _rl_vi_advance_point ();
       while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_advance_point ();
       opoint = rl_point;
       if (rl_point < rl_end)
     {
       if (_rl_isident (rl_line_buffer[rl_point]))
         do
           {
         opoint = _rl_vi_advance_point ();
           }
         while (rl_point < rl_end && _rl_isident (rl_line_buffer[rl_point]));
       else
         do
           {
         opoint = _rl_vi_advance_point ();
           }
         while (rl_point < rl_end && !_rl_isident (rl_line_buffer[rl_point])
            && !whitespace (rl_line_buffer[rl_point]));
     }
       rl_point = opoint;
     }
   return (0);
 }
References _rl_isident, _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_end_word().
rl_vi_fetch_history()
int rl_vi_fetch_history (int count, int c)
Definition at line 338 of file vi_mode.c.
 {
   return (rl_fetch_history (count, c));
 }
References c, count, and rl_fetch_history().
rl_vi_first_print()
int rl_vi_first_print (int count, int key)
Definition at line 1759 of file vi_mode.c.
 {
   return (rl_vi_back_to_indent (1, key));
 }
References rl_vi_back_to_indent().
rl_vi_fWord()
int rl_vi_fWord (int count, int ignore)
Definition at line 541 of file vi_mode.c.
 {
   while (count-- && rl_point < (rl_end - 1))
     {
       /* Skip until whitespace. */
       while (!whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
     _rl_vi_advance_point ();
       /* Now skip whitespace. */
       while (whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
     _rl_vi_advance_point ();
     }
   return (0);
 }
References _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_next_word().
rl_vi_fword()
int rl_vi_fword (int count, int ignore)
Definition at line 620 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point < (rl_end - 1))
     {
       /* Move to white space (really non-identifer). */
       if (_rl_isident (rl_line_buffer[rl_point]))
     {
       while (_rl_isident (rl_line_buffer[rl_point]) && rl_point < rl_end)
         _rl_vi_advance_point ();
     }
       else /* if (!whitespace (rl_line_buffer[rl_point])) */
     {
       while (!_rl_isident (rl_line_buffer[rl_point]) &&
          !whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
         _rl_vi_advance_point ();
     }
       opoint = rl_point;
       /* Move past whitespace. */
       while (whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
     opoint = _rl_vi_advance_point ();
     }
   return (0);
 }
References _rl_isident, _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_next_word().
rl_vi_goto_mark()
int rl_vi_goto_mark (int count, int key)
Definition at line 2402 of file vi_mode.c.
 {
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = 0;
       _rl_callback_func = _rl_vi_callback_goto_mark;
       return (0);
     }
 #endif
   return (_rl_vi_goto_mark ());
 }
References _rl_callback_data, _rl_callback_func, _rl_vi_callback_goto_mark(), _rl_vi_goto_mark(), RL_ISSTATE, and RL_STATE_CALLBACK.
rl_vi_insert_beg()
int rl_vi_insert_beg (int count, int key)
Definition at line 738 of file vi_mode.c.
 {
   rl_beg_of_line (1, key);
   rl_vi_insert_mode (1, key);
   return (0);
 }
References rl_beg_of_line(), and rl_vi_insert_mode().
rl_vi_insert_mode()
int rl_vi_insert_mode (int count, int key)
Definition at line 789 of file vi_mode.c.
 {
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References rl_arg_sign, and rl_vi_start_inserting().
Referenced by rl_vi_editing_mode(), and rl_vi_insert_beg().
rl_vi_insertion_mode()
int rl_vi_insertion_mode (int count, int key)
Definition at line 779 of file vi_mode.c.
 {
   _rl_keymap = vi_insertion_keymap;
   _rl_vi_last_key_before_insert = key;
   if (_rl_show_mode_in_prompt)
     _rl_reset_prompt ();
   return (0);
 }
References _rl_keymap, _rl_reset_prompt(), _rl_show_mode_in_prompt, _rl_vi_last_key_before_insert, and vi_insertion_keymap.
Referenced by readline_internal_setup(), and rl_vi_start_inserting().
rl_vi_match()
int rl_vi_match (int ignore, int key)
Definition at line 1895 of file vi_mode.c.
 {
   int count = 1, brack, pos, tmp, pre;
   pos = rl_point;
   if ((brack = rl_vi_bracktype (rl_line_buffer[rl_point])) == 0)
     {
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       while ((brack = rl_vi_bracktype (rl_line_buffer[rl_point])) == 0)
         {
           pre = rl_point;
           rl_forward_char (1, key);
           if (pre == rl_point)
         break;
         }
     }
       else
     while ((brack = rl_vi_bracktype (rl_line_buffer[rl_point])) == 0 &&
         rl_point < rl_end - 1)
       rl_forward_char (1, key);
       if (brack <= 0)
     {
       rl_point = pos;
       rl_ding ();
       return 1;
     }
     }
   pos = rl_point;
   if (brack < 0)
     {
       while (count)
     {
       tmp = pos;
       if (MB_CUR_MAX == 1 || rl_byte_oriented)
         pos--;
       else
         {
           pos = _rl_find_prev_mbchar (rl_line_buffer, pos, MB_FIND_ANY);
           if (tmp == pos)
         pos--;
         }
       if (pos >= 0)
         {
           int b = rl_vi_bracktype (rl_line_buffer[pos]);
           if (b == -brack)
         count--;
           else if (b == brack)
         count++;
         }
       else
         {
           rl_ding ();
           return 1;
         }
     }
     }
   else
     {           /* brack > 0 */
       while (count)
     {
       if (MB_CUR_MAX == 1 || rl_byte_oriented)
         pos++;
       else
         pos = _rl_find_next_mbchar (rl_line_buffer, pos, 1, MB_FIND_ANY);
       if (pos < rl_end)
         {
           int b = rl_vi_bracktype (rl_line_buffer[pos]);
           if (b == -brack)
         count--;
           else if (b == brack)
         count++;
         }
       else
         {
           rl_ding ();
           return 1;
         }
     }
     }
   rl_point = pos;
   return (0);
 }
References _rl_find_next_mbchar, _rl_find_prev_mbchar, count, MB_CUR_MAX, MB_FIND_ANY, pos, rl_byte_oriented, rl_ding(), rl_end, rl_forward_char(), rl_line_buffer, rl_point, and rl_vi_bracktype().
rl_vi_movement_mode()
int rl_vi_movement_mode (int count, int key)
Definition at line 896 of file vi_mode.c.
 {
   if (rl_point > 0)
     rl_backward_char (1, key);
   _rl_keymap = vi_movement_keymap;
   _rl_vi_done_inserting ();
   /* This is how POSIX.2 says `U' should behave -- everything up until the
      first time you go into command mode should not be undone. */
   if (RL_ISSTATE (RL_STATE_VICMDONCE) == 0)
     rl_free_undo_list ();
   if (_rl_show_mode_in_prompt)
     _rl_reset_prompt ();
   RL_SETSTATE (RL_STATE_VICMDONCE);
   return (0);
 }
References _rl_keymap, _rl_reset_prompt(), _rl_show_mode_in_prompt, _rl_vi_done_inserting(), rl_backward_char(), rl_free_undo_list(), RL_ISSTATE, rl_point, RL_SETSTATE, RL_STATE_VICMDONCE, and vi_movement_keymap.
Referenced by rl_bind_keyseq_if_unbound_in_map(), and rl_vi_replace().
rl_vi_next_word()
int rl_vi_next_word (int count, int key)
Definition at line 441 of file vi_mode.c.
 {
   if (count < 0)
     return (rl_vi_prev_word (-count, key));
   if (rl_point >= (rl_end - 1))
     {
       rl_ding ();
       return (0);
     }
   if (_rl_uppercase_p (key))
     rl_vi_fWord (count, key);
   else
     rl_vi_fword (count, key);
   return (0);
 }
References _rl_uppercase_p(), count, rl_ding(), rl_end, rl_point, rl_vi_fWord(), rl_vi_fword(), and rl_vi_prev_word().
Referenced by rl_vi_prev_word().
rl_vi_overstrike()
int rl_vi_overstrike (int count, int key)
Definition at line 2112 of file vi_mode.c.
 {
   if (_rl_vi_doing_insert == 0)
     {
       _rl_vi_doing_insert = 1;
       rl_begin_undo_group ();
     }
   if (count > 0)
     {
       if (_rl_overwrite_char (count, key) != 0)
     return (1);
       vi_replace_count += count;
     }
   return (0);
 }
References _rl_overwrite_char(), _rl_vi_doing_insert, count, rl_begin_undo_group(), and vi_replace_count.
Referenced by rl_vi_overstrike_bracketed_paste(), and rl_vi_replace().
rl_vi_overstrike_delete()
int rl_vi_overstrike_delete (int count, int key)
Definition at line 2131 of file vi_mode.c.
 {
   int i, s;
   for (i = 0; i < count; i++)
     {
       if (vi_replace_count == 0)
     {
       rl_ding ();
       break;
     }
       s = rl_point;
       if (rl_do_undo ())
     vi_replace_count--;     /* XXX */
       if (rl_point == s)
     rl_backward_char (1, key);
     }
   if (vi_replace_count == 0 && _rl_vi_doing_insert)
     {
       rl_end_undo_group ();
       rl_do_undo ();
       _rl_vi_doing_insert = 0;
     }
   return (0);
 }
References _rl_vi_doing_insert, count, i, rl_backward_char(), rl_ding(), rl_do_undo(), rl_end_undo_group(), rl_point, s, and vi_replace_count.
Referenced by rl_vi_replace().
rl_vi_prev_word()
int rl_vi_prev_word (int count, int key)
Definition at line 420 of file vi_mode.c.
 {
   if (count < 0)
     return (rl_vi_next_word (-count, key));
   if (rl_point == 0)
     {
       rl_ding ();
       return (0);
     }
   if (_rl_uppercase_p (key))
     rl_vi_bWord (count, key);
   else
     rl_vi_bword (count, key);
   return (0);
 }
References _rl_uppercase_p(), count, rl_ding(), rl_point, rl_vi_bWord(), rl_vi_bword(), and rl_vi_next_word().
Referenced by rl_vi_next_word().
rl_vi_put()
int rl_vi_put (int count, int key)
Definition at line 1027 of file vi_mode.c.
 {
   if (!_rl_uppercase_p (key) && (rl_point + 1 <= rl_end))
     rl_point = _rl_find_next_mbchar (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
   while (count--)
     rl_yank (1, key);
   rl_backward_char (1, key);
   return (0);
 }
References _rl_find_next_mbchar, _rl_uppercase_p(), count, MB_FIND_NONZERO, rl_backward_char(), rl_end, rl_line_buffer, rl_point, and rl_yank().
Referenced by rl_vi_yank_pop().
rl_vi_redo()
int rl_vi_redo (int count, int c)
Definition at line 246 of file vi_mode.c.
 {
   int r;
   if (rl_explicit_arg == 0)
     {
       rl_numeric_arg = _rl_vi_last_repeat;
       rl_arg_sign = _rl_vi_last_arg_sign;
     }
   r = 0;
   _rl_vi_redoing = 1;
   /* If we're redoing an insert with `i', stuff in the inserted text
      and do not go into insertion mode. */
   if (_rl_vi_last_command == 'i' && vi_insert_buffer && *vi_insert_buffer)
     {
       _rl_vi_stuff_insert (count);
       /* And back up point over the last character inserted. */
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   else if (_rl_vi_last_command == 'R' && vi_insert_buffer && *vi_insert_buffer)
     {
       _rl_vi_replace_insert (count);
       /* And back up point over the last character inserted. */
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   /* Ditto for redoing an insert with `I', but move to the beginning of the
      line like the `I' command does. */
   else if (_rl_vi_last_command == 'I' && vi_insert_buffer && *vi_insert_buffer)
     {
       rl_beg_of_line (1, 'I');
       _rl_vi_stuff_insert (count);
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   /* Ditto for redoing an insert with `a', but move forward a character first
      like the `a' command does. */
   else if (_rl_vi_last_command == 'a' && vi_insert_buffer && *vi_insert_buffer)
     {
       _rl_vi_append_forward ('a');
       _rl_vi_stuff_insert (count);
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   /* Ditto for redoing an insert with `A', but move to the end of the line
      like the `A' command does. */
   else if (_rl_vi_last_command == 'A' && vi_insert_buffer && *vi_insert_buffer)
     {
       rl_end_of_line (1, 'A');
       _rl_vi_stuff_insert (count);
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   else if (_rl_vi_last_command == '.' && _rl_keymap == vi_movement_keymap)
     {
       rl_ding ();
       r = 0;
     }
   else
     r = _rl_dispatch (_rl_vi_last_command, _rl_keymap);
   _rl_vi_redoing = 0;
   return (r);
 }
References _rl_dispatch(), _rl_keymap, _rl_vi_append_forward(), _rl_vi_backup(), _rl_vi_last_arg_sign, _rl_vi_last_command, _rl_vi_last_repeat, _rl_vi_redoing, _rl_vi_replace_insert(), _rl_vi_stuff_insert(), count, rl_arg_sign, rl_beg_of_line(), rl_ding(), rl_end_of_line(), rl_explicit_arg, rl_numeric_arg, rl_point, vi_insert_buffer, and vi_movement_keymap.
rl_vi_replace()
int rl_vi_replace (int count, int key)
Definition at line 2222 of file vi_mode.c.
 {
   int i;
   vi_replace_count = 0;
   if (vi_replace_map == 0)
     {
       vi_replace_map = rl_make_bare_keymap ();
       for (i = 0; i < ' '; i++)
     if (vi_insertion_keymap[i].type == ISFUNC)
       vi_replace_map[i].function = vi_insertion_keymap[i].function;
       for (i = ' '; i < KEYMAP_SIZE; i++)
     vi_replace_map[i].function = rl_vi_overstrike;
       vi_replace_map[RUBOUT].function = rl_vi_overstrike_delete;
       /* Make sure these are what we want. */
       vi_replace_map[ESC].function = rl_vi_movement_mode;
       vi_replace_map[RETURN].function = rl_newline;
       vi_replace_map[NEWLINE].function = rl_newline;
       /* If the normal vi insertion keymap has ^H bound to erase, do the
      same here.  Probably should remove the assignment to RUBOUT up
      there, but I don't think it will make a difference in real life. */
       if (vi_insertion_keymap[CTRL ('H')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('H')].function == rl_rubout)
     vi_replace_map[CTRL ('H')].function = rl_vi_overstrike_delete;
       /* Same for ^U and unix-line-discard. */
       if (vi_insertion_keymap[CTRL ('U')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('U')].function == rl_unix_line_discard)
     vi_replace_map[CTRL ('U')].function = rl_vi_overstrike_kill_line;
       /* And for ^W and unix-word-rubout. */
       if (vi_insertion_keymap[CTRL ('W')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('W')].function == rl_vi_unix_word_rubout)
     vi_replace_map[CTRL ('W')].function = rl_vi_overstrike_kill_word;
       /* And finally for ^Y and yank. */
       if (vi_insertion_keymap[CTRL ('Y')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('Y')].function == rl_yank)
     vi_replace_map[CTRL ('Y')].function = rl_vi_overstrike_yank;
       /* Make sure this is the value we need. */
       vi_replace_map[ANYOTHERKEY].type = ISFUNC;
       vi_replace_map[ANYOTHERKEY].function = (rl_command_func_t *)NULL;
     }
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   _rl_vi_last_key_before_insert = 'R';  /* in case someone rebinds it */
   _rl_keymap = vi_replace_map;
   if (_rl_enable_bracketed_paste)
     rl_bind_keyseq_if_unbound (BRACK_PASTE_PREF, rl_vi_overstrike_bracketed_paste);
   return (0);
 }
References _rl_enable_bracketed_paste, _rl_keymap, _rl_vi_last_key_before_insert, ANYOTHERKEY, BRACK_PASTE_PREF, CTRL, ESC, _keymap_entry::function, i, ISFUNC, KEYMAP_SIZE, NEWLINE, NULL, RETURN, rl_arg_sign, rl_bind_keyseq_if_unbound(), rl_make_bare_keymap(), rl_newline(), rl_rubout(), rl_unix_line_discard(), rl_vi_movement_mode(), rl_vi_overstrike(), rl_vi_overstrike_bracketed_paste(), rl_vi_overstrike_delete(), rl_vi_overstrike_kill_line(), rl_vi_overstrike_kill_word(), rl_vi_overstrike_yank(), rl_vi_start_inserting(), rl_vi_unix_word_rubout(), rl_yank(), RUBOUT, _keymap_entry::type, type, vi_insertion_keymap, vi_replace_count, and vi_replace_map.
rl_vi_rubout()
int rl_vi_rubout (int count, int key)
Definition at line 1635 of file vi_mode.c.
 {
   int opoint;
   if (count < 0)
     return (rl_vi_delete (-count, key));
   if (rl_point == 0)
     {
       rl_ding ();
       return 1;
     }
   opoint = rl_point;
   if (count > 1 && MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_backward_char (count, key);
   else if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_point = _rl_find_prev_mbchar (rl_line_buffer, rl_point, MB_FIND_NONZERO);
   else
     rl_point -= count;
   if (rl_point < 0)
     rl_point = 0;
   rl_kill_text (rl_point, opoint);
   return (0);
 }
References _rl_find_prev_mbchar, count, MB_CUR_MAX, MB_FIND_NONZERO, rl_backward_char(), rl_byte_oriented, rl_ding(), rl_kill_text(), rl_line_buffer, rl_point, and rl_vi_delete().
Referenced by rl_vi_delete().
rl_vi_search()
int rl_vi_search (int count, int key)
Definition at line 362 of file vi_mode.c.
 {
   switch (key)
     {
     case '?':
       _rl_free_saved_history_line ();
       rl_noninc_forward_search (count, key);
       break;
     case '/':
       _rl_free_saved_history_line ();
       rl_noninc_reverse_search (count, key);
       break;
     default:
       rl_ding ();
       break;
     }
   return (0);
 }
References _rl_free_saved_history_line(), count, rl_ding(), rl_noninc_forward_search(), and rl_noninc_reverse_search().
rl_vi_search_again()
int rl_vi_search_again (int count, int key)
Definition at line 345 of file vi_mode.c.
 {
   switch (key)
     {
     case 'n':
       rl_noninc_reverse_search_again (count, key);
       break;
     case 'N':
       rl_noninc_forward_search_again (count, key);
       break;
     }
   return (0);
 }
References count, rl_noninc_forward_search_again(), and rl_noninc_reverse_search_again().
rl_vi_set_mark()
int rl_vi_set_mark (int count, int key)
Definition at line 2344 of file vi_mode.c.
 {
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = 0;
       _rl_callback_func = _rl_vi_callback_set_mark;
       return (0);
     }
 #endif
   return (_rl_vi_set_mark ());
 }
References _rl_callback_data, _rl_callback_func, _rl_vi_callback_set_mark(), _rl_vi_set_mark(), RL_ISSTATE, and RL_STATE_CALLBACK.
rl_vi_start_inserting()
void rl_vi_start_inserting (int key, int repeat, int sign)
Definition at line 198 of file vi_mode.c.
 {
   _rl_vi_set_last (key, repeat, sign);
   rl_begin_undo_group ();       /* ensure inserts aren't concatenated */
   rl_vi_insertion_mode (1, key);
 }
References _rl_vi_set_last(), rl_begin_undo_group(), and rl_vi_insertion_mode().
Referenced by rl_vi_append_mode(), rl_vi_complete(), rl_vi_insert_mode(), rl_vi_replace(), rl_vi_tilde_expand(), and vi_change_dispatch().
rl_vi_subst()
int rl_vi_subst (int count, int key)
Definition at line 2102 of file vi_mode.c.
 {
   /* If we are redoing, rl_vi_change_to will stuff the last motion char */
   if (_rl_vi_redoing == 0)
     rl_stuff_char ((key == 'S') ? 'c' : 'l');   /* `S' == `cc', `s' == `cl' */
   return (rl_vi_change_to (count, 'c'));
 }
References _rl_vi_redoing, count, rl_stuff_char(), and rl_vi_change_to().
rl_vi_tilde_expand()
int rl_vi_tilde_expand (int ignore, int key)
Definition at line 411 of file vi_mode.c.
 {
   rl_tilde_expand (0, key);
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References rl_arg_sign, rl_tilde_expand(), and rl_vi_start_inserting().
rl_vi_undo()
int rl_vi_undo (int count, int key)
Definition at line 316 of file vi_mode.c.
 {
   return (rl_undo_command (count, key));
 }
References count, and rl_undo_command().
rl_vi_unix_word_rubout()
int rl_vi_unix_word_rubout (int count, int key)
Definition at line 1700 of file vi_mode.c.
 {
   int orig_point;
   if (rl_point == 0)
     rl_ding ();
   else
     {
       orig_point = rl_point;
       if (count <= 0)
     count = 1;
       while (count--)
     {
       /* This isn't quite what ksh93 does but it seems to match what the
          Posix description of sh specifies, with a few accommodations
          for sequences of whitespace characters between words and at
          the end of the line. */
       /* Skip over whitespace at the end of the line as a special case */
       if (rl_point > 0 && (rl_line_buffer[rl_point] == 0) &&
         whitespace (rl_line_buffer[rl_point - 1]))
         while (--rl_point > 0 && whitespace (rl_line_buffer[rl_point]))
           ;
       /* If we're at the start of a word, move back to word boundary so we
          move back to the `preceding' word */
       if (rl_point > 0 && (vi_unix_word_boundary (rl_line_buffer[rl_point]) == 0) &&
         vi_unix_word_boundary (rl_line_buffer[rl_point - 1]))
         rl_point--;
       /* If we are at a word boundary (whitespace/punct), move backward
          past a sequence of word boundary characters.  If we are at the
          end of a word (non-word boundary), move back to a word boundary */
       if (rl_point > 0 && vi_unix_word_boundary (rl_line_buffer[rl_point]))
         while (rl_point && vi_unix_word_boundary (rl_line_buffer[rl_point - 1]))
           rl_point--;
       else if (rl_point > 0 && vi_unix_word_boundary (rl_line_buffer[rl_point]) == 0)
         while (rl_point > 0 && (vi_unix_word_boundary (rl_line_buffer[rl_point - 1]) == 0))
           _rl_vi_backup_point ();
     }
       rl_kill_text (orig_point, rl_point);
     }
   return 0;
 }
References _rl_vi_backup_point(), count, rl_ding(), rl_kill_text(), rl_line_buffer, rl_point, vi_unix_word_boundary, and whitespace.
Referenced by rl_vi_overstrike_kill_word(), and rl_vi_replace().
rl_vi_yank_arg()
int rl_vi_yank_arg (int count, int key)
Definition at line 323 of file vi_mode.c.
 {
   /* Readline thinks that the first word on a line is the 0th, while vi
      thinks the first word on a line is the 1st.  Compensate. */
   if (rl_explicit_arg)
     rl_yank_nth_arg (count - 1, key);
   else
     rl_yank_nth_arg ('$', key);
   return (0);
 }
References count, rl_explicit_arg, and rl_yank_nth_arg().
rl_vi_yank_pop()
int rl_vi_yank_pop (int count, int key)
Definition at line 560 of file kill.c.
 {
   int l, n, origpoint;
   if (((rl_last_func != rl_vi_yank_pop) && (rl_last_func != rl_vi_put)) ||
       !rl_kill_ring)
     {
       _rl_abort_internal ();
       return 1;
     }
   l = strlen (rl_kill_ring[rl_kill_index]);
 #if 0 /* TAG:readline-8.3 8/29/2022 matteopaolini1995@gmail.com */
   origpoint = rl_point;
   n = rl_point - l + 1;
 #else
   n = rl_point - l;
 #endif
   if (n >= 0 && STREQN (rl_line_buffer + n, rl_kill_ring[rl_kill_index], l))
     {
 #if 0 /* TAG:readline-8.3 */
       rl_delete_text (n, n + l);        /* remember vi cursor positioning */
       rl_point = origpoint - l;
 #else
       rl_delete_text (n, rl_point);
       rl_point = n;
 #endif
       rl_kill_index--;
       if (rl_kill_index < 0)
     rl_kill_index = rl_kill_ring_length - 1;
       rl_vi_put (1, 'p');
       return 0;
     }
   else
     {
       _rl_abort_internal ();
       return 1;
     }
 }
References _rl_abort_internal(), l, n, rl_delete_text(), rl_kill_index, rl_kill_ring, rl_kill_ring_length, rl_last_func, rl_line_buffer, rl_point, rl_vi_put(), STREQN, and strlen().
rl_vi_yank_to()
int rl_vi_yank_to (int count, int key)
Definition at line 1550 of file vi_mode.c.
 {
   int c, r;
   _rl_vimotion_cxt *savecxt;
   savecxt = 0;
   if (_rl_vi_redoing)
     {
       savecxt = _rl_vimvcxt;
       _rl_vimvcxt = _rl_mvcxt_alloc (VIM_YANK, key);
     }
   else if (_rl_vimvcxt)
     _rl_mvcxt_init (_rl_vimvcxt, VIM_YANK, key);
   else
     _rl_vimvcxt = _rl_mvcxt_alloc (VIM_YANK, key);
   _rl_vimvcxt->start = rl_point;
   rl_mark = rl_point;
   if (_rl_uppercase_p (key))
     {
       _rl_vimvcxt->motion = '$';
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing && _rl_vi_last_motion != 'y') /* `yy' is special */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing)          /* handle redoing `yy' here */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       rl_mark = rl_end;
       rl_beg_of_line (1, key);
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       r = vidomove_dispatch (_rl_vimvcxt);
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       RL_SETSTATE (RL_STATE_VIMOTION);
       return (0);
     }
 #endif
   else
     r = rl_vi_domove (key, &c);
   if (r < 0)
     {
       rl_ding ();
       r = -1;
     }
   _rl_mvcxt_dispose (_rl_vimvcxt);
   _rl_vimvcxt = savecxt;
   return r;
 }
References _rl_mvcxt_alloc(), _rl_mvcxt_dispose(), _rl_mvcxt_init(), _rl_uppercase_p(), _rl_vi_last_motion, _rl_vi_redoing, _rl_vimvcxt, c, __rl_vimotion_context::motion, rl_beg_of_line(), rl_ding(), rl_domove_motion_callback(), rl_end, RL_ISSTATE, rl_mark, rl_point, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove(), __rl_vimotion_context::start, vidomove_dispatch(), and VIM_YANK.
rl_yank()
int rl_yank (int count, int key)
Definition at line 510 of file kill.c.
 {
   if (rl_kill_ring == 0)
     {
       _rl_abort_internal ();
       return 1;
     }
   _rl_set_mark_at_pos (rl_point);
   rl_insert_text (rl_kill_ring[rl_kill_index]);
   return 0;
 }
References _rl_abort_internal(), _rl_set_mark_at_pos(), rl_insert_text(), rl_kill_index, rl_kill_ring, and rl_point.
Referenced by _rl_isearch_dispatch(), rl_vi_overstrike_yank(), rl_vi_put(), rl_vi_replace(), and rl_yank_pop().
rl_yank_last_arg()
int rl_yank_last_arg (int count, int key)
Definition at line 668 of file kill.c.
 {
   static int history_skip = 0;
   static int explicit_arg_p = 0;
   static int count_passed = 1;
   static int direction = 1;
   static int undo_needed = 0;
   int retval;
   if (rl_last_func != rl_yank_last_arg)
     {
       history_skip = 0;
       explicit_arg_p = rl_explicit_arg;
       count_passed = count;
       direction = 1;
     }
   else
     {
       if (undo_needed)
     rl_do_undo ();
       if (count < 0)        /* XXX - was < 1 */
         direction = -direction;
       history_skip += direction;
       if (history_skip < 0)
     history_skip = 0;
     }
   if (explicit_arg_p)
     retval = rl_yank_nth_arg_internal (count_passed, key, history_skip);
   else
     retval = rl_yank_nth_arg_internal ('$', key, history_skip);
   undo_needed = retval == 0;
   return retval;
 }
References count, retval, rl_do_undo(), rl_explicit_arg, rl_last_func, and rl_yank_nth_arg_internal().
rl_yank_nth_arg()
int rl_yank_nth_arg (int count, int key)
Definition at line 659 of file kill.c.
 {
   return (rl_yank_nth_arg_internal (count, key, 0));
 }
References count, and rl_yank_nth_arg_internal().
Referenced by rl_vi_yank_arg().
rl_yank_pop()
int rl_yank_pop (int count, int key)
Definition at line 528 of file kill.c.
 {
   int l, n;
   if (((rl_last_func != rl_yank_pop) && (rl_last_func != rl_yank)) ||
       !rl_kill_ring)
     {
       _rl_abort_internal ();
       return 1;
     }
   l = strlen (rl_kill_ring[rl_kill_index]);
   n = rl_point - l;
   if (n >= 0 && STREQN (rl_line_buffer + n, rl_kill_ring[rl_kill_index], l))
     {
       rl_delete_text (n, rl_point);
       rl_point = n;
       rl_kill_index--;
       if (rl_kill_index < 0)
     rl_kill_index = rl_kill_ring_length - 1;
       rl_yank (1, 0);
       return 0;
     }
   else
     {
       _rl_abort_internal ();
       return 1;
     }
 }
References _rl_abort_internal(), l, n, rl_delete_text(), rl_kill_index, rl_kill_ring, rl_kill_ring_length, rl_last_func, rl_line_buffer, rl_point, rl_yank(), STREQN, and strlen().
Variable Documentation
funmap
FUNMAP** funmap extern
Definition at line 51 of file funmap.c.
Referenced by rl_add_funmap_entry(), rl_funmap_names(), and rl_named_function().
rl_already_prompted
int rl_already_prompted extern
Definition at line 195 of file readline.c.
Referenced by readline_internal_setup().
rl_attempted_completion_function
rl_completion_func_t* rl_attempted_completion_function extern
Definition at line 277 of file complete.c.
Referenced by gen_completion_matches(), initialize_readline(), rl_restore_state(), and rl_save_state().
rl_attempted_completion_over
int rl_attempted_completion_over extern
Definition at line 281 of file complete.c.
Referenced by gen_completion_matches().
rl_basic_quote_characters
const char* rl_basic_quote_characters extern
Definition at line 302 of file complete.c.
Referenced by _rl_find_completion_word(), and find_matching_open().
rl_basic_word_break_characters
const char* rl_basic_word_break_characters extern
Definition at line 299 of file complete.c.
Referenced by readline_initialize_everything().
rl_binding_keymap
Keymap rl_binding_keymap extern
Definition at line 73 of file bind.c.
Referenced by rl_bind_key(), and rl_generic_bind().
rl_catch_signals
int rl_catch_signals extern
Definition at line 80 of file signals.c.
Referenced by rl_clear_signals(), rl_restore_state(), rl_save_state(), and rl_set_signals().
rl_catch_sigwinch
int rl_catch_sigwinch extern
Definition at line 86 of file signals.c.
Referenced by rl_clear_signals(), rl_restore_state(), rl_save_state(), and rl_set_signals().
rl_change_environment
int rl_change_environment extern
Definition at line 90 of file terminal.c.
Referenced by _rl_get_screen_size().
rl_char_is_quoted_p
rl_linebuf_func_t* rl_char_is_quoted_p extern
Definition at line 369 of file complete.c.
Referenced by _rl_find_completion_word().
rl_completer_quote_characters
const char* rl_completer_quote_characters extern
Definition at line 318 of file complete.c.
Referenced by _rl_find_completion_word(), make_quoted_replacement(), and rl_quote_filename().
rl_completer_word_break_characters
const char* rl_completer_word_break_characters extern
Definition at line 307 of file complete.c.
Referenced by _rl_find_completion_word(), readline_initialize_everything(), rl_restore_state(), and rl_save_state().
rl_completion_append_character
int rl_completion_append_character extern
Definition at line 378 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_display_matches_hook
rl_compdisp_func_t* rl_completion_display_matches_hook extern
Definition at line 108 of file complete.c.
Referenced by display_matches(), and rl_complete_internal().
rl_completion_entry_function
rl_compentry_func_t* rl_completion_entry_function extern
Definition at line 264 of file complete.c.
Referenced by rl_complete_internal(), rl_menu_complete(), rl_old_menu_complete(), rl_restore_state(), and rl_save_state().
rl_completion_found_quote
int rl_completion_found_quote extern
Definition at line 391 of file complete.c.
Referenced by _rl_reset_completion_state(), compare_match(), compute_lcd_of_matches(), gen_completion_matches(), and rl_filename_completion_function().
rl_completion_invoking_key
int rl_completion_invoking_key extern
Definition at line 408 of file complete.c.
Referenced by rl_complete(), rl_insert_completions(), rl_old_menu_complete(), and rl_possible_completions().
rl_completion_mark_symlink_dirs
int rl_completion_mark_symlink_dirs extern
Definition at line 402 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_query_items
int rl_completion_query_items extern
Definition at line 292 of file complete.c.
Referenced by _rl_get_string_variable_value(), display_matches(), rl_menu_complete(), and sv_compquery().
rl_completion_quote_character
int rl_completion_quote_character extern
Definition at line 387 of file complete.c.
Referenced by _rl_reset_completion_state(), compare_match(), compute_lcd_of_matches(), gen_completion_matches(), and rl_filename_completion_function().
rl_completion_suppress_append
int rl_completion_suppress_append extern
Definition at line 374 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_suppress_quote
int rl_completion_suppress_quote extern
Definition at line 383 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_type
int rl_completion_type extern
Definition at line 286 of file complete.c.
Referenced by set_completion_defaults().
rl_completion_word_break_hook
rl_cpvfunc_t* rl_completion_word_break_hook extern
Definition at line 312 of file complete.c.
Referenced by _rl_find_completion_word().
rl_deprep_term_function
rl_voidfunc_t* rl_deprep_term_function extern
Definition at line 53 of file rltty.c.
Referenced by exit_shell(), readline(), rl_callback_handler_remove(), rl_callback_read_char(), and rl_cleanup_after_signal().
rl_directory_completion_hook
rl_icppfunc_t* rl_directory_completion_hook extern
Definition at line 241 of file complete.c.
Referenced by print_filename(), and rl_filename_completion_function().
rl_directory_rewrite_hook
rl_icppfunc_t* rl_directory_rewrite_hook extern
Definition at line 243 of file complete.c.
Referenced by rl_filename_completion_function().
rl_dispatching
int rl_dispatching extern
Definition at line 130 of file readline.c.
Referenced by _rl_dispatch_subseq(), readline_internal_char(), rl_dump_functions(), rl_dump_macros(), and rl_dump_variables().
rl_display_prompt
char* rl_display_prompt extern
Definition at line 177 of file display.c.
Referenced by _rl_current_display_line(), _rl_redisplay_after_sigwinch(), redraw_prompt(), rl_clear_message(), rl_message(), rl_on_new_line_with_prompt(), rl_redisplay(), rl_redraw_prompt_last_line(), rl_reset_line_state(), and rl_set_prompt().
rl_done
int rl_done extern
Definition at line 165 of file readline.c.
Referenced by _rl_arg_dispatch(), _rl_internal_char_cleanup(), readline_internal_char(), readline_internal_charloop(), rl_callback_read_char(), rl_initialize(), rl_insert(), rl_newline(), rl_read_key(), rl_restore_state(), and rl_save_state().
rl_editing_mode
int rl_editing_mode extern
Definition at line 122 of file readline.c.
Referenced by _rl_copy_to_kill_ring(), _rl_dispatch_subseq(), _rl_history_set_point(), _rl_internal_char_cleanup(), make_history_line_current(), noninc_dosearch(), parser_if(), prompt_modestr(), readline_internal_setup(), rl_backward_kill_line(), rl_backward_kill_word(), rl_complete_internal(), rl_emacs_editing_mode(), rl_fetch_history(), rl_get_keymap_name_from_edit_mode(), rl_initialize(), rl_kill_line(), rl_kill_word(), rl_newline(), rl_prep_terminal(), rl_replace_from_history(), rl_restore_state(), rl_revert_line(), rl_save_state(), rl_set_keymap_from_edit_mode(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_editing_mode(), rl_yank_nth_arg_internal(), and sv_editmode().
rl_end
int rl_end extern
Definition at line 162 of file readline.c.
Referenced by _rl_char_search_internal(), _rl_forward_char_internal(), _rl_history_set_point(), _rl_init_line_state(), _rl_internal_char_cleanup(), _rl_isearch_dispatch(), _rl_mvcxt_init(), _rl_nsearch_init(), _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_rubout_char(), _rl_set_mark_at_pos(), _rl_vi_advance_point(), _rl_vi_change_char(), _rl_vi_domove_motion_cleanup(), append_to_match(), insert_match(), invert_case_line(), make_history_line_current(), noninc_dosearch(), readline_internal_char(), rl_change_case(), rl_delete(), rl_delete_horizontal_space(), rl_delete_or_show_completions(), rl_delete_text(), rl_domove_motion_callback(), rl_domove_read_callback(), rl_end_of_line(), rl_exchange_point_and_mark(), rl_forward_byte(), rl_forward_word(), rl_get_next_history(), rl_get_previous_history(), rl_history_search_internal(), rl_insert_text(), rl_kill_full_line(), rl_maybe_unsave_line(), rl_newline(), rl_redisplay(), rl_replace_from_history(), rl_replace_line(), rl_restore_state(), rl_rubout_or_delete(), rl_save_state(), rl_tilde_expand(), rl_transpose_chars(), rl_transpose_words(), rl_vi_back_to_indent(), rl_vi_change_case(), rl_vi_change_to(), rl_vi_check(), rl_vi_column(), rl_vi_complete(), rl_vi_delete(), rl_vi_delete_to(), rl_vi_eWord(), rl_vi_eword(), rl_vi_fWord(), rl_vi_fword(), rl_vi_match(), rl_vi_next_word(), rl_vi_overstrike_kill_line(), rl_vi_overstrike_kill_word(), rl_vi_overstrike_yank(), rl_vi_put(), rl_vi_yank_to(), set_active_region(), vi_change_dispatch(), vi_delete_dispatch(), and vi_yank_dispatch().
rl_eof_found
int rl_eof_found extern
Definition at line 168 of file readline.c.
Referenced by readline_internal(), rl_callback_read_char(), and rl_deprep_terminal().
rl_erase_empty_line
int rl_erase_empty_line extern
Definition at line 250 of file readline.c.
Referenced by _rl_internal_char_cleanup(), and rl_newline().
rl_event_hook
rl_hook_func_t* rl_event_hook extern
Definition at line 88 of file input.c.
Referenced by rl_read_key().
rl_executing_key
int rl_executing_key extern
Definition at line 263 of file readline.c.
Referenced by _rl_dispatch_subseq(), and readline_internal_char().
rl_executing_keymap
Keymap rl_executing_keymap extern
Definition at line 241 of file readline.c.
Referenced by _rl_dispatch_subseq(), and readline_internal_char().
rl_executing_keyseq
char* rl_executing_keyseq extern
Definition at line 264 of file readline.c.
Referenced by _rl_add_executing_keyseq(), _rl_dispatch_subseq(), _rl_end_executing_keyseq(), _rl_init_executing_keyseq(), _rl_subseq_result(), _rl_term_executing_keyseq(), readline_initialize_everything(), readline_internal_char(), rl_insert(), rl_restore_state(), and rl_save_state().
rl_executing_macro
char* rl_executing_macro extern
Definition at line 62 of file macro.c.
Referenced by _rl_abort_internal(), _rl_kill_kbd_macro(), _rl_next_macro_key(), _rl_peek_macro_key(), _rl_pop_executing_macro(), _rl_prev_macro_key(), _rl_push_executing_macro(), _rl_with_macro_input(), rl_restore_state(), and rl_save_state().
rl_explicit_arg
int rl_explicit_arg extern
Definition at line 139 of file readline.c.
Referenced by _rl_arg_dispatch(), _rl_arg_overflow(), _rl_overwrite_rubout(), _rl_reset_argument(), _rl_rubout_char(), _rl_vi_arg_dispatch(), rl_clear_screen(), rl_delete(), rl_domove_read_callback(), rl_dump_functions(), rl_dump_macros(), rl_dump_variables(), rl_fetch_history(), rl_insert_close(), rl_insert_comment(), rl_operate_and_get_next(), rl_overwrite_mode(), rl_set_mark(), rl_start_kbd_macro(), rl_vi_arg_digit(), rl_vi_redo(), rl_vi_yank_arg(), and rl_yank_last_arg().
rl_filename_completion_desired
int rl_filename_completion_desired extern
Definition at line 334 of file complete.c.
Referenced by append_to_match(), compare_match(), compute_lcd_of_matches(), make_quoted_replacement(), print_filename(), printable_part(), rl_complete_internal(), rl_display_match_list(), rl_filename_completion_function(), rl_menu_complete(), rl_old_menu_complete(), rl_username_completion_function(), and set_completion_defaults().
rl_filename_dequoting_function
rl_dequote_func_t* rl_filename_dequoting_function extern
Definition at line 364 of file complete.c.
Referenced by compare_match(), compute_lcd_of_matches(), and rl_filename_completion_function().
rl_filename_quote_characters
const char* rl_filename_quote_characters extern
Definition at line 321 of file complete.c.
Referenced by make_quoted_replacement().
rl_filename_quoting_desired
int rl_filename_quoting_desired extern
Definition at line 341 of file complete.c.
Referenced by compare_match(), compute_lcd_of_matches(), make_quoted_replacement(), and set_completion_defaults().
rl_filename_quoting_function
rl_quote_func_t* rl_filename_quoting_function extern
Definition at line 358 of file complete.c.
Referenced by make_quoted_replacement().
rl_filename_rewrite_hook
rl_dequote_func_t* rl_filename_rewrite_hook extern
Definition at line 256 of file complete.c.
Referenced by rl_filename_completion_function().
rl_filename_stat_hook
rl_icppfunc_t* rl_filename_stat_hook extern
Definition at line 245 of file complete.c.
Referenced by _rl_print_color_indicator(), append_to_match(), print_filename(), and stat_char().
rl_getc_function
rl_getc_func_t* rl_getc_function extern
Definition at line 100 of file input.c.
Referenced by rl_read_key().
rl_gnu_readline_p
int rl_gnu_readline_p extern
Definition at line 115 of file readline.c.
rl_ignore_completion_duplicates
int rl_ignore_completion_duplicates extern
Definition at line 329 of file complete.c.
Referenced by postprocess_matches(), and rl_display_match_list().
rl_ignore_some_completions_function
rl_compignore_func_t* rl_ignore_some_completions_function extern
Definition at line 352 of file complete.c.
Referenced by postprocess_matches(), rl_restore_state(), and rl_save_state().
rl_inhibit_completion
int rl_inhibit_completion extern
Definition at line 405 of file complete.c.
Referenced by rl_complete().
rl_input_available_hook
rl_hook_func_t* rl_input_available_hook extern
Definition at line 98 of file input.c.
Referenced by _rl_input_available().
rl_insert_mode
int rl_insert_mode extern
Definition at line 125 of file readline.c.
Referenced by _rl_set_cursor(), _rl_set_insert_mode(), rl_insert(), rl_overwrite_mode(), rl_restore_state(), rl_rubout(), and rl_save_state().
rl_instream
FILE* rl_instream extern
Definition at line 180 of file readline.c.
Referenced by _rl_init_terminal_io(), _rl_input_available(), _rl_nchars_available(), _rl_sigwinch_resize_terminal(), main(), readline_initialize_everything(), readline_internal_setup(), rl_deprep_terminal(), rl_gather_tyi(), rl_insert_close(), rl_prep_terminal(), rl_read_key(), rl_reset_screen_size(), rl_resize_terminal(), rl_restore_state(), rl_save_state(), rl_stop_output(), and rltty_set_default_bindings().
rl_key_sequence_length
int rl_key_sequence_length extern
Definition at line 198 of file readline.c.
Referenced by _rl_add_executing_keyseq(), _rl_del_executing_keyseq(), _rl_dispatch_subseq(), _rl_end_executing_keyseq(), _rl_init_executing_keyseq(), _rl_subseq_result(), _rl_term_executing_keyseq(), readline_initialize_everything(), readline_internal_char(), rl_end_kbd_macro(), rl_insert(), rl_restore_state(), and rl_save_state().
rl_last_func
rl_command_func_t* rl_last_func extern
Definition at line 171 of file readline.c.
Referenced by _rl_abort_internal(), _rl_dispatch_subseq(), _rl_internal_char_cleanup(), rl_complete(), rl_completion_mode(), rl_history_search_backward(), rl_history_search_forward(), rl_history_substr_search_backward(), rl_history_substr_search_forward(), rl_initialize(), rl_insert(), rl_menu_complete(), rl_old_menu_complete(), rl_restore_state(), rl_save_state(), rl_vi_yank_pop(), rl_yank_last_arg(), and rl_yank_pop().
rl_library_version
const char* rl_library_version extern
Definition at line 110 of file readline.c.
rl_line_buffer
char* rl_line_buffer extern
Definition at line 257 of file readline.c.
Referenced by _rl_backward_char_internal(), _rl_char_search_internal(), _rl_find_completion_word(), _rl_forward_char_internal(), _rl_init_line_state(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_isearch_init(), _rl_nsearch_dosearch(), _rl_nsearch_init(), _rl_overwrite_rubout(), _rl_revert_previous_lines(), _rl_rubout_char(), _rl_set_the_line(), _rl_vi_backup(), _rl_vi_domove_motion_cleanup(), append_to_match(), change_prompt(), insert_all_matches(), insert_match(), invert_case_line(), readline_initialize_everything(), rl_backward_word(), rl_callback_read_char(), rl_change_case(), rl_complete_internal(), rl_copy_text(), rl_delete(), rl_delete_horizontal_space(), rl_delete_text(), rl_do_undo(), rl_domove_motion_callback(), rl_extend_line_buffer(), rl_forward_word(), rl_history_search_internal(), rl_history_search_reinit(), rl_insert_close(), rl_insert_comment(), rl_insert_text(), rl_maybe_replace_line(), rl_maybe_save_line(), rl_redisplay(), rl_replace_line(), rl_restore_state(), rl_save_state(), rl_tilde_expand(), rl_transpose_chars(), rl_unix_filename_rubout(), rl_unix_word_rubout(), rl_vi_back_to_indent(), rl_vi_bWord(), rl_vi_bword(), rl_vi_change_case(), rl_vi_complete(), rl_vi_delete(), rl_vi_eWord(), rl_vi_eword(), rl_vi_fWord(), rl_vi_fword(), rl_vi_match(), rl_vi_put(), rl_vi_rubout(), rl_vi_unix_word_rubout(), rl_vi_yank_pop(), rl_yank_pop(), and vi_save_insert_buffer().
rl_mark
int rl_mark extern
Definition at line 159 of file readline.c.
Referenced by _rl_copy_word_as_kill(), _rl_fix_mark(), _rl_fix_point(), _rl_history_set_point(), _rl_init_line_state(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_nsearch_abort(), _rl_nsearch_dosearch(), _rl_scxt_alloc(), _rl_set_mark_at_pos(), _rl_vi_domove_motion_cleanup(), _rl_vi_goto_mark(), noninc_dosearch(), region_kill_internal(), rl_backward_kill_line(), rl_backward_kill_word(), rl_bracketed_paste_begin(), rl_domove_read_callback(), rl_exchange_point_and_mark(), rl_history_search_internal(), rl_kill_full_line(), rl_kill_line(), rl_kill_region(), rl_kill_word(), rl_replace_from_history(), rl_restore_state(), rl_revert_line(), rl_save_state(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_change_to(), rl_vi_delete_to(), rl_vi_yank_to(), set_active_region(), vi_change_dispatch(), vi_delete_dispatch(), and vi_yank_dispatch().
rl_menu_completion_entry_function
rl_compentry_func_t* rl_menu_completion_entry_function extern
Definition at line 268 of file complete.c.
Referenced by rl_menu_complete(), rl_old_menu_complete(), rl_restore_state(), and rl_save_state().
rl_num_chars_to_read
int rl_num_chars_to_read extern
Definition at line 254 of file readline.c.
Referenced by _rl_internal_char_cleanup(), main(), and rl_insert().
rl_numeric_arg
int rl_numeric_arg extern
Definition at line 136 of file readline.c.
Referenced by _rl_arg_callback(), _rl_arg_dispatch(), _rl_arg_getchar(), _rl_arg_overflow(), _rl_dispatch_subseq(), _rl_reset_argument(), _rl_vi_arg_dispatch(), rl_digit_argument(), rl_domove_read_callback(), rl_universal_argument(), rl_vi_arg_digit(), rl_vi_redo(), and vi_change_dispatch().
rl_outstream
FILE* rl_outstream extern
Definition at line 181 of file readline.c.
Referenced by _rl_clean_up_for_exit(), _rl_cr(), _rl_erase_at_end_of_line(), _rl_erase_entire_line(), _rl_internal_pager(), _rl_macro_dumper_internal(), _rl_move_vert(), _rl_put_indicator(), _rl_ttyflush(), _rl_update_final(), display_matches(), fnprint(), print_filename(), putc_face(), readline_initialize_everything(), readline_internal_setup(), rl_deprep_terminal(), rl_display_match_list(), rl_dump_functions(), rl_dump_macros(), rl_dump_variables(), rl_function_dumper(), rl_list_funmap_names(), rl_prep_terminal(), rl_redisplay(), rl_restart_output(), rl_restore_state(), rl_save_state(), rl_show_char(), rl_variable_dumper(), space_to_eol(), and update_line().
rl_pending_input
int rl_pending_input extern
Definition at line 221 of file readline.c.
Referenced by _rl_dispatch_subseq(), readline(), readline_internal_char(), rl_callback_read_char(), rl_clear_pending_input(), rl_execute_next(), rl_read_key(), rl_restore_state(), rl_save_state(), and rl_stuff_char().
rl_persistent_signal_handlers
int rl_persistent_signal_handlers extern
Definition at line 59 of file callback.c.
Referenced by _rl_callback_newline(), and rl_callback_read_char().
rl_point
int rl_point extern
Definition at line 156 of file readline.c.
Referenced by _rl_backward_char_internal(), _rl_char_search_internal(), _rl_copy_word_as_kill(), _rl_find_completion_word(), _rl_fix_point(), _rl_forward_char_internal(), _rl_history_set_point(), _rl_init_line_state(), _rl_internal_char_cleanup(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_isearch_init(), _rl_mvcxt_init(), _rl_nsearch_abort(), _rl_nsearch_dispatch(), _rl_nsearch_dosearch(), _rl_nsearch_init(), _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_replace_text(), _rl_rubout_char(), _rl_scxt_alloc(), _rl_vi_advance_point(), _rl_vi_backup(), _rl_vi_backup_point(), _rl_vi_change_char(), _rl_vi_domove_motion_cleanup(), _rl_vi_goto_mark(), _rl_vi_replace_insert(), _rl_vi_save_replace(), _rl_vi_set_mark(), append_to_match(), insert_all_matches(), insert_match(), invert_case_line(), noninc_dosearch(), region_kill_internal(), rl_backward_byte(), rl_backward_kill_line(), rl_backward_kill_word(), rl_backward_word(), rl_beg_of_line(), rl_bracketed_paste_begin(), rl_change_case(), rl_complete_internal(), rl_delete(), rl_delete_horizontal_space(), rl_delete_or_show_completions(), rl_do_undo(), rl_end_of_line(), rl_exchange_point_and_mark(), rl_forward_byte(), rl_forward_word(), rl_get_next_history(), rl_get_previous_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_insert_close(), rl_insert_comment(), rl_insert_text(), rl_kill_full_line(), rl_kill_line(), rl_kill_region(), rl_kill_word(), rl_maybe_unsave_line(), rl_menu_complete(), rl_newline(), rl_old_menu_complete(), rl_redisplay(), rl_replace_from_history(), rl_restore_state(), rl_revert_line(), rl_rubout(), rl_rubout_or_delete(), rl_save_state(), rl_set_mark(), rl_tilde_expand(), rl_transpose_chars(), rl_transpose_words(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_back_to_indent(), rl_vi_bWord(), rl_vi_bword(), rl_vi_change_case(), rl_vi_change_to(), rl_vi_check(), rl_vi_column(), rl_vi_complete(), rl_vi_delete(), rl_vi_delete_to(), rl_vi_eWord(), rl_vi_eword(), rl_vi_fWord(), rl_vi_fword(), rl_vi_match(), rl_vi_movement_mode(), rl_vi_next_word(), rl_vi_overstrike_delete(), rl_vi_prev_word(), rl_vi_put(), rl_vi_redo(), rl_vi_rubout(), rl_vi_unix_word_rubout(), rl_vi_yank_pop(), rl_vi_yank_to(), rl_yank(), rl_yank_nth_arg_internal(), rl_yank_pop(), set_active_region(), vi_change_dispatch(), vi_delete_dispatch(), and vi_yank_dispatch().
rl_pre_input_hook
rl_hook_func_t* rl_pre_input_hook extern
Definition at line 211 of file readline.c.
Referenced by readline_internal_setup().
rl_prefer_env_winsize
int rl_prefer_env_winsize extern
Definition at line 86 of file terminal.c.
Referenced by _rl_get_screen_size(), and initialize_shell_variables().
rl_prep_term_function
rl_vintfunc_t* rl_prep_term_function extern
Definition at line 52 of file rltty.c.
Referenced by _rl_callback_newline(), readline(), and rl_reset_after_signal().
rl_prompt
char* rl_prompt extern
Definition at line 190 of file readline.c.
Referenced by _rl_current_display_line(), _rl_make_prompt_for_search(), _rl_reset_prompt(), expand_prompt(), readline_internal_setup(), rl_clear_message(), rl_on_new_line_with_prompt(), rl_redisplay(), rl_reset_line_state(), rl_restore_state(), rl_save_state(), and rl_set_prompt().
rl_readline_name
const char* rl_readline_name extern
Definition at line 1245 of file bind.c.
Referenced by initialize_readline(), and parser_if().
rl_readline_state
unsigned long rl_readline_state extern
Definition at line 153 of file readline.c.
Referenced by rl_restore_state(), and rl_save_state().
rl_readline_version
int rl_readline_version extern
Definition at line 112 of file readline.c.
rl_redisplay_function
rl_voidfunc_t* rl_redisplay_function extern
Definition at line 169 of file display.c.
Referenced by readline_internal_setup().
rl_signal_event_hook
rl_hook_func_t* rl_signal_event_hook extern
Definition at line 91 of file input.c.
Referenced by _rl_signal_handler(), readline_internal_char(), rl_complete_internal(), and rl_getc().
rl_sort_completion_matches
int rl_sort_completion_matches extern
Definition at line 411 of file complete.c.
Referenced by compute_lcd_of_matches(), remove_duplicate_matches(), and rl_display_match_list().
rl_special_prefixes
const char* rl_special_prefixes extern
Definition at line 326 of file complete.c.
Referenced by _rl_find_completion_word().
rl_startup_hook
rl_hook_func_t* rl_startup_hook extern
Definition at line 202 of file readline.c.
Referenced by main(), run_startup_hooks(), and set_deftext().
rl_terminal_name
const char* rl_terminal_name extern
Definition at line 224 of file readline.c.
Referenced by _rl_set_screen_size(), parser_if(), and readline_initialize_everything().
rl_timeout_event_hook
rl_hook_func_t* rl_timeout_event_hook extern
Definition at line 94 of file input.c.
Referenced by _rl_timeout_handle().
rl_undo_list
UNDO_LIST* rl_undo_list extern
Definition at line 62 of file undo.c.
Referenced by _rl_fix_last_undo_of_type(), _rl_free_saved_history_line(), _rl_nsearch_init(), _rl_revert_previous_lines(), _rl_vi_done_inserting(), _rl_vi_save_replace(), make_history_line_current(), readline_internal_teardown(), rl_add_undo(), rl_clear_history(), rl_do_undo(), rl_free_undo_list(), rl_insert_text(), rl_maybe_replace_line(), rl_maybe_save_line(), rl_maybe_unsave_line(), rl_redisplay(), rl_replace_from_history(), rl_restore_state(), rl_revert_line(), and rl_save_state().