Fennix: Userspace/libs/libinit/printf.c File Reference
printf.c File Reference
#include "printf.h"
#include <types.h>
#include <limits.h>
Data Structures
struct output_gadget_t
Macros
#define PRINTF_INTEGER_BUFFER_SIZE 32
Small stand-alone implementation of the printf family of functions ((v)printf, (v)s(n)printf etc., geared towards use on embedded systems with a very limited resources.
#define PRINTF_DECIMAL_BUFFER_SIZE 32
#define PRINTF_SUPPORT_WRITEBACK_SPECIFIER 1
#define PRINTF_DEFAULT_FLOAT_PRECISION 6
#define PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL 9
#define PRINTF_SUPPORT_LONG_LONG 1
#define PRINTF_LOG10_TAYLOR_TERMS 4
#define PRINTF_CHECK_FOR_NUL_IN_FORMAT_SPECIFIER 1
#define PRINTF_PREFER_DECIMAL false
#define PRINTF_PREFER_EXPONENTIAL true
#define PRINTF_CONCATENATE(s1, s2) s1##s2
#define PRINTF_EXPAND_THEN_CONCATENATE(s1, s2) PRINTF_CONCATENATE(s1, s2)
#define PRINTF_FLOAT_NOTATION_THRESHOLD PRINTF_EXPAND_THEN_CONCATENATE(1e, PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL)
#define FLAGS_ZEROPAD (1U << 0U)
#define FLAGS_LEFT (1U << 1U)
#define FLAGS_PLUS (1U << 2U)
#define FLAGS_SPACE (1U << 3U)
#define FLAGS_HASH (1U << 4U)
#define FLAGS_UPPERCASE (1U << 5U)
#define FLAGS_CHAR (1U << 6U)
#define FLAGS_SHORT (1U << 7U)
#define FLAGS_INT (1U << 8U)
#define FLAGS_LONG (1U << 9U)
#define FLAGS_LONG_LONG (1U << 10U)
#define FLAGS_PRECISION (1U << 11U)
#define FLAGS_ADAPT_EXP (1U << 12U)
#define FLAGS_POINTER (1U << 13U)
#define FLAGS_SIGNED (1U << 14U)
#define BASE_BINARY 2
#define BASE_OCTAL 8
#define BASE_DECIMAL 10
#define BASE_HEX 16
#define PRINTF_MAX_POSSIBLE_BUFFER_SIZE INT_MAX
#define ABS_FOR_PRINTING(_x) ((printf_unsigned_value_t)((_x) > 0 ? (_x) : -((printf_signed_value_t)_x)))
#define ADVANCE_IN_FORMAT_STRING(cptr_)
Typedefs
typedef unsigned int printf_flags_t
typedef uint8_t numeric_base_t
typedef unsigned long long printf_unsigned_value_t
typedef long long printf_signed_value_t
typedef unsigned int printf_size_t
Functions
static void putchar_via_gadget_libint (output_gadget_t *gadget, char c)
static void append_termination_with_gadget_libint (output_gadget_t *gadget)
static void putchar_wrapper_libint (char c, void *unused)
static output_gadget_t discarding_gadget_libint (void)
static output_gadget_t buffer_gadget_libint (char *buffer, size_t buffer_size)
static output_gadget_t function_gadget_libint (void(*function)(char, void *), void *extra_arg)
static output_gadget_t extern_putchar_gadget_libint (void)
static printf_size_t strnlen_s_libint (const char *str, printf_size_t maxsize)
static bool is_digit_libint (char ch)
static printf_size_t atou_libint (const char **str)
static void out_rev_libint (output_gadget_t *output, const char *buf, printf_size_t len, printf_size_t width, printf_flags_t flags)
static void print_integer_finalization_libint (output_gadget_t *output, char *buf, printf_size_t len, bool negative, numeric_base_t base, printf_size_t precision, printf_size_t width, printf_flags_t flags)
static void print_integer_libint (output_gadget_t *output, printf_unsigned_value_t value, bool negative, numeric_base_t base, printf_size_t precision, printf_size_t width, printf_flags_t flags)
static printf_flags_t parse_flags_libint (const char **format)
static void format_string_loop_libint (output_gadget_t *output, const char *format, va_list args)
static int vsnprintf_impl_libint (output_gadget_t *output, const char *format, va_list args)
int vprintf_libinit (const char *format, va_list arg)
int vsnprintf_libinit (char *s, size_t n, const char *format, va_list arg)
int vsprintf_libinit (char *s, const char *format, va_list arg)
int vfctprintf_libinit (void(*out)(char c, void *extra_arg), void *extra_arg, const char *format, va_list arg)
int printf_libinit (const char *format,...)
int sprintf_libinit (char *s, const char *format,...)
int snprintf_libinit (char *s, size_t n, const char *format,...)
int fctprintf_libinit (void(*out)(char c, void *extra_arg), void *extra_arg, const char *format,...)
Macro Definition Documentation
ABS_FOR_PRINTING
#define ABS_FOR_PRINTING (_x) ((printf_unsigned_value_t)((_x) > 0 ? (_x) : -((printf_signed_value_t)_x)))
Definition at line 297 of file printf.c.
ADVANCE_IN_FORMAT_STRING
#define ADVANCE_IN_FORMAT_STRING (cptr_)
Value:
    do                                  \
    {                                   \
        (cptr_)++;                      \
        if (!*(cptr_))                  \
            return;                     \
    } while (0)
BASE_BINARY
#define BASE_BINARY 2
Definition at line 203 of file printf.c.
BASE_DECIMAL
#define BASE_DECIMAL 10
Definition at line 205 of file printf.c.
BASE_HEX
#define BASE_HEX 16
Definition at line 206 of file printf.c.
BASE_OCTAL
#define BASE_OCTAL 8
Definition at line 204 of file printf.c.
FLAGS_ADAPT_EXP
#define FLAGS_ADAPT_EXP (1U << 12U)
Definition at line 153 of file printf.c.
FLAGS_CHAR
#define FLAGS_CHAR (1U << 6U)
Definition at line 146 of file printf.c.
FLAGS_HASH
#define FLAGS_HASH (1U << 4U)
Definition at line 144 of file printf.c.
FLAGS_INT
#define FLAGS_INT (1U << 8U)
Definition at line 148 of file printf.c.
FLAGS_LEFT
#define FLAGS_LEFT (1U << 1U)
Definition at line 141 of file printf.c.
FLAGS_LONG
#define FLAGS_LONG (1U << 9U)
Definition at line 150 of file printf.c.
FLAGS_LONG_LONG
#define FLAGS_LONG_LONG (1U << 10U)
Definition at line 151 of file printf.c.
FLAGS_PLUS
#define FLAGS_PLUS (1U << 2U)
Definition at line 142 of file printf.c.
FLAGS_POINTER
#define FLAGS_POINTER (1U << 13U)
Definition at line 154 of file printf.c.
FLAGS_PRECISION
#define FLAGS_PRECISION (1U << 11U)
Definition at line 152 of file printf.c.
FLAGS_SHORT
#define FLAGS_SHORT (1U << 7U)
Definition at line 147 of file printf.c.
FLAGS_SIGNED
#define FLAGS_SIGNED (1U << 14U)
Definition at line 156 of file printf.c.
FLAGS_SPACE
#define FLAGS_SPACE (1U << 3U)
Definition at line 143 of file printf.c.
FLAGS_UPPERCASE
#define FLAGS_UPPERCASE (1U << 5U)
Definition at line 145 of file printf.c.
FLAGS_ZEROPAD
#define FLAGS_ZEROPAD (1U << 0U)
Definition at line 140 of file printf.c.
PRINTF_CHECK_FOR_NUL_IN_FORMAT_SPECIFIER
#define PRINTF_CHECK_FOR_NUL_IN_FORMAT_SPECIFIER 1
Definition at line 126 of file printf.c.
PRINTF_CONCATENATE
#define PRINTF_CONCATENATE (s1, s2) s1##s2
Definition at line 135 of file printf.c.
PRINTF_DECIMAL_BUFFER_SIZE
#define PRINTF_DECIMAL_BUFFER_SIZE 32
Definition at line 75 of file printf.c.
PRINTF_DEFAULT_FLOAT_PRECISION
#define PRINTF_DEFAULT_FLOAT_PRECISION 6
Definition at line 95 of file printf.c.
PRINTF_EXPAND_THEN_CONCATENATE
#define PRINTF_EXPAND_THEN_CONCATENATE (s1, s2) PRINTF_CONCATENATE(s1, s2)
Definition at line 136 of file printf.c.
PRINTF_FLOAT_NOTATION_THRESHOLD
#define PRINTF_FLOAT_NOTATION_THRESHOLD PRINTF_EXPAND_THEN_CONCATENATE(1e, PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL)
Definition at line 137 of file printf.c.
PRINTF_INTEGER_BUFFER_SIZE
#define PRINTF_INTEGER_BUFFER_SIZE 32
Small stand-alone implementation of the printf family of functions ((v)printf, (v)s(n)printf etc., geared towards use on embedded systems with a very limited resources.
Author
(c) Eyal Rozenberg eyalr.nosp@m.oz1@.nosp@m.gmx.c.nosp@m.om 2021-2022, Haifa, Palestine/Israel
(c) Marco Paland (info@.nosp@m.pala.nosp@m.nd.co.nosp@m.m) 2014-2019, PALANDesign Hannover, Germany
Note
Others have made smaller contributions to this file: see the contributors page at https://github.com/eyalroz/printf/graphs/contributors or ask one of the authors. The original code for exponential specifiers was contributed by Martijn Jasperse m.jas.nosp@m.pers.nosp@m.e@gma.nosp@m.il.c.nosp@m.om.
the implementations are thread-safe; re-entrant; use no functions from the standard library; and do not dynamically allocate any memory.
@license The MIT License (MIT)
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 68 of file printf.c.
PRINTF_LOG10_TAYLOR_TERMS
#define PRINTF_LOG10_TAYLOR_TERMS 4
Definition at line 116 of file printf.c.
PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL
#define PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL 9
Definition at line 103 of file printf.c.
PRINTF_MAX_POSSIBLE_BUFFER_SIZE
#define PRINTF_MAX_POSSIBLE_BUFFER_SIZE INT_MAX
Definition at line 224 of file printf.c.
PRINTF_PREFER_DECIMAL
#define PRINTF_PREFER_DECIMAL false
Definition at line 129 of file printf.c.
PRINTF_PREFER_EXPONENTIAL
#define PRINTF_PREFER_EXPONENTIAL true
Definition at line 130 of file printf.c.
PRINTF_SUPPORT_LONG_LONG
#define PRINTF_SUPPORT_LONG_LONG 1
Definition at line 109 of file printf.c.
PRINTF_SUPPORT_WRITEBACK_SPECIFIER
#define PRINTF_SUPPORT_WRITEBACK_SPECIFIER 1
Definition at line 90 of file printf.c.
Typedef Documentation
numeric_base_t
typedef uint8_t numeric_base_t
Definition at line 208 of file printf.c.
printf_flags_t
typedef unsigned int printf_flags_t
Definition at line 201 of file printf.c.
printf_signed_value_t
typedef long long printf_signed_value_t
Definition at line 212 of file printf.c.
printf_size_t
typedef unsigned int printf_size_t
Definition at line 223 of file printf.c.
printf_unsigned_value_t
typedef unsigned long long printf_unsigned_value_t
Definition at line 211 of file printf.c.
Function Documentation
append_termination_with_gadget_libint()
static void append_termination_with_gadget_libint (output_gadget_t * gadget) inline static
Definition at line 343 of file printf.c.
 {
     if (gadget->function != NULL || gadget->max_chars == 0)
     {
         return;
     }
     if (gadget->buffer == NULL)
     {
         return;
     }
     printf_size_t null_char_pos = gadget->pos < gadget->max_chars ? gadget->pos : gadget->max_chars - 1;
     gadget->buffer[null_char_pos] = '\0';
 }
References output_gadget_t::buffer, output_gadget_t::function, output_gadget_t::max_chars, NULL, and output_gadget_t::pos.
Referenced by vsnprintf_impl_libint().
atou_libint()
static printf_size_t atou_libint (const char ** str) static
Definition at line 425 of file printf.c.
 {
     printf_size_t i = 0U;
     while (is_digit_libint(**str))
     {
         i = i * 10U + (printf_size_t)(*((*str)++) - '0');
     }
     return i;
 }
References i, and is_digit_libint().
Referenced by format_string_loop_libint().
buffer_gadget_libint()
static output_gadget_t buffer_gadget_libint (char * buffer, size_t buffer_size) inline static
Definition at line 379 of file printf.c.
 {
     printf_size_t usable_buffer_size = (buffer_size > PRINTF_MAX_POSSIBLE_BUFFER_SIZE) ? PRINTF_MAX_POSSIBLE_BUFFER_SIZE : (printf_size_t)buffer_size;
     output_gadget_t result = discarding_gadget_libint();
     if (buffer != NULL)
     {
         result.buffer = buffer;
         result.max_chars = usable_buffer_size;
     }
     return result;
 }
References discarding_gadget_libint(), NULL, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, and mlibc::result.
Referenced by vsnprintf_libinit().
discarding_gadget_libint()
static output_gadget_t discarding_gadget_libint (void) inline static
Definition at line 368 of file printf.c.
 {
     output_gadget_t gadget;
     gadget.function = NULL;
     gadget.extra_function_arg = NULL;
     gadget.buffer = NULL;
     gadget.pos = 0;
     gadget.max_chars = 0;
     return gadget;
 }
References output_gadget_t::buffer, output_gadget_t::extra_function_arg, output_gadget_t::function, output_gadget_t::max_chars, NULL, and output_gadget_t::pos.
Referenced by buffer_gadget_libint(), and function_gadget_libint().
extern_putchar_gadget_libint()
static output_gadget_t extern_putchar_gadget_libint (void) inline static
Definition at line 400 of file printf.c.
 {
     return function_gadget_libint(putchar_wrapper_libint, NULL);
 }
References function_gadget_libint(), NULL, and putchar_wrapper_libint().
Referenced by vprintf_libinit().
fctprintf_libinit()
int fctprintf_libinit (void(*)(char c, void *extra_arg) out, void * extra_arg, const char * format, ...)
Definition at line 1584 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vfctprintf_libinit(out, extra_arg, format, args);
     va_end(args);
     return ret;
 }
References args, format, ret, va_end(), va_start(), and vfctprintf_libinit().
format_string_loop_libint()
static void format_string_loop_libint (output_gadget_t * output, const char * format, va_list args) inline static
Definition at line 1137 of file printf.c.
 {
 #if PRINTF_CHECK_FOR_NUL_IN_FORMAT_SPECIFIER
 #define ADVANCE_IN_FORMAT_STRING(cptr_) \
     do                                  \
     {                                   \
         (cptr_)++;                      \
         if (!*(cptr_))                  \
             return;                     \
     } while (0)
 #else
 #define ADVANCE_IN_FORMAT_STRING(cptr_) (cptr_)++
 #endif
     while (*format)
     {
         if (*format != '%')
         {
             // A regular content character
             putchar_via_gadget_libint(output, *format);
             format++;
             continue;
         }
         // We're parsing a format specifier: %[flags][width][.precision][length]
         ADVANCE_IN_FORMAT_STRING(format);
         printf_flags_t flags = parse_flags_libint(&format);
         // evaluate width field
         printf_size_t width = 0U;
         if (is_digit_libint(*format))
         {
             width = (printf_size_t)atou_libint(&format);
         }
         else if (*format == '*')
         {
             const int w = va_arg(args, int);
             if (w < 0)
             {
                 flags |= FLAGS_LEFT; // reverse padding
                 width = (printf_size_t)-w;
             }
             else
             {
                 width = (printf_size_t)w;
             }
             ADVANCE_IN_FORMAT_STRING(format);
         }
         // evaluate precision field
         printf_size_t precision = 0U;
         if (*format == '.')
         {
             flags |= FLAGS_PRECISION;
             ADVANCE_IN_FORMAT_STRING(format);
             if (is_digit_libint(*format))
             {
                 precision = (printf_size_t)atou_libint(&format);
             }
             else if (*format == '*')
             {
                 const int precision_ = va_arg(args, int);
                 precision = precision_ > 0 ? (printf_size_t)precision_ : 0U;
                 ADVANCE_IN_FORMAT_STRING(format);
             }
         }
         // evaluate length field
         switch (*format)
         {
 #ifdef PRINTF_SUPPORT_MSVC_STYLE_INTEGER_SPECIFIERS
         case 'I':
         {
             ADVANCE_IN_FORMAT_STRING(format);
             // Greedily parse for size in bits: 8, 16, 32 or 64
             switch (*format)
             {
             case '8':
                 flags |= FLAGS_INT8;
                 ADVANCE_IN_FORMAT_STRING(format);
                 break;
             case '1':
                 ADVANCE_IN_FORMAT_STRING(format);
                 if (*format == '6')
                 {
                     format++;
                     flags |= FLAGS_INT16;
                 }
                 break;
             case '3':
                 ADVANCE_IN_FORMAT_STRING(format);
                 if (*format == '2')
                 {
                     ADVANCE_IN_FORMAT_STRING(format);
                     flags |= FLAGS_INT32;
                 }
                 break;
             case '6':
                 ADVANCE_IN_FORMAT_STRING(format);
                 if (*format == '4')
                 {
                     ADVANCE_IN_FORMAT_STRING(format);
                     flags |= FLAGS_INT64;
                 }
                 break;
             default:
                 break;
             }
             break;
         }
 #endif
         case 'l':
             flags |= FLAGS_LONG;
             ADVANCE_IN_FORMAT_STRING(format);
             if (*format == 'l')
             {
                 flags |= FLAGS_LONG_LONG;
                 ADVANCE_IN_FORMAT_STRING(format);
             }
             break;
         case 'h':
             flags |= FLAGS_SHORT;
             ADVANCE_IN_FORMAT_STRING(format);
             if (*format == 'h')
             {
                 flags |= FLAGS_CHAR;
                 ADVANCE_IN_FORMAT_STRING(format);
             }
             break;
         case 't':
             flags |= (sizeof(ptrdiff_t) == sizeof(long) ? FLAGS_LONG : FLAGS_LONG_LONG);
             ADVANCE_IN_FORMAT_STRING(format);
             break;
         case 'j':
             flags |= (sizeof(intmax_t) == sizeof(long) ? FLAGS_LONG : FLAGS_LONG_LONG);
             ADVANCE_IN_FORMAT_STRING(format);
             break;
         case 'z':
             flags |= (sizeof(size_t) == sizeof(long) ? FLAGS_LONG : FLAGS_LONG_LONG);
             ADVANCE_IN_FORMAT_STRING(format);
             break;
         default:
             break;
         }
         // evaluate specifier
         switch (*format)
         {
         case 'd':
         case 'i':
         case 'u':
         case 'x':
         case 'X':
         case 'o':
         case 'b':
         {
             if (*format == 'd' || *format == 'i')
             {
                 flags |= FLAGS_SIGNED;
             }
             numeric_base_t base;
             if (*format == 'x' || *format == 'X')
             {
                 base = BASE_HEX;
             }
             else if (*format == 'o')
             {
                 base = BASE_OCTAL;
             }
             else if (*format == 'b')
             {
                 base = BASE_BINARY;
             }
             else
             {
                 base = BASE_DECIMAL;
                 flags &= ~FLAGS_HASH; // decimal integers have no alternative presentation
             }
             if (*format == 'X')
             {
                 flags |= FLAGS_UPPERCASE;
             }
             format++;
             // ignore '0' flag when precision is given
             if (flags & FLAGS_PRECISION)
             {
                 flags &= ~FLAGS_ZEROPAD;
             }
             if (flags & FLAGS_SIGNED)
             {
                 // A signed specifier: d, i or possibly I + bit size if enabled
                 if (flags & FLAGS_LONG_LONG)
                 {
 #if PRINTF_SUPPORT_LONG_LONG
                     const long long value = va_arg(args, long long);
                     print_integer_libint(output, ABS_FOR_PRINTING(value), value < 0, base, precision, width, flags);
 #endif
                 }
                 else if (flags & FLAGS_LONG)
                 {
                     const long value = va_arg(args, long);
                     print_integer_libint(output, ABS_FOR_PRINTING(value), value < 0, base, precision, width, flags);
                 }
                 else
                 {
                     // We never try to interpret the argument as something potentially-smaller than int,
                     // due to integer promotion rules: Even if the user passed a short int, short unsigned
                     // etc. - these will come in after promotion, as int's (or unsigned for the case of
                     // short unsigned when it has the same size as int)
                     const int value =
                         (flags & FLAGS_CHAR) ? (signed char)va_arg(args, int) : (flags & FLAGS_SHORT) ? (short int)va_arg(args, int)
                                                                                                       : va_arg(args, int);
                     print_integer_libint(output, ABS_FOR_PRINTING(value), value < 0, base, precision, width, flags);
                 }
             }
             else
             {
                 // An unsigned specifier: u, x, X, o, b
                 flags &= ~(FLAGS_PLUS | FLAGS_SPACE);
                 if (flags & FLAGS_LONG_LONG)
                 {
 #if PRINTF_SUPPORT_LONG_LONG
                     print_integer_libint(output, (printf_unsigned_value_t)va_arg(args, unsigned long long), false, base, precision, width, flags);
 #endif
                 }
                 else if (flags & FLAGS_LONG)
                 {
                     print_integer_libint(output, (printf_unsigned_value_t)va_arg(args, unsigned long), false, base, precision, width, flags);
                 }
                 else
                 {
                     const unsigned int value =
                         (flags & FLAGS_CHAR) ? (unsigned char)va_arg(args, unsigned int) : (flags & FLAGS_SHORT) ? (unsigned short int)va_arg(args, unsigned int)
                                                                                                                  : va_arg(args, unsigned int);
                     print_integer_libint(output, (printf_unsigned_value_t)value, false, base, precision, width, flags);
                 }
             }
             break;
         }
 #if PRINTF_SUPPORT_DECIMAL_SPECIFIERS
         case 'f':
         case 'F':
             if (*format == 'F')
                 flags |= FLAGS_UPPERCASE;
             print_floating_point_libint(output, va_arg(args, double), precision, width, flags, PRINTF_PREFER_DECIMAL);
             format++;
             break;
 #endif
 #if PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS
         case 'e':
         case 'E':
         case 'g':
         case 'G':
             if ((*format == 'g') || (*format == 'G'))
                 flags |= FLAGS_ADAPT_EXP;
             if ((*format == 'E') || (*format == 'G'))
                 flags |= FLAGS_UPPERCASE;
             print_floating_point_libint(output, va_arg(args, double), precision, width, flags, PRINTF_PREFER_EXPONENTIAL);
             format++;
             break;
 #endif // PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS
         case 'c':
         {
             printf_size_t l = 1U;
             // pre padding
             if (!(flags & FLAGS_LEFT))
             {
                 while (l++ < width)
                 {
                     putchar_via_gadget_libint(output, ' ');
                 }
             }
             // char output
             putchar_via_gadget_libint(output, (char)va_arg(args, int));
             // post padding
             if (flags & FLAGS_LEFT)
             {
                 while (l++ < width)
                 {
                     putchar_via_gadget_libint(output, ' ');
                 }
             }
             format++;
             break;
         }
         case 's':
         {
             const char *p = va_arg(args, char *);
             if (p == NULL)
             {
                 out_rev_libint(output, ")llun(", 6, width, flags);
             }
             else
             {
                 printf_size_t l = strnlen_s_libint(p, precision ? precision : PRINTF_MAX_POSSIBLE_BUFFER_SIZE);
                 // pre padding
                 if (flags & FLAGS_PRECISION)
                 {
                     l = (l < precision ? l : precision);
                 }
                 if (!(flags & FLAGS_LEFT))
                 {
                     while (l++ < width)
                     {
                         putchar_via_gadget_libint(output, ' ');
                     }
                 }
                 // string output
                 while ((*p != 0) && (!(flags & FLAGS_PRECISION) || precision))
                 {
                     putchar_via_gadget_libint(output, *(p++));
                     --precision;
                 }
                 // post padding
                 if (flags & FLAGS_LEFT)
                 {
                     while (l++ < width)
                     {
                         putchar_via_gadget_libint(output, ' ');
                     }
                 }
             }
             format++;
             break;
         }
         case 'p':
         {
             width = sizeof(void *) * 2U + 2; // 2 hex chars per byte + the "0x" prefix
             flags |= FLAGS_ZEROPAD | FLAGS_POINTER;
             uintptr_t value = (uintptr_t)va_arg(args, void *);
             (value == (uintptr_t)NULL) ? out_rev_libint(output, ")lin(", 5, width, flags) : print_integer_libint(output, (printf_unsigned_value_t)value, false, BASE_HEX, precision, width, flags);
             format++;
             break;
         }
         case '%':
             putchar_via_gadget_libint(output, '%');
             format++;
             break;
             // Many people prefer to disable support for %n, as it lets the caller
             // engineer a write to an arbitrary location, of a value the caller
             // effectively controls - which could be a security concern in some cases.
 #if PRINTF_SUPPORT_WRITEBACK_SPECIFIER
         case 'n':
         {
             if (flags & FLAGS_CHAR)
                 *(va_arg(args, char *)) = (char)output->pos;
             else if (flags & FLAGS_SHORT)
                 *(va_arg(args, short *)) = (short)output->pos;
             else if (flags & FLAGS_LONG)
                 *(va_arg(args, long *)) = (long)output->pos;
 #if PRINTF_SUPPORT_LONG_LONG
             else if (flags & FLAGS_LONG_LONG)
                 *(va_arg(args, long long *)) = (long long int)output->pos;
 #endif // PRINTF_SUPPORT_LONG_LONG
             else
                 *(va_arg(args, int *)) = (int)output->pos;
             format++;
             break;
         }
 #endif // PRINTF_SUPPORT_WRITEBACK_SPECIFIER
         default:
             putchar_via_gadget_libint(output, *format);
             format++;
             break;
         }
     }
 }
References ABS_FOR_PRINTING, ADVANCE_IN_FORMAT_STRING, atou_libint(), base, BASE_BINARY, BASE_DECIMAL, BASE_HEX, BASE_OCTAL, mlibc::flags, FLAGS_ADAPT_EXP, FLAGS_CHAR, FLAGS_HASH, FLAGS_LEFT, FLAGS_LONG, FLAGS_LONG_LONG, FLAGS_PLUS, FLAGS_POINTER, FLAGS_PRECISION, FLAGS_SHORT, FLAGS_SIGNED, FLAGS_SPACE, FLAGS_UPPERCASE, FLAGS_ZEROPAD, format, is_digit_libint(), NULL, out_rev_libint(), error::output, p, parse_flags_libint(), print_integer_libint(), PRINTF_MAX_POSSIBLE_BUFFER_SIZE, PRINTF_PREFER_DECIMAL, PRINTF_PREFER_EXPONENTIAL, putchar_via_gadget_libint(), strnlen_s_libint(), va_arg, and value.
Referenced by vsnprintf_impl_libint().
function_gadget_libint()
static output_gadget_t function_gadget_libint (void(*)(char, void *) function, void * extra_arg) inline static
Definition at line 391 of file printf.c.
 {
     output_gadget_t result = discarding_gadget_libint();
     result.function = function;
     result.extra_function_arg = extra_arg;
     result.max_chars = PRINTF_MAX_POSSIBLE_BUFFER_SIZE;
     return result;
 }
References discarding_gadget_libint(), PRINTF_MAX_POSSIBLE_BUFFER_SIZE, and mlibc::result.
Referenced by extern_putchar_gadget_libint(), and vfctprintf_libinit().
is_digit_libint()
static bool is_digit_libint (char ch) inline static
Definition at line 419 of file printf.c.
 {
     return (ch >= '0') && (ch <= '9');
 }
Referenced by atou_libint(), and format_string_loop_libint().
out_rev_libint()
static void out_rev_libint (output_gadget_t * output, const char * buf, printf_size_t len, printf_size_t width, printf_flags_t flags) static
Definition at line 436 of file printf.c.
 {
     const printf_size_t start_pos = output->pos;
     // pad spaces up to given width
     if (!(flags & FLAGS_LEFT) && !(flags & FLAGS_ZEROPAD))
     {
         for (printf_size_t i = len; i < width; i++)
         {
             putchar_via_gadget_libint(output, ' ');
         }
     }
     // reverse string
     while (len)
     {
         putchar_via_gadget_libint(output, buf[--len]);
     }
     // append pad spaces up to given width
     if (flags & FLAGS_LEFT)
     {
         while (output->pos - start_pos < width)
         {
             putchar_via_gadget_libint(output, ' ');
         }
     }
 }
References buf, mlibc::flags, FLAGS_LEFT, FLAGS_ZEROPAD, i, error::output, and putchar_via_gadget_libint().
Referenced by format_string_loop_libint(), and print_integer_finalization_libint().
parse_flags_libint()
static printf_flags_t parse_flags_libint (const char ** format) static
Definition at line 1104 of file printf.c.
 {
     printf_flags_t flags = 0U;
     do
     {
         switch (**format)
         {
         case '0':
             flags |= FLAGS_ZEROPAD;
             (*format)++;
             break;
         case '-':
             flags |= FLAGS_LEFT;
             (*format)++;
             break;
         case '+':
             flags |= FLAGS_PLUS;
             (*format)++;
             break;
         case ' ':
             flags |= FLAGS_SPACE;
             (*format)++;
             break;
         case '#':
             flags |= FLAGS_HASH;
             (*format)++;
             break;
         default:
             return flags;
         }
     } while (true);
 }
References mlibc::flags, FLAGS_HASH, FLAGS_LEFT, FLAGS_PLUS, FLAGS_SPACE, FLAGS_ZEROPAD, and format.
Referenced by format_string_loop_libint().
print_integer_finalization_libint()
static void print_integer_finalization_libint (output_gadget_t * output, char * buf, printf_size_t len, bool negative, numeric_base_t base, printf_size_t precision, printf_size_t width, printf_flags_t flags) static
Definition at line 467 of file printf.c.
 {
     printf_size_t unpadded_len = len;
     // pad with leading zeros
     {
         if (!(flags & FLAGS_LEFT))
         {
             if (width && (flags & FLAGS_ZEROPAD) && (negative || (flags & (FLAGS_PLUS | FLAGS_SPACE))))
             {
                 width--;
             }
             while ((flags & FLAGS_ZEROPAD) && (len < width) && (len < PRINTF_INTEGER_BUFFER_SIZE))
             {
                 buf[len++] = '0';
             }
         }
         while ((len < precision) && (len < PRINTF_INTEGER_BUFFER_SIZE))
         {
             buf[len++] = '0';
         }
         if (base == BASE_OCTAL && (len > unpadded_len))
         {
             // Since we've written some zeros, we've satisfied the alternative format leading space requirement
             flags &= ~FLAGS_HASH;
         }
     }
     // handle hash
     if (flags & (FLAGS_HASH | FLAGS_POINTER))
     {
         if (!(flags & FLAGS_PRECISION) && len && ((len == precision) || (len == width)))
         {
             // Let's take back some padding digits to fit in what will eventually
             // be the format-specific prefix
             if (unpadded_len < len)
             {
                 len--; // This should suffice for BASE_OCTAL
             }
             if (len && (base == BASE_HEX || base == BASE_BINARY) && (unpadded_len < len))
             {
                 len--; // ... and an extra one for 0x or 0b
             }
         }
         if ((base == BASE_HEX) && !(flags & FLAGS_UPPERCASE) && (len < PRINTF_INTEGER_BUFFER_SIZE))
         {
             buf[len++] = 'x';
         }
         else if ((base == BASE_HEX) && (flags & FLAGS_UPPERCASE) && (len < PRINTF_INTEGER_BUFFER_SIZE))
         {
             buf[len++] = 'X';
         }
         else if ((base == BASE_BINARY) && (len < PRINTF_INTEGER_BUFFER_SIZE))
         {
             buf[len++] = 'b';
         }
         if (len < PRINTF_INTEGER_BUFFER_SIZE)
         {
             buf[len++] = '0';
         }
     }
     if (len < PRINTF_INTEGER_BUFFER_SIZE)
     {
         if (negative)
         {
             buf[len++] = '-';
         }
         else if (flags & FLAGS_PLUS)
         {
             buf[len++] = '+'; // ignore the space if the '+' exists
         }
         else if (flags & FLAGS_SPACE)
         {
             buf[len++] = ' ';
         }
     }
     out_rev_libint(output, buf, len, width, flags);
 }
References base, BASE_BINARY, BASE_HEX, BASE_OCTAL, buf, mlibc::flags, FLAGS_HASH, FLAGS_LEFT, FLAGS_PLUS, FLAGS_POINTER, FLAGS_PRECISION, FLAGS_SPACE, FLAGS_UPPERCASE, FLAGS_ZEROPAD, out_rev_libint(), error::output, and PRINTF_INTEGER_BUFFER_SIZE.
Referenced by print_integer_libint().
print_integer_libint()
static void print_integer_libint (output_gadget_t * output, printf_unsigned_value_t value, bool negative, numeric_base_t base, printf_size_t precision, printf_size_t width, printf_flags_t flags) static
Definition at line 551 of file printf.c.
 {
     char buf[PRINTF_INTEGER_BUFFER_SIZE];
     printf_size_t len = 0U;
     if (!value)
     {
         if (!(flags & FLAGS_PRECISION))
         {
             buf[len++] = '0';
             flags &= ~FLAGS_HASH;
             // We drop this flag this since either the alternative and regular modes of the specifier
             // don't differ on 0 values, or (in the case of octal) we've already provided the special
             // handling for this mode.
         }
         else if (base == BASE_HEX)
         {
             flags &= ~FLAGS_HASH;
             // We drop this flag this since either the alternative and regular modes of the specifier
             // don't differ on 0 values
         }
     }
     else
     {
         do
         {
             const char digit = (char)(value % base);
             buf[len++] = (char)(digit < 10 ? '0' + digit : (flags & FLAGS_UPPERCASE ? 'A' : 'a') + digit - 10);
             value /= base;
         } while (value && (len < PRINTF_INTEGER_BUFFER_SIZE));
     }
     print_integer_finalization_libint(output, buf, len, negative, base, precision, width, flags);
 }
References base, BASE_HEX, buf, mlibc::flags, FLAGS_HASH, FLAGS_PRECISION, FLAGS_UPPERCASE, error::output, print_integer_finalization_libint(), PRINTF_INTEGER_BUFFER_SIZE, and value.
Referenced by format_string_loop_libint().
printf_libinit()
int printf_libinit (const char * format, ...)
Definition at line 1557 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vprintf_libinit(format, args);
     va_end(args);
     return ret;
 }
References args, format, ret, va_end(), va_start(), and vprintf_libinit().
Referenced by init_log().
putchar_via_gadget_libint()
static void putchar_via_gadget_libint (output_gadget_t * gadget, char c) inline static
Definition at line 320 of file printf.c.
 {
     printf_size_t write_pos = gadget->pos++;
     // We're _always_ increasing pos, so as to count how may characters
     // _would_ have been written if not for the max_chars limitation
     if (write_pos >= gadget->max_chars)
     {
         return;
     }
     if (gadget->function != NULL)
     {
         // No check for c == '\0' .
         gadget->function(c, gadget->extra_function_arg);
     }
     else
     {
         // it must be the case that gadget->buffer != NULL , due to the constraint
         // on output_gadget_t ; and note we're relying on write_pos being non-negative.
         gadget->buffer[write_pos] = c;
     }
 }
References output_gadget_t::buffer, c, output_gadget_t::extra_function_arg, output_gadget_t::function, output_gadget_t::max_chars, NULL, and output_gadget_t::pos.
Referenced by format_string_loop_libint(), and out_rev_libint().
putchar_wrapper_libint()
static void putchar_wrapper_libint (char c, void * unused) inline static
Definition at line 359 of file printf.c.
 {
     (void)unused;
     __asm__ __volatile__("syscall"
                          :
                          : "a"(1), "D"(c), "S"(0)
                          : "rcx", "r11", "memory");
 }
References c, and Driver::void().
Referenced by extern_putchar_gadget_libint().
snprintf_libinit()
int snprintf_libinit (char * s, size_t n, const char * format, ...)
Definition at line 1575 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsnprintf_libinit(s, n, format, args);
     va_end(args);
     return ret;
 }
References args, format, n, ret, va_end(), va_start(), and vsnprintf_libinit().
sprintf_libinit()
int sprintf_libinit (char * s, const char * format, ...)
Definition at line 1566 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsprintf_libinit(s, format, args);
     va_end(args);
     return ret;
 }
References args, format, ret, va_end(), va_start(), and vsprintf_libinit().
strnlen_s_libint()
static printf_size_t strnlen_s_libint (const char * str, printf_size_t maxsize) inline static
Definition at line 409 of file printf.c.
 {
     const char *s;
     for (s = str; *s && maxsize--; ++s)
         ;
     return (printf_size_t)(s - str);
 }
Referenced by format_string_loop_libint().
vfctprintf_libinit()
int vfctprintf_libinit (void(*)(char c, void *extra_arg) out, void * extra_arg, const char * format, va_list arg)
Definition at line 1551 of file printf.c.
 {
     output_gadget_t gadget = function_gadget_libint(out, extra_arg);
     return vsnprintf_impl_libint(&gadget, format, arg);
 }
References arg, format, function_gadget_libint(), and vsnprintf_impl_libint().
Referenced by fctprintf_libinit().
vprintf_libinit()
int vprintf_libinit (const char * format, va_list arg)
Definition at line 1534 of file printf.c.
 {
     output_gadget_t gadget = extern_putchar_gadget_libint();
     return vsnprintf_impl_libint(&gadget, format, arg);
 }
References arg, extern_putchar_gadget_libint(), format, and vsnprintf_impl_libint().
Referenced by init_log(), and printf_libinit().
vsnprintf_impl_libint()
static int vsnprintf_impl_libint (output_gadget_t * output, const char * format, va_list args) static
Definition at line 1519 of file printf.c.
 {
     // Note: The library only calls vsnprintf_impl_libint() with output->pos being 0. However, it is
     // possible to call this function with a non-zero pos value for some "remedial printing".
     format_string_loop_libint(output, format, args);
     // termination
     append_termination_with_gadget_libint(output);
     // return written chars without terminating \0
     return (int)output->pos;
 }
References append_termination_with_gadget_libint(), format, format_string_loop_libint(), and error::output.
Referenced by vfctprintf_libinit(), vprintf_libinit(), and vsnprintf_libinit().
vsnprintf_libinit()
int vsnprintf_libinit (char * s, size_t n, const char * format, va_list arg)
Definition at line 1540 of file printf.c.
 {
     output_gadget_t gadget = buffer_gadget_libint(s, n);
     return vsnprintf_impl_libint(&gadget, format, arg);
 }
References arg, buffer_gadget_libint(), format, n, and vsnprintf_impl_libint().
Referenced by snprintf_libinit(), and vsprintf_libinit().
vsprintf_libinit()
int vsprintf_libinit (char * s, const char * format, va_list arg)
Definition at line 1546 of file printf.c.
 {
     return vsnprintf_libinit(s, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, format, arg);
 }
References arg, format, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, and vsnprintf_libinit().
Referenced by sprintf_libinit().