Fennix Kernel: SMBIOS Namespace Reference
SMBIOS Namespace Reference
Data Structures
struct SMBIOSHeader
struct SMBIOSEntryPoint
struct SMBIOSBIOSInformation
struct SMBIOSSystemInformation
struct SMBIOSBaseBoardInformation
struct SMBIOSProcessorInformation
struct SMBIOSMemoryDevice
struct SMBIOSMemoryArrayMappedAddress
struct SMBIOSMemoryDeviceMappedAddress
struct SMBIOSMemoryArray
Enumerations
enum SMBIOSType {
SMBIOSTypeBIOSInformation = 0 , SMBIOSTypeSystemInformation = 1 , SMBIOSTypeBaseBoardInformation = 2 , SMBIOSTypeSystemEnclosure = 3 ,
SMBIOSTypeProcessorInformation = 4 , SMBIOSTypeMemoryControllerInformation = 5 , SMBIOSTypeMemoryModuleInformation = 6 , SMBIOSTypeCacheInformation = 7 ,
SMBIOSTypePortConnectorInformation = 8 , SMBIOSTypeSystemSlots = 9 , SMBIOSTypeOnBoardDevicesInformation = 10 , SMBIOSTypeOEMStrings = 11 ,
SMBIOSTypeSystemConfigurationOptions = 12 , SMBIOSTypeBIOSLanguageInformation = 13 , SMBIOSTypeGroupAssociations = 14 , SMBIOSTypeSystemEventLog = 15 ,
SMBIOSTypePhysicalMemoryArray = 16 , SMBIOSTypeMemoryDevice = 17 , SMBIOSType32BitMemoryErrorInformation = 18 , SMBIOSTypeMemoryArrayMappedAddress = 19 ,
SMBIOSTypeMemoryDeviceMappedAddress = 20 , SMBIOSTypeBuiltInPointingDevice = 21 , SMBIOSTypePortableBattery = 22 , SMBIOSTypeSystemReset = 23 ,
SMBIOSTypeHardwareSecurity = 24 , SMBIOSTypeSystemPowerControls = 25 , SMBIOSTypeVoltageProbe = 26 , SMBIOSTypeCoolingDevice = 27 ,
SMBIOSTypeTemperatureProbe = 28 , SMBIOSTypeElectricalCurrentProbe = 29 , SMBIOSTypeOutofBandRemoteAccess = 30 , SMBIOSTypeBootIntegrityServices = 31 ,
SMBIOSTypeSystemBoot = 32 , SMBIOSType64BitMemoryErrorInformation = 33 , SMBIOSTypeManagementDevice = 34 , SMBIOSTypeManagementDeviceComponent = 35 ,
SMBIOSTypeManagementDeviceThresholdData = 36 , SMBIOSTypeMemoryChannel = 37 , SMBIOSTypeIPMIDevice = 38 , SMBIOSTypePowerSupply = 39 ,
SMBIOSTypeAdditionalInformation = 40 , SMBIOSTypeOnboardDevicesExtendedInformation = 41 , SMBIOSTypeManagementControllerHostInterface = 42 , SMBIOSTypeTPMDevice = 43 ,
SMBIOSTypeProcessorAdditionalInformation = 44 , SMBIOSTypeInactive = 126 , SMBIOSTypeEndOfTable = 127
}
Functions
static char * SMBIOSNextString (char *Str)
bool CheckSMBIOS ()
SMBIOSEntryPoint * GetSMBIOSEntryPoint ()
void * GetSMBIOSHeader (SMBIOSType Type)
SMBIOSBIOSInformation * GetBIOSInformation ()
SMBIOSSystemInformation * GetSystemInformation ()
SMBIOSBaseBoardInformation * GetBaseBoardInformation ()
SMBIOSProcessorInformation * GetProcessorInformation ()
SMBIOSMemoryArray * GetMemoryArray ()
SMBIOSMemoryDevice * GetMemoryDevice ()
SMBIOSMemoryArrayMappedAddress * GetMemoryArrayMappedAddress ()
SMBIOSMemoryDeviceMappedAddress * GetMemoryDeviceMappedAddress ()
static int SMBIOSTableLength (SMBIOSHeader *Hdr)
Data Structure Documentation
SMBIOS::SMBIOSHeader
struct SMBIOS::SMBIOSHeader
Definition at line 59 of file smbios.hpp.
Data Fields
unsigned short Handle
unsigned char Length
unsigned char Type
SMBIOS::SMBIOSEntryPoint
struct SMBIOS::SMBIOSEntryPoint
Definition at line 66 of file smbios.hpp.
Data Fields
unsigned char BCDRevision
unsigned char Checksum
unsigned char Checksum2
unsigned char EntryPointRevision
char EntryPointString[4]
char EntryPointString2[5]
char FormattedArea[5]
unsigned char Length
unsigned char MajorVersion
unsigned short MaxStructureSize
unsigned char MinorVersion
unsigned short NumberOfStructures
unsigned int TableAddress
unsigned short TableLength
Enumeration Type Documentation
SMBIOSType
enum SMBIOS::SMBIOSType
Enumerator
SMBIOSTypeBIOSInformation
SMBIOSTypeSystemInformation
SMBIOSTypeBaseBoardInformation
SMBIOSTypeSystemEnclosure
SMBIOSTypeProcessorInformation
SMBIOSTypeMemoryControllerInformation
SMBIOSTypeMemoryModuleInformation
SMBIOSTypeCacheInformation
SMBIOSTypePortConnectorInformation
SMBIOSTypeSystemSlots
SMBIOSTypeOnBoardDevicesInformation
SMBIOSTypeOEMStrings
SMBIOSTypeSystemConfigurationOptions
SMBIOSTypeBIOSLanguageInformation
SMBIOSTypeGroupAssociations
SMBIOSTypeSystemEventLog
SMBIOSTypePhysicalMemoryArray
SMBIOSTypeMemoryDevice
SMBIOSType32BitMemoryErrorInformation
SMBIOSTypeMemoryArrayMappedAddress
SMBIOSTypeMemoryDeviceMappedAddress
SMBIOSTypeBuiltInPointingDevice
SMBIOSTypePortableBattery
SMBIOSTypeSystemReset
SMBIOSTypeHardwareSecurity
SMBIOSTypeSystemPowerControls
SMBIOSTypeVoltageProbe
SMBIOSTypeCoolingDevice
SMBIOSTypeTemperatureProbe
SMBIOSTypeElectricalCurrentProbe
SMBIOSTypeOutofBandRemoteAccess
SMBIOSTypeBootIntegrityServices
SMBIOSTypeSystemBoot
SMBIOSType64BitMemoryErrorInformation
SMBIOSTypeManagementDevice
SMBIOSTypeManagementDeviceComponent
SMBIOSTypeManagementDeviceThresholdData
SMBIOSTypeMemoryChannel
SMBIOSTypeIPMIDevice
SMBIOSTypePowerSupply
SMBIOSTypeAdditionalInformation
SMBIOSTypeOnboardDevicesExtendedInformation
SMBIOSTypeManagementControllerHostInterface
SMBIOSTypeTPMDevice
SMBIOSTypeProcessorAdditionalInformation
SMBIOSTypeInactive
SMBIOSTypeEndOfTable
Definition at line 8 of file smbios.hpp.
     {
         SMBIOSTypeBIOSInformation = 0,
         SMBIOSTypeSystemInformation = 1,
         SMBIOSTypeBaseBoardInformation = 2,
         SMBIOSTypeSystemEnclosure = 3,
         SMBIOSTypeProcessorInformation = 4,
         SMBIOSTypeMemoryControllerInformation = 5,
         SMBIOSTypeMemoryModuleInformation = 6,
         SMBIOSTypeCacheInformation = 7,
         SMBIOSTypePortConnectorInformation = 8,
         SMBIOSTypeSystemSlots = 9,
         SMBIOSTypeOnBoardDevicesInformation = 10,
         SMBIOSTypeOEMStrings = 11,
         SMBIOSTypeSystemConfigurationOptions = 12,
         SMBIOSTypeBIOSLanguageInformation = 13,
         SMBIOSTypeGroupAssociations = 14,
         SMBIOSTypeSystemEventLog = 15,
         SMBIOSTypePhysicalMemoryArray = 16,
         SMBIOSTypeMemoryDevice = 17,
         SMBIOSType32BitMemoryErrorInformation = 18,
         SMBIOSTypeMemoryArrayMappedAddress = 19,
         SMBIOSTypeMemoryDeviceMappedAddress = 20,
         SMBIOSTypeBuiltInPointingDevice = 21,
         SMBIOSTypePortableBattery = 22,
         SMBIOSTypeSystemReset = 23,
         SMBIOSTypeHardwareSecurity = 24,
         SMBIOSTypeSystemPowerControls = 25,
         SMBIOSTypeVoltageProbe = 26,
         SMBIOSTypeCoolingDevice = 27,
         SMBIOSTypeTemperatureProbe = 28,
         SMBIOSTypeElectricalCurrentProbe = 29,
         SMBIOSTypeOutofBandRemoteAccess = 30,
         SMBIOSTypeBootIntegrityServices = 31,
         SMBIOSTypeSystemBoot = 32,
         SMBIOSType64BitMemoryErrorInformation = 33,
         SMBIOSTypeManagementDevice = 34,
         SMBIOSTypeManagementDeviceComponent = 35,
         SMBIOSTypeManagementDeviceThresholdData = 36,
         SMBIOSTypeMemoryChannel = 37,
         SMBIOSTypeIPMIDevice = 38,
         SMBIOSTypePowerSupply = 39,
         SMBIOSTypeAdditionalInformation = 40,
         SMBIOSTypeOnboardDevicesExtendedInformation = 41,
         SMBIOSTypeManagementControllerHostInterface = 42,
         SMBIOSTypeTPMDevice = 43,
         SMBIOSTypeProcessorAdditionalInformation = 44,
         SMBIOSTypeInactive = 126,
         SMBIOSTypeEndOfTable = 127
     };
Function Documentation
CheckSMBIOS()
bool SMBIOS::CheckSMBIOS ()
Definition at line 11 of file SystemManagementBIOS.cpp.
     {
         if (bInfo->SMBIOSPtr != nullptr && bInfo->SMBIOSPtr < (void *)0xffffffffffff0000)
         {
             debug("SMBIOS is available (%#lx).", bInfo->SMBIOSPtr);
             return true;
         }
         debug("SMBIOS is not available. (%#lx)", bInfo->SMBIOSPtr);
         return false;
     }
References bInfo, debug, and BootInfo::SMBIOSPtr.
Referenced by GetSMBIOSHeader(), and Main().
GetBaseBoardInformation()
SMBIOSBaseBoardInformation * SMBIOS::GetBaseBoardInformation ()
Definition at line 59 of file SystemManagementBIOS.cpp.
 { return (SMBIOSBaseBoardInformation *)GetSMBIOSHeader(SMBIOSTypeBaseBoardInformation); }
References GetSMBIOSHeader(), and SMBIOSTypeBaseBoardInformation.
Referenced by Main().
GetBIOSInformation()
SMBIOSBIOSInformation * SMBIOS::GetBIOSInformation ()
Definition at line 55 of file SystemManagementBIOS.cpp.
 { return (SMBIOSBIOSInformation *)GetSMBIOSHeader(SMBIOSTypeBIOSInformation); }
References GetSMBIOSHeader(), and SMBIOSTypeBIOSInformation.
Referenced by Main().
GetMemoryArray()
SMBIOSMemoryArray * SMBIOS::GetMemoryArray ()
Definition at line 63 of file SystemManagementBIOS.cpp.
 { return (SMBIOSMemoryArray *)GetSMBIOSHeader(SMBIOSTypePhysicalMemoryArray); }
References GetSMBIOSHeader(), and SMBIOSTypePhysicalMemoryArray.
GetMemoryArrayMappedAddress()
SMBIOSMemoryArrayMappedAddress * SMBIOS::GetMemoryArrayMappedAddress ()
Definition at line 67 of file SystemManagementBIOS.cpp.
 { return (SMBIOSMemoryArrayMappedAddress *)GetSMBIOSHeader(SMBIOSTypeMemoryArrayMappedAddress); }
References GetSMBIOSHeader(), and SMBIOSTypeMemoryArrayMappedAddress.
GetMemoryDevice()
SMBIOSMemoryDevice * SMBIOS::GetMemoryDevice ()
Definition at line 65 of file SystemManagementBIOS.cpp.
 { return (SMBIOSMemoryDevice *)GetSMBIOSHeader(SMBIOSTypeMemoryDevice); }
References GetSMBIOSHeader(), and SMBIOSTypeMemoryDevice.
GetMemoryDeviceMappedAddress()
SMBIOSMemoryDeviceMappedAddress * SMBIOS::GetMemoryDeviceMappedAddress ()
Definition at line 69 of file SystemManagementBIOS.cpp.
 { return (SMBIOSMemoryDeviceMappedAddress *)GetSMBIOSHeader(SMBIOSTypeMemoryDeviceMappedAddress); }
References GetSMBIOSHeader(), and SMBIOSTypeMemoryDeviceMappedAddress.
GetProcessorInformation()
SMBIOSProcessorInformation * SMBIOS::GetProcessorInformation ()
Definition at line 61 of file SystemManagementBIOS.cpp.
 { return (SMBIOSProcessorInformation *)GetSMBIOSHeader(SMBIOSTypeProcessorInformation); }
References GetSMBIOSHeader(), and SMBIOSTypeProcessorInformation.
GetSMBIOSEntryPoint()
SMBIOSEntryPoint * SMBIOS::GetSMBIOSEntryPoint ()
Definition at line 22 of file SystemManagementBIOS.cpp.
 { return (SMBIOSEntryPoint *)bInfo->SMBIOSPtr; }
References bInfo, and BootInfo::SMBIOSPtr.
Referenced by Main().
GetSMBIOSHeader()
void * SMBIOS::GetSMBIOSHeader (SMBIOSType Type)
Definition at line 33 of file SystemManagementBIOS.cpp.
     {
         if (!CheckSMBIOS())
             return nullptr;
         SMBIOSEntryPoint *Header = (SMBIOSEntryPoint *)bInfo->SMBIOSPtr;
         debug("Getting SMBIOS header for type %d", Type);
         struct SMBIOSHeader *hdr = (SMBIOSHeader *)(uintptr_t)Header->TableAddress;
         for (int i = 0; i <= 11; i++)
         {
             if (hdr < (void *)(uintptr_t)(Header->TableAddress + Header->TableLength))
                 if (hdr->Type == Type)
                 {
                     debug("Found SMBIOS header for type %d at %#lx", Type, hdr);
                     return hdr;
                 }
             hdr = (struct SMBIOSHeader *)((uintptr_t)hdr + SMBIOSTableLength(hdr));
         }
         return nullptr;
     }
References bInfo, CheckSMBIOS(), debug, Header, BootInfo::SMBIOSPtr, SMBIOSTableLength(), Type, and SMBIOS::SMBIOSHeader::Type.
Referenced by GetBaseBoardInformation(), GetBIOSInformation(), GetMemoryArray(), GetMemoryArrayMappedAddress(), GetMemoryDevice(), GetMemoryDeviceMappedAddress(), GetProcessorInformation(), and GetSystemInformation().
GetSystemInformation()
SMBIOSSystemInformation * SMBIOS::GetSystemInformation ()
Definition at line 57 of file SystemManagementBIOS.cpp.
 { return (SMBIOSSystemInformation *)GetSMBIOSHeader(SMBIOSTypeSystemInformation); }
References GetSMBIOSHeader(), and SMBIOSTypeSystemInformation.
Referenced by Main().
SMBIOSNextString()
static char* SMBIOS::SMBIOSNextString (char * Str) inline static
Definition at line 84 of file smbios.hpp.
     {
         while (*Str != '\0')
             Str++;
         return Str + 1;
     }
Referenced by SMBIOS::SMBIOSBIOSInformation::GetString(), SMBIOS::SMBIOSSystemInformation::GetString(), SMBIOS::SMBIOSBaseBoardInformation::GetString(), SMBIOS::SMBIOSProcessorInformation::GetString(), SMBIOS::SMBIOSMemoryDevice::GetString(), SMBIOS::SMBIOSMemoryArrayMappedAddress::GetString(), SMBIOS::SMBIOSMemoryDeviceMappedAddress::GetString(), and SMBIOS::SMBIOSMemoryArray::GetString().
SMBIOSTableLength()
static int SMBIOS::SMBIOSTableLength (SMBIOSHeader * Hdr) inline static
Definition at line 24 of file SystemManagementBIOS.cpp.
     {
         int i;
         const char *strtab = (char *)Hdr + Hdr->Length;
         for (i = 1; strtab[i - 1] != '\0' || strtab[i] != '\0'; i++)
             ;
         return Hdr->Length + i + 1;
     }
References SMBIOS::SMBIOSHeader::Length.
Referenced by GetSMBIOSHeader().