Fennix: Kernel/KernelConfig.cpp File Reference
KernelConfig.cpp File Reference
#include <kconfig.hpp>
#include <convert.h>
#include <cargs.h>
#include <printf.h>
#include <targp.h>
#include "kernel.h"
Functions
EXTERNC void fprintf (FILE *stream, const char *Format,...)
EXTERNC void fputs (const char *s, FILE *stream)
void ParseConfig (char *ConfigString, KernelConfig *ModConfig)
Variables
static struct cag_option ConfigOptions []
Function Documentation
fprintf()
EXTERNC void fprintf (FILE * stream, const char * Format, ...)
Definition at line 28 of file KernelConfig.cpp.
 {
     va_list args;
     va_start(args, Format);
     vprintf(Format, args);
     va_end(args);
     UNUSED(stream);
 }
References args, UNUSED, va_end, va_start, and vprintf().
Referenced by __assert_fail(), _nl_log_untranslated(), _rl_errmsg(), _rl_init_file_error(), _rl_internal_pager(), _rl_macro_dumper_internal(), _rl_ttymsg(), addcchar(), addcstr(), addmntent(), ash_vmsg(), ask_and_unlink(), back_lines(), bad_record_die(), bb_progress_update(), bbunpack(), botch(), builtin_error(), builtin_error_prolog(), builtin_usage(), builtin_warning(), cag_option_print(), cag_option_print_letters(), cag_option_print_name(), cag_option_print_value(), catch(), cmp_main(), conf_warning(), conf_write(), confirm_or_abort(), const_des_init(), dd_output_status(), describe_pid(), dialog_checklist(), dialog_menu(), dialog_textbox(), display_matches(), do_check(), do_config_file(), dolisten(), DonutOverrun(), download_one_url(), dump_lsyntax(), error_prolog(), escape_input(), EV_DoDonut(), EV_VerticalDoor(), exec_kernel_doc(), execute_line(), extract_info(), fatal_error(), fgets_trim_sanitize(), file_write_dep(), finalize(), find_export_symbols(), ftpcmd(), get_line(), get_working_directory(), glob_filename(), handle_eof_input_unit(), herror(), I_CDMusPrintStartup(), I_Error(), ifupdown_main(), init_wsize(), initialize_signames(), internal_debug(), internal_error(), internal_inform(), internal_warning(), ipaddr_modify(), j_inputbox(), kconfig_load(), klogd_setloglevel(), line_error(), M_Episode(), main(), make_here_document(), memory_error_and_abort(), menu_warn(), mkfs_vfat_main(), mv_main(), nc_main(), notify_of_job_status(), pad(), PadRejectArray(), parse_dep_file(), ParseField(), parser_error(), pretty_print_job(), print_builtin(), print_deps(), print_pipeline(), print_position(), print_prompt(), print_route(), printargs(), process_files(), process_line(), produces_handler(), programming_error(), prop_warn(), psignal(), putgrent(), putpwent(), putspent(), reader_loop(), readline_internal_setup(), readwrite(), remove_file(), report_error(), resize_main(), restore(), retrieve_file_data(), rl_deprep_terminal(), rl_ding(), rl_dump_functions(), rl_dump_macros(), rl_dump_variables(), rl_function_dumper(), rl_list_funmap_names(), rl_prep_terminal(), rl_show_char(), rl_variable_dumper(), safe_write_to_pty_decode_iac(), save_input_to_file(), SaveDefaultCollection(), saveg_read8(), saveg_write8(), scan_expression(), scan_request(), script_main(), send_headers(), send_pwd_to_eterm(), shell_getc(), show_shell_usage(), sigpipe(), sigstat(), sort_main(), SpechitOverrun(), stdcat(), stralloc(), strgrow(), sys_error(), table_lookup(), throw_to_top_level(), too_dangerous(), unpack_package(), update_passwd(), usage(), Usage(), valid_argument(), vwarn(), vwarnx(), wait_for(), wcomment(), wprintf_core(), write_buffer_no_status(), write_builtins(), write_documentation(), write_dummy_declarations(), write_endifs(), write_file_footers(), write_file_headers(), write_helpfiles(), write_ifdefs(), write_longdocs(), write_signames(), write_status_file(), WriteTimidityConfig(), xargs_main(), xbotch(), xgetpty(), xmalloc(), xtrace_print_assignment(), xtrace_print_case_command_head(), xtrace_print_for_command_head(), xtrace_print_word_list(), and Z_FileDumpHeap().
fputs()
EXTERNC void fputs (const char * s, FILE * stream)
Definition at line 38 of file KernelConfig.cpp.
 {
     printf("%s", s);
     UNUSED(stream);
 }
ParseConfig()
void ParseConfig (char * ConfigString, KernelConfig * ModConfig)
Definition at line 117 of file KernelConfig.cpp.
 {
     if (ConfigString == NULL ||
         strlen(ConfigString) == 0)
     {
         KPrint("Empty kernel parameters!");
         return;
     }
     if (ModConfig == NULL)
     {
         KPrint("ModConfig is NULL!");
         return;
     }
     KPrint("Kernel parameters: %s", ConfigString);
     debug("Kernel parameters: %s", ConfigString);
     char *argv[32];
     int argc = 0;
     /* Not sure if the quotes are being parsed correctly. */
     targp_parse(ConfigString, argv, &argc);
 #ifdef DEBUG
     for (int i = 0; i < argc; i++)
         debug("argv[%d] = %s", i, argv[i]);
     debug("argc = %d", argc);
 #endif
     char identifier;
     const char *value;
     cag_option_context context;
     cag_option_prepare(&context, ConfigOptions, CAG_ARRAY_SIZE(ConfigOptions), argc, argv);
     while (cag_option_fetch(&context))
     {
         identifier = cag_option_get(&context);
         switch (identifier)
         {
         case 'a':
         {
             value = cag_option_get_value(&context);
             if (strcmp(value, "xallocv1") == 0)
             {
                 KPrint("\eAAFFAAUsing XallocV1 as memory allocator");
                 ModConfig->AllocatorType = Memory::MemoryAllocatorType::XallocV1;
             }
             else if (strcmp(value, "xallocv2") == 0)
             {
                 KPrint("\eAAFFAAUsing XallocV2 as memory allocator");
                 ModConfig->AllocatorType = Memory::MemoryAllocatorType::XallocV2;
             }
             else if (strcmp(value, "liballoc11") == 0)
             {
                 KPrint("\eAAFFAAUsing Liballoc11 as memory allocator");
                 ModConfig->AllocatorType = Memory::MemoryAllocatorType::liballoc11;
             }
             else if (strcmp(value, "pages") == 0)
             {
                 KPrint("\eAAFFAAUsing Pages as memory allocator");
                 ModConfig->AllocatorType = Memory::MemoryAllocatorType::Pages;
             }
             break;
         }
         case 'c':
         {
             value = cag_option_get_value(&context);
             KPrint("\eAAFFAAUsing %s cores", atoi(value) ? value : "all");
             ModConfig->Cores = atoi(value);
             break;
         }
         case 'p':
         {
             value = cag_option_get_value(&context);
             KPrint("\eAAFFAARedirecting I/O APIC interrupts to %s%s", atoi(value) ? "core " : "", atoi(value) ? value : "BSP");
             ModConfig->IOAPICInterruptCore = atoi(value);
             break;
         }
         case 't':
         {
             value = cag_option_get_value(&context);
             if (strcmp(value, "multi") == 0)
             {
                 KPrint("\eAAFFAAUsing Multi-Tasking Scheduler");
                 ModConfig->SchedulerType = Multi;
             }
             else if (strcmp(value, "single") == 0)
             {
                 KPrint("\eAAFFAAUsing Single-Tasking Scheduler");
                 ModConfig->SchedulerType = Mono;
             }
             else
             {
                 KPrint("\eAAFFAAUnknown scheduler: %s", value);
                 ModConfig->SchedulerType = Multi;
             }
             break;
         }
         case 'd':
         {
             value = cag_option_get_value(&context);
             strncpy(ModConfig->DriverDirectory, value, strlen(value));
             KPrint("\eAAFFAAUsing %s as driver directory", value);
             break;
         }
         case 'i':
         {
             value = cag_option_get_value(&context);
             strncpy(ModConfig->InitPath, value, strlen(value));
             KPrint("\eAAFFAAUsing %s as init program", value);
             break;
         }
         case 'y':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->UseLinuxSyscalls = true : ModConfig->UseLinuxSyscalls = false;
             KPrint("\eAAFFAAUse Linux syscalls by default: %s", value);
             break;
         }
         case 'o':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->InterruptsOnCrash = true : ModConfig->InterruptsOnCrash = false;
             KPrint("\eAAFFAAInterrupts on crash: %s", value);
             break;
         }
         case 'l':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->UnlockDeadLock = true : ModConfig->UnlockDeadLock = false;
             KPrint("\eAAFFAAUnlocking the deadlock after 10 retries");
             break;
         }
         case 's':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->SIMD = true : ModConfig->SIMD = false;
             KPrint("\eAAFFAASingle Instruction, Multiple Data (SIMD): %s", value);
             break;
         }
         case 'b':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->BootAnimation = true : ModConfig->BootAnimation = false;
             KPrint("\eAAFFAABoot animation: %s", value);
             break;
         }
         case 'h':
         {
             KPrint("\n---------------------------------------------------------------------------\nUsage: kernel.fsys [OPTION]...\nKernel configuration.");
             cag_option_print(ConfigOptions, CAG_ARRAY_SIZE(ConfigOptions), nullptr);
             KPrint("\eFF2200System Halted.");
             CPU::Stop();
         }
         default:
         {
             KPrint("\eFF2200Unknown option: %c", identifier);
             break;
         }
         }
     }
     debug("Config loaded");
 }
References KernelConfig::AllocatorType, argc, argv, atoi(), KernelConfig::BootAnimation, CAG_ARRAY_SIZE, cag_option_fetch(), cag_option_get(), cag_option_get_value(), cag_option_prepare(), cag_option_print(), ConfigOptions, context, KernelConfig::Cores, debug, KernelConfig::DriverDirectory, i, cag_option::identifier, KernelConfig::InitPath, KernelConfig::InterruptsOnCrash, KernelConfig::IOAPICInterruptCore, KPrint(), Mono, Multi, NULL, KernelConfig::SchedulerType, KernelConfig::SIMD, strcmp, strlen(), strncpy(), targp_parse(), true, KernelConfig::UnlockDeadLock, KernelConfig::UseLinuxSyscalls, and value.
Referenced by Main().
Variable Documentation
ConfigOptions
struct cag_option ConfigOptions[] static
Definition at line 38 of file KernelConfig.cpp.
Referenced by ParseConfig().