Fennix Userspace: Userspace/apps/base/busybox/util-linux/mkfs_reiser.c File Reference
mkfs_reiser.c File Reference
#include "libbb.h"
#include <linux/fs.h>
Data Structures
struct journal_params
struct reiserfs_journal_header
struct reiserfs_super_block
struct block_head
Macros
#define REISERFS_DISK_OFFSET_IN_BYTES (64 * 1024)
#define REISERFS_3_6_SUPER_MAGIC_STRING "ReIsEr2Fs"
#define REISERFS_FORMAT_3_6 2
#define DEFAULT_MAX_MNT_COUNT 30 /* 30 mounts */
#define DEFAULT_CHECK_INTERVAL (180 * 60 * 60 * 24) /* 180 days */
#define FS_CLEANLY_UMOUNTED 1 /* this was REISERFS_VALID_FS */
#define JOURNAL_MIN_SIZE 512
#define JOURNAL_TRANS_MAX 1024
#define JOURNAL_TRANS_MIN 256 /* need to check whether it works */
#define JOURNAL_DEFAULT_RATIO 8 /* default journal size / max trans length */
#define JOURNAL_MIN_RATIO 2
#define JOURNAL_MAX_BATCH 900
#define JOURNAL_MAX_COMMIT_AGE 30
Enumerations
enum {
OPT_b = 1 << 0 , OPT_j = 1 << 1 , OPT_s = 1 << 2 , OPT_o = 1 << 3 ,
OPT_t = 1 << 4 , OPT_B = 1 << 5 , OPT_h = 1 << 6 , OPT_u = 1 << 7 ,
OPT_l = 1 << 8 , OPT_f = 1 << 9 , OPT_q = 1 << 10 , OPT_d = 1 << 11
}
Functions
int mkfs_reiser_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
journal_params
struct journal_params
Definition at line 30 of file mkfs_reiser.c.
Data Fields
uint32_t jp_journal_1st_block
uint32_t jp_journal_dev
uint32_t jp_journal_magic
uint32_t jp_journal_max_batch
uint32_t jp_journal_max_commit_age
uint32_t jp_journal_max_trans_age
uint32_t jp_journal_size
uint32_t jp_journal_trans_max
reiserfs_journal_header
struct reiserfs_journal_header
Definition at line 41 of file mkfs_reiser.c.
Data Fields
uint32_t jh_first_unflushed_offset
struct journal_params jh_journal
uint32_t jh_last_check_mount_id
uint32_t jh_last_flush_trans_id
uint32_t jh_mount_id
reiserfs_super_block
struct reiserfs_super_block
Definition at line 49 of file mkfs_reiser.c.
Data Fields
uint32_t blocks_count
uint16_t blocksize
uint32_t dummy2[5]
uint16_t dummy3[3]
uint32_t dummy4[5]
uint32_t free_blocks
uint32_t journal_block
uint32_t journal_dev
uint8_t label[16]
uint8_t magic[12]
uint32_t orig_journal_size
uint32_t root_block
unsigned char s_label[16]
char s_magic[10]
char s_unused[76]
unsigned char s_uuid[16]
uint32_t sb_block_count
uint16_t sb_blocksize
uint16_t sb_bmap_nr
uint32_t sb_check_interval
uint32_t sb_flags
uint32_t sb_free_blocks
uint16_t sb_fs_state
uint32_t sb_hash_function_code
uint32_t sb_inode_generation
struct journal_params sb_journal
uint32_t sb_lastcheck
uint16_t sb_max_mnt_count
uint16_t sb_mnt_count
uint16_t sb_oid_cursize
uint16_t sb_oid_maxsize
uint16_t sb_reserved_for_journal
uint32_t sb_root_block
uint16_t sb_tree_height
uint16_t sb_umount_state
uint16_t sb_version
uint8_t uuid[16]
block_head
struct block_head
Definition at line 83 of file mkfs_reiser.c.
Data Fields
uint16_t blk2_free_space
uint16_t blk2_level
uint16_t blk2_nr_item
uint16_t blk_reserved
uint32_t reserved[4]
Macro Definition Documentation
DEFAULT_CHECK_INTERVAL
#define DEFAULT_CHECK_INTERVAL (180 * 60 * 60 * 24) /* 180 days */
Definition at line 96 of file mkfs_reiser.c.
DEFAULT_MAX_MNT_COUNT
#define DEFAULT_MAX_MNT_COUNT 30 /* 30 mounts */
Definition at line 95 of file mkfs_reiser.c.
FS_CLEANLY_UMOUNTED
#define FS_CLEANLY_UMOUNTED 1 /* this was REISERFS_VALID_FS */
Definition at line 98 of file mkfs_reiser.c.
JOURNAL_DEFAULT_RATIO
#define JOURNAL_DEFAULT_RATIO 8 /* default journal size / max trans length */
Definition at line 104 of file mkfs_reiser.c.
JOURNAL_MAX_BATCH
#define JOURNAL_MAX_BATCH 900
Definition at line 107 of file mkfs_reiser.c.
JOURNAL_MAX_COMMIT_AGE
#define JOURNAL_MAX_COMMIT_AGE 30
Definition at line 108 of file mkfs_reiser.c.
JOURNAL_MIN_RATIO
#define JOURNAL_MIN_RATIO 2
Definition at line 105 of file mkfs_reiser.c.
JOURNAL_MIN_SIZE
#define JOURNAL_MIN_SIZE 512
Definition at line 100 of file mkfs_reiser.c.
JOURNAL_TRANS_MAX
#define JOURNAL_TRANS_MAX 1024
Definition at line 102 of file mkfs_reiser.c.
JOURNAL_TRANS_MIN
#define JOURNAL_TRANS_MIN 256 /* need to check whether it works */
Definition at line 103 of file mkfs_reiser.c.
REISERFS_3_6_SUPER_MAGIC_STRING
#define REISERFS_3_6_SUPER_MAGIC_STRING "ReIsEr2Fs"
Definition at line 93 of file mkfs_reiser.c.
REISERFS_DISK_OFFSET_IN_BYTES
#define REISERFS_DISK_OFFSET_IN_BYTES (64 * 1024)
Definition at line 91 of file mkfs_reiser.c.
REISERFS_FORMAT_3_6
#define REISERFS_FORMAT_3_6 2
Definition at line 94 of file mkfs_reiser.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_b
OPT_j
OPT_s
OPT_o
OPT_t
OPT_B
OPT_h
OPT_u
OPT_l
OPT_f
OPT_q
OPT_d
Definition at line 133 of file mkfs_reiser.c.
      {
     OPT_b = 1 << 0,
     OPT_j = 1 << 1,
     OPT_s = 1 << 2,
     OPT_o = 1 << 3,
     OPT_t = 1 << 4,
     OPT_B = 1 << 5,
     OPT_h = 1 << 6,
     OPT_u = 1 << 7,
     OPT_l = 1 << 8,     // label
     OPT_f = 1 << 9,     // ask no questions
     OPT_q = 1 << 10,
     OPT_d = 1 << 11,
     //OPT_V = 1 << 12,  // -V version. bbox applets don't support that
 };
Function Documentation
mkfs_reiser_main()
int mkfs_reiser_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 150 of file mkfs_reiser.c.
 {
     unsigned blocksize = 4096;
     unsigned journal_blocks = 8192;
     unsigned blocks, bitmap_blocks, i, block;
     time_t timestamp;
     const char *label = "";
     struct stat st;
     int fd;
     uint8_t *buf;
     struct reiserfs_super_block *sb;
     struct journal_params *jp;
     struct block_head *root;
     // using global "option_mask32" instead of local "opts":
     // we are register starved here
     /*opts =*/ getopt32(argv, "^" "b:+j:s:o:t:B:h:u:l:fqd" "\0" "-1",
         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, &label);
     argv += optind; // argv[0] -- device
     // check the device is a block device
     fd = xopen(argv[0], O_WRONLY | O_EXCL);
     xfstat(fd, &st, argv[0]);
     if (!S_ISBLK(st.st_mode) && !(option_mask32 & OPT_f))
         bb_error_msg_and_die("%s: not a block device", argv[0]);
     // check if it is mounted
     // N.B. what if we format a file? find_mount_point will return false negative since
     // it is loop block device which is mounted!
     if (find_mount_point(argv[0], 0))
         bb_simple_error_msg_and_die("can't format mounted filesystem");
     // open the device, get size in blocks
     blocks = get_volume_size_in_bytes(fd, argv[1], blocksize, /*extend:*/ 1) / blocksize;
     // block number sanity check
     // we have a limit: skipped area, super block, journal and root block
     // all have to be addressed by one first bitmap
     block = REISERFS_DISK_OFFSET_IN_BYTES / blocksize // boot area
         + 1     // sb
         + 1     // bitmap#0
         + journal_blocks+1  // journal
     ;
     // count overhead
     bitmap_blocks = (blocks - 1) / (blocksize * 8) + 1;
     i = block + bitmap_blocks;
     // check overhead
     if (MIN(blocksize * 8, blocks) < i)
         bb_error_msg_and_die("need >= %u blocks", i);
     // ask confirmation?
     // TODO: ???
     // wipe out first REISERFS_DISK_OFFSET_IN_BYTES of device
     // TODO: do we really need to wipe?!
     xlseek(fd, REISERFS_DISK_OFFSET_IN_BYTES, SEEK_SET);
     // fill superblock
     sb = (struct reiserfs_super_block *)xzalloc(blocksize);
     // block count
     STORE_LE(sb->sb_block_count, blocks);
     STORE_LE(sb->sb_free_blocks, blocks - i);
     // TODO: decypher!
     STORE_LE(sb->sb_root_block, block);
     // fill journal related fields
     jp = &sb->sb_journal;
     STORE_LE(jp->jp_journal_1st_block, REISERFS_DISK_OFFSET_IN_BYTES / blocksize + 1/*sb*/ + 1/*bmp#0*/);
     timestamp = time(NULL);
     srand(timestamp);
     STORE_LE(jp->jp_journal_magic, rand());
     STORE_LE(jp->jp_journal_size, journal_blocks);
     STORE_LE(jp->jp_journal_trans_max, JOURNAL_TRANS_MAX);
     STORE_LE(jp->jp_journal_max_batch, JOURNAL_MAX_BATCH);
     STORE_LE(jp->jp_journal_max_commit_age, JOURNAL_MAX_COMMIT_AGE);
     // sizes
     STORE_LE(sb->sb_blocksize, blocksize);
     STORE_LE(sb->sb_oid_maxsize, (blocksize - sizeof(*sb)) / sizeof(uint32_t) / 2 * 2);
     STORE_LE(sb->sb_oid_cursize, 2); // "." and ".."
     strcpy(sb->s_magic, REISERFS_3_6_SUPER_MAGIC_STRING);
     STORE_LE(sb->sb_bmap_nr, (bitmap_blocks > ((1LL << 16) - 1)) ? 0 : bitmap_blocks);
     // misc
     STORE_LE(sb->sb_version, REISERFS_FORMAT_3_6);
     STORE_LE(sb->sb_lastcheck, timestamp);
     STORE_LE(sb->sb_check_interval, DEFAULT_CHECK_INTERVAL);
     STORE_LE(sb->sb_mnt_count, 1);
     STORE_LE(sb->sb_max_mnt_count, DEFAULT_MAX_MNT_COUNT);
     STORE_LE(sb->sb_umount_state, FS_CLEANLY_UMOUNTED);
     STORE_LE(sb->sb_tree_height, 2);
     STORE_LE(sb->sb_hash_function_code, 3); // R5_HASH
     STORE_LE(sb->sb_flags, 1);
     //STORE_LE(sb->sb_reserved_for_journal, 0);
     // create UUID
     generate_uuid(sb->s_uuid);
     // write the label
     safe_strncpy((char *)sb->s_label, label, sizeof(sb->s_label));
     // TODO: EMPIRIC! ENDIANNESS!
     // superblock has only 204 bytes. What are these?
     buf = (uint8_t *)sb;
     buf[205] = 1;
     buf[209] = 3;
     // put superblock
     xwrite(fd, sb, blocksize);
     // create bitmaps
     buf = xzalloc(blocksize);
     // bitmap #0 uses initial "block"+1 blocks
     i = block + 1;
     memset(buf, 0xFF, i / 8);
     buf[i / 8] = (1 << (i & 7)) - 1; //0..7 => 00000000..01111111
     // mark trailing absent blocks, if any
     if (blocks < 8*blocksize) {
         unsigned n = 8*blocksize - blocks;
         i = n / 8;
         buf[blocksize - i - 1] |= 0x7F00 >> (n & 7); //0..7 => 00000000..11111110
         memset(buf + blocksize - i, 0xFF, i); // N.B. no overflow here!
     }
     // put bitmap #0
     xwrite(fd, buf, blocksize);
     // now go journal blocks
     memset(buf, 0, blocksize);
     for (i = 0; i < journal_blocks; i++)
         xwrite(fd, buf, blocksize);
     // dump journal control block
     memcpy(&((struct reiserfs_journal_header *)buf)->jh_journal, &sb->sb_journal, sizeof(sb->sb_journal));
     xwrite(fd, buf, blocksize);
     // other bitmaps are in every (8*blocksize)-th block
     // N.B. they use the only block -- namely bitmap itself!
     buf[0] = 0x01;
     // put bitmaps
     for (i = 1; i < bitmap_blocks; i++) {
         xlseek(fd, i*8*blocksize * blocksize, SEEK_SET);
         // mark trailing absent blocks, if any
         if (i == bitmap_blocks - 1 && (blocks % (8*blocksize))) {
             unsigned n = 8*blocksize - blocks % (8*blocksize);
             unsigned j = n / 8;
             buf[blocksize - j - 1] |= 0x7F00 >> (n & 7); //0..7 => 00000000..11111110
             memset(buf + blocksize - j, 0xFF, j); // N.B. no overflow here!
         }
         xwrite(fd, buf, blocksize);
     }
     // fill root block
     // block head
     memset(buf, 0, blocksize);
     root = (struct block_head *)buf;
     STORE_LE(root->blk2_level, 1); // leaf node
     STORE_LE(root->blk2_nr_item, 2); // "." and ".."
     STORE_LE(root->blk2_free_space, blocksize - sizeof(struct block_head));
     // item head
     // root directory
     // TODO: EMPIRIC! ENDIANNESS!
     // TODO: indented assignments seem to be timestamps
 buf[4] = 0134;
 buf[24] = 01;
 buf[28] = 02;
 buf[42] = 054;
 buf[44] = 0324;
 buf[45] = 017;
 buf[46] = 01;
 buf[48] = 01;
 buf[52] = 02;
 buf[56] = 01;
 buf[60] = 0364;
 buf[61] = 01;
 buf[64] = 02;
 buf[66] = 060;
 buf[68] = 0244;
 buf[69] = 017;
 buf[4004] = 01;
 buf[4008] = 01;
 buf[4012] = 02;
 buf[4016] = 050;
 buf[4018] = 04;
 buf[4020] = 02;
 buf[4028] = 01;
 buf[4032] = 040;
 buf[4034] = 04;
 buf[4036] = 056; buf[4037] = 056;   // ".."
 buf[4044] = 056;            // "."
 buf[4052] = 0355;
 buf[4053] = 0101;
 buf[4056] = 03;
 buf[4060] = 060;
         buf[4076] = 0173;
         buf[4077] = 0240;
     buf[4078] = 0344;
     buf[4079] = 0112;
         buf[4080] = 0173;
         buf[4081] = 0240;
     buf[4082] = 0344;
     buf[4083] = 0112;
         buf[4084] = 0173;
         buf[4085] = 0240;
     buf[4086] = 0344;
     buf[4087] = 0112;
 buf[4088] = 01;
     // put root block
     xlseek(fd, block * blocksize, SEEK_SET);
     xwrite(fd, buf, blocksize);
     // cleanup
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(buf);
         free(sb);
     }
     xclose(fd);
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_simple_error_msg_and_die(), block_head::blk2_free_space, block_head::blk2_level, block_head::blk2_nr_item, reiserfs_super_block::blocksize, buf, DEFAULT_CHECK_INTERVAL, DEFAULT_MAX_MNT_COUNT, EXIT_SUCCESS, fd, find_mount_point(), free, FS_CLEANLY_UMOUNTED, generate_uuid(), get_volume_size_in_bytes(), getopt32(), i, j, JOURNAL_MAX_BATCH, JOURNAL_MAX_COMMIT_AGE, JOURNAL_TRANS_MAX, journal_params::jp_journal_1st_block, journal_params::jp_journal_magic, journal_params::jp_journal_max_batch, journal_params::jp_journal_max_commit_age, journal_params::jp_journal_size, journal_params::jp_journal_trans_max, label, memcpy(), memset(), MIN, n, NULL, O_EXCL, O_WRONLY, OPT_f, optind, option_mask32, rand(), REISERFS_3_6_SUPER_MAGIC_STRING, REISERFS_DISK_OFFSET_IN_BYTES, REISERFS_FORMAT_3_6, S_ISBLK, reiserfs_super_block::s_label, reiserfs_super_block::s_magic, reiserfs_super_block::s_uuid, safe_strncpy(), reiserfs_super_block::sb_block_count, reiserfs_super_block::sb_blocksize, reiserfs_super_block::sb_bmap_nr, reiserfs_super_block::sb_check_interval, reiserfs_super_block::sb_flags, reiserfs_super_block::sb_free_blocks, reiserfs_super_block::sb_hash_function_code, reiserfs_super_block::sb_journal, reiserfs_super_block::sb_lastcheck, reiserfs_super_block::sb_max_mnt_count, reiserfs_super_block::sb_mnt_count, reiserfs_super_block::sb_oid_cursize, reiserfs_super_block::sb_oid_maxsize, reiserfs_super_block::sb_root_block, reiserfs_super_block::sb_tree_height, reiserfs_super_block::sb_umount_state, reiserfs_super_block::sb_version, SEEK_SET, srand(), STORE_LE, strcpy(), time(), xclose(), xfstat(), xlseek(), xopen(), xwrite(), and xzalloc().