Fennix Userspace: Userspace/musl/src/internal/pthread_impl.h File Reference
pthread_impl.h File Reference
#include <pthread.h>
#include <signal.h>
#include <errno.h>
#include <limits.h>
#include <sys/mman.h>
#include "libc.h"
#include "syscall.h"
#include "atomic.h"
#include "futex.h"
#include "pthread_arch.h"
Data Structures
struct pthread
struct pthread.robust_list
Macros
#define pthread __pthread
#define __SU (sizeof(size_t)/sizeof(int))
#define _a_stacksize __u.__s[0]
#define _a_guardsize __u.__s[1]
#define _a_stackaddr __u.__s[2]
#define _a_detach __u.__i[3*__SU+0]
#define _a_sched __u.__i[3*__SU+1]
#define _a_policy __u.__i[3*__SU+2]
#define _a_prio __u.__i[3*__SU+3]
#define _m_type __u.__i[0]
#define _m_lock __u.__vi[1]
#define _m_waiters __u.__vi[2]
#define _m_prev __u.__p[3]
#define _m_next __u.__p[4]
#define _m_count __u.__i[5]
#define _c_shared __u.__p[0]
#define _c_seq __u.__vi[2]
#define _c_waiters __u.__vi[3]
#define _c_clock __u.__i[4]
#define _c_lock __u.__vi[8]
#define _c_head __u.__p[1]
#define _c_tail __u.__p[5]
#define _rw_lock __u.__vi[0]
#define _rw_waiters __u.__vi[1]
#define _rw_shared __u.__i[2]
#define _b_lock __u.__vi[0]
#define _b_waiters __u.__vi[1]
#define _b_limit __u.__i[2]
#define _b_count __u.__vi[3]
#define _b_waiters2 __u.__vi[4]
#define _b_inst __u.__p[3]
#define TP_OFFSET 0
#define DTP_OFFSET 0
#define TP_ADJ(p) (p)
#define __pthread_self() ((pthread_t)__get_tp())
#define tls_mod_off_t size_t
#define SIGTIMER 32
#define SIGCANCEL 33
#define SIGSYNCCALL 34
#define SIGALL_SET ((sigset_t *)(const unsigned long long [2]){ -1,-1 })
#define SIGPT_SET
#define SIGTIMER_SET
#define DEFAULT_STACK_SIZE 131072
#define DEFAULT_GUARD_SIZE 8192
#define DEFAULT_STACK_MAX (8<<20)
#define DEFAULT_GUARD_MAX (1<<20)
#define __ATTRP_C11_THREAD ((void*)(uintptr_t)-1)
Enumerations
enum { DT_EXITED = 0 , DT_EXITING , DT_JOINABLE , DT_DETACHED }
Functions
void * __tls_get_addr (tls_mod_off_t *)
hidden int __init_tp (void *)
hidden void * __copy_tls (unsigned char *)
hidden void __reset_tls ()
hidden void __membarrier_init (void)
hidden void __dl_thread_cleanup (void)
hidden void __testcancel ()
hidden void __do_cleanup_push (struct __ptcb *)
hidden void __do_cleanup_pop (struct __ptcb *)
hidden void __pthread_tsd_run_dtors ()
hidden void __pthread_key_delete_synccall (void(*)(void *), void *)
hidden int __pthread_key_delete_impl (pthread_key_t)
hidden int __clone (int(*)(void *), void *, int, void *,...)
hidden int __set_thread_area (void *)
hidden int __libc_sigaction (int, const struct sigaction *, struct sigaction *)
hidden void __unmapself (void *, size_t)
hidden int __timedwait (volatile int *, int, clockid_t, const struct timespec *, int)
hidden int __timedwait_cp (volatile int *, int, clockid_t, const struct timespec *, int)
hidden void __wait (volatile int *, volatile int *, int, int)
static void __wake (volatile void *addr, int cnt, int priv)
static void __futexwait (volatile void *addr, int val, int priv)
hidden void __acquire_ptc (void)
hidden void __release_ptc (void)
hidden void __inhibit_ptc (void)
hidden void __tl_lock (void)
hidden void __tl_unlock (void)
hidden void __tl_sync (pthread_t)
Variables
hidden volatile size_t __pthread_tsd_size
hidden void * __pthread_tsd_main []
hidden volatile int __eintr_valid_flag
hidden volatile int __thread_list_lock
hidden volatile int __abort_lock [1]
hidden unsigned __default_stacksize
hidden unsigned __default_guardsize
Data Structure Documentation
pthread
struct pthread
Definition at line 18 of file pthread_impl.h.
Data Fields
uintptr_t canary
volatile int cancel
volatile unsigned char cancelasync
struct __ptcb * cancelbuf
volatile unsigned char canceldisable
volatile int detach_state
char * dlerror_buf
unsigned char dlerror_flag:1
uintptr_t * dtv
int errno_val
size_t guard_size
int h_errno_val
volatile int killlock[1]
locale_t locale
unsigned char * map_base
size_t map_size
struct pthread * next
struct pthread * prev
void * result
struct pthread robust_list
struct pthread * self
void * stack
size_t stack_size
void * stdio_locks
uintptr_t sysinfo
int tid
volatile int timer_id
void ** tsd
unsigned char tsd_used:1
pthread.robust_list
struct pthread.robust_list
Definition at line 50 of file pthread_impl.h.
Data Fields
volatile void *volatile head
long off
volatile void *volatile pending
Macro Definition Documentation
__ATTRP_C11_THREAD
#define __ATTRP_C11_THREAD ((void*)(uintptr_t)-1)
Definition at line 203 of file pthread_impl.h.
__pthread_self
#define __pthread_self () ((pthread_t)__get_tp())
Definition at line 122 of file pthread_impl.h.
__SU
#define __SU (sizeof(size_t)/sizeof(int))
Definition at line 77 of file pthread_impl.h.
_a_detach
#define _a_detach __u.__i[3*__SU+0]
Definition at line 82 of file pthread_impl.h.
_a_guardsize
#define _a_guardsize __u.__s[1]
Definition at line 80 of file pthread_impl.h.
_a_policy
#define _a_policy __u.__i[3*__SU+2]
Definition at line 84 of file pthread_impl.h.
_a_prio
#define _a_prio __u.__i[3*__SU+3]
Definition at line 85 of file pthread_impl.h.
_a_sched
#define _a_sched __u.__i[3*__SU+1]
Definition at line 83 of file pthread_impl.h.
_a_stackaddr
#define _a_stackaddr __u.__s[2]
Definition at line 81 of file pthread_impl.h.
_a_stacksize
#define _a_stacksize __u.__s[0]
Definition at line 79 of file pthread_impl.h.
_b_count
#define _b_count __u.__vi[3]
Definition at line 105 of file pthread_impl.h.
_b_inst
#define _b_inst __u.__p[3]
Definition at line 107 of file pthread_impl.h.
_b_limit
#define _b_limit __u.__i[2]
Definition at line 104 of file pthread_impl.h.
_b_lock
#define _b_lock __u.__vi[0]
Definition at line 102 of file pthread_impl.h.
_b_waiters
#define _b_waiters __u.__vi[1]
Definition at line 103 of file pthread_impl.h.
_b_waiters2
#define _b_waiters2 __u.__vi[4]
Definition at line 106 of file pthread_impl.h.
_c_clock
#define _c_clock __u.__i[4]
Definition at line 95 of file pthread_impl.h.
_c_head
#define _c_head __u.__p[1]
Definition at line 97 of file pthread_impl.h.
_c_lock
#define _c_lock __u.__vi[8]
Definition at line 96 of file pthread_impl.h.
_c_seq
#define _c_seq __u.__vi[2]
Definition at line 93 of file pthread_impl.h.
_c_shared
#define _c_shared __u.__p[0]
Definition at line 92 of file pthread_impl.h.
_c_tail
#define _c_tail __u.__p[5]
Definition at line 98 of file pthread_impl.h.
_c_waiters
#define _c_waiters __u.__vi[3]
Definition at line 94 of file pthread_impl.h.
_m_count
#define _m_count __u.__i[5]
Definition at line 91 of file pthread_impl.h.
_m_lock
#define _m_lock __u.__vi[1]
Definition at line 87 of file pthread_impl.h.
_m_next
#define _m_next __u.__p[4]
Definition at line 90 of file pthread_impl.h.
_m_prev
#define _m_prev __u.__p[3]
Definition at line 89 of file pthread_impl.h.
_m_type
#define _m_type __u.__i[0]
Definition at line 86 of file pthread_impl.h.
_m_waiters
#define _m_waiters __u.__vi[2]
Definition at line 88 of file pthread_impl.h.
_rw_lock
#define _rw_lock __u.__vi[0]
Definition at line 99 of file pthread_impl.h.
_rw_shared
#define _rw_shared __u.__i[2]
Definition at line 101 of file pthread_impl.h.
_rw_waiters
#define _rw_waiters __u.__vi[1]
Definition at line 100 of file pthread_impl.h.
DEFAULT_GUARD_MAX
#define DEFAULT_GUARD_MAX (1<<20)
Definition at line 201 of file pthread_impl.h.
DEFAULT_GUARD_SIZE
#define DEFAULT_GUARD_SIZE 8192
Definition at line 198 of file pthread_impl.h.
DEFAULT_STACK_MAX
#define DEFAULT_STACK_MAX (8<<20)
Definition at line 200 of file pthread_impl.h.
DEFAULT_STACK_SIZE
#define DEFAULT_STACK_SIZE 131072
Definition at line 197 of file pthread_impl.h.
DTP_OFFSET
#define DTP_OFFSET 0
Definition at line 114 of file pthread_impl.h.
pthread
#define pthread __pthread
Definition at line 16 of file pthread_impl.h.
SIGALL_SET
#define SIGALL_SET ((sigset_t *)(const unsigned long long [2]){ -1,-1 })
Definition at line 133 of file pthread_impl.h.
SIGCANCEL
#define SIGCANCEL 33
Definition at line 130 of file pthread_impl.h.
SIGPT_SET
#define SIGPT_SET
Value:
    ((sigset_t *)(const unsigned long [_NSIG/8/sizeof(long)]){ \
    [sizeof(long)==4] = 3UL<<(32*(sizeof(long)>4)) })
Definition at line 134 of file pthread_impl.h.
SIGSYNCCALL
#define SIGSYNCCALL 34
Definition at line 131 of file pthread_impl.h.
SIGTIMER
#define SIGTIMER 32
Definition at line 129 of file pthread_impl.h.
SIGTIMER_SET
#define SIGTIMER_SET
Value:
    ((sigset_t *)(const unsigned long [_NSIG/8/sizeof(long)]){ \
     0x80000000 })
Definition at line 137 of file pthread_impl.h.
tls_mod_off_t
#define tls_mod_off_t size_t
Definition at line 126 of file pthread_impl.h.
TP_ADJ
#define TP_ADJ (p) (p)
Definition at line 121 of file pthread_impl.h.
TP_OFFSET
#define TP_OFFSET 0
Definition at line 110 of file pthread_impl.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DT_EXITED
DT_EXITING
DT_JOINABLE
DT_DETACHED
Definition at line 70 of file pthread_impl.h.
      {
     DT_EXITED = 0,
     DT_EXITING,
     DT_JOINABLE,
     DT_DETACHED,
 };
Function Documentation
__acquire_ptc()
hidden void __acquire_ptc (void)
Definition at line 10 of file lock_ptc.c.
 {
     pthread_rwlock_rdlock(&lock);
 }
References lock, and pthread_rwlock_rdlock().
Referenced by __pthread_create(), pthread_attr_init(), and pthread_getattr_default_np().
__clone()
hidden int __clone (int(*)(void *) func, void * stack, int flags, void * arg, ...)
Definition at line 4 of file clone.c.
 {
     return -ENOSYS;
 }
References ENOSYS.
Referenced by __pthread_create(), clone(), faccessat(), and posix_spawn().
__copy_tls()
hidden void* __copy_tls (unsigned char * mem)
Definition at line 39 of file __init_tls.c.
 {
     pthread_t td;
     struct tls_module *p;
     size_t i;
     uintptr_t *dtv;
 #ifdef TLS_ABOVE_TP
     dtv = (uintptr_t*)(mem + libc.tls_size) - (libc.tls_cnt + 1);
     mem += -((uintptr_t)mem + sizeof(struct pthread)) & (libc.tls_align-1);
     td = (pthread_t)mem;
     mem += sizeof(struct pthread);
     for (i=1, p=libc.tls_head; p; i++, p=p->next) {
         dtv[i] = (uintptr_t)(mem + p->offset) + DTP_OFFSET;
         memcpy(mem + p->offset, p->image, p->len);
     }
 #else
     dtv = (uintptr_t *)mem;
     mem += libc.tls_size - sizeof(struct pthread);
     mem -= (uintptr_t)mem & (libc.tls_align-1);
     td = (pthread_t)mem;
     for (i=1, p=libc.tls_head; p; i++, p=p->next) {
         dtv[i] = (uintptr_t)(mem - p->offset) + DTP_OFFSET;
         memcpy(mem - p->offset, p->image, p->len);
     }
 #endif
     dtv[0] = libc.tls_cnt;
     td->dtv = dtv;
     return td;
 }
References DTP_OFFSET, pthread::dtv, i, libc, mem, memcpy(), p, and td.
Referenced by __dls2b(), __dls3(), __pthread_create(), and static_init_tls().
__dl_thread_cleanup()
hidden void __dl_thread_cleanup (void)
Definition at line 33 of file dlerror.c.
 {
     pthread_t self = __pthread_self();
     if (!self->dlerror_buf || self->dlerror_buf == (void *)-1)
         return;
     void *h;
     do {
         h = freebuf_queue;
         *(void **)self->dlerror_buf = h;
     } while (a_cas_p(&freebuf_queue, h, self->dlerror_buf) != h);
 }
References __pthread_self, a_cas_p, freebuf_queue, and h.
Referenced by __pthread_exit().
__do_cleanup_pop()
hidden void __do_cleanup_pop (struct __ptcb * cb)
Definition at line 182 of file pthread_create.c.
 {
     __pthread_self()->cancelbuf = cb->__next;
 }
References __ptcb::__next, and __pthread_self.
Referenced by _pthread_cleanup_pop().
__do_cleanup_push()
hidden void __do_cleanup_push (struct __ptcb * cb)
Definition at line 175 of file pthread_create.c.
 {
     struct pthread *self = __pthread_self();
     cb->__next = self->cancelbuf;
     self->cancelbuf = cb;
 }
References __ptcb::__next, and __pthread_self.
Referenced by _pthread_cleanup_push().
__futexwait()
static void __futexwait (volatile void * addr, int val, int priv) inline static
Definition at line 175 of file pthread_impl.h.
 {
     if (priv) priv = FUTEX_PRIVATE;
     __syscall(SYS_futex, addr, FUTEX_WAIT|priv, val, 0) != -ENOSYS ||
     __syscall(SYS_futex, addr, FUTEX_WAIT, val, 0);
 }
References __syscall, addr, ENOSYS, FUTEX_PRIVATE, FUTEX_WAIT, SYS_futex, and val.
Referenced by __lock(), and __lockfile().
__inhibit_ptc()
hidden void __inhibit_ptc (void)
Definition at line 5 of file lock_ptc.c.
 {
     pthread_rwlock_wrlock(&lock);
 }
References lock, and pthread_rwlock_wrlock().
Referenced by dlopen(), fork(), and pthread_setattr_default_np().
__init_tp()
hidden int __init_tp (void * p)
Definition at line 14 of file __init_tls.c.
 {
     pthread_t td = p;
     td->self = td;
     int r = __set_thread_area(TP_ADJ(p));
     if (r < 0) return -1;
     if (!r) libc.can_do_threads = 1;
     td->detach_state = DT_JOINABLE;
     td->tid = __syscall(SYS_set_tid_address, &__thread_list_lock);
     td->locale = &libc.global_locale;
     td->robust_list.head = &td->robust_list.head;
     td->sysinfo = __sysinfo;
     td->next = td->prev = td;
     return 0;
 }
References __set_thread_area(), __syscall, __sysinfo, __thread_list_lock, DT_JOINABLE, libc, p, td, and TP_ADJ.
Referenced by __dls2b(), __dls3(), and static_init_tls().
__libc_sigaction()
hidden int __libc_sigaction (int , const struct sigaction * , struct sigaction *)
Referenced by __membarrier(), __synccall(), child(), and init_cancellation().
__membarrier_init()
hidden void __membarrier_init (void)
Definition at line 58 of file membarrier.c.
 {
     /* If membarrier is linked, attempt to pre-register to be able to use
      * the private expedited command before the process becomes multi-
      * threaded, since registering later has bad, potentially unbounded
      * latency. This syscall should be essentially free, and it's arguably
      * a mistake in the API design that registration was even required.
      * For other commands, registration may impose some cost, so it's left
      * to the application to do so if desired. Unfortunately this means
      * library code initialized after the process becomes multi-threaded
      * cannot use these features without accepting registration latency. */
     __syscall(SYS_membarrier, MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED, 0);
 }
References __syscall, and MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED.
Referenced by __pthread_create().
__pthread_key_delete_impl()
hidden int __pthread_key_delete_impl (pthread_key_t)
__pthread_key_delete_synccall()
hidden void __pthread_key_delete_synccall (void(*)(void *) , void *)
__pthread_tsd_run_dtors()
hidden void __pthread_tsd_run_dtors ()
Definition at line 77 of file pthread_key_create.c.
 {
     pthread_t self = __pthread_self();
     int i, j;
     for (j=0; self->tsd_used && j<PTHREAD_DESTRUCTOR_ITERATIONS; j++) {
         __pthread_rwlock_rdlock(&key_lock);
         self->tsd_used = 0;
         for (i=0; i<PTHREAD_KEYS_MAX; i++) {
             void *val = self->tsd[i];
             void (*dtor)(void *) = keys[i];
             self->tsd[i] = 0;
             if (val && dtor && dtor != nodtor) {
                 __pthread_rwlock_unlock(&key_lock);
                 dtor(val);
                 __pthread_rwlock_rdlock(&key_lock);
             }
         }
         __pthread_rwlock_unlock(&key_lock);
     }
 }
References __pthread_rwlock_rdlock(), __pthread_rwlock_unlock(), __pthread_self, i, j, key_lock, keys, nodtor(), and val.
Referenced by __pthread_exit(), and cleanup_fromsig().
__release_ptc()
hidden void __release_ptc (void)
Definition at line 15 of file lock_ptc.c.
 {
     pthread_rwlock_unlock(&lock);
 }
References lock, and pthread_rwlock_unlock().
Referenced by __pthread_create(), dlopen(), fork(), pthread_attr_init(), pthread_getattr_default_np(), and pthread_setattr_default_np().
__reset_tls()
hidden void __reset_tls ()
Definition at line 5 of file __reset_tls.c.
 {
     pthread_t self = __pthread_self();
     struct tls_module *p;
     size_t i, n = self->dtv[0];
     if (n) for (p=libc.tls_head, i=1; i<=n; i++, p=p->next) {
         char *mem = (char *)(self->dtv[i] - DTP_OFFSET);
         memcpy(mem, p->image, p->len);
         memset(mem+p->len, 0, p->size - p->len);
     }
 }
References __pthread_self, DTP_OFFSET, i, libc, mem, memcpy(), memset(), n, next, and p.
Referenced by cleanup_fromsig().
__set_thread_area()
hidden int __set_thread_area (void * p)
Definition at line 3 of file __set_thread_area.c.
 {
 #ifdef SYS_set_thread_area
     return __syscall(SYS_set_thread_area, p);
 #else
     return -ENOSYS;
 #endif
 }
References __a_barrier_kuser, __a_barrier_oldkuser, __a_barrier_ptr, __a_barrier_v6, __a_barrier_v7, __a_cas_kuser, __a_cas_ptr, __a_cas_v6, __a_cas_v7, __a_gettp_kuser, __a_gettp_ptr, __asm__(), __hwcap, __sh_cas_cas_l, __sh_cas_gusa, __sh_cas_imask, __sh_cas_llsc, __sh_cas_ptr, __sh_nommu, __syscall, a_crash, AT_PLATFORM, CPU_HAS_CAS_L, CPU_HAS_LLSC, ENOSYS, HWCAP_TLS, libc, p, and s.
Referenced by __init_tp().
__testcancel()
hidden void __testcancel ()
Definition at line 75 of file pthread_cancel.c.
 {
     pthread_t self = __pthread_self();
     if (self->cancel && !self->canceldisable)
         __cancel();
 }
References __cancel(), and __pthread_self.
Referenced by __pthread_testcancel().
__timedwait()
hidden int __timedwait (volatile int * addr, int val, clockid_t clk, const struct timespec * at, int priv)
Definition at line 63 of file __timedwait.c.
 {
     int cs, r;
     __pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     r = __timedwait_cp(addr, val, clk, at, priv);
     __pthread_setcancelstate(cs, 0);
     return r;
 }
References __pthread_setcancelstate(), __timedwait_cp(), addr, PTHREAD_CANCEL_DISABLE, and val.
Referenced by __pthread_mutex_timedlock(), __pthread_rwlock_timedrdlock(), __pthread_rwlock_timedwrlock(), and pthread_mutex_timedlock_pi().
__timedwait_cp()
hidden int __timedwait_cp (volatile int * addr, int val, clockid_t clk, const struct timespec * at, int priv)
Definition at line 32 of file __timedwait.c.
 {
     int r;
     struct timespec to, *top=0;
     if (priv) priv = FUTEX_PRIVATE;
     if (at) {
         if (at->tv_nsec >= 1000000000UL) return EINVAL;
         if (__clock_gettime(clk, &to)) return EINVAL;
         to.tv_sec = at->tv_sec - to.tv_sec;
         if ((to.tv_nsec = at->tv_nsec - to.tv_nsec) < 0) {
             to.tv_sec--;
             to.tv_nsec += 1000000000;
         }
         if (to.tv_sec < 0) return ETIMEDOUT;
         top = &to;
     }
     r = -__futex4_cp(addr, FUTEX_WAIT|priv, val, top);
     if (r != EINTR && r != ETIMEDOUT && r != ECANCELED) r = 0;
     /* Mitigate bug in old kernels wrongly reporting EINTR for non-
      * interrupting (SA_RESTART) signal handlers. This is only practical
      * when NO interrupting signal handlers have been installed, and
      * works by sigaction tracking whether that's the case. */
     if (r == EINTR && !__eintr_valid_flag) r = 0;
     return r;
 }
References __clock_gettime(), __eintr_valid_flag, __futex4_cp(), addr, ECANCELED, EINTR, EINVAL, ETIMEDOUT, FUTEX_PRIVATE, FUTEX_WAIT, top, timespec::tv_nsec, timespec::tv_sec, and val.
Referenced by __pthread_cond_timedwait(), __pthread_timedjoin_np(), __timedwait(), aio_suspend(), and sem_timedwait().
__tl_lock()
hidden void __tl_lock (void)
Definition at line 23 of file pthread_create.c.
 {
     int tid = __pthread_self()->tid;
     int val = __thread_list_lock;
     if (val == tid) {
         tl_lock_count++;
         return;
     }
     while ((val = a_cas(&__thread_list_lock, 0, tid)))
         __wait(&__thread_list_lock, &tl_lock_waiters, val, 0);
 }
References __pthread_self, __thread_list_lock, __wait(), a_cas, tl_lock_count, tl_lock_waiters, and val.
Referenced by __membarrier(), __pthread_create(), __pthread_exit(), __pthread_key_delete(), __synccall(), fork(), and install_new_tls().
__tl_sync()
hidden void __tl_sync (pthread_t td)
Definition at line 45 of file pthread_create.c.
 {
     a_barrier();
     int val = __thread_list_lock;
     if (!val) return;
     __wait(&__thread_list_lock, &tl_lock_waiters, val, 0);
     if (tl_lock_waiters) __wake(&__thread_list_lock, 1, 0);
 }
References __thread_list_lock, __wait(), __wake(), a_barrier, tl_lock_waiters, and val.
Referenced by __pthread_timedjoin_np().
__tl_unlock()
hidden void __tl_unlock (void)
Definition at line 35 of file pthread_create.c.
 {
     if (tl_lock_count) {
         tl_lock_count--;
         return;
     }
     a_store(&__thread_list_lock, 0);
     if (tl_lock_waiters) __wake(&__thread_list_lock, 1, 0);
 }
References __thread_list_lock, __wake(), a_store, tl_lock_count, and tl_lock_waiters.
Referenced by __membarrier(), __pthread_create(), __pthread_exit(), __pthread_key_delete(), __synccall(), fork(), and install_new_tls().
__tls_get_addr()
void* __tls_get_addr (tls_mod_off_t * v)
Definition at line 3 of file __tls_get_addr.c.
 {
     pthread_t self = __pthread_self();
     return (void *)(self->dtv[v[0]] + v[1]);
 }
References __pthread_self.
Referenced by dl_iterate_phdr(), do_dlsym(), and static_dl_iterate_phdr().
__unmapself()
hidden void __unmapself (void * base, size_t size)
Definition at line 17 of file __unmapself.c.
 {
     char *stack = shared_stack + sizeof shared_stack;
     stack -= (uintptr_t)stack % 16;
     unmap_base = base;
     unmap_size = size;
     CRTJMP(do_unmap, stack);
 }
References __sh_nommu, __unmapself_sh_mmu(), __unmapself_sh_nommu(), base, CRTJMP, do_unmap(), shared_stack, size, stack, unmap_base, and unmap_size.
__wait()
hidden void __wait (volatile int * addr, volatile int * waiters, int val, int priv)
Definition at line 3 of file __wait.c.
 {
     int spins=100;
     if (priv) priv = FUTEX_PRIVATE;
     while (spins-- && (!waiters || !*waiters)) {
         if (*addr==val) a_spin();
         else return;
     }
     if (waiters) a_inc(waiters);
     while (*addr==val) {
         __syscall(SYS_futex, addr, FUTEX_WAIT|priv, val, 0) != -ENOSYS
         || __syscall(SYS_futex, addr, FUTEX_WAIT, val, 0);
     }
     if (waiters) a_dec(waiters);
 }
References __syscall, a_dec, a_inc, a_spin, addr, ENOSYS, FUTEX_PRIVATE, FUTEX_WAIT, SYS_futex, and val.
Referenced by __private_cond_signal(), __pthread_create(), __pthread_once_full(), __tl_lock(), __tl_sync(), __vm_wait(), aio_cancel(), lock(), pshared_barrier_wait(), pthread_barrier_destroy(), pthread_barrier_wait(), pthread_cond_destroy(), and start().
__wake()
static void __wake (volatile void * addr, int cnt, int priv) inline static
Definition at line 168 of file pthread_impl.h.
 {
     if (priv) priv = FUTEX_PRIVATE;
     if (cnt<0) cnt = INT_MAX;
     __syscall(SYS_futex, addr, FUTEX_WAKE|priv, cnt) != -ENOSYS ||
     __syscall(SYS_futex, addr, FUTEX_WAKE, cnt);
 }
References __syscall, addr, cnt, ENOSYS, FUTEX_PRIVATE, FUTEX_WAKE, INT_MAX, and SYS_futex.
Referenced by __pthread_cond_timedwait(), __pthread_create(), __pthread_exit(), __pthread_mutex_unlock(), __pthread_once_full(), __pthread_rwlock_unlock(), __tl_sync(), __tl_unlock(), __unlock(), __unlockfile(), __vm_unlock(), cleanup(), locking_getc(), locking_putc(), pshared_barrier_wait(), pthread_barrier_wait(), pthread_cond_broadcast(), pthread_cond_destroy(), pthread_cond_signal(), sem_post(), undo(), unlock(), and unlock_requeue().
Variable Documentation
__abort_lock
hidden volatile int __abort_lock[1] extern
Definition at line 3 of file abort_lock.c.
Referenced by __sigaction(), _Fork(), abort(), and posix_spawn().
__default_guardsize
hidden unsigned __default_guardsize extern
Definition at line 4 of file default_attr.c.
Referenced by __pthread_create(), pthread_attr_init(), pthread_getattr_default_np(), and pthread_setattr_default_np().
__default_stacksize
hidden unsigned __default_stacksize extern
Definition at line 3 of file default_attr.c.
Referenced by __pthread_create(), kernel_mapped_dso(), map_library(), pthread_attr_init(), pthread_getattr_default_np(), pthread_setattr_default_np(), and static_init_tls().
__eintr_valid_flag
hidden volatile int __eintr_valid_flag extern
Definition at line 18 of file sigaction.c.
Referenced by __libc_sigaction(), and __timedwait_cp().
__pthread_tsd_main
hidden void* __pthread_tsd_main[] extern
Definition at line 5 of file pthread_key_create.c.
Referenced by __pthread_create(), and __pthread_key_create().
__pthread_tsd_size
hidden volatile size_t __pthread_tsd_size extern
Definition at line 4 of file pthread_key_create.c.
Referenced by __pthread_create().
__thread_list_lock
hidden volatile int __thread_list_lock extern
Definition at line 12 of file __init_tls.c.
Referenced by __init_tp(), __pthread_create(), __tl_lock(), __tl_sync(), __tl_unlock(), and _Fork().