Fennix Userspace: Userspace/apps/base/busybox/util-linux/fdformat.c File Reference
fdformat.c File Reference
#include "libbb.h"
Data Structures
struct floppy_struct
struct format_descr
Macros
#define FD_STRETCH 1
#define FD_SWAPSIDES 2
#define FD_2M 0x4
#define FD_SIZECODEMASK 0x38
#define FD_SIZECODE(floppy) (((((floppy)->rate&FD_SIZECODEMASK)>> 3)+ 2) %8)
#define FD_SECTSIZE(floppy)
#define FD_PERP 0x40
#define FDFMTBEG _IO(2,0x47)
#define FDFMTTRK _IOW(2,0x48, struct format_descr)
#define FDFMTEND _IO(2,0x49)
#define FDGETPRM _IOR(2, 0x04, struct floppy_struct)
#define FD_FILL_BYTE 0xF6 /* format fill byte. */
Functions
int fdformat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
floppy_struct
struct floppy_struct
Definition at line 28 of file fdformat.c.
Data Fields
fmt_gap
unsigned char gap
unsigned int head
const char * name
unsigned char rate
unsigned int sect
unsigned int size
spec1
unsigned int stretch
unsigned int track
format_descr
struct format_descr
Definition at line 51 of file fdformat.c.
Data Fields
unsigned int device
unsigned int head
unsigned int track
Macro Definition Documentation
FD_2M
#define FD_2M 0x4
Definition at line 40 of file fdformat.c.
FD_FILL_BYTE
#define FD_FILL_BYTE 0xF6 /* format fill byte. */
Definition at line 58 of file fdformat.c.
FD_PERP
#define FD_PERP 0x40
Definition at line 45 of file fdformat.c.
FD_SECTSIZE
#define FD_SECTSIZE (floppy)
Value:
                 ( (floppy)->rate & FD_2M ? \
                 512 : 128 << FD_SIZECODE(floppy) )
Definition at line 43 of file fdformat.c.
FD_SIZECODE
#define FD_SIZECODE (floppy) (((((floppy)->rate&FD_SIZECODEMASK)>> 3)+ 2) %8)
Definition at line 42 of file fdformat.c.
FD_SIZECODEMASK
#define FD_SIZECODEMASK 0x38
Definition at line 41 of file fdformat.c.
FD_STRETCH
#define FD_STRETCH 1
Definition at line 34 of file fdformat.c.
FD_SWAPSIDES
#define FD_SWAPSIDES 2
Definition at line 35 of file fdformat.c.
FDFMTBEG
#define FDFMTBEG _IO(2,0x47)
Definition at line 54 of file fdformat.c.
FDFMTEND
#define FDFMTEND _IO(2,0x49)
Definition at line 56 of file fdformat.c.
FDFMTTRK
#define FDFMTTRK _IOW(2,0x48, struct format_descr)
Definition at line 55 of file fdformat.c.
FDGETPRM
#define FDGETPRM _IOR(2, 0x04, struct floppy_struct)
Definition at line 57 of file fdformat.c.
Function Documentation
fdformat_main()
int fdformat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 61 of file fdformat.c.
 {
     int fd, n, cyl, read_bytes, verify;
     unsigned char *data;
     struct stat st;
     struct floppy_struct param;
     struct format_descr descr;
     verify = !getopt32(argv, "^" "n" "\0" "=1");
     argv += optind;
     xstat(*argv, &st);
     if (!S_ISBLK(st.st_mode)) {
         bb_error_msg_and_die("%s: not a block device", *argv);
         /* do not test major - perhaps this was an USB floppy */
     }
     /* O_RDWR for formatting and verifying */
     fd = xopen(*argv, O_RDWR);
     /* original message was: "Could not determine current format type" */
     xioctl(fd, FDGETPRM, &param);
     printf("%s-sided, %u tracks, %u sec/track. Total capacity %d kB\n",
         (param.head == 2) ? "Double" : "Single",
         param.track, param.sect, param.size >> 1);
     /* FORMAT */
     printf("Formatting... ");
     xioctl(fd, FDFMTBEG, NULL);
     /* n == track */
     for (n = 0; n < param.track; n++) {
         descr.head = 0;
         descr.track = n;
         xioctl(fd, FDFMTTRK, &descr);
         printf("%3d\b\b\b", n);
         if (param.head == 2) {
             descr.head = 1;
             xioctl(fd, FDFMTTRK, &descr);
         }
     }
     xioctl(fd, FDFMTEND, NULL);
     puts("Done");
     /* VERIFY */
     if (verify) {
         /* n == cyl_size */
         n = param.sect*param.head*512;
         data = xmalloc(n);
         printf("Verifying... ");
         for (cyl = 0; cyl < param.track; cyl++) {
             printf("%3d\b\b\b", cyl);
             read_bytes = safe_read(fd, data, n);
             if (read_bytes != n) {
                 if (read_bytes < 0) {
                     bb_simple_perror_msg(bb_msg_read_error);
                 }
                 bb_error_msg_and_die("problem reading cylinder %d, "
                     "expected %d, read %d", cyl, n, read_bytes);
                 // FIXME: maybe better seek & continue??
             }
             /* Check backwards so we don't need a counter */
             while (--read_bytes >= 0) {
                 if (data[read_bytes] != FD_FILL_BYTE) {
                     printf("bad data in cyl %d\nContinuing... ", cyl);
                 }
             }
         }
         /* There is no point in freeing blocks at the end of a program, because
         all of the program's space is given back to the system when the process
         terminates.*/
         if (ENABLE_FEATURE_CLEAN_UP) free(data);
         puts("Done");
     }
     if (ENABLE_FEATURE_CLEAN_UP) close(fd);
     /* Don't bother closing.  Exit does
      * that, so we can save a few bytes */
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_msg_read_error, bb_simple_perror_msg(), close(), EXIT_SUCCESS, fd, FD_FILL_BYTE, FDFMTBEG, FDFMTEND, FDFMTTRK, FDGETPRM, free, getopt32(), format_descr::head, n, NULL, O_RDWR, optind, param, printf(), puts(), S_ISBLK, safe_read(), format_descr::track, verify, xioctl, xmalloc, xopen(), and xstat().