Fennix: Memory64::Physical Class Reference
Memory64::Physical Class Reference
#include <memory.hpp>
Public Member Functions
void LockPage (void *Address)
void LockPages (void *Address, size_t PageCount)
void ReservePage (void *Address)
void ReservePages (void *Address, size_t PageCount)
void UnreservePage (void *Address)
void UnreservePages (void *Address, size_t PageCount)
void * RequestPage ()
void * RequestPages (size_t Count)
void FreePage (void *Address)
void FreePages (void *Address, size_t Count)
void Init (BootInfo *Info)
Physical ()
~Physical ()
Data Fields
uint64_t TotalMemory = 0
uint64_t FreeMemory = 0
uint64_t ReservedMemory = 0
uint64_t UsedMemory = 0
Private Attributes
uint64_t PageBitmapIndex = 0
Bitmap PageBitmap
Detailed Description
Definition at line 448 of file memory.hpp.
Constructor & Destructor Documentation
Physical()
Memory::Physical::Physical ()
Definition at line 476 of file PhysicalMemoryManager.cpp.
 {}
~Physical()
Memory::Physical::~Physical ()
Definition at line 477 of file PhysicalMemoryManager.cpp.
 {}
Member Function Documentation
FreePage()
void Memory::Physical::FreePage (void * Address)
Definition at line 188 of file PhysicalMemoryManager.cpp.
     {
         SmartLock(this->MemoryLock);
         if (unlikely(Address == nullptr))
         {
             warn("Null pointer passed to FreePage.");
             return;
         }
         size_t Index = (size_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == false))
         {
             warn("Tried to free an already free page. (%p)", Address);
             return;
         }
         if (PageBitmap.Set(Index, false))
         {
             FreeMemory += PAGE_SIZE;
             UsedMemory -= PAGE_SIZE;
             if (PageBitmapIndex > Index)
                 PageBitmapIndex = Index;
         }
 #ifdef DEBUG
         if (EnableExternalMemoryTracer)
         {
             char LockTmpStr[64];
             strcpy_unsafe(LockTmpStr, __FUNCTION__);
             strcat_unsafe(LockTmpStr, "_memTrk");
             mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
             sprintf(mExtTrkLog, "FreePage( %p )~%p\n\r",
                     Address,
                     __builtin_return_address(0));
             UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
             for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
             {
                 if (mExtTrkLog[i] == '\r')
                     break;
                 mTrkUART.Write(mExtTrkLog[i]);
             }
             mExtTrkLock.Unlock();
         }
 #endif
     }
References Address, UniversalAsynchronousReceiverTransmitter::COM3, i, PAGE_SIZE, sprintf(), strcat_unsafe(), strcpy_unsafe(), unlikely, warn, and UniversalAsynchronousReceiverTransmitter::UART::Write().
FreePages()
void Memory64::Physical::FreePages (void * Address, size_t Count)
Definition at line 236 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || Count == 0))
         {
             warn("%s%s%s passed to FreePages.", Address == nullptr ? "Null pointer " : "", Address == nullptr && Count == 0 ? "and " : "", Count == 0 ? "Zero count" : "");
             return;
         }
 #ifdef DEBUG
         if (EnableExternalMemoryTracer)
         {
             char LockTmpStr[64];
             strcpy_unsafe(LockTmpStr, __FUNCTION__);
             strcat_unsafe(LockTmpStr, "_memTrk");
             mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
             sprintf(mExtTrkLog, "!FreePages( %p %ld )~%p\n\r",
                     Address, Count,
                     __builtin_return_address(0));
             UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
             for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
             {
                 if (mExtTrkLog[i] == '\r')
                     break;
                 mTrkUART.Write(mExtTrkLog[i]);
             }
             mExtTrkLock.Unlock();
         }
 #endif
         for (size_t t = 0; t < Count; t++)
             this->FreePage((void *)((uintptr_t)Address + (t * PAGE_SIZE)));
     }
References Address, UniversalAsynchronousReceiverTransmitter::COM3, FreePage(), i, PAGE_SIZE, sprintf(), strcat_unsafe(), strcpy_unsafe(), unlikely, warn, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Init()
void Memory64::Physical::Init (BootInfo * Info)
Definition at line 486 of file PhysicalMemoryManager.cpp.
     {
         uint64_t MemorySize = Info->Memory.Size;
         debug("Memory size: %lld bytes (%ld pages)", MemorySize, TO_PAGES(MemorySize));
         UsedMemory = 0;
         ReservedMemory = 0;
         TotalMemory = MemorySize;
         FreeMemory = MemorySize;
         void *LargestFreeMemorySegment = nullptr;
         uint64_t LargestFreeMemorySegmentSize = 0;
         for (uint64_t i = 0; i < Info->Memory.Entries; i++)
         {
             if (Info->Memory.Entry[i].Type == Usable)
             {
                 if (Info->Memory.Entry[i].Length > LargestFreeMemorySegmentSize)
                 {
                     /* We don't want to use 0 as a memory address. */
                     if (Info->Memory.Entry[i].BaseAddress == 0x0)
                         continue;
                     LargestFreeMemorySegment = (void *)Info->Memory.Entry[i].BaseAddress;
                     LargestFreeMemorySegmentSize = Info->Memory.Entry[i].Length;
                     debug("Largest free memory segment: %llp (%lldMB)",
                           (void *)Info->Memory.Entry[i].BaseAddress,
                           TO_MB(Info->Memory.Entry[i].Length));
                 }
             }
         }
         if (LargestFreeMemorySegment == nullptr)
         {
             error("No free memory found!");
             while (1)
                 asmv("cli; hlt");
         }
         size_t BitmapSize = (MemorySize / PAGE_SIZE) / 8 + 1;
         void *LargestFreeMemorySegmentNoKernel = nullptr;
         if ((uintptr_t)LargestFreeMemorySegment >= (uintptr_t)&_kernel_start &&
             (uintptr_t)LargestFreeMemorySegment <= (uintptr_t)&_kernel_end)
         {
             LargestFreeMemorySegmentNoKernel = (void *)((uintptr_t)LargestFreeMemorySegment + (uintptr_t)&_kernel_end);
             if ((uintptr_t)LargestFreeMemorySegmentNoKernel > ((uintptr_t)LargestFreeMemorySegment + LargestFreeMemorySegmentSize))
             {
                 error("No free memory found!");
                 while (1)
                     asmv("cli; hlt");
             }
         }
         else
         {
             LargestFreeMemorySegmentNoKernel = LargestFreeMemorySegment;
         }
         debug("Initializing Bitmap at %llp-%llp (%lld Bytes)",
               LargestFreeMemorySegmentNoKernel,
               (void *)((uintptr_t)LargestFreeMemorySegmentNoKernel + BitmapSize),
               BitmapSize);
         PageBitmap.Size = BitmapSize;
         PageBitmap.Buffer = (uint8_t *)LargestFreeMemorySegmentNoKernel;
         for (size_t i = 0; i < BitmapSize; i++)
             *(uint8_t *)(PageBitmap.Buffer + i) = 0;
         debug("Reserving pages...");
         this->ReservePages(0, TO_PAGES(Info->Memory.Size));
         debug("Unreserving usable pages...");
         for (uint64_t i = 0; i < Info->Memory.Entries; i++)
         {
             if (Info->Memory.Entry[i].Type == Usable)
                 this->UnreservePages(Info->Memory.Entry[i].BaseAddress, TO_PAGES(Info->Memory.Entry[i].Length));
         }
         debug("Reserving bitmap pages...");
         this->ReservePages(PageBitmap.Buffer, TO_PAGES(PageBitmap.Size));
         debug("Reserving fennix loader...");
         this->ReservePages(&_kernel_start, TO_PAGES((uintptr_t)&_kernel_end - (uintptr_t)&_kernel_start));
         debug("Reserving kernel and its modules...");
         BootInfo::ModuleInfo *Module = &Info->Modules[0];
         int ModuleIndex = 0;
         do
         {
             debug("Reserving %s (%p-%p)", Module->CommandLine, Module->Address, (void *)((uintptr_t)Module->Address + Module->Size));
             this->ReservePages(Module->Address, TO_PAGES(Module->Size));
             Module = &Info->Modules[++ModuleIndex];
         } while (Module->Address);
         this->ReservePages(0, 16);
     }
References _kernel_end, _kernel_start, BootInfo::ModuleInfo::Address, asmv(), BootInfo::MemoryInfo::MemoryEntryInfo::BaseAddress, Bitmap::Buffer, BootInfo::ModuleInfo::CommandLine, debug, BootInfo::MemoryInfo::Entry, error, FreeMemory, i, Info, BootInfo::Memory, PAGE_SIZE, PageBitmap, ReservedMemory, ReservePages(), Bitmap::Size, BootInfo::MemoryInfo::Size, BootInfo::ModuleInfo::Size, TO_MB, TO_PAGES, TotalMemory, UnreservePages(), Usable, and UsedMemory.
LockPage()
void Memory::Physical::LockPage (void * Address)
Definition at line 267 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to lock null address.");
         uintptr_t Index = (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == true))
             return;
         if (PageBitmap.Set(Index, true))
         {
             FreeMemory -= PAGE_SIZE;
             UsedMemory += PAGE_SIZE;
         }
     }
References Address, PAGE_SIZE, unlikely, and warn.
LockPages()
void Memory64::Physical::LockPages (void * Address, size_t PageCount)
Definition at line 284 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to lock %s%s.", Address ? "null address" : "", PageCount ? "0 pages" : "");
         for (size_t i = 0; i < PageCount; i++)
             this->LockPage((void *)((uintptr_t)Address + (i * PAGE_SIZE)));
     }
References Address, i, PAGE_SIZE, unlikely, and warn.
RequestPage()
void * Memory::Physical::RequestPage ()
Definition at line 85 of file PhysicalMemoryManager.cpp.
     {
         SmartLock(this->MemoryLock);
         for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
         {
             if (PageBitmap[PageBitmapIndex] == true)
                 continue;
             this->LockPage((void *)(PageBitmapIndex * PAGE_SIZE));
 #ifdef DEBUG
             if (EnableExternalMemoryTracer)
             {
                 char LockTmpStr[64];
                 strcpy_unsafe(LockTmpStr, __FUNCTION__);
                 strcat_unsafe(LockTmpStr, "_memTrk");
                 mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
                 sprintf(mExtTrkLog, "RequestPage( )=%p~%p\n\r",
                         (void *)(PageBitmapIndex * PAGE_SIZE), __builtin_return_address(0));
                 UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
                 for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
                 {
                     if (mExtTrkLog[i] == '\r')
                         break;
                     mTrkUART.Write(mExtTrkLog[i]);
                 }
                 mExtTrkLock.Unlock();
             }
 #endif
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         if (this->SwapPage((void *)(PageBitmapIndex * PAGE_SIZE)))
         {
             this->LockPage((void *)(PageBitmapIndex * PAGE_SIZE));
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         error("Out of memory! (Free: %ldMB; Used: %ldMB; Reserved: %ldMB)", TO_MB(FreeMemory), TO_MB(UsedMemory), TO_MB(ReservedMemory));
         CPU::Stop();
         __builtin_unreachable();
     }
References UniversalAsynchronousReceiverTransmitter::COM3, error, i, PAGE_SIZE, sprintf(), strcat_unsafe(), strcpy_unsafe(), TO_MB, and UniversalAsynchronousReceiverTransmitter::UART::Write().
RequestPages()
void * Memory64::Physical::RequestPages (size_t Count)
Definition at line 128 of file PhysicalMemoryManager.cpp.
     {
         SmartLock(this->MemoryLock);
         for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
         {
             if (PageBitmap[PageBitmapIndex] == true)
                 continue;
             for (uint64_t Index = PageBitmapIndex; Index < PageBitmap.Size * 8; Index++)
             {
                 if (PageBitmap[Index] == true)
                     continue;
                 for (size_t i = 0; i < Count; i++)
                 {
                     if (PageBitmap[Index + i] == true)
                         goto NextPage;
                 }
                 this->LockPages((void *)(Index * PAGE_SIZE), Count);
 #ifdef DEBUG
                 if (EnableExternalMemoryTracer)
                 {
                     char LockTmpStr[64];
                     strcpy_unsafe(LockTmpStr, __FUNCTION__);
                     strcat_unsafe(LockTmpStr, "_memTrk");
                     mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
                     sprintf(mExtTrkLog, "RequestPages( %ld )=%p~%p\n\r",
                             Count,
                             (void *)(Index * PAGE_SIZE), __builtin_return_address(0));
                     UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
                     for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
                     {
                         if (mExtTrkLog[i] == '\r')
                             break;
                         mTrkUART.Write(mExtTrkLog[i]);
                     }
                     mExtTrkLock.Unlock();
                 }
 #endif
                 return (void *)(Index * PAGE_SIZE);
             NextPage:
                 Index += Count;
                 continue;
             }
         }
         if (this->SwapPages((void *)(PageBitmapIndex * PAGE_SIZE), Count))
         {
             this->LockPages((void *)(PageBitmapIndex * PAGE_SIZE), Count);
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         error("Out of memory! (Free: %ldMB; Used: %ldMB; Reserved: %ldMB)", TO_MB(FreeMemory), TO_MB(UsedMemory), TO_MB(ReservedMemory));
         CPU::Halt(true);
         __builtin_unreachable();
     }
References UniversalAsynchronousReceiverTransmitter::COM3, error, Halt(), i, PAGE_SIZE, sprintf(), strcat_unsafe(), strcpy_unsafe(), TO_MB, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by Memory64::Virtual::Map().
ReservePage()
void Memory::Physical::ReservePage (void * Address)
Definition at line 293 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to reserve null address.");
         uintptr_t Index = (Address == NULL) ? 0 : (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == true))
             return;
         if (PageBitmap.Set(Index, true))
         {
             FreeMemory -= PAGE_SIZE;
             ReservedMemory += PAGE_SIZE;
         }
     }
References Address, NULL, PAGE_SIZE, unlikely, and warn.
ReservePages()
void Memory64::Physical::ReservePages (void * Address, size_t PageCount)
Definition at line 310 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to reserve %s%s.", Address ? "null address" : "", PageCount ? "0 pages" : "");
         for (size_t t = 0; t < PageCount; t++)
         {
             uintptr_t Index = ((uintptr_t)Address + (t * PAGE_SIZE)) / PAGE_SIZE;
             if (unlikely(PageBitmap[Index] == true))
                 return;
             if (PageBitmap.Set(Index, true))
             {
                 FreeMemory -= PAGE_SIZE;
                 ReservedMemory += PAGE_SIZE;
             }
         }
     }
References Address, PAGE_SIZE, unlikely, and warn.
Referenced by Init().
UnreservePage()
void Memory::Physical::UnreservePage (void * Address)
Definition at line 330 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to unreserve null address.");
         uintptr_t Index = (Address == NULL) ? 0 : (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == false))
             return;
         if (PageBitmap.Set(Index, false))
         {
             FreeMemory += PAGE_SIZE;
             ReservedMemory -= PAGE_SIZE;
             if (PageBitmapIndex > Index)
                 PageBitmapIndex = Index;
         }
     }
References Address, NULL, PAGE_SIZE, unlikely, and warn.
UnreservePages()
void Memory64::Physical::UnreservePages (void * Address, size_t PageCount)
Definition at line 349 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to unreserve %s%s.", Address ? "null address" : "", PageCount ? "0 pages" : "");
         for (size_t t = 0; t < PageCount; t++)
         {
             uintptr_t Index = ((uintptr_t)Address + (t * PAGE_SIZE)) / PAGE_SIZE;
             if (unlikely(PageBitmap[Index] == false))
                 return;
             if (PageBitmap.Set(Index, false))
             {
                 FreeMemory += PAGE_SIZE;
                 ReservedMemory -= PAGE_SIZE;
                 if (PageBitmapIndex > Index)
                     PageBitmapIndex = Index;
             }
         }
     }
References Address, PAGE_SIZE, unlikely, and warn.
Referenced by Init().
Field Documentation
FreeMemory
uint64_t Memory64::Physical::FreeMemory = 0
Definition at line 456 of file memory.hpp.
Referenced by Init().
PageBitmap
Bitmap Memory64::Physical::PageBitmap private
Definition at line 452 of file memory.hpp.
Referenced by Init().
PageBitmapIndex
uint64_t Memory64::Physical::PageBitmapIndex = 0 private
Definition at line 451 of file memory.hpp.
ReservedMemory
uint64_t Memory64::Physical::ReservedMemory = 0
Definition at line 457 of file memory.hpp.
Referenced by Init().
TotalMemory
uint64_t Memory64::Physical::TotalMemory = 0
Definition at line 455 of file memory.hpp.
Referenced by Init().
UsedMemory
uint64_t Memory64::Physical::UsedMemory = 0
Definition at line 458 of file memory.hpp.
Referenced by Init().
The documentation for this class was generated from the following files:
Lynx/FennixLoader/include/memory.hpp
Kernel/Core/Memory/PhysicalMemoryManager.cpp