Fennix: Power::Power Class Reference
Power::Power Class Reference
#include <power.hpp>
Public Member Functions
void * GetACPI ()
Get Advanced Configuration and Power Interface. (Available only on x32 and x64)
void * GetDSDT ()
Get Differentiated System Description Table. (Available only on x32 and x64)
void * GetMADT ()
Get Multiple APIC Description Table. (Available only on x32 and x64)
void Reboot ()
Reboot the system.
void Shutdown ()
Shutdown the system.
void InitDSDT ()
Power ()
Private Attributes
void * acpi = nullptr
void * dsdt = nullptr
void * madt = nullptr
Detailed Description
Definition at line 25 of file power.hpp.
Constructor & Destructor Documentation
Power()
Power::Power::Power ()
Definition at line 79 of file power.cpp.
     {
         this->acpi = new ACPI::ACPI;
         this->madt = new ACPI::MADT(((ACPI::ACPI *)acpi)->MADT);
         trace("Power manager initialized");
     }
References trace.
Member Function Documentation
GetACPI()
void* Power::Power::GetACPI () inline
Get Advanced Configuration and Power Interface. (Available only on x32 and x64)
Returns
void* (ACPI::ACPI *)
Definition at line 38 of file power.hpp.
 { return this->acpi; }
Referenced by DetectByHPET(), Main(), and PCI::PCI::PCI().
GetDSDT()
void* Power::Power::GetDSDT () inline
Get Differentiated System Description Table. (Available only on x32 and x64)
Returns
void* (ACPI::DSDT *)
Definition at line 45 of file power.hpp.
 { return this->dsdt; }
GetMADT()
void* Power::Power::GetMADT () inline
Get Multiple APIC Description Table. (Available only on x32 and x64)
Returns
void* (ACPI::MADT *)
Definition at line 52 of file power.hpp.
 { return this->madt; }
Referenced by APIC::APIC::APIC(), Interrupts::Enable(), APIC::APIC::IOGetMaxRedirect(), Main(), APIC::APIC::RawRedirectIRQ(), and APIC::APIC::RedirectIRQ().
InitDSDT()
void Power::Power::InitDSDT ()
Definition at line 73 of file power.cpp.
     {
         if (((ACPI::ACPI *)this->acpi)->FADT)
             this->dsdt = new ACPI::DSDT((ACPI::ACPI *)acpi);
     }
Referenced by Main().
Reboot()
void Power::Power::Reboot ()
Reboot the system.
Definition at line 29 of file power.cpp.
     {
         if (((ACPI::ACPI *)this->acpi)->FADT)
             if (((ACPI::DSDT *)this->dsdt)->ACPIShutdownSupported)
                 ((ACPI::DSDT *)this->dsdt)->Reboot();
         uint8_t val = 0x02;
         while (val & 0x02)
             val = inb(0x64);
         outb(0x64, 0xFE);
         warn("Executing the second attempt to reboot...");
         // https://wiki.osdev.org/Reboot
         /* Second attempt to reboot */
         asmv("cli");
         uint8_t temp;
         do
         {
             temp = inb(0x64);
             if (((temp) & (1 << (0))) != 0)
                 inb(0x60);
         } while (((temp) & (1 << (1))) != 0);
         outb(0x64, 0xFE);
         CPU::Stop();
     }
References asmv(), inb(), outb(), val, and warn.
Referenced by KernelShutdownThread(), and CrashHandler::UserInput().
Shutdown()
void Power::Power::Shutdown ()
Shutdown the system.
Definition at line 57 of file power.cpp.
     {
         if (((ACPI::ACPI *)this->acpi)->FADT)
             if (((ACPI::DSDT *)this->dsdt)->ACPIShutdownSupported)
                 ((ACPI::DSDT *)this->dsdt)->Shutdown();
                 /* TODO: If no ACPI, display "It is now safe to turn off your computer" */
                 /* FIXME: Detect emulators and use their shutdown methods */
 #ifdef DEBUG
         outl(0xB004, 0x2000); // for qemu
         outl(0x604, 0x2000);  // if qemu not working, bochs and older versions of qemu
         outl(0x4004, 0x3400); // virtual box
 #endif
         CPU::Stop();
     }
References outl().
Referenced by KernelShutdownThread(), and CrashHandler::UserInput().
Field Documentation
acpi
void* Power::Power::acpi = nullptr private
Definition at line 28 of file power.hpp.
dsdt
void* Power::Power::dsdt = nullptr private
Definition at line 29 of file power.hpp.
madt
void* Power::Power::madt = nullptr private
Definition at line 30 of file power.hpp.
The documentation for this class was generated from the following files:
Kernel/include/power.hpp
Kernel/core/power.cpp