Fennix: Userspace/apps/base/busybox/util-linux/mkfs_vfat.c File Reference
mkfs_vfat.c File Reference
#include "libbb.h"
#include <linux/hdreg.h>
#include <linux/fd.h>
#include <sys/mount.h>
Data Structures
struct msdos_dir_entry
struct msdos_volume_info
struct msdos_boot_sector
struct fat32_fsinfo
struct bug_check
Macros
#define BLKSSZGET _IO(0x12, 104)
#define SECTOR_SIZE 512
#define SECTORS_PER_BLOCK (BLOCK_SIZE / SECTOR_SIZE)
#define EOF_FAT32 0x0FFFFFF8
#define BAD_FAT32 0x0FFFFFF7
#define MAX_CLUST_32 0x0FFFFFF0
#define ATTR_VOLUME 8
#define NUM_FATS 2
#define TEST_BUFFER_BLOCKS 16
#define BOOT_SIGN 0xAA55
#define FAT_FSINFO_SIG1 0x41615252
#define FAT_FSINFO_SIG2 0x61417272
#define MARK_CLUSTER(cluster, value) ((uint32_t *)fat)[cluster] = SWAP_LE32(value)
Enumerations
enum { info_sector_number = 1 , backup_boot_sector = 3 , reserved_sect = 6 }
Functions
int mkfs_vfat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct msdos_dir_entry PACKED
static const char boot_code[] ALIGN1
Data Structure Documentation
msdos_dir_entry
struct msdos_dir_entry
Definition at line 102 of file mkfs_vfat.c.
Data Fields
uint16_t adate
uint8_t attr
uint16_t cdate
uint16_t ctime
uint8_t ctime_cs
uint16_t date
uint8_t lcase
char name[11]
uint32_t size
uint16_t start
uint16_t starthi
uint16_t time
msdos_volume_info
struct msdos_volume_info
Definition at line 125 of file mkfs_vfat.c.
Data Fields
uint8_t drive_number
uint8_t ext_boot_sign
char fs_type[8]
uint8_t reserved
uint32_t volume_id32
char volume_label[11]
msdos_boot_sector
struct msdos_boot_sector
Definition at line 134 of file mkfs_vfat.c.
Data Fields
char boot_code[0x200 - 0x5a - 2]
char boot_jump_and_sys_id[3+8]
uint16_t boot_sign
uint16_t bytes_per_sect
uint16_t dir_entries
uint16_t fat32_backup_boot
uint16_t fat32_flags
uint16_t fat32_info_sector
uint32_t fat32_root_cluster
uint32_t fat32_sect_per_fat
uint8_t fat32_version[2]
uint32_t fat32_volume_size_sect
uint8_t fats
uint16_t heads
uint32_t hidden
uint8_t media_byte
uint32_t reserved2[3]
uint16_t reserved_sect
uint8_t sect_per_clust
uint16_t sect_per_fat
uint16_t sect_per_track
struct msdos_volume_info vi
uint16_t volume_size_sect
fat32_fsinfo
struct fat32_fsinfo
Definition at line 165 of file mkfs_vfat.c.
Data Fields
uint16_t boot_sign
uint32_t free_clusters
uint32_t next_cluster
uint32_t reserved1[128 - 8]
uint32_t reserved2[3]
uint16_t reserved3
uint32_t signature1
uint32_t signature2
bug_check
struct bug_check
Definition at line 176 of file mkfs_vfat.c.
Data Fields
char BUG1[sizeof(struct msdos_dir_entry)==0x20 ? 1 :-1]
char BUG2[sizeof(struct msdos_volume_info)==0x1a ? 1 :-1]
char BUG3[sizeof(struct msdos_boot_sector)==0x200 ? 1 :-1]
char BUG4[sizeof(struct fat32_fsinfo)==0x200 ? 1 :-1]
Macro Definition Documentation
ATTR_VOLUME
#define ATTR_VOLUME 8
Definition at line 63 of file mkfs_vfat.c.
BAD_FAT32
#define BAD_FAT32 0x0FFFFFF7
Definition at line 60 of file mkfs_vfat.c.
BLKSSZGET
#define BLKSSZGET _IO(0x12, 104)
Definition at line 50 of file mkfs_vfat.c.
BOOT_SIGN
#define BOOT_SIGN 0xAA55
Definition at line 159 of file mkfs_vfat.c.
EOF_FAT32
#define EOF_FAT32 0x0FFFFFF8
Definition at line 59 of file mkfs_vfat.c.
FAT_FSINFO_SIG1
#define FAT_FSINFO_SIG1 0x41615252
Definition at line 163 of file mkfs_vfat.c.
FAT_FSINFO_SIG2
#define FAT_FSINFO_SIG2 0x61417272
Definition at line 164 of file mkfs_vfat.c.
MARK_CLUSTER
#define MARK_CLUSTER (cluster, value) ((uint32_t *)fat)[cluster] = SWAP_LE32(value)
Definition at line 204 of file mkfs_vfat.c.
MAX_CLUST_32
#define MAX_CLUST_32 0x0FFFFFF0
Definition at line 61 of file mkfs_vfat.c.
NUM_FATS
#define NUM_FATS 2
Definition at line 65 of file mkfs_vfat.c.
SECTOR_SIZE
#define SECTOR_SIZE 512
Definition at line 54 of file mkfs_vfat.c.
SECTORS_PER_BLOCK
#define SECTORS_PER_BLOCK (BLOCK_SIZE / SECTOR_SIZE)
Definition at line 56 of file mkfs_vfat.c.
TEST_BUFFER_BLOCKS
#define TEST_BUFFER_BLOCKS 16
Definition at line 100 of file mkfs_vfat.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
info_sector_number
backup_boot_sector
reserved_sect
Definition at line 90 of file mkfs_vfat.c.
      {
 // Perhaps this should remain constant
     info_sector_number = 1,
 // TODO: make these cmdline options
 // dont forget sanity check: backup_boot_sector + 3 <= reserved_sect
     backup_boot_sector = 3,
     reserved_sect      = 6,
 };
Function Documentation
mkfs_vfat_main()
int mkfs_vfat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 219 of file mkfs_vfat.c.
 {
     static const char NO_NAME_11[] = "NO NAME    ";
     struct stat st;
     const char *arg_volume_label = NO_NAME_11; //default
     char volume_label11[12];
     char *buf;
     char *device_name;
     uoff_t volume_size_bytes;
     uoff_t volume_size_sect;
     uint32_t total_clust;
     uint32_t volume_id;
     int dev;
     unsigned bytes_per_sect;
     unsigned sect_per_fat;
     unsigned opts;
     uint16_t sect_per_track;
     uint8_t media_byte;
     uint8_t sect_per_clust;
     uint8_t heads;
     enum {
         OPT_A = 1 << 0,  // [IGNORED] atari format
         OPT_b = 1 << 1,  // [IGNORED] location of backup boot sector
         OPT_c = 1 << 2,  // [IGNORED] check filesystem
         OPT_C = 1 << 3,  // [IGNORED] create a new file
         OPT_f = 1 << 4,  // [IGNORED] number of FATs
         OPT_F = 1 << 5,  // [IGNORED, implied 32] choose FAT size
         OPT_h = 1 << 6,  // [IGNORED] number of hidden sectors
         OPT_I = 1 << 7,  // [IGNORED] don't bark at entire disk devices
         OPT_i = 1 << 8,  // [IGNORED] volume ID
         OPT_l = 1 << 9,  // [IGNORED] bad block filename
         OPT_m = 1 << 10, // [IGNORED] message file
         OPT_n = 1 << 11, // volume label
         OPT_r = 1 << 12, // [IGNORED] root directory entries
         OPT_R = 1 << 13, // [IGNORED] number of reserved sectors
         OPT_s = 1 << 14, // [IGNORED] sectors per cluster
         OPT_S = 1 << 15, // [IGNORED] sector size
         OPT_v = 1 << 16, // verbose
     };
     opts = getopt32(argv, "^"
         "Ab:cCf:F:h:Ii:l:m:n:r:R:s:S:v"
         "\0" "-1", //:b+:f+:F+:h+:r+:R+:s+:S+:vv:c--l:l--c
         /*b*/NULL, /*f*/NULL, /*F*/NULL, /*h*/NULL, /*i*/NULL,
         /*l*/NULL, /*m*/NULL, /*n*/&arg_volume_label,
         /*r*/NULL, /*R*/NULL, /*s*/NULL, /*S*/NULL);
     argv += optind;
     // cache device name
     device_name = argv[0];
     // default volume ID = creation time
     volume_id = time(NULL);
     // truncate to exactly 11 chars, pad with spaces
     sprintf(volume_label11, "%-11.11s", arg_volume_label);
     dev = xopen(device_name, O_RDWR);
     xfstat(dev, &st, device_name);
     //
     // Get image size and sector size
     //
     bytes_per_sect = SECTOR_SIZE;
     if (!S_ISBLK(st.st_mode)) {
         if (!S_ISREG(st.st_mode)) {
             if (!argv[1])
                 bb_simple_error_msg_and_die("image size must be specified");
         }
         // not a block device, skip bad sectors check
         opts &= ~OPT_c;
     } else {
         int min_bytes_per_sect;
 #if 0
         unsigned device_num;
         // for true block devices we do check sanity
         device_num = st.st_rdev & 0xff3f;
         // do we allow to format the whole disk device?
         if (!(opts & OPT_I) && (
             device_num == 0x0300 || // hda, hdb
             (device_num & 0xff0f) == 0x0800 || // sd
             device_num == 0x0d00 || // xd
             device_num == 0x1600 )  // hdc, hdd
         )
             bb_error_msg_and_die("will not try to make filesystem on full-disk device (use -I if wanted)");
         // can't work on mounted filesystems
         if (find_mount_point(device_name, 0))
             bb_error_msg_and_die("can't format mounted filesystem");
 #endif
         // get true sector size
         // (parameter must be int*, not long* or size_t*)
         xioctl(dev, BLKSSZGET, &min_bytes_per_sect);
         if (min_bytes_per_sect > SECTOR_SIZE) {
             bytes_per_sect = min_bytes_per_sect;
             bb_error_msg("for this device sector size is %u", min_bytes_per_sect);
         }
     }
     volume_size_bytes = get_volume_size_in_bytes(dev, argv[1], 1024, /*extend:*/ 1);
     volume_size_sect = volume_size_bytes / bytes_per_sect;
     //
     // Find out or guess media parameters
     //
     media_byte = 0xf8;
     heads = 255;
     sect_per_track = 63;
     sect_per_clust = 1;
     {
         struct hd_geometry geometry;
         // size (in sectors), sect (per track), head
         struct floppy_struct param;
         // N.B. whether to use HDIO_GETGEO or HDIO_REQ?
         if (ioctl(dev, HDIO_GETGEO, &geometry) == 0
          && geometry.sectors
          && geometry.heads
         ) {
             // hard drive
             sect_per_track = geometry.sectors;
             heads = geometry.heads;
  set_cluster_size:
             /* For FAT32, try to do the same as M$'s format command
              * (see http://www.win.tue.nl/~aeb/linux/fs/fat/fatgen103.pdf p. 20):
              * fs size <= 260M: 0.5k clusters
              * fs size <=   8G: 4k clusters
              * fs size <=  16G: 8k clusters
              * fs size >   16G: 16k clusters
              */
             sect_per_clust = 1;
             if (volume_size_bytes >= 260*1024*1024) {
                 sect_per_clust = 8;
                 /* fight gcc: */
                 /* "error: integer overflow in expression" */
                 /* "error: right shift count >= width of type" */
                 if (sizeof(off_t) > 4) {
                     unsigned t = (volume_size_bytes >> 31 >> 1);
                     if (t >= 8/4)
                         sect_per_clust = 16;
                     if (t >= 16/4)
                         sect_per_clust = 32;
                 }
             }
         } else {
             // floppy, loop, or regular file
             int not_floppy = ioctl(dev, FDGETPRM, &param);
             if (not_floppy == 0) {
                 // floppy disk
                 sect_per_track = param.sect;
                 heads = param.head;
                 volume_size_sect = param.size;
                 volume_size_bytes = param.size * SECTOR_SIZE;
             }
             // setup the media descriptor byte
             switch (volume_size_sect) {
             case 2*360: // 5.25", 2, 9, 40 - 360K
                 media_byte = 0xfd;
                 break;
             case 2*720: // 3.5", 2, 9, 80 - 720K
             case 2*1200:    // 5.25", 2, 15, 80 - 1200K
                 media_byte = 0xf9;
                 break;
             default:    // anything else
                 if (not_floppy)
                     goto set_cluster_size;
             case 2*1440:    // 3.5", 2, 18, 80 - 1440K
             case 2*2880:    // 3.5", 2, 36, 80 - 2880K
                 media_byte = 0xf0;
                 break;
             }
             // not floppy, but size matches floppy exactly.
             // perhaps it is a floppy image.
             // we already set media_byte as if it is a floppy,
             // now set sect_per_track and heads.
             heads = 2;
             sect_per_track = (unsigned)volume_size_sect / 160;
             if (sect_per_track < 9)
                 sect_per_track = 9;
         }
     }
     //
     // Calculate number of clusters, sectors/cluster, sectors/FAT
     // (an initial guess for sect_per_clust should already be set)
     //
     // "mkdosfs -v -F 32 image5k 5" is the minimum:
     // 2 sectors for FATs and 2 data sectors
     if ((off_t)(volume_size_sect - reserved_sect) < 4)
         bb_simple_error_msg_and_die("the image is too small for FAT32");
     sect_per_fat = 1;
     while (1) {
         while (1) {
             int spf_adj;
             uoff_t tcl = (volume_size_sect - reserved_sect - NUM_FATS * sect_per_fat) / sect_per_clust;
             // tcl may be > MAX_CLUST_32 here, but it may be
             // because sect_per_fat is underestimated,
             // and with increased sect_per_fat it still may become
             // <= MAX_CLUST_32. Therefore, we do not check
             // against MAX_CLUST_32, but against a bigger const:
             if (tcl > 0x80ffffff)
                 goto next;
             total_clust = tcl; // fits in uint32_t
             // Every cluster needs 4 bytes in FAT. +2 entries since
             // FAT has space for non-existent clusters 0 and 1.
             // Let's see how many sectors that needs.
             //May overflow at "*4":
             //spf_adj = ((total_clust+2) * 4 + bytes_per_sect-1) / bytes_per_sect - sect_per_fat;
             //Same in the more obscure, non-overflowing form:
             spf_adj = ((total_clust+2) + (bytes_per_sect/4)-1) / (bytes_per_sect/4) - sect_per_fat;
 #if 0
             bb_error_msg("sect_per_clust:%u sect_per_fat:%u total_clust:%u",
                     sect_per_clust, sect_per_fat, (int)tcl);
             bb_error_msg("adjust to sect_per_fat:%d", spf_adj);
 #endif
             if (spf_adj <= 0) {
                 // do not need to adjust sect_per_fat.
                 // so, was total_clust too big after all?
                 if (total_clust <= MAX_CLUST_32)
                     goto found_total_clust; // no
                 // yes, total_clust is _a bit_ too big
                 goto next;
             }
             // adjust sect_per_fat, go back and recalc total_clust
             // (note: just "sect_per_fat += spf_adj" isn't ok)
             sect_per_fat += ((unsigned)spf_adj / 2) | 1;
         }
  next:
         if (sect_per_clust == 128)
             bb_simple_error_msg_and_die("can't make FAT32 with >128 sectors/cluster");
         sect_per_clust *= 2;
         sect_per_fat = (sect_per_fat / 2) | 1;
     }
  found_total_clust:
     //
     // Print info
     //
     if (opts & OPT_v) {
         fprintf(stderr,
             "Device '%s':\n"
             "heads:%u, sectors/track:%u, bytes/sector:%u\n"
             "media descriptor:%02x\n"
             "total sectors:%"OFF_FMT"u, clusters:%u, sectors/cluster:%u\n"
             "FATs:2, sectors/FAT:%u\n"
             "volumeID:%08x, label:'%s'\n",
             device_name,
             heads, sect_per_track, bytes_per_sect,
             (int)media_byte,
             volume_size_sect, (int)total_clust, (int)sect_per_clust,
             sect_per_fat,
             (int)volume_id, volume_label11
         );
     }
     //
     // Write filesystem image sequentially (no seeking)
     //
     {
         // (a | b) is poor man's max(a, b)
         unsigned bufsize = reserved_sect;
         //bufsize |= sect_per_fat; // can be quite large
         bufsize |= 2; // use this instead
         bufsize |= sect_per_clust;
         buf = xzalloc(bufsize * bytes_per_sect);
     }
     { // boot and fsinfo sectors, and their copies
         struct msdos_boot_sector *boot_blk = (void*)buf;
         struct fat32_fsinfo *info = (void*)(buf + bytes_per_sect);
         strcpy(boot_blk->boot_jump_and_sys_id, "\xeb\x58\x90" "mkdosfs");
         STORE_LE(boot_blk->bytes_per_sect, bytes_per_sect);
         STORE_LE(boot_blk->sect_per_clust, sect_per_clust);
         // cast in needed on big endian to suppress a warning
         STORE_LE(boot_blk->reserved_sect, (uint16_t)reserved_sect);
         STORE_LE(boot_blk->fats, 2);
         //STORE_LE(boot_blk->dir_entries, 0); // for FAT32, stays 0
         if (volume_size_sect <= 0xffff)
             STORE_LE(boot_blk->volume_size_sect, volume_size_sect);
         STORE_LE(boot_blk->media_byte, media_byte);
         // wrong: this would make Linux think that it's fat12/16:
         //if (sect_per_fat <= 0xffff)
         //  STORE_LE(boot_blk->sect_per_fat, sect_per_fat);
         // works:
         //STORE_LE(boot_blk->sect_per_fat, 0);
         STORE_LE(boot_blk->sect_per_track, sect_per_track);
         STORE_LE(boot_blk->heads, heads);
         //STORE_LE(boot_blk->hidden, 0);
         STORE_LE(boot_blk->fat32_volume_size_sect, volume_size_sect);
         STORE_LE(boot_blk->fat32_sect_per_fat, sect_per_fat);
         //STORE_LE(boot_blk->fat32_flags, 0);
         //STORE_LE(boot_blk->fat32_version[2], 0,0);
         STORE_LE(boot_blk->fat32_root_cluster, 2);
         STORE_LE(boot_blk->fat32_info_sector, info_sector_number);
         STORE_LE(boot_blk->fat32_backup_boot, backup_boot_sector);
         //STORE_LE(boot_blk->reserved2[3], 0,0,0);
         STORE_LE(boot_blk->vi.ext_boot_sign, 0x29);
         STORE_LE(boot_blk->vi.volume_id32, volume_id);
         memcpy(boot_blk->vi.fs_type, "FAT32   ", sizeof(boot_blk->vi.fs_type));
         memcpy(boot_blk->vi.volume_label, volume_label11, 11);
         memcpy(boot_blk->boot_code, boot_code, sizeof(boot_code));
         STORE_LE(boot_blk->boot_sign, BOOT_SIGN);
         STORE_LE(info->signature1, FAT_FSINFO_SIG1);
         STORE_LE(info->signature2, FAT_FSINFO_SIG2);
         // we've allocated cluster 2 for the root dir
         STORE_LE(info->free_clusters, (total_clust - 1));
         STORE_LE(info->next_cluster, 2);
         STORE_LE(info->boot_sign, BOOT_SIGN);
         // 1st copy
         xwrite(dev, buf, bytes_per_sect * backup_boot_sector);
         // 2nd copy and possibly zero sectors
         xwrite(dev, buf, bytes_per_sect * (reserved_sect - backup_boot_sector));
     }
     { // file allocation tables
         unsigned i,j;
         unsigned char *fat = (void*)buf;
         memset(buf, 0, bytes_per_sect * 2);
         // initial FAT entries
         MARK_CLUSTER(0, 0x0fffff00 | media_byte);
         MARK_CLUSTER(1, 0xffffffff);
         // mark cluster 2 as EOF (used for root dir)
         MARK_CLUSTER(2, EOF_FAT32);
         for (i = 0; i < NUM_FATS; i++) {
             xwrite(dev, buf, bytes_per_sect);
             for (j = 1; j < sect_per_fat; j++)
                 xwrite(dev, buf + bytes_per_sect, bytes_per_sect);
         }
     }
     // root directory
     // empty directory is just a set of zero bytes
     memset(buf, 0, sect_per_clust * bytes_per_sect);
     // not "NO NAME", "NO NAME  " etc?
     // (mkfs.fat 4.1 won't create dir entry even with explicit -n 'NO NAME',
     // but will create one with e.g. -n '', -n '  zZz')
     if (strcmp(volume_label11, NO_NAME_11) != 0) {
         // create dir entry for volume label
         struct msdos_dir_entry *de;
 #if 0
         struct tm tm_time;
         uint16_t t, d;
 #endif
         de = (void*)buf;
         memcpy(de->name, volume_label11, 11);
         STORE_LE(de->attr, ATTR_VOLUME);
 #if 0
         localtime_r(&create_time, &tm_time);
         t = (tm_time.tm_sec >> 1) + (tm_time.tm_min << 5) + (tm_time.tm_hour << 11);
         d = tm_time.tm_mday + ((tm_time.tm_mon+1) << 5) + ((tm_time.tm_year-80) << 9);
         STORE_LE(de->time, t);
         STORE_LE(de->date, d);
         //STORE_LE(de->ctime_cs, 0);
         de->ctime = de->time;
         de->cdate = de->date;
         de->adate = de->date;
 #endif
     }
     xwrite(dev, buf, sect_per_clust * bytes_per_sect);
 #if 0
     if (opts & OPT_c) {
         uoff_t volume_size_blocks;
         unsigned start_data_sector;
         unsigned start_data_block;
         unsigned badblocks = 0;
         int try, got;
         off_t currently_testing;
         char *blkbuf = xmalloc(BLOCK_SIZE * TEST_BUFFER_BLOCKS);
         volume_size_blocks = (volume_size_bytes >> BLOCK_SIZE_BITS);
         // N.B. the two following vars are in hard sectors, i.e. SECTOR_SIZE byte sectors!
         start_data_sector = (reserved_sect + NUM_FATS * sect_per_fat) * (bytes_per_sect / SECTOR_SIZE);
         start_data_block = (start_data_sector + SECTORS_PER_BLOCK - 1) / SECTORS_PER_BLOCK;
         bb_error_msg("searching for bad blocks");
         currently_testing = 0;
         try = TEST_BUFFER_BLOCKS;
         while (currently_testing < volume_size_blocks) {
             if (currently_testing + try > volume_size_blocks)
                 try = volume_size_blocks - currently_testing;
             // perform a test on a block. return the number of blocks
             // that could be read successfully.
             // seek to the correct location
             xlseek(dev, currently_testing * BLOCK_SIZE, SEEK_SET);
             // try reading
             got = read(dev, blkbuf, try * BLOCK_SIZE);
             if (got < 0)
                 got = 0;
             if (got & (BLOCK_SIZE - 1))
                 bb_error_msg("unexpected values in do_check: probably bugs");
             got /= BLOCK_SIZE;
             currently_testing += got;
             if (got == try) {
                 try = TEST_BUFFER_BLOCKS;
                 continue;
             }
             try = 1;
             if (currently_testing < start_data_block)
                 bb_error_msg_and_die("bad blocks before data-area: cannot make fs");
             // mark all of the sectors in the block as bad
             for (i = 0; i < SECTORS_PER_BLOCK; i++) {
                 int cluster = (currently_testing * SECTORS_PER_BLOCK + i - start_data_sector) / (int) (sect_per_clust) / (bytes_per_sect / SECTOR_SIZE);
                 if (cluster < 0)
                     bb_error_msg_and_die("invalid cluster number in mark_sector: probably bug!");
                 MARK_CLUSTER(cluster, BAD_FAT32);
             }
             badblocks++;
             currently_testing++;
         }
         free(blkbuf);
         if (badblocks)
             bb_error_msg("%d bad block(s)", badblocks);
     }
 #endif
     // cleanup
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(buf);
         close(dev);
     }
     return 0;
 }
References msdos_dir_entry::adate, argv, msdos_dir_entry::attr, ATTR_VOLUME, backup_boot_sector, BAD_FAT32, bb_error_msg(), bb_error_msg_and_die(), bb_simple_error_msg_and_die(), BLKSSZGET, BLOCK_SIZE, msdos_boot_sector::boot_code, msdos_boot_sector::boot_jump_and_sys_id, BOOT_SIGN, msdos_boot_sector::boot_sign, buf, msdos_boot_sector::bytes_per_sect, msdos_dir_entry::cdate, close(), msdos_dir_entry::ctime, msdos_dir_entry::date, device_name, EOF_FAT32, msdos_volume_info::ext_boot_sign, msdos_boot_sector::fat32_backup_boot, msdos_boot_sector::fat32_info_sector, msdos_boot_sector::fat32_root_cluster, msdos_boot_sector::fat32_sect_per_fat, msdos_boot_sector::fat32_volume_size_sect, FAT_FSINFO_SIG1, FAT_FSINFO_SIG2, msdos_boot_sector::fats, FDGETPRM, find_mount_point(), fprintf(), free, msdos_volume_info::fs_type, get_volume_size_in_bytes(), getopt32(), HDIO_GETGEO, hd_geometry::heads, msdos_boot_sector::heads, i, info, info_sector_number, ioctl(), j, MARK_CLUSTER, MAX_CLUST_32, msdos_boot_sector::media_byte, memcpy, memset, msdos_dir_entry::name, next, NULL, NUM_FATS, O_RDWR, OFF_FMT, off_t, OPT_A, OPT_b, OPT_C, OPT_c, OPT_F, OPT_f, OPT_h, OPT_i, OPT_I, OPT_l, OPT_m, OPT_n, OPT_R, OPT_r, OPT_s, OPT_S, OPT_v, optind, param, read(), reserved_sect, msdos_boot_sector::reserved_sect, S_ISBLK, S_ISREG, msdos_boot_sector::sect_per_clust, msdos_boot_sector::sect_per_track, SECTOR_SIZE, hd_geometry::sectors, SECTORS_PER_BLOCK, SEEK_SET, sprintf(), stderr, STORE_LE, strcmp, strcpy, t, TEST_BUFFER_BLOCKS, msdos_dir_entry::time, time(), tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_year, msdos_boot_sector::vi, msdos_volume_info::volume_id32, msdos_volume_info::volume_label, msdos_boot_sector::volume_size_sect, xfstat(), xioctl, xlseek(), xmalloc, xopen(), xwrite(), and xzalloc().
Variable Documentation
ALIGN1
const char boot_code [] ALIGN1 static
Initial value:
=
    "\x0e"
    "\x1f"
    "\xbe\x77\x7c"
    "\xac"
    "\x22\xc0"
    "\x74\x0b"
    "\x56"
    "\xb4\x0e"
    "\xbb\x07\x00"
    "\xcd\x10"
    "\x5e"
    "\xeb\xf0"
    "\x32\xe4"
    "\xcd\x16"
    "\xcd\x19"
    "\xeb\xfe"
    "This is not a bootable disk\r\n"
Definition at line 183 of file mkfs_vfat.c.
PACKED
struct fat32_fsinfo PACKED