Fennix: Userspace/musl/src/crypt/crypt_des.c File Reference
crypt_des.c File Reference
#include <stdint.h>
#include <string.h>
#include "crypt_des.h"
Macros
#define _PASSWORD_EFMT1 '_'
Functions
static uint32_t ascii_to_bin (int ch)
static int ascii_is_unsafe (unsigned char ch)
static uint32_t setup_salt (uint32_t salt)
void __des_setkey (const unsigned char *key, struct expanded_key *ekey)
void __do_des (uint32_t l_in, uint32_t r_in, uint32_t *l_out, uint32_t *r_out, uint32_t count, uint32_t saltbits, const struct expanded_key *ekey)
static void des_cipher (const unsigned char *in, unsigned char *out, uint32_t count, uint32_t saltbits, const struct expanded_key *ekey)
static char * _crypt_extended_r_uut (const char *_key, const char *_setting, char *output)
char * __crypt_des (const char *key, const char *setting, char *output)
Variables
static const unsigned char key_shifts [16]
static const uint32_t psbox [8][64]
static const uint32_t ip_maskl [16][16]
static const uint32_t ip_maskr [16][16]
static const uint32_t fp_maskl [8][16]
static const uint32_t fp_maskr [8][16]
static const uint32_t key_perm_maskl [8][16]
static const uint32_t key_perm_maskr [12][16]
static const uint32_t comp_maskl0 [4][8]
static const uint32_t comp_maskr0 [4][8]
static const uint32_t comp_maskl1 [4][16]
static const uint32_t comp_maskr1 [4][16]
static const unsigned char ascii64 []
Macro Definition Documentation
_PASSWORD_EFMT1
#define _PASSWORD_EFMT1 '_'
Definition at line 61 of file crypt_des.c.
Function Documentation
__crypt_des()
char* __crypt_des (const char * key, const char * setting, char * output)
Definition at line 984 of file crypt_des.c.
 {
     const char *test_key = "\x80\xff\x80\x01 "
         "\x7f\x81\x80\x80\x0d\x0a\xff\x7f \x81 test";
     const char *test_setting = "_0.../9Zz";
     const char *test_hash = "_0.../9ZzX7iSJNd21sU";
     char test_buf[21];
     char *retval;
     const char *p;
     if (*setting != _PASSWORD_EFMT1) {
         test_setting = "\x80x";
         test_hash = "\x80x22/wK52ZKGA";
     }
     /*
      * Hash the supplied password.
      */
     retval = _crypt_extended_r_uut(key, setting, output);
     /*
      * Perform a quick self-test.  It is important that we make both calls
      * to _crypt_extended_r_uut() from the same scope such that they likely
      * use the same stack locations, which makes the second call overwrite
      * the first call's sensitive data on the stack and makes it more
      * likely that any alignment related issues would be detected.
      */
     p = _crypt_extended_r_uut(test_key, test_setting, test_buf);
     if (p && !strcmp(p, test_hash) && retval)
         return retval;
     return (setting[0]=='*') ? "x" : "*";
 }
References _crypt_extended_r_uut(), _PASSWORD_EFMT1, output, p, retval, and strcmp.
Referenced by __crypt_r().
__des_setkey()
void __des_setkey (const unsigned char * key, struct expanded_key * ekey)
Definition at line 693 of file crypt_des.c.
 {
     uint32_t k0, k1, rawkey0, rawkey1;
     unsigned int shifts, round, i, ibit;
     rawkey0 =
         (uint32_t)key[3] |
         ((uint32_t)key[2] << 8) |
         ((uint32_t)key[1] << 16) |
         ((uint32_t)key[0] << 24);
     rawkey1 =
         (uint32_t)key[7] |
         ((uint32_t)key[6] << 8) |
         ((uint32_t)key[5] << 16) |
         ((uint32_t)key[4] << 24);
     /*
      * Do key permutation and split into two 28-bit subkeys.
      */
     k0 = k1 = 0;
     for (i = 0, ibit = 28; i < 4; i++, ibit -= 4) {
         unsigned int j = i << 1;
         k0 |= key_perm_maskl[i][(rawkey0 >> ibit) & 0xf] |
               key_perm_maskl[i + 4][(rawkey1 >> ibit) & 0xf];
         k1 |= key_perm_maskr[j][(rawkey0 >> ibit) & 0xf];
         ibit -= 4;
         k1 |= key_perm_maskr[j + 1][(rawkey0 >> ibit) & 0xf] |
               key_perm_maskr[i + 8][(rawkey1 >> ibit) & 0xf];
     }
     /*
      * Rotate subkeys and do compression permutation.
      */
     shifts = 0;
     for (round = 0; round < 16; round++) {
         uint32_t t0, t1;
         uint32_t kl, kr;
         shifts += key_shifts[round];
         t0 = (k0 << shifts) | (k0 >> (28 - shifts));
         t1 = (k1 << shifts) | (k1 >> (28 - shifts));
         kl = kr = 0;
         ibit = 25;
         for (i = 0; i < 4; i++) {
             kl |= comp_maskl0[i][(t0 >> ibit) & 7];
             kr |= comp_maskr0[i][(t1 >> ibit) & 7];
             ibit -= 4;
             kl |= comp_maskl1[i][(t0 >> ibit) & 0xf];
             kr |= comp_maskr1[i][(t1 >> ibit) & 0xf];
             ibit -= 3;
         }
         ekey->l[round] = kl;
         ekey->r[round] = kr;
     }
 }
References comp_maskl0, comp_maskl1, comp_maskr0, comp_maskr1, i, j, key_perm_maskl, key_perm_maskr, key_shifts, expanded_key::l, expanded_key::r, round, t0, and t1.
Referenced by _crypt_extended_r_uut(), and setkey().
__do_des()
void __do_des (uint32_t l_in, uint32_t r_in, uint32_t * l_out, uint32_t * r_out, uint32_t count, uint32_t saltbits, const struct expanded_key * ekey)
Definition at line 754 of file crypt_des.c.
 {
     uint32_t l, r;
     /*
      * Do initial permutation (IP).
      */
     l = r = 0;
     if (l_in | r_in) {
         unsigned int i, ibit;
         for (i = 0, ibit = 28; i < 8; i++, ibit -= 4) {
             l |= ip_maskl[i][(l_in >> ibit) & 0xf] |
                  ip_maskl[i + 8][(r_in >> ibit) & 0xf];
             r |= ip_maskr[i][(l_in >> ibit) & 0xf] |
                  ip_maskr[i + 8][(r_in >> ibit) & 0xf];
         }
     }
     while (count--) {
         /*
          * Do each round.
          */
         unsigned int round = 16;
         const uint32_t *kl = ekey->l;
         const uint32_t *kr = ekey->r;
         uint32_t f;
         while (round--) {
             uint32_t r48l, r48r;
             /*
              * Expand R to 48 bits (simulate the E-box).
              */
             r48l    = ((r & 0x00000001) << 23)
                 | ((r & 0xf8000000) >> 9)
                 | ((r & 0x1f800000) >> 11)
                 | ((r & 0x01f80000) >> 13)
                 | ((r & 0x001f8000) >> 15);
             r48r    = ((r & 0x0001f800) << 7)
                 | ((r & 0x00001f80) << 5)
                 | ((r & 0x000001f8) << 3)
                 | ((r & 0x0000001f) << 1)
                 | ((r & 0x80000000) >> 31);
             /*
              * Do salting for crypt() and friends, and
              * XOR with the permuted key.
              */
             f = (r48l ^ r48r) & saltbits;
             r48l ^= f ^ *kl++;
             r48r ^= f ^ *kr++;
             /*
              * Do S-box lookups (which shrink it back to 32 bits)
              * and do the P-box permutation at the same time.
              */
             f = psbox[0][r48l >> 18]
               | psbox[1][(r48l >> 12) & 0x3f]
               | psbox[2][(r48l >> 6) & 0x3f]
               | psbox[3][r48l & 0x3f]
               | psbox[4][r48r >> 18]
               | psbox[5][(r48r >> 12) & 0x3f]
               | psbox[6][(r48r >> 6) & 0x3f]
               | psbox[7][r48r & 0x3f];
             /*
              * Now that we've permuted things, complete f().
              */
             f ^= l;
             l = r;
             r = f;
         }
         r = l;
         l = f;
     }
     /*
      * Do final permutation (inverse of IP).
      */
     {
         unsigned int i, ibit;
         uint32_t lo, ro;
         lo = ro = 0;
         for (i = 0, ibit = 28; i < 4; i++, ibit -= 4) {
             ro |= fp_maskr[i][(l >> ibit) & 0xf] |
                   fp_maskr[i + 4][(r >> ibit) & 0xf];
             ibit -= 4;
             lo |= fp_maskl[i][(l >> ibit) & 0xf] |
                   fp_maskl[i + 4][(r >> ibit) & 0xf];
         }
         *l_out = lo;
         *r_out = ro;
     }
 }
References count, f, fp_maskl, fp_maskr, i, ip_maskl, ip_maskr, l, expanded_key::l, psbox, expanded_key::r, round, and saltbits.
Referenced by _crypt_extended_r_uut(), des_cipher(), and encrypt().
_crypt_extended_r_uut()
static char* _crypt_extended_r_uut (const char * _key, const char * _setting, char * output) static
Definition at line 875 of file crypt_des.c.
 {
     const unsigned char *key = (const unsigned char *)_key;
     const unsigned char *setting = (const unsigned char *)_setting;
     struct expanded_key ekey;
     unsigned char keybuf[8];
     unsigned char *p, *q;
     uint32_t count, salt, l, r0, r1;
     unsigned int i;
     /*
      * Copy the key, shifting each character left by one bit and padding
      * with zeroes.
      */
     q = keybuf;
     while (q <= &keybuf[sizeof(keybuf) - 1]) {
         *q++ = *key << 1;
         if (*key)
             key++;
     }
     __des_setkey(keybuf, &ekey);
     if (*setting == _PASSWORD_EFMT1) {
         /*
          * "new"-style:
          *  setting - underscore, 4 chars of count, 4 chars of salt
          *  key - unlimited characters
          */
         for (i = 1, count = 0; i < 5; i++) {
             uint32_t value = ascii_to_bin(setting[i]);
             if (ascii64[value] != setting[i])
                 return NULL;
             count |= value << (i - 1) * 6;
         }
         if (!count)
             return NULL;
         for (i = 5, salt = 0; i < 9; i++) {
             uint32_t value = ascii_to_bin(setting[i]);
             if (ascii64[value] != setting[i])
                 return NULL;
             salt |= value << (i - 5) * 6;
         }
         while (*key) {
             /*
              * Encrypt the key with itself.
              */
             des_cipher(keybuf, keybuf, 1, 0, &ekey);
             /*
              * And XOR with the next 8 characters of the key.
              */
             q = keybuf;
             while (q <= &keybuf[sizeof(keybuf) - 1] && *key)
                 *q++ ^= *key++ << 1;
             __des_setkey(keybuf, &ekey);
         }
         memcpy(output, setting, 9);
         output[9] = '\0';
         p = (unsigned char *)output + 9;
     } else {
         /*
          * "old"-style:
          *  setting - 2 chars of salt
          *  key - up to 8 characters
          */
         count = 25;
         if (ascii_is_unsafe(setting[0]) || ascii_is_unsafe(setting[1]))
             return NULL;
         salt = (ascii_to_bin(setting[1]) << 6)
              |  ascii_to_bin(setting[0]);
         output[0] = setting[0];
         output[1] = setting[1];
         p = (unsigned char *)output + 2;
     }
     /*
      * Do it.
      */
     __do_des(0, 0, &r0, &r1, count, setup_salt(salt), &ekey);
     /*
      * Now encode the result...
      */
     l = (r0 >> 8);
     *p++ = ascii64[(l >> 18) & 0x3f];
     *p++ = ascii64[(l >> 12) & 0x3f];
     *p++ = ascii64[(l >> 6) & 0x3f];
     *p++ = ascii64[l & 0x3f];
     l = (r0 << 16) | ((r1 >> 16) & 0xffff);
     *p++ = ascii64[(l >> 18) & 0x3f];
     *p++ = ascii64[(l >> 12) & 0x3f];
     *p++ = ascii64[(l >> 6) & 0x3f];
     *p++ = ascii64[l & 0x3f];
     l = r1 << 2;
     *p++ = ascii64[(l >> 12) & 0x3f];
     *p++ = ascii64[(l >> 6) & 0x3f];
     *p++ = ascii64[l & 0x3f];
     *p = 0;
     return output;
 }
References __des_setkey(), __do_des(), _PASSWORD_EFMT1, ascii64, ascii_is_unsafe(), ascii_to_bin(), count, des_cipher(), i, keybuf, l, memcpy, NULL, output, p, r0, r1, setup_salt(), and value.
Referenced by __crypt_des().
ascii_is_unsafe()
static int ascii_is_unsafe (unsigned char ch) inline static
Definition at line 670 of file crypt_des.c.
 {
     return !ch || ch == '\n' || ch == ':';
 }
Referenced by _crypt_extended_r_uut().
ascii_to_bin()
static uint32_t ascii_to_bin (int ch) static
Definition at line 650 of file crypt_des.c.
 {
     int sch = (ch < 0x80) ? ch : -(0x100 - ch);
     int retval;
     retval = sch - '.';
     if (sch >= 'A') {
         retval = sch - ('A' - 12);
         if (sch >= 'a')
             retval = sch - ('a' - 38);
     }
     retval &= 0x3f;
     return retval;
 }
References retval.
Referenced by _crypt_extended_r_uut().
des_cipher()
static void des_cipher (const unsigned char * in, unsigned char * out, uint32_t count, uint32_t saltbits, const struct expanded_key * ekey) static
Definition at line 847 of file crypt_des.c.
 {
     uint32_t l_out, r_out, rawl, rawr;
     rawl =
         (uint32_t)in[3] |
         ((uint32_t)in[2] << 8) |
         ((uint32_t)in[1] << 16) |
         ((uint32_t)in[0] << 24);
     rawr =
         (uint32_t)in[7] |
         ((uint32_t)in[6] << 8) |
         ((uint32_t)in[5] << 16) |
         ((uint32_t)in[4] << 24);
     __do_des(rawl, rawr, &l_out, &r_out, count, saltbits, ekey);
     out[0] = l_out >> 24;
     out[1] = l_out >> 16;
     out[2] = l_out >> 8;
     out[3] = l_out;
     out[4] = r_out >> 24;
     out[5] = r_out >> 16;
     out[6] = r_out >> 8;
     out[7] = r_out;
 }
References __do_des(), count, out(), and saltbits.
Referenced by _crypt_extended_r_uut().
setup_salt()
static uint32_t setup_salt (uint32_t salt) static
Definition at line 675 of file crypt_des.c.
 {
     uint32_t obit, saltbit, saltbits;
     unsigned int i;
     saltbits = 0;
     saltbit = 1;
     obit = 0x800000;
     for (i = 0; i < 24; i++) {
         if (salt & saltbit)
             saltbits |= obit;
         saltbit <<= 1;
         obit >>= 1;
     }
     return saltbits;
 }
References i, and saltbits.
Referenced by _crypt_extended_r_uut().
Variable Documentation
ascii64
const unsigned char ascii64[] static
Initial value:
=
    "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
Definition at line 641 of file crypt_des.c.
Referenced by _crypt_extended_r_uut(), des_crypt(), and to64_msb_first().
comp_maskl0
const uint32_t comp_maskl0[4][8] static
Initial value:
= {
    {
        0x00000000,0x00020000,0x00000001,0x00020001,
        0x00080000,0x000a0000,0x00080001,0x000a0001,
    },{
        0x00000000,0x00001000,0x00000000,0x00001000,
        0x00000040,0x00001040,0x00000040,0x00001040,
    },{
        0x00000000,0x00400000,0x00000020,0x00400020,
        0x00008000,0x00408000,0x00008020,0x00408020,
    },{
        0x00000000,0x00100000,0x00000800,0x00100800,
        0x00000000,0x00100000,0x00000800,0x00100800,
    },
}
Definition at line 564 of file crypt_des.c.
Referenced by __des_setkey().
comp_maskl1
const uint32_t comp_maskl1[4][16] static
Initial value:
= {
    {
        0x00000000,0x00000010,0x00004000,0x00004010,
        0x00040000,0x00040010,0x00044000,0x00044010,
        0x00000100,0x00000110,0x00004100,0x00004110,
        0x00040100,0x00040110,0x00044100,0x00044110,
    },{
        0x00000000,0x00800000,0x00000002,0x00800002,
        0x00000200,0x00800200,0x00000202,0x00800202,
        0x00200000,0x00a00000,0x00200002,0x00a00002,
        0x00200200,0x00a00200,0x00200202,0x00a00202,
    },{
        0x00000000,0x00002000,0x00000004,0x00002004,
        0x00000400,0x00002400,0x00000404,0x00002404,
        0x00000000,0x00002000,0x00000004,0x00002004,
        0x00000400,0x00002400,0x00000404,0x00002404,
    },{
        0x00000000,0x00010000,0x00000008,0x00010008,
        0x00000080,0x00010080,0x00000088,0x00010088,
        0x00000000,0x00010000,0x00000008,0x00010008,
        0x00000080,0x00010080,0x00000088,0x00010088,
    },
}
Definition at line 594 of file crypt_des.c.
Referenced by __des_setkey().
comp_maskr0
const uint32_t comp_maskr0[4][8] static
Initial value:
= {
    {
        0x00000000,0x00200000,0x00020000,0x00220000,
        0x00000002,0x00200002,0x00020002,0x00220002,
    },{
        0x00000000,0x00000000,0x00100000,0x00100000,
        0x00000004,0x00000004,0x00100004,0x00100004,
    },{
        0x00000000,0x00004000,0x00000800,0x00004800,
        0x00000000,0x00004000,0x00000800,0x00004800,
    },{
        0x00000000,0x00400000,0x00008000,0x00408000,
        0x00000008,0x00400008,0x00008008,0x00408008,
    },
}
Definition at line 579 of file crypt_des.c.
Referenced by __des_setkey().
comp_maskr1
const uint32_t comp_maskr1[4][16] static
Initial value:
= {
    {
        0x00000000,0x00000000,0x00000080,0x00000080,
        0x00002000,0x00002000,0x00002080,0x00002080,
        0x00000001,0x00000001,0x00000081,0x00000081,
        0x00002001,0x00002001,0x00002081,0x00002081,
    },{
        0x00000000,0x00000010,0x00800000,0x00800010,
        0x00010000,0x00010010,0x00810000,0x00810010,
        0x00000200,0x00000210,0x00800200,0x00800210,
        0x00010200,0x00010210,0x00810200,0x00810210,
    },{
        0x00000000,0x00000400,0x00001000,0x00001400,
        0x00080000,0x00080400,0x00081000,0x00081400,
        0x00000020,0x00000420,0x00001020,0x00001420,
        0x00080020,0x00080420,0x00081020,0x00081420,
    },{
        0x00000000,0x00000100,0x00040000,0x00040100,
        0x00000000,0x00000100,0x00040000,0x00040100,
        0x00000040,0x00000140,0x00040040,0x00040140,
        0x00000040,0x00000140,0x00040040,0x00040140,
    },
}
Definition at line 617 of file crypt_des.c.
Referenced by __des_setkey().
fp_maskl
const uint32_t fp_maskl[8][16] static
Definition at line 372 of file crypt_des.c.
Referenced by __do_des().
fp_maskr
const uint32_t fp_maskr[8][16] static
Definition at line 415 of file crypt_des.c.
Referenced by __do_des().
ip_maskl
const uint32_t ip_maskl[16][16] static
Definition at line 206 of file crypt_des.c.
Referenced by __do_des().
ip_maskr
const uint32_t ip_maskr[16][16] static
Definition at line 289 of file crypt_des.c.
Referenced by __do_des().
key_perm_maskl
const uint32_t key_perm_maskl[8][16] static
Definition at line 458 of file crypt_des.c.
Referenced by __des_setkey().
key_perm_maskr
const uint32_t key_perm_maskr[12][16] static
Definition at line 501 of file crypt_des.c.
Referenced by __des_setkey().
key_shifts
static const uint8_t key_shifts static
Initial value:
= {
    1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1
}
Definition at line 63 of file crypt_des.c.
Referenced by __des_setkey(), and des_setkey().
psbox
const uint32_t psbox[8][64] static
Definition at line 67 of file crypt_des.c.
Referenced by __do_des().