Fennix: Userspace/apps/base/busybox/networking/tls.h File Reference
tls.h File Reference
#include "libbb.h"
#include "tls_pstm.h"
#include "tls_aes.h"
#include "tls_aesgcm.h"
#include "tls_rsa.h"
Macros
#define HAVE_NATIVE_INT64
#define USE_AES
#define PS_SUCCESS 0
#define PS_FAILURE -1
#define PS_ARG_FAIL -6 /* Failure due to bad function param */
#define PS_PLATFORM_FAIL -7 /* Failure as a result of system call error */
#define PS_MEM_FAIL -8 /* Failure to allocate requested memory */
#define PS_LIMIT_FAIL -9 /* Failure on sanity/limit tests */
#define PS_TRUE 1
#define PS_FALSE 0
#define ENDIAN_LITTLE 1
#define PS_EXPTMOD_WINSIZE 3
#define PUBKEY_TYPE 0x01
#define PRIVKEY_TYPE 0x02
#define AES_BLOCK_SIZE 16
#define ALIGNED_long ALIGNED(sizeof(long))
#define matrixCryptoGetPrngData(buf, len, userPtr) (tls_get_random(buf, len), PS_SUCCESS)
#define psFree(p, pool) free(p)
#define psTraceCrypto(msg) bb_simple_error_msg_and_die(msg)
#define memset_s(A, B, C, D) memset((A),(C),(D))
#define memcmpct(s1, s2, len) memcmp((s1), (s2), (len))
#define min(x, y) ((x) < (y) ? (x) : (y))
#define EC_CURVE_KEYSIZE 32
#define P256_KEYSIZE 32
#define CURVE25519_KEYSIZE 32
Typedefs
typedef uint64_t uint64
typedef int64_t int64
typedef uint32_t uint32
typedef int32_t int32
typedef uint16_t uint16
typedef int16_t int16
Functions
void tls_get_random (void *buf, unsigned len) FAST_FUNC
void xorbuf (void *buf, const void *mask, unsigned count) FAST_FUNC
void xorbuf_aligned_AES_BLOCK_SIZE (void *buf, const void *mask) FAST_FUNC
void curve_x25519_compute_pubkey_and_premaster (uint8_t *pubkey32, uint8_t *premaster32, const uint8_t *peerkey32) FAST_FUNC
void curve_P256_compute_pubkey_and_premaster (uint8_t *pubkey2x32, uint8_t *premaster32, const uint8_t *peerkey2x32) FAST_FUNC
void curve_P256_compute_pubkey_and_premaster_NEW (uint8_t *pubkey2x32, uint8_t *premaster32, const uint8_t *peerkey2x32) FAST_FUNC
Macro Definition Documentation
AES_BLOCK_SIZE
#define AES_BLOCK_SIZE 16
Definition at line 81 of file tls.h.
ALIGNED_long
#define ALIGNED_long ALIGNED(sizeof(long))
Definition at line 87 of file tls.h.
CURVE25519_KEYSIZE
#define CURVE25519_KEYSIZE 32
Definition at line 110 of file tls.h.
EC_CURVE_KEYSIZE
#define EC_CURVE_KEYSIZE 32
Definition at line 108 of file tls.h.
ENDIAN_LITTLE
#define ENDIAN_LITTLE 1
Definition at line 60 of file tls.h.
HAVE_NATIVE_INT64
#define HAVE_NATIVE_INT64
Definition at line 15 of file tls.h.
matrixCryptoGetPrngData
#define matrixCryptoGetPrngData (buf, len, userPtr) (tls_get_random(buf, len), PS_SUCCESS)
Definition at line 90 of file tls.h.
memcmpct
#define memcmpct (s1, s2, len) memcmp((s1), (s2), (len))
Definition at line 98 of file tls.h.
memset_s
#define memset_s (A, B, C, D) memset((A),(C),(D))
Definition at line 96 of file tls.h.
min
#define min (x, y) ((x) < (y) ? (x) : (y))
Definition at line 100 of file tls.h.
P256_KEYSIZE
#define P256_KEYSIZE 32
Definition at line 109 of file tls.h.
PRIVKEY_TYPE
#define PRIVKEY_TYPE 0x02
Definition at line 79 of file tls.h.
PS_ARG_FAIL
#define PS_ARG_FAIL -6 /* Failure due to bad function param */
Definition at line 46 of file tls.h.
PS_EXPTMOD_WINSIZE
#define PS_EXPTMOD_WINSIZE 3
Definition at line 74 of file tls.h.
PS_FAILURE
#define PS_FAILURE -1
Definition at line 45 of file tls.h.
PS_FALSE
#define PS_FALSE 0
Definition at line 52 of file tls.h.
PS_LIMIT_FAIL
#define PS_LIMIT_FAIL -9 /* Failure on sanity/limit tests */
Definition at line 49 of file tls.h.
PS_MEM_FAIL
#define PS_MEM_FAIL -8 /* Failure to allocate requested memory */
Definition at line 48 of file tls.h.
PS_PLATFORM_FAIL
#define PS_PLATFORM_FAIL -7 /* Failure as a result of system call error */
Definition at line 47 of file tls.h.
PS_SUCCESS
#define PS_SUCCESS 0
Definition at line 44 of file tls.h.
PS_TRUE
#define PS_TRUE 1
Definition at line 51 of file tls.h.
psFree
#define psFree (p, pool) free(p)
Definition at line 92 of file tls.h.
psTraceCrypto
#define psTraceCrypto (msg) bb_simple_error_msg_and_die(msg)
Definition at line 93 of file tls.h.
PUBKEY_TYPE
#define PUBKEY_TYPE 0x01
Definition at line 78 of file tls.h.
USE_AES
#define USE_AES
Definition at line 18 of file tls.h.
Typedef Documentation
int16
typedef int16_t int16
Definition at line 69 of file tls.h.
int32
typedef int32_t int32
Definition at line 67 of file tls.h.
int64
typedef int64_t int64
Definition at line 65 of file tls.h.
uint16
typedef uint16_t uint16
Definition at line 68 of file tls.h.
uint32
typedef uint32_t uint32
Definition at line 66 of file tls.h.
uint64
typedef uint64_t uint64
Definition at line 64 of file tls.h.
Function Documentation
curve_P256_compute_pubkey_and_premaster()
void curve_P256_compute_pubkey_and_premaster (uint8_t * pubkey2x32, uint8_t * premaster32, const uint8_t * peerkey2x32)
Definition at line 1484 of file tls_sp_c32.c.
 {
     sp_digit privkey[8];
     dump_hex("peerkey2x32: %s\n", peerkey2x32, 64);
     sp_ecc_make_key_256(privkey, pubkey2x32);
     dump_hex("pubkey: %s\n", pubkey2x32, 32);
     dump_hex("        %s\n", pubkey2x32 + 32, 32);
     /* Combine our privkey and peer's public key to generate premaster */
     sp_ecc_secret_gen_256(privkey, /*x,y:*/peerkey2x32, premaster32);
     dump_hex("premaster: %s\n", premaster32, 32);
 }
References dump_hex, sp_ecc_make_key_256(), and sp_ecc_secret_gen_256().
Referenced by send_client_key_exchange(), and tls_run_copy_loop().
curve_P256_compute_pubkey_and_premaster_NEW()
void curve_P256_compute_pubkey_and_premaster_NEW (uint8_t * pubkey2x32, uint8_t * premaster32, const uint8_t * peerkey2x32)
Referenced by tls_run_copy_loop().
curve_x25519_compute_pubkey_and_premaster()
void curve_x25519_compute_pubkey_and_premaster (uint8_t * pubkey32, uint8_t * premaster32, const uint8_t * peerkey32)
Definition at line 612 of file tls_fe.c.
 {
     uint8_t privkey[CURVE25519_KEYSIZE]; //[32]
     /* Generate random private key, see RFC 7748 */
     tls_get_random(privkey, sizeof(privkey));
     privkey[0] &= 0xf8;
     privkey[CURVE25519_KEYSIZE-1] = ((privkey[CURVE25519_KEYSIZE-1] & 0x7f) | 0x40);
     /* Compute public key */
     curve25519(pubkey, privkey, NULL /* "use base point of x25519" */);
     /* Compute premaster using peer's public key */
     curve25519(premaster, privkey, peerkey32);
 }
References curve25519(), CURVE25519_KEYSIZE, NULL, and tls_get_random().
Referenced by send_client_key_exchange().
tls_get_random()
void tls_get_random (void * buf, unsigned len)
Definition at line 332 of file tls.c.
 {
     if (len != open_read_close("/dev/urandom", buf, len))
         xfunc_die();
 }
References buf, len, open_read_close(), and xfunc_die().
Referenced by curve_x25519_compute_pubkey_and_premaster(), send_client_hello_and_alloc_hsd(), send_client_key_exchange(), sp_256_ecc_gen_k_8(), and xwrite_encrypted_and_hmac_signed().
xorbuf()
void xorbuf (void * buf, const void * mask, unsigned count)
Definition at line 347 of file tls.c.
 {
     xorbuf3(dst, dst, src, count);
 }
References count, dst, src, and xorbuf3().
Referenced by aesgcm_GHASH(), and xwrite_encrypted_aesgcm().
xorbuf_aligned_AES_BLOCK_SIZE()
void xorbuf_aligned_AES_BLOCK_SIZE (void * buf, const void * mask)
Definition at line 352 of file tls.c.
 {
     unsigned long *d = dst;
     const unsigned long *s = src;
     d[0] ^= s[0];
 #if ULONG_MAX <= 0xffffffffffffffff
     d[1] ^= s[1];
  #if ULONG_MAX == 0xffffffff
     d[2] ^= s[2];
     d[3] ^= s[3];
  #endif
 #endif
 }
References dst, s, and src.
Referenced by aesgcm_GHASH(), GMULT(), and xwrite_encrypted_aesgcm().