Fennix: Userspace/apps/base/busybox/libbb/sysconf.c File Reference
sysconf.c File Reference
#include "libbb.h"
Functions
unsigned FAST_FUNC bb_arg_max (void)
unsigned FAST_FUNC bb_clk_tck (void)
Function Documentation
bb_arg_max()
unsigned FAST_FUNC bb_arg_max (void)
Definition at line 12 of file sysconf.c.
 {
     long r = sysconf(_SC_ARG_MAX);
     /* I've seen a version of uclibc which returned -1.
      * Guard about it, and also avoid insanely large values
      */
     if ((unsigned long)r > 64*1024*1024)
         r = 64*1024*1024;
     return r;
 }
References _SC_ARG_MAX, and sysconf().
Referenced by xargs_main().
bb_clk_tck()
unsigned FAST_FUNC bb_clk_tck (void)
Definition at line 27 of file sysconf.c.
 {
     return sysconf(_SC_CLK_TCK);
 }
References _SC_CLK_TCK, and sysconf().
Referenced by get_hz(), INET_setroute(), iostat_main(), mpstat_main(), and timescmd().