Fennix: Userspace/apps/base/busybox/util-linux/ionice.c File Reference
ionice.c File Reference
#include <sys/syscall.h>
#include <asm/unistd.h>
#include "libbb.h"
Macros
#define IOPRIO_CLASS_SHIFT 13
Enumerations
enum { IOPRIO_WHO_PROCESS = 1 , IOPRIO_WHO_PGRP , IOPRIO_WHO_USER }
enum { IOPRIO_CLASS_NONE , IOPRIO_CLASS_RT , IOPRIO_CLASS_BE , IOPRIO_CLASS_IDLE }
Functions
static int ioprio_set (int which, int who, int ioprio)
static int ioprio_get (int which, int who)
int ionice_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char to_prio[] ALIGN1 = "none\0realtime\0best-effort\0idle"
Macro Definition Documentation
IOPRIO_CLASS_SHIFT
#define IOPRIO_CLASS_SHIFT 13
Definition at line 58 of file ionice.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IOPRIO_WHO_PROCESS
IOPRIO_WHO_PGRP
IOPRIO_WHO_USER
Definition at line 43 of file ionice.c.
      {
     IOPRIO_WHO_PROCESS = 1,
     IOPRIO_WHO_PGRP,
     IOPRIO_WHO_USER
 };
anonymous enum
anonymous enum
Enumerator
IOPRIO_CLASS_NONE
IOPRIO_CLASS_RT
IOPRIO_CLASS_BE
IOPRIO_CLASS_IDLE
Definition at line 49 of file ionice.c.
      {
     IOPRIO_CLASS_NONE,
     IOPRIO_CLASS_RT,
     IOPRIO_CLASS_BE,
     IOPRIO_CLASS_IDLE
 };
Function Documentation
ionice_main()
int ionice_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 61 of file ionice.c.
 {
     /* Defaults */
     int ioclass = 0;
     int pri = 0;
     int pid = 0; /* affect own process */
     int opt;
     enum {
         OPT_n = 1 << 0,
         OPT_c = 1 << 1,
         OPT_p = 1 << 2,
         OPT_t = 1 << 3,
     };
     /* '+': stop at first non-option */
     /* numeric params for -n -c -p */
     opt = getopt32(argv, "+""n:+c:+p:+t", &pri, &ioclass, &pid);
     argv += optind;
     if (opt & OPT_c) {
         if (ioclass > 3)
             bb_error_msg_and_die("bad class %d", ioclass);
 // Do we need this (compat?)?
 //      if (ioclass == IOPRIO_CLASS_NONE)
 //          ioclass = IOPRIO_CLASS_BE;
 //      if (ioclass == IOPRIO_CLASS_IDLE) {
 //          //if (opt & OPT_n)
 //          //  bb_error_msg("ignoring priority for idle class");
 //          pri = 7;
 //      }
     }
     if (!(opt & (OPT_n|OPT_c))) {
         if (!(opt & OPT_p) && *argv)
             pid = xatoi_positive(*argv);
         pri = ioprio_get(IOPRIO_WHO_PROCESS, pid);
         if (pri == -1)
             bb_perror_msg_and_die("ioprio_%cet", 'g');
         ioclass = (pri >> IOPRIO_CLASS_SHIFT) & 0x3;
         pri &= 0xff;
         printf((ioclass == IOPRIO_CLASS_IDLE) ? "%s\n" : "%s: prio %d\n",
                 nth_string(to_prio, ioclass), pri);
     } else {
 //printf("pri=%d class=%d val=%x\n",
 //pri, ioclass, pri | (ioclass << IOPRIO_CLASS_SHIFT));
         pri |= (ioclass << IOPRIO_CLASS_SHIFT);
         if (ioprio_set(IOPRIO_WHO_PROCESS, pid, pri) == -1)
             if (!(opt & OPT_t))
                 bb_perror_msg_and_die("ioprio_%cet", 's');
         if (argv[0]) {
             BB_EXECVP_or_die(argv);
         }
     }
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), BB_EXECVP_or_die(), bb_perror_msg_and_die(), EXIT_SUCCESS, getopt32(), IOPRIO_CLASS_IDLE, IOPRIO_CLASS_SHIFT, ioprio_get(), ioprio_set(), IOPRIO_WHO_PROCESS, nth_string(), opt, OPT_c, OPT_n, OPT_p, OPT_t, optind, pid, printf, and xatoi_positive().
ioprio_get()
static int ioprio_get (int which, int who) static
Definition at line 38 of file ionice.c.
 {
     return syscall(SYS_ioprio_get, which, who);
 }
References syscall().
Referenced by ionice_main().
ioprio_set()
static int ioprio_set (int which, int who, int ioprio) static
Definition at line 33 of file ionice.c.
 {
     return syscall(SYS_ioprio_set, which, who, ioprio);
 }
References syscall().
Referenced by ionice_main().
Variable Documentation
ALIGN1
const char to_prio [] ALIGN1 = "none\0realtime\0best-effort\0idle" static
Definition at line 56 of file ionice.c.