Fennix Userspace: Userspace/mlibc/options/ansi/include/signal.h File Reference
signal.h File Reference
#include <abi-bits/signal.h>
#include <mlibc-config.h>
Macros
#define CLD_EXITED 1
#define CLD_KILLED 2
#define CLD_DUMPED 3
#define CLD_TRAPPED 4
#define CLD_STOPPED 5
#define CLD_CONTINUED 6
#define _NSIG NSIG
Typedefs
typedef int sig_atomic_t
typedef void(* __sighandler) (int)
Functions
__sighandler signal (int sig, __sighandler handler)
int raise (int sig)
Macro Definition Documentation
_NSIG
#define _NSIG NSIG
Definition at line 33 of file signal.h.
CLD_CONTINUED
#define CLD_CONTINUED 6
Definition at line 23 of file signal.h.
CLD_DUMPED
#define CLD_DUMPED 3
Definition at line 20 of file signal.h.
CLD_EXITED
#define CLD_EXITED 1
Definition at line 18 of file signal.h.
CLD_KILLED
#define CLD_KILLED 2
Definition at line 19 of file signal.h.
CLD_STOPPED
#define CLD_STOPPED 5
Definition at line 22 of file signal.h.
CLD_TRAPPED
#define CLD_TRAPPED 4
Definition at line 21 of file signal.h.
Typedef Documentation
__sighandler
typedef void(* __sighandler) (int)
Definition at line 16 of file signal.h.
sig_atomic_t
typedef int sig_atomic_t
Definition at line 13 of file signal.h.
Function Documentation
raise()
int raise (int sig)
Definition at line 23 of file signal-stubs.cpp.
                    {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getpid && mlibc::sys_kill, -1);
     pid_t pid = mlibc::sys_getpid();
     if (int e = mlibc::sys_kill(pid, sig)) {
         errno = e;
         return -1;
     }
     return 0;
 }
signal()
__sighandler signal (int sig, __sighandler handler)
Definition at line 289 of file signal.h.
References errno, handler(), MLIBC_CHECK_OR_ENOSYS, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SIG_ERR, and mlibc::sys_sigaction().
Referenced by _rl_handle_signal(), initialize_terminating_signals(), kill_pid(), main(), reset_terminating_signals(), rl_set_sighandler(), rl_sigaction(), sigalrm_handler(), anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler(), and sigint_sighandler().