Fennix: Userspace/mlibc/options/linux/generic/sys-epoll.cpp File Reference
sys-epoll.cpp File Reference
#include <errno.h>
#include <sys/epoll.h>
#include <bits/ensure.h>
#include <mlibc/linux-sysdeps.hpp>
#include <stddef.h>
Functions
int epoll_create (int)
int epoll_pwait (int epfd, struct epoll_event *evnts, int n, int timeout, const sigset_t *sigmask)
int epoll_create1 (int flags)
int epoll_ctl (int epfd, int mode, int fd, struct epoll_event *ev)
int epoll_wait (int epfd, struct epoll_event *evnts, int n, int timeout)
Function Documentation
epoll_create()
int epoll_create (int)
Definition at line 9 of file sys-epoll.cpp.
                       {
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_create, -1);
     if(int e = mlibc::sys_epoll_create(0, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_epoll_create().
epoll_create1()
int epoll_create1 (int flags)
Definition at line 30 of file sys-epoll.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_create, -1);
     if(int e = mlibc::sys_epoll_create(flags, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_epoll_create().
Referenced by mlibc::sys_pselect().
epoll_ctl()
int epoll_ctl (int epfd, int mode, int fd, struct epoll_event * ev)
Definition at line 40 of file sys-epoll.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_ctl, -1);
     if(int e = mlibc::sys_epoll_ctl(epfd, mode, fd, ev); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_epoll_ctl().
Referenced by mlibc::sys_pselect().
epoll_pwait()
int epoll_pwait (int epfd, struct epoll_event * evnts, int n, int timeout, const sigset_t * sigmask)
Definition at line 19 of file sys-epoll.cpp.
{
     int raised;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_pwait, -1);
     if(int e = mlibc::sys_epoll_pwait(epfd, evnts, n, timeout, sigmask, &raised)) {
         errno = e;
         return -1;
     }
     return raised;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, n, mlibc::sigmask, mlibc::sys_epoll_pwait(), and mlibc::timeout.
Referenced by mlibc::sys_pselect().
epoll_wait()
int epoll_wait (int epfd, struct epoll_event * evnts, int n, int timeout)
Definition at line 49 of file sys-epoll.cpp.
{
     int raised;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_pwait, -1);
     if(int e = mlibc::sys_epoll_pwait(epfd, evnts, n, timeout, NULL, &raised)) {
         errno = e;
         return -1;
     }
     return raised;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, n, NULL, mlibc::sys_epoll_pwait(), and mlibc::timeout.