Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_cheat.h File Reference
m_cheat.h File Reference
Data Structures
struct cheatseq_t
Macros
#define CHEAT(value, parameters) { value, sizeof(value) - 1, parameters, 0, 0, "" }
#define MAX_CHEAT_LEN 25
#define MAX_CHEAT_PARAMS 5
Functions
int cht_CheckCheat (cheatseq_t *cht, char key)
void cht_GetParam (cheatseq_t *cht, char *buffer)
Data Structure Documentation
cheatseq_t
struct cheatseq_t
Definition at line 35 of file m_cheat.h.
Data Fields
size_t chars_read
int param_chars_read
char parameter_buf[MAX_CHEAT_PARAMS]
int parameter_chars
char sequence[MAX_CHEAT_LEN]
size_t sequence_len
Macro Definition Documentation
CHEAT
#define CHEAT (value, parameters) { value, sizeof(value) - 1, parameters, 0, 0, "" }
Definition at line 29 of file m_cheat.h.
MAX_CHEAT_LEN
#define MAX_CHEAT_LEN 25
Definition at line 32 of file m_cheat.h.
MAX_CHEAT_PARAMS
#define MAX_CHEAT_PARAMS 5
Definition at line 33 of file m_cheat.h.
Function Documentation
cht_CheckCheat()
int cht_CheckCheat (cheatseq_t * cht, char key)
Definition at line 35 of file m_cheat.c.
 {
     // if we make a short sequence on a cheat with parameters, this
     // will not work in vanilla doom.  behave the same.
     if (cht->parameter_chars > 0 && strlen(cht->sequence) < cht->sequence_len)
         return false;
     if (cht->chars_read < strlen(cht->sequence))
     {
         // still reading characters from the cheat code
         // and verifying.  reset back to the beginning
         // if a key is wrong
         if (key == cht->sequence[cht->chars_read])
             ++cht->chars_read;
         else
             cht->chars_read = 0;
         cht->param_chars_read = 0;
     }
     else if (cht->param_chars_read < cht->parameter_chars)
     {
         // we have passed the end of the cheat sequence and are
         // entering parameters now
         cht->parameter_buf[cht->param_chars_read] = key;
         ++cht->param_chars_read;
     }
     if (cht->chars_read >= strlen(cht->sequence)
      && cht->param_chars_read >= cht->parameter_chars)
     {
         cht->chars_read = cht->param_chars_read = 0;
         return true;
     }
     // cheat not matched yet
     return false;
 }
References cheatseq_t::chars_read, cheatseq_t::param_chars_read, cheatseq_t::parameter_buf, cheatseq_t::parameter_chars, cheatseq_t::sequence, cheatseq_t::sequence_len, and strlen().
Referenced by AM_Responder(), and ST_Responder().
cht_GetParam()
void cht_GetParam (cheatseq_t * cht, char * buffer)
Definition at line 82 of file m_cheat.c.
 {
     memcpy(buffer, cht->parameter_buf, cht->parameter_chars);
 }
References memcpy(), cheatseq_t::parameter_buf, and cheatseq_t::parameter_chars.
Referenced by ST_Responder().