Fennix Userspace: Userspace/musl/src/include/resolv.h File Reference
resolv.h File Reference
#include "../../include/resolv.h"
Functions
hidden int __dn_expand (const unsigned char *, const unsigned char *, const unsigned char *, char *, int)
hidden int __res_mkquery (int, const char *, int, int, const unsigned char *, int, const unsigned char *, unsigned char *, int)
hidden int __res_send (const unsigned char *, int, unsigned char *, int)
hidden int __res_msend (int, const unsigned char *const *, const int *, unsigned char *const *, int *, int)
Function Documentation
__dn_expand()
hidden int __dn_expand (const unsigned char * base, const unsigned char * end, const unsigned char * src, char * dest, int space)
Definition at line 3 of file dn_expand.c.
 {
     const unsigned char *p = src;
     char *dend, *dbegin = dest;
     int len = -1, i, j;
     if (p==end || space <= 0) return -1;
     dend = dest + (space > 254 ? 254 : space);
     /* detect reference loop using an iteration counter */
     for (i=0; i < end-base; i+=2) {
         /* loop invariants: p<end, dest<dend */
         if (*p & 0xc0) {
             if (p+1==end) return -1;
             j = ((p[0] & 0x3f) << 8) | p[1];
             if (len < 0) len = p+2-src;
             if (j >= end-base) return -1;
             p = base+j;
         } else if (*p) {
             if (dest != dbegin) *dest++ = '.';
             j = *p++;
             if (j >= end-p || j >= dend-dest) return -1;
             while (j--) *dest++ = *p++;
         } else {
             *dest = 0;
             if (len < 0) len = p+1-src;
             return len;
         }
     }
     return -1;
 }
References base, end, i, j, p, and src.
Referenced by dns_parse_callback().
__res_mkquery()
hidden int __res_mkquery (int op, const char * dname, int class, int type, const unsigned char * data, int datalen, const unsigned char * newrr, unsigned char * buf, int buflen)
Definition at line 5 of file res_mkquery.c.
 {
     int id, i, j;
     unsigned char q[280];
     struct timespec ts;
     size_t l = strnlen(dname, 255);
     int n;
     if (l && dname[l-1]=='.') l--;
     if (l && dname[l-1]=='.') return -1;
     n = 17+l+!!l;
     if (l>253 || buflen<n || op>15u || class>255u || type>255u)
         return -1;
     /* Construct query template - ID will be filled later */
     memset(q, 0, n);
     q[2] = op*8 + 1;
     q[3] = 32; /* AD */
     q[5] = 1;
     memcpy((char *)q+13, dname, l);
     for (i=13; q[i]; i=j+1) {
         for (j=i; q[j] && q[j] != '.'; j++);
         if (j-i-1u > 62u) return -1;
         q[i-1] = j-i;
     }
     q[i+1] = type;
     q[i+3] = class;
     /* Make a reasonably unpredictable id */
     clock_gettime(CLOCK_REALTIME, &ts);
     id = ts.tv_nsec + ts.tv_nsec/65536UL & 0xffff;
     q[0] = id/256;
     q[1] = id;
     memcpy(buf, q, n);
     return n;
 }
References buf, i, j, l, memcpy(), memset(), n, strnlen(), timespec::tv_nsec, and type.
Referenced by getnameinfo(), name_from_dns(), and res_query().
__res_msend()
hidden int __res_msend (int nqueries, const unsigned char *const * queries, const int * qlens, unsigned char *const * answers, int * alens, int asize)
Definition at line 319 of file res_msend.c.
 {
     struct resolvconf conf;
     if (__get_resolv_conf(&conf, 0, 0) < 0) return -1;
     return __res_msend_rc(nqueries, queries, qlens, answers, alens, asize, &conf);
 }
References __get_resolv_conf(), and __res_msend_rc().
Referenced by __res_send().
__res_send()
hidden int __res_send (const unsigned char * msg, int msglen, unsigned char * answer, int anslen)
Definition at line 4 of file res_send.c.
 {
     int r;
     if (anslen < 512) {
         unsigned char buf[512];
         r = __res_send(msg, msglen, buf, sizeof buf);
         if (r >= 0) memcpy(answer, buf, r < anslen ? r : anslen);
         return r;
     }
     r = __res_msend(1, &msg, &msglen, &answer, &anslen, anslen);
     return r<0 || !anslen ? -1 : anslen;
 }
References __res_msend(), __res_send(), buf, and memcpy().
Referenced by __res_send(), getnameinfo(), and res_query().