Fennix Userspace: Userspace/apps/base/bash/xmalloc.c File Reference
xmalloc.c File Reference
#include "bashtypes.h"
#include <stdio.h>
#include "ansi_stdlib.h"
#include "error.h"
#include "bashintl.h"
Macros
#define PTR_T char *
#define FINDBRK()
Functions
static void allocerr (char *func, size_t bytes) const
PTR_T xmalloc (size_t bytes)
PTR_T xrealloc (PTR_T pointer, size_t bytes)
void xfree (PTR_T string)
Macro Definition Documentation
FINDBRK
#define FINDBRK ()
Definition at line 83 of file xmalloc.c.
PTR_T
#define PTR_T char *
Definition at line 46 of file xmalloc.c.
Function Documentation
allocerr()
static void allocerr (char * func, size_t bytes) const static
Definition at line 87 of file xmalloc.c.
 {
 #if HAVE_SBRK && defined (USING_BASH_MALLOC)
       allocated = findbrk ();
       fatal_error (_("%s: cannot allocate %lu bytes (%lu bytes allocated)"), func, (unsigned long)bytes, (unsigned long)allocated);
 #else
       fatal_error (_("%s: cannot allocate %lu bytes"), func, (unsigned long)bytes);
 #endif /* !HAVE_SBRK */
 }
References _, and fatal_error().
Referenced by xmalloc(), and xrealloc().
xfree()
void xfree (PTR_T string)
Definition at line 146 of file xmalloc.c.
 {
   if (string)
     free (string);
 }
References free.
xmalloc()
PTR_T xmalloc (size_t bytes)
Definition at line 103 of file xmalloc.c.
 {
   PTR_T temp;
 #if defined (DEBUG)
   if (bytes == 0)
     internal_warning("xmalloc: size argument is 0");
 #endif
   FINDBRK();
   temp = malloc (bytes);
   if (temp == 0)
     allocerr ("xmalloc", bytes);
   return (temp);
 }
References allocerr(), FINDBRK, internal_warning(), malloc, and PTR_T.
xrealloc()
PTR_T xrealloc (PTR_T pointer, size_t bytes)
Definition at line 123 of file xmalloc.c.
 {
   PTR_T temp;
 #if defined (DEBUG)
   if (bytes == 0)
     internal_warning("xrealloc: size argument is 0");
 #endif
   FINDBRK();
   temp = pointer ? realloc (pointer, bytes) : malloc (bytes);
   if (temp == 0)
     allocerr ("xrealloc", bytes);
   return (temp);
 }
References allocerr(), FINDBRK, internal_warning(), malloc, PTR_T, and realloc.