Fennix: Loader Class Reference
Loader Class Reference
#include <linker.hpp>
Public Member Functions
Loader (Scope *scope, SharedObject *mainExecutable, bool is_initial_link, uint64_t rts)
void linkObjects (SharedObject *root)
void initObjects ()
Private Member Functions
void _buildLinkBfs (SharedObject *root)
void _buildTlsMaps ()
void _processStaticRelocations (SharedObject *object)
void _processLazyRelocations (SharedObject *object)
void _processRela (SharedObject *object, Elf64_Rela *reloc)
void _scheduleInit (SharedObject *object)
Private Attributes
SharedObject * _mainExecutable
Scope * _loadScope
bool _isInitialLink
uint64_t _linkRts
frg::vector< SharedObject *, MemoryAllocator > _linkBfs
frg::vector< SharedObject *, MemoryAllocator > _initQueue
Detailed Description
Definition at line 274 of file linker.hpp.
Constructor & Destructor Documentation
Loader()
Loader::Loader (Scope * scope, SharedObject * mainExecutable, bool is_initial_link, uint64_t rts)
Definition at line 1177 of file linker.cpp.
 : _mainExecutable{mainExecutable}, _loadScope{scope}, _isInitialLink{is_initial_link},
         _linkRts{rts}, _linkBfs{getAllocator()}, _initQueue{getAllocator()} { }
Member Function Documentation
_buildLinkBfs()
void Loader::_buildLinkBfs (SharedObject * root) private
Definition at line 1181 of file linker.cpp.
{
     __ensure(_linkBfs.size() == 0);
     struct Token {};
     using Set = frg::hash_map<SharedObject *, Token,
             frg::hash<SharedObject *>, MemoryAllocator>;
     Set set{frg::hash<SharedObject *>{}, getAllocator()};
     _linkBfs.push(root);
     // Loop over indices (not iterators) here: We are adding elements in the loop!
     for(size_t i = 0; i < _linkBfs.size(); i++) {
         auto current = _linkBfs[i];
         // At this point the object is loaded and we can fill in its debug struct,
         // the linked list fields will be filled later.
         current->linkMap.base = current->baseAddress;
         current->linkMap.name = current->path.data();
         current->linkMap.dynv = current->dynamic;
         __ensure((current->tlsAlignment & (current->tlsAlignment - 1)) == 0);
         if (_isInitialLink && current->tlsAlignment > tlsMaxAlignment) {
             tlsMaxAlignment = current->tlsAlignment;
         }
         for (auto dep : current->dependencies) {
             if (!set.get(dep)) {
                 set.insert(dep, Token{});
                 _linkBfs.push(dep);
             }
         }
     }
 }
References __ensure, _isInitialLink, _linkBfs, getAllocator(), i, and tlsMaxAlignment.
Referenced by linkObjects().
_buildTlsMaps()
void Loader::_buildTlsMaps () private
Definition at line 1282 of file linker.cpp.
{
     if(_isInitialLink) {
         __ensure(runtimeTlsMap->initialPtr == 0);
         __ensure(runtimeTlsMap->initialLimit == 0);
         __ensure(!_linkBfs.empty());
         __ensure(_linkBfs.front()->isMainObject);
         for(auto object : _linkBfs) {
             __ensure(object->tlsModel == TlsModel::null);
             if(object->tlsSegmentSize == 0)
                 continue;
             // Allocate an index for the object.
             object->tlsIndex = runtimeTlsMap->indices.size();
             runtimeTlsMap->indices.push_back(object);
             object->tlsModel = TlsModel::initial;
             if constexpr (tlsAboveTp) {
                 // As per the comment in allocateTcb(), we may simply add sizeof(Tcb) to
                 // reach the TLS data.
                 object->tlsOffset = runtimeTlsMap->initialPtr + sizeof(Tcb);
                 runtimeTlsMap->initialPtr += object->tlsSegmentSize;
                 size_t misalign = runtimeTlsMap->initialPtr & (object->tlsAlignment - 1);
                 if(misalign)
                     runtimeTlsMap->initialPtr += object->tlsAlignment - misalign;
             } else {
                 runtimeTlsMap->initialPtr += object->tlsSegmentSize;
                 size_t misalign = runtimeTlsMap->initialPtr & (object->tlsAlignment - 1);
                 if(misalign)
                     runtimeTlsMap->initialPtr += object->tlsAlignment - misalign;
                 object->tlsOffset = -runtimeTlsMap->initialPtr;
             }
             if(verbose)
                 mlibc::infoLogger() << "rtdl: TLS of " << object->name
                         << " mapped to 0x" << frg::hex_fmt{object->tlsOffset}
                         << ", size: " << object->tlsSegmentSize
                         << ", alignment: " << object->tlsAlignment << frg::endlog;
         }
         // Reserve some additional space for future libraries.
         runtimeTlsMap->initialLimit = runtimeTlsMap->initialPtr + 64;
     }else{
         for(auto object : _linkBfs) {
             if(object->tlsModel != TlsModel::null)
                 continue;
             if(object->tlsSegmentSize == 0)
                 continue;
             // Allocate an index for the object.
             object->tlsIndex = runtimeTlsMap->indices.size();
             runtimeTlsMap->indices.push_back(object);
             // There are some libraries (e.g. Mesa) that require static TLS even though
             // they expect to be dynamically loaded.
             if(object->haveStaticTls) {
                 auto ptr = runtimeTlsMap->initialPtr + object->tlsSegmentSize;
                 size_t misalign = ptr & (object->tlsAlignment - 1);
                 if(misalign)
                     ptr += object->tlsAlignment - misalign;
                 if(ptr > runtimeTlsMap->initialLimit)
                     mlibc::panicLogger() << "rtdl: Static TLS space exhausted while while"
                             " allocating TLS for " << object->name << frg::endlog;
                 object->tlsModel = TlsModel::initial;
                 if constexpr (tlsAboveTp) {
                     size_t tcbSize = ((sizeof(Tcb) + tlsMaxAlignment - 1) & ~(tlsMaxAlignment - 1));
                     object->tlsOffset = runtimeTlsMap->initialPtr + tcbSize;
                     runtimeTlsMap->initialPtr = ptr;
                 } else {
                     runtimeTlsMap->initialPtr = ptr;
                     object->tlsOffset = -runtimeTlsMap->initialPtr;
                 }
                 if(verbose)
                     mlibc::infoLogger() << "rtdl: TLS of " << object->name
                             << " mapped to 0x" << frg::hex_fmt{object->tlsOffset}
                             << ", size: " << object->tlsSegmentSize
                             << ", alignment: " << object->tlsAlignment << frg::endlog;
             }else{
                 object->tlsModel = TlsModel::dynamic;
             }
         }
     }
 }
References __ensure, _isInitialLink, _linkBfs, dynamic, mlibc::infoLogger, initial, null, mlibc::panicLogger, runtimeTlsMap, tlsMaxAlignment, and verbose.
Referenced by linkObjects().
_processLazyRelocations()
void Loader::_processLazyRelocations (SharedObject * object) private
Definition at line 1663 of file linker.cpp.
{
     if(object->globalOffsetTable == nullptr) {
         __ensure(object->lazyRelocTableOffset == 0);
         return;
     }
     object->globalOffsetTable[1] = object;
     object->globalOffsetTable[2] = (void *)&pltRelocateStub;
     if(!object->lazyTableSize)
         return;
     // adjust the addresses of JUMP_SLOT relocations
     __ensure(object->lazyExplicitAddend);
     for(size_t offset = 0; offset < object->lazyTableSize; offset += sizeof(Elf64_Rela)) {
         auto reloc = (Elf64_Rela *)(object->baseAddress + object->lazyRelocTableOffset + offset);
         Elf64_Xword type = ELF64_R_TYPE(reloc->r_info);
         Elf64_Xword symbol_index = ELF64_R_SYM(reloc->r_info);
         uintptr_t rel_addr = object->baseAddress + reloc->r_offset;
         switch (type) {
 #if defined(__x86_64__)
         case R_X86_64_JUMP_SLOT:
 #elif defined(__aarch64__)
         case R_AARCH64_JUMP_SLOT:
 #elif defined(__riscv)
         case R_RISCV_JUMP_SLOT:
 #endif
             if(eagerBinding) {
                 auto symbol = (Elf64_Sym *)(object->baseAddress + object->symbolTableOffset
                         + symbol_index * sizeof(Elf64_Sym));
                 ObjectSymbol r(object, symbol);
                 auto p = Scope::resolveGlobalOrLocal(*globalScope, object->localScope, r.getString(), object->objectRts, 0);
                 if(!p) {
                     if(ELF64_ST_BIND(symbol->st_info) != STB_WEAK)
                         mlibc::panicLogger() << "rtdl: Unresolved JUMP_SLOT symbol "
                                 << r.getString() << " in object " << object->name << frg::endlog;
                     if(verbose)
                         mlibc::infoLogger() << "rtdl: Unresolved weak JUMP_SLOT symbol "
                             << r.getString() << " in object " << object->name << frg::endlog;
                     *((uint64_t *)rel_addr) = 0;
                 }else{
                     *((uint64_t *)rel_addr) = p->virtualAddress();
                 }
             }else{
                 *((uint64_t *)rel_addr) += object->baseAddress;
             }
             break;
 #if defined(__x86_64__)
         case R_X86_64_IRELATIVE: {
             auto ptr = object->baseAddress + reloc->r_addend;
             auto target = reinterpret_cast<Elf64_Addr (*)(void)>(ptr)();
             *((uint64_t *)rel_addr) = target;
             break;
         }
 #endif
 // TODO: TLSDESC relocations aren't aarch64 specific
 #if defined(__aarch64__)
         case R_AARCH64_TLSDESC: {
             size_t symValue = 0;
             SharedObject *target = nullptr;
             if (symbol_index) {
                 auto symbol = (Elf64_Sym *)(object->baseAddress + object->symbolTableOffset
                         + symbol_index * sizeof(Elf64_Sym));
                 ObjectSymbol r(object, symbol);
                 auto p = Scope::resolveGlobalOrLocal(*globalScope, object->localScope, r.getString(), object->objectRts, 0);
                 if (!p) {
                     __ensure(ELF64_ST_BIND(symbol->st_info) != STB_WEAK);
                     mlibc::panicLogger() << "rtdl: Unresolved TLSDESC for symbol "
                         << r.getString() << " in object " << object->name << frg::endlog;
                 } else {
                     target = p->object();
                     if (p->symbol())
                         symValue = p->symbol()->st_value;
                 }
             } else {
                 target = object;
             }
             __ensure(target);
             if (target->tlsModel == TlsModel::initial) {
                 ((uint64_t *)rel_addr)[0] = reinterpret_cast<uintptr_t>(&__mlibcTlsdescStatic);
                 ((uint64_t *)rel_addr)[1] = symValue + target->tlsOffset + reloc->r_addend;
             } else {
                 struct TlsdescData {
                     uintptr_t tlsIndex;
                     uintptr_t addend;
                 };
                 // Access DTV for object to force the entry to be allocated and initialized
                 accessDtv(target);
                 __ensure(target->tlsIndex < mlibc::get_current_tcb()->dtvSize);
                 // TODO: We should free this when the DSO gets destroyed
                 auto data = frg::construct<TlsdescData>(getAllocator());
                 data->tlsIndex = target->tlsIndex;
                 data->addend = symValue + reloc->r_addend;
                 ((uint64_t *)rel_addr)[0] = reinterpret_cast<uintptr_t>(&__mlibcTlsdescDynamic);
                 ((uint64_t *)rel_addr)[1] = reinterpret_cast<uintptr_t>(data);
             }
         } break;
 #endif
         default:
             mlibc::panicLogger() << "unimplemented lazy relocation type " << type << frg::endlog;
             break;
         }
     }
 }
References __ensure, accessDtv(), SharedObject::baseAddress, Tcb::dtvSize, eagerBinding, ELF64_R_SYM(), ELF64_R_TYPE(), ELF64_ST_BIND, mlibc::get_current_tcb(), getAllocator(), SharedObject::globalOffsetTable, globalScope, mlibc::infoLogger, initial, SharedObject::lazyExplicitAddend, SharedObject::lazyRelocTableOffset, SharedObject::lazyTableSize, SharedObject::localScope, SharedObject::objectRts, offset, p, mlibc::panicLogger, pltRelocateStub(), r, R_AARCH64_JUMP_SLOT, R_AARCH64_TLSDESC, R_RISCV_JUMP_SLOT, R_X86_64_IRELATIVE, R_X86_64_JUMP_SLOT, Scope::resolveGlobalOrLocal(), STB_WEAK, SharedObject::symbolTableOffset, SharedObject::tlsIndex, SharedObject::tlsModel, SharedObject::tlsOffset, type, and verbose.
Referenced by linkObjects().
_processRela()
void Loader::_processRela (SharedObject * object, Elf64_Rela * reloc) private
Definition at line 1422 of file linker.cpp.
{
     Elf64_Xword type = ELF64_R_TYPE(reloc->r_info);
     Elf64_Xword symbol_index = ELF64_R_SYM(reloc->r_info);
     // copy relocations have to be performed after all other relocations
 #if defined(__x86_64__)
     if(type == R_X86_64_COPY)
         return;
 #elif defined(__aarch64__)
     if(type == R_AARCH64_COPY)
         return;
 #elif defined(__riscv)
     if(type == R_RISCV_COPY)
         return;
 #endif
     // resolve the symbol if there is a symbol
     frg::optional<ObjectSymbol> p;
     if(symbol_index) {
         auto symbol = (Elf64_Sym *)(object->baseAddress + object->symbolTableOffset
                 + symbol_index * sizeof(Elf64_Sym));
         ObjectSymbol r(object, symbol);
         p = Scope::resolveGlobalOrLocal(*globalScope, object->localScope,
                 r.getString(), object->objectRts, 0);
         if(!p) {
             if(ELF64_ST_BIND(symbol->st_info) != STB_WEAK)
                 mlibc::panicLogger() << "Unresolved load-time symbol "
                         << r.getString() << " in object " << object->name << frg::endlog;
             if(verbose)
                 mlibc::infoLogger() << "rtdl: Unresolved weak load-time symbol "
                         << r.getString() << " in object " << object->name << frg::endlog;
         }
     }
     uintptr_t rel_addr = object->baseAddress + reloc->r_offset;
     switch(type) {
 #if defined(__x86_64__)
     case R_X86_64_64: {
         __ensure(symbol_index);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr + reloc->r_addend;
     } break;
     case R_X86_64_GLOB_DAT: {
         __ensure(symbol_index);
         __ensure(!reloc->r_addend);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr;
     } break;
     case R_X86_64_JUMP_SLOT: {
         __ensure(symbol_index);
         __ensure(!reloc->r_addend);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr;
     } break;
     case R_X86_64_RELATIVE: {
         __ensure(!symbol_index);
         *((uint64_t *)rel_addr) = object->baseAddress + reloc->r_addend;
     } break;
     // DTPMOD and DTPOFF are dynamic TLS relocations (for __tls_get_addr()).
     // TPOFF is a relocation to the initial TLS model.
     case R_X86_64_DTPMOD64: {
         __ensure(!reloc->r_addend);
         if(symbol_index) {
             __ensure(p);
             *((uint64_t *)rel_addr) = (uint64_t)p->object();
         }else{
             // TODO: is this behaviour actually documented anywhere?
             if(stillSlightlyVerbose)
                 mlibc::infoLogger() << "rtdl: Warning: DTPOFF64 with no symbol"
                         " in object " << object->name << frg::endlog;
             *((uint64_t *)rel_addr) = (uint64_t)object;
         }
     } break;
     case R_X86_64_DTPOFF64: {
         __ensure(p);
         __ensure(!reloc->r_addend);
         *((uint64_t *)rel_addr) = p->symbol()->st_value;
     } break;
     case R_X86_64_TPOFF64: {
         if(symbol_index) {
             __ensure(p);
             __ensure(!reloc->r_addend);
             if(p->object()->tlsModel != TlsModel::initial)
                 mlibc::panicLogger() << "rtdl: In object " << object->name
                         << ": Static TLS relocation to symbol " << p->getString()
                         << " in dynamically loaded object "
                         << p->object()->name << frg::endlog;
             *((uint64_t *)rel_addr) = p->object()->tlsOffset + p->symbol()->st_value;
         }else{
             if(stillSlightlyVerbose)
                 mlibc::infoLogger() << "rtdl: Warning: TPOFF64 with no symbol"
                         " in object " << object->name << frg::endlog;
             if(object->tlsModel != TlsModel::initial)
                 mlibc::panicLogger() << "rtdl: In object " << object->name
                         << ": Static TLS relocation to dynamically loaded object "
                         << object->name << frg::endlog;
             *((uint64_t *)rel_addr) = object->tlsOffset + reloc->r_addend;
         }
     } break;
 #elif defined(__aarch64__)
     case R_AARCH64_ABS64: {
         __ensure(symbol_index);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr + reloc->r_addend;
     } break;
     case R_AARCH64_GLOB_DAT: {
         __ensure(symbol_index);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr + reloc->r_addend;
     } break;
     case R_AARCH64_RELATIVE: {
         __ensure(!symbol_index);
         *((uint64_t *)rel_addr) = object->baseAddress + reloc->r_addend;
     } break;
     case R_AARCH64_TLS_TPREL: {
         if(symbol_index) {
             __ensure(p);
             __ensure(!reloc->r_addend);
             if(p->object()->tlsModel != TlsModel::initial)
                 mlibc::panicLogger() << "rtdl: In object " << object->name
                         << ": Static TLS relocation to dynamically loaded object "
                         << p->object()->name << frg::endlog;
             *((uint64_t *)rel_addr) = p->object()->tlsOffset + p->symbol()->st_value;
         }else{
             __ensure(!reloc->r_addend);
             if(stillSlightlyVerbose)
                 mlibc::infoLogger() << "rtdl: Warning: TLS_TPREL with no symbol"
                         " in object " << object->name << frg::endlog;
             if(object->tlsModel != TlsModel::initial)
                 mlibc::panicLogger() << "rtdl: In object " << object->name
                         << ": Static TLS relocation to dynamically loaded object "
                         << object->name << frg::endlog;
             *((uint64_t *)rel_addr) = object->tlsOffset;
         }
     } break;
 #elif defined(__riscv)
     case R_RISCV_64: {
         __ensure(symbol_index);
         __ensure(p);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr + reloc->r_addend;
     } break;
     case R_RISCV_JUMP_SLOT: {
         __ensure(symbol_index);
         __ensure(p);
         __ensure(!reloc->r_addend);
         uint64_t symbol_addr = p ? p->virtualAddress() : 0;
         *((uint64_t *)rel_addr) = symbol_addr;
     } break;
     case R_RISCV_RELATIVE: {
         __ensure(!symbol_index);
         *((uint64_t *)rel_addr) = object->baseAddress + reloc->r_addend;
     } break;
     case R_RISCV_TLS_DTPMOD64: {
         __ensure(!reloc->r_addend);
         if(symbol_index) {
             __ensure(p);
             *((uint64_t *)rel_addr) = (uint64_t)p->object();
         }else{
             if(stillSlightlyVerbose)
                 mlibc::infoLogger() << "rtdl: Warning: TLS_DTPMOD64 with no symbol"
                         " in object " << object->name << frg::endlog;
             *((uint64_t *)rel_addr) = (uint64_t)object;
         }
     } break;
     case R_RISCV_TLS_DTPREL64: {
         __ensure(symbol_index);
         __ensure(p);
         *((uint64_t *)rel_addr) = p->symbol()->st_value + reloc->r_addend - TLS_DTV_OFFSET;
     } break;
     case R_RISCV_TLS_TPREL64: {
         // Note: this assumes that tcb_ptr + sizeof(Tcb) == tp.
         if(symbol_index) {
             __ensure(p);
             __ensure(!reloc->r_addend);
             if(p->object()->tlsModel != TlsModel::initial)
                 mlibc::panicLogger() << "rtdl: In object " << object->name
                         << ": Static TLS relocation to dynamically loaded object "
                         << p->object()->name << frg::endlog;
             *((uint64_t *)rel_addr) = p->object()->tlsOffset - sizeof(Tcb) + p->symbol()->st_value;
         }else{
             __ensure(!reloc->r_addend);
             if(stillSlightlyVerbose)
                 mlibc::infoLogger() << "rtdl: Warning: TLS_TPREL64 with no symbol"
                         " in object " << object->name << frg::endlog;
             if(object->tlsModel != TlsModel::initial)
                 mlibc::panicLogger() << "rtdl: In object " << object->name
                         << ": Static TLS relocation to dynamically loaded object "
                         << object->name << frg::endlog;
             *((uint64_t *)rel_addr) = object->tlsOffset - sizeof(Tcb);
         }
     } break;
     case R_RISCV_NONE:
         // Work around https://sourceware.org/bugzilla/show_bug.cgi?id=24673.
         break;
 #endif
     default:
         mlibc::panicLogger() << "Unexpected relocation type "
                 << (void *)type << frg::endlog;
     }
 }
References __ensure, SharedObject::baseAddress, ELF64_R_SYM(), ELF64_R_TYPE(), ELF64_ST_BIND, globalScope, mlibc::infoLogger, initial, SharedObject::localScope, SharedObject::objectRts, p, mlibc::panicLogger, r, R_AARCH64_ABS64, R_AARCH64_COPY, R_AARCH64_GLOB_DAT, R_AARCH64_RELATIVE, R_AARCH64_TLS_TPREL, Elf64_Rela::r_addend, Elf64_Rela::r_info, Elf64_Rela::r_offset, R_RISCV_64, R_RISCV_COPY, R_RISCV_JUMP_SLOT, R_RISCV_NONE, R_RISCV_RELATIVE, R_RISCV_TLS_DTPMOD64, R_RISCV_TLS_DTPREL64, R_RISCV_TLS_TPREL64, R_X86_64_64, R_X86_64_COPY, R_X86_64_DTPMOD64, R_X86_64_DTPOFF64, R_X86_64_GLOB_DAT, R_X86_64_JUMP_SLOT, R_X86_64_RELATIVE, R_X86_64_TPOFF64, Scope::resolveGlobalOrLocal(), STB_WEAK, stillSlightlyVerbose, SharedObject::symbolTableOffset, SharedObject::tlsModel, type, and verbose.
Referenced by _processStaticRelocations().
_processStaticRelocations()
void Loader::_processStaticRelocations (SharedObject * object) private
Definition at line 1627 of file linker.cpp.
{
     frg::optional<uintptr_t> rela_offset;
     frg::optional<size_t> rela_length;
     for(size_t i = 0; object->dynamic[i].d_tag != DT_NULL; i++) {
         Elf64_Dyn *dynamic = &object->dynamic[i];
         switch(dynamic->d_tag) {
         case DT_RELA:
             rela_offset = dynamic->d_un.d_ptr;
             break;
         case DT_RELASZ:
             rela_length = dynamic->d_un.d_val;
             break;
         case DT_RELAENT:
             __ensure(dynamic->d_un.d_val == sizeof(Elf64_Rela));
             break;
         }
     }
     if(rela_offset && rela_length) {
         for(size_t offset = 0; offset < *rela_length; offset += sizeof(Elf64_Rela)) {
             auto reloc = (Elf64_Rela *)(object->baseAddress + *rela_offset + offset);
             _processRela(object, reloc);
         }
     }else{
         __ensure(!rela_offset && !rela_length);
     }
 }
References __ensure, _processRela(), SharedObject::baseAddress, DT_NULL, DT_RELA, DT_RELAENT, DT_RELASZ, dynamic, i, and offset.
Referenced by linkObjects().
_scheduleInit()
void Loader::_scheduleInit (SharedObject * object) private
Definition at line 1405 of file linker.cpp.
{
     // Here we detect cyclic dependencies.
     __ensure(!object->onInitStack);
     object->onInitStack = true;
     __ensure(!object->scheduledForInit);
     object->scheduledForInit = true;
     for(size_t i = 0; i < object->dependencies.size(); i++) {
         if(!object->dependencies[i]->scheduledForInit)
             _scheduleInit(object->dependencies[i]);
     }
     _initQueue.push(object);
     object->onInitStack = false;
 }
References __ensure, _initQueue, SharedObject::dependencies, i, SharedObject::onInitStack, and SharedObject::scheduledForInit.
Referenced by initObjects().
initObjects()
void Loader::initObjects ()
Definition at line 1377 of file linker.cpp.
{
     initTlsObjects(mlibc::get_current_tcb(), _linkBfs, true);
     if (_mainExecutable && _mainExecutable->preInitArray) {
         if (verbose)
             mlibc::infoLogger() << "rtdl: Running DT_PREINIT_ARRAY functions" << frg::endlog;
         __ensure(_mainExecutable->isMainObject);
         __ensure(!_mainExecutable->wasInitialized);
         __ensure((_mainExecutable->preInitArraySize % sizeof(InitFuncPtr)) == 0);
         for(size_t i = 0; i < _mainExecutable->preInitArraySize / sizeof(InitFuncPtr); i++)
             _mainExecutable->preInitArray[i]();
     }
     // Convert the breadth-first representation to a depth-first post-order representation,
     // so that every object is initialized *after* its dependencies.
     for(auto object : _linkBfs) {
         if(!object->scheduledForInit)
             _scheduleInit(object);
     }
     for(auto object : _initQueue) {
         if(!object->wasInitialized)
             doInitialize(object);
     }
 }
References __ensure, _initQueue, _linkBfs, _mainExecutable, _scheduleInit(), doInitialize(), mlibc::get_current_tcb(), i, mlibc::infoLogger, initTlsObjects(), SharedObject::isMainObject, SharedObject::preInitArray, SharedObject::preInitArraySize, verbose, and SharedObject::wasInitialized.
linkObjects()
void Loader::linkObjects (SharedObject * root)
Definition at line 1215 of file linker.cpp.
{
     _buildLinkBfs(root);
     _buildTlsMaps();
     // Promote objects to the desired scope.
     for(auto object : _linkBfs) {
         if (object->globalRts == 0 && _loadScope->isGlobal)
             object->globalRts = _linkRts;
         _loadScope->appendObject(object);
     }
     // Process regular relocations.
     for(auto object : _linkBfs) {
         // Some objects have already been linked before.
         if(object->objectRts < _linkRts)
             continue;
         if(object->dynamic == nullptr)
             continue;
         if(verbose)
             mlibc::infoLogger() << "rtdl: Linking " << object->name << frg::endlog;
         __ensure(!object->wasLinked);
         // TODO: Support this.
         if(object->symbolicResolution)
             mlibc::infoLogger() << "\e[31mrtdl: DT_SYMBOLIC is not implemented correctly!\e[39m"
                     << frg::endlog;
         _processStaticRelocations(object);
         _processLazyRelocations(object);
     }
     // Process copy relocations.
     for(auto object : _linkBfs) {
         if(!object->isMainObject)
             continue;
         // Some objects have already been linked before.
         if(object->objectRts < _linkRts)
             continue;
         if(object->dynamic == nullptr)
             continue;
         processCopyRelocations(object);
     }
     for(auto object : _linkBfs) {
         object->wasLinked = true;
         if(object->inLinkMap)
             continue;
         auto linkMap = reinterpret_cast<LinkMap*>(globalDebugInterface.head);
         object->linkMap.prev = linkMap;
         object->linkMap.next = linkMap->next;
         if(linkMap->next)
             linkMap->next->prev = &(object->linkMap);
         linkMap->next = &(object->linkMap);
         object->inLinkMap = true;
     }
 }
References __ensure, _buildLinkBfs(), _buildTlsMaps(), _linkBfs, _linkRts, _loadScope, _processLazyRelocations(), _processStaticRelocations(), Scope::appendObject(), globalDebugInterface, DebugInterface::head, mlibc::infoLogger, Scope::isGlobal, LinkMap::next, LinkMap::prev, processCopyRelocations(), and verbose.
Field Documentation
_initQueue
frg::vector<SharedObject *, MemoryAllocator> Loader::_initQueue private
Definition at line 303 of file linker.hpp.
Referenced by _scheduleInit(), and initObjects().
_isInitialLink
bool Loader::_isInitialLink private
Definition at line 298 of file linker.hpp.
Referenced by _buildLinkBfs(), and _buildTlsMaps().
_linkBfs
frg::vector<SharedObject *, MemoryAllocator> Loader::_linkBfs private
Definition at line 301 of file linker.hpp.
Referenced by _buildLinkBfs(), _buildTlsMaps(), initObjects(), and linkObjects().
_linkRts
uint64_t Loader::_linkRts private
Definition at line 299 of file linker.hpp.
Referenced by linkObjects().
_loadScope
Scope* Loader::_loadScope private
Definition at line 297 of file linker.hpp.
Referenced by linkObjects().
_mainExecutable
SharedObject* Loader::_mainExecutable private
Definition at line 296 of file linker.hpp.
Referenced by initObjects().
The documentation for this class was generated from the following files:
Userspace/mlibc/options/rtdl/generic/linker.hpp
Userspace/mlibc/options/rtdl/generic/linker.cpp