Fennix: Userspace/apps/base/busybox/klibc-utils/resume.c File Reference
resume.c File Reference
#include "libbb.h"
Functions
static dev_t name_to_dev_t (const char *devname)
int resume_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
name_to_dev_t()
static dev_t name_to_dev_t (const char * devname) static
Definition at line 34 of file resume.c.
 {
     char devfile[sizeof(int)*3 * 2 + 4];
     char *sysname;
     unsigned major_num, minor_num;
     struct stat st;
     int r;
     if (strncmp(devname, "/dev/", 5) != 0) {
         char *cptr;
         cptr = strchr(devname, ':');
         if (cptr) {
             /* Colon-separated decimal device number? */
             *cptr = '\0';
             major_num = bb_strtou(devname, NULL, 10);
             if (!errno)
                 minor_num = bb_strtou(cptr + 1, NULL, 10);
             *cptr = ':';
             if (!errno)
                 return makedev(major_num, minor_num);
         } else {
             /* Hexadecimal device number? */
             dev_t res = (dev_t) bb_strtoul(devname, NULL, 16);
             if (!errno)
                 return res;
         }
         devname = xasprintf("/dev/%s", devname);
     }
     /* Now devname is always "/dev/FOO" */
     if (stat(devname, &st) == 0 && S_ISBLK(st.st_mode))
         return st.st_rdev;
     /* Full blockdevs as well as partitions may be visible
      * in /sys/class/block/ even if /dev is not populated.
      */
     sysname = xasprintf("/sys/class/block/%s/dev", devname + 5);
     r = open_read_close(sysname, devfile, sizeof(devfile) - 1);
     //free(sysname);
     if (r > 0) {
         devfile[r] = '\0';
         if (sscanf(devfile, "%u:%u", &major_num, &minor_num) == 2) {
             return makedev(major_num, minor_num);
         }
     }
     return (dev_t) 0;
 }
References bb_strtou(), bb_strtoul(), dev_t, errno, makedev, NULL, open_read_close(), S_ISBLK, sscanf(), stat(), strchr(), strncmp(), and xasprintf().
Referenced by resume_main().
resume_main()
int resume_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 91 of file resume.c.
 {
     unsigned long long ofs;
     dev_t resume_device;
     char *s;
     int fd;
     argv++;
     if (!argv[0])
         bb_show_usage();
     resume_device = name_to_dev_t(argv[0]);
     if (major(resume_device) == 0) {
         bb_error_msg_and_die("invalid resume device: %s", argv[0]);
     }
     ofs = (argv[1] ? xstrtoull(argv[1], 0) : 0);
     /* Old kernels have no /sys/power/resume_offset, set it only if necessary */
     if (ofs != 0) {
         fd = xopen("/sys/power/resume_offset", O_WRONLY);
         s = xasprintf("%llu", ofs);
         xwrite_str(fd, s);
     }
     fd = xopen("/sys/power/resume", O_WRONLY);
     s = xasprintf("%u:%u", major(resume_device), minor(resume_device));
     xwrite_str(fd, s);
     /* if write() returns, resume did not succeed */
     return EXIT_FAILURE; /* klibc-utils exits -1 aka 255 */
 }
References argv, bb_error_msg_and_die(), bb_show_usage(), dev_t, EXIT_FAILURE, fd, major, minor, name_to_dev_t(), O_WRONLY, s, xasprintf(), xopen(), and xwrite_str().