Fennix: Userspace/musl/src/malloc/lite_malloc.c File Reference
lite_malloc.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include <limits.h>
#include <errno.h>
#include <sys/mman.h>
#include "libc.h"
#include "lock.h"
#include "syscall.h"
#include "fork_impl.h"
Macros
#define ALIGN 16
Functions
static int traverses_stack_p (uintptr_t old, uintptr_t new)
static void * __simple_malloc (size_t n)
weak_alias (__simple_malloc, __libc_malloc_impl)
void * __libc_malloc (size_t n)
static void * default_malloc (size_t n)
weak_alias (default_malloc, malloc)
Variables
static volatile int lock [1]
volatile int *const __bump_lockptr = lock
Macro Definition Documentation
ALIGN
#define ALIGN 16
Definition at line 11 of file lite_malloc.c.
Function Documentation
__libc_malloc()
void* __libc_malloc (size_t n)
Definition at line 108 of file lite_malloc.c.
 {
     return __libc_malloc_impl(n);
 }
References __libc_malloc_impl(), and n.
__simple_malloc()
static void* __simple_malloc (size_t n) static
Definition at line 38 of file lite_malloc.c.
 {
     static uintptr_t brk, cur, end;
     static unsigned mmap_step;
     size_t align=1;
     void *p;
     if (n > SIZE_MAX/2) {
         errno = ENOMEM;
         return 0;
     }
     if (!n) n++;
     while (align<n && align<ALIGN)
         align += align;
     LOCK(lock);
     cur += -cur & align-1;
     if (n > end-cur) {
         size_t req = n - (end-cur) + PAGE_SIZE-1 & -PAGE_SIZE;
         if (!cur) {
             brk = __syscall(SYS_brk, 0);
             brk += -brk & PAGE_SIZE-1;
             cur = end = brk;
         }
         if (brk == end && req < SIZE_MAX-brk
             && !traverses_stack_p(brk, brk+req)
             && __syscall(SYS_brk, brk+req)==brk+req) {
             brk = end += req;
         } else {
             int new_area = 0;
             req = n + PAGE_SIZE-1 & -PAGE_SIZE;
             /* Only make a new area rather than individual mmap
              * if wasted space would be over 1/8 of the map. */
             if (req-n > req/8) {
                 /* Geometric area size growth up to 64 pages,
                  * bounding waste by 1/8 of the area. */
                 size_t min = PAGE_SIZE<<(mmap_step/2);
                 if (min-n > end-cur) {
                     if (req < min) {
                         req = min;
                         if (mmap_step < 12)
                             mmap_step++;
                     }
                     new_area = 1;
                 }
             }
             void *mem = __mmap(0, req, PROT_READ|PROT_WRITE,
                 MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
             if (mem == MAP_FAILED || !new_area) {
                 UNLOCK(lock);
                 return mem==MAP_FAILED ? 0 : mem;
             }
             cur = (uintptr_t)mem;
             end = cur + req;
         }
     }
     p = (void *)cur;
     cur += n;
     UNLOCK(lock);
     return p;
 }
References __mmap(), __syscall, ALIGN, brk(), cur, end, ENOMEM, errno, LOCK, lock, MAP_ANONYMOUS, MAP_FAILED, MAP_PRIVATE, mem, min, n, p, PAGE_SIZE, PROT_READ, PROT_WRITE, SIZE_MAX, traverses_stack_p(), and UNLOCK.
default_malloc()
static void* default_malloc (size_t n) static
Definition at line 113 of file lite_malloc.c.
 {
     return __libc_malloc_impl(n);
 }
References __libc_malloc_impl(), and n.
traverses_stack_p()
static int traverses_stack_p (uintptr_t old, uintptr_t new) static
Definition at line 19 of file lite_malloc.c.
 {
     const uintptr_t len = 8<<20;
     uintptr_t a, b;
     b = (uintptr_t)libc.auxv;
     a = b > len ? b-len : 0;
     if (new>a && old<b) return 1;
     b = (uintptr_t)&b;
     a = b > len ? b-len : 0;
     if (new>a && old<b) return 1;
     return 0;
 }
References if(), len, libc, and old.
Referenced by __simple_malloc().
weak_alias() [1/2]
weak_alias (__simple_malloc , __libc_malloc_impl)
weak_alias() [2/2]
weak_alias (default_malloc , malloc)
Variable Documentation
__bump_lockptr
volatile int* const __bump_lockptr = lock
Definition at line 36 of file lite_malloc.c.
lock
volatile int lock[1] static
Definition at line 35 of file lite_malloc.c.
Referenced by __simple_malloc().