Fennix: Userspace/mlibc/options/posix/generic/utime-stubs.cpp File Reference
utime-stubs.cpp File Reference
#include <utime.h>
#include <fcntl.h>
#include <errno.h>
#include <bits/ensure.h>
#include <mlibc/posix-sysdeps.hpp>
Functions
int utime (const char *filename, const struct utimbuf *times)
Function Documentation
utime()
int utime (const char * filename, const struct utimbuf * times)
Definition at line 9 of file utime-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     struct timespec time[2];
     if(times) {
         time[0].tv_sec = times->actime;
         time[0].tv_nsec = 0;
         time[1].tv_sec = times->modtime;
         time[1].tv_nsec = 0;
     } else {
         time[0].tv_sec = UTIME_NOW;
         time[0].tv_nsec = UTIME_NOW;
         time[1].tv_sec = UTIME_NOW;
         time[1].tv_nsec = UTIME_NOW;
     }
     if (int e = mlibc::sys_utimensat(AT_FDCWD, filename, time, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_utimensat(), time(), times(), and UTIME_NOW.