Fennix Userspace: Userspace/mlibc/options/posix/include/netdb.h File Reference
netdb.h File Reference
#include <stdint.h>
#include <bits/size_t.h>
#include <bits/posix/in_port_t.h>
#include <bits/posix/in_addr_t.h>
#include <abi-bits/socklen_t.h>
Data Structures
struct hostent
struct netent
struct protoent
struct servent
struct addrinfo
Macros
#define AI_PASSIVE 0x01
#define AI_CANONNAME 0x02
#define AI_NUMERICHOST 0x04
#define AI_V4MAPPED 0x08
#define AI_ALL 0x10
#define AI_ADDRCONFIG 0x20
#define AI_NUMERICSERV 0x40
#define NI_NOFQDN 0x01
#define NI_NUMERICHOST 0x02
#define NI_NAMEREQD 0x04
#define NI_NUMERICSCOPE 0x08
#define NI_DGRAM 0x10
#define NI_NUMERICSERV 2
#define NI_MAXSERV 32
#define NI_IDN 32
#define NI_MAXHOST 1025
#define EAI_AGAIN 1
#define EAI_BADFLAGS 2
#define EAI_FAIL 3
#define EAI_FAMILY 4
#define EAI_MEMORY 5
#define EAI_NONAME 6
#define EAI_SERVICE 7
#define EAI_SOCKTYPE 8
#define EAI_SYSTEM 9
#define EAI_OVERFLOW 10
#define EAI_NODATA 11
#define EAI_ADDRFAMILY 12
#define HOST_NOT_FOUND 1
#define TRY_AGAIN 2
#define NO_RECOVERY 3
#define NO_DATA 4
#define NO_ADDRESS NO_DATA
#define IPPORT_RESERVED 1024
#define _PATH_SERVICES "/etc/services"
#define h_errno (*__h_errno_location())
#define h_addr h_addr_list[0]
Functions
int * __h_errno_location (void)
void endhostent (void)
void endnetent (void)
void endprotoent (void)
void endservent (void)
void freeaddrinfo (struct addrinfo *)
const char * gai_strerror (int)
int getaddrinfo (const char *__restrict, const char *__restrict, const struct addrinfo *__restrict, struct addrinfo **__restrict)
struct hostent * gethostent (void)
struct hostent * gethostbyname (const char *)
struct hostent * gethostbyname2 (const char *, int)
struct hostent * gethostbyaddr (const void *, socklen_t, int)
int gethostbyaddr_r (const void *__restrict, socklen_t, int, struct hostent *__restrict, char *__restrict, size_t, struct hostent **__restrict, int *__restrict)
int gethostbyname_r (const char *__restrict, struct hostent *__restrict, char *__restrict, size_t, struct hostent **__restrict, int *__restrict)
int getnameinfo (const struct sockaddr *__restrict, socklen_t, char *__restrict, socklen_t, char *__restrict, socklen_t, int)
struct netent * getnetbyaddr (uint32_t, int)
struct netent * getnetbyname (const char *)
struct netent * getnetent (void)
struct protoent * getprotobyname (const char *)
struct protoent * getprotobynumber (int)
struct protoent * getprotoent (void)
struct servent * getservbyname (const char *, const char *)
struct servent * getservbyport (int, const char *)
struct servent * getservent (void)
void sethostent (int)
void setnetent (int)
void setprotoent (int)
void setservent (int)
Data Structure Documentation
hostent
struct hostent
Definition at line 64 of file netdb.h.
Data Fields
char ** h_addr_list
int h_addrtype
char ** h_aliases
int h_length
char * h_name
netent
struct netent
Definition at line 74 of file netdb.h.
Data Fields
int n_addrtype
char ** n_aliases
char * n_name
uint32_t n_net
protoent
struct protoent
Definition at line 81 of file netdb.h.
Data Fields
char ** p_aliases
char * p_name
int p_proto
servent
struct servent
Definition at line 87 of file netdb.h.
Data Fields
char ** s_aliases
char * s_name
int s_port
char * s_proto
addrinfo
struct addrinfo
Definition at line 94 of file netdb.h.
Data Fields
struct sockaddr * ai_addr
socklen_t ai_addrlen
char * ai_canonname
int ai_family
int ai_flags
struct addrinfo * ai_next
int ai_protocol
int ai_socktype
Macro Definition Documentation
_PATH_SERVICES
#define _PATH_SERVICES "/etc/services"
Definition at line 51 of file netdb.h.
AI_ADDRCONFIG
#define AI_ADDRCONFIG 0x20
Definition at line 15 of file netdb.h.
AI_ALL
#define AI_ALL 0x10
Definition at line 14 of file netdb.h.
AI_CANONNAME
#define AI_CANONNAME 0x02
Definition at line 11 of file netdb.h.
AI_NUMERICHOST
#define AI_NUMERICHOST 0x04
Definition at line 12 of file netdb.h.
AI_NUMERICSERV
#define AI_NUMERICSERV 0x40
Definition at line 16 of file netdb.h.
AI_PASSIVE
#define AI_PASSIVE 0x01
Definition at line 10 of file netdb.h.
AI_V4MAPPED
#define AI_V4MAPPED 0x08
Definition at line 13 of file netdb.h.
EAI_ADDRFAMILY
#define EAI_ADDRFAMILY 12
Definition at line 41 of file netdb.h.
EAI_AGAIN
#define EAI_AGAIN 1
Definition at line 30 of file netdb.h.
EAI_BADFLAGS
#define EAI_BADFLAGS 2
Definition at line 31 of file netdb.h.
EAI_FAIL
#define EAI_FAIL 3
Definition at line 32 of file netdb.h.
EAI_FAMILY
#define EAI_FAMILY 4
Definition at line 33 of file netdb.h.
EAI_MEMORY
#define EAI_MEMORY 5
Definition at line 34 of file netdb.h.
EAI_NODATA
#define EAI_NODATA 11
Definition at line 40 of file netdb.h.
EAI_NONAME
#define EAI_NONAME 6
Definition at line 35 of file netdb.h.
EAI_OVERFLOW
#define EAI_OVERFLOW 10
Definition at line 39 of file netdb.h.
EAI_SERVICE
#define EAI_SERVICE 7
Definition at line 36 of file netdb.h.
EAI_SOCKTYPE
#define EAI_SOCKTYPE 8
Definition at line 37 of file netdb.h.
EAI_SYSTEM
#define EAI_SYSTEM 9
Definition at line 38 of file netdb.h.
h_addr
#define h_addr h_addr_list[0]
Definition at line 72 of file netdb.h.
h_errno
#define h_errno (*__h_errno_location())
Definition at line 60 of file netdb.h.
HOST_NOT_FOUND
#define HOST_NOT_FOUND 1
Definition at line 43 of file netdb.h.
IPPORT_RESERVED
#define IPPORT_RESERVED 1024
Definition at line 49 of file netdb.h.
NI_DGRAM
#define NI_DGRAM 0x10
Definition at line 22 of file netdb.h.
NI_IDN
#define NI_IDN 32
Definition at line 26 of file netdb.h.
NI_MAXHOST
#define NI_MAXHOST 1025
Definition at line 28 of file netdb.h.
NI_MAXSERV
#define NI_MAXSERV 32
Definition at line 25 of file netdb.h.
NI_NAMEREQD
#define NI_NAMEREQD 0x04
Definition at line 20 of file netdb.h.
NI_NOFQDN
#define NI_NOFQDN 0x01
Definition at line 18 of file netdb.h.
NI_NUMERICHOST
#define NI_NUMERICHOST 0x02
Definition at line 19 of file netdb.h.
NI_NUMERICSCOPE
#define NI_NUMERICSCOPE 0x08
Definition at line 21 of file netdb.h.
NI_NUMERICSERV
#define NI_NUMERICSERV 2
Definition at line 24 of file netdb.h.
NO_ADDRESS
#define NO_ADDRESS NO_DATA
Definition at line 47 of file netdb.h.
NO_DATA
#define NO_DATA 4
Definition at line 46 of file netdb.h.
NO_RECOVERY
#define NO_RECOVERY 3
Definition at line 45 of file netdb.h.
TRY_AGAIN
#define TRY_AGAIN 2
Definition at line 44 of file netdb.h.
Function Documentation
__h_errno_location()
int* __h_errno_location (void)
Definition at line 21 of file netdb-stubs.cpp.
{
     return &__mlibc_h_errno;
 }
References __mlibc_h_errno.
endhostent()
void endhostent (void)
Definition at line 25 of file netdb-stubs.cpp.
                       {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
endnetent()
void endnetent (void)
Definition at line 30 of file netdb-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
endprotoent()
void endprotoent (void)
Definition at line 35 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
endservent()
void endservent (void)
Definition at line 40 of file netdb-stubs.cpp.
                       {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
freeaddrinfo()
void freeaddrinfo (struct addrinfo * ptr)
Definition at line 45 of file netdb-stubs.cpp.
{
     if (ptr) {
         auto buf = (struct mlibc::ai_buf*) ptr - offsetof(struct mlibc::ai_buf, ai);
         // this string was allocated by a frg::string
         getAllocator().free(ptr->ai_canonname);
         free(buf);
     }
 }
References mlibc::ai_buf::ai, addrinfo::ai_canonname, buf, free(), getAllocator(), and offsetof.
Referenced by main().
gai_strerror()
const char* gai_strerror (int code)
Definition at line 54 of file netdb-stubs.cpp.
{
     static thread_local char buffer[128];
     snprintf(buffer, sizeof(buffer), "Unknown error (%d)", code);
     return buffer;
 }
References snprintf().
getaddrinfo()
int getaddrinfo (const char * __restrict, const char * __restrict, const struct addrinfo * __restrict, struct addrinfo ** __restrict)
gethostbyaddr()
struct hostent* gethostbyaddr (const void * , socklen_t , int)
Definition at line 308 of file netdb-stubs.cpp.
{
     __ensure(!"gethostbyaddr() not implemented");
     __builtin_unreachable();
 }
References __ensure.
gethostbyaddr_r()
int gethostbyaddr_r (const void * __restrict, socklen_t , int , struct hostent * __restrict, char * __restrict, size_t , struct hostent ** __restrict, int * __restrict)
Definition at line 313 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
gethostbyname()
struct hostent* gethostbyname (const char * name)
Definition at line 232 of file netdb-stubs.cpp.
{
     if (!name) {
         h_errno = HOST_NOT_FOUND;
         return NULL;
     }
     struct mlibc::lookup_result buf;
     frg::string<MemoryAllocator> canon{getAllocator()};
     int ret = 0;
     if ((ret = mlibc::lookup_name_hosts(buf, name, canon)) <= 0)
         ret = mlibc::lookup_name_dns(buf, name, canon);
     if (ret <= 0) {
         h_errno = HOST_NOT_FOUND;
         return NULL;
     }
     static struct hostent h;
     if (h.h_name) {
         getAllocator().free(h.h_name);
         for (int i = 0; h.h_aliases[i] != NULL; i++)
             getAllocator().free(h.h_aliases[i]);
         free(h.h_aliases);
         if (h.h_addr_list) {
             for (int i = 0; h.h_addr_list[i] != NULL; i++)
                 free(h.h_addr_list[i]);
             free(h.h_addr_list);
         }
     }
     h = {};
     if (!canon.size())
         canon = frg::string<MemoryAllocator>{name, getAllocator()};
     h.h_name = canon.data();
     h.h_aliases = reinterpret_cast<char**>(malloc((buf.aliases.size() + 1)
                 * sizeof(char*)));
     int alias_pos = 0;
     for (auto &buf_name : buf.aliases) {
         h.h_aliases[alias_pos] = buf_name.data();
         buf_name.detach();
         alias_pos++;
     }
     h.h_aliases[alias_pos] = NULL;
     canon.detach();
     // just pick the first family as the one for all addresses...??
     h.h_addrtype = buf.buf[0].family;
     if (h.h_addrtype != AF_INET && h.h_addrtype != AF_INET6) {
         // this is not allowed per spec
         h_errno = NO_DATA;
         return NULL;
     }
     // can only be AF_INET or AF_INET6
     h.h_length = h.h_addrtype == AF_INET ? 4 : 16;
     h.h_addr_list = reinterpret_cast<char**>(malloc((ret + 1) * sizeof(char*)));
     int addr_pos = 0;
     for (int i = 0; i < ret; i++) {
         if (buf.buf[i].family != h.h_addrtype)
             continue;
         h.h_addr_list[addr_pos] = reinterpret_cast<char*>(malloc(h.h_length));
         memcpy(h.h_addr_list[addr_pos], buf.buf[i].addr, h.h_length);
         addr_pos++;
     }
     h.h_addr_list[addr_pos] = NULL;
     return &h;
 }
References AF_INET, AF_INET6, buf, free(), getAllocator(), hostent::h_addr_list, hostent::h_addrtype, hostent::h_aliases, h_errno, hostent::h_length, hostent::h_name, HOST_NOT_FOUND, i, mlibc::lookup_name_dns(), mlibc::lookup_name_hosts(), malloc(), memcpy(), name, NO_DATA, NULL, and ret.
gethostbyname2()
struct hostent* gethostbyname2 (const char * , int)
Definition at line 303 of file netdb-stubs.cpp.
{
     __ensure(!"gethostbyname2() not implemented");
     __builtin_unreachable();
 }
References __ensure.
gethostbyname_r()
int gethostbyname_r (const char * __restrict, struct hostent * __restrict, char * __restrict, size_t , struct hostent ** __restrict, int * __restrict)
Definition at line 319 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
gethostent()
struct hostent* gethostent (void)
Definition at line 151 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getnameinfo()
int getnameinfo (const struct sockaddr * __restrict, socklen_t , char * __restrict, socklen_t , char * __restrict, socklen_t , int)
getnetbyaddr()
struct netent* getnetbyaddr (uint32_t , int)
Definition at line 217 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getnetbyname()
struct netent* getnetbyname (const char *)
Definition at line 222 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getnetent()
struct netent* getnetent (void)
Definition at line 227 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getprotobyname()
struct protoent* getprotobyname (const char *)
Definition at line 325 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getprotobynumber()
struct protoent* getprotobynumber (int)
Definition at line 330 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getprotoent()
struct protoent* getprotoent (void)
Definition at line 335 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getservbyname()
struct servent* getservbyname (const char * name, const char * proto)
Definition at line 340 of file netdb-stubs.cpp.
{
     int iproto = -1;
     if (proto &&(!strncmp(proto, "tcp", 3) || !strncmp(proto, "TCP", 3)))
         iproto = IPPROTO_TCP;
     else if (proto && (!strncmp(proto, "udp", 3) || !strncmp(proto, "UDP", 3)))
         iproto = IPPROTO_UDP;
     static struct servent ret;
     if (ret.s_name) {
         free(ret.s_name);
         ret.s_name = nullptr;
         for (char **alias = ret.s_aliases; *alias != NULL; alias++) {
             free(*alias);
             *alias = nullptr;
         }
         free(ret.s_proto);
         ret.s_proto = nullptr;
     }
     mlibc::service_result serv_buf{getAllocator()};
     int count = mlibc::lookup_serv_by_name(serv_buf, name, iproto,
             0, 0);
     if (count <= 0)
         return NULL;
     ret.s_name = serv_buf[0].name.data();
     serv_buf[0].name.detach();
     // Sanity check.
     if (strncmp(name, serv_buf[0].name.data(), serv_buf[0].name.size()))
         return NULL;
     ret.s_aliases = reinterpret_cast<char**>(malloc((serv_buf[0].aliases.size() + 1) * sizeof(char*)));
     int alias_pos = 0;
     for (auto &buf_name : serv_buf[0].aliases) {
         ret.s_aliases[alias_pos] = buf_name.data();
         buf_name.detach();
         alias_pos++;
     }
     ret.s_aliases[alias_pos] = NULL;
     ret.s_port = htons(serv_buf[0].port);
     auto proto_string = frg::string<MemoryAllocator>(getAllocator());
     if (!proto) {
         if (serv_buf[0].protocol == IPPROTO_TCP)
             proto_string = frg::string<MemoryAllocator>("tcp", getAllocator());
         else if (serv_buf[0].protocol == IPPROTO_UDP)
             proto_string = frg::string<MemoryAllocator>("udp", getAllocator());
         else
             return NULL;
     } else {
         proto_string = frg::string<MemoryAllocator>(proto, getAllocator());
     }
     ret.s_proto = proto_string.data();
     proto_string.detach();
     return &ret;
 }
References mlibc::count, free(), getAllocator(), htons(), IPPROTO_TCP, IPPROTO_UDP, mlibc::lookup_serv_by_name(), malloc(), name, NULL, ret, and strncmp().
Referenced by main().
getservbyport()
struct servent* getservbyport (int port, const char * proto)
Definition at line 401 of file netdb-stubs.cpp.
{
     int iproto = -1;
     if (proto && (!strncmp(proto, "tcp", 3) || !strncmp(proto, "TCP", 3)))
         iproto = IPPROTO_TCP;
     else if (proto && (!strncmp(proto, "udp", 3) || !strncmp(proto, "UDP", 3)))
         iproto = IPPROTO_UDP;
     static struct servent ret;
     if (ret.s_name) {
         free(ret.s_name);
         ret.s_name = nullptr;
         for (char **alias = ret.s_aliases; *alias != NULL; alias++) {
             free(*alias);
             *alias = nullptr;
         }
         free(ret.s_proto);
         ret.s_proto = nullptr;
     }
     mlibc::service_result serv_buf{getAllocator()};
     int count = mlibc::lookup_serv_by_port(serv_buf, iproto, ntohs(port));
     if (count <= 0)
         return NULL;
     ret.s_name = serv_buf[0].name.data();
     serv_buf[0].name.detach();
     ret.s_aliases = reinterpret_cast<char**>(malloc((serv_buf[0].aliases.size() + 1) * sizeof(char*)));
     int alias_pos = 0;
     for (auto &buf_name : serv_buf[0].aliases) {
         ret.s_aliases[alias_pos] = buf_name.data();
         buf_name.detach();
         alias_pos++;
     }
     ret.s_aliases[alias_pos] = NULL;
     ret.s_port = port;
     auto proto_string = frg::string<MemoryAllocator>(getAllocator());
     if (!proto) {
         if (serv_buf[0].protocol == IPPROTO_TCP)
             proto_string = frg::string<MemoryAllocator>("tcp", getAllocator());
         else if (serv_buf[0].protocol == IPPROTO_UDP)
             proto_string = frg::string<MemoryAllocator>("udp", getAllocator());
         else
             return NULL;
     } else {
         proto_string = frg::string<MemoryAllocator>(proto, getAllocator());
     }
     ret.s_proto = proto_string.data();
     proto_string.detach();
     return &ret;
 }
References mlibc::count, free(), getAllocator(), IPPROTO_TCP, IPPROTO_UDP, mlibc::lookup_serv_by_port(), malloc(), ntohs(), NULL, ret, and strncmp().
Referenced by main().
getservent()
struct servent* getservent (void)
Definition at line 458 of file netdb-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sethostent()
void sethostent (int)
Definition at line 463 of file netdb-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setnetent()
void setnetent (int)
Definition at line 468 of file netdb-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setprotoent()
void setprotoent (int)
Definition at line 473 of file netdb-stubs.cpp.
                       {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setservent()
void setservent (int)
Definition at line 478 of file netdb-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.