Fennix Kernel: Kernel/library/simd_memset.cpp File Reference
simd_memset.cpp File Reference
#include <convert.h>
#include <memory.hpp>
#include <limits.h>
#include <debug.h>
#include <cpu.hpp>
Functions
EXTERNC void * memset_sse (void *dest, int c, size_t n)
EXTERNC void * memset_sse2 (void *dest, int c, size_t n)
EXTERNC void * memset_sse3 (void *dest, int c, size_t n)
EXTERNC void * memset_ssse3 (void *dest, int c, size_t n)
EXTERNC void * memset_sse4_1 (void *dest, int c, size_t n)
EXTERNC void * memset_sse4_2 (void *dest, int c, size_t n)
Function Documentation
memset_sse()
EXTERNC void* memset_sse (void * dest, int c, size_t n)
Definition at line 32 of file simd_memset.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References memset_unsafe().
Referenced by __memset_chk().
memset_sse2()
EXTERNC void* memset_sse2 (void * dest, int c, size_t n)
Definition at line 37 of file simd_memset.cpp.
 {
     size_t i;
     if ((size_t)dest & (16 - 1))
     {
         i = 0;
         while (((size_t)dest + i) & (16 - 1) && i < n)
         {
             asmv("stosb\n"
                  :
                  : "D"((size_t)dest + i),
                    "a"(c));
             i++;
         }
     }
     else
         i = 0;
     for (; i + 64 <= n; i += 64)
     {
         asmv("movd %0, %%xmm0\n"
              "movdqa %%xmm0, (%1)\n"
              "movdqa %%xmm0, 16(%1)\n"
              "movdqa %%xmm0, 32(%1)\n"
              "movdqa %%xmm0, 48(%1)\n"
              :
              : "r"(c), "r"(((size_t)dest) + i)
              : "xmm0");
     }
     asmv("rep stosb\n" ::"a"((size_t)(c)),
          "D"(((size_t)dest) + i),
          "c"(n - i));
     i += n - i;
     return (void *)(((size_t)dest) + i);
 }
References asmv().
Referenced by __memset_chk(), memset_sse3(), memset_sse4_1(), and memset_ssse3().
memset_sse3()
EXTERNC void* memset_sse3 (void * dest, int c, size_t n)
Definition at line 75 of file simd_memset.cpp.
 {
     return memset_sse2(dest, c, n);
 }
References memset_sse2().
Referenced by __memset_chk().
memset_sse4_1()
EXTERNC void* memset_sse4_1 (void * dest, int c, size_t n)
Definition at line 85 of file simd_memset.cpp.
 {
     return memset_sse2(dest, c, n);
 }
References memset_sse2().
Referenced by __memset_chk().
memset_sse4_2()
EXTERNC void* memset_sse4_2 (void * dest, int c, size_t n)
Definition at line 90 of file simd_memset.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     if (((uintptr_t)d & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movd %0, %%xmm0\n"
                  "pshufd $0, %%xmm0, %%xmm0\n"
                  "movdqa %%xmm0, (%1)\n"
                  :
                  : "r"(c), "r"(d)
                  : "xmm0");
             d += 16;
         }
         n -= num_vectors * 16;
     }
     memset_unsafe(d, c, n);
 #endif
     return dest;
 }
References asmv(), and memset_unsafe().
Referenced by __memset_chk().
memset_ssse3()
EXTERNC void* memset_ssse3 (void * dest, int c, size_t n)
Definition at line 80 of file simd_memset.cpp.
 {
     return memset_sse2(dest, c, n);
 }
References memset_sse2().
Referenced by __memset_chk().