Fennix Kernel: Kernel/include/cargs.h File Reference
cargs.h File Reference
#include <types.h>
Data Structures
struct cag_option
struct cag_option_context
Macros
#define CAG_LIBRARY_H
#define CAG_EXPORT
#define CAG_IMPORT
#define CAG_PUBLIC
#define CAG_ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
Typedefs
typedef unsigned int FILE
typedef struct cag_option cag_option
typedef struct cag_option_context cag_option_context
Functions
CAG_PUBLIC void cag_option_print (const cag_option *options, size_t option_count, FILE *destination)
Prints all options to the terminal.
CAG_PUBLIC void cag_option_prepare (cag_option_context *context, const cag_option *options, size_t option_count, int argc, char **argv)
Prepare argument options context for parsing.
CAG_PUBLIC bool cag_option_fetch (cag_option_context *context)
Fetches an option from the argument list.
CAG_PUBLIC char cag_option_get (const cag_option_context *context)
Gets the identifier of the option.
CAG_PUBLIC const char * cag_option_get_value (const cag_option_context *context)
Gets the value from the option.
CAG_PUBLIC int cag_option_get_index (const cag_option_context *context)
Gets the current index of the context.
Data Structure Documentation
cag_option
struct cag_option
An option is used to describe a flag/argument option submitted when the program is run.
Definition at line 70 of file cargs.h.
Data Fields
const char * access_letters
const char * access_name
const char * description
const char identifier
const char * value_name
cag_option_context
struct cag_option_context
A context is used to iterate over all options provided. It stores the parsing state.
Definition at line 83 of file cargs.h.
Data Fields
int argc
char ** argv
bool forced_end
char identifier
int index
int inner_index
size_t option_count
const struct cag_option * options
char * value
Macro Definition Documentation
CAG_ARRAY_SIZE
#define CAG_ARRAY_SIZE (arr) (sizeof(arr) / sizeof((arr)[0]))
This is just a small macro which calculates the size of an array.
Definition at line 99 of file cargs.h.
CAG_EXPORT
#define CAG_EXPORT
Definition at line 47 of file cargs.h.
CAG_IMPORT
#define CAG_IMPORT
Definition at line 48 of file cargs.h.
CAG_LIBRARY_H
#define CAG_LIBRARY_H
This is a simple alternative cross-platform implementation of getopt, which is used to parse argument strings submitted to the executable (argc and argv which are received in the main function).
Definition at line 34 of file cargs.h.
CAG_PUBLIC
#define CAG_PUBLIC
Definition at line 58 of file cargs.h.
Typedef Documentation
cag_option
typedef struct cag_option cag_option
An option is used to describe a flag/argument option submitted when the program is run.
cag_option_context
typedef struct cag_option_context cag_option_context
A context is used to iterate over all options provided. It stores the parsing state.
FILE
typedef unsigned int FILE
Definition at line 38 of file cargs.h.
Function Documentation
cag_option_fetch()
CAG_PUBLIC bool cag_option_fetch (cag_option_context * context)
Fetches an option from the argument list.
This function fetches a single option from the argument list. The context will be moved to that item. Information can be extracted from the context after the item has been fetched. The arguments will be re-ordered, which means that non-option arguments will be moved to the end of the argument list. After all options have been fetched, all non-option arguments will be positioned after the index of the context.
Parameters
context The context from which we will fetch the option.
Returns
Returns true if there was another option or false if the end is reached.
Definition at line 432 of file cargs.c.
 {
     char *c;
     int old_index, new_index;
     // Reset our identifier to a question mark, which indicates an "unknown"
     // option. The value is set to NULL, to make sure we are not carrying the
     // parameter from the previous option to this one.
     context->identifier = '?';
     context->value = NULL;
     // Check whether there are any options left to parse and remember the old
     // index as well as the new index. In the end we will move the option junk to
     // the beginning, so that non option arguments can be read.
     old_index = context->index;
     new_index = cag_option_find_next(context);
     if (new_index >= 0)
     {
         context->index = new_index;
     }
     else
     {
         return false;
     }
     // Grab a pointer to the beginning of the option. At this point, the next
     // character must be a '-', since if it was not the prepare function would
     // have returned false. We will skip that symbol and proceed.
     c = context->argv[context->index];
     assert(*c == '-');
     ++c;
     // Check whether this is a long option, starting with a double "--".
     if (*c == '-')
     {
         ++c;
         // This might be a double "--" which indicates the end of options. If this
         // is the case, we will not move to the next index. That ensures that
         // another call to the fetch function will not skip the "--".
         if (*c == '\0')
         {
             context->forced_end = true;
         }
         else
         {
             // We parse now the access name. All information about it will be written
             // to the context.
             cag_option_parse_access_name(context, &c);
         }
     }
     else
     {
         // This is no long option, so we can just parse an access letter.
         cag_option_parse_access_letter(context, &c);
     }
     // Move the items so that the options come first followed by non-option
     // arguments.
     cag_option_shift(context, old_index, new_index, context->index);
     return context->forced_end == false;
 }
References cag_option_context::argv, assert, cag_option_find_next(), cag_option_parse_access_letter(), cag_option_parse_access_name(), cag_option_shift(), cag_option_context::forced_end, cag_option_context::identifier, cag_option_context::index, NULL, and cag_option_context::value.
Referenced by ParseConfig().
cag_option_get()
CAG_PUBLIC char cag_option_get (const cag_option_context * context)
Gets the identifier of the option.
This function gets the identifier of the option, which should be unique to this option and can be used to determine what kind of option this is.
Parameters
context The context from which the option was fetched.
Returns
Returns the identifier of the option.
Definition at line 496 of file cargs.c.
 {
     // We just return the identifier here.
     return context->identifier;
 }
References cag_option_context::identifier.
Referenced by ParseConfig().
cag_option_get_index()
CAG_PUBLIC int cag_option_get_index (const cag_option_context * context)
Gets the current index of the context.
This function gets the index within the argv arguments of the context. The context always points to the next item which it will inspect. This is particularly useful to inspect the original argument array, or to get non-option arguments after option fetching has finished.
Parameters
context The context from which the option was fetched.
Returns
Returns the current index of the context.
Definition at line 508 of file cargs.c.
 {
     // Either we point to a value item,
     return context->index;
 }
References cag_option_context::index.
cag_option_get_value()
CAG_PUBLIC const char* cag_option_get_value (const cag_option_context * context)
Gets the value from the option.
This function gets the value from the option, if any. If the option does not contain a value, this function will return NULL.
Parameters
context The context from which the option was fetched.
Returns
Returns a pointer to the value or NULL if there is no value.
Definition at line 502 of file cargs.c.
 {
     // We just return the internal value pointer of the context.
     return context->value;
 }
References cag_option_context::value.
Referenced by ParseConfig().
cag_option_prepare()
CAG_PUBLIC void cag_option_prepare (cag_option_context * context, const cag_option * options, size_t option_count, int argc, char ** argv)
Prepare argument options context for parsing.
This function prepares the context for iteration and initializes the context with the supplied options and arguments. After the context has been prepared, it can be used to fetch arguments from it.
Parameters
context The context which will be initialized.
options The registered options which are available for the program.
option_count The amount of options which are available for the program.
argc The amount of arguments the user supplied in the main function.
argv A pointer to the arguments of the main function.
Definition at line 155 of file cargs.c.
 {
     // This just initialized the values to the beginning of all the arguments.
     context->options = options;
     context->option_count = option_count;
     context->argc = argc;
     context->argv = argv;
     context->index = 1;
     context->inner_index = 0;
     context->forced_end = false;
 }
References cag_option_context::argc, cag_option_context::argv, cag_option_context::forced_end, cag_option_context::index, cag_option_context::inner_index, cag_option_context::option_count, and cag_option_context::options.
Referenced by ParseConfig().
cag_option_print()
CAG_PUBLIC void cag_option_print (const cag_option * options, size_t option_count, FILE * destination)
Prints all options to the terminal.
This function prints all options to the terminal. This can be used to generate the output for a "--help" option.
Parameters
options The options which will be printed.
option_count The option count which will be printed.
destination The destination where the output will be printed.
Definition at line 122 of file cargs.c.
 {
     size_t option_index, indention, i, accessor_length;
     const cag_option *option;
     bool first;
     indention = cag_option_get_print_indention(options, option_count);
     for (option_index = 0; option_index < option_count; ++option_index)
     {
         option = &options[option_index];
         accessor_length = 0;
         first = true;
         fputs("  ", destination);
         cag_option_print_letters(option, &first, &accessor_length, destination);
         cag_option_print_name(option, &first, &accessor_length, destination);
         cag_option_print_value(option, &accessor_length, destination);
         for (i = accessor_length; i < indention; ++i)
         {
             fputs(" ", destination);
         }
         fputs(" ", destination);
         fputs(option->description, destination);
         fprintf(destination, "\n");
     }
 }
References cag_option_get_print_indention(), cag_option_print_letters(), cag_option_print_name(), cag_option_print_value(), cag_option::description, fprintf(), and fputs().
Referenced by ParseConfig().