Fennix: Userspace/mlibc/options/posix/include/sys/uio.h File Reference
uio.h File Reference
#include <bits/posix/iovec.h>
#include <bits/ssize_t.h>
#include <bits/off_t.h>
#include <bits/size_t.h>
#include <limits.h>
Macros
#define UIO_MAXIOV IOV_MAX
Functions
ssize_t readv (int fd, const struct iovec *iov, int iovcnt)
ssize_t writev (int fd, const struct iovec *iov, int iovcnt)
ssize_t preadv (int fd, const struct iovec *iov, int iovcnt, off_t offset)
ssize_t pwritev (int fd, const struct iovec *iov, int iovcnt, off_t offset)
Macro Definition Documentation
UIO_MAXIOV
#define UIO_MAXIOV IOV_MAX
Definition at line 14 of file uio.h.
Function Documentation
preadv()
ssize_t preadv (int fd, const struct iovec * iov, int iovcnt, off_t offset)
Definition at line 59 of file sys-uio.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pwritev()
ssize_t pwritev (int fd, const struct iovec * iov, int iovcnt, off_t offset)
Definition at line 64 of file sys-uio.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
readv()
ssize_t readv (int fd, const struct iovec * iov, int iovcnt)
Definition at line 15 of file sys-uio.cpp.
{
     ssize_t read_bytes = 0;
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_readv, -1);
     if (int e = sysdep(fd, iovs, iovc, &read_bytes); e) {
         errno = e;
         return -1;
     }
     return read_bytes;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_readv().
Referenced by main().
writev()
ssize_t writev (int fd, const struct iovec * iov, int iovcnt)
Definition at line 28 of file sys-uio.cpp.
{
     __ensure(iovc);
     ssize_t written = 0;
     size_t bytes = 0;
     for(int i = 0; i < iovc; i++) {
         if(SSIZE_MAX - bytes < iovs[i].iov_len) {
             errno = EINVAL;
             return -1;
         }
         bytes += iovs[i].iov_len;
     }
     frg::vector<char, MemoryAllocator> buffer{getAllocator()};
     buffer.resize(bytes);
     size_t to_copy = bytes;
     char *bp = buffer.data();
     for(int i = 0; i < iovc; i++) {
         size_t copy = frg::min(iovs[i].iov_len, to_copy);
         bp = (char *)mempcpy((void *)bp, (void *)iovs[i].iov_base, copy);
         to_copy -= copy;
         if(to_copy == 0)
             break;
     }
     written = write(fd, buffer.data(), bytes);
     return written;
 }
References __ensure, bp, EINVAL, errno, fd, getAllocator(), i, iovec::iov_len, mempcpy(), SSIZE_MAX, and write().
Referenced by main().