Fennix: Userspace/apps/base/busybox/coreutils/dd.c File Reference
dd.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define XATOU_SFX xatoul_sfx
#define obs ibs
#define obuf ibuf
#define ocount (Z.ocount)
#define prev_read_size (Z.prev_read_size)
#define count (Z.count)
#define seek (Z.seek)
#define skip (Z.skip)
#define infile (Z.infile)
#define outfile (Z.outfile)
Enumerations
enum { ifd = STDIN_FILENO , ofd = STDOUT_FILENO }
enum {
FLAG_NOTRUNC = (1 << 0) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_SYNC = (1 << 1) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_NOERROR = (1 << 2) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_FSYNC = (1 << 3) * ENABLE_FEATURE_DD_IBS_OBS ,
FLAG_SWAB = (1 << 4) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_IFLAG_SHIFT = 5 , FLAG_SKIP_BYTES = (1 << 5) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_COUNT_BYTES = (1 << 6) * ENABLE_FEATURE_DD_IBS_OBS ,
FLAG_FULLBLOCK = (1 << 7) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_IDIRECT = (1 << 8) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_OFLAG_SHIFT = 9 , FLAG_SEEK_BYTES = (1 << 9) * ENABLE_FEATURE_DD_IBS_OBS ,
FLAG_APPEND = (1 << 10) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_ODIRECT = (1 << 11) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_TWOBUFS = (1 << 12) * ENABLE_FEATURE_DD_IBS_OBS , FLAG_COUNT = 1 << 13 ,
FLAG_STATUS_NONE = 1 << 14 , FLAG_STATUS_NOXFER = 1 << 15
}
Functions
static void dd_output_status (int UNUSED_PARAM cur_signal)
static ssize_t dd_read (void *ibuf, size_t ibs)
static bool write_and_stats (const void *buf, size_t len, size_t obs, const char *filename)
static void * alloc_buf (size_t size)
int dd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
count
#define count (Z.count)
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 123 of file dd.c.
infile
#define infile (Z.infile)
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    /* we have to zero it out because of NOEXEC */ \
    memset(&G, 0, sizeof(G)); \
} while (0)
Definition at line 124 of file dd.c.
obs
#define obs ibs
obuf
#define obuf ibuf
ocount
#define ocount (Z.ocount)
outfile
#define outfile (Z.outfile)
prev_read_size
#define prev_read_size (Z.prev_read_size)
seek
#define seek (Z.seek)
skip
#define skip (Z.skip)
XATOU_SFX
#define XATOU_SFX xatoul_sfx
Definition at line 278 of file dd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ifd
ofd
Definition at line 110 of file dd.c.
      {
     ifd = STDIN_FILENO,
     ofd = STDOUT_FILENO,
 };
anonymous enum
anonymous enum
Enumerator
FLAG_NOTRUNC
FLAG_SYNC
FLAG_NOERROR
FLAG_FSYNC
FLAG_SWAB
FLAG_IFLAG_SHIFT
FLAG_SKIP_BYTES
FLAG_COUNT_BYTES
FLAG_FULLBLOCK
FLAG_IDIRECT
FLAG_OFLAG_SHIFT
FLAG_SEEK_BYTES
FLAG_APPEND
FLAG_ODIRECT
FLAG_TWOBUFS
FLAG_COUNT
FLAG_STATUS_NONE
FLAG_STATUS_NOXFER
Definition at line 130 of file dd.c.
      {
     /* Must be in the same order as OP_conv_XXX! */
     /* (see "flags |= (1 << what)" below) */
     FLAG_NOTRUNC = (1 << 0) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_SYNC    = (1 << 1) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_NOERROR = (1 << 2) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_FSYNC   = (1 << 3) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_SWAB    = (1 << 4) * ENABLE_FEATURE_DD_IBS_OBS,
     /* end of conv flags */
     /* start of input flags */
     FLAG_IFLAG_SHIFT   = 5,
     FLAG_SKIP_BYTES    = (1 << 5) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_COUNT_BYTES   = (1 << 6) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_FULLBLOCK     = (1 << 7) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_IDIRECT       = (1 << 8) * ENABLE_FEATURE_DD_IBS_OBS,
     /* end of input flags */
     /* start of output flags */
     FLAG_OFLAG_SHIFT   = 9,
     FLAG_SEEK_BYTES    = (1 << 9) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_APPEND        = (1 << 10) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_ODIRECT       = (1 << 11) * ENABLE_FEATURE_DD_IBS_OBS,
     /* end of output flags */
     FLAG_TWOBUFS       = (1 << 12) * ENABLE_FEATURE_DD_IBS_OBS,
     FLAG_COUNT         = 1 << 13,
     FLAG_STATUS_NONE   = 1 << 14,
     FLAG_STATUS_NOXFER = 1 << 15,
 };
Function Documentation
alloc_buf()
static void* alloc_buf (size_t size) static
Definition at line 308 of file dd.c.
 {
     /* Important for "{i,o}flag=direct" - buffers must be page aligned */
     if (size >= bb_getpagesize())
         return xmmap_anon(size);
     return xmalloc(size);
 }
References bb_getpagesize, size, xmalloc, and xmmap_anon().
Referenced by dd_main().
dd_main()
int dd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 317 of file dd.c.
 {
     static const char keywords[] ALIGN1 =
         "bs\0""count\0""seek\0""skip\0""if\0""of\0"IF_FEATURE_DD_STATUS("status\0")
 #if ENABLE_FEATURE_DD_IBS_OBS
         "ibs\0""obs\0""conv\0""iflag\0""oflag\0"
 #endif
         ;
 #if ENABLE_FEATURE_DD_IBS_OBS
     static const char conv_words[] ALIGN1 =
         "notrunc\0""sync\0""noerror\0""fsync\0""swab\0";
     static const char iflag_words[] ALIGN1 =
         "skip_bytes\0""count_bytes\0""fullblock\0""direct\0";
     static const char oflag_words[] ALIGN1 =
         "seek_bytes\0append\0""direct\0";
 #endif
 #if ENABLE_FEATURE_DD_STATUS
     static const char status_words[] ALIGN1 =
         "none\0""noxfer\0";
 #endif
     enum {
         OP_bs = 0,
         OP_count,
         OP_seek,
         OP_skip,
         OP_if,
         OP_of,
         IF_FEATURE_DD_STATUS(OP_status,)
 #if ENABLE_FEATURE_DD_IBS_OBS
         OP_ibs,
         OP_obs,
         OP_conv,
         OP_iflag,
         OP_oflag,
         /* Must be in the same order as FLAG_XXX! */
         OP_conv_notrunc = 0,
         OP_conv_sync,
         OP_conv_noerror,
         OP_conv_fsync,
         OP_conv_swab,
     /* Unimplemented conv=XXX: */
     //nocreat       do not create the output file
     //excl          fail if the output file already exists
     //fdatasync     physically write output file data before finishing
     //lcase         change upper case to lower case
     //ucase         change lower case to upper case
     //block         pad newline-terminated records with spaces to cbs-size
     //unblock       replace trailing spaces in cbs-size records with newline
     //ascii         from EBCDIC to ASCII
     //ebcdic        from ASCII to EBCDIC
     //ibm           from ASCII to alternate EBCDIC
     /* Partially implemented: */
     //swab          swap every pair of input bytes: will abort on non-even reads
         OP_iflag_skip_bytes,
         OP_iflag_count_bytes,
         OP_iflag_fullblock,
         OP_iflag_direct,
         OP_oflag_seek_bytes,
         OP_oflag_direct,
 #endif
     };
     smallint exitcode = EXIT_FAILURE;
     int i;
     size_t ibs = 512;
     char *ibuf;
 #if ENABLE_FEATURE_DD_IBS_OBS
     size_t obs = 512;
     char *obuf;
 #else
 # define obs  ibs
 # define obuf ibuf
 #endif
     /* These are all zeroed at once! */
     struct {
         IF_FEATURE_DD_IBS_OBS(size_t ocount;)
         ssize_t prev_read_size; /* for detecting swab failure */
         off_t count;
         off_t seek, skip;
         const char *infile, *outfile;
     } Z;
 #define ocount  (Z.ocount )
 #define prev_read_size (Z.prev_read_size)
 #define count   (Z.count  )
 #define seek    (Z.seek   )
 #define skip    (Z.skip   )
 #define infile  (Z.infile )
 #define outfile (Z.outfile)
     memset(&Z, 0, sizeof(Z));
     INIT_G();
     //fflush_all(); - is this needed because of NOEXEC?
     for (i = 1; argv[i]; i++) {
         int what;
         char *val;
         char *arg = argv[i];
 #if ENABLE_DESKTOP
         /* "dd --". NB: coreutils 6.9 will complain if they see
          * more than one of them. We wouldn't. */
         if (arg[0] == '-' && arg[1] == '-' && arg[2] == '\0')
             continue;
 #endif
         val = strchr(arg, '=');
         if (val == NULL)
             bb_show_usage();
         *val = '\0';
         what = index_in_strings(keywords, arg);
         if (what < 0)
             bb_show_usage();
         /* *val = '='; - to preserve ps listing? */
         val++;
 #if ENABLE_FEATURE_DD_IBS_OBS
         if (what == OP_ibs) {
             /* Must fit into positive ssize_t */
             ibs = xatoul_range_sfx(val, 1, ((size_t)-1L)/2, cwbkMG_suffixes);
             /*continue;*/
         }
         if (what == OP_obs) {
             obs = xatoul_range_sfx(val, 1, ((size_t)-1L)/2, cwbkMG_suffixes);
             /*continue;*/
         }
         if (what == OP_conv) {
             G.flags |= parse_comma_flags(val, conv_words, "conv");
             /*continue;*/
         }
         if (what == OP_iflag) {
             G.flags |= parse_comma_flags(val, iflag_words, "iflag") << FLAG_IFLAG_SHIFT;
             /*continue;*/
         }
         if (what == OP_oflag) {
             G.flags |= parse_comma_flags(val, oflag_words, "oflag") << FLAG_OFLAG_SHIFT;
             /*continue;*/
         }
 #endif
         if (what == OP_bs) {
             ibs = xatoul_range_sfx(val, 1, ((size_t)-1L)/2, cwbkMG_suffixes);
             obs = ibs;
             /*continue;*/
         }
         /* These can be large: */
         if (what == OP_count) {
             G.flags |= FLAG_COUNT;
             count = XATOU_SFX(val, cwbkMG_suffixes);
             /*continue;*/
         }
         if (what == OP_seek) {
             seek = XATOU_SFX(val, cwbkMG_suffixes);
             /*continue;*/
         }
         if (what == OP_skip) {
             skip = XATOU_SFX(val, cwbkMG_suffixes);
             /*continue;*/
         }
         if (what == OP_if) {
             infile = val;
             /*continue;*/
         }
         if (what == OP_of) {
             outfile = val;
             /*continue;*/
         }
 #if ENABLE_FEATURE_DD_STATUS
         if (what == OP_status) {
             int n;
             n = index_in_strings(status_words, val);
             if (n < 0)
                 bb_error_msg_and_die(bb_msg_invalid_arg_to, val, "status");
             G.flags |= FLAG_STATUS_NONE << n;
             /*continue;*/
         }
 #endif
     } /* end of "for (argv[i])" */
     ibuf = alloc_buf(ibs);
     obuf = ibuf;
 #if ENABLE_FEATURE_DD_IBS_OBS
     if (ibs != obs) {
         G.flags |= FLAG_TWOBUFS;
         obuf = alloc_buf(obs);
     }
 #endif
 #if ENABLE_FEATURE_DD_SIGNAL_HANDLING
     signal_SA_RESTART_empty_mask(SIGUSR1, dd_output_status);
 #endif
 #if ENABLE_FEATURE_DD_THIRD_STATUS_LINE
     G.begin_time_us = monotonic_us();
 #endif
     if (infile) {
         int iflag = O_RDONLY;
 #if ENABLE_FEATURE_DD_IBS_OBS
         if (G.flags & FLAG_IDIRECT) {
 # ifdef O_DIRECT
             iflag |= O_DIRECT;
 # else
             bb_error_msg_and_die("O_DIRECT not supported on this platform");
 # endif
         }
 #endif
         xmove_fd(xopen(infile, iflag), ifd);
     } else {
         infile = bb_msg_standard_input;
     }
     if (outfile) {
         int oflag = O_WRONLY | O_CREAT;
         if (!seek && !(G.flags & FLAG_NOTRUNC))
             oflag |= O_TRUNC;
         if (G.flags & FLAG_APPEND)
             oflag |= O_APPEND;
 #if ENABLE_FEATURE_DD_IBS_OBS
         if (G.flags & FLAG_ODIRECT) {
 # ifdef O_DIRECT
             oflag |= O_DIRECT;
 # else
             bb_error_msg_and_die("O_DIRECT not supported on this platform");
 # endif
         }
 #endif
         xmove_fd(xopen(outfile, oflag), ofd);
         if (seek && !(G.flags & FLAG_NOTRUNC)) {
             size_t blocksz = (G.flags & FLAG_SEEK_BYTES) ? 1 : obs;
             if (ftruncate(ofd, seek * blocksz) < 0) {
                 struct stat st;
                 if (fstat(ofd, &st) < 0
                  || S_ISREG(st.st_mode)
                  || S_ISDIR(st.st_mode)
                 ) {
                     goto die_outfile;
                 }
             }
         }
     } else {
         outfile = bb_msg_standard_output;
     }
     if (skip) {
         size_t blocksz = (G.flags & FLAG_SKIP_BYTES) ? 1 : ibs;
         if (lseek(ifd, skip * blocksz, SEEK_CUR) < 0) {
             do {
                 ssize_t n = dd_read(ibuf, blocksz);
                 if (n < 0)
                     goto die_infile;
                 if (n == 0)
                     break;
             } while (--skip != 0);
         }
     }
     if (seek) {
         size_t blocksz = (G.flags & FLAG_SEEK_BYTES) ? 1 : obs;
         if (lseek(ofd, seek * blocksz, SEEK_CUR) < 0)
             goto die_outfile;
     }
     while (1) {
         ssize_t n = ibs;
         if (G.flags & FLAG_COUNT) {
             if (count == 0)
                 break;
             if ((G.flags & FLAG_COUNT_BYTES) && count < ibs)
                 n = count;
         }
         n = dd_read(ibuf, n);
         if (n == 0)
             break;
         if (n < 0) {
             /* "Bad block" */
             if (!(G.flags & FLAG_NOERROR))
                 goto die_infile;
             bb_simple_perror_msg(infile);
             /* GNU dd with conv=noerror skips over bad blocks */
             xlseek(ifd, ibs, SEEK_CUR);
             /* conv=noerror,sync writes NULs,
              * conv=noerror just ignores input bad blocks */
             n = 0;
         }
         if (G.flags & FLAG_SWAB) {
             uint16_t *p16;
             ssize_t n2;
             /* Our code allows only last read to be odd-sized */
             if (prev_read_size & 1)
                 bb_error_msg_and_die("can't swab %lu byte buffer",
                         (unsigned long)prev_read_size);
             prev_read_size = n;
             /* If n is odd, last byte is not swapped:
              *  echo -n "qwe" | dd conv=swab
              * prints "wqe".
              */
             p16 = (void*) ibuf;
             n2 = (n >> 1);
             while (--n2 >= 0) {
                 *p16 = bswap_16(*p16);
                 p16++;
             }
         }
         count -= (G.flags & FLAG_COUNT_BYTES) ? n : 1;
         if ((size_t)n == ibs)
             G.in_full++;
         else {
             G.in_part++;
             if (G.flags & FLAG_SYNC) {
                 memset(ibuf + n, 0, ibs - n);
                 n = ibs;
             }
         }
 #if ENABLE_FEATURE_DD_IBS_OBS
         if (G.flags & FLAG_TWOBUFS) {
             char *tmp = ibuf;
             while (n) {
                 size_t d = obs - ocount;
                 if (d > (size_t)n)
                     d = n;
                 memcpy(obuf + ocount, tmp, d);
                 n -= d;
                 tmp += d;
                 ocount += d;
                 if (ocount == obs) {
                     if (write_and_stats(obuf, obs, obs, outfile))
                         goto out_status;
                     ocount = 0;
                 }
             }
         } else
 #endif
         {
             if (write_and_stats(ibuf, n, obs, outfile))
                 goto out_status;
         }
     }
     if (G.flags & FLAG_FSYNC) {
         if (fsync(ofd) < 0)
             goto die_outfile;
     }
 #if ENABLE_FEATURE_DD_IBS_OBS
     if (ocount != 0) {
         if (write_and_stats(obuf, ocount, obs, outfile))
             goto out_status;
     }
 #endif
     if (close(ifd) < 0) {
  die_infile:
         bb_simple_perror_msg_and_die(infile);
     }
     if (close(ofd) < 0) {
  die_outfile:
         bb_simple_perror_msg_and_die(outfile);
     }
     exitcode = EXIT_SUCCESS;
  out_status:
     if (!ENABLE_FEATURE_DD_STATUS || !(G.flags & FLAG_STATUS_NONE))
         dd_output_status(0);
 #if 0 /* can't just free(), they can be mmap()ed */
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(obuf);
         if (G.flags & FLAG_TWOBUFS)
             free(ibuf);
     }
 #endif
     return exitcode;
 }
References ALIGN1, alloc_buf(), argv, bb_error_msg_and_die(), bb_show_usage(), bb_simple_perror_msg(), bswap_16, count, cwbkMG_suffixes, dd_output_status(), dd_read(), EXIT_FAILURE, exitcode, FLAG_APPEND, FLAG_COUNT, FLAG_COUNT_BYTES, FLAG_IDIRECT, FLAG_IFLAG_SHIFT, FLAG_NOERROR, FLAG_NOTRUNC, FLAG_ODIRECT, FLAG_OFLAG_SHIFT, FLAG_SEEK_BYTES, FLAG_SKIP_BYTES, FLAG_STATUS_NONE, FLAG_SWAB, FLAG_SYNC, FLAG_TWOBUFS, fstat(), ftruncate(), G, i, if(), ifd, iflag, index_in_strings(), infile, INIT_G, lseek(), memcpy, memset, monotonic_us(), n, NULL, O_APPEND, O_CREAT, O_DIRECT, O_RDONLY, O_TRUNC, O_WRONLY, obs, obuf, ocount, ofd, off_t, outfile, prev_read_size, S_ISDIR, S_ISREG, seek, SEEK_CUR, signal_SA_RESTART_empty_mask(), SIGUSR1, skip, strchr(), val, write_and_stats(), XATOU_SFX, xlseek(), xmove_fd(), and xopen().
dd_output_status()
static void dd_output_status (int UNUSED_PARAM cur_signal) static
Definition at line 158 of file dd.c.
 {
 #if ENABLE_FEATURE_DD_THIRD_STATUS_LINE
     double seconds;
     unsigned long long bytes_sec;
     unsigned long long now_us = monotonic_us(); /* before fprintf */
 #endif
     /* Deliberately using %u, not %d */
     fprintf(stderr, "%"OFF_FMT"u+%"OFF_FMT"u records in\n"
             "%"OFF_FMT"u+%"OFF_FMT"u records out\n",
             G.in_full, G.in_part,
             G.out_full, G.out_part);
 #if ENABLE_FEATURE_DD_THIRD_STATUS_LINE
 # if ENABLE_FEATURE_DD_STATUS
     if (G.flags & FLAG_STATUS_NOXFER) /* status=noxfer active? */
         return;
     //TODO: should status=none make dd stop reacting to USR1 entirely?
     //So far we react to it (we print the stats),
     //status=none only suppresses final, non-USR1 generated status message.
 # endif
     fprintf(stderr, /*G.total_bytes < 1024
                 ? "%llu bytes copied, " : */ "%llu bytes (%sB) copied, "
             , G.total_bytes,
             /* show fractional digit, use suffixes */
             make_human_readable_str(G.total_bytes, 1, 0)
     );
     /* Corner cases:
      * ./busybox dd </dev/null >/dev/null
      * ./busybox dd bs=1M count=2000 </dev/zero >/dev/null
      * (echo DONE) | ./busybox dd >/dev/null
      * (sleep 1; echo DONE) | ./busybox dd >/dev/null
      */
     seconds = (now_us - G.begin_time_us) / 1000000.0;
     bytes_sec = G.total_bytes / seconds;
     fprintf(stderr, "%f seconds, %sB/s\n",
             seconds,
             /* show fractional digit, use suffixes */
             make_human_readable_str(bytes_sec, 1, 0)
     );
 #endif
 }
References FLAG_STATUS_NOXFER, fprintf(), G, make_human_readable_str(), monotonic_us(), OFF_FMT, and stderr.
Referenced by dd_main().
dd_read()
static ssize_t dd_read (void * ibuf, size_t ibs) static
Definition at line 218 of file dd.c.
 {
     ssize_t n;
 #if ENABLE_FEATURE_DD_IBS_OBS
  read_again:
     if (G.flags & FLAG_FULLBLOCK)
         n = full_read(ifd, ibuf, ibs);
     else
 #endif
         n = safe_read(ifd, ibuf, ibs);
 #if ENABLE_FEATURE_DD_IBS_OBS
 # ifdef O_DIRECT
     if (n < 0 && (G.flags & FLAG_IDIRECT) && clear_O_DIRECT(ifd))
         goto read_again;
 # endif
 #endif
     return n;
 }
References FLAG_FULLBLOCK, FLAG_IDIRECT, full_read(), G, ifd, n, and safe_read().
Referenced by dd_main().
write_and_stats()
static bool write_and_stats (const void * buf, size_t len, size_t obs, const char * filename) static
Definition at line 238 of file dd.c.
 {
     ssize_t n;
  IF_FEATURE_DD_IBS_OBS(write_again:)
     n = full_write(ofd, buf, len);
 #if ENABLE_FEATURE_DD_IBS_OBS
 # ifdef O_DIRECT
     if (n < 0 && (G.flags & FLAG_ODIRECT) && clear_O_DIRECT(ofd))
         goto write_again;
 # endif
 #endif
 #if ENABLE_FEATURE_DD_THIRD_STATUS_LINE
     if (n > 0)
         G.total_bytes += n;
 #endif
     if ((size_t)n == obs) {
         G.out_full++;
         return 0;
     }
     if ((size_t)n == len) {
         G.out_part++;
         return 0;
     }
     /* n is < len (and possibly is -1).
      * Even if n >= 0, errno is usually set correctly.
      * For example, if writing to block device and getting ENOSPC,
      * full_write() first sees a short write, then tries to write
      * the remainder and gets errno set to ENOSPC.
      * It returns n > 0 (the amount which it did write).
      */
     bb_perror_msg("error writing '%s'", filename);
     return 1;
 }
References bb_perror_msg(), buf, filename, FLAG_ODIRECT, full_write(), G, len, n, obs, and ofd.
Referenced by dd_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING