Fennix Userspace: Userspace/apps/base/busybox/libbb/change_identity.c File Reference
change_identity.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC change_identity (const struct passwd *pw)
Function Documentation
change_identity()
void FAST_FUNC change_identity (const struct passwd * pw)
Definition at line 33 of file change_identity.c.
 {
     int res;
     res = initgroups(pw->pw_name, pw->pw_gid);
     endgrent(); /* helps to close a fd used internally by libc */
     if (res != 0) {
         /*
          * If initgroups() fails because a system call is unimplemented
          * then we are running on a Linux kernel compiled without multiuser
          * support (CONFIG_MULTIUSER is not defined).
          *
          * If we are running without multiuser support *and* the target uid
          * already matches the current uid then we can skip the change of
          * identity.
          */
         if (errno == ENOSYS && pw->pw_uid == getuid()) {
             return;
         }
         bb_simple_perror_msg_and_die("can't set groups");
     }
     xsetgid(pw->pw_gid);
     xsetuid(pw->pw_uid);
 }
References bb_simple_perror_msg_and_die(), endgrent(), ENOSYS, errno, getuid, initgroups, pw, passwd::pw_gid, passwd::pw_name, passwd::pw_uid, xsetgid(), and xsetuid().
Referenced by change_user(), edit_file(), ftpd_main(), inetd_main(), login_main(), start_stop_daemon_main(), and su_main().