Fennix: Userspace/apps/base/busybox/libbb/find_mount_point.c File Reference
find_mount_point.c File Reference
#include "libbb.h"
#include <mntent.h>
Functions
struct mntent *FAST_FUNC find_mount_point (const char *name, int subdir_too)
Function Documentation
find_mount_point()
struct mntent* FAST_FUNC find_mount_point (const char * name, int subdir_too)
Definition at line 19 of file find_mount_point.c.
 {
     struct stat s;
     FILE *mtab_fp;
     struct mntent *mountEntry;
     dev_t devno_of_name;
     bool block_dev;
     if (stat(name, &s) != 0)
         return NULL;
     devno_of_name = s.st_dev;
     block_dev = 0;
     /* Why S_ISCHR? - UBI volumes use char devices, not block */
     if (S_ISBLK(s.st_mode) || S_ISCHR(s.st_mode)) {
         devno_of_name = s.st_rdev;
         block_dev = 1;
     }
     mtab_fp = setmntent(bb_path_mtab_file, "r");
     if (!mtab_fp)
         return NULL;
     while ((mountEntry = getmntent(mtab_fp)) != NULL) {
         /* rootfs mount in Linux 2.6 exists always,
          * and it makes sense to always ignore it.
          * Otherwise people can't reference their "real" root! */
         if (ENABLE_FEATURE_SKIP_ROOTFS && strcmp(mountEntry->mnt_fsname, "rootfs") == 0)
             continue;
         if (strcmp(name, mountEntry->mnt_dir) == 0
          || strcmp(name, mountEntry->mnt_fsname) == 0
         ) { /* String match. */
             break;
         }
         if (!(subdir_too || block_dev))
             continue;
         /* Is device's dev_t == name's dev_t? */
         if (mountEntry->mnt_fsname[0] == '/'
         /* ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          * avoid stat'ing "sysfs", "proc", "none" and such,
          * useless at best, can stat unrelated files at worst.
          */
          && stat(mountEntry->mnt_fsname, &s) == 0
          && s.st_rdev == devno_of_name
         ) {
             break;
         }
         /* Match the directory's mount point. */
         if (stat(mountEntry->mnt_dir, &s) == 0
          && s.st_dev == devno_of_name
         ) {
             break;
         }
     }
     endmntent(mtab_fp);
     return mountEntry;
 }
References bb_path_mtab_file, dev_t, endmntent(), getmntent(), mntent::mnt_dir, mntent::mnt_fsname, NULL, s, S_ISBLK, S_ISCHR, setmntent(), stat(), and strcmp.
Referenced by check_mount(), df_main(), mkfs_ext2_main(), mkfs_minix_main(), mkfs_reiser_main(), mkfs_vfat_main(), and mount_main().