Fennix Kernel: Kernel/tasking/signal.cpp File Reference
signal.cpp File Reference
#include <signal.hpp>
#include <dumper.hpp>
#include <task.hpp>
#include <errno.h>
#include "../kernel.h"
Namespaces
Tasking
Functions
SignalDispositions GetDefaultSignalDisposition (Signals sig)
int ConvertSignalToLinux (Signals sig)
Variables
uintptr_t _sig_native_trampoline_start
uintptr_t _sig_native_trampoline_end
uintptr_t _sig_linux_trampoline_start
uintptr_t _sig_linux_trampoline_end
struct {
Signals Signal
SignalDispositions Disposition
} SignalDisposition []
Function Documentation
ConvertSignalToLinux()
int ConvertSignalToLinux (Signals sig)
Definition at line 538 of file syscall.cpp.
 {
     if (sig >= SIGRTMIN && sig <= SIGRTMAX)
         return sig; /* We ignore for now */
     foreach (auto &mapping in signalMapping)
     {
         if (mapping.nativeSignal == sig)
         {
             // debug("Converted \"%s\"(%d) to \"%s\"(%d)",
             //    sigStr[mapping.nativeSignal], sig,
             //    lSigStr[mapping.linuxSignal], mapping.linuxSignal);
             return mapping.linuxSignal;
         }
     }
     debug("Unknown signal %d", sig);
     // assert(!"Unknown signal");
     return SIG_NULL;
 }
References debug, SIG_NULL, signalMapping, SIGRTMAX, and SIGRTMIN.
Referenced by ConvertMaskToLinux(), Tasking::Signal::HandleSignal(), linux_wait4(), and Tasking::Signal::MakeExitCode().
GetDefaultSignalDisposition()
SignalDispositions GetDefaultSignalDisposition (Signals sig)
Definition at line 184 of file signal.cpp.
 {
     foreach (auto var in SignalDisposition)
     {
         if (var.Signal == sig)
             return var.Disposition;
     }
     error("Invalid signal: %d", sig);
     return SIG_TERM;
 }
References error, SIG_TERM, and SignalDisposition.
Referenced by Tasking::Signal::SetAction().
Variable Documentation
_sig_linux_trampoline_end
uintptr_t _sig_linux_trampoline_end
Definition at line 111 of file signal.cpp.
Referenced by Tasking::Signal::InitTrampoline().
_sig_linux_trampoline_start
uintptr_t _sig_linux_trampoline_start
Definition at line 111 of file signal.cpp.
Referenced by Tasking::Signal::InitTrampoline().
_sig_native_trampoline_end
uintptr_t _sig_native_trampoline_end
Definition at line 110 of file signal.cpp.
Referenced by Tasking::Signal::InitTrampoline().
_sig_native_trampoline_start
uintptr_t _sig_native_trampoline_start
Definition at line 110 of file signal.cpp.
Referenced by Tasking::Signal::InitTrampoline().
const { ... } SignalDisposition[]
Referenced by GetDefaultSignalDisposition().