Fennix: Userspace/musl/src/passwd/getpw_r.c File Reference
getpw_r.c File Reference
#include "pwf.h"
#include <pthread.h>
Macros
#define FIX(x) (pw->pw_##x = pw->pw_##x-line+buf)
Functions
static int getpw_r (const char *name, uid_t uid, struct passwd *pw, char *buf, size_t size, struct passwd **res)
int getpwnam_r (const char *name, struct passwd *pw, char *buf, size_t size, struct passwd **res)
int getpwuid_r (uid_t uid, struct passwd *pw, char *buf, size_t size, struct passwd **res)
Macro Definition Documentation
FIX
#define FIX (x) (pw->pw_##x = pw->pw_##x-line+buf)
Definition at line 4 of file getpw_r.c.
Function Documentation
getpw_r()
static int getpw_r (const char * name, uid_t uid, struct passwd * pw, char * buf, size_t size, struct passwd ** res) static
Definition at line 6 of file getpw_r.c.
 {
     char *line = 0;
     size_t len = 0;
     int rv = 0;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     rv = __getpw_a(name, uid, pw, &line, &len, res);
     if (*res && size < len) {
         *res = 0;
         rv = ERANGE;
     }
     if (*res) {
         memcpy(buf, line, len);
         FIX(name);
         FIX(passwd);
         FIX(gecos);
         FIX(dir);
         FIX(shell);
     }
     free(line);
     pthread_setcancelstate(cs, 0);
     if (rv) errno = rv;
     return rv;
 }
References __getpw_a(), buf, dir, ERANGE, errno, FIX, free, len, memcpy, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pw, and size.
Referenced by getpwnam_r(), and getpwuid_r().
getpwnam_r()
int getpwnam_r (const char * name, struct passwd * pw, char * buf, size_t size, struct passwd ** res)
Definition at line 34 of file getpw_r.c.
 {
     return getpw_r(name, 0, pw, buf, size, res);
 }
References buf, getpw_r(), pw, and size.
getpwuid_r()
int getpwuid_r (uid_t uid, struct passwd * pw, char * buf, size_t size, struct passwd ** res)
Definition at line 39 of file getpw_r.c.
 {
     return getpw_r(0, uid, pw, buf, size, res);
 }
References buf, getpw_r(), pw, and size.
Referenced by cuserid(), and expand_tilde().