Fennix: Kernel/include/ini.h File Reference
ini.h File Reference
Macros
#define INI_GLOBAL_SECTION (0)
#define INI_NOT_FOUND (-1)
Typedefs
typedef struct ini_t ini_t
Functions
ini_t * ini_create (void *memctx)
ini_t * ini_load (char const *data, void *memctx)
int ini_save (ini_t const *ini, char *data, int size)
void ini_destroy (ini_t *ini)
int ini_section_count (ini_t const *ini)
char const * ini_section_name (ini_t const *ini, int section)
int ini_property_count (ini_t const *ini, int section)
char const * ini_property_name (ini_t const *ini, int section, int property)
char const * ini_property_value (ini_t const *ini, int section, int property)
int ini_find_section (ini_t const *ini, char const *name, int name_length)
int ini_find_property (ini_t const *ini, int section, char const *name, int name_length)
int ini_section_add (ini_t *ini, char const *name, int length)
void ini_property_add (ini_t *ini, int section, char const *name, int name_length, char const *value, int value_length)
void ini_section_remove (ini_t *ini, int section)
void ini_property_remove (ini_t *ini, int section, int property)
void ini_section_name_set (ini_t *ini, int section, char const *name, int length)
void ini_property_name_set (ini_t *ini, int section, int property, char const *name, int length)
void ini_property_value_set (ini_t *ini, int section, int property, char const *value, int length)
Macro Definition Documentation
INI_GLOBAL_SECTION
#define INI_GLOBAL_SECTION (0)
Definition at line 18 of file ini.h.
INI_NOT_FOUND
#define INI_NOT_FOUND (-1)
Definition at line 19 of file ini.h.
Typedef Documentation
ini_t
typedef struct ini_t ini_t
Definition at line 1 of file ini.h.
Function Documentation
ini_create()
ini_t* ini_create (void * memctx)
ini_destroy()
void ini_destroy (ini_t * ini)
Referenced by linux_uname().
ini_find_property()
int ini_find_property (ini_t const * ini, int section, char const * name, int name_length)
Referenced by linux_uname().
ini_find_section()
int ini_find_section (ini_t const * ini, char const * name, int name_length)
Referenced by linux_uname().
ini_load()
ini_t* ini_load (char const * data, void * memctx)
Referenced by linux_uname().
ini_property_add()
void ini_property_add (ini_t * ini, int section, char const * name, int name_length, char const * value, int value_length)
ini_property_count()
int ini_property_count (ini_t const * ini, int section)
ini_property_name()
char const* ini_property_name (ini_t const * ini, int section, int property)
ini_property_name_set()
void ini_property_name_set (ini_t * ini, int section, int property, char const * name, int length)
ini_property_remove()
void ini_property_remove (ini_t * ini, int section, int property)
ini_property_value()
char const* ini_property_value (ini_t const * ini, int section, int property)
Referenced by linux_uname().
ini_property_value_set()
void ini_property_value_set (ini_t * ini, int section, int property, char const * value, int length)
ini_save()
int ini_save (ini_t const * ini, char * data, int size)
ini_section_add()
int ini_section_add (ini_t * ini, char const * name, int length)
ini_section_count()
int ini_section_count (ini_t const * ini)
ini_section_name()
char const* ini_section_name (ini_t const * ini, int section)
ini_section_name_set()
void ini_section_name_set (ini_t * ini, int section, char const * name, int length)
ini_section_remove()
void ini_section_remove (ini_t * ini, int section)