Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/r_segs.h File Reference
r_segs.h File Reference
Functions
void R_RenderMaskedSegRange (drawseg_t *ds, int x1, int x2)
Function Documentation
R_RenderMaskedSegRange()
void R_RenderMaskedSegRange (drawseg_t * ds, int x1, int x2)
Definition at line 96 of file r_segs.c.
 {
     unsigned    index;
     column_t*   col;
     int     lightnum;
     int     texnum;
     // Calculate light table.
     // Use different light tables
     //   for horizontal / vertical / diagonal. Diagonal?
     // OPTIMIZE: get rid of LIGHTSEGSHIFT globally
     curline = ds->curline;
     frontsector = curline->frontsector;
     backsector = curline->backsector;
     texnum = texturetranslation[curline->sidedef->midtexture];
     lightnum = (frontsector->lightlevel >> LIGHTSEGSHIFT)+extralight;
     if (curline->v1->y == curline->v2->y)
     lightnum--;
     else if (curline->v1->x == curline->v2->x)
     lightnum++;
     if (lightnum < 0)
     walllights = scalelight[0];
     else if (lightnum >= LIGHTLEVELS)
     walllights = scalelight[LIGHTLEVELS-1];
     else
     walllights = scalelight[lightnum];
     maskedtexturecol = ds->maskedtexturecol;
     rw_scalestep = ds->scalestep;
     spryscale = ds->scale1 + (x1 - ds->x1)*rw_scalestep;
     mfloorclip = ds->sprbottomclip;
     mceilingclip = ds->sprtopclip;
     // find positioning
     if (curline->linedef->flags & ML_DONTPEGBOTTOM)
     {
     dc_texturemid = frontsector->floorheight > backsector->floorheight
         ? frontsector->floorheight : backsector->floorheight;
     dc_texturemid = dc_texturemid + textureheight[texnum] - viewz;
     }
     else
     {
     dc_texturemid =frontsector->ceilingheight<backsector->ceilingheight
         ? frontsector->ceilingheight : backsector->ceilingheight;
     dc_texturemid = dc_texturemid - viewz;
     }
     dc_texturemid += curline->sidedef->rowoffset;
     if (fixedcolormap)
     dc_colormap = fixedcolormap;
     // draw the columns
     for (dc_x = x1 ; dc_x <= x2 ; dc_x++)
     {
     // calculate lighting
     if (maskedtexturecol[dc_x] != __SHRT_MAX__)
     {
         if (!fixedcolormap)
         {
         index = spryscale>>LIGHTSCALESHIFT;
         if (index >=  MAXLIGHTSCALE )
             index = MAXLIGHTSCALE-1;
         dc_colormap = walllights[index];
         }
         sprtopscreen = centeryfrac - FixedMul(dc_texturemid, spryscale);
         dc_iscale = 0xffffffffu / (unsigned)spryscale;
         // draw the texture
         col = (column_t *)(
         (byte *)R_GetColumn(texnum,maskedtexturecol[dc_x]) -3);
         R_DrawMaskedColumn (col);
         maskedtexturecol[dc_x] = __SHRT_MAX__;
     }
     spryscale += rw_scalestep;
     }
 }
References backsector, seg_t::backsector, sector_t::ceilingheight, centeryfrac, curline, drawseg_s::curline, dc_colormap, dc_iscale, dc_texturemid, dc_x, extralight, fixedcolormap, FixedMul(), line_s::flags, sector_t::floorheight, frontsector, seg_t::frontsector, index(), sector_t::lightlevel, LIGHTLEVELS, LIGHTSCALESHIFT, LIGHTSEGSHIFT, seg_t::linedef, drawseg_s::maskedtexturecol, maskedtexturecol, MAXLIGHTSCALE, mceilingclip, mfloorclip, side_t::midtexture, ML_DONTPEGBOTTOM, R_DrawMaskedColumn(), R_GetColumn(), side_t::rowoffset, rw_scalestep, drawseg_s::scale1, scalelight, drawseg_s::scalestep, seg_t::sidedef, drawseg_s::sprbottomclip, drawseg_s::sprtopclip, sprtopscreen, spryscale, textureheight, texturetranslation, seg_t::v1, seg_t::v2, viewz, walllights, vertex_t::x, drawseg_s::x1, and vertex_t::y.
Referenced by R_DrawMasked(), and R_DrawSprite().