Fennix: Userspace/musl/src/stdio/ofl.c File Reference
ofl.c File Reference
#include "stdio_impl.h"
#include "lock.h"
#include "fork_impl.h"
Functions
FILE ** __ofl_lock ()
void __ofl_unlock ()
Variables
static FILE * ofl_head
static volatile int ofl_lock [1]
volatile int *const __stdio_ofl_lockptr = ofl_lock
Function Documentation
__ofl_lock()
FILE** __ofl_lock (void)
Definition at line 9 of file ofl.c.
 {
     LOCK(ofl_lock);
     return &ofl_head;
 }
References LOCK, ofl_head, and ofl_lock.
Referenced by __ofl_add(), __pthread_create(), __stdio_exit(), fclose(), fflush(), and popen().
__ofl_unlock()
void __ofl_unlock (void)
Definition at line 15 of file ofl.c.
 {
     UNLOCK(ofl_lock);
 }
References ofl_lock, and UNLOCK.
Referenced by __ofl_add(), __pthread_create(), fclose(), fflush(), and popen().
Variable Documentation
__stdio_ofl_lockptr
volatile int* const __stdio_ofl_lockptr = ofl_lock
Definition at line 7 of file ofl.c.
ofl_head
FILE* ofl_head static
Definition at line 5 of file ofl.c.
Referenced by __ofl_lock().
ofl_lock
volatile int ofl_lock[1] static
Definition at line 6 of file ofl.c.
Referenced by __ofl_lock(), and __ofl_unlock().