Fennix: Userspace/apps/base/bash/lib/readline/rldefs.h File Reference
rldefs.h File Reference
#include "rlstdc.h"
#include <strings.h>
#include "rlconf.h"
Macros
#define NEW_TTY_DRIVER
#define no_mode -1
#define vi_mode 0
#define emacs_mode 1
#define RL_IM_INSERT 1
#define RL_IM_OVERWRITE 0
#define RL_IM_DEFAULT RL_IM_INSERT
#define FUNCTION_TO_KEYMAP(map, key) (Keymap)(map[key].function)
#define KEYMAP_TO_FUNCTION(data) (rl_command_func_t *)(data)
#define savestring(x) strcpy ((char *)xmalloc (1 + strlen (x)), (x))
#define NO_BELL 0
#define AUDIBLE_BELL 1
#define VISIBLE_BELL 2
#define FTO 1 /* forward to */
#define BTO -1 /* backward to */
#define FFIND 2 /* forward find */
#define BFIND -2 /* backward find */
#define RL_QF_SINGLE_QUOTE 0x01
#define RL_QF_DOUBLE_QUOTE 0x02
#define RL_QF_BACKSLASH 0x04
#define RL_QF_OTHER_QUOTE 0x08
#define DEFAULT_BUFFER_SIZE 256
#define STREQ(a, b) (((a)[0] == (b)[0]) && (strcmp ((a), (b)) == 0))
#define STREQN(a, b, n)
#define RL_STRLEN(s) (((s) && (s)[0]) ? ((s)[1] ? ((s)[2] ? strlen(s) : 2) : 1) : 0)
#define FREE(x) if (x) free (x)
#define SWAP(s, e) do { int t; t = s; s = e; e = t; } while (0)
Functions
char * strchr ()
char * strrchr ()
int _rl_stricmp (const char *, const char *)
int _rl_strnicmp (const char *, const char *, int)
char * _rl_strpbrk (const char *, const char *)
Macro Definition Documentation
AUDIBLE_BELL
#define AUDIBLE_BELL 1
Definition at line 124 of file rldefs.h.
BFIND
#define BFIND -2 /* backward find */
Definition at line 132 of file rldefs.h.
BTO
#define BTO -1 /* backward to */
Definition at line 130 of file rldefs.h.
DEFAULT_BUFFER_SIZE
#define DEFAULT_BUFFER_SIZE 256
Definition at line 143 of file rldefs.h.
emacs_mode
#define emacs_mode 1
Definition at line 95 of file rldefs.h.
FFIND
#define FFIND 2 /* forward find */
Definition at line 131 of file rldefs.h.
FREE
#define FREE (x) if (x) free (x)
Definition at line 156 of file rldefs.h.
FTO
#define FTO 1 /* forward to */
Definition at line 129 of file rldefs.h.
FUNCTION_TO_KEYMAP
#define FUNCTION_TO_KEYMAP (map, key) (Keymap)(map[key].function)
Definition at line 114 of file rldefs.h.
KEYMAP_TO_FUNCTION
#define KEYMAP_TO_FUNCTION (data) (rl_command_func_t *)(data)
Definition at line 115 of file rldefs.h.
NEW_TTY_DRIVER
#define NEW_TTY_DRIVER
Definition at line 44 of file rldefs.h.
NO_BELL
#define NO_BELL 0
Definition at line 123 of file rldefs.h.
no_mode
#define no_mode -1
Definition at line 93 of file rldefs.h.
RL_IM_DEFAULT
#define RL_IM_DEFAULT RL_IM_INSERT
Definition at line 102 of file rldefs.h.
RL_IM_INSERT
#define RL_IM_INSERT 1
Definition at line 99 of file rldefs.h.
RL_IM_OVERWRITE
#define RL_IM_OVERWRITE 0
Definition at line 100 of file rldefs.h.
RL_QF_BACKSLASH
#define RL_QF_BACKSLASH 0x04
Definition at line 139 of file rldefs.h.
RL_QF_DOUBLE_QUOTE
#define RL_QF_DOUBLE_QUOTE 0x02
Definition at line 138 of file rldefs.h.
RL_QF_OTHER_QUOTE
#define RL_QF_OTHER_QUOTE 0x08
Definition at line 140 of file rldefs.h.
RL_QF_SINGLE_QUOTE
#define RL_QF_SINGLE_QUOTE 0x01
Definition at line 137 of file rldefs.h.
RL_STRLEN
#define RL_STRLEN (s) (((s) && (s)[0]) ? ((s)[1] ? ((s)[2] ? strlen(s) : 2) : 1) : 0)
Definition at line 152 of file rldefs.h.
savestring
#define savestring (x) strcpy ((char *)xmalloc (1 + strlen (x)), (x))
Definition at line 119 of file rldefs.h.
STREQ
#define STREQ (a, b) (((a)[0] == (b)[0]) && (strcmp ((a), (b)) == 0))
Definition at line 146 of file rldefs.h.
STREQN
#define STREQN (a, b, n)
Value:
                    (((n) == 0) ? (1) \
                    : ((a)[0] == (b)[0]) && (strncmp ((a), (b), (n)) == 0))
Definition at line 147 of file rldefs.h.
SWAP
#define SWAP (s, e) do { int t; t = s; s = e; e = t; } while (0)
Definition at line 160 of file rldefs.h.
vi_mode
#define vi_mode 0
Definition at line 94 of file rldefs.h.
VISIBLE_BELL
#define VISIBLE_BELL 2
Definition at line 125 of file rldefs.h.
Function Documentation
_rl_stricmp()
int _rl_stricmp (const char * string1, const char * string2)
Definition at line 397 of file util.c.
 {
   register const char *s1;
   register const char *s2;
   register int d;
   s1 = string1;
   s2 = string2;
   if (s1 == s2)
     return 0;
   while ((d = _rl_to_lower (*s1) - _rl_to_lower (*s2)) == 0)
     {
       if (*s1++ == '\0')
         return 0;
       s2++;
     }
   return (d);
 }
References _rl_to_lower(), s1, and s2.
Referenced by _rl_get_keymap_by_name(), _rl_get_string_variable_value(), bool_to_int(), find_boolean_var(), find_string_var(), hack_special_boolean_var(), handle_parser_directive(), parser_if(), rl_named_function(), rl_parse_and_bind(), stat_char(), and sv_bell_style().
_rl_strnicmp()
int _rl_strnicmp (const char * string1, const char * string2, int count)
Definition at line 370 of file util.c.
 {
   register const char *s1;
   register const char *s2;
   register int d;
   if (count <= 0 || (string1 == string2))
     return 0;
   s1 = string1;
   s2 = string2;
   do
     {
       d = _rl_to_lower (*s1) - _rl_to_lower (*s2);  /* XXX - cast to unsigned char? */
       if (d != 0)
     return d;
       if (*s1++ == '\0')
         break;
       s2++;
     }
   while (--count != 0);
   return (0);
 }
References _rl_to_lower(), count, s1, and s2.
Referenced by _rl_strindex(), complete_fncmp(), parser_if(), and sv_editmode().
_rl_strpbrk()
char* _rl_strpbrk (const char * string1, const char * string2)
Definition at line 336 of file util.c.
 {
   register const char *scan;
 #if defined (HANDLE_MULTIBYTE)
   mbstate_t ps;
   register int i, v;
   memset (&ps, 0, sizeof (mbstate_t));
 #endif
   for (; *string1; string1++)
     {
       for (scan = string2; *scan; scan++)
     {
       if (*string1 == *scan)
         return ((char *)string1);
     }
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       v = _rl_get_char_len (string1, &ps);
       if (v > 1)
         string1 += v - 1;   /* -1 to account for auto-increment in loop */
     }
 #endif
     }
   return ((char *)NULL);
 }
References i, MB_CUR_MAX, memset, NULL, and rl_byte_oriented.
Referenced by make_quoted_replacement().
strchr()
char* strchr ()
strrchr()
char * strrchr ()