Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/i_input.c File Reference
i_input.c File Reference
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <fcntl.h>
#include <stdio.h>
#include "config.h"
#include "deh_str.h"
#include "doomtype.h"
#include "doomkeys.h"
#include "i_joystick.h"
#include "i_system.h"
#include "i_swap.h"
#include "i_timer.h"
#include "i_video.h"
#include "i_scale.h"
#include "m_argv.h"
#include "m_config.h"
#include "m_misc.h"
#include "tables.h"
#include "v_video.h"
#include "w_wad.h"
#include "z_zone.h"
#include "doomgeneric.h"
Functions
static unsigned char TranslateKey (unsigned char key)
static unsigned char GetTypedChar (unsigned char key)
static void UpdateShiftStatus (int pressed, unsigned char key)
void I_GetEvent (void)
void I_InitInput (void)
Variables
int vanilla_keyboard_mapping = 1
static int shiftdown = 0
static const char at_to_doom []
static const char shiftxform []
Function Documentation
GetTypedChar()
static unsigned char GetTypedChar (unsigned char key) static
Definition at line 242 of file i_input.c.
 {
     key = TranslateKey(key);
     // Is shift held down?  If so, perform a translation.
     if (shiftdown > 0)
     {
         if (key >= 0 && key < arrlen(shiftxform))
         {
             key = shiftxform[key];
         }
         else
         {
             key = 0;
         }
     }
     return key;
 }
References arrlen, shiftdown, shiftxform, and TranslateKey().
Referenced by I_GetEvent().
I_GetEvent()
void I_GetEvent (void)
Definition at line 279 of file i_input.c.
 {
     event_t event;
     int pressed;
     unsigned char key;
     while (DG_GetKey(&pressed, &key))
     {
         UpdateShiftStatus(pressed, key);
         // process event
         if (pressed)
         {
             // data1 has the key pressed, data2 has the character
             // (shift-translated, etc)
             event.type = ev_keydown;
             event.data1 = TranslateKey(key);
             event.data2 = GetTypedChar(key);
             if (event.data1 != 0)
             {
                 D_PostEvent(&event);
             }
         }
         else
         {
             event.type = ev_keyup;
             event.data1 = TranslateKey(key);
             // data2 is just initialized to zero for ev_keyup.
             // For ev_keydown it's the shifted Unicode character
             // that was typed, but if something wants to detect
             // key releases it should do so based on data1
             // (key ID), not the printable char.
             event.data2 = 0;
             if (event.data1 != 0)
             {
                 D_PostEvent(&event);
             }
             break;
         }
     }
                 /*
             case SDL_MOUSEMOTION:
                 event.type = ev_mouse;
                 event.data1 = mouse_button_state;
                 event.data2 = AccelerateMouse(sdlevent.motion.xrel);
                 event.data3 = -AccelerateMouse(sdlevent.motion.yrel);
                 D_PostEvent(&event);
                 break;
                 */
 }
References D_PostEvent(), event_t::data1, DG_GetKey(), ev_keydown, ev_keyup, GetTypedChar(), TranslateKey(), and UpdateShiftStatus().
Referenced by I_StartTic().
I_InitInput()
void I_InitInput (void)
Definition at line 338 of file i_input.c.
 {
 }
Referenced by I_InitGraphics().
TranslateKey()
static unsigned char TranslateKey (unsigned char key) static
Definition at line 225 of file i_input.c.
 {
     return key;
     /*
     if (key < sizeof(at_to_doom))
         return at_to_doom[key];
     else
         return 0x0;
     */
     //default:
     //  return tolower(key);
 }
Referenced by GetTypedChar(), and I_GetEvent().
UpdateShiftStatus()
static void UpdateShiftStatus (int pressed, unsigned char key) static
Definition at line 263 of file i_input.c.
 {
     int change;
     if (pressed) {
         change = 1;
     } else {
         change = -1;
     }
     if (key == KEY_RSHIFT) {
         shiftdown += change;
     }
 }
References KEY_RSHIFT, and shiftdown.
Referenced by I_GetEvent().
Variable Documentation
at_to_doom
const char at_to_doom[] static
Definition at line 51 of file i_input.c.
shiftdown
int shiftdown = 0 static
Definition at line 48 of file i_input.c.
Referenced by GetTypedChar(), and UpdateShiftStatus().
shiftxform
const char shiftxform[] static
Definition at line 185 of file i_input.c.
Referenced by GetTypedChar().
vanilla_keyboard_mapping
int vanilla_keyboard_mapping = 1
Definition at line 44 of file i_input.c.
Referenced by M_Responder().