Fennix Userspace: Userspace/musl/src/time/nanosleep.c File Reference
nanosleep.c File Reference
#include <time.h>
#include "syscall.h"
Functions
int nanosleep (const struct timespec *req, struct timespec *rem)
Function Documentation
nanosleep()
int nanosleep (const struct timespec * req, struct timespec * rem)
Definition at line 4 of file nanosleep.c.
 {
     return __syscall_ret(-__clock_nanosleep(CLOCK_REALTIME, 0, req, rem));
 }
References __clock_nanosleep(), and __syscall_ret().
Referenced by __nanosleep_time32(), main(), msleep(), sleep(), and usleep().