Fennix: Userspace/mlibc/options/internal/generic/frigg.cpp File Reference
frigg.cpp File Reference
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/internal-sysdeps.hpp>
Functions
void frg_panic (const char *mstr)
void frg_log (const char *mstr)
Function Documentation
frg_log()
void frg_log (const char * mstr)
Definition at line 12 of file frigg.cpp.
{
     mlibc::sys_libc_log(mstr);
 }
References mlibc::sys_libc_log().
frg_panic()
void frg_panic (const char * mstr)
Definition at line 6 of file frigg.cpp.
{
 //  mlibc::sys_libc_log("mlibc: Call to frg_panic");
     mlibc::sys_libc_log(mstr);
     mlibc::sys_libc_panic();
 }
References mlibc::sys_libc_log(), and mlibc::sys_libc_panic().