Fennix Userspace: Userspace/apps/base/bash/general.c File Reference
general.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixstat.h"
#include "filecntl.h"
#include "bashansi.h"
#include <stdio.h>
#include "chartypes.h"
#include <errno.h>
#include "bashintl.h"
#include "shell.h"
#include "parser.h"
#include "flags.h"
#include "findcmd.h"
#include "test.h"
#include "trap.h"
#include "pathexp.h"
#include "builtins/common.h"
#include <tilde/tilde.h>
Macros
#define TILDE_END(c) ((c) == '\0' || (c) == '/' || (c) == ':')
#define NOGROUP (gid_t) -1
Functions
static char *bash_special_tilde_expansions PARAMS ((char *))
static int unquoted_tilde_word PARAMS ((const char *))
static void initialize_group_array PARAMS ((void))
void posix_initialize (int on)
int num_posix_options ()
char * get_posix_options (char *bitmap)
void save_posix_options ()
void set_posix_options (char *bitmap) const
int all_digits (char *string) const
int legal_number (char *string, intmax_t *result) const
int legal_identifier (char *name) const
int valid_nameref_value (char *name, int flags) const
int check_selfref (char *name, char *value, int flags) const
int check_identifier (WORD_DESC *word, int check_word)
int importable_function_name (char *string, size_t len) const
int exportable_function_name (char *string) const
int legal_alias_name (char *string, int flags) const
int assignment (char *string, int flags) const
int line_isblank (char *line) const
int sh_unset_nodelay_mode (int fd)
int sh_setclexec (int fd)
int sh_validfd (int fd)
int fd_ispipe (int fd)
void check_dev_tty ()
int same_file (char *path1, char *path2, struct stat *stp1, struct stat *stp2) const
int move_to_high_fd (int fd, int check_new, int maxfd)
int check_binary_file (char *sample, int sample_len) const
int sh_openpipe (int *pv)
int sh_closepipe (int *pv)
int file_exists (char *fn) const
int file_isdir (char *fn) const
int file_iswdir (char *fn) const
int path_dot_or_dotdot (char *string) const
int absolute_pathname (char *string) const
int absolute_program (char *string) const
char * make_absolute (char *string, char *dot_path) const
char * base_pathname (char *string)
char * full_pathname (char *file)
char * polite_directory_format (char *name)
char * trim_pathname (char *name, int maxlen)
char * printable_filename (char *fn, int flags)
char * extract_colon_unit (char *string, int *p_index)
static char * bash_special_tilde_expansions (char *text)
void tilde_initialize ()
static int unquoted_tilde_word (char *s) const
char * bash_tilde_find_word (char *s, int flags, int *lenp) const
char * bash_tilde_expand (char *s, int assign_p) const
static void initialize_group_array ()
int group_member (gid_t gid)
char ** get_group_list (int *ngp)
int * get_group_array (int *ngp)
char * conf_standard_path ()
int default_columns ()
Variables
int errno
const char *const bash_getcwd_errstr = N_("getcwd: cannot access parent directories")
struct {
int * posix_mode_var
} posix_vars []
static char * saved_posix_vars = 0
static char tdir [PATH_MAX]
static char ** bash_tilde_prefixes
static char ** bash_tilde_prefixes2
static char ** bash_tilde_suffixes
static char ** bash_tilde_suffixes2
static int ngroups
static int maxgroups
static GETGROUPS_T * group_array = (GETGROUPS_T *)NULL
Macro Definition Documentation
NOGROUP
#define NOGROUP (gid_t) -1
Definition at line 1240 of file general.c.
TILDE_END
#define TILDE_END (c) ((c) == '\0' || (c) == '/' || (c) == ':')
Definition at line 1143 of file general.c.
Function Documentation
absolute_pathname()
int absolute_pathname (char * string) const
Definition at line 793 of file general.c.
 {
   if (string == 0 || *string == '\0')
     return (0);
   if (ABSPATH(string))
     return (1);
   if (string[0] == '.' && PATHSEP(string[1]))   /* . and ./ */
     return (1);
   if (string[0] == '.' && string[1] == '.' && PATHSEP(string[2]))   /* .. and ../ */
     return (1);
   return (0);
 }
References ABSPATH, and PATHSEP.
Referenced by base_pathname().
absolute_program()
int absolute_program (char * string) const
Definition at line 815 of file general.c.
 {
   return ((char *)mbschr (string, '/') != (char *)NULL);
 }
References mbschr(), and NULL.
Referenced by exportable_function_name(), find_user_command_in_path(), importable_function_name(), initialize_shell_variables(), open_shell_script(), search_for_command(), and user_command_matches().
all_digits()
int all_digits (char * string) const
Definition at line 233 of file general.c.
 {
   register const char *s;
   for (s = string; *s; s++)
     if (DIGIT (*s) == 0)
       return (0);
   return (1);
 }
References DIGIT.
Referenced by check_identifier(), do_redirection_internal(), make_redirection(), normalize_codeset(), print_builtin(), redir_special_open(), seq_builtin(), sv_ignoreeof(), valid_brace_expansion_word(), and valid_length_expression().
assignment()
int assignment (char * string, int flags) const
Definition at line 433 of file general.c.
 {
   register unsigned char c;
   register int newi, indx;
   c = string[indx = 0];
 #if defined (ARRAY_VARS)
   /* If parser_state includes PST_COMPASSIGN, FLAGS will include 1, so we are
      parsing the contents of a compound assignment. If parser_state includes
      PST_REPARSE, we are in the middle of an assignment statement and breaking
      the words between the parens into words and assignment statements, but
      we don't need to check for that right now. Within a compound assignment,
      the subscript is required to make the word an assignment statement. If
      we don't have a subscript, even if the word is a valid assignment
      statement otherwise, we don't want to treat it as one. */
   if ((flags & 1) && c != '[')      /* ] */
     return (0);
   else if ((flags & 1) == 0 && legal_variable_starter (c) == 0)
 #else
   if (legal_variable_starter (c) == 0)
 #endif
     return (0);
   while (c = string[indx])
     {
       /* The following is safe.  Note that '=' at the start of a word
      is not an assignment statement. */
       if (c == '=')
     return (indx);
 #if defined (ARRAY_VARS)
       if (c == '[')
     {
       newi = skipsubscript (string, indx, (flags & 2) ? 1 : 0);
       /* XXX - why not check for blank subscripts here, if we do in
          valid_array_reference? */
       if (string[newi++] != ']')
         return (0);
       if (string[newi] == '+' && string[newi+1] == '=')
         return (newi + 1);
       return ((string[newi] == '=') ? newi : 0);
     }
 #endif /* ARRAY_VARS */
       /* Check for `+=' */
       if (c == '+' && string[indx+1] == '=')
     return (indx + 1);
       /* Variable names in assignment statements may contain only letters,
      digits, and `_'. */
       if (legal_variable_char (c) == 0)
     return (0);
       indx++;
     }
   return (0);
 }
References c, flags, legal_variable_char, and legal_variable_starter.
Referenced by add_or_supercede_exported_var(), assign_in_env(), do_assignment_internal(), and read_token_word().
base_pathname()
char* base_pathname (char * string)
Definition at line 858 of file general.c.
 {
   char *p;
 #if 0
   if (absolute_pathname (string) == 0)
     return (string);
 #endif
   if (string[0] == '/' && string[1] == 0)
     return (string);
   p = (char *)strrchr (string, '/');
   return (p ? ++p : string);
 }
References absolute_pathname(), p, and strrchr().
Referenced by decode_prompt_string(), finfo_main(), get_name_for_error(), and set_shell_name().
bash_special_tilde_expansions()
static char* bash_special_tilde_expansions (char * text) static
Definition at line 1077 of file general.c.
 {
   char *result;
   result = (char *)NULL;
   if (text[0] == '+' && text[1] == '\0')
     result = get_string_value ("PWD");
   else if (text[0] == '-' && text[1] == '\0')
     result = get_string_value ("OLDPWD");
 #if defined (PUSHD_AND_POPD)
   else if (DIGIT (*text) || ((*text == '+' || *text == '-') && DIGIT (text[1])))
     result = get_dirstack_from_string (text);
 #endif
   return (result ? savestring (result) : (char *)NULL);
 }
References DIGIT, get_string_value(), NULL, and savestring().
Referenced by tilde_initialize().
bash_tilde_expand()
char* bash_tilde_expand (char * s, int assign_p) const
Definition at line 1208 of file general.c.
 {
   int r;
   char *ret;
   tilde_additional_prefixes = assign_p == 0 ? (char **)0
                         : (assign_p == 2 ? bash_tilde_prefixes2 : bash_tilde_prefixes);
   if (assign_p == 2)
     tilde_additional_suffixes = bash_tilde_suffixes2;
   r = (*s == '~') ? unquoted_tilde_word (s) : 1;
   ret = r ? tilde_expand (s) : savestring (s);
   QUIT;
   return (ret);
 }
References bash_tilde_prefixes, bash_tilde_prefixes2, bash_tilde_suffixes2, QUIT, r, ret, savestring(), tilde_additional_prefixes, tilde_additional_suffixes, tilde_expand(), and unquoted_tilde_word().
Referenced by expand_word_internal(), find_in_path_element(), force_execute_file(), full_pathname(), initialize_shell_variables(), maybe_execute_file(), and sh_makepath().
bash_tilde_find_word()
char* bash_tilde_find_word (char * s, int flags, int * lenp) const
Definition at line 1169 of file general.c.
 {
   const char *r;
   char *ret;
   int l;
   for (r = s; *r && *r != '/'; r++)
     {
       /* Short-circuit immediately if we see a quote character.  Even though
      POSIX says that `the first unquoted slash' (or `:') terminates the
      tilde-prefix, in practice, any quoted portion of the tilde prefix
      will cause it to not be expanded. */
       if (*r == '\\' || *r == '\'' || *r == '"')
     {
       ret = savestring (s);
       if (lenp)
         *lenp = 0;
       return ret;
     }
       else if (flags && *r == ':')
     break;
     }
   l = r - s;
   ret = xmalloc (l + 1);
   strncpy (ret, s, l);
   ret[l] = '\0';
   if (lenp)
     *lenp = l;
   return ret;
 }
References flags, r, ret, savestring(), strncpy(), and xmalloc.
Referenced by expand_word_internal().
check_binary_file()
int check_binary_file (char * sample, int sample_len) const
Definition at line 681 of file general.c.
 {
   register int i;
   int nline;
   unsigned char c;
   if (sample_len >= 4 && sample[0] == 0x7f && sample[1] == 'E' && sample[2] == 'L' && sample[3] == 'F')
     return 1;
   /* Generally we check the first line for NULs. If the first line looks like
      a `#!' interpreter specifier, we look for NULs in the first two lines. */
   nline = (sample[0] == '#' && sample[1] == '!') ? 2 : 1;
   for (i = 0; i < sample_len; i++)
     {
       c = sample[i];
       if (c == '\n' && --nline == 0)
     return (0);
       if (c == '\0')
     return (1);
     }
   return (0);
 }
References c, and i.
Referenced by _evalfile(), open_shell_script(), and shell_execve().
check_dev_tty()
void check_dev_tty ()
Definition at line 590 of file general.c.
 {
   int tty_fd;
   char *tty;
   tty_fd = open ("/dev/tty", O_RDWR|O_NONBLOCK);
   if (tty_fd < 0)
     {
       tty = (char *)ttyname (fileno (stdin));
       if (tty == 0)
     return;
       tty_fd = open (tty, O_RDWR|O_NONBLOCK);
     }
   if (tty_fd >= 0)
     close (tty_fd);
 }
References close(), fileno(), O_NONBLOCK, O_RDWR, open(), stdin, and ttyname().
Referenced by main().
check_identifier()
int check_identifier (WORD_DESC * word, int check_word)
Definition at line 364 of file general.c.
 {
   if (word->flags & (W_HASDOLLAR|W_QUOTED)) /* XXX - HASDOLLAR? */
     {
       internal_error (_("`%s': not a valid identifier"), word->word);
       return (0);
     }
   else if (check_word && (all_digits (word->word) || legal_identifier (word->word) == 0))
     {
       internal_error (_("`%s': not a valid identifier"), word->word);
       return (0);
     }
   else
     return (1);
 }
References _, all_digits(), internal_error(), legal_identifier(), W_HASDOLLAR, and W_QUOTED.
Referenced by execute_for_command(), and execute_intern_function().
check_selfref()
int check_selfref (char * name, char * value, int flags) const
Definition at line 332 of file general.c.
 {
   char *t;
   if (STREQ (name, value))
     return 1;
 #if defined (ARRAY_VARS)
   if (valid_array_reference (value, 0))
     {
       t = array_variable_name (value, 0, (char **)NULL, (int *)NULL);
       if (t && STREQ (name, t))
     {
       free (t);
       return 1;
     }
       free (t);
     }
 #endif
   return 0; /* not a self reference */
 }
References free, name, NULL, STREQ, t, and value.
Referenced by bind_variable_value().
conf_standard_path()
char* conf_standard_path ()
Definition at line 1405 of file general.c.
 {
 #if defined (_CS_PATH) && defined (HAVE_CONFSTR)
   char *p;
   size_t len;
   len = (size_t)confstr (_CS_PATH, (char *)NULL, (size_t)0);
   if (len > 0)
     {
       p = (char *)xmalloc (len + 2);
       *p = '\0';
       confstr (_CS_PATH, p, len);
       return (p);
     }
   else
     return (savestring (STANDARD_UTILS_PATH));
 #else /* !_CS_PATH || !HAVE_CONFSTR  */
 #  if defined (CS_PATH)
   return (savestring (CS_PATH));
 #  else
   return (savestring (STANDARD_UTILS_PATH));
 #  endif /* !CS_PATH */
 #endif /* !_CS_PATH || !HAVE_CONFSTR */
 }
References _CS_PATH, confstr(), NULL, p, savestring(), STANDARD_UTILS_PATH, and xmalloc.
Referenced by search_for_command().
default_columns()
int default_columns ()
Definition at line 1431 of file general.c.
 {
   char *v;
   int c;
   c = -1;
   v = get_string_value ("COLUMNS");
   if (v && *v)
     {
       c = atoi (v);
       if (c > 0)
     return c;
     }
   if (check_window_size)
     get_new_window_size (0, (int *)0, &c);
   return (c > 0 ? c : 80);
 }
References atoi(), c, check_window_size, get_new_window_size(), and get_string_value().
exportable_function_name()
int exportable_function_name (char * string) const
Definition at line 402 of file general.c.
 {
   if (absolute_program (string))
     return 0;
   if (mbschr (string, '=') != 0)
     return 0;
   return 1;
 }
References absolute_program(), and mbschr().
extract_colon_unit()
char* extract_colon_unit (char * string, int * p_index)
Definition at line 1013 of file general.c.
 {
   int i, start, len;
   char *value;
   if (string == 0)
     return (string);
   len = strlen (string);
   if (*p_index >= len)
     return ((char *)NULL);
   i = *p_index;
   /* Each call to this routine leaves the index pointing at a colon if
      there is more to the path.  If I is > 0, then increment past the
      `:'.  If I is 0, then the path has a leading colon.  Trailing colons
      are handled OK by the `else' part of the if statement; an empty
      string is returned in that case. */
   if (i && string[i] == ':')
     i++;
   for (start = i; string[i] && string[i] != ':'; i++)
     ;
   *p_index = i;
   if (i == start)
     {
       if (string[i])
     (*p_index)++;
       /* Return "" in the case of a trailing `:'. */
       value = (char *)xmalloc (1);
       value[0] = '\0';
     }
   else
     value = substring (string, start, i);
   return (value);
 }
References i, NULL, start(), strlen(), substring(), value, and xmalloc.
Referenced by get_next_path_element(), remember_mail_dates(), and setup_ignore_patterns().
fd_ispipe()
int fd_ispipe (int fd)
Definition at line 572 of file general.c.
 {
   errno = 0;
   return ((lseek (fd, 0L, SEEK_CUR) < 0) && (errno == ESPIPE));
 }
References errno, ESPIPE, L, lseek(), and SEEK_CUR.
file_exists()
int file_exists (char * fn) const
Definition at line 750 of file general.c.
 {
   struct stat sb;
   return (stat (fn, &sb) == 0);
 }
file_isdir()
int file_isdir (char * fn) const
Definition at line 759 of file general.c.
 {
   struct stat sb;
   return ((stat (fn, &sb) == 0) && S_ISDIR (sb.st_mode));
 }
References S_ISDIR, and stat::st_mode.
Referenced by file_iswdir(), find_user_command_in_path(), is_dirname(), open_shell_script(), rm_file(), set_pwd(), and shell_execve().
file_iswdir()
int file_iswdir (char * fn) const
Definition at line 768 of file general.c.
 {
   return (file_isdir (fn) && sh_eaccess (fn, W_OK) == 0);
 }
References file_isdir(), sh_eaccess(), and W_OK.
Referenced by get_sys_tmpdir(), and get_tmpdir().
full_pathname()
char* full_pathname (char * file)
Definition at line 880 of file general.c.
 {
   char *ret;
   file = (*file == '~') ? bash_tilde_expand (file, 0) : savestring (file);
   if (ABSPATH(file))
     return (file);
   ret = sh_makepath ((char *)NULL, file, (MP_DOCWD|MP_RMDOT));
   free (file);
   return (ret);
 }
References ABSPATH, bash_tilde_expand(), free, MP_DOCWD, MP_RMDOT, NULL, ret, savestring(), and sh_makepath().
Referenced by add_mail_file(), get_bash_name(), and print_filename().
get_group_array()
int* get_group_array (int * ngp)
Definition at line 1363 of file general.c.
 {
   int i;
   static int *group_iarray = (int *)NULL;
   if (group_iarray)
     {
       if (ngp)
     *ngp = ngroups;
       return (group_iarray);
     }
   if (ngroups == 0)
     initialize_group_array ();
   if (ngroups <= 0)
     {
       if (ngp)
     *ngp = 0;
       return (int *)NULL;
     }
   group_iarray = (int *)xmalloc (ngroups * sizeof (int));
   for (i = 0; i < ngroups; i++)
     group_iarray[i] = (int)group_array[i];
   if (ngp)
     *ngp = ngroups;
   return group_iarray;
 }
References group_array, i, initialize_group_array(), ngroups, NULL, and xmalloc.
Referenced by id_prall(), and id_prgroups().
get_group_list()
char** get_group_list (int * ngp)
Definition at line 1330 of file general.c.
 {
   static char **group_vector = (char **)NULL;
   register int i;
   if (group_vector)
     {
       if (ngp)
     *ngp = ngroups;
       return group_vector;
     }
   if (ngroups == 0)
     initialize_group_array ();
   if (ngroups <= 0)
     {
       if (ngp)
     *ngp = 0;
       return (char **)NULL;
     }
   group_vector = strvec_create (ngroups);
   for (i = 0; i < ngroups; i++)
     group_vector[i] = itos (group_array[i]);
   if (ngp)
     *ngp = ngroups;
   return group_vector;
 }
References group_array, i, initialize_group_array(), itos(), ngroups, NULL, and strvec_create().
get_posix_options()
char* get_posix_options (char * bitmap)
Definition at line 139 of file general.c.
 {
   register int i;
   if (bitmap == 0)
     bitmap = (char *)xmalloc (num_posix_options ());    /* no trailing NULL */
   for (i = 0; posix_vars[i].posix_mode_var; i++)
     bitmap[i] = *(posix_vars[i].posix_mode_var);
   return bitmap;
 }
References i, num_posix_options(), posix_vars, and xmalloc.
Referenced by save_posix_options().
group_member()
int group_member (gid_t gid)
Definition at line 1300 of file general.c.
 {
 #if defined (HAVE_GETGROUPS)
   register int i;
 #endif
   /* Short-circuit if possible, maybe saving a call to getgroups(). */
   if (gid == current_user.gid || gid == current_user.egid)
     return (1);
 #if defined (HAVE_GETGROUPS)
   if (ngroups == 0)
     initialize_group_array ();
   /* In case of error, the user loses. */
   if (ngroups <= 0)
     return (0);
   /* Search through the list looking for GID. */
   for (i = 0; i < ngroups; i++)
     if (gid == (gid_t)group_array[i])
       return (1);
 #endif
   return (0);
 }
References current_user, user_info::egid, user_info::gid, group_array, i, initialize_group_array(), and ngroups.
Referenced by file_status(), and sh_stataccess().
importable_function_name()
int importable_function_name (char * string, size_t len) const
Definition at line 388 of file general.c.
 {
   if (absolute_program (string))    /* don't allow slash */
     return 0;
   if (*string == '\n')          /* can't start with a newline */
     return 0;
   if (shellblank (*string) || shellblank(string[len-1]))
     return 0;
   return (posixly_correct ? legal_identifier (string) : 1);
 }
References absolute_program(), legal_identifier(), posixly_correct, and shellblank.
initialize_group_array()
static void initialize_group_array () static
Definition at line 1244 of file general.c.
 {
   register int i;
   if (maxgroups == 0)
     maxgroups = getmaxgroups ();
   ngroups = 0;
   group_array = (GETGROUPS_T *)xrealloc (group_array, maxgroups * sizeof (GETGROUPS_T));
 #if defined (HAVE_GETGROUPS)
   ngroups = getgroups (maxgroups, group_array);
 #endif
   /* If getgroups returns nothing, or the OS does not support getgroups(),
      make sure the groups array includes at least the current gid. */
   if (ngroups == 0)
     {
       group_array[0] = current_user.gid;
       ngroups = 1;
     }
   /* If the primary group is not in the groups array, add it as group_array[0]
      and shuffle everything else up 1, if there's room. */
   for (i = 0; i < ngroups; i++)
     if (current_user.gid == (gid_t)group_array[i])
       break;
   if (i == ngroups && ngroups < maxgroups)
     {
       for (i = ngroups; i > 0; i--)
     group_array[i] = group_array[i - 1];
       group_array[0] = current_user.gid;
       ngroups++;
     }
   /* If the primary group is not group_array[0], swap group_array[0] and
      whatever the current group is.  The vast majority of systems should
      not need this; a notable exception is Linux. */
   if (group_array[0] != current_user.gid)
     {
       for (i = 0; i < ngroups; i++)
     if (group_array[i] == current_user.gid)
       break;
       if (i < ngroups)
     {
       group_array[i] = group_array[0];
       group_array[0] = current_user.gid;
     }
     }
 }
References current_user, getgroups(), getmaxgroups(), user_info::gid, group_array, i, maxgroups, ngroups, and xrealloc.
Referenced by get_group_array(), get_group_list(), and group_member().
legal_alias_name()
int legal_alias_name (char * string, int flags) const
Definition at line 416 of file general.c.
 {
   register const char *s;
   for (s = string; *s; s++)
     if (shellbreak (*s) || shellxquote (*s) || shellexp (*s) || (*s == '/'))
       return 0;
   return 1;
 }
References shellbreak, shellexp, and shellxquote.
legal_identifier()
int legal_identifier (char * name) const
Definition at line 290 of file general.c.
 {
   register const char *s;
   unsigned char c;
   if (!name || !(c = *name) || (legal_variable_starter (c) == 0))
     return (0);
   for (s = name + 1; (c = *s) != 0; s++)
     {
       if (legal_variable_char (c) == 0)
     return (0);
     }
   return (1);
 }
References c, legal_variable_char, legal_variable_starter, and name.
Referenced by asort_builtin(), assign_in_env(), bind_int_variable(), check_identifier(), csv_builtin(), cut_internal(), dsv_builtin(), find_variable_nameref_for_create(), importable_function_name(), initialize_shell_variables(), mktemp_builtin(), param_expand(), parameter_brace_expand_indir(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), read_token_word(), realpath_builtin(), stat_builtin(), valid_brace_expansion_word(), valid_length_expression(), and valid_nameref_value().
legal_number()
int legal_number (char * string, intmax_t * result) const
Definition at line 249 of file general.c.
 {
   intmax_t value;
   char *ep;
   if (result)
     *result = 0;
   if (string == 0)
     return 0;
   errno = 0;
   value = strtoimax (string, &ep, 10);
   if (errno || ep == string)
     return 0;   /* errno is set on overflow or underflow */
   /* Skip any trailing whitespace, since strtoimax does not. */
   while (whitespace (*ep))
     ep++;
   /* If *string is not '\0' but *ep is '\0' on return, the entire string
      is valid. */
   if (*string && *ep == '\0')
     {
       if (result)
     *result = value;
       /* The SunOS4 implementation of strtol() will happily ignore
      overflow conditions, so this cannot do overflow correctly
      on those systems. */
       return 1;
     }
   return (0);
 }
References errno, strtoimax(), value, and whitespace.
Referenced by accept_builtin(), adjust_shell_level(), arithcomp(), assign_lineno(), assign_random(), assign_seconds(), assign_subshell(), decode_signal(), display_signal_list(), do_redirection_internal(), fdflags_builtin(), get_exitstat(), get_numeric_arg(), getlist(), getstat(), init_seconds_var(), internal_getopt(), make_redirection(), parameter_brace_expand_length(), parameter_brace_expand_word(), pop_args(), print_builtin(), read_token_word(), redir_special_open(), redir_varvalue(), setpgid_builtin(), sh_stat(), strftime_builtin(), sv_funcnest(), time_to_check_mail(), trim_pathname(), unary_operator(), and unary_test().
line_isblank()
int line_isblank (char * line) const
Definition at line 495 of file general.c.
 {
   register int i;
   if (line == 0)
     return 0;       /* XXX */
   for (i = 0; line[i]; i++)
     if (isblank ((unsigned char)line[i]) == 0)
       break;
   return (line[i] == '\0');
 }
References i, isblank, and line.
make_absolute()
char* make_absolute (char * string, char * dot_path) const
Definition at line 832 of file general.c.
 {
   char *result;
   if (dot_path == 0 || ABSPATH(string))
 #ifdef __CYGWIN__
     {
       char pathbuf[PATH_MAX + 1];
       /* WAS cygwin_conv_to_full_posix_path (string, pathbuf); */
       cygwin_conv_path (CCP_WIN_A_TO_POSIX, string, pathbuf, PATH_MAX);
       result = savestring (pathbuf);
     }
 #else
     result = savestring (string);
 #endif
   else
     result = sh_makepath (dot_path, string, 0);
   return (result);
 }
References ABSPATH, PATH_MAX, savestring(), and sh_makepath().
Referenced by get_bash_name(), and realpath_builtin().
move_to_high_fd()
int move_to_high_fd (int fd, int check_new, int maxfd)
Definition at line 643 of file general.c.
 {
   int script_fd, nfds, ignore;
   if (maxfd < 20)
     {
       nfds = getdtablesize ();
       if (nfds <= 0)
     nfds = 20;
       if (nfds > HIGH_FD_MAX)
     nfds = HIGH_FD_MAX;     /* reasonable maximum */
     }
   else
     nfds = maxfd;
   for (nfds--; check_new && nfds > 3; nfds--)
     if (fcntl (nfds, F_GETFD, &ignore) == -1)
       break;
   if (nfds > 3 && fd != nfds && (script_fd = dup2 (fd, nfds)) != -1)
     {
       if (check_new == 0 || fd != fileno (stderr))  /* don't close stderr */
     close (fd);
       return (script_fd);
     }
   /* OK, we didn't find one less than our artificial maximum; return the
      original file descriptor. */
   return (fd);
 }
References close(), dup2(), F_GETFD, fcntl(), fileno(), getdtablesize(), HIGH_FD_MAX, and stderr.
Referenced by execute_pipeline(), initialize_job_control(), open_shell_script(), and sh_openpipe().
num_posix_options()
int num_posix_options ()
Definition at line 133 of file general.c.
 {
   return ((sizeof (posix_vars) / sizeof (posix_vars[0])) - 1);
 }
References posix_vars.
Referenced by get_posix_options().
PARAMS() [1/3]
static char* bash_special_tilde_expansions PARAMS ((char *)) static
PARAMS() [2/3]
static int unquoted_tilde_word PARAMS ((const char *)) static
PARAMS() [3/3]
static void initialize_group_array PARAMS ((void)) static
path_dot_or_dotdot()
int path_dot_or_dotdot (char * string) const
Definition at line 777 of file general.c.
 {
   if (string == 0 || *string == '\0' || *string != '.')
     return (0);
   /* string[0] == '.' */
   if (PATHSEP(string[1]) || (string[1] == '.' && PATHSEP(string[2])))
     return (1);
   return (0);
 }
References PATHSEP.
polite_directory_format()
char* polite_directory_format (char * name)
Definition at line 903 of file general.c.
 {
   char *home;
   int l;
   home = get_string_value ("HOME");
   l = home ? strlen (home) : 0;
   if (l > 1 && strncmp (home, name, l) == 0 && (!name[l] || name[l] == '/'))
     {
       strncpy (tdir + 1, name + l, sizeof(tdir) - 2);
       tdir[0] = '~';
       tdir[sizeof(tdir) - 1] = '\0';
       return (tdir);
     }
   else
     return (name);
 }
References get_string_value(), name, strlen(), strncmp(), strncpy(), and tdir.
Referenced by decode_prompt_string(), notify_of_job_status(), print_pipeline(), and start_job().
posix_initialize()
void posix_initialize (int on)
Definition at line 103 of file general.c.
 {
   /* Things that should be turned on when posix mode is enabled. */
   if (on != 0)
     {
       interactive_comments = source_uses_path = 1;
       expand_aliases = expaliases_flag = 1;
       inherit_errexit = 1;
       source_searches_cwd = 0;
       print_shift_error = 1;
     }
   /* Things that should be turned on when posix mode is disabled. */
   else if (saved_posix_vars)        /* on == 0, restore saved settings */
     {
       set_posix_options (saved_posix_vars);
       expand_aliases = expaliases_flag;
       free (saved_posix_vars);
       saved_posix_vars = 0;
     }
   else  /* on == 0, restore a default set of settings */
     {
       source_searches_cwd = 1;
       expand_aliases = expaliases_flag = interactive_shell; /* XXX */
       print_shift_error = 0;
     }
 }
References expaliases_flag, expand_aliases, free, inherit_errexit, interactive_comments, interactive_shell, print_shift_error, saved_posix_vars, set_posix_options(), source_searches_cwd, and source_uses_path.
Referenced by sv_strict_posix().
printable_filename()
char* printable_filename (char * fn, int flags)
Definition at line 993 of file general.c.
 {
   char *newf;
   if (ansic_shouldquote (fn))
     newf = ansic_quote (fn, 0, NULL);
   else if (flags && sh_contains_shell_metas (fn))
     newf = sh_single_quote (fn);
   else
     newf = fn;
   return newf;
 }
References ansic_quote(), ansic_shouldquote(), flags, NULL, sh_contains_shell_metas(), and sh_single_quote().
Referenced by execute_disk_command().
same_file()
int same_file (char * path1, char * path2, struct stat * stp1, struct stat * stp2) const
Definition at line 612 of file general.c.
 {
   struct stat st1, st2;
   if (stp1 == NULL)
     {
       if (stat (path1, &st1) != 0)
     return (0);
       stp1 = &st1;
     }
   if (stp2 == NULL)
     {
       if (stat (path2, &st2) != 0)
     return (0);
       stp2 = &st2;
     }
   return ((stp1->st_dev == stp2->st_dev) && (stp1->st_ino == stp2->st_ino));
 }
References NULL, stat::st_dev, and stat::st_ino.
Referenced by filecomp(), find_in_path_element(), here_document_to_fd(), noclobber_open(), phash_search(), and set_pwd().
save_posix_options()
void save_posix_options ()
Definition at line 153 of file general.c.
 {
   saved_posix_vars = get_posix_options (saved_posix_vars);
 }
References get_posix_options(), and saved_posix_vars.
Referenced by assign_in_env().
set_posix_options()
void set_posix_options (char * bitmap) const
Definition at line 159 of file general.c.
 {
   register int i;
   for (i = 0; posix_vars[i].posix_mode_var; i++)
     *(posix_vars[i].posix_mode_var) = bitmap[i];
 }
References i, and posix_vars.
Referenced by posix_initialize().
sh_closepipe()
int sh_closepipe (int * pv)
Definition at line 730 of file general.c.
 {
   if (pv[0] >= 0)
     close (pv[0]);
   if (pv[1] >= 0)
     close (pv[1]);
   pv[0] = pv[1] = -1;
   return 0;
 }
References close().
Referenced by make_child(), start_pipeline(), stop_pipeline(), and without_job_control().
sh_openpipe()
int sh_openpipe (int * pv)
Definition at line 715 of file general.c.
 {
   int r;
   if ((r = pipe (pv)) < 0)
     return r;
   pv[0] = move_to_high_fd (pv[0], 1, 64);
   pv[1] = move_to_high_fd (pv[1], 1, 64);
   return 0;
 }
References move_to_high_fd(), pipe(), and r.
sh_setclexec()
int sh_setclexec (int fd)
Definition at line 557 of file general.c.
 {
   return (SET_CLOSE_ON_EXEC (fd));
 }
References SET_CLOSE_ON_EXEC.
sh_unset_nodelay_mode()
int sh_unset_nodelay_mode (int fd)
Definition at line 526 of file general.c.
 {
   int flags, bflags;
   if ((flags = fcntl (fd, F_GETFL, 0)) < 0)
     return -1;
   bflags = 0;
   /* This is defined to O_NDELAY in filecntl.h if O_NONBLOCK is not present
      and O_NDELAY is defined. */
 #ifdef O_NONBLOCK
   bflags |= O_NONBLOCK;
 #endif
 #ifdef O_NDELAY
   bflags |= O_NDELAY;
 #endif
   if (flags & bflags)
     {
       flags &= ~bflags;
       return (fcntl (fd, F_SETFL, flags));
     }
   return 0;
 }
References F_GETFL, F_SETFL, fcntl(), flags, O_NDELAY, and O_NONBLOCK.
Referenced by getc_with_restart(), and rl_getc().
sh_validfd()
int sh_validfd (int fd)
Definition at line 565 of file general.c.
 {
   return (fcntl (fd, F_GETFD, 0) >= 0);
 }
References F_GETFD, and fcntl().
Referenced by execute_pipeline(), sv_xtracefd(), and xtrace_set().
tilde_initialize()
void tilde_initialize ()
Definition at line 1100 of file general.c.
 {
   static int times_called = 0;
   /* Tell the tilde expander that we want a crack first. */
   tilde_expansion_preexpansion_hook = bash_special_tilde_expansions;
   /* Tell the tilde expander about special strings which start a tilde
      expansion, and the special strings that end one.  Only do this once.
      tilde_initialize () is called from within bashline_reinitialize (). */
   if (times_called++ == 0)
     {
       bash_tilde_prefixes = strvec_create (3);
       bash_tilde_prefixes[0] = "=~";
       bash_tilde_prefixes[1] = ":~";
       bash_tilde_prefixes[2] = (char *)NULL;
       bash_tilde_prefixes2 = strvec_create (2);
       bash_tilde_prefixes2[0] = ":~";
       bash_tilde_prefixes2[1] = (char *)NULL;
       tilde_additional_prefixes = bash_tilde_prefixes;
       bash_tilde_suffixes = strvec_create (3);
       bash_tilde_suffixes[0] = ":";
       bash_tilde_suffixes[1] = "=~";    /* XXX - ?? */
       bash_tilde_suffixes[2] = (char *)NULL;
       tilde_additional_suffixes = bash_tilde_suffixes;
       bash_tilde_suffixes2 = strvec_create (2);
       bash_tilde_suffixes2[0] = ":";
       bash_tilde_suffixes2[1] = (char *)NULL;
     }
 }
References bash_special_tilde_expansions(), bash_tilde_prefixes, bash_tilde_prefixes2, bash_tilde_suffixes, bash_tilde_suffixes2, NULL, strvec_create(), tilde_additional_prefixes, tilde_additional_suffixes, and tilde_expansion_preexpansion_hook.
Referenced by shell_initialize().
trim_pathname()
char* trim_pathname (char * name, int maxlen)
Definition at line 926 of file general.c.
 {
   int nlen, ndirs;
   intmax_t nskip;
   char *nbeg, *nend, *ntail, *v;
   if (name == 0 || (nlen = strlen (name)) == 0)
     return name;
   nend = name + nlen;
   v = get_string_value ("PROMPT_DIRTRIM");
   if (v == 0 || *v == 0)
     return name;
   if (legal_number (v, &nskip) == 0 || nskip <= 0)
     return name;
   /* Skip over tilde prefix */
   nbeg = name;
   if (name[0] == '~')
     for (nbeg = name; *nbeg; nbeg++)
       if (*nbeg == '/')
     {
       nbeg++;
       break;
     }
   if (*nbeg == 0)
     return name;
   for (ndirs = 0, ntail = nbeg; *ntail; ntail++)
     if (*ntail == '/')
       ndirs++;
   if (ndirs < nskip)
     return name;
   for (ntail = (*nend == '/') ? nend : nend - 1; ntail > nbeg; ntail--)
     {
       if (*ntail == '/')
     nskip--;
       if (nskip == 0)
     break;
     }
   if (ntail == nbeg)
     return name;
   /* Now we want to return name[0..nbeg]+"..."+ntail, modifying name in place */
   nlen = ntail - nbeg;
   if (nlen <= 3)
     return name;
   *nbeg++ = '.';
   *nbeg++ = '.';
   *nbeg++ = '.';
   nlen = nend - ntail;
   memmove (nbeg, ntail, nlen);
   nbeg[nlen] = '\0';
   return name;
 }
References get_string_value(), legal_number(), memmove(), name, and strlen().
Referenced by decode_prompt_string().
unquoted_tilde_word()
static int unquoted_tilde_word (char * s) const static
Definition at line 1146 of file general.c.
 {
   const char *r;
   for (r = s; TILDE_END(*r) == 0; r++)
     {
       switch (*r)
     {
     case '\\':
     case '\'':
     case '"':
       return 0;
     }
     }
   return 1;
 }
References r, and TILDE_END.
Referenced by bash_tilde_expand().
valid_nameref_value()
int valid_nameref_value (char * name, int flags) const
Definition at line 313 of file general.c.
 {
   if (name == 0 || *name == 0)
     return 0;
   /* valid identifier */
 #if defined (ARRAY_VARS)
   if (legal_identifier (name) || (flags != 2 && valid_array_reference (name, 0)))
 #else
   if (legal_identifier (name))
 #endif
     return 1;
   return 0;
 }
References flags, legal_identifier(), and name.
Referenced by assign_in_env(), bind_variable_internal(), bind_variable_value(), execute_for_command(), find_variable_nameref_for_assignment(), and nameref_transform_name().
Variable Documentation
bash_getcwd_errstr
const char* const bash_getcwd_errstr = N_("getcwd: cannot access parent directories")
Definition at line 70 of file general.c.
Referenced by get_working_directory().
bash_tilde_prefixes
char** bash_tilde_prefixes static
Definition at line 1066 of file general.c.
Referenced by bash_tilde_expand(), and tilde_initialize().
bash_tilde_prefixes2
char** bash_tilde_prefixes2 static
Definition at line 1067 of file general.c.
Referenced by bash_tilde_expand(), and tilde_initialize().
bash_tilde_suffixes
char** bash_tilde_suffixes static
Definition at line 1068 of file general.c.
Referenced by tilde_initialize().
bash_tilde_suffixes2
char** bash_tilde_suffixes2 static
Definition at line 1069 of file general.c.
Referenced by bash_tilde_expand(), and tilde_initialize().
errno
int errno extern
Referenced by fd_ispipe(), and legal_number().
group_array
GETGROUPS_T* group_array = (GETGROUPS_T *)NULL static
Definition at line 1237 of file general.c.
Referenced by get_group_array(), get_group_list(), group_member(), and initialize_group_array().
maxgroups
int maxgroups static
Definition at line 1234 of file general.c.
Referenced by getmaxgroups(), and initialize_group_array().
ngroups
int ngroups static
Definition at line 1234 of file general.c.
Referenced by get_group_array(), get_group_list(), getgrouplist(), group_member(), and initialize_group_array().
struct { ... } posix_vars[]
Initial value:
=
{
  &interactive_comments,
  &source_uses_path,
  &expaliases_flag,
  &inherit_errexit,
  &print_shift_error,
  0
}
Referenced by get_posix_options(), num_posix_options(), and set_posix_options().
saved_posix_vars
char* saved_posix_vars = 0 static
Definition at line 100 of file general.c.
Referenced by posix_initialize(), and save_posix_options().
tdir
char tdir[PATH_MAX] static
Definition at line 898 of file general.c.
Referenced by get_tmpdir(), P_NewChaseDir(), polite_directory_format(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), and sh_realpath().