Fennix Userspace: Userspace/musl/src/thread/sh/__unmapself.c File Reference
__unmapself.c File Reference
#include "pthread_impl.h"
#include "dynlink.h"
#include "../__unmapself.c"
Macros
#define __unmapself __unmapself_sh_nommu
#define CRTJMP(pc, sp)
Functions
hidden void __unmapself_sh_mmu (void *, size_t)
hidden void __unmapself_sh_nommu (void *, size_t)
void __unmapself (void *base, size_t size)
Variables
hidden unsigned __sh_nommu
Macro Definition Documentation
__unmapself
#define __unmapself __unmapself_sh_nommu
Definition at line 7 of file __unmapself.c.
CRTJMP
#define CRTJMP (pc, sp)
Value:
    __asm__ __volatile__( \
    "mov.l @%0+,r0 ; mov.l @%0,r12 ; jmp @r0 ; mov %1,r15" \
    : : "r"(pc), "r"(sp) : "r0", "memory" )
Definition at line 10 of file __unmapself.c.
Function Documentation
__unmapself()
void __unmapself (void * base, size_t size)
Definition at line 20 of file __unmapself.c.
 {
     if (__sh_nommu) __unmapself_sh_nommu(base, size);
     else __unmapself_sh_mmu(base, size);
 }
References __sh_nommu, __unmapself_sh_mmu(), __unmapself_sh_nommu(), base, CRTJMP, do_unmap(), shared_stack, size, stack, unmap_base, and unmap_size.
__unmapself_sh_mmu()
hidden void __unmapself_sh_mmu (void * , size_t)
Referenced by __unmapself().
__unmapself_sh_nommu()
hidden void __unmapself_sh_nommu (void * , size_t)
Referenced by __unmapself().
Variable Documentation
__sh_nommu
hidden unsigned __sh_nommu extern
Definition at line 14 of file __set_thread_area.c.
Referenced by __set_thread_area(), and __unmapself().