Fennix Userspace: Userspace/mlibc/options/posix/include/syslog.h File Reference
syslog.h File Reference
#include <stdarg.h>
Macros
#define LOG_PID 0x01
#define LOG_CONS 0x02
#define LOG_NDELAY 0x08
#define LOG_ODELAY 0x04
#define LOG_NOWAIT 0x10
#define LOG_PERROR 0x20
#define LOG_KERN (0<<3)
#define LOG_USER (1<<3)
#define LOG_MAIL (2<<3)
#define LOG_DAEMON (3<<3)
#define LOG_AUTH (4<<3)
#define LOG_SYSLOG (5<<3)
#define LOG_LPR (6<<3)
#define LOG_NEWS (7<<3)
#define LOG_UUCP (8<<3)
#define LOG_CRON (9<<3)
#define LOG_AUTHPRIV (10<<3)
#define LOG_FTP (11<<3)
#define LOG_LOCAL0 (16<<3)
#define LOG_LOCAL1 (17<<3)
#define LOG_LOCAL2 (18<<3)
#define LOG_LOCAL3 (19<<3)
#define LOG_LOCAL4 (20<<3)
#define LOG_LOCAL5 (21<<3)
#define LOG_LOCAL6 (22<<3)
#define LOG_LOCAL7 (23<<3)
#define LOG_PRIMASK 7
#define LOG_PRI(p) ((p)&LOG_PRIMASK)
#define LOG_MAKEPRI(f, p) (((f)<<3) | (p))
#define LOG_MASK(p) (1<<(p))
#define LOG_UPTO(p) ((1<<((p)+1))-1)
#define LOG_NFACILITIES 24
#define LOG_FACMASK (0x7F<<3)
#define LOG_FAC(p) (((p)&LOG_FACMASK)>>3)
#define LOG_EMERG 0
#define LOG_ALERT 1
#define LOG_CRIT 2
#define LOG_ERR 3
#define LOG_WARNING 4
#define LOG_NOTICE 5
#define LOG_INFO 6
#define LOG_DEBUG 7
Functions
void closelog (void)
void openlog (const char *, int, int)
int setlogmask (int)
void syslog (int, const char *,...)
void vsyslog (int, const char *, va_list)
Macro Definition Documentation
LOG_ALERT
#define LOG_ALERT 1
Definition at line 50 of file syslog.h.
LOG_AUTH
#define LOG_AUTH (4<<3)
Definition at line 22 of file syslog.h.
LOG_AUTHPRIV
#define LOG_AUTHPRIV (10<<3)
Definition at line 28 of file syslog.h.
LOG_CONS
#define LOG_CONS 0x02
Definition at line 12 of file syslog.h.
LOG_CRIT
#define LOG_CRIT 2
Definition at line 51 of file syslog.h.
LOG_CRON
#define LOG_CRON (9<<3)
Definition at line 27 of file syslog.h.
LOG_DAEMON
#define LOG_DAEMON (3<<3)
Definition at line 21 of file syslog.h.
LOG_DEBUG
#define LOG_DEBUG 7
Definition at line 56 of file syslog.h.
LOG_EMERG
#define LOG_EMERG 0
Definition at line 49 of file syslog.h.
LOG_ERR
#define LOG_ERR 3
Definition at line 52 of file syslog.h.
LOG_FAC
#define LOG_FAC (p) (((p)&LOG_FACMASK)>>3)
Definition at line 47 of file syslog.h.
LOG_FACMASK
#define LOG_FACMASK (0x7F<<3)
Definition at line 46 of file syslog.h.
LOG_FTP
#define LOG_FTP (11<<3)
Definition at line 29 of file syslog.h.
LOG_INFO
#define LOG_INFO 6
Definition at line 55 of file syslog.h.
LOG_KERN
#define LOG_KERN (0<<3)
Definition at line 18 of file syslog.h.
LOG_LOCAL0
#define LOG_LOCAL0 (16<<3)
Definition at line 31 of file syslog.h.
LOG_LOCAL1
#define LOG_LOCAL1 (17<<3)
Definition at line 32 of file syslog.h.
LOG_LOCAL2
#define LOG_LOCAL2 (18<<3)
Definition at line 33 of file syslog.h.
LOG_LOCAL3
#define LOG_LOCAL3 (19<<3)
Definition at line 34 of file syslog.h.
LOG_LOCAL4
#define LOG_LOCAL4 (20<<3)
Definition at line 35 of file syslog.h.
LOG_LOCAL5
#define LOG_LOCAL5 (21<<3)
Definition at line 36 of file syslog.h.
LOG_LOCAL6
#define LOG_LOCAL6 (22<<3)
Definition at line 37 of file syslog.h.
LOG_LOCAL7
#define LOG_LOCAL7 (23<<3)
Definition at line 38 of file syslog.h.
LOG_LPR
#define LOG_LPR (6<<3)
Definition at line 24 of file syslog.h.
LOG_MAIL
#define LOG_MAIL (2<<3)
Definition at line 20 of file syslog.h.
LOG_MAKEPRI
#define LOG_MAKEPRI (f, p) (((f)<<3) | (p))
Definition at line 42 of file syslog.h.
LOG_MASK
#define LOG_MASK (p) (1<<(p))
Definition at line 43 of file syslog.h.
LOG_NDELAY
#define LOG_NDELAY 0x08
Definition at line 13 of file syslog.h.
LOG_NEWS
#define LOG_NEWS (7<<3)
Definition at line 25 of file syslog.h.
LOG_NFACILITIES
#define LOG_NFACILITIES 24
Definition at line 45 of file syslog.h.
LOG_NOTICE
#define LOG_NOTICE 5
Definition at line 54 of file syslog.h.
LOG_NOWAIT
#define LOG_NOWAIT 0x10
Definition at line 15 of file syslog.h.
LOG_ODELAY
#define LOG_ODELAY 0x04
Definition at line 14 of file syslog.h.
LOG_PERROR
#define LOG_PERROR 0x20
Definition at line 16 of file syslog.h.
LOG_PID
#define LOG_PID 0x01
Definition at line 11 of file syslog.h.
LOG_PRI
#define LOG_PRI (p) ((p)&LOG_PRIMASK)
Definition at line 41 of file syslog.h.
LOG_PRIMASK
#define LOG_PRIMASK 7
Definition at line 40 of file syslog.h.
LOG_SYSLOG
#define LOG_SYSLOG (5<<3)
Definition at line 23 of file syslog.h.
LOG_UPTO
#define LOG_UPTO (p) ((1<<((p)+1))-1)
Definition at line 44 of file syslog.h.
LOG_USER
#define LOG_USER (1<<3)
Definition at line 19 of file syslog.h.
LOG_UUCP
#define LOG_UUCP (8<<3)
Definition at line 26 of file syslog.h.
LOG_WARNING
#define LOG_WARNING 4
Definition at line 53 of file syslog.h.
Function Documentation
closelog()
void closelog (void)
Definition at line 32 of file syslog-stubs.cpp.
                     {
     frg::unique_lock<FutexLock> holder { __syslog_lock };
     close(log_fd);
     log_fd = -1;
 }
References __syslog_lock, close(), and log_fd.
openlog()
void openlog (const char * ident, int options, int facility)
Definition at line 49 of file syslog-stubs.cpp.
{
     frg::unique_lock<FutexLock> holder { __syslog_lock };
     if(ident) {
         size_t n = strnlen(ident, sizeof log_ident - 1);
         memcpy(log_ident, ident, n);
         log_ident[n] = 0;
     } else {
         log_ident[0] = 0;
     }
     log_options = options;
     log_facility = facility;
     if((options & LOG_NDELAY) && log_fd < 0)
         __openlog();
 }
References __openlog(), __syslog_lock, log_facility, log_fd, log_ident, LOG_NDELAY, log_options, memcpy(), n, options, and strnlen().
setlogmask()
int setlogmask (int mask)
Definition at line 65 of file syslog-stubs.cpp.
{
     int old_mask = log_mask;
     log_mask = mask;
     return old_mask;
 }
References log_mask.
syslog()
void syslog (int priority, const char * format, ...)
Definition at line 135 of file syslog-stubs.cpp.
{
     va_list ap;
     va_start(ap, format);
     vsyslog(priority, format, ap);
     va_end(ap);
 }
References format, va_end(), va_start(), and vsyslog().
vsyslog()
void vsyslog (int priority, const char * message, va_list ap)
Definition at line 142 of file syslog-stubs.cpp.
{
     int cs;
     if(!(log_mask & LOG_MASK(priority & 7)) || (priority & ~0x3ff)) {
         mlibc::infoLogger() << "\e[31mmlibc: syslog: log_mask or priority out of range, not printing anything\e[39m" << frg::endlog;
         return;
     }
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     frg::unique_lock<FutexLock> lock(__syslog_lock);
     _vsyslog(priority, message, ap);
     pthread_setcancelstate(cs, 0);
 }
References __syslog_lock, _vsyslog(), mlibc::infoLogger, log_mask, LOG_MASK, PTHREAD_CANCEL_DISABLE, and pthread_setcancelstate().
Referenced by syslog().