Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_random.c File Reference
m_random.c File Reference
Functions
int P_Random (void)
int M_Random (void)
void M_ClearRandom (void)
Variables
static const unsigned char rndtable [256]
int rndindex = 0
int prndindex = 0
Function Documentation
M_ClearRandom()
void M_ClearRandom (void)
Definition at line 62 of file m_random.c.
 {
     rndindex = prndindex = 0;
 }
References prndindex, and rndindex.
Referenced by G_InitNew().
M_Random()
int M_Random (void)
Definition at line 56 of file m_random.c.
 {
     rndindex = (rndindex+1)&0xff;
     return rndtable[rndindex];
 }
References rndindex, and rndtable.
Referenced by ST_Ticker(), WI_initAnimatedBack(), WI_updateAnimatedBack(), and wipe_initMelt().
P_Random()
int P_Random (void)
Definition at line 50 of file m_random.c.
 {
     prndindex = (prndindex+1)&0xff;
     return rndtable[prndindex];
 }
References prndindex, and rndtable.
Referenced by A_BFGSpray(), A_BrainExplode(), A_BrainScream(), A_BruisAttack(), A_Chase(), A_CPosAttack(), A_CPosRefire(), A_FaceTarget(), A_FirePlasma(), A_FireShotgun2(), A_HeadAttack(), A_Look(), A_PosAttack(), A_Punch(), A_SargAttack(), A_Saw(), A_Scream(), A_SkelFist(), A_SpawnFly(), A_SpidRefire(), A_SPosAttack(), A_Tracer(), A_TroopAttack(), EV_DoPlat(), G_DeathMatchSpawnPlayer(), P_CheckMissileRange(), P_CheckMissileSpawn(), P_DamageMobj(), P_ExplodeMissile(), P_GunShot(), P_KillMobj(), P_MobjThinker(), P_NewChaseDir(), P_PlayerInSpecialSector(), P_SpawnBlood(), P_SpawnLightFlash(), P_SpawnMapThing(), P_SpawnMissile(), P_SpawnMobj(), P_SpawnPuff(), P_SpawnStrobeFlash(), P_TryWalk(), PIT_ChangeSector(), PIT_CheckThing(), T_FireFlicker(), and T_LightFlash().
Variable Documentation
prndindex
int prndindex = 0
Definition at line 47 of file m_random.c.
Referenced by M_ClearRandom(), and P_Random().
rndindex
int rndindex = 0
Definition at line 46 of file m_random.c.
Referenced by G_Ticker(), M_ClearRandom(), and M_Random().
rndtable
const unsigned char rndtable[256] static
Initial value:
= {
    0,   8, 109, 220, 222, 241, 149, 107,  75, 248, 254, 140,  16,  66 ,
    74,  21, 211,  47,  80, 242, 154,  27, 205, 128, 161,  89,  77,  36 ,
    95, 110,  85,  48, 212, 140, 211, 249,  22,  79, 200,  50,  28, 188 ,
    52, 140, 202, 120,  68, 145,  62,  70, 184, 190,  91, 197, 152, 224 ,
    149, 104,  25, 178, 252, 182, 202, 182, 141, 197,   4,  81, 181, 242 ,
    145,  42,  39, 227, 156, 198, 225, 193, 219,  93, 122, 175, 249,   0 ,
    175, 143,  70, 239,  46, 246, 163,  53, 163, 109, 168, 135,   2, 235 ,
    25,  92,  20, 145, 138,  77,  69, 166,  78, 176, 173, 212, 166, 113 ,
    94, 161,  41,  50, 239,  49, 111, 164,  70,  60,   2,  37, 171,  75 ,
    136, 156,  11,  56,  42, 146, 138, 229,  73, 146,  77,  61,  98, 196 ,
    135, 106,  63, 197, 195,  86,  96, 203, 113, 101, 170, 247, 181, 113 ,
    80, 250, 108,   7, 255, 237, 129, 226,  79, 107, 112, 166, 103, 241 ,
    24, 223, 239, 120, 198,  58,  60,  82, 128,   3, 184,  66, 143, 224 ,
    145, 224,  81, 206, 163,  45,  63,  90, 168, 114,  59,  33, 159,  95 ,
    28, 139, 123,  98, 125, 196,  15,  70, 194, 253,  54,  14, 109, 226 ,
    71,  17, 161,  93, 186,  87, 244, 138,  20,  52, 123, 251,  26,  36 ,
    17,  46,  52, 231, 232,  76,  31, 221,  84,  37, 216, 165, 212, 106 ,
    197, 242,  98,  43,  39, 175, 254, 145, 190,  84, 118, 222, 187, 136 ,
    120, 163, 236, 249
}
Definition at line 24 of file m_random.c.
Referenced by M_Random(), and P_Random().