Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/f_finale.c File Reference
f_finale.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "deh_main.h"
#include "i_system.h"
#include "i_swap.h"
#include "z_zone.h"
#include "v_video.h"
#include "w_wad.h"
#include "s_sound.h"
#include "d_main.h"
#include "dstrings.h"
#include "sounds.h"
#include "doomstat.h"
#include "r_state.h"
#include "hu_stuff.h"
Data Structures
struct textscreen_t
struct castinfo_t
Macros
#define TEXTSPEED 3
#define TEXTWAIT 250
Enumerations
enum finalestage_t { F_STAGE_TEXT , F_STAGE_ARTSCREEN , F_STAGE_CAST }
Functions
void F_StartCast (void)
void F_CastTicker (void)
boolean F_CastResponder (event_t *ev)
void F_CastDrawer (void)
void F_StartFinale (void)
boolean F_Responder (event_t *event)
void F_Ticker (void)
void F_TextWrite (void)
void F_CastPrint (char *text)
void F_DrawPatchCol (int x, patch_t *patch, int col)
void F_BunnyScroll (void)
static void F_ArtScreenDrawer (void)
void F_Drawer (void)
Variables
finalestage_t finalestage
unsigned int finalecount
static textscreen_t textscreens []
char * finaletext
char * finaleflat
patch_t * hu_font [HU_FONTSIZE]
castinfo_t castorder []
int castnum
int casttics
state_t * caststate
boolean castdeath
int castframes
int castonmelee
boolean castattacking
Data Structure Documentation
textscreen_t
struct textscreen_t
Definition at line 60 of file f_finale.c.
Data Fields
char * background
int episode
int level
GameMission_t mission
char * text
castinfo_t
struct castinfo_t
Definition at line 300 of file f_finale.c.
Data Fields
char * name
mobjtype_t type
Macro Definition Documentation
TEXTSPEED
#define TEXTSPEED 3
Definition at line 57 of file f_finale.c.
TEXTWAIT
#define TEXTWAIT 250
Definition at line 58 of file f_finale.c.
Enumeration Type Documentation
finalestage_t
enum finalestage_t
Enumerator
F_STAGE_TEXT
F_STAGE_ARTSCREEN
F_STAGE_CAST
Definition at line 40 of file f_finale.c.
 {
     F_STAGE_TEXT,
     F_STAGE_ARTSCREEN,
     F_STAGE_CAST,
 } finalestage_t;
Function Documentation
F_ArtScreenDrawer()
static void F_ArtScreenDrawer (void) static
Definition at line 661 of file f_finale.c.
 {
     char *lumpname;
     if (gameepisode == 3)
     {
         F_BunnyScroll();
     }
     else
     {
         switch (gameepisode)
         {
             case 1:
                 if (gamemode == retail)
                 {
                     lumpname = "CREDIT";
                 }
                 else
                 {
                     lumpname = "HELP2";
                 }
                 break;
             case 2:
                 lumpname = "VICTORY2";
                 break;
             case 4:
                 lumpname = "ENDPIC";
                 break;
             default:
                 return;
         }
         lumpname = DEH_String(lumpname);
         V_DrawPatch (0, 0, W_CacheLumpName(lumpname, PU_CACHE));
     }
 }
References DEH_String, F_BunnyScroll(), gameepisode, gamemode, PU_CACHE, retail, V_DrawPatch(), and W_CacheLumpName().
Referenced by F_Drawer().
F_BunnyScroll()
void F_BunnyScroll (void)
Definition at line 606 of file f_finale.c.
 {
     signed int  scrolled;
     int     x;
     patch_t*    p1;
     patch_t*    p2;
     char    name[10];
     int     stage;
     static int  laststage;
     p1 = W_CacheLumpName (DEH_String("PFUB2"), PU_LEVEL);
     p2 = W_CacheLumpName (DEH_String("PFUB1"), PU_LEVEL);
     V_MarkRect (0, 0, SCREENWIDTH, SCREENHEIGHT);
     scrolled = (320 - ((signed int) finalecount-230)/2);
     if (scrolled > 320)
     scrolled = 320;
     if (scrolled < 0)
     scrolled = 0;
     for ( x=0 ; x<SCREENWIDTH ; x++)
     {
     if (x+scrolled < 320)
         F_DrawPatchCol (x, p1, x+scrolled);
     else
         F_DrawPatchCol (x, p2, x+scrolled - 320);
     }
     if (finalecount < 1130)
     return;
     if (finalecount < 1180)
     {
         V_DrawPatch((SCREENWIDTH - 13 * 8) / 2,
                     (SCREENHEIGHT - 8 * 8) / 2,
                     W_CacheLumpName(DEH_String("END0"), PU_CACHE));
     laststage = 0;
     return;
     }
     stage = (finalecount-1180) / 5;
     if (stage > 6)
     stage = 6;
     if (stage > laststage)
     {
     S_StartSound (NULL, sfx_pistol);
     laststage = stage;
     }
     DEH_snprintf(name, 10, "END%i", stage);
     V_DrawPatch((SCREENWIDTH - 13 * 8) / 2,
                 (SCREENHEIGHT - 8 * 8) / 2,
                 W_CacheLumpName (name,PU_CACHE));
 }
References DEH_snprintf, DEH_String, F_DrawPatchCol(), finalecount, int, name, NULL, PU_CACHE, PU_LEVEL, S_StartSound(), SCREENHEIGHT, SCREENWIDTH, sfx_pistol, V_DrawPatch(), V_MarkRect(), W_CacheLumpName(), and x.
Referenced by F_ArtScreenDrawer().
F_CastDrawer()
void F_CastDrawer (void)
Definition at line 541 of file f_finale.c.
 {
     spritedef_t*    sprdef;
     spriteframe_t*  sprframe;
     int         lump;
     boolean     flip;
     patch_t*        patch;
     // erase the entire screen to a background
     V_DrawPatch (0, 0, W_CacheLumpName (DEH_String("BOSSBACK"), PU_CACHE));
     F_CastPrint (DEH_String(castorder[castnum].name));
     // draw the current frame in the middle of the screen
     sprdef = &sprites[caststate->sprite];
     sprframe = &sprdef->spriteframes[ caststate->frame & FF_FRAMEMASK];
     lump = sprframe->lump[0];
     flip = (boolean)sprframe->flip[0];
     patch = W_CacheLumpNum (lump+firstspritelump, PU_CACHE);
     if (flip)
     V_DrawPatchFlipped(160, 170, patch);
     else
     V_DrawPatch(160, 170, patch);
 }
References castnum, castorder, caststate, DEH_String, F_CastPrint(), FF_FRAMEMASK, firstspritelump, spriteframe_t::flip, state_t::frame, spriteframe_t::lump, name, PU_CACHE, state_t::sprite, spritedef_t::spriteframes, sprites, V_DrawPatch(), V_DrawPatchFlipped(), W_CacheLumpName(), and W_CacheLumpNum().
Referenced by F_Drawer().
F_CastPrint()
void F_CastPrint (char * text)
Definition at line 486 of file f_finale.c.
 {
     char*   ch;
     int     c;
     int     cx;
     int     w;
     int     width;
     // find width
     ch = text;
     width = 0;
     while (ch)
     {
     c = *ch++;
     if (!c)
         break;
     c = toupper(c) - HU_FONTSTART;
     if (c < 0 || c> HU_FONTSIZE)
     {
         width += 4;
         continue;
     }
     w = SHORT (hu_font[c]->width);
     width += w;
     }
     // draw it
     cx = 160-width/2;
     ch = text;
     while (ch)
     {
     c = *ch++;
     if (!c)
         break;
     c = toupper(c) - HU_FONTSTART;
     if (c < 0 || c> HU_FONTSIZE)
     {
         cx += 4;
         continue;
     }
     w = SHORT (hu_font[c]->width);
     V_DrawPatch(cx, 180, hu_font[c]);
     cx+=w;
     }
 }
References c, hu_font, HU_FONTSIZE, HU_FONTSTART, SHORT, toupper, and V_DrawPatch().
Referenced by F_CastDrawer().
F_CastResponder()
boolean F_CastResponder (event_t * ev)
Definition at line 465 of file f_finale.c.
 {
     if (ev->type != ev_keydown)
     return false;
     if (castdeath)
     return true;            // already in dying frames
     // go into death frame
     castdeath = true;
     caststate = &states[mobjinfo[castorder[castnum].type].deathstate];
     casttics = caststate->tics;
     castframes = 0;
     castattacking = false;
     if (mobjinfo[castorder[castnum].type].deathsound)
     S_StartSound (NULL, mobjinfo[castorder[castnum].type].deathsound);
     return true;
 }
References castattacking, castdeath, castframes, castnum, castorder, caststate, casttics, mobjinfo_t::deathstate, ev_keydown, mobjinfo, NULL, S_StartSound(), states, state_t::tics, event_t::type, and castinfo_t::type.
Referenced by F_Responder().
F_CastTicker()
void F_CastTicker (void)
Definition at line 358 of file f_finale.c.
 {
     int     st;
     int     sfx;
     if (--casttics > 0)
     return;         // not time to change state yet
     if (caststate->tics == -1 || caststate->nextstate == S_NULL)
     {
     // switch from deathstate to next monster
     castnum++;
     castdeath = false;
     if (castorder[castnum].name == NULL)
         castnum = 0;
     if (mobjinfo[castorder[castnum].type].seesound)
         S_StartSound (NULL, mobjinfo[castorder[castnum].type].seesound);
     caststate = &states[mobjinfo[castorder[castnum].type].seestate];
     castframes = 0;
     }
     else
     {
     // just advance to next state in animation
     if (caststate == &states[S_PLAY_ATK1])
         goto stopattack;    // Oh, gross hack!
     st = caststate->nextstate;
     caststate = &states[st];
     castframes++;
     // sound hacks....
     switch (st)
     {
       case S_PLAY_ATK1: sfx = sfx_dshtgn; break;
       case S_POSS_ATK2: sfx = sfx_pistol; break;
       case S_SPOS_ATK2: sfx = sfx_shotgn; break;
       case S_VILE_ATK2: sfx = sfx_vilatk; break;
       case S_SKEL_FIST2:    sfx = sfx_skeswg; break;
       case S_SKEL_FIST4:    sfx = sfx_skepch; break;
       case S_SKEL_MISS2:    sfx = sfx_skeatk; break;
       case S_FATT_ATK8:
       case S_FATT_ATK5:
       case S_FATT_ATK2: sfx = sfx_firsht; break;
       case S_CPOS_ATK2:
       case S_CPOS_ATK3:
       case S_CPOS_ATK4: sfx = sfx_shotgn; break;
       case S_TROO_ATK3: sfx = sfx_claw; break;
       case S_SARG_ATK2: sfx = sfx_sgtatk; break;
       case S_BOSS_ATK2:
       case S_BOS2_ATK2:
       case S_HEAD_ATK2: sfx = sfx_firsht; break;
       case S_SKULL_ATK2:    sfx = sfx_sklatk; break;
       case S_SPID_ATK2:
       case S_SPID_ATK3: sfx = sfx_shotgn; break;
       case S_BSPI_ATK2: sfx = sfx_plasma; break;
       case S_CYBER_ATK2:
       case S_CYBER_ATK4:
       case S_CYBER_ATK6:    sfx = sfx_rlaunc; break;
       case S_PAIN_ATK3: sfx = sfx_sklatk; break;
       default: sfx = 0; break;
     }
     if (sfx)
         S_StartSound (NULL, sfx);
     }
     if (castframes == 12)
     {
     // go into attack frame
     castattacking = true;
     if (castonmelee)
         caststate=&states[mobjinfo[castorder[castnum].type].meleestate];
     else
         caststate=&states[mobjinfo[castorder[castnum].type].missilestate];
     castonmelee ^= 1;
     if (caststate == &states[S_NULL])
     {
         if (castonmelee)
         caststate=
             &states[mobjinfo[castorder[castnum].type].meleestate];
         else
         caststate=
             &states[mobjinfo[castorder[castnum].type].missilestate];
     }
     }
     if (castattacking)
     {
     if (castframes == 24
         ||  caststate == &states[mobjinfo[castorder[castnum].type].seestate] )
     {
       stopattack:
         castattacking = false;
         castframes = 0;
         caststate = &states[mobjinfo[castorder[castnum].type].seestate];
     }
     }
     casttics = caststate->tics;
     if (casttics == -1)
     casttics = 15;
 }
References castattacking, castdeath, castframes, castnum, castonmelee, castorder, caststate, casttics, mobjinfo_t::meleestate, mobjinfo_t::missilestate, mobjinfo, name, state_t::nextstate, NULL, S_BOS2_ATK2, S_BOSS_ATK2, S_BSPI_ATK2, S_CPOS_ATK2, S_CPOS_ATK3, S_CPOS_ATK4, S_CYBER_ATK2, S_CYBER_ATK4, S_CYBER_ATK6, S_FATT_ATK2, S_FATT_ATK5, S_FATT_ATK8, S_HEAD_ATK2, S_NULL, S_PAIN_ATK3, S_PLAY_ATK1, S_POSS_ATK2, S_SARG_ATK2, S_SKEL_FIST2, S_SKEL_FIST4, S_SKEL_MISS2, S_SKULL_ATK2, S_SPID_ATK2, S_SPID_ATK3, S_SPOS_ATK2, S_StartSound(), S_TROO_ATK3, S_VILE_ATK2, mobjinfo_t::seestate, sfx_claw, sfx_dshtgn, sfx_firsht, sfx_pistol, sfx_plasma, sfx_rlaunc, sfx_sgtatk, sfx_shotgn, sfx_skeatk, sfx_skepch, sfx_skeswg, sfx_sklatk, sfx_vilatk, states, state_t::tics, and castinfo_t::type.
Referenced by F_Ticker().
F_Drawer()
void F_Drawer (void)
Definition at line 702 of file f_finale.c.
 {
     switch (finalestage)
     {
         case F_STAGE_CAST:
             F_CastDrawer();
             break;
         case F_STAGE_TEXT:
             F_TextWrite();
             break;
         case F_STAGE_ARTSCREEN:
             F_ArtScreenDrawer();
             break;
     }
 }
References F_ArtScreenDrawer(), F_CastDrawer(), F_STAGE_ARTSCREEN, F_STAGE_CAST, F_STAGE_TEXT, F_TextWrite(), and finalestage.
Referenced by D_Display().
F_DrawPatchCol()
void F_DrawPatchCol (int x, patch_t * patch, int col)
Definition at line 572 of file f_finale.c.
 {
     column_t*   column;
     byte*   source;
     byte*   dest;
     byte*   desttop;
     int     count;
     column = (column_t *)((byte *)patch + LONG(patch->columnofs[col]));
     desttop = I_VideoBuffer + x;
     // step through the posts in a column
     while (column->topdelta != 0xff )
     {
     source = (byte *)column + 3;
     dest = desttop + column->topdelta*SCREENWIDTH;
     count = column->length;
     while (count--)
     {
         *dest = *source++;
         dest += SCREENWIDTH;
     }
     column = (column_t *)(  (byte *)column + column->length + 4 );
     }
 }
References mlibc::count, I_VideoBuffer, LONG, SCREENWIDTH, and x.
Referenced by F_BunnyScroll().
F_Responder()
boolean F_Responder (event_t * event)
Definition at line 160 of file f_finale.c.
 {
     if (finalestage == F_STAGE_CAST)
     return F_CastResponder (event);
     return false;
 }
References F_CastResponder(), F_STAGE_CAST, and finalestage.
Referenced by G_Responder().
F_StartCast()
void F_StartCast (void)
Definition at line 340 of file f_finale.c.
 {
     wipegamestate = -1;     // force a screen wipe
     castnum = 0;
     caststate = &states[mobjinfo[castorder[castnum].type].seestate];
     casttics = caststate->tics;
     castdeath = false;
     finalestage = F_STAGE_CAST;
     castframes = 0;
     castonmelee = 0;
     castattacking = false;
     S_ChangeMusic(mus_evil, true);
 }
References castattacking, castdeath, castframes, castnum, castonmelee, castorder, caststate, casttics, F_STAGE_CAST, finalestage, mobjinfo, mus_evil, S_ChangeMusic(), mobjinfo_t::seestate, states, state_t::tics, castinfo_t::type, and wipegamestate.
Referenced by F_Ticker().
F_StartFinale()
void F_StartFinale (void)
Definition at line 108 of file f_finale.c.
 {
     size_t i;
     gameaction = ga_nothing;
     gamestate = GS_FINALE;
     viewactive = false;
     automapactive = false;
     if (logical_gamemission == doom)
     {
         S_ChangeMusic(mus_victor, true);
     }
     else
     {
         S_ChangeMusic(mus_read_m, true);
     }
     // Find the right screen and set the text and background
     for (i=0; i<arrlen(textscreens); ++i)
     {
         textscreen_t *screen = &textscreens[i];
         // Hack for Chex Quest
         if (gameversion == exe_chex && screen->mission == doom)
         {
             screen->level = 5;
         }
         if (logical_gamemission == screen->mission
          && (logical_gamemission != doom || gameepisode == screen->episode)
          && gamemap == screen->level)
         {
             finaletext = screen->text;
             finaleflat = screen->background;
         }
     }
     // Do dehacked substitutions of strings
     finaletext = DEH_String(finaletext);
     finaleflat = DEH_String(finaleflat);
     finalestage = F_STAGE_TEXT;
     finalecount = 0;
 }
References arrlen, automapactive, textscreen_t::background, DEH_String, doom, textscreen_t::episode, exe_chex, F_STAGE_TEXT, finalecount, finaleflat, finalestage, finaletext, ga_nothing, gameaction, gameepisode, gamemap, gamestate, gameversion, GS_FINALE, i, textscreen_t::level, logical_gamemission, textscreen_t::mission, mus_read_m, mus_victor, S_ChangeMusic(), textscreen_t::text, textscreens, and viewactive.
Referenced by G_Ticker(), and G_WorldDone().
F_TextWrite()
void F_TextWrite (void)
Definition at line 227 of file f_finale.c.
 {
     byte*   src;
     byte*   dest;
     int     x,y,w;
     signed int  count;
     char*   ch;
     int     c;
     int     cx;
     int     cy;
     // erase the entire screen to a tiled background
     src = W_CacheLumpName ( finaleflat , PU_CACHE);
     dest = I_VideoBuffer;
     for (y=0 ; y<SCREENHEIGHT ; y++)
     {
     for (x=0 ; x<SCREENWIDTH/64 ; x++)
     {
         memcpy (dest, src+((y&63)<<6), 64);
         dest += 64;
     }
     if (SCREENWIDTH&63)
     {
         memcpy (dest, src+((y&63)<<6), SCREENWIDTH&63);
         dest += (SCREENWIDTH&63);
     }
     }
     V_MarkRect (0, 0, SCREENWIDTH, SCREENHEIGHT);
     // draw some of the text onto the screen
     cx = 10;
     cy = 10;
     ch = finaletext;
     count = ((signed int) finalecount - 10) / TEXTSPEED;
     if (count < 0)
     count = 0;
     for ( ; count ; count-- )
     {
     c = *ch++;
     if (!c)
         break;
     if (c == '\n')
     {
         cx = 10;
         cy += 11;
         continue;
     }
     c = toupper(c) - HU_FONTSTART;
     if (c < 0 || c> HU_FONTSIZE)
     {
         cx += 4;
         continue;
     }
     w = SHORT (hu_font[c]->width);
     if (cx+w > SCREENWIDTH)
         break;
     V_DrawPatch(cx, cy, hu_font[c]);
     cx+=w;
     }
 }
References c, mlibc::count, finalecount, finaleflat, finaletext, hu_font, HU_FONTSIZE, HU_FONTSTART, I_VideoBuffer, int, memcpy(), PU_CACHE, SCREENHEIGHT, SCREENWIDTH, SHORT, TEXTSPEED, toupper, V_DrawPatch(), V_MarkRect(), W_CacheLumpName(), x, and y.
Referenced by F_Drawer().
F_Ticker()
void F_Ticker (void)
Definition at line 172 of file f_finale.c.
 {
     size_t      i;
     // check for skipping
     if ( (gamemode == commercial)
       && ( finalecount > 50) )
     {
       // go on to the next level
       for (i=0 ; i<MAXPLAYERS ; i++)
     if (players[i].cmd.buttons)
       break;
       if (i < MAXPLAYERS)
       {
     if (gamemap == 30)
       F_StartCast ();
     else
       gameaction = ga_worlddone;
       }
     }
     // advance animation
     finalecount++;
     if (finalestage == F_STAGE_CAST)
     {
     F_CastTicker ();
     return;
     }
     if ( gamemode == commercial)
     return;
     if (finalestage == F_STAGE_TEXT
      && finalecount>strlen (finaletext)*TEXTSPEED + TEXTWAIT)
     {
     finalecount = 0;
     finalestage = F_STAGE_ARTSCREEN;
     wipegamestate = -1;     // force a wipe
     if (gameepisode == 3)
         S_StartMusic (mus_bunny);
     }
 }
References commercial, F_CastTicker(), F_STAGE_ARTSCREEN, F_STAGE_CAST, F_STAGE_TEXT, F_StartCast(), finalecount, finalestage, finaletext, ga_worlddone, gameaction, gameepisode, gamemap, gamemode, i, MAXPLAYERS, mus_bunny, players, S_StartMusic(), strlen(), TEXTSPEED, TEXTWAIT, and wipegamestate.
Referenced by G_Ticker().
Variable Documentation
castattacking
boolean castattacking
Definition at line 334 of file f_finale.c.
Referenced by F_CastResponder(), F_CastTicker(), and F_StartCast().
castdeath
boolean castdeath
Definition at line 331 of file f_finale.c.
Referenced by F_CastResponder(), F_CastTicker(), and F_StartCast().
castframes
int castframes
Definition at line 332 of file f_finale.c.
Referenced by F_CastResponder(), F_CastTicker(), and F_StartCast().
castnum
int castnum
Definition at line 328 of file f_finale.c.
Referenced by F_CastDrawer(), F_CastResponder(), F_CastTicker(), and F_StartCast().
castonmelee
int castonmelee
Definition at line 333 of file f_finale.c.
Referenced by F_CastTicker(), and F_StartCast().
castorder
castinfo_t castorder[]
Initial value:
= {
    {CC_ZOMBIE, MT_POSSESSED},
    {CC_SHOTGUN, MT_SHOTGUY},
    {CC_HEAVY, MT_CHAINGUY},
    {CC_IMP, MT_TROOP},
    {CC_DEMON, MT_SERGEANT},
    {CC_LOST, MT_SKULL},
    {CC_CACO, MT_HEAD},
    {CC_HELL, MT_KNIGHT},
    {CC_BARON, MT_BRUISER},
    {CC_ARACH, MT_BABY},
    {CC_PAIN, MT_PAIN},
    {CC_REVEN, MT_UNDEAD},
    {CC_MANCU, MT_FATSO},
    {CC_ARCH, MT_VILE},
    {CC_SPIDER, MT_SPIDER},
    {CC_CYBER, MT_CYBORG},
    {CC_HERO, MT_PLAYER},
    {NULL,0}
}
Definition at line 306 of file f_finale.c.
Referenced by F_CastDrawer(), F_CastResponder(), F_CastTicker(), and F_StartCast().
caststate
state_t* caststate
Definition at line 330 of file f_finale.c.
Referenced by F_CastDrawer(), F_CastResponder(), F_CastTicker(), and F_StartCast().
casttics
int casttics
Definition at line 329 of file f_finale.c.
Referenced by F_CastResponder(), F_CastTicker(), and F_StartCast().
finalecount
unsigned int finalecount
Definition at line 55 of file f_finale.c.
Referenced by F_BunnyScroll(), F_StartFinale(), F_TextWrite(), and F_Ticker().
finaleflat
char* finaleflat
Definition at line 98 of file f_finale.c.
Referenced by F_StartFinale(), and F_TextWrite().
finalestage
finalestage_t finalestage
Definition at line 53 of file f_finale.c.
Referenced by F_Drawer(), F_Responder(), F_StartCast(), F_StartFinale(), and F_Ticker().
finaletext
char* finaletext
Definition at line 97 of file f_finale.c.
Referenced by F_StartFinale(), F_TextWrite(), and F_Ticker().
hu_font
patch_t* hu_font[HU_FONTSIZE] extern
Definition at line 88 of file hu_stuff.c.
Referenced by F_CastPrint(), and F_TextWrite().
textscreens
textscreen_t textscreens[] static
Initial value:
=
{
    { doom,      1, 8,  "FLOOR4_8",  E1TEXT},
    { doom,      2, 8,  "SFLR6_1",   E2TEXT},
    { doom,      3, 8,  "MFLR8_4",   E3TEXT},
    { doom,      4, 8,  "MFLR8_3",   E4TEXT},
    { doom2,     1, 6,  "SLIME16",   C1TEXT},
    { doom2,     1, 11, "RROCK14",   C2TEXT},
    { doom2,     1, 20, "RROCK07",   C3TEXT},
    { doom2,     1, 30, "RROCK17",   C4TEXT},
    { doom2,     1, 15, "RROCK13",   C5TEXT},
    { doom2,     1, 31, "RROCK19",   C6TEXT},
    { pack_tnt,  1, 6,  "SLIME16",   T1TEXT},
    { pack_tnt,  1, 11, "RROCK14",   T2TEXT},
    { pack_tnt,  1, 20, "RROCK07",   T3TEXT},
    { pack_tnt,  1, 30, "RROCK17",   T4TEXT},
    { pack_tnt,  1, 15, "RROCK13",   T5TEXT},
    { pack_tnt,  1, 31, "RROCK19",   T6TEXT},
    { pack_plut, 1, 6,  "SLIME16",   P1TEXT},
    { pack_plut, 1, 11, "RROCK14",   P2TEXT},
    { pack_plut, 1, 20, "RROCK07",   P3TEXT},
    { pack_plut, 1, 30, "RROCK17",   P4TEXT},
    { pack_plut, 1, 15, "RROCK13",   P5TEXT},
    { pack_plut, 1, 31, "RROCK19",   P6TEXT},
}
Definition at line 68 of file f_finale.c.
Referenced by F_StartFinale().