Fennix: Userspace/apps/base/busybox/coreutils/cksum.c File Reference
cksum.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define IS_CKSUM (ENABLE_CKSUM && (!ENABLE_CRC32 || applet_name[1] == 'k'))
#define IS_CRC32 (ENABLE_CRC32 && (!ENABLE_CKSUM || applet_name[1] == 'r'))
#define read_buf bb_common_bufsiz1
Functions
int cksum_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
IS_CKSUM
#define IS_CKSUM (ENABLE_CKSUM && (!ENABLE_CRC32 || applet_name[1] == 'k'))
Definition at line 35 of file cksum.c.
IS_CRC32
#define IS_CRC32 (ENABLE_CRC32 && (!ENABLE_CKSUM || applet_name[1] == 'r'))
Definition at line 36 of file cksum.c.
read_buf
#define read_buf bb_common_bufsiz1
Function Documentation
cksum_main()
int cksum_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 39 of file cksum.c.
 {
     uint32_t *crc32_table = crc32_filltable(NULL, IS_CKSUM);
     int exit_code = EXIT_SUCCESS;
 #if ENABLE_DESKTOP
     getopt32(argv, ""); /* cksum coreutils 6.9 compat */
     argv += optind;
 #else
     argv++;
 #endif
     setup_common_bufsiz();
     do {
         uint32_t crc;
         IF_CKSUM(off_t filesize;)
         const char *fname = *argv ? *argv : bb_msg_standard_input;
         int fd = open_or_warn_stdin(fname);
         if (fd < 0) {
             exit_code = EXIT_FAILURE;
             continue;
         }
         crc = IS_CKSUM ? 0 : 0xffffffff;
         IF_CKSUM(filesize = 0;)
 #define read_buf bb_common_bufsiz1
         for (;;) {
             int bytes_read = safe_read(fd, read_buf, COMMON_BUFSIZE);
             if (bytes_read < 0)
                 bb_simple_perror_msg_and_die(fname);
             if (bytes_read > 0) {
                 IF_CKSUM(filesize += bytes_read;)
             } else {
                 IF_CKSUM(uoff_t t;)
                 close(fd);
                 if (IS_CRC32)
                     break;
 #if ENABLE_CKSUM
                 fd = -1; /* break flag */
                 /* Checksum filesize bytes, LSB first */
                 t = filesize;
                 /*bytes_read = 0; - already is */
                 while (t != 0) {
                     read_buf[bytes_read++] = (uint8_t)t;
                     t >>= 8;
                 }
 #endif
             }
             crc = (IS_CKSUM ? crc32_block_endian1 : crc32_block_endian0)(crc, read_buf, bytes_read, crc32_table);
             if (ENABLE_CKSUM && fd < 0)
                 break;
         }
         crc = ~crc;
 #if ENABLE_CKSUM
         if (IS_CKSUM)
             printf((*argv ? "%u %"OFF_FMT"u %s\n" : "%u %"OFF_FMT"u\n"),
                 (unsigned)crc, filesize, *argv);
         else
 #endif
             printf((*argv ? "%08x %s\n" : "%08x\n"),
                 (unsigned)crc, *argv);
     } while (*argv && *++argv);
     fflush_stdout_and_exit(exit_code);
 }
References argv, bb_simple_perror_msg_and_die(), bytes_read, close(), crc32_block_endian0(), crc32_block_endian1(), crc32_filltable(), EXIT_FAILURE, EXIT_SUCCESS, fd, fflush_stdout_and_exit(), fname, getopt32(), IS_CKSUM, IS_CRC32, NULL, OFF_FMT, off_t, open_or_warn_stdin(), optind, printf, read_buf, safe_read(), and t.