Fennix: Kernel/boot_logo.cpp File Reference
boot_logo.cpp File Reference
#include "kernel.h"
#include <filesystem/ustar.hpp>
#include <kshell.hpp>
#include <power.hpp>
#include <lock.hpp>
#include <printf.h>
#include <exec.hpp>
#include <cwalk.h>
#include <vm.hpp>
#include <vector>
#include <stb/image.h>
#include "mapi.hpp"
#include "Fex.hpp"
Macros
#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_STDIO
#define STBI_NO_LINEAR
#define STBI_NO_THREAD_LOCALS
#define STBI_NO_HDR
#define STBI_ONLY_TGA
Functions
void BootLogoAnimationThread ()
void ExitLogoAnimationThread ()
Variables
uint8_t * Frames [27]
uint32_t FrameSizes [27]
size_t FrameCount = 1
Macro Definition Documentation
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 29 of file boot_logo.cpp.
STBI_NO_HDR
#define STBI_NO_HDR
Definition at line 33 of file boot_logo.cpp.
STBI_NO_LINEAR
#define STBI_NO_LINEAR
Definition at line 31 of file boot_logo.cpp.
STBI_NO_STDIO
#define STBI_NO_STDIO
Definition at line 30 of file boot_logo.cpp.
STBI_NO_THREAD_LOCALS
#define STBI_NO_THREAD_LOCALS
Definition at line 32 of file boot_logo.cpp.
STBI_ONLY_TGA
#define STBI_ONLY_TGA
Definition at line 34 of file boot_logo.cpp.
Function Documentation
BootLogoAnimationThread()
void BootLogoAnimationThread ()
Definition at line 47 of file boot_logo.cpp.
 {
     char BootAnimPath[16];
     while (FrameCount < 27)
     {
         sprintf(BootAnimPath, "/etc/boot/%ld.tga", FrameCount);
         RefNode *frame = fs->Open(BootAnimPath);
         if (!frame)
         {
             debug("Failed to load boot animation frame %s", BootAnimPath);
             break;
         }
         FrameSizes[FrameCount] = s_cst(uint32_t, frame->Size);
         Frames[FrameCount] = new uint8_t[frame->Size];
         frame->read(Frames[FrameCount], frame->Size);
         delete frame;
         FrameCount++;
     }
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = 1; i < FrameCount; i++)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i],
                                    &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i],
                                              FrameSizes[i], &x, &y,
                                              &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY,
                               (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
         TaskManager->Sleep(50);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
         TaskManager->Sleep(5);
     }
 }
References channels, debug, Display, FrameCount, Frames, FrameSizes, free, fs, g, Video::Display::GetBuffer(), Video::ScreenBuffer::Height, i, NULL, vfs::Virtual::Open(), vfs::RefNode::read(), Video::Display::SetBrightness(), Video::Display::SetBuffer(), Video::Display::SetPixel(), vfs::RefNode::Size, Tasking::Task::Sleep(), sprintf(), stbi_info_from_memory(), stbi_load_from_memory(), STBI_rgb_alpha, TaskManager, Video::ScreenBuffer::Width, x, and y.
Referenced by KernelMainThread().
ExitLogoAnimationThread()
void ExitLogoAnimationThread ()
Definition at line 122 of file boot_logo.cpp.
 {
     Display->SetBrightness(100, 1);
     Display->SetBuffer(1);
     /* Files: 26.tga 25.tga ... 1.tga */
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = FrameCount - 1; i > 0; i--)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i],
                                    &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i],
                                              FrameSizes[i], &x, &y,
                                              &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY,
                               (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
         TaskManager->Sleep(50);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
         TaskManager->Sleep(5);
     }
 }
References channels, Display, FrameCount, Frames, FrameSizes, free, g, Video::Display::GetBuffer(), Video::ScreenBuffer::Height, i, NULL, Video::Display::SetBrightness(), Video::Display::SetBuffer(), Video::Display::SetPixel(), Tasking::Task::Sleep(), stbi_info_from_memory(), stbi_load_from_memory(), STBI_rgb_alpha, TaskManager, Video::ScreenBuffer::Width, x, and y.
Referenced by KernelShutdownThread().
Variable Documentation
FrameCount
size_t FrameCount = 1
Definition at line 45 of file boot_logo.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
Frames
uint8_t* Frames[27]
Definition at line 43 of file boot_logo.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
FrameSizes
uint32_t FrameSizes[27]
Definition at line 44 of file boot_logo.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().