Fennix Userspace: Userspace/mlibc/options/posix/generic/posix_signal.cpp File Reference
posix_signal.cpp File Reference
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <bits/ensure.h>
#include <mlibc/posix-sysdeps.hpp>
#include <mlibc/tcb.hpp>
Functions
int sigsuspend (const sigset_t *sigmask)
int pthread_sigmask (int how, const sigset_t *__restrict set, sigset_t *__restrict retrieve)
int pthread_kill (pthread_t thread, int sig)
int sigaction (int signum, const struct sigaction *__restrict act, struct sigaction *__restrict oldact)
int siginterrupt (int sig, int flag)
int kill (pid_t pid, int number)
int killpg (pid_t pgrp, int sig)
int sigtimedwait (const sigset_t *__restrict set, siginfo_t *__restrict info, const struct timespec *__restrict timeout)
int sigwaitinfo (const sigset_t *__restrict set, siginfo_t *__restrict info)
int sigwait (const sigset_t *__restrict set, int *__restrict sig)
int sigpending (sigset_t *)
int sigaltstack (const stack_t *__restrict ss, stack_t *__restrict oss)
Function Documentation
kill()
int kill (pid_t pid, int number)
Definition at line 68 of file posix_signal.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_kill, -1);
     if(int e = mlibc::sys_kill(pid, number); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_kill().
Referenced by child_fn(), killpg(), and main().
killpg()
int killpg (pid_t pgrp, int sig)
Definition at line 77 of file posix_signal.cpp.
{
     if(pgrp > 1) {
         return kill(-pgrp, sig);
     }
     errno = EINVAL;
     return -1;
 }
References EINVAL, errno, and kill().
pthread_kill()
int pthread_kill (pthread_t thread, int sig)
Definition at line 29 of file posix_signal.cpp.
{
     auto tcb = reinterpret_cast<Tcb *>(thread);
     auto pid = getpid();
     if(!mlibc::sys_tgkill) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     if(int e = mlibc::sys_tgkill(pid, tcb->tid, sig); e) {
         return e;
     }
     return 0;
 }
References ENOSYS, getpid(), MLIBC_MISSING_SYSDEP, and mlibc::sys_tgkill().
Referenced by main().
pthread_sigmask()
int pthread_sigmask (int how, const sigset_t *__restrict set, sigset_t *__restrict retrieve)
Definition at line 18 of file posix_signal.cpp.
{
     if(!mlibc::sys_sigprocmask) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     if(int e = mlibc::sys_sigprocmask(how, set, retrieve); e) {
         return e;
     }
     return 0;
 }
References ENOSYS, MLIBC_MISSING_SYSDEP, and mlibc::sys_sigprocmask().
Referenced by child(), and posix_spawn().
sigaction()
int sigaction (int signum, const struct sigaction *__restrict act, struct sigaction *__restrict oldact)
Definition at line 45 of file posix_signal.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigaction, -1);
     if(int e = mlibc::sys_sigaction(signum, act, oldact); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_sigaction().
Referenced by child(), main(), siginterrupt(), signal_handler(), and worker().
sigaltstack()
int sigaltstack (const stack_t *__restrict ss, stack_t *__restrict oss)
Definition at line 120 of file posix_signal.cpp.
{
     if (ss && ss->ss_size < MINSIGSTKSZ && !(ss->ss_flags & SS_DISABLE)) {
         errno = ENOMEM;
         return -1;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigaltstack, -1);
     if (int e = mlibc::sys_sigaltstack(ss, oss); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References ENOMEM, errno, MINSIGSTKSZ, MLIBC_CHECK_OR_ENOSYS, SS_DISABLE, and mlibc::sys_sigaltstack().
Referenced by main().
siginterrupt()
int siginterrupt (int sig, int flag)
Definition at line 54 of file posix_signal.cpp.
{
     int ret;
     struct sigaction act;
     sigaction(sig, NULL, &act);
     if (flag)
         act.sa_flags &= ~SA_RESTART;
     else
         act.sa_flags |= SA_RESTART;
     ret = sigaction(sig, &act, NULL);
     return ret;
 }
References NULL, ret, sigaction::sa_flags, SA_RESTART, and sigaction().
sigpending()
int sigpending (sigset_t *)
Definition at line 115 of file posix_signal.cpp.
{
     __ensure(!"sigpending() not implemented");
     __builtin_unreachable();
 }
References __ensure.
sigsuspend()
int sigsuspend (const sigset_t * sigmask)
Definition at line 10 of file posix_signal.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigsuspend, -1);
     // This is guaranteed to return an error (EINTR most probably)
     errno = mlibc::sys_sigsuspend(sigmask);
     return -1;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sigmask, and mlibc::sys_sigsuspend().
Referenced by worker().
sigtimedwait()
int sigtimedwait (const sigset_t *__restrict set, siginfo_t *__restrict info, const struct timespec *__restrict timeout)
Definition at line 86 of file posix_signal.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigtimedwait, -1);
     int signo;
     if (int e = sysdep(set, info, timeout, &signo)) {
         errno = e;
         return -1;
     }
     return signo;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_sigtimedwait(), and mlibc::timeout.
Referenced by parent_fn(), and sigwaitinfo().
sigwait()
int sigwait (const sigset_t *__restrict set, int *__restrict sig)
Definition at line 104 of file posix_signal.cpp.
{
     if (int e = sigwaitinfo(set, nullptr); e < 0) {
         return e;
     } else {
         if (sig)
             *sig = e;
         return 0;
     }
 }
References sigwaitinfo().
Referenced by main(), and parent_fn().
sigwaitinfo()
int sigwaitinfo (const sigset_t *__restrict set, siginfo_t *__restrict info)
Definition at line 99 of file posix_signal.cpp.
{
     // NOTE: This assumes the sysdep behavior noted in mlibc/posix-sysdeps.hpp
     return sigtimedwait(set, info, nullptr);
 }
References sigtimedwait().
Referenced by parent_fn(), and sigwait().