Fennix Userspace: Userspace/apps/base/bash/examples/loadables/dirname.c File Reference
dirname.c File Reference
#include "config.h"
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
#include "bashgetopt.h"
Functions
int dirname_builtin (WORD_LIST *list)
Variables
char * dirname_doc []
struct builtin dirname_struct
Function Documentation
dirname_builtin()
int dirname_builtin (WORD_LIST * list)
Definition at line 36 of file dirname.c.
 {
   int slen;
   char *string;
   if (no_options (list))
     return (EX_USAGE);
   list = loptend;
   if (list == 0 || list->next)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   string = list->word->word;
   slen = strlen (string);
   /* Strip trailing slashes */
   while (slen > 0 && string[slen - 1] == '/')
     slen--;
   /* (2) If string consists entirely of slash characters, string shall be
      set to a single slash character.  In this case, skip steps (3)
      through (8). */
   if (slen == 0)
     {
       fputs ("/\n", stdout);
       return (EXECUTION_SUCCESS);
     }
   /* (3) If there are any trailing slash characters in string, they
      shall be removed. */
   string[slen] = '\0';
   /* (4) If there are no slash characters remaining in string, string
      shall be set to a single period character.  In this case, skip
      steps (5) through (8).
      (5) If there are any trailing nonslash characters in string,
      they shall be removed. */
   while (--slen >= 0)
     if (string[slen] == '/')
       break;
   if (slen < 0)
     {
       fputs (".\n", stdout);
       return (EXECUTION_SUCCESS);
     }
   /* (7) If there are any trailing slash characters in string, they
      shall be removed. */
   while (--slen >= 0)
     if (string[slen] != '/')
       break;
   string[++slen] = '\0';
   /* (8) If the remaining string is empty, string shall be set to a single
      slash character. */
   printf ("%s\n", (slen == 0) ? "/" : string);
   return (EXECUTION_SUCCESS);
 }
References builtin_usage(), EX_USAGE, EXECUTION_SUCCESS, fputs(), loptend, word_list::next, no_options(), printf(), stdout, string, strlen(), word_desc::word, and word_list::word.
Variable Documentation
dirname_doc
char* dirname_doc[]
Initial value:
= {
    "Display directory portion of pathname.",
    "",
    "The STRING is converted to the name of the directory containing",
    "the filename corresponding to the last pathname component in STRING.",
    (char *)NULL
}
Definition at line 102 of file dirname.c.
dirname_struct
struct builtin dirname_struct
Initial value:
= {
    "dirname",
    dirname_builtin,
    BUILTIN_ENABLED,
    dirname_doc,
    "dirname string",
    0
}
Definition at line 102 of file dirname.c.