Fennix Userspace: Userspace/apps/base/busybox/console-tools/setkeycodes.c File Reference
setkeycodes.c File Reference
#include "libbb.h"
Data Structures
struct kbkeycode
Enumerations
enum { KDSETKEYCODE = 0x4B4D }
Functions
int setkeycodes_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
kbkeycode
struct kbkeycode
Definition at line 35 of file setkeycodes.c.
Data Fields
unsigned keycode
unsigned scancode
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
KDSETKEYCODE
Definition at line 38 of file setkeycodes.c.
      {
     KDSETKEYCODE = 0x4B4D  /* write kernel keycode table entry */
 };
Function Documentation
setkeycodes_main()
int setkeycodes_main (int argc, char ** argv)
Definition at line 43 of file setkeycodes.c.
 {
     int fd;
     if (!(argc & 1) /* if even */ || argc < 2) {
         bb_show_usage();
     }
     fd = get_console_fd_or_die();
     while (argv[1]) {
         struct kbkeycode a;
         int sc;
         sc = xstrtoul_range(argv[1], 16, 0, 0xe07f);
         if (sc >= 0xe000) {
             sc -= 0xe000;
             sc += 0x0080;
         }
         a.scancode = sc;
         a.keycode = xatou_range(argv[2], 0, 255);
         ioctl_or_perror_and_die(fd, KDSETKEYCODE, &a,
             "can't set SCANCODE %x to KEYCODE %d",
             sc, a.keycode);
         argv += 2;
     }
     return EXIT_SUCCESS;
 }
References argc, argv, bb_show_usage(), EXIT_SUCCESS, fd, get_console_fd_or_die(), ioctl_or_perror_and_die(), KDSETKEYCODE, kbkeycode::keycode, and kbkeycode::scancode.