Fennix: Userspace/musl/src/passwd/getpwent_a.c File Reference
getpwent_a.c File Reference
#include "pwf.h"
#include <pthread.h>
Functions
static unsigned atou (char **s)
int __getpwent_a (FILE *f, struct passwd *pw, char **line, size_t *size, struct passwd **res)
Function Documentation
__getpwent_a()
int __getpwent_a (FILE * f, struct passwd * pw, char ** line, size_t * size, struct passwd ** res)
Definition at line 11 of file getpwent_a.c.
 {
     ssize_t l;
     char *s;
     int rv = 0;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     for (;;) {
         if ((l=getline(line, size, f)) < 0) {
             rv = ferror(f) ? errno : 0;
             free(*line);
             *line = 0;
             pw = 0;
             break;
         }
         line[0][l-1] = 0;
         s = line[0];
         pw->pw_name = s++;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_passwd = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_uid = atou(&s);
         if (*s != ':') continue;
         *s++ = 0; pw->pw_gid = atou(&s);
         if (*s != ':') continue;
         *s++ = 0; pw->pw_gecos = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_dir = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_shell = s;
         break;
     }
     pthread_setcancelstate(cs, 0);
     *res = pw;
     if (rv) errno = rv;
     return rv;
 }
References atou(), errno, f, ferror, free, getline(), l, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pw, passwd::pw_dir, passwd::pw_gecos, passwd::pw_gid, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, s, size, and strchr().
Referenced by __getpw_a(), fgetpwent(), and getpwent().
atou()
static unsigned atou (char ** s) static
Definition at line 4 of file getpwent_a.c.
 {
     unsigned x;
     for (x=0; **s-'0'<10U; ++*s) x=10*x+(**s-'0');
     return x;
 }
References s, and x.
Referenced by __getpwent_a().