Fennix Kernel: shared_ptr< T >::Counter Class Reference
shared_ptr< T >::Counter Class Reference
Public Member Functions
Counter ()
Counter (const Counter &)=delete
Counter & operator= (const Counter &)=delete
~Counter ()
void Reset ()
unsigned int Get ()
void operator++ ()
void operator++ (int)
void operator-- ()
void operator-- (int)
Private Attributes
unsigned int m_RefCount {}
Detailed Description
template<typename T>
class shared_ptr< T >::Counter
Definition at line 79 of file smartptr.hpp.
Constructor & Destructor Documentation
Counter() [1/2]
template<typename T > shared_ptr< T >::Counter::Counter () inline
Definition at line 85 of file smartptr.hpp.
 : m_RefCount(0) { spdbg("Counter %#lx created", this); };
References spdbg.
Counter() [2/2]
template<typename T > shared_ptr< T >::Counter::Counter (const Counter &) delete
~Counter()
template<typename T > shared_ptr< T >::Counter::~Counter () inline
Definition at line 88 of file smartptr.hpp.
 { spdbg("Counter %#lx deleted", this); }
References spdbg.
Member Function Documentation
Get()
template<typename T > unsigned int shared_ptr< T >::Counter::Get () inline
Definition at line 95 of file smartptr.hpp.
         {
             return m_RefCount;
             spdbg("Counter returned");
         }
References shared_ptr< T >::Counter::m_RefCount, and spdbg.
Referenced by shared_ptr< T >::GetCount(), shared_ptr< T >::reset(), and shared_ptr< T >::~shared_ptr().
operator++() [1/2]
template<typename T > void shared_ptr< T >::Counter::operator++ () inline
Definition at line 101 of file smartptr.hpp.
         {
             m_RefCount++;
             spdbg("Counter incremented");
         }
References shared_ptr< T >::Counter::m_RefCount, and spdbg.
operator++() [2/2]
template<typename T > void shared_ptr< T >::Counter::operator++ (int) inline
Definition at line 107 of file smartptr.hpp.
         {
             m_RefCount++;
             spdbg("Counter incremented");
         }
References shared_ptr< T >::Counter::m_RefCount, and spdbg.
operator--() [1/2]
template<typename T > void shared_ptr< T >::Counter::operator-- () inline
Definition at line 113 of file smartptr.hpp.
         {
             m_RefCount--;
             spdbg("Counter decremented");
         }
References shared_ptr< T >::Counter::m_RefCount, and spdbg.
operator--() [2/2]
template<typename T > void shared_ptr< T >::Counter::operator-- (int) inline
Definition at line 119 of file smartptr.hpp.
         {
             m_RefCount--;
             spdbg("Counter decremented");
         }
References shared_ptr< T >::Counter::m_RefCount, and spdbg.
operator=()
template<typename T > Counter& shared_ptr< T >::Counter::operator= (const Counter &) delete
Reset()
template<typename T > void shared_ptr< T >::Counter::Reset () inline
Definition at line 89 of file smartptr.hpp.
         {
             m_RefCount = 0;
             spdbg("Counter reset");
         }
References shared_ptr< T >::Counter::m_RefCount, and spdbg.
Field Documentation
m_RefCount
template<typename T > unsigned int shared_ptr< T >::Counter::m_RefCount {} private
Definition at line 82 of file smartptr.hpp.
Referenced by shared_ptr< T >::Counter::Get(), shared_ptr< T >::Counter::operator++(), shared_ptr< T >::Counter::operator--(), and shared_ptr< T >::Counter::Reset().
The documentation for this class was generated from the following file:
Kernel/include/smartptr.hpp