Fennix: Userspace/apps/base/bash/lib/readline/savestring.c File Reference
savestring.c File Reference
#include <config.h>
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
Functions
char * savestring (const char *s)
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file savestring.c.
Function Documentation
savestring()
char* savestring (const char * s)
Definition at line 33 of file savestring.c.
 {
   char *ret;
   ret = (char *)xmalloc (strlen (s) + 1);
   strcpy (ret, s);
   return ret;
 }
References s, strcpy, strlen(), and xmalloc.
Referenced by _find_user_command_internal(), _rl_copy_undo_entry(), _rl_dispatch_subseq(), _rl_init_locale(), _rl_nsearch_dosearch(), _rl_parse_colors(), _rl_print_color_indicator(), _rl_read_init_file(), _rl_revert_previous_lines(), _run_trap_internal(), add_history_time(), add_or_supercede_exported_var(), all_variables_matching_prefix(), alloc_history_entry(), alloc_mail_file(), append_to_match(), assign_bash_argv0(), assign_in_env(), bash_special_tilde_expansions(), bash_tilde_expand(), bash_tilde_find_word(), bind_args(), bind_function(), bind_tempenv_variable(), bind_variable_internal(), check_mail(), conf_standard_path(), copy_bucket_array(), copy_coproc_command(), copy_function_def_contents(), copy_history_entry(), copy_redirect(), decode_prompt_string(), do_assignment_internal(), error_token_from_token(), execute_builtin(), execute_case_command(), execute_command_internal(), execute_disk_command(), execute_for_command(), execute_function(), execute_pipeline(), execute_simple_command(), execute_subshell_builtin_or_function(), execute_variable_command(), expand_arith_string(), expand_prompt(), expand_prompt_string(), expand_string_assignment(), expand_string_for_pat(), expand_string_for_rhs(), expand_string_if_necessary(), expand_string_internal(), expand_word_internal(), expassign(), find_absolute_program(), find_in_path_element(), find_token_in_alist(), find_user_command_in_path(), full_pathname(), get_bash_name(), get_current_user_info(), get_dollar_var_value(), get_history_event(), get_history_word_specifier(), get_home_dir(), get_next_path_element(), get_working_directory(), hist_inittime(), history_expand(), history_expand_internal(), history_filename(), init_yy_io(), itos(), job_working_directory(), list_remove_pattern(), list_transform(), loadstat(), main(), make_absolute(), make_bare_word(), make_coproc_command(), make_env_array_from_var_list(), make_function_def(), make_here_document(), make_local_variable(), make_new_variable(), make_path(), make_variable_value(), makunbound(), new_shell_variable(), new_var_context(), open_shell_script(), param_expand(), parameter_brace_casemod(), parameter_brace_expand(), parameter_brace_expand_indir(), parameter_brace_expand_length(), parameter_brace_expand_rhs(), parameter_brace_find_indir(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parse_prologue(), parser_if(), pat_subst(), phash_insert(), phash_search(), pos_params_modcase(), pos_params_pat_subst(), print_filename(), print_offending_line(), propagate_temp_var(), push_builtin(), push_posix_temp_var(), push_temp_var(), readline_internal_teardown(), readtok(), redirection_error(), remember_args(), remove_duplicate_matches(), remove_pattern(), remove_upattern(), replace_history_entry(), rl_call_last_kbd_macro(), rl_complete_internal(), rl_filename_completion_function(), rl_maybe_save_line(), rl_set_keymap_name(), rl_set_prompt(), rl_start_kbd_macro(), rl_username_completion_function(), run_exit_trap(), run_pending_traps(), run_sigchld_trap(), search_for_command(), set_default_locale(), set_default_locale_vars(), set_lang(), set_locale_var(), set_shell_name(), set_signal(), set_string_value(), set_working_directory(), setup_ignore_patterns(), sh_canonpath(), sh_get_home_dir(), sh_makepath(), sh_physpath(), sh_realpath(), shell_initialize(), shell_ungets(), shift_args(), show_shell_usage(), stat_char(), statlink(), statval(), string_extract_verbatim(), string_list_internal(), string_transform(), strsub(), strvec_copy(), strvec_from_word_list(), subexpr(), sv_combegin(), sv_isrchterm(), uitos(), verify_substring_values(), and xstrdup().