Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/cimagf.c File Reference
cimagf.c File Reference
#include <complex.h>
#include "fdlibm.h"
Functions
float cimagf (float complex z)
Function Documentation
cimagf()
float cimagf (float complex z)
Definition at line 16 of file cimagf.c.
 {
     float_complex w = { .z = z };
     return (IMAG_PART(w));
 }
References IMAG_PART, and float_complex::z.
Referenced by __mlibc_ctansf(), cabsf(), cacosf(), cargf(), casinf(), catanf(), ccosf(), ccoshf(), cexpf(), clogf(), cpowf(), cprojf(), csinf(), csinhf(), csqrtf(), ctanf(), ctanhf(), and main().