Fennix: Userspace/apps/base/busybox/networking/udhcp/d6_common.h File Reference
d6_common.h File Reference
#include <netinet/ip6.h>
Data Structures
struct d6_packet
struct ip6_udp_d6_packet
struct udp_d6_packet
struct d6_option
struct client6_data_t
union d6_packet.d6_u
Macros
#define D6_MSG_SOLICIT 1
#define D6_MSG_ADVERTISE 2
#define D6_MSG_REQUEST 3
#define D6_MSG_CONFIRM 4
#define D6_MSG_RENEW 5
#define D6_MSG_REBIND 6
#define D6_MSG_REPLY 7
#define D6_MSG_RELEASE 8
#define D6_MSG_DECLINE 9
#define D6_MSG_RECONFIGURE 10
#define D6_MSG_INFORMATION_REQUEST 11
#define D6_MSG_RELAY_FORW 12
#define D6_MSG_RELAY_REPL 13
#define d6_msg_type d6_u.d6_msg_type
#define d6_xid32 d6_u.d6_xid32
#define D6_OPT_CLIENTID 1
#define D6_OPT_SERVERID 2
#define D6_OPT_IA_NA 3
#define D6_OPT_IAADDR 5
#define D6_OPT_ORO 6
#define D6_OPT_ELAPSED_TIME 8
#define D6_OPT_STATUS_CODE 13
#define D6_OPT_DNS_SERVERS 23
#define D6_OPT_DOMAIN_LIST 24
#define D6_OPT_IA_PD 25
#define D6_OPT_IAPREFIX 26
#define D6_OPT_CLIENT_FQDN 39
#define D6_OPT_TZ_POSIX 41
#define D6_OPT_TZ_NAME 42
#define D6_OPT_BOOT_URL 59
#define D6_OPT_BOOT_PARAM 60
#define client6_data (*(struct client6_data_t*)(&bb_common_bufsiz1[COMMON_BUFSIZE - sizeof(struct client6_data_t)]))
#define d6_dump_packet(packet) ((void)0)
Functions
int FAST_FUNC d6_read_interface (const char *interface, int *ifindex, struct in6_addr *nip6, uint8_t *mac)
int FAST_FUNC d6_listen_socket (int port, const char *inf)
int FAST_FUNC d6_recv_kernel_packet (struct in6_addr *peer_ipv6, struct d6_packet *packet, int fd)
int FAST_FUNC d6_send_raw_packet_from_client_data_ifindex (struct d6_packet *d6_pkt, unsigned d6_pkt_size, struct in6_addr *src_ipv6, int source_port, struct in6_addr *dst_ipv6, int dest_port, const uint8_t *dest_arp)
int FAST_FUNC d6_send_kernel_packet_from_client_data_ifindex (struct d6_packet *d6_pkt, unsigned d6_pkt_size, struct in6_addr *src_ipv6, int source_port, struct in6_addr *dst_ipv6, int dest_port)
Variables
struct d6_packet PACKED
struct client6_data_t FIX_ALIASING
Data Structure Documentation
d6_packet
struct d6_packet
Definition at line 32 of file d6_common.h.
Data Fields
uint8_t d6_options[576 - sizeof(struct ip6_hdr) - sizeof(struct udphdr) - 4+CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS]
union d6_packet d6_u
ip6_udp_d6_packet
struct ip6_udp_d6_packet
Definition at line 43 of file d6_common.h.
Data Fields
struct d6_packet data
struct ip6_hdr ip6
struct udphdr udp
udp_d6_packet
struct udp_d6_packet
Definition at line 49 of file d6_common.h.
Data Fields
struct d6_packet data
struct udphdr udp
d6_option
struct d6_option
Definition at line 56 of file d6_common.h.
Data Fields
uint8_t code
uint8_t code_hi
uint8_t data[1]
uint8_t len
uint8_t len_hi
client6_data_t
struct client6_data_t
Definition at line 153 of file d6_common.h.
Data Fields
unsigned env_idx
char ** env_ptr
struct d6_option * ia_na
struct d6_option * ia_pd
struct in6_addr ll_ip6
struct d6_option * server_id
d6_packet.d6_u
union d6_packet.d6_u
Definition at line 33 of file d6_common.h.
Data Fields
uint8_t d6_msg_type
uint32_t d6_xid32
Macro Definition Documentation
client6_data
#define client6_data (*(struct client6_data_t*)(&bb_common_bufsiz1[COMMON_BUFSIZE - sizeof(struct client6_data_t)]))
Definition at line 163 of file d6_common.h.
d6_dump_packet
#define d6_dump_packet (packet) ((void)0)
Definition at line 194 of file d6_common.h.
D6_MSG_ADVERTISE
#define D6_MSG_ADVERTISE 2
Definition at line 19 of file d6_common.h.
D6_MSG_CONFIRM
#define D6_MSG_CONFIRM 4
Definition at line 21 of file d6_common.h.
D6_MSG_DECLINE
#define D6_MSG_DECLINE 9
Definition at line 26 of file d6_common.h.
D6_MSG_INFORMATION_REQUEST
#define D6_MSG_INFORMATION_REQUEST 11
Definition at line 28 of file d6_common.h.
D6_MSG_REBIND
#define D6_MSG_REBIND 6
Definition at line 23 of file d6_common.h.
D6_MSG_RECONFIGURE
#define D6_MSG_RECONFIGURE 10
Definition at line 27 of file d6_common.h.
D6_MSG_RELAY_FORW
#define D6_MSG_RELAY_FORW 12
Definition at line 29 of file d6_common.h.
D6_MSG_RELAY_REPL
#define D6_MSG_RELAY_REPL 13
Definition at line 30 of file d6_common.h.
D6_MSG_RELEASE
#define D6_MSG_RELEASE 8
Definition at line 25 of file d6_common.h.
D6_MSG_RENEW
#define D6_MSG_RENEW 5
Definition at line 22 of file d6_common.h.
D6_MSG_REPLY
#define D6_MSG_REPLY 7
Definition at line 24 of file d6_common.h.
D6_MSG_REQUEST
#define D6_MSG_REQUEST 3
Definition at line 20 of file d6_common.h.
D6_MSG_SOLICIT
#define D6_MSG_SOLICIT 1
Definition at line 18 of file d6_common.h.
d6_msg_type
#define d6_msg_type d6_u.d6_msg_type
Definition at line 40 of file d6_common.h.
D6_OPT_BOOT_PARAM
#define D6_OPT_BOOT_PARAM 60
Definition at line 149 of file d6_common.h.
D6_OPT_BOOT_URL
#define D6_OPT_BOOT_URL 59
Definition at line 148 of file d6_common.h.
D6_OPT_CLIENT_FQDN
#define D6_OPT_CLIENT_FQDN 39
Definition at line 143 of file d6_common.h.
D6_OPT_CLIENTID
#define D6_OPT_CLIENTID 1
Definition at line 64 of file d6_common.h.
D6_OPT_DNS_SERVERS
#define D6_OPT_DNS_SERVERS 23
Definition at line 98 of file d6_common.h.
D6_OPT_DOMAIN_LIST
#define D6_OPT_DOMAIN_LIST 24
Definition at line 99 of file d6_common.h.
D6_OPT_ELAPSED_TIME
#define D6_OPT_ELAPSED_TIME 8
Definition at line 78 of file d6_common.h.
D6_OPT_IA_NA
#define D6_OPT_IA_NA 3
Definition at line 68 of file d6_common.h.
D6_OPT_IA_PD
#define D6_OPT_IA_PD 25
Definition at line 103 of file d6_common.h.
D6_OPT_IAADDR
#define D6_OPT_IAADDR 5
Definition at line 74 of file d6_common.h.
D6_OPT_IAPREFIX
#define D6_OPT_IAPREFIX 26
Definition at line 105 of file d6_common.h.
D6_OPT_ORO
#define D6_OPT_ORO 6
Definition at line 76 of file d6_common.h.
D6_OPT_SERVERID
#define D6_OPT_SERVERID 2
Definition at line 65 of file d6_common.h.
D6_OPT_STATUS_CODE
#define D6_OPT_STATUS_CODE 13
Definition at line 87 of file d6_common.h.
D6_OPT_TZ_NAME
#define D6_OPT_TZ_NAME 42
Definition at line 146 of file d6_common.h.
D6_OPT_TZ_POSIX
#define D6_OPT_TZ_POSIX 41
Definition at line 145 of file d6_common.h.
d6_xid32
#define d6_xid32 d6_u.d6_xid32
Definition at line 41 of file d6_common.h.
Function Documentation
d6_listen_socket()
int FAST_FUNC d6_listen_socket (int port, const char * inf)
Definition at line 105 of file d6_socket.c.
 {
     int fd;
     struct sockaddr_in6 addr;
     char *colon;
     log2("opening listen socket on *:%d %s", port, inf);
     fd = xsocket(PF_INET6, SOCK_DGRAM, IPPROTO_UDP);
     setsockopt_reuseaddr(fd);
     if (setsockopt_broadcast(fd) == -1)
         bb_simple_perror_msg_and_die("SO_BROADCAST");
     /* SO_BINDTODEVICE doesn't work on ethernet aliases (ethN:M) */
     colon = strrchr(inf, ':');
     if (colon)
         *colon = '\0';
     if (setsockopt_bindtodevice(fd, inf))
         xfunc_die(); /* warning is already printed */
     if (colon)
         *colon = ':';
     memset(&addr, 0, sizeof(addr));
     addr.sin6_family = AF_INET6;
     addr.sin6_port = htons(port);
     /* addr.sin6_addr is all-zeros */
     xbind(fd, (struct sockaddr *)&addr, sizeof(addr));
     return fd;
 }
References addr, AF_INET6, bb_simple_perror_msg_and_die(), colon, fd, htons(), IPPROTO_UDP, log2, memset, PF_INET6, port, setsockopt_bindtodevice(), setsockopt_broadcast(), setsockopt_reuseaddr(), SOCK_DGRAM, strrchr(), xbind(), xfunc_die(), and xsocket().
Referenced by change_listen_mode().
d6_read_interface()
int FAST_FUNC d6_read_interface (const char * interface, int * ifindex, struct in6_addr * nip6, uint8_t * mac)
Definition at line 13 of file d6_socket.c.
 {
     int retval = 3;
     struct ifaddrs *ifap, *ifa;
     getifaddrs(&ifap);
     for (ifa = ifap; ifa; ifa = ifa->ifa_next) {
         struct sockaddr_in6 *sip6;
         if (!ifa->ifa_addr || (strcmp(ifa->ifa_name, interface) != 0))
             continue;
         if (ifa->ifa_addr->sa_family == AF_PACKET) {
             struct sockaddr_ll *sll = (void*)(ifa->ifa_addr);
             memcpy(mac, sll->sll_addr, 6);
             log2("MAC %02x:%02x:%02x:%02x:%02x:%02x",
                 mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]
             );
             *ifindex = sll->sll_ifindex;
             log2("ifindex %d", *ifindex);
             retval &= (3 - (1<<0));
         }
 #if 0
         if (ifa->ifa_addr->sa_family == AF_INET) {
             *nip = ((struct sockaddr_in *)ifa->ifa_addr)->sin_addr.s_addr;
             log1("IP %s", inet_ntoa(((struct sockaddr_in *)ifa->ifa_addr)->sin_addr));
         }
 #endif
 /* RFC 3315
  * 16. Client Source Address and Interface Selection
  *
  * "When a client sends a DHCP message to the
  * All_DHCP_Relay_Agents_and_Servers address, ... ... The client
  * MUST use a link-local address assigned to the interface for which it
  * is requesting configuration information as the source address in the
  * header of the IP datagram."
  */
         sip6 = (void*)(ifa->ifa_addr);
         if (ifa->ifa_addr->sa_family == AF_INET6
          && IN6_IS_ADDR_LINKLOCAL(&sip6->sin6_addr)
         ) {
             *nip6 = sip6->sin6_addr; /* struct copy */
             log1(
                 "IPv6 %02x%02x:%02x%02x:%02x%02x:%02x%02x:%02x%02x:%02x%02x:%02x%02x:%02x%02x",
                 nip6->s6_addr[0], nip6->s6_addr[1],
                 nip6->s6_addr[2], nip6->s6_addr[3],
                 nip6->s6_addr[4], nip6->s6_addr[5],
                 nip6->s6_addr[6], nip6->s6_addr[7],
                 nip6->s6_addr[8], nip6->s6_addr[9],
                 nip6->s6_addr[10], nip6->s6_addr[11],
                 nip6->s6_addr[12], nip6->s6_addr[13],
                 nip6->s6_addr[14], nip6->s6_addr[15]
             );
             retval &= (3 - (1<<1));
         }
     }
     freeifaddrs(ifap);
     if (retval & (1<<0)) {
         /* This iface has no MAC (e.g. ppp), generate a random one */
         struct ifreq ifr;
         int fd;
         /*memset(&ifr, 0, sizeof(ifr)); - SIOCGIFINDEX does not need to clear all */
         strncpy_IFNAMSIZ(ifr.ifr_name, interface);
         fd = xsocket(AF_INET6, SOCK_RAW, IPPROTO_RAW);
         if (ioctl(fd, SIOCGIFINDEX, &ifr) == 0) {
             *ifindex = ifr.ifr_ifindex;
             log2("ifindex %d", *ifindex);
             if (((uint32_t*)mac)[0] == 0) {
                 /* invent a fictitious MAC (once) */
                 ((uint32_t*)mac)[0] = rand();
                 ((uint16_t*)mac)[2] = rand();
                 mac[0] &= 0xfc; /* make sure it's not bcast */
             }
             retval &= (3 - (1<<0));
         }
         close(fd);
     }
     if (retval & (1<<0))
         bb_error_msg("can't get %s", "MAC");
     if (retval & (1<<1))
         bb_error_msg("can't get %s", "link-local IPv6 address");
     return retval;
 }
References AF_INET, AF_INET6, AF_PACKET, bb_error_msg(), close(), fd, freeifaddrs(), getifaddrs(), ifaddrs::ifa_addr, ifaddrs::ifa_name, ifaddrs::ifa_next, ifr, IN6_IS_ADDR_LINKLOCAL, inet_ntoa(), ioctl(), IPPROTO_RAW, log1, log2, memcpy, rand(), retval, sockaddr::sa_family, sockaddr_in6::sin6_addr, SIOCGIFINDEX, sockaddr_ll::sll_addr, sockaddr_ll::sll_ifindex, SOCK_RAW, strcmp, strncpy_IFNAMSIZ(), and xsocket().
Referenced by udhcpc6_main().
d6_recv_kernel_packet()
int FAST_FUNC d6_recv_kernel_packet (struct in6_addr * peer_ipv6, struct d6_packet * packet, int fd)
Referenced by udhcpc6_main().
d6_send_kernel_packet_from_client_data_ifindex()
int FAST_FUNC d6_send_kernel_packet_from_client_data_ifindex (struct d6_packet * d6_pkt, unsigned d6_pkt_size, struct in6_addr * src_ipv6, int source_port, struct in6_addr * dst_ipv6, int dest_port)
Definition at line 139 of file d6_packet.c.
 {
     struct sockaddr_in6 sa;
     int fd;
     int result = -1;
     const char *msg;
     fd = socket(PF_INET6, SOCK_DGRAM, IPPROTO_UDP);
     if (fd < 0) {
         msg = "socket(%s)";
         goto ret_msg;
     }
     setsockopt_reuseaddr(fd);
     memset(&sa, 0, sizeof(sa));
     sa.sin6_family = AF_INET6;
     sa.sin6_port = htons(source_port);
     sa.sin6_addr = *src_ipv6; /* struct copy */
     if (bind(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
         msg = "bind(%s)";
         goto ret_close;
     }
     memset(&sa, 0, sizeof(sa));
     sa.sin6_family = AF_INET6;
     sa.sin6_port = htons(dest_port);
     sa.sin6_addr = *dst_ipv6; /* struct copy */
     sa.sin6_scope_id = client_data.ifindex;
     if (connect(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
         msg = "connect";
         goto ret_close;
     }
     d6_dump_packet(d6_pkt);
     result = safe_write(fd, d6_pkt, d6_pkt_size);
     msg = "write";
  ret_close:
     close(fd);
     if (result < 0) {
  ret_msg:
         bb_perror_msg(msg, "UDP");
     }
     return result;
 }
References AF_INET6, bb_perror_msg(), bind(), client_data, close(), connect(), d6_dump_packet, fd, htons(), IPPROTO_UDP, memset, PF_INET6, safe_write(), setsockopt_reuseaddr(), sockaddr_in6::sin6_addr, sockaddr_in6::sin6_family, sockaddr_in6::sin6_port, sockaddr_in6::sin6_scope_id, SOCK_DGRAM, and socket().
Referenced by send_d6_release(), and send_d6_renew().
d6_send_raw_packet_from_client_data_ifindex()
int FAST_FUNC d6_send_raw_packet_from_client_data_ifindex (struct d6_packet * d6_pkt, unsigned d6_pkt_size, struct in6_addr * src_ipv6, int source_port, struct in6_addr * dst_ipv6, int dest_port, const uint8_t * dest_arp)
Definition at line 54 of file d6_packet.c.
 {
     struct sockaddr_ll dest_sll;
     struct ip6_udp_d6_packet packet;
     int fd;
     int result = -1;
     const char *msg;
     fd = socket(PF_PACKET, SOCK_DGRAM, htons(ETH_P_IPV6));
     if (fd < 0) {
         msg = "socket(%s)";
         goto ret_msg;
     }
     memset(&dest_sll, 0, sizeof(dest_sll));
     memset(&packet, 0, offsetof(struct ip6_udp_d6_packet, data));
     packet.data = *d6_pkt; /* struct copy */
     dest_sll.sll_family = AF_PACKET;
     dest_sll.sll_protocol = htons(ETH_P_IPV6);
     dest_sll.sll_ifindex = client_data.ifindex;
     /*dest_sll.sll_hatype = ARPHRD_???;*/
     /*dest_sll.sll_pkttype = PACKET_???;*/
     dest_sll.sll_halen = 6;
     memcpy(dest_sll.sll_addr, dest_arp, 6);
 //TODO: is bind() necessary? we sendto() to this destination, should work anyway
     if (bind(fd, (struct sockaddr *)&dest_sll, sizeof(dest_sll)) < 0) {
         msg = "bind(%s)";
         goto ret_close;
     }
     packet.ip6.ip6_vfc = (6 << 4); /* 4 bits version, top 4 bits of tclass */
 // In case we have no IPv6 on our interface at all, we can try
 // to fill "all hosts" mcast address as source:
 //  /* FF02::1 is Link-local "All_Nodes" address */
 //  packet.ip6.ip6_dst.s6_addr[0] = 0xff;
 //  packet.ip6.ip6_dst.s6_addr[1] = 0x02;
 //  packet.ip6.ip6_dst.s6_addr[15] = 0x01;
 // Maybe some servers will be able to respond to us this way?
 // Users report that leaving ::0 address there makes servers try to reply to ::0,
 // which doesn't work.
     if (src_ipv6)
         packet.ip6.ip6_src = *src_ipv6; /* struct copy */
     packet.ip6.ip6_dst = *dst_ipv6; /* struct copy */
     packet.udp.source = htons(source_port);
     packet.udp.dest = htons(dest_port);
     /* size, excluding IP header: */
     packet.udp.len = htons(sizeof(struct udphdr) + d6_pkt_size);
     packet.ip6.ip6_plen = packet.udp.len;
     /*
      * Someone was smoking weed (at least) while inventing UDP checksumming:
      * UDP checksum skips first four bytes of IPv6 header.
      * 'next header' field should be summed as if it is one more byte
      * to the right, therefore we write its value (IPPROTO_UDP)
      * into ip6_hlim, and its 'real' location remains zero-filled for now.
      */
     packet.ip6.ip6_hlim = IPPROTO_UDP;
     packet.udp.check = inet_cksum(
             (uint8_t *)&packet + 4,
             offsetof(struct ip6_udp_d6_packet, data) - 4 + d6_pkt_size
     );
     /* fix 'hop limit' and 'next header' after UDP checksumming */
     packet.ip6.ip6_hlim = 1; /* observed Windows machines to use hlim=1 */
     packet.ip6.ip6_nxt = IPPROTO_UDP;
     d6_dump_packet(d6_pkt);
     result = sendto(fd, &packet, offsetof(struct ip6_udp_d6_packet, data) + d6_pkt_size,
             /*flags:*/ 0,
             (struct sockaddr *) &dest_sll, sizeof(dest_sll)
     );
     msg = "sendto";
  ret_close:
     close(fd);
     if (result < 0) {
  ret_msg:
         bb_perror_msg(msg, "PACKET");
     }
     return result;
 }
References AF_PACKET, bb_perror_msg(), bind(), client_data, close(), d6_dump_packet, ip6_udp_d6_packet::data, ETH_P_IPV6, fd, htons(), inet_cksum(), ip6_udp_d6_packet::ip6, ip6_hdr::ip6_dst, ip6_hdr::ip6_src, IPPROTO_UDP, memcpy, memset, offsetof, PF_PACKET, sendto(), sockaddr_ll::sll_addr, sockaddr_ll::sll_family, sockaddr_ll::sll_halen, sockaddr_ll::sll_ifindex, sockaddr_ll::sll_protocol, SOCK_DGRAM, socket(), and ip6_udp_d6_packet::udp.
Referenced by d6_mcast_from_client_data_ifindex().
Variable Documentation
FIX_ALIASING
struct client6_data_t FIX_ALIASING
PACKED
struct d6_option PACKED