Fennix: Userspace/musl/src/locale/textdomain.c File Reference
textdomain.c File Reference
#include <libintl.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <limits.h>
Functions
char * __gettextdomain ()
char * textdomain (const char *domainname)
char * gettext (const char *msgid)
char * ngettext (const char *msgid1, const char *msgid2, unsigned long int n)
Variables
static char * current_domain
Function Documentation
__gettextdomain()
char* __gettextdomain (void)
Definition at line 9 of file textdomain.c.
 {
     return current_domain ? current_domain : "messages";
 }
References current_domain.
Referenced by dcngettext(), and textdomain().
gettext()
char* gettext (const char * msgid)
Definition at line 34 of file textdomain.c.
 {
     return dgettext(0, msgid);
 }
References dgettext().
ngettext()
char* ngettext (const char * msgid1, const char * msgid2, unsigned long int n)
Definition at line 39 of file textdomain.c.
 {
     return dngettext(0, msgid1, msgid2, n);
 }
References dngettext(), and n.
textdomain()
char* textdomain (const char * domainname)
Definition at line 14 of file textdomain.c.
 {
     if (!domainname) return __gettextdomain();
     size_t domlen = strlen(domainname);
     if (domlen > NAME_MAX) {
         errno = EINVAL;
         return 0;
     }
     if (!current_domain) {
         current_domain = malloc(NAME_MAX+1);
         if (!current_domain) return 0;
     }
     memcpy(current_domain, domainname, domlen+1);
     return current_domain;
 }
References __gettextdomain(), current_domain, EINVAL, errno, malloc, memcpy, and strlen.
Variable Documentation
current_domain
char* current_domain static
Definition at line 7 of file textdomain.c.
Referenced by __gettextdomain(), and textdomain().