Fennix: FileSystem Namespace Reference
FileSystem Namespace Reference
Data Structures
class EXT2
class FAT
class Initrd
class Device
class Mount
class Process
class Driver
class Network
class Serial
class Random
class Null
class Zero
class FB
class USTAR
struct FileSystemOperations
struct FileSystemNode
struct FILE
class Virtual
Typedefs
typedef uint64_t(* OperationMount) (const char *, unsigned long, const void *)
typedef uint64_t(* OperationUmount) (int)
typedef uint64_t(* OperationRead) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
typedef uint64_t(* OperationWrite) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
typedef void(* OperationOpen) (FileSystemNode *Node, uint8_t Mode, uint8_t Flags)
typedef void(* OperationClose) (FileSystemNode *Node)
typedef uint64_t(* OperationSync) (void)
typedef void(* OperationCreate) (FileSystemNode *Node, char *Name, uint16_t NameLength)
typedef void(* OperationMkdir) (FileSystemNode *Node, char *Name, uint16_t NameLength)
Enumerations
enum FileStatus {
OK = 0 , NOT_FOUND = 1 , ACCESS_DENIED = 2 , INVALID_NAME = 3 ,
INVALID_PARAMETER = 4 , INVALID_HANDLE = 5 , INVALID_PATH = 6 , INVALID_FILE = 7 ,
INVALID_DEVICE = 8 , NOT_EMPTY = 9 , NOT_SUPPORTED = 10 , INVALID_DRIVE = 11 ,
VOLUME_IN_USE = 12 , TIMEOUT = 13 , NO_MORE_FILES = 14 , END_OF_FILE = 15 ,
FILE_EXISTS = 16 , PIPE_BUSY = 17 , PIPE_DISCONNECTED = 18 , MORE_DATA = 19 ,
NO_DATA = 20 , PIPE_NOT_CONNECTED = 21 , MORE_ENTRIES = 22 , DIRECTORY_NOT_EMPTY = 23 ,
NOT_A_DIRECTORY = 24 , FILE_IS_A_DIRECTORY = 25 , DIRECTORY_NOT_ROOT = 26 , DIRECTORY_NOT_EMPTY_2 = 27 ,
END_OF_MEDIA = 28 , NO_MEDIA = 29 , UNRECOGNIZED_MEDIA = 30 , SECTOR_NOT_FOUND = 31
}
enum NodeFlags {
FS_ERROR = 0x0 , FS_FILE = 0x01 , FS_DIRECTORY = 0x02 , FS_CHARDEVICE = 0x03 ,
FS_BLOCKDEVICE = 0x04 , FS_PIPE = 0x05 , FS_SYMLINK = 0x06 , FS_MOUNTPOINT = 0x08
}
Functions
FileSystemNode * AddNewChild (FileSystemNode *Parent, const char *Name)
FileSystemNode * GetChild (FileSystemNode *Parent, const char *Name)
FileStatus RemoveChild (FileSystemNode *Parent, const char *Name)
ReadFSFunction (USTAR_Read)
Variables
FileSystemOperations ustar
Data Structure Documentation
FileSystem::FileSystemOperations
struct FileSystem::FileSystemOperations
Definition at line 92 of file filesystem.hpp.
Data Fields
OperationClose Close
OperationCreate Create
OperationMkdir MakeDirectory
OperationMount Mount
char Name[FILENAME_LENGTH]
OperationOpen Open
OperationRead Read
OperationUmount Umount
OperationWrite Write
FileSystem::FileSystemNode
struct FileSystem::FileSystemNode
Definition at line 105 of file filesystem.hpp.
Data Fields
uint64_t Address
Vector< FileSystemNode * > Children
uint64_t Flags
uint64_t GroupIdentifier
uint64_t IndexNode
uint64_t Length
uint64_t Mask
uint64_t Mode
char Name[FILENAME_LENGTH]
FileSystemOperations * Operator
FileSystemNode * Parent
uint64_t UserIdentifier
FileSystem::FILE
struct FileSystem::FILE
Definition at line 125 of file filesystem.hpp.
Data Fields
const char * Name
FileSystemNode * Node
FileStatus Status
Typedef Documentation
OperationClose
typedef void(* FileSystem::OperationClose) (FileSystemNode *Node)
Definition at line 28 of file filesystem.hpp.
OperationCreate
typedef void(* FileSystem::OperationCreate) (FileSystemNode *Node, char *Name, uint16_t NameLength)
Definition at line 30 of file filesystem.hpp.
OperationMkdir
typedef void(* FileSystem::OperationMkdir) (FileSystemNode *Node, char *Name, uint16_t NameLength)
Definition at line 31 of file filesystem.hpp.
OperationMount
typedef uint64_t(* FileSystem::OperationMount) (const char *, unsigned long, const void *)
Definition at line 23 of file filesystem.hpp.
OperationOpen
typedef void(* FileSystem::OperationOpen) (FileSystemNode *Node, uint8_t Mode, uint8_t Flags)
Definition at line 27 of file filesystem.hpp.
OperationRead
typedef uint64_t(* FileSystem::OperationRead) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
Definition at line 25 of file filesystem.hpp.
OperationSync
typedef uint64_t(* FileSystem::OperationSync) (void)
Definition at line 29 of file filesystem.hpp.
OperationUmount
typedef uint64_t(* FileSystem::OperationUmount) (int)
Definition at line 24 of file filesystem.hpp.
OperationWrite
typedef uint64_t(* FileSystem::OperationWrite) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
Definition at line 26 of file filesystem.hpp.
Enumeration Type Documentation
FileStatus
enum FileSystem::FileStatus
Enumerator
OK
NOT_FOUND
ACCESS_DENIED
INVALID_NAME
INVALID_PARAMETER
INVALID_HANDLE
INVALID_PATH
INVALID_FILE
INVALID_DEVICE
NOT_EMPTY
NOT_SUPPORTED
INVALID_DRIVE
VOLUME_IN_USE
TIMEOUT
NO_MORE_FILES
END_OF_FILE
FILE_EXISTS
PIPE_BUSY
PIPE_DISCONNECTED
MORE_DATA
NO_DATA
PIPE_NOT_CONNECTED
MORE_ENTRIES
DIRECTORY_NOT_EMPTY
NOT_A_DIRECTORY
FILE_IS_A_DIRECTORY
DIRECTORY_NOT_ROOT
DIRECTORY_NOT_EMPTY_2
END_OF_MEDIA
NO_MEDIA
UNRECOGNIZED_MEDIA
SECTOR_NOT_FOUND
Definition at line 44 of file filesystem.hpp.
     {
         OK = 0,
         NOT_FOUND = 1,
         ACCESS_DENIED = 2,
         INVALID_NAME = 3,
         INVALID_PARAMETER = 4,
         INVALID_HANDLE = 5,
         INVALID_PATH = 6,
         INVALID_FILE = 7,
         INVALID_DEVICE = 8,
         NOT_EMPTY = 9,
         NOT_SUPPORTED = 10,
         INVALID_DRIVE = 11,
         VOLUME_IN_USE = 12,
         TIMEOUT = 13,
         NO_MORE_FILES = 14,
         END_OF_FILE = 15,
         FILE_EXISTS = 16,
         PIPE_BUSY = 17,
         PIPE_DISCONNECTED = 18,
         MORE_DATA = 19,
         NO_DATA = 20,
         PIPE_NOT_CONNECTED = 21,
         MORE_ENTRIES = 22,
         DIRECTORY_NOT_EMPTY = 23,
         NOT_A_DIRECTORY = 24,
         FILE_IS_A_DIRECTORY = 25,
         DIRECTORY_NOT_ROOT = 26,
         DIRECTORY_NOT_EMPTY_2 = 27,
         END_OF_MEDIA = 28,
         NO_MEDIA = 29,
         UNRECOGNIZED_MEDIA = 30,
         SECTOR_NOT_FOUND = 31
     };
NodeFlags
enum FileSystem::NodeFlags
Enumerator
FS_ERROR
FS_FILE
FS_DIRECTORY
FS_CHARDEVICE
FS_BLOCKDEVICE
FS_PIPE
FS_SYMLINK
FS_MOUNTPOINT
Definition at line 80 of file filesystem.hpp.
     {
         FS_ERROR = 0x0,
         FS_FILE = 0x01,
         FS_DIRECTORY = 0x02,
         FS_CHARDEVICE = 0x03,
         FS_BLOCKDEVICE = 0x04,
         FS_PIPE = 0x05,
         FS_SYMLINK = 0x06,
         FS_MOUNTPOINT = 0x08
     };
Function Documentation
AddNewChild()
FileSystemNode* FileSystem::AddNewChild (FileSystemNode * Parent, const char * Name)
Definition at line 102 of file Filesystem.cpp.
     {
         vfsdbg("AddNewChild( Parent: \"%s\" Name: \"%s\" )", Parent->Name, Name);
         FileSystemNode *newNode = new FileSystemNode;
         newNode->Parent = Parent;
         strncpy(newNode->Name, Name, FILENAME_LENGTH);
         if (likely(Parent))
             newNode->Operator = Parent->Operator;
         else
             newNode->Operator = nullptr;
         if (likely(Parent))
             Parent->Children.push_back(newNode);
         vfsdbg("AddNewChild()->\"%s\"", newNode->Name);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FILENAME_LENGTH, likely, CPU::Name(), FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, FileSystem::FileSystemNode::Parent, strncpy(), and vfsdbg.
Referenced by FileSystem::Virtual::Create().
GetChild()
FileSystemNode* FileSystem::GetChild (FileSystemNode * Parent, const char * Name)
Definition at line 119 of file Filesystem.cpp.
     {
         vfsdbg("GetChild( Parent: \"%s\" Name: \"%s\" )", Parent->Name, Name);
         if (likely(Parent))
             foreach (auto var in Parent->Children)
                 if (strcmp(var->Name, Name) == 0)
                 {
                     vfsdbg("GetChild()->\"%s\"", var->Name);
                     return var;
                 }
         vfsdbg("GetChild()->nullptr");
         return nullptr;
     }
References likely, CPU::Name(), FileSystem::FileSystemNode::Name, strcmp(), and vfsdbg.
Referenced by FileSystem::Virtual::Create().
ReadFSFunction()
FileSystem::ReadFSFunction (USTAR_Read)
Definition at line 10 of file ustar.cpp.
     {
         if (!Size)
             Size = Node->Length;
         if (Offset > Node->Length)
             return 0;
         if (Offset + Size > Node->Length)
             Size = Node->Length - Offset;
         memcpy(Buffer, (uint8_t *)(Node->Address + Offset), Size);
         return Size;
     }
References memcpy.
RemoveChild()
FileStatus FileSystem::RemoveChild (FileSystemNode * Parent, const char * Name)
Definition at line 133 of file Filesystem.cpp.
     {
         vfsdbg("RemoveChild( Parent: \"%s\" Name: \"%s\" )", Parent->Name, Name);
         for (uint64_t i = 0; i < Parent->Children.size(); i++)
             if (strcmp(Parent->Children[i]->Name, Name) == 0)
             {
                 Parent->Children.remove(i);
                 vfsdbg("RemoveChild()->OK");
                 return FileStatus::OK;
             }
         vfsdbg("RemoveChild()->NOT_FOUND");
         return FileStatus::NOT_FOUND;
     }
References FileSystem::FileSystemNode::Children, CPU::Name(), FileSystem::FileSystemNode::Name, NOT_FOUND, OK, strcmp(), and vfsdbg.
Variable Documentation
ustar
FileSystemOperations FileSystem::ustar
Initial value:
= {
        .Name = "ustar",
        .Read = USTAR_Read,
    }
Definition at line 22 of file ustar.cpp.
Referenced by FileSystem::USTAR::USTAR().