Fennix: Userspace/apps/base/busybox/networking/tls_rsa.h File Reference
tls_rsa.h File Reference
Data Structures
struct psRsaKey_t
Macros
#define psRsaEncryptPub(pool, key, in, inlen, out, outlen, data) psRsaEncryptPub(key, in, inlen, out, outlen)
Functions
static ALWAYS_INLINE void psRsaKey_clear (psRsaKey_t *key)
int32 psRsaEncryptPub (psPool_t *pool, psRsaKey_t *key, unsigned char *in, uint32 inlen, unsigned char *out, uint32 outlen, void *data) FAST_FUNC
Data Structure Documentation
psRsaKey_t
struct psRsaKey_t
Definition at line 9 of file tls_rsa.h.
Data Fields
pstm_int d
pstm_int dP
pstm_int dQ
pstm_int e
pstm_int N
int32 optimized
pstm_int p
pstm_int q
pstm_int qP
uint32 size
Macro Definition Documentation
psRsaEncryptPub
#define psRsaEncryptPub (pool, key, in, inlen, out, outlen, data) psRsaEncryptPub(key, in, inlen, out, outlen)
Definition at line 28 of file tls_rsa.h.
Function Documentation
psRsaEncryptPub()
int32 psRsaEncryptPub (psPool_t * pool, psRsaKey_t * key, unsigned char * in, uint32 inlen, unsigned char * out, uint32 outlen, void * data)
Definition at line 184 of file tls_rsa.c.
 {
     int32   err;
     uint32  size;
     size = key->size;
     if (outlen < size) {
 //bbox      psTraceCrypto("Error on bad outlen parameter to psRsaEncryptPub\n");
         bb_error_msg_and_die("RSA crypt outlen:%d < size:%d", outlen, size);
         return PS_ARG_FAIL;
     }
     if ((err = pkcs1Pad(in, inlen, out, size, PRIVKEY_TYPE, data))
             < PS_SUCCESS) {
         psTraceCrypto("Error padding psRsaEncryptPub. Likely data too long\n");
         return err;
     }
     if ((err = psRsaCrypt(pool, out, size, out, (uint32*)&outlen, key,
             PUBKEY_TYPE, data)) < PS_SUCCESS) {
         psTraceCrypto("Error performing psRsaEncryptPub\n");
         return err;
     }
     if (outlen != size) {
         psTraceCrypto("Encrypted size error in psRsaEncryptPub\n");
         return PS_FAILURE;
     }
     return size;
 }
References bb_error_msg_and_die(), err(), out(), pkcs1Pad, PRIVKEY_TYPE, PS_ARG_FAIL, PS_FAILURE, PS_SUCCESS, psRsaCrypt, psTraceCrypto, PUBKEY_TYPE, size, and psRsaKey_t::size.
psRsaKey_clear()
static ALWAYS_INLINE void psRsaKey_clear (psRsaKey_t * key) static
Definition at line 16 of file tls_rsa.h.
 {
     pstm_clear(&key->N);
     pstm_clear(&key->e);
     pstm_clear(&key->d);
     pstm_clear(&key->p);
     pstm_clear(&key->q);
     pstm_clear(&key->dP);
     pstm_clear(&key->dQ);
     pstm_clear(&key->qP);
 }
References psRsaKey_t::d, psRsaKey_t::dP, psRsaKey_t::dQ, psRsaKey_t::e, psRsaKey_t::N, psRsaKey_t::p, pstm_clear(), psRsaKey_t::q, and psRsaKey_t::qP.
Referenced by tls_handshake().