Fennix: Tasking::Signal Class Reference
Tasking::Signal Class Reference
#include <signal.hpp>
Data Structures
struct SignalInfo
struct StackInfo
Public Member Functions
void * GetContext ()
Signals GetLastSignal ()
int AddWatcher (Signal *who, int sig)
int RemoveWatcher (Signal *who, int sig)
int AddSignal (int sig, union sigval val)
int RemoveSignal (int sig)
bool HandleSignal (CPU::TrapFrame *tf)
void RestoreHandleSignal (SyscallsFrame *tf)
sigset_t Block (sigset_t sig)
sigset_t Unblock (sigset_t sig)
sigset_t SetMask (sigset_t sig)
sigset_t GetMask ()
int SetAction (int sig, const sigaction act)
int GetAction (int sig, sigaction *act)
int SendSignal (int sig, union sigval val={0})
int WaitAnySignal ()
int WaitSignal (int sig, union sigval *val)
int WaitSignalTimeout (int sig, union sigval *val, uint64_t timeout)
Signal (void *ctx)
~Signal ()
Private Member Functions
struct Tasking::Signal::StackInfo __aligned (16) __packed
NewLock (SignalLock)
bool LinuxSig ()
int ConvertToLinuxIfNecessary (int sig)
int ConvertToNativeIfNecessary (int sig)
sigset_t ConvertSigsetToLinuxIfNecessary (sigset_t sig)
sigset_t ConvertSigsetToNativeIfNecessary (sigset_t sig)
int MakeExitCode (int sig)
void RemoveUnmaskable (sigset_t *sig)
bool CanHaveHandler (sigset_t sig)
Private Attributes
void * ctx
Signals LastSignal = SIG_NULL
void * TrampAddr = nullptr
size_t TrampSz = 0
std::vector< SignalInfo > SignalQueue
std::atomic< sigset_t > SignalMask = 0
sigaction SignalAction [SIGNAL_MAX] {}
SignalDisposition sigDisp [SIGNAL_MAX]
std::vector< SignalInfo > Watchers
const sigset_t nMasks
const sigset_t lMasks
Detailed Description
Definition at line 354 of file signal.hpp.
Data Structure Documentation
Tasking::Signal::SignalInfo
struct Tasking::Signal::SignalInfo
Definition at line 357 of file signal.hpp.
Data Fields
int sig
union sigval val
Tasking::Signal::StackInfo
struct Tasking::Signal::StackInfo
Definition at line 363 of file signal.hpp.
Data Fields
int Compatibility
uintptr_t FSBase
FXState fx
uintptr_t GSBase
sigset_t SignalMask
TrapFrame tf
Constructor & Destructor Documentation
Signal()
Tasking::Signal::Signal (void * ctx)
Definition at line 674 of file signal.cpp.
     {
         assert(ctx != nullptr);
         this->ctx = ctx;
         sigDisp[SIG_NULL] = SIG_IGN;
         sigDisp[SIGABRT] = SIG_CORE;
         sigDisp[SIGALRM] = SIG_TERM;
         sigDisp[SIGBUS] = SIG_CORE;
         sigDisp[SIGCHLD] = SIG_IGN;
         sigDisp[SIGCONT] = SIG_CONT;
         sigDisp[SIGFPE] = SIG_CORE;
         sigDisp[SIGHUP] = SIG_TERM;
         sigDisp[SIGILL] = SIG_CORE;
         sigDisp[SIGINT] = SIG_TERM;
         sigDisp[SIGKILL] = SIG_TERM;
         sigDisp[SIGPIPE] = SIG_TERM;
         sigDisp[SIGQUIT] = SIG_TERM;
         sigDisp[SIGSEGV] = SIG_CORE;
         sigDisp[SIGSTOP] = SIG_STOP;
         sigDisp[SIGTERM] = SIG_TERM;
         sigDisp[SIGTSTP] = SIG_STOP;
         sigDisp[SIGTTIN] = SIG_STOP;
         sigDisp[SIGTTOU] = SIG_STOP;
         sigDisp[SIGUSR1] = SIG_TERM;
         sigDisp[SIGUSR2] = SIG_TERM;
         sigDisp[SIGPOLL] = SIG_TERM;
         sigDisp[SIGPROF] = SIG_TERM;
         sigDisp[SIGSYS] = SIG_CORE;
         sigDisp[SIGTRAP] = SIG_CORE;
         sigDisp[SIGURG] = SIG_IGN;
         sigDisp[SIGVTALRM] = SIG_TERM;
         sigDisp[SIGXCPU] = SIG_CORE;
         sigDisp[SIGXFSZ] = SIG_CORE;
 #ifdef DEBUG
         static int once = 0;
         if (!once++)
         {
             if (LinuxSig())
             {
                 for (int i = 0; i <= linux_SIGUNUSED; i++)
                     debug("%s: %s",
                           lSigStr[i],
                           dispStr[sigDisp[i]]);
             }
             else
             {
                 for (int i = 0; i < SIGNAL_MAX; i++)
                     debug("%s: %s",
                           sigStr[i],
                           dispStr[sigDisp[i]]);
             }
         }
 #endif
     }
References assert, ctx, debug, i, linux_SIGUNUSED, LinuxSig(), SIG_CONT, SIG_CORE, SIG_IGN, SIG_NULL, SIG_STOP, SIG_TERM, SIGABRT, SIGALRM, SIGBUS, SIGCHLD, SIGCONT, sigDisp, SIGFPE, SIGHUP, SIGILL, SIGINT, SIGKILL, SIGNAL_MAX, SIGPIPE, SIGPOLL, SIGPROF, SIGQUIT, SIGSEGV, SIGSTOP, SIGSYS, SIGTERM, SIGTRAP, SIGTSTP, SIGTTIN, SIGTTOU, SIGURG, SIGUSR1, SIGUSR2, SIGVTALRM, SIGXCPU, and SIGXFSZ.
~Signal()
Tasking::Signal::~Signal ()
Definition at line 731 of file signal.cpp.
 {}
Member Function Documentation
__aligned()
struct Tasking::Signal::StackInfo Tasking::Signal::__aligned (16) private
AddSignal()
int Tasking::Signal::AddSignal (int sig, union sigval val)
Definition at line 280 of file signal.cpp.
     {
         SmartLock(SignalLock);
         SignalInfo info{.sig = sig, .val = val};
         SignalQueue.push_back(info);
         return 0;
     }
References info, SignalQueue, and val.
AddWatcher()
int Tasking::Signal::AddWatcher (Signal * who, int sig)
Definition at line 254 of file signal.cpp.
     {
         SmartLock(SignalLock);
         SignalInfo info;
         info.sig = sig;
         info.val.sival_ptr = who;
         Watchers.push_back(info);
         return 0;
     }
References info, and Watchers.
Block()
sigset_t Tasking::Signal::Block (sigset_t sig)
Mask a signal
Parameters
sig The signal to set
Returns
Old mask
Definition at line 420 of file signal.cpp.
     {
         SmartLock(SignalLock);
         sig = CSigTNif(sig);
         sigset_t oldMask = SignalMask.fetch_or(sig);
         debug("%#lx -> %#lx", oldMask, SignalMask);
         return CSigTLif(oldMask);
     }
References CSigTLif, CSigTNif, debug, and SignalMask.
Referenced by linux_sigprocmask().
CanHaveHandler()
bool Tasking::Signal::CanHaveHandler (sigset_t sig) inline private
Definition at line 431 of file signal.hpp.
         {
             switch (sig)
             {
             case SIGKILL:
             case SIGSTOP:
             case SIGCONT:
                 return false;
             default:
                 return true;
             }
         }
References SIGCONT, SIGKILL, and SIGSTOP.
ConvertSigsetToLinuxIfNecessary()
sigset_t Tasking::Signal::ConvertSigsetToLinuxIfNecessary (sigset_t sig) private
Definition at line 208 of file signal.cpp.
     {
         if (!LinuxSig())
         {
             debug("Not linux sigset: %#lx", sig);
             return 0;
         }
         sigset_t ret = 0;
         for (int i = 0; i < SIGNAL_MAX; i++)
         {
             if (sig & ToFlag(i))
                 ret |= ToFlag(CTLif(i));
         }
         return ret;
     }
References CTLif, debug, i, LinuxSig(), and SIGNAL_MAX.
ConvertSigsetToNativeIfNecessary()
sigset_t Tasking::Signal::ConvertSigsetToNativeIfNecessary (sigset_t sig) private
Definition at line 226 of file signal.cpp.
     {
         if (!LinuxSig())
         {
             debug("Not native sigset: %#lx", sig);
             return 0;
         }
         sigset_t ret = 0;
         for (int i = 0; i < linux_SIGUNUSED; i++)
         {
             if (sig & ToFlag(i))
                 ret |= ToFlag(CTNif(i));
         }
         return ret;
     }
References CTNif, debug, i, linux_SIGUNUSED, and LinuxSig().
ConvertToLinuxIfNecessary()
int Tasking::Signal::ConvertToLinuxIfNecessary (int sig) private
Definition at line 168 of file signal.cpp.
     {
         if (!LinuxSig())
         {
             debug("Not linux sig: %d", sig);
             return sig;
         }
         foreach (auto &mapping in signalMapping)
         {
             if (mapping.nativeSignal == sig)
             {
                 // debug("Converted %d to %d", sig, mapping.linuxSignal);
                 return mapping.linuxSignal;
             }
         }
         return -1;
     }
References debug, LinuxSig(), and signalMapping.
ConvertToNativeIfNecessary()
int Tasking::Signal::ConvertToNativeIfNecessary (int sig) private
Definition at line 188 of file signal.cpp.
     {
         if (!LinuxSig())
         {
             debug("Not native sig: %d", sig);
             return sig;
         }
         foreach (auto &mapping in signalMapping)
         {
             if (mapping.linuxSignal == sig)
             {
                 // debug("Converted %d to %d", sig, mapping.nativeSignal);
                 return mapping.nativeSignal;
             }
         }
         return -1;
     }
References debug, LinuxSig(), and signalMapping.
GetAction()
int Tasking::Signal::GetAction (int sig, sigaction * act)
Definition at line 466 of file signal.cpp.
     {
         SmartLock(SignalLock);
         if ((size_t)sig > sizeof(SignalAction) / sizeof(SignalAction[0]))
             return -EINVAL;
         sig = CTNif(sig);
         act->__sa_handler.sa_handler = SignalAction[sig].__sa_handler.sa_handler;
         act->sa_mask = SignalAction[sig].sa_mask;
         act->sa_flags = SignalAction[sig].sa_flags;
         debug("Got action for %s with handler %#lx, mask %#lx and flags %#lx",
               LinuxSig() ? lSigStr[sig] : sigStr[sig],
               SignalAction[sig].__sa_handler.sa_handler,
               SignalAction[sig].sa_mask,
               SignalAction[sig].sa_flags);
         return 0;
     }
References act(), CTNif, debug, EINVAL, and LinuxSig().
Referenced by linux_sigaction().
GetContext()
void* Tasking::Signal::GetContext () inline
Definition at line 445 of file signal.hpp.
 { return ctx; }
References ctx.
Referenced by SendSignal().
GetLastSignal()
Signals Tasking::Signal::GetLastSignal () inline
Definition at line 446 of file signal.hpp.
 { return LastSignal; }
References LastSignal.
GetMask()
sigset_t Tasking::Signal::GetMask () inline
Definition at line 488 of file signal.hpp.
 { return SignalMask.load(); }
References SignalMask.
Referenced by linux_sigprocmask().
HandleSignal()
bool Tasking::Signal::HandleSignal (CPU::TrapFrame * tf)
For scheduler use only
Returns
True if there is a signal to handle
Definition at line 302 of file signal.cpp.
     {
         SmartLock(SignalLock);
         if (SignalQueue.empty())
             return false;
         /* We don't want to do this in kernel mode */
         if (unlikely(tf->cs != GDT_USER_CODE &&
                      tf->cs != GDT_USER_DATA))
         {
             // debug("Not user-mode");
             return false;
         }
         debug("We have %d signals to handle", SignalQueue.size());
         SignalInfo sigI = SignalQueue.front();
         SignalQueue.erase(SignalQueue.begin());
         uintptr_t _p_rsp = ((PCB *)ctx)->PageTable->Get(tf->rsp);
         uint64_t paRsp = _p_rsp;
         paRsp &= ~0xF; /* Align */
         paRsp -= 128;  /* Red zone */
         /* Calculate the virtual rsp */
         uintptr_t _v_rsp = tf->rsp;
         _v_rsp &= ~0xF; /* Align */
         _v_rsp -= 128;  /* Red zone */
         uint64_t *vRsp = (uint64_t *)(_v_rsp - sizeof(StackInfo));
         vRsp--; /* Alignment */
         vRsp--; /* Handler Address */
         assert(!((uintptr_t)vRsp & 0xF));
         /* Add the stack info */
         StackInfo si{};
         CPU::x64::fxsave(&si.fx);
         si.tf = *tf;
         si.GSBase = CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE);
         si.FSBase = CPU::x64::rdmsr(CPU::x64::MSR_FS_BASE);
         si.ShadowGSBase = CPU::x64::rdmsr(CPU::x64::MSR_SHADOW_GS_BASE);
         debug("gs: %#lx fs: %#lx shadow: %#lx",
               si.GSBase, si.FSBase, si.ShadowGSBase);
         si.SignalMask = SignalMask.load();
         si.Compatibility = ((PCB *)ctx)->Info.Compatibility;
         /* Copy the stack info */
         uint64_t *pRsp = (uint64_t *)(paRsp - sizeof(StackInfo));
         memcpy(pRsp, &si, sizeof(StackInfo));
         /* Set the handler address */
         pRsp--; /* Alignment */
         pRsp--;
         *pRsp = uint64_t(SignalAction[sigI.sig].__sa_handler.sa_handler);
         assert(!((uintptr_t)pRsp & 0xF));
 #ifdef DEBUG
         DumpData("Stack Data", (void *)pRsp,
                  paRsp - uint64_t(pRsp));
         debug("initial stack tf->rsp: %#lx after: %#lx",
               tf->rsp, uint64_t(vRsp));
         debug("sig: %d -> %d", sigI.sig, CTLif(sigI.sig));
 #endif
         tf->rsp = uint64_t(vRsp);
         tf->rip = uint64_t(TrampAddr);
         tf->rdi = CTLif(sigI.sig);
         tf->rsi = uint64_t(sigI.val.sival_ptr);
         return true;
     }
References assert, CPU::x32::TrapFrame::cs, CTLif, debug, DumpData(), CPU::x64::fxsave(), GDT_USER_CODE, GDT_USER_DATA, memcpy, CPU::x64::MSR_FS_BASE, CPU::x64::MSR_GS_BASE, CPU::x64::MSR_SHADOW_GS_BASE, Tasking::Signal::SignalInfo::sig, SignalMask, SignalQueue, sigval::sival_ptr, tf, TrampAddr, unlikely, and Tasking::Signal::SignalInfo::val.
LinuxSig()
bool Tasking::Signal::LinuxSig () private
Definition at line 163 of file signal.cpp.
     {
         return ((PCB *)ctx)->Info.Compatibility == Linux;
     }
References Tasking::Linux.
Referenced by ConvertSigsetToLinuxIfNecessary(), ConvertSigsetToNativeIfNecessary(), ConvertToLinuxIfNecessary(), ConvertToNativeIfNecessary(), GetAction(), MakeExitCode(), RemoveUnmaskable(), SetAction(), and Signal().
MakeExitCode()
int Tasking::Signal::MakeExitCode (int sig) private
Definition at line 244 of file signal.cpp.
     {
         if (this->LinuxSig())
             return 128 + sig;
         else
             return 100 + sig;
     }
References LinuxSig().
Referenced by SendSignal().
NewLock()
Tasking::Signal::NewLock (SignalLock) private
RemoveSignal()
int Tasking::Signal::RemoveSignal (int sig)
Definition at line 288 of file signal.cpp.
     {
         SmartLock(SignalLock);
         forItr(itr, SignalQueue)
         {
             if (itr->sig == sig)
             {
                 SignalQueue.erase(itr);
                 return 0;
             }
         }
         return -ENOENT;
     }
References ENOENT, and SignalQueue.
RemoveUnmaskable()
void Tasking::Signal::RemoveUnmaskable (sigset_t * sig) inline private
Definition at line 423 of file signal.hpp.
         {
             if (LinuxSig())
                 *sig &= ~lMasks;
             else
                 *sig &= ~nMasks;
         }
References LinuxSig(), lMasks, and nMasks.
RemoveWatcher()
int Tasking::Signal::RemoveWatcher (Signal * who, int sig)
Definition at line 265 of file signal.cpp.
     {
         SmartLock(SignalLock);
         forItr(itr, Watchers)
         {
             if (itr->sig == sig &&
                 itr->val.sival_ptr == who)
             {
                 Watchers.erase(itr);
                 return 0;
             }
         }
         return -ENOENT;
     }
References ENOENT, and Watchers.
RestoreHandleSignal()
void Tasking::Signal::RestoreHandleSignal (SyscallsFrame * tf)
Definition at line 373 of file signal.cpp.
     {
         SmartLock(SignalLock);
         debug("Restoring signal handler");
         gsTCB *gs = (gsTCB *)CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE);
         uint64_t *sp = (uint64_t *)((PCB *)ctx)->PageTable->Get(gs->TempStack);
         sp++; /* Alignment */
         sp++; /* Handler Address */
         assert(!((uintptr_t)sp & 0xF));
         StackInfo *si = (StackInfo *)sp;
         assert(si != nullptr);
         sf->r15 = si->tf.r15;
         sf->r14 = si->tf.r14;
         sf->r13 = si->tf.r13;
         sf->r12 = si->tf.r12;
         sf->r11 = si->tf.r11;
         sf->r10 = si->tf.r10;
         sf->r9 = si->tf.r9;
         sf->r8 = si->tf.r8;
         sf->rbp = si->tf.rbp;
         sf->rdi = si->tf.rdi;
         sf->rsi = si->tf.rsi;
         sf->rdx = si->tf.rdx;
         sf->rcx = si->tf.rcx;
         sf->rbx = si->tf.rbx;
         sf->rax = si->tf.rax;
         sf->Flags = si->tf.rflags.raw;
         sf->ReturnAddress = si->tf.rip;
         gs->TempStack = si->tf.rsp;
         SignalMask.store(si->SignalMask);
         CPU::x64::fxrstor(&si->fx);
         CPU::x64::wrmsr(CPU::x64::MSR_GS_BASE, si->ShadowGSBase);
         CPU::x64::wrmsr(CPU::x64::MSR_FS_BASE, si->FSBase);
         CPU::x64::wrmsr(CPU::x64::MSR_SHADOW_GS_BASE, si->GSBase);
         debug("gs: %#lx fs: %#lx shadow: %#lx",
               si->GSBase, si->FSBase, si->ShadowGSBase);
         // ((PCB *)ctx)->GetContext()->Yield();
         // __builtin_unreachable();
         /* Return because we will restore at sysretq */
     }
References assert, ctx, debug, Tasking::Signal::StackInfo::FSBase, Tasking::Signal::StackInfo::fx, CPU::x64::fxrstor(), Tasking::Signal::StackInfo::GSBase, CPU::x64::MSR_FS_BASE, CPU::x64::MSR_GS_BASE, CPU::x64::MSR_SHADOW_GS_BASE, CPU::PageTable(), Tasking::Signal::StackInfo::SignalMask, SignalMask, sp, Tasking::gsTCB::TempStack, and Tasking::Signal::StackInfo::tf.
SendSignal()
int Tasking::Signal::SendSignal (int sig, union sigval val = {0})
Send a signal to the process
Parameters
sig The signal to send (compatibility specific)
val The value to send
Returns
0 on success, -errno on error
Definition at line 486 of file signal.cpp.
     {
         PCB *pcb = (PCB *)ctx;
         sig = CTNif(sig);
         LastSignal = (Signals)sig;
         debug("Sending signal %s to %s(%d)",
               sigStr[sig], pcb->Name, pcb->ID);
         if (SignalAction[sig].__sa_handler.sa_handler)
         {
             if (pcb->Security.ExecutionMode == Kernel)
             {
                 info("Kernel processes cannot have signal handlers");
                 return -EINVAL;
             }
             debug("sa_handler: %#lx",
                   SignalAction[sig].__sa_handler.sa_handler);
             debug("Adding signal %s to queue", sigStr[sig]);
             goto CompleteSignal;
         }
         debug("Signal disposition: %s", dispStr[sigDisp[sig]]);
         switch (sigDisp[sig])
         {
         case SIG_TERM:
         {
             if (unlikely(pcb->Security.IsCritical))
             {
                 debug("Critical process %s received signal %s(%d): Terminated",
                       pcb->Name, sigStr[sig], sig);
                 // int3;
             }
             pcb->SetExitCode(MakeExitCode(sig));
             debug("We have %d watchers", this->Watchers.size());
             if (this->Watchers.size() > 0)
                 pcb->SetState(Zombie);
             else
                 pcb->SetState(Terminated);
             break;
         }
         case SIG_IGN:
         {
             debug("Ignoring signal %d", sig);
             return 0;
         }
         case SIG_CORE:
         {
             fixme("core dump");
             if (unlikely(pcb->Security.IsCritical))
             {
                 debug("Critical process %s received signal %s(%d): Core dumped",
                       pcb->Name, sigStr[sig], sig);
                 // int3;
             }
             pcb->SetExitCode(MakeExitCode(sig));
             debug("We have %d watchers", this->Watchers.size());
             if (this->Watchers.size() > 0)
                 pcb->SetState(CoreDump);
             else
                 pcb->SetState(Terminated);
             break;
         }
         case SIG_STOP:
         {
             pcb->SetState(Stopped);
             break;
         }
         case SIG_CONT:
         {
             pcb->SetState(Ready);
             break;
         }
         default:
             assert(!"Invalid signal disposition");
             return -EINVAL;
         };
     CompleteSignal:
         if (pcb->Security.ExecutionMode == Kernel)
         {
             debug("Kernel process %s received signal %s(%d)! Ignoring... (with exceptions)",
                   pcb->Name, sigStr[sig], sig);
             return 0;
         }
         if (unlikely(TrampAddr == nullptr))
         {
             debug("Trampoline not set up yet");
             switch (thisThread->Info.Compatibility)
             {
             case Native:
             {
                 debug("%#lx - %#lx",
                       &_sig_native_trampoline_end,
                       &_sig_native_trampoline_start);
                 TrampSz = (size_t)&_sig_native_trampoline_end -
                           (size_t)&_sig_native_trampoline_start;
                 TrampAddr = pcb->vma->RequestPages(TO_PAGES(TrampSz), true);
                 memcpy((void *)TrampAddr,
                        (void *)&_sig_native_trampoline_start,
                        TrampSz);
                 debug("Trampoline at %#lx with size %lld",
                       TrampAddr, TrampSz);
                 break;
             }
             case Linux:
             {
                 debug("%#lx - %#lx",
                       &_sig_linux_trampoline_end,
                       &_sig_linux_trampoline_start);
                 TrampSz = (size_t)&_sig_linux_trampoline_end -
                           (size_t)&_sig_linux_trampoline_start;
                 TrampAddr = pcb->vma->RequestPages(TO_PAGES(TrampSz), true);
                 memcpy((void *)TrampAddr,
                        (void *)&_sig_linux_trampoline_start,
                        TrampSz);
                 debug("Trampoline at %#lx with size %lld",
                       TrampAddr, TrampSz);
                 break;
             }
             default:
             {
                 assert(!"Not implemented");
                 break;
             }
             }
         }
         debug("Signal %s(%d) completed", sigStr[sig], sig);
         if (sigDisp[sig] != SIG_IGN)
         {
             foreach (auto info in Watchers)
             {
                 Signal *who = (Signal *)info.val.sival_ptr;
                 assert(who != nullptr);
                 debug("Sending SIGCHLD to %s(%d)",
                       ((PCB *)who->GetContext())->Name,
                       ((PCB *)who->GetContext())->ID);
                 who->SendSignal(SIGCHLD, val);
             }
         }
         debug("Adding signal to queue");
         SignalQueue.push_back({.sig = sig, .val = val});
         return 0;
     }
References _sig_linux_trampoline_end, _sig_linux_trampoline_start, _sig_native_trampoline_end, _sig_native_trampoline_start, assert, Tasking::CoreDump, CTNif, debug, EINVAL, fixme, GetContext(), Tasking::PCB::ID, info, Tasking::Kernel, LastSignal, Tasking::Linux, MakeExitCode(), memcpy, Tasking::PCB::Name, Tasking::Native, Tasking::Ready, Memory::VirtualMemoryArea::RequestPages(), Tasking::PCB::Security, SendSignal(), Tasking::PCB::SetExitCode(), Tasking::PCB::SetState(), SIG_CONT, SIG_CORE, SIG_IGN, SIG_STOP, SIG_TERM, SIGCHLD, sigDisp, SignalQueue, Tasking::Stopped, Tasking::Terminated, thisThread, TO_PAGES, TrampAddr, TrampSz, unlikely, val, Tasking::PCB::vma, Watchers, and Tasking::Zombie.
Referenced by Tasking::TCB::SendSignal(), and SendSignal().
SetAction()
int Tasking::Signal::SetAction (int sig, const sigaction act)
Definition at line 447 of file signal.cpp.
     {
         SmartLock(SignalLock);
         if ((size_t)sig > sizeof(SignalAction) / sizeof(SignalAction[0]))
             return -EINVAL;
         sig = CTNif(sig);
         SignalAction[sig].__sa_handler.sa_handler = act.__sa_handler.sa_handler;
         SignalAction[sig].sa_mask = act.sa_mask;
         SignalAction[sig].sa_flags = act.sa_flags;
         debug("Set action for %s with handler %#lx, mask %#lx and flags %#lx",
               LinuxSig() ? lSigStr[sig] : sigStr[sig],
               SignalAction[sig].__sa_handler.sa_handler,
               SignalAction[sig].sa_mask,
               SignalAction[sig].sa_flags);
         return 0;
     }
References act(), CTNif, debug, EINVAL, and LinuxSig().
Referenced by linux_sigaction().
SetMask()
sigset_t Tasking::Signal::SetMask (sigset_t sig)
Set the signal mask
Parameters
sig The signal to set
Returns
Old mask
Definition at line 438 of file signal.cpp.
     {
         SmartLock(SignalLock);
         sig = CSigTNif(sig);
         sigset_t oldMask = SignalMask.exchange(sig);
         debug("%#lx -> %#lx", oldMask, SignalMask);
         return CSigTLif(oldMask);
     }
References CSigTLif, CSigTNif, debug, and SignalMask.
Referenced by linux_sigprocmask().
Unblock()
sigset_t Tasking::Signal::Unblock (sigset_t sig)
Unmask a signal
Parameters
sig The signal to set
Returns
Old mask
Definition at line 429 of file signal.cpp.
     {
         SmartLock(SignalLock);
         sig = CSigTNif(sig);
         sigset_t oldMask = SignalMask.fetch_and(~sig);
         debug("%#lx -> %#lx", oldMask, SignalMask);
         return CSigTLif(oldMask);
     }
References CSigTLif, CSigTNif, debug, and SignalMask.
Referenced by linux_sigprocmask().
WaitAnySignal()
int Tasking::Signal::WaitAnySignal ()
Definition at line 640 of file signal.cpp.
     {
         /* Sleep until a signal that terminated or invokes
         the signal catch function */
         debug("Waiting for any signal");
         size_t oldSize = SignalQueue.size();
     Reset:
         while (SignalQueue.size() == oldSize)
             TaskManager->Yield();
         if (SignalQueue.size() > oldSize)
         {
             debug("Added signal to queue %d > %d",
                   SignalQueue.size(), oldSize);
             oldSize = SignalQueue.size();
             goto Reset;
         }
         debug("Signal received");
         return -EINTR;
     }
References debug, EINTR, SignalQueue, TaskManager, and Tasking::Task::Yield().
Referenced by linux_pause().
WaitSignal()
int Tasking::Signal::WaitSignal (int sig, union sigval * val)
Wait for a signal
Parameters
sig The signal to wait for (compatibility specific)
val The value to wait for
Returns
0 on success, -errno on error
Definition at line 664 of file signal.cpp.
     {
         return 0;
     }
WaitSignalTimeout()
int Tasking::Signal::WaitSignalTimeout (int sig, union sigval * val, uint64_t timeout)
Wait for a signal with a timeout
Parameters
sig The signal to wait for (compatibility specific)
val The value to wait for
timeout The timeout to wait for
Returns
0 on success, -errno on error
Definition at line 669 of file signal.cpp.
     {
         return 0;
     }
Field Documentation
ctx
void* Tasking::Signal::ctx private
Definition at line 384 of file signal.hpp.
Referenced by GetContext(), RestoreHandleSignal(), and Signal().
LastSignal
Signals Tasking::Signal::LastSignal = SIG_NULL private
Definition at line 385 of file signal.hpp.
Referenced by GetLastSignal(), and SendSignal().
lMasks
const sigset_t Tasking::Signal::lMasks private
Initial value:
= ToFlag(linux_SIGKILL) |
                                ToFlag(linux_SIGSTOP) |
                                ToFlag(linux_SIGCONT) |
                                ToFlag(linux_SIGSEGV) |
                                ToFlag(linux_SIGBUS) |
                                ToFlag(linux_SIGILL) |
                                ToFlag(linux_SIGFPE)
Definition at line 415 of file signal.hpp.
Referenced by RemoveUnmaskable().
nMasks
const sigset_t Tasking::Signal::nMasks private
Initial value:
= ToFlag(SIGKILL) |
                                ToFlag(SIGSTOP) |
                                ToFlag(SIGCONT) |
                                ToFlag(SIGSEGV) |
                                ToFlag(SIGBUS) |
                                ToFlag(SIGILL) |
                                ToFlag(SIGFPE)
Definition at line 407 of file signal.hpp.
Referenced by RemoveUnmaskable().
sigDisp
SignalDisposition Tasking::Signal::sigDisp[SIGNAL_MAX] private
Definition at line 394 of file signal.hpp.
Referenced by SendSignal(), and Signal().
SignalAction
sigaction Tasking::Signal::SignalAction[SIGNAL_MAX] {} private
Definition at line 393 of file signal.hpp.
SignalMask
std::atomic<sigset_t> Tasking::Signal::SignalMask = 0 private
Definition at line 392 of file signal.hpp.
Referenced by Block(), GetMask(), HandleSignal(), RestoreHandleSignal(), SetMask(), and Unblock().
SignalQueue
std::vector<SignalInfo> Tasking::Signal::SignalQueue private
Definition at line 391 of file signal.hpp.
Referenced by AddSignal(), HandleSignal(), RemoveSignal(), SendSignal(), and WaitAnySignal().
TrampAddr
void* Tasking::Signal::TrampAddr = nullptr private
Definition at line 388 of file signal.hpp.
Referenced by HandleSignal(), and SendSignal().
TrampSz
size_t Tasking::Signal::TrampSz = 0 private
Definition at line 389 of file signal.hpp.
Referenced by SendSignal().
Watchers
std::vector<SignalInfo> Tasking::Signal::Watchers private
Definition at line 395 of file signal.hpp.
Referenced by AddWatcher(), RemoveWatcher(), and SendSignal().
The documentation for this class was generated from the following files:
Kernel/include/signal.hpp
Kernel/tasking/signal.cpp