Fennix: Kernel/Modules/drv.hpp File Reference
drv.hpp File Reference
#include <types.h>
Functions
bool StartAHCI ()
bool StartVMwareMouse ()
bool StartPS2Mouse ()
bool StartPS2Keyboard ()
bool StartATA ()
bool StartAC97 ()
bool StartRTL8139 ()
bool StartPCNET ()
bool StartGigabit ()
Function Documentation
StartAC97()
bool StartAC97 ()
Definition at line 258 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = AudioCodec97::DriverEntry,
         .ExtendedHeader = &AC97ExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References AC97ExtendedHeader, AudioCodec97::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartAHCI()
bool StartAHCI ()
Definition at line 198 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = AdvancedHostControllerInterface::DriverEntry,
         .ExtendedHeader = &AHCIExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References AHCIExtendedHeader, AdvancedHostControllerInterface::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartATA()
bool StartATA ()
Definition at line 246 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = AdvancedTechnologyAttachment::DriverEntry,
         .ExtendedHeader = &ATAExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References ATAExtendedHeader, AdvancedTechnologyAttachment::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartGigabit()
bool StartGigabit ()
Definition at line 294 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = Gigabit::DriverEntry,
         .ExtendedHeader = &IntelGigabitExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References Gigabit::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, IntelGigabitExtendedHeader, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartPCNET()
bool StartPCNET ()
Definition at line 282 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = PCNET::DriverEntry,
         .ExtendedHeader = &AMDPCNETExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References AMDPCNETExtendedHeader, PCNET::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartPS2Keyboard()
bool StartPS2Keyboard ()
Definition at line 234 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = PS2Keyboard::DriverEntry,
         .ExtendedHeader = &PS2KeyboardExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References PS2Keyboard::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and PS2KeyboardExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
StartPS2Mouse()
bool StartPS2Mouse ()
Definition at line 222 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = PS2Mouse::DriverEntry,
         .ExtendedHeader = &PS2MouseExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References PS2Mouse::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and PS2MouseExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
StartRTL8139()
bool StartRTL8139 ()
Definition at line 270 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = RTL8139::DriverEntry,
         .ExtendedHeader = &RTL8139ExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References RTL8139::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and RTL8139ExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
StartVMwareMouse()
bool StartVMwareMouse ()
Definition at line 210 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = VMwareMouse::DriverEntry,
         .ExtendedHeader = &VMwareVirtualMouseExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References VMwareMouse::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and VMwareVirtualMouseExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().