Fennix Userspace: music_module_t Struct Reference
music_module_t Struct Reference
#include <i_sound.h>
Data Fields
snddevice_t * sound_devices
int num_sound_devices
boolean(* Init)(void)
void(* Shutdown)(void)
void(* SetMusicVolume)(int volume)
void(* PauseMusic)(void)
void(* ResumeMusic)(void)
void *(* RegisterSong)(void *data, int len)
void(* UnRegisterSong)(void *handle)
void(* PlaySong)(void *handle, boolean looping)
void(* StopSong)(void)
boolean(* MusicIsPlaying)(void)
void(* Poll)(void)
Detailed Description
Definition at line 164 of file i_sound.h.
Field Documentation
Init
boolean(* music_module_t::Init) (void)
Definition at line 173 of file i_sound.h.
Referenced by I_InitMusic().
MusicIsPlaying
boolean(* music_module_t::MusicIsPlaying) (void)
Definition at line 210 of file i_sound.h.
Referenced by I_MusicIsPlaying().
num_sound_devices
int music_module_t::num_sound_devices
Definition at line 169 of file i_sound.h.
PauseMusic
void(* music_module_t::PauseMusic) (void)
Definition at line 185 of file i_sound.h.
Referenced by I_PauseSong().
PlaySong
void(* music_module_t::PlaySong) (void *handle, boolean looping)
Definition at line 202 of file i_sound.h.
Referenced by I_PlaySong().
Poll
void(* music_module_t::Poll) (void)
Definition at line 214 of file i_sound.h.
Referenced by I_UpdateSound().
RegisterSong
void*(* music_module_t::RegisterSong) (void *data, int len)
Definition at line 194 of file i_sound.h.
Referenced by I_RegisterSong().
ResumeMusic
void(* music_module_t::ResumeMusic) (void)
Definition at line 189 of file i_sound.h.
Referenced by I_ResumeSong().
SetMusicVolume
void(* music_module_t::SetMusicVolume) (int volume)
Definition at line 181 of file i_sound.h.
Referenced by I_SetMusicVolume().
Shutdown
void(* music_module_t::Shutdown) (void)
Definition at line 177 of file i_sound.h.
Referenced by I_ShutdownSound().
sound_devices
snddevice_t* music_module_t::sound_devices
Definition at line 168 of file i_sound.h.
StopSong
void(* music_module_t::StopSong) (void)
Definition at line 206 of file i_sound.h.
Referenced by I_StopSong().
UnRegisterSong
void(* music_module_t::UnRegisterSong) (void *handle)
Definition at line 198 of file i_sound.h.
Referenced by I_UnRegisterSong().
The documentation for this struct was generated from the following file:
Userspace/apps/user/games/doomgeneric/doomgeneric/i_sound.h