Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/unxz/xz_dec_stream.c File Reference
xz_dec_stream.c File Reference
#include "xz_private.h"
#include "xz_stream.h"
Data Structures
struct xz_dec_hash
struct xz_dec
struct xz_dec.block_header
struct xz_dec.block
struct xz_dec.index
struct xz_dec.temp
Functions
static bool XZ_FUNC fill_temp (struct xz_dec *s, struct xz_buf *b)
static enum xz_ret XZ_FUNC dec_vli (struct xz_dec *s, const uint8_t *in, size_t *in_pos, size_t in_size)
static enum xz_ret XZ_FUNC dec_block (struct xz_dec *s, struct xz_buf *b)
static void XZ_FUNC index_update (struct xz_dec *s, const struct xz_buf *b)
static enum xz_ret XZ_FUNC dec_index (struct xz_dec *s, struct xz_buf *b)
static enum xz_ret XZ_FUNC crc32_validate (struct xz_dec *s, struct xz_buf *b)
static bool XZ_FUNC check_skip (struct xz_dec *s, struct xz_buf *b)
static enum xz_ret XZ_FUNC dec_stream_header (struct xz_dec *s)
static enum xz_ret XZ_FUNC dec_stream_footer (struct xz_dec *s)
static enum xz_ret XZ_FUNC dec_block_header (struct xz_dec *s)
static NOINLINE enum xz_ret XZ_FUNC dec_main (struct xz_dec *s, struct xz_buf *b)
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_run (struct xz_dec *s, struct xz_buf *b)
XZ_EXTERN struct xz_dec *XZ_FUNC xz_dec_init (enum xz_mode mode, uint32_t dict_max)
XZ_EXTERN void XZ_FUNC xz_dec_reset (struct xz_dec *s)
XZ_EXTERN void XZ_FUNC xz_dec_end (struct xz_dec *s)
Variables
static const uint8_t check_sizes [16]
Data Structure Documentation
xz_dec_hash
struct xz_dec_hash
Definition at line 14 of file xz_dec_stream.c.
Data Fields
uint32_t crc32
vli_type uncompressed
vli_type unpadded
xz_dec.block_header
struct xz_dec.block_header
Definition at line 61 of file xz_dec_stream.c.
Data Fields
vli_type compressed
uint32_t size
vli_type uncompressed
xz_dec.block
struct xz_dec.block
Definition at line 79 of file xz_dec_stream.c.
Data Fields
vli_type compressed
vli_type count
struct xz_dec_hash hash
vli_type uncompressed
xz_dec.index
struct xz_dec.index
Definition at line 97 of file xz_dec_stream.c.
Data Fields
vli_type count
struct xz_dec_hash hash
enum xz_dec sequence
vli_type size
xz_dec.temp
struct xz_dec.temp
Definition at line 125 of file xz_dec_stream.c.
Data Fields
uint8_t buf[1024]
size_t pos
size_t size
Function Documentation
check_skip()
static bool XZ_FUNC check_skip (struct xz_dec * s, struct xz_buf * b) static
Definition at line 369 of file xz_dec_stream.c.
 {
     while (s->pos < check_sizes[s->check_type]) {
         if (b->in_pos == b->in_size)
             return false;
         ++b->in_pos;
         ++s->pos;
     }
     s->pos = 0;
     return true;
 }
References check_sizes, xz_buf::in_pos, xz_buf::in_size, and s.
Referenced by dec_main().
crc32_validate()
static enum xz_ret XZ_FUNC crc32_validate (struct xz_dec * s, struct xz_buf * b) static
Definition at line 281 of file xz_dec_stream.c.
 {
     do {
         if (b->in_pos == b->in_size)
             return XZ_OK;
         if (((s->crc32 >> s->pos) & 0xFF) != b->in[b->in_pos++])
             return XZ_DATA_ERROR;
         s->pos += 8;
     } while (s->pos < 32);
     s->crc32 = 0;
     s->pos = 0;
     return XZ_STREAM_END;
 }
References xz_buf::in, xz_buf::in_pos, s, and xz_crc32().
Referenced by dec_main().
dec_block()
static enum xz_ret XZ_FUNC dec_block (struct xz_dec * s, struct xz_buf * b) static
Definition at line 157 of file xz_dec_stream.c.
 {
     enum xz_ret ret;
     s->in_start = b->in_pos;
     s->out_start = b->out_pos;
 #ifdef XZ_DEC_BCJ
     if (s->bcj_active)
         ret = xz_dec_bcj_run(s->bcj, s->lzma2, b);
     else
 #endif
         ret = xz_dec_lzma2_run(s->lzma2, b);
     s->block.compressed += b->in_pos - s->in_start;
     s->block.uncompressed += b->out_pos - s->out_start;
     /*
      * There is no need to separately check for VLI_UNKNOWN, since
      * the observed sizes are always smaller than VLI_UNKNOWN.
      */
     if (s->block.compressed > s->block_header.compressed
             || s->block.uncompressed
                 > s->block_header.uncompressed)
         return XZ_DATA_ERROR;
     if (s->check_type == XZ_CHECK_CRC32)
         s->crc32 = xz_crc32(b->out + s->out_start,
                 b->out_pos - s->out_start, s->crc32);
     if (ret == XZ_STREAM_END) {
         if (s->block_header.compressed != VLI_UNKNOWN
                 && s->block_header.compressed
                     != s->block.compressed)
             return XZ_DATA_ERROR;
         if (s->block_header.uncompressed != VLI_UNKNOWN
                 && s->block_header.uncompressed
                     != s->block.uncompressed)
             return XZ_DATA_ERROR;
         s->block.hash.unpadded += s->block_header.size
                 + s->block.compressed;
 #ifdef XZ_DEC_ANY_CHECK
         s->block.hash.unpadded += check_sizes[s->check_type];
 #else
         if (s->check_type == XZ_CHECK_CRC32)
             s->block.hash.unpadded += 4;
 #endif
         s->block.hash.uncompressed += s->block.uncompressed;
         s->block.hash.crc32 = xz_crc32(
                 (const uint8_t *)&s->block.hash,
                 sizeof(s->block.hash), s->block.hash.crc32);
         ++s->block.count;
     }
     return ret;
 }
References xz_buf::in, xz_buf::in_pos, xz_buf::in_size, memcpy(), min_t, and s.
Referenced by dec_main().
dec_block_header()
static enum xz_ret XZ_FUNC dec_block_header (struct xz_dec * s) static
Definition at line 369 of file xz_dec_stream.c.
 {
     enum xz_ret ret;
     /*
      * Validate the CRC32. We know that the temp buffer is at least
      * eight bytes so this is safe.
      */
     s->temp.size -= 4;
     if (xz_crc32(s->temp.buf, s->temp.size, 0)
             != get_le32(s->temp.buf + s->temp.size))
         return XZ_DATA_ERROR;
     s->temp.pos = 2;
     /*
      * Catch unsupported Block Flags. We support only one or two filters
      * in the chain, so we catch that with the same test.
      */
 #ifdef XZ_DEC_BCJ
     if (s->temp.buf[1] & 0x3E)
 #else
     if (s->temp.buf[1] & 0x3F)
 #endif
         return XZ_OPTIONS_ERROR;
     /* Compressed Size */
     if (s->temp.buf[1] & 0x40) {
         if (dec_vli(s, s->temp.buf, &s->temp.pos, s->temp.size)
                     != XZ_STREAM_END)
             return XZ_DATA_ERROR;
         s->block_header.compressed = s->vli;
     } else {
         s->block_header.compressed = VLI_UNKNOWN;
     }
     /* Uncompressed Size */
     if (s->temp.buf[1] & 0x80) {
         if (dec_vli(s, s->temp.buf, &s->temp.pos, s->temp.size)
                 != XZ_STREAM_END)
             return XZ_DATA_ERROR;
         s->block_header.uncompressed = s->vli;
     } else {
         s->block_header.uncompressed = VLI_UNKNOWN;
     }
 #ifdef XZ_DEC_BCJ
     /* If there are two filters, the first one must be a BCJ filter. */
     s->bcj_active = s->temp.buf[1] & 0x01;
     if (s->bcj_active) {
         if (s->temp.size - s->temp.pos < 2)
             return XZ_OPTIONS_ERROR;
         ret = xz_dec_bcj_reset(s->bcj, s->temp.buf[s->temp.pos++]);
         if (ret != XZ_OK)
             return ret;
         /*
          * We don't support custom start offset,
          * so Size of Properties must be zero.
          */
         if (s->temp.buf[s->temp.pos++] != 0x00)
             return XZ_OPTIONS_ERROR;
     }
 #endif
     /* Valid Filter Flags always take at least two bytes. */
     if (s->temp.size - s->temp.pos < 2)
         return XZ_DATA_ERROR;
     /* Filter ID = LZMA2 */
     if (s->temp.buf[s->temp.pos++] != 0x21)
         return XZ_OPTIONS_ERROR;
     /* Size of Properties = 1-byte Filter Properties */
     if (s->temp.buf[s->temp.pos++] != 0x01)
         return XZ_OPTIONS_ERROR;
     /* Filter Properties contains LZMA2 dictionary size. */
     if (s->temp.size - s->temp.pos < 1)
         return XZ_DATA_ERROR;
     ret = xz_dec_lzma2_reset(s->lzma2, s->temp.buf[s->temp.pos++]);
     if (ret != XZ_OK)
         return ret;
     /* The rest must be Header Padding. */
     while (s->temp.pos < s->temp.size)
         if (s->temp.buf[s->temp.pos++] != 0x00)
             return XZ_OPTIONS_ERROR;
     s->temp.pos = 0;
     s->block.compressed = 0;
     s->block.uncompressed = 0;
     return XZ_OK;
 }
Referenced by dec_main().
dec_index()
static enum xz_ret XZ_FUNC dec_index (struct xz_dec * s, struct xz_buf * b) static
Definition at line 281 of file xz_dec_stream.c.
 {
     enum xz_ret ret;
     do {
         ret = dec_vli(s, b->in, &b->in_pos, b->in_size);
         if (ret != XZ_STREAM_END) {
             index_update(s, b);
             return ret;
         }
         switch (s->index.sequence) {
         case SEQ_INDEX_COUNT:
             s->index.count = s->vli;
             /*
              * Validate that the Number of Records field
              * indicates the same number of Records as
              * there were Blocks in the Stream.
              */
             if (s->index.count != s->block.count)
                 return XZ_DATA_ERROR;
             s->index.sequence = SEQ_INDEX_UNPADDED;
             break;
         case SEQ_INDEX_UNPADDED:
             s->index.hash.unpadded += s->vli;
             s->index.sequence = SEQ_INDEX_UNCOMPRESSED;
             break;
         case SEQ_INDEX_UNCOMPRESSED:
             s->index.hash.uncompressed += s->vli;
             s->index.hash.crc32 = xz_crc32(
                     (const uint8_t *)&s->index.hash,
                     sizeof(s->index.hash),
                     s->index.hash.crc32);
             --s->index.count;
             s->index.sequence = SEQ_INDEX_UNPADDED;
             break;
         }
     } while (s->index.count > 0);
     return XZ_STREAM_END;
 }
Referenced by dec_main().
dec_main()
static NOINLINE enum xz_ret XZ_FUNC dec_main (struct xz_dec * s, struct xz_buf * b) static
Definition at line 548 of file xz_dec_stream.c.
 {
     enum xz_ret ret;
     /*
      * Store the start position for the case when we are in the middle
      * of the Index field.
      */
     s->in_start = b->in_pos;
     while (true) {
         switch (s->sequence) {
         case SEQ_STREAM_HEADER:
             /*
              * Stream Header is copied to s->temp, and then
              * decoded from there. This way if the caller
              * gives us only little input at a time, we can
              * still keep the Stream Header decoding code
              * simple. Similar approach is used in many places
              * in this file.
              */
             if (!fill_temp(s, b))
                 return XZ_OK;
             /*
              * If dec_stream_header() returns
              * XZ_UNSUPPORTED_CHECK, it is still possible
              * to continue decoding if working in multi-call
              * mode. Thus, update s->sequence before calling
              * dec_stream_header().
              */
             s->sequence = SEQ_BLOCK_START;
             ret = dec_stream_header(s);
             if (ret != XZ_OK)
                 return ret;
         case SEQ_BLOCK_START:
             /* We need one byte of input to continue. */
             if (b->in_pos == b->in_size)
                 return XZ_OK;
             /* See if this is the beginning of the Index field. */
             if (b->in[b->in_pos] == 0) {
                 s->in_start = b->in_pos++;
                 s->sequence = SEQ_INDEX;
                 break;
             }
             /*
              * Calculate the size of the Block Header and
              * prepare to decode it.
              */
             s->block_header.size
                 = ((uint32_t)b->in[b->in_pos] + 1) * 4;
             s->temp.size = s->block_header.size;
             s->temp.pos = 0;
             s->sequence = SEQ_BLOCK_HEADER;
         case SEQ_BLOCK_HEADER:
             if (!fill_temp(s, b))
                 return XZ_OK;
             ret = dec_block_header(s);
             if (ret != XZ_OK)
                 return ret;
             s->sequence = SEQ_BLOCK_UNCOMPRESS;
         case SEQ_BLOCK_UNCOMPRESS:
             ret = dec_block(s, b);
             if (ret != XZ_STREAM_END)
                 return ret;
             s->sequence = SEQ_BLOCK_PADDING;
         case SEQ_BLOCK_PADDING:
             /*
              * Size of Compressed Data + Block Padding
              * must be a multiple of four. We don't need
              * s->block.compressed for anything else
              * anymore, so we use it here to test the size
              * of the Block Padding field.
              */
             while (s->block.compressed & 3) {
                 if (b->in_pos == b->in_size)
                     return XZ_OK;
                 if (b->in[b->in_pos++] != 0)
                     return XZ_DATA_ERROR;
                 ++s->block.compressed;
             }
             s->sequence = SEQ_BLOCK_CHECK;
         case SEQ_BLOCK_CHECK:
             if (s->check_type == XZ_CHECK_CRC32) {
                 ret = crc32_validate(s, b);
                 if (ret != XZ_STREAM_END)
                     return ret;
             }
 #ifdef XZ_DEC_ANY_CHECK
             else if (!check_skip(s, b)) {
                 return XZ_OK;
             }
 #endif
             s->sequence = SEQ_BLOCK_START;
             break;
         case SEQ_INDEX:
             ret = dec_index(s, b);
             if (ret != XZ_STREAM_END)
                 return ret;
             s->sequence = SEQ_INDEX_PADDING;
         case SEQ_INDEX_PADDING:
             while ((s->index.size + (b->in_pos - s->in_start))
                     & 3) {
                 if (b->in_pos == b->in_size) {
                     index_update(s, b);
                     return XZ_OK;
                 }
                 if (b->in[b->in_pos++] != 0)
                     return XZ_DATA_ERROR;
             }
             /* Finish the CRC32 value and Index size. */
             index_update(s, b);
             /* Compare the hashes to validate the Index field. */
             if (!memeq(&s->block.hash, &s->index.hash,
                     sizeof(s->block.hash)))
                 return XZ_DATA_ERROR;
             s->sequence = SEQ_INDEX_CRC32;
         case SEQ_INDEX_CRC32:
             ret = crc32_validate(s, b);
             if (ret != XZ_STREAM_END)
                 return ret;
             s->temp.size = STREAM_HEADER_SIZE;
             s->sequence = SEQ_STREAM_FOOTER;
         case SEQ_STREAM_FOOTER:
             if (!fill_temp(s, b))
                 return XZ_OK;
             return dec_stream_footer(s);
         }
     }
     /* Never reached */
 }
References check_skip(), crc32_validate(), dec_block(), dec_block_header(), dec_index(), dec_stream_footer(), dec_stream_header(), fill_temp(), xz_buf::in, xz_buf::in_pos, xz_buf::in_size, index_update(), memeq, s, STREAM_HEADER_SIZE, XZ_CHECK_CRC32, XZ_DATA_ERROR, XZ_OK, and XZ_STREAM_END.
Referenced by xz_dec_run().
dec_stream_footer()
static enum xz_ret XZ_FUNC dec_stream_footer (struct xz_dec * s) static
Definition at line 369 of file xz_dec_stream.c.
 {
     if (!memeq(s->temp.buf + 10, FOOTER_MAGIC, FOOTER_MAGIC_SIZE))
         return XZ_DATA_ERROR;
     if (xz_crc32(s->temp.buf + 4, 6, 0) != get_le32(s->temp.buf))
         return XZ_DATA_ERROR;
     /*
      * Validate Backward Size. Note that we never added the size of the
      * Index CRC32 field to s->index.size, thus we use s->index.size / 4
      * instead of s->index.size / 4 - 1.
      */
     if ((s->index.size >> 2) != get_le32(s->temp.buf + 4))
         return XZ_DATA_ERROR;
     if (s->temp.buf[8] != 0 || s->temp.buf[9] != s->check_type)
         return XZ_DATA_ERROR;
     /*
      * Use XZ_STREAM_END instead of XZ_OK to be more convenient
      * for the caller.
      */
     return XZ_STREAM_END;
 }
Referenced by dec_main().
dec_stream_header()
static enum xz_ret XZ_FUNC dec_stream_header (struct xz_dec * s) static
Definition at line 369 of file xz_dec_stream.c.
 {
     if (!memeq(s->temp.buf, HEADER_MAGIC, HEADER_MAGIC_SIZE))
         return XZ_FORMAT_ERROR;
     if (xz_crc32(s->temp.buf + HEADER_MAGIC_SIZE, 2, 0)
             != get_le32(s->temp.buf + HEADER_MAGIC_SIZE + 2))
         return XZ_DATA_ERROR;
     if (s->temp.buf[HEADER_MAGIC_SIZE] != 0)
         return XZ_OPTIONS_ERROR;
     /*
      * Of integrity checks, we support only none (Check ID = 0) and
      * CRC32 (Check ID = 1). However, if XZ_DEC_ANY_CHECK is defined,
      * we will accept other check types too, but then the check won't
      * be verified and a warning (XZ_UNSUPPORTED_CHECK) will be given.
      */
     s->check_type = s->temp.buf[HEADER_MAGIC_SIZE + 1];
 #ifdef XZ_DEC_ANY_CHECK
     if (s->check_type > XZ_CHECK_MAX)
         return XZ_OPTIONS_ERROR;
     if (s->check_type > XZ_CHECK_CRC32)
         return XZ_UNSUPPORTED_CHECK;
 #else
     if (s->check_type > XZ_CHECK_CRC32)
         return XZ_OPTIONS_ERROR;
 #endif
     return XZ_OK;
 }
Referenced by dec_main().
dec_vli()
static enum xz_ret XZ_FUNC dec_vli (struct xz_dec * s, const uint8_t * in, size_t * in_pos, size_t in_size) static
Definition at line 157 of file xz_dec_stream.c.
 {
     uint8_t byte;
     if (s->pos == 0)
         s->vli = 0;
     while (*in_pos < in_size) {
         byte = in[*in_pos];
         ++*in_pos;
         s->vli |= (vli_type)(byte & 0x7F) << s->pos;
         if ((byte & 0x80) == 0) {
             /* Don't allow non-minimal encodings. */
             if (byte == 0 && s->pos != 0)
                 return XZ_DATA_ERROR;
             s->pos = 0;
             return XZ_STREAM_END;
         }
         s->pos += 7;
         if (s->pos == 7 * VLI_BYTES_MAX)
             return XZ_DATA_ERROR;
     }
     return XZ_OK;
 }
fill_temp()
static bool XZ_FUNC fill_temp (struct xz_dec * s, struct xz_buf * b) static
Definition at line 157 of file xz_dec_stream.c.
 {
     size_t copy_size = min_t(size_t,
             b->in_size - b->in_pos, s->temp.size - s->temp.pos);
     memcpy(s->temp.buf + s->temp.pos, b->in + b->in_pos, copy_size);
     b->in_pos += copy_size;
     s->temp.pos += copy_size;
     if (s->temp.pos == s->temp.size) {
         s->temp.pos = 0;
         return true;
     }
     return false;
 }
Referenced by dec_main().
index_update()
static void XZ_FUNC index_update (struct xz_dec * s, const struct xz_buf * b) static
Definition at line 281 of file xz_dec_stream.c.
 {
     size_t in_used = b->in_pos - s->in_start;
     s->index.size += in_used;
     s->crc32 = xz_crc32(b->in + s->in_start, in_used, s->crc32);
 }
Referenced by dec_main().
xz_dec_end()
XZ_EXTERN void XZ_FUNC xz_dec_end (struct xz_dec * s)
xz_dec_end() - Free the memory allocated for the decoder state @s: Decoder state allocated using xz_dec_init(). If s is NULL, this function does nothing.
Definition at line 811 of file xz_dec_stream.c.
 {
     if (s != NULL) {
         xz_dec_lzma2_end(s->lzma2);
 #ifdef XZ_DEC_BCJ
         xz_dec_bcj_end(s->bcj);
 #endif
         kfree(s);
     }
 }
References kfree, NULL, s, and xz_dec_lzma2_end().
Referenced by IF_DESKTOP().
xz_dec_init()
XZ_EXTERN struct xz_dec* XZ_FUNC xz_dec_init (enum xz_mode mode, uint32_t dict_max)
xz_dec_init() - Allocate and initialize a XZ decoder state @mode: Operation mode @dict_max: Maximum size of the LZMA2 dictionary (history buffer) for multi-call decoding. This is ignored in single-call mode (mode == XZ_SINGLE). LZMA2 dictionary is always 2^n bytes or 2^n + 2^(n-1) bytes (the latter sizes are less common in practice), so other values for dict_max don't make sense. In the kernel, dictionary sizes of 64 KiB, 128 KiB, 256 KiB, 512 KiB, and 1 MiB are probably the only reasonable values, except for kernel and initramfs images where a bigger dictionary can be fine and useful.
Single-call mode (XZ_SINGLE): xz_dec_run() decodes the whole stream at once. The caller must provide enough output space or the decoding will fail. The output space is used as the dictionary buffer, which is why there is no need to allocate the dictionary as part of the decoder's internal state.
Because the output buffer is used as the workspace, streams encoded using a big dictionary are not a problem in single-call mode. It is enough that the output buffer is big enough to hold the actual uncompressed data; it can be smaller than the dictionary size stored in the stream headers.
Multi-call mode with preallocated dictionary (XZ_PREALLOC): dict_max bytes of memory is preallocated for the LZMA2 dictionary. This way there is no risk that xz_dec_run() could run out of memory, since xz_dec_run() will never allocate any memory. Instead, if the preallocated dictionary is too small for decoding the given input stream, xz_dec_run() will return XZ_MEMLIMIT_ERROR. Thus, it is important to know what kind of data will be decoded to avoid allocating excessive amount of memory for the dictionary.
Multi-call mode with dynamically allocated dictionary (XZ_DYNALLOC): dict_max specifies the maximum allowed dictionary size that xz_dec_run() may allocate once it has parsed the dictionary size from the stream headers. This way excessive allocations can be avoided while still limiting the maximum memory usage to a sane value to prevent running the system out of memory when decompressing streams from untrusted sources.
On success, xz_dec_init() returns a pointer to struct xz_dec, which is ready to be used with xz_dec_run(). If memory allocation fails, xz_dec_init() returns NULL.
Definition at line 768 of file xz_dec_stream.c.
 {
     struct xz_dec *s = kmalloc(sizeof(*s), GFP_KERNEL);
     if (s == NULL)
         return NULL;
     s->mode = mode;
 #ifdef XZ_DEC_BCJ
     s->bcj = xz_dec_bcj_create(DEC_IS_SINGLE(mode));
     if (s->bcj == NULL)
         goto error_bcj;
 #endif
     s->lzma2 = xz_dec_lzma2_create(mode, dict_max);
     if (s->lzma2 == NULL)
         goto error_lzma2;
     xz_dec_reset(s);
     return s;
 error_lzma2:
 #ifdef XZ_DEC_BCJ
     xz_dec_bcj_end(s->bcj);
 error_bcj:
 #endif
     kfree(s);
     return NULL;
 }
References DEC_IS_SINGLE, kfree, kmalloc, xz_dec::mode, NULL, s, xz_dec_lzma2_create(), and xz_dec_reset().
Referenced by IF_DESKTOP().
xz_dec_reset()
XZ_EXTERN void XZ_FUNC xz_dec_reset (struct xz_dec * s)
xz_dec_reset() - Reset an already allocated decoder state @s: Decoder state allocated using xz_dec_init()
This function can be used to reset the multi-call decoder state without freeing and reallocating memory with xz_dec_end() and xz_dec_init().
In single-call mode, xz_dec_reset() is always called in the beginning of xz_dec_run(). Thus, explicit call to xz_dec_reset() is useful only in multi-call mode.
Definition at line 799 of file xz_dec_stream.c.
 {
     s->sequence = SEQ_STREAM_HEADER;
     s->allow_buf_error = false;
     s->pos = 0;
     s->crc32 = 0;
     memzero(&s->block, sizeof(s->block));
     memzero(&s->index, sizeof(s->index));
     s->temp.pos = 0;
     s->temp.size = STREAM_HEADER_SIZE;
 }
References memzero, s, xz_dec::SEQ_STREAM_HEADER, and STREAM_HEADER_SIZE.
Referenced by IF_DESKTOP(), xz_dec_init(), and xz_dec_run().
xz_dec_run()
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_run (struct xz_dec * s, struct xz_buf * b)
xz_dec_run() - Run the XZ decoder @s: Decoder state allocated using xz_dec_init() : Input and output buffers
The possible return values depend on build options and operation mode. See enum xz_ret for details.
Note that if an error occurs in single-call mode (return value is not XZ_STREAM_END), b->in_pos and b->out_pos are not modified and the contents of the output buffer from b->out[b->out_pos] onward are undefined. This is true even after XZ_BUF_ERROR, because with some filter chains, there may be a second pass over the output buffer, and this pass cannot be properly done if the output buffer is truncated. Thus, you cannot give the single-call decoder a too small buffer and then expect to get that amount valid data from the beginning of the stream. You must use the multi-call decoder if you don't want to uncompress the whole stream.
Definition at line 733 of file xz_dec_stream.c.
 {
     size_t in_start;
     size_t out_start;
     enum xz_ret ret;
     if (DEC_IS_SINGLE(s->mode))
         xz_dec_reset(s);
     in_start = b->in_pos;
     out_start = b->out_pos;
     ret = dec_main(s, b);
     if (DEC_IS_SINGLE(s->mode)) {
         if (ret == XZ_OK)
             ret = b->in_pos == b->in_size
                     ? XZ_DATA_ERROR : XZ_BUF_ERROR;
         if (ret != XZ_STREAM_END) {
             b->in_pos = in_start;
             b->out_pos = out_start;
         }
     } else if (ret == XZ_OK && in_start == b->in_pos
             && out_start == b->out_pos) {
         if (s->allow_buf_error)
             ret = XZ_BUF_ERROR;
         s->allow_buf_error = true;
     } else {
         s->allow_buf_error = false;
     }
     return ret;
 }
References DEC_IS_SINGLE, dec_main(), xz_buf::in_pos, xz_buf::in_size, xz_buf::out_pos, s, XZ_BUF_ERROR, XZ_DATA_ERROR, xz_dec_reset(), XZ_OK, and XZ_STREAM_END.
Referenced by IF_DESKTOP().
Variable Documentation
check_sizes
const uint8_t check_sizes[16] static
Initial value:
= {
    0,
    4, 4, 4,
    8, 8, 8,
    16, 16, 16,
    32, 32, 32,
    64, 64, 64
}
Definition at line 141 of file xz_dec_stream.c.
Referenced by check_skip().