Fennix Userspace: Userspace/apps/base/bash/support/printenv.c File Reference
printenv.c File Reference
#include "bashansi.h"
#include <stdio.h>
Functions
int main (int argc, char **argv)
Variables
char ** environ
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 37 of file printenv.c.
 {
   register char **envp, *eval;
   int len;
   argv++;
   argc--;
   /* printenv */
   if (argc == 0)
     {
       for (envp = environ; *envp; envp++)
     puts (*envp);
       exit (0);
     }
   /* printenv varname */
   len = strlen (*argv);
   for (envp = environ; *envp; envp++)
     {
       if (**argv == **envp && strncmp (*envp, *argv, len) == 0)
     {
       eval = *envp + len;
       /* If the environment variable doesn't have an `=', ignore it. */
       if (*eval == '=')
         {
           puts (eval + 1);
           exit (0);
         }
     }
     }
   exit (1);
 }
References argc, argv, environ, eval(), exit(), puts(), strlen(), and strncmp().
Variable Documentation
environ
char** environ extern
Definition at line 42 of file lib.c.
Referenced by awk_main(), env_main(), evalcommand(), hush_main(), init(), main(), printenv_main(), re_execute_shell(), and readline_initialize_everything().