Fennix Userspace: Userspace/apps/base/busybox/networking/whois.c File Reference
whois.c File Reference
#include "libbb.h"
Enumerations
enum { OPT_i = (1 << 0) }
Functions
static char * query (const char *host, int port, const char *domain)
static void recursive_query (const char *host, int port, const char *domain)
int whois_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_i
Definition at line 31 of file whois.c.
      {
     OPT_i = (1 << 0),
 };
Function Documentation
query()
static char* query (const char * host, int port, const char * domain) static
Definition at line 35 of file whois.c.
 {
     int fd;
     FILE *fp;
     bool success;
     char *redir = NULL;
     const char *pfx = "";
     /* some .io domains reported to have very long strings in whois
      * responses, 1k was not enough:
      */
     char linebuf[2 * 1024];
     char *buf = NULL;
     unsigned bufpos = 0;
  again:
     printf("[Querying %s:%d '%s%s']\n", host, port, pfx, domain);
     fd = create_and_connect_stream_or_die(host, port);
     fdprintf(fd, "%s%s\r\n", pfx, domain);
     fp = xfdopen_for_read(fd);
     success = 0;
     while (bufpos < 32*1024 /* paranoia */
      && fgets(linebuf, sizeof(linebuf)-1, fp)
     ) {
         unsigned len;
         len = strcspn(linebuf, "\r\n");
         linebuf[len++] = '\n';
         linebuf[len] = '\0';
         buf = xrealloc(buf, bufpos + len + 1);
         memcpy(buf + bufpos, linebuf, len);
         bufpos += len;
         buf[bufpos] = '\0';
         if (!redir || !success) {
             trim(linebuf);
             str_tolower(linebuf);
             if (!success) {
                 success = is_prefixed_with(linebuf, "domain:")
                        || is_prefixed_with(linebuf, "domain name:");
             }
             else if (!redir) {
                 char *p = is_prefixed_with(linebuf, "whois server:");
                 if (!p)
                     p = is_prefixed_with(linebuf, "whois:");
                 if (p)
                     redir = xstrdup(skip_whitespace(p));
             }
         }
     }
     fclose(fp); /* closes fd too */
     if (!success && !pfx[0]) {
         /*
          * Looking at /etc/jwhois.conf, some whois servers use
          * "domain = DOMAIN", "DOMAIN ID <DOMAIN>"
          * and "domain=DOMAIN_WITHOUT_LAST_COMPONENT"
          * formats, but those are rare.
          * (There are a few even more contrived ones.)
          * We are trying only "domain DOMAIN", the typical one.
          */
         pfx = "domain ";
         bufpos = 0;
         goto again;
     }
     /* Success */
     if (redir && strcmp(redir, host) == 0) {
         /* Redirect to self does not count */
         free(redir);
         redir = NULL;
     }
     if (!redir || (option_mask32 & OPT_i)) {
         /* Output saved text */
         printf("[%s]\n%s", host, buf ? buf : "");
     }
     free(buf);
     return redir;
 }
References buf, create_and_connect_stream_or_die(), domain, fclose(), fd, fdprintf, fgets, free, is_prefixed_with(), memcpy(), NULL, OPT_i, option_mask32, p, port, printf(), redir, skip_whitespace(), str_tolower(), strcmp, strcspn(), trim(), xfdopen_for_read(), xrealloc, and xstrdup().
Referenced by getnameinfo(), and recursive_query().
recursive_query()
static void recursive_query (const char * host, int port, const char * domain) static
Definition at line 115 of file whois.c.
 {
     char *free_me = NULL;
     char *redir;
  again:
     redir = query(host, port, domain);
     free(free_me);
     if (redir) {
         printf("[Redirected to %s]\n", redir);
         host = free_me = redir;
         port = 43;
         goto again;
     }
 }
References domain, free, NULL, port, printf(), query(), and redir.
Referenced by whois_main().
whois_main()
int whois_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 172 of file whois.c.
 {
     int port = 43;
     const char *host = "whois.iana.org";
     getopt32(argv, "^" "ih:p:+" "\0" "-1", &host, &port);
     argv += optind;
     do {
         recursive_query(host, port, *argv);
     }
     while (*++argv);
     return EXIT_SUCCESS;
 }
References argv, EXIT_SUCCESS, getopt32(), optind, port, and recursive_query().