Fennix Userspace: Userspace/musl/src/stdlib/fcvt.c File Reference
fcvt.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Macros
#define _GNU_SOURCE
Functions
char * fcvt (double x, int n, int *dp, int *sign)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file fcvt.c.
Function Documentation
fcvt()
char* fcvt (double x, int n, int * dp, int * sign)
Definition at line 6 of file fcvt.c.
 {
     char tmp[1500];
     int i, lz;
     if (n > 1400U) n = 1400;
     sprintf(tmp, "%.*f", n, x);
     i = (tmp[0] == '-');
     if (tmp[i] == '0') lz = strspn(tmp+i+2, "0");
     else lz = -(int)strcspn(tmp+i, ".");
     if (n<=lz) {
         *sign = i;
         *dp = 1;
         if (n>14U) n = 14;
         return "000000000000000"+14-n;
     }
     return ecvt(x, n-lz, dp, sign);
 }
References ecvt(), i, int, n, sprintf(), strcspn(), strspn(), and x.