Fennix: Userspace/musl/src/stdio/__toread.c File Reference
__toread.c File Reference
#include <stdio_impl.h>
Functions
int __toread (FILE *f)
hidden void __toread_needs_stdio_exit ()
Function Documentation
__toread()
int __toread (FILE * f)
Definition at line 3 of file __toread.c.
 {
     f->mode |= f->mode-1;
     if (f->wpos != f->wbase) f->write(f, 0, 0);
     f->wpos = f->wbase = f->wend = 0;
     if (f->flags & F_NORD) {
         f->flags |= F_ERR;
         return EOF;
     }
     f->rpos = f->rend = f->buf + f->buf_size;
     return (f->flags & F_EOF) ? EOF : 0;
 }
References EOF, f, F_EOF, F_ERR, and F_NORD.
Referenced by __uflow(), fread(), ungetc(), ungetwc(), and vfscanf().
__toread_needs_stdio_exit()
hidden void __toread_needs_stdio_exit ()
Definition at line 16 of file __toread.c.
 {
     __stdio_exit_needed();
 }
References __stdio_exit_needed().