Fennix Userspace: Userspace/musl/src/math/__expo2f.c File Reference
__expo2f.c File Reference
#include "libm.h"
Functions
float __expo2f (float x, float sign)
Variables
static const int k = 235
static const float kln2 = 0x1.45c778p+7f
Function Documentation
__expo2f()
float __expo2f (float x, float sign)
Definition at line 8 of file __expo2f.c.
 {
     float scale;
     /* note that k is odd and scale*scale overflows */
     SET_FLOAT_WORD(scale, (uint32_t)(0x7f + k/2) << 23);
     /* exp(x - k ln2) * 2**(k-1) */
     /* in directed rounding correct sign before rounding or overflow is important */
     return expf(x - kln2) * (sign * scale) * scale;
 }
References expf(), k, kln2, SET_FLOAT_WORD, and x.
Referenced by coshf(), and sinhf().
Variable Documentation
k
const int k = 235 static
Definition at line 4 of file __expo2f.c.
Referenced by __expo2f().
kln2
const float kln2 = 0x1.45c778p+7f static
Definition at line 5 of file __expo2f.c.
Referenced by __expo2f().