Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/am_map.c File Reference
am_map.c File Reference
#include <stdio.h>
#include "deh_main.h"
#include "z_zone.h"
#include "doomkeys.h"
#include "doomdef.h"
#include "st_stuff.h"
#include "p_local.h"
#include "w_wad.h"
#include "m_cheat.h"
#include "m_controls.h"
#include "m_misc.h"
#include "i_system.h"
#include "v_video.h"
#include "doomstat.h"
#include "r_state.h"
#include "dstrings.h"
#include "am_map.h"
Data Structures
struct fpoint_t
struct fline_t
struct mpoint_t
struct mline_t
struct islope_t
Macros
#define REDS (256-5*16)
#define REDRANGE 16
#define BLUES (256-4*16+8)
#define BLUERANGE 8
#define GREENS (7*16)
#define GREENRANGE 16
#define GRAYS (6*16)
#define GRAYSRANGE 16
#define BROWNS (4*16)
#define BROWNRANGE 16
#define YELLOWS (256-32+7)
#define YELLOWRANGE 1
#define BLACK 0
#define WHITE (256-47)
#define BACKGROUND BLACK
#define YOURCOLORS WHITE
#define YOURRANGE 0
#define WALLCOLORS REDS
#define WALLRANGE REDRANGE
#define TSWALLCOLORS GRAYS
#define TSWALLRANGE GRAYSRANGE
#define FDWALLCOLORS BROWNS
#define FDWALLRANGE BROWNRANGE
#define CDWALLCOLORS YELLOWS
#define CDWALLRANGE YELLOWRANGE
#define THINGCOLORS GREENS
#define THINGRANGE GREENRANGE
#define SECRETWALLCOLORS WALLCOLORS
#define SECRETWALLRANGE WALLRANGE
#define GRIDCOLORS (GRAYS + GRAYSRANGE/2)
#define GRIDRANGE 0
#define XHAIRCOLORS GRAYS
#define AM_NUMMARKPOINTS 10
#define INITSCALEMTOF (.2*FRACUNIT)
#define F_PANINC 4
#define M_ZOOMIN ((int) (1.02*FRACUNIT))
#define M_ZOOMOUT ((int) (FRACUNIT/1.02))
#define FTOM(x) FixedMul(((x)<<16),scale_ftom)
#define MTOF(x) (FixedMul((x),scale_mtof)>>16)
#define CXMTOF(x) (f_x + MTOF((x)-m_x))
#define CYMTOF(y) (f_y + (f_h - MTOF((y)-m_y)))
#define LINE_NEVERSEE ML_DONTDRAW
#define R ((8*PLAYERRADIUS)/7)
#define R ((8*PLAYERRADIUS)/7)
#define R (FRACUNIT)
#define R (FRACUNIT)
#define DOOUTCODE(oc, mx, my)
#define PUTDOT(xx, yy, cc) fb[(yy)*f_w+(xx)]=(cc)
Functions
void AM_getIslope (mline_t *ml, islope_t *is)
void AM_activateNewScale (void)
void AM_saveScaleAndLoc (void)
void AM_restoreScaleAndLoc (void)
void AM_addMark (void)
void AM_findMinMaxBoundaries (void)
void AM_changeWindowLoc (void)
void AM_initVariables (void)
void AM_loadPics (void)
void AM_unloadPics (void)
void AM_clearMarks (void)
void AM_LevelInit (void)
void AM_Stop (void)
void AM_Start (void)
void AM_minOutWindowScale (void)
void AM_maxOutWindowScale (void)
boolean AM_Responder (event_t *ev)
void AM_changeWindowScale (void)
void AM_doFollowPlayer (void)
void AM_updateLightLev (void)
void AM_Ticker (void)
void AM_clearFB (int color)
boolean AM_clipMline (mline_t *ml, fline_t *fl)
void AM_drawFline (fline_t *fl, int color)
void AM_drawMline (mline_t *ml, int color)
void AM_drawGrid (int color)
void AM_drawWalls (void)
void AM_rotate (fixed_t *x, fixed_t *y, angle_t a)
void AM_drawLineCharacter (mline_t *lineguy, int lineguylines, fixed_t scale, angle_t angle, int color, fixed_t x, fixed_t y)
void AM_drawPlayers (void)
void AM_drawThings (int colors, int colorrange)
void AM_drawMarks (void)
void AM_drawCrosshair (int color)
void AM_Drawer (void)
Variables
mline_t player_arrow []
mline_t cheat_player_arrow []
mline_t triangle_guy []
mline_t thintriangle_guy []
static int cheating = 0
static int grid = 0
static int leveljuststarted = 1
boolean automapactive = false
static int finit_width = SCREENWIDTH
static int finit_height = SCREENHEIGHT - 32
static int f_x
static int f_y
static int f_w
static int f_h
static int lightlev
static byte * fb
static int amclock
static mpoint_t m_paninc
static fixed_t mtof_zoommul
static fixed_t ftom_zoommul
static fixed_t m_x
static fixed_t m_y
static fixed_t m_x2
static fixed_t m_y2
static fixed_t m_w
static fixed_t m_h
static fixed_t min_x
static fixed_t min_y
static fixed_t max_x
static fixed_t max_y
static fixed_t max_w
static fixed_t max_h
static fixed_t min_w
static fixed_t min_h
static fixed_t min_scale_mtof
static fixed_t max_scale_mtof
static fixed_t old_m_w
static fixed_t old_m_h
static fixed_t old_m_x
static fixed_t old_m_y
static mpoint_t f_oldloc
static fixed_t scale_mtof = (fixed_t)INITSCALEMTOF
static fixed_t scale_ftom
static player_t * plr
static patch_t * marknums [10]
static mpoint_t markpoints [AM_NUMMARKPOINTS]
static int markpointnum = 0
static int followplayer = 1
cheatseq_t cheat_amap = CHEAT("iddt", 0)
static boolean stopped = true
Data Structure Documentation
fpoint_t
struct fpoint_t
Definition at line 111 of file am_map.c.
Data Fields
int x
int y
fline_t
struct fline_t
Definition at line 116 of file am_map.c.
Data Fields
fpoint_t a
fpoint_t b
mpoint_t
struct mpoint_t
Definition at line 121 of file am_map.c.
Data Fields
fixed_t x
fixed_t y
mline_t
struct mline_t
Definition at line 126 of file am_map.c.
Data Fields
mpoint_t a
mpoint_t b
islope_t
struct islope_t
Definition at line 131 of file am_map.c.
Data Fields
fixed_t islp
fixed_t slp
Macro Definition Documentation
AM_NUMMARKPOINTS
#define AM_NUMMARKPOINTS 10
Definition at line 87 of file am_map.c.
BACKGROUND
#define BACKGROUND BLACK
Definition at line 66 of file am_map.c.
BLACK
#define BLACK 0
Definition at line 62 of file am_map.c.
BLUERANGE
#define BLUERANGE 8
Definition at line 53 of file am_map.c.
BLUES
#define BLUES (256-4*16+8)
Definition at line 52 of file am_map.c.
BROWNRANGE
#define BROWNRANGE 16
Definition at line 59 of file am_map.c.
BROWNS
#define BROWNS (4*16)
Definition at line 58 of file am_map.c.
CDWALLCOLORS
#define CDWALLCOLORS YELLOWS
Definition at line 75 of file am_map.c.
CDWALLRANGE
#define CDWALLRANGE YELLOWRANGE
Definition at line 76 of file am_map.c.
CXMTOF
#define CXMTOF (x) (f_x + MTOF((x)-m_x))
Definition at line 105 of file am_map.c.
CYMTOF
#define CYMTOF (y) (f_y + (f_h - MTOF((y)-m_y)))
Definition at line 106 of file am_map.c.
DOOUTCODE
#define DOOUTCODE (oc, mx, my)
Value:
    (oc) = 0; \
    if ((my) < 0) (oc) |= TOP; \
    else if ((my) >= f_h) (oc) |= BOTTOM; \
    if ((mx) < 0) (oc) |= LEFT; \
    else if ((mx) >= f_w) (oc) |= RIGHT;
F_PANINC
#define F_PANINC 4
Definition at line 93 of file am_map.c.
FDWALLCOLORS
#define FDWALLCOLORS BROWNS
Definition at line 73 of file am_map.c.
FDWALLRANGE
#define FDWALLRANGE BROWNRANGE
Definition at line 74 of file am_map.c.
FTOM
#define FTOM (x) FixedMul(((x)<<16),scale_ftom)
Definition at line 102 of file am_map.c.
GRAYS
#define GRAYS (6*16)
Definition at line 56 of file am_map.c.
GRAYSRANGE
#define GRAYSRANGE 16
Definition at line 57 of file am_map.c.
GREENRANGE
#define GREENRANGE 16
Definition at line 55 of file am_map.c.
GREENS
#define GREENS (7*16)
Definition at line 54 of file am_map.c.
GRIDCOLORS
#define GRIDCOLORS (GRAYS + GRAYSRANGE/2)
Definition at line 81 of file am_map.c.
GRIDRANGE
#define GRIDRANGE 0
Definition at line 82 of file am_map.c.
INITSCALEMTOF
#define INITSCALEMTOF (.2*FRACUNIT)
Definition at line 90 of file am_map.c.
LINE_NEVERSEE
#define LINE_NEVERSEE ML_DONTDRAW
Definition at line 109 of file am_map.c.
M_ZOOMIN
#define M_ZOOMIN ((int) (1.02*FRACUNIT))
Definition at line 96 of file am_map.c.
M_ZOOMOUT
#define M_ZOOMOUT ((int) (FRACUNIT/1.02))
Definition at line 99 of file am_map.c.
MTOF
#define MTOF (x) (FixedMul((x),scale_mtof)>>16)
Definition at line 103 of file am_map.c.
PUTDOT
#define PUTDOT (xx, yy, cc) fb[(yy)*f_w+(xx)]=(cc)
R [1/4]
#define R ((8*PLAYERRADIUS)/7)
Definition at line 184 of file am_map.c.
R [2/4]
#define R ((8*PLAYERRADIUS)/7)
Definition at line 184 of file am_map.c.
R [3/4]
#define R (FRACUNIT)
Definition at line 184 of file am_map.c.
R [4/4]
#define R (FRACUNIT)
Definition at line 184 of file am_map.c.
REDRANGE
#define REDRANGE 16
Definition at line 51 of file am_map.c.
REDS
#define REDS (256-5*16)
Definition at line 50 of file am_map.c.
SECRETWALLCOLORS
#define SECRETWALLCOLORS WALLCOLORS
Definition at line 79 of file am_map.c.
SECRETWALLRANGE
#define SECRETWALLRANGE WALLRANGE
Definition at line 80 of file am_map.c.
THINGCOLORS
#define THINGCOLORS GREENS
Definition at line 77 of file am_map.c.
THINGRANGE
#define THINGRANGE GREENRANGE
Definition at line 78 of file am_map.c.
TSWALLCOLORS
#define TSWALLCOLORS GRAYS
Definition at line 71 of file am_map.c.
TSWALLRANGE
#define TSWALLRANGE GRAYSRANGE
Definition at line 72 of file am_map.c.
WALLCOLORS
#define WALLCOLORS REDS
Definition at line 69 of file am_map.c.
WALLRANGE
#define WALLRANGE REDRANGE
Definition at line 70 of file am_map.c.
WHITE
#define WHITE (256-47)
Definition at line 63 of file am_map.c.
XHAIRCOLORS
#define XHAIRCOLORS GRAYS
Definition at line 83 of file am_map.c.
YELLOWRANGE
#define YELLOWRANGE 1
Definition at line 61 of file am_map.c.
YELLOWS
#define YELLOWS (256-32+7)
Definition at line 60 of file am_map.c.
YOURCOLORS
#define YOURCOLORS WHITE
Definition at line 67 of file am_map.c.
YOURRANGE
#define YOURRANGE 0
Definition at line 68 of file am_map.c.
Function Documentation
AM_activateNewScale()
void AM_activateNewScale (void)
Definition at line 293 of file am_map.c.
 {
     m_x += m_w/2;
     m_y += m_h/2;
     m_w = FTOM(f_w);
     m_h = FTOM(f_h);
     m_x -= m_w/2;
     m_y -= m_h/2;
     m_x2 = m_x + m_w;
     m_y2 = m_y + m_h;
 }
References f_h, f_w, FTOM, m_h, m_w, m_x, m_x2, m_y, and m_y2.
Referenced by AM_changeWindowScale(), AM_maxOutWindowScale(), and AM_minOutWindowScale().
AM_addMark()
void AM_addMark (void)
Definition at line 343 of file am_map.c.
 {
     markpoints[markpointnum].x = m_x + m_w/2;
     markpoints[markpointnum].y = m_y + m_h/2;
     markpointnum = (markpointnum + 1) % AM_NUMMARKPOINTS;
 }
References AM_NUMMARKPOINTS, m_h, m_w, m_x, m_y, markpointnum, markpoints, mpoint_t::x, and mpoint_t::y.
Referenced by AM_Responder().
AM_changeWindowLoc()
void AM_changeWindowLoc (void)
Definition at line 395 of file am_map.c.
 {
     if (m_paninc.x || m_paninc.y)
     {
     followplayer = 0;
     f_oldloc.x = INT_MAX;
     }
     m_x += m_paninc.x;
     m_y += m_paninc.y;
     if (m_x + m_w/2 > max_x)
     m_x = max_x - m_w/2;
     else if (m_x + m_w/2 < min_x)
     m_x = min_x - m_w/2;
     if (m_y + m_h/2 > max_y)
     m_y = max_y - m_h/2;
     else if (m_y + m_h/2 < min_y)
     m_y = min_y - m_h/2;
     m_x2 = m_x + m_w;
     m_y2 = m_y + m_h;
 }
References f_oldloc, followplayer, INT_MAX, m_h, m_paninc, m_w, m_x, m_x2, m_y, m_y2, max_x, max_y, min_x, min_y, mpoint_t::x, and mpoint_t::y.
Referenced by AM_initVariables(), and AM_Ticker().
AM_changeWindowScale()
void AM_changeWindowScale (void)
Definition at line 742 of file am_map.c.
 {
     // Change the scaling multipliers
     scale_mtof = FixedMul(scale_mtof, mtof_zoommul);
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
     if (scale_mtof < min_scale_mtof)
     AM_minOutWindowScale();
     else if (scale_mtof > max_scale_mtof)
     AM_maxOutWindowScale();
     else
     AM_activateNewScale();
 }
References AM_activateNewScale(), AM_maxOutWindowScale(), AM_minOutWindowScale(), FixedDiv(), FixedMul(), FRACUNIT, max_scale_mtof, min_scale_mtof, mtof_zoommul, scale_ftom, and scale_mtof.
Referenced by AM_Ticker().
AM_clearFB()
void AM_clearFB (int color)
Definition at line 834 of file am_map.c.
 {
     memset(fb, color, f_w*f_h);
 }
References f_h, f_w, fb, and memset.
Referenced by AM_Drawer().
AM_clearMarks()
void AM_clearMarks (void)
Definition at line 505 of file am_map.c.
 {
     int i;
     for (i=0;i<AM_NUMMARKPOINTS;i++)
     markpoints[i].x = -1; // means empty
     markpointnum = 0;
 }
References AM_NUMMARKPOINTS, i, markpointnum, markpoints, and x.
Referenced by AM_LevelInit(), and AM_Responder().
AM_clipMline()
boolean AM_clipMline (mline_t * ml, fline_t * fl)
Definition at line 848 of file am_map.c.
 {
     enum
     {
     LEFT    =1,
     RIGHT   =2,
     BOTTOM  =4,
     TOP =8
     };
     register int    outcode1 = 0;
     register int    outcode2 = 0;
     register int    outside;
     fpoint_t    tmp;
     int     dx;
     int     dy;
 #define DOOUTCODE(oc, mx, my) \
     (oc) = 0; \
     if ((my) < 0) (oc) |= TOP; \
     else if ((my) >= f_h) (oc) |= BOTTOM; \
     if ((mx) < 0) (oc) |= LEFT; \
     else if ((mx) >= f_w) (oc) |= RIGHT;
     // do trivial rejects and outcodes
     if (ml->a.y > m_y2)
     outcode1 = TOP;
     else if (ml->a.y < m_y)
     outcode1 = BOTTOM;
     if (ml->b.y > m_y2)
     outcode2 = TOP;
     else if (ml->b.y < m_y)
     outcode2 = BOTTOM;
     if (outcode1 & outcode2)
     return false; // trivially outside
     if (ml->a.x < m_x)
     outcode1 |= LEFT;
     else if (ml->a.x > m_x2)
     outcode1 |= RIGHT;
     if (ml->b.x < m_x)
     outcode2 |= LEFT;
     else if (ml->b.x > m_x2)
     outcode2 |= RIGHT;
     if (outcode1 & outcode2)
     return false; // trivially outside
     // transform to frame-buffer coordinates.
     fl->a.x = CXMTOF(ml->a.x);
     fl->a.y = CYMTOF(ml->a.y);
     fl->b.x = CXMTOF(ml->b.x);
     fl->b.y = CYMTOF(ml->b.y);
     DOOUTCODE(outcode1, fl->a.x, fl->a.y);
     DOOUTCODE(outcode2, fl->b.x, fl->b.y);
     if (outcode1 & outcode2)
     return false;
     while (outcode1 | outcode2)
     {
     // may be partially inside box
     // find an outside point
     if (outcode1)
         outside = outcode1;
     else
         outside = outcode2;
     // clip to each side
     if (outside & TOP)
     {
         dy = fl->a.y - fl->b.y;
         dx = fl->b.x - fl->a.x;
         tmp.x = fl->a.x + (dx*(fl->a.y))/dy;
         tmp.y = 0;
     }
     else if (outside & BOTTOM)
     {
         dy = fl->a.y - fl->b.y;
         dx = fl->b.x - fl->a.x;
         tmp.x = fl->a.x + (dx*(fl->a.y-f_h))/dy;
         tmp.y = f_h-1;
     }
     else if (outside & RIGHT)
     {
         dy = fl->b.y - fl->a.y;
         dx = fl->b.x - fl->a.x;
         tmp.y = fl->a.y + (dy*(f_w-1 - fl->a.x))/dx;
         tmp.x = f_w-1;
     }
     else if (outside & LEFT)
     {
         dy = fl->b.y - fl->a.y;
         dx = fl->b.x - fl->a.x;
         tmp.y = fl->a.y + (dy*(-fl->a.x))/dx;
         tmp.x = 0;
     }
         else
         {
             tmp.x = 0;
             tmp.y = 0;
         }
     if (outside == outcode1)
     {
         fl->a = tmp;
         DOOUTCODE(outcode1, fl->a.x, fl->a.y);
     }
     else
     {
         fl->b = tmp;
         DOOUTCODE(outcode2, fl->b.x, fl->b.y);
     }
     if (outcode1 & outcode2)
         return false; // trivially outside
     }
     return true;
 }
References fline_t::a, mline_t::a, fline_t::b, mline_t::b, CXMTOF, CYMTOF, DOOUTCODE, f_h, f_w, m_x, m_x2, m_y, m_y2, fpoint_t::x, mpoint_t::x, fpoint_t::y, and mpoint_t::y.
Referenced by AM_drawMline().
AM_doFollowPlayer()
void AM_doFollowPlayer (void)
Definition at line 761 of file am_map.c.
 {
     if (f_oldloc.x != plr->mo->x || f_oldloc.y != plr->mo->y)
     {
     m_x = FTOM(MTOF(plr->mo->x)) - m_w/2;
     m_y = FTOM(MTOF(plr->mo->y)) - m_h/2;
     m_x2 = m_x + m_w;
     m_y2 = m_y + m_h;
     f_oldloc.x = plr->mo->x;
     f_oldloc.y = plr->mo->y;
     //  m_x = FTOM(MTOF(plr->mo->x - m_w/2));
     //  m_y = FTOM(MTOF(plr->mo->y - m_h/2));
     //  m_x = plr->mo->x - m_w/2;
     //  m_y = plr->mo->y - m_h/2;
     }
 }
References f_oldloc, FTOM, m_h, m_w, m_x, m_x2, m_y, m_y2, player_s::mo, MTOF, plr, mpoint_t::x, mobj_s::x, mpoint_t::y, and mobj_s::y.
Referenced by AM_Ticker().
AM_drawCrosshair()
void AM_drawCrosshair (int color)
Definition at line 1332 of file am_map.c.
 {
     fb[(f_w*(f_h+1))/2] = color; // single point for now
 }
References f_h, f_w, and fb.
Referenced by AM_Drawer().
AM_Drawer()
void AM_Drawer (void)
Definition at line 1338 of file am_map.c.
 {
     if (!automapactive) return;
     AM_clearFB(BACKGROUND);
     if (grid)
     AM_drawGrid(GRIDCOLORS);
     AM_drawWalls();
     AM_drawPlayers();
     if (cheating==2)
     AM_drawThings(THINGCOLORS, THINGRANGE);
     AM_drawCrosshair(XHAIRCOLORS);
     AM_drawMarks();
     V_MarkRect(f_x, f_y, f_w, f_h);
 }
References AM_clearFB(), AM_drawCrosshair(), AM_drawGrid(), AM_drawMarks(), AM_drawPlayers(), AM_drawThings(), AM_drawWalls(), automapactive, BACKGROUND, cheating, f_h, f_w, f_x, f_y, grid, GRIDCOLORS, THINGCOLORS, THINGRANGE, V_MarkRect(), and XHAIRCOLORS.
Referenced by D_Display().
AM_drawFline()
void AM_drawFline (fline_t * fl, int color)
Definition at line 984 of file am_map.c.
 {
     register int x;
     register int y;
     register int dx;
     register int dy;
     register int sx;
     register int sy;
     register int ax;
     register int ay;
     register int d;
     static int fuck = 0;
     // For debugging only
     if (      fl->a.x < 0 || fl->a.x >= f_w
        || fl->a.y < 0 || fl->a.y >= f_h
        || fl->b.x < 0 || fl->b.x >= f_w
        || fl->b.y < 0 || fl->b.y >= f_h)
     {
         DEH_fprintf(stderr, "fuck %d \r", fuck++);
     return;
     }
 #define PUTDOT(xx,yy,cc) fb[(yy)*f_w+(xx)]=(cc)
     dx = fl->b.x - fl->a.x;
     ax = 2 * (dx<0 ? -dx : dx);
     sx = dx<0 ? -1 : 1;
     dy = fl->b.y - fl->a.y;
     ay = 2 * (dy<0 ? -dy : dy);
     sy = dy<0 ? -1 : 1;
     x = fl->a.x;
     y = fl->a.y;
     if (ax > ay)
     {
     d = ay - ax/2;
     while (1)
     {
         PUTDOT(x,y,color);
         if (x == fl->b.x) return;
         if (d>=0)
         {
         y += sy;
         d -= ax;
         }
         x += sx;
         d += ay;
     }
     }
     else
     {
     d = ax - ay/2;
     while (1)
     {
         PUTDOT(x, y, color);
         if (y == fl->b.y) return;
         if (d >= 0)
         {
         x += sx;
         d -= ay;
         }
         y += sy;
         d += ax;
     }
     }
 }
References fline_t::a, fline_t::b, DEH_fprintf, f_h, f_w, PUTDOT, stderr, fpoint_t::x, x, fpoint_t::y, and y.
Referenced by AM_drawMline().
AM_drawGrid()
void AM_drawGrid (int color)
Definition at line 1077 of file am_map.c.
 {
     fixed_t x, y;
     fixed_t start, end;
     mline_t ml;
     // Figure out start of vertical gridlines
     start = m_x;
     if ((start-bmaporgx)%(MAPBLOCKUNITS<<FRACBITS))
     start += (MAPBLOCKUNITS<<FRACBITS)
         - ((start-bmaporgx)%(MAPBLOCKUNITS<<FRACBITS));
     end = m_x + m_w;
     // draw vertical gridlines
     ml.a.y = m_y;
     ml.b.y = m_y+m_h;
     for (x=start; x<end; x+=(MAPBLOCKUNITS<<FRACBITS))
     {
     ml.a.x = x;
     ml.b.x = x;
     AM_drawMline(&ml, color);
     }
     // Figure out start of horizontal gridlines
     start = m_y;
     if ((start-bmaporgy)%(MAPBLOCKUNITS<<FRACBITS))
     start += (MAPBLOCKUNITS<<FRACBITS)
         - ((start-bmaporgy)%(MAPBLOCKUNITS<<FRACBITS));
     end = m_y + m_h;
     // draw horizontal gridlines
     ml.a.x = m_x;
     ml.b.x = m_x + m_w;
     for (y=start; y<end; y+=(MAPBLOCKUNITS<<FRACBITS))
     {
     ml.a.y = y;
     ml.b.y = y;
     AM_drawMline(&ml, color);
     }
 }
References mline_t::a, AM_drawMline(), mline_t::b, bmaporgx, bmaporgy, FRACBITS, m_h, m_w, m_x, m_y, MAPBLOCKUNITS, mpoint_t::x, x, mpoint_t::y, and y.
Referenced by AM_Drawer().
AM_drawLineCharacter()
void AM_drawLineCharacter (mline_t * lineguy, int lineguylines, fixed_t scale, angle_t angle, int color, fixed_t x, fixed_t y)
Definition at line 1198 of file am_map.c.
 {
     int     i;
     mline_t l;
     for (i=0;i<lineguylines;i++)
     {
     l.a.x = lineguy[i].a.x;
     l.a.y = lineguy[i].a.y;
     if (scale)
     {
         l.a.x = FixedMul(scale, l.a.x);
         l.a.y = FixedMul(scale, l.a.y);
     }
     if (angle)
         AM_rotate(&l.a.x, &l.a.y, angle);
     l.a.x += x;
     l.a.y += y;
     l.b.x = lineguy[i].b.x;
     l.b.y = lineguy[i].b.y;
     if (scale)
     {
         l.b.x = FixedMul(scale, l.b.x);
         l.b.y = FixedMul(scale, l.b.y);
     }
     if (angle)
         AM_rotate(&l.b.x, &l.b.y, angle);
     l.b.x += x;
     l.b.y += y;
     AM_drawMline(&l, color);
     }
 }
References mline_t::a, AM_drawMline(), AM_rotate(), mline_t::b, FixedMul(), i, mpoint_t::x, x, mpoint_t::y, and y.
Referenced by AM_drawPlayers(), and AM_drawThings().
AM_drawMarks()
void AM_drawMarks (void)
Definition at line 1311 of file am_map.c.
 {
     int i, fx, fy, w, h;
     for (i=0;i<AM_NUMMARKPOINTS;i++)
     {
     if (markpoints[i].x != -1)
     {
         //      w = SHORT(marknums[i]->width);
         //      h = SHORT(marknums[i]->height);
         w = 5; // because something's wrong with the wad, i guess
         h = 6; // because something's wrong with the wad, i guess
         fx = CXMTOF(markpoints[i].x);
         fy = CYMTOF(markpoints[i].y);
         if (fx >= f_x && fx <= f_w - w && fy >= f_y && fy <= f_h - h)
         V_DrawPatch(fx, fy, marknums[i]);
     }
     }
 }
References AM_NUMMARKPOINTS, CXMTOF, CYMTOF, f_h, f_x, f_y, i, marknums, markpoints, V_DrawPatch(), x, and y.
Referenced by AM_Drawer().
AM_drawMline()
void AM_drawMline (mline_t * ml, int color)
Definition at line 1062 of file am_map.c.
 {
     static fline_t fl;
     if (AM_clipMline(ml, &fl))
     AM_drawFline(&fl, color); // draws it on frame buffer using fb coords
 }
References AM_clipMline(), and AM_drawFline().
Referenced by AM_drawGrid(), AM_drawLineCharacter(), and AM_drawWalls().
AM_drawPlayers()
void AM_drawPlayers (void)
Definition at line 1246 of file am_map.c.
 {
     int     i;
     player_t*   p;
     static int  their_colors[] = { GREENS, GRAYS, BROWNS, REDS };
     int     their_color = -1;
     int     color;
     if (!netgame)
     {
     if (cheating)
         AM_drawLineCharacter
         (cheat_player_arrow, arrlen(cheat_player_arrow), 0,
          plr->mo->angle, WHITE, plr->mo->x, plr->mo->y);
     else
         AM_drawLineCharacter
         (player_arrow, arrlen(player_arrow), 0, plr->mo->angle,
          WHITE, plr->mo->x, plr->mo->y);
     return;
     }
     for (i=0;i<MAXPLAYERS;i++)
     {
     their_color++;
     p = &players[i];
     if ( (deathmatch && !singledemo) && p != plr)
         continue;
     if (!playeringame[i])
         continue;
     if (p->powers[pw_invisibility])
         color = 246; // *close* to black
     else
         color = their_colors[their_color];
     AM_drawLineCharacter
         (player_arrow, arrlen(player_arrow), 0, p->mo->angle,
          color, p->mo->x, p->mo->y);
     }
 }
References AM_drawLineCharacter(), mobj_s::angle, arrlen, BROWNS, cheat_player_arrow, cheating, deathmatch, GRAYS, GREENS, i, MAXPLAYERS, player_s::mo, netgame, p, player_arrow, playeringame, players, plr, pw_invisibility, REDS, singledemo, WHITE, mobj_s::x, and mobj_s::y.
Referenced by AM_Drawer().
AM_drawThings()
void AM_drawThings (int colors, int colorrange)
Definition at line 1291 of file am_map.c.
 {
     int     i;
     mobj_t* t;
     for (i=0;i<numsectors;i++)
     {
     t = sectors[i].thinglist;
     while (t)
     {
         AM_drawLineCharacter
         (thintriangle_guy, arrlen(thintriangle_guy),
          16<<FRACBITS, t->angle, colors+lightlev, t->x, t->y);
         t = t->snext;
     }
     }
 }
References AM_drawLineCharacter(), mobj_s::angle, arrlen, colors, FRACBITS, i, lightlev, numsectors, sectors, mobj_s::snext, sector_t::thinglist, thintriangle_guy, mobj_s::x, and mobj_s::y.
Referenced by AM_Drawer().
AM_drawWalls()
void AM_drawWalls (void)
Definition at line 1123 of file am_map.c.
 {
     int i;
     static mline_t l;
     for (i=0;i<numlines;i++)
     {
     l.a.x = lines[i].v1->x;
     l.a.y = lines[i].v1->y;
     l.b.x = lines[i].v2->x;
     l.b.y = lines[i].v2->y;
     if (cheating || (lines[i].flags & ML_MAPPED))
     {
         if ((lines[i].flags & LINE_NEVERSEE) && !cheating)
         continue;
         if (!lines[i].backsector)
         {
         AM_drawMline(&l, WALLCOLORS+lightlev);
         }
         else
         {
         if (lines[i].special == 39)
         { // teleporters
             AM_drawMline(&l, WALLCOLORS+WALLRANGE/2);
         }
         else if (lines[i].flags & ML_SECRET) // secret door
         {
             if (cheating) AM_drawMline(&l, SECRETWALLCOLORS + lightlev);
             else AM_drawMline(&l, WALLCOLORS+lightlev);
         }
         else if (lines[i].backsector->floorheight
                != lines[i].frontsector->floorheight) {
             AM_drawMline(&l, FDWALLCOLORS + lightlev); // floor level change
         }
         else if (lines[i].backsector->ceilingheight
                != lines[i].frontsector->ceilingheight) {
             AM_drawMline(&l, CDWALLCOLORS+lightlev); // ceiling level change
         }
         else if (cheating) {
             AM_drawMline(&l, TSWALLCOLORS+lightlev);
         }
         }
     }
     else if (plr->powers[pw_allmap])
     {
         if (!(lines[i].flags & LINE_NEVERSEE)) AM_drawMline(&l, GRAYS+3);
     }
     }
 }
References mline_t::a, AM_drawMline(), mline_t::b, backsector, CDWALLCOLORS, sector_t::ceilingheight, cheating, FDWALLCOLORS, mlibc::flags, sector_t::floorheight, line_s::frontsector, GRAYS, i, lightlev, LINE_NEVERSEE, lines, ML_MAPPED, ML_SECRET, numlines, plr, player_s::powers, pw_allmap, SECRETWALLCOLORS, TSWALLCOLORS, line_s::v1, line_s::v2, WALLCOLORS, WALLRANGE, mpoint_t::x, vertex_t::x, mpoint_t::y, and vertex_t::y.
Referenced by AM_Drawer().
AM_findMinMaxBoundaries()
void AM_findMinMaxBoundaries (void)
Definition at line 355 of file am_map.c.
 {
     int i;
     fixed_t a;
     fixed_t b;
     min_x = min_y =  INT_MAX;
     max_x = max_y = -INT_MAX;
     for (i=0;i<numvertexes;i++)
     {
     if (vertexes[i].x < min_x)
         min_x = vertexes[i].x;
     else if (vertexes[i].x > max_x)
         max_x = vertexes[i].x;
     if (vertexes[i].y < min_y)
         min_y = vertexes[i].y;
     else if (vertexes[i].y > max_y)
         max_y = vertexes[i].y;
     }
     max_w = max_x - min_x;
     max_h = max_y - min_y;
     min_w = 2*PLAYERRADIUS; // const? never changed?
     min_h = 2*PLAYERRADIUS;
     a = FixedDiv(f_w<<FRACBITS, max_w);
     b = FixedDiv(f_h<<FRACBITS, max_h);
     min_scale_mtof = a < b ? a : b;
     max_scale_mtof = FixedDiv(f_h<<FRACBITS, 2*PLAYERRADIUS);
 }
References b, f_h, f_w, FixedDiv(), FRACBITS, i, INT_MAX, max_h, max_scale_mtof, max_w, max_x, max_y, min_h, min_scale_mtof, min_w, min_x, min_y, numvertexes, PLAYERRADIUS, vertexes, vertex_t::x, x, y, and vertex_t::y.
Referenced by AM_LevelInit().
AM_getIslope()
void AM_getIslope (mline_t * ml, islope_t * is)
Definition at line 275 of file am_map.c.
 {
     int dx, dy;
     dy = ml->a.y - ml->b.y;
     dx = ml->b.x - ml->a.x;
     if (!dy) is->islp = (dx<0?-INT_MAX:INT_MAX);
     else is->islp = FixedDiv(dx, dy);
     if (!dx) is->slp = (dy<0?-INT_MAX:INT_MAX);
     else is->slp = FixedDiv(dy, dx);
 }
References mline_t::a, mline_t::b, FixedDiv(), INT_MAX, islope_t::islp, islope_t::slp, mpoint_t::x, and mpoint_t::y.
AM_initVariables()
void AM_initVariables (void)
Definition at line 424 of file am_map.c.
 {
     int pnum;
     static event_t st_notify = { ev_keyup, AM_MSGENTERED, 0, 0 };
     automapactive = true;
     fb = I_VideoBuffer;
     f_oldloc.x = INT_MAX;
     amclock = 0;
     lightlev = 0;
     m_paninc.x = m_paninc.y = 0;
     ftom_zoommul = FRACUNIT;
     mtof_zoommul = FRACUNIT;
     m_w = FTOM(f_w);
     m_h = FTOM(f_h);
     // find player to center on initially
     if (playeringame[consoleplayer])
     {
         plr = &players[consoleplayer];
     }
     else
     {
         plr = &players[0];
     for (pnum=0;pnum<MAXPLAYERS;pnum++)
         {
         if (playeringame[pnum])
             {
                 plr = &players[pnum];
         break;
             }
         }
     }
     m_x = plr->mo->x - m_w/2;
     m_y = plr->mo->y - m_h/2;
     AM_changeWindowLoc();
     // for saving & restoring
     old_m_x = m_x;
     old_m_y = m_y;
     old_m_w = m_w;
     old_m_h = m_h;
     // inform the status bar of the change
     ST_Responder(&st_notify);
 }
References AM_changeWindowLoc(), AM_MSGENTERED, amclock, automapactive, consoleplayer, ev_keyup, f_h, f_oldloc, f_w, fb, FRACUNIT, FTOM, ftom_zoommul, I_VideoBuffer, INT_MAX, lightlev, m_h, m_paninc, m_w, m_x, m_y, MAXPLAYERS, player_s::mo, mtof_zoommul, old_m_h, old_m_w, old_m_x, old_m_y, playeringame, players, plr, ST_Responder(), mpoint_t::x, mobj_s::x, mpoint_t::y, and mobj_s::y.
Referenced by AM_Start().
AM_LevelInit()
void AM_LevelInit (void)
Definition at line 518 of file am_map.c.
 {
     leveljuststarted = 0;
     f_x = f_y = 0;
     f_w = finit_width;
     f_h = finit_height;
     AM_clearMarks();
     AM_findMinMaxBoundaries();
     scale_mtof = FixedDiv(min_scale_mtof, (int) (0.7*FRACUNIT));
     if (scale_mtof > max_scale_mtof)
     scale_mtof = min_scale_mtof;
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
 }
References AM_clearMarks(), AM_findMinMaxBoundaries(), f_h, f_w, f_x, f_y, finit_height, finit_width, FixedDiv(), FRACUNIT, leveljuststarted, max_scale_mtof, min_scale_mtof, scale_ftom, and scale_mtof.
Referenced by AM_Start().
AM_loadPics()
void AM_loadPics (void)
Definition at line 480 of file am_map.c.
 {
     int i;
     char namebuf[9];
     for (i=0;i<10;i++)
     {
     DEH_snprintf(namebuf, 9, "AMMNUM%d", i);
     marknums[i] = W_CacheLumpName(namebuf, PU_STATIC);
     }
 }
References DEH_snprintf, i, marknums, PU_STATIC, and W_CacheLumpName().
Referenced by AM_Start().
AM_maxOutWindowScale()
void AM_maxOutWindowScale (void)
Definition at line 583 of file am_map.c.
 {
     scale_mtof = max_scale_mtof;
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
     AM_activateNewScale();
 }
References AM_activateNewScale(), FixedDiv(), FRACUNIT, max_scale_mtof, scale_ftom, and scale_mtof.
Referenced by AM_changeWindowScale().
AM_minOutWindowScale()
void AM_minOutWindowScale (void)
Definition at line 573 of file am_map.c.
 {
     scale_mtof = min_scale_mtof;
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
     AM_activateNewScale();
 }
References AM_activateNewScale(), FixedDiv(), FRACUNIT, min_scale_mtof, scale_ftom, and scale_mtof.
Referenced by AM_changeWindowScale(), and AM_Responder().
AM_Responder()
boolean AM_Responder (event_t * ev)
Definition at line 595 of file am_map.c.
 {
     int rc;
     static int bigstate=0;
     static char buffer[20];
     int key;
     rc = false;
     if (!automapactive)
     {
     if (ev->type == ev_keydown && ev->data1 == key_map_toggle)
     {
         AM_Start ();
         viewactive = false;
         rc = true;
     }
     }
     else if (ev->type == ev_keydown)
     {
     rc = true;
         key = ev->data1;
         if (key == key_map_east)          // pan right
         {
             if (!followplayer) m_paninc.x = FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_west)     // pan left
         {
             if (!followplayer) m_paninc.x = -FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_north)    // pan up
         {
             if (!followplayer) m_paninc.y = FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_south)    // pan down
         {
             if (!followplayer) m_paninc.y = -FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_zoomout)  // zoom out
         {
             mtof_zoommul = M_ZOOMOUT;
             ftom_zoommul = M_ZOOMIN;
         }
         else if (key == key_map_zoomin)   // zoom in
         {
             mtof_zoommul = M_ZOOMIN;
             ftom_zoommul = M_ZOOMOUT;
         }
         else if (key == key_map_toggle)
         {
             bigstate = 0;
             viewactive = true;
             AM_Stop ();
         }
         else if (key == key_map_maxzoom)
         {
             bigstate = !bigstate;
             if (bigstate)
             {
                 AM_saveScaleAndLoc();
                 AM_minOutWindowScale();
             }
             else AM_restoreScaleAndLoc();
         }
         else if (key == key_map_follow)
         {
             followplayer = !followplayer;
             f_oldloc.x = INT_MAX;
             if (followplayer)
                 plr->message = DEH_String(AMSTR_FOLLOWON);
             else
                 plr->message = DEH_String(AMSTR_FOLLOWOFF);
         }
         else if (key == key_map_grid)
         {
             grid = !grid;
             if (grid)
                 plr->message = DEH_String(AMSTR_GRIDON);
             else
                 plr->message = DEH_String(AMSTR_GRIDOFF);
         }
         else if (key == key_map_mark)
         {
             M_snprintf(buffer, sizeof(buffer), "%s %d",
                        DEH_String(AMSTR_MARKEDSPOT), markpointnum);
             plr->message = buffer;
             AM_addMark();
         }
         else if (key == key_map_clearmark)
         {
             AM_clearMarks();
             plr->message = DEH_String(AMSTR_MARKSCLEARED);
         }
         else
         {
             rc = false;
         }
     if (!deathmatch && cht_CheckCheat(&cheat_amap, ev->data2))
     {
         rc = false;
         cheating = (cheating+1) % 3;
     }
     }
     else if (ev->type == ev_keyup)
     {
         rc = false;
         key = ev->data1;
         if (key == key_map_east)
         {
             if (!followplayer) m_paninc.x = 0;
         }
         else if (key == key_map_west)
         {
             if (!followplayer) m_paninc.x = 0;
         }
         else if (key == key_map_north)
         {
             if (!followplayer) m_paninc.y = 0;
         }
         else if (key == key_map_south)
         {
             if (!followplayer) m_paninc.y = 0;
         }
         else if (key == key_map_zoomout || key == key_map_zoomin)
         {
             mtof_zoommul = FRACUNIT;
             ftom_zoommul = FRACUNIT;
         }
     }
     return rc;
 }
References AM_addMark(), AM_clearMarks(), AM_minOutWindowScale(), AM_restoreScaleAndLoc(), AM_saveScaleAndLoc(), AM_Start(), AM_Stop(), AMSTR_FOLLOWOFF, AMSTR_FOLLOWON, AMSTR_GRIDOFF, AMSTR_GRIDON, AMSTR_MARKEDSPOT, AMSTR_MARKSCLEARED, automapactive, cheat_amap, cheating, cht_CheckCheat(), event_t::data1, event_t::data2, deathmatch, DEH_String, ev_keydown, ev_keyup, f_oldloc, F_PANINC, followplayer, FRACUNIT, FTOM, ftom_zoommul, grid, INT_MAX, key_map_clearmark, key_map_east, key_map_follow, key_map_grid, key_map_mark, key_map_maxzoom, key_map_north, key_map_south, key_map_toggle, key_map_west, key_map_zoomin, key_map_zoomout, m_paninc, M_snprintf(), M_ZOOMIN, M_ZOOMOUT, markpointnum, player_s::message, mtof_zoommul, plr, event_t::type, viewactive, mpoint_t::x, and mpoint_t::y.
Referenced by G_Responder().
AM_restoreScaleAndLoc()
void AM_restoreScaleAndLoc (void)
Definition at line 319 of file am_map.c.
 {
     m_w = old_m_w;
     m_h = old_m_h;
     if (!followplayer)
     {
     m_x = old_m_x;
     m_y = old_m_y;
     } else {
     m_x = plr->mo->x - m_w/2;
     m_y = plr->mo->y - m_h/2;
     }
     m_x2 = m_x + m_w;
     m_y2 = m_y + m_h;
     // Change the scaling multipliers
     scale_mtof = FixedDiv(f_w<<FRACBITS, m_w);
     scale_ftom = FixedDiv(FRACUNIT, scale_mtof);
 }
References f_w, FixedDiv(), followplayer, FRACBITS, FRACUNIT, m_h, m_w, m_x, m_x2, m_y, m_y2, player_s::mo, old_m_h, old_m_w, old_m_x, old_m_y, plr, scale_ftom, scale_mtof, mobj_s::x, and mobj_s::y.
Referenced by AM_Responder().
AM_rotate()
void AM_rotate (fixed_t * x, fixed_t * y, angle_t a)
Definition at line 1179 of file am_map.c.
 {
     fixed_t tmpx;
     tmpx =
     FixedMul(*x,finecosine[a>>ANGLETOFINESHIFT])
     - FixedMul(*y,finesine[a>>ANGLETOFINESHIFT]);
     *y   =
     FixedMul(*x,finesine[a>>ANGLETOFINESHIFT])
     + FixedMul(*y,finecosine[a>>ANGLETOFINESHIFT]);
     *x = tmpx;
 }
References ANGLETOFINESHIFT, finecosine, finesine, FixedMul(), x, and y.
Referenced by AM_drawLineCharacter().
AM_saveScaleAndLoc()
void AM_saveScaleAndLoc (void)
Definition at line 308 of file am_map.c.
 {
     old_m_x = m_x;
     old_m_y = m_y;
     old_m_w = m_w;
     old_m_h = m_h;
 }
References m_h, m_w, m_x, m_y, old_m_h, old_m_w, old_m_x, and old_m_y.
Referenced by AM_Responder().
AM_Start()
void AM_Start (void)
Definition at line 554 of file am_map.c.
 {
     static int lastlevel = -1, lastepisode = -1;
     if (!stopped) AM_Stop();
     stopped = false;
     if (lastlevel != gamemap || lastepisode != gameepisode)
     {
     AM_LevelInit();
     lastlevel = gamemap;
     lastepisode = gameepisode;
     }
     AM_initVariables();
     AM_loadPics();
 }
References AM_initVariables(), AM_LevelInit(), AM_loadPics(), AM_Stop(), gameepisode, gamemap, and stopped.
Referenced by AM_Responder().
AM_Stop()
void AM_Stop (void)
Definition at line 541 of file am_map.c.
 {
     static event_t st_notify = { 0, ev_keyup, AM_MSGEXITED, 0 };
     AM_unloadPics();
     automapactive = false;
     ST_Responder(&st_notify);
     stopped = true;
 }
References AM_MSGEXITED, AM_unloadPics(), automapactive, ev_keyup, ST_Responder(), and stopped.
Referenced by AM_Responder(), AM_Start(), G_DoCompleted(), and P_KillMobj().
AM_Ticker()
void AM_Ticker (void)
Definition at line 806 of file am_map.c.
 {
     if (!automapactive)
     return;
     amclock++;
     if (followplayer)
     AM_doFollowPlayer();
     // Change the zoom if necessary
     if (ftom_zoommul != FRACUNIT)
     AM_changeWindowScale();
     // Change x,y location
     if (m_paninc.x || m_paninc.y)
     AM_changeWindowLoc();
     // Update light level
     // AM_updateLightLev();
 }
References AM_changeWindowLoc(), AM_changeWindowScale(), AM_doFollowPlayer(), amclock, automapactive, followplayer, FRACUNIT, ftom_zoommul, m_paninc, mpoint_t::x, and mpoint_t::y.
Referenced by G_Ticker().
AM_unloadPics()
void AM_unloadPics (void)
Definition at line 493 of file am_map.c.
 {
     int i;
     char namebuf[9];
     for (i=0;i<10;i++)
     {
     DEH_snprintf(namebuf, 9, "AMMNUM%d", i);
     W_ReleaseLumpName(namebuf);
     }
 }
References DEH_snprintf, i, and W_ReleaseLumpName().
Referenced by AM_Stop().
AM_updateLightLev()
void AM_updateLightLev (void)
Definition at line 785 of file am_map.c.
 {
     static int nexttic = 0;
     //static int litelevels[] = { 0, 3, 5, 6, 6, 7, 7, 7 };
     static int litelevels[] = { 0, 4, 7, 10, 12, 14, 15, 15 };
     static int litelevelscnt = 0;
     // Change light level
     if (amclock>nexttic)
     {
     lightlev = litelevels[litelevelscnt++];
     if (litelevelscnt == arrlen(litelevels)) litelevelscnt = 0;
     nexttic = amclock + 6 - (amclock % 6);
     }
 }
References amclock, arrlen, and lightlev.
Variable Documentation
amclock
int amclock static
Definition at line 214 of file am_map.c.
Referenced by AM_initVariables(), AM_Ticker(), and AM_updateLightLev().
automapactive
boolean automapactive = false
Definition at line 200 of file am_map.c.
Referenced by AM_Drawer(), AM_initVariables(), AM_Responder(), AM_Stop(), AM_Ticker(), D_Display(), F_StartFinale(), G_DoCompleted(), G_InitNew(), HU_Drawer(), HUlib_eraseTextLine(), M_Responder(), P_KillMobj(), and ST_Drawer().
cheat_amap
cheatseq_t cheat_amap = CHEAT("iddt", 0)
Definition at line 266 of file am_map.c.
Referenced by AM_Responder().
cheat_player_arrow
mline_t cheat_player_arrow[]
Initial value:
= {
    { { -R+R/8, 0 }, { R, 0 } },
    { { R, 0 }, { R-R/2, R/6 } },
    { { R, 0 }, { R-R/2, -R/6 } },
    { { -R+R/8, 0 }, { -R-R/8, R/6 } },
    { { -R+R/8, 0 }, { -R-R/8, -R/6 } },
    { { -R+3*R/8, 0 }, { -R+R/8, R/6 } },
    { { -R+3*R/8, 0 }, { -R+R/8, -R/6 } },
    { { -R/2, 0 }, { -R/2, -R/6 } },
    { { -R/2, -R/6 }, { -R/2+R/6, -R/6 } },
    { { -R/2+R/6, -R/6 }, { -R/2+R/6, R/4 } },
    { { -R/6, 0 }, { -R/6, -R/6 } },
    { { -R/6, -R/6 }, { 0, -R/6 } },
    { { 0, -R/6 }, { 0, R/4 } },
    { { R/6, R/4 }, { R/6, -R/7 } },
    { { R/6, -R/7 }, { R/6+R/32, -R/7-R/32 } },
    { { R/6+R/32, -R/7-R/32 }, { R/6+R/10, -R/7 } }
}
Definition at line 156 of file am_map.c.
Referenced by AM_drawPlayers().
cheating
int cheating = 0 static
Definition at line 195 of file am_map.c.
Referenced by AM_Drawer(), AM_drawPlayers(), AM_drawWalls(), and AM_Responder().
f_h
int f_h static
Definition at line 210 of file am_map.c.
Referenced by AM_activateNewScale(), AM_clearFB(), AM_clipMline(), AM_drawCrosshair(), AM_Drawer(), AM_drawFline(), AM_drawMarks(), AM_findMinMaxBoundaries(), AM_initVariables(), and AM_LevelInit().
f_oldloc
mpoint_t f_oldloc static
Definition at line 251 of file am_map.c.
Referenced by AM_changeWindowLoc(), AM_doFollowPlayer(), AM_initVariables(), and AM_Responder().
f_w
int f_w static
Definition at line 209 of file am_map.c.
Referenced by AM_activateNewScale(), AM_clearFB(), AM_clipMline(), AM_drawCrosshair(), AM_Drawer(), AM_drawFline(), AM_findMinMaxBoundaries(), AM_initVariables(), AM_LevelInit(), and AM_restoreScaleAndLoc().
f_x
int f_x static
Definition at line 205 of file am_map.c.
Referenced by AM_Drawer(), AM_drawMarks(), and AM_LevelInit().
f_y
int f_y static
Definition at line 206 of file am_map.c.
Referenced by AM_Drawer(), AM_drawMarks(), and AM_LevelInit().
fb
byte* fb static
Definition at line 213 of file am_map.c.
Referenced by AM_clearFB(), AM_drawCrosshair(), AM_initVariables(), and multiboot_main().
finit_height
int finit_height = SCREENHEIGHT - 32 static
Definition at line 202 of file am_map.c.
Referenced by AM_LevelInit().
finit_width
int finit_width = SCREENWIDTH static
Definition at line 201 of file am_map.c.
Referenced by AM_LevelInit().
followplayer
int followplayer = 1 static
Definition at line 264 of file am_map.c.
Referenced by AM_changeWindowLoc(), AM_Responder(), AM_restoreScaleAndLoc(), and AM_Ticker().
ftom_zoommul
fixed_t ftom_zoommul static
Definition at line 218 of file am_map.c.
Referenced by AM_initVariables(), AM_Responder(), and AM_Ticker().
grid
int grid = 0 static
Definition at line 196 of file am_map.c.
Referenced by AM_Drawer(), and AM_Responder().
leveljuststarted
int leveljuststarted = 1 static
Definition at line 198 of file am_map.c.
Referenced by AM_LevelInit().
lightlev
int lightlev static
Definition at line 212 of file am_map.c.
Referenced by AM_drawThings(), AM_drawWalls(), AM_initVariables(), and AM_updateLightLev().
m_h
fixed_t m_h static
Definition at line 227 of file am_map.c.
Referenced by AM_activateNewScale(), AM_addMark(), AM_changeWindowLoc(), AM_doFollowPlayer(), AM_drawGrid(), AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
m_paninc
mpoint_t m_paninc static
Definition at line 216 of file am_map.c.
Referenced by AM_changeWindowLoc(), AM_initVariables(), AM_Responder(), and AM_Ticker().
m_w
fixed_t m_w static
Definition at line 226 of file am_map.c.
Referenced by AM_activateNewScale(), AM_addMark(), AM_changeWindowLoc(), AM_doFollowPlayer(), AM_drawGrid(), AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
m_x
fixed_t m_x static
Definition at line 220 of file am_map.c.
Referenced by AM_activateNewScale(), AM_addMark(), AM_changeWindowLoc(), AM_clipMline(), AM_doFollowPlayer(), AM_drawGrid(), AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
m_x2
fixed_t m_x2 static
Definition at line 221 of file am_map.c.
Referenced by AM_activateNewScale(), AM_changeWindowLoc(), AM_clipMline(), AM_doFollowPlayer(), and AM_restoreScaleAndLoc().
m_y
fixed_t m_y static
Definition at line 220 of file am_map.c.
Referenced by AM_activateNewScale(), AM_addMark(), AM_changeWindowLoc(), AM_clipMline(), AM_doFollowPlayer(), AM_drawGrid(), AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
m_y2
fixed_t m_y2 static
Definition at line 221 of file am_map.c.
Referenced by AM_activateNewScale(), AM_changeWindowLoc(), AM_clipMline(), AM_doFollowPlayer(), and AM_restoreScaleAndLoc().
marknums
patch_t* marknums[10] static
Definition at line 260 of file am_map.c.
Referenced by AM_drawMarks(), and AM_loadPics().
markpointnum
int markpointnum = 0 static
Definition at line 262 of file am_map.c.
Referenced by AM_addMark(), AM_clearMarks(), and AM_Responder().
markpoints
mpoint_t markpoints[AM_NUMMARKPOINTS] static
Definition at line 261 of file am_map.c.
Referenced by AM_addMark(), AM_clearMarks(), and AM_drawMarks().
max_h
fixed_t max_h static
Definition at line 236 of file am_map.c.
Referenced by AM_findMinMaxBoundaries().
max_scale_mtof
fixed_t max_scale_mtof static
Definition at line 244 of file am_map.c.
Referenced by AM_changeWindowScale(), AM_findMinMaxBoundaries(), AM_LevelInit(), and AM_maxOutWindowScale().
max_w
fixed_t max_w static
Definition at line 235 of file am_map.c.
Referenced by AM_findMinMaxBoundaries().
max_x
fixed_t max_x static
Definition at line 232 of file am_map.c.
Referenced by AM_changeWindowLoc(), and AM_findMinMaxBoundaries().
max_y
fixed_t max_y static
Definition at line 233 of file am_map.c.
Referenced by AM_changeWindowLoc(), and AM_findMinMaxBoundaries().
min_h
fixed_t min_h static
Definition at line 240 of file am_map.c.
Referenced by AM_findMinMaxBoundaries().
min_scale_mtof
fixed_t min_scale_mtof static
Definition at line 243 of file am_map.c.
Referenced by AM_changeWindowScale(), AM_findMinMaxBoundaries(), AM_LevelInit(), and AM_minOutWindowScale().
min_w
fixed_t min_w static
Definition at line 239 of file am_map.c.
Referenced by AM_findMinMaxBoundaries().
min_x
fixed_t min_x static
Definition at line 230 of file am_map.c.
Referenced by AM_changeWindowLoc(), and AM_findMinMaxBoundaries().
min_y
fixed_t min_y static
Definition at line 231 of file am_map.c.
Referenced by AM_changeWindowLoc(), and AM_findMinMaxBoundaries().
mtof_zoommul
fixed_t mtof_zoommul static
Definition at line 217 of file am_map.c.
Referenced by AM_changeWindowScale(), AM_initVariables(), and AM_Responder().
old_m_h
fixed_t old_m_h static
Definition at line 247 of file am_map.c.
Referenced by AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
old_m_w
fixed_t old_m_w static
Definition at line 247 of file am_map.c.
Referenced by AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
old_m_x
fixed_t old_m_x static
Definition at line 248 of file am_map.c.
Referenced by AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
old_m_y
fixed_t old_m_y static
Definition at line 248 of file am_map.c.
Referenced by AM_initVariables(), AM_restoreScaleAndLoc(), and AM_saveScaleAndLoc().
player_arrow
mline_t player_arrow[]
Initial value:
= {
    { { -R+R/8, 0 }, { R, 0 } },
    { { R, 0 }, { R-R/2, R/4 } },
    { { R, 0 }, { R-R/2, -R/4 } },
    { { -R+R/8, 0 }, { -R-R/8, R/4 } },
    { { -R+R/8, 0 }, { -R-R/8, -R/4 } },
    { { -R+3*R/8, 0 }, { -R+R/8, R/4 } },
    { { -R+3*R/8, 0 }, { -R+R/8, -R/4 } }
}
Definition at line 144 of file am_map.c.
Referenced by AM_drawPlayers().
plr
player_t* plr static
Definition at line 258 of file am_map.c.
Referenced by AM_doFollowPlayer(), AM_drawPlayers(), AM_drawWalls(), AM_initVariables(), AM_Responder(), and AM_restoreScaleAndLoc().
scale_ftom
fixed_t scale_ftom static
Definition at line 256 of file am_map.c.
Referenced by AM_changeWindowScale(), AM_LevelInit(), AM_maxOutWindowScale(), AM_minOutWindowScale(), and AM_restoreScaleAndLoc().
scale_mtof
fixed_t scale_mtof = (fixed_t)INITSCALEMTOF static
Definition at line 254 of file am_map.c.
Referenced by AM_changeWindowScale(), AM_LevelInit(), AM_maxOutWindowScale(), AM_minOutWindowScale(), and AM_restoreScaleAndLoc().
stopped
boolean stopped = true static
Definition at line 268 of file am_map.c.
Referenced by AM_Start(), and AM_Stop().
thintriangle_guy
mline_t thintriangle_guy[]
Initial value:
= {
    { { (fixed_t)(-.5*R), (fixed_t)(-.7*R) }, { (fixed_t)(R    ), (fixed_t)(0    ) } },
    { { (fixed_t)(R    ), (fixed_t)(0    ) }, { (fixed_t)(-.5*R), (fixed_t)(.7*R ) } },
    { { (fixed_t)(-.5*R), (fixed_t)(.7*R ) }, { (fixed_t)(-.5*R), (fixed_t)(-.7*R) } }
}
Definition at line 185 of file am_map.c.
Referenced by AM_drawThings().
triangle_guy
mline_t triangle_guy[]
Initial value:
= {
    { { (fixed_t)(-.867*R), (fixed_t)(-.5*R) }, { (fixed_t)(.867*R ), (fixed_t)(-.5*R) } },
    { { (fixed_t)(.867*R ), (fixed_t)(-.5*R) }, { (fixed_t)(0      ), (fixed_t)(R    ) } },
    { { (fixed_t)(0      ), (fixed_t)(R    ) }, { (fixed_t)(-.867*R), (fixed_t)(-.5*R) } }
}
Definition at line 177 of file am_map.c.