Fennix Kernel: Kernel/Tasking/Task.cpp File Reference
Task.cpp File Reference
#include <task.hpp>
#include <dumper.hpp>
#include <convert.h>
#include <lock.hpp>
#include <printf.h>
#include <smp.hpp>
#include <io.h>
#include "../kernel.h"
Namespaces
Tasking
Macros
#define tskdbg(m, ...)
Functions
NewLock (TaskingLock)
void ThreadDoExit ()
__no_sanitize ("undefined") TCB *Task
Macro Definition Documentation
tskdbg
#define tskdbg (m, ...)
Definition at line 44 of file Task.cpp.
Function Documentation
__no_sanitize()
__no_sanitize ("undefined")
Definition at line 350 of file Task.cpp.
     {
         SmartLock(TaskingLock);
         TCB *Thread = new TCB;
         if (Parent == nullptr)
         {
             Thread->Parent = this->GetCurrentProcess();
             if (Thread->Parent == nullptr)
             {
                 error("Failed to get current process. Thread cannot be created.");
                 delete Thread;
                 return nullptr;
             }
         }
         else
             Thread->Parent = Parent;
         if (InvalidPCB(Parent))
         {
             error("Parent is invalid");
             delete Thread;
             return nullptr;
         }
         Thread->ID = this->NextTID++;
         strcpy(Thread->Name, Parent->Name);
         Thread->EntryPoint = EntryPoint;
         Thread->Offset = Offset;
         Thread->ExitCode = 0xdead;
         if (ThreadNotReady)
             Thread->Status = TaskStatus::Waiting;
         else
             Thread->Status = TaskStatus::Ready;
         Thread->Memory = new Memory::MemMgr(Parent->PageTable, Parent->memDirectory);
         Thread->FPU = (CPU::x64::FXState *)Thread->Memory->RequestPages(TO_PAGES(sizeof(CPU::x64::FXState) + 1));
         memset(Thread->FPU, 0, sizeof(CPU::x64::FXState));
         Thread->Security.TrustLevel = Parent->Security.TrustLevel;
         Thread->Security.UniqueToken = SecurityManager.CreateToken();
         // TODO: Is really a good idea to use the FPU in kernel mode?
         Thread->FPU->mxcsr = 0b0001111110000000;
         Thread->FPU->mxcsrmask = 0b1111111110111111;
         Thread->FPU->fcw = 0b0000001100111111;
         // CPU::x64::fxrstor(Thread->FPU);
         // uint16_t FCW = 0b1100111111;
         // asmv("fldcw %0"
         //      :
         //      : "m"(FCW)
         //      : "memory");
         // uint32_t MXCSR = 0b1111110000000;
         // asmv("ldmxcsr %0"
         //      :
         //      : "m"(MXCSR)
         //      : "memory");
         // CPU::x64::fxsave(Thread->FPU);
 #if defined(a64)
         memset(&Thread->Registers, 0, sizeof(CPU::x64::TrapFrame)); // Just in case
         Thread->Registers.rip = (EntryPoint + Offset);
 #elif defined(a32)
 #elif defined(aa64)
 #endif
         switch (Parent->Security.TrustLevel)
         {
         case TaskTrustLevel::System:
             warn("Trust level not supported.");
             [[fallthrough]];
         case TaskTrustLevel::Kernel:
         {
             Thread->Security.IsCritical = true;
             Thread->Stack = new Memory::StackGuard(false, Parent->PageTable);
 #if defined(a64)
             SecurityManager.TrustToken(Thread->Security.UniqueToken, TTL::TrustedByKernel);
             Thread->ShadowGSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_SHADOW_GS_BASE);
             Thread->GSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_GS_BASE);
             Thread->FSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_FS_BASE);
             Thread->Registers.cs = GDT_KERNEL_CODE;
             Thread->Registers.ss = GDT_KERNEL_DATA;
             Thread->Registers.rflags.AlwaysOne = 1;
             Thread->Registers.rflags.IF = 1;
             Thread->Registers.rflags.ID = 1;
             Thread->Registers.rsp = ((uintptr_t)Thread->Stack->GetStackTop());
             POKE(uintptr_t, Thread->Registers.rsp) = (uintptr_t)ThreadDoExit;
 #elif defined(a32)
 #elif defined(aa64)
 #endif
             break;
         }
         case TaskTrustLevel::User:
         {
             Thread->Stack = new Memory::StackGuard(true, Parent->PageTable);
 #if defined(a64)
             SecurityManager.TrustToken(Thread->Security.UniqueToken, TTL::Untrusted);
             Thread->ShadowGSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_SHADOW_GS_BASE);
             Thread->GSBase = 0;
             Thread->FSBase = 0;
             Thread->Registers.cs = GDT_USER_CODE;
             Thread->Registers.ss = GDT_USER_DATA;
             Thread->Registers.rflags.AlwaysOne = 1;
             Thread->Registers.rflags.IF = 1;
             Thread->Registers.rflags.ID = 1;
             /* We need to leave the libc's crt
                to make a syscall when the Thread
                is exited or we are going to get
                GPF or PF exception. */
 #pragma region
             size_t ArgvSize = 0;
             if (argv)
                 while (argv[ArgvSize] != nullptr)
                     ArgvSize++;
             size_t EnvpSize = 0;
             if (envp)
                 while (envp[EnvpSize] != nullptr)
                     EnvpSize++;
             debug("ArgvSize: %d", ArgvSize);
             debug("EnvpSize: %d", EnvpSize);
             /* https://articles.manugarg.com/aboutelfauxiliaryvectors.html */
             /* https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf#figure.3.9 */
             // rsp is the top of the stack
             char *Stack = (char *)Thread->Stack->GetStackPhysicalTop();
             // Temporary stack pointer for strings
             char *StackStrings = (char *)Stack;
             char *StackStringsVirtual = (char *)Thread->Stack->GetStackTop();
             // Store string pointers for later
             uintptr_t *ArgvStrings = nullptr;
             uintptr_t *EnvpStrings = nullptr;
             if (ArgvSize > 0)
                 ArgvStrings = new uintptr_t[ArgvSize];
             if (EnvpSize > 0)
                 EnvpStrings = new uintptr_t[EnvpSize];
             for (size_t i = 0; i < ArgvSize; i++)
             {
                 // Subtract the length of the string and the null terminator
                 StackStrings -= strlen(argv[i]) + 1;
                 StackStringsVirtual -= strlen(argv[i]) + 1;
                 // Store the pointer to the string
                 ArgvStrings[i] = (uintptr_t)StackStringsVirtual;
                 // Copy the string to the stack
                 strcpy(StackStrings, argv[i]);
             }
             for (size_t i = 0; i < EnvpSize; i++)
             {
                 // Subtract the length of the string and the null terminator
                 StackStrings -= strlen(envp[i]) + 1;
                 StackStringsVirtual -= strlen(envp[i]) + 1;
                 // Store the pointer to the string
                 EnvpStrings[i] = (uintptr_t)StackStringsVirtual;
                 // Copy the string to the stack
                 strcpy(StackStrings, envp[i]);
             }
             // Align the stack to 16 bytes
             StackStrings -= (uintptr_t)StackStrings & 0xF;
             // Set "Stack" to the new stack pointer
             Stack = (char *)StackStrings;
             // If argv and envp sizes are odd then we need to align the stack
             Stack -= (ArgvSize + EnvpSize) % 2;
             // We need 8 bit pointers for the stack from here
             uintptr_t *Stack64 = (uintptr_t *)Stack;
             // Store the null terminator
             Stack64--;
             *Stack64 = AT_NULL;
             // auxv_array is initialized with auxv elements. If the array is empty then we add a null terminator
             std::vector<AuxiliaryVector> auxv_array = auxv;
             if (auxv_array.size() == 0)
                 auxv_array.push_back({.archaux = {.a_type = AT_NULL, .a_un = {.a_val = 0}}});
             // Store auxillary vector
             foreach (AuxiliaryVector var in auxv_array)
             {
                 // Subtract the size of the auxillary vector
                 Stack64 -= sizeof(Elf64_auxv_t) / sizeof(uintptr_t);
                 // Store the auxillary vector
                 POKE(Elf64_auxv_t, Stack64) = var.archaux;
                 // TODO: Store strings to the stack
             }
             // Store the null terminator
             Stack64--;
             *Stack64 = AT_NULL;
             // Store EnvpStrings[] to the stack
             Stack64 -= EnvpSize; // (1 Stack64 = 8 bits; Stack64 = 8 * EnvpSize)
             for (size_t i = 0; i < EnvpSize; i++)
             {
                 *(Stack64 + i) = (uintptr_t)EnvpStrings[i];
                 debug("EnvpStrings[%d]: %#lx", i, EnvpStrings[i]);
             }
             // Store the null terminator
             Stack64--;
             *Stack64 = AT_NULL;
             // Store ArgvStrings[] to the stack
             Stack64 -= ArgvSize; // (1 Stack64 = 8 bits; Stack64 = 8 * ArgvSize)
             for (size_t i = 0; i < ArgvSize; i++)
             {
                 *(Stack64 + i) = (uintptr_t)ArgvStrings[i];
                 debug("ArgvStrings[%d]: %#lx", i, ArgvStrings[i]);
             }
             // Store the argc
             Stack64--;
             *Stack64 = ArgvSize;
             // Set "Stack" to the new stack pointer
             Stack = (char *)Stack64;
             /* We need the virtual address but because we are in the kernel we can't use the process page table.
                 So we modify the physical address and store how much we need to subtract to get the virtual address for RSP. */
             uintptr_t SubtractStack = (uintptr_t)Thread->Stack->GetStackPhysicalTop() - (uintptr_t)Stack;
             debug("SubtractStack: %#lx", SubtractStack);
             // Set the stack pointer to the new stack
             Thread->Registers.rsp = ((uintptr_t)Thread->Stack->GetStackTop() - SubtractStack);
             if (ArgvSize > 0)
                 delete[] ArgvStrings;
             if (EnvpSize > 0)
                 delete[] EnvpStrings;
 #ifdef DEBUG
             DumpData("Stack Data", (void *)((uintptr_t)Thread->Stack->GetStackPhysicalTop() - (uintptr_t)SubtractStack), SubtractStack);
 #endif
             Thread->Registers.rdi = (uintptr_t)ArgvSize;                                         // argc
             Thread->Registers.rsi = (uintptr_t)(Thread->Registers.rsp + 8);                      // argv
             Thread->Registers.rcx = (uintptr_t)EnvpSize;                                         // envc
             Thread->Registers.rdx = (uintptr_t)(Thread->Registers.rsp + 8 + (8 * ArgvSize) + 8); // envp
 #pragma endregion
 #elif defined(a32)
 #elif defined(aa64)
 #endif
 #ifdef DEBUG_TASKING
             DumpData(Thread->Name, Thread->Stack, STACK_SIZE);
 #endif
             break;
         }
         default:
         {
             error("Unknown elevation.");
             delete Thread->Stack;
             this->NextTID--;
             delete Thread;
             return nullptr;
         }
         }
         Thread->Info = {};
         Thread->Info.SpawnTime = TimeManager->GetCounter();
         Thread->Info.Year = 0;
         Thread->Info.Month = 0;
         Thread->Info.Day = 0;
         Thread->Info.Hour = 0;
         Thread->Info.Minute = 0;
         Thread->Info.Second = 0;
         for (int i = 0; i < MAX_CPU; i++)
         {
             Thread->Info.Affinity[i] = true;
         }
         Thread->Info.Priority = TaskPriority::Normal;
         Thread->Info.Architecture = Architecture;
         Thread->Info.Compatibility = Compatibility;
 #ifdef DEBUG
 #ifdef a64
         debug("Thread offset is %#lx (EntryPoint: %#lx) => RIP: %#lx", Thread->Offset, Thread->EntryPoint, Thread->Registers.rip);
         if (Parent->Security.TrustLevel == TaskTrustLevel::User)
             debug("Thread stack region is %#lx-%#lx (U) and rsp is %#lx", Thread->Stack->GetStackBottom(), Thread->Stack->GetStackTop(), Thread->Registers.rsp);
         else
             debug("Thread stack region is %#lx-%#lx (K) and rsp is %#lx", Thread->Stack->GetStackBottom(), Thread->Stack->GetStackTop(), Thread->Registers.rsp);
 #elif defined(a32)
         debug("Thread offset is %#lx (EntryPoint: %#lx) => RIP: %#lx", Thread->Offset, Thread->EntryPoint, Thread->Registers.eip);
         if (Parent->Security.TrustLevel == TaskTrustLevel::User)
             debug("Thread stack region is %#lx-%#lx (U) and rsp is %#lx", Thread->Stack->GetStackBottom(), Thread->Stack->GetStackTop(), Thread->Registers.esp);
         else
             debug("Thread stack region is %#lx-%#lx (K) and rsp is %#lx", Thread->Stack->GetStackBottom(), Thread->Stack->GetStackTop(), Thread->Registers.esp);
 #elif defined(aa64)
 #endif
         debug("Created thread \"%s\"(%d) in process \"%s\"(%d)",
               Thread->Name, Thread->ID,
               Thread->Parent->Name, Thread->Parent->ID);
 #endif
         Parent->Threads.push_back(Thread);
         return Thread;
     }
References AT_NULL, debug, EntryPoint, error, GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_CODE, GDT_USER_DATA, Tasking::Kernel, memset(), CPU::x32::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, CPU::x32::MSR_SHADOW_GS_BASE, POKE, std::vector< T >::push_back(), Tasking::Ready, std::vector< T >::size(), Stack, strcpy, strlen(), Tasking::System, ThreadDoExit(), Tasking::TrustedByKernel, Tasking::Untrusted, Tasking::User, Tasking::Waiting, and warn.
NewLock()
NewLock (TaskingLock)
ThreadDoExit()
void ThreadDoExit ()
Definition at line 188 of file Task.cpp.
     {
         // TODO: How I can lock the scheduler without causing a deadlock?
         CPUData *CPUData = GetCurrentCPU();
         CPUData->CurrentThread->Status = TaskStatus::Terminated;
         debug("\"%s\"(%d) exited with code: %#lx", CPUData->CurrentThread->Name, CPUData->CurrentThread->ID, CPUData->CurrentThread->ExitCode);
         CPU::Halt(true);
     }
References CPUData::CurrentThread, debug, Tasking::TCB::ExitCode, GetCurrentCPU(), Halt(), Tasking::TCB::ID, Tasking::TCB::Name, Tasking::TCB::Status, and Tasking::Terminated.
Referenced by __no_sanitize().