Fennix: Userspace/apps/base/busybox/mailutils/mail.c File Reference
mail.c File Reference
#include "libbb.h"
#include "mail.h"
Macros
#define status signo
#define src_buf text
Functions
static void signal_handler (int signo)
void FAST_FUNC launch_helper (const char **argv)
void FAST_FUNC send_r_n (const char *s)
char *FAST_FUNC send_mail_command (const char *fmt, const char *param)
static void encode_n_base64 (const char *fname, const char *text, size_t len)
void FAST_FUNC printstr_base64 (const char *text)
void FAST_FUNC printbuf_base64 (const char *text, unsigned len)
void FAST_FUNC printfile_base64 (const char *fname)
void FAST_FUNC get_cred_or_die (int fd)
Macro Definition Documentation
src_buf
#define src_buf text
status
#define status signo
Function Documentation
encode_n_base64()
static void encode_n_base64 (const char * fname, const char * text, size_t len) static
Definition at line 128 of file mail.c.
 {
     enum {
         SRC_BUF_SIZE = 57,  /* This *MUST* be a multiple of 3 */
         DST_BUF_SIZE = 4 * ((SRC_BUF_SIZE + 2) / 3),
     };
 #define src_buf text
     char src[SRC_BUF_SIZE];
     FILE *fp = fp;
     char dst_buf[DST_BUF_SIZE + 1];
     if (fname) {
         fp = (NOT_LONE_DASH(fname)) ? xfopen_for_read(fname) : stdin;
         src_buf = src;
     }
     while (1) {
         size_t size;
         if (fname) {
             size = fread((char *)src_buf, 1, SRC_BUF_SIZE, fp);
             if ((ssize_t)size < 0)
                 bb_simple_perror_msg_and_die(bb_msg_read_error);
         } else {
             size = len;
             if (len > SRC_BUF_SIZE)
                 size = SRC_BUF_SIZE;
         }
         if (!size)
             break;
         // encode the buffer we just read in
         bb_uuencode(dst_buf, src_buf, size, bb_uuenc_tbl_base64);
         if (fname) {
             puts("");
         } else {
             src_buf += size;
             len -= size;
         }
         fwrite(dst_buf, 1, 4 * ((size + 2) / 3), stdout);
     }
     if (fname && NOT_LONE_DASH(fname))
         fclose(fp);
 #undef src_buf
 }
References bb_msg_read_error, bb_simple_perror_msg_and_die(), bb_uuencode(), DST_BUF_SIZE, fclose(), fname, fread(), fwrite(), len, NOT_LONE_DASH, puts(), size, src, src_buf, SRC_BUF_SIZE, stdin, stdout, and xfopen_for_read().
Referenced by printbuf_base64(), printfile_base64(), and printstr_base64().
get_cred_or_die()
void FAST_FUNC get_cred_or_die (int fd)
Definition at line 190 of file mail.c.
 {
     if (isatty(fd)) {
         G.user = bb_ask_noecho(fd, /* timeout: */ 0, "User: ");
         G.pass = bb_ask_noecho(fd, /* timeout: */ 0, "Password: ");
     } else {
         G.user = xmalloc_reads(fd, /* maxsize: */ NULL);
         G.pass = xmalloc_reads(fd, /* maxsize: */ NULL);
     }
     if (!G.user || !*G.user || !G.pass)
         bb_simple_error_msg_and_die("no username or password");
 }
References bb_ask_noecho(), bb_simple_error_msg_and_die(), fd, G(), isatty(), NULL, and xmalloc_reads().
Referenced by popmaildir_main(), and sendmail_main().
launch_helper()
void FAST_FUNC launch_helper (const char ** argv)
Definition at line 40 of file mail.c.
 {
     pid_t pid;
     struct fd_pair child_out;
     struct fd_pair child_in;
     xpiped_pair(child_out);
     xpiped_pair(child_in);
     // NB: handler must be installed before vfork
     bb_signals(0
         + (1 << SIGCHLD)
         + (1 << SIGALRM)
         , signal_handler);
     fflush_all();
     pid = xvfork();
     if (pid == 0) {
         // child
         close(child_in.wr);
         close(child_out.rd);
         xmove_fd(child_in.rd, STDIN_FILENO);
         xmove_fd(child_out.wr, STDOUT_FILENO);
         // if parent dies, get SIGTERM
 #if defined(PRCTL)
         prctl(PR_SET_PDEATHSIG, SIGTERM, 0, 0, 0);
 #elif defined(PROCCTL)
         {
             int signum = SIGTERM;
             procctl(P_PID, 0, PROC_PDEATHSIG_CTL, &signum);
         }
 #endif
         // try to execute connection helper
         // NB: SIGCHLD & SIGALRM revert to SIG_DFL on exec
         BB_EXECVP_or_die((char**)argv);
     }
     G.helper_pid = pid;
     close(child_out.wr);
     close(child_in.rd);
     xmove_fd(child_out.rd, STDIN_FILENO);
     xmove_fd(child_in.wr, STDOUT_FILENO);
     // parent goes on
 }
References argv, BB_EXECVP_or_die(), bb_signals(), close(), fflush_all(), G(), P_PID, pid, PR_SET_PDEATHSIG, prctl(), fd_pair::rd, SIGALRM, SIGCHLD, signal_handler(), SIGTERM, STDIN_FILENO, STDOUT_FILENO, fd_pair::wr, xmove_fd(), xpiped_pair, and xvfork.
Referenced by popmaildir_main(), and sendmail_main().
printbuf_base64()
void FAST_FUNC printbuf_base64 (const char * text, unsigned len)
Definition at line 177 of file mail.c.
 {
     encode_n_base64(NULL, text, len);
 }
References encode_n_base64(), len, NULL, and text.
Referenced by sendmail_main().
printfile_base64()
void FAST_FUNC printfile_base64 (const char * fname)
Definition at line 182 of file mail.c.
 {
     encode_n_base64(fname, NULL, 0);
 }
References encode_n_base64(), fname, and NULL.
Referenced by makemime_main().
printstr_base64()
void FAST_FUNC printstr_base64 (const char * text)
Definition at line 172 of file mail.c.
 {
     encode_n_base64(NULL, text, strlen(text));
 }
References encode_n_base64(), NULL, strlen(), and text.
Referenced by sendmail_main().
send_mail_command()
char* FAST_FUNC send_mail_command (const char * fmt, const char * param)
Definition at line 92 of file mail.c.
 {
     char *msg;
     if (G.timeout)
         alarm(G.timeout);
     msg = (char*)fmt;
     if (fmt) {
         msg = xasprintf(fmt, param);
         send_r_n(msg);
     }
     fflush_all();
     return msg;
 }
References alarm(), fflush_all(), G(), param, send_r_n(), and xasprintf().
Referenced by pop3_checkr(), and smtp_checkp().
send_r_n()
void FAST_FUNC send_r_n (const char * s)
Definition at line 85 of file mail.c.
 {
     if (G.verbose)
         bb_error_msg("send:'%s'", s);
     printf("%s\r\n", s);
 }
References bb_error_msg(), G(), printf, and s.
Referenced by send_mail_command(), and sendmail_main().
signal_handler()
static void signal_handler (int signo) static
Definition at line 20 of file mail.c.
 {
     if (SIGALRM == signo) {
         bb_simple_error_msg_and_die("timed out");
     }
     // SIGCHLD. reap the zombie if we expect one
     if (G.helper_pid == 0)
         return;
 #define status signo
     if (safe_waitpid(G.helper_pid, &status, WNOHANG) > 0) {
         G.helper_pid = 0;
         if (WIFSIGNALED(status))
             bb_error_msg_and_die("helper killed by signal %u", WTERMSIG(status));
         if (WIFEXITED(status) && WEXITSTATUS(status) != 0)
             bb_error_msg_and_die("helper exited (%u)", WEXITSTATUS(status));
     }
 #undef status
 }
References bb_error_msg_and_die(), bb_simple_error_msg_and_die(), G(), safe_waitpid(), SIGALRM, status, WEXITSTATUS, WIFEXITED, WIFSIGNALED, WNOHANG, and WTERMSIG.
Referenced by launch_helper().