Fennix: Userspace/musl/src/malloc/oldmalloc/aligned_alloc.c File Reference
aligned_alloc.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>
#include "malloc_impl.h"
Functions
void * aligned_alloc (size_t align, size_t len)
Function Documentation
aligned_alloc()
void* aligned_alloc (size_t align, size_t len)
Definition at line 6 of file aligned_alloc.c.
 {
     unsigned char *mem, *new;
     if ((align & -align) != align) {
         errno = EINVAL;
         return 0;
     }
     if (len > SIZE_MAX - align ||
         (__malloc_replaced && !__aligned_alloc_replaced)) {
         errno = ENOMEM;
         return 0;
     }
     if (align <= SIZE_ALIGN)
         return malloc(len);
     if (!(mem = malloc(len + align-1)))
         return 0;
     new = (void *)((uintptr_t)mem + align-1 & -align);
     if (new == mem) return mem;
     struct chunk *c = MEM_TO_CHUNK(mem);
     struct chunk *n = MEM_TO_CHUNK(new);
     if (IS_MMAPPED(c)) {
         /* Apply difference between aligned and original
          * address to the "extra" field of mmapped chunk. */
         n->psize = c->psize + (new-mem);
         n->csize = c->csize - (new-mem);
         return new;
     }
     struct chunk *t = NEXT_CHUNK(c);
     /* Split the allocated chunk into two chunks. The aligned part
      * that will be used has the size in its footer reduced by the
      * difference between the aligned and original addresses, and
      * the resulting size copied to its header. A new header and
      * footer are written for the split-off part to be freed. */
     n->psize = c->csize = C_INUSE | (new-mem);
     n->csize = t->psize -= new-mem;
     __bin_chunk(c);
     return new;
 }
References __aligned_alloc_replaced, __bin_chunk(), __malloc_replaced, c, C_INUSE, DISABLE_ALIGNED_ALLOC, EINVAL, end, ENOMEM, errno, g, get_meta(), get_slot_index(), get_stride(), IB, idx, IS_MMAPPED, len, malloc, mem, MEM_TO_CHUNK, n, NEXT_CHUNK, offset, p, set_size(), SIZE_ALIGN, SIZE_MAX, start, t, and UNIT.
Referenced by memalign(), and posix_memalign().