Fennix Userspace: Userspace/apps/base/busybox/libbb/getopt32.c File Reference
getopt32.c File Reference
#include "libbb.h"
Data Structures
struct t_complementary
Macros
#define vgetopt32(argv, applet_opts, applet_long_options, p) vgetopt32(argv,applet_opts,p)
#define SHOW_USAGE_IF_ERROR 1
Enumerations
enum { PARAM_STRING , PARAM_LIST , PARAM_INT }
Functions
static uint32_t vgetopt32 (char **argv, const char *applet_opts, const char *applet_long_options, va_list p)
uint32_t FAST_FUNC getopt32 (char **argv, const char *applet_opts,...)
Variables
const char *const bb_argv_dash[] ALIGN_PTR = { "-", NULL }
uint32_t option_mask32
Data Structure Documentation
t_complementary
struct t_complementary
Definition at line 307 of file getopt32.c.
Data Fields
int * counter
unsigned incongruously
unsigned char opt_char
void ** optarg
smallint param_type
unsigned requires
unsigned switch_off
unsigned switch_on
Macro Definition Documentation
SHOW_USAGE_IF_ERROR
#define SHOW_USAGE_IF_ERROR 1
vgetopt32
#define vgetopt32 (argv, applet_opts, applet_long_options, p) vgetopt32(argv,applet_opts,p)
Definition at line 325 of file getopt32.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PARAM_STRING
PARAM_LIST
PARAM_INT
Definition at line 301 of file getopt32.c.
      {
     PARAM_STRING,
     PARAM_LIST,
     PARAM_INT,
 };
Function Documentation
getopt32()
uint32_t FAST_FUNC getopt32 (char ** argv, const char * applet_opts, ...)
Definition at line 599 of file getopt32.c.
 {
     uint32_t opt;
     va_list p;
     va_start(p, applet_opts);
     opt = vgetopt32(argv, applet_opts, NULL, p);
     va_end(p);
     return opt;
 }
References argv, NULL, opt, p, va_end, va_start, and vgetopt32.
Referenced by acpid_main(), adjtimex_main(), ar_main(), arp_main(), awk_main(), basename_main(), blkdiscard_main(), bzip2_main(), cal_main(), cat_main(), chat_main(), chmod_main(), chpst_main(), chrt_main(), cksum_main(), cmp_main(), comm_main(), cp_main(), crond_main(), crontab_main(), cut_main(), depmod_main(), df_main(), dmesg_main(), dnsd_main(), dos2unix_main(), dpkg_deb_main(), du_main(), ed_main(), eject_main(), ether_wake_main(), fakeidentd_main(), fallocate_main(), fbsplash_main(), fdformat_main(), fdisk_main(), find_main(), flash_eraseall_main(), flashcp_main(), fold_main(), fsck_minix_main(), ftpd_main(), ftpgetput_main(), fuser_main(), getopt_main(), getopt_mk_fifo_nod(), getsebool_main(), grep_main(), gzip_main(), halt_main(), hexedit_main(), hostname_main(), httpd_main(), id_main(), ifplugd_main(), ifupdown_main(), inetd_main(), insmod_main(), ionice_main(), iostat_main(), ipcs_main(), kbd_mode_main(), klogd_main(), last_main(), less_main(), link_main(), ln_main(), logger_main(), login_main(), logread_main(), losetup_main(), lpqr_main(), lsattr_main(), lspci_main(), lzop_main(), makemime_main(), man_main(), matchpathcon_main(), md5_sha1_sum_main(), mdev_main(), microcom_main(), mkfs_ext2_main(), mkfs_minix_main(), mkfs_reiser_main(), mkfs_vfat_main(), mkswap_main(), mktemp_main(), modinfo_main(), more_main(), mount_main(), mountpoint_main(), mpstat_main(), nameif_main(), nandwrite_main(), nc_main(), netstat_main(), nmeter_main(), ntp_init(), openvt_main(), parse_args(), partprobe_main(), passwd_main(), paste_main(), patch_main(), pgrep_main(), pidof_main(), pmap_main(), popmaildir_main(), ps_main(), pscan_main(), pstree_main(), pwd_main(), pwdx_main(), rdate_main(), readlink_main(), readprofile_main(), reformime_main(), rev_main(), rm_main(), rmmod_main(), route_main(), runsvdir_main(), sendmail_main(), seq_main(), sestatus_main(), setarch_main(), setconsole_main(), setfattr_main(), setfiles_main(), setserial_main(), setsid_main(), showkey_main(), shred_main(), shuf_main(), slattach_main(), sort_main(), split_main(), ssl_client_main(), stat_main(), strings_main(), su_main(), sulogin_main(), sum_main(), svlogd_main(), swap_on_off_main(), switch_root_main(), sysctl_main(), syslogd_main(), tac_main(), tail_main(), taskset_main(), tcpudpsvd_main(), tee_main(), telnet_main(), telnetd_main(), time_main(), timeout_main(), top_main(), tr_main(), traceroute_init(), truncate_main(), ts_main(), tty_main(), tunctl_main(), tune2fs_main(), ubi_tools_main(), udhcpd_main(), umount_main(), uniq_main(), unlink_main(), uptime_main(), uuencode_main(), vi_main(), vlock_main(), watch_main(), watchdog_main(), wc_main(), which_main(), who_main(), whois_main(), and xxd_main().
vgetopt32()
static uint32_t vgetopt32 (char ** argv, const char * applet_opts, const char * applet_long_options, va_list p) static
Definition at line 332 of file getopt32.c.
 {
     int argc;
     unsigned flags = 0;
     unsigned requires = 0;
     unsigned len;
     t_complementary complementary[33]; /* last stays zero-filled */
     char dont_die_flag;
     int c;
     const unsigned char *s;
     const char *opt_complementary;
     t_complementary *on_off;
 #if ENABLE_LONG_OPTS
     const struct option *l_o;
     struct option *long_options = (struct option *) &bb_null_long_options;
 #endif
     unsigned trigger;
     int min_arg = 0;
     int max_arg = -1;
     int spec_flgs = 0;
 #define SHOW_USAGE_IF_ERROR     1
     on_off = complementary;
     memset(on_off, 0, sizeof(complementary));
     len = strlen(applet_opts);
     /* skip bbox extension */
     opt_complementary = NULL;
     if (applet_opts[0] == '^') {
         applet_opts++;
         /* point it past terminating NUL */
         opt_complementary = applet_opts + len;
     }
     /* skip another bbox extension */
     dont_die_flag = applet_opts[0];
     if (dont_die_flag == '!')
         applet_opts++;
     applet_opts = strcpy(alloca(len + 1), applet_opts);
     /* skip GNU extension */
     s = (const unsigned char *)applet_opts;
     if (*s == '+' || *s == '-')
         s++;
     c = 0;
     while (*s) {
         if (c >= 32)
             break;
         on_off->opt_char = *s;
         on_off->switch_on = (1U << c);
         if (*++s == ':') {
             on_off->optarg = va_arg(p, void **);
             if (s[1] == '+' || s[1] == '*') {
                 /* 'o:+' or 'o:*' */
                 on_off->param_type = (s[1] == '+') ?
                     PARAM_INT : PARAM_LIST;
                 overlapping_strcpy((char*)s + 1, (char*)s + 2);
             }
             /* skip possible 'o::' (or 'o:+:' !) */
             while (*++s == ':')
                 continue;
         }
         on_off++;
         c++;
     }
 #if ENABLE_LONG_OPTS
     if (applet_long_options) {
         const char *optstr;
         unsigned i, count;
         count = 1;
         optstr = applet_long_options;
         while (optstr[0]) {
             optstr += strlen(optstr) + 3; /* skip NUL, has_arg, val */
             count++;
         }
         /* count == no. of longopts + 1 */
         long_options = alloca(count * sizeof(*long_options));
         memset(long_options, 0, count * sizeof(*long_options));
         i = 0;
         optstr = applet_long_options;
         while (--count) {
             long_options[i].name = optstr;
             optstr += strlen(optstr) + 1;
             long_options[i].has_arg = (unsigned char)(*optstr++);
             /* long_options[i].flag = NULL; */
             long_options[i].val = (unsigned char)(*optstr++);
             i++;
         }
         for (l_o = long_options; l_o->name; l_o++) {
             if (l_o->flag)
                 continue;
             for (on_off = complementary; on_off->opt_char; on_off++)
                 if (on_off->opt_char == l_o->val)
                     goto next_long;
             if (c >= 32)
                 break;
             on_off->opt_char = l_o->val;
             on_off->switch_on = (1U << c);
             if (l_o->has_arg != no_argument)
                 on_off->optarg = va_arg(p, void **);
             c++;
  next_long: ;
         }
     }
 #endif /* ENABLE_LONG_OPTS */
     s = (const unsigned char *)opt_complementary;
     if (s) for (; *s; s++) {
         t_complementary *pair;
         unsigned *pair_switch;
         if (*s == ':')
             continue;
         c = s[1];
         if (*s == '?') {
             if (c < '0' || c > '9') {
                 spec_flgs |= SHOW_USAGE_IF_ERROR;
             } else {
                 max_arg = c - '0';
                 s++;
             }
             continue;
         }
         if (*s == '-') {
             if (c >= '0' && c <= '9') {
                 min_arg = c - '0';
                 s++;
             }
             continue;
         }
         if (*s == '=') {
             min_arg = max_arg = c - '0';
             s++;
             continue;
         }
         for (on_off = complementary; on_off->opt_char; on_off++)
             if (on_off->opt_char == *s)
                 goto found_opt;
         /* Without this, diagnostic of such bugs is not easy */
         bb_error_msg_and_die("NO OPT %c!", *s);
  found_opt:
         if (c == ':' && s[2] == ':') {
             on_off->param_type = PARAM_LIST;
             continue;
         }
         if (c == '+' && (s[2] == ':' || s[2] == '\0')) {
             on_off->param_type = PARAM_INT;
             s++;
             continue;
         }
         if (c == ':' || c == '\0') {
             requires |= on_off->switch_on;
             continue;
         }
         if (c == '-' && (s[2] == ':' || s[2] == '\0')) {
             flags |= on_off->switch_on;
             on_off->incongruously |= on_off->switch_on;
             s++;
             continue;
         }
         if (c == *s) {
             on_off->counter = va_arg(p, int *);
             s++;
         }
         pair = on_off;
         pair_switch = &pair->switch_on;
         for (s++; *s && *s != ':'; s++) {
             if (*s == '?') {
                 pair_switch = &pair->requires;
             } else if (*s == '-') {
                 if (pair_switch == &pair->switch_off)
                     pair_switch = &pair->incongruously;
                 else
                     pair_switch = &pair->switch_off;
             } else {
                 for (on_off = complementary; on_off->opt_char; on_off++)
                     if (on_off->opt_char == *s) {
                         *pair_switch |= on_off->switch_on;
                         break;
                     }
             }
         }
         s--;
     }
     /* In case getopt32 was already called:
      * reset libc getopt() internal state.
      * run_nofork_applet() does this, but we might end up here
      * also via gunzip_main() -> gzip_main(). Play safe.
      */
     GETOPT_RESET();
     /* skip 0: some applets cheat: they do not actually HAVE argv[0] */
     argc = 1 + string_array_len(argv + 1);
     /* Note: just "getopt() <= 0" will not work well for
      * "fake" short options, like this one:
      * wget $'-\203' "Test: test" http://kernel.org/
      * (supposed to act as --header, but doesn't) */
 #if ENABLE_LONG_OPTS
     while ((c = getopt_long(argc, argv, applet_opts,
             long_options, NULL)) != -1) {
 #else
     while ((c = getopt(argc, argv, applet_opts)) != -1) {
 #endif
         /* getopt prints "option requires an argument -- X"
          * and returns '?' if an option has no arg, but one is reqd */
         c &= 0xff; /* fight libc's sign extension */
         for (on_off = complementary; on_off->opt_char != c; on_off++) {
             /* c can be NUL if long opt has non-NULL ->flag,
              * but we construct long opts so that flag
              * is always NULL (see above) */
             if (on_off->opt_char == '\0' /* && c != '\0' */) {
                 /* c is probably '?' - "bad option" */
                 goto error;
             }
         }
         if (flags & on_off->incongruously)
             goto error;
         trigger = on_off->switch_on & on_off->switch_off;
         flags &= ~(on_off->switch_off ^ trigger);
         flags |= on_off->switch_on ^ trigger;
         flags ^= trigger;
         if (on_off->counter)
             (*(on_off->counter))++;
         if (optarg) {
             if (on_off->param_type == PARAM_LIST) {
                 llist_add_to_end((llist_t **)(on_off->optarg), optarg);
             } else if (on_off->param_type == PARAM_INT) {
 //TODO: xatoi_positive indirectly pulls in printf machinery
                 *(unsigned*)(on_off->optarg) = xatoi_positive(optarg);
             } else if (on_off->optarg) {
                 *(char **)(on_off->optarg) = optarg;
             }
         }
     }
     /* check depending requires for given options */
     for (on_off = complementary; on_off->opt_char; on_off++) {
         if (on_off->requires
          && (flags & on_off->switch_on)
          && (flags & on_off->requires) == 0
         ) {
             goto error;
         }
     }
     if (requires && (flags & requires) == 0)
         goto error;
     argc -= optind;
     if (argc < min_arg || (max_arg >= 0 && argc > max_arg))
         goto error;
     option_mask32 = flags;
     return flags;
  error:
     if (dont_die_flag != '!')
         bb_show_usage();
     return (int32_t)-1;
 }
References alloca, argc, argv, bb_error_msg_and_die(), bb_show_usage(), c, count, error, FAST_FUNC, option::flag, flags, getopt(), getopt_long(), GETOPT_RESET, option::has_arg, i, t_complementary::incongruously, llist_add_to_end(), memset(), option::name, no_argument, NULL, on_off(), optarg, optind, option_mask32, overlapping_strcpy(), p, PARAM_INT, PARAM_LIST, t_complementary::requires, s, SHOW_USAGE_IF_ERROR, strcpy(), string_array_len(), strlen(), t_complementary::switch_off, t_complementary::switch_on, va_arg, option::val, and xatoi_positive().
Variable Documentation
ALIGN_PTR
const char* const bb_argv_dash [] ALIGN_PTR = { "-", NULL }
Definition at line 299 of file getopt32.c.
Referenced by action_compat(), get_console_fd_or_die(), get_old_name(), hide_special_symbols(), man_main(), reset_main(), and rtnl_rtprot_initialize().
option_mask32
uint32_t option_mask32
Definition at line 318 of file getopt32.c.
Referenced by acpid_main(), act(), add_client_options(), add_probe(), adjust_column(), apply_one_hunk(), arp_del(), arp_getdevhw(), arp_set(), arp_show(), at_end(), bb_alphasort(), bbunpack(), buffer_down(), buffer_fill_and_print(), buffer_print(), buffer_up(), bzip2_main(), cal_main(), calc_name_len(), cap_cur_fline(), catcher(), change_filedir_context(), chcon_main(), chpst_main(), compare_keys(), conspy_main(), cut_file(), depmod_main(), detect_link(), diff(), diff_main(), diffreg(), display(), display_files(), display_single(), do_lzo_compress(), do_modprobe(), do_stat(), do_syslogd(), doit(), download_one_url(), dpkg_main(), du(), dump(), dump_strings(), dump_tree(), edir(), fetch(), fgets_trim_sanitize(), fileAction(), finish(), fold_main(), fuser_main(), get_boot(), get_logname(), getopt_main(), getty_main(), grep_dir(), grep_file(), grep_main(), gzip_main(), id_main(), IF_DESKTOP(), init_tty_attrs(), iter(), keypress_process(), less_main(), list_attributes(), load_modules_dep(), ls_main(), lsattr_args(), lsattr_dir_proc(), lzo_decompress(), lzo_set_method(), lzop_main(), make_new_name_lzop(), maybe_up_new_iface(), mkfs_ext2_main(), mkfs_reiser_main(), modinfo(), modinfo_main(), mount_it_now(), mount_main(), my_stat(), nc_main(), ntp_init(), ntpd_main(), number_process(), open_next_file(), packet4_ok(), parse(), passwd_study(), patch_main(), print(), print_common(), print_inet_line(), print_line(), print_name(), print_stats_dev_struct(), print_status(), progress(), progress_newline(), query(), read_lines(), read_token(), readLines(), recv_and_process_peer_pkt(), recv_pack(), retrieve_file_data(), run_parts_main(), run_pipe(), run_script(), runsv(), scan_and_display_dirs_recur(), scan_one_dir(), scan_proc_net_or_maps(), scan_recursive(), screen_char(), search_dev_inode(), send_d6_discover(), send_pack(), send_probe(), set_shell(), showkey_main(), sort_main(), status_print(), stone(), strings_main(), swap_on_off_main(), sysctl_act_on_setting(), sysctl_act_recursive(), sysctl_main(), syslogd_main(), timestamp_and_log(), timestamp_and_log_internal(), top_main(), tree_equal(), udhcpc6_main(), unix_do_one(), unpack_package(), update_local_clock(), vgetopt32(), vlock_main(), wget_main(), which_main(), write_block(), writeline(), writeLines(), xargs_exec(), and xgroup_study().