Fennix: Userspace/apps/base/busybox/modutils/modutils-24.c File Reference
modutils-24.c File Reference
#include "libbb.h"
#include "modutils.h"
#include <sys/utsname.h>
#include <elf.h>
#include <endian.h>
Data Structures
struct new_module_symbol
struct new_module_ref
struct new_module
struct new_module_info
struct obj_section
struct obj_symbol
struct obj_file
struct obj_string_patch
struct obj_symbol_patch
struct arch_file
struct arch_symbol
struct external_module
Macros
#define LOADBITS 1
#define tgt_sizeof_char sizeof(char)
#define tgt_sizeof_short sizeof(short)
#define tgt_sizeof_int sizeof(int)
#define tgt_sizeof_long sizeof(long)
#define tgt_sizeof_char_p sizeof(char *)
#define tgt_sizeof_void_p sizeof(void *)
#define tgt_long long
#define ARCHDATA_SEC_NAME "__archdata"
#define KALLSYMS_SEC_NAME "__kallsyms"
#define ElfW(x) Elf32_ ## x
#define ELFW(x) ELF32_ ## x
#define ELF32_ST_INFO(bind, type) (((bind) << 4) + ((type) & 0xf))
#define ELF64_ST_INFO(bind, type) (((bind) << 4) + ((type) & 0xf))
#define ELF_ST_BIND(info) ELFW(ST_BIND)(info)
#define ELF_ST_TYPE(info) ELFW(ST_TYPE)(info)
#define ELF_ST_INFO(bind, type) ELFW(ST_INFO)(bind, type)
#define ELF_R_TYPE(val) ELFW(R_TYPE)(val)
#define ELF_R_SYM(val) ELFW(R_SYM)(val)
#define HASH_BUCKETS 521
#define SPFX ""
#define flag_force_load (option_mask32 & INSMOD_OPT_FORCE)
#define flag_autoclean (option_mask32 & INSMOD_OPT_KERNELD)
#define flag_verbose (option_mask32 & INSMOD_OPT_VERBOSE)
#define flag_quiet (option_mask32 & INSMOD_OPT_SILENT)
#define flag_noexport (option_mask32 & INSMOD_OPT_NO_EXPORT)
#define flag_print_load_map (option_mask32 & INSMOD_OPT_PRINT_MAP)
#define ELFMAG_U32 ((uint32_t)((((ELFMAG0 * 0x100) + ELFMAG1) * 0x100 + ELFMAG2) * 0x100 + ELFMAG3))
#define check_tainted_module(x, y) do { } while (0);
Enumerations
enum {
NEW_MOD_RUNNING = 1 , NEW_MOD_DELETED = 2 , NEW_MOD_AUTOCLEAN = 4 , NEW_MOD_VISITED = 8 ,
NEW_MOD_USED_ONCE = 16
}
enum {
QM_MODULES = 1 , QM_DEPS = 2 , QM_REFS = 3 , QM_SYMBOLS = 4 ,
QM_INFO = 5
}
enum obj_reloc { obj_reloc_ok , obj_reloc_overflow , obj_reloc_dangerous , obj_reloc_unhandled }
Functions
int init_module (const char *name, const struct new_module *)
int query_module (const char *name, int which, void *buf, size_t bufsize, size_t *ret)
unsigned long create_module (const char *, size_t)
int delete_module (const char *module, unsigned int flags)
static unsigned long FAST_FUNC obj_elf_hash (const char *)
static unsigned long obj_elf_hash_n (const char *, unsigned long len)
static struct obj_symbol * obj_find_symbol (struct obj_file *f, const char *name)
static ElfW (Addr)
static struct obj_file * arch_new_file (void)
static struct obj_section * arch_new_section (void)
static struct obj_symbol * arch_new_symbol (void)
static enum obj_reloc arch_apply_relocation (struct obj_file *f, struct obj_section *targsec, struct obj_symbol *sym, ElfW(RelM) *rel, ElfW(Addr) v)
static void arch_create_got (struct obj_file *f)
static struct obj_symbol * obj_add_symbol (struct obj_file *f, const char *name, unsigned long symidx, int info, int secidx, ElfW(Addr) value, unsigned long size)
static struct obj_section * obj_find_section (struct obj_file *f, const char *name)
static int obj_load_order_prio (struct obj_section *a)
static void obj_insert_section_load_order (struct obj_file *f, struct obj_section *sec)
static struct obj_section * helper_create_alloced_section (struct obj_file *f, const char *name, unsigned long align, unsigned long size)
static struct obj_section * obj_create_alloced_section (struct obj_file *f, const char *name, unsigned long align, unsigned long size)
static struct obj_section * obj_create_alloced_section_first (struct obj_file *f, const char *name, unsigned long align, unsigned long size)
static void * obj_extend_section (struct obj_section *sec, unsigned long more)
static int add_symbols_from (struct obj_file *f, int idx, struct new_module_symbol *syms, size_t nsyms)
static void add_kernel_symbols (struct obj_file *f)
static char * get_modinfo_value (struct obj_file *f, const char *key)
static char * next_arg (char *args, char **param, char **val)
static void new_process_module_arguments (struct obj_file *f, const char *options)
static void new_get_kernel_symbols (void)
static int new_is_kernel_checksummed (void)
static void new_create_this_module (struct obj_file *f, const char *m_name)
static int new_create_module_ksymtab (struct obj_file *f)
static int new_init_module (const char *m_name, struct obj_file *f, unsigned long m_size)
static void obj_string_patch (struct obj_file *f, int secidx, ElfW(Addr) offset, const char *string)
static void obj_symbol_patch (struct obj_file *f, int secidx, ElfW(Addr) offset, struct obj_symbol *sym)
static void obj_check_undefineds (struct obj_file *f)
static void obj_allocate_commons (struct obj_file *f)
static unsigned long obj_load_size (struct obj_file *f)
static int obj_relocate (struct obj_file *f, ElfW(Addr) base)
static int obj_create_image (struct obj_file *f, char *image)
static struct obj_file * obj_load (char *image, size_t image_size, int loadprogbits)
static void hide_special_symbols (struct obj_file *f)
static void print_load_map (struct obj_file *f UNUSED_PARAM)
int FAST_FUNC bb_init_module_24 (const char *m_filename, const char *options)
Variables
static struct new_module_symbol * ksyms
static size_t nksyms
static struct external_module * ext_modules
static int n_ext_modules
static int n_ext_modules_used
Data Structure Documentation
new_module_symbol
struct new_module_symbol
Definition at line 376 of file modutils-24.c.
Data Fields
unsigned long name
unsigned long value
new_module_ref
struct new_module_ref
Definition at line 383 of file modutils-24.c.
Data Fields
unsigned tgt_long dep
unsigned tgt_long next_ref
unsigned tgt_long ref
new_module
struct new_module
Definition at line 389 of file modutils-24.c.
Data Fields
const char * archdata_end
const char * archdata_start
unsigned tgt_long can_unload
unsigned tgt_long cleanup
unsigned tgt_long deps
unsigned tgt_long ex_table_end
unsigned tgt_long ex_table_start
unsigned tgt_long flags
unsigned tgt_long init
const char * kallsyms_end
const char * kallsyms_start
const char * kernel_data
unsigned tgt_long name
unsigned ndeps
unsigned tgt_long next
unsigned nsyms
unsigned tgt_long persist_end
unsigned tgt_long persist_start
unsigned tgt_long refs
unsigned tgt_long runsize
unsigned tgt_long size
unsigned tgt_long size_of_struct
unsigned tgt_long syms
tgt_long usecount
new_module_info
struct new_module_info
Definition at line 431 of file modutils-24.c.
Data Fields
unsigned long addr
unsigned long flags
unsigned long size
long usecount
obj_section
struct obj_section
Definition at line 536 of file modutils-24.c.
obj_symbol
struct obj_symbol
Definition at line 544 of file modutils-24.c.
Data Fields
int info
int ksymidx
const char * name
struct obj_symbol * next
int referenced
int secidx
unsigned long size
unsigned long value
obj_file
struct obj_file
Definition at line 561 of file modutils-24.c.
obj_string_patch
struct obj_string_patch
Definition at line 583 of file modutils-24.c.
Data Fields
struct obj_string_patch * next
int reloc_secidx
obj_symbol_patch
struct obj_symbol_patch
Definition at line 590 of file modutils-24.c.
Data Fields
struct obj_symbol_patch * next
int reloc_secidx
arch_file
struct arch_file
Definition at line 729 of file modutils-24.c.
Data Fields
struct obj_file root
arch_symbol
struct arch_symbol
Definition at line 742 of file modutils-24.c.
Data Fields
struct obj_symbol root
external_module
struct external_module
Definition at line 757 of file modutils-24.c.
Data Fields
const char * name
Macro Definition Documentation
ARCHDATA_SEC_NAME
#define ARCHDATA_SEC_NAME "__archdata"
Definition at line 426 of file modutils-24.c.
check_tainted_module
#define check_tainted_module (x, y) do { } while (0);
Definition at line 3595 of file modutils-24.c.
ELF32_ST_INFO
#define ELF32_ST_INFO (bind, type) (((bind) << 4) + ((type) & 0xf))
Definition at line 520 of file modutils-24.c.
ELF64_ST_INFO
#define ELF64_ST_INFO (bind, type) (((bind) << 4) + ((type) & 0xf))
Definition at line 524 of file modutils-24.c.
ELF_R_SYM
#define ELF_R_SYM (val) ELFW(R_SYM)(val)
Definition at line 531 of file modutils-24.c.
ELF_R_TYPE
#define ELF_R_TYPE (val) ELFW(R_TYPE)(val)
Definition at line 530 of file modutils-24.c.
ELF_ST_BIND
#define ELF_ST_BIND (info) ELFW(ST_BIND)(info)
Definition at line 527 of file modutils-24.c.
ELF_ST_INFO
#define ELF_ST_INFO (bind, type) ELFW(ST_INFO)(bind, type)
Definition at line 529 of file modutils-24.c.
ELF_ST_TYPE
#define ELF_ST_TYPE (info) ELFW(ST_TYPE)(info)
Definition at line 528 of file modutils-24.c.
ELFMAG_U32
#define ELFMAG_U32 ((uint32_t)((((ELFMAG0 * 0x100) + ELFMAG1) * 0x100 + ELFMAG2) * 0x100 + ELFMAG3))
ElfW
#define ElfW (x) Elf32_ ## x
Definition at line 510 of file modutils-24.c.
ELFW
#define ELFW (x) ELF32_ ## x
Definition at line 511 of file modutils-24.c.
flag_autoclean
#define flag_autoclean (option_mask32 & INSMOD_OPT_KERNELD)
Definition at line 692 of file modutils-24.c.
flag_force_load
#define flag_force_load (option_mask32 & INSMOD_OPT_FORCE)
Definition at line 691 of file modutils-24.c.
flag_noexport
#define flag_noexport (option_mask32 & INSMOD_OPT_NO_EXPORT)
Definition at line 695 of file modutils-24.c.
flag_print_load_map
#define flag_print_load_map (option_mask32 & INSMOD_OPT_PRINT_MAP)
Definition at line 696 of file modutils-24.c.
flag_quiet
#define flag_quiet (option_mask32 & INSMOD_OPT_SILENT)
Definition at line 694 of file modutils-24.c.
flag_verbose
#define flag_verbose (option_mask32 & INSMOD_OPT_VERBOSE)
Definition at line 693 of file modutils-24.c.
HASH_BUCKETS
#define HASH_BUCKETS 521
Definition at line 559 of file modutils-24.c.
KALLSYMS_SEC_NAME
#define KALLSYMS_SEC_NAME "__kallsyms"
Definition at line 428 of file modutils-24.c.
LOADBITS
#define LOADBITS 1
Definition at line 70 of file modutils-24.c.
SPFX
#define SPFX ""
tgt_long
#define tgt_long long
Definition at line 357 of file modutils-24.c.
tgt_sizeof_char
#define tgt_sizeof_char sizeof(char)
Definition at line 351 of file modutils-24.c.
tgt_sizeof_char_p
#define tgt_sizeof_char_p sizeof(char *)
Definition at line 355 of file modutils-24.c.
tgt_sizeof_int
#define tgt_sizeof_int sizeof(int)
Definition at line 353 of file modutils-24.c.
tgt_sizeof_long
#define tgt_sizeof_long sizeof(long)
Definition at line 354 of file modutils-24.c.
tgt_sizeof_short
#define tgt_sizeof_short sizeof(short)
Definition at line 352 of file modutils-24.c.
tgt_sizeof_void_p
#define tgt_sizeof_void_p sizeof(void *)
Definition at line 356 of file modutils-24.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NEW_MOD_RUNNING
NEW_MOD_DELETED
NEW_MOD_AUTOCLEAN
NEW_MOD_VISITED
NEW_MOD_USED_ONCE
Definition at line 439 of file modutils-24.c.
      {
     NEW_MOD_RUNNING = 1,
     NEW_MOD_DELETED = 2,
     NEW_MOD_AUTOCLEAN = 4,
     NEW_MOD_VISITED = 8,
     NEW_MOD_USED_ONCE = 16
 };
anonymous enum
anonymous enum
Enumerator
QM_MODULES
QM_DEPS
QM_REFS
QM_SYMBOLS
QM_INFO
Definition at line 452 of file modutils-24.c.
      {
     QM_MODULES = 1,
     QM_DEPS = 2,
     QM_REFS = 3,
     QM_SYMBOLS = 4,
     QM_INFO = 5
 };
obj_reloc
enum obj_reloc
Enumerator
obj_reloc_ok
obj_reloc_overflow
obj_reloc_dangerous
obj_reloc_unhandled
Definition at line 576 of file modutils-24.c.
                {
     obj_reloc_ok,
     obj_reloc_overflow,
     obj_reloc_dangerous,
     obj_reloc_unhandled
 };
Function Documentation
add_kernel_symbols()
static void add_kernel_symbols (struct obj_file * f) static
Definition at line 2306 of file modutils-24.c.
 {
     struct external_module *m;
     int i, nused = 0;
     /* Add module symbols first.  */
     for (i = 0, m = ext_modules; i < n_ext_modules; ++i, ++m) {
         if (m->nsyms
          && add_symbols_from(f, SHN_HIRESERVE + 2 + i, m->syms, m->nsyms)
         ) {
             m->used = 1;
             ++nused;
         }
     }
     n_ext_modules_used = nused;
     /* And finally the symbols from the kernel proper.  */
     if (nksyms)
         add_symbols_from(f, SHN_HIRESERVE + 1, ksyms, nksyms);
 }
References add_symbols_from(), ext_modules, f, i, ksyms, n_ext_modules, n_ext_modules_used, nksyms, and SHN_HIRESERVE.
Referenced by bb_init_module_24().
add_symbols_from()
static int add_symbols_from (struct obj_file * f, int idx, struct new_module_symbol * syms, size_t nsyms) static
Definition at line 2229 of file modutils-24.c.
 {
     struct new_module_symbol *s;
     size_t i;
     int used = 0;
 #ifdef SYMBOL_PREFIX
     char *name_buf = NULL;
     size_t name_alloced_size = 0;
 #endif
 #if ENABLE_FEATURE_CHECK_TAINTED_MODULE
     int gpl;
     gpl = obj_gpl_license(f, NULL) == 0;
 #endif
     for (i = 0, s = syms; i < nsyms; ++i, ++s) {
         /* Only add symbols that are already marked external.
            If we override locals we may cause problems for
            argument initialization.  We will also create a false
            dependency on the module.  */
         struct obj_symbol *sym;
         char *name;
         /* GPL licensed modules can use symbols exported with
          * EXPORT_SYMBOL_GPL, so ignore any GPLONLY_ prefix on the
          * exported names.  Non-GPL modules never see any GPLONLY_
          * symbols so they cannot fudge it by adding the prefix on
          * their references.
          */
         if (is_prefixed_with((char *)s->name, "GPLONLY_")) {
 #if ENABLE_FEATURE_CHECK_TAINTED_MODULE
             if (gpl)
                 s->name += 8;
             else
 #endif
                 continue;
         }
         name = (char *)s->name;
 #ifdef SYMBOL_PREFIX
         /* Prepend SYMBOL_PREFIX to the symbol's name (the
            kernel exports 'C names', but module object files
            reference 'linker names').  */
         size_t extra = sizeof SYMBOL_PREFIX;
         size_t name_size = strlen(name) + extra;
         if (name_size > name_alloced_size) {
             name_alloced_size = name_size * 2;
             name_buf = alloca(name_alloced_size);
         }
         strcpy(name_buf, SYMBOL_PREFIX);
         strcpy(name_buf + extra - 1, name);
         name = name_buf;
 #endif
         sym = obj_find_symbol(f, name);
         if (sym && !(ELF_ST_BIND(sym->info) == STB_LOCAL)) {
 #ifdef SYMBOL_PREFIX
             /* Put NAME_BUF into more permanent storage.  */
             name = xmalloc(name_size);
             strcpy(name, name_buf);
 #endif
             sym = obj_add_symbol(f, name, -1,
                     ELF_ST_INFO(STB_GLOBAL,
                         STT_NOTYPE),
                     idx, s->value, 0);
             /* Did our symbol just get installed?  If so, mark the
                module as "used".  */
             if (sym->secidx == idx)
                 used = 1;
         }
     }
     return used;
 }
References alloca, ELF_ST_BIND, ELF_ST_INFO, f, i, idx, obj_symbol::info, is_prefixed_with(), obj_symbol::name, NULL, obj_add_symbol(), obj_find_symbol(), s, obj_symbol::secidx, STB_GLOBAL, STB_LOCAL, strcpy, strlen(), STT_NOTYPE, and xmalloc.
Referenced by add_kernel_symbols().
arch_apply_relocation()
static enum obj_reloc arch_apply_relocation (struct obj_file * f, struct obj_section * targsec, struct obj_symbol * sym, ElfW(RelM) * rel, ElfW(Addr) v) static
Definition at line 787 of file modutils-24.c.
 {
 #if defined(__arm__) || defined(__i386__) || defined(__mc68000__) \
  || defined(__sh__) || defined(__s390__) || defined(__x86_64__) \
  || defined(__powerpc__) || defined(__mips__)
     struct arch_file *ifile = (struct arch_file *) f;
 #endif
     enum obj_reloc ret = obj_reloc_ok;
     ElfW(Addr) *loc = (ElfW(Addr) *) (targsec->contents + rel->r_offset);
 #if defined(__arm__) || defined(__H8300H__) || defined(__H8300S__) \
  || defined(__i386__) || defined(__mc68000__) || defined(__microblaze__) \
  || defined(__mips__) || defined(__nios2__) || defined(__powerpc__) \
  || defined(__s390__) || defined(__sh__) || defined(__x86_64__)
     ElfW(Addr) dot = targsec->header.sh_addr + rel->r_offset;
 #endif
 #if defined(USE_GOT_ENTRIES) || defined(USE_PLT_ENTRIES)
     struct arch_symbol *isym = (struct arch_symbol *) sym;
 #endif
 #if defined(__arm__) || defined(__i386__) || defined(__mc68000__) \
  || defined(__sh__) || defined(__s390__)
 #if defined(USE_GOT_ENTRIES)
     ElfW(Addr) got = ifile->got ? ifile->got->header.sh_addr : 0;
 #endif
 #endif
 #if defined(USE_PLT_ENTRIES)
     ElfW(Addr) plt = ifile->plt ? ifile->plt->header.sh_addr : 0;
     unsigned long *ip;
 # if defined(USE_PLT_LIST)
     struct arch_list_entry *pe;
 # else
     struct arch_single_entry *pe;
 # endif
 #endif
     switch (ELF_R_TYPE(rel->r_info)) {
 #if defined(__arm__)
         case R_ARM_NONE:
             break;
         case R_ARM_ABS32:
             *loc += v;
             break;
         case R_ARM_GOT32:
             goto bb_use_got;
         case R_ARM_GOTPC:
             /* relative reloc, always to _GLOBAL_OFFSET_TABLE_
              * (which is .got) similar to branch,
              * but is full 32 bits relative */
             *loc += got - dot;
             break;
         case R_ARM_PC24:
         case R_ARM_PLT32:
             goto bb_use_plt;
         case R_ARM_GOTOFF: /* address relative to the got */
             *loc += v - got;
             break;
 #elif defined(__cris__)
         case R_CRIS_NONE:
             break;
         case R_CRIS_32:
             /* CRIS keeps the relocation value in the r_addend field and
              * should not use whats in *loc at all
              */
             *loc = v;
             break;
 #elif defined(__H8300H__) || defined(__H8300S__)
         case R_H8_DIR24R8:
             loc = (ElfW(Addr) *)((ElfW(Addr))loc - 1);
             *loc = (*loc & 0xff000000) | ((*loc & 0xffffff) + v);
             break;
         case R_H8_DIR24A8:
             *loc += v;
             break;
         case R_H8_DIR32:
         case R_H8_DIR32A16:
             *loc += v;
             break;
         case R_H8_PCREL16:
             v -= dot + 2;
             if ((ElfW(Sword))v > 0x7fff
              || (ElfW(Sword))v < -(ElfW(Sword))0x8000
             ) {
                 ret = obj_reloc_overflow;
             } else {
                 *(unsigned short *)loc = v;
             }
             break;
         case R_H8_PCREL8:
             v -= dot + 1;
             if ((ElfW(Sword))v > 0x7f
              || (ElfW(Sword))v < -(ElfW(Sword))0x80
             ) {
                 ret = obj_reloc_overflow;
             } else {
                 *(unsigned char *)loc = v;
             }
             break;
 #elif defined(__i386__)
         case R_386_NONE:
             break;
         case R_386_32:
             *loc += v;
             break;
         case R_386_PLT32:
         case R_386_PC32:
         case R_386_GOTOFF:
             *loc += v - dot;
             break;
         case R_386_GLOB_DAT:
         case R_386_JMP_SLOT:
             *loc = v;
             break;
         case R_386_RELATIVE:
             *loc += f->baseaddr;
             break;
         case R_386_GOTPC:
             *loc += got - dot;
             break;
         case R_386_GOT32:
             goto bb_use_got;
             break;
 #elif defined(__microblaze__)
         case R_MICROBLAZE_NONE:
         case R_MICROBLAZE_64_NONE:
         case R_MICROBLAZE_32_SYM_OP_SYM:
         case R_MICROBLAZE_32_PCREL:
             break;
         case R_MICROBLAZE_64_PCREL: {
             /* dot is the address of the current instruction.
              * v is the target symbol address.
              * So we need to extract the offset in the code,
              * adding v, then subtrating the current address
              * of this instruction.
              * Ex: "IMM 0xFFFE  bralid 0x0000" = "bralid 0xFFFE0000"
              */
             /* Get split offset stored in code */
             unsigned int temp = (loc[0] & 0xFFFF) << 16 |
                         (loc[1] & 0xFFFF);
             /* Adjust relative offset. -4 adjustment required
              * because dot points to the IMM insn, but branch
              * is computed relative to the branch instruction itself.
              */
             temp += v - dot - 4;
             /* Store back into code */
             loc[0] = (loc[0] & 0xFFFF0000) | temp >> 16;
             loc[1] = (loc[1] & 0xFFFF0000) | (temp & 0xFFFF);
             break;
         }
         case R_MICROBLAZE_32:
             *loc += v;
             break;
         case R_MICROBLAZE_64: {
             /* Get split pointer stored in code */
             unsigned int temp1 = (loc[0] & 0xFFFF) << 16 |
                         (loc[1] & 0xFFFF);
             /* Add reloc offset */
             temp1 += v;
             /* Store back into code */
             loc[0] = (loc[0] & 0xFFFF0000) | temp1 >> 16;
             loc[1] = (loc[1] & 0xFFFF0000) | (temp1 & 0xFFFF);
             break;
         }
         case R_MICROBLAZE_32_PCREL_LO:
         case R_MICROBLAZE_32_LO:
         case R_MICROBLAZE_SRO32:
         case R_MICROBLAZE_SRW32:
             ret = obj_reloc_unhandled;
             break;
 #elif defined(__mc68000__)
         case R_68K_NONE:
             break;
         case R_68K_32:
             *loc += v;
             break;
         case R_68K_8:
             if (v > 0xff) {
                 ret = obj_reloc_overflow;
             }
             *(char *)loc = v;
             break;
         case R_68K_16:
             if (v > 0xffff) {
                 ret = obj_reloc_overflow;
             }
             *(short *)loc = v;
             break;
         case R_68K_PC8:
             v -= dot;
             if ((ElfW(Sword))v > 0x7f
              || (ElfW(Sword))v < -(ElfW(Sword))0x80
             ) {
                 ret = obj_reloc_overflow;
             }
             *(char *)loc = v;
             break;
         case R_68K_PC16:
             v -= dot;
             if ((ElfW(Sword))v > 0x7fff
              || (ElfW(Sword))v < -(ElfW(Sword))0x8000
             ) {
                 ret = obj_reloc_overflow;
             }
             *(short *)loc = v;
             break;
         case R_68K_PC32:
             *(int *)loc = v - dot;
             break;
         case R_68K_GLOB_DAT:
         case R_68K_JMP_SLOT:
             *loc = v;
             break;
         case R_68K_RELATIVE:
             *(int *)loc += f->baseaddr;
             break;
         case R_68K_GOT32:
             goto bb_use_got;
 # ifdef R_68K_GOTOFF
         case R_68K_GOTOFF:
             *loc += v - got;
             break;
 # endif
 #elif defined(__mips__)
         case R_MIPS_NONE:
             break;
         case R_MIPS_32:
             *loc += v;
             break;
         case R_MIPS_26:
             if (v % 4)
                 ret = obj_reloc_dangerous;
             if ((v & 0xf0000000) != ((dot + 4) & 0xf0000000))
                 ret = obj_reloc_overflow;
             *loc =
                 (*loc & ~0x03ffffff) | ((*loc + (v >> 2)) &
                                         0x03ffffff);
             break;
         case R_MIPS_HI16:
             {
                 struct mips_hi16 *n;
                 /* We cannot relocate this one now because we don't know the value
                    of the carry we need to add.  Save the information, and let LO16
                    do the actual relocation.  */
                 n = xmalloc(sizeof *n);
                 n->addr = loc;
                 n->value = v;
                 n->next = ifile->mips_hi16_list;
                 ifile->mips_hi16_list = n;
                 break;
             }
         case R_MIPS_LO16:
             {
                 unsigned long insnlo = *loc;
                 ElfW(Addr) val, vallo;
                 /* Sign extend the addend we extract from the lo insn.  */
                 vallo = ((insnlo & 0xffff) ^ 0x8000) - 0x8000;
                 if (ifile->mips_hi16_list != NULL) {
                     struct mips_hi16 *l;
                     l = ifile->mips_hi16_list;
                     while (l != NULL) {
                         struct mips_hi16 *next;
                         unsigned long insn;
                         /* Do the HI16 relocation.  Note that we actually don't
                            need to know anything about the LO16 itself, except where
                            to find the low 16 bits of the addend needed by the LO16.  */
                         insn = *l->addr;
                         val =
                             ((insn & 0xffff) << 16) +
                             vallo;
                         val += v;
                         /* Account for the sign extension that will happen in the
                            low bits.  */
                         val =
                             ((val >> 16) +
                              ((val & 0x8000) !=
                               0)) & 0xffff;
                         insn = (insn & ~0xffff) | val;
                         *l->addr = insn;
                         next = l->next;
                         free(l);
                         l = next;
                     }
                     ifile->mips_hi16_list = NULL;
                 }
                 /* Ok, we're done with the HI16 relocs.  Now deal with the LO16.  */
                 val = v + vallo;
                 insnlo = (insnlo & ~0xffff) | (val & 0xffff);
                 *loc = insnlo;
                 break;
             }
 #elif defined(__nios2__)
         case R_NIOS2_NONE:
             break;
         case R_NIOS2_BFD_RELOC_32:
             *loc += v;
             break;
         case R_NIOS2_BFD_RELOC_16:
             if (v > 0xffff) {
                 ret = obj_reloc_overflow;
             }
             *(short *)loc = v;
             break;
         case R_NIOS2_BFD_RELOC_8:
             if (v > 0xff) {
                 ret = obj_reloc_overflow;
             }
             *(char *)loc = v;
             break;
         case R_NIOS2_S16:
             {
                 Elf32_Addr word;
                 if ((Elf32_Sword)v > 0x7fff
                  || (Elf32_Sword)v < -(Elf32_Sword)0x8000
                 ) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc;
                 *loc = ((((word >> 22) << 16) | (v & 0xffff)) << 6) |
                        (word & 0x3f);
             }
             break;
         case R_NIOS2_U16:
             {
                 Elf32_Addr word;
                 if (v > 0xffff) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc;
                 *loc = ((((word >> 22) << 16) | (v & 0xffff)) << 6) |
                        (word & 0x3f);
             }
             break;
         case R_NIOS2_PCREL16:
             {
                 Elf32_Addr word;
                 v -= dot + 4;
                 if ((Elf32_Sword)v > 0x7fff
                  || (Elf32_Sword)v < -(Elf32_Sword)0x8000
                 ) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc;
                 *loc = ((((word >> 22) << 16) | (v & 0xffff)) << 6) | (word & 0x3f);
             }
             break;
         case R_NIOS2_GPREL:
             {
                 Elf32_Addr word, gp;
                 /* get _gp */
                 gp = obj_symbol_final_value(f, obj_find_symbol(f, SPFX "_gp"));
                 v -= gp;
                 if ((Elf32_Sword)v > 0x7fff
                  || (Elf32_Sword)v < -(Elf32_Sword)0x8000
                 ) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc;
                 *loc = ((((word >> 22) << 16) | (v & 0xffff)) << 6) | (word & 0x3f);
             }
             break;
         case R_NIOS2_CALL26:
             if (v & 3)
                 ret = obj_reloc_dangerous;
             if ((v >> 28) != (dot >> 28))
                 ret = obj_reloc_overflow;
             *loc = (*loc & 0x3f) | ((v >> 2) << 6);
             break;
         case R_NIOS2_IMM5:
             {
                 Elf32_Addr word;
                 if (v > 0x1f) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc & ~0x7c0;
                 *loc = word | ((v & 0x1f) << 6);
             }
             break;
         case R_NIOS2_IMM6:
             {
                 Elf32_Addr word;
                 if (v > 0x3f) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc & ~0xfc0;
                 *loc = word | ((v & 0x3f) << 6);
             }
             break;
         case R_NIOS2_IMM8:
             {
                 Elf32_Addr word;
                 if (v > 0xff) {
                     ret = obj_reloc_overflow;
                 }
                 word = *loc & ~0x3fc0;
                 *loc = word | ((v & 0xff) << 6);
             }
             break;
         case R_NIOS2_HI16:
             {
                 Elf32_Addr word;
                 word = *loc;
                 *loc = ((((word >> 22) << 16) | ((v >>16) & 0xffff)) << 6) |
                        (word & 0x3f);
             }
             break;
         case R_NIOS2_LO16:
             {
                 Elf32_Addr word;
                 word = *loc;
                 *loc = ((((word >> 22) << 16) | (v & 0xffff)) << 6) |
                        (word & 0x3f);
             }
             break;
         case R_NIOS2_HIADJ16:
             {
                 Elf32_Addr word1, word2;
                 word1 = *loc;
                 word2 = ((v >> 16) + ((v >> 15) & 1)) & 0xffff;
                 *loc = ((((word1 >> 22) << 16) | word2) << 6) |
                        (word1 & 0x3f);
             }
             break;
 #elif defined(__powerpc64__)
         /* PPC64 needs a 2.6 kernel, 2.4 module relocation irrelevant */
 #elif defined(__powerpc__)
         case R_PPC_ADDR16_HA:
             *(unsigned short *)loc = (v + 0x8000) >> 16;
             break;
         case R_PPC_ADDR16_HI:
             *(unsigned short *)loc = v >> 16;
             break;
         case R_PPC_ADDR16_LO:
             *(unsigned short *)loc = v;
             break;
         case R_PPC_REL24:
             goto bb_use_plt;
         case R_PPC_REL32:
             *loc = v - dot;
             break;
         case R_PPC_ADDR32:
             *loc = v;
             break;
 #elif defined(__s390__)
         case R_390_32:
             *(unsigned int *) loc += v;
             break;
         case R_390_16:
             *(unsigned short *) loc += v;
             break;
         case R_390_8:
             *(unsigned char *) loc += v;
             break;
         case R_390_PC32:
             *(unsigned int *) loc += v - dot;
             break;
         case R_390_PC16DBL:
             *(unsigned short *) loc += (v - dot) >> 1;
             break;
         case R_390_PC16:
             *(unsigned short *) loc += v - dot;
             break;
         case R_390_PLT32:
         case R_390_PLT16DBL:
             /* find the plt entry and initialize it.  */
             pe = (struct arch_single_entry *) &isym->pltent;
             if (pe->inited == 0) {
                 ip = (unsigned long *)(ifile->plt->contents + pe->offset);
                 ip[0] = 0x0d105810; /* basr 1,0; lg 1,10(1); br 1 */
                 ip[1] = 0x100607f1;
                 if (ELF_R_TYPE(rel->r_info) == R_390_PLT16DBL)
                     ip[2] = v - 2;
                 else
                     ip[2] = v;
                 pe->inited = 1;
             }
             /* Insert relative distance to target.  */
             v = plt + pe->offset - dot;
             if (ELF_R_TYPE(rel->r_info) == R_390_PLT32)
                 *(unsigned int *) loc = (unsigned int) v;
             else if (ELF_R_TYPE(rel->r_info) == R_390_PLT16DBL)
                 *(unsigned short *) loc = (unsigned short) ((v + 2) >> 1);
             break;
         case R_390_GLOB_DAT:
         case R_390_JMP_SLOT:
             *loc = v;
             break;
         case R_390_RELATIVE:
             *loc += f->baseaddr;
             break;
         case R_390_GOTPC:
             *(unsigned long *) loc += got - dot;
             break;
         case R_390_GOT12:
         case R_390_GOT16:
         case R_390_GOT32:
             if (!isym->gotent.inited)
             {
                 isym->gotent.inited = 1;
                 *(ElfW(Addr) *)(ifile->got->contents + isym->gotent.offset) = v;
             }
             if (ELF_R_TYPE(rel->r_info) == R_390_GOT12)
                 *(unsigned short *) loc |= (*(unsigned short *) loc + isym->gotent.offset) & 0xfff;
             else if (ELF_R_TYPE(rel->r_info) == R_390_GOT16)
                 *(unsigned short *) loc += isym->gotent.offset;
             else if (ELF_R_TYPE(rel->r_info) == R_390_GOT32)
                 *(unsigned int *) loc += isym->gotent.offset;
             break;
 # ifndef R_390_GOTOFF32
 #  define R_390_GOTOFF32 R_390_GOTOFF
 # endif
         case R_390_GOTOFF32:
             *loc += v - got;
             break;
 #elif defined(__sh__)
         case R_SH_NONE:
             break;
         case R_SH_DIR32:
             *loc += v;
             break;
         case R_SH_REL32:
             *loc += v - dot;
             break;
         case R_SH_PLT32:
             *loc = v - dot;
             break;
         case R_SH_GLOB_DAT:
         case R_SH_JMP_SLOT:
             *loc = v;
             break;
         case R_SH_RELATIVE:
             *loc = f->baseaddr + rel->r_addend;
             break;
         case R_SH_GOTPC:
             *loc = got - dot + rel->r_addend;
             break;
         case R_SH_GOT32:
             goto bb_use_got;
         case R_SH_GOTOFF:
             *loc = v - got;
             break;
 # if defined(__SH5__)
         case R_SH_IMM_MEDLOW16:
         case R_SH_IMM_LOW16:
             {
                 ElfW(Addr) word;
                 if (ELF_R_TYPE(rel->r_info) == R_SH_IMM_MEDLOW16)
                     v >>= 16;
                 /*
                  *  movi and shori have the format:
                  *
                  *  |  op  | imm  | reg | reserved |
                  *   31..26 25..10 9.. 4 3   ..   0
                  *
                  * so we simply mask and or in imm.
                  */
                 word = *loc & ~0x3fffc00;
                 word |= (v & 0xffff) << 10;
                 *loc = word;
                 break;
             }
         case R_SH_IMM_MEDLOW16_PCREL:
         case R_SH_IMM_LOW16_PCREL:
             {
                 ElfW(Addr) word;
                 word = *loc & ~0x3fffc00;
                 v -= dot;
                 if (ELF_R_TYPE(rel->r_info) == R_SH_IMM_MEDLOW16_PCREL)
                     v >>= 16;
                 word |= (v & 0xffff) << 10;
                 *loc = word;
                 break;
             }
 # endif /* __SH5__ */
 #elif defined(__v850e__)
         case R_V850_NONE:
             break;
         case R_V850_32:
             /* We write two shorts instead of a long because even
                32-bit insns only need half-word alignment, but
                32-bit data needs to be long-word aligned.  */
             v += ((unsigned short *)loc)[0];
             v += ((unsigned short *)loc)[1] << 16;
             ((unsigned short *)loc)[0] = v & 0xffff;
             ((unsigned short *)loc)[1] = (v >> 16) & 0xffff;
             break;
         case R_V850_22_PCREL:
             goto bb_use_plt;
 #elif defined(__x86_64__)
         case R_X86_64_NONE:
             break;
         case R_X86_64_64:
             *loc += v;
             break;
         case R_X86_64_32:
             *(unsigned int *) loc += v;
             if (v > 0xffffffff)
             {
                 ret = obj_reloc_overflow; /* Kernel module compiled without -mcmodel=kernel. */
                 /* error("Possibly is module compiled without -mcmodel=kernel!"); */
             }
             break;
         case R_X86_64_32S:
             *(signed int *) loc += v;
             break;
         case R_X86_64_16:
             *(unsigned short *) loc += v;
             break;
         case R_X86_64_8:
             *(unsigned char *) loc += v;
             break;
         case R_X86_64_PC32:
             *(unsigned int *) loc += v - dot;
             break;
         case R_X86_64_PC16:
             *(unsigned short *) loc += v - dot;
             break;
         case R_X86_64_PC8:
             *(unsigned char *) loc += v - dot;
             break;
         case R_X86_64_GLOB_DAT:
         case R_X86_64_JUMP_SLOT:
             *loc = v;
             break;
         case R_X86_64_RELATIVE:
             *loc += f->baseaddr;
             break;
         case R_X86_64_GOT32:
         case R_X86_64_GOTPCREL:
             goto bb_use_got;
 # if 0
             if (!isym->gotent.reloc_done)
             {
                 isym->gotent.reloc_done = 1;
                 *(Elf64_Addr *)(ifile->got->contents + isym->gotent.offset) = v;
             }
             /* XXX are these really correct?  */
             if (ELF64_R_TYPE(rel->r_info) == R_X86_64_GOTPCREL)
                 *(unsigned int *) loc += v + isym->gotent.offset;
             else
                 *loc += isym->gotent.offset;
             break;
 # endif
 #else
 # warning "no idea how to handle relocations on your arch"
 #endif
         default:
             printf("Warning: unhandled reloc %d\n", (int)ELF_R_TYPE(rel->r_info));
             ret = obj_reloc_unhandled;
             break;
 #if defined(USE_PLT_ENTRIES)
 bb_use_plt:
             /* find the plt entry and initialize it if necessary */
 #if defined(USE_PLT_LIST)
             for (pe = isym->pltent; pe != NULL && pe->addend != rel->r_addend;)
                 pe = pe->next;
 #else
             pe = &isym->pltent;
 #endif
             if (! pe->inited) {
                 ip = (unsigned long *) (ifile->plt->contents + pe->offset);
                 /* generate some machine code */
 #if defined(__arm__)
                 ip[0] = 0xe51ff004;         /* ldr pc,[pc,#-4] */
                 ip[1] = v;              /* sym@ */
 #endif
 #if defined(__powerpc__)
                 ip[0] = 0x3d600000 + ((v + 0x8000) >> 16);  /* lis r11,sym@ha */
                 ip[1] = 0x396b0000 + (v & 0xffff);          /* addi r11,r11,sym@l */
                 ip[2] = 0x7d6903a6;               /* mtctr r11 */
                 ip[3] = 0x4e800420;               /* bctr */
 #endif
 #if defined(__v850e__)
                 /* We have to trash a register, so we assume that any control
                    transfer more than 21-bits away must be a function call
                    (so we can use a call-clobbered register).  */
                 ip[0] = 0x0621 + ((v & 0xffff) << 16);   /* mov sym, r1 ... */
                 ip[1] = ((v >> 16) & 0xffff) + 0x610000; /* ...; jmp r1 */
 #endif
                 pe->inited = 1;
             }
             /* relative distance to target */
             v -= dot;
             /* if the target is too far away.... */
 #if defined(__arm__) || defined(__powerpc__)
             if ((int)v < -0x02000000 || (int)v >= 0x02000000)
 #elif defined(__v850e__)
                 if ((ElfW(Sword))v > 0x1fffff || (ElfW(Sword))v < (ElfW(Sword))-0x200000)
 #endif
                     /* go via the plt */
                     v = plt + pe->offset - dot;
 #if defined(__v850e__)
             if (v & 1)
 #else
                 if (v & 3)
 #endif
                     ret = obj_reloc_dangerous;
             /* merge the offset into the instruction. */
 #if defined(__arm__)
             /* Convert to words. */
             v >>= 2;
             *loc = (*loc & ~0x00ffffff) | ((v + *loc) & 0x00ffffff);
 #endif
 #if defined(__powerpc__)
             *loc = (*loc & ~0x03fffffc) | (v & 0x03fffffc);
 #endif
 #if defined(__v850e__)
             /* We write two shorts instead of a long because even 32-bit insns
                only need half-word alignment, but the 32-bit data write needs
                to be long-word aligned.  */
             ((unsigned short *)loc)[0] =
                 (*(unsigned short *)loc & 0xffc0) /* opcode + reg */
                 | ((v >> 16) & 0x3f);             /* offs high part */
             ((unsigned short *)loc)[1] =
                 (v & 0xffff);                    /* offs low part */
 #endif
             break;
 #endif /* USE_PLT_ENTRIES */
 #if defined(USE_GOT_ENTRIES)
 bb_use_got:
             /* needs an entry in the .got: set it, once */
             if (!isym->gotent.inited) {
                 isym->gotent.inited = 1;
                 *(ElfW(Addr) *) (ifile->got->contents + isym->gotent.offset) = v;
             }
             /* make the reloc with_respect_to_.got */
 #if defined(__sh__)
             *loc += isym->gotent.offset + rel->r_addend;
 #elif defined(__i386__) || defined(__arm__) || defined(__mc68000__)
             *loc += isym->gotent.offset;
 #endif
             break;
 #endif /* USE_GOT_ENTRIES */
     }
     return ret;
 }
References arch_symbol::root, and xzalloc().
Referenced by obj_relocate().
arch_create_got()
static void arch_create_got (struct obj_file * f) static
Definition at line 1767 of file modutils-24.c.
 {
 #if defined(USE_GOT_ENTRIES) || defined(USE_PLT_ENTRIES)
     struct arch_file *ifile = (struct arch_file *) f;
     int i;
 #if defined(USE_GOT_ENTRIES)
     int got_offset = 0, got_needed = 0, got_allocate;
 #endif
 #if defined(USE_PLT_ENTRIES)
     int plt_offset = 0, plt_needed = 0, plt_allocate;
 #endif
     struct obj_section *relsec, *symsec, *strsec;
     ElfW(RelM) *rel, *relend;
     ElfW(Sym) *symtab, *extsym;
     const char *strtab, *name;
     struct arch_symbol *intsym;
     for (i = 0; i < f->header.e_shnum; ++i) {
         relsec = f->sections[i];
         if (relsec->header.sh_type != SHT_RELM)
             continue;
         symsec = f->sections[relsec->header.sh_link];
         strsec = f->sections[symsec->header.sh_link];
         rel = (ElfW(RelM) *) relsec->contents;
         relend = rel + (relsec->header.sh_size / sizeof(ElfW(RelM)));
         symtab = (ElfW(Sym) *) symsec->contents;
         strtab = (const char *) strsec->contents;
         for (; rel < relend; ++rel) {
             extsym = &symtab[ELF_R_SYM(rel->r_info)];
 #if defined(USE_GOT_ENTRIES)
             got_allocate = 0;
 #endif
 #if defined(USE_PLT_ENTRIES)
             plt_allocate = 0;
 #endif
             switch (ELF_R_TYPE(rel->r_info)) {
 #if defined(__arm__)
             case R_ARM_PC24:
             case R_ARM_PLT32:
                 plt_allocate = 1;
                 break;
             case R_ARM_GOTOFF:
             case R_ARM_GOTPC:
                 got_needed = 1;
                 continue;
             case R_ARM_GOT32:
                 got_allocate = 1;
                 break;
 #elif defined(__i386__)
             case R_386_GOTPC:
             case R_386_GOTOFF:
                 got_needed = 1;
                 continue;
             case R_386_GOT32:
                 got_allocate = 1;
                 break;
 #elif defined(__powerpc__)
             case R_PPC_REL24:
                 plt_allocate = 1;
                 break;
 #elif defined(__mc68000__)
             case R_68K_GOT32:
                 got_allocate = 1;
                 break;
 #ifdef R_68K_GOTOFF
             case R_68K_GOTOFF:
                 got_needed = 1;
                 continue;
 #endif
 #elif defined(__sh__)
             case R_SH_GOT32:
                 got_allocate = 1;
                 break;
             case R_SH_GOTPC:
             case R_SH_GOTOFF:
                 got_needed = 1;
                 continue;
 #elif defined(__v850e__)
             case R_V850_22_PCREL:
                 plt_needed = 1;
                 break;
 #endif
             default:
                 continue;
             }
             if (extsym->st_name != 0) {
                 name = strtab + extsym->st_name;
             } else {
                 name = f->sections[extsym->st_shndx]->name;
             }
             intsym = (struct arch_symbol *) obj_find_symbol(f, name);
 #if defined(USE_GOT_ENTRIES)
             if (got_allocate) {
                 got_offset += arch_single_init(
                         /*rel,*/ &intsym->gotent,
                         got_offset, GOT_ENTRY_SIZE);
                 got_needed = 1;
             }
 #endif
 #if defined(USE_PLT_ENTRIES)
             if (plt_allocate) {
 #if defined(USE_PLT_LIST)
                 plt_offset += arch_list_add(
                         rel, &intsym->pltent,
                         plt_offset, PLT_ENTRY_SIZE);
 #else
                 plt_offset += arch_single_init(
                         /*rel,*/ &intsym->pltent,
                         plt_offset, PLT_ENTRY_SIZE);
 #endif
                 plt_needed = 1;
             }
 #endif
         }
     }
 #if defined(USE_GOT_ENTRIES)
     if (got_needed) {
         ifile->got = arch_xsect_init(f, ".got", got_offset,
                 GOT_ENTRY_SIZE);
     }
 #endif
 #if defined(USE_PLT_ENTRIES)
     if (plt_needed) {
         ifile->plt = arch_xsect_init(f, ".plt", plt_offset,
                 PLT_ENTRY_SIZE);
     }
 #endif
 #endif /* defined(USE_GOT_ENTRIES) || defined(USE_PLT_ENTRIES) */
 }
References ELF_R_SYM, ELF_R_TYPE, ElfW, f, i, obj_find_symbol(), R_386_GOT32, R_386_GOTOFF, R_386_GOTPC, R_68K_GOT32, R_ARM_GOT32, R_ARM_GOTOFF, R_ARM_GOTPC, R_ARM_PC24, R_ARM_PLT32, R_PPC_REL24, R_SH_GOT32, R_SH_GOTOFF, and R_SH_GOTPC.
Referenced by bb_init_module_24().
arch_new_file()
static struct obj_file* arch_new_file (void) static
Definition at line 775 of file modutils-24.c.
 {
     struct arch_file *f;
     f = xzalloc(sizeof(*f));
     return &f->root; /* it's a first member */
 }
References f, and xzalloc().
Referenced by obj_load().
arch_new_section()
static struct obj_section* arch_new_section (void) static
Definition at line 782 of file modutils-24.c.
 {
     return xzalloc(sizeof(struct obj_section));
 }
References xzalloc().
Referenced by helper_create_alloced_section(), obj_allocate_commons(), and obj_load().
arch_new_symbol()
static struct obj_symbol* arch_new_symbol (void) static
Definition at line 787 of file modutils-24.c.
 {
     struct arch_symbol *sym;
     sym = xzalloc(sizeof(*sym));
     return &sym->root;
 }
Referenced by obj_add_symbol().
bb_init_module_24()
int FAST_FUNC bb_init_module_24 (const char * m_filename, const char * options)
Definition at line 3805 of file modutils-24.c.
 {
     int k_crcs;
     unsigned long m_size;
     ElfW(Addr) m_addr;
     struct obj_file *f;
     int exit_status = EXIT_FAILURE;
     char *m_name;
 #if ENABLE_FEATURE_INSMOD_VERSION_CHECKING
     int m_has_modinfo;
 #endif
     char *image;
     size_t image_size;
     bool mmaped;
     image_size = INT_MAX - 4095;
     mmaped = 0;
     image = try_to_mmap_module(m_filename, &image_size);
     if (image) {
         mmaped = 1;
     } else {
         /* Load module into memory and unzip if compressed */
         image = xmalloc_open_zipped_read_close(m_filename, &image_size);
         if (!image)
             return EXIT_FAILURE;
     }
     m_name = xstrdup(bb_basename(m_filename));
     /* "module.o[.gz]" -> "module" */
     *strchrnul(m_name, '.') = '\0';
     f = obj_load(image, image_size, LOADBITS);
 #if ENABLE_FEATURE_INSMOD_VERSION_CHECKING
     /* Version correspondence?  */
     m_has_modinfo = (get_modinfo_value(f, "kernel_version") != NULL);
     if (!flag_quiet) {
         char m_strversion[STRVERSIONLEN];
         struct utsname uts;
         if (m_has_modinfo) {
             int m_version = new_get_module_version(f, m_strversion);
             if (m_version == -1) {
                 bb_simple_error_msg_and_die("can't find the kernel version "
                     "the module was compiled for");
             }
         }
         uname(&uts);
         if (strncmp(uts.release, m_strversion, STRVERSIONLEN) != 0) {
             bb_error_msg("%skernel-module version mismatch\n"
                 "\t%s was compiled for kernel version %s\n"
                 "\twhile this kernel is version %s",
                 flag_force_load ? "warning: " : "",
                 m_name, m_strversion, uts.release);
             if (!flag_force_load)
                 goto out;
         }
     }
 #endif
     if (query_module(NULL, 0, NULL, 0, NULL))
         bb_simple_error_msg_and_die("old (unsupported) kernel");
     new_get_kernel_symbols();
     k_crcs = new_is_kernel_checksummed();
 #if ENABLE_FEATURE_INSMOD_VERSION_CHECKING
     {
         int m_crcs = 0;
         if (m_has_modinfo)
             m_crcs = new_is_module_checksummed(f);
         if (m_crcs != k_crcs)
             obj_set_symbol_compare(f, ncv_strcmp, ncv_symbol_hash);
     }
 #endif
     /* Let the module know about the kernel symbols.  */
     add_kernel_symbols(f);
     /* Allocate common symbols, symbol tables, and string tables.  */
     new_create_this_module(f, m_name);
     obj_check_undefineds(f);
     obj_allocate_commons(f);
     check_tainted_module(f, m_name);
     /* Done with the module name, on to the optional var=value arguments */
     new_process_module_arguments(f, options);
     arch_create_got(f);
     hide_special_symbols(f);
 #if ENABLE_FEATURE_INSMOD_KSYMOOPS_SYMBOLS
     add_ksymoops_symbols(f, m_filename, m_name);
 #endif
     new_create_module_ksymtab(f);
     /* Find current size of the module */
     m_size = obj_load_size(f);
     m_addr = create_module(m_name, m_size);
     if (m_addr == (ElfW(Addr))(-1)) switch (errno) {
     case EEXIST:
         bb_error_msg_and_die("a module named %s already exists", m_name);
     case ENOMEM:
         bb_error_msg_and_die("can't allocate kernel memory for module; needed %lu bytes",
                 m_size);
     default:
         bb_perror_msg_and_die("create_module: %s", m_name);
     }
 #if !LOADBITS
     /*
      * the PROGBITS section was not loaded by the obj_load
      * now we can load them directly into the kernel memory
      */
     if (!obj_load_progbits(image, image_size, f, (char*)m_addr)) {
         delete_module(m_name, 0);
         goto out;
     }
 #endif
     if (!obj_relocate(f, m_addr)) {
         delete_module(m_name, 0);
         goto out;
     }
     if (!new_init_module(m_name, f, m_size)) {
         delete_module(m_name, 0);
         goto out;
     }
     if (flag_print_load_map)
         print_load_map(f);
     exit_status = EXIT_SUCCESS;
  out:
     if (mmaped)
         munmap(image, image_size);
     else
         free(image);
     free(m_name);
     return exit_status;
 }
References add_kernel_symbols(), arch_create_got(), bb_basename(), bb_error_msg(), bb_error_msg_and_die(), bb_perror_msg_and_die(), bb_simple_error_msg_and_die(), check_tainted_module, create_module(), delete_module(), EEXIST, ElfW, ENOMEM, errno, EXIT_FAILURE, exit_status, EXIT_SUCCESS, f, flag_force_load, flag_print_load_map, flag_quiet, free, get_modinfo_value(), hide_special_symbols(), INT_MAX, LOADBITS, munmap(), new_create_module_ksymtab(), new_create_this_module(), new_get_kernel_symbols(), new_init_module(), new_is_kernel_checksummed(), new_process_module_arguments(), NULL, obj_allocate_commons(), obj_check_undefineds(), obj_load(), obj_load_size(), obj_relocate(), out(), print_load_map(), query_module(), utsname::release, strchrnul(), strncmp(), try_to_mmap_module, uname(), xmalloc_open_zipped_read_close, and xstrdup().
Referenced by bb_init_module().
create_module()
unsigned long create_module (const char * , size_t)
Referenced by bb_init_module_24().
delete_module()
int delete_module (const char * module, unsigned int flags)
Referenced by bb_init_module_24().
ElfW()
static ElfW (Addr) static
Definition at line 607 of file modutils-24.c.
      { STRVERSIONLEN = 64 };
get_modinfo_value()
static char* get_modinfo_value (struct obj_file * f, const char * key) static
Definition at line 2330 of file modutils-24.c.
 {
     struct obj_section *sec;
     char *p, *v, *n, *ep;
     size_t klen = strlen(key);
     sec = obj_find_section(f, ".modinfo");
     if (sec == NULL)
         return NULL;
     p = sec->contents;
     ep = p + sec->header.sh_size;
     while (p < ep) {
         v = strchr(p, '=');
         n = strchr(p, '\0');
         if (v) {
             if (p + klen == v && strncmp(p, key, klen) == 0)
                 return v + 1;
         } else {
             if (p + klen == n && strcmp(p, key) == 0)
                 return n;
         }
         p = n + 1;
     }
     return NULL;
 }
References f, n, NULL, obj_find_section(), p, strchr(), strcmp, strlen(), and strncmp().
Referenced by bb_init_module_24(), and new_process_module_arguments().
helper_create_alloced_section()
static struct obj_section* helper_create_alloced_section (struct obj_file * f, const char * name, unsigned long align, unsigned long size) static
Definition at line 2164 of file modutils-24.c.
 {
     int newidx = f->header.e_shnum++;
     struct obj_section *sec;
     f->sections = xrealloc_vector(f->sections, 2, newidx);
     f->sections[newidx] = sec = arch_new_section();
     sec->header.sh_type = SHT_PROGBITS;
     sec->header.sh_flags = SHF_WRITE | SHF_ALLOC;
     sec->header.sh_size = size;
     sec->header.sh_addralign = align;
     sec->name = name;
     sec->idx = newidx;
     if (size)
         sec->contents = xzalloc(size);
     return sec;
 }
References arch_new_section(), f, SHF_ALLOC, SHF_WRITE, SHT_PROGBITS, size, xrealloc_vector, and xzalloc().
Referenced by obj_create_alloced_section(), and obj_create_alloced_section_first().
hide_special_symbols()
static void hide_special_symbols (struct obj_file * f) static
Definition at line 3459 of file modutils-24.c.
 {
     static const char *const specials[] ALIGN_PTR = {
         SPFX "cleanup_module",
         SPFX "init_module",
         SPFX "kernel_version",
         NULL
     };
     struct obj_symbol *sym;
     const char *const *p;
     for (p = specials; *p; ++p) {
         sym = obj_find_symbol(f, *p);
         if (sym != NULL)
             sym->info = ELF_ST_INFO(STB_LOCAL, ELF_ST_TYPE(sym->info));
     }
 }
References ALIGN_PTR, ELF_ST_INFO, ELF_ST_TYPE, f, obj_symbol::info, NULL, obj_find_symbol(), p, SPFX, and STB_LOCAL.
Referenced by bb_init_module_24().
init_module()
int init_module (const char * name, const struct new_module *)
Referenced by new_init_module().
new_create_module_ksymtab()
static int new_create_module_ksymtab (struct obj_file * f) static
Definition at line 2741 of file modutils-24.c.
 {
     struct obj_section *sec;
     int i;
     /* We must always add the module references.  */
     if (n_ext_modules_used) {
         struct new_module_ref *dep;
         struct obj_symbol *tm;
         sec = obj_create_alloced_section(f, ".kmodtab", tgt_sizeof_void_p,
                 (sizeof(struct new_module_ref)
                  * n_ext_modules_used));
         if (!sec)
             return 0;
         tm = obj_find_symbol(f, SPFX "__this_module");
         dep = (struct new_module_ref *) sec->contents;
         for (i = 0; i < n_ext_modules; ++i)
             if (ext_modules[i].used) {
                 dep->dep = ext_modules[i].addr;
                 obj_symbol_patch(f, sec->idx,
                         (char *) &dep->ref - sec->contents, tm);
                 dep->next_ref = 0;
                 ++dep;
             }
     }
     if (!flag_noexport && !obj_find_section(f, "__ksymtab")) {
         size_t nsyms;
         int *loaded;
         sec = obj_create_alloced_section(f, "__ksymtab", tgt_sizeof_void_p, 0);
         /* We don't want to export symbols residing in sections that
            aren't loaded.  There are a number of these created so that
            we make sure certain module options don't appear twice.  */
         i = f->header.e_shnum;
         loaded = alloca(sizeof(int) * i);
         while (--i >= 0)
             loaded[i] = (f->sections[i]->header.sh_flags & SHF_ALLOC) != 0;
         for (nsyms = i = 0; i < HASH_BUCKETS; ++i) {
             struct obj_symbol *sym;
             for (sym = f->symtab[i]; sym; sym = sym->next) {
                 if (ELF_ST_BIND(sym->info) != STB_LOCAL
                  && sym->secidx <= SHN_HIRESERVE
                  && (sym->secidx >= SHN_LORESERVE || loaded[sym->secidx])
                 ) {
                     ElfW(Addr) ofs = nsyms * 2 * tgt_sizeof_void_p;
                     obj_symbol_patch(f, sec->idx, ofs, sym);
                     obj_string_patch(f, sec->idx, ofs + tgt_sizeof_void_p,
                             sym->name);
                     nsyms++;
                 }
             }
         }
         obj_extend_section(sec, nsyms * 2 * tgt_sizeof_char_p);
     }
     return 1;
 }
References alloca, new_module_ref::dep, ELF_ST_BIND, ElfW, ext_modules, f, flag_noexport, for(), HASH_BUCKETS, i, obj_symbol::info, n_ext_modules, n_ext_modules_used, obj_symbol::name, obj_symbol::next, obj_create_alloced_section(), obj_extend_section(), obj_find_section(), obj_find_symbol(), obj_string_patch(), obj_symbol_patch(), obj_symbol::secidx, SHF_ALLOC, SHN_HIRESERVE, SHN_LORESERVE, SPFX, STB_LOCAL, tgt_sizeof_char_p, and tgt_sizeof_void_p.
Referenced by bb_init_module_24().
new_create_this_module()
static void new_create_this_module (struct obj_file * f, const char * m_name) static
Definition at line 2692 of file modutils-24.c.
 {
     struct obj_section *sec;
     sec = obj_create_alloced_section_first(f, ".this", tgt_sizeof_long,
             sizeof(struct new_module));
     /* done by obj_create_alloced_section_first: */
     /*memset(sec->contents, 0, sizeof(struct new_module));*/
     obj_add_symbol(f, SPFX "__this_module", -1,
             ELF_ST_INFO(STB_LOCAL, STT_OBJECT), sec->idx, 0,
             sizeof(struct new_module));
     obj_string_patch(f, sec->idx, offsetof(struct new_module, name),
             m_name);
 }
References ELF_ST_INFO, f, obj_add_symbol(), obj_create_alloced_section_first(), obj_string_patch(), offsetof, SPFX, STB_LOCAL, STT_OBJECT, and tgt_sizeof_long.
Referenced by bb_init_module_24().
new_get_kernel_symbols()
static void new_get_kernel_symbols (void) static
Definition at line 2584 of file modutils-24.c.
 {
     char *module_names, *mn;
     struct external_module *modules, *m;
     struct new_module_symbol *syms, *s;
     size_t ret, bufsize, nmod, nsyms, i, j;
     /* Collect the loaded modules.  */
     bufsize = 256;
     module_names = xmalloc(bufsize);
  retry_modules_load:
     if (query_module(NULL, QM_MODULES, module_names, bufsize, &ret)) {
         if (errno == ENOSPC && bufsize < ret) {
             bufsize = ret;
             module_names = xrealloc(module_names, bufsize);
             goto retry_modules_load;
         }
         bb_simple_perror_msg_and_die("QM_MODULES");
     }
     n_ext_modules = nmod = ret;
     /* Collect the modules' symbols.  */
     if (nmod) {
         ext_modules = modules = xzalloc(nmod * sizeof(*modules));
         for (i = 0, mn = module_names, m = modules;
                 i < nmod; ++i, ++m, mn += strlen(mn) + 1) {
             struct new_module_info info;
             if (query_module(mn, QM_INFO, &info, sizeof(info), &ret)) {
                 if (errno == ENOENT) {
                     /* The module was removed out from underneath us.  */
                     continue;
                 }
                 bb_perror_msg_and_die("query_module: QM_INFO: %s", mn);
             }
             bufsize = 1024;
             syms = xmalloc(bufsize);
  retry_mod_sym_load:
             if (query_module(mn, QM_SYMBOLS, syms, bufsize, &ret)) {
                 switch (errno) {
                     case ENOSPC:
                         bufsize = ret;
                         syms = xrealloc(syms, bufsize);
                         goto retry_mod_sym_load;
                     case ENOENT:
                         /* The module was removed out from underneath us.  */
                         continue;
                     default:
                         bb_perror_msg_and_die("query_module: QM_SYMBOLS: %s", mn);
                 }
             }
             nsyms = ret;
             m->name = mn;
             m->addr = info.addr;
             m->nsyms = nsyms;
             m->syms = syms;
             for (j = 0, s = syms; j < nsyms; ++j, ++s) {
                 s->name += (unsigned long) syms;
             }
         }
     }
     /* Collect the kernel's symbols.  */
     bufsize = 16 * 1024;
     syms = xmalloc(bufsize);
  retry_kern_sym_load:
     if (query_module(NULL, QM_SYMBOLS, syms, bufsize, &ret)) {
         if (errno == ENOSPC && bufsize < ret) {
             bufsize = ret;
             syms = xrealloc(syms, bufsize);
             goto retry_kern_sym_load;
         }
         bb_simple_perror_msg_and_die("kernel: QM_SYMBOLS");
     }
     nksyms = nsyms = ret;
     ksyms = syms;
     for (j = 0, s = syms; j < nsyms; ++j, ++s) {
         s->name += (unsigned long) syms;
     }
 }
References bb_perror_msg_and_die(), bb_simple_perror_msg_and_die(), ENOENT, ENOSPC, errno, ext_modules, i, info, j, ksyms, n_ext_modules, nksyms, NULL, QM_INFO, QM_MODULES, QM_SYMBOLS, query_module(), s, strlen(), xmalloc, xrealloc, and xzalloc().
Referenced by bb_init_module_24().
new_init_module()
static int new_init_module (const char * m_name, struct obj_file * f, unsigned long m_size) static
Definition at line 2809 of file modutils-24.c.
 {
     struct new_module *module;
     struct obj_section *sec;
     void *image;
     int ret;
     tgt_long m_addr;
     sec = obj_find_section(f, ".this");
     if (!sec || !sec->contents) {
         bb_perror_msg_and_die("corrupt module %s?", m_name);
     }
     module = (struct new_module *) sec->contents;
     m_addr = sec->header.sh_addr;
     module->size_of_struct = sizeof(*module);
     module->size = m_size;
     module->flags = flag_autoclean ? NEW_MOD_AUTOCLEAN : 0;
     sec = obj_find_section(f, "__ksymtab");
     if (sec && sec->header.sh_size) {
         module->syms = sec->header.sh_addr;
         module->nsyms = sec->header.sh_size / (2 * tgt_sizeof_char_p);
     }
     if (n_ext_modules_used) {
         sec = obj_find_section(f, ".kmodtab");
         module->deps = sec->header.sh_addr;
         module->ndeps = n_ext_modules_used;
     }
     module->init = obj_symbol_final_value(f, obj_find_symbol(f, SPFX "init_module"));
     module->cleanup = obj_symbol_final_value(f, obj_find_symbol(f, SPFX "cleanup_module"));
     sec = obj_find_section(f, "__ex_table");
     if (sec) {
         module->ex_table_start = sec->header.sh_addr;
         module->ex_table_end = sec->header.sh_addr + sec->header.sh_size;
     }
     sec = obj_find_section(f, ".text.init");
     if (sec) {
         module->runsize = sec->header.sh_addr - m_addr;
     }
     sec = obj_find_section(f, ".data.init");
     if (sec) {
         if (!module->runsize
          || module->runsize > sec->header.sh_addr - m_addr
         ) {
             module->runsize = sec->header.sh_addr - m_addr;
         }
     }
     sec = obj_find_section(f, ARCHDATA_SEC_NAME);
     if (sec && sec->header.sh_size) {
         module->archdata_start = (void*)sec->header.sh_addr;
         module->archdata_end = module->archdata_start + sec->header.sh_size;
     }
     sec = obj_find_section(f, KALLSYMS_SEC_NAME);
     if (sec && sec->header.sh_size) {
         module->kallsyms_start = (void*)sec->header.sh_addr;
         module->kallsyms_end = module->kallsyms_start + sec->header.sh_size;
     }
     /* Whew!  All of the initialization is complete.  Collect the final
        module image and give it to the kernel.  */
     image = xmalloc(m_size);
     obj_create_image(f, image);
     ret = init_module(m_name, (struct new_module *) image);
     if (ret)
         bb_perror_msg("init_module: %s", m_name);
     free(image);
     return ret == 0;
 }
References new_module::archdata_end, ARCHDATA_SEC_NAME, new_module::archdata_start, bb_perror_msg(), bb_perror_msg_and_die(), new_module::cleanup, new_module::deps, new_module::ex_table_end, new_module::ex_table_start, f, flag_autoclean, new_module::flags, free, new_module::init, init_module(), new_module::kallsyms_end, KALLSYMS_SEC_NAME, new_module::kallsyms_start, n_ext_modules_used, new_module::ndeps, NEW_MOD_AUTOCLEAN, new_module::nsyms, obj_create_image(), obj_find_section(), obj_find_symbol(), new_module::runsize, new_module::size, new_module::size_of_struct, SPFX, new_module::syms, tgt_long, tgt_sizeof_char_p, and xmalloc.
Referenced by bb_init_module_24().
new_is_kernel_checksummed()
static int new_is_kernel_checksummed (void) static
Definition at line 2677 of file modutils-24.c.
 {
     struct new_module_symbol *s;
     size_t i;
     /* Using_Versions is not the first symbol, but it should be in there.  */
     for (i = 0, s = ksyms; i < nksyms; ++i, ++s)
         if (strcmp((char *) s->name, "Using_Versions") == 0)
             return s->value;
     return 0;
 }
References i, ksyms, nksyms, s, and strcmp.
Referenced by bb_init_module_24().
new_process_module_arguments()
static void new_process_module_arguments (struct obj_file * f, const char * options) static
Definition at line 2415 of file modutils-24.c.
 {
     char *xoptions, *pos;
     char *param, *val;
     xoptions = pos = xstrdup(skip_whitespace(options));
     while (*pos) {
         unsigned long charssize = 0;
         char *tmp, *contents, *loc, *pinfo, *p;
         struct obj_symbol *sym;
         int min, max, n, len;
         pos = next_arg(pos, &param, &val);
         tmp = xasprintf("parm_%s", param);
         pinfo = get_modinfo_value(f, tmp);
         free(tmp);
         if (pinfo == NULL)
             bb_error_msg_and_die("invalid parameter %s", param);
 #ifdef SYMBOL_PREFIX
         tmp = xasprintf(SYMBOL_PREFIX "%s", param);
         sym = obj_find_symbol(f, tmp);
         free(tmp);
 #else
         sym = obj_find_symbol(f, param);
 #endif
         /* Also check that the parameter was not resolved from the kernel.  */
         if (sym == NULL || sym->secidx > SHN_HIRESERVE)
             bb_error_msg_and_die("symbol for parameter %s not found", param);
         /* Number of parameters */
         min = max = 1;
         if (isdigit(*pinfo)) {
             min = max = strtoul(pinfo, &pinfo, 10);
             if (*pinfo == '-')
                 max = strtoul(pinfo + 1, &pinfo, 10);
         }
         contents = f->sections[sym->secidx]->contents;
         loc = contents + sym->value;
         if (*pinfo == 'c') {
             if (!isdigit(pinfo[1])) {
                 bb_error_msg_and_die("parameter type 'c' for %s must be followed by"
                              " the maximum size", param);
             }
             charssize = strtoul(pinfo + 1, NULL, 10);
         }
         if (val == NULL) {
             if (*pinfo != 'b')
                 bb_error_msg_and_die("argument expected for parameter %s", param);
             val = (char *) "1";
         }
         /* Parse parameter values */
         n = 0;
         p = val;
         while (*p) {
             char sv_ch;
             char *endp;
             if (++n > max)
                 bb_error_msg_and_die("too many values for %s (max %d)", param, max);
             switch (*pinfo) {
             case 's':
                 len = strcspn(p, ",");
                 sv_ch = p[len];
                 p[len] = '\0';
                 obj_string_patch(f, sym->secidx,
                          loc - contents, p);
                 loc += tgt_sizeof_char_p;
                 p += len;
                 *p = sv_ch;
                 break;
             case 'c':
                 len = strcspn(p, ",");
                 sv_ch = p[len];
                 p[len] = '\0';
                 if (len >= charssize)
                     bb_error_msg_and_die("string too long for %s (max %ld)", param,
                                  charssize - 1);
                 strcpy((char *) loc, p);
                 loc += charssize;
                 p += len;
                 *p = sv_ch;
                 break;
             case 'b':
                 *loc++ = strtoul(p, &endp, 0);
                 p = endp; /* gcc likes temp var for &endp */
                 break;
             case 'h':
                 *(short *) loc = strtoul(p, &endp, 0);
                 loc += tgt_sizeof_short;
                 p = endp;
                 break;
             case 'i':
                 *(int *) loc = strtoul(p, &endp, 0);
                 loc += tgt_sizeof_int;
                 p = endp;
                 break;
             case 'l':
                 *(long *) loc = strtoul(p, &endp, 0);
                 loc += tgt_sizeof_long;
                 p = endp;
                 break;
             default:
                 bb_error_msg_and_die("unknown parameter type '%c' for %s",
                              *pinfo, param);
             }
             p = skip_whitespace(p);
             if (*p != ',')
                 break;
             p = skip_whitespace(p + 1);
         }
         if (n < min)
             bb_error_msg_and_die("parameter %s requires at least %d arguments", param, min);
         if (*p != '\0')
             bb_error_msg_and_die("invalid argument syntax for %s", param);
     }
     free(xoptions);
 }
References bb_error_msg_and_die(), f, free, get_modinfo_value(), isdigit, len, max, min, n, next_arg(), NULL, obj_find_symbol(), obj_string_patch(), p, param, pos, obj_symbol::secidx, SHN_HIRESERVE, skip_whitespace(), strcpy, strcspn(), strtoul(), tgt_sizeof_char_p, tgt_sizeof_int, tgt_sizeof_long, tgt_sizeof_short, val, obj_symbol::value, xasprintf(), and xstrdup().
Referenced by bb_init_module_24().
next_arg()
static char* next_arg (char * args, char ** param, char ** val) static
Definition at line 2364 of file modutils-24.c.
 {
     unsigned int i, equals = 0;
     int in_quote = 0, quoted = 0;
     char *next;
     if (*args == '"') {
         args++;
         in_quote = 1;
         quoted = 1;
     }
     for (i = 0; args[i]; i++) {
         if (args[i] == ' ' && !in_quote)
             break;
         if (equals == 0) {
             if (args[i] == '=')
                 equals = i;
         }
         if (args[i] == '"')
             in_quote = !in_quote;
     }
     *param = args;
     if (!equals)
         *val = NULL;
     else {
         args[equals] = '\0';
         *val = args + equals + 1;
         /* Don't include quotes in value. */
         if (**val == '"') {
             (*val)++;
             if (args[i-1] == '"')
                 args[i-1] = '\0';
         }
         if (quoted && args[i-1] == '"')
             args[i-1] = '\0';
     }
     if (args[i]) {
         args[i] = '\0';
         next = args + i + 1;
     } else
         next = args + i;
     /* Chew up trailing spaces. */
     return skip_whitespace(next);
 }
References args, i, next, NULL, param, skip_whitespace(), and val.
Referenced by fsck_main(), man_main(), new_process_module_arguments(), and parse_shell_options().
obj_add_symbol()
static struct obj_symbol* obj_add_symbol (struct obj_file * f, const char * name, unsigned long symidx, int info, int secidx, ElfW(Addr) value, unsigned long size) static
Definition at line 2001 of file modutils-24.c.
 {
     struct obj_symbol *sym;
     unsigned long hash = f->symbol_hash(name) % HASH_BUCKETS;
     int n_type = ELF_ST_TYPE(info);
     int n_binding = ELF_ST_BIND(info);
     for (sym = f->symtab[hash]; sym; sym = sym->next) {
         if (f->symbol_cmp(sym->name, name) == 0) {
             int o_secidx = sym->secidx;
             int o_info = sym->info;
             int o_type = ELF_ST_TYPE(o_info);
             int o_binding = ELF_ST_BIND(o_info);
             /* A redefinition!  Is it legal?  */
             if (secidx == SHN_UNDEF)
                 return sym;
             else if (o_secidx == SHN_UNDEF)
                 goto found;
             else if (n_binding == STB_GLOBAL && o_binding == STB_LOCAL) {
                 /* Cope with local and global symbols of the same name
                    in the same object file, as might have been created
                    by ld -r.  The only reason locals are now seen at this
                    level at all is so that we can do semi-sensible things
                    with parameters.  */
                 struct obj_symbol *nsym, **p;
                 nsym = arch_new_symbol();
                 nsym->next = sym->next;
                 nsym->ksymidx = -1;
                 /* Excise the old (local) symbol from the hash chain.  */
                 for (p = &f->symtab[hash]; *p != sym; p = &(*p)->next)
                     continue;
                 *p = sym = nsym;
                 goto found;
             } else if (n_binding == STB_LOCAL) {
                 /* Another symbol of the same name has already been defined.
                    Just add this to the local table.  */
                 sym = arch_new_symbol();
                 sym->next = NULL;
                 sym->ksymidx = -1;
                 f->local_symtab[symidx] = sym;
                 goto found;
             } else if (n_binding == STB_WEAK)
                 return sym;
             else if (o_binding == STB_WEAK)
                 goto found;
             /* Don't unify COMMON symbols with object types the programmer
                doesn't expect.  */
             else if (secidx == SHN_COMMON
                     && (o_type == STT_NOTYPE || o_type == STT_OBJECT))
                 return sym;
             else if (o_secidx == SHN_COMMON
                     && (n_type == STT_NOTYPE || n_type == STT_OBJECT))
                 goto found;
             else {
                 /* Don't report an error if the symbol is coming from
                    the kernel or some external module.  */
                 if (secidx <= SHN_HIRESERVE)
                     bb_error_msg("%s multiply defined", name);
                 return sym;
             }
         }
     }
     /* Completely new symbol.  */
     sym = arch_new_symbol();
     sym->next = f->symtab[hash];
     f->symtab[hash] = sym;
     sym->ksymidx = -1;
     if (ELF_ST_BIND(info) == STB_LOCAL && symidx != (unsigned long)(-1)) {
         if (symidx >= f->local_symtab_size)
             bb_error_msg("local symbol %s with index %ld exceeds local_symtab_size %ld",
                     name, (long) symidx, (long) f->local_symtab_size);
         else
             f->local_symtab[symidx] = sym;
     }
 found:
     sym->name = name;
     sym->value = value;
     sym->size = size;
     sym->secidx = secidx;
     sym->info = info;
     return sym;
 }
References arch_new_symbol(), bb_error_msg(), ELF_ST_BIND, ELF_ST_TYPE, f, found, HASH_BUCKETS, info, obj_symbol::info, obj_symbol::ksymidx, obj_symbol::name, obj_symbol::next, NULL, p, obj_symbol::secidx, SHN_COMMON, SHN_HIRESERVE, SHN_UNDEF, size, obj_symbol::size, STB_GLOBAL, STB_LOCAL, STB_WEAK, STT_NOTYPE, STT_OBJECT, obj_symbol::value, and value.
Referenced by add_symbols_from(), new_create_this_module(), and obj_load().
obj_allocate_commons()
static void obj_allocate_commons (struct obj_file * f) static
Definition at line 2951 of file modutils-24.c.
 {
     struct common_entry {
         struct common_entry *next;
         struct obj_symbol *sym;
     } *common_head = NULL;
     unsigned long i;
     for (i = 0; i < HASH_BUCKETS; ++i) {
         struct obj_symbol *sym;
         for (sym = f->symtab[i]; sym; sym = sym->next) {
             if (sym->secidx == SHN_COMMON) {
                 /* Collect all COMMON symbols and sort them by size so as to
                    minimize space wasted by alignment requirements.  */
                 struct common_entry **p, *n;
                 for (p = &common_head; *p; p = &(*p)->next)
                     if (sym->size <= (*p)->sym->size)
                         break;
                 n = alloca(sizeof(*n));
                 n->next = *p;
                 n->sym = sym;
                 *p = n;
             }
         }
     }
     for (i = 1; i < f->local_symtab_size; ++i) {
         struct obj_symbol *sym = f->local_symtab[i];
         if (sym && sym->secidx == SHN_COMMON) {
             struct common_entry **p, *n;
             for (p = &common_head; *p; p = &(*p)->next) {
                 if (sym == (*p)->sym)
                     break;
                 if (sym->size < (*p)->sym->size) {
                     n = alloca(sizeof(*n));
                     n->next = *p;
                     n->sym = sym;
                     *p = n;
                     break;
                 }
             }
         }
     }
     if (common_head) {
         /* Find the bss section.  */
         for (i = 0; i < f->header.e_shnum; ++i)
             if (f->sections[i]->header.sh_type == SHT_NOBITS)
                 break;
         /* If for some reason there hadn't been one, create one.  */
         if (i == f->header.e_shnum) {
             struct obj_section *sec;
             f->header.e_shnum++;
             f->sections = xrealloc_vector(f->sections, 2, i);
             f->sections[i] = sec = arch_new_section();
             sec->header.sh_type = SHT_PROGBITS;
             sec->header.sh_flags = SHF_WRITE | SHF_ALLOC;
             sec->name = ".bss";
             sec->idx = i;
         }
         /* Allocate the COMMONS.  */
         {
             ElfW(Addr) bss_size = f->sections[i]->header.sh_size;
             ElfW(Addr) max_align = f->sections[i]->header.sh_addralign;
             struct common_entry *c;
             for (c = common_head; c; c = c->next) {
                 ElfW(Addr) align = c->sym->value;
                 if (align > max_align)
                     max_align = align;
                 if (bss_size & (align - 1))
                     bss_size = (bss_size | (align - 1)) + 1;
                 c->sym->secidx = i;
                 c->sym->value = bss_size;
                 bss_size += c->sym->size;
             }
             f->sections[i]->header.sh_size = bss_size;
             f->sections[i]->header.sh_addralign = max_align;
         }
     }
     /* For the sake of patch relocation and parameter initialization,
        allocate zeroed data for NOBITS sections now.  Note that after
        this we cannot assume NOBITS are really empty.  */
     for (i = 0; i < f->header.e_shnum; ++i) {
         struct obj_section *s = f->sections[i];
         if (s->header.sh_type == SHT_NOBITS) {
             s->contents = NULL;
             if (s->header.sh_size != 0)
                 s->contents = xzalloc(s->header.sh_size);
             s->header.sh_type = SHT_PROGBITS;
         }
     }
 }
References alloca, arch_new_section(), c, ElfW, f, HASH_BUCKETS, i, n, obj_symbol::next, next, NULL, p, s, obj_symbol::secidx, SHF_ALLOC, SHF_WRITE, SHN_COMMON, SHT_NOBITS, SHT_PROGBITS, obj_symbol::size, xrealloc_vector, and xzalloc().
Referenced by bb_init_module_24().
obj_check_undefineds()
static void obj_check_undefineds (struct obj_file * f) static
Definition at line 2931 of file modutils-24.c.
 {
     unsigned i;
     for (i = 0; i < HASH_BUCKETS; ++i) {
         struct obj_symbol *sym;
         for (sym = f->symtab[i]; sym; sym = sym->next) {
             if (sym->secidx == SHN_UNDEF) {
                 if (ELF_ST_BIND(sym->info) == STB_WEAK) {
                     sym->secidx = SHN_ABS;
                     sym->value = 0;
                 } else {
                     if (!flag_quiet)
                         bb_error_msg_and_die("unresolved symbol %s", sym->name);
                 }
             }
         }
     }
 }
References bb_error_msg_and_die(), ELF_ST_BIND, f, flag_quiet, HASH_BUCKETS, i, obj_symbol::info, obj_symbol::name, obj_symbol::next, obj_symbol::secidx, SHN_ABS, SHN_UNDEF, STB_WEAK, and obj_symbol::value.
Referenced by bb_init_module_24().
obj_create_alloced_section()
static struct obj_section* obj_create_alloced_section (struct obj_file * f, const char * name, unsigned long align, unsigned long size) static
Definition at line 2187 of file modutils-24.c.
 {
     struct obj_section *sec;
     sec = helper_create_alloced_section(f, name, align, size);
     obj_insert_section_load_order(f, sec);
     return sec;
 }
References f, helper_create_alloced_section(), obj_insert_section_load_order(), and size.
Referenced by new_create_module_ksymtab(), and obj_string_patch().
obj_create_alloced_section_first()
static struct obj_section* obj_create_alloced_section_first (struct obj_file * f, const char * name, unsigned long align, unsigned long size) static
Definition at line 2199 of file modutils-24.c.
 {
     struct obj_section *sec;
     sec = helper_create_alloced_section(f, name, align, size);
     sec->load_next = f->load_order;
     f->load_order = sec;
     if (f->load_order_search_start == &f->load_order)
         f->load_order_search_start = &sec->load_next;
     return sec;
 }
References f, helper_create_alloced_section(), and size.
Referenced by new_create_this_module().
obj_create_image()
static int obj_create_image (struct obj_file * f, char * image) static
Definition at line 3207 of file modutils-24.c.
 {
     struct obj_section *sec;
     ElfW(Addr) base = f->baseaddr;
     for (sec = f->load_order; sec; sec = sec->load_next) {
         char *secimg;
         if (sec->contents == 0 || sec->header.sh_size == 0)
             continue;
         secimg = image + (sec->header.sh_addr - base);
         /* Note that we allocated data for NOBITS sections earlier.  */
         memcpy(secimg, sec->contents, sec->header.sh_size);
     }
     return 1;
 }
References base, ElfW, f, and memcpy.
Referenced by new_init_module().
obj_elf_hash()
static unsigned long FAST_FUNC obj_elf_hash (const char * name) static
Definition at line 1940 of file modutils-24.c.
 {
     return obj_elf_hash_n(name, strlen(name));
 }
References obj_elf_hash_n(), and strlen().
Referenced by obj_load().
obj_elf_hash_n()
static unsigned long obj_elf_hash_n (const char * name, unsigned long len) static
Definition at line 1921 of file modutils-24.c.
 {
     unsigned long h = 0;
     unsigned long g;
     unsigned char ch;
     while (n > 0) {
         ch = *name++;
         h = (h << 4) + ch;
         g = (h & 0xf0000000);
         if (g != 0) {
             h ^= g >> 24;
             h &= ~g;
         }
         n--;
     }
     return h;
 }
References g, h, and n.
Referenced by obj_elf_hash().
obj_extend_section()
static void* obj_extend_section (struct obj_section * sec, unsigned long more) static
Definition at line 2215 of file modutils-24.c.
 {
     unsigned long oldsize = sec->header.sh_size;
     if (more) {
         sec->header.sh_size += more;
         sec->contents = xrealloc(sec->contents, sec->header.sh_size);
     }
     return sec->contents + oldsize;
 }
References xrealloc.
Referenced by new_create_module_ksymtab(), and obj_string_patch().
obj_find_section()
static struct obj_section* obj_find_section (struct obj_file * f, const char * name) static
Definition at line 2118 of file modutils-24.c.
 {
     int i, n = f->header.e_shnum;
     for (i = 0; i < n; ++i)
         if (strcmp(f->sections[i]->name, name) == 0)
             return f->sections[i];
     return NULL;
 }
References f, i, n, NULL, and strcmp.
Referenced by get_modinfo_value(), new_create_module_ksymtab(), new_init_module(), obj_relocate(), and obj_string_patch().
obj_find_symbol()
static struct obj_symbol * obj_find_symbol (struct obj_file * f, const char * name) static
Definition at line 2096 of file modutils-24.c.
 {
     struct obj_symbol *sym;
     unsigned long hash = f->symbol_hash(name) % HASH_BUCKETS;
     for (sym = f->symtab[hash]; sym; sym = sym->next)
         if (f->symbol_cmp(sym->name, name) == 0)
             return sym;
     return NULL;
 }
References f, HASH_BUCKETS, obj_symbol::name, obj_symbol::next, and NULL.
Referenced by add_symbols_from(), arch_create_got(), hide_special_symbols(), new_create_module_ksymtab(), new_init_module(), new_process_module_arguments(), and obj_relocate().
obj_insert_section_load_order()
static void obj_insert_section_load_order (struct obj_file * f, struct obj_section * sec) static
Definition at line 2153 of file modutils-24.c.
 {
     struct obj_section **p;
     int prio = obj_load_order_prio(sec);
     for (p = f->load_order_search_start; *p; p = &(*p)->load_next)
         if (obj_load_order_prio(*p) < prio)
             break;
     sec->load_next = *p;
     *p = sec;
 }
References f, obj_load_order_prio(), and p.
Referenced by obj_create_alloced_section(), and obj_load().
obj_load()
static struct obj_file* obj_load (char * image, size_t image_size, int loadprogbits) static
Definition at line 3229 of file modutils-24.c.
 {
     typedef uint32_t aliased_uint32_t FIX_ALIASING;
 #if BB_LITTLE_ENDIAN
 # define ELFMAG_U32 ((uint32_t)(ELFMAG0 + 0x100 * (ELFMAG1 + (0x100 * (ELFMAG2 + 0x100 * ELFMAG3)))))
 #else
 # define ELFMAG_U32 ((uint32_t)((((ELFMAG0 * 0x100) + ELFMAG1) * 0x100 + ELFMAG2) * 0x100 + ELFMAG3))
 #endif
     struct obj_file *f;
     ElfW(Shdr) * section_headers;
     size_t shnum, i;
     char *shstrtab;
     /* Read the file header.  */
     f = arch_new_file();
     f->symbol_cmp = strcmp;
     f->symbol_hash = obj_elf_hash;
     f->load_order_search_start = &f->load_order;
     if (image_size < sizeof(f->header))
         bb_simple_error_msg_and_die("error while loading ELF header");
     memcpy(&f->header, image, sizeof(f->header));
     if (*(aliased_uint32_t*)(&f->header.e_ident) != ELFMAG_U32) {
         bb_simple_error_msg_and_die("not an ELF file");
     }
     if (f->header.e_ident[EI_CLASS] != ELFCLASSM
      || f->header.e_ident[EI_DATA] != (BB_BIG_ENDIAN ? ELFDATA2MSB : ELFDATA2LSB)
      || f->header.e_ident[EI_VERSION] != EV_CURRENT
      || !MATCH_MACHINE(f->header.e_machine)
     ) {
         bb_simple_error_msg_and_die("ELF file not for this architecture");
     }
     if (f->header.e_type != ET_REL) {
         bb_simple_error_msg_and_die("ELF file not a relocatable object");
     }
     /* Read the section headers.  */
     if (f->header.e_shentsize != sizeof(ElfW(Shdr))) {
         bb_error_msg_and_die("section header size mismatch: %lu != %lu",
                 (unsigned long) f->header.e_shentsize,
                 (unsigned long) sizeof(ElfW(Shdr)));
     }
     shnum = f->header.e_shnum;
     /* Growth of ->sections vector will be done by
      * xrealloc_vector(..., 2, ...), therefore we must allocate
      * at least 2^2 = 4 extra elements here. */
     f->sections = xzalloc(sizeof(f->sections[0]) * (shnum + 4));
     section_headers = alloca(sizeof(ElfW(Shdr)) * shnum);
     if (image_size < f->header.e_shoff + sizeof(ElfW(Shdr)) * shnum)
         bb_simple_error_msg_and_die("error while loading section headers");
     memcpy(section_headers, image + f->header.e_shoff, sizeof(ElfW(Shdr)) * shnum);
     /* Read the section data.  */
     for (i = 0; i < shnum; ++i) {
         struct obj_section *sec;
         f->sections[i] = sec = arch_new_section();
         sec->header = section_headers[i];
         sec->idx = i;
         if (sec->header.sh_size) {
             switch (sec->header.sh_type) {
             case SHT_NULL:
             case SHT_NOTE:
             case SHT_NOBITS:
                 /* ignore */
                 break;
             case SHT_PROGBITS:
 #if LOADBITS
                 if (!loadprogbits) {
                     sec->contents = NULL;
                     break;
                 }
 #endif
             case SHT_SYMTAB:
             case SHT_STRTAB:
             case SHT_RELM:
 #if defined(__mips__)
             case SHT_MIPS_DWARF:
 #endif
                 sec->contents = NULL;
                 if (sec->header.sh_size > 0) {
                     sec->contents = xmalloc(sec->header.sh_size);
                     if (image_size < (sec->header.sh_offset + sec->header.sh_size))
                         bb_simple_error_msg_and_die("error while loading section data");
                     memcpy(sec->contents, image + sec->header.sh_offset, sec->header.sh_size);
                 }
                 break;
 #if SHT_RELM == SHT_REL
             case SHT_RELA:
                 bb_simple_error_msg_and_die("RELA relocations not supported on this architecture");
 #else
             case SHT_REL:
                 bb_simple_error_msg_and_die("REL relocations not supported on this architecture");
 #endif
             default:
                 if (sec->header.sh_type >= SHT_LOPROC) {
                     /* Assume processor specific section types are debug
                        info and can safely be ignored.  If this is ever not
                        the case (Hello MIPS?), don't put ifdefs here but
                        create an arch_load_proc_section().  */
                     break;
                 }
                 bb_error_msg_and_die("can't handle sections of type %ld",
                         (long) sec->header.sh_type);
             }
         }
     }
     /* Do what sort of interpretation as needed by each section.  */
     shstrtab = f->sections[f->header.e_shstrndx]->contents;
     for (i = 0; i < shnum; ++i) {
         struct obj_section *sec = f->sections[i];
         sec->name = shstrtab + sec->header.sh_name;
     }
     for (i = 0; i < shnum; ++i) {
         struct obj_section *sec = f->sections[i];
         /* .modinfo should be contents only but gcc has no attribute for that.
          * The kernel may have marked .modinfo as ALLOC, ignore this bit.
          */
         if (strcmp(sec->name, ".modinfo") == 0)
             sec->header.sh_flags &= ~SHF_ALLOC;
         if (sec->header.sh_flags & SHF_ALLOC)
             obj_insert_section_load_order(f, sec);
         switch (sec->header.sh_type) {
         case SHT_SYMTAB:
             {
                 unsigned long nsym, j;
                 char *strtab;
                 ElfW(Sym) * sym;
                 if (sec->header.sh_entsize != sizeof(ElfW(Sym))) {
                     bb_error_msg_and_die("symbol size mismatch: %lu != %lu",
                             (unsigned long) sec->header.sh_entsize,
                             (unsigned long) sizeof(ElfW(Sym)));
                 }
                 nsym = sec->header.sh_size / sizeof(ElfW(Sym));
                 strtab = f->sections[sec->header.sh_link]->contents;
                 sym = (ElfW(Sym) *) sec->contents;
                 /* Allocate space for a table of local symbols.  */
                 j = f->local_symtab_size = sec->header.sh_info;
                 f->local_symtab = xzalloc(j * sizeof(struct obj_symbol *));
                 /* Insert all symbols into the hash table.  */
                 for (j = 1, ++sym; j < nsym; ++j, ++sym) {
                     ElfW(Addr) val = sym->st_value;
                     const char *name;
                     if (sym->st_name)
                         name = strtab + sym->st_name;
                     else if (sym->st_shndx < shnum)
                         name = f->sections[sym->st_shndx]->name;
                     else
                         continue;
 #if defined(__SH5__)
                     /*
                      * For sh64 it is possible that the target of a branch
                      * requires a mode switch (32 to 16 and back again).
                      *
                      * This is implied by the lsb being set in the target
                      * address for SHmedia mode and clear for SHcompact.
                      */
                     val |= sym->st_other & 4;
 #endif
                     obj_add_symbol(f, name, j, sym->st_info, sym->st_shndx,
                             val, sym->st_size);
                 }
             }
             break;
         case SHT_RELM:
             if (sec->header.sh_entsize != sizeof(ElfW(RelM))) {
                 bb_error_msg_and_die("relocation entry size mismatch: %lu != %lu",
                         (unsigned long) sec->header.sh_entsize,
                         (unsigned long) sizeof(ElfW(RelM)));
             }
             break;
             /* XXX  Relocation code from modutils-2.3.19 is not here.
              * Why?  That's about 20 lines of code from obj/obj_load.c,
              * which gets done in a second pass through the sections.
              * This BusyBox insmod does similar work in obj_relocate(). */
         }
     }
     return f;
 }
References alloca, arch_new_file(), arch_new_section(), bb_error_msg_and_die(), bb_simple_error_msg_and_die(), EI_CLASS, EI_DATA, EI_VERSION, ELFDATA2LSB, ELFDATA2MSB, ELFMAG_U32, ElfW, ET_REL, EV_CURRENT, f, FIX_ALIASING, i, j, memcpy, NULL, obj_add_symbol(), obj_elf_hash(), obj_insert_section_load_order(), SHF_ALLOC, SHT_LOPROC, SHT_MIPS_DWARF, SHT_NOBITS, SHT_NOTE, SHT_NULL, SHT_PROGBITS, SHT_REL, SHT_RELA, SHT_STRTAB, SHT_SYMTAB, strcmp, val, xmalloc, and xzalloc().
Referenced by bb_init_module_24().
obj_load_order_prio()
static int obj_load_order_prio (struct obj_section * a) static
Definition at line 2128 of file modutils-24.c.
 {
     unsigned long af, ac;
     af = a->header.sh_flags;
     ac = 0;
     if (a->name[0] != '.' || strlen(a->name) != 10
      || strcmp(a->name + 5, ".init") != 0
     ) {
         ac |= 32;
     }
     if (af & SHF_ALLOC)
         ac |= 16;
     if (!(af & SHF_WRITE))
         ac |= 8;
     if (af & SHF_EXECINSTR)
         ac |= 4;
     if (a->header.sh_type != SHT_NOBITS)
         ac |= 2;
     return ac;
 }
References SHF_ALLOC, SHF_EXECINSTR, SHF_WRITE, SHT_NOBITS, strcmp, and strlen().
Referenced by obj_insert_section_load_order().
obj_load_size()
static unsigned long obj_load_size (struct obj_file * f) static
Definition at line 3055 of file modutils-24.c.
 {
     unsigned long dot = 0;
     struct obj_section *sec;
     /* Finalize the positions of the sections relative to one another.  */
     for (sec = f->load_order; sec; sec = sec->load_next) {
         ElfW(Addr) align;
         align = sec->header.sh_addralign;
         if (align && (dot & (align - 1)))
             dot = (dot | (align - 1)) + 1;
         sec->header.sh_addr = dot;
         dot += sec->header.sh_size;
     }
     return dot;
 }
References dot, ElfW, and f.
Referenced by bb_init_module_24().
obj_relocate()
static int obj_relocate (struct obj_file * f, ElfW(Addr) base) static
Definition at line 3076 of file modutils-24.c.
 {
     int i, n = f->header.e_shnum;
     int ret = 1;
     /* Finalize the addresses of the sections.  */
     f->baseaddr = base;
     for (i = 0; i < n; ++i)
         f->sections[i]->header.sh_addr += base;
     /* And iterate over all of the relocations.  */
     for (i = 0; i < n; ++i) {
         struct obj_section *relsec, *symsec, *targsec, *strsec;
         ElfW(RelM) * rel, *relend;
         ElfW(Sym) * symtab;
         const char *strtab;
         relsec = f->sections[i];
         if (relsec->header.sh_type != SHT_RELM)
             continue;
         symsec = f->sections[relsec->header.sh_link];
         targsec = f->sections[relsec->header.sh_info];
         strsec = f->sections[symsec->header.sh_link];
         rel = (ElfW(RelM) *) relsec->contents;
         relend = rel + (relsec->header.sh_size / sizeof(ElfW(RelM)));
         symtab = (ElfW(Sym) *) symsec->contents;
         strtab = (const char *) strsec->contents;
         for (; rel < relend; ++rel) {
             ElfW(Addr) value = 0;
             struct obj_symbol *intsym = NULL;
             unsigned long symndx;
             ElfW(Sym) *extsym = NULL;
             const char *errmsg;
             /* Attempt to find a value to use for this relocation.  */
             symndx = ELF_R_SYM(rel->r_info);
             if (symndx) {
                 /* Note we've already checked for undefined symbols.  */
                 extsym = &symtab[symndx];
                 if (ELF_ST_BIND(extsym->st_info) == STB_LOCAL) {
                     /* Local symbols we look up in the local table to be sure
                        we get the one that is really intended.  */
                     intsym = f->local_symtab[symndx];
                 } else {
                     /* Others we look up in the hash table.  */
                     const char *name;
                     if (extsym->st_name)
                         name = strtab + extsym->st_name;
                     else
                         name = f->sections[extsym->st_shndx]->name;
                     intsym = obj_find_symbol(f, name);
                 }
                 value = obj_symbol_final_value(f, intsym);
                 intsym->referenced = 1;
             }
 #if SHT_RELM == SHT_RELA
 #if defined(__alpha__) && defined(AXP_BROKEN_GAS)
             /* Work around a nasty GAS bug, that is fixed as of 2.7.0.9.  */
             if (!extsym || !extsym->st_name
              || ELF_ST_BIND(extsym->st_info) != STB_LOCAL)
 #endif
                 value += rel->r_addend;
 #endif
             /* Do it! */
             switch (arch_apply_relocation
                     (f, targsec, /*symsec,*/ intsym, rel, value)
             ) {
             case obj_reloc_ok:
                 break;
             case obj_reloc_overflow:
                 errmsg = "Relocation overflow";
                 goto bad_reloc;
             case obj_reloc_dangerous:
                 errmsg = "Dangerous relocation";
                 goto bad_reloc;
             case obj_reloc_unhandled:
                 errmsg = "Unhandled relocation";
 bad_reloc:
                 if (extsym) {
                     bb_error_msg("%s of type %ld for %s", errmsg,
                             (long) ELF_R_TYPE(rel->r_info),
                             strtab + extsym->st_name);
                 } else {
                     bb_error_msg("%s of type %ld", errmsg,
                             (long) ELF_R_TYPE(rel->r_info));
                 }
                 ret = 0;
                 break;
             }
         }
     }
     /* Finally, take care of the patches.  */
     if (f->string_patches) {
         struct obj_string_patch *p;
         struct obj_section *strsec;
         ElfW(Addr) strsec_base;
         strsec = obj_find_section(f, ".kstrtab");
         strsec_base = strsec->header.sh_addr;
         for (p = f->string_patches; p; p = p->next) {
             struct obj_section *targsec = f->sections[p->reloc_secidx];
             *(ElfW(Addr) *) (targsec->contents + p->reloc_offset)
                 = strsec_base + p->string_offset;
         }
     }
     if (f->symbol_patches) {
         struct obj_symbol_patch *p;
         for (p = f->symbol_patches; p; p = p->next) {
             struct obj_section *targsec = f->sections[p->reloc_secidx];
             *(ElfW(Addr) *) (targsec->contents + p->reloc_offset)
                 = obj_symbol_final_value(f, p->sym);
         }
     }
     return ret;
 }
References arch_apply_relocation(), base, bb_error_msg(), ELF_R_SYM, ELF_R_TYPE, ELF_ST_BIND, ElfW, errmsg(), f, for(), i, n, obj_symbol::name, NULL, obj_find_section(), obj_find_symbol(), obj_reloc_dangerous, obj_reloc_ok, obj_reloc_overflow, obj_reloc_unhandled, p, obj_symbol::referenced, STB_LOCAL, and value.
Referenced by bb_init_module_24().
obj_string_patch()
static void obj_string_patch (struct obj_file * f, int secidx, ElfW(Addr) offset, const char * string) static
Definition at line 2891 of file modutils-24.c.
 {
     struct obj_string_patch *p;
     struct obj_section *strsec;
     size_t len = strlen(string) + 1;
     char *loc;
     p = xzalloc(sizeof(*p));
     p->next = f->string_patches;
     p->reloc_secidx = secidx;
     p->reloc_offset = offset;
     f->string_patches = p;
     strsec = obj_find_section(f, ".kstrtab");
     if (strsec == NULL) {
         strsec = obj_create_alloced_section(f, ".kstrtab", 1, len);
         /*p->string_offset = 0;*/
         loc = strsec->contents;
     } else {
         p->string_offset = strsec->header.sh_size;
         loc = obj_extend_section(strsec, len);
     }
     memcpy(loc, string, len);
 }
References f, len, memcpy, NULL, obj_create_alloced_section(), obj_extend_section(), obj_find_section(), offset, p, strlen(), and xzalloc().
Referenced by new_create_module_ksymtab(), new_create_this_module(), and new_process_module_arguments().
obj_symbol_patch()
static void obj_symbol_patch (struct obj_file * f, int secidx, ElfW(Addr) offset, struct obj_symbol * sym) static
Definition at line 2918 of file modutils-24.c.
 {
     struct obj_symbol_patch *p;
     p = xmalloc(sizeof(*p));
     p->next = f->symbol_patches;
     p->reloc_secidx = secidx;
     p->reloc_offset = offset;
     p->sym = sym;
     f->symbol_patches = p;
 }
References f, offset, p, and xmalloc.
Referenced by new_create_module_ksymtab().
print_load_map()
static void print_load_map (struct obj_file *f UNUSED_PARAM) static
Definition at line 3800 of file modutils-24.c.
 {
 }
Referenced by bb_init_module_24().
query_module()
int query_module (const char * name, int which, void * buf, size_t bufsize, size_t * ret)
Referenced by bb_init_module_24(), and new_get_kernel_symbols().
Variable Documentation
ext_modules
struct external_module* ext_modules static
Definition at line 768 of file modutils-24.c.
Referenced by add_kernel_symbols(), new_create_module_ksymtab(), and new_get_kernel_symbols().
ksyms
struct new_module_symbol* ksyms static
Definition at line 765 of file modutils-24.c.
Referenced by add_kernel_symbols(), new_get_kernel_symbols(), and new_is_kernel_checksummed().
n_ext_modules
int n_ext_modules static
Definition at line 769 of file modutils-24.c.
Referenced by add_kernel_symbols(), new_create_module_ksymtab(), and new_get_kernel_symbols().
n_ext_modules_used
int n_ext_modules_used static
Definition at line 770 of file modutils-24.c.
Referenced by add_kernel_symbols(), new_create_module_ksymtab(), and new_init_module().
nksyms
size_t nksyms static
Definition at line 766 of file modutils-24.c.
Referenced by add_kernel_symbols(), new_get_kernel_symbols(), and new_is_kernel_checksummed().