Fennix Kernel: x32 Namespace Reference
x32 Namespace Reference
Data Structures
union EFLAGS
struct TrapFrame
union DR6
union DR7
struct FXState
struct EFLAGS.__unnamed825__
struct DR6.__unnamed827__
struct DR7.__unnamed829__
Typedefs
typedef struct x32::TrapFrame TrapFrame
typedef union x32::DR6 DR6
typedef union x32::DR7 DR7
Functions
static void cpuid (uint32_t Function, uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
CPUID.
static SafeFunction void lgdt (void *gdt)
static SafeFunction void lidt (void *idt)
static SafeFunction void ltr (uint16_t Segment)
static SafeFunction void invlpg (void *Address)
static SafeFunction void fxsave (void *FXSaveArea)
static SafeFunction void fxrstor (void *FXRstorArea)
Variables
struct x32::FXState __packed
Data Structure Documentation
x32::EFLAGS
union x32::EFLAGS
Definition at line 213 of file cpu.hpp.
Data Fields
struct EFLAGS __unnamed__
uint32_t raw
x32::TrapFrame
struct x32::TrapFrame
Definition at line 263 of file cpu.hpp.
Data Fields
uint32_t cs
uint32_t eax
uint32_t ebp
uint32_t ebx
uint32_t ecx
uint32_t edi
uint32_t edx
EFLAGS eflags
uint32_t eip
uint32_t ErrorCode
uint32_t esi
uint32_t esp
uint32_t InterruptNumber
uint32_t ss
x32::DR6
union x32::DR6
Definition at line 292 of file cpu.hpp.
Data Fields
struct DR6 __unnamed__
uint64_t raw
x32::DR7
union x32::DR7
Definition at line 320 of file cpu.hpp.
Data Fields
struct DR7 __unnamed__
uint32_t raw
x32::FXState
struct x32::FXState
Definition at line 372 of file cpu.hpp.
Data Fields
uint16_t fcw FPU control word.
uint16_t fop FPU opcode.
uint16_t fsw FPU status word.
uint8_t ftw FPU tag words.
uint32_t mxcsr SSE control register.
uint32_t mxcsrmask SSE control register mask.
uint64_t rdp FPU data pointer.
uint8_t Reserved Reserved (zero)
uint64_t rip PFU instruction pointer.
uint8_t st[8][16] FPU registers (last 6 bytes reserved)
uint8_t xmm[16][16] XMM registers.
x32::EFLAGS.__unnamed825__
struct x32::EFLAGS.__unnamed825__
Definition at line 215 of file cpu.hpp.
Data Fields
uint32_t AC: 1 Alignment Check.
uint32_t AF: 1 Auxiliary Carry Flag.
uint32_t AlwaysOne: 1 Reserved.
uint32_t CF: 1 Carry Flag.
uint32_t DF: 1 Direction Flag.
uint32_t ID: 1 ID Flag.
uint32_t IF: 1 Interrupt Enable Flag.
uint32_t IOPL: 2 I/O Privilege Level.
uint32_t NT: 1 Nested Task.
uint32_t OF: 1 Overflow Flag.
uint32_t PF: 1 Parity Flag.
uint32_t Reserved0: 1 Reserved.
uint32_t Reserved1: 1 Reserved.
uint32_t Reserved2: 1 Reserved.
uint32_t RF: 1 Resume Flag.
uint32_t SF: 1 Sign Flag.
uint32_t TF: 1 Trap Flag.
uint32_t VIF: 1 Virtual Interrupt Flag.
uint32_t VIP: 1 Virtual Interrupt Pending.
uint32_t VM: 1 Virtual 8086 Mode.
uint32_t ZF: 1 Zero Flag.
x32::DR6.__unnamed827__
struct x32::DR6.__unnamed827__
Definition at line 294 of file cpu.hpp.
Data Fields
uint64_t B0: 1 Breakpoint #0 Condition Detected.
uint64_t B1: 1 Breakpoint #1 Condition Detected.
uint64_t B2: 1 Breakpoint #2 Condition Detected.
uint64_t B3: 1 Breakpoint #3 Condition Detected.
uint64_t BD: 1 Breakpoint Debug Access Detected.
uint64_t BS: 1 Breakpoint Single Step.
uint64_t BT: 1 Breakpoint Task Switch.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 15 Reserved.
x32::DR7.__unnamed829__
struct x32::DR7.__unnamed829__
Definition at line 322 of file cpu.hpp.
Data Fields
uint32_t G0: 1 Global Exact Breakpoint #0 Enabled.
uint32_t G1: 1 Global Exact Breakpoint #1 Enabled.
uint32_t G2: 1 Global Exact Breakpoint #2 Enabled.
uint32_t G3: 1 Global Exact Breakpoint #3 Enabled.
uint32_t GD: 1 General Detect Enabled.
uint32_t GE: 1 Global Exact Breakpoint Enabled.
uint32_t L0: 1 Local Exact Breakpoint #0 Enabled.
uint32_t L1: 1 Local Exact Breakpoint #1 Enabled.
uint32_t L2: 1 Local Exact Breakpoint #2 Enabled.
uint32_t L3: 1 Local Exact Breakpoint #3 Enabled.
uint32_t LE: 1 Local Exact Breakpoint Enabled.
uint32_t LEN0: 2 Length of Breakpoint #0.
uint32_t LEN1: 2 Length of Breakpoint #1.
uint32_t LEN2: 2 Length of Breakpoint #2.
uint32_t LEN3: 2 Length of Breakpoint #3.
uint32_t Reserved0: 1 Reserved.
uint32_t Reserved1: 2 Reserved.
uint32_t Reserved2: 2 Reserved.
uint32_t RW0: 2 Type of Transaction(s) to Trap.
uint32_t RW1: 2 Type of Transaction(s) to Trap.
uint32_t RW2: 2 Type of Transaction(s) to Trap.
uint32_t RW3: 2 Type of Transaction(s) to Trap.
Typedef Documentation
DR6
typedef union x32::DR6 x32::DR6
DR7
typedef union x32::DR7 x32::DR7
TrapFrame
typedef struct x32::TrapFrame x32::TrapFrame
Function Documentation
cpuid()
static void x32::cpuid (uint32_t Function, uint32_t * eax, uint32_t * ebx, uint32_t * ecx, uint32_t * edx) inline static
CPUID.
Parameters
Function Leaf
eax EAX
ebx EBX
ecx ECX
edx EDX
Definition at line 407 of file cpu.hpp.
         {
 #ifdef a32
             asmv("cpuid"
                  : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx)
                  : "a"(Function));
 #else
             UNUSED(Function);
             UNUSED(eax);
             UNUSED(ebx);
             UNUSED(ecx);
             UNUSED(edx);
 #endif
         }
References asmv(), and UNUSED.
Referenced by APIC::APIC::APIC(), CPU::CheckSIMD(), InitializeMemoryManagement(), CPU::Name(), Random::rand16(), Random::rand32(), Random::rand64(), Tasking::Task::Task(), and CPU::Vendor().
fxrstor()
static SafeFunction void x32::fxrstor (void * FXRstorArea) inline static
Definition at line 482 of file cpu.hpp.
         {
 #ifdef a32
             if (!FXRstorArea)
                 return;
             asmv("fxrstor (%0)"
                  :
                  : "r"(FXRstorArea)
                  : "memory");
 #else
             UNUSED(FXRstorArea);
 #endif
         }
References asmv(), and UNUSED.
Referenced by CPU::InitializeFeatures().
fxsave()
static SafeFunction void x32::fxsave (void * FXSaveArea) inline static
Definition at line 467 of file cpu.hpp.
         {
 #ifdef a32
             if (!FXSaveArea)
                 return;
             asmv("fxsave (%0)"
                  :
                  : "r"(FXSaveArea)
                  : "memory");
 #else
             UNUSED(FXSaveArea);
 #endif
         }
References asmv(), and UNUSED.
invlpg()
static SafeFunction void x32::invlpg (void * Address) inline static
Definition at line 455 of file cpu.hpp.
         {
 #ifdef a32
             asmv("invlpg (%0)"
                  :
                  : "r"(Address)
                  : "memory");
 #else
             UNUSED(Address);
 #endif
         }
References Address, asmv(), and UNUSED.
lgdt()
static SafeFunction void x32::lgdt (void * gdt) inline static
Definition at line 422 of file cpu.hpp.
         {
 #ifdef a32
             asmv("lgdt (%0)"
                  :
                  : "r"(gdt));
 #else
             UNUSED(gdt);
 #endif
         }
References asmv(), and UNUSED.
Referenced by GlobalDescriptorTable::Init().
lidt()
static SafeFunction void x32::lidt (void * idt) inline static
Definition at line 433 of file cpu.hpp.
         {
 #ifdef a32
             asmv("lidt (%0)"
                  :
                  : "r"(idt));
 #else
             UNUSED(idt);
 #endif
         }
References asmv(), and UNUSED.
Referenced by InterruptDescriptorTable::Init().
ltr()
static SafeFunction void x32::ltr (uint16_t Segment) inline static
Definition at line 444 of file cpu.hpp.
         {
 #ifdef a32
             asmv("ltr %0"
                  :
                  : "r"(Segment));
 #else
             UNUSED(Segment);
 #endif
         }
References asmv(), and UNUSED.
Referenced by GlobalDescriptorTable::Init().
Variable Documentation
__packed
struct x32::FXState x32::__packed