Fennix: Kernel/library/simd_strlen.cpp File Reference
simd_strlen.cpp File Reference
#include <convert.h>
#include <memory.hpp>
#include <limits.h>
#include <debug.h>
#include <cpu.hpp>
Functions
long unsigned __strlen (const char s[])
long unsigned strlen_sse (const char s[])
long unsigned strlen_sse2 (const char s[])
long unsigned strlen_sse3 (const char s[])
long unsigned strlen_ssse3 (const char s[])
long unsigned strlen_sse4_1 (const char s[])
long unsigned strlen_sse4_2 (const char s[])
Function Documentation
__strlen()
long unsigned __strlen (const char s[])
Definition at line 30 of file simd_strlen.cpp.
 {
     size_t ret = (size_t)s;
     asmv("._strlenLoop:"
          "cmpb $0, 0(%1)\n"
          "jz ._strlenExit\n"
          "cmpb $0, 1(%1)\n"
          "jz .scmp1\n"
          "cmpb $0, 2(%1)\n"
          "jz .scmp2\n"
          "cmpb $0, 3(%1)\n"
          "jz .scmp3\n"
          "cmpb $0, 4(%1)\n"
          "jz .scmp4\n"
          "cmpb $0, 5(%1)\n"
          "jz .scmp5\n"
          "cmpb $0, 6(%1)\n"
          "jz .scmp6\n"
          "cmpb $0, 7(%1)\n"
          "jz .scmp7\n"
          "add $8, %1\n"
          "jmp ._strlenLoop\n"
          ".scmp1:"
          "inc %1\n"
          "jmp ._strlenExit\n"
          ".scmp2:"
          "add $2, %1\n"
          "jmp ._strlenExit\n"
          ".scmp3:"
          "add $3, %1\n"
          "jmp ._strlenExit\n"
          ".scmp4:"
          "add $4, %1\n"
          "jmp ._strlenExit\n"
          ".scmp5:"
          "add $5, %1\n"
          "jmp ._strlenExit\n"
          ".scmp6:"
          "add $6, %1\n"
          "jmp ._strlenExit\n"
          ".scmp7:"
          "add $7, %1\n"
          "._strlenExit:"
          "mov %1, %0\n"
          : "=r"(ret) : "0"(ret));
     return ret - (size_t)s;
 }
References asmv(), and ret.
Referenced by strlen(), strlen_sse(), strlen_sse2(), strlen_sse3(), strlen_sse4_1(), and strlen_ssse3().
strlen_sse()
long unsigned strlen_sse (const char s[])
Definition at line 83 of file simd_strlen.cpp.
 {
     return __strlen(s);
 }
References __strlen().
Referenced by strlen().
strlen_sse2()
long unsigned strlen_sse2 (const char s[])
Definition at line 88 of file simd_strlen.cpp.
 {
     return __strlen(s);
 }
References __strlen().
Referenced by strlen().
strlen_sse3()
long unsigned strlen_sse3 (const char s[])
Definition at line 93 of file simd_strlen.cpp.
 {
     return __strlen(s);
 }
References __strlen().
Referenced by strlen().
strlen_sse4_1()
long unsigned strlen_sse4_1 (const char s[])
Definition at line 103 of file simd_strlen.cpp.
 {
     return __strlen(s);
 }
References __strlen().
Referenced by strlen().
strlen_sse4_2()
long unsigned strlen_sse4_2 (const char s[])
Definition at line 108 of file simd_strlen.cpp.
 {
     size_t ret;
     asmv("mov $-16, %0\n"
          "pxor %%xmm0, %%xmm0\n"
          ".strlen42Loop:"
          "add $16, %0\n"
          "pcmpistri $0x08, (%0,%1), %%xmm0\n"
          "jnz .strlen42Loop\n"
          "add %2, %0\n"
          : "=a"(ret)
          : "d"((size_t)s), "c"((size_t)s));
     return ret;
 }
References asmv(), and ret.
Referenced by strlen().
strlen_ssse3()
long unsigned strlen_ssse3 (const char s[])
Definition at line 98 of file simd_strlen.cpp.
 {
     return __strlen(s);
 }
References __strlen().
Referenced by strlen().