Fennix Userspace: Userspace/musl/src/mq/mq_notify.c File Reference
mq_notify.c File Reference
#include <mqueue.h>
#include <pthread.h>
#include <errno.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <semaphore.h>
#include "syscall.h"
Data Structures
struct args
Functions
static void * start (void *p)
int mq_notify (mqd_t mqd, const struct sigevent *sev)
Data Structure Documentation
args
struct args
Definition at line 45 of file spawn-stubs.cpp.
Data Fields
char *const * argv
const posix_spawnattr_t *__restrict attr
const posix_spawnattr_t *restrict attr
char *const *const * envp
int err
const posix_spawn_file_actions_t * fa
mqd_t mqd
sigset_t oldmask
int p[2]
const char * path
sem_t sem
const struct sigevent * sev
int sock
Function Documentation
mq_notify()
int mq_notify (mqd_t mqd, const struct sigevent * sev)
Definition at line 46 of file mq_notify.c.
 {
     struct args args = { .sev = sev };
     pthread_attr_t attr;
     pthread_t td;
     int s;
     int cs;
     sigset_t allmask, origmask;
     if (!sev || sev->sigev_notify != SIGEV_THREAD)
         return syscall(SYS_mq_notify, mqd, sev);
     s = socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, 0);
     if (s < 0) return -1;
     args.sock = s;
     args.mqd = mqd;
     if (sev->sigev_notify_attributes) attr = *sev->sigev_notify_attributes;
     else pthread_attr_init(&attr);
     pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
     sem_init(&args.sem, 0, 0);
     sigfillset(&allmask);
     pthread_sigmask(SIG_BLOCK, &allmask, &origmask);
     if (pthread_create(&td, &attr, start, &args)) {
         __syscall(SYS_close, s);
         pthread_sigmask(SIG_SETMASK, &origmask, 0);
         errno = EAGAIN;
         return -1;
     }
     pthread_sigmask(SIG_SETMASK, &origmask, 0);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     sem_wait(&args.sem);
     sem_destroy(&args.sem);
     if (args.err) {
         __syscall(SYS_close, s);
         pthread_join(td, 0);
         pthread_setcancelstate(cs, 0);
         errno = args.err;
         return -1;
     }
     pthread_setcancelstate(cs, 0);
     return 0;
 }
References __syscall, AF_NETLINK, args::attr, EAGAIN, args::err, errno, args::mqd, pthread_attr_init(), pthread_attr_setdetachstate(), PTHREAD_CANCEL_DISABLE, pthread_create(), PTHREAD_CREATE_JOINABLE, pthread_join(), pthread_setcancelstate(), pthread_sigmask(), args::sem, sem_destroy(), sem_init(), sem_wait(), args::sev, SIG_BLOCK, SIG_SETMASK, sigevent::sigev_notify, SIGEV_THREAD, sigfillset, args::sock, SOCK_CLOEXEC, SOCK_RAW, socket(), start(), and syscall().
start()
static void* start (void * p) static
Definition at line 18 of file mq_notify.c.
 {
     struct args *args = p;
     char buf[32];
     ssize_t n;
     int s = args->sock;
     void (*func)(union sigval) = args->sev->sigev_notify_function;
     union sigval val = args->sev->sigev_value;
     struct sigevent sev2;
     static const char zeros[32];
     int err;
     sev2.sigev_notify = SIGEV_THREAD;
     sev2.sigev_signo = s;
     sev2.sigev_value.sival_ptr = (void *)&zeros;
     args->err = err = -__syscall(SYS_mq_notify, args->mqd, &sev2);
     sem_post(&args->sem);
     if (err) return 0;
     pthread_detach(pthread_self());
     n = recv(s, buf, sizeof(buf), MSG_NOSIGNAL|MSG_WAITALL);
     close(s);
     if (n==sizeof buf && buf[sizeof buf - 1] == 1)
         func(val);
     return 0;
 }
References __syscall, buf, close(), err(), args::err, args::mqd, MSG_NOSIGNAL, MSG_WAITALL, n, p, pthread_detach(), pthread_self(), recv(), args::sem, sem_post(), args::sev, sigevent::sigev_notify, sigevent::sigev_notify_function, sigevent::sigev_signo, SIGEV_THREAD, sigevent::sigev_value, sigval::sival_ptr, args::sock, and val.
Referenced by __getopt_long_core(), __malloc_donate(), __mmap(), __mprotect(), __munmap(), _hs_history_patsearch(), _rl_fix_last_undo_of_type(), _rl_replace_text(), _rl_skip_to_delim(), _rl_vi_save_insert(), _rl_vi_save_replace(), aligned_alloc(), alloc_undo_entry(), AM_drawGrid(), ansiexpand(), BF_encrypt(), define_pushf(), execute_shell_script(), extract_colon_unit(), fileman_completion(), ObjectRepository::findCaller(), free(), freewords(), gen_completion_matches(), getinterp(), hist_error(), history_expand_internal(), history_substring(), history_tokenize_internal(), insert_match(), anonymous_namespace{wchar-stubs.cpp}::intable(), invert_case_line(), M_Drawer(), make_arith_for_command(), malloc_usable_size(), mq_notify(), msync(), next_pending_trap(), P_FindSectorFromLineTag(), parse_bracket_terms(), pos_params(), R_CheckBBox(), R_CheckPlane(), R_ClipPassWallSegment(), R_ClipSolidWallSegment(), R_InitSpriteDefs(), R_StoreWallRange(), realloc(), reclaim(), remove_history(), remove_history_range(), ObjectRepository::requestObjectWithName(), rl_add_undo(), rl_change_case(), rl_complete_internal(), rl_delete_horizontal_space(), rl_do_undo(), rl_modifying(), rl_tilde_expand(), sh_modcase(), skip_matched_pair(), skip_to_delim(), strftime(), anonymous_namespace{time.cpp}::strptime_internal(), substring(), tilde_expand(), tre_purge_regset(), tre_tnfa_run_parallel(), validate_path(), vi_change_dispatch(), vi_save_insert_buffer(), and Z_Malloc().