Fennix: Userspace/mlibc/tests/posix/pthread_key.c File Reference
pthread_key.c File Reference
#include <assert.h>
#include <pthread.h>
#include <errno.h>
#include <limits.h>
Functions
static void dtor1 (void *arg)
static void dtor2 (void *arg)
static void * worker1 (void *arg)
static void dtor3 (void *arg)
static void * worker2 (void *arg)
int main ()
Variables
_Atomic int dtors_entered = 0
pthread_key_t key3
Function Documentation
dtor1()
static void dtor1 (void * arg) static
Definition at line 9 of file pthread_key.c.
{
     (void)arg;
     dtors_entered++;
     // Set the key during destruction to trigger dtor2 (as it only runs if
     // the key value is non-NULL).
     assert(!pthread_setspecific(key3, &key3));
     assert(pthread_getspecific(key3) == &key3);
 }
References mlibc::arg, assert, dtors_entered, key3, pthread_getspecific(), pthread_setspecific(), and Driver::void().
Referenced by worker1().
dtor2()
static void dtor2 (void * arg) static
Definition at line 19 of file pthread_key.c.
{
     (void)arg;
     dtors_entered++;
 }
References mlibc::arg, dtors_entered, and Driver::void().
Referenced by worker1().
dtor3()
static void dtor3 (void * arg) static
Definition at line 42 of file pthread_key.c.
{
     (void)arg;
     // Make sure that we can create and destroy keys inside the dtor.
     pthread_key_t dtorKey;
     assert(!pthread_key_create(&dtorKey, NULL));
     assert(!pthread_setspecific(dtorKey, &dtorKey));
     assert(pthread_getspecific(dtorKey) == &dtorKey);
     assert(!pthread_key_delete(dtorKey));
 }
References mlibc::arg, assert, NULL, pthread_getspecific(), pthread_key_create(), pthread_key_delete(), pthread_setspecific(), and Driver::void().
Referenced by worker2().
main()
int main (void)
Definition at line 68 of file pthread_key.c.
            {
     // NOTE that the EINVAL return from pthread_setspecific is mlibc-specific,
     // POSIX specifies that accessing an invalid key is undefined behavior.
     assert(pthread_getspecific(PTHREAD_KEYS_MAX) == NULL);
     assert(pthread_setspecific(PTHREAD_KEYS_MAX, NULL) == EINVAL);
     pthread_key_t key;
     assert(!pthread_key_create(&key, NULL));
     assert(!pthread_setspecific(key, &key));
     assert(pthread_getspecific(key) == &key);
     assert(!pthread_key_delete(key));
     pthread_t thread;
     assert(!pthread_create(&thread, NULL, &worker1, NULL));
     assert(!pthread_join(thread, NULL));
     assert(pthread_getspecific(key) == NULL);
     assert(!pthread_setspecific(key, &key));
     assert(pthread_getspecific(key) == &key);
     assert(dtors_entered == 2);
     assert(!pthread_create(&thread, NULL, &worker2, NULL));
     assert(!pthread_join(thread, NULL));
     return 0;
 }
References assert, dtors_entered, EINVAL, CrashHandler::key, NULL, pthread_create(), pthread_getspecific(), pthread_join(), pthread_key_create(), pthread_key_delete(), PTHREAD_KEYS_MAX, pthread_setspecific(), worker1(), and worker2().
worker1()
static void* worker1 (void * arg) static
Definition at line 24 of file pthread_key.c.
{
     (void)arg;
     pthread_key_t key1, key2;
     assert(!pthread_key_create(&key1, NULL));
     assert(!pthread_key_create(&key2, dtor1));
     assert(!pthread_key_create(&key3, dtor2));
     assert(!pthread_setspecific(key1, &key1));
     assert(pthread_getspecific(key1) == &key1);
     assert(!pthread_setspecific(key2, &key2));
     assert(pthread_getspecific(key2) == &key2);
     pthread_exit(0);
     return NULL;
 }
References mlibc::arg, assert, dtor1(), dtor2(), key3, NULL, pthread_exit(), pthread_getspecific(), pthread_key_create(), pthread_setspecific(), and Driver::void().
Referenced by main().
worker2()
static void* worker2 (void * arg) static
Definition at line 55 of file pthread_key.c.
{
     (void)arg;
     pthread_key_t key;
     assert(!pthread_key_create(&key, dtor3));
     assert(!pthread_setspecific(key, &key));
     assert(pthread_getspecific(key) == &key);
     pthread_exit(0);
     return NULL;
 }
References mlibc::arg, assert, dtor3(), CrashHandler::key, NULL, pthread_exit(), pthread_getspecific(), pthread_key_create(), pthread_setspecific(), and Driver::void().
Referenced by main().
Variable Documentation
dtors_entered
_Atomic int dtors_entered = 0
Definition at line 6 of file pthread_key.c.
Referenced by dtor1(), dtor2(), and main().
key3
pthread_key_t key3
Definition at line 7 of file pthread_key.c.
Referenced by dtor1(), and worker1().