Fennix Userspace: Userspace/mlibc/options/posix/generic/sys-mman-stubs.cpp File Reference
sys-mman-stubs.cpp File Reference
#include <errno.h>
#include <limits.h>
#include <pthread.h>
#include <unistd.h>
#include <sys/mman.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Namespaces
anonymous_namespace{sys-mman-stubs.cpp}
Functions
int mprotect (void *pointer, size_t size, int prot)
int mlock (const void *addr, size_t len)
int mlockall (int flags)
int munlock (const void *addr, size_t len)
int munlockall (void)
int posix_madvise (void *, size_t, int)
int msync (void *addr, size_t length, int flags)
void * mremap (void *pointer, size_t size, size_t new_size, int flags,...)
int remap_file_pages (void *, size_t, int, size_t, int)
void * mmap (void *hint, size_t size, int prot, int flags, int fd, off_t offset)
int munmap (void *pointer, size_t size)
char * anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname (const char *name, char *buf)
int shm_open (const char *name, int flags, mode_t mode)
int shm_unlink (const char *name)
Function Documentation
mlock()
int mlock (const void * addr, size_t len)
Definition at line 21 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mlock, -1);
     if(int e = mlibc::sys_mlock(addr, len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mlock().
mlockall()
int mlockall (int flags)
Definition at line 30 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mlockall, -1);
     if(int e = mlibc::sys_mlockall(flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mlockall().
mmap()
void* mmap (void * hint, size_t size, int prot, int flags, int fd, off_t offset)
Definition at line 90 of file sys-mman-stubs.cpp.
{
     void *window;
     if(int e = mlibc::sys_vm_map(hint, size, prot, flags, fd, offset, &window); e) {
         errno = e;
         return (void *)-1;
     }
     return window;
 }
References errno, fd, mlibc::flags, offset, mlibc::prot, size, mlibc::sys_vm_map(), and mlibc::window.
Referenced by mlibc::sys_prepare_stack(), and test_stackaddr().
mprotect()
int mprotect (void * pointer, size_t size, int prot)
Definition at line 12 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_vm_protect, -1);
     if(int e = mlibc::sys_vm_protect(pointer, size, prot); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::prot, size, and mlibc::sys_vm_protect().
mremap()
void* mremap (void * pointer, size_t size, size_t new_size, int flags, ...)
Definition at line 73 of file sys-mman-stubs.cpp.
{
     __ensure(flags == MREMAP_MAYMOVE);
     void *window;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_vm_remap, (void *)-1);
     if(int e = mlibc::sys_vm_remap(pointer, size, new_size, &window); e) {
         errno = e;
         return (void *)-1;
     }
     return window;
 }
References __ensure, errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, MREMAP_MAYMOVE, size, mlibc::sys_vm_remap(), and mlibc::window.
msync()
int msync (void * addr, size_t length, int flags)
Definition at line 64 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msync, -1);
     if(int e = mlibc::sys_msync(addr, length, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_msync().
munlock()
int munlock (const void * addr, size_t len)
Definition at line 39 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_munlock, -1);
     if(int e = mlibc::sys_munlock(addr, len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_munlock().
munlockall()
int munlockall (void)
Definition at line 48 of file sys-mman-stubs.cpp.
                      {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_munlockall, -1);
     if(int e = mlibc::sys_munlockall(); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_munlockall().
munmap()
int munmap (void * pointer, size_t size)
Definition at line 99 of file sys-mman-stubs.cpp.
{
     if(int e = mlibc::sys_vm_unmap(pointer, size); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, size, and mlibc::sys_vm_unmap().
posix_madvise()
int posix_madvise (void * , size_t , int)
Definition at line 58 of file sys-mman-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31m" "mlibc: posix_madvise() fails unconditionally" "\e[39m"
             << frg::endlog;
     return ENOSYS;
 }
References ENOSYS, and mlibc::infoLogger.
remap_file_pages()
int remap_file_pages (void * , size_t , int , size_t , int)
Definition at line 85 of file sys-mman-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
shm_open()
int shm_open (const char * name, int flags, mode_t mode)
Definition at line 128 of file sys-mman-stubs.cpp.
{
     int cs;
     char buf[NAME_MAX + 10];
     if(!(name = shm_mapname(name, buf)))
         return -1;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     int fd = open(name, flags | O_NOFOLLOW | O_CLOEXEC | O_NONBLOCK, mode);
     pthread_setcancelstate(cs, 0);
     return fd;
 }
References buf, fd, mlibc::flags, name, NAME_MAX, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, open(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname().
shm_unlink()
int shm_unlink (const char * name)
Definition at line 139 of file sys-mman-stubs.cpp.
{
     char buf[NAME_MAX + 10];
     if(!(name = shm_mapname(name, buf)))
         return -1;
     return unlink(name);
 }
References buf, name, NAME_MAX, anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname(), and unlink().