Fennix: Userspace/mlibc/options/posix/include/unistd.h File Reference
unistd.h File Reference
#include <mlibc-config.h>
#include <bits/types.h>
#include <bits/size_t.h>
#include <bits/ssize_t.h>
#include <bits/off_t.h>
#include <abi-bits/access.h>
#include <abi-bits/uid_t.h>
#include <abi-bits/gid_t.h>
#include <abi-bits/pid_t.h>
Macros
#define _POSIX_VERSION 200809L
#define _POSIX2_VERSION _POSIX_VERSION
#define _XOPEN_VERSION 700
#define _POSIX_FSYNC _POSIX_VERSION
#define _POSIX_IPV6 _POSIX_VERSION
#define _POSIX_JOB_CONTROL 1
#define _POSIX_SAVED_IDS 1
#define _POSIX_SHELL 1
#define _POSIX_SPAWN _POSIX_VERSION
#define _POSIX_THREADS _POSIX_VERSION
#define _POSIX_THREAD_SAFE_FUNCTIONS _POSIX_VERSION
#define _POSIX_MONOTONIC_CLOCK 0
#define _CS_PATH 0
#define _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS 1
#define _CS_GNU_LIBC_VERSION 2
#define _CS_GNU_LIBPTHREAD_VERSION 3
#define _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS 4
#define _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS 5
#define _CS_POSIX_V6_ILP32_OFF32_CFLAGS 1116
#define _CS_POSIX_V6_ILP32_OFF32_LDFLAGS 1117
#define _CS_POSIX_V6_ILP32_OFF32_LIBS 1118
#define _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS 1119
#define _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS 1120
#define _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS 1121
#define _CS_POSIX_V6_ILP32_OFFBIG_LIBS 1122
#define _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS 1123
#define _CS_POSIX_V6_LP64_OFF64_CFLAGS 1124
#define _CS_POSIX_V6_LP64_OFF64_LDFLAGS 1125
#define _CS_POSIX_V6_LP64_OFF64_LIBS 1126
#define _CS_POSIX_V6_LP64_OFF64_LINTFLAGS 1127
#define _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS 1128
#define _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS 1129
#define _CS_POSIX_V6_LPBIG_OFFBIG_LIBS 1130
#define _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS 1131
#define _CS_POSIX_V7_ILP32_OFF32_CFLAGS 1132
#define _CS_POSIX_V7_ILP32_OFF32_LDFLAGS 1133
#define _CS_POSIX_V7_ILP32_OFF32_LIBS 1134
#define _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS 1135
#define _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS 1136
#define _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS 1137
#define _CS_POSIX_V7_ILP32_OFFBIG_LIBS 1138
#define _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS 1139
#define _CS_POSIX_V7_LP64_OFF64_CFLAGS 1140
#define _CS_POSIX_V7_LP64_OFF64_LDFLAGS 1141
#define _CS_POSIX_V7_LP64_OFF64_LIBS 1142
#define _CS_POSIX_V7_LP64_OFF64_LINTFLAGS 1143
#define _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS 1144
#define _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS 1145
#define _CS_POSIX_V7_LPBIG_OFFBIG_LIBS 1146
#define _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS 1147
#define _CS_V6_ENV 1148
#define _CS_V7_ENV 1149
#define F_LOCK 1
#define F_TEST 2
#define F_TLOCK 3
#define F_ULOCK 4
#define _PC_LINK_MAX 0
#define _PC_MAX_CANON 1
#define _PC_MAX_INPUT 2
#define _PC_NAME_MAX 3
#define _PC_PATH_MAX 4
#define _PC_PIPE_BUF 5
#define _PC_CHOWN_RESTRICTED 6
#define _PC_NO_TRUNC 7
#define _PC_VDISABLE 8
#define _PC_FILESIZEBITS 9
#define _PC_SYMLINK_MAX 10
#define _SC_ARG_MAX 0
#define _SC_GETPW_R_SIZE_MAX 1
#define _SC_PHYS_PAGES 2
#define _SC_PAGE_SIZE 3
#define _SC_PAGESIZE _SC_PAGE_SIZE
#define _SC_OPEN_MAX 5
#define _SC_NPROCESSORS_ONLN 6
#define _SC_GETGR_R_SIZE_MAX 7
#define _SC_CHILD_MAX 8
#define _SC_CLK_TCK 9
#define _SC_NGROUPS_MAX 10
#define _SC_VERSION 11
#define _SC_SAVED_IDS 12
#define _SC_JOB_CONTROL 13
#define _SC_HOST_NAME_MAX 14
#define _SC_LINE_MAX 15
#define _SC_XOPEN_CRYPT 16
#define _SC_NPROCESSORS_CONF 17
#define _SC_SYMLOOP_MAX 18
#define _SC_TTY_NAME_MAX 19
#define _SC_RE_DUP_MAX 20
#define _SC_ATEXIT_MAX 21
#define _SC_LOGIN_NAME_MAX 22
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 23
#define _SC_THREAD_KEYS_MAX 24
#define _SC_THREAD_STACK_MIN 25
#define _SC_THREAD_THREADS_MAX 26
#define _SC_TZNAME_MAX 27
#define _SC_ASYNCHRONOUS_IO 28
#define _SC_FSYNC 29
#define _SC_MAPPED_FILES 30
#define _SC_MEMLOCK 31
#define _SC_MEMLOCK_RANGE 32
#define _SC_MEMORY_PROTECTION 33
#define _SC_MESSAGE_PASSING 34
#define _SC_PRIORITY_SCHEDULING 35
#define _SC_REALTIME_SIGNALS 36
#define _SC_SEMAPHORES 37
#define _SC_SHARED_MEMORY_OBJECTS 38
#define _SC_SYNCHRONIZED_IO 39
#define _SC_THREADS 40
#define _SC_THREAD_ATTR_STACKADDR 41
#define _SC_THREAD_ATTR_STACKSIZE 42
#define _SC_THREAD_PRIORITY_SCHEDULING 43
#define _SC_THREAD_PRIO_INHERIT 44
#define _SC_THREAD_PRIO_PROTECT 45
#define _SC_THREAD_PROCESS_SHARED 46
#define _SC_THREAD_SAFE_FUNCTIONS 47
#define _SC_TIMERS 48
#define _SC_TIMER_MAX 49
#define _SC_2_CHAR_TERM 50
#define _SC_2_C_BIND 51
#define _SC_2_C_DEV 52
#define _SC_2_FORT_DEV 53
#define _SC_2_FORT_RUN 54
#define _SC_2_LOCALEDEF 55
#define _SC_2_SW_DEV 56
#define _SC_2_UPE 57
#define _SC_2_VERSION 58
#define _SC_CLOCK_SELECTION 59
#define _SC_CPUTIME 60
#define _SC_THREAD_CPUTIME 61
#define _SC_MONOTONIC_CLOCK 62
#define _SC_READER_WRITER_LOCKS 63
#define _SC_SPIN_LOCKS 64
#define _SC_REGEXP 65
#define _SC_SHELL 66
#define _SC_SPAWN 67
#define _SC_2_PBS 68
#define _SC_2_PBS_ACCOUNTING 69
#define _SC_2_PBS_LOCATE 70
#define _SC_2_PBS_TRACK 71
#define _SC_2_PBS_MESSAGE 72
#define _SC_STREAM_MAX 73
#define _SC_AIO_LISTIO_MAX 74
#define _SC_AIO_MAX 75
#define _SC_DELAYTIMER_MAX 76
#define _SC_MQ_OPEN_MAX 77
#define _SC_MQ_PRIO_MAX 78
#define _SC_RTSIG_MAX 79
#define _SC_SIGQUEUE_MAX 80
#define STDERR_FILENO 2
#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define _POSIX_VDISABLE (-1)
#define L_ctermid 20
Typedefs
typedef __mlibc_uint64 useconds_t
Functions
int access (const char *path, int mode)
unsigned int alarm (unsigned int seconds)
int chdir (const char *path)
int chown (const char *path, uid_t uid, gid_t gid)
int close (int fd)
ssize_t confstr (int, char *, size_t)
char * ctermid (char *s)
int dup (int fd)
int dup2 (int src_fd, int dest_fd)
__attribute__ ((noreturn)) void _exit(int status)
void endusershell (void)
int execl (const char *, const char *,...)
int execle (const char *, const char *,...)
int execlp (const char *, const char *,...)
int execv (const char *, char *const [])
int execve (const char *path, char *const argv[], char *const envp[])
int execvp (const char *, char *const[])
int execvpe (const char *path, char *const argv[], char *const envp[])
int faccessat (int, const char *, int, int)
int fchdir (int fd)
int fchown (int fd, uid_t uid, gid_t gid)
int fchownat (int fd, const char *path, uid_t uid, gid_t gid, int flags)
int fdatasync (int)
int fexecve (int, char *const [], char *const [])
pid_t fork (void)
pid_t vfork (void)
long fpathconf (int, int)
int fsync (int)
int ftruncate (int, off_t)
char * getcwd (char *, size_t)
gid_t getegid (void)
uid_t geteuid (void)
gid_t getgid (void)
int getgroups (int, gid_t[])
long gethostid (void)
int gethostname (char *buffer, size_t max_length)
int sethostname (const char *buffer, size_t max_length)
char * getlogin (void)
int getlogin_r (char *, size_t)
int getopt (int, char *const [], const char *)
char * getpass (const char *)
pid_t getpgid (pid_t)
pid_t getpgrp (void)
pid_t getpid (void)
pid_t getppid (void)
pid_t getsid (pid_t)
uid_t getuid (void)
char * getusershell (void)
int isatty (int fd)
int lchown (const char *path, uid_t uid, gid_t gid)
int link (const char *, const char *)
int linkat (int, const char *, int, const char *, int)
int lockf (int, int, off_t)
off_t lseek (int fd, off_t offset, int whence)
off64_t lseek64 (int fd, off64_t offset, int whence)
int nice (int)
long pathconf (const char *, int)
int pause (void)
int pipe (int[2])
ssize_t pread (int, void *, size_t, off_t)
ssize_t pwrite (int, const void *, size_t, off_t)
ssize_t read (int fd, void *buffer, size_t size)
ssize_t readlink (const char *__restrict, char *__restrict, size_t)
ssize_t readlinkat (int, const char *__restrict, char *__restrict, size_t)
int rmdir (const char *)
int setegid (gid_t)
int seteuid (uid_t)
int setgid (gid_t)
int setpgid (pid_t, pid_t)
pid_t setpgrp (void)
int setregid (gid_t, gid_t)
int setreuid (uid_t, uid_t)
pid_t setsid (void)
int setuid (uid_t)
void setusershell (void)
unsigned int sleep (unsigned int)
void swab (const void *__restrict, void *__restrict, ssize_t)
int symlink (const char *, const char *)
int symlinkat (const char *, int, const char *)
void sync (void)
unsigned long sysconf (int)
pid_t tcgetpgrp (int)
int tcsetpgrp (int, pid_t)
int truncate (const char *, off_t)
char * ttyname (int)
int ttyname_r (int, char *, size_t)
int unlink (const char *)
int unlinkat (int, const char *, int)
ssize_t write (int fd, const void *buffer, size_t size)
int getpagesize (void)
char * get_current_dir_name (void)
int usleep (useconds_t)
int chroot (const char *)
int daemon (int, int)
pid_t gettid (void)
int getentropy (void *, size_t)
int pipe2 (int *pipefd, int flags)
int setresuid (uid_t ruid, uid_t euid, uid_t suid)
int setresgid (gid_t rgid, gid_t egid, gid_t sgid)
int getdomainname (char *name, size_t len)
int setdomainname (const char *name, size_t len)
int getresuid (uid_t *ruid, uid_t *euid, uid_t *suid)
int getresgid (gid_t *rgid, gid_t *egid, gid_t *sgid)
Variables
char ** environ
char * optarg
int optind
int opterr
int optopt
Macro Definition Documentation
_CS_GNU_LIBC_VERSION
#define _CS_GNU_LIBC_VERSION 2
Definition at line 46 of file unistd.h.
_CS_GNU_LIBPTHREAD_VERSION
#define _CS_GNU_LIBPTHREAD_VERSION 3
Definition at line 47 of file unistd.h.
_CS_PATH
#define _CS_PATH 0
Definition at line 44 of file unistd.h.
_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS 4
Definition at line 48 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_CFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_CFLAGS 1116
Definition at line 51 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LDFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_LDFLAGS 1117
Definition at line 52 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LIBS
#define _CS_POSIX_V6_ILP32_OFF32_LIBS 1118
Definition at line 53 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS 1119
Definition at line 54 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS 1120
Definition at line 55 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS 1121
Definition at line 56 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LIBS
#define _CS_POSIX_V6_ILP32_OFFBIG_LIBS 1122
Definition at line 57 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS 1123
Definition at line 58 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_CFLAGS
#define _CS_POSIX_V6_LP64_OFF64_CFLAGS 1124
Definition at line 59 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LDFLAGS
#define _CS_POSIX_V6_LP64_OFF64_LDFLAGS 1125
Definition at line 60 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LIBS
#define _CS_POSIX_V6_LP64_OFF64_LIBS 1126
Definition at line 61 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LINTFLAGS
#define _CS_POSIX_V6_LP64_OFF64_LINTFLAGS 1127
Definition at line 62 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS 1128
Definition at line 63 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS 1129
Definition at line 64 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LIBS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LIBS 1130
Definition at line 65 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS 1131
Definition at line 66 of file unistd.h.
_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS 1
Definition at line 45 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_CFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_CFLAGS 1132
Definition at line 67 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LDFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_LDFLAGS 1133
Definition at line 68 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LIBS
#define _CS_POSIX_V7_ILP32_OFF32_LIBS 1134
Definition at line 69 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS 1135
Definition at line 70 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS 1136
Definition at line 71 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS 1137
Definition at line 72 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LIBS
#define _CS_POSIX_V7_ILP32_OFFBIG_LIBS 1138
Definition at line 73 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS 1139
Definition at line 74 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_CFLAGS
#define _CS_POSIX_V7_LP64_OFF64_CFLAGS 1140
Definition at line 75 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LDFLAGS
#define _CS_POSIX_V7_LP64_OFF64_LDFLAGS 1141
Definition at line 76 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LIBS
#define _CS_POSIX_V7_LP64_OFF64_LIBS 1142
Definition at line 77 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LINTFLAGS
#define _CS_POSIX_V7_LP64_OFF64_LINTFLAGS 1143
Definition at line 78 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS 1144
Definition at line 79 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS 1145
Definition at line 80 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LIBS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LIBS 1146
Definition at line 81 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS 1147
Definition at line 82 of file unistd.h.
_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS 5
Definition at line 49 of file unistd.h.
_CS_V6_ENV
#define _CS_V6_ENV 1148
Definition at line 83 of file unistd.h.
_CS_V7_ENV
#define _CS_V7_ENV 1149
Definition at line 84 of file unistd.h.
_PC_CHOWN_RESTRICTED
#define _PC_CHOWN_RESTRICTED 6
Definition at line 101 of file unistd.h.
_PC_FILESIZEBITS
#define _PC_FILESIZEBITS 9
Definition at line 105 of file unistd.h.
_PC_LINK_MAX
#define _PC_LINK_MAX 0
Definition at line 95 of file unistd.h.
_PC_MAX_CANON
#define _PC_MAX_CANON 1
Definition at line 96 of file unistd.h.
_PC_MAX_INPUT
#define _PC_MAX_INPUT 2
Definition at line 97 of file unistd.h.
_PC_NAME_MAX
#define _PC_NAME_MAX 3
Definition at line 98 of file unistd.h.
_PC_NO_TRUNC
#define _PC_NO_TRUNC 7
Definition at line 102 of file unistd.h.
_PC_PATH_MAX
#define _PC_PATH_MAX 4
Definition at line 99 of file unistd.h.
_PC_PIPE_BUF
#define _PC_PIPE_BUF 5
Definition at line 100 of file unistd.h.
_PC_SYMLINK_MAX
#define _PC_SYMLINK_MAX 10
Definition at line 106 of file unistd.h.
_PC_VDISABLE
#define _PC_VDISABLE 8
Definition at line 103 of file unistd.h.
_POSIX2_VERSION
#define _POSIX2_VERSION _POSIX_VERSION
Definition at line 24 of file unistd.h.
_POSIX_FSYNC
#define _POSIX_FSYNC _POSIX_VERSION
Definition at line 27 of file unistd.h.
_POSIX_IPV6
#define _POSIX_IPV6 _POSIX_VERSION
Definition at line 28 of file unistd.h.
_POSIX_JOB_CONTROL
#define _POSIX_JOB_CONTROL 1
Definition at line 29 of file unistd.h.
_POSIX_MONOTONIC_CLOCK
#define _POSIX_MONOTONIC_CLOCK 0
Definition at line 35 of file unistd.h.
_POSIX_SAVED_IDS
#define _POSIX_SAVED_IDS 1
Definition at line 30 of file unistd.h.
_POSIX_SHELL
#define _POSIX_SHELL 1
Definition at line 31 of file unistd.h.
_POSIX_SPAWN
#define _POSIX_SPAWN _POSIX_VERSION
Definition at line 32 of file unistd.h.
_POSIX_THREAD_SAFE_FUNCTIONS
#define _POSIX_THREAD_SAFE_FUNCTIONS _POSIX_VERSION
Definition at line 34 of file unistd.h.
_POSIX_THREADS
#define _POSIX_THREADS _POSIX_VERSION
Definition at line 33 of file unistd.h.
_POSIX_VDISABLE
#define _POSIX_VDISABLE (-1)
Definition at line 197 of file unistd.h.
_POSIX_VERSION
#define _POSIX_VERSION 200809L
Definition at line 23 of file unistd.h.
_SC_2_C_BIND
#define _SC_2_C_BIND 51
Definition at line 162 of file unistd.h.
_SC_2_C_DEV
#define _SC_2_C_DEV 52
Definition at line 163 of file unistd.h.
_SC_2_CHAR_TERM
#define _SC_2_CHAR_TERM 50
Definition at line 161 of file unistd.h.
_SC_2_FORT_DEV
#define _SC_2_FORT_DEV 53
Definition at line 164 of file unistd.h.
_SC_2_FORT_RUN
#define _SC_2_FORT_RUN 54
Definition at line 165 of file unistd.h.
_SC_2_LOCALEDEF
#define _SC_2_LOCALEDEF 55
Definition at line 166 of file unistd.h.
_SC_2_PBS
#define _SC_2_PBS 68
Definition at line 179 of file unistd.h.
_SC_2_PBS_ACCOUNTING
#define _SC_2_PBS_ACCOUNTING 69
Definition at line 180 of file unistd.h.
_SC_2_PBS_LOCATE
#define _SC_2_PBS_LOCATE 70
Definition at line 181 of file unistd.h.
_SC_2_PBS_MESSAGE
#define _SC_2_PBS_MESSAGE 72
Definition at line 183 of file unistd.h.
_SC_2_PBS_TRACK
#define _SC_2_PBS_TRACK 71
Definition at line 182 of file unistd.h.
_SC_2_SW_DEV
#define _SC_2_SW_DEV 56
Definition at line 167 of file unistd.h.
_SC_2_UPE
#define _SC_2_UPE 57
Definition at line 168 of file unistd.h.
_SC_2_VERSION
#define _SC_2_VERSION 58
Definition at line 169 of file unistd.h.
_SC_AIO_LISTIO_MAX
#define _SC_AIO_LISTIO_MAX 74
Definition at line 185 of file unistd.h.
_SC_AIO_MAX
#define _SC_AIO_MAX 75
Definition at line 186 of file unistd.h.
_SC_ARG_MAX
#define _SC_ARG_MAX 0
Definition at line 109 of file unistd.h.
_SC_ASYNCHRONOUS_IO
#define _SC_ASYNCHRONOUS_IO 28
Definition at line 139 of file unistd.h.
_SC_ATEXIT_MAX
#define _SC_ATEXIT_MAX 21
Definition at line 132 of file unistd.h.
_SC_CHILD_MAX
#define _SC_CHILD_MAX 8
Definition at line 118 of file unistd.h.
_SC_CLK_TCK
#define _SC_CLK_TCK 9
Definition at line 119 of file unistd.h.
_SC_CLOCK_SELECTION
#define _SC_CLOCK_SELECTION 59
Definition at line 170 of file unistd.h.
_SC_CPUTIME
#define _SC_CPUTIME 60
Definition at line 171 of file unistd.h.
_SC_DELAYTIMER_MAX
#define _SC_DELAYTIMER_MAX 76
Definition at line 187 of file unistd.h.
_SC_FSYNC
#define _SC_FSYNC 29
Definition at line 140 of file unistd.h.
_SC_GETGR_R_SIZE_MAX
#define _SC_GETGR_R_SIZE_MAX 7
Definition at line 116 of file unistd.h.
_SC_GETPW_R_SIZE_MAX
#define _SC_GETPW_R_SIZE_MAX 1
Definition at line 110 of file unistd.h.
_SC_HOST_NAME_MAX
#define _SC_HOST_NAME_MAX 14
Definition at line 124 of file unistd.h.
_SC_JOB_CONTROL
#define _SC_JOB_CONTROL 13
Definition at line 123 of file unistd.h.
_SC_LINE_MAX
#define _SC_LINE_MAX 15
Definition at line 125 of file unistd.h.
_SC_LOGIN_NAME_MAX
#define _SC_LOGIN_NAME_MAX 22
Definition at line 133 of file unistd.h.
_SC_MAPPED_FILES
#define _SC_MAPPED_FILES 30
Definition at line 141 of file unistd.h.
_SC_MEMLOCK
#define _SC_MEMLOCK 31
Definition at line 142 of file unistd.h.
_SC_MEMLOCK_RANGE
#define _SC_MEMLOCK_RANGE 32
Definition at line 143 of file unistd.h.
_SC_MEMORY_PROTECTION
#define _SC_MEMORY_PROTECTION 33
Definition at line 144 of file unistd.h.
_SC_MESSAGE_PASSING
#define _SC_MESSAGE_PASSING 34
Definition at line 145 of file unistd.h.
_SC_MONOTONIC_CLOCK
#define _SC_MONOTONIC_CLOCK 62
Definition at line 173 of file unistd.h.
_SC_MQ_OPEN_MAX
#define _SC_MQ_OPEN_MAX 77
Definition at line 188 of file unistd.h.
_SC_MQ_PRIO_MAX
#define _SC_MQ_PRIO_MAX 78
Definition at line 189 of file unistd.h.
_SC_NGROUPS_MAX
#define _SC_NGROUPS_MAX 10
Definition at line 120 of file unistd.h.
_SC_NPROCESSORS_CONF
#define _SC_NPROCESSORS_CONF 17
Definition at line 127 of file unistd.h.
_SC_NPROCESSORS_ONLN
#define _SC_NPROCESSORS_ONLN 6
Definition at line 115 of file unistd.h.
_SC_OPEN_MAX
#define _SC_OPEN_MAX 5
Definition at line 114 of file unistd.h.
_SC_PAGE_SIZE
#define _SC_PAGE_SIZE 3
Definition at line 112 of file unistd.h.
_SC_PAGESIZE
#define _SC_PAGESIZE _SC_PAGE_SIZE
Definition at line 113 of file unistd.h.
_SC_PHYS_PAGES
#define _SC_PHYS_PAGES 2
Definition at line 111 of file unistd.h.
_SC_PRIORITY_SCHEDULING
#define _SC_PRIORITY_SCHEDULING 35
Definition at line 146 of file unistd.h.
_SC_RE_DUP_MAX
#define _SC_RE_DUP_MAX 20
Definition at line 130 of file unistd.h.
_SC_READER_WRITER_LOCKS
#define _SC_READER_WRITER_LOCKS 63
Definition at line 174 of file unistd.h.
_SC_REALTIME_SIGNALS
#define _SC_REALTIME_SIGNALS 36
Definition at line 147 of file unistd.h.
_SC_REGEXP
#define _SC_REGEXP 65
Definition at line 176 of file unistd.h.
_SC_RTSIG_MAX
#define _SC_RTSIG_MAX 79
Definition at line 190 of file unistd.h.
_SC_SAVED_IDS
#define _SC_SAVED_IDS 12
Definition at line 122 of file unistd.h.
_SC_SEMAPHORES
#define _SC_SEMAPHORES 37
Definition at line 148 of file unistd.h.
_SC_SHARED_MEMORY_OBJECTS
#define _SC_SHARED_MEMORY_OBJECTS 38
Definition at line 149 of file unistd.h.
_SC_SHELL
#define _SC_SHELL 66
Definition at line 177 of file unistd.h.
_SC_SIGQUEUE_MAX
#define _SC_SIGQUEUE_MAX 80
Definition at line 191 of file unistd.h.
_SC_SPAWN
#define _SC_SPAWN 67
Definition at line 178 of file unistd.h.
_SC_SPIN_LOCKS
#define _SC_SPIN_LOCKS 64
Definition at line 175 of file unistd.h.
_SC_STREAM_MAX
#define _SC_STREAM_MAX 73
Definition at line 184 of file unistd.h.
_SC_SYMLOOP_MAX
#define _SC_SYMLOOP_MAX 18
Definition at line 128 of file unistd.h.
_SC_SYNCHRONIZED_IO
#define _SC_SYNCHRONIZED_IO 39
Definition at line 150 of file unistd.h.
_SC_THREAD_ATTR_STACKADDR
#define _SC_THREAD_ATTR_STACKADDR 41
Definition at line 152 of file unistd.h.
_SC_THREAD_ATTR_STACKSIZE
#define _SC_THREAD_ATTR_STACKSIZE 42
Definition at line 153 of file unistd.h.
_SC_THREAD_CPUTIME
#define _SC_THREAD_CPUTIME 61
Definition at line 172 of file unistd.h.
_SC_THREAD_DESTRUCTOR_ITERATIONS
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 23
Definition at line 134 of file unistd.h.
_SC_THREAD_KEYS_MAX
#define _SC_THREAD_KEYS_MAX 24
Definition at line 135 of file unistd.h.
_SC_THREAD_PRIO_INHERIT
#define _SC_THREAD_PRIO_INHERIT 44
Definition at line 155 of file unistd.h.
_SC_THREAD_PRIO_PROTECT
#define _SC_THREAD_PRIO_PROTECT 45
Definition at line 156 of file unistd.h.
_SC_THREAD_PRIORITY_SCHEDULING
#define _SC_THREAD_PRIORITY_SCHEDULING 43
Definition at line 154 of file unistd.h.
_SC_THREAD_PROCESS_SHARED
#define _SC_THREAD_PROCESS_SHARED 46
Definition at line 157 of file unistd.h.
_SC_THREAD_SAFE_FUNCTIONS
#define _SC_THREAD_SAFE_FUNCTIONS 47
Definition at line 158 of file unistd.h.
_SC_THREAD_STACK_MIN
#define _SC_THREAD_STACK_MIN 25
Definition at line 136 of file unistd.h.
_SC_THREAD_THREADS_MAX
#define _SC_THREAD_THREADS_MAX 26
Definition at line 137 of file unistd.h.
_SC_THREADS
#define _SC_THREADS 40
Definition at line 151 of file unistd.h.
_SC_TIMER_MAX
#define _SC_TIMER_MAX 49
Definition at line 160 of file unistd.h.
_SC_TIMERS
#define _SC_TIMERS 48
Definition at line 159 of file unistd.h.
_SC_TTY_NAME_MAX
#define _SC_TTY_NAME_MAX 19
Definition at line 129 of file unistd.h.
_SC_TZNAME_MAX
#define _SC_TZNAME_MAX 27
Definition at line 138 of file unistd.h.
_SC_VERSION
#define _SC_VERSION 11
Definition at line 121 of file unistd.h.
_SC_XOPEN_CRYPT
#define _SC_XOPEN_CRYPT 16
Definition at line 126 of file unistd.h.
_XOPEN_VERSION
#define _XOPEN_VERSION 700
Definition at line 25 of file unistd.h.
F_LOCK
#define F_LOCK 1
Definition at line 88 of file unistd.h.
F_TEST
#define F_TEST 2
Definition at line 89 of file unistd.h.
F_TLOCK
#define F_TLOCK 3
Definition at line 90 of file unistd.h.
F_ULOCK
#define F_ULOCK 4
Definition at line 91 of file unistd.h.
L_ctermid
#define L_ctermid 20
Definition at line 199 of file unistd.h.
STDERR_FILENO
#define STDERR_FILENO 2
Definition at line 193 of file unistd.h.
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 194 of file unistd.h.
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 195 of file unistd.h.
Typedef Documentation
useconds_t
typedef __mlibc_uint64 useconds_t
Definition at line 300 of file unistd.h.
Function Documentation
__attribute__()
__attribute__ ((noreturn))
References fmt, NULL, params, savesigs, SIG_SETMASK, sigprocmask(), sigset, and vwarn().
access()
int access (const char * path, int mode)
Definition at line 1079 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_access, -1);
     if(int e = mlibc::sys_access(path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_access().
Referenced by main(), and run_test().
alarm()
unsigned int alarm (unsigned int seconds)
Definition at line 19 of file unistd-stubs.cpp.
{
     struct itimerval it = {}, old = {};
     it.it_value.tv_sec = seconds;
     setitimer(ITIMER_REAL, &it, &old);
     return old.it_value.tv_sec + !! old.it_value.tv_usec;
 }
References itimerval::it_value, ITIMER_REAL, setitimer(), and timeval::tv_sec.
Referenced by main().
chdir()
int chdir (const char * path)
Definition at line 26 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_chdir, -1);
     if(int e = mlibc::sys_chdir(path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_chdir().
Referenced by child(), and prepare().
chown()
int chown (const char * path, uid_t uid, gid_t gid)
Definition at line 44 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(AT_FDCWD, path, uid, gid, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchownat().
chroot()
int chroot (const char * ptr)
Definition at line 1112 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_chroot, -1);
     if(int e = mlibc::sys_chroot(ptr); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_chroot().
close()
int close (int fd)
Definition at line 904 of file unistd-stubs.cpp.
                   {
     return mlibc::sys_close(fd);
 }
References fd, and mlibc::sys_close().
Referenced by _vsyslog(), child(), closedir(), closelog(), endutent(), getpass(), getspnam_r(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), main(), posix_spawn(), run_test(), mlibc::sys_if_indextoname(), mlibc::sys_if_nametoindex(), mlibc::sys_pselect(), and we_askshell().
confstr()
ssize_t confstr (int name, char * buf, size_t len)
Definition at line 53 of file unistd-stubs.cpp.
{
     const char *str = "";
     if (name == _CS_PATH) {
         str = "/bin:/usr/bin";
     } else if(name == _CS_GNU_LIBPTHREAD_VERSION) {
         // We are not glibc, so we can return 0 here.
         return 0;
     } else if(name == _CS_GNU_LIBC_VERSION) {
         // We are not glibc, so we can return 0 here.
         return 0;
     } else {
         mlibc::infoLogger() << "\e[31mmlibc: confstr() request " << name << " is unimplemented\e[39m"
                 << frg::endlog;
         __ensure(!"Not implemented");
     }
     return snprintf(buf, len, "%s", str) + 1;
 }
References __ensure, _CS_GNU_LIBC_VERSION, _CS_GNU_LIBPTHREAD_VERSION, _CS_PATH, buf, mlibc::infoLogger, name, and snprintf().
ctermid()
char* ctermid (char * s)
Definition at line 1126 of file unistd-stubs.cpp.
{
     return s ? strcpy(s, "/dev/tty") : const_cast<char *>("/dev/tty");
 }
References strcpy.
daemon()
int daemon (int , int)
Definition at line 1121 of file unistd-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
dup()
int dup (int fd)
Definition at line 930 of file unistd-stubs.cpp.
                 {
     int newfd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_dup, -1);
     if(int e = mlibc::sys_dup(fd, 0, &newfd); e) {
         errno = e;
         return -1;
     }
     return newfd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_dup().
Referenced by child(), and tre_make_trans().
dup2()
int dup2 (int src_fd, int dest_fd)
Definition at line 940 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_dup2, -1);
     if(int e = mlibc::sys_dup2(fd, 0, newfd); e) {
         errno = e;
         return -1;
     }
     return newfd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_dup2().
Referenced by child(), and we_askshell().
endusershell()
void endusershell (void)
Definition at line 1098 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
execl()
int execl (const char * path, const char * arg0, ...)
Definition at line 76 of file unistd-stubs.cpp.
{
     // TODO: It's a stupid idea to limit the number of arguments here.
     char *argv[16];
     argv[0] = const_cast<char *>(arg0);
     va_list args;
     int n = 1;
     va_start(args, arg0);
     while(true) {
         __ensure(n < 15);
         auto argn = va_arg(args, const char *);
         argv[n++] = const_cast<char *>(argn);
         if(!argn)
             break;
     }
     va_end(args);
     argv[n] = nullptr;
     return execve(path, argv, environ);
 }
References __ensure, arg0, args, environ, execve(), n, va_arg, va_end(), and va_start().
Referenced by we_askshell().
execle()
int execle (const char * path, const char * arg0, ...)
Definition at line 98 of file unistd-stubs.cpp.
{
     int argc;
     va_list ap;
     va_start(ap, arg0);
     for(argc = 1; va_arg(ap, const char *); argc++);
     va_end(ap);
     int i;
     char *argv[argc + 1];
     char **envp;
     va_start(ap, arg0);
     argv[0] = (char *)argv;
     for(i = 1; i <= argc; i++)
         argv[i] = va_arg(ap, char *);
     envp = va_arg(ap, char **);
     va_end(ap);
     return execve(path, argv, envp);
 }
References arg0, execve(), i, va_arg, va_end(), and va_start().
execlp()
int execlp (const char * file, const char * argv0, ...)
Definition at line 118 of file unistd-stubs.cpp.
{
     int argc;
     va_list ap;
     va_start(ap, argv0);
     for(argc = 1; va_arg(ap, const char *); argc++);
     va_end(ap);
     {
         int i;
         char *argv[argc + 1];
         va_start(ap, argv0);
         argv[0] = (char *)argv0;
         for(i = 1; i < argc; i++)
             argv[i] = va_arg(ap, char *);
         argv[i] = NULL;
         va_end(ap);
         return execvp(file, argv);
     }
 }
References execvp(), i, NULL, va_arg, va_end(), and va_start().
execv()
int execv (const char * path, char * const argv[])
Definition at line 137 of file unistd-stubs.cpp.
{
     return execve(path, argv, environ);
 }
execve()
int execve (const char * path, char *const argv[], char *const envp[])
Definition at line 1014 of file unistd-stubs.cpp.
{
     char *null_list[] = {
         nullptr
     };
     if(!argv)
         argv = null_list;
     if(!envp)
         envp = null_list;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_execve, -1);
     int e = mlibc::sys_execve(path, argv, envp);
     __ensure(e && "sys_execve() is expected to fail if it returns");
     errno = e;
     return -1;
 }
Referenced by execl(), execle(), and execv().
execvp()
int execvp (const char * file, char * const argv[])
Definition at line 141 of file unistd-stubs.cpp.
{
     return execvpe(file, argv, environ);
 }
Referenced by execlp().
execvpe()
int execvpe (const char * path, char *const argv[], char *const envp[])
Definition at line 145 of file unistd-stubs.cpp.
{
     char *null_list[] = {
         nullptr
     };
     if(!argv)
         argv = null_list;
     if(!envp)
         envp = null_list;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_execve, -1);
     if(strchr(file, '/')) {
         int e = mlibc::sys_execve(file, argv, envp);
         __ensure(e && "sys_execve() is supposed to never return with success");
         errno = e;
         return -1;
     }
     frg::string_view dirs;
     if(const char *pv = getenv("PATH"); pv) {
         dirs = pv;
     }else{
         dirs = "/bin:/usr/bin";
     }
     size_t p = 0;
     int res = ENOENT;
     while(p < dirs.size()) {
         size_t s; // Offset of next colon or end of string.
         if(size_t cs = dirs.find_first(':', p); cs != size_t(-1)) {
             s = cs;
         }else{
             s = dirs.size();
         }
         frg::string<MemoryAllocator> path{getAllocator()};
         path += dirs.sub_string(p, s - p);
         path += "/";
         path += file;
         mlibc::infoLogger() << "mlibc: execvpe() tries '" << path.data() << "'" << frg::endlog;
         int e = mlibc::sys_execve(path.data(), argv, envp);
         __ensure(e && "sys_execve() is supposed to never return with success");
         switch(e) {
         case ENOENT:
         case ENOTDIR:
             break;
         case EACCES:
             res = EACCES;
             break;
         default:
             errno = e;
             return -1;
         }
         p = s + 1;
     }
     errno = res;
     return -1;
 }
References __ensure, EACCES, ENOENT, ENOTDIR, errno, getAllocator(), getenv(), mlibc::infoLogger, MLIBC_CHECK_OR_ENOSYS, p, strchr(), and mlibc::sys_execve().
Referenced by child(), execvp(), and posix_spawnp().
faccessat()
int faccessat (int dirfd, const char * pathname, int mode, int flags)
Definition at line 208 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_faccessat, -1);
     if(int e = mlibc::sys_faccessat(dirfd, pathname, mode, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_faccessat().
fchdir()
int fchdir (int fd)
Definition at line 35 of file unistd-stubs.cpp.
                    {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchdir, -1);
     if(int e = mlibc::sys_fchdir(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchdir().
Referenced by child().
fchown()
int fchown (int fd, uid_t uid, gid_t gid)
Definition at line 217 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(fd, "", uid, gid, AT_EMPTY_PATH); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_EMPTY_PATH, errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchownat().
fchownat()
int fchownat (int fd, const char * path, uid_t uid, gid_t gid, int flags)
Definition at line 226 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(fd, path, uid, gid, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchownat().
fdatasync()
int fdatasync (int fd)
Definition at line 235 of file unistd-stubs.cpp.
                       {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fdatasync, -1);
     if(int e = mlibc::sys_fdatasync(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fdatasync().
fexecve()
int fexecve (int , char * const [], char * const [])
Definition at line 244 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fork()
pid_t fork (void)
Definition at line 949 of file unistd-stubs.cpp.
                  {
     auto self = mlibc::get_current_tcb();
     pid_t child;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fork, -1);
     auto hand = self->atforkEnd;
     while (hand) {
         if (hand->prepare)
             hand->prepare();
         hand = hand->prev;
     }
     if(int e = mlibc::sys_fork(&child); e) {
         errno = e;
         return -1;
     }
     hand = self->atforkBegin;
     while (hand) {
         if (!child) {
             if (hand->child)
                 hand->child();
         } else {
             if (hand->parent)
                 hand->parent();
         }
         hand = hand->next;
     }
     return child;
 }
fpathconf()
long fpathconf (int , int)
Definition at line 249 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fsync()
int fsync (int fd)
Definition at line 254 of file unistd-stubs.cpp.
                   {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fsync, -1);
     if(auto e = mlibc::sys_fsync(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fsync().
ftruncate()
int ftruncate (int fd, off_t size)
Definition at line 263 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ftruncate, -1);
     if(int e = mlibc::sys_ftruncate(fd, size); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_ftruncate().
get_current_dir_name()
char* get_current_dir_name (void)
Definition at line 841 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getcwd()
char* getcwd (char * buffer, size_t size)
Definition at line 272 of file unistd-stubs.cpp.
{
     if (buffer) {
         if (size == 0) {
             errno = EINVAL;
             return NULL;
         }
     } else if (!buffer) {
         if (size == 0)
             size = PATH_MAX;
         buffer = (char *)malloc(size);
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getcwd, nullptr);
     if(int e = mlibc::sys_getcwd(buffer, size); e) {
         errno = e;
         return NULL;
     }
     return buffer;
 }
References EINVAL, errno, malloc(), MLIBC_CHECK_OR_ENOSYS, NULL, PATH_MAX, size, and mlibc::sys_getcwd().
Referenced by main().
getdomainname()
int getdomainname (char * name, size_t len)
Definition at line 1148 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getegid()
gid_t getegid (void)
Definition at line 1039 of file unistd-stubs.cpp.
                     {
     if(!mlibc::sys_getegid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getegid()");
     }
     return mlibc::sys_getegid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_getegid().
getentropy()
int getentropy (void * buffer, size_t length)
Definition at line 855 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getentropy, -1);
     if(length > 256) {
         errno = EIO;
         return -1;
     }
     if(int e = mlibc::sys_getentropy(buffer, length); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References EIO, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getentropy().
geteuid()
uid_t geteuid (void)
Definition at line 1055 of file unistd-stubs.cpp.
                     {
     if(!mlibc::sys_geteuid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_geteuid()");
     }
     return mlibc::sys_geteuid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_geteuid().
getgid()
gid_t getgid (void)
Definition at line 1031 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_getgid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getgid()");
     }
     return mlibc::sys_getgid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_getgid().
Referenced by child().
getgroups()
int getgroups (int size, gid_t list[])
Definition at line 294 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getgroups, -1);
     int ret;
     if(int e = mlibc::sys_getgroups(size, list, &ret); e) {
         errno = e;
         return -1;
     }
     return ret;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, ret, size, and mlibc::sys_getgroups().
gethostid()
long gethostid (void)
Definition at line 304 of file unistd-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
gethostname()
int gethostname (char * buffer, size_t max_length)
Definition at line 309 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_gethostname, -1);
     if(auto e = mlibc::sys_gethostname(buffer, bufsize); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_gethostname().
getlogin()
char* getlogin (void)
Definition at line 328 of file unistd-stubs.cpp.
                      {
     return getenv("LOGNAME");
 }
References getenv().
getlogin_r()
int getlogin_r (char * , size_t)
Definition at line 332 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getopt()
int getopt (int argc, char * const argv[], const char * optstring)
Definition at line 341 of file unistd-stubs.cpp.
{
     char c;
     char *place;
     optarg = NULL;
     if (!scan || *scan == '\0') {
         if (optind == 0)
             optind++;
         if (optind >= argc || argv[optind][0] != '-' || argv[optind][1] == '\0')
             return EOF;
         if (argv[optind][1] == '-' && argv[optind][2] == '\0') {
             optind++;
             return EOF;
         }
         scan = argv[optind]+1;
         optind++;
     }
     c = *scan++;
     place = strchr(optstring, c);
     if (!place || c == ':') {
         fprintf(stderr, "%s: unknown option -%c\n", argv[0], c);
         return '?';
     }
     place++;
     if (*place == ':') {
         if (*scan != '\0') {
             optarg = scan;
             scan = NULL;
         } else if( optind < argc ) {
             optarg = argv[optind];
             optind++;
         } else {
             fprintf(stderr, "%s: option requires argument -%c\n", argv[0], c);
             return ':';
         }
     }
     return c;
 }
getpagesize()
int getpagesize (void)
Definition at line 794 of file unistd-stubs.cpp.
                   {
     return mlibc::page_size;
 }
References mlibc::page_size.
getpass()
char* getpass (const char * prompt)
Definition at line 800 of file unistd-stubs.cpp.
{
     int fdin, fdout;
     struct termios s, t;
     ssize_t l;
     static char password[128];
     if((fdin = open("/dev/tty", O_RDWR|O_NOCTTY|O_CLOEXEC)) < 0) {
         fdin = STDIN_FILENO;
         fdout = STDOUT_FILENO;
     } else {
         fdout = fdin;
     }
     tcgetattr(fdin, &t);
     s = t;
     t.c_lflag &= ~(ECHO | ISIG);
     t.c_lflag |= ICANON;
     t.c_iflag &= ~(INLCR | IGNCR);
     t.c_iflag |= ICRNL;
     tcsetattr(fdin, TCSAFLUSH, &t);
     tcdrain(fdin);
     dprintf(fdout, "%s", prompt);
     l = read(fdin, password, sizeof password);
     if(l >= 0) {
         if((l > 0 && password[l - 1] == '\n') || l == sizeof password)
             l--;
         password[l] = 0;
     }
     tcsetattr(fdin, TCSAFLUSH, &s);
     dprintf(fdout, "\n");
     if(fdin != STDIN_FILENO) {
         close(fdin);
     }
     return l < 0 ? 0 : password;
 }
References termios::c_iflag, termios::c_lflag, close(), dprintf(), ECHO, ICANON, ICRNL, IGNCR, INLCR, ISIG, O_CLOEXEC, O_NOCTTY, O_RDWR, open(), read(), STDIN_FILENO, STDOUT_FILENO, tcdrain(), tcgetattr(), TCSAFLUSH, and tcsetattr().
getpgid()
pid_t getpgid (pid_t pid)
Definition at line 387 of file unistd-stubs.cpp.
{
     pid_t pgid;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getpgid, -1);
     if(int e = mlibc::sys_getpgid(pid, &pgid); e) {
         errno = e;
         return -1;
     }
     return pgid;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getpgid().
Referenced by getpgrp().
getpgrp()
pid_t getpgrp (void)
Definition at line 398 of file unistd-stubs.cpp.
                     {
     return getpgid(0);
 }
References getpgid().
getpid()
pid_t getpid (void)
Definition at line 1063 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_getpid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getpid()");
     }
     return mlibc::sys_getpid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_getpid().
Referenced by _vsyslog(), lockf(), main(), pthread_cancel(), pthread_kill(), and anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler().
getppid()
pid_t getppid (void)
Definition at line 1071 of file unistd-stubs.cpp.
                     {
     if(!mlibc::sys_getppid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getppid()");
     }
     return mlibc::sys_getppid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_getppid().
getresgid()
int getresgid (gid_t * rgid, gid_t * egid, gid_t * sgid)
Definition at line 1163 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getresuid()
int getresuid (uid_t * ruid, uid_t * euid, uid_t * suid)
Definition at line 1158 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getsid()
pid_t getsid (pid_t pid)
Definition at line 402 of file unistd-stubs.cpp.
{
     if(!mlibc::sys_getsid) {
         MLIBC_MISSING_SYSDEP();
         return -1;
     }
     pid_t sid;
     if(int e = mlibc::sys_getsid(pid, &sid); e) {
         errno = e;
         return -1;
     }
     return sid;
 }
References errno, MLIBC_MISSING_SYSDEP, and mlibc::sys_getsid().
gettid()
pid_t gettid (void)
Definition at line 847 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_gettid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_gettid()");
     }
     return mlibc::sys_gettid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_gettid().
getuid()
uid_t getuid (void)
Definition at line 1047 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_getuid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getuid()");
     }
     return mlibc::sys_getuid();
 }
References __ensure, MLIBC_MISSING_SYSDEP, and mlibc::sys_getuid().
Referenced by child(), and expand_tilde().
getusershell()
char* getusershell (void)
Definition at line 1088 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
isatty()
int isatty (int fd)
Definition at line 1103 of file unistd-stubs.cpp.
                    {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_isatty, 0);
     if(int e = mlibc::sys_isatty(fd); e) {
         errno = e;
         return 0;
     }
     return 1;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_isatty().
Referenced by I_ConsoleStdout().
lchown()
int lchown (const char * path, uid_t uid, gid_t gid)
Definition at line 415 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(AT_FDCWD, path, uid, gid, AT_SYMLINK_NOFOLLOW); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, AT_SYMLINK_NOFOLLOW, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchownat().
link()
int link (const char * old_path, const char * new_path)
Definition at line 424 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_link, -1);
     if(int e = mlibc::sys_link(old_path, new_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_link().
Referenced by P_SetThingPosition().
linkat()
int linkat (int olddirfd, const char * old_path, int newdirfd, const char * new_path, int flags)
Definition at line 433 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_linkat, -1);
     if(int e = mlibc::sys_linkat(olddirfd, old_path, newdirfd, new_path, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_linkat().
lockf()
int lockf (int fd, int op, off_t size)
Definition at line 443 of file unistd-stubs.cpp.
{
     struct flock l = {
         .l_type = F_WRLCK,
         .l_whence = SEEK_CUR,
         .l_start = 0,
         .l_len = size,
         .l_pid = 0,
     };
     switch(op) {
         case F_TEST:
             l.l_type = F_RDLCK;
             if(fcntl(fd, F_GETLK, &l) < 0)
                 return -1;
             if(l.l_type == F_UNLCK || l.l_pid == getpid())
                 return 0;
             errno = EACCES;
             return -1;
         case F_ULOCK:
             l.l_type = F_UNLCK;
             [[fallthrough]];
         case F_TLOCK:
             return fcntl(fd, F_SETLK, &l);
         case F_LOCK:
             return fcntl(fd, F_SETLKW, &l);
     }
     errno = EINVAL;
     return -1;
 }
References EACCES, EINVAL, errno, F_GETLK, F_LOCK, F_RDLCK, F_SETLK, F_SETLKW, F_TEST, F_TLOCK, F_ULOCK, F_UNLCK, F_WRLCK, fcntl(), fd, getpid(), flock::l_pid, flock::l_type, SEEK_CUR, and size.
lseek()
off_t lseek (int fd, off_t offset, int whence)
Definition at line 886 of file unistd-stubs.cpp.
{
     off_t new_offset;
     if(int e = mlibc::sys_seek(fd, offset, whence, &new_offset); e) {
         errno = e;
         return (off_t)-1;
     }
     return new_offset;
 }
References errno, fd, mlibc::new_offset, offset, mlibc::sys_seek(), and mlibc::whence.
Referenced by main(), rewinddir(), and setutent().
lseek64()
off64_t lseek64 (int fd, off64_t offset, int whence)
Definition at line 895 of file unistd-stubs.cpp.
{
     off64_t new_offset;
     if(int e = mlibc::sys_seek(fd, offset, whence, &new_offset); e) {
         errno = e;
         return (off64_t)-1;
     }
     return new_offset;
 }
References errno, fd, mlibc::new_offset, offset, mlibc::sys_seek(), and mlibc::whence.
nice()
int nice (int)
Definition at line 474 of file unistd-stubs.cpp.
               {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pathconf()
long pathconf (const char * , int name)
Definition at line 479 of file unistd-stubs.cpp.
{
     switch (name) {
     case _PC_NAME_MAX:
         return NAME_MAX;
     default:
         mlibc::infoLogger() << "missing pathconf() entry " << name << frg::endlog;
         errno = EINVAL;
         return -1;
     }
 }
References _PC_NAME_MAX, EINVAL, errno, mlibc::infoLogger, name, and NAME_MAX.
pause()
int pause (void)
Definition at line 490 of file unistd-stubs.cpp.
                 {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pause, -1);
     if(int e = mlibc::sys_pause(); e) {
         errno = e;
         return -1;
     }
     __ensure(!"There is no successful completion return value for pause");
     __builtin_unreachable();
 }
References __ensure, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_pause().
Referenced by main().
pipe()
int pipe (int [2])
pipe2()
int pipe2 (int * pipefd, int flags)
Definition at line 509 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pipe, -1);
     if(int e = mlibc::sys_pipe(fds, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fds, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_pipe().
Referenced by posix_spawn(), and we_askshell().
pread()
ssize_t pread (int fd, void * buf, size_t n, off_t off)
Definition at line 518 of file unistd-stubs.cpp.
{
     ssize_t num_read;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pread, -1);
     if(int e = mlibc::sys_pread(fd, buf, n, off, &num_read); e) {
         errno = e;
         return -1;
     }
     return num_read;
 }
References buf, errno, fd, MLIBC_CHECK_OR_ENOSYS, n, mlibc::off, and mlibc::sys_pread().
Referenced by read_last_entry().
pwrite()
ssize_t pwrite (int fd, const void * buf, size_t n, off_t off)
Definition at line 529 of file unistd-stubs.cpp.
{
     ssize_t num_written;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pwrite, -1);
     if(int e = mlibc::sys_pwrite(fd, buf, n, off, &num_written); e) {
         errno = e;
         return -1;
     }
     return num_written;
 }
References buf, errno, fd, MLIBC_CHECK_OR_ENOSYS, n, mlibc::off, and mlibc::sys_pwrite().
read()
ssize_t read (int fd, void * buffer, size_t size)
Definition at line 877 of file unistd-stubs.cpp.
{
     ssize_t bytes_read;
     if(int e = mlibc::sys_read(fd, buf, count, &bytes_read); e) {
         errno = e;
         return (ssize_t)-1;
     }
     return bytes_read;
 }
References buf, mlibc::count, errno, fd, and mlibc::sys_read().
Referenced by child_fn(), getpass(), main(), posix_spawn(), and we_read_fully().
readlink()
ssize_t readlink (const char * __restrict, char * __restrict, size_t)
readlinkat()
ssize_t readlinkat (int , const char * __restrict, char * __restrict, size_t)
Definition at line 550 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
rmdir()
int rmdir (const char * path)
Definition at line 555 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_rmdir, -1);
     if(int e = mlibc::sys_rmdir(path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_rmdir().
Referenced by cleanup().
setdomainname()
int setdomainname (const char * name, size_t len)
Definition at line 1153 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setegid()
int setegid (gid_t egid)
Definition at line 564 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setegid, 0);
     if(int e = mlibc::sys_setegid(egid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setegid().
seteuid()
int seteuid (uid_t euid)
Definition at line 573 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_seteuid, 0);
     if(int e = mlibc::sys_seteuid(euid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_seteuid().
setgid()
int setgid (gid_t gid)
Definition at line 582 of file unistd-stubs.cpp.
                       {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setgid, 0);
     if(int e = mlibc::sys_setgid(gid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setgid().
Referenced by child().
sethostname()
int sethostname (const char * buffer, size_t max_length)
Definition at line 318 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sethostname, -1);
     if(auto e = mlibc::sys_sethostname(buffer, bufsize); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_sethostname().
setpgid()
int setpgid (pid_t pid, pid_t pgid)
Definition at line 591 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setpgid, -1);
     if(int e = mlibc::sys_setpgid(pid, pgid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setpgid().
Referenced by setpgrp().
setpgrp()
pid_t setpgrp (void)
Definition at line 600 of file unistd-stubs.cpp.
                     {
     return setpgid(0, 0);
 }
References setpgid().
setregid()
int setregid (gid_t rgid, gid_t egid)
Definition at line 604 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setregid, -1);
     if(int e = mlibc::sys_setregid(rgid, egid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setregid().
setresgid()
int setresgid (gid_t rgid, gid_t egid, gid_t sgid)
Definition at line 1139 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setresgid, -1);
     if(int e = mlibc::sys_setresgid(rgid, egid, sgid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setresgid().
setresuid()
int setresuid (uid_t ruid, uid_t euid, uid_t suid)
Definition at line 1130 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setresuid, -1);
     if(int e = mlibc::sys_setresuid(ruid, euid, suid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setresuid().
setreuid()
int setreuid (uid_t ruid, uid_t euid)
Definition at line 613 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setreuid, -1);
     if(int e = mlibc::sys_setreuid(ruid, euid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setreuid().
setsid()
pid_t setsid (void)
Definition at line 622 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_setsid) {
         MLIBC_MISSING_SYSDEP();
         return -1;
     }
     pid_t sid;
     if(int e = mlibc::sys_setsid(&sid); e) {
         errno = e;
         return -1;
     }
     return sid;
 }
References errno, MLIBC_MISSING_SYSDEP, and mlibc::sys_setsid().
Referenced by child(), and login_tty().
setuid()
int setuid (uid_t uid)
Definition at line 635 of file unistd-stubs.cpp.
                       {
     if(!mlibc::sys_setuid) {
         MLIBC_MISSING_SYSDEP();
         mlibc::infoLogger() << "mlibc: missing sysdep sys_setuid(). Returning 0" << frg::endlog;
         return 0;
     }
     if(int e = mlibc::sys_setuid(uid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::infoLogger, MLIBC_MISSING_SYSDEP, and mlibc::sys_setuid().
Referenced by child().
setusershell()
void setusershell (void)
Definition at line 1093 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sleep()
unsigned int sleep (unsigned int secs)
Definition at line 908 of file unistd-stubs.cpp.
{
     time_t seconds = secs;
     long nanos = 0;
     if(!mlibc::sys_sleep) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_sleep()");
     }
     mlibc::sys_sleep(&seconds, &nanos);
     return seconds;
 }
References __ensure, MLIBC_MISSING_SYSDEP, mlibc::nanos, mlibc::secs, and mlibc::sys_sleep().
Referenced by main(), worker1(), worker2(), and worker4().
swab()
void swab (const void * __restrict, void * __restrict, ssize_t)
Definition at line 648 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
symlink()
int symlink (const char * target_path, const char * link_path)
Definition at line 653 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_symlink, -1);
     if(int e = mlibc::sys_symlink(target_path, link_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_symlink().
Referenced by main(), and prepare().
symlinkat()
int symlinkat (const char * target_path, int dirfd, const char * link_path)
Definition at line 662 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_symlinkat, -1);
     if(int e = mlibc::sys_symlinkat(target_path, dirfd, link_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_symlinkat().
sync()
void sync (void)
Definition at line 671 of file unistd-stubs.cpp.
                 {
     if(!mlibc::sys_sync) {
         MLIBC_MISSING_SYSDEP();
     } else {
         mlibc::sys_sync();
     }
 }
References MLIBC_MISSING_SYSDEP, and mlibc::sys_sync().
sysconf()
unsigned long sysconf (int number)
Definition at line 679 of file unistd-stubs.cpp.
{
     switch(number) {
         case _SC_ARG_MAX:
             // On linux, it is defined to 2097152 in most cases, so define it to be 2097152
             return 2097152;
         case _SC_PAGE_SIZE:
             return mlibc::page_size;
         case _SC_OPEN_MAX:
             struct rlimit ru;
             if (getrlimit(RLIMIT_NOFILE, &ru) < 0) {
                 mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_OPEN_MAX) returns arbitrary value 256\e[39m" << frg::endlog;
                 return 256;
             } else {
                 return (ru.rlim_cur == RLIM_INFINITY) ? -1 : ru.rlim_cur;
             }
         case _SC_PHYS_PAGES:
             // TODO: actually return a proper value for _SC_PHYS_PAGES
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_PHYS_PAGES) returns arbitrary value 1024\e[39m" << frg::endlog;
             return 1024;
         case _SC_NPROCESSORS_ONLN:
             // TODO: actually return a proper value for _SC_NPROCESSORS_ONLN
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_NPROCESSORS_ONLN) unconditionally returns 1\e[39m" << frg::endlog;
             return 1;
         case _SC_GETPW_R_SIZE_MAX:
             return 1024;
         case _SC_GETGR_R_SIZE_MAX:
             return 1024;
         case _SC_CHILD_MAX:
             // On linux, it is defined to 25 in most cases, so define it to be 25
             return 25;
         case _SC_JOB_CONTROL:
             // If 1, job control is supported
             return 1;
         case _SC_CLK_TCK:
             // TODO: This should be obsolete?
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_CLK_TCK) is obsolete and returns arbitrary value 1000000\e[39m" << frg::endlog;
             return 1000000;
         case _SC_NGROUPS_MAX:
             // On linux, it is defined to 65536 in most cases, so define it to be 65536
             return 65536;
         case _SC_RE_DUP_MAX:
             return RE_DUP_MAX;
         case _SC_LINE_MAX:
             // Linux defines it as 2048.
             return 2048;
         case _SC_XOPEN_CRYPT:
 #if __MLIBC_CRYPT_OPTION
             return _XOPEN_CRYPT;
 #else
             return -1;
 #endif /* __MLIBC_CRYPT_OPTION */
         case _SC_NPROCESSORS_CONF:
             // TODO: actually return a proper value for _SC_NPROCESSORS_CONF
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_NPROCESSORS_CONF) unconditionally returns 1\e[39m" << frg::endlog;
             return 1;
         default:
             mlibc::panicLogger() << "\e[31mmlibc: sysconf() call is not implemented, number: " << number << "\e[39m" << frg::endlog;
             __builtin_unreachable();
     }
 }
References _SC_ARG_MAX, _SC_CHILD_MAX, _SC_CLK_TCK, _SC_GETGR_R_SIZE_MAX, _SC_GETPW_R_SIZE_MAX, _SC_JOB_CONTROL, _SC_LINE_MAX, _SC_NGROUPS_MAX, _SC_NPROCESSORS_CONF, _SC_NPROCESSORS_ONLN, _SC_OPEN_MAX, _SC_PAGE_SIZE, _SC_PHYS_PAGES, _SC_RE_DUP_MAX, _SC_XOPEN_CRYPT, getrlimit(), mlibc::infoLogger, mlibc::page_size, mlibc::panicLogger, RE_DUP_MAX, RLIM_INFINITY, RLIMIT_NOFILE, and mlibc::ru.
Referenced by getdtablesize(), and main().
tcgetpgrp()
pid_t tcgetpgrp (int fd)
Definition at line 740 of file unistd-stubs.cpp.
{
     int pgrp;
     if(ioctl(fd, TIOCGPGRP, &pgrp) < 0) {
         return -1;
     }
     return pgrp;
 }
References fd, ioctl(), and TIOCGPGRP.
tcsetpgrp()
int tcsetpgrp (int fd, pid_t pgrp)
Definition at line 748 of file unistd-stubs.cpp.
{
     return ioctl(fd, TIOCSPGRP, &pgrp);
 }
References fd, ioctl(), and TIOCSPGRP.
truncate()
int truncate (const char * , off_t)
Definition at line 752 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
ttyname()
char* ttyname (int fd)
Definition at line 757 of file unistd-stubs.cpp.
                       {
     const size_t size = 128;
     static thread_local char buf[size];
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ttyname, nullptr);
     if(int e = mlibc::sys_ttyname(fd, buf, size); e) {
         errno = e;
         return nullptr;
     }
     return buf;
 }
References buf, errno, fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_ttyname().
ttyname_r()
int ttyname_r (int fd, char * buf, size_t size)
Definition at line 768 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ttyname, -1);
     if(int e = mlibc::sys_ttyname(fd, buf, size); e) {
         return e;
     }
     return 0;
 }
References buf, fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_ttyname().
unlink()
int unlink (const char * path)
Definition at line 776 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_unlinkat, -1);
     if(int e = mlibc::sys_unlinkat(AT_FDCWD, path, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_unlinkat().
Referenced by cleanup(), main(), remove_tmp(), and shm_unlink().
unlinkat()
int unlinkat (int fd, const char * path, int flags)
Definition at line 785 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_unlinkat, -1);
     if(int e = mlibc::sys_unlinkat(fd, path, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_unlinkat().
usleep()
int usleep (useconds_t usecs)
Definition at line 920 of file unistd-stubs.cpp.
{
     time_t seconds = 0;
     long nanos = usecs * 1000;
     if(!mlibc::sys_sleep) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_sleep()");
     }
     return mlibc::sys_sleep(&seconds, &nanos);
 }
References __ensure, MLIBC_MISSING_SYSDEP, mlibc::nanos, and mlibc::sys_sleep().
Referenced by main(), and test_broadcast_wakes_all().
vfork()
pid_t vfork (void)
Definition at line 983 of file unistd-stubs.cpp.
                   {
     pid_t child;
     /*
      * Fork handlers established using pthread_atfork(3) are not
      * called when a multithreaded program employing the NPTL
      * threading library calls vfork().  Fork handlers are called
      * in this case in a program using the LinuxThreads threading
      * library.  (See pthreads(7) for a description of Linux
      * threading libraries.)
      *  - vfork(2), release 5.13 of the Linux man-pages project
      *
      *  as a result, we call sys_fork instead of running atforks
      */
     /* deferring to fork as implementing vfork correctly requires assembly
      * to handle not mucking up the stack
      */
     if(!mlibc::sys_fork) {
         MLIBC_MISSING_SYSDEP();
         errno = ENOSYS;
         return -1;
     }
     if(int e = mlibc::sys_fork(&child); e) {
         errno = e;
         return -1;
     }
     return child;
 }
References child, ENOSYS, errno, MLIBC_MISSING_SYSDEP, and mlibc::sys_fork().
Referenced by main().
write()
ssize_t write (int fd, const void * buffer, size_t size)
Definition at line 868 of file unistd-stubs.cpp.
{
     ssize_t bytes_written;
     if(int e = mlibc::sys_write(fd, buf, count, &bytes_written); e) {
         errno = e;
         return (ssize_t)-1;
     }
     return bytes_written;
 }
References buf, mlibc::count, errno, fd, and mlibc::sys_write().
Referenced by child(), main(), parent_fn(), and writev().
Variable Documentation
environ
char** environ extern
Definition at line 41 of file lib.c.
optarg
char* optarg extern
Definition at line 11 of file getopt-stubs.cpp.
Referenced by getopt(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), test1(), test3(), test4(), and test6().
opterr
int opterr extern
Definition at line 13 of file getopt-stubs.cpp.
Referenced by anonymous_namespace{getopt-stubs.cpp}::getopt_common().
optind
int optind extern
Definition at line 12 of file getopt-stubs.cpp.
Referenced by getopt(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), test1(), test2(), test3(), test4(), test5(), test6(), test7(), and test8().
optopt
int optopt extern
Definition at line 14 of file getopt-stubs.cpp.
Referenced by anonymous_namespace{getopt-stubs.cpp}::getopt_common(), test2(), and test8().