Fennix: Drivers/include/base.h File Reference
base.h File Reference
#include <driver.h>
Macros
#define PAGE_SIZE 0x1000
#define ECS CriticalState __ECS = EnterCriticalSection()
Enter a critical section.
#define LCS LeaveCriticalSection(__ECS)
Leave a critical section.
#define DriverInfo(Name, Description, Author, Version, License)
#define DebugLog(m, ...)
#define memcpy(dest, src, len) MemoryCopy(dest, src, len)
#define memset(dest, val, len) MemorySet(dest, val, len)
#define memmove(dest, src, len) MemoryMove(dest, src, len)
#define strlen(str) StringLength(str)
Typedefs
typedef int CriticalState
Functions
void * AllocateMemory (size_t Pages)
Allocate an amount of memory pages.
void FreeMemory (void *Pointer, size_t Pages)
Free an amount of memory pages.
void AppendMapFlag (void *Address, PageMapFlags Flag)
Append a flag to a page.
void RemoveMapFlag (void *Address, PageMapFlags Flag)
Remove a flag from a page.
void MapPages (void *PhysicalAddress, void *VirtualAddress, size_t Pages, uint32_t Flags)
Map pages.
void UnmapPages (void *VirtualAddress, size_t Pages)
Unmap pages.
void KPrint (const char *Format,...)
Print to the screen.
void Log (const char *Format,...)
Print to the kernel logger.
int RegisterInterruptHandler (uint8_t IRQ, void *Handler)
Register an interrupt handler.
int OverrideInterruptHandler (uint8_t IRQ, void *Handler)
Override an interrupt handler.
int UnregisterInterruptHandler (uint8_t IRQ, void *Handler)
Unregister an interrupt handler.
int UnregisterAllInterruptHandlers (void *Handler)
Unregister all interrupt handlers for a given handler.
void * MemoryCopy (void *Destination, const void *Source, size_t Length)
Copy memory.
void * MemorySet (void *Destination, int Value, size_t Length)
Set memory.
void * MemoryMove (void *Destination, const void *Source, size_t Length)
Move memory.
size_t StringLength (const char String[])
String length.
char * strstr (const char *Haystack, const char *Needle)
pid_t CreateKernelProcess (const char *Name)
Create a kernel process.
pid_t CreateKernelThread (pid_t pId, const char *Name, void *EntryPoint, void *Argument)
Create a kernel thread.
int KillProcess (pid_t pId, int ExitCode)
Kill a process.
int KillThread (pid_t tId, int ExitCode)
Kill a thread.
void Yield ()
Yield the current thread.
void Sleep (uint64_t Milliseconds)
Sleep for a given amount of milliseconds.
CriticalState EnterCriticalSection ()
Enter a critical section.
void LeaveCriticalSection (CriticalState PreviousState)
Leave a critical section.
Macro Definition Documentation
DebugLog
#define DebugLog (m, ...)
Definition at line 249 of file base.h.
DriverInfo
#define DriverInfo (Name, Description, Author, Version, License)
Value:
    void __IdentifyDriver(                                              \
        dev_t ID,                                                       \
        int (*GetDriverInfo)(dev_t, const char *, const char *,         \
                             const char *, const char *, const char *)) \
    {                                                                   \
        GetDriverInfo(ID, Name, Description, Author, Version, License); \
    }
Definition at line 237 of file base.h.
ECS
#define ECS CriticalState __ECS = EnterCriticalSection()
Enter a critical section.
Returns
The previous interrupt state
This function will disable interrupts and return the previous interrupt state.
Definition at line 232 of file base.h.
LCS
#define LCS LeaveCriticalSection(__ECS)
Leave a critical section.
Parameters
PreviousState The previous interrupt state
This function will restore the previous interrupt state.
Definition at line 235 of file base.h.
memcpy
#define memcpy (dest, src, len) MemoryCopy(dest, src, len)
Definition at line 271 of file base.h.
memmove
#define memmove (dest, src, len) MemoryMove(dest, src, len)
Definition at line 273 of file base.h.
memset
#define memset (dest, val, len) MemorySet(dest, val, len)
Definition at line 272 of file base.h.
PAGE_SIZE
#define PAGE_SIZE 0x1000
Definition at line 23 of file base.h.
strlen
#define strlen (str) StringLength(str)
Definition at line 275 of file base.h.
Typedef Documentation
CriticalState
typedef int CriticalState
Definition at line 25 of file base.h.
Function Documentation
AllocateMemory()
void* AllocateMemory (size_t Pages)
Allocate an amount of memory pages.
Parameters
Pages The amount of pages to allocate
Returns
A pointer to the allocated memory, NULL if failed
Definition at line 64 of file base.c.
 {
     if (Pages == 0)
         return NULL;
     return API->RequestPages(API->MajorID,
                              Pages);
 }
References API, __driverAPI::MajorID, NULL, and __driverAPI::RequestPages.
Referenced by AC97Device::AC97Device(), Port::Configure(), DisplayScaleThread(), E1000Device::InitializeRX(), E1000Device::InitializeTX(), MessageReceive(), Port::Port(), and RTL8139Device::RTL8139Device().
AppendMapFlag()
void AppendMapFlag (void * Address, PageMapFlags Flag)
Append a flag to a page.
Parameters
Address The address of the page
Flag The flag to append
Definition at line 83 of file base.c.
 {
     API->AppendMapFlag(API->MajorID,
                        Address,
                        Flag);
 }
References Address, API, __driverAPI::AppendMapFlag, and __driverAPI::MajorID.
CreateKernelProcess()
pid_t CreateKernelProcess (const char * Name)
Create a kernel process.
Parameters
Name The name of the process
Returns
The PID of the process, this function never fails
Definition at line 23 of file task.c.
 {
     return API->CreateKernelProcess(API->MajorID,
                                     Name);
 }
References API, __driverAPI::CreateKernelProcess, __driverAPI::MajorID, and CPU::Name().
CreateKernelThread()
pid_t CreateKernelThread (pid_t pId, const char * Name, void * EntryPoint, void * Argument)
Create a kernel thread.
Parameters
pId The PID of the process to create the thread in
Name The name of the thread
EntryPoint The entry point of the thread
Argument The argument to pass to the thread (rdi)
Returns
The TID of the thread, this function never fails
Definition at line 29 of file task.c.
 {
     return API->CreateKernelThread(API->MajorID,
                                    pId,
                                    Name,
                                    EntryPoint,
                                    Argument);
 }
References API, __driverAPI::CreateKernelThread, __driverAPI::MajorID, and CPU::Name().
EnterCriticalSection()
CriticalState EnterCriticalSection ()
Enter a critical section.
Returns
The previous interrupt state
This function will disable interrupts and return the previous interrupt state.
Definition at line 137 of file base.c.
 {
     CriticalState cs;
 #if defined(__i386__) || defined(__x86_64__)
     uintptr_t Flags;
 #if defined(__x86_64__)
     asmv("pushfq");
     asmv("popq %0"
          : "=r"(Flags));
 #else
     asmv("pushfl");
     asmv("popl %0"
          : "=r"(Flags));
 #endif
     cs = Flags & (1 << 9);
     asmv("cli");
 #elif defined(__arm__) || defined(__aarch64__)
     uintptr_t Flags;
     asmv("mrs %0, cpsr"
          : "=r"(Flags));
     cs = Flags & (1 << 7);
     asmv("cpsid i");
 #endif
     return cs;
 }
References asmv(), and Flags.
FreeMemory()
void FreeMemory (void * Pointer, size_t Pages)
Free an amount of memory pages.
Parameters
Pointer The pointer to the memory to free
Pages The amount of pages to free
Note
If the pointer is invalid, the error is ignored and the function returns
Definition at line 73 of file base.c.
 {
     if (Pointer == NULL || Pages == 0)
         return;
     API->FreePages(API->MajorID,
                    Pointer,
                    Pages);
 }
References API, __driverAPI::FreePages, __driverAPI::MajorID, and NULL.
Referenced by DriverFinal(), MessageReceive(), and Port::~Port().
KillProcess()
int KillProcess (pid_t pId, int ExitCode)
Kill a process.
Parameters
pId The PID of the process to kill
ExitCode The exit code of the process
Returns
0 on success, errno on failure
Definition at line 38 of file task.c.
 {
     return API->KillProcess(API->MajorID,
                             pId, ExitCode);
 }
References API, __driverAPI::KillProcess, and __driverAPI::MajorID.
KillThread()
int KillThread (pid_t tId, int ExitCode)
Kill a thread.
Parameters
tId The TID of the thread to kill
ExitCode The exit code of the thread
Returns
0 on success, errno on failure
Definition at line 44 of file task.c.
 {
     return API->KillThread(API->MajorID,
                            tId, ExitCode);
 }
References API, __driverAPI::KillThread, and __driverAPI::MajorID.
KPrint()
void KPrint (const char * Format, ...)
Print to the screen.
Parameters
Format The format string
... The arguments to the format string
Note
The newline character is automatically appended
Definition at line 102 of file kernel.cpp.
 {
     va_list args;
     va_start(args, Format);
     _KPrint(Format, args);
     va_end(args);
 #ifdef DEBUG
     va_start(args, Format);
     vfctprintf(uart_wrapper, nullptr, "PRINT| ", args);
     va_end(args);
     va_start(args, Format);
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
     uart_wrapper('\n', nullptr);
 #endif
 }
References _KPrint(), API, args, __driverAPI::KPrint, __driverAPI::MajorID, uart_wrapper(), va_end, va_start, and vfctprintf().
Referenced by ACPI::__no_sanitize(), BeforeShutdown(), cxx_Initialize(), DriverEntry(), DriverProbe(), ACPI::DSDT::DSDT(), Time::time::FindTimers(), Time::HighPrecisionEventTimer::HighPrecisionEventTimer(), InterruptDescriptorTable::Init(), Interrupts::Initialize(), CPU::InitializeFeatures(), KernelMainThread(), KernelShutdownThread(), KernelVFS(), linux_reboot(), Driver::Manager::LoadAllDrivers(), ACPI::MADT::MADT(), Main(), Driver::Manager::Manager(), ACPI::DSDT::OnInterruptReceived(), ParseConfig(), Memory::Physical::RequestPage(), Memory::Physical::RequestPages(), ACPI::DSDT::Shutdown(), Power::Power::Shutdown(), StartCPU(), StartKernelShell(), NetworkInterfaceManager::NetworkInterface::StartNetworkStack(), Tasking::Task::Task(), and APIC::Timer::Timer().
LeaveCriticalSection()
void LeaveCriticalSection (CriticalState PreviousState)
Leave a critical section.
Parameters
PreviousState The previous interrupt state
This function will restore the previous interrupt state.
Definition at line 169 of file base.c.
 {
 #if defined(__i386__) || defined(__x86_64__)
     if (PreviousState)
         asmv("sti");
 #elif defined(__arm__) || defined(__aarch64__)
     if (PreviousState)
         asmv("cpsie i");
 #endif
 }
References asmv().
Log()
void Log (const char * Format, ...)
Print to the kernel logger.
Parameters
Format The format string
... The arguments to the format string
Definition at line 125 of file base.c.
 {
     va_list Args;
     va_start(Args, Format);
     API->KernelLog(API->MajorID,
                    Format,
                    Args);
     va_end(Args);
 }
References API, __driverAPI::KernelLog, __driverAPI::MajorID, va_end, and va_start.
Referenced by Port::Configure(), cxx_Finalize(), cxx_Initialize(), cxx_Probe(), DetectPS2Keyboard(), DetectPS2Mouse(), DisplayGetSize(), DisplayScaleThread(), DriverEntry(), DriverProbe(), E1000Device::E1000Device(), E1000Device::GetMAC(), HDADevice::HDADevice(), Port::Identify(), InitializeKeyboard(), InitializeMouse(), InterruptHandler(), MessageReceive(), MessageSend(), AC97Device::OnInterruptReceived(), OpenMessageChannel(), PS2KbdInterruptHandler(), Port::ReadWrite(), SendRPCI(), AC97Device::write(), and E1000Device::~E1000Device().
MapPages()
void MapPages (void * PhysicalAddress, void * VirtualAddress, size_t Pages, uint32_t Flags)
Map pages.
Parameters
PhysicalAddress The physical address to map
VirtualAddress The virtual address to map to
Pages The amount of pages to map
Flags The flags to map the pages with
Definition at line 97 of file base.c.
 {
     API->MapPages(API->MajorID,
                   PhysicalAddress,
                   VirtualAddress,
                   Pages,
                   Flags);
 }
References API, Flags, __driverAPI::MajorID, __driverAPI::MapPages, and PhysicalAddress.
MemoryCopy()
void* MemoryCopy (void * Destination, const void * Source, size_t Length)
Copy memory.
Parameters
Destination The destination
Source The source
Length The length of the memory to copy
Returns
The destination
Definition at line 28 of file std.c.
 {
     return API->memcpy(API->MajorID, Destination, Source, Length);
 }
References API, Length, __driverAPI::MajorID, and __driverAPI::memcpy.
Referenced by MessageReceiveLB(), and MessageSendLB().
MemoryMove()
void* MemoryMove (void * Destination, const void * Source, size_t Length)
Move memory.
Parameters
Destination The destination
Source The source
Length The length of the memory to move
Returns
The destination
Definition at line 38 of file std.c.
 {
     return API->memmove(API->MajorID, Destination, Source, Length);
 }
References API, Length, __driverAPI::MajorID, and __driverAPI::memmove.
MemorySet()
void* MemorySet (void * Destination, int Value, size_t Length)
Set memory.
Parameters
Destination The destination
Value The value to set
Length The length of the memory to set
Returns
The destination
Definition at line 33 of file std.c.
 {
     return API->memset(API->MajorID, Destination, Value, Length);
 }
References API, Length, __driverAPI::MajorID, and __driverAPI::memset.
Referenced by Port::Configure(), Port::Identify(), Port::Port(), and Port::ReadWrite().
OverrideInterruptHandler()
int OverrideInterruptHandler (uint8_t IRQ, void * Handler)
Override an interrupt handler.
This function will check all registered handlers (by the drivers) for the given IRQ and remove them. Then it will register the new handler.
Parameters
IRQ The IRQ to override the handler for (IRQ0 != 0x32 but 0)
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 35 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->OverrideInterruptHandler(API->MajorID,
                                          IRQ,
                                          Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::OverrideInterruptHandler.
RegisterInterruptHandler()
int RegisterInterruptHandler (uint8_t IRQ, void * Handler)
Register an interrupt handler.
Parameters
IRQ The IRQ to register the handler for (IRQ0 != 0x32 but 0)
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 25 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->RegisterInterruptHandler(API->MajorID,
                                          IRQ,
                                          Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::RegisterInterruptHandler.
RemoveMapFlag()
void RemoveMapFlag (void * Address, PageMapFlags Flag)
Remove a flag from a page.
Parameters
Address The address of the page
Flag The flag to remove
Definition at line 90 of file base.c.
 {
     API->RemoveMapFlag(API->MajorID,
                        Address,
                        Flag);
 }
References Address, API, __driverAPI::MajorID, and __driverAPI::RemoveMapFlag.
Sleep()
void Sleep (uint64_t Milliseconds)
Sleep for a given amount of milliseconds.
Parameters
Milliseconds The amount of milliseconds to sleep
Definition at line 55 of file task.c.
 {
     API->Sleep(API->MajorID,
                Milliseconds);
 }
References API, __driverAPI::MajorID, Time::Milliseconds, and __driverAPI::Sleep.
StringLength()
size_t StringLength (const char String[])
String length.
Parameters
String The string
Returns
The length of the string
Definition at line 43 of file std.c.
 {
     return API->strlen(API->MajorID, String);
 }
References API, __driverAPI::MajorID, and __driverAPI::strlen.
Referenced by DisplayGetSize(), MessageSend(), MessageSendHB(), and MessageSendLB().
strstr()
char* strstr (const char * Haystack, const char * Needle)
Definition at line 156 of file convert.cpp.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
References API, c, fourbyte_strstr(), h, __driverAPI::MajorID, n, NULL, strchr(), __driverAPI::strstr, threebyte_strstr(), twobyte_strstr(), and twoway_strstr().
UnmapPages()
void UnmapPages (void * VirtualAddress, size_t Pages)
Unmap pages.
Parameters
VirtualAddress The virtual address to unmap
Pages The amount of pages to unmap
Definition at line 106 of file base.c.
 {
     API->UnmapPages(API->MajorID,
                     VirtualAddress,
                     Pages);
 }
References API, __driverAPI::MajorID, and __driverAPI::UnmapPages.
UnregisterAllInterruptHandlers()
int UnregisterAllInterruptHandlers (void * Handler)
Unregister all interrupt handlers for a given handler.
Parameters
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 55 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->UnregisterAllInterruptHandlers(API->MajorID,
                                                Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::UnregisterAllInterruptHandlers.
UnregisterInterruptHandler()
int UnregisterInterruptHandler (uint8_t IRQ, void * Handler)
Unregister an interrupt handler.
Parameters
IRQ The IRQ to unregister the handler for (IRQ0 != 0x32 but 0)
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 45 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->UnregisterInterruptHandler(API->MajorID,
                                            IRQ,
                                            Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::UnregisterInterruptHandler.
Yield()
void Yield ()
Yield the current thread.
This function will yield the current thread to the scheduler.
Definition at line 50 of file task.c.
 {
     API->Yield(API->MajorID);
 }
References API, __driverAPI::MajorID, and __driverAPI::Yield.