Fennix Userspace: Userspace/musl/src/string/wcsncasecmp.c File Reference
wcsncasecmp.c File Reference
#include <wchar.h>
#include <wctype.h>
Functions
int wcsncasecmp (const wchar_t *l, const wchar_t *r, size_t n)
Function Documentation
wcsncasecmp()
int wcsncasecmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 4 of file wcsncasecmp.c.
 {
     if (!n--) return 0;
     for (; *l && *r && n && (*l == *r || towlower(*l) == towlower(*r)); l++, r++, n--);
     return towlower(*l) - towlower(*r);
 }
References l, n, and towlower().
Referenced by wcscasecmp(), and wcsncasecmp_l().