Fennix: Userspace/apps/base/busybox/e2fsprogs/tune2fs.c File Reference
tune2fs.c File Reference
#include "libbb.h"
#include <linux/fs.h>
#include "bb_e2fs_defs.h"
Enumerations
enum { OPT_L = 1 << 0 , OPT_c = 1 << 1 , OPT_i = 1 << 2 , OPT_C = 1 << 3 }
Functions
int tune2fs_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_L
OPT_c
OPT_i
OPT_C
Definition at line 42 of file tune2fs.c.
      {
     OPT_L = 1 << 0, // label
     OPT_c = 1 << 1, // max mount count
     OPT_i = 1 << 2, // check interval
     OPT_C = 1 << 3, // current mount count
 };
Function Documentation
tune2fs_main()
int tune2fs_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 50 of file tune2fs.c.
 {
     unsigned opts;
     const char *label, *str_c, *str_i, *str_C;
     struct ext2_super_block *sb;
     int fd;
     opts = getopt32(argv, "^" "L:c:i:C:" "\0" "=1", &label, &str_c, &str_i, &str_C);
     if (!opts)
         bb_show_usage();
     argv += optind; // argv[0] -- device
     // read superblock
     fd = xopen(argv[0], O_RDWR);
     xlseek(fd, 1024, SEEK_SET);
     sb = xzalloc(1024);
     xread(fd, sb, 1024);
     // mangle superblock
     //STORE_LE(sb->s_wtime, time(NULL)); - why bother?
     if (opts & OPT_C) {
         int n = xatoi_range(str_C, 1, 0xfffe);
         STORE_LE(sb->s_mnt_count, (unsigned)n);
     }
     // set the label
     if (opts & OPT_L)
         safe_strncpy((char *)sb->s_volume_name, label, sizeof(sb->s_volume_name));
     if (opts & OPT_c) {
         int n = xatoi_range(str_c, -1, 0xfffe);
         if (n == 0)
             n = -1;
         STORE_LE(sb->s_max_mnt_count, (unsigned)n);
     }
     if (opts & OPT_i) {
         unsigned n = xatou_range(str_i, 0, (unsigned)0xffffffff / (24*60*60)) * 24*60*60;
         STORE_LE(sb->s_checkinterval, n);
     }
     // write superblock
     xlseek(fd, 1024, SEEK_SET);
     xwrite(fd, sb, 1024);
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(sb);
     }
     xclose(fd);
     return EXIT_SUCCESS;
 }
References argv, bb_show_usage(), EXIT_SUCCESS, fd, free, getopt32(), label, n, O_RDWR, OPT_c, OPT_C, OPT_i, OPT_L, optind, ext2_super_block::s_checkinterval, ext2_super_block::s_max_mnt_count, ext2_super_block::s_mnt_count, ext2_super_block::s_volume_name, safe_strncpy(), SEEK_SET, STORE_LE, xclose(), xlseek(), xopen(), xread(), xwrite(), and xzalloc().