Fennix: CPU Namespace Reference
CPU Namespace Reference
CPU related functions.
Namespaces
aarch64
MemBar
x32
x64
x86
Data Structures
struct SupportedFeat
Enumerations
enum InterruptsType { Check , Enable , Disable }
Enum for CPU::Interrupts() function.
enum x86SIMDType {
SIMD_NONE = (1 << 0) , SIMD_SSE = (1 << 1) , SIMD_SSE2 = (1 << 2) , SIMD_SSE3 = (1 << 3) ,
SIMD_SSSE3 = (1 << 4) , SIMD_SSE41 = (1 << 5) , SIMD_SSE42 = (1 << 6) , SIMD_AVX = (1 << 7) ,
SIMD_AVX2 = (1 << 8) , SIMD_AVX512 = (1 << 9) , SIMD_AVX512F = (1 << 10) , SIMD_AVX512CD = (1 << 11) ,
SIMD_AVX512ER = (1 << 12) , SIMD_AVX512PF = (1 << 13) , SIMD_AVX512VL = (1 << 14) , SIMD_AVX512DQ = (1 << 16) ,
SIMD_AVX512BW = (1 << 15) , SIMD_AVX512IFMA = (1 << 17) , SIMD_AVX512VBMI = (1 << 18) , SIMD_AVX5124VNNIW = (1 << 19) ,
SIMD_AVX5124FMAPS = (1 << 20) , SIMD_AVX512VPOPCNTDQ = (1 << 21) , SIMD_AVX512VNNI = (1 << 22) , SIMD_AVX512VBMI2 = (1 << 23) ,
SIMD_AVX512BITALG = (1 << 24) , SIMD_AVX512VP2INTERSECT = (1 << 25) , SIMD_AVX512GFNI = (1 << 26) , SIMD_AVX512VPCLMULQDQ = (1 << 27) ,
SIMD_AVX512VAES = (1 << 28)
}
Functions
const char * Vendor ()
Get CPU vendor identifier.
const char * Name ()
Get CPU name.
const char * Hypervisor ()
Get CPU hypervisor vendor.
bool Interrupts (InterruptsType Type=Check)
Check if interrupts are enabled.
void * PageTable (void *PT=nullptr)
Get/Set the CPU's page table.
SupportedFeat GetCPUFeat ()
void InitializeFeatures (int Core)
To be used only once.
uint64_t Counter ()
Get CPU counter value.
uint64_t CheckSIMD ()
Check SIMD support. It will return the highest supported SIMD type.
bool CheckSIMD (x86SIMDType Type)
Check SIMD support.
static nsa __always_inline void Pause (bool Loop=false)
Pause the CPU.
nsa __noreturn __used void Stop ()
Stop the CPU (infinite loop)
static nsa __always_inline void Halt (bool Loop=false)
Halt the CPU.
Variables
static bool SSEEnabled = false
Detailed Description
CPU related functions.
Data Structure Documentation
CPU::SupportedFeat
struct CPU::SupportedFeat
Definition at line 237 of file cpu.cpp.
Data Fields
bool PGE
bool SMAP
bool SMEP
bool SSE
bool UMIP
Enumeration Type Documentation
InterruptsType
enum CPU::InterruptsType
Enum for CPU::Interrupts() function.
Enumerator
Check
Check if interrupts are enabled.
Enable
Enable interrupts.
Disable
Disable interrupts.
Definition at line 43 of file cpu.hpp.
     {
         Check,
         Enable,
         Disable
     };
x86SIMDType
enum CPU::x86SIMDType
Enumerator
SIMD_NONE
SIMD_SSE
SIMD_SSE2
SIMD_SSE3
SIMD_SSSE3
SIMD_SSE41
SIMD_SSE42
SIMD_AVX
SIMD_AVX2
SIMD_AVX512
SIMD_AVX512F
SIMD_AVX512CD
SIMD_AVX512ER
SIMD_AVX512PF
SIMD_AVX512VL
SIMD_AVX512DQ
SIMD_AVX512BW
SIMD_AVX512IFMA
SIMD_AVX512VBMI
SIMD_AVX5124VNNIW
SIMD_AVX5124FMAPS
SIMD_AVX512VPOPCNTDQ
SIMD_AVX512VNNI
SIMD_AVX512VBMI2
SIMD_AVX512BITALG
SIMD_AVX512VP2INTERSECT
SIMD_AVX512GFNI
SIMD_AVX512VPCLMULQDQ
SIMD_AVX512VAES
Definition at line 59 of file cpu.hpp.
     {
         SIMD_NONE = (1 << 0),
         SIMD_SSE = (1 << 1),
         SIMD_SSE2 = (1 << 2),
         SIMD_SSE3 = (1 << 3),
         SIMD_SSSE3 = (1 << 4),
         SIMD_SSE41 = (1 << 5),
         SIMD_SSE42 = (1 << 6),
         SIMD_AVX = (1 << 7),
         SIMD_AVX2 = (1 << 8),
         SIMD_AVX512 = (1 << 9),
         SIMD_AVX512F = (1 << 10),
         SIMD_AVX512CD = (1 << 11),
         SIMD_AVX512ER = (1 << 12),
         SIMD_AVX512PF = (1 << 13),
         SIMD_AVX512VL = (1 << 14),
         SIMD_AVX512DQ = (1 << 16),
         SIMD_AVX512BW = (1 << 15),
         SIMD_AVX512IFMA = (1 << 17),
         SIMD_AVX512VBMI = (1 << 18),
         SIMD_AVX5124VNNIW = (1 << 19),
         SIMD_AVX5124FMAPS = (1 << 20),
         SIMD_AVX512VPOPCNTDQ = (1 << 21),
         SIMD_AVX512VNNI = (1 << 22),
         SIMD_AVX512VBMI2 = (1 << 23),
         SIMD_AVX512BITALG = (1 << 24),
         SIMD_AVX512VP2INTERSECT = (1 << 25),
         SIMD_AVX512GFNI = (1 << 26),
         SIMD_AVX512VPCLMULQDQ = (1 << 27),
         SIMD_AVX512VAES = (1 << 28),
     };
Function Documentation
CheckSIMD() [1/2]
uint64_t CPU::CheckSIMD ()
Check SIMD support. It will return the highest supported SIMD type.
Returns
x86SIMDType flags.
Definition at line 408 of file cpu.cpp.
     {
         if (unlikely(!SSEEnabled))
             return SIMD_NONE;
 #warning "TODO: Proper SIMD support"
         return SIMD_NONE;
 #if defined(a86)
         static uint64_t SIMDType = SIMD_NONE;
         if (likely(SIMDType != SIMD_NONE))
             return SIMDType;
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
             CPU::x86::AMD::CPUID0x00000001 cpuid;
             asmv("cpuid"
                  : "=a"(cpuid.EAX.raw), "=b"(cpuid.EBX.raw),
                    "=c"(cpuid.ECX.raw), "=d"(cpuid.EDX.raw)
                  : "a"(0x1));
             if (cpuid.ECX.SSE42)
                 SIMDType |= SIMD_SSE42;
             else if (cpuid.ECX.SSE41)
                 SIMDType |= SIMD_SSE41;
             else if (cpuid.ECX.SSSE3)
                 SIMDType |= SIMD_SSSE3;
             else if (cpuid.ECX.SSE3)
                 SIMDType |= SIMD_SSE3;
             else if (cpuid.EDX.SSE2)
                 SIMDType |= SIMD_SSE2;
             else if (cpuid.EDX.SSE)
                 SIMDType |= SIMD_SSE;
 #ifdef DEBUG
             if (cpuid.ECX.SSE42)
                 debug("SSE4.2 is supported.");
             if (cpuid.ECX.SSE41)
                 debug("SSE4.1 is supported.");
             if (cpuid.ECX.SSSE3)
                 debug("SSSE3 is supported.");
             if (cpuid.ECX.SSE3)
                 debug("SSE3 is supported.");
             if (cpuid.EDX.SSE2)
                 debug("SSE2 is supported.");
             if (cpuid.EDX.SSE)
                 debug("SSE is supported.");
 #endif
             return SIMDType;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
             CPU::x86::Intel::CPUID0x00000001 cpuid;
             asmv("cpuid"
                  : "=a"(cpuid.EAX.raw), "=b"(cpuid.EBX.raw), "=c"(cpuid.ECX.raw), "=d"(cpuid.EDX.raw)
                  : "a"(0x1));
             if (cpuid.ECX.SSE4_2)
                 SIMDType |= SIMD_SSE42;
             else if (cpuid.ECX.SSE4_1)
                 SIMDType |= SIMD_SSE41;
             else if (cpuid.ECX.SSSE3)
                 SIMDType |= SIMD_SSSE3;
             else if (cpuid.ECX.SSE3)
                 SIMDType |= SIMD_SSE3;
             else if (cpuid.EDX.SSE2)
                 SIMDType |= SIMD_SSE2;
             else if (cpuid.EDX.SSE)
                 SIMDType |= SIMD_SSE;
 #ifdef DEBUG
             if (cpuid.ECX.SSE4_2)
                 debug("SSE4.2 is supported.");
             if (cpuid.ECX.SSE4_1)
                 debug("SSE4.1 is supported.");
             if (cpuid.ECX.SSSE3)
                 debug("SSSE3 is supported.");
             if (cpuid.ECX.SSE3)
                 debug("SSE3 is supported.");
             if (cpuid.EDX.SSE2)
                 debug("SSE2 is supported.");
             if (cpuid.EDX.SSE)
                 debug("SSE is supported.");
 #endif
             return SIMDType;
         }
         debug("No SIMD support.");
 #endif // a64 || a32
         return SIMD_NONE;
     }
References asmv(), CPU::x64::cpuid(), debug, likely, SIMD_NONE, SIMD_SSE, SIMD_SSE2, SIMD_SSE3, SIMD_SSE41, SIMD_SSE42, SIMD_SSSE3, SSEEnabled, strcmp, unlikely, Vendor(), x86_CPUID_VENDOR_AMD, and x86_CPUID_VENDOR_INTEL.
Referenced by __memcpy_chk(), __memmove_chk(), __memset_chk(), and strlen().
CheckSIMD() [2/2]
bool CPU::CheckSIMD (x86SIMDType Type)
Check SIMD support.
Parameters
Type SIMD type.
Returns
true if supported.
false if not supported.
Definition at line 502 of file cpu.cpp.
     {
         if (unlikely(!SSEEnabled))
             return false;
 #if defined(a86)
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
             CPU::x86::AMD::CPUID0x00000001 cpuid;
             asmv("cpuid"
                  : "=a"(cpuid.EAX.raw), "=b"(cpuid.EBX.raw), "=c"(cpuid.ECX.raw), "=d"(cpuid.EDX.raw)
                  : "a"(0x1));
             if (Type == SIMD_SSE42)
                 return cpuid.ECX.SSE42;
             else if (Type == SIMD_SSE41)
                 return cpuid.ECX.SSE41;
             else if (Type == SIMD_SSSE3)
                 return cpuid.ECX.SSSE3;
             else if (Type == SIMD_SSE3)
                 return cpuid.ECX.SSE3;
             else if (Type == SIMD_SSE2)
                 return cpuid.EDX.SSE2;
             else if (Type == SIMD_SSE)
                 return cpuid.EDX.SSE;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
             CPU::x86::Intel::CPUID0x00000001 cpuid;
             asmv("cpuid"
                  : "=a"(cpuid.EAX.raw), "=b"(cpuid.EBX.raw), "=c"(cpuid.ECX.raw), "=d"(cpuid.EDX.raw)
                  : "a"(0x1));
             if (Type == SIMD_SSE42)
                 return cpuid.ECX.SSE4_2;
             else if (Type == SIMD_SSE41)
                 return cpuid.ECX.SSE4_1;
             else if (Type == SIMD_SSSE3)
                 return cpuid.ECX.SSSE3;
             else if (Type == SIMD_SSE3)
                 return cpuid.ECX.SSE3;
             else if (Type == SIMD_SSE2)
                 return cpuid.EDX.SSE2;
             else if (Type == SIMD_SSE)
                 return cpuid.EDX.SSE;
         }
 #endif // a64 || a32
         return false;
     }
References asmv(), CPU::x64::cpuid(), SIMD_SSE, SIMD_SSE2, SIMD_SSE3, SIMD_SSE41, SIMD_SSE42, SIMD_SSSE3, SSEEnabled, strcmp, unlikely, Vendor(), x86_CPUID_VENDOR_AMD, and x86_CPUID_VENDOR_INTEL.
Counter()
uint64_t CPU::Counter ()
Get CPU counter value.
Definition at line 391 of file cpu.cpp.
     {
         // TODO: Get the counter from the x2APIC or any other timer that is available. (TSC is not available on all CPUs)
         uint64_t Counter;
 #if defined(a86)
         uint32_t eax, edx;
         asmv("rdtsc"
              : "=a"(eax),
                "=d"(edx));
         Counter = ((uint64_t)eax) | (((uint64_t)edx) << 32);
 #elif defined(aa64)
         asmv("mrs %0, cntvct_el0"
              : "=r"(Counter));
 #endif
         return Counter;
     }
References asmv().
Referenced by Time::TimeStampCounter::GetCounter(), and Time::TimeStampCounter::TimeStampCounter().
GetCPUFeat()
SupportedFeat CPU::GetCPUFeat ()
Definition at line 246 of file cpu.cpp.
     {
         SupportedFeat feat{};
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
             CPU::x86::AMD::CPUID0x00000001 cpuid1;
             CPU::x86::AMD::CPUID0x00000007_ECX_0 cpuid7;
             feat.PGE = cpuid1.EDX.PGE;
             feat.SSE = cpuid1.EDX.SSE;
             feat.SMEP = cpuid7.EBX.SMEP;
             feat.SMAP = cpuid7.EBX.SMAP;
             feat.UMIP = cpuid7.ECX.UMIP;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
             CPU::x86::Intel::CPUID0x00000001 cpuid1;
             CPU::x86::Intel::CPUID0x00000007_0 cpuid7_0;
             feat.PGE = cpuid1.EDX.PGE;
             feat.SSE = cpuid1.EDX.SSE;
             feat.SMEP = cpuid7_0.EBX.SMEP;
             feat.SMAP = cpuid7_0.EBX.SMAP;
             feat.UMIP = cpuid7_0.ECX.UMIP;
         }
         return feat;
     }
References CPU::x86::AMD::CPUID0x00000007_ECX_0::EBX, CPU::x86::Intel::CPUID0x00000007_0::EBX, CPU::x86::AMD::CPUID0x00000007_ECX_0::ECX, CPU::x86::Intel::CPUID0x00000007_0::ECX, CPU::x86::AMD::CPUID0x00000001::EDX, CPU::x86::Intel::CPUID0x00000001::EDX, strcmp, Vendor(), x86_CPUID_VENDOR_AMD, and x86_CPUID_VENDOR_INTEL.
Referenced by InitializeFeatures().
Halt()
static nsa __always_inline void CPU::Halt (bool Loop = false) inline static
Halt the CPU.
Definition at line 177 of file cpu.hpp.
     {
         do
         {
 #if defined(a86)
             asmv("hlt");
 #elif defined(aa64)
             asmv("wfe");
 #endif
         } while (Loop);
     }
References asmv().
Referenced by arm64Entry(), cmd_exit(), cmd_reboot(), cmd_shutdown(), DisplayCrashScreen(), KernelMainThread(), Main(), Memory::Physical::RequestPages(), StartCPU(), NetworkInterfaceManager::NetworkInterface::StartNetworkStack(), and ThreadDoExit().
Hypervisor()
const char * CPU::Hypervisor ()
Get CPU hypervisor vendor.
Returns
Hypervisor vendor.
Definition at line 106 of file cpu.cpp.
     {
         static char Hypervisor[13] = {0};
         if (Hypervisor[0] != 0)
             return Hypervisor;
 #if defined(a64)
         uint32_t eax, ebx, ecx, edx;
         x64::cpuid(0x1, &eax, &ebx, &ecx, &edx);
         if (!(ecx & (1 << 31))) /* Intel & AMD are the same */
         {
             Hypervisor[0] = 'N';
             Hypervisor[1] = 'o';
             Hypervisor[2] = 'n';
             Hypervisor[3] = 'e';
             return Hypervisor;
         }
         x64::cpuid(0x40000000, &eax, &ebx, &ecx, &edx);
         memcpy(Hypervisor + 0, &ebx, 4);
         memcpy(Hypervisor + 4, &ecx, 4);
         memcpy(Hypervisor + 8, &edx, 4);
 #elif defined(a32)
         uint32_t eax, ebx, ecx, edx;
         x32::cpuid(0x1, &eax, &ebx, &ecx, &edx);
         if (!(ecx & (1 << 31))) /* Intel & AMD are the same */
         {
             Hypervisor[0] = 'N';
             Hypervisor[1] = 'o';
             Hypervisor[2] = 'n';
             Hypervisor[3] = 'e';
             return Hypervisor;
         }
         x32::cpuid(0x40000000, &eax, &ebx, &ecx, &edx);
         memcpy(Hypervisor + 0, &ebx, 4);
         memcpy(Hypervisor + 4, &ecx, 4);
         memcpy(Hypervisor + 8, &edx, 4);
 #elif defined(aa64)
 #error "Not implemented"
 #endif
         return Hypervisor;
     }
References CPU::x32::cpuid(), CPU::x64::cpuid(), and memcpy.
Referenced by DetectByHypervisor(), DisplayTopOverlay(), Entry(), InitializeFeatures(), Main(), Random::rand16(), Random::rand32(), and Random::rand64().
InitializeFeatures()
void CPU::InitializeFeatures (int Core)
To be used only once.
Definition at line 276 of file cpu.cpp.
     {
         static int BSP = 0;
         SupportedFeat feat = GetCPUFeat();
         CR0 cr0 = readcr0();
         CR4 cr4 = readcr4();
         if (Config.SIMD == false)
         {
             debug("Disabling SSE support...");
             feat.SSE = false;
         }
         if (feat.PGE)
         {
             debug("Enabling global pages support...");
             if (!BSP)
                 KPrint("Global Pages is supported.");
             cr4.PGE = true;
         }
         bool SSEEnableAfter = false;
         /* Not sure if my code is not working properly or something else is the issue. */
         if ((strcmp(Hypervisor(), x86_CPUID_VENDOR_VIRTUALBOX) != 0) &&
             feat.SSE)
         {
             debug("Enabling SSE support...");
             if (!BSP)
                 KPrint("SSE is supported.");
             cr0.EM = false;
             cr0.MP = true;
             cr4.OSFXSR = true;
             cr4.OSXMMEXCPT = true;
             CPUData *CoreData = GetCPU(Core);
             CoreData->Data.FPU.mxcsr = 0b0001111110000000;
             CoreData->Data.FPU.mxcsrmask = 0b1111111110111111;
             CoreData->Data.FPU.fcw = 0b0000001100111111;
             fxrstor(&CoreData->Data.FPU);
             SSEEnableAfter = true;
         }
         /* More info in AMD64 Architecture Programmer's Manual
             Volume 2: 3.1.1 CR0 Register */
         /* Not Write-Through
             This is ignored on recent processors.
         */
         cr0.NW = false;
         /* Cache Disable
             Wether the CPU should cache memory or not.
             If it's enabled, PWT and PCD are ignored.
         */
         cr0.CD = false;
         /* Write Protect
             When set, the supervisor can't write to read-only pages.
         */
         cr0.WP = true;
         /* Alignment check
             The CPU checks the alignment of memory operands
             and generates #AC if the alignment is incorrect.
             The condition for an alignment check is:
             - The AM flag in CR0 is set.
             - The AC flag in the RFLAGS register is set.
             - CPL is 3.
         */
         cr0.AM = true;
         debug("Updating CR0...");
         writecr0(cr0);
         debug("Updated CR0.");
         debug("CPU Prevention Features:%s%s%s",
               feat.SMEP ? " SMEP" : "",
               feat.SMAP ? " SMAP" : "",
               feat.UMIP ? " UMIP" : "");
         /* User-Mode Instruction Prevention
             This prevents user-mode code from executing these instructions:
                 SGDT, SIDT, SLDT, SMSW, STR
             If any of these instructions are executed with CPL > 0, a #GP is generated.
         */
         // cr4.UMIP = feat.UMIP;
         /* Supervisor Mode Execution Prevention
             This prevents user-mode code from executing code in the supervisor mode.
         */
         cr4.SMEP = feat.SMEP;
         /* Supervisor Mode Access Prevention
             This prevents supervisor-mode code from accessing user-mode pages.
         */
         cr4.SMAP = feat.SMAP;
         debug("Updating CR4...");
         writecr4(cr4);
         debug("Updated CR4.");
         debug("Enabling PAT support...");
         wrmsr(MSR_CR_PAT, 0x6 | (0x0 << 8) | (0x1 << 16));
         if (!BSP++)
             trace("Features for BSP initialized.");
         if (SSEEnableAfter)
         {
             SSEEnabled = true;
             debug("SSE support enabled.");
         }
     }
References Config, CPUData::Data, debug, CPU::x64::fxrstor(), GetCPU(), GetCPUFeat(), Hypervisor(), KPrint(), CPU::x64::MSR_CR_PAT, CPU::SupportedFeat::PGE, KernelConfig::SIMD, CPU::SupportedFeat::SMAP, CPU::SupportedFeat::SMEP, CPU::SupportedFeat::SSE, SSEEnabled, strcmp, trace, CPU::SupportedFeat::UMIP, and x86_CPUID_VENDOR_VIRTUALBOX.
Referenced by Main(), and StartCPU().
Interrupts()
bool CPU::Interrupts (InterruptsType Type = Check)
Check if interrupts are enabled.
Returns
true If InterruptsType::Check and interrupts are enabled, or if other InterruptsType were executed successfully
false If InterruptsType::Check and interrupts are disabled, or if other InterruptsType failed
Definition at line 149 of file cpu.cpp.
     {
         switch (Type)
         {
         case Check:
         {
             uintptr_t Flags;
 #if defined(a64)
             asmv("pushfq");
             asmv("popq %0"
                  : "=r"(Flags));
             return Flags & (1 << 9);
 #elif defined(a32)
             asmv("pushfl");
             asmv("popl %0"
                  : "=r"(Flags));
             return Flags & (1 << 9);
 #elif defined(aa64)
             asmv("mrs %0, cpsr"
                  : "=r"(Flags));
             return Flags & (1 << 7);
 #endif
         }
         case Enable:
         {
 #if defined(a86)
             asmv("sti");
 #elif defined(aa64)
             asmv("cpsie i");
 #endif
             return true;
         }
         case Disable:
         {
 #if defined(a86)
             asmv("cli");
 #elif defined(aa64)
             asmv("cpsid i");
 #endif
             return true;
         }
         default:
             assert(!"Unknown InterruptsType");
             break;
         }
         return false;
     }
References asmv(), assert, Check, Disable, Enable, and Flags.
Referenced by CrashKeyboardDriver::CrashKeyboardDriver(), Interrupts::Enable(), StartCPU(), and Tasking::Task::Task().
Name()
const char * CPU::Name ()
Get CPU name.
Returns
CPU Name.
Definition at line 61 of file cpu.cpp.
     {
         static char Name[49] = {0};
         if (Name[0] != 0)
             return Name;
 #if defined(a64)
         uint32_t eax, ebx, ecx, edx;
         x64::cpuid(0x80000002, &eax, &ebx, &ecx, &edx);
         memcpy(Name + 0, &eax, 4);
         memcpy(Name + 4, &ebx, 4);
         memcpy(Name + 8, &ecx, 4);
         memcpy(Name + 12, &edx, 4);
         x64::cpuid(0x80000003, &eax, &ebx, &ecx, &edx);
         memcpy(Name + 16, &eax, 4);
         memcpy(Name + 20, &ebx, 4);
         memcpy(Name + 24, &ecx, 4);
         memcpy(Name + 28, &edx, 4);
         x64::cpuid(0x80000004, &eax, &ebx, &ecx, &edx);
         memcpy(Name + 32, &eax, 4);
         memcpy(Name + 36, &ebx, 4);
         memcpy(Name + 40, &ecx, 4);
         memcpy(Name + 44, &edx, 4);
 #elif defined(a32)
         uint32_t eax, ebx, ecx, edx;
         x32::cpuid(0x80000002, &eax, &ebx, &ecx, &edx);
         memcpy(Name + 0, &eax, 4);
         memcpy(Name + 4, &ebx, 4);
         memcpy(Name + 8, &ecx, 4);
         memcpy(Name + 12, &edx, 4);
         x32::cpuid(0x80000003, &eax, &ebx, &ecx, &edx);
         memcpy(Name + 16, &eax, 4);
         memcpy(Name + 20, &ebx, 4);
         memcpy(Name + 24, &ecx, 4);
         memcpy(Name + 28, &edx, 4);
         x32::cpuid(0x80000004, &eax, &ebx, &ecx, &edx);
         memcpy(Name + 32, &eax, 4);
         memcpy(Name + 36, &ebx, 4);
         memcpy(Name + 40, &ecx, 4);
         memcpy(Name + 44, &edx, 4);
 #elif defined(aa64)
 #error "Not implemented"
 #endif
         return Name;
     }
References CPU::x32::cpuid(), CPU::x64::cpuid(), and memcpy.
Referenced by SymbolResolver::Symbols::AddSymbol(), vfs::Virtual::Create(), CreateKernelProcess(), Driver::CreateKernelProcess(), Driver::CreateKernelThread(), CreateKernelThread(), Tasking::Task::CreateProcess(), Execute::ELFGetSections_x86_64(), Execute::ELFGetSymbolValue(), ElfHash(), Execute::ELFLoadRel(), ELFLookupSymbol(), Execute::ELFLookupSymbol(), Driver::GetDriverInfo(), SymbolResolver::Symbols::GetSymbol(), Main(), Driver::Manager::Manager(), Tasking::PCB::Rename(), Tasking::PCB::SetExe(), Tasking::PCB::SetWorkingDirectory(), Tasking::Task::SignalShutdown(), StartKernelShell(), and Tasking::Task::~Task().
PageTable()
void * CPU::PageTable (void * PT = nullptr)
Get/Set the CPU's page table.
Parameters
PT The new page table, if empty, the current page table will be returned
Returns
Get: The current page table
Set: The old page table
Definition at line 197 of file cpu.cpp.
     {
         void *ret;
 #if defined(a64)
         asmv("movq %%cr3, %0"
              : "=r"(ret));
         if (PT)
         {
             asmv("movq %0, %%cr3"
                  :
                  : "r"(PT)
                  : "memory");
         }
 #elif defined(a32)
         asmv("movl %%cr3, %0"
              : "=r"(ret));
         if (PT)
         {
             asmv("movl %0, %%cr3"
                  :
                  : "r"(PT)
                  : "memory");
         }
 #elif defined(aa64)
         asmv("mrs %0, ttbr0_el1"
              : "=r"(ret));
         if (PT)
         {
             asmv("msr ttbr0_el1, %0"
                  :
                  : "r"(PT)
                  : "memory");
         }
 #endif
         return ret;
     }
References asmv().
Referenced by BaseBufferStackError(), HandleException(), InitializeMemoryManagement(), Tasking::Signal::RestoreHandleSignal(), and UserInput().
Pause()
static nsa __always_inline void CPU::Pause (bool Loop = false) inline static
Pause the CPU.
Definition at line 142 of file cpu.hpp.
     {
         do
         {
 #if defined(a86)
             asmv("pause");
 #elif defined(aa64)
             asmv("yield");
 #endif
         } while (Loop);
     }
References asmv().
Referenced by ACPI::ACPI::ACPI(), HandleUnrecoverableException(), Time::HighPrecisionEventTimer::Sleep(), Time::TimeStampCounter::Sleep(), and APIC::APIC::WaitForIPI().
Stop()
nsa __noreturn __used void CPU::Stop () inline
Stop the CPU (infinite loop)
Definition at line 157 of file cpu.hpp.
     {
 #if defined(a86)
         asmv("CPUStopLoop:\n"
              "cli\n"
              "hlt\n"
              "jmp CPUStopLoop");
 #elif defined(aa64)
         asmv("CPUStopLoop:\n"
              "cpsid i\n"
              "wfe\n"
              "wfi\n"
              "b CPUStopLoop");
 #endif
         __builtin_unreachable();
     }
References asmv().
Referenced by __cxxabiv1::__cxa_bad_typeid(), __cxxabiv1::__cxa_throw(), calloc(), CrashKeyboardDriver::CrashKeyboardDriver(), DisplayAssertionFailed(), DisplayCrashScreen(), free(), HandleBufferOverflow(), HandleException(), HandleExceptionInsideException(), HandleStackSmashing(), HandleUnrecoverableException(), Memory::Physical::Init(), Interrupts::Initialize(), InitializeMemoryManagement(), KernelShutdownThread(), KernelVFS(), linux_reboot(), Interrupts::MainInterruptHandler(), malloc(), multiboot2_parse(), multiboot_main(), ACPI::DSDT::OnInterruptReceived(), ParseConfig(), realloc(), Memory::Physical::RequestPage(), __cxxabiv1::terminate_header_stub(), and UserInput().
Vendor()
const char * CPU::Vendor ()
Get CPU vendor identifier.
Returns
CPU Vendor ID.
Definition at line 38 of file cpu.cpp.
     {
         static char Vendor[13] = {0};
         if (Vendor[0] != 0)
             return Vendor;
 #if defined(a64)
         uint32_t eax, ebx, ecx, edx;
         x64::cpuid(0x0, &eax, &ebx, &ecx, &edx);
         memcpy(Vendor + 0, &ebx, 4);
         memcpy(Vendor + 4, &edx, 4);
         memcpy(Vendor + 8, &ecx, 4);
 #elif defined(a32)
         uint32_t eax, ebx, ecx, edx;
         x32::cpuid(0x0, &eax, &ebx, &ecx, &edx);
         memcpy(Vendor + 0, &ebx, 4);
         memcpy(Vendor + 4, &edx, 4);
         memcpy(Vendor + 8, &ecx, 4);
 #elif defined(aa64)
 #error "Not implemented"
 #endif
         return Vendor;
     }
References CPU::x32::cpuid(), CPU::x64::cpuid(), and memcpy.
Referenced by APIC::APIC::APIC(), CheckSIMD(), CreatePageTable(), DetectByCPUID(), DisplayTopOverlay(), Time::time::FindTimers(), GetCPUFeat(), Main(), Random::rand16(), Random::rand32(), Random::rand64(), and Tasking::Task::Task().
Variable Documentation
SSEEnabled
bool CPU::SSEEnabled = false static
Definition at line 36 of file cpu.cpp.
Referenced by CheckSIMD(), and InitializeFeatures().