Fennix: Userspace/musl/src/search/tsearch.c File Reference
tsearch.c File Reference
#include <stdlib.h>
#include <search.h>
#include "tsearch.h"
Functions
static int height (struct node *n)
static int rot (void **p, struct node *x, int dir)
int __tsearch_balance (void **p)
void * tsearch (const void *key, void **rootp, int(*cmp)(const void *, const void *))
Function Documentation
__tsearch_balance()
int __tsearch_balance (void ** p)
Definition at line 49 of file tsearch.c.
 {
     struct node *n = *p;
     int h0 = height(n->a[0]);
     int h1 = height(n->a[1]);
     if (h0 - h1 + 1u < 3u) {
         int old = n->h;
         n->h = h0<h1 ? h1+1 : h0+1;
         return n->h - old;
     }
     return rot(p, n, h0<h1);
 }
References height(), n, old, p, and rot().
Referenced by tdelete(), and tsearch().
height()
static int height (struct node * n) inline static
Definition at line 5 of file tsearch.c.
 { return n ? n->h : 0; }
References n.
Referenced by __tsearch_balance(), attr_clear(), ConfigMainWindow::ConfigMainWindow(), dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), dialog_yesno(), display_window_size(), do_load(), do_loadfont(), draw_box(), draw_shadow(), EV_BuildStairs(), fb_drawimage(), fb_drawprogressbar(), get_terminal_width_height(), HUlib_initSText(), M_Drawer(), M_StringHeight(), P_FindHighestCeilingSurrounding(), P_FindLowestCeilingSurrounding(), P_FindNextHighestFloor(), P_TryMove(), print_arrows(), print_buttons(), print_page(), print_position(), PTR_SlideTraverse(), R_FindPlane(), R_InitBuffer(), rl_resize_terminal(), rot(), ConfigMainWindow::saveSettings(), V_CopyRect(), V_DrawBlock(), V_MarkRect(), WI_drawOnLnode(), WI_drawStats(), wipe_doColorXForm(), wipe_doMelt(), wipe_EndScreen(), wipe_initColorXForm(), wipe_initMelt(), wipe_ScreenWipe(), wipe_shittyColMajorXform(), and WritePCXfile().
rot()
static int rot (void ** p, struct node * x, int dir) static
Definition at line 7 of file tsearch.c.
 {
     struct node *y = x->a[dir];
     struct node *z = y->a[!dir];
     int hx = x->h;
     int hz = height(z);
     if (hz > height(y->a[dir])) {
         /*
          *   x
          *  / \ dir          z
          * A   y            / \
          *    / \   -->    x   y
          *   z   D        /|   |\
          *  / \          A B   C D
          * B   C
          */
         x->a[dir] = z->a[!dir];
         y->a[!dir] = z->a[dir];
         z->a[!dir] = x;
         z->a[dir] = y;
         x->h = hz;
         y->h = hz;
         z->h = hz+1;
     } else {
         /*
          *   x               y
          *  / \             / \
          * A   y    -->    x   D
          *    / \         / \
          *   z   D       A   z
          */
         x->a[dir] = z;
         y->a[!dir] = x;
         x->h = hz+1;
         y->h = hz+2;
         z = y;
     }
     *p = z;
     return z->h - hx;
 }
References node::a, dir, node::h, height(), p, x, and y.
Referenced by __tsearch_balance(), and R_ProjectSprite().
tsearch()
void* tsearch (const void * key, void ** rootp, int(*)(const void *, const void *) cmp)
Definition at line 62 of file tsearch.c.
 {
     if (!rootp)
         return 0;
     void **a[MAXH];
     struct node *n = *rootp;
     struct node *r;
     int i=0;
     a[i++] = rootp;
     for (;;) {
         if (!n)
             break;
         int c = cmp(key, n->key);
         if (!c)
             return n;
         a[i++] = &n->a[c>0];
         n = n->a[c>0];
     }
     r = malloc(sizeof *r);
     if (!r)
         return 0;
     r->key = key;
     r->a[0] = r->a[1] = 0;
     r->h = 1;
     /* insert new node, rebalance ancestors.  */
     *a[--i] = r;
     while (i && __tsearch_balance(a[--i]));
     return r;
 }
References __tsearch_balance(), node::a, c, cmp(), node::h, i, node::key, malloc, MAXH, and n.
Referenced by while().