Fennix Userspace: Userspace/musl/include/wchar.h File Reference
wchar.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define __NEED_FILE
#define __NEED___isoc_va_list
#define __NEED_size_t
#define __NEED_wchar_t
#define __NEED_wint_t
#define __NEED_mbstate_t
#define __NEED_struct__IO_FILE
#define WCHAR_MAX (0x7fffffff+L'\0')
#define WCHAR_MIN (-1-0x7fffffff+L'\0')
#define NULL ((void*)0)
#define WEOF 0xffffffffU
Functions
wchar_t * wcscpy (wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcsncpy (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wcscat (wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcsncat (wchar_t *__restrict, const wchar_t *__restrict, size_t)
int wcscmp (const wchar_t *, const wchar_t *)
int wcsncmp (const wchar_t *, const wchar_t *, size_t)
int wcscoll (const wchar_t *, const wchar_t *)
size_t wcsxfrm (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wcschr (const wchar_t *, wchar_t)
wchar_t * wcsrchr (const wchar_t *, wchar_t)
size_t wcscspn (const wchar_t *, const wchar_t *)
size_t wcsspn (const wchar_t *, const wchar_t *)
wchar_t * wcspbrk (const wchar_t *, const wchar_t *)
wchar_t * wcstok (wchar_t *__restrict, const wchar_t *__restrict, wchar_t **__restrict)
size_t wcslen (const wchar_t *)
wchar_t * wcsstr (const wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcswcs (const wchar_t *, const wchar_t *)
wchar_t * wmemchr (const wchar_t *, wchar_t, size_t)
int wmemcmp (const wchar_t *, const wchar_t *, size_t)
wchar_t * wmemcpy (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wmemmove (wchar_t *, const wchar_t *, size_t)
wchar_t * wmemset (wchar_t *, wchar_t, size_t)
wint_t btowc (int)
int wctob (wint_t)
int mbsinit (const mbstate_t *)
size_t mbrtowc (wchar_t *__restrict, const char *__restrict, size_t, mbstate_t *__restrict)
size_t wcrtomb (char *__restrict, wchar_t, mbstate_t *__restrict)
size_t mbrlen (const char *__restrict, size_t, mbstate_t *__restrict)
size_t mbsrtowcs (wchar_t *__restrict, const char **__restrict, size_t, mbstate_t *__restrict)
size_t wcsrtombs (char *__restrict, const wchar_t **__restrict, size_t, mbstate_t *__restrict)
float wcstof (const wchar_t *__restrict, wchar_t **__restrict)
double wcstod (const wchar_t *__restrict, wchar_t **__restrict)
long double wcstold (const wchar_t *__restrict, wchar_t **__restrict)
long wcstol (const wchar_t *__restrict, wchar_t **__restrict, int)
unsigned long wcstoul (const wchar_t *__restrict, wchar_t **__restrict, int)
long long wcstoll (const wchar_t *__restrict, wchar_t **__restrict, int)
unsigned long long wcstoull (const wchar_t *__restrict, wchar_t **__restrict, int)
int fwide (FILE *, int)
int wprintf (const wchar_t *__restrict,...)
int fwprintf (FILE *__restrict, const wchar_t *__restrict,...)
int swprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict,...)
int vwprintf (const wchar_t *__restrict, __isoc_va_list)
int vfwprintf (FILE *__restrict, const wchar_t *__restrict, __isoc_va_list)
int vswprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict, __isoc_va_list)
int wscanf (const wchar_t *__restrict,...)
int fwscanf (FILE *__restrict, const wchar_t *__restrict,...)
int swscanf (const wchar_t *__restrict, const wchar_t *__restrict,...)
int vwscanf (const wchar_t *__restrict, __isoc_va_list)
int vfwscanf (FILE *__restrict, const wchar_t *__restrict, __isoc_va_list)
int vswscanf (const wchar_t *__restrict, const wchar_t *__restrict, __isoc_va_list)
wint_t fgetwc (FILE *)
wint_t getwc (FILE *)
wint_t getwchar (void)
wint_t fputwc (wchar_t, FILE *)
wint_t putwc (wchar_t, FILE *)
wint_t putwchar (wchar_t)
wchar_t * fgetws (wchar_t *__restrict, int, FILE *__restrict)
int fputws (const wchar_t *__restrict, FILE *__restrict)
wint_t ungetwc (wint_t, FILE *)
size_t wcsftime (wchar_t *__restrict, size_t, const wchar_t *__restrict, const struct tm *__restrict)
Macro Definition Documentation
__NEED___isoc_va_list
#define __NEED___isoc_va_list
Definition at line 11 of file wchar.h.
__NEED_FILE
#define __NEED_FILE
Definition at line 10 of file wchar.h.
__NEED_mbstate_t
#define __NEED_mbstate_t
Definition at line 15 of file wchar.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 12 of file wchar.h.
__NEED_struct__IO_FILE
#define __NEED_struct__IO_FILE
Definition at line 18 of file wchar.h.
__NEED_wchar_t
#define __NEED_wchar_t
Definition at line 13 of file wchar.h.
__NEED_wint_t
#define __NEED_wint_t
Definition at line 14 of file wchar.h.
NULL
#define NULL ((void*)0)
Definition at line 46 of file wchar.h.
WCHAR_MAX
#define WCHAR_MAX (0x7fffffff+L'\0')
Definition at line 37 of file wchar.h.
WCHAR_MIN
#define WCHAR_MIN (-1-0x7fffffff+L'\0')
Definition at line 38 of file wchar.h.
WEOF
#define WEOF 0xffffffffU
Definition at line 50 of file wchar.h.
Function Documentation
btowc()
wint_t btowc (int c)
Definition at line 6 of file btowc.c.
 {
     int b = (unsigned char)c;
     return b<128U ? b : (MB_CUR_MAX==1 && c!=EOF) ? CODEUNIT(c) : WEOF;
 }
References c, CODEUNIT, EOF, MB_CUR_MAX, and WEOF.
Referenced by wprintf_core().
fgetwc()
wint_t fgetwc (FILE * f)
Definition at line 58 of file fgetwc.c.
 {
     wint_t c;
     FLOCK(f);
     c = __fgetwc_unlocked(f);
     FUNLOCK(f);
     return c;
 }
References __fgetwc_unlocked(), c, f, FLOCK, and FUNLOCK.
Referenced by getwc(), and getwchar().
fgetws()
wchar_t* fgetws (wchar_t * __restrict, int , FILE * __restrict)
fputwc()
wint_t fputwc (wchar_t c, FILE * f)
Definition at line 31 of file fputwc.c.
 {
     FLOCK(f);
     c = __fputwc_unlocked(c, f);
     FUNLOCK(f);
     return c;
 }
References __fputwc_unlocked(), c, f, FLOCK, and FUNLOCK.
Referenced by out(), putwc(), and putwchar().
fputws()
int fputws (const wchar_t * __restrict, FILE * __restrict)
fwide()
int fwide (FILE * f, int mode)
Definition at line 5 of file fwide.c.
 {
     FLOCK(f);
     if (mode) {
         if (!f->locale) f->locale = MB_CUR_MAX==1
             ? C_LOCALE : UTF8_LOCALE;
         if (!f->mode) f->mode = mode>0 ? 1 : -1;
     }
     mode = f->mode;
     FUNLOCK(f);
     return mode;
 }
References C_LOCALE, f, FLOCK, FUNLOCK, _IO_FILE::locale, MB_CUR_MAX, _IO_FILE::mode, and UTF8_LOCALE.
Referenced by __fgetwc_unlocked(), __fputwc_unlocked(), fputws(), open_wmemstream(), ungetwc(), vfwprintf(), and vfwscanf().
fwprintf()
int fwprintf (FILE * __restrict, const wchar_t * __restrict, ...)
fwscanf()
int fwscanf (FILE * __restrict, const wchar_t * __restrict, ...)
getwc()
wint_t getwc (FILE * f)
Definition at line 4 of file getwc.c.
 {
     return fgetwc(f);
 }
References f, and fgetwc().
getwchar()
wint_t getwchar (void)
Definition at line 4 of file getwchar.c.
 {
     return fgetwc(stdin);
 }
References fgetwc(), and stdin.
mbrlen()
size_t mbrlen (const char * __restrict, size_t , mbstate_t * __restrict)
Referenced by mbschr().
mbrtowc()
size_t mbrtowc (wchar_t * __restrict, const char * __restrict, size_t , mbstate_t * __restrict)
Referenced by __fgetwc_unlocked_internal(), ansic_quote(), ansicstr(), mbrlen(), mbrtoc16(), mbrtoc32(), mbsnrtowcs(), read_comsub(), sh_modcase(), and vfscanf().
mbsinit()
int mbsinit (const mbstate_t * st)
Definition at line 3 of file mbsinit.c.
 {
     return !st || !*(unsigned *)st;
 }
Referenced by vfscanf().
mbsrtowcs()
size_t mbsrtowcs (wchar_t * __restrict, const char ** __restrict, size_t , mbstate_t * __restrict)
Referenced by mbsnrtowcs(), mbstowcs(), and unicode_conv_to_printable2().
putwc()
wint_t putwc (wchar_t c, FILE * f)
Definition at line 4 of file putwc.c.
 {
     return fputwc(c, f);
 }
References c, f, and fputwc().
putwchar()
wint_t putwchar (wchar_t c)
Definition at line 4 of file putwchar.c.
 {
     return fputwc(c, stdout);
 }
References c, fputwc(), and stdout.
swprintf()
int swprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, ...)
swscanf()
int swscanf (const wchar_t * __restrict, const wchar_t * __restrict, ...)
ungetwc()
wint_t ungetwc (wint_t c, FILE * f)
Definition at line 8 of file ungetwc.c.
 {
     unsigned char mbc[MB_LEN_MAX];
     int l;
     locale_t *ploc = &CURRENT_LOCALE, loc = *ploc;
     FLOCK(f);
     if (f->mode <= 0) fwide(f, 1);
     *ploc = f->locale;
     if (!f->rpos) __toread(f);
     if (!f->rpos || c == WEOF || (l = wcrtomb((void *)mbc, c, 0)) < 0 ||
         f->rpos < f->buf - UNGET + l) {
         FUNLOCK(f);
         *ploc = loc;
         return WEOF;
     }
     if (isascii(c)) *--f->rpos = c;
     else memcpy(f->rpos -= l, mbc, l);
     f->flags &= ~F_EOF;
     FUNLOCK(f);
     *ploc = loc;
     return c;
 }
References __toread(), _IO_FILE::buf, c, CURRENT_LOCALE, f, F_EOF, _IO_FILE::flags, FLOCK, FUNLOCK, fwide(), isascii(), l, _IO_FILE::locale, MB_LEN_MAX, memcpy(), _IO_FILE::mode, _IO_FILE::rpos, UNGET, wcrtomb(), and WEOF.
vfwprintf()
int vfwprintf (FILE * __restrict, const wchar_t * __restrict, __isoc_va_list)
Referenced by fwprintf(), vswprintf(), and vwprintf().
vfwscanf()
int vfwscanf (FILE * __restrict, const wchar_t * __restrict, __isoc_va_list)
Referenced by fwscanf(), vswscanf(), and vwscanf().
vswprintf()
int vswprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, __isoc_va_list)
Referenced by swprintf().
vswscanf()
int vswscanf (const wchar_t * __restrict, const wchar_t * __restrict, __isoc_va_list)
Referenced by swscanf().
vwprintf()
int vwprintf (const wchar_t * __restrict, __isoc_va_list)
Referenced by wprintf().
vwscanf()
int vwscanf (const wchar_t * __restrict, __isoc_va_list)
Referenced by wscanf().
wcrtomb()
size_t wcrtomb (char * __restrict, wchar_t , mbstate_t * __restrict)
wcscat()
wchar_t* wcscat (wchar_t * __restrict, const wchar_t * __restrict)
wcschr()
wchar_t* wcschr (const wchar_t * s, wchar_t c)
Definition at line 3 of file wcschr.c.
 {
     if (!c) return (wchar_t *)s + wcslen(s);
     for (; *s && *s != c; s++);
     return *s ? (wchar_t *)s : 0;
 }
References c, s, and wcslen().
Referenced by iswspace(), string_extract_verbatim(), wcscspn(), wcsspn(), and wcsstr().
wcscmp()
int wcscmp (const wchar_t * l, const wchar_t * r)
Definition at line 3 of file wcscmp.c.
 {
     for (; *l==*r && *l && *r; l++, r++);
     return *l < *r ? -1 : *l > *r;
 }
References l.
Referenced by __wcscoll_l().
wcscoll()
int wcscoll (const wchar_t * l, const wchar_t * r)
Definition at line 11 of file wcscoll.c.
 {
     return __wcscoll_l(l, r, CURRENT_LOCALE);
 }
References __wcscoll_l(), CURRENT_LOCALE, and l.
wcscpy()
wchar_t* wcscpy (wchar_t * __restrict, const wchar_t * __restrict)
Referenced by wcpcpy(), and wcscat().
wcscspn()
size_t wcscspn (const wchar_t * s, const wchar_t * c)
Definition at line 3 of file wcscspn.c.
 {
     const wchar_t *a;
     if (!c[0]) return wcslen(s);
     if (!c[1]) return (s=wcschr(a=s, *c)) ? s-a : wcslen(a);
     for (a=s; *s && !wcschr(c, *s); s++);
     return s-a;
 }
References c, s, wcschr(), and wcslen().
Referenced by wcspbrk(), and wcstok().
wcsftime()
size_t wcsftime (wchar_t * __restrict, size_t , const wchar_t * __restrict, const struct tm * __restrict)
wcslen()
size_t wcslen (const wchar_t * s)
Definition at line 3 of file wcslen.c.
 {
     const wchar_t *a;
     for (a=s; *s; s++);
     return s-a;
 }
References s.
Referenced by __wcsxfrm_l(), wcpcpy(), wcscat(), wcschr(), wcscspn(), wcsdup(), wcsncat(), and wcsrchr().
wcsncat()
wchar_t* wcsncat (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wcsncmp()
int wcsncmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 3 of file wcsncmp.c.
 {
     for (; n && *l==*r && *l && *r; n--, l++, r++);
     return n ? (*l < *r ? -1 : *l > *r) : 0;
 }
References l, and n.
wcsncpy()
wchar_t* wcsncpy (wchar_t * __restrict, const wchar_t * __restrict, size_t)
Referenced by wcpncpy().
wcspbrk()
wchar_t* wcspbrk (const wchar_t * s, const wchar_t * b)
Definition at line 3 of file wcspbrk.c.
 {
     s += wcscspn(s, b);
     return *s ? (wchar_t *)s : NULL;
 }
References NULL, s, and wcscspn().
wcsrchr()
wchar_t* wcsrchr (const wchar_t * s, wchar_t c)
Definition at line 3 of file wcsrchr.c.
 {
     const wchar_t *p;
     for (p=s+wcslen(s); p>=s && *p!=c; p--);
     return p>=s ? (wchar_t *)p : 0;
 }
References c, p, s, and wcslen().
wcsrtombs()
size_t wcsrtombs (char * __restrict, const wchar_t ** __restrict, size_t , mbstate_t * __restrict)
Referenced by fputws(), remove_pattern(), wcstombs(), and wstring_read().
wcsspn()
size_t wcsspn (const wchar_t * s, const wchar_t * c)
Definition at line 3 of file wcsspn.c.
 {
     const wchar_t *a;
     for (a=s; *s && wcschr(c, *s); s++);
     return s-a;
 }
References c, s, and wcschr().
Referenced by wcstok().
wcsstr()
wchar_t* wcsstr (const wchar_t * __restrict, const wchar_t * __restrict)
Referenced by wcswcs().
wcstod()
double wcstod (const wchar_t * __restrict, wchar_t ** __restrict)
wcstof()
float wcstof (const wchar_t * __restrict, wchar_t ** __restrict)
wcstok()
wchar_t* wcstok (wchar_t * __restrict, const wchar_t * __restrict, wchar_t ** __restrict)
wcstol()
long wcstol (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstold()
long double wcstold (const wchar_t * __restrict, wchar_t ** __restrict)
wcstoll()
long long wcstoll (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstoul()
unsigned long wcstoul (const wchar_t * __restrict, wchar_t ** __restrict, int)
Referenced by __wcsftime_l().
wcstoull()
unsigned long long wcstoull (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcswcs()
wchar_t* wcswcs (const wchar_t * haystack, const wchar_t * needle)
Definition at line 3 of file wcswcs.c.
 {
     return wcsstr(haystack, needle);
 }
References wcsstr().
wcsxfrm()
size_t wcsxfrm (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wctob()
int wctob (wint_t c)
Definition at line 6 of file wctob.c.
 {
     if (c < 128U) return c;
     if (MB_CUR_MAX==1 && IS_CODEUNIT(c)) return (unsigned char)c;
     return EOF;
 }
References c, EOF, IS_CODEUNIT, and MB_CUR_MAX.
wmemchr()
wchar_t* wmemchr (const wchar_t * s, wchar_t c, size_t n)
Definition at line 3 of file wmemchr.c.
 {
     for (; n && *s != c; n--, s++);
     return n ? (wchar_t *)s : 0;
 }
References c, n, and s.
Referenced by twoway_wcsstr(), and wcsnlen().
wmemcmp()
int wmemcmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 3 of file wmemcmp.c.
 {
     for (; n && *l==*r; n--, l++, r++);
     return n ? (*l < *r ? -1 : *l > *r) : 0;
 }
References l, and n.
Referenced by twoway_wcsstr().
wmemcpy()
wchar_t* wmemcpy (wchar_t * __restrict, const wchar_t * __restrict, size_t)
Referenced by __wcsftime_l(), __wcsxfrm_l(), and wcsdup().
wmemmove()
wchar_t* wmemmove (wchar_t * d, const wchar_t * s, size_t n)
Definition at line 4 of file wmemmove.c.
 {
     wchar_t *d0 = d;
     if (d == s) return d;
     if ((uintptr_t)d-(uintptr_t)s < n * sizeof *d)
         while (n--) d[n] = s[n];
     else
         while (n--) *d++ = *s++;
     return d0;
 }
References n, and s.
wmemset()
wchar_t* wmemset (wchar_t * d, wchar_t c, size_t n)
Definition at line 3 of file wmemset.c.
 {
     wchar_t *ret = d;
     while (n--) *d++ = c;
     return ret;
 }
References c, and n.
Referenced by wcsncpy().
wprintf()
int wprintf (const wchar_t * __restrict, ...)
wscanf()
int wscanf (const wchar_t * __restrict, ...)