Fennix: Userspace/apps/base/busybox/findutils/xargs.c File Reference
xargs.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define dbg_msg(...) ((void)0)
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define OPTION_STR
#define ISSPACE(a) ({ unsigned char xargs__isspace = (a) - 9; xargs__isspace == (' ' - 9) || xargs__isspace <= (13 - 9); })
#define xargs_ask_confirmation() 1
#define read_args process_stdin
Enumerations
enum {
OPTBIT_VERBOSE = 0 , OPTBIT_NO_EMPTY , OPTBIT_UPTO_NUMBER , OPTBIT_UPTO_SIZE ,
OPTBIT_EOF_STRING , OPTBIT_EOF_STRING1 , OPTBIT_STDIN_TTY , OPT_VERBOSE = 1 << OPTBIT_VERBOSE ,
OPT_NO_EMPTY = 1 << OPTBIT_NO_EMPTY , OPT_UPTO_NUMBER = 1 << OPTBIT_UPTO_NUMBER , OPT_UPTO_SIZE = 1 << OPTBIT_UPTO_SIZE , OPT_EOF_STRING = 1 << OPTBIT_EOF_STRING ,
OPT_EOF_STRING1 = 1 << OPTBIT_EOF_STRING1 , OPT_STDIN_TTY = 1 << OPTBIT_STDIN_TTY , OPT_INTERACTIVE = IF_FEATURE_XARGS_SUPPORT_CONFIRMATION((1 << OPTBIT_INTERACTIVE)) + 0 , OPT_TERMINATE = IF_FEATURE_XARGS_SUPPORT_TERMOPT((1 << OPTBIT_TERMINATE)) + 0 ,
OPT_ZEROTERM = IF_FEATURE_XARGS_SUPPORT_ZERO_TERM((1 << OPTBIT_ZEROTERM)) + 0 , OPT_REPLSTR = IF_FEATURE_XARGS_SUPPORT_REPL_STR((1 << OPTBIT_REPLSTR)) + 0 , OPT_REPLSTR1 = IF_FEATURE_XARGS_SUPPORT_REPL_STR((1 << OPTBIT_REPLSTR1)) + 0
}
Functions
static int xargs_exec (void)
static void store_param (char *s)
static char *FAST_FUNC process_stdin (int n_max_chars, int n_max_arg, char *buf)
int xargs_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
dbg_msg
#define dbg_msg (...) ((void)0)
Definition at line 86 of file xargs.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 130 of file xargs.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    IF_FEATURE_XARGS_SUPPORT_REPL_STR(G.repl_str = "{}";) \
    IF_FEATURE_XARGS_SUPPORT_REPL_STR(G.eol_ch = '\n';) \
    /* Even zero values are set because we are NOEXEC applet */ \
    G.eof_str = NULL; \
    G.idx = 0; \
    IF_FEATURE_XARGS_SUPPORT_PARALLEL(G.running_procs = 0;) \
    IF_FEATURE_XARGS_SUPPORT_PARALLEL(G.max_procs = 1;) \
    G.xargs_exitcode = 0; \
    IF_FEATURE_XARGS_SUPPORT_QUOTES(G.process_stdin__state = NORM;) \
    IF_FEATURE_XARGS_SUPPORT_QUOTES(G.process_stdin__q = '\0';) \
} while (0)
Definition at line 131 of file xargs.c.
ISSPACE
#define ISSPACE (a) ({ unsigned char xargs__isspace = (a) - 9; xargs__isspace == (' ' - 9) || xargs__isspace <= (13 - 9); })
Definition at line 289 of file xargs.c.
OPTION_STR
#define OPTION_STR
Value:
    "+trn:s:e::E:o" \
    IF_FEATURE_XARGS_SUPPORT_CONFIRMATION("p") \
    IF_FEATURE_XARGS_SUPPORT_TERMOPT(     "x") \
    IF_FEATURE_XARGS_SUPPORT_ZERO_TERM(   "0") \
    IF_FEATURE_XARGS_SUPPORT_REPL_STR(    "I:i::") \
    IF_FEATURE_XARGS_SUPPORT_PARALLEL(    "P:+") \
    IF_FEATURE_XARGS_SUPPORT_ARGS_FILE(   "a:")
Definition at line 173 of file xargs.c.
read_args
#define read_args process_stdin
xargs_ask_confirmation
#define xargs_ask_confirmation () 1
Definition at line 575 of file xargs.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTBIT_VERBOSE
OPTBIT_NO_EMPTY
OPTBIT_UPTO_NUMBER
OPTBIT_UPTO_SIZE
OPTBIT_EOF_STRING
OPTBIT_EOF_STRING1
OPTBIT_STDIN_TTY
OPT_VERBOSE
OPT_NO_EMPTY
OPT_UPTO_NUMBER
OPT_UPTO_SIZE
OPT_EOF_STRING
OPT_EOF_STRING1
OPT_STDIN_TTY
OPT_INTERACTIVE
OPT_TERMINATE
OPT_ZEROTERM
OPT_REPLSTR
OPT_REPLSTR1
Definition at line 146 of file xargs.c.
      {
     OPTBIT_VERBOSE = 0,
     OPTBIT_NO_EMPTY,
     OPTBIT_UPTO_NUMBER,
     OPTBIT_UPTO_SIZE,
     OPTBIT_EOF_STRING,
     OPTBIT_EOF_STRING1,
     OPTBIT_STDIN_TTY,
     IF_FEATURE_XARGS_SUPPORT_CONFIRMATION(OPTBIT_INTERACTIVE,)
     IF_FEATURE_XARGS_SUPPORT_TERMOPT(     OPTBIT_TERMINATE  ,)
     IF_FEATURE_XARGS_SUPPORT_ZERO_TERM(   OPTBIT_ZEROTERM   ,)
     IF_FEATURE_XARGS_SUPPORT_REPL_STR(    OPTBIT_REPLSTR    ,)
     IF_FEATURE_XARGS_SUPPORT_REPL_STR(    OPTBIT_REPLSTR1   ,)
     OPT_VERBOSE     = 1 << OPTBIT_VERBOSE    ,
     OPT_NO_EMPTY    = 1 << OPTBIT_NO_EMPTY   ,
     OPT_UPTO_NUMBER = 1 << OPTBIT_UPTO_NUMBER,
     OPT_UPTO_SIZE   = 1 << OPTBIT_UPTO_SIZE  ,
     OPT_EOF_STRING  = 1 << OPTBIT_EOF_STRING , /* GNU: -e[<param>] */
     OPT_EOF_STRING1 = 1 << OPTBIT_EOF_STRING1, /* SUS: -E<param> */
     OPT_STDIN_TTY   = 1 << OPTBIT_STDIN_TTY,
     OPT_INTERACTIVE = IF_FEATURE_XARGS_SUPPORT_CONFIRMATION((1 << OPTBIT_INTERACTIVE)) + 0,
     OPT_TERMINATE   = IF_FEATURE_XARGS_SUPPORT_TERMOPT(     (1 << OPTBIT_TERMINATE  )) + 0,
     OPT_ZEROTERM    = IF_FEATURE_XARGS_SUPPORT_ZERO_TERM(   (1 << OPTBIT_ZEROTERM   )) + 0,
     OPT_REPLSTR     = IF_FEATURE_XARGS_SUPPORT_REPL_STR(    (1 << OPTBIT_REPLSTR    )) + 0,
     OPT_REPLSTR1    = IF_FEATURE_XARGS_SUPPORT_REPL_STR(    (1 << OPTBIT_REPLSTR1   )) + 0,
 };
Function Documentation
process_stdin()
static char* FAST_FUNC process_stdin (int n_max_chars, int n_max_arg, char * buf) static
Definition at line 399 of file xargs.c.
 {
     char *s = buf;             /* start of the word */
     char *p = s + strlen(buf); /* end of the word */
     buf += n_max_chars;        /* past buffer's end */
     while (1) {
         int c = getchar();
         if (c == EOF) {
             if (p == s)
                 goto ret;
         }
         if (c == EOF || ISSPACE(c)) {
             if (p == s)
                 continue;
             c = EOF;
         }
         *p++ = (c == EOF ? '\0' : c);
         if (c == EOF) { /* word's delimiter or EOF detected */
             /* A full word is loaded */
             if (G.eof_str) {
                 if (strcmp(s, G.eof_str) == 0) {
                     while (getchar() != EOF)
                         continue;
                     p = s;
                     goto ret;
                 }
             }
             store_param(s);
             dbg_msg("args[]:'%s'", s);
             s = p;
             n_max_arg--;
             if (n_max_arg == 0) {
                 goto ret;
             }
         }
         if (p == buf) {
             goto ret;
         }
     }
  ret:
     *p = '\0';
     /* store_param(NULL) - caller will do it */
     dbg_msg("return:'%s'", s);
     return s;
 }
References buf, c, dbg_msg, EOF, G, getchar, ISSPACE, p, s, store_param(), strcmp, and strlen().
Referenced by xargs_main().
store_param()
static void store_param (char * s) static
Definition at line 291 of file xargs.c.
 {
     /* Grow by 256 elements at once */
     if (!(G.idx & 0xff)) { /* G.idx == N*256? */
         /* Enlarge, make G.args[(N+1)*256 - 1] last valid idx */
         G.args = xrealloc(G.args, sizeof(G.args[0]) * (G.idx + 0x100));
     }
     G.args[G.idx++] = s;
 }
References G, s, and xrealloc.
Referenced by process_stdin(), and xargs_main().
xargs_exec()
static int xargs_exec (void) static
Definition at line 188 of file xargs.c.
 {
     int status;
     if (option_mask32 & OPT_STDIN_TTY)
         xdup2(G.fd_tty, STDIN_FILENO);
 #if !ENABLE_FEATURE_XARGS_SUPPORT_PARALLEL
     status = spawn_and_wait(G.args);
 #else
     if (G.max_procs == 1) {
         status = spawn_and_wait(G.args);
     } else {
         pid_t pid;
         int wstat;
  again:
         if (G.running_procs >= G.max_procs)
             pid = safe_waitpid(-1, &wstat, 0);
         else
             pid = wait_any_nohang(&wstat);
         if (pid > 0) {
             /* We may have children we don't know about:
              * sh -c 'sleep 1 & exec xargs ...'
              * Do not make G.running_procs go negative.
              */
             if (G.running_procs != 0)
                 G.running_procs--;
             status = WIFSIGNALED(wstat)
                 ? 0x180 + WTERMSIG(wstat)
                 : WEXITSTATUS(wstat);
             if (status > 0 && status < 255) {
                 /* See below why 123 does not abort */
                 G.xargs_exitcode = 123;
                 status = 0;
             }
             if (status == 0)
                 goto again; /* maybe we have more children? */
             /* else: "bad" status, will bail out */
         } else if (G.max_procs != 0) {
             /* Not in final waitpid() loop,
              * and G.running_procs < G.max_procs: start more procs
              */
             status = spawn(G.args);
             /* here "status" actually holds pid, or -1 */
             if (status > 0) {
                 G.running_procs++;
                 status = 0;
             }
             /* else: status == -1 (failed to fork or exec) */
         } else {
             /* final waitpid() loop: must be ECHILD "no more children" */
             status = 0;
         }
     }
 #endif
     /* Manpage:
      * """xargs exits with the following status:
      * 0 if it succeeds
      * 123 if any invocation of the command exited with status 1-125
      * 124 if the command exited with status 255
      *     ("""If any invocation of the command exits with a status of 255,
      *     xargs will stop immediately without reading any further input.
      *     An error message is issued on stderr when this happens.""")
      * 125 if the command is killed by a signal
      * 126 if the command cannot be run
      * 127 if the command is not found
      * 1 if some other error occurred."""
      */
     if (status < 0) {
         bb_simple_perror_msg(G.args[0]);
         status = (errno == ENOENT) ? 127 : 126;
     }
     else if (status >= 0x180) {
         bb_error_msg("'%s' terminated by signal %u",
             G.args[0], status - 0x180);
         status = 125;
     }
     else if (status != 0) {
         if (status == 255) {
             bb_error_msg("%s: exited with status 255; aborting", G.args[0]);
             status = 124;
             goto ret;
         }
         /* "123 if any invocation of the command exited with status 1-125"
          * This implies that nonzero exit code is remembered,
          * but does not cause xargs to stop: we return 0.
          */
         G.xargs_exitcode = 123;
         status = 0;
     }
  ret:
     if (status != 0)
         G.xargs_exitcode = status;
     if (option_mask32 & OPT_STDIN_TTY)
         xdup2(G.fd_stdin, STDIN_FILENO);
     return status;
 }
References bb_error_msg(), bb_simple_perror_msg(), ENOENT, errno, G, OPT_STDIN_TTY, option_mask32, pid, safe_waitpid(), spawn(), spawn_and_wait(), status, STDIN_FILENO, wait_any_nohang(), WEXITSTATUS, WIFSIGNALED, wstat, WTERMSIG, and xdup2().
Referenced by xargs_main().
xargs_main()
int xargs_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 611 of file xargs.c.
 {
     int initial_idx;
     int i;
     char *max_args;
     char *max_chars;
     char *buf;
     unsigned opt;
     int n_max_chars;
     int n_max_arg;
 #if ENABLE_FEATURE_XARGS_SUPPORT_ZERO_TERM \
  || ENABLE_FEATURE_XARGS_SUPPORT_REPL_STR
     char* FAST_FUNC (*read_args)(int, int, char*) = process_stdin;
 #else
 #define read_args process_stdin
 #endif
     IF_FEATURE_XARGS_SUPPORT_ARGS_FILE(char *opt_a = NULL;)
     INIT_G();
     opt = getopt32long(argv, OPTION_STR,
         "no-run-if-empty\0" No_argument "r",
         &max_args, &max_chars, &G.eof_str, &G.eof_str
         IF_FEATURE_XARGS_SUPPORT_REPL_STR(, &G.repl_str, &G.repl_str)
         IF_FEATURE_XARGS_SUPPORT_PARALLEL(, &G.max_procs)
         IF_FEATURE_XARGS_SUPPORT_ARGS_FILE(, &opt_a)
     );
 #if ENABLE_FEATURE_XARGS_SUPPORT_PARALLEL
     if (G.max_procs <= 0) /* -P0 means "run lots of them" */
         G.max_procs = 100; /* let's not go crazy high */
 #endif
 #if ENABLE_FEATURE_XARGS_SUPPORT_ARGS_FILE
     if (opt_a)
         xmove_fd(xopen(opt_a, O_RDONLY), 0);
 #endif
     /* -E ""? You may wonder why not just omit -E?
      * This is used for portability:
      * old xargs was using "_" as default for -E / -e */
     if ((opt & OPT_EOF_STRING1) && G.eof_str[0] == '\0')
         G.eof_str = NULL;
     if (opt & OPT_ZEROTERM) {
         IF_FEATURE_XARGS_SUPPORT_ZERO_TERM(read_args = process0_stdin;)
         IF_FEATURE_XARGS_SUPPORT_REPL_STR(G.eol_ch = '\0';)
     }
     argv += optind;
     //argc -= optind;
     if (!argv[0]) {
         /* default behavior is to echo all the filenames */
         *--argv = (char*)"echo";
         //argc++;
     }
     /*
      * The Open Group Base Specifications Issue 6:
      * "The xargs utility shall limit the command line length such that
      * when the command line is invoked, the combined argument
      * and environment lists (see the exec family of functions
      * in the System Interfaces volume of IEEE Std 1003.1-2001)
      * shall not exceed {ARG_MAX}-2048 bytes".
      */
     n_max_chars = bb_arg_max();
     if (n_max_chars > 32 * 1024)
         n_max_chars = 32 * 1024;
     /*
      * POSIX suggests substracting 2048 bytes from sysconf(_SC_ARG_MAX)
      * so that the process may safely modify its environment.
      */
     n_max_chars -= 2048;
     if (opt & OPT_UPTO_SIZE) {
         n_max_chars = xatou_range(max_chars, 1, INT_MAX);
     }
     /* Account for prepended fixed arguments */
     {
         size_t n_chars = 0;
         for (i = 0; argv[i]; i++) {
             n_chars += strlen(argv[i]) + 1;
         }
         n_max_chars -= n_chars;
     }
     /* Sanity check */
     if (n_max_chars <= 0) {
         bb_simple_error_msg_and_die("can't fit single argument within argument list size limit");
     }
     buf = xzalloc(n_max_chars + 1);
     n_max_arg = n_max_chars;
     if (opt & OPT_UPTO_NUMBER) {
         n_max_arg = xatou_range(max_args, 1, INT_MAX);
         /* Not necessary, we use growable args[]: */
         /* if (n_max_arg > n_max_chars) n_max_arg = n_max_chars */
     }
 #if ENABLE_FEATURE_XARGS_SUPPORT_REPL_STR
     if (opt & (OPT_REPLSTR | OPT_REPLSTR1)) {
         /*
          * -I<str>:
          * Unmodified args are kept in G.argv[i],
          * G.args[i] receives malloced G.argv[i] with <str> replaced
          * with input line. Setting this up:
          */
         G.args = NULL;
         G.argv = argv;
         read_args = process_stdin_with_replace;
         /* Make -I imply -r. GNU findutils seems to do the same: */
         /* (otherwise "echo -n | xargs -I% echo %" would SEGV) */
         opt |= OPT_NO_EMPTY;
     } else
 #endif
     {
         /* Store the command to be executed, part 1.
          * We can statically allocate (argc + n_max_arg + 1) elements
          * and do not bother with resizing args[], but on 64-bit machines
          * this results in args[] vector which is ~8 times bigger
          * than n_max_chars! That is, with n_max_chars == 20k,
          * args[] will take 160k (!), which will most likely be
          * almost entirely unused.
          */
         for (i = 0; argv[i]; i++)
             store_param(argv[i]);
     }
     if (opt & OPT_STDIN_TTY) {
         G.fd_tty = xopen(CURRENT_TTY, O_RDONLY);
         close_on_exec_on(G.fd_tty);
         G.fd_stdin = dup(STDIN_FILENO);
         close_on_exec_on(G.fd_stdin);
     }
     initial_idx = G.idx;
     while (1) {
         char *rem;
         G.idx = initial_idx;
         rem = read_args(n_max_chars, n_max_arg, buf);
         store_param(NULL);
         if (!G.args[initial_idx]) { /* not even one ARG was added? */
             if (*rem != '\0')
                 bb_simple_error_msg_and_die("argument line too long");
             if (opt & OPT_NO_EMPTY)
                 break;
         }
         opt |= OPT_NO_EMPTY;
         if (opt & (OPT_INTERACTIVE | OPT_VERBOSE)) {
             const char *fmt = " %s" + 1;
             char **args = G.args;
             for (i = 0; args[i]; i++) {
                 fprintf(stderr, fmt, args[i]);
                 fmt = " %s";
             }
             if (!(opt & OPT_INTERACTIVE))
                 bb_putchar_stderr('\n');
         }
         if (!(opt & OPT_INTERACTIVE) || xargs_ask_confirmation()) {
             if (xargs_exec() != 0)
                 break; /* G.xargs_exitcode is set by xargs_exec() */
         }
         overlapping_strcpy(buf, rem);
     } /* while */
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(G.args);
         free(buf);
     }
 #if ENABLE_FEATURE_XARGS_SUPPORT_PARALLEL
     G.max_procs = 0;
     xargs_exec(); /* final waitpid() loop */
 #endif
     return G.xargs_exitcode;
 }
References argv, bb_arg_max(), bb_putchar_stderr(), bb_simple_error_msg_and_die(), buf, close_on_exec_on(), CURRENT_TTY, dup(), FAST_FUNC, fprintf(), free, G, getopt32long, i, INIT_G, INT_MAX, No_argument, NULL, O_RDONLY, opt, OPT_EOF_STRING1, OPT_INTERACTIVE, OPT_NO_EMPTY, OPT_REPLSTR, OPT_REPLSTR1, OPT_STDIN_TTY, OPT_UPTO_NUMBER, OPT_UPTO_SIZE, OPT_VERBOSE, OPT_ZEROTERM, optind, OPTION_STR, overlapping_strcpy(), process_stdin(), read_args, stderr, STDIN_FILENO, store_param(), strlen(), xargs_ask_confirmation, xargs_exec(), xmove_fd(), xopen(), and xzalloc().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING