Fennix Lynx Bootloader: Memory32::Physical Class Reference
Memory32::Physical Class Reference
#include <memory.hpp>
Public Member Functions
void LockPage (void *Address)
void LockPages (void *Address, size_t PageCount)
void ReservePage (void *Address)
void ReservePages (void *Address, size_t PageCount)
void UnreservePage (void *Address)
void UnreservePages (void *Address, size_t PageCount)
void * RequestPage ()
void * RequestPages (size_t Count)
void FreePage (void *Address)
void FreePages (void *Address, size_t Count)
void Init (BootInfo *Info)
Physical ()
~Physical ()
Data Fields
uint64_t TotalMemory = 0
uint64_t FreeMemory = 0
uint64_t ReservedMemory = 0
uint64_t UsedMemory = 0
Private Attributes
uint64_t PageBitmapIndex = 0
Bitmap PageBitmap
Detailed Description
Definition at line 178 of file memory.hpp.
Constructor & Destructor Documentation
Physical()
Memory32::Physical::Physical ()
Definition at line 290 of file PhysicalMemoryManager.cpp.
 {}
~Physical()
Memory32::Physical::~Physical ()
Definition at line 291 of file PhysicalMemoryManager.cpp.
 {}
Member Function Documentation
FreePage()
void Memory32::Physical::FreePage (void * Address)
Definition at line 54 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
         {
             warn("Null pointer passed to FreePage.");
             return;
         }
         size_t Index = (size_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == false))
         {
             warn("Tried to free an already free page. (%p)", Address);
             return;
         }
         if (PageBitmap.Set(Index, false))
         {
             FreeMemory += PAGE_SIZE;
             UsedMemory -= PAGE_SIZE;
             if (PageBitmapIndex > Index)
                 PageBitmapIndex = Index;
         }
     }
References FreeMemory, PAGE_SIZE, PageBitmap, PageBitmapIndex, Bitmap::Set(), unlikely, UsedMemory, and warn.
Referenced by FreePages().
FreePages()
void Memory32::Physical::FreePages (void * Address, size_t Count)
Definition at line 79 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || Count == 0))
         {
             warn("%s%s%s passed to FreePages.", Address == nullptr ? "Null pointer " : "", Address == nullptr && Count == 0 ? "and " : "", Count == 0 ? "Zero count" : "");
             return;
         }
         for (size_t t = 0; t < Count; t++)
             this->FreePage((void *)((uintptr_t)Address + (t * PAGE_SIZE)));
     }
References FreePage(), PAGE_SIZE, unlikely, and warn.
Init()
void Memory32::Physical::Init (BootInfo * Info)
Definition at line 194 of file PhysicalMemoryManager.cpp.
     {
         uint64_t MemorySize = Info->Memory.Size;
         debug("Memory size: %lld bytes (%ld pages)", MemorySize, TO_PAGES(MemorySize));
         UsedMemory = 0;
         ReservedMemory = 0;
         TotalMemory = MemorySize;
         FreeMemory = MemorySize;
         void *LargestFreeMemorySegment = nullptr;
         uint64_t LargestFreeMemorySegmentSize = 0;
         for (uint64_t i = 0; i < Info->Memory.Entries; i++)
         {
             if (Info->Memory.Entry[i].Type == Usable)
             {
                 if (Info->Memory.Entry[i].Length > LargestFreeMemorySegmentSize)
                 {
                     /* We don't want to use 0 as a memory address. */
                     if (Info->Memory.Entry[i].BaseAddress == 0x0)
                         continue;
                     LargestFreeMemorySegment = (void *)Info->Memory.Entry[i].BaseAddress;
                     LargestFreeMemorySegmentSize = Info->Memory.Entry[i].Length;
                     debug("Largest free memory segment: %llp (%lldMB)",
                           (void *)Info->Memory.Entry[i].BaseAddress,
                           TO_MB(Info->Memory.Entry[i].Length));
                 }
             }
         }
         if (LargestFreeMemorySegment == nullptr)
         {
             error("No free memory found!");
             while (1)
                 asmv("cli; hlt");
         }
         size_t BitmapSize = (MemorySize / PAGE_SIZE) / 8 + 1;
         void *LargestFreeMemorySegmentNoKernel = nullptr;
         if ((uintptr_t)LargestFreeMemorySegment >= (uintptr_t)&_kernel_start &&
             (uintptr_t)LargestFreeMemorySegment <= (uintptr_t)&_kernel_end)
         {
             LargestFreeMemorySegmentNoKernel = (void *)((uintptr_t)LargestFreeMemorySegment + (uintptr_t)&_kernel_end);
             if ((uintptr_t)LargestFreeMemorySegmentNoKernel > ((uintptr_t)LargestFreeMemorySegment + LargestFreeMemorySegmentSize))
             {
                 error("No free memory found!");
                 while (1)
                     asmv("cli; hlt");
             }
         }
         else
         {
             LargestFreeMemorySegmentNoKernel = LargestFreeMemorySegment;
         }
         debug("Initializing Bitmap at %llp-%llp (%lld Bytes)",
               LargestFreeMemorySegmentNoKernel,
               (void *)((uintptr_t)LargestFreeMemorySegmentNoKernel + BitmapSize),
               BitmapSize);
         PageBitmap.Size = BitmapSize;
         PageBitmap.Buffer = (uint8_t *)LargestFreeMemorySegmentNoKernel;
         for (size_t i = 0; i < BitmapSize; i++)
             *(uint8_t *)(PageBitmap.Buffer + i) = 0;
         debug("Reserving pages...");
         this->ReservePages(0, TO_PAGES(Info->Memory.Size));
         debug("Unreserving usable pages...");
         for (uint64_t i = 0; i < Info->Memory.Entries; i++)
         {
             if (Info->Memory.Entry[i].Type == Usable)
                 this->UnreservePages(Info->Memory.Entry[i].BaseAddress, TO_PAGES(Info->Memory.Entry[i].Length));
         }
         debug("Reserving bitmap pages...");
         this->ReservePages(PageBitmap.Buffer, TO_PAGES(PageBitmap.Size));
         debug("Reserving kernel...");
         this->ReservePages(&_kernel_start, TO_PAGES((uintptr_t)&_kernel_end - (uintptr_t)&_kernel_start));
         debug("Reserving kernel and its modules...");
         BootInfo::ModuleInfo *Module = &Info->Modules[0];
         int ModuleIndex = 0;
         do
         {
             debug("Reserving %s (%p-%p)", Module->CommandLine, Module->Address, (void *)((uintptr_t)Module->Address + Module->Size));
             this->ReservePages(Module->Address, TO_PAGES(Module->Size));
             Module = &Info->Modules[++ModuleIndex];
         } while (Module->Address);
         this->ReservePages(0, 16);
     }
References _kernel_end, _kernel_start, BootInfo::ModuleInfo::Address, asmv, BootInfo::MemoryInfo::MemoryEntryInfo::BaseAddress, Bitmap::Buffer, BootInfo::ModuleInfo::CommandLine, debug, BootInfo::MemoryInfo::Entries, BootInfo::MemoryInfo::Entry, error, FreeMemory, BootInfo::MemoryInfo::MemoryEntryInfo::Length, BootInfo::Memory, BootInfo::Modules, PAGE_SIZE, PageBitmap, ReservedMemory, ReservePages(), BootInfo::MemoryInfo::Size, BootInfo::ModuleInfo::Size, Bitmap::Size, TO_MB, TO_PAGES, TotalMemory, BootInfo::MemoryInfo::MemoryEntryInfo::Type, UnreservePages(), Usable, and UsedMemory.
Referenced by InitializeMemoryManagement().
LockPage()
void Memory32::Physical::LockPage (void * Address)
Definition at line 90 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to lock null address.");
         uintptr_t Index = (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == true))
             return;
         if (PageBitmap.Set(Index, true))
         {
             FreeMemory -= PAGE_SIZE;
             UsedMemory += PAGE_SIZE;
         }
     }
References FreeMemory, PAGE_SIZE, PageBitmap, Bitmap::Set(), unlikely, UsedMemory, and warn.
Referenced by LockPages(), and RequestPage().
LockPages()
void Memory32::Physical::LockPages (void * Address, size_t PageCount)
Definition at line 107 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to lock %s%s.", Address ? "null address" : "", PageCount ? "0 pages" : "");
         for (size_t i = 0; i < PageCount; i++)
             this->LockPage((void *)((uintptr_t)Address + (i * PAGE_SIZE)));
     }
References LockPage(), PAGE_SIZE, unlikely, and warn.
Referenced by RequestPages().
RequestPage()
void * Memory32::Physical::RequestPage ()
Definition at line 4 of file PhysicalMemoryManager.cpp.
     {
         for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
         {
             if (PageBitmap[PageBitmapIndex] == true)
                 continue;
             this->LockPage((void *)(PageBitmapIndex * PAGE_SIZE));
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         error("Out of memory! (Free: %ldMB; Used: %ldMB; Reserved: %ldMB)", TO_MB(FreeMemory), TO_MB(UsedMemory), TO_MB(ReservedMemory));
         while (1)
             asmv("cli; hlt");
         __builtin_unreachable();
     }
References asmv, error, FreeMemory, LockPage(), PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Size, TO_MB, and UsedMemory.
Referenced by LoadElfInMemory().
RequestPages()
void * Memory32::Physical::RequestPages (size_t Count)
Definition at line 21 of file PhysicalMemoryManager.cpp.
     {
         for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
         {
             if (PageBitmap[PageBitmapIndex] == true)
                 continue;
             for (uint64_t Index = PageBitmapIndex; Index < PageBitmap.Size * 8; Index++)
             {
                 if (PageBitmap[Index] == true)
                     continue;
                 for (size_t i = 0; i < Count; i++)
                 {
                     if (PageBitmap[Index + i] == true)
                         goto NextPage;
                 }
                 this->LockPages((void *)(Index * PAGE_SIZE), Count);
                 return (void *)(Index * PAGE_SIZE);
             NextPage:
                 Index += Count;
                 continue;
             }
         }
         error("Out of memory! (Free: %ldMB; Used: %ldMB; Reserved: %ldMB)", TO_MB(FreeMemory), TO_MB(UsedMemory), TO_MB(ReservedMemory));
         while (1)
             asmv("cli; hlt");
         __builtin_unreachable();
     }
References asmv, error, FreeMemory, LockPages(), PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Size, TO_MB, and UsedMemory.
Referenced by __cxa_allocate_exception(), InitializeMemoryManagement(), LoadElfInMemory(), and Memory32::Virtual::Map().
ReservePage()
void Memory32::Physical::ReservePage (void * Address)
Definition at line 116 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to reserve null address.");
         uintptr_t Index = (Address == NULL) ? 0 : (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == true))
             return;
         if (PageBitmap.Set(Index, true))
         {
             FreeMemory -= PAGE_SIZE;
             ReservedMemory += PAGE_SIZE;
         }
     }
References FreeMemory, NULL, PAGE_SIZE, PageBitmap, ReservedMemory, Bitmap::Set(), unlikely, and warn.
ReservePages()
void Memory32::Physical::ReservePages (void * Address, size_t PageCount)
Definition at line 133 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to reserve %s%s.", Address ? "null address" : "", PageCount ? "0 pages" : "");
         for (size_t t = 0; t < PageCount; t++)
         {
             uintptr_t Index = ((uintptr_t)Address + (t * PAGE_SIZE)) / PAGE_SIZE;
             if (unlikely(PageBitmap[Index] == true))
                 return;
             if (PageBitmap.Set(Index, true))
             {
                 FreeMemory -= PAGE_SIZE;
                 ReservedMemory += PAGE_SIZE;
             }
         }
     }
References FreeMemory, PAGE_SIZE, PageBitmap, ReservedMemory, Bitmap::Set(), unlikely, and warn.
Referenced by Init().
UnreservePage()
void Memory32::Physical::UnreservePage (void * Address)
Definition at line 153 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to unreserve null address.");
         uintptr_t Index = (Address == NULL) ? 0 : (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == false))
             return;
         if (PageBitmap.Set(Index, false))
         {
             FreeMemory += PAGE_SIZE;
             ReservedMemory -= PAGE_SIZE;
             if (PageBitmapIndex > Index)
                 PageBitmapIndex = Index;
         }
     }
References FreeMemory, NULL, PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Set(), unlikely, and warn.
UnreservePages()
void Memory32::Physical::UnreservePages (void * Address, size_t PageCount)
Definition at line 172 of file PhysicalMemoryManager.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to unreserve %s%s.", Address ? "null address" : "", PageCount ? "0 pages" : "");
         for (size_t t = 0; t < PageCount; t++)
         {
             uintptr_t Index = ((uintptr_t)Address + (t * PAGE_SIZE)) / PAGE_SIZE;
             if (unlikely(PageBitmap[Index] == false))
                 return;
             if (PageBitmap.Set(Index, false))
             {
                 FreeMemory += PAGE_SIZE;
                 ReservedMemory -= PAGE_SIZE;
                 if (PageBitmapIndex > Index)
                     PageBitmapIndex = Index;
             }
         }
     }
References FreeMemory, PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Set(), unlikely, and warn.
Referenced by Init().
Field Documentation
FreeMemory
uint64_t Memory32::Physical::FreeMemory = 0
Definition at line 186 of file memory.hpp.
Referenced by FreePage(), Init(), LockPage(), RequestPage(), RequestPages(), ReservePage(), ReservePages(), UnreservePage(), and UnreservePages().
PageBitmap
Bitmap Memory32::Physical::PageBitmap private
Definition at line 182 of file memory.hpp.
Referenced by FreePage(), Init(), LockPage(), RequestPage(), RequestPages(), ReservePage(), ReservePages(), UnreservePage(), and UnreservePages().
PageBitmapIndex
uint64_t Memory32::Physical::PageBitmapIndex = 0 private
Definition at line 181 of file memory.hpp.
Referenced by FreePage(), RequestPage(), RequestPages(), UnreservePage(), and UnreservePages().
ReservedMemory
uint64_t Memory32::Physical::ReservedMemory = 0
Definition at line 187 of file memory.hpp.
Referenced by Init(), InitializeMemoryManagement(), LoadElfInMemory(), RequestPage(), RequestPages(), ReservePage(), ReservePages(), UnreservePage(), and UnreservePages().
TotalMemory
uint64_t Memory32::Physical::TotalMemory = 0
Definition at line 185 of file memory.hpp.
Referenced by Init(), InitializeMemoryManagement(), and LoadElfInMemory().
UsedMemory
uint64_t Memory32::Physical::UsedMemory = 0
Definition at line 188 of file memory.hpp.
Referenced by FreePage(), Init(), InitializeMemoryManagement(), LoadElfInMemory(), LockPage(), RequestPage(), and RequestPages().
The documentation for this class was generated from the following files:
Lynx/FennixLoader/include/memory.hpp
Lynx/FennixLoader/Memory/PhysicalMemoryManager.cpp