Fennix Userspace: Userspace/mlibc/tests/posix/vfork.c File Reference
vfork.c File Reference
#include <assert.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>
Functions
void prevent_atforks (void)
int main ()
Function Documentation
main()
int main (void)
Definition at line 12 of file vfork.c.
            {
     pid_t pid;
     int status;
     assert(!pthread_atfork(prevent_atforks, NULL, NULL));
     switch (pid = vfork()) {
     case -1:
         perror("vfork");
         abort();
     case 0:
         _exit(12);
     default: break;
     }
     assert(wait(&status) == pid);
     assert(WIFEXITED(status) && WEXITSTATUS(status) == 12);
 }
References _exit(), abort(), assert, NULL, perror(), prevent_atforks(), pthread_atfork(), mlibc::status, vfork(), wait(), WEXITSTATUS, and WIFEXITED.
prevent_atforks()
void prevent_atforks (void)
Definition at line 8 of file vfork.c.
{
     exit(1);
 }
References exit().
Referenced by main().