Fennix Kernel: Kernel/KThread.cpp File Reference
KThread.cpp File Reference
#include "kernel.h"
#include <filesystem/ustar.hpp>
#include <vector.hpp>
#include <power.hpp>
#include <lock.hpp>
#include <printf.h>
#include <exec.hpp>
#include <cwalk.h>
#include <stb/image.h>
#include "DAPI.hpp"
#include "Fex.hpp"
Macros
#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_STDIO
#define STBI_NO_LINEAR
#define STBI_NO_THREAD_LOCALS
#define STBI_NO_HDR
#define STBI_ONLY_TGA
Functions
NewLock (ShutdownLock)
Execute::SpawnData SpawnInit ()
void BootLogoAnimationThread ()
void ExitLogoAnimationThread ()
void CleanupProcessesThreadWrapper ()
void KernelMainThread ()
void __no_stack_protector KernelShutdownThread (bool Reboot)
void KST_Reboot ()
void KST_Shutdown ()
Variables
Driver::Driver * DriverManager = nullptr
Disk::Manager * DiskManager = nullptr
NetworkInterfaceManager::NetworkInterface * NIManager = nullptr
Recovery::KernelRecovery * RecoveryScreen = nullptr
VirtualFileSystem::Node * DevFS = nullptr
VirtualFileSystem::Node * MntFS = nullptr
VirtualFileSystem::Node * ProcFS = nullptr
void * Frames [41]
uint32_t FrameSizes [41]
uint32_t FrameCount = 1
Macro Definition Documentation
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 11 of file KThread.cpp.
STBI_NO_HDR
#define STBI_NO_HDR
Definition at line 15 of file KThread.cpp.
STBI_NO_LINEAR
#define STBI_NO_LINEAR
Definition at line 13 of file KThread.cpp.
STBI_NO_STDIO
#define STBI_NO_STDIO
Definition at line 12 of file KThread.cpp.
STBI_NO_THREAD_LOCALS
#define STBI_NO_THREAD_LOCALS
Definition at line 14 of file KThread.cpp.
STBI_ONLY_TGA
#define STBI_ONLY_TGA
Definition at line 16 of file KThread.cpp.
Function Documentation
BootLogoAnimationThread()
void BootLogoAnimationThread ()
Definition at line 150 of file KThread.cpp.
 {
     char BootAnimPath[16];
     while (FrameCount < 41)
     {
         sprintf(BootAnimPath, "%d.tga", FrameCount);
         std::shared_ptr<File> ba = bootanim_vfs->Open(BootAnimPath);
         if (ba->Status != FileStatus::OK)
         {
             bootanim_vfs->Close(ba);
             debug("Failed to load boot animation frame %s", BootAnimPath);
             break;
         }
         FrameSizes[FrameCount] = s_cst(uint32_t, ba->node->Length);
         Frames[FrameCount] = new uint8_t[ba->node->Length];
         memcpy((void *)Frames[FrameCount], (void *)ba->node->Address, ba->node->Length);
         bootanim_vfs->Close(ba);
         FrameCount++;
     }
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = 1; i < FrameCount; i++)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i], &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i], FrameSizes[i], &x, &y, &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY, (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
     }
 }
References bootanim_vfs, VirtualFileSystem::Virtual::Close(), debug, Display, FrameCount, Frames, FrameSizes, free(), memcpy(), NULL, OK, VirtualFileSystem::Virtual::Open(), sprintf(), stbi_info_from_memory(), stbi_load_from_memory(), and STBI_rgb_alpha.
Referenced by KernelMainThread().
CleanupProcessesThreadWrapper()
void CleanupProcessesThreadWrapper ()
Definition at line 275 of file KThread.cpp.
 { TaskManager->CleanupProcessesThread(); }
References Tasking::Task::CleanupProcessesThread(), and TaskManager.
Referenced by KernelMainThread().
ExitLogoAnimationThread()
void ExitLogoAnimationThread ()
Definition at line 220 of file KThread.cpp.
 {
     Display->SetBrightness(100, 1);
     Display->SetBuffer(1);
     /* Files: 26.tga 25.tga ... 1.tga */
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = 40; i > 25; i--)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i], &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i], FrameSizes[i], &x, &y, &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY, (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
     }
 }
References Display, Frames, FrameSizes, free(), NULL, stbi_info_from_memory(), stbi_load_from_memory(), and STBI_rgb_alpha.
Referenced by KernelShutdownThread().
KernelMainThread()
void KernelMainThread ()
Definition at line 277 of file KThread.cpp.
 {
     Tasking::TCB *clnThd = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (Tasking::IP)CleanupProcessesThreadWrapper);
     clnThd->SetPriority(Tasking::Idle);
     TaskManager->SetCleanupThread(clnThd);
     TaskManager->GetCurrentThread()->SetPriority(Tasking::Critical);
     Tasking::TCB *blaThread = nullptr;
     if (Config.BootAnimation)
     {
         blaThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (Tasking::IP)BootLogoAnimationThread);
         blaThread->Rename("Logo Animation");
     }
 #ifdef DEBUG
     /* TODO: This should not be enabled because it may cause a deadlock. Not sure where or how. */
     // Tasking::PCB *tskMgr = TaskManager->CreateProcess(TaskManager->GetCurrentProcess(), "Debug Task Manager", Tasking::TaskTrustLevel::Kernel);
     // TaskManager->CreateThread(tskMgr, (Tasking::IP)TaskMgr)->SetPriority(Tasking::High);
     TreeFS(vfs->GetRootNode(), 0);
 #endif
     KPrint("Kernel Compiled at: %s %s with C++ Standard: %d", __DATE__, __TIME__, CPP_LANGUAGE_STANDARD);
     KPrint("C++ Language Version (__cplusplus): %ld", __cplusplus);
     KPrint("Initializing Disk Manager...");
     DiskManager = new Disk::Manager;
     KPrint("Loading Drivers...");
     DriverManager = new Driver::Driver;
     KPrint("Fetching Disks...");
     if (DriverManager->GetDrivers().size() > 0)
     {
         foreach (auto Driver in DriverManager->GetDrivers())
             if (((FexExtended *)((uintptr_t)Driver.Address + EXTENDED_SECTION_ADDRESS))->Driver.Type == FexDriverType::FexDriverType_Storage)
                 DiskManager->FetchDisks(Driver.DriverUID);
     }
     else
         KPrint("\eE85230No disk drivers found! Cannot fetch disks!");
     KPrint("Initializing Network Interface Manager...");
     NIManager = new NetworkInterfaceManager::NetworkInterface;
     KPrint("Starting Network Interface Manager...");
     NIManager->StartService();
     Time::Clock tm = Time::ReadClock();
     printf("\eCCCCCC[\e00AEFF%02d:%02d:%02d\eCCCCCC] ", tm.Hour, tm.Minute, tm.Second);
     const char *USpace_msg = "Setting up userspace";
     for (size_t i = 0; i < strlen(USpace_msg); i++)
         Display->Print(USpace_msg[i], 0);
     if (!Config.BootAnimation)
         Display->SetBuffer(0);
     Execute::SpawnData ret = {Execute::ExStatus::Unknown, nullptr, nullptr};
     Tasking::TCB *ExecuteThread = nullptr;
     int ExitCode = -1;
     ExecuteThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (Tasking::IP)Execute::StartExecuteService);
     ExecuteThread->Rename("Library Manager");
     ExecuteThread->SetCritical(true);
     ExecuteThread->SetPriority(Tasking::Idle);
     Display->Print('.', 0);
     if (!Config.BootAnimation)
         Display->SetBuffer(0);
     ret = SpawnInit();
     Display->Print('.', 0);
     if (!Config.BootAnimation)
         Display->SetBuffer(0);
     if (ret.Status != Execute::ExStatus::OK)
     {
         KPrint("\eE85230Failed to start %s! Code: %d", Config.InitPath, ret.Status);
         goto Exit;
     }
     ret.Thread->SetCritical(true);
     TaskManager->GetSecurityManager()->TrustToken(ret.Process->Security.UniqueToken, Tasking::TTL::FullTrust);
     TaskManager->GetSecurityManager()->TrustToken(ret.Thread->Security.UniqueToken, Tasking::TTL::FullTrust);
     Display->Print('.', 0);
     Display->Print('\n', 0);
     if (!Config.BootAnimation)
         Display->SetBuffer(0);
     KPrint("Waiting for \e22AAFF%s\eCCCCCC to start...", Config.InitPath);
     TaskManager->GetCurrentThread()->SetPriority(Tasking::Idle);
     TaskManager->WaitForThread(ret.Thread);
     ExitCode = ret.Thread->GetExitCode();
 Exit:
     if (ExitCode != 0)
     {
         KPrint("\eE85230Userspace process exited with code %d", ExitCode);
         KPrint("Dropping to recovery screen...");
         TaskManager->Sleep(2500);
         TaskManager->WaitForThread(blaThread);
         RecoveryScreen = new Recovery::KernelRecovery;
     }
     else
     {
         KPrint("\eFF7900%s process exited with code %d and it didn't invoked the shutdown function.",
                Config.InitPath, ExitCode);
         KPrint("System Halted");
     }
     CPU::Halt(true);
 }
References KernelConfig::BootAnimation, BootLogoAnimationThread(), CleanupProcessesThreadWrapper(), Config, Tasking::Task::CreateThread(), Tasking::Critical, DiskManager, Display, Driver, DriverManager, EXTENDED_SECTION_ADDRESS, Disk::Manager::FetchDisks(), FexDriverType_Storage, Tasking::FullTrust, Tasking::Task::GetCurrentProcess(), Tasking::Task::GetCurrentThread(), Driver::Driver::GetDrivers(), Tasking::TCB::GetExitCode(), VirtualFileSystem::Virtual::GetRootNode(), Tasking::Task::GetSecurityManager(), CPU::Halt(), Time::Clock::Hour, Tasking::Idle, KernelConfig::InitPath, KPrint(), Time::Clock::Minute, NIManager, OK, printf, Execute::SpawnData::Process, Time::ReadClock(), RecoveryScreen, Tasking::TCB::Rename(), Time::Clock::Second, Tasking::TCB::Security, Tasking::PCB::Security, Tasking::Task::SetCleanupThread(), Tasking::TCB::SetCritical(), Tasking::TCB::SetPriority(), Tasking::Task::Sleep(), SpawnInit(), Execute::StartExecuteService(), NetworkInterfaceManager::NetworkInterface::StartService(), Execute::SpawnData::Status, strlen(), TaskManager, Execute::SpawnData::Thread, Tasking::Security::TrustToken(), Tasking::TaskSecurity::UniqueToken, Unknown, vfs, and Tasking::Task::WaitForThread().
Referenced by Main().
KernelShutdownThread()
void __no_stack_protector KernelShutdownThread (bool Reboot)
Definition at line 387 of file KThread.cpp.
 {
     SmartLock(ShutdownLock);
     debug("KernelShutdownThread(%s)", Reboot ? "true" : "false");
     if (Config.BootAnimation && TaskManager)
     {
         if (RecoveryScreen)
             delete RecoveryScreen, RecoveryScreen = nullptr;
         Tasking::TCB *elaThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (Tasking::IP)ExitLogoAnimationThread);
         elaThread->Rename("Logo Animation");
         TaskManager->WaitForThread(elaThread);
     }
     BeforeShutdown(Reboot);
     trace("%s...", Reboot ? "Rebooting" : "Shutting down");
     if (Reboot)
         PowerManager->Reboot();
     else
         PowerManager->Shutdown();
     CPU::Stop();
 }
References BeforeShutdown(), KernelConfig::BootAnimation, Config, Tasking::Task::CreateThread(), debug, ExitLogoAnimationThread(), Tasking::Task::GetCurrentProcess(), PowerManager, Power::Power::Reboot(), RecoveryScreen, Tasking::TCB::Rename(), Power::Power::Shutdown(), CPU::Stop(), TaskManager, trace, and Tasking::Task::WaitForThread().
Referenced by KST_Reboot(), KST_Shutdown(), and ACPI::DSDT::OnInterruptReceived().
KST_Reboot()
void KST_Reboot ()
Definition at line 411 of file KThread.cpp.
 { KernelShutdownThread(true); }
References KernelShutdownThread().
Referenced by Recovery::RebootCommandThread().
KST_Shutdown()
void KST_Shutdown ()
Definition at line 412 of file KThread.cpp.
 { KernelShutdownThread(false); }
References KernelShutdownThread().
Referenced by ACPI::DSDT::OnInterruptReceived(), and Recovery::ShutdownCommandThread().
NewLock()
NewLock (ShutdownLock)
SpawnInit()
Execute::SpawnData SpawnInit ()
Definition at line 123 of file KThread.cpp.
 {
     const char *envp[9] = {
         "PATH=/system:/system/bin",
         "TERM=tty",
         "HOME=/",
         "USER=root",
         "SHELL=/system/sh",
         "PWD=/",
         "LANG=en_US.UTF-8",
         "TZ=UTC",
         nullptr};
     const char *argv[4] = {
         Config.InitPath,
         "--init",
         "--critical",
         nullptr};
     return Execute::Spawn(Config.InitPath, argv, envp);
 }
References Config, KernelConfig::InitPath, and Execute::Spawn().
Referenced by KernelMainThread().
Variable Documentation
DevFS
VirtualFileSystem::Node* DevFS = nullptr
Definition at line 31 of file KThread.cpp.
Referenced by Main().
DiskManager
Disk::Manager* DiskManager = nullptr
Definition at line 28 of file KThread.cpp.
Referenced by BeforeShutdown(), and KernelMainThread().
DriverManager
Driver::Driver* DriverManager = nullptr
Definition at line 27 of file KThread.cpp.
Referenced by BeforeShutdown(), Recovery::ChangeSampleRate(), Recovery::ChangeVolume(), Disk::Manager::FetchDisks(), GraphicalUserInterface::GUI::FetchInputs(), NetworkInterfaceManager::NetworkInterface::FetchNetworkCards(), CrashHandler::Handle(), KernelMainThread(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), Driver::Driver::Panic(), Recovery::PlayAudio(), NetworkInterfaceManager::NetworkInterface::Send(), and Driver::Driver::UnloadAllDrivers().
FrameCount
uint32_t FrameCount = 1
Definition at line 148 of file KThread.cpp.
Referenced by BootLogoAnimationThread().
Frames
void* Frames[41]
Definition at line 146 of file KThread.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
FrameSizes
uint32_t FrameSizes[41]
Definition at line 147 of file KThread.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
MntFS
VirtualFileSystem::Node* MntFS = nullptr
Definition at line 32 of file KThread.cpp.
Referenced by Main().
NIManager
NetworkInterfaceManager::NetworkInterface* NIManager = nullptr
Definition at line 29 of file KThread.cpp.
Referenced by BeforeShutdown(), NetworkInterfaceManager::CallStartNetworkStackWrapper(), DriverNetReceive(), DriverNetSend(), NetworkInterfaceManager::NetworkInterface::DrvReceive(), NetworkInterfaceManager::NetworkInterface::DrvSend(), KernelMainThread(), NetworkIPv4::IPv4::OnEthernetPacketReceived(), NetworkICMPv4::ICMPv4::Receive(), and NetworkEthernet::Ethernet::Send().
ProcFS
VirtualFileSystem::Node* ProcFS = nullptr
Definition at line 33 of file KThread.cpp.
Referenced by Tasking::Task::CreateProcess(), and Main().
RecoveryScreen
Recovery::KernelRecovery* RecoveryScreen = nullptr
Definition at line 30 of file KThread.cpp.
Referenced by BeforeShutdown(), KernelMainThread(), KernelShutdownThread(), and Recovery::RecoveryThreadWrapper().