Fennix: Xalloc::V2 Class Reference
Xalloc::V2 Class Reference
#include <Xalloc.hpp>
Data Structures
class Block
Public Member Functions
void Arrange ()
void * malloc (Xsize_t Size)
void free (void *Address)
void * calloc (Xsize_t NumberOfBlocks, Xsize_t Size)
void * realloc (void *Address, Xsize_t Size)
V2 (void *VirtualBase)
~V2 ()
Private Member Functions
class Xalloc::V2::Block __attribute__ ((packed, aligned((16))))
Xuint8_t * AllocateHeap (Xsize_t Size)
void FreeHeap (Xuint8_t *At, Xsize_t Size)
Xsize_t Align (Xsize_t Size)
void * FindFreeBlock (Xsize_t Size, Block *&CurrentBlock)
Private Attributes
Xuintptr_t BaseVirtualAddress = 0x0
Xsize_t HeapSize = 0x0
Xsize_t HeapUsed = 0x0
Block * FirstBlock = nullptr
Friends
class Block
Detailed Description
Definition at line 125 of file Xalloc.hpp.
Constructor & Destructor Documentation
V2()
Xalloc::V2::V2 (void * VirtualBase)
Construct a new Allocator object
Parameters
VirtualBase Virtual address to map the pages.
Definition at line 261 of file XallocV2.cpp.
     {
         if (VirtualBase == 0x0 && Xalloc_MapPages)
         {
             Xalloc_err("VirtualBase is 0x0 and Xalloc_MapPages is true!");
             while (true)
                 ;
         }
         XallocV2_lock;
         this->BaseVirtualAddress = Xuintptr_t(VirtualBase);
         XallocV2_unlock;
     }
References BaseVirtualAddress, Xalloc_err, Xalloc_MapPages, XallocV2_lock, and XallocV2_unlock.
~V2()
Xalloc::V2::~V2 ()
Destroy the Allocator object
Definition at line 275 of file XallocV2.cpp.
     {
         XallocV2_lock;
         Xalloc_trace("Destructor not implemented yet.");
         XallocV2_unlock;
     }
References Xalloc_trace, XallocV2_lock, and XallocV2_unlock.
Member Function Documentation
__attribute__()
class Xalloc::V2::Block Xalloc::V2::__attribute__ ((packed, aligned((16)))) private
Align()
Xsize_t Xalloc::V2::Align (Xsize_t Size) private
Definition at line 129 of file XallocV2.cpp.
     {
         return (Size + 0xF) & ~0xF;
     }
References Size.
Referenced by AllocateHeap().
AllocateHeap()
Xuint8_t * Xalloc::V2::AllocateHeap (Xsize_t Size) private
Definition at line 81 of file XallocV2.cpp.
     {
         Size = this->Align(Size);
         Xsize_t Pages = XStoP(Size);
         Xuint8_t *FinalAddress = 0x0;
         if (this->HeapUsed + Size >= this->HeapSize)
         {
             void *Address = Xalloc_REQUEST_PAGES(Pages);
             void *VirtualAddress = (void *)(this->BaseVirtualAddress + this->HeapSize);
             if (Xalloc_MapPages)
             {
                 for (Xsize_t i = 0; i < Pages; i++)
                 {
                     Xuintptr_t Page = i * Xalloc_PAGE_SIZE;
                     void *vAddress = (void *)((Xuintptr_t)VirtualAddress + Page);
                     Xalloc_MAP_MEMORY(vAddress, (void *)((Xuintptr_t)Address + Page), 0x3);
                 }
             }
             this->HeapSize += XPtoS(Pages);
             FinalAddress = (Xuint8_t *)VirtualAddress;
         }
         else
             FinalAddress = (Xuint8_t *)(this->BaseVirtualAddress + this->HeapUsed);
         this->HeapUsed += Size;
         return (uint8_t *)FinalAddress;
     }
References Address, Align(), BaseVirtualAddress, HeapSize, HeapUsed, i, Size, Xalloc_MAP_MEMORY(), Xalloc_MapPages, Xalloc_PAGE_SIZE, Xalloc_REQUEST_PAGES(), XPtoS, and XStoP.
Referenced by Xalloc::V2::Block::Block().
Arrange()
void Xalloc::V2::Arrange ()
Arrange the blocks to optimize the memory usage. The allocator is not arranged by default to avoid performance issues. This function will defragment the memory and free the unused blocks.
You should call this function when the kernel is idle or when is not using the allocator.
Definition at line 165 of file XallocV2.cpp.
     {
         Xalloc_err("Arrange() is not implemented yet!");
     }
References Xalloc_err.
calloc()
void * Xalloc::V2::calloc (Xsize_t NumberOfBlocks, Xsize_t Size)
Allocate a new memory block
Parameters
NumberOfBlocks Number of blocks to allocate.
Size Size of the block to allocate.
Returns
void* Pointer to the allocated block.
Definition at line 224 of file XallocV2.cpp.
     {
         if (NumberOfBlocks == 0 || Size == 0)
         {
             Xalloc_warn("The %s%s%s is 0!",
                         NumberOfBlocks == 0 ? "NumberOfBlocks" : "",
                         NumberOfBlocks == 0 && Size == 0 ? " and " : "",
                         Size == 0 ? "Size" : "");
             return nullptr;
         }
         return this->malloc(NumberOfBlocks * Size);
     }
References malloc(), Size, and Xalloc_warn.
Referenced by calloc().
FindFreeBlock()
void * Xalloc::V2::FindFreeBlock (Xsize_t Size, Block *& CurrentBlock) private
Definition at line 134 of file XallocV2.cpp.
     {
         if (this->FirstBlock == nullptr)
         {
             this->FirstBlock = new Block(Size, this);
             this->FirstBlock->IsFree = false;
             return this->FirstBlock->Data;
         }
         while (true)
         {
             CurrentBlock->Check();
             /* FIXME: This will waste a lot of space
                 need better algorithm */
             if (CurrentBlock->IsFree &&
                 CurrentBlock->DataSize >= Size)
             {
                 CurrentBlock->IsFree = false;
                 return CurrentBlock->Data;
             }
             if (CurrentBlock->Next == nullptr)
                 break;
             CurrentBlock = CurrentBlock->Next;
         }
         return nullptr;
     }
References Block, Xalloc::V2::Block::Check(), Xalloc::V2::Block::Data, Xalloc::V2::Block::DataSize, FirstBlock, Xalloc::V2::Block::IsFree, Xalloc::V2::Block::Next, and Size.
Referenced by malloc().
free()
void Xalloc::V2::free (void * Address)
Free a previously allocated block
Parameters
Address Address of the block to free.
Definition at line 193 of file XallocV2.cpp.
     {
         if (Address == nullptr)
         {
             Xalloc_warn("Attempted to free a null pointer!");
             return;
         }
         XallocV2_lock;
         Block *CurrentBlock = ((Block *)this->FirstBlock);
         while (CurrentBlock != nullptr)
         {
             CurrentBlock->Check();
             if (CurrentBlock->Data == Address)
             {
                 if (CurrentBlock->IsFree)
                     Xalloc_warn("Attempted to free an already freed block! %#lx", Address);
                 CurrentBlock->IsFree = true;
                 XallocV2_unlock;
                 return;
             }
             CurrentBlock = CurrentBlock->Next;
         }
         Xalloc_err("Invalid address %#lx.", Address);
         XallocV2_unlock;
     }
References Address, Xalloc::V2::Block::Check(), Xalloc::V2::Block::Data, FirstBlock, Xalloc::V2::Block::IsFree, Xalloc::V2::Block::Next, Xalloc_err, Xalloc_warn, XallocV2_lock, and XallocV2_unlock.
Referenced by free(), and realloc().
FreeHeap()
void Xalloc::V2::FreeHeap (Xuint8_t * At, Xsize_t Size) private
Definition at line 111 of file XallocV2.cpp.
     {
         Xsize_t Pages = XStoP(Size);
         if (Xalloc_MapPages)
         {
             for (Xsize_t i = 0; i < Pages; i++)
             {
                 Xuintptr_t Page = i * Xalloc_PAGE_SIZE;
                 void *VirtualAddress = (void *)((Xuintptr_t)At + Page);
                 Xalloc_UNMAP_MEMORY(VirtualAddress);
             }
         }
         Xalloc_FREE_PAGES(At, Pages);
         this->HeapUsed -= Size;
     }
References HeapUsed, i, Size, Xalloc_FREE_PAGES(), Xalloc_MapPages, Xalloc_PAGE_SIZE, Xalloc_UNMAP_MEMORY(), and XStoP.
malloc()
void * Xalloc::V2::malloc (Xsize_t Size)
Allocate a new memory block
Parameters
Size Size of the block to allocate.
Returns
void* Pointer to the allocated block.
Definition at line 170 of file XallocV2.cpp.
     {
         if (Size == 0)
         {
             Xalloc_warn("Attempted to allocate 0 bytes!");
             return nullptr;
         }
         XallocV2_lock;
         Block *CurrentBlock = this->FirstBlock;
         void *ret = this->FindFreeBlock(Size, CurrentBlock);
         if (ret)
         {
             XallocV2_unlock;
             return ret;
         }
         CurrentBlock->Next = new Block(Size, this);
         CurrentBlock->Next->IsFree = false;
         XallocV2_unlock;
         return CurrentBlock->Next->Data;
     }
References Block, Xalloc::V2::Block::Data, FindFreeBlock(), FirstBlock, Xalloc::V2::Block::IsFree, Xalloc::V2::Block::Next, Size, Xalloc_warn, XallocV2_lock, and XallocV2_unlock.
Referenced by calloc(), malloc(), and realloc().
realloc()
void * Xalloc::V2::realloc (void * Address, Xsize_t Size)
Reallocate a previously allocated block
Parameters
Address Address of the block to reallocate.
Size New size of the block.
Returns
void* Pointer to the reallocated block.
Definition at line 238 of file XallocV2.cpp.
     {
         if (Address == nullptr && Size != 0)
             return this->malloc(Size);
         if (Size == 0)
         {
             this->free(Address);
             return nullptr;
         }
         // XallocV2_lock;
         // ...
         // XallocV2_unlock;
         // TODO: Implement realloc
         static int once = 0;
         if (!once++)
             Xalloc_trace("realloc is stub!");
         this->free(Address);
         return this->malloc(Size);
     }
References Address, free(), malloc(), Size, and Xalloc_trace.
Referenced by realloc().
Friends And Related Function Documentation
Block
friend class Block friend
Definition at line 232 of file Xalloc.hpp.
Referenced by FindFreeBlock(), and malloc().
Field Documentation
BaseVirtualAddress
Xuintptr_t Xalloc::V2::BaseVirtualAddress = 0x0 private
Definition at line 147 of file Xalloc.hpp.
Referenced by AllocateHeap(), and V2().
FirstBlock
Block* Xalloc::V2::FirstBlock = nullptr private
Definition at line 155 of file Xalloc.hpp.
Referenced by FindFreeBlock(), free(), and malloc().
HeapSize
Xsize_t Xalloc::V2::HeapSize = 0x0 private
Definition at line 150 of file Xalloc.hpp.
Referenced by AllocateHeap().
HeapUsed
Xsize_t Xalloc::V2::HeapUsed = 0x0 private
Definition at line 153 of file Xalloc.hpp.
Referenced by AllocateHeap(), and FreeHeap().
The documentation for this class was generated from the following files:
Kernel/core/memory/heap_allocators/Xalloc/Xalloc.hpp
Kernel/core/memory/heap_allocators/Xalloc/XallocV2.cpp