Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_argv.h File Reference
m_argv.h File Reference
#include "doomtype.h"
Functions
int M_CheckParm (char *check)
int M_CheckParmWithArgs (char *check, int num_args)
void M_FindResponseFile (void)
boolean M_ParmExists (char *check)
char * M_GetExecutableName (void)
Variables
int myargc
char ** myargv
Function Documentation
M_CheckParm()
int M_CheckParm (char * check)
Definition at line 68 of file m_argv.c.
 {
     return M_CheckParmWithArgs(check, 0);
 }
References M_CheckParmWithArgs().
Referenced by D_CheckNetGame(), D_ConnectNetGame(), D_DoomMain(), D_Endoom(), D_InitNetGame(), D_StartNetGame(), G_BeginRecording(), G_DoPlayDemo(), G_TimeDemo(), I_InitSound(), I_Stretch5x(), InitConnectData(), M_ParmExists(), PadRejectArray(), SaveGameSettings(), and W_OpenFile().
M_CheckParmWithArgs()
int M_CheckParmWithArgs (char * check, int num_args)
Definition at line 43 of file m_argv.c.
 {
     int i;
     for (i = 1; i < myargc - num_args; i++)
     {
     if (!strcasecmp(check, myargv[i]))
         return i;
     }
     return 0;
 }
References i, myargc, myargv, and strcasecmp().
Referenced by D_DoomMain(), D_FindIWAD(), D_IdentifyVersion(), D_InitNetGame(), D_StartNetGame(), DonutOverrun(), G_RecordDemo(), I_GetMemoryValue(), I_InitGraphics(), I_ZoneBase(), InitGameVersion(), M_CheckParm(), M_LoadDefaults(), SpechitOverrun(), StatDump(), and W_ParseCommandLine().
M_FindResponseFile()
void M_FindResponseFile (void)
Definition at line 235 of file m_argv.c.
 {
     int             i;
     for (i = 1; i < myargc; i++)
     {
         if (myargv[i][0] == '@')
         {
             LoadResponseFile(i);
         }
     }
 }
M_GetExecutableName()
char* M_GetExecutableName (void)
Definition at line 250 of file m_argv.c.
 {
     char *sep;
     sep = strrchr(myargv[0], DIR_SEPARATOR);
     if (sep == NULL)
     {
         return myargv[0];
     }
     else
     {
         return sep + 1;
     }
 }
References DIR_SEPARATOR, myargv, NULL, and strrchr().
M_ParmExists()
boolean M_ParmExists (char * check)
Definition at line 63 of file m_argv.c.
 {
     return M_CheckParm(check) != 0;
 }
References M_CheckParm().
Referenced by D_DoomMain(), I_Error(), and StatCopy().
Variable Documentation
myargc
int myargc extern
Definition at line 29 of file m_argv.c.
Referenced by D_DoomMain(), doomgeneric_Create(), I_GetMemoryValue(), LoadResponseFile(), M_CheckParmWithArgs(), M_FindResponseFile(), and W_ParseCommandLine().
myargv
char** myargv extern
Definition at line 30 of file m_argv.c.
Referenced by D_DoomMain(), D_FindIWAD(), D_IdentifyVersion(), D_InitNetGame(), D_StartNetGame(), DonutOverrun(), doomgeneric_Create(), G_RecordDemo(), I_GetMemoryValue(), I_InitGraphics(), I_ZoneBase(), InitGameVersion(), LoadResponseFile(), M_CheckParmWithArgs(), M_FindResponseFile(), M_GetExecutableName(), M_LoadDefaults(), SpechitOverrun(), StatDump(), and W_ParseCommandLine().