Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/nilfs.c File Reference
nilfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct nilfs2_super_block
Macros
#define NILFS_UUID_SIZE 16
#define NILFS_LABEL_SIZE 80
#define NILFS_SB1_OFFSET 0x400
#define NILFS_SB2_OFFSET 0x1000
#define NILFS_MAGIC 0x3434
Functions
int FAST_FUNC volume_id_probe_nilfs (struct volume_id *id)
Variables
struct nilfs2_super_block PACKED
Data Structure Documentation
nilfs2_super_block
struct nilfs2_super_block
Definition at line 47 of file nilfs.c.
Data Fields
uint32_t s_blocks_per_segment
uint16_t s_bytes
uint32_t s_checkinterval
uint16_t s_checkpoint_size
uint32_t s_crc_seed
uint32_t s_creator_os
uint64_t s_ctime
uint16_t s_dat_entry_size
uint16_t s_def_resgid
uint16_t s_def_resuid
uint64_t s_dev_size
uint16_t s_errors
uint64_t s_first_data_block
uint32_t s_first_ino
uint16_t s_flags
uint64_t s_free_blocks_count
uint16_t s_inode_size
uint64_t s_last_cno
uint64_t s_last_pseg
uint64_t s_last_seq
uint64_t s_lastcheck
uint32_t s_log_block_size
uint16_t s_magic
uint16_t s_max_mnt_count
uint16_t s_minor_rev_level
uint16_t s_mnt_count
uint64_t s_mtime
uint64_t s_nsegments
uint32_t s_r_segments_percentage
uint32_t s_rev_level
uint16_t s_segment_usage_size
uint16_t s_state
uint32_t s_sum
uint8_t s_uuid[NILFS_UUID_SIZE]
uint8_t s_volume_name[NILFS_LABEL_SIZE]
uint64_t s_wtime
Macro Definition Documentation
NILFS_LABEL_SIZE
#define NILFS_LABEL_SIZE 80
Definition at line 42 of file nilfs.c.
NILFS_MAGIC
#define NILFS_MAGIC 0x3434
Definition at line 45 of file nilfs.c.
NILFS_SB1_OFFSET
#define NILFS_SB1_OFFSET 0x400
Definition at line 43 of file nilfs.c.
NILFS_SB2_OFFSET
#define NILFS_SB2_OFFSET 0x1000
Definition at line 44 of file nilfs.c.
NILFS_UUID_SIZE
#define NILFS_UUID_SIZE 16
Definition at line 41 of file nilfs.c.
Function Documentation
volume_id_probe_nilfs()
int FAST_FUNC volume_id_probe_nilfs (struct volume_id * id)
Definition at line 87 of file nilfs.c.
 {
     struct nilfs2_super_block *sb;
     // Primary super block
     dbg("nilfs: probing at offset 0x%x", NILFS_SB1_OFFSET);
     sb = volume_id_get_buffer(id, NILFS_SB1_OFFSET, sizeof(*sb));
     if (sb == NULL)
         return -1;
     if (sb->s_magic != NILFS_MAGIC)
         return -1;
     // The secondary superblock is not always used, so ignore it for now.
     // When used it is at 4K from the end of the partition (sb->s_dev_size - NILFS_SB2_OFFSET).
     volume_id_set_label_string(id, sb->s_volume_name, NILFS_LABEL_SIZE < VOLUME_ID_LABEL_SIZE ?
                 NILFS_LABEL_SIZE : VOLUME_ID_LABEL_SIZE);
     volume_id_set_uuid(id, sb->s_uuid, UUID_DCE);
     if (sb->s_rev_level == 2)
         IF_FEATURE_BLKID_TYPE(id->type = "nilfs2");
     return 0;
 }
References dbg, NILFS_LABEL_SIZE, NILFS_MAGIC, NILFS_SB1_OFFSET, NULL, nilfs2_super_block::s_magic, nilfs2_super_block::s_rev_level, nilfs2_super_block::s_uuid, nilfs2_super_block::s_volume_name, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct nilfs2_super_block PACKED