Fennix Userspace: Userspace/apps/base/busybox/coreutils/mkdir.c File Reference
mkdir.c File Reference
#include "libbb.h"
Functions
int mkdir_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
mkdir_main()
int mkdir_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 52 of file mkdir.c.
 {
     long mode = -1;
     int status = EXIT_SUCCESS;
     int flags = 0;
     unsigned opt;
     char *smode;
 #if ENABLE_SELINUX
     security_context_t scontext;
 #endif
     opt = getopt32long(argv, "m:pv" IF_SELINUX("Z:"),
             "mode\0"    Required_argument "m"
             "parents\0" No_argument       "p"
 # if ENABLE_SELINUX
             "context\0" Required_argument "Z"
 # endif
 # if ENABLE_FEATURE_VERBOSE
             "verbose\0" No_argument       "v"
 # endif
             , &smode IF_SELINUX(,&scontext)
     );
     if (opt & 1) {
         mode_t mmode = bb_parse_mode(smode, 0777);
         if (mmode == (mode_t)-1) {
             bb_error_msg_and_die("invalid mode '%s'", smode);
         }
         mode = mmode;
     }
     if (opt & 2)
         flags |= FILEUTILS_RECUR;
     if ((opt & 4) && FILEUTILS_VERBOSE)
         flags |= FILEUTILS_VERBOSE;
 #if ENABLE_SELINUX
     if (opt & 8) {
         selinux_or_die();
         setfscreatecon_or_die(scontext);
     }
 #endif
     argv += optind;
     if (!argv[0])
         bb_show_usage();
     do {
         if (bb_make_directory(*argv, mode, flags)) {
             status = EXIT_FAILURE;
         }
     } while (*++argv);
     return status;
 }
References argv, bb_error_msg_and_die(), bb_make_directory(), bb_parse_mode(), bb_show_usage(), EXIT_FAILURE, EXIT_SUCCESS, FILEUTILS_RECUR, FILEUTILS_VERBOSE, flags, getopt32long, mode_t, No_argument, opt, optind, Required_argument, selinux_or_die(), setfscreatecon_or_die(), and status.