Fennix: Userspace/apps/base/busybox/libpwdgrp/uidgid_get.c File Reference
uidgid_get.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC get_uidgid (struct bb_uidgid_t *u, const char *ug)
void FAST_FUNC xget_uidgid (struct bb_uidgid_t *u, const char *ug)
void FAST_FUNC parse_chown_usergroup_or_die (struct bb_uidgid_t *u, char *user_group)
Function Documentation
get_uidgid()
int FAST_FUNC get_uidgid (struct bb_uidgid_t * u, const char * ug)
Definition at line 31 of file uidgid_get.c.
 {
     struct passwd *pwd;
     struct group *gr;
     char *user, *group;
     unsigned n;
     user = (char*)ug;
     group = strchr(ug, ':');
     if (group) {
         int sz = (++group) - ug;
         user = alloca(sz);
         /* copies sz-1 bytes, stores terminating '\0' */
         safe_strncpy(user, ug, sz);
     }
     n = bb_strtou(user, NULL, 10);
     if (!errno) {
         u->uid = n;
         pwd = getpwuid(n);
         /* If we have e.g. "500" string without user */
         /* with uid 500 in /etc/passwd, we set gid == uid */
         u->gid = pwd ? pwd->pw_gid : n;
         goto skip;
     }
     /* it is not numeric */
     pwd = getpwnam(user);
     if (!pwd)
         return 0;
     u->uid = pwd->pw_uid;
     u->gid = pwd->pw_gid;
  skip:
     if (group) {
         n = bb_strtou(group, NULL, 10);
         if (!errno) {
             u->gid = n;
             return 1;
         }
         gr = getgrnam(group);
         if (!gr)
             return 0;
         u->gid = gr->gr_gid;
     }
     return 1;
 }
References alloca, bb_strtou(), errno, getgrnam, getpwnam, getpwuid, bb_uidgid_t::gid, gr, group::gr_gid, n, NULL, passwd::pw_gid, passwd::pw_uid, safe_strncpy(), skip, strchr(), bb_uidgid_t::uid, and user.
Referenced by xget_uidgid().
parse_chown_usergroup_or_die()
void FAST_FUNC parse_chown_usergroup_or_die (struct bb_uidgid_t * u, char * user_group)
Definition at line 89 of file uidgid_get.c.
 {
     char *group;
     u->uid = u->gid = (gid_t)-1L;
     /* Check if there is a group name */
     group = strchr(user_group, '.'); /* deprecated? */
     if (!group)
         group = strchr(user_group, ':');
     else
         *group = ':'; /* replace '.' with ':' */
     /* Parse "user[:[group]]" */
     if (!group) { /* "user" */
         u->uid = get_ug_id(user_group, xuname2uid);
     } else if (group == user_group) { /* ":group" */
         u->gid = get_ug_id(group + 1, xgroup2gid);
     } else {
         if (!group[1]) /* "user:" */
             *group = '\0';
         xget_uidgid(u, user_group);
     }
 }
References get_ug_id(), bb_uidgid_t::gid, strchr(), bb_uidgid_t::uid, xget_uidgid(), xgroup2gid(), and xuname2uid().
Referenced by start_stop_daemon_main().
xget_uidgid()
void FAST_FUNC xget_uidgid (struct bb_uidgid_t * u, const char * ug)
Definition at line 76 of file uidgid_get.c.
 {
     if (!get_uidgid(u, ug))
         bb_error_msg_and_die("unknown user/group %s", ug);
 }
References bb_error_msg_and_die(), and get_uidgid().
Referenced by chpst_main(), httpd_main(), parse_chown_usergroup_or_die(), and tcpudpsvd_main().