Fennix Userspace: Userspace/apps/base/busybox/init/halt.c File Reference
halt.c File Reference
#include "libbb.h"
#include "reboot.h"
Macros
#define write_wtmp() ((void)0)
#define init_was_not_there() 0
Functions
int halt_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
init_was_not_there
#define init_was_not_there () 0
Definition at line 161 of file halt.c.
write_wtmp
#define write_wtmp () ((void)0)
Definition at line 119 of file halt.c.
Function Documentation
halt_main()
int halt_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 165 of file halt.c.
 {
     static const int magic[] = {
         RB_HALT_SYSTEM,
         RB_POWER_OFF,
         RB_AUTOBOOT
     };
     static const smallint signals[] = { SIGUSR1, SIGUSR2, SIGTERM };
     int delay = 0;
     int which, flags, rc;
     /* Figure out which applet we're running */
     if (ENABLE_HALT && !ENABLE_POWEROFF && !ENABLE_REBOOT)
         which = 0;
     else
     if (!ENABLE_HALT && ENABLE_POWEROFF && !ENABLE_REBOOT)
         which = 1;
     else
     if (!ENABLE_HALT && !ENABLE_POWEROFF && ENABLE_REBOOT)
         which = 2;
     else
     for (which = 0; "hpr"[which] != applet_name[0]; which++)
         continue;
     /* Parse and handle arguments */
     /* We support -w even if !ENABLE_FEATURE_WTMP,
      * in order to not break scripts.
      * -i (shut down network interfaces) is ignored.
      */
     flags = getopt32(argv, "d:+nfwi", &delay);
     sleep(delay);
     write_wtmp();
     if (flags & 8) /* -w */
         return EXIT_SUCCESS;
     if (!(flags & 2)) /* no -n */
         sync();
     /* Perform action. */
     rc = 1;
     if (!(flags & 4)) { /* no -f */
 //TODO: I tend to think that signalling linuxrc is wrong
 // pity original author didn't comment on it...
         if (ENABLE_LINUXRC) {
             /* talk to linuxrc */
             /* bbox init/linuxrc assumed */
             pid_t *pidlist = find_pid_by_name("linuxrc");
             if (pidlist[0] > 0)
                 rc = kill(pidlist[0], signals[which]);
             if (ENABLE_FEATURE_CLEAN_UP)
                 free(pidlist);
         }
         if (rc) {
             /* talk to init */
             if (!ENABLE_FEATURE_CALL_TELINIT) {
                 /* bbox init assumed */
                 rc = kill(1, signals[which]);
                 if (init_was_not_there())
                     rc = kill(1, signals[which]);
             } else {
                 /* SysV style init assumed */
                 /* runlevels:
                  * 0 == shutdown
                  * 6 == reboot */
                 execlp(CONFIG_TELINIT_PATH,
                         CONFIG_TELINIT_PATH,
                         which == 2 ? "6" : "0",
                         (char *)NULL
                 );
                 bb_perror_msg_and_die("can't execute '%s'",
                         CONFIG_TELINIT_PATH);
             }
         }
     } else {
         rc = reboot(magic[which]);
     }
     if (rc)
         bb_perror_nomsg_and_die();
     return rc;
 }
References applet_name, argv, bb_perror_msg_and_die(), bb_perror_nomsg_and_die(), execlp(), EXIT_SUCCESS, find_pid_by_name(), flags, free, getopt32(), init_was_not_there, kill(), NULL, RB_AUTOBOOT, RB_HALT_SYSTEM, RB_POWER_OFF, rc, reboot(), SIGTERM, SIGUSR1, SIGUSR2, sleep(), sync(), and write_wtmp.