Fennix Lynx Bootloader: Memory64::PageTableEntry Union Reference
Memory64::PageTableEntry Union Reference
#include <memory.hpp>
Public Member Functions
void SetAddress (uintptr_t _Address)
Set Address.
uintptr_t GetAddress ()
Get Address.
Data Fields
struct {
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
uint64_t CacheDisable: 1
uint64_t Accessed: 1
uint64_t Dirty: 1
uint64_t PageAttributeTable: 1
uint64_t Global: 1
uint64_t Available0: 3
uint64_t Address: 40
uint64_t Available1: 7
uint64_t ProtectionKey: 4
uint64_t ExecuteDisable: 1
};
uint64_t raw
Detailed Description
Definition at line 240 of file memory.hpp.
Member Function Documentation
GetAddress()
uintptr_t Memory64::PageTableEntry::GetAddress () inline
Get Address.
Definition at line 270 of file memory.hpp.
         {
             return (this->raw & 0x000FFFFFFFFFF000) >> 12;
         }
Referenced by Memory64::Virtual::GetPhysical(), and Memory64::Virtual::Unmap().
SetAddress()
void Memory64::PageTableEntry::SetAddress (uintptr_t _Address) inline
Set Address.
Definition at line 262 of file memory.hpp.
         {
             _Address &= 0x000000FFFFFFFFFF;
             this->raw &= 0xFFF0000000000FFF;
             this->raw |= (_Address << 12);
         }
Referenced by Memory64::Virtual::Map().
Field Documentation
struct { ... }
raw
uint64_t Memory64::PageTableEntry::raw
Definition at line 259 of file memory.hpp.
Referenced by Memory64::Virtual::Map().
The documentation for this union was generated from the following file:
Lynx/FennixLoader/include/memory.hpp