Fennix: Userspace/musl/src/stat/__xstat.c File Reference
__xstat.c File Reference
#include <sys/stat.h>
Functions
int __fxstat (int ver, int fd, struct stat *buf)
int __fxstatat (int ver, int fd, const char *path, struct stat *buf, int flag)
int __lxstat (int ver, const char *path, struct stat *buf)
int __xstat (int ver, const char *path, struct stat *buf)
int __xmknod (int ver, const char *path, mode_t mode, dev_t *dev)
int __xmknodat (int ver, int fd, const char *path, mode_t mode, dev_t *dev)
Function Documentation
__fxstat()
int __fxstat (int ver, int fd, struct stat * buf)
Definition at line 5 of file __xstat.c.
 {
     return fstat(fd, buf);
 }
References buf, fd, and fstat().
__fxstatat()
int __fxstatat (int ver, int fd, const char * path, struct stat * buf, int flag)
Definition at line 10 of file __xstat.c.
 {
     return fstatat(fd, path, buf, flag);
 }
References buf, fd, and fstatat().
__lxstat()
int __lxstat (int ver, const char * path, struct stat * buf)
Definition at line 15 of file __xstat.c.
 {
     return lstat(path, buf);
 }
References buf, and lstat().
__xmknod()
int __xmknod (int ver, const char * path, mode_t mode, dev_t * dev)
Definition at line 27 of file __xstat.c.
 {
     return mknod(path, mode, *dev);
 }
References mknod().
__xmknodat()
int __xmknodat (int ver, int fd, const char * path, mode_t mode, dev_t * dev)
Definition at line 32 of file __xstat.c.
 {
     return mknodat(fd, path, mode, *dev);
 }
References fd, and mknodat().
__xstat()
int __xstat (int ver, const char * path, struct stat * buf)
Definition at line 20 of file __xstat.c.
 {
     return stat(path, buf);
 }
References buf, and stat().