Fennix Userspace: Userspace/apps/base/bash/support/xcase.c File Reference
xcase.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "bashansi.h"
#include <errno.h>
Macros
#define LOWER 1
#define UPPER 2
Functions
int main (int ac, char **av)
Variables
int errno
int optind
Macro Definition Documentation
LOWER
#define LOWER 1
Definition at line 41 of file xcase.c.
UPPER
#define UPPER 2
Definition at line 42 of file xcase.c.
Function Documentation
main()
int main (int ac, char ** av)
Definition at line 45 of file xcase.c.
 {
     int c, x;
     int op;
     FILE    *inf;
     op = 0;
     while ((c = getopt(ac, av, "lnu")) != EOF) {
         switch (c) {
         case 'n':
             setbuf (stdout, (char *)NULL);
             break;
         case 'u':
             op = UPPER;
             break;
         case 'l':
             op = LOWER;
             break;
         default:
             fprintf(stderr, "casemod: usage: casemod [-lnu] [file]\n");
             exit(2);
         }
     }
     av += optind;
     ac -= optind;
     if (av[0] && (av[0][0] != '-' || av[0][1])) {
         inf = fopen(av[0], "r");
         if (inf == 0) {
             fprintf(stderr, "casemod: %s: cannot open: %s\n", av[0], strerror(errno));
             exit(1);
         }
     } else
         inf = stdin;
     while ((c = getc(inf)) != EOF) {
         switch (op) {
         case UPPER:
             x = islower(c) ? toupper(c) : c;
             break;
         case LOWER:
             x = isupper(c) ? tolower(c) : c;
             break;
         default:
             x = c;
             break;
         }
         putchar(x);
     }
     exit(0);
 }
References c, EOF, errno, exit(), fopen(), fprintf(), getc, getopt(), islower, isupper, LOWER, NULL, optind, putchar, setbuf(), stderr, stdin, stdout, strerror(), tolower, toupper, UPPER, and x.
Variable Documentation
errno
int errno extern
Referenced by main().
optind
int optind extern
Definition at line 11 of file getopt.c.
Referenced by main().