Fennix: Userspace/apps/base/busybox/applets/individual.c File Reference
individual.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "usage.h"
Functions
int main (int argc, char **argv)
void bb_show_usage (void)
Variables
const char * applet_name
Function Documentation
bb_show_usage()
void bb_show_usage (void)
Definition at line 20 of file individual.c.
 {
     fputs_stdout(APPLET_full_usage "\n");
     exit(EXIT_FAILURE);
 }
References exit(), EXIT_FAILURE, and fputs_stdout().
Referenced by addgroup_main(), ar_main(), arp_del(), arp_set(), awk_main(), basename_main(), beep_main(), blockdev_main(), bootchartd_main(), brctl_main(), cal_main(), chat_main(), chattr_main(), chpst_main(), chroot_main(), chrt_main(), common_ping_main(), cp_main(), crontab_main(), date_main(), dc_main(), dd_main(), deallocvt_main(), decode_arg(), deluser_main(), devfsd_main(), devmem_main(), dhcprelay_main(), dpkg_deb_main(), dpkg_main(), dumpkmap_main(), expand(), factorize_numstr(), fallocate_main(), fatattr_main(), fbset_main(), fbsplash_main(), fdisk_main(), find_cmd(), findfs_main(), flash_lock_unlock_main(), free_main(), fsck_main(), ftpd_main(), get_dest_addr(), get_flag(), getsebool_main(), grep_main(), hdparm_main(), head_main(), hexdump_main(), hostid_main(), hush_main(), ifconfig_main(), ifupdown_main(), INET_setroute(), init_if(), inotifyd_main(), insmod_main(), install_main(), ip_parse_common_args(), ipcalc_main(), ipcrm_main(), ipcs_main(), iprule_modify(), kill_main(), kw_lookup(), last_main(), less_main(), load_policy_main(), loadkmap_main(), logname_main(), losetup_main(), mesg_main(), mkdir_main(), mkfifo_main(), mkfs_minix_main(), mknod_main(), mpstat_main(), mt_main(), mv_main(), nameif_main(), nandwrite_main(), nbdclient_main(), nc_main(), nice_main(), nmeter_main(), nohup_main(), nslookup_main(), ntp_init(), od_main(), open_by_path_or_target(), parse_params(), passwd_main(), pgrep_main(), pivot_root_main(), printf_main(), process_action(), readahead_main(), readlink_main(), realpath_main(), renice_main(), resume_main(), rfkill_main(), rm_main(), rmdir_main(), rmmod_main(), route_main(), scriptreplay_main(), sed_main(), sendmail_main(), seq_main(), setarch_main(), setenforce_main(), setfiles_main(), setkeycodes_main(), setpriv_main(), setsebool_main(), shred_main(), shuf_main(), single_argv(), sleep_main(), ssl_client_main(), start_stop_daemon_main(), strings_main(), svlogd_main(), swap_on_off_main(), switch_root_main(), taskset_main(), tc_main(), tcpudpsvd_main(), telnet_main(), timeout_main(), tsort_main(), tune2fs_main(), ubi_tools_main(), ubirename_main(), udhcpc_main(), umount_main(), uniq_main(), unzip_main(), usleep_main(), vconfig_main(), vgetopt32(), vi_main(), volname_main(), whoami_main(), and xfind_str().
main()
int main (int argc , char ** argv)
Definition at line 14 of file individual.c.
 {
     applet_name = argv[0];
     return APPLET_main(argc, argv);
 }
References applet_name, argc, and argv.
Variable Documentation
applet_name
const char* applet_name
Definition at line 8 of file individual.c.
Referenced by acpid_main(), ask_and_unlink(), bb_verror_msg(), brctl_main(), chpst_main(), crond_main(), cryptpw_main(), deluser_main(), devfsd_main(), dnsd_main(), do_ipaddr(), do_iplink(), do_ipneigh(), do_iproute(), do_iprule(), do_iptunnel(), dos2unix_main(), expand_main(), fakeidentd_main(), flash_eraseall_main(), freeramdisk_main(), fsck_minix_main(), ftpd_main(), ftpgetput_main(), getty_main(), grep_main(), halt_main(), handle_incoming_and_exit(), hash_file(), hexdump_main(), hostname_main(), id_main(), ifplugd_main(), ifupdown_main(), inetd_main(), init_main(), iprule_modify(), login_main(), lpqr_main(), ls_main(), lzop_main(), main(), md5_sha1_sum_main(), mdev_main(), message(), nameif_main(), open_mdev_log(), open_tty(), passwd_main(), printf_main(), remove_file(), restore(), setarch_main(), setfiles_main(), sleep_main(), su_main(), sulogin_main(), switch_root_main(), tcpudpsvd_main(), telnetd_main(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), update_passwd(), vi_main(), and who_main().