Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/d_main.h File Reference
d_main.h File Reference
#include "doomdef.h"
Functions
void D_ProcessEvents (void)
void D_PageTicker (void)
void D_PageDrawer (void)
void D_AdvanceDemo (void)
void D_DoAdvanceDemo (void)
void D_StartTitle (void)
Variables
gameaction_t gameaction
Function Documentation
D_AdvanceDemo()
void D_AdvanceDemo (void)
Definition at line 496 of file d_main.c.
 {
     advancedemo = true;
 }
References advancedemo.
Referenced by D_PageTicker(), D_StartTitle(), and G_CheckDemoStatus().
D_DoAdvanceDemo()
void D_DoAdvanceDemo (void)
Definition at line 506 of file d_main.c.
 {
     players[consoleplayer].playerstate = PST_LIVE;  // not reborn
     advancedemo = false;
     usergame = false;               // no save / end game here
     paused = false;
     gameaction = ga_nothing;
     // The Ultimate Doom executable changed the demo sequence to add
     // a DEMO4 demo.  Final Doom was based on Ultimate, so also
     // includes this change; however, the Final Doom IWADs do not
     // include a DEMO4 lump, so the game bombs out with an error
     // when it reaches this point in the demo sequence.
     // However! There is an alternate version of Final Doom that
     // includes a fixed executable.
     if (gameversion == exe_ultimate || gameversion == exe_final)
       demosequence = (demosequence+1)%7;
     else
       demosequence = (demosequence+1)%6;
     switch (demosequence)
     {
       case 0:
     if ( gamemode == commercial )
         pagetic = TICRATE * 11;
     else
         pagetic = 170;
     gamestate = GS_DEMOSCREEN;
     pagename = DEH_String("TITLEPIC");
     if ( gamemode == commercial )
       S_StartMusic(mus_dm2ttl);
     else
       S_StartMusic (mus_intro);
     break;
       case 1:
     G_DeferedPlayDemo(DEH_String("demo1"));
     break;
       case 2:
     pagetic = 200;
     gamestate = GS_DEMOSCREEN;
     pagename = DEH_String("CREDIT");
     break;
       case 3:
     G_DeferedPlayDemo(DEH_String("demo2"));
     break;
       case 4:
     gamestate = GS_DEMOSCREEN;
     if ( gamemode == commercial)
     {
         pagetic = TICRATE * 11;
         pagename = DEH_String("TITLEPIC");
         S_StartMusic(mus_dm2ttl);
     }
     else
     {
         pagetic = 200;
         if ( gamemode == retail )
           pagename = DEH_String("CREDIT");
         else
           pagename = DEH_String("HELP2");
     }
     break;
       case 5:
     G_DeferedPlayDemo(DEH_String("demo3"));
     break;
         // THE DEFINITIVE DOOM Special Edition demo
       case 6:
     G_DeferedPlayDemo(DEH_String("demo4"));
     break;
     }
     // The Doom 3: BFG Edition version of doom2.wad does not have a
     // TITLETPIC lump. Use INTERPIC instead as a workaround.
     if (bfgedition && !strcasecmp(pagename, "TITLEPIC")
         && W_CheckNumForName("titlepic") < 0)
     {
         pagename = DEH_String("INTERPIC");
     }
 }
References advancedemo, bfgedition, commercial, consoleplayer, DEH_String, demosequence, exe_final, exe_ultimate, G_DeferedPlayDemo(), ga_nothing, gameaction, gamemode, gamestate, gameversion, GS_DEMOSCREEN, mus_dm2ttl, mus_intro, pagename, pagetic, paused, players, player_s::playerstate, PST_LIVE, retail, S_StartMusic(), strcasecmp, TICRATE, usergame, and W_CheckNumForName().
Referenced by RunTic().
D_PageDrawer()
void D_PageDrawer (void)
Definition at line 486 of file d_main.c.
 {
     V_DrawPatch (0, 0, W_CacheLumpName(pagename, PU_CACHE));
 }
References pagename, PU_CACHE, V_DrawPatch(), and W_CacheLumpName().
Referenced by D_Display().
D_PageTicker()
void D_PageTicker (void)
Definition at line 475 of file d_main.c.
 {
     if (--pagetic < 0)
     D_AdvanceDemo ();
 }
References D_AdvanceDemo(), and pagetic.
Referenced by G_Ticker().
D_ProcessEvents()
void D_ProcessEvents (void)
Definition at line 139 of file d_main.c.
 {
     event_t*    ev;
     // IF STORE DEMO, DO NOT ACCEPT INPUT
     if (storedemo)
         return;
     while ((ev = D_PopEvent()) != NULL)
     {
     if (M_Responder (ev))
         continue;               // menu ate the event
     G_Responder (ev);
     }
 }
References D_PopEvent(), G_Responder(), M_Responder(), NULL, and storedemo.
D_StartTitle()
void D_StartTitle (void)
Definition at line 594 of file d_main.c.
 {
     gameaction = ga_nothing;
     demosequence = -1;
     D_AdvanceDemo ();
 }
References D_AdvanceDemo(), demosequence, ga_nothing, and gameaction.
Referenced by D_DoomMain(), and M_EndGameResponse().
Variable Documentation
gameaction
gameaction_t gameaction extern
Definition at line 96 of file g_game.c.
Referenced by D_DoAdvanceDemo(), D_DoomLoop(), D_DoomMain(), D_StartTitle(), F_StartFinale(), F_Ticker(), G_DeferedInitNew(), G_DeferedPlayDemo(), G_DoCompleted(), G_DoLoadGame(), G_DoLoadLevel(), G_DoNewGame(), G_DoPlayDemo(), G_DoReborn(), G_DoSaveGame(), G_DoWorldDone(), G_ExitLevel(), G_LoadGame(), G_Responder(), G_ScreenShot(), G_SecretExitLevel(), G_Ticker(), G_TimeDemo(), and G_WorldDone().