Fennix Userspace: Userspace/musl/src/math/exp.c File Reference
exp.c File Reference
#include <math.h>
#include <stdint.h>
#include "libm.h"
#include "exp_data.h"
Macros
#define N (1 << EXP_TABLE_BITS)
#define InvLn2N __exp_data.invln2N
#define NegLn2hiN __exp_data.negln2hiN
#define NegLn2loN __exp_data.negln2loN
#define Shift __exp_data.shift
#define T __exp_data.tab
#define C2 __exp_data.poly[5 - EXP_POLY_ORDER]
#define C3 __exp_data.poly[6 - EXP_POLY_ORDER]
#define C4 __exp_data.poly[7 - EXP_POLY_ORDER]
#define C5 __exp_data.poly[8 - EXP_POLY_ORDER]
Functions
static double specialcase (double_t tmp, uint64_t sbits, uint64_t ki)
static uint32_t top12 (double x)
double exp (double x)
Macro Definition Documentation
C2
#define C2 __exp_data.poly[5 - EXP_POLY_ORDER]
Definition at line 19 of file exp.c.
C3
#define C3 __exp_data.poly[6 - EXP_POLY_ORDER]
Definition at line 20 of file exp.c.
C4
#define C4 __exp_data.poly[7 - EXP_POLY_ORDER]
Definition at line 21 of file exp.c.
C5
#define C5 __exp_data.poly[8 - EXP_POLY_ORDER]
Definition at line 22 of file exp.c.
InvLn2N
#define InvLn2N __exp_data.invln2N
Definition at line 14 of file exp.c.
N
#define N (1 << EXP_TABLE_BITS)
Definition at line 13 of file exp.c.
NegLn2hiN
#define NegLn2hiN __exp_data.negln2hiN
Definition at line 15 of file exp.c.
NegLn2loN
#define NegLn2loN __exp_data.negln2loN
Definition at line 16 of file exp.c.
Shift
#define Shift __exp_data.shift
Definition at line 17 of file exp.c.
T
#define T __exp_data.tab
Definition at line 18 of file exp.c.
Function Documentation
exp()
double exp (double x)
Definition at line 72 of file exp.c.
 {
     uint32_t abstop;
     uint64_t ki, idx, top, sbits;
     double_t kd, z, r, r2, scale, tail, tmp;
     abstop = top12(x) & 0x7ff;
     if (predict_false(abstop - top12(0x1p-54) >= top12(512.0) - top12(0x1p-54))) {
         if (abstop - top12(0x1p-54) >= 0x80000000)
             /* Avoid spurious underflow for tiny x.  */
             /* Note: 0 is common input.  */
             return WANT_ROUNDING ? 1.0 + x : 1.0;
         if (abstop >= top12(1024.0)) {
             if (asuint64(x) == asuint64(-INFINITY))
                 return 0.0;
             if (abstop >= top12(INFINITY))
                 return 1.0 + x;
             if (asuint64(x) >> 63)
                 return __math_uflow(0);
             else
                 return __math_oflow(0);
         }
         /* Large x is special cased below.  */
         abstop = 0;
     }
     /* exp(x) = 2^(k/N) * exp(r), with exp(r) in [2^(-1/2N),2^(1/2N)].  */
     /* x = ln2/N*k + r, with int k and r in [-ln2/2N, ln2/2N].  */
     z = InvLn2N * x;
 #if TOINT_INTRINSICS
     kd = roundtoint(z);
     ki = converttoint(z);
 #elif EXP_USE_TOINT_NARROW
     /* z - kd is in [-0.5-2^-16, 0.5] in all rounding modes.  */
     kd = eval_as_double(z + Shift);
     ki = asuint64(kd) >> 16;
     kd = (double_t)(int32_t)ki;
 #else
     /* z - kd is in [-1, 1] in non-nearest rounding modes.  */
     kd = eval_as_double(z + Shift);
     ki = asuint64(kd);
     kd -= Shift;
 #endif
     r = x + kd * NegLn2hiN + kd * NegLn2loN;
     /* 2^(k/N) ~= scale * (1 + tail).  */
     idx = 2 * (ki % N);
     top = ki << (52 - EXP_TABLE_BITS);
     tail = asdouble(T[idx]);
     /* This is only a valid scale when -1023*N < k < 1024*N.  */
     sbits = T[idx + 1] + top;
     /* exp(x) = 2^(k/N) * exp(r) ~= scale + scale * (tail + exp(r) - 1).  */
     /* Evaluation is optimized assuming superscalar pipelined execution.  */
     r2 = r * r;
     /* Without fma the worst case error is 0.25/N ulp larger.  */
     /* Worst case error is less than 0.5+1.11/N+(abs poly error * 2^53) ulp.  */
     tmp = tail + r + r2 * (C2 + r * C3) + r2 * r2 * (C4 + r * C5);
     if (predict_false(abstop == 0))
         return specialcase(tmp, sbits, ki);
     scale = asdouble(sbits);
     /* Note: tmp == 0 or |tmp| > 2^-200 and scale > 2^-739, so there
        is no spurious underflow here even without fma.  */
     return eval_as_double(scale + scale * tmp);
 }
References __math_oflow(), __math_uflow(), asdouble, asuint64, c, C2, C3, C4, C5, eval_as_double(), EXP_TABLE_BITS, FORCE_EVAL, GET_HIGH_WORD, half, idx, INFINITY, int, invln2, InvLn2N, isnan, k, ln2hi, ln2lo, N, NegLn2hiN, NegLn2loN, P1, P2, P3, P4, P5, predict_false, r, r2, scalbn, Shift, specialcase(), T, tail, top, top12(), WANT_ROUNDING, x, and y.
specialcase()
static double specialcase (double_t tmp, uint64_t sbits, uint64_t ki) inline static
Definition at line 31 of file exp.c.
 {
     double_t scale, y;
     if ((ki & 0x80000000) == 0) {
         /* k > 0, the exponent of scale might have overflowed by <= 460.  */
         sbits -= 1009ull << 52;
         scale = asdouble(sbits);
         y = 0x1p1009 * (scale + scale * tmp);
         return eval_as_double(y);
     }
     /* k < 0, need special care in the subnormal range.  */
     sbits += 1022ull << 52;
     scale = asdouble(sbits);
     y = scale + scale * tmp;
     if (y < 1.0) {
         /* Round y to the right precision before scaling it into the subnormal
          range to avoid double rounding that can cause 0.5+E/2 ulp error where
          E is the worst-case ulp error outside the subnormal range.  So this
          is only useful if the goal is better than 1 ulp worst-case error.  */
         double_t hi, lo;
         lo = scale - y + scale * tmp;
         hi = 1.0 + y;
         lo = 1.0 - hi + y + lo;
         y = eval_as_double(hi + lo) - 1.0;
         /* Avoid -0.0 with downward rounding.  */
         if (WANT_ROUNDING && y == 0.0)
             y = 0.0;
         /* The underflow exception needs to be signaled explicitly.  */
         fp_force_eval(fp_barrier(0x1p-1022) * 0x1p-1022);
     }
     y = 0x1p-1022 * y;
     return eval_as_double(y);
 }
References asdouble, eval_as_double(), fp_barrier, fp_force_eval, WANT_ROUNDING, and y.
Referenced by exp().
top12()
static uint32_t top12 (double x) inline static
Definition at line 67 of file exp.c.
 {
     return asuint64(x) >> 52;
 }
References asuint64, and x.
Referenced by exp().