Fennix Kernel: CrashPS2KeyboardDriver Class Reference
CrashPS2KeyboardDriver Class Reference
#include <ps2.hpp>
Public Member Functions
CrashPS2KeyboardDriver ()
~CrashPS2KeyboardDriver ()=default
Public Member Functions inherited from Interrupts::Handler
virtual void OnInterruptReceived (CPU::SchedulerFrame *Frame)
Private Member Functions
void PS2Wait (bool Read)
void OnInterruptReceived (CPU::TrapFrame *Frame)
Private Attributes
int BackSpaceLimit = 0
char UserInputBuffer [256]
int TimeoutCallNumber = 0
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 22 of file ps2.hpp.
Constructor & Destructor Documentation
CrashPS2KeyboardDriver()
nsa CrashPS2KeyboardDriver::CrashPS2KeyboardDriver ()
Definition at line 145 of file ps2.cpp.
                                                    : Interrupts::Handler(1) /* IRQ1 */
 {
 #define WaitRead PS2Wait(true)
 #define WaitWrite PS2Wait(false)
 #define SetMessageLocation \
     ExPrint("\x1b[%d;%dH", (Display->GetWidth / CrashFontRenderer.CurrentFont->GetInfo().Width) - 1, 0);
     CPU::Interrupts(CPU::Disable);
     /* Dots will be printed at the bottom of the screen as a progress bar. */
     ExPrint("\x1b[%d;%dH", (Display->GetWidth / CrashFontRenderer.CurrentFont->GetInfo().Width) - 2, 0);
 #if defined(a86)
     /* Disable port 1 & 2 */
     {
         /* Disable Port 1 */
         WaitWrite;
         outb(PS2_CMD, PS2_CMD_DISABLE_PORT_1);
         /* Disable Port 2 */
         WaitWrite;
         outb(PS2_CMD, PS2_CMD_DISABLE_PORT_2);
     }
     ExPrint(".");
     /* Flush */
     {
         PS2_STATUSES status;
         int timeout = 0x500;
         while (timeout--)
         {
             status.Raw = inb(PS2_STATUS);
             if (status.OutputBufferFull == 0)
                 break;
             inb(PS2_DATA);
         }
         if (timeout <= 0)
         {
             SetMessageLocation;
             ExPrint(ERROR_COLOR
                     "PS/2 controller timeout (flush;0)\n" DEFAULT_COLOR);
             CPU::Stop();
         }
     }
     ExPrint(".");
     /* Test controller */
     {
         /* Save config */
         WaitWrite;
         outb(PS2_CMD, PS2_CMD_READ_CONFIG);
         WaitRead;
         PS2_CONFIGURATION cfg = {.Raw = inb(PS2_DATA)};
         cfg.Port1Interrupt = 1;
         cfg.Port2Interrupt = 1;
         cfg.Port1Translation = 1;
         /* Update config */
         WaitWrite;
         outb(PS2_CMD, PS2_DATA);
         WaitWrite;
         outb(PS2_DATA, cfg.Raw);
         /* Test PS/2 controller */
         WaitWrite;
         outb(PS2_CMD, PS2_CMD_TEST_CONTROLLER);
         WaitRead;
         uint8_t test = inb(PS2_DATA);
         if (test != PS2_TEST_PASSED)
         {
             if (test == PS2_ACK)
             {
                 trace("PS/2 controller sent ACK to test request.");
                 WaitRead;
                 test = inb(PS2_DATA);
             }
             if (test != PS2_TEST_PASSED)
             {
                 SetMessageLocation;
                 ExPrint(ERROR_COLOR
                         "PS/2 controller self test failed (%#x)\n" DEFAULT_COLOR,
                         test);
                 CPU::Stop();
             }
         }
         /* Restore config */
         WaitWrite;
         outb(PS2_CMD, PS2_DATA);
         WaitWrite;
         outb(PS2_DATA, cfg.Raw);
     }
     ExPrint(".");
     /* Disable scanning; Enable port 1; Set default settings */
     {
         /* Disable scanning */
         outb(PS2_DATA, PS2_KBD_CMD_DISABLE_SCANNING);
         /* Enable Port 1 */
         WaitWrite;
         outb(PS2_CMD, PS2_CMD_ENABLE_PORT_1);
         /* Set default settings */
         outb(PS2_DATA, PS2_KBD_CMD_DEFAULTS);
     }
     ExPrint(".");
     /* Test port 1 */
     {
         WaitWrite;
         outb(PS2_CMD, PS2_CMD_TEST_PORT_1);
         WaitRead;
         uint8_t test = inb(PS2_DATA);
         if (test != 0x00)
         {
             if (test == PS2_KBD_RESP_ACK)
             {
                 trace("PS/2 keyboard sent ACK to test request.");
                 WaitRead;
                 test = inb(PS2_DATA);
             }
             if (test != 0x00)
             {
                 SetMessageLocation;
                 ExPrint(ERROR_COLOR
                         "PS/2 keyboard self test failed (%#x)\n" DEFAULT_COLOR,
                         test);
                 CPU::Stop();
             }
         }
     }
     ExPrint(".");
     /* Configure the controller */
     {
         // /* Read Controller Configuration */
         // WaitWrite;
         // outb(PS2_CMD, PS2_CMD_READ_CONFIG);
         // WaitRead;
         // uint8_t cfg = inb(PS2_DATA);
         // /* Enable Port 1 & Port 1 translation */
         // cfg |= 0b01000001;
         // /* Write Controller Configuration */
         // WaitWrite;
         // outb(PS2_CMD, PS2_CMD_WRITE_CONFIG);
         // WaitWrite;
         // outb(PS2_DATA, cfg);
     }
     ExPrint(".");
     /* Enable port 1; Set scan code; Enable scanning */
     {
         /* Enable Port 1 */
         outb(PS2_CMD, PS2_CMD_ENABLE_PORT_1);
         /* Set scan code set 1 */
         WaitWrite;
         outb(PS2_DATA, PS2_KBD_CMD_SCAN_CODE_SET);
         WaitWrite;
         outb(PS2_DATA, PS2_KBD_SCAN_CODE_SET_2);
         /* Check if we have scan code set 1 */
         WaitWrite;
         outb(PS2_DATA, PS2_KBD_CMD_SCAN_CODE_SET);
         WaitWrite;
         outb(PS2_DATA, PS2_KBD_SCAN_CODE_GET_CURRENT);
         /* Read scan code set */
         WaitRead;
         uint8_t scs = inb(PS2_DATA);
         if (scs == PS2_KBD_RESP_ACK || scs == PS2_KBD_RESP_RESEND)
         {
             if (scs == PS2_KBD_RESP_ACK)
                 trace("PS/2 keyboard sent ACK to scan code set request.");
             if (scs == PS2_KBD_RESP_RESEND)
                 trace("PS/2 keyboard sent RESEND to scan code set request.");
             WaitRead;
             scs = inb(PS2_DATA);
         }
         if (scs != PS2_KBD_SC_SET_2)
         {
             SetMessageLocation;
             ExPrint(WARN_COLOR
                     "PS/2 keyboard scan code set 1 not supported (%#x)\n" DEFAULT_COLOR,
                     scs);
         }
         /* Enable scanning */
         outb(PS2_DATA, PS2_KBD_CMD_ENABLE_SCANNING);
     }
 #ifdef DEBUG
     WaitWrite;
     outb(PS2_CMD, PS2_CMD_READ_CONFIG);
     WaitRead;
     PS2_CONFIGURATION cfg = {.Raw = inb(PS2_DATA)};
     debug("PS2 CONFIG:\nPort1int: %d\nPort2int: %d\nSysFlg: %d\nZ: %d\nP1clk: %d\nP2clk: %d\nP1trans: %d\nz: %d",
           cfg.Port1Interrupt, cfg.Port2Interrupt, cfg.SystemFlag, cfg.Zero0, cfg.Port1Clock, cfg.Port2Clock, cfg.Port1Translation, cfg.Zero1);
 #endif
     ExPrint(".");
 #endif // defined(a86)
     CPU::Interrupts(CPU::Enable);
 }
References CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, debug, DEFAULT_COLOR, CPU::Disable, Display, CPU::Enable, ERROR_COLOR, ExPrint(), Video::Font::GetInfo(), Video::Display::GetWidth, CPU::Interrupts(), PS2_ACK, PS2_CMD, PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_ENABLE_PORT_1, PS2_CMD_READ_CONFIG, PS2_CMD_TEST_CONTROLLER, PS2_CMD_TEST_PORT_1, PS2_DATA, PS2_KBD_CMD_DEFAULTS, PS2_KBD_CMD_DISABLE_SCANNING, PS2_KBD_CMD_ENABLE_SCANNING, PS2_KBD_CMD_SCAN_CODE_SET, PS2_KBD_RESP_ACK, PS2_KBD_RESP_RESEND, PS2_KBD_SC_SET_2, PS2_KBD_SCAN_CODE_GET_CURRENT, PS2_KBD_SCAN_CODE_SET_2, PS2_STATUS, PS2_TEST_PASSED, PS2_STATUSES::Raw, PS2_CONFIGURATION::Raw, SetMessageLocation, CPU::Stop(), trace, WaitRead, WaitWrite, WARN_COLOR, and Video::FontInfo::Width.
~CrashPS2KeyboardDriver()
CrashPS2KeyboardDriver::~CrashPS2KeyboardDriver () default
Member Function Documentation
OnInterruptReceived()
nsa void CrashPS2KeyboardDriver::OnInterruptReceived (CPU::TrapFrame * Frame) private virtual
Reimplemented from Interrupts::Handler.
Definition at line 363 of file ps2.cpp.
 {
 #if defined(a86)
     uint8_t scanCode = inb(PS2_DATA);
     if (scanCode == KEY_D_TAB ||
         scanCode == KEY_D_LCTRL ||
         scanCode == KEY_D_LALT ||
         scanCode == KEY_U_LCTRL ||
         scanCode == KEY_U_LALT)
         return;
     switch (scanCode)
     {
     case KEY_D_UP:
     case KEY_D_LEFT:
     case KEY_D_RIGHT:
     case KEY_D_DOWN:
         ArrowInput(scanCode);
         break;
     default:
         break;
     }
     int key = GetLetterFromScanCode(scanCode);
     if (key != KEY_INVALID)
     {
         if (key == KEY_D_BACKSPACE)
         {
             if (BackSpaceLimit > 0)
             {
                 char keyBuf[5] = {'\b', '\x1b', '[', 'K', '\0'};
                 ExPrint(keyBuf);
                 backspace(UserInputBuffer);
                 BackSpaceLimit--;
             }
         }
         else if (key == '\n')
         {
             UserInput(UserInputBuffer);
             BackSpaceLimit = 0;
             UserInputBuffer[0] = '\0';
         }
         else
         {
             append(UserInputBuffer, s_cst(char, key));
             char keyBuf[2] = {(char)key, '\0'};
             ExPrint(keyBuf);
             BackSpaceLimit++;
         }
         Display->UpdateBuffer(); /* Update as we type. */
     }
 #endif // a64 || a32
 }
References append(), ArrowInput(), backspace(), BackSpaceLimit, Display, ExPrint(), GetLetterFromScanCode(), KEY_D_BACKSPACE, KEY_D_DOWN, KEY_D_LALT, KEY_D_LCTRL, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_TAB, KEY_D_UP, KEY_INVALID, KEY_U_LALT, KEY_U_LCTRL, PS2_DATA, Video::Display::UpdateBuffer(), UserInput(), and UserInputBuffer.
PS2Wait()
nsa void CrashPS2KeyboardDriver::PS2Wait (bool Read) private
Definition at line 108 of file ps2.cpp.
 {
 #if defined(a86)
     TimeoutCallNumber++;
     int timeout = 100000;
     PS2_STATUSES status = {.Raw = inb(PS2_STATUS)};
     while (timeout--)
     {
         if (!Output)
         {
             if (status.OutputBufferFull == 0)
                 return;
         }
         else
         {
             if (status.InputBufferFull == 0)
                 return;
         }
         status.Raw = inb(PS2_STATUS);
     }
     ExPrint(WARN_COLOR "PS/2 controller timeout (%s;%d)\n" DEFAULT_COLOR,
             Output ? "output" : "input", TimeoutCallNumber);
 #endif // a86
 }
References DEFAULT_COLOR, ExPrint(), PS2_STATUS, PS2_STATUSES::Raw, and WARN_COLOR.
Field Documentation
BackSpaceLimit
int CrashPS2KeyboardDriver::BackSpaceLimit = 0 private
Definition at line 28 of file ps2.hpp.
Referenced by OnInterruptReceived().
TimeoutCallNumber
int CrashPS2KeyboardDriver::TimeoutCallNumber = 0 private
Definition at line 30 of file ps2.hpp.
UserInputBuffer
char CrashPS2KeyboardDriver::UserInputBuffer[256] private
Definition at line 29 of file ps2.hpp.
Referenced by OnInterruptReceived().
The documentation for this class was generated from the following files:
Kernel/core/panic/kbd/ps2.hpp
Kernel/core/panic/kbd/ps2.cpp