Fennix: Userspace/apps/base/busybox/libbb/parse_config.c File Reference
parse_config.c File Reference
#include "libbb.h"
Functions
parser_t *FAST_FUNC config_open2 (const char *filename, FILE *FAST_FUNC(*fopen_func)(const char *path))
parser_t *FAST_FUNC config_open (const char *filename)
void FAST_FUNC config_close (parser_t *parser)
static int get_line_with_continuation (parser_t *parser)
int FAST_FUNC config_read (parser_t *parser, char **tokens, unsigned flags, const char *delims)
Function Documentation
config_close()
void FAST_FUNC config_close (parser_t * parser)
Definition at line 87 of file parse_config.c.
 {
     if (parser) {
         if (PARSE_KEEP_COPY) /* compile-time constant */
             free(parser->data);
         fclose(parser->fp);
         free(parser->line);
         free(parser->nline);
         free(parser);
     }
 }
References fclose(), free, PARSE_KEEP_COPY, and parser.
Referenced by bootchartd_main(), close_config_file(), config_file_action(), do_sethostname(), fileAction(), init(), load_crontab(), load_modules_dep(), lsmod_main(), man_main(), modinfo_main(), modprobe_main(), nameif_main(), ntp_init(), parse_conf_file(), parse_inittab(), parse_map_file(), read_config(), reopen_config_file(), rfkill_main(), rtnl_tab_initialize(), and sysctl_handle_preload_file().
config_open()
parser_t* FAST_FUNC config_open (const char * filename)
Definition at line 82 of file parse_config.c.
 {
     return config_open2(filename, fopen_or_warn_stdin);
 }
References config_open2(), filename, and fopen_or_warn_stdin().
Referenced by load_crontab(), lsmod_main(), nameif_main(), ntp_init(), parse_conf_file(), read_config(), reopen_config_file(), and sysctl_handle_preload_file().
config_open2()
parser_t* FAST_FUNC config_open2 (const char * filename, FILE *FAST_FUNC(*)(const char *path) fopen_func)
Definition at line 69 of file parse_config.c.
 {
     FILE* fp;
     parser_t *parser;
     fp = fopen_func(filename);
     if (!fp)
         return NULL;
     parser = xzalloc(sizeof(*parser));
     parser->fp = fp;
     return parser;
 }
References filename, NULL, parser, and xzalloc().
Referenced by bootchartd_main(), config_file_action(), config_open(), do_sethostname(), fileAction(), init(), load_modules_dep(), man_main(), modinfo_main(), modprobe_main(), nameif_main(), parse_conf_file(), parse_inittab(), parse_map_file(), rfkill_main(), and rtnl_tab_initialize().
config_read()
int FAST_FUNC config_read (parser_t * parser, char ** tokens, unsigned flags, const char * delims)
Definition at line 163 of file parse_config.c.
 {
     char *line, *p;
     int ntokens, mintokens;
     int t;
     char alt_comment_ch;
     if (!parser)
         return 0;
     alt_comment_ch = '\0';
     if (flags & PARSE_ALT_COMMENTS)
         alt_comment_ch = *delims++;
     ntokens = (uint8_t)flags;
     mintokens = (uint8_t)(flags >> 8);
  again:
     memset(tokens, 0, sizeof(tokens[0]) * ntokens);
     /* Read one line (handling continuations with backslash) */
     if (get_line_with_continuation(parser) < 0)
         return 0;
     line = parser->line;
     /* Skip token in the start of line? */
     if (flags & PARSE_TRIM)
         line += strspn(line, delims + 1);
     p = line;
     if (flags & PARSE_WS_COMMENTS)
         p = skip_whitespace(p);
     if (p[0] == '\0' || p[0] == delims[0] || p[0] == alt_comment_ch)
         goto again;
     if (flags & PARSE_KEEP_COPY) {
         free(parser->data);
         parser->data = xstrdup(line);
     }
     /* Tokenize the line */
     t = 0;
     do {
         /* Pin token */
         tokens[t] = line;
         /* Combine remaining arguments? */
         if ((t != (ntokens-1)) || !(flags & PARSE_GREEDY)) {
             /* Vanilla token, find next delimiter */
             line += strcspn(line, (delims[0] && (flags & PARSE_EOL_COMMENTS)) ? delims : delims + 1);
         } else {
             /* Combining, find comment char if any */
             line = strchrnul(line, (flags & PARSE_EOL_COMMENTS) ? delims[0] : '\0');
             /* Trim any extra delimiters from the end */
             if (flags & PARSE_TRIM) {
                 while (strchr(delims + 1, line[-1]) != NULL)
                     line--;
             }
         }
         /* Token not terminated? */
         if ((flags & PARSE_EOL_COMMENTS) && *line == delims[0])
             *line = '\0'; /* ends with comment char: this line is done */
         else if (*line != '\0')
             *line++ = '\0'; /* token is done, continue parsing line */
 #if 0 /* unused so far */
         if (flags & PARSE_ESCAPE) {
             strcpy_and_process_escape_sequences(tokens[t], tokens[t]);
         }
 #endif
         /* Skip possible delimiters */
         if (flags & PARSE_COLLAPSE)
             line += strspn(line, delims + 1);
         t++;
     } while (*line && *line != delims[0] && t < ntokens);
     if (t < mintokens) {
         bb_error_msg("bad line %u: %d tokens found, %d needed",
                 parser->lineno, t, mintokens);
         if (flags & PARSE_MIN_DIE)
             xfunc_die();
         goto again;
     }
     return t;
 }
References bb_error_msg(), flags, free, get_line_with_continuation(), line, memset, NULL, p, PARSE_ALT_COMMENTS, PARSE_COLLAPSE, PARSE_EOL_COMMENTS, PARSE_GREEDY, PARSE_KEEP_COPY, PARSE_MIN_DIE, PARSE_TRIM, PARSE_WS_COMMENTS, parser, skip_whitespace(), strchr(), strchrnul(), strcpy_and_process_escape_sequences(), strcspn(), strspn(), t, xfunc_die(), and xstrdup().
get_line_with_continuation()
static int get_line_with_continuation (parser_t * parser) static
Definition at line 104 of file parse_config.c.
 {
     ssize_t len, nlen;
     char *line;
     len = getline(&parser->line, &parser->line_alloc, parser->fp);
     if (len <= 0)
         return len;
     line = parser->line;
     for (;;) {
         parser->lineno++;
         if (line[len - 1] == '\n')
             len--;
         if (len == 0 || line[len - 1] != '\\')
             break;
         len--;
         nlen = getline(&parser->nline, &parser->nline_alloc, parser->fp);
         if (nlen <= 0)
             break;
         if (parser->line_alloc < len + nlen + 1) {
             parser->line_alloc = len + nlen + 1;
             line = parser->line = xrealloc(line, parser->line_alloc);
         }
         memcpy(&line[len], parser->nline, nlen);
         len += nlen;
     }
     line[len] = '\0';
     return len;
 }
References getline(), len, line, memcpy, parser, and xrealloc.
Referenced by config_read().