Fennix Userspace: Userspace/apps/base/bash/examples/loadables/uname.c File Reference
uname.c File Reference
#include <config.h>
#include <stdio.h>
#include "bashtypes.h"
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Data Structures
struct utsname
Macros
#define FLAG_SYSNAME 0x01 /* -s */
#define FLAG_NODENAME 0x02 /* -n */
#define FLAG_RELEASE 0x04 /* -r */
#define FLAG_VERSION 0x08 /* -v */
#define FLAG_MACHINE 0x10 /* -m, -p */
#define FLAG_ALL 0x1f
Functions
static void uprint ()
int uname_builtin (WORD_LIST *list)
static void uprint (int flag, char *info)
Variables
int errno
static int uname_flags
char * uname_doc []
struct builtin uname_struct
Data Structure Documentation
utsname
struct utsname
Definition at line 34 of file uname.c.
Data Fields
char __domainname[65]
char domainname[65]
char machine[32]
char nodename[32]
char release[32]
char sysname[32]
char version[32]
Macro Definition Documentation
FLAG_ALL
#define FLAG_ALL 0x1f
Definition at line 56 of file uname.c.
FLAG_MACHINE
#define FLAG_MACHINE 0x10 /* -m, -p */
Definition at line 54 of file uname.c.
FLAG_NODENAME
#define FLAG_NODENAME 0x02 /* -n */
Definition at line 51 of file uname.c.
FLAG_RELEASE
#define FLAG_RELEASE 0x04 /* -r */
Definition at line 52 of file uname.c.
FLAG_SYSNAME
#define FLAG_SYSNAME 0x01 /* -s */
Definition at line 50 of file uname.c.
FLAG_VERSION
#define FLAG_VERSION 0x08 /* -v */
Definition at line 53 of file uname.c.
Function Documentation
uname_builtin()
int uname_builtin (WORD_LIST * list)
Definition at line 67 of file uname.c.
 {
   int opt, r;
   struct utsname uninfo;
   uname_flags = 0;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "amnprsv")) != -1)
     {
       switch (opt)
     {
     case 'a':
       uname_flags |= FLAG_ALL;
       break;
     case 'm':
     case 'p':
       uname_flags |= FLAG_MACHINE;
       break;
     case 'n':
       uname_flags |= FLAG_NODENAME;
       break;
     case 'r':
       uname_flags |= FLAG_RELEASE;
       break;
     case 's':
       uname_flags |= FLAG_SYSNAME;
       break;
     case 'v':
       uname_flags |= FLAG_VERSION;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   if (uname_flags == 0)
     uname_flags = FLAG_SYSNAME;
   /* Only ancient systems will not have uname(2). */
 #ifdef HAVE_UNAME
   if (uname (&uninfo) < 0)
     {
       builtin_error ("cannot get system name: %s", strerror (errno));
       return (EXECUTION_FAILURE);
     }
 #else
   builtin_error ("cannot get system information: uname(2) not available");
   return (EXECUTION_FAILURE);
 #endif
   uprint (FLAG_SYSNAME, uninfo.sysname);
   uprint (FLAG_NODENAME, uninfo.nodename);
   uprint (FLAG_RELEASE, uninfo.release);
   uprint (FLAG_VERSION, uninfo.version);
   uprint (FLAG_MACHINE, uninfo.machine);
   return (EXECUTION_SUCCESS);
 }
References builtin_error(), builtin_usage(), CASE_HELPOPT, errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, FLAG_ALL, FLAG_MACHINE, FLAG_NODENAME, FLAG_RELEASE, FLAG_SYSNAME, FLAG_VERSION, internal_getopt(), loptend, utsname::machine, utsname::nodename, r, utsname::release, reset_internal_getopt(), strerror(), utsname::sysname, uname(), uname_flags, uprint(), and utsname::version.
uprint() [1/2]
static void uprint () static
Referenced by uname_builtin().
uprint() [2/2]
static void uprint (int flag, char * info) static
Definition at line 137 of file uname.c.
 {
   if (uname_flags & flag)
     {
       uname_flags &= ~flag;
       printf ("%s%c", info, uname_flags ? ' ' : '\n');
     }
 }
References printf(), and uname_flags.
Variable Documentation
errno
int errno extern
Referenced by uname_builtin().
uname_doc
char* uname_doc[]
Initial value:
= {
    "Display system information.",
    "",
    "Display information about the system hardware and OS.",
    (char *)NULL
}
Definition at line 148 of file uname.c.
uname_flags
int uname_flags static
Definition at line 64 of file uname.c.
Referenced by uname_builtin(), and uprint().
uname_struct
struct builtin uname_struct
Initial value:
= {
    "uname",
    uname_builtin,
    BUILTIN_ENABLED,
    uname_doc,
    "uname [-amnrsv]",
    0
}
Definition at line 148 of file uname.c.