Fennix Userspace: Userspace/musl/src/stdio/ungetwc.c File Reference
ungetwc.c File Reference
#include "stdio_impl.h"
#include "locale_impl.h"
#include <wchar.h>
#include <limits.h>
#include <ctype.h>
#include <string.h>
Functions
wint_t ungetwc (wint_t c, FILE *f)
Function Documentation
ungetwc()
wint_t ungetwc (wint_t c, FILE * f)
Definition at line 8 of file ungetwc.c.
 {
     unsigned char mbc[MB_LEN_MAX];
     int l;
     locale_t *ploc = &CURRENT_LOCALE, loc = *ploc;
     FLOCK(f);
     if (f->mode <= 0) fwide(f, 1);
     *ploc = f->locale;
     if (!f->rpos) __toread(f);
     if (!f->rpos || c == WEOF || (l = wcrtomb((void *)mbc, c, 0)) < 0 ||
         f->rpos < f->buf - UNGET + l) {
         FUNLOCK(f);
         *ploc = loc;
         return WEOF;
     }
     if (isascii(c)) *--f->rpos = c;
     else memcpy(f->rpos -= l, mbc, l);
     f->flags &= ~F_EOF;
     FUNLOCK(f);
     *ploc = loc;
     return c;
 }
References __toread(), _IO_FILE::buf, CURRENT_LOCALE, f, F_EOF, _IO_FILE::flags, FLOCK, FUNLOCK, fwide(), isascii(), _IO_FILE::locale, MB_LEN_MAX, memcpy(), _IO_FILE::mode, _IO_FILE::rpos, UNGET, wcrtomb(), and WEOF.