Fennix Userspace: Userspace/musl/include/fnmatch.h File Reference
fnmatch.h File Reference
Macros
#define FNM_PATHNAME 0x1
#define FNM_NOESCAPE 0x2
#define FNM_PERIOD 0x4
#define FNM_LEADING_DIR 0x8
#define FNM_CASEFOLD 0x10
#define FNM_FILE_NAME FNM_PATHNAME
#define FNM_NOMATCH 1
#define FNM_NOSYS (-1)
Functions
int fnmatch (const char *, const char *, int)
Macro Definition Documentation
FNM_CASEFOLD
#define FNM_CASEFOLD 0x10
Definition at line 12 of file fnmatch.h.
FNM_FILE_NAME
#define FNM_FILE_NAME FNM_PATHNAME
Definition at line 13 of file fnmatch.h.
FNM_LEADING_DIR
#define FNM_LEADING_DIR 0x8
Definition at line 11 of file fnmatch.h.
FNM_NOESCAPE
#define FNM_NOESCAPE 0x2
Definition at line 9 of file fnmatch.h.
FNM_NOMATCH
#define FNM_NOMATCH 1
Definition at line 15 of file fnmatch.h.
FNM_NOSYS
#define FNM_NOSYS (-1)
Definition at line 16 of file fnmatch.h.
FNM_PATHNAME
#define FNM_PATHNAME 0x1
Definition at line 8 of file fnmatch.h.
FNM_PERIOD
#define FNM_PERIOD 0x4
Definition at line 10 of file fnmatch.h.
Function Documentation
fnmatch()
int fnmatch (const char * pat, const char * str, int flags)
Definition at line 298 of file fnmatch.c.
 {
     const char *s, *p;
     size_t inc;
     int c;
     if (flags & FNM_PATHNAME) for (;;) {
         for (s=str; *s && *s!='/'; s++);
         for (p=pat; (c=pat_next(p, -1, &inc, flags))!=END && c!='/'; p+=inc);
         if (c!=*s && (!*s || !(flags & FNM_LEADING_DIR)))
             return FNM_NOMATCH;
         if (fnmatch_internal(pat, p-pat, str, s-str, flags))
             return FNM_NOMATCH;
         if (!c) return 0;
         str = s+1;
         pat = p+inc;
     } else if (flags & FNM_LEADING_DIR) {
         for (s=str; *s; s++) {
             if (*s != '/') continue;
             if (!fnmatch_internal(pat, -1, str, s-str, flags))
                 return 0;
         }
     }
     return fnmatch_internal(pat, -1, str, -1, flags);
 }
References c, END, flags, FNM_LEADING_DIR, FNM_NOMATCH, FNM_PATHNAME, fnmatch_internal(), p, pat, pat_next(), s, and str.
Referenced by binop(), config_file_action(), data_extract_all_prefix(), do_glob(), find_list_entry(), find_list_entry2(), history_search_internal(), ifupdown_main(), ipaddr_list_or_flush(), list_packages(), modinfo_main(), modprobe_main(), print_addrinfo(), print_linkinfo(), run_list(), and scan_and_match().