Fennix Userspace: Userspace/musl/src/stdio/__fmodeflags.c File Reference
__fmodeflags.c File Reference
#include <fcntl.h>
#include <string.h>
Functions
int __fmodeflags (const char *mode)
Function Documentation
__fmodeflags()
int __fmodeflags (const char * mode)
Definition at line 4 of file __fmodeflags.c.
 {
     int flags;
     if (strchr(mode, '+')) flags = O_RDWR;
     else if (*mode == 'r') flags = O_RDONLY;
     else flags = O_WRONLY;
     if (strchr(mode, 'x')) flags |= O_EXCL;
     if (strchr(mode, 'e')) flags |= O_CLOEXEC;
     if (*mode != 'r') flags |= O_CREAT;
     if (*mode == 'w') flags |= O_TRUNC;
     if (*mode == 'a') flags |= O_APPEND;
     return flags;
 }
References flags, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, and strchr().
Referenced by fopen(), and freopen().