Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/unsafe_symlink_target.c File Reference
unsafe_symlink_target.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
void FAST_FUNC create_or_remember_link (llist_t **link_placeholders, const char *target, const char *linkname, int hard_link)
void FAST_FUNC create_links_from_list (llist_t *list)
Function Documentation
create_links_from_list()
void FAST_FUNC create_links_from_list (llist_t * list)
Definition at line 27 of file unsafe_symlink_target.c.
 {
     while (list) {
         char *target;
         target = list->data + 1 + strlen(list->data + 1) + 1;
         if ((*list->data ? link : symlink) (target, list->data + 1)) {
             /* shared message */
             bb_error_msg_and_die("can't create %slink '%s' to '%s'",
                 *list->data ? "hard" : "sym",
                 list->data + 1, target
             );
         }
         list = list->link;
     }
 }
References bb_error_msg_and_die(), link(), list(), strlen(), symlink(), and target.
Referenced by get_header_ar(), tar_main(), and unzip_main().
create_or_remember_link()
void FAST_FUNC create_or_remember_link (llist_t ** link_placeholders, const char * target, const char * linkname, int hard_link)
Definition at line 8 of file unsafe_symlink_target.c.
 {
     if (hard_link || target[0] == '/' || strstr(target, "..")) {
         llist_add_to_end(link_placeholders,
             xasprintf("%c%s%c%s", hard_link, linkname, '\0', target)
         );
         return;
     }
     if (symlink(target, linkname) != 0) {
         /* shared message */
         bb_perror_msg_and_die("can't create %slink '%s' to '%s'",
             "sym", linkname, target
         );
     }
 }
References bb_perror_msg_and_die(), llist_add_to_end(), strstr(), symlink(), target, and xasprintf().
Referenced by data_extract_all().