Fennix Userspace: Userspace/apps/base/busybox/scripts/kconfig/lxdialog/lxdialog.c File Reference
lxdialog.c File Reference
#include "dialog.h"
Data Structures
struct Mode
Typedefs
typedef int() jumperFn(const char *title, int argc, const char *const *argv)
Functions
static void Usage (const char *name)
int main (int argc, const char *const *argv)
int j_menu (const char *t, int ac, const char *const *av)
int j_radiolist (const char *t, int ac, const char *const *av)
int j_textbox (const char *t, int ac, const char *const *av)
int j_yesno (const char *t, int ac, const char *const *av)
int j_inputbox (const char *t, int ac, const char *const *av)
int j_msgbox (const char *t, int ac, const char *const *av)
int j_infobox (const char *t, int ac, const char *const *av)
Variables
jumperFn j_menu
jumperFn j_radiolist
jumperFn j_yesno
jumperFn j_textbox
jumperFn j_inputbox
jumperFn j_msgbox
jumperFn j_infobox
static struct Mode modes []
static struct Mode * modePtr
Data Structure Documentation
Mode
struct Mode
Definition at line 28 of file lxdialog.c.
Data Fields
int argmax
int argmin
int argmod
jumperFn * jumper
char * name
Typedef Documentation
jumperFn
typedef int() jumperFn(const char *title, int argc, const char *const *argv)
Definition at line 26 of file lxdialog.c.
Function Documentation
j_infobox()
int j_infobox (const char * t, int ac, const char *const * av)
Definition at line 201 of file lxdialog.c.
 {
     return dialog_msgbox(t, av[2], atoi(av[3]), atoi(av[4]), 0);
 }
References atoi(), dialog_msgbox(), and t.
j_inputbox()
int j_inputbox (const char * t, int ac, const char *const * av)
Definition at line 187 of file lxdialog.c.
 {
     int ret = dialog_inputbox(t, av[2], atoi(av[3]), atoi(av[4]),
                   ac == 6 ? av[5] : (char *)NULL);
     if (ret == 0)
         fprintf(stderr, "%s", dialog_input_result);
     return ret;
 }
References atoi(), dialog_input_result, dialog_inputbox(), fprintf(), NULL, stderr, and t.
j_menu()
int j_menu (const char * t, int ac, const char *const * av)
Definition at line 165 of file lxdialog.c.
 {
     return dialog_menu(t, av[2], atoi(av[3]), atoi(av[4]),
                atoi(av[5]), av[6], (ac - 6) / 2, av + 7);
 }
References atoi(), dialog_menu(), and t.
j_msgbox()
int j_msgbox (const char * t, int ac, const char *const * av)
Definition at line 196 of file lxdialog.c.
 {
     return dialog_msgbox(t, av[2], atoi(av[3]), atoi(av[4]), 1);
 }
References atoi(), dialog_msgbox(), and t.
j_radiolist()
int j_radiolist (const char * t, int ac, const char *const * av)
Definition at line 171 of file lxdialog.c.
 {
     return dialog_checklist(t, av[2], atoi(av[3]), atoi(av[4]),
                 atoi(av[5]), (ac - 6) / 3, av + 6);
 }
References atoi(), dialog_checklist(), and t.
j_textbox()
int j_textbox (const char * t, int ac, const char *const * av)
Definition at line 177 of file lxdialog.c.
 {
     return dialog_textbox(t, av[2], atoi(av[3]), atoi(av[4]));
 }
References atoi(), dialog_textbox(), and t.
j_yesno()
int j_yesno (const char * t, int ac, const char *const * av)
Definition at line 182 of file lxdialog.c.
 {
     return dialog_yesno(t, av[2], atoi(av[3]), atoi(av[4]));
 }
References atoi(), dialog_yesno(), and t.
main()
int main (int argc , const char *const * argv)
Definition at line 54 of file lxdialog.c.
 {
     int offset = 0, opt_clear = 0, end_common_opts = 0, retval;
     const char *title = NULL;
 #ifdef LOCALE
     (void)setlocale(LC_ALL, "");
 #endif
 #ifdef TRACE
     trace(TRACE_CALLS | TRACE_UPDATE);
 #endif
     if (argc < 2) {
         Usage(argv[0]);
         exit(-1);
     }
     while (offset < argc - 1 && !end_common_opts) { /* Common options */
         if (!strcmp(argv[offset + 1], "--title")) {
             if (argc - offset < 3 || title != NULL) {
                 Usage(argv[0]);
                 exit(-1);
             } else {
                 title = argv[offset + 2];
                 offset += 2;
             }
         } else if (!strcmp(argv[offset + 1], "--backtitle")) {
             if (backtitle != NULL) {
                 Usage(argv[0]);
                 exit(-1);
             } else {
                 backtitle = argv[offset + 2];
                 offset += 2;
             }
         } else if (!strcmp(argv[offset + 1], "--clear")) {
             if (opt_clear) {    /* Hey, "--clear" can't appear twice! */
                 Usage(argv[0]);
                 exit(-1);
             } else if (argc == 2) { /* we only want to clear the screen */
                 init_dialog();
                 refresh();  /* init_dialog() will clear the screen for us */
                 end_dialog();
                 return 0;
             } else {
                 opt_clear = 1;
                 offset++;
             }
         } else      /* no more common options */
             end_common_opts = 1;
     }
     if (argc - 1 == offset) {   /* no more options */
         Usage(argv[0]);
         exit(-1);
     }
     /* use a table to look for the requested mode, to avoid code duplication */
     for (modePtr = modes; modePtr->name; modePtr++) /* look for the mode */
         if (!strcmp(argv[offset + 1], modePtr->name))
             break;
     if (!modePtr->name)
         Usage(argv[0]);
     if (argc - offset < modePtr->argmin)
         Usage(argv[0]);
     if (modePtr->argmax && argc - offset > modePtr->argmax)
         Usage(argv[0]);
     init_dialog();
     retval = (*(modePtr->jumper)) (title, argc - offset, argv + offset);
     if (opt_clear) {    /* clear screen before exit */
         attr_clear(stdscr, LINES, COLS, screen_attr);
         refresh();
     }
     end_dialog();
     exit(retval);
 }
References argc, Mode::argmax, Mode::argmin, argv, attr_clear(), backtitle, end_dialog(), exit(), init_dialog(), Mode::jumper, LC_ALL, modePtr, modes, Mode::name, NULL, offset, refresh(), retval, screen_attr, setlocale, strcmp, title, trace, and Usage().
Usage()
static void Usage (const char * name) static
Definition at line 137 of file lxdialog.c.
 {
     fprintf(stderr, "\
 \ndialog, by Savio Lam (lam836@cs.cuhk.hk).\
 \n  patched by Stuart Herbert (S.Herbert@shef.ac.uk)\
 \n  modified/gutted for use as a Linux kernel config tool by \
 \n  William Roadcap (roadcapw@cfw.com)\
 \n\
 \n* Display dialog boxes from shell scripts *\
 \n\
 \nUsage: %s --clear\
 \n       %s [--title <title>] [--backtitle <backtitle>] --clear <Box options>\
 \n\
 \nBox options:\
 \n\
 \n  --menu      <text> <height> <width> <menu height> <tag1> <item1>...\
 \n  --radiolist <text> <height> <width> <list height> <tag1> <item1> <status1>...\
 \n  --textbox   <file> <height> <width>\
 \n  --inputbox  <text> <height> <width> [<init>]\
 \n  --yesno     <text> <height> <width>\
 \n", name, name);
     exit(-1);
 }
References exit(), fprintf(), Mode::name, and stderr.
Referenced by main().
Variable Documentation
j_infobox
jumperFn j_infobox
Definition at line 35 of file lxdialog.c.
j_inputbox
jumperFn j_inputbox
Definition at line 34 of file lxdialog.c.
j_menu
jumperFn j_menu
Definition at line 34 of file lxdialog.c.
j_msgbox
jumperFn j_msgbox
Definition at line 35 of file lxdialog.c.
j_radiolist
jumperFn j_radiolist
Definition at line 34 of file lxdialog.c.
j_textbox
jumperFn j_textbox
Definition at line 34 of file lxdialog.c.
j_yesno
jumperFn j_yesno
Definition at line 34 of file lxdialog.c.
modePtr
struct Mode* modePtr static
Definition at line 48 of file lxdialog.c.
Referenced by main().
modes
struct Mode modes[] static
Initial value:
= {
    {"--menu", 9, 0, 3, j_menu},
    {"--radiolist", 9, 0, 3, j_radiolist},
    {"--yesno", 5, 5, 1, j_yesno},
    {"--textbox", 5, 5, 1, j_textbox},
    {"--inputbox", 5, 6, 1, j_inputbox},
    {"--msgbox", 5, 5, 1, j_msgbox},
    {"--infobox", 5, 5, 1, j_infobox},
    {NULL, 0, 0, 0, NULL}
}
Definition at line 35 of file lxdialog.c.
Referenced by main().