Fennix Kernel: Video::Display Class Reference
Video::Display Class Reference
#include <display.hpp>
Public Member Functions
Font * GetCurrentFont ()
void SetCurrentFont (Font *Font)
uint16_t GetBitsPerPixel ()
size_t GetPitch ()
void CreateBuffer (uint32_t Width, uint32_t Height, int Index)
Create a new buffer.
void SetBuffer (int Index)
ScreenBuffer * GetBuffer (int Index)
void ClearBuffer (int Index)
void DeleteBuffer (int Index)
void SetBrightness (int Value, int Index)
void SetBufferCursor (int Index, uint32_t X, uint32_t Y)
void GetBufferCursor (int Index, uint32_t *X, uint32_t *Y)
void SetPixel (uint32_t X, uint32_t Y, uint32_t Color, int Index)
uint32_t GetPixel (uint32_t X, uint32_t Y, int Index)
void Scroll (int Index, int Lines)
void SetDoNotScroll (bool Value, int Index)
char Print (char Char, int Index, bool WriteToUART=false)
void DrawString (const char *String, uint32_t X, uint32_t Y, int Index, bool WriteToUART=false)
Display (BootInfo::FramebufferInfo Info, bool LoadDefaultFont=true)
~Display ()
Private Attributes
BootInfo::FramebufferInfo framebuffer
Font * CurrentFont = nullptr
ScreenBuffer Buffers [256]
bool ColorIteration = false
int ColorPickerIteration = 0
Detailed Description
Definition at line 108 of file display.hpp.
Constructor & Destructor Documentation
Display()
Video::Display::Display (BootInfo::FramebufferInfo Info, bool LoadDefaultFont = true)
Definition at line 418 of file Display.cpp.
     {
         this->framebuffer = Info;
         if (LoadDefaultFont)
         {
             this->CurrentFont = new Font(&_binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_start, &_binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_end, FontType::PCScreenFont2);
 #ifdef DEBUG
             FontInfo Info = this->CurrentFont->GetInfo();
             debug("Font loaded: %dx%d %s",
                   Info.Width, Info.Height,
                   Info.Type == FontType::PCScreenFont1 ? "PSF1" : "PSF2");
 #endif
         }
         this->CreateBuffer(Info.Width, Info.Height, 0);
     }
References _binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_end, _binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_start, CreateBuffer(), CurrentFont, debug, framebuffer, Video::Font::GetInfo(), Info, Video::PCScreenFont1, Video::PCScreenFont2, BootInfo::FramebufferInfo::Width, and Video::FontInfo::Width.
~Display()
Video::Display::~Display ()
Definition at line 434 of file Display.cpp.
     {
         debug("Destructor called");
         this->ClearBuffer(0);
         this->SetBuffer(0);
         for (int i = 0; i < s_cst(int, sizeof(this->Buffers) / sizeof(this->Buffers[0])); i++)
         {
             if (this->Buffers[i].Checksum == 0xBBFFE515A117E)
                 this->DeleteBuffer(i);
         }
     }
References Buffers, Checksum, ClearBuffer(), debug, DeleteBuffer(), and SetBuffer().
Member Function Documentation
ClearBuffer()
void Video::Display::ClearBuffer (int Index)
Definition at line 86 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         memset(this->Buffers[Index].Buffer, 0, this->Buffers[Index].Size);
     }
References Buffers, Checksum, debug, memset(), Size, and unlikely.
Referenced by ~Display().
CreateBuffer()
void Video::Display::CreateBuffer (uint32_t Width, uint32_t Height, int Index)
Create a new buffer.
This function creates a new buffer.
For
See also
Width and
Height. Both values must be greater than 0.
Note
Some indexes are reserved for the kernel. 0 - Main buffer 1 - Loading screen buffer 200 - GUI buffer 250 - Empty (crash screen) 251 - Console (crash screen) 252 - Tasks (crash screen) 253 - Frames (crash screen) 254 - Details (crash screen) 255 - Main (crash screen)
Parameters
Width The width of the buffer
Height The height of the buffer
Index The index of the buffer (0-255)
Definition at line 36 of file Display.cpp.
     {
         if (Width == 0 || Height == 0)
         {
             Width = this->framebuffer.Width;
             Height = this->framebuffer.Height;
             debug("Buffer %d created with default size (%d, %d)", Index, Width, Height);
         }
         if (this->Buffers[Index].Checksum == 0xBBFFE515A117E)
         {
             warn("Buffer %d already exists, skipping creation", Index);
             return;
         }
         size_t Size = this->framebuffer.Pitch * Height;
         this->Buffers[Index].Buffer = KernelAllocator.RequestPages(TO_PAGES(Size + 1));
         memset(this->Buffers[Index].Buffer, 0, Size);
         this->Buffers[Index].Width = Width;
         this->Buffers[Index].Height = Height;
         this->Buffers[Index].Size = Size;
         this->Buffers[Index].Color = 0xFFFFFF;
         this->Buffers[Index].CursorX = 0;
         this->Buffers[Index].CursorY = 0;
         this->Buffers[Index].Brightness = 100;
         this->Buffers[Index].Checksum = 0xBBFFE515A117E;
         debug("Buffer %d created", Index);
     }
References Video::ScreenBuffer::Brightness, Video::ScreenBuffer::Buffer, Buffers, Checksum, Video::ScreenBuffer::Checksum, Video::ScreenBuffer::Color, Video::ScreenBuffer::CursorX, Video::ScreenBuffer::CursorY, debug, framebuffer, BootInfo::FramebufferInfo::Height, Video::ScreenBuffer::Height, KernelAllocator, memset(), BootInfo::FramebufferInfo::Pitch, Size, Video::ScreenBuffer::Size, warn, BootInfo::FramebufferInfo::Width, and Video::ScreenBuffer::Width.
Referenced by Display(), and Main().
DeleteBuffer()
void Video::Display::DeleteBuffer (int Index)
Definition at line 97 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         KernelAllocator.FreePages(this->Buffers[Index].Buffer, TO_PAGES(this->Buffers[Index].Size + 1));
         this->Buffers[Index].Buffer = nullptr;
         this->Buffers[Index].Checksum = 0;
         debug("Buffer %d deleted", Index);
     }
References Video::ScreenBuffer::Buffer, Buffers, Checksum, Video::ScreenBuffer::Checksum, debug, KernelAllocator, Size, and unlikely.
Referenced by ~Display().
DrawString()
void Video::Display::DrawString (const char * String, uint32_t X, uint32_t Y, int Index, bool WriteToUART = false)
Definition at line 403 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         this->Buffers[Index].CursorX = X;
         this->Buffers[Index].CursorY = Y;
         for (int i = 0; String[i] != '\0'; i++)
             this->Print(String[i], Index, WriteToUART);
     }
References Buffers, Checksum, Video::ScreenBuffer::CursorX, Video::ScreenBuffer::CursorY, debug, Print(), and unlikely.
GetBitsPerPixel()
uint16_t Video::Display::GetBitsPerPixel ()
Definition at line 33 of file Display.cpp.
 { return this->framebuffer.BitsPerPixel; }
References BootInfo::FramebufferInfo::BitsPerPixel, and framebuffer.
GetBuffer()
ScreenBuffer * Video::Display::GetBuffer (int Index)
Definition at line 84 of file Display.cpp.
 { return &this->Buffers[Index]; }
References Buffers.
Referenced by Main().
GetBufferCursor()
void Video::Display::GetBufferCursor (int Index, uint32_t * X, uint32_t * Y)
Definition at line 158 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         *X = this->Buffers[Index].CursorX;
         *Y = this->Buffers[Index].CursorY;
     }
References Buffers, Checksum, Video::ScreenBuffer::CursorX, Video::ScreenBuffer::CursorY, debug, and unlikely.
GetCurrentFont()
Font * Video::Display::GetCurrentFont ()
Definition at line 31 of file Display.cpp.
 { return CurrentFont; }
References CurrentFont.
Referenced by Main(), and Print().
GetPitch()
size_t Video::Display::GetPitch ()
Definition at line 34 of file Display.cpp.
 { return this->framebuffer.Pitch; }
References framebuffer, and BootInfo::FramebufferInfo::Pitch.
GetPixel()
uint32_t Video::Display::GetPixel (uint32_t X, uint32_t Y, int Index)
Definition at line 188 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
             return 0;
         if (unlikely(X >= this->Buffers[Index].Width || Y >= this->Buffers[Index].Height))
             return 0;
         uint32_t *Pixel = (uint32_t *)((uintptr_t)this->Buffers[Index].Buffer + (Y * this->Buffers[Index].Width + X) * (this->framebuffer.BitsPerPixel / 8));
         return *Pixel;
     }
References BootInfo::FramebufferInfo::BitsPerPixel, Video::ScreenBuffer::Buffer, Buffers, Checksum, framebuffer, unlikely, and Video::ScreenBuffer::Width.
Print()
char Video::Display::Print (char Char, int Index, bool WriteToUART = false)
Definition at line 238 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
             return 0;
         // SmartLock(PrintLock);
         if (this->ColorIteration)
         {
             // RRGGBB
             if (Char >= '0' && Char <= '9')
                 this->Buffers[Index].Color = (this->Buffers[Index].Color << 4) | (Char - '0');
             else if (Char >= 'a' && Char <= 'f')
                 this->Buffers[Index].Color = (this->Buffers[Index].Color << 4) | (Char - 'a' + 10);
             else if (Char >= 'A' && Char <= 'F')
                 this->Buffers[Index].Color = (this->Buffers[Index].Color << 4) | (Char - 'A' + 10);
             else
                 this->Buffers[Index].Color = 0xFFFFFF;
             if (WriteToUART)
                 UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write(Char);
             this->ColorPickerIteration++;
             if (this->ColorPickerIteration == 6)
             {
                 this->ColorPickerIteration = 0;
                 if (WriteToUART)
                     UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write(']');
                 this->ColorIteration = false;
             }
             return Char;
         }
         if (WriteToUART)
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write(Char);
         switch (Char)
         {
         case '\e':
         {
             if (WriteToUART)
                 UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write('[');
             this->ColorIteration = true;
             return Char;
         }
         case '\b':
         {
             switch (this->CurrentFont->GetInfo().Type)
             {
             case FontType::PCScreenFont1:
             {
                 fixme("PCScreenFont1");
                 break;
             }
             case FontType::PCScreenFont2:
             {
                 uint32_t fonthdrWidth = this->CurrentFont->GetInfo().PSF2Font->Header->width;
                 uint32_t fonthdrHeight = this->CurrentFont->GetInfo().PSF2Font->Header->height;
                 for (unsigned long Y = this->Buffers[Index].CursorY; Y < this->Buffers[Index].CursorY + fonthdrHeight; Y++)
                     for (unsigned long X = this->Buffers[Index].CursorX - fonthdrWidth; X < this->Buffers[Index].CursorX; X++)
                         *(uint32_t *)((uintptr_t)this->Buffers[Index].Buffer +
                                       (Y * this->Buffers[Index].Width + X) * (this->framebuffer.BitsPerPixel / 8)) = 0;
                 break;
             }
             default:
                 warn("Unsupported font type");
                 break;
             }
             if (this->Buffers[Index].CursorX > 0)
                 this->Buffers[Index].CursorX -= this->GetCurrentFont()->GetInfo().Width;
             return Char;
         }
         case '\t':
         {
             this->Buffers[Index].CursorX = (this->Buffers[Index].CursorX + 8) & ~(8 - 1);
             return Char;
         }
         case '\r':
         {
             this->Buffers[Index].CursorX = 0;
             return Char;
         }
         case '\n':
         {
             this->Buffers[Index].CursorX = 0;
             this->Buffers[Index].CursorY += this->GetCurrentFont()->GetInfo().Height;
             return Char;
         }
         default:
             break;
         }
         uint32_t FontHeight = this->GetCurrentFont()->GetInfo().Height;
         if (this->Buffers[Index].CursorX + this->GetCurrentFont()->GetInfo().Width >= this->Buffers[Index].Width)
         {
             this->Buffers[Index].CursorX = 0;
             this->Buffers[Index].CursorY += FontHeight;
         }
         if (this->Buffers[Index].CursorY + FontHeight >= this->Buffers[Index].Height)
         {
             if (!this->Buffers[Index].DoNotScroll)
             {
                 this->Buffers[Index].CursorY -= FontHeight;
                 this->Scroll(Index, 1);
             }
         }
         switch (this->CurrentFont->GetInfo().Type)
         {
         case FontType::PCScreenFont1:
         {
             uint32_t *PixelPtr = (uint32_t *)this->Buffers[Index].Buffer;
             char *FontPtr = (char *)this->CurrentFont->GetInfo().PSF1Font->GlyphBuffer + (Char * this->CurrentFont->GetInfo().PSF1Font->Header->charsize);
             for (uint64_t Y = this->Buffers[Index].CursorY; Y < this->Buffers[Index].CursorY + 16; Y++)
             {
                 for (uint64_t X = this->Buffers[Index].CursorX; X < this->Buffers[Index].CursorX + 8; X++)
                     if ((*FontPtr & (0b10000000 >> (X - this->Buffers[Index].CursorX))) > 0)
                         *(unsigned int *)(PixelPtr + X + (Y * this->Buffers[Index].Width)) = this->Buffers[Index].Color;
                 FontPtr++;
             }
             this->Buffers[Index].CursorX += 8;
             break;
         }
         case FontType::PCScreenFont2:
         {
             // if (this->CurrentFont->PSF2Font->GlyphBuffer == (uint16_t *)0x01) // HAS UNICODE TABLE
             //     Char = this->CurrentFont->PSF2Font->GlyphBuffer[Char];
             int BytesPerLine = (this->CurrentFont->GetInfo().PSF2Font->Header->width + 7) / 8;
             char *FontAddress = (char *)this->CurrentFont->GetInfo().StartAddress;
             uint32_t FontHeaderSize = this->CurrentFont->GetInfo().PSF2Font->Header->headersize;
             uint32_t FontCharSize = this->CurrentFont->GetInfo().PSF2Font->Header->charsize;
             uint32_t FontLength = this->CurrentFont->GetInfo().PSF2Font->Header->length;
             char *FontPtr = FontAddress + FontHeaderSize + (Char > 0 && (uint32_t)Char < FontLength ? Char : 0) * FontCharSize;
             uint32_t FontHdrWidth = this->CurrentFont->GetInfo().PSF2Font->Header->width;
             uint32_t FontHdrHeight = this->CurrentFont->GetInfo().PSF2Font->Header->height;
             for (size_t Y = this->Buffers[Index].CursorY; Y < this->Buffers[Index].CursorY + FontHdrHeight; Y++)
             {
                 for (size_t X = this->Buffers[Index].CursorX; X < this->Buffers[Index].CursorX + FontHdrWidth; X++)
                 {
                     if ((*FontPtr & (0b10000000 >> (X - this->Buffers[Index].CursorX))) > 0)
                     {
                         void *FramebufferAddress = (void *)((uintptr_t)this->Buffers[Index].Buffer +
                                                             (Y * this->Buffers[Index].Width + X) *
                                                                 (this->framebuffer.BitsPerPixel / 8));
                         *(uint32_t *)FramebufferAddress = this->Buffers[Index].Color;
                     }
                 }
                 FontPtr += BytesPerLine;
             }
             this->Buffers[Index].CursorX += FontHdrWidth;
             break;
         }
         default:
             warn("Unsupported font type");
             break;
         }
         return Char;
     }
References BootInfo::FramebufferInfo::BitsPerPixel, Video::ScreenBuffer::Buffer, Buffers, Video::PSF1_HEADER::charsize, Video::PSF2_HEADER::charsize, Checksum, Video::ScreenBuffer::Color, ColorIteration, ColorPickerIteration, UniversalAsynchronousReceiverTransmitter::COM1, CurrentFont, Video::ScreenBuffer::CursorX, Video::ScreenBuffer::CursorY, fixme, framebuffer, GetCurrentFont(), Video::Font::GetInfo(), Video::_PSF1_FONT::GlyphBuffer, Video::_PSF1_FONT::Header, Video::_PSF2_FONT::Header, Video::PSF2_HEADER::headersize, Video::PSF2_HEADER::height, Video::FontInfo::Height, Video::PSF2_HEADER::length, Video::PCScreenFont1, Video::PCScreenFont2, Video::FontInfo::PSF1Font, Video::FontInfo::PSF2Font, Scroll(), Video::FontInfo::StartAddress, Video::FontInfo::Type, unlikely, warn, Video::PSF2_HEADER::width, Video::FontInfo::Width, Video::ScreenBuffer::Width, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by DrawString(), and putchar().
Scroll()
void Video::Display::Scroll (int Index, int Lines)
Definition at line 200 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         if (this->Buffers[Index].DoNotScroll)
             return;
         if (Lines == 0)
             return;
         if (Lines > 0)
         {
             uint32_t LineSize = this->Buffers[Index].Width * (this->framebuffer.BitsPerPixel / 8);
             uint32_t BytesToMove = LineSize * Lines * this->CurrentFont->GetInfo().Height;
             size_t BytesToClear = this->Buffers[Index].Size - BytesToMove;
             memmove(this->Buffers[Index].Buffer, (uint8_t *)this->Buffers[Index].Buffer + BytesToMove, BytesToClear);
             memset((uint8_t *)this->Buffers[Index].Buffer + BytesToClear, 0, BytesToMove);
         }
     }
References BootInfo::FramebufferInfo::BitsPerPixel, Buffers, Checksum, CurrentFont, debug, framebuffer, Video::Font::GetInfo(), Video::FontInfo::Height, memmove, memset(), Video::ScreenBuffer::Size, unlikely, and Video::ScreenBuffer::Width.
Referenced by Print().
SetBrightness()
void Video::Display::SetBrightness (int Value, int Index)
Definition at line 111 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         if (Value > 100)
             Value = 100;
         else if (Value < 0)
             Value = 0;
         uint32_t *pixel = (uint32_t *)this->Buffers[Index].Buffer;
         for (uint32_t y = 0; y < this->Buffers[Index].Height; y++)
         {
             for (uint32_t x = 0; x < this->Buffers[Index].Width; x++)
             {
                 uint32_t color = pixel[y * this->Buffers[Index].Width + x];
                 uint8_t r = color & 0xff;
                 uint8_t g = (color >> 8) & 0xff;
                 uint8_t b = (color >> 16) & 0xff;
                 r = s_cst(uint8_t, (r * Value) / 100);
                 g = s_cst(uint8_t, (g * Value) / 100);
                 b = s_cst(uint8_t, (b * Value) / 100);
                 pixel[y * this->Buffers[Index].Width + x] = (b << 16) | (g << 8) | r;
             }
         }
         this->Buffers[Index].Brightness = s_cst(char, Value);
     }
References Video::ScreenBuffer::Brightness, Buffers, Checksum, debug, Video::ScreenBuffer::Height, unlikely, and Video::ScreenBuffer::Width.
Referenced by SetBuffer().
SetBuffer()
void Video::Display::SetBuffer (int Index)
Definition at line 67 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         if (this->Buffers[Index].Brightness != 100)
             this->SetBrightness(this->Buffers[Index].Brightness, Index);
         if (this->Buffers[Index].Brightness == 0) /* Just clear the buffer */
             memset(this->Buffers[Index].Buffer, 0, this->Buffers[Index].Size);
         memcpy(this->framebuffer.BaseAddress, this->Buffers[Index].Buffer, this->Buffers[Index].Size);
     }
References BootInfo::FramebufferInfo::BaseAddress, Buffers, Checksum, debug, framebuffer, memcpy(), memset(), SetBrightness(), Size, and unlikely.
Referenced by KPrint(), Main(), and ~Display().
SetBufferCursor()
void Video::Display::SetBufferCursor (int Index, uint32_t X, uint32_t Y)
Definition at line 146 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         this->Buffers[Index].CursorX = X;
         this->Buffers[Index].CursorY = Y;
     }
References Buffers, Checksum, Video::ScreenBuffer::CursorX, Video::ScreenBuffer::CursorY, debug, and unlikely.
Referenced by Main().
SetCurrentFont()
void Video::Display::SetCurrentFont (Font * Font)
Definition at line 32 of file Display.cpp.
 { CurrentFont = Font; }
References CurrentFont.
SetDoNotScroll()
void Video::Display::SetDoNotScroll (bool Value, int Index)
Definition at line 224 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         this->Buffers[Index].DoNotScroll = Value;
     }
References Buffers, Checksum, debug, Video::ScreenBuffer::DoNotScroll, and unlikely.
Referenced by Main().
SetPixel()
void Video::Display::SetPixel (uint32_t X, uint32_t Y, uint32_t Color, int Index)
Definition at line 170 of file Display.cpp.
     {
         if (unlikely(this->Buffers[Index].Checksum != 0xBBFFE515A117E))
         {
             debug("Invalid buffer %d", Index);
             return;
         }
         if (unlikely(X >= this->Buffers[Index].Width))
             X = this->Buffers[Index].Width - 1;
         if (unlikely(Y >= this->Buffers[Index].Height))
             Y = this->Buffers[Index].Height - 1;
         uint32_t *Pixel = (uint32_t *)((uintptr_t)this->Buffers[Index].Buffer + (Y * this->Buffers[Index].Width + X) * (this->framebuffer.BitsPerPixel / 8));
         *Pixel = Color;
     }
References BootInfo::FramebufferInfo::BitsPerPixel, Video::ScreenBuffer::Buffer, Buffers, Checksum, debug, framebuffer, Video::ScreenBuffer::Height, unlikely, and Video::ScreenBuffer::Width.
Field Documentation
Buffers
ScreenBuffer Video::Display::Buffers[256] private
Definition at line 113 of file display.hpp.
Referenced by ClearBuffer(), CreateBuffer(), DeleteBuffer(), DrawString(), GetBuffer(), GetBufferCursor(), GetPixel(), Print(), Scroll(), SetBrightness(), SetBuffer(), SetBufferCursor(), SetDoNotScroll(), SetPixel(), and ~Display().
ColorIteration
bool Video::Display::ColorIteration = false private
Definition at line 114 of file display.hpp.
Referenced by Print().
ColorPickerIteration
int Video::Display::ColorPickerIteration = 0 private
Definition at line 115 of file display.hpp.
Referenced by Print().
CurrentFont
Font* Video::Display::CurrentFont = nullptr private
Definition at line 112 of file display.hpp.
Referenced by Display(), GetCurrentFont(), Print(), Scroll(), and SetCurrentFont().
framebuffer
BootInfo::FramebufferInfo Video::Display::framebuffer private
Definition at line 111 of file display.hpp.
Referenced by CreateBuffer(), Display(), GetBitsPerPixel(), GetPitch(), GetPixel(), Print(), Scroll(), SetBuffer(), and SetPixel().
The documentation for this class was generated from the following files:
Kernel/include/display.hpp
Kernel/Core/Video/Display.cpp