Fennix Userspace: Userspace/apps/base/busybox/networking/libiproute/rt_names.h File Reference
rt_names.h File Reference
Functions
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN const char * rtnl_rtprot_n2a (int id) FAST_FUNC
const char * rtnl_rtscope_n2a (int id) FAST_FUNC
const char * rtnl_rtrealm_n2a (int id) FAST_FUNC
const char * rtnl_dsfield_n2a (int id) FAST_FUNC
const char * rtnl_rttable_n2a (int id) FAST_FUNC
int rtnl_rtprot_a2n (uint32_t *id, char *arg) FAST_FUNC
int rtnl_rtscope_a2n (uint32_t *id, char *arg) FAST_FUNC
int rtnl_rtrealm_a2n (uint32_t *id, char *arg) FAST_FUNC
int rtnl_dsfield_a2n (uint32_t *id, char *arg) FAST_FUNC
int rtnl_rttable_a2n (uint32_t *id, char *arg) FAST_FUNC
const char * ll_type_n2a (int type, char *buf) FAST_FUNC
const char * ll_addr_n2a (unsigned char *addr, int alen, int type, char *buf, int blen) FAST_FUNC
int ll_addr_a2n (unsigned char *lladdr, int len, char *arg) FAST_FUNC
const char * ll_proto_n2a (unsigned short id, char *buf, int len) FAST_FUNC
int ll_proto_a2n (unsigned short *id, char *buf) FAST_FUNC
Function Documentation
ll_addr_a2n()
int ll_addr_a2n (unsigned char * lladdr, int len, char * arg)
Definition at line 41 of file ll_addr.c.
 {
     int i;
     if (strchr(arg, '.')) {
         inet_prefix pfx;
         if (get_addr_1(&pfx, arg, AF_INET)) {
             bb_error_msg("\"%s\" is invalid lladdr", arg);
             return -1;
         }
         if (len < 4) {
             return -1;
         }
         memcpy(lladdr, pfx.data, 4);
         return 4;
     }
     for (i = 0; i < len; i++) {
         int temp;
         char *cp = strchr(arg, ':');
         if (cp) {
             *cp = 0;
             cp++;
         }
         if (sscanf(arg, "%x", &temp) != 1 || (temp < 0 || temp > 255)) {
             bb_error_msg("\"%s\" is invalid lladdr", arg);
             return -1;
         }
         lladdr[i] = temp;
         if (!cp) {
             break;
         }
         arg = cp;
     }
     return i+1;
 }
References AF_INET, bb_error_msg(), inet_prefix::data, get_addr_1(), i, memcpy(), sscanf(), and strchr().
Referenced by do_add_or_delete(), do_set(), and parse_address().
ll_addr_n2a()
const char* ll_addr_n2a (unsigned char * addr, int alen, int type, char * buf, int blen)
Definition at line 16 of file ll_addr.c.
 {
     int i;
     int l;
     if (alen == 4
      && (type == ARPHRD_TUNNEL || type == ARPHRD_SIT || type == ARPHRD_IPGRE)
     ) {
         return inet_ntop(AF_INET, addr, buf, blen);
     }
     l = 0;
     for (i = 0; i < alen; i++) {
         if (i == 0) {
             snprintf(buf + l, blen, ":%02x"+1, addr[i]);
             blen -= 2;
             l += 2;
         } else {
             snprintf(buf + l, blen, ":%02x", addr[i]);
             blen -= 3;
             l += 3;
         }
     }
     return buf;
 }
References addr, AF_INET, ARPHRD_IPGRE, ARPHRD_SIT, ARPHRD_TUNNEL, buf, i, inet_ntop(), l, snprintf(), and type.
Referenced by print_linkinfo(), and print_neigh().
ll_proto_a2n()
int ll_proto_a2n (unsigned short * id, char * buf)
Definition at line 165 of file ll_proto.c.
 {
     unsigned i;
     const char *name = llproto_names;
     for (i = 0; i < ARRAY_SIZE(llproto_ids); i++) {
         if (strcasecmp(name, buf) == 0) {
             i = llproto_ids[i];
             goto good;
         }
         name += strlen(name) + 1;
     }
     errno = 0;
     i = bb_strtou(buf, NULL, 0);
     if (errno || i > 0xffff)
         return -1;
  good:
     *id = htons(i);
     return 0;
 }
References ARRAY_SIZE, bb_strtou(), buf, errno, htons(), i, NULL, strcasecmp, and strlen().
Referenced by tc_main().
ll_proto_n2a()
const char* ll_proto_n2a (unsigned short id, char * buf, int len)
Definition at line 153 of file ll_proto.c.
 {
     unsigned i;
     id = ntohs(id);
     for (i = 0; i < ARRAY_SIZE(llproto_ids); i++) {
         if (llproto_ids[i] == id)
             return nth_string(llproto_names, i);
     }
     snprintf(buf, len, "[%u]", id);
     return buf;
 }
References ARRAY_SIZE, buf, i, nth_string(), ntohs(), and snprintf().
ll_type_n2a()
const char* ll_type_n2a (int type, char * buf)
Definition at line 17 of file ll_types.c.
 {
     static const char arphrd_name[] ALIGN1 =
     /* 0,                  */ "generic" "\0"
     /* ARPHRD_LOOPBACK,    */ "loopback" "\0"
     /* ARPHRD_ETHER,       */ "ether" "\0"
 #ifdef ARPHRD_INFINIBAND
     /* ARPHRD_INFINIBAND,  */ "infiniband" "\0"
 #endif
 #ifdef ARPHRD_IEEE802_TR
     /* ARPHRD_IEEE802,     */ "ieee802" "\0"
     /* ARPHRD_IEEE802_TR,  */ "tr" "\0"
 #else
     /* ARPHRD_IEEE802,     */ "tr" "\0"
 #endif
 #ifdef ARPHRD_IEEE80211
     /* ARPHRD_IEEE80211,   */ "ieee802.11" "\0"
 #endif
 #ifdef ARPHRD_IEEE1394
     /* ARPHRD_IEEE1394,    */ "ieee1394" "\0"
 #endif
     /* ARPHRD_IRDA,        */ "irda" "\0"
     /* ARPHRD_SLIP,        */ "slip" "\0"
     /* ARPHRD_CSLIP,       */ "cslip" "\0"
     /* ARPHRD_SLIP6,       */ "slip6" "\0"
     /* ARPHRD_CSLIP6,      */ "cslip6" "\0"
     /* ARPHRD_PPP,         */ "ppp" "\0"
     /* ARPHRD_TUNNEL,      */ "ipip" "\0"
     /* ARPHRD_TUNNEL6,     */ "tunnel6" "\0"
     /* ARPHRD_SIT,         */ "sit" "\0"
     /* ARPHRD_IPGRE,       */ "gre" "\0"
 #ifdef ARPHRD_VOID
     /* ARPHRD_VOID,        */ "void" "\0"
 #endif
 #if ENABLE_FEATURE_IP_RARE_PROTOCOLS
     /* ARPHRD_EETHER,      */ "eether" "\0"
     /* ARPHRD_AX25,        */ "ax25" "\0"
     /* ARPHRD_PRONET,      */ "pronet" "\0"
     /* ARPHRD_CHAOS,       */ "chaos" "\0"
     /* ARPHRD_ARCNET,      */ "arcnet" "\0"
     /* ARPHRD_APPLETLK,    */ "atalk" "\0"
     /* ARPHRD_DLCI,        */ "dlci" "\0"
 #ifdef ARPHRD_ATM
     /* ARPHRD_ATM,         */ "atm" "\0"
 #endif
     /* ARPHRD_METRICOM,    */ "metricom" "\0"
     /* ARPHRD_RSRVD,       */ "rsrvd" "\0"
     /* ARPHRD_ADAPT,       */ "adapt" "\0"
     /* ARPHRD_ROSE,        */ "rose" "\0"
     /* ARPHRD_X25,         */ "x25" "\0"
 #ifdef ARPHRD_HWX25
     /* ARPHRD_HWX25,       */ "hwx25" "\0"
 #endif
     /* ARPHRD_HDLC,        */ "hdlc" "\0"
     /* ARPHRD_LAPB,        */ "lapb" "\0"
 #ifdef ARPHRD_DDCMP
     /* ARPHRD_DDCMP,       */ "ddcmp" "\0"
     /* ARPHRD_RAWHDLC,     */ "rawhdlc" "\0"
 #endif
     /* ARPHRD_FRAD,        */ "frad" "\0"
     /* ARPHRD_SKIP,        */ "skip" "\0"
     /* ARPHRD_LOCALTLK,    */ "ltalk" "\0"
     /* ARPHRD_FDDI,        */ "fddi" "\0"
     /* ARPHRD_BIF,         */ "bif" "\0"
     /* ARPHRD_IPDDP,       */ "ip/ddp" "\0"
     /* ARPHRD_PIMREG,      */ "pimreg" "\0"
     /* ARPHRD_HIPPI,       */ "hippi" "\0"
     /* ARPHRD_ASH,         */ "ash" "\0"
     /* ARPHRD_ECONET,      */ "econet" "\0"
     /* ARPHRD_FCPP,        */ "fcpp" "\0"
     /* ARPHRD_FCAL,        */ "fcal" "\0"
     /* ARPHRD_FCPL,        */ "fcpl" "\0"
     /* ARPHRD_FCFABRIC,    */ "fcfb0" "\0"
     /* ARPHRD_FCFABRIC+1,  */ "fcfb1" "\0"
     /* ARPHRD_FCFABRIC+2,  */ "fcfb2" "\0"
     /* ARPHRD_FCFABRIC+3,  */ "fcfb3" "\0"
     /* ARPHRD_FCFABRIC+4,  */ "fcfb4" "\0"
     /* ARPHRD_FCFABRIC+5,  */ "fcfb5" "\0"
     /* ARPHRD_FCFABRIC+6,  */ "fcfb6" "\0"
     /* ARPHRD_FCFABRIC+7,  */ "fcfb7" "\0"
     /* ARPHRD_FCFABRIC+8,  */ "fcfb8" "\0"
     /* ARPHRD_FCFABRIC+9,  */ "fcfb9" "\0"
     /* ARPHRD_FCFABRIC+10, */ "fcfb10" "\0"
     /* ARPHRD_FCFABRIC+11, */ "fcfb11" "\0"
     /* ARPHRD_FCFABRIC+12, */ "fcfb12" "\0"
 #endif /* FEATURE_IP_RARE_PROTOCOLS */
     ;
     /* Keep these arrays in sync! */
     static const uint16_t arphrd_type[] ALIGN2 = {
     0,                  /* "generic" "\0" */
     ARPHRD_LOOPBACK,    /* "loopback" "\0" */
     ARPHRD_ETHER,       /* "ether" "\0" */
 #ifdef ARPHRD_INFINIBAND
     ARPHRD_INFINIBAND,  /* "infiniband" "\0" */
 #endif
 #ifdef ARPHRD_IEEE802_TR
     ARPHRD_IEEE802,     /* "ieee802" "\0" */
     ARPHRD_IEEE802_TR,  /* "tr" "\0" */
 #else
     ARPHRD_IEEE802,     /* "tr" "\0" */
 #endif
 #ifdef ARPHRD_IEEE80211
     ARPHRD_IEEE80211,   /* "ieee802.11" "\0" */
 #endif
 #ifdef ARPHRD_IEEE1394
     ARPHRD_IEEE1394,    /* "ieee1394" "\0" */
 #endif
     ARPHRD_IRDA,        /* "irda" "\0" */
     ARPHRD_SLIP,        /* "slip" "\0" */
     ARPHRD_CSLIP,       /* "cslip" "\0" */
     ARPHRD_SLIP6,       /* "slip6" "\0" */
     ARPHRD_CSLIP6,      /* "cslip6" "\0" */
     ARPHRD_PPP,         /* "ppp" "\0" */
     ARPHRD_TUNNEL,      /* "ipip" "\0" */
     ARPHRD_TUNNEL6,     /* "tunnel6" "\0" */
     ARPHRD_SIT,         /* "sit" "\0" */
     ARPHRD_IPGRE,       /* "gre" "\0" */
 #ifdef ARPHRD_VOID
     ARPHRD_VOID,        /* "void" "\0" */
 #endif
 #if ENABLE_FEATURE_IP_RARE_PROTOCOLS
     ARPHRD_EETHER,      /* "eether" "\0" */
     ARPHRD_AX25,        /* "ax25" "\0" */
     ARPHRD_PRONET,      /* "pronet" "\0" */
     ARPHRD_CHAOS,       /* "chaos" "\0" */
     ARPHRD_ARCNET,      /* "arcnet" "\0" */
     ARPHRD_APPLETLK,    /* "atalk" "\0" */
     ARPHRD_DLCI,        /* "dlci" "\0" */
 #ifdef ARPHRD_ATM
     ARPHRD_ATM,         /* "atm" "\0" */
 #endif
     ARPHRD_METRICOM,    /* "metricom" "\0" */
     ARPHRD_RSRVD,       /* "rsrvd" "\0" */
     ARPHRD_ADAPT,       /* "adapt" "\0" */
     ARPHRD_ROSE,        /* "rose" "\0" */
     ARPHRD_X25,         /* "x25" "\0" */
 #ifdef ARPHRD_HWX25
     ARPHRD_HWX25,       /* "hwx25" "\0" */
 #endif
     ARPHRD_HDLC,        /* "hdlc" "\0" */
     ARPHRD_LAPB,        /* "lapb" "\0" */
 #ifdef ARPHRD_DDCMP
     ARPHRD_DDCMP,       /* "ddcmp" "\0" */
     ARPHRD_RAWHDLC,     /* "rawhdlc" "\0" */
 #endif
     ARPHRD_FRAD,        /* "frad" "\0" */
     ARPHRD_SKIP,        /* "skip" "\0" */
     ARPHRD_LOCALTLK,    /* "ltalk" "\0" */
     ARPHRD_FDDI,        /* "fddi" "\0" */
     ARPHRD_BIF,         /* "bif" "\0" */
     ARPHRD_IPDDP,       /* "ip/ddp" "\0" */
     ARPHRD_PIMREG,      /* "pimreg" "\0" */
     ARPHRD_HIPPI,       /* "hippi" "\0" */
     ARPHRD_ASH,         /* "ash" "\0" */
     ARPHRD_ECONET,      /* "econet" "\0" */
     ARPHRD_FCPP,        /* "fcpp" "\0" */
     ARPHRD_FCAL,        /* "fcal" "\0" */
     ARPHRD_FCPL,        /* "fcpl" "\0" */
     ARPHRD_FCFABRIC,    /* "fcfb0" "\0" */
     ARPHRD_FCFABRIC+1,  /* "fcfb1" "\0" */
     ARPHRD_FCFABRIC+2,  /* "fcfb2" "\0" */
     ARPHRD_FCFABRIC+3,  /* "fcfb3" "\0" */
     ARPHRD_FCFABRIC+4,  /* "fcfb4" "\0" */
     ARPHRD_FCFABRIC+5,  /* "fcfb5" "\0" */
     ARPHRD_FCFABRIC+6,  /* "fcfb6" "\0" */
     ARPHRD_FCFABRIC+7,  /* "fcfb7" "\0" */
     ARPHRD_FCFABRIC+8,  /* "fcfb8" "\0" */
     ARPHRD_FCFABRIC+9,  /* "fcfb9" "\0" */
     ARPHRD_FCFABRIC+10, /* "fcfb10" "\0" */
     ARPHRD_FCFABRIC+11, /* "fcfb11" "\0" */
     ARPHRD_FCFABRIC+12, /* "fcfb12" "\0" */
 #endif /* FEATURE_IP_RARE_PROTOCOLS */
     };
     unsigned i;
     const char *aname = arphrd_name;
     for (i = 0; i < ARRAY_SIZE(arphrd_type); i++) {
         if (arphrd_type[i] == type)
             return aname;
         aname += strlen(aname) + 1;
     }
     sprintf(buf, "[%d]", type);
     return buf;
 }
References ALIGN1, ALIGN2, ARPHRD_ADAPT, ARPHRD_APPLETLK, ARPHRD_ARCNET, ARPHRD_ASH, ARPHRD_ATM, ARPHRD_AX25, ARPHRD_BIF, ARPHRD_CHAOS, ARPHRD_CSLIP, ARPHRD_CSLIP6, ARPHRD_DDCMP, ARPHRD_DLCI, ARPHRD_ECONET, ARPHRD_EETHER, ARPHRD_ETHER, ARPHRD_FCAL, ARPHRD_FCFABRIC, ARPHRD_FCPL, ARPHRD_FCPP, ARPHRD_FDDI, ARPHRD_FRAD, ARPHRD_HDLC, ARPHRD_HIPPI, ARPHRD_HWX25, ARPHRD_IEEE1394, ARPHRD_IEEE802, ARPHRD_IEEE80211, ARPHRD_IEEE802_TR, ARPHRD_INFINIBAND, ARPHRD_IPDDP, ARPHRD_IPGRE, ARPHRD_IRDA, ARPHRD_LAPB, ARPHRD_LOCALTLK, ARPHRD_LOOPBACK, ARPHRD_METRICOM, ARPHRD_PIMREG, ARPHRD_PPP, ARPHRD_PRONET, ARPHRD_RAWHDLC, ARPHRD_ROSE, ARPHRD_RSRVD, ARPHRD_SIT, ARPHRD_SKIP, ARPHRD_SLIP, ARPHRD_SLIP6, ARPHRD_TUNNEL, ARPHRD_TUNNEL6, ARPHRD_VOID, ARPHRD_X25, ARRAY_SIZE, buf, i, sprintf(), strlen(), and type.
Referenced by print_linkinfo().
rtnl_dsfield_a2n()
int rtnl_dsfield_a2n (uint32_t * id, char * arg)
Definition at line 215 of file rt_names.c.
 {
     rtnl_rtdsfield_initialize();
     return rtnl_a2n(rtnl_rtdsfield_tab, id, arg, 16);
 }
References rtnl_a2n(), rtnl_rtdsfield_initialize(), and rtnl_rtdsfield_tab.
Referenced by iproute_modify(), iprule_modify(), and parse_args().
rtnl_dsfield_n2a()
const char* rtnl_dsfield_n2a (int id)
Definition at line 202 of file rt_names.c.
 {
     if (id < 0 || id > RT_TABLE_MAX) {
         return itoa(id);
     }
     rtnl_rtdsfield_initialize();
     if (rtnl_rtdsfield_tab->tab[id])
         return rtnl_rtdsfield_tab->tab[id];
     return itoa(id);
 }
References itoa, RT_TABLE_MAX, rtnl_rtdsfield_initialize(), rtnl_rtdsfield_tab, and rtnl_tab_t::tab.
Referenced by print_rule(), and print_tunnel().
rtnl_rtprot_a2n()
int rtnl_rtprot_a2n (uint32_t * id, char * arg)
Definition at line 118 of file rt_names.c.
 {
     rtnl_rtprot_initialize();
     return rtnl_a2n(rtnl_rtprot_tab, id, arg, 0);
 }
References rtnl_a2n(), rtnl_rtprot_initialize(), and rtnl_rtprot_tab.
Referenced by iproute_list_or_flush(), and iproute_modify().
rtnl_rtprot_n2a()
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN const char* rtnl_rtprot_n2a (int id)
rtnl_rtrealm_a2n()
int rtnl_rtrealm_a2n (uint32_t * id, char * arg)
Definition at line 170 of file rt_names.c.
 {
     rtnl_rtrealm_initialize();
     return rtnl_a2n(rtnl_rtrealm_tab, id, arg, 0);
 }
References rtnl_a2n(), rtnl_rtrealm_initialize(), and rtnl_rtrealm_tab.
Referenced by get_rt_realms().
rtnl_rtrealm_n2a()
const char* rtnl_rtrealm_n2a (int id)
Referenced by print_rule().
rtnl_rtscope_a2n()
int rtnl_rtscope_a2n (uint32_t * id, char * arg)
Definition at line 153 of file rt_names.c.
 {
     rtnl_rtscope_initialize();
     return rtnl_a2n(rtnl_rtscope_tab, id, arg, 0);
 }
References rtnl_a2n(), rtnl_rtscope_initialize(), and rtnl_rtscope_tab.
Referenced by ipaddr_list_or_flush(), ipaddr_modify(), iproute_list_or_flush(), and iproute_modify().
rtnl_rtscope_n2a()
const char* rtnl_rtscope_n2a (int id)
Definition at line 140 of file rt_names.c.
 {
     if (id < 0 || id > RT_TABLE_MAX) {
         return itoa(id);
     }
     rtnl_rtscope_initialize();
     if (rtnl_rtscope_tab->tab[id])
         return rtnl_rtscope_tab->tab[id];
     return itoa(id);
 }
References itoa, RT_TABLE_MAX, rtnl_rtscope_initialize(), rtnl_rtscope_tab, and rtnl_tab_t::tab.
Referenced by print_addrinfo(), and print_route().
rtnl_rttable_a2n()
int rtnl_rttable_a2n (uint32_t * id, char * arg)
Referenced by iproute_list_or_flush(), iproute_modify(), and iprule_modify().
rtnl_rttable_n2a()
const char* rtnl_rttable_n2a (int id)
Referenced by print_route(), and print_rule().