Fennix Userspace: Userspace/mlibc/options/posix/generic/search.cpp File Reference
search.cpp File Reference
#include <bits/ensure.h>
#include <search.h>
#include <stddef.h>
#include <new>
#include <mlibc/allocator.hpp>
#include <frg/stack.hpp>
#include <stdlib.h>
Data Structures
struct node
Namespaces
anonymous_namespace{search.cpp}
Functions
int anonymous_namespace{search.cpp}::height (struct node *node)
int anonymous_namespace{search.cpp}::rotate (struct node **nodep, int side)
int anonymous_namespace{search.cpp}::balance_tree (struct node **nodep)
void * tsearch (const void *key, void **rootp, int(*compar)(const void *, const void *))
void * tfind (const void *key, void *const *rootp, int(*compar)(const void *, const void *))
void * tdelete (const void *, void **, int(*compar)(const void *, const void *))
void twalk (const void *, void(*action)(const void *, VISIT, int))
void tdestroy (void *, void(*free_node)(void *))
void * lsearch (const void *key, void *base, size_t *nelp, size_t width, int(*compar)(const void *, const void *))
void * lfind (const void *key, const void *base, size_t *nelp, size_t width, int(*compar)(const void *, const void *))
Data Structure Documentation
node
struct node
Definition at line 10 of file search.cpp.
Data Fields
void * a[2]
int h
const void * key
Function Documentation
lfind()
void* lfind (const void * key, const void * base, size_t * nelp, size_t width, int(*)(const void *, const void *) compar)
Definition at line 142 of file search.cpp.
{
     (void)key;
     (void)base;
     (void)nelp;
     (void)width;
     (void)compar;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, base, and node::key.
lsearch()
void* lsearch (const void * key, void * base, size_t * nelp, size_t width, int(*)(const void *, const void *) compar)
Definition at line 131 of file search.cpp.
{
     (void)key;
     (void)base;
     (void)nelp;
     (void)width;
     (void)compar;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, base, and node::key.
tdelete()
void* tdelete (const void * , void ** , int(*)(const void *, const void *) compar)
Definition at line 113 of file search.cpp.
{
     (void)compar;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tdestroy()
void tdestroy (void * , void(*)(void *) free_node)
Definition at line 125 of file search.cpp.
{
     (void)free_node;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tfind()
void* tfind (const void * key, void *const * rootp, int(*)(const void *, const void *) compar)
Definition at line 97 of file search.cpp.
{
     if(!rootp)
         return 0;
     struct node *n = (struct node *)*rootp;
     for(;;) {
         if(!n)
             break;
         int c = compar(key, n->key);
         if(!c)
             break;
         n = (struct node *)n->a[c > 0];
     }
     return n;
 }
References c, node::key, and n.
Referenced by check_key(), and main().
tsearch()
void* tsearch (const void * key, void ** rootp, int(*)(const void *, const void *) compar)
Definition at line 65 of file search.cpp.
{
     if (!rootp)
         return NULL;
     struct node *n = static_cast<struct node *>(*rootp);
     frg::stack<struct node **, MemoryAllocator> nodes(getAllocator());
     nodes.push(reinterpret_cast<struct node **>(rootp));
     int c = 0;
     for (;;) {
         if (!n)
             break;
         c = compar(key, n->key);
         if (!c)
             return n;
         nodes.push(reinterpret_cast<struct node **>(&n->a[c > 0]));
         n = static_cast<struct node *>(n->a[c > 0]);
     }
     struct node *insert = static_cast<struct node*>(malloc(sizeof(struct node)));
     if (!insert)
         return NULL;
     insert->key = key;
     insert->a[0] = insert->a[1] = NULL;
     insert->h = 1;
     (*nodes.top()) = insert;
     nodes.pop();
     while(nodes.size() && balance_tree(nodes.top())) nodes.pop();
     return insert;
 }
References node::a, anonymous_namespace{search.cpp}::balance_tree(), c, getAllocator(), node::h, node::key, malloc(), n, nodes, and NULL.
Referenced by main().
twalk()
void twalk (const void * , void(*)(const void *, VISIT, int) action)
Definition at line 119 of file search.cpp.
{
     (void)action;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.