Fennix Userspace: Userspace/musl/src/locale/setlocale.c File Reference
setlocale.c File Reference
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include "locale_impl.h"
#include "libc.h"
#include "lock.h"
Functions
char * setlocale (int cat, const char *name)
Variables
static char buf [LC_ALL *(LOCALE_NAME_MAX+1)]
Function Documentation
setlocale()
char* setlocale (int cat, const char * name)
Definition at line 10 of file setlocale.c.
 {
     const struct __locale_map *lm;
     if ((unsigned)cat > LC_ALL) return 0;
     LOCK(__locale_lock);
     /* For LC_ALL, setlocale is required to return a string which
      * encodes the current setting for all categories. The format of
      * this string is unspecified, and only the following code, which
      * performs both the serialization and deserialization, depends
      * on the format, so it can easily be changed if needed. */
     if (cat == LC_ALL) {
         int i;
         if (name) {
             struct __locale_struct tmp_locale;
             char part[LOCALE_NAME_MAX+1] = "C.UTF-8";
             const char *p = name;
             for (i=0; i<LC_ALL; i++) {
                 const char *z = __strchrnul(p, ';');
                 if (z-p <= LOCALE_NAME_MAX) {
                     memcpy(part, p, z-p);
                     part[z-p] = 0;
                     if (*z) p = z+1;
                 }
                 lm = __get_locale(i, part);
                 if (lm == LOC_MAP_FAILED) {
                     UNLOCK(__locale_lock);
                     return 0;
                 }
                 tmp_locale.cat[i] = lm;
             }
             libc.global_locale = tmp_locale;
         }
         char *s = buf;
         const char *part;
         int same = 0;
         for (i=0; i<LC_ALL; i++) {
             const struct __locale_map *lm =
                 libc.global_locale.cat[i];
             if (lm == libc.global_locale.cat[0]) same++;
             part = lm ? lm->name : "C";
             size_t l = strlen(part);
             memcpy(s, part, l);
             s[l] = ';';
             s += l+1;
         }
         *--s = 0;
         UNLOCK(__locale_lock);
         return same==LC_ALL ? (char *)part : buf;
     }
     if (name) {
         lm = __get_locale(cat, name);
         if (lm == LOC_MAP_FAILED) {
             UNLOCK(__locale_lock);
             return 0;
         }
         libc.global_locale.cat[cat] = lm;
     } else {
         lm = libc.global_locale.cat[cat];
     }
     char *ret = lm ? (char *)lm->name : "C";
     UNLOCK(__locale_lock);
     return ret;
 }
References __get_locale(), __locale_lock, __strchrnul(), buf, __locale_struct::cat, i, LC_ALL, libc, LOC_MAP_FAILED, LOCALE_NAME_MAX, LOCK, memcpy(), __locale_map::name, p, strlen(), and UNLOCK.
Variable Documentation
buf
char buf[LC_ALL *(LOCALE_NAME_MAX+1)] static
Definition at line 8 of file setlocale.c.
Referenced by __asctime_r(), __crypt_blowfish(), __ctime32_r(), __dl_vseterr(), __fopen_rb_ca(), __fstatfs(), __fxstat(), __fxstatat(), __get_locale(), __getgr_a(), __getpw_a(), __lookup_ipliteral(), __lookup_name(), __lookup_serv(), __lxstat(), __netlink_enumerate(), __nscd_query(), __procfdname(), __ptsname_r(), __res_mkquery(), __res_send(), __semtimedop_time32(), __shm_mapname(), __statfs(), __stdio_read(), __stdio_write(), __stdout_write(), __strftime_l(), __wcsftime_l(), __xstat(), _vsyslog(), asctime(), catopen(), ChecksumAddLump(), confstr(), cookieread(), cookiewrite(), crypt(), ctime_r(), cuserid(), D_BindVariables(), do_glob(), do_read(), do_tzset(), ecvt(), expand_tilde(), fchdir(), fchmod(), fchown(), fexecve(), fixup_rpath(), fmemopen(), fmt_fp(), fputws(), fstatvfs(), G_Ticker(), getcwd(), getdents(), getgr_r(), getgrgid_r(), getgrnam_r(), getgrouplist(), gethostbyaddr_r(), gethostbyname2_r(), gethostbyname_r(), getnameinfo(), getpw_r(), getpwnam_r(), getpwuid_r(), getrandom(), getservbyname(), getservbyname_r(), getservbyport(), getservbyport_r(), getspnam_r(), glob(), inet_ntoa(), inet_ntop(), io_thread_func(), ioctl(), klogctl(), load_library(), lstat(), M_ReadFile(), M_snprintf(), M_vsnprintf(), map_library(), match_bracket(), mem_fopen_read(), mem_fread(), mem_get_buf(), mread(), ms_write(), msgctl(), mwrite(), name_from_dns(), name_from_dns_search(), name_from_hosts(), name_from_null(), name_from_numeric(), open_memstream(), open_wmemstream(), openpty(), out_rev_(), path_open(), pread(), print_broken_up_decimal(), print_decimal_number(), print_exponential_number(), print_floating_point(), print_integer(), print_integer_finalization(), printf_core(), processblock(), ptsname(), pwrite(), read(), readdir_r(), readlink(), readlinkat(), recv(), recvfrom(), regerror(), reverse_hosts(), reverse_services(), sem_open(), semop(), semtimedop(), send(), sendto(), setbuf(), setbuffer(), setlocale(), setvbuf(), SHA1_UpdateInt32(), shm_open(), shm_unlink(), shmctl(), siglongjmp(), ST_Responder(), start(), stat(), statvfs(), strdup(), strerror_r(), string_read(), tmpnam(), tre_tnfa_run_parallel(), ttyname(), V_DrawFilledBox(), V_DrawHorizLine(), V_DrawVertLine(), vsnprintf(), vswprintf(), vswscanf(), wcsrtombs(), wcstox(), wms_write(), write(), and wstring_read().