Fennix: Userspace/apps/base/busybox/libbb/bb_getgroups.c File Reference
bb_getgroups.c File Reference
#include "libbb.h"
Functions
gid_t *FAST_FUNC bb_getgroups (int *ngroups, gid_t *group_array)
Function Documentation
bb_getgroups()
gid_t* FAST_FUNC bb_getgroups (int * ngroups, gid_t * group_array)
Definition at line 13 of file bb_getgroups.c.
 {
     int n = ngroups ? *ngroups : 0;
     /* getgroups may be a bit expensive, try to use it only once */
     if (n < 32)
         n = 32;
     for (;;) {
 // FIXME: ash tries so hard to not die on OOM (when we are called from test),
 // and we spoil it with just one xrealloc here
         group_array = xrealloc(group_array, (n+1) * sizeof(group_array[0]));
         n = getgroups(n, group_array);
         /*
          * If buffer is too small, kernel does not return new_n > n.
          * It returns -1 and EINVAL:
          */
         if (n >= 0) {
             /* Terminator for bb_getgroups(NULL, NULL) usage */
             group_array[n] = (gid_t) -1;
             break;
         }
         if (errno == EINVAL) { /* too small? */
             /* This is the way to ask kernel how big the array is */
             n = getgroups(0, group_array);
             continue;
         }
         /* Some other error (should never happen on Linux) */
         bb_simple_perror_msg_and_die("getgroups");
     }
     if (ngroups)
         *ngroups = n;
     return group_array;
 }
References bb_simple_perror_msg_and_die(), EINVAL, errno, getgroups(), group_array, n, ngroups, and xrealloc.
Referenced by initialize_group_array().