Fennix: Atomic< T > Class Template Reference
Atomic< T > Class Template Reference
#include <atomic.hpp>
Public Member Functions
Atomic ()
Atomic (T Init)
T Load (MemoryOrder Order=MemoryOrder::SeqCst)
Load the value of the atomic variable.
void Store (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Store a value to the atomic variable.
T Exchange (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Exchange the value of the atomic variable.
bool CompareExchange (T &Expected, T Desired, MemoryOrder Order=MemoryOrder::SeqCst)
Compare and exchange the value of the atomic variable.
T FetchAdd (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Fetch and add the value of the atomic variable.
T FetchSub (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Fetch and subtract the value of the atomic variable.
T FetchAnd (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Fetch and and the value of the atomic variable.
T FetchOr (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Fetch and or the value of the atomic variable.
T FetchXor (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Fetch and xor the value of the atomic variable.
T FetchNand (T v, MemoryOrder Order=MemoryOrder::SeqCst)
Fetch and nand the value of the atomic variable.
operator bool ()
T operator-> ()
T operator++ ()
T operator-- ()
T operator++ (int)
T operator-- (int)
T operator+= (T v)
T operator-= (T v)
T operator&= (T v)
T operator|= (T v)
T operator^= (T v)
T operator~ ()
T operator= (T v)
Private Member Functions
_Atomic (T) m_Value
Detailed Description
template<typename T>
class Atomic< T >
Definition at line 65 of file atomic.hpp.
Constructor & Destructor Documentation
Atomic() [1/2]
template<typename T > Atomic< T >::Atomic () inline
Definition at line 70 of file atomic.hpp.
 : m_Value(0) {}
Atomic() [2/2]
template<typename T > Atomic< T >::Atomic (T Init) inline
Definition at line 71 of file atomic.hpp.
 : m_Value(Init) {}
Member Function Documentation
_Atomic()
template<typename T > Atomic< T >::_Atomic (T) private
CompareExchange()
template<typename T > bool Atomic< T >::CompareExchange (T & Expected, T Desired, MemoryOrder Order = MemoryOrder::SeqCst) inline
Compare and exchange the value of the atomic variable.
Parameters
Expected The expected value
Desired The desired value
Order The memory order to use
Returns
true If the exchange was successful
false If the exchange was not successful
Definition at line 116 of file atomic.hpp.
     {
         return builtin_atomic_n(compare_exchange)(&m_Value, &Expected, Desired, true, Order, Order);
     }
References builtin_atomic_n.
Exchange()
template<typename T > T Atomic< T >::Exchange (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Exchange the value of the atomic variable.
Parameters
v The value to exchange
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 102 of file atomic.hpp.
     {
         return builtin_atomic_n(exchange)(&m_Value, v, Order);
     }
References builtin_atomic_n.
FetchAdd()
template<typename T > T Atomic< T >::FetchAdd (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Fetch and add the value of the atomic variable.
Parameters
v The value to add
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 128 of file atomic.hpp.
     {
         return builtin_atomic(fetch_add)(&m_Value, v, Order);
     }
References builtin_atomic.
Referenced by Atomic< T >::operator++(), and Atomic< T >::operator+=().
FetchAnd()
template<typename T > T Atomic< T >::FetchAnd (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Fetch and and the value of the atomic variable.
Parameters
v The value to and
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 152 of file atomic.hpp.
     {
         return builtin_atomic(fetch_and)(&m_Value, v, Order);
     }
References builtin_atomic.
Referenced by Atomic< T >::operator&=().
FetchNand()
template<typename T > T Atomic< T >::FetchNand (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Fetch and nand the value of the atomic variable.
Parameters
v The value to nand
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 188 of file atomic.hpp.
     {
         return builtin_atomic(fetch_nand)(&m_Value, v, Order);
     }
References builtin_atomic.
Referenced by Atomic< T >::operator~().
FetchOr()
template<typename T > T Atomic< T >::FetchOr (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Fetch and or the value of the atomic variable.
Parameters
v The value to or
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 164 of file atomic.hpp.
     {
         return builtin_atomic(fetch_or)(&m_Value, v, Order);
     }
References builtin_atomic.
Referenced by Atomic< T >::operator|=().
FetchSub()
template<typename T > T Atomic< T >::FetchSub (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Fetch and subtract the value of the atomic variable.
Parameters
v The value to subtract
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 140 of file atomic.hpp.
     {
         return builtin_atomic(fetch_sub)(&m_Value, v, Order);
     }
References builtin_atomic.
Referenced by Atomic< T >::operator--(), and Atomic< T >::operator-=().
FetchXor()
template<typename T > T Atomic< T >::FetchXor (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Fetch and xor the value of the atomic variable.
Parameters
v The value to xor
Order The memory order to use
Returns
T The old value of the atomic variable
Definition at line 176 of file atomic.hpp.
     {
         return builtin_atomic(fetch_xor)(&m_Value, v, Order);
     }
References builtin_atomic.
Referenced by Atomic< T >::operator^=().
Load()
template<typename T > T Atomic< T >::Load (MemoryOrder Order = MemoryOrder::SeqCst) inline
Load the value of the atomic variable.
Parameters
Order The memory order to use
Returns
T The value of the atomic variable
Definition at line 79 of file atomic.hpp.
     {
         return builtin_atomic_n(load)(&m_Value, Order);
     }
References builtin_atomic_n.
Referenced by Tasking::Task::GetCurrentProcess(), Tasking::Task::GetCurrentThread(), Tasking::Task::GetLastTaskTicks(), Tasking::Task::GetSchedulerTicks(), CrashHandler::Handle(), Atomic< T >::operator bool(), and Atomic< T >::operator->().
operator bool()
template<typename T > Atomic< T >::operator bool () inline
Definition at line 193 of file atomic.hpp.
 { return this->Load() != 0; }
References Atomic< T >::Load().
operator&=()
template<typename T > T Atomic< T >::operator&= (T v) inline
Definition at line 201 of file atomic.hpp.
 { return this->FetchAnd(v) & v; }
References Atomic< T >::FetchAnd().
operator++() [1/2]
template<typename T > T Atomic< T >::operator++ () inline
Definition at line 195 of file atomic.hpp.
 { return this->FetchAdd(1) + 1; }
References Atomic< T >::FetchAdd().
operator++() [2/2]
template<typename T > T Atomic< T >::operator++ (int) inline
Definition at line 197 of file atomic.hpp.
 { return this->FetchAdd(1); }
References Atomic< T >::FetchAdd().
operator+=()
template<typename T > T Atomic< T >::operator+= (T v) inline
Definition at line 199 of file atomic.hpp.
 { return this->FetchAdd(v) + v; }
References Atomic< T >::FetchAdd().
operator--() [1/2]
template<typename T > T Atomic< T >::operator-- () inline
Definition at line 196 of file atomic.hpp.
 { return this->FetchSub(1) - 1; }
References Atomic< T >::FetchSub().
operator--() [2/2]
template<typename T > T Atomic< T >::operator-- (int) inline
Definition at line 198 of file atomic.hpp.
 { return this->FetchSub(1); }
References Atomic< T >::FetchSub().
operator-=()
template<typename T > T Atomic< T >::operator-= (T v) inline
Definition at line 200 of file atomic.hpp.
 { return this->FetchSub(v) - v; }
References Atomic< T >::FetchSub().
operator->()
template<typename T > T Atomic< T >::operator-> () inline
Definition at line 194 of file atomic.hpp.
 { return this->Load(); }
References Atomic< T >::Load().
operator=()
template<typename T > T Atomic< T >::operator= (T v) inline
Definition at line 205 of file atomic.hpp.
     {
         this->Store(v);
         return v;
     }
References Atomic< T >::Store().
operator^=()
template<typename T > T Atomic< T >::operator^= (T v) inline
Definition at line 203 of file atomic.hpp.
 { return this->FetchXor(v) ^ v; }
References Atomic< T >::FetchXor().
operator|=()
template<typename T > T Atomic< T >::operator|= (T v) inline
Definition at line 202 of file atomic.hpp.
 { return this->FetchOr(v) | v; }
References Atomic< T >::FetchOr().
operator~()
template<typename T > T Atomic< T >::operator~ () inline
Definition at line 204 of file atomic.hpp.
 { return this->FetchNand(-1); }
References Atomic< T >::FetchNand().
Store()
template<typename T > void Atomic< T >::Store (T v, MemoryOrder Order = MemoryOrder::SeqCst) inline
Store a value to the atomic variable.
Parameters
v The value to store
Order The memory order to use
Definition at line 90 of file atomic.hpp.
     {
         return builtin_atomic_n(store)(&m_Value, v, Order);
     }
References builtin_atomic_n.
Referenced by Atomic< T >::operator=().
The documentation for this class was generated from the following file:
Kernel/include/atomic.hpp