Fennix: Memory::Virtual Class Reference
Memory::Virtual Class Reference
#include <virtual.hpp>
Data Structures
class PageMapIndexer
Public Types
enum MapType {
NoMapType , FourKiB , TwoMiB , FourMiB ,
OneGiB
}
Public Member Functions
bool Check (void *VirtualAddress, PTFlag Flag=PTFlag::P, MapType Type=MapType::FourKiB)
Check if page has the specified flag.
bool CheckRegion (void *VirtualAddress, size_t Length, PTFlag Flag=PTFlag::P, MapType Type=MapType::FourKiB)
Check if the region has the specified flag.
void * GetPhysical (void *VirtualAddress)
Get physical address of the page.
MapType GetMapType (void *VirtualAddress)
Get map type of the page.
PageDirectoryEntry * GetPDE (void *VirtualAddress, MapType Type=MapType::FourKiB)
PageTableEntry * GetPTE (void *VirtualAddress, MapType Type=MapType::FourKiB)
void Map (void *VirtualAddress, void *PhysicalAddress, uint64_t Flag=PTFlag::P, MapType Type=MapType::FourKiB)
Map page.
__always_inline void Map (void *VirtualAddress, void *PhysicalAddress, size_t Length, uint64_t Flags, MapType Type=MapType::FourKiB)
Map multiple pages.
__always_inline MapType OptimizedMap (void *VirtualAddress, void *PhysicalAddress, size_t Length, uint64_t Flags, bool Fit=false, bool FailOnModulo=false)
Map multiple pages efficiently.
void Unmap (void *VirtualAddress, MapType Type=MapType::FourKiB)
Unmap page.
__always_inline void Unmap (void *VirtualAddress, size_t Length, MapType Type=MapType::FourKiB)
Unmap multiple pages.
__always_inline void Remap (void *VirtualAddress, void *PhysicalAddress, uint64_t Flags, MapType Type=MapType::FourKiB)
Remap page.
Virtual (PageTable *Table=nullptr)
Construct a new Virtual object.
~Virtual ()
Destroy the Virtual object.
Private Member Functions
NewLock (MemoryLock)
Private Attributes
PageTable * pTable = nullptr
Detailed Description
Definition at line 29 of file virtual.hpp.
Member Enumeration Documentation
MapType
enum Memory::Virtual::MapType
Enumerator
NoMapType
FourKiB
TwoMiB
FourMiB
OneGiB
Definition at line 36 of file virtual.hpp.
         {
             NoMapType,
             FourKiB,
             TwoMiB,
             FourMiB,
             OneGiB
         };
Constructor & Destructor Documentation
Virtual()
Memory::Virtual::Virtual (PageTable * Table = nullptr)
Construct a new Virtual object.
Parameters
Table Page table. If null, it will use the current page table.
Definition at line 27 of file vmm.cpp.
     {
         if (Table)
             this->pTable = Table;
         else
             this->pTable = thisPageTable;
         // debug("+ %#lx (PT: %#lx) %s", this, this->pTable,
         //    KernelSymbolTable
         //        ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
         //        : "Unknown");
     }
References pTable, and thisPageTable.
~Virtual()
Memory::Virtual::~Virtual ()
Destroy the Virtual object.
Definition at line 40 of file vmm.cpp.
     {
         // debug("- %#lx", this);
     }
Member Function Documentation
Check()
bool Memory::Virtual::Check (void * VirtualAddress, PTFlag Flag = PTFlag::P, MapType Type = MapType::FourKiB)
Check if page has the specified flag.
Parameters
VirtualAddress Virtual address of the page
Flag Flag to check
Type Type of the page. Check MapType enum.
Returns
true if page has the specified flag, false otherwise.
Definition at line 25 of file vmm.cpp.
     {
     }
Referenced by Memory::__no_sanitize(), SymbolResolver::__no_sanitize(), ACPI::ACPI::ACPI(), CheckRegion(), DisplayStackScreen(), ACPI::DSDT::DSDT(), linux_arch_prctl(), linux_clock_gettime(), linux_execve(), linux_fstat(), linux_getrandom(), linux_ioctl(), linux_lstat(), linux_mprotect(), linux_munmap(), linux_nanosleep(), linux_prlimit64(), linux_readlink(), linux_reboot(), linux_sigaction(), linux_stat(), linux_uname(), linux_wait4(), sys_execve(), sys_mprotect(), sys_munmap(), sys_readlink(), sys_uname(), and UserInput().
CheckRegion()
bool Memory::Virtual::CheckRegion (void * VirtualAddress, size_t Length, PTFlag Flag = PTFlag::P, MapType Type = MapType::FourKiB) inline
Check if the region has the specified flag.
Parameters
VirtualAddress Virtual address of the region.
Length Length of the region.
Flag Flag to check.
Type Type of the page. Check MapType enum.
Returns
true if the region has the specified flag, false otherwise.
Definition at line 78 of file virtual.hpp.
         {
             for (size_t i = 0; i < Length; i += PAGE_SIZE_4K)
             {
                 if (!this->Check((void *)((uintptr_t)VirtualAddress + i), Flag, Type))
                 {
                     debug("address %#lx for pt %#lx has flag(s) %#lx",
                           (uintptr_t)VirtualAddress + i, this->pTable, Flag);
                     return false;
                 }
             }
             return true;
         }
References Check(), debug, i, Length, and PAGE_SIZE_4K.
Referenced by linux_mmap().
GetMapType()
Virtual::MapType Memory::Virtual::GetMapType (void * VirtualAddress)
Get map type of the page.
Parameters
VirtualAddress Virtual address of the page.
Returns
Map type of the page.
Definition at line 115 of file vmm.cpp.
     {
         // 0x1000 aligned
         uintptr_t Address = (uintptr_t)VirtualAddress;
         Address &= 0xFFFFFFFFFFFFF000;
         PageMapIndexer Index = PageMapIndexer(Address);
         PageMapLevel4 *PML4 = &this->pTable->Entries[Index.PMLIndex];
         PageDirectoryPointerTableEntryPtr *PDPTE = nullptr;
         PageDirectoryEntryPtr *PDE = nullptr;
         PageTableEntryPtr *PTE = nullptr;
         if (PML4->Present)
         {
             PDPTE = (PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4->GetAddress() << 12);
             if (PDPTE)
             {
                 if (PDPTE->Entries[Index.PDPTEIndex].Present)
                 {
                     if (PDPTE->Entries[Index.PDPTEIndex].PageSize)
                         return MapType::OneGiB;
                     PDE = (PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
                     if (PDE)
                     {
                         if (PDE->Entries[Index.PDEIndex].Present)
{
                             if (PDE->Entries[Index.PDEIndex].PageSize)
                                 return MapType::TwoMiB;
                             PTE = (PageTableEntryPtr *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
                             if (PTE)
{
                                 if (PTE->Entries[Index.PTEIndex].Present)
                                     return MapType::FourKiB;
                             }
                         }
                     }
                 }
             }
         }
         return MapType::NoMapType;
     }
References Address, PDE, Memory::Virtual::PageMapIndexer::PDEIndex, PDPTE, PML4, pTable, PTE, and Memory::Virtual::PageMapIndexer::PTEIndex.
GetPDE()
PageDirectoryEntry * Memory::Virtual::GetPDE (void * VirtualAddress, MapType Type = MapType::FourKiB)
Definition at line 206 of file vmm.cpp.
     {
         UNUSED(Type);
         uintptr_t Address = (uintptr_t)VirtualAddress;
         Address &= 0xFFFFFFFFFFFFF000;
         PageMapIndexer Index = PageMapIndexer(Address);
         PageMapLevel4 *PML4 = &this->pTable->Entries[Index.PMLIndex];
         if (!PML4->Present)
         {
             debug("PML4 not present for %#lx", VirtualAddress);
             return nullptr;
         }
         PageDirectoryPointerTableEntryPtr *PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4->Address << 12);
         PageDirectoryPointerTableEntry *PDPTE = &PDPTEPtr->Entries[Index.PDPTEIndex];
         if (!PDPTE->Present)
         {
             debug("PDPTE not present for %#lx", VirtualAddress);
             return nullptr;
         }
         PageDirectoryEntryPtr *PDEPtr = (PageDirectoryEntryPtr *)(PDPTE->GetAddress() << 12);
         PageDirectoryEntry *PDE = &PDEPtr->Entries[Index.PDEIndex];
         if (PDE->Present)
             return PDE;
         debug("PDE not present for %#lx", VirtualAddress);
         return nullptr;
     }
References Address, debug, PDE, Memory::Virtual::PageMapIndexer::PDEIndex, PDEPtr, PDPTE, PDPTEPtr, PML4, pTable, and UNUSED.
GetPhysical()
void * Memory::Virtual::GetPhysical (void * VirtualAddress)
Get physical address of the page.
Parameters
VirtualAddress Virtual address of the page.
Returns
Physical address of the page.
Definition at line 29 of file vmm.cpp.
     {
     }
Referenced by Memory::PageTable::__getPhysical().
GetPTE()
PageTableEntry * Memory::Virtual::GetPTE (void * VirtualAddress, MapType Type = MapType::FourKiB)
Definition at line 237 of file vmm.cpp.
     {
         UNUSED(Type);
         uintptr_t Address = (uintptr_t)VirtualAddress;
         Address &= 0xFFFFFFFFFFFFF000;
         PageMapIndexer Index = PageMapIndexer(Address);
         PageMapLevel4 *PML4 = &this->pTable->Entries[Index.PMLIndex];
         if (!PML4->Present)
         {
             debug("PML4 not present for %#lx", VirtualAddress);
             return nullptr;
         }
         PageDirectoryPointerTableEntryPtr *PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4->Address << 12);
         PageDirectoryPointerTableEntry *PDPTE = &PDPTEPtr->Entries[Index.PDPTEIndex];
         if (!PDPTE->Present)
         {
             debug("PDPTE not present for %#lx", VirtualAddress);
             return nullptr;
         }
         PageDirectoryEntryPtr *PDEPtr = (PageDirectoryEntryPtr *)(PDPTE->GetAddress() << 12);
         PageDirectoryEntry *PDE = &PDEPtr->Entries[Index.PDEIndex];
         if (!PDE->Present)
         {
             debug("PDE not present for %#lx", VirtualAddress);
             return nullptr;
         }
         PageTableEntryPtr *PTEPtr = (PageTableEntryPtr *)(PDE->GetAddress() << 12);
         PageTableEntry *PTE = &PTEPtr->Entries[Index.PTEIndex];
         if (PTE->Present)
             return PTE;
         debug("PTE not present for %#lx", VirtualAddress);
         return nullptr;
     }
References Address, debug, PDE, Memory::Virtual::PageMapIndexer::PDEIndex, PDEPtr, PDPTE, PDPTEPtr, PML4, pTable, PTE, Memory::Virtual::PageMapIndexer::PTEIndex, PTEPtr, and UNUSED.
Referenced by Driver::AppendMapFlag(), Memory::VirtualMemoryArea::HandleCoW(), linux_mprotect(), Driver::RemoveMapFlag(), and sys_mprotect().
Map() [1/2]
__always_inline void Memory::Virtual::Map (void * VirtualAddress, void * PhysicalAddress, size_t Length, uint64_t Flags, MapType Type = MapType::FourKiB) inline
Map multiple pages.
Parameters
VirtualAddress First virtual address of the page.
PhysicalAddress First physical address of the page.
Length Length to map.
Flags Flags of the page. Check PTFlag enum.
Type Type of the page. Check MapType enum.
Definition at line 139 of file virtual.hpp.
         {
             int PageSize = PAGE_SIZE_4K;
             if (Type == MapType::TwoMiB)
                 PageSize = PAGE_SIZE_2M;
             else if (Type == MapType::FourMiB)
                 PageSize = PAGE_SIZE_4M;
             else if (Type == MapType::OneGiB)
                 PageSize = PAGE_SIZE_1G;
             for (uintptr_t i = 0; i < Length; i += PageSize)
             {
                 this->Map((void *)((uintptr_t)VirtualAddress + i),
                           (void *)((uintptr_t)PhysicalAddress + i),
                           Flags, Type);
             }
         }
References Flags, i, Length, Map(), PAGE_SIZE_1G, PAGE_SIZE_2M, PAGE_SIZE_4K, PAGE_SIZE_4M, and PhysicalAddress.
Map() [2/2]
void Memory::Virtual::Map (void * VirtualAddress, void * PhysicalAddress, uint64_t Flag = PTFlag::P, MapType Type = MapType::FourKiB)
Map page.
Parameters
VirtualAddress Virtual address of the page.
PhysicalAddress Physical address of the page.
Flags Flags of the page. Check PTFlag enum.
Type Type of the page. Check MapType enum.
Definition at line 33 of file vmm.cpp.
     {
     }
Referenced by ACPI::ACPI::ACPI(), APIC::APIC::APIC(), Memory::ProgramBreak::brk(), Memory::VirtualMemoryArea::CreateCoWRegion(), ACPI::DSDT::DSDT(), Execute::ELFLoadRel(), PCI::Manager::EnumerateBus(), PCI::Manager::EnumerateDevice(), PCI::Manager::EnumerateFunction(), Memory::StackGuard::Expand(), Video::Font::Font(), Time::HighPrecisionEventTimer::HighPrecisionEventTimer(), InitializeMemoryManagement(), Driver::InitializePCI(), linux_mmap(), Execute::ELFObject::LoadExec_x86_64(), ACPI::MADT::MADT(), PCI::Manager::Manager(), Map(), MapFramebuffer(), MapFromZero(), MapKernel(), Driver::MapPages(), PCI::Manager::MapPCIAddresses(), OptimizedMap(), Remap(), Memory::VirtualMemoryArea::RequestPages(), Tasking::TCB::SetupThreadLocalStorage(), Memory::StackGuard::StackGuard(), and Xalloc_MAP_MEMORY().
NewLock()
Memory::Virtual::NewLock (MemoryLock) private
OptimizedMap()
__always_inline MapType Memory::Virtual::OptimizedMap (void * VirtualAddress, void * PhysicalAddress, size_t Length, uint64_t Flags, bool Fit = false, bool FailOnModulo = false) inline
Map multiple pages efficiently.
This function will detect the best page size to map the pages.
Note
This function will not check if PSE or 1GB pages are enabled or supported.
Parameters
VirtualAddress First virtual address of the page.
PhysicalAddress First physical address of the page.
Length Length of the pages.
Flags Flags of the page. Check PTFlag enum.
Fit If true, the function will try to fit the pages in the smallest page size.
FailOnModulo If true, the function will return NoMapType if the length is not a multiple of the page size.
Returns
The best page size to map the pages.
Definition at line 177 of file virtual.hpp.
         {
             if (unlikely(Fit))
             {
                 while (Length >= PAGE_SIZE_1G)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::OneGiB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_1G);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_1G);
                     Length -= PAGE_SIZE_1G;
                 }
                 while (Length >= PAGE_SIZE_4M)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::FourMiB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_4M);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_4M);
                     Length -= PAGE_SIZE_4M;
                 }
                 while (Length >= PAGE_SIZE_2M)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::TwoMiB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_2M);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_2M);
                     Length -= PAGE_SIZE_2M;
                 }
                 while (Length >= PAGE_SIZE_4K)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::FourKiB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_4K);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_4K);
                     Length -= PAGE_SIZE_4K;
                 }
                 return Virtual::MapType::FourKiB;
             }
             Virtual::MapType Type = Virtual::MapType::FourKiB;
             if (Length >= PAGE_SIZE_1G)
             {
                 Type = Virtual::MapType::OneGiB;
                 if (Length % PAGE_SIZE_1G != 0)
                 {
                     warn("Length is not a multiple of 1GB.");
                     if (FailOnModulo)
                         return Virtual::MapType::NoMapType;
                 }
             }
             else if (Length >= PAGE_SIZE_4M)
             {
                 Type = Virtual::MapType::FourMiB;
                 if (Length % PAGE_SIZE_4M != 0)
                 {
                     warn("Length is not a multiple of 4MB.");
                     if (FailOnModulo)
                         return Virtual::MapType::NoMapType;
                 }
             }
             else if (Length >= PAGE_SIZE_2M)
             {
                 Type = Virtual::MapType::TwoMiB;
                 if (Length % PAGE_SIZE_2M != 0)
                 {
                     warn("Length is not a multiple of 2MB.");
                     if (FailOnModulo)
                         return Virtual::MapType::NoMapType;
                 }
             }
             this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Type);
             return Type;
         }
References Flags, Length, Map(), PAGE_SIZE_1G, PAGE_SIZE_2M, PAGE_SIZE_4K, PAGE_SIZE_4M, PhysicalAddress, unlikely, and warn.
Referenced by MapFramebuffer().
Remap()
__always_inline void Memory::Virtual::Remap (void * VirtualAddress, void * PhysicalAddress, uint64_t Flags, MapType Type = MapType::FourKiB) inline
Remap page.
Parameters
VirtualAddress Virtual address of the page.
PhysicalAddress Physical address of the page.
Flags Flags of the page. Check PTFlag enum.
Type Type of the page. Check MapType enum.
Definition at line 296 of file virtual.hpp.
         {
             this->Unmap(VirtualAddress, Type);
             this->Map(VirtualAddress, PhysicalAddress, Flags, Type);
         }
References Flags, Map(), PhysicalAddress, and Unmap().
Referenced by Memory::ProgramBreak::brk(), Memory::VirtualMemoryArea::FreeAllPages(), Memory::VirtualMemoryArea::FreePages(), linux_munmap(), Tasking::TCB::SetupThreadLocalStorage(), and sys_munmap().
Unmap() [1/2]
void Memory::Virtual::Unmap (void * VirtualAddress, MapType Type = MapType::FourKiB)
Unmap page.
Parameters
VirtualAddress Virtual address of the page.
Type Type of the page. Check MapType enum.
Definition at line 37 of file vmm.cpp.
     {
     }
Referenced by Memory::VirtualMemoryArea::CreateCoWRegion(), MapFromZero(), Remap(), Unmap(), Driver::UnmapPages(), and Xalloc_UNMAP_MEMORY().
Unmap() [2/2]
__always_inline void Memory::Virtual::Unmap (void * VirtualAddress, size_t Length, MapType Type = MapType::FourKiB) inline
Unmap multiple pages.
Parameters
VirtualAddress First virtual address of the page.
Length Length to map.
Type Type of the page. Check MapType enum.
Definition at line 273 of file virtual.hpp.
         {
             int PageSize = PAGE_SIZE_4K;
             if (Type == MapType::TwoMiB)
                 PageSize = PAGE_SIZE_2M;
             else if (Type == MapType::FourMiB)
                 PageSize = PAGE_SIZE_4M;
             else if (Type == MapType::OneGiB)
                 PageSize = PAGE_SIZE_1G;
             for (uintptr_t i = 0; i < Length; i += PageSize)
                 this->Unmap((void *)((uintptr_t)VirtualAddress + i), Type);
         }
References i, Length, PAGE_SIZE_1G, PAGE_SIZE_2M, PAGE_SIZE_4K, PAGE_SIZE_4M, and Unmap().
Field Documentation
pTable
PageTable* Memory::Virtual::pTable = nullptr private
Definition at line 33 of file virtual.hpp.
Referenced by GetMapType(), GetPDE(), GetPTE(), and Virtual().
The documentation for this class was generated from the following files:
Kernel/include/memory/virtual.hpp
Kernel/arch/aarch64/memory/vmm.cpp
Lynx/UEFI/src/Memory/VirtualMemoryManager.cpp