Fennix: Userspace/musl/include/libintl.h File Reference
libintl.h File Reference
Macros
#define __USE_GNU_GETTEXT 1
#define __GNU_GETTEXT_SUPPORTED_REVISION(major) ((major) == 0 ? 1 : -1)
#define __fa(n)
Functions
char * gettext (const char *) __fa(1)
char * dgettext (const char *, const char *) __fa(2)
char * dcgettext (const char *, const char *, int) __fa(2)
char * ngettext (const char *, const char *, unsigned long) __fa(1) __fa(2)
char * dngettext (const char *, const char *, const char *, unsigned long) __fa(2) __fa(3)
char * dcngettext (const char *, const char *, const char *, unsigned long, int) __fa(2) __fa(3)
char * textdomain (const char *)
char * bindtextdomain (const char *, const char *)
char * bind_textdomain_codeset (const char *, const char *)
Macro Definition Documentation
__fa
#define __fa (n)
Definition at line 14 of file libintl.h.
__GNU_GETTEXT_SUPPORTED_REVISION
#define __GNU_GETTEXT_SUPPORTED_REVISION (major) ((major) == 0 ? 1 : -1)
Definition at line 9 of file libintl.h.
__USE_GNU_GETTEXT
#define __USE_GNU_GETTEXT 1
Definition at line 8 of file libintl.h.
Function Documentation
bind_textdomain_codeset()
char* bind_textdomain_codeset (const char * domainname, const char * codeset)
Definition at line 68 of file libintl-stubs.cpp.
{
     (void)domainname;
     (void)codeset;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, domainname, EINVAL, errno, NULL, strcasecmp, and Driver::void().
bindtextdomain()
char* bindtextdomain (const char * domainname, const char * dirname)
Definition at line 61 of file libintl-stubs.cpp.
{
     (void)domainname;
     (void)dirname;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, a_cas_p, a_store, binding::active, bindings, calloc, binding::dirlen, dirname, domainname, binding::domainname, EINVAL, errno, gettextdir(), LOCK, lock, memcpy, NAME_MAX, binding::next, p, PATH_MAX, strcmp, strnlen(), UNLOCK, and Driver::void().
dcgettext()
char* dcgettext (const char * domainname, const char * msgid, int category)
Definition at line 17 of file libintl-stubs.cpp.
                       {
     (void)domainname;
     (void)msgid;
     (void)category;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, category, dcngettext(), domainname, msgid, and Driver::void().
dcngettext()
char* dcngettext (const char * , const char * , const char * , unsigned long , int)
dgettext()
char* dgettext (const char * domainname, const char * msgid)
Definition at line 10 of file libintl-stubs.cpp.
{
     (void)domainname;
     (void)msgid;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, dcngettext(), domainname, LC_MESSAGES, msgid, and Driver::void().
dngettext()
char* dngettext (const char * , const char * , const char * , unsigned long)
gettext()
char* gettext (const char * msgid)
Definition at line 4 of file libintl-stubs.cpp.
{
     (void)msgid;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, dgettext, msgid, and Driver::void().
ngettext()
char* ngettext (const char * , const char * , unsigned long)
textdomain()
char* textdomain (const char * domainname)
Definition at line 55 of file libintl-stubs.cpp.
{
     (void)domainname;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __gettextdomain(), current_domain, domainname, EINVAL, errno, malloc, memcpy, NAME_MAX, strlen(), and Driver::void().