Fennix Userspace: Userspace/musl/src/misc/get_current_dir_name.c File Reference
get_current_dir_name.c File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <unistd.h>
#include <sys/stat.h>
Macros
#define _GNU_SOURCE
Functions
char * get_current_dir_name (void)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file get_current_dir_name.c.
Function Documentation
get_current_dir_name()
char* get_current_dir_name (void)
Definition at line 8 of file get_current_dir_name.c.
{
     struct stat a, b;
     char *res = getenv("PWD");
     if (res && *res && !stat(res, &a) && !stat(".", &b)
         && (a.st_dev == b.st_dev) && (a.st_ino == b.st_ino))
         return strdup(res);
     return getcwd(0, 0);
 }
References getcwd(), getenv(), stat::st_dev, stat::st_ino, stat(), and strdup().