Fennix: Userspace/musl/include/arpa/inet.h File Reference
inet.h File Reference
#include <features.h>
#include <netinet/in.h>
Functions
uint32_t htonl (uint32_t)
uint16_t htons (uint16_t)
uint32_t ntohl (uint32_t)
uint16_t ntohs (uint16_t)
in_addr_t inet_addr (const char *)
in_addr_t inet_network (const char *)
char * inet_ntoa (struct in_addr)
int inet_pton (int, const char *__restrict, void *__restrict)
const char * inet_ntop (int, const void *__restrict, char *__restrict, socklen_t)
int inet_aton (const char *, struct in_addr *)
struct in_addr inet_makeaddr (in_addr_t, in_addr_t)
in_addr_t inet_lnaof (struct in_addr)
in_addr_t inet_netof (struct in_addr)
Function Documentation
htonl()
uint32_t htonl (uint32_t n)
Definition at line 4 of file htonl.c.
 {
     union { int i; char c; } u = { 1 };
     return u.c ? bswap_32(n) : n;
 }
References bswap_32, c, i, and n.
Referenced by accept_builtin(), d4_recv_raw_packet(), dhcprelay_main(), do_lzo_compress(), find_free_or_expired_nip(), fmt_time_bernstein_25(), get_netmask(), inet_addr_match(), INET_resolve(), INET_setroute(), init_d6_packet(), ipaddr_modify(), ipcalc_main(), lzo_compress(), nbdclient_main(), parse_args(), pass_to_client(), pick_nip(), process_packet(), random_xid(), rpm_gettags(), send_ACK(), send_offer(), send_probe(), tls_aesgcm_decrypt(), udhcp_recv_kernel_packet(), udhcp_str2optset(), udhcpc6_main(), write32(), write_header(), write_leases(), and xwrite_encrypted_aesgcm().
htons()
uint16_t htons (uint16_t n)
Definition at line 4 of file htons.c.
 {
     union { int i; char c; } u = { 1 };
     return u.c ? bswap_16(n) : n;
 }
References bswap_16, c, i, and n.
Referenced by __res_msend_rc(), accept_builtin(), add_client_options(), arpping(), common_ping_main(), create_and_bind_or_die(), d4_recv_raw_packet(), d6_listen_socket(), d6_raw_socket(), d6_recv_raw_packet(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), dhcprelay_main(), do_lzo_compress(), get_address(), getaddrinfo(), getservbyname_r(), handle_port(), init_d6_packet(), init_packet(), ip_port_str(), ll_proto_a2n(), nbdclient_main(), nc_main(), packet4_ok(), parse_args(), port_name(), print_tunnel(), process_packet(), pscan_main(), read_header(), recv_pack(), reread_config_file(), send_arp_request(), send_pack(), send_packet_to_client(), send_probe(), str2sockaddr(), table_lookup(), tcpudpsvd_main(), traceroute_init(), udhcp_listen_socket(), udhcp_raw_socket(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), udhcp_str2optset(), vlan_parse_opt(), and xconnect_ftpdata().
inet_addr()
in_addr_t inet_addr (const char * p)
Definition at line 5 of file inet_addr.c.
 {
     struct in_addr a;
     if (!__inet_aton(p, &a)) return -1;
     return a.s_addr;
 }
References __inet_aton(), p, and in_addr::s_addr.
Referenced by accept_builtin(), and inet_makeaddr().
inet_aton()
int inet_aton (const char * , struct in_addr *)
Referenced by dhcprelay_main(), handle_port(), INET_resolve(), ipcalc_main(), parse_conf_file(), str2sockaddr(), and udhcpc_main().
inet_lnaof()
in_addr_t inet_lnaof (struct in_addr in)
Definition at line 18 of file inet_legacy.c.
 {
     uint32_t h = in.s_addr;
     if (h>>24 < 128) return h & 0xffffff;
     if (h>>24 < 192) return h & 0xffff;
     return h & 0xff;
 }
References h, and in_addr::s_addr.
inet_makeaddr()
struct in_addr inet_makeaddr (in_addr_t n, in_addr_t h)
Definition at line 5 of file inet_legacy.c.
 {
     if (n < 256) h |= n<<24;
     else if (n < 65536) h |= n<<16;
     else h |= n<<8;
     return (struct in_addr){ h };
 }
References inet_addr(), ntohl(), and p.
inet_netof()
in_addr_t inet_netof (struct in_addr in)
Definition at line 26 of file inet_legacy.c.
 {
     uint32_t h = in.s_addr;
     if (h>>24 < 128) return h >> 24;
     if (h>>24 < 192) return h >> 16;
     return h >> 8;
 }
References h, and in_addr::s_addr.
inet_network()
in_addr_t inet_network (const char * p)
Definition at line 5 of file inet_legacy.c.
 {
     return ntohl(inet_addr(p));
 }
inet_ntoa()
char* inet_ntoa (struct in_addr in)
Definition at line 4 of file inet_ntoa.c.
 {
     static char buf[16];
     unsigned char *a = (void *)&in;
     snprintf(buf, sizeof buf, "%d.%d.%d.%d", a[0], a[1], a[2], a[3]);
     return buf;
 }
References buf, and snprintf().
Referenced by accept_builtin(), bb_displayroutes(), d6_read_interface(), dumpleases_main(), hostname_main(), ipcalc_main(), nip_to_a(), nobody_responds_to_arp(), packet4_ok(), perform_release(), recv_pack(), send_packet_verbose(), send_renew(), send_select(), udhcp_read_interface(), udhcpc_main(), and xconnect().
inet_ntop()
const char* inet_ntop (int , const void * __restrict, char * __restrict, socklen_t)
Referenced by getnameinfo(), ll_addr_n2a(), print_tunnel(), and rt_addr_n2a().
inet_pton()
int inet_pton (int , const char * __restrict, void * __restrict)
Referenced by __lookup_ipliteral(), get_addr_1(), str2sockaddr(), and udhcpc6_main().
ntohl()
uint32_t ntohl (uint32_t n)
Definition at line 4 of file ntohl.c.
 {
     union { int i; char c; } u = { 1 };
     return u.c ? bswap_32(n) : n;
 }
References bswap_32, c, i, and n.
Referenced by askremotedate(), des_setkey(), dumpleases_main(), f_read32(), get_prefix_1(), handle_incoming_and_exit(), inet_makeaddr(), INET_rresolve(), INET_setroute(), lfp_to_d(), mton(), option_to_env(), parse_args(), parse_conf_file(), read32(), read_config(), read_header(), read_leases(), rpm_gettags(), select_lease_time(), send_offer(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), and xmalloc_optname_optval().
ntohs()
uint16_t ntohs (uint16_t n)
Definition at line 4 of file ntohs.c.
 {
     union { int i; char c; } u = { 1 };
     return u.c ? bswap_16(n) : n;
 }
References bswap_16, c, i, and n.
Referenced by bb_lookup_port(), bind_for_passive_mode(), d4_recv_raw_packet(), d6_recv_raw_packet(), get_sname(), getnameinfo(), getservbyport_r(), ll_proto_n2a(), nbdclient_main(), nc_main(), packet4_ok(), reread_config_file(), send_probe(), sfp_to_d(), and xmalloc_optname_optval().