Fennix Userspace: Userspace/mlibc/options/internal/generic/sigset.cpp File Reference
sigset.cpp File Reference
#include <bits/sigset_t.h>
#include <bits/ensure.h>
Functions
int sigemptyset (sigset_t *sigset)
int sigfillset (sigset_t *sigset)
int sigaddset (sigset_t *sigset, int sig)
int sigdelset (sigset_t *sigset, int sig)
int sigismember (const sigset_t *set, int sig)
Function Documentation
sigaddset()
int sigaddset (sigset_t * sigset, int sig)
Definition at line 16 of file sigset.cpp.
{
     int signo = sig - 1;
     // TODO: do not hard code CHAR_BITS
     __ensure((unsigned int)signo < sizeof(sigset_t) * 8);
     *sigset |= sigset_t(1) << signo;
     return 0;
 }
References __ensure, and sigset.
Referenced by abort(), main(), parent_fn(), popen(), pthread_setcancelstate(), system(), test_sigmask(), and we_askshell().
sigdelset()
int sigdelset (sigset_t * sigset, int sig)
Definition at line 24 of file sigset.cpp.
{
     int signo = sig - 1;
     // TODO: do not hard code CHAR_BITS
     __ensure((unsigned int)signo < sizeof(sigset_t) * 8);
     *sigset &= ~(sigset_t(1) << signo);
     return 0;
 }
References __ensure, and sigset.
Referenced by abort(), pthread_attr_setsigmask_np(), and worker().
sigemptyset()
int sigemptyset (sigset_t * sigset)
Definition at line 4 of file sigset.cpp.
{
     *sigset = 0;
     return 0;
 }
References sigset.
Referenced by abort(), main(), parent_fn(), popen(), pthread_attr_getsigmask_np(), signal_handler(), system(), test_sigmask(), we_askshell(), and worker().
sigfillset()
int sigfillset (sigset_t * sigset)
Definition at line 9 of file sigset.cpp.
{
     *sigset = ~sigset_t(0);
     return 0;
 }
References sigset.
Referenced by abort(), posix_spawn(), and worker().
sigismember()
int sigismember (const sigset_t * set, int sig)
Definition at line 32 of file sigset.cpp.
{
     int signo = sig - 1;
     // TODO: do not hard code CHAR_BITS
     __ensure((unsigned int)signo < sizeof(sigset_t) * 8);
     return (*set) & (sigset_t(1) << signo);
 }
References __ensure.
Referenced by child(), and test_sigmask().