Fennix Kernel: Kernel/KernelThread.cpp File Reference
KernelThread.cpp File Reference
#include "kernel.h"
#include <filesystem/ustar.hpp>
#include <kshell.hpp>
#include <power.hpp>
#include <lock.hpp>
#include <printf.h>
#include <exec.hpp>
#include <cwalk.h>
#include <vm.hpp>
#include <vector>
#include <stb/image.h>
#include "DAPI.hpp"
#include "Fex.hpp"
Macros
#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_STDIO
#define STBI_NO_LINEAR
#define STBI_NO_THREAD_LOCALS
#define STBI_NO_HDR
#define STBI_ONLY_TGA
Functions
int SpawnInit ()
void BootLogoAnimationThread ()
void ExitLogoAnimationThread ()
void CleanupProcessesThreadWrapper ()
void KernelMainThread ()
NewLock (ShutdownLock)
void __no_stack_protector KernelShutdownThread (bool Reboot)
void KST_Reboot ()
void KST_Shutdown ()
Variables
Driver::Driver * DriverManager = nullptr
Disk::Manager * DiskManager = nullptr
NetworkInterfaceManager::NetworkInterface * NIManager = nullptr
VirtualFileSystem::Node * DevFS = nullptr
VirtualFileSystem::Node * MntFS = nullptr
VirtualFileSystem::Node * ProcFS = nullptr
VirtualFileSystem::Node * VarLogFS = nullptr
uint8_t * Frames [27]
uint32_t FrameSizes [27]
size_t FrameCount = 1
Macro Definition Documentation
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 32 of file KernelThread.cpp.
STBI_NO_HDR
#define STBI_NO_HDR
Definition at line 36 of file KernelThread.cpp.
STBI_NO_LINEAR
#define STBI_NO_LINEAR
Definition at line 34 of file KernelThread.cpp.
STBI_NO_STDIO
#define STBI_NO_STDIO
Definition at line 33 of file KernelThread.cpp.
STBI_NO_THREAD_LOCALS
#define STBI_NO_THREAD_LOCALS
Definition at line 35 of file KernelThread.cpp.
STBI_ONLY_TGA
#define STBI_ONLY_TGA
Definition at line 37 of file KernelThread.cpp.
Function Documentation
BootLogoAnimationThread()
void BootLogoAnimationThread ()
Definition at line 419 of file KernelThread.cpp.
 {
     char BootAnimPath[16];
     while (FrameCount < 27)
     {
         sprintf(BootAnimPath, "/etc/boot/%ld.tga", FrameCount);
         RefNode *frame = vfs->Open(BootAnimPath);
         if (!frame)
         {
             debug("Failed to load boot animation frame %s", BootAnimPath);
             break;
         }
         FrameSizes[FrameCount] = s_cst(uint32_t, frame->Length);
         Frames[FrameCount] = new uint8_t[frame->Length];
         frame->Read(Frames[FrameCount], frame->Length);
         delete frame;
         FrameCount++;
     }
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = 1; i < FrameCount; i++)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i],
                                    &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i],
                                              FrameSizes[i], &x, &y,
                                              &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY,
                               (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
         TaskManager->Sleep(50);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
         TaskManager->Sleep(5);
     }
 }
References debug, Display, FrameCount, Frames, FrameSizes, free(), NULL, VirtualFileSystem::Virtual::Open(), RefNode, Tasking::Task::Sleep(), sprintf(), stbi_info_from_memory(), stbi_load_from_memory(), STBI_rgb_alpha, TaskManager, and vfs.
Referenced by KernelMainThread().
CleanupProcessesThreadWrapper()
void CleanupProcessesThreadWrapper ()
Definition at line 555 of file KernelThread.cpp.
 {
     TaskManager->CleanupProcessesThread();
 }
References Tasking::Task::CleanupProcessesThread(), and TaskManager.
Referenced by KernelMainThread().
ExitLogoAnimationThread()
void ExitLogoAnimationThread ()
Definition at line 494 of file KernelThread.cpp.
 {
     Display->SetBrightness(100, 1);
     Display->SetBuffer(1);
     /* Files: 26.tga 25.tga ... 1.tga */
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = FrameCount - 1; i > 0; i--)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i],
                                    &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i],
                                              FrameSizes[i], &x, &y,
                                              &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY,
                               (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
         TaskManager->Sleep(50);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
         TaskManager->Sleep(5);
     }
 }
References Display, FrameCount, Frames, FrameSizes, free(), NULL, Tasking::Task::Sleep(), stbi_info_from_memory(), stbi_load_from_memory(), STBI_rgb_alpha, and TaskManager.
Referenced by KernelShutdownThread().
KernelMainThread()
void KernelMainThread ()
Definition at line 560 of file KernelThread.cpp.
 {
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test_long));
     // TaskManager->Yield();
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(mutex_test));
     // ilp;
     // TaskManager->CreateThread(thisProcess, Tasking::IP(tasking_test_fb));
     // ilp;
     Tasking::TCB *clnThd =
         TaskManager->CreateThread(thisProcess,
                                   Tasking::IP(CleanupProcessesThreadWrapper));
     clnThd->SetPriority(Tasking::Idle);
     TaskManager->SetCleanupThread(clnThd);
     thisThread->SetPriority(Tasking::Critical);
     Tasking::TCB *blaThread = nullptr;
     if (Config.BootAnimation)
     {
         blaThread =
             TaskManager->CreateThread(thisProcess,
                                       Tasking::IP(BootLogoAnimationThread));
         blaThread->Rename("Logo Animation");
     }
 #ifdef DEBUG
     TaskManager->CreateThread(thisProcess, Tasking::IP(TaskMgr));
     TaskManager->CreateThread(thisProcess, Tasking::IP(lsof));
     TreeFS(vfs->GetRootNode(), 0);
 #endif
     KPrint("Kernel Compiled at: %s %s with C++ Standard: %d",
            __DATE__, __TIME__, CPP_LANGUAGE_STANDARD);
     KPrint("C++ Language Version (__cplusplus): %ld", __cplusplus);
     if (IsVirtualizedEnvironment())
         KPrint("Running in Virtualized Environment");
     KPrint("Initializing Disk Manager...");
     DiskManager = new Disk::Manager;
     KPrint("Loading Modules...");
     DriverManager = new Driver::Driver;
     DriverManager->LoadDrivers();
     KPrint("Fetching Disks...");
     if (DriverManager->GetDrivers().size() > 0)
     {
         foreach (auto Driver in DriverManager->GetDrivers())
             if (((FexExtended *)Driver.ExtendedHeaderAddress)->Driver.Type == FexDriverType::FexDriverType_Storage)
                 DiskManager->FetchDisks(Driver.DriverUID);
     }
     else
         KPrint("\eE85230No disk drivers found! Cannot fetch disks!");
     KPrint("Initializing Network Interface Manager...");
     NIManager = new NetworkInterfaceManager::NetworkInterface;
     KPrint("Starting Network Interface Manager...");
     NIManager->StartService();
     KPrint("Setting up userspace");
     int ExitCode = -1;
     Tasking::TCB *initThread = nullptr;
     int tid = SpawnInit();
     if (tid < 0)
     {
         KPrint("\eE85230Failed to start %s! Code: %d", Config.InitPath, tid);
         goto Exit;
     }
     KPrint("Waiting for \e22AAFF%s\eCCCCCC to start...", Config.InitPath);
     thisThread->SetPriority(Tasking::Idle);
     initThread = TaskManager->GetThreadByID(tid);
     TaskManager->WaitForThread(initThread);
     ExitCode = initThread->GetExitCode();
 Exit:
     if (ExitCode == 0)
     {
         KPrint("\eFF7900%s process exited with code %d and it didn't invoked the shutdown function.",
                Config.InitPath, ExitCode);
         KPrint("System Halted");
         CPU::Halt(true);
     }
     KPrint("\eE85230Userspace process exited with code %d (%#x)",
            ExitCode, ExitCode < 0 ? -ExitCode : ExitCode);
     KPrint("Dropping to kernel shell...");
     TaskManager->Sleep(1000);
     TaskManager->WaitForThread(blaThread);
     TaskManager->CreateThread(thisProcess,
                               Tasking::IP(KShellThread))
         ->Rename("Kernel Shell");
     CPU::Halt(true);
 }
References KernelConfig::BootAnimation, BootLogoAnimationThread(), CleanupProcessesThreadWrapper(), Config, Tasking::Task::CreateThread(), Tasking::Critical, DiskManager, Driver, DriverManager, Disk::Manager::FetchDisks(), FexDriverType_Storage, Driver::Driver::GetDrivers(), Tasking::TCB::GetExitCode(), VirtualFileSystem::Virtual::GetRootNode(), Tasking::Task::GetThreadByID(), Halt(), Tasking::Idle, KernelConfig::InitPath, IsVirtualizedEnvironment(), KPrint(), KShellThread(), Driver::Driver::LoadDrivers(), NIManager, Tasking::TCB::Rename(), Tasking::Task::SetCleanupThread(), Tasking::TCB::SetPriority(), Tasking::Task::Sleep(), SpawnInit(), NetworkInterfaceManager::NetworkInterface::StartService(), TaskManager, thisProcess, thisThread, vfs, and Tasking::Task::WaitForThread().
Referenced by Main().
KernelShutdownThread()
void __no_stack_protector KernelShutdownThread (bool Reboot)
Definition at line 667 of file KernelThread.cpp.
 {
     SmartLock(ShutdownLock);
     debug("KernelShutdownThread(%s)", Reboot ? "true" : "false");
     if (Config.BootAnimation && TaskManager)
     {
         Tasking::TCB *elaThread =
             TaskManager->CreateThread(thisProcess,
                                       Tasking::IP(ExitLogoAnimationThread));
         elaThread->Rename("Logo Animation");
         TaskManager->WaitForThread(elaThread);
     }
     BeforeShutdown(Reboot);
     trace("%s...", Reboot ? "Rebooting" : "Shutting down");
     if (Reboot)
         PowerManager->Reboot();
     else
         PowerManager->Shutdown();
     CPU::Stop();
 }
References BeforeShutdown(), KernelConfig::BootAnimation, Config, Tasking::Task::CreateThread(), debug, ExitLogoAnimationThread(), PowerManager, Power::Power::Reboot(), Tasking::TCB::Rename(), Power::Power::Shutdown(), TaskManager, thisProcess, trace, and Tasking::Task::WaitForThread().
Referenced by cmd_exit(), cmd_reboot(), cmd_shutdown(), KST_Reboot(), and KST_Shutdown().
KST_Reboot()
void KST_Reboot ()
Definition at line 690 of file KernelThread.cpp.
 { KernelShutdownThread(true); }
References KernelShutdownThread().
KST_Shutdown()
void KST_Shutdown ()
Definition at line 691 of file KernelThread.cpp.
 { KernelShutdownThread(false); }
References KernelShutdownThread().
NewLock()
NewLock (ShutdownLock)
SpawnInit()
int SpawnInit ()
Definition at line 393 of file KernelThread.cpp.
 {
     const char *envp[5] = {
         "PATH=/bin:/usr/bin",
         "TERM=tty",
         "HOME=/root",
         "USER=root",
         nullptr};
     const char *argv[4] = {
         Config.InitPath,
         "--init",
         "--critical",
         nullptr};
     return Execute::Spawn(Config.InitPath, argv, envp,
                           nullptr,
                           Tasking::TaskCompatibility::Native,
                           true);
 }
References Config, KernelConfig::InitPath, Tasking::Native, and Execute::Spawn().
Referenced by KernelMainThread().
Variable Documentation
DevFS
VirtualFileSystem::Node* DevFS = nullptr
Definition at line 49 of file KernelThread.cpp.
Referenced by Init_Null(), Init_Random(), Init_Teletype(), Init_Zero(), and Main().
DiskManager
Disk::Manager* DiskManager = nullptr
Definition at line 47 of file KernelThread.cpp.
Referenced by BeforeShutdown(), and KernelMainThread().
DriverManager
Driver::Driver* DriverManager = nullptr
Definition at line 46 of file KernelThread.cpp.
Referenced by BeforeShutdown(), Disk::Manager::FetchDisks(), NetworkInterfaceManager::NetworkInterface::FetchNetworkCards(), CrashHandler::Handle(), KernelMainThread(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), Driver::Driver::Panic(), NetworkInterfaceManager::NetworkInterface::Send(), StartAC97(), StartAHCI(), StartATA(), StartGigabit(), StartKernelShell(), StartPCNET(), StartPS2Keyboard(), StartPS2Mouse(), StartRTL8139(), StartVMwareMouse(), and Driver::Driver::UnloadAllDrivers().
FrameCount
size_t FrameCount = 1
Definition at line 417 of file KernelThread.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
Frames
uint8_t* Frames[27]
Definition at line 415 of file KernelThread.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
FrameSizes
uint32_t FrameSizes[27]
Definition at line 416 of file KernelThread.cpp.
Referenced by BootLogoAnimationThread(), and ExitLogoAnimationThread().
MntFS
VirtualFileSystem::Node* MntFS = nullptr
Definition at line 50 of file KernelThread.cpp.
Referenced by Main().
NIManager
NetworkInterfaceManager::NetworkInterface* NIManager = nullptr
Definition at line 48 of file KernelThread.cpp.
Referenced by NetworkIPv4::__no_sanitize(), BeforeShutdown(), NetworkInterfaceManager::CallStartNetworkStackWrapper(), DriverNetReceive(), DriverNetSend(), NetworkInterfaceManager::NetworkInterface::DrvReceive(), NetworkInterfaceManager::NetworkInterface::DrvSend(), KernelMainThread(), NetworkICMPv4::ICMPv4::Receive(), and NetworkEthernet::Ethernet::Send().
ProcFS
VirtualFileSystem::Node* ProcFS = nullptr
Definition at line 51 of file KernelThread.cpp.
Referenced by Main(), and Tasking::PCB::PCB().
VarLogFS
VirtualFileSystem::Node* VarLogFS = nullptr
Definition at line 52 of file KernelThread.cpp.
Referenced by Main().