Fennix: shared_ptr< T > Class Template Reference
shared_ptr< T > Class Template Reference
#include <smartptr.hpp>
Data Structures
class Counter
Public Member Functions
shared_ptr (T *Pointer=nullptr)
shared_ptr (shared_ptr< T > &SPtr)
~shared_ptr ()
unsigned int GetCount ()
T * Get ()
T & operator* ()
T * operator-> ()
void reset (T *Pointer=nullptr)
void reset ()
void swap (shared_ptr< T > &Other)
Private Attributes
Counter * m_ReferenceCounter
T * m_RealPointer
Detailed Description
template<typename T>
class shared_ptr< T >
Definition at line 76 of file smartptr.hpp.
Constructor & Destructor Documentation
shared_ptr() [1/2]
template<typename T > shared_ptr< T >::shared_ptr (T * Pointer = nullptr) inline explicit
Definition at line 130 of file smartptr.hpp.
     {
         m_RealPointer = Pointer;
         m_ReferenceCounter = new Counter();
         spdbg("[%#lx] Shared pointer created (ptr=%#lx, ref=%#lx)", this, Pointer, m_ReferenceCounter);
         if (Pointer)
             (*m_ReferenceCounter)++;
     }
References CPU::Counter(), shared_ptr< T >::m_RealPointer, shared_ptr< T >::m_ReferenceCounter, and spdbg.
shared_ptr() [2/2]
template<typename T > shared_ptr< T >::shared_ptr (shared_ptr< T > & SPtr) inline
Definition at line 139 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer copied (ptr=%#lx, ref=%#lx)", this, SPtr.m_RealPointer, SPtr.m_ReferenceCounter);
         m_RealPointer = SPtr.m_RealPointer;
         m_ReferenceCounter = SPtr.m_ReferenceCounter;
         (*m_ReferenceCounter)++;
     }
References shared_ptr< T >::m_RealPointer, shared_ptr< T >::m_ReferenceCounter, and spdbg.
~shared_ptr()
template<typename T > shared_ptr< T >::~shared_ptr () inline
Definition at line 147 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer destructor called", this);
         (*m_ReferenceCounter)--;
         if (m_ReferenceCounter->Get() == 0)
         {
             spdbg("[%#lx] Shared pointer deleted (ptr=%#lx, ref=%#lx)", this, m_RealPointer, m_ReferenceCounter);
             delete m_ReferenceCounter;
             delete m_RealPointer;
         }
     }
References shared_ptr< T >::Counter::Get(), shared_ptr< T >::m_RealPointer, shared_ptr< T >::m_ReferenceCounter, and spdbg.
Member Function Documentation
Get()
template<typename T > T* shared_ptr< T >::Get () inline
Definition at line 165 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer get (%#lx)", this, m_RealPointer);
         return m_RealPointer;
     }
References shared_ptr< T >::m_RealPointer, and spdbg.
Referenced by VirtualFileSystem::Virtual::Create(), VirtualFileSystem::Virtual::Delete(), Execute::ELFLoad(), VirtualFileSystem::Virtual::GetPathFromNode(), VirtualFileSystem::Virtual::NormalizePath(), and VirtualFileSystem::Virtual::Open().
GetCount()
template<typename T > unsigned int shared_ptr< T >::GetCount () inline
Definition at line 159 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer count (%d)", this, m_ReferenceCounter->Get());
         return m_ReferenceCounter->Get();
     }
References shared_ptr< T >::Counter::Get(), shared_ptr< T >::m_ReferenceCounter, and spdbg.
operator*()
template<typename T > T& shared_ptr< T >::operator* () inline
Definition at line 171 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer dereference (ptr*=%#lx)", this, *m_RealPointer);
         return *m_RealPointer;
     }
References shared_ptr< T >::m_RealPointer, and spdbg.
operator->()
template<typename T > T* shared_ptr< T >::operator-> () inline
Definition at line 177 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer dereference (ptr->%#lx)", this, m_RealPointer);
         return m_RealPointer;
     }
References shared_ptr< T >::m_RealPointer, and spdbg.
reset() [1/2]
template<typename T > void shared_ptr< T >::reset () inline
Definition at line 200 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer reset (ptr=%#lx, ref=%#lx)", this, m_RealPointer, m_ReferenceCounter);
         if (m_ReferenceCounter->Get() == 1)
         {
             delete m_RealPointer;
             delete m_ReferenceCounter;
         }
         else
         {
             (*m_ReferenceCounter)--;
         }
         m_RealPointer = nullptr;
         m_ReferenceCounter = nullptr;
     }
References shared_ptr< T >::Counter::Get(), shared_ptr< T >::m_RealPointer, shared_ptr< T >::m_ReferenceCounter, and spdbg.
reset() [2/2]
template<typename T > void shared_ptr< T >::reset (T * Pointer = nullptr) inline
Definition at line 183 of file smartptr.hpp.
     {
         if (m_RealPointer == Pointer)
             return;
         spdbg("[%#lx] Shared pointer reset (ptr=%#lx, ref=%#lx)", this, Pointer, m_ReferenceCounter);
         (*m_ReferenceCounter)--;
         if (m_ReferenceCounter->Get() == 0)
         {
             delete m_ReferenceCounter;
             delete m_RealPointer;
         }
         m_RealPointer = Pointer;
         m_ReferenceCounter = new Counter();
         if (Pointer)
             (*m_ReferenceCounter)++;
     }
References CPU::Counter(), shared_ptr< T >::Counter::Get(), shared_ptr< T >::m_RealPointer, shared_ptr< T >::m_ReferenceCounter, and spdbg.
Referenced by VirtualFileSystem::Virtual::GetPathFromNode(), and VirtualFileSystem::Virtual::NormalizePath().
swap()
template<typename T > void shared_ptr< T >::swap (shared_ptr< T > & Other) inline
Definition at line 216 of file smartptr.hpp.
     {
         spdbg("[%#lx] Shared pointer swap (ptr=%#lx, ref=%#lx <=> ptr=%#lx, ref=%#lx)",
               this, m_RealPointer, m_ReferenceCounter, Other.m_RealPointer, Other.m_ReferenceCounter);
         T *tempRealPointer = m_RealPointer;
         Counter *tempReferenceCounter = m_ReferenceCounter;
         m_RealPointer = Other.m_RealPointer;
         m_ReferenceCounter = Other.m_ReferenceCounter;
         Other.m_RealPointer = tempRealPointer;
         Other.m_ReferenceCounter = tempReferenceCounter;
     }
References shared_ptr< T >::m_RealPointer, shared_ptr< T >::m_ReferenceCounter, and spdbg.
Field Documentation
m_RealPointer
template<typename T > T* shared_ptr< T >::m_RealPointer private
Definition at line 127 of file smartptr.hpp.
Referenced by shared_ptr< T >::Get(), shared_ptr< T >::operator*(), shared_ptr< T >::operator->(), shared_ptr< T >::reset(), shared_ptr< T >::shared_ptr(), shared_ptr< T >::swap(), and shared_ptr< T >::~shared_ptr().
m_ReferenceCounter
template<typename T > Counter* shared_ptr< T >::m_ReferenceCounter private
Definition at line 126 of file smartptr.hpp.
Referenced by shared_ptr< T >::GetCount(), shared_ptr< T >::reset(), shared_ptr< T >::shared_ptr(), shared_ptr< T >::swap(), and shared_ptr< T >::~shared_ptr().
The documentation for this class was generated from the following file:
Kernel/include/smartptr.hpp