Fennix: Userspace/musl/src/string/strrchr.c File Reference
strrchr.c File Reference
#include <string.h>
Functions
char * strrchr (const char *s, int c)
Function Documentation
strrchr()
char* strrchr (const char * s, int c)
Definition at line 3 of file strrchr.c.
 {
     return __memrchr(s, c, strlen(s) + 1);
 }
References __memrchr(), c, len, NULL, pos, and strlen().
Referenced by __mlibc_gnu_basename_c(), base_pathname(), decode_prompt_string(), dolink(), fixup_rpath(), glob_filename(), glob_name_is_acceptable(), history_expand_internal(), IdentifyIWADByName(), load_library(), M_GetExecutableName(), main(), mktemp_builtin(), phash_search(), printable_part(), realpath(), rindex(), rl_display_match_list(), rl_filename_completion_function(), scan_request(), mlibc::set_startup_data(), and stat_char().