Fennix: Userspace/apps/base/busybox/networking/libiproute/rt_names.c File Reference
rt_names.c File Reference
#include "libbb.h"
#include "rt_names.h"
Data Structures
struct rtnl_tab_t
Macros
#define CONFDIR CONFIG_FEATURE_IP_ROUTE_DIR
#define RT_TABLE_MAX 1023
Typedefs
typedef struct rtnl_tab_t rtnl_tab_t
Functions
static void rtnl_tab_initialize (const char *file, const char **tab)
static int rtnl_a2n (rtnl_tab_t *tab, uint32_t *id, const char *arg, int base)
static void rtnl_rtprot_initialize (void)
int FAST_FUNC rtnl_rtprot_a2n (uint32_t *id, char *arg)
static void rtnl_rtscope_initialize (void)
const char *FAST_FUNC rtnl_rtscope_n2a (int id)
int FAST_FUNC rtnl_rtscope_a2n (uint32_t *id, char *arg)
static void rtnl_rtrealm_initialize (void)
int FAST_FUNC rtnl_rtrealm_a2n (uint32_t *id, char *arg)
static void rtnl_rtdsfield_initialize (void)
const char *FAST_FUNC rtnl_dsfield_n2a (int id)
int FAST_FUNC rtnl_dsfield_a2n (uint32_t *id, char *arg)
Variables
static rtnl_tab_t * rtnl_rtprot_tab
static rtnl_tab_t * rtnl_rtscope_tab
static rtnl_tab_t * rtnl_rtrealm_tab
static rtnl_tab_t * rtnl_rtdsfield_tab
Data Structure Documentation
rtnl_tab_t
struct rtnl_tab_t
Definition at line 15 of file rt_names.c.
Data Fields
unsigned cached_result
const char * cached_str
const char * tab[RT_TABLE_MAX+1]
Macro Definition Documentation
CONFDIR
#define CONFDIR CONFIG_FEATURE_IP_ROUTE_DIR
Definition at line 13 of file rt_names.c.
RT_TABLE_MAX
#define RT_TABLE_MAX 1023
Definition at line 24 of file rt_names.c.
Typedef Documentation
rtnl_tab_t
typedef struct rtnl_tab_t rtnl_tab_t
Function Documentation
rtnl_a2n()
static int rtnl_a2n (rtnl_tab_t * tab, uint32_t * id, const char * arg, int base) static
Definition at line 48 of file rt_names.c.
 {
     unsigned i;
     if (tab->cached_str && strcmp(tab->cached_str, arg) == 0) {
         *id = tab->cached_result;
         return 0;
     }
     for (i = 0; i <= RT_TABLE_MAX; i++) {
         if (tab->tab[i]
          && strcmp(tab->tab[i], arg) == 0
         ) {
             tab->cached_str = tab->tab[i];
             tab->cached_result = i;
             *id = i;
             return 0;
         }
     }
     i = bb_strtou(arg, NULL, base);
     if (i > RT_TABLE_MAX)
         return -1;
     *id = i;
     return 0;
 }
References base, bb_strtou(), i, NULL, RT_TABLE_MAX, strcmp, and tab.
Referenced by rtnl_dsfield_a2n(), rtnl_rtprot_a2n(), rtnl_rtrealm_a2n(), and rtnl_rtscope_a2n().
rtnl_dsfield_a2n()
int FAST_FUNC rtnl_dsfield_a2n (uint32_t * id, char * arg)
Definition at line 215 of file rt_names.c.
 {
     rtnl_rtdsfield_initialize();
     return rtnl_a2n(rtnl_rtdsfield_tab, id, arg, 16);
 }
References rtnl_a2n(), rtnl_rtdsfield_initialize(), and rtnl_rtdsfield_tab.
Referenced by iproute_modify(), iprule_modify(), and parse_args().
rtnl_dsfield_n2a()
const char* FAST_FUNC rtnl_dsfield_n2a (int id)
Definition at line 202 of file rt_names.c.
 {
     if (id < 0 || id > RT_TABLE_MAX) {
         return itoa(id);
     }
     rtnl_rtdsfield_initialize();
     if (rtnl_rtdsfield_tab->tab[id])
         return rtnl_rtdsfield_tab->tab[id];
     return itoa(id);
 }
References itoa, RT_TABLE_MAX, rtnl_rtdsfield_initialize(), rtnl_rtdsfield_tab, and rtnl_tab_t::tab.
Referenced by print_rule(), and print_tunnel().
rtnl_rtdsfield_initialize()
static void rtnl_rtdsfield_initialize (void) static
Definition at line 194 of file rt_names.c.
 {
     if (rtnl_rtdsfield_tab) return;
     rtnl_rtdsfield_tab = xzalloc(sizeof(*rtnl_rtdsfield_tab));
     rtnl_rtdsfield_tab->tab[0] = "0";
     rtnl_tab_initialize("dsfield", rtnl_rtdsfield_tab->tab);
 }
References rtnl_rtdsfield_tab, rtnl_tab_initialize(), rtnl_tab_t::tab, and xzalloc().
Referenced by rtnl_dsfield_a2n(), and rtnl_dsfield_n2a().
rtnl_rtprot_a2n()
int FAST_FUNC rtnl_rtprot_a2n (uint32_t * id, char * arg)
Definition at line 118 of file rt_names.c.
 {
     rtnl_rtprot_initialize();
     return rtnl_a2n(rtnl_rtprot_tab, id, arg, 0);
 }
References rtnl_a2n(), rtnl_rtprot_initialize(), and rtnl_rtprot_tab.
Referenced by iproute_list_or_flush(), and iproute_modify().
rtnl_rtprot_initialize()
static void rtnl_rtprot_initialize (void) static
Definition at line 78 of file rt_names.c.
 {
     static const char *const init_tab[] ALIGN_PTR = {
         "none",
         "redirect",
         "kernel",
         "boot",
         "static",
         NULL,
         NULL,
         NULL,
         "gated",
         "ra",
         "mrt",
         "zebra",
         "bird",
     };
     if (rtnl_rtprot_tab)
         return;
     rtnl_rtprot_tab = xzalloc(sizeof(*rtnl_rtprot_tab));
     memcpy(rtnl_rtprot_tab->tab, init_tab, sizeof(init_tab));
     rtnl_tab_initialize("protos", rtnl_rtprot_tab->tab);
 }
References ALIGN_PTR, memcpy, NULL, rtnl_rtprot_tab, rtnl_tab_initialize(), rtnl_tab_t::tab, and xzalloc().
Referenced by rtnl_rtprot_a2n().
rtnl_rtrealm_a2n()
int FAST_FUNC rtnl_rtrealm_a2n (uint32_t * id, char * arg)
Definition at line 170 of file rt_names.c.
 {
     rtnl_rtrealm_initialize();
     return rtnl_a2n(rtnl_rtrealm_tab, id, arg, 0);
 }
References rtnl_a2n(), rtnl_rtrealm_initialize(), and rtnl_rtrealm_tab.
Referenced by get_rt_realms().
rtnl_rtrealm_initialize()
static void rtnl_rtrealm_initialize (void) static
Definition at line 162 of file rt_names.c.
 {
     if (rtnl_rtrealm_tab) return;
     rtnl_rtrealm_tab = xzalloc(sizeof(*rtnl_rtrealm_tab));
     rtnl_rtrealm_tab->tab[0] = "unknown";
     rtnl_tab_initialize("realms", rtnl_rtrealm_tab->tab);
 }
References rtnl_rtrealm_tab, rtnl_tab_initialize(), rtnl_tab_t::tab, and xzalloc().
Referenced by rtnl_rtrealm_a2n().
rtnl_rtscope_a2n()
int FAST_FUNC rtnl_rtscope_a2n (uint32_t * id, char * arg)
Definition at line 153 of file rt_names.c.
 {
     rtnl_rtscope_initialize();
     return rtnl_a2n(rtnl_rtscope_tab, id, arg, 0);
 }
References rtnl_a2n(), rtnl_rtscope_initialize(), and rtnl_rtscope_tab.
Referenced by ipaddr_list_or_flush(), ipaddr_modify(), iproute_list_or_flush(), and iproute_modify().
rtnl_rtscope_initialize()
static void rtnl_rtscope_initialize (void) static
Definition at line 127 of file rt_names.c.
 {
     if (rtnl_rtscope_tab)
         return;
     rtnl_rtscope_tab = xzalloc(sizeof(*rtnl_rtscope_tab));
     rtnl_rtscope_tab->tab[0] = "global";
     rtnl_rtscope_tab->tab[255] = "nowhere";
     rtnl_rtscope_tab->tab[254] = "host";
     rtnl_rtscope_tab->tab[253] = "link";
     rtnl_rtscope_tab->tab[200] = "site";
     rtnl_tab_initialize("scopes", rtnl_rtscope_tab->tab);
 }
References rtnl_rtscope_tab, rtnl_tab_initialize(), rtnl_tab_t::tab, and xzalloc().
Referenced by rtnl_rtscope_a2n(), and rtnl_rtscope_n2a().
rtnl_rtscope_n2a()
const char* FAST_FUNC rtnl_rtscope_n2a (int id)
Definition at line 140 of file rt_names.c.
 {
     if (id < 0 || id > RT_TABLE_MAX) {
         return itoa(id);
     }
     rtnl_rtscope_initialize();
     if (rtnl_rtscope_tab->tab[id])
         return rtnl_rtscope_tab->tab[id];
     return itoa(id);
 }
References itoa, RT_TABLE_MAX, rtnl_rtscope_initialize(), rtnl_rtscope_tab, and rtnl_tab_t::tab.
Referenced by print_addrinfo(), and print_route().
rtnl_tab_initialize()
static void rtnl_tab_initialize (const char * file, const char ** tab) static
Definition at line 28 of file rt_names.c.
 {
     char *token[2];
     char fullname[sizeof(CONFDIR"/rt_dsfield") + 8];
     parser_t *parser;
     sprintf(fullname, CONFDIR"/rt_%s", file);
     parser = config_open2(fullname, fopen_for_read);
     while (config_read(parser, token, 2, 2, "# \t", PARSE_NORMAL)) {
         unsigned id = bb_strtou(token[0], NULL, 0);
         if (id > RT_TABLE_MAX) {
             bb_error_msg("database %s is corrupted at line %d",
                 file, parser->lineno);
             break;
         }
         tab[id] = xstrdup(token[1]);
     }
     config_close(parser);
 }
References bb_error_msg(), bb_strtou(), CONFDIR, config_close(), config_open2(), config_read, fopen_for_read(), NULL, PARSE_NORMAL, parser, RT_TABLE_MAX, sprintf(), tab, and xstrdup().
Referenced by rtnl_rtdsfield_initialize(), rtnl_rtprot_initialize(), rtnl_rtrealm_initialize(), and rtnl_rtscope_initialize().
Variable Documentation
rtnl_rtdsfield_tab
rtnl_tab_t* rtnl_rtdsfield_tab static
Definition at line 192 of file rt_names.c.
Referenced by rtnl_dsfield_a2n(), rtnl_dsfield_n2a(), and rtnl_rtdsfield_initialize().
rtnl_rtprot_tab
rtnl_tab_t* rtnl_rtprot_tab static
Definition at line 76 of file rt_names.c.
Referenced by rtnl_rtprot_a2n(), and rtnl_rtprot_initialize().
rtnl_rtrealm_tab
rtnl_tab_t* rtnl_rtrealm_tab static
Definition at line 160 of file rt_names.c.
Referenced by rtnl_rtrealm_a2n(), and rtnl_rtrealm_initialize().
rtnl_rtscope_tab
rtnl_tab_t* rtnl_rtscope_tab static
Definition at line 125 of file rt_names.c.
Referenced by rtnl_rtscope_a2n(), rtnl_rtscope_initialize(), and rtnl_rtscope_n2a().