Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_saveg.h File Reference
p_saveg.h File Reference
#include <stdio.h>
Macros
#define SAVESTRINGSIZE 24
Functions
char * P_TempSaveGameFile (void)
char * P_SaveGameFile (int slot)
boolean P_ReadSaveGameHeader (void)
void P_WriteSaveGameHeader (char *description)
boolean P_ReadSaveGameEOF (void)
void P_WriteSaveGameEOF (void)
void P_ArchivePlayers (void)
void P_UnArchivePlayers (void)
void P_ArchiveWorld (void)
void P_UnArchiveWorld (void)
void P_ArchiveThinkers (void)
void P_UnArchiveThinkers (void)
void P_ArchiveSpecials (void)
void P_UnArchiveSpecials (void)
Variables
FILE * save_stream
boolean savegame_error
Macro Definition Documentation
SAVESTRINGSIZE
#define SAVESTRINGSIZE 24
Definition at line 27 of file p_saveg.h.
Function Documentation
P_ArchivePlayers()
void P_ArchivePlayers (void)
Definition at line 1440 of file p_saveg.c.
 {
     int     i;
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     if (!playeringame[i])
         continue;
     saveg_write_pad();
         saveg_write_player_t(&players[i]);
     }
 }
References i, MAXPLAYERS, playeringame, players, saveg_write_pad(), and saveg_write_player_t().
Referenced by G_DoSaveGame().
P_ArchiveSpecials()
void P_ArchiveSpecials (void)
Definition at line 1704 of file p_saveg.c.
 {
     thinker_t*      th;
     int         i;
     // save off the current thinkers
     for (th = thinkercap.next ; th != &thinkercap ; th=th->next)
     {
     if (th->function.acv == (actionf_v)NULL)
     {
         for (i = 0; i < MAXCEILINGS;i++)
         if (activeceilings[i] == (ceiling_t *)th)
             break;
         if (i<MAXCEILINGS)
         {
                 saveg_write8(tc_ceiling);
         saveg_write_pad();
                 saveg_write_ceiling_t((ceiling_t *) th);
         }
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_MoveCeiling)
     {
             saveg_write8(tc_ceiling);
         saveg_write_pad();
             saveg_write_ceiling_t((ceiling_t *) th);
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_VerticalDoor)
     {
             saveg_write8(tc_door);
         saveg_write_pad();
             saveg_write_vldoor_t((vldoor_t *) th);
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_MoveFloor)
     {
             saveg_write8(tc_floor);
         saveg_write_pad();
             saveg_write_floormove_t((floormove_t *) th);
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_PlatRaise)
     {
             saveg_write8(tc_plat);
         saveg_write_pad();
             saveg_write_plat_t((plat_t *) th);
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_LightFlash)
     {
             saveg_write8(tc_flash);
         saveg_write_pad();
             saveg_write_lightflash_t((lightflash_t *) th);
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_StrobeFlash)
     {
             saveg_write8(tc_strobe);
         saveg_write_pad();
             saveg_write_strobe_t((strobe_t *) th);
         continue;
     }
     if (th->function.acp1 == (actionf_p1)T_Glow)
     {
             saveg_write8(tc_glow);
         saveg_write_pad();
             saveg_write_glow_t((glow_t *) th);
         continue;
     }
     }
     // add a terminating marker
     saveg_write8(tc_endspecials);
 }
References actionf_t::acp1, activeceilings, actionf_t::acv, thinker_s::function, i, MAXCEILINGS, thinker_s::next, NULL, saveg_write8(), saveg_write_ceiling_t(), saveg_write_floormove_t(), saveg_write_glow_t(), saveg_write_lightflash_t(), saveg_write_pad(), saveg_write_plat_t(), saveg_write_strobe_t(), saveg_write_vldoor_t(), T_Glow(), T_LightFlash(), T_MoveCeiling(), T_MoveFloor(), T_PlatRaise(), T_StrobeFlash(), T_VerticalDoor(), tc_ceiling, tc_door, tc_endspecials, tc_flash, tc_floor, tc_glow, tc_plat, tc_strobe, and thinkercap.
Referenced by G_DoSaveGame().
P_ArchiveThinkers()
void P_ArchiveThinkers (void)
Definition at line 1592 of file p_saveg.c.
 {
     thinker_t*      th;
     // save off the current thinkers
     for (th = thinkercap.next ; th != &thinkercap ; th=th->next)
     {
     if (th->function.acp1 == (actionf_p1)P_MobjThinker)
     {
             saveg_write8(tc_mobj);
         saveg_write_pad();
             saveg_write_mobj_t((mobj_t *) th);
         continue;
     }
     // I_Error ("P_ArchiveThinkers: Unknown thinker function");
     }
     // add a terminating marker
     saveg_write8(tc_end);
 }
References actionf_t::acp1, thinker_s::function, thinker_s::next, P_MobjThinker(), saveg_write8(), saveg_write_mobj_t(), saveg_write_pad(), tc_end, tc_mobj, and thinkercap.
Referenced by G_DoSaveGame().
P_ArchiveWorld()
void P_ArchiveWorld (void)
Definition at line 1484 of file p_saveg.c.
 {
     int         i;
     int         j;
     sector_t*       sec;
     line_t*     li;
     side_t*     si;
     // do sectors
     for (i=0, sec = sectors ; i<numsectors ; i++,sec++)
     {
     saveg_write16(sec->floorheight >> FRACBITS);
     saveg_write16(sec->ceilingheight >> FRACBITS);
     saveg_write16(sec->floorpic);
     saveg_write16(sec->ceilingpic);
     saveg_write16(sec->lightlevel);
     saveg_write16(sec->special);        // needed?
     saveg_write16(sec->tag);        // needed?
     }
     // do lines
     for (i=0, li = lines ; i<numlines ; i++,li++)
     {
     saveg_write16(li->flags);
     saveg_write16(li->special);
     saveg_write16(li->tag);
     for (j=0 ; j<2 ; j++)
     {
         if (li->sidenum[j] == -1)
         continue;
         si = &sides[li->sidenum[j]];
         saveg_write16(si->textureoffset >> FRACBITS);
         saveg_write16(si->rowoffset >> FRACBITS);
         saveg_write16(si->toptexture);
         saveg_write16(si->bottomtexture);
         saveg_write16(si->midtexture);
     }
     }
 }
References side_t::bottomtexture, sector_t::ceilingheight, sector_t::ceilingpic, line_s::flags, sector_t::floorheight, sector_t::floorpic, FRACBITS, i, j, sector_t::lightlevel, lines, side_t::midtexture, numlines, numsectors, side_t::rowoffset, saveg_write16(), sectors, line_s::sidenum, sides, sector_t::special, line_s::special, sector_t::tag, line_s::tag, side_t::textureoffset, and side_t::toptexture.
Referenced by G_DoSaveGame().
P_ReadSaveGameEOF()
boolean P_ReadSaveGameEOF (void)
Definition at line 1419 of file p_saveg.c.
 {
     int value;
     value = saveg_read8();
     return value == SAVEGAME_EOF;
 }
References saveg_read8(), SAVEGAME_EOF, and value.
Referenced by G_DoLoadGame().
P_ReadSaveGameHeader()
boolean P_ReadSaveGameHeader (void)
Definition at line 1379 of file p_saveg.c.
 {
     int  i;
     byte a, b, c;
     char vcheck[VERSIONSIZE];
     char read_vcheck[VERSIONSIZE];
     // skip the description field
     for (i=0; i<SAVESTRINGSIZE; ++i)
         saveg_read8();
     for (i=0; i<VERSIONSIZE; ++i)
         read_vcheck[i] = saveg_read8();
     memset(vcheck, 0, sizeof(vcheck));
     M_snprintf(vcheck, sizeof(vcheck), "version %i", G_VanillaVersionCode());
     if (strcmp(read_vcheck, vcheck) != 0)
     return false;               // bad version
     gameskill = saveg_read8();
     gameepisode = saveg_read8();
     gamemap = saveg_read8();
     for (i=0 ; i<MAXPLAYERS ; i++)
     playeringame[i] = saveg_read8();
     // get the times
     a = saveg_read8();
     b = saveg_read8();
     c = saveg_read8();
     leveltime = (a<<16) + (b<<8) + c;
     return true;
 }
References b, c, G_VanillaVersionCode(), gameepisode, gamemap, gameskill, i, leveltime, M_snprintf(), MAXPLAYERS, memset, playeringame, saveg_read8(), SAVESTRINGSIZE, strcmp(), and VERSIONSIZE.
Referenced by G_DoLoadGame().
P_SaveGameFile()
char* P_SaveGameFile (int slot)
Definition at line 61 of file p_saveg.c.
 {
     static char *filename = NULL;
     static size_t filename_size = 0;
     char basename[32];
     if (filename == NULL)
     {
         filename_size = strlen(savegamedir) + 32;
         filename = malloc(filename_size);
     }
     DEH_snprintf(basename, 32, SAVEGAMENAME "%d.dsg", slot);
     M_snprintf(filename, filename_size, "%s%s", savegamedir, basename);
     return filename;
 }
References basename, DEH_snprintf, M_snprintf(), malloc(), NULL, savegamedir, SAVEGAMENAME, and strlen().
Referenced by D_DoomMain(), G_DoSaveGame(), M_LoadSelect(), and M_ReadSaveStrings().
P_TempSaveGameFile()
char* P_TempSaveGameFile (void)
Definition at line 47 of file p_saveg.c.
 {
     static char *filename = NULL;
     if (filename == NULL)
     {
         filename = M_StringJoin(savegamedir, "temp.dsg", NULL);
     }
     return filename;
 }
References M_StringJoin(), NULL, and savegamedir.
Referenced by G_DoSaveGame().
P_UnArchivePlayers()
void P_UnArchivePlayers (void)
Definition at line 1460 of file p_saveg.c.
 {
     int     i;
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     if (!playeringame[i])
         continue;
     saveg_read_pad();
         saveg_read_player_t(&players[i]);
     // will be set when unarc thinker
     players[i].mo = NULL;
     players[i].message = NULL;
     players[i].attacker = NULL;
     }
 }
References player_s::attacker, i, MAXPLAYERS, player_s::message, player_s::mo, NULL, playeringame, players, saveg_read_pad(), and saveg_read_player_t().
Referenced by G_DoLoadGame().
P_UnArchiveSpecials()
void P_UnArchiveSpecials (void)
Definition at line 1793 of file p_saveg.c.
 {
     byte        tclass;
     ceiling_t*      ceiling;
     vldoor_t*       door;
     floormove_t*    floor;
     plat_t*     plat;
     lightflash_t*   flash;
     strobe_t*       strobe;
     glow_t*     glow;
     // read in saved thinkers
     while (1)
     {
     tclass = saveg_read8();
     switch (tclass)
     {
       case tc_endspecials:
         return; // end of list
       case tc_ceiling:
         saveg_read_pad();
         ceiling = Z_Malloc (sizeof(*ceiling), PU_LEVEL, NULL);
             saveg_read_ceiling_t(ceiling);
         ceiling->sector->specialdata = ceiling;
         if (ceiling->thinker.function.acp1)
         ceiling->thinker.function.acp1 = (actionf_p1)T_MoveCeiling;
         P_AddThinker (&ceiling->thinker);
         P_AddActiveCeiling(ceiling);
         break;
       case tc_door:
         saveg_read_pad();
         door = Z_Malloc (sizeof(*door), PU_LEVEL, NULL);
             saveg_read_vldoor_t(door);
         door->sector->specialdata = door;
         door->thinker.function.acp1 = (actionf_p1)T_VerticalDoor;
         P_AddThinker (&door->thinker);
         break;
       case tc_floor:
         saveg_read_pad();
         floor = Z_Malloc (sizeof(*floor), PU_LEVEL, NULL);
             saveg_read_floormove_t(floor);
         floor->sector->specialdata = floor;
         floor->thinker.function.acp1 = (actionf_p1)T_MoveFloor;
         P_AddThinker (&floor->thinker);
         break;
       case tc_plat:
         saveg_read_pad();
         plat = Z_Malloc (sizeof(*plat), PU_LEVEL, NULL);
             saveg_read_plat_t(plat);
         plat->sector->specialdata = plat;
         if (plat->thinker.function.acp1)
         plat->thinker.function.acp1 = (actionf_p1)T_PlatRaise;
         P_AddThinker (&plat->thinker);
         P_AddActivePlat(plat);
         break;
       case tc_flash:
         saveg_read_pad();
         flash = Z_Malloc (sizeof(*flash), PU_LEVEL, NULL);
             saveg_read_lightflash_t(flash);
         flash->thinker.function.acp1 = (actionf_p1)T_LightFlash;
         P_AddThinker (&flash->thinker);
         break;
       case tc_strobe:
         saveg_read_pad();
         strobe = Z_Malloc (sizeof(*strobe), PU_LEVEL, NULL);
             saveg_read_strobe_t(strobe);
         strobe->thinker.function.acp1 = (actionf_p1)T_StrobeFlash;
         P_AddThinker (&strobe->thinker);
         break;
       case tc_glow:
         saveg_read_pad();
         glow = Z_Malloc (sizeof(*glow), PU_LEVEL, NULL);
             saveg_read_glow_t(glow);
         glow->thinker.function.acp1 = (actionf_p1)T_Glow;
         P_AddThinker (&glow->thinker);
         break;
       default:
         I_Error ("P_UnarchiveSpecials:Unknown tclass %i "
              "in savegame",tclass);
     }
     }
 }
References actionf_t::acp1, floor(), thinker_s::function, I_Error(), NULL, P_AddActiveCeiling(), P_AddActivePlat(), P_AddThinker(), PU_LEVEL, saveg_read8(), saveg_read_ceiling_t(), saveg_read_floormove_t(), saveg_read_glow_t(), saveg_read_lightflash_t(), saveg_read_pad(), saveg_read_plat_t(), saveg_read_strobe_t(), saveg_read_vldoor_t(), plat_t::sector, vldoor_t::sector, ceiling_t::sector, sector_t::specialdata, T_Glow(), T_LightFlash(), T_MoveCeiling(), T_MoveFloor(), T_PlatRaise(), T_StrobeFlash(), T_VerticalDoor(), tc_ceiling, tc_door, tc_endspecials, tc_flash, tc_floor, tc_glow, tc_plat, tc_strobe, lightflash_t::thinker, strobe_t::thinker, glow_t::thinker, plat_t::thinker, vldoor_t::thinker, ceiling_t::thinker, and Z_Malloc().
Referenced by G_DoLoadGame().
P_UnArchiveThinkers()
void P_UnArchiveThinkers (void)
Definition at line 1620 of file p_saveg.c.
 {
     byte        tclass;
     thinker_t*      currentthinker;
     thinker_t*      next;
     mobj_t*     mobj;
     // remove all the current thinkers
     currentthinker = thinkercap.next;
     while (currentthinker != &thinkercap)
     {
     next = currentthinker->next;
     if (currentthinker->function.acp1 == (actionf_p1)P_MobjThinker)
         P_RemoveMobj ((mobj_t *)currentthinker);
     else
         Z_Free (currentthinker);
     currentthinker = next;
     }
     P_InitThinkers ();
     // read in saved thinkers
     while (1)
     {
     tclass = saveg_read8();
     switch (tclass)
     {
       case tc_end:
         return;     // end of list
       case tc_mobj:
         saveg_read_pad();
         mobj = Z_Malloc (sizeof(*mobj), PU_LEVEL, NULL);
             saveg_read_mobj_t(mobj);
         mobj->target = NULL;
             mobj->tracer = NULL;
         P_SetThingPosition (mobj);
         mobj->info = &mobjinfo[mobj->type];
         mobj->floorz = mobj->subsector->sector->floorheight;
         mobj->ceilingz = mobj->subsector->sector->ceilingheight;
         mobj->thinker.function.acp1 = (actionf_p1)P_MobjThinker;
         P_AddThinker (&mobj->thinker);
         break;
       default:
         I_Error ("Unknown tclass %i in savegame",tclass);
     }
     }
 }
References actionf_t::acp1, sector_t::ceilingheight, mobj_s::ceilingz, sector_t::floorheight, mobj_s::floorz, thinker_s::function, I_Error(), mobj_s::info, mobjinfo, thinker_s::next, NULL, P_AddThinker(), P_InitThinkers(), P_MobjThinker(), P_RemoveMobj(), P_SetThingPosition(), PU_LEVEL, saveg_read8(), saveg_read_mobj_t(), saveg_read_pad(), subsector_s::sector, mobj_s::subsector, mobj_s::target, tc_end, tc_mobj, mobj_s::thinker, thinkercap, mobj_s::tracer, mobj_s::type, Z_Free(), and Z_Malloc().
Referenced by G_DoLoadGame().
P_UnArchiveWorld()
void P_UnArchiveWorld (void)
Definition at line 1532 of file p_saveg.c.
 {
     int         i;
     int         j;
     sector_t*       sec;
     line_t*     li;
     side_t*     si;
     // do sectors
     for (i=0, sec = sectors ; i<numsectors ; i++,sec++)
     {
     sec->floorheight = saveg_read16() << FRACBITS;
     sec->ceilingheight = saveg_read16() << FRACBITS;
     sec->floorpic = saveg_read16();
     sec->ceilingpic = saveg_read16();
     sec->lightlevel = saveg_read16();
     sec->special = saveg_read16();      // needed?
     sec->tag = saveg_read16();      // needed?
     sec->specialdata = 0;
     sec->soundtarget = 0;
     }
     // do lines
     for (i=0, li = lines ; i<numlines ; i++,li++)
     {
     li->flags = saveg_read16();
     li->special = saveg_read16();
     li->tag = saveg_read16();
     for (j=0 ; j<2 ; j++)
     {
         if (li->sidenum[j] == -1)
         continue;
         si = &sides[li->sidenum[j]];
         si->textureoffset = saveg_read16() << FRACBITS;
         si->rowoffset = saveg_read16() << FRACBITS;
         si->toptexture = saveg_read16();
         si->bottomtexture = saveg_read16();
         si->midtexture = saveg_read16();
     }
     }
 }
References side_t::bottomtexture, sector_t::ceilingheight, sector_t::ceilingpic, line_s::flags, sector_t::floorheight, sector_t::floorpic, FRACBITS, i, j, sector_t::lightlevel, lines, side_t::midtexture, numlines, numsectors, side_t::rowoffset, saveg_read16(), sectors, line_s::sidenum, sides, sector_t::soundtarget, sector_t::special, line_s::special, sector_t::specialdata, sector_t::tag, line_s::tag, side_t::textureoffset, and side_t::toptexture.
Referenced by G_DoLoadGame().
P_WriteSaveGameEOF()
void P_WriteSaveGameEOF (void)
Definition at line 1432 of file p_saveg.c.
 {
     saveg_write8(SAVEGAME_EOF);
 }
References saveg_write8(), and SAVEGAME_EOF.
Referenced by G_DoSaveGame().
P_WriteSaveGameHeader()
void P_WriteSaveGameHeader (char * description)
Definition at line 1347 of file p_saveg.c.
 {
     char name[VERSIONSIZE];
     int i;
     for (i=0; description[i] != '\0'; ++i)
         saveg_write8(description[i]);
     for (; i<SAVESTRINGSIZE; ++i)
         saveg_write8(0);
     memset(name, 0, sizeof(name));
     M_snprintf(name, sizeof(name), "version %i", G_VanillaVersionCode());
     for (i=0; i<VERSIONSIZE; ++i)
         saveg_write8(name[i]);
     saveg_write8(gameskill);
     saveg_write8(gameepisode);
     saveg_write8(gamemap);
     for (i=0 ; i<MAXPLAYERS ; i++)
         saveg_write8(playeringame[i]);
     saveg_write8((leveltime >> 16) & 0xff);
     saveg_write8((leveltime >> 8) & 0xff);
     saveg_write8(leveltime & 0xff);
 }
References G_VanillaVersionCode(), gameepisode, gamemap, gameskill, i, leveltime, M_snprintf(), MAXPLAYERS, memset, name, playeringame, saveg_write8(), SAVESTRINGSIZE, and VERSIONSIZE.
Referenced by G_DoSaveGame().
Variable Documentation
save_stream
FILE* save_stream extern
Definition at line 39 of file p_saveg.c.
Referenced by G_DoLoadGame(), G_DoSaveGame(), saveg_read8(), saveg_read_pad(), saveg_write8(), and saveg_write_pad().
savegame_error
boolean savegame_error extern
Definition at line 41 of file p_saveg.c.
Referenced by G_DoLoadGame(), G_DoSaveGame(), saveg_read8(), and saveg_write8().