Fennix Userspace: Userspace/apps/base/bash/lib/readline/examples/rl.c File Reference
rl.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <readline/readline.h>
#include <readline/history.h>
Functions
void exit ()
char * strrchr ()
static int set_deftext ()
static void usage ()
int main (int argc, char **argv)
Variables
int optind
char * optarg
static char * progname
static char * deftext
Function Documentation
exit()
void exit ()
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 85 of file rl.c.
 {
   char *temp, *prompt;
   struct stat sb;
   int opt, fd, nch;
   FILE *ifp;
   progname = strrchr(argv[0], '/');
   if (progname == 0)
     progname = argv[0];
   else
     progname++;
 #ifdef HAVE_SETLOCALE
   setlocale (LC_ALL, "");
 #endif
   /* defaults */
   prompt = "readline$ ";
   fd = nch = 0;
   deftext = (char *)0;
   while ((opt = getopt(argc, argv, "p:u:d:n:")) != EOF)
     {
       switch (opt)
     {
     case 'p':
       prompt = optarg;
       break;
     case 'u':
       fd = atoi(optarg);
       if (fd < 0)
         {
           fprintf (stderr, "%s: bad file descriptor `%s'\n", progname, optarg);
           exit (2);
         }
       break;
     case 'd':
       deftext = optarg;
       break;
     case 'n':
       nch = atoi(optarg);
       if (nch < 0)
         {
           fprintf (stderr, "%s: bad value for -n: `%s'\n", progname, optarg);
           exit (2);
         }
       break;
     default:
       usage ();
       exit (2);
     }
     }
   if (fd != 0)
     {
       if (fstat (fd, &sb) < 0)
     {
       fprintf (stderr, "%s: %d: bad file descriptor\n", progname, fd);
       exit (1);
     }
       ifp = fdopen (fd, "r");
       rl_instream = ifp;
     }
   if (deftext && *deftext)
     rl_startup_hook = set_deftext;
   if (nch > 0)
     rl_num_chars_to_read = nch;
   temp = readline (prompt);
   /* Test for EOF. */
   if (temp == 0)
     exit (1);
   printf ("%s\n", temp);
   exit (0);
 }
References argc, argv, atoi(), deftext, EOF, exit(), fdopen(), fprintf(), fstat(), getopt(), LC_ALL, optarg, printf(), progname, prompt, readline(), rl_instream, rl_num_chars_to_read, rl_startup_hook, set_deftext(), setlocale, stderr, strrchr(), and usage().
set_deftext()
static int set_deftext () static
Definition at line 66 of file rl.c.
 {
   if (deftext)
     {
       rl_insert_text (deftext);
       deftext = (char *)NULL;
       rl_startup_hook = (rl_hook_func_t *)NULL;
     }
   return 0;
 }
References deftext, NULL, rl_insert_text(), and rl_startup_hook.
Referenced by main().
strrchr()
char* strrchr ()
Referenced by main().
usage()
static void usage (void) static
Definition at line 78 of file rl.c.
 {
   fprintf (stderr, "%s: usage: %s [-p prompt] [-u unit] [-d default] [-n nchars]\n",
         progname, progname);
 }
References fprintf(), progname, and stderr.
Referenced by __wait3_time32(), __wait4_time32(), alloc_group(), getrusage(), main(), malloc(), nontrivial_free(), mlibc::sys_getrusage(), and wait3().
Variable Documentation
deftext
char* deftext static
Definition at line 63 of file rl.c.
Referenced by main(), and set_deftext().
optarg
char* optarg extern
Definition at line 12 of file getopt-stubs.cpp.
Referenced by __getopt_long_core(), getopt(), and main().
optind
int optind extern
Definition at line 13 of file getopt-stubs.cpp.
Referenced by __getopt_long(), __getopt_long_core(), and getopt().
progname
char* progname static
Definition at line 62 of file rl.c.
Referenced by main(), and usage().