Fennix: Userspace/musl/include/poll.h File Reference
poll.h File Reference
#include <features.h>
#include <bits/poll.h>
Data Structures
struct pollfd
Macros
#define POLLIN 0x001
#define POLLPRI 0x002
#define POLLOUT 0x004
#define POLLERR 0x008
#define POLLHUP 0x010
#define POLLNVAL 0x020
#define POLLRDNORM 0x040
#define POLLRDBAND 0x080
#define POLLWRNORM 0x100
#define POLLWRBAND 0x200
#define POLLMSG 0x400
#define POLLRDHUP 0x2000
Typedefs
typedef unsigned long nfds_t
Functions
int poll (struct pollfd *, nfds_t, int)
Data Structure Documentation
pollfd
struct pollfd
Definition at line 31 of file poll.h.
Data Fields
short events
int fd
short revents
Macro Definition Documentation
POLLERR
#define POLLERR 0x008
Definition at line 15 of file poll.h.
POLLHUP
#define POLLHUP 0x010
Definition at line 16 of file poll.h.
POLLIN
#define POLLIN 0x001
Definition at line 12 of file poll.h.
POLLMSG
#define POLLMSG 0x400
Definition at line 25 of file poll.h.
POLLNVAL
#define POLLNVAL 0x020
Definition at line 17 of file poll.h.
POLLOUT
#define POLLOUT 0x004
Definition at line 14 of file poll.h.
POLLPRI
#define POLLPRI 0x002
Definition at line 13 of file poll.h.
POLLRDBAND
#define POLLRDBAND 0x080
Definition at line 19 of file poll.h.
POLLRDHUP
#define POLLRDHUP 0x2000
Definition at line 26 of file poll.h.
POLLRDNORM
#define POLLRDNORM 0x040
Definition at line 18 of file poll.h.
POLLWRBAND
#define POLLWRBAND 0x200
Definition at line 22 of file poll.h.
POLLWRNORM
#define POLLWRNORM 0x100
Definition at line 21 of file poll.h.
Typedef Documentation
nfds_t
typedef unsigned long nfds_t
Definition at line 29 of file poll.h.
Function Documentation
poll()
int poll (struct pollfd * fds, nfds_t n, int timeout)
Definition at line 6 of file poll.c.
 {
 #ifdef SYS_poll
     return syscall_cp(SYS_poll, fds, n, timeout);
 #else
 #if SYS_ppoll_time64 == SYS_ppoll
     typedef long long ppoll_ts_t[2];
 #else
     typedef long ppoll_ts_t[2];
 #endif
     return syscall_cp(SYS_ppoll, fds, n, timeout>=0 ?
         ((ppoll_ts_t){ timeout/1000, timeout%1000*1000000 }) : 0,
         0, _NSIG/8);
 #endif
 }
References _NSIG, n, SYS_ppoll, syscall_cp, and timeout().
Referenced by __res_msend_rc(), buffer_pread(), chat_main(), conspy_main(), getch_nowait(), ifplugd_main(), inotifyd_main(), microcom_main(), ntpd_main(), read_key(), read_new_seed(), readwrite(), refill_HFILE_and_getc(), runsv_main(), runsvdir_main(), safe_poll(), script_main(), shell_builtin_read(), telnet_main(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), and wait_for_input().