Fennix: Userspace/musl/src/process/execl.c File Reference
execl.c File Reference
#include <unistd.h>
#include <stdarg.h>
Functions
int execl (const char *path, const char *argv0,...)
Function Documentation
execl()
int execl (const char * path, const char * argv0, ...)
Definition at line 4 of file execl.c.
 {
     int argc;
     va_list ap;
     va_start(ap, argv0);
     for (argc=1; va_arg(ap, const char *); argc++);
     va_end(ap);
     {
         int i;
         char *argv[argc+1];
         va_start(ap, argv0);
         argv[0] = (char *)argv0;
         for (i=1; i<argc; i++)
             argv[i] = va_arg(ap, char *);
         argv[i] = NULL;
         va_end(ap);
         return execv(path, argv);
     }
 }
References argc, argv, ENOSYS, errno, execv(), i, NULL, va_arg, va_end(), and va_start().
Referenced by do_wordexp(), and we_askshell().