Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_tick.h File Reference
p_tick.h File Reference
Functions
void P_Ticker (void)
Function Documentation
P_Ticker()
void P_Ticker (void)
Definition at line 123 of file p_tick.c.
 {
     int     i;
     // run the tic
     if (paused)
     return;
     // pause if in menu and at least one tic has been run
     if ( !netgame
      && menuactive
      && !demoplayback
      && players[consoleplayer].viewz != 1)
     {
     return;
     }
     for (i=0 ; i<MAXPLAYERS ; i++)
     if (playeringame[i])
         P_PlayerThink (&players[i]);
     P_RunThinkers ();
     P_UpdateSpecials ();
     P_RespawnSpecials ();
     // for par times
     leveltime++;
 }
References consoleplayer, demoplayback, i, leveltime, MAXPLAYERS, menuactive, netgame, P_PlayerThink(), P_RespawnSpecials(), P_RunThinkers(), P_UpdateSpecials(), paused, playeringame, players, and viewz.
Referenced by G_Ticker().