Fennix: Userspace/apps/base/busybox/archival/tar.c File Reference
tar.c File Reference
#include <fnmatch.h>
#include "libbb.h"
#include "common_bufsiz.h"
#include "bb_archive.h"
Macros
#define FNM_LEADING_DIR 0
#define DBG(...) ((void)0)
#define DBG_OPTION_PARSING 0
#define block_buf bb_common_bufsiz1
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define GETOPT32 getopt32
#define LONGOPTS
Enumerations
enum {
OPTBIT_KEEP_OLD = 8 , IF_FEATURE_SEAMLESS_Z , OPT_TEST = 1 << 0 , OPT_EXTRACT = 1 << 1 ,
OPT_BASEDIR = 1 << 2 , OPT_TARNAME = 1 << 3 , OPT_2STDOUT = 1 << 4 , OPT_NOPRESERVE_OWNER = 1 << 5 ,
OPT_P = 1 << 6 , OPT_VERBOSE = 1 << 7 , OPT_KEEP_OLD = 1 << 8 , OPT_CREATE = IF_FEATURE_TAR_CREATE((1 << OPTBIT_CREATE)) + 0 ,
OPT_DEREFERENCE = IF_FEATURE_TAR_CREATE((1 << OPTBIT_DEREFERENCE)) + 0 , OPT_BZIP2 = IF_FEATURE_SEAMLESS_BZ2((1 << OPTBIT_BZIP2)) + 0 , OPT_INCLUDE_FROM = IF_FEATURE_TAR_FROM((1 << OPTBIT_INCLUDE_FROM)) + 0 , OPT_EXCLUDE_FROM = IF_FEATURE_TAR_FROM((1 << OPTBIT_EXCLUDE_FROM)) + 0 ,
OPT_GZIP = IF_FEATURE_SEAMLESS_GZ((1 << OPTBIT_GZIP)) + 0 , OPT_XZ = IF_FEATURE_SEAMLESS_XZ((1 << OPTBIT_XZ)) + 0 , OPT_COMPRESS = IF_FEATURE_SEAMLESS_Z((1 << OPTBIT_COMPRESS)) + 0 , OPT_AUTOCOMPRESS_BY_EXT = 1 << OPTBIT_AUTOCOMPRESS_BY_EXT ,
OPT_NOPRESERVE_TIME = IF_FEATURE_TAR_NOPRESERVE_TIME((1 << OPTBIT_NOPRESERVE_TIME)) + 0 , OPT_STRIP_COMPONENTS = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_STRIP_COMPONENTS)) + 0 , OPT_LZMA = IF_FEATURE_TAR_LONG_OPTIONS(IF_FEATURE_SEAMLESS_LZMA((1 << OPTBIT_LZMA))) + 0 , OPT_NORECURSION = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_NORECURSION)) + 0 ,
OPT_2COMMAND = IF_FEATURE_TAR_TO_COMMAND((1 << OPTBIT_2COMMAND)) + 0 , OPT_NUMERIC_OWNER = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_NUMERIC_OWNER)) + 0 , OPT_NOPRESERVE_PERM = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_NOPRESERVE_PERM)) + 0 , OPT_OVERWRITE = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_OVERWRITE)) + 0 ,
OPT_ANY_COMPRESS = (OPT_BZIP2 | OPT_LZMA | OPT_GZIP | OPT_XZ | OPT_COMPRESS)
}
Functions
int tar_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
block_buf
#define block_buf bb_common_bufsiz1
Definition at line 135 of file tar.c.
DBG
#define DBG (...) ((void)0)
Definition at line 130 of file tar.c.
DBG_OPTION_PARSING
#define DBG_OPTION_PARSING 0
Definition at line 132 of file tar.c.
FNM_LEADING_DIR
#define FNM_LEADING_DIR 0
Definition at line 124 of file tar.c.
GETOPT32
#define GETOPT32 getopt32
Definition at line 927 of file tar.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 136 of file tar.c.
LONGOPTS
#define LONGOPTS
Definition at line 928 of file tar.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTBIT_KEEP_OLD
IF_FEATURE_SEAMLESS_Z
OPT_TEST
OPT_EXTRACT
OPT_BASEDIR
OPT_TARNAME
OPT_2STDOUT
OPT_NOPRESERVE_OWNER
OPT_P
OPT_VERBOSE
OPT_KEEP_OLD
OPT_CREATE
OPT_DEREFERENCE
OPT_BZIP2
OPT_INCLUDE_FROM
OPT_EXCLUDE_FROM
OPT_GZIP
OPT_XZ
OPT_COMPRESS
OPT_AUTOCOMPRESS_BY_EXT
OPT_NOPRESERVE_TIME
OPT_STRIP_COMPONENTS
OPT_LZMA
OPT_NORECURSION
OPT_2COMMAND
OPT_NUMERIC_OWNER
OPT_NOPRESERVE_PERM
OPT_OVERWRITE
OPT_ANY_COMPRESS
Definition at line 816 of file tar.c.
      {
     OPTBIT_KEEP_OLD = 8,
     IF_FEATURE_TAR_CREATE(   OPTBIT_CREATE      ,)
     IF_FEATURE_TAR_CREATE(   OPTBIT_DEREFERENCE ,)
     IF_FEATURE_SEAMLESS_BZ2( OPTBIT_BZIP2       ,)
     IF_FEATURE_TAR_FROM(     OPTBIT_INCLUDE_FROM,)
     IF_FEATURE_TAR_FROM(     OPTBIT_EXCLUDE_FROM,)
     IF_FEATURE_SEAMLESS_GZ(  OPTBIT_GZIP        ,)
     IF_FEATURE_SEAMLESS_XZ(  OPTBIT_XZ          ,)
     IF_FEATURE_SEAMLESS_Z(   OPTBIT_COMPRESS    ,) // 16th bit
     OPTBIT_AUTOCOMPRESS_BY_EXT,
     IF_FEATURE_TAR_NOPRESERVE_TIME(OPTBIT_NOPRESERVE_TIME,)
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS
     OPTBIT_STRIP_COMPONENTS,
     IF_FEATURE_SEAMLESS_LZMA(OPTBIT_LZMA        ,)
     OPTBIT_NORECURSION,
     IF_FEATURE_TAR_TO_COMMAND(OPTBIT_2COMMAND   ,)
     OPTBIT_NUMERIC_OWNER,
     OPTBIT_NOPRESERVE_PERM,
     OPTBIT_OVERWRITE,
 #endif
     OPT_TEST         = 1 << 0, // t
     OPT_EXTRACT      = 1 << 1, // x
     OPT_BASEDIR      = 1 << 2, // C
     OPT_TARNAME      = 1 << 3, // f
     OPT_2STDOUT      = 1 << 4, // O
     OPT_NOPRESERVE_OWNER = 1 << 5, // o == no-same-owner
     OPT_P            = 1 << 6, // p
     OPT_VERBOSE      = 1 << 7, // v
     OPT_KEEP_OLD     = 1 << 8, // k
     OPT_CREATE       = IF_FEATURE_TAR_CREATE(   (1 << OPTBIT_CREATE      )) + 0, // c
     OPT_DEREFERENCE  = IF_FEATURE_TAR_CREATE(   (1 << OPTBIT_DEREFERENCE )) + 0, // h
     OPT_BZIP2        = IF_FEATURE_SEAMLESS_BZ2( (1 << OPTBIT_BZIP2       )) + 0, // j
     OPT_INCLUDE_FROM = IF_FEATURE_TAR_FROM(     (1 << OPTBIT_INCLUDE_FROM)) + 0, // T
     OPT_EXCLUDE_FROM = IF_FEATURE_TAR_FROM(     (1 << OPTBIT_EXCLUDE_FROM)) + 0, // X
     OPT_GZIP         = IF_FEATURE_SEAMLESS_GZ(  (1 << OPTBIT_GZIP        )) + 0, // z
     OPT_XZ           = IF_FEATURE_SEAMLESS_XZ(  (1 << OPTBIT_XZ          )) + 0, // J
     OPT_COMPRESS     = IF_FEATURE_SEAMLESS_Z(   (1 << OPTBIT_COMPRESS    )) + 0, // Z
     OPT_AUTOCOMPRESS_BY_EXT = 1 << OPTBIT_AUTOCOMPRESS_BY_EXT,                   // a
     OPT_NOPRESERVE_TIME  = IF_FEATURE_TAR_NOPRESERVE_TIME((1 << OPTBIT_NOPRESERVE_TIME)) + 0, // m
     OPT_STRIP_COMPONENTS = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_STRIP_COMPONENTS)) + 0, // strip-components
     OPT_LZMA             = IF_FEATURE_TAR_LONG_OPTIONS(IF_FEATURE_SEAMLESS_LZMA((1 << OPTBIT_LZMA))) + 0, // lzma
     OPT_NORECURSION      = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_NORECURSION    )) + 0, // no-recursion
     OPT_2COMMAND         = IF_FEATURE_TAR_TO_COMMAND(  (1 << OPTBIT_2COMMAND       )) + 0, // to-command
     OPT_NUMERIC_OWNER    = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_NUMERIC_OWNER  )) + 0, // numeric-owner
     OPT_NOPRESERVE_PERM  = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_NOPRESERVE_PERM)) + 0, // no-same-permissions
     OPT_OVERWRITE        = IF_FEATURE_TAR_LONG_OPTIONS((1 << OPTBIT_OVERWRITE      )) + 0, // overwrite
     OPT_ANY_COMPRESS = (OPT_BZIP2 | OPT_LZMA | OPT_GZIP | OPT_XZ | OPT_COMPRESS),
 };
Function Documentation
tar_main()
int tar_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 932 of file tar.c.
 {
     archive_handle_t *tar_handle;
     char *base_dir = NULL;
     const char *tar_filename = "-";
     unsigned opt;
     int verboseFlag = 0;
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS && ENABLE_FEATURE_TAR_FROM
     llist_t *excludes = NULL;
 #endif
     INIT_G();
     /* Initialise default values */
     tar_handle = init_handle();
     tar_handle->ah_flags = ARCHIVE_CREATE_LEADING_DIRS
                          | ARCHIVE_RESTORE_DATE
                          | ARCHIVE_UNLINK_OLD;
     /* Apparently only root's tar preserves perms (see bug 3844) */
     if (getuid() != 0)
         tar_handle->ah_flags |= ARCHIVE_DONT_RESTORE_PERM;
 #if ENABLE_DESKTOP
     /* Lie to buildroot when it starts asking stupid questions. */
     if (argv[1] && strcmp(argv[1], "--version") == 0) {
         // Output of 'tar --version' examples:
         // tar (GNU tar) 1.15.1
         // tar (GNU tar) 1.25
         // bsdtar 2.8.3 - libarchive 2.8.3
         puts("tar (busybox) " BB_VER);
         return 0;
     }
 #endif
     if (argv[1] && argv[1][0] != '-' && argv[1][0] != '\0') {
         /* Compat:
          * 1st argument without dash handles options with parameters
          * differently from dashed one: it takes *next argv[i]*
          * as parameter even if there are more chars in 1st argument:
          *  "tar fx TARFILE" - "x" is not taken as f's param
          *  but is interpreted as -x option
          *  "tar -xf TARFILE" - dashed equivalent of the above
          *  "tar -fx ..." - "x" is taken as f's param
          * getopt32 wouldn't handle 1st command correctly.
          * Unfortunately, people do use such commands.
          * We massage argv[1] to work around it by moving 'f'
          * to the end of the string.
          * More contrived "tar fCx TARFILE DIR" still fails,
          * but such commands are much less likely to be used.
          */
         char *f = strchr(argv[1], 'f');
         if (f) {
             while (f[1] != '\0') {
                 *f = f[1];
                 f++;
             }
             *f = 'f';
         }
         /* Prepend '-' to the first argument  */
         argv[1] = xasprintf("-%s", argv[1]);
     }
     opt = GETOPT32(argv, "^"
         "txC:f:Oopvk"
         IF_FEATURE_TAR_CREATE(   "ch"    )
         IF_FEATURE_SEAMLESS_BZ2( "j"     )
         IF_FEATURE_TAR_FROM(     "T:*X:*")
         IF_FEATURE_SEAMLESS_GZ(  "z"     )
         IF_FEATURE_SEAMLESS_XZ(  "J"     )
         IF_FEATURE_SEAMLESS_Z(   "Z"     )
         "a"
         IF_FEATURE_TAR_NOPRESERVE_TIME("m")
         IF_FEATURE_TAR_LONG_OPTIONS("\xf8:") // --strip-components
         "\0"
         "tt:vv:" // count -t,-v
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS && ENABLE_FEATURE_TAR_FROM
         "\xff::" // --exclude=PATTERN is a list
 #endif
         IF_FEATURE_TAR_CREATE("c:") "t:x:" // at least one of these is reqd
         IF_FEATURE_TAR_CREATE("c--tx:t--cx:x--ct") // mutually exclusive
         IF_NOT_FEATURE_TAR_CREATE("t--x:x--t") // mutually exclusive
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS
         ":\xf8+" // --strip-components=NUM
 #endif
         LONGOPTS
         , &base_dir // -C dir
         , &tar_filename // -f filename
         IF_FEATURE_TAR_FROM(, &(tar_handle->accept)) // T
         IF_FEATURE_TAR_FROM(, &(tar_handle->reject)) // X
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS
         , &tar_handle->tar__strip_components // --strip-components
 #endif
         IF_FEATURE_TAR_TO_COMMAND(, &(tar_handle->tar__to_command)) // --to-command
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS && ENABLE_FEATURE_TAR_FROM
         , &excludes // --exclude
 #endif
         , &verboseFlag // combined count for -t and -v
         , &verboseFlag // combined count for -t and -v
         );
 #if DBG_OPTION_PARSING
     bb_error_msg("opt: 0x%08x", opt);
 # define showopt(o) bb_error_msg("opt & %s(%x):\t%x", #o, o, opt & o);
     showopt(OPT_TEST            );
     showopt(OPT_EXTRACT         );
     showopt(OPT_BASEDIR         );
     showopt(OPT_TARNAME         );
     showopt(OPT_2STDOUT         );
     showopt(OPT_NOPRESERVE_OWNER);
     showopt(OPT_P               );
     showopt(OPT_VERBOSE         );
     showopt(OPT_KEEP_OLD        );
     showopt(OPT_CREATE          );
     showopt(OPT_DEREFERENCE     );
     showopt(OPT_BZIP2           );
     showopt(OPT_INCLUDE_FROM    );
     showopt(OPT_EXCLUDE_FROM    );
     showopt(OPT_GZIP            );
     showopt(OPT_XZ              );
     showopt(OPT_COMPRESS        );
     showopt(OPT_AUTOCOMPRESS_BY_EXT);
     showopt(OPT_NOPRESERVE_TIME );
     showopt(OPT_STRIP_COMPONENTS);
     showopt(OPT_LZMA            );
     showopt(OPT_NORECURSION     );
     showopt(OPT_2COMMAND        );
     showopt(OPT_NUMERIC_OWNER   );
     showopt(OPT_NOPRESERVE_PERM );
     showopt(OPT_OVERWRITE       );
     showopt(OPT_ANY_COMPRESS    );
     bb_error_msg("base_dir:'%s'", base_dir);
     bb_error_msg("tar_filename:'%s'", tar_filename);
     bb_error_msg("verboseFlag:%d", verboseFlag);
     bb_error_msg("tar_handle->tar__to_command:'%s'", tar_handle->tar__to_command);
     bb_error_msg("tar_handle->tar__strip_components:%u", tar_handle->tar__strip_components);
     return 0;
 # undef showopt
 #endif
     argv += optind;
     if (verboseFlag)
         tar_handle->action_header = header_verbose_list;
     if (verboseFlag == 1)
         tar_handle->action_header = header_list;
     if (opt & OPT_EXTRACT)
         tar_handle->action_data = data_extract_all;
     if (opt & OPT_2STDOUT)
         tar_handle->action_data = data_extract_to_stdout;
     if (opt & OPT_2COMMAND) {
         putenv((char*)"TAR_FILETYPE=f");
         signal(SIGPIPE, SIG_IGN);
         tar_handle->action_data = data_extract_to_command;
         IF_FEATURE_TAR_TO_COMMAND(tar_handle->tar__to_command_shell = xstrdup(get_shell_name());)
     }
     if (opt & OPT_KEEP_OLD)
         tar_handle->ah_flags &= ~ARCHIVE_UNLINK_OLD;
     if (opt & OPT_NUMERIC_OWNER)
         tar_handle->ah_flags |= ARCHIVE_NUMERIC_OWNER;
     if (opt & OPT_NOPRESERVE_OWNER)
         tar_handle->ah_flags |= ARCHIVE_DONT_RESTORE_OWNER;
     if (opt & OPT_NOPRESERVE_PERM)
         tar_handle->ah_flags |= ARCHIVE_DONT_RESTORE_PERM;
     if (opt & OPT_OVERWRITE) {
         tar_handle->ah_flags &= ~ARCHIVE_UNLINK_OLD;
         tar_handle->ah_flags |= ARCHIVE_O_TRUNC;
     }
     if (opt & OPT_NOPRESERVE_TIME)
         tar_handle->ah_flags &= ~ARCHIVE_RESTORE_DATE;
 #if ENABLE_FEATURE_TAR_FROM
     /* Convert each -X EXCLFILE to list of to-be-rejected glob patterns */
     tar_handle->reject = append_file_list_to_list(tar_handle->reject);
 # if ENABLE_FEATURE_TAR_LONG_OPTIONS
     /* Append --exclude=GLOBPATTERNs to reject */
     if (excludes) {
         llist_t **p2next = &tar_handle->reject;
         while (*p2next)
             p2next = &((*p2next)->link);
         *p2next = excludes;
     }
 # endif
     tar_handle->accept = append_file_list_to_list(tar_handle->accept);
 #endif
     /* Setup an array of filenames to work with */
     /* TODO: This is the same as in ar, make a separate function? */
     while (*argv) {
         /* kill trailing '/' unless the string is just "/" */
         char *cp = last_char_is(*argv, '/');
         if (cp > *argv)
             *cp = '\0';
         llist_add_to_end(&tar_handle->accept, *argv);
         argv++;
     }
     if (tar_handle->accept || tar_handle->reject)
         tar_handle->filter = filter_accept_reject_list;
     /* Open the tar file */
     {
         int tar_fd = STDIN_FILENO;
         int flags = O_RDONLY;
         if (opt & OPT_CREATE) {
             /* Make sure there is at least one file to tar up */
             if (tar_handle->accept == NULL)
                 bb_simple_error_msg_and_die("empty archive");
             tar_fd = STDOUT_FILENO;
             /* Mimicking GNU tar 1.15.1: */
             flags = O_WRONLY | O_CREAT | O_TRUNC;
         }
         if (LONE_DASH(tar_filename)) {
             tar_handle->src_fd = tar_fd;
             tar_handle->seek = seek_by_read;
         } else
         if (ENABLE_FEATURE_TAR_AUTODETECT
          && ENABLE_FEATURE_SEAMLESS_LZMA
          && flags == O_RDONLY
          && !(opt & OPT_ANY_COMPRESS)
          && is_suffixed_with(tar_filename, ".lzma")
         /* We do this only for .lzma files, they have no signature.
          * All other compression formats are recognized in
          * get_header_tar() when first tar block has invalid format.
          * Doing it here for all filenames would falsely trigger
          * on e.g. tarball with 1st file named "BZh5".
          */
         ) {
             tar_handle->src_fd = open_zipped(tar_filename, /*fail_if_not_compressed:*/ 0);
             if (tar_handle->src_fd < 0)
                 bb_perror_msg_and_die("can't open '%s'", tar_filename);
         } else {
             tar_handle->src_fd = xopen(tar_filename, flags);
 #if ENABLE_FEATURE_TAR_CREATE
             if ((OPT_GZIP | OPT_BZIP2 | OPT_XZ | OPT_LZMA) != 0 /* at least one is config-enabled */
              && (opt & OPT_AUTOCOMPRESS_BY_EXT)
              && flags != O_RDONLY
             ) {
                 if (OPT_GZIP != 0 && is_suffixed_with(tar_filename, "gz"))
                     opt |= OPT_GZIP;
                 if (OPT_BZIP2 != 0 && is_suffixed_with(tar_filename, "bz2"))
                     opt |= OPT_BZIP2;
                 if (OPT_XZ != 0 && is_suffixed_with(tar_filename, "xz"))
                     opt |= OPT_XZ;
                 if (OPT_LZMA != 0 && is_suffixed_with(tar_filename, "lzma"))
                     opt |= OPT_LZMA;
             }
 #endif
         }
     }
     if (base_dir)
         xchdir(base_dir);
 #if ENABLE_FEATURE_TAR_CREATE
     /* Create an archive */
     if (opt & OPT_CREATE) {
         struct TarBallInfo *tbInfo;
 # if SEAMLESS_COMPRESSION
         const char *zipMode = NULL;
         if (opt & OPT_COMPRESS)
             zipMode = "compress";
         if (opt & OPT_GZIP)
             zipMode = "gzip";
         if (opt & OPT_BZIP2)
             zipMode = "bzip2";
         if (opt & OPT_LZMA)
             zipMode = "lzma";
         if (opt & OPT_XZ)
             zipMode = "xz";
 # endif
         tbInfo = xzalloc(sizeof(*tbInfo));
         tbInfo->tarFd = tar_handle->src_fd;
         tbInfo->verboseFlag = verboseFlag;
 # if ENABLE_FEATURE_TAR_FROM
         tbInfo->excludeList = tar_handle->reject;
 # endif
         /* NB: writeTarFile() closes tar_handle->src_fd */
         return writeTarFile(tbInfo,
                 (opt & OPT_DEREFERENCE ? ACTION_FOLLOWLINKS : 0)
                 | (opt & OPT_NORECURSION ? 0 : ACTION_RECURSE),
                 tar_handle->accept,
                 zipMode);
     }
 #endif
     if (opt & OPT_ANY_COMPRESS) {
         USE_FOR_MMU(IF_DESKTOP(long long) int FAST_FUNC (*xformer)(transformer_state_t *xstate);)
         USE_FOR_NOMMU(const char *xformer_prog;)
         if (opt & OPT_COMPRESS) {
             USE_FOR_MMU(IF_FEATURE_SEAMLESS_Z(xformer = unpack_Z_stream;))
             USE_FOR_NOMMU(xformer_prog = "uncompress";)
         }
         if (opt & OPT_GZIP) {
             USE_FOR_MMU(IF_FEATURE_SEAMLESS_GZ(xformer = unpack_gz_stream;))
             USE_FOR_NOMMU(xformer_prog = "gunzip";)
         }
         if (opt & OPT_BZIP2) {
             USE_FOR_MMU(IF_FEATURE_SEAMLESS_BZ2(xformer = unpack_bz2_stream;))
             USE_FOR_NOMMU(xformer_prog = "bunzip2";)
         }
         if (opt & OPT_LZMA) {
             USE_FOR_MMU(IF_FEATURE_SEAMLESS_LZMA(xformer = unpack_lzma_stream;))
             USE_FOR_NOMMU(xformer_prog = "unlzma";)
         }
         if (opt & OPT_XZ) {
             USE_FOR_MMU(IF_FEATURE_SEAMLESS_XZ(xformer = unpack_xz_stream;))
             USE_FOR_NOMMU(xformer_prog = "unxz";)
         }
         fork_transformer_with_sig(tar_handle->src_fd, xformer, xformer_prog);
         /* Can't lseek over pipes */
         tar_handle->seek = seek_by_read;
         /*tar_handle->offset = 0; - already is */
     }
     /* Zero processed headers (== empty file) is not a valid tarball.
      * We (ab)use bb_got_signal as exitcode here,
      * because check_errors_in_children() uses _it_ as error indicator.
      */
     bb_got_signal = EXIT_FAILURE;
     while (get_header_tar(tar_handle) == EXIT_SUCCESS)
         bb_got_signal = EXIT_SUCCESS; /* saw at least one header, good */
     create_links_from_list(tar_handle->link_placeholders);
     /* Check that every file that should have been extracted was */
     while (tar_handle->accept) {
         if (!find_list_entry(tar_handle->reject, tar_handle->accept->data)
          && !find_list_entry(tar_handle->passed, tar_handle->accept->data)
         ) {
             bb_error_msg_and_die("%s: not found in archive",
                 tar_handle->accept->data);
         }
         tar_handle->accept = tar_handle->accept->link;
     }
     if (ENABLE_FEATURE_CLEAN_UP /* && tar_handle->src_fd != STDIN_FILENO */)
         close(tar_handle->src_fd);
     if (SEAMLESS_COMPRESSION || OPT_COMPRESS) {
         /* Set bb_got_signal to 1 if a child died with !0 exitcode */
         check_errors_in_children(0);
     }
     return bb_got_signal;
 }
References archive_handle_t::accept, archive_handle_t::action_data, ACTION_FOLLOWLINKS, archive_handle_t::action_header, ACTION_RECURSE, archive_handle_t::ah_flags, ARCHIVE_CREATE_LEADING_DIRS, ARCHIVE_DONT_RESTORE_OWNER, ARCHIVE_DONT_RESTORE_PERM, ARCHIVE_NUMERIC_OWNER, ARCHIVE_O_TRUNC, ARCHIVE_RESTORE_DATE, ARCHIVE_UNLINK_OLD, argv, bb_error_msg(), bb_error_msg_and_die(), bb_got_signal, bb_perror_msg_and_die(), bb_simple_error_msg_and_die(), check_errors_in_children(), close(), create_links_from_list(), llist_t::data, data_extract_all(), data_extract_to_command(), data_extract_to_stdout(), EXIT_FAILURE, EXIT_SUCCESS, f, FAST_FUNC, archive_handle_t::filter, filter_accept_reject_list(), find_list_entry(), flags, fork_transformer_with_sig, get_header_tar(), get_shell_name(), GETOPT32, getuid, header_list(), header_verbose_list(), IF_DESKTOP(), IF_FEATURE_SEAMLESS_Z, INIT_G, init_handle(), is_suffixed_with(), last_char_is(), llist_t::link, archive_handle_t::link_placeholders, llist_add_to_end(), LONE_DASH, LONGOPTS, NULL, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open_zipped, opt, OPT_2COMMAND, OPT_2STDOUT, OPT_ANY_COMPRESS, OPT_AUTOCOMPRESS_BY_EXT, OPT_BASEDIR, OPT_BZIP2, OPT_COMPRESS, OPT_CREATE, OPT_DEREFERENCE, OPT_EXCLUDE_FROM, OPT_EXTRACT, OPT_GZIP, OPT_INCLUDE_FROM, OPT_KEEP_OLD, OPT_LZMA, OPT_NOPRESERVE_OWNER, OPT_NOPRESERVE_PERM, OPT_NOPRESERVE_TIME, OPT_NORECURSION, OPT_NUMERIC_OWNER, OPT_OVERWRITE, OPT_P, OPT_STRIP_COMPONENTS, OPT_TARNAME, OPT_TEST, OPT_VERBOSE, OPT_XZ, optind, archive_handle_t::passed, putenv(), puts(), archive_handle_t::reject, SEAMLESS_COMPRESSION, archive_handle_t::seek, seek_by_read(), SIG_IGN, signal, SIGPIPE, archive_handle_t::src_fd, STDIN_FILENO, STDOUT_FILENO, strchr(), strcmp, USE_FOR_MMU, USE_FOR_NOMMU, xasprintf(), xchdir(), xopen(), xstrdup(), and xzalloc().