Fennix: Userspace/musl/include/sys/socket.h File Reference
socket.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/socket.h>
Data Structures
struct msghdr
struct cmsghdr
struct linger
struct sockaddr
struct sockaddr_storage
Macros
#define __NEED_socklen_t
#define __NEED_sa_family_t
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_uid_t
#define __NEED_pid_t
#define __NEED_gid_t
#define __NEED_struct_iovec
#define SHUT_RD 0
#define SHUT_WR 1
#define SHUT_RDWR 2
#define SOCK_STREAM 1
#define SOCK_DGRAM 2
#define SOCK_RAW 3
#define SOCK_RDM 4
#define SOCK_SEQPACKET 5
#define SOCK_DCCP 6
#define SOCK_PACKET 10
#define SOCK_CLOEXEC 02000000
#define SOCK_NONBLOCK 04000
#define PF_UNSPEC 0
#define PF_LOCAL 1
#define PF_UNIX PF_LOCAL
#define PF_FILE PF_LOCAL
#define PF_INET 2
#define PF_AX25 3
#define PF_IPX 4
#define PF_APPLETALK 5
#define PF_NETROM 6
#define PF_BRIDGE 7
#define PF_ATMPVC 8
#define PF_X25 9
#define PF_INET6 10
#define PF_ROSE 11
#define PF_DECnet 12
#define PF_NETBEUI 13
#define PF_SECURITY 14
#define PF_KEY 15
#define PF_NETLINK 16
#define PF_ROUTE PF_NETLINK
#define PF_PACKET 17
#define PF_ASH 18
#define PF_ECONET 19
#define PF_ATMSVC 20
#define PF_RDS 21
#define PF_SNA 22
#define PF_IRDA 23
#define PF_PPPOX 24
#define PF_WANPIPE 25
#define PF_LLC 26
#define PF_IB 27
#define PF_MPLS 28
#define PF_CAN 29
#define PF_TIPC 30
#define PF_BLUETOOTH 31
#define PF_IUCV 32
#define PF_RXRPC 33
#define PF_ISDN 34
#define PF_PHONET 35
#define PF_IEEE802154 36
#define PF_CAIF 37
#define PF_ALG 38
#define PF_NFC 39
#define PF_VSOCK 40
#define PF_KCM 41
#define PF_QIPCRTR 42
#define PF_SMC 43
#define PF_XDP 44
#define PF_MAX 45
#define AF_UNSPEC PF_UNSPEC
#define AF_LOCAL PF_LOCAL
#define AF_UNIX AF_LOCAL
#define AF_FILE AF_LOCAL
#define AF_INET PF_INET
#define AF_AX25 PF_AX25
#define AF_IPX PF_IPX
#define AF_APPLETALK PF_APPLETALK
#define AF_NETROM PF_NETROM
#define AF_BRIDGE PF_BRIDGE
#define AF_ATMPVC PF_ATMPVC
#define AF_X25 PF_X25
#define AF_INET6 PF_INET6
#define AF_ROSE PF_ROSE
#define AF_DECnet PF_DECnet
#define AF_NETBEUI PF_NETBEUI
#define AF_SECURITY PF_SECURITY
#define AF_KEY PF_KEY
#define AF_NETLINK PF_NETLINK
#define AF_ROUTE PF_ROUTE
#define AF_PACKET PF_PACKET
#define AF_ASH PF_ASH
#define AF_ECONET PF_ECONET
#define AF_ATMSVC PF_ATMSVC
#define AF_RDS PF_RDS
#define AF_SNA PF_SNA
#define AF_IRDA PF_IRDA
#define AF_PPPOX PF_PPPOX
#define AF_WANPIPE PF_WANPIPE
#define AF_LLC PF_LLC
#define AF_IB PF_IB
#define AF_MPLS PF_MPLS
#define AF_CAN PF_CAN
#define AF_TIPC PF_TIPC
#define AF_BLUETOOTH PF_BLUETOOTH
#define AF_IUCV PF_IUCV
#define AF_RXRPC PF_RXRPC
#define AF_ISDN PF_ISDN
#define AF_PHONET PF_PHONET
#define AF_IEEE802154 PF_IEEE802154
#define AF_CAIF PF_CAIF
#define AF_ALG PF_ALG
#define AF_NFC PF_NFC
#define AF_VSOCK PF_VSOCK
#define AF_KCM PF_KCM
#define AF_QIPCRTR PF_QIPCRTR
#define AF_SMC PF_SMC
#define AF_XDP PF_XDP
#define AF_MAX PF_MAX
#define SO_DEBUG 1
#define SO_REUSEADDR 2
#define SO_TYPE 3
#define SO_ERROR 4
#define SO_DONTROUTE 5
#define SO_BROADCAST 6
#define SO_SNDBUF 7
#define SO_RCVBUF 8
#define SO_KEEPALIVE 9
#define SO_OOBINLINE 10
#define SO_NO_CHECK 11
#define SO_PRIORITY 12
#define SO_LINGER 13
#define SO_BSDCOMPAT 14
#define SO_REUSEPORT 15
#define SO_PASSCRED 16
#define SO_PEERCRED 17
#define SO_RCVLOWAT 18
#define SO_SNDLOWAT 19
#define SO_ACCEPTCONN 30
#define SO_PEERSEC 31
#define SO_SNDBUFFORCE 32
#define SO_RCVBUFFORCE 33
#define SO_PROTOCOL 38
#define SO_DOMAIN 39
#define SO_RCVTIMEO 20
#define SO_SNDTIMEO 21
#define SO_TIMESTAMP 29
#define SO_TIMESTAMPNS 35
#define SO_TIMESTAMPING 37
#define SO_SECURITY_AUTHENTICATION 22
#define SO_SECURITY_ENCRYPTION_TRANSPORT 23
#define SO_SECURITY_ENCRYPTION_NETWORK 24
#define SO_BINDTODEVICE 25
#define SO_ATTACH_FILTER 26
#define SO_DETACH_FILTER 27
#define SO_GET_FILTER SO_ATTACH_FILTER
#define SO_PEERNAME 28
#define SCM_TIMESTAMP SO_TIMESTAMP
#define SO_PASSSEC 34
#define SCM_TIMESTAMPNS SO_TIMESTAMPNS
#define SO_MARK 36
#define SCM_TIMESTAMPING SO_TIMESTAMPING
#define SO_RXQ_OVFL 40
#define SO_WIFI_STATUS 41
#define SCM_WIFI_STATUS SO_WIFI_STATUS
#define SO_PEEK_OFF 42
#define SO_NOFCS 43
#define SO_LOCK_FILTER 44
#define SO_SELECT_ERR_QUEUE 45
#define SO_BUSY_POLL 46
#define SO_MAX_PACING_RATE 47
#define SO_BPF_EXTENSIONS 48
#define SO_INCOMING_CPU 49
#define SO_ATTACH_BPF 50
#define SO_DETACH_BPF SO_DETACH_FILTER
#define SO_ATTACH_REUSEPORT_CBPF 51
#define SO_ATTACH_REUSEPORT_EBPF 52
#define SO_CNX_ADVICE 53
#define SCM_TIMESTAMPING_OPT_STATS 54
#define SO_MEMINFO 55
#define SO_INCOMING_NAPI_ID 56
#define SO_COOKIE 57
#define SCM_TIMESTAMPING_PKTINFO 58
#define SO_PEERGROUPS 59
#define SO_ZEROCOPY 60
#define SO_TXTIME 61
#define SCM_TXTIME SO_TXTIME
#define SO_BINDTOIFINDEX 62
#define SO_DETACH_REUSEPORT_BPF 68
#define SO_PREFER_BUSY_POLL 69
#define SO_BUSY_POLL_BUDGET 70
#define SOL_SOCKET 1
#define SOL_IP 0
#define SOL_IPV6 41
#define SOL_ICMPV6 58
#define SOL_RAW 255
#define SOL_DECNET 261
#define SOL_X25 262
#define SOL_PACKET 263
#define SOL_ATM 264
#define SOL_AAL 265
#define SOL_IRDA 266
#define SOL_NETBEUI 267
#define SOL_LLC 268
#define SOL_DCCP 269
#define SOL_NETLINK 270
#define SOL_TIPC 271
#define SOL_RXRPC 272
#define SOL_PPPOL2TP 273
#define SOL_BLUETOOTH 274
#define SOL_PNPIPE 275
#define SOL_RDS 276
#define SOL_IUCV 277
#define SOL_CAIF 278
#define SOL_ALG 279
#define SOL_NFC 280
#define SOL_KCM 281
#define SOL_TLS 282
#define SOL_XDP 283
#define SOMAXCONN 128
#define MSG_OOB 0x0001
#define MSG_PEEK 0x0002
#define MSG_DONTROUTE 0x0004
#define MSG_CTRUNC 0x0008
#define MSG_PROXY 0x0010
#define MSG_TRUNC 0x0020
#define MSG_DONTWAIT 0x0040
#define MSG_EOR 0x0080
#define MSG_WAITALL 0x0100
#define MSG_FIN 0x0200
#define MSG_SYN 0x0400
#define MSG_CONFIRM 0x0800
#define MSG_RST 0x1000
#define MSG_ERRQUEUE 0x2000
#define MSG_NOSIGNAL 0x4000
#define MSG_MORE 0x8000
#define MSG_WAITFORONE 0x10000
#define MSG_BATCH 0x40000
#define MSG_ZEROCOPY 0x4000000
#define MSG_FASTOPEN 0x20000000
#define MSG_CMSG_CLOEXEC 0x40000000
#define __CMSG_LEN(cmsg) (((cmsg)->cmsg_len + sizeof(long) - 1) & ~(long)(sizeof(long) - 1))
#define __CMSG_NEXT(cmsg) ((unsigned char *)(cmsg) + __CMSG_LEN(cmsg))
#define __MHDR_END(mhdr) ((unsigned char *)(mhdr)->msg_control + (mhdr)->msg_controllen)
#define CMSG_DATA(cmsg) ((unsigned char *) (((struct cmsghdr *)(cmsg)) + 1))
#define CMSG_NXTHDR(mhdr, cmsg)
#define CMSG_FIRSTHDR(mhdr) ((size_t) (mhdr)->msg_controllen >= sizeof (struct cmsghdr) ? (struct cmsghdr *) (mhdr)->msg_control : (struct cmsghdr *) 0)
#define CMSG_ALIGN(len) (((len) + sizeof (size_t) - 1) & (size_t) ~(sizeof (size_t) - 1))
#define CMSG_SPACE(len) (CMSG_ALIGN (len) + CMSG_ALIGN (sizeof (struct cmsghdr)))
#define CMSG_LEN(len) (CMSG_ALIGN (sizeof (struct cmsghdr)) + (len))
#define SCM_RIGHTS 0x01
#define SCM_CREDENTIALS 0x02
Functions
int socket (int, int, int)
int socketpair (int, int, int, int[2])
int shutdown (int, int)
int bind (int, const struct sockaddr *, socklen_t)
int connect (int, const struct sockaddr *, socklen_t)
int listen (int, int)
int accept (int, struct sockaddr *__restrict, socklen_t *__restrict)
int accept4 (int, struct sockaddr *__restrict, socklen_t *__restrict, int)
int getsockname (int, struct sockaddr *__restrict, socklen_t *__restrict)
int getpeername (int, struct sockaddr *__restrict, socklen_t *__restrict)
ssize_t send (int, const void *, size_t, int)
ssize_t recv (int, void *, size_t, int)
ssize_t sendto (int, const void *, size_t, int, const struct sockaddr *, socklen_t)
ssize_t recvfrom (int, void *__restrict, size_t, int, struct sockaddr *__restrict, socklen_t *__restrict)
ssize_t sendmsg (int, const struct msghdr *, int)
ssize_t recvmsg (int, struct msghdr *, int)
int getsockopt (int, int, int, void *__restrict, socklen_t *__restrict)
int setsockopt (int, int, int, const void *, socklen_t)
int sockatmark (int)
Data Structure Documentation
msghdr
struct msghdr
Definition at line 22 of file socket.h.
Data Fields
void * msg_control
socklen_t msg_controllen
int msg_flags
struct iovec * msg_iov
int msg_iovlen
void * msg_name
socklen_t msg_namelen
cmsghdr
struct cmsghdr
Definition at line 44 of file socket.h.
Data Fields
socklen_t cmsg_len
int cmsg_level
int cmsg_type
linger
struct linger
Definition at line 74 of file socket.h.
Data Fields
int l_linger
int l_onoff
sockaddr
struct sockaddr
Definition at line 369 of file socket.h.
Data Fields
char sa_data[14]
sa_family_t sa_family
sockaddr_storage
struct sockaddr_storage
Definition at line 374 of file socket.h.
Data Fields
unsigned long __ss_align
char __ss_padding[128-sizeof(long) -sizeof(sa_family_t)]
sa_family_t ss_family
Macro Definition Documentation
__CMSG_LEN
#define __CMSG_LEN (cmsg) (((cmsg)->cmsg_len + sizeof(long) - 1) & ~(long)(sizeof(long) - 1))
Definition at line 352 of file socket.h.
__CMSG_NEXT
#define __CMSG_NEXT (cmsg) ((unsigned char *)(cmsg) + __CMSG_LEN(cmsg))
Definition at line 353 of file socket.h.
__MHDR_END
#define __MHDR_END (mhdr) ((unsigned char *)(mhdr)->msg_control + (mhdr)->msg_controllen)
Definition at line 354 of file socket.h.
__NEED_gid_t
#define __NEED_gid_t
Definition at line 15 of file socket.h.
__NEED_pid_t
#define __NEED_pid_t
Definition at line 14 of file socket.h.
__NEED_sa_family_t
#define __NEED_sa_family_t
Definition at line 10 of file socket.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 11 of file socket.h.
__NEED_socklen_t
#define __NEED_socklen_t
Definition at line 9 of file socket.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 12 of file socket.h.
__NEED_struct_iovec
#define __NEED_struct_iovec
Definition at line 16 of file socket.h.
__NEED_uid_t
#define __NEED_uid_t
Definition at line 13 of file socket.h.
AF_ALG
#define AF_ALG PF_ALG
Definition at line 190 of file socket.h.
AF_APPLETALK
#define AF_APPLETALK PF_APPLETALK
Definition at line 156 of file socket.h.
AF_ASH
#define AF_ASH PF_ASH
Definition at line 170 of file socket.h.
AF_ATMPVC
#define AF_ATMPVC PF_ATMPVC
Definition at line 159 of file socket.h.
AF_ATMSVC
#define AF_ATMSVC PF_ATMSVC
Definition at line 172 of file socket.h.
AF_AX25
#define AF_AX25 PF_AX25
Definition at line 154 of file socket.h.
AF_BLUETOOTH
#define AF_BLUETOOTH PF_BLUETOOTH
Definition at line 183 of file socket.h.
AF_BRIDGE
#define AF_BRIDGE PF_BRIDGE
Definition at line 158 of file socket.h.
AF_CAIF
#define AF_CAIF PF_CAIF
Definition at line 189 of file socket.h.
AF_CAN
#define AF_CAN PF_CAN
Definition at line 181 of file socket.h.
AF_DECnet
#define AF_DECnet PF_DECnet
Definition at line 163 of file socket.h.
AF_ECONET
#define AF_ECONET PF_ECONET
Definition at line 171 of file socket.h.
AF_FILE
#define AF_FILE AF_LOCAL
Definition at line 152 of file socket.h.
AF_IB
#define AF_IB PF_IB
Definition at line 179 of file socket.h.
AF_IEEE802154
#define AF_IEEE802154 PF_IEEE802154
Definition at line 188 of file socket.h.
AF_INET
#define AF_INET PF_INET
Definition at line 153 of file socket.h.
AF_INET6
#define AF_INET6 PF_INET6
Definition at line 161 of file socket.h.
AF_IPX
#define AF_IPX PF_IPX
Definition at line 155 of file socket.h.
AF_IRDA
#define AF_IRDA PF_IRDA
Definition at line 175 of file socket.h.
AF_ISDN
#define AF_ISDN PF_ISDN
Definition at line 186 of file socket.h.
AF_IUCV
#define AF_IUCV PF_IUCV
Definition at line 184 of file socket.h.
AF_KCM
#define AF_KCM PF_KCM
Definition at line 193 of file socket.h.
AF_KEY
#define AF_KEY PF_KEY
Definition at line 166 of file socket.h.
AF_LLC
#define AF_LLC PF_LLC
Definition at line 178 of file socket.h.
AF_LOCAL
#define AF_LOCAL PF_LOCAL
Definition at line 150 of file socket.h.
AF_MAX
#define AF_MAX PF_MAX
Definition at line 197 of file socket.h.
AF_MPLS
#define AF_MPLS PF_MPLS
Definition at line 180 of file socket.h.
AF_NETBEUI
#define AF_NETBEUI PF_NETBEUI
Definition at line 164 of file socket.h.
AF_NETLINK
#define AF_NETLINK PF_NETLINK
Definition at line 167 of file socket.h.
AF_NETROM
#define AF_NETROM PF_NETROM
Definition at line 157 of file socket.h.
AF_NFC
#define AF_NFC PF_NFC
Definition at line 191 of file socket.h.
AF_PACKET
#define AF_PACKET PF_PACKET
Definition at line 169 of file socket.h.
AF_PHONET
#define AF_PHONET PF_PHONET
Definition at line 187 of file socket.h.
AF_PPPOX
#define AF_PPPOX PF_PPPOX
Definition at line 176 of file socket.h.
AF_QIPCRTR
#define AF_QIPCRTR PF_QIPCRTR
Definition at line 194 of file socket.h.
AF_RDS
#define AF_RDS PF_RDS
Definition at line 173 of file socket.h.
AF_ROSE
#define AF_ROSE PF_ROSE
Definition at line 162 of file socket.h.
AF_ROUTE
#define AF_ROUTE PF_ROUTE
Definition at line 168 of file socket.h.
AF_RXRPC
#define AF_RXRPC PF_RXRPC
Definition at line 185 of file socket.h.
AF_SECURITY
#define AF_SECURITY PF_SECURITY
Definition at line 165 of file socket.h.
AF_SMC
#define AF_SMC PF_SMC
Definition at line 195 of file socket.h.
AF_SNA
#define AF_SNA PF_SNA
Definition at line 174 of file socket.h.
AF_TIPC
#define AF_TIPC PF_TIPC
Definition at line 182 of file socket.h.
AF_UNIX
#define AF_UNIX AF_LOCAL
Definition at line 151 of file socket.h.
AF_UNSPEC
#define AF_UNSPEC PF_UNSPEC
Definition at line 149 of file socket.h.
AF_VSOCK
#define AF_VSOCK PF_VSOCK
Definition at line 192 of file socket.h.
AF_WANPIPE
#define AF_WANPIPE PF_WANPIPE
Definition at line 177 of file socket.h.
AF_X25
#define AF_X25 PF_X25
Definition at line 160 of file socket.h.
AF_XDP
#define AF_XDP PF_XDP
Definition at line 196 of file socket.h.
CMSG_ALIGN
#define CMSG_ALIGN (len) (((len) + sizeof (size_t) - 1) & (size_t) ~(sizeof (size_t) - 1))
Definition at line 362 of file socket.h.
CMSG_DATA
#define CMSG_DATA (cmsg) ((unsigned char *) (((struct cmsghdr *)(cmsg)) + 1))
Definition at line 356 of file socket.h.
CMSG_FIRSTHDR
#define CMSG_FIRSTHDR (mhdr) ((size_t) (mhdr)->msg_controllen >= sizeof (struct cmsghdr) ? (struct cmsghdr *) (mhdr)->msg_control : (struct cmsghdr *) 0)
Definition at line 360 of file socket.h.
CMSG_LEN
#define CMSG_LEN (len) (CMSG_ALIGN (sizeof (struct cmsghdr)) + (len))
Definition at line 364 of file socket.h.
CMSG_NXTHDR
#define CMSG_NXTHDR (mhdr, cmsg)
Value:
    ((cmsg)->cmsg_len < sizeof (struct cmsghdr) || \
    __CMSG_LEN(cmsg) + sizeof(struct cmsghdr) >= __MHDR_END(mhdr) - (unsigned char *)(cmsg) \
    ? 0 : (struct cmsghdr *)__CMSG_NEXT(cmsg))
Definition at line 357 of file socket.h.
CMSG_SPACE
#define CMSG_SPACE (len) (CMSG_ALIGN (len) + CMSG_ALIGN (sizeof (struct cmsghdr)))
Definition at line 363 of file socket.h.
MSG_BATCH
#define MSG_BATCH 0x40000
Definition at line 347 of file socket.h.
MSG_CMSG_CLOEXEC
#define MSG_CMSG_CLOEXEC 0x40000000
Definition at line 350 of file socket.h.
MSG_CONFIRM
#define MSG_CONFIRM 0x0800
Definition at line 341 of file socket.h.
MSG_CTRUNC
#define MSG_CTRUNC 0x0008
Definition at line 333 of file socket.h.
MSG_DONTROUTE
#define MSG_DONTROUTE 0x0004
Definition at line 332 of file socket.h.
MSG_DONTWAIT
#define MSG_DONTWAIT 0x0040
Definition at line 336 of file socket.h.
MSG_EOR
#define MSG_EOR 0x0080
Definition at line 337 of file socket.h.
MSG_ERRQUEUE
#define MSG_ERRQUEUE 0x2000
Definition at line 343 of file socket.h.
MSG_FASTOPEN
#define MSG_FASTOPEN 0x20000000
Definition at line 349 of file socket.h.
MSG_FIN
#define MSG_FIN 0x0200
Definition at line 339 of file socket.h.
MSG_MORE
#define MSG_MORE 0x8000
Definition at line 345 of file socket.h.
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0x4000
Definition at line 344 of file socket.h.
MSG_OOB
#define MSG_OOB 0x0001
Definition at line 330 of file socket.h.
MSG_PEEK
#define MSG_PEEK 0x0002
Definition at line 331 of file socket.h.
MSG_PROXY
#define MSG_PROXY 0x0010
Definition at line 334 of file socket.h.
MSG_RST
#define MSG_RST 0x1000
Definition at line 342 of file socket.h.
MSG_SYN
#define MSG_SYN 0x0400
Definition at line 340 of file socket.h.
MSG_TRUNC
#define MSG_TRUNC 0x0020
Definition at line 335 of file socket.h.
MSG_WAITALL
#define MSG_WAITALL 0x0100
Definition at line 338 of file socket.h.
MSG_WAITFORONE
#define MSG_WAITFORONE 0x10000
Definition at line 346 of file socket.h.
MSG_ZEROCOPY
#define MSG_ZEROCOPY 0x4000000
Definition at line 348 of file socket.h.
PF_ALG
#define PF_ALG 38
Definition at line 140 of file socket.h.
PF_APPLETALK
#define PF_APPLETALK 5
Definition at line 106 of file socket.h.
PF_ASH
#define PF_ASH 18
Definition at line 120 of file socket.h.
PF_ATMPVC
#define PF_ATMPVC 8
Definition at line 109 of file socket.h.
PF_ATMSVC
#define PF_ATMSVC 20
Definition at line 122 of file socket.h.
PF_AX25
#define PF_AX25 3
Definition at line 104 of file socket.h.
PF_BLUETOOTH
#define PF_BLUETOOTH 31
Definition at line 133 of file socket.h.
PF_BRIDGE
#define PF_BRIDGE 7
Definition at line 108 of file socket.h.
PF_CAIF
#define PF_CAIF 37
Definition at line 139 of file socket.h.
PF_CAN
#define PF_CAN 29
Definition at line 131 of file socket.h.
PF_DECnet
#define PF_DECnet 12
Definition at line 113 of file socket.h.
PF_ECONET
#define PF_ECONET 19
Definition at line 121 of file socket.h.
PF_FILE
#define PF_FILE PF_LOCAL
Definition at line 102 of file socket.h.
PF_IB
#define PF_IB 27
Definition at line 129 of file socket.h.
PF_IEEE802154
#define PF_IEEE802154 36
Definition at line 138 of file socket.h.
PF_INET
#define PF_INET 2
Definition at line 103 of file socket.h.
PF_INET6
#define PF_INET6 10
Definition at line 111 of file socket.h.
PF_IPX
#define PF_IPX 4
Definition at line 105 of file socket.h.
PF_IRDA
#define PF_IRDA 23
Definition at line 125 of file socket.h.
PF_ISDN
#define PF_ISDN 34
Definition at line 136 of file socket.h.
PF_IUCV
#define PF_IUCV 32
Definition at line 134 of file socket.h.
PF_KCM
#define PF_KCM 41
Definition at line 143 of file socket.h.
PF_KEY
#define PF_KEY 15
Definition at line 116 of file socket.h.
PF_LLC
#define PF_LLC 26
Definition at line 128 of file socket.h.
PF_LOCAL
#define PF_LOCAL 1
Definition at line 100 of file socket.h.
PF_MAX
#define PF_MAX 45
Definition at line 147 of file socket.h.
PF_MPLS
#define PF_MPLS 28
Definition at line 130 of file socket.h.
PF_NETBEUI
#define PF_NETBEUI 13
Definition at line 114 of file socket.h.
PF_NETLINK
#define PF_NETLINK 16
Definition at line 117 of file socket.h.
PF_NETROM
#define PF_NETROM 6
Definition at line 107 of file socket.h.
PF_NFC
#define PF_NFC 39
Definition at line 141 of file socket.h.
PF_PACKET
#define PF_PACKET 17
Definition at line 119 of file socket.h.
PF_PHONET
#define PF_PHONET 35
Definition at line 137 of file socket.h.
PF_PPPOX
#define PF_PPPOX 24
Definition at line 126 of file socket.h.
PF_QIPCRTR
#define PF_QIPCRTR 42
Definition at line 144 of file socket.h.
PF_RDS
#define PF_RDS 21
Definition at line 123 of file socket.h.
PF_ROSE
#define PF_ROSE 11
Definition at line 112 of file socket.h.
PF_ROUTE
#define PF_ROUTE PF_NETLINK
Definition at line 118 of file socket.h.
PF_RXRPC
#define PF_RXRPC 33
Definition at line 135 of file socket.h.
PF_SECURITY
#define PF_SECURITY 14
Definition at line 115 of file socket.h.
PF_SMC
#define PF_SMC 43
Definition at line 145 of file socket.h.
PF_SNA
#define PF_SNA 22
Definition at line 124 of file socket.h.
PF_TIPC
#define PF_TIPC 30
Definition at line 132 of file socket.h.
PF_UNIX
#define PF_UNIX PF_LOCAL
Definition at line 101 of file socket.h.
PF_UNSPEC
#define PF_UNSPEC 0
Definition at line 99 of file socket.h.
PF_VSOCK
#define PF_VSOCK 40
Definition at line 142 of file socket.h.
PF_WANPIPE
#define PF_WANPIPE 25
Definition at line 127 of file socket.h.
PF_X25
#define PF_X25 9
Definition at line 110 of file socket.h.
PF_XDP
#define PF_XDP 44
Definition at line 146 of file socket.h.
SCM_CREDENTIALS
#define SCM_CREDENTIALS 0x02
Definition at line 367 of file socket.h.
SCM_RIGHTS
#define SCM_RIGHTS 0x01
Definition at line 366 of file socket.h.
SCM_TIMESTAMP
#define SCM_TIMESTAMP SO_TIMESTAMP
Definition at line 260 of file socket.h.
SCM_TIMESTAMPING
#define SCM_TIMESTAMPING SO_TIMESTAMPING
Definition at line 264 of file socket.h.
SCM_TIMESTAMPING_OPT_STATS
#define SCM_TIMESTAMPING_OPT_STATS 54
Definition at line 281 of file socket.h.
SCM_TIMESTAMPING_PKTINFO
#define SCM_TIMESTAMPING_PKTINFO 58
Definition at line 285 of file socket.h.
SCM_TIMESTAMPNS
#define SCM_TIMESTAMPNS SO_TIMESTAMPNS
Definition at line 262 of file socket.h.
SCM_TXTIME
#define SCM_TXTIME SO_TXTIME
Definition at line 289 of file socket.h.
SCM_WIFI_STATUS
#define SCM_WIFI_STATUS SO_WIFI_STATUS
Definition at line 267 of file socket.h.
SHUT_RD
#define SHUT_RD 0
Definition at line 79 of file socket.h.
SHUT_RDWR
#define SHUT_RDWR 2
Definition at line 81 of file socket.h.
SHUT_WR
#define SHUT_WR 1
Definition at line 80 of file socket.h.
SO_ACCEPTCONN
#define SO_ACCEPTCONN 30
Definition at line 219 of file socket.h.
SO_ATTACH_BPF
#define SO_ATTACH_BPF 50
Definition at line 276 of file socket.h.
SO_ATTACH_FILTER
#define SO_ATTACH_FILTER 26
Definition at line 255 of file socket.h.
SO_ATTACH_REUSEPORT_CBPF
#define SO_ATTACH_REUSEPORT_CBPF 51
Definition at line 278 of file socket.h.
SO_ATTACH_REUSEPORT_EBPF
#define SO_ATTACH_REUSEPORT_EBPF 52
Definition at line 279 of file socket.h.
SO_BINDTODEVICE
#define SO_BINDTODEVICE 25
Definition at line 253 of file socket.h.
SO_BINDTOIFINDEX
#define SO_BINDTOIFINDEX 62
Definition at line 290 of file socket.h.
SO_BPF_EXTENSIONS
#define SO_BPF_EXTENSIONS 48
Definition at line 274 of file socket.h.
SO_BROADCAST
#define SO_BROADCAST 6
Definition at line 205 of file socket.h.
SO_BSDCOMPAT
#define SO_BSDCOMPAT 14
Definition at line 213 of file socket.h.
SO_BUSY_POLL
#define SO_BUSY_POLL 46
Definition at line 272 of file socket.h.
SO_BUSY_POLL_BUDGET
#define SO_BUSY_POLL_BUDGET 70
Definition at line 293 of file socket.h.
SO_CNX_ADVICE
#define SO_CNX_ADVICE 53
Definition at line 280 of file socket.h.
SO_COOKIE
#define SO_COOKIE 57
Definition at line 284 of file socket.h.
SO_DEBUG
#define SO_DEBUG 1
Definition at line 200 of file socket.h.
SO_DETACH_BPF
#define SO_DETACH_BPF SO_DETACH_FILTER
Definition at line 277 of file socket.h.
SO_DETACH_FILTER
#define SO_DETACH_FILTER 27
Definition at line 256 of file socket.h.
SO_DETACH_REUSEPORT_BPF
#define SO_DETACH_REUSEPORT_BPF 68
Definition at line 291 of file socket.h.
SO_DOMAIN
#define SO_DOMAIN 39
Definition at line 224 of file socket.h.
SO_DONTROUTE
#define SO_DONTROUTE 5
Definition at line 204 of file socket.h.
SO_ERROR
#define SO_ERROR 4
Definition at line 203 of file socket.h.
SO_GET_FILTER
#define SO_GET_FILTER SO_ATTACH_FILTER
Definition at line 257 of file socket.h.
SO_INCOMING_CPU
#define SO_INCOMING_CPU 49
Definition at line 275 of file socket.h.
SO_INCOMING_NAPI_ID
#define SO_INCOMING_NAPI_ID 56
Definition at line 283 of file socket.h.
SO_KEEPALIVE
#define SO_KEEPALIVE 9
Definition at line 208 of file socket.h.
SO_LINGER
#define SO_LINGER 13
Definition at line 212 of file socket.h.
SO_LOCK_FILTER
#define SO_LOCK_FILTER 44
Definition at line 270 of file socket.h.
SO_MARK
#define SO_MARK 36
Definition at line 263 of file socket.h.
SO_MAX_PACING_RATE
#define SO_MAX_PACING_RATE 47
Definition at line 273 of file socket.h.
SO_MEMINFO
#define SO_MEMINFO 55
Definition at line 282 of file socket.h.
SO_NO_CHECK
#define SO_NO_CHECK 11
Definition at line 210 of file socket.h.
SO_NOFCS
#define SO_NOFCS 43
Definition at line 269 of file socket.h.
SO_OOBINLINE
#define SO_OOBINLINE 10
Definition at line 209 of file socket.h.
SO_PASSCRED
#define SO_PASSCRED 16
Definition at line 215 of file socket.h.
SO_PASSSEC
#define SO_PASSSEC 34
Definition at line 261 of file socket.h.
SO_PEEK_OFF
#define SO_PEEK_OFF 42
Definition at line 268 of file socket.h.
SO_PEERCRED
#define SO_PEERCRED 17
Definition at line 216 of file socket.h.
SO_PEERGROUPS
#define SO_PEERGROUPS 59
Definition at line 286 of file socket.h.
SO_PEERNAME
#define SO_PEERNAME 28
Definition at line 259 of file socket.h.
SO_PEERSEC
#define SO_PEERSEC 31
Definition at line 220 of file socket.h.
SO_PREFER_BUSY_POLL
#define SO_PREFER_BUSY_POLL 69
Definition at line 292 of file socket.h.
SO_PRIORITY
#define SO_PRIORITY 12
Definition at line 211 of file socket.h.
SO_PROTOCOL
#define SO_PROTOCOL 38
Definition at line 223 of file socket.h.
SO_RCVBUF
#define SO_RCVBUF 8
Definition at line 207 of file socket.h.
SO_RCVBUFFORCE
#define SO_RCVBUFFORCE 33
Definition at line 222 of file socket.h.
SO_RCVLOWAT
#define SO_RCVLOWAT 18
Definition at line 217 of file socket.h.
SO_RCVTIMEO
#define SO_RCVTIMEO 20
Definition at line 232 of file socket.h.
SO_REUSEADDR
#define SO_REUSEADDR 2
Definition at line 201 of file socket.h.
SO_REUSEPORT
#define SO_REUSEPORT 15
Definition at line 214 of file socket.h.
SO_RXQ_OVFL
#define SO_RXQ_OVFL 40
Definition at line 265 of file socket.h.
SO_SECURITY_AUTHENTICATION
#define SO_SECURITY_AUTHENTICATION 22
Definition at line 249 of file socket.h.
SO_SECURITY_ENCRYPTION_NETWORK
#define SO_SECURITY_ENCRYPTION_NETWORK 24
Definition at line 251 of file socket.h.
SO_SECURITY_ENCRYPTION_TRANSPORT
#define SO_SECURITY_ENCRYPTION_TRANSPORT 23
Definition at line 250 of file socket.h.
SO_SELECT_ERR_QUEUE
#define SO_SELECT_ERR_QUEUE 45
Definition at line 271 of file socket.h.
SO_SNDBUF
#define SO_SNDBUF 7
Definition at line 206 of file socket.h.
SO_SNDBUFFORCE
#define SO_SNDBUFFORCE 32
Definition at line 221 of file socket.h.
SO_SNDLOWAT
#define SO_SNDLOWAT 19
Definition at line 218 of file socket.h.
SO_SNDTIMEO
#define SO_SNDTIMEO 21
Definition at line 233 of file socket.h.
SO_TIMESTAMP
#define SO_TIMESTAMP 29
Definition at line 243 of file socket.h.
SO_TIMESTAMPING
#define SO_TIMESTAMPING 37
Definition at line 245 of file socket.h.
SO_TIMESTAMPNS
#define SO_TIMESTAMPNS 35
Definition at line 244 of file socket.h.
SO_TXTIME
#define SO_TXTIME 61
Definition at line 288 of file socket.h.
SO_TYPE
#define SO_TYPE 3
Definition at line 202 of file socket.h.
SO_WIFI_STATUS
#define SO_WIFI_STATUS 41
Definition at line 266 of file socket.h.
SO_ZEROCOPY
#define SO_ZEROCOPY 60
Definition at line 287 of file socket.h.
SOCK_CLOEXEC
#define SOCK_CLOEXEC 02000000
Definition at line 95 of file socket.h.
SOCK_DCCP
#define SOCK_DCCP 6
Definition at line 91 of file socket.h.
SOCK_DGRAM
#define SOCK_DGRAM 2
Definition at line 85 of file socket.h.
SOCK_NONBLOCK
#define SOCK_NONBLOCK 04000
Definition at line 96 of file socket.h.
SOCK_PACKET
#define SOCK_PACKET 10
Definition at line 92 of file socket.h.
SOCK_RAW
#define SOCK_RAW 3
Definition at line 88 of file socket.h.
SOCK_RDM
#define SOCK_RDM 4
Definition at line 89 of file socket.h.
SOCK_SEQPACKET
#define SOCK_SEQPACKET 5
Definition at line 90 of file socket.h.
SOCK_STREAM
#define SOCK_STREAM 1
Definition at line 84 of file socket.h.
SOL_AAL
#define SOL_AAL 265
Definition at line 308 of file socket.h.
SOL_ALG
#define SOL_ALG 279
Definition at line 322 of file socket.h.
SOL_ATM
#define SOL_ATM 264
Definition at line 307 of file socket.h.
SOL_BLUETOOTH
#define SOL_BLUETOOTH 274
Definition at line 317 of file socket.h.
SOL_CAIF
#define SOL_CAIF 278
Definition at line 321 of file socket.h.
SOL_DCCP
#define SOL_DCCP 269
Definition at line 312 of file socket.h.
SOL_DECNET
#define SOL_DECNET 261
Definition at line 304 of file socket.h.
SOL_ICMPV6
#define SOL_ICMPV6 58
Definition at line 301 of file socket.h.
SOL_IP
#define SOL_IP 0
Definition at line 299 of file socket.h.
SOL_IPV6
#define SOL_IPV6 41
Definition at line 300 of file socket.h.
SOL_IRDA
#define SOL_IRDA 266
Definition at line 309 of file socket.h.
SOL_IUCV
#define SOL_IUCV 277
Definition at line 320 of file socket.h.
SOL_KCM
#define SOL_KCM 281
Definition at line 324 of file socket.h.
SOL_LLC
#define SOL_LLC 268
Definition at line 311 of file socket.h.
SOL_NETBEUI
#define SOL_NETBEUI 267
Definition at line 310 of file socket.h.
SOL_NETLINK
#define SOL_NETLINK 270
Definition at line 313 of file socket.h.
SOL_NFC
#define SOL_NFC 280
Definition at line 323 of file socket.h.
SOL_PACKET
#define SOL_PACKET 263
Definition at line 306 of file socket.h.
SOL_PNPIPE
#define SOL_PNPIPE 275
Definition at line 318 of file socket.h.
SOL_PPPOL2TP
#define SOL_PPPOL2TP 273
Definition at line 316 of file socket.h.
SOL_RAW
#define SOL_RAW 255
Definition at line 303 of file socket.h.
SOL_RDS
#define SOL_RDS 276
Definition at line 319 of file socket.h.
SOL_RXRPC
#define SOL_RXRPC 272
Definition at line 315 of file socket.h.
SOL_SOCKET
#define SOL_SOCKET 1
Definition at line 296 of file socket.h.
SOL_TIPC
#define SOL_TIPC 271
Definition at line 314 of file socket.h.
SOL_TLS
#define SOL_TLS 282
Definition at line 325 of file socket.h.
SOL_X25
#define SOL_X25 262
Definition at line 305 of file socket.h.
SOL_XDP
#define SOL_XDP 283
Definition at line 326 of file socket.h.
SOMAXCONN
#define SOMAXCONN 128
Definition at line 328 of file socket.h.
Function Documentation
accept()
int accept (int , struct sockaddr * __restrict, socklen_t * __restrict)
Referenced by accept4(), dolisten(), ftpdataio_get_pasv_fd(), handle_accept(), inetd_main(), mini_httpd_nommu(), nc_main(), strpbrk(), tcpudpsvd_main(), and telnetd_main().
accept4()
int accept4 (int , struct sockaddr * __restrict, socklen_t * __restrict, int)
bind()
int bind (int fd, const struct sockaddr * addr, socklen_t len)
Definition at line 4 of file bind.c.
 {
     return socketcall(bind, fd, addr, len, 0, 0, 0);
 }
References addr, bind(), fd, len, and socketcall.
Referenced by __res_msend_rc(), accept_builtin(), bind(), copy_inode(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), inetd_main(), prepare_socket_fd(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), and xbind().
connect()
int connect (int fd, const struct sockaddr * addr, socklen_t len)
Definition at line 4 of file connect.c.
 {
     return socketcall_cp(connect, fd, addr, len, 0, 0, 0);
 }
References addr, connect(), fd, len, and socketcall_cp.
Referenced by __lookup_name(), __nscd_query(), __openlog(), _vsyslog(), ConfigList::ConfigList(), ConfigMainWindow::ConfigMainWindow(), connect(), connect_w_timeout(), d6_send_kernel_packet_from_client_data_ifindex(), getaddrinfo(), handle_incoming_and_exit(), inetd_main(), pscan_main(), start_tcp(), udhcp_send_kernel_packet(), and xconnect().
getpeername()
int getpeername (int , struct sockaddr * __restrict, socklen_t * __restrict)
Referenced by get_peer_lsa(), handle_port(), isnetconn(), and mini_httpd_inetd().
getsockname()
int getsockname (int , struct sockaddr * __restrict, socklen_t * __restrict)
Referenced by __lookup_name(), bb_getsockname(), bind_for_passive_mode(), dolisten(), get_sock_lsa(), nc_main(), prepare_socket_fd(), and tcpudpsvd_main().
getsockopt()
int getsockopt (int , int , int , void * __restrict, socklen_t * __restrict)
Referenced by dolisten(), and tcpudpsvd_main().
listen()
int listen (int fd, int backlog)
Definition at line 4 of file listen.c.
 {
     return socketcall(listen, fd, backlog, 0, 0, 0, 0);
 }
References fd, listen(), and socketcall.
Referenced by accept_builtin(), listen(), prepare_socket_fd(), and xlisten().
recv()
ssize_t recv (int fd, void * buf, size_t len, int flags)
Definition at line 3 of file recv.c.
 {
     return recvfrom(fd, buf, len, flags, 0, 0);
 }
References buf, fd, flags, len, and recvfrom().
Referenced by __netlink_enumerate(), check_existence_through_netlink(), inetd_main(), ping4(), recv_and_process_peer_pkt(), rtnl_send_check(), and start().
recvfrom()
ssize_t recvfrom (int , void * __restrict, size_t , int , struct sockaddr * __restrict, socklen_t * __restrict)
Referenced by dhcprelay_main(), inetd_main(), ping4(), recv(), recv_from_to(), and wait_for_reply().
recvmsg()
ssize_t recvmsg (int fd, struct msghdr * msg, int flags)
Definition at line 50 of file recvmsg.c.
 {
     ssize_t r;
     socklen_t orig_controllen = msg->msg_controllen;
 #if LONG_MAX > INT_MAX
     struct msghdr h, *orig = msg;
     if (msg) {
         h = *msg;
         h.__pad1 = h.__pad2 = 0;
         msg = &h;
     }
 #endif
     r = socketcall_cp(recvmsg, fd, msg, flags, 0, 0, 0);
     if (r >= 0) __convert_scm_timestamps(msg, orig_controllen);
 #if LONG_MAX > INT_MAX
     if (orig) *orig = h;
 #endif
     return r;
 }
References __convert_scm_timestamps(), fd, flags, h, msghdr::msg_controllen, recvmsg(), and socketcall_cp.
Referenced by __res_msend_rc(), d4_recv_raw_packet(), recv_from_to(), recvmsg(), rtnl_dump_filter(), and rtnl_talk().
send()
ssize_t send (int fd, const void * buf, size_t len, int flags)
Definition at line 3 of file send.c.
 {
     return sendto(fd, buf, len, flags, 0, 0);
 }
References buf, fd, flags, len, and sendto().
Referenced by __netlink_enumerate(), _vsyslog(), dequote_escapes(), dequote_string(), expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), pat_subst(), quote_escapes_internal(), quote_globbing_chars(), quote_string(), quote_string_for_repl(), remove_quoted_ifs(), sh_backslash_quote(), sh_charvis(), sh_double_quote(), sh_mkdoublequoted(), string_extract_double_quoted(), string_quote_removal(), tcpudpsvd_main(), and unquoted_glob_pattern_p().
sendmsg()
ssize_t sendmsg (int fd, const struct msghdr * msg, int flags)
Definition at line 7 of file sendmsg.c.
 {
 #if LONG_MAX > INT_MAX
     struct msghdr h;
     /* Kernels before 2.6.38 set SCM_MAX_FD to 255, allocate enough
      * space to support an SCM_RIGHTS ancillary message with 255 fds.
      * Kernels since 2.6.38 set SCM_MAX_FD to 253. */
     struct cmsghdr chbuf[CMSG_SPACE(255*sizeof(int))/sizeof(struct cmsghdr)+1], *c;
     if (msg) {
         h = *msg;
         h.__pad1 = h.__pad2 = 0;
         msg = &h;
         if (h.msg_controllen) {
             if (h.msg_controllen > sizeof chbuf) {
                 errno = ENOMEM;
                 return -1;
             }
             memcpy(chbuf, h.msg_control, h.msg_controllen);
             h.msg_control = chbuf;
             for (c=CMSG_FIRSTHDR(&h); c; c=CMSG_NXTHDR(&h,c))
                 c->__pad1 = 0;
         }
     }
 #endif
     return socketcall_cp(sendmsg, fd, msg, flags, 0, 0, 0);
 }
References c, CMSG_FIRSTHDR, CMSG_NXTHDR, CMSG_SPACE, ENOMEM, errno, fd, flags, h, memcpy, sendmsg(), and socketcall_cp.
Referenced by __nscd_query(), __res_msend_rc(), rtnl_dump_request(), rtnl_talk(), send_to_from(), sendmmsg(), sendmsg(), and start_tcp().
sendto()
ssize_t sendto (int fd, const void * buf, size_t len, int flags, const struct sockaddr * addr, socklen_t alen)
Definition at line 4 of file sendto.c.
 {
     return socketcall_cp(sendto, fd, buf, len, flags, addr, alen);
 }
References addr, buf, fd, flags, len, sendto(), and socketcall_cp.
Referenced by __res_msend_rc(), arpping(), d6_send_raw_packet_from_client_data_ifindex(), do_sendto(), do_syslogd(), send(), send_pack(), send_to_from(), sendto(), sendto_ip4(), udhcp_send_raw_packet(), and xsendto().
setsockopt()
int setsockopt (int fd, int level, int optname, const void * optval, socklen_t optlen)
Definition at line 9 of file setsockopt.c.
 {
     const struct timeval *tv;
     time_t s;
     suseconds_t us;
     int r = __socketcall(setsockopt, fd, level, optname, optval, optlen, 0);
     if (r==-ENOPROTOOPT) switch (level) {
     case SOL_SOCKET:
         switch (optname) {
         case SO_RCVTIMEO:
         case SO_SNDTIMEO:
             if (SO_RCVTIMEO == SO_RCVTIMEO_OLD) break;
             if (optlen < sizeof *tv) return __syscall_ret(-EINVAL);
             tv = optval;
             s = tv->tv_sec;
             us = tv->tv_usec;
             if (!IS32BIT(s)) return __syscall_ret(-ENOTSUP);
             if (optname==SO_RCVTIMEO) optname=SO_RCVTIMEO_OLD;
             if (optname==SO_SNDTIMEO) optname=SO_SNDTIMEO_OLD;
             r = __socketcall(setsockopt, fd, level, optname,
                 ((long[]){s, CLAMP(us)}), 2*sizeof(long), 0);
             break;
         case SO_TIMESTAMP:
         case SO_TIMESTAMPNS:
             if (SO_TIMESTAMP == SO_TIMESTAMP_OLD) break;
             if (optname==SO_TIMESTAMP) optname=SO_TIMESTAMP_OLD;
             if (optname==SO_TIMESTAMPNS) optname=SO_TIMESTAMPNS_OLD;
             r = __socketcall(setsockopt, fd, level,
                 optname, optval, optlen, 0);
             break;
         }
     }
     return __syscall_ret(r);
 }
References __socketcall, __syscall_ret(), CLAMP, EINVAL, ENOPROTOOPT, ENOTSUP, fd, IS32BIT, s, setsockopt(), SO_RCVTIMEO, SO_RCVTIMEO_OLD, SO_SNDTIMEO, SO_SNDTIMEO_OLD, SO_TIMESTAMP, SO_TIMESTAMP_OLD, SO_TIMESTAMPNS, SO_TIMESTAMPNS_OLD, SOL_SOCKET, timeval::tv_sec, and timeval::tv_usec.
Referenced by __res_msend_rc(), accept_builtin(), d6_raw_socket(), setsockopt(), setsockopt_int(), start_tcp(), traceroute_init(), and udhcp_raw_socket().
shutdown()
int shutdown (int fd, int how)
Definition at line 4 of file shutdown.c.
 {
     return socketcall(shutdown, fd, how, 0, 0, 0, 0);
 }
References fd, shutdown(), and socketcall.
Referenced by close_conn_and_exit(), download_one_url(), log_and_exit(), nc_main(), readwrite(), and shutdown().
sockatmark()
int sockatmark (int s)
Definition at line 4 of file sockatmark.c.
 {
     int ret;
     if (ioctl(s, SIOCATMARK, &ret) < 0)
         return -1;
     return ret;
 }
References ioctl(), s, and SIOCATMARK.
socket()
int socket (int domain, int type, int protocol)
Definition at line 6 of file socket.c.
 {
     int s = __socketcall(socket, domain, type, protocol, 0, 0, 0);
     if ((s==-EINVAL || s==-EPROTONOSUPPORT)
         && (type&(SOCK_CLOEXEC|SOCK_NONBLOCK))) {
         s = __socketcall(socket, domain,
             type & ~(SOCK_CLOEXEC|SOCK_NONBLOCK),
             protocol, 0, 0, 0);
         if (s < 0) return __syscall_ret(s);
         if (type & SOCK_CLOEXEC)
             __syscall(SYS_fcntl, s, F_SETFD, FD_CLOEXEC);
         if (type & SOCK_NONBLOCK)
             __syscall(SYS_fcntl, s, F_SETFL, O_NONBLOCK);
     }
     return __syscall_ret(s);
 }
References __socketcall, __syscall, __syscall_ret(), domain, EINVAL, EPROTONOSUPPORT, F_SETFD, F_SETFL, FD_CLOEXEC, O_NONBLOCK, s, SOCK_CLOEXEC, SOCK_NONBLOCK, socket(), and type.
Referenced by __lookup_name(), __nscd_query(), __openlog(), __res_msend_rc(), __rtnetlink_enumerate(), accept_builtin(), arpping(), NetworkUDP::UDP::Connect(), copy_inode(), create_icmp_socket(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), get_ctl_fd(), getaddrinfo(), handle_incoming_and_exit(), if_indextoname(), if_nametoindex(), inetd_main(), mq_notify(), prepare_socket_fd(), print_queuelen(), scan_proc_net_or_maps(), socket(), start_tcp(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), xsocket(), and xsocket_type().
socketpair()
int socketpair (int domain, int type, int protocol, int fd[2])
Definition at line 6 of file socketpair.c.
 {
     int r = socketcall(socketpair, domain, type, protocol, fd, 0, 0);
     if (r<0 && (errno==EINVAL || errno==EPROTONOSUPPORT)
         && (type&(SOCK_CLOEXEC|SOCK_NONBLOCK))) {
         r = socketcall(socketpair, domain,
             type & ~(SOCK_CLOEXEC|SOCK_NONBLOCK),
             protocol, fd, 0, 0);
         if (r < 0) return r;
         if (type & SOCK_CLOEXEC) {
             __syscall(SYS_fcntl, fd[0], F_SETFD, FD_CLOEXEC);
             __syscall(SYS_fcntl, fd[1], F_SETFD, FD_CLOEXEC);
         }
         if (type & SOCK_NONBLOCK) {
             __syscall(SYS_fcntl, fd[0], F_SETFL, O_NONBLOCK);
             __syscall(SYS_fcntl, fd[1], F_SETFL, O_NONBLOCK);
         }
     }
     return r;
 }
References __syscall, domain, EINVAL, EPROTONOSUPPORT, errno, F_SETFD, F_SETFL, fd, FD_CLOEXEC, O_NONBLOCK, SOCK_CLOEXEC, SOCK_NONBLOCK, socketcall, socketpair(), and type.
Referenced by socketpair().