Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_ceilng.c File Reference
p_ceilng.c File Reference
#include "z_zone.h"
#include "doomdef.h"
#include "p_local.h"
#include "s_sound.h"
#include "doomstat.h"
#include "r_state.h"
#include "sounds.h"
Functions
void T_MoveCeiling (ceiling_t *ceiling)
int EV_DoCeiling (line_t *line, ceiling_e type)
void P_AddActiveCeiling (ceiling_t *c)
void P_RemoveActiveCeiling (ceiling_t *c)
void P_ActivateInStasisCeiling (line_t *line)
int EV_CeilingCrushStop (line_t *line)
Variables
ceiling_t * activeceilings [MAXCEILINGS]
Function Documentation
EV_CeilingCrushStop()
int EV_CeilingCrushStop (line_t * line)
Definition at line 303 of file p_ceilng.c.
 {
     int     i;
     int     rtn;
     rtn = 0;
     for (i = 0;i < MAXCEILINGS;i++)
     {
     if (activeceilings[i]
         && (activeceilings[i]->tag == line->tag)
         && (activeceilings[i]->direction != 0))
     {
         activeceilings[i]->olddirection = activeceilings[i]->direction;
         activeceilings[i]->thinker.function.acv = (actionf_v)NULL;
         activeceilings[i]->direction = 0;       // in-stasis
         rtn = 1;
     }
     }
     return rtn;
 }
References activeceilings, actionf_t::acv, ceiling_t::direction, thinker_s::function, i, MAXCEILINGS, NULL, ceiling_t::olddirection, line_s::tag, and ceiling_t::thinker.
Referenced by P_CrossSpecialLine().
EV_DoCeiling()
int EV_DoCeiling (line_t * line, ceiling_e type)
Definition at line 161 of file p_ceilng.c.
 {
     int     secnum;
     int     rtn;
     sector_t*   sec;
     ceiling_t*  ceiling;
     secnum = -1;
     rtn = 0;
     //  Reactivate in-stasis ceilings...for certain types.
     switch(type)
     {
       case fastCrushAndRaise:
       case silentCrushAndRaise:
       case crushAndRaise:
     P_ActivateInStasisCeiling(line);
       default:
     break;
     }
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     // new door thinker
     rtn = 1;
     ceiling = Z_Malloc (sizeof(*ceiling), PU_LEVSPEC, 0);
     P_AddThinker (&ceiling->thinker);
     sec->specialdata = ceiling;
     ceiling->thinker.function.acp1 = (actionf_p1)T_MoveCeiling;
     ceiling->sector = sec;
     ceiling->crush = false;
     switch(type)
     {
       case fastCrushAndRaise:
         ceiling->crush = true;
         ceiling->topheight = sec->ceilingheight;
         ceiling->bottomheight = sec->floorheight + (8*FRACUNIT);
         ceiling->direction = -1;
         ceiling->speed = CEILSPEED * 2;
         break;
       case silentCrushAndRaise:
       case crushAndRaise:
         ceiling->crush = true;
         ceiling->topheight = sec->ceilingheight;
       case lowerAndCrush:
       case lowerToFloor:
         ceiling->bottomheight = sec->floorheight;
         if (type != lowerToFloor)
         ceiling->bottomheight += 8*FRACUNIT;
         ceiling->direction = -1;
         ceiling->speed = CEILSPEED;
         break;
       case raiseToHighest:
         ceiling->topheight = P_FindHighestCeilingSurrounding(sec);
         ceiling->direction = 1;
         ceiling->speed = CEILSPEED;
         break;
     }
     ceiling->tag = sec->tag;
     ceiling->type = type;
     P_AddActiveCeiling(ceiling);
     }
     return rtn;
 }
References actionf_t::acp1, ceiling_t::bottomheight, sector_t::ceilingheight, CEILSPEED, ceiling_t::crush, crushAndRaise, ceiling_t::direction, fastCrushAndRaise, sector_t::floorheight, FRACUNIT, thinker_s::function, lowerAndCrush, lowerToFloor, P_ActivateInStasisCeiling(), P_AddActiveCeiling(), P_AddThinker(), P_FindHighestCeilingSurrounding(), P_FindSectorFromLineTag(), PU_LEVSPEC, raiseToHighest, ceiling_t::sector, sectors, silentCrushAndRaise, sector_t::specialdata, ceiling_t::speed, T_MoveCeiling(), ceiling_t::tag, sector_t::tag, ceiling_t::thinker, ceiling_t::topheight, type, ceiling_t::type, and Z_Malloc().
Referenced by P_CrossSpecialLine(), and P_UseSpecialLine().
P_ActivateInStasisCeiling()
void P_ActivateInStasisCeiling (line_t * line)
Definition at line 280 of file p_ceilng.c.
 {
     int     i;
     for (i = 0;i < MAXCEILINGS;i++)
     {
     if (activeceilings[i]
         && (activeceilings[i]->tag == line->tag)
         && (activeceilings[i]->direction == 0))
     {
         activeceilings[i]->direction = activeceilings[i]->olddirection;
         activeceilings[i]->thinker.function.acp1
           = (actionf_p1)T_MoveCeiling;
     }
     }
 }
References actionf_t::acp1, activeceilings, ceiling_t::direction, thinker_s::function, i, MAXCEILINGS, ceiling_t::olddirection, T_MoveCeiling(), line_s::tag, and ceiling_t::thinker.
Referenced by EV_DoCeiling().
P_AddActiveCeiling()
void P_AddActiveCeiling (ceiling_t * c)
Definition at line 240 of file p_ceilng.c.
 {
     int     i;
     for (i = 0; i < MAXCEILINGS;i++)
     {
     if (activeceilings[i] == NULL)
     {
         activeceilings[i] = c;
         return;
     }
     }
 }
References activeceilings, c, i, MAXCEILINGS, and NULL.
Referenced by EV_DoCeiling(), and P_UnArchiveSpecials().
P_RemoveActiveCeiling()
void P_RemoveActiveCeiling (ceiling_t * c)
Definition at line 259 of file p_ceilng.c.
 {
     int     i;
     for (i = 0;i < MAXCEILINGS;i++)
     {
     if (activeceilings[i] == c)
     {
         activeceilings[i]->sector->specialdata = NULL;
         P_RemoveThinker (&activeceilings[i]->thinker);
         activeceilings[i] = NULL;
         break;
     }
     }
 }
References activeceilings, c, i, MAXCEILINGS, NULL, P_RemoveThinker(), ceiling_t::sector, and sector_t::specialdata.
Referenced by T_MoveCeiling().
T_MoveCeiling()
void T_MoveCeiling (ceiling_t * ceiling)
Definition at line 45 of file p_ceilng.c.
 {
     result_e    res;
     switch(ceiling->direction)
     {
       case 0:
     // IN STASIS
     break;
       case 1:
     // UP
     res = T_MovePlane(ceiling->sector,
               ceiling->speed,
               ceiling->topheight,
               false,1,ceiling->direction);
     if (!(leveltime&7))
     {
         switch(ceiling->type)
         {
           case silentCrushAndRaise:
         break;
           default:
         S_StartSound(&ceiling->sector->soundorg, sfx_stnmov);
         // ?
         break;
         }
     }
     if (res == pastdest)
     {
         switch(ceiling->type)
         {
           case raiseToHighest:
         P_RemoveActiveCeiling(ceiling);
         break;
           case silentCrushAndRaise:
         S_StartSound(&ceiling->sector->soundorg, sfx_pstop);
           case fastCrushAndRaise:
           case crushAndRaise:
         ceiling->direction = -1;
         break;
           default:
         break;
         }
     }
     break;
       case -1:
     // DOWN
     res = T_MovePlane(ceiling->sector,
               ceiling->speed,
               ceiling->bottomheight,
               ceiling->crush,1,ceiling->direction);
     if (!(leveltime&7))
     {
         switch(ceiling->type)
         {
           case silentCrushAndRaise: break;
           default:
         S_StartSound(&ceiling->sector->soundorg, sfx_stnmov);
         }
     }
     if (res == pastdest)
     {
         switch(ceiling->type)
         {
           case silentCrushAndRaise:
         S_StartSound(&ceiling->sector->soundorg, sfx_pstop);
           case crushAndRaise:
         ceiling->speed = CEILSPEED;
           case fastCrushAndRaise:
         ceiling->direction = 1;
         break;
           case lowerAndCrush:
           case lowerToFloor:
         P_RemoveActiveCeiling(ceiling);
         break;
           default:
         break;
         }
     }
     else // ( res != pastdest )
     {
         if (res == crushed)
         {
         switch(ceiling->type)
         {
           case silentCrushAndRaise:
           case crushAndRaise:
           case lowerAndCrush:
             ceiling->speed = CEILSPEED / 8;
             break;
           default:
             break;
         }
         }
     }
     break;
     }
 }
References ceiling_t::bottomheight, CEILSPEED, ceiling_t::crush, crushAndRaise, crushed, ceiling_t::direction, fastCrushAndRaise, leveltime, lowerAndCrush, lowerToFloor, P_RemoveActiveCeiling(), pastdest, raiseToHighest, S_StartSound(), ceiling_t::sector, sfx_pstop, sfx_stnmov, silentCrushAndRaise, sector_t::soundorg, ceiling_t::speed, T_MovePlane(), ceiling_t::topheight, and ceiling_t::type.
Referenced by EV_DoCeiling(), P_ActivateInStasisCeiling(), P_ArchiveSpecials(), and P_UnArchiveSpecials().
Variable Documentation
activeceilings
ceiling_t* activeceilings[MAXCEILINGS]
Definition at line 38 of file p_ceilng.c.
Referenced by EV_CeilingCrushStop(), P_ActivateInStasisCeiling(), P_AddActiveCeiling(), P_ArchiveSpecials(), P_RemoveActiveCeiling(), and P_SpawnSpecials().