Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/w_main.c File Reference
w_main.c File Reference
#include "doomfeatures.h"
#include "d_iwad.h"
#include "m_argv.h"
#include "w_main.h"
#include "w_merge.h"
#include "w_wad.h"
#include "z_zone.h"
Functions
boolean W_ParseCommandLine (void)
Function Documentation
W_ParseCommandLine()
boolean W_ParseCommandLine (void)
Definition at line 30 of file w_main.c.
 {
     boolean modifiedgame = false;
     int p;
 #ifdef FEATURE_WAD_MERGE
     // Merged PWADs are loaded first, because they are supposed to be
     // modified IWADs.
     // @arg <files>
     // @category mod
     //
     // Simulates the behavior of deutex's -merge option, merging a PWAD
     // into the main IWAD.  Multiple files may be specified.
     //
     p = M_CheckParmWithArgs("-merge", 1);
     if (p > 0)
     {
         for (p = p + 1; p<myargc && myargv[p][0] != '-'; ++p)
         {
             char *filename;
             modifiedgame = true;
             filename = D_TryFindWADByName(myargv[p]);
             printf(" merging %s\n", filename);
             W_MergeFile(filename);
         }
     }
     // NWT-style merging:
     // NWT's -merge option:
     // @arg <files>
     // @category mod
     //
     // Simulates the behavior of NWT's -merge option.  Multiple files
     // may be specified.
     p = M_CheckParmWithArgs("-nwtmerge", 1);
     if (p > 0)
     {
         for (p = p + 1; p<myargc && myargv[p][0] != '-'; ++p)
         {
             char *filename;
             modifiedgame = true;
             filename = D_TryFindWADByName(myargv[p]);
             printf(" performing NWT-style merge of %s\n", filename);
             W_NWTDashMerge(filename);
         }
     }
     // Add flats
     // @arg <files>
     // @category mod
     //
     // Simulates the behavior of NWT's -af option, merging flats into
     // the main IWAD directory.  Multiple files may be specified.
     //
     p = M_CheckParmWithArgs("-af", 1);
     if (p > 0)
     {
         for (p = p + 1; p<myargc && myargv[p][0] != '-'; ++p)
         {
             char *filename;
             modifiedgame = true;
             filename = D_TryFindWADByName(myargv[p]);
             printf(" merging flats from %s\n", filename);
             W_NWTMergeFile(filename, W_NWT_MERGE_FLATS);
         }
     }
     // @arg <files>
     // @category mod
     //
     // Simulates the behavior of NWT's -as option, merging sprites
     // into the main IWAD directory.  Multiple files may be specified.
     //
     p = M_CheckParmWithArgs("-as", 1);
     if (p > 0)
     {
         for (p = p + 1; p<myargc && myargv[p][0] != '-'; ++p)
         {
             char *filename;
             modifiedgame = true;
             filename = D_TryFindWADByName(myargv[p]);
             printf(" merging sprites from %s\n", filename);
             W_NWTMergeFile(filename, W_NWT_MERGE_SPRITES);
         }
     }
     // @arg <files>
     // @category mod
     //
     // Equivalent to "-af <files> -as <files>".
     //
     p = M_CheckParmWithArgs("-aa", 1);
     if (p > 0)
     {
         for (p = p + 1; p<myargc && myargv[p][0] != '-'; ++p)
         {
             char *filename;
             modifiedgame = true;
             filename = D_TryFindWADByName(myargv[p]);
             printf(" merging sprites and flats from %s\n", filename);
             W_NWTMergeFile(filename, W_NWT_MERGE_SPRITES | W_NWT_MERGE_FLATS);
         }
     }
 #endif
     // @arg <files>
     // @vanilla
     //
     // Load the specified PWAD files.
     //
     p = M_CheckParmWithArgs ("-file", 1);
     if (p)
     {
     // the parms after p are wadfile/lump names,
     // until end of parms or another - preceded parm
     modifiedgame = true;            // homebrew levels
     while (++p != myargc && myargv[p][0] != '-')
         {
             char *filename;
             filename = D_TryFindWADByName(myargv[p]);
             printf(" adding %s\n", filename);
         W_AddFile(filename);
         }
     }
 //    W_PrintDirectory();
     return modifiedgame;
 }
References D_TryFindWADByName(), filename, M_CheckParmWithArgs(), modifiedgame, myargc, myargv, p, printf, W_AddFile(), W_MergeFile(), W_NWT_MERGE_FLATS, W_NWT_MERGE_SPRITES, W_NWTDashMerge(), and W_NWTMergeFile().
Referenced by D_DoomMain().