Fennix Userspace: Userspace/apps/base/busybox/libbb/xatonum.c File Reference
xatonum.c File Reference
#include "libbb.h"
#include "xatonum_template.c"
Macros
#define type long long
#define xstrtou(rest) xstrtoull##rest
#define xstrto(rest) xstrtoll##rest
#define xatou(rest) xatoull##rest
#define xato(rest) xatoll##rest
#define XSTR_UTYPE_MAX ULLONG_MAX
#define XSTR_TYPE_MAX LLONG_MAX
#define XSTR_TYPE_MIN LLONG_MIN
#define XSTR_STRTOU strtoull
Functions
int FAST_FUNC xatoi_positive (const char *numstr)
uint16_t FAST_FUNC xatou16 (const char *numstr)
Variables
const struct suffix_mult bkm_suffixes[] ALIGN_SUFFIX
Macro Definition Documentation
type
#define type long long
Definition at line 11 of file xatonum.c.
xato
#define xato (rest) xatoll##rest
Definition at line 15 of file xatonum.c.
xatou
#define xatou (rest) xatoull##rest
Definition at line 14 of file xatonum.c.
XSTR_STRTOU
#define XSTR_STRTOU strtoull
Definition at line 19 of file xatonum.c.
XSTR_TYPE_MAX
#define XSTR_TYPE_MAX LLONG_MAX
Definition at line 17 of file xatonum.c.
XSTR_TYPE_MIN
#define XSTR_TYPE_MIN LLONG_MIN
Definition at line 18 of file xatonum.c.
XSTR_UTYPE_MAX
#define XSTR_UTYPE_MAX ULLONG_MAX
Definition at line 16 of file xatonum.c.
xstrto
#define xstrto (rest) xstrtoll##rest
Definition at line 13 of file xatonum.c.
xstrtou
#define xstrtou (rest) xstrtoull##rest
Definition at line 12 of file xatonum.c.
Function Documentation
xatoi_positive()
int FAST_FUNC xatoi_positive (const char * numstr)
Definition at line 61 of file xatonum.c.
 {
     return xatou_range(numstr, 0, INT_MAX);
 }
References INT_MAX.
Referenced by blockdev_main(), brctl_main(), cut_main(), date_main(), expand_one_var(), flock_main(), fsck_main(), hdparm_main(), hexdump_main(), init(), init_int(), ionice_main(), iostat_main(), is_hpet_irq(), logdir_open(), login_main(), mpstat_main(), mt_main(), nameif_parse_selector(), parse_map_file(), parse_params(), pmap_main(), rfkill_main(), and vgetopt32().
xatou16()
uint16_t FAST_FUNC xatou16 (const char * numstr)
Definition at line 66 of file xatonum.c.
 {
     return xatou_range(numstr, 0, 0xffff);
 }
Referenced by nbdclient_main(), parse_map_file(), telnetd_main(), traceroute_init(), udhcpc6_main(), udhcpc_main(), and udhcpd_main().
Variable Documentation
ALIGN_SUFFIX
const struct suffix_mult kmg_i_suffixes [] ALIGN_SUFFIX
Initial value:
= {
    { "b", 512 },
    { "k", 1024 },
    { "m", 1024*1024 },
    { "", 0 }
}
Definition at line 71 of file xatonum.c.
Referenced by logdir_open(), parse_params(), ubi_tools_main(), and watchdog_main().