Fennix: AC97Device Class Reference
AC97Device Class Reference
Public Member Functions
size_t write (uint8_t *Buffer, size_t Size)
int ioctl (AudioIoctl, void *)
void OnInterruptReceived (TrapFrame *)
void Panic ()
AC97Device (PCIHeader0 *_Header)
~AC97Device ()
Private Attributes
PCIHeader0 * Header
BufferDescriptorList * DescriptorList = nullptr
uint16_t MixerAddress
uint16_t BusMasterAddress
AudioEncodingValues Encoding = AE_PCMs16le
char Channels = 2
uint8_t Volume = AV_Maximum
bool Mute = false
int SampleRate = 48000
char SampleSize = 2
Detailed Description
Definition at line 353 of file ac97.cpp.
Constructor & Destructor Documentation
AC97Device()
AC97Device::AC97Device (PCIHeader0 * _Header) inline
Definition at line 605 of file ac97.cpp.
         : Header(_Header)
     {
         /* Native Audio Mixer Base Address */
         uint32_t PCIBAR0 = Header->BAR0;
         /* Native Audio Bus Master Base Address */
         uint32_t PCIBAR1 = Header->BAR1;
         // uint8_t Type = PCIBAR0 & 1;
         MixerAddress = (uint16_t)(PCIBAR0 & (~3));
         BusMasterAddress = PCIBAR1 & (~15);
         uint16_t OutputPCMTransferControl = BusMasterAddress + PCMOUT_TransferControl;
         /* DescriptorList address MUST be physical. */
         DescriptorList = (BufferDescriptorList *)AllocateMemory(TO_PAGES(sizeof(BufferDescriptorList) * DescriptorListLength));
         memset(DescriptorList, 0, sizeof(BufferDescriptorList) * DescriptorListLength);
         uint16_t DLSampleCount = (uint16_t)(PAGE_SIZE / SampleSize);
         for (int i = 0; i < DescriptorListLength; i++)
         {
             DescriptorList[i].Address = (uint32_t)(uintptr_t)AllocateMemory(TO_PAGES(sizeof(uint16_t *)));
             DescriptorList[i].SampleCount = DLSampleCount;
             DescriptorList[i].Flags = 0;
             DebugLog("DescriptorList[%d] = { Address: %#lx, SampleCount: %d, Flags: %#lx }",
                      i,
                      DescriptorList[i].Address,
                      DescriptorList[i].SampleCount,
                      DescriptorList[i].Flags);
         }
         outw(MixerAddress + NAM_MasterVolume, MixerVolume(Volume, Volume, Mute));
         outw(MixerAddress + NAM_PCMOutVolume, MixerVolume(Volume, Volume, Mute));
         Volume = 0x3F - (0x3F * /* VOL 50% */ 50 / 100);
         outw(MixerAddress + NAM_MasterVolume, MixerVolume(Volume, Volume, Mute));
         outb(OutputPCMTransferControl, inb(OutputPCMTransferControl) | TC_TransferReset);
         while (inb(OutputPCMTransferControl) & TC_TransferReset)
             ;
         uint32_t GlobalControl = inl(BusMasterAddress + NABM_GlobalControl);
         GlobalControl = (GlobalControl & ~((0x3U) << 0x16)); /* PCM 16-bit mode */
         GlobalControl = (GlobalControl & ~((0x3U) << 20));   /* 2 channels */
         GlobalControl |= GC_GlobalInterruptEnable;
         GlobalControl &= ~GC_ShutDown;
         outl(BusMasterAddress + PCMOUT_BufferDescriptorList,
              (uint32_t)(uint64_t)DescriptorList);
         outl(BusMasterAddress + NABM_GlobalControl, GlobalControl);
         uint8_t TransferControl = inb(OutputPCMTransferControl);
         TransferControl |= TC_IOCInterruptEnable |
                            TC_FifoERRORInterruptEnable;
         outb(OutputPCMTransferControl, TransferControl);
         // Stop DMA
         outb(OutputPCMTransferControl, inb(OutputPCMTransferControl) & ~TC_DMAControllerControl);
     }
References Address, BufferDescriptorList::Address, AllocateMemory(), BusMasterAddress, DebugLog, DescriptorList, DescriptorListLength, Flags, BufferDescriptorList::Flags, GC_GlobalInterruptEnable, GC_ShutDown, Header, i, inb(), inl(), memset, MixerAddress, MixerVolume(), Mute, NABM_GlobalControl, NAM_MasterVolume, NAM_PCMOutVolume, outb(), outl(), outw(), PAGE_SIZE, PCMOUT_BufferDescriptorList, PCMOUT_TransferControl, SampleCount, BufferDescriptorList::SampleCount, SampleSize, TC_DMAControllerControl, TC_FifoERRORInterruptEnable, TC_IOCInterruptEnable, TC_TransferReset, TO_PAGES, and Volume.
~AC97Device()
AC97Device::~AC97Device () inline
Definition at line 667 of file ac97.cpp.
     {
         outw(MixerAddress + NAM_MasterVolume, MixerVolume(AV_Maximum, AV_Maximum, true));
         outw(MixerAddress + NAM_PCMOutVolume, MixerVolume(AV_Maximum, AV_Maximum, true));
         // Stop DMA
         outb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl),
              inb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl)) & ~TC_DMAControllerControl);
         // Disable interrupts
         uint8_t TransferControl = inb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl));
         TransferControl &= ~(TC_LastBufferEntryInterruptEnable |
                              TC_IOCInterruptEnable |
                              TC_FifoERRORInterruptEnable);
         outb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl), TransferControl);
         // Disable global control
         uint32_t GlobalControl = inl((uint16_t)(BusMasterAddress + NABM_GlobalControl));
         GlobalControl &= ~GC_GlobalInterruptEnable;
         GlobalControl |= GC_ShutDown;
         outl((uint16_t)(BusMasterAddress + NABM_GlobalControl), GlobalControl);
     }
References AV_Maximum, BusMasterAddress, GC_GlobalInterruptEnable, GC_ShutDown, inb(), inl(), MixerAddress, MixerVolume(), NABM_GlobalControl, NAM_MasterVolume, NAM_PCMOutVolume, outb(), outl(), outw(), PCMOUT_TransferControl, TC_DMAControllerControl, TC_FifoERRORInterruptEnable, TC_IOCInterruptEnable, and TC_LastBufferEntryInterruptEnable.
Member Function Documentation
ioctl()
int AC97Device::ioctl (AudioIoctl , void *) inline
Definition at line 463 of file ac97.cpp.
     {
         // if (Data->AudioCallback.Adjust._Volume)
         // {
         //  Volume = (uint8_t)(0x3F - (0x3F * Data->AudioCallback.Adjust.Volume / 100));
         //  outw(BAR.MixerAddress + NAM_MasterVolume, MixerVolume(Volume, Volume, Mute));
         //  // outw(BAR.MixerAddress + NAM_PCMOutVolume, MixerVolume(Volume, Volume, Mute));
         // }
         // else if (Data->AudioCallback.Adjust._Encoding)
         // {
         //  fixme("Encoding changing not supported yet.");
         // }
         // else if (Data->AudioCallback.Adjust._SampleRate)
         // {
         //  switch (Data->AudioCallback.Adjust.SampleRate)
         //  {
         //  case 0:
         //  {
         //      SampleRate = 8000;
         //      break;
         //  }
         //  case 1:
         //  {
         //      SampleRate = 11025;
         //      break;
         //  }
         //  case 2:
         //  {
         //      SampleRate = 16000;
         //      break;
         //  }
         //  case 3:
         //  {
         //      SampleRate = 22050;
         //      break;
         //  }
         //  case 4:
         //  {
         //      SampleRate = 32000;
         //      break;
         //  }
         //  case 5:
         //  {
         //      SampleRate = 44100;
         //      break;
         //  }
         //  case 6:
         //  {
         //      SampleRate = 48000;
         //      break;
         //  }
         //  case 7:
         //  {
         //      SampleRate = 88200;
         //      break;
         //  }
         //  case 8:
         //  {
         //      SampleRate = 96000;
         //      break;
         //  }
         //  default:
         //  {
         //      SampleRate = 16000;
         //      error("Invalid sample rate. Defaulting to 16000.");
         //      break;
         //  }
         //  }
         // }
         // else if (Data->AudioCallback.Adjust._Channels)
         // {
         //  switch (Data->AudioCallback.Adjust.Channels)
         //  {
         //  case 0:
         //  {
         //      Channels = 1; // Mono
         //      break;
         //  }
         //  case 1:
         //  {
         //      Channels = 2; // Stereo
         //      break;
         //  }
         //  default:
         //  {
         //      Channels = 2;
         //      error("Invalid channel count. Defaulting to 2.");
         //      break;
         //  }
         //  }
         // }
         return 0;
     }
Referenced by __fs_Ioctl().
OnInterruptReceived()
void AC97Device::OnInterruptReceived (TrapFrame *) inline
Definition at line 557 of file ac97.cpp.
     {
         uint16_t Status = inw(MixerAddress + PCMOUT_Status);
         if (Status & TC_IOCInterruptEnable)
         {
             DebugLog("IOC");
             outw(MixerAddress + PCMOUT_Status, TC_IOCInterruptEnable);
             uint16_t CurrentBDL = inb(BusMasterAddress + PCMOUT_BufferDescriptorEntry);
             uint16_t LastBDL = (CurrentBDL + 2) & (DescriptorListLength - 1);
             outb(BusMasterAddress + PCMOUT_DescriptorEntries, LastBDL);
             KernelLog("FIXME: CurrentBDL: %d, LastBDL: %d", CurrentBDL, LastBDL);
         }
         else if (Status & TC_LastBufferEntryInterruptEnable)
         {
             DebugLog("Last buffer entry");
             // Stop DMA
             uint8_t TransferControl = inb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl));
             TransferControl &= ~TC_DMAControllerControl;
             outb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl), TransferControl);
             outw(MixerAddress + PCMOUT_Status, TC_LastBufferEntryInterruptEnable);
         }
         else if (Status & TC_FifoERRORInterruptEnable)
         {
             KernelLog("FIFO error");
             outw(MixerAddress + PCMOUT_Status, TC_FifoERRORInterruptEnable);
         }
         else
         {
             DebugLog("Unknown interrupt status %#x", Status);
             outw(MixerAddress + PCMOUT_Status, 0xFFFF);
         }
     }
References BusMasterAddress, DebugLog, DescriptorListLength, inb(), inw(), KernelLog(), MixerAddress, outb(), outw(), PCMOUT_BufferDescriptorEntry, PCMOUT_DescriptorEntries, PCMOUT_Status, PCMOUT_TransferControl, TC_DMAControllerControl, TC_FifoERRORInterruptEnable, TC_IOCInterruptEnable, and TC_LastBufferEntryInterruptEnable.
Panic()
void AC97Device::Panic () inline
Definition at line 591 of file ac97.cpp.
     {
         uint8_t TransferControl = inb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl));
         TransferControl &= ~(TC_LastBufferEntryInterruptEnable |
                              TC_IOCInterruptEnable |
                              TC_FifoERRORInterruptEnable);
         outb((uint16_t)(BusMasterAddress + PCMOUT_TransferControl), TransferControl);
         uint32_t GlobalControl = inl((uint16_t)(BusMasterAddress + NABM_GlobalControl));
         GlobalControl &= ~GC_GlobalInterruptEnable;
         GlobalControl |= GC_ShutDown;
         outl((uint16_t)(BusMasterAddress + NABM_GlobalControl), GlobalControl);
     }
References BusMasterAddress, GC_GlobalInterruptEnable, GC_ShutDown, inb(), inl(), NABM_GlobalControl, outb(), outl(), PCMOUT_TransferControl, TC_FifoERRORInterruptEnable, TC_IOCInterruptEnable, and TC_LastBufferEntryInterruptEnable.
Referenced by cxx_Panic().
write()
size_t AC97Device::write (uint8_t * Buffer, size_t Size) inline
Definition at line 370 of file ac97.cpp.
     {
         if (Buffer == nullptr)
         {
             KernelLog("Invalid buffer.");
             return -EINVAL;
         }
         if ((Size == 0) || (Size % (SampleSize * Channels)))
         {
             KernelLog("Invalid buffer length.");
             return -EINVAL;
         }
         int TotalBDLToFill = (int)((Size + PAGE_SIZE - 1) >> 12);
         while (Size > 0)
         {
             bool ActiveDMA = !(inw(BusMasterAddress + PCMOUT_Status) & TC_DMAControllerControl);
             if (ActiveDMA)
             {
                 int RemainingBDL = 0;
                 do
                 {
                     int CurrentBDL = inb(BusMasterAddress + PCMOUT_BufferDescriptorEntry);
                     int LastBDL = inb(BusMasterAddress + PCMOUT_DescriptorEntries);
                     RemainingBDL = LastBDL - CurrentBDL;
                     if (RemainingBDL < 0)
                         RemainingBDL += DescriptorListLength;
                     RemainingBDL += 1;
                     if (RemainingBDL >= DescriptorListLength - 1)
                     {
                         long SampleCount = DescriptorList[(CurrentBDL + 1) % DescriptorListLength].SampleCount / Channels;
                         if (SampleCount > 0)
                             Sleep(SampleCount * 1000 / SampleRate);
                     }
                 } while (RemainingBDL >= DescriptorListLength - 1 &&
                          !(inw(BusMasterAddress + PCMOUT_Status) & TC_DMAControllerControl));
             }
             uint8_t CurrentBDL = inb(BusMasterAddress + PCMOUT_BufferDescriptorEntry);
             uint8_t LastBDL = inb(BusMasterAddress + PCMOUT_DescriptorEntries);
             uint8_t NextBDL = LastBDL % DescriptorListLength;
             ActiveDMA = !(inw(BusMasterAddress + PCMOUT_Status) & TC_DMAControllerControl);
             if (ActiveDMA)
             {
                 NextBDL = (uint8_t)((LastBDL + 1) % DescriptorListLength);
                 if (NextBDL == CurrentBDL)
                     continue;
             }
             do
             {
                 size_t Wrote = (PAGE_SIZE > Size) ? size_t(Size)
                                                   : size_t(PAGE_SIZE);
                 if (Wrote == 0)
                 {
                     KernelLog("Wrote 0 bytes.");
                     break;
                 }
                 memcpy((void *)((uint64_t)DescriptorList[NextBDL].Address), Buffer, Wrote);
                 DescriptorList[NextBDL].Flags = 0;
                 Buffer += Wrote;
                 Size -= (unsigned int)Wrote;
                 DescriptorList[NextBDL].SampleCount = uint16_t(Wrote / SampleSize);
                 TotalBDLToFill--;
                 NextBDL = (uint8_t)((NextBDL + 1) % DescriptorListLength);
             } while (TotalBDLToFill-- && NextBDL != CurrentBDL);
             outb(BusMasterAddress + PCMOUT_DescriptorEntries, NextBDL - 1);
             ActiveDMA = !(inw(BusMasterAddress + PCMOUT_Status) & TC_DMAControllerControl);
             if (!ActiveDMA)
             {
                 // Start DMA
                 outb(BusMasterAddress + PCMOUT_TransferControl,
                      inb(BusMasterAddress + PCMOUT_TransferControl) | TC_DMAControllerControl);
             }
         }
         return Size;
     }
References Address, Buffer, BusMasterAddress, Channels, DescriptorList, DescriptorListLength, EINVAL, BufferDescriptorList::Flags, inb(), inw(), KernelLog(), memcpy, outb(), PAGE_SIZE, PCMOUT_BufferDescriptorEntry, PCMOUT_DescriptorEntries, PCMOUT_Status, PCMOUT_TransferControl, SampleCount, BufferDescriptorList::SampleCount, SampleRate, SampleSize, Driver::Size, Sleep(), and TC_DMAControllerControl.
Referenced by __fs_Write().
Field Documentation
BusMasterAddress
uint16_t AC97Device::BusMasterAddress private
Definition at line 360 of file ac97.cpp.
Referenced by AC97Device(), OnInterruptReceived(), Panic(), write(), and ~AC97Device().
Channels
char AC97Device::Channels = 2 private
Definition at line 363 of file ac97.cpp.
Referenced by write().
DescriptorList
BufferDescriptorList* AC97Device::DescriptorList = nullptr private
Definition at line 357 of file ac97.cpp.
Referenced by AC97Device(), and write().
Encoding
AudioEncodingValues AC97Device::Encoding = AE_PCMs16le private
Definition at line 362 of file ac97.cpp.
Header
PCIHeader0* AC97Device::Header private
Definition at line 356 of file ac97.cpp.
Referenced by AC97Device().
MixerAddress
uint16_t AC97Device::MixerAddress private
Definition at line 359 of file ac97.cpp.
Referenced by AC97Device(), OnInterruptReceived(), and ~AC97Device().
Mute
bool AC97Device::Mute = false private
Definition at line 365 of file ac97.cpp.
Referenced by AC97Device().
SampleRate
int AC97Device::SampleRate = 48000 private
Definition at line 366 of file ac97.cpp.
Referenced by write().
SampleSize
char AC97Device::SampleSize = 2 private
Definition at line 367 of file ac97.cpp.
Referenced by AC97Device(), and write().
Volume
uint8_t AC97Device::Volume = AV_Maximum private
Definition at line 364 of file ac97.cpp.
Referenced by AC97Device().
The documentation for this class was generated from the following file:
Drivers/audio/ac97/ac97.cpp