Fennix Userspace: Userspace/apps/base/bash/lib/glob/smatch.c File Reference
smatch.c File Reference
#include <config.h>
#include <stdio.h>
#include "strmatch.h"
#include <chartypes.h>
#include "bashansi.h"
#include "shmbutil.h"
#include "xmalloc.h"
#include <errno.h>
#include "collsyms.h"
#include "sm_loop.c"
Macros
#define CHAR unsigned char
#define U_CHAR unsigned char
#define XCHAR char
#define INT int
#define L(CS) CS
#define INVALID -1
#define STREQ(a, b) ((a)[0] == (b)[0] && strcmp(a, b) == 0)
#define STREQN(a, b, n) ((a)[0] == (b)[0] && strncmp(a, b, n) == 0)
#define GLOBASCII_DEFAULT 0
#define rangecmp(c1, c2, f) ((int)(c1) - (int)(c2))
#define collequiv(c, equiv) ((c) == (equiv))
#define _COLLSYM _collsym
#define __COLLSYM __collsym
#define POSIXCOLL posix_collsyms
#define isascii(c) ((unsigned int)(c) <= 0177)
#define N_CHAR_CLASS (sizeof(cclass_name) / sizeof (cclass_name[0]))
#define FOLD(c)
#define ISDIRSEP(c) ((c) == '/')
#define PATHSEP(c) (ISDIRSEP(c) || (c) == 0)
#define PDOT_OR_DOTDOT(s) (s[0] == '.' && (PATHSEP (s[1]) || (s[1] == '.' && PATHSEP (s[2]))))
#define SDOT_OR_DOTDOT(s) (s[0] == '.' && (s[1] == 0 || (s[1] == '.' && s[2] == 0)))
#define FCT internal_strmatch
#define GMATCH gmatch
#define COLLSYM collsym
#define PARSE_COLLSYM parse_collsym
#define BRACKMATCH brackmatch
#define PATSCAN glob_patscan
#define STRCOMPARE strcompare
#define EXTMATCH extmatch
#define DEQUOTE_PATHNAME udequote_pathname
#define STRUCT smat_struct
#define STRCHR(S, C) strchr((S), (C))
#define MEMCHR(S, C, N) memchr((S), (C), (N))
#define STRCOLL(S1, S2) strcoll((S1), (S2))
#define STRLEN(S) strlen(S)
#define STRCMP(S1, S2) strcmp((S1), (S2))
#define RANGECMP(C1, C2, F) rangecmp((C1), (C2), (F))
#define COLLEQUIV(C1, C2) collequiv((C1), (C2))
#define CTYPE_T enum char_class
#define IS_CCLASS(C, S) is_cclass((C), (S))
Enumerations
enum char_class {
CC_NO_CLASS = 0 , CC_ASCII , CC_ALNUM , CC_ALPHA ,
CC_BLANK , CC_CNTRL , CC_DIGIT , CC_GRAPH ,
CC_LOWER , CC_PRINT , CC_PUNCT , CC_SPACE ,
CC_UPPER , CC_WORD , CC_XDIGIT
}
Functions
static int collsym (CHAR *s, int len)
static enum char_class is_valid_cclass (char *name) const
static int cclass_test (int c, enum char_class char_class)
static int is_cclass (int c, const char *name)
int xstrmatch (char *pattern, char *string, int flags)
Variables
int errno
int glob_asciirange = GLOBASCII_DEFAULT
static char const *const cclass_name []
Macro Definition Documentation
__COLLSYM
#define __COLLSYM __collsym
Definition at line 165 of file smatch.c.
_COLLSYM
#define _COLLSYM _collsym
Definition at line 164 of file smatch.c.
BRACKMATCH
#define BRACKMATCH brackmatch
Definition at line 325 of file smatch.c.
CHAR
#define CHAR unsigned char
Definition at line 46 of file smatch.c.
collequiv
#define collequiv (c, equiv) ((c) == (equiv))
Definition at line 161 of file smatch.c.
COLLEQUIV
#define COLLEQUIV (C1, C2) collequiv((C1), (C2))
Definition at line 337 of file smatch.c.
COLLSYM
#define COLLSYM collsym
Definition at line 323 of file smatch.c.
CTYPE_T
#define CTYPE_T enum char_class
Definition at line 338 of file smatch.c.
DEQUOTE_PATHNAME
#define DEQUOTE_PATHNAME udequote_pathname
Definition at line 329 of file smatch.c.
EXTMATCH
#define EXTMATCH extmatch
Definition at line 328 of file smatch.c.
FCT
#define FCT internal_strmatch
Definition at line 321 of file smatch.c.
FOLD
#define FOLD (c)
Value:
    ((flags & FNM_CASEFOLD) \
    ? TOLOWER ((unsigned char)c) \
    : ((unsigned char)c))
Definition at line 307 of file smatch.c.
GLOBASCII_DEFAULT
#define GLOBASCII_DEFAULT 0
Definition at line 59 of file smatch.c.
GMATCH
#define GMATCH gmatch
Definition at line 322 of file smatch.c.
INT
#define INT int
Definition at line 49 of file smatch.c.
INVALID
#define INVALID -1
Definition at line 51 of file smatch.c.
IS_CCLASS
#define IS_CCLASS (C, S) is_cclass((C), (S))
Definition at line 339 of file smatch.c.
isascii
#define isascii (c) ((unsigned int)(c) <= 0177)
Definition at line 190 of file smatch.c.
ISDIRSEP
#define ISDIRSEP (c) ((c) == '/')
Definition at line 312 of file smatch.c.
L
#define L (CS) CS
Definition at line 50 of file smatch.c.
MEMCHR
#define MEMCHR (S, C, N) memchr((S), (C), (N))
Definition at line 332 of file smatch.c.
N_CHAR_CLASS
#define N_CHAR_CLASS (sizeof(cclass_name) / sizeof (cclass_name[0]))
Definition at line 207 of file smatch.c.
PARSE_COLLSYM
#define PARSE_COLLSYM parse_collsym
Definition at line 324 of file smatch.c.
PATHSEP
#define PATHSEP (c) (ISDIRSEP(c) || (c) == 0)
Definition at line 316 of file smatch.c.
PATSCAN
#define PATSCAN glob_patscan
Definition at line 326 of file smatch.c.
PDOT_OR_DOTDOT
#define PDOT_OR_DOTDOT (s) (s[0] == '.' && (PATHSEP (s[1]) || (s[1] == '.' && PATHSEP (s[2]))))
Definition at line 318 of file smatch.c.
POSIXCOLL
#define POSIXCOLL posix_collsyms
Definition at line 166 of file smatch.c.
rangecmp
#define rangecmp (c1, c2, f) ((int)(c1) - (int)(c2))
Definition at line 141 of file smatch.c.
RANGECMP
#define RANGECMP (C1, C2, F) rangecmp((C1), (C2), (F))
Definition at line 336 of file smatch.c.
SDOT_OR_DOTDOT
#define SDOT_OR_DOTDOT (s) (s[0] == '.' && (s[1] == 0 || (s[1] == '.' && s[2] == 0)))
Definition at line 319 of file smatch.c.
STRCHR
#define STRCHR (S, C) strchr((S), (C))
Definition at line 331 of file smatch.c.
STRCMP
#define STRCMP (S1, S2) strcmp((S1), (S2))
Definition at line 335 of file smatch.c.
STRCOLL
#define STRCOLL (S1, S2) strcoll((S1), (S2))
Definition at line 333 of file smatch.c.
STRCOMPARE
#define STRCOMPARE strcompare
Definition at line 327 of file smatch.c.
STREQ
#define STREQ (a, b) ((a)[0] == (b)[0] && strcmp(a, b) == 0)
Definition at line 55 of file smatch.c.
STREQN
#define STREQN (a, b, n) ((a)[0] == (b)[0] && strncmp(a, b, n) == 0)
Definition at line 56 of file smatch.c.
STRLEN
#define STRLEN (S) strlen(S)
Definition at line 334 of file smatch.c.
STRUCT
#define STRUCT smat_struct
Definition at line 330 of file smatch.c.
U_CHAR
#define U_CHAR unsigned char
Definition at line 47 of file smatch.c.
XCHAR
#define XCHAR char
Definition at line 48 of file smatch.c.
Enumeration Type Documentation
char_class
enum char_class
Enumerator
CC_NO_CLASS
CC_ASCII
CC_ALNUM
CC_ALPHA
CC_BLANK
CC_CNTRL
CC_DIGIT
CC_GRAPH
CC_LOWER
CC_PRINT
CC_PUNCT
CC_SPACE
CC_UPPER
CC_WORD
CC_XDIGIT
Definition at line 193 of file smatch.c.
   {
     CC_NO_CLASS = 0,
     CC_ASCII, CC_ALNUM, CC_ALPHA, CC_BLANK, CC_CNTRL, CC_DIGIT, CC_GRAPH,
     CC_LOWER, CC_PRINT, CC_PUNCT, CC_SPACE, CC_UPPER, CC_WORD, CC_XDIGIT
   };
Function Documentation
cclass_test()
static int cclass_test (int c, enum char_class char_class) static
Definition at line 231 of file smatch.c.
 {
   int result;
   switch (char_class)
     {
       case CC_ASCII:
     result = isascii (c);
     break;
       case CC_ALNUM:
     result = ISALNUM (c);
     break;
       case CC_ALPHA:
     result = ISALPHA (c);
     break;
       case CC_BLANK:
     result = ISBLANK (c);
     break;
       case CC_CNTRL:
     result = ISCNTRL (c);
     break;
       case CC_DIGIT:
     result = ISDIGIT (c);
     break;
       case CC_GRAPH:
     result = ISGRAPH (c);
     break;
       case CC_LOWER:
     result = ISLOWER (c);
     break;
       case CC_PRINT:
     result = ISPRINT (c);
     break;
       case CC_PUNCT:
     result = ISPUNCT (c);
     break;
       case CC_SPACE:
     result = ISSPACE (c);
     break;
       case CC_UPPER:
     result = ISUPPER (c);
     break;
       case CC_WORD:
         result = (ISALNUM (c) || c == '_');
     break;
       case CC_XDIGIT:
     result = ISXDIGIT (c);
     break;
       default:
     result = -1;
     break;
     }
   return result;
 }
References c, CC_ALNUM, CC_ALPHA, CC_ASCII, CC_BLANK, CC_CNTRL, CC_DIGIT, CC_GRAPH, CC_LOWER, CC_PRINT, CC_PUNCT, CC_SPACE, CC_UPPER, CC_WORD, CC_XDIGIT, ISALNUM, ISALPHA, isascii, ISBLANK, ISCNTRL, ISDIGIT, ISGRAPH, ISLOWER, ISPRINT, ISPUNCT, ISSPACE, ISUPPER, and ISXDIGIT.
Referenced by is_cclass().
collsym()
static int collsym (CHAR * s, int len) static
Definition at line 170 of file smatch.c.
 {
   register struct _collsym *csp;
   char *x;
   x = (char *)s;
   for (csp = posix_collsyms; csp->name; csp++)
     {
       if (STREQN(csp->name, x, len) && csp->name[len] == '\0')
     return (csp->code);
     }
   if (len == 1)
     return s[0];
   return INVALID;
 }
References INVALID, STREQN, and x.
Referenced by quote_string_for_globbing().
is_cclass()
static int is_cclass (int c, const char * name) static
Definition at line 290 of file smatch.c.
 {
   enum char_class char_class;
   int result;
   char_class = is_valid_cclass (name);
   if (char_class == CC_NO_CLASS)
     return -1;
   result = cclass_test (c, char_class);
   return (result);
 }
References c, CC_NO_CLASS, cclass_test(), is_valid_cclass(), and name.
is_valid_cclass()
static enum char_class is_valid_cclass (char * name) const static
Definition at line 200 of file smatch.c.
 {
   enum char_class ret;
   int i;
   ret = CC_NO_CLASS;
   for (i = 1; i < N_CHAR_CLASS; i++)
     {
       if (STREQ (name, cclass_name[i]))
     {
       ret = (enum char_class)i;
       break;
     }
     }
   return ret;
 }
Referenced by is_cclass().
xstrmatch()
int xstrmatch (char * pattern, char * string, int flags)
Definition at line 601 of file smatch.c.
 {
 #if HANDLE_MULTIBYTE
   int ret;
   size_t n;
   wchar_t *wpattern, *wstring;
   size_t plen, slen, mplen, mslen;
   if (MB_CUR_MAX == 1)
     return (internal_strmatch ((unsigned char *)pattern, (unsigned char *)string, flags));
   if (mbsmbchar (string) == 0 && mbsmbchar (pattern) == 0 && posix_cclass_only (pattern))
     return (internal_strmatch ((unsigned char *)pattern, (unsigned char *)string, flags));
   n = xdupmbstowcs (&wpattern, NULL, pattern);
   if (n == (size_t)-1 || n == (size_t)-2)
     return (internal_strmatch ((unsigned char *)pattern, (unsigned char *)string, flags));
   n = xdupmbstowcs (&wstring, NULL, string);
   if (n == (size_t)-1 || n == (size_t)-2)
     {
       free (wpattern);
       return (internal_strmatch ((unsigned char *)pattern, (unsigned char *)string, flags));
     }
   ret = internal_wstrmatch (wpattern, wstring, flags);
   free (wpattern);
   free (wstring);
   return ret;
 #else
   return (internal_strmatch ((unsigned char *)pattern, (unsigned char *)string, flags));
 #endif /* !HANDLE_MULTIBYTE */
 }
References flags, free, MB_CUR_MAX, n, NULL, pattern, and ret.
Referenced by strmatch().
Variable Documentation
cclass_name
char const* const cclass_name[] static
Initial value:
=
  {
    "",
    "ascii", "alnum", "alpha", "blank", "cntrl", "digit", "graph",
    "lower", "print", "punct", "space", "upper", "word", "xdigit"
  }
Definition at line 200 of file smatch.c.
errno
int errno extern
glob_asciirange
int glob_asciirange = GLOBASCII_DEFAULT
Definition at line 62 of file smatch.c.