Fennix: Userspace/apps/base/bash/lib/readline/callback.c File Reference
callback.c File Reference
#include "rlconf.h"
#include <sys/types.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "readline.h"
#include "rlprivate.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define CALLBACK_READ_RETURN()
Functions
static void _rl_callback_newline (void)
void rl_callback_handler_install (const char *prompt, rl_vcpfunc_t *linefunc)
void rl_callback_read_char (void)
void rl_callback_handler_remove (void)
_rl_callback_generic_arg * _rl_callback_data_alloc (int count)
void _rl_callback_data_dispose (_rl_callback_generic_arg *arg)
void rl_callback_sigcleanup (void)
Variables
_rl_callback_func_t * _rl_callback_func = 0
_rl_callback_generic_arg * _rl_callback_data = 0
int rl_persistent_signal_handlers = 0
rl_vcpfunc_t * rl_linefunc
static int in_handler
Macro Definition Documentation
CALLBACK_READ_RETURN
#define CALLBACK_READ_RETURN ()
Value:
  do { \
    if (rl_persistent_signal_handlers == 0) \
      rl_clear_signals (); \
    return; \
  } while (0)
Definition at line 115 of file callback.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file callback.c.
Function Documentation
_rl_callback_data_alloc()
_rl_callback_generic_arg* _rl_callback_data_alloc (int count)
Definition at line 335 of file callback.c.
 {
   _rl_callback_generic_arg *arg;
   arg = (_rl_callback_generic_arg *)xmalloc (sizeof (_rl_callback_generic_arg));
   arg->count = count;
   arg->i1 = arg->i2 = 0;
   return arg;
 }
References count, and xmalloc.
Referenced by rl_backward_char_search(), rl_char_search(), rl_quoted_insert(), rl_vi_change_char(), and rl_vi_char_search().
_rl_callback_data_dispose()
void _rl_callback_data_dispose (_rl_callback_generic_arg * arg)
Definition at line 348 of file callback.c.
 {
   xfree (arg);
 }
References xfree.
Referenced by rl_callback_read_char().
_rl_callback_newline()
static void _rl_callback_newline (void) static
Definition at line 83 of file callback.c.
 {
   rl_initialize ();
   if (in_handler == 0)
     {
       in_handler = 1;
       if (rl_prep_term_function)
     (*rl_prep_term_function) (_rl_meta_flag);
 #if defined (HANDLE_SIGNALS)
       if (rl_persistent_signal_handlers)
     rl_set_signals ();
 #endif
     }
   readline_internal_setup ();
   RL_CHECK_SIGNALS ();
 }
References _rl_meta_flag, in_handler, readline_internal_setup(), RL_CHECK_SIGNALS, rl_initialize(), rl_persistent_signal_handlers, rl_prep_term_function, and rl_set_signals().
Referenced by rl_callback_handler_install(), and rl_callback_read_char().
rl_callback_handler_install()
void rl_callback_handler_install (const char * prompt, rl_vcpfunc_t * linefunc)
Definition at line 106 of file callback.c.
 {
   rl_set_prompt (prompt);
   RL_SETSTATE (RL_STATE_CALLBACK);
   rl_linefunc = linefunc;
   _rl_callback_newline ();
 }
References _rl_callback_newline(), prompt, rl_linefunc, rl_set_prompt(), RL_SETSTATE, and RL_STATE_CALLBACK.
Referenced by change_prompt(), and main().
rl_callback_handler_remove()
void rl_callback_handler_remove (void)
Definition at line 318 of file callback.c.
 {
   rl_linefunc = NULL;
   RL_UNSETSTATE (RL_STATE_CALLBACK);
   RL_CHECK_SIGNALS ();
   if (in_handler)
     {
       in_handler = 0;
       if (rl_deprep_term_function)
     (*rl_deprep_term_function) ();
 #if defined (HANDLE_SIGNALS)
       rl_clear_signals ();
 #endif
     }
 }
References in_handler, NULL, RL_CHECK_SIGNALS, rl_clear_signals(), rl_deprep_term_function, rl_linefunc, RL_STATE_CALLBACK, and RL_UNSETSTATE.
Referenced by cb_linehandler(), and main().
rl_callback_read_char()
void rl_callback_read_char (void)
Definition at line 127 of file callback.c.
 {
   char *line;
   int eof, jcode;
   static procenv_t olevel;
   if (rl_linefunc == NULL)
     {
       _rl_errmsg ("readline_callback_read_char() called with no handler!");
       abort ();
     }
   eof = 0;
   memcpy ((void *)olevel, (void *)_rl_top_level, sizeof (procenv_t));
 #if defined (HAVE_POSIX_SIGSETJMP)
   jcode = sigsetjmp (_rl_top_level, 0);
 #else
   jcode = setjmp (_rl_top_level);
 #endif
   if (jcode)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
       memcpy ((void *)_rl_top_level, (void *)olevel, sizeof (procenv_t));
       /* If we longjmped because of a timeout, handle it here. */
       if (RL_ISSTATE (RL_STATE_TIMEOUT))
     {
       RL_SETSTATE (RL_STATE_DONE);
       rl_done = 1;
     }
       CALLBACK_READ_RETURN ();
     }
 #if defined (HANDLE_SIGNALS)
   /* Install signal handlers only when readline has control. */
   if (rl_persistent_signal_handlers == 0)
     rl_set_signals ();
 #endif
   do
     {
       RL_CHECK_SIGNALS ();
       if  (RL_ISSTATE (RL_STATE_ISEARCH))
     {
       eof = _rl_isearch_callback (_rl_iscxt);
       if (eof == 0 && (RL_ISSTATE (RL_STATE_ISEARCH) == 0) && RL_ISSTATE (RL_STATE_INPUTPENDING))
         rl_callback_read_char ();
       CALLBACK_READ_RETURN ();
     }
       else if  (RL_ISSTATE (RL_STATE_NSEARCH))
     {
       eof = _rl_nsearch_callback (_rl_nscxt);
       CALLBACK_READ_RETURN ();
     }
 #if defined (VI_MODE)
       /* States that can occur while in state VIMOTION have to be checked
      before RL_STATE_VIMOTION */
       else if (RL_ISSTATE (RL_STATE_CHARSEARCH))
     {
       int k;
       k = _rl_callback_data->i2;
       eof = (*_rl_callback_func) (_rl_callback_data);
       /* If the function `deregisters' itself, make sure the data is
          cleaned up. */
       if (_rl_callback_func == 0)   /* XXX - just sanity check */
         {
           if (_rl_callback_data)
         {
           _rl_callback_data_dispose (_rl_callback_data);
           _rl_callback_data = 0;
         }
         }
       /* Messy case where vi motion command can be char search */
       if (RL_ISSTATE (RL_STATE_VIMOTION))
         {
           _rl_vi_domove_motion_cleanup (k, _rl_vimvcxt);
           _rl_internal_char_cleanup ();
           CALLBACK_READ_RETURN ();
         }
       _rl_internal_char_cleanup ();
     }
       else if (RL_ISSTATE (RL_STATE_VIMOTION))
     {
       eof = _rl_vi_domove_callback (_rl_vimvcxt);
       /* Should handle everything, including cleanup, numeric arguments,
          and turning off RL_STATE_VIMOTION */
       if (RL_ISSTATE (RL_STATE_NUMERICARG) == 0)
         _rl_internal_char_cleanup ();
       CALLBACK_READ_RETURN ();
     }
 #endif
       else if (RL_ISSTATE (RL_STATE_NUMERICARG))
     {
       eof = _rl_arg_callback (_rl_argcxt);
       if (eof == 0 && (RL_ISSTATE (RL_STATE_NUMERICARG) == 0) && RL_ISSTATE (RL_STATE_INPUTPENDING))
         rl_callback_read_char ();
       /* XXX - this should handle _rl_last_command_was_kill better */
       else if (RL_ISSTATE (RL_STATE_NUMERICARG) == 0)
         _rl_internal_char_cleanup ();
       CALLBACK_READ_RETURN ();
     }
       else if (RL_ISSTATE (RL_STATE_MULTIKEY))
     {
       eof = _rl_dispatch_callback (_rl_kscxt);  /* For now */
       while ((eof == -1 || eof == -2) && RL_ISSTATE (RL_STATE_MULTIKEY) && _rl_kscxt && (_rl_kscxt->flags & KSEQ_DISPATCHED))
         eof = _rl_dispatch_callback (_rl_kscxt);
       if (RL_ISSTATE (RL_STATE_MULTIKEY) == 0)
         {
           _rl_internal_char_cleanup ();
           _rl_want_redisplay = 1;
         }
     }
       else if (_rl_callback_func)
     {
       /* This allows functions that simply need to read an additional
          character (like quoted-insert) to register a function to be
          called when input is available.  _rl_callback_data is a
          pointer to a struct that has the argument count originally
          passed to the registering function and space for any additional
          parameters.  */
       eof = (*_rl_callback_func) (_rl_callback_data);
       /* If the function `deregisters' itself, make sure the data is
          cleaned up. */
       if (_rl_callback_func == 0)
         {
           if (_rl_callback_data)
         {
           _rl_callback_data_dispose (_rl_callback_data);
           _rl_callback_data = 0;
         }
           _rl_internal_char_cleanup ();
         }
     }
       else
     eof = readline_internal_char ();
       RL_CHECK_SIGNALS ();
       if (rl_done == 0 && _rl_want_redisplay)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
     }
       /* Make sure application hooks can see whether we saw EOF. */
       if (eof > 0)
     {
       rl_eof_found = eof;
       RL_SETSTATE(RL_STATE_EOF);
     }
       if (rl_done)
     {
       line = readline_internal_teardown (eof);
       if (rl_deprep_term_function)
         (*rl_deprep_term_function) ();
 #if defined (HANDLE_SIGNALS)
       rl_clear_signals ();
 #endif
       in_handler = 0;
       if (rl_linefunc)          /* just in case */
         (*rl_linefunc) (line);
       /* If the user did not clear out the line, do it for him. */
       if (rl_line_buffer[0])
         _rl_init_line_state ();
       /* Redisplay the prompt if readline_handler_{install,remove}
          not called. */
       if (in_handler == 0 && rl_linefunc)
         _rl_callback_newline ();
     }
     }
   while (rl_pending_input || _rl_pushed_input_available () || RL_ISSTATE (RL_STATE_MACROINPUT));
   CALLBACK_READ_RETURN ();
 }
References _rl_arg_callback(), _rl_argcxt, _rl_callback_data, _rl_callback_data_dispose(), _rl_callback_func, _rl_callback_newline(), _rl_dispatch_callback(), _rl_errmsg(), _rl_init_line_state(), _rl_internal_char_cleanup(), _rl_iscxt, _rl_isearch_callback(), _rl_kscxt, _rl_nscxt, _rl_nsearch_callback(), _rl_pushed_input_available(), _rl_top_level, _rl_vi_domove_callback(), _rl_vi_domove_motion_cleanup(), _rl_vimvcxt, _rl_want_redisplay, abort(), CALLBACK_READ_RETURN, __rl_keyseq_context::flags, __rl_callback_generic_arg::i2, in_handler, k, KSEQ_DISPATCHED, line, memcpy, NULL, procenv_t, readline_internal_char(), readline_internal_teardown(), RL_CHECK_SIGNALS, rl_clear_signals(), rl_deprep_term_function, rl_done, rl_eof_found, RL_ISSTATE, rl_line_buffer, rl_linefunc, rl_pending_input, rl_persistent_signal_handlers, rl_set_signals(), RL_SETSTATE, RL_STATE_CHARSEARCH, RL_STATE_DONE, RL_STATE_EOF, RL_STATE_INPUTPENDING, RL_STATE_ISEARCH, RL_STATE_MACROINPUT, RL_STATE_MULTIKEY, RL_STATE_NSEARCH, RL_STATE_NUMERICARG, RL_STATE_TIMEOUT, RL_STATE_VIMOTION, and setjmp.
Referenced by main().
rl_callback_sigcleanup()
void rl_callback_sigcleanup (void)
Definition at line 355 of file callback.c.
 {
   if (RL_ISSTATE (RL_STATE_CALLBACK) == 0)
     return;
   if (RL_ISSTATE (RL_STATE_ISEARCH))
     _rl_isearch_cleanup (_rl_iscxt, 0);
   else if (RL_ISSTATE (RL_STATE_NSEARCH))
     _rl_nsearch_cleanup (_rl_nscxt, 0);
   else if (RL_ISSTATE (RL_STATE_VIMOTION))
     RL_UNSETSTATE (RL_STATE_VIMOTION);
   else if (RL_ISSTATE (RL_STATE_NUMERICARG))
     {
       _rl_argcxt = 0;
       RL_UNSETSTATE (RL_STATE_NUMERICARG);
     }
   else if (RL_ISSTATE (RL_STATE_MULTIKEY))
     RL_UNSETSTATE (RL_STATE_MULTIKEY);
   if (RL_ISSTATE (RL_STATE_CHARSEARCH))
     RL_UNSETSTATE (RL_STATE_CHARSEARCH);
   _rl_callback_func = 0;
 }
References _rl_argcxt, _rl_callback_func, _rl_iscxt, _rl_isearch_cleanup(), _rl_nscxt, _rl_nsearch_cleanup(), RL_ISSTATE, RL_STATE_CALLBACK, RL_STATE_CHARSEARCH, RL_STATE_ISEARCH, RL_STATE_MULTIKEY, RL_STATE_NSEARCH, RL_STATE_NUMERICARG, RL_STATE_VIMOTION, and RL_UNSETSTATE.
Referenced by _rl_handle_signal().
Variable Documentation
_rl_callback_data
_rl_callback_generic_arg* _rl_callback_data = 0
Definition at line 51 of file callback.c.
Referenced by rl_backward_char_search(), rl_callback_read_char(), rl_char_search(), rl_quoted_insert(), rl_vi_change_char(), rl_vi_char_search(), rl_vi_goto_mark(), and rl_vi_set_mark().
_rl_callback_func
_rl_callback_func_t* _rl_callback_func = 0
Definition at line 50 of file callback.c.
Referenced by _rl_char_search_callback(), _rl_insert_next_callback(), _rl_vi_callback_change_char(), _rl_vi_callback_char_search(), _rl_vi_callback_goto_mark(), _rl_vi_callback_set_mark(), rl_backward_char_search(), rl_callback_read_char(), rl_callback_sigcleanup(), rl_char_search(), rl_quoted_insert(), rl_vi_change_char(), rl_vi_char_search(), rl_vi_goto_mark(), and rl_vi_set_mark().
in_handler
int in_handler static
Definition at line 79 of file callback.c.
Referenced by _rl_callback_newline(), rl_callback_handler_remove(), and rl_callback_read_char().
rl_linefunc
rl_vcpfunc_t* rl_linefunc
Definition at line 78 of file callback.c.
Referenced by rl_callback_handler_install(), rl_callback_handler_remove(), and rl_callback_read_char().
rl_persistent_signal_handlers
int rl_persistent_signal_handlers = 0
Definition at line 59 of file callback.c.
Referenced by _rl_callback_newline(), and rl_callback_read_char().