Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/d_iwad.h File Reference
d_iwad.h File Reference
#include "d_mode.h"
Data Structures
struct iwad_t
Macros
#define IWAD_MASK_DOOM
#define IWAD_MASK_HERETIC (1 << heretic)
#define IWAD_MASK_HEXEN (1 << hexen)
#define IWAD_MASK_STRIFE (1 << strife)
Functions
char * D_FindWADByName (char *filename)
char * D_TryFindWADByName (char *filename)
char * D_FindIWAD (int mask, GameMission_t *mission)
const iwad_t ** D_FindAllIWADs (int mask)
char * D_SaveGameIWADName (GameMission_t gamemission)
char * D_SuggestIWADName (GameMission_t mission, GameMode_t mode)
char * D_SuggestGameName (GameMission_t mission, GameMode_t mode)
void D_CheckCorrectIWAD (GameMission_t mission)
Data Structure Documentation
iwad_t
struct iwad_t
Definition at line 34 of file d_iwad.h.
Data Fields
char * description
GameMission_t mission
GameMode_t mode
char * name
Macro Definition Documentation
IWAD_MASK_DOOM
#define IWAD_MASK_DOOM
Value:
                         ((1 << doom)           \
                         | (1 << doom2)          \
                         | (1 << pack_tnt)       \
                         | (1 << pack_plut)      \
                         | (1 << pack_chex)      \
                         | (1 << pack_hacx))
Definition at line 24 of file d_iwad.h.
IWAD_MASK_HERETIC
#define IWAD_MASK_HERETIC (1 << heretic)
Definition at line 30 of file d_iwad.h.
IWAD_MASK_HEXEN
#define IWAD_MASK_HEXEN (1 << hexen)
Definition at line 31 of file d_iwad.h.
IWAD_MASK_STRIFE
#define IWAD_MASK_STRIFE (1 << strife)
Definition at line 32 of file d_iwad.h.
Function Documentation
D_CheckCorrectIWAD()
void D_CheckCorrectIWAD (GameMission_t mission)
D_FindAllIWADs()
const iwad_t** D_FindAllIWADs (int mask)
Definition at line 755 of file d_iwad.c.
 {
     const iwad_t **result;
     int result_len;
     char *filename;
     int i;
     result = malloc(sizeof(iwad_t *) * (arrlen(iwads) + 1));
     result_len = 0;
     // Try to find all IWADs
     for (i=0; i<arrlen(iwads); ++i)
     {
         if (((1 << iwads[i].mission) & mask) == 0)
         {
             continue;
         }
         filename = D_FindWADByName(iwads[i].name);
         if (filename != NULL)
         {
             result[result_len] = &iwads[i];
             ++result_len;
         }
     }
     // End of list
     result[result_len] = NULL;
     return result;
 }
References arrlen, D_FindWADByName(), i, iwads, malloc(), name, NULL, and mlibc::result.
D_FindIWAD()
char* D_FindIWAD (int mask, GameMission_t * mission)
Definition at line 702 of file d_iwad.c.
 {
     char *result;
     char *iwadfile;
     int iwadparm;
     int i;
     // Check for the -iwad parameter
     // Specify an IWAD file to use.
     //
     // @arg <file>
     //
     iwadparm = M_CheckParmWithArgs("-iwad", 1);
     if (iwadparm)
     {
         // Search through IWAD dirs for an IWAD with the given name.
         iwadfile = myargv[iwadparm + 1];
         result = D_FindWADByName(iwadfile);
         if (result == NULL)
         {
             I_Error("IWAD file '%s' not found!", iwadfile);
         }
         *mission = IdentifyIWADByName(result, mask);
     }
     else
     {
         // Search through the list and look for an IWAD
         printf("-iwad not specified, trying a few iwad names\n");
         result = NULL;
         BuildIWADDirList();
         for (i=0; result == NULL && i<num_iwad_dirs; ++i)
         {
             result = SearchDirectoryForIWAD(iwad_dirs[i], mask, mission);
         }
     }
     return result;
 }
References BuildIWADDirList(), D_FindWADByName(), i, I_Error(), IdentifyIWADByName(), iwad_dirs, iwadfile, M_CheckParmWithArgs(), myargv, NULL, num_iwad_dirs, printf, mlibc::result, and SearchDirectoryForIWAD().
Referenced by D_DoomMain().
D_FindWADByName()
char* D_FindWADByName (char * filename)
Definition at line 628 of file d_iwad.c.
 {
     char *path;
     int i;
     // Absolute path?
     if (M_FileExists(name))
     {
         return name;
     }
     BuildIWADDirList();
     // Search through all IWAD paths for a file with the given name.
     for (i=0; i<num_iwad_dirs; ++i)
     {
         // As a special case, if this is in DOOMWADDIR or DOOMWADPATH,
         // the "directory" may actually refer directly to an IWAD
         // file.
         if (DirIsFile(iwad_dirs[i], name) && M_FileExists(iwad_dirs[i]))
         {
             return strdup(iwad_dirs[i]);
         }
         // Construct a string for the full path
         path = M_StringJoin(iwad_dirs[i], DIR_SEPARATOR_S, name, NULL);
         if (M_FileExists(path))
         {
             return path;
         }
         free(path);
     }
     // File not found
     return NULL;
 }
References BuildIWADDirList(), DIR_SEPARATOR_S, DirIsFile(), free(), i, iwad_dirs, M_FileExists(), M_StringJoin(), name, NULL, num_iwad_dirs, and strdup().
Referenced by D_FindAllIWADs(), D_FindIWAD(), and D_TryFindWADByName().
D_SaveGameIWADName()
char* D_SaveGameIWADName (GameMission_t gamemission)
Definition at line 794 of file d_iwad.c.
 {
     size_t i;
     // Determine the IWAD name to use for savegames.
     // This determines the directory the savegame files get put into.
     //
     // Note that we match on gamemission rather than on IWAD name.
     // This ensures that doom1.wad and doom.wad saves are stored
     // in the same place.
     for (i=0; i<arrlen(iwads); ++i)
     {
         if (gamemission == iwads[i].mission)
         {
             return iwads[i].name;
         }
     }
     // Default fallback:
     return "unknown.wad";
 }
References arrlen, gamemission, i, iwads, and iwad_t::name.
Referenced by D_DoomMain().
D_SuggestGameName()
char* D_SuggestGameName (GameMission_t mission, GameMode_t mode)
Definition at line 833 of file d_iwad.c.
 {
     int i;
     for (i = 0; i < arrlen(iwads); ++i)
     {
         if (iwads[i].mission == mission
          && (mode == indetermined || iwads[i].mode == mode))
         {
             return iwads[i].description;
         }
     }
     return "Unknown game?";
 }
References arrlen, iwad_t::description, i, indetermined, and iwads.
Referenced by W_CheckCorrectIWAD().
D_SuggestIWADName()
char* D_SuggestIWADName (GameMission_t mission, GameMode_t mode)
Definition at line 818 of file d_iwad.c.
 {
     int i;
     for (i = 0; i < arrlen(iwads); ++i)
     {
         if (iwads[i].mission == mission && iwads[i].mode == mode)
         {
             return iwads[i].name;
         }
     }
     return "unknown.wad";
 }
References arrlen, i, iwads, and iwad_t::name.
D_TryFindWADByName()
char* D_TryFindWADByName (char * filename)
Definition at line 679 of file d_iwad.c.
 {
     char *result;
     result = D_FindWADByName(filename);
     if (result != NULL)
     {
         return result;
     }
     else
     {
         return filename;
     }
 }
References D_FindWADByName(), NULL, and mlibc::result.
Referenced by W_ParseCommandLine().