Fennix: Userspace/musl/include/grp.h File Reference
grp.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct group
Macros
#define __NEED_size_t
#define __NEED_gid_t
Functions
struct group * getgrgid (gid_t)
struct group * getgrnam (const char *)
int getgrgid_r (gid_t, struct group *, char *, size_t, struct group **)
int getgrnam_r (const char *, struct group *, char *, size_t, struct group **)
Data Structure Documentation
group
struct group
Definition at line 12 of file grp.h.
Data Fields
unsigned char active_idx:5
gid_t gr_gid
char ** gr_mem
char * gr_name
char * gr_passwd
struct meta * meta
char pad[UNIT - sizeof(struct meta *) - 1]
unsigned char storage[]
Macro Definition Documentation
__NEED_gid_t
#define __NEED_gid_t
Definition at line 11 of file grp.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file grp.h.
Function Documentation
getgrgid()
struct group* getgrgid (gid_t gid)
Definition at line 213 of file grp-stubs.cpp.
{
     static group entry;
     int err = walk_file(&entry, [&] (group *entry) {
         return entry->gr_gid == gid;
     });
     if (err) {
         errno = err;
         return nullptr;
     }
     return &entry;
 }
References __getgr_a(), err(), errno, gr, line, mem, size, and anonymous_namespace{grp-stubs.cpp}::walk_file().
getgrgid_r()
int getgrgid_r (gid_t gid, struct group * grp, char * buffer, size_t size, struct group ** result)
Definition at line 228 of file grp-stubs.cpp.
{
     *result = nullptr;
     int err = walk_file(grp, [&] (group *entry) {
         return entry->gr_gid == gid;
     });
     if (err) {
         return err;
     }
     err = copy_to_buffer(grp, buffer, size);
     if (err) {
         return err;
     }
     *result = grp;
     return 0;
 }
References buf, anonymous_namespace{grp-stubs.cpp}::copy_to_buffer(), err(), getgr_r(), gr, size, and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().
getgrnam()
struct group* getgrnam (const char * name)
Definition at line 247 of file grp-stubs.cpp.
{
     static group entry;
     int err = walk_file(&entry, [&] (group *entry) {
         return !strcmp(entry->gr_name, name);
     });
     if (err) {
         errno = err;
         return nullptr;
     }
     return &entry;
 }
References __getgr_a(), err(), errno, gr, line, mem, name, size, strcmp, and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().
getgrnam_r()
int getgrnam_r (const char * name, struct group * grp, char * buffer, size_t size, struct group ** result)
Definition at line 262 of file grp-stubs.cpp.
{
     *result = nullptr;
     int err = walk_file(grp, [&] (group *entry) {
         return !strcmp(entry->gr_name, name);
     });
     if (err) {
         return err;
     }
     err = copy_to_buffer(grp, buffer, size);
     if (err) {
         return err;
     }
     *result = grp;
     return 0;
 }
References buf, anonymous_namespace{grp-stubs.cpp}::copy_to_buffer(), err(), getgr_r(), gr, name, size, strcmp, and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().