Fennix Userspace: Userspace/musl/include/sys/resource.h File Reference
resource.h File Reference
#include <features.h>
#include <sys/time.h>
#include <bits/alltypes.h>
#include <bits/resource.h>
Data Structures
struct rlimit
struct rusage
Macros
#define __NEED_id_t
#define PRIO_MIN (-20)
#define PRIO_MAX 20
#define PRIO_PROCESS 0
#define PRIO_PGRP 1
#define PRIO_USER 2
#define RUSAGE_SELF 0
#define RUSAGE_CHILDREN (-1)
#define RUSAGE_THREAD 1
#define RLIM_INFINITY (~0ULL)
#define RLIM_SAVED_CUR RLIM_INFINITY
#define RLIM_SAVED_MAX RLIM_INFINITY
#define RLIMIT_CPU 0
#define RLIMIT_FSIZE 1
#define RLIMIT_DATA 2
#define RLIMIT_STACK 3
#define RLIMIT_CORE 4
#define RLIMIT_RSS 5
#define RLIMIT_NPROC 6
#define RLIMIT_NOFILE 7
#define RLIMIT_MEMLOCK 8
#define RLIMIT_AS 9
#define RLIMIT_LOCKS 10
#define RLIMIT_SIGPENDING 11
#define RLIMIT_MSGQUEUE 12
#define RLIMIT_NICE 13
#define RLIMIT_RTPRIO 14
#define RLIMIT_RTTIME 15
#define RLIMIT_NLIMITS 16
#define RLIM_NLIMITS RLIMIT_NLIMITS
Typedefs
typedef unsigned long long rlim_t
Functions
int getrlimit (int, struct rlimit *)
int setrlimit (int, const struct rlimit *)
int getrusage (int, struct rusage *)
int getpriority (int, id_t)
int setpriority (int, id_t, int)
Data Structure Documentation
rlimit
struct rlimit
Definition at line 22 of file resource.h.
Data Fields
rlim_t rlim_cur
rlim_t rlim_max
rusage
struct rusage
Definition at line 27 of file resource.h.
Data Fields
long __reserved[16]
long ru_idrss
long ru_inblock
long ru_isrss
long ru_ixrss
long ru_majflt
long ru_maxrss
long ru_minflt
long ru_msgrcv
long ru_msgsnd
long ru_nivcsw
long ru_nsignals
long ru_nswap
long ru_nvcsw
long ru_oublock
struct timeval ru_stime
struct timeval ru_utime
Macro Definition Documentation
__NEED_id_t
#define __NEED_id_t
Definition at line 11 of file resource.h.
PRIO_MAX
#define PRIO_MAX 20
Definition at line 62 of file resource.h.
PRIO_MIN
#define PRIO_MIN (-20)
Definition at line 61 of file resource.h.
PRIO_PGRP
#define PRIO_PGRP 1
Definition at line 65 of file resource.h.
PRIO_PROCESS
#define PRIO_PROCESS 0
Definition at line 64 of file resource.h.
PRIO_USER
#define PRIO_USER 2
Definition at line 66 of file resource.h.
RLIM_INFINITY
#define RLIM_INFINITY (~0ULL)
Definition at line 72 of file resource.h.
RLIM_NLIMITS
#define RLIM_NLIMITS RLIMIT_NLIMITS
Definition at line 96 of file resource.h.
RLIM_SAVED_CUR
#define RLIM_SAVED_CUR RLIM_INFINITY
Definition at line 73 of file resource.h.
RLIM_SAVED_MAX
#define RLIM_SAVED_MAX RLIM_INFINITY
Definition at line 74 of file resource.h.
RLIMIT_AS
#define RLIMIT_AS 9
Definition at line 86 of file resource.h.
RLIMIT_CORE
#define RLIMIT_CORE 4
Definition at line 80 of file resource.h.
RLIMIT_CPU
#define RLIMIT_CPU 0
Definition at line 76 of file resource.h.
RLIMIT_DATA
#define RLIMIT_DATA 2
Definition at line 78 of file resource.h.
RLIMIT_FSIZE
#define RLIMIT_FSIZE 1
Definition at line 77 of file resource.h.
RLIMIT_LOCKS
#define RLIMIT_LOCKS 10
Definition at line 88 of file resource.h.
RLIMIT_MEMLOCK
#define RLIMIT_MEMLOCK 8
Definition at line 85 of file resource.h.
RLIMIT_MSGQUEUE
#define RLIMIT_MSGQUEUE 12
Definition at line 90 of file resource.h.
RLIMIT_NICE
#define RLIMIT_NICE 13
Definition at line 91 of file resource.h.
RLIMIT_NLIMITS
#define RLIMIT_NLIMITS 16
Definition at line 94 of file resource.h.
RLIMIT_NOFILE
#define RLIMIT_NOFILE 7
Definition at line 84 of file resource.h.
RLIMIT_NPROC
#define RLIMIT_NPROC 6
Definition at line 83 of file resource.h.
RLIMIT_RSS
#define RLIMIT_RSS 5
Definition at line 82 of file resource.h.
RLIMIT_RTPRIO
#define RLIMIT_RTPRIO 14
Definition at line 92 of file resource.h.
RLIMIT_RTTIME
#define RLIMIT_RTTIME 15
Definition at line 93 of file resource.h.
RLIMIT_SIGPENDING
#define RLIMIT_SIGPENDING 11
Definition at line 89 of file resource.h.
RLIMIT_STACK
#define RLIMIT_STACK 3
Definition at line 79 of file resource.h.
RUSAGE_CHILDREN
#define RUSAGE_CHILDREN (-1)
Definition at line 69 of file resource.h.
RUSAGE_SELF
#define RUSAGE_SELF 0
Definition at line 68 of file resource.h.
RUSAGE_THREAD
#define RUSAGE_THREAD 1
Definition at line 70 of file resource.h.
Typedef Documentation
rlim_t
typedef unsigned long long rlim_t
Definition at line 20 of file resource.h.
Function Documentation
getpriority()
int getpriority (int which, id_t who)
Definition at line 4 of file getpriority.c.
 {
     int ret = syscall(SYS_getpriority, which, who);
     if (ret < 0) return ret;
     return 20-ret;
 }
References syscall().
Referenced by nice().
getrlimit()
int getrlimit (int resource, struct rlimit * rlim)
Definition at line 7 of file getrlimit.c.
 {
     int ret = syscall(SYS_prlimit64, 0, resource, 0, rlim);
     if (!ret) {
         FIX(rlim->rlim_cur);
         FIX(rlim->rlim_max);
     }
 #ifdef SYS_getrlimit
     unsigned long k_rlim[2];
     if (!ret || errno != ENOSYS)
         return ret;
     if (syscall(SYS_getrlimit, resource, k_rlim) < 0)
         return -1;
     rlim->rlim_cur = k_rlim[0] == -1UL ? RLIM_INFINITY : k_rlim[0];
     rlim->rlim_max = k_rlim[1] == -1UL ? RLIM_INFINITY : k_rlim[1];
     FIX(rlim->rlim_cur);
     FIX(rlim->rlim_max);
     return 0;
 #else
     return ret;
 #endif
 }
References ENOSYS, errno, FIX, rlimit::rlim_cur, RLIM_INFINITY, rlimit::rlim_max, and syscall().
Referenced by getdtablesize(), sysconf(), and ulimit().
getrusage()
int getrusage (int who, struct rusage * ru)
Definition at line 6 of file getrusage.c.
 {
     int r;
 #ifdef SYS_getrusage_time64
     long long kru64[18];
     r = __syscall(SYS_getrusage_time64, who, kru64);
     if (!r) {
         ru->ru_utime = (struct timeval)
             { .tv_sec = kru64[0], .tv_usec = kru64[1] };
         ru->ru_stime = (struct timeval)
             { .tv_sec = kru64[2], .tv_usec = kru64[3] };
         char *slots = (char *)&ru->ru_maxrss;
         for (int i=0; i<14; i++)
             *(long *)(slots + i*sizeof(long)) = kru64[4+i];
     }
     if (SYS_getrusage_time64 == SYS_getrusage || r != -ENOSYS)
         return __syscall_ret(r);
 #endif
     char *dest = (char *)&ru->ru_maxrss - 4*sizeof(long);
     r = __syscall(SYS_getrusage, who, dest);
     if (!r && sizeof(time_t) > sizeof(long)) {
         long kru[4];
         memcpy(kru, dest, 4*sizeof(long));
         ru->ru_utime = (struct timeval)
             { .tv_sec = kru[0], .tv_usec = kru[1] };
         ru->ru_stime = (struct timeval)
             { .tv_sec = kru[2], .tv_usec = kru[3] };
     }
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ENOSYS, i, memcpy(), rusage::ru_maxrss, rusage::ru_stime, rusage::ru_utime, and SYS_getrusage_time64.
setpriority()
int setpriority (int which, id_t who, int prio)
Definition at line 4 of file setpriority.c.
 {
     return syscall(SYS_setpriority, which, who, prio);
 }
References syscall().
Referenced by nice().
setrlimit()
int setrlimit (int resource, const struct rlimit * rlim)
Definition at line 24 of file setrlimit.c.
 {
     struct rlimit tmp;
     if (SYSCALL_RLIM_INFINITY != RLIM_INFINITY) {
         tmp = *rlim;
         FIX(tmp.rlim_cur);
         FIX(tmp.rlim_max);
         rlim = &tmp;
     }
     int ret = __syscall(SYS_prlimit64, 0, resource, rlim, 0);
 #ifdef SYS_setrlimit
     if (ret != -ENOSYS) return __syscall_ret(ret);
     struct ctx c = {
         .lim[0] = MIN(rlim->rlim_cur, MIN(-1UL, SYSCALL_RLIM_INFINITY)),
         .lim[1] = MIN(rlim->rlim_max, MIN(-1UL, SYSCALL_RLIM_INFINITY)),
         .res = resource, .err = -1
     };
     __synccall(do_setrlimit, &c);
     if (c.err) {
         if (c.err>0) errno = c.err;
         return -1;
     }
     return 0;
 #else
     return __syscall_ret(ret);
 #endif
 }
References __synccall(), __syscall, __syscall_ret(), ENOSYS, ctx::err, errno, FIX, ctx::lim, MIN, ctx::ret, rlimit::rlim_cur, RLIM_INFINITY, rlimit::rlim_max, and SYSCALL_RLIM_INFINITY.
Referenced by ulimit().