Fennix Drivers: Drivers/Input/VirtualBoxMouse/VirtualBoxMouseDriver.cpp File Reference
VirtualBoxMouseDriver.cpp File Reference
#include <pci.h>
#include <io.h>
#include "../../../Kernel/DAPI.hpp"
#include "../../../Kernel/Fex.hpp"
Macros
#define print(msg) KAPI->Util.DebugPrint((char *)(msg), KAPI->Info.DriverUID)
Functions
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *Registers)
HEAD (FexFormatType_Driver, FexOSType_Fennix, DriverEntry)
__attribute__ ((section(".extended"))) FexExtended ExtendedHeader
Variables
KernelAPI * KAPI
int MouseX = 0
int MouseY = 0
int MouseZ = 0
int MouseButton = 0
Macro Definition Documentation
print
#define print (msg) KAPI->Util.DebugPrint((char *)(msg), KAPI->Info.DriverUID)
Definition at line 35 of file VirtualBoxMouseDriver.cpp.
Function Documentation
__attribute__()
__attribute__ ((section(".extended")))
References CallbackHandler(), and InterruptCallback().
CallbackHandler()
int CallbackHandler (KernelCallback * Data)
Definition at line 56 of file VirtualBoxMouseDriver.cpp.
 {
     switch (Data->Reason)
     {
     case AcknowledgeReason:
     {
         print("Kernel acknowledged the driver.");
         break;
     }
     case ConfigurationReason:
     {
         break;
     }
     case FetchReason:
     {
         Data->InputCallback.Mouse.X = MouseX;
         Data->InputCallback.Mouse.Y = MouseY;
         Data->InputCallback.Mouse.Z = MouseZ;
         Data->InputCallback.Mouse.Buttons.Left = MouseButton & 0x20;
         Data->InputCallback.Mouse.Buttons.Right = MouseButton & 0x10;
         Data->InputCallback.Mouse.Buttons.Middle = MouseButton & 0x08;
         break;
     }
     case StopReason:
     {
         break;
     }
     default:
     {
         break;
     }
     }
     return OK;
 }
References MouseButton, MouseX, MouseY, MouseZ, and print.
Referenced by __attribute__().
DriverEntry()
int DriverEntry (void * Data)
Definition at line 39 of file VirtualBoxMouseDriver.cpp.
 {
     if (!Data)
         return INVALID_KERNEL_API;
     KAPI = (KernelAPI *)Data;
     if (KAPI->Version.Major < 0 || KAPI->Version.Minor < 0 || KAPI->Version.Patch < 0)
         return KERNEL_API_VERSION_NOT_SUPPORTED;
     print("Not implemented!");
     return NOT_IMPLEMENTED;
     // return OK;
 }
References KAPI, and print.
HEAD()
HEAD (FexFormatType_Driver , FexOSType_Fennix , DriverEntry)
InterruptCallback()
int InterruptCallback (CPURegisters * Registers)
Definition at line 91 of file VirtualBoxMouseDriver.cpp.
 {
     return OK;
 }
Referenced by __attribute__().
Variable Documentation
KAPI
KernelAPI* KAPI
Definition at line 33 of file VirtualBoxMouseDriver.cpp.
Referenced by DriverEntry().
MouseButton
int MouseButton = 0
Definition at line 54 of file VirtualBoxMouseDriver.cpp.
Referenced by CallbackHandler().
MouseX
int MouseX = 0
Definition at line 53 of file VirtualBoxMouseDriver.cpp.
Referenced by CallbackHandler().
MouseY
int MouseY = 0
Definition at line 53 of file VirtualBoxMouseDriver.cpp.
Referenced by CallbackHandler().
MouseZ
int MouseZ = 0
Definition at line 53 of file VirtualBoxMouseDriver.cpp.
Referenced by CallbackHandler().