Fennix Userspace: Userspace/apps/base/busybox/scripts/echo.c File Reference
echo.c File Reference
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <unistd.h>
Macros
#define WANT_HEX_ESCAPES 1
#define _tolower(X) ((X)|((char) 0x20))
Functions
static char bb_process_escape_sequence (const char **ptr)
int main (int argc, char **argv)
Macro Definition Documentation
_tolower
#define _tolower (X) ((X)|((char) 0x20))
Definition at line 36 of file echo.c.
WANT_HEX_ESCAPES
#define WANT_HEX_ESCAPES 1
Definition at line 32 of file echo.c.
Function Documentation
bb_process_escape_sequence()
static char bb_process_escape_sequence (const char ** ptr) static
Definition at line 38 of file echo.c.
 {
     static const char charmap[] = {
         'a',  'b',  'f',  'n',  'r',  't',  'v',  '\\', 0,
         '\a', '\b', '\f', '\n', '\r', '\t', '\v', '\\', '\\' };
     const char *p;
     const char *q;
     unsigned int num_digits;
     unsigned int r;
     unsigned int n;
     unsigned int d;
     unsigned int base;
     num_digits = n = 0;
     base = 8;
     q = *ptr;
 #ifdef WANT_HEX_ESCAPES
     if (*q == 'x') {
         ++q;
         base = 16;
         ++num_digits;
     }
 #endif
     do {
         d = (unsigned char)(*q) - '0';
 #ifdef WANT_HEX_ESCAPES
         if (d >= 10) {
             d = (unsigned char)(_tolower(*q)) - 'a' + 10;
         }
 #endif
         if (d >= base) {
 #ifdef WANT_HEX_ESCAPES
             if ((base == 16) && (!--num_digits)) {
 /*              return '\\'; */
                 --q;
             }
 #endif
             break;
         }
         r = n * base + d;
         if (r > UCHAR_MAX) {
             break;
         }
         n = r;
         ++q;
     } while (++num_digits < 3);
     if (num_digits == 0) {  /* mnemonic escape sequence? */
         p = charmap;
         do {
             if (*p == *q) {
                 q++;
                 break;
             }
         } while (*++p);
         n = *(p + (sizeof(charmap)/2));
     }
     *ptr = q;
     return (char) n;
 }
References _tolower, base, n, p, and UCHAR_MAX.
Referenced by echo_main(), and main().
main()
int main (int argc , char ** argv)
Definition at line 108 of file echo.c.
 {
     const char *arg;
     const char *p;
     char nflag = 1;
     char eflag = 0;
     /* We must check that stdout is not closed. */
     if (dup2(1, 1) != 1)
         return -1;
     while (1) {
         arg = *++argv;
         if (!arg)
             goto newline_ret;
         if (*arg != '-')
             break;
         /* If it appears that we are handling options, then make sure
          * that all of the options specified are actually valid.
          * Otherwise, the string should just be echoed.
          */
         p = arg + 1;
         if (!*p)    /* A single '-', so echo it. */
             goto just_echo;
         do {
             if (!strrchr("neE", *p))
                 goto just_echo;
         } while (*++p);
         /* All of the options in this arg are valid, so handle them. */
         p = arg + 1;
         do {
             if (*p == 'n')
                 nflag = 0;
             if (*p == 'e')
                 eflag = '\\';
         } while (*++p);
     }
  just_echo:
     while (1) {
         /* arg is already == *argv and isn't NULL */
         int c;
         if (!eflag) {
             /* optimization for very common case */
             fputs(arg, stdout);
         } else
         while ((c = *arg++) != '\0') {
             if (c == eflag) {
                 /* This is an "\x" sequence */
                 if (*arg == 'c') {
                     /* "\c" means cancel newline and
                      * ignore all subsequent chars. */
                     goto ret;
                 }
                 /* Since SUSv3 mandates a first digit of 0, 4-digit octals
                 * of the form \0### are accepted. */
                 if (*arg == '0') {
                     if ((unsigned char)(arg[1] - '0') < 8) {
                         /* 2nd char is 0..7: skip leading '0' */
                         arg++;
                     }
                 }
                 /* bb_process_escape_sequence handles NUL correctly
                  * ("...\" case). */
                 {
                     /* optimization: don't force arg to be on-stack,
                      * use another variable for that. ~30 bytes win */
                     const char *z = arg;
                     c = bb_process_escape_sequence(&z);
                     arg = z;
                 }
             }
             putchar(c);
         }
         arg = *++argv;
         if (!arg)
             break;
         putchar(' ');
     }
  newline_ret:
     if (nflag) {
         putchar('\n');
     }
  ret:
     return fflush(NULL);
 }
References argv, bb_process_escape_sequence(), c, dup2(), eflag, fflush(), fputs, nflag, NULL, p, putchar, stdout, and strrchr().