Fennix Userspace: Userspace/apps/base/bash/include/ansi_stdlib.h File Reference
ansi_stdlib.h File Reference
Macros
#define PTR_T char *
Functions
int atoi ()
double atof ()
double strtod ()
PTR_T malloc ()
PTR_T realloc ()
void free ()
void abort ()
void exit ()
char * getenv ()
void qsort ()
Macro Definition Documentation
PTR_T
#define PTR_T char *
Definition at line 39 of file ansi_stdlib.h.
Function Documentation
abort()
void abort ()
Definition at line 9 of file lib.c.
 {
     syscall1(sc_exit, -0xAB057);
     while (1)
         ;
 }
Referenced by __assert_fail(), botch(), conspy_main(), evaltreenr(), evalvar(), exitshell(), find_command(), get_sysdep_segment_value(), make_redirection(), memory_error_and_abort(), openredirect(), programming_error(), rl_callback_read_char(), set_curjob(), stunalloc(), and subevalvar().
atof()
double atof ()
Referenced by bootchartd_main(), compare_keys(), scriptreplay_main(), and SetVariable().
atoi()
int atoi ()
Referenced by _rl_get_screen_size(), action_compat(), bb_dump_add(), bb_dump_size(), chat_main(), compare_keys(), complete_get_screenwidth(), conf_choice(), D_DoomMain(), D_StartNetGame(), decode(), default_columns(), download_one_url(), ecvt(), evalcommand(), fbsplash_main(), G_RecordDemo(), get_linux_version_code(), get_old_name(), get_uid_gid(), getjob(), head_builtin(), I_InitGraphics(), I_ZoneBase(), init(), init_wsize(), j_infobox(), j_inputbox(), j_menu(), j_msgbox(), j_radiolist(), j_textbox(), j_yesno(), main(), number(), parse_conf(), ParseLine(), patch_main(), popmaildir_main(), preadfd(), read_command(), readtoken1(), rewrite(), sendmail_main(), smtp_checkp(), sv_compquery(), sv_compwidth(), sv_dispprefix(), sv_histsize(), sv_ignoreeof(), sv_opterr(), sv_optind(), sv_seqtimeout(), tgetnum(), varvalue(), version_compare(), and wh_helper().
exit()
void exit ()
Referenced by __pthread_exit(), back_lines(), bb_show_usage(), check_stdin(), cleanup(), close_conn_and_exit(), cmdio_get_cmd_and_arg(), command_substitute(), conf_askvalue(), conf_choice(), D_DoomMain(), D_Endoom(), dialog_checklist(), dialog_textbox(), die(), disable_priv_mode(), do_config_file(), docfunctions(), doexit(), escape_input(), exec_conf(), exec_kernel_doc(), execute_disk_command(), execute_in_subshell(), execute_null_command(), execute_subshell_builtin_or_function(), ExecuteCommand(), exit_SUCCESS(), file_error(), finish(), function_handler(), get_line(), get_username_or_die(), grow_config(), HandleSignal(), I_Error(), I_Quit(), init_wsize(), initialize_job_control(), kconfig_load(), kill_shell(), libc_start_main_stage2(), LoadResponseFile(), ls_main(), main(), memory_error_and_abort(), memory_out(), new_group(), noresp(), open_shell_script(), parse_address(), parse_args(), parse_dep_file(), parse_long_options(), parse_shell_options(), popen_ls(), print_deps(), print_position(), process_includes(), process_line(), restore_state_and_exit(), run_shopt_alist(), scan_request(), serial_ctl(), serial_set(), setfiles_main(), sh_exit(), show_textbox(), sigpipe(), stralloc(), strgrow(), test_execve_fork(), test_stdio(), test_watch_directory(), test_watch_file(), timeout_handler(), tls_run_copy_loop(), update_local_clock(), usage(), Usage(), verr(), verrx(), wait_for_input(), wget_main(), write_helpfiles(), xfunc_die(), and xmalloc().
free()
void free ()
getenv()
char* getenv ()
malloc()
PTR_T malloc ()
qsort()
void qsort ()
Referenced by __lookup_name(), compute_lcd_of_matches(), create_J(), cut_main(), getlist(), glob(), initialize_shell_builtins(), main(), parse_bracket(), qsort_string_vector(), read_alias_file(), remove_duplicate_matches(), rl_display_match_list(), rl_funmap_names(), run_parts_main(), scandir(), select_and_cluster(), showvars(), sort_index(), sort_inplace(), sort_lines(), sort_main(), sort_variables(), strvec_sort(), stupidly_hack_special_variables(), and top_main().
realloc()
PTR_T realloc ()
strtod()
double strtod ()
Referenced by atof(), compare_keys(), conv_strtod(), my_strtod(), seq_main(), sort_index(), sort_inplace(), stack_machine(), and strtod_l().