Fennix Userspace: Kernel/include/memory.hpp File Reference
memory.hpp File Reference
#include <boot/binfo.h>
#include <bitmap.hpp>
#include <lock.hpp>
#include <types.h>
Data Structures
struct Memory::PageTable
class Memory::Physical
class Memory::Virtual
class Memory::Virtual::PageMapIndexer
Namespaces
Memory
Macros
#define TO_KB(d) (d / 1024)
#define TO_MB(d) (d / 1024 / 1024)
#define TO_GB(d) (d / 1024 / 1024 / 1024)
#define TO_TB(d) (d / 1024 / 1024 / 1024 / 1024)
#define TO_PB(d) (d / 1024 / 1024 / 1024 / 1024 / 1024)
#define TO_EB(d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
#define TO_ZB(d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
#define TO_YB(d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
#define TO_BB(d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
#define TO_GPB(d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
#define PAGE_SIZE 0x1000
#define TO_PAGES(d) (d / PAGE_SIZE + 1)
#define FROM_PAGES(d) (d * PAGE_SIZE - 1)
#define NORMAL_VMA_OFFSET 0xFFFF800000000000
#define KERNEL_VMA_OFFSET 0xFFFFFFFF80000000
#define KERNEL_HEAP_BASE 0xFFFFC00000000000
KERNEL_HEAP_BASE is the base address of the kernel heap.
#define USER_HEAP_BASE 0xFFFFD00000000000
USER_HEAP_BASE is the base address of the user heap allocated by the kernel.
#define kmalloc(Size) HeapMalloc(Size)
#define kcalloc(n, Size) HeapCalloc(n, Size)
#define krealloc(Address, Size) HeapRealloc(Address, Size)
#define kfree(Address) HeapFree(Address)
Enumerations
enum Memory::PTFlag {
Memory::P = 1 << 0, Memory::RW = 1 << 1, Memory::US = 1 << 2, Memory::PWT = 1 << 3,
Memory::PCD = 1 << 4, Memory::A = 1 << 5, Memory::D = 1 << 6, Memory::PS = 1 << 7,
Memory::G = 1 << 8, Memory::AVL0 = 1 << 9, Memory::AVL1 = 1 << 10, Memory::AVL2 = 1 << 11,
Memory::PAT = 1 << 12, Memory::AVL3 = (uint64_t)1 << 52, Memory::AVL4 = (uint64_t)1 << 53, Memory::AVL5 = (uint64_t)1 << 54,
Memory::AVL6 = (uint64_t)1 << 55, Memory::AVL7 = (uint64_t)1 << 56, Memory::AVL8 = (uint64_t)1 << 57, Memory::AVL9 = (uint64_t)1 << 58,
Memory::PK0 = (uint64_t)1 << 59, Memory::PK1 = (uint64_t)1 << 60, Memory::PK2 = (uint64_t)1 << 61, Memory::PK3 = (uint64_t)1 << 62,
Memory::XD = (uint64_t)1 << 63
}
https://wiki.osdev.org/images/4/41/64-bit_page_tables1.png
Functions
union Memory::__attribute__ ((packed))
struct Memory::PageTable Memory::__attribute__ ((aligned(0x1000)))
void InitializeMemoryManagement (BootInfo *Info)
void * operator new (uint64_t Size)
void * operator new[] (uint64_t Size)
void operator delete (void *Pointer)
void operator delete[] (void *Pointer)
void operator delete (void *Pointer, long unsigned int Size)
void operator delete[] (void *Pointer, long unsigned int Size)
void * HeapMalloc (uint64_t Size)
void * HeapCalloc (uint64_t n, uint64_t Size)
void * HeapRealloc (void *Address, uint64_t Size)
void HeapFree (void *Address)
Variables
uint64_t _kernel_start
uint64_t _kernel_end
uint64_t _kernel_text_end
uint64_t _kernel_data_end
uint64_t _kernel_rodata_end
Memory::PDEData
PageDirectoryEntry Entries [512]
class Memory::Physical Memory::__attribute__
Memory::Physical KernelAllocator
Memory::PageTable * KernelPageTable
Data Structure Documentation
Memory::PageTable
struct Memory::PageTable
Definition at line 201 of file memory.hpp.
Data Fields
PageDirectoryEntry Entries[512]
Macro Definition Documentation
FROM_PAGES
#define FROM_PAGES (d) (d * PAGE_SIZE - 1)
Definition at line 38 of file memory.hpp.
kcalloc
#define kcalloc (n, Size) HeapCalloc(n, Size)
Definition at line 425 of file memory.hpp.
KERNEL_HEAP_BASE
#define KERNEL_HEAP_BASE 0xFFFFC00000000000
KERNEL_HEAP_BASE is the base address of the kernel heap.
Definition at line 46 of file memory.hpp.
KERNEL_VMA_OFFSET
#define KERNEL_VMA_OFFSET 0xFFFFFFFF80000000
Definition at line 41 of file memory.hpp.
kfree
#define kfree (Address) HeapFree(Address)
Definition at line 427 of file memory.hpp.
kmalloc
#define kmalloc (Size) HeapMalloc(Size)
Definition at line 424 of file memory.hpp.
krealloc
#define krealloc (Address, Size) HeapRealloc(Address, Size)
Definition at line 426 of file memory.hpp.
NORMAL_VMA_OFFSET
#define NORMAL_VMA_OFFSET 0xFFFF800000000000
Definition at line 40 of file memory.hpp.
PAGE_SIZE
#define PAGE_SIZE 0x1000
Definition at line 33 of file memory.hpp.
TO_BB
#define TO_BB (d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
Definition at line 29 of file memory.hpp.
TO_EB
#define TO_EB (d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
Definition at line 23 of file memory.hpp.
TO_GB
#define TO_GB (d) (d / 1024 / 1024 / 1024)
Definition at line 17 of file memory.hpp.
TO_GPB
#define TO_GPB (d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
Definition at line 31 of file memory.hpp.
TO_KB
#define TO_KB (d) (d / 1024)
Definition at line 13 of file memory.hpp.
TO_MB
#define TO_MB (d) (d / 1024 / 1024)
Definition at line 15 of file memory.hpp.
TO_PAGES
#define TO_PAGES (d) (d / PAGE_SIZE + 1)
Definition at line 36 of file memory.hpp.
TO_PB
#define TO_PB (d) (d / 1024 / 1024 / 1024 / 1024 / 1024)
Definition at line 21 of file memory.hpp.
TO_TB
#define TO_TB (d) (d / 1024 / 1024 / 1024 / 1024)
Definition at line 19 of file memory.hpp.
TO_YB
#define TO_YB (d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
Definition at line 27 of file memory.hpp.
TO_ZB
#define TO_ZB (d) (d / 1024 / 1024 / 1024 / 1024 / 1024 / 1024 / 1024)
Definition at line 25 of file memory.hpp.
USER_HEAP_BASE
#define USER_HEAP_BASE 0xFFFFD00000000000
USER_HEAP_BASE is the base address of the user heap allocated by the kernel.
Definition at line 50 of file memory.hpp.
Function Documentation
HeapCalloc()
void* HeapCalloc (uint64_t n, uint64_t Size)
Definition at line 161 of file Memory.cpp.
 {
     switch (AllocatorType)
     {
     case MemoryAllocatorType::Pages:
         return KernelAllocator.RequestPages(TO_PAGES(n * Size));
     case MemoryAllocatorType::XallocV1:
         return XallocV1Allocator->Calloc(n, Size);
     case MemoryAllocatorType::liballoc11:
         return PREFIX(calloc)(n, Size);
     default:
         throw;
     }
 }
HeapFree()
void HeapFree (void * Address)
Definition at line 191 of file Memory.cpp.
 {
     switch (AllocatorType)
     {
     case MemoryAllocatorType::Pages:
         KernelAllocator.FreePage(Address); // WARNING: Potential memory leak
         break;
     case MemoryAllocatorType::XallocV1:
         XallocV1Allocator->Free(Address);
         break;
     case MemoryAllocatorType::liballoc11:
         PREFIX(free)
         (Address);
         break;
     default:
         throw;
     }
 }
HeapMalloc()
void* HeapMalloc (uint64_t Size)
Definition at line 146 of file Memory.cpp.
 {
     switch (AllocatorType)
     {
     case MemoryAllocatorType::Pages:
         return KernelAllocator.RequestPages(TO_PAGES(Size));
     case MemoryAllocatorType::XallocV1:
         return XallocV1Allocator->Malloc(Size);
     case MemoryAllocatorType::liballoc11:
         return PREFIX(malloc)(Size);
     default:
         throw;
     }
 }
HeapRealloc()
void* HeapRealloc (void * Address, uint64_t Size)
Definition at line 176 of file Memory.cpp.
 {
     switch (AllocatorType)
     {
     case MemoryAllocatorType::Pages:
         return KernelAllocator.RequestPages(TO_PAGES(Size)); // WARNING: Potential memory leak
     case MemoryAllocatorType::XallocV1:
         return XallocV1Allocator->Realloc(Address, Size);
     case MemoryAllocatorType::liballoc11:
         return PREFIX(realloc)(Address, Size);
     default:
         throw;
     }
 }
InitializeMemoryManagement()
void InitializeMemoryManagement (BootInfo * Info)
Definition at line 43 of file Memory.cpp.
 {
     trace("Initializing Physical Memory Manager");
     KernelAllocator = Physical();
     KernelAllocator.Init(Info);
     debug("Memory Info: %dMB / %dMB (%dMB reserved)",
           TO_MB(KernelAllocator.GetUsedMemory()),
           TO_MB(KernelAllocator.GetTotalMemory()),
           TO_MB(KernelAllocator.GetReservedMemory()));
     AllocatorType = MemoryAllocatorType::Pages;
     trace("Initializing Virtual Memory Manager");
     KernelPageTable = (PageTable *)KernelAllocator.RequestPage();
     memset(KernelPageTable, 0, PAGE_SIZE);
     Virtual kva = Virtual(KernelPageTable);
     uint64_t KernelStart = (uint64_t)&_kernel_start;
     uint64_t KernelTextEnd = (uint64_t)&_kernel_text_end;
     uint64_t KernelDataEnd = (uint64_t)&_kernel_data_end;
     uint64_t KernelRoDataEnd = (uint64_t)&_kernel_rodata_end;
     uint64_t KernelEnd = (uint64_t)&_kernel_end;
     uint64_t VirtualOffsetNormalVMA = NORMAL_VMA_OFFSET;
     uint64_t BaseKernelMapAddress = (uint64_t)Info->Kernel.PhysicalBase;
     for (uint64_t t = 0; t < Info->Memory.Size; t += PAGE_SIZE)
     {
         kva.Map((void *)t, (void *)t, PTFlag::RW);
         kva.Map((void *)VirtualOffsetNormalVMA, (void *)t, PTFlag::RW);
         VirtualOffsetNormalVMA += PAGE_SIZE;
     }
     /* Mapping Framebuffer address */
     int itrfb = 0;
     while (1)
     {
         if (!Info->Framebuffer[itrfb].BaseAddress)
             break;
         for (uint64_t fb_base = (uint64_t)Info->Framebuffer[itrfb].BaseAddress;
              fb_base < ((uint64_t)Info->Framebuffer[itrfb].BaseAddress + ((Info->Framebuffer[itrfb].Pitch * Info->Framebuffer[itrfb].Height) + PAGE_SIZE));
              fb_base += PAGE_SIZE)
             kva.Map((void *)(fb_base + NORMAL_VMA_OFFSET), (void *)fb_base, PTFlag::RW | PTFlag::US);
         itrfb++;
     }
     /* Kernel mapping */
     for (uint64_t k = KernelStart; k < KernelTextEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (uint64_t k = KernelTextEnd; k < KernelDataEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (uint64_t k = KernelDataEnd; k < KernelRoDataEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::P);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (uint64_t k = KernelRoDataEnd; k < KernelEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     debug("\nStart: %#llx - Text End: %#llx - RoEnd: %#llx - End: %#llx\nStart Physical: %#llx - End Physical: %#llx",
           KernelStart, KernelTextEnd, KernelRoDataEnd, KernelEnd, Info->Kernel.PhysicalBase, BaseKernelMapAddress - PAGE_SIZE);
     /*    KernelStart             KernelTextEnd       KernelRoDataEnd                  KernelEnd
     Kernel Start & Text Start ------ Text End ------ Kernel Rodata End ------ Kernel Data End & Kernel End
     */
     trace("Applying new page table from address %p", KernelPageTable);
 #ifdef DEBUG
     tracepagetable(KernelPageTable);
 #endif
 #if defined(__amd64__) || defined(__i386__)
     asmv("mov %0, %%cr3" ::"r"(KernelPageTable));
 #elif defined(__aarch64__)
     asmv("msr ttbr0_el1, %0" ::"r"(KernelPageTable));
 #endif
     if (strstr(Info->Kernel.CommandLine, "xallocv1"))
     {
         XallocV1Allocator = new Xalloc::AllocatorV1((void *)KERNEL_HEAP_BASE, false, false);
         AllocatorType = MemoryAllocatorType::XallocV1;
         trace("XallocV1 Allocator initialized (%p)", XallocV1Allocator);
     }
     else if (strstr(Info->Kernel.CommandLine, "liballoc11"))
     {
         AllocatorType = MemoryAllocatorType::liballoc11;
     }
 }
References _kernel_data_end, _kernel_end, _kernel_rodata_end, _kernel_start, _kernel_text_end, AllocatorType, asmv, BootInfo::FramebufferInfo::BaseAddress, BootInfo::KernelInfo::CommandLine, debug, BootInfo::Framebuffer, Memory::Physical::GetReservedMemory(), Memory::Physical::GetTotalMemory(), Memory::Physical::GetUsedMemory(), BootInfo::FramebufferInfo::Height, Memory::Physical::Init(), BootInfo::Kernel, KERNEL_HEAP_BASE, KernelAllocator, KernelPageTable, liballoc11, Memory::Physical::LockPage(), Memory::Virtual::Map(), BootInfo::Memory, memset(), NORMAL_VMA_OFFSET, Memory::P, PAGE_SIZE, Pages, BootInfo::KernelInfo::PhysicalBase, BootInfo::FramebufferInfo::Pitch, Memory::Physical::RequestPage(), Memory::RW, BootInfo::MemoryInfo::Size, strstr(), TO_MB, trace, Memory::US, XallocV1, and XallocV1Allocator.
Referenced by efi_main(), and Entry().
operator delete() [1/2]
void operator delete (void * Pointer)
Definition at line 212 of file Memory.cpp.
 { HeapFree(Pointer); }
References HeapFree().
operator delete() [2/2]
void operator delete (void * Pointer, long unsigned int Size)
Definition at line 214 of file Memory.cpp.
 { HeapFree(Pointer); }
References HeapFree().
operator delete[]() [1/2]
void operator delete[] (void * Pointer)
Definition at line 213 of file Memory.cpp.
 { HeapFree(Pointer); }
References HeapFree().
operator delete[]() [2/2]
void operator delete[] (void * Pointer, long unsigned int Size)
Definition at line 215 of file Memory.cpp.
 { HeapFree(Pointer); }
References HeapFree().
operator new()
void* operator new (uint64_t Size)
Definition at line 210 of file Memory.cpp.
 { return HeapMalloc(Size); }
References HeapMalloc().
operator new[]()
void* operator new[] (uint64_t Size)
Definition at line 211 of file Memory.cpp.
 { return HeapMalloc(Size); }
References HeapMalloc().
Variable Documentation
_kernel_data_end
uint64_t _kernel_data_end
Definition at line 10 of file memory.hpp.
Referenced by InitializeMemoryManagement().
_kernel_end
uint64_t _kernel_end
Definition at line 9 of file memory.hpp.
Referenced by CrashHandler::__attribute__(), and InitializeMemoryManagement().
_kernel_rodata_end
uint64_t _kernel_rodata_end
Definition at line 10 of file memory.hpp.
Referenced by InitializeMemoryManagement().
_kernel_start
uint64_t _kernel_start
Referenced by InitializeMemoryManagement().
_kernel_text_end
uint64_t _kernel_text_end
Referenced by InitializeMemoryManagement().
Entries
PageDirectoryEntry Entries[512]
Definition at line 158 of file memory.hpp.
KernelAllocator
Memory::Physical KernelAllocator
Definition at line 11 of file Memory.cpp.
Referenced by GlobalDescriptorTable::__attribute__(), Video::Display::CreateBuffer(), Video::Display::DeleteBuffer(), Entry(), Video::Font::Font(), HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), InitializeMemoryManagement(), liballoc_alloc(), liballoc_free(), Memory::Virtual::Map(), SymbolResolver::Symbols::Symbols(), and SymbolResolver::Symbols::~Symbols().
KernelPageTable
Memory::PageTable* KernelPageTable
Definition at line 12 of file Memory.cpp.
Referenced by InitializeMemoryManagement().