Fennix Userspace: Userspace/mlibc/options/ansi/include/fenv.h File Reference
fenv.h File Reference
#include <bits/types.h>
#include <bits/ansi/fenv.h>
Data Structures
struct fenv_t
Macros
#define FE_DFL_ENV ((const fenv_t *) -1)
Typedefs
typedef __mlibc_uint16 fexcept_t
Functions
int feclearexcept (int)
int fegetenv (fenv_t *)
int fegetexceptflag (fexcept_t *, int)
int fegetround (void)
int feholdexcept (fenv_t *)
int feraiseexcept (int)
int fesetenv (const fenv_t *)
int fesetexceptflag (const fexcept_t *, int)
int fesetround (int)
int fetestexcept (int)
int feupdateenv (const fenv_t *)
Data Structure Documentation
fenv_t
struct fenv_t
Definition at line 12 of file fenv.h.
Data Fields
__mlibc_uint32 __control_word
__mlibc_uint32 __mxcsr
__mlibc_uint32 __status_word
__mlibc_uint32 __unused[5]
Macro Definition Documentation
FE_DFL_ENV
#define FE_DFL_ENV ((const fenv_t *) -1)
Definition at line 41 of file fenv.h.
Typedef Documentation
fexcept_t
typedef __mlibc_uint16 fexcept_t
Definition at line 19 of file fenv.h.
Function Documentation
feclearexcept()
int feclearexcept (int)
Referenced by fmaf(), nearbyint(), nearbyintf(), nearbyintl(), test0(), test1(), test2(), and test3().
fegetenv()
int fegetenv (fenv_t *)
Referenced by test3().
fegetexceptflag()
int fegetexceptflag (fexcept_t * , int)
Definition at line 9 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fegetround()
int fegetround (void)
Referenced by fmaf(), and test1().
feholdexcept()
int feholdexcept (fenv_t *)
Definition at line 14 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
feraiseexcept()
int feraiseexcept (int)
Referenced by fmaf(), test2(), and test3().
fesetenv()
int fesetenv (const fenv_t *)
Referenced by test3().
fesetexceptflag()
int fesetexceptflag (const fexcept_t * , int)
Definition at line 19 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fesetround()
int fesetround (int r)
Definition at line 24 of file fenv-stubs.cpp.
                       {
     if (r != FE_TONEAREST
 #ifdef FE_DOWNWARD
         && r != FE_DOWNWARD
 #endif
 #ifdef FE_UPWARD
         && r != FE_UPWARD
 #endif
 #ifdef FE_TOWARDZERO
         && r != FE_TOWARDZERO
 #endif
     )
         return -1;
     return __fesetround(r);
 }
References r.
Referenced by fmaf(), and test1().
fetestexcept()
int fetestexcept (int)
Referenced by fmaf(), nearbyint(), nearbyintf(), nearbyintl(), test0(), test1(), test2(), and test3().
feupdateenv()
int feupdateenv (const fenv_t *)
Definition at line 40 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.