Fennix: Userspace/mlibc/options/posix/include/pwd.h File Reference
pwd.h File Reference
#include <abi-bits/uid_t.h>
#include <abi-bits/gid_t.h>
#include <bits/size_t.h>
#include <stdio.h>
Data Structures
struct passwd
Functions
void endpwent (void)
struct passwd * getpwent (void)
struct passwd * getpwnam (const char *)
int getpwnam_r (const char *, struct passwd *, char *, size_t, struct passwd **)
struct passwd * getpwuid (uid_t)
int getpwuid_r (uid_t, struct passwd *, char *, size_t, struct passwd **)
void setpwent (void)
int putpwent (const struct passwd *, FILE *)
struct passwd * fgetpwent (FILE *)
Data Structure Documentation
passwd
struct passwd
Definition at line 14 of file pwd.h.
Data Fields
char * pw_dir
char * pw_gecos
gid_t pw_gid
char * pw_name
char * pw_passwd
char * pw_shell
uid_t pw_uid
Function Documentation
endpwent()
void endpwent (void)
Definition at line 272 of file pwd-stubs.cpp.
                     {
     close_global_file();
 }
References anonymous_namespace{pwd-stubs.cpp}::close_global_file().
fgetpwent()
struct passwd* fgetpwent (FILE *)
Definition at line 281 of file pwd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getpwent()
struct passwd* getpwent (void)
Definition at line 119 of file pwd-stubs.cpp.
{
     static passwd entry;
     char line[512];
     if(!open_global_file()) {
         return nullptr;
     }
     if (fgets(line, 512, global_file)) {
         clear_entry(&entry);
         if(!extract_entry(line, &entry)) {
             errno = EINVAL; // I suppose this can be a valid errno?
             return nullptr;
         }
         return &entry;
     }
     if(ferror(global_file)) {
         errno = EIO;
     }
     return nullptr;
 }
References anonymous_namespace{pwd-stubs.cpp}::clear_entry(), EINVAL, EIO, errno, anonymous_namespace{pwd-stubs.cpp}::extract_entry(), ferror(), fgets(), anonymous_namespace{pwd-stubs.cpp}::global_file, and anonymous_namespace{pwd-stubs.cpp}::open_global_file().
Referenced by main().
getpwnam()
struct passwd* getpwnam (const char * name)
Definition at line 143 of file pwd-stubs.cpp.
{
     static passwd entry;
     auto file = fopen("/etc/passwd", "r");
     if(!file)
         return nullptr;
     char line[512];
     while(fgets(line, 512, file)) {
         clear_entry(&entry);
         if(!extract_entry(line, &entry))
             continue;
         if(!strcmp(entry.pw_name, name)) {
             fclose(file);
             return &entry;
         }
     }
     int err = errno;
     if(ferror(file)) {
         err = EIO;
     }
     fclose(file);
     errno = err;
     return nullptr;
 }
References anonymous_namespace{pwd-stubs.cpp}::clear_entry(), EIO, errno, anonymous_namespace{pwd-stubs.cpp}::extract_entry(), fclose(), ferror(), fgets(), fopen(), name, passwd::pw_name, and strcmp().
Referenced by main().
getpwnam_r()
int getpwnam_r (const char * name, struct passwd * pwd, char * buffer, size_t size, struct passwd ** result)
Definition at line 170 of file pwd-stubs.cpp.
{
     *result = nullptr;
     auto file = fopen("/etc/passwd", "r");
     if(!file) {
         return EIO;
     }
     char line[512];
     while(fgets(line, 512, file)) {
         if(!extract_entry(line, pwd))
             continue;
         if(!strcmp(pwd->pw_name, name)) {
             fclose(file);
             size_t required_size = strlen(pwd->pw_name) + strlen(pwd->pw_dir)
                 + strlen(pwd->pw_shell) + strlen(pwd->pw_passwd) + 4;
             if (size < required_size)
                 return ERANGE;
             copy_to_buffer(pwd, buffer, size);
             *result = pwd;
             return 0;
         }
     }
     int ret = 0;
     if(ferror(file)) {
         ret = EIO;
     }
     fclose(file);
     return ret;
 }
References anonymous_namespace{pwd-stubs.cpp}::copy_to_buffer(), EIO, ERANGE, anonymous_namespace{pwd-stubs.cpp}::extract_entry(), fclose(), ferror(), fgets(), fopen(), name, passwd::pw_dir, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, ret, size, strcmp(), and strlen().
Referenced by expand_tilde(), and main().
getpwuid()
struct passwd* getpwuid (uid_t uid)
Definition at line 204 of file pwd-stubs.cpp.
{
     static passwd entry;
     auto file = fopen("/etc/passwd", "r");
     if(!file)
         return nullptr;
     char line[512];
     while(fgets(line, 512, file)) {
         clear_entry(&entry);
         if(!extract_entry(line, &entry))
             continue;
         if(entry.pw_uid == uid) {
             fclose(file);
             return &entry;
         }
     }
     int err = ESRCH;
     if(ferror(file)) {
         err = EIO;
     }
     fclose(file);
     errno = err;
     return nullptr;
 }
References anonymous_namespace{pwd-stubs.cpp}::clear_entry(), EIO, errno, ESRCH, anonymous_namespace{pwd-stubs.cpp}::extract_entry(), fclose(), ferror(), fgets(), fopen(), and passwd::pw_uid.
Referenced by main().
getpwuid_r()
int getpwuid_r (uid_t uid, struct passwd * pwd, char * buffer, size_t size, struct passwd ** result)
Definition at line 231 of file pwd-stubs.cpp.
{
     *result = nullptr;
     auto file = fopen("/etc/passwd", "r");
     if(!file) {
         return EIO;
     }
     char line[512];
     while(fgets(line, 512, file)) {
         if(!extract_entry(line, pwd))
             continue;
         if(pwd->pw_uid == uid) {
             fclose(file);
             size_t required_size = strlen(pwd->pw_name) + strlen(pwd->pw_dir)
                 + strlen(pwd->pw_shell) + + strlen(pwd->pw_passwd) + 4;
             if (size < required_size)
                 return ERANGE;
             copy_to_buffer(pwd, buffer, size);
             *result = pwd;
             return 0;
         }
     }
     int ret = 0;
     if(ferror(file)) {
         ret = EIO;
     }
     fclose(file);
     return ret;
 }
References anonymous_namespace{pwd-stubs.cpp}::copy_to_buffer(), EIO, ERANGE, anonymous_namespace{pwd-stubs.cpp}::extract_entry(), fclose(), ferror(), fgets(), fopen(), passwd::pw_dir, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, ret, size, and strlen().
Referenced by expand_tilde(), and main().
putpwent()
int putpwent (const struct passwd * , FILE *)
Definition at line 276 of file pwd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setpwent()
void setpwent (void)
Definition at line 265 of file pwd-stubs.cpp.
                     {
     if(!open_global_file()) {
         return;
     }
     rewind(global_file);
 }
References anonymous_namespace{pwd-stubs.cpp}::global_file, anonymous_namespace{pwd-stubs.cpp}::open_global_file(), and rewind().
Referenced by main().