Fennix Userspace: Userspace/mlibc/sysdeps/keyronex/generic/entry.cpp File Reference
entry.cpp File Reference
#include <stdint.h>
#include <stdlib.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/elf/startup.h>
#include <mlibc/all-sysdeps.hpp>
#include <bits/posix/posix_signal.h>
#include <keyronex/syscall.h>
Data Structures
struct LibraryGuard
struct GPRState
Namespaces
mlibc
Functions
void __mlibc_initLocale ()
uintptr_t * __dlapi_entrystack ()
int mlibc::sys_sigentry (void *sigentry)
int mlibc::sys_sigreturn (void *context, sigset_t old_mask)
static void __mlibc_sigentry (int which, siginfo_t *siginfo, void(*sa)(int, siginfo_t *, void *), GPRState *ret_context, sigset_t prev_mask)
void __mlibc_entry (int(*main_fn)(int argc, char *argv[], char *env[]))
Variables
char ** environ
static mlibc::exec_stack_data __mlibc_stack_data
static LibraryGuard guard
Data Structure Documentation
GPRState
struct GPRState
Definition at line 33 of file entry.cpp.
Data Fields
uint64_t cs
uint64_t ds
uint64_t err
uint64_t es
uint64_t r10
uint64_t r11
uint64_t r12
uint64_t r13
uint64_t r14
uint64_t r15
uint64_t r8
uint64_t r9
uint64_t rax
uint64_t rbp
uint64_t rbx
uint64_t rcx
uint64_t rdi
uint64_t rdx
uint64_t rflags
uint64_t rip
uint64_t rsi
uint64_t rsp
uint64_t ss
Function Documentation
__dlapi_entrystack()
uintptr_t* __dlapi_entrystack ()
Definition at line 398 of file main.cpp.
{
     return entryStack;
 }
__mlibc_entry()
void __mlibc_entry (int(*)(int argc, char *argv[], char *env[]) main_fn)
Definition at line 120 of file entry.cpp.
{
     //mlibc::sys_sigentry((void *)__mlibc_sigentry);
     // TODO: call __dlapi_enter, otherwise static builds will break (see Linux sysdeps)
     auto result = main_fn(__mlibc_stack_data.argc, __mlibc_stack_data.argv, environ);
     exit(result);
 }
References __mlibc_stack_data, mlibc::exec_stack_data::argc, mlibc::exec_stack_data::argv, environ, and exit().
__mlibc_initLocale()
void __mlibc_initLocale ()
Definition at line 74 of file locale-stubs.cpp.
{
     mlibc::collate_facet = &mlibc::c_locale;
     mlibc::ctype_facet = &mlibc::c_locale;
     mlibc::monetary_facet = &mlibc::c_locale;
     mlibc::numeric_facet = &mlibc::c_locale;
     mlibc::time_facet = &mlibc::c_locale;
     mlibc::messages_facet = &mlibc::c_locale;
 }
__mlibc_sigentry()
static void __mlibc_sigentry (int which, siginfo_t * siginfo, void(*)(int, siginfo_t *, void *) sa, GPRState * ret_context, sigset_t prev_mask) static
Definition at line 80 of file entry.cpp.
{
 /*
     size_t *base_ptr = (size_t *)ret_context->rbp;
     mlibc::infoLogger() << "Stacktrace:" << frg::endlog;
     mlibc::infoLogger() << "  [" << (void *)ret_context->rip << "]" << frg::endlog;
     for (;;) {
         size_t old_bp = base_ptr[0];
         size_t ret_addr = base_ptr[1];
         if (!ret_addr)
             break;
         size_t off;
         mlibc::infoLogger() << "  [" << (void *)ret_addr << "]" << frg::endlog;
         if (!old_bp)
             break;
         base_ptr = (size_t *)old_bp;
     }
 */
     switch ((uintptr_t)sa) {
         // DFL
         case (uintptr_t)(-2):
             mlibc::infoLogger() << "mlibc: Unhandled signal " << which << frg::endlog;
             mlibc::sys_exit(128 + which);
         // IGN
         case (uintptr_t)(-3):
             break;
         default:
             sa(which, siginfo, NULL);
             break;
     }
     mlibc::sys_sigreturn(ret_context, prev_mask);
     __builtin_unreachable();
 }
References mlibc::infoLogger, NULL, mlibc::sys_exit(), and mlibc::sys_sigreturn().
Variable Documentation
__mlibc_stack_data
mlibc::exec_stack_data __mlibc_stack_data static
Definition at line 16 of file entry.cpp.
Referenced by __mlibc_entry().
environ
char** environ extern
Definition at line 42 of file lib.c.
guard
LibraryGuard guard static
Definition at line 22 of file entry.cpp.