Fennix Kernel: Kernel/core/panic/diag.cpp File Reference
diag.cpp File Reference
#include <display.hpp>
#include <bitmap.hpp>
#include <convert.h>
#include <printf.h>
#include <lock.hpp>
#include <rand.hpp>
#include <uart.hpp>
#include <time.hpp>
#include <debug.h>
#include <smp.hpp>
#include <cpu.hpp>
#include <io.h>
#include "../../kernel.h"
#include "keyboard.hpp"
Data Structures
struct DiagnosticFile
Functions
void ExPrint (const char *Format,...)
void DisplayTopOverlay ()
nsa bool WriteDiagDataToNode (vfs::RefNode *refFile)
nsa void DiagnosticDataCollection ()
Variables
Video::Font * CrashFont
CPU::ExceptionFrame * ExFrame
Function Documentation
DiagnosticDataCollection()
nsa void DiagnosticDataCollection ()
Definition at line 106 of file diag.cpp.
 {
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\n\eFAFAFAPlease wait while we collect some diagnostic information...\n");
     ExPrint("This may take a while...\n");
     vfs::Node *panicDir = fs->CreateIfNotExists("/var/panic", vfs::DIRECTORY);
     if (!panicDir)
     {
         ExPrint("\eFF0000Failed to create /var/panic\n");
         Display->UpdateBuffer();
         return;
     }
     Time::Clock clock = Time::ReadClock();
     char filename[64];
     for (int i = 0; i < INT32_MAX; i++)
     {
         sprintf(filename, "dump-%d-%d-%d-%d.dmp",
                 clock.Year, clock.Month, clock.Day, i);
         if (fs->PathExists(filename, panicDir))
             continue;
         fs->Create(filename, vfs::FILE, panicDir);
         break;
     }
     vfs::RefNode *refFile = fs->Open(filename, panicDir);
     if (!WriteDiagDataToNode(refFile))
     {
         delete refFile;
         return;
     }
     ExPrint("You can find the diagnostic file in /var/panic/%s\n", filename);
     Display->UpdateBuffer();
     delete refFile;
 }
References Video::Display::ClearBuffer(), vfs::Virtual::Create(), vfs::Virtual::CreateIfNotExists(), Time::Clock::Day, vfs::DIRECTORY, Display, DisplayTopOverlay(), ExPrint(), vfs::FILE, fs, INT32_MAX, Time::Clock::Month, vfs::Virtual::Open(), vfs::Virtual::PathExists(), Time::ReadClock(), sprintf(), Video::Display::UpdateBuffer(), WriteDiagDataToNode(), and Time::Clock::Year.
Referenced by UserInput().
DisplayTopOverlay()
void DisplayTopOverlay ()
Definition at line 176 of file ui.cpp.
 {
     Video::Font *f = Display->GetCurrentFont();
     Video::FontInfo fi = f->GetInfo();
     for (uint32_t i = 0; i < Display->GetWidth; i++)
     {
         for (uint32_t j = 0; j < fi.Height + 8; j++)
         {
             // uint32_t grayValue = 0x505050 - (j * 0x020202);
             // Display->SetPixel(i, j, grayValue);
             Display->SetPixel(i, j, 0x202020);
         }
     }
     for (uint32_t i = 0; i < Display->GetWidth; i++)
         Display->SetPixel(i, fi.Height + 8, 0x404040);
     Display->SetBufferCursor(8, (fi.Height + 8) / 6);
     /* This wouldn't have enough space for a 640x480 screen */
     // ExPrint("%sMAIN %sDETAILS %sSTACK %sPROCESS \eAAAAAA| ",
     //      ActiveScreen == 0 ? "\e00AAFF" : "\eAAAAAA",
     //      ActiveScreen == 1 ? "\e00AAFF" : "\eAAAAAA",
     //      ActiveScreen == 2 ? "\e00AAFF" : "\eAAAAAA",
     //      ActiveScreen == 3 ? "\e00AAFF" : "\eAAAAAA");
     ExPrint("%s %s %s %s \eAAAAAA| ",
             ActiveScreen == 0 ? "\eAAAAAA"
                                 "MAIN   "
                               : "\e5A5A5A"
                                 "M",
             ActiveScreen == 1 ? "\eAAAAAA"
                                 "DETAIL "
                               : "\e5A5A5A"
                                 "D",
             ActiveScreen == 2 ? "\eAAAAAA"
                                 "STACK  "
                               : "\e5A5A5A"
                                 "S",
             ActiveScreen == 3 ? "\eAAAAAA"
                                 "PROCESS"
                               : "\e5A5A5A"
                                 "P");
     ExPrint("%s %s %s | ", KERNEL_NAME, KERNEL_ARCH, KERNEL_VERSION);
     ExPrint("%ld | ", TO_MiB(KernelAllocator.GetFreeMemory()));
     ExPrint("%s %s", CPU::Hypervisor(), CPU::Vendor());
     Display->SetBufferCursor(0, fi.Height + 10);
     /* https://imgflip.com/i/77slbl */
     if ((Random::rand32() % 100) >= 98)
     {
         debug("Easter egg activated!");
         int BaseXOffset = Display->GetWidth - 14;
         int BaseYOffset = 8;
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 8, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 2, 0xFFFFFF);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 2, 0x000000);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 2, 0xFFFFFF);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 2, 0x000000);
         Display->SetPixel(BaseXOffset + 8, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 0, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 0, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 0, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 6, 0x1216FF);
         Display->UpdateBuffer();
     }
 }
References ActiveScreen, debug, Display, ExPrint(), Video::Display::GetCurrentFont(), Video::Font::GetInfo(), Video::Display::GetWidth, Video::FontInfo::Height, CPU::Hypervisor(), KernelAllocator, Random::rand32(), Video::Display::SetBufferCursor(), Video::Display::SetPixel(), TO_MiB, Video::Display::UpdateBuffer(), and CPU::Vendor().
Referenced by ArrowInput(), DiagnosticDataCollection(), DisplayAssertionFailed(), DisplayBufferOverflow(), DisplayCrashScreen(), DisplayStackSmashing(), and UserInput().
ExPrint()
void ExPrint (const char * Format, ...)
Definition at line 54 of file handler.cpp.
 {
     va_list args;
     va_start(args, Format);
     vfctprintf(__printfWrapper, NULL, Format, args);
     va_end(args);
 }
References __printfWrapper(), NULL, va_end, va_start, and vfctprintf().
Referenced by DiagnosticDataCollection(), and WriteDiagDataToNode().
WriteDiagDataToNode()
nsa bool WriteDiagDataToNode (vfs::RefNode * refFile)
Definition at line 68 of file diag.cpp.
 {
     uintptr_t KStart = (uintptr_t)&_kernel_start;
     uintptr_t kEnd = (uintptr_t)&_kernel_end;
     size_t kSize = kEnd - KStart;
     size_t fileSize = sizeof(DiagnosticFile) + kSize;
     uint8_t *buf = (uint8_t *)KernelAllocator.RequestPages(TO_PAGES(fileSize));
     if (!buf)
     {
         ExPrint("\eFF0000Failed to allocate memory for diagnostic data\n");
         Display->UpdateBuffer();
         return false;
     }
     DiagnosticFile *file = (DiagnosticFile *)buf;
     file->Header = {};
     file->Header.Length = uint32_t(fileSize);
     file->Header.Is64Bit = sizeof(void *) == 8;
     file->Data.Frame = *ExFrame;
     file->Data.KernelMemoryLength = uint32_t(kSize);
     memcpy(file->Data.KernelMemory, (void *)KStart, kSize);
     ExPrint("\eFAFAFAWriting to %s\n", refFile->node->FullPath);
     size_t w = refFile->write(buf, fileSize);
     if (w != fileSize)
     {
         debug("%d out of %d bytes written", w, fileSize);
         ExPrint("\eFF0000Failed to write diagnostic data to file: %s\n",
                 strerror((int)w));
         Display->UpdateBuffer();
         return false;
     }
     return true;
 }
References _kernel_end, _kernel_start, DiagnosticFile::Data, debug, Display, ExFrame, ExPrint(), DiagnosticFile::Header, KernelAllocator, memcpy(), vfs::RefNode::node, strerror(), TO_PAGES, Video::Display::UpdateBuffer(), and vfs::RefNode::write().
Referenced by DiagnosticDataCollection().
Variable Documentation
CrashFont
Video::Font* CrashFont extern
Definition at line 47 of file handler.cpp.
ExFrame
CPU::ExceptionFrame* ExFrame extern
Definition at line 597 of file ui.cpp.
Referenced by ArrowInput(), DisplayCrashScreen(), UserInput(), and WriteDiagDataToNode().