Fennix Kernel: CPU::x86::Intel::CPUID0x00000001 Struct Reference
CPU::x86::Intel::CPUID0x00000001 Struct Reference
Additional CPU information.
#include <cpuid_intel.hpp>
Public Member Functions
__always_inline void Get ()
Data Fields
union {
struct {
uint32_t Stepping: 4
uint32_t Model: 4
uint32_t Family: 4
uint32_t ProcessorType: 2
Processor Type.
uint32_t Reserved0: 2
uint32_t ExtendedModel: 4
uint32_t ExtendedFamily: 8
uint32_t Reserved1: 4
}
cpuid_t raw
} EAX
union {
struct {
uint32_t BrandIndex: 8
uint32_t CLFLUSHLineSize: 8
uint32_t LogicalProcessorsPerPackage: 8
uint32_t DefaultAPICID: 8
}
cpuid_t raw
} EBX
union {
struct {
uint32_t SSE3: 1
uint32_t PCLMULDQ: 1
uint32_t DTES64: 1
uint32_t MONITOR: 1
uint32_t DS_CPL: 1
uint32_t VMX: 1
uint32_t SMX: 1
uint32_t EIST: 1
uint32_t TM2: 1
uint32_t SSSE3: 1
uint32_t CNXT_ID: 1
uint32_t Reserved0: 1
uint32_t FMA: 1
uint32_t CX16: 1
uint32_t xTPR: 1
uint32_t PDCM: 1
uint32_t Reserved1: 1
uint32_t PCID: 1
uint32_t DCA: 1
uint32_t SSE4_1: 1
uint32_t SSE4_2: 1
uint32_t x2APIC: 1
uint32_t MOVBE: 1
uint32_t POPCNT: 1
uint32_t TSC_DEADLINE: 1
uint32_t AES: 1
uint32_t XSAVE: 1
uint32_t OSXSAVE: 1
uint32_t AVX: 1
uint32_t F16C: 1
uint32_t RDRAND: 1
uint32_t Hypervisor: 1
}
cpuid_t raw
} ECX
union {
struct {
uint32_t FPU: 1
uint32_t VME: 1
uint32_t DE: 1
uint32_t PSE: 1
uint32_t TSC: 1
uint32_t MSR: 1
uint32_t PAE: 1
uint32_t MCE: 1
uint32_t CX8: 1
uint32_t APIC: 1
uint32_t Reserved0: 1
uint32_t SEP: 1
uint32_t MTRR: 1
uint32_t PGE: 1
uint32_t MCA: 1
uint32_t CMOV: 1
uint32_t PAT: 1
uint32_t PSE36: 1
uint32_t PSN: 1
uint32_t CLFSH: 1
uint32_t Reserved1: 1
uint32_t DS: 1
uint32_t ACPI: 1
uint32_t MMX: 1
uint32_t FXSR: 1
uint32_t SSE: 1
uint32_t SSE2: 1
uint32_t SS: 1
uint32_t HTT: 1
uint32_t TM: 1
uint32_t Reserved2: 1
uint32_t PBE: 1
}
cpuid_t raw
} EDX
Detailed Description
Additional CPU information.
Definition at line 85 of file cpuid_intel.hpp.
Member Function Documentation
Get()
__always_inline void CPU::x86::Intel::CPUID0x00000001::Get () inline
Definition at line 87 of file cpuid_intel.hpp.
                 {
 #if defined(a86)
                     asmv("cpuid"
                          : "=a"(EAX.raw), "=b"(EBX.raw), "=c"(ECX.raw), "=d"(EDX.raw)
                          : "a"(0x1));
 #endif // a64 || a32
                 }
References asmv(), EAX, EBX, ECX, and EDX.
Referenced by DetectByCPUID(), and CPU::InitializeFeatures().
Field Documentation
union { ... } CPU::x86::Intel::CPUID0x00000001::EAX
Referenced by Get().
union { ... } CPU::x86::Intel::CPUID0x00000001::EBX
Referenced by Get().
union { ... } CPU::x86::Intel::CPUID0x00000001::ECX
Referenced by DetectByCPUID(), and Get().
union { ... } CPU::x86::Intel::CPUID0x00000001::EDX
Referenced by Get(), and CPU::InitializeFeatures().
The documentation for this struct was generated from the following file:
Kernel/include/cpu/x86/cpuid_intel.hpp