Fennix Kernel: Kernel/syscalls/native/readlink.cpp File Reference
readlink.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <utsname.h>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
Functions
ssize_t sys_readlink (SysFrm *, const char *path, char *buf, size_t bufsize)
Function Documentation
sys_readlink()
ssize_t sys_readlink (SysFrm * , const char * path, char * buf, size_t bufsize)
Definition at line 34 of file readlink.cpp.
 {
     if (!path || !buf)
         return -EINVAL;
     if (bufsize > PAGE_SIZE)
     {
         warn("bufsize is too large: %ld", bufsize);
         return -EINVAL;
     }
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)buf, Memory::US))
     {
         warn("Invalid address %#lx", buf);
         return -EFAULT;
     }
     const char *pPath = pcb->PageTable->Get(path);
     char *pBuf = pcb->PageTable->Get(buf);
     function("%s %#lx %ld", pPath, buf, bufsize);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_open(pPath, O_RDONLY, 0);
     if (fd < 0)
         return -ENOENT;
     vfs::FileDescriptorTable::Fildes fildes = fdt->GetDescriptor(fd);
     vfs::Node *node = fildes.Handle->node;
     fdt->_close(fd);
     if (node->Type != vfs::NodeType::SYMLINK)
         return -EINVAL;
     if (!node->Symlink)
     {
         warn("Symlink null for \"%s\"?", pPath);
         return -EINVAL;
     }
     size_t len = strlen(node->Symlink);
     if (len > bufsize)
         len = bufsize;
     strncpy(pBuf, node->Symlink, len);
     return len;
 }
References vfs::FileDescriptorTable::_close(), vfs::FileDescriptorTable::_open(), Memory::Virtual::Check(), EFAULT, EINVAL, ENOENT, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), vfs::FileDescriptorTable::GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, len, vfs::RefNode::node, O_RDONLY, PAGE_SIZE, Tasking::PCB::PageTable, strlen(), strncpy(), vfs::SYMLINK, vfs::Node::Symlink, thisProcess, vfs::Node::Type, Memory::US, and warn.