Fennix Userspace: Userspace/mlibc/tests/rtdl/dl_iterate_phdr/test.c File Reference
test.c File Reference
#include <assert.h>
#include <link.h>
#include <string.h>
#include <dlfcn.h>
#include <stdio.h>
Data Structures
struct result
Macros
#define LDSO_PATTERN "ld.so"
#define LIBFOO "libfoo.so"
#define LIBBAR "libbar.so"
Functions
static int ends_with (const char *suffix, const char *s)
static int contains (const char *pattern, const char *s)
static int callback (struct dl_phdr_info *info, size_t size, void *data)
int main ()
Data Structure Documentation
result
struct result
Definition at line 17 of file test.c.
Data Fields
int found_bar
int found_foo
int found_ldso
int found_self
Macro Definition Documentation
LDSO_PATTERN
#define LDSO_PATTERN "ld.so"
Definition at line 12 of file test.c.
LIBBAR
#define LIBBAR "libbar.so"
Definition at line 14 of file test.c.
LIBFOO
#define LIBFOO "libfoo.so"
Definition at line 13 of file test.c.
Function Documentation
callback()
static int callback (struct dl_phdr_info * info, size_t size, void * data) static
Definition at line 38 of file test.c.
{
     assert(size == sizeof(struct dl_phdr_info));
     struct result *found = (struct result *) data;
     printf("%s\n", info->dlpi_name);
     fflush(stdout);
     if (ends_with("foo.so", info->dlpi_name))
         found->found_foo++;
     if (ends_with("bar.so", info->dlpi_name))
         found->found_bar++;
     if (contains(LDSO_PATTERN, info->dlpi_name))
         found->found_ldso++;
     if (!strcmp("", info->dlpi_name))
         found->found_self++;
     assert(info->dlpi_phdr);
     return 0;
 }
References assert, contains(), dl_phdr_info::dlpi_name, ends_with(), fflush(), result::found_bar, result::found_foo, result::found_ldso, result::found_self, LDSO_PATTERN, printf(), size, stdout, and strcmp().
Referenced by __dlapi_iterate_phdr(), D_StartNetGame(), dl_iterate_phdr(), main(), ST_loadUnloadGraphics(), and WI_loadUnloadData().
contains()
static int contains (const char * pattern, const char * s) static
Definition at line 34 of file test.c.
{
     return !!strstr(s, pattern);
 }
References strstr().
Referenced by callback().
ends_with()
static int ends_with (const char * suffix, const char * s) static
Definition at line 24 of file test.c.
{
     size_t suffix_len = strlen(suffix);
     size_t s_len = strlen(s);
     if (s_len < suffix_len)
         return 0;
     else {
         return !strcmp(suffix, s + s_len - suffix_len);
     }
 }
References strcmp(), and strlen().
Referenced by callback().
main()
int main (void)
Definition at line 59 of file test.c.
            {
     struct result found = { 0 };
     assert(!dl_iterate_phdr(callback, &found));
     assert(found.found_ldso == 1);
     assert(found.found_self == 1);
     assert(found.found_foo == 0);
     assert(found.found_bar == 0);
     printf("---\n");
     memset(&found, 0, sizeof(found));
     void *bar = dlopen(LIBBAR, RTLD_LOCAL | RTLD_NOW);
     assert(bar);
     assert(!dl_iterate_phdr(callback, &found));
     assert(found.found_ldso == 1);
     assert(found.found_self == 1);
     assert(found.found_bar == 1);
     assert(found.found_foo == 1); // Since bar depends on foo.
     printf("---\n");
     memset(&found, 0, sizeof(found));
     void *foo = dlopen(LIBFOO, RTLD_GLOBAL | RTLD_NOW);
     assert(foo);
     assert(!dl_iterate_phdr(callback, &found));
     assert(found.found_ldso == 1);
     assert(found.found_self == 1);
     assert(found.found_foo == 1);
     assert(found.found_bar == 1);
     printf("---\n");
     dlclose(bar);
     dlclose(foo);
     return 0;
 }
References assert, bar(), callback(), dl_iterate_phdr(), dlclose(), dlopen(), foo(), result::found_bar, result::found_foo, result::found_ldso, result::found_self, LIBBAR, LIBFOO, memset(), printf(), RTLD_GLOBAL, RTLD_LOCAL, and RTLD_NOW.