Fennix: Userspace/apps/base/busybox/networking/ipcalc.c File Reference
ipcalc.c File Reference
#include "libbb.h"
#include <arpa/inet.h>
Macros
#define CLASS_A_NETMASK ntohl(0xFF000000)
#define CLASS_B_NETMASK ntohl(0xFFFF0000)
#define CLASS_C_NETMASK ntohl(0xFFFFFF00)
#define NETMASK 0x01
#define BROADCAST 0x02
#define NETWORK 0x04
#define NETPREFIX 0x08
#define HOSTNAME 0x10
#define SILENT 0x20
#define GETOPT32 getopt32
#define LONGOPTS
#define netmask (s_netmask.s_addr)
#define broadcast (s_broadcast.s_addr)
#define network (s_network.s_addr)
#define ipaddr (s_ipaddr.s_addr)
Functions
static unsigned long get_netmask (unsigned long ipaddr)
int get_prefix (unsigned long netmask)
int ipcalc_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BROADCAST
#define BROADCAST 0x02
Definition at line 94 of file ipcalc.c.
broadcast
#define broadcast (s_broadcast.s_addr)
CLASS_A_NETMASK
#define CLASS_A_NETMASK ntohl(0xFF000000)
Definition at line 56 of file ipcalc.c.
CLASS_B_NETMASK
#define CLASS_B_NETMASK ntohl(0xFFFF0000)
Definition at line 57 of file ipcalc.c.
CLASS_C_NETMASK
#define CLASS_C_NETMASK ntohl(0xFFFFFF00)
Definition at line 58 of file ipcalc.c.
GETOPT32
#define GETOPT32 getopt32
Definition at line 114 of file ipcalc.c.
HOSTNAME
#define HOSTNAME 0x10
Definition at line 97 of file ipcalc.c.
ipaddr
#define ipaddr (s_ipaddr.s_addr)
LONGOPTS
#define LONGOPTS
Definition at line 115 of file ipcalc.c.
NETMASK
#define NETMASK 0x01
Definition at line 93 of file ipcalc.c.
netmask
#define netmask (s_netmask.s_addr)
NETPREFIX
#define NETPREFIX 0x08
Definition at line 96 of file ipcalc.c.
NETWORK
#define NETWORK 0x04
Definition at line 95 of file ipcalc.c.
network
#define network (s_network.s_addr)
SILENT
#define SILENT 0x20
Definition at line 98 of file ipcalc.c.
Function Documentation
get_netmask()
static unsigned long get_netmask (unsigned long ipaddr) static
Definition at line 60 of file ipcalc.c.
 {
     ipaddr = htonl(ipaddr);
     if ((ipaddr & 0xC0000000) == 0xC0000000)
         return CLASS_C_NETMASK;
     else if ((ipaddr & 0x80000000) == 0x80000000)
         return CLASS_B_NETMASK;
     else if ((ipaddr & 0x80000000) == 0)
         return CLASS_A_NETMASK;
     else
         return 0;
 }
References CLASS_A_NETMASK, CLASS_B_NETMASK, CLASS_C_NETMASK, htonl(), and ipaddr.
Referenced by ipcalc_main().
get_prefix()
int get_prefix (unsigned long netmask)
Referenced by ipaddr_list_or_flush(), ipaddr_modify(), ipcalc_main(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), iproute_modify(), and iprule_modify().
ipcalc_main()
int ipcalc_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 119 of file ipcalc.c.
 {
     unsigned opt;
     bool have_netmask = 0;
     struct in_addr s_netmask, s_broadcast, s_network, s_ipaddr;
     /* struct in_addr { in_addr_t s_addr; }  and  in_addr_t
      * (which in turn is just a typedef to uint32_t)
      * are essentially the same type. A few macros for less verbosity: */
 #define netmask   (s_netmask.s_addr)
 #define broadcast (s_broadcast.s_addr)
 #define network   (s_network.s_addr)
 #define ipaddr    (s_ipaddr.s_addr)
     char *ipstr;
     opt = GETOPT32(argv, "^"
             "mbn" IF_FEATURE_IPCALC_FANCY("phs")
             "\0" "-1:?2"/*min 1, max 2 args*/
             LONGOPTS
     );
     argv += optind;
     if (opt & SILENT)
         logmode = LOGMODE_NONE; /* suppress error_msg() output */
     opt &= ~SILENT;
     if (!(opt & (BROADCAST | NETWORK | NETPREFIX))) {
         /* if no options at all or
          * (no broadcast,network,prefix) and (two args)... */
         if (!opt || argv[1])
             bb_show_usage();
     }
     ipstr = argv[0];
     if (ENABLE_FEATURE_IPCALC_FANCY) {
         unsigned long netprefix = 0;
         char *prefixstr;
         prefixstr = ipstr;
         while (*prefixstr) {
             if (*prefixstr == '/') {
                 *prefixstr++ = '\0';
                 if (*prefixstr) {
                     unsigned msk;
                     netprefix = xatoul_range(prefixstr, 0, 32);
                     netmask = 0;
                     msk = 0x80000000;
                     while (netprefix > 0) {
                         netmask |= msk;
                         msk >>= 1;
                         netprefix--;
                     }
                     netmask = htonl(netmask);
                     /* Even if it was 0, we will signify that we have a netmask. This allows */
                     /* for specification of default routes, etc which have a 0 netmask/prefix */
                     have_netmask = 1;
                 }
                 break;
             }
             prefixstr++;
         }
     }
     if (inet_aton(ipstr, &s_ipaddr) == 0) {
         bb_error_msg_and_die("bad IP address: %s", argv[0]);
     }
     if (argv[1]) {
         if (ENABLE_FEATURE_IPCALC_FANCY && have_netmask) {
             bb_simple_error_msg_and_die("use prefix or netmask, not both");
         }
         if (inet_aton(argv[1], &s_netmask) == 0) {
             bb_error_msg_and_die("bad netmask: %s", argv[1]);
         }
     } else {
         /* JHC - If the netmask wasn't provided then calculate it */
         if (!ENABLE_FEATURE_IPCALC_FANCY || !have_netmask)
             netmask = get_netmask(ipaddr);
     }
     if (opt & NETMASK) {
         printf("NETMASK=%s\n", inet_ntoa(s_netmask));
     }
     if (opt & BROADCAST) {
         broadcast = (ipaddr & netmask) | ~netmask;
         printf("BROADCAST=%s\n", inet_ntoa(s_broadcast));
     }
     if (opt & NETWORK) {
         network = ipaddr & netmask;
         printf("NETWORK=%s\n", inet_ntoa(s_network));
     }
     if (ENABLE_FEATURE_IPCALC_FANCY) {
         if (opt & NETPREFIX) {
             printf("PREFIX=%i\n", get_prefix(netmask));
         }
         if (opt & HOSTNAME) {
             struct hostent *hostinfo;
             hostinfo = gethostbyaddr((char *) &ipaddr, sizeof(ipaddr), AF_INET);
             if (!hostinfo) {
                 bb_herror_msg_and_die("can't find hostname for %s", argv[0]);
             }
             str_tolower(hostinfo->h_name);
             printf("HOSTNAME=%s\n", hostinfo->h_name);
         }
     }
     return EXIT_SUCCESS;
 }
References AF_INET, argv, bb_error_msg_and_die(), bb_herror_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), BROADCAST, broadcast, EXIT_SUCCESS, get_netmask(), get_prefix(), gethostbyaddr(), GETOPT32, hostent::h_name, HOSTNAME, htonl(), inet_aton(), inet_ntoa(), ipaddr, logmode, LOGMODE_NONE, LONGOPTS, NETMASK, netmask, NETPREFIX, NETWORK, network, opt, optind, printf, SILENT, and str_tolower().