Fennix Userspace: Userspace/apps/base/busybox/networking/tls_pstm_montgomery_reduce.c File Reference
tls_pstm_montgomery_reduce.c File Reference
#include "tls.h"
Macros
#define MONT_START
#define MONT_FINI
#define LOOP_END
#define LOOP_START mu = c[x] * mp
#define INNERMUL
#define PROPCARRY do { pstm_digit t = _c[0] += cy; cy = (t < cy); } while (0)
#define LO 0
Functions
int32 FAST_FUNC pstm_montgomery_reduce (psPool_t *pool, pstm_int *a, pstm_int *m, pstm_digit mp, pstm_digit *paD, uint32 paDlen)
Macro Definition Documentation
INNERMUL
#define INNERMUL
Value:
    do { pstm_word t;                                   \
        t = ((pstm_word)_c[0] + (pstm_word)cy) +        \
            (((pstm_word)mu) * ((pstm_word)*tmpm++));   \
        _c[0] = (pstm_digit)t;                          \
        cy = (pstm_digit)(t >> DIGIT_BIT);              \
    } while (0)
Definition at line 349 of file tls_pstm_montgomery_reduce.c.
LO
#define LO 0
Definition at line 364 of file tls_pstm_montgomery_reduce.c.
LOOP_END
#define LOOP_END
Definition at line 345 of file tls_pstm_montgomery_reduce.c.
LOOP_START
#define LOOP_START mu = c[x] * mp
Definition at line 346 of file tls_pstm_montgomery_reduce.c.
MONT_FINI
#define MONT_FINI
Definition at line 344 of file tls_pstm_montgomery_reduce.c.
MONT_START
#define MONT_START
Definition at line 343 of file tls_pstm_montgomery_reduce.c.
PROPCARRY
#define PROPCARRY do { pstm_digit t = _c[0] += cy; cy = (t < cy); } while (0)
Definition at line 357 of file tls_pstm_montgomery_reduce.c.
Function Documentation
pstm_montgomery_reduce()
int32 FAST_FUNC pstm_montgomery_reduce (psPool_t * pool, pstm_int * a, pstm_int * m, pstm_digit mp, pstm_digit * paD, uint32 paDlen)
Definition at line 367 of file tls_pstm_montgomery_reduce.c.
 {
     pstm_digit  *c, *_c, *tmpm, mu;
     int32       oldused, x, y;
     int     pa; //bbox: was int16
     pa = m->used;
     if (pa > a->alloc) {
         /* Sanity test for bad numbers.  This will confirm no buffer overruns */
         return PS_LIMIT_FAIL;
     }
     if (paD && paDlen >= (uint32)2*pa+1) {
         c = paD;
         memset(c, 0x0, paDlen);
     } else {
         c = xzalloc(2*pa+1);//bbox
     }
     /* copy the input */
     oldused = a->used;
     for (x = 0; x < oldused; x++) {
         c[x] = a->dp[x];
     }
     MONT_START;
     for (x = 0; x < pa; x++) {
         pstm_digit cy = 0;
         /* get Mu for this round */
         LOOP_START;
         _c   = c + x;
         tmpm = m->dp;
         y = 0;
 #ifdef PSTM_X86_64
         for (; y < (pa & ~7); y += 8) {
             INNERMUL8;
             _c   += 8;
             tmpm += 8;
         }
 #endif /* PSTM_X86_64 */
         for (; y < pa; y++) {
             INNERMUL;
             ++_c;
         }
         LOOP_END;
         while (cy) {
             PROPCARRY;
             ++_c;
         }
     }
     /* now copy out */
     _c   = c + pa;
     tmpm = a->dp;
     for (x = 0; x < pa+1; x++) {
         *tmpm++ = *_c++;
     }
     for (; x < oldused; x++)   {
         *tmpm++ = 0;
     }
     MONT_FINI;
     a->used = pa+1;
     pstm_clamp(a);
     /* reuse x as return code */
     x = PSTM_OKAY;
     /* if A >= m then A = A - m */
     if (pstm_cmp_mag (a, m) != PSTM_LT) {
         if (s_pstm_sub (a, m, a) != PSTM_OKAY) {
             x = PS_MEM_FAIL;
         }
     }
     if (paDlen < (uint32)2*pa+1) {
         psFree(c, pool);
     }
     return x;
 }
References pstm_int::alloc, c, pstm_int::dp, INNERMUL, LOOP_END, LOOP_START, memset(), MONT_FINI, MONT_START, PROPCARRY, PS_LIMIT_FAIL, PS_MEM_FAIL, psFree, pstm_clamp(), pstm_cmp_mag(), PSTM_LT, PSTM_OKAY, s_pstm_sub(), pstm_int::used, x, xzalloc(), and y.