Fennix Userspace: Userspace/apps/base/busybox/procps/mpstat.c File Reference
mpstat.c File Reference
#include "libbb.h"
#include <sys/utsname.h>
Data Structures
struct stats_irqcpu
struct stats_cpu
struct stats_irq
struct globals
Macros
#define debug(fmt, ...) ((void)0)
#define INTERRUPTS_LINE 64
#define NR_IRQS 256
#define NR_IRQCPU_PREALLOC 3
#define MAX_IRQNAME_LEN 16
#define MAX_PF_NAME 512
#define INTRATE_SCRWIDTH 10
#define INTRATE_SCRWIDTH_STR "10"
#define PROCFS_STAT "/proc/stat"
#define PROCFS_INTERRUPTS "/proc/interrupts"
#define PROCFS_SOFTIRQS "/proc/softirqs"
#define PROCFS_UPTIME "/proc/uptime"
#define FMT_DATA "ll"
#define DATA_MAX ULLONG_MAX
#define G (*ptr_to_globals)
#define INIT_G()
Typedefs
typedef unsigned long long data_t
typedef long long idata_t
Enumerations
enum { D_CPU = 1 << 0 , D_IRQ_SUM = 1 << 1 , D_IRQ_CPU = 1 << 2 , D_SOFTIRQS = 1 << 3 }
Functions
static ALWAYS_INLINE int display_opt (int opt)
static ALWAYS_INLINE data_t overflow_safe_sub (data_t prev, data_t curr)
static double percent_value (data_t prev, data_t curr, data_t itv)
static double hz_value (data_t prev, data_t curr, data_t itv)
static ALWAYS_INLINE data_t jiffies_diff (data_t old, data_t new)
static int is_cpu_in_bitmap (unsigned cpu)
static void write_irqcpu_stats (struct stats_irqcpu *per_cpu_stats[], int total_irqs, data_t itv, int prev, int current, const char *prev_str, const char *current_str)
static data_t get_per_cpu_interval (const struct stats_cpu *scc, const struct stats_cpu *scp)
static void print_stats_cpu_struct (const struct stats_cpu *p, const struct stats_cpu *c, data_t itv)
static void write_stats_core (int prev, int current, const char *prev_str, const char *current_str)
static void write_stats (int current)
static void write_stats_avg (int current)
static void get_cpu_statistics (struct stats_cpu *cpu, data_t *up, data_t *up0)
static void get_irqs_from_stat (struct stats_irq *irq)
static void get_irqs_from_interrupts (const char *fname, struct stats_irqcpu *per_cpu_stats[], int irqs_per_cpu, int current)
static void get_uptime (data_t *uptime)
static void get_localtime (struct tm *tm)
static void alarm_handler (int sig UNUSED_PARAM)
static void main_loop (void)
static void alloc_struct (int cpus)
static void print_header (struct tm *t)
static int get_irqcpu_nr (const char *f, int max_irqs)
int mpstat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
stats_irqcpu
struct stats_irqcpu
Definition at line 62 of file mpstat.c.
Data Fields
unsigned interrupts
char irq_name[MAX_IRQNAME_LEN]
stats_cpu
struct stats_cpu
Definition at line 67 of file mpstat.c.
Data Fields
data_t cpu_guest
data_t cpu_idle
data_t cpu_iowait
data_t cpu_irq
data_t cpu_nice
data_t cpu_softirq
data_t cpu_steal
data_t cpu_system
data_t cpu_user
stats_irq
struct stats_irq
Definition at line 79 of file mpstat.c.
Data Fields
data_t irq_nr
Macro Definition Documentation
DATA_MAX
#define DATA_MAX ULLONG_MAX
Definition at line 53 of file mpstat.c.
debug
#define debug (fmt, ...) ((void)0)
Definition at line 24 of file mpstat.c.
FMT_DATA
#define FMT_DATA "ll"
Definition at line 52 of file mpstat.c.
G
#define G (*ptr_to_globals)
Definition at line 107 of file mpstat.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 108 of file mpstat.c.
INTERRUPTS_LINE
#define INTERRUPTS_LINE 64
Definition at line 27 of file mpstat.c.
INTRATE_SCRWIDTH
#define INTRATE_SCRWIDTH 10
Definition at line 39 of file mpstat.c.
INTRATE_SCRWIDTH_STR
#define INTRATE_SCRWIDTH_STR "10"
Definition at line 40 of file mpstat.c.
MAX_IRQNAME_LEN
#define MAX_IRQNAME_LEN 16
Definition at line 31 of file mpstat.c.
MAX_PF_NAME
#define MAX_PF_NAME 512
Definition at line 32 of file mpstat.c.
NR_IRQCPU_PREALLOC
#define NR_IRQCPU_PREALLOC 3
Definition at line 30 of file mpstat.c.
NR_IRQS
#define NR_IRQS 256
Definition at line 29 of file mpstat.c.
PROCFS_INTERRUPTS
#define PROCFS_INTERRUPTS "/proc/interrupts"
Definition at line 44 of file mpstat.c.
PROCFS_SOFTIRQS
#define PROCFS_SOFTIRQS "/proc/softirqs"
Definition at line 45 of file mpstat.c.
PROCFS_STAT
#define PROCFS_STAT "/proc/stat"
Definition at line 43 of file mpstat.c.
PROCFS_UPTIME
#define PROCFS_UPTIME "/proc/uptime"
Definition at line 46 of file mpstat.c.
Typedef Documentation
data_t
typedef unsigned long long data_t
Definition at line 50 of file mpstat.c.
idata_t
typedef long long idata_t
Definition at line 51 of file mpstat.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
D_CPU
D_IRQ_SUM
D_IRQ_CPU
D_SOFTIRQS
Definition at line 113 of file mpstat.c.
      {
     D_CPU      = 1 << 0,
     D_IRQ_SUM  = 1 << 1,
     D_IRQ_CPU  = 1 << 2,
     D_SOFTIRQS = 1 << 3,
 };
Function Documentation
alarm_handler()
static void alarm_handler (int sig UNUSED_PARAM) static
Definition at line 662 of file mpstat.c.
 {
     signal(SIGALRM, alarm_handler);
     alarm(G.interval);
 }
References alarm(), G, SIGALRM, and signal.
Referenced by main_loop().
alloc_struct()
static void alloc_struct (int cpus) static
Definition at line 774 of file mpstat.c.
 {
     int i;
     for (i = 0; i < 3; i++) {
         G.st_cpu[i] = xzalloc(sizeof(G.st_cpu[i][0]) * cpus);
         G.st_irq[i] = xzalloc(sizeof(G.st_irq[i][0]) * cpus);
         G.st_irqcpu[i] = xzalloc(sizeof(G.st_irqcpu[i][0]) * cpus * G.irqcpu_nr);
         G.st_softirqcpu[i] = xzalloc(sizeof(G.st_softirqcpu[i][0]) * cpus * G.softirqcpu_nr);
     }
     G.cpu_bitmap_len = (cpus >> 3) + 1;
     G.cpu_bitmap = xzalloc(G.cpu_bitmap_len);
 }
References G, i, and xzalloc().
Referenced by mpstat_main().
display_opt()
static ALWAYS_INLINE int display_opt (int opt) static
Definition at line 122 of file mpstat.c.
 {
     return (opt & G.options);
 }
References G, and opt.
Referenced by main_loop(), and write_stats_core().
get_cpu_statistics()
static void get_cpu_statistics (struct stats_cpu * cpu, data_t * up, data_t * up0) static
Definition at line 456 of file mpstat.c.
 {
     FILE *fp;
     char buf[1024];
     fp = xfopen_for_read(PROCFS_STAT);
     while (fgets(buf, sizeof(buf), fp)) {
         data_t sum;
         unsigned cpu_number;
         struct stats_cpu *cp;
         if (!starts_with_cpu(buf))
             continue; /* not "cpu" */
         cp = cpu; /* for "cpu " case */
         if (buf[3] != ' ') {
             /* "cpuN " */
             if (G.cpu_nr == 0
              || sscanf(buf + 3, "%u ", &cpu_number) != 1
              || cpu_number >= G.cpu_nr
             ) {
                 continue;
             }
             cp = &cpu[cpu_number + 1];
         }
         /* Read the counters, save them */
         /* Not all fields have to be present */
         memset(cp, 0, sizeof(*cp));
         sscanf(buf, "%*s"
             " %"FMT_DATA"u %"FMT_DATA"u %"FMT_DATA"u"
             " %"FMT_DATA"u %"FMT_DATA"u %"FMT_DATA"u"
             " %"FMT_DATA"u %"FMT_DATA"u %"FMT_DATA"u",
             &cp->cpu_user, &cp->cpu_nice, &cp->cpu_system,
             &cp->cpu_idle, &cp->cpu_iowait, &cp->cpu_irq,
             &cp->cpu_softirq, &cp->cpu_steal, &cp->cpu_guest
         );
         /*
          * Compute uptime in jiffies (1/HZ), it'll be the sum of
          * individual CPU's uptimes.
          * NB: We have to omit cpu_guest, because cpu_user includes it.
          */
         sum = cp->cpu_user + cp->cpu_nice + cp->cpu_system +
             cp->cpu_idle + cp->cpu_iowait + cp->cpu_irq +
             cp->cpu_softirq + cp->cpu_steal;
         if (buf[3] == ' ') {
             /* "cpu " */
             *up = sum;
         } else {
             /* "cpuN " */
             if (cpu_number == 0 && *up0 != 0) {
                 /* Compute uptime of single CPU */
                 *up0 = sum;
             }
         }
     }
     fclose(fp);
 }
References buf, stats_cpu::cpu_guest, stats_cpu::cpu_idle, stats_cpu::cpu_iowait, stats_cpu::cpu_irq, stats_cpu::cpu_nice, stats_cpu::cpu_softirq, stats_cpu::cpu_steal, stats_cpu::cpu_system, stats_cpu::cpu_user, fclose(), fgets, FMT_DATA, G, memset(), PROCFS_STAT, sscanf(), starts_with_cpu(), up, and xfopen_for_read().
Referenced by main_loop().
get_irqcpu_nr()
static int get_irqcpu_nr (const char * f, int max_irqs) static
Definition at line 804 of file mpstat.c.
 {
     FILE *fp;
     char *line;
     unsigned linelen;
     unsigned irq;
     fp = fopen_for_read(f);
     if (!fp)  /* No interrupts file */
         return 0;
     linelen = INTERRUPTS_LINE + 16 * G.cpu_nr;
     line = xmalloc(linelen);
     irq = 0;
     while (fgets(line, linelen, fp)
      && irq < max_irqs
     ) {
         int p = strcspn(line, ":");
         if ((p > 0) && (p < 16))
             irq++;
     }
     fclose(fp);
     free(line);
     return irq;
 }
References f, fclose(), fgets, fopen_for_read(), free, G, INTERRUPTS_LINE, line, linelen, p, strcspn(), and xmalloc.
Referenced by mpstat_main().
get_irqs_from_interrupts()
static void get_irqs_from_interrupts (const char * fname, struct stats_irqcpu * per_cpu_stats[], int irqs_per_cpu, int current) static
Definition at line 541 of file mpstat.c.
 {
     FILE *fp;
     struct stats_irq *irq_i;
     struct stats_irqcpu *ic;
     char *buf;
     unsigned buflen;
     unsigned cpu;
     unsigned irq;
     int cpu_index[G.cpu_nr];
     int iindex;
 // Moved to caller.
 // Otherwise reading of /proc/softirqs
 // was resetting counts to 0 after we painstakingly collected them from
 // /proc/interrupts. Which resulted in:
 // 01:32:47 PM  CPU    intr/s
 // 01:32:47 PM  all    591.47
 // 01:32:47 PM    0      0.00 <= ???
 // 01:32:47 PM    1      0.00 <= ???
 //  for (cpu = 1; cpu <= G.cpu_nr; cpu++) {
 //      G.st_irq[current][cpu].irq_nr = 0;
 //      //bb_error_msg("G.st_irq[%u][%u].irq_nr=0", current, cpu);
 //  }
     fp = fopen_for_read(fname);
     if (!fp)
         return;
     buflen = INTERRUPTS_LINE + 16 * G.cpu_nr;
     buf = xmalloc(buflen);
     /* Parse header and determine, which CPUs are online */
     iindex = 0;
     while (fgets(buf, buflen, fp)) {
         char *cp, *next;
         next = buf;
         while ((cp = strstr(next, "CPU")) != NULL
          && iindex < G.cpu_nr
         ) {
             cpu = strtoul(cp + 3, &next, 10);
             cpu_index[iindex++] = cpu;
         }
         if (iindex) /* We found header */
             break;
     }
     irq = 0;
     while (fgets(buf, buflen, fp)
      && irq < irqs_per_cpu
     ) {
         int len;
         char last_char;
         char *cp;
         /* Skip over "IRQNAME:" */
         cp = strchr(buf, ':');
         if (!cp)
             continue;
         last_char = cp[-1];
         ic = &per_cpu_stats[current][irq];
         len = cp - buf;
         if (len >= sizeof(ic->irq_name)) {
             len = sizeof(ic->irq_name) - 1;
         }
         safe_strncpy(ic->irq_name, buf, len + 1);
         //bb_error_msg("%s: irq%d:'%s' buf:'%s'", fname, irq, ic->irq_name, buf);
         cp++;
         for (cpu = 0; cpu < iindex; cpu++) {
             char *next;
             ic = &per_cpu_stats[current][cpu_index[cpu] * irqs_per_cpu + irq];
             irq_i = &G.st_irq[current][cpu_index[cpu] + 1];
             ic->interrupts = strtoul(cp, &next, 10);
             /* Count only numerical IRQs */
             if (isdigit(last_char)) {
                 irq_i->irq_nr += ic->interrupts;
                 //bb_error_msg("G.st_irq[%u][%u].irq_nr + %u = %lld",
                 // current, cpu_index[cpu] + 1, ic->interrupts, irq_i->irq_nr);
             }
             cp = next;
         }
         irq++;
     }
     fclose(fp);
     free(buf);
     while (irq < irqs_per_cpu) {
         /* Number of interrupts per CPU has changed */
         ic = &per_cpu_stats[current][irq];
         ic->irq_name[0] = '\0'; /* False interrupt */
         irq++;
     }
 }
References buf, buflen, current, fclose(), fgets, fname, fopen_for_read(), free, G, stats_irqcpu::interrupts, INTERRUPTS_LINE, stats_irqcpu::irq_name, stats_irq::irq_nr, isdigit, next, NULL, safe_strncpy(), strchr(), strstr(), strtoul(), and xmalloc.
Referenced by main_loop().
get_irqs_from_stat()
static void get_irqs_from_stat (struct stats_irq * irq) static
Definition at line 520 of file mpstat.c.
 {
     FILE *fp;
     char buf[1024];
     fp = xfopen_for_read(PROCFS_STAT);
     while (fgets(buf, sizeof(buf), fp)) {
         //bb_error_msg("/proc/stat:'%s'", buf);
         if (is_prefixed_with(buf, "intr ")) {
             /* Read total number of IRQs since system boot */
             sscanf(buf + 5, "%"FMT_DATA"u", &irq->irq_nr);
         }
     }
     fclose(fp);
 }
References buf, fclose(), fgets, FMT_DATA, stats_irq::irq_nr, is_prefixed_with(), PROCFS_STAT, sscanf(), and xfopen_for_read().
Referenced by main_loop().
get_localtime()
static void get_localtime (struct tm * tm) static
Definition at line 655 of file mpstat.c.
 {
     time_t timer;
     time(&timer);
     localtime_r(&timer, tm);
 }
References time().
Referenced by main_loop(), and mpstat_main().
get_per_cpu_interval()
static data_t get_per_cpu_interval (const struct stats_cpu * scc, const struct stats_cpu * scp) static
Definition at line 277 of file mpstat.c.
 {
     return ((scc->cpu_user + scc->cpu_nice +
          scc->cpu_system + scc->cpu_iowait +
          scc->cpu_idle + scc->cpu_steal +
          scc->cpu_irq + scc->cpu_softirq) -
         (scp->cpu_user + scp->cpu_nice +
          scp->cpu_system + scp->cpu_iowait +
          scp->cpu_idle + scp->cpu_steal +
          scp->cpu_irq + scp->cpu_softirq));
 }
References stats_cpu::cpu_idle, stats_cpu::cpu_iowait, stats_cpu::cpu_irq, stats_cpu::cpu_nice, stats_cpu::cpu_softirq, stats_cpu::cpu_steal, stats_cpu::cpu_system, and stats_cpu::cpu_user.
Referenced by write_stats_core().
get_uptime()
static void get_uptime (data_t * uptime) static
Definition at line 639 of file mpstat.c.
 {
     FILE *fp;
     char buf[sizeof(long)*3 * 2 + 4]; /* enough for long.long */
     unsigned long uptime_sec, decimal;
     fp = xfopen_for_read(PROCFS_UPTIME);
     if (fgets(buf, sizeof(buf), fp)) {
         if (sscanf(buf, "%lu.%lu", &uptime_sec, &decimal) == 2) {
             *uptime = (data_t)uptime_sec * G.hz + decimal * G.hz / 100;
         }
     }
     fclose(fp);
 }
References buf, fclose(), fgets, G, PROCFS_UPTIME, sscanf(), and xfopen_for_read().
Referenced by main_loop(), and ps_main().
hz_value()
static double hz_value (data_t prev, data_t curr, data_t itv) static
Definition at line 158 of file mpstat.c.
 {
     //bb_error_msg("curr:%lld prev:%lld G.hz:%u", curr, prev, G.hz);
     return ((double)overflow_safe_sub(prev, curr)) / itv * G.hz;
 }
References G, and overflow_safe_sub().
Referenced by write_stats_core().
is_cpu_in_bitmap()
static int is_cpu_in_bitmap (unsigned cpu) static
Definition at line 170 of file mpstat.c.
 {
     return G.cpu_bitmap[cpu >> 3] & (1 << (cpu & 7));
 }
References G.
Referenced by write_irqcpu_stats(), and write_stats_core().
jiffies_diff()
static ALWAYS_INLINE data_t jiffies_diff (data_t old, data_t new) static
Definition at line 164 of file mpstat.c.
 {
     data_t diff = new - old;
     return (diff == 0) ? 1 : diff;
 }
References diff(), and old.
Referenced by write_stats_core().
main_loop()
static void main_loop (void) static
Definition at line 668 of file mpstat.c.
 {
     unsigned current;
     unsigned cpus;
     /* Read the stats */
     if (G.cpu_nr > 1) {
         G.per_cpu_uptime[0] = 0;
         get_uptime(&G.per_cpu_uptime[0]);
     }
     get_cpu_statistics(G.st_cpu[0], &G.global_uptime[0], &G.per_cpu_uptime[0]);
     if (display_opt(D_IRQ_SUM))
         get_irqs_from_stat(G.st_irq[0]);
     if (display_opt(D_IRQ_SUM | D_IRQ_CPU))
         get_irqs_from_interrupts(PROCFS_INTERRUPTS, G.st_irqcpu,
                     G.irqcpu_nr, 0);
     if (display_opt(D_SOFTIRQS))
         get_irqs_from_interrupts(PROCFS_SOFTIRQS, G.st_softirqcpu,
                     G.softirqcpu_nr, 0);
     if (G.interval == 0) {
         /* Display since boot time */
         cpus = G.cpu_nr + 1;
         G.timestamp[1] = G.timestamp[0];
         memset(G.st_cpu[1], 0, sizeof(G.st_cpu[1][0]) * cpus);
         memset(G.st_irq[1], 0, sizeof(G.st_irq[1][0]) * cpus);
         memset(G.st_irqcpu[1], 0, sizeof(G.st_irqcpu[1][0]) * cpus * G.irqcpu_nr);
         memset(G.st_softirqcpu[1], 0, sizeof(G.st_softirqcpu[1][0]) * cpus * G.softirqcpu_nr);
         write_stats(0);
         /* And we're done */
         return;
     }
     /* Set a handler for SIGALRM */
     alarm_handler(0);
     /* Save the stats we already have. We need them to compute the average */
     G.timestamp[2] = G.timestamp[0];
     G.global_uptime[2] = G.global_uptime[0];
     G.per_cpu_uptime[2] = G.per_cpu_uptime[0];
     cpus = G.cpu_nr + 1;
     memcpy(G.st_cpu[2], G.st_cpu[0], sizeof(G.st_cpu[0][0]) * cpus);
     memcpy(G.st_irq[2], G.st_irq[0], sizeof(G.st_irq[0][0]) * cpus);
     memcpy(G.st_irqcpu[2], G.st_irqcpu[0], sizeof(G.st_irqcpu[0][0]) * cpus * G.irqcpu_nr);
     if (display_opt(D_SOFTIRQS)) {
         memcpy(G.st_softirqcpu[2], G.st_softirqcpu[0],
             sizeof(G.st_softirqcpu[0][0]) * cpus * G.softirqcpu_nr);
     }
     current = 1;
     while (1) {
         /* Suspend until a signal is received */
         pause();
         /* Set structures to 0 to distinguish off/online CPUs */
         memset(&G.st_cpu[current][/*cpu:*/ 1], 0, sizeof(G.st_cpu[0][0]) * G.cpu_nr);
         get_localtime(&G.timestamp[current]);
         /* Read stats */
         if (G.cpu_nr > 1) {
             G.per_cpu_uptime[current] = 0;
             get_uptime(&G.per_cpu_uptime[current]);
         }
         get_cpu_statistics(G.st_cpu[current], &G.global_uptime[current], &G.per_cpu_uptime[current]);
         if (display_opt(D_IRQ_SUM))
             get_irqs_from_stat(G.st_irq[current]);
         if (display_opt(D_IRQ_SUM | D_IRQ_CPU)) {
             int cpu;
             for (cpu = 1; cpu <= G.cpu_nr; cpu++) {
                 G.st_irq[current][cpu].irq_nr = 0;
             }
             /* accumulates .irq_nr */
             get_irqs_from_interrupts(PROCFS_INTERRUPTS, G.st_irqcpu,
                     G.irqcpu_nr, current);
         }
         if (display_opt(D_SOFTIRQS))
             get_irqs_from_interrupts(PROCFS_SOFTIRQS,
                     G.st_softirqcpu,
                     G.softirqcpu_nr, current);
         write_stats(current);
         if (G.count > 0) {
             if (--G.count == 0)
                 break;
         }
         current ^= 1;
     }
     /* Print average statistics */
     write_stats_avg(current);
 }
References alarm_handler(), current, D_IRQ_CPU, D_IRQ_SUM, D_SOFTIRQS, display_opt(), G, get_cpu_statistics(), get_irqs_from_interrupts(), get_irqs_from_stat(), get_localtime(), get_uptime(), memcpy(), memset(), pause(), PROCFS_INTERRUPTS, PROCFS_SOFTIRQS, write_stats(), and write_stats_avg().
Referenced by mpstat_main().
mpstat_main()
int mpstat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 843 of file mpstat.c.
 {
     char *opt_irq_fmt;
     char *opt_set_cpu;
     int i, opt;
     enum {
         OPT_ALL    = 1 << 0, /* -A */
         OPT_INTS   = 1 << 1, /* -I */
         OPT_SETCPU = 1 << 2, /* -P */
         OPT_UTIL   = 1 << 3, /* -u */
     };
     /* Dont buffer data if redirected to a pipe */
     setbuf(stdout, NULL);
     INIT_G();
     G.interval = -1;
     /* Get number of processors */
     G.cpu_nr = get_cpu_count();
     /* Get number of clock ticks per sec */
     G.hz = bb_clk_tck();
     /* Calculate number of interrupts per processor */
     G.irqcpu_nr = get_irqcpu_nr(PROCFS_INTERRUPTS, NR_IRQS) + NR_IRQCPU_PREALLOC;
     /* Calculate number of soft interrupts per processor */
     G.softirqcpu_nr = get_irqcpu_nr(PROCFS_SOFTIRQS, NR_IRQS) + NR_IRQCPU_PREALLOC;
     /* Allocate space for structures. + 1 for global structure. */
     alloc_struct(G.cpu_nr + 1);
     /* Parse and process arguments */
     opt = getopt32(argv, "AI:P:u", &opt_irq_fmt, &opt_set_cpu);
     argv += optind;
     if (*argv) {
         /* Get interval */
         G.interval = xatoi_positive(*argv);
         G.count = -1;
         argv++;
         if (*argv) {
             /* Get count value */
             if (G.interval == 0)
                 bb_show_usage();
             G.count = xatoi_positive(*argv);
             //if (*++argv)
             //  bb_show_usage();
         }
     }
     if (G.interval < 0)
         G.interval = 0;
     if (opt & OPT_ALL) {
         G.p_option = 1;
         G.options |= D_CPU + D_IRQ_SUM + D_IRQ_CPU + D_SOFTIRQS;
         /* Select every CPU */
         memset(G.cpu_bitmap, 0xff, G.cpu_bitmap_len);
     }
     if (opt & OPT_INTS) {
         static const char v[] = {
             D_IRQ_CPU, D_IRQ_SUM, D_SOFTIRQS,
             D_IRQ_SUM + D_IRQ_CPU + D_SOFTIRQS
         };
         i = index_in_strings("CPU\0SUM\0SCPU\0ALL\0", opt_irq_fmt);
         if (i == -1)
             bb_show_usage();
         G.options |= v[i];
     }
     if ((opt & OPT_UTIL) /* -u? */
      || G.options == 0  /* nothing? (use default then) */
     ) {
         G.options |= D_CPU;
     }
     if (opt & OPT_SETCPU) {
         char *t;
         G.p_option = 1;
         for (t = strtok_r(opt_set_cpu, ",", &opt_set_cpu); t; t = strtok_r(NULL, ",", &opt_set_cpu)) {
             if (strcmp(t, "ALL") == 0) {
                 /* Select every CPU */
                 memset(G.cpu_bitmap, 0xff, G.cpu_bitmap_len);
             } else {
                 /* Get CPU number */
                 unsigned n = xatoi_positive(t);
                 if (n >= G.cpu_nr)
                     bb_simple_error_msg_and_die("not that many processors");
                 n++;
                 G.cpu_bitmap[n >> 3] |= 1 << (n & 7);
             }
         }
     }
     if (!G.p_option)
         /* Display global stats */
         G.cpu_bitmap[0] = 1;
     /* Get time */
     get_localtime(&G.timestamp[0]);
     /* Display header */
     print_header(&G.timestamp[0]);
     /* The main loop */
     main_loop();
     if (ENABLE_FEATURE_CLEAN_UP) {
         /* Clean up */
         for (i = 0; i < 3; i++) {
             free(G.st_cpu[i]);
             free(G.st_irq[i]);
             free(G.st_irqcpu[i]);
             free(G.st_softirqcpu[i]);
         }
         free(G.cpu_bitmap);
         free(&G);
     }
     return EXIT_SUCCESS;
 }
References alloc_struct(), argv, bb_clk_tck(), bb_show_usage(), bb_simple_error_msg_and_die(), D_CPU, D_IRQ_CPU, D_IRQ_SUM, D_SOFTIRQS, EXIT_SUCCESS, free, G, get_cpu_count(), get_irqcpu_nr(), get_localtime(), getopt32(), i, index_in_strings(), INIT_G, main_loop(), memset(), n, NR_IRQCPU_PREALLOC, NR_IRQS, NULL, opt, OPT_ALL, optind, print_header(), PROCFS_INTERRUPTS, PROCFS_SOFTIRQS, setbuf(), stdout, strcmp, strtok_r(), t, and xatoi_positive().
overflow_safe_sub()
static ALWAYS_INLINE data_t overflow_safe_sub (data_t prev, data_t curr) static
Definition at line 147 of file mpstat.c.
 {
     return curr - prev;
 }
Referenced by hz_value(), and percent_value().
percent_value()
static double percent_value (data_t prev, data_t curr, data_t itv) static
Definition at line 153 of file mpstat.c.
 {
     return ((double)overflow_safe_sub(prev, curr)) / itv * 100;
 }
References overflow_safe_sub().
Referenced by print_stats_cpu_struct().
print_header()
static void print_header (struct tm * t) static
Definition at line 787 of file mpstat.c.
 {
     char cur_date[16];
     struct utsname uts;
     /* Get system name, release number and hostname */
     uname(&uts);
     strftime(cur_date, sizeof(cur_date), "%x", t);
     printf("%s %s (%s)\t%s\t_%s_\t(%u CPU)\n",
         uts.sysname, uts.release, uts.nodename, cur_date, uts.machine, G.cpu_nr);
 }
References G, utsname::machine, utsname::nodename, printf(), utsname::release, strftime(), utsname::sysname, t, and uname().
Referenced by mpstat_main().
print_stats_cpu_struct()
static void print_stats_cpu_struct (const struct stats_cpu * p, const struct stats_cpu * c, data_t itv) static
Definition at line 290 of file mpstat.c.
 {
     printf(" %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f\n",
         percent_value(p->cpu_user - p->cpu_guest,
                                   c->cpu_user - c->cpu_guest, itv),
         percent_value(p->cpu_nice   , c->cpu_nice   , itv),
         percent_value(p->cpu_system , c->cpu_system , itv),
         percent_value(p->cpu_iowait , c->cpu_iowait , itv),
         percent_value(p->cpu_irq    , c->cpu_irq    , itv),
         percent_value(p->cpu_softirq, c->cpu_softirq, itv),
         percent_value(p->cpu_steal  , c->cpu_steal  , itv),
         percent_value(p->cpu_guest  , c->cpu_guest  , itv),
         percent_value(p->cpu_idle   , c->cpu_idle   , itv)
     );
 }
References c, p, percent_value(), and printf().
Referenced by write_stats_core().
write_irqcpu_stats()
static void write_irqcpu_stats (struct stats_irqcpu * per_cpu_stats[], int total_irqs, data_t itv, int prev, int current, const char * prev_str, const char * current_str) static
Definition at line 175 of file mpstat.c.
 {
     int j;
     int offset, cpu;
     struct stats_irqcpu *p0, *q0;
     /* Check if number of IRQs has changed */
     if (G.interval != 0) {
         for (j = 0; j <= total_irqs; j++) {
             p0 = &per_cpu_stats[current][j];
             if (p0->irq_name[0] != '\0') {
                 q0 = &per_cpu_stats[prev][j];
                 if (strcmp(p0->irq_name, q0->irq_name) != 0) {
                     /* Strings are different */
                     break;
                 }
             }
         }
     }
     /* Print header */
     printf("\n%-11s  CPU", prev_str);
     {
         /* A bit complex code to "buy back" space if one header is too wide.
          * Here's how it looks like. BLOCK_IOPOLL eats too much space,
          * and latter headers use smaller width to compensate:
          * ...BLOCK/s BLOCK_IOPOLL/s TASKLET/s SCHED/s HRTIMER/s  RCU/s
          * ...   2.32      0.00      0.01     17.58      0.14    141.96
          */
         int expected_len = 0;
         int printed_len = 0;
         for (j = 0; j < total_irqs; j++) {
             p0 = &per_cpu_stats[current][j];
             if (p0->irq_name[0] != '\0') {
                 int n = (INTRATE_SCRWIDTH-3) - (printed_len - expected_len);
                 printed_len += printf(" %*s/s", n > 0 ? n : 0, skip_whitespace(p0->irq_name));
                 expected_len += INTRATE_SCRWIDTH;
             }
         }
     }
     bb_putchar('\n');
     for (cpu = 1; cpu <= G.cpu_nr; cpu++) {
         /* Check if we want stats about this CPU */
         if (!is_cpu_in_bitmap(cpu) && G.p_option) {
             continue;
         }
         printf("%-11s %4u", current_str, cpu - 1);
         for (j = 0; j < total_irqs; j++) {
             /* IRQ field set only for proc 0 */
             p0 = &per_cpu_stats[current][j];
             /*
              * An empty string for irq name means that
              * interrupt is no longer used.
              */
             if (p0->irq_name[0] != '\0') {
                 offset = j;
                 q0 = &per_cpu_stats[prev][offset];
                 /*
                  * If we want stats for the time since boot
                  * we have p0->irq != q0->irq.
                  */
                 if (strcmp(p0->irq_name, q0->irq_name) != 0
                  && G.interval != 0
                 ) {
                     if (j) {
                         offset = j - 1;
                         q0 = &per_cpu_stats[prev][offset];
                     }
                     if (strcmp(p0->irq_name, q0->irq_name) != 0
                      && (j + 1 < total_irqs)
                     ) {
                         offset = j + 1;
                         q0 = &per_cpu_stats[prev][offset];
                     }
                 }
                 if (strcmp(p0->irq_name, q0->irq_name) == 0
                  || G.interval == 0
                 ) {
                     struct stats_irqcpu *p, *q;
                     p = &per_cpu_stats[current][(cpu - 1) * total_irqs + j];
                     q = &per_cpu_stats[prev][(cpu - 1) * total_irqs + offset];
                     printf("%"INTRATE_SCRWIDTH_STR".2f",
                         (double)(p->interrupts - q->interrupts) / itv * G.hz);
                 } else {
                     printf("        N/A");
                 }
             }
         }
         bb_putchar('\n');
     }
 }
References bb_putchar(), current, G, stats_irqcpu::interrupts, INTRATE_SCRWIDTH, INTRATE_SCRWIDTH_STR, stats_irqcpu::irq_name, is_cpu_in_bitmap(), j, n, offset, p, printf(), skip_whitespace(), and strcmp.
Referenced by write_stats_core().
write_stats()
static void write_stats (int current) static
Definition at line 437 of file mpstat.c.
 {
     char prev_time[16];
     char curr_time[16];
     strftime(prev_time, sizeof(prev_time), "%X", &G.timestamp[!current]);
     strftime(curr_time, sizeof(curr_time), "%X", &G.timestamp[current]);
     write_stats_core(!current, current, prev_time, curr_time);
 }
References current, G, strftime(), and write_stats_core().
Referenced by main_loop().
write_stats_avg()
static void write_stats_avg (int current) static
Definition at line 448 of file mpstat.c.
 {
     write_stats_core(2, current, "Average:", "Average:");
 }
References current, and write_stats_core().
Referenced by main_loop().
write_stats_core()
static void write_stats_core (int prev, int current, const char * prev_str, const char * current_str) static
This is done exactly once *‍/
Print average header, this is done exactly once *‍/
Definition at line 308 of file mpstat.c.
 {
     struct stats_cpu *scc, *scp;
     data_t itv, global_itv;
     int cpu;
     /* Compute time interval */
     itv = global_itv = jiffies_diff(G.global_uptime[prev], G.global_uptime[current]);
     /* Reduce interval to one CPU */
     if (G.cpu_nr > 1)
         itv = jiffies_diff(G.per_cpu_uptime[prev], G.per_cpu_uptime[current]);
     /* Print CPU stats */
     if (display_opt(D_CPU)) {
         //if (!G.header_done) {
             printf("\n%-11s  CPU    %%usr   %%nice    %%sys %%iowait    %%irq   %%soft  %%steal  %%guest   %%idle\n",
                 prev_str
             );
         //  G.header_done = 1;
         //}
         for (cpu = 0; cpu <= G.cpu_nr; cpu++) {
             data_t per_cpu_itv;
             /* Print stats about this particular CPU? */
             if (!is_cpu_in_bitmap(cpu))
                 continue;
             scc = &G.st_cpu[current][cpu];
             scp = &G.st_cpu[prev][cpu];
             per_cpu_itv = global_itv;
             printf((cpu ? "%-11s %4u" : "%-11s  all"), current_str, cpu - 1);
             if (cpu) {
                 double idle;
                 /*
                  * If the CPU is offline, then it isn't in /proc/stat,
                  * so all values are 0.
                  * NB: Guest time is already included in user time.
                  */
                 if ((scc->cpu_user | scc->cpu_nice | scc->cpu_system |
                      scc->cpu_iowait | scc->cpu_idle | scc->cpu_steal |
                      scc->cpu_irq | scc->cpu_softirq) == 0
                 ) {
                     /*
                      * Set current struct fields to values from prev.
                      * iteration. Then their values won't jump from
                      * zero, when the CPU comes back online.
                      */
                     *scc = *scp;
                     idle = 0.0;
                     goto print_zeros;
                 }
                 /* Compute interval again for current proc */
                 per_cpu_itv = get_per_cpu_interval(scc, scp);
                 if (per_cpu_itv == 0) {
                     /*
                      * If the CPU is tickless then there is no change in CPU values
                      * but the sum of values is not zero.
                      */
                     idle = 100.0;
  print_zeros:
                     printf(" %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f\n",
                         0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, idle);
                     continue;
                 }
             }
             print_stats_cpu_struct(scp, scc, per_cpu_itv);
         }
     }
     /* Print total number of IRQs per CPU */
     if (display_opt(D_IRQ_SUM)) {
         //if (!G.avg_header_done) {
             printf("\n%-11s  CPU    intr/s\n", prev_str);
         //  G.avg_header_done = 1;
         //}
         for (cpu = 0; cpu <= G.cpu_nr; cpu++) {
             data_t per_cpu_itv;
             /* Print stats about this CPU? */
             if (!is_cpu_in_bitmap(cpu))
                 continue;
             per_cpu_itv = itv;
             printf((cpu ? "%-11s %4u" : "%-11s  all"), current_str, cpu - 1);
             if (cpu) {
                 scc = &G.st_cpu[current][cpu];
                 scp = &G.st_cpu[prev][cpu];
                 /* Compute interval again for current proc */
                 per_cpu_itv = get_per_cpu_interval(scc, scp);
                 if (per_cpu_itv == 0) {
                     printf(" %9.2f\n", 0.0);
                     continue;
                 }
             }
             //bb_error_msg("G.st_irq[%u][%u].irq_nr:%lld - G.st_irq[%u][%u].irq_nr:%lld",
             // current, cpu, G.st_irq[prev][cpu].irq_nr, prev, cpu, G.st_irq[current][cpu].irq_nr);
             printf(" %9.2f\n", hz_value(G.st_irq[prev][cpu].irq_nr, G.st_irq[current][cpu].irq_nr, per_cpu_itv));
         }
     }
     if (display_opt(D_IRQ_CPU)) {
         write_irqcpu_stats(G.st_irqcpu, G.irqcpu_nr,
                 itv,
                 prev, current,
                 prev_str, current_str
         );
     }
     if (display_opt(D_SOFTIRQS)) {
         write_irqcpu_stats(G.st_softirqcpu, G.softirqcpu_nr,
                 itv,
                 prev, current,
                 prev_str, current_str
         );
     }
 }
References stats_cpu::cpu_idle, stats_cpu::cpu_iowait, stats_cpu::cpu_irq, stats_cpu::cpu_nice, stats_cpu::cpu_softirq, stats_cpu::cpu_steal, stats_cpu::cpu_system, stats_cpu::cpu_user, current, D_CPU, D_IRQ_CPU, D_IRQ_SUM, D_SOFTIRQS, display_opt(), G, get_per_cpu_interval(), hz_value(), is_cpu_in_bitmap(), jiffies_diff(), print_stats_cpu_struct(), printf(), and write_irqcpu_stats().
Referenced by write_stats(), and write_stats_avg().