Fennix Userspace: Userspace/musl/include/string.h File Reference
string.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define NULL ((void*)0)
#define __NEED_size_t
Functions
void * memcpy (void *__restrict, const void *__restrict, size_t)
void * memmove (void *, const void *, size_t)
void * memset (void *, int, size_t)
int memcmp (const void *, const void *, size_t)
void * memchr (const void *, int, size_t)
char * strcpy (char *__restrict, const char *__restrict)
char * strncpy (char *__restrict, const char *__restrict, size_t)
char * strcat (char *__restrict, const char *__restrict)
char * strncat (char *__restrict, const char *__restrict, size_t)
int strcmp (const char *, const char *)
int strncmp (const char *, const char *, size_t)
int strcoll (const char *, const char *)
size_t strxfrm (char *__restrict, const char *__restrict, size_t)
char * strchr (const char *, int)
char * strrchr (const char *, int)
size_t strcspn (const char *, const char *)
size_t strspn (const char *, const char *)
char * strpbrk (const char *, const char *)
char * strstr (const char *, const char *)
char * strtok (char *__restrict, const char *__restrict)
size_t strlen (const char *)
char * strerror (int)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 18 of file string.h.
NULL
#define NULL ((void*)0)
Definition at line 15 of file string.h.
Function Documentation
memchr()
void* memchr (const void * s, int c, size_t size)
Definition at line 109 of file string-stubs.cpp.
{
     auto s_bytes = static_cast<const unsigned char *>(s);
     for(size_t i = 0; i < size; i++)
         if(s_bytes[i] == static_cast<unsigned char>(c))
             return const_cast<unsigned char *>(s_bytes + i);
     return nullptr;
 }
References __attribute__, ALIGN, c, HASZERO, i, k, n, ONES, size, and SS.
Referenced by dcngettext(), fgetln(), fgets(), getdelim(), main(), memmem(), string_read(), strnlen(), twoway_strstr(), we_askshell(), and mlibc::abstract_file::write().
memcmp()
int memcmp (const void * a, const void * b, size_t size)
Definition at line 54 of file string-stubs.cpp.
{
     for(size_t i = 0; i < size; i++) {
         auto a_byte = static_cast<const unsigned char *>(a)[i];
         auto b_byte = static_cast<const unsigned char *>(b)[i];
         if(a_byte < b_byte)
             return -1;
         if(a_byte > b_byte)
             return 1;
     }
     return 0;
 }
References b, i, n, r, and size.
Referenced by __crypt_blowfish(), __crypt_md5(), __crypt_sha256(), __crypt_sha512(), __dls3(), __mkostemps(), __res_msend_rc(), _rl_move_cursor_relative(), bcmp(), do_newlocale(), do_tzset(), getnameinfo(), inet_ntop(), main(), match(), mkdtemp(), mktemp(), netlink_msg_to_nameindex(), policyof(), pthread_setattr_default_np(), reverse_hosts(), test_affinity(), twoway_memmem(), twoway_strstr(), and update_line().
memcpy()
void* memcpy (void * __restrict, const void * __restrict, size_t n)
Definition at line 90 of file fcts.c.
 {
     uint8_t *d = dest;
     const uint8_t *s = src;
     while (n--)
         *d++ = *s++;
     return dest;
 }
References __attribute__, i, n, and x.
Referenced by __attribute__(), __convert_scm_timestamps(), __copy_tls(), __crypt_blowfish(), __execvpe(), __fstat_time32(), __fstatat_time32(), __fwritex(), __get_handler_set(), __get_locale(), __get_resolv_conf(), __init_ssp(), __libc_sigaction(), __lookup_ipliteral(), __lookup_name(), __lstat_time32(), __mkostemps(), __pthread_create(), __putenv(), __res_mkquery(), __res_msend_rc(), __res_send(), __reset_tls(), __shm_mapname(), __stat_time32(), __strftime_l(), __wait3_time32(), __wait4_time32(), _crypt_extended_r_uut(), _nl_find_domain(), _nl_init_domain_conv(), _nl_load_domain(), _nl_make_l10nflist(), _rl_insert_char(), _rl_isearch_dispatch(), accessDtv(), append(), BF_crypt(), bindtextdomain(), catopen(), cht_GetParam(), convert_ioctl_struct(), copy_addr(), copy_lladdr(), cuserid(), cycle(), dn_comp(), dns_parse_callback(), do_glob(), do_relocs(), do_tzset(), ResizePrinter::expand(), expand_prompt(), extend_bfs_deps(), ExtendLumpInfo(), F_TextWrite(), fgets(), fixup_rpath(), fread(), G_DoCompleted(), G_PlayerReborn(), G_Ticker(), get_charset_aliases(), get_random_secret(), getaddrinfo(), getcwd(), getdelim(), getgr_r(), gethostbyaddr_r(), gethostbyname(), gethostbyname2_r(), getnameinfo(), getpw_r(), getrusage(), I_Endoom(), I_FinishUpdate(), I_ReadScreen(), I_Scale1x(), I_Stretch1x(), iconv(), if(), if_nameindex(), ifs_firstchar(), IncreaseDemoBuffer(), indirection_level_string(), inet_pton(), init_yy_io(), initialize_shell_variables(), mlibc::initStackGuard(), initTlsObjects(), install_new_tls(), mlibc::mem_file::io_write(), lcong48(), lio_listio(), load(), load_library(), locale_charset(), long_double_format(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), mlibc::lookup_name_hosts(), mlibc::lookup_name_ip(), mlibc::lookup_name_null(), lsearch(), match_bracket(), md5_update(), md5crypt(), mem_fread(), mem_fwrite(), memmove(), mempcpy(), mk_env_string(), mkdtemp(), mread(), ms_write(), mwrite(), name_from_dns_search(), name_from_hosts(), netlink_msg_to_ifaddr(), netlink_msg_to_nameindex(), nftw(), openlog(), P_SpawnMapThing(), parse_bracket(), parse_bracket_terms(), processCopyRela(), pthread_attr_getaffinity_np(), pthread_attr_setaffinity_np(), R_DrawColumnInCache(), R_FillBackScreen(), R_FlatNumForName(), R_InitSpriteDefs(), R_InitTextures(), R_StoreWallRange(), R_VideoErase(), mlibc::abstract_file::read(), read_alias_file(), readdir(), readdir_r(), realloc(), realpath(), regcomp(), res_querydomain(), restore_parser_state(), reverse_hosts(), reverse_services(), rl_callback_read_char(), rl_change_case(), rl_set_keymap_name(), rl_set_sighandler(), save_parser_state(), scandir(), seed48(), sendmsg(), set_binding_values(), setenv(), setifs(), setlocale(), sh_modcase(), SHA1_Final(), sha256_update(), sha512_update(), anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname(), sn_write(), StatCopy(), stpcpy(), stpncpy(), strdup(), strerror_r(), string_list_dollar_at(), string_list_dollar_star(), string_read(), strndup(), substring(), mlibc::sys_read_entries(), tempnam(), textdomain(), Transform(), TryRunTics(), tzset(), ungetwc(), anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt(), update_line(), V_CopyRect(), V_DrawBlock(), V_DrawRawScreen(), wait4(), wcsnrtombs(), while(), wipe_initColorXForm(), wipe_initMelt(), wipe_shittyColMajorXform(), wmemcpy(), mlibc::abstract_file::write(), and zmapfd().
memmove()
void* memmove (void * dest, const void * src, size_t n)
Definition at line 290 of file memop.c.
 {
 #ifdef __GNUC__
     typedef __attribute__((__may_alias__)) size_t WT;
 #define WS (sizeof(WT))
 #endif
     char *d = dest;
     const char *s = src;
     if (d == s)
         return d;
     if ((uintptr_t)s - (uintptr_t)d - n <= -2 * n)
         return memcpy(d, s, n);
     if (d < s)
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)d % WS)
             {
                 if (!n--)
                     return dest;
                 *d++ = *s++;
             }
             for (; n >= WS; n -= WS, d += WS, s += WS)
                 *(WT *)d = *(WT *)s;
         }
 #endif
         for (; n; n--)
             *d++ = *s++;
     }
     else
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)(d + n) % WS)
             {
                 if (!n--)
                     return dest;
                 d[n] = s[n];
             }
             while (n >= WS)
                 n -= WS, *(WT *)(d + n) = *(WT *)(s + n);
         }
 #endif
         while (n)
             n--, d[n] = s[n];
     }
     return dest;
 }
References i, memcpy(), n, and size.
memset()
void* memset (void * s, int c, size_t n)
Definition at line 99 of file fcts.c.
 {
     uint8_t *p = s;
     while (n--)
         *p++ = c;
 }
References __attribute__, c, count, i, k, n, and p.
strcat()
char* strcat (char * __restrict, const char * __restrict)
strchr()
char* strchr (const char * s, int c)
Definition at line 103 of file string.c.
 {
     size_t len = strlen(s);
     for (size_t i = 0; i < len; i++)
         if (s[i] == c)
             return (char *)s + i;
     return NULL;
 }
References __strchrnul(), c, i, and r.
Referenced by main(), strcspn(), strpbrk(), strspn(), and strtok_r().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 106 of file fcts.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
References b, i, and r.
Referenced by ELFLookupSymbol(), main(), and strcoll().
strcoll()
int strcoll (const char * a, const char * b)
Definition at line 81 of file string-stubs.cpp.
{
     // TODO: strcoll should take "LC_COLLATE" into account.
     return strcmp(a, b);
 }
References __strcoll_l(), b, CURRENT_LOCALE, r, and strcmp().
Referenced by _rl_qsort_string_compare(), alphasort(), binary_test(), compare(), strvec_posixcmp(), and strvec_strcmp().
strcpy()
char* strcpy (char * __restrict, const char * __restrict)
strcspn()
size_t strcspn (const char * s, const char * chrs)
Definition at line 127 of file string-stubs.cpp.
{
     size_t n = 0;
     while(true) {
         if(!s[n] || strchr(chrs, s[n]))
             return n;
         n++;
     }
 }
References __strchrnul(), BITOP, c, memset(), n, and strchr().
Referenced by _nl_init_domain_conv(), catopen(), csvsplit(), dsvsplit(), fcvt(), path_open(), strpbrk(), strsep(), strtok(), and strtok_r().
strerror()
char* strerror (int e)
Definition at line 52 of file strerror.c.
 {
   static char emsg[40];
 #if defined (HAVE_SYS_ERRLIST)
   extern int sys_nerr;
   extern char *sys_errlist[];
   if (e > 0 && e < sys_nerr)
     return (sys_errlist[e]);
   else
 #endif /* HAVE_SYS_ERRLIST */
     {
       char *z;
       z = itos (e);
       strcpy (emsg, errbase);
       strcat (emsg, z);
       free (z);
       return (&emsg[0]);
     }
 }
References __strerror_l(), CURRENT_LOCALE, E2BIG, EACCES, EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, EAGAIN, EALREADY, EBADF, EBADFD, EBADMSG, EBADR, EBADSLT, EBUSY, ECANCELED, ECHILD, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDEADLK, EDESTADDRREQ, EDOM, EDQUOT, EEXIST, EFAULT, EFBIG, EHOSTDOWN, EHOSTUNREACH, EIDRM, EILSEQ, EINPROGRESS, EINTR, EINVAL, EIO, EISCONN, EISDIR, EKEYREJECTED, EKEYREVOKED, ELNRNG, ELOOP, EMEDIUMTYPE, EMFILE, EMLINK, EMSGSIZE, EMULTIHOP, ENAMETOOLONG, ENETDOWN, ENETRESET, ENETUNREACH, ENFILE, ENOANO, ENOBUFS, ENOCSI, ENODATA, ENODEV, ENOENT, ENOEXEC, ENOKEY, ENOLCK, ENOLINK, ENOMEDIUM, ENOMEM, ENOMSG, ENONET, ENOPKG, ENOPROTOOPT, ENOSPC, ENOSTR, ENOSYS, ENOTBLK, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTRECOVERABLE, ENOTSOCK, ENOTSUP, ENOTTY, ENOTUNIQ, ENXIO, EOPNOTSUPP, EOVERFLOW, EOWNERDEAD, EPERM, EPFNOSUPPORT, EPIPE, EPROTO, EPROTONOSUPPORT, EPROTOTYPE, ERANGE, EREMOTE, EREMOTEIO, ERESTART, ERFKILL, EROFS, errbase, ESHUTDOWN, ESOCKTNOSUPPORT, ESPIPE, ESRCH, ESTALE, ESTRPIPE, ETIME, ETIMEDOUT, ETOOMANYREFS, ETXTBSY, EUCLEAN, EUNATCH, EUSERS, EXDEV, EXFULL, free, itos(), sprintf(), strcat(), strcpy(), and sys_nerr.
Referenced by strerror_r().
strlen()
size_t strlen (const char * str)
Definition at line 5 of file string.c.
 {
     long unsigned i = 0;
     if (str)
         while (str[i] != '\0')
             ++i;
     return i;
 }
References __attribute__, ALIGN, HASZERO, and i.
Referenced by strchr(), strdup(), and strrchr().
strncat()
char* strncat (char * __restrict, const char * __restrict, size_t)
strncmp()
int strncmp (const char * s1, const char * s2, size_t n)
Definition at line 21 of file string.c.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
References b, i, max_size, n, and r.
strncpy()
char* strncpy (char * __restrict, const char * __restrict, size_t)
strpbrk()
char* strpbrk (const char * s, const char * accept)
Definition at line 34 of file strpbrk.c.
 {
   while (*s != '\0')
     {
       const char *a = accept;
       while (*a != '\0')
     if (*a++ == *s)
       return (char *) s;
       ++s;
     }
   return 0;
 }
References accept(), b, n, strchr(), and strcspn().
Referenced by fix_assignment_words(), and sleep_builtin().
strrchr()
char* strrchr (const char * s, int c)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
References __memrchr(), c, i, mlibc::length, and strlen().
Referenced by main().
strspn()
size_t strspn (const char * s, const char * chrs)
Definition at line 153 of file string-stubs.cpp.
{
     size_t n = 0;
     while(true) {
         if(!s[n] || !strchr(chrs, s[n]))
             return n;
         n++;
     }
 }
References BITOP, c, n, and strchr().
Referenced by fcvt(), inet_ntop(), long_double_format(), path_open(), strtok(), and strtok_r().
strstr()
char* strstr (const char * phaystack, const char * pneedle)
Definition at line 44 of file strstr.c.
 {
   register const unsigned char *haystack, *needle;
   register chartype b, c;
   haystack = (const unsigned char *) phaystack;
   needle = (const unsigned char *) pneedle;
   b = *needle;
   if (b != '\0')
     {
       haystack--;               /* possible ANSI violation */
       do
     {
       c = *++haystack;
       if (c == '\0')
         goto ret0;
     }
       while (c != b);
       c = *++needle;
       if (c == '\0')
     goto foundneedle;
       ++needle;
       goto jin;
       for (;;)
         {
           register chartype a;
       register const unsigned char *rhaystack, *rneedle;
       do
         {
           a = *++haystack;
           if (a == '\0')
         goto ret0;
           if (a == b)
         break;
           a = *++haystack;
           if (a == '\0')
         goto ret0;
 shloop:;    }
           while (a != b);
 jin:      a = *++haystack;
       if (a == '\0')
         goto ret0;
       if (a != c)
         goto shloop;
       rhaystack = haystack-- + 1;
       rneedle = needle;
       a = *rneedle;
       if (*rhaystack == a)
         do
           {
         if (a == '\0')
           goto foundneedle;
         ++rhaystack;
         a = *++needle;
         if (*rhaystack != a)
           break;
         if (a == '\0')
           goto foundneedle;
         ++rhaystack;
         a = *++needle;
           }
         while (*rhaystack == a);
       needle = rneedle;        /* took the register-poor approach */
       if (a == '\0')
         break;
         }
     }
 foundneedle:
   return (char*) haystack;
 ret0:
   return 0;
 }
References b, c, fourbyte_strstr(), i, j, n, NULL, pattern, strchr(), threebyte_strstr(), twobyte_strstr(), and twoway_strstr().
Referenced by __get_resolv_conf(), __lookup_serv(), _nl_init_domain_conv(), add_links(), contains(), hasmntopt(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), M_StringReplace(), main(), name_from_hosts(), popen(), rl_history_search_internal(), scan_request(), and scan_table().
strtok()
char* strtok (char * __restrict, const char * __restrict)
strxfrm()
size_t strxfrm (char * __restrict, const char * __restrict, size_t)
Definition at line 104 of file string-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.