Fennix Userspace: Userspace/apps/base/busybox/loginutils/cryptpw.c File Reference
cryptpw.c File Reference
#include "libbb.h"
Functions
int cryptpw_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
cryptpw_main()
int cryptpw_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 85 of file cryptpw.c.
 {
     /* Supports: cryptpw -m sha256 PASS 'rounds=999999999$SALT' */
     char salt[MAX_PW_SALT_LEN + sizeof("rounds=999999999$")];
     char *salt_ptr;
     char *password;
     const char *opt_m, *opt_S;
     int fd;
 #if ENABLE_LONG_OPTS
     static const char mkpasswd_longopts[] ALIGN1 =
         "stdin\0"       No_argument       "s"
         "password-fd\0" Required_argument "P"
         "salt\0"        Required_argument "S"
         "method\0"      Required_argument "m"
     ;
 #endif
     fd = STDIN_FILENO;
     opt_m = CONFIG_FEATURE_DEFAULT_PASSWD_ALGO;
     opt_S = NULL;
     /* at most two non-option arguments; -P NUM */
     getopt32long(argv, "^" "sP:+S:m:a:" "\0" "?2",
             mkpasswd_longopts,
             &fd, &opt_S, &opt_m, &opt_m
     );
     argv += optind;
     /* have no idea how to handle -s... */
     if (argv[0] && !opt_S)
         opt_S = argv[1];
     salt_ptr = crypt_make_pw_salt(salt, opt_m);
     if (opt_S)
         /* put user's data after the "$N$" prefix */
         safe_strncpy(salt_ptr, opt_S, sizeof(salt) - (sizeof("$N$")-1));
     xmove_fd(fd, STDIN_FILENO);
     password = argv[0];
     if (!password) {
         /* Only mkpasswd, and only from tty, prompts.
          * Otherwise it is a plain read. */
         password = (ENABLE_MKPASSWD && applet_name[0] == 'm' && isatty(STDIN_FILENO))
             ? bb_ask_noecho_stdin("Password: ")
             : xmalloc_fgetline(stdin)
         ;
         /* may still be NULL on EOF/error */
     }
     if (password)
         puts(pw_encrypt(password, salt, 1));
     return EXIT_SUCCESS;
 }
References ALIGN1, applet_name, argv, bb_ask_noecho_stdin(), crypt_make_pw_salt(), EXIT_SUCCESS, fd, getopt32long, isatty(), MAX_PW_SALT_LEN, No_argument, NULL, optind, password, puts(), pw_encrypt, Required_argument, safe_strncpy(), stdin, STDIN_FILENO, xmalloc_fgetline(), and xmove_fd().