Fennix Userspace: Userspace/musl/src/linux/epoll.c File Reference
epoll.c File Reference
#include <sys/epoll.h>
#include <signal.h>
#include <errno.h>
#include "syscall.h"
Functions
int epoll_create (int size)
int epoll_create1 (int flags)
int epoll_ctl (int fd, int op, int fd2, struct epoll_event *ev)
int epoll_pwait (int fd, struct epoll_event *ev, int cnt, int to, const sigset_t *sigs)
int epoll_wait (int fd, struct epoll_event *ev, int cnt, int to)
Function Documentation
epoll_create()
int epoll_create (int size)
Definition at line 6 of file epoll.c.
 {
     if (size<=0) return __syscall_ret(-EINVAL);
     return epoll_create1(0);
 }
References __syscall_ret(), EINVAL, epoll_create1(), and size.
epoll_create1()
int epoll_create1 (int flags)
Definition at line 12 of file epoll.c.
 {
     int r = __syscall(SYS_epoll_create1, flags);
 #ifdef SYS_epoll_create
     if (r==-ENOSYS && !flags) r = __syscall(SYS_epoll_create, 1);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ENOSYS, and flags.
Referenced by epoll_create().
epoll_ctl()
int epoll_ctl (int fd, int op, int fd2, struct epoll_event * ev)
Definition at line 21 of file epoll.c.
 {
     return syscall(SYS_epoll_ctl, fd, op, fd2, ev);
 }
References fd, and syscall().
epoll_pwait()
int epoll_pwait (int fd, struct epoll_event * ev, int cnt, int to, const sigset_t * sigs)
Definition at line 26 of file epoll.c.
 {
     int r = __syscall_cp(SYS_epoll_pwait, fd, ev, cnt, to, sigs, _NSIG/8);
 #ifdef SYS_epoll_wait
     if (r==-ENOSYS && !sigs) r = __syscall_cp(SYS_epoll_wait, fd, ev, cnt, to);
 #endif
     return __syscall_ret(r);
 }
References __syscall_cp, __syscall_ret(), _NSIG, cnt, ENOSYS, and fd.
Referenced by epoll_wait().
epoll_wait()
int epoll_wait (int fd, struct epoll_event * ev, int cnt, int to)
Definition at line 35 of file epoll.c.
 {
     return epoll_pwait(fd, ev, cnt, to, 0);
 }
References cnt, epoll_pwait(), and fd.