Fennix Userspace: Userspace/apps/base/busybox/libbb/get_line_from_file.c File Reference
get_line_from_file.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC bb_get_chunk_from_file (FILE *file, size_t *end)
char *FAST_FUNC xmalloc_fgets (FILE *file)
char *FAST_FUNC xmalloc_fgetline (FILE *file)
Function Documentation
bb_get_chunk_from_file()
char* FAST_FUNC bb_get_chunk_from_file (FILE * file, size_t * end)
Definition at line 13 of file get_line_from_file.c.
 {
     int ch;
     size_t idx = 0;
     char *linebuf = NULL;
     while ((ch = getc(file)) != EOF) {
         /* grow the line buffer as necessary */
         if (!(idx & 0xff)) {
             if (idx == ((size_t)-1) - 0xff)
                 bb_die_memory_exhausted();
             linebuf = xrealloc(linebuf, idx + 0x100);
         }
         linebuf[idx++] = (char) ch;
         if (ch == '\0')
             break;
         if (end && ch == '\n')
             break;
     }
     if (end)
         *end = idx;
     if (linebuf) {
         // huh, does fgets discard prior data on error like this?
         // I don't think so....
         //if (ferror(file)) {
         //  free(linebuf);
         //  return NULL;
         //}
         linebuf = xrealloc(linebuf, idx + 1);
         linebuf[idx] = '\0';
     }
     return linebuf;
 }
References bb_die_memory_exhausted(), end, EOF, getc, idx, NULL, and xrealloc.
Referenced by get_next_line(), xmalloc_fgetline(), and xmalloc_fgets().
xmalloc_fgetline()
char* FAST_FUNC xmalloc_fgetline (FILE * file)
Definition at line 55 of file get_line_from_file.c.
 {
     size_t i;
     char *c = bb_get_chunk_from_file(file, &i);
     if (i && c[--i] == '\n')
         c[i] = '\0';
     return c;
 }
References bb_get_chunk_from_file(), c, and i.
Referenced by add_remove_shell_main(), append_control_file_to_llist(), bb_dump_addfile(), chpasswd_main(), comm_main(), create_list(), cryptpw_main(), cut_file(), do_all_in_proc_swaps(), factor_main(), fbsplash_main(), get_block_backed_filesystems(), grep_file(), handle_dir_common(), load_regexes_from_file(), md5_sha1_sum_main(), parse_common(), paste_files(), paste_files_separate(), patch_main(), pop3_checkr(), print_numbered_lines(), process_file(), process_files(), read_interfaces(), reverse(), sed_main(), sendmail_main(), shuf_main(), smtp_checkp(), uniq_main(), and update_passwd().
xmalloc_fgets()
char* FAST_FUNC xmalloc_fgets (FILE * file)
Definition at line 48 of file get_line_from_file.c.
 {
     size_t i;
     return bb_get_chunk_from_file(file, &i);
 }
References bb_get_chunk_from_file(), and i.
Referenced by copy_lines(), handle_dir_common(), parse(), patch_main(), read_iface_state(), and ts_main().