Fennix Userspace: Userspace/apps/base/bash/builtins/psize.c File Reference
psize.c File Reference
#include <config.h>
#include <stdio.h>
#include "../bashtypes.h"
#include <signal.h>
#include <errno.h>
#include "../command.h"
#include "../general.h"
#include "../sig.h"
Functions
sighandler sigpipe (int sig)
int main (int argc, char **argv)
Variables
int errno
int nw
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 59 of file psize.c.
 {
   char buf[128];
   register int i;
   for (i = 0; i < 128; i++)
     buf[i] = ' ';
   signal (SIGPIPE, sigpipe);
   nw = 0;
   for (;;)
     {
       int n;
       n = write (1, buf, 128);
       nw += n;
     }
   return (0);
 }
References buf, i, n, nw, signal, sigpipe(), SIGPIPE, and write().
sigpipe()
sighandler sigpipe (int sig)
Definition at line 51 of file psize.c.
 {
   fprintf (stderr, "%d\n", nw);
   exit (0);
 }
References exit(), fprintf(), nw, and stderr.
Referenced by main().
Variable Documentation
errno
int errno extern
nw
int nw
Definition at line 48 of file psize.c.
Referenced by fourbyte_memmem(), fourbyte_strstr(), heredoc_write(), main(), sigpipe(), tee_builtin(), threebyte_memmem(), threebyte_strstr(), twobyte_memmem(), and twobyte_strstr().