Fennix: Kernel/core/memory/heap_allocators/rpmalloc/rpmalloc_compat.cpp File Reference
rpmalloc_compat.cpp File Reference
#include <memory/macro.hpp>
#include <sys/mman.h>
#include <memory.hpp>
#include <assert.h>
#include <unistd.h>
#include "../../../../kernel.h"
Data Structures
struct heap_t
Functions
EXTERNC heap_t ** __memory_thread_heap (void)
EXTERNC uintptr_t __get_tid (void)
EXTERNC long __rpmalloc_sysconf (int name)
EXTERNC void * __rpmalloc_mmap (void *addr, size_t length, int, int, int fd, off_t offset)
EXTERNC int __rpmalloc_munmap (void *addr, size_t length)
EXTERNC int __rpmalloc_posix_madvise (void *addr, size_t length, int advice)
Variables
static heap_t * __rpmalloc_tls_heap = nullptr
Data Structure Documentation
heap_t
struct heap_t
Definition at line 496 of file rpmalloc.c.
Data Fields
atomic32_t child_count Child count.
int finalize Finalization state flag.
size_t full_span_count Number of full spans.
int32_t id Heap ID.
heap_t * master_heap Master heap owning the memory pages.
heap_t * next_heap Next heap in id list.
heap_t * next_orphan Next heap in orphan list.
uintptr_t owner_thread Owning thread ID.
char pad[56408]
heap_size_class_t size_class[SIZE_CLASS_COUNT] Free lists for each size class.
span_cache_t span_cache Arrays of fully freed spans, single span.
atomicptr_t span_free_deferred List of deferred free spans (single linked list)
span_large_cache_t span_large_cache[LARGE_CLASS_COUNT - 1] Arrays of fully freed spans, large spans with > 1 span count.
span_t * span_reserve Mapped but unused spans.
span_t * span_reserve_master Master span for mapped but unused spans.
uint32_t spans_reserved Number of mapped but unused spans.
Function Documentation
__get_tid()
EXTERNC uintptr_t __get_tid (void)
Definition at line 51 of file rpmalloc_compat.cpp.
 {
     if (unlikely(!TaskManager || !thisThread))
         return (uintptr_t)-1;
     return thisThread->ID;
 }
References TaskManager, thisThread, and unlikely.
Referenced by get_thread_id().
__memory_thread_heap()
EXTERNC heap_t** __memory_thread_heap (void)
Definition at line 33 of file rpmalloc_compat.cpp.
 {
     if (unlikely(!TaskManager || !thisThread))
     {
         if (unlikely(!__rpmalloc_tls_heap))
         {
             __rpmalloc_tls_heap = (heap_t *)KernelAllocator.RequestPages(TO_PAGES(sizeof(heap_t)));
             debug("rpmalloc TLS heap: %#lx", __rpmalloc_tls_heap);
             memset(__rpmalloc_tls_heap, 0, sizeof(heap_t));
             assert(__rpmalloc_tls_heap);
         }
         return &__rpmalloc_tls_heap;
     }
     return &__rpmalloc_tls_heap;
     heap_t *heap = (heap_t *)thisThread->TLS.pBase;
     return (heap_t **)heap;
 }
References __rpmalloc_tls_heap, assert, debug, heap, KernelAllocator, memset, return(), TaskManager, thisThread, TO_PAGES, and unlikely.
__rpmalloc_mmap()
EXTERNC void* __rpmalloc_mmap (void * addr, size_t length, int prot, int flags, int fd, off_t offset)
Definition at line 69 of file rpmalloc_compat.cpp.
 {
     assert(addr == 0 && fd == -1 && offset == 0);
     void *ptr = KernelAllocator.RequestPages(TO_PAGES(length));
     debug("Requested %d pages, got %p", TO_PAGES(length), ptr);
     if (ptr == nullptr)
         return MAP_FAILED;
     return ptr;
 }
References addr, assert, debug, fd, KernelAllocator, MAP_FAILED, offset, and TO_PAGES.
Referenced by _rpmalloc_mmap_os().
__rpmalloc_munmap()
EXTERNC int __rpmalloc_munmap (void * addr, size_t length)
Definition at line 80 of file rpmalloc_compat.cpp.
 {
     KernelAllocator.FreePages(addr, TO_PAGES(length));
     debug("Freed %d pages at %p", TO_PAGES(length), addr);
     return 0;
 }
References addr, debug, KernelAllocator, and TO_PAGES.
Referenced by _rpmalloc_unmap_os().
__rpmalloc_posix_madvise()
EXTERNC int __rpmalloc_posix_madvise (void * addr, size_t length, int advice)
Definition at line 87 of file rpmalloc_compat.cpp.
 {
     function("%#lx %d %d", addr, length, advice);
     return 0;
 }
References addr.
Referenced by _rpmalloc_unmap_os().
__rpmalloc_sysconf()
EXTERNC long __rpmalloc_sysconf (int name)
Definition at line 58 of file rpmalloc_compat.cpp.
 {
     switch (name)
     {
     case _SC_PAGESIZE:
         return PAGE_SIZE;
     default:
         return -1;
     }
 }
References _SC_PAGESIZE, and PAGE_SIZE.
Referenced by rpmalloc_initialize_config().
Variable Documentation
__rpmalloc_tls_heap
heap_t* __rpmalloc_tls_heap = nullptr static
Definition at line 32 of file rpmalloc_compat.cpp.
Referenced by __memory_thread_heap().