Fennix Userspace: Userspace/musl/src/sched/affinity.c File Reference
affinity.c File Reference
#include <sched.h>
#include <string.h>
#include "pthread_impl.h"
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
int sched_setaffinity (pid_t tid, size_t size, const cpu_set_t *set)
int pthread_setaffinity_np (pthread_t td, size_t size, const cpu_set_t *set)
static int do_getaffinity (pid_t tid, size_t size, cpu_set_t *set)
int sched_getaffinity (pid_t tid, size_t size, cpu_set_t *set)
int pthread_getaffinity_np (pthread_t td, size_t size, cpu_set_t *set)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file affinity.c.
Function Documentation
do_getaffinity()
static int do_getaffinity (pid_t tid, size_t size, cpu_set_t * set) static
Definition at line 17 of file affinity.c.
 {
     long ret = __syscall(SYS_sched_getaffinity, tid, size, set);
     if (ret < 0) return ret;
     if (ret < size) memset((char *)set+ret, 0, size-ret);
     return 0;
 }
References __syscall, memset(), ret, and size.
Referenced by pthread_getaffinity_np(), and sched_getaffinity().
pthread_getaffinity_np()
int pthread_getaffinity_np (pthread_t td, size_t size, cpu_set_t * set)
Definition at line 30 of file affinity.c.
 {
     return -do_getaffinity(td->tid, size, set);
 }
References do_getaffinity(), and size.
pthread_setaffinity_np()
int pthread_setaffinity_np (pthread_t td, size_t size, const cpu_set_t * set)
Definition at line 12 of file affinity.c.
 {
     return -__syscall(SYS_sched_setaffinity, td->tid, size, set);
 }
References __syscall, and size.
sched_getaffinity()
int sched_getaffinity (pid_t tid, size_t size, cpu_set_t * set)
Definition at line 25 of file affinity.c.
 {
     return __syscall_ret(do_getaffinity(tid, size, set));
 }
References __syscall_ret(), do_getaffinity(), and size.
sched_setaffinity()
int sched_setaffinity (pid_t tid, size_t size, const cpu_set_t * set)
Definition at line 7 of file affinity.c.
 {
     return syscall(SYS_sched_setaffinity, tid, size, set);
 }
References size, and syscall().