Fennix Userspace: Userspace/apps/base/bash/lib/intl/hash-string.h File Reference
hash-string.h File Reference
Macros
#define PARAMS(Args) ()
#define HASHWORDBITS 32
Functions
static unsigned long int hash_string PARAMS ((const char *__str_param))
static unsigned long int hash_string (str_param) const char *str_param
if (g !=0)
Variables
const char * str = str_param
hval = 0
g = hval & ((unsigned long int) 0xf << (HASHWORDBITS - 4))
Macro Definition Documentation
HASHWORDBITS
#define HASHWORDBITS 32
Definition at line 32 of file hash-string.h.
PARAMS
#define PARAMS (Args) ()
Definition at line 27 of file hash-string.h.
Function Documentation
hash_string()
static unsigned long int hash_string (str_param) const inline static
References g, and hval.
if()
if (g ! = 0)
Definition at line 54 of file hash-string.h.
     {
       hval ^= g >> (HASHWORDBITS - 8);
       hval ^= g;
     }
References g, HASHWORDBITS, and hval.
PARAMS()
static unsigned long int hash_string PARAMS ((const char *__str_param)) static
Variable Documentation
g
g = hval & ((unsigned long int) 0xf << (HASHWORDBITS - 4))
Definition at line 53 of file hash-string.h.
Referenced by __netlink_enumerate(), __syscall7(), add_links(), aligned_alloc(), alloc_group(), alloc_slot(), cmap_to_fb(), cmap_to_rgb565(), elf64Hash(), enframe(), finddirs(), FindNearestColor(), free(), GenerateStretchTable(), get_stride(), glob(), globfree(), groupnum(), hash_string(), I_GetPaletteIndex(), if(), is_allzero(), malloc(), malloc_usable_size(), nontrivial_free(), P_SpawnGlowingLight(), processblock(), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), pthread_setspecific(), realloc(), scan_table(), and T_Glow().
hval
return hval = 0
Definition at line 48 of file hash-string.h.
Referenced by hash_string(), and if().
str
while str = str_param
Definition at line 45 of file hash-string.h.
Referenced by __nl_langinfo_l(), _rl_insert_char(), addcstr(), ansic_quote(), StreamPrinter::append(), BufferPrinter::append(), LimitedPrinter::append(), ResizePrinter::append(), atou_(), atou_libint(), confstr(), escape_input(), fnmatch(), fnmatch_internal(), fputc(), get_subst_pattern(), HUlib_addPrefixToIText(), invis_adds(), M_StrToInt(), main(), memset(), parse_mailpath_spec(), pat_subst(), print_escaped(), puts_face(), putspent(), saveg_read_actionf_t(), saveg_read_ceiling_t(), saveg_read_floormove_t(), saveg_read_glow_t(), saveg_read_lightflash_t(), saveg_read_mapthing_t(), saveg_read_mobj_t(), saveg_read_plat_t(), saveg_read_player_t(), saveg_read_pspdef_t(), saveg_read_strobe_t(), saveg_read_thinker_t(), saveg_read_ticcmd_t(), saveg_read_vldoor_t(), saveg_write_actionf_t(), saveg_write_ceiling_t(), saveg_write_floormove_t(), saveg_write_glow_t(), saveg_write_lightflash_t(), saveg_write_mapthing_t(), saveg_write_mobj_t(), saveg_write_plat_t(), saveg_write_player_t(), saveg_write_pspdef_t(), saveg_write_strobe_t(), saveg_write_thinker_t(), saveg_write_ticcmd_t(), saveg_write_vldoor_t(), scan_file(), SHA1_UpdateString(), str_next(), strlen(), strnlen_s_(), strnlen_s_libint(), strprint(), strsep(), mlibc::strtofp(), and tputs().