Fennix: Userspace/apps/base/bash/unwind_prot.c File Reference
unwind_prot.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "bashansi.h"
#include "command.h"
#include "general.h"
#include "unwind_prot.h"
#include "sig.h"
#include "quit.h"
#include "bashintl.h"
#include "error.h"
#include "ocache.h"
Data Structures
struct SAVED_VAR
union uwp
struct uwp::uwp_head
struct uwp.arg
struct uwp.sv
Macros
#define offsetof(TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)
#define UWCACHESIZE 128
#define uwpalloc(elt) ocache_alloc (uwcache, UNWIND_ELT, elt)
#define uwpfree(elt) ocache_free (uwcache, UNWIND_ELT, elt)
Typedefs
typedef union uwp UNWIND_ELT
Functions
static void without_interrupts PARAMS ((VFunction *, char *, char *))
static void unwind_frame_discard_internal PARAMS ((char *, char *))
static void add_unwind_protect_internal PARAMS ((Function *, char *))
static void restore_variable PARAMS ((SAVED_VAR *))
void uwp_init ()
static void without_interrupts (VFunction *function, char *arg1, char *arg2)
void begin_unwind_frame (char *tag)
void discard_unwind_frame (char *tag)
void run_unwind_frame (char *tag)
void add_unwind_protect (Function *cleanup, char *arg)
void remove_unwind_protect ()
void run_unwind_protects ()
void clear_unwind_protect_list (int flags)
int have_unwind_protects ()
int unwind_protect_tag_on_stack (char *tag) const
static void add_unwind_protect_internal (Function *cleanup, char *arg)
static void remove_unwind_protect_internal (char *ignore1, char *ignore2)
static void run_unwind_protects_internal (char *ignore1, char *ignore2)
static void clear_unwind_protects_internal (char *flag, char *ignore)
static void unwind_frame_discard_internal (char *tag, char *ignore)
static void restore_variable (SAVED_VAR *sv)
static void unwind_frame_run_internal (char *tag, char *ignore)
static void unwind_protect_mem_internal (char *var, char *psize)
void unwind_protect_mem (char *var, int size)
Variables
static UNWIND_ELT * unwind_protect_list = (UNWIND_ELT *)NULL
sh_obj_cache_t uwcache = {0, 0, 0}
Data Structure Documentation
SAVED_VAR
struct SAVED_VAR
Definition at line 56 of file unwind_prot.c.
Data Fields
char desired_setting[1]
int size
char * variable
uwp
union uwp
Definition at line 65 of file unwind_prot.c.
Data Fields
struct uwp arg
struct uwp_head head
struct uwp sv
uwp::uwp_head
struct uwp::uwp_head
Definition at line 66 of file unwind_prot.c.
Data Fields
Function * cleanup
union uwp * next
uwp.arg
struct uwp.arg
Definition at line 70 of file unwind_prot.c.
Data Fields
struct uwp_head uwp_head
char * v
uwp.sv
struct uwp.sv
Definition at line 74 of file unwind_prot.c.
Data Fields
struct uwp_head uwp_head
SAVED_VAR v
Macro Definition Documentation
offsetof
#define offsetof (TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)
Definition at line 43 of file unwind_prot.c.
UWCACHESIZE
#define UWCACHESIZE 128
Definition at line 93 of file unwind_prot.c.
uwpalloc
#define uwpalloc (elt) ocache_alloc (uwcache, UNWIND_ELT, elt)
Definition at line 101 of file unwind_prot.c.
uwpfree
#define uwpfree (elt) ocache_free (uwcache, UNWIND_ELT, elt)
Definition at line 102 of file unwind_prot.c.
Typedef Documentation
UNWIND_ELT
typedef union uwp UNWIND_ELT
Function Documentation
add_unwind_protect()
void add_unwind_protect (Function * cleanup, char * arg)
Definition at line 149 of file unwind_prot.c.
 {
   without_interrupts (add_unwind_protect_internal, (char *)cleanup, arg);
 }
References add_unwind_protect_internal(), cleanup(), and without_interrupts().
Referenced by _evalfile(), begin_unwind_frame(), command_substitute(), execute_builtin(), execute_builtin_or_function(), execute_case_command(), execute_command(), execute_command_internal(), execute_for_command(), execute_function(), execute_pipeline(), execute_shell_function(), execute_simple_command(), parse_and_execute(), parse_prologue(), print_function_def(), and run_sigchld_trap().
add_unwind_protect_internal()
static void add_unwind_protect_internal (Function * cleanup, char * arg) static
Definition at line 218 of file unwind_prot.c.
 {
   UNWIND_ELT *elt;
   uwpalloc (elt);
   elt->head.next = unwind_protect_list;
   elt->head.cleanup = cleanup;
   elt->arg.v = arg;
   unwind_protect_list = elt;
 }
References uwp::arg, uwp::uwp_head::cleanup, cleanup(), uwp::head, uwp::uwp_head::next, unwind_protect_list, and uwpalloc.
Referenced by add_unwind_protect().
begin_unwind_frame()
void begin_unwind_frame (char * tag)
Definition at line 123 of file unwind_prot.c.
 {
   add_unwind_protect ((Function *)NULL, tag);
 }
References add_unwind_protect(), and NULL.
Referenced by _evalfile(), command_substitute(), evalstring(), execute_builtin(), execute_builtin_or_function(), execute_case_command(), execute_command(), execute_command_internal(), execute_for_command(), execute_function(), execute_pipeline(), execute_shell_function(), execute_simple_command(), parse_and_execute(), parse_prologue(), and run_sigchld_trap().
clear_unwind_protect_list()
void clear_unwind_protect_list (int flags)
Definition at line 176 of file unwind_prot.c.
 {
   char *flag;
   if (unwind_protect_list)
     {
       flag = flags ? "" : (char *)NULL;
       without_interrupts
         (clear_unwind_protects_internal, flag, (char *)NULL);
     }
 }
References clear_unwind_protects_internal(), flags, NULL, unwind_protect_list, and without_interrupts().
Referenced by initialize_subshell().
clear_unwind_protects_internal()
static void clear_unwind_protects_internal (char * flag, char * ignore) static
Definition at line 253 of file unwind_prot.c.
 {
   if (flag)
     {
       while (unwind_protect_list)
     remove_unwind_protect_internal ((char *)NULL, (char *)NULL);
     }
   unwind_protect_list = (UNWIND_ELT *)NULL;
 }
References NULL, remove_unwind_protect_internal(), and unwind_protect_list.
Referenced by clear_unwind_protect_list().
discard_unwind_frame()
void discard_unwind_frame (char * tag)
Definition at line 131 of file unwind_prot.c.
 {
   if (unwind_protect_list)
     without_interrupts (unwind_frame_discard_internal, tag, (char *)NULL);
 }
References NULL, unwind_frame_discard_internal(), unwind_protect_list, and without_interrupts().
Referenced by command_substitute(), execute_builtin(), execute_builtin_or_function(), execute_case_command(), execute_command(), execute_command_internal(), execute_for_command(), execute_pipeline(), execute_shell_function(), execute_simple_command(), and parse_and_execute().
have_unwind_protects()
int have_unwind_protects ()
Definition at line 190 of file unwind_prot.c.
 {
   return (unwind_protect_list != 0);
 }
References unwind_protect_list.
Referenced by parse_and_execute_cleanup().
PARAMS() [1/4]
static void unwind_frame_discard_internal PARAMS ((char *, char *)) static
PARAMS() [2/4]
static void add_unwind_protect_internal PARAMS ((Function *, char *)) static
PARAMS() [3/4]
static void restore_variable PARAMS ((SAVED_VAR *)) inline static
PARAMS() [4/4]
static void without_interrupts PARAMS ((VFunction *, char *, char *)) static
remove_unwind_protect()
void remove_unwind_protect ()
Definition at line 158 of file unwind_prot.c.
 {
   if (unwind_protect_list)
     without_interrupts
       (remove_unwind_protect_internal, (char *)NULL, (char *)NULL);
 }
References NULL, remove_unwind_protect_internal(), unwind_protect_list, and without_interrupts().
Referenced by print_function_def().
remove_unwind_protect_internal()
static void remove_unwind_protect_internal (char * ignore1, char * ignore2) static
Definition at line 232 of file unwind_prot.c.
 {
   UNWIND_ELT *elt;
   elt = unwind_protect_list;
   if (elt)
     {
       unwind_protect_list = unwind_protect_list->head.next;
       uwpfree (elt);
     }
 }
References uwp::head, uwp::uwp_head::next, unwind_protect_list, and uwpfree.
Referenced by clear_unwind_protects_internal(), and remove_unwind_protect().
restore_variable()
static void restore_variable (SAVED_VAR * sv) inline static
Definition at line 293 of file unwind_prot.c.
 {
   FASTCOPY (sv->desired_setting, sv->variable, sv->size);
 }
References SAVED_VAR::desired_setting, FASTCOPY, SAVED_VAR::size, and SAVED_VAR::variable.
Referenced by unwind_frame_run_internal(), and unwind_protect_mem_internal().
run_unwind_frame()
void run_unwind_frame (char * tag)
Definition at line 140 of file unwind_prot.c.
 {
   if (unwind_protect_list)
     without_interrupts (unwind_frame_run_internal, tag, (char *)NULL);
 }
References NULL, unwind_frame_run_internal(), unwind_protect_list, and without_interrupts().
Referenced by _evalfile(), evalstring(), execute_builtin(), execute_command_internal(), execute_function(), execute_simple_command(), parse_and_execute(), parse_and_execute_cleanup(), parse_string(), and run_sigchld_trap().
run_unwind_protects()
void run_unwind_protects ()
Definition at line 167 of file unwind_prot.c.
 {
   if (unwind_protect_list)
     without_interrupts
       (run_unwind_protects_internal, (char *)NULL, (char *)NULL);
 }
References NULL, run_unwind_protects_internal(), unwind_protect_list, and without_interrupts().
Referenced by throw_to_top_level(), and top_level_cleanup().
run_unwind_protects_internal()
static void run_unwind_protects_internal (char * ignore1, char * ignore2) static
Definition at line 246 of file unwind_prot.c.
 {
   unwind_frame_run_internal ((char *) NULL, (char *) NULL);
 }
References NULL, and unwind_frame_run_internal().
Referenced by run_unwind_protects().
unwind_frame_discard_internal()
static void unwind_frame_discard_internal (char * tag, char * ignore) static
Definition at line 265 of file unwind_prot.c.
 {
   UNWIND_ELT *elt;
   int found;
   found = 0;
   while (elt = unwind_protect_list)
     {
       unwind_protect_list = unwind_protect_list->head.next;
       if (elt->head.cleanup == 0 && (STREQ (elt->arg.v, tag)))
     {
       uwpfree (elt);
       found = 1;
       break;
     }
       else
     uwpfree (elt);
     }
   if (found == 0)
     internal_warning (_("unwind_frame_discard: %s: frame not found"), tag);
 }
References _, uwp::arg, uwp::uwp_head::cleanup, uwp::head, internal_warning(), uwp::uwp_head::next, STREQ, unwind_protect_list, and uwpfree.
Referenced by discard_unwind_frame().
unwind_frame_run_internal()
static void unwind_frame_run_internal (char * tag, char * ignore) static
Definition at line 300 of file unwind_prot.c.
 {
   UNWIND_ELT *elt;
   int found;
   found = 0;
   while (elt = unwind_protect_list)
     {
       unwind_protect_list = elt->head.next;
       /* If tag, then compare. */
       if (elt->head.cleanup == 0)
     {
       if (tag && STREQ (elt->arg.v, tag))
         {
           uwpfree (elt);
           found = 1;
           break;
         }
     }
       else
     {
       if (elt->head.cleanup == (Function *) restore_variable)
         restore_variable (&elt->sv.v);
       else
         (*(elt->head.cleanup)) (elt->arg.v);
     }
       uwpfree (elt);
     }
   if (tag && found == 0)
     internal_warning (_("unwind_frame_run: %s: frame not found"), tag);
 }
References _, uwp::arg, uwp::uwp_head::cleanup, uwp::head, internal_warning(), uwp::uwp_head::next, restore_variable(), STREQ, uwp::sv, unwind_protect_list, and uwpfree.
Referenced by run_unwind_frame(), and run_unwind_protects_internal().
unwind_protect_mem()
void unwind_protect_mem (char * var, int size)
Definition at line 360 of file unwind_prot.c.
 {
   without_interrupts (unwind_protect_mem_internal, var, (char *) &size);
 }
References size, unwind_protect_mem_internal(), and without_interrupts().
unwind_protect_mem_internal()
static void unwind_protect_mem_internal (char * var, char * psize) static
Definition at line 336 of file unwind_prot.c.
 {
   int size, allocated;
   UNWIND_ELT *elt;
   size = *(int *) psize;
   allocated = size + offsetof (UNWIND_ELT, sv.v.desired_setting[0]);
   if (allocated < sizeof (UNWIND_ELT))
     allocated = sizeof (UNWIND_ELT);
   elt = (UNWIND_ELT *)xmalloc (allocated);
   elt->head.next = unwind_protect_list;
   elt->head.cleanup = (Function *) restore_variable;
   elt->sv.v.variable = var;
   elt->sv.v.size = size;
   FASTCOPY (var, elt->sv.v.desired_setting, size);
   unwind_protect_list = elt;
 }
References uwp::uwp_head::cleanup, SAVED_VAR::desired_setting, FASTCOPY, uwp::head, uwp::uwp_head::next, offsetof, restore_variable(), size, uwp::sv, unwind_protect_list, and xmalloc.
Referenced by unwind_protect_mem().
unwind_protect_tag_on_stack()
int unwind_protect_tag_on_stack (char * tag) const
Definition at line 196 of file unwind_prot.c.
 {
   UNWIND_ELT *elt;
   elt = unwind_protect_list;
   while (elt)
     {
       if (elt->head.cleanup == 0 && STREQ (elt->arg.v, tag))
     return 1;
       elt = elt->head.next;
     }
   return 0;
 }
References uwp::arg, uwp::uwp_head::cleanup, uwp::head, uwp::uwp_head::next, STREQ, and unwind_protect_list.
Referenced by execute_command_internal().
uwp_init()
void uwp_init ()
Definition at line 106 of file unwind_prot.c.
 {
   ocache_create (uwcache, UNWIND_ELT, UWCACHESIZE);
 }
References ocache_create, uwcache, and UWCACHESIZE.
Referenced by main().
without_interrupts()
static void without_interrupts (VFunction * function, char * arg1, char * arg2) static
Definition at line 114 of file unwind_prot.c.
 {
   (*function)(arg1, arg2);
 }
References arg1, and arg2.
Referenced by add_unwind_protect(), clear_unwind_protect_list(), discard_unwind_frame(), remove_unwind_protect(), run_unwind_frame(), run_unwind_protects(), and unwind_protect_mem().
Variable Documentation
unwind_protect_list
UNWIND_ELT* unwind_protect_list = (UNWIND_ELT *)NULL static
Definition at line 90 of file unwind_prot.c.
Referenced by add_unwind_protect_internal(), clear_unwind_protect_list(), clear_unwind_protects_internal(), discard_unwind_frame(), have_unwind_protects(), remove_unwind_protect(), remove_unwind_protect_internal(), run_unwind_frame(), run_unwind_protects(), unwind_frame_discard_internal(), unwind_frame_run_internal(), unwind_protect_mem_internal(), and unwind_protect_tag_on_stack().
uwcache
sh_obj_cache_t uwcache = {0, 0, 0}
Definition at line 95 of file unwind_prot.c.
Referenced by uwp_init().