Fennix Userspace: Userspace/musl/src/string/strchrnul.c File Reference
strchrnul.c File Reference
#include <string.h>
#include <stdint.h>
#include <limits.h>
Macros
#define ALIGN (sizeof(size_t))
#define ONES ((size_t)-1/UCHAR_MAX)
#define HIGHS (ONES * (UCHAR_MAX/2+1))
#define HASZERO(x) ((x)-ONES & ~(x) & HIGHS)
Functions
char * __strchrnul (const char *s, int c)
weak_alias (__strchrnul, strchrnul)
Macro Definition Documentation
ALIGN
#define ALIGN (sizeof(size_t))
Definition at line 5 of file strchrnul.c.
HASZERO
#define HASZERO (x) ((x)-ONES & ~(x) & HIGHS)
Definition at line 8 of file strchrnul.c.
HIGHS
#define HIGHS (ONES * (UCHAR_MAX/2+1))
Definition at line 7 of file strchrnul.c.
ONES
#define ONES ((size_t)-1/UCHAR_MAX)
Definition at line 6 of file strchrnul.c.
Function Documentation
__strchrnul()
char* __strchrnul (const char * s, int c)
Definition at line 10 of file strchrnul.c.
 {
     c = (unsigned char)c;
     if (!c) return (char *)s + strlen(s);
 #ifdef __GNUC__
     typedef size_t __attribute__((__may_alias__)) word;
     const word *w;
     for (; (uintptr_t)s % ALIGN; s++)
         if (!*s || *(unsigned char *)s == c) return (char *)s;
     size_t k = ONES * c;
     for (w = (void *)s; !HASZERO(*w) && !HASZERO(*w^k); w++);
     s = (void *)w;
 #endif
     for (; *s && *(unsigned char *)s != c; s++);
     return (char *)s;
 }
References __attribute__, ALIGN, c, HASZERO, k, ONES, s, strlen(), and w.
Referenced by __execvpe(), __get_locale(), __shm_mapname(), catopen(), expand_tilde(), getenv(), putenv(), realpath(), setenv(), setlocale(), strchr(), strcspn(), and unsetenv().
weak_alias()
weak_alias (__strchrnul , strchrnul)