Fennix Userspace: Userspace/apps/base/busybox/util-linux/hwclock.c File Reference
hwclock.c File Reference
#include "libbb.h"
#include <sys/utsname.h>
#include "rtc_.h"
Macros
#define LIBC_IS_MUSL 0
#define SHOW_HWCLOCK_DIFF 0
#define read_rtc(pp_rtcname, sys_tv, utc) read_rtc(pp_rtcname, utc)
#define HWCLOCK_OPT_LOCALTIME 0x01
#define HWCLOCK_OPT_UTC 0x02
#define HWCLOCK_OPT_SHOW 0x04
#define HWCLOCK_OPT_HCTOSYS 0x08
#define HWCLOCK_OPT_SYSTOHC 0x10
#define HWCLOCK_OPT_SYSTZ 0x20
#define HWCLOCK_OPT_RTCFILE 0x40
Functions
static time_t read_rtc (const char **pp_rtcname, struct timeval *sys_tv, int utc)
static void show_clock (const char **pp_rtcname, int utc)
static void set_kernel_tz (const struct timezone *tz)
static void set_kernel_timezone_and_clock (int utc, const struct timeval *hctosys)
static void to_sys_clock (const char **pp_rtcname, int utc)
static void from_sys_clock (const char **pp_rtcname, int utc)
int hwclock_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
HWCLOCK_OPT_HCTOSYS
#define HWCLOCK_OPT_HCTOSYS 0x08
Definition at line 374 of file hwclock.c.
HWCLOCK_OPT_LOCALTIME
#define HWCLOCK_OPT_LOCALTIME 0x01
Definition at line 371 of file hwclock.c.
HWCLOCK_OPT_RTCFILE
#define HWCLOCK_OPT_RTCFILE 0x40
Definition at line 377 of file hwclock.c.
HWCLOCK_OPT_SHOW
#define HWCLOCK_OPT_SHOW 0x04
Definition at line 373 of file hwclock.c.
HWCLOCK_OPT_SYSTOHC
#define HWCLOCK_OPT_SYSTOHC 0x10
Definition at line 375 of file hwclock.c.
HWCLOCK_OPT_SYSTZ
#define HWCLOCK_OPT_SYSTZ 0x20
Definition at line 376 of file hwclock.c.
HWCLOCK_OPT_UTC
#define HWCLOCK_OPT_UTC 0x02
Definition at line 372 of file hwclock.c.
LIBC_IS_MUSL
#define LIBC_IS_MUSL 0
Definition at line 48 of file hwclock.c.
read_rtc
#define read_rtc (pp_rtcname, sys_tv, utc) read_rtc(pp_rtcname, utc)
Definition at line 66 of file hwclock.c.
SHOW_HWCLOCK_DIFF
#define SHOW_HWCLOCK_DIFF 0
Definition at line 62 of file hwclock.c.
Function Documentation
from_sys_clock()
static void from_sys_clock (const char ** pp_rtcname, int utc) static
Definition at line 200 of file hwclock.c.
 {
 #if 1
     struct timeval tv;
     struct tm tm_time;
     int rtc;
     rtc = rtc_xopen(pp_rtcname, O_WRONLY);
     xgettimeofday(&tv);
     /* Prepare tm_time */
     if (sizeof(time_t) == sizeof(tv.tv_sec)) {
         if (utc)
             gmtime_r((time_t*)&tv.tv_sec, &tm_time);
         else
             localtime_r((time_t*)&tv.tv_sec, &tm_time);
     } else {
         time_t t = tv.tv_sec;
         if (utc)
             gmtime_r(&t, &tm_time);
         else
             localtime_r(&t, &tm_time);
     }
 #else
 /* Bloated code which tries to set hw clock with better precision.
  * On x86, even though code does set hw clock within <1ms of exact
  * whole seconds, apparently hw clock (at least on some machines)
  * doesn't reset internal fractional seconds to 0,
  * making all this a pointless exercise.
  */
     /* If we see that we are N usec away from whole second,
      * we'll sleep for N-ADJ usecs. ADJ corrects for the fact
      * that CPU is not infinitely fast.
      * On infinitely fast CPU, next wakeup would be
      * on (exactly_next_whole_second - ADJ). On real CPUs,
      * this difference between current time and whole second
      * is less than ADJ (assuming system isn't heavily loaded).
      */
     /* Small value of 256us gives very precise sync for 2+ GHz CPUs.
      * Slower CPUs will fail to sync and will go to bigger
      * ADJ values. qemu-emulated armv4tl with ~100 MHz
      * performance ends up using ADJ ~= 4*1024 and it takes
      * 2+ secs (2 tries with successively larger ADJ)
      * to sync. Even straced one on the same qemu (very slow)
      * takes only 4 tries.
      */
 #define TWEAK_USEC 256
     unsigned adj = TWEAK_USEC;
     struct tm tm_time;
     struct timeval tv;
     int rtc = rtc_xopen(pp_rtcname, O_WRONLY);
     /* Try to catch the moment when whole second is close */
     while (1) {
         unsigned rem_usec;
         time_t t;
         xgettimeofday(&tv);
         t = tv.tv_sec;
         rem_usec = 1000000 - tv.tv_usec;
         if (rem_usec < adj) {
             /* Close enough */
  small_rem:
             t++;
         }
         /* Prepare tm_time from t */
         if (utc)
             gmtime_r(&t, &tm_time); /* may read /etc/xxx (it takes time) */
         else
             localtime_r(&t, &tm_time); /* same */
         if (adj >= 32*1024) {
             break; /* 32 ms diff and still no luck?? give up trying to sync */
         }
         /* gmtime/localtime took some time, re-get cur time */
         xgettimeofday(&tv);
         if (tv.tv_sec < t /* we are still in old second */
          || (tv.tv_sec == t && tv.tv_usec < adj) /* not too far into next second */
         ) {
             break; /* good, we are in sync! */
         }
         rem_usec = 1000000 - tv.tv_usec;
         if (rem_usec < adj) {
             t = tv.tv_sec;
             goto small_rem; /* already close to next sec, don't sleep */
         }
         /* Try to sync up by sleeping */
         usleep(rem_usec - adj);
         /* Jump to 1ms diff, then increase fast (x2): EVERY loop
          * takes ~1 sec, people won't like slowly converging code here!
          */
     //bb_error_msg("adj:%d tv.tv_usec:%d", adj, (int)tv.tv_usec);
         if (adj < 512)
             adj = 512;
         /* ... and if last "overshoot" does not look insanely big,
          * just use it as adj increment. This makes convergence faster.
          */
         if (tv.tv_usec < adj * 8) {
             adj += tv.tv_usec;
             continue;
         }
         adj *= 2;
     }
     /* Debug aid to find "optimal" TWEAK_USEC with nearly exact sync.
      * Look for a value which makes tv_usec close to 999999 or 0.
      * For 2.20GHz Intel Core 2: optimal TWEAK_USEC ~= 200
      */
     //bb_error_msg("tv.tv_usec:%d", (int)tv.tv_usec);
 #endif
     tm_time.tm_isdst = 0;
     xioctl(rtc, RTC_SET_TIME, &tm_time);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(rtc);
 }
References close(), O_WRONLY, RTC_SET_TIME, rtc_xopen(), t, tm::tm_isdst, timeval::tv_sec, timeval::tv_usec, usleep(), xgettimeofday(), and xioctl.
Referenced by hwclock_main().
hwclock_main()
int hwclock_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 380 of file hwclock.c.
 {
     const char *rtcname = NULL;
     unsigned opt;
     int utc;
 #if ENABLE_LONG_OPTS
     static const char hwclock_longopts[] ALIGN1 =
         "localtime\0" No_argument "l"
         "utc\0"       No_argument "u"
         "show\0"      No_argument "r"
         "hctosys\0"   No_argument "s"
         "systohc\0"   No_argument "w"
         "systz\0"     No_argument "t" /* short opt is non-standard */
         "rtc\0"       Required_argument "f"
         ;
 #endif
     opt = getopt32long(argv,
         "^""lurswtf:v" /* -v is accepted and ignored */
         "\0"
         "r--wst:w--rst:s--wrt:t--rsw:l--u:u--l",
         hwclock_longopts,
         &rtcname
     );
     /* If -u or -l wasn't given, check if we are using utc */
     if (opt & (HWCLOCK_OPT_UTC | HWCLOCK_OPT_LOCALTIME))
         utc = (opt & HWCLOCK_OPT_UTC);
     else
         utc = rtc_adjtime_is_utc();
     if (opt & HWCLOCK_OPT_HCTOSYS)
         to_sys_clock(&rtcname, utc);
     else if (opt & HWCLOCK_OPT_SYSTOHC)
         from_sys_clock(&rtcname, utc);
     else if (opt & HWCLOCK_OPT_SYSTZ)
         set_kernel_timezone_and_clock(utc, NULL);
     else
         /* default HWCLOCK_OPT_SHOW */
         show_clock(&rtcname, utc);
     return 0;
 }
References ALIGN1, argv, from_sys_clock(), getopt32long, HWCLOCK_OPT_HCTOSYS, HWCLOCK_OPT_LOCALTIME, HWCLOCK_OPT_SYSTOHC, HWCLOCK_OPT_SYSTZ, HWCLOCK_OPT_UTC, No_argument, NULL, opt, Required_argument, rtc_adjtime_is_utc(), set_kernel_timezone_and_clock(), show_clock(), and to_sys_clock().
read_rtc()
static time_t read_rtc (const char ** pp_rtcname, struct timeval * sys_tv, int utc) static
Definition at line 68 of file hwclock.c.
 {
     struct tm tm_time;
     int fd;
     fd = rtc_xopen(pp_rtcname, O_RDONLY);
     rtc_read_tm(&tm_time, fd);
 #if SHOW_HWCLOCK_DIFF
     {
         int before = tm_time.tm_sec;
         while (1) {
             rtc_read_tm(&tm_time, fd);
             xgettimeofday(sys_tv);
             if (before != (int)tm_time.tm_sec)
                 break;
         }
     }
 #endif
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     return rtc_tm2time(&tm_time, utc);
 }
References close(), fd, O_RDONLY, rtc_read_tm(), rtc_tm2time(), rtc_xopen(), tm::tm_sec, and xgettimeofday().
set_kernel_timezone_and_clock()
static void set_kernel_timezone_and_clock (int utc, const struct timeval * hctosys) static
Definition at line 167 of file hwclock.c.
 {
     time_t cur;
     struct tm *broken;
     struct timezone tz = { 0 };
     /* if --utc, prevent kernel's warp_clock() with a dummy call */
     if (utc)
         set_kernel_tz(&tz);
     /* Set kernel's timezone offset based on userspace one */
 //It's tempting to call tzset() and use libc global "timezone" variable
 //...but it does NOT include DST shift (IOW: it's WRONG, usually by one hour,
 //if DST is in effect!) Thus this ridiculous dance:
     cur = time(NULL);
     broken = localtime(&cur);
     tz.tz_minuteswest = -broken->tm_gmtoff / 60;
     /*tz.tz_dsttime = 0; already is */
     set_kernel_tz(&tz); /* MIGHT warp_clock() if 1st call since boot */
     if (hctosys) /* it's --hctosys: set time too */
         xsettimeofday(hctosys);
 }
References cur, localtime(), NULL, set_kernel_tz(), time(), and xsettimeofday().
Referenced by hwclock_main(), and to_sys_clock().
set_kernel_tz()
static void set_kernel_tz (const struct timezone * tz) static
Definition at line 132 of file hwclock.c.
 {
 #if LIBC_IS_MUSL
     /* musl libc does not pass tz argument to syscall
      * because "it's deprecated by POSIX, therefore it's fine
      * if we gratuitously break stuff" :(
      */
 #if !defined(SYS_settimeofday) && defined(SYS_settimeofday_time32)
 # define SYS_settimeofday SYS_settimeofday_time32
 #endif
     int ret = syscall(SYS_settimeofday, NULL, tz);
 #else
     int ret = settimeofday(NULL, tz);
 #endif
     if (ret)
         bb_simple_perror_msg_and_die("settimeofday");
 }
References bb_simple_perror_msg_and_die(), NULL, settimeofday(), and syscall().
Referenced by set_kernel_timezone_and_clock().
show_clock()
static void show_clock (const char ** pp_rtcname, int utc) static
Definition at line 95 of file hwclock.c.
 {
 #if SHOW_HWCLOCK_DIFF
     struct timeval sys_tv;
 #endif
     time_t t = read_rtc(pp_rtcname, &sys_tv, utc);
 #if ENABLE_LOCALE_SUPPORT
     /* Standard hwclock uses locale-specific output format */
     char cp[64];
     struct tm *ptm = localtime(&t);
     strftime(cp, sizeof(cp), "%c", ptm);
 #else
     char *cp = ctime(&t);
     chomp(cp);
 #endif
 #if !SHOW_HWCLOCK_DIFF
     printf("%s  0.000000 seconds\n", cp);
 #else
     {
         long diff = sys_tv.tv_sec - t;
         if (diff < 0 /*&& tv.tv_usec != 0*/) {
             /* Why we need diff++? */
             /* diff >= 0 is ok: | diff < 0, can't just use tv.tv_usec: */
             /*   45.520820      |   43.520820 */
             /* - 44.000000      | - 45.000000 */
             /* =  1.520820      | = -1.479180, not -2.520820! */
             diff++;
             /* Should be 1000000 - tv.tv_usec, but then we must check tv.tv_usec != 0 */
             sys_tv.tv_usec = 999999 - sys_tv.tv_usec;
         }
         printf("%s  %ld.%06lu seconds\n", cp, diff, (unsigned long)sys_tv.tv_usec);
     }
 #endif
 }
References chomp(), ctime(), diff(), localtime(), printf(), read_rtc, strftime(), t, timeval::tv_sec, and timeval::tv_usec.
Referenced by hwclock_main().
to_sys_clock()
static void to_sys_clock (const char ** pp_rtcname, int utc) static
Definition at line 191 of file hwclock.c.
 {
     struct timeval tv;
     tv.tv_sec = read_rtc(pp_rtcname, NULL, utc);
     tv.tv_usec = 0;
     return set_kernel_timezone_and_clock(utc, &tv);
 }
References NULL, read_rtc, set_kernel_timezone_and_clock(), timeval::tv_sec, and timeval::tv_usec.
Referenced by hwclock_main().