Fennix Userspace: Userspace/libc/src/std/io/put.c File Reference
put.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <fennix/syscall.h>
#include <sys/types.h>
Functions
PUBLIC int fputc (int c, FILE *stream)
PUBLIC int putc (int c, FILE *stream)
PUBLIC int fputs (const char *s, FILE *stream)
PUBLIC int puts (const char *s)
PUBLIC int putchar (int c)
PUBLIC void perror (const char *s)
Function Documentation
fputc()
PUBLIC int fputc (int c, FILE * stream)
Definition at line 7 of file put.c.
 {
     // FIXME
     // if (stream == NULL)
     // {
     //     errno = EBADF;
     //     return EOF;
     // }
     char str[2] = {c, '\0'};
     return syscall3(sys_KernelCTL, KCTL_PRINT, str, 0);
 }
Referenced by fputs(), putc(), putchar(), and puts().
fputs()
PUBLIC int fputs (const char * s, FILE * stream)
Definition at line 21 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stream);
 }
References fputc(), i, and s.
Referenced by perror().
perror()
PUBLIC void perror (const char * s)
Definition at line 34 of file put.c.
 { fputs(s, stderr); }
putc()
PUBLIC int putc (int c, FILE * stream)
Definition at line 19 of file put.c.
 { return fputc(c, stream); }
putchar()
PUBLIC int putchar (int c)
Definition at line 33 of file put.c.
 { return fputc(c, stdout); }
puts()
PUBLIC int puts (const char * s)
Definition at line 27 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stdout);
 }