Fennix: Kernel/Core/Memory/Memory.cpp File Reference
Memory.cpp File Reference
#include <memory.hpp>
#include <convert.h>
#include <lock.hpp>
#include <debug.h>
#include "HeapAllocators/Xalloc/Xalloc.hpp"
#include "../Library/liballoc_1_1.h"
#include "../../kernel.h"
Macros
#define memdbg(m, ...)
Functions
NIF void MapFromZero (PageTable4 *PT, BootInfo *Info)
NIF void MapFramebuffer (PageTable4 *PT, BootInfo *Info)
NIF void MapKernel (PageTable4 *PT, BootInfo *Info)
NIF void InitializeMemoryManagement (BootInfo *Info)
void * malloc (size_t Size)
The standard function.
void * calloc (size_t n, size_t Size)
The standard function.
void * realloc (void *Address, size_t Size)
The standard function.
void free (void *Address)
The standard function.
void * operator new (size_t Size)
void * operator new[] (size_t Size)
void * operator new (unsigned long Size, std::align_val_t Alignment)
void operator delete (void *Pointer)
void operator delete[] (void *Pointer)
void operator delete (void *Pointer, long unsigned int Size)
void operator delete[] (void *Pointer, long unsigned int Size)
Variables
Physical KernelAllocator
PageTable4 * KernelPageTable = nullptr
bool Page1GBSupport = false
bool PSESupport = false
static MemoryAllocatorType AllocatorType = MemoryAllocatorType::Pages
Xalloc::V1 * XallocV1Allocator = nullptr
Macro Definition Documentation
memdbg
#define memdbg (m, ...)
Definition at line 39 of file Memory.cpp.
Function Documentation
InitializeMemoryManagement()
NIF void InitializeMemoryManagement (BootInfo * Info)
Definition at line 238 of file Memory.cpp.
 {
 #ifdef DEBUG
     for (uint64_t i = 0; i < Info->Memory.Entries; i++)
     {
         uintptr_t Base = r_cst(uintptr_t, Info->Memory.Entry[i].BaseAddress);
         size_t Length = Info->Memory.Entry[i].Length;
         uintptr_t End = Base + Length;
         const char *Type = "Unknown";
         switch (Info->Memory.Entry[i].Type)
         {
         case likely(Usable):
             Type = "Usable";
             break;
         case Reserved:
             Type = "Reserved";
             break;
         case ACPIReclaimable:
             Type = "ACPI Reclaimable";
             break;
         case ACPINVS:
             Type = "ACPI NVS";
             break;
         case BadMemory:
             Type = "Bad Memory";
             break;
         case BootloaderReclaimable:
             Type = "Bootloader Reclaimable";
             break;
         case KernelAndModules:
             Type = "Kernel and Modules";
             break;
         case Framebuffer:
             Type = "Framebuffer";
             break;
         default:
             break;
         }
         debug("%lld: %#016llx-%#016llx %s",
               i,
               Base,
               End,
               Type);
     }
 #endif
     trace("Initializing Physical Memory Manager");
     // KernelAllocator = Physical(); <- Already called in the constructor
     KernelAllocator.Init(Info);
     debug("Memory Info: %lldMB / %lldMB (%lldMB reserved)",
           TO_MB(KernelAllocator.GetUsedMemory()),
           TO_MB(KernelAllocator.GetTotalMemory()),
           TO_MB(KernelAllocator.GetReservedMemory()));
     /* -- Debugging --
         size_t bmap_size = KernelAllocator.GetPageBitmap().Size;
         for (size_t i = 0; i < bmap_size; i++)
         {
             bool idx = KernelAllocator.GetPageBitmap().Get(i);
             if (idx == true)
                 debug("Page %04d: %#lx", i, i * PAGE_SIZE);
         }
         inf_loop debug("Alloc.: %#lx", KernelAllocator.RequestPage());
     */
     trace("Initializing Virtual Memory Manager");
     KernelPageTable = (PageTable4 *)KernelAllocator.RequestPages(TO_PAGES(PAGE_SIZE + 1));
     memset(KernelPageTable, 0, PAGE_SIZE);
     if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
     {
         CPU::x86::AMD::CPUID0x80000001 cpuid;
         cpuid.Get();
         PSESupport = cpuid.EDX.PSE;
         Page1GBSupport = cpuid.EDX.Page1GB;
     }
     else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
     {
         CPU::x86::Intel::CPUID0x80000001 cpuid;
         cpuid.Get();
         fixme("Intel PSE support");
     }
     if (Page1GBSupport && PSESupport)
     {
         debug("1GB Page Support Enabled");
 #if defined(a64)
         CPU::x64::CR4 cr4 = CPU::x64::readcr4();
         cr4.PSE = 1;
         CPU::x64::writecr4(cr4);
 #elif defined(a32)
         CPU::x32::CR4 cr4 = CPU::x32::readcr4();
         cr4.PSE = 1;
         CPU::x32::writecr4(cr4);
 #elif defined(aa64)
 #endif
     }
     MapFromZero(KernelPageTable, Info);
     MapFramebuffer(KernelPageTable, Info);
     MapKernel(KernelPageTable, Info);
     trace("Applying new page table from address %#lx", KernelPageTable);
 #ifdef DEBUG
     tracepagetable(KernelPageTable);
 #endif
 #if defined(a86)
     asmv("mov %0, %%cr3" ::"r"(KernelPageTable));
 #elif defined(aa64)
     asmv("msr ttbr0_el1, %0" ::"r"(KernelPageTable));
 #endif
     debug("Page table updated.");
     if (strstr(Info->Kernel.CommandLine, "xallocv1"))
     {
         XallocV1Allocator = new Xalloc::V1((void *)KERNEL_HEAP_BASE, false, false);
         AllocatorType = MemoryAllocatorType::XallocV1;
         trace("XallocV1 Allocator initialized (%p)", XallocV1Allocator);
     }
     else if (strstr(Info->Kernel.CommandLine, "liballoc11"))
     {
         AllocatorType = MemoryAllocatorType::liballoc11;
     }
 }
References ACPINVS, ACPIReclaimable, AllocatorType, asmv, BadMemory, BootloaderReclaimable, x32::cpuid(), debug, fixme, Framebuffer, i, Info, KERNEL_HEAP_BASE, KernelAllocator, KernelAndModules, KernelPageTable, Length, likely, MapFramebuffer(), MapFromZero(), MapKernel(), memset(), Page1GBSupport, PAGE_SIZE, PSESupport, Reserved, strcmp(), strstr(), TO_PAGES, trace, Type, Usable, CPU::Vendor(), x86_CPUID_VENDOR_AMD, x86_CPUID_VENDOR_INTEL, and XallocV1Allocator.
Referenced by efi_main(), and Entry().
MapFramebuffer()
NIF void MapFramebuffer (PageTable4 * PT, BootInfo * Info)
Definition at line 107 of file Memory.cpp.
 {
     debug("Mapping Framebuffer");
     Virtual va = Virtual(PT);
     int itrfb = 0;
     while (1)
     {
         if (!Info->Framebuffer[itrfb].BaseAddress)
             break;
         va.OptimizedMap((void *)Info->Framebuffer[itrfb].BaseAddress,
                         (void *)Info->Framebuffer[itrfb].BaseAddress,
                         Info->Framebuffer[itrfb].Pitch * Info->Framebuffer[itrfb].Height,
                         PTFlag::RW | PTFlag::US | PTFlag::G);
         itrfb++;
 #ifdef DEBUG
         if (EnableExternalMemoryTracer)
         {
             char LockTmpStr[64];
             strcpy_unsafe(LockTmpStr, __FUNCTION__);
             strcat_unsafe(LockTmpStr, "_memTrk");
             mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
             sprintf(mExtTrkLog, "Rsrv( %p %ld )\n\r",
                     Info->Framebuffer[itrfb].BaseAddress,
                     (Info->Framebuffer[itrfb].Pitch * Info->Framebuffer[itrfb].Height) + PAGE_SIZE);
             UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
             for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
             {
                 if (mExtTrkLog[i] == '\r')
                     break;
                 mTrkUART.Write(mExtTrkLog[i]);
             }
             mExtTrkLock.Unlock();
         }
 #endif
     }
 }
References UniversalAsynchronousReceiverTransmitter::COM3, debug, G(), i, Info, PAGE_SIZE, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by InitializeMemoryManagement().
MapFromZero()
NIF void MapFromZero (PageTable4 * PT, BootInfo * Info)
Definition at line 77 of file Memory.cpp.
 {
     debug("Mapping from 0x0 to %#llx", Info->Memory.Size);
     Virtual va = Virtual(PT);
     size_t MemSize = Info->Memory.Size;
     if (Page1GBSupport && PSESupport)
     {
         /* Map the first 100MB of memory as 4KB pages */
         // uintptr_t Physical4KBSectionStart = 0x10000000;
         // va.Map((void *)0,
         //        (void *)0,
         //        Physical4KBSectionStart,
         //        PTFlag::RW);
         // va.Map((void *)Physical4KBSectionStart,
         //        (void *)Physical4KBSectionStart,
         //        MemSize - Physical4KBSectionStart,
         //        PTFlag::RW,
         //        Virtual::MapType::OneGB);
         va.Map((void *)0, (void *)0, MemSize, PTFlag::RW);
     }
     else
         va.Map((void *)0, (void *)0, MemSize, PTFlag::RW);
     va.Unmap((void *)0);
 }
References debug, Info, Page1GBSupport, and PSESupport.
Referenced by InitializeMemoryManagement().
MapKernel()
NIF void MapKernel (PageTable4 * PT, BootInfo * Info)
Definition at line 146 of file Memory.cpp.
 {
     debug("Mapping Kernel");
     uintptr_t KernelStart = (uintptr_t)&_kernel_start;
     uintptr_t KernelTextEnd = (uintptr_t)&_kernel_text_end;
     uintptr_t KernelDataEnd = (uintptr_t)&_kernel_data_end;
     uintptr_t KernelRoDataEnd = (uintptr_t)&_kernel_rodata_end;
     uintptr_t KernelEnd = (uintptr_t)&_kernel_end;
     uintptr_t KernelFileStart = (uintptr_t)Info->Kernel.FileBase;
     uintptr_t KernelFileEnd = KernelFileStart + Info->Kernel.Size;
     debug("File size: %ld KB", TO_KB(Info->Kernel.Size));
     debug(".text size: %ld KB", TO_KB(KernelTextEnd - KernelStart));
     debug(".data size: %ld KB", TO_KB(KernelDataEnd - KernelTextEnd));
     debug(".rodata size: %ld KB", TO_KB(KernelRoDataEnd - KernelDataEnd));
     debug(".bss size: %ld KB", TO_KB(KernelEnd - KernelRoDataEnd));
     uintptr_t BaseKernelMapAddress = (uintptr_t)Info->Kernel.PhysicalBase;
     uintptr_t k;
     Virtual va = Virtual(PT);
     /* Text section */
     for (k = KernelStart; k < KernelTextEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW | PTFlag::G);
         KernelAllocator.ReservePage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     /* Data section */
     for (k = KernelTextEnd; k < KernelDataEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW | PTFlag::G);
         KernelAllocator.ReservePage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     /* Read only data section */
     for (k = KernelDataEnd; k < KernelRoDataEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::G);
         KernelAllocator.ReservePage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     /* BSS section */
     for (k = KernelRoDataEnd; k < KernelEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW | PTFlag::G);
         KernelAllocator.ReservePage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     /* Kernel file */
     for (k = KernelFileStart; k < KernelFileEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)k, PTFlag::G);
         KernelAllocator.ReservePage((void *)k);
     }
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "Rsrv( %p %ld )\n\r",
                 Info->Kernel.PhysicalBase,
                 Info->Kernel.Size);
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         sprintf(mExtTrkLog, "Rsrv( %p %ld )\n\r",
                 Info->Kernel.VirtualBase,
                 Info->Kernel.Size);
         mExtTrkLock.Unlock();
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
     }
 #endif
 }
References UniversalAsynchronousReceiverTransmitter::COM3, debug, G(), i, Info, k, KernelAllocator, PAGE_SIZE, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by InitializeMemoryManagement().
operator delete() [1/2]
void operator delete (void * Pointer)
Definition at line 667 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete(%#lx)->[%s]", Pointer, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     free(Pointer);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "delete( %p )~%p\n\r",
                 Pointer,
                 __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
 }
References UniversalAsynchronousReceiverTransmitter::COM3, free(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, memdbg, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator delete() [2/2]
void operator delete (void * Pointer, long unsigned int Size)
Definition at line 727 of file Memory.cpp.
 {
     UNUSED(Size);
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete(%#lx, %d)->[%s]", Pointer, Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     free(Pointer);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "delete( %p %ld )~%p\n\r",
                 Pointer, Size,
                 __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
 }
References UniversalAsynchronousReceiverTransmitter::COM3, free(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, memdbg, Size, sprintf(), strcat_unsafe(), strcpy_unsafe(), UNUSED, and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator delete[]() [1/2]
void operator delete[] (void * Pointer)
Definition at line 697 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete[](%#lx)->[%s]", Pointer, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     free(Pointer);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "delete[]( %p )~%p\n\r",
                 Pointer,
                 __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
 }
References UniversalAsynchronousReceiverTransmitter::COM3, free(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, memdbg, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator delete[]() [2/2]
void operator delete[] (void * Pointer, long unsigned int Size)
Definition at line 758 of file Memory.cpp.
 {
     UNUSED(Size);
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete[](%#lx, %d)->[%s]", Pointer, Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     free(Pointer);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "delete[]( %p %ld )~%p\n\r",
                 Pointer, Size,
                 __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
 }
References UniversalAsynchronousReceiverTransmitter::COM3, free(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, memdbg, Size, sprintf(), strcat_unsafe(), strcpy_unsafe(), UNUSED, and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator new() [1/2]
void* operator new (size_t Size)
Definition at line 573 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("new(%d)->[%s]", Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     void *ret = malloc(Size);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "new( %ld )=%p~%p\n\r",
                 Size,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, malloc(), memdbg, ret, Size, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator new() [2/2]
void* operator new (unsigned long Size, std::align_val_t Alignment)
Definition at line 635 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("new(%d, %d)->[%s]", Size, Alignment, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     fixme("operator new with alignment(%#lx) is not implemented", Alignment);
     void *ret = malloc(Size);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "new( %ld %#lx )=%p~%p\n\r",
                 Size, (uintptr_t)Alignment,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References UniversalAsynchronousReceiverTransmitter::COM3, fixme, SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, malloc(), memdbg, ret, Size, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator new[]()
void* operator new[] (size_t Size)
Definition at line 604 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("new[](%d)->[%s]", Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     void *ret = malloc(Size);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "new[]( %ld )=%p~%p\n\r",
                 Size,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, malloc(), memdbg, ret, Size, sprintf(), strcat_unsafe(), strcpy_unsafe(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
Variable Documentation
AllocatorType
MemoryAllocatorType AllocatorType = MemoryAllocatorType::Pages static
Definition at line 54 of file Memory.cpp.
Referenced by calloc(), free(), InitializeMemoryManagement(), malloc(), and realloc().
KernelAllocator
Physical KernelAllocator
Definition at line 49 of file Memory.cpp.
Referenced by calloc(), Video::Display::CreateBuffer(), Tasking::Task::CreateProcess(), Video::Display::DeleteBuffer(), CrashHandler::DisplayTopOverlay(), Execute::ELFLoad(), Execute::ELFLoadRel(), Disk::Manager::FetchDisks(), Video::Font::Font(), free(), FreePage(), GlobalDescriptorTable::Init(), Interrupts::Initialize(), CPU::InitializeFeatures(), InitializeMemoryManagement(), liballoc_alloc(), liballoc_free(), malloc(), MapKernel(), Recovery::PlayAudio(), realloc(), Recovery::KernelRecovery::RecoveryThread(), Tasking::Task::RemoveProcess(), RequestPage(), Tasking::Task::RevertProcessCreation(), Execute::Spawn(), CrashHandler::UserInput(), Xalloc_FREE_PAGES(), and Xalloc_REQUEST_PAGES().
KernelPageTable
PageTable4* KernelPageTable = nullptr
Definition at line 50 of file Memory.cpp.
Referenced by Tasking::Task::CreateProcess(), PCI::PCI::EnumerateBus(), PCI::PCI::EnumerateDevice(), PCI::PCI::EnumerateFunction(), InitializeMemoryManagement(), ACPI::MADT::MADT(), MapMemory(), PCI::PCI::PCI(), UnmapMemory(), Xalloc_MAP_MEMORY(), and Xalloc_UNMAP_MEMORY().
Page1GBSupport
bool Page1GBSupport = false
Definition at line 51 of file Memory.cpp.
Referenced by InitializeMemoryManagement(), and MapFromZero().
PSESupport
bool PSESupport = false
Definition at line 52 of file Memory.cpp.
Referenced by InitializeMemoryManagement(), and MapFromZero().
XallocV1Allocator
Xalloc::V1* XallocV1Allocator = nullptr
Definition at line 55 of file Memory.cpp.
Referenced by calloc(), free(), InitializeMemoryManagement(), malloc(), and realloc().