Fennix: Kernel/syscalls/native/write.cpp File Reference
write.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
#include "../../ipc.h"
Macros
#define SysFrm SyscallsFrame
Functions
ssize_t sys_write (SysFrm *, int fildes, const void *buf, size_t nbyte)
Macro Definition Documentation
SysFrm
#define SysFrm SyscallsFrame
Definition at line 38 of file write.cpp.
Function Documentation
sys_write()
ssize_t sys_write (SysFrm * , int fildes, const void * buf, size_t nbyte)
Definition at line 47 of file write.cpp.
 {
     const void *safe_buf = nullptr;
     Tasking::PCB *pcb = thisProcess;
     Memory::SmartHeap sh(nbyte, pcb->vma);
     safe_buf = sh.Get();
     {
         Memory::SwapPT swap(pcb->PageTable);
         memcpy((void *)safe_buf, buf, nbyte);
     }
     function("%d, %p, %d", fildes, buf, nbyte);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_write(fildes, safe_buf, nbyte);
     if (ret)
         fdt->_lseek(fildes, ret, SEEK_CUR);
     return ret;
 }
References vfs::FileDescriptorTable::_lseek(), vfs::FileDescriptorTable::_write(), buf, Tasking::PCB::FileDescriptors, Memory::SmartHeap::Get(), memcpy, Tasking::PCB::PageTable, SEEK_CUR, swap(), thisProcess, and Tasking::PCB::vma.
Referenced by linux_write().