Fennix: Userspace/apps/base/bash/lib/malloc/malloc.c File Reference
malloc.c File Reference
#include <sys/types.h>
#include <signal.h>
#include <strings.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include "getpagesize.h"
#include "imalloc.h"
Data Structures
union mhead
union _malloc_guard
struct mhead.minfo
Macros
#define powerof2(x) ((((x) - 1) & (x)) == 0)
#define MALLOC_PAGESIZE_MIN 4096
#define MALLOC_INCR_PAGES 8192
#define ISALLOC ((char) 0xf7) /* magic byte that implies allocation */
#define ISFREE ((char) 0x54) /* magic byte that implies free block */
#define ISMEMALIGN
#define mh_alloc minfo.mi_alloc
#define mh_index minfo.mi_index
#define mh_nbytes minfo.mi_nbytes
#define mh_magic2 minfo.mi_magic2
#define mh_magic8 minfo.mi_magic8
#define MAGIC8_NUMBYTES 8
#define MALLOC_SIZE_T u_bits32_t
#define MOVERHEAD sizeof(union mhead)
#define MALIGN_MASK 15 /* one less than desired alignment */
#define CHAIN(a) (*(union mhead **) (sizeof (char *) + (char *) (a)))
#define MAGIC1 0x55
#define MAGIC2 0x5555
#define MSLOP 4 /* 4 bytes extra for u_bits32_t end guard size */
#define ALLOCATED_BYTES(n) (((n) + MOVERHEAD + MSLOP + MALIGN_MASK) & ~MALIGN_MASK)
#define ASSERT(p)
#define SPLIT_MIN 1 /* 64 */
#define SPLIT_MID 9 /* 16384 */
#define SPLIT_MAX 12 /* 131072 */
#define COMBINE_MIN 1 /* 64 */
#define COMBINE_MAX (pagebucket - 1) /* 2048 for 4096-byte pages */
#define LESSCORE_MIN 8 /* 8192 */
#define LESSCORE_FRC 11 /* 65536 */
#define PREPOP_BIN 1
#define PREPOP_SIZE 64
#define STARTBUCK 0
#define MMAP_THRESHOLD (8 * SIZEOF_LONG)
#define NBUCKETS 28
#define MALLOC_WRAPPER 0x01 /* wrapper function */
#define MALLOC_INTERNAL 0x02 /* internal function calling another */
#define MALLOC_NOTRACE 0x04 /* don't trace this allocation or free */
#define MALLOC_NOREG 0x08 /* don't register this allocation or free */
#define ERR_DUPFREE 0x01
#define ERR_UNALLOC 0x02
#define ERR_UNDERFLOW 0x04
#define ERR_ASSERT_FAILED 0x08
#define IN_BUCKET(nb, nu) ((nb) <= binsizes[(nu)])
#define RIGHT_BUCKET(nb, nu) (((nb) > binsizes[(nu)-1]) && ((nb) <= binsizes[(nu)]))
#define binsize(x) binsizes[(x)]
#define MAXALLOC_SIZE binsizes[NBUCKETS-1]
Typedefs
typedef union _malloc_guard mguard_t
Functions
static PTR_T internal_malloc PARAMS ((size_t, const char *, int, int))
static PTR_T internal_realloc PARAMS ((PTR_T, size_t, const char *, int, int))
static void internal_free PARAMS ((PTR_T, const char *, int, int))
static PTR_T internal_memalign PARAMS ((size_t, size_t, const char *, int, int))
static PTR_T internal_remap PARAMS ((PTR_T, size_t, int, int))
static void botch PARAMS ((const char *, const char *, int))
static void xbotch PARAMS ((PTR_T, int, const char *, const char *, int))
char * sbrk ()
static void botch (char *s, const char *file, int line) const
static void xbotch (PTR_T mem, int e, const char *s, const char *file, int line)
static void bcoalesce (int nu)
static void bsplit (int nu)
static void xsplit (union mhead *mp, int nu)
void _malloc_block_signals (sigset_t *setp, sigset_t *osetp)
void _malloc_unblock_signals (sigset_t *setp, sigset_t *osetp)
static void lesscore (int nu)
static void morecore (int nu)
static void malloc_debug_dummy ()
static int pagealign ()
static PTR_T internal_malloc (size_t n, const char *file, int line, int flags)
static void internal_free (PTR_T mem, const char *file, int line, int flags)
static PTR_T internal_realloc (PTR_T mem, size_t n, const char *file, int line, int flags)
static PTR_T internal_memalign (size_t alignment, size_t size, const char *file, int line, int flags)
int posix_memalign (void **memptr, size_t alignment, size_t size)
size_t malloc_usable_size (void *mem)
static PTR_T internal_valloc (size_t size, const char *file, int line, int flags)
static PTR_T internal_calloc (size_t n, size_t s, const char *file, int line, int flags)
static void internal_cfree (PTR_T p, const char *file, int line, int flags)
PTR_T sh_malloc (size_t bytes, const char *file, int line)
PTR_T sh_realloc (PTR_T ptr, size_t size, const char *file, int line)
void sh_free (PTR_T mem, const char *file, int line)
PTR_T sh_memalign (size_t alignment, size_t size, const char *file, int line)
PTR_T sh_calloc (size_t n, size_t s, const char *file, int line)
void sh_cfree (PTR_T mem, const char *file, int line)
PTR_T sh_valloc (size_t size, const char *file, int line)
PTR_T malloc (size_t size)
The standard function.
PTR_T realloc (PTR_T mem, size_t nbytes)
void free (PTR_T mem)
PTR_T memalign (size_t alignment, size_t size)
PTR_T valloc (size_t size)
PTR_T calloc (size_t n, size_t s)
The standard function.
void cfree (PTR_T mem)
Variables
static union mhead * nextf [NBUCKETS]
static char busy [NBUCKETS]
static int pagesz
static int pagebucket
static int maxbuck
static char * memtop
static const unsigned long binsizes [NBUCKETS]
int errno
int malloc_flags = 0
int malloc_trace = 0
int malloc_register = 0
int malloc_mmap_threshold = MMAP_THRESHOLD
Data Structure Documentation
mhead
union mhead
Definition at line 139 of file malloc.c.
Data Fields
bits64_t mh_align[2]
struct mhead minfo
_malloc_guard
union _malloc_guard
Definition at line 164 of file malloc.c.
Data Fields
u_bits32_t i
char s[4]
mhead.minfo
struct mhead.minfo
Definition at line 141 of file malloc.c.
Data Fields
char mi_alloc
char mi_index
u_bits16_t mi_magic2
char mi_magic8[8]
u_bits32_t mi_nbytes
Macro Definition Documentation
ALLOCATED_BYTES
#define ALLOCATED_BYTES (n) (((n) + MOVERHEAD + MSLOP + MALIGN_MASK) & ~MALIGN_MASK)
Definition at line 196 of file malloc.c.
ASSERT
#define ASSERT (p)
Value:
  do \
    { \
      if (!(p)) xbotch((PTR_T)0, ERR_ASSERT_FAILED, CPP_STRING(p), file, line); \
    } \
  while (0)
Definition at line 199 of file malloc.c.
binsize
#define binsize (x) binsizes[(x)]
Definition at line 299 of file malloc.c.
CHAIN
#define CHAIN (a) (*(union mhead **) (sizeof (char *) + (char *) (a)))
Definition at line 180 of file malloc.c.
COMBINE_MAX
#define COMBINE_MAX (pagebucket - 1) /* 2048 for 4096-byte pages */
Definition at line 214 of file malloc.c.
COMBINE_MIN
#define COMBINE_MIN 1 /* 64 */
Definition at line 213 of file malloc.c.
ERR_ASSERT_FAILED
#define ERR_ASSERT_FAILED 0x08
Definition at line 262 of file malloc.c.
ERR_DUPFREE
#define ERR_DUPFREE 0x01
Definition at line 259 of file malloc.c.
ERR_UNALLOC
#define ERR_UNALLOC 0x02
Definition at line 260 of file malloc.c.
ERR_UNDERFLOW
#define ERR_UNDERFLOW 0x04
Definition at line 261 of file malloc.c.
IN_BUCKET
#define IN_BUCKET (nb, nu) ((nb) <= binsizes[(nu)])
Definition at line 270 of file malloc.c.
ISALLOC
#define ISALLOC ((char) 0xf7) /* magic byte that implies allocation */
Definition at line 127 of file malloc.c.
ISFREE
#define ISFREE ((char) 0x54) /* magic byte that implies free block */
Definition at line 128 of file malloc.c.
ISMEMALIGN
#define ISMEMALIGN
Value:
                     ((char) 0xd6)  /* Stored before the value returned by
                     memalign, with the rest of the word
                     being the distance to the true
                     beginning of the block.  */
Definition at line 130 of file malloc.c.
LESSCORE_FRC
#define LESSCORE_FRC 11 /* 65536 */
Definition at line 217 of file malloc.c.
LESSCORE_MIN
#define LESSCORE_MIN 8 /* 8192 */
Definition at line 216 of file malloc.c.
MAGIC1
#define MAGIC1 0x55
Definition at line 188 of file malloc.c.
MAGIC2
#define MAGIC2 0x5555
Definition at line 189 of file malloc.c.
MAGIC8_NUMBYTES
#define MAGIC8_NUMBYTES 8
Definition at line 156 of file malloc.c.
MALIGN_MASK
#define MALIGN_MASK 15 /* one less than desired alignment */
Definition at line 161 of file malloc.c.
MALLOC_INCR_PAGES
#define MALLOC_INCR_PAGES 8192
Definition at line 125 of file malloc.c.
MALLOC_INTERNAL
#define MALLOC_INTERNAL 0x02 /* internal function calling another */
Definition at line 254 of file malloc.c.
MALLOC_NOREG
#define MALLOC_NOREG 0x08 /* don't register this allocation or free */
Definition at line 256 of file malloc.c.
MALLOC_NOTRACE
#define MALLOC_NOTRACE 0x04 /* don't trace this allocation or free */
Definition at line 255 of file malloc.c.
MALLOC_PAGESIZE_MIN
#define MALLOC_PAGESIZE_MIN 4096
Definition at line 124 of file malloc.c.
MALLOC_SIZE_T
#define MALLOC_SIZE_T u_bits32_t
Definition at line 157 of file malloc.c.
MALLOC_WRAPPER
#define MALLOC_WRAPPER 0x01 /* wrapper function */
Definition at line 253 of file malloc.c.
MAXALLOC_SIZE
#define MAXALLOC_SIZE binsizes[NBUCKETS-1]
Definition at line 301 of file malloc.c.
mh_alloc
#define mh_alloc minfo.mi_alloc
Definition at line 150 of file malloc.c.
mh_index
#define mh_index minfo.mi_index
Definition at line 151 of file malloc.c.
mh_magic2
#define mh_magic2 minfo.mi_magic2
Definition at line 153 of file malloc.c.
mh_magic8
#define mh_magic8 minfo.mi_magic8
Definition at line 154 of file malloc.c.
mh_nbytes
#define mh_nbytes minfo.mi_nbytes
Definition at line 152 of file malloc.c.
MMAP_THRESHOLD
#define MMAP_THRESHOLD (8 * SIZEOF_LONG)
Definition at line 239 of file malloc.c.
MOVERHEAD
#define MOVERHEAD sizeof(union mhead)
Definition at line 159 of file malloc.c.
MSLOP
#define MSLOP 4 /* 4 bytes extra for u_bits32_t end guard size */
Definition at line 191 of file malloc.c.
NBUCKETS
#define NBUCKETS 28
Definition at line 250 of file malloc.c.
powerof2
#define powerof2 (x) ((((x) - 1) & (x)) == 0)
Definition at line 117 of file malloc.c.
PREPOP_BIN
#define PREPOP_BIN 1
Definition at line 220 of file malloc.c.
PREPOP_SIZE
#define PREPOP_SIZE 64
Definition at line 221 of file malloc.c.
RIGHT_BUCKET
#define RIGHT_BUCKET (nb, nu) (((nb) > binsizes[(nu)-1]) && ((nb) <= binsizes[(nu)]))
Definition at line 273 of file malloc.c.
SPLIT_MAX
#define SPLIT_MAX 12 /* 131072 */
Definition at line 210 of file malloc.c.
SPLIT_MID
#define SPLIT_MID 9 /* 16384 */
Definition at line 209 of file malloc.c.
SPLIT_MIN
#define SPLIT_MIN 1 /* 64 */
Definition at line 208 of file malloc.c.
STARTBUCK
#define STARTBUCK 0
Definition at line 223 of file malloc.c.
Typedef Documentation
mguard_t
typedef union _malloc_guard mguard_t
Function Documentation
_malloc_block_signals()
void _malloc_block_signals (sigset_t * setp, sigset_t * osetp)
Definition at line 570 of file malloc.c.
 {
 #ifdef HAVE_POSIX_SIGNALS
   sigfillset (setp);
   sigemptyset (osetp);
   sigprocmask (SIG_BLOCK, setp, osetp);
 #else
 #  if defined (HAVE_BSD_SIGNALS)
   *osetp = sigsetmask (-1);
Referenced by morecore().
_malloc_unblock_signals()
void _malloc_unblock_signals (sigset_t * setp, sigset_t * osetp)
Definition at line 585 of file malloc.c.
 {
 #ifdef HAVE_POSIX_SIGNALS
   sigprocmask (SIG_SETMASK, osetp, (sigset_t *)NULL);
 #else
 #  if defined (HAVE_BSD_SIGNALS)
   sigsetmask (*osetp);
Referenced by morecore().
bcoalesce()
static void bcoalesce (int nu) static
Definition at line 395 of file malloc.c.
 {
   register union mhead *mp, *mp1, *mp2;
   register int nbuck;
   unsigned long siz;
   nbuck = nu - 1;
   if (nextf[nbuck] == 0 || busy[nbuck])
     return;
   busy[nbuck] = 1;
   siz = binsize (nbuck);
   mp2 = mp1 = nextf[nbuck];
   mp = CHAIN (mp1);
   while (mp && mp != (union mhead *)((char *)mp1 + siz))
     {
       mp2 = mp1;
       mp1 = mp;
       mp = CHAIN (mp);
     }
   if (mp == 0)
     {
       busy[nbuck] = 0;
       return;
     }
   /* OK, now we have mp1 pointing to the block we want to add to nextf[NU].
      CHAIN(mp2) must equal mp1.  Check that mp1 and mp are adjacent. */
   if (mp2 != mp1 && CHAIN(mp2) != mp1)
     {
       busy[nbuck] = 0;
       xbotch ((PTR_T)0, 0, "bcoalesce: CHAIN(mp2) != mp1", (char *)NULL, 0);
     }
 #ifdef MALLOC_DEBUG
   if (CHAIN (mp1) != (union mhead *)((char *)mp1 + siz))
     {
       busy[nbuck] = 0;
       return;   /* not adjacent */
     }
 #endif
   /* Since they are adjacent, remove them from the free list */
   if (mp1 == nextf[nbuck])
     nextf[nbuck] = CHAIN (mp);
   else
     CHAIN (mp2) = CHAIN (mp);
   busy[nbuck] = 0;
 #ifdef MALLOC_STATS
   _mstats.tbcoalesce++;
   _mstats.ncoalesce[nbuck]++;
 #endif
   /* And add the combined two blocks to nextf[NU]. */
   mp1->mh_alloc = ISFREE;
   mp1->mh_index = nu;
References binsize, busy, CHAIN, ISFREE, nextf, NULL, PTR_T, and xbotch().
Referenced by morecore().
botch()
static void botch (char * s, const char * file, int line) const static
Definition at line 359 of file malloc.c.
 {
   fprintf (stderr, _("malloc: failed assertion: %s\n"), s);
References _, abort(), fflush(), fprintf(), s, and stderr.
Referenced by xbotch().
bsplit()
static void bsplit (int nu) static
Definition at line 464 of file malloc.c.
 {
   register union mhead *mp;
   int nbuck, nblks, split_max;
   unsigned long siz;
   split_max = (maxbuck > SPLIT_MAX) ? maxbuck : SPLIT_MAX;
   if (nu >= SPLIT_MID)
     {
       for (nbuck = split_max; nbuck > nu; nbuck--)
     {
       if (busy[nbuck] || nextf[nbuck] == 0)
         continue;
       break;
     }
     }
   else
     {
       for (nbuck = nu + 1; nbuck <= split_max; nbuck++)
     {
       if (busy[nbuck] || nextf[nbuck] == 0)
         continue;
       break;
     }
     }
   if (nbuck > split_max || nbuck <= nu)
     return;
   /* XXX might want to split only if nextf[nbuck] has >= 2 blocks free
      and nbuck is below some threshold. */
   /* Remove the block from the chain of larger blocks. */
   busy[nbuck] = 1;
   mp = nextf[nbuck];
   nextf[nbuck] = CHAIN (mp);
   busy[nbuck] = 0;
 #ifdef MALLOC_STATS
   _mstats.tbsplit++;
   _mstats.nsplit[nbuck]++;
 #endif
   /* Figure out how many blocks we'll get. */
   siz = binsize (nu);
   nblks = binsize (nbuck) / siz;
   /* Split the block and put it on the requested chain. */
   nextf[nu] = mp;
   while (1)
     {
       mp->mh_alloc = ISFREE;
       mp->mh_index = nu;
       if (--nblks <= 0) break;
       CHAIN (mp) = (union mhead *)((char *)mp + siz);
       mp = (union mhead *)((char *)mp + siz);
References binsize, busy, CHAIN, ISFREE, maxbuck, nextf, SPLIT_MAX, and SPLIT_MID.
Referenced by morecore().
cfree()
void cfree (PTR_T mem)
Definition at line 1550 of file malloc.c.
 {
free()
void free (PTR_T mem)
Definition at line 1518 of file malloc.c.
 {
internal_calloc()
static PTR_T internal_calloc (size_t n, size_t s, const char * file, int line, int flags) static
Definition at line 1387 of file malloc.c.
 {
   size_t total;
   PTR_T result;
   total = n * s;
   result = internal_malloc (total, file, line, flags|MALLOC_INTERNAL);
   if (result)
References flags, internal_malloc(), MALLOC_INTERNAL, memset, n, PTR_T, s, and total.
Referenced by calloc(), and sh_calloc().
internal_cfree()
static void internal_cfree (PTR_T p, const char * file, int line, int flags) static
Definition at line 1403 of file malloc.c.
 {
internal_free()
static void internal_free (PTR_T mem, const char * file, int line, int flags) static
Definition at line 947 of file malloc.c.
 {
   register union mhead *p;
   register char *ap, *z;
   register int nunits;
   register MALLOC_SIZE_T nbytes;
   MALLOC_SIZE_T ubytes;     /* caller-requested size */
   mguard_t mg;
   if ((ap = (char *)mem) == 0)
     return;
   p = (union mhead *) ap - 1;
   if (p->mh_alloc == ISMEMALIGN)
     {
       ap -= p->mh_nbytes;
       p = (union mhead *) ap - 1;
     }
 #if defined (MALLOC_TRACE) || defined (MALLOC_REGISTER) || defined (MALLOC_WATCH)
   if (malloc_trace || malloc_register || _malloc_nwatch > 0)
     ubytes = p->mh_nbytes;
 #endif
   if (p->mh_alloc != ISALLOC)
     {
       if (p->mh_alloc == ISFREE)
     xbotch (mem, ERR_DUPFREE,
         _("free: called with already freed block argument"), file, line);
       else
     xbotch (mem, ERR_UNALLOC,
         _("free: called with unallocated block argument"), file, line);
     }
   ASSERT (p->mh_magic2 == MAGIC2);
   nunits = p->mh_index;
   nbytes = ALLOCATED_BYTES(p->mh_nbytes);
   /* The MAGIC8_NUMBYTES bytes before the memory handed to the user are now
      used for a simple check to catch things like p[-1] = 'x'.
      We sanity-check the value of mh_nbytes against the size of the blocks
      in the appropriate bucket before we use it.  This can still cause problems
      and obscure errors if mh_nbytes is wrong but still within range; the
      checks against the size recorded at the end of the chunk will probably
      fail then. Using MALLOC_REGISTER will help here, since it saves the
      original number of bytes requested. */
   if (IN_BUCKET(nbytes, nunits) == 0)
     xbotch (mem, ERR_UNDERFLOW,
         _("free: underflow detected; mh_nbytes out of range"), file, line);
   {
     int i;
     for (i = 0, z = p->mh_magic8; i < MAGIC8_NUMBYTES; i++)
       if (*z++ != MAGIC1)
     xbotch (mem, ERR_UNDERFLOW,
         _("free: underflow detected; magic8 corrupted"), file, line);
   }
   ap += p->mh_nbytes;
   z = mg.s;
   *z++ = *ap++, *z++ = *ap++, *z++ = *ap++, *z++ = *ap++;
   if (mg.i != p->mh_nbytes)
     xbotch (mem, ERR_ASSERT_FAILED, _("free: start and end chunk sizes differ"), file, line);
 #if defined (USE_MMAP)
   if (nunits > malloc_mmap_threshold)
     {
       munmap (p, binsize (nunits));
 #if defined (MALLOC_STATS)
       _mstats.nlesscore[nunits]++;
 #endif
       goto free_return;
     }
 #endif
 #if defined (USE_LESSCORE)
   /* We take care of the mmap case and munmap above */
   if (nunits >= LESSCORE_MIN && ((char *)p + binsize(nunits) == memtop))
     {
       /* If above LESSCORE_FRC, give back unconditionally.  This should be set
      high enough to be infrequently encountered.  If between LESSCORE_MIN
      and LESSCORE_FRC, call lesscore if the bucket is marked as busy or if
      there's already a block on the free list. */
       if ((nunits >= LESSCORE_FRC) || busy[nunits] || nextf[nunits] != 0)
     {
       lesscore (nunits);
       /* keeps the tracing and registering code in one place */
       goto free_return;
     }
     }
 #endif /* USE_LESSCORE */
 #ifdef MEMSCRAMBLE
   if (p->mh_nbytes)
     MALLOC_MEMSET (mem, 0xcf, p->mh_nbytes);
 #endif
   ASSERT (nunits < NBUCKETS);
   if (busy[nunits] == 1)
     {
       xsplit (p, nunits);   /* split block and add to different chain */
       goto free_return;
     }
   p->mh_alloc = ISFREE;
   /* Protect against signal handlers calling malloc.  */
   busy[nunits] = 1;
   /* Put this block on the free list.  */
   CHAIN (p) = nextf[nunits];
   nextf[nunits] = p;
   busy[nunits] = 0;
 free_return:
   ;     /* Empty statement in case this is the end of the function */
 #ifdef MALLOC_STATS
   _mstats.nmalloc[nunits]--;
   _mstats.nfre++;
 #endif /* MALLOC_STATS */
 #ifdef MALLOC_TRACE
   if (malloc_trace && (flags & MALLOC_NOTRACE) == 0)
     mtrace_free (mem, ubytes, file, line);
   else if (_malloc_trace_buckets[nunits])
     mtrace_free (mem, ubytes, file, line);
 #endif
 #ifdef MALLOC_REGISTER
   if (malloc_register && (flags & MALLOC_NOREG) == 0)
     mregister_free (mem, ubytes, file, line);
 #endif
 #ifdef MALLOC_WATCH
   if (_malloc_nwatch > 0)
Referenced by internal_realloc().
internal_malloc()
static PTR_T internal_malloc (size_t n, const char * file, int line, int flags) static
Definition at line 825 of file malloc.c.
 {
   register union mhead *p;
   register int nunits;
   register char *m, *z;
   MALLOC_SIZE_T nbytes;
   mguard_t mg;
   /* Get the system page size and align break pointer so future sbrks will
      be page-aligned.  The page size must be at least 1K -- anything
      smaller is increased. */
   if (pagesz == 0)
     if (pagealign () < 0)
       return ((PTR_T)NULL);
   /* Figure out how many bytes are required, rounding up to the nearest
      multiple of 8, then figure out which nextf[] area to use.  Try to
      be smart about where to start searching -- if the number of bytes
      needed is greater than the page size, we can start at pagebucket. */
 #if SIZEOF_SIZE_T == 8
   if (ALLOCATED_BYTES(n) > MAXALLOC_SIZE)
     return ((PTR_T) NULL);
 #endif
   nbytes = ALLOCATED_BYTES(n);
   nunits = (nbytes <= (pagesz >> 1)) ? STARTBUCK : pagebucket;
   for ( ; nunits < NBUCKETS; nunits++)
     if (nbytes <= binsize(nunits))
       break;
   /* Silently reject too-large requests. XXX - can increase this if HAVE_MMAP */
   if (nunits >= NBUCKETS)
     return ((PTR_T) NULL);
   /* In case this is reentrant use of malloc from signal handler,
      pick a block size that no other malloc level is currently
      trying to allocate.  That's the easiest harmless way not to
      interfere with the other level of execution.  */
 #ifdef MALLOC_STATS
   if (busy[nunits]) _mstats.nrecurse++;
 #endif
   while (busy[nunits]) nunits++;
   busy[nunits] = 1;
   if (nunits > maxbuck)
     maxbuck = nunits;
   /* If there are no blocks of the appropriate size, go get some */
   if (nextf[nunits] == 0)
     morecore (nunits);
   /* Get one block off the list, and set the new list head */
   if ((p = nextf[nunits]) == NULL)
     {
       busy[nunits] = 0;
       return NULL;
     }
   nextf[nunits] = CHAIN (p);
   busy[nunits] = 0;
   /* Check for free block clobbered */
   /* If not for this check, we would gobble a clobbered free chain ptr
      and bomb out on the NEXT allocate of this size block */
   if (p->mh_alloc != ISFREE || p->mh_index != nunits)
     xbotch ((PTR_T)(p+1), 0, _("malloc: block on free list clobbered"), file, line);
   /* Fill in the info, and set up the magic numbers for range checking. */
   p->mh_alloc = ISALLOC;
   p->mh_magic2 = MAGIC2;
   p->mh_nbytes = n;
   /* Begin guard */
   MALLOC_MEMSET ((char *)p->mh_magic8, MAGIC1, MAGIC8_NUMBYTES);
   /* End guard */
   mg.i = n;
   z = mg.s;
   m = (char *) (p + 1) + n;
   *m++ = *z++, *m++ = *z++, *m++ = *z++, *m++ = *z++;
 #ifdef MEMSCRAMBLE
   if (n)
     MALLOC_MEMSET ((char *)(p + 1), 0xdf, n);   /* scramble previous contents */
 #endif
 #ifdef MALLOC_STATS
   _mstats.nmalloc[nunits]++;
   _mstats.tmalloc[nunits]++;
   _mstats.nmal++;
   _mstats.bytesreq += n;
 #endif /* MALLOC_STATS */
 #ifdef MALLOC_TRACE
   if (malloc_trace && (flags & MALLOC_NOTRACE) == 0)
     mtrace_alloc ("malloc", p + 1, n, file, line);
   else if (_malloc_trace_buckets[nunits])
     mtrace_alloc ("malloc", p + 1, n, file, line);
 #endif
 #ifdef MALLOC_REGISTER
   if (malloc_register && (flags & MALLOC_NOREG) == 0)
     mregister_alloc ("malloc", p + 1, n, file, line);
 #endif
 #ifdef MALLOC_WATCH
   if (_malloc_nwatch > 0)
     _malloc_ckwatch (p + 1, file, line, W_ALLOC, n);
 #endif
 #if defined (MALLOC_DEBUG)
   z = (char *) (p + 1);
   /* Check alignment of returned pointer */
   if ((unsigned long)z & MALIGN_MASK)
     fprintf (stderr, "malloc: %s:%d: warning: request for %d bytes not aligned on %d byte boundary\r\n",
     file ? file : _("unknown"), line, p->mh_nbytes, MALIGN_MASK+1);
 #endif
Referenced by internal_calloc(), internal_realloc(), malloc(), and sh_malloc().
internal_memalign()
static PTR_T internal_memalign (size_t alignment, size_t size, const char * file, int line, int flags) static
Definition at line 1294 of file malloc.c.
 {
   register char *ptr;
   register char *aligned;
   register union mhead *p;
   ptr = internal_malloc (size + alignment, file, line, MALLOC_INTERNAL);
   if (ptr == 0)
     return 0;
   /* If entire block has the desired alignment, just accept it.  */
   if (((long) ptr & (alignment - 1)) == 0)
     return ptr;
   /* Otherwise, get address of byte in the block that has that alignment.  */
   aligned = (char *) (((long) ptr + alignment - 1) & (~alignment + 1));
   /* Store a suitable indication of how to free the block,
      so that free can find the true beginning of it.  */
   p = (union mhead *) aligned - 1;
   p->mh_nbytes = aligned - ptr;
   p->mh_alloc = ISMEMALIGN;
Referenced by internal_valloc().
internal_realloc()
static PTR_T internal_realloc (PTR_T mem, size_t n, const char * file, int line, int flags) static
Definition at line 1143 of file malloc.c.
 {
   register union mhead *p;
   register MALLOC_SIZE_T tocopy;
   register MALLOC_SIZE_T nbytes;
   register int newunits, nunits;
   register char *m, *z;
   mguard_t mg;
 #ifdef MALLOC_STATS
   _mstats.nrealloc++;
 #endif
   if (n == 0)
     {
       internal_free (mem, file, line, MALLOC_INTERNAL);
       return (NULL);
     }
   if ((p = (union mhead *) mem) == 0)
     return internal_malloc (n, file, line, MALLOC_INTERNAL);
   p--;
   nunits = p->mh_index;
   ASSERT (nunits < NBUCKETS);
   if (p->mh_alloc != ISALLOC)
     xbotch (mem, ERR_UNALLOC,
         _("realloc: called with unallocated block argument"), file, line);
   ASSERT (p->mh_magic2 == MAGIC2);
   nbytes = ALLOCATED_BYTES(p->mh_nbytes);
   /* Since the sizeof(u_bits32_t) bytes before the memory handed to the user
      are now used for the number of bytes allocated, a simple check of
      mh_magic2 is no longer sufficient to catch things like p[-1] = 'x'.
      We sanity-check the value of mh_nbytes against the size of the blocks
      in the appropriate bucket before we use it.  This can still cause problems
      and obscure errors if mh_nbytes is wrong but still within range; the
      checks against the size recorded at the end of the chunk will probably
      fail then.  Using MALLOC_REGISTER will help here, since it saves the
      original number of bytes requested. */
   if (IN_BUCKET(nbytes, nunits) == 0)
     xbotch (mem, ERR_UNDERFLOW,
         _("realloc: underflow detected; mh_nbytes out of range"), file, line);
   {
     int i;
     for (i = 0, z = p->mh_magic8; i < MAGIC8_NUMBYTES; i++)
       if (*z++ != MAGIC1)
     xbotch (mem, ERR_UNDERFLOW,
         _("realloc: underflow detected; magic8 corrupted"), file, line);
   }
   m = (char *)mem + (tocopy = p->mh_nbytes);
   z = mg.s;
   *z++ = *m++, *z++ = *m++, *z++ = *m++, *z++ = *m++;
   if (mg.i != p->mh_nbytes)
     xbotch (mem, ERR_ASSERT_FAILED, _("realloc: start and end chunk sizes differ"), file, line);
 #ifdef MALLOC_WATCH
   if (_malloc_nwatch > 0)
     _malloc_ckwatch (p + 1, file, line, W_REALLOC, n);
 #endif
 #ifdef MALLOC_STATS
   _mstats.bytesreq += (n < tocopy) ? 0 : n - tocopy;
 #endif
   /* If we're reallocating to the same size as previously, return now */
   if (n == p->mh_nbytes)
     return mem;
 #if SIZEOF_SIZE_T == 8
   if (ALLOCATED_BYTES(n) > MAXALLOC_SIZE)
     return ((PTR_T) NULL);
 #endif
   /* See if desired size rounds to same power of 2 as actual size. */
   nbytes = ALLOCATED_BYTES(n);
   /* If ok, use the same block, just marking its size as changed.  */
   if (RIGHT_BUCKET(nbytes, nunits) || RIGHT_BUCKET(nbytes, nunits-1))
     {
       /* Compensate for increment above. */
       m -= 4;
       *m++ = 0;  *m++ = 0;  *m++ = 0;  *m++ = 0;
       m = (char *)mem + (p->mh_nbytes = n);
       mg.i = n;
       z = mg.s;
       *m++ = *z++, *m++ = *z++, *m++ = *z++, *m++ = *z++;
       return mem;
     }
   if (n < tocopy)
     tocopy = n;
 #ifdef MALLOC_STATS
   _mstats.nrcopy++;
 #endif
 #if USE_MREMAP == 1
   /* If we are using mmap and have mremap, we use it here. Make sure that
      the old size and new size are above the threshold where we use mmap */
   if (nbytes > p->mh_nbytes)
     newunits = nunits;
   else
     newunits = (nbytes <= (pagesz >> 1)) ? STARTBUCK : pagebucket;
   for ( ; newunits < NBUCKETS; newunits++)
     if (nbytes <= binsize(newunits))
      break;
   if (nunits > malloc_mmap_threshold && newunits > malloc_mmap_threshold)
     {
       m = internal_remap (mem, n, newunits, MALLOC_INTERNAL);
       if (m == 0)
         return 0;
     }
   else
 #endif /* USE_MREMAP */
     {
   if ((m = internal_malloc (n, file, line, MALLOC_INTERNAL|MALLOC_NOTRACE|MALLOC_NOREG)) == 0)
     return 0;
   FASTCOPY (mem, m, tocopy);
   internal_free (mem, file, line, MALLOC_INTERNAL);
     }
 #ifdef MALLOC_TRACE
   if (malloc_trace && (flags & MALLOC_NOTRACE) == 0)
     mtrace_alloc ("realloc", m, n, file, line);
   else if (_malloc_trace_buckets[nunits])
     mtrace_alloc ("realloc", m, n, file, line);
 #endif
 #ifdef MALLOC_REGISTER
   if (malloc_register && (flags & MALLOC_NOREG) == 0)
     mregister_alloc ("realloc", m, n, file, line);
 #endif
 #ifdef MALLOC_WATCH
   if (_malloc_nwatch > 0)
     _malloc_ckwatch (m, file, line, W_RESIZED, n);
 #endif
References _, ALLOCATED_BYTES, ASSERT, binsize, ERR_ASSERT_FAILED, ERR_UNALLOC, ERR_UNDERFLOW, FASTCOPY, flags, i, _malloc_guard::i, IN_BUCKET, internal_free(), internal_malloc(), ISALLOC, MAGIC1, MAGIC2, MAGIC8_NUMBYTES, MALLOC_INTERNAL, malloc_mmap_threshold, MALLOC_NOREG, MALLOC_NOTRACE, malloc_register, MALLOC_SIZE_T, malloc_trace, MAXALLOC_SIZE, mem, n, NBUCKETS, NULL, p, pagebucket, pagesz, PTR_T, RIGHT_BUCKET, _malloc_guard::s, STARTBUCK, and xbotch().
internal_valloc()
static PTR_T internal_valloc (size_t size, const char * file, int line, int flags) static
Definition at line 1376 of file malloc.c.
 {
References flags, getpagesize(), internal_memalign(), MALLOC_INTERNAL, and size.
Referenced by sh_valloc(), and valloc().
lesscore()
static void lesscore (int nu) static
Definition at line 602 of file malloc.c.
 {
   long siz;
   siz = binsize (nu);
   /* Should check for errors here, I guess. */
   sbrk (-siz);
   memtop -= siz;
 #ifdef MALLOC_STATS
   _mstats.nsbrk++;
   _mstats.tsbrk -= siz;
References binsize, memtop, and sbrk().
malloc_debug_dummy()
static void malloc_debug_dummy () static
Definition at line 752 of file malloc.c.
 {
malloc_usable_size()
size_t malloc_usable_size (void * mem)
Definition at line 1346 of file malloc.c.
 {
   register union mhead *p;
   register char *ap;
   if ((ap = (char *)mem) == 0)
     return 0;
   /* Find the true start of the memory block to discover which bin */
   p = (union mhead *) ap - 1;
   if (p->mh_alloc == ISMEMALIGN)
     {
       ap -= p->mh_nbytes;
       p = (union mhead *) ap - 1;
     }
   /* return 0 if ISFREE */
   if (p->mh_alloc == ISFREE)
     return 0;
memalign()
PTR_T memalign (size_t alignment, size_t size)
Definition at line 1525 of file malloc.c.
 {
Referenced by valloc().
morecore()
static void morecore (int nu) static
Definition at line 622 of file malloc.c.
 {
   register union mhead *mp;
   register int nblks;
   register long siz;
   long sbrk_amt;        /* amount to get via sbrk() */
   sigset_t set, oset;
   int blocked_sigs;
   /* Block all signals in case we are executed from a signal handler. */
   blocked_sigs = 0;
 #ifdef SHELL
 #  if defined (SIGCHLD)
   if (running_trap || signal_is_trapped (SIGINT) || signal_is_trapped (SIGCHLD))
 #  else
   if (running_trap || signal_is_trapped (SIGINT))
 #  endif
 #endif
     {
       _malloc_block_signals (&set, &oset);
       blocked_sigs = 1;
     }
   siz = binsize (nu);   /* size of desired block for nextf[nu] */
   if (siz < 0)
     goto morecore_done;     /* oops */
 #ifdef MALLOC_STATS
   _mstats.nmorecore[nu]++;
 #endif
   /* Try to split a larger block here, if we're within the range of sizes
      to split. */
   if (nu >= SPLIT_MIN && nu <= malloc_mmap_threshold)
     {
       bsplit (nu);
       if (nextf[nu] != 0)
     goto morecore_done;
     }
   /* Try to coalesce two adjacent blocks from the free list on nextf[nu - 1],
      if we can, and we're within the range of the block coalescing limits. */
   if (nu >= COMBINE_MIN && nu < COMBINE_MAX && nu <= malloc_mmap_threshold && busy[nu - 1] == 0 && nextf[nu - 1])
     {
       bcoalesce (nu);
       if (nextf[nu] != 0)
     goto morecore_done;
     }
   /* Take at least a page, and figure out how many blocks of the requested
      size we're getting. */
   if (siz <= pagesz)
     {
       sbrk_amt = pagesz;
       nblks = sbrk_amt / siz;
     }
   else
     {
       /* We always want to request an integral multiple of the page size
      from the kernel, so let's compute whether or not `siz' is such
      an amount.  If it is, we can just request it.  If not, we want
      the smallest integral multiple of pagesize that is larger than
      `siz' and will satisfy the request. */
       sbrk_amt = siz & (pagesz - 1);
       if (sbrk_amt == 0)
     sbrk_amt = siz;
       else
     sbrk_amt = siz + pagesz - sbrk_amt;
       nblks = 1;
     }
 #if defined (USE_MMAP)
   if (nu > malloc_mmap_threshold)
     {
       mp = (union mhead *)mmap (0, sbrk_amt, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
       if ((void *)mp == MAP_FAILED)
     goto morecore_done;
       nextf[nu] = mp;
       mp->mh_alloc = ISFREE;
       mp->mh_index = nu;
       CHAIN (mp) = 0;
 #ifdef MALLOC_STATS
       _mstats.nmmap++;
       _mstats.tmmap += sbrk_amt;
 #endif
       goto morecore_done;
     }
 #endif
 #ifdef MALLOC_STATS
   _mstats.nsbrk++;
   _mstats.tsbrk += sbrk_amt;
 #endif
   mp = (union mhead *) sbrk (sbrk_amt);
   /* Totally out of memory. */
   if ((long)mp == -1)
     goto morecore_done;
   memtop += sbrk_amt;
   /* shouldn't happen, but just in case -- require 8- or 16-byte alignment */
   if ((long)mp & MALIGN_MASK)
     {
       mp = (union mhead *) (((long)mp + MALIGN_MASK) & ~MALIGN_MASK);
       nblks--;
     }
   /* save new header and link the nblks blocks together */
   nextf[nu] = mp;
   while (1)
     {
       mp->mh_alloc = ISFREE;
       mp->mh_index = nu;
       if (--nblks <= 0) break;
       CHAIN (mp) = (union mhead *)((char *)mp + siz);
       mp = (union mhead *)((char *)mp + siz);
     }
   CHAIN (mp) = 0;
 morecore_done:
References _malloc_block_signals(), _malloc_unblock_signals(), bcoalesce(), binsize, bsplit(), busy, CHAIN, COMBINE_MAX, COMBINE_MIN, ISFREE, MALIGN_MASK, malloc_mmap_threshold, MAP_ANONYMOUS, MAP_FAILED, MAP_PRIVATE, memtop, mmap(), nextf, pagesz, PROT_READ, PROT_WRITE, running_trap, sbrk(), SIGCHLD, SIGINT, signal_is_trapped(), and SPLIT_MIN.
pagealign()
static int pagealign () static
Definition at line 758 of file malloc.c.
 {
   register int nunits;
   register union mhead *mp;
   long sbrk_needed;
   char *curbrk;
   pagesz = getpagesize ();
   if (pagesz < MALLOC_PAGESIZE_MIN)
     pagesz = MALLOC_PAGESIZE_MIN;
   /* OK, how much do we need to allocate to make things page-aligned?
      Some of this partial page will be wasted space, but we'll use as
      much as we can.  Once we figure out how much to advance the break
      pointer, go ahead and do it. */
   memtop = curbrk = sbrk (0);
   sbrk_needed = pagesz - ((long)curbrk & (pagesz - 1)); /* sbrk(0) % pagesz */
   if (sbrk_needed < 0)
     sbrk_needed += pagesz;
   /* Now allocate the wasted space. */
   if (sbrk_needed)
     {
 #ifdef MALLOC_STATS
       _mstats.nsbrk++;
       _mstats.tsbrk += sbrk_needed;
 #endif
       curbrk = sbrk (sbrk_needed);
       if ((long)curbrk == -1)
     return -1;
       memtop += sbrk_needed;
       /* Take the memory which would otherwise be wasted and populate the most
      popular bin (3 == 64 bytes) with it.  Add whatever we need to curbrk
      to make things 64-byte aligned, compute how many 64-byte chunks we're
      going to get, and set up the bin. */
       curbrk += sbrk_needed & (PREPOP_SIZE - 1);
       sbrk_needed -= sbrk_needed & (PREPOP_SIZE - 1);
       nunits = sbrk_needed / PREPOP_SIZE;
       if (nunits > 0)
     {
       mp = (union mhead *)curbrk;
       nextf[PREPOP_BIN] = mp;
       while (1)
         {
           mp->mh_alloc = ISFREE;
           mp->mh_index = PREPOP_BIN;
           if (--nunits <= 0) break;
           CHAIN(mp) = (union mhead *)((char *)mp + PREPOP_SIZE);
           mp = (union mhead *)((char *)mp + PREPOP_SIZE);
         }
       CHAIN(mp) = 0;
     }
     }
   /* compute which bin corresponds to the page size. */
   for (nunits = 7; nunits < NBUCKETS; nunits++)
     if (pagesz <= binsize(nunits))
       break;
   pagebucket = nunits;
PARAMS() [1/7]
static void botch PARAMS ((const char *, const char *, int)) static
PARAMS() [2/7]
static void internal_free PARAMS ((PTR_T, const char *, int, int)) static
PARAMS() [3/7]
static void xbotch PARAMS ((PTR_T, int, const char *, const char *, int)) static
PARAMS() [4/7]
static PTR_T internal_realloc PARAMS ((PTR_T, size_t, const char *, int, int)) static
PARAMS() [5/7]
static PTR_T internal_remap PARAMS ((PTR_T, size_t, int, int)) static
PARAMS() [6/7]
static PTR_T internal_malloc PARAMS ((size_t, const char *, int, int)) static
PARAMS() [7/7]
static PTR_T internal_memalign PARAMS ((size_t, size_t, const char *, int, int)) static
posix_memalign()
int posix_memalign (void ** memptr, size_t alignment, size_t size)
Definition at line 1324 of file malloc.c.
 {
   void *mem;
   /* Perform posix-mandated error checking here */
   if ((alignment % sizeof (void *) != 0) || alignment == 0)
     return EINVAL;
   else if (powerof2 (alignment) == 0)
     return EINVAL;
   mem = internal_memalign (alignment, size, (char *)0, 0, 0);
   if (mem != 0)
     {
       *memptr = mem;
       return 0;
realloc()
PTR_T realloc (PTR_T mem, size_t nbytes)
Definition at line 1510 of file malloc.c.
 {
sbrk()
char* sbrk ()
Referenced by lesscore(), and morecore().
sh_calloc()
PTR_T sh_calloc (size_t n, size_t s, const char * file, int line)
Definition at line 1469 of file malloc.c.
 {
References internal_calloc(), MALLOC_WRAPPER, n, and s.
sh_cfree()
void sh_cfree (PTR_T mem, const char * file, int line)
Definition at line 1478 of file malloc.c.
 {
sh_free()
void sh_free (PTR_T mem, const char * file, int line)
Definition at line 1449 of file malloc.c.
 {
sh_malloc()
PTR_T sh_malloc (size_t bytes, const char * file, int line)
Definition at line 1430 of file malloc.c.
 {
References internal_malloc(), and MALLOC_WRAPPER.
sh_memalign()
PTR_T sh_memalign (size_t alignment, size_t size, const char * file, int line)
Definition at line 1458 of file malloc.c.
 {
sh_realloc()
PTR_T sh_realloc (PTR_T ptr, size_t size, const char * file, int line)
Definition at line 1439 of file malloc.c.
 {
sh_valloc()
PTR_T sh_valloc (size_t size, const char * file, int line)
Definition at line 1489 of file malloc.c.
 {
References internal_valloc(), MALLOC_WRAPPER, and size.
valloc()
PTR_T valloc (size_t size)
Definition at line 1534 of file malloc.c.
 {
References internal_valloc(), NULL, and size.
xbotch()
static void xbotch (PTR_T mem, int e, const char * s, const char * file, int line) static
Definition at line 373 of file malloc.c.
 {
   fprintf (stderr, _("\r\nmalloc: %s:%d: assertion botched\r\n"),
             file ? file : _("unknown"), line);
 #ifdef MALLOC_REGISTER
   if (mem != NULL && malloc_register)
     mregister_describe_mem (mem, stderr);
 #endif
References _, botch(), fflush(), fprintf(), malloc_register, mem, NULL, s, and stderr.
Referenced by bcoalesce(), and internal_realloc().
xsplit()
static void xsplit (union mhead * mp, int nu) static
Definition at line 529 of file malloc.c.
 {
   union mhead *nh;
   int nbuck, nblks, split_max;
   unsigned long siz;
   nbuck = nu - 1;
   while (nbuck >= SPLIT_MIN && busy[nbuck])
     nbuck--;
   if (nbuck < SPLIT_MIN)
     return;
 #ifdef MALLOC_STATS
   _mstats.tbsplit++;
   _mstats.nsplit[nu]++;
 #endif
   /* Figure out how many blocks we'll get. */
   siz = binsize (nu);           /* original block size */
   nblks = siz / binsize (nbuck);    /* should be 2 most of the time */
   /* And add it to nextf[nbuck] */
   siz = binsize (nbuck);        /* XXX - resetting here */
   nh = mp;
   while (1)
     {
       mp->mh_alloc = ISFREE;
       mp->mh_index = nbuck;
       if (--nblks <= 0) break;
       CHAIN (mp) = (union mhead *)((char *)mp + siz);
       mp = (union mhead *)((char *)mp + siz);
     }
   busy[nbuck] = 1;
   CHAIN (mp) = nextf[nbuck];
References binsize, busy, CHAIN, ISFREE, nextf, and SPLIT_MIN.
Variable Documentation
binsizes
const unsigned long binsizes[NBUCKETS] static
Initial value:
= {
    32UL, 64UL, 128UL, 256UL, 512UL, 1024UL, 2048UL, 4096UL,
    8192UL, 16384UL, 32768UL, 65536UL, 131072UL, 262144UL, 524288UL,
    1048576UL, 2097152UL, 4194304UL, 8388608UL, 16777216UL, 33554432UL,
    67108864UL, 134217728UL, 268435456UL, 536870912UL, 1073741824UL,
    2147483648UL, 4294967295UL
}
Definition at line 290 of file malloc.c.
busy
char busy[NBUCKETS] static
Definition at line 282 of file malloc.c.
Referenced by bcoalesce(), bsplit(), morecore(), and xsplit().
errno
int errno extern
Referenced by __bin_chunk(), __expand_heap(), adjust_size(), alloc_meta(), and unmap_chunk().
malloc_flags
int malloc_flags = 0
Definition at line 342 of file malloc.c.
malloc_mmap_threshold
int malloc_mmap_threshold = MMAP_THRESHOLD
Definition at line 347 of file malloc.c.
Referenced by internal_realloc(), and morecore().
malloc_register
int malloc_register = 0
Definition at line 344 of file malloc.c.
Referenced by internal_realloc(), malloc_set_register(), and xbotch().
malloc_trace
int malloc_trace = 0
Definition at line 343 of file malloc.c.
Referenced by internal_realloc(), and malloc_set_trace().
maxbuck
int maxbuck static
Definition at line 286 of file malloc.c.
Referenced by bsplit().
memtop
char* memtop static
Definition at line 288 of file malloc.c.
Referenced by lesscore(), and morecore().
nextf
union mhead* nextf[NBUCKETS] static
Definition at line 278 of file malloc.c.
Referenced by bcoalesce(), bsplit(), morecore(), and xsplit().
pagebucket
int pagebucket static
Definition at line 285 of file malloc.c.
Referenced by internal_realloc().
pagesz
int pagesz static
Definition at line 284 of file malloc.c.
Referenced by internal_realloc(), mal0_clear(), and morecore().