Fennix: Userspace/apps/base/busybox/util-linux/last.c File Reference
last.c File Reference
#include "libbb.h"
Macros
#define SHUTDOWN_TIME 254
Functions
int last_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int last_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Macro Definition Documentation
SHUTDOWN_TIME
#define SHUTDOWN_TIME 254
Definition at line 48 of file last.c.
Function Documentation
last_main() [1/2]
int last_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 70 of file last.c.
 {
     struct utmpx ut;
     int n, file = STDIN_FILENO;
     time_t t_tmp;
     off_t pos;
     static const char _ut_usr[] ALIGN1 =
             "runlevel\0" "reboot\0" "shutdown\0";
     static const char _ut_lin[] ALIGN1 =
             "~\0" "{\0" "|\0" /* "LOGIN\0" "date\0" */;
     enum {
         TYPE_RUN_LVL = RUN_LVL,         /* 1 */
         TYPE_BOOT_TIME = BOOT_TIME,     /* 2 */
         TYPE_SHUTDOWN_TIME = SHUTDOWN_TIME
     };
     enum {
         _TILDE = EMPTY, /* 0 */
         TYPE_NEW_TIME,  /* NEW_TIME, 3 */
         TYPE_OLD_TIME   /* OLD_TIME, 4 */
     };
     if (argv[1]) {
         bb_show_usage();
     }
     file = xopen(bb_path_wtmp_file, O_RDONLY);
     printf("%-10s %-14s %-18s %-12.12s %s\n",
         "USER", "TTY", "HOST", "LOGIN", "TIME");
     /* yikes. We reverse over the file and that is a not too elegant way */
     pos = xlseek(file, 0, SEEK_END);
     pos = lseek(file, pos - sizeof(ut), SEEK_SET);
     while ((n = full_read(file, &ut, sizeof(ut))) > 0) {
         if (n != sizeof(ut)) {
             bb_simple_perror_msg_and_die("short read");
         }
         n = index_in_strings(_ut_lin, ut.ut_line);
         if (n == _TILDE) { /* '~' */
 #if 1
 /* do we really need to be cautious here? */
             n = index_in_strings(_ut_usr, ut.ut_user);
             if (++n > 0)
                 ut.ut_type = n != 3 ? n : SHUTDOWN_TIME;
 #else
             if (is_prefixed_with(ut.ut_user, "shutdown"))
                 ut.ut_type = SHUTDOWN_TIME;
             else if (is_prefixed_with(ut.ut_user, "reboot"))
                 ut.ut_type = BOOT_TIME;
             else if (is_prefixed_with(ut.ut_user, "runlevel"))
                 ut.ut_type = RUN_LVL;
 #endif
         } else {
             if (ut.ut_user[0] == '\0' || strcmp(ut.ut_user, "LOGIN") == 0) {
                 /* Don't bother.  This means we can't find how long
                  * someone was logged in for.  Oh well. */
                 goto next;
             }
             if (ut.ut_type != DEAD_PROCESS
              && ut.ut_user[0]
              && ut.ut_line[0]
             ) {
                 ut.ut_type = USER_PROCESS;
             }
             if (strcmp(ut.ut_user, "date") == 0) {
                 if (n == TYPE_OLD_TIME) { /* '|' */
                     ut.ut_type = OLD_TIME;
                 }
                 if (n == TYPE_NEW_TIME) { /* '{' */
                     ut.ut_type = NEW_TIME;
                 }
             }
         }
         if (ut.ut_type != USER_PROCESS) {
             switch (ut.ut_type) {
                 case OLD_TIME:
                 case NEW_TIME:
                 case RUN_LVL:
                 case SHUTDOWN_TIME:
                     goto next;
                 case BOOT_TIME:
                     strcpy(ut.ut_line, "system boot");
             }
         }
         /* manpages say ut_tv.tv_sec *is* time_t,
          * but some systems have it wrong */
         t_tmp = (time_t)ut.ut_tv.tv_sec;
         printf("%-10s %-14s %-18s %-12.12s\n",
             ut.ut_user, ut.ut_line, ut.ut_host, ctime(&t_tmp) + 4);
  next:
         pos -= sizeof(ut);
         if (pos <= 0)
             break; /* done. */
         xlseek(file, pos, SEEK_SET);
     }
     fflush_stdout_and_exit_SUCCESS();
 }
References ALIGN1, argv, bb_show_usage(), bb_simple_perror_msg_and_die(), BOOT_TIME, ctime(), DEAD_PROCESS, EMPTY, fflush_stdout_and_exit_SUCCESS(), full_read(), index_in_strings(), is_prefixed_with(), lseek(), n, NEW_TIME, next, O_RDONLY, OLD_TIME, pos, printf, RUN_LVL, SEEK_END, SEEK_SET, SHUTDOWN_TIME, STDIN_FILENO, strcmp, strcpy, timeval::tv_sec, USER_PROCESS, utmpx::ut_host, utmpx::ut_line, utmpx::ut_tv, utmpx::ut_type, utmpx::ut_user, xlseek(), and xopen().
last_main() [2/2]
int last_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 159 of file last_fancy.c.
 {
     struct utmpx ut;
     const char *filename = _PATH_WTMP;
     llist_t *zlist;
     off_t pos;
     time_t start_time;
     time_t boot_time;
     time_t down_time;
     int file;
     smallint going_down;
     smallint boot_down;
     /*opt =*/ getopt32(argv, "Wf:" /* "H" */, &filename);
 #ifdef BUT_UTIL_LINUX_LAST_HAS_NO_SUCH_OPT
     if (opt & LAST_OPT_H) {
         /* Print header line */
         if (opt & LAST_OPT_W) {
             printf(HEADER_FORMAT, HEADER_LINE_WIDE);
         } else {
             printf(HEADER_FORMAT, HEADER_LINE);
         }
     }
 #endif
     file = xopen(filename, O_RDONLY);
     {
         /* in case the file is empty... */
         struct stat st;
         fstat(file, &st);
         start_time = st.st_ctime;
     }
     time(&down_time);
     going_down = 0;
     boot_down = NORMAL; /* 0 */
     zlist = NULL;
     boot_time = 0;
     /* get file size, rounding down to last full record */
     pos = xlseek(file, 0, SEEK_END) / sizeof(ut) * sizeof(ut);
     for (;;) {
         pos -= (off_t)sizeof(ut);
         if (pos < 0) {
             /* Beyond the beginning of the file boundary =>
              * the whole file has been read. */
             break;
         }
         xlseek(file, pos, SEEK_SET);
         xread(file, &ut, sizeof(ut));
         /* rewritten by each record, eventially will have
          * first record's ut_tv.tv_sec: */
         start_time = ut.ut_tv.tv_sec;
         switch (get_ut_type(&ut)) {
         case SHUTDOWN_TIME:
             down_time = ut.ut_tv.tv_sec;
             boot_down = DOWN;
             going_down = 1;
             break;
         case RUN_LVL:
             if (is_runlevel_shutdown(&ut)) {
                 down_time = ut.ut_tv.tv_sec;
                 going_down = 1;
                 boot_down = DOWN;
             }
             break;
         case BOOT_TIME:
             strcpy(ut.ut_line, "system boot");
             show_entry(&ut, REBOOT, down_time);
             boot_down = CRASH;
             going_down = 1;
             break;
         case DEAD_PROCESS:
             if (!ut.ut_line[0]) {
                 break;
             }
             /* add_entry */
             llist_add_to(&zlist, xmemdup(&ut, sizeof(ut)));
             break;
         case USER_PROCESS: {
             int show;
             if (!ut.ut_line[0]) {
                 break;
             }
             /* find_entry */
             show = 1;
             {
                 llist_t *el, *next;
                 for (el = zlist; el; el = next) {
                     struct utmpx *up = (struct utmpx *)el->data;
                     next = el->link;
                     if (strncmp(up->ut_line, ut.ut_line, __UT_LINESIZE) == 0) {
                         if (show) {
                             show_entry(&ut, NORMAL, up->ut_tv.tv_sec);
                             show = 0;
                         }
                         llist_unlink(&zlist, el);
                         free(el->data);
                         free(el);
                     }
                 }
             }
             if (show) {
                 int state = boot_down;
                 if (boot_time == 0) {
                     state = LOGGED;
                     /* Check if the process is alive */
                     if ((ut.ut_pid > 0)
                      && (kill(ut.ut_pid, 0) != 0)
                      && (errno == ESRCH)) {
                         state = GONE;
                     }
                 }
                 show_entry(&ut, state, boot_time);
             }
             /* add_entry */
             llist_add_to(&zlist, xmemdup(&ut, sizeof(ut)));
             break;
         }
         }
         if (going_down) {
             boot_time = ut.ut_tv.tv_sec;
             llist_free(zlist, free);
             zlist = NULL;
             going_down = 0;
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         llist_free(zlist, free);
     }
     printf("\nwtmp begins %s", ctime(&start_time));
     if (ENABLE_FEATURE_CLEAN_UP)
         close(file);
     fflush_stdout_and_exit_SUCCESS();
 }
References _PATH_WTMP, argv, BOOT_TIME, close(), CRASH, ctime(), llist_t::data, DEAD_PROCESS, DOWN, errno, ESRCH, fflush_stdout_and_exit_SUCCESS(), filename, free, fstat(), get_ut_type(), getopt32(), GONE, HEADER_FORMAT, HEADER_LINE, HEADER_LINE_WIDE, if(), is_runlevel_shutdown(), kill(), LAST_OPT_H, LAST_OPT_W, llist_t::link, llist_add_to(), llist_free(), llist_unlink(), LOGGED, next, NORMAL, NULL, O_RDONLY, opt, pos, printf, REBOOT, RUN_LVL, SEEK_END, SEEK_SET, show_entry(), SHUTDOWN_TIME, state, strcpy, strncmp(), time(), timeval::tv_sec, up, USER_PROCESS, utmpx::ut_line, utmpx::ut_pid, utmpx::ut_tv, xlseek(), xmemdup(), xopen(), and xread().