Fennix: Userspace/mlibc/sysdeps/linux/include/bits/syscall.h File Reference
syscall.h File Reference
Macros
#define __scc(x) ((__sc_word_t)(x))
#define __syscall0(n) __do_syscall0(n)
#define __syscall1(n, a) __do_syscall1(n,__scc(a))
#define __syscall2(n, a, b) __do_syscall2(n,__scc(a),__scc(b))
#define __syscall3(n, a, b, c) __do_syscall3(n,__scc(a),__scc(b),__scc(c))
#define __syscall4(n, a, b, c, d) __do_syscall4(n,__scc(a),__scc(b),__scc(c),__scc(d))
#define __syscall5(n, a, b, c, d, e) __do_syscall5(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e))
#define __syscall6(n, a, b, c, d, e, f) __do_syscall6(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f))
#define __syscall7(n, a, b, c, d, e, f, g) __do_syscall7(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f),__scc(g))
#define __SYSCALL_NARGS_X(a, b, c, d, e, f, g, h, n, ...) n
#define __SYSCALL_NARGS(...) __SYSCALL_NARGS_X(__VA_ARGS__,7,6,5,4,3,2,1,0,)
#define __SYSCALL_CONCAT_X(a, b) a##b
#define __SYSCALL_CONCAT(a, b) __SYSCALL_CONCAT_X(a,b)
#define __SYSCALL_DISP(b, ...) __SYSCALL_CONCAT(b,__SYSCALL_NARGS(__VA_ARGS__))(__VA_ARGS__)
#define __syscall(...) __SYSCALL_DISP(__syscall,__VA_ARGS__)
#define syscall(...) __do_syscall_ret(__syscall(__VA_ARGS__))
Typedefs
typedef long __sc_word_t
Functions
__sc_word_t __do_syscall0 (long)
__sc_word_t __do_syscall1 (long, __sc_word_t)
__sc_word_t __do_syscall2 (long, __sc_word_t, __sc_word_t)
__sc_word_t __do_syscall3 (long, __sc_word_t, __sc_word_t, __sc_word_t)
__sc_word_t __do_syscall4 (long, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t)
__sc_word_t __do_syscall5 (long, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t)
__sc_word_t __do_syscall6 (long, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t)
__sc_word_t __do_syscall7 (long, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t, __sc_word_t)
long __do_syscall_ret (unsigned long)
Macro Definition Documentation
__scc
#define __scc (x) ((__sc_word_t)(x))
Definition at line 67 of file syscall.h.
__syscall
#define __syscall (...) __SYSCALL_DISP(__syscall,__VA_ARGS__)
Definition at line 81 of file syscall.h.
__syscall0
#define __syscall0 (n) __do_syscall0(n)
Definition at line 68 of file syscall.h.
__syscall1
#define __syscall1 (n, a) __do_syscall1(n,__scc(a))
Definition at line 69 of file syscall.h.
__syscall2
#define __syscall2 (n, a, b) __do_syscall2(n,__scc(a),__scc(b))
Definition at line 70 of file syscall.h.
__syscall3
#define __syscall3 (n, a, b, c) __do_syscall3(n,__scc(a),__scc(b),__scc(c))
Definition at line 71 of file syscall.h.
__syscall4
#define __syscall4 (n, a, b, c, d) __do_syscall4(n,__scc(a),__scc(b),__scc(c),__scc(d))
Definition at line 72 of file syscall.h.
__syscall5
#define __syscall5 (n, a, b, c, d, e) __do_syscall5(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e))
Definition at line 73 of file syscall.h.
__syscall6
#define __syscall6 (n, a, b, c, d, e, f) __do_syscall6(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f))
Definition at line 74 of file syscall.h.
__syscall7
#define __syscall7 (n, a, b, c, d, e, f, g) __do_syscall7(n,__scc(a),__scc(b),__scc(c),__scc(d),__scc(e),__scc(f),__scc(g))
Definition at line 75 of file syscall.h.
__SYSCALL_CONCAT
#define __SYSCALL_CONCAT (a, b) __SYSCALL_CONCAT_X(a,b)
Definition at line 79 of file syscall.h.
__SYSCALL_CONCAT_X
#define __SYSCALL_CONCAT_X (a, b) a##b
Definition at line 78 of file syscall.h.
__SYSCALL_DISP
#define __SYSCALL_DISP (b, ...) __SYSCALL_CONCAT(b,__SYSCALL_NARGS(__VA_ARGS__))(__VA_ARGS__)
Definition at line 80 of file syscall.h.
__SYSCALL_NARGS
#define __SYSCALL_NARGS (...) __SYSCALL_NARGS_X(__VA_ARGS__,7,6,5,4,3,2,1,0,)
Definition at line 77 of file syscall.h.
__SYSCALL_NARGS_X
#define __SYSCALL_NARGS_X (a, b, c, d, e, f, g, h, n, ...) n
Definition at line 76 of file syscall.h.
syscall
#define syscall (...) __do_syscall_ret(__syscall(__VA_ARGS__))
Definition at line 82 of file syscall.h.
Typedef Documentation
__sc_word_t
typedef long __sc_word_t
Definition at line 8 of file syscall.h.
Function Documentation
__do_syscall0()
__sc_word_t __do_syscall0 (long sc)
Definition at line 6 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) : "r"(sc_reg) : "memory");
     return ret;
 }
References ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall1()
__sc_word_t __do_syscall1 (long sc, __sc_word_t arg1)
Definition at line 13 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t arg1_reg asm("x0") = arg1;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) :
             "r"(sc_reg),
             "r"(arg1_reg)
             : "memory");
     return ret;
 }
References arg1, and ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall2()
__sc_word_t __do_syscall2 (long sc, __sc_word_t arg1, __sc_word_t arg2)
Definition at line 25 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t arg1_reg asm("x0") = arg1;
     register sc_word_t arg2_reg asm("x1") = arg2;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) :
             "r"(sc_reg),
             "r"(arg1_reg),
             "r"(arg2_reg)
             : "memory");
     return ret;
 }
References arg1, arg2, and ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall3()
__sc_word_t __do_syscall3 (long sc, __sc_word_t arg1, __sc_word_t arg2, __sc_word_t arg3)
Definition at line 39 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t arg1_reg asm("x0") = arg1;
     register sc_word_t arg2_reg asm("x1") = arg2;
     register sc_word_t arg3_reg asm("x2") = arg3;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) :
             "r"(sc_reg),
             "r"(arg1_reg),
             "r"(arg2_reg),
             "r"(arg3_reg)
             : "memory");
     return ret;
 }
References arg1, arg2, arg3, and ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall4()
__sc_word_t __do_syscall4 (long sc, __sc_word_t arg1, __sc_word_t arg2, __sc_word_t arg3, __sc_word_t arg4)
Definition at line 55 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t arg1_reg asm("x0") = arg1;
     register sc_word_t arg2_reg asm("x1") = arg2;
     register sc_word_t arg3_reg asm("x2") = arg3;
     register sc_word_t arg4_reg asm("x3") = arg4;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) :
             "r"(sc_reg),
             "r"(arg1_reg),
             "r"(arg2_reg),
             "r"(arg3_reg),
             "r"(arg4_reg)
             : "memory");
     return ret;
 }
References arg1, arg2, arg3, arg4, and ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall5()
__sc_word_t __do_syscall5 (long sc, __sc_word_t arg1, __sc_word_t arg2, __sc_word_t arg3, __sc_word_t arg4, __sc_word_t arg5)
Definition at line 74 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t arg1_reg asm("x0") = arg1;
     register sc_word_t arg2_reg asm("x1") = arg2;
     register sc_word_t arg3_reg asm("x2") = arg3;
     register sc_word_t arg4_reg asm("x3") = arg4;
     register sc_word_t arg5_reg asm("x4") = arg5;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) :
             "r"(sc_reg),
             "r"(arg1_reg),
             "r"(arg2_reg),
             "r"(arg3_reg),
             "r"(arg4_reg),
             "r"(arg5_reg)
             : "memory");
     return ret;
 }
References arg1, arg2, arg3, arg4, arg5, and ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall6()
__sc_word_t __do_syscall6 (long sc, __sc_word_t arg1, __sc_word_t arg2, __sc_word_t arg3, __sc_word_t arg4, __sc_word_t arg5, __sc_word_t arg6)
Definition at line 95 of file arch-syscall.cpp.
{
     register int sc_reg asm("x8") = sc;
     register sc_word_t arg1_reg asm("x0") = arg1;
     register sc_word_t arg2_reg asm("x1") = arg2;
     register sc_word_t arg3_reg asm("x2") = arg3;
     register sc_word_t arg4_reg asm("x3") = arg4;
     register sc_word_t arg5_reg asm("x4") = arg5;
     register sc_word_t arg6_reg asm("x5") = arg6;
     register sc_word_t ret asm("x0");
     asm volatile ("svc 0" : "=r"(ret) :
             "r"(sc_reg),
             "r"(arg1_reg),
             "r"(arg2_reg),
             "r"(arg3_reg),
             "r"(arg4_reg),
             "r"(arg5_reg),
             "r"(arg6_reg)
             : "memory"
             );
     return ret;
 }
References arg1, arg2, arg3, arg4, arg5, and ret.
Referenced by mlibc::do_nargs_syscall().
__do_syscall7()
__sc_word_t __do_syscall7 (long , __sc_word_t , __sc_word_t , __sc_word_t , __sc_word_t , __sc_word_t , __sc_word_t , __sc_word_t)
__do_syscall_ret()
long __do_syscall_ret (unsigned long ret)
Definition at line 21 of file sysdeps.cpp.
{
     if(ret > -4096UL) {
         errno = -ret;
         return -1;
     }
     return ret;
 }
References errno, and ret.