Fennix: Userspace/mlibc/options/posix/generic/pthread-stubs.cpp File Reference
pthread-stubs.cpp File Reference
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <unistd.h>
#include <errno.h>
#include <inttypes.h>
#include <bits/ensure.h>
#include <frg/allocation.hpp>
#include <frg/array.hpp>
#include <mlibc/allocator.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
#include <mlibc/thread.hpp>
#include <mlibc/tcb.hpp>
#include <mlibc/tid.hpp>
Data Structures
struct ScopeTrace
struct anonymous_namespace{pthread-stubs.cpp}::key_global_info
struct mlibc::anonymous_namespace{pthread-stubs.cpp}::PthreadSignalInstaller
Namespaces
anonymous_namespace{pthread-stubs.cpp}
mlibc
mlibc::anonymous_namespace{pthread-stubs.cpp}
Macros
#define SCOPE_TRACE() ScopeTrace(__FILE__, __LINE__, __FUNCTION__)
Functions
int pthread_attr_init (pthread_attr_t *attr)
int pthread_attr_destroy (pthread_attr_t *)
int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate)
int pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate)
int pthread_attr_getstacksize (const pthread_attr_t *__restrict attr, size_t *__restrict stacksize)
int pthread_attr_setstacksize (pthread_attr_t *attr, size_t stacksize)
int pthread_attr_getstackaddr (const pthread_attr_t *attr, void **stackaddr)
int pthread_attr_setstackaddr (pthread_attr_t *attr, void *stackaddr)
int pthread_attr_getstack (const pthread_attr_t *attr, void **stackaddr, size_t *stacksize)
int pthread_attr_setstack (pthread_attr_t *attr, void *stackaddr, size_t stacksize)
int pthread_attr_getguardsize (const pthread_attr_t *__restrict attr, size_t *__restrict guardsize)
int pthread_attr_setguardsize (pthread_attr_t *attr, size_t guardsize)
int pthread_attr_getscope (const pthread_attr_t *attr, int *scope)
int pthread_attr_setscope (pthread_attr_t *attr, int scope)
int pthread_attr_getinheritsched (const pthread_attr_t *attr, int *inheritsched)
int pthread_attr_setinheritsched (pthread_attr_t *attr, int inheritsched)
int pthread_attr_getschedparam (const pthread_attr_t *__restrict attr, struct sched_param *__restrict schedparam)
int pthread_attr_setschedparam (pthread_attr_t *__restrict attr, const struct sched_param *__restrict schedparam)
int pthread_attr_getschedpolicy (const pthread_attr_t *__restrict attr, int *__restrict policy)
int pthread_attr_setschedpolicy (pthread_attr_t *__restrict attr, int policy)
int pthread_attr_getaffinity_np (const pthread_attr_t *__restrict attr, size_t cpusetsize, cpu_set_t *__restrict cpusetp)
int pthread_attr_setaffinity_np (pthread_attr_t *__restrict attr, size_t cpusetsize, const cpu_set_t *__restrict cpusetp)
int pthread_attr_getsigmask_np (const pthread_attr_t *__restrict attr, sigset_t *__restrict sigmask)
int pthread_attr_setsigmask_np (pthread_attr_t *__restrict attr, const sigset_t *__restrict sigmask)
void anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo (void **stack_addr, size_t *stack_size)
int pthread_getattr_np (pthread_t thread, pthread_attr_t *attr)
Tcb * __rtdl_allocateTcb ()
int pthread_create (pthread_t *__restrict thread, const pthread_attr_t *__restrict attrp, void *(*entry)(void *), void *__restrict user_arg)
pthread_t pthread_self (void)
int pthread_equal (pthread_t t1, pthread_t t2)
int pthread_exit (void *ret_val)
int pthread_join (pthread_t thread, void **ret)
int pthread_detach (pthread_t thread)
void pthread_cleanup_push (void(*func)(void *), void *arg)
void pthread_cleanup_pop (int execute)
int pthread_setname_np (pthread_t, const char *)
int pthread_getname_np (pthread_t, char *, size_t)
int pthread_setschedparam (pthread_t, int, const struct sched_param *)
int pthread_getschedparam (pthread_t, int *, struct sched_param *)
void __mlibc_do_cancel ()
void anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler (int signal, siginfo_t *info, void *ucontext)
int pthread_setcanceltype (int type, int *oldtype)
int pthread_setcancelstate (int state, int *oldstate)
void pthread_testcancel (void)
int pthread_cancel (pthread_t thread)
int pthread_atfork (void(*prepare)(void), void(*parent)(void), void(*child)(void))
int pthread_key_create (pthread_key_t *out, void(*destructor)(void *))
int pthread_key_delete (pthread_key_t key)
void * pthread_getspecific (pthread_key_t key)
int pthread_setspecific (pthread_key_t key, const void *value)
int pthread_once (pthread_once_t *once, void(*function)(void))
int pthread_mutexattr_init (pthread_mutexattr_t *attr)
int pthread_mutexattr_destroy (pthread_mutexattr_t *attr)
int pthread_mutexattr_gettype (const pthread_mutexattr_t *__restrict attr, int *__restrict type)
int pthread_mutexattr_settype (pthread_mutexattr_t *attr, int type)
int pthread_mutexattr_getrobust (const pthread_mutexattr_t *__restrict attr, int *__restrict robust)
int pthread_mutexattr_setrobust (pthread_mutexattr_t *attr, int robust)
int pthread_mutexattr_getpshared (const pthread_mutexattr_t *attr, int *pshared)
int pthread_mutexattr_setpshared (pthread_mutexattr_t *attr, int pshared)
int pthread_mutexattr_getprotocol (const pthread_mutexattr_t *__restrict attr, int *__restrict protocol)
int pthread_mutexattr_setprotocol (pthread_mutexattr_t *attr, int protocol)
int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t *__restrict attr, int *__restrict prioceiling)
int pthread_mutexattr_setprioceiling (pthread_mutexattr_t *attr, int prioceiling)
int pthread_mutex_init (pthread_mutex_t *__restrict mutex, const pthread_mutexattr_t *__restrict attr)
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_lock (pthread_mutex_t *mutex)
int pthread_mutex_trylock (pthread_mutex_t *mutex)
int pthread_mutex_timedlock (pthread_mutex_t *__restrict, const struct timespec *__restrict)
int pthread_mutex_unlock (pthread_mutex_t *mutex)
int pthread_mutex_consistent (pthread_mutex_t *)
int pthread_condattr_init (pthread_condattr_t *attr)
int pthread_condattr_destroy (pthread_condattr_t *attr)
int pthread_condattr_getclock (const pthread_condattr_t *__restrict attr, clockid_t *__restrict clock)
int pthread_condattr_setclock (pthread_condattr_t *attr, clockid_t clock)
int pthread_condattr_getpshared (const pthread_condattr_t *__restrict attr, int *__restrict pshared)
int pthread_condattr_setpshared (pthread_condattr_t *attr, int pshared)
int pthread_cond_init (pthread_cond_t *__restrict cond, const pthread_condattr_t *__restrict attr)
int pthread_cond_destroy (pthread_cond_t *)
int pthread_cond_wait (pthread_cond_t *__restrict cond, pthread_mutex_t *__restrict mutex)
int pthread_cond_timedwait (pthread_cond_t *__restrict cond, pthread_mutex_t *__restrict mutex, const struct timespec *__restrict abstime)
int pthread_cond_signal (pthread_cond_t *cond)
int pthread_cond_broadcast (pthread_cond_t *cond)
int pthread_barrierattr_init (pthread_barrierattr_t *attr)
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *__restrict attr, int *__restrict pshared)
int pthread_barrierattr_setpshared (pthread_barrierattr_t *attr, int pshared)
int pthread_barrierattr_destroy (pthread_barrierattr_t *)
int pthread_barrier_init (pthread_barrier_t *__restrict barrier, const pthread_barrierattr_t *__restrict attr, unsigned count)
int pthread_barrier_destroy (pthread_barrier_t *barrier)
int pthread_barrier_wait (pthread_barrier_t *barrier)
void anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock (pthread_rwlock_t *rw, bool excl)
int anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock (pthread_rwlock_t *rw, bool excl)
void anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock (pthread_rwlock_t *rw)
int pthread_rwlockattr_init (pthread_rwlockattr_t *attr)
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t *__restrict attr, int *__restrict pshared)
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *attr, int pshared)
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *)
int pthread_rwlock_init (pthread_rwlock_t *__restrict rw, const pthread_rwlockattr_t *__restrict attr)
int pthread_rwlock_destroy (pthread_rwlock_t *rw)
int pthread_rwlock_trywrlock (pthread_rwlock_t *rw)
int pthread_rwlock_wrlock (pthread_rwlock_t *rw)
int pthread_rwlock_tryrdlock (pthread_rwlock_t *rw)
int pthread_rwlock_rdlock (pthread_rwlock_t *rw)
int pthread_rwlock_unlock (pthread_rwlock_t *rw)
int pthread_getcpuclockid (pthread_t, clockid_t *)
Variables
static bool enableTrace = false
static constexpr unsigned int mutexRecursive = 1
static constexpr unsigned int mutexErrorCheck = 2
static constexpr unsigned int mutex_owner_mask = (static_cast<uint32_t>(1) << 30) - 1
static constexpr unsigned int mutex_waiters_bit = static_cast<uint32_t>(1) << 31
static constexpr unsigned int mutex_excl_bit = static_cast<uint32_t>(1) << 30
static constexpr unsigned int rc_count_mask = (static_cast<uint32_t>(1) << 31) - 1
static constexpr unsigned int rc_waiters_bit = static_cast<uint32_t>(1) << 31
static constexpr size_t default_stacksize = 0x200000
static constexpr size_t default_guardsize = 4096
constinit frg::array< key_global_info, PTHREAD_KEYS_MAX > anonymous_namespace{pthread-stubs.cpp}::key_globals_ {}
FutexLock anonymous_namespace{pthread-stubs.cpp}::key_mutex_
PthreadSignalInstaller mlibc::anonymous_namespace{pthread-stubs.cpp}::pthread_signal_installer
static constexpr unsigned int onceComplete = 1
static constexpr unsigned int onceLocked = 2
Macro Definition Documentation
SCOPE_TRACE
#define SCOPE_TRACE () ScopeTrace(__FILE__, __LINE__, __FUNCTION__)
Definition at line 46 of file pthread-stubs.cpp.
Function Documentation
__mlibc_do_cancel()
void __mlibc_do_cancel ()
Definition at line 514 of file pthread-stubs.cpp.
{
     //TODO(geert): for now the same as pthread_exit()
     pthread_exit(PTHREAD_CANCELED);
 }
References PTHREAD_CANCELED, and pthread_exit().
Referenced by mlibc::do_cp_syscall(), pthread_setcancelstate(), pthread_setcanceltype(), pthread_testcancel(), and anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler().
__rtdl_allocateTcb()
Tcb* __rtdl_allocateTcb ()
Definition at line 135 of file main.cpp.
{
     auto tcb = allocateTcb();
     initTlsObjects(tcb, globalScope->_objects, false);
     return tcb;
 }
References allocateTcb(), globalScope, and initTlsObjects().
Referenced by pthread_create().
pthread_atfork()
int pthread_atfork (void(*)(void) prepare, void(*)(void) parent, void(*)(void) child)
Definition at line 731 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     auto hand = frg::construct<Tcb::AtforkHandler>(getAllocator());
     if (!hand)
         return -1;
     hand->prepare = prepare;
     hand->parent = parent;
     hand->child = child;
     hand->next = nullptr;
     hand->prev = self->atforkEnd;
     if (self->atforkEnd)
         self->atforkEnd->next = hand;
     self->atforkEnd = hand;
     if (!self->atforkBegin)
         self->atforkBegin = self->atforkEnd;
     return 0;
 }
References child(), mlibc::get_current_tcb(), getAllocator(), and prepare().
Referenced by main().
pthread_attr_destroy()
int pthread_attr_destroy (pthread_attr_t *)
Definition at line 77 of file pthread-stubs.cpp.
{
     return 0;
 }
pthread_attr_getaffinity_np()
int pthread_attr_getaffinity_np (const pthread_attr_t *__restrict attr, size_t cpusetsize, cpu_set_t *__restrict cpusetp)
Definition at line 186 of file pthread-stubs.cpp.
{
     if (!attr)
         return EINVAL;
     if (!attr->__mlibc_cpuset) {
         memset(cpusetp, -1, cpusetsize);
         return 0;
     }
     for (size_t cnt = cpusetsize; cnt < attr->__mlibc_cpusetsize; cnt++)
         if (reinterpret_cast<char*>(attr->__mlibc_cpuset)[cnt] != '\0')
             return ERANGE;
     auto p = memcpy(cpusetp, attr->__mlibc_cpuset,
             std::min(cpusetsize, attr->__mlibc_cpusetsize));
     if (cpusetsize > attr->__mlibc_cpusetsize)
         memset(p, '\0', cpusetsize - attr->__mlibc_cpusetsize);
     return 0;
 }
References cnt, EINVAL, ERANGE, memcpy, memset, min(), and p.
Referenced by test_affinity().
pthread_attr_getdetachstate()
int pthread_attr_getdetachstate (const pthread_attr_t * attr, int * detachstate)
Definition at line 81 of file pthread-stubs.cpp.
{
     *detachstate = attr->__mlibc_detachstate;
     return 0;
 }
References __mlibc_threadattr::__mlibc_detachstate.
Referenced by test_detachstate().
pthread_attr_getguardsize()
int pthread_attr_getguardsize (const pthread_attr_t *__restrict attr, size_t *__restrict guardsize)
Definition at line 128 of file pthread-stubs.cpp.
{
     *guardsize = attr->__mlibc_guardsize;
     return 0;
 }
Referenced by test_guardsize().
pthread_attr_getinheritsched()
int pthread_attr_getinheritsched (const pthread_attr_t * attr, int * inheritsched)
Definition at line 151 of file pthread-stubs.cpp.
{
     *inheritsched = attr->__mlibc_inheritsched;
     return 0;
 }
References __mlibc_threadattr::__mlibc_inheritsched.
Referenced by test_inheritsched().
pthread_attr_getschedparam()
int pthread_attr_getschedparam (const pthread_attr_t *__restrict attr, struct sched_param *__restrict schedparam)
Definition at line 163 of file pthread-stubs.cpp.
{
     *schedparam = attr->__mlibc_schedparam;
     return 0;
 }
Referenced by test_schedparam().
pthread_attr_getschedpolicy()
int pthread_attr_getschedpolicy (const pthread_attr_t *__restrict attr, int *__restrict policy)
Definition at line 174 of file pthread-stubs.cpp.
{
     *policy = attr->__mlibc_schedpolicy;
     return 0;
 }
Referenced by test_schedpolicy().
pthread_attr_getscope()
int pthread_attr_getscope (const pthread_attr_t * attr, int * scope)
Definition at line 137 of file pthread-stubs.cpp.
{
     *scope = attr->__mlibc_scope;
     return 0;
 }
References __mlibc_threadattr::__mlibc_scope.
Referenced by test_scope().
pthread_attr_getsigmask_np()
int pthread_attr_getsigmask_np (const pthread_attr_t *__restrict attr, sigset_t *__restrict sigmask)
Definition at line 232 of file pthread-stubs.cpp.
{
     if (!attr)
         return EINVAL;
     if (!attr->__mlibc_sigmaskset) {
         sigemptyset(sigmask);
         return PTHREAD_ATTR_NO_SIGMASK_NP;
     }
     *sigmask = attr->__mlibc_sigmask;
     return 0;
 }
References EINVAL, PTHREAD_ATTR_NO_SIGMASK_NP, sigemptyset, and sigmask.
Referenced by test_sigmask().
pthread_attr_getstack()
int pthread_attr_getstack (const pthread_attr_t * attr, void ** stackaddr, size_t * stacksize)
Definition at line 115 of file pthread-stubs.cpp.
{
     *stackaddr = attr->__mlibc_stackaddr;
     *stacksize = attr->__mlibc_stacksize;
     return 0;
 }
References __mlibc_threadattr::__mlibc_stackaddr, and __mlibc_threadattr::__mlibc_stacksize.
Referenced by test_getattrnp(), and test_stack().
pthread_attr_getstackaddr()
int pthread_attr_getstackaddr (const pthread_attr_t * attr, void ** stackaddr)
Definition at line 106 of file pthread-stubs.cpp.
{
     *stackaddr = attr->__mlibc_stackaddr;
     return 0;
 }
References __mlibc_threadattr::__mlibc_stackaddr.
Referenced by test_stackaddr().
pthread_attr_getstacksize()
int pthread_attr_getstacksize (const pthread_attr_t *__restrict attr, size_t *__restrict stacksize)
Definition at line 94 of file pthread-stubs.cpp.
{
     *stacksize = attr->__mlibc_stacksize;
     return 0;
 }
Referenced by test_getattrnp(), test_stackaddr(), and test_stacksize().
pthread_attr_init()
int pthread_attr_init (pthread_attr_t * attr)
Definition at line 69 of file pthread-stubs.cpp.
{
     *attr = pthread_attr_t{};
     attr->__mlibc_stacksize = default_stacksize;
     attr->__mlibc_guardsize = default_guardsize;
     attr->__mlibc_detachstate = PTHREAD_CREATE_JOINABLE;
     return 0;
 }
References __mlibc_threadattr::__mlibc_detachstate, __mlibc_threadattr::__mlibc_guardsize, __mlibc_threadattr::__mlibc_stacksize, default_guardsize, default_stacksize, and PTHREAD_CREATE_JOINABLE.
Referenced by lio_listio(), mq_notify(), pthread_create(), submit(), test_affinity(), test_getattrnp(), test_guardsize(), test_sigmask(), test_stackaddr(), and test_stacksize().
pthread_attr_setaffinity_np()
int pthread_attr_setaffinity_np (pthread_attr_t *__restrict attr, size_t cpusetsize, const cpu_set_t *__restrict cpusetp)
Definition at line 208 of file pthread-stubs.cpp.
{
     if (!attr)
         return EINVAL;
     if (!cpusetp || !cpusetsize) {
         attr->__mlibc_cpuset = NULL;
         attr->__mlibc_cpusetsize = 0;
         return 0;
     }
     if (attr->__mlibc_cpusetsize != cpusetsize) {
         auto newp = realloc(attr->__mlibc_cpuset, cpusetsize);
         if (!newp)
             return ENOMEM;
         attr->__mlibc_cpuset = static_cast<cpu_set_t*>(newp);
         attr->__mlibc_cpusetsize = cpusetsize;
     }
     memcpy(attr->__mlibc_cpuset, cpusetp, cpusetsize);
     return 0;
 }
References EINVAL, ENOMEM, memcpy, NULL, and realloc.
Referenced by test_affinity().
pthread_attr_setdetachstate()
int pthread_attr_setdetachstate (pthread_attr_t * attr, int detachstate)
Definition at line 85 of file pthread-stubs.cpp.
{
     if (detachstate != PTHREAD_CREATE_DETACHED &&
             detachstate != PTHREAD_CREATE_JOINABLE)
         return EINVAL;
     attr->__mlibc_detachstate = detachstate;
     return 0;
 }
References __mlibc_threadattr::__mlibc_detachstate, EINVAL, PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
Referenced by lio_listio(), mq_notify(), submit(), and test_detachstate().
pthread_attr_setguardsize()
int pthread_attr_setguardsize (pthread_attr_t * attr, size_t guardsize)
Definition at line 132 of file pthread-stubs.cpp.
{
     attr->__mlibc_guardsize = guardsize;
     return 0;
 }
References __mlibc_threadattr::__mlibc_guardsize.
Referenced by lio_listio(), submit(), test_guardsize(), and test_stackaddr().
pthread_attr_setinheritsched()
int pthread_attr_setinheritsched (pthread_attr_t * attr, int inheritsched)
Definition at line 155 of file pthread-stubs.cpp.
{
     if (inheritsched != PTHREAD_INHERIT_SCHED &&
             inheritsched != PTHREAD_EXPLICIT_SCHED)
         return EINVAL;
     attr->__mlibc_inheritsched = inheritsched;
     return 0;
 }
References __mlibc_threadattr::__mlibc_inheritsched, EINVAL, PTHREAD_EXPLICIT_SCHED, and PTHREAD_INHERIT_SCHED.
Referenced by test_inheritsched(), and test_schedpolicy().
pthread_attr_setschedparam()
int pthread_attr_setschedparam (pthread_attr_t *__restrict attr, const struct sched_param *__restrict schedparam)
Definition at line 167 of file pthread-stubs.cpp.
{
     // TODO: this is supposed to return EINVAL for when the schedparam doesn't make sense
     // for the given schedpolicy.
     attr->__mlibc_schedparam = *schedparam;
     return 0;
 }
Referenced by test_schedparam().
pthread_attr_setschedpolicy()
int pthread_attr_setschedpolicy (pthread_attr_t *__restrict attr, int policy)
Definition at line 178 of file pthread-stubs.cpp.
{
     if (policy != SCHED_FIFO && policy != SCHED_RR &&
             policy != SCHED_OTHER)
         return EINVAL;
     attr->__mlibc_schedpolicy = policy;
     return 0;
 }
References EINVAL, SCHED_FIFO, SCHED_OTHER, and SCHED_RR.
Referenced by test_schedpolicy().
pthread_attr_setscope()
int pthread_attr_setscope (pthread_attr_t * attr, int scope)
Definition at line 141 of file pthread-stubs.cpp.
{
     if (scope != PTHREAD_SCOPE_SYSTEM &&
             scope != PTHREAD_SCOPE_PROCESS)
         return EINVAL;
     if (scope == PTHREAD_SCOPE_PROCESS)
         return ENOTSUP;
     attr->__mlibc_scope = scope;
     return 0;
 }
References __mlibc_threadattr::__mlibc_scope, EINVAL, ENOTSUP, PTHREAD_SCOPE_PROCESS, and PTHREAD_SCOPE_SYSTEM.
Referenced by test_scope().
pthread_attr_setsigmask_np()
int pthread_attr_setsigmask_np (pthread_attr_t *__restrict attr, const sigset_t *__restrict sigmask)
Definition at line 246 of file pthread-stubs.cpp.
{
     if (!attr)
         return EINVAL;
     if (!sigmask) {
         attr->__mlibc_sigmaskset = 0;
         return 0;
     }
     attr->__mlibc_sigmask = *sigmask;
     attr->__mlibc_sigmaskset = 1;
     // Filter out internally used signals.
     sigdelset(&attr->__mlibc_sigmask, SIGCANCEL);
     return 0;
 }
References EINVAL, SIGCANCEL, sigdelset, and sigmask.
Referenced by test_sigmask().
pthread_attr_setstack()
int pthread_attr_setstack (pthread_attr_t * attr, void * stackaddr, size_t stacksize)
Definition at line 120 of file pthread-stubs.cpp.
{
     if (stacksize < PTHREAD_STACK_MIN)
         return EINVAL;
     attr->__mlibc_stacksize = stacksize;
     attr->__mlibc_stackaddr = stackaddr;
     return 0;
 }
References __mlibc_threadattr::__mlibc_stackaddr, __mlibc_threadattr::__mlibc_stacksize, EINVAL, and PTHREAD_STACK_MIN.
Referenced by test_stack().
pthread_attr_setstackaddr()
int pthread_attr_setstackaddr (pthread_attr_t * attr, void * stackaddr)
Definition at line 110 of file pthread-stubs.cpp.
{
     attr->__mlibc_stackaddr = stackaddr;
     return 0;
 }
References __mlibc_threadattr::__mlibc_stackaddr.
Referenced by test_stackaddr().
pthread_attr_setstacksize()
int pthread_attr_setstacksize (pthread_attr_t * attr, size_t stacksize)
Definition at line 99 of file pthread-stubs.cpp.
{
     if (stacksize < PTHREAD_STACK_MIN)
         return EINVAL;
     attr->__mlibc_stacksize = stacksize;
     return 0;
 }
References __mlibc_threadattr::__mlibc_stacksize, EINVAL, and PTHREAD_STACK_MIN.
Referenced by lio_listio(), submit(), test_getattrnp(), and test_stacksize().
pthread_barrier_destroy()
int pthread_barrier_destroy (pthread_barrier_t * barrier)
Definition at line 1322 of file pthread-stubs.cpp.
{
     // Wait until there are no threads still using the barrier.
     unsigned inside = 0;
     do {
         unsigned expected = __atomic_load_n(&barrier->__mlibc_inside, __ATOMIC_RELAXED);
         if (expected == 0)
             break;
         int e = mlibc::sys_futex_wait((int *)&barrier->__mlibc_inside, expected, nullptr);
         if (e != 0 && e != EAGAIN && e != EINTR)
             mlibc::panicLogger() << "mlibc: sys_futex_wait() returned error " << e << frg::endlog;
     } while (inside > 0);
     memset(barrier, 0, sizeof *barrier);
     return 0;
 }
References __mlibc_barrier::__mlibc_inside, barrier, EAGAIN, EINTR, memset, mlibc::panicLogger, and mlibc::sys_futex_wait().
Referenced by main().
pthread_barrier_init()
int pthread_barrier_init (pthread_barrier_t *__restrict barrier, const pthread_barrierattr_t *__restrict attr, unsigned count)
Definition at line 1305 of file pthread-stubs.cpp.
{
     if (count == 0)
         return EINVAL;
     barrier->__mlibc_waiting = 0;
     barrier->__mlibc_inside = 0;
     barrier->__mlibc_seq = 0;
     barrier->__mlibc_count = count;
     // Since we don't implement these yet, set a flag to error later.
     auto pshared = attr ? attr->__mlibc_pshared : PTHREAD_PROCESS_PRIVATE;
     barrier->__mlibc_flags = pshared;
     return 0;
 }
References __mlibc_barrier::__mlibc_count, __mlibc_barrier::__mlibc_flags, __mlibc_barrier::__mlibc_inside, __mlibc_barrier::__mlibc_seq, __mlibc_barrier::__mlibc_waiting, barrier, count, EINVAL, and PTHREAD_PROCESS_PRIVATE.
Referenced by main().
pthread_barrier_wait()
int pthread_barrier_wait (pthread_barrier_t * barrier)
Definition at line 1339 of file pthread-stubs.cpp.
{
     if (barrier->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_barrier_t flags were non-zero"
             << frg::endlog;
     }
     // inside is incremented on entry and decremented on exit.
     // This is used to synchronise with pthread_barrier_destroy, to ensure that a thread doesn't pass
     // the barrier and immediately destroy its state while other threads still rely on it.
     __atomic_fetch_add(&barrier->__mlibc_inside, 1, __ATOMIC_ACQUIRE);
     auto leave = [&](){
         unsigned inside = __atomic_sub_fetch(&barrier->__mlibc_inside, 1, __ATOMIC_RELEASE);
         if (inside == 0)
             mlibc::sys_futex_wake((int *)&barrier->__mlibc_inside);
     };
     unsigned seq = __atomic_load_n(&barrier->__mlibc_seq, __ATOMIC_ACQUIRE);
     while (true) {
         unsigned expected = __atomic_load_n(&barrier->__mlibc_waiting, __ATOMIC_RELAXED);
         bool swapped = __atomic_compare_exchange_n(&barrier->__mlibc_waiting, &expected, expected + 1, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE);
         if (swapped) {
             if (expected + 1 == barrier->__mlibc_count) {
                 // We were the last thread to hit the barrier. Reset waiters and wake the others.
                 __atomic_fetch_add(&barrier->__mlibc_seq, 1, __ATOMIC_ACQUIRE);
                 __atomic_store_n(&barrier->__mlibc_waiting, 0, __ATOMIC_RELEASE);
                 mlibc::sys_futex_wake((int *)&barrier->__mlibc_seq);
                 leave();
                 return PTHREAD_BARRIER_SERIAL_THREAD;
             }
             while (true) {
                 int e = mlibc::sys_futex_wait((int *)&barrier->__mlibc_seq, seq, nullptr);
                 if (e != 0 && e != EAGAIN && e != EINTR)
                     mlibc::panicLogger() << "mlibc: sys_futex_wait() returned error " << e << frg::endlog;
                 unsigned newSeq = __atomic_load_n(&barrier->__mlibc_seq, __ATOMIC_ACQUIRE);
                 if (newSeq > seq) {
                     leave();
                     return 0;
                 }
             }
         }
     }
 }
References __mlibc_barrier::__mlibc_count, __mlibc_barrier::__mlibc_flags, __mlibc_barrier::__mlibc_inside, __mlibc_barrier::__mlibc_seq, __mlibc_barrier::__mlibc_waiting, barrier, EAGAIN, EINTR, mlibc::panicLogger, PTHREAD_BARRIER_SERIAL_THREAD, mlibc::sys_futex_wait(), and mlibc::sys_futex_wake().
Referenced by main(), start(), and worker().
pthread_barrierattr_destroy()
int pthread_barrierattr_destroy (pthread_barrierattr_t *)
Definition at line 1301 of file pthread-stubs.cpp.
{
     return 0;
 }
Referenced by main().
pthread_barrierattr_getpshared()
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *__restrict attr, int *__restrict pshared)
Definition at line 1287 of file pthread-stubs.cpp.
{
     *pshared = attr->__mlibc_pshared;
     return 0;
 }
Referenced by main().
pthread_barrierattr_init()
int pthread_barrierattr_init (pthread_barrierattr_t * attr)
Definition at line 1282 of file pthread-stubs.cpp.
{
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     return 0;
 }
References __mlibc_barrierattr_struct::__mlibc_pshared, and PTHREAD_PROCESS_PRIVATE.
Referenced by main().
pthread_barrierattr_setpshared()
int pthread_barrierattr_setpshared (pthread_barrierattr_t * attr, int pshared)
Definition at line 1293 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_SHARED && pshared != PTHREAD_PROCESS_PRIVATE)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References __mlibc_barrierattr_struct::__mlibc_pshared, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by main().
pthread_cancel()
int pthread_cancel (pthread_t thread)
Definition at line 684 of file pthread-stubs.cpp.
{
     if (!mlibc::sys_tgkill) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     auto tcb = reinterpret_cast<Tcb *>(thread);
     // Check if the TCB is valid, somewhat..
     if (tcb->selfPointer != tcb)
         return ESRCH;
     int old_value = __atomic_load_n(&tcb->cancelBits, __ATOMIC_RELAXED);
     while (1) {
         int bitmask = tcbCancelTriggerBit;
         int new_value = old_value | bitmask;
         if (old_value == new_value)
             break;
         int current_value = old_value;
         if (__atomic_compare_exchange_n(&tcb->cancelBits, &current_value,
                     new_value, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
             if (mlibc::tcb_cancel_enabled(new_value)) {
                 pid_t pid = getpid();
                 int res = mlibc::sys_tgkill(pid, tcb->tid, SIGCANCEL);
                 current_value = __atomic_load_n(&tcb->cancelBits, __ATOMIC_RELAXED);
                 // If we can't find the thread anymore, it's possible that it exited between
                 // us setting the cancel trigger bit, and us sending the signal. Check the
                 // cancelBits for tcbExitingBit to confirm that.
                 // XXX(qookie): This will be an use-after-free once we start freeing TCBs on
                 //              exit. Perhaps the TCB should be refcounted.
                 if (!(res == ESRCH && (current_value & tcbExitingBit)))
                     return res;
             }
             break;
         }
         old_value = current_value;
     }
     return 0;
 }
References ENOSYS, ESRCH, getpid(), MLIBC_MISSING_SYSDEP, SIGCANCEL, mlibc::sys_tgkill(), mlibc::tcb_cancel_enabled(), anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and anonymous_namespace{tcb.hpp}::tcbExitingBit.
Referenced by aio_cancel().
pthread_cleanup_pop()
void pthread_cleanup_pop (int execute)
Definition at line 476 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     auto hand = self->cleanupEnd;
     if (self->cleanupEnd)
         self->cleanupEnd = self->cleanupEnd->prev;
     if (self->cleanupEnd)
         self->cleanupEnd->next = nullptr;
     if (execute)
         hand->func(hand->arg);
     frg::destruct(getAllocator(), hand);
 }
References mlibc::get_current_tcb(), and getAllocator().
pthread_cleanup_push()
void pthread_cleanup_push (void(*)(void *) func, void * arg)
Definition at line 458 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     auto hand = frg::construct<Tcb::CleanupHandler>(getAllocator());
     hand->func = func;
     hand->arg = arg;
     hand->next = nullptr;
     hand->prev = self->cleanupEnd;
     if (self->cleanupEnd)
         self->cleanupEnd->next = hand;
     self->cleanupEnd = hand;
     if (!self->cleanupBegin)
         self->cleanupBegin = self->cleanupEnd;
 }
References mlibc::get_current_tcb(), and getAllocator().
pthread_cond_broadcast()
int pthread_cond_broadcast (pthread_cond_t * cond)
Definition at line 1269 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     __atomic_fetch_add(&cond->__mlibc_seq, 1, __ATOMIC_RELEASE);
     if(int e = mlibc::sys_futex_wake((int *)&cond->__mlibc_seq); e)
         __ensure(!"sys_futex_wake() failed");
     return 0;
 }
References __ensure, __mlibc_cond::__mlibc_seq, cond, SCOPE_TRACE, and mlibc::sys_futex_wake().
Referenced by cleanup(), do_init_fini(), pthread_cond_signal(), and test_broadcast_wakes_all().
pthread_cond_destroy()
int pthread_cond_destroy (pthread_cond_t *)
Definition at line 1174 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     return 0;
 }
References SCOPE_TRACE.
Referenced by test_attr().
pthread_cond_init()
int pthread_cond_init (pthread_cond_t *__restrict cond, const pthread_condattr_t *__restrict attr)
Definition at line 1160 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto clock = attr ? attr->__mlibc_clock : CLOCK_REALTIME;
     auto pshared = attr ? attr->__mlibc_pshared : PTHREAD_PROCESS_PRIVATE;
     cond->__mlibc_clock = clock;
     cond->__mlibc_flags = pshared;
     __atomic_store_n(&cond->__mlibc_seq, 1, __ATOMIC_RELAXED);
     return 0;
 }
References __mlibc_cond::__mlibc_clock, __mlibc_cond::__mlibc_flags, __mlibc_cond::__mlibc_seq, clock(), CLOCK_REALTIME, cond, PTHREAD_PROCESS_PRIVATE, and SCOPE_TRACE.
Referenced by __aio_get_queue(), and test_attr().
pthread_cond_signal()
int pthread_cond_signal (pthread_cond_t * cond)
Definition at line 1263 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     return pthread_cond_broadcast(cond);
 }
References cond, pthread_cond_broadcast(), and SCOPE_TRACE.
pthread_cond_timedwait()
int pthread_cond_timedwait (pthread_cond_t *__restrict cond, pthread_mutex_t *__restrict mutex, const struct timespec *__restrict abstime)
Definition at line 1184 of file pthread-stubs.cpp.
{
     // TODO: pshared isn't supported yet.
     __ensure(cond->__mlibc_flags == 0);
     constexpr long nanos_per_second = 1'000'000'000;
     if (abstime && (abstime->tv_nsec < 0 || abstime->tv_nsec >= nanos_per_second))
         return EINVAL;
     auto seq = __atomic_load_n(&cond->__mlibc_seq, __ATOMIC_ACQUIRE);
     // TODO: handle locking errors and cancellation properly.
     while (true) {
         if (pthread_mutex_unlock(mutex))
             __ensure(!"Failed to unlock the mutex");
         int e;
         if (abstime) {
             // Adjust for the fact that sys_futex_wait accepts a *timeout*, but
             // pthread_cond_timedwait accepts an *absolute time*.
             // Note: mlibc::sys_clock_get is available unconditionally.
             struct timespec now;
             if (mlibc::sys_clock_get(cond->__mlibc_clock, &now.tv_sec, &now.tv_nsec))
                 __ensure(!"sys_clock_get() failed");
             struct timespec timeout;
             timeout.tv_sec = abstime->tv_sec - now.tv_sec;
             timeout.tv_nsec = abstime->tv_nsec - now.tv_nsec;
             // Check if abstime has already passed.
             if (timeout.tv_sec < 0 || (timeout.tv_sec == 0 && timeout.tv_nsec < 0)) {
                 if (pthread_mutex_lock(mutex))
                     __ensure(!"Failed to lock the mutex");
                 return ETIMEDOUT;
             } else if (timeout.tv_nsec >= nanos_per_second) {
                 timeout.tv_nsec -= nanos_per_second;
                 timeout.tv_sec++;
                 __ensure(timeout.tv_nsec < nanos_per_second);
             } else if (timeout.tv_nsec < 0) {
                 timeout.tv_nsec += nanos_per_second;
                 timeout.tv_sec--;
                 __ensure(timeout.tv_nsec >= 0);
             }
             e = mlibc::sys_futex_wait((int *)&cond->__mlibc_seq, seq, &timeout);
         } else {
             e = mlibc::sys_futex_wait((int *)&cond->__mlibc_seq, seq, nullptr);
         }
         if (pthread_mutex_lock(mutex))
             __ensure(!"Failed to lock the mutex");
         // There are four cases to handle:
         //   1. e == 0: this indicates a (potentially spurious) wakeup. The value of
         //      seq *must* be checked to distinguish these two cases.
         //   2. e == EAGAIN: this indicates that the value of seq changed before we
         //      went to sleep. We don't need to check seq in this case.
         //   3. e == EINTR: a signal was delivered. The man page allows us to choose
         //      whether to go to sleep again or to return 0, but we do the former
         //      to match other libcs.
         //   4. e == ETIMEDOUT: this should only happen if abstime is set.
         if (e == 0) {
             auto cur_seq = __atomic_load_n(&cond->__mlibc_seq, __ATOMIC_ACQUIRE);
             if (cur_seq > seq)
                 return 0;
         } else if (e == EAGAIN) {
             __ensure(__atomic_load_n(&cond->__mlibc_seq, __ATOMIC_ACQUIRE) > seq);
             return 0;
         } else if (e == EINTR) {
             continue;
         } else if (e == ETIMEDOUT) {
             __ensure(abstime);
             return ETIMEDOUT;
         } else {
             mlibc::panicLogger() << "sys_futex_wait() failed with error " << e << frg::endlog;
         }
     }
 }
References __ensure, __mlibc_cond::__mlibc_clock, __mlibc_cond::__mlibc_flags, __mlibc_cond::__mlibc_seq, cond, EAGAIN, EINTR, EINVAL, ETIMEDOUT, mutex, mlibc::panicLogger, pthread_mutex_lock(), pthread_mutex_unlock(), mlibc::sys_clock_get(), mlibc::sys_futex_wait(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by __pthread_cond_timedwait_time32(), pthread_cond_wait(), and test_timedwait_timedout().
pthread_cond_wait()
int pthread_cond_wait (pthread_cond_t *__restrict cond, pthread_mutex_t *__restrict mutex)
Definition at line 1180 of file pthread-stubs.cpp.
{
     return pthread_cond_timedwait(cond, mutex, nullptr);
 }
References cond, mutex, and pthread_cond_timedwait().
Referenced by __libc_exit_fini(), do_init_fini(), io_thread_func(), and worker().
pthread_condattr_destroy()
int pthread_condattr_destroy (pthread_condattr_t * attr)
Definition at line 1125 of file pthread-stubs.cpp.
{
     memset(attr, 0, sizeof(*attr));
     return 0;
 }
References memset.
Referenced by test_attr().
pthread_condattr_getclock()
int pthread_condattr_getclock (const pthread_condattr_t *__restrict attr, clockid_t *__restrict clock)
Definition at line 1130 of file pthread-stubs.cpp.
{
     *clock = attr->__mlibc_clock;
     return 0;
 }
References clock().
Referenced by test_attr().
pthread_condattr_getpshared()
int pthread_condattr_getpshared (const pthread_condattr_t *__restrict attr, int *__restrict pshared)
Definition at line 1146 of file pthread-stubs.cpp.
{
     *pshared = attr->__mlibc_pshared;
     return 0;
 }
Referenced by test_attr().
pthread_condattr_init()
int pthread_condattr_init (pthread_condattr_t * attr)
Definition at line 1119 of file pthread-stubs.cpp.
{
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     attr->__mlibc_clock = CLOCK_REALTIME;
     return 0;
 }
References __mlibc_condattr_struct::__mlibc_clock, __mlibc_condattr_struct::__mlibc_pshared, CLOCK_REALTIME, and PTHREAD_PROCESS_PRIVATE.
Referenced by test_attr(), and test_timedwait_timedout().
pthread_condattr_setclock()
int pthread_condattr_setclock (pthread_condattr_t * attr, clockid_t clock)
Definition at line 1136 of file pthread-stubs.cpp.
{
     if (clock != CLOCK_REALTIME && clock != CLOCK_MONOTONIC
             && clock != CLOCK_MONOTONIC_RAW && clock != CLOCK_REALTIME_COARSE
             && clock != CLOCK_MONOTONIC_COARSE && clock != CLOCK_BOOTTIME)
         return EINVAL;
     attr->__mlibc_clock = clock;
     return 0;
 }
References __mlibc_condattr_struct::__mlibc_clock, clock(), CLOCK_BOOTTIME, CLOCK_MONOTONIC, CLOCK_MONOTONIC_COARSE, CLOCK_MONOTONIC_RAW, CLOCK_REALTIME, CLOCK_REALTIME_COARSE, and EINVAL.
Referenced by test_attr(), and test_timedwait_timedout().
pthread_condattr_setpshared()
int pthread_condattr_setpshared (pthread_condattr_t * attr, int pshared)
Definition at line 1152 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_PRIVATE && pshared != PTHREAD_PROCESS_SHARED)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References __mlibc_condattr_struct::__mlibc_pshared, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by test_attr().
pthread_create()
int pthread_create (pthread_t *__restrict thread, const pthread_attr_t *__restrict attrp, void *(*)(void *) entry, void *__restrict user_arg)
Definition at line 313 of file pthread-stubs.cpp.
{
     auto new_tcb = __rtdl_allocateTcb();
     pid_t tid;
     pthread_attr_t attr = {};
     if (!attrp)
         pthread_attr_init(&attr);
     else
         attr = *attrp;
     if (attr.__mlibc_cpuset)
         mlibc::infoLogger() << "pthread_create(): cpuset is ignored!" << frg::endlog;
     if (attr.__mlibc_sigmaskset)
         mlibc::infoLogger() << "pthread_create(): sigmask is ignored!" << frg::endlog;
     // TODO: due to alignment guarantees, the stackaddr and stacksize might change
     // when the stack is allocated. Currently this isn't propagated to the TCB,
     // but it should be.
     void *stack = attr.__mlibc_stackaddr;
     if (!mlibc::sys_prepare_stack) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     int ret = mlibc::sys_prepare_stack(&stack, reinterpret_cast<void*>(entry),
             user_arg, new_tcb, &attr.__mlibc_stacksize, &attr.__mlibc_guardsize);
     if (ret)
         return ret;
     if (!mlibc::sys_clone) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     new_tcb->stackSize = attr.__mlibc_stacksize;
     new_tcb->guardSize = attr.__mlibc_guardsize;
     new_tcb->stackAddr = reinterpret_cast<void*>(
             reinterpret_cast<uintptr_t>(stack)
             - attr.__mlibc_stacksize - attr.__mlibc_guardsize);
     mlibc::sys_clone(new_tcb, &tid, stack);
     *thread = reinterpret_cast<pthread_t>(new_tcb);
     __atomic_store_n(&new_tcb->tid, tid, __ATOMIC_RELAXED);
     mlibc::sys_futex_wake(&new_tcb->tid);
     return 0;
 }
References __mlibc_threadattr::__mlibc_cpuset, __mlibc_threadattr::__mlibc_guardsize, __mlibc_threadattr::__mlibc_sigmaskset, __mlibc_threadattr::__mlibc_stackaddr, __mlibc_threadattr::__mlibc_stacksize, __rtdl_allocateTcb(), ENOSYS, mlibc::infoLogger, MLIBC_MISSING_SYSDEP, pthread_attr_init(), ret, mlibc::stack, mlibc::sys_clone(), mlibc::sys_futex_wake(), and mlibc::sys_prepare_stack().
Referenced by lio_listio(), main(), mq_notify(), submit(), test_broadcast_wakes_all(), test_getattrnp(), test_stackaddr(), test_stacksize(), testNormal(), and testRecursive().
pthread_detach()
int pthread_detach (pthread_t thread)
Definition at line 445 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb*>(thread);
     if (!__atomic_load_n(&tcb->isJoinable, __ATOMIC_RELAXED))
         return EINVAL;
     int expected = 1;
     if(!__atomic_compare_exchange_n(&tcb->isJoinable, &expected, 0, false, __ATOMIC_RELEASE,
                 __ATOMIC_RELAXED))
         return EINVAL;
     return 0;
 }
References EINVAL.
Referenced by start().
pthread_equal()
int pthread_equal (pthread_t t1, pthread_t t2)
Definition at line 363 of file pthread-stubs.cpp.
{
     if(t1 == t2)
         return 1;
     return 0;
 }
References t1, and t2.
pthread_exit()
int pthread_exit (void * ret_val)
Definition at line 385 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     if (__atomic_load_n(&self->cancelBits, __ATOMIC_RELAXED) & tcbExitingBit)
         return 0; // We are already exiting
     __atomic_fetch_or(&self->cancelBits, tcbExitingBit, __ATOMIC_RELAXED);
     auto hand = self->cleanupEnd;
     while (hand) {
         auto old = hand;
         hand->func(hand->arg);
         hand = hand->prev;
         frg::destruct(getAllocator(), old);
     }
     for (size_t j = 0; j < PTHREAD_DESTRUCTOR_ITERATIONS; j++) {
         for (size_t i = 0; i < PTHREAD_KEYS_MAX; i++) {
             if (auto v = pthread_getspecific(i)) {
                 key_mutex_.lock();
                 auto dtor = key_globals_[i].dtor;
                 key_mutex_.unlock();
                 if (dtor) {
                     dtor(v);
                     (*self->localKeys)[i].value = nullptr;
                 }
             }
         }
     }
     self->returnValue = ret_val;
     __atomic_store_n(&self->didExit, 1, __ATOMIC_RELEASE);
     mlibc::sys_futex_wake(&self->didExit);
     // TODO: clean up thread resources when we are detached.
     // TODO: do exit(0) when we're the only thread instead
     mlibc::sys_thread_exit();
     __builtin_unreachable();
 }
References mlibc::get_current_tcb(), getAllocator(), i, j, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, FutexLockImpl< Recursive >::lock(), PTHREAD_DESTRUCTOR_ITERATIONS, pthread_getspecific(), PTHREAD_KEYS_MAX, mlibc::sys_futex_wake(), mlibc::sys_thread_exit(), anonymous_namespace{tcb.hpp}::tcbExitingBit, FutexLockImpl< Recursive >::unlock(), and value.
Referenced by __cancel(), __mlibc_do_cancel(), pthread_cancel(), worker(), worker1(), and worker2().
pthread_getattr_np()
int pthread_getattr_np (pthread_t thread, pthread_attr_t * attr)
Definition at line 293 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb*>(thread);
     *attr = pthread_attr_t{};
     if (!tcb->stackAddr || !tcb->stackSize) {
         get_own_stackinfo(&attr->__mlibc_stackaddr, &attr->__mlibc_stacksize);
     } else {
         attr->__mlibc_stacksize = tcb->stackSize;
         attr->__mlibc_stackaddr = tcb->stackAddr;
     }
     attr->__mlibc_guardsize = tcb->guardSize;
     attr->__mlibc_detachstate = tcb->isJoinable ? PTHREAD_CREATE_JOINABLE : PTHREAD_CREATE_DETACHED;
     mlibc::infoLogger() << "pthread_getattr_np(): Implementation is incomplete!" << frg::endlog;
     return 0;
 }
References __mlibc_threadattr::__mlibc_detachstate, __mlibc_threadattr::__mlibc_guardsize, __mlibc_threadattr::__mlibc_stackaddr, __mlibc_threadattr::__mlibc_stacksize, anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo(), mlibc::infoLogger, PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
Referenced by test_getattrnp().
pthread_getcpuclockid()
int pthread_getcpuclockid (pthread_t , clockid_t *)
Definition at line 1627 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_getname_np()
int pthread_getname_np (pthread_t , char * , size_t)
Definition at line 497 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_getschedparam()
int pthread_getschedparam (pthread_t , int * __restrict, struct sched_param * __restrict)
Definition at line 507 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_getspecific()
void* pthread_getspecific (pthread_key_t key)
Definition at line 798 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto self = mlibc::get_current_tcb();
     auto g = frg::guard(&key_mutex_);
     if (key >= PTHREAD_KEYS_MAX || !key_globals_[key].in_use)
         return nullptr;
     if (key_globals_[key].generation > (*self->localKeys)[key].generation) {
         (*self->localKeys)[key].value = nullptr;
         (*self->localKeys)[key].generation = key_globals_[key].generation;
     }
     return (*self->localKeys)[key].value;
 }
References g, mlibc::get_current_tcb(), mlibc::guard, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, SCOPE_TRACE, and value.
Referenced by dtor1(), dtor3(), main(), pthread_exit(), worker1(), and worker2().
pthread_join()
int pthread_join (pthread_t thread, void ** ret)
Definition at line 427 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb *>(thread);
     if (!__atomic_load_n(&tcb->isJoinable, __ATOMIC_ACQUIRE))
         return EINVAL;
     while (!__atomic_load_n(&tcb->didExit, __ATOMIC_ACQUIRE)) {
         mlibc::sys_futex_wait(&tcb->didExit, 0, nullptr);
     }
     if (ret)
         *ret = tcb->returnValue;
     // FIXME: destroy tcb here, currently we leak it
     return 0;
 }
References EINVAL, ret, and mlibc::sys_futex_wait().
Referenced by check_result(), main(), mq_notify(), test_broadcast_wakes_all(), test_getattrnp(), test_stackaddr(), test_stacksize(), testNormal(), and testRecursive().
pthread_key_create()
int pthread_key_create (pthread_key_t * out, void(*)(void *) destructor)
Definition at line 759 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto g = frg::guard(&key_mutex_);
     pthread_key_t key = PTHREAD_KEYS_MAX;
     for (size_t i = 0; i < PTHREAD_KEYS_MAX; i++) {
         if (!key_globals_[i].in_use) {
             key = i;
             break;
         }
     }
     if (key == PTHREAD_KEYS_MAX)
         return EAGAIN;
     key_globals_[key].in_use = true;
     key_globals_[key].dtor = destructor;
     *out = key;
     return 0;
 }
References EAGAIN, g, mlibc::guard, i, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, out(), PTHREAD_KEYS_MAX, and SCOPE_TRACE.
Referenced by dtor3(), main(), worker1(), and worker2().
pthread_key_delete()
int pthread_key_delete (pthread_key_t key)
Definition at line 783 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto g = frg::guard(&key_mutex_);
     if (key >= PTHREAD_KEYS_MAX || !key_globals_[key].in_use)
         return EINVAL;
     key_globals_[key].in_use = false;
     key_globals_[key].dtor = nullptr;
     key_globals_[key].generation++;
     return 0;
 }
References EINVAL, g, mlibc::guard, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, and SCOPE_TRACE.
Referenced by dtor3(), and main().
pthread_mutex_consistent()
int pthread_mutex_consistent (pthread_mutex_t *)
Definition at line 1110 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_mutex_destroy()
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 987 of file pthread-stubs.cpp.
{
     __ensure(!mutex->__mlibc_state);
     return 0;
 }
References __ensure, __mlibc_mutex::__mlibc_state, and mutex.
Referenced by testNormal(), and testRecursive().
pthread_mutex_init()
int pthread_mutex_init (pthread_mutex_t *__restrict mutex, const pthread_mutexattr_t *__restrict attr)
Definition at line 958 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto type = attr ? attr->__mlibc_type : PTHREAD_MUTEX_DEFAULT;
     auto robust = attr ? attr->__mlibc_robust : PTHREAD_MUTEX_STALLED;
     auto protocol = attr ? attr->__mlibc_protocol : PTHREAD_PRIO_NONE;
     auto pshared = attr ? attr->__mlibc_pshared : PTHREAD_PROCESS_PRIVATE;
     mutex->__mlibc_state = 0;
     mutex->__mlibc_recursion = 0;
     mutex->__mlibc_flags = 0;
     mutex->__mlibc_prioceiling = 0; // TODO: We don't implement this.
     if(type == PTHREAD_MUTEX_RECURSIVE) {
         mutex->__mlibc_flags |= mutexRecursive;
     }else if(type == PTHREAD_MUTEX_ERRORCHECK) {
         mutex->__mlibc_flags |= mutexErrorCheck;
     }else{
         __ensure(type == PTHREAD_MUTEX_NORMAL);
     }
     // TODO: Other values aren't supported yet.
     __ensure(robust == PTHREAD_MUTEX_STALLED);
     __ensure(protocol == PTHREAD_PRIO_NONE);
     __ensure(pshared == PTHREAD_PROCESS_PRIVATE);
     return 0;
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_prioceiling, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, mutex, mutexErrorCheck, mutexRecursive, PTHREAD_MUTEX_DEFAULT, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_NORMAL, PTHREAD_MUTEX_RECURSIVE, PTHREAD_MUTEX_STALLED, PTHREAD_PRIO_NONE, PTHREAD_PROCESS_PRIVATE, SCOPE_TRACE, and type.
Referenced by __aio_get_queue(), testNormal(), and testRecursive().
pthread_mutex_lock()
int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 992 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     unsigned int this_tid = mlibc::this_tid();
     unsigned int expected = 0;
     while(true) {
         if(!expected) {
             // Try to take the mutex here.
             if(__atomic_compare_exchange_n(&mutex->__mlibc_state,
                     &expected, this_tid, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
                 __ensure(!mutex->__mlibc_recursion);
                 mutex->__mlibc_recursion = 1;
                 return 0;
             }
         }else{
             // If this (recursive) mutex is already owned by us, increment the recursion level.
             if((expected & mutex_owner_mask) == this_tid) {
                 if(!(mutex->__mlibc_flags & mutexRecursive)) {
                     if (mutex->__mlibc_flags & mutexErrorCheck)
                         return EDEADLK;
                     else
                         mlibc::panicLogger() << "mlibc: pthread_mutex deadlock detected!"
                             << frg::endlog;
                 }
                 ++mutex->__mlibc_recursion;
                 return 0;
             }
             // Wait on the futex if the waiters flag is set.
             if(expected & mutex_waiters_bit) {
                 int e = mlibc::sys_futex_wait((int *)&mutex->__mlibc_state, expected, nullptr);
                 // If the wait returns EAGAIN, that means that the mutex_waiters_bit was just unset by
                 // some other thread. In this case, we should loop back around.
                 if (e && e != EAGAIN)
                     mlibc::panicLogger() << "sys_futex_wait() failed with error code " << e << frg::endlog;
                 // Opportunistically try to take the lock after we wake up.
                 expected = 0;
             }else{
                 // Otherwise we have to set the waiters flag first.
                 unsigned int desired = expected | mutex_waiters_bit;
                 if(__atomic_compare_exchange_n((int *)&mutex->__mlibc_state,
                         reinterpret_cast<int*>(&expected), desired, false, __ATOMIC_RELAXED, __ATOMIC_RELAXED))
                     expected = desired;
             }
         }
     }
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, EAGAIN, EDEADLK, mutex, mutex_owner_mask, mutex_waiters_bit, mutexErrorCheck, mutexRecursive, mlibc::panicLogger, SCOPE_TRACE, mlibc::sys_futex_wait(), and mlibc::this_tid().
Referenced by __aio_get_queue(), __aio_unref_queue(), __ldso_atfork(), __libc_exit_fini(), __pthread_cond_timedwait(), cleanup(), dlopen(), do_init_fini(), io_thread_func(), pthread_cond_timedwait(), submit(), test_timedwait_timedout(), testNormal(), testRecursive(), and worker().
pthread_mutex_timedlock()
int pthread_mutex_timedlock (pthread_mutex_t * __restrict, const struct timespec * __restrict)
Definition at line 1069 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by __pthread_mutex_timedlock_time32().
pthread_mutex_trylock()
int pthread_mutex_trylock (pthread_mutex_t * mutex)
Definition at line 1042 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     unsigned int this_tid = mlibc::this_tid();
     unsigned int expected = __atomic_load_n(&mutex->__mlibc_state, __ATOMIC_RELAXED);
     if(!expected) {
         // Try to take the mutex here.
         if(__atomic_compare_exchange_n(&mutex->__mlibc_state,
                         &expected, this_tid, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
             __ensure(!mutex->__mlibc_recursion);
             mutex->__mlibc_recursion = 1;
             return 0;
         }
     } else {
         // If this (recursive) mutex is already owned by us, increment the recursion level.
         if((expected & mutex_owner_mask) == this_tid) {
             if(!(mutex->__mlibc_flags & mutexRecursive)) {
                 return EBUSY;
             }
             ++mutex->__mlibc_recursion;
             return 0;
         }
     }
     return EBUSY;
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, EBUSY, mutex, mutex_owner_mask, mutexRecursive, SCOPE_TRACE, and mlibc::this_tid().
Referenced by test_broadcast_wakes_all(), testNormal(), and testRecursive().
pthread_mutex_unlock()
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Definition at line 1075 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     // Decrement the recursion level and unlock if we hit zero.
     __ensure(mutex->__mlibc_recursion);
     if(--mutex->__mlibc_recursion)
         return 0;
     auto flags = mutex->__mlibc_flags;
     // Reset the mutex to the unlocked state.
     auto state = __atomic_exchange_n(&mutex->__mlibc_state, 0, __ATOMIC_RELEASE);
     // After this point the mutex is unlocked, and therefore we cannot access its contents as it
     // may have been destroyed by another thread.
     unsigned int this_tid = mlibc::this_tid();
     if ((flags & mutexErrorCheck) && (state & mutex_owner_mask) != this_tid)
         return EPERM;
     if ((flags & mutexErrorCheck) && !(state & mutex_owner_mask))
         return EINVAL;
     __ensure((state & mutex_owner_mask) == this_tid);
     if(state & mutex_waiters_bit) {
         // Wake the futex if there were waiters. Since the mutex might not exist at this location
         // anymore, we must conservatively ignore EACCES and EINVAL which may occur as a result.
         int e = mlibc::sys_futex_wake((int *)&mutex->__mlibc_state);
         __ensure(e >= 0 || e == EACCES || e == EINVAL);
     }
     return 0;
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, EACCES, EINVAL, EPERM, flags, mutex, mutex_owner_mask, mutex_waiters_bit, mutexErrorCheck, SCOPE_TRACE, state, mlibc::sys_futex_wake(), and mlibc::this_tid().
Referenced by __aio_unref_queue(), __ldso_atfork(), aio_cancel(), dlopen(), do_init_fini(), io_thread_func(), pthread_cond_timedwait(), submit(), test_broadcast_wakes_all(), test_timedwait_timedout(), testNormal(), testRecursive(), and worker().
pthread_mutexattr_destroy()
int pthread_mutexattr_destroy (pthread_mutexattr_t * attr)
Definition at line 883 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     memset(attr, 0, sizeof(*attr));
     return 0;
 }
References memset, and SCOPE_TRACE.
Referenced by testAttr(), testNormal(), and testRecursive().
pthread_mutexattr_getprioceiling()
int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t *__restrict attr, int *__restrict prioceiling)
Definition at line 944 of file pthread-stubs.cpp.
{
     (void)attr;
     (void)prioceiling;
     return EINVAL;
 }
References EINVAL, and Driver::void().
pthread_mutexattr_getprotocol()
int pthread_mutexattr_getprotocol (const pthread_mutexattr_t *__restrict attr, int *__restrict protocol)
Definition at line 929 of file pthread-stubs.cpp.
{
     *protocol = attr->__mlibc_protocol;
     return 0;
 }
pthread_mutexattr_getpshared()
int pthread_mutexattr_getpshared (const pthread_mutexattr_t * attr, int * pshared)
Definition at line 917 of file pthread-stubs.cpp.
{
     *pshared = attr->__mlibc_pshared;
     return 0;
 }
References __mlibc_mutexattr::__mlibc_pshared.
pthread_mutexattr_getrobust()
int pthread_mutexattr_getrobust (const pthread_mutexattr_t *__restrict attr, int *__restrict robust)
Definition at line 904 of file pthread-stubs.cpp.
{
     *robust = attr->__mlibc_robust;
     return 0;
 }
pthread_mutexattr_gettype()
int pthread_mutexattr_gettype (const pthread_mutexattr_t *__restrict attr, int *__restrict type)
Definition at line 889 of file pthread-stubs.cpp.
{
     *type = attr->__mlibc_type;
     return 0;
 }
References type.
pthread_mutexattr_init()
int pthread_mutexattr_init (pthread_mutexattr_t * attr)
Definition at line 874 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     attr->__mlibc_type = PTHREAD_MUTEX_DEFAULT;
     attr->__mlibc_robust = PTHREAD_MUTEX_STALLED;
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     attr->__mlibc_protocol = PTHREAD_PRIO_NONE;
     return 0;
 }
References __mlibc_mutexattr::__mlibc_protocol, __mlibc_mutexattr::__mlibc_pshared, __mlibc_mutexattr::__mlibc_robust, __mlibc_mutexattr::__mlibc_type, PTHREAD_MUTEX_DEFAULT, PTHREAD_MUTEX_STALLED, PTHREAD_PRIO_NONE, PTHREAD_PROCESS_PRIVATE, and SCOPE_TRACE.
Referenced by testAttr(), testNormal(), and testRecursive().
pthread_mutexattr_setprioceiling()
int pthread_mutexattr_setprioceiling (pthread_mutexattr_t * attr, int prioceiling)
Definition at line 951 of file pthread-stubs.cpp.
{
     (void)attr;
     (void)prioceiling;
     return EINVAL;
 }
References EINVAL, and Driver::void().
pthread_mutexattr_setprotocol()
int pthread_mutexattr_setprotocol (pthread_mutexattr_t * attr, int protocol)
Definition at line 935 of file pthread-stubs.cpp.
{
     if (protocol != PTHREAD_PRIO_NONE && protocol != PTHREAD_PRIO_INHERIT
             && protocol != PTHREAD_PRIO_PROTECT)
         return EINVAL;
     attr->__mlibc_protocol = protocol;
     return 0;
 }
References __mlibc_mutexattr::__mlibc_protocol, EINVAL, PTHREAD_PRIO_INHERIT, PTHREAD_PRIO_NONE, and PTHREAD_PRIO_PROTECT.
pthread_mutexattr_setpshared()
int pthread_mutexattr_setpshared (pthread_mutexattr_t * attr, int pshared)
Definition at line 921 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_PRIVATE && pshared != PTHREAD_PROCESS_SHARED)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References __mlibc_mutexattr::__mlibc_pshared, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
pthread_mutexattr_setrobust()
int pthread_mutexattr_setrobust (pthread_mutexattr_t * attr, int robust)
Definition at line 909 of file pthread-stubs.cpp.
{
     if (robust != PTHREAD_MUTEX_STALLED && robust != PTHREAD_MUTEX_ROBUST)
         return EINVAL;
     attr->__mlibc_robust = robust;
     return 0;
 }
References __mlibc_mutexattr::__mlibc_robust, EINVAL, PTHREAD_MUTEX_ROBUST, and PTHREAD_MUTEX_STALLED.
pthread_mutexattr_settype()
int pthread_mutexattr_settype (pthread_mutexattr_t * attr, int type)
Definition at line 895 of file pthread-stubs.cpp.
{
     if (type != PTHREAD_MUTEX_NORMAL && type != PTHREAD_MUTEX_ERRORCHECK
             && type != PTHREAD_MUTEX_RECURSIVE)
         return EINVAL;
     attr->__mlibc_type = type;
     return 0;
 }
References __mlibc_mutexattr::__mlibc_type, EINVAL, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_NORMAL, PTHREAD_MUTEX_RECURSIVE, and type.
Referenced by testRecursive().
pthread_once()
int pthread_once (pthread_once_t * once, void(*)(void) function)
Definition at line 837 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto expected = __atomic_load_n(&once->__mlibc_done, __ATOMIC_ACQUIRE);
     // fast path: the function was already run.
     while(!(expected & onceComplete)) {
         if(!expected) {
             // try to acquire the mutex.
             if(!__atomic_compare_exchange_n(&once->__mlibc_done,
                     &expected, onceLocked, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE))
                 continue;
             function();
             // unlock the mutex.
             __atomic_exchange_n(&once->__mlibc_done, onceComplete, __ATOMIC_RELEASE);
             if(int e = mlibc::sys_futex_wake((int *)&once->__mlibc_done); e)
                 __ensure(!"sys_futex_wake() failed");
             return 0;
         }else{
             // a different thread is currently running the initializer.
             __ensure(expected == onceLocked);
             if(int e = mlibc::sys_futex_wait((int *)&once->__mlibc_done, onceLocked, nullptr); e)
                 __ensure(!"sys_futex_wait() failed");
             expected =  __atomic_load_n(&once->__mlibc_done, __ATOMIC_ACQUIRE);
         }
     }
     return 0;
 }
References __ensure, __mlibc_once::__mlibc_done, onceComplete, onceLocked, SCOPE_TRACE, mlibc::sys_futex_wait(), and mlibc::sys_futex_wake().
Referenced by cacheFileTable(), SignalGuard::SignalGuard(), and SignalGuard::~SignalGuard().
pthread_rwlock_destroy()
int pthread_rwlock_destroy (pthread_rwlock_t * rw)
Definition at line 1490 of file pthread-stubs.cpp.
{
     __ensure(!rw->__mlibc_m);
     __ensure(!rw->__mlibc_rc);
     return 0;
 }
References __ensure, __mlibc_fair_rwlock::__mlibc_m, and __mlibc_fair_rwlock::__mlibc_rc.
pthread_rwlock_init()
int pthread_rwlock_init (pthread_rwlock_t *__restrict rw, const pthread_rwlockattr_t *__restrict attr)
Definition at line 1479 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     rw->__mlibc_m = 0;
     rw->__mlibc_rc = 0;
     // Since we don't implement this yet, set a flag to error later.
     auto pshared = attr ? attr->__mlibc_pshared : PTHREAD_PROCESS_PRIVATE;
     rw->__mlibc_flags = pshared;
     return 0;
 }
References PTHREAD_PROCESS_PRIVATE, and SCOPE_TRACE.
Referenced by __aio_atfork().
pthread_rwlock_rdlock()
int pthread_rwlock_rdlock (pthread_rwlock_t * rw)
Definition at line 1574 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Increment the reader count while holding the __mlibc_m mutex.
     rwlock_m_lock(rw, false);
     __atomic_fetch_add(&rw->__mlibc_rc, 1, __ATOMIC_ACQUIRE);
     rwlock_m_unlock(rw);
     return 0;
 }
References __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, mlibc::panicLogger, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), and SCOPE_TRACE.
Referenced by __acquire_ptc(), __aio_atfork(), __aio_get_queue(), __dlsym(), dl_iterate_phdr(), dladdr(), test_read_allows_read(), test_read_lock_unlock(), and test_read_prevents_write().
pthread_rwlock_tryrdlock()
int pthread_rwlock_tryrdlock (pthread_rwlock_t * rw)
Definition at line 1557 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Increment the reader count while holding the __mlibc_m mutex.
     if(int e = rwlock_m_trylock(rw, false); e)
         return e;
     __atomic_fetch_add(&rw->__mlibc_rc, 1, __ATOMIC_ACQUIRE);
     rwlock_m_unlock(rw);
     return 0;
 }
References __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, mlibc::panicLogger, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), and SCOPE_TRACE.
Referenced by __aio_atfork(), __pthread_rwlock_timedrdlock(), test_read_allows_read(), test_read_trylock_unlock(), and test_write_prevents_read().
pthread_rwlock_trywrlock()
int pthread_rwlock_trywrlock (pthread_rwlock_t * rw)
Definition at line 1496 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Take the __mlibc_m mutex.
     // Will be released in pthread_rwlock_unlock().
     if(int e = rwlock_m_trylock(rw, true))
         return e;
     // Check that there are no readers.
     unsigned int rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_ACQUIRE);
     if(rc_expected) {
         rwlock_m_unlock(rw);
         return EBUSY;
     }
     return 0;
 }
References __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, EBUSY, mlibc::panicLogger, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), and SCOPE_TRACE.
Referenced by __pthread_rwlock_timedwrlock(), test_read_prevents_write(), test_write_prevents_write(), and test_write_trylock_unlock().
pthread_rwlock_unlock()
int pthread_rwlock_unlock (pthread_rwlock_t * rw)
Definition at line 1590 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     unsigned int rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_RELAXED);
     if(!rc_expected) {
         // We are doing a write-unlock.
         rwlock_m_unlock(rw);
         return 0;
     }else{
         // We are doing a read-unlock.
         while(true) {
             unsigned int count = rc_expected & rc_count_mask;
             __ensure(count);
             // Try to decrement the count.
             if(count == 1 && (rc_expected & rc_waiters_bit)) {
                 unsigned int desired = 0;
                 if(!__atomic_compare_exchange_n(&rw->__mlibc_rc,
                         &rc_expected, desired, false, __ATOMIC_RELEASE, __ATOMIC_RELAXED))
                     continue;
                 // Wake the futex.
                 mlibc::sys_futex_wake((int *)&rw->__mlibc_rc);
                 break;
             }else{
                 unsigned int desired = (rc_expected & ~rc_count_mask) | (count - 1);
                 if(!__atomic_compare_exchange_n(&rw->__mlibc_rc,
                         &rc_expected, desired, false, __ATOMIC_RELEASE, __ATOMIC_RELAXED))
                     continue;
                 break;
             }
         }
         return 0;
     }
 }
References __ensure, __mlibc_fair_rwlock::__mlibc_rc, count, rc_count_mask, rc_waiters_bit, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), SCOPE_TRACE, and mlibc::sys_futex_wake().
Referenced by __aio_atfork(), __aio_get_queue(), __aio_unref_queue(), __dlsym(), __ldso_atfork(), __libc_exit_fini(), __release_ptc(), dl_iterate_phdr(), dladdr(), dlopen(), test_read_allows_read(), test_read_lock_unlock(), test_read_prevents_write(), test_read_trylock_unlock(), test_write_lock_unlock(), test_write_prevents_read(), test_write_prevents_write(), and test_write_trylock_unlock().
pthread_rwlock_wrlock()
int pthread_rwlock_wrlock (pthread_rwlock_t * rw)
Definition at line 1519 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Take the __mlibc_m mutex.
     // Will be released in pthread_rwlock_unlock().
     rwlock_m_lock(rw, true);
     // Now wait until there are no more readers.
     unsigned int rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_ACQUIRE);
     while(true) {
         if(!rc_expected)
             break;
         __ensure(rc_expected & rc_count_mask);
         // Try to set the waiters bit.
         if(!(rc_expected & rc_waiters_bit)) {
             unsigned int desired = rc_expected | rc_count_mask;
             if(!__atomic_compare_exchange_n(&rw->__mlibc_rc,
                     &rc_expected, desired, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE))
                 continue;
         }
         // Wait on the futex.
         mlibc::sys_futex_wait((int *)&rw->__mlibc_rc, rc_expected | rc_waiters_bit, nullptr);
         // Re-check the reader counter.
         rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_ACQUIRE);
     }
     return 0;
 }
References __ensure, __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, mlibc::panicLogger, rc_count_mask, rc_waiters_bit, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), SCOPE_TRACE, and mlibc::sys_futex_wait().
Referenced by __aio_get_queue(), __aio_unref_queue(), __inhibit_ptc(), __ldso_atfork(), __libc_exit_fini(), dlopen(), test_write_lock_unlock(), test_write_prevents_read(), and test_write_prevents_write().
pthread_rwlockattr_destroy()
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *)
Definition at line 1475 of file pthread-stubs.cpp.
{
     return 0;
 }
Referenced by test_attr().
pthread_rwlockattr_getpshared()
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t *__restrict attr, int *__restrict pshared)
Definition at line 1461 of file pthread-stubs.cpp.
{
     *pshared = attr->__mlibc_pshared;
     return 0;
 }
Referenced by test_attr().
pthread_rwlockattr_init()
int pthread_rwlockattr_init (pthread_rwlockattr_t * attr)
Definition at line 1456 of file pthread-stubs.cpp.
{
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     return 0;
 }
References __mlibc_rwlockattr::__mlibc_pshared, and PTHREAD_PROCESS_PRIVATE.
Referenced by test_attr().
pthread_rwlockattr_setpshared()
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t * attr, int pshared)
Definition at line 1467 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_SHARED && pshared != PTHREAD_PROCESS_PRIVATE)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References __mlibc_rwlockattr::__mlibc_pshared, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by test_attr().
pthread_self()
pthread_t pthread_self (void)
Definition at line 359 of file pthread-stubs.cpp.
{
     return reinterpret_cast<pthread_t>(mlibc::get_current_tcb());
 }
References mlibc::get_current_tcb().
Referenced by pthread_cancel(), pthread_getname_np(), pthread_setname_np(), start(), and test_getattrnp().
pthread_setcancelstate()
int pthread_setcancelstate (int state, int * oldstate)
Definition at line 635 of file pthread-stubs.cpp.
{
     if (state != PTHREAD_CANCEL_ENABLE && state != PTHREAD_CANCEL_DISABLE)
         return EINVAL;
     auto self = reinterpret_cast<Tcb *>(mlibc::get_current_tcb());
     int old_value = self->cancelBits;
     while (1) {
         int new_value = old_value & ~tcbCancelEnableBit;
         if (state == PTHREAD_CANCEL_ENABLE)
             new_value |= tcbCancelEnableBit;
         if (oldstate)
             *oldstate = ((old_value & tcbCancelEnableBit)
                     ? PTHREAD_CANCEL_ENABLE
                     : PTHREAD_CANCEL_DISABLE);
         // Avoid unecessary atomic op.
         if (old_value == new_value)
             break;
         int current_value = old_value;
         if (__atomic_compare_exchange_n(&self->cancelBits, &current_value,
                     new_value, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
             if (mlibc::tcb_async_cancelled(new_value))
                 __mlibc_do_cancel();
             sigset_t set = {};
             sigaddset(&set, SIGCANCEL);
             if (new_value & PTHREAD_CANCEL_ENABLE)
                 sigprocmask(SIG_UNBLOCK, &set, NULL);
             else
                 sigprocmask(SIG_BLOCK, &set, NULL);
             break;
         }
         old_value = current_value;
     }
     return 0;
 }
References __mlibc_do_cancel(), Tcb::cancelBits, EINVAL, mlibc::get_current_tcb(), NULL, PTHREAD_CANCEL_DISABLE, PTHREAD_CANCEL_ENABLE, SIG_BLOCK, SIG_UNBLOCK, sigaddset, SIGCANCEL, sigprocmask(), state, mlibc::tcb_async_cancelled(), and anonymous_namespace{tcb.hpp}::tcbCancelEnableBit.
Referenced by __getgr_a(), __getgrent_a(), __getpw_a(), __getpwent_a(), __lookup_name(), __res_msend_rc(), __synccall(), __vsyslog(), closelog(), dlopen(), fgetspent(), fmtmsg(), forkpty(), getaddrinfo(), getdate(), getentropy(), getgr_r(), getpw_r(), getspnam_r(), if_nameindex(), mq_notify(), nftw(), openlog(), openpty(), posix_spawn(), pthread_getname_np(), pthread_setname_np(), sem_open(), shm_open(), vsyslog(), wordexp(), worker1(), worker2(), worker3(), worker4(), and worker5().
pthread_setcanceltype()
int pthread_setcanceltype (int type, int * oldtype)
Definition at line 600 of file pthread-stubs.cpp.
{
     if (type != PTHREAD_CANCEL_DEFERRED && type != PTHREAD_CANCEL_ASYNCHRONOUS)
         return EINVAL;
     auto self = reinterpret_cast<Tcb *>(mlibc::get_current_tcb());
     int old_value = self->cancelBits;
     while (1) {
         int new_value = old_value & ~tcbCancelAsyncBit;
         if (type == PTHREAD_CANCEL_ASYNCHRONOUS)
             new_value |= tcbCancelAsyncBit;
         if (oldtype)
             *oldtype = ((old_value & tcbCancelAsyncBit)
                     ? PTHREAD_CANCEL_ASYNCHRONOUS
                     : PTHREAD_CANCEL_DEFERRED);
         // Avoid unecessary atomic op.
         if (old_value == new_value)
             break;
         int current_value = old_value;
         if (__atomic_compare_exchange_n(&self->cancelBits, &current_value,
                     new_value, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
             if (mlibc::tcb_async_cancelled(new_value))
                 __mlibc_do_cancel();
             break;
         }
         old_value = current_value;
     }
     return 0;
 }
References __mlibc_do_cancel(), Tcb::cancelBits, EINVAL, mlibc::get_current_tcb(), PTHREAD_CANCEL_ASYNCHRONOUS, PTHREAD_CANCEL_DEFERRED, mlibc::tcb_async_cancelled(), anonymous_namespace{tcb.hpp}::tcbCancelAsyncBit, and type.
Referenced by worker1().
pthread_setname_np()
int pthread_setname_np (pthread_t , const char *)
Definition at line 492 of file pthread-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: pthread_setname_np is a stub" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
pthread_setschedparam()
int pthread_setschedparam (pthread_t , int , const struct sched_param *)
Definition at line 502 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_setspecific()
int pthread_setspecific (pthread_key_t key, const void * value)
Definition at line 815 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto self = mlibc::get_current_tcb();
     auto g = frg::guard(&key_mutex_);
     if (key >= PTHREAD_KEYS_MAX || !key_globals_[key].in_use)
         return EINVAL;
     (*self->localKeys)[key].value = const_cast<void *>(value);
     (*self->localKeys)[key].generation = key_globals_[key].generation;
     return 0;
 }
References EINVAL, g, mlibc::get_current_tcb(), mlibc::guard, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, SCOPE_TRACE, and value.
Referenced by dtor1(), dtor3(), main(), worker1(), and worker2().
pthread_testcancel()
void pthread_testcancel (void)
Definition at line 676 of file pthread-stubs.cpp.
{
     auto self = reinterpret_cast<Tcb *>(mlibc::get_current_tcb());
     int value = self->cancelBits;
     if ((value & tcbCancelEnableBit) && (value & tcbCancelTriggerBit)) {
         __mlibc_do_cancel();
         __builtin_unreachable();
     }
 }
References __mlibc_do_cancel(), mlibc::get_current_tcb(), anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and value.
Referenced by aio_suspend(), pthread_setcanceltype(), sem_timedwait(), system(), worker3(), and worker5().
Variable Documentation
default_guardsize
constexpr size_t default_guardsize = 4096 static constexpr
Definition at line 62 of file pthread-stubs.cpp.
Referenced by pthread_attr_init().
default_stacksize
constexpr size_t default_stacksize = 0x200000 static constexpr
Definition at line 61 of file pthread-stubs.cpp.
Referenced by pthread_attr_init(), and stacksize_worker().
enableTrace
bool enableTrace = false static
Definition at line 22 of file pthread-stubs.cpp.
Referenced by ScopeTrace::ScopeTrace(), and ScopeTrace::~ScopeTrace().
mutex_excl_bit
constexpr unsigned int mutex_excl_bit = static_cast<uint32_t>(1) << 30 static constexpr
Definition at line 56 of file pthread-stubs.cpp.
Referenced by anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), and anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock().
mutex_owner_mask
constexpr unsigned int mutex_owner_mask = (static_cast<uint32_t>(1) << 30) - 1 static constexpr
Definition at line 52 of file pthread-stubs.cpp.
Referenced by pthread_mutex_lock(), pthread_mutex_trylock(), pthread_mutex_unlock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), and anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock().
mutex_waiters_bit
constexpr unsigned int mutex_waiters_bit = static_cast<uint32_t>(1) << 31 static constexpr
Definition at line 53 of file pthread-stubs.cpp.
Referenced by pthread_mutex_lock(), pthread_mutex_unlock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), and anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock().
mutexErrorCheck
constexpr unsigned int mutexErrorCheck = 2 static constexpr
Definition at line 49 of file pthread-stubs.cpp.
Referenced by pthread_mutex_init(), pthread_mutex_lock(), and pthread_mutex_unlock().
mutexRecursive
constexpr unsigned int mutexRecursive = 1 static constexpr
Definition at line 48 of file pthread-stubs.cpp.
Referenced by pthread_mutex_init(), pthread_mutex_lock(), and pthread_mutex_trylock().
onceComplete
constexpr unsigned int onceComplete = 1 static constexpr
Definition at line 834 of file pthread-stubs.cpp.
Referenced by pthread_once().
onceLocked
constexpr unsigned int onceLocked = 2 static constexpr
Definition at line 835 of file pthread-stubs.cpp.
Referenced by pthread_once().
rc_count_mask
constexpr unsigned int rc_count_mask = (static_cast<uint32_t>(1) << 31) - 1 static constexpr
Definition at line 58 of file pthread-stubs.cpp.
Referenced by pthread_rwlock_unlock(), and pthread_rwlock_wrlock().
rc_waiters_bit
constexpr unsigned int rc_waiters_bit = static_cast<uint32_t>(1) << 31 static constexpr
Definition at line 59 of file pthread-stubs.cpp.
Referenced by pthread_rwlock_unlock(), and pthread_rwlock_wrlock().