Fennix: Userspace/musl/src/misc/openpty.c File Reference
openpty.c File Reference
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <pty.h>
#include <stdio.h>
#include <pthread.h>
Functions
int openpty (int *pm, int *ps, char *name, const struct termios *tio, const struct winsize *ws)
Function Documentation
openpty()
int openpty (int * pm, int * ps, char * name, const struct termios * tio, const struct winsize * ws)
Definition at line 10 of file openpty.c.
 {
     int m, s, n=0, cs;
     char buf[20];
     m = open("/dev/ptmx", O_RDWR|O_NOCTTY);
     if (m < 0) return -1;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (ioctl(m, TIOCSPTLCK, &n) || ioctl (m, TIOCGPTN, &n))
         goto fail;
     if (!name) name = buf;
     snprintf(name, sizeof buf, "/dev/pts/%d", n);
     if ((s = open(name, O_RDWR|O_NOCTTY)) < 0)
         goto fail;
     if (tio) tcsetattr(s, TCSANOW, tio);
     if (ws) ioctl(s, TIOCSWINSZ, ws);
     *pm = m;
     *ps = s;
     pthread_setcancelstate(cs, 0);
     return 0;
 fail:
     close(m);
     pthread_setcancelstate(cs, 0);
     return -1;
 }
References buf, close(), ioctl(), n, O_NOCTTY, O_RDWR, open(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), s, snprintf(), TCSANOW, tcsetattr(), tio, TIOCGPTN, TIOCSPTLCK, and TIOCSWINSZ.
Referenced by forkpty(), and test_ptmx().