Fennix: Gigabit Namespace Reference
Gigabit Namespace Reference
Data Structures
struct RXDescriptor
struct TXDescriptor
struct BARData
Enumerations
enum REG {
CTRL = 0x0000 , STATUS = 0x0008 , ICR = 0x000C , EEPROM = 0x0014 ,
CTRL_EXT = 0x0018 , ITR = 0x00C4 , IMASK = 0x00D0 , IAM = 0x00D8 ,
RCTRL = 0x0100 , RXDESCLO = 0x2800 , RXDESCHI = 0x2804 , RXDESCLEN = 0x2808 ,
RXDESCHEAD = 0x2810 , RXDESCTAIL = 0x2818 , TCTRL = 0x0400 , TXDESCLO = 0x3800 ,
TXDESCHI = 0x3804 , TXDESCLEN = 0x3808 , TXDESCHEAD = 0x3810 , TXDESCTAIL = 0x3818 ,
RDTR = 0x2820 , RXDCTL = 0x3828 , RADV = 0x282C , RSRPD = 0x2C00 ,
TIPG = 0x0410
}
enum PCTRL {
RESERVED = 0b000000 , SPEED_SELECTION_MSB = 0b010000 , UPDATE_COLLISION_TEST = 0b001000 , DUPLEX_MODE = 0b000100 ,
RESTART_AUTO_NEGOTIATION = 0b000010 , ISOLATE = 0b000001 , POWER_DOWN = 0b100000 , SPEED_SELECTION_LSB = 0b100000
}
enum ECTRL { SLU = 0x40 }
enum RTCL { RDMTS_HALF = (0 << 8) , RDMTS_QUARTER = (1 << 8) , RDMTS_EIGHTH = (2 << 8) }
enum RCTL {
EN = (1 << 1) , SBP = (1 << 2) , UPE = (1 << 3) , MPE = (1 << 4) ,
LPE = (1 << 5) , LBM_NONE = (0 << 6) , LBM_PHY = (3 << 6) , MO_36 = (0 << 12) ,
MO_35 = (1 << 12) , MO_34 = (2 << 12) , MO_32 = (3 << 12) , BAM = (1 << 15) ,
VFE = (1 << 18) , CFIEN = (1 << 19) , CFI = (1 << 20) , DPF = (1 << 22) ,
PMCF = (1 << 23) , SECRC = (1 << 26) , BSIZE_256 = (3 << 16) , BSIZE_512 = (2 << 16) ,
BSIZE_1024 = (1 << 16) , BSIZE_2048 = (0 << 16) , BSIZE_4096 = ((3 << 16) | (1 << 25)) , BSIZE_8192 = ((2 << 16) | (1 << 25)) ,
BSIZE_16384 = ((1 << 16) | (1 << 25))
}
enum CMD {
EOP = (1 << 0) , IFCS = (1 << 1) , IC = (1 << 2) , RS = (1 << 3) ,
RPS = (1 << 4) , VLE = (1 << 6) , IDE = (1 << 7)
}
enum TCTL {
EN_ = (1 << 1) , PSP = (1 << 3) , CT_SHIFT = 4 , COLD_SHIFT = 12 ,
SWXOFF = (1 << 22) , RTLC = (1 << 24)
}
enum TSTA { DD = (1 << 0) , EC = (1 << 1) , LC = (1 << 2) }
enum LSTA { LSTA_TU = (1 << 3) }
Functions
void WriteCMD (uint16_t Address, uint32_t Value)
uint32_t ReadCMD (uint16_t Address)
uint32_t ReadEEPROM (uint8_t Address)
MediaAccessControl GetMAC ()
void InitializeRX ()
void InitializeTX ()
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *)
struct Gigabit::RXDescriptor __attribute__ ((packed))
Variables
KernelAPI KAPI
PCIDeviceHeader * PCIBaseAddress
uint32_t CurrentPacket
BARData BAR
bool EEPROMAvailable
uint16_t RXCurrent
uint16_t TXCurrent
RXDescriptor * RX [E1000_NUM_RX_DESC]
TXDescriptor * TX [E1000_NUM_TX_DESC]
MediaAccessControl MAC
InternetProtocol::Version4 IP
struct Gigabit::BARData __attribute__
Data Structure Documentation
Gigabit::RXDescriptor
struct Gigabit::RXDescriptor
Definition at line 144 of file gigabit.hpp.
Data Fields
volatile uint64_t Address
volatile uint16_t Checksum
volatile uint8_t Errors
volatile uint16_t Length
volatile uint16_t Special
volatile uint8_t Status
Gigabit::TXDescriptor
struct Gigabit::TXDescriptor
Definition at line 154 of file gigabit.hpp.
Data Fields
volatile uint64_t Address
volatile uint8_t Command
volatile uint8_t cso
volatile uint8_t css
volatile uint16_t Length
volatile uint16_t Special
volatile uint8_t Status
Gigabit::BARData
struct Gigabit::BARData
Definition at line 165 of file gigabit.hpp.
Data Fields
uint16_t IOBase
uint64_t MemoryBase
uint8_t Type
Enumeration Type Documentation
CMD
enum Gigabit::CMD
Enumerator
EOP
IFCS
IC
RS
RPS
VLE
IDE
Definition at line 111 of file gigabit.hpp.
     {
         EOP = (1 << 0),
         IFCS = (1 << 1),
         IC = (1 << 2),
         RS = (1 << 3),
         RPS = (1 << 4),
         VLE = (1 << 6),
         IDE = (1 << 7)
     };
ECTRL
enum Gigabit::ECTRL
Enumerator
SLU
Definition at line 70 of file gigabit.hpp.
     {
         SLU = 0x40
     };
LSTA
enum Gigabit::LSTA
Enumerator
LSTA_TU
Definition at line 139 of file gigabit.hpp.
     {
         LSTA_TU = (1 << 3)
     };
PCTRL
enum Gigabit::PCTRL
Enumerator
RESERVED
SPEED_SELECTION_MSB
UPDATE_COLLISION_TEST
DUPLEX_MODE
RESTART_AUTO_NEGOTIATION
ISOLATE
POWER_DOWN
SPEED_SELECTION_LSB
Definition at line 58 of file gigabit.hpp.
     {
         RESERVED = 0b000000,                 // bits 5:0
         SPEED_SELECTION_MSB = 0b010000,      // bit 6
         UPDATE_COLLISION_TEST = 0b001000,    // bit 7
         DUPLEX_MODE = 0b000100,              // bit 8
         RESTART_AUTO_NEGOTIATION = 0b000010, // bit 9
         ISOLATE = 0b000001,                  // bit 10
         POWER_DOWN = 0b100000,               // bit 11
         SPEED_SELECTION_LSB = 0b100000,      // bit 13
     };
RCTL
enum Gigabit::RCTL
Enumerator
EN
SBP
UPE
MPE
LPE
LBM_NONE
LBM_PHY
MO_36
MO_35
MO_34
MO_32
BAM
VFE
CFIEN
CFI
DPF
PMCF
SECRC
BSIZE_256
BSIZE_512
BSIZE_1024
BSIZE_2048
BSIZE_4096
BSIZE_8192
BSIZE_16384
Definition at line 82 of file gigabit.hpp.
     {
         EN = (1 << 1),
         SBP = (1 << 2),
         UPE = (1 << 3),
         MPE = (1 << 4),
         LPE = (1 << 5),
         LBM_NONE = (0 << 6),
         LBM_PHY = (3 << 6),
         MO_36 = (0 << 12),
         MO_35 = (1 << 12),
         MO_34 = (2 << 12),
         MO_32 = (3 << 12),
         BAM = (1 << 15),
         VFE = (1 << 18),
         CFIEN = (1 << 19),
         CFI = (1 << 20),
         DPF = (1 << 22),
         PMCF = (1 << 23),
         SECRC = (1 << 26),
         BSIZE_256 = (3 << 16),
         BSIZE_512 = (2 << 16),
         BSIZE_1024 = (1 << 16),
         BSIZE_2048 = (0 << 16),
         BSIZE_4096 = ((3 << 16) | (1 << 25)),
         BSIZE_8192 = ((2 << 16) | (1 << 25)),
         BSIZE_16384 = ((1 << 16) | (1 << 25))
     };
REG
enum Gigabit::REG
Enumerator
CTRL
STATUS
ICR
EEPROM
CTRL_EXT
ITR
IMASK
IAM
RCTRL
RXDESCLO
RXDESCHI
RXDESCLEN
RXDESCHEAD
RXDESCTAIL
TCTRL
TXDESCLO
TXDESCHI
TXDESCLEN
TXDESCHEAD
TXDESCTAIL
RDTR
RXDCTL
RADV
RSRPD
TIPG
Definition at line 29 of file gigabit.hpp.
     {
         CTRL = 0x0000,
         STATUS = 0x0008,
         ICR = 0x000C,
         EEPROM = 0x0014,
         CTRL_EXT = 0x0018,
         ITR = 0x00C4,
         IMASK = 0x00D0,
         IAM = 0x00D8,
         RCTRL = 0x0100,
         RXDESCLO = 0x2800,
         RXDESCHI = 0x2804,
         RXDESCLEN = 0x2808,
         RXDESCHEAD = 0x2810,
         RXDESCTAIL = 0x2818,
         TCTRL = 0x0400,
         TXDESCLO = 0x3800,
         TXDESCHI = 0x3804,
         TXDESCLEN = 0x3808,
         TXDESCHEAD = 0x3810,
         TXDESCTAIL = 0x3818,
         RDTR = 0x2820,
         RXDCTL = 0x3828,
         RADV = 0x282C,
         RSRPD = 0x2C00,
         TIPG = 0x0410
     };
RTCL
enum Gigabit::RTCL
Enumerator
RDMTS_HALF
RDMTS_QUARTER
RDMTS_EIGHTH
Definition at line 75 of file gigabit.hpp.
     {
         RDMTS_HALF = (0 << 8),
         RDMTS_QUARTER = (1 << 8),
         RDMTS_EIGHTH = (2 << 8)
     };
TCTL
enum Gigabit::TCTL
Enumerator
EN_
PSP
CT_SHIFT
COLD_SHIFT
SWXOFF
RTLC
Definition at line 122 of file gigabit.hpp.
     {
         EN_ = (1 << 1),
         PSP = (1 << 3),
         CT_SHIFT = 4,
         COLD_SHIFT = 12,
         SWXOFF = (1 << 22),
         RTLC = (1 << 24)
     };
TSTA
enum Gigabit::TSTA
Enumerator
DD
EC
LC
Definition at line 132 of file gigabit.hpp.
     {
         DD = (1 << 0),
         EC = (1 << 1),
         LC = (1 << 2)
     };
Function Documentation
__attribute__()
struct Gigabit::RXDescriptor Gigabit::__attribute__ ((packed))
CallbackHandler()
int Gigabit::CallbackHandler (KernelCallback * Data)
Definition at line 186 of file Gigabit.cpp.
     {
         switch (Data->Reason)
         {
         case AcknowledgeReason:
         {
             debug("Kernel acknowledged the driver.");
             break;
         }
         case ConfigurationReason:
         {
             debug("Module received configuration data.");
             PCIBaseAddress = reinterpret_cast<PCIDeviceHeader *>(Data->RawPtr);
             switch (PCIBaseAddress->DeviceID)
             {
             case 0x100E:
             {
                 trace("Found Intel 82540EM Gigabit Ethernet Controller.");
                 PCIBaseAddress->Command |= PCI_COMMAND_MASTER | PCI_COMMAND_IO | PCI_COMMAND_MEMORY;
                 uint32_t PCIBAR0 = ((PCIHeader0 *)PCIBaseAddress)->BAR0;
                 uint32_t PCIBAR1 = ((PCIHeader0 *)PCIBaseAddress)->BAR1;
                 BAR.Type = PCIBAR0 & 1;
                 BAR.IOBase = (uint16_t)(PCIBAR1 & (~3));
                 BAR.MemoryBase = PCIBAR0 & (~15);
                 // Detect EEPROM
                 WriteCMD(REG::EEPROM, 0x1);
                 for (int i = 0; i < 1000 && !EEPROMAvailable; i++)
                     if (ReadCMD(REG::EEPROM) & 0x10)
                         EEPROMAvailable = true;
                     else
                         EEPROMAvailable = false;
                 // Get MAC address
                 if (!GetMAC().Valid())
                     return NOT_AVAILABLE;
                 else
                 {
                     debug("MAC address found.");
                 }
                 MAC = GetMAC();
                 // Start link
                 uint32_t cmdret = ReadCMD(REG::CTRL);
                 WriteCMD(REG::CTRL, cmdret | ECTRL::SLU);
                 for (int i = 0; i < 0x80; i++)
                     WriteCMD((uint16_t)(0x5200 + i * 4), 0);
                 WriteCMD(REG::IMASK, 0x1F6DC);
                 WriteCMD(REG::IMASK, 0xFF & ~4);
                 ReadCMD(0xC0);
                 InitializeRX();
                 InitializeTX();
                 return OK;
             }
             case 0x100F:
             {
                 trace("Found Intel 82545EM Gigabit Ethernet Controller.");
                 PCIBaseAddress->Command |= PCI_COMMAND_MASTER | PCI_COMMAND_IO | PCI_COMMAND_MEMORY;
                 uint32_t PCIBAR0 = ((PCIHeader0 *)PCIBaseAddress)->BAR0;
                 uint32_t PCIBAR1 = ((PCIHeader0 *)PCIBaseAddress)->BAR1;
                 BAR.Type = PCIBAR0 & 1;
                 BAR.IOBase = (uint16_t)(PCIBAR1 & (~3));
                 BAR.MemoryBase = PCIBAR0 & (~15);
                 // Detect EEPROM
                 WriteCMD(REG::EEPROM, 0x1);
                 for (int i = 0; i < 1000 && !EEPROMAvailable; i++)
                     if (ReadCMD(REG::EEPROM) & 0x10)
                         EEPROMAvailable = true;
                     else
                         EEPROMAvailable = false;
                 // Get MAC address
                 if (!GetMAC().Valid())
                     return NOT_AVAILABLE;
                 else
                 {
                     debug("MAC address found.");
                 }
                 MAC = GetMAC();
                 return NOT_IMPLEMENTED;
             }
             case 0x10D3:
             {
                 trace("Found Intel 82574L Gigabit Ethernet Controller.");
                 PCIBaseAddress->Command |= PCI_COMMAND_MASTER | PCI_COMMAND_IO | PCI_COMMAND_MEMORY;
                 uint32_t PCIBAR0 = ((PCIHeader0 *)PCIBaseAddress)->BAR0;
                 uint32_t PCIBAR1 = ((PCIHeader0 *)PCIBaseAddress)->BAR1;
                 BAR.Type = PCIBAR0 & 1;
                 BAR.IOBase = (uint16_t)(PCIBAR1 & (~3));
                 BAR.MemoryBase = PCIBAR0 & (~15);
                 // Detect EEPROM
                 WriteCMD(REG::EEPROM, 0x1);
                 for (int i = 0; i < 1000 && !EEPROMAvailable; i++)
                     if (ReadCMD(REG::EEPROM) & 0x10)
                         EEPROMAvailable = true;
                     else
                         EEPROMAvailable = false;
                 // Get MAC address
                 if (!GetMAC().Valid())
                     return NOT_AVAILABLE;
                 else
                 {
                     debug("MAC address found.");
                 }
                 MAC = GetMAC();
                 return NOT_IMPLEMENTED;
             }
             case 0x10EA:
             {
                 fixme("Found Intel I217-LM Gigabit Ethernet Controller.");
                 return NOT_IMPLEMENTED;
             }
             case 0x153A:
             {
                 fixme("Found Intel 82577LM Gigabit Ethernet Controller.");
                 return NOT_IMPLEMENTED;
             }
             default:
             {
                 error("Unsupported Intel Ethernet Controller.");
                 return DEVICE_NOT_SUPPORTED;
             }
             }
             return ERROR;
         }
         case QueryReason:
         {
             memcpy(Data->NetworkCallback.Fetch.Name, (void *)"Intel Gigabit Ethernet Controller", 34);
             Data->NetworkCallback.Fetch.MAC = MAC.ToHex();
             break;
         }
         case SendReason:
         {
             TX[TXCurrent]->Address = (uint64_t)Data->NetworkCallback.Send.Data;
             TX[TXCurrent]->Length = (uint16_t)Data->NetworkCallback.Send.Length;
             TX[TXCurrent]->Command = CMD::EOP | CMD::IFCS | CMD::RS;
             TX[TXCurrent]->Status = 0;
             uint16_t OldTXCurrent = TXCurrent;
             TXCurrent = (uint16_t)((TXCurrent + 1) % E1000_NUM_TX_DESC);
             WriteCMD(REG::TXDESCTAIL, TXCurrent);
             while (!(TX[OldTXCurrent]->Status & 0xFF))
                 ;
             break;
         }
         case StopReason:
         {
             // Clearing Enable bit in Receive Control Register
             uint32_t cmdret = ReadCMD(REG::RCTRL);
             WriteCMD(REG::RCTRL, cmdret & ~RCTL::EN);
             // Masking Interrupt Mask, Interrupt Throttling Rate & Interrupt Auto-Mask
             WriteCMD(REG::IMASK, 0x00000000);
             WriteCMD(REG::ITR, 0x00000000);
             WriteCMD(REG::IAM, 0x00000000);
             // Clearing SLU bit in Device Control Register
             cmdret = ReadCMD(REG::CTRL);
             WriteCMD(REG::CTRL, cmdret & ~ECTRL::SLU);
             // Clear the Interrupt Cause Read register by reading it
             ReadCMD(REG::ICR);
             // Powering down the device (?)
             WriteCMD(REG::CTRL, PCTRL::POWER_DOWN);
             /* TODO: Stop link; further testing required */
             debug("Module stopped.");
             break;
         }
         default:
         {
             warn("Unknown reason.");
             break;
         }
         }
         return OK;
     }
References AcknowledgeReason, Gigabit::TXDescriptor::Address, BAR, PCI::PCIDeviceHeader::Command, Gigabit::TXDescriptor::Command, ConfigurationReason, CTRL, Data, debug, DEVICE_NOT_SUPPORTED, PCI::PCIDeviceHeader::DeviceID, E1000_NUM_TX_DESC, EEPROM, EEPROMAvailable, EN, EOP, error, ERROR, fixme, GetMAC(), i, IAM, ICR, IFCS, IMASK, InitializeRX(), InitializeTX(), Gigabit::BARData::IOBase, ITR, Gigabit::TXDescriptor::Length, MAC, memcpy, Gigabit::BARData::MemoryBase, NOT_AVAILABLE, NOT_IMPLEMENTED, OK, PCI::PCI_COMMAND_IO, PCI::PCI_COMMAND_MASTER, PCI::PCI_COMMAND_MEMORY, PCIBaseAddress, POWER_DOWN, QueryReason, RCTRL, ReadCMD(), RS, SendReason, SLU, Status, Gigabit::TXDescriptor::Status, StopReason, MediaAccessControl::ToHex(), trace, TX, TXCurrent, TXDESCTAIL, Gigabit::BARData::Type, warn, and WriteCMD().
DriverEntry()
int Gigabit::DriverEntry (void * Data)
Definition at line 176 of file Gigabit.cpp.
     {
         if (!Data)
             return INVALID_KERNEL_API;
         KAPI = *(KernelAPI *)Data;
         if (KAPI.Version.Major < 0 || KAPI.Version.Minor < 0 || KAPI.Version.Patch < 0)
             return KERNEL_API_VERSION_NOT_SUPPORTED;
         return OK;
     }
References Data, INVALID_KERNEL_API, KAPI, KERNEL_API_VERSION_NOT_SUPPORTED, KernelAPI::KAPIVersion::Major, KernelAPI::KAPIVersion::Minor, OK, KernelAPI::KAPIVersion::Patch, and KernelAPI::Version.
Referenced by StartGigabit().
GetMAC()
MediaAccessControl Gigabit::GetMAC ()
Definition at line 89 of file Gigabit.cpp.
     {
         MediaAccessControl mac;
         if (EEPROMAvailable)
         {
             uint32_t temp;
             temp = ReadEEPROM(0);
             mac.Address[0] = temp & 0xff;
             mac.Address[1] = (uint8_t)(temp >> 8);
             temp = ReadEEPROM(1);
             mac.Address[2] = temp & 0xff;
             mac.Address[3] = (uint8_t)(temp >> 8);
             temp = ReadEEPROM(2);
             mac.Address[4] = temp & 0xff;
             mac.Address[5] = (uint8_t)(temp >> 8);
         }
         else
         {
             uint8_t *BaseMac8 = (uint8_t *)(BAR.MemoryBase + 0x5400);
             uint32_t *BaseMac32 = (uint32_t *)(BAR.MemoryBase + 0x5400);
             if (BaseMac32[0] != 0)
                 for (int i = 0; i < 6; i++)
                     mac.Address[i] = BaseMac8[i];
             else
             {
                 error("No MAC address found.");
                 return MediaAccessControl();
             }
         }
         return mac;
     }
References MediaAccessControl::Address, BAR, EEPROMAvailable, error, i, Gigabit::BARData::MemoryBase, and ReadEEPROM().
Referenced by CallbackHandler().
InitializeRX()
void Gigabit::InitializeRX ()
Definition at line 121 of file Gigabit.cpp.
     {
         debug("Initializing RX...");
         uintptr_t Ptr = (uintptr_t)KAPI.Memory.RequestPage((((sizeof(RXDescriptor) * E1000_NUM_RX_DESC + 16)) / KAPI.Memory.PageSize) + 1);
         for (int i = 0; i < E1000_NUM_RX_DESC; i++)
         {
             RX[i] = (RXDescriptor *)(Ptr + i * 16);
             RX[i]->Address = (uint64_t)(uintptr_t)KAPI.Memory.RequestPage(((8192 + 16) / KAPI.Memory.PageSize) + 1);
             RX[i]->Status = 0;
         }
 #pragma GCC diagnostic ignored "-Wshift-count-overflow"
         WriteCMD(REG::TXDESCLO, (uint32_t)(Ptr >> 32));
         WriteCMD(REG::TXDESCHI, (uint32_t)(Ptr & 0xFFFFFFFF));
         WriteCMD(REG::RXDESCLO, (uint32_t)Ptr);
         WriteCMD(REG::RXDESCHI, 0);
         WriteCMD(REG::RXDESCLEN, E1000_NUM_RX_DESC * 16);
         WriteCMD(REG::RXDESCHEAD, 0);
         WriteCMD(REG::RXDESCTAIL, E1000_NUM_RX_DESC - 1);
         RXCurrent = 0;
         WriteCMD(REG::RCTRL, RCTL::EN | RCTL::SBP | RCTL::UPE | RCTL::MPE | RCTL::LBM_NONE | RTCL::RDMTS_HALF | RCTL::BAM | RCTL::SECRC | RCTL::BSIZE_8192);
     }
References Gigabit::RXDescriptor::Address, BAM, BSIZE_8192, debug, E1000_NUM_RX_DESC, EN, i, KAPI, LBM_NONE, KernelAPI::Memory, MPE, KernelAPI::KAPIMemory::PageSize, RCTRL, RDMTS_HALF, KernelAPI::KAPIMemory::RequestPage, RX, RXCurrent, RXDESCHEAD, RXDESCHI, RXDESCLEN, RXDESCLO, RXDESCTAIL, SBP, SECRC, Gigabit::RXDescriptor::Status, TXDESCHI, TXDESCLO, UPE, and WriteCMD().
Referenced by CallbackHandler().
InitializeTX()
void Gigabit::InitializeTX ()
Definition at line 149 of file Gigabit.cpp.
     {
         debug("Initializing TX...");
         uintptr_t Ptr = (uintptr_t)KAPI.Memory.RequestPage(((sizeof(TXDescriptor) * E1000_NUM_RX_DESC + 16) / KAPI.Memory.PageSize) + 1);
         for (short i = 0; i < E1000_NUM_TX_DESC; i++)
         {
             TX[i] = (TXDescriptor *)((uintptr_t)Ptr + i * 16);
             TX[i]->Address = 0;
             TX[i]->Command = 0;
             TX[i]->Status = TSTA::DD;
         }
         WriteCMD(REG::TXDESCHI, (uint32_t)((uint64_t)Ptr >> 32));
         WriteCMD(REG::TXDESCLO, (uint32_t)((uint64_t)Ptr & 0xFFFFFFFF));
         WriteCMD(REG::TXDESCLEN, E1000_NUM_TX_DESC * 16);
         WriteCMD(REG::TXDESCHEAD, 0);
         WriteCMD(REG::TXDESCTAIL, 0);
         TXCurrent = 0;
         WriteCMD(REG::TCTRL, TCTL::EN_ | TCTL::PSP | (15 << TCTL::CT_SHIFT) | (64 << TCTL::COLD_SHIFT) | TCTL::RTLC);
         WriteCMD(REG::TCTRL, 0b0110000000000111111000011111010);
         WriteCMD(REG::TIPG, 0x0060200A);
     }
References Gigabit::TXDescriptor::Address, COLD_SHIFT, Gigabit::TXDescriptor::Command, CT_SHIFT, DD, debug, E1000_NUM_RX_DESC, E1000_NUM_TX_DESC, EN_, i, KAPI, KernelAPI::Memory, KernelAPI::KAPIMemory::PageSize, PSP, KernelAPI::KAPIMemory::RequestPage, RTLC, Gigabit::TXDescriptor::Status, TCTRL, TIPG, TX, TXCurrent, TXDESCHEAD, TXDESCHI, TXDESCLEN, TXDESCLO, TXDESCTAIL, and WriteCMD().
Referenced by CallbackHandler().
InterruptCallback()
int Gigabit::InterruptCallback (CPURegisters *)
Definition at line 376 of file Gigabit.cpp.
     {
         WriteCMD(REG::IMASK, 0x1);
         uint32_t status = ReadCMD(0xC0);
         UNUSED(status);
         while ((RX[RXCurrent]->Status & 0x1))
         {
             uint8_t *Data = (uint8_t *)RX[RXCurrent]->Address;
             uint16_t DataLength = RX[RXCurrent]->Length;
             KAPI.Command.Network.ReceivePacket(KAPI.Info.modUniqueID, Data, DataLength);
             RX[RXCurrent]->Status = 0;
             uint16_t OldRXCurrent = RXCurrent;
             RXCurrent = (uint16_t)((RXCurrent + 1) % E1000_NUM_RX_DESC);
             WriteCMD(REG::RXDESCTAIL, OldRXCurrent);
         }
         return OK;
     }
References Address, KernelAPI::Command, Data, E1000_NUM_RX_DESC, IMASK, KernelAPI::Info, KAPI, Gigabit::RXDescriptor::Length, KernelAPI::KAPIInfo::modUniqueID, KernelAPI::KAPIModuleTalk::Network, OK, ReadCMD(), RX, RXCurrent, RXDESCTAIL, Status, Gigabit::RXDescriptor::Status, status, UNUSED, and WriteCMD().
ReadCMD()
uint32_t Gigabit::ReadCMD (uint16_t Address)
Definition at line 58 of file Gigabit.cpp.
     {
         if (BAR.Type == 0)
             return mmioin32(BAR.MemoryBase + Address);
         else
         {
             outportl(BAR.IOBase, Address);
             return inportl(BAR.IOBase + 0x4);
         }
     }
References Address, BAR, Gigabit::BARData::IOBase, Gigabit::BARData::MemoryBase, and Gigabit::BARData::Type.
Referenced by CallbackHandler(), InterruptCallback(), and ReadEEPROM().
ReadEEPROM()
uint32_t Gigabit::ReadEEPROM (uint8_t Address)
Definition at line 69 of file Gigabit.cpp.
     {
         uint16_t Data = 0;
         uint32_t temp = 0;
         if (EEPROMAvailable)
         {
             WriteCMD(REG::EEPROM, (1) | ((uint32_t)(Address) << 8));
             while (!((temp = ReadCMD(REG::EEPROM)) & (1 << 4)))
                 ;
         }
         else
         {
             WriteCMD(REG::EEPROM, (1) | ((uint32_t)(Address) << 2));
             while (!((temp = ReadCMD(REG::EEPROM)) & (1 << 1)))
                 ;
         }
         Data = (uint16_t)((temp >> 16) & 0xFFFF);
         return Data;
     }
References Address, Data, EEPROM, EEPROMAvailable, ReadCMD(), and WriteCMD().
Referenced by GetMAC().
WriteCMD()
void Gigabit::WriteCMD (uint16_t Address, uint32_t Value)
Definition at line 47 of file Gigabit.cpp.
     {
         if (BAR.Type == 0)
             mmioout32(BAR.MemoryBase + Address, Value);
         else
         {
             outportl(BAR.IOBase, Address);
             outportl(BAR.IOBase + 4, Value);
         }
     }
References Address, BAR, Gigabit::BARData::IOBase, Gigabit::BARData::MemoryBase, and Gigabit::BARData::Type.
Referenced by CallbackHandler(), InitializeRX(), InitializeTX(), InterruptCallback(), and ReadEEPROM().
Variable Documentation
__attribute__
struct Gigabit::TXDescriptor Gigabit::__attribute__
BAR
BARData Gigabit::BAR
Definition at line 36 of file Gigabit.cpp.
Referenced by CallbackHandler(), GetMAC(), ReadCMD(), and WriteCMD().
CurrentPacket
uint32_t Gigabit::CurrentPacket
Definition at line 35 of file Gigabit.cpp.
EEPROMAvailable
bool Gigabit::EEPROMAvailable
Definition at line 37 of file Gigabit.cpp.
Referenced by CallbackHandler(), GetMAC(), and ReadEEPROM().
IP
InternetProtocol::Version4 Gigabit::IP
Definition at line 45 of file Gigabit.cpp.
KAPI
KernelAPI Gigabit::KAPI
Definition at line 32 of file Gigabit.cpp.
Referenced by DriverEntry(), InitializeRX(), InitializeTX(), and InterruptCallback().
MAC
MediaAccessControl Gigabit::MAC
Definition at line 44 of file Gigabit.cpp.
Referenced by CallbackHandler().
PCIBaseAddress
PCIDeviceHeader* Gigabit::PCIBaseAddress
Definition at line 34 of file Gigabit.cpp.
Referenced by CallbackHandler().
RX
RXDescriptor* Gigabit::RX[E1000_NUM_RX_DESC]
Definition at line 41 of file Gigabit.cpp.
Referenced by InitializeRX(), and InterruptCallback().
RXCurrent
uint16_t Gigabit::RXCurrent
Definition at line 39 of file Gigabit.cpp.
Referenced by InitializeRX(), and InterruptCallback().
TX
TXDescriptor* Gigabit::TX[E1000_NUM_TX_DESC]
Definition at line 42 of file Gigabit.cpp.
Referenced by CallbackHandler(), and InitializeTX().
TXCurrent
uint16_t Gigabit::TXCurrent
Definition at line 40 of file Gigabit.cpp.
Referenced by CallbackHandler(), and InitializeTX().