Fennix: Userspace/apps/base/busybox/libbb/bb_cat.c File Reference
bb_cat.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC bb_cat (char **argv)
Function Documentation
bb_cat()
int FAST_FUNC bb_cat (char ** argv)
Definition at line 11 of file bb_cat.c.
 {
     int fd;
     int retval = EXIT_SUCCESS;
     if (!*argv)
         argv = (char**) &bb_argv_dash;
     do {
         fd = open_or_warn_stdin(*argv);
         if (fd >= 0) {
             /* This is not a xfunc - never exits */
             off_t r = bb_copyfd_eof(fd, STDOUT_FILENO);
             if (fd != STDIN_FILENO)
                 close(fd);
             if (r >= 0)
                 continue;
         }
         retval = EXIT_FAILURE;
     } while (*++argv);
     return retval;
 }
References argv, bb_argv_dash, bb_copyfd_eof(), close(), EXIT_FAILURE, EXIT_SUCCESS, fd, open_or_warn_stdin(), retval, STDIN_FILENO, and STDOUT_FILENO.
Referenced by cat_main(), crontab_main(), less_main(), and more_main().