Fennix Kernel: Kernel/core/panic/user.cpp File Reference
user.cpp File Reference
#include <display.hpp>
#include <printf.h>
#include <debug.h>
#include <smp.hpp>
#include <cpu.hpp>
#include "../../kernel.h"
Functions
nsa bool UserModeExceptionHandler (CPU::ExceptionFrame *Frame)
Function Documentation
UserModeExceptionHandler()
nsa bool UserModeExceptionHandler (CPU::ExceptionFrame * Frame)
Definition at line 143 of file user.cpp.
 {
     CPUData *core = GetCurrentCPU();
     Tasking::PCB *proc = core->CurrentProcess;
     Tasking::TCB *thread = core->CurrentThread;
     debug("Current process %s(%d) and thread %s(%d)",
           proc->Name, proc->ID, thread->Name, thread->ID);
     thread->SetState(Tasking::Waiting);
 #ifdef DEBUG
     dbgPrint(Frame);
 #endif
     switch (Frame->InterruptNumber)
     {
     case CPU::x86::PageFault:
     {
         bool Handled = proc->vma->HandleCoW(Frame->cr2);
         if (!Handled)
             Handled = thread->Stack->Expand(Frame->cr2);
         if (Handled)
         {
             debug("Page fault handled");
             thread->SetState(Tasking::Ready);
             return true;
         }
         proc->Signals->SendSignal(SIGSEGV,
                                   {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::Debug:
     case CPU::x86::Breakpoint:
     {
         proc->Signals->SendSignal(SIGTRAP,
                                   {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::DivideByZero:
     case CPU::x86::Overflow:
     case CPU::x86::BoundRange:
     case CPU::x86::x87FloatingPoint:
     case CPU::x86::SIMDFloatingPoint:
     {
         proc->Signals->SendSignal(SIGFPE,
                                   {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::InvalidOpcode:
     case CPU::x86::GeneralProtectionFault:
     {
         proc->Signals->SendSignal(SIGILL,
                                   {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::DeviceNotAvailable:
     {
         proc->Signals->SendSignal(SIGBUS,
                                   {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::NonMaskableInterrupt:
     case CPU::x86::DoubleFault:
     case CPU::x86::CoprocessorSegmentOverrun:
     case CPU::x86::InvalidTSS:
     case CPU::x86::SegmentNotPresent:
     case CPU::x86::StackSegmentFault:
     case CPU::x86::AlignmentCheck:
     case CPU::x86::MachineCheck:
     case CPU::x86::Virtualization:
     case CPU::x86::Security:
     default:
     {
         error("Unhandled exception %d on CPU %d",
               Frame->InterruptNumber, core->ID);
         break;
     }
     }
     error("User mode exception handler failed");
     return false;
 }
References CPU::x86::AlignmentCheck, CPU::x86::BoundRange, CPU::x86::Breakpoint, CPU::x86::CoprocessorSegmentOverrun, CPUData::CurrentProcess, CPUData::CurrentThread, CPU::x86::Debug, debug, CPU::x86::DeviceNotAvailable, CPU::x86::DivideByZero, CPU::x86::DoubleFault, error, Memory::StackGuard::Expand(), CPU::x86::GeneralProtectionFault, GetCurrentCPU(), Memory::VirtualMemoryArea::HandleCoW(), CPUData::ID, Tasking::TCB::ID, Tasking::PCB::ID, CPU::x86::InvalidOpcode, CPU::x86::InvalidTSS, Tasking::KILL_CRASH, CPU::x86::MachineCheck, Tasking::TCB::Name, Tasking::PCB::Name, CPU::x86::NonMaskableInterrupt, CPU::x86::Overflow, CPU::x86::PageFault, Tasking::Ready, CPU::x86::Security, CPU::x86::SegmentNotPresent, Tasking::Signal::SendSignal(), Tasking::TCB::SetState(), SIGBUS, SIGFPE, SIGILL, Tasking::PCB::Signals, SIGSEGV, SIGTRAP, CPU::x86::SIMDFloatingPoint, Tasking::TCB::Stack, CPU::x86::StackSegmentFault, CPU::x86::Virtualization, Tasking::PCB::vma, Tasking::Waiting, and CPU::x86::x87FloatingPoint.
Referenced by HandleException().