Fennix: Userspace/musl/src/stdio/clearerr.c File Reference
clearerr.c File Reference
#include "stdio_impl.h"
Functions
void clearerr (FILE *f)
weak_alias (clearerr, clearerr_unlocked)
Function Documentation
clearerr()
void clearerr (FILE * f)
Definition at line 3 of file clearerr.c.
 {
     FLOCK(f);
     f->flags &= ~(F_EOF|F_ERR);
     FUNLOCK(f);
 }
References f, F_EOF, F_ERR, FLOCK, and FUNLOCK.
Referenced by evalbltin(), execute_builtin_or_function(), expand_main(), read_a_line(), retrieve_file_data(), sh_chkwrite(), and shell_getc().
weak_alias()
weak_alias (clearerr , clearerr_unlocked)