Fennix Kernel: Kernel/FileSystem/Mounts/Zero.cpp File Reference
Zero.cpp File Reference
#include <filesystem.hpp>
#include <errno.h>
#include "../../kernel.h"
Functions
ReadFSFunction (Zero_Read)
ReadFSFunction (Zero_Write)
void Init_Zero (Virtual *vfs_ctx)
Variables
FileSystemOperations zero_op
Function Documentation
Init_Zero()
void Init_Zero (Virtual * vfs_ctx)
Definition at line 45 of file Zero.cpp.
 {
     Node *n = vfs_ctx->Create("zero", CHARDEVICE, DevFS);
     n->Operator = &zero_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, VirtualFileSystem::Node::Operator, and zero_op.
Referenced by Main().
ReadFSFunction() [1/2]
ReadFSFunction (Zero_Read)
Definition at line 25 of file Zero.cpp.
 {
     if (Size <= 0)
         return 0;
     memset(Buffer, 0, Size);
     return Size;
 }
References memset(), and Size.
ReadFSFunction() [2/2]
ReadFSFunction (Zero_Write)
Definition at line 34 of file Zero.cpp.
 {
     return Size;
 }
References Size.
Variable Documentation
zero_op
FileSystemOperations zero_op
Initial value:
= {
    .Name = "Zero",
    .Read = Zero_Read,
    .Write = Zero_Write,
}
Definition at line 39 of file Zero.cpp.
Referenced by Init_Zero().