Fennix: Userspace/musl/src/stdlib/wcstod.c File Reference
wcstod.c File Reference
#include "shgetc.h"
#include "floatscan.h"
#include "stdio_impl.h"
#include <wchar.h>
#include <wctype.h>
Functions
static size_t do_read (FILE *f, unsigned char *buf, size_t len)
static long double wcstox (const wchar_t *s, wchar_t **p, int prec)
float wcstof (const wchar_t *restrict s, wchar_t **restrict p)
double wcstod (const wchar_t *restrict s, wchar_t **restrict p)
long double wcstold (const wchar_t *restrict s, wchar_t **restrict p)
Function Documentation
do_read()
static size_t do_read (FILE * f, unsigned char * buf, size_t len) static
Definition at line 11 of file wcstod.c.
 {
     size_t i;
     const wchar_t *wcs = f->cookie;
     if (!wcs[0]) wcs=L"@";
     for (i=0; i<f->buf_size && wcs[i]; i++)
         f->buf[i] = wcs[i] < 128 ? wcs[i] : '@';
     f->rpos = f->buf;
     f->rend = f->buf + i;
     f->cookie = (void *)(wcs+i);
     if (i && len) {
         *buf = *f->rpos++;
         return 1;
     }
     return 0;
 }
References buf, f, i, L, and len.
Referenced by wcstox().
wcstod()
double wcstod (const wchar_t *restrict s, wchar_t **restrict p)
Definition at line 56 of file wcstod.c.
 {
     return wcstox(s, p, 1);
 }
References p, and wcstox().
wcstof()
float wcstof (const wchar_t *restrict s, wchar_t **restrict p)
Definition at line 51 of file wcstod.c.
 {
     return wcstox(s, p, 0);
 }
References p, and wcstox().
wcstold()
long double wcstold (const wchar_t *restrict s, wchar_t **restrict p)
Definition at line 61 of file wcstod.c.
 {
     return wcstox(s, p, 2);
 }
References p, and wcstox().
wcstox()
static long double wcstox (const wchar_t * s, wchar_t ** p, int prec) static
Definition at line 30 of file wcstod.c.
 {
     wchar_t *t = (wchar_t *)s;
     unsigned char buf[64];
     FILE f = {0};
     f.flags = 0;
     f.rpos = f.rend = f.buf = buf + 4;
     f.buf_size = sizeof buf - 4;
     f.lock = -1;
     f.read = do_read;
     while (iswspace(*t)) t++;
     f.cookie = (void *)t;
     shlim(&f, 0);
     long double y = __floatscan(&f, prec, 1);
     if (p) {
         size_t cnt = shcnt(&f);
         *p = cnt ? t + cnt : (wchar_t *)s;
     }
     return y;
 }
References __floatscan(), buf, cnt, do_read(), f, iswspace(), p, shcnt, shlim, t, and y.
Referenced by wcstod(), wcstof(), and wcstold().