Fennix Kernel: CrashUHCIKeyboardDriver Class Reference
CrashUHCIKeyboardDriver Class Reference
#include <uhci.hpp>
Data Structures
struct IORegisters
union IORegisters.FRBASEADD
struct IORegisters.FRBASEADD.__packed
union IORegisters.FRNUM
struct IORegisters.FRNUM.__packed
union IORegisters.PORTSC
struct IORegisters.PORTSC.__packed
union IORegisters.SOFMOD
struct IORegisters.SOFMOD.__packed
union IORegisters.USBCMD
struct IORegisters.USBCMD.__packed
union IORegisters.USBINTR
struct IORegisters.USBINTR.__packed
union IORegisters.USBSTS
struct IORegisters.USBSTS.__packed
struct QH
union QH.ELEMENT
struct QH.ELEMENT.__packed
union QH.HEAD
struct QH.HEAD.__packed
struct TD
union TD.BUFFER
struct TD.BUFFER.__packed
union TD.CS
struct TD.CS.__packed
union TD.LINK
struct TD.LINK.__packed
union TD.TOKEN
struct TD.TOKEN.__packed
Public Member Functions
struct CrashUHCIKeyboardDriver::TD __aligned (16) __packed
struct CrashUHCIKeyboardDriver::QH __aligned (16) __packed
void OnInterruptReceived (CPU::TrapFrame *Frame)
bool Initialize ()
CrashUHCIKeyboardDriver (PCI::PCIDevice dev)
~CrashUHCIKeyboardDriver ()=default
Public Member Functions inherited from Interrupts::Handler
virtual void OnInterruptReceived (CPU::SchedulerFrame *Frame)
Data Fields
struct CrashUHCIKeyboardDriver::IORegisters __packed
PCI::PCIDeviceHeader * Header = nullptr
IORegisters * io = nullptr
uint32_t * FrameList = nullptr
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 22 of file uhci.hpp.
Data Structure Documentation
CrashUHCIKeyboardDriver::IORegisters
struct CrashUHCIKeyboardDriver::IORegisters
Definition at line 25 of file uhci.hpp.
Data Fields
union IORegisters FRBASEADD
union IORegisters FRNUM
union IORegisters PORTSC[2]
union IORegisters SOFMOD
union IORegisters USBCMD
union IORegisters USBINTR
union IORegisters USBSTS
CrashUHCIKeyboardDriver::IORegisters.FRBASEADD
union CrashUHCIKeyboardDriver::IORegisters.FRBASEADD
Definition at line 78 of file uhci.hpp.
Data Fields
FRBASEADD __packed
uint32_t raw
CrashUHCIKeyboardDriver::IORegisters.FRBASEADD.__packed
struct CrashUHCIKeyboardDriver::IORegisters.FRBASEADD.__packed
Definition at line 80 of file uhci.hpp.
Data Fields
uint32_t __reserved0: 12
uint32_t BA: 20
CrashUHCIKeyboardDriver::IORegisters.FRNUM
union CrashUHCIKeyboardDriver::IORegisters.FRNUM
Definition at line 69 of file uhci.hpp.
Data Fields
FRNUM __packed
uint16_t raw
CrashUHCIKeyboardDriver::IORegisters.FRNUM.__packed
struct CrashUHCIKeyboardDriver::IORegisters.FRNUM.__packed
Definition at line 71 of file uhci.hpp.
Data Fields
uint16_t __reserved0: 7
uint16_t FN: 9
CrashUHCIKeyboardDriver::IORegisters.PORTSC
union CrashUHCIKeyboardDriver::IORegisters.PORTSC
Definition at line 96 of file uhci.hpp.
Data Fields
PORTSC __packed
uint16_t raw
CrashUHCIKeyboardDriver::IORegisters.PORTSC.__packed
struct CrashUHCIKeyboardDriver::IORegisters.PORTSC.__packed
Definition at line 98 of file uhci.hpp.
Data Fields
uint16_t __reserved0: 1
uint16_t __reserved1: 2
uint16_t __reserved2: 4
uint16_t CCS: 1
uint16_t CSC: 1
uint16_t LS: 1
uint16_t LSDA: 1
uint16_t PE: 1
uint16_t PEC: 1
uint16_t PR: 1
uint16_t RD: 1
uint16_t SUS: 1
CrashUHCIKeyboardDriver::IORegisters.SOFMOD
union CrashUHCIKeyboardDriver::IORegisters.SOFMOD
Definition at line 87 of file uhci.hpp.
Data Fields
SOFMOD __packed
uint8_t raw
CrashUHCIKeyboardDriver::IORegisters.SOFMOD.__packed
struct CrashUHCIKeyboardDriver::IORegisters.SOFMOD.__packed
Definition at line 89 of file uhci.hpp.
Data Fields
uint8_t __reserved0: 1
uint8_t SOFTVAL: 7
CrashUHCIKeyboardDriver::IORegisters.USBCMD
union CrashUHCIKeyboardDriver::IORegisters.USBCMD
Definition at line 27 of file uhci.hpp.
Data Fields
USBCMD __packed
uint16_t raw
CrashUHCIKeyboardDriver::IORegisters.USBCMD.__packed
struct CrashUHCIKeyboardDriver::IORegisters.USBCMD.__packed
Definition at line 29 of file uhci.hpp.
Data Fields
uint16_t __reserved0: 8
uint16_t CF: 1
uint16_t EGSM: 1
uint16_t FGR: 1
uint16_t GRESET: 1
uint16_t HCRESET: 1
uint16_t MAXP: 1
uint16_t RS: 1
uint16_t SWDBG: 1
CrashUHCIKeyboardDriver::IORegisters.USBINTR
union CrashUHCIKeyboardDriver::IORegisters.USBINTR
Definition at line 57 of file uhci.hpp.
Data Fields
USBINTR __packed
uint16_t raw
CrashUHCIKeyboardDriver::IORegisters.USBINTR.__packed
struct CrashUHCIKeyboardDriver::IORegisters.USBINTR.__packed
Definition at line 59 of file uhci.hpp.
Data Fields
uint16_t __reserved0: 12
uint16_t IOCE: 1
uint16_t RIE: 1
uint16_t SPIE: 1
uint16_t TOCRC: 1
CrashUHCIKeyboardDriver::IORegisters.USBSTS
union CrashUHCIKeyboardDriver::IORegisters.USBSTS
Definition at line 43 of file uhci.hpp.
Data Fields
USBSTS __packed
uint16_t raw
CrashUHCIKeyboardDriver::IORegisters.USBSTS.__packed
struct CrashUHCIKeyboardDriver::IORegisters.USBSTS.__packed
Definition at line 45 of file uhci.hpp.
Data Fields
uint16_t __reserved0: 10
uint16_t HCH: 1
uint16_t HCPE: 1
uint16_t HSE: 1
uint16_t RD: 1
uint16_t USBERRINT: 1
uint16_t USBINT: 1
CrashUHCIKeyboardDriver::QH
struct CrashUHCIKeyboardDriver::QH
Definition at line 178 of file uhci.hpp.
Data Fields
union QH ELEMENT
union QH HEAD
CrashUHCIKeyboardDriver::QH.ELEMENT
union CrashUHCIKeyboardDriver::QH.ELEMENT
Definition at line 191 of file uhci.hpp.
Data Fields
ELEMENT __packed
uint32_t raw
CrashUHCIKeyboardDriver::QH.ELEMENT.__packed
struct CrashUHCIKeyboardDriver::QH.ELEMENT.__packed
Definition at line 193 of file uhci.hpp.
Data Fields
uint32_t __reserved0: 1
uint32_t __reserved1: 1
uint32_t Q: 1
uint32_t QELP: 28
uint32_t T: 1
CrashUHCIKeyboardDriver::QH.HEAD
union CrashUHCIKeyboardDriver::QH.HEAD
Definition at line 180 of file uhci.hpp.
Data Fields
HEAD __packed
uint32_t raw
CrashUHCIKeyboardDriver::QH.HEAD.__packed
struct CrashUHCIKeyboardDriver::QH.HEAD.__packed
Definition at line 182 of file uhci.hpp.
Data Fields
uint32_t __reserved0: 2
uint32_t Q: 1
uint32_t QHLP: 28
uint32_t T: 1
CrashUHCIKeyboardDriver::TD
struct CrashUHCIKeyboardDriver::TD
Definition at line 117 of file uhci.hpp.
Data Fields
uint32_t __padding[4]
union TD BUFFER
union TD CS
union TD LINK
union TD TOKEN
CrashUHCIKeyboardDriver::TD.BUFFER
union CrashUHCIKeyboardDriver::TD.BUFFER
Definition at line 160 of file uhci.hpp.
Data Fields
BUFFER __packed
uint32_t raw
CrashUHCIKeyboardDriver::TD.BUFFER.__packed
struct CrashUHCIKeyboardDriver::TD.BUFFER.__packed
Definition at line 162 of file uhci.hpp.
Data Fields
uint32_t Addr: 32
CrashUHCIKeyboardDriver::TD.CS
union CrashUHCIKeyboardDriver::TD.CS
Definition at line 131 of file uhci.hpp.
Data Fields
CS __packed
uint32_t raw
CrashUHCIKeyboardDriver::TD.CS.__packed
struct CrashUHCIKeyboardDriver::TD.CS.__packed
Definition at line 133 of file uhci.hpp.
Data Fields
uint32_t __reserved0: 5
uint32_t __reserved1: 2
uint32_t ActLen: 11
uint32_t IOC: 1
uint32_t IOS: 1
uint32_t LS: 1
uint32_t SPD: 1
uint32_t STATUS: 8
uint32_t unknown_0: 2
CrashUHCIKeyboardDriver::TD.LINK
union CrashUHCIKeyboardDriver::TD.LINK
Definition at line 119 of file uhci.hpp.
Data Fields
LINK __packed
uint32_t raw
CrashUHCIKeyboardDriver::TD.LINK.__packed
struct CrashUHCIKeyboardDriver::TD.LINK.__packed
Definition at line 121 of file uhci.hpp.
Data Fields
uint32_t __reserved0: 1
uint32_t LP: 28
uint32_t Q: 1
uint32_t T: 1
uint32_t Vf: 1
CrashUHCIKeyboardDriver::TD.TOKEN
union CrashUHCIKeyboardDriver::TD.TOKEN
Definition at line 147 of file uhci.hpp.
Data Fields
TOKEN __packed
uint32_t raw
CrashUHCIKeyboardDriver::TD.TOKEN.__packed
struct CrashUHCIKeyboardDriver::TD.TOKEN.__packed
Definition at line 149 of file uhci.hpp.
Data Fields
uint32_t __reserved0: 1
uint32_t D: 1
uint32_t DeviceAddress: 6
uint32_t EndPt: 4
uint32_t MaxLen: 11
uint32_t PID: 8
Constructor & Destructor Documentation
CrashUHCIKeyboardDriver()
nsa CrashUHCIKeyboardDriver::CrashUHCIKeyboardDriver (PCI::PCIDevice dev)
Definition at line 93 of file uhci.cpp.
     : Interrupts::Handler(dev)
 {
     Header = (PCIDeviceHeader *)dev.Header;
     switch (Header->HeaderType)
     {
     case 128:
     {
         ExPrint(ERROR_COLOR "Unknown header type %d! Guessing PCI Header 0\n" DEFAULT_COLOR,
                 Header->HeaderType);
         [[fallthrough]];
     }
     case 0: /* PCI Header 0 */
     {
         PCI::PCIHeader0 *hdr = (PCI::PCIHeader0 *)Header;
         uint32_t BAR[6];
         size_t BARsSize[6];
         BAR[0] = hdr->BAR0;
         BAR[1] = hdr->BAR1;
         BAR[2] = hdr->BAR2;
         BAR[3] = hdr->BAR3;
         BAR[4] = hdr->BAR4;
         BAR[5] = hdr->BAR5;
         /* BARs Size */
         for (short i = 0; i < 6; i++)
         {
             if (BAR[i] == 0)
                 continue;
             size_t size;
             if ((BAR[i] & 1) == 0) /* Memory Base */
             {
                 hdr->BAR0 = 0xFFFFFFFF;
                 size = hdr->BAR0;
                 hdr->BAR0 = BAR[i];
                 BARsSize[i] = size & (~15);
                 BARsSize[i] = ~BARsSize[i] + 1;
                 BARsSize[i] = BARsSize[i] & 0xFFFFFFFF;
                 debug("MEM BAR%d %#lx size: %d",
                       i, BAR[i], BARsSize[i]);
             }
             else if ((BAR[i] & 1) == 1) /* I/O Base */
             {
                 hdr->BAR1 = 0xFFFFFFFF;
                 size = hdr->BAR1;
                 hdr->BAR1 = BAR[i];
                 BARsSize[i] = size & (~3);
                 BARsSize[i] = ~BARsSize[i] + 1;
                 BARsSize[i] = BARsSize[i] & 0xFFFF;
                 debug("I/O BAR%d %#lx size: %d",
                       i, BAR[i], BARsSize[i]);
             }
         }
         uintptr_t baseAddress = BAR[4];
         assert(baseAddress & 0x1); /* must be I/O */
         debug("baseAddress: %#lx size %#lx", baseAddress, BARsSize[4]);
         Memory::Virtual vmm;
         vmm.Map((void *)baseAddress, (void *)baseAddress, BARsSize[4], Memory::RW);
         io = (IORegisters *)baseAddress;
         break;
     }
     case 1: /* PCI Header 1 (PCI-to-PCI Bridge) */
     {
         ExPrint(ERROR_COLOR "PCI-to-PCI Bridge not supported\n" DEFAULT_COLOR);
         break;
     }
     case 2: /* PCI Header 2 (PCI-to-CardBus Bridge) */
     {
         ExPrint(ERROR_COLOR "PCI-to-CardBus Bridge not supported\n" DEFAULT_COLOR);
         break;
     }
     default:
     {
         ExPrint(ERROR_COLOR "Invalid PCI header type\n" DEFAULT_COLOR);
         break;
     }
     }
 }
References assert, PCI::PCIHeader0::BAR0, PCI::PCIHeader0::BAR1, PCI::PCIHeader0::BAR2, PCI::PCIHeader0::BAR3, PCI::PCIHeader0::BAR4, PCI::PCIHeader0::BAR5, debug, DEFAULT_COLOR, ERROR_COLOR, ExPrint(), Header, PCI::PCIDevice::Header, PCI::PCIDeviceHeader::HeaderType, io, Memory::Virtual::Map(), Memory::RW, and size.
~CrashUHCIKeyboardDriver()
CrashUHCIKeyboardDriver::~CrashUHCIKeyboardDriver () default
Member Function Documentation
__aligned() [1/2]
struct CrashUHCIKeyboardDriver::TD CrashUHCIKeyboardDriver::__aligned (16)
__aligned() [2/2]
struct CrashUHCIKeyboardDriver::QH CrashUHCIKeyboardDriver::__aligned (16)
Initialize()
bool CrashUHCIKeyboardDriver::Initialize ()
Referenced by DetectUSBKeyboard().
OnInterruptReceived()
nsa void CrashUHCIKeyboardDriver::OnInterruptReceived (CPU::TrapFrame * Frame) virtual
Reimplemented from Interrupts::Handler.
Definition at line 50 of file uhci.cpp.
 {
 }
Field Documentation
__packed
struct CrashUHCIKeyboardDriver::IORegisters CrashUHCIKeyboardDriver::__packed
FrameList
uint32_t* CrashUHCIKeyboardDriver::FrameList = nullptr
Definition at line 209 of file uhci.hpp.
Header
PCI::PCIDeviceHeader* CrashUHCIKeyboardDriver::Header = nullptr
Definition at line 207 of file uhci.hpp.
Referenced by CrashUHCIKeyboardDriver().
io
IORegisters* CrashUHCIKeyboardDriver::io = nullptr
Definition at line 208 of file uhci.hpp.
Referenced by CrashUHCIKeyboardDriver().
The documentation for this class was generated from the following files:
Kernel/core/panic/kbd/uhci.hpp
Kernel/core/panic/kbd/uhci.cpp