Fennix: Kernel/Core/Crash/CrashDetails.cpp File Reference
CrashDetails.cpp File Reference
#include "../crashhandler.hpp"
#include "chfcts.hpp"
#include <display.hpp>
#include <printf.h>
#include <debug.h>
#include <smp.hpp>
#include <cpu.hpp>
#include "../../kernel.h"
Functions
SafeFunction void DivideByZeroExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void DebugExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void NonMaskableInterruptExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void BreakpointExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void OverflowExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void BoundRangeExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void InvalidOpcodeExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void DeviceNotAvailableExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void DoubleFaultExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void CoprocessorSegmentOverrunExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void InvalidTSSExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void SegmentNotPresentExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void StackFaultExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void GeneralProtectionExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void PageFaultExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void x87FloatingPointExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void AlignmentCheckExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void MachineCheckExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void SIMDFloatingPointExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void VirtualizationExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void SecurityExceptionHandler (CHArchTrapFrame *Frame)
SafeFunction void UnknownExceptionHandler (CHArchTrapFrame *Frame)
Variables
static const char * PageFaultDescriptions [8]
Function Documentation
AlignmentCheckExceptionHandler()
SafeFunction void AlignmentCheckExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 314 of file CrashDetails.cpp.
 {
     fixme("Alignment check exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
BoundRangeExceptionHandler()
SafeFunction void BoundRangeExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 75 of file CrashDetails.cpp.
 {
     fixme("Bound range exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
BreakpointExceptionHandler()
SafeFunction void BreakpointExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 63 of file CrashDetails.cpp.
 {
     fixme("Breakpoint exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
CoprocessorSegmentOverrunExceptionHandler()
SafeFunction void CoprocessorSegmentOverrunExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 99 of file CrashDetails.cpp.
 {
     fixme("Coprocessor segment overrun exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DebugExceptionHandler()
SafeFunction void DebugExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 51 of file CrashDetails.cpp.
 {
     CrashHandler::EHPrint("Kernel triggered debug exception.\n");
     UNUSED(Frame);
 }
References CrashHandler::EHPrint(), and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DeviceNotAvailableExceptionHandler()
SafeFunction void DeviceNotAvailableExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 87 of file CrashDetails.cpp.
 {
     fixme("Device not available exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DivideByZeroExceptionHandler()
SafeFunction void DivideByZeroExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 45 of file CrashDetails.cpp.
 {
     fixme("Divide by zero exception\n");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DoubleFaultExceptionHandler()
SafeFunction void DoubleFaultExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 93 of file CrashDetails.cpp.
 {
     fixme("Double fault exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
GeneralProtectionExceptionHandler()
SafeFunction void GeneralProtectionExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 132 of file CrashDetails.cpp.
 {
     CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
     // switch (SelCode.Table)
     // {
     // case CPU::x64::0b00:
     //     memcpy(desc_tmp, "GDT", 3);
     //     break;
     // case CPU::x64::0b01:
     //     memcpy(desc_tmp, "IDT", 3);
     //     break;
     // case CPU::x64::0b10:
     //     memcpy(desc_tmp, "LDT", 3);
     //     break;
     // case CPU::x64::0b11:
     //     memcpy(desc_tmp, "IDT", 3);
     //     break;
     // default:
     //     memcpy(desc_tmp, "Unknown", 7);
     //     break;
     // }
     CrashHandler::EHPrint("Kernel performed an illegal operation.\n");
     CrashHandler::EHPrint("External: %d\n", SelCode.External);
     CrashHandler::EHPrint("Table: %d\n", SelCode.Table);
     CrashHandler::EHPrint("Index: %#x\n", SelCode.Idx);
 }
References CrashHandler::EHPrint(), and x64::SelectorErrorCode::raw.
Referenced by CrashHandler::DisplayDetailsScreen().
InvalidOpcodeExceptionHandler()
SafeFunction void InvalidOpcodeExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 81 of file CrashDetails.cpp.
 {
     CrashHandler::EHPrint("Kernel tried to execute an invalid opcode.\n");
     UNUSED(Frame);
 }
References CrashHandler::EHPrint(), and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
InvalidTSSExceptionHandler()
SafeFunction void InvalidTSSExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 105 of file CrashDetails.cpp.
 {
     fixme("Invalid TSS exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
MachineCheckExceptionHandler()
SafeFunction void MachineCheckExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 320 of file CrashDetails.cpp.
 {
     fixme("Machine check exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
NonMaskableInterruptExceptionHandler()
SafeFunction void NonMaskableInterruptExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 57 of file CrashDetails.cpp.
 {
     fixme("NMI exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
OverflowExceptionHandler()
SafeFunction void OverflowExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 69 of file CrashDetails.cpp.
 {
     fixme("Overflow exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
PageFaultExceptionHandler()
SafeFunction void PageFaultExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 159 of file CrashDetails.cpp.
 {
     CPU::x64::PageFaultErrorCode params = {.raw = (uint32_t)Frame->ErrorCode};
 #if defined(a64)
     CrashHandler::EHPrint("\eAFAFAFAn exception occurred at %#lx by %#lx\n", CrashHandler::PageFaultAddress, Frame->rip);
 #elif defined(a32)
     CrashHandler::EHPrint("\eAFAFAFAn exception occurred at %#lx by %#lx\n", CrashHandler::PageFaultAddress, Frame->eip);
 #elif defined(aa64)
 #endif
     CrashHandler::EHPrint("Page: %s\n", params.P ? "Present" : "Not Present");
     CrashHandler::EHPrint("Write Operation: %s\n", params.W ? "Read-Only" : "Read-Write");
     CrashHandler::EHPrint("Processor Mode: %s\n", params.U ? "User-Mode" : "Kernel-Mode");
     CrashHandler::EHPrint("CPU Reserved Bits: %s\n", params.R ? "Reserved" : "Unreserved");
     CrashHandler::EHPrint("Caused By An Instruction Fetch: %s\n", params.I ? "Yes" : "No");
     CrashHandler::EHPrint("Caused By A Protection-Key Violation: %s\n", params.PK ? "Yes" : "No");
     CrashHandler::EHPrint("Caused By A Shadow Stack Access: %s\n", params.SS ? "Yes" : "No");
     CrashHandler::EHPrint("Caused By An SGX Violation: %s\n", params.SGX ? "Yes" : "No");
     if (Frame->ErrorCode & 0x00000008)
         CrashHandler::EHPrint("One or more page directory entries contain reserved bits which are set to 1.\n");
     else
         CrashHandler::EHPrint(PageFaultDescriptions[Frame->ErrorCode & 0b111]);
 #ifdef DEBUG
     uintptr_t CheckPageFaultAddress = 0;
     CheckPageFaultAddress = CrashHandler::PageFaultAddress;
     if (CheckPageFaultAddress == 0)
 #ifdef a64
         CheckPageFaultAddress = Frame->rip;
 #elif defined(a32)
         CheckPageFaultAddress = Frame->eip;
 #elif defined(aa64)
         CheckPageFaultAddress = 0;
 #endif
 #if defined(a64)
     Memory::Virtual vmm = Memory::Virtual(((Memory::PageTable *)CPU::x64::readcr3().raw));
 #elif defined(a32)
     Memory::Virtual vmm = Memory::Virtual(((Memory::PageTable *)CPU::x32::readcr3().raw));
 #elif defined(aa64)
     Memory::Virtual vmm = Memory::Virtual();
 #warning "TODO: aa64"
 #endif
     bool PageAvailable = vmm.Check((void *)CheckPageFaultAddress);
     debug("Page available (Check(...)): %s. %s",
           PageAvailable ? "Yes" : "No",
           (params.P && !PageAvailable) ? "CR2 == Present; Check() != Present??????" : "CR2 confirms Check() result.");
     if (PageAvailable)
     {
         bool Present = vmm.Check((void *)CheckPageFaultAddress);
         bool ReadWrite = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::RW);
         bool User = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::US);
         bool WriteThrough = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::PWT);
         bool CacheDisabled = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::PCD);
         bool Accessed = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::A);
         bool Dirty = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::D);
         bool Global = vmm.Check((void *)CheckPageFaultAddress, Memory::PTFlag::G);
         /* ... */
         debug("Page available: %s", Present ? "Yes" : "No");
         debug("Page read/write: %s", ReadWrite ? "Yes" : "No");
         debug("Page user/kernel: %s", User ? "User" : "Kernel");
         debug("Page write-through: %s", WriteThrough ? "Yes" : "No");
         debug("Page cache disabled: %s", CacheDisabled ? "Yes" : "No");
         debug("Page accessed: %s", Accessed ? "Yes" : "No");
         debug("Page dirty: %s", Dirty ? "Yes" : "No");
         debug("Page global: %s", Global ? "Yes" : "No");
         if (Present)
         {
 #if defined(a64)
             uintptr_t CheckPageFaultLinearAddress = (uintptr_t)CheckPageFaultAddress;
             CheckPageFaultLinearAddress &= 0xFFFFFFFFFFFFF000;
             debug("%#lx -> %#lx", CheckPageFaultAddress, CheckPageFaultLinearAddress);
             Memory::Virtual::PageMapIndexer Index = Memory::Virtual::PageMapIndexer((uintptr_t)CheckPageFaultLinearAddress);
             debug("Index for %#lx is PML:%d PDPTE:%d PDE:%d PTE:%d",
                   CheckPageFaultLinearAddress,
                   Index.PMLIndex,
                   Index.PDPTEIndex,
                   Index.PDEIndex,
                   Index.PTEIndex);
 #if defined(a64)
             Memory::PageMapLevel4 PML4 = ((Memory::PageTable *)CPU::x64::readcr3().raw)->Entries[Index.PMLIndex];
 #elif defined(a32)
             Memory::PageMapLevel4 PML4 = ((Memory::PageTable *)CPU::x32::readcr3().raw)->Entries[Index.PMLIndex];
 #elif defined(aa64)
             Memory::PageMapLevel4 PML4 = {.raw = 0};
 #warning "TODO: aa64"
 #endif
             Memory::PageDirectoryPointerTableEntryPtr *PDPTE = (Memory::PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4.GetAddress() << 12);
             Memory::PageDirectoryEntryPtr *PDE = (Memory::PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
             Memory::PageTableEntryPtr *PTE = (Memory::PageTableEntryPtr *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                   Index.PMLIndex, 0, 0, 0,
                   PML4.Present ? "1" : "0",
                   PML4.ReadWrite ? "1" : "0",
                   PML4.UserSupervisor ? "1" : "0",
                   PML4.WriteThrough ? "1" : "0",
                   PML4.CacheDisable ? "1" : "0",
                   PML4.Accessed ? "1" : "0",
                   PML4.ExecuteDisable ? "1" : "0",
                   PML4.GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                   Index.PMLIndex, Index.PDPTEIndex, 0, 0,
                   PDPTE->Entries[Index.PDPTEIndex].Present ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].ReadWrite ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].UserSupervisor ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].WriteThrough ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].CacheDisable ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].Accessed ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].ExecuteDisable ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                   Index.PMLIndex, Index.PDPTEIndex, Index.PDEIndex, 0,
                   PDE->Entries[Index.PDEIndex].Present ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].ReadWrite ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].UserSupervisor ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].WriteThrough ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].CacheDisable ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].Accessed ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].ExecuteDisable ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s D:%s PAT:%s G:%s PK:%d NX:%s Address:%#lx",
                   Index.PMLIndex, Index.PDPTEIndex, Index.PDEIndex, Index.PTEIndex,
                   PTE->Entries[Index.PTEIndex].Present ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].ReadWrite ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].UserSupervisor ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].WriteThrough ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].CacheDisable ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].Accessed ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].Dirty ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].PageAttributeTable ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].Global ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].ProtectionKey,
                   PTE->Entries[Index.PTEIndex].ExecuteDisable ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].GetAddress() << 12);
 #endif
         }
     }
 #endif
 }
References A, D, debug, CrashHandler::EHPrint(), Entries, G(), CrashHandler::PageFaultAddress, PageFaultDescriptions, PageTable(), params, PDE, PDPTE, PML4, Present, PTE, raw, and Tasking::User.
Referenced by CrashHandler::DisplayDetailsScreen().
SecurityExceptionHandler()
SafeFunction void SecurityExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 338 of file CrashDetails.cpp.
 {
     fixme("Security exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
SegmentNotPresentExceptionHandler()
SafeFunction void SegmentNotPresentExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 111 of file CrashDetails.cpp.
 {
     fixme("Segment not present exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
SIMDFloatingPointExceptionHandler()
SafeFunction void SIMDFloatingPointExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 326 of file CrashDetails.cpp.
 {
     fixme("SIMD floating point exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
StackFaultExceptionHandler()
SafeFunction void StackFaultExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 117 of file CrashDetails.cpp.
 {
     CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
 #if defined(a64)
     CrashHandler::EHPrint("Stack segment fault at address %#lx\n", Frame->rip);
 #elif defined(a32)
     CrashHandler::EHPrint("Stack segment fault at address %#lx\n", Frame->eip);
 #elif defined(aa64)
 #endif
     CrashHandler::EHPrint("External: %d\n", SelCode.External);
     CrashHandler::EHPrint("Table: %d\n", SelCode.Table);
     CrashHandler::EHPrint("Index: %#x\n", SelCode.Idx);
     CrashHandler::EHPrint("Error code: %#lx\n", Frame->ErrorCode);
 }
References CrashHandler::EHPrint(), and x64::SelectorErrorCode::raw.
Referenced by CrashHandler::DisplayDetailsScreen().
UnknownExceptionHandler()
SafeFunction void UnknownExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 344 of file CrashDetails.cpp.
 {
     fixme("Unknown exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
VirtualizationExceptionHandler()
SafeFunction void VirtualizationExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 332 of file CrashDetails.cpp.
 {
     fixme("Virtualization exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
x87FloatingPointExceptionHandler()
SafeFunction void x87FloatingPointExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 308 of file CrashDetails.cpp.
 {
     fixme("x87 floating point exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
Variable Documentation
PageFaultDescriptions
const char* PageFaultDescriptions[8] static
Initial value:
= {
    "Supervisory process tried to read a non-present page entry\n",
    "Supervisory process tried to read a page and caused a protection fault\n",
    "Supervisory process tried to write to a non-present page entry\n",
    "Supervisory process tried to write a page and caused a protection fault\n",
    "User process tried to read a non-present page entry\n",
    "User process tried to read a page and caused a protection fault\n",
    "User process tried to write to a non-present page entry\n",
    "User process tried to write a page and caused a protection fault\n"}
Definition at line 35 of file CrashDetails.cpp.
Referenced by PageFaultExceptionHandler().