Fennix: Userspace/musl/src/complex/catanf.c File Reference
catanf.c File Reference
#include "complex_impl.h"
Macros
#define MAXNUMF 1.0e38F
Functions
static float _redupif (float xx)
float complex catanf (float complex z)
Variables
static const double DP1 = 3.140625
static const double DP2 = 9.67502593994140625E-4
static const double DP3 = 1.509957990978376432E-7
static const float float_pi = M_PI
Macro Definition Documentation
MAXNUMF
#define MAXNUMF 1.0e38F
Definition at line 58 of file catanf.c.
Function Documentation
_redupif()
static float _redupif (float xx) static
Definition at line 66 of file catanf.c.
 {
     float x, t;
     long i;
     x = xx;
     t = x/float_pi;
     if (t >= 0.0f)
         t += 0.5f;
     else
         t -= 0.5f;
     i = t;  /* the multiple */
     t = i;
     t = ((x - t * DP1) - t * DP2) - t * DP3;
     return t;
 }
References DP1, DP2, DP3, float_pi, i, and x.
Referenced by catanf().
catanf()
float complex catanf (float complex z)
Definition at line 84 of file catanf.c.
 {
     float complex w;
     float a, t, x, x2, y;
     x = crealf(z);
     y = cimagf(z);
     x2 = x * x;
     a = 1.0f - x2 - (y * y);
     t = 0.5f * atan2f(2.0f * x, a);
     w = _redupif(t);
     t = y - 1.0f;
     a = x2 + (t * t);
     t = y + 1.0f;
     a = (x2 + (t * t))/a;
     w = CMPLXF(w, 0.25f * logf(a));
     return w;
 }
References _redupif(), atan2f(), cimagf, CMPLXF, complex, crealf, logf(), x, and y.
Referenced by catanhf().
Variable Documentation
DP1
const double DP1 = 3.140625 static
Definition at line 60 of file catanf.c.
Referenced by _redupif().
DP2
const double DP2 = 9.67502593994140625E-4 static
Definition at line 61 of file catanf.c.
Referenced by _redupif().
DP3
const double DP3 = 1.509957990978376432E-7 static
Definition at line 62 of file catanf.c.
Referenced by _redupif().
float_pi
const float float_pi = M_PI static
Definition at line 64 of file catanf.c.
Referenced by _redupif().