Fennix: Userspace/musl/src/process/fork.c File Reference
fork.c File Reference
#include <unistd.h>
#include <errno.h>
#include "libc.h"
#include "lock.h"
#include "pthread_impl.h"
#include "fork_impl.h"
Functions
weak_alias (dummy_lockptr, __at_quick_exit_lockptr)
weak_alias (dummy_lockptr, __atexit_lockptr)
weak_alias (dummy_lockptr, __gettext_lockptr)
weak_alias (dummy_lockptr, __locale_lockptr)
weak_alias (dummy_lockptr, __random_lockptr)
weak_alias (dummy_lockptr, __sem_open_lockptr)
weak_alias (dummy_lockptr, __stdio_ofl_lockptr)
weak_alias (dummy_lockptr, __syslog_lockptr)
weak_alias (dummy_lockptr, __timezone_lockptr)
weak_alias (dummy_lockptr, __bump_lockptr)
weak_alias (dummy_lockptr, __vmlock_lockptr)
static void dummy (int x)
weak_alias (dummy, __fork_handler)
weak_alias (dummy, __malloc_atfork)
weak_alias (dummy, __aio_atfork)
weak_alias (dummy, __pthread_key_atfork)
weak_alias (dummy, __ldso_atfork)
static void dummy_0 (void)
weak_alias (dummy_0, __tl_lock)
weak_alias (dummy_0, __tl_unlock)
pid_t fork (void)
Variables
static volatile int *const dummy_lockptr = 0
static volatile int *const *const atfork_locks []
Function Documentation
dummy()
static void dummy (int x) static
Definition at line 36 of file fork.c.
 { }
dummy_0()
static void dummy_0 (void) static
Definition at line 43 of file fork.c.
 { }
fork()
pid_t fork (void)
Definition at line 47 of file fork.c.
 {
     sigset_t set;
     __fork_handler(-1);
     __block_app_sigs(&set);
     int need_locks = libc.need_locks > 0;
     if (need_locks) {
         __ldso_atfork(-1);
         __pthread_key_atfork(-1);
         __aio_atfork(-1);
         __inhibit_ptc();
         for (int i=0; i<sizeof atfork_locks/sizeof *atfork_locks; i++)
             if (*atfork_locks[i]) LOCK(*atfork_locks[i]);
         __malloc_atfork(-1);
         __tl_lock();
     }
     pthread_t self=__pthread_self(), next=self->next;
     pid_t ret = _Fork();
     int errno_save = errno;
     if (need_locks) {
         if (!ret) {
             for (pthread_t td=next; td!=self; td=td->next)
                 td->tid = -1;
             if (__vmlock_lockptr) {
                 __vmlock_lockptr[0] = 0;
                 __vmlock_lockptr[1] = 0;
             }
         }
         __tl_unlock();
         __malloc_atfork(!ret);
         for (int i=0; i<sizeof atfork_locks/sizeof *atfork_locks; i++)
             if (*atfork_locks[i])
                 if (ret) UNLOCK(*atfork_locks[i]);
                 else **atfork_locks[i] = 0;
         __release_ptc();
         if (ret) __aio_atfork(0);
         __pthread_key_atfork(!ret);
         __ldso_atfork(!ret);
     }
     __restore_sigs(&set);
     __fork_handler(!ret);
     if (ret<0) errno = errno_save;
     return ret;
 }
References __aio_atfork(), __block_app_sigs(), __fork_handler(), __inhibit_ptc(), __ldso_atfork(), __malloc_atfork(), __pthread_key_atfork(), __pthread_self, __release_ptc(), __restore_sigs(), __tl_lock(), __tl_unlock(), __vmlock_lockptr, _Fork(), atfork_locks, errno, i, if(), libc, LOCK, next, sc_fork, syscall0(), td, and UNLOCK.
weak_alias() [1/18]
weak_alias (dummy , __aio_atfork)
weak_alias() [2/18]
weak_alias (dummy , __fork_handler)
weak_alias() [3/18]
weak_alias (dummy , __ldso_atfork)
weak_alias() [4/18]
weak_alias (dummy , __malloc_atfork)
weak_alias() [5/18]
weak_alias (dummy , __pthread_key_atfork)
weak_alias() [6/18]
weak_alias (dummy_0 , __tl_lock)
weak_alias() [7/18]
weak_alias (dummy_0 , __tl_unlock)
weak_alias() [8/18]
weak_alias (dummy_lockptr , __at_quick_exit_lockptr)
weak_alias() [9/18]
weak_alias (dummy_lockptr , __atexit_lockptr)
weak_alias() [10/18]
weak_alias (dummy_lockptr , __bump_lockptr)
weak_alias() [11/18]
weak_alias (dummy_lockptr , __gettext_lockptr)
weak_alias() [12/18]
weak_alias (dummy_lockptr , __locale_lockptr)
weak_alias() [13/18]
weak_alias (dummy_lockptr , __random_lockptr)
weak_alias() [14/18]
weak_alias (dummy_lockptr , __sem_open_lockptr)
weak_alias() [15/18]
weak_alias (dummy_lockptr , __stdio_ofl_lockptr)
weak_alias() [16/18]
weak_alias (dummy_lockptr , __syslog_lockptr)
weak_alias() [17/18]
weak_alias (dummy_lockptr , __timezone_lockptr)
weak_alias() [18/18]
weak_alias (dummy_lockptr , __vmlock_lockptr)
Variable Documentation
atfork_locks
volatile int* const* const atfork_locks[] static
Initial value:
= {
    &__at_quick_exit_lockptr,
    &__atexit_lockptr,
    &__gettext_lockptr,
    &__locale_lockptr,
    &__random_lockptr,
    &__sem_open_lockptr,
    &__stdio_ofl_lockptr,
    &__syslog_lockptr,
    &__timezone_lockptr,
    &__bump_lockptr,
}
Definition at line 23 of file fork.c.
Referenced by fork().
dummy_lockptr
volatile int* const dummy_lockptr = 0 static
Definition at line 8 of file fork.c.