Fennix Userspace: Userspace/apps/base/bash/lib/sh/zread.c File Reference
zread.c File Reference
#include <config.h>
#include <sys/types.h>
#include <signal.h>
#include <errno.h>
Macros
#define SEEK_CUR 1
#define ZBUFSIZ 4096
#define NUM_INTR 3
Functions
void check_signals_and_traps (void)
void check_signals (void)
int signal_is_trapped (int)
int read_builtin_timeout (int)
ssize_t zread (int fd, char *buf, size_t len)
ssize_t zreadretry (int fd, char *buf, size_t len)
ssize_t zreadintr (int fd, char *buf, size_t len)
ssize_t zreadc (int fd, char *cp)
ssize_t zreadcintr (int fd, char *cp)
ssize_t zreadn (int fd, char *cp, size_t len)
void zreset ()
void zsyncfd (int fd)
Variables
int errno
int executing_builtin
static char lbuf [ZBUFSIZ]
static size_t lind
static size_t lused
Macro Definition Documentation
NUM_INTR
#define NUM_INTR 3
Definition at line 87 of file zread.c.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 37 of file zread.c.
ZBUFSIZ
#define ZBUFSIZ 4096
Definition at line 41 of file zread.c.
Function Documentation
check_signals()
void check_signals (void)
Definition at line 617 of file trap.c.
 {
   /* Add any other shell timeouts here */
   check_read_timeout ();    /* set by the read builtin */
   QUIT;
 }
References QUIT.
Referenced by check_signals_and_traps(), zread(), and zreadintr().
check_signals_and_traps()
void check_signals_and_traps (void)
Definition at line 626 of file trap.c.
 {
   check_signals ();
   run_pending_traps ();
 }
References check_signals(), and run_pending_traps().
Referenced by zread().
read_builtin_timeout()
int read_builtin_timeout (int)
Referenced by zread().
signal_is_trapped()
int signal_is_trapped (int sig)
Definition at line 1503 of file trap.c.
 {
   return (sigmodes[sig] & SIG_TRAPPED);
 }
References SIG_TRAPPED, and sigmodes.
Referenced by default_tty_job_signals(), execute_command_internal(), execute_connection(), execute_in_subshell(), exit_shell(), initialize_terminating_signals(), morecore(), notify_of_job_status(), parse_and_execute(), reader_loop(), reset_terminating_signals(), set_job_status_and_cleanup(), should_optimize_fork(), sigint_sighandler(), subshell_exit(), termsig_handler(), throw_to_top_level(), wait_for(), wait_sigint_handler(), and waitchld().
zread()
ssize_t zread (int fd, char * buf, size_t len)
Definition at line 54 of file zread.c.
 {
   ssize_t r;
   check_signals (); /* check for signals before a blocking read */
   /* should generalize into a mechanism where different parts of the shell can
      `register' timeouts and have them checked here. */
   while (((r = read_builtin_timeout (fd)) < 0 || (r = read (fd, buf, len)) < 0) &&
          errno == EINTR)
     {
       int t;
       t = errno;
       /* XXX - bash-5.0 */
       /* We check executing_builtin and run traps here for backwards compatibility */
       if (executing_builtin)
     check_signals_and_traps (); /* XXX - should it be check_signals()? */
       else
     check_signals ();
       errno = t;
     }
   return r;
 }
References buf, check_signals(), check_signals_and_traps(), EINTR, errno, executing_builtin, fd, read(), read_builtin_timeout(), and t.
Referenced by read_comsub(), zcatfd(), zgetline(), zmapfd(), zreadc(), and zreadn().
zreadc()
ssize_t zreadc (int fd, char * cp)
Definition at line 132 of file zread.c.
 {
   ssize_t nr;
   if (lind == lused || lused == 0)
     {
       nr = zread (fd, lbuf, sizeof (lbuf));
       lind = 0;
       if (nr <= 0)
     {
       lused = 0;
       return nr;
     }
       lused = nr;
     }
   if (cp)
     *cp = lbuf[lind++];
   return 1;
 }
References fd, lbuf, lind, lused, and zread().
Referenced by zgetline().
zreadcintr()
ssize_t zreadcintr (int fd, char * cp)
Definition at line 157 of file zread.c.
 {
   ssize_t nr;
   if (lind == lused || lused == 0)
     {
       nr = zreadintr (fd, lbuf, sizeof (lbuf));
       lind = 0;
       if (nr <= 0)
     {
       lused = 0;
       return nr;
     }
       lused = nr;
     }
   if (cp)
     *cp = lbuf[lind++];
   return 1;
 }
References fd, lbuf, lind, lused, and zreadintr().
zreadintr()
ssize_t zreadintr (int fd, char * buf, size_t len)
Definition at line 115 of file zread.c.
 {
   check_signals ();
   return (read (fd, buf, len));
 }
References buf, check_signals(), fd, and read().
Referenced by zreadcintr().
zreadn()
ssize_t zreadn (int fd, char * cp, size_t len)
Definition at line 182 of file zread.c.
 {
   ssize_t nr;
   if (lind == lused || lused == 0)
     {
       if (len > sizeof (lbuf))
     len = sizeof (lbuf);
       nr = zread (fd, lbuf, len);
       lind = 0;
       if (nr <= 0)
     {
       lused = 0;
       return nr;
     }
       lused = nr;
     }
   if (cp)
     *cp = lbuf[lind++];
   return 1;
 }
References fd, lbuf, lind, lused, and zread().
zreadretry()
ssize_t zreadretry (int fd, char * buf, size_t len)
Definition at line 90 of file zread.c.
 {
   ssize_t r;
   int nintr;
   for (nintr = 0; ; )
     {
       r = read (fd, buf, len);
       if (r >= 0)
     return r;
       if (r == -1 && errno == EINTR)
     {
       if (++nintr >= NUM_INTR)
         return -1;
       continue;
     }
       return r;
     }
 }
References buf, EINTR, errno, fd, NUM_INTR, and read().
zreset()
void zreset ()
Definition at line 208 of file zread.c.
 {
   lind = lused = 0;
 }
References lind, and lused.
zsyncfd()
void zsyncfd (int fd)
Definition at line 216 of file zread.c.
 {
   off_t off, r;
   off = lused - lind;
   r = 0;
   if (off > 0)
     r = lseek (fd, -off, SEEK_CUR);
   if (r != -1)
     lused = lind = 0;
 }
References fd, lind, lseek(), lused, off, off_t, and SEEK_CUR.
Variable Documentation
errno
int errno extern
Referenced by zread(), and zreadretry().
executing_builtin
int executing_builtin extern
Definition at line 238 of file execute_cmd.c.
Referenced by execute_builtin(), execute_simple_command(), find_variable(), find_variable_for_assignment(), find_variable_last_nameref(), find_variable_nameref(), find_variable_no_invisible(), find_variable_noref(), heredoc_expand(), redirection_expand(), report_syntax_error(), waitchld(), and zread().
lbuf
char lbuf[ZBUFSIZ] static
Definition at line 128 of file zread.c.
Referenced by _rl_revert_previous_lines(), itos(), mitos(), uitos(), zcatfd(), zmapfd(), zreadc(), zreadcintr(), and zreadn().
lind
size_t lind static
Definition at line 129 of file zread.c.
Referenced by expassign(), zreadc(), zreadcintr(), zreadn(), zreset(), and zsyncfd().
lused
size_t lused static
Definition at line 129 of file zread.c.
Referenced by zreadc(), zreadcintr(), zreadn(), zreset(), and zsyncfd().