Fennix Userspace: Userspace/musl/src/math/exp2f.c File Reference
exp2f.c File Reference
#include <math.h>
#include <stdint.h>
#include "libm.h"
#include "exp2f_data.h"
Macros
#define N (1 << EXP2F_TABLE_BITS)
#define T __exp2f_data.tab
#define C __exp2f_data.poly
#define SHIFT __exp2f_data.shift_scaled
Functions
static uint32_t top12 (float x)
float exp2f (float x)
Macro Definition Documentation
C
#define C __exp2f_data.poly
Definition at line 25 of file exp2f.c.
N
#define N (1 << EXP2F_TABLE_BITS)
Definition at line 23 of file exp2f.c.
SHIFT
#define SHIFT __exp2f_data.shift_scaled
Definition at line 26 of file exp2f.c.
T
#define T __exp2f_data.tab
Definition at line 24 of file exp2f.c.
Function Documentation
exp2f()
float exp2f (float x)
Definition at line 33 of file exp2f.c.
 {
     uint32_t abstop;
     uint64_t ki, t;
     double_t kd, xd, z, r, r2, y, s;
     xd = (double_t)x;
     abstop = top12(x) & 0x7ff;
     if (predict_false(abstop >= top12(128.0f))) {
         /* |x| >= 128 or x is nan.  */
         if (asuint(x) == asuint(-INFINITY))
             return 0.0f;
         if (abstop >= top12(INFINITY))
             return x + x;
         if (x > 0.0f)
             return __math_oflowf(0);
         if (x <= -150.0f)
             return __math_uflowf(0);
     }
     /* x = k/N + r with r in [-1/(2N), 1/(2N)] and int k.  */
     kd = eval_as_double(xd + SHIFT);
     ki = asuint64(kd);
     kd -= SHIFT; /* k/N for int k.  */
     r = xd - kd;
     /* exp2(x) = 2^(k/N) * 2^r ~= s * (C0*r^3 + C1*r^2 + C2*r + 1) */
     t = T[ki % N];
     t += ki << (52 - EXP2F_TABLE_BITS);
     s = asdouble(t);
     z = C[0] * r + C[1];
     r2 = r * r;
     y = C[2] * r + 1;
     y = z * r2 + y;
     y = y * s;
     return eval_as_float(y);
 }
References __math_oflowf(), __math_uflowf(), asdouble, asuint, asuint64, C, eval_as_double(), eval_as_float(), EXP2F_TABLE_BITS, INFINITY, N, predict_false, r2, s, SHIFT, t, T, top12(), x, and y.
Referenced by exp10f().
top12()
static uint32_t top12 (float x) inline static
Definition at line 28 of file exp2f.c.
 {
     return asuint(x) >> 20;
 }
References asuint, and x.
Referenced by exp2f().