Fennix Userspace: Userspace/musl/src/passwd/getgr_r.c File Reference
getgr_r.c File Reference
#include "pwf.h"
#include <pthread.h>
Macros
#define FIX(x) (gr->gr_##x = gr->gr_##x-line+buf)
Functions
static int getgr_r (const char *name, gid_t gid, struct group *gr, char *buf, size_t size, struct group **res)
int getgrnam_r (const char *name, struct group *gr, char *buf, size_t size, struct group **res)
int getgrgid_r (gid_t gid, struct group *gr, char *buf, size_t size, struct group **res)
Macro Definition Documentation
FIX
#define FIX (x) (gr->gr_##x = gr->gr_##x-line+buf)
Definition at line 4 of file getgr_r.c.
Function Documentation
getgr_r()
static int getgr_r (const char * name, gid_t gid, struct group * gr, char * buf, size_t size, struct group ** res) static
Definition at line 6 of file getgr_r.c.
 {
     char *line = 0;
     size_t len = 0;
     char **mem = 0;
     size_t nmem = 0;
     int rv = 0;
     size_t i;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     rv = __getgr_a(name, gid, gr, &line, &len, &mem, &nmem, res);
     if (*res && size < len + (nmem+1)*sizeof(char *) + 32) {
         *res = 0;
         rv = ERANGE;
     }
     if (*res) {
         buf += (16-(uintptr_t)buf)%16;
         gr->gr_mem = (void *)buf;
         buf += (nmem+1)*sizeof(char *);
         memcpy(buf, line, len);
         FIX(name);
         FIX(passwd);
         for (i=0; mem[i]; i++)
             gr->gr_mem[i] = mem[i]-line+buf;
         gr->gr_mem[i] = 0;
     }
     free(mem);
     free(line);
     pthread_setcancelstate(cs, 0);
     if (rv) errno = rv;
     return rv;
 }
References __getgr_a(), buf, ERANGE, errno, FIX, free, gr, group::gr_mem, i, line, mem, memcpy(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and size.
Referenced by getgrgid_r(), and getgrnam_r().
getgrgid_r()
int getgrgid_r (gid_t gid, struct group * gr, char * buf, size_t size, struct group ** res)
Definition at line 46 of file getgr_r.c.
 {
     return getgr_r(0, gid, gr, buf, size, res);
 }
References buf, getgr_r(), gr, and size.
getgrnam_r()
int getgrnam_r (const char * name, struct group * gr, char * buf, size_t size, struct group ** res)
Definition at line 41 of file getgr_r.c.
 {
     return getgr_r(name, 0, gr, buf, size, res);
 }
References buf, getgr_r(), gr, and size.