Fennix Userspace: Userspace/apps/base/busybox/coreutils/libcoreutils/coreutils.h File Reference
coreutils.h File Reference
Functions
int cp_mv_stat2 (const char *fn, struct stat *fn_stat, stat_func sf) FAST_FUNC
int cp_mv_stat (const char *fn, struct stat *fn_stat) FAST_FUNC
mode_t getopt_mk_fifo_nod (char **argv) FAST_FUNC
Variables
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN typedef int(* stat_func)(const char *fn, struct stat *ps)
Function Documentation
cp_mv_stat()
int cp_mv_stat (const char * fn, struct stat * fn_stat)
Definition at line 45 of file cp_mv_stat.c.
 {
     return cp_mv_stat2(fn, fn_stat, stat);
 }
References cp_mv_stat2().
Referenced by cp_main(), and mv_main().
cp_mv_stat2()
int cp_mv_stat2 (const char * fn, struct stat * fn_stat, stat_func sf)
Definition at line 24 of file cp_mv_stat.c.
 {
     if (sf(fn, fn_stat) < 0) {
         if (errno != ENOENT) {
 #if ENABLE_FEATURE_VERBOSE_CP_MESSAGE
             if (errno == ENOTDIR) {
                 bb_error_msg("can't stat '%s': Path has non-directory component", fn);
                 return -1;
             }
 #endif
             bb_perror_msg("can't stat '%s'", fn);
             return -1;
         }
         return 0;
     }
     if (S_ISDIR(fn_stat->st_mode)) {
         return 3;
     }
     return 1;
 }
References bb_error_msg(), bb_perror_msg(), ENOENT, ENOTDIR, errno, S_ISDIR, and stat::st_mode.
Referenced by cp_main(), cp_mv_stat(), and mv_main().
getopt_mk_fifo_nod()
mode_t getopt_mk_fifo_nod (char ** argv)
Definition at line 24 of file getopt_mk_fifo_nod.c.
 {
     mode_t mode = 0666;
     char *smode = NULL;
 #if ENABLE_SELINUX
     security_context_t scontext;
 #endif
     int opt;
     opt = getopt32(argv, "m:" IF_SELINUX("Z:"), &smode IF_SELINUX(,&scontext));
     if (opt & 1) {
         mode = bb_parse_mode(smode, mode);
         if (mode != (mode_t)-1) /* if mode is valid */
             /* make future mknod/mkfifo set mode bits exactly */
             umask(0);
     }
 #if ENABLE_SELINUX
     if (opt & 2) {
         selinux_or_die();
         setfscreatecon_or_die(scontext);
     }
 #endif
     return mode;
 }
References argv, bb_parse_mode(), getopt32(), mode_t, NULL, opt, selinux_or_die(), setfscreatecon_or_die(), and umask().
Referenced by mkfifo_main(), and mknod_main().
Variable Documentation
stat_func
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN typedef int(* stat_func) (const char *fn, struct stat *ps) (const char * fn, struct stat * ps)
Definition at line 10 of file coreutils.h.