Fennix: Userspace/apps/base/busybox/libbb/signals.c File Reference
signals.c File Reference
#include "libbb.h"
Functions
void record_signo (int signo)
int FAST_FUNC sigaction_set (int signum, const struct sigaction *act)
int FAST_FUNC sigprocmask_allsigs (int how)
int FAST_FUNC sigprocmask2 (int how, sigset_t *set)
void FAST_FUNC bb_signals (int sigs, void(*f)(int))
void FAST_FUNC bb_signals_norestart (int sigs, void(*f)(int))
void FAST_FUNC sig_block (int sig)
void FAST_FUNC sig_unblock (int sig)
void FAST_FUNC wait_for_any_sig (void)
void FAST_FUNC kill_myself_with_sig (int sig)
void FAST_FUNC signal_SA_RESTART_empty_mask (int sig, void(*handler)(int))
void FAST_FUNC signal_no_SA_RESTART_empty_mask (int sig, void(*handler)(int))
Variables
smallint bb_got_signal
Function Documentation
bb_signals()
void FAST_FUNC bb_signals (int sigs, void(*)(int) f)
Definition at line 44 of file signals.c.
 {
     int sig_no = 0;
     int bit = 1;
     while (sigs) {
         if (sigs & bit) {
             sigs -= bit;
             signal(sig_no, f);
         }
         sig_no++;
         bit <<= 1;
     }
 }
References f, and signal.
Referenced by acpid_main(), bootchartd_main(), chat_main(), conspy_main(), ftpd_main(), hexedit_main(), ifplugd_main(), inotifyd_main(), launch_helper(), less_main(), logread_main(), make_new_session(), microcom_main(), more_main(), nc_main(), ntp_init(), passwd_main(), powertop_main(), reset_sighandlers_and_unblock_sigs(), resize_main(), runsv(), runsvdir_main(), slattach_main(), tcpudpsvd_main(), top_main(), udhcp_sp_setup(), vlock_main(), and watchdog_main().
bb_signals_norestart()
void FAST_FUNC bb_signals_norestart (int sigs, void(*)(int) f)
Definition at line 59 of file signals.c.
 {
     int sig_no = 0;
     int bit = 1;
     struct sigaction sa;
     memset(&sa, 0, sizeof(sa));
     sa.sa_handler = f;
     /*sa.sa_flags = 0;*/
     /*sigemptyset(&sa.sa_mask); - hope memset did it*/
     while (sigs) {
         if (sigs & bit) {
             sigs -= bit;
             sigaction_set(sig_no, &sa);
         }
         sig_no++;
         bit <<= 1;
     }
 }
References f, memset, and sigaction_set().
Referenced by klogd_main(), runsv_main(), showkey_main(), and svlogd_main().
kill_myself_with_sig()
void FAST_FUNC kill_myself_with_sig (int sig)
Definition at line 104 of file signals.c.
 {
     signal(sig, SIG_DFL);
     sig_unblock(sig);
     raise(sig);
     _exit(sig | 128); /* Should not reach it */
 }
References _exit(), SIG_DFL, sig_unblock(), and signal.
Referenced by catch(), cleanup(), do_syslogd(), interrupted(), klogd_main(), ntpd_main(), sig_catcher(), sig_term_handler(), and xvfork_parent_waits_and_exits().
record_signo()
void record_signo (int signo)
Definition at line 16 of file signals.c.
 {
     bb_got_signal = signo;
 }
References bb_got_signal.
Referenced by bootchartd_main(), do_syslogd(), fsck_main(), ifplugd_main(), init_tty_attrs(), inotifyd_main(), klogd_main(), microcom_main(), ntp_init(), runsvdir_main(), script_main(), showkey_main(), stop_handler(), and telnet_main().
sig_block()
void FAST_FUNC sig_block (int sig)
Definition at line 80 of file signals.c.
 {
     sigset_t ss;
     sigemptyset(&ss);
     sigaddset(&ss, sig);
     sigprocmask(SIG_BLOCK, &ss, NULL);
 }
References NULL, SIG_BLOCK, sigaddset(), sigemptyset(), and sigprocmask().
Referenced by processorstop(), runsv_main(), and tcpudpsvd_main().
sig_unblock()
void FAST_FUNC sig_unblock (int sig)
Definition at line 88 of file signals.c.
 {
     sigset_t ss;
     sigemptyset(&ss);
     sigaddset(&ss, sig);
     sigprocmask(SIG_UNBLOCK, &ss, NULL);
 }
References NULL, sigaddset(), sigemptyset(), and sigprocmask().
Referenced by kill_myself_with_sig(), processorstop(), runsv_main(), startservice(), tcpudpsvd_main(), and vlock_main().
sigaction_set()
int FAST_FUNC sigaction_set (int signum, const struct sigaction * act)
Definition at line 22 of file signals.c.
 {
     return sigaction(signum, act, NULL);
 }
References act(), and NULL.
Referenced by bb_ask_noecho(), bb_signals_norestart(), devfsd_main(), inetd_main(), init_main(), setsignal(), signal_no_SA_RESTART_empty_mask(), and signal_SA_RESTART_empty_mask().
signal_no_SA_RESTART_empty_mask()
void FAST_FUNC signal_no_SA_RESTART_empty_mask (int sig, void(*)(int) handler)
Definition at line 122 of file signals.c.
 {
     struct sigaction sa;
     memset(&sa, 0, sizeof(sa));
     /*sigemptyset(&sa.sa_mask);*/
     /*sa.sa_flags = 0;*/
     sa.sa_handler = handler;
     sigaction_set(sig, &sa);
 }
References handler(), memset, and sigaction_set().
Referenced by do_syslogd(), fsck_main(), init_tty_attrs(), and rx_main().
signal_SA_RESTART_empty_mask()
void FAST_FUNC signal_SA_RESTART_empty_mask (int sig, void(*)(int) handler)
Definition at line 112 of file signals.c.
 {
     struct sigaction sa;
     memset(&sa, 0, sizeof(sa));
     /*sigemptyset(&sa.sa_mask);*/
     sa.sa_flags = SA_RESTART;
     sa.sa_handler = handler;
     sigaction_set(sig, &sa);
 }
References handler(), memset, SA_RESTART, and sigaction_set().
Referenced by dd_main(), and vlock_main().
sigprocmask2()
int FAST_FUNC sigprocmask2 (int how, sigset_t * set)
Definition at line 34 of file signals.c.
 {
     // Grr... gcc 8.1.1:
     // "passing argument 3 to restrict-qualified parameter aliases with argument 2"
     // dance around that...
     sigset_t *oset FIX_ALIASING;
     oset = set;
     return sigprocmask(how, set, oset);
 }
References FIX_ALIASING, and sigprocmask().
Referenced by block_CHLD_HUP_ALRM(), and waitproc().
sigprocmask_allsigs()
int FAST_FUNC sigprocmask_allsigs (int how)
Definition at line 27 of file signals.c.
 {
     sigset_t set;
     sigfillset(&set);
     return sigprocmask(how, &set, NULL);
 }
References NULL, sigfillset(), and sigprocmask().
Referenced by raise_interrupt(), and reset_sighandlers_and_unblock_sigs().
wait_for_any_sig()
void FAST_FUNC wait_for_any_sig (void)
Definition at line 96 of file signals.c.
 {
     sigset_t ss;
     sigemptyset(&ss);
     sigsuspend(&ss);
 }
References sigemptyset(), and sigsuspend().
Referenced by tcpudpsvd_main().
Variable Documentation
bb_got_signal
smallint bb_got_signal
Definition at line 14 of file signals.c.
Referenced by check_all(), check_errors_in_children(), con_escape(), do_logging(), do_syslogd(), fsck_main(), hexedit_main(), ifplugd_main(), inotifyd_main(), kill_all_if_got_signal(), klogd_main(), microcom_main(), ntpd_main(), preadfd(), record_pending_signo(), record_signo(), runsv(), runsvdir_main(), script_main(), showkey_main(), sig_catcher(), signal_handler(), stop_handler(), tar_main(), and telnet_main().