Fennix Userspace: Userspace/musl/include/search.h File Reference
search.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct entry
Macros
#define __NEED_size_t
Typedefs
typedef struct entry ENTRY
Enumerations
enum ACTION { FIND , ENTER }
enum VISIT { preorder , postorder , endorder , leaf }
Functions
int hcreate (size_t)
void hdestroy (void)
ENTRY * hsearch (ENTRY, ACTION)
void insque (void *, void *)
void remque (void *)
void * lsearch (const void *, void *, size_t *, size_t, int(*)(const void *, const void *))
void * lfind (const void *, const void *, size_t *, size_t, int(*)(const void *, const void *))
void * tdelete (const void *__restrict, void **__restrict, int(*)(const void *, const void *))
void * tfind (const void *, void *const *, int(*)(const void *, const void *))
void * tsearch (const void *, void **, int(*)(const void *, const void *))
void twalk (const void *, void(*)(const void *, VISIT, int))
Data Structure Documentation
entry
struct entry
Definition at line 16 of file search.h.
Data Fields
void * data
char * key
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file search.h.
Typedef Documentation
ENTRY
typedef struct entry ENTRY
Enumeration Type Documentation
ACTION
enum ACTION
Enumerator
FIND
ENTER
Definition at line 13 of file search.h.
 { FIND, ENTER } ACTION;
VISIT
enum VISIT
Enumerator
preorder
postorder
endorder
leaf
Definition at line 14 of file search.h.
 { preorder, postorder, endorder, leaf } VISIT;
Function Documentation
hcreate()
int hcreate (size_t nel)
Definition at line 72 of file hsearch.c.
 {
     return __hcreate_r(nel, &htab);
 }
References __hcreate_r(), and htab.
hdestroy()
void hdestroy (void)
Definition at line 77 of file hsearch.c.
 {
     __hdestroy_r(&htab);
 }
References __hdestroy_r(), and htab.
hsearch()
ENTRY* hsearch (ENTRY item, ACTION action)
Definition at line 95 of file hsearch.c.
 {
     ENTRY *e;
     __hsearch_r(item, action, &e, &htab);
     return e;
 }
References __hsearch_r(), and htab.
insque()
void insque (void * element, void * pred)
Definition at line 8 of file insque.c.
 {
     struct node *e = element;
     struct node *p = pred;
     if (!p) {
         e->next = e->prev = 0;
         return;
     }
     e->next = p->next;
     e->prev = p;
     p->next = e;
     if (e->next)
         e->next->prev = e;
 }
References node::next, p, and node::prev.
lfind()
void* lfind (const void * key, const void * base, size_t * nelp, size_t width, int(*)(const void *, const void *) compar)
Definition at line 18 of file lsearch.c.
 {
     char (*p)[width] = (void *)base;
     size_t n = *nelp;
     size_t i;
     for (i = 0; i < n; i++)
         if (compar(key, p[i]) == 0)
             return p[i];
     return 0;
 }
References base, i, n, p, and width.
lsearch()
void* lsearch (const void * key, void * base, size_t * nelp, size_t width, int(*)(const void *, const void *) compar)
Definition at line 4 of file lsearch.c.
 {
     char (*p)[width] = base;
     size_t n = *nelp;
     size_t i;
     for (i = 0; i < n; i++)
         if (compar(key, p[i]) == 0)
             return p[i];
     *nelp = n+1;
     return memcpy(p[n], key, width);
 }
References base, i, memcpy(), n, p, and width.
remque()
void remque (void * element)
Definition at line 24 of file insque.c.
 {
     struct node *e = element;
     if (e->next)
         e->next->prev = e->prev;
     if (e->prev)
         e->prev->next = e->next;
 }
References node::next, and node::prev.
tdelete()
void* tdelete (const void * __restrict, void ** __restrict, int(*)(const void *, const void *))
tfind()
void* tfind (const void * key, void *const * rootp, int(*)(const void *, const void *) cmp)
Definition at line 4 of file tfind.c.
 {
     if (!rootp)
         return 0;
     struct node *n = *rootp;
     for (;;) {
         if (!n)
             break;
         int c = cmp(key, n->key);
         if (!c)
             break;
         n = n->a[c>0];
     }
     return n;
 }
References c, cmp(), node::key, and n.
tsearch()
void* tsearch (const void * key, void ** rootp, int(*)(const void *, const void *) cmp)
Definition at line 62 of file tsearch.c.
 {
     if (!rootp)
         return 0;
     void **a[MAXH];
     struct node *n = *rootp;
     struct node *r;
     int i=0;
     a[i++] = rootp;
     for (;;) {
         if (!n)
             break;
         int c = cmp(key, n->key);
         if (!c)
             return n;
         a[i++] = &n->a[c>0];
         n = n->a[c>0];
     }
     r = malloc(sizeof *r);
     if (!r)
         return 0;
     r->key = key;
     r->a[0] = r->a[1] = 0;
     r->h = 1;
     /* insert new node, rebalance ancestors.  */
     *a[--i] = r;
     while (i && __tsearch_balance(a[--i]));
     return r;
 }
References __tsearch_balance(), node::a, c, cmp(), node::h, i, node::key, malloc, MAXH, and n.
Referenced by while().
twalk()
void twalk (const void * root, void(*)(const void *, VISIT, int) action)
Definition at line 19 of file twalk.c.
 {
     walk(root, action, 0);
 }
References walk().