Fennix: Userspace/apps/base/busybox/debianutils/which.c File Reference
which.c File Reference
#include "libbb.h"
Functions
int which_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
which_main()
int which_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 32 of file which.c.
 {
     char *env_path;
     int status = 0;
     /* This sizeof(): bb_default_root_path is shorter than BB_PATH_ROOT_PATH */
     char buf[sizeof(BB_PATH_ROOT_PATH)];
     env_path = getenv("PATH");
     if (!env_path)
         /* env_path must be writable, and must not alloc, so... */
         env_path = strcpy(buf, bb_default_root_path);
     getopt32(argv, "^" "a" "\0" "-1"/*at least one arg*/);
     argv += optind;
     do {
         int missing = 1;
         /* If file contains a slash don't use PATH */
         if (strchr(*argv, '/')) {
             if (file_is_executable(*argv)) {
                 missing = 0;
                 puts(*argv);
             }
         } else {
             char *path;
             char *p;
             path = env_path;
             /* NOFORK NB: xmalloc inside find_executable(), must have no allocs above! */
             while ((p = find_executable(*argv, &path)) != NULL) {
                 missing = 0;
                 puts(p);
                 free(p);
                 if (!option_mask32) /* -a not set */
                     break;
             }
         }
         status |= missing;
     } while (*++argv);
     return status;
 }
References argv, bb_default_root_path, BB_PATH_ROOT_PATH, buf, env_path, file_is_executable(), find_executable(), free, getenv, getopt32(), NULL, optind, option_mask32, p, puts(), status, strchr(), and strcpy.