Fennix: Userspace/apps/base/bash/examples/loadables/logname.c File Reference
logname.c File Reference
#include <config.h>
#include <stdio.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
Functions
int logname_builtin (WORD_LIST *list)
Variables
int errno
char * logname_doc []
struct builtin logname_struct
Function Documentation
logname_builtin()
int logname_builtin (WORD_LIST * list)
Definition at line 39 of file logname.c.
 {
   char *np;
   if (no_options (list))
     return (EX_USAGE);
   np = getlogin ();
   if (np == 0)
     {
       builtin_error ("cannot find username: %s", strerror (errno));
       return (EXECUTION_FAILURE);
     }
   printf ("%s\n", np);
   return (EXECUTION_SUCCESS);
 }
References builtin_error(), errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, getlogin(), list(), no_options(), printf, and strerror().
Variable Documentation
errno
int errno extern
Referenced by logname_builtin().
logname_doc
char* logname_doc[]
Initial value:
= {
    "Display user login name.",
    "",
    "Write the current user's login name to the standard output",
    "and exit.  logname ignores the LOGNAME and USER variables.",
    "logname ignores any non-option arguments.",
    (char *)NULL
}
Definition at line 57 of file logname.c.
logname_struct
struct builtin logname_struct
Initial value:
= {
    "logname",
    logname_builtin,
    BUILTIN_ENABLED,
    logname_doc,
    "logname",
    0
}
Definition at line 57 of file logname.c.