Fennix: Userspace/apps/base/busybox/networking/tcpudp_perhost.h File Reference
tcpudp_perhost.h File Reference
Data Structures
struct hcc
Functions
struct hcc *FAST_FUNC ipsvd_perhost_init (unsigned)
unsigned FAST_FUNC ipsvd_perhost_add (struct hcc *cc, char *ip, unsigned maxconn, struct hcc **hccpp)
void FAST_FUNC ipsvd_perhost_remove (struct hcc *cc, int pid)
Data Structure Documentation
hcc
struct hcc
Definition at line 12 of file tcpudp_perhost.h.
Data Fields
char * ip
int pid
Function Documentation
ipsvd_perhost_add()
unsigned FAST_FUNC ipsvd_perhost_add (struct hcc * cc, char * ip, unsigned maxconn, struct hcc ** hccpp)
Definition at line 21 of file tcpudp_perhost.c.
 {
     unsigned i;
     unsigned conn = 1;
     int freepos = -1;
     for (i = 0; cc[i].pid >= 0; ++i) {
         if (!cc[i].ip) {
             freepos = i;
             continue;
         }
         if (strcmp(cc[i].ip, ip) == 0) {
             conn++;
             continue;
         }
     }
     if (freepos == -1) return 0;
     if (conn <= maxconn) {
         cc[freepos].ip = ip;
         *hccpp = &cc[freepos];
     }
     return conn;
 }
References i, hcc::ip, hcc::pid, and strcmp.
Referenced by tcpudpsvd_main().
ipsvd_perhost_init()
struct hcc* FAST_FUNC ipsvd_perhost_init (unsigned c)
Definition at line 13 of file tcpudp_perhost.c.
 {
 //  free(cc);
     struct hcc *cc = xzalloc((c + 1) * sizeof(*cc));
     cc[c].pid = -1; /* "end" marker */
     return cc;
 }
References c, hcc::pid, and xzalloc().
Referenced by tcpudpsvd_main().
ipsvd_perhost_remove()
void FAST_FUNC ipsvd_perhost_remove (struct hcc * cc, int pid)
Definition at line 45 of file tcpudp_perhost.c.
 {
     unsigned i;
     for (i = 0; cc[i].pid >= 0; ++i) {
         if (cc[i].pid == pid) {
             free(cc[i].ip);
             cc[i].ip = NULL;
             cc[i].pid = 0;
             return;
         }
     }
 }
References free, i, hcc::ip, NULL, hcc::pid, and pid.
Referenced by sig_child_handler().