Fennix Userspace: Userspace/apps/base/bash/lib/sh/stringlist.c File Reference
stringlist.c File Reference
#include <config.h>
#include <stdio.h>
#include <bashansi.h>
#include "shell.h"
Macros
#define STRDUP(x) ((x) ? savestring (x) : (char *)NULL)
Functions
STRINGLIST * strlist_create (int n)
STRINGLIST * strlist_resize (STRINGLIST *sl, int n)
void strlist_flush (STRINGLIST *sl)
void strlist_dispose (STRINGLIST *sl)
int strlist_remove (STRINGLIST *sl, char *s)
STRINGLIST * strlist_copy (STRINGLIST *sl)
STRINGLIST * strlist_merge (STRINGLIST *m1, STRINGLIST *m2)
STRINGLIST * strlist_append (STRINGLIST *m1, STRINGLIST *m2)
STRINGLIST * strlist_prefix_suffix (STRINGLIST *sl, char *prefix, char *suffix)
void strlist_print (STRINGLIST *sl, char *prefix)
void strlist_walk (STRINGLIST *sl, sh_strlist_map_func_t *func)
void strlist_sort (STRINGLIST *sl)
STRINGLIST * strlist_from_word_list (WORD_LIST *list, int alloc, int starting_index, int *ip)
WORD_LIST * strlist_to_word_list (STRINGLIST *sl, int alloc, int starting_index)
Macro Definition Documentation
STRDUP
#define STRDUP (x) ((x) ? savestring (x) : (char *)NULL)
Definition at line 35 of file stringlist.c.
Function Documentation
strlist_append()
STRINGLIST* strlist_append (STRINGLIST * m1, STRINGLIST * m2)
Definition at line 168 of file stringlist.c.
 {
   register int i, n, len1, len2;
   if (m1 == 0)
     return (m2 ? strlist_copy (m2) : (STRINGLIST *)0);
   len1 = m1->list_len;
   len2 = m2 ? m2->list_len : 0;
   if (len2)
     {
       m1 = strlist_resize (m1, len1 + len2 + 1);
       for (i = 0, n = len1; i < len2; i++, n++)
     m1->list[n] = STRDUP (m2->list[i]);
       m1->list[n] = (char *)NULL;
       m1->list_len = n;
     }
   return m1;
 }
References i, _list_of_strings::list, _list_of_strings::list_len, n, NULL, STRDUP, strlist_copy(), and strlist_resize().
strlist_copy()
STRINGLIST* strlist_copy (STRINGLIST * sl)
Definition at line 121 of file stringlist.c.
 {
   STRINGLIST *new;
   register int i;
   if (sl == 0)
     return ((STRINGLIST *)0);
   new = strlist_create (sl->list_size);
   /* I'd like to use strvec_copy, but that doesn't copy everything. */
   if (sl->list)
     {
       for (i = 0; i < sl->list_size; i++)
     new->list[i] = STRDUP (sl->list[i]);
     }
   new->list_size = sl->list_size;
   new->list_len = sl->list_len;
   /* just being careful */
   if (new->list)
     new->list[new->list_len] = (char *)NULL;
   return new;
 }
References i, _list_of_strings::list, _list_of_strings::list_len, _list_of_strings::list_size, NULL, STRDUP, and strlist_create().
Referenced by strlist_append().
strlist_create()
STRINGLIST* strlist_create (int n)
Definition at line 40 of file stringlist.c.
 {
   STRINGLIST *ret;
   register int i;
   ret = (STRINGLIST *)xmalloc (sizeof (STRINGLIST));
   if (n)
     {
       ret->list = strvec_create (n+1);
       ret->list_size = n;
       for (i = 0; i < n; i++)
     ret->list[i] = (char *)NULL;
     }
   else
     {
       ret->list = (char **)NULL;
       ret->list_size = 0;
     }
   ret->list_len = 0;
   return ret;
 }
References i, _list_of_strings::list, _list_of_strings::list_len, _list_of_strings::list_size, n, NULL, strvec_create(), and xmalloc.
Referenced by strlist_copy(), strlist_merge(), and strlist_resize().
strlist_dispose()
void strlist_dispose (STRINGLIST * sl)
Definition at line 94 of file stringlist.c.
 {
   if (sl == 0)
     return;
   if (sl->list)
     strvec_dispose (sl->list);
   free (sl);
 }
References free, _list_of_strings::list, and strvec_dispose().
strlist_flush()
void strlist_flush (STRINGLIST * sl)
Definition at line 84 of file stringlist.c.
 {
   if (sl == 0 || sl->list == 0)
     return;
   strvec_flush (sl->list);
   sl->list_len = 0;
 }
References _list_of_strings::list, _list_of_strings::list_len, and strvec_flush().
strlist_from_word_list()
STRINGLIST* strlist_from_word_list (WORD_LIST * list, int alloc, int starting_index, int * ip)
Definition at line 262 of file stringlist.c.
 {
   STRINGLIST *ret;
   int slen, len;
   if (list == 0)
     {
       if (ip)
         *ip = 0;
       return ((STRINGLIST *)0);
     }
   slen = list_length (list);
   ret = (STRINGLIST *)xmalloc (sizeof (STRINGLIST));
   ret->list = strvec_from_word_list (list, alloc, starting_index, &len);
   ret->list_size = slen + starting_index;
   ret->list_len = len;
   if (ip)
     *ip = len;
   return ret;
 }
References _list_of_strings::list, list(), _list_of_strings::list_len, list_length(), _list_of_strings::list_size, strvec_from_word_list(), and xmalloc.
strlist_merge()
STRINGLIST* strlist_merge (STRINGLIST * m1, STRINGLIST * m2)
Definition at line 147 of file stringlist.c.
 {
   STRINGLIST *sl;
   int i, n, l1, l2;
   l1 = m1 ? m1->list_len : 0;
   l2 = m2 ? m2->list_len : 0;
   sl = strlist_create (l1 + l2 + 1);
   for (i = n = 0; i < l1; i++, n++)
     sl->list[n] = STRDUP (m1->list[i]);
   for (i = 0; i < l2; i++, n++)
     sl->list[n] = STRDUP (m2->list[i]);
   sl->list_len = n;
   sl->list[n] = (char *)NULL;
   return (sl);
 }
References i, l1, _list_of_strings::list, _list_of_strings::list_len, n, NULL, STRDUP, and strlist_create().
strlist_prefix_suffix()
STRINGLIST* strlist_prefix_suffix (STRINGLIST * sl, char * prefix, char * suffix)
Definition at line 192 of file stringlist.c.
 {
   int plen, slen, tlen, llen, i;
   char *t;
   if (sl == 0 || sl->list == 0 || sl->list_len == 0)
     return sl;
   plen = STRLEN (prefix);
   slen = STRLEN (suffix);
   if (plen == 0 && slen == 0)
     return (sl);
   for (i = 0; i < sl->list_len; i++)
     {
       llen = STRLEN (sl->list[i]);
       tlen = plen + llen + slen + 1;
       t = (char *)xmalloc (tlen + 1);
       if (plen)
     strcpy (t, prefix);
       strcpy (t + plen, sl->list[i]);
       if (slen)
     strcpy (t + plen + llen, suffix);
       free (sl->list[i]);
       sl->list[i] = t;
     }
   return (sl);
 }
References free, i, _list_of_strings::list, _list_of_strings::list_len, prefix(), strcpy(), STRLEN, t, and xmalloc.
strlist_print()
void strlist_print (STRINGLIST * sl, char * prefix)
Definition at line 226 of file stringlist.c.
 {
   register int i;
   if (sl == 0)
     return;
   for (i = 0; i < sl->list_len; i++)
     printf ("%s%s\n", prefix ? prefix : "", sl->list[i]);
 }
References i, _list_of_strings::list, _list_of_strings::list_len, prefix(), and printf().
strlist_remove()
int strlist_remove (STRINGLIST * sl, char * s)
Definition at line 105 of file stringlist.c.
 {
   int r;
   if (sl == 0 || sl->list == 0 || sl->list_len == 0)
     return 0;
   r = strvec_remove (sl->list, s);
   if (r)
     sl->list_len--;
   return r;
 }
References _list_of_strings::list, _list_of_strings::list_len, s, and strvec_remove().
strlist_resize()
STRINGLIST* strlist_resize (STRINGLIST * sl, int n)
Definition at line 64 of file stringlist.c.
 {
   register int i;
   if (sl == 0)
     return (sl = strlist_create (n));
   if (n > sl->list_size)
     {
       sl->list = strvec_resize (sl->list, n + 1);
       for (i = sl->list_size; i <= n; i++)
     sl->list[i] = (char *)NULL;
       sl->list_size = n;
     }
   return sl;
 }
References i, _list_of_strings::list, _list_of_strings::list_size, n, NULL, strlist_create(), and strvec_resize().
Referenced by strlist_append().
strlist_sort()
void strlist_sort (STRINGLIST * sl)
Definition at line 253 of file stringlist.c.
 {
   if (sl == 0 || sl->list_len == 0 || sl->list == 0)
     return;
   strvec_sort (sl->list, 0);
 }
References _list_of_strings::list, _list_of_strings::list_len, and strvec_sort().
strlist_to_word_list()
WORD_LIST* strlist_to_word_list (STRINGLIST * sl, int alloc, int starting_index)
Definition at line 286 of file stringlist.c.
 {
   WORD_LIST *list;
   if (sl == 0 || sl->list == 0)
     return ((WORD_LIST *)NULL);
   list = strvec_to_word_list (sl->list, alloc, starting_index);
   return list;
 }
References _list_of_strings::list, list(), NULL, and strvec_to_word_list().
strlist_walk()
void strlist_walk (STRINGLIST * sl, sh_strlist_map_func_t * func)
Definition at line 239 of file stringlist.c.
 {
   register int i;
   if (sl == 0)
     return;
   for (i = 0; i < sl->list_len; i++)
     if ((*func)(sl->list[i]) < 0)
       break;
 }
References i, _list_of_strings::list, and _list_of_strings::list_len.