Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/i_video.c File Reference
i_video.c File Reference
#include "config.h"
#include "v_video.h"
#include "m_argv.h"
#include "d_event.h"
#include "d_main.h"
#include "i_video.h"
#include "z_zone.h"
#include "tables.h"
#include "doomkeys.h"
#include "doomgeneric.h"
#include <stdbool.h>
#include <stdlib.h>
#include <fcntl.h>
#include <stdarg.h>
#include <sys/types.h>
Data Structures
struct FB_BitField
struct FB_ScreenInfo
struct color
struct col_t
Macros
#define GFX_RGB565(r, g, b) ((((r & 0xF8) >> 3) << 11) | (((g & 0xFC) >> 2) << 5) | ((b & 0xF8) >> 3))
#define GFX_RGB565_R(color) ((0xF800 & color) >> 11)
#define GFX_RGB565_G(color) ((0x07E0 & color) >> 5)
#define GFX_RGB565_B(color) (0x001F & color)
Functions
void I_GetEvent (void)
void cmap_to_rgb565 (uint16_t *out, uint8_t *in, int in_pixels)
void cmap_to_fb (uint8_t *out, uint8_t *in, int in_pixels)
void I_InitGraphics (void)
void I_ShutdownGraphics (void)
void I_StartFrame (void)
void I_StartTic (void)
void I_UpdateNoBlit (void)
void I_FinishUpdate (void)
void I_ReadScreen (byte *scr)
void I_SetPalette (byte *palette)
int I_GetPaletteIndex (int r, int g, int b)
void I_BeginRead (void)
void I_EndRead (void)
void I_SetWindowTitle (char *title)
void I_GraphicsCheckCommandLine (void)
void I_SetGrabMouseCallback (grabmouse_callback_t func)
void I_EnableLoadingDisk (void)
void I_BindVideoVariables (void)
void I_DisplayFPSDots (boolean dots_on)
void I_CheckIsScreensaver (void)
Variables
static const char rcsid [] = "$Id: i_x.c,v 1.6 1997/02/03 22:45:10 b1 Exp $"
static struct FB_ScreenInfo s_Fb
int fb_scaling = 1
int usemouse = 0
static struct color colors [256]
byte * I_VideoBuffer = NULL
boolean screensaver_mode = false
boolean screenvisible
float mouse_acceleration = 2.0
int mouse_threshold = 10
int usegamma = 0
static uint16_t rgb565_palette [256]
Data Structure Documentation
FB_BitField
struct FB_BitField
Definition at line 52 of file i_video.c.
Data Fields
uint32_t length
uint32_t offset
FB_ScreenInfo
struct FB_ScreenInfo
Definition at line 58 of file i_video.c.
Data Fields
uint32_t bits_per_pixel
struct FB_BitField blue
struct FB_BitField green
struct FB_BitField red
struct FB_BitField transp
uint32_t xres
uint32_t xres_virtual
uint32_t yres
uint32_t yres_virtual
color
struct color
Definition at line 78 of file i_video.c.
Data Fields
uint32_t a:8
uint32_t b:8
uint32_t g:8
uint32_t r:8
col_t
struct col_t
Definition at line 118 of file i_video.c.
Data Fields
byte b
byte g
byte r
Macro Definition Documentation
GFX_RGB565
#define GFX_RGB565 (r, g, b) ((((r & 0xF8) >> 3) << 11) | (((g & 0xFC) >> 2) << 5) | ((b & 0xF8) >> 3))
Definition at line 308 of file i_video.c.
GFX_RGB565_B
#define GFX_RGB565_B (color) (0x001F & color)
Definition at line 311 of file i_video.c.
GFX_RGB565_G
#define GFX_RGB565_G (color) ((0x07E0 & color) >> 5)
Definition at line 310 of file i_video.c.
GFX_RGB565_R
#define GFX_RGB565_R (color) ((0xF800 & color) >> 11)
Definition at line 309 of file i_video.c.
Function Documentation
cmap_to_fb()
void cmap_to_fb (uint8_t * out, uint8_t * in, int in_pixels)
Definition at line 150 of file i_video.c.
 {
     int i, j, k;
     struct color c;
     uint32_t pix;
     uint16_t r, g, b;
     for (i = 0; i < in_pixels; i++)
     {
         c = colors[*in];  /* R:8 G:8 B:8 format! */
         r = (uint16_t)(c.r >> (8 - s_Fb.red.length));
         g = (uint16_t)(c.g >> (8 - s_Fb.green.length));
         b = (uint16_t)(c.b >> (8 - s_Fb.blue.length));
         pix = r << s_Fb.red.offset;
         pix |= g << s_Fb.green.offset;
         pix |= b << s_Fb.blue.offset;
         for (k = 0; k < fb_scaling; k++) {
             for (j = 0; j < s_Fb.bits_per_pixel/8; j++) {
                 *out = (pix >> (j*8));
                 out++;
             }
         }
         in++;
     }
 }
References b, FB_ScreenInfo::bits_per_pixel, FB_ScreenInfo::blue, c, colors, fb_scaling, g, FB_ScreenInfo::green, i, j, k, FB_BitField::length, FB_BitField::offset, out(), r, FB_ScreenInfo::red, and s_Fb.
Referenced by I_FinishUpdate().
cmap_to_rgb565()
void cmap_to_rgb565 (uint16_t * out, uint8_t * in, int in_pixels)
Definition at line 129 of file i_video.c.
 {
     int i, j;
     struct color c;
     uint16_t r, g, b;
     for (i = 0; i < in_pixels; i++)
     {
         c = colors[*in];
         r = ((uint16_t)(c.r >> 3)) << 11;
         g = ((uint16_t)(c.g >> 2)) << 5;
         b = ((uint16_t)(c.b >> 3)) << 0;
         *out = (r | g | b);
         in++;
         for (j = 0; j < fb_scaling; j++) {
             out++;
         }
     }
 }
References b, c, colors, fb_scaling, g, i, j, out(), and r.
I_BeginRead()
void I_BeginRead (void)
Definition at line 379 of file i_video.c.
 {
 }
Referenced by W_ReadLump().
I_BindVideoVariables()
void I_BindVideoVariables (void)
Definition at line 404 of file i_video.c.
 {
 }
Referenced by D_BindVariables().
I_CheckIsScreensaver()
void I_CheckIsScreensaver (void)
Definition at line 412 of file i_video.c.
 {
 }
Referenced by D_DoomMain().
I_DisplayFPSDots()
void I_DisplayFPSDots (boolean dots_on)
Definition at line 408 of file i_video.c.
 {
 }
Referenced by D_DoomMain().
I_EnableLoadingDisk()
void I_EnableLoadingDisk (void)
Definition at line 400 of file i_video.c.
 {
 }
Referenced by D_DoomLoop().
I_EndRead()
void I_EndRead (void)
Definition at line 383 of file i_video.c.
 {
 }
Referenced by W_ReadLump().
I_FinishUpdate()
void I_FinishUpdate (void)
Definition at line 253 of file i_video.c.
 {
     int y;
     int x_offset, y_offset, x_offset_end;
     unsigned char *line_in, *line_out;
     /* Offsets in case FB is bigger than DOOM */
     /* 600 = s_Fb heigt, 200 screenheight */
     /* 600 = s_Fb heigt, 200 screenheight */
     /* 2048 =s_Fb width, 320 screenwidth */
     y_offset     = (((s_Fb.yres - (SCREENHEIGHT * fb_scaling)) * s_Fb.bits_per_pixel/8)) / 2;
     x_offset     = (((s_Fb.xres - (SCREENWIDTH  * fb_scaling)) * s_Fb.bits_per_pixel/8)) / 2; // XXX: siglent FB hack: /4 instead of /2, since it seems to handle the resolution in a funny way
     //x_offset     = 0;
     x_offset_end = ((s_Fb.xres - (SCREENWIDTH  * fb_scaling)) * s_Fb.bits_per_pixel/8) - x_offset;
     /* DRAW SCREEN */
     line_in  = (unsigned char *) I_VideoBuffer;
     line_out = (unsigned char *) DG_ScreenBuffer;
     y = SCREENHEIGHT;
     while (y--)
     {
         int i;
         for (i = 0; i < fb_scaling; i++) {
             line_out += x_offset;
 #ifdef CMAP256
             for (fb_scaling == 1) {
                 memcpy(line_out, line_in, SCREENWIDTH); /* fb_width is bigger than Doom SCREENWIDTH... */
             } else {
                 //XXX FIXME fb_scaling support!
             }
 #else
             //cmap_to_rgb565((void*)line_out, (void*)line_in, SCREENWIDTH);
             cmap_to_fb((void*)line_out, (void*)line_in, SCREENWIDTH);
 #endif
             line_out += (SCREENWIDTH * fb_scaling * (s_Fb.bits_per_pixel/8)) + x_offset_end;
         }
         line_in += SCREENWIDTH;
     }
     DG_DrawFrame();
 }
References FB_ScreenInfo::bits_per_pixel, cmap_to_fb(), DG_DrawFrame(), DG_ScreenBuffer, fb_scaling, i, I_VideoBuffer, memcpy, s_Fb, SCREENHEIGHT, SCREENWIDTH, FB_ScreenInfo::xres, y, and FB_ScreenInfo::yres.
Referenced by D_Display().
I_GetEvent()
void I_GetEvent (void)
Definition at line 279 of file i_input.c.
 {
     event_t event;
     int pressed;
     unsigned char key;
     while (DG_GetKey(&pressed, &key))
     {
         UpdateShiftStatus(pressed, key);
         // process event
         if (pressed)
         {
             // data1 has the key pressed, data2 has the character
             // (shift-translated, etc)
             event.type = ev_keydown;
             event.data1 = TranslateKey(key);
             event.data2 = GetTypedChar(key);
             if (event.data1 != 0)
             {
                 D_PostEvent(&event);
             }
         }
         else
         {
             event.type = ev_keyup;
             event.data1 = TranslateKey(key);
             // data2 is just initialized to zero for ev_keyup.
             // For ev_keydown it's the shifted Unicode character
             // that was typed, but if something wants to detect
             // key releases it should do so based on data1
             // (key ID), not the printable char.
             event.data2 = 0;
             if (event.data1 != 0)
             {
                 D_PostEvent(&event);
             }
             break;
         }
     }
                 /*
             case SDL_MOUSEMOTION:
                 event.type = ev_mouse;
                 event.data1 = mouse_button_state;
                 event.data2 = AccelerateMouse(sdlevent.motion.xrel);
                 event.data3 = -AccelerateMouse(sdlevent.motion.yrel);
                 D_PostEvent(&event);
                 break;
                 */
 }
References D_PostEvent(), event_t::data1, DG_GetKey(), ev_keydown, ev_keyup, GetTypedChar(), TranslateKey(), and UpdateShiftStatus().
Referenced by I_StartTic().
I_GetPaletteIndex()
int I_GetPaletteIndex (int r, int g, int b)
Definition at line 343 of file i_video.c.
 {
     int best, best_diff, diff;
     int i;
     col_t color;
     printf("I_GetPaletteIndex\n");
     best = 0;
     best_diff = __INT_MAX__;
     for (i = 0; i < 256; ++i)
     {
         color.r = GFX_RGB565_R(rgb565_palette[i]);
         color.g = GFX_RGB565_G(rgb565_palette[i]);
         color.b = GFX_RGB565_B(rgb565_palette[i]);
         diff = (r - color.r) * (r - color.r)
              + (g - color.g) * (g - color.g)
              + (b - color.b) * (b - color.b);
         if (diff < best_diff)
         {
             best = i;
             best_diff = diff;
         }
         if (diff == 0)
         {
             break;
         }
     }
     return best;
 }
References color::b, b, g, color::g, GFX_RGB565_B, GFX_RGB565_G, GFX_RGB565_R, i, printf, color::r, r, and rgb565_palette.
Referenced by V_DrawMouseSpeedBox().
I_GraphicsCheckCommandLine()
void I_GraphicsCheckCommandLine (void)
Definition at line 392 of file i_video.c.
 {
 }
Referenced by D_DoomLoop().
I_InitGraphics()
void I_InitGraphics (void)
Definition at line 177 of file i_video.c.
 {
     int i;
     memset(&s_Fb, 0, sizeof(struct FB_ScreenInfo));
     s_Fb.xres = DOOMGENERIC_RESX;
     s_Fb.yres = DOOMGENERIC_RESY;
     s_Fb.xres_virtual = s_Fb.xres;
     s_Fb.yres_virtual = s_Fb.yres;
     s_Fb.bits_per_pixel = 32;
     s_Fb.blue.length = 8;
     s_Fb.green.length = 8;
     s_Fb.red.length = 8;
     s_Fb.transp.length = 8;
     s_Fb.blue.offset = 0;
     s_Fb.green.offset = 8;
     s_Fb.red.offset = 16;
     s_Fb.transp.offset = 24;
     printf("I_InitGraphics: framebuffer: x_res: %d, y_res: %d, x_virtual: %d, y_virtual: %d, bpp: %d\n",
             s_Fb.xres, s_Fb.yres, s_Fb.xres_virtual, s_Fb.yres_virtual, s_Fb.bits_per_pixel);
     printf("I_InitGraphics: framebuffer: RGBA: %d%d%d%d, red_off: %d, green_off: %d, blue_off: %d, transp_off: %d\n",
             s_Fb.red.length, s_Fb.green.length, s_Fb.blue.length, s_Fb.transp.length, s_Fb.red.offset, s_Fb.green.offset, s_Fb.blue.offset, s_Fb.transp.offset);
     printf("I_InitGraphics: DOOM screen size: w x h: %d x %d\n", SCREENWIDTH, SCREENHEIGHT);
     i = M_CheckParmWithArgs("-scaling", 1);
     if (i > 0) {
         i = atoi(myargv[i + 1]);
         fb_scaling = i;
         printf("I_InitGraphics: Scaling factor: %d\n", fb_scaling);
     } else {
         fb_scaling = s_Fb.xres / SCREENWIDTH;
         if (s_Fb.yres / SCREENHEIGHT < fb_scaling)
             fb_scaling = s_Fb.yres / SCREENHEIGHT;
         printf("I_InitGraphics: Auto-scaling factor: %d\n", fb_scaling);
     }
     /* Allocate screen to draw to */
     I_VideoBuffer = (byte*)Z_Malloc (SCREENWIDTH * SCREENHEIGHT, PU_STATIC, NULL);  // For DOOM to draw on
     screenvisible = true;
     extern int I_InitInput(void);
     I_InitInput();
 }
References atoi(), FB_ScreenInfo::bits_per_pixel, FB_ScreenInfo::blue, DOOMGENERIC_RESX, DOOMGENERIC_RESY, fb_scaling, FB_ScreenInfo::green, i, I_InitInput(), I_VideoBuffer, FB_BitField::length, M_CheckParmWithArgs(), memset, myargv, NULL, FB_BitField::offset, printf, PU_STATIC, FB_ScreenInfo::red, s_Fb, SCREENHEIGHT, screenvisible, SCREENWIDTH, FB_ScreenInfo::transp, FB_ScreenInfo::xres, FB_ScreenInfo::xres_virtual, FB_ScreenInfo::yres, FB_ScreenInfo::yres_virtual, and Z_Malloc().
Referenced by D_DoomLoop().
I_ReadScreen()
void I_ReadScreen (byte * scr)
Definition at line 300 of file i_video.c.
 {
     memcpy (scr, I_VideoBuffer, SCREENWIDTH * SCREENHEIGHT);
 }
References I_VideoBuffer, memcpy, SCREENHEIGHT, and SCREENWIDTH.
Referenced by wipe_EndScreen(), and wipe_StartScreen().
I_SetGrabMouseCallback()
void I_SetGrabMouseCallback (grabmouse_callback_t func)
Definition at line 396 of file i_video.c.
 {
 }
Referenced by D_DoomLoop().
I_SetPalette()
void I_SetPalette (byte * palette)
Definition at line 313 of file i_video.c.
 {
     int i;
     //col_t* c;
     //for (i = 0; i < 256; i++)
     //{
     //  c = (col_t*)palette;
     //  rgb565_palette[i] = GFX_RGB565(gammatable[usegamma][c->r],
     //                                 gammatable[usegamma][c->g],
     //                                 gammatable[usegamma][c->b]);
     //  palette += 3;
     //}
     /* performance boost:
      * map to the right pixel format over here! */
     for (i=0; i<256; ++i ) {
         colors[i].a = 0;
         colors[i].r = gammatable[usegamma][*palette++];
         colors[i].g = gammatable[usegamma][*palette++];
         colors[i].b = gammatable[usegamma][*palette++];
     }
 }
References color::a, color::b, colors, color::g, gammatable, i, color::r, and usegamma.
Referenced by D_Display(), M_Responder(), ST_doPaletteStuff(), and ST_Stop().
I_SetWindowTitle()
void I_SetWindowTitle (char * title)
Definition at line 387 of file i_video.c.
 {
     DG_SetWindowTitle(title);
 }
References DG_SetWindowTitle(), and title.
Referenced by D_DoomLoop().
I_ShutdownGraphics()
void I_ShutdownGraphics (void)
Definition at line 230 of file i_video.c.
 {
     Z_Free (I_VideoBuffer);
 }
References I_VideoBuffer, and Z_Free().
I_StartFrame()
void I_StartFrame (void)
Definition at line 235 of file i_video.c.
 {
 }
Referenced by doomgeneric_Tick().
I_StartTic()
void I_StartTic (void)
Definition at line 240 of file i_video.c.
 {
     I_GetEvent();
 }
References I_GetEvent().
Referenced by BuildNewTic().
I_UpdateNoBlit()
void I_UpdateNoBlit (void)
Definition at line 245 of file i_video.c.
 {
 }
Referenced by D_Display().
Variable Documentation
colors
struct color colors[256] static
Definition at line 76 of file i_video.c.
Referenced by AM_drawThings(), cmap_to_fb(), cmap_to_rgb565(), and I_SetPalette().
fb_scaling
int fb_scaling = 1
Definition at line 75 of file i_video.c.
Referenced by cmap_to_fb(), cmap_to_rgb565(), I_FinishUpdate(), and I_InitGraphics().
I_VideoBuffer
byte* I_VideoBuffer = NULL
Definition at line 91 of file i_video.c.
Referenced by AM_initVariables(), F_DrawPatchCol(), F_TextWrite(), I_FinishUpdate(), I_InitGraphics(), I_ReadScreen(), I_ShutdownGraphics(), R_InitBuffer(), R_VideoErase(), V_DrawFilledBox(), V_DrawHorizLine(), V_DrawVertLine(), V_MarkRect(), V_RestoreBuffer(), V_ScreenShot(), and wipe_ScreenWipe().
mouse_acceleration
float mouse_acceleration = 2.0
Definition at line 111 of file i_video.c.
Referenced by V_DrawMouseSpeedBox().
mouse_threshold
int mouse_threshold = 10
Definition at line 112 of file i_video.c.
Referenced by V_DrawMouseSpeedBox().
rcsid
const char rcsid[] = "$Id: i_x.c,v 1.6 1997/02/03 22:45:10 b1 Exp $" static
Definition at line 26 of file i_video.c.
rgb565_palette
uint16_t rgb565_palette[256] static
Definition at line 127 of file i_video.c.
Referenced by I_GetPaletteIndex().
s_Fb
struct FB_ScreenInfo s_Fb static
Definition at line 26 of file i_video.c.
Referenced by cmap_to_fb(), I_FinishUpdate(), and I_InitGraphics().
screensaver_mode
boolean screensaver_mode = false
Definition at line 95 of file i_video.c.
Referenced by D_Endoom(), and I_InitSound().
screenvisible
boolean screenvisible
Definition at line 100 of file i_video.c.
Referenced by doomgeneric_Tick(), and I_InitGraphics().
usegamma
int usegamma = 0
Definition at line 116 of file i_video.c.
Referenced by I_SetPalette(), and M_Responder().
usemouse
int usemouse = 0
Definition at line 76 of file i_video.c.
Referenced by V_DrawMouseSpeedBox().