Fennix: Userspace/musl/src/passwd/nscd.h File Reference
nscd.h File Reference
#include <stdint.h>
Macros
#define NSCDVERSION 2
#define GETPWBYNAME 0
#define GETPWBYUID 1
#define GETGRBYNAME 2
#define GETGRBYGID 3
#define GETINITGR 15
#define REQVERSION 0
#define REQTYPE 1
#define REQKEYLEN 2
#define REQ_LEN 3
#define PWVERSION 0
#define PWFOUND 1
#define PWNAMELEN 2
#define PWPASSWDLEN 3
#define PWUID 4
#define PWGID 5
#define PWGECOSLEN 6
#define PWDIRLEN 7
#define PWSHELLLEN 8
#define PW_LEN 9
#define GRVERSION 0
#define GRFOUND 1
#define GRNAMELEN 2
#define GRPASSWDLEN 3
#define GRGID 4
#define GRMEMCNT 5
#define GR_LEN 6
#define INITGRVERSION 0
#define INITGRFOUND 1
#define INITGRNGRPS 2
#define INITGR_LEN 3
Functions
hidden FILE * __nscd_query (int32_t req, const char *key, int32_t *buf, size_t len, int *swap)
Macro Definition Documentation
GETGRBYGID
#define GETGRBYGID 3
Definition at line 10 of file nscd.h.
GETGRBYNAME
#define GETGRBYNAME 2
Definition at line 9 of file nscd.h.
GETINITGR
#define GETINITGR 15
Definition at line 11 of file nscd.h.
GETPWBYNAME
#define GETPWBYNAME 0
Definition at line 7 of file nscd.h.
GETPWBYUID
#define GETPWBYUID 1
Definition at line 8 of file nscd.h.
GR_LEN
#define GR_LEN 6
Definition at line 35 of file nscd.h.
GRFOUND
#define GRFOUND 1
Definition at line 30 of file nscd.h.
GRGID
#define GRGID 4
Definition at line 33 of file nscd.h.
GRMEMCNT
#define GRMEMCNT 5
Definition at line 34 of file nscd.h.
GRNAMELEN
#define GRNAMELEN 2
Definition at line 31 of file nscd.h.
GRPASSWDLEN
#define GRPASSWDLEN 3
Definition at line 32 of file nscd.h.
GRVERSION
#define GRVERSION 0
Definition at line 29 of file nscd.h.
INITGR_LEN
#define INITGR_LEN 3
Definition at line 40 of file nscd.h.
INITGRFOUND
#define INITGRFOUND 1
Definition at line 38 of file nscd.h.
INITGRNGRPS
#define INITGRNGRPS 2
Definition at line 39 of file nscd.h.
INITGRVERSION
#define INITGRVERSION 0
Definition at line 37 of file nscd.h.
NSCDVERSION
#define NSCDVERSION 2
Definition at line 6 of file nscd.h.
PW_LEN
#define PW_LEN 9
Definition at line 27 of file nscd.h.
PWDIRLEN
#define PWDIRLEN 7
Definition at line 25 of file nscd.h.
PWFOUND
#define PWFOUND 1
Definition at line 19 of file nscd.h.
PWGECOSLEN
#define PWGECOSLEN 6
Definition at line 24 of file nscd.h.
PWGID
#define PWGID 5
Definition at line 23 of file nscd.h.
PWNAMELEN
#define PWNAMELEN 2
Definition at line 20 of file nscd.h.
PWPASSWDLEN
#define PWPASSWDLEN 3
Definition at line 21 of file nscd.h.
PWSHELLLEN
#define PWSHELLLEN 8
Definition at line 26 of file nscd.h.
PWUID
#define PWUID 4
Definition at line 22 of file nscd.h.
PWVERSION
#define PWVERSION 0
Definition at line 18 of file nscd.h.
REQ_LEN
#define REQ_LEN 3
Definition at line 16 of file nscd.h.
REQKEYLEN
#define REQKEYLEN 2
Definition at line 15 of file nscd.h.
REQTYPE
#define REQTYPE 1
Definition at line 14 of file nscd.h.
REQVERSION
#define REQVERSION 0
Definition at line 13 of file nscd.h.
Function Documentation
__nscd_query()
hidden FILE* __nscd_query (int32_t req, const char * key, int32_t * buf, size_t len, int * swap)
Definition at line 18 of file nscd_query.c.
 {
     size_t i;
     int fd;
     FILE *f = 0;
     int32_t req_buf[REQ_LEN] = {
         NSCDVERSION,
         req,
         strnlen(key,LOGIN_NAME_MAX)+1
     };
     struct msghdr msg = {
         .msg_iov = (struct iovec[]){
             {&req_buf, sizeof(req_buf)},
             {(char*)key, strlen(key)+1}
         },
         .msg_iovlen = 2
     };
     int errno_save = errno;
     *swap = 0;
 retry:
     memset(buf, 0, len);
     buf[0] = NSCDVERSION;
     fd = socket(PF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
     if (fd < 0) {
         if (errno == EAFNOSUPPORT) {
             f = fopen("/dev/null", "re");
             if (f)
                 errno = errno_save;
             return f;
         }
         return 0;
     }
     if(!(f = fdopen(fd, "r"))) {
         close(fd);
         return 0;
     }
     if (req_buf[2] > LOGIN_NAME_MAX)
         return f;
     if (connect(fd, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
         /* If there isn't a running nscd we simulate a "not found"
          * result and the caller is responsible for calling
          * fclose on the (unconnected) socket. The value of
          * errno must be left unchanged in this case.  */
         if (errno == EACCES || errno == ECONNREFUSED || errno == ENOENT) {
             errno = errno_save;
             return f;
         }
         goto error;
     }
     if (sendmsg(fd, &msg, MSG_NOSIGNAL) < 0)
         goto error;
     if (!fread(buf, len, 1, f)) {
         /* If the VERSION entry mismatches nscd will disconnect. The
          * most likely cause is that the endianness mismatched. So, we
          * byteswap and try once more. (if we already swapped, just
          * fail out)
          */
         if (ferror(f)) goto error;
         if (!*swap) {
             fclose(f);
             for (i = 0; i < sizeof(req_buf)/sizeof(req_buf[0]); i++) {
                 req_buf[i] = bswap_32(req_buf[i]);
             }
             *swap = 1;
             goto retry;
         } else {
             errno = EIO;
             goto error;
         }
     }
     if (*swap) {
         for (i = 0; i < len/sizeof(buf[0]); i++) {
             buf[i] = bswap_32(buf[i]);
         }
     }
     /* The first entry in every nscd response is the version number. This
      * really shouldn't happen, and is evidence of some form of malformed
      * response.
      */
     if(buf[0] != NSCDVERSION) {
         errno = EIO;
         goto error;
     }
     return f;
 error:
     fclose(f);
     return 0;
 }
References addr, bswap_32, buf, close(), connect(), EACCES, EAFNOSUPPORT, ECONNREFUSED, EIO, ENOENT, errno, error, f, fclose(), fd, ferror, fopen(), fread(), i, len, LOGIN_NAME_MAX, memset, msghdr::msg_iov, MSG_NOSIGNAL, NSCDVERSION, PF_UNIX, REQ_LEN, sendmsg(), SOCK_CLOEXEC, SOCK_STREAM, socket(), strlen(), strnlen(), and swap().
Referenced by __getgr_a(), __getpw_a(), and getgrouplist().