Fennix: Userspace/mlibc/options/ansi/generic/complex/cpowf.c File Reference
cpowf.c File Reference
#include <complex.h>
#include <math.h>
Functions
float complex cpowf (float complex a, float complex z)
Function Documentation
cpowf()
float complex cpowf (float complex a, float complex z)
Definition at line 39 of file cpowf.c.
 {
     float complex w;
     float x, y, r, theta, absa, arga;
     x = crealf(z);
     y = cimagf(z);
     absa = cabsf(a);
     if (absa == 0.0f) {
         return (0.0f + 0.0f * I);
     }
     arga = cargf(a);
     r = powf(absa, x);
     theta = x * arga;
     if (y != 0.0f) {
         r = r * expf(-y * arga);
         theta = theta + y * logf(absa);
     }
     w = r * cosf(theta) + (r * sinf(theta)) * I;
     return w;
 }
References cabsf(), cargf(), cimagf(), complex, cosf(), crealf(), expf(), I(), logf(), powf(), r, sinf(), x, and y.