Fennix Kernel: InterProcessCommunication::IPC Class Reference
InterProcessCommunication::IPC Class Reference
#include <ipc.hpp>
Public Member Functions
std::vector< IPCHandle * > GetHandles ()
void Fork (IPC *Parent)
IPCHandle * Create (IPCType Type, char UniqueToken[16])
IPCErrorCode Destroy (IPCID ID)
IPCErrorCode Allocate (IPCID ID, long Size)
IPCErrorCode Deallocate (IPCID ID)
IPCErrorCode Read (IPCID ID, void *Buffer, long Size)
IPCErrorCode Write (IPCID ID, void *Buffer, long Size)
IPCErrorCode Listen (IPCID ID, bool Listen)
IPCErrorCode Wait (IPCID ID)
IPCHandle * SearchByToken (char UniqueToken[16])
int HandleSyscall (long Command, long Type, int ID, int Flags, void *Buffer, size_t Size)
IPC (void *Process)
~IPC ()
Private Member Functions
NewLock (IPCLock)
Private Attributes
IPCID NextID = 0
std::vector< IPCHandle * > Handles
Memory::VirtualMemoryArea * vma
vfs::Node * IPCNode
void * Process
Detailed Description
Definition at line 65 of file ipc.hpp.
Constructor & Destructor Documentation
IPC()
InterProcessCommunication::IPC::IPC (void * Process)
Definition at line 263 of file ipc.cpp.
     {
         Tasking::PCB *pcb = (Tasking::PCB *)Process;
         this->Process = Process;
         this->vma = new Memory::VirtualMemoryArea(pcb->PageTable);
         IPCNode = fs->Create("ipc", vfs::NodeType::DIRECTORY,
                               pcb->ProcessDirectory);
     }
References vfs::Virtual::Create(), vfs::DIRECTORY, fs, IPCNode, Tasking::PCB::PageTable, Process, Tasking::PCB::ProcessDirectory, and vma.
~IPC()
InterProcessCommunication::IPC::~IPC ()
Definition at line 272 of file ipc.cpp.
     {
         fs->Delete(IPCNode, true);
         delete this->vma, this->vma = nullptr;
     }
References vfs::Virtual::Delete(), fs, IPCNode, and vma.
Member Function Documentation
Allocate()
IPCErrorCode InterProcessCommunication::IPC::Allocate (IPCID ID, long Size)
Definition at line 77 of file ipc.cpp.
     {
         SmartLock(this->IPCLock);
         if (Size < 0)
             return IPCError;
         foreach (auto Hnd in Handles)
         {
             if (Hnd->ID == ID)
             {
                 if (Hnd->Buffer != nullptr || Hnd->Length != 0)
                     return IPCAlreadyAllocated;
                 Hnd->Buffer = (uint8_t *)vma->RequestPages(TO_PAGES(Size + 1));
                 Hnd->Length = Size;
                 return IPCSuccess;
             }
         }
         return IPCIDNotFound;
     }
References Handles, ID, InterProcessCommunication::IPCAlreadyAllocated, InterProcessCommunication::IPCError, InterProcessCommunication::IPCIDNotFound, InterProcessCommunication::IPCSuccess, Memory::VirtualMemoryArea::RequestPages(), Size, TO_PAGES, and vma.
Referenced by HandleSyscall().
Create()
IPCHandle * InterProcessCommunication::IPC::Create (IPCType Type, char UniqueToken[16])
Definition at line 41 of file ipc.cpp.
     {
         UNUSED(Type);
         SmartLock(this->IPCLock);
         IPCHandle *Hnd = (IPCHandle *)vma->RequestPages(TO_PAGES(sizeof(IPCHandle) + 1));
         Hnd->ID = NextID++;
         Hnd->Node = fs->Create(UniqueToken, vfs::NodeType::FILE, IPCNode);
         Hnd->Buffer = nullptr;
         Hnd->Length = 0;
         Hnd->Listening = false;
         Handles.push_back(Hnd);
         debug("Created IPC with ID %d", Hnd->ID);
         return Hnd;
     }
References InterProcessCommunication::IPCHandle::Buffer, vfs::Virtual::Create(), debug, fs, Handles, InterProcessCommunication::IPCHandle::ID, IPCNode, InterProcessCommunication::IPCHandle::Length, InterProcessCommunication::IPCHandle::Listening, NextID, InterProcessCommunication::IPCHandle::Node, Memory::VirtualMemoryArea::RequestPages(), TO_PAGES, Type, UNUSED, and vma.
Referenced by HandleSyscall().
Deallocate()
IPCErrorCode InterProcessCommunication::IPC::Deallocate (IPCID ID)
Definition at line 98 of file ipc.cpp.
     {
         SmartLock(this->IPCLock);
         foreach (auto Hnd in Handles)
         {
             if (Hnd->ID == ID)
             {
                 if (Hnd->Buffer == nullptr || Hnd->Length == 0)
                     return IPCNotAllocated;
                 vma->FreePages(Hnd->Buffer, TO_PAGES(Hnd->Length + 1));
                 Hnd->Buffer = nullptr;
                 Hnd->Length = 0;
                 return IPCSuccess;
             }
         }
         return IPCIDNotFound;
     }
References Memory::VirtualMemoryArea::FreePages(), Handles, ID, InterProcessCommunication::IPCIDNotFound, InterProcessCommunication::IPCNotAllocated, InterProcessCommunication::IPCSuccess, TO_PAGES, and vma.
Referenced by HandleSyscall().
Destroy()
IPCErrorCode InterProcessCommunication::IPC::Destroy (IPCID ID)
Definition at line 58 of file ipc.cpp.
     {
         SmartLock(this->IPCLock);
         forItr(itr, Handles)
         {
             if ((*itr)->ID == ID)
             {
                 fs->Delete((*itr)->Node);
                 vma->FreePages((*itr), TO_PAGES(sizeof(IPCHandle) + 1));
                 Handles.erase(itr);
                 debug("Destroyed IPC with ID %d", ID);
                 return IPCSuccess;
             }
         }
         debug("Failed to destroy IPC with ID %d", ID);
         return IPCIDNotFound;
     }
References debug, vfs::Virtual::Delete(), Memory::VirtualMemoryArea::FreePages(), fs, Handles, ID, InterProcessCommunication::IPCIDNotFound, InterProcessCommunication::IPCSuccess, TO_PAGES, and vma.
Referenced by HandleSyscall().
Fork()
void InterProcessCommunication::IPC::Fork (IPC * Parent)
Definition at line 27 of file ipc.cpp.
     {
         std::vector<IPCHandle *> ParentHandles = Parent->GetHandles();
         foreach (auto Hnd in ParentHandles)
         {
             debug("Forking IPC with ID %d", Hnd->ID);
             IPCHandle *NewHnd = (IPCHandle *)vma->RequestPages(TO_PAGES(sizeof(IPCHandle) + 1));
             memcpy(NewHnd, Hnd, sizeof(IPCHandle));
             NewHnd->Node = fs->Create(Hnd->Node->Name, vfs::NodeType::FILE, IPCNode);
             Handles.push_back(NewHnd);
         }
     }
References vfs::Virtual::Create(), debug, fs, GetHandles(), Handles, IPCNode, memcpy(), InterProcessCommunication::IPCHandle::Node, Memory::VirtualMemoryArea::RequestPages(), TO_PAGES, and vma.
Referenced by sys_fork().
GetHandles()
std::vector<IPCHandle *> InterProcessCommunication::IPC::GetHandles () inline
Definition at line 76 of file ipc.hpp.
 { return Handles; }
References Handles.
Referenced by Fork().
HandleSyscall()
int InterProcessCommunication::IPC::HandleSyscall (long Command, long Type, int ID, int Flags, void * Buffer, size_t Size)
Definition at line 229 of file ipc.cpp.
     {
         switch (Command)
         {
         case IPC_CREATE:
         {
             char UniqueToken[16];
             if (Buffer != nullptr)
                 strcpy(UniqueToken, (char *)Buffer);
             else
                 snprintf(UniqueToken, 16, "IPC_%d", ID);
             IPCHandle *Hnd = this->Create((IPCType)Type, UniqueToken);
             this->Allocate(Hnd->ID, Size ? Size : PAGE_SIZE);
             return Hnd->ID;
         }
         case IPC_READ:
             return this->Read(ID, Buffer, Size);
         case IPC_WRITE:
             return TaskManager->GetProcessByID(Flags)->IPC->Write(ID, Buffer, Size);
         case IPC_DELETE:
         {
             this->Deallocate(ID);
             return this->Destroy(ID);
         }
         case IPC_WAIT:
             return this->Wait(ID);
         case IPC_LISTEN:
             return this->Listen(ID, Flags);
         default:
             return IPCInvalidCommand;
         }
         return IPCError;
     }
References Allocate(), Create(), Deallocate(), Destroy(), Flags, Tasking::Task::GetProcessByID(), InterProcessCommunication::IPCHandle::ID, ID, Tasking::PCB::IPC, IPC_CREATE, IPC_DELETE, IPC_LISTEN, IPC_READ, IPC_WAIT, IPC_WRITE, InterProcessCommunication::IPCError, InterProcessCommunication::IPCInvalidCommand, Listen(), PAGE_SIZE, Read(), Size, snprintf(), strcpy, TaskManager, Type, Wait(), and Write().
Listen()
IPCErrorCode InterProcessCommunication::IPC::Listen (IPCID ID, bool Listen)
Definition at line 181 of file ipc.cpp.
     {
         foreach (auto Hnd in Handles)
         {
             if (Hnd->ID == ID)
             {
                 Hnd->Listening = Listen;
                 debug("IPC %d is now set to %s", ID, Listen ? "listening" : "ready");
                 return IPCSuccess;
             }
         }
         debug("IPC %d not found", ID);
         return IPCIDNotFound;
     }
References debug, Handles, ID, InterProcessCommunication::IPCIDNotFound, and InterProcessCommunication::IPCSuccess.
Referenced by HandleSyscall().
NewLock()
InterProcessCommunication::IPC::NewLock (IPCLock) private
Read()
IPCErrorCode InterProcessCommunication::IPC::Read (IPCID ID, void * Buffer, long Size)
Definition at line 117 of file ipc.cpp.
     {
         SmartLock(this->IPCLock);
         if (Size < 0)
             return IPCError;
         foreach (auto Hnd in Handles)
         {
             if (Hnd->ID == ID)
             {
                 if (Hnd->Listening)
                 {
                     debug("IPC %d is listening", ID);
                     return IPCNotListening;
                 }
                 if (Hnd->Length < Size)
                 {
                     debug("IPC %d is too small", ID);
                     return IPCError;
                 }
                 debug("IPC %d reading %d bytes", ID, Size);
                 memcpy(Buffer, Hnd->Buffer, Size);
                 debug("IPC read %d bytes", Size);
                 return IPCSuccess;
             }
         }
         debug("IPC %d not found", ID);
         return IPCIDNotFound;
     }
References debug, Handles, ID, InterProcessCommunication::IPCError, InterProcessCommunication::IPCIDNotFound, InterProcessCommunication::IPCNotListening, InterProcessCommunication::IPCSuccess, memcpy(), and Size.
Referenced by HandleSyscall().
SearchByToken()
IPCHandle * InterProcessCommunication::IPC::SearchByToken (char UniqueToken[16])
Definition at line 215 of file ipc.cpp.
     {
         foreach (auto Hnd in Handles)
         {
             if (strcmp(Hnd->Node->Name, UniqueToken) == 0)
             {
                 debug("Found IPC with token %s", UniqueToken);
                 return Hnd;
             }
         }
         debug("Failed to find IPC with token %s", UniqueToken);
         return nullptr;
     }
References debug, Handles, and strcmp().
Wait()
IPCErrorCode InterProcessCommunication::IPC::Wait (IPCID ID)
Definition at line 196 of file ipc.cpp.
     {
         foreach (auto Hnd in Handles)
         {
             if (Hnd->ID == ID)
             {
                 if (!CPU::Interrupts())
                     warn("Interrupts are disabled. This may cause a kernel hang.");
                 debug("Waiting for IPC %d (now %s)", ID, Hnd->Listening ? "listening" : "ready");
                 while (Hnd->Listening)
                     TaskManager->Yield();
                 debug("IPC %d is ready", ID);
                 return IPCSuccess;
             }
         }
         debug("IPC %d not found", ID);
         return IPCIDNotFound;
     }
References debug, Handles, ID, CPU::Interrupts(), InterProcessCommunication::IPCIDNotFound, InterProcessCommunication::IPCSuccess, TaskManager, warn, and Tasking::Task::Yield().
Referenced by HandleSyscall().
Write()
IPCErrorCode InterProcessCommunication::IPC::Write (IPCID ID, void * Buffer, long Size)
Definition at line 147 of file ipc.cpp.
     {
         SmartLock(this->IPCLock);
         if (Size < 0)
         {
             debug("IPC %d is too small", ID);
             return IPCError;
         }
         foreach (auto Hnd in Handles)
         {
             if (Hnd->ID == ID)
             {
                 if (!Hnd->Listening)
                 {
                     debug("IPC %d is NOT listening", ID);
                     return IPCNotListening;
                 }
                 if (Hnd->Length < Size)
                 {
                     debug("IPC %d is too small", ID);
                     return IPCError;
                 }
                 debug("IPC %d writing %d bytes", ID, Size);
                 memcpy(Hnd->Buffer, Buffer, Size);
                 Hnd->Listening = false;
                 debug("IPC %d wrote %d bytes and now is %s", ID, Size, Hnd->Listening ? "listening" : "ready");
                 return IPCSuccess;
             }
         }
         debug("IPC %d not found", ID);
         return IPCIDNotFound;
     }
References debug, Handles, ID, InterProcessCommunication::IPCError, InterProcessCommunication::IPCIDNotFound, InterProcessCommunication::IPCNotListening, InterProcessCommunication::IPCSuccess, memcpy(), and Size.
Referenced by HandleSyscall().
Field Documentation
Handles
std::vector<IPCHandle *> InterProcessCommunication::IPC::Handles private
Definition at line 70 of file ipc.hpp.
Referenced by Allocate(), Create(), Deallocate(), Destroy(), Fork(), GetHandles(), Listen(), Read(), SearchByToken(), Wait(), and Write().
IPCNode
vfs::Node* InterProcessCommunication::IPC::IPCNode private
Definition at line 72 of file ipc.hpp.
Referenced by Create(), Fork(), IPC(), and ~IPC().
NextID
IPCID InterProcessCommunication::IPC::NextID = 0 private
Definition at line 69 of file ipc.hpp.
Referenced by Create().
Process
void* InterProcessCommunication::IPC::Process private
Definition at line 73 of file ipc.hpp.
Referenced by IPC().
vma
Memory::VirtualMemoryArea* InterProcessCommunication::IPC::vma private
Definition at line 71 of file ipc.hpp.
Referenced by Allocate(), Create(), Deallocate(), Destroy(), Fork(), IPC(), and ~IPC().
The documentation for this class was generated from the following files:
Kernel/include/ipc.hpp
Kernel/tasking/ipc.cpp