Fennix: Userspace/apps/base/busybox/coreutils/nproc.c File Reference
nproc.c File Reference
#include <sched.h>
#include "libbb.h"
Functions
int nproc_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int nproc_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
nproc_main() [1/2]
int nproc_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 30 of file nproc.c.
 {
     unsigned long mask[1024];
     int count = 0;
 #if ENABLE_LONG_OPTS
     int ignore = 0;
     int opts = getopt32long(argv, "\xfe:+",
             "ignore\0" Required_argument "\xfe"
             "all\0"    No_argument       "\xff"
             , &ignore
     );
     if (opts & (1 << 1)) {
         DIR *cpusd = opendir("/sys/devices/system/cpu");
         if (cpusd) {
             struct dirent *de;
             while (NULL != (de = readdir(cpusd))) {
                 char *cpuid = strstr(de->d_name, "cpu");
                 if (cpuid && isdigit(cpuid[strlen(cpuid) - 1]))
                     count++;
             }
             IF_FEATURE_CLEAN_UP(closedir(cpusd);)
         }
     } else
 #endif
     if (sched_getaffinity(0, sizeof(mask), (void*)mask) == 0) {
         int i;
         for (i = 0; i < ARRAY_SIZE(mask); i++) {
             unsigned long m = mask[i];
             while (m) {
                 if (m & 1)
                     count++;
                 m >>= 1;
             }
         }
     }
     IF_LONG_OPTS(count -= ignore;)
     if (count <= 0)
         count = 1;
     printf("%u\n", count);
     return 0;
 }
References argv, ARRAY_SIZE, closedir(), count, x32::cpuid(), dirent::d_name, getopt32long, i, ignore(), isdigit, No_argument, NULL, opendir(), printf, readdir(), Required_argument, sched_getaffinity(), strlen(), and strstr().
nproc_main() [2/2]
int nproc_main (int argc, char ** argv)