Fennix: Userspace/mlibc/options/posix/include/regex.h File Reference
regex.h File Reference
#include <stddef.h>
Data Structures
struct re_pattern_buffer
struct regmatch_t
Macros
#define REG_EXTENDED 1
#define REG_ICASE 2
#define REG_NEWLINE 4
#define REG_NOSUB 8
#define REG_NOTBOL 1
#define REG_NOTEOL 2
#define REG_OK 0
#define REG_NOMATCH 1
#define REG_BADPAT 2
#define REG_ECOLLATE 3
#define REG_ECTYPE 4
#define REG_EESCAPE 5
#define REG_ESUBREG 6
#define REG_EBRACK 7
#define REG_EPAREN 8
#define REG_EBRACE 9
#define REG_BADBR 10
#define REG_ERANGE 11
#define REG_ESPACE 12
#define REG_BADRPT 13
#define REG_ENOSYS -1
Typedefs
typedef ptrdiff_t regoff_t
typedef struct re_pattern_buffer regex_t
Functions
int regcomp (regex_t *__restrict, const char *__restrict, int)
int regexec (const regex_t *__restrict, const char *__restrict, size_t, regmatch_t *__restrict, int)
size_t regerror (int, const regex_t *__restrict, char *__restrict, size_t)
void regfree (regex_t *)
Data Structure Documentation
re_pattern_buffer
struct re_pattern_buffer
Definition at line 12 of file regex.h.
Data Fields
size_t __nsub2
void * __opaque
void * __padding[4]
char __padding2
size_t re_nsub
regmatch_t
struct regmatch_t
Definition at line 19 of file regex.h.
Data Fields
regoff_t rm_eo
regoff_t rm_so
Macro Definition Documentation
REG_BADBR
#define REG_BADBR 10
Definition at line 45 of file regex.h.
REG_BADPAT
#define REG_BADPAT 2
Definition at line 37 of file regex.h.
REG_BADRPT
#define REG_BADRPT 13
Definition at line 48 of file regex.h.
REG_EBRACE
#define REG_EBRACE 9
Definition at line 44 of file regex.h.
REG_EBRACK
#define REG_EBRACK 7
Definition at line 42 of file regex.h.
REG_ECOLLATE
#define REG_ECOLLATE 3
Definition at line 38 of file regex.h.
REG_ECTYPE
#define REG_ECTYPE 4
Definition at line 39 of file regex.h.
REG_EESCAPE
#define REG_EESCAPE 5
Definition at line 40 of file regex.h.
REG_ENOSYS
#define REG_ENOSYS -1
Definition at line 51 of file regex.h.
REG_EPAREN
#define REG_EPAREN 8
Definition at line 43 of file regex.h.
REG_ERANGE
#define REG_ERANGE 11
Definition at line 46 of file regex.h.
REG_ESPACE
#define REG_ESPACE 12
Definition at line 47 of file regex.h.
REG_ESUBREG
#define REG_ESUBREG 6
Definition at line 41 of file regex.h.
REG_EXTENDED
#define REG_EXTENDED 1
Definition at line 25 of file regex.h.
REG_ICASE
#define REG_ICASE 2
Definition at line 26 of file regex.h.
REG_NEWLINE
#define REG_NEWLINE 4
Definition at line 27 of file regex.h.
REG_NOMATCH
#define REG_NOMATCH 1
Definition at line 36 of file regex.h.
REG_NOSUB
#define REG_NOSUB 8
Definition at line 28 of file regex.h.
REG_NOTBOL
#define REG_NOTBOL 1
Definition at line 31 of file regex.h.
REG_NOTEOL
#define REG_NOTEOL 2
Definition at line 32 of file regex.h.
REG_OK
#define REG_OK 0
Definition at line 35 of file regex.h.
Typedef Documentation
regex_t
typedef struct re_pattern_buffer regex_t
regoff_t
typedef ptrdiff_t regoff_t
Definition at line 10 of file regex.h.
Function Documentation
regcomp()
int regcomp (regex_t * __restrict, const char * __restrict, int)
Referenced by main().
regerror()
size_t regerror (int , const regex_t * __restrict, char * __restrict, size_t)
regexec()
int regexec (const regex_t * __restrict, const char * __restrict, size_t , regmatch_t * __restrict, int)
Referenced by main().
regfree()
void regfree (regex_t * preg)
Definition at line 2907 of file regcomp.c.
 {
   tre_tnfa_t *tnfa;
   unsigned int i;
   tre_tnfa_transition_t *trans;
   tnfa = (void *)preg->TRE_REGEX_T_FIELD;
   if (!tnfa)
     return;
   for (i = 0; i < tnfa->num_transitions; i++)
     if (tnfa->transitions[i].state)
       {
     if (tnfa->transitions[i].tags)
       xfree(tnfa->transitions[i].tags);
     if (tnfa->transitions[i].neg_classes)
       xfree(tnfa->transitions[i].neg_classes);
       }
   if (tnfa->transitions)
     xfree(tnfa->transitions);
   if (tnfa->initial)
     {
       for (trans = tnfa->initial; trans->state; trans++)
     {
       if (trans->tags)
         xfree(trans->tags);
     }
       xfree(tnfa->initial);
     }
   if (tnfa->submatch_data)
     {
       for (i = 0; i < tnfa->num_submatches; i++)
     if (tnfa->submatch_data[i].parents)
       xfree(tnfa->submatch_data[i].parents);
       xfree(tnfa->submatch_data);
     }
   if (tnfa->tag_directions)
     xfree(tnfa->tag_directions);
   if (tnfa->firstpos_chars)
     xfree(tnfa->firstpos_chars);
   if (tnfa->minimal_tags)
     xfree(tnfa->minimal_tags);
   xfree(tnfa);
 }
References tnfa::firstpos_chars, i, if(), tnfa::initial, tnfa::minimal_tags, tnfa_transition::neg_classes, tnfa::num_submatches, tnfa::num_transitions, tre_submatch_data::parents, tnfa_transition::state, tnfa::submatch_data, tnfa::tag_directions, tnfa_transition::tags, tnfa::transitions, and xfree.
Referenced by main(), and regcomp().