Fennix: k_sigaction Struct Reference
k_sigaction Struct Reference
#include <signals.hpp>
Data Fields
void(* handler)(int)
unsigned long flags
void(* restorer)(void)
unsigned mask [2]
unsigned flags
unsigned long mask [4]
void * unused
void * restorer
Detailed Description
Definition at line 59 of file signals.hpp.
Field Documentation
flags [1/2]
unsigned long k_sigaction::flags
Definition at line 62 of file signals.hpp.
Referenced by __libc_sigaction(), KStatToStat(), and SetSigActToNative().
flags [2/2]
unsigned k_sigaction::flags
Definition at line 4 of file ksigaction.h.
handler
void(* k_sigaction::handler)(int)
Definition at line 61 of file signals.hpp.
Referenced by __libc_sigaction(), KStatToStat(), and SetSigActToNative().
mask [1/2]
unsigned k_sigaction::mask
Definition at line 64 of file signals.hpp.
Referenced by __libc_sigaction(), KStatToStat(), and SetSigActToNative().
mask [2/2]
unsigned long k_sigaction::mask[4]
Definition at line 6 of file ksigaction.h.
restorer [1/2]
void(* k_sigaction::restorer)(void) (void)
Definition at line 63 of file signals.hpp.
Referenced by __libc_sigaction(), KStatToStat(), and SetSigActToNative().
restorer [2/2]
void* k_sigaction::restorer (void)
Definition at line 6 of file ksigaction.h.
unused
void * k_sigaction::unused
Definition at line 7 of file ksigaction.h.
The documentation for this struct was generated from the following files:
Kernel/subsystem/linux/include/signals.hpp
Userspace/musl/arch/mips/ksigaction.h