Fennix: Userspace/musl/include/ulimit.h File Reference
ulimit.h File Reference
Macros
#define UL_GETFSIZE 1
#define UL_SETFSIZE 2
Functions
long ulimit (int,...)
Macro Definition Documentation
UL_GETFSIZE
#define UL_GETFSIZE 1
Definition at line 8 of file ulimit.h.
UL_SETFSIZE
#define UL_SETFSIZE 2
Definition at line 9 of file ulimit.h.
Function Documentation
ulimit()
long ulimit (int cmd, ...)
Definition at line 5 of file ulimit.c.
 {
     struct rlimit rl;
     getrlimit(RLIMIT_FSIZE, &rl);
     if (cmd == UL_SETFSIZE) {
         long val;
         va_list ap;
         va_start(ap, cmd);
         val = va_arg(ap, long);
         va_end(ap);
         rl.rlim_cur = 512ULL * val;
         if (setrlimit(RLIMIT_FSIZE, &rl)) return -1;
     }
     return rl.rlim_cur / 512;
 }
References ap, cmd, getrlimit(), rlimit::rlim_cur, RLIMIT_FSIZE, setrlimit(), UL_SETFSIZE, va_arg, va_end, va_start, and val.
Referenced by getdtablesize().