Fennix: Userspace/mlibc/options/posix/generic/spawn-stubs.cpp File Reference
spawn-stubs.cpp File Reference
#include <spawn.h>
#include <errno.h>
#include <pthread.h>
#include <fcntl.h>
#include <unistd.h>
#include <limits.h>
#include <sched.h>
#include <stdlib.h>
#include <signal.h>
#include <sys/wait.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
Data Structures
struct fdop
struct args
Macros
#define FDOP_CLOSE 1
#define FDOP_DUP2 2
#define FDOP_OPEN 3
#define FDOP_CHDIR 4
#define FDOP_FCHDIR 5
Functions
static void __get_handler_set (sigset_t *set)
static int child (void *args_vp)
int posix_spawn (pid_t *__restrict res, const char *__restrict path, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *__restrict attrs, char *const argv[], char *const envp[])
int posix_spawnattr_init (posix_spawnattr_t *attr)
int posix_spawnattr_destroy (posix_spawnattr_t *)
int posix_spawnattr_setflags (posix_spawnattr_t *attr, short flags)
int posix_spawnattr_setsigdefault (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigdefault)
int posix_spawnattr_setschedparam (posix_spawnattr_t *__restrict, const struct sched_param *__restrict)
int posix_spawnattr_setschedpolicy (posix_spawnattr_t *, int)
int posix_spawnattr_setsigmask (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigmask)
int posix_spawnattr_setpgroup (posix_spawnattr_t *attr, pid_t pgroup)
int posix_spawn_file_actions_init (posix_spawn_file_actions_t *file_actions)
int posix_spawn_file_actions_destroy (posix_spawn_file_actions_t *file_actions)
int posix_spawn_file_actions_adddup2 (posix_spawn_file_actions_t *file_actions, int fildes, int newfildes)
int posix_spawn_file_actions_addclose (posix_spawn_file_actions_t *file_actions, int fildes)
int posix_spawn_file_actions_addopen (posix_spawn_file_actions_t *__restrict file_actions, int fildes, const char *__restrict path, int oflag, mode_t mode)
int posix_spawnp (pid_t *__restrict pid, const char *__restrict file, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *__restrict attrp, char *const argv[], char *const envp[])
Variables
static unsigned long handler_set [NSIG/(8 *sizeof(long))]
Data Structure Documentation
fdop
struct fdop
Definition at line 28 of file spawn-stubs.cpp.
Data Fields
int cmd
int fd
mode_t mode
struct fdop * next
int oflag
char path[]
struct fdop * prev
int srcfd
args
struct args
Definition at line 45 of file spawn-stubs.cpp.
Data Fields
char *const * argv
const posix_spawnattr_t *__restrict attr
const posix_spawnattr_t *restrict attr
char *const *const * envp
int err
const posix_spawn_file_actions_t * fa
mqd_t mqd
sigset_t oldmask
int p[2]
const char * path
sem_t sem
const struct sigevent * sev
int sock
Macro Definition Documentation
FDOP_CHDIR
#define FDOP_CHDIR 4
Definition at line 25 of file spawn-stubs.cpp.
FDOP_CLOSE
#define FDOP_CLOSE 1
Definition at line 22 of file spawn-stubs.cpp.
FDOP_DUP2
#define FDOP_DUP2 2
Definition at line 23 of file spawn-stubs.cpp.
FDOP_FCHDIR
#define FDOP_FCHDIR 5
Definition at line 26 of file spawn-stubs.cpp.
FDOP_OPEN
#define FDOP_OPEN 3
Definition at line 24 of file spawn-stubs.cpp.
Function Documentation
__get_handler_set()
static void __get_handler_set (sigset_t * set) static
Definition at line 41 of file spawn-stubs.cpp.
{
     memcpy(set, handler_set, sizeof handler_set);
 }
References handler_set, and memcpy.
Referenced by child().
child()
static int child (void * args_vp) static
Definition at line 54 of file spawn-stubs.cpp.
{
     int i, ret;
     struct sigaction sa = {};
     struct args *args = (struct args *)args_vp;
     int p = args->p[1];
     const posix_spawn_file_actions_t *fa = args->fa;
     const posix_spawnattr_t *__restrict attr = args->attr;
     sigset_t hset;
     bool use_execvpe = false;
     if(attr->__fn)
         use_execvpe = true;
     close(args->p[0]);
     /* All signal dispositions must be either SIG_DFL or SIG_IGN
      * before signals are unblocked. Otherwise a signal handler
      * from the parent might get run in the child while sharing
      * memory, with unpredictable and dangerous results. To
      * reduce overhead, sigaction has tracked for us which signals
      * potentially have a signal handler. */
     __get_handler_set(&hset);
     for(i = 1; i < NSIG; i++) {
         if((attr->__flags & POSIX_SPAWN_SETSIGDEF) && sigismember(&attr->__def, i)) {
             sa.sa_handler = SIG_DFL;
         } else if(sigismember(&hset, i)) {
             if (i - 32 < 3) {
                 sa.sa_handler = SIG_IGN;
             } else {;
                 sigaction(i, 0, &sa);
                 if(sa.sa_handler == SIG_IGN)
                     continue;
                 sa.sa_handler = SIG_DFL;
             }
         } else {
             continue;
         }
         sigaction(i, &sa, 0);
     }
     if(attr->__flags & POSIX_SPAWN_SETSID) {
         if((ret = setsid()) < 0)
             goto fail;
     }
     if(attr->__flags & POSIX_SPAWN_SETPGROUP) {
         mlibc::infoLogger() << "mlibc: posix_spawn: ignoring SETPGROUP" << frg::endlog;
         //if((ret = setpgid(0, attr->__pgrp)))
         //  goto fail;
     }
     if(attr->__flags & POSIX_SPAWN_RESETIDS) {
         if((ret = setgid(getgid())) || (ret = setuid(getuid())) )
             goto fail;
     }
     if(fa && fa->__actions) {
         struct fdop *op;
         int fd;
         for(op = (struct fdop *)fa->__actions; op->next; op = op->next);
         for(; op; op = op->prev) {
             /* It's possible that a file operation would clobber
              * the pipe fd used for synchronizing with the
              * parent. To avoid that, we dup the pipe onto
              * an unoccupied fd. */
             if(op->fd == p) {
                 ret = dup(p);
                 if(ret < 0)
                     goto fail;
                 close(p);
                 p = ret;
             }
             switch(op->cmd) {
             case FDOP_CLOSE:
                 close(op->fd);
                 break;
             case FDOP_DUP2:
                 fd = op->srcfd;
                 if(fd == p) {
                     ret = -EBADF;
                     goto fail;
                 }
                 if(fd != op->fd) {
                     if((ret = dup2(fd, op->fd)) < 0)
                         goto fail;
                 } else {
                     ret = fcntl(fd, F_GETFD);
                     ret = fcntl(fd, F_SETFD, ret & ~FD_CLOEXEC);
                     if(ret < 0)
                         goto fail;
                 }
                 break;
             case FDOP_OPEN:
                 fd = open(op->path, op->oflag, op->mode);
                 if((ret = fd) < 0)
                     goto fail;
                 if(fd != op->fd) {
                     if((ret = dup2(fd, op->fd)) < 0)
                         goto fail;
                     close(fd);
                 }
                 break;
             case FDOP_CHDIR:
                 ret = chdir(op->path);
                 if(ret < 0)
                     goto fail;
                 break;
             case FDOP_FCHDIR:
                 ret = fchdir(op->fd);
                 if(ret < 0)
                     goto fail;
                 break;
             }
         }
     }
     /* Close-on-exec flag may have been lost if we moved the pipe
      * to a different fd. */
     fcntl(p, F_SETFD, FD_CLOEXEC);
     pthread_sigmask(SIG_SETMASK, (attr->__flags & POSIX_SPAWN_SETSIGMASK)
         ? &attr->__mask : &args->oldmask, 0);
     if(use_execvpe)
         execvpe(args->path, args->argv, args->envp);
     else
         execve(args->path, args->argv, args->envp);
     ret = -errno;
 fail:
     /* Since sizeof errno < PIPE_BUF, the write is atomic. */
     ret = -ret;
     if(ret)
         while(write(p, &ret, sizeof ret) < 0);
     _exit(127);
 }
References posix_spawn_file_actions_t::__actions, posix_spawnattr_t::__def, posix_spawnattr_t::__flags, posix_spawnattr_t::__fn, __get_handler_set(), __restrict, _exit(), args::argv, args::attr, chdir(), close(), fdop::cmd, dup(), dup2(), EBADF, args::envp, errno, execve(), execvpe(), F_GETFD, F_SETFD, args::fa, fchdir(), fcntl(), fdop::fd, FD_CLOEXEC, FDOP_CHDIR, FDOP_CLOSE, FDOP_DUP2, FDOP_FCHDIR, FDOP_OPEN, getgid, getuid, i, mlibc::infoLogger, fdop::mode, fdop::next, NSIG, fdop::oflag, args::oldmask, open(), p, args::p, fdop::path, args::path, POSIX_SPAWN_RESETIDS, POSIX_SPAWN_SETPGROUP, POSIX_SPAWN_SETSID, POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, fdop::prev, pthread_sigmask(), ret, sigaction::sa_handler, setgid(), setsid(), setuid(), SIG_DFL, SIG_IGN, SIG_SETMASK, sigaction(), sigismember, fdop::srcfd, and write().
Referenced by fork(), forkpty(), popen(), posix_spawn(), pthread_atfork(), set_job_status_and_cleanup(), mlibc::sys_fork(), system(), tdelete(), vfork(), wait_for(), wait_for_single_pid(), and waitchld().
posix_spawn()
int posix_spawn (pid_t *__restrict res, const char *__restrict path, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t *__restrict attrs, char *const argv[], char *const envp[])
Definition at line 191 of file spawn-stubs.cpp.
{
     pid_t pid;
     int ec = 0, cs;
     struct args args;
     const posix_spawnattr_t empty_attr = {};
     sigset_t full_sigset;
     sigfillset(&full_sigset);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     args.path = path;
     args.fa = file_actions;
     args.attr = attrs ? attrs : &empty_attr;
     args.argv = argv;
     args.envp = envp;
     pthread_sigmask(SIG_BLOCK, &full_sigset, &args.oldmask);
     /* The lock guards both against seeing a SIGABRT disposition change
      * by abort and against leaking the pipe fd to fork-without-exec. */
     //LOCK(__abort_lock);
     if(pipe2(args.p, O_CLOEXEC)) {
         //UNLOCK(__abort_lock);
         ec = errno;
         goto fail;
     }
     /* Mlibc change: We use fork + execve, as clone is not implemented.
      * This yields the same result in the end. */
     //pid = clone(child, stack + sizeof stack, CLONE_VM | CLONE_VFORK | SIGCHLD, &args);
     pid = fork();
     if(!pid) {
         child(&args);
     }
     close(args.p[1]);
     //UNLOCK(__abort_lock);
     if(pid > 0) {
         if(read(args.p[0], &ec, sizeof ec) != sizeof ec)
             ec = 0;
         else
             waitpid(pid, 0, 0);
     } else {
         ec = -pid;
     }
     close(args.p[0]);
     if(!ec && res)
         *res = pid;
 fail:
     pthread_sigmask(SIG_SETMASK, &args.oldmask, 0);
     pthread_setcancelstate(cs, 0);
     return ec;
 }
References argv, args::argv, args::attr, child(), close(), args::envp, errno, args::fa, fork(), O_CLOEXEC, args::oldmask, args::p, args::path, pipe2(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pthread_sigmask(), read(), SIG_BLOCK, SIG_SETMASK, sigfillset, and waitpid().
Referenced by posix_spawnp().
posix_spawn_file_actions_addclose()
int posix_spawn_file_actions_addclose (posix_spawn_file_actions_t * file_actions, int fildes)
Definition at line 335 of file spawn-stubs.cpp.
                     {
     struct fdop *op = (struct fdop *)malloc(sizeof *op);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_CLOSE;
     op->fd = fildes;
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References posix_spawn_file_actions_t::__actions, fdop::cmd, ENOMEM, fdop::fd, FDOP_CLOSE, malloc, fdop::next, and fdop::prev.
Referenced by popen().
posix_spawn_file_actions_adddup2()
int posix_spawn_file_actions_adddup2 (posix_spawn_file_actions_t * file_actions, int fildes, int newfildes)
Definition at line 320 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)malloc(sizeof *op);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_DUP2;
     op->srcfd = fildes;
     op->fd = newfildes;
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References posix_spawn_file_actions_t::__actions, fdop::cmd, ENOMEM, fdop::fd, FDOP_DUP2, malloc, fdop::next, fdop::prev, and fdop::srcfd.
Referenced by popen().
posix_spawn_file_actions_addopen()
int posix_spawn_file_actions_addopen (posix_spawn_file_actions_t *__restrict file_actions, int fildes, const char *__restrict path, int oflag, mode_t mode)
Definition at line 349 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)malloc(sizeof *op + strlen(path) + 1);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_OPEN;
     op->fd = fildes;
     op->oflag = oflag;
     op->mode = mode;
     strcpy(op->path, path);
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References fdop::cmd, ENOMEM, fdop::fd, FDOP_OPEN, malloc, fdop::mode, fdop::next, fdop::oflag, fdop::path, fdop::prev, strcpy, and strlen().
posix_spawn_file_actions_destroy()
int posix_spawn_file_actions_destroy (posix_spawn_file_actions_t * file_actions)
Definition at line 310 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)file_actions->__actions, *next;
     while(op) {
         next = op->next;
         free(op);
         op = next;
     }
     return 0;
 }
References posix_spawn_file_actions_t::__actions, free, and fdop::next.
Referenced by popen().
posix_spawn_file_actions_init()
int posix_spawn_file_actions_init (posix_spawn_file_actions_t * file_actions)
Definition at line 305 of file spawn-stubs.cpp.
{
     file_actions->__actions = 0;
     return 0;
 }
References posix_spawn_file_actions_t::__actions.
Referenced by popen().
posix_spawnattr_destroy()
int posix_spawnattr_destroy (posix_spawnattr_t * attr)
Definition at line 257 of file spawn-stubs.cpp.
{
     return 0;
 }
Referenced by system().
posix_spawnattr_init()
int posix_spawnattr_init (posix_spawnattr_t * attr)
Definition at line 252 of file spawn-stubs.cpp.
{
     *attr = (posix_spawnattr_t){};
     return 0;
 }
References args::attr.
Referenced by system().
posix_spawnattr_setflags()
int posix_spawnattr_setflags (posix_spawnattr_t * attr, short flags)
Definition at line 261 of file spawn-stubs.cpp.
{
     const unsigned all_flags =
             POSIX_SPAWN_RESETIDS |
             POSIX_SPAWN_SETPGROUP |
             POSIX_SPAWN_SETSIGDEF |
             POSIX_SPAWN_SETSIGMASK |
             POSIX_SPAWN_SETSCHEDPARAM |
             POSIX_SPAWN_SETSCHEDULER |
             POSIX_SPAWN_USEVFORK |
             POSIX_SPAWN_SETSID;
     if(flags & ~all_flags)
         return EINVAL;
     attr->__flags = flags;
     return 0;
 }
References posix_spawnattr_t::__flags, args::attr, EINVAL, flags, POSIX_SPAWN_RESETIDS, POSIX_SPAWN_SETPGROUP, POSIX_SPAWN_SETSCHEDPARAM, POSIX_SPAWN_SETSCHEDULER, POSIX_SPAWN_SETSID, POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, and POSIX_SPAWN_USEVFORK.
Referenced by system().
posix_spawnattr_setpgroup()
int posix_spawnattr_setpgroup (posix_spawnattr_t * attr, pid_t pgroup)
Definition at line 300 of file spawn-stubs.cpp.
{
     attr->__pgrp = pgroup;
     return 0;
 }
References posix_spawnattr_t::__pgrp, and args::attr.
posix_spawnattr_setschedparam()
int posix_spawnattr_setschedparam (posix_spawnattr_t * __restrict, const struct sched_param * __restrict)
Definition at line 283 of file spawn-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
posix_spawnattr_setschedpolicy()
int posix_spawnattr_setschedpolicy (posix_spawnattr_t * attr, int schedpolicy)
Definition at line 289 of file spawn-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
posix_spawnattr_setsigdefault()
int posix_spawnattr_setsigdefault (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigdefault)
Definition at line 277 of file spawn-stubs.cpp.
{
     attr->__def = *sigdefault;
     return 0;
 }
References posix_spawnattr_t::__def, and args::attr.
Referenced by system().
posix_spawnattr_setsigmask()
int posix_spawnattr_setsigmask (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigmask)
Definition at line 294 of file spawn-stubs.cpp.
{
     attr->__mask = *sigmask;
     return 0;
 }
References posix_spawnattr_t::__mask, args::attr, and sigmask.
Referenced by system().
posix_spawnp()
int posix_spawnp (pid_t *__restrict pid, const char *__restrict file, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t *__restrict attrp, char *const argv[], char *const envp[])
Definition at line 366 of file spawn-stubs.cpp.
{
     posix_spawnattr_t spawnp_attr = {};
     if(attrp)
         spawnp_attr = *attrp;
     spawnp_attr.__fn = (void *)execvpe;
     return posix_spawn(pid, file, file_actions, &spawnp_attr, argv, envp);
 }
References posix_spawnattr_t::__fn, argv, execvpe(), and posix_spawn().
Variable Documentation
handler_set
unsigned long handler_set[NSIG/(8 *sizeof(long))] static
Definition at line 39 of file spawn-stubs.cpp.
Referenced by __get_handler_set().