Fennix: Userspace/apps/base/busybox/coreutils/cat.c File Reference
cat.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Functions
int cat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
cat_main()
int cat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 169 of file cat.c.
 {
 #if ENABLE_FEATURE_CATV || ENABLE_FEATURE_CATN
     unsigned opts;
     opts =
 #endif
     getopt32(argv, IF_FEATURE_CATV("^")
         /* -u is ignored ("unbuffered") */
         IF_FEATURE_CATV("etvA")IF_FEATURE_CATN("nb")"u"
         IF_FEATURE_CATV("\0" "Aetv" /* -A == -vet */)
     );
     argv += optind;
     /* Read from stdin if there's nothing else to do. */
     if (!argv[0])
         *--argv = (char*)"-";
 #if ENABLE_FEATURE_CATV
     if (opts & 7)
         return catv(opts, argv);
     opts >>= 4;
 #endif
 #if ENABLE_FEATURE_CATN
 # define CAT_OPT_n (1<<0)
 # define CAT_OPT_b (1<<1)
     if (opts & (CAT_OPT_n|CAT_OPT_b)) { /* -n or -b */
         struct number_state ns;
         int exitcode;
         ns.width = 6;
         ns.start = 1;
         ns.inc = 1;
         ns.sep = "\t";
         ns.empty_str = NULL;
         ns.all = !(opts & CAT_OPT_b); /* -n without -b */
         ns.nonempty = (opts & CAT_OPT_b); /* -b (with or without -n) */
         exitcode = EXIT_SUCCESS;
         do {
             exitcode |= print_numbered_lines(&ns, *argv);
         } while (*++argv);
         fflush_stdout_and_exit(exitcode);
     }
     /*opts >>= 2;*/
 #endif
     return bb_cat(argv);
 }
References number_state::all, argv, bb_cat(), number_state::empty_str, EXIT_SUCCESS, exitcode, fflush_stdout_and_exit(), getopt32(), number_state::inc, number_state::nonempty, NULL, optind, print_numbered_lines(), number_state::sep, number_state::start, and number_state::width.