Fennix: Userspace/apps/base/bash/print_cmd.c File Reference
print_cmd.c File Reference
#include "config.h"
#include <stdio.h>
#include <varargs.h>
#include "bashansi.h"
#include "bashintl.h"
#include "shell.h"
#include "flags.h"
#include <y.tab.h>
#include "input.h"
#include "shmbutil.h"
#include "builtins/common.h"
Macros
#define NEED_XTRACE_SET_DECL
#define PFUNC VFunction
#define PRINTED_COMMAND_INITIAL_SIZE 64
#define PRINTED_COMMAND_GROW_SIZE 128
#define CHECK_XTRACE_FP xtrace_fp = (xtrace_fp ? xtrace_fp : stderr)
#define EXPCHAR(c) ((c) == '{' || (c) == '~' || (c) == '$' || (c) == '`')
#define PRINT_DEFERRED_HEREDOCS(x)
Functions
int printf PARAMS ((const char *,...))
static void cprintf ()
static void xprintf ()
static void reset_locals PARAMS ((void))
static void newline PARAMS ((char *))
static void indent PARAMS ((int))
static void make_command_string_internal PARAMS ((COMMAND *))
static void _print_word_list PARAMS ((WORD_LIST *, char *, PFUNC *))
static void command_print_word_list PARAMS ((WORD_LIST *, char *))
static void print_case_clauses PARAMS ((PATTERN_LIST *))
static void print_redirection_list PARAMS ((REDIRECT *))
static void print_deferred_heredocs PARAMS ((const char *))
static void print_for_command PARAMS ((FOR_COM *))
static void print_group_command PARAMS ((GROUP_COM *))
static void print_case_command PARAMS ((CASE_COM *))
static void print_while_command PARAMS ((WHILE_COM *))
static void print_until_or_while PARAMS ((WHILE_COM *, char *))
static void print_if_command PARAMS ((IF_COM *))
static void print_function_def PARAMS ((FUNCTION_DEF *))
void print_command (COMMAND *command)
char * make_command_string (COMMAND *command)
char * print_comsub (COMMAND *command)
static void make_command_string_internal (COMMAND *command)
static void _print_word_list (WORD_LIST *list, char *separator, PFUNC *pfunc)
void print_word_list (WORD_LIST *list, char *separator)
void xtrace_set (int fd, FILE *fp)
void xtrace_init ()
void xtrace_reset ()
void xtrace_fdchk (int fd)
char * indirection_level_string ()
void xtrace_print_assignment (char *name, char *value, int assign_list, int xflags)
void xtrace_print_word_list (WORD_LIST *list, int xtflags)
static void command_print_word_list (WORD_LIST *list, char *separator)
void print_for_command_head (FOR_COM *for_command)
void xtrace_print_for_command_head (FOR_COM *for_command)
static void print_for_command (FOR_COM *for_command)
static void print_group_command (GROUP_COM *group_command)
void print_case_command_head (CASE_COM *case_command)
void xtrace_print_case_command_head (CASE_COM *case_command)
static void print_case_command (CASE_COM *case_command)
static void print_case_clauses (PATTERN_LIST *clauses)
static void print_while_command (WHILE_COM *while_command)
static void print_until_command (WHILE_COM *while_command)
static void print_until_or_while (WHILE_COM *while_command, char *which)
static void print_if_command (IF_COM *if_command)
void print_simple_command (SIMPLE_COM *simple_command)
static void print_heredocs (REDIRECT *heredocs)
static void print_heredoc_bodies (REDIRECT *heredocs)
static void print_deferred_heredocs (char *cstring) const
static void print_redirection_list (REDIRECT *redirects)
static void print_heredoc_header (REDIRECT *redirect)
static void print_heredoc_body (REDIRECT *redirect)
static void print_redirection (REDIRECT *redirect)
static void reset_locals ()
static void print_function_def (FUNCTION_DEF *func)
char * named_function_string (char *name, COMMAND *command, int flags)
static void newline (char *string)
static void indent (int amount)
static void semicolon ()
static void cprintf (char *control, va_alist) const
static void the_printed_command_resize (int length)
static void xprintf (char *format, arg1, arg2, arg3, arg4, arg5) const
Variables
static int indentation
static int indentation_amount = 4
char * the_printed_command = (char *)NULL
int the_printed_command_size = 0
int command_string_index = 0
int xtrace_fd = -1
FILE * xtrace_fp = 0
static int inside_function_def
static int skip_this_indent
static int was_heredoc
static int printing_connection
static int printing_comsub
static REDIRECT * deferred_heredocs
static int group_command_nesting
static char * indirection_string = 0
static int indirection_stringsiz = 0
static char * indentation_string
static int indentation_size
Macro Definition Documentation
CHECK_XTRACE_FP
#define CHECK_XTRACE_FP xtrace_fp = (xtrace_fp ? xtrace_fp : stderr)
Definition at line 116 of file print_cmd.c.
EXPCHAR
#define EXPCHAR (c) ((c) == '{' || (c) == '~' || (c) == '$' || (c) == '`')
Definition at line 119 of file print_cmd.c.
NEED_XTRACE_SET_DECL
#define NEED_XTRACE_SET_DECL
Definition at line 41 of file print_cmd.c.
PFUNC
#define PFUNC VFunction
Definition at line 65 of file print_cmd.c.
PRINT_DEFERRED_HEREDOCS
#define PRINT_DEFERRED_HEREDOCS (x)
Value:
  do { \
    if (deferred_heredocs) \
      print_deferred_heredocs (x); \
  } while (0)
Definition at line 121 of file print_cmd.c.
PRINTED_COMMAND_GROW_SIZE
#define PRINTED_COMMAND_GROW_SIZE 128
Definition at line 107 of file print_cmd.c.
PRINTED_COMMAND_INITIAL_SIZE
#define PRINTED_COMMAND_INITIAL_SIZE 64
Definition at line 106 of file print_cmd.c.
Function Documentation
_print_word_list()
static void _print_word_list (WORD_LIST * list, char * separator, PFUNC * pfunc) static
Definition at line 379 of file print_cmd.c.
 {
   WORD_LIST *w;
   for (w = list; w; w = w->next)
     (*pfunc) ("%s%s", w->word->word, w->next ? separator : "");
 }
References list(), separator, and w.
Referenced by command_print_word_list(), and print_word_list().
command_print_word_list()
static void command_print_word_list (WORD_LIST * list, char * separator) static
Definition at line 595 of file print_cmd.c.
 {
   _print_word_list (list, separator, cprintf);
 }
References _print_word_list(), cprintf(), list(), and separator.
Referenced by print_case_clauses(), print_for_command_head(), and print_simple_command().
cprintf() [1/2]
static void cprintf () static
Referenced by command_print_word_list(), indent(), make_command_string_internal(), named_function_string(), newline(), print_case_clauses(), print_case_command_head(), print_deferred_heredocs(), print_for_command(), print_for_command_head(), print_function_def(), print_group_command(), print_heredoc_bodies(), print_heredoc_body(), print_heredoc_header(), print_heredocs(), print_if_command(), print_redirection(), print_redirection_list(), print_simple_command(), print_until_or_while(), and semicolon().
cprintf() [2/2]
static void cprintf (char * control, va_alist) const static
Definition at line 1526 of file print_cmd.c.
 {
   register const char *s;
   char char_arg[2], *argp, intbuf[INT_STRLEN_BOUND (unsigned int) + 1];
   int digit_arg, arg_len, c;
   va_list args;
   SH_VA_START (args, control);
   arg_len = strlen (control);
   the_printed_command_resize (arg_len + 1);
   char_arg[1] = '\0';
   s = control;
   while (s && *s)
     {
       c = *s++;
       argp = (char *)NULL;
       if (c != '%' || !*s)
     {
       char_arg[0] = c;
       argp = char_arg;
       arg_len = 1;
     }
       else
     {
       c = *s++;
       switch (c)
         {
         case '%':
           char_arg[0] = c;
           argp = char_arg;
           arg_len = 1;
           break;
         case 's':
           argp = va_arg (args, char *);
           arg_len = strlen (argp);
           break;
         case 'd':
           /* Represent an out-of-range file descriptor with an out-of-range
          integer value.  We can do this because the only use of `%d' in
          the calls to cprintf is to output a file descriptor number for
          a redirection. */
           digit_arg = va_arg (args, int);
           if (digit_arg < 0)
         {
           sprintf (intbuf, "%u", (unsigned int)-1);
           argp = intbuf;
         }
           else
         argp = inttostr (digit_arg, intbuf, sizeof (intbuf));
           arg_len = strlen (argp);
           break;
         case 'c':
           char_arg[0] = va_arg (args, int);
           argp = char_arg;
           arg_len = 1;
           break;
         default:
           programming_error (_("cprintf: `%c': invalid format character"), c);
           /*NOTREACHED*/
         }
     }
       if (argp && arg_len)
     {
       the_printed_command_resize (arg_len + 1);
       FASTCOPY (argp, the_printed_command + command_string_index, arg_len);
       command_string_index += arg_len;
     }
     }
   va_end (args);
   the_printed_command[command_string_index] = '\0';
 }
References _, args, c, command_string_index, control, FASTCOPY, INT_STRLEN_BOUND, intbuf, inttostr(), NULL, programming_error(), s, SH_VA_START, sprintf(), strlen(), the_printed_command, the_printed_command_resize(), va_arg, and va_end.
indent()
static void indent (int amount) static
Definition at line 1498 of file print_cmd.c.
 {
   register int i;
   RESIZE_MALLOCED_BUFFER (indentation_string, 0, amount, indentation_size, 16);
   for (i = 0; amount > 0; amount--)
     indentation_string[i++] = ' ';
   indentation_string[i] = '\0';
   cprintf ("%s", indentation_string);
 }
References cprintf(), i, indentation_size, indentation_string, and RESIZE_MALLOCED_BUFFER.
Referenced by make_command_string_internal(), newline(), print_function_def(), and print_group_command().
indirection_level_string()
char* indirection_level_string ()
Definition at line 452 of file print_cmd.c.
 {
   register int i, j;
   char *ps4;
   char ps4_firstc[MB_LEN_MAX+1];
   int ps4_firstc_len, ps4_len, ineed, old;
   ps4 = get_string_value ("PS4");
   if (indirection_string == 0)
     indirection_string = xmalloc (indirection_stringsiz = 100);
   indirection_string[0] = '\0';
   if (ps4 == 0 || *ps4 == '\0')
     return (indirection_string);
   old = change_flag ('x', FLAG_OFF);
   ps4 = decode_prompt_string (ps4);
   if (old)
     change_flag ('x', FLAG_ON);
   if (ps4 == 0 || *ps4 == '\0')
     {
       FREE (ps4);
       return (indirection_string);
     }
 #if defined (HANDLE_MULTIBYTE)
   ps4_len = strnlen (ps4, MB_CUR_MAX);
   ps4_firstc_len = MBLEN (ps4, ps4_len);
   if (ps4_firstc_len == 1 || ps4_firstc_len == 0 || ps4_firstc_len < 0)
     {
       ps4_firstc[0] = ps4[0];
       ps4_firstc[ps4_firstc_len = 1] = '\0';
     }
   else
     memcpy (ps4_firstc, ps4, ps4_firstc_len);
 #else
   ps4_firstc[0] = ps4[0];
   ps4_firstc[ps4_firstc_len = 1] = '\0';
 #endif
   /* Dynamically resize indirection_string so we have room for everything
      and we don't have to truncate ps4 */
   ineed = (ps4_firstc_len * indirection_level) + strlen (ps4);
   if (ineed > indirection_stringsiz - 1)
     {
       indirection_stringsiz = ineed + 1;
       indirection_string = xrealloc (indirection_string, indirection_stringsiz);
     }
   for (i = j = 0; ps4_firstc[0] && j < indirection_level && i < indirection_stringsiz - 1; i += ps4_firstc_len, j++)
     {
       if (ps4_firstc_len == 1)
     indirection_string[i] = ps4_firstc[0];
       else
     memcpy (indirection_string+i, ps4_firstc, ps4_firstc_len);
     }
   for (j = ps4_firstc_len; *ps4 && ps4[j] && i < indirection_stringsiz - 1; i++, j++)
     indirection_string[i] = ps4[j];
   indirection_string[i] = '\0';
   free (ps4);
   return (indirection_string);
 }
References change_flag(), decode_prompt_string(), FLAG_OFF, FLAG_ON, FREE, free, get_string_value(), i, indirection_level, indirection_string, indirection_stringsiz, j, MB_CUR_MAX, MB_LEN_MAX, MBLEN, memcpy, old, strlen(), strnlen(), xmalloc, and xrealloc.
Referenced by xtrace_print_assignment(), xtrace_print_case_command_head(), xtrace_print_for_command_head(), and xtrace_print_word_list().
make_command_string()
char* make_command_string (COMMAND * command)
Definition at line 157 of file print_cmd.c.
 {
   command_string_index = was_heredoc = 0;
   deferred_heredocs = 0;
   make_command_string_internal (command);
   return (the_printed_command);
 }
References command_string_index, deferred_heredocs, make_command_string_internal(), the_printed_command, and was_heredoc.
Referenced by execute_command_internal(), pretty_print_loop(), print_command(), and print_comsub().
make_command_string_internal()
static void make_command_string_internal (COMMAND * command) static
Definition at line 183 of file print_cmd.c.
 {
   char s[3];
   if (command == 0)
     cprintf ("");
   else
     {
       if (skip_this_indent)
     skip_this_indent--;
       else
     indent (indentation);
       if (command->flags & CMD_TIME_PIPELINE)
     {
       cprintf ("time ");
       if (command->flags & CMD_TIME_POSIX)
         cprintf ("-p ");
     }
       if (command->flags & CMD_INVERT_RETURN)
     cprintf ("! ");
       switch (command->type)
     {
     case cm_for:
       print_for_command (command->value.For);
       break;
 #if defined (ARITH_FOR_COMMAND)
     case cm_arith_for:
       print_arith_for_command (command->value.ArithFor);
       break;
 #endif
 #if defined (SELECT_COMMAND)
     case cm_select:
       print_select_command (command->value.Select);
       break;
 #endif
     case cm_case:
       print_case_command (command->value.Case);
       break;
     case cm_while:
       print_while_command (command->value.While);
       break;
     case cm_until:
       print_until_command (command->value.While);
       break;
     case cm_if:
       print_if_command (command->value.If);
       break;
 #if defined (DPAREN_ARITHMETIC)
     case cm_arith:
       print_arith_command (command->value.Arith->exp);
       break;
 #endif
 #if defined (COND_COMMAND)
     case cm_cond:
       print_cond_command (command->value.Cond);
       break;
 #endif
     case cm_simple:
       print_simple_command (command->value.Simple);
       break;
     case cm_connection:
       skip_this_indent++;
       printing_connection++;
       make_command_string_internal (command->value.Connection->first);
       switch (command->value.Connection->connector)
         {
         case '&':
         case '|':
           {
         char c = command->value.Connection->connector;
         s[0] = ' ';
         s[1] = c;
         s[2] = '\0';
         print_deferred_heredocs (s);
         if (c != '&' || command->value.Connection->second)
           {
             cprintf (" ");
             skip_this_indent++;
           }
           }
           break;
         case AND_AND:
           print_deferred_heredocs (" && ");
           if (command->value.Connection->second)
         skip_this_indent++;
           break;
         case OR_OR:
           print_deferred_heredocs (" || ");
           if (command->value.Connection->second)
         skip_this_indent++;
           break;
         case ';':
         case '\n':              /* special case this */
           {
         char c = command->value.Connection->connector;
         int was_newline;
         s[0] = printing_comsub ? c : ';';
         s[1] = '\0';
         was_newline = deferred_heredocs == 0 && was_heredoc == 0 && c == '\n';
         if (deferred_heredocs == 0)
           {
             if (was_heredoc == 0)
               cprintf ("%s", s);    /* inside_function_def? */
             else
               was_heredoc = 0;
           }
         else
           /* print_deferred_heredocs special-cases `;' */
           print_deferred_heredocs (inside_function_def ? "" : ";");
         if (inside_function_def)
           cprintf ("\n");
         else if (printing_comsub && c == '\n' && was_newline == 0)
           cprintf ("\n");   /* preserve newlines in comsubs but don't double them */
         else
           {
             if (c == ';')
               cprintf (" ");
             if (command->value.Connection->second)
               skip_this_indent++;
           }
         break;
           }
         default:
           cprintf (_("print_command: bad connector `%d'"),
                command->value.Connection->connector);
           break;
         }
       make_command_string_internal (command->value.Connection->second);
       PRINT_DEFERRED_HEREDOCS ("");
       printing_connection--;
       break;
     case cm_function_def:
       print_function_def (command->value.Function_def);
       break;
     case cm_group:
       print_group_command (command->value.Group);
       break;
     case cm_subshell:
       cprintf ("( ");
       skip_this_indent++;
       make_command_string_internal (command->value.Subshell->command);
       PRINT_DEFERRED_HEREDOCS ("");
       cprintf (" )");
       break;
     case cm_coproc:
       cprintf ("coproc %s ", command->value.Coproc->name);
       skip_this_indent++;
       make_command_string_internal (command->value.Coproc->command);
       break;
     default:
       command_error ("print_command", CMDERR_BADTYPE, command->type, 0);
       break;
     }
       if (command->redirects)
     {
       cprintf (" ");
       print_redirection_list (command->redirects);
     }
     }
 }
References _, AND_AND, c, cm_arith, cm_arith_for, cm_case, cm_cond, cm_connection, cm_coproc, cm_for, cm_function_def, cm_group, cm_if, cm_select, cm_simple, cm_subshell, cm_until, cm_while, CMD_INVERT_RETURN, CMD_TIME_PIPELINE, CMD_TIME_POSIX, CMDERR_BADTYPE, command_error(), cprintf(), deferred_heredocs, command::flags, indent(), indentation, inside_function_def, OR_OR, print_case_command(), print_deferred_heredocs(), PRINT_DEFERRED_HEREDOCS, print_for_command(), print_function_def(), print_group_command(), print_if_command(), print_redirection_list(), print_simple_command(), print_until_command(), print_while_command(), printing_comsub, printing_connection, command::redirects, s, skip_this_indent, command::type, command::value, and was_heredoc.
Referenced by make_command_string(), named_function_string(), print_case_clauses(), print_for_command(), print_function_def(), print_group_command(), print_if_command(), and print_until_or_while().
named_function_string()
char* named_function_string (char * name, COMMAND * command, int flags)
Definition at line 1388 of file print_cmd.c.
 {
   char *result;
   int old_indent, old_amount;
   COMMAND *cmdcopy;
   REDIRECT *func_redirects;
   old_indent = indentation;
   old_amount = indentation_amount;
   command_string_index = was_heredoc = 0;
   deferred_heredocs = 0;
   printing_comsub = 0;
   if (name && *name)
     {
       if (find_reserved_word (name) >= 0)
     cprintf ("function ");
       cprintf ("%s ", name);
     }
   cprintf ("() ");
   if ((flags & FUNC_MULTILINE) == 0)
     {
       indentation = 1;
       indentation_amount = 0;
     }
   else
     {
       cprintf ("\n");
       indentation += indentation_amount;
     }
   inside_function_def++;
   cprintf ((flags & FUNC_MULTILINE) ? "{ \n" : "{ ");
   cmdcopy = copy_command (command);
   /* Take any redirections specified in the function definition (which should
      apply to the function as a whole) and save them for printing later. */
   func_redirects = (REDIRECT *)NULL;
   if (cmdcopy->type == cm_group)
     {
       func_redirects = cmdcopy->redirects;
       cmdcopy->redirects = (REDIRECT *)NULL;
     }
   make_command_string_internal (cmdcopy->type == cm_group
                     ? cmdcopy->value.Group->command
                     : cmdcopy);
   PRINT_DEFERRED_HEREDOCS ("");
   indentation = old_indent;
   indentation_amount = old_amount;
   inside_function_def--;
   if (func_redirects)
     { /* { */
       newline ("} ");
       print_redirection_list (func_redirects);
       cmdcopy->redirects = func_redirects;
     }
   else
     {   /* { */
       newline ("}");
       was_heredoc = 0;
     }
   result = the_printed_command;
   if ((flags & FUNC_MULTILINE) == 0)
     {
 #if 0
       register int i;
       for (i = 0; result[i]; i++)
     if (result[i] == '\n')
       {
         strcpy (result + i, result + i + 1);
         --i;
       }
 #else
       if (result[2] == '\n')    /* XXX -- experimental */
     memmove (result + 2, result + 3, strlen (result) - 2);
 #endif
     }
   dispose_command (cmdcopy);
   if (flags & FUNC_EXTERNAL)
     result = remove_quoted_escapes (result);
   return (result);
 }
References cm_group, command_string_index, copy_command(), cprintf(), deferred_heredocs, dispose_command(), find_reserved_word(), flags, FUNC_EXTERNAL, FUNC_MULTILINE, i, indentation, indentation_amount, inside_function_def, make_command_string_internal(), memmove, newline(), NULL, PRINT_DEFERRED_HEREDOCS, print_redirection_list(), printing_comsub, remove_quoted_escapes(), strcpy, strlen(), the_printed_command, and was_heredoc.
Referenced by make_env_array_from_var_list(), and print_var_function().
newline()
static void newline (char * string) static
Definition at line 1485 of file print_cmd.c.
 {
   cprintf ("\n");
   indent (indentation);
   if (string && *string)
     cprintf ("%s", string);
 }
References cprintf(), indent(), and indentation.
Referenced by _hs_append_history_line(), klogd_main(), named_function_string(), ParseDMXConfig(), print_case_clauses(), print_case_command(), print_for_command(), print_function_def(), print_if_command(), and print_until_or_while().
PARAMS() [1/17]
static void print_case_command PARAMS ((CASE_COM *)) static
PARAMS() [2/17]
static void newline PARAMS ((char *)) static
PARAMS() [3/17]
static void make_command_string_internal PARAMS ((COMMAND *)) static
PARAMS() [4/17]
static void print_deferred_heredocs PARAMS ((const char *)) static
PARAMS() [5/17]
int printf PARAMS ((const char *,...))
PARAMS() [6/17]
static void print_for_command PARAMS ((FOR_COM *)) static
PARAMS() [7/17]
static void print_function_def PARAMS ((FUNCTION_DEF *)) static
PARAMS() [8/17]
static void print_group_command PARAMS ((GROUP_COM *)) static
PARAMS() [9/17]
static void print_if_command PARAMS ((IF_COM *)) static
PARAMS() [10/17]
static void indent PARAMS ((int)) static
PARAMS() [11/17]
static void print_case_clauses PARAMS ((PATTERN_LIST *)) static
PARAMS() [12/17]
static void print_redirection_list PARAMS ((REDIRECT *)) static
PARAMS() [13/17]
static void reset_locals PARAMS ((void)) static
PARAMS() [14/17]
static void print_while_command PARAMS ((WHILE_COM *)) static
PARAMS() [15/17]
static void print_until_or_while PARAMS ((WHILE_COM *, char *)) static
PARAMS() [16/17]
static void command_print_word_list PARAMS ((WORD_LIST *, char *)) static
PARAMS() [17/17]
static void _print_word_list PARAMS ((WORD_LIST *, char *, PFUNC *)) static
print_case_clauses()
static void print_case_clauses (PATTERN_LIST * clauses) static
Definition at line 761 of file print_cmd.c.
 {
   indentation += indentation_amount;
   while (clauses)
     {
       newline ("");
       command_print_word_list (clauses->patterns, " | ");
       cprintf (")\n");
       indentation += indentation_amount;
       make_command_string_internal (clauses->action);
       indentation -= indentation_amount;
       PRINT_DEFERRED_HEREDOCS ("");
       if (clauses->flags & CASEPAT_FALLTHROUGH)
     newline (";&");
       else if (clauses->flags & CASEPAT_TESTNEXT)
     newline (";;&");
       else
     newline (";;");
       clauses = clauses->next;
     }
   indentation -= indentation_amount;
 }
References pattern_list::action, CASEPAT_FALLTHROUGH, CASEPAT_TESTNEXT, command_print_word_list(), cprintf(), pattern_list::flags, indentation, indentation_amount, make_command_string_internal(), newline(), pattern_list::next, pattern_list::patterns, and PRINT_DEFERRED_HEREDOCS.
Referenced by print_case_command().
print_case_command()
static void print_case_command (CASE_COM * case_command) static
Definition at line 750 of file print_cmd.c.
 {
   print_case_command_head (case_command);
   if (case_command->clauses)
     print_case_clauses (case_command->clauses);
   newline ("esac");
 }
References case_com::clauses, newline(), print_case_clauses(), and print_case_command_head().
Referenced by make_command_string_internal().
print_case_command_head()
void print_case_command_head (CASE_COM * case_command)
Definition at line 734 of file print_cmd.c.
 {
   cprintf ("case %s in ", case_command->word->word);
 }
References cprintf(), word_desc::word, and case_com::word.
Referenced by execute_case_command(), and print_case_command().
print_command()
void print_command (COMMAND * command)
Definition at line 145 of file print_cmd.c.
 {
   command_string_index = 0;
   printf ("%s", make_command_string (command));
 }
References command_string_index, make_command_string(), and printf.
print_comsub()
char* print_comsub (COMMAND * command)
Definition at line 170 of file print_cmd.c.
 {
   char *ret;
   printing_comsub++;
   ret = make_command_string (command);
   printing_comsub--;
   return ret;
 }
References make_command_string(), and printing_comsub.
Referenced by parse_comsub().
print_deferred_heredocs()
static void print_deferred_heredocs (char * cstring) const static
Definition at line 1041 of file print_cmd.c.
 {
   /* We now print the heredoc headers in print_redirection_list */
   if (cstring && cstring[0] && (cstring[0] != ';' || cstring[1]))
     cprintf ("%s", cstring);
   if (deferred_heredocs)
     {
       print_heredoc_bodies (deferred_heredocs);
       if (cstring && cstring[0] && (cstring[0] != ';' || cstring[1]))
     cprintf (" ");  /* make sure there's at least one space */
       dispose_redirects (deferred_heredocs);
       was_heredoc = 1;
     }
   deferred_heredocs = (REDIRECT *)NULL;
 }
References cprintf(), deferred_heredocs, dispose_redirects(), NULL, print_heredoc_bodies(), and was_heredoc.
Referenced by make_command_string_internal().
print_for_command()
static void print_for_command (FOR_COM * for_command) static
Definition at line 621 of file print_cmd.c.
 {
   print_for_command_head (for_command);
   cprintf (";");
   newline ("do\n");
   indentation += indentation_amount;
   make_command_string_internal (for_command->action);
   PRINT_DEFERRED_HEREDOCS ("");
   semicolon ();
   indentation -= indentation_amount;
   newline ("done");
 }
References for_com::action, cprintf(), indentation, indentation_amount, make_command_string_internal(), newline(), PRINT_DEFERRED_HEREDOCS, print_for_command_head(), and semicolon().
Referenced by make_command_string_internal().
print_for_command_head()
void print_for_command_head (FOR_COM * for_command)
Definition at line 603 of file print_cmd.c.
 {
   cprintf ("for %s in ", for_command->name->word);
   command_print_word_list (for_command->map_list, " ");
 }
References command_print_word_list(), cprintf(), for_com::map_list, for_com::name, and word_desc::word.
Referenced by execute_for_command(), and print_for_command().
print_function_def()
static void print_function_def (FUNCTION_DEF * func) static
Definition at line 1330 of file print_cmd.c.
 {
   COMMAND *cmdcopy;
   REDIRECT *func_redirects;
   func_redirects = NULL;
   /* When in posix mode, print functions as posix specifies them. */
   if (posixly_correct == 0)
     cprintf ("function %s () \n", func->name->word);
   else
     cprintf ("%s () \n", func->name->word);
   add_unwind_protect (reset_locals, 0);
   indent (indentation);
   cprintf ("{ \n");
   inside_function_def++;
   indentation += indentation_amount;
   cmdcopy = copy_command (func->command);
   if (cmdcopy->type == cm_group)
     {
       func_redirects = cmdcopy->redirects;
       cmdcopy->redirects = (REDIRECT *)NULL;
     }
   make_command_string_internal (cmdcopy->type == cm_group
                     ? cmdcopy->value.Group->command
                     : cmdcopy);
   PRINT_DEFERRED_HEREDOCS ("");
   remove_unwind_protect ();
   indentation -= indentation_amount;
   inside_function_def--;
   if (func_redirects)
     { /* { */
       newline ("} ");
       print_redirection_list (func_redirects);
       cmdcopy->redirects = func_redirects;
     }
   else
     {
       /* { */
       newline ("}");
       was_heredoc = 0;      /* not printing any here-documents now */
     }
   dispose_command (cmdcopy);
 }
References add_unwind_protect(), cm_group, copy_command(), cprintf(), dispose_command(), indent(), indentation, indentation_amount, inside_function_def, make_command_string_internal(), newline(), NULL, posixly_correct, PRINT_DEFERRED_HEREDOCS, print_redirection_list(), remove_unwind_protect(), reset_locals(), and was_heredoc.
Referenced by make_command_string_internal().
print_group_command()
static void print_group_command (GROUP_COM * group_command) static
Definition at line 696 of file print_cmd.c.
 {
   group_command_nesting++;
   cprintf ("{ ");
   if (inside_function_def == 0)
     skip_this_indent++;
   else
     {
       /* This is a group command { ... } inside of a function
      definition, and should be printed as a multiline group
      command, using the current indentation. */
       cprintf ("\n");
       indentation += indentation_amount;
     }
   make_command_string_internal (group_command->command);
   PRINT_DEFERRED_HEREDOCS ("");
   if (inside_function_def)
     {
       cprintf ("\n");
       indentation -= indentation_amount;
       indent (indentation);
     }
   else
     {
       semicolon ();
       cprintf (" ");
     }
   cprintf ("}");
   group_command_nesting--;
 }
References group_com::command, cprintf(), group_command_nesting, indent(), indentation, indentation_amount, inside_function_def, make_command_string_internal(), PRINT_DEFERRED_HEREDOCS, semicolon(), and skip_this_indent.
Referenced by make_command_string_internal().
print_heredoc_bodies()
static void print_heredoc_bodies (REDIRECT * heredocs) static
Definition at line 1019 of file print_cmd.c.
 {
   REDIRECT *hdtail;
   cprintf ("\n");
   for (hdtail = heredocs; hdtail; hdtail = hdtail->next)
     {
       print_heredoc_body (hdtail);
       cprintf ("\n");
     }
   was_heredoc = 1;
 }
References cprintf(), redirect::next, print_heredoc_body(), and was_heredoc.
Referenced by print_deferred_heredocs(), and print_redirection_list().
print_heredoc_body()
static void print_heredoc_body (REDIRECT * redirect) static
Definition at line 1148 of file print_cmd.c.
 {
   /* Here doc body */
   cprintf ("%s%s", redirect->redirectee.filename->word, redirect->here_doc_eof);
 }
References cprintf(), REDIRECTEE::filename, redirect::here_doc_eof, redirect::redirectee, and word_desc::word.
Referenced by print_heredoc_bodies(), and print_redirection().
print_heredoc_header()
static void print_heredoc_header (REDIRECT * redirect) static
Definition at line 1122 of file print_cmd.c.
 {
   int kill_leading;
   char *x;
   kill_leading = redirect->instruction == r_deblank_reading_until;
   /* Here doc header */
   if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redirect->redirector.filename->word);
   else if (redirect->redirector.dest != 0)
     cprintf ("%d", redirect->redirector.dest);
   /* If the here document delimiter is quoted, single-quote it. */
   if (redirect->redirectee.filename->flags & W_QUOTED)
     {
       x = sh_single_quote (redirect->here_doc_eof);
       cprintf ("<<%s%s", kill_leading ? "-" : "", x);
       free (x);
     }
   else
     cprintf ("<<%s%s", kill_leading ? "-" : "", redirect->here_doc_eof);
 }
References cprintf(), REDIRECTEE::dest, REDIRECTEE::filename, word_desc::flags, free, redirect::here_doc_eof, redirect::instruction, r_deblank_reading_until, REDIR_VARASSIGN, redirect::redirectee, redirect::redirector, redirect::rflags, sh_single_quote(), W_QUOTED, word_desc::word, and x.
Referenced by print_redirection(), and print_redirection_list().
print_heredocs()
static void print_heredocs (REDIRECT * heredocs) static
Definition at line 1004 of file print_cmd.c.
 {
   REDIRECT *hdtail;
   cprintf (" ");
   for (hdtail = heredocs; hdtail; hdtail = hdtail->next)
     {
       print_redirection (hdtail);
       cprintf ("\n");
     }
   was_heredoc = 1;
 }
References cprintf(), redirect::next, print_redirection(), and was_heredoc.
print_if_command()
static void print_if_command (IF_COM * if_command) static
Definition at line 819 of file print_cmd.c.
 {
   cprintf ("if ");
   skip_this_indent++;
   make_command_string_internal (if_command->test);
   semicolon ();
   cprintf (" then\n");
   indentation += indentation_amount;
   make_command_string_internal (if_command->true_case);
   PRINT_DEFERRED_HEREDOCS ("");
   indentation -= indentation_amount;
   if (if_command->false_case)
     {
       semicolon ();
       newline ("else\n");
       indentation += indentation_amount;
       make_command_string_internal (if_command->false_case);
       PRINT_DEFERRED_HEREDOCS ("");
       indentation -= indentation_amount;
     }
   semicolon ();
   newline ("fi");
 }
References cprintf(), if_com::false_case, indentation, indentation_amount, make_command_string_internal(), newline(), PRINT_DEFERRED_HEREDOCS, semicolon(), skip_this_indent, if_com::test, and if_com::true_case.
Referenced by make_command_string_internal().
print_redirection()
static void print_redirection (REDIRECT * redirect) static
Definition at line 1156 of file print_cmd.c.
 {
   int redirector, redir_fd;
   WORD_DESC *redirectee, *redir_word;
   redirectee = redirect->redirectee.filename;
   redir_fd = redirect->redirectee.dest;
   redir_word = redirect->redirector.filename;
   redirector = redirect->redirector.dest;
   switch (redirect->instruction)
     {
     case r_input_direction:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redir_word->word);
       else if (redirector != 0)
     cprintf ("%d", redirector);
       cprintf ("< %s", redirectee->word);
       break;
     case r_output_direction:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redir_word->word);
       else if (redirector != 1)
     cprintf ("%d", redirector);
       cprintf ("> %s", redirectee->word);
       break;
     case r_inputa_direction:    /* Redirection created by the shell. */
       cprintf ("&");
       break;
     case r_output_force:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redir_word->word);
       else if (redirector != 1)
     cprintf ("%d", redirector);
       cprintf (">| %s", redirectee->word);
       break;
     case r_appending_to:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redir_word->word);
       else if (redirector != 1)
     cprintf ("%d", redirector);
       cprintf (">> %s", redirectee->word);
       break;
     case r_input_output:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redir_word->word);
       else if (redirector != 1)
     cprintf ("%d", redirector);
       cprintf ("<> %s", redirectee->word);
       break;
     case r_deblank_reading_until:
     case r_reading_until:
       print_heredoc_header (redirect);
       cprintf ("\n");
       print_heredoc_body (redirect);
       break;
     case r_reading_string:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}", redir_word->word);
       else if (redirector != 0)
     cprintf ("%d", redirector);
 #if 0
       /* Don't need to check whether or not to requote, since original quotes
          are still intact.  The only thing that has happened is that $'...'
          has been replaced with 'expanded ...'. */
       if (ansic_shouldquote (redirect->redirectee.filename->word))
     {
       char *x;
       x = ansic_quote (redirect->redirectee.filename->word, 0, (int *)0);
       cprintf ("<<< %s", x);
       free (x);
     }
       else
 #endif
     cprintf ("<<< %s", redirect->redirectee.filename->word);
       break;
     case r_duplicating_input:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}<&%d", redir_word->word, redir_fd);
       else
     cprintf ("%d<&%d", redirector, redir_fd);
       break;
     case r_duplicating_output:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}>&%d", redir_word->word, redir_fd);
       else
     cprintf ("%d>&%d", redirector, redir_fd);
       break;
     case r_duplicating_input_word:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}<&%s", redir_word->word, redirectee->word);
       else if (redirector == 0)
     cprintf ("<&%s", redirectee->word);
       else
     cprintf ("%d<&%s", redirector, redirectee->word);
       break;
     case r_duplicating_output_word:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}>&%s", redir_word->word, redirectee->word);
       else if (redirector == 1)
     cprintf (">&%s", redirectee->word);
       else
     cprintf ("%d>&%s", redirector, redirectee->word);
       break;
     case r_move_input:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}<&%d-", redir_word->word, redir_fd);
       else
     cprintf ("%d<&%d-", redirector, redir_fd);
       break;
     case r_move_output:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}>&%d-", redir_word->word, redir_fd);
       else
     cprintf ("%d>&%d-", redirector, redir_fd);
       break;
     case r_move_input_word:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}<&%s-", redir_word->word, redirectee->word);
       else
     cprintf ("%d<&%s-", redirector, redirectee->word);
       break;
     case r_move_output_word:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}>&%s-", redir_word->word, redirectee->word);
       else
     cprintf ("%d>&%s-", redirector, redirectee->word);
       break;
     case r_close_this:
       if (redirect->rflags & REDIR_VARASSIGN)
     cprintf ("{%s}>&-", redir_word->word);
       else
     cprintf ("%d>&-", redirector);
       break;
     case r_err_and_out:
       cprintf ("&> %s", redirectee->word);
       break;
     case r_append_err_and_out:
       cprintf ("&>> %s", redirectee->word);
       break;
     }
 }
References ansic_quote(), ansic_shouldquote(), cprintf(), REDIRECTEE::dest, REDIRECTEE::filename, free, redirect::instruction, print_heredoc_body(), print_heredoc_header(), r_append_err_and_out, r_appending_to, r_close_this, r_deblank_reading_until, r_duplicating_input, r_duplicating_input_word, r_duplicating_output, r_duplicating_output_word, r_err_and_out, r_input_direction, r_input_output, r_inputa_direction, r_move_input, r_move_input_word, r_move_output, r_move_output_word, r_output_direction, r_output_force, r_reading_string, r_reading_until, REDIR_VARASSIGN, redirect::redirectee, redirect::redirector, redirect::rflags, word_desc::word, and x.
Referenced by print_heredocs(), and print_redirection_list().
print_redirection_list()
static void print_redirection_list (REDIRECT * redirects) static
Definition at line 1059 of file print_cmd.c.
 {
   REDIRECT *heredocs, *hdtail, *newredir;
   char *rw;
   heredocs = (REDIRECT *)NULL;
   hdtail = heredocs;
   was_heredoc = 0;
   while (redirects)
     {
       /* Defer printing the here document bodiess until we've printed the rest of the
          redirections, but print the headers in the order they're given.  */
       if (redirects->instruction == r_reading_until || redirects->instruction == r_deblank_reading_until)
     {
       newredir = copy_redirect (redirects);
       newredir->next = (REDIRECT *)NULL;
       print_heredoc_header (newredir);
       if (heredocs)
         {
           hdtail->next = newredir;
           hdtail = newredir;
         }
       else
         hdtail = heredocs = newredir;
     }
 #if 0
       /* Remove this heuristic now that the command printing code doesn't
      unconditionally put in the redirector file descriptor. */
       else if (redirects->instruction == r_duplicating_output_word && (redirects->flags & REDIR_VARASSIGN) == 0 && redirects->redirector.dest == 1)
     {
       /* Temporarily translate it as the execution code does. */
       rw = redirects->redirectee.filename->word;
       if (rw && *rw != '-' && DIGIT (*rw) == 0 && EXPCHAR (*rw) == 0)
         redirects->instruction = r_err_and_out;
       print_redirection (redirects);
       redirects->instruction = r_duplicating_output_word;
     }
 #endif
       else
     print_redirection (redirects);
       redirects = redirects->next;
       if (redirects)
     cprintf (" ");
     }
   /* Now that we've printed all the other redirections (on one line),
      print the here documents.  If we're printing a connection, we wait until
      we print the connector symbol, then we print the here document bodies */
   if (heredocs && printing_connection)
     deferred_heredocs = heredocs;
   else if (heredocs)
     {
       print_heredoc_bodies (heredocs);
       dispose_redirects (heredocs);
     }
 }
References copy_redirect(), cprintf(), deferred_heredocs, REDIRECTEE::dest, DIGIT, dispose_redirects(), EXPCHAR, REDIRECTEE::filename, redirect::flags, redirect::instruction, redirect::next, NULL, print_heredoc_bodies(), print_heredoc_header(), print_redirection(), printing_connection, r_deblank_reading_until, r_duplicating_output_word, r_err_and_out, r_reading_until, REDIR_VARASSIGN, redirect::redirectee, redirect::redirector, was_heredoc, and word_desc::word.
Referenced by make_command_string_internal(), named_function_string(), print_function_def(), and print_simple_command().
print_simple_command()
void print_simple_command (SIMPLE_COM * simple_command)
Definition at line 989 of file print_cmd.c.
 {
   if (simple_command->words)
     command_print_word_list (simple_command->words, " ");
   if (simple_command->redirects)
     {
       if (simple_command->words)
     cprintf (" ");
       print_redirection_list (simple_command->redirects);
     }
 }
References command_print_word_list(), cprintf(), print_redirection_list(), simple_com::redirects, and simple_com::words.
Referenced by execute_simple_command(), and make_command_string_internal().
print_until_command()
static void print_until_command (WHILE_COM * while_command) static
Definition at line 793 of file print_cmd.c.
 {
   print_until_or_while (while_command, "until");
 }
References print_until_or_while().
Referenced by make_command_string_internal().
print_until_or_while()
static void print_until_or_while (WHILE_COM * while_command, char * which) static
Definition at line 800 of file print_cmd.c.
 {
   cprintf ("%s ", which);
   skip_this_indent++;
   make_command_string_internal (while_command->test);
   PRINT_DEFERRED_HEREDOCS ("");
   semicolon ();
   cprintf (" do\n");    /* was newline ("do\n"); */
   indentation += indentation_amount;
   make_command_string_internal (while_command->action);
   PRINT_DEFERRED_HEREDOCS ("");
   indentation -= indentation_amount;
   semicolon ();
   newline ("done");
 }
References while_com::action, cprintf(), indentation, indentation_amount, make_command_string_internal(), newline(), PRINT_DEFERRED_HEREDOCS, semicolon(), skip_this_indent, and while_com::test.
Referenced by print_until_command(), and print_while_command().
print_while_command()
static void print_while_command (WHILE_COM * while_command) static
Definition at line 786 of file print_cmd.c.
 {
   print_until_or_while (while_command, "while");
 }
References print_until_or_while().
Referenced by make_command_string_internal().
print_word_list()
void print_word_list (WORD_LIST * list, char * separator)
Definition at line 391 of file print_cmd.c.
 {
   _print_word_list (list, separator, xprintf);
 }
References _print_word_list(), list(), separator, and xprintf().
Referenced by necho_builtin().
reset_locals()
static void reset_locals () static
Definition at line 1320 of file print_cmd.c.
 {
   inside_function_def = 0;
   indentation = 0;
   printing_connection = 0;
   deferred_heredocs = 0;
   printing_comsub = 0;
 }
References deferred_heredocs, indentation, inside_function_def, printing_comsub, and printing_connection.
Referenced by print_function_def().
semicolon()
static void semicolon () static
Definition at line 1512 of file print_cmd.c.
 {
   if (command_string_index > 0 &&
        (the_printed_command[command_string_index - 1] == '&' ||
     the_printed_command[command_string_index - 1] == '\n'))
     return;
   cprintf (";");
 }
References command_string_index, cprintf(), and the_printed_command.
Referenced by print_for_command(), print_group_command(), print_if_command(), and print_until_or_while().
the_printed_command_resize()
static void the_printed_command_resize (int length) static
Definition at line 1613 of file print_cmd.c.
 {
   if (the_printed_command == 0)
     {
       the_printed_command_size = (length + PRINTED_COMMAND_INITIAL_SIZE - 1) & ~(PRINTED_COMMAND_INITIAL_SIZE - 1);
       the_printed_command = (char *)xmalloc (the_printed_command_size);
       command_string_index = 0;
     }
   else if ((command_string_index + length) >= the_printed_command_size)
     {
       int new;
       new = command_string_index + length + 1;
       /* Round up to the next multiple of PRINTED_COMMAND_GROW_SIZE. */
       new = (new + PRINTED_COMMAND_GROW_SIZE - 1) & ~(PRINTED_COMMAND_GROW_SIZE - 1);
       the_printed_command_size = new;
       the_printed_command = (char *)xrealloc (the_printed_command, the_printed_command_size);
     }
 }
References command_string_index, PRINTED_COMMAND_GROW_SIZE, PRINTED_COMMAND_INITIAL_SIZE, the_printed_command, the_printed_command_size, xmalloc, and xrealloc.
Referenced by cprintf().
xprintf() [1/2]
static void xprintf () static
Referenced by print_word_list().
xprintf() [2/2]
static void xprintf (char * format, arg1 , arg2 , arg3 , arg4 , arg5) const static
Definition at line 1659 of file print_cmd.c.
 {
   printf (format, arg1, arg2, arg3, arg4, arg5);
 }
References format(), and printf.
xtrace_fdchk()
void xtrace_fdchk (int fd)
Definition at line 442 of file print_cmd.c.
 {
   if (fd == xtrace_fd)
     xtrace_reset ();
 }
References fd, xtrace_fd, and xtrace_reset().
Referenced by do_redirection_internal().
xtrace_init()
void xtrace_init ()
Definition at line 421 of file print_cmd.c.
 {
   xtrace_set (-1, stderr);
 }
References stderr, and xtrace_set().
Referenced by main().
xtrace_print_assignment()
void xtrace_print_assignment (char * name, char * value, int assign_list, int xflags)
Definition at line 519 of file print_cmd.c.
 {
   char *nval;
   CHECK_XTRACE_FP;
   if (xflags)
     fprintf (xtrace_fp, "%s", indirection_level_string ());
   /* VALUE should not be NULL when this is called. */
   if (*value == '\0' || assign_list)
     nval = value;
   else if (sh_contains_shell_metas (value))
     nval = sh_single_quote (value);
   else if (ansic_shouldquote (value))
     nval = ansic_quote (value, 0, (int *)0);
   else
     nval = value;
   if (assign_list)
     fprintf (xtrace_fp, "%s=(%s)\n", name, nval);
   else
     fprintf (xtrace_fp, "%s=%s\n", name, nval);
   if (nval != value)
     FREE (nval);
   fflush (xtrace_fp);
 }
References ansic_quote(), ansic_shouldquote(), CHECK_XTRACE_FP, fflush(), fprintf(), FREE, indirection_level_string(), sh_contains_shell_metas(), sh_single_quote(), value, and xtrace_fp.
Referenced by assign_in_env(), and do_assignment_internal().
xtrace_print_case_command_head()
void xtrace_print_case_command_head (CASE_COM * case_command)
Definition at line 741 of file print_cmd.c.
 {
   CHECK_XTRACE_FP;
   fprintf (xtrace_fp, "%s", indirection_level_string ());
   fprintf (xtrace_fp, "case %s in\n", case_command->word->word);
 }
References CHECK_XTRACE_FP, fprintf(), indirection_level_string(), word_desc::word, case_com::word, and xtrace_fp.
Referenced by execute_case_command().
xtrace_print_for_command_head()
void xtrace_print_for_command_head (FOR_COM * for_command)
Definition at line 611 of file print_cmd.c.
 {
   CHECK_XTRACE_FP;
   fprintf (xtrace_fp, "%s", indirection_level_string ());
   fprintf (xtrace_fp, "for %s in ", for_command->name->word);
   xtrace_print_word_list (for_command->map_list, 2);
 }
References CHECK_XTRACE_FP, fprintf(), indirection_level_string(), for_com::map_list, for_com::name, word_desc::word, xtrace_fp, and xtrace_print_word_list().
Referenced by execute_for_command().
xtrace_print_word_list()
void xtrace_print_word_list (WORD_LIST * list, int xtflags)
Definition at line 556 of file print_cmd.c.
 {
   WORD_LIST *w;
   char *t, *x;
   CHECK_XTRACE_FP;
   if (xtflags&1)
     fprintf (xtrace_fp, "%s", indirection_level_string ());
   for (w = list; w; w = w->next)
     {
       t = w->word->word;
       if (t == 0 || *t == '\0')
     fprintf (xtrace_fp, "''%s", w->next ? " " : "");
       else if (xtflags & 2)
     fprintf (xtrace_fp, "%s%s", t, w->next ? " " : "");
       else if (sh_contains_shell_metas (t))
     {
       x = sh_single_quote (t);
       fprintf (xtrace_fp, "%s%s", x, w->next ? " " : "");
       free (x);
     }
       else if (ansic_shouldquote (t))
     {
       x = ansic_quote (t, 0, (int *)0);
       fprintf (xtrace_fp, "%s%s", x, w->next ? " " : "");
       free (x);
     }
       else
     fprintf (xtrace_fp, "%s%s", t, w->next ? " " : "");
     }
   fprintf (xtrace_fp, "\n");
   fflush (xtrace_fp);
 }
References ansic_quote(), ansic_shouldquote(), CHECK_XTRACE_FP, fflush(), fprintf(), free, indirection_level_string(), list(), sh_contains_shell_metas(), sh_single_quote(), t, w, x, and xtrace_fp.
Referenced by execute_simple_command(), and xtrace_print_for_command_head().
xtrace_reset()
void xtrace_reset ()
Definition at line 427 of file print_cmd.c.
 {
   if (xtrace_fd >= 0 && xtrace_fp)
     {
       fflush (xtrace_fp);
       fclose (xtrace_fp);
     }
   else if (xtrace_fd >= 0)
     close (xtrace_fd);
   xtrace_fd = -1;
   xtrace_fp = stderr;
 }
References close(), fclose(), fflush(), stderr, xtrace_fd, and xtrace_fp.
Referenced by sv_xtracefd(), and xtrace_fdchk().
xtrace_set()
void xtrace_set (int fd, FILE * fp)
Definition at line 399 of file print_cmd.c.
 {
   if (fd >= 0 && sh_validfd (fd) == 0)
     {
       internal_error (_("xtrace_set: %d: invalid file descriptor"), fd);
       return;
     }
   if (fp == 0)
     {
       internal_error (_("xtrace_set: NULL file pointer"));
       return;
     }
   if (fd >= 0 && fileno (fp) != fd)
     internal_warning (_("xtrace fd (%d) != fileno xtrace fp (%d)"), fd, fileno (fp));
   xtrace_fd = fd;
   xtrace_fp = fp;
 }
References _, fd, fileno(), internal_error(), internal_warning(), sh_validfd(), xtrace_fd, and xtrace_fp.
Referenced by sv_xtracefd(), and xtrace_init().
Variable Documentation
command_string_index
int command_string_index = 0
Definition at line 111 of file print_cmd.c.
Referenced by cprintf(), execute_case_command(), execute_for_command(), execute_simple_command(), make_command_string(), named_function_string(), print_command(), semicolon(), and the_printed_command_resize().
deferred_heredocs
REDIRECT* deferred_heredocs static
Definition at line 133 of file print_cmd.c.
Referenced by make_command_string(), make_command_string_internal(), named_function_string(), print_deferred_heredocs(), print_redirection_list(), and reset_locals().
group_command_nesting
int group_command_nesting static
Definition at line 137 of file print_cmd.c.
Referenced by print_group_command().
indentation
int indentation static
Definition at line 56 of file print_cmd.c.
Referenced by make_command_string_internal(), named_function_string(), newline(), print_case_clauses(), print_for_command(), print_function_def(), print_group_command(), print_if_command(), print_until_or_while(), reset_locals(), and write_documentation().
indentation_amount
int indentation_amount = 4 static
Definition at line 57 of file print_cmd.c.
Referenced by named_function_string(), print_case_clauses(), print_for_command(), print_function_def(), print_group_command(), print_if_command(), and print_until_or_while().
indentation_size
int indentation_size static
Definition at line 1495 of file print_cmd.c.
Referenced by indent().
indentation_string
char* indentation_string static
Definition at line 1494 of file print_cmd.c.
Referenced by indent().
indirection_string
char* indirection_string = 0 static
Definition at line 140 of file print_cmd.c.
Referenced by indirection_level_string().
indirection_stringsiz
int indirection_stringsiz = 0 static
Definition at line 141 of file print_cmd.c.
Referenced by indirection_level_string().
inside_function_def
int inside_function_def static
Definition at line 128 of file print_cmd.c.
Referenced by make_command_string_internal(), named_function_string(), print_function_def(), print_group_command(), and reset_locals().
printing_comsub
int printing_comsub static
Definition at line 132 of file print_cmd.c.
Referenced by make_command_string_internal(), named_function_string(), print_comsub(), and reset_locals().
printing_connection
int printing_connection static
Definition at line 131 of file print_cmd.c.
Referenced by make_command_string_internal(), print_redirection_list(), and reset_locals().
skip_this_indent
int skip_this_indent static
Definition at line 129 of file print_cmd.c.
Referenced by make_command_string_internal(), print_group_command(), print_if_command(), and print_until_or_while().
the_printed_command
char* the_printed_command = (char *)NULL
Definition at line 109 of file print_cmd.c.
Referenced by cprintf(), execute_case_command(), execute_command_internal(), execute_for_command(), execute_simple_command(), make_command_string(), named_function_string(), semicolon(), and the_printed_command_resize().
the_printed_command_size
int the_printed_command_size = 0
Definition at line 110 of file print_cmd.c.
Referenced by the_printed_command_resize().
was_heredoc
int was_heredoc static
Definition at line 130 of file print_cmd.c.
Referenced by make_command_string(), make_command_string_internal(), named_function_string(), print_deferred_heredocs(), print_function_def(), print_heredoc_bodies(), print_heredocs(), and print_redirection_list().
xtrace_fd
int xtrace_fd = -1
Definition at line 113 of file print_cmd.c.
Referenced by xtrace_fdchk(), xtrace_reset(), and xtrace_set().
xtrace_fp
FILE* xtrace_fp = 0
Definition at line 114 of file print_cmd.c.
Referenced by xtrace_print_assignment(), xtrace_print_case_command_head(), xtrace_print_for_command_head(), xtrace_print_word_list(), xtrace_reset(), and xtrace_set().