Fennix Userspace: Userspace/apps/base/bash/lib/sh/gettimeofday.c File Reference
gettimeofday.c File Reference
#include "config.h"
#include "posixtime.h"
Functions
int gettimeofday (struct timeval *tv, void *tz)
Function Documentation
gettimeofday()
int gettimeofday (struct timeval * tv, void * tz)
Definition at line 29 of file gettimeofday.c.
 {
   tv->tv_sec = (time_t) time ((time_t *)0);
   tv->tv_usec = 0;
   return 0;
 }
References time(), timeval::tv_sec, and timeval::tv_usec.
Referenced by __gettimeofday_time32(), _rl_timeout_handle_sigalrm(), _rl_timeout_init(), assign_seconds(), genseed(), get_epochrealtime(), get_seconds(), main(), rl_timeout_remaining(), sh_seedrand(), shtimer_chktimeout(), shtimer_set(), strftime(), times(), and xgettimeofday().