Fennix: Userspace/apps/base/bash/examples/loadables/mkfifo.c File Reference
mkfifo.c File Reference
#include <config.h>
#include "bashtypes.h"
#include "posixstat.h"
#include <errno.h>
#include <stdio.h>
#include "bashansi.h"
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Macros
#define ISOCTAL(c) ((c) >= '0' && (c) <= '7')
Functions
int parse_symbolic_mode ()
int mkfifo_builtin (WORD_LIST *list)
Variables
int errno
static int original_umask
char * mkfifo_doc []
struct builtin mkfifo_struct
Macro Definition Documentation
ISOCTAL
#define ISOCTAL (c) ((c) >= '0' && (c) <= '7')
Definition at line 43 of file mkfifo.c.
Function Documentation
mkfifo_builtin()
int mkfifo_builtin (WORD_LIST * list)
Definition at line 50 of file mkfifo.c.
 {
   int opt, mflag, omode, rval, nmode, basemode;
   char *mode;
   WORD_LIST *l;
   mflag = 0;
   mode = (char *)NULL;
   reset_internal_getopt ();
   while ((opt = internal_getopt(list, "m:")) != -1)
     switch (opt)
       {
     case 'm':
       mflag = 1;
       mode = list_optarg;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage();
       return (EX_USAGE);
       }
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   basemode = S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH;
   if (mode == NULL)
     omode = basemode;
   else if (ISOCTAL (*mode)) /* octal number */
     {
       omode = read_octal (mode);
       if (omode < 0)
     {
       builtin_error ("invalid file mode: %s", mode);
       return (EXECUTION_FAILURE);
     }
     }
   else              /* symbolic mode */
     {
       /* initial bits are a=rwx; the mode argument modifies them */
       omode = parse_symbolic_mode (mode, basemode);
       if (omode < 0)
     {
       builtin_error ("invalid file mode: %s", mode);
       return (EXECUTION_FAILURE);
     }
     }
   /* Make the new mode */
   original_umask = umask (0);
   umask (original_umask);
   nmode = basemode & ~original_umask;
   /* Adjust new mode based on mode argument */
   nmode &= omode;
   for (rval = EXECUTION_SUCCESS, l = list; l; l = l->next)
     {
       if (mkfifo (l->word->word, nmode) < 0)
         {
           builtin_error ("cannot create FIFO `%s': %s", l->word->word, strerror (errno));
           rval = EXECUTION_FAILURE;
         }
     }
   return rval;
 }
References builtin_error(), builtin_usage(), CASE_HELPOPT, errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, internal_getopt(), ISOCTAL, l, list(), list_optarg, loptend, mflag, mkfifo(), NULL, opt, original_umask, parse_symbolic_mode(), read_octal(), reset_internal_getopt(), S_IRGRP, S_IROTH, S_IRUSR, S_IWGRP, S_IWOTH, S_IWUSR, strerror(), and umask().
parse_symbolic_mode()
int parse_symbolic_mode ()
Referenced by mkfifo_builtin().
Variable Documentation
errno
int errno extern
Referenced by mkfifo_builtin().
mkfifo_doc
char* mkfifo_doc[]
Initial value:
= {
    "Create FIFOs (named pipes).",
    "",
    "Make FIFOs.  Create the FIFOs named as arguments, in",
    "the order specified, using mode a=rw as modified by the current",
    "umask (see `help umask').  The -m option causes the file permission",
    "bits of the final FIFO to be MODE.  The MODE argument may be",
    "an octal number or a symbolic mode like that used by chmod(1).  If",
    "a symbolic mode is used, the operations are interpreted relative to",
    "an initial mode of \"a=rw\".  mkfifo returns 0 if the FIFOs are",
    "umask, plus write and search permissions for the owner.  mkdir",
    "created successfully, and non-zero if an error occurs.",
    (char *)NULL
}
Definition at line 124 of file mkfifo.c.
mkfifo_struct
struct builtin mkfifo_struct
Initial value:
= {
    "mkfifo",
    mkfifo_builtin,
    BUILTIN_ENABLED,
    mkfifo_doc,
    "mkfifo [-m mode] fifo_name [fifo_name ...]",
    0
}
Definition at line 124 of file mkfifo.c.
original_umask
int original_umask static
Definition at line 47 of file mkfifo.c.
Referenced by mkfifo_builtin().