Fennix: Userspace/mlibc/options/posix/include/bits/posix/posix_string.h File Reference
posix_string.h File Reference
#include <bits/posix/locale_t.h>
Functions
char * strdup (const char *string)
char * strndup (const char *, size_t)
size_t strnlen (const char *, size_t)
char * strtok_r (char *__restrict, const char *__restrict, char **__restrict)
char * strsep (char **stringp, const char *delim)
char * strsignal (int sig)
char * stpcpy (char *__restrict, const char *__restrict)
char * stpncpy (char *__restrict, const char *__restrict, size_t n)
void * memccpy (void *__restrict dest, const void *__restrict src, int c, size_t n)
int strcoll_l (const char *s1, const char *s2, locale_t locale)
char * strcasestr (const char *, const char *)
char * strdupa (const char *)
char * strndupa (const char *, size_t)
void * memrchr (const void *, int, size_t)
size_t strlcpy (char *d, const char *s, size_t n)
size_t strlcat (char *d, const char *s, size_t n)
Function Documentation
memccpy()
void* memccpy (void *__restrict dest, const void *__restrict src, int c, size_t n)
memrchr()
void* memrchr (const void * m, int c, size_t n)
Definition at line 151 of file posix_string.cpp.
{
     const unsigned char *s = (const unsigned char *)m;
     c = (unsigned char)c;
     while(n--) {
         if(s[n] == c)
             return (void *)(s + n);
     }
     return 0;
 }
References c, and n.
Referenced by main().
stpcpy()
char* stpcpy (char * __restrict, const char * __restrict)
stpncpy()
char* stpncpy (char * __restrict, const char * __restrict, size_t n)
strcasestr()
char* strcasestr (const char * s, const char * pattern)
Definition at line 123 of file posix_string.cpp.
{
     size_t plen = strlen(pattern);
     const char *p = s;
     while(*p) {
         // Need strncasecmp() to avoid checking past the end of a successful match.
         if(!strncasecmp(p, pattern, plen))
             return const_cast<char *>(p);
         ++p;
     }
     return nullptr;
 }
References p, strlen(), and strncasecmp().
strcoll_l()
int strcoll_l (const char * s1, const char * s2, locale_t locale)
Definition at line 475 of file posix_stdlib.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
strdup()
char* strdup (const char * string)
Definition at line 154 of file Convert.cpp.
 {
     char *OutBuffer = (char *)kmalloc(strlen((char *)String) + 1);
     strncpy(OutBuffer, String, strlen(String) + 1);
     return OutBuffer;
 }
References malloc(), memcpy, and strlen().
strdupa()
char* strdupa (const char *)
Definition at line 135 of file posix_string.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
strlcat()
size_t strlcat (char * d, const char * s, size_t n)
Definition at line 174 of file posix_string.cpp.
{
     size_t l = strnlen(d, n);
     if(l == n) {
         return l + strlen(s);
     }
     return l + strlcpy(d + l, s, n - l);
 }
References n, strlcpy(), strlen(), and strnlen().
Referenced by main().
strlcpy()
size_t strlcpy (char * d, const char * s, size_t n)
Definition at line 163 of file posix_string.cpp.
{
     char *d0 = d;
     if(!n--)
         goto finish;
     for(; n && (*d=*s); n--, s++, d++);
     *d = 0;
 finish:
     return d-d0 + strlen(s);
 }
References n, and strlen().
Referenced by main(), and strlcat().
strndup()
char* strndup (const char * string, size_t max_size)
Definition at line 21 of file posix_string.cpp.
{
     auto num_bytes = strnlen(string, max_size);
     char *new_string = (char *)malloc(num_bytes + 1);
     if(!new_string) // TODO: set errno
         return nullptr;
     memcpy(new_string, string, num_bytes);
     new_string[num_bytes] = 0;
     return new_string;
 }
References malloc(), max_size, memcpy, and strnlen().
Referenced by anonymous_namespace{grp-stubs.cpp}::extract_entry(), and anonymous_namespace{pwd-stubs.cpp}::extract_entry().
strndupa()
char* strndupa (const char * , size_t)
Definition at line 140 of file posix_string.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
strnlen()
size_t strnlen (const char * s, size_t n)
Definition at line 53 of file posix_string.cpp.
{
     size_t len = 0;
     while(len < n && s[len])
         ++len;
     return len;
 }
References n.
Referenced by fnmatch_internal(), openlog(), strlcat(), and strndup().
strsep()
char* strsep (char ** stringp, const char * delim)
Definition at line 60 of file posix_string.cpp.
{
     __ensure(m);
     auto tok = *m;
     if(!tok)
         return nullptr;
     // Replace the following delimiter by a null-terminator.
     // After this loop: *p is null iff we reached the end of the string.
     auto p = tok;
     while(*p && !strchr(del, *p))
         p++;
     if(*p) {
         *p = 0;
         *m = p + 1;
     }else{
         *m = nullptr;
     }
     return tok;
 }
References __ensure, p, and strchr().
strsignal()
char* strsignal (int sig)
Definition at line 82 of file posix_string.cpp.
{
     #define CASE_FOR(sigconst) case sigconst: s = #sigconst; break;
     const char *s;
     switch(sig) {
     CASE_FOR(SIGABRT)
     CASE_FOR(SIGFPE)
     CASE_FOR(SIGILL)
     CASE_FOR(SIGINT)
     CASE_FOR(SIGSEGV)
     CASE_FOR(SIGTERM)
     CASE_FOR(SIGPROF)
     CASE_FOR(SIGIO)
     CASE_FOR(SIGPWR)
     CASE_FOR(SIGALRM)
     CASE_FOR(SIGBUS)
     CASE_FOR(SIGCHLD)
     CASE_FOR(SIGCONT)
     CASE_FOR(SIGHUP)
     CASE_FOR(SIGKILL)
     CASE_FOR(SIGPIPE)
     CASE_FOR(SIGQUIT)
     CASE_FOR(SIGSTOP)
     CASE_FOR(SIGTSTP)
     CASE_FOR(SIGTTIN)
     CASE_FOR(SIGTTOU)
     CASE_FOR(SIGUSR1)
     CASE_FOR(SIGUSR2)
     CASE_FOR(SIGSYS)
     CASE_FOR(SIGTRAP)
     CASE_FOR(SIGURG)
     CASE_FOR(SIGVTALRM)
     CASE_FOR(SIGXCPU)
     CASE_FOR(SIGXFSZ)
     CASE_FOR(SIGWINCH)
     default:
         mlibc::infoLogger() << "mlibc: Unknown signal number " << sig << frg::endlog;
         s = "Unknown signal number";
     }
     return const_cast<char *>(s);
 }
References CASE_FOR, mlibc::infoLogger, SIGABRT, SIGALRM, SIGBUS, SIGCHLD, SIGCONT, SIGFPE, SIGHUP, SIGILL, SIGINT, SIGIO, SIGKILL, SIGPIPE, SIGPROF, SIGPWR, SIGQUIT, SIGSEGV, SIGSTOP, SIGSYS, SIGTERM, SIGTRAP, SIGTSTP, SIGTTIN, SIGTTOU, SIGURG, SIGUSR1, SIGUSR2, SIGVTALRM, SIGWINCH, SIGXCPU, and SIGXFSZ.
strtok_r()
char* strtok_r (char * __restrict, const char * __restrict, char ** __restrict)