Fennix Userspace: Userspace/apps/base/busybox/libbb/simplify_path.c File Reference
simplify_path.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC bb_simplify_abs_path_inplace (char *start)
char *FAST_FUNC bb_simplify_path (const char *path)
Function Documentation
bb_simplify_abs_path_inplace()
char* FAST_FUNC bb_simplify_abs_path_inplace (char * start)
Definition at line 11 of file simplify_path.c.
 {
     char *s, *p;
     p = s = start;
     do {
         if (*p == '/') {
             if (*s == '/') {  /* skip duplicate (or initial) slash */
                 continue;
             }
             if (*s == '.') {
                 if (s[1] == '/' || !s[1]) {  /* remove extra '.' */
                     continue;
                 }
                 if ((s[1] == '.') && (s[2] == '/' || !s[2])) {
                     ++s;
                     if (p > start) {
                         while (*--p != '/')  /* omit previous dir */
                             continue;
                     }
                     continue;
                 }
             }
         }
         *++p = *s;
     } while (*++s);
     if ((p == start) || (*p != '/')) {  /* not a trailing slash */
         ++p;  /* so keep last character */
     }
     *p = '\0';
     return p;
 }
References p, s, and start.
Referenced by bb_simplify_path(), and parse_conf().
bb_simplify_path()
char* FAST_FUNC bb_simplify_path (const char * path)
Definition at line 45 of file simplify_path.c.
 {
     char *s, *p;
     if (path[0] == '/')
         s = xstrdup(path);
     else {
         p = xrealloc_getcwd_or_warn(NULL);
         s = concat_path_file(p, path);
         free(p);
     }
     bb_simplify_abs_path_inplace(s);
     return s;
 }
References bb_simplify_abs_path_inplace(), concat_path_file(), free, NULL, p, s, xrealloc_getcwd_or_warn(), and xstrdup().
Referenced by devfsd_main(), mount_it_now(), mount_main(), read_config_file(), restore(), and singlemount().