Fennix: Userspace/libc/src/std/lib.c File Reference
lib.c File Reference
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "../mem/liballoc_1_1.h"
Functions
void abort (void)
int atexit (void(*function)(void))
void exit (int status)
int atoi (const char *nptr)
char * getenv (const char *name)
void * malloc (size_t Size)
The standard function.
void * realloc (void *Address, size_t Size)
The standard function.
void * calloc (size_t Count, size_t Size)
The standard function.
void free (void *Address)
The standard function.
Variables
char ** environ = NULL
Function Documentation
abort()
void abort (void)
Definition at line 7 of file lib.c.
 {
     while (1)
         ;
 }
atexit()
int atexit (void(*)(void) function)
Definition at line 13 of file lib.c.
 {
     return 0;
 }
atoi()
int atoi (const char * nptr)
Definition at line 24 of file lib.c.
 {
     // uint64_t Length = strlen((char *)nptr);
     uint64_t Length = 0;
     if (nptr)
         while (nptr[Length] != '\0')
             ++Length;
     uint64_t OutBuffer = 0;
     uint64_t Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (nptr[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References Length, and strlen().
Referenced by ParseConfig(), and CrashHandler::UserInput().
exit()
void exit (int status)
Definition at line 18 of file lib.c.
 {
     while (1)
         ;
 }
getenv()
char* getenv (const char * name)
Definition at line 43 of file lib.c.
 {
     char **env = environ;
     if (env == NULL)
         return NULL;
     size_t len = strlen(name);
     while (*env != NULL)
     {
         if ((strncmp(*env, name, len) == 0) && ((*env)[len] == '='))
             return &(*env)[len + 1];
         ++env;
     }
 }
References environ, NULL, strlen(), and strncmp().
Variable Documentation
environ
char** environ = NULL
Definition at line 41 of file lib.c.
Referenced by getenv().