Fennix: Userspace/libc/include/stdlib.h File Reference
stdlib.h File Reference
#include <stddef.h>
Macros
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
Functions
void abort (void)
int atexit (void(*function)(void))
void exit (int status)
int atoi (const char *nptr)
char * getenv (const char *name)
void * malloc (size_t Size)
The standard function.
void * realloc (void *Address, size_t Size)
The standard function.
void * calloc (size_t Count, size_t Size)
The standard function.
void free (void *Address)
The standard function.
int system (const char *command)
double atof (const char *nptr)
void perror (const char *s)
Macro Definition Documentation
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 11 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 12 of file stdlib.h.
Function Documentation
abort()
void abort (void)
Definition at line 7 of file lib.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(0), "D"(-0xAB057)
                          : "rcx", "r11", "memory");
     while (1)
         ;
 }
References mlibc::panicLogger, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SIG_DFL, SIG_SETMASK, SIG_UNBLOCK, SIGABRT, sigaddset(), sigdelset(), sigemptyset(), sigfillset(), mlibc::sys_sigaction(), and mlibc::sys_sigprocmask().
Referenced by __assert_fail(), main(), and signal_handler().
atexit()
int atexit (void(*)(void) function)
Definition at line 18 of file lib.c.
 {
     return 1;
 }
atof()
double atof (const char * nptr)
Definition at line 548 of file Convert.cpp.
 {
     // Originally from https://github.com/GaloisInc/minlibc/blob/master/atof.c
     /*
     Copyright (c) 2014 Galois Inc.
     All rights reserved.
     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:
       * Redistributions of source code must retain the above copyright
         notice, this list of conditions and the following disclaimer.
       * Redistributions in binary form must reproduce the above copyright
         notice, this list of conditions and the following disclaimer in
         the documentation and/or other materials provided with the
         distribution.
       * Neither the name of Galois, Inc. nor the names of its contributors
         may be used to endorse or promote products derived from this
         software without specific prior written permission.
     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
     TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
     PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
     OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     */
     double a = 0.0;
     int e = 0;
     int c;
     while ((c = *String++) != '\0' && isdigit(c))
     {
         a = a * 10.0 + (c - '0');
     }
     if (c == '.')
     {
         while ((c = *String++) != '\0' && isdigit(c))
         {
             a = a * 10.0 + (c - '0');
             e = e - 1;
         }
     }
     if (c == 'e' || c == 'E')
     {
         int sign = 1;
         int i = 0;
         c = *String++;
         if (c == '+')
             c = *String++;
         else if (c == '-')
         {
             c = *String++;
             sign = -1;
         }
         while (isdigit(c))
         {
             i = i * 10 + (c - '0');
             c = *String++;
         }
         e += i * sign;
     }
     while (e > 0)
     {
         a *= 10.0;
         e--;
     }
     while (e < 0)
     {
         a *= 0.1;
         e++;
     }
     return a;
 }
atoi()
int atoi (const char * nptr)
Definition at line 535 of file Convert.cpp.
 {
     uint64_t Length = strlen((char *)String);
     int OutBuffer = 0;
     int Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (String[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
exit()
void exit (int status)
Definition at line 23 of file lib.c.
 {
     _exit(status);
 }
References __mlibc_do_finalize(), _exit(), mlibc::status, and mlibc::sys_exit().
Referenced by __mlibc_entry(), D_DoomMain(), D_Endoom(), error(), error_at_line(), I_Error(), I_Quit(), LoadResponseFile(), main(), prevent_atforks(), and socket_setup().
getenv()
char* getenv (const char * name)
Definition at line 46 of file lib.c.
 {
     char **env = environ;
     if (env == NULL)
         return NULL;
     size_t len = strlen(name);
     while (*env != NULL)
     {
         if ((strncmp(*env, name, len) == 0) && ((*env)[len] == '='))
             return &(*env)[len + 1];
         ++env;
     }
 }
References env, environ, len, name, NULL, strlen(), and strncmp().
Referenced by BuildIWADDirList(), mlibc::envEnabled(), execvpe(), expand_tilde(), getlogin(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), M_TempFile(), main(), secure_getenv(), and we_askshell().
perror()
void perror (const char * s)
Definition at line 32 of file put.c.
 { fputs(s, stderr); }
References fputs(), and stderr.
Referenced by main(), run_cmd(), and vwarn().
system()
int system (const char * command)
Definition at line 69 of file lib.c.
 {
     return -1;
 }
Referenced by Main(), main(), ZenityAvailable(), and ZenityErrorBox().