Fennix: Userspace/musl/src/stat/fchmod.c File Reference
fchmod.c File Reference
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include "syscall.h"
Functions
int fchmod (int fd, mode_t mode)
Function Documentation
fchmod()
int fchmod (int fd, mode_t mode)
Definition at line 6 of file fchmod.c.
 {
     int ret = __syscall(SYS_fchmod, fd, mode);
     if (ret != -EBADF || __syscall(SYS_fcntl, fd, F_GETFD) < 0)
         return __syscall_ret(ret);
     char buf[15+3*sizeof(int)];
     __procfdname(buf, fd);
 #ifdef SYS_chmod
     return syscall(SYS_chmod, buf, mode);
 #else
     return syscall(SYS_fchmodat, AT_FDCWD, buf, mode);
 #endif
 }
References __procfdname(), __syscall, __syscall_ret(), AT_FDCWD, buf, EBADF, F_GETFD, fd, and syscall().
Referenced by convert(), copy_tempfile(), here_document_to_fd(), logdir_close(), logdir_open(), login_main(), lpd_main(), mesg_main(), open_tty(), patch_main(), rotate(), sed_main(), and update_passwd().