Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_misc.h File Reference
m_misc.h File Reference
#include <stdio.h>
#include <stdarg.h>
#include "doomtype.h"
Functions
boolean M_WriteFile (char *name, void *source, int length)
int M_ReadFile (char *name, byte **buffer)
void M_MakeDirectory (char *dir)
char * M_TempFile (char *s)
boolean M_FileExists (char *file)
long M_FileLength (FILE *handle)
boolean M_StrToInt (const char *str, int *result)
void M_ExtractFileBase (char *path, char *dest)
void M_ForceUppercase (char *text)
char * M_StrCaseStr (char *haystack, char *needle)
char * M_StringDuplicate (const char *orig)
boolean M_StringCopy (char *dest, const char *src, size_t dest_size)
boolean M_StringConcat (char *dest, const char *src, size_t dest_size)
char * M_StringReplace (const char *haystack, const char *needle, const char *replacement)
char * M_StringJoin (const char *s,...)
boolean M_StringStartsWith (const char *s, const char *prefix)
boolean M_StringEndsWith (const char *s, const char *suffix)
int M_vsnprintf (char *buf, size_t buf_len, const char *s, va_list args)
int M_snprintf (char *buf, size_t buf_len, const char *s,...)
char * M_OEMToUTF8 (const char *ansi)
Function Documentation
M_ExtractFileBase()
void M_ExtractFileBase (char * path, char * dest)
Definition at line 198 of file m_misc.c.
 {
     char *src;
     char *filename;
     int length;
     src = path + strlen(path) - 1;
     // back up until a \ or the start
     while (src != path && *(src - 1) != DIR_SEPARATOR)
     {
     src--;
     }
     filename = src;
     // Copy up to eight characters
     // Note: Vanilla Doom exits with an error if a filename is specified
     // with a base of more than eight characters.  To remove the 8.3
     // filename limit, instead we simply truncate the name.
     length = 0;
     memset(dest, 0, 8);
     while (*src != '\0' && *src != '.')
     {
         if (length >= 8)
         {
             printf("Warning: Truncated '%s' lump name to '%.8s'.\n",
                    filename, dest);
             break;
         }
     dest[length++] = toupper((int)*src++);
     }
 }
References DIR_SEPARATOR, memset(), printf(), strlen(), and toupper.
Referenced by W_AddFile().
M_FileExists()
boolean M_FileExists (char * file)
Definition at line 66 of file m_misc.c.
 {
     FILE *fstream;
     fstream = fopen(filename, "r");
     if (fstream != NULL)
     {
         fclose(fstream);
         return true;
     }
     else
     {
         // If we can't open because the file is a directory, the
         // "file" exists at least!
         return errno == EISDIR;
     }
 }
References EISDIR, errno, fclose(), fopen(), and NULL.
Referenced by CheckDirectoryHasIWAD(), D_FindWADByName(), and V_ScreenShot().
M_FileLength()
long M_FileLength (FILE * handle)
Definition at line 90 of file m_misc.c.
 {
     long savedpos;
     long length;
     // save the current position in the file
     savedpos = ftell(handle);
     // jump to the end and find the length
     fseek(handle, 0, SEEK_END);
     length = ftell(handle);
     // go back to the old location
     fseek(handle, savedpos, SEEK_SET);
     return length;
 }
References fseek(), ftell(), SEEK_END, and SEEK_SET.
Referenced by LoadResponseFile(), M_ReadFile(), and W_StdC_OpenFile().
M_ForceUppercase()
void M_ForceUppercase (char * text)
Definition at line 243 of file m_misc.c.
 {
     char *p;
     for (p = text; *p != '\0'; ++p)
     {
         *p = toupper(*p);
     }
 }
References p, and toupper.
M_MakeDirectory()
void M_MakeDirectory (char * dir)
Definition at line 55 of file m_misc.c.
 {
 #ifdef _WIN32
     mkdir(path);
 #else
     mkdir(path, 0755);
 #endif
 }
References mkdir().
Referenced by M_GetSaveGameDir(), and M_SetConfigDir().
M_OEMToUTF8()
char* M_OEMToUTF8 (const char * ansi)
M_ReadFile()
int M_ReadFile (char * name, byte ** buffer)
Definition at line 136 of file m_misc.c.
 {
     FILE *handle;
     int count, length;
     byte *buf;
     handle = fopen(name, "rb");
     if (handle == NULL)
     I_Error ("Couldn't read file %s", name);
     // find the size of the file by seeking to the end and
     // reading the current position
     length = M_FileLength(handle);
     buf = Z_Malloc (length, PU_STATIC, NULL);
     count = fread(buf, 1, length, handle);
     fclose (handle);
     if (count < length)
     I_Error ("Couldn't read file %s", name);
     *buffer = buf;
     return length;
 }
References buf, count, fclose(), fopen(), fread(), I_Error(), M_FileLength(), name, NULL, PU_STATIC, and Z_Malloc().
M_snprintf()
int M_snprintf (char * buf, size_t buf_len, const char * s, ...)
Definition at line 508 of file m_misc.c.
 {
     va_list args;
     int result;
     va_start(args, s);
     result = M_vsnprintf(buf, buf_len, s, args);
     va_end(args);
     return result;
 }
References args, buf, M_vsnprintf(), mlibc::result, va_end(), and va_start().
Referenced by AM_Responder(), D_BindVariables(), DemoVersionDescription(), G_RecordDemo(), G_Ticker(), GetGameName(), I_BindJoystickVariables(), M_BindChatControls(), P_ReadSaveGameHeader(), P_SaveGameFile(), P_WriteSaveGameHeader(), S_ChangeMusic(), ST_Responder(), V_ScreenShot(), and ZenityErrorBox().
M_StrCaseStr()
char* M_StrCaseStr (char * haystack, char * needle)
Definition at line 259 of file m_misc.c.
 {
     unsigned int haystack_len;
     unsigned int needle_len;
     unsigned int len;
     unsigned int i;
     haystack_len = strlen(haystack);
     needle_len = strlen(needle);
     if (haystack_len < needle_len)
     {
         return NULL;
     }
     len = haystack_len - needle_len;
     for (i = 0; i <= len; ++i)
     {
         if (!strncasecmp(haystack + i, needle, needle_len))
         {
             return haystack + i;
         }
     }
     return NULL;
 }
References i, NULL, strlen(), and mlibc::strncasecmp().
M_StringConcat()
boolean M_StringConcat (char * dest, const char * src, size_t dest_size)
Definition at line 394 of file m_misc.c.
 {
     size_t offset;
     offset = strlen(dest);
     if (offset > dest_size)
     {
         offset = dest_size;
     }
     return M_StringCopy(dest + offset, src, dest_size - offset);
 }
References M_StringCopy(), offset, and strlen().
Referenced by M_StringJoin().
M_StringCopy()
boolean M_StringCopy (char * dest, const char * src, size_t dest_size)
Definition at line 373 of file m_misc.c.
 {
     size_t len;
     if (dest_size >= 1)
     {
         dest[dest_size - 1] = '\0';
         strncpy(dest, src, dest_size - 1);
     }
     else
     {
         return false;
     }
     len = strlen(dest);
     return src[len] == '\0';
 }
References strlen(), and strncpy().
Referenced by ChecksumAddLump(), D_DoomMain(), G_DoSaveGame(), G_LoadGame(), G_SaveGame(), G_Ticker(), HU_Responder(), M_Drawer(), M_LoadSelect(), M_ReadSaveStrings(), M_Responder(), M_SaveSelect(), M_StringConcat(), M_StringJoin(), M_StringReplace(), PlayerQuitGame(), R_InitTextures(), and WI_loadUnloadData().
M_StringDuplicate()
char* M_StringDuplicate (const char * orig)
Definition at line 292 of file m_misc.c.
 {
     char *result;
     result = strdup(orig);
     if (result == NULL)
     {
         I_Error("Failed to duplicate string (length %i)\n",
                 strlen(orig));
     }
     return result;
 }
References I_Error(), NULL, mlibc::result, strdup(), and strlen().
M_StringEndsWith()
boolean M_StringEndsWith (const char * s, const char * suffix)
Definition at line 417 of file m_misc.c.
 {
     return strlen(s) >= strlen(suffix)
         && strcmp(s + strlen(s) - strlen(suffix), suffix) == 0;
 }
References strcmp(), and strlen().
Referenced by D_DoomMain().
M_StringJoin()
char* M_StringJoin (const char * s, ...)
Definition at line 426 of file m_misc.c.
 {
     char *result;
     const char *v;
     va_list args;
     size_t result_len;
     result_len = strlen(s) + 1;
     va_start(args, s);
     for (;;)
     {
         v = va_arg(args, const char *);
         if (v == NULL)
         {
             break;
         }
         result_len += strlen(v);
     }
     va_end(args);
     result = malloc(result_len);
     if (result == NULL)
     {
         I_Error("M_StringJoin: Failed to allocate new string.");
         return NULL;
     }
     M_StringCopy(result, s, result_len);
     va_start(args, s);
     for (;;)
     {
         v = va_arg(args, const char *);
         if (v == NULL)
         {
             break;
         }
         M_StringConcat(result, v, result_len);
     }
     va_end(args);
     return result;
 }
References args, I_Error(), M_StringConcat(), M_StringCopy(), malloc(), NULL, mlibc::result, strlen(), va_arg, va_end(), and va_start().
Referenced by CheckDirectoryHasIWAD(), D_FindWADByName(), M_GetSaveGameDir(), M_LoadDefaults(), M_TempFile(), and P_TempSaveGameFile().
M_StringReplace()
char* M_StringReplace (const char * haystack, const char * needle, const char * replacement)
Definition at line 311 of file m_misc.c.
 {
     char *result, *dst;
     const char *p;
     size_t needle_len = strlen(needle);
     size_t result_len, dst_len;
     // Iterate through occurrences of 'needle' and calculate the size of
     // the new string.
     result_len = strlen(haystack) + 1;
     p = haystack;
     for (;;)
     {
         p = strstr(p, needle);
         if (p == NULL)
         {
             break;
         }
         p += needle_len;
         result_len += strlen(replacement) - needle_len;
     }
     // Construct new string.
     result = malloc(result_len);
     if (result == NULL)
     {
         I_Error("M_StringReplace: Failed to allocate new string");
         return NULL;
     }
     dst = result; dst_len = result_len;
     p = haystack;
     while (*p != '\0')
     {
         if (!strncmp(p, needle, needle_len))
         {
             M_StringCopy(dst, replacement, dst_len);
             p += needle_len;
             dst += strlen(replacement);
             dst_len -= strlen(replacement);
         }
         else
         {
             *dst = *p;
             ++dst; --dst_len;
             ++p;
         }
     }
     *dst = '\0';
     return result;
 }
References I_Error(), M_StringCopy(), malloc(), NULL, p, mlibc::result, strlen(), strncmp(), and strstr().
M_StringStartsWith()
boolean M_StringStartsWith (const char * s, const char * prefix)
Definition at line 409 of file m_misc.c.
 {
     return strlen(s) > strlen(prefix)
         && strncmp(s, prefix, strlen(prefix)) == 0;
 }
References strlen(), and strncmp().
M_StrToInt()
boolean M_StrToInt (const char * str, int * result)
Definition at line 190 of file m_misc.c.
 {
     return sscanf(str, " 0x%x", result) == 1
         || sscanf(str, " 0X%x", result) == 1
         || sscanf(str, " 0%o", result) == 1
         || sscanf(str, " %d", result) == 1;
 }
References sscanf().
Referenced by DonutOverrun(), I_GetMemoryValue(), and SpechitOverrun().
M_TempFile()
char* M_TempFile (char * s)
Definition at line 167 of file m_misc.c.
 {
     char *tempdir;
 #ifdef _WIN32
     // Check the TEMP environment variable to find the location.
     tempdir = getenv("TEMP");
     if (tempdir == NULL)
     {
         tempdir = ".";
     }
 #else
     // In Unix, just use /tmp.
     tempdir = "/tmp";
 #endif
     return M_StringJoin(tempdir, DIR_SEPARATOR_S, s, NULL);
 }
References DIR_SEPARATOR_S, getenv(), M_StringJoin(), and NULL.
Referenced by G_DoSaveGame().
M_vsnprintf()
int M_vsnprintf (char * buf, size_t buf_len, const char * s, va_list args)
Definition at line 482 of file m_misc.c.
 {
     int result;
     if (buf_len < 1)
     {
         return 0;
     }
     // Windows (and other OSes?) has a vsnprintf() that doesn't always
     // append a trailing \0. So we must do it, and write into a buffer
     // that is one byte shorter; otherwise this function is unsafe.
     result = vsnprintf(buf, buf_len, s, args);
     // If truncated, change the final char in the buffer to a \0.
     // A negative result indicates a truncated buffer on Windows.
     if (result < 0 || result >= buf_len)
     {
         buf[buf_len - 1] = '\0';
         result = buf_len - 1;
     }
     return result;
 }
References buf, mlibc::result, and vsnprintf().
Referenced by I_Error(), and M_snprintf().
M_WriteFile()
boolean M_WriteFile (char * name, void * source, int length)
Definition at line 112 of file m_misc.c.
 {
     FILE *handle;
     int count;
     handle = fopen(name, "wb");
     if (handle == NULL)
     return false;
     count = fwrite(source, 1, length, handle);
     fclose(handle);
     if (count < length)
     return false;
     return true;
 }
References count, fclose(), fopen(), fwrite(), name, and NULL.
Referenced by G_CheckDemoStatus(), and WritePCXfile().