Fennix Userspace: Userspace/apps/base/busybox/util-linux/rtcwake.c File Reference
rtcwake.c File Reference
#include "libbb.h"
#include "rtc_.h"
Macros
#define SYS_RTC_PATH "/sys/class/rtc/%s/device/power/wakeup"
#define SYS_POWER_PATH "/sys/power/state"
#define RTCWAKE_OPT_AUTO 0x01
#define RTCWAKE_OPT_LOCAL 0x02
#define RTCWAKE_OPT_UTC 0x04
#define RTCWAKE_OPT_DEVICE 0x08
#define RTCWAKE_OPT_SUSPEND_MODE 0x10
#define RTCWAKE_OPT_SECONDS 0x20
#define RTCWAKE_OPT_TIME 0x40
Functions
static NOINLINE bool may_wakeup (const char *rtcname)
static NOINLINE void setup_alarm (int fd, time_t *wakeup, time_t rtc_time)
int rtcwake_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
RTCWAKE_OPT_AUTO
#define RTCWAKE_OPT_AUTO 0x01
Definition at line 111 of file rtcwake.c.
RTCWAKE_OPT_DEVICE
#define RTCWAKE_OPT_DEVICE 0x08
Definition at line 114 of file rtcwake.c.
RTCWAKE_OPT_LOCAL
#define RTCWAKE_OPT_LOCAL 0x02
Definition at line 112 of file rtcwake.c.
RTCWAKE_OPT_SECONDS
#define RTCWAKE_OPT_SECONDS 0x20
Definition at line 116 of file rtcwake.c.
RTCWAKE_OPT_SUSPEND_MODE
#define RTCWAKE_OPT_SUSPEND_MODE 0x10
Definition at line 115 of file rtcwake.c.
RTCWAKE_OPT_TIME
#define RTCWAKE_OPT_TIME 0x40
Definition at line 117 of file rtcwake.c.
RTCWAKE_OPT_UTC
#define RTCWAKE_OPT_UTC 0x04
Definition at line 113 of file rtcwake.c.
SYS_POWER_PATH
#define SYS_POWER_PATH "/sys/power/state"
Definition at line 51 of file rtcwake.c.
SYS_RTC_PATH
#define SYS_RTC_PATH "/sys/class/rtc/%s/device/power/wakeup"
Definition at line 50 of file rtcwake.c.
Function Documentation
may_wakeup()
static NOINLINE bool may_wakeup (const char * rtcname) static
Definition at line 53 of file rtcwake.c.
 {
     ssize_t ret;
     char buf[128];
     /* strip "/dev/" from the rtcname here */
     rtcname = skip_dev_pfx(rtcname);
     snprintf(buf, sizeof(buf), SYS_RTC_PATH, rtcname);
     ret = open_read_close(buf, buf, sizeof(buf));
     if (ret < 0)
         return false;
     /* wakeup events could be disabled or not supported */
     return is_prefixed_with(buf, "enabled\n") != NULL;
 }
References buf, is_prefixed_with(), NULL, open_read_close(), skip_dev_pfx(), snprintf(), and SYS_RTC_PATH.
Referenced by rtcwake_main().
rtcwake_main()
int rtcwake_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 120 of file rtcwake.c.
 {
     unsigned opt;
     const char *rtcname = NULL;
     const char *suspend = "standby";
     const char *opt_seconds;
     const char *opt_time;
     time_t rtc_time;
     time_t sys_time;
     time_t alarm_time = alarm_time;
     unsigned seconds = seconds; /* for compiler */
     int utc = -1;
     int fd;
 #if ENABLE_LONG_OPTS
     static const char rtcwake_longopts[] ALIGN1 =
         "auto\0"    No_argument "a"
         "local\0"   No_argument "l"
         "utc\0"     No_argument "u"
         "device\0"  Required_argument "d"
         "mode\0"    Required_argument "m"
         "seconds\0" Required_argument "s"
         "time\0"    Required_argument "t"
         ;
 #endif
     opt = getopt32long(argv,
             /* Must have -s or -t, exclusive */
             "^alud:m:s:t:" "\0" "s:t:s--t:t--s", rtcwake_longopts,
             &rtcname, &suspend, &opt_seconds, &opt_time);
     /* this is the default
     if (opt & RTCWAKE_OPT_AUTO)
         utc = -1;
     */
     if (opt & (RTCWAKE_OPT_UTC | RTCWAKE_OPT_LOCAL))
         utc = opt & RTCWAKE_OPT_UTC;
     if (opt & RTCWAKE_OPT_SECONDS) {
         /* alarm time, seconds-to-sleep (relative) */
         seconds = xatou(opt_seconds);
     } else {
         /* RTCWAKE_OPT_TIME */
         /* alarm time, time_t (absolute, seconds since 1/1 1970 UTC) */
         if (sizeof(alarm_time) <= sizeof(long))
             alarm_time = xatol(opt_time);
         else
             alarm_time = xatoll(opt_time);
     }
     if (utc == -1)
         utc = rtc_adjtime_is_utc();
     /* the rtcname is relative to /dev */
     xchdir("/dev");
     /* this RTC must exist and (if we'll sleep) be wakeup-enabled */
     fd = rtc_xopen(&rtcname, O_RDONLY);
     if (strcmp(suspend, "on") != 0)
         if (!may_wakeup(rtcname))
             bb_error_msg_and_die("%s not enabled for wakeup events", rtcname);
     /* relative or absolute alarm time, normalized to time_t */
     sys_time = time(NULL);
     {
         struct tm tm_time;
         rtc_read_tm(&tm_time, fd);
         rtc_time = rtc_tm2time(&tm_time, utc);
     }
     if (opt & RTCWAKE_OPT_TIME) {
         /* Correct for RTC<->system clock difference */
         alarm_time += rtc_time - sys_time;
         if (alarm_time < rtc_time)
             /*
              * Compat message text.
              * I'd say "RTC time is already ahead of ..." instead.
              */
             bb_error_msg_and_die("time doesn't go backward to %s", ctime(&alarm_time));
     } else
         alarm_time = rtc_time + seconds + 1;
     setup_alarm(fd, &alarm_time, rtc_time);
     sync();
 #if 0 /*debug*/
     printf("sys_time: %s", ctime(&sys_time));
     printf("rtc_time: %s", ctime(&rtc_time));
 #endif
     printf("wakeup from \"%s\" at %s", suspend, ctime(&alarm_time));
     fflush_all();
     usleep(10 * 1000);
     if (strcmp(suspend, "on") != 0)
         xopen_xwrite_close(SYS_POWER_PATH, suspend);
     else {
         /* "fake" suspend ... we'll do the delay ourselves */
         unsigned long data;
         do {
             ssize_t ret = safe_read(fd, &data, sizeof(data));
             if (ret < 0) {
                 bb_simple_perror_msg("rtc read");
                 break;
             }
         } while (!(data & RTC_AF));
     }
     xioctl(fd, RTC_AIE_OFF, 0);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     return EXIT_SUCCESS;
 }
References ALIGN1, argv, bb_error_msg_and_die(), bb_simple_perror_msg(), close(), ctime(), EXIT_SUCCESS, fd, fflush_all(), getopt32long, may_wakeup(), No_argument, NULL, O_RDONLY, opt, printf(), Required_argument, rtc_adjtime_is_utc(), RTC_AF, RTC_AIE_OFF, rtc_read_tm(), rtc_tm2time(), rtc_xopen(), RTCWAKE_OPT_LOCAL, RTCWAKE_OPT_SECONDS, RTCWAKE_OPT_TIME, RTCWAKE_OPT_UTC, safe_read(), setup_alarm(), strcmp, sync(), SYS_POWER_PATH, time(), usleep(), xatol(), xatou(), xchdir(), xioctl, and xopen_xwrite_close().
setup_alarm()
static NOINLINE void setup_alarm (int fd, time_t * wakeup, time_t rtc_time) static
Definition at line 70 of file rtcwake.c.
 {
     struct tm *ptm;
     struct linux_rtc_wkalrm wake;
     /* The wakeup time is in POSIX time (more or less UTC).
      * Ideally RTCs use that same time; but PCs can't do that
      * if they need to boot MS-Windows.  Messy...
      *
      * When running in utc mode this process's timezone is UTC,
      * so we'll pass a UTC date to the RTC.
      *
      * Else mode is local so the time given to the RTC
      * will instead use the local time zone.
      */
     ptm = localtime(wakeup);
     wake.time.tm_sec = ptm->tm_sec;
     wake.time.tm_min = ptm->tm_min;
     wake.time.tm_hour = ptm->tm_hour;
     wake.time.tm_mday = ptm->tm_mday;
     wake.time.tm_mon = ptm->tm_mon;
     wake.time.tm_year = ptm->tm_year;
     /* wday, yday, and isdst fields are unused by Linux */
     wake.time.tm_wday = -1;
     wake.time.tm_yday = -1;
     wake.time.tm_isdst = -1;
     /* many rtc alarms only support up to 24 hours from 'now',
      * so use the "more than 24 hours" request only if we must
      */
     if ((rtc_time + (24 * 60 * 60)) > *wakeup) {
         xioctl(fd, RTC_ALM_SET, &wake.time);
         xioctl(fd, RTC_AIE_ON, 0);
     } else {
         /* avoid an extra AIE_ON call */
         wake.enabled = 1;
         xioctl(fd, RTC_WKALM_SET, &wake);
     }
 }
References linux_rtc_wkalrm::enabled, fd, localtime(), RTC_AIE_ON, RTC_ALM_SET, RTC_WKALM_SET, linux_rtc_wkalrm::time, linux_rtc_time::tm_hour, tm::tm_hour, linux_rtc_time::tm_isdst, linux_rtc_time::tm_mday, tm::tm_mday, linux_rtc_time::tm_min, tm::tm_min, linux_rtc_time::tm_mon, tm::tm_mon, linux_rtc_time::tm_sec, tm::tm_sec, linux_rtc_time::tm_wday, linux_rtc_time::tm_yday, linux_rtc_time::tm_year, tm::tm_year, and xioctl.
Referenced by rtcwake_main().