Fennix: Lynx/FennixLoader/Debugger.cpp File Reference
Debugger.cpp File Reference
#include <debug.h>
#include <printf.h>
Namespaces
SysDbg
Enumerations
enum vga_color {
VGA_COLOR_BLACK = 0 , VGA_COLOR_BLUE = 1 , VGA_COLOR_GREEN = 2 , VGA_COLOR_CYAN = 3 ,
VGA_COLOR_RED = 4 , VGA_COLOR_MAGENTA = 5 , VGA_COLOR_BROWN = 6 , VGA_COLOR_LIGHT_GREY = 7 ,
VGA_COLOR_DARK_GREY = 8 , VGA_COLOR_LIGHT_BLUE = 9 , VGA_COLOR_LIGHT_GREEN = 10 , VGA_COLOR_LIGHT_CYAN = 11 ,
VGA_COLOR_LIGHT_RED = 12 , VGA_COLOR_LIGHT_MAGENTA = 13 , VGA_COLOR_LIGHT_BROWN = 14 , VGA_COLOR_WHITE = 15 ,
VGA_COLOR_BLACK = 0 , VGA_COLOR_BLUE = 1 , VGA_COLOR_GREEN = 2 , VGA_COLOR_CYAN = 3 ,
VGA_COLOR_RED = 4 , VGA_COLOR_MAGENTA = 5 , VGA_COLOR_BROWN = 6 , VGA_COLOR_LIGHT_GREY = 7 ,
VGA_COLOR_DARK_GREY = 8 , VGA_COLOR_LIGHT_BLUE = 9 , VGA_COLOR_LIGHT_GREEN = 10 , VGA_COLOR_LIGHT_CYAN = 11 ,
VGA_COLOR_LIGHT_RED = 12 , VGA_COLOR_LIGHT_MAGENTA = 13 , VGA_COLOR_LIGHT_BROWN = 14 , VGA_COLOR_WHITE = 15
}
Functions
void terminal_setcolor (uint8_t color)
void putchar (char c)
static void WritePrefix (DebugLevel Level, const char *File, int Line, const char *Function)
NIF void SysDbg::Write (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbg::WriteLine (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
void SysDbgWrite (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
void SysDbgWriteLine (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
Variables
bool DoNotWriteOnScreen
Enumeration Type Documentation
vga_color
enum vga_color
Enumerator
VGA_COLOR_BLACK
VGA_COLOR_BLUE
VGA_COLOR_GREEN
VGA_COLOR_CYAN
VGA_COLOR_RED
VGA_COLOR_MAGENTA
VGA_COLOR_BROWN
VGA_COLOR_LIGHT_GREY
VGA_COLOR_DARK_GREY
VGA_COLOR_LIGHT_BLUE
VGA_COLOR_LIGHT_GREEN
VGA_COLOR_LIGHT_CYAN
VGA_COLOR_LIGHT_RED
VGA_COLOR_LIGHT_MAGENTA
VGA_COLOR_LIGHT_BROWN
VGA_COLOR_WHITE
VGA_COLOR_BLACK
VGA_COLOR_BLUE
VGA_COLOR_GREEN
VGA_COLOR_CYAN
VGA_COLOR_RED
VGA_COLOR_MAGENTA
VGA_COLOR_BROWN
VGA_COLOR_LIGHT_GREY
VGA_COLOR_DARK_GREY
VGA_COLOR_LIGHT_BLUE
VGA_COLOR_LIGHT_GREEN
VGA_COLOR_LIGHT_CYAN
VGA_COLOR_LIGHT_RED
VGA_COLOR_LIGHT_MAGENTA
VGA_COLOR_LIGHT_BROWN
VGA_COLOR_WHITE
Definition at line 4 of file Debugger.cpp.
 {
     VGA_COLOR_BLACK = 0,
     VGA_COLOR_BLUE = 1,
     VGA_COLOR_GREEN = 2,
     VGA_COLOR_CYAN = 3,
     VGA_COLOR_RED = 4,
     VGA_COLOR_MAGENTA = 5,
     VGA_COLOR_BROWN = 6,
     VGA_COLOR_LIGHT_GREY = 7,
     VGA_COLOR_DARK_GREY = 8,
     VGA_COLOR_LIGHT_BLUE = 9,
     VGA_COLOR_LIGHT_GREEN = 10,
     VGA_COLOR_LIGHT_CYAN = 11,
     VGA_COLOR_LIGHT_RED = 12,
     VGA_COLOR_LIGHT_MAGENTA = 13,
     VGA_COLOR_LIGHT_BROWN = 14,
     VGA_COLOR_WHITE = 15,
 };
Function Documentation
putchar()
void putchar (char c)
Definition at line 226 of file Kernel.cpp.
 {
     if (Display)
         Display->Print(c, PutCharBufferIndex);
     else
         UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write(c);
 }
Referenced by SysDbgWriteLine().
SysDbgWrite()
void SysDbgWrite (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 97 of file Debugger.cpp.
 {
     WritePrefix(Level, File, Line, Function);
     va_list args;
     va_start(args, Format);
     vprintf(Format, args);
     va_end(args);
 }
References args, Level, va_end(), va_start(), vprintf(), and WritePrefix().
SysDbgWriteLine()
void SysDbgWriteLine (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 107 of file Debugger.cpp.
 {
     WritePrefix(Level, File, Line, Function);
     va_list args;
     va_start(args, Format);
     vprintf(Format, args);
     va_end(args);
     putchar('\n');
 }
References args, Level, putchar(), va_end(), va_start(), vprintf(), and WritePrefix().
terminal_setcolor()
void terminal_setcolor (uint8_t color)
Definition at line 75 of file ega.c.
 {
     terminal_color = color;
 }
References terminal_color.
Referenced by WritePrefix().
WritePrefix()
static void WritePrefix (DebugLevel Level, const char * File, int Line, const char * Function) inline static
Definition at line 28 of file Debugger.cpp.
 {
     const char *DbgLvlString;
     switch (Level)
     {
     case DebugLevelError:
         DbgLvlString = "ERROR";
         terminal_setcolor(VGA_COLOR_RED);
         break;
     case DebugLevelWarning:
         DbgLvlString = "WARN ";
         terminal_setcolor(VGA_COLOR_BROWN);
         break;
     case DebugLevelInfo:
         DbgLvlString = "INFO ";
         terminal_setcolor(VGA_COLOR_LIGHT_GREY);
         break;
     case DebugLevelDebug:
         DbgLvlString = "DEBUG";
         terminal_setcolor(VGA_COLOR_GREEN);
         break;
     case DebugLevelTrace:
         DbgLvlString = "TRACE";
         terminal_setcolor(VGA_COLOR_DARK_GREY);
         break;
     case DebugLevelFixme:
         DbgLvlString = "FIXME";
         terminal_setcolor(VGA_COLOR_LIGHT_RED);
         break;
     case DebugLevelUbsan:
     {
         DbgLvlString = "UBSAN";
         printf("%s|%s: ", DbgLvlString, Function);
         terminal_setcolor(VGA_COLOR_LIGHT_RED);
         return;
     }
     default:
         DbgLvlString = "UNKNW";
         terminal_setcolor(VGA_COLOR_WHITE);
         break;
     }
     DoNotWriteOnScreen = true;
     printf("%s|%s->%s:%d: ", DbgLvlString, File, Function, Line);
     DoNotWriteOnScreen = false;
 }
References DebugLevelDebug, DebugLevelError, DebugLevelFixme, DebugLevelInfo, DebugLevelTrace, DebugLevelUbsan, DebugLevelWarning, DoNotWriteOnScreen, Level, printf, terminal_setcolor(), VGA_COLOR_BROWN, VGA_COLOR_DARK_GREY, VGA_COLOR_GREEN, VGA_COLOR_LIGHT_GREY, VGA_COLOR_LIGHT_RED, VGA_COLOR_RED, and VGA_COLOR_WHITE.
Referenced by SysDbgWrite(), and SysDbgWriteLine().
Variable Documentation
DoNotWriteOnScreen
bool DoNotWriteOnScreen extern
Definition at line 13 of file Loader.cpp.
Referenced by putchar(), and WritePrefix().