Fennix Userspace: Userspace/apps/base/busybox/coreutils/paste.c File Reference
paste.c File Reference
#include "libbb.h"
Macros
#define PASTE_OPT_DELIMITERS (1 << 0)
#define PASTE_OPT_SEPARATE (1 << 1)
Functions
static void paste_files (FILE **files, int file_cnt, char *delims, int del_cnt)
static void paste_files_separate (FILE **files, char *delims, int del_cnt)
int paste_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
PASTE_OPT_DELIMITERS
#define PASTE_OPT_DELIMITERS (1 << 0)
Definition at line 103 of file paste.c.
PASTE_OPT_SEPARATE
#define PASTE_OPT_SEPARATE (1 << 1)
Definition at line 104 of file paste.c.
Function Documentation
paste_files()
static void paste_files (FILE ** files, int file_cnt, char * delims, int del_cnt) static
Definition at line 35 of file paste.c.
 {
     char *line;
     char delim;
     int active_files = file_cnt;
     int i;
     while (active_files > 0) {
         int del_idx = 0;
         for (i = 0; i < file_cnt; ++i) {
             if (files[i] == NULL)
                 continue;
             line = xmalloc_fgetline(files[i]);
             if (!line) {
                 fclose_if_not_stdin(files[i]);
                 files[i] = NULL;
                 --active_files;
                 continue;
             }
             fputs_stdout(line);
             free(line);
             delim = '\n';
             if (i != file_cnt - 1) {
                 delim = delims[del_idx++];
                 if (del_idx == del_cnt)
                     del_idx = 0;
             }
             if (delim != '\0')
                 fputc(delim, stdout);
         }
     }
 }
References fclose_if_not_stdin(), files, fputc, fputs_stdout(), free, i, line, NULL, stdout, and xmalloc_fgetline().
Referenced by paste_main().
paste_files_separate()
static void paste_files_separate (FILE ** files, char * delims, int del_cnt) static
Definition at line 70 of file paste.c.
 {
     char *line, *next_line;
     char delim;
     int i;
     for (i = 0; files[i]; ++i) {
         int del_idx = 0;
         line = NULL;
         while ((next_line = xmalloc_fgetline(files[i])) != NULL) {
             if (line) {
                 fputs_stdout(line);
                 free(line);
                 delim = delims[del_idx++];
                 if (del_idx == del_cnt)
                     del_idx = 0;
                 if (delim != '\0')
                     fputc(delim, stdout);
             }
             line = next_line;
         }
         if (line) {
             /* coreutils adds \n even if this is a final line
              * of the last file and it was not \n-terminated.
              */
             printf("%s\n", line);
             free(line);
         }
         fclose_if_not_stdin(files[i]);
     }
 }
References fclose_if_not_stdin(), files, fputc, fputs_stdout(), free, i, line, next_line(), NULL, printf(), stdout, and xmalloc_fgetline().
Referenced by paste_main().
paste_main()
int paste_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 107 of file paste.c.
 {
     char *delims = (char*)"\t";
     int del_cnt = 1;
     unsigned opt;
     int i;
     opt = getopt32(argv, "d:s", &delims);
     argv += optind;
     if (opt & PASTE_OPT_DELIMITERS) {
         if (!delims[0])
             bb_simple_error_msg_and_die("-d '' is not supported");
         /* unknown mappings are not changed: "\z" -> '\\' 'z' */
         /* trailing backslash, if any, is preserved */
         del_cnt = strcpy_and_process_escape_sequences(delims, delims) - delims;
         /* note: handle NUL properly (do not stop at it!): try -d'\t\0\t' */
     }
     if (!argv[0])
         (--argv)[0] = (char*) "-";
     for (i = 0; argv[i]; ++i) {
         argv[i] = (void*) fopen_or_warn_stdin(argv[i]);
         if (!argv[i])
             xfunc_die();
     }
     if (opt & PASTE_OPT_SEPARATE)
         paste_files_separate((FILE**)argv, delims, del_cnt);
     else
         paste_files((FILE**)argv, i, delims, del_cnt);
     fflush_stdout_and_exit(0);
 }
References argv, bb_simple_error_msg_and_die(), fflush_stdout_and_exit(), fopen_or_warn_stdin(), getopt32(), i, opt, optind, paste_files(), paste_files_separate(), PASTE_OPT_DELIMITERS, PASTE_OPT_SEPARATE, strcpy_and_process_escape_sequences(), and xfunc_die().