Fennix Userspace: Userspace/mlibc/options/linux/generic/sys-inotify-stubs.cpp File Reference
sys-inotify-stubs.cpp File Reference
#include <errno.h>
#include <sys/inotify.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/linux-sysdeps.hpp>
Functions
int inotify_init (void)
int inotify_init1 (int flags)
int inotify_add_watch (int ifd, const char *path, uint32_t mask)
int inotify_rm_watch (int ifd, int wd)
Function Documentation
inotify_add_watch()
int inotify_add_watch (int ifd, const char * path, uint32_t mask)
Definition at line 29 of file sys-inotify-stubs.cpp.
{
     int wd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_add_watch, -1);
     if(int e = mlibc::sys_inotify_add_watch(ifd, path, mask, &wd); e) {
         errno = e;
         return -1;
     }
     return wd;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_add_watch().
inotify_init()
int inotify_init (void)
Definition at line 9 of file sys-inotify-stubs.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_create, -1);
     if(int e = mlibc::sys_inotify_create(0, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_create().
inotify_init1()
int inotify_init1 (int flags)
Definition at line 19 of file sys-inotify-stubs.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_create, -1);
     if(int e = mlibc::sys_inotify_create(flags, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_create().
inotify_rm_watch()
int inotify_rm_watch (int ifd, int wd)
Definition at line 39 of file sys-inotify-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_rm_watch, -1);
     if(int e = mlibc::sys_inotify_rm_watch(ifd, wd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_rm_watch().