Fennix Userspace: Userspace/apps/base/busybox/miscutils/flashcp.c File Reference
flashcp.c File Reference
#include "libbb.h"
#include <mtd/mtd-user.h>
Macros
#define MTD_DEBUG 0
#define OPT_v (1 << 0)
#define BUFSIZE (4 * 1024)
#define filename argv[0]
#define devicename argv[1]
Functions
static void progress (int mode, uoff_t count, uoff_t total)
static void progress_newline (void)
int flashcp_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BUFSIZE
#define BUFSIZE (4 * 1024)
Definition at line 35 of file flashcp.c.
devicename
#define devicename argv[1]
filename
#define filename argv[0]
MTD_DEBUG
#define MTD_DEBUG 0
Definition at line 31 of file flashcp.c.
OPT_v
#define OPT_v (1 << 0)
Definition at line 33 of file flashcp.c.
Function Documentation
flashcp_main()
int flashcp_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 60 of file flashcp.c.
 {
     int fd_f, fd_d; /* input file and mtd device file descriptors */
     int i;
     uoff_t erase_count;
     struct mtd_info_user mtd;
     struct erase_info_user e;
     struct stat statb;
 //  const char *filename, *devicename;
     RESERVE_CONFIG_UBUFFER(buf, BUFSIZE);
     RESERVE_CONFIG_UBUFFER(buf2, BUFSIZE);
     /*opts =*/ getopt32(argv, "^" "v" "\0" "=2"/*exactly 2 non-option args: file,dev*/);
     argv += optind;
 //  filename = *argv++;
 //  devicename = *argv;
 #define filename argv[0]
 #define devicename argv[1]
     /* open input file and mtd device and do sanity checks */
     fd_f = xopen(filename, O_RDONLY);
     fstat(fd_f, &statb);
     fd_d = xopen(devicename, O_SYNC | O_RDWR);
 #if !MTD_DEBUG
     if (ioctl(fd_d, MEMGETINFO, &mtd) < 0) {
         bb_error_msg_and_die("%s is not a MTD flash device", devicename);
     }
     if (statb.st_size > mtd.size) {
         bb_error_msg_and_die("%s bigger than %s", filename, devicename);
     }
 #else
     mtd.erasesize = 64 * 1024;
 #endif
     /* always erase a complete block */
     erase_count = (uoff_t)(statb.st_size + mtd.erasesize - 1) / mtd.erasesize;
     /* erase 1 block at a time to be able to give verbose output */
     e.length = mtd.erasesize;
 #if 0
 /* (1) bloat
  * (2) will it work for multi-gigabyte devices?
  * (3) worse wrt error detection granularity
  */
     /* optimization: if not verbose, erase in one go */
     if (!opts) { // if (!(opts & OPT_v))
         e.length = mtd.erasesize * erase_count;
         erase_count = 1;
     }
 #endif
     e.start = 0;
     for (i = 1; i <= erase_count; i++) {
         progress(-1, i, erase_count);
 #if !MTD_DEBUG
         if (ioctl(fd_d, MEMERASE, &e) < 0) {
             bb_perror_msg_and_die("erase error at 0x%llx on %s",
                 (long long)e.start, devicename);
         }
 #else
         usleep(100*1000);
 #endif
         e.start += mtd.erasesize;
     }
     progress_newline();
     /* doing this outer loop gives significantly smaller code
      * than doing two separate loops for writing and verifying */
     for (i = 0; i <= 1; i++) {
         uoff_t done;
         unsigned count;
         xlseek(fd_f, 0, SEEK_SET);
         xlseek(fd_d, 0, SEEK_SET);
         done = 0;
         count = BUFSIZE;
         while (1) {
             uoff_t rem;
             progress(i, done / 1024, (uoff_t)statb.st_size / 1024);
             rem = statb.st_size - done;
             if (rem == 0)
                 break;
             if (rem < BUFSIZE)
                 count = rem;
             xread(fd_f, buf, count);
             if (i == 0) {
                 int ret;
                 if (count < BUFSIZE)
                     memset((char*)buf + count, 0, BUFSIZE - count);
                 errno = 0;
                 ret = full_write(fd_d, buf, BUFSIZE);
                 if (ret != BUFSIZE) {
                     bb_perror_msg_and_die("write error at 0x%"OFF_FMT"x on %s, "
                         "write returned %d",
                         done, devicename, ret);
                 }
             } else { /* i == 1 */
                 xread(fd_d, buf2, count);
                 if (memcmp(buf, buf2, count) != 0) {
                     bb_error_msg_and_die("verification mismatch at 0x%"OFF_FMT"x", done);
                 }
             }
             done += count;
         }
         progress_newline();
     }
     /* we won't come here if there was an error */
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_perror_msg_and_die(), buf, BUFSIZE, count, devicename, done, errno, EXIT_SUCCESS, filename, fstat(), full_write(), getopt32(), i, ioctl(), memcmp(), memset(), O_RDONLY, O_RDWR, O_SYNC, OFF_FMT, optind, progress(), progress_newline(), RESERVE_CONFIG_UBUFFER, SEEK_SET, stat::st_size, usleep(), xlseek(), xopen(), and xread().
progress()
static void progress (int mode, uoff_t count, uoff_t total) static
Definition at line 37 of file flashcp.c.
 {
     uoff_t percent;
     if (!option_mask32) //if (!(option_mask32 & OPT_v))
         return;
     percent = count * 100;
     if (total)
         percent = (unsigned) (percent / total);
     printf("\r%s: %"OFF_FMT"u/%"OFF_FMT"u (%u%%) ",
         (mode < 0) ? "Erasing block" : ((mode == 0) ? "Writing kb" : "Verifying kb"),
         count, total, (unsigned)percent);
     fflush_all();
 }
References count, fflush_all(), OFF_FMT, option_mask32, percent, printf(), and total.
Referenced by execute(), flashcp_main(), fsck_main(), and wait_one().
progress_newline()
static void progress_newline (void) static
Definition at line 52 of file flashcp.c.
 {
     if (!option_mask32) //if (!(option_mask32 & OPT_v))
         return;
     bb_putchar('\n');
 }
References bb_putchar(), and option_mask32.
Referenced by flashcp_main().