Fennix Userspace: Userspace/musl/include/stdlib.h File Reference
stdlib.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct div_t
struct ldiv_t
struct lldiv_t
Macros
#define NULL ((void*)0)
#define __NEED_size_t
#define __NEED_wchar_t
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define MB_CUR_MAX (__ctype_get_mb_cur_max())
#define RAND_MAX (0x7fffffff)
Functions
int atoi (const char *)
long atol (const char *)
long long atoll (const char *)
double atof (const char *)
float strtof (const char *__restrict, char **__restrict)
double strtod (const char *__restrict, char **__restrict)
long double strtold (const char *__restrict, char **__restrict)
long strtol (const char *__restrict, char **__restrict, int)
unsigned long strtoul (const char *__restrict, char **__restrict, int)
long long strtoll (const char *__restrict, char **__restrict, int)
unsigned long long strtoull (const char *__restrict, char **__restrict, int)
int rand (void)
void srand (unsigned)
void * malloc (size_t)
The standard function.
void * calloc (size_t, size_t)
The standard function.
void * realloc (void *, size_t)
The standard function.
void free (void *)
The standard function.
void * aligned_alloc (size_t, size_t)
_Noreturn void abort (void)
int atexit (void(*)(void))
_Noreturn void exit (int)
_Noreturn void _Exit (int)
int at_quick_exit (void(*)(void))
_Noreturn void quick_exit (int)
char * getenv (const char *)
int system (const char *)
void * bsearch (const void *, const void *, size_t, size_t, int(*)(const void *, const void *))
void qsort (void *, size_t, size_t, int(*)(const void *, const void *))
int abs (int)
long labs (long)
long long llabs (long long)
div_t div (int, int)
ldiv_t ldiv (long, long)
lldiv_t lldiv (long long, long long)
int mblen (const char *, size_t)
int mbtowc (wchar_t *__restrict, const char *__restrict, size_t)
int wctomb (char *, wchar_t)
size_t mbstowcs (wchar_t *__restrict, const char *__restrict, size_t)
size_t wcstombs (char *__restrict, const wchar_t *__restrict, size_t)
size_t __ctype_get_mb_cur_max (void)
Data Structure Documentation
div_t
struct div_t
Definition at line 64 of file stdlib.h.
Data Fields
int quot
int rem
ldiv_t
struct ldiv_t
Definition at line 65 of file stdlib.h.
Data Fields
long quot
long rem
lldiv_t
struct lldiv_t
Definition at line 66 of file stdlib.h.
Data Fields
long long quot
long long rem
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 18 of file stdlib.h.
__NEED_wchar_t
#define __NEED_wchar_t
Definition at line 19 of file stdlib.h.
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 78 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 79 of file stdlib.h.
MB_CUR_MAX
#define MB_CUR_MAX (__ctype_get_mb_cur_max())
Definition at line 82 of file stdlib.h.
NULL
#define NULL ((void*)0)
Definition at line 15 of file stdlib.h.
RAND_MAX
#define RAND_MAX (0x7fffffff)
Definition at line 84 of file stdlib.h.
Function Documentation
__ctype_get_mb_cur_max()
size_t __ctype_get_mb_cur_max (void)
Definition at line 4 of file __ctype_get_mb_cur_max.c.
 {
     return MB_CUR_MAX;
 }
References MB_CUR_MAX.
_Exit()
_Noreturn void _Exit (int ec)
Definition at line 4 of file _Exit.c.
 {
     __syscall(SYS_exit_group, ec);
     for (;;) __syscall(SYS_exit, ec);
 }
References __syscall.
Referenced by _exit(), abort(), exit(), and quick_exit().
abort()
_Noreturn void abort (void)
Definition at line 9 of file lib.c.
 {
     syscall1(sys_Exit, -0xAB057);
     while (1)
         ;
 }
References __abort_lock, __block_all_sigs(), __pthread_self, __syscall, _Exit(), _NSIG, a_crash, LOCK, SIG_DFL, SIGABRT, and SIGKILL.
abs()
int abs (int i)
Definition at line 26 of file fcts.c.
 { return i < 0 ? -i : i; }
References i.
Referenced by ltoa().
aligned_alloc()
void* aligned_alloc (size_t align, size_t len)
Definition at line 5 of file aligned_alloc.c.
 {
     if ((align & -align) != align) {
         errno = EINVAL;
         return 0;
     }
     if (len > SIZE_MAX - align || align >= (1ULL<<31)*UNIT) {
         errno = ENOMEM;
         return 0;
     }
     if (DISABLE_ALIGNED_ALLOC) {
         errno = ENOMEM;
         return 0;
     }
     if (align <= UNIT) align = UNIT;
     unsigned char *p = malloc(len + align - UNIT);
     if (!p)
         return 0;
     struct meta *g = get_meta(p);
     int idx = get_slot_index(p);
     size_t stride = get_stride(g);
     unsigned char *start = g->mem->storage + stride*idx;
     unsigned char *end = g->mem->storage + stride*(idx+1) - IB;
     size_t adj = -(uintptr_t)p & (align-1);
     if (!adj) {
         set_size(p, end, len);
         return p;
     }
     p += adj;
     uint32_t offset = (size_t)(p-g->mem->storage)/UNIT;
     if (offset <= 0xffff) {
         *(uint16_t *)(p-2) = offset;
         p[-4] = 0;
     } else {
         // use a 32-bit offset if 16-bit doesn't fit. for this,
         // 16-bit field must be zero, [-4] byte nonzero.
         *(uint16_t *)(p-2) = 0;
         *(uint32_t *)(p-8) = offset;
         p[-4] = 1;
     }
     p[-3] = idx;
     set_size(p, end, len);
     // store offset to aligned enframing. this facilitates cycling
     // offset and also iteration of heap for debugging/measurement.
     // for extreme overalignment it won't fit but these are classless
     // allocations anyway.
     *(uint16_t *)(start - 2) = (size_t)(p-start)/UNIT;
     start[-3] = 7<<5;
     return p;
 }
References __aligned_alloc_replaced, __bin_chunk(), __malloc_replaced, c, C_INUSE, DISABLE_ALIGNED_ALLOC, EINVAL, end, ENOMEM, errno, g, get_meta(), get_slot_index(), get_stride(), IB, idx, IS_MMAPPED, malloc, mem, MEM_TO_CHUNK, n, NEXT_CHUNK, offset, p, set_size(), SIZE_ALIGN, SIZE_MAX, start, t, and UNIT.
Referenced by memalign(), and posix_memalign().
at_quick_exit()
int at_quick_exit (void(*)(void) func)
Definition at line 25 of file at_quick_exit.c.
 {
     int r = 0;
     LOCK(lock);
     if (count == 32) r = -1;
     else funcs[count++] = func;
     UNLOCK(lock);
     return r;
 }
References count, funcs, LOCK, lock, and UNLOCK.
atexit()
int atexit (void(*)(void) function)
Definition at line 16 of file lib.c.
 {
     return 1;
 }
References __cxa_atexit(), and call().
atof()
double atof (const char * nptr)
Definition at line 72 of file lib.c.
 {
     // FIXME: This is a very bad implementation of atof.
     uint64_t Length = strlen((char *)nptr);
     if (nptr)
         while (nptr[Length] != '\0')
             ++Length;
     double OutBuffer = 0;
     double Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (nptr[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References s, and strtod().
atoi()
int atoi (const char * nptr)
Definition at line 26 of file lib.c.
 {
     uint64_t Length = strlen((char *)nptr);
     if (nptr)
         while (nptr[Length] != '\0')
             ++Length;
     uint64_t OutBuffer = 0;
     uint64_t Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (nptr[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References isdigit, isspace, n, and s.
atol()
long atol (const char * s)
Definition at line 4 of file atol.c.
 {
     long n=0;
     int neg=0;
     while (isspace(*s)) s++;
     switch (*s) {
     case '-': neg=1;
     case '+': s++;
     }
     /* Compute n as a negative number to avoid overflow on LONG_MIN */
     while (isdigit(*s))
         n = 10*n - (*s++ - '0');
     return neg ? n : -n;
 }
References isdigit, isspace, n, and s.
atoll()
long long atoll (const char * s)
Definition at line 4 of file atoll.c.
 {
     long long n=0;
     int neg=0;
     while (isspace(*s)) s++;
     switch (*s) {
     case '-': neg=1;
     case '+': s++;
     }
     /* Compute n as a negative number to avoid overflow on LLONG_MIN */
     while (isdigit(*s))
         n = 10*n - (*s++ - '0');
     return neg ? n : -n;
 }
References isdigit, isspace, n, and s.
Referenced by process_action(), and wait_for_seqfile().
bsearch()
void* bsearch (const void * key, const void * base, size_t nel, size_t width, int(*)(const void *, const void *) cmp)
Definition at line 3 of file bsearch.c.
 {
     void *try;
     int sign;
     while (nel > 0) {
         try = (char *)base + width*(nel/2);
         sign = cmp(key, try);
         if (sign < 0) {
             nel /= 2;
         } else if (sign > 0) {
             base = (char *)try + width;
             nel -= nel/2+1;
         } else {
             return try;
         }
     }
     return NULL;
 }
References base, cmp(), NULL, and width.
Referenced by catgets(), find_builtin(), findkwd(), and rpm_getstr().
div()
div_t div (int num, int den)
Definition at line 3 of file div.c.
 {
     return (div_t){ num/den, num%den };
 }
Referenced by WI_drawTime().
exit()
_Noreturn void exit (int status)
Definition at line 21 of file lib.c.
 {
     _exit(status);
 }
References __funcs_on_exit(), __libc_exit_fini(), __stdio_exit(), _Exit(), and code.
getenv()
char* getenv (const char * name)
Definition at line 44 of file lib.c.
 {
     char **env = environ;
     if (env == NULL)
         return NULL;
     size_t len = strlen(name);
     while (*env != NULL)
     {
         if ((strncmp(*env, name, len) == 0) && ((*env)[len] == '='))
             return &(*env)[len + 1];
         ++env;
     }
 }
References __environ, __strchrnul(), l, and strncmp().
labs()
long labs (long a)
Definition at line 3 of file labs.c.
 {
     return a>0 ? a : -a;
 }
ldiv()
ldiv_t ldiv (long num, long den)
Definition at line 3 of file ldiv.c.
 {
     return (ldiv_t){ num/den, num%den };
 }
llabs()
long long llabs (long long a)
Definition at line 3 of file llabs.c.
 {
     return a>0 ? a : -a;
 }
lldiv()
lldiv_t lldiv (long long num, long long den)
Definition at line 3 of file lldiv.c.
 {
     return (lldiv_t){ num/den, num%den };
 }
mblen()
int mblen (const char * s, size_t n)
Definition at line 3 of file mblen.c.
 {
     return mbtowc(0, s, n);
 }
References mbtowc(), n, and s.
Referenced by __getopt_long_core(), read_comsub(), reset_locale_vars(), set_default_locale(), set_default_locale_vars(), and set_locale_var().
mbstowcs()
size_t mbstowcs (wchar_t * __restrict, const char * __restrict, size_t n)
Definition at line 226 of file unicode.c.
 {
     size_t org_n = n;
     if (unicode_status != UNICODE_ON) {
         while (n) {
             unsigned char c = *src++;
             if (dest)
                 *dest++ = c;
             if (c == 0)
                 break;
             n--;
         }
         return org_n - n;
     }
     while (n) {
         wchar_t wc;
         src = mbstowc_internal(&wc, src);
         if (wc == ERROR_WCHAR) /* error */
             return (size_t) -1L;
         if (dest)
             *dest++ = wc;
         if (wc == 0) /* end-of-string */
             break;
         n--;
     }
     return org_n - n;
 }
References c, ERROR_WCHAR, mbstowc_internal(), n, src, UNICODE_ON, and unicode_status.
Referenced by __wcsftime_l(), cutchars(), is_valid_hostname(), rev_main(), string_extract_verbatim(), and unicode_strlen().
mbtowc()
int mbtowc (wchar_t * __restrict, const char * __restrict, size_t)
Referenced by __fgetwc_unlocked_internal(), getopt(), match_bracket(), mblen(), parse_atom(), parse_bracket_terms(), pat_next(), str_next(), string_extract_verbatim(), sw_write(), and wprintf_core().
qsort()
void qsort (void * , size_t , size_t , int(*)(const void *, const void *))
quick_exit()
_Noreturn void quick_exit (int code)
Definition at line 7 of file quick_exit.c.
 {
     __funcs_on_quick_exit();
     _Exit(code);
 }
References __funcs_on_quick_exit(), _Exit(), and code.
rand()
int rand (void)
Definition at line 11 of file rand.c.
 {
     seed = 6364136223846793005ULL*seed + 1;
     return seed>>33;
 }
References seed.
Referenced by d6_read_interface(), evaluate(), generate_uuid(), makemime_main(), mkfs_reiser_main(), pick_nip(), poll_interval(), random_delay_ms(), random_xid(), send_d6_discover(), send_query_to_peer(), shuffle_lines(), and tls_run_copy_loop().
srand()
void srand (unsigned s)
Definition at line 6 of file rand.c.
 {
     seed = s-1;
 }
References s, and seed.
Referenced by evaluate(), generate_uuid(), makemime_main(), mkfs_reiser_main(), ntp_init(), shuffle_lines(), tls_run_copy_loop(), udhcpc6_main(), udhcpc_main(), and vi_main().
strtod()
double strtod (const char * __restrict, char ** __restrict)
strtof()
float strtof (const char * __restrict, char ** __restrict)
Referenced by strtof_l().
strtol()
long strtol (const char * __restrict, char ** __restrict, int)
strtold()
long double strtold (const char * __restrict, char ** __restrict)
Referenced by strtold_l().
strtoll()
long long strtoll (const char * __restrict, char ** __restrict, int)
Referenced by bb_strtoll(), check_operator(), and strtoimax().
strtoul()
unsigned long strtoul (const char * __restrict, char ** __restrict, int)
Referenced by __get_resolv_conf(), __inet_aton(), __lookup_serv(), __strftime_l(), bb_parse_mode(), dcngettext(), ether_aton_r(), evalprim(), get_irqs_from_interrupts(), get_mode(), get_qdisc_handle(), get_tc_classid(), get_u16(), get_u32(), get_unsigned(), getservbyname_r(), ifconfig_main(), init_cpu(), klogd_main(), new_process_module_arguments(), parse_meminfo(), process_irq_counts(), read_key(), reverse_services(), rtnl_rtntype_a2n(), sha256crypt(), sha512crypt(), strptime(), and strtoumax().
strtoull()
unsigned long long strtoull (const char * __restrict, char ** __restrict, int)
Referenced by __lookup_ipliteral(), bb_strtoull(), conf_write(), getOctal(), rdval(), rdval_diskstats(), read_after_slash(), and strtoumax().
system()
int system (const char * command)
Definition at line 67 of file lib.c.
 {
     return -1;
 }
References __environ, cmd, EINTR, errno, NULL, old, pid, posix_spawn(), POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, posix_spawnattr_destroy(), posix_spawnattr_init(), posix_spawnattr_setflags(), posix_spawnattr_setsigdefault(), posix_spawnattr_setsigmask(), pthread_testcancel(), reset(), SIG_BLOCK, SIG_IGN, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, sigprocmask(), SIGQUIT, status, and waitpid().
wcstombs()
size_t wcstombs (char * __restrict, const wchar_t * __restrict, size_t n)
Definition at line 133 of file unicode.c.
 {
     size_t org_n = n;
     if (unicode_status != UNICODE_ON) {
         while (n) {
             wchar_t c = *src++;
             *dest++ = c;
             if (c == 0)
                 break;
             n--;
         }
         return org_n - n;
     }
     while (n >= MB_CUR_MAX) {
         wchar_t wc = *src++;
         size_t len = wcrtomb_internal(dest, wc);
         if (wc == L'\0')
             return org_n - n;
         dest += len;
         n -= len;
     }
     while (n) {
         char tbuf[MB_CUR_MAX];
         wchar_t wc = *src++;
         size_t len = wcrtomb_internal(tbuf, wc);
         if (len > n)
             break;
         memcpy(dest, tbuf, len);
         if (wc == L'\0')
             return org_n - n;
         dest += len;
         n -= len;
     }
     return org_n - n;
 }
References c, L, MB_CUR_MAX, memcpy(), n, src, UNICODE_ON, unicode_status, and wcrtomb_internal().
Referenced by cutchars(), and rev_main().
wctomb()
int wctomb (char * s, wchar_t wc)
Definition at line 4 of file wctomb.c.
 {
     if (!s) return 0;
     return wcrtomb(s, wc, 0);
 }
References s, and wcrtomb().
Referenced by __fputwc_unlocked(), printf_core(), and vfwscanf().