Fennix: Userspace/apps/base/bash/examples/loadables/mktemp.c File Reference
mktemp.c File Reference
#include <config.h>
#include <stdio.h>
#include "bashansi.h"
#include "loadables.h"
Macros
#define DEFAULT_PREFIX "shtmp"
Functions
int mktemp_builtin (WORD_LIST *list)
Variables
char * mktemp_doc []
struct builtin mktemp_struct
Macro Definition Documentation
DEFAULT_PREFIX
#define DEFAULT_PREFIX "shtmp"
Definition at line 32 of file mktemp.c.
Function Documentation
mktemp_builtin()
int mktemp_builtin (WORD_LIST * list)
Definition at line 35 of file mktemp.c.
 {
   WORD_LIST *l;
   int rval, opt, fd, mflags, base_mflags;
   int dflag, qflag, tflag, uflag, onetime;
   char *prefix, *varname, *filename, *template;
   SHELL_VAR *v;
   dflag = qflag = uflag = tflag = onetime = 0;
   prefix = varname = 0;
   rval = EXECUTION_SUCCESS;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "dqut:v:")) != -1)
     {
       switch (opt)
     {
     case 'd':
       dflag = 1;
       break;
     case 'q':
       qflag = 1;
       break;
     case 't':
       tflag = 1;
       prefix = list_optarg;
       break;
     case 'u':
       uflag = 1;
       break;
     case 'v':
       varname = list_optarg;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (varname)          /* check for validity, not readonly */
     {
       if (legal_identifier (varname) == 0)
     {
       if (qflag == 0)
         sh_invalidid (varname);
       return (EXECUTION_FAILURE);
     }
       v = find_variable (varname);
       if (v && readonly_p (v))
     {
       if (qflag == 0)
         sh_readonly (varname);
       return (EXECUTION_FAILURE);
     }
     }
   onetime = (list == 0);    /* once through the loop, $TMPDIR/prefix.XXXXXX */
   if (prefix == 0)
     prefix = DEFAULT_PREFIX;
   base_mflags = MT_USETMPDIR|MT_USERANDOM;  /* USERANDOM not strictly needed */
   while (list || onetime)
     {
       mflags = base_mflags;
       onetime = 0;
 #if defined (USE_MKTEMP) && defined (USE_MKSTEMP)
       if (list)
     {
       template = list->word->word;
       mflags |= MT_TEMPLATE;
     }
 #else
       /* This is sub-optimal. */
       if (list)
     {
       /* Treat the basename as a prefix */
       template = strrchr (list->word->word, '/');
       if (template)
         template++;
       else
         template = list->word->word;
     }
 #endif
       else
     template = prefix;
       if (dflag)
     {
       filename = sh_mktmpdir (template, mflags);
       if (filename == 0)
         {
           if (qflag == 0)
         builtin_error ("%s: cannot create directory", template);
           rval = EXECUTION_FAILURE;
         }
       else
         {
           if (uflag)
         rmdir (filename);
           printf ("%s\n", filename);
         }
     }
       else      /* filename */
     {
       fd = sh_mktmpfd (template, mflags, &filename);
       if (fd < 0)
         {
           if (qflag == 0)
         builtin_error ("%s: cannot create file", template);
           rval = EXECUTION_FAILURE;
         }
       else
         {
           close (fd);
           if (uflag)
         unlink (filename);
           printf ("%s\n", filename);
         }
     }
       /* Assign variable if requested */
       if (filename && varname)
     {
       v = builtin_bind_variable (varname, filename, 0);
       if (v == 0 || readonly_p (v) || noassign_p (v))
         {
           builtin_error ("%s: cannot set variable", varname);
           rval = EXECUTION_FAILURE;
         }
     }
       FREE (filename);
       if (list)
         list = list->next;
     }
   return (rval);
 }
References builtin_bind_variable(), builtin_error(), builtin_usage(), CASE_HELPOPT, close(), DEFAULT_PREFIX, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, find_variable(), FREE, internal_getopt(), legal_identifier(), list_optarg, loptend, MT_TEMPLATE, MT_USERANDOM, MT_USETMPDIR, word_list::next, noassign_p, printf, readonly_p, reset_internal_getopt(), rmdir(), sh_invalidid(), sh_mktmpdir(), sh_mktmpfd(), sh_readonly(), strrchr(), unlink(), word_desc::word, and word_list::word.
Variable Documentation
mktemp_doc
char* mktemp_doc[]
Initial value:
= {
    "Make unique temporary file name",
    "",
    "Take each supplied filename template and overwrite a portion of it",
    "to create a filename, which is unique and may be used by the calling",
    "script. TEMPLATE is a string ending in some number of 'X's. If",
    "TEMPLATE is not supplied, shtmp.XXXXXX is used and $TMPDIR is used as",
    "the name of the containing directory. Files are created u+rw; directories",
    "are created u+rwx.",
    "",
    "Options, if supplied, have the following meanings:",
    "",
    "    -d    Create a directory instead of a file",
    "    -q    Do not print error messages about file creation failure",
    "    -t PREFIX Use PREFIX as the directory in which to create files",
    "    -u    Do not create anything; simply print a name",
    "    -v VAR    Store the generated name into shell variable VAR",
    "",
    "Any PREFIX supplied with -t is ignored if TEMPLATE is supplied.",
    "",
    "The return status is true if the file or directory was created successfully;",
    "false if an error occurs or VAR is invalid or readonly.",
    (char *)NULL
}
Definition at line 179 of file mktemp.c.
mktemp_struct
struct builtin mktemp_struct
Initial value:
= {
    "mktemp",
    mktemp_builtin,
    BUILTIN_ENABLED,
    mktemp_doc,
    "mktemp [-d] [-q] [-t prefix] [-u] [-v varname] [template] ...",
    0
}
Definition at line 179 of file mktemp.c.