Fennix: Userspace/apps/base/busybox/coreutils/shred.c File Reference
shred.c File Reference
#include "libbb.h"
Functions
int shred_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
shred_main()
int shred_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 43 of file shred.c.
 {
     char *opt_s;
     int rand_fd = rand_fd; /* for compiler */
     int zero_fd;
     unsigned num_iter = 3;
     unsigned opt;
     enum {
         OPT_f = (1 << 0),
         OPT_u = (1 << 1),
         OPT_z = (1 << 2),
         OPT_n = (1 << 3),
         OPT_v = (1 << 4),
         OPT_x = (1 << 5),
         OPT_s = (1 << 6),
     };
     opt = getopt32(argv, "^" "fuzn:+vxs:" "\0" "-1"/*min 1 arg*/, &num_iter, &opt_s);
     argv += optind;
     zero_fd = xopen("/dev/zero", O_RDONLY);
     if (num_iter != 0)
         rand_fd = xopen("/dev/urandom", O_RDONLY);
     for (;;) {
         struct stat sb;
         const char *fname;
         unsigned i;
         int fd;
         fname = *argv++;
         if (!fname)
             break;
         fd = -1;
         if (opt & OPT_f) {
             fd = open(fname, O_WRONLY);
             if (fd < 0)
                 chmod(fname, 0666);
         }
         if (fd < 0)
             fd = xopen(fname, O_WRONLY);
         if (fstat(fd, &sb) == 0 && sb.st_size > 0) {
             off_t size = sb.st_size;
             if (opt & OPT_s) {
                 size = BB_STRTOOFF(opt_s, NULL, 0); /* accepts oct/hex */
                 if (errno || size < 0) bb_show_usage();
             }
             for (i = 0; i < num_iter; i++) {
                 bb_copyfd_size(rand_fd, fd, size);
                 fdatasync(fd);
                 xlseek(fd, 0, SEEK_SET);
             }
             if (opt & OPT_z) {
                 bb_copyfd_size(zero_fd, fd, size);
                 fdatasync(fd);
             }
         }
         if (opt & OPT_u) {
             ftruncate(fd, 0);
             xunlink(fname);
         }
         xclose(fd);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_copyfd_size(), bb_show_usage(), BB_STRTOOFF, chmod(), errno, EXIT_SUCCESS, fd, fdatasync(), fname, fstat(), ftruncate(), getopt32(), i, NULL, O_RDONLY, O_WRONLY, off_t, open(), opt, OPT_f, OPT_n, OPT_s, OPT_u, OPT_v, OPT_x, OPT_z, optind, SEEK_SET, size, stat::st_size, xclose(), xlseek(), xopen(), and xunlink().