Fennix: Lynx/UEFI/src/Memory/memory.hpp File Reference
memory.hpp File Reference
#include "../bitmap.hpp"
#include <efi.h>
#include <efilib.h>
Macros
#define LYNX_MEMORY_TYPES_H
#define NULL ((void *)0)
#define EXTERNC
#define ALIGN_UP(x, align) ((__typeof__(x))(((uint64_t)(x) + ((align)-1)) & (~((align)-1))))
#define ALIGN_DOWN(x, align) ((__typeof__(x))((x) & (~((align)-1))))
#define PAGE_SIZE 0x1000
#define TO_PAGES(d) (d / PAGE_SIZE + 1)
#define FROM_PAGES(d) (d * PAGE_SIZE - 1)
#define NORMAL_VMA_OFFSET 0xFFFF800000000000
#define KERNEL_VMA_OFFSET 0xFFFFFFFF80000000
#define KERNEL_HEAP_BASE 0xFFFFC00000000000
KERNEL_HEAP_BASE is the base address of the kernel heap.
#define USER_HEAP_BASE 0xFFFFD00000000000
USER_HEAP_BASE is the base address of the user heap allocated by the kernel.
#define kmalloc(Size) HeapMalloc(Size)
#define kcalloc(n, Size) HeapCalloc(n, Size)
#define krealloc(Address, Size) HeapRealloc(Address, Size)
#define kfree(Address) HeapFree(Address)
Typedefs
typedef __UINT8_TYPE__ uint8_t
typedef __UINT16_TYPE__ uint16_t
typedef __UINT32_TYPE__ uint32_t
typedef __UINT64_TYPE__ uint64_t
typedef __SIZE_TYPE__ size_t
typedef __UINTPTR_TYPE__ uintptr_t
Functions
EXTERNC void InitializeMemoryManagement (EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE *SystemTable)
EXTERNC void * HeapMalloc (uint64_t Size)
EXTERNC void * HeapCalloc (uint64_t n, uint64_t Size)
EXTERNC void * HeapRealloc (void *Address, uint64_t Size)
EXTERNC void HeapFree (void *Address)
Macro Definition Documentation
ALIGN_DOWN
#define ALIGN_DOWN (x, align) ((__typeof__(x))((x) & (~((align)-1))))
Definition at line 24 of file memory.hpp.
ALIGN_UP
#define ALIGN_UP (x, align) ((__typeof__(x))(((uint64_t)(x) + ((align)-1)) & (~((align)-1))))
Definition at line 23 of file memory.hpp.
EXTERNC
#define EXTERNC
Definition at line 20 of file memory.hpp.
FROM_PAGES
#define FROM_PAGES (d) (d * PAGE_SIZE - 1)
Definition at line 38 of file memory.hpp.
kcalloc
#define kcalloc (n, Size) HeapCalloc(n, Size)
Definition at line 429 of file memory.hpp.
KERNEL_HEAP_BASE
#define KERNEL_HEAP_BASE 0xFFFFC00000000000
KERNEL_HEAP_BASE is the base address of the kernel heap.
Definition at line 46 of file memory.hpp.
KERNEL_VMA_OFFSET
#define KERNEL_VMA_OFFSET 0xFFFFFFFF80000000
Definition at line 41 of file memory.hpp.
kfree
#define kfree (Address) HeapFree(Address)
Definition at line 431 of file memory.hpp.
kmalloc
#define kmalloc (Size) HeapMalloc(Size)
Definition at line 428 of file memory.hpp.
krealloc
#define krealloc (Address, Size) HeapRealloc(Address, Size)
Definition at line 430 of file memory.hpp.
LYNX_MEMORY_TYPES_H
#define LYNX_MEMORY_TYPES_H
Definition at line 5 of file memory.hpp.
NORMAL_VMA_OFFSET
#define NORMAL_VMA_OFFSET 0xFFFF800000000000
Definition at line 40 of file memory.hpp.
NULL
#define NULL ((void *)0)
Definition at line 14 of file memory.hpp.
PAGE_SIZE
#define PAGE_SIZE 0x1000
Definition at line 33 of file memory.hpp.
TO_PAGES
#define TO_PAGES (d) (d / PAGE_SIZE + 1)
Definition at line 36 of file memory.hpp.
USER_HEAP_BASE
#define USER_HEAP_BASE 0xFFFFD00000000000
USER_HEAP_BASE is the base address of the user heap allocated by the kernel.
Definition at line 50 of file memory.hpp.
Typedef Documentation
size_t
typedef __SIZE_TYPE__ size_t
Definition at line 11 of file memory.hpp.
uint16_t
typedef __UINT16_TYPE__ uint16_t
Definition at line 8 of file memory.hpp.
uint32_t
typedef __UINT32_TYPE__ uint32_t
Definition at line 9 of file memory.hpp.
uint64_t
typedef __UINT64_TYPE__ uint64_t
Definition at line 10 of file memory.hpp.
uint8_t
typedef __UINT8_TYPE__ uint8_t
Definition at line 7 of file memory.hpp.
uintptr_t
typedef __UINTPTR_TYPE__ uintptr_t
Definition at line 12 of file memory.hpp.
Function Documentation
HeapCalloc()
EXTERNC void* HeapCalloc (uint64_t n, uint64_t Size)
Definition at line 124 of file Memory.cpp.
 { return PREFIX(calloc)(n, Size); }
References calloc(), n, PREFIX, and Size.
HeapFree()
EXTERNC void HeapFree (void * Address)
Definition at line 471 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(AllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("free(%#lx)->[%s]", Address, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     switch (AllocatorType)
     {
     case unlikely(MemoryAllocatorType::Pages):
     {
         KernelAllocator.FreePage(Address); // WARNING: Potential memory leak
         break;
     }
     case MemoryAllocatorType::XallocV1:
     {
         XallocV1Allocator->free(Address);
         break;
     }
     case MemoryAllocatorType::liballoc11:
     {
         PREFIX(free)
         (Address);
         break;
     }
     default:
         throw;
     }
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "free( %p )~%p\n\r",
                 Address,
                 __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
 }
References Address, AllocatorType, UniversalAsynchronousReceiverTransmitter::COM3, Xalloc::V1::free(), free(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelAllocator, KernelSymbolTable, memdbg, PREFIX, sprintf(), strcat_unsafe(), strcpy_unsafe(), unlikely, UniversalAsynchronousReceiverTransmitter::UART::Write(), and XallocV1Allocator.
Referenced by operator delete(), and operator delete[]().
HeapMalloc()
EXTERNC void* HeapMalloc (uint64_t Size)
Definition at line 123 of file Memory.cpp.
 { return PREFIX(malloc)(Size); }
References malloc(), PREFIX, and Size.
HeapRealloc()
EXTERNC void* HeapRealloc (void * Address, uint64_t Size)
Definition at line 125 of file Memory.cpp.
 { return PREFIX(realloc)(Address, Size); }
References Address, PREFIX, realloc(), and Size.
InitializeMemoryManagement()
EXTERNC void InitializeMemoryManagement (EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE * SystemTable)
Definition at line 23 of file Memory.cpp.
 {
     printf("Initializing Physical Memory Manager\n");
     KernelAllocator = Physical();
     KernelAllocator.Init(ImageHandle, SystemTable);
     printf("Memory Info: %dMB / %dMB (%dMB reserved)",
            (KernelAllocator.GetUsedMemory() / 1024 / 1024),
            (KernelAllocator.GetTotalMemory() / 1024 / 1024),
            (KernelAllocator.GetReservedMemory() / 1024 / 1024));
     KernelPageTable = (PageTable *)KernelAllocator.RequestPage();
     memset(KernelPageTable, 0, PAGE_SIZE);
     Virtual kva = Virtual(KernelPageTable);
     printf("Mapping...\n");
     uint64_t BootloaderStart = (uint64_t)&ImageBase;
     uint64_t BootloaderTextEnd = (uint64_t)&_text;
     uint64_t BootloaderDataEnd = (uint64_t)&_data;
     uint64_t BootloaderEnd = (uint64_t)&ImageBase + (uint64_t)&_etext + (uint64_t)&_edata;
     uint64_t VirtualOffsetNormalVMA = NORMAL_VMA_OFFSET;
     uint64_t BaseKernelMapAddress = (uint64_t)0; // TODO: Info->Kernel.PhysicalBase;
     EFI_MEMORY_DESCRIPTOR *memDesc = nullptr;
     UINTN MapSize, MapKey;
     UINTN DescriptorSize;
     UINT32 DescriptorVersion;
     {
         SystemTable->BootServices->GetMemoryMap(&MapSize, memDesc, &MapKey, &DescriptorSize, &DescriptorVersion);
         SystemTable->BootServices->AllocatePool(EfiLoaderData, MapSize, (void **)&memDesc);
         SystemTable->BootServices->GetMemoryMap(&MapSize, memDesc, &MapKey, &DescriptorSize, &DescriptorVersion);
     }
     for (uint64_t t = 0; t < MapSize / DescriptorSize; t += PAGE_SIZE)
     {
         kva.Map((void *)t, (void *)t, PTFlag::RW);
         kva.Map((void *)VirtualOffsetNormalVMA, (void *)t, PTFlag::RW);
         VirtualOffsetNormalVMA += PAGE_SIZE;
     }
     EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *info;
     UINTN SizeOfInfo, numModes = 0; //, MaximumSupportedMode = 0;
     EFI_STATUS status;
     EFI_GRAPHICS_OUTPUT_PROTOCOL *gop;
     EFI_GUID gopGuid = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;
     status = uefi_call_wrapper(BS->LocateProtocol, 3, &gopGuid, NULL, (void **)&gop);
     if (EFI_ERROR(status))
     {
         printf("Unable to locate the Graphics Output Protocol.\n");
     }
     status = uefi_call_wrapper(gop->QueryMode, 4, gop, gop->Mode == NULL ? 0 : gop->Mode->Mode, &SizeOfInfo, &info);
     if (status == EFI_NOT_STARTED)
     {
         printf("The EFI not started!\n");
         status = uefi_call_wrapper(gop->SetMode, 2, gop, 0);
     }
     /* Mapping Framebuffer address */
     int itrfb = 0;
     while (1)
     {
         for (uint64_t fb_base = (uint64_t)gop->Mode->FrameBufferBase;
              fb_base < ((uint64_t)gop->Mode->FrameBufferBase + ((gop->Mode->Info->PixelsPerScanLine) + PAGE_SIZE));
              fb_base += PAGE_SIZE)
             kva.Map((void *)fb_base, (void *)fb_base, PTFlag::RW | PTFlag::US);
         itrfb++;
     }
     /* Kernel mapping */
     for (uint64_t k = BootloaderStart; k < BootloaderTextEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (uint64_t k = BootloaderTextEnd; k < BootloaderDataEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (uint64_t k = BootloaderDataEnd; k < BootloaderEnd; k += PAGE_SIZE)
     {
         kva.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     printf("\nStart: %#llx - Text End: %#llx - End: %#llx\nStart Physical: %#llx - End Physical: %#llx",
            BootloaderStart, BootloaderTextEnd, BootloaderEnd, /* Info->Kernel.PhysicalBase */ 0, BaseKernelMapAddress - PAGE_SIZE);
     /*    BootloaderStart             BootloaderTextEnd       KernelRoDataEnd                  BootloaderEnd
     Kernel Start & Text Start ------ Text End ------ Kernel Rodata End ------ Kernel Data End & Kernel End
     */
     printf("Applying new page table from address %p", KernelPageTable);
     __asm__ volatile("mov %0, %%cr3" ::"r"(KernelPageTable));
 }
References _data, _edata, _etext, _text, ImageBase, info, k, KernelAllocator, KernelPageTable, memset(), NORMAL_VMA_OFFSET, NULL, PAGE_SIZE, CPU::PageTable(), APIC::Physical, printf(), RW, and mlibc::status.