Fennix Userspace: Userspace/apps/base/bash/jobs.c File Reference
jobs.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "trap.h"
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include "posixtime.h"
#include "filecntl.h"
#include <sys/ioctl.h>
#include "shtty.h"
#include "bashansi.h"
#include "bashintl.h"
#include "shell.h"
#include "parser.h"
#include "jobs.h"
#include "execute_cmd.h"
#include "flags.h"
#include "typemax.h"
#include "builtins/builtext.h"
#include "builtins/common.h"
Macros
#define DEFAULT_CHILD_MAX 4096
#define MAX_CHILD_MAX 32768
#define MAX_JOBS_IN_ARRAY 4096 /* production */
#define PIDSTAT_TABLE_SZ 4096
#define BGPIDS_TABLE_SZ 512
#define DEL_WARNSTOPPED 1 /* warn about deleting stopped jobs */
#define DEL_NOBGPID 2 /* don't add pgrp leader to bgpids */
#define WAITPID(pid, statusp, options) wait3 (statusp, options, (int *)0)
#define getpgid(p) getpgrp (p)
#define REINSTALL_SIGCHLD_HANDLER
#define WCONTINUED 0
#define WIFCONTINUED(s) (0)
#define JOB_SLOTS 8
#define QUEUE_SIGCHLD(os) (os) = sigchld, queue_sigchld++
#define UNQUEUE_SIGCHLD(os)
#define setpgid(pid, pgrp) setpgrp (pid, pgrp)
#define tcsetpgrp(fd, pgrp) ioctl ((fd), TIOCSPGRP, &(pgrp))
#define input_tty() (shell_tty != -1) ? shell_tty : fileno (stderr)
#define INVALID_SIGNAL_HANDLER (SigHandler *)wait_for_background_pids
#define FIND_CHILD(pid, child)
Typedefs
typedef int sh_job_map_func_t PARAMS((JOB *, int, int, int))
Functions
int killpg PARAMS ((pid_t, int))
void set_original_signal PARAMS ((int, SigHandler *))
void debug_print_pgrps (void)
static sighandler wait_sigint_handler PARAMS ((int))
static PROCESS *find_pid_in_pipeline PARAMS ((pid_t, PROCESS *, int))
static PROCESS *find_pipeline PARAMS ((pid_t, int, int *))
static char *current_working_directory PARAMS ((void))
static int map_over_jobs PARAMS ((sh_job_map_func_t *, int, int))
static int most_recent_job_in_state PARAMS ((int, JOB_STATE))
static int find_job PARAMS ((pid_t, int, PROCESS **))
static int process_exit_status PARAMS ((WAIT))
static void add_process PARAMS ((char *, pid_t))
static void print_pipeline PARAMS ((PROCESS *, int, int, FILE *))
static void pretty_print_job PARAMS ((int, int, FILE *))
static int maybe_give_terminal_to PARAMS ((pid_t, pid_t, int))
pid_t tcgetpgrp (int fd)
void init_job_stats ()
static char * current_working_directory ()
static char * job_working_directory ()
void making_children ()
void stop_making_children ()
void cleanup_the_pipeline ()
void discard_last_procsub_child ()
static struct pipeline_saver * alloc_pipeline_saver ()
void save_pipeline (int clear)
PROCESS * restore_pipeline (int discard)
void start_pipeline ()
int stop_pipeline (int async, COMMAND *deferred)
static void bgp_resize ()
static ps_index_t bgp_getindex ()
static ps_index_t * pshash_getbucket (pid_t pid)
static struct pidstat * bgp_add (pid_t pid, int status)
static void pshash_delindex (ps_index_t psi)
static int bgp_delete (pid_t pid)
static void bgp_clear ()
static int bgp_search (pid_t pid)
void save_proc_status (pid_t pid, int status)
static void reset_job_indices ()
static void cleanup_dead_jobs ()
static int processes_in_job (int job)
static void delete_old_job (pid_t pid)
static void realloc_jobs_list ()
static int compact_jobs_list (int flags)
void delete_job (int job_index, int dflags)
void nohup_job (int job_index)
int discard_pipeline (PROCESS *chain)
static void add_process (char *name, pid_t pid)
void append_process (char *name, pid_t pid, int status, int jid)
static int map_over_jobs (sh_job_map_func_t *func, int arg1, int arg2)
void terminate_current_pipeline ()
void terminate_stopped_jobs ()
void hangup_all_jobs ()
void kill_current_pipeline ()
static PROCESS * find_pid_in_pipeline (pid_t pid, PROCESS *pipeline, int alive_only)
static PROCESS * find_pipeline (pid_t pid, int alive_only, int *jobp)
static PROCESS * find_process (pid_t pid, int alive_only, int *jobp)
static int find_job (pid_t pid, int alive_only, PROCESS **procp)
int get_job_by_pid (pid_t pid, int block, PROCESS **procp)
void describe_pid (pid_t pid)
static char * j_strsignal (int s)
static char * printable_job_status (int j, PROCESS *p, int format)
static void print_pipeline (PROCESS *p, int job_index, int format, FILE *stream)
static void pretty_print_job (int job_index, int format, FILE *stream)
static int print_job (JOB *job, int format, int state, int job_index)
void list_one_job (JOB *job, int format, int ignore, int job_index)
void list_stopped_jobs (int format)
void list_running_jobs (int format)
void list_all_jobs (int format)
pid_t make_child (char *command, int flags)
void ignore_tty_job_signals ()
void default_tty_job_signals ()
void get_original_tty_job_signals ()
int get_tty_state ()
int set_tty_state ()
static PROCESS * find_last_proc (int job, int block)
static pid_t find_last_pid (int job, int block)
int wait_for_single_pid (pid_t pid, int flags)
int wait_for_background_pids (struct procstat *ps)
void wait_sigint_cleanup ()
static void restore_sigint_handler ()
static sighandler wait_sigint_handler (int sig)
static int process_exit_signal (WAIT status)
static int process_exit_status (WAIT status)
static WAIT job_signal_status (int job)
static WAIT raw_job_exit_status (int job)
int job_exit_status (int job)
int job_exit_signal (int job)
int wait_for (pid_t pid, int flags)
int wait_for_job (int job, int flags, struct procstat *ps)
int wait_for_any_job (int flags, struct procstat *ps)
void notify_and_cleanup ()
void reap_dead_jobs ()
static int most_recent_job_in_state (int job, JOB_STATE state)
static int job_last_stopped (int job)
static int job_last_running (int job)
static void set_current_job (int job)
static void reset_current ()
static void set_job_running (int job)
int start_job (int job, int foreground)
int kill_pid (pid_t pid, int sig, int group)
static sighandler sigchld_handler (int sig)
static int waitchld (pid_t wpid, int block)
static int set_job_status_and_cleanup (int job)
static void setjstatus (int j)
void run_sigchld_trap (int nchild)
static void notify_of_job_status ()
int initialize_job_control (int force)
static int set_new_line_discipline (int tty)
void initialize_job_signals ()
static sighandler sigcont_sighandler (int sig)
static sighandler sigstop_sighandler (int sig)
int give_terminal_to (pid_t pgrp, int force)
static int maybe_give_terminal_to (pid_t opgrp, pid_t npgrp, int flags)
void delete_all_jobs (int running_only)
void nohup_all_jobs (int running_only)
int count_all_jobs ()
static void mark_all_jobs_as_dead ()
static void mark_dead_jobs_as_notified (int force)
int freeze_jobs_list ()
void unfreeze_jobs_list ()
void set_jobs_list_frozen (int s)
int set_job_control (int arg)
void without_job_control ()
void end_job_control ()
void restart_job_control ()
void set_maxchild (int nchild)
void set_sigchld_handler ()
Variables
int errno
WORD_LIST * subst_assign_varlist
SigHandler ** original_signals
static struct jobstats zerojs = { -1L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NO_JOB, NO_JOB, 0, 0 }
struct jobstats js = { -1L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NO_JOB, NO_JOB, 0, 0 }
ps_index_t pidstat_table [PIDSTAT_TABLE_SZ]
struct bgpids bgpids = { 0, 0, 0, 0 }
struct procchain procsubs = { 0, 0, 0 }
JOB ** jobs = (JOB **)NULL
int shell_tty = -1
pid_t shell_pgrp = NO_PID
pid_t terminal_pgrp = NO_PID
pid_t original_pgrp = NO_PID
pid_t pipeline_pgrp = (pid_t)0
volatile pid_t last_made_pid = NO_PID
volatile pid_t last_asynchronous_pid = NO_PID
PROCESS * the_pipeline = (PROCESS *)NULL
int job_control = 1
int running_in_background = 0
int already_making_children = 0
int check_window_size = CHECKWINSIZE_DEFAULT
PROCESS * last_procsub_child = (PROCESS *)NULL
static int sigchld
static int queue_sigchld
static SigHandler * old_tstp
static SigHandler * old_ttou
static SigHandler * old_ttin
static SigHandler * old_cont = (SigHandler *)SIG_DFL
static struct pipeline_saver * saved_pipeline
static int saved_already_making_children
static int jobs_list_frozen
static char retcode_name_buffer [64]
static TTYSTRUCT shell_tty_info
static SigHandler * old_sigint_handler = INVALID_SIGNAL_HANDLER
static int wait_sigint_received
static int child_caught_sigint
int waiting_for_child
Macro Definition Documentation
BGPIDS_TABLE_SZ
#define BGPIDS_TABLE_SZ 512
Definition at line 109 of file jobs.c.
DEFAULT_CHILD_MAX
#define DEFAULT_CHILD_MAX 4096
Definition at line 94 of file jobs.c.
DEL_NOBGPID
#define DEL_NOBGPID 2 /* don't add pgrp leader to bgpids */
Definition at line 113 of file jobs.c.
DEL_WARNSTOPPED
#define DEL_WARNSTOPPED 1 /* warn about deleting stopped jobs */
Definition at line 112 of file jobs.c.
FIND_CHILD
#define FIND_CHILD (pid, child)
Value:
  do \
    { \
      child = find_pipeline (pid, 0, (int *)NULL); \
      if (child == 0) \
    { \
      give_terminal_to (shell_pgrp, 0); \
      UNBLOCK_CHILD (oset); \
      internal_error (_("wait_for: No record of process %ld"), (long)pid); \
      restore_sigint_handler (); \
      return (termination_state = 127); \
    } \
    } \
  while (0)
Definition at line 2879 of file jobs.c.
getpgid
#define getpgid (p) getpgrp (p)
Definition at line 142 of file jobs.c.
input_tty
#define input_tty () (shell_tty != -1) ? shell_tty : fileno (stderr)
Definition at line 2467 of file jobs.c.
INVALID_SIGNAL_HANDLER
#define INVALID_SIGNAL_HANDLER (SigHandler *)wait_for_background_pids
Definition at line 2718 of file jobs.c.
JOB_SLOTS
#define JOB_SLOTS 8
Definition at line 163 of file jobs.c.
MAX_CHILD_MAX
#define MAX_CHILD_MAX 32768
Definition at line 98 of file jobs.c.
MAX_JOBS_IN_ARRAY
#define MAX_JOBS_IN_ARRAY 4096 /* production */
Definition at line 102 of file jobs.c.
PIDSTAT_TABLE_SZ
#define PIDSTAT_TABLE_SZ 4096
Definition at line 108 of file jobs.c.
QUEUE_SIGCHLD
#define QUEUE_SIGCHLD (os) (os) = sigchld, queue_sigchld++
Definition at line 320 of file jobs.c.
REINSTALL_SIGCHLD_HANDLER
#define REINSTALL_SIGCHLD_HANDLER
Definition at line 150 of file jobs.c.
setpgid
#define setpgid (pid, pgrp) setpgrp (pid, pgrp)
Definition at line 354 of file jobs.c.
tcsetpgrp
#define tcsetpgrp (fd, pgrp) ioctl ((fd), TIOCSPGRP, &(pgrp))
Definition at line 355 of file jobs.c.
UNQUEUE_SIGCHLD
#define UNQUEUE_SIGCHLD (os)
Value:
    do { \
      queue_sigchld--; \
      if (queue_sigchld == 0 && os != sigchld) \
        { \
          queue_sigchld = 1; \
          waitchld (-1, 0); \
          queue_sigchld = 0; \
        } \
    } while (0)
Definition at line 324 of file jobs.c.
WAITPID
#define WAITPID (pid, statusp, options) wait3 (statusp, options, (int *)0)
Definition at line 131 of file jobs.c.
WCONTINUED
#define WCONTINUED 0
Definition at line 156 of file jobs.c.
WIFCONTINUED
#define WIFCONTINUED (s) (0)
Definition at line 159 of file jobs.c.
Typedef Documentation
PARAMS
typedef int sh_job_map_func_t PARAMS((JOB *, int, int, int))
Definition at line 165 of file jobs.c.
Function Documentation
add_process()
static void add_process (char * name, pid_t pid) static
Definition at line 1488 of file jobs.c.
 {
   PROCESS *t, *p;
 #if defined (RECYCLES_PIDS)
   int j;
   p = find_process (pid, 0, &j);
   if (p)
     {
       if (j == NO_JOB)
     internal_debug ("add_process: process %5ld (%s) in the_pipeline", (long)p->pid, p->command);
       if (PALIVE (p))
     internal_warning (_("add_process: pid %5ld (%s) marked as still alive"), (long)p->pid, p->command);
       p->running = PS_RECYCLED;     /* mark as recycled */
     }
 #endif
   t = (PROCESS *)xmalloc (sizeof (PROCESS));
   t->next = the_pipeline;
   t->pid = pid;
   WSTATUS (t->status) = 0;
   t->running = PS_RUNNING;
   t->command = name;
   the_pipeline = t;
   if (t->next == 0)
     t->next = t;
   else
     {
       p = t->next;
       while (p->next != t->next)
     p = p->next;
       p->next = t;
     }
 }
References _, find_process(), internal_debug(), internal_warning(), j, NO_JOB, p, PALIVE, pid, PS_RECYCLED, PS_RUNNING, t, the_pipeline, WSTATUS, and xmalloc.
Referenced by make_child().
alloc_pipeline_saver()
static struct pipeline_saver* alloc_pipeline_saver () static
Definition at line 468 of file jobs.c.
 {
   struct pipeline_saver *ret;
   ret = (struct pipeline_saver *)xmalloc (sizeof (struct pipeline_saver));
   ret->pipeline = 0;
   ret->next = 0;
   return ret;
 }
References pipeline_saver::next, pipeline_saver::pipeline, and xmalloc.
Referenced by save_pipeline().
append_process()
void append_process (char * name, pid_t pid, int status, int jid)
Definition at line 1529 of file jobs.c.
 {
   PROCESS *t, *p;
   t = (PROCESS *)xmalloc (sizeof (PROCESS));
   t->next = (PROCESS *)NULL;
   t->pid = pid;
   /* set process exit status using offset discovered by configure */
   t->status = (status & 0xff) << WEXITSTATUS_OFFSET;
   t->running = PS_DONE;
   t->command = name;
   js.c_reaped++;    /* XXX */
   for (p = jobs[jid]->pipe; p->next != jobs[jid]->pipe; p = p->next)
     ;
   p->next = t;
   t->next = jobs[jid]->pipe;
 }
References jobstats::c_reaped, jobs, js, NULL, p, pid, job::pipe, PS_DONE, status, t, and xmalloc.
Referenced by execute_pipeline().
bgp_add()
static struct pidstat* bgp_add (pid_t pid, int status) static
Definition at line 822 of file jobs.c.
 {
   ps_index_t *bucket, psi;
   struct pidstat *ps;
   /* bucket == existing chain of pids hashing to same value
      psi = where were going to put this pid/status */
   bucket = pshash_getbucket (pid);  /* index into pidstat_table */
   psi = bgp_getindex ();        /* bgpids.head, index into storage */
   /* XXX - what if psi == *bucket? */
   if (psi == *bucket)
     {
       internal_debug ("hashed pid %d (pid %d) collides with bgpids.head, skipping", psi, pid);
       bgpids.storage[psi].pid = NO_PID;     /* make sure */
       psi = bgp_getindex ();            /* skip to next one */
     }
   ps = &bgpids.storage[psi];
   ps->pid = pid;
   ps->status = status;
   ps->bucket_next = *bucket;
   ps->bucket_prev = NO_PIDSTAT;
   bgpids.npid++;
 #if 0
   if (bgpids.npid > js.c_childmax)
     bgp_prune ();
 #endif
   if (ps->bucket_next != NO_PIDSTAT)
     bgpids.storage[ps->bucket_next].bucket_prev = psi;
   *bucket = psi;        /* set chain head in hash table */
   return ps;
 }
References bgp_getindex(), pidstat::bucket_next, pidstat::bucket_prev, jobstats::c_childmax, internal_debug(), js, NO_PID, NO_PIDSTAT, bgpids::npid, pidstat::pid, pid, pshash_getbucket(), pidstat::status, status, and bgpids::storage.
Referenced by delete_job(), and save_proc_status().
bgp_clear()
static void bgp_clear () static
Definition at line 927 of file jobs.c.
 {
   if (bgpids.storage == 0 || bgpids.nalloc == 0)
     return;
   free (bgpids.storage);
   bgpids.storage = 0;
   bgpids.nalloc = 0;
   bgpids.head = 0;
   bgpids.npid = 0;
 }
References free, bgpids::head, bgpids::nalloc, bgpids::npid, and bgpids::storage.
Referenced by delete_all_jobs(), and wait_for_background_pids().
bgp_delete()
static int bgp_delete (pid_t pid) static
Definition at line 892 of file jobs.c.
 {
   ps_index_t psi, orig_psi;
   if (bgpids.storage == 0 || bgpids.nalloc == 0 || bgpids.npid == 0)
     return 0;
   /* Search chain using hash to find bucket in pidstat_table */
   for (orig_psi = psi = *(pshash_getbucket (pid)); psi != NO_PIDSTAT; psi = bgpids.storage[psi].bucket_next)
     {
       if (bgpids.storage[psi].pid == pid)
     break;
       if (orig_psi == bgpids.storage[psi].bucket_next)  /* catch reported bug */
     {
       internal_warning (_("bgp_delete: LOOP: psi (%d) == storage[psi].bucket_next"), psi);
       return 0;
     }
     }
   if (psi == NO_PIDSTAT)
     return 0;       /* not found */
 #if 0
   itrace("bgp_delete: deleting %d", pid);
 #endif
   pshash_delindex (psi);    /* hash table management */
   bgpids.npid--;
   return 1;
 }
References _, pidstat::bucket_next, internal_warning(), bgpids::nalloc, NO_PIDSTAT, bgpids::npid, pidstat::pid, pid, pshash_delindex(), pshash_getbucket(), and bgpids::storage.
Referenced by make_child(), and wait_for_single_pid().
bgp_getindex()
static ps_index_t bgp_getindex () static
Definition at line 802 of file jobs.c.
 {
   if (bgpids.nalloc < (ps_index_t)js.c_childmax || bgpids.head >= bgpids.nalloc)
     bgp_resize ();
   pshash_delindex (bgpids.head);        /* XXX - clear before reusing */
   return bgpids.head++;
 }
References bgp_resize(), jobstats::c_childmax, bgpids::head, js, bgpids::nalloc, and pshash_delindex().
Referenced by bgp_add().
bgp_resize()
static void bgp_resize () static
Definition at line 759 of file jobs.c.
 {
   ps_index_t nsize, nsize_cur, nsize_max;
   ps_index_t psi;
   if (bgpids.nalloc == 0)
     {
       /* invalidate hash table when bgpids table is reallocated */
       for (psi = 0; psi < PIDSTAT_TABLE_SZ; psi++)
         pidstat_table[psi] = NO_PIDSTAT;
       nsize = BGPIDS_TABLE_SZ;  /* should be power of 2 */
       bgpids.head = 0;
     }
   else
     nsize = bgpids.nalloc;
   nsize_max = TYPE_MAXIMUM (ps_index_t);
   nsize_cur = (ps_index_t)js.c_childmax;
   if (nsize_cur < 0)                /* overflow */
     nsize_cur = MAX_CHILD_MAX;
   while (nsize > 0 && nsize < nsize_cur)    /* > 0 should catch overflow */
     nsize <<= 1;
   if (nsize > nsize_max || nsize <= 0)      /* overflow? */
     nsize = nsize_max;
   if (nsize > MAX_CHILD_MAX)
     nsize = nsize_max = MAX_CHILD_MAX;      /* hard cap */
   if (bgpids.nalloc < nsize_cur && bgpids.nalloc < nsize_max)
     {
       bgpids.storage = (struct pidstat *)xrealloc (bgpids.storage, nsize * sizeof (struct pidstat));
       for (psi = bgpids.nalloc; psi < nsize; psi++)
     bgpids.storage[psi].pid = NO_PID;
       bgpids.nalloc = nsize;
     }
   else if (bgpids.head >= bgpids.nalloc)    /* wrap around */
     bgpids.head = 0;
 }
References BGPIDS_TABLE_SZ, jobstats::c_childmax, bgpids::head, if(), js, MAX_CHILD_MAX, bgpids::nalloc, NO_PID, NO_PIDSTAT, pidstat::pid, pidstat_table, PIDSTAT_TABLE_SZ, bgpids::storage, TYPE_MAXIMUM, and xrealloc.
Referenced by bgp_getindex().
bgp_search()
static int bgp_search (pid_t pid) static
Definition at line 945 of file jobs.c.
 {
   ps_index_t psi, orig_psi;
   if (bgpids.storage == 0 || bgpids.nalloc == 0 || bgpids.npid == 0)
     return -1;
   /* Search chain using hash to find bucket in pidstat_table */
   for (orig_psi = psi = *(pshash_getbucket (pid)); psi != NO_PIDSTAT; psi = bgpids.storage[psi].bucket_next)
     {
       if (bgpids.storage[psi].pid == pid)
     return (bgpids.storage[psi].status);
       if (orig_psi == bgpids.storage[psi].bucket_next)  /* catch reported bug */
     {
       internal_warning (_("bgp_search: LOOP: psi (%d) == storage[psi].bucket_next"), psi);
       return -1;
     }
     }
   return -1;
 }
References _, pidstat::bucket_next, internal_warning(), bgpids::nalloc, NO_PIDSTAT, bgpids::npid, pidstat::pid, pid, pshash_getbucket(), pidstat::status, and bgpids::storage.
Referenced by wait_for_single_pid().
cleanup_dead_jobs()
static void cleanup_dead_jobs () static
Definition at line 1210 of file jobs.c.
 {
   register int i;
   int os;
   PROCESS *discard;
   if (js.j_jobslots == 0 || jobs_list_frozen)
     return;
   QUEUE_SIGCHLD(os);
   /* XXX could use js.j_firstj and js.j_lastj here */
   for (i = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
     INTERNAL_DEBUG (("cleanup_dead_jobs: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
     INTERNAL_DEBUG(("cleanup_dead_jobs: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i] && DEADJOB (i) && IS_NOTIFIED (i))
     delete_job (i, 0);
     }
 #if defined (PROCESS_SUBSTITUTION)
   procsub_prune ();
   last_procsub_child = (PROCESS *)NULL;
 #endif
 #if defined (COPROCESS_SUPPORT)
   coproc_reap ();
 #endif
   UNQUEUE_SIGCHLD(os);
 }
References DEADJOB, delete_job(), i, INTERNAL_DEBUG, IS_NOTIFIED, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobs, jobs_list_frozen, js, last_procsub_child, NULL, QUEUE_SIGCHLD, and UNQUEUE_SIGCHLD.
Referenced by list_all_jobs(), list_one_job(), list_running_jobs(), list_stopped_jobs(), notify_and_cleanup(), reap_dead_jobs(), stop_pipeline(), wait_for_background_pids(), and wait_for_single_pid().
cleanup_the_pipeline()
void cleanup_the_pipeline ()
Definition at line 437 of file jobs.c.
 {
   PROCESS *disposer;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   disposer = the_pipeline;
   the_pipeline = (PROCESS *)NULL;
   UNBLOCK_CHILD (oset);
   if (disposer)
     discard_pipeline (disposer);
 }
References BLOCK_CHILD, discard_pipeline(), NULL, the_pipeline, and UNBLOCK_CHILD.
Referenced by command_substitute(), push_builtin(), and start_pipeline().
compact_jobs_list()
static int compact_jobs_list (int flags) static
Definition at line 1367 of file jobs.c.
 {
   if (js.j_jobslots == 0 || jobs_list_frozen)
     return js.j_jobslots;
   reap_dead_jobs ();
   realloc_jobs_list ();
 #if 0
   itrace("compact_jobs_list: returning %d", (js.j_lastj || jobs[js.j_lastj]) ? js.j_lastj + 1 : 0);
 #endif
   return ((js.j_lastj || jobs[js.j_lastj]) ? js.j_lastj + 1 : 0);
 }
References jobstats::j_jobslots, jobstats::j_lastj, jobs, jobs_list_frozen, js, realloc_jobs_list(), and reap_dead_jobs().
Referenced by stop_pipeline().
count_all_jobs()
int count_all_jobs ()
Definition at line 4778 of file jobs.c.
 {
   int i, n;
   sigset_t set, oset;
   /* This really counts all non-dead jobs. */
   BLOCK_CHILD (set, oset);
   /* XXX could use js.j_firstj here */
   for (i = n = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
     INTERNAL_DEBUG (("count_all_jobs: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
     INTERNAL_DEBUG (("count_all_jobs: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i] && DEADJOB(i) == 0)
     n++;
     }
   UNBLOCK_CHILD (oset);
   return n;
 }
References BLOCK_CHILD, DEADJOB, i, INTERNAL_DEBUG, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobs, js, n, and UNBLOCK_CHILD.
Referenced by decode_prompt_string().
current_working_directory()
static char* current_working_directory () static
Definition at line 383 of file jobs.c.
 {
   char *dir;
   static char d[PATH_MAX];
   dir = get_string_value ("PWD");
   if (dir == 0 && the_current_working_directory && no_symbolic_links)
     dir = the_current_working_directory;
   if (dir == 0)
     {
       dir = getcwd (d, sizeof(d));
       if (dir)
     dir = d;
     }
   return (dir == 0) ? "<unknown>" : dir;
 }
References dir, get_string_value(), getcwd, no_symbolic_links, PATH_MAX, and the_current_working_directory.
Referenced by notify_of_job_status(), print_pipeline(), and start_job().
debug_print_pgrps()
void debug_print_pgrps (void)
default_tty_job_signals()
void default_tty_job_signals ()
Definition at line 2370 of file jobs.c.
 {
   if (signal_is_trapped (SIGTSTP) == 0 && signal_is_hard_ignored (SIGTSTP))
     set_signal_handler (SIGTSTP, SIG_IGN);
   else
     set_signal_handler (SIGTSTP, SIG_DFL);
   if (signal_is_trapped (SIGTTIN) == 0 && signal_is_hard_ignored (SIGTTIN))
     set_signal_handler (SIGTTIN, SIG_IGN);
   else
     set_signal_handler (SIGTTIN, SIG_DFL);
   if (signal_is_trapped (SIGTTOU) == 0 && signal_is_hard_ignored (SIGTTOU))
     set_signal_handler (SIGTTOU, SIG_IGN);
   else
     set_signal_handler (SIGTTOU, SIG_DFL);
 }
References set_signal_handler, SIG_DFL, SIG_IGN, signal_is_hard_ignored(), signal_is_trapped(), SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by make_child(), and set_job_control().
delete_all_jobs()
void delete_all_jobs (int running_only)
Definition at line 4712 of file jobs.c.
 {
   register int i;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   /* XXX - need to set j_lastj, j_firstj appropriately if running_only != 0. */
   if (js.j_jobslots)
     {
       js.j_current = js.j_previous = NO_JOB;
       /* XXX could use js.j_firstj here */
       for (i = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
         INTERNAL_DEBUG (("delete_all_jobs: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
         INTERNAL_DEBUG (("delete_all_jobs: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i] && (running_only == 0 || (running_only && RUNNING(i))))
         /* We don't want to add any of these pids to bgpids.  If running_only
            is non-zero, we don't want to add running jobs to the list.
            If we are interested in all jobs, not just running jobs, and
            we are going to clear the bgpids list below (bgp_clear()), we
            don't need to bother. */
         delete_job (i, DEL_WARNSTOPPED|DEL_NOBGPID);
     }
       if (running_only == 0)
     {
       free ((char *)jobs);
       js.j_jobslots = 0;
       js.j_firstj = js.j_lastj = js.j_njobs = 0;
     }
     }
   if (running_only == 0)
     bgp_clear ();
   UNBLOCK_CHILD (oset);
 }
References bgp_clear(), BLOCK_CHILD, DEL_NOBGPID, DEL_WARNSTOPPED, delete_job(), free, i, INTERNAL_DEBUG, jobstats::j_current, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobstats::j_njobs, jobstats::j_previous, jobs, js, NO_JOB, RUNNING, and UNBLOCK_CHILD.
Referenced by push_builtin(), and without_job_control().
delete_job()
void delete_job (int job_index, int dflags)
Definition at line 1386 of file jobs.c.
 {
   register JOB *temp;
   PROCESS *proc;
   int ndel;
   if (js.j_jobslots == 0 || jobs_list_frozen)
     return;
   if ((dflags & DEL_WARNSTOPPED) && subshell_environment == 0 && STOPPED (job_index))
     internal_warning (_("deleting stopped job %d with process group %ld"), job_index+1, (long)jobs[job_index]->pgrp);
   temp = jobs[job_index];
   if (temp == 0)
     return;
   if ((dflags & DEL_NOBGPID) == 0 && (temp->flags & (J_ASYNC|J_FOREGROUND)) == J_ASYNC)
     {
       proc = find_last_proc (job_index, 0);
       if (proc)
     bgp_add (proc->pid, process_exit_status (proc->status));
     }
   jobs[job_index] = (JOB *)NULL;
   if (temp == js.j_lastmade)
     js.j_lastmade = 0;
   else if (temp == js.j_lastasync)
     js.j_lastasync = 0;
   free (temp->wd);
   ndel = discard_pipeline (temp->pipe);
   js.c_injobs -= ndel;
   if (temp->state == JDEAD)
     {
       /* XXX - save_pipeline and restore_pipeline (e.g., for DEBUG trap) can
      mess with this total. */
       js.c_reaped -= ndel;  /* assumes proc hadn't been reaped earlier */
       js.j_ndead--;
       if (js.c_reaped < 0)
     {
       INTERNAL_DEBUG (("delete_job (%d pgrp %d): js.c_reaped (%d) < 0 ndel = %d js.j_ndead = %d", job_index, temp->pgrp, js.c_reaped, ndel, js.j_ndead));
       js.c_reaped = 0;
     }
     }
   if (temp->deferred)
     dispose_command (temp->deferred);
   free (temp);
   js.j_njobs--;
   if (js.j_njobs == 0)
     js.j_firstj = js.j_lastj = 0;
   else if (jobs[js.j_firstj] == 0 || jobs[js.j_lastj] == 0)
     reset_job_indices ();
   if (job_index == js.j_current || job_index == js.j_previous)
     reset_current ();
 }
References _, bgp_add(), jobstats::c_injobs, jobstats::c_reaped, DEL_NOBGPID, DEL_WARNSTOPPED, discard_pipeline(), dispose_command(), find_last_proc(), job::flags, free, INTERNAL_DEBUG, internal_warning(), J_ASYNC, jobstats::j_current, jobstats::j_firstj, J_FOREGROUND, jobstats::j_jobslots, jobstats::j_lastasync, jobstats::j_lastj, jobstats::j_lastmade, jobstats::j_ndead, jobstats::j_njobs, jobstats::j_previous, JDEAD, jobs, jobs_list_frozen, js, NULL, job::pgrp, proc::pid, job::pipe, process_exit_status(), reset_current(), reset_job_indices(), job::state, STOPPED, subshell_environment, and job::wd.
Referenced by cleanup_dead_jobs(), delete_all_jobs(), delete_old_job(), and wait_for_any_job().
delete_old_job()
static void delete_old_job (pid_t pid) static
Definition at line 1265 of file jobs.c.
 {
   PROCESS *p;
   int job;
   job = find_job (pid, 0, &p);
   if (job != NO_JOB)
     {
       INTERNAL_DEBUG (("delete_old_job: found pid %d in job %d with state %d", pid, job, jobs[job]->state));
       if (JOBSTATE (job) == JDEAD)
     delete_job (job, DEL_NOBGPID);
       else
     {
       internal_debug (_("forked pid %d appears in running job %d"), pid, job+1);
       if (p)
         p->pid = 0;
     }
     }
 }
References _, DEL_NOBGPID, delete_job(), find_job(), internal_debug(), INTERNAL_DEBUG, JDEAD, jobs, JOBSTATE, NO_JOB, p, pid, and state.
Referenced by make_child().
describe_pid()
void describe_pid (pid_t pid)
Definition at line 1826 of file jobs.c.
 {
   int job;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   job = find_job (pid, 0, NULL);
   if (job != NO_JOB)
     fprintf (stderr, "[%d] %ld\n", job + 1, (long)pid);
   else
     programming_error (_("describe_pid: %ld: no such pid"), (long)pid);
   UNBLOCK_CHILD (oset);
 }
References _, BLOCK_CHILD, find_job(), fprintf(), NO_JOB, NULL, pid, programming_error(), stderr, and UNBLOCK_CHILD.
discard_last_procsub_child()
void discard_last_procsub_child ()
Definition at line 453 of file jobs.c.
 {
   PROCESS *disposer;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   disposer = last_procsub_child;
   last_procsub_child = (PROCESS *)NULL;
   UNBLOCK_CHILD (oset);
   if (disposer)
     discard_pipeline (disposer);
 }
References BLOCK_CHILD, discard_pipeline(), last_procsub_child, NULL, and UNBLOCK_CHILD.
discard_pipeline()
int discard_pipeline (PROCESS * chain)
Definition at line 1463 of file jobs.c.
 {
   register PROCESS *this, *next;
   int n;
   this = chain;
   n = 0;
   do
     {
       next = this->next;
       FREE (this->command);
       free (this);
       n++;
       this = next;
     }
   while (this != chain);
   return n;
 }
References FREE, free, n, and next.
Referenced by cleanup_the_pipeline(), delete_job(), discard_last_procsub_child(), and restore_pipeline().
end_job_control()
void end_job_control ()
Definition at line 5012 of file jobs.c.
 {
   if (job_control)
     terminate_stopped_jobs ();
   if (original_pgrp >= 0 && terminal_pgrp != original_pgrp)
     give_terminal_to (original_pgrp, 1);
   if (original_pgrp >= 0 && setpgid (0, original_pgrp) == 0)
     shell_pgrp = original_pgrp;
 }
References give_terminal_to(), job_control, original_pgrp, setpgid, shell_pgrp, terminal_pgrp, and terminate_stopped_jobs().
Referenced by exit_shell(), open_shell_script(), and termsig_handler().
find_job()
static int find_job (pid_t pid, int alive_only, PROCESS ** procp) static
Definition at line 1764 of file jobs.c.
 {
   register int i;
   PROCESS *p;
   /* XXX could use js.j_firstj here, and should check js.j_lastj */
   for (i = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
     INTERNAL_DEBUG (("find_job: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
     INTERNAL_DEBUG (("find_job: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i])
     {
       p = jobs[i]->pipe;
       do
         {
           if (p->pid == pid && ((alive_only == 0 && PRECYCLED(p) == 0) || PALIVE(p)))
         {
           if (procp)
             *procp = p;
           return (i);
         }
           p = p->next;
         }
       while (p != jobs[i]->pipe);
     }
     }
   return (NO_JOB);
 }
References i, INTERNAL_DEBUG, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobs, js, NO_JOB, p, PALIVE, pid, job::pipe, and PRECYCLED.
Referenced by delete_old_job(), describe_pid(), find_pipeline(), get_job_by_pid(), wait_for(), and wait_for_single_pid().
find_last_pid()
static pid_t find_last_pid (int job, int block) static
Definition at line 2567 of file jobs.c.
 {
   PROCESS *p;
   p = find_last_proc (job, block);
   /* Possible race condition here. */
   return p->pid;
 }
References find_last_proc(), and p.
Referenced by mark_dead_jobs_as_notified(), notify_of_job_status(), start_job(), wait_for_any_job(), wait_for_background_pids(), and wait_for_job().
find_last_proc()
static PROCESS* find_last_proc (int job, int block) static
Definition at line 2546 of file jobs.c.
 {
   register PROCESS *p;
   sigset_t set, oset;
   if (block)
     BLOCK_CHILD (set, oset);
   p = jobs[job]->pipe;
   while (p && p->next != jobs[job]->pipe)
     p = p->next;
   if (block)
     UNBLOCK_CHILD (oset);
   return (p);
 }
References BLOCK_CHILD, jobs, p, job::pipe, and UNBLOCK_CHILD.
Referenced by delete_job(), and find_last_pid().
find_pid_in_pipeline()
static PROCESS* find_pid_in_pipeline (pid_t pid, PROCESS * pipeline, int alive_only) static
Definition at line 1687 of file jobs.c.
 {
   PROCESS *p;
   p = pipeline;
   do
     {
       /* Return it if we found it.  Don't ever return a recycled pid. */
       if (p->pid == pid && ((alive_only == 0 && PRECYCLED(p) == 0) || PALIVE(p)))
     return (p);
       p = p->next;
     }
   while (p != pipeline);
   return ((PROCESS *)NULL);
 }
References NULL, p, PALIVE, pid, pipeline(), and PRECYCLED.
Referenced by find_pipeline().
find_pipeline()
static PROCESS* find_pipeline (pid_t pid, int alive_only, int * jobp) static
Definition at line 1711 of file jobs.c.
 {
   int job;
   PROCESS *p;
   struct pipeline_saver *save;
   /* See if this process is in the pipeline that we are building. */
   p = (PROCESS *)NULL;
   if (jobp)
     *jobp = NO_JOB;
   if (the_pipeline && (p = find_pid_in_pipeline (pid, the_pipeline, alive_only)))
     return (p);
   /* Is this process in a saved pipeline? */
   for (save = saved_pipeline; save; save = save->next)
     if (save->pipeline && (p = find_pid_in_pipeline (pid, save->pipeline, alive_only)))
       return (p);
 #if defined (PROCESS_SUBSTITUTION)
   if (procsubs.nproc > 0 && (p = procsub_search (pid)) && ((alive_only == 0 && PRECYCLED(p) == 0) || PALIVE(p)))
     return (p);
 #endif
   job = find_job (pid, alive_only, &p);
   if (jobp)
     *jobp = job;
   return (job == NO_JOB) ? (PROCESS *)NULL : jobs[job]->pipe;
 }
References find_job(), find_pid_in_pipeline(), jobs, pipeline_saver::next, NO_JOB, procchain::nproc, NULL, p, PALIVE, pid, pipeline_saver::pipeline, PRECYCLED, procsubs, saved_pipeline, and the_pipeline.
Referenced by find_process(), kill_pid(), and wait_for_single_pid().
find_process()
static PROCESS* find_process (pid_t pid, int alive_only, int * jobp) static
Definition at line 1748 of file jobs.c.
 {
   PROCESS *p;
   p = find_pipeline (pid, alive_only, jobp);
   while (p && p->pid != pid)
     p = p->next;
   return p;
 }
References find_pipeline(), p, and pid.
Referenced by add_process(), and waitchld().
freeze_jobs_list()
int freeze_jobs_list ()
Definition at line 4933 of file jobs.c.
 {
   int o;
   o = jobs_list_frozen;
   jobs_list_frozen = 1;
   return o;
 }
References jobs_list_frozen.
Referenced by execute_pipeline().
get_job_by_pid()
int get_job_by_pid (pid_t pid, int block, PROCESS ** procp)
Definition at line 1805 of file jobs.c.
 {
   int job;
   sigset_t set, oset;
   if (block)
     BLOCK_CHILD (set, oset);
   job = find_job (pid, 0, procp);
   if (block)
     UNBLOCK_CHILD (oset);
   return job;
 }
References BLOCK_CHILD, find_job(), pid, and UNBLOCK_CHILD.
get_original_tty_job_signals()
void get_original_tty_job_signals ()
Definition at line 2390 of file jobs.c.
 {
   static int fetched = 0;
   if (fetched == 0)
     {
       if (interactive_shell)
     {
       set_original_signal (SIGTSTP, SIG_DFL);
       set_original_signal (SIGTTIN, SIG_DFL);
       set_original_signal (SIGTTOU, SIG_DFL);
     }
       else
     {
       get_original_signal (SIGTSTP);
       get_original_signal (SIGTTIN);
       get_original_signal (SIGTTOU);
     }
       fetched = 1;
     }
 }
References get_original_signal(), interactive_shell, set_original_signal(), SIG_DFL, SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by initialize_traps().
get_tty_state()
int get_tty_state ()
Definition at line 2471 of file jobs.c.
 {
   int tty;
   tty = input_tty ();
   if (tty != -1)
     {
 #if defined (NEW_TTY_DRIVER)
       ioctl (tty, TIOCGETP, &shell_tty_info);
       ioctl (tty, TIOCGETC, &shell_tchars);
       ioctl (tty, TIOCGLTC, &shell_ltchars);
 #endif /* NEW_TTY_DRIVER */
 #if defined (TERMIO_TTY_DRIVER)
       ioctl (tty, TCGETA, &shell_tty_info);
 #endif /* TERMIO_TTY_DRIVER */
 #if defined (TERMIOS_TTY_DRIVER)
       if (tcgetattr (tty, &shell_tty_info) < 0)
     {
 #if 0
       /* Only print an error message if we're really interactive at
          this time. */
       if (interactive)
         sys_error ("[%ld: %d (%d)] tcgetattr", (long)getpid (), shell_level, tty);
 #endif
       return -1;
     }
 #endif /* TERMIOS_TTY_DRIVER */
       if (check_window_size)
     get_new_window_size (0, (int *)0, (int *)0);
     }
   return 0;
 }
References check_window_size, get_new_window_size(), getpid(), input_tty, interactive, ioctl(), shell_level, shell_tty_info, sys_error(), TCGETA, tcgetattr(), TIOCGETC, TIOCGETP, and TIOCGLTC.
Referenced by initialize_job_control(), start_job(), and wait_for().
give_terminal_to()
int give_terminal_to (pid_t pgrp, int force)
Definition at line 4641 of file jobs.c.
 {
   sigset_t set, oset;
   int r, e;
   r = 0;
   if (job_control || force)
     {
       sigemptyset (&set);
       sigaddset (&set, SIGTTOU);
       sigaddset (&set, SIGTTIN);
       sigaddset (&set, SIGTSTP);
       sigaddset (&set, SIGCHLD);
       sigemptyset (&oset);
       sigprocmask (SIG_BLOCK, &set, &oset);
       if (tcsetpgrp (shell_tty, pgrp) < 0)
     {
       /* Maybe we should print an error message? */
 #if 0
       sys_error ("tcsetpgrp(%d) failed: pid %ld to pgrp %ld",
         shell_tty, (long)getpid(), (long)pgrp);
 #endif
       r = -1;
       e = errno;
     }
       else
     terminal_pgrp = pgrp;
       sigprocmask (SIG_SETMASK, &oset, (sigset_t *)NULL);
     }
   if (r == -1)
     errno = e;
   return r;
 }
References errno, force, getpid(), job_control, NULL, shell_tty, SIG_BLOCK, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), sigprocmask(), SIGTSTP, SIGTTIN, SIGTTOU, sys_error(), tcsetpgrp, and terminal_pgrp.
Referenced by end_job_control(), initialize_job_control(), make_child(), maybe_give_terminal_to(), programming_error(), run_debug_trap(), sigstop_sighandler(), start_job(), throw_to_top_level(), and wait_for().
hangup_all_jobs()
void hangup_all_jobs ()
Definition at line 1661 of file jobs.c.
 {
   register int i;
   /* XXX could use js.j_firstj here */
   for (i = 0; i < js.j_jobslots; i++)
     {
       if (jobs[i])
     {
       if  (jobs[i]->flags & J_NOHUP)
         continue;
       killpg (jobs[i]->pgrp, SIGHUP);
       if (STOPPED (i))
         killpg (jobs[i]->pgrp, SIGCONT);
     }
     }
 }
References flags, i, jobstats::j_jobslots, J_NOHUP, jobs, js, killpg, SIGCONT, SIGHUP, and STOPPED.
Referenced by exit_shell(), and termsig_handler().
ignore_tty_job_signals()
void ignore_tty_job_signals ()
Definition at line 2358 of file jobs.c.
 {
   set_signal_handler (SIGTSTP, SIG_IGN);
   set_signal_handler (SIGTTIN, SIG_IGN);
   set_signal_handler (SIGTTOU, SIG_IGN);
 }
References set_signal_handler, SIG_IGN, SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by make_child().
init_job_stats()
void init_job_stats ()
Definition at line 373 of file jobs.c.
 {
   js = zerojs;
 }
References js, and zerojs.
Referenced by initialize_subshell().
initialize_job_control()
int initialize_job_control (int force)
Definition at line 4370 of file jobs.c.
 {
   pid_t t;
   int t_errno, tty_sigs;
   t_errno = -1;
   shell_pgrp = getpgid (0);
   if (shell_pgrp == -1)
     {
       sys_error (_("initialize_job_control: getpgrp failed"));
       exit (1);
     }
   /* We can only have job control if we are interactive unless we force it. */
   if (interactive == 0 && force == 0)
     {
       job_control = 0;
       original_pgrp = NO_PID;
       shell_tty = fileno (stderr);
       terminal_pgrp = tcgetpgrp (shell_tty);    /* for checking later */
     }
   else
     {
       shell_tty = -1;
       /* If forced_interactive is set, we skip the normal check that stderr
      is attached to a tty, so we need to check here.  If it's not, we
      need to see whether we have a controlling tty by opening /dev/tty,
      since trying to use job control tty pgrp manipulations on a non-tty
      is going to fail. */
       if (forced_interactive && isatty (fileno (stderr)) == 0)
     shell_tty = open ("/dev/tty", O_RDWR|O_NONBLOCK);
       /* Get our controlling terminal.  If job_control is set, or
      interactive is set, then this is an interactive shell no
      matter where fd 2 is directed. */
       if (shell_tty == -1)
     shell_tty = dup (fileno (stderr));  /* fd 2 */
       if (shell_tty != -1)
     shell_tty = move_to_high_fd (shell_tty, 1, -1);
       /* Compensate for a bug in systems that compiled the BSD
      rlogind with DEBUG defined, like NeXT and Alliant. */
       if (shell_pgrp == 0)
     {
       shell_pgrp = getpid ();
       setpgid (0, shell_pgrp);
       if (shell_tty != -1)
         tcsetpgrp (shell_tty, shell_pgrp);
     }
       tty_sigs = 0;
       while ((terminal_pgrp = tcgetpgrp (shell_tty)) != -1)
     {
       if (shell_pgrp != terminal_pgrp)
         {
           SigHandler *ottin;
           CHECK_TERMSIG;
           ottin = set_signal_handler (SIGTTIN, SIG_DFL);
           kill (0, SIGTTIN);
           set_signal_handler (SIGTTIN, ottin);
           if (tty_sigs++ > 16)
         {
           sys_error (_("initialize_job_control: no job control in background"));
           job_control = 0;
           original_pgrp = terminal_pgrp;    /* for eventual give_terminal_to */
           goto just_bail;
         }
           continue;
         }
       break;
     }
       if (terminal_pgrp == -1)
     t_errno = errno;
       /* Make sure that we are using the new line discipline. */
       if (set_new_line_discipline (shell_tty) < 0)
     {
       sys_error (_("initialize_job_control: line discipline"));
       job_control = 0;
     }
       else
     {
       original_pgrp = shell_pgrp;
       shell_pgrp = getpid ();
       if ((original_pgrp != shell_pgrp) && (setpgid (0, shell_pgrp) < 0))
         {
           sys_error (_("initialize_job_control: setpgid"));
           shell_pgrp = original_pgrp;
         }
       job_control = 1;
       /* If (and only if) we just set our process group to our pid,
          thereby becoming a process group leader, and the terminal
          is not in the same process group as our (new) process group,
          then set the terminal's process group to our (new) process
          group.  If that fails, set our process group back to what it
          was originally (so we can still read from the terminal) and
          turn off job control.  */
       if (shell_pgrp != original_pgrp && shell_pgrp != terminal_pgrp)
         {
           if (give_terminal_to (shell_pgrp, 0) < 0)
         {
           t_errno = errno;
           setpgid (0, original_pgrp);
           shell_pgrp = original_pgrp;
           errno = t_errno;
           sys_error (_("cannot set terminal process group (%d)"), shell_pgrp);
           job_control = 0;
         }
         }
       if (job_control && ((t = tcgetpgrp (shell_tty)) == -1 || t != shell_pgrp))
         {
           if (t_errno != -1)
         errno = t_errno;
           sys_error (_("cannot set terminal process group (%d)"), t);
           job_control = 0;
         }
     }
       if (job_control == 0)
     internal_error (_("no job control in this shell"));
     }
 just_bail:
   running_in_background = terminal_pgrp != shell_pgrp;
   if (shell_tty != fileno (stderr))
     SET_CLOSE_ON_EXEC (shell_tty);
   set_signal_handler (SIGCHLD, sigchld_handler);
   change_flag ('m', job_control ? '-' : '+');
   if (interactive)
     get_tty_state ();
   set_maxchild (0);
   return job_control;
 }
References _, change_flag(), CHECK_TERMSIG, dup(), errno, exit(), fileno(), force, forced_interactive, get_tty_state(), getpgid, getpid(), give_terminal_to(), interactive, internal_error(), isatty(), job_control, kill(), move_to_high_fd(), NO_PID, O_NONBLOCK, O_RDWR, open(), original_pgrp, running_in_background, SET_CLOSE_ON_EXEC, set_maxchild(), set_new_line_discipline(), set_signal_handler, setpgid, shell_pgrp, shell_tty, SIG_DFL, SIGCHLD, sigchld_handler(), SIGTTIN, stderr, sys_error(), t, tcgetpgrp(), tcsetpgrp, and terminal_pgrp.
Referenced by push_builtin(), restart_job_control(), and shell_initialize().
initialize_job_signals()
void initialize_job_signals ()
Definition at line 4590 of file jobs.c.
 {
   if (interactive)
     {
       set_signal_handler (SIGINT, sigint_sighandler);
       set_signal_handler (SIGTSTP, SIG_IGN);
       set_signal_handler (SIGTTOU, SIG_IGN);
       set_signal_handler (SIGTTIN, SIG_IGN);
     }
   else if (job_control)
     {
       old_tstp = set_signal_handler (SIGTSTP, sigstop_sighandler);
       old_ttin = set_signal_handler (SIGTTIN, sigstop_sighandler);
       old_ttou = set_signal_handler (SIGTTOU, sigstop_sighandler);
     }
   /* Leave disposition unmodified for non-interactive shells without job
      control. */
 }
References interactive, job_control, old_tstp, old_ttin, old_ttou, set_signal_handler, SIG_IGN, SIGINT, sigint_sighandler(), sigstop_sighandler(), SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by initialize_signals(), push_builtin(), set_job_control(), and sigcont_sighandler().
j_strsignal()
static char* j_strsignal (int s) static
Definition at line 1845 of file jobs.c.
 {
   char *x;
   x = strsignal (s);
   if (x == 0)
     {
       x = retcode_name_buffer;
       snprintf (x, sizeof(retcode_name_buffer), _("Signal %d"), s);
     }
   return x;
 }
References _, retcode_name_buffer, s, snprintf(), strsignal(), and x.
Referenced by notify_of_job_status(), and printable_job_status().
job_exit_signal()
int job_exit_signal (int job)
Definition at line 2873 of file jobs.c.
 {
   return (process_exit_signal (raw_job_exit_status (job)));
 }
References process_exit_signal(), and raw_job_exit_status().
Referenced by wait_for().
job_exit_status()
int job_exit_status (int job)
Definition at line 2866 of file jobs.c.
 {
   return (process_exit_status (raw_job_exit_status (job)));
 }
References process_exit_status(), and raw_job_exit_status().
Referenced by execute_pipeline(), wait_for(), and wait_for_any_job().
job_last_running()
static int job_last_running (int job) static
Definition at line 3412 of file jobs.c.
 {
   return (most_recent_job_in_state (job, JRUNNING));
 }
References JRUNNING, and most_recent_job_in_state().
Referenced by reset_current(), and set_current_job().
job_last_stopped()
static int job_last_stopped (int job) static
Definition at line 3403 of file jobs.c.
 {
   return (most_recent_job_in_state (job, JSTOPPED));
 }
References JSTOPPED, and most_recent_job_in_state().
Referenced by reset_current(), and set_current_job().
job_signal_status()
static WAIT job_signal_status (int job) static
Definition at line 2813 of file jobs.c.
 {
   register PROCESS *p;
   WAIT s;
   p = jobs[job]->pipe;
   do
     {
       s = p->status;
       if (WIFSIGNALED(s) || WIFSTOPPED(s))
     break;
       p = p->next;
     }
   while (p != jobs[job]->pipe);
   return s;
 }
References jobs, p, job::pipe, s, WIFSIGNALED, and WIFSTOPPED.
Referenced by wait_for().
job_working_directory()
static char* job_working_directory () static
Definition at line 405 of file jobs.c.
 {
   char *dir;
   dir = get_string_value ("PWD");
   if (dir)
     return (savestring (dir));
   dir = get_working_directory ("job-working-directory");
   if (dir)
     return (dir);
   return (savestring ("<unknown>"));
 }
References dir, get_string_value(), get_working_directory(), and savestring().
Referenced by stop_pipeline().
kill_current_pipeline()
void kill_current_pipeline ()
Definition at line 1680 of file jobs.c.
 {
   stop_making_children ();
   start_pipeline ();
 }
References start_pipeline(), and stop_making_children().
Referenced by execute_pipeline(), execute_subshell_builtin_or_function(), and make_child().
kill_pid()
int kill_pid (pid_t pid, int sig, int group)
Definition at line 3665 of file jobs.c.
 {
   register PROCESS *p;
   int job, result, negative;
   sigset_t set, oset;
   if (pid < -1)
     {
       pid = -pid;
       group = negative = 1;
     }
   else
     negative = 0;
   result = EXECUTION_SUCCESS;
   if (group)
     {
       BLOCK_CHILD (set, oset);
       p = find_pipeline (pid, 0, &job);
       if (job != NO_JOB)
     {
       jobs[job]->flags &= ~J_NOTIFIED;
       /* Kill process in backquotes or one started without job control? */
       /* If we're passed a pid < -1, just call killpg and see what happens  */
       if (negative && jobs[job]->pgrp == shell_pgrp)
         result = killpg (pid, sig);
       /* If we're killing using job control notification, for example,
          without job control active, we have to do things ourselves. */
       else if (jobs[job]->pgrp == shell_pgrp)   /* XXX - IS_JOBCONTROL(job) == 0? */
         {
           p = jobs[job]->pipe;
           do
         {
           if (PALIVE (p) == 0)
             continue;       /* avoid pid recycling problem */
           kill (p->pid, sig);
           if (PEXITED (p) && (sig == SIGTERM || sig == SIGHUP))
             kill (p->pid, SIGCONT);
           p = p->next;
         }
           while  (p != jobs[job]->pipe);
         }
       else
         {
           result = killpg (jobs[job]->pgrp, sig);
           if (p && STOPPED (job) && (sig == SIGTERM || sig == SIGHUP))
         killpg (jobs[job]->pgrp, SIGCONT);
           /* If we're continuing a stopped job via kill rather than bg or
          fg, emulate the `bg' behavior. */
           if (p && STOPPED (job) && (sig == SIGCONT))
         {
           set_job_running (job);
           jobs[job]->flags &= ~J_FOREGROUND;
           jobs[job]->flags |= J_NOTIFIED;
         }
         }
     }
       else
     result = killpg (pid, sig);
       UNBLOCK_CHILD (oset);
     }
   else
     result = kill (pid, sig);
   return (result);
 }
References BLOCK_CHILD, EXECUTION_SUCCESS, find_pipeline(), job::flags, J_FOREGROUND, J_NOTIFIED, jobs, kill(), killpg, NO_JOB, p, PALIVE, PEXITED, pid, job::pipe, set_job_running(), shell_pgrp, SIGCONT, SIGHUP, SIGTERM, STOPPED, and UNBLOCK_CHILD.
list_all_jobs()
void list_all_jobs (int format)
Definition at line 2109 of file jobs.c.
 {
   cleanup_dead_jobs ();
   map_over_jobs (print_job, format, -1);
 }
References cleanup_dead_jobs(), format(), map_over_jobs(), and print_job().
list_one_job()
void list_one_job (JOB * job, int format, int ignore, int job_index)
Definition at line 2082 of file jobs.c.
 {
   pretty_print_job (job_index, format, stdout);
   cleanup_dead_jobs ();
 }
References cleanup_dead_jobs(), format(), pretty_print_job(), and stdout.
list_running_jobs()
void list_running_jobs (int format)
Definition at line 2099 of file jobs.c.
 {
   cleanup_dead_jobs ();
   map_over_jobs (print_job, format, (int)JRUNNING);
 }
References cleanup_dead_jobs(), format(), JRUNNING, map_over_jobs(), and print_job().
list_stopped_jobs()
void list_stopped_jobs (int format)
Definition at line 2091 of file jobs.c.
 {
   cleanup_dead_jobs ();
   map_over_jobs (print_job, format, (int)JSTOPPED);
 }
References cleanup_dead_jobs(), format(), JSTOPPED, map_over_jobs(), and print_job().
make_child()
pid_t make_child (char * command, int flags)
Definition at line 2121 of file jobs.c.
 {
   int async_p, forksleep;
   sigset_t set, oset, termset, chldset, oset_copy;
   pid_t pid;
   SigHandler *oterm;
   sigemptyset (&oset_copy);
   sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &oset_copy);
   sigaddset (&oset_copy, SIGTERM);
   /* Block SIGTERM here and unblock in child after fork resets the
      set of pending signals. */
   sigemptyset (&set);
   sigaddset (&set, SIGCHLD);
   sigaddset (&set, SIGINT);
   sigaddset (&set, SIGTERM);
   sigemptyset (&oset);
   sigprocmask (SIG_BLOCK, &set, &oset);
   /* Blocked in the parent, child will receive it after unblocking SIGTERM */
   if (interactive_shell)
     oterm = set_signal_handler (SIGTERM, SIG_DFL);
   making_children ();
   async_p = (flags & FORK_ASYNC);
   forksleep = 1;
 #if defined (BUFFERED_INPUT)
   /* If default_buffered_input is active, we are reading a script.  If
      the command is asynchronous, we have already duplicated /dev/null
      as fd 0, but have not changed the buffered stream corresponding to
      the old fd 0.  We don't want to sync the stream in this case. */
   if (default_buffered_input != -1 &&
       (!async_p || default_buffered_input > 0))
     sync_buffered_stream (default_buffered_input);
 #endif /* BUFFERED_INPUT */
   /* Create the child, handle severe errors.  Retry on EAGAIN. */
   while ((pid = fork ()) < 0 && errno == EAGAIN && forksleep < FORKSLEEP_MAX)
     {
       /* bash-4.2 */
       /* keep SIGTERM blocked until we reset the handler to SIG_IGN */
       sigprocmask (SIG_SETMASK, &oset_copy, (sigset_t *)NULL);
       /* If we can't create any children, try to reap some dead ones. */
       waitchld (-1, 0);
       errno = EAGAIN;       /* restore errno */
       sys_error ("fork: retry");
       if (sleep (forksleep) != 0)
     break;
       forksleep <<= 1;
       if (interrupt_state)
     break;
       sigprocmask (SIG_SETMASK, &set, (sigset_t *)NULL);
     }
   if (pid != 0)
     if (interactive_shell)
       set_signal_handler (SIGTERM, oterm);
   if (pid < 0)
     {
       sys_error ("fork");
       /* Kill all of the processes in the current pipeline. */
       terminate_current_pipeline ();
       /* Discard the current pipeline, if any. */
       if (the_pipeline)
     kill_current_pipeline ();
       set_exit_status (EX_NOEXEC);
       throw_to_top_level ();    /* Reset signals, etc. */
     }
   if (pid == 0)
     {
       /* In the child.  Give this child the right process group, set the
      signals to the default state for a new process. */
       pid_t mypid;
       subshell_environment |= SUBSHELL_IGNTRAP;
       /* If this ends up being changed to modify or use `command' in the
      child process, go back and change callers who free `command' in
      the child process when this returns. */
       mypid = getpid ();
 #if defined (BUFFERED_INPUT)
       /* Close default_buffered_input if it's > 0.  We don't close it if it's
      0 because that's the file descriptor used when redirecting input,
      and it's wrong to close the file in that case. */
       unset_bash_input (0);
 #endif /* BUFFERED_INPUT */
       CLRINTERRUPT; /* XXX - children have their own interrupt state */
       /* Restore top-level signal mask, including unblocking SIGTERM */
       restore_sigmask ();
       if (job_control)
     {
       /* All processes in this pipeline belong in the same
          process group. */
       if (pipeline_pgrp == 0)   /* This is the first child. */
         pipeline_pgrp = mypid;
       /* Check for running command in backquotes. */
       if (pipeline_pgrp == shell_pgrp)
         ignore_tty_job_signals ();
       else
         default_tty_job_signals ();
       /* Set the process group before trying to mess with the terminal's
          process group.  This is mandated by POSIX. */
       /* This is in accordance with the Posix 1003.1 standard,
          section B.7.2.4, which says that trying to set the terminal
          process group with tcsetpgrp() to an unused pgrp value (like
          this would have for the first child) is an error.  Section
          B.4.3.3, p. 237 also covers this, in the context of job control
          shells. */
       if (setpgid (mypid, pipeline_pgrp) < 0)
         sys_error (_("child setpgid (%ld to %ld)"), (long)mypid, (long)pipeline_pgrp);
       /* By convention (and assumption above), if
          pipeline_pgrp == shell_pgrp, we are making a child for
          command substitution.
          In this case, we don't want to give the terminal to the
          shell's process group (we could be in the middle of a
          pipeline, for example). */
       if ((flags & FORK_NOTERM) == 0 && async_p == 0 && pipeline_pgrp != shell_pgrp && ((subshell_environment&(SUBSHELL_ASYNC|SUBSHELL_PIPE)) == 0) && running_in_background == 0)
         give_terminal_to (pipeline_pgrp, 0);
 #if defined (PGRP_PIPE)
       if (pipeline_pgrp == mypid)
         pipe_read (pgrp_pipe);
 #endif
     }
       else          /* Without job control... */
     {
       if (pipeline_pgrp == 0)
         pipeline_pgrp = shell_pgrp;
       /* If these signals are set to SIG_DFL, we encounter the curious
          situation of an interactive ^Z to a running process *working*
          and stopping the process, but being unable to do anything with
          that process to change its state.  On the other hand, if they
          are set to SIG_IGN, jobs started from scripts do not stop when
          the shell running the script gets a SIGTSTP and stops. */
       default_tty_job_signals ();
     }
 #if defined (PGRP_PIPE)
       /* Release the process group pipe, since our call to setpgid ()
      is done.  The last call to sh_closepipe is done in stop_pipeline. */
       sh_closepipe (pgrp_pipe);
 #endif /* PGRP_PIPE */
       /* Don't set last_asynchronous_pid in the child */
 #if defined (RECYCLES_PIDS)
       if (last_asynchronous_pid == mypid)
     /* Avoid pid aliasing.  1 seems like a safe, unusual pid value. */
     last_asynchronous_pid = 1;
 #endif
     }
   else
     {
       /* In the parent.  Remember the pid of the child just created
      as the proper pgrp if this is the first child. */
       if (job_control)
     {
       if (pipeline_pgrp == 0)
         {
           pipeline_pgrp = pid;
           /* Don't twiddle terminal pgrps in the parent!  This is the bug,
          not the good thing of twiddling them in the child! */
           /* give_terminal_to (pipeline_pgrp, 0); */
         }
       /* This is done on the recommendation of the Rationale section of
          the POSIX 1003.1 standard, where it discusses job control and
          shells.  It is done to avoid possible race conditions. (Ref.
          1003.1 Rationale, section B.4.3.3, page 236). */
       setpgid (pid, pipeline_pgrp);
     }
       else
     {
       if (pipeline_pgrp == 0)
         pipeline_pgrp = shell_pgrp;
     }
       /* Place all processes into the jobs array regardless of the
      state of job_control. */
       add_process (command, pid);
       if (async_p)
     last_asynchronous_pid = pid;
 #if defined (RECYCLES_PIDS)
       else if (last_asynchronous_pid == pid)
     /* Avoid pid aliasing.  1 seems like a safe, unusual pid value. */
     last_asynchronous_pid = 1;
 #endif
       /* Delete the saved status for any job containing this PID in case it's
      been reused. */
       delete_old_job (pid);
       /* Perform the check for pid reuse unconditionally.  Some systems reuse
      PIDs before giving a process CHILD_MAX/_SC_CHILD_MAX unique ones. */
       bgp_delete (pid);     /* new process, discard any saved status */
       last_made_pid = pid;
       /* keep stats */
       js.c_totforked++;
       js.c_living++;
       /* Unblock SIGTERM, SIGINT, and SIGCHLD unless creating a pipeline, in
      which case SIGCHLD remains blocked until all commands in the pipeline
      have been created (execute_cmd.c:execute_pipeline()). */
       sigprocmask (SIG_SETMASK, &oset, (sigset_t *)NULL);
     }
   return (pid);
 }
References _, add_process(), bgp_delete(), jobstats::c_living, jobstats::c_totforked, CLRINTERRUPT, default_tty_job_signals(), delete_old_job(), EAGAIN, errno, EX_NOEXEC, flags, fork(), FORK_ASYNC, FORK_NOTERM, FORKSLEEP_MAX, getpid(), give_terminal_to(), ignore_tty_job_signals(), interactive_shell, interrupt_state, job_control, js, kill_current_pipeline(), last_asynchronous_pid, last_made_pid, making_children(), NULL, pid, pipeline_pgrp, restore_sigmask(), running_in_background, set_exit_status(), set_signal_handler, setpgid, sh_closepipe(), shell_pgrp, SIG_BLOCK, SIG_DFL, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, sigprocmask(), SIGTERM, sleep(), SUBSHELL_ASYNC, subshell_environment, SUBSHELL_IGNTRAP, SUBSHELL_PIPE, sys_error(), terminate_current_pipeline(), the_pipeline, throw_to_top_level(), unset_bash_input(), and waitchld().
Referenced by command_substitute(), execute_command_internal(), execute_disk_command(), execute_null_command(), execute_simple_command(), and push_builtin().
making_children()
void making_children ()
Definition at line 421 of file jobs.c.
 {
   if (already_making_children)
     return;
   already_making_children = 1;
   start_pipeline ();
 }
References already_making_children, and start_pipeline().
Referenced by make_child().
map_over_jobs()
static int map_over_jobs (sh_job_map_func_t * func, int arg1, int arg2) static
Definition at line 1596 of file jobs.c.
 {
   register int i;
   int result;
   sigset_t set, oset;
   if (js.j_jobslots == 0)
     return 0;
   BLOCK_CHILD (set, oset);
   /* XXX could use js.j_firstj here */
   for (i = result = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
     INTERNAL_DEBUG (("map_over_jobs: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
     INTERNAL_DEBUG (("map_over_jobs: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i])
     {
       result = (*func)(jobs[i], arg1, arg2, i);
       if (result)
         break;
     }
     }
   UNBLOCK_CHILD (oset);
   return (result);
 }
References BLOCK_CHILD, i, INTERNAL_DEBUG, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobs, js, and UNBLOCK_CHILD.
Referenced by list_all_jobs(), list_running_jobs(), and list_stopped_jobs().
mark_all_jobs_as_dead()
static void mark_all_jobs_as_dead () static
Definition at line 4801 of file jobs.c.
 {
   register int i;
   sigset_t set, oset;
   if (js.j_jobslots == 0)
     return;
   BLOCK_CHILD (set, oset);
   /* XXX could use js.j_firstj here */
   for (i = 0; i < js.j_jobslots; i++)
     if (jobs[i])
       {
     jobs[i]->state = JDEAD;
     js.j_ndead++;
       }
   UNBLOCK_CHILD (oset);
 }
References BLOCK_CHILD, i, jobstats::j_jobslots, jobstats::j_ndead, JDEAD, jobs, js, job::state, and UNBLOCK_CHILD.
Referenced by wait_for_any_job(), wait_for_background_pids(), and wait_for_job().
mark_dead_jobs_as_notified()
static void mark_dead_jobs_as_notified (int force) static
Definition at line 4827 of file jobs.c.
 {
   register int i, ndead, ndeadproc;
   sigset_t set, oset;
   if (js.j_jobslots == 0)
     return;
   BLOCK_CHILD (set, oset);
   /* If FORCE is non-zero, we don't have to keep CHILD_MAX statuses
      around; just run through the array. */
   if (force)
     {
     /* XXX could use js.j_firstj here */
       for (i = 0; i < js.j_jobslots; i++)
     {
       if (jobs[i] && DEADJOB (i) && (interactive_shell || (find_last_pid (i, 0) != last_asynchronous_pid)))
         jobs[i]->flags |= J_NOTIFIED;
     }
       UNBLOCK_CHILD (oset);
       return;
     }
   /* Mark enough dead jobs as notified to keep CHILD_MAX processes left in the
      array with the corresponding not marked as notified.  This is a better
      way to avoid pid aliasing and reuse problems than keeping the POSIX-
      mandated CHILD_MAX jobs around.  delete_job() takes care of keeping the
      bgpids list regulated. */
   /* Count the number of dead jobs */
   /* XXX could use js.j_firstj here */
   for (i = ndead = ndeadproc = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
     INTERNAL_DEBUG (("mark_dead_jobs_as_notified: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
     INTERNAL_DEBUG (("mark_dead_jobs_as_notified: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i] && DEADJOB (i))
     {
       ndead++;
       ndeadproc += processes_in_job (i);
     }
     }
 # if 0
   if (ndeadproc != js.c_reaped)
     itrace("mark_dead_jobs_as_notified: ndeadproc (%d) != js.c_reaped (%d)", ndeadproc, js.c_reaped);
 # endif
   if (ndead != js.j_ndead)
     INTERNAL_DEBUG (("mark_dead_jobs_as_notified: ndead (%d) != js.j_ndead (%d)", ndead, js.j_ndead));
   if (js.c_childmax < 0)
     set_maxchild (0);
   /* Don't do anything if the number of dead processes is less than CHILD_MAX
      and we're not forcing a cleanup. */
   if (ndeadproc <= js.c_childmax)
     {
       UNBLOCK_CHILD (oset);
       return;
     }
 #if 0
 itrace("mark_dead_jobs_as_notified: child_max = %d ndead = %d ndeadproc = %d", js.c_childmax, ndead, ndeadproc);
 #endif
   /* Mark enough dead jobs as notified that we keep CHILD_MAX jobs in
      the list.  This isn't exactly right yet; changes need to be made
      to stop_pipeline so we don't mark the newer jobs after we've
      created CHILD_MAX slots in the jobs array.  This needs to be
      integrated with a way to keep the jobs array from growing without
      bound.  Maybe we wrap back around to 0 after we reach some max
      limit, and there are sufficient job slots free (keep track of total
      size of jobs array (js.j_jobslots) and running count of number of jobs
      in jobs array.  Then keep a job index corresponding to the `oldest job'
      and start this loop there, wrapping around as necessary.  In effect,
      we turn the list into a circular buffer. */
   /* XXX could use js.j_firstj here */
   for (i = 0; i < js.j_jobslots; i++)
     {
       if (jobs[i] && DEADJOB (i) && (interactive_shell || (find_last_pid (i, 0) != last_asynchronous_pid)))
     {
       if (i < js.j_firstj && jobs[i])
         INTERNAL_DEBUG (("mark_dead_jobs_as_notified: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
         INTERNAL_DEBUG (("mark_dead_jobs_as_notified: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       /* If marking this job as notified would drop us down below
          child_max, don't mark it so we can keep at least child_max
          statuses.  XXX -- need to check what Posix actually says
          about keeping statuses. */
       if ((ndeadproc -= processes_in_job (i)) <= js.c_childmax)
         break;
       jobs[i]->flags |= J_NOTIFIED;
     }
     }
   UNBLOCK_CHILD (oset);
 }
References BLOCK_CHILD, jobstats::c_childmax, jobstats::c_reaped, DEADJOB, find_last_pid(), job::flags, force, i, interactive_shell, INTERNAL_DEBUG, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobstats::j_ndead, J_NOTIFIED, jobs, js, last_asynchronous_pid, processes_in_job(), set_maxchild(), and UNBLOCK_CHILD.
Referenced by reap_dead_jobs(), and wait_for_background_pids().
maybe_give_terminal_to()
static int maybe_give_terminal_to (pid_t opgrp, pid_t npgrp, int flags) static
Definition at line 4683 of file jobs.c.
 {
   int tpgrp;
   tpgrp = tcgetpgrp (shell_tty);
   if (tpgrp < 0 && errno == ENOTTY)
     return -1;
   if (tpgrp == npgrp)
     {
       terminal_pgrp = npgrp;
       return 0;
     }
   else if (tpgrp != opgrp)
     {
       internal_debug ("%d: maybe_give_terminal_to: terminal pgrp == %d shell pgrp = %d new pgrp = %d in_background = %d", (int)getpid(), tpgrp, opgrp, npgrp, running_in_background);
       return -1;
     }
   else
     return (give_terminal_to (npgrp, flags));
 }
References ENOTTY, errno, flags, getpid(), give_terminal_to(), internal_debug(), running_in_background, shell_tty, tcgetpgrp(), and terminal_pgrp.
Referenced by stop_pipeline().
most_recent_job_in_state()
static int most_recent_job_in_state (int job, JOB_STATE state) static
Definition at line 3377 of file jobs.c.
 {
   register int i, result;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   for (result = NO_JOB, i = job - 1; i >= 0; i--)
     {
       if (jobs[i] && (JOBSTATE (i) == state))
     {
       result = i;
       break;
     }
     }
   UNBLOCK_CHILD (oset);
   return (result);
 }
References BLOCK_CHILD, i, jobs, JOBSTATE, NO_JOB, state, and UNBLOCK_CHILD.
Referenced by job_last_running(), and job_last_stopped().
nohup_all_jobs()
void nohup_all_jobs (int running_only)
Definition at line 4758 of file jobs.c.
 {
   register int i;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   if (js.j_jobslots)
     {
       /* XXX could use js.j_firstj here */
       for (i = 0; i < js.j_jobslots; i++)
     if (jobs[i] && (running_only == 0 || (running_only && RUNNING(i))))
       nohup_job (i);
     }
   UNBLOCK_CHILD (oset);
 }
References BLOCK_CHILD, i, jobstats::j_jobslots, jobs, js, nohup_job(), RUNNING, and UNBLOCK_CHILD.
nohup_job()
void nohup_job (int job_index)
Definition at line 1449 of file jobs.c.
 {
   register JOB *temp;
   if (js.j_jobslots == 0)
     return;
   if (temp = jobs[job_index])
     temp->flags |= J_NOHUP;
 }
References job::flags, jobstats::j_jobslots, J_NOHUP, jobs, and js.
Referenced by nohup_all_jobs().
notify_and_cleanup()
void notify_and_cleanup ()
Definition at line 3353 of file jobs.c.
 {
   if (jobs_list_frozen)
     return;
   if (interactive || interactive_shell == 0 || sourcelevel)
     notify_of_job_status ();
   cleanup_dead_jobs ();
 }
References cleanup_dead_jobs(), interactive, interactive_shell, jobs_list_frozen, notify_of_job_status(), and sourcelevel.
Referenced by run_debug_trap(), shell_getc(), and wait_for().
notify_of_job_status()
static void notify_of_job_status () static
Definition at line 4235 of file jobs.c.
 {
   register int job, termsig;
   char *dir;
   sigset_t set, oset;
   WAIT s;
   if (jobs == 0 || js.j_jobslots == 0)
     return;
   if (old_ttou != 0)
     {
       sigemptyset (&set);
       sigaddset (&set, SIGCHLD);
       sigaddset (&set, SIGTTOU);
       sigemptyset (&oset);
       sigprocmask (SIG_BLOCK, &set, &oset);
     }
   else
     queue_sigchld++;
   /* XXX could use js.j_firstj here */
   for (job = 0, dir = (char *)NULL; job < js.j_jobslots; job++)
     {
       if (jobs[job] && IS_NOTIFIED (job) == 0)
     {
       s = raw_job_exit_status (job);
       termsig = WTERMSIG (s);
       /* POSIX.2 says we have to hang onto the statuses of at most the
          last CHILD_MAX background processes if the shell is running a
          script.  If the shell is running a script, either from a file
          or standard input, don't print anything unless the job was
          killed by a signal. */
       if (startup_state == 0 && WIFSIGNALED (s) == 0 &&
         ((DEADJOB (job) && IS_FOREGROUND (job) == 0) || STOPPED (job)))
         continue;
       /* If job control is disabled, don't print the status messages.
          Mark dead jobs as notified so that they get cleaned up.  If
          startup_state == 2 and subshell_environment has the
          SUBSHELL_COMSUB bit turned on, we were started to run a command
          substitution, so don't print anything.
          Otherwise, if the shell is not interactive, POSIX says that `jobs'
          is the only way to notify of job status. */
       if ((job_control == 0 && interactive_shell) ||
           (startup_state == 2 && (subshell_environment & SUBSHELL_COMSUB)) ||
           (startup_state == 2 && posixly_correct && (subshell_environment & SUBSHELL_COMSUB) == 0))
         {
           /* POSIX.2 compatibility:  if the shell is not interactive,
          hang onto the job corresponding to the last asynchronous
          pid until the user has been notified of its status or does
          a `wait'. */
           if (DEADJOB (job) && (interactive_shell || (find_last_pid (job, 0) != last_asynchronous_pid)))
         jobs[job]->flags |= J_NOTIFIED;
           continue;
         }
       /* Print info on jobs that are running in the background,
          and on foreground jobs that were killed by anything
          except SIGINT (and possibly SIGPIPE). */
       switch (JOBSTATE (job))
         {
         case JDEAD:
           if (interactive_shell == 0 && termsig && WIFSIGNALED (s) &&
           termsig != SIGINT &&
 #if defined (DONT_REPORT_SIGTERM)
           termsig != SIGTERM &&
 #endif
 #if defined (DONT_REPORT_SIGPIPE)
           termsig != SIGPIPE &&
 #endif
           signal_is_trapped (termsig) == 0)
         {
           /* Don't print `0' for a line number. */
           fprintf (stderr, _("%s: line %d: "), get_name_for_error (), (line_number == 0) ? 1 : line_number);
           pretty_print_job (job, JLIST_NONINTERACTIVE, stderr);
         }
           else if (IS_FOREGROUND (job))
         {
 #if !defined (DONT_REPORT_SIGPIPE)
           if (termsig && WIFSIGNALED (s) && termsig != SIGINT)
 #else
           if (termsig && WIFSIGNALED (s) && termsig != SIGINT && termsig != SIGPIPE)
 #endif
             {
               fprintf (stderr, "%s", j_strsignal (termsig));
               if (WIFCORED (s))
             fprintf (stderr, _(" (core dumped)"));
               fprintf (stderr, "\n");
             }
         }
           else if (job_control) /* XXX job control test added */
         {
           if (dir == 0)
             dir = current_working_directory ();
           pretty_print_job (job, JLIST_STANDARD, stderr);
           if (dir && strcmp (dir, jobs[job]->wd) != 0)
             fprintf (stderr,
                  _("(wd now: %s)\n"), polite_directory_format (dir));
         }
           jobs[job]->flags |= J_NOTIFIED;
           break;
         case JSTOPPED:
           fprintf (stderr, "\n");
           if (dir == 0)
         dir = current_working_directory ();
           pretty_print_job (job, JLIST_STANDARD, stderr);
           if (dir && (strcmp (dir, jobs[job]->wd) != 0))
         fprintf (stderr,
              _("(wd now: %s)\n"), polite_directory_format (dir));
           jobs[job]->flags |= J_NOTIFIED;
           break;
         case JRUNNING:
         case JMIXED:
           break;
         default:
           programming_error ("notify_of_job_status");
         }
     }
     }
   if (old_ttou != 0)
     sigprocmask (SIG_SETMASK, &oset, (sigset_t *)NULL);
   else
     queue_sigchld--;
 }
References _, current_working_directory(), DEADJOB, dir, DONT_REPORT_SIGPIPE, DONT_REPORT_SIGTERM, find_last_pid(), job::flags, fprintf(), get_name_for_error(), interactive_shell, IS_FOREGROUND, IS_NOTIFIED, jobstats::j_jobslots, J_NOTIFIED, j_strsignal(), JDEAD, JLIST_NONINTERACTIVE, JLIST_STANDARD, JMIXED, job_control, jobs, JOBSTATE, JRUNNING, js, JSTOPPED, last_asynchronous_pid, line_number, NULL, old_ttou, polite_directory_format(), posixly_correct, pretty_print_job(), programming_error(), queue_sigchld, raw_job_exit_status(), s, SIG_BLOCK, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, signal_is_trapped(), SIGPIPE, sigprocmask(), SIGTERM, SIGTTOU, startup_state, stderr, STOPPED, strcmp, SUBSHELL_COMSUB, subshell_environment, WIFCORED, WIFSIGNALED, and WTERMSIG.
Referenced by notify_and_cleanup(), wait_for_any_job(), and waitchld().
PARAMS() [1/14]
static void add_process PARAMS ((char *, pid_t)) static
PARAMS() [2/14]
static sighandler wait_sigint_handler PARAMS ((int)) static
PARAMS() [3/14]
static void pretty_print_job PARAMS ((int, int, FILE *)) static
PARAMS() [4/14]
static int most_recent_job_in_state PARAMS ((int, JOB_STATE)) static
PARAMS() [5/14]
void set_original_signal PARAMS ((int, SigHandler *))
PARAMS() [6/14]
int killpg PARAMS ((pid_t, int))
PARAMS() [7/14]
static PROCESS* find_pipeline PARAMS ((pid_t, int, int *)) static
PARAMS() [8/14]
static int find_job PARAMS ((pid_t, int, PROCESS **)) static
PARAMS() [9/14]
static int maybe_give_terminal_to PARAMS ((pid_t, pid_t, int)) static
PARAMS() [10/14]
static PROCESS* find_pid_in_pipeline PARAMS ((pid_t, PROCESS *, int)) static
PARAMS() [11/14]
static void print_pipeline PARAMS ((PROCESS *, int, int, FILE *)) static
PARAMS() [12/14]
static int map_over_jobs PARAMS ((sh_job_map_func_t *, int, int)) static
PARAMS() [13/14]
static char* current_working_directory PARAMS ((void)) static
PARAMS() [14/14]
static int process_exit_status PARAMS ((WAIT)) static
pretty_print_job()
static void pretty_print_job (int job_index, int format, FILE * stream) static
Definition at line 2034 of file jobs.c.
 {
   register PROCESS *p;
   /* Format only pid information about the process group leader? */
   if (format == JLIST_PID_ONLY)
     {
       fprintf (stream, "%ld\n", (long)jobs[job_index]->pipe->pid);
       return;
     }
   if (format == JLIST_CHANGED_ONLY)
     {
       if (IS_NOTIFIED (job_index))
     return;
       format = JLIST_STANDARD;
     }
   if (format != JLIST_NONINTERACTIVE)
     fprintf (stream, "[%d]%c ", job_index + 1,
           (job_index == js.j_current) ? '+':
         (job_index == js.j_previous) ? '-' : ' ');
   if (format == JLIST_NONINTERACTIVE)
     format = JLIST_LONG;
   p = jobs[job_index]->pipe;
   print_pipeline (p, job_index, format, stream);
   /* We have printed information about this job.  When the job's
      status changes, waitchld () sets the notification flag to 0. */
   jobs[job_index]->flags |= J_NOTIFIED;
 }
References job::flags, format(), fprintf(), IS_NOTIFIED, jobstats::j_current, J_NOTIFIED, jobstats::j_previous, JLIST_CHANGED_ONLY, JLIST_LONG, JLIST_NONINTERACTIVE, JLIST_PID_ONLY, JLIST_STANDARD, jobs, js, p, job::pipe, and print_pipeline().
Referenced by list_one_job(), notify_of_job_status(), and print_job().
print_job()
static int print_job (JOB * job, int format, int state, int job_index) static
Definition at line 2072 of file jobs.c.
 {
   if (state == -1 || (JOB_STATE)state == job->state)
     pretty_print_job (job_index, format, stdout);
   return (0);
 }
References format(), pretty_print_job(), job::state, state, and stdout.
Referenced by list_all_jobs(), list_running_jobs(), and list_stopped_jobs().
print_pipeline()
static void print_pipeline (PROCESS * p, int job_index, int format, FILE * stream) static
Definition at line 1933 of file jobs.c.
 {
   PROCESS *first, *last, *show;
   int es, name_padding;
   char *temp;
   if (p == 0)
     return;
   first = last = p;
   while (last->next != first)
     last = last->next;
   for (;;)
     {
       if (p != first)
     fprintf (stream, format ? "     " : " |");
       if (format != JLIST_STANDARD)
     fprintf (stream, "%5ld", (long)p->pid);
       fprintf (stream, " ");
       if (format > -1 && job_index >= 0)
     {
       show = format ? p : last;
       temp = printable_job_status (job_index, show, format);
       if (p != first)
         {
           if (format)
         {
           if (show->running == first->running &&
               WSTATUS (show->status) == WSTATUS (first->status))
             temp = "";
         }
           else
         temp = (char *)NULL;
         }
       if (temp)
         {
           fprintf (stream, "%s", temp);
           es = STRLEN (temp);
           if (es == 0)
         es = 2; /* strlen ("| ") */
           name_padding = LONGEST_SIGNAL_DESC - es;
           fprintf (stream, "%*s", name_padding, "");
           if ((WIFSTOPPED (show->status) == 0) &&
           (WIFCONTINUED (show->status) == 0) &&
           WIFCORED (show->status))
         fprintf (stream, _("(core dumped) "));
         }
     }
       if (p != first && format)
     fprintf (stream, "| ");
       if (p->command)
     fprintf (stream, "%s", p->command);
       if (p == last && job_index >= 0)
     {
       temp = current_working_directory ();
       if (RUNNING (job_index) && (IS_FOREGROUND (job_index) == 0))
         fprintf (stream, " &");
       if (strcmp (temp, jobs[job_index]->wd) != 0)
         fprintf (stream,
           _("  (wd: %s)"), polite_directory_format (jobs[job_index]->wd));
     }
       if (format || (p == last))
     {
       /* We need to add a CR only if this is an interactive shell, and
          we're reporting the status of a completed job asynchronously.
          We can't really check whether this particular job is being
          reported asynchronously, so just add the CR if the shell is
          currently interactive and asynchronous notification is enabled. */
       if (asynchronous_notification && interactive)
         putc ('\r', stream);
       fprintf (stream, "\n");
     }
       if (p == last)
     break;
       p = p->next;
     }
   fflush (stream);
 }
References _, asynchronous_notification, current_working_directory(), fflush(), first, format(), fprintf(), interactive, IS_FOREGROUND, JLIST_STANDARD, jobs, last, LONGEST_SIGNAL_DESC, NULL, p, polite_directory_format(), printable_job_status(), putc, process::running, RUNNING, process::status, strcmp, STRLEN, WIFCONTINUED, WIFCORED, WIFSTOPPED, and WSTATUS.
Referenced by pretty_print_job().
printable_job_status()
static char* printable_job_status (int j, PROCESS * p, int format) static
Definition at line 1860 of file jobs.c.
 {
   static char *temp;
   int es;
   temp = _("Done");
   if (STOPPED (j) && format == 0)
     {
       if (posixly_correct == 0 || p == 0 || (WIFSTOPPED (p->status) == 0))
     temp = _("Stopped");
       else
     {
       temp = retcode_name_buffer;
       snprintf (temp, sizeof(retcode_name_buffer), _("Stopped(%s)"), signal_name (WSTOPSIG (p->status)));
     }
     }
   else if (RUNNING (j))
     temp = _("Running");
   else
     {
       if (WIFSTOPPED (p->status))
     temp = j_strsignal (WSTOPSIG (p->status));
       else if (WIFSIGNALED (p->status))
     temp = j_strsignal (WTERMSIG (p->status));
       else if (WIFEXITED (p->status))
     {
       temp = retcode_name_buffer;
       es = WEXITSTATUS (p->status);
       if (es == 0)
         {
           strncpy (temp, _("Done"), sizeof (retcode_name_buffer) - 1);
           temp[sizeof (retcode_name_buffer) - 1] = '\0';
         }
       else if (posixly_correct)
         snprintf (temp, sizeof(retcode_name_buffer), _("Done(%d)"), es);
       else
         snprintf (temp, sizeof(retcode_name_buffer), _("Exit %d"), es);
     }
       else
     temp = _("Unknown status");
     }
   return temp;
 }
References _, format(), j, j_strsignal(), p, posixly_correct, retcode_name_buffer, RUNNING, signal_name(), snprintf(), STOPPED, strncpy(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, WIFSTOPPED, WSTOPSIG, and WTERMSIG.
Referenced by print_pipeline().
process_exit_signal()
static int process_exit_signal (WAIT status) static
Definition at line 2794 of file jobs.c.
 {
   return (WIFSIGNALED (status) ? WTERMSIG (status) : 0);
 }
References status, WIFSIGNALED, and WTERMSIG.
Referenced by job_exit_signal(), and wait_for().
process_exit_status()
static int process_exit_status (WAIT status) static
Definition at line 2801 of file jobs.c.
 {
   if (WIFSIGNALED (status))
     return (128 + WTERMSIG (status));
   else if (WIFSTOPPED (status) == 0)
     return (WEXITSTATUS (status));
   else
     return (EXECUTION_SUCCESS);
 }
References EXECUTION_SUCCESS, status, WEXITSTATUS, WIFSIGNALED, WIFSTOPPED, and WTERMSIG.
Referenced by delete_job(), job_exit_status(), set_job_status_and_cleanup(), setjstatus(), and wait_for().
processes_in_job()
static int processes_in_job (int job) static
Definition at line 1246 of file jobs.c.
 {
   int nproc;
   register PROCESS *p;
   nproc = 0;
   p = jobs[job]->pipe;
   do
     {
       p = p->next;
       nproc++;
     }
   while (p != jobs[job]->pipe);
   return nproc;
 }
References jobs, p, and job::pipe.
Referenced by mark_dead_jobs_as_notified(), and realloc_jobs_list().
pshash_delindex()
static void pshash_delindex (ps_index_t psi) static
Definition at line 866 of file jobs.c.
 {
   struct pidstat *ps;
   ps_index_t *bucket;
   ps = &bgpids.storage[psi];
   if (ps->pid == NO_PID)
     return;
   if (ps->bucket_next != NO_PIDSTAT)
     bgpids.storage[ps->bucket_next].bucket_prev = ps->bucket_prev;
   if (ps->bucket_prev != NO_PIDSTAT)
     bgpids.storage[ps->bucket_prev].bucket_next = ps->bucket_next;
   else
     {
       bucket = pshash_getbucket (ps->pid);
       *bucket = ps->bucket_next;    /* deleting chain head in hash table */
     }
   /* clear out this cell, in case it gets reused. */
   ps->pid = NO_PID;
   ps->bucket_next = ps->bucket_prev = NO_PIDSTAT;
 }
References pidstat::bucket_next, pidstat::bucket_prev, NO_PID, NO_PIDSTAT, pidstat::pid, pshash_getbucket(), and bgpids::storage.
Referenced by bgp_delete(), and bgp_getindex().
pshash_getbucket()
static ps_index_t* pshash_getbucket (pid_t pid) static
Definition at line 812 of file jobs.c.
 {
   unsigned long hash;       /* XXX - u_bits32_t */
   hash = pid * 0x9e370001UL;
   return (&pidstat_table[hash % PIDSTAT_TABLE_SZ]);
 }
References pid, pidstat_table, and PIDSTAT_TABLE_SZ.
Referenced by bgp_add(), bgp_delete(), bgp_search(), and pshash_delindex().
raw_job_exit_status()
static WAIT raw_job_exit_status (int job) static
Definition at line 2835 of file jobs.c.
 {
   register PROCESS *p;
   int fail;
   WAIT ret;
   if (jobs[job]->flags & J_PIPEFAIL)
     {
       fail = 0;
       p = jobs[job]->pipe;
       do
     {
       if (WSTATUS (p->status) != EXECUTION_SUCCESS)
         fail = WSTATUS(p->status);
       p = p->next;
     }
       while (p != jobs[job]->pipe);
       WSTATUS (ret) = fail;
       return ret;
     }
   for (p = jobs[job]->pipe; p->next != jobs[job]->pipe; p = p->next)
     ;
   return (p->status);
 }
References EXECUTION_SUCCESS, flags, J_PIPEFAIL, jobs, p, job::pipe, and WSTATUS.
Referenced by job_exit_signal(), job_exit_status(), and notify_of_job_status().
realloc_jobs_list()
static void realloc_jobs_list () static
Definition at line 1290 of file jobs.c.
 {
   sigset_t set, oset;
   int nsize, i, j, ncur, nprev;
   JOB **nlist;
   ncur = nprev = NO_JOB;
   nsize = ((js.j_njobs + JOB_SLOTS - 1) / JOB_SLOTS);
   nsize *= JOB_SLOTS;
   i = js.j_njobs % JOB_SLOTS;
   if (i == 0 || i > (JOB_SLOTS >> 1))
     nsize += JOB_SLOTS;
   BLOCK_CHILD (set, oset);
   nlist = (js.j_jobslots == nsize) ? jobs : (JOB **) xmalloc (nsize * sizeof (JOB *));
   js.c_reaped = js.j_ndead = 0;
   for (i = j = 0; i < js.j_jobslots; i++)
     if (jobs[i])
       {
     if (i == js.j_current)
       ncur = j;
     if (i == js.j_previous)
       nprev = j;
     nlist[j++] = jobs[i];
     if (jobs[i]->state == JDEAD)
       {
         js.j_ndead++;
         js.c_reaped += processes_in_job (i);
       }
       }
 #if 0
   itrace ("realloc_jobs_list: resize jobs list from %d to %d", js.j_jobslots, nsize);
   itrace ("realloc_jobs_list: j_lastj changed from %d to %d", js.j_lastj, (j > 0) ? j - 1 : 0);
   itrace ("realloc_jobs_list: j_njobs changed from %d to %d", js.j_njobs, j);
   itrace ("realloc_jobs_list: js.j_ndead %d js.c_reaped %d", js.j_ndead, js.c_reaped);
 #endif
   js.j_firstj = 0;
   js.j_lastj = (j > 0) ? j - 1 : 0;
   js.j_njobs = j;
   js.j_jobslots = nsize;
   /* Zero out remaining slots in new jobs list */
   for ( ; j < nsize; j++)
     nlist[j] = (JOB *)NULL;
   if (jobs != nlist)
     {
       free (jobs);
       jobs = nlist;
     }
   if (ncur != NO_JOB)
     js.j_current = ncur;
   if (nprev != NO_JOB)
     js.j_previous = nprev;
   /* Need to reset these */
   if (js.j_current == NO_JOB || js.j_previous == NO_JOB || js.j_current > js.j_lastj || js.j_previous > js.j_lastj)
     reset_current ();
 #if 0
   itrace ("realloc_jobs_list: reset js.j_current (%d) and js.j_previous (%d)", js.j_current, js.j_previous);
 #endif
   UNBLOCK_CHILD (oset);
 }
References BLOCK_CHILD, jobstats::c_reaped, free, i, j, jobstats::j_current, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobstats::j_ndead, jobstats::j_njobs, jobstats::j_previous, JDEAD, JOB_SLOTS, jobs, js, NO_JOB, NULL, processes_in_job(), reset_current(), state, UNBLOCK_CHILD, and xmalloc.
Referenced by compact_jobs_list().
reap_dead_jobs()
void reap_dead_jobs ()
Definition at line 3367 of file jobs.c.
 {
   mark_dead_jobs_as_notified (0);
   cleanup_dead_jobs ();
 }
References cleanup_dead_jobs(), and mark_dead_jobs_as_notified().
Referenced by compact_jobs_list().
reset_current()
static void reset_current () static
Definition at line 3482 of file jobs.c.
 {
   int candidate;
   if (js.j_jobslots && js.j_current != NO_JOB && jobs[js.j_current] && STOPPED (js.j_current))
     candidate = js.j_current;
   else
     {
       candidate = NO_JOB;
       /* First choice: the previous job. */
       if (js.j_previous != NO_JOB && jobs[js.j_previous] && STOPPED (js.j_previous))
     candidate = js.j_previous;
       /* Second choice: the most recently stopped job. */
       if (candidate == NO_JOB)
     candidate = job_last_stopped (js.j_jobslots);
       /* Third choice: the newest running job. */
       if (candidate == NO_JOB)
     candidate = job_last_running (js.j_jobslots);
     }
   /* If we found a job to use, then use it.  Otherwise, there
      are no jobs period. */
   if (candidate != NO_JOB)
     set_current_job (candidate);
   else
     js.j_current = js.j_previous = NO_JOB;
 }
References jobstats::j_current, jobstats::j_jobslots, jobstats::j_previous, job_last_running(), job_last_stopped(), jobs, js, NO_JOB, set_current_job(), and STOPPED.
Referenced by delete_job(), realloc_jobs_list(), start_job(), stop_pipeline(), and waitchld().
reset_job_indices()
static void reset_job_indices () static
Definition at line 1170 of file jobs.c.
 {
   int old;
   if (jobs[js.j_firstj] == 0)
     {
       old = js.j_firstj++;
       if (old >= js.j_jobslots)
     old = js.j_jobslots - 1;
       while (js.j_firstj != old)
     {
       if (js.j_firstj >= js.j_jobslots)
         js.j_firstj = 0;
       if (jobs[js.j_firstj] || js.j_firstj == old)  /* needed if old == 0 */
         break;
       js.j_firstj++;
     }
       if (js.j_firstj == old)
     js.j_firstj = js.j_lastj = js.j_njobs = 0;
     }
   if (jobs[js.j_lastj] == 0)
     {
       old = js.j_lastj--;
       if (old < 0)
     old = 0;
       while (js.j_lastj != old)
     {
       if (js.j_lastj < 0)
         js.j_lastj = js.j_jobslots - 1;
       if (jobs[js.j_lastj] || js.j_lastj == old)    /* needed if old == js.j_jobslots */
         break;
       js.j_lastj--;
     }
       if (js.j_lastj == old)
     js.j_firstj = js.j_lastj = js.j_njobs = 0;
     }
 }
References jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobstats::j_njobs, jobs, js, and old.
Referenced by delete_job().
restart_job_control()
void restart_job_control ()
Definition at line 5027 of file jobs.c.
 {
   if (shell_tty != -1)
     close (shell_tty);
   initialize_job_control (0);
 }
References close(), initialize_job_control(), and shell_tty.
restore_pipeline()
PROCESS* restore_pipeline (int discard)
Definition at line 497 of file jobs.c.
 {
   PROCESS *old_pipeline;
   sigset_t set, oset;
   struct pipeline_saver *saver;
   BLOCK_CHILD (set, oset);
   old_pipeline = the_pipeline;
   the_pipeline = saved_pipeline->pipeline;
   saver = saved_pipeline;
   saved_pipeline = saved_pipeline->next;
   free (saver);
   already_making_children = saved_already_making_children;
   UNBLOCK_CHILD (oset);
   if (discard && old_pipeline)
     {
       discard_pipeline (old_pipeline);
       return ((PROCESS *)NULL);
     }
   return old_pipeline;
 }
References already_making_children, BLOCK_CHILD, discard_pipeline(), free, pipeline_saver::next, NULL, pipeline_saver::pipeline, saved_already_making_children, saved_pipeline, the_pipeline, and UNBLOCK_CHILD.
Referenced by _run_trap_internal(), run_debug_trap(), and run_pending_traps().
restore_sigint_handler()
static void restore_sigint_handler () static
Definition at line 2736 of file jobs.c.
 {
   if (old_sigint_handler != INVALID_SIGNAL_HANDLER)
     {
       set_signal_handler (SIGINT, old_sigint_handler);
       old_sigint_handler = INVALID_SIGNAL_HANDLER;
       waiting_for_child = 0;
     }
 }
References INVALID_SIGNAL_HANDLER, old_sigint_handler, set_signal_handler, SIGINT, and waiting_for_child.
Referenced by set_job_status_and_cleanup(), wait_for(), wait_sigint_cleanup(), and wait_sigint_handler().
run_sigchld_trap()
void run_sigchld_trap (int nchild)
Definition at line 4185 of file jobs.c.
 {
   char *trap_command;
   int i;
   /* Turn off the trap list during the call to parse_and_execute ()
      to avoid potentially infinite recursive calls.  Preserve the
      values of last_command_exit_value, last_made_pid, and the_pipeline
      around the execution of the trap commands. */
   trap_command = savestring (trap_list[SIGCHLD]);
   begin_unwind_frame ("SIGCHLD trap");
   unwind_protect_int (last_command_exit_value);
   unwind_protect_int (last_command_exit_signal);
   unwind_protect_var (last_made_pid);
   unwind_protect_int (jobs_list_frozen);
   unwind_protect_pointer (the_pipeline);
   unwind_protect_pointer (subst_assign_varlist);
   unwind_protect_pointer (this_shell_builtin);
   unwind_protect_pointer (temporary_env);
   /* We have to add the commands this way because they will be run
      in reverse order of adding.  We don't want maybe_set_sigchld_trap ()
      to reference freed memory. */
   add_unwind_protect (xfree, trap_command);
   add_unwind_protect (maybe_set_sigchld_trap, trap_command);
   subst_assign_varlist = (WORD_LIST *)NULL;
   the_pipeline = (PROCESS *)NULL;
   temporary_env = 0;    /* traps should not run with temporary env */
   running_trap = SIGCHLD + 1;
   set_impossible_sigchld_trap ();
   jobs_list_frozen = 1;
   for (i = 0; i < nchild; i++)
     {
       parse_and_execute (savestring (trap_command), "trap", SEVAL_NOHIST|SEVAL_RESETLINE|SEVAL_NOOPTIMIZE);
     }
   run_unwind_frame ("SIGCHLD trap");
   running_trap = 0;
 }
References add_unwind_protect(), begin_unwind_frame(), i, jobs_list_frozen, last_command_exit_signal, last_command_exit_value, last_made_pid, NULL, parse_and_execute(), run_unwind_frame(), running_trap, savestring(), SEVAL_NOHIST, SEVAL_NOOPTIMIZE, SEVAL_RESETLINE, SIGCHLD, subst_assign_varlist, temporary_env, the_pipeline, this_shell_builtin, trap_list, unwind_protect_int, unwind_protect_pointer, unwind_protect_var, and xfree.
Referenced by run_pending_traps(), and waitchld().
save_pipeline()
void save_pipeline (int clear)
Definition at line 479 of file jobs.c.
 {
   sigset_t set, oset;
   struct pipeline_saver *saver;
   BLOCK_CHILD (set, oset);
   saver = alloc_pipeline_saver ();
   saver->pipeline = the_pipeline;
   saver->next = saved_pipeline;
   saved_pipeline = saver;
   if (clear)
     the_pipeline = (PROCESS *)NULL;
   saved_already_making_children = already_making_children;
   UNBLOCK_CHILD (oset);
 }
References alloc_pipeline_saver(), already_making_children, BLOCK_CHILD, pipeline_saver::next, NULL, pipeline_saver::pipeline, saved_already_making_children, saved_pipeline, the_pipeline, and UNBLOCK_CHILD.
Referenced by _run_trap_internal(), run_debug_trap(), and run_pending_traps().
save_proc_status()
void save_proc_status (pid_t pid, int status)
Definition at line 979 of file jobs.c.
 {
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
   bgp_add (pid, status);
   UNBLOCK_CHILD (oset);
 }
References bgp_add(), BLOCK_CHILD, pid, status, and UNBLOCK_CHILD.
set_current_job()
static void set_current_job (int job) static
Definition at line 3421 of file jobs.c.
 {
   int candidate;
   if (js.j_current != job)
     {
       js.j_previous = js.j_current;
       js.j_current = job;
     }
   /* First choice for previous job is the old current job. */
   if (js.j_previous != js.j_current &&
       js.j_previous != NO_JOB &&
       jobs[js.j_previous] &&
       STOPPED (js.j_previous))
     return;
   /* Second choice:  Newest stopped job that is older than
      the current job. */
   candidate = NO_JOB;
   if (STOPPED (js.j_current))
     {
       candidate = job_last_stopped (js.j_current);
       if (candidate != NO_JOB)
     {
       js.j_previous = candidate;
       return;
     }
     }
   /* If we get here, there is either only one stopped job, in which case it is
      the current job and the previous job should be set to the newest running
      job, or there are only running jobs and the previous job should be set to
      the newest running job older than the current job.  We decide on which
      alternative to use based on whether or not JOBSTATE(js.j_current) is
      JSTOPPED. */
   candidate = RUNNING (js.j_current) ? job_last_running (js.j_current)
                     : job_last_running (js.j_jobslots);
   if (candidate != NO_JOB)
     {
       js.j_previous = candidate;
       return;
     }
   /* There is only a single job, and it is both `+' and `-'. */
   js.j_previous = js.j_current;
 }
References jobstats::j_current, jobstats::j_jobslots, jobstats::j_previous, job_last_running(), job_last_stopped(), jobs, js, NO_JOB, RUNNING, and STOPPED.
Referenced by reset_current(), start_job(), and waitchld().
set_job_control()
int set_job_control (int arg)
Definition at line 4958 of file jobs.c.
 {
   int old;
   old = job_control;
   job_control = arg;
   if (terminal_pgrp == NO_PID && shell_tty >= 0)
     terminal_pgrp = tcgetpgrp (shell_tty);
   /* If we're turning on job control we're going to want to know the shell's
      process group. */
   if (job_control != old && job_control)
     shell_pgrp = getpgid (0);
   running_in_background = (terminal_pgrp != shell_pgrp);
 #if 0
   if (interactive_shell == 0 && running_in_background == 0 && job_control != old)
     {
       if (job_control)
     initialize_job_signals ();
       else
     default_tty_job_signals ();
     }
 #endif
   /* If we're turning on job control, reset pipeline_pgrp so make_child will
      put new child processes into the right pgrp */
   if (job_control != old && job_control)
     pipeline_pgrp = 0;
   return (old);
 }
References default_tty_job_signals(), getpgid, initialize_job_signals(), interactive_shell, job_control, NO_PID, old, pipeline_pgrp, running_in_background, shell_pgrp, shell_tty, tcgetpgrp(), and terminal_pgrp.
Referenced by change_flag(), init_noninteractive(), main(), run_startup_files(), and without_job_control().
set_job_running()
static void set_job_running (int job) static
Definition at line 3516 of file jobs.c.
 {
   register PROCESS *p;
   /* Each member of the pipeline is now running. */
   p = jobs[job]->pipe;
   do
     {
       if (WIFSTOPPED (p->status))
     p->running = PS_RUNNING;    /* XXX - could be PS_STOPPED */
       p = p->next;
     }
   while (p != jobs[job]->pipe);
   /* This means that the job is running. */
   JOBSTATE (job) = JRUNNING;
 }
References jobs, JOBSTATE, JRUNNING, p, job::pipe, PS_RUNNING, and WIFSTOPPED.
Referenced by kill_pid(), and start_job().
set_job_status_and_cleanup()
static int set_job_status_and_cleanup (int job) static
Definition at line 3980 of file jobs.c.
 {
   PROCESS *child;
   int tstatus, job_state, any_stopped, any_tstped, call_set_current;
   SigHandler *temp_handler;
   child = jobs[job]->pipe;
   jobs[job]->flags &= ~J_NOTIFIED;
   call_set_current = 0;
   /*
    * COMPUTE JOB STATUS
    */
   /* If all children are not running, but any of them is  stopped, then
      the job is stopped, not dead. */
   job_state = any_stopped = any_tstped = 0;
   do
     {
       job_state |= PRUNNING (child);
 #if 0
       if (PEXITED (child) && (WIFSTOPPED (child->status)))
 #else
       /* Only checking for WIFSTOPPED now, not for PS_DONE */
       if (PSTOPPED (child))
 #endif
     {
       any_stopped = 1;
       any_tstped |= job_control && (WSTOPSIG (child->status) == SIGTSTP);
     }
       child = child->next;
     }
   while (child != jobs[job]->pipe);
   /* If job_state != 0, the job is still running, so don't bother with
      setting the process exit status and job state unless we're
      transitioning from stopped to running. */
   if (job_state != 0 && JOBSTATE(job) != JSTOPPED)
     return 0;
   /*
    * SET JOB STATUS
    */
   /* The job is either stopped or dead.  Set the state of the job accordingly. */
   if (any_stopped)
     {
       jobs[job]->state = JSTOPPED;
       jobs[job]->flags &= ~J_FOREGROUND;
       call_set_current++;
       /* Suspending a job with SIGTSTP breaks all active loops. */
       if (any_tstped && loop_level)
     breaking = loop_level;
     }
   else if (job_state != 0)  /* was stopped, now running */
     {
       jobs[job]->state = JRUNNING;
       call_set_current++;
     }
   else
     {
       jobs[job]->state = JDEAD;
       js.j_ndead++;
 #if 0
       if (IS_FOREGROUND (job))
     setjstatus (job);
 #endif
       /* If this job has a cleanup function associated with it, call it
      with `cleanarg' as the single argument, then set the function
      pointer to NULL so it is not inadvertently called twice.  The
      cleanup function is responsible for deallocating cleanarg. */
       if (jobs[job]->j_cleanup)
     {
       (*jobs[job]->j_cleanup) (jobs[job]->cleanarg);
       jobs[job]->j_cleanup = (sh_vptrfunc_t *)NULL;
     }
     }
   /*
    * CLEANUP
    *
    * Currently, we just do special things if we got a SIGINT while waiting
    * for a foreground job to complete
    */
   if (JOBSTATE (job) == JDEAD)
     {
       /* If we're running a shell script and we get a SIGINT with a
      SIGINT trap handler, but the foreground job handles it and
      does not exit due to SIGINT, run the trap handler but do not
      otherwise act as if we got the interrupt. */
       if (wait_sigint_received && interactive_shell == 0 &&
       child_caught_sigint && IS_FOREGROUND (job) &&
       signal_is_trapped (SIGINT))
     {
       int old_frozen;
       wait_sigint_received = 0;
       last_command_exit_value = process_exit_status (child->status);
       old_frozen = jobs_list_frozen;
       jobs_list_frozen = 1;
       tstatus = maybe_call_trap_handler (SIGINT);
       jobs_list_frozen = old_frozen;
     }
       /* If the foreground job is killed by SIGINT when job control is not
      active, we need to perform some special handling.
      The check of wait_sigint_received is a way to determine if the
      SIGINT came from the keyboard (in which case the shell has already
      seen it, and wait_sigint_received is non-zero, because keyboard
      signals are sent to process groups) or via kill(2) to the foreground
      process by another process (or itself).  If the shell did receive the
      SIGINT, it needs to perform normal SIGINT processing.  XXX - should
      this change its behavior depending on whether the last command in an
      pipeline exited due to SIGINT, or any process in the pipeline?  Right
      now it does this if any process in the pipeline exits due to SIGINT. */
       else if (wait_sigint_received &&
           child_caught_sigint == 0 &&
           IS_FOREGROUND (job) && IS_JOBCONTROL (job) == 0)
     {
       int old_frozen;
       wait_sigint_received = 0;
       /* If SIGINT is trapped, set the exit status so that the trap
          handler can see it. */
       if (signal_is_trapped (SIGINT))
         last_command_exit_value = process_exit_status (child->status);
       /* If the signal is trapped, let the trap handler get it no matter
          what and simply return if the trap handler returns.
          maybe_call_trap_handler() may cause dead jobs to be removed from
          the job table because of a call to execute_command.  We work
          around this by setting JOBS_LIST_FROZEN. */
       old_frozen = jobs_list_frozen;
       jobs_list_frozen = 1;
       tstatus = maybe_call_trap_handler (SIGINT);
       jobs_list_frozen = old_frozen;
       if (tstatus == 0 && old_sigint_handler != INVALID_SIGNAL_HANDLER)
         {
           /* wait_sigint_handler () has already seen SIGINT and
          allowed the wait builtin to jump out.  We need to
          call the original SIGINT handler, if necessary.  If
          the original handler is SIG_DFL, we need to resend
          the signal to ourselves. */
           temp_handler = old_sigint_handler;
           /* Bogus.  If we've reset the signal handler as the result
          of a trap caught on SIGINT, then old_sigint_handler
          will point to trap_handler, which now knows nothing about
          SIGINT (if we reset the sighandler to the default).
          In this case, we have to fix things up.  What a crock. */
           if (temp_handler == trap_handler && signal_is_trapped (SIGINT) == 0)
           temp_handler = trap_to_sighandler (SIGINT);
           restore_sigint_handler ();
           if (temp_handler == SIG_DFL)
         termsig_handler (SIGINT);   /* XXX */
           else if (temp_handler != SIG_IGN)
         (*temp_handler) (SIGINT);
         }
     }
     }
   return call_set_current;
 }
References breaking, child(), child_caught_sigint, job::flags, interactive_shell, INVALID_SIGNAL_HANDLER, IS_FOREGROUND, IS_JOBCONTROL, J_FOREGROUND, jobstats::j_ndead, J_NOTIFIED, JDEAD, job_control, jobs, jobs_list_frozen, JOBSTATE, JRUNNING, js, JSTOPPED, last_command_exit_value, loop_level, maybe_call_trap_handler(), child::next, NULL, old_sigint_handler, PEXITED, job::pipe, process_exit_status(), PRUNNING, PSTOPPED, restore_sigint_handler(), setjstatus(), SIG_DFL, SIG_IGN, SIGINT, signal_is_trapped(), SIGTSTP, job::state, termsig_handler(), trap_handler(), trap_to_sighandler(), wait_sigint_received, WIFSTOPPED, and WSTOPSIG.
Referenced by waitchld().
set_jobs_list_frozen()
void set_jobs_list_frozen (int s)
Definition at line 4949 of file jobs.c.
 {
   jobs_list_frozen = s;
 }
References jobs_list_frozen, and s.
Referenced by execute_pipeline(), and lastpipe_cleanup().
set_maxchild()
void set_maxchild (int nchild)
Definition at line 5038 of file jobs.c.
 {
   static int lmaxchild = -1;
   /* Initialize once. */
   if (lmaxchild < 0)
     {
       errno = 0;
       lmaxchild = getmaxchild ();
       if (lmaxchild < 0 && errno == 0)
         lmaxchild = MAX_CHILD_MAX;      /* assume unlimited */
     }
   if (lmaxchild < 0)
     lmaxchild = DEFAULT_CHILD_MAX;
   /* Clamp value we set.  Minimum is what Posix requires, maximum is defined
      above as MAX_CHILD_MAX. */
   if (nchild < lmaxchild)
     nchild = lmaxchild;
   else if (nchild > MAX_CHILD_MAX)
     nchild = MAX_CHILD_MAX;
   js.c_childmax = nchild;
 }
References jobstats::c_childmax, DEFAULT_CHILD_MAX, errno, getmaxchild(), js, and MAX_CHILD_MAX.
Referenced by initialize_job_control(), and mark_dead_jobs_as_notified().
set_new_line_discipline()
static int set_new_line_discipline (int tty) static
Definition at line 4534 of file jobs.c.
 {
 #if defined (NEW_TTY_DRIVER)
   int ldisc;
   if (ioctl (tty, TIOCGETD, &ldisc) < 0)
     return (-1);
   if (ldisc != NTTYDISC)
     {
       ldisc = NTTYDISC;
       if (ioctl (tty, TIOCSETD, &ldisc) < 0)
     return (-1);
     }
   return (0);
 #endif /* NEW_TTY_DRIVER */
 #if defined (TERMIO_TTY_DRIVER)
 #  if defined (TERMIO_LDISC) && (NTTYDISC)
   if (ioctl (tty, TCGETA, &shell_tty_info) < 0)
     return (-1);
   if (shell_tty_info.c_line != NTTYDISC)
     {
       shell_tty_info.c_line = NTTYDISC;
       if (ioctl (tty, TCSETAW, &shell_tty_info) < 0)
     return (-1);
     }
 #  endif /* TERMIO_LDISC && NTTYDISC */
   return (0);
 #endif /* TERMIO_TTY_DRIVER */
 #if defined (TERMIOS_TTY_DRIVER)
 #  if defined (TERMIOS_LDISC) && defined (NTTYDISC)
   if (tcgetattr (tty, &shell_tty_info) < 0)
     return (-1);
   if (shell_tty_info.c_line != NTTYDISC)
     {
       shell_tty_info.c_line = NTTYDISC;
       if (tcsetattr (tty, TCSADRAIN, &shell_tty_info) < 0)
     return (-1);
     }
 #  endif /* TERMIOS_LDISC && NTTYDISC */
   return (0);
 #endif /* TERMIOS_TTY_DRIVER */
 #if !defined (NEW_TTY_DRIVER) && !defined (TERMIO_TTY_DRIVER) && !defined (TERMIOS_TTY_DRIVER)
   return (-1);
 #endif
 }
References ioctl(), shell_tty_info, TCGETA, tcgetattr(), TCSADRAIN, tcsetattr(), TCSETAW, TIOCGETD, and TIOCSETD.
Referenced by initialize_job_control().
set_sigchld_handler()
void set_sigchld_handler ()
Definition at line 5066 of file jobs.c.
 {
   set_signal_handler (SIGCHLD, sigchld_handler);
 }
References set_signal_handler, SIGCHLD, and sigchld_handler().
Referenced by command_substitute(), execute_disk_command(), execute_in_subshell(), execute_subshell_builtin_or_function(), and initialize_subshell().
set_tty_state()
int set_tty_state ()
Definition at line 2508 of file jobs.c.
 {
   int tty;
   tty = input_tty ();
   if (tty != -1)
     {
 #if defined (NEW_TTY_DRIVER)
 #  if defined (DRAIN_OUTPUT)
       draino (tty, shell_tty_info.sg_ospeed);
 #  endif /* DRAIN_OUTPUT */
       ioctl (tty, TIOCSETN, &shell_tty_info);
       ioctl (tty, TIOCSETC, &shell_tchars);
       ioctl (tty, TIOCSLTC, &shell_ltchars);
 #endif /* NEW_TTY_DRIVER */
 #if defined (TERMIO_TTY_DRIVER)
       ioctl (tty, TCSETAW, &shell_tty_info);
 #endif /* TERMIO_TTY_DRIVER */
 #if defined (TERMIOS_TTY_DRIVER)
       if (tcsetattr (tty, TCSADRAIN, &shell_tty_info) < 0)
     {
       /* Only print an error message if we're really interactive at
          this time. */
       if (interactive)
         sys_error ("[%ld: %d (%d)] tcsetattr", (long)getpid (), shell_level, tty);
       return -1;
     }
 #endif /* TERMIOS_TTY_DRIVER */
     }
   return 0;
 }
References getpid(), input_tty, interactive, ioctl(), shell_level, shell_tty_info, sys_error(), TCSADRAIN, tcsetattr(), TCSETAW, TIOCSETC, TIOCSETN, and TIOCSLTC.
Referenced by start_job(), and wait_for().
setjstatus()
static void setjstatus (int j) static
Definition at line 4155 of file jobs.c.
 {
 #if defined (ARRAY_VARS)
   register int i;
   register PROCESS *p;
   for (i = 1, p = jobs[j]->pipe; p->next != jobs[j]->pipe; p = p->next, i++)
     ;
   i++;
   if (statsize < i)
     {
       pstatuses = (int *)xrealloc (pstatuses, i * sizeof (int));
       statsize = i;
     }
   i = 0;
   p = jobs[j]->pipe;
   do
     {
       pstatuses[i++] = process_exit_status (p->status);
       p = p->next;
     }
   while (p != jobs[j]->pipe);
   pstatuses[i] = -1;    /* sentinel */
   set_pipestatus_array (pstatuses, i);
 #endif
 }
References i, j, jobs, p, job::pipe, process_exit_status(), and xrealloc.
Referenced by set_job_status_and_cleanup(), stop_pipeline(), and wait_for().
sigchld_handler()
static sighandler sigchld_handler (int sig) static
Definition at line 3741 of file jobs.c.
 {
   int n, oerrno;
   oerrno = errno;
   REINSTALL_SIGCHLD_HANDLER;
   sigchld++;
   n = 0;
   if (queue_sigchld == 0)
     n = waitchld (-1, 0);
   errno = oerrno;
   SIGRETURN (n);
 }
References errno, n, queue_sigchld, REINSTALL_SIGCHLD_HANDLER, sigchld, SIGRETURN, and waitchld().
Referenced by initialize_job_control(), and set_sigchld_handler().
sigcont_sighandler()
static sighandler sigcont_sighandler (int sig) static
Definition at line 4611 of file jobs.c.
 {
   initialize_job_signals ();
   set_signal_handler (SIGCONT, old_cont);
   kill (getpid (), SIGCONT);
   SIGRETURN (0);
 }
References getpid(), initialize_job_signals(), kill(), old_cont, set_signal_handler, SIGCONT, and SIGRETURN.
Referenced by sigstop_sighandler().
sigstop_sighandler()
static sighandler sigstop_sighandler (int sig) static
Definition at line 4623 of file jobs.c.
 {
   set_signal_handler (SIGTSTP, old_tstp);
   set_signal_handler (SIGTTOU, old_ttou);
   set_signal_handler (SIGTTIN, old_ttin);
   old_cont = set_signal_handler (SIGCONT, sigcont_sighandler);
   give_terminal_to (shell_pgrp, 0);
   kill (getpid (), sig);
   SIGRETURN (0);
 }
References getpid(), give_terminal_to(), kill(), old_cont, old_tstp, old_ttin, old_ttou, set_signal_handler, shell_pgrp, SIGCONT, sigcont_sighandler(), SIGRETURN, SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by initialize_job_signals().
start_job()
int start_job (int job, int foreground)
Definition at line 3541 of file jobs.c.
 {
   register PROCESS *p;
   int already_running;
   sigset_t set, oset;
   char *wd, *s;
   static TTYSTRUCT save_stty;
   BLOCK_CHILD (set, oset);
   if ((subshell_environment & SUBSHELL_COMSUB) && (pipeline_pgrp == shell_pgrp))
     {
       internal_error (_("%s: no current jobs"), this_command_name);
       UNBLOCK_CHILD (oset);
       return (-1);
     }
   if (DEADJOB (job))
     {
       internal_error (_("%s: job has terminated"), this_command_name);
       UNBLOCK_CHILD (oset);
       return (-1);
     }
   already_running = RUNNING (job);
   if (foreground == 0 && already_running)
     {
       internal_error (_("%s: job %d already in background"), this_command_name, job + 1);
       UNBLOCK_CHILD (oset);
       return (0);       /* XPG6/SUSv3 says this is not an error */
     }
   wd = current_working_directory ();
   /* You don't know about the state of this job.  Do you? */
   jobs[job]->flags &= ~J_NOTIFIED;
   if (foreground)
     {
       set_current_job (job);
       jobs[job]->flags |= J_FOREGROUND;
     }
   /* Tell the outside world what we're doing. */
   p = jobs[job]->pipe;
   if (foreground == 0)
     {
       /* POSIX.2 says `bg' doesn't give any indication about current or
      previous job. */
       if (posixly_correct == 0)
     s = (job == js.j_current) ? "+ ": ((job == js.j_previous) ? "- " : " ");
       else
     s = " ";
       printf ("[%d]%s", job + 1, s);
     }
   do
     {
       printf ("%s%s",
            p->command ? p->command : "",
            p->next != jobs[job]->pipe? " | " : "");
       p = p->next;
     }
   while (p != jobs[job]->pipe);
   if (foreground == 0)
     printf (" &");
   if (strcmp (wd, jobs[job]->wd) != 0)
     printf ("   (wd: %s)", polite_directory_format (jobs[job]->wd));
   printf ("\n");
   /* Run the job. */
   if (already_running == 0)
     set_job_running (job);
   /* Save the tty settings before we start the job in the foreground. */
   if (foreground)
     {
       get_tty_state ();
       save_stty = shell_tty_info;
       /* Give the terminal to this job. */
       if (IS_JOBCONTROL (job))
     give_terminal_to (jobs[job]->pgrp, 0);
     }
   else
     jobs[job]->flags &= ~J_FOREGROUND;
   /* If the job is already running, then don't bother jump-starting it. */
   if (already_running == 0)
     {
       jobs[job]->flags |= J_NOTIFIED;
       killpg (jobs[job]->pgrp, SIGCONT);
     }
   if (foreground)
     {
       pid_t pid;
       int st;
       pid = find_last_pid (job, 0);
       UNBLOCK_CHILD (oset);
       st = wait_for (pid, 0);
       shell_tty_info = save_stty;
       set_tty_state ();
       return (st);
     }
   else
     {
       reset_current ();
       UNBLOCK_CHILD (oset);
       return (0);
     }
 }
References _, BLOCK_CHILD, current_working_directory(), DEADJOB, find_last_pid(), job::flags, get_tty_state(), give_terminal_to(), internal_error(), IS_JOBCONTROL, jobstats::j_current, J_FOREGROUND, J_NOTIFIED, jobstats::j_previous, jobs, js, killpg, p, pid, job::pipe, pipeline_pgrp, polite_directory_format(), posixly_correct, printf(), reset_current(), RUNNING, s, set_current_job(), set_job_running(), set_tty_state(), shell_pgrp, shell_tty_info, SIGCONT, strcmp, SUBSHELL_COMSUB, subshell_environment, this_command_name, TTYSTRUCT, UNBLOCK_CHILD, and wait_for().
Referenced by execute_simple_command().
start_pipeline()
void start_pipeline ()
Definition at line 523 of file jobs.c.
 {
   if (the_pipeline)
     {
       cleanup_the_pipeline ();
       /* If job_control == 0, pipeline_pgrp will always be equal to shell_pgrp;
      if job_control != 0, pipeline_pgrp == shell_pgrp for command and
      process substitution, in which case we want it to be the same as
      shell_pgrp for the lifetime of this shell instance. */
       if (pipeline_pgrp != shell_pgrp)
     pipeline_pgrp = 0;
 #if defined (PGRP_PIPE)
       sh_closepipe (pgrp_pipe);
 #endif
     }
 #if defined (PGRP_PIPE)
   if (job_control)
     {
       if (pipe (pgrp_pipe) == -1)
     sys_error (_("start_pipeline: pgrp pipe"));
     }
 #endif
 }
References _, cleanup_the_pipeline(), job_control, pipeline_pgrp, sh_closepipe(), shell_pgrp, sys_error(), and the_pipeline.
Referenced by kill_current_pipeline(), making_children(), and without_job_control().
stop_making_children()
void stop_making_children ()
Definition at line 431 of file jobs.c.
 {
   already_making_children = 0;
 }
References already_making_children.
Referenced by command_substitute(), kill_current_pipeline(), push_builtin(), run_debug_trap(), stop_pipeline(), and without_job_control().
stop_pipeline()
int stop_pipeline (int async, COMMAND * deferred)
Definition at line 553 of file jobs.c.
 {
   register int i, j;
   JOB *newjob;
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
 #if defined (PGRP_PIPE)
   /* The parent closes the process group synchronization pipe. */
   sh_closepipe (pgrp_pipe);
 #endif
   cleanup_dead_jobs ();
   if (js.j_jobslots == 0)
     {
       js.j_jobslots = JOB_SLOTS;
       jobs = (JOB **)xmalloc (js.j_jobslots * sizeof (JOB *));
       /* Now blank out these new entries. */
       for (i = 0; i < js.j_jobslots; i++)
     jobs[i] = (JOB *)NULL;
       js.j_firstj = js.j_lastj = js.j_njobs = 0;
     }
   /* Scan from the last slot backward, looking for the next free one. */
   /* XXX - revisit this interactive assumption */
   /* XXX - this way for now */
   if (interactive)
     {
       for (i = js.j_jobslots; i; i--)
     if (jobs[i - 1])
       break;
     }
   else
     {
 #if 0
       /* This wraps around, but makes it inconvenient to extend the array */
       for (i = js.j_lastj+1; i != js.j_lastj; i++)
     {
       if (i >= js.j_jobslots)
         i = 0;
       if (jobs[i] == 0)
         break;
     }
       if (i == js.j_lastj)
         i = js.j_jobslots;
 #else
       /* This doesn't wrap around yet. */
       for (i = js.j_lastj ? js.j_lastj + 1 : js.j_lastj; i < js.j_jobslots; i++)
     if (jobs[i] == 0)
       break;
 #endif
     }
   /* Do we need more room? */
   /* First try compaction */
   if ((interactive_shell == 0 || subshell_environment) && i == js.j_jobslots && js.j_jobslots >= MAX_JOBS_IN_ARRAY)
     i = compact_jobs_list (0);
   /* If we can't compact, reallocate */
   if (i == js.j_jobslots)
     {
       js.j_jobslots += JOB_SLOTS;
       jobs = (JOB **)xrealloc (jobs, (js.j_jobslots * sizeof (JOB *)));
       for (j = i; j < js.j_jobslots; j++)
     jobs[j] = (JOB *)NULL;
     }
   /* Add the current pipeline to the job list. */
   if (the_pipeline)
     {
       register PROCESS *p;
       int any_running, any_stopped, n;
       newjob = (JOB *)xmalloc (sizeof (JOB));
       for (n = 1, p = the_pipeline; p->next != the_pipeline; n++, p = p->next)
     ;
       p->next = (PROCESS *)NULL;
       newjob->pipe = REVERSE_LIST (the_pipeline, PROCESS *);
       for (p = newjob->pipe; p->next; p = p->next)
     ;
       p->next = newjob->pipe;
       the_pipeline = (PROCESS *)NULL;
       newjob->pgrp = pipeline_pgrp;
       /* Invariant: if the shell is executing a command substitution,
      pipeline_pgrp == shell_pgrp. Other parts of the shell assume this. */
       if (pipeline_pgrp != shell_pgrp)
     pipeline_pgrp = 0;
       newjob->flags = 0;
       if (pipefail_opt)
     newjob->flags |= J_PIPEFAIL;
       /* Flag to see if in another pgrp. */
       if (job_control)
     newjob->flags |= J_JOBCONTROL;
       /* Set the state of this pipeline. */
       p = newjob->pipe;
       any_running = any_stopped = 0;
       do
     {
       any_running |= PRUNNING (p);
       any_stopped |= PSTOPPED (p);
       p = p->next;
     }
       while (p != newjob->pipe);
       newjob->state = any_running ? JRUNNING : (any_stopped ? JSTOPPED : JDEAD);
       newjob->wd = job_working_directory ();
       newjob->deferred = deferred;
       newjob->j_cleanup = (sh_vptrfunc_t *)NULL;
       newjob->cleanarg = (PTR_T) NULL;
       jobs[i] = newjob;
       if (newjob->state == JDEAD && (newjob->flags & J_FOREGROUND))
     setjstatus (i);
       if (newjob->state == JDEAD)
     {
       js.c_reaped += n; /* wouldn't have been done since this was not part of a job */
       js.j_ndead++;
     }
       js.c_injobs += n;
       js.j_lastj = i;
       js.j_njobs++;
     }
   else
     newjob = (JOB *)NULL;
   if (newjob)
     js.j_lastmade = newjob;
   if (async)
     {
       if (newjob)
     {
       newjob->flags &= ~J_FOREGROUND;
       newjob->flags |= J_ASYNC;
       js.j_lastasync = newjob;
     }
       reset_current ();
     }
   else
     {
       if (newjob)
     {
       newjob->flags |= J_FOREGROUND;
       /*
        *        !!!!! NOTE !!!!!  (chet@po.cwru.edu)
        *
        * The currently-accepted job control wisdom says to set the
        * terminal's process group n+1 times in an n-step pipeline:
        * once in the parent and once in each child.  This is where
        * the parent gives it away.
        *
        * Don't give the terminal away if this shell is an asynchronous
        * subshell or if we're a (presumably non-interactive) shell running
        * in the background.
        *
        */
       if (job_control && newjob->pgrp && (subshell_environment&SUBSHELL_ASYNC) == 0 && running_in_background == 0)
         maybe_give_terminal_to (shell_pgrp, newjob->pgrp, 0);
     }
     }
   stop_making_children ();
   UNBLOCK_CHILD (oset);
   return (newjob ? i : js.j_current);
 }
References BLOCK_CHILD, jobstats::c_injobs, jobstats::c_reaped, cleanup_dead_jobs(), compact_jobs_list(), job::flags, i, interactive, interactive_shell, j, J_ASYNC, jobstats::j_current, jobstats::j_firstj, J_FOREGROUND, J_JOBCONTROL, jobstats::j_jobslots, jobstats::j_lastasync, jobstats::j_lastj, jobstats::j_lastmade, jobstats::j_ndead, jobstats::j_njobs, J_PIPEFAIL, JDEAD, job_control, JOB_SLOTS, job_working_directory(), jobs, JRUNNING, js, JSTOPPED, MAX_JOBS_IN_ARRAY, maybe_give_terminal_to(), n, NULL, p, job::pgrp, job::pipe, pipefail_opt, pipeline_pgrp, PRUNNING, PSTOPPED, PTR_T, reset_current(), REVERSE_LIST, running_in_background, setjstatus(), sh_closepipe(), shell_pgrp, job::state, stop_making_children(), SUBSHELL_ASYNC, subshell_environment, the_pipeline, UNBLOCK_CHILD, job::wd, xmalloc, and xrealloc.
Referenced by execute_command_internal(), execute_function(), execute_pipeline(), and push_builtin().
tcgetpgrp()
pid_t tcgetpgrp (int fd)
Definition at line 358 of file jobs.c.
 {
   pid_t pgrp;
   /* ioctl will handle setting errno correctly. */
   if (ioctl (fd, TIOCGPGRP, &pgrp) < 0)
     return (-1);
   return (pgrp);
 }
References fd, ioctl(), and TIOCGPGRP.
Referenced by hush_main(), initialize_job_control(), maybe_give_terminal_to(), and set_job_control().
terminate_current_pipeline()
void terminate_current_pipeline ()
Definition at line 1632 of file jobs.c.
 {
   if (pipeline_pgrp && pipeline_pgrp != shell_pgrp)
     {
       killpg (pipeline_pgrp, SIGTERM);
       killpg (pipeline_pgrp, SIGCONT);
     }
 }
References killpg, pipeline_pgrp, shell_pgrp, SIGCONT, and SIGTERM.
Referenced by execute_pipeline(), and make_child().
terminate_stopped_jobs()
void terminate_stopped_jobs ()
Definition at line 1643 of file jobs.c.
 {
   register int i;
   /* XXX could use js.j_firstj here */
   for (i = 0; i < js.j_jobslots; i++)
     {
       if (jobs[i] && STOPPED (i))
     {
       killpg (jobs[i]->pgrp, SIGTERM);
       killpg (jobs[i]->pgrp, SIGCONT);
     }
     }
 }
References i, jobstats::j_jobslots, jobs, js, killpg, SIGCONT, SIGTERM, and STOPPED.
Referenced by end_job_control().
unfreeze_jobs_list()
void unfreeze_jobs_list ()
Definition at line 4943 of file jobs.c.
 {
   jobs_list_frozen = 0;
 }
References jobs_list_frozen.
Referenced by parse_and_execute_cleanup().
wait_for()
int wait_for (pid_t pid, int flags)
Definition at line 2899 of file jobs.c.
 {
   int job, termination_state, r;
   WAIT s;
   register PROCESS *child;
   sigset_t set, oset;
   /* In the case that this code is interrupted, and we longjmp () out of it,
      we are relying on the code in throw_to_top_level () to restore the
      top-level signal mask. */
   child = 0;
   BLOCK_CHILD (set, oset);
   /* Ignore interrupts while waiting for a job run without job control
      to finish.  We don't want the shell to exit if an interrupt is
      received, only if one of the jobs run is killed via SIGINT.  If
      job control is not set, the job will be run in the same pgrp as
      the shell, and the shell will see any signals the job gets.  In
      fact, we want this set every time the waiting shell and the waited-
      for process are in the same process group, including command
      substitution. */
   /* This is possibly a race condition -- should it go in stop_pipeline? */
   wait_sigint_received = child_caught_sigint = 0;
   if (job_control == 0 || (subshell_environment&SUBSHELL_COMSUB))
     {
       SigHandler *temp_sigint_handler;
       temp_sigint_handler = set_signal_handler (SIGINT, wait_sigint_handler);
       if (temp_sigint_handler == wait_sigint_handler)
     internal_debug ("wait_for: recursively setting old_sigint_handler to wait_sigint_handler: running_trap = %d", running_trap);
       else
     old_sigint_handler = temp_sigint_handler;
       waiting_for_child = 0;
       if (old_sigint_handler == SIG_IGN)
     set_signal_handler (SIGINT, old_sigint_handler);
     }
   termination_state = last_command_exit_value;
   if (interactive && job_control == 0)
     QUIT;
   /* Check for terminating signals and exit the shell if we receive one */
   CHECK_TERMSIG;
   /* Check for a trapped signal interrupting the wait builtin and jump out */
   CHECK_WAIT_INTR;
   /* If we say wait_for (), then we have a record of this child somewhere.
      If it and none of its peers are running, don't call waitchld(). */
   job = NO_JOB;
   do
     {
       if (pid != ANY_PID)
     FIND_CHILD (pid, child);
       /* If this child is part of a job, then we are really waiting for the
      job to finish.  Otherwise, we are waiting for the child to finish.
      We check for JDEAD in case the job state has been set by waitchld
      after receipt of a SIGCHLD. */
       if (job == NO_JOB && pid != ANY_PID)  /* XXX -- && pid != ANY_PID ? */
     job = find_job (pid, 0, NULL);
       /* waitchld() takes care of setting the state of the job.  If the job
      has already exited before this is called, sigchld_handler will have
      called waitchld and the state will be set to JDEAD. */
       if (pid == ANY_PID || PRUNNING(child) || (job != NO_JOB && RUNNING (job)))
     {
       int old_waiting;
       queue_sigchld = 1;
       old_waiting = waiting_for_child;
       waiting_for_child = 1;
       /* XXX - probably not strictly necessary but we want to catch
          everything that happened before we switch the behavior of
          trap_handler to longjmp on a trapped signal (waiting_for_child) */
       CHECK_WAIT_INTR;
       r = waitchld (pid, 1);    /* XXX */
       waiting_for_child = old_waiting;
 #if 0
 itrace("wait_for: blocking wait for %d returns %d child = %p", (int)pid, r, child);
 #endif
       queue_sigchld = 0;
       if (r == -1 && errno == ECHILD && this_shell_builtin == wait_builtin)
         {
           termination_state = -1;
           /* XXX - restore sigint handler here */
           restore_sigint_handler ();
           goto wait_for_return;
         }
       /* If child is marked as running, but waitpid() returns -1/ECHILD,
          there is something wrong.  Somewhere, wait should have returned
          that child's pid.  Mark the child as not running and the job,
          if it exists, as JDEAD. */
       if (r == -1 && errno == ECHILD)
         {
           if (child)
         {
           child->running = PS_DONE;
           WSTATUS (child->status) = 0;  /* XXX -- can't find true status */
         }
           js.c_living = 0;      /* no living child processes */
           if (job != NO_JOB)
         {
           jobs[job]->state = JDEAD;
           js.c_reaped++;
           js.j_ndead++;
         }
           if (pid == ANY_PID)
         {
           termination_state = -1;
           break;
         }
         }
     }
       /* If the shell is interactive, and job control is disabled, see
      if the foreground process has died due to SIGINT and jump out
      of the wait loop if it has.  waitchld has already restored the
      old SIGINT signal handler. */
       if (interactive && job_control == 0)
     QUIT;
       /* Check for terminating signals and exit the shell if we receive one */
       CHECK_TERMSIG;
       /* Check for a trapped signal interrupting the wait builtin and jump out */
       CHECK_WAIT_INTR;
       if (pid == ANY_PID)
     {
       /* XXX - could set child but we don't have a handle on what waitchld
         reaps.  Leave termination_state alone. */
       restore_sigint_handler ();
       goto wait_for_return;
     }
     }
   while (PRUNNING (child) || (job != NO_JOB && RUNNING (job)));
   /* Restore the original SIGINT signal handler before we return. */
   restore_sigint_handler ();
   /* The exit state of the command is either the termination state of the
      child, or the termination state of the job.  If a job, the status
      of the last child in the pipeline is the significant one.  If the command
      or job was terminated by a signal, note that value also. */
   termination_state = (job != NO_JOB) ? job_exit_status (job)
                       : (child ? process_exit_status (child->status) : EXECUTION_SUCCESS);
   last_command_exit_signal = (job != NO_JOB) ? job_exit_signal (job)
                          : (child ? process_exit_signal (child->status) : 0);
   /* XXX */
   if ((job != NO_JOB && JOBSTATE (job) == JSTOPPED) || (child && WIFSTOPPED (child->status)))
     termination_state = 128 + WSTOPSIG (child->status);
   if (job == NO_JOB || IS_JOBCONTROL (job))
     {
       /* XXX - under what circumstances is a job not present in the jobs
      table (job == NO_JOB)?
         1.  command substitution
      In the case of command substitution, at least, it's probably not
      the right thing to give the terminal to the shell's process group,
      even though there is code in subst.c:command_substitute to work
      around it.
      Things that don't:
         $PROMPT_COMMAND execution
         process substitution
        */
 #if 0
 if (job == NO_JOB)
   itrace("wait_for: job == NO_JOB, giving the terminal to shell_pgrp (%ld)", (long)shell_pgrp);
 #endif
       /* Don't modify terminal pgrp if we are running in background or a
      subshell.  Make sure subst.c:command_substitute uses the same
      conditions to determine whether or not it should undo this and
      give the terminal to pipeline_pgrp. */
       if ((flags & JWAIT_NOTERM) == 0 && running_in_background == 0 &&
       (subshell_environment & (SUBSHELL_ASYNC|SUBSHELL_PIPE)) == 0)
     give_terminal_to (shell_pgrp, 0);
     }
   /* If the command did not exit cleanly, or the job is just
      being stopped, then reset the tty state back to what it
      was before this command.  Reset the tty state and notify
      the user of the job termination only if the shell is
      interactive.  Clean up any dead jobs in either case. */
   if (job != NO_JOB)
     {
       if (interactive_shell && subshell_environment == 0)
     {
       /* This used to use `child->status'.  That's wrong, however, for
          pipelines.  `child' is the first process in the pipeline.  It's
          likely that the process we want to check for abnormal termination
          or stopping is the last process in the pipeline, especially if
          it's long-lived and the first process is short-lived.  Since we
          know we have a job here, we can check all the processes in this
          job's pipeline and see if one of them stopped or terminated due
          to a signal.  We might want to change this later to just check
          the last process in the pipeline.  If no process exits due to a
          signal, S is left as the status of the last job in the pipeline. */
       s = job_signal_status (job);
       if (WIFSIGNALED (s) || WIFSTOPPED (s))
         {
           set_tty_state ();
           /* If the current job was stopped or killed by a signal, and
          the user has requested it, get a possibly new window size */
           if (check_window_size && (job == js.j_current || IS_FOREGROUND (job)))
         get_new_window_size (0, (int *)0, (int *)0);
         }
       else
 #if defined (READLINE)
         /* We don't want to do this if we are running a process during
            programmable completion or a command bound to `bind -x'. */
         if (RL_ISSTATE (RL_STATE_COMPLETING|RL_STATE_DISPATCHING|RL_STATE_TERMPREPPED) == 0)
 #endif
         get_tty_state ();
       /* If job control is enabled, the job was started with job
          control, the job was the foreground job, and it was killed
          by SIGINT, then print a newline to compensate for the kernel
          printing the ^C without a trailing newline. */
       if (job_control && IS_JOBCONTROL (job) && IS_FOREGROUND (job) &&
         WIFSIGNALED (s) && WTERMSIG (s) == SIGINT)
         {
           /* If SIGINT is not trapped and the shell is in a for, while,
          or until loop, act as if the shell received SIGINT as
          well, so the loop can be broken.  This doesn't call the
          SIGINT signal handler; maybe it should. */
           if (signal_is_trapped (SIGINT) == 0 && (loop_level || (shell_compatibility_level > 32 && executing_list)))
         ADDINTERRUPT;
           /* Call any SIGINT trap handler if the shell is running a loop, so
          the loop can be broken.  This seems more useful and matches the
          behavior when the shell is running a builtin command in a loop
          when it is interrupted.  Change ADDINTERRUPT to
          trap_handler (SIGINT) to run the trap without interrupting the
          loop. */
           else if (signal_is_trapped (SIGINT) && loop_level)
         ADDINTERRUPT;
           /* If an interactive shell with job control enabled is sourcing
          a file, allow the interrupt to terminate the file sourcing. */
           else if (interactive_shell && signal_is_trapped (SIGINT) == 0 && sourcelevel)
         ADDINTERRUPT;
           else
         {
           putchar ('\n');
           fflush (stdout);
         }
         }
     }
       else if ((subshell_environment & (SUBSHELL_COMSUB|SUBSHELL_PIPE)) && wait_sigint_received)
     {
       /* If waiting for a job in a subshell started to do command
          substitution or to run a pipeline element that consists of
          something like a while loop or a for loop, simulate getting
          and being killed by the SIGINT to pass the status back to our
          parent. */
       if (child_caught_sigint == 0 && signal_is_trapped (SIGINT) == 0)
         {
           UNBLOCK_CHILD (oset);
           old_sigint_handler = set_signal_handler (SIGINT, SIG_DFL);
           if (old_sigint_handler == SIG_IGN)
         restore_sigint_handler ();
           else
         kill (getpid (), SIGINT);
         }
     }
       else if (interactive_shell == 0 && subshell_environment == 0 && IS_FOREGROUND (job))
     {
       s = job_signal_status (job);
       /* If we are non-interactive, but job control is enabled, and the job
          died due to SIGINT, pretend we got the SIGINT */
       if (job_control && IS_JOBCONTROL (job) && WIFSIGNALED (s) && WTERMSIG (s) == SIGINT)
         {
           ADDINTERRUPT; /* For now */
         }
       if (check_window_size)
         get_new_window_size (0, (int *)0, (int *)0);
     }
       /* Moved here from set_job_status_and_cleanup, which is in the SIGCHLD
      signal handler path */
       if (DEADJOB (job) && IS_FOREGROUND (job) /*&& subshell_environment == 0*/)
     setjstatus (job);
       /* If this job is dead, notify the user of the status.  If the shell
      is interactive, this will display a message on the terminal.  If
      the shell is not interactive, make sure we turn on the notify bit
      so we don't get an unwanted message about the job's termination,
      and so delete_job really clears the slot in the jobs table. */
       notify_and_cleanup ();
     }
 wait_for_return:
   UNBLOCK_CHILD (oset);
   return (termination_state);
 }
References ADDINTERRUPT, ANY_PID, BLOCK_CHILD, jobstats::c_living, jobstats::c_reaped, CHECK_TERMSIG, CHECK_WAIT_INTR, check_window_size, child(), child_caught_sigint, DEADJOB, ECHILD, errno, executing_list, EXECUTION_SUCCESS, fflush(), FIND_CHILD, find_job(), flags, get_new_window_size(), get_tty_state(), getpid(), give_terminal_to(), interactive, interactive_shell, internal_debug(), IS_FOREGROUND, IS_JOBCONTROL, jobstats::j_current, jobstats::j_ndead, JDEAD, job_control, job_exit_signal(), job_exit_status(), job_signal_status(), jobs, JOBSTATE, js, JSTOPPED, JWAIT_NOTERM, kill(), last_command_exit_signal, last_command_exit_value, loop_level, NO_JOB, notify_and_cleanup(), NULL, old_sigint_handler, pid, process_exit_signal(), process_exit_status(), PRUNNING, PS_DONE, putchar, queue_sigchld, QUIT, restore_sigint_handler(), RL_ISSTATE, RL_STATE_COMPLETING, RL_STATE_DISPATCHING, RL_STATE_TERMPREPPED, RUNNING, running_in_background, running_trap, s, set_signal_handler, set_tty_state(), setjstatus(), shell_compatibility_level, shell_pgrp, SIG_DFL, SIG_IGN, SIGINT, signal_is_trapped(), sourcelevel, job::state, stdout, SUBSHELL_ASYNC, SUBSHELL_COMSUB, subshell_environment, SUBSHELL_PIPE, this_shell_builtin, UNBLOCK_CHILD, wait_sigint_handler(), wait_sigint_received, waitchld(), waiting_for_child, WIFSIGNALED, WIFSTOPPED, WSTATUS, WSTOPSIG, and WTERMSIG.
Referenced by command_substitute(), execute_command_internal(), execute_pipeline(), push_builtin(), start_job(), wait_for_any_job(), wait_for_job(), and wait_for_single_pid().
wait_for_any_job()
int wait_for_any_job (int flags, struct procstat * ps)
Definition at line 3269 of file jobs.c.
 {
   pid_t pid;
   int i, r;
   sigset_t set, oset;
   if (jobs_list_frozen)
     return -1;
   /* First see if there are any unnotified dead jobs that we can report on */
   BLOCK_CHILD (set, oset);
   for (i = 0; i < js.j_jobslots; i++)
     {
       if ((flags & JWAIT_WAITING) && jobs[i] && IS_WAITING (i) == 0)
     continue;       /* if we don't want it, skip it */
       if (jobs[i] && DEADJOB (i) && IS_NOTIFIED (i) == 0)
     {
 return_job:
       r = job_exit_status (i);
       pid = find_last_pid (i, 0);
       if (ps)
         {
           ps->pid = pid;
           ps->status = r;
         }
       notify_of_job_status ();      /* XXX */
       delete_job (i, 0);
 #if defined (COPROCESS_SUPPORT)
       coproc_reap ();
 #endif
       UNBLOCK_CHILD (oset);
       return r;
     }
     }
   UNBLOCK_CHILD (oset);
   /* At this point, we have no dead jobs in the jobs table.  Wait until we
      get one, even if it takes multiple pids exiting. */
   for (;;)
     {
       /* Make sure there is a background job to wait for */
       BLOCK_CHILD (set, oset);
       for (i = 0; i < js.j_jobslots; i++)
     if (jobs[i] && RUNNING (i) && IS_FOREGROUND (i) == 0)
       break;
       if (i == js.j_jobslots)
     {
       UNBLOCK_CHILD (oset);
       return -1;
     }
       UNBLOCK_CHILD (oset);
       QUIT;
       CHECK_TERMSIG;
       CHECK_WAIT_INTR;
       errno = 0;
       r = wait_for (ANY_PID, 0);    /* special sentinel value for wait_for */
       if (r == -1 && errno == ECHILD)
     mark_all_jobs_as_dead ();
       /* Now we see if we have any dead jobs and return the first one */
       BLOCK_CHILD (set, oset);
       for (i = 0; i < js.j_jobslots; i++)
     {
       if ((flags & JWAIT_WAITING) && jobs[i] && IS_WAITING (i) == 0)
         continue;       /* if we don't want it, skip it */
       if (jobs[i] && DEADJOB (i))
         goto return_job;
     }
       UNBLOCK_CHILD (oset);
     }
   return -1;
 }
References ANY_PID, BLOCK_CHILD, CHECK_TERMSIG, CHECK_WAIT_INTR, DEADJOB, delete_job(), ECHILD, errno, find_last_pid(), flags, i, IS_FOREGROUND, IS_NOTIFIED, IS_WAITING, jobstats::j_jobslots, job_exit_status(), jobs, jobs_list_frozen, js, JWAIT_WAITING, mark_all_jobs_as_dead(), notify_of_job_status(), procstat::pid, pid, QUIT, RUNNING, procstat::status, UNBLOCK_CHILD, and wait_for().
wait_for_background_pids()
int wait_for_background_pids (struct procstat * ps)
Definition at line 2648 of file jobs.c.
 {
   register int i, r;
   int any_stopped, check_async, njobs;
   sigset_t set, oset;
   pid_t pid;
   for (njobs = any_stopped = 0, check_async = 1;;)
     {
       BLOCK_CHILD (set, oset);
       /* find first running job; if none running in foreground, break */
       /* XXX could use js.j_firstj and js.j_lastj here */
       for (i = 0; i < js.j_jobslots; i++)
     {
       if (i < js.j_firstj && jobs[i])
         INTERNAL_DEBUG (("wait_for_background_pids: job %d non-null before js.j_firstj (%d)", i, js.j_firstj));
       if (i > js.j_lastj && jobs[i])
         INTERNAL_DEBUG (("wait_for_background_pids: job %d non-null after js.j_lastj (%d)", i, js.j_lastj));
       if (jobs[i] && STOPPED (i))
         {
           builtin_warning ("job %d[%d] stopped", i+1, find_last_pid (i, 0));
           any_stopped = 1;
         }
       if (jobs[i] && RUNNING (i) && IS_FOREGROUND (i) == 0)
         break;
     }
       if (i == js.j_jobslots)
     {
       UNBLOCK_CHILD (oset);
       break;
     }
       /* now wait for the last pid in that job. */
       pid = find_last_pid (i, 0);
       UNBLOCK_CHILD (oset);
       QUIT;
       errno = 0;        /* XXX */
       r = wait_for_single_pid (pid, JWAIT_PERROR);
       if (ps)
     {
       ps->pid = pid;
       ps->status = (r < 0 || r > 256) ? 127 : r;
     }
       if (r == -1 && errno == ECHILD)
     {
       /* If we're mistaken about job state, compensate. */
       check_async = 0;
       mark_all_jobs_as_dead ();
     }
       njobs++;
     }
 #if defined (PROCESS_SUBSTITUTION)
   procsub_waitall ();
 #endif
   /* POSIX.2 says the shell can discard the statuses of all completed jobs if
      `wait' is called with no arguments. */
   mark_dead_jobs_as_notified (1);
   cleanup_dead_jobs ();
   bgp_clear ();
   return njobs;
 }
References bgp_clear(), BLOCK_CHILD, builtin_warning(), cleanup_dead_jobs(), ECHILD, errno, find_last_pid(), i, INTERNAL_DEBUG, IS_FOREGROUND, jobstats::j_firstj, jobstats::j_jobslots, jobstats::j_lastj, jobs, js, JWAIT_PERROR, mark_all_jobs_as_dead(), mark_dead_jobs_as_notified(), njobs, procstat::pid, pid, QUIT, RUNNING, procstat::status, STOPPED, UNBLOCK_CHILD, and wait_for_single_pid().
wait_for_job()
int wait_for_job (int job, int flags, struct procstat * ps)
Definition at line 3215 of file jobs.c.
 {
   pid_t pid;
   int r, state;
   sigset_t set, oset;
   BLOCK_CHILD(set, oset);
   state = JOBSTATE (job);
   if (state == JSTOPPED)
     internal_warning (_("wait_for_job: job %d is stopped"), job+1);
   pid = find_last_pid (job, 0);
   UNBLOCK_CHILD(oset);
   do
     {
       r = wait_for (pid, 0);
       if (r == -1 && errno == ECHILD)
     mark_all_jobs_as_dead ();
       CHECK_WAIT_INTR;
       if ((flags & JWAIT_FORCE) == 0)
     break;
       BLOCK_CHILD (set, oset);
       state = (job != NO_JOB && jobs[job]) ? JOBSTATE (job) : JDEAD;
       UNBLOCK_CHILD (oset);
     }
   while (state != JDEAD);
   /* POSIX.2: we can remove the job from the jobs table if we just waited
      for it. */
   BLOCK_CHILD (set, oset);
   if (job != NO_JOB && jobs[job] && DEADJOB (job))
     jobs[job]->flags |= J_NOTIFIED;
   UNBLOCK_CHILD (oset);
   if (ps)
     {
       ps->pid = pid;
       ps->status = (r < 0) ? 127 : r;
     }
   return r;
 }
References _, BLOCK_CHILD, CHECK_WAIT_INTR, DEADJOB, ECHILD, errno, find_last_pid(), job::flags, flags, internal_warning(), J_NOTIFIED, JDEAD, jobs, JOBSTATE, JSTOPPED, JWAIT_FORCE, mark_all_jobs_as_dead(), NO_JOB, procstat::pid, pid, state, procstat::status, UNBLOCK_CHILD, and wait_for().
wait_for_single_pid()
int wait_for_single_pid (pid_t pid, int flags)
Definition at line 2586 of file jobs.c.
 {
   register PROCESS *child;
   sigset_t set, oset;
   int r, job, alive;
   BLOCK_CHILD (set, oset);
   child = find_pipeline (pid, 0, (int *)NULL);
   UNBLOCK_CHILD (oset);
   if (child == 0)
     {
       r = bgp_search (pid);
       if (r >= 0)
     return r;
     }
   if (child == 0)
     {
       if (flags & JWAIT_PERROR)
     internal_error (_("wait: pid %ld is not a child of this shell"), (long)pid);
       return (257);
     }
   alive = 0;
   do
     {
       r = wait_for (pid, 0);
       if ((flags & JWAIT_FORCE) == 0)
     break;
       BLOCK_CHILD (set, oset);
       alive = PALIVE (child);
       UNBLOCK_CHILD (oset);
     }
   while (alive);
   /* POSIX.2: if we just waited for a job, we can remove it from the jobs
      table. */
   BLOCK_CHILD (set, oset);
   job = find_job (pid, 0, NULL);
   if (job != NO_JOB && jobs[job] && DEADJOB (job))
     jobs[job]->flags |= J_NOTIFIED;
   UNBLOCK_CHILD (oset);
   /* If running in posix mode, remove the job from the jobs table immediately */
   if (posixly_correct)
     {
       cleanup_dead_jobs ();
       bgp_delete (pid);
     }
   /* Check for a trapped signal interrupting the wait builtin and jump out */
   CHECK_WAIT_INTR;
   return r;
 }
References _, bgp_delete(), bgp_search(), BLOCK_CHILD, CHECK_WAIT_INTR, child(), cleanup_dead_jobs(), DEADJOB, find_job(), find_pipeline(), job::flags, flags, internal_error(), J_NOTIFIED, jobs, JWAIT_FORCE, JWAIT_PERROR, NO_JOB, NULL, PALIVE, pid, posixly_correct, UNBLOCK_CHILD, and wait_for().
Referenced by execute_pipeline(), and wait_for_background_pids().
wait_sigint_cleanup()
void wait_sigint_cleanup ()
Definition at line 2728 of file jobs.c.
 {
   queue_sigchld = 0;
   waiting_for_child = 0;
   restore_sigint_handler ();
 }
References queue_sigchld, restore_sigint_handler(), and waiting_for_child.
wait_sigint_handler()
static sighandler wait_sigint_handler (int sig) static
Definition at line 2750 of file jobs.c.
 {
   SigHandler *sigint_handler;
   if (this_shell_builtin && this_shell_builtin == wait_builtin)
     {
       set_exit_status (128+SIGINT);
       restore_sigint_handler ();
       /* If we got a SIGINT while in `wait', and SIGINT is trapped, do
      what POSIX.2 says (see builtins/wait.def for more info). */
       if (this_shell_builtin && this_shell_builtin == wait_builtin &&
       signal_is_trapped (SIGINT) &&
       ((sigint_handler = trap_to_sighandler (SIGINT)) == trap_handler))
     {
       trap_handler (SIGINT);    /* set pending_traps[SIGINT] */
       wait_signal_received = SIGINT;
       if (wait_intr_flag)
         sh_longjmp (wait_intr_buf, 1);
       else
         /* Let CHECK_WAIT_INTR handle it in wait_for/waitchld */
         SIGRETURN (0);
     }
       else /* wait_builtin but signal not trapped, treat as interrupt */
     kill (getpid (), SIGINT);
     }
   /* XXX - should this be interrupt_state?  If it is, the shell will act
      as if it got the SIGINT interrupt. */
   if (waiting_for_child)
     wait_sigint_received = 1;
   else
     {
       set_exit_status (128+SIGINT);
       restore_sigint_handler ();
       kill (getpid (), SIGINT);
     }
   /* Otherwise effectively ignore the SIGINT and allow the running job to
      be killed. */
   SIGRETURN (0);
 }
References getpid(), kill(), restore_sigint_handler(), set_exit_status(), sh_longjmp, SIGINT, signal_is_trapped(), SIGRETURN, this_shell_builtin, trap_handler(), trap_to_sighandler(), wait_intr_buf, wait_intr_flag, wait_sigint_received, wait_signal_received, and waiting_for_child.
Referenced by wait_for().
waitchld()
static int waitchld (pid_t wpid, int block) static
Definition at line 3764 of file jobs.c.
 {
   WAIT status;
   PROCESS *child;
   pid_t pid;
   int ind;
   int call_set_current, last_stopped_job, job, children_exited, waitpid_flags;
   static int wcontinued = WCONTINUED;   /* run-time fix for glibc problem */
   call_set_current = children_exited = 0;
   last_stopped_job = NO_JOB;
   do
     {
       /* We don't want to be notified about jobs stopping if job control
      is not active.  XXX - was interactive_shell instead of job_control */
       waitpid_flags = (job_control && subshell_environment == 0)
             ? (WUNTRACED|wcontinued)
             : 0;
       if (sigchld || block == 0)
     waitpid_flags |= WNOHANG;
       /* Check for terminating signals and exit the shell if we receive one */
       CHECK_TERMSIG;
       /* Check for a trapped signal interrupting the wait builtin and jump out */
       CHECK_WAIT_INTR;
       if (block == 1 && queue_sigchld == 0 && (waitpid_flags & WNOHANG) == 0)
     {
       internal_warning (_("waitchld: turning on WNOHANG to avoid indefinite block"));
       waitpid_flags |= WNOHANG;
     }
       pid = WAITPID (-1, &status, waitpid_flags);
 #if 0
 if (wpid != -1 && block)
   itrace("waitchld: blocking waitpid returns %d", pid);
 #endif
 #if 0
 if (wpid != -1)
   itrace("waitchld: %s waitpid returns %d", block?"blocking":"non-blocking", pid);
 #endif
       /* WCONTINUED may be rejected by waitpid as invalid even when defined */
       if (wcontinued && pid < 0 && errno == EINVAL)
     {
       wcontinued = 0;
       continue; /* jump back to the test and retry without WCONTINUED */
     }
       /* The check for WNOHANG is to make sure we decrement sigchld only
      if it was non-zero before we called waitpid. */
       if (sigchld > 0 && (waitpid_flags & WNOHANG))
     sigchld--;
       /* If waitpid returns -1 with errno == ECHILD, there are no more
      unwaited-for child processes of this shell. */
       if (pid < 0 && errno == ECHILD)
     {
       if (children_exited == 0)
         return -1;
       else
         break;
     }
 #if 0
 itrace("waitchld: waitpid returns %d block = %d children_exited = %d", pid, block, children_exited);
 #endif
       /* If waitpid returns 0, there are running children.  If it returns -1,
      the only other error POSIX says it can return is EINTR. */
       CHECK_TERMSIG;
       CHECK_WAIT_INTR;
       /* If waitpid returns -1/EINTR and the shell saw a SIGINT, then we
      assume the child has blocked or handled SIGINT.  In that case, we
      require the child to actually die due to SIGINT to act on the
      SIGINT we received; otherwise we assume the child handled it and
      let it go. */
       if (pid < 0 && errno == EINTR && wait_sigint_received)
     child_caught_sigint = 1;
       if (pid <= 0)
     continue;   /* jumps right to the test */
       /* Linux kernels appear to signal the parent but not interrupt the
      waitpid() (or restart it even without SA_RESTART) on SIGINT, so if
      we saw a SIGINT and the process exited or died due to some other
      signal, assume the child caught the SIGINT. */
       if (wait_sigint_received && (WIFSIGNALED (status) == 0 || WTERMSIG (status) != SIGINT))
     child_caught_sigint = 1;
       /* If the child process did die due to SIGINT, forget our assumption
      that it caught or otherwise handled it. */
       if (WIFSIGNALED (status) && WTERMSIG (status) == SIGINT)
     child_caught_sigint = 0;
       /* children_exited is used to run traps on SIGCHLD.  We don't want to
      run the trap if a process is just being continued. */
       if (WIFCONTINUED(status) == 0)
     {
       children_exited++;
       js.c_living--;
     }
       /* Locate our PROCESS for this pid. */
       child = find_process (pid, 1, &job);  /* want living procs only */
 #if defined (COPROCESS_SUPPORT)
       coproc_pidchk (pid, WSTATUS(status));
 #endif
 #if defined (PROCESS_SUBSTITUTION)
       /* Only manipulate the list of process substitutions while SIGCHLD
      is blocked. We only use this as a hint that we can remove FIFOs
      or close file descriptors corresponding to terminated process
      substitutions. */
       if ((ind = find_procsub_child (pid)) >= 0)
     set_procsub_status (ind, pid, WSTATUS (status));
 #endif
       /* It is not an error to have a child terminate that we did
      not have a record of.  This child could have been part of
      a pipeline in backquote substitution.  Even so, I'm not
      sure child is ever non-zero. */
       if (child == 0)
     {
       if (WIFEXITED (status) || WIFSIGNALED (status))
         js.c_reaped++;
       continue;
     }
       /* Remember status, and whether or not the process is running. */
       child->status = status;
       child->running = WIFCONTINUED(status) ? PS_RUNNING : PS_DONE;
       if (PEXITED (child))
     {
       js.c_totreaped++;
       if (job != NO_JOB)
         js.c_reaped++;
     }
       if (job == NO_JOB)
     continue;
       call_set_current += set_job_status_and_cleanup (job);
       if (STOPPED (job))
     last_stopped_job = job;
       else if (DEADJOB (job) && last_stopped_job == job)
     last_stopped_job = NO_JOB;
     }
   while ((sigchld || block == 0) && pid > (pid_t)0);
   /* If a job was running and became stopped, then set the current
      job.  Otherwise, don't change a thing. */
   if (call_set_current)
     {
       if (last_stopped_job != NO_JOB)
     set_current_job (last_stopped_job);
       else
     reset_current ();
     }
   /* Call a SIGCHLD trap handler for each child that exits, if one is set. */
   if (children_exited &&
       (signal_is_trapped (SIGCHLD) || trap_list[SIGCHLD] == (char *)IMPOSSIBLE_TRAP_HANDLER) &&
       trap_list[SIGCHLD] != (char *)IGNORE_SIG)
     {
       if (posixly_correct && this_shell_builtin && this_shell_builtin == wait_builtin)
     {
       /* This was trap_handler (SIGCHLD) but that can lose traps if
          children_exited > 1 */
       queue_sigchld_trap (children_exited);
       wait_signal_received = SIGCHLD;
       /* If we're in a signal handler, let CHECK_WAIT_INTR pick it up;
          run_pending_traps will call run_sigchld_trap later  */
       if (sigchld == 0 && wait_intr_flag)
         sh_longjmp (wait_intr_buf, 1);
     }
       /* If not in posix mode and not executing the wait builtin, queue the
      signal for later handling.  Run the trap immediately if we are
      executing the wait builtin, but don't break out of `wait'. */
       else if (sigchld) /* called from signal handler */
     queue_sigchld_trap (children_exited);
       else if (signal_in_progress (SIGCHLD))
     queue_sigchld_trap (children_exited);
       else if (trap_list[SIGCHLD] == (char *)IMPOSSIBLE_TRAP_HANDLER)
     queue_sigchld_trap (children_exited);
       else if (running_trap)
     queue_sigchld_trap (children_exited);
       else if (this_shell_builtin == wait_builtin)
     run_sigchld_trap (children_exited); /* XXX */
       else
     queue_sigchld_trap (children_exited);
     }
   /* We have successfully recorded the useful information about this process
      that has just changed state.  If we notify asynchronously, and the job
      that this process belongs to is no longer running, then notify the user
      of that fact now. */
   if (asynchronous_notification && interactive && executing_builtin == 0)
     notify_of_job_status ();
   return (children_exited);
 }
References _, asynchronous_notification, jobstats::c_living, jobstats::c_reaped, jobstats::c_totreaped, CHECK_TERMSIG, CHECK_WAIT_INTR, child(), child_caught_sigint, DEADJOB, ECHILD, EINTR, EINVAL, errno, executing_builtin, find_process(), IGNORE_SIG, IMPOSSIBLE_TRAP_HANDLER, interactive, internal_warning(), job_control, js, NO_JOB, notify_of_job_status(), PEXITED, pid, posixly_correct, PS_DONE, PS_RUNNING, queue_sigchld, reset_current(), run_sigchld_trap(), running_trap, set_current_job(), set_job_status_and_cleanup(), sh_longjmp, sigchld, SIGCHLD, SIGINT, signal_in_progress(), signal_is_trapped(), status, STOPPED, subshell_environment, this_shell_builtin, trap_list, wait_intr_buf, wait_intr_flag, wait_sigint_received, wait_signal_received, WAITPID, WCONTINUED, WIFCONTINUED, WIFEXITED, WIFSIGNALED, WNOHANG, WSTATUS, WTERMSIG, and WUNTRACED.
Referenced by make_child(), sigchld_handler(), and wait_for().
without_job_control()
void without_job_control ()
Definition at line 4997 of file jobs.c.
 {
   stop_making_children ();
   start_pipeline ();
 #if defined (PGRP_PIPE)
   sh_closepipe (pgrp_pipe);
 #endif
   delete_all_jobs (0);
   set_job_control (0);
 }
References delete_all_jobs(), set_job_control(), sh_closepipe(), start_pipeline(), and stop_making_children().
Referenced by execute_disk_command(), execute_in_subshell(), execute_subshell_builtin_or_function(), and initialize_subshell().
Variable Documentation
already_making_children
int already_making_children = 0
Definition at line 228 of file jobs.c.
Referenced by execute_command_internal(), making_children(), restore_pipeline(), save_pipeline(), and stop_making_children().
bgpids
struct bgpids bgpids = { 0, 0, 0, 0 }
Definition at line 177 of file jobs.c.
check_window_size
int check_window_size = CHECKWINSIZE_DEFAULT
Definition at line 232 of file jobs.c.
Referenced by default_columns(), get_tty_state(), and wait_for().
child_caught_sigint
int child_caught_sigint static
Definition at line 2722 of file jobs.c.
Referenced by set_job_status_and_cleanup(), wait_for(), and waitchld().
errno
int errno extern
Referenced by give_terminal_to(), initialize_job_control(), make_child(), maybe_give_terminal_to(), set_maxchild(), sigchld_handler(), wait_for(), wait_for_any_job(), wait_for_background_pids(), wait_for_job(), and waitchld().
job_control
int job_control = 1
Definition at line 222 of file jobs.c.
Referenced by end_job_control(), execute_connection(), execute_pipeline(), execute_simple_command(), give_terminal_to(), initialize_job_control(), initialize_job_signals(), make_child(), notify_of_job_status(), set_job_control(), set_job_status_and_cleanup(), setup_async_signals(), start_pipeline(), stop_pipeline(), wait_for(), and waitchld().
jobs
JOB** jobs = (JOB **)NULL
Definition at line 183 of file jobs.c.
Referenced by append_process(), cleanup_dead_jobs(), compact_jobs_list(), count_all_jobs(), delete_all_jobs(), delete_job(), delete_old_job(), find_job(), find_last_proc(), find_pipeline(), hangup_all_jobs(), job_signal_status(), kill_pid(), map_over_jobs(), mark_all_jobs_as_dead(), mark_dead_jobs_as_notified(), most_recent_job_in_state(), nohup_all_jobs(), nohup_job(), notify_of_job_status(), pretty_print_job(), print_pipeline(), processes_in_job(), raw_job_exit_status(), realloc_jobs_list(), reset_current(), reset_job_indices(), set_current_job(), set_job_running(), set_job_status_and_cleanup(), setjstatus(), start_job(), stop_pipeline(), terminate_stopped_jobs(), wait_for(), wait_for_any_job(), wait_for_background_pids(), wait_for_job(), and wait_for_single_pid().
jobs_list_frozen
int jobs_list_frozen static
Definition at line 346 of file jobs.c.
Referenced by cleanup_dead_jobs(), compact_jobs_list(), delete_job(), freeze_jobs_list(), notify_and_cleanup(), run_sigchld_trap(), set_job_status_and_cleanup(), set_jobs_list_frozen(), unfreeze_jobs_list(), and wait_for_any_job().
js
struct jobstats js = { -1L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NO_JOB, NO_JOB, 0, 0 }
Definition at line 172 of file jobs.c.
Referenced by append_process(), bgp_add(), bgp_getindex(), bgp_resize(), cleanup_dead_jobs(), compact_jobs_list(), count_all_jobs(), delete_all_jobs(), delete_job(), find_job(), hangup_all_jobs(), init_job_stats(), make_child(), map_over_jobs(), mark_all_jobs_as_dead(), mark_dead_jobs_as_notified(), nohup_all_jobs(), nohup_job(), notify_of_job_status(), pretty_print_job(), realloc_jobs_list(), reset_current(), reset_job_indices(), set_current_job(), set_job_status_and_cleanup(), set_maxchild(), start_job(), stop_pipeline(), terminate_stopped_jobs(), volume_id_probe_jfs(), wait_for(), wait_for_any_job(), wait_for_background_pids(), and waitchld().
last_asynchronous_pid
volatile pid_t last_asynchronous_pid = NO_PID
Definition at line 216 of file jobs.c.
Referenced by command_substitute(), execute_command_internal(), execute_simple_command(), make_child(), mark_dead_jobs_as_notified(), notify_of_job_status(), param_expand(), parameter_brace_expand_length(), and push_builtin().
last_made_pid
volatile pid_t last_made_pid = NO_PID
Definition at line 213 of file jobs.c.
Referenced by command_substitute(), execute_command_internal(), execute_pipeline(), make_child(), and run_sigchld_trap().
last_procsub_child
PROCESS* last_procsub_child = (PROCESS *)NULL
Definition at line 234 of file jobs.c.
Referenced by cleanup_dead_jobs(), and discard_last_procsub_child().
old_cont
SigHandler* old_cont = (SigHandler *)SIG_DFL static
Definition at line 336 of file jobs.c.
Referenced by sigcont_sighandler(), and sigstop_sighandler().
old_sigint_handler
SigHandler* old_sigint_handler = INVALID_SIGNAL_HANDLER static
Definition at line 2719 of file jobs.c.
Referenced by restore_sigint_handler(), set_job_status_and_cleanup(), and wait_for().
old_tstp
SigHandler* old_tstp static
Definition at line 335 of file jobs.c.
Referenced by initialize_job_signals(), rl_clear_signals(), rl_set_signals(), and sigstop_sighandler().
old_ttin
SigHandler * old_ttin static
Definition at line 335 of file jobs.c.
Referenced by initialize_job_signals(), rl_clear_signals(), rl_set_signals(), and sigstop_sighandler().
old_ttou
SigHandler * old_ttou static
Definition at line 335 of file jobs.c.
Referenced by initialize_job_signals(), notify_of_job_status(), rl_clear_signals(), rl_set_signals(), and sigstop_sighandler().
original_pgrp
pid_t original_pgrp = NO_PID
Definition at line 200 of file jobs.c.
Referenced by end_job_control(), execute_in_subshell(), and initialize_job_control().
original_signals
SigHandler** original_signals extern
Definition at line 98 of file trap.c.
Referenced by get_original_signal(), initialize_traps(), reset_signal(), restore_default_signal(), restore_signal(), set_original_signal(), set_signal(), set_signal_hard_ignored(), set_signal_ignored(), and trap_handler().
pidstat_table
ps_index_t pidstat_table[PIDSTAT_TABLE_SZ]
Definition at line 177 of file jobs.c.
Referenced by bgp_resize(), and pshash_getbucket().
pipeline_pgrp
pid_t pipeline_pgrp = (pid_t)0
Definition at line 203 of file jobs.c.
Referenced by command_substitute(), make_child(), run_debug_trap(), set_job_control(), start_job(), start_pipeline(), stop_pipeline(), and terminate_current_pipeline().
procsubs
struct procchain procsubs = { 0, 0, 0 }
Definition at line 177 of file jobs.c.
Referenced by find_pipeline().
queue_sigchld
int queue_sigchld static
Definition at line 318 of file jobs.c.
Referenced by notify_of_job_status(), sigchld_handler(), wait_for(), wait_sigint_cleanup(), and waitchld().
retcode_name_buffer
char retcode_name_buffer[64] static
Definition at line 348 of file jobs.c.
Referenced by j_strsignal(), and printable_job_status().
running_in_background
int running_in_background = 0
Definition at line 225 of file jobs.c.
Referenced by initialize_job_control(), make_child(), maybe_give_terminal_to(), set_job_control(), stop_pipeline(), and wait_for().
saved_already_making_children
int saved_already_making_children static
Definition at line 340 of file jobs.c.
Referenced by restore_pipeline(), and save_pipeline().
saved_pipeline
struct pipeline_saver* saved_pipeline static
Definition at line 339 of file jobs.c.
Referenced by find_pipeline(), restore_pipeline(), and save_pipeline().
shell_pgrp
pid_t shell_pgrp = NO_PID
Definition at line 194 of file jobs.c.
Referenced by command_substitute(), end_job_control(), hush_main(), initialize_job_control(), kill_pid(), make_child(), programming_error(), set_job_control(), sigstop_sighandler(), start_job(), start_pipeline(), stop_pipeline(), terminate_current_pipeline(), throw_to_top_level(), and wait_for().
shell_tty
int shell_tty = -1
Definition at line 191 of file jobs.c.
Referenced by give_terminal_to(), initialize_job_control(), maybe_give_terminal_to(), restart_job_control(), and set_job_control().
shell_tty_info
TTYSTRUCT shell_tty_info static
Definition at line 2416 of file jobs.c.
Referenced by get_tty_state(), set_new_line_discipline(), set_tty_state(), and start_job().
sigchld
int sigchld static
Definition at line 317 of file jobs.c.
Referenced by sigchld_handler(), and waitchld().
subst_assign_varlist
WORD_LIST* subst_assign_varlist extern
Definition at line 177 of file subst.c.
Referenced by run_sigchld_trap().
terminal_pgrp
pid_t terminal_pgrp = NO_PID
Definition at line 197 of file jobs.c.
Referenced by end_job_control(), give_terminal_to(), initialize_job_control(), maybe_give_terminal_to(), and set_job_control().
the_pipeline
PROCESS* the_pipeline = (PROCESS *)NULL
Definition at line 219 of file jobs.c.
Referenced by add_process(), cleanup_the_pipeline(), find_pipeline(), make_child(), restore_pipeline(), run_sigchld_trap(), save_pipeline(), start_pipeline(), and stop_pipeline().
wait_sigint_received
int wait_sigint_received static
Definition at line 2721 of file jobs.c.
Referenced by set_job_status_and_cleanup(), wait_for(), wait_sigint_handler(), and waitchld().
waiting_for_child
int waiting_for_child
Definition at line 2724 of file jobs.c.
Referenced by restore_sigint_handler(), wait_for(), wait_sigint_cleanup(), and wait_sigint_handler().
zerojs
struct jobstats zerojs = { -1L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NO_JOB, NO_JOB, 0, 0 } static
Definition at line 172 of file jobs.c.
Referenced by init_job_stats().