Fennix Userspace: Userspace/apps/base/bash/lib/sh/oslib.c File Reference
oslib.c File Reference
#include <config.h>
#include <bashtypes.h>
#include <posixstat.h>
#include <filecntl.h>
#include <bashansi.h>
#include <signal.h>
#include <stdio.h>
#include <errno.h>
#include <chartypes.h>
#include <shell.h>
Macros
#define DEFAULT_MAXGROUPS 64
Functions
char * strchr (char *string, int c)
char * strrchr (char *string, int c)
int dup2 (int fd1, int fd2)
int getdtablesize ()
void bcopy (void *s, void *d, size_t n)
void bzero (void *s, size_t n)
int gethostname (char *name, size_t namelen)
int killpg (pid_t pgrp, int sig)
int getmaxgroups ()
long getmaxchild ()
Variables
int errno
Macro Definition Documentation
DEFAULT_MAXGROUPS
#define DEFAULT_MAXGROUPS 64
Definition at line 250 of file oslib.c.
Function Documentation
bcopy()
void bcopy (void * s, void * d, size_t n)
Definition at line 169 of file oslib.c.
 {
   FASTCOPY (s, d, n);
 }
References FASTCOPY, n, and s.
bzero()
void bzero (void * s, size_t n)
Definition at line 182 of file oslib.c.
 {
   register int i;
   register char *r;
   for (i = 0, r = s; i < n; i++)
     *r++ = '\0';
 }
References i, n, and s.
Referenced by init_signames().
dup2()
int dup2 (int fd1, int fd2)
Definition at line 88 of file oslib.c.
 {
   int saved_errno, r;
   /* If FD1 is not a valid file descriptor, then return immediately with
      an error. */
   if (fcntl (fd1, F_GETFL, 0) == -1)
     return (-1);
   if (fd2 < 0 || fd2 >= getdtablesize ())
     {
       errno = EBADF;
       return (-1);
     }
   if (fd1 == fd2)
     return (0);
   saved_errno = errno;
   (void) close (fd2);
   r = fcntl (fd1, F_DUPFD, fd2);
   if (r >= 0)
     errno = saved_errno;
   else
     if (errno == EINVAL)
       errno = EBADF;
   /* Force the new file descriptor to remain open across exec () calls. */
   SET_OPEN_ON_EXEC (fd2);
   return (r);
 }
References close(), EBADF, EINVAL, errno, F_DUPFD, F_GETFL, fcntl(), getdtablesize(), saved_errno, and SET_OPEN_ON_EXEC.
Referenced by async_redirect_stdin(), bb_daemonize_or_rexec(), command_substitute(), console_init(), cttyhack_main(), custom(), daemon(), do_piping(), do_redirection_internal(), do_wordexp(), doexec(), dup2_or_raise(), evalpipe(), exec_conf(), login_tty(), main(), move_to_high_fd(), nohup_main(), open_shell_script(), open_stdio_to_tty(), restore_stdin(), runsvdir_main(), and xdup2().
getdtablesize()
int getdtablesize (void)
Definition at line 146 of file oslib.c.
 {
 #  if defined (_POSIX_VERSION) && defined (HAVE_SYSCONF) && defined (_SC_OPEN_MAX)
   return (sysconf(_SC_OPEN_MAX));   /* Posix systems use sysconf */
 #  else /* ! (_POSIX_VERSION && HAVE_SYSCONF && _SC_OPEN_MAX) */
 #    if defined (ULIMIT_MAXFDS)
   return (ulimit (4, 0L));  /* System V.3 systems use ulimit(4, 0L) */
 #    else /* !ULIMIT_MAXFDS */
 #      if defined (NOFILE)  /* Other systems use NOFILE */
   return (NOFILE);
 #      else /* !NOFILE */
   return (20);          /* XXX - traditional value is 20 */
 #      endif /* !NOFILE */
 #    endif /* !ULIMIT_MAXFDS */
 #  endif /* ! (_POSIX_VERSION && _SC_OPEN_MAX) */
 }
References _SC_OPEN_MAX, L, NOFILE, sysconf(), and ulimit().
Referenced by dup2(), getmaxfd(), main(), and move_to_high_fd().
gethostname()
int gethostname (char * name, size_t namelen)
Definition at line 215 of file oslib.c.
 {
   strncpy (name, "unknown", namelen);
   name[namelen] = '\0';
   return 0;
 }
References namelen, and strncpy().
Referenced by main(), and shell_initialize().
getmaxchild()
long getmaxchild ()
Definition at line 281 of file oslib.c.
 {
   static long maxchild = -1L;
   if (maxchild > 0)
     return maxchild;
 #if defined (HAVE_SYSCONF) && defined (_SC_CHILD_MAX)
   maxchild = sysconf (_SC_CHILD_MAX);
 #else
 #  if defined (CHILD_MAX)
   maxchild = CHILD_MAX;
 #  else
 #    if defined (MAXUPRC)
   maxchild = MAXUPRC;
 #    endif /* MAXUPRC */
 #  endif /* CHILD_MAX */
 #endif /* !HAVE_SYSCONF || !_SC_CHILD_MAX */
   return (maxchild);
 }
References _SC_CHILD_MAX, and sysconf().
Referenced by mark_dead_jobs_as_notified(), and set_maxchild().
getmaxgroups()
int getmaxgroups ()
Definition at line 253 of file oslib.c.
 {
   static int maxgroups = -1;
   if (maxgroups > 0)
     return maxgroups;
 #if defined (HAVE_SYSCONF) && defined (_SC_NGROUPS_MAX)
   maxgroups = sysconf (_SC_NGROUPS_MAX);
 #else
 #  if defined (NGROUPS_MAX)
   maxgroups = NGROUPS_MAX;
 #  else /* !NGROUPS_MAX */
 #    if defined (NGROUPS)
   maxgroups = NGROUPS;
 #    else /* !NGROUPS */
   maxgroups = DEFAULT_MAXGROUPS;
 #    endif /* !NGROUPS */
 #  endif /* !NGROUPS_MAX */
 #endif /* !HAVE_SYSCONF || !SC_NGROUPS_MAX */
   if (maxgroups <= 0)
     maxgroups = DEFAULT_MAXGROUPS;
   return maxgroups;
 }
References _SC_NGROUPS_MAX, DEFAULT_MAXGROUPS, maxgroups, NGROUPS, and sysconf().
Referenced by initialize_group_array().
killpg()
int killpg (pid_t pgrp, int sig)
Definition at line 228 of file oslib.c.
 {
   return (kill (-pgrp, sig));
 }
References kill().
strchr()
char* strchr (char * string, int c)
Definition at line 57 of file oslib.c.
 {
   register char *s;
   for (s = string; s && *s; s++)
     if (*s == c)
       return (s);
   return ((char *) NULL);
 }
References c, NULL, and s.
strrchr()
char* strrchr (char * string, int c)
Definition at line 71 of file oslib.c.
 {
   register char *s, *t;
   for (s = string, t = (char *)NULL; s && *s; s++)
     if (*s == c)
       t = s;
   return (t);
 }
References c, NULL, s, and t.
Variable Documentation
errno
int errno extern
Referenced by dup2().