Fennix: Userspace/apps/base/busybox/coreutils/mv.c File Reference
mv.c File Reference
#include "libbb.h"
#include "libcoreutils/coreutils.h"
Macros
#define OPT_FORCE (1 << 0)
#define OPT_INTERACTIVE (1 << 1)
#define OPT_NOCLOBBER (1 << 2)
#define OPT_DESTNOTDIR (1 << 3)
#define OPT_DESTDIR (1 << 4)
#define OPT_VERBOSE ((1 << 5) * ENABLE_FEATURE_VERBOSE)
Functions
int mv_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPT_DESTDIR
#define OPT_DESTDIR (1 << 4)
OPT_DESTNOTDIR
#define OPT_DESTNOTDIR (1 << 3)
OPT_FORCE
#define OPT_FORCE (1 << 0)
OPT_INTERACTIVE
#define OPT_INTERACTIVE (1 << 1)
OPT_NOCLOBBER
#define OPT_NOCLOBBER (1 << 2)
OPT_VERBOSE
#define OPT_VERBOSE ((1 << 5) * ENABLE_FEATURE_VERBOSE)
Function Documentation
mv_main()
int mv_main (int argc, char ** argv)
Definition at line 43 of file mv.c.
 {
     struct stat statbuf;
     const char *last;
     const char *dest;
     unsigned flags;
     int dest_exists;
     int status = 0;
     int copy_flag = 0;
 #define OPT_FORCE       (1 << 0)
 #define OPT_INTERACTIVE (1 << 1)
 #define OPT_NOCLOBBER   (1 << 2)
 #define OPT_DESTNOTDIR  (1 << 3)
 #define OPT_DESTDIR     (1 << 4)
 #define OPT_VERBOSE     ((1 << 5) * ENABLE_FEATURE_VERBOSE)
     flags = getopt32long(argv, "^"
             "finTt:v"
             "\0"
     /* At least one argument. (Usually two+, but -t DIR can have only one) */
             "-1"
     /* only the final one of -f, -i, -n takes effect */
             ":f-in:i-fn:n-fi"
     /* -t and -T don't mix */
             ":t--T:T--t",
             "interactive\0" No_argument "i"
             "force\0"       No_argument "f"
             "no-clobber\0"  No_argument "n"
             "no-target-directory\0" No_argument "T"
             "target-directory\0" Required_argument "t"
             IF_FEATURE_VERBOSE(
             "verbose\0"     No_argument "v"
             )
             , &last
     );
     argc -= optind;
     argv += optind;
     if (!(flags & OPT_DESTDIR)) {
         last = argv[argc - 1];
         if (argc < 2)
             bb_show_usage();
         if (argc != 2) {
             if (flags & OPT_DESTNOTDIR)
                 bb_show_usage();
             /* "mv A B C... DIR" - target must be dir */
         } else /* argc == 2 */ {
             /* "mv A B" - only case where target can be not a dir */
             dest_exists = cp_mv_stat(last, &statbuf);
             if (dest_exists < 0) { /* error other than ENOENT */
                 return EXIT_FAILURE;
             }
             if (!(dest_exists & 2)) {
                 /* last is not a directory */
                 dest = last;
                 goto DO_MOVE;
             }
             /* last is a directory */
             if (flags & OPT_DESTNOTDIR) {
                 if (stat(argv[0], &statbuf) == 0 && !S_ISDIR(statbuf.st_mode))
                     bb_error_msg_and_die("'%s' is a directory", last);
                 /* "mv -T DIR1 DIR2" is allowed (renames a dir) */
                 dest = last;
                 goto DO_MOVE;
             }
             /* else: fall through into "do { move SRC to DIR/SRC } while" loop */
         }
     }
     /* else: last is DIR from "-t DIR" */
     do {
         dest = concat_path_file(last, bb_get_last_path_component_strip(*argv));
         dest_exists = cp_mv_stat(dest, &statbuf);
         if (dest_exists < 0) {
             goto RET_1;
         }
  DO_MOVE:
         if (dest_exists) {
             if (flags & OPT_NOCLOBBER)
                 goto RET_0;
             if (!(flags & OPT_FORCE)
              && ((access(dest, W_OK) < 0 && isatty(0))
                 || (flags & OPT_INTERACTIVE))
             ) {
                 if (fprintf(stderr, "mv: overwrite '%s'? ", dest) < 0) {
                     goto RET_1;  /* Ouch! fprintf failed! */
                 }
                 if (!bb_ask_y_confirmation()) {
                     goto RET_0;
                 }
             }
         }
         if (rename(*argv, dest) < 0) {
             int source_exists;
             if (errno != EXDEV
              || (source_exists = cp_mv_stat2(*argv, &statbuf, lstat)) < 1
             ) {
                 bb_perror_msg("can't rename '%s'", *argv);
             } else {
                 static const char fmt[] ALIGN1 =
                     "can't overwrite %sdirectory with %sdirectory";
                 if (dest_exists) {
                     if (dest_exists == 3) {
                         if (source_exists != 3) {
                             bb_error_msg(fmt, "", "non-");
                             goto RET_1;
                         }
                     } else {
                         if (source_exists == 3) {
                             bb_error_msg(fmt, "non-", "");
                             goto RET_1;
                         }
                     }
                     if (unlink(dest) < 0) {
                         bb_perror_msg("can't remove '%s'", dest);
                         goto RET_1;
                     }
                 }
                 /* FILEUTILS_RECUR also prevents nasties like
                  * "read from device and write contents to dst"
                  * instead of "create same device node" */
                 copy_flag = FILEUTILS_RECUR | FILEUTILS_PRESERVE_STATUS;
 #if ENABLE_SELINUX
                 copy_flag |= FILEUTILS_PRESERVE_SECURITY_CONTEXT;
 #endif
                 if ((copy_file(*argv, dest, copy_flag) >= 0)
                  && (remove_file(*argv, FILEUTILS_RECUR | FILEUTILS_FORCE) >= 0)
                 ) {
                     goto RET_0;
                 }
             }
  RET_1:
             status = 1;
         }
  RET_0:
         if (flags & OPT_VERBOSE) {
             printf("'%s' -> '%s'\n", *argv, dest);
         }
         if (dest != last) {
             free((void *) dest);
         }
     } while (*++argv && *argv != last);
     return status;
 }
References access(), ALIGN1, argc, argv, bb_ask_y_confirmation(), bb_error_msg(), bb_error_msg_and_die(), bb_get_last_path_component_strip(), bb_perror_msg(), bb_show_usage(), concat_path_file(), copy_file(), cp_mv_stat(), cp_mv_stat2(), errno, EXDEV, EXIT_FAILURE, FILEUTILS_FORCE, FILEUTILS_PRESERVE_STATUS, FILEUTILS_RECUR, flags, fprintf(), free, getopt32long, isatty(), last, lstat, No_argument, OPT_DESTDIR, OPT_DESTNOTDIR, OPT_FORCE, OPT_INTERACTIVE, OPT_NOCLOBBER, OPT_VERBOSE, optind, printf, remove_file(), rename(), Required_argument, S_ISDIR, stat::st_mode, stat(), status, stderr, unlink(), and W_OK.