Fennix: Userspace/mlibc/sysdeps/aero/generic/aero.cpp File Reference
aero.cpp File Reference
#include <abi-bits/pid_t.h>
#include <aero/syscall.h>
#include <bits/ensure.h>
#include <errno.h>
#include <mlibc/all-sysdeps.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/thread-entry.hpp>
#include <stddef.h>
#include <frg/vector.hpp>
#include <mlibc/allocator.hpp>
Data Structures
struct Slice
Namespaces
mlibc
Macros
#define ARCH_SET_GS 0x1001
#define ARCH_SET_FS 0x1002
#define ARCH_GET_FS 0x1003
#define ARCH_GET_GS 0x1004
Functions
static frg::vector< Slice, MemoryAllocator > create_slice (char *const arg[])
int mlibc::sys_uname (struct utsname *buf)
int mlibc::sys_futex_wait (int *pointer, int expected, const struct timespec *time)
int mlibc::sys_futex_wake (int *pointer)
int mlibc::sys_tcb_set (void *pointer)
int mlibc::sys_vm_map (void *hint, size_t size, int prot, int flags, int fd, off_t offset, void **window)
int mlibc::sys_vm_unmap (void *pointer, size_t size)
int mlibc::sys_vm_protect (void *pointer, size_t size, int prot)
int mlibc::sys_anon_allocate (size_t size, void **pointer)
int mlibc::sys_anon_free (void *pointer, size_t size)
void mlibc::sys_libc_panic ()
void mlibc::sys_libc_log (const char *message)
void mlibc::sys_exit (int status)
pid_t mlibc::sys_getpid ()
pid_t mlibc::sys_getppid ()
int mlibc::sys_kill (int, int)
pid_t mlibc::sys_getpgid (pid_t pid, pid_t *pgid)
int mlibc::sys_clock_get (int clock, time_t *secs, long *nanos)
int mlibc::sys_getcwd (char *buffer, size_t size)
int mlibc::sys_chdir (const char *path)
int mlibc::sys_gethostname (char *buffer, size_t bufsize)
int mlibc::sys_sleep (time_t *secs, long *nanos)
uid_t mlibc::sys_getuid ()
uid_t mlibc::sys_geteuid ()
int mlibc::sys_setsid (pid_t *sid)
int mlibc::sys_seteuid (uid_t euid)
gid_t mlibc::sys_getegid ()
int mlibc::sys_setgid (gid_t gid)
int mlibc::sys_setegid (gid_t egid)
void mlibc::sys_yield ()
int mlibc::sys_clone (void *tcb, pid_t *pid_out, void *stack)
void mlibc::sys_thread_exit ()
mlibc::if (result< 0)
int mlibc::sys_fork (pid_t *child)
int mlibc::sys_execve (const char *path, char *const argv[], char *const envp[])
Variables
void int * mlibc::status
void int int mlibc::flags
void int int struct rusage * mlibc::ru
void int int struct rusage pid_t * mlibc::ret_pid
mlibc::return
Data Structure Documentation
Slice
struct Slice
Definition at line 18 of file aero.cpp.
Data Fields
uint64_t len
void * ptr
Macro Definition Documentation
ARCH_GET_FS
#define ARCH_GET_FS 0x1003
Definition at line 15 of file aero.cpp.
ARCH_GET_GS
#define ARCH_GET_GS 0x1004
Definition at line 16 of file aero.cpp.
ARCH_SET_FS
#define ARCH_SET_FS 0x1002
Definition at line 14 of file aero.cpp.
ARCH_SET_GS
#define ARCH_SET_GS 0x1001
Definition at line 13 of file aero.cpp.
Function Documentation
create_slice()
static frg::vector<Slice, MemoryAllocator> create_slice (char *const arg[]) static
Helper function to construct a slice vector from the provided argument array. A slice basically consists of a pointer to the data and the length of it.
Examples
auto slice = create_slice({ "hello", "world" });
The slice will look like the following:
vector<Slice>(
    Slice { .ptr: hello_ptr, .size: hello_size },
    Slice { .ptr: world_ptr, .size: world_size }
)
Definition at line 40 of file aero.cpp.
{
     if (arg == nullptr) {
         return frg::vector<Slice, MemoryAllocator>{getAllocator()};
     }
     // Find out the length of arg:
     size_t len = 0;
     while (arg[len] != nullptr) {
         len += 1;
     }
     frg::vector<Slice, MemoryAllocator> params{getAllocator()};
     params.resize(len);
     // Construct the slice vector:
     for (size_t i = 0; i < len; ++i) {
         params[i].ptr = (void *)arg[i];
         params[i].len = strlen(arg[i]);
     }
     return params;
 }
References arg, getAllocator(), i, len, params, and strlen().
Referenced by mlibc::sys_execve().