Fennix: Userspace/musl/src/stdio/perror.c File Reference
perror.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include "stdio_impl.h"
Functions
void perror (const char *msg)
Function Documentation
perror()
void perror (const char * msg)
Definition at line 6 of file perror.c.
 {
     FILE *f = stderr;
     char *errstr = strerror(errno);
     FLOCK(f);
     /* Save stderr's orientation and encoding rule, since perror is not
      * permitted to change them. */
     void *old_locale = f->locale;
     int old_mode = f->mode;
     if (msg && *msg) {
         fwrite(msg, strlen(msg), 1, f);
         fputc(':', f);
         fputc(' ', f);
     }
     fwrite(errstr, strlen(errstr), 1, f);
     fputc('\n', f);
     f->mode = old_mode;
     f->locale = old_locale;
     FUNLOCK(f);
 }
References errno, f, FLOCK, fputc(), fputs(), FUNLOCK, fwrite(), stderr, strerror(), and strlen.
Referenced by create_directory(), create_file(), ExecuteCommand(), main(), ptmx_test(), test_brk(), test_dirent(), test_execve_fork(), test_file(), test_passwd(), test_ptmx(), test_stat(), test_stdio(), test_time(), test_watch_directory(), test_watch_file(), and vwarn().