Fennix Userspace: Userspace/apps/base/bash/lib/readline/funmap.c File Reference
funmap.c File Reference
#include <stdio.h>
#include "ansi_stdlib.h"
#include "rlconf.h"
#include "readline.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
Typedefs
typedef int QSFUNC()
Functions
int _rl_qsort_string_compare (char **, char **)
int rl_add_funmap_entry (const char *name, rl_command_func_t *function)
void rl_initialize_funmap (void)
const char ** rl_funmap_names (void)
Variables
FUNMAP ** funmap
static int funmap_size
static int funmap_entry
int funmap_program_specific_entry_start
static const FUNMAP default_funmap []
static int funmap_initialized
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file funmap.c.
Typedef Documentation
QSFUNC
typedef int QSFUNC()
Definition at line 46 of file funmap.c.
Function Documentation
_rl_qsort_string_compare()
int _rl_qsort_string_compare (char ** s1, char ** s2)
Definition at line 422 of file util.c.
 {
 #if defined (HAVE_STRCOLL)
   return (strcoll (*s1, *s2));
 #else
   int result;
   result = **s1 - **s2;
   if (result == 0)
     result = strcmp (*s1, *s2);
   return result;
 #endif
 }
References s1, s2, strcmp, and strcoll().
Referenced by compute_lcd_of_matches(), remove_duplicate_matches(), rl_display_match_list(), and rl_funmap_names().
rl_add_funmap_entry()
int rl_add_funmap_entry (const char * name, rl_command_func_t * function)
Definition at line 213 of file funmap.c.
 {
   if (funmap_entry + 2 >= funmap_size)
     {
       funmap_size += 64;
       funmap = (FUNMAP **)xrealloc (funmap, funmap_size * sizeof (FUNMAP *));
     }
   funmap[funmap_entry] = (FUNMAP *)xmalloc (sizeof (FUNMAP));
   funmap[funmap_entry]->name = name;
   funmap[funmap_entry]->function = function;
   funmap[++funmap_entry] = (FUNMAP *)NULL;
   return funmap_entry;
 }
References _funmap::function, funmap, funmap_entry, funmap_size, _funmap::name, NULL, xmalloc, and xrealloc.
Referenced by rl_add_defun(), and rl_initialize_funmap().
rl_funmap_names()
const char** rl_funmap_names (void)
Definition at line 251 of file funmap.c.
 {
   const char **result;
   int result_size, result_index;
   /* Make sure that the function map has been initialized. */
   rl_initialize_funmap ();
   for (result_index = result_size = 0, result = (const char **)NULL; funmap[result_index]; result_index++)
     {
       if (result_index + 2 > result_size)
     {
       result_size += 20;
       result = (const char **)xrealloc (result, result_size * sizeof (char *));
     }
       result[result_index] = funmap[result_index]->name;
       result[result_index + 1] = (char *)NULL;
     }
   qsort (result, result_index, sizeof (char *), (QSFUNC *)_rl_qsort_string_compare);
   return (result);
 }
References _rl_qsort_string_compare(), funmap, _funmap::name, NULL, qsort(), rl_initialize_funmap(), and xrealloc.
Referenced by rl_function_dumper(), and rl_list_funmap_names().
rl_initialize_funmap()
void rl_initialize_funmap (void)
Definition at line 233 of file funmap.c.
 {
   register int i;
   if (funmap_initialized)
     return;
   for (i = 0; default_funmap[i].name; i++)
     rl_add_funmap_entry (default_funmap[i].name, default_funmap[i].function);
   funmap_initialized = 1;
   funmap_program_specific_entry_start = i;
 }
References default_funmap, funmap_initialized, funmap_program_specific_entry_start, i, _funmap::name, and rl_add_funmap_entry().
Referenced by readline_initialize_everything(), rl_funmap_names(), and rl_named_function().
Variable Documentation
default_funmap
const FUNMAP default_funmap[] static
Definition at line 59 of file funmap.c.
Referenced by rl_initialize_funmap().
funmap
FUNMAP** funmap
Definition at line 51 of file funmap.c.
Referenced by rl_add_funmap_entry(), rl_funmap_names(), and rl_named_function().
funmap_entry
int funmap_entry static
Definition at line 53 of file funmap.c.
Referenced by rl_add_funmap_entry().
funmap_initialized
int funmap_initialized static
Definition at line 229 of file funmap.c.
Referenced by rl_initialize_funmap().
funmap_program_specific_entry_start
int funmap_program_specific_entry_start
Definition at line 57 of file funmap.c.
Referenced by rl_initialize_funmap().
funmap_size
int funmap_size static
Definition at line 52 of file funmap.c.
Referenced by rl_add_funmap_entry().