Fennix: Userspace/musl/src/math/exp2.c File Reference
exp2.c File Reference
#include <math.h>
#include <stdint.h>
#include "libm.h"
#include "exp_data.h"
Macros
#define N (1 << EXP_TABLE_BITS)
#define Shift __exp_data.exp2_shift
#define T __exp_data.tab
#define C1 __exp_data.exp2_poly[0]
#define C2 __exp_data.exp2_poly[1]
#define C3 __exp_data.exp2_poly[2]
#define C4 __exp_data.exp2_poly[3]
#define C5 __exp_data.exp2_poly[4]
Functions
static double specialcase (double_t tmp, uint64_t sbits, uint64_t ki)
static uint32_t top12 (double x)
double exp2 (double x)
Macro Definition Documentation
C1
#define C1 __exp_data.exp2_poly[0]
Definition at line 16 of file exp2.c.
C2
#define C2 __exp_data.exp2_poly[1]
Definition at line 17 of file exp2.c.
C3
#define C3 __exp_data.exp2_poly[2]
Definition at line 18 of file exp2.c.
C4
#define C4 __exp_data.exp2_poly[3]
Definition at line 19 of file exp2.c.
C5
#define C5 __exp_data.exp2_poly[4]
Definition at line 20 of file exp2.c.
N
#define N (1 << EXP_TABLE_BITS)
Definition at line 13 of file exp2.c.
Shift
#define Shift __exp_data.exp2_shift
Definition at line 14 of file exp2.c.
T
#define T __exp_data.tab
Definition at line 15 of file exp2.c.
Function Documentation
exp2()
double exp2 (double x)
Definition at line 70 of file exp2.c.
 {
     uint32_t abstop;
     uint64_t ki, idx, top, sbits;
     double_t kd, r, r2, scale, tail, tmp;
     abstop = top12(x) & 0x7ff;
     if (predict_false(abstop - top12(0x1p-54) >= top12(512.0) - top12(0x1p-54))) {
         if (abstop - top12(0x1p-54) >= 0x80000000)
             /* Avoid spurious underflow for tiny x.  */
             /* Note: 0 is common input.  */
             return WANT_ROUNDING ? 1.0 + x : 1.0;
         if (abstop >= top12(1024.0)) {
             if (asuint64(x) == asuint64(-INFINITY))
                 return 0.0;
             if (abstop >= top12(INFINITY))
                 return 1.0 + x;
             if (!(asuint64(x) >> 63))
                 return __math_oflow(0);
             else if (asuint64(x) >= asuint64(-1075.0))
                 return __math_uflow(0);
         }
         if (2 * asuint64(x) > 2 * asuint64(928.0))
             /* Large x is special cased below.  */
             abstop = 0;
     }
     /* exp2(x) = 2^(k/N) * 2^r, with 2^r in [2^(-1/2N),2^(1/2N)].  */
     /* x = k/N + r, with int k and r in [-1/2N, 1/2N].  */
     kd = eval_as_double(x + Shift);
     ki = asuint64(kd); /* k.  */
     kd -= Shift; /* k/N for int k.  */
     r = x - kd;
     /* 2^(k/N) ~= scale * (1 + tail).  */
     idx = 2 * (ki % N);
     top = ki << (52 - EXP_TABLE_BITS);
     tail = asdouble(T[idx]);
     /* This is only a valid scale when -1023*N < k < 1024*N.  */
     sbits = T[idx + 1] + top;
     /* exp2(x) = 2^(k/N) * 2^r ~= scale + scale * (tail + 2^r - 1).  */
     /* Evaluation is optimized assuming superscalar pipelined execution.  */
     r2 = r * r;
     /* Without fma the worst case error is 0.5/N ulp larger.  */
     /* Worst case error is less than 0.5+0.86/N+(abs poly error * 2^53) ulp.  */
     tmp = tail + r * C1 + r2 * (C2 + r * C3) + r2 * r2 * (C4 + r * C5);
     if (predict_false(abstop == 0))
         return specialcase(tmp, sbits, ki);
     scale = asdouble(sbits);
     /* Note: tmp == 0 or |tmp| > 2^-65 and scale > 2^-928, so there
        is no spurious underflow here even without fma.  */
     return eval_as_double(scale + scale * tmp);
 }
References __math_oflow(), __math_uflow(), asdouble, asuint64, C1, C2, C3, C4, C5, eval_as_double(), EXP_TABLE_BITS, idx, INFINITY, N, predict_false, r2, scale, Shift, specialcase(), T, tail, top, top12(), WANT_ROUNDING, and x.
specialcase()
static double specialcase (double_t tmp, uint64_t sbits, uint64_t ki) inline static
Definition at line 29 of file exp2.c.
 {
     double_t scale, y;
     if ((ki & 0x80000000) == 0) {
         /* k > 0, the exponent of scale might have overflowed by 1.  */
         sbits -= 1ull << 52;
         scale = asdouble(sbits);
         y = 2 * (scale + scale * tmp);
         return eval_as_double(y);
     }
     /* k < 0, need special care in the subnormal range.  */
     sbits += 1022ull << 52;
     scale = asdouble(sbits);
     y = scale + scale * tmp;
     if (y < 1.0) {
         /* Round y to the right precision before scaling it into the subnormal
            range to avoid double rounding that can cause 0.5+E/2 ulp error where
            E is the worst-case ulp error outside the subnormal range.  So this
            is only useful if the goal is better than 1 ulp worst-case error.  */
         double_t hi, lo;
         lo = scale - y + scale * tmp;
         hi = 1.0 + y;
         lo = 1.0 - hi + y + lo;
         y = eval_as_double(hi + lo) - 1.0;
         /* Avoid -0.0 with downward rounding.  */
         if (WANT_ROUNDING && y == 0.0)
             y = 0.0;
         /* The underflow exception needs to be signaled explicitly.  */
         fp_force_eval(fp_barrier(0x1p-1022) * 0x1p-1022);
     }
     y = 0x1p-1022 * y;
     return eval_as_double(y);
 }
References asdouble, eval_as_double(), fp_barrier, fp_force_eval, scale, WANT_ROUNDING, and y.
Referenced by exp2().
top12()
static uint32_t top12 (double x) inline static
Definition at line 65 of file exp2.c.
 {
     return asuint64(x) >> 52;
 }
References asuint64, and x.
Referenced by exp2().