Fennix Userspace: Userspace/libc/src/InitArray.c File Reference
InitArray.c File Reference
Typedefs
typedef void(* fct) (void)
Functions
void __libc_init_array (void)
void __libc_fini_array (void)
Variables
fct __init_array_start [0]
fct __init_array_end [0]
fct __fini_array_start [0]
fct __fini_array_end [0]
Typedef Documentation
fct
typedef void(* fct) (void)
Definition at line 8 of file InitArray.c.
Function Documentation
__libc_fini_array()
void __libc_fini_array (void)
Definition at line 18 of file InitArray.c.
 {
     for (fct *func = __fini_array_start; func != __fini_array_end; func++)
         (*func)();
 }
References __fini_array_end, and __fini_array_start.
Referenced by _exit().
__libc_init_array()
void __libc_init_array (void)
Definition at line 12 of file InitArray.c.
 {
     for (fct *func = __init_array_start; func != __init_array_end; func++)
         (*func)();
 }
References __init_array_end, and __init_array_start.
Referenced by __libc_init().
Variable Documentation
__fini_array_end
fct __fini_array_end[0]
Definition at line 10 of file InitArray.c.
Referenced by __libc_fini_array().
__fini_array_start
fct __fini_array_start[0] (void) extern
Definition at line 162 of file dynlink.c.
Referenced by __libc_fini_array().
__init_array_end
fct __init_array_end[0] (void)
Definition at line 9 of file InitArray.c.
Referenced by __libc_init_array().
__init_array_start
fct __init_array_start[0] (void) extern
Definition at line 162 of file dynlink.c.
Referenced by __libc_init_array().