Fennix: Userspace/apps/base/bash/examples/loadables/dsv.c File Reference
dsv.c File Reference
#include <config.h>
#include "bashansi.h"
#include <stdio.h>
#include "loadables.h"
Macros
#define DSV_ARRAY_DEFAULT "DSV"
#define NQUOTE 0
#define DQUOTE 1
#define SQUOTE 2
#define F_SHELLQUOTE 0x01
#define F_GREEDY 0x02
#define F_PRESERVE 0x04
Functions
static int dsvsplit (SHELL_VAR *dsv, char *line, char *dstring, int flags)
int dsv_builtin (WORD_LIST *list)
int dsv_builtin_load (char *name)
void dsv_builtin_unload (char *name)
Variables
char * dsv_doc []
struct builtin dsv_struct
Macro Definition Documentation
DQUOTE
#define DQUOTE 1
Definition at line 36 of file dsv.c.
DSV_ARRAY_DEFAULT
#define DSV_ARRAY_DEFAULT "DSV"
Definition at line 33 of file dsv.c.
F_GREEDY
#define F_GREEDY 0x02
Definition at line 40 of file dsv.c.
F_PRESERVE
#define F_PRESERVE 0x04
Definition at line 41 of file dsv.c.
F_SHELLQUOTE
#define F_SHELLQUOTE 0x01
Definition at line 39 of file dsv.c.
NQUOTE
#define NQUOTE 0
Definition at line 35 of file dsv.c.
SQUOTE
#define SQUOTE 2
Definition at line 37 of file dsv.c.
Function Documentation
dsv_builtin()
int dsv_builtin (WORD_LIST * list)
Definition at line 166 of file dsv.c.
 {
   int opt, rval, flags;
   char *array_name, *dsvstring, *delims;
   SHELL_VAR *v;
   array_name = 0;
   rval = EXECUTION_SUCCESS;
   delims = ",";
   flags = 0;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "a:d:Sgp")) != -1)
     {
       switch (opt)
     {
     case 'a':
       array_name = list_optarg;
       break;
     case 'd':
       delims = list_optarg;
       break;
     case 'S':
       flags |= F_SHELLQUOTE;
       break;
     case 'g':
       flags |= F_GREEDY;
       break;
     case 'p':
       flags |= F_PRESERVE;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (array_name == 0)
     array_name = DSV_ARRAY_DEFAULT;
   if (legal_identifier (array_name) == 0)
     {
       sh_invalidid (array_name);
       return (EXECUTION_FAILURE);
     }
   if (list == 0)
     {
       builtin_error ("dsv string argument required");
       return (EX_USAGE);
     }
   v = find_or_make_array_variable (array_name, 1);
   if (v == 0 || readonly_p (v) || noassign_p (v))
     {
       if (v && readonly_p (v))
     err_readonly (array_name);
       return (EXECUTION_FAILURE);
     }
   else if (array_p (v) == 0)
     {
       builtin_error ("%s: not an indexed array", array_name);
       return (EXECUTION_FAILURE);
     }
   if (invisible_p (v))
     VUNSETATTR (v, att_invisible);
   array_flush (array_cell (v));
   dsvstring = list->word->word;
   if (dsvstring == 0 || *dsvstring == 0)
     return (EXECUTION_SUCCESS);
   opt = dsvsplit (v, dsvstring, delims, flags);
   /* Maybe do something with OPT here, it's the number of fields */
   return (rval);
 }
References array_cell, array_p, att_invisible, builtin_error(), builtin_usage(), CASE_HELPOPT, DSV_ARRAY_DEFAULT, dsvsplit(), err_readonly(), EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, F_GREEDY, F_PRESERVE, F_SHELLQUOTE, flags, internal_getopt(), invisible_p, legal_identifier(), list(), list_optarg, loptend, noassign_p, opt, readonly_p, reset_internal_getopt(), sh_invalidid(), and VUNSETATTR.
dsv_builtin_load()
int dsv_builtin_load (char * name)
Definition at line 252 of file dsv.c.
 {
   return (1);
 }
dsv_builtin_unload()
void dsv_builtin_unload (char * name)
Definition at line 260 of file dsv.c.
 {
 }
dsvsplit()
static int dsvsplit (SHELL_VAR * dsv, char * line, char * dstring, int flags) static
Definition at line 55 of file dsv.c.
 {
   arrayind_t ind;
   char *field, *prev, *buf, *xbuf;
   int delim, qstate;
   int b, rval;
   xbuf = 0;
   ind = 0;
   field = prev = line;
   /* If we want a greedy split, consume leading instances of *DSTRING */
   if (flags & F_GREEDY)
     {
       while (*prev == *dstring)
     prev++;
       field = prev;
     }
   do
     {
       if (*prev == '"')
     {
       if (xbuf == 0)
         xbuf = xmalloc (strlen (prev) + 1);
       buf = xbuf;
       b = 0;
       if (flags & F_PRESERVE)
         buf[b++] = *prev;
       qstate = DQUOTE;
       for (field = ++prev; *field; field++)
         {
           if (qstate == DQUOTE && *field == '"' && field[1] == '"' && (flags & F_SHELLQUOTE) == 0)
         buf[b++] = *field++;    /* skip double quote */
           else if (qstate == DQUOTE && (flags & F_SHELLQUOTE) && *field == '\\' && strchr (slashify_in_quotes, field[1]) != 0)
         buf[b++] = *++field;    /* backslash quoted double quote */
           else if (qstate == DQUOTE && *field == '"')
         {
           qstate = NQUOTE;
           if (flags & F_PRESERVE)
             buf[b++] = *field;
         }
           else if (qstate == NQUOTE && *field == *dstring)
         break;
           else
         /* This copies any text between a closing double quote and the
            delimiter. If you want to change that, make sure to do the
            copy only if qstate == DQUOTE. */
         buf[b++] = *field;
         }
       buf[b] = '\0';
     }
       else if ((flags & F_SHELLQUOTE) && *prev == '\'')
     {
       if (xbuf == 0)
         xbuf = xmalloc (strlen (prev) + 1);
       buf = xbuf;
       b = 0;
       if (flags & F_PRESERVE)
         buf[b++] = *prev;
       qstate = SQUOTE;
       for (field = ++prev; *field; field++)
         {
           if (qstate == SQUOTE && *field == '\'')
         {
           qstate = NQUOTE;
           if (flags & F_PRESERVE)
             buf[b++] = *field;
         }
           else if (qstate == NQUOTE && *field == *dstring)
         break;
           else
         /* This copies any text between a closing single quote and the
            delimiter. If you want to change that, make sure to do the
            copy only if qstate == SQUOTE. */
         buf[b++] = *field;
         }
       buf[b] = '\0';
     }
       else
     {
       buf = prev;
       field = prev + strcspn (prev, dstring);
     }
       delim = *field;
       *field = '\0';
       if ((flags & F_GREEDY) == 0 || buf[0])
     {
       bind_array_element (dsv, ind, buf, 0);
       ind++;
     }
       *field = delim;
       if (delim == *dstring)
     prev = field + 1;
     }
   while (delim == *dstring);
   if (xbuf)
     free (xbuf);
   return (rval = ind);              /* number of fields */
 }
References buf, DQUOTE, F_GREEDY, F_PRESERVE, F_SHELLQUOTE, flags, free, line, NQUOTE, slashify_in_quotes, SQUOTE, strchr(), strcspn(), strlen(), and xmalloc.
Referenced by dsv_builtin().
Variable Documentation
dsv_doc
char* dsv_doc[]
Initial value:
= {
    "Read delimiter-separated fields from STRING.",
    "",
    "Parse STRING, a line of delimiter-separated values, into individual",
    "fields, and store them into the indexed array ARRAYNAME starting at",
    "index 0. The parsing understands and skips over double-quoted strings. ",
    "If ARRAYNAME is not supplied, \"DSV\" is the default array name.",
    "If the delimiter is a comma, the default, this parses comma-",
    "separated values as specified in RFC 4180.",
    "",
    "The -d option specifies the delimiter. The delimiter is the first",
    "character of the DELIMS argument. Specifying a DELIMS argument that",
    "contains more than one character is not supported and will produce",
    "unexpected results. The -S option enables shell-like quoting: double-",
    "quoted strings can contain backslashes preceding special characters,",
    "and the backslash will be removed; and single-quoted strings are",
    "processed as the shell would process them. The -g option enables a",
    "greedy split: sequences of the delimiter are skipped at the beginning",
    "and end of STRING, and consecutive instances of the delimiter in STRING",
    "do not generate empty fields. If the -p option is supplied, dsv leaves",
    "quote characters as part of the generated field; otherwise they are",
    "removed.",
    "",
    "The return value is 0 unless an invalid option is supplied or the ARRAYNAME",
    "argument is invalid or readonly.",
    (char *)NULL
}
Definition at line 265 of file dsv.c.
dsv_struct
struct builtin dsv_struct
Initial value:
= {
    "dsv",
    dsv_builtin,
    BUILTIN_ENABLED,
    dsv_doc,
    "dsv [-a ARRAYNAME] [-d DELIMS] [-Sgp] string",
    0
}
Definition at line 265 of file dsv.c.