Fennix Userspace: Userspace/apps/base/busybox/libbb/get_shell_name.c File Reference
get_shell_name.c File Reference
#include "libbb.h"
Functions
const char *FAST_FUNC get_shell_name (void)
Function Documentation
get_shell_name()
const char* FAST_FUNC get_shell_name (void)
Definition at line 11 of file get_shell_name.c.
 {
     struct passwd *pw;
     char *shell;
     shell = getenv("SHELL");
     if (shell && shell[0])
         return shell;
     pw = getpwuid(getuid());
     if (pw && pw->pw_shell && pw->pw_shell[0])
         return pw->pw_shell;
     return DEFAULT_SHELL;
 }
References DEFAULT_SHELL, getenv, getpwuid, getuid, pw, and passwd::pw_shell.
Referenced by adduser_main(), chroot_main(), crond_main(), flock_main(), ifupdown_main(), openvt_main(), processorstart(), script_main(), start_shell_in_child(), and tar_main().