Fennix: Userspace/apps/base/busybox/libbb/correct_password.c File Reference
correct_password.c File Reference
#include "libbb.h"
Macros
#define SHADOW_BUFSIZE 256
#define get_passwd(pw, buffer) get_passwd(pw)
Functions
static const char * get_passwd (const struct passwd *pw, char buffer[SHADOW_BUFSIZE])
int FAST_FUNC check_password (const struct passwd *pw, const char *plaintext)
int FAST_FUNC ask_and_check_password_extended (const struct passwd *pw, int timeout, const char *prompt)
int FAST_FUNC ask_and_check_password (const struct passwd *pw)
Macro Definition Documentation
get_passwd
#define get_passwd (pw, buffer) get_passwd(pw)
Definition at line 39 of file correct_password.c.
SHADOW_BUFSIZE
#define SHADOW_BUFSIZE 256
Definition at line 32 of file correct_password.c.
Function Documentation
ask_and_check_password()
int FAST_FUNC ask_and_check_password (const struct passwd * pw)
Definition at line 120 of file correct_password.c.
 {
     return ask_and_check_password_extended(pw, 0, "Password: ");
 }
References ask_and_check_password_extended(), and pw.
Referenced by login_main(), su_main(), and vlock_main().
ask_and_check_password_extended()
int FAST_FUNC ask_and_check_password_extended (const struct passwd * pw, int timeout, const char * prompt)
Definition at line 97 of file correct_password.c.
 {
     IF_FEATURE_SHADOWPASSWDS(char buffer[SHADOW_BUFSIZE];)
     char *plaintext;
     const char *pw_pass;
     int r;
     pw_pass = get_passwd(pw, buffer);
     if (!pw_pass[0]) /* empty password field? */
         return CHECKPASS_PW_HAS_EMPTY_PASSWORD;
     plaintext = bb_ask_noecho(STDIN_FILENO, timeout, prompt);
     if (!plaintext) {
         /* EOF (such as ^D) or error (such as ^C) or timeout */
         return -1;
     }
     r = check_password(pw, plaintext);
     nuke_str(plaintext);
     return r;
 }
References bb_ask_noecho(), check_password(), CHECKPASS_PW_HAS_EMPTY_PASSWORD, get_passwd, nuke_str(), prompt, pw, SHADOW_BUFSIZE, STDIN_FILENO, and timeout().
Referenced by ask_and_check_password(), and sulogin_main().
check_password()
int FAST_FUNC check_password (const struct passwd * pw, const char * plaintext)
Definition at line 70 of file correct_password.c.
 {
     IF_FEATURE_SHADOWPASSWDS(char buffer[SHADOW_BUFSIZE];)
     char *encrypted;
     const char *pw_pass;
     int r;
     pw_pass = get_passwd(pw, buffer);
     if (!pw_pass[0]) { /* empty password field? */
         return CHECKPASS_PW_HAS_EMPTY_PASSWORD;
     }
     encrypted = pw_encrypt(plaintext, /*salt:*/ pw_pass, 1);
     r = (strcmp(encrypted, pw_pass) == 0);
     free(encrypted);
     return r;
 }
References CHECKPASS_PW_HAS_EMPTY_PASSWORD, free, get_passwd, pw, pw_encrypt, SHADOW_BUFSIZE, and strcmp.
Referenced by ask_and_check_password_extended(), and ftpd_main().
get_passwd()
static const char* get_passwd (const struct passwd * pw, char buffer[SHADOW_BUFSIZE]) static
Definition at line 41 of file correct_password.c.
 {
     const char *pass;
     if (!pw)
         return "aa"; /* "aa" will never match */
     pass = pw->pw_passwd;
 #if ENABLE_FEATURE_SHADOWPASSWDS
     /* Using _r function to avoid pulling in static buffers */
     if ((pass[0] == 'x' || pass[0] == '*') && !pass[1]) {
         struct spwd spw;
         int r;
         /* getspnam_r may return 0 yet set result to NULL.
          * At least glibc 2.4 does this. Be extra paranoid here. */
         struct spwd *result = NULL;
         r = getspnam_r(pw->pw_name, &spw, buffer, SHADOW_BUFSIZE, &result);
         pass = (r || !result) ? "aa" : result->sp_pwdp;
     }
 #endif
     return pass;
 }
References getspnam_r, NULL, pw, passwd::pw_name, passwd::pw_passwd, SHADOW_BUFSIZE, and spwd::sp_pwdp.