Fennix Userspace: Userspace/apps/base/busybox/scripts/kconfig/util.c File Reference
util.c File Reference
#include <string.h>
#include "lkc.h"
Functions
struct file * file_lookup (const char *name)
int file_write_dep (const char *name)
struct gstr str_new (void)
struct gstr str_assign (const char *s)
void str_free (struct gstr *gs)
void str_append (struct gstr *gs, const char *s)
void str_printf (struct gstr *gs, const char *fmt,...)
const char * str_get (struct gstr *gs)
Function Documentation
file_lookup()
struct file* file_lookup (const char * name)
Definition at line 12 of file util.c.
 {
     struct file *file;
     for (file = file_list; file; file = file->next) {
         if (!strcmp(name, file->name))
             return file;
     }
     file = malloc(sizeof(*file));
     memset(file, 0, sizeof(*file));
     file->name = strdup(name);
     file->next = file_list;
     file_list = file;
     return file;
 }
References file_list, malloc, memset(), file::name, file::next, strcmp, and strdup().
file_write_dep()
int file_write_dep (const char * name)
Definition at line 30 of file util.c.
 {
     struct file *file;
     FILE *out;
     if (!name)
         name = ".kconfig.d";
     out = fopen("..config.tmp", "w");
     if (!out)
         return 1;
     fprintf(out, "deps_config := \\\n");
     for (file = file_list; file; file = file->next) {
         if (file->next)
             fprintf(out, "\t%s \\\n", file->name);
         else
             fprintf(out, "\t%s\n", file->name);
     }
     fprintf(out,
         "\n"
         ".config include/autoconf.h: $(deps_config)\n"
         "\n"
         "include/autoconf.h: .config\n" /* bbox */
         "\n"
         "$(deps_config):\n");
     fclose(out);
     rename("..config.tmp", name);
     return 0;
 }
References fclose(), file_list, fopen(), fprintf(), file::name, file::next, out(), and rename().
Referenced by conf_write().
str_append()
void str_append (struct gstr * gs, const char * s)
Definition at line 88 of file util.c.
 {
     size_t l = strlen(gs->s) + strlen(s) + 1;
     if (l > gs->len) {
         gs->s   = realloc(gs->s, l);
         gs->len = l;
     }
     strcat(gs->s, s);
 }
References l, gstr::len, realloc, s, gstr::s, strcat(), and strlen().
Referenced by expr_print_gstr_helper(), get_prompt_str(), get_relations_str(), show_help(), and str_printf().
str_assign()
struct gstr str_assign (const char * s)
Definition at line 30 of file util.c.
 {
     struct gstr gs;
     gs.s = strdup(s);
     gs.len = strlen(s) + 1;
     return gs;
 }
str_free()
void str_free (struct gstr * gs)
Definition at line 80 of file util.c.
 {
     free(gs->s);
     gs->s = NULL;
     gs->len = 0;
 }
References free, gstr::len, NULL, and gstr::s.
Referenced by search_conf(), and show_help().
str_get()
const char* str_get (struct gstr * gs)
Definition at line 110 of file util.c.
 {
     return gs->s;
 }
References gstr::s.
Referenced by search_conf(), and show_help().
str_new()
struct gstr str_new (void)
Definition at line 30 of file util.c.
 {
     struct gstr gs;
     gs.s = malloc(sizeof(char) * 64);
     gs.len = 16;
     strcpy(gs.s, "\0");
     return gs;
 }
Referenced by show_help().
str_printf()
void str_printf (struct gstr * gs, const char * fmt, ...)
Definition at line 99 of file util.c.
 {
     va_list ap;
     char s[10000]; /* big enough... */
     va_start(ap, fmt);
     vsnprintf(s, sizeof(s), fmt, ap);
     str_append(gs, s);
     va_end(ap);
 }
References ap, s, str_append(), va_end, va_start, and vsnprintf().
Referenced by get_prompt_str(), get_relations_str(), and show_help().