Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/s_sound.h File Reference
s_sound.h File Reference
#include "p_mobj.h"
#include "sounds.h"
Functions
void S_Init (int sfxVolume, int musicVolume)
void S_Shutdown (void)
void S_Start (void)
void S_StartSound (void *origin, int sound_id)
void S_StopSound (mobj_t *origin)
void S_StartMusic (int music_id)
void S_ChangeMusic (int music_id, int looping)
boolean S_MusicPlaying (void)
void S_StopMusic (void)
void S_PauseSound (void)
void S_ResumeSound (void)
void S_UpdateSounds (mobj_t *listener)
void S_SetMusicVolume (int volume)
void S_SetSfxVolume (int volume)
Variables
int snd_channels
Function Documentation
S_ChangeMusic()
void S_ChangeMusic (int music_id, int looping)
Definition at line 601 of file s_sound.c.
 {
     musicinfo_t *music = NULL;
     char namebuf[9];
     void *handle;
     // The Doom IWAD file has two versions of the intro music: d_intro
     // and d_introa.  The latter is used for OPL playback.
     if (musicnum == mus_intro && (snd_musicdevice == SNDDEVICE_ADLIB
                                || snd_musicdevice == SNDDEVICE_SB))
     {
         musicnum = mus_introa;
     }
     if (musicnum <= mus_None || musicnum >= NUMMUSIC)
     {
         I_Error("Bad music number %d", musicnum);
     }
     else
     {
         music = &S_music[musicnum];
     }
     if (mus_playing == music)
     {
         return;
     }
     // shutdown old music
     S_StopMusic();
     // get lumpnum if neccessary
     if (!music->lumpnum)
     {
         M_snprintf(namebuf, sizeof(namebuf), "d_%s", DEH_String(music->name));
         music->lumpnum = W_GetNumForName(namebuf);
     }
     music->data = W_CacheLumpNum(music->lumpnum, PU_STATIC);
     handle = I_RegisterSong(music->data, W_LumpLength(music->lumpnum));
     music->handle = handle;
     I_PlaySong(handle, looping);
     mus_playing = music;
 }
References musicinfo_t::data, DEH_String, musicinfo_t::handle, I_Error(), I_PlaySong(), I_RegisterSong(), musicinfo_t::lumpnum, M_snprintf(), mus_intro, mus_introa, mus_playing, musicinfo_t::name, NULL, NUMMUSIC, PU_STATIC, S_music, S_StopMusic(), snd_musicdevice, SNDDEVICE_ADLIB, SNDDEVICE_SB, W_CacheLumpNum(), W_GetNumForName(), and W_LumpLength().
Referenced by F_StartCast(), F_StartFinale(), S_Start(), S_StartMusic(), ST_Responder(), and WI_Ticker().
S_Init()
void S_Init (int sfxVolume, int musicVolume)
Definition at line 114 of file s_sound.c.
 {
     int i;
     I_PrecacheSounds(S_sfx, NUMSFX);
     S_SetSfxVolume(sfxVolume);
     S_SetMusicVolume(musicVolume);
     // Allocating the internal channels for mixing
     // (the maximum numer of sounds rendered
     // simultaneously) within zone memory.
     channels = Z_Malloc(snd_channels*sizeof(channel_t), PU_STATIC, 0);
     // Free all channels for use
     for (i=0 ; i<snd_channels ; i++)
     {
         channels[i].sfxinfo = 0;
     }
     // no sounds are playing, and they are not mus_paused
     mus_paused = 0;
     // Note that sounds have not been cached (yet).
     for (i=1 ; i<NUMSFX ; i++)
     {
         S_sfx[i].lumpnum = S_sfx[i].usefulness = -1;
     }
     I_AtExit(S_Shutdown, true);
 }
References channels, i, I_AtExit(), I_PrecacheSounds(), sfxinfo_struct::lumpnum, mus_paused, musicVolume, NUMSFX, PU_STATIC, S_SetMusicVolume(), S_SetSfxVolume(), S_sfx, S_Shutdown(), channel_t::sfxinfo, sfxVolume, snd_channels, sfxinfo_struct::usefulness, and Z_Malloc().
Referenced by D_DoomMain().
S_MusicPlaying()
boolean S_MusicPlaying (void)
Definition at line 649 of file s_sound.c.
 {
     return I_MusicIsPlaying();
 }
References I_MusicIsPlaying().
S_PauseSound()
void S_PauseSound (void)
Definition at line 482 of file s_sound.c.
 {
     if (mus_playing && !mus_paused)
     {
         I_PauseSong();
         mus_paused = true;
     }
 }
References I_PauseSong(), mus_paused, and mus_playing.
Referenced by G_Ticker().
S_ResumeSound()
void S_ResumeSound (void)
Definition at line 491 of file s_sound.c.
 {
     if (mus_playing && mus_paused)
     {
         I_ResumeSong();
         mus_paused = false;
     }
 }
References I_ResumeSong(), mus_paused, and mus_playing.
Referenced by G_InitNew(), and G_Ticker().
S_SetMusicVolume()
void S_SetMusicVolume (int volume)
Definition at line 571 of file s_sound.c.
 {
     if (volume < 0 || volume > 127)
     {
         I_Error("Attempt to set music volume at %d",
                 volume);
     }
     I_SetMusicVolume(volume);
 }
References I_Error(), and I_SetMusicVolume().
Referenced by M_MusicVol(), and S_Init().
S_SetSfxVolume()
void S_SetSfxVolume (int volume)
Definition at line 582 of file s_sound.c.
 {
     if (volume < 0 || volume > 127)
     {
         I_Error("Attempt to set sfx volume at %d", volume);
     }
     snd_SfxVolume = volume;
 }
References I_Error(), and snd_SfxVolume.
Referenced by M_SfxVol(), and S_Init().
S_Shutdown()
void S_Shutdown (void)
Definition at line 146 of file s_sound.c.
 {
     I_ShutdownSound();
     I_ShutdownMusic();
 }
References I_ShutdownMusic(), and I_ShutdownSound().
Referenced by S_Init().
S_Start()
void S_Start (void)
Definition at line 191 of file s_sound.c.
 {
     int cnum;
     int mnum;
     // kill all playing sounds at start of level
     //  (trust me - a good idea)
     for (cnum=0 ; cnum<snd_channels ; cnum++)
     {
         if (channels[cnum].sfxinfo)
         {
             S_StopChannel(cnum);
         }
     }
     // start new music for the level
     mus_paused = 0;
     if (gamemode == commercial)
     {
         mnum = mus_runnin + gamemap - 1;
     }
     else
     {
         int spmus[]=
         {
             // Song - Who? - Where?
             mus_e3m4,        // American     e4m1
             mus_e3m2,        // Romero       e4m2
             mus_e3m3,        // Shawn        e4m3
             mus_e1m5,        // American     e4m4
             mus_e2m7,        // Tim          e4m5
             mus_e2m4,        // Romero       e4m6
             mus_e2m6,        // J.Anderson   e4m7 CHIRON.WAD
             mus_e2m5,        // Shawn        e4m8
             mus_e1m9,        // Tim          e4m9
         };
         if (gameepisode < 4)
         {
             mnum = mus_e1m1 + (gameepisode-1)*9 + gamemap-1;
         }
         else
         {
             mnum = spmus[gamemap-1];
         }
     }
     S_ChangeMusic(mnum, true);
 }
References channels, cnum, commercial, gameepisode, gamemap, gamemode, mus_e1m1, mus_e1m5, mus_e1m9, mus_e2m4, mus_e2m5, mus_e2m6, mus_e2m7, mus_e3m2, mus_e3m3, mus_e3m4, mus_paused, mus_runnin, S_ChangeMusic(), S_StopChannel(), and snd_channels.
Referenced by P_SetupLevel().
S_StartMusic()
void S_StartMusic (int music_id)
Definition at line 596 of file s_sound.c.
 {
     S_ChangeMusic(m_id, false);
 }
References S_ChangeMusic().
Referenced by D_DoAdvanceDemo(), and F_Ticker().
S_StartSound()
void S_StartSound (void * origin, int sound_id)
Definition at line 391 of file s_sound.c.
 {
     sfxinfo_t *sfx;
     mobj_t *origin;
     int rc;
     int sep;
     int cnum;
     int volume;
     origin = (mobj_t *) origin_p;
     volume = snd_SfxVolume;
     // check for bogus sound #
     if (sfx_id < 1 || sfx_id > NUMSFX)
     {
         I_Error("Bad sfx #: %d", sfx_id);
     }
     sfx = &S_sfx[sfx_id];
     // Initialize sound parameters
     if (sfx->link)
     {
         volume += sfx->volume;
         if (volume < 1)
         {
             return;
         }
         if (volume > snd_SfxVolume)
         {
             volume = snd_SfxVolume;
         }
     }
     // Check to see if it is audible,
     //  and if not, modify the params
     if (origin && origin != players[consoleplayer].mo)
     {
         rc = S_AdjustSoundParams(players[consoleplayer].mo,
                                  origin,
                                  &volume,
                                  &sep);
         if (origin->x == players[consoleplayer].mo->x
          && origin->y == players[consoleplayer].mo->y)
         {
             sep = NORM_SEP;
         }
         if (!rc)
         {
             return;
         }
     }
     else
     {
         sep = NORM_SEP;
     }
     // kill old sound
     S_StopSound(origin);
     // try to find a channel
     cnum = S_GetChannel(origin, sfx);
     if (cnum < 0)
     {
         return;
     }
     // increase the usefulness
     if (sfx->usefulness++ < 0)
     {
         sfx->usefulness = 1;
     }
     if (sfx->lumpnum < 0)
     {
         sfx->lumpnum = I_GetSfxLumpNum(sfx);
     }
     channels[cnum].handle = I_StartSound(sfx, cnum, volume, sep);
 }
References channels, cnum, consoleplayer, channel_t::handle, I_Error(), I_GetSfxLumpNum(), I_StartSound(), sfxinfo_struct::link, sfxinfo_struct::lumpnum, player_s::mo, NORM_SEP, NUMSFX, players, rc, S_AdjustSoundParams(), S_GetChannel(), S_sfx, S_StopSound(), snd_SfxVolume, sfxinfo_struct::usefulness, sfxinfo_struct::volume, mobj_s::x, and mobj_s::y.
Referenced by A_BabyMetal(), A_BFGsound(), A_BrainAwake(), A_BrainPain(), A_BrainScream(), A_BrainSpit(), A_BruisAttack(), A_Chase(), A_CloseShotgun2(), A_CPosAttack(), A_FatRaise(), A_FireCGun(), A_FireCrackle(), A_FirePistol(), A_FireShotgun(), A_FireShotgun2(), A_Hoof(), A_LoadShotgun2(), A_Look(), A_Metal(), A_OpenShotgun2(), A_Pain(), A_PlayerScream(), A_PosAttack(), A_Punch(), A_Saw(), A_Scream(), A_SkelFist(), A_SkelWhoosh(), A_SkullAttack(), A_SpawnFly(), A_SpawnSound(), A_SPosAttack(), A_StartFire(), A_TroopAttack(), A_VileAttack(), A_VileChase(), A_VileStart(), A_WeaponReady(), A_XScream(), EV_DoDoor(), EV_DoLockedDoor(), EV_DoPlat(), EV_Teleport(), EV_VerticalDoor(), F_BunnyScroll(), F_CastResponder(), F_CastTicker(), G_CheckSpot(), HU_Ticker(), M_EndGame(), M_QuickLoadResponse(), M_QuickSave(), M_QuickSaveResponse(), M_QuitResponse(), M_Responder(), P_BringUpWeapon(), P_ChangeSwitchTexture(), P_ExplodeMissile(), P_GiveWeapon(), P_NightmareRespawn(), P_RespawnSpecials(), P_SpawnMissile(), P_SpawnPlayerMissile(), P_TouchSpecialThing(), P_UpdateSpecials(), P_ZMovement(), PTR_UseTraverse(), T_MoveCeiling(), T_MoveFloor(), T_PlatRaise(), T_VerticalDoor(), WI_updateDeathmatchStats(), WI_updateNetgameStats(), and WI_updateStats().
S_StopMusic()
void S_StopMusic (void)
Definition at line 654 of file s_sound.c.
 {
     if (mus_playing)
     {
         if (mus_paused)
         {
             I_ResumeSong();
         }
         I_StopSong();
         I_UnRegisterSong(mus_playing->handle);
         W_ReleaseLumpNum(mus_playing->lumpnum);
         mus_playing->data = NULL;
         mus_playing = NULL;
     }
 }
References musicinfo_t::data, musicinfo_t::handle, I_ResumeSong(), I_StopSong(), I_UnRegisterSong(), musicinfo_t::lumpnum, mus_paused, mus_playing, NULL, and W_ReleaseLumpNum().
Referenced by S_ChangeMusic().
S_StopSound()
void S_StopSound (mobj_t * origin)
Definition at line 243 of file s_sound.c.
 {
     int cnum;
     for (cnum=0 ; cnum<snd_channels ; cnum++)
     {
         if (channels[cnum].sfxinfo && channels[cnum].origin == origin)
         {
             S_StopChannel(cnum);
             break;
         }
     }
 }
References channels, cnum, S_StopChannel(), and snd_channels.
Referenced by P_RemoveMobj(), and S_StartSound().
S_UpdateSounds()
void S_UpdateSounds (mobj_t * listener)
Definition at line 504 of file s_sound.c.
 {
     int                audible;
     int                cnum;
     int                volume;
     int                sep;
     sfxinfo_t*        sfx;
     channel_t*        c;
     I_UpdateSound();
     for (cnum=0; cnum<snd_channels; cnum++)
     {
         c = &channels[cnum];
         sfx = c->sfxinfo;
         if (c->sfxinfo)
         {
             if (I_SoundIsPlaying(c->handle))
             {
                 // initialize parameters
                 volume = snd_SfxVolume;
                 sep = NORM_SEP;
                 if (sfx->link)
                 {
                     volume += sfx->volume;
                     if (volume < 1)
                     {
                         S_StopChannel(cnum);
                         continue;
                     }
                     else if (volume > snd_SfxVolume)
                     {
                         volume = snd_SfxVolume;
                     }
                 }
                 // check non-local sounds for distance clipping
                 //  or modify their params
                 if (c->origin && listener != c->origin)
                 {
                     audible = S_AdjustSoundParams(listener,
                                                   c->origin,
                                                   &volume,
                                                   &sep);
                     if (!audible)
                     {
                         S_StopChannel(cnum);
                     }
                     else
                     {
                         I_UpdateSoundParams(c->handle, volume, sep);
                     }
                 }
             }
             else
             {
                 // if channel is allocated but sound has stopped,
                 //  free it
                 S_StopChannel(cnum);
             }
         }
     }
 }
References c, channels, cnum, I_SoundIsPlaying(), I_UpdateSound(), I_UpdateSoundParams(), sfxinfo_struct::link, NORM_SEP, S_AdjustSoundParams(), S_StopChannel(), snd_channels, snd_SfxVolume, and sfxinfo_struct::volume.
Referenced by doomgeneric_Tick().
Variable Documentation
snd_channels
int snd_channels extern
Definition at line 106 of file s_sound.c.
Referenced by D_BindVariables(), S_GetChannel(), S_Init(), S_Start(), S_StopChannel(), S_StopSound(), and S_UpdateSounds().