Fennix Userspace: Userspace/mlibc/tests/posix/pause.c File Reference
pause.c File Reference
#include <assert.h>
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <sys/wait.h>
Functions
static void noop (int x)
int main ()
Function Documentation
main()
int main (void)
Definition at line 13 of file pause.c.
            {
     signal(SIGUSR1, &noop);
     int pid;
     switch(pid = fork()) {
     case -1:
         perror("fork");
         abort();
     case 0:
         pause();
         assert(errno == EINTR);
         return 0;
     default:
         while (1) {
             usleep(100);
             kill(pid, SIGUSR1);
             usleep(100);
             int status;
             errno = 0;
             if (waitpid(-1, &status, WNOHANG) <= 0) {
                 if (errno && errno != EAGAIN) {
                     perror("wait");
                     kill(pid, SIGKILL);
                 }
                 continue;
             }
             if (!WIFEXITED(status)) {
                 printf("wait returned %x\n", status);
                 abort();
             }
             return WEXITSTATUS(status);
         }
     }
 }
References abort(), assert, EAGAIN, EINTR, errno, fork(), kill(), noop(), pause(), perror(), printf(), SIGKILL, signal(), SIGUSR1, mlibc::status, usleep(), waitpid(), WEXITSTATUS, WIFEXITED, and WNOHANG.
noop()
static void noop (int x) static
Definition at line 9 of file pause.c.
{
     (void)x;
 }
References x.
Referenced by main().