Fennix Userspace: Userspace/libc/include/stdlib.h File Reference
stdlib.h File Reference
#include <stddef.h>
Macros
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
Functions
void abort (void)
int atexit (void(*function)(void))
void exit (int status)
int atoi (const char *nptr)
char * getenv (const char *name)
void * malloc (size_t Size)
void * realloc (void *Address, size_t Size)
void * calloc (size_t Count, size_t Size)
void free (void *Address)
int system (const char *command)
double atof (const char *nptr)
void perror (const char *s)
Macro Definition Documentation
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 11 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 12 of file stdlib.h.
Function Documentation
abort()
void abort (void)
Definition at line 9 of file lib.c.
 {
     syscall1(sys_Exit, -0xAB057);
     while (1)
         ;
 }
atexit()
int atexit (void(*)(void) function)
Definition at line 16 of file lib.c.
 {
     return 1;
 }
atof()
double atof (const char * nptr)
Definition at line 72 of file lib.c.
 {
     // FIXME: This is a very bad implementation of atof.
     uint64_t Length = strlen((char *)nptr);
     if (nptr)
         while (nptr[Length] != '\0')
             ++Length;
     double OutBuffer = 0;
     double Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (nptr[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References i, and strlen().
atoi()
int atoi (const char * nptr)
Definition at line 26 of file lib.c.
 {
     uint64_t Length = strlen((char *)nptr);
     if (nptr)
         while (nptr[Length] != '\0')
             ++Length;
     uint64_t OutBuffer = 0;
     uint64_t Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (nptr[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References i, and strlen().
calloc()
void* calloc (size_t Count, size_t Size)
Definition at line 1543 of file malloc.c.
 {
exit()
void exit (int status)
Definition at line 21 of file lib.c.
 {
     _exit(status);
 }
References _exit(), and mlibc::status.
free()
void free (void * Address)
Definition at line 560 of file liballoc_1_1.c.
 {
     struct liballoc_minor *min;
     struct liballoc_major *maj;
     if (ptr == NULL)
     {
         l_warningCount += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
         printf("liballoc: WARNING: PREFIX(free)( NULL ) called from %x\n",
                __builtin_return_address(0));
         FLUSH();
 #endif
         return;
     }
     UNALIGN(ptr);
     liballoc_lock(); // lockit
     min = (struct liballoc_minor *)((uintptr_t)ptr - sizeof(struct liballoc_minor));
     if (min->magic != LIBALLOC_MAGIC)
     {
         l_errorCount += 1;
         // Check for overrun errors. For all bytes of LIBALLOC_MAGIC
         if (
             ((min->magic & 0xFFFFFF) == (LIBALLOC_MAGIC & 0xFFFFFF)) ||
             ((min->magic & 0xFFFF) == (LIBALLOC_MAGIC & 0xFFFF)) ||
             ((min->magic & 0xFF) == (LIBALLOC_MAGIC & 0xFF)))
         {
             l_possibleOverruns += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Possible 1-3 byte overrun for magic %x != %x\n",
                    min->magic,
                    LIBALLOC_MAGIC);
             FLUSH();
 #endif
         }
         if (min->magic == LIBALLOC_DEAD)
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: multiple PREFIX(free)() attempt on %x from %x.\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         else
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Bad PREFIX(free)( %x ) called from %x\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         // being lied to...
         liballoc_unlock(); // release the lock
         return;
     }
 #ifdef LIBALLOCDEBUG
     printf("liballoc: %x PREFIX(free)( %x ): ",
            __builtin_return_address(0),
            ptr);
     FLUSH();
 #endif
     maj = min->block;
     l_inuse -= min->size;
     maj->usage -= (min->size + sizeof(struct liballoc_minor));
     min->magic = LIBALLOC_DEAD; // No mojo.
     if (min->next != NULL)
         min->next->prev = min->prev;
     if (min->prev != NULL)
         min->prev->next = min->next;
     if (min->prev == NULL)
         maj->first = min->next;
     // Might empty the block. This was the first
     // minor.
     // We need to clean up after the majors now....
     if (maj->first == NULL) // Block completely unused.
     {
         if (l_memRoot == maj)
             l_memRoot = maj->next;
         if (l_bestBet == maj)
             l_bestBet = NULL;
         if (maj->prev != NULL)
             maj->prev->next = maj->next;
         if (maj->next != NULL)
             maj->next->prev = maj->prev;
         l_allocated -= maj->size;
         liballoc_free(maj, maj->pages);
     }
     else
     {
         if (l_bestBet != NULL)
         {
             int bestSize = l_bestBet->size - l_bestBet->usage;
             int majSize = maj->size - maj->usage;
             if (majSize > bestSize)
                 l_bestBet = maj;
         }
     }
 #ifdef LIBALLOCDEBUG
     printf("OK\n");
     FLUSH();
 #endif
     liballoc_unlock(); // release the lock
 }
getenv()
char* getenv (const char * name)
Definition at line 44 of file lib.c.
 {
     char **env = environ;
     if (env == NULL)
         return NULL;
     size_t len = strlen(name);
     while (*env != NULL)
     {
         if ((strncmp(*env, name, len) == 0) && ((*env)[len] == '='))
             return &(*env)[len + 1];
         ++env;
     }
 }
References env, environ, name, NULL, strlen(), and strncmp().
malloc()
void* malloc (size_t Size)
Definition at line 1503 of file malloc.c.
 {
perror()
void perror (const char * s)
Definition at line 34 of file put.c.
 { fputs(s, stderr); }
References fputs(), and stderr.
Referenced by com_cd(), com_stat(), file_error(), main(), process_line(), run_cmd(), and vwarn().
realloc()
void* realloc (void * Address, size_t Size)
Definition at line 699 of file liballoc_1_1.c.
 {
     void *ptr;
     struct liballoc_minor *min;
     unsigned int real_size;
     // Honour the case of size == 0 => free old and return NULL
     if (size == 0)
     {
         PREFIX(free)
         (p);
         return NULL;
     }
     // In the case of a NULL pointer, return a simple malloc.
     if (p == NULL)
         return PREFIX(malloc)(size);
     // Unalign the pointer if required.
     ptr = p;
     UNALIGN(ptr);
     liballoc_lock(); // lockit
     min = (struct liballoc_minor *)((uintptr_t)ptr - sizeof(struct liballoc_minor));
     // Ensure it is a valid structure.
     if (min->magic != LIBALLOC_MAGIC)
     {
         l_errorCount += 1;
         // Check for overrun errors. For all bytes of LIBALLOC_MAGIC
         if (
             ((min->magic & 0xFFFFFF) == (LIBALLOC_MAGIC & 0xFFFFFF)) ||
             ((min->magic & 0xFFFF) == (LIBALLOC_MAGIC & 0xFFFF)) ||
             ((min->magic & 0xFF) == (LIBALLOC_MAGIC & 0xFF)))
         {
             l_possibleOverruns += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Possible 1-3 byte overrun for magic %x != %x\n",
                    min->magic,
                    LIBALLOC_MAGIC);
             FLUSH();
 #endif
         }
         if (min->magic == LIBALLOC_DEAD)
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: multiple PREFIX(free)() attempt on %x from %x.\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         else
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Bad PREFIX(free)( %x ) called from %x\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         // being lied to...
         liballoc_unlock(); // release the lock
         return NULL;
     }
     // Definitely a memory block.
     real_size = min->req_size;
     if (real_size >= size)
     {
         min->req_size = size;
         liballoc_unlock();
         return p;
     }
     liballoc_unlock();
     // If we got here then we're reallocating to a block bigger than us.
     ptr = PREFIX(malloc)(size); // We need to allocate new memory
     liballoc_memcpy(ptr, p, real_size);
     PREFIX(free)
     (p);
     return ptr;
 }
References FLUSH, free(), l_errorCount, l_possibleOverruns, LIBALLOC_DEAD, liballoc_lock(), LIBALLOC_MAGIC, liballoc_memcpy(), liballoc_unlock(), malloc(), min(), NULL, p, PREFIX, printf(), size, and UNALIGN.
system()
int system (const char * command)
Definition at line 67 of file lib.c.
 {
     return -1;
 }
Referenced by com_list(), com_view(), ZenityAvailable(), and ZenityErrorBox().