Fennix: Userspace/apps/base/busybox/util-linux/blockdev.c File Reference
blockdev.c File Reference
#include "libbb.h"
#include <linux/fs.h>
Macros
#define CMD_SETRO 0
#define CMD_SETBSZ 5
#define CMD_SETRA 10
Enumerations
enum {
ARG_NONE = 0 , ARG_INT = 1 , ARG_ULONG = 2 , ARG_U64 = 3 ,
ARG_MASK = 3 , FL_USRARG = 4 , FL_NORESULT = 8 , FL_SCALE512 = 16
}
Functions
static unsigned find_cmd (const char *s)
int blockdev_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char bdcmd_names[] ALIGN1
static const uint32_t bdcmd_ioctl[] ALIGN4
Macro Definition Documentation
CMD_SETBSZ
#define CMD_SETBSZ 5
CMD_SETRA
#define CMD_SETRA 10
CMD_SETRO
#define CMD_SETRO 0
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARG_NONE
ARG_INT
ARG_ULONG
ARG_U64
ARG_MASK
FL_USRARG
FL_NORESULT
FL_SCALE512
Definition at line 84 of file blockdev.c.
      {
     ARG_NONE   = 0,
     ARG_INT    = 1,
     ARG_ULONG  = 2,
     /* Yes, BLKGETSIZE64 takes pointer to uint64_t, not ullong! */
     ARG_U64    = 3,
     ARG_MASK   = 3,
     FL_USRARG   = 4, /* argument is provided by user */
     FL_NORESULT = 8,
     FL_SCALE512 = 16,
 };
Function Documentation
blockdev_main()
int blockdev_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 123 of file blockdev.c.
 {
     unsigned bdcmd;
     unsigned flags;
     int fd;
     uint64_t u64;
     union {
         int i;
         unsigned long lu;
         uint64_t u64;
     } ioctl_val_on_stack;
     argv++;
     if (!argv[0] || !argv[1]) /* must have at least 2 args */
         bb_show_usage();
     bdcmd = find_cmd(*argv);
     /* setrw translates to BLKROSET(0), most other ioctls don't care... */
     /* ...setro will do BLKROSET(1) */
     u64 = (bdcmd == CMD_SETRO);
     if (bdcmd == CMD_SETBSZ || bdcmd == CMD_SETRA) {
         /* ...setbsz is BLKBSZSET(bytes) */
         /* ...setra is BLKRASET(512 bytes) */
         u64 = xatoi_positive(*++argv);
     }
     argv++;
     if (!argv[0] || argv[1])
         bb_show_usage();
     fd = xopen(argv[0], O_RDONLY);
     ioctl_val_on_stack.u64 = u64;
     flags = bdcmd_flags[bdcmd];
 #if BB_BIG_ENDIAN
     /* Store data properly wrt data size.
      * (1) It's no-op for little-endian.
      * (2) it's no-op for 0 and -1.
      * --setro uses arg != 0 and != -1, and it is ARG_INT
      * --setbsz USER_VAL is also ARG_INT
      * --setra USER_VAL is ARG_ULONG, but it is passed by value,
      * not reference (see below in ioctl call).
      * Thus, we don't need to handle ARG_ULONG.
      */
     switch (flags & ARG_MASK) {
     case ARG_INT:
         ioctl_val_on_stack.i = (int)u64;
         break;
 # if 0 /* unused */
     case ARG_ULONG:
         ioctl_val_on_stack.lu = (unsigned long)u64;
         break;
 # endif
     }
 #endif
     if (ioctl(fd, bdcmd_ioctl[bdcmd],
             bdcmd == CMD_SETRA
                 ? (void*)(uintptr_t)u64 /* BLKRASET passes _value_, not pointer to it */
                 : &ioctl_val_on_stack.u64
         ) == -1)
         bb_simple_perror_msg_and_die(*argv);
     /* Fetch it into register(s) */
     u64 = ioctl_val_on_stack.u64;
     if (flags & FL_SCALE512)
         u64 >>= 9;
     /* Zero- or one-extend the value if needed, then print */
     switch (flags & (ARG_MASK+FL_NORESULT)) {
     case ARG_INT:
         /* Smaller code when we use long long
          * (gcc tail-merges printf call)
          */
         printf("%lld\n", (long long)(int)u64);
         break;
     case ARG_ULONG:
         u64 = (unsigned long)u64;
         /* FALLTHROUGH */
     case ARG_U64:
         printf("%llu\n", (unsigned long long)u64);
         break;
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     return EXIT_SUCCESS;
 }
References ARG_INT, ARG_MASK, ARG_U64, ARG_ULONG, argv, bb_show_usage(), bb_simple_perror_msg_and_die(), close(), CMD_SETBSZ, CMD_SETRA, CMD_SETRO, EXIT_SUCCESS, fd, find_cmd(), FL_NORESULT, FL_SCALE512, flags, i, ioctl(), O_RDONLY, printf, xatoi_positive(), and xopen().
find_cmd()
static unsigned find_cmd (const char * s) static
Definition at line 112 of file blockdev.c.
 {
     if (s[0] == '-' && s[1] == '-') {
         int n = index_in_strings(bdcmd_names, s + 2);
         if (n >= 0)
             return n;
     }
     bb_show_usage();
 }
References bb_show_usage(), index_in_strings(), n, and s.
Referenced by blockdev_main().
Variable Documentation
ALIGN1
const uint8_t bdcmd_flags [] ALIGN1 static
Initial value:
=
    "setro"     "\0"
#define CMD_SETRO
    "setrw"     "\0"
    "getro"     "\0"
    "getss"     "\0"
    "getbsz"    "\0"
    "setbsz"    "\0"
#define CMD_SETBSZ
    "getsz"     "\0"
    "getsize"   "\0"
    "getsize64" "\0"
    "getra"     "\0"
    "setra"     "\0"
#define CMD_SETRA
    "flushbufs" "\0"
    "rereadpt"  "\0"
Definition at line 51 of file blockdev.c.
ALIGN4
const uint32_t bdcmd_ioctl [] ALIGN4 static
Initial value:
= {
    BLKROSET,
    BLKROSET,
    BLKROGET,
    BLKSSZGET,
    BLKBSZGET,
    BLKBSZSET,
    BLKGETSIZE64,
    BLKGETSIZE,
    BLKGETSIZE64,
    BLKRAGET,
    BLKRASET,
    BLKFLSBUF,
    BLKRRPART,
}
Definition at line 69 of file blockdev.c.