Fennix: Userspace/apps/base/busybox/libbb/print_numbered_lines.c File Reference
print_numbered_lines.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC print_numbered_lines (struct number_state *ns, const char *filename)
Function Documentation
print_numbered_lines()
int FAST_FUNC print_numbered_lines (struct number_state * ns, const char * filename)
Definition at line 11 of file print_numbered_lines.c.
 {
     FILE *fp = fopen_or_warn_stdin(filename);
     unsigned N;
     char *line;
     if (!fp)
         return EXIT_FAILURE;
     N = ns->start;
     while ((line = xmalloc_fgetline(fp)) != NULL) {
         if (ns->all
          || (ns->nonempty && line[0])
         ) {
             printf("%*u%s", ns->width, N, ns->sep);
             N += ns->inc;
         } else if (ns->empty_str)
             fputs_stdout(ns->empty_str);
         puts(line);
         free(line);
     }
     ns->start = N;
     fclose(fp);
     return EXIT_SUCCESS;
 }
References number_state::all, number_state::empty_str, EXIT_FAILURE, EXIT_SUCCESS, fclose(), filename, fopen_or_warn_stdin(), fputs_stdout(), free, number_state::inc, line, N, number_state::nonempty, NULL, printf, puts(), number_state::sep, number_state::start, number_state::width, and xmalloc_fgetline().
Referenced by cat_main(), and nl_main().