Fennix Kernel: Kernel/include/filesystem/mounts.hpp File Reference
mounts.hpp File Reference
#include <types.h>
#include <filesystem.hpp>
Functions
void Init_Null (VirtualFileSystem::Virtual *vfs_ctx)
void Init_Random (VirtualFileSystem::Virtual *vfs_ctx)
void Init_Teletype (VirtualFileSystem::Virtual *vfs_ctx)
void Init_Zero (VirtualFileSystem::Virtual *vfs_ctx)
Function Documentation
Init_Null()
void Init_Null (VirtualFileSystem::Virtual * vfs_ctx)
Definition at line 45 of file Null.cpp.
 {
     Node *n = vfs_ctx->Create("null", CHARDEVICE, DevFS);
     n->Operator = &null_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, null_op, and VirtualFileSystem::Node::Operator.
Referenced by Main().
Init_Random()
void Init_Random (VirtualFileSystem::Virtual * vfs_ctx)
Definition at line 48 of file Random.cpp.
 {
     Node *n = vfs_ctx->Create("random", CHARDEVICE, DevFS);
     n->Operator = &random_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, VirtualFileSystem::Node::Operator, and random_op.
Referenced by Main().
Init_Teletype()
void Init_Teletype (VirtualFileSystem::Virtual * vfs_ctx)
Definition at line 39 of file Teletype.cpp.
 {
     Node *n = vfs_ctx->Create("tty", CHARDEVICE, DevFS);
     n->Operator = &tty_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, VirtualFileSystem::Node::Operator, and tty_op.
Referenced by Main().
Init_Zero()
void Init_Zero (VirtualFileSystem::Virtual * vfs_ctx)
Definition at line 45 of file Zero.cpp.
 {
     Node *n = vfs_ctx->Create("zero", CHARDEVICE, DevFS);
     n->Operator = &zero_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, VirtualFileSystem::Node::Operator, and zero_op.
Referenced by Main().