Fennix Userspace: Userspace/musl/src/internal/fork_impl.h File Reference
fork_impl.h File Reference
#include <features.h>
Functions
hidden void __malloc_atfork (int)
hidden void __ldso_atfork (int)
hidden void __pthread_key_atfork (int)
Variables
hidden volatile int *const __at_quick_exit_lockptr
hidden volatile int *const __atexit_lockptr
hidden volatile int *const __gettext_lockptr
hidden volatile int *const __locale_lockptr
hidden volatile int *const __random_lockptr
hidden volatile int *const __sem_open_lockptr
hidden volatile int *const __stdio_ofl_lockptr
hidden volatile int *const __syslog_lockptr
hidden volatile int *const __timezone_lockptr
hidden volatile int *const __bump_lockptr
hidden volatile int *const __vmlock_lockptr
Function Documentation
__ldso_atfork()
hidden void __ldso_atfork (int who)
Definition at line 1497 of file dynlink.c.
 {
     if (who<0) {
         pthread_rwlock_wrlock(&lock);
         pthread_mutex_lock(&init_fini_lock);
     } else {
         pthread_mutex_unlock(&init_fini_lock);
         pthread_rwlock_unlock(&lock);
     }
 }
References init_fini_lock, lock, pthread_mutex_lock(), pthread_mutex_unlock(), pthread_rwlock_unlock(), and pthread_rwlock_wrlock().
Referenced by fork().
__malloc_atfork()
hidden void __malloc_atfork (int who)
Definition at line 540 of file malloc.c.
 {
     if (who<0) {
         lock(mal.split_merge_lock);
         for (int i=0; i<64; i++)
             lock(mal.bins[i].lock);
     } else if (!who) {
         for (int i=0; i<64; i++)
             unlock(mal.bins[i].lock);
         unlock(mal.split_merge_lock);
     } else {
         for (int i=0; i<64; i++)
             mal.bins[i].lock[0] = mal.bins[i].lock[1] = 0;
         mal.split_merge_lock[1] = 0;
         mal.split_merge_lock[0] = 0;
     }
 }
References i, lock(), mal, and unlock().
Referenced by fork().
__pthread_key_atfork()
hidden void __pthread_key_atfork (int who)
Definition at line 24 of file pthread_key_create.c.
 {
     if (who<0) __pthread_rwlock_rdlock(&key_lock);
     else if (!who) __pthread_rwlock_unlock(&key_lock);
     else key_lock = (pthread_rwlock_t)PTHREAD_RWLOCK_INITIALIZER;
 }
References __pthread_rwlock_rdlock(), __pthread_rwlock_unlock(), key_lock, and PTHREAD_RWLOCK_INITIALIZER.
Referenced by fork().
Variable Documentation
__at_quick_exit_lockptr
hidden volatile int* const __at_quick_exit_lockptr extern
Definition at line 11 of file at_quick_exit.c.
__atexit_lockptr
hidden volatile int* const __atexit_lockptr extern
Definition at line 24 of file atexit.c.
__bump_lockptr
hidden volatile int* const __bump_lockptr extern
Definition at line 36 of file lite_malloc.c.
__gettext_lockptr
hidden volatile int* const __gettext_lockptr extern
Definition at line 44 of file dcngettext.c.
__locale_lockptr
hidden volatile int* const __locale_lockptr extern
Definition at line 32 of file locale_map.c.
__random_lockptr
hidden volatile int* const __random_lockptr extern
Definition at line 27 of file random.c.
__sem_open_lockptr
hidden volatile int* const __sem_open_lockptr extern
Definition at line 28 of file sem_open.c.
__stdio_ofl_lockptr
hidden volatile int* const __stdio_ofl_lockptr extern
Definition at line 7 of file ofl.c.
__syslog_lockptr
hidden volatile int* const __syslog_lockptr extern
Definition at line 21 of file syslog.c.
__timezone_lockptr
hidden volatile int* const __timezone_lockptr extern
Definition at line 40 of file __tz.c.
__vmlock_lockptr
hidden volatile int* const __vmlock_lockptr extern
Definition at line 5 of file vmlock.c.
Referenced by fork().