Fennix Kernel: Kernel/include/smp.hpp File Reference
smp.hpp File Reference
#include <task.hpp>
#include <cxxabi.h>
#include <types.h>
#include <atomic>
Data Structures
struct CPUArchData
struct CPUData
Namespaces
SMP
Macros
#define MAX_CPU 255
Maximum supported number of CPU cores by the kernel.
#define CPU_DATA_CHECKSUM 0xC0FFEE
Functions
struct CPUData __aligned (16)
CPUData * GetCurrentCPU ()
CPUData * GetCPU (long ID)
void SMP::Initialize (void *madt)
Variables
uintptr_t Stack
Used by CPU.
int ID
CPU ID.
long ErrorCode
Local CPU error code.
std::atomic< Tasking::PCB * > CurrentProcess
Current running process.
std::atomic< Tasking::TCB * > CurrentThread
Current running thread.
__cxa_eh_globals EHGlobals
Unwind data.
CPUArchData Data
Architecture-specific data.
int Checksum
Checksum. Used to verify the integrity of the data. Must be equal to CPU_DATA_CHECKSUM (0xC0FFEE).
bool IsActive
Is CPU online?
Data Structure Documentation
CPUArchData
struct CPUArchData
Definition at line 30 of file smp.hpp.
CPUData
struct CPUData
Definition at line 40 of file smp.hpp.
Data Fields
int Checksum Checksum. Used to verify the integrity of the data. Must be equal to CPU_DATA_CHECKSUM (0xC0FFEE).
atomic< PCB * > CurrentProcess Current running process.
atomic< TCB * > CurrentThread Current running thread.
CPUArchData Data Architecture-specific data.
__cxa_eh_globals EHGlobals Unwind data.
long ErrorCode Local CPU error code.
int ID CPU ID.
bool IsActive Is CPU online?
uintptr_t Stack Used by CPU.
Macro Definition Documentation
CPU_DATA_CHECKSUM
#define CPU_DATA_CHECKSUM 0xC0FFEE
Definition at line 28 of file smp.hpp.
MAX_CPU
#define MAX_CPU 255
Maximum supported number of CPU cores by the kernel.
Definition at line 27 of file smp.hpp.
Function Documentation
__aligned()
struct CPUData __aligned (16)
Definition at line 32 of file syscalls.cpp.
 {
     asmv("swapgs\n");            /* Swap GS to get the gsTCB */
     asmv("mov %rsp, %gs:0x8\n"); /* We save the current rsp to gsTCB->TempStack */
     asmv("mov %gs:0x0, %rsp\n"); /* Get gsTCB->SystemCallStack and set it as rsp */
     asmv("push $0x1b\n");        /* Push user data segment for SyscallsFrame */
     asmv("push %gs:0x8\n");      /* Push gsTCB->TempStack (old rsp) for SyscallsFrame */
     asmv("push %r11\n");         /* Push the flags for SyscallsFrame */
     asmv("push $0x23\n");        /* Push user code segment for SyscallsFrame */
     asmv("push %rcx\n");         /* Push the return address for SyscallsFrame + sysretq (https://www.felixcloutier.com/x86/sysret) */
     /* Push registers */
     asmv("push %rax\n"
          "push %rbx\n"
          "push %rcx\n"
          "push %rdx\n"
          "push %rsi\n"
          "push %rdi\n"
          "push %rbp\n"
          "push %r8\n"
          "push %r9\n"
          "push %r10\n"
          "push %r11\n"
          "push %r12\n"
          "push %r13\n"
          "push %r14\n"
          "push %r15\n");
     /* Set the first argument to the SyscallsFrame pointer */
     asmv("mov %rsp, %rdi\n");
     asmv("mov $0, %rbp\n");
     asmv("call SystemCallsHandler\n");
     /* Pop registers except rax */
     asmv("pop %r15\n"
          "pop %r14\n"
          "pop %r13\n"
          "pop %r12\n"
          "pop %r11\n"
          "pop %r10\n"
          "pop %r9\n"
          "pop %r8\n"
          "pop %rbp\n"
          "pop %rdi\n"
          "pop %rsi\n"
          "pop %rdx\n"
          "pop %rcx\n"
          "pop %rbx\n");
     /* Restore rsp from gsTCB->TempStack */
     asmv("mov %gs:0x8, %rsp\n");
 #ifdef DEBUG
     /* Easier to debug stacks */
     asmv("movq $0, %gs:0x8\n");
 #endif
     asmv("swapgs\n");  /* Swap GS back to the user GS */
     asmv("sti\n");     /* Enable interrupts */
     asmv("sysretq\n"); /* Return to rcx address in user mode */
 }
GetCPU()
CPUData* GetCPU (long ID)
Definition at line 49 of file smp.cpp.
 { return &CPUs[id]; }
GetCurrentCPU()
CPUData* GetCurrentCPU ()
Definition at line 33 of file smp.cpp.
 {
     uint64_t ret = 0;
     if (!CPUs[ret].IsActive)
     {
         error("CPU %d is not active!", ret);
         return &CPUs[0];
     }
     if (CPUs[ret].Checksum != CPU_DATA_CHECKSUM)
     {
         error("CPU %d data is corrupted!", ret);
         return &CPUs[0];
     }
     return &CPUs[ret];
 }
References APIC::APIC_ID, assert, Checksum, CPU_DATA_CHECKSUM, CPUEnabled, error, IsActive, KernelPageTable, memory_order_acquire, CPU::x32::MSR_X2APIC_APICID, CPU::x64::MSR_X2APIC_APICID, APIC::APIC::Read(), swap(), thisPageTable, unlikely, and APIC::APIC::x2APIC.
Referenced by __cxxabiv1::__cxa_get_globals(), DisplayAssertionFailed(), DisplayBufferOverflow(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayStackSmashing(), Tasking::Task::GetCurrentProcess(), Tasking::Task::GetCurrentThread(), GlobalDescriptorTable::GetKernelStack(), HandleException(), HandleUnrecoverableException(), Interrupts::MainInterruptHandler(), ACPI::DSDT::OnInterruptReceived(), GlobalDescriptorTable::SetKernelStack(), TaskingScheduler_OneShot(), ThreadDoExit(), APIC::Timer::Timer(), UserModeExceptionHandler(), and Tasking::Task::~Task().
Variable Documentation
Checksum
int Checksum
Checksum. Used to verify the integrity of the data. Must be equal to CPU_DATA_CHECKSUM (0xC0FFEE).
Definition at line 22 of file smp.hpp.
CurrentProcess
std::atomic<Tasking::PCB *> CurrentProcess
Current running process.
Definition at line 10 of file smp.hpp.
Referenced by Tasking::Task::~Task().
CurrentThread
std::atomic<Tasking::TCB *> CurrentThread
Current running thread.
Definition at line 13 of file smp.hpp.
Referenced by ThreadDoExit(), and Tasking::Task::~Task().
Data
CPUArchData Data
Architecture-specific data.
Definition at line 19 of file smp.hpp.
EHGlobals
__cxa_eh_globals EHGlobals
Unwind data.
Definition at line 16 of file smp.hpp.
ErrorCode
long ErrorCode
Local CPU error code.
Definition at line 7 of file smp.hpp.
ID
int ID
CPU ID.
Definition at line 4 of file smp.hpp.
Referenced by Tasking::Task::GetProcessByID(), Tasking::Task::GetThreadByID(), Driver::MasterDeviceFile::NewAudio(), Driver::MasterDeviceFile::NewBlock(), Driver::MasterDeviceFile::NewNet(), ACPI::DSDT::OnInterruptReceived(), Driver::MasterDeviceFile::Register(), Driver::MasterDeviceFile::ReportKeyEvent(), Tasking::Task::SignalShutdown(), APIC::Timer::Timer(), Driver::MasterDeviceFile::Unregister(), and Tasking::Task::~Task().
IsActive
bool IsActive
Is CPU online?
Definition at line 25 of file smp.hpp.
Referenced by GetCurrentCPU().
Stack
uintptr_t Stack
Used by CPU.
Definition at line 1 of file smp.hpp.
Referenced by Tasking::__no_sanitize(), __stack_chk_fail(), GlobalDescriptorTable::SetKernelStack(), and StartCPU().