Fennix: Userspace/apps/base/bash/lib/sh/ufuncs.c File Reference
ufuncs.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixtime.h"
#include <errno.h>
Functions
int falarm (unsigned int secs, unsigned int usecs)
int fsleep (long sec, long usec)
Variables
int errno
Function Documentation
falarm()
int falarm (unsigned int secs, unsigned int usecs)
Definition at line 68 of file ufuncs.c.
 {
   if (secs == 0 && usecs == 0)
     return (alarm (0));
   if (secs == 0 || usecs >= 500000)
     {
       secs++;
       usecs = 0;
     }
   return (alarm (secs));
 }
References alarm().
Referenced by shtimer_set(), and shtimer_unset().
fsleep()
int fsleep (long sec, long usec)
Definition at line 133 of file ufuncs.c.
 {
   if (usec >= 500000)   /* round */
    sec++;
   return (sleep(sec));
 }
References sleep().
Referenced by sleep_builtin().
Variable Documentation
errno
int errno extern