Fennix: Userspace/musl/src/stdio/fileno.c File Reference
fileno.c File Reference
#include "stdio_impl.h"
#include <errno.h>
Functions
int fileno (FILE *f)
weak_alias (fileno, fileno_unlocked)
Function Documentation
fileno()
int fileno (FILE * f)
Definition at line 4 of file fileno.c.
 {
     FLOCK(f);
     int fd = f->fd;
     FUNLOCK(f);
     if (fd < 0) {
         errno = EBADF;
         return -1;
     }
     return fd;
 }
References EBADF, errno, f, fd, FLOCK, and FUNLOCK.
Referenced by _rl_init_terminal_io(), _rl_input_available(), _rl_nchars_available(), _rl_sigwinch_resize_terminal(), add_remove_shell_main(), awk_getline(), check_dev_tty(), command_substitute(), convert(), decode_prompt_string(), do_redirection_internal(), download_one_url(), dump_file(), getc_with_restart(), getXXent(), I_ConsoleStdout(), initialize_job_control(), load_crontab(), main(), more_main(), move_to_high_fd(), open_shell_script(), patch_main(), retrieve_file_data(), rl_deprep_terminal(), rl_gather_tyi(), rl_getc(), rl_insert_close(), rl_prep_terminal(), rl_reset_screen_size(), rl_resize_terminal(), rl_restart_output(), rl_stop_output(), rltty_set_default_bindings(), run_startup_files(), set_bash_input(), skip(), update_passwd(), xprint_and_close_file(), and xtrace_set().
weak_alias()
weak_alias (fileno , fileno_unlocked)