Fennix Userspace: Userspace/apps/base/busybox/libbb/process_escape_sequence.c File Reference
process_escape_sequence.c File Reference
#include "libbb.h"
Macros
#define WANT_HEX_ESCAPES 1
#define _tolower(X) ((X)|((char) 0x20))
Functions
char FAST_FUNC bb_process_escape_sequence (const char **ptr)
char *FAST_FUNC strcpy_and_process_escape_sequences (char *dst, const char *src)
Macro Definition Documentation
_tolower
#define _tolower (X) ((X)|((char) 0x20))
Definition at line 16 of file process_escape_sequence.c.
WANT_HEX_ESCAPES
#define WANT_HEX_ESCAPES 1
Definition at line 12 of file process_escape_sequence.c.
Function Documentation
bb_process_escape_sequence()
char FAST_FUNC bb_process_escape_sequence (const char ** ptr)
Definition at line 18 of file process_escape_sequence.c.
 {
     const char *q;
     unsigned num_digits;
     unsigned n;
     unsigned base;
     num_digits = n = 0;
     base = 8;
     q = *ptr;
     if (WANT_HEX_ESCAPES && *q == 'x') {
         ++q;
         base = 16;
         ++num_digits;
     }
     /* bash requires leading 0 in octal escapes:
      * \02 works, \2 does not (prints \ and 2).
      * We treat \2 as a valid octal escape sequence. */
     do {
         unsigned r;
         unsigned d = (unsigned char)(*q) - '0';
 #if WANT_HEX_ESCAPES
         if (d >= 10) {
             d = (unsigned char)_tolower(*q) - 'a';
             //d += 10;
             /* The above would map 'A'-'F' and 'a'-'f' to 10-15,
              * however, some chars like '@' would map to 9 < base.
              * Do not allow that, map invalid chars to N > base:
              */
             if ((int)d >= 0)
                 d += 10;
         }
 #endif
         if (d >= base) {
             if (WANT_HEX_ESCAPES && base == 16) {
                 --num_digits;
                 if (num_digits == 0) {
                     /* \x<bad_char>: return '\',
                      * leave ptr pointing to x */
                     return '\\';
                 }
             }
             break;
         }
         r = n * base + d;
         if (r > UCHAR_MAX) {
             break;
         }
         n = r;
         ++q;
     } while (++num_digits < 3);
     if (num_digits == 0) {
         /* Not octal or hex escape sequence.
          * Is it one-letter one? */
         /* bash builtin "echo -e '\ec'" interprets \e as ESC,
          * but coreutils "/bin/echo -e '\ec'" does not.
          * Manpages tend to support coreutils way.
          * Update: coreutils added support for \e on 28 Oct 2009. */
         static const char charmap[] ALIGN1 = {
             'a',  'b', 'e', 'f',  'n',  'r',  't',  'v',  '\\', '\0',
             '\a', '\b', 27, '\f', '\n', '\r', '\t', '\v', '\\', '\\',
         };
         const char *p = charmap;
         do {
             if (*p == *q) {
                 q++;
                 break;
             }
         } while (*++p != '\0');
         /* p points to found escape char or NUL,
          * advance it and find what it translates to.
          * Note that \NUL and unrecognized sequence \z return '\'
          * and leave ptr pointing to NUL or z. */
         n = p[sizeof(charmap) / 2];
     }
     *ptr = q;
     return (char) n;
 }
References _tolower, ALIGN1, base, n, p, UCHAR_MAX, and WANT_HEX_ESCAPES.
Referenced by expand(), next_token(), nextchar(), print_esc_string(), print_formatted(), strcpy_and_process_escape_sequences(), and unescape().
strcpy_and_process_escape_sequences()
char* FAST_FUNC strcpy_and_process_escape_sequences (char * dst, const char * src)
Definition at line 105 of file process_escape_sequence.c.
 {
     while (1) {
         char c, c1;
         c = c1 = *src++;
         if (c1 == '\\')
             c1 = bb_process_escape_sequence(&src);
         *dst = c1;
         if (c == '\0')
             return dst;
         dst++;
     }
 }
References bb_process_escape_sequence(), c, dst, and src.
Referenced by bb_dump_add(), config_read(), parse_args(), and paste_main().