Fennix: Userspace/apps/base/bash/input.c File Reference
input.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "filecntl.h"
#include "posixstat.h"
#include <stdio.h>
#include <errno.h>
#include "bashansi.h"
#include "bashintl.h"
#include "shell.h"
#include "input.h"
#include "externs.h"
#include "trap.h"
Macros
#define X_EAGAIN -99
#define X_EWOULDBLOCK -99
Functions
void termsig_handler PARAMS ((int))
int getc_with_restart (FILE *stream)
int ungetc_with_restart (int c, FILE *stream)
Variables
int errno
static char localbuf [1024]
static int local_index = 0
static int local_bufused = 0
Macro Definition Documentation
X_EAGAIN
#define X_EAGAIN -99
Definition at line 51 of file input.c.
X_EWOULDBLOCK
#define X_EWOULDBLOCK -99
Definition at line 57 of file input.c.
Function Documentation
getc_with_restart()
int getc_with_restart (FILE * stream)
Definition at line 72 of file input.c.
 {
   unsigned char uc;
   CHECK_TERMSIG;
   /* Try local buffering to reduce the number of read(2) calls. */
   if (local_index == local_bufused || local_bufused == 0)
     {
       while (1)
     {
       QUIT;
       run_pending_traps ();
       local_bufused = read (fileno (stream), localbuf, sizeof(localbuf));
       if (local_bufused > 0)
         break;
       else if (local_bufused == 0)
         {
           local_index = 0;
           return EOF;
         }
       else if (errno == X_EAGAIN || errno == X_EWOULDBLOCK)
         {
           if (sh_unset_nodelay_mode (fileno (stream)) < 0)
         {
           sys_error (_("cannot reset nodelay mode for fd %d"), fileno (stream));
           local_index = local_bufused = 0;
           return EOF;
         }
           continue;
         }
       else if (errno != EINTR)
         {
           local_index = local_bufused = 0;
           return EOF;
         }
       else if (interrupt_state || terminating_signal)   /* QUIT; */
         local_index = local_bufused = 0;
     }
       local_index = 0;
     }
   uc = localbuf[local_index++];
   return uc;
 }
References _, CHECK_TERMSIG, EINTR, EOF, errno, fileno(), interrupt_state, local_bufused, local_index, localbuf, QUIT, read(), run_pending_traps(), sh_unset_nodelay_mode(), sys_error(), terminating_signal, X_EAGAIN, and X_EWOULDBLOCK.
Referenced by yy_stream_get().
PARAMS()
void termsig_handler PARAMS ((int))
ungetc_with_restart()
int ungetc_with_restart (int c, FILE * stream)
Definition at line 120 of file input.c.
 {
   if (local_index == 0 || c == EOF)
     return EOF;
   localbuf[--local_index] = c;
   return c;
 }
References c, EOF, local_index, and localbuf.
Referenced by yy_stream_unget().
Variable Documentation
errno
int errno extern
Referenced by _rl_nchars_available(), getc_with_restart(), rl_gather_tyi(), rl_getc(), rl_read_key(), and rl_timeout_remaining().
local_bufused
int local_bufused = 0 static
Definition at line 66 of file input.c.
Referenced by getc_with_restart().
local_index
int local_index = 0 static
Definition at line 66 of file input.c.
Referenced by get_history_event(), getc_with_restart(), history_get(), and ungetc_with_restart().
localbuf
char localbuf[1024] static
Definition at line 65 of file input.c.
Referenced by getc_with_restart(), and ungetc_with_restart().