Fennix Kernel: UniversalAsynchronousReceiverTransmitter::UART Class Reference
UniversalAsynchronousReceiverTransmitter::UART Class Reference
#include <uart.hpp>
Public Member Functions
UART (SerialPorts Port=COMNULL)
~UART ()
void Write (uint8_t Char)
uint8_t Read ()
Private Attributes
SerialPorts Port
bool IsAvailable
Detailed Description
Definition at line 41 of file uart.hpp.
Constructor & Destructor Documentation
UART()
SafeFunction NIF UniversalAsynchronousReceiverTransmitter::UART::UART (SerialPorts Port = COMNULL)
Definition at line 57 of file uart.cpp.
     {
 #if defined(a86)
         if (Port == COMNULL)
             return;
         uint8_t com = NoProfiler_inportb(Port);
         if (com == 0xFF)
         {
             error("Serial port %#lx is not available.", Port);
             return;
         }
         this->Port = Port;
         int PortNumber = 0;
         switch (Port)
         {
         case COM1:
             PortNumber = 0;
             break;
         case COM2:
             PortNumber = 1;
             break;
         case COM3:
             PortNumber = 2;
             break;
         case COM4:
             PortNumber = 3;
             break;
         case COM5:
             PortNumber = 4;
             break;
         case COM6:
             PortNumber = 5;
             break;
         case COM7:
             PortNumber = 6;
             break;
         case COM8:
             PortNumber = 7;
             break;
         default:
             return;
         }
         if (serialports[PortNumber])
             return;
         // Initialize the serial port
         NoProfiler_outportb(s_cst(uint16_t, Port + 1), 0x00);                  // Disable all interrupts
         NoProfiler_outportb(s_cst(uint16_t, Port + 3), SERIAL_ENABLE_DLAB);    // Enable DLAB (set baud rate divisor)
         NoProfiler_outportb(s_cst(uint16_t, Port + 0), SERIAL_RATE_115200_LO); // Set divisor to 1 (lo byte) 115200 baud
         NoProfiler_outportb(s_cst(uint16_t, Port + 1), SERIAL_RATE_115200_HI); //                  (hi byte)
         NoProfiler_outportb(s_cst(uint16_t, Port + 3), 0x03);                  // 8 bits, no parity, one stop bit
         NoProfiler_outportb(s_cst(uint16_t, Port + 2), 0xC7);                  // Enable FIFO, clear them, with 14-byte threshold
         NoProfiler_outportb(s_cst(uint16_t, Port + 4), 0x0B);                  // IRQs enabled, RTS/DSR set
         /* FIXME  https://wiki.osdev.org/Serial_Ports */
         // NoProfiler_outportb(s_cst(uint16_t, Port + 0), 0x1E);
         // NoProfiler_outportb(s_cst(uint16_t, Port + 0), 0xAE);
         // Check if the serial port is faulty.
         // if (NoProfiler_inportb(s_cst(uint16_t, Port + 0)) != 0xAE)
         // {
         //     static int once = 0;
         //     if (!once++)
         //         warn("Serial port %#lx is faulty.", Port);
         //     // serialports[Port] = false; // ignore for now
         //     // return;
         // }
         // Set to normal operation mode.
         NoProfiler_outportb(s_cst(uint16_t, Port + 4), 0x0F);
         serialports[PortNumber] = true;
         this->IsAvailable = true;
 #endif
     }
References UniversalAsynchronousReceiverTransmitter::COM1, UniversalAsynchronousReceiverTransmitter::COM2, UniversalAsynchronousReceiverTransmitter::COM3, UniversalAsynchronousReceiverTransmitter::COM4, UniversalAsynchronousReceiverTransmitter::COM5, UniversalAsynchronousReceiverTransmitter::COM6, UniversalAsynchronousReceiverTransmitter::COM7, UniversalAsynchronousReceiverTransmitter::COM8, UniversalAsynchronousReceiverTransmitter::COMNULL, error, IsAvailable, Port, SERIAL_ENABLE_DLAB, SERIAL_RATE_115200_HI, SERIAL_RATE_115200_LO, and serialports.
~UART()
SafeFunction NIF UniversalAsynchronousReceiverTransmitter::UART::~UART ()
Definition at line 135 of file uart.cpp.
 {}
Member Function Documentation
Read()
SafeFunction NIF uint8_t UniversalAsynchronousReceiverTransmitter::UART::Read ()
Definition at line 151 of file uart.cpp.
     {
         if (!this->IsAvailable)
             return 0;
 #if defined(a86)
         while ((NoProfiler_inportb(s_cst(uint16_t, Port + 5)) & 1) == 0)
             ;
         return NoProfiler_inportb(Port);
 #endif
         foreach (auto e in RegisteredEvents)
         {
             if (e->GetRegisteredPort() == Port || e->GetRegisteredPort() == COMNULL)
             {
 #if defined(a86)
                 e->OnReceived(NoProfiler_inportb(Port));
 #endif
             }
         }
     }
References UniversalAsynchronousReceiverTransmitter::COMNULL, IsAvailable, Port, and RegisteredEvents.
Write()
SafeFunction NIF void UniversalAsynchronousReceiverTransmitter::UART::Write (uint8_t Char)
Definition at line 137 of file uart.cpp.
     {
         if (!this->IsAvailable)
             return;
 #if defined(a86)
         while ((NoProfiler_inportb(s_cst(uint16_t, Port + 5)) & SERIAL_BUFFER_EMPTY) == 0)
             ;
         NoProfiler_outportb(Port, Char);
 #endif
         foreach (auto e in RegisteredEvents)
             if (e->GetRegisteredPort() == Port || e->GetRegisteredPort() == COMNULL)
                 e->OnSent(Char);
     }
References UniversalAsynchronousReceiverTransmitter::COMNULL, IsAvailable, Port, RegisteredEvents, and SERIAL_BUFFER_EMPTY.
Referenced by gcov_uart_wrapper(), gprof_uart_wrapper(), profiler_uart_wrapper(), putchar(), and CrashHandler::UserInput().
Field Documentation
IsAvailable
bool UniversalAsynchronousReceiverTransmitter::UART::IsAvailable private
Definition at line 45 of file uart.hpp.
Referenced by Read(), UART(), and Write().
Port
SerialPorts UniversalAsynchronousReceiverTransmitter::UART::Port private
Definition at line 44 of file uart.hpp.
Referenced by Read(), UART(), and Write().
The documentation for this class was generated from the following files:
Kernel/include/uart.hpp
Kernel/core/uart.cpp