Fennix Userspace: Userspace/apps/base/busybox/loginutils/addgroup.c File Reference
addgroup.c File Reference
#include "libbb.h"
Macros
#define OPT_GID (1 << 0)
#define OPT_SYSTEM_ACCOUNT (1 << 1)
Functions
static void xgroup_study (struct group *g)
static void new_group (char *group, gid_t gid)
int addgroup_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char addgroup_longopts[] ALIGN1
Macro Definition Documentation
OPT_GID
#define OPT_GID (1 << 0)
Definition at line 47 of file addgroup.c.
OPT_SYSTEM_ACCOUNT
#define OPT_SYSTEM_ACCOUNT (1 << 1)
Definition at line 48 of file addgroup.c.
Function Documentation
addgroup_main()
int addgroup_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 143 of file addgroup.c.
 {
 #if ENABLE_FEATURE_ADDUSER_TO_GROUP
     unsigned opts;
 #endif
     const char *gid = "0";
     /* need to be root */
     if (geteuid()) {
         bb_simple_error_msg_and_die(bb_msg_perm_denied_are_you_root);
     }
     /* Syntax:
      *  addgroup group
      *  addgroup --gid num group
      *  addgroup user group
      * Check for min, max and missing args */
 #if ENABLE_FEATURE_ADDUSER_TO_GROUP
     opts =
 #endif
     getopt32long(argv, "^" "g:S" "\0" "-1:?2", addgroup_longopts,
                 &gid
     );
     /* move past the commandline options */
     argv += optind;
     //argc -= optind;
 #if ENABLE_FEATURE_ADDUSER_TO_GROUP
     if (argv[1]) {
         struct group *gr;
         if (opts & OPT_GID) {
             /* -g was there, but "addgroup -g num user group"
              * is a no-no */
             bb_show_usage();
         }
         /* check if group and user exist */
         xuname2uid(argv[0]); /* unknown user: exit */
         gr = xgetgrnam(argv[1]); /* unknown group: exit */
         /* check if user is already in this group */
         for (; *(gr->gr_mem) != NULL; (gr->gr_mem)++) {
             if (strcmp(argv[0], *(gr->gr_mem)) == 0) {
                 /* user is already in group: do nothing */
                 return EXIT_SUCCESS;
             }
         }
         if (update_passwd(bb_path_group_file, argv[1], NULL, argv[0]) < 0) {
             return EXIT_FAILURE;
         }
 # if ENABLE_FEATURE_SHADOWPASSWDS
         update_passwd(bb_path_gshadow_file, argv[1], NULL, argv[0]);
 # endif
     } else
 #endif /* ENABLE_FEATURE_ADDUSER_TO_GROUP */
     {
         die_if_bad_username(argv[0]);
         new_group(argv[0], xatou_range(gid, 0, CONFIG_LAST_ID));
     }
     /* Reached only on success */
     return EXIT_SUCCESS;
 }
References argv, bb_path_group_file, bb_path_gshadow_file, bb_show_usage(), bb_simple_error_msg_and_die(), die_if_bad_username(), EXIT_FAILURE, EXIT_SUCCESS, geteuid, getopt32long, gr, group::gr_mem, new_group(), NULL, OPT_GID, optind, strcmp, update_passwd, xgetgrnam(), and xuname2uid().
new_group()
static void new_group (char * group, gid_t gid) static
Definition at line 92 of file addgroup.c.
 {
     struct group gr;
     char *p;
     /* make sure gid and group haven't already been allocated */
     gr.gr_gid = gid;
     gr.gr_name = group;
     xgroup_study(&gr);
     /* add entry to group */
     p = xasprintf("x:%u:", (unsigned) gr.gr_gid);
     if (update_passwd(bb_path_group_file, group, p, NULL) < 0)
         exit(EXIT_FAILURE);
     if (ENABLE_FEATURE_CLEAN_UP)
         free(p);
 #if ENABLE_FEATURE_SHADOWPASSWDS
     /* /etc/gshadow fields:
      * 1. Group name.
      * 2. Encrypted password.
      *    If set, non-members of the group can join the group
      *    by typing the password for that group using the newgrp command.
      *    If the value is of this field ! then no user is allowed
      *    to access the group using the newgrp command. A value of !!
      *    is treated the same as a value of ! only it indicates
      *    that a password has never been set before. If the value is null,
      *    only group members can log into the group.
      * 3. Group administrators (comma delimited list).
      *    Group members listed here can add or remove group members
      *    using the gpasswd command.
      * 4. Group members (comma delimited list).
      */
     /* Ignore errors: if file is missing we assume admin doesn't want it */
     update_passwd(bb_path_gshadow_file, group, "!::", NULL);
 #endif
 }
References bb_path_group_file, bb_path_gshadow_file, exit(), EXIT_FAILURE, free, gr, group::gr_gid, group::gr_name, NULL, p, update_passwd, xasprintf(), and xgroup_study().
Referenced by addgroup_main(), and copy_group_command().
xgroup_study()
static void xgroup_study (struct group * g) static
Definition at line 50 of file addgroup.c.
 {
     unsigned max = CONFIG_LAST_ID;
     /* Make sure gr_name is unused */
     if (getgrnam(g->gr_name)) {
         bb_error_msg_and_die("%s '%s' in use", "group", g->gr_name);
         /* these format strings are reused in adduser and addgroup */
     }
     /* if a specific gid is requested, the --system switch and */
     /* min and max values are overridden, and the range of valid */
     /* gid values is set to [0, INT_MAX] */
     if (!(option_mask32 & OPT_GID)) {
         if (option_mask32 & OPT_SYSTEM_ACCOUNT) {
             g->gr_gid = CONFIG_FIRST_SYSTEM_ID;
             max = CONFIG_LAST_SYSTEM_ID;
         } else {
             g->gr_gid = CONFIG_LAST_SYSTEM_ID + 1;
         }
     }
     /* Check if the desired gid is free
      * or find the first free one */
     while (1) {
         if (!getgrgid(g->gr_gid)) {
             return; /* found free group: return */
         }
         if (option_mask32 & OPT_GID) {
             /* -g N, cannot pick gid other than N: error */
             bb_error_msg_and_die("%s '%s' in use", "gid", itoa(g->gr_gid));
             /* this format strings is reused in adduser and addgroup */
         }
         if (g->gr_gid == max) {
             /* overflowed: error */
             bb_error_msg_and_die("no %cids left", 'g');
             /* this format string is reused in adduser and addgroup */
         }
         g->gr_gid++;
     }
 }
References bb_error_msg_and_die(), g, getgrgid, getgrnam, itoa, max, OPT_GID, OPT_SYSTEM_ACCOUNT, and option_mask32.
Referenced by new_group().
Variable Documentation
ALIGN1
const char addgroup_longopts [] ALIGN1 static
Initial value:
=
        "gid\0"                 Required_argument "g"
        "system\0"              No_argument       "S"
Definition at line 130 of file addgroup.c.