Fennix Userspace: Userspace/apps/base/busybox/util-linux/nsenter.c File Reference
nsenter.c File Reference
#include <sched.h>
#include "libbb.h"
Data Structures
struct namespace_descr
struct namespace_ctx
Macros
#define CLONE_NEWUTS 0x04000000
#define CLONE_NEWIPC 0x08000000
#define CLONE_NEWUSER 0x10000000
#define CLONE_NEWPID 0x20000000
#define CLONE_NEWNET 0x40000000
Enumerations
enum {
OPT_user = 1 << 0 , OPT_ipc = 1 << 1 , OPT_uts = 1 << 2 , OPT_network = 1 << 3 ,
OPT_pid = 1 << 4 , OPT_mount = 1 << 5 , OPT_target = 1 << 6 , OPT_setuid = 1 << 7 ,
OPT_setgid = 1 << 8 , OPT_root = 1 << 9 , OPT_wd = 1 << 10 , OPT_nofork = 1 << 11 ,
OPT_prescred = (1 << 12) * ENABLE_LONG_OPTS
}
enum {
NS_USR_POS = 0 , NS_IPC_POS , NS_UTS_POS , NS_NET_POS ,
NS_PID_POS , NS_MNT_POS , NS_COUNT
}
Functions
static int open_by_path_or_target (const char *path, pid_t target_pid, const char *target_file)
int nsenter_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const struct namespace_descr ns_list[] ALIGN_INT
static const char opt_str[] ALIGN1 = "+""U::i::u::n::p::m::""t:+S:+G:+r::w::F"
Data Structure Documentation
namespace_descr
struct namespace_descr
Definition at line 57 of file nsenter.c.
Data Fields
int flag
char ns_nsfile8[8]
const char nsfile4[4]
namespace_ctx
struct namespace_ctx
Definition at line 62 of file nsenter.c.
Data Fields
int fd
char * path
Macro Definition Documentation
CLONE_NEWIPC
#define CLONE_NEWIPC 0x08000000
Definition at line 43 of file nsenter.c.
CLONE_NEWNET
#define CLONE_NEWNET 0x40000000
Definition at line 52 of file nsenter.c.
CLONE_NEWPID
#define CLONE_NEWPID 0x20000000
Definition at line 49 of file nsenter.c.
CLONE_NEWUSER
#define CLONE_NEWUSER 0x10000000
Definition at line 46 of file nsenter.c.
CLONE_NEWUTS
#define CLONE_NEWUTS 0x04000000
Definition at line 40 of file nsenter.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_user
OPT_ipc
OPT_uts
OPT_network
OPT_pid
OPT_mount
OPT_target
OPT_setuid
OPT_setgid
OPT_root
OPT_wd
OPT_nofork
OPT_prescred
Definition at line 67 of file nsenter.c.
      {
     OPT_user    = 1 << 0,
     OPT_ipc     = 1 << 1,
     OPT_uts     = 1 << 2,
     OPT_network = 1 << 3,
     OPT_pid     = 1 << 4,
     OPT_mount   = 1 << 5,
     OPT_target  = 1 << 6,
     OPT_setuid  = 1 << 7,
     OPT_setgid  = 1 << 8,
     OPT_root    = 1 << 9,
     OPT_wd      = 1 << 10,
     OPT_nofork  = 1 << 11,
     OPT_prescred    = (1 << 12) * ENABLE_LONG_OPTS,
 };
anonymous enum
anonymous enum
Enumerator
NS_USR_POS
NS_IPC_POS
NS_UTS_POS
NS_NET_POS
NS_PID_POS
NS_MNT_POS
NS_COUNT
Definition at line 82 of file nsenter.c.
      {
     NS_USR_POS = 0,
     NS_IPC_POS,
     NS_UTS_POS,
     NS_NET_POS,
     NS_PID_POS,
     NS_MNT_POS,
     NS_COUNT,
 };
Function Documentation
nsenter_main()
int nsenter_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 155 of file nsenter.c.
 {
     int i;
     unsigned int opts;
     const char *root_dir_str = NULL;
     const char *wd_str = NULL;
     struct namespace_ctx ns_ctx_list[NS_COUNT];
     int setgroups_failed;
     int root_fd, wd_fd;
     int target_pid = 0;
     int uid = 0;
     int gid = 0;
     memset(ns_ctx_list, 0, sizeof(ns_ctx_list));
     opts = getopt32long(argv, opt_str, nsenter_longopts,
             &ns_ctx_list[NS_USR_POS].path,
             &ns_ctx_list[NS_IPC_POS].path,
             &ns_ctx_list[NS_UTS_POS].path,
             &ns_ctx_list[NS_NET_POS].path,
             &ns_ctx_list[NS_PID_POS].path,
             &ns_ctx_list[NS_MNT_POS].path,
             &target_pid, &uid, &gid,
             &root_dir_str, &wd_str
     );
     argv += optind;
     root_fd = wd_fd = -1;
     if (opts & OPT_root)
         root_fd = open_by_path_or_target(root_dir_str,
                          target_pid, "root");
     if (opts & OPT_wd)
         wd_fd = open_by_path_or_target(wd_str, target_pid, "cwd");
     for (i = 0; i < NS_COUNT; i++) {
         const struct namespace_descr *ns = &ns_list[i];
         struct namespace_ctx *ns_ctx = &ns_ctx_list[i];
         ns_ctx->fd = -1;
         if (opts & (1 << i))
             ns_ctx->fd = open_by_path_or_target(ns_ctx->path,
                     target_pid, ns->ns_nsfile8);
     }
     /*
      * Entering the user namespace without --preserve-credentials implies
      * --setuid & --setgid and clearing root's groups.
      */
     setgroups_failed = 0;
     if ((opts & OPT_user) && !(opts & OPT_prescred)) {
         opts |= (OPT_setuid | OPT_setgid);
         /*
          * We call setgroups() before and after setns() and only
          * bail-out if it fails twice.
          */
         setgroups_failed = (setgroups(0, NULL) < 0);
     }
     for (i = 0; i < NS_COUNT; i++) {
         const struct namespace_descr *ns = &ns_list[i];
         struct namespace_ctx *ns_ctx = &ns_ctx_list[i];
         if (ns_ctx->fd < 0)
             continue;
         if (setns(ns_ctx->fd, ns->flag)) {
             bb_perror_msg_and_die(
                 "setns(): can't reassociate to namespace '%s'",
                 ns->ns_nsfile8 + 3 /* skip over "ns/" */
             );
         }
         close(ns_ctx->fd); /* should close fds, to not confuse exec'ed PROG */
         /*ns_ctx->fd = -1;*/
     }
     if (root_fd >= 0) {
         if (wd_fd < 0) {
             /*
              * Save the current working directory if we're not
              * changing it.
              */
             wd_fd = xopen(".", O_RDONLY);
         }
         xfchdir(root_fd);
         xchroot(".");
         close(root_fd);
         /*root_fd = -1;*/
     }
     if (wd_fd >= 0) {
         xfchdir(wd_fd);
         close(wd_fd);
         /*wd_fd = -1;*/
     }
     /*
      * Entering the pid namespace implies forking unless it's been
      * explicitly requested by the user not to.
      */
     if (!(opts & OPT_nofork) && (opts & OPT_pid)) {
         xvfork_parent_waits_and_exits();
         /* Child continues */
     }
     if (opts & OPT_setgid) {
         if (setgroups(0, NULL) < 0 && setgroups_failed)
             bb_simple_perror_msg_and_die("setgroups");
         xsetgid(gid);
     }
     if (opts & OPT_setuid)
         xsetuid(uid);
     exec_prog_or_SHELL(argv);
 }
References argv, bb_perror_msg_and_die(), bb_simple_perror_msg_and_die(), close(), exec_prog_or_SHELL(), namespace_ctx::fd, namespace_descr::flag, getopt32long, i, memset(), NS_COUNT, NS_IPC_POS, NS_MNT_POS, NS_NET_POS, namespace_descr::ns_nsfile8, NS_PID_POS, NS_USR_POS, NS_UTS_POS, NULL, O_RDONLY, open_by_path_or_target(), OPT_nofork, OPT_pid, OPT_prescred, OPT_root, OPT_setgid, OPT_setuid, OPT_user, OPT_wd, optind, namespace_ctx::path, setgroups(), setns(), xchroot(), xfchdir(), xopen(), xsetgid(), xsetuid(), and xvfork_parent_waits_and_exits().
open_by_path_or_target()
static int open_by_path_or_target (const char * path, pid_t target_pid, const char * target_file) static
Definition at line 134 of file nsenter.c.
 {
     char proc_path_buf[sizeof("/proc/%u/1234567890") + sizeof(int)*3];
     if (!path) {
         if (target_pid == 0) {
             /* Example:
              * "nsenter -p PROG" - neither -pFILE nor -tPID given.
              */
             bb_show_usage();
         }
         snprintf(proc_path_buf, sizeof(proc_path_buf),
              "/proc/%u/%s", (unsigned)target_pid, target_file);
         path = proc_path_buf;
     }
     return xopen(path, O_RDONLY);
 }
References bb_show_usage(), O_RDONLY, snprintf(), and xopen().
Referenced by nsenter_main().
Variable Documentation
ALIGN1
const char opt_str [] ALIGN1 = "+""U::i::u::n::p::m::""t:+S:+G:+r::w::F" static
Definition at line 108 of file nsenter.c.
ALIGN_INT
const struct namespace_descr ns_list [] ALIGN_INT static
Initial value:
= {
    { CLONE_NEWUSER, "ns/user", },
    { CLONE_NEWIPC,  "ns/ipc",  },
    { CLONE_NEWUTS,  "ns/uts",  },
    { CLONE_NEWNET,  "ns/net",  },
    { CLONE_NEWPID,  "ns/pid",  },
    { CLONE_NEWNS,   "ns/mnt",  },
}
Definition at line 96 of file nsenter.c.