Fennix Userspace: Userspace/musl/src/process/execlp.c File Reference
execlp.c File Reference
#include <unistd.h>
#include <stdarg.h>
Functions
int execlp (const char *file, const char *argv0,...)
Function Documentation
execlp()
int execlp (const char * file, const char * argv0, ...)
Definition at line 4 of file execlp.c.
 {
     int argc;
     va_list ap;
     va_start(ap, argv0);
     for (argc=1; va_arg(ap, const char *); argc++);
     va_end(ap);
     {
         int i;
         char *argv[argc+1];
         va_start(ap, argv0);
         argv[0] = (char *)argv0;
         for (i=1; i<argc; i++)
             argv[i] = va_arg(ap, char *);
         argv[i] = NULL;
         va_end(ap);
         return execvp(file, argv);
     }
 }
References ap, argc, argv, ENOSYS, errno, execvp(), i, NULL, va_arg, va_end, and va_start.
Referenced by halt_main(), and runsv().