Fennix: Userspace/apps/base/busybox/networking/libiproute/ll_map.c File Reference
ll_map.c File Reference
#include <net/if.h>
#include "libbb.h"
#include "libnetlink.h"
#include "ll_map.h"
Data Structures
struct idxmap
Functions
static struct idxmap * find_by_index (int idx)
int FAST_FUNC ll_remember_index (const struct sockaddr_nl *who UNUSED_PARAM, struct nlmsghdr *n, void *arg UNUSED_PARAM)
static const char FAST_FUNC * ll_idx_n2a (int idx)
const char FAST_FUNC * ll_index_to_name (int idx)
unsigned FAST_FUNC ll_index_to_flags (int idx)
int FAST_FUNC xll_name_to_index (const char *name)
int FAST_FUNC ll_init_map (struct rtnl_handle *rth)
Variables
static struct idxmap ** idxmap
Data Structure Documentation
idxmap
struct idxmap
Definition at line 16 of file ll_map.c.
Data Fields
unsigned char addr[8]
int alen
unsigned flags
int index
char name[16]
struct idxmap * next
int type
Function Documentation
find_by_index()
static struct idxmap* find_by_index (int idx) static
Definition at line 28 of file ll_map.c.
 {
     struct idxmap *im;
     if (idxmap)
         for (im = idxmap[idx & 0xF]; im; im = im->next)
             if (im->index == idx)
                 return im;
     return NULL;
 }
References idx, idxmap::index, idxmap::next, and NULL.
Referenced by ll_idx_n2a(), and ll_index_to_flags().
ll_idx_n2a()
static const char FAST_FUNC* ll_idx_n2a (int idx) static
Definition at line 89 of file ll_map.c.
 {
     struct idxmap *im;
     if (idx == 0)
         return "*";
     im = find_by_index(idx);
     if (im)
         return im->name;
     //snprintf(buf, 16, "if%d", idx);
     //return buf;
     return auto_string(xasprintf("if%d", idx));
 }
References auto_string(), find_by_index(), idx, idxmap::name, and xasprintf().
Referenced by ll_index_to_name().
ll_index_to_flags()
unsigned FAST_FUNC ll_index_to_flags (int idx)
Definition at line 123 of file ll_map.c.
 {
     struct idxmap *im;
     if (idx == 0)
         return 0;
     im = find_by_index(idx);
     if (im)
         return im->flags;
     return 0;
 }
References find_by_index(), idxmap::flags, and idx.
Referenced by print_linkinfo().
ll_index_to_name()
const char FAST_FUNC* ll_index_to_name (int idx)
Definition at line 103 of file ll_map.c.
 {
     //static char nbuf[16];
     return ll_idx_n2a(idx/*, nbuf*/);
 }
References idx, and ll_idx_n2a().
Referenced by ipaddr_list_or_flush(), print_addrinfo(), print_class(), print_linkinfo(), print_neigh(), print_qdisc(), and print_route().
ll_init_map()
int FAST_FUNC ll_init_map (struct rtnl_handle * rth)
Definition at line 173 of file ll_map.c.
 {
     xrtnl_wilddump_request(rth, AF_UNSPEC, RTM_GETLINK);
     xrtnl_dump_filter(rth, ll_remember_index, NULL);
     return 0;
 }
References AF_UNSPEC, ll_remember_index(), NULL, RTM_GETLINK, xrtnl_dump_filter(), and xrtnl_wilddump_request().
Referenced by do_add_or_delete(), ipaddr_modify(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), and tc_main().
ll_remember_index()
int FAST_FUNC ll_remember_index (const struct sockaddr_nl *who UNUSED_PARAM, struct nlmsghdr * n, void *arg UNUSED_PARAM)
Definition at line 39 of file ll_map.c.
 {
     int h;
     struct ifinfomsg *ifi = NLMSG_DATA(n);
     struct idxmap *im, **imp;
     struct rtattr *tb[IFLA_MAX+1];
     if (n->nlmsg_type != RTM_NEWLINK)
         return 0;
     if (n->nlmsg_len < NLMSG_LENGTH(sizeof(ifi)))
         return -1;
     //memset(tb, 0, sizeof(tb)); - parse_rtattr does this
     parse_rtattr(tb, IFLA_MAX, IFLA_RTA(ifi), IFLA_PAYLOAD(n));
     if (tb[IFLA_IFNAME] == NULL)
         return 0;
     if (!idxmap)
         idxmap = xzalloc(sizeof(idxmap[0]) * 16);
     h = ifi->ifi_index & 0xF;
     for (imp = &idxmap[h]; (im = *imp) != NULL; imp = &im->next)
         if (im->index == ifi->ifi_index)
             goto found;
     im = xmalloc(sizeof(*im));
     im->next = *imp;
     im->index = ifi->ifi_index;
     *imp = im;
  found:
     im->type = ifi->ifi_type;
     im->flags = ifi->ifi_flags;
     if (tb[IFLA_ADDRESS]) {
         int alen;
         im->alen = alen = RTA_PAYLOAD(tb[IFLA_ADDRESS]);
         if (alen > (int)sizeof(im->addr))
             alen = sizeof(im->addr);
         memcpy(im->addr, RTA_DATA(tb[IFLA_ADDRESS]), alen);
     } else {
         im->alen = 0;
         memset(im->addr, 0, sizeof(im->addr));
     }
     strcpy(im->name, RTA_DATA(tb[IFLA_IFNAME]));
     return 0;
 }
References idxmap::addr, idxmap::alen, idxmap::flags, found, h, ifinfomsg::ifi_flags, ifinfomsg::ifi_index, ifinfomsg::ifi_type, IFLA_ADDRESS, IFLA_IFNAME, idxmap::index, memcpy, memset, n, idxmap::name, idxmap::next, NLMSG_DATA, NULL, parse_rtattr(), RTA_DATA, RTM_NEWLINK, strcpy, idxmap::type, xmalloc, and xzalloc().
Referenced by ll_init_map(), and store_nlmsg().
xll_name_to_index()
int FAST_FUNC xll_name_to_index (const char * name)
Definition at line 135 of file ll_map.c.
 {
     int ret = 0;
 /* caching is not warranted - no users which repeatedly call it */
 #ifdef UNUSED
     static char ncache[16];
     static int icache;
     struct idxmap *im;
     int i;
     if (name == NULL)
         goto out;
     if (icache && strcmp(name, ncache) == 0) {
         ret = icache;
         goto out;
     }
     if (idxmap) {
         for (i = 0; i < 16; i++) {
             for (im = idxmap[i]; im; im = im->next) {
                 if (strcmp(im->name, name) == 0) {
                     icache = im->index;
                     strcpy(ncache, name);
                     ret = im->index;
                     goto out;
                 }
             }
         }
     }
 #endif
     ret = if_nametoindex(name);
 /* out:*/
     if (ret <= 0)
         bb_error_msg_and_die("can't find device '%s'", name);
     return ret;
 }
References bb_error_msg_and_die(), i, if_nametoindex(), idxmap::index, idxmap::name, idxmap::next, NULL, out(), strcmp, and strcpy.
Referenced by do_add_or_delete(), do_set(), ipaddr_list_or_flush(), ipaddr_modify(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), set_master(), set_netns(), and tc_main().
Variable Documentation
idxmap
struct idxmap** idxmap static
Definition at line 26 of file ll_map.c.