Fennix: Userspace/apps/base/busybox/libbb/pw_encrypt_md5.c File Reference
pw_encrypt_md5.c File Reference
Macros
#define MD5_OUT_BUFSIZE 36
Functions
static char *NOINLINE md5_crypt (char result[MD5_OUT_BUFSIZE], const unsigned char *pw, const unsigned char *salt)
Macro Definition Documentation
MD5_OUT_BUFSIZE
#define MD5_OUT_BUFSIZE 36
Definition at line 73 of file pw_encrypt_md5.c.
Function Documentation
md5_crypt()
static char* NOINLINE md5_crypt (char result[MD5_OUT_BUFSIZE], const unsigned char * pw, const unsigned char * salt) static
Definition at line 76 of file pw_encrypt_md5.c.
 {
     char *p;
     unsigned char final[17]; /* final[16] exists only to aid in looping */
     int sl, pl, i, pw_len;
     md5_ctx_t ctx, ctx1;
     /* NB: in busybox, "$1$" in salt is always present */
     /* Refine the Salt first */
     /* Get the length of the salt including "$1$" */
     sl = 3;
     while (sl < (3 + 8) && salt[sl] && salt[sl] != '$')
         sl++;
     /* Hash. the password first, since that is what is most unknown */
     md5_begin(&ctx);
     pw_len = strlen((char*)pw);
     md5_hash(&ctx, pw, pw_len);
     /* Then the salt including "$1$" */
     md5_hash(&ctx, salt, sl);
     /* Copy salt to result; skip "$1$" */
     memcpy(result, salt, sl);
     result[sl] = '$';
     salt += 3;
     sl -= 3;
     /* Then just as many characters of the MD5(pw, salt, pw) */
     md5_begin(&ctx1);
     md5_hash(&ctx1, pw, pw_len);
     md5_hash(&ctx1, salt, sl);
     md5_hash(&ctx1, pw, pw_len);
     md5_end(&ctx1, final);
     for (pl = pw_len; pl > 0; pl -= 16)
         md5_hash(&ctx, final, pl > 16 ? 16 : pl);
     /* Then something really weird... */
     memset(final, 0, sizeof(final));
     for (i = pw_len; i; i >>= 1) {
         md5_hash(&ctx, ((i & 1) ? final : (const unsigned char *) pw), 1);
     }
     md5_end(&ctx, final);
     /* And now, just to make sure things don't run too fast.
      * On a 60 Mhz Pentium this takes 34 msec, so you would
      * need 30 seconds to build a 1000 entry dictionary...
      */
     for (i = 0; i < 1000; i++) {
         md5_begin(&ctx1);
         if (i & 1)
             md5_hash(&ctx1, pw, pw_len);
         else
             md5_hash(&ctx1, final, 16);
         if (i % 3)
             md5_hash(&ctx1, salt, sl);
         if (i % 7)
             md5_hash(&ctx1, pw, pw_len);
         if (i & 1)
             md5_hash(&ctx1, final, 16);
         else
             md5_hash(&ctx1, pw, pw_len);
         md5_end(&ctx1, final);
     }
     p = result + sl + 4; /* 12 bytes max (sl is up to 8 bytes) */
     /* Add 5*4+2 = 22 bytes of hash, + NUL byte. */
     final[16] = final[5];
     for (i = 0; i < 5; i++) {
         unsigned l = (final[i] << 16) | (final[i+6] << 8) | final[i+12];
         p = to64(p, l, 4);
     }
     p = to64(p, final[11], 2);
     *p = '\0';
     /* Don't leave anything around in vm they could use. */
     memset(final, 0, sizeof(final));
     return result;
 }
References ctx, i, l, md5_begin(), md5_end(), md5_hash(), memcpy, memset, p, pw, strlen(), and to64().