Fennix Userspace: Userspace/apps/base/busybox/libbb/wfopen.c File Reference
wfopen.c File Reference
#include "libbb.h"
Functions
FILE *FAST_FUNC fopen_or_warn (const char *path, const char *mode)
FILE *FAST_FUNC fopen_for_read (const char *path)
FILE *FAST_FUNC xfopen_for_read (const char *path)
FILE *FAST_FUNC fopen_for_write (const char *path)
FILE *FAST_FUNC xfopen_for_write (const char *path)
static FILE * xfdopen_helper (unsigned fd_and_rw_bit)
FILE *FAST_FUNC xfdopen_for_read (int fd)
FILE *FAST_FUNC xfdopen_for_write (int fd)
Function Documentation
fopen_for_read()
FILE* FAST_FUNC fopen_for_read (const char * path)
Definition at line 21 of file wfopen.c.
 {
     return fopen(path, "r");
 }
References fopen().
Referenced by add_remove_shell_main(), append_control_file_to_llist(), bootchartd_main(), config_file_action(), create_list(), do_all_in_proc_swaps(), do_pidfile(), evaluate(), file_action_grep(), fileAction(), get_block_backed_filesystems(), get_hz(), get_irqcpu_nr(), get_irqs_from_interrupts(), getgrouplist_internal(), getXXent(), grep_main(), is_hpet_irq(), is_ide_cdrom_or_tape(), man_main(), modprobe_main(), more_main(), parse_conf(), parse_conf_file(), parse_file(), parse_inittab(), parse_map_file(), print_login_issue(), process_cron_update_file(), process_files(), process_timer_stats(), procps_scan(), read_config_file(), read_cstate_counts(), read_iface_state(), rfkill_main(), rtc_adjtime_is_utc(), rtnl_tab_initialize(), and scan_proc_net_or_maps().
fopen_for_write()
FILE* FAST_FUNC fopen_for_write (const char * path)
Definition at line 31 of file wfopen.c.
 {
     return fopen(path, "w");
 }
References fopen().
Referenced by save_input_to_file(), and write_str_to_file().
fopen_or_warn()
FILE* FAST_FUNC fopen_or_warn (const char * path, const char * mode)
Definition at line 11 of file wfopen.c.
 {
     FILE *fp = fopen(path, mode);
     if (!fp) {
         bb_simple_perror_msg(path);
         //errno = 0; /* why? */
     }
     return fp;
 }
References bb_simple_perror_msg(), and fopen().
Referenced by do_tunnels_list(), fopen_or_warn_stdin(), get_next_line(), if_readlist_proc(), klogd_setloglevel(), list_devs_in_proc_partititons(), more_main(), tee_main(), and update_passwd().
xfdopen_for_read()
FILE* FAST_FUNC xfdopen_for_read (int fd)
Definition at line 48 of file wfopen.c.
 {
     return xfdopen_helper(fd << 1);
 }
References fd, and xfdopen_helper().
Referenced by fb_drawimage(), handle_dir_common(), query(), and sendmail_main().
xfdopen_for_write()
FILE* FAST_FUNC xfdopen_for_write (int fd)
Definition at line 52 of file wfopen.c.
 {
     return xfdopen_helper((fd << 1) + 1);
 }
References fd, and xfdopen_helper().
Referenced by convert(), open_new_state_file(), parse(), sed_main(), and update_passwd().
xfdopen_helper()
static FILE* xfdopen_helper (unsigned fd_and_rw_bit) static
Definition at line 41 of file wfopen.c.
 {
     FILE* fp = fdopen(fd_and_rw_bit >> 1, fd_and_rw_bit & 1 ? "w" : "r");
     if (!fp)
         bb_die_memory_exhausted();
     return fp;
 }
References bb_die_memory_exhausted().
Referenced by xfdopen_for_read(), and xfdopen_for_write().
xfopen_for_read()
FILE* FAST_FUNC xfopen_for_read (const char * path)
Definition at line 26 of file wfopen.c.
 {
     return xfopen(path, "r");
 }
References xfopen().
Referenced by arp_show(), bb_displayroutes(), bb_dump_addfile(), convert(), dc_main(), do_disk_statistics(), do_em_all_in_fstab(), do_sethostname(), encode_n_base64(), get_cpu_count(), get_cpu_statistics(), get_irqs_from_stat(), get_list_blocks(), get_smp_uptime(), get_uptime(), index_status_file(), load_modules_dep(), lsmod_main(), modinfo_main(), modprobe_main(), nameif_main(), parse_meminfo(), patch_main(), process_irq_counts(), read_interfaces(), readprofile_main(), reverse(), scriptreplay_main(), setfiles_main(), and write_status_file().
xfopen_for_write()
FILE* FAST_FUNC xfopen_for_write (const char * path)
Definition at line 36 of file wfopen.c.
 {
     return xfopen(path, "w");
 }
References xfopen().
Referenced by do_logging(), finalize(), getty_main(), init(), parse(), patch_main(), popmaildir_main(), script_main(), sed_xfopen_w(), setfiles_main(), unpack_package(), and write_status_file().