Fennix Lynx Bootloader: Memory64::PageDirectoryPointerTableEntry Union Reference
Memory64::PageDirectoryPointerTableEntry Union Reference
#include <memory.hpp>
Public Member Functions
void SetAddress (uintptr_t _Address)
Set PageDirectoryEntryPtr address.
uintptr_t GetAddress ()
Get PageDirectoryEntryPtr address.
Data Fields
struct {
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
uint64_t CacheDisable: 1
uint64_t Accessed: 1
uint64_t Available0: 1
uint64_t PageSize: 1
uint64_t Available1: 4
uint64_t Address: 40
uint64_t Available2: 11
uint64_t ExecuteDisable: 1
};
struct {
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
uint64_t CacheDisable: 1
uint64_t Accessed: 1
uint64_t Dirty: 1
uint64_t PageSize: 1
uint64_t Global: 1
uint64_t Available0: 3
uint64_t PageAttributeTable: 1
uint64_t Reserved0: 17
uint64_t Address: 22
uint64_t Available1: 7
uint64_t ProtectionKey: 4
uint64_t ExecuteDisable: 1
} OneGB
uint64_t raw
Detailed Description
Definition at line 341 of file memory.hpp.
Member Function Documentation
GetAddress()
uintptr_t Memory64::PageDirectoryPointerTableEntry::GetAddress () inline
Get PageDirectoryEntryPtr address.
Definition at line 390 of file memory.hpp.
         {
             return (this->raw & 0x000FFFFFFFFFF000) >> 12;
         }
Referenced by Memory64::Virtual::Check(), Memory64::Virtual::GetPhysical(), Memory64::Virtual::Map(), and Memory64::Virtual::Unmap().
SetAddress()
void Memory64::PageDirectoryPointerTableEntry::SetAddress (uintptr_t _Address) inline
Set PageDirectoryEntryPtr address.
Definition at line 382 of file memory.hpp.
         {
             _Address &= 0x000000FFFFFFFFFF;
             this->raw &= 0xFFF0000000000FFF;
             this->raw |= (_Address << 12);
         }
Referenced by Memory64::Virtual::Map().
Field Documentation
struct { ... }
struct { ... } Memory64::PageDirectoryPointerTableEntry::OneGB
raw
uint64_t Memory64::PageDirectoryPointerTableEntry::raw
Definition at line 379 of file memory.hpp.
Referenced by Memory64::Virtual::Map().
The documentation for this union was generated from the following file:
Lynx/FennixLoader/include/memory.hpp