Fennix: Userspace/mlibc/options/ansi/generic/complex/cephes_subrf.h File Reference
cephes_subrf.h File Reference
Functions
void __mlibc_cchshf (float, float *, float *)
float __mlibc_redupif (float)
float __mlibc_ctansf (float complex)
Function Documentation
__mlibc_cchshf()
void __mlibc_cchshf (float x, float * c, float * s)
Definition at line 42 of file cephes_subrf.c.
 {
     float e, ei;
     if (fabsf(x) <= 0.5f) {
         *c = coshf(x);
         *s = sinhf(x);
     } else {
         e = expf(x);
         ei = 0.5f / e;
         e = 0.5f * e;
         *s = e - ei;
         *c = e + ei;
     }
 }
References c, coshf(), expf(), fabsf(), sinhf(), and x.
Referenced by ccosf(), and csinf().
__mlibc_ctansf()
float __mlibc_ctansf (float complex)
Definition at line 87 of file cephes_subrf.c.
 {
     float f, x, x2, y, y2, rn, t, d;
     x = fabsf(2.0f * crealf(z));
     y = fabsf(2.0f * cimagf(z));
     x = __mlibc_redupif(x);
     x = x * x;
     y = y * y;
     x2 = 1.0f;
     y2 = 1.0f;
     f = 1.0f;
     rn = 0.0f;
     d = 0.0f;
     do {
         rn += 1.0f;
         f *= rn;
         rn += 1.0f;
         f *= rn;
         x2 *= x;
         y2 *= y;
         t = y2 + x2;
         t /= f;
         d += t;
         rn += 1.0f;
         f *= rn;
         rn += 1.0f;
         f *= rn;
         x2 *= x;
         y2 *= y;
         t = y2 - x2;
         t /= f;
         d += t;
     } while (fabsf(t/d) > MACHEPF);
     return d;
 }
References __mlibc_redupif(), cimagf(), crealf(), fabsf(), MACHEPF, x, and y.
Referenced by ctanf().
__mlibc_redupif()
float __mlibc_redupif (float x)
Definition at line 67 of file cephes_subrf.c.
 {
     float t;
     long i;
     t = x / (float)M_PI;
     if (t >= 0.0f)
         t += 0.5f;
     else
         t -= 0.5f;
     i = t;  /* the multiple */
     t = i;
     t = ((x - t * DP1) - t * DP2) - t * DP3;
     return t;
 }
References DP1, DP2, DP3, i, M_PI, and x.
Referenced by __mlibc_ctansf(), and catanf().