Fennix: Userspace/musl/src/ldso/arm/find_exidx.c File Reference
find_exidx.c File Reference
#include <link.h>
#include <stdint.h>
Data Structures
struct find_exidx_data
Macros
#define _GNU_SOURCE
Functions
static int find_exidx (struct dl_phdr_info *info, size_t size, void *ptr)
uintptr_t __gnu_Unwind_Find_exidx (uintptr_t pc, int *pcount)
Data Structure Documentation
find_exidx_data
struct find_exidx_data
Definition at line 5 of file find_exidx.c.
Data Fields
int exidx_len
uintptr_t exidx_start
uintptr_t pc
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file find_exidx.c.
Function Documentation
__gnu_Unwind_Find_exidx()
uintptr_t __gnu_Unwind_Find_exidx (uintptr_t pc, int * pcount)
Definition at line 34 of file find_exidx.c.
 {
     struct find_exidx_data data;
     data.pc = pc;
     if (dl_iterate_phdr(find_exidx, &data) <= 0)
         return 0;
     *pcount = data.exidx_len / 8;
     return data.exidx_start;
 }
References dl_iterate_phdr(), find_exidx_data::exidx_len, find_exidx_data::exidx_start, find_exidx(), and find_exidx_data::pc.
find_exidx()
static int find_exidx (struct dl_phdr_info * info, size_t size, void * ptr) static
Definition at line 10 of file find_exidx.c.
 {
     struct find_exidx_data *data = ptr;
     const ElfW(Phdr) *phdr = info->dlpi_phdr;
     uintptr_t addr, exidx_start = 0;
     int i, match = 0, exidx_len = 0;
     for (i = info->dlpi_phnum; i > 0; i--, phdr++) {
         addr = info->dlpi_addr + phdr->p_vaddr;
         switch (phdr->p_type) {
         case PT_LOAD:
             match |= data->pc >= addr && data->pc < addr + phdr->p_memsz;
             break;
         case PT_ARM_EXIDX:
             exidx_start = addr;
             exidx_len = phdr->p_memsz;
             break;
         }
     }
     data->exidx_start = exidx_start;
     data->exidx_len = exidx_len;
     return match;
 }
References addr, ElfW, find_exidx_data::exidx_len, find_exidx_data::exidx_start, i, info, match(), find_exidx_data::pc, PT_ARM_EXIDX, and PT_LOAD.
Referenced by __gnu_Unwind_Find_exidx().