Fennix Userspace: Queue Struct Reference
Queue Struct Reference
#include <posix-pipe.hpp>
Public Member Functions
Queue ()
Queue (const Queue &)=delete
Queue & operator= (const Queue &)=delete
void recreateQueue ()
HelHandle getQueue ()
void trim ()
ElementHandle dequeueSingle ()
void retire (int n)
void reference (int n)
Queue ()
Queue (const Queue &)=delete
Queue & operator= (const Queue &)=delete
HelHandle getHandle ()
void * dequeueSingle ()
Private Member Functions
int _numberOf (int index)
HelChunk * _retrieveChunk ()
void _wakeHeadFutex ()
void _waitProgressFutex (bool *done)
void _wakeHeadFutex ()
void _waitProgressFutex (bool *done)
Private Attributes
HelHandle _handle
HelQueue * _queue
HelChunk * _chunks [2]
int _retrieveIndex
int _nextIndex
int _lastProgress
int _refCount [2]
HelChunk * _chunk
Detailed Description
Definition at line 70 of file posix-pipe.hpp.
Constructor & Destructor Documentation
Queue() [1/4]
Queue::Queue () inline
Definition at line 71 of file posix-pipe.hpp.
     : _handle{kHelNullHandle} {
         // We do not need to protect those allocations against signals as this constructor
         // is only called during library initialization.
         _chunks[0] = reinterpret_cast<HelChunk *>(getSysdepsAllocator().allocate(sizeof(HelChunk) + 4096));
         _chunks[1] = reinterpret_cast<HelChunk *>(getSysdepsAllocator().allocate(sizeof(HelChunk) + 4096));
         recreateQueue();
     }
References _chunks, getSysdepsAllocator(), and recreateQueue().
Queue() [2/4]
Queue::Queue (const Queue &) delete
Queue() [3/4]
Queue::Queue () inline
Definition at line 45 of file support.cpp.
     : _handle{kHelNullHandle}, _lastProgress(0) {
         HelQueueParameters params {
             .flags = 0,
             .ringShift = 0,
             .numChunks = 1,
             .chunkSize = 4096
         };
         HEL_CHECK(helCreateQueue(&params, &_handle));
         auto chunksOffset = (sizeof(HelQueue) + (sizeof(int) << 0) + 63) & ~size_t(63);
         auto reservedPerChunk = (sizeof(HelChunk) + params.chunkSize + 63) & ~size_t(63);
         auto overallSize = chunksOffset + params.numChunks * reservedPerChunk;
         void *mapping;
         HEL_CHECK(helMapMemory(_handle, kHelNullHandle, nullptr,
                 0, (overallSize + 0xFFF) & ~size_t(0xFFF),
                 kHelMapProtRead | kHelMapProtWrite, &mapping));
         _queue = reinterpret_cast<HelQueue *>(mapping);
         _chunk = reinterpret_cast<HelChunk *>(
                 reinterpret_cast<std::byte *>(mapping) + chunksOffset);
         // Reset and enqueue the first chunk.
         _chunk->progressFutex = 0;
         _queue->indexQueue[0] = 0;
         _queue->headFutex = 1;
         _nextIndex = 1;
         _wakeHeadFutex();
     }
References _chunk, _handle, _nextIndex, _queue, _wakeHeadFutex(), and params.
Queue() [4/4]
Queue::Queue (const Queue &) delete
Member Function Documentation
_numberOf()
int Queue::_numberOf (int index) inline private
Definition at line 179 of file posix-pipe.hpp.
{
         return _queue->indexQueue[index & 1];
     }
References index.
Referenced by dequeueSingle().
_retrieveChunk()
HelChunk* Queue::_retrieveChunk () inline private
Definition at line 183 of file posix-pipe.hpp.
{
         return _chunks[_numberOf(_retrieveIndex)];
     }
_waitProgressFutex() [1/2]
void Queue::_waitProgressFutex (bool * done) inline private
Definition at line 193 of file posix-pipe.hpp.
{
         while(true) {
             auto futex = __atomic_load_n(&_retrieveChunk()->progressFutex, __ATOMIC_ACQUIRE);
             __ensure(!(futex & ~(kHelProgressMask | kHelProgressWaiters | kHelProgressDone)));
             do {
                 if(_lastProgress != (futex & kHelProgressMask)) {
                     *done = false;
                     return;
                 }else if(futex & kHelProgressDone) {
                     *done = true;
                     return;
                 }
                 if(futex & kHelProgressWaiters)
                     break; // Waiters bit is already set (in a previous iteration).
             } while(!__atomic_compare_exchange_n(&_retrieveChunk()->progressFutex, &futex,
                         _lastProgress | kHelProgressWaiters,
                         false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE));
             HEL_CHECK(helFutexWait(&_retrieveChunk()->progressFutex,
                     _lastProgress | kHelProgressWaiters, -1));
         }
     }
References __ensure, and done.
Referenced by dequeueSingle().
_waitProgressFutex() [2/2]
void Queue::_waitProgressFutex (bool * done) inline private
Definition at line 116 of file support.cpp.
{
         while(true) {
             auto futex = __atomic_load_n(&_chunk->progressFutex, __ATOMIC_ACQUIRE);
             __ensure(!(futex & ~(kHelProgressMask | kHelProgressWaiters | kHelProgressDone)));
             do {
                 if(_lastProgress != (futex & kHelProgressMask)) {
                     *done = false;
                     return;
                 }else if(futex & kHelProgressDone) {
                     *done = true;
                     return;
                 }
                 if(futex & kHelProgressWaiters)
                     break; // Waiters bit is already set (in a previous iteration).
             } while(!__atomic_compare_exchange_n(&_chunk->progressFutex, &futex,
                         _lastProgress | kHelProgressWaiters,
                         false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE));
             HEL_CHECK(helFutexWait(&_chunk->progressFutex,
                     _lastProgress | kHelProgressWaiters, -1));
         }
     }
References __ensure, _chunk, _lastProgress, and done.
_wakeHeadFutex() [1/2]
void Queue::_wakeHeadFutex () inline private
Definition at line 187 of file posix-pipe.hpp.
{
         auto futex = __atomic_exchange_n(&_queue->headFutex, _nextIndex, __ATOMIC_RELEASE);
         if(futex & kHelHeadWaiters)
             HEL_CHECK(helFutexWake(&_queue->headFutex));
     }
Referenced by dequeueSingle(), Queue(), and recreateQueue().
_wakeHeadFutex() [2/2]
void Queue::_wakeHeadFutex () inline private
Definition at line 110 of file support.cpp.
{
         auto futex = __atomic_exchange_n(&_queue->headFutex, _nextIndex, __ATOMIC_RELEASE);
         if(futex & kHelHeadWaiters)
             HEL_CHECK(helFutexWake(&_queue->headFutex));
     }
References _nextIndex, and _queue.
dequeueSingle() [1/2]
ElementHandle Queue::dequeueSingle () inline
Definition at line 133 of file posix-pipe.hpp.
{
         while(true) {
             __ensure(_retrieveIndex != _nextIndex);
             bool done;
             _waitProgressFutex(&done);
             auto n = _numberOf(_retrieveIndex);
             __ensure(_refCount[n]);
             if(done) {
                 retire(n);
                 _lastProgress = 0;
                 _retrieveIndex = ((_retrieveIndex + 1) & kHelHeadMask);
                 continue;
             }
             // Dequeue the next element.
             auto ptr = (char *)_chunks[n] + sizeof(HelChunk) + _lastProgress;
             auto element = reinterpret_cast<HelElement *>(ptr);
             _lastProgress += sizeof(HelElement) + element->length;
             _refCount[n]++;
             return ElementHandle{this, n, ptr + sizeof(HelElement)};
         }
     }
References __ensure, _chunks, _lastProgress, _nextIndex, _numberOf(), _refCount, _retrieveIndex, _waitProgressFutex(), done, n, and retire().
Referenced by __raw_map(), exchangeMsgsSync(), mlibc::sys_chroot(), mlibc::sys_faccessat(), mlibc::sys_fallocate(), mlibc::sys_flock(), mlibc::sys_getrusage(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
dequeueSingle() [2/2]
void* Queue::dequeueSingle () inline
Definition at line 85 of file support.cpp.
{
         while(true) {
             bool done;
             _waitProgressFutex(&done);
             if(done) {
                 // Reset and enqueue the chunk again.
                 _chunk->progressFutex = 0;
                 _queue->indexQueue[0] = 0;
                 _nextIndex = ((_nextIndex + 1) & kHelHeadMask);
                 _wakeHeadFutex();
                 _lastProgress = 0;
                 continue;
             }
             // Dequeue the next element.
             auto ptr = (char *)_chunk + sizeof(HelChunk) + _lastProgress;
             auto element = load<HelElement>(ptr);
             _lastProgress += sizeof(HelElement) + element.length;
             return ptr + sizeof(HelElement);
         }
     }
References _chunk, _lastProgress, _nextIndex, _queue, _waitProgressFutex(), _wakeHeadFutex(), and done.
getHandle()
HelHandle Queue::getHandle () inline
Definition at line 81 of file support.cpp.
{
         return _handle;
     }
References _handle.
getQueue()
HelHandle Queue::getQueue () inline
Definition at line 127 of file posix-pipe.hpp.
{
         return _handle;
     }
References _handle.
Referenced by __raw_map(), exchangeMsgsSync(), mlibc::sys_chroot(), mlibc::sys_faccessat(), mlibc::sys_fallocate(), mlibc::sys_flock(), mlibc::sys_getrusage(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
operator=() [1/2]
Queue& Queue::operator= (const Queue &) delete
operator=() [2/2]
Queue& Queue::operator= (const Queue &) delete
recreateQueue()
void Queue::recreateQueue () inline
Definition at line 85 of file posix-pipe.hpp.
{
         // Reset the internal queue state.
         _retrieveIndex = 0;
         _nextIndex = 0;
         _lastProgress = 0;
         // Setup the queue header.
         HelQueueParameters params {
             .flags = 0,
             .ringShift = 1,
             .numChunks = 2,
             .chunkSize = 4096
         };
         HEL_CHECK(helCreateQueue(&params, &_handle));
         auto chunksOffset = (sizeof(HelQueue) + (sizeof(int) << 1) + 63) & ~size_t(63);
         auto reservedPerChunk = (sizeof(HelChunk) + params.chunkSize + 63) & ~size_t(63);
         auto overallSize = chunksOffset + params.numChunks * reservedPerChunk;
         void *mapping;
         HEL_CHECK(helMapMemory(_handle, kHelNullHandle, nullptr,
                 0, (overallSize + 0xFFF) & ~size_t(0xFFF),
                 kHelMapProtRead | kHelMapProtWrite, &mapping));
         _queue = reinterpret_cast<HelQueue *>(mapping);
         auto chunksPtr = reinterpret_cast<std::byte *>(mapping) + chunksOffset;
         for(unsigned int i = 0; i < 2; ++i)
             _chunks[i] = reinterpret_cast<HelChunk *>(chunksPtr + i * reservedPerChunk);
         // Reset and enqueue the chunks.
         _chunks[0]->progressFutex = 0;
         _chunks[1]->progressFutex = 0;
         _refCount[0] = 1;
         _refCount[1] = 1;
         _queue->indexQueue[0] = 0;
         _queue->indexQueue[1] = 1;
         _queue->headFutex = 0;
         _nextIndex = 2;
         _wakeHeadFutex();
     }
References _chunks, _handle, _lastProgress, _nextIndex, _queue, _refCount, _retrieveIndex, _wakeHeadFutex(), i, and params.
Referenced by Queue().
reference()
void Queue::reference (int n) inline
Definition at line 174 of file posix-pipe.hpp.
{
         _refCount[n]++;
     }
References n.
Referenced by ElementHandle::ElementHandle().
retire()
void Queue::retire (int n) inline
Definition at line 160 of file posix-pipe.hpp.
{
         __ensure(_refCount[n]);
         if(_refCount[n]-- > 1)
             return;
         // Reset and enqueue the chunk again.
         _chunks[n]->progressFutex = 0;
         _refCount[n] = 1;
         _queue->indexQueue[_nextIndex & 1] = n;
         _nextIndex = ((_nextIndex + 1) & kHelHeadMask);
         _wakeHeadFutex();
     }
References __ensure, and n.
Referenced by dequeueSingle(), and ElementHandle::~ElementHandle().
trim()
void Queue::trim () inline
Definition at line 131 of file posix-pipe.hpp.
 { }
Referenced by __raw_map(), mlibc::sys_chroot(), mlibc::sys_faccessat(), mlibc::sys_fallocate(), mlibc::sys_flock(), mlibc::sys_getrusage(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
Field Documentation
_chunk
HelChunk* Queue::_chunk private
Definition at line 143 of file support.cpp.
Referenced by _waitProgressFutex(), dequeueSingle(), and Queue().
_chunks
HelChunk* Queue::_chunks[2] private
Definition at line 220 of file posix-pipe.hpp.
Referenced by dequeueSingle(), Queue(), and recreateQueue().
_handle
HelHandle Queue::_handle private
Definition at line 218 of file posix-pipe.hpp.
Referenced by getHandle(), getQueue(), Queue(), and recreateQueue().
_lastProgress
int Queue::_lastProgress private
Definition at line 227 of file posix-pipe.hpp.
Referenced by _waitProgressFutex(), dequeueSingle(), and recreateQueue().
_nextIndex
int Queue::_nextIndex private
Definition at line 224 of file posix-pipe.hpp.
Referenced by _wakeHeadFutex(), dequeueSingle(), Queue(), and recreateQueue().
_queue
HelQueue * Queue::_queue private
Definition at line 219 of file posix-pipe.hpp.
Referenced by _wakeHeadFutex(), dequeueSingle(), Queue(), and recreateQueue().
_refCount
int Queue::_refCount[2] private
Definition at line 230 of file posix-pipe.hpp.
Referenced by dequeueSingle(), and recreateQueue().
_retrieveIndex
int Queue::_retrieveIndex private
Definition at line 223 of file posix-pipe.hpp.
Referenced by dequeueSingle(), and recreateQueue().
The documentation for this struct was generated from the following files:
Userspace/mlibc/sysdeps/managarm/include/mlibc/posix-pipe.hpp
Userspace/mlibc/sysdeps/managarm/rtdl-generic/support.cpp