Fennix: Kernel/Fex.hpp File Reference
Fex.hpp File Reference
Data Structures
struct Fex
struct FexExtended
struct FexExtended.Executable
struct FexExtended.Driver
struct DriverBind.Driver.Bind
struct DriverBind.Driver.Bind.Interrupt
struct DriverBind.Driver.Bind.Process
struct DriverBind.Driver.Bind.PCI
struct DriverBind.Driver.Bind.Input
Macros
#define EXTENDED_SECTION_ADDRESS 0x20
This may change.
#define HEAD(FormatType, OperatingSystem, Address)
Add file header.
Enumerations
enum FexFormatType { FexFormatType_Unknown , FexFormatType_Executable , FexFormatType_Driver }
enum FexOSType { FexOSType_Unknown , FexOSType_Fennix , FexOSType_Linux }
enum FexDriverType {
FexDriverType_Unknown , FexDriverType_Generic , FexDriverType_Display , FexDriverType_Network ,
FexDriverType_Storage , FexDriverType_FileSystem , FexDriverType_Input , FexDriverType_Audio
}
enum FexDriverInputTypes { FexDriverInputTypes_None = 0b00000000 , FexDriverInputTypes_Mouse = 0b00000001 , FexDriverInputTypes_Keyboard = 0b00000010 }
Functions
struct Fex __attribute__ ((packed))
Variables
char Magic [4]
enum FexFormatType Type
enum FexOSType OS
int(* EntryPoint)(void *)
struct {
} Executable
struct {
char Name [64]
enum FexDriverType Type: 4
enum FexDriverInputTypes TypeFlags: 4
bool OverrideOnConflict: 1
int(* Callback)(union KernelCallback *)
int(* InterruptCallback)(union CPURegisters *)
struct DriverBind {
int Type
struct {
unsigned char Vector [16]
} Interrupt
struct {
unsigned int ProcessId [16]
} Process
struct {
unsigned short VendorID [16]
unsigned short DeviceID [16]
unsigned short Class
unsigned short SubClass
unsigned short ProgIF
} PCI
struct {
char AttachToMouse
char AttachToKeyboard
} Input
} Bind
} Driver
Data Structure Documentation
FexExtended
struct FexExtended
Definition at line 65 of file Fex.hpp.
Data Fields
struct FexExtended Driver
struct FexExtended Executable
FexExtended.Executable
struct FexExtended.Executable
Definition at line 67 of file Fex.hpp.
FexExtended::DriverBind.Driver.Bind
struct FexExtended::DriverBind.Driver.Bind
Definition at line 81 of file Fex.hpp.
Data Fields
Bind Input
Bind Interrupt
Bind PCI
Bind Process
int Type
FexExtended::DriverBind.Driver.Bind.Interrupt
struct FexExtended::DriverBind.Driver.Bind.Interrupt
Definition at line 84 of file Fex.hpp.
Data Fields
unsigned char Vector[16]
FexExtended::DriverBind.Driver.Bind.Process
struct FexExtended::DriverBind.Driver.Bind.Process
Definition at line 89 of file Fex.hpp.
Data Fields
unsigned int ProcessId[16]
FexExtended::DriverBind.Driver.Bind.PCI
struct FexExtended::DriverBind.Driver.Bind.PCI
Definition at line 94 of file Fex.hpp.
Data Fields
unsigned short Class
unsigned short DeviceID[16]
unsigned short ProgIF
unsigned short SubClass
unsigned short VendorID[16]
FexExtended::DriverBind.Driver.Bind.Input
struct FexExtended::DriverBind.Driver.Bind.Input
Definition at line 103 of file Fex.hpp.
Data Fields
char AttachToKeyboard
char AttachToMouse
Macro Definition Documentation
EXTENDED_SECTION_ADDRESS
#define EXTENDED_SECTION_ADDRESS 0x20
This may change.
Definition at line 15 of file Fex.hpp.
HEAD
#define HEAD (FormatType, OperatingSystem, Address)
Value:
    __attribute__((section(".header"))) struct Fex FexHeader = { \
        .Magic = {'F', 'E', 'X', '\0'},                          \
        .Type = FormatType,                                      \
        .OS = OperatingSystem,                                   \
        .EntryPoint = Address}
Add file header.
Parameters
FormatType FexFormatType
OperatingSystem FexOSType
Address EntryPoint to the start function
Note
Must include ".header : { *(.header .header.*) }" in linker script
Definition at line 121 of file Fex.hpp.
Enumeration Type Documentation
FexDriverInputTypes
enum FexDriverInputTypes
Enumerator
FexDriverInputTypes_None
FexDriverInputTypes_Mouse
FexDriverInputTypes_Keyboard
Definition at line 46 of file Fex.hpp.
 {
     FexDriverInputTypes_None = 0b00000000,
     FexDriverInputTypes_Mouse = 0b00000001,
     FexDriverInputTypes_Keyboard = 0b00000010,
     /* ... */
 };
FexDriverType
enum FexDriverType
Enumerator
FexDriverType_Unknown
FexDriverType_Generic
FexDriverType_Display
FexDriverType_Network
FexDriverType_Storage
FexDriverType_FileSystem
FexDriverType_Input
FexDriverType_Audio
Definition at line 33 of file Fex.hpp.
 {
     FexDriverType_Unknown,
     FexDriverType_Generic,
     FexDriverType_Display,
     FexDriverType_Network,
     FexDriverType_Storage,
     FexDriverType_FileSystem,
     FexDriverType_Input,
     FexDriverType_Audio
     /* ... */
 };
FexFormatType
enum FexFormatType
Enumerator
FexFormatType_Unknown
FexFormatType_Executable
FexFormatType_Driver
Definition at line 17 of file Fex.hpp.
 {
     FexFormatType_Unknown,
     FexFormatType_Executable,
     FexFormatType_Driver
     /* ... */
 };
FexOSType
enum FexOSType
Enumerator
FexOSType_Unknown
FexOSType_Fennix
FexOSType_Linux
Definition at line 25 of file Fex.hpp.
 {
     FexOSType_Unknown,
     FexOSType_Fennix,
     FexOSType_Linux
     /* ... */
 };
Function Documentation
__attribute__()
struct Fex __attribute__ ((packed))
Variable Documentation
struct { ... } Driver
Referenced by Recovery::ChangeSampleRate(), Recovery::ChangeVolume(), KernelMainThread(), and Recovery::PlayAudio().
EntryPoint
int(* EntryPoint) (void *) (void *)
Definition at line 3 of file Fex.hpp.
Referenced by Driver::Driver::CallDriverEntryPoint(), Tasking::Task::CreateThread(), Execute::ELFLoadExec(), and Tasking::Task::Task().
struct { ... } Executable
Magic
char Magic[4]
Definition at line 0 of file Fex.hpp.
Referenced by Multiboot2Entry().
OS
enum FexOSType OS
Definition at line 0 of file Fex.hpp.
Type
enum FexFormatType Type
Definition at line 0 of file Fex.hpp.