Fennix: Userspace/apps/base/bash/lib/readline/rlprivate.h File Reference
rlprivate.h File Reference
#include "rlconf.h"
#include "rlstdc.h"
#include "posixjmp.h"
#include "rlmbutil.h"
Data Structures
struct __rl_search_context
struct _rl_cmd
struct __rl_keyseq_context
struct __rl_vimotion_context
struct __rl_callback_generic_arg
Macros
#define EMACS_MODE() (rl_editing_mode == emacs_mode)
#define VI_COMMAND_MODE() (rl_editing_mode == vi_mode && _rl_keymap == vi_movement_keymap)
#define VI_INSERT_MODE() (rl_editing_mode == vi_mode && _rl_keymap == vi_insertion_keymap)
#define RL_CHECK_SIGNALS()
#define RL_SIG_RECEIVED() (_rl_caught_signal != 0)
#define RL_SIGINT_RECEIVED() (_rl_caught_signal == SIGINT)
#define RL_SIGWINCH_RECEIVED() (_rl_caught_signal == SIGWINCH)
#define CUSTOM_REDISPLAY_FUNC() (rl_redisplay_function != rl_redisplay)
#define CUSTOM_INPUT_FUNC() (rl_getc_function != rl_getc)
#define RL_SEARCH_ISEARCH 0x01 /* incremental search */
#define RL_SEARCH_NSEARCH 0x02 /* non-incremental search */
#define RL_SEARCH_CSEARCH 0x04 /* intra-line char search */
#define SF_REVERSE 0x01
#define SF_FOUND 0x02
#define SF_FAILED 0x04
#define SF_CHGKMAP 0x08
#define SF_PATTERN 0x10
#define SF_NOCASE 0x20 /* unused so far */
#define NUM_SAWMINUS 0x01
#define NUM_SAWDIGITS 0x02
#define NUM_READONE 0x04
#define KSEQ_DISPATCHED 0x01
#define KSEQ_SUBSEQ 0x02
#define KSEQ_RECURSIVE 0x04
#define VIM_DELETE 0x01
#define VIM_CHANGE 0x02
#define VIM_YANK 0x04
#define VMSTATE_READ 0x01
#define VMSTATE_NUMARG 0x02
#define BRACKETED_PASTE_DEFAULT 1 /* XXX - for now */
#define BRACK_PASTE_PREF "\033[200~"
#define BRACK_PASTE_SUFF "\033[201~"
#define BRACK_PASTE_LAST '~'
#define BRACK_PASTE_SLEN 6
#define BRACK_PASTE_INIT "\033[?2004h"
#define BRACK_PASTE_FINI "\033[?2004l\r"
Typedefs
typedef struct __rl_search_context _rl_search_cxt
typedef int _rl_arg_cxt
typedef struct __rl_keyseq_context _rl_keyseq_cxt
typedef struct __rl_vimotion_context _rl_vimotion_cxt
typedef struct __rl_callback_generic_arg _rl_callback_generic_arg
typedef int _rl_callback_func_t(_rl_callback_generic_arg *)
typedef void _rl_sigcleanup_func_t(int, void *)
Functions
int rl_set_retained_kills (int)
void _rl_set_screen_size (int, int)
int _rl_fix_last_undo_of_type (int, int, int)
char * _rl_savestring (const char *)
void readline_internal_setup (void)
char * readline_internal_teardown (int)
int readline_internal_char (void)
_rl_keyseq_cxt * _rl_keyseq_cxt_alloc (void)
void _rl_keyseq_cxt_dispose (_rl_keyseq_cxt *)
void _rl_keyseq_chain_dispose (void)
int _rl_dispatch_callback (_rl_keyseq_cxt *)
_rl_callback_generic_arg * _rl_callback_data_alloc (int)
void _rl_callback_data_dispose (_rl_callback_generic_arg *)
char * _rl_untranslate_macro_value (char *, int)
void _rl_reset_completion_state (void)
char _rl_find_completion_word (int *, int *)
void _rl_free_match_list (char **)
char * _rl_strip_prompt (char *)
void _rl_reset_prompt (void)
void _rl_move_vert (int)
void _rl_save_prompt (void)
void _rl_restore_prompt (void)
char * _rl_make_prompt_for_search (int)
void _rl_erase_at_end_of_line (int)
void _rl_clear_to_eol (int)
void _rl_clear_screen (int)
void _rl_update_final (void)
void _rl_optimize_redisplay (void)
void _rl_redisplay_after_sigwinch (void)
void _rl_clean_up_for_exit (void)
void _rl_erase_entire_line (void)
int _rl_current_display_line (void)
void _rl_refresh_line (void)
int _rl_any_typein (void)
int _rl_input_available (void)
int _rl_nchars_available (void)
int _rl_input_queued (int)
void _rl_insert_typein (int)
int _rl_unget_char (int)
int _rl_pushed_input_available (void)
int _rl_timeout_init (void)
int _rl_timeout_handle_sigalrm (void)
_rl_search_cxt * _rl_scxt_alloc (int, int)
void _rl_scxt_dispose (_rl_search_cxt *, int)
int _rl_isearch_dispatch (_rl_search_cxt *, int)
int _rl_isearch_callback (_rl_search_cxt *)
int _rl_isearch_cleanup (_rl_search_cxt *, int)
int _rl_search_getchar (_rl_search_cxt *)
int _rl_read_bracketed_paste_prefix (int)
char * _rl_bracketed_text (size_t *)
int _rl_bracketed_read_key (void)
int _rl_bracketed_read_mbstring (char *, int)
void _rl_with_macro_input (char *)
int _rl_peek_macro_key (void)
int _rl_next_macro_key (void)
int _rl_prev_macro_key (void)
void _rl_push_executing_macro (void)
void _rl_pop_executing_macro (void)
void _rl_add_macro_char (int)
void _rl_kill_kbd_macro (void)
int _rl_arg_overflow (void)
void _rl_arg_init (void)
int _rl_arg_getchar (void)
int _rl_arg_callback (_rl_arg_cxt)
void _rl_reset_argument (void)
void _rl_start_using_history (void)
int _rl_free_saved_history_line (void)
void _rl_set_insert_mode (int, int)
void _rl_revert_previous_lines (void)
void _rl_revert_all_lines (void)
char * _rl_init_locale (void)
int _rl_init_eightbit (void)
void _rl_reset_locale (void)
void _rl_enable_paren_matching (int)
void _rl_init_line_state (void)
void _rl_set_the_line (void)
int _rl_dispatch (int, Keymap)
int _rl_dispatch_subseq (int, Keymap, int)
void _rl_internal_char_cleanup (void)
void _rl_init_executing_keyseq (void)
void _rl_term_executing_keyseq (void)
void _rl_end_executing_keyseq (void)
void _rl_add_executing_keyseq (int)
void _rl_del_executing_keyseq (void)
int _rl_disable_tty_signals (void)
int _rl_restore_tty_signals (void)
int _rl_nsearch_callback (_rl_search_cxt *)
int _rl_nsearch_cleanup (_rl_search_cxt *, int)
void _rl_signal_handler (int)
void _rl_block_sigint (void)
void _rl_release_sigint (void)
void _rl_block_sigwinch (void)
void _rl_release_sigwinch (void)
void _rl_get_screen_size (int, int)
void _rl_sigwinch_resize_terminal (void)
int _rl_init_terminal_io (const char *)
int _rl_output_character_function (int)
void _rl_cr (void)
void _rl_output_some_chars (const char *, int)
int _rl_backspace (int)
void _rl_enable_meta_key (void)
void _rl_disable_meta_key (void)
void _rl_control_keypad (int)
void _rl_set_cursor (int, int)
void _rl_standout_on (void)
void _rl_standout_off (void)
int _rl_reset_region_color (int, const char *)
void _rl_region_color_on (void)
void _rl_region_color_off (void)
void _rl_fix_point (int)
void _rl_fix_mark (void)
int _rl_replace_text (const char *, int, int)
int _rl_forward_char_internal (int)
int _rl_backward_char_internal (int)
int _rl_insert_char (int, int)
int _rl_overwrite_char (int, int)
int _rl_overwrite_rubout (int, int)
int _rl_rubout_char (int, int)
int _rl_char_search_internal (int, int, int)
int _rl_set_mark_at_pos (int)
UNDO_LIST * _rl_copy_undo_entry (UNDO_LIST *)
UNDO_LIST * _rl_copy_undo_list (UNDO_LIST *)
void _rl_free_undo_list (UNDO_LIST *)
void _rl_ttymsg ()
void _rl_errmsg ()
void _rl_trace ()
void _rl_audit_tty (char *)
int _rl_tropen (void)
int _rl_abort_internal (void)
int _rl_null_function (int, int)
char * _rl_strindex (const char *, const char *)
int _rl_qsort_string_compare (char **, char **)
int() _rl_uppercase_p (int)
int() _rl_lowercase_p (int)
int() _rl_pure_alphabetic (int)
int() _rl_digit_p (int)
int() _rl_to_lower (int)
int() _rl_to_upper (int)
int() _rl_digit_value (int)
void _rl_vi_initialize_line (void)
void _rl_vi_reset_last (void)
void _rl_vi_set_last (int, int, int)
int _rl_vi_textmod_command (int)
int _rl_vi_motion_command (int)
void _rl_vi_done_inserting (void)
int _rl_vi_domove_callback (_rl_vimotion_cxt *)
int _rl_vi_domove_motion_cleanup (int, _rl_vimotion_cxt *)
Variables
struct _rl_cmd _rl_pending_command
struct _rl_cmd * _rl_command_to_execute
int rl_complete_with_tilde_expansion
int rl_visible_stats
int _rl_colored_stats
int _rl_colored_completion_prefix
int rl_line_buffer_len
int rl_arg_sign
int rl_visible_prompt_length
int rl_byte_oriented
int rl_display_fixed
int rl_blink_matching_paren
rl_command_func_t * _rl_executing_func
const char *const _rl_possible_control_prefixes []
const char *const _rl_possible_meta_prefixes []
_rl_callback_func_t * _rl_callback_func
_rl_callback_generic_arg * _rl_callback_data
int _rl_complete_show_all
int _rl_complete_show_unmodified
int _rl_complete_mark_directories
int _rl_complete_mark_symlink_dirs
int _rl_completion_prefix_display_length
int _rl_completion_columns
int _rl_print_completions_horizontally
int _rl_completion_case_fold
int _rl_completion_case_map
int _rl_match_hidden_files
int _rl_page_completions
int _rl_skip_completed_text
int _rl_menu_complete_prefix_first
int _rl_vis_botlin
int _rl_last_c_pos
int _rl_suppress_redisplay
int _rl_want_redisplay
char * _rl_emacs_mode_str
int _rl_emacs_modestr_len
char * _rl_vi_ins_mode_str
int _rl_vi_ins_modestr_len
char * _rl_vi_cmd_mode_str
int _rl_vi_cmd_modestr_len
char * _rl_isearch_terminators
_rl_search_cxt * _rl_iscxt
char * _rl_executing_macro
int _rl_history_preserve_point
int _rl_history_saved_point
_rl_arg_cxt _rl_argcxt
int _rl_utf8locale
int _rl_echoing_p
int _rl_horizontal_scroll_mode
int _rl_mark_modified_lines
int _rl_bell_preference
int _rl_meta_flag
int _rl_convert_meta_chars_to_ascii
int _rl_output_meta_chars
int _rl_bind_stty_chars
int _rl_revert_all_at_newline
int _rl_echo_control_chars
int _rl_show_mode_in_prompt
int _rl_enable_bracketed_paste
int _rl_enable_active_region
char * _rl_active_region_start_color
char * _rl_active_region_end_color
char * _rl_comment_begin
unsigned char _rl_parsing_conditionalized_out
Keymap _rl_keymap
FILE * _rl_in_stream
FILE * _rl_out_stream
int _rl_last_command_was_kill
int _rl_eof_char
procenv_t _rl_top_level
_rl_keyseq_cxt * _rl_kscxt
int _rl_keyseq_timeout
int _rl_executing_keyseq_size
rl_hook_func_t * _rl_internal_startup_hook
_rl_search_cxt * _rl_nscxt
int _rl_history_search_pos
int volatile _rl_caught_signal
_rl_sigcleanup_func_t * _rl_sigcleanup
void * _rl_sigcleanarg
int _rl_echoctl
int _rl_intr_char
int _rl_quit_char
int _rl_susp_char
int _rl_enable_keypad
int _rl_enable_meta
char * _rl_term_clreol
char * _rl_term_clrpag
char * _rl_term_clrscroll
char * _rl_term_im
char * _rl_term_ic
char * _rl_term_ei
char * _rl_term_DC
char * _rl_term_up
char * _rl_term_dc
char * _rl_term_cr
char * _rl_term_IC
char * _rl_term_forward_char
int _rl_screenheight
int _rl_screenwidth
int _rl_screenchars
int _rl_terminal_can_insert
int _rl_term_autowrap
int _rl_optimize_typeahead
int _rl_keep_mark_active
int _rl_doing_an_undo
int _rl_undo_group_level
int _rl_vi_last_command
int _rl_vi_redoing
_rl_vimotion_cxt * _rl_vimvcxt
Data Structure Documentation
__rl_search_context
struct __rl_search_context
Definition at line 71 of file rlprivate.h.
Data Fields
char * allocated_line
int direction
int hindex
int history_pos
int hlen
Keymap keymap
int last_found_line
int lastc
char ** lines
Keymap okeymap
char * prev_line_found
int prevc
int save_line
int save_mark
int save_point
UNDO_LIST * save_undo_list
char * search_string
int search_string_index
int search_string_size
char * search_terminators
int sflags
char * sline
int sline_index
int sline_len
int type
_rl_cmd
struct _rl_cmd
Definition at line 113 of file rlprivate.h.
Data Fields
int count
rl_command_func_t * func
int key
Keymap map
__rl_keyseq_context
struct __rl_keyseq_context
Definition at line 135 of file rlprivate.h.
Data Fields
int childval
Keymap dmap
int flags
struct __rl_keyseq_context * ocxt
int okey
Keymap oldmap
int subseq_arg
int subseq_retval
__rl_vimotion_context
struct __rl_vimotion_context
Definition at line 159 of file rlprivate.h.
Data Fields
int end
int flags
int key
int motion
_rl_arg_cxt ncxt
int numeric_arg
int op
int start
int state
__rl_callback_generic_arg
struct __rl_callback_generic_arg
Definition at line 172 of file rlprivate.h.
Data Fields
int count
int i1
int i2
Macro Definition Documentation
BRACK_PASTE_FINI
#define BRACK_PASTE_FINI "\033[?2004l\r"
Definition at line 333 of file rlprivate.h.
BRACK_PASTE_INIT
#define BRACK_PASTE_INIT "\033[?2004h"
Definition at line 332 of file rlprivate.h.
BRACK_PASTE_LAST
#define BRACK_PASTE_LAST '~'
Definition at line 329 of file rlprivate.h.
BRACK_PASTE_PREF
#define BRACK_PASTE_PREF "\033[200~"
Definition at line 326 of file rlprivate.h.
BRACK_PASTE_SLEN
#define BRACK_PASTE_SLEN 6
Definition at line 330 of file rlprivate.h.
BRACK_PASTE_SUFF
#define BRACK_PASTE_SUFF "\033[201~"
Definition at line 327 of file rlprivate.h.
BRACKETED_PASTE_DEFAULT
#define BRACKETED_PASTE_DEFAULT 1 /* XXX - for now */
Definition at line 323 of file rlprivate.h.
CUSTOM_INPUT_FUNC
#define CUSTOM_INPUT_FUNC () (rl_getc_function != rl_getc)
Definition at line 51 of file rlprivate.h.
CUSTOM_REDISPLAY_FUNC
#define CUSTOM_REDISPLAY_FUNC () (rl_redisplay_function != rl_redisplay)
Definition at line 50 of file rlprivate.h.
EMACS_MODE
#define EMACS_MODE () (rl_editing_mode == emacs_mode)
Definition at line 37 of file rlprivate.h.
KSEQ_DISPATCHED
#define KSEQ_DISPATCHED 0x01
Definition at line 131 of file rlprivate.h.
KSEQ_RECURSIVE
#define KSEQ_RECURSIVE 0x04
Definition at line 133 of file rlprivate.h.
KSEQ_SUBSEQ
#define KSEQ_SUBSEQ 0x02
Definition at line 132 of file rlprivate.h.
NUM_READONE
#define NUM_READONE 0x04
Definition at line 125 of file rlprivate.h.
NUM_SAWDIGITS
#define NUM_SAWDIGITS 0x02
Definition at line 124 of file rlprivate.h.
NUM_SAWMINUS
#define NUM_SAWMINUS 0x01
Definition at line 123 of file rlprivate.h.
RL_CHECK_SIGNALS
#define RL_CHECK_SIGNALS ()
Value:
    do { \
      if (_rl_caught_signal) _rl_signal_handler (_rl_caught_signal); \
    } while (0)
Definition at line 41 of file rlprivate.h.
RL_SEARCH_CSEARCH
#define RL_SEARCH_CSEARCH 0x04 /* intra-line char search */
Definition at line 61 of file rlprivate.h.
RL_SEARCH_ISEARCH
#define RL_SEARCH_ISEARCH 0x01 /* incremental search */
Definition at line 59 of file rlprivate.h.
RL_SEARCH_NSEARCH
#define RL_SEARCH_NSEARCH 0x02 /* non-incremental search */
Definition at line 60 of file rlprivate.h.
RL_SIG_RECEIVED
#define RL_SIG_RECEIVED () (_rl_caught_signal != 0)
Definition at line 46 of file rlprivate.h.
RL_SIGINT_RECEIVED
#define RL_SIGINT_RECEIVED () (_rl_caught_signal == SIGINT)
Definition at line 47 of file rlprivate.h.
RL_SIGWINCH_RECEIVED
#define RL_SIGWINCH_RECEIVED () (_rl_caught_signal == SIGWINCH)
Definition at line 48 of file rlprivate.h.
SF_CHGKMAP
#define SF_CHGKMAP 0x08
Definition at line 67 of file rlprivate.h.
SF_FAILED
#define SF_FAILED 0x04
Definition at line 66 of file rlprivate.h.
SF_FOUND
#define SF_FOUND 0x02
Definition at line 65 of file rlprivate.h.
SF_NOCASE
#define SF_NOCASE 0x20 /* unused so far */
Definition at line 69 of file rlprivate.h.
SF_PATTERN
#define SF_PATTERN 0x10
Definition at line 68 of file rlprivate.h.
SF_REVERSE
#define SF_REVERSE 0x01
Definition at line 64 of file rlprivate.h.
VI_COMMAND_MODE
#define VI_COMMAND_MODE () (rl_editing_mode == vi_mode && _rl_keymap == vi_movement_keymap)
Definition at line 38 of file rlprivate.h.
VI_INSERT_MODE
#define VI_INSERT_MODE () (rl_editing_mode == vi_mode && _rl_keymap == vi_insertion_keymap)
Definition at line 39 of file rlprivate.h.
VIM_CHANGE
#define VIM_CHANGE 0x02
Definition at line 151 of file rlprivate.h.
VIM_DELETE
#define VIM_DELETE 0x01
Definition at line 150 of file rlprivate.h.
VIM_YANK
#define VIM_YANK 0x04
Definition at line 152 of file rlprivate.h.
VMSTATE_NUMARG
#define VMSTATE_NUMARG 0x02
Definition at line 157 of file rlprivate.h.
VMSTATE_READ
#define VMSTATE_READ 0x01
Definition at line 156 of file rlprivate.h.
Typedef Documentation
_rl_arg_cxt
typedef int _rl_arg_cxt
Definition at line 127 of file rlprivate.h.
_rl_callback_func_t
typedef int _rl_callback_func_t(_rl_callback_generic_arg *)
Definition at line 179 of file rlprivate.h.
_rl_callback_generic_arg
typedef struct __rl_callback_generic_arg _rl_callback_generic_arg
_rl_keyseq_cxt
typedef struct __rl_keyseq_context _rl_keyseq_cxt
_rl_search_cxt
typedef struct __rl_search_context _rl_search_cxt
_rl_sigcleanup_func_t
typedef void _rl_sigcleanup_func_t(int, void *)
Definition at line 181 of file rlprivate.h.
_rl_vimotion_cxt
typedef struct __rl_vimotion_context _rl_vimotion_cxt
Function Documentation
_rl_abort_internal()
int _rl_abort_internal (void)
Definition at line 99 of file util.c.
 {
   if (RL_ISSTATE (RL_STATE_TIMEOUT) == 0)
     rl_ding ();         /* Don't ring the bell on a timeout */
   rl_clear_message ();
   _rl_reset_argument ();
   rl_clear_pending_input ();
   rl_deactivate_mark ();
   while (rl_executing_macro)
     _rl_pop_executing_macro ();
   _rl_kill_kbd_macro ();
   RL_UNSETSTATE (RL_STATE_MULTIKEY);    /* XXX */
   rl_last_func = (rl_command_func_t *)NULL;
   _rl_longjmp (_rl_top_level, 1);
   return (0);
 }
References _rl_kill_kbd_macro(), _rl_longjmp, _rl_pop_executing_macro(), _rl_reset_argument(), _rl_top_level, NULL, rl_clear_message(), rl_clear_pending_input(), rl_deactivate_mark(), rl_ding(), rl_executing_macro, RL_ISSTATE, rl_last_func, RL_STATE_MULTIKEY, RL_STATE_TIMEOUT, and RL_UNSETSTATE.
Referenced by _rl_dispatch_callback(), _rl_dispatch_subseq(), _rl_timeout_handle(), _rl_with_macro_input(), get_y_or_n(), rl_abort(), rl_call_last_kbd_macro(), rl_digit_loop(), rl_end_kbd_macro(), rl_start_kbd_macro(), rl_vi_yank_pop(), rl_yank(), and rl_yank_pop().
_rl_add_executing_keyseq()
void _rl_add_executing_keyseq (int key)
Definition at line 1562 of file readline.c.
 {
   RESIZE_KEYSEQ_BUFFER ();
  rl_executing_keyseq[rl_key_sequence_length++] = key;
 }
References _rl_cmd::key, RESIZE_KEYSEQ_BUFFER, rl_executing_keyseq, and rl_key_sequence_length.
Referenced by _rl_isearch_dispatch().
_rl_add_macro_char()
void _rl_add_macro_char (int c)
Definition at line 208 of file macro.c.
 {
   if (current_macro_index + 1 >= current_macro_size)
     {
       if (current_macro == 0)
     current_macro = (char *)xmalloc (current_macro_size = 25);
       else
     current_macro = (char *)xrealloc (current_macro, current_macro_size += 25);
     }
   current_macro[current_macro_index++] = c;
   current_macro[current_macro_index] = '\0';
 }
References c, current_macro, current_macro_index, current_macro_size, xmalloc, and xrealloc.
Referenced by _rl_bracketed_text(), _rl_dispatch_subseq(), and _rl_insert_next().
_rl_any_typein()
int _rl_any_typein (void)
Definition at line 182 of file input.c.
 {
   return any_typein;
 }
References any_typein.
_rl_arg_callback()
int _rl_arg_callback (_rl_arg_cxt cxt)
Definition at line 255 of file misc.c.
 {
   int c, r;
   c = _rl_arg_getchar ();
   if (c < 0)
     return (1);     /* EOF */
   if (_rl_argcxt & NUM_READONE)
     {
       _rl_argcxt &= ~NUM_READONE;
       rl_restore_prompt ();
       rl_clear_message ();
       RL_UNSETSTATE(RL_STATE_NUMERICARG);
       rl_execute_next (c);
       return 0;
     }
   r = _rl_arg_dispatch (cxt, c);
   if (r > 0)
     rl_message ("(arg: %d) ", rl_arg_sign * rl_numeric_arg);
   return (r != 1);
 }
References _rl_arg_dispatch(), _rl_arg_getchar(), _rl_argcxt, c, NUM_READONE, r, rl_arg_sign, rl_clear_message(), rl_execute_next(), rl_message(), rl_numeric_arg, rl_restore_prompt(), RL_STATE_NUMERICARG, and RL_UNSETSTATE.
Referenced by rl_callback_read_char().
_rl_arg_getchar()
int _rl_arg_getchar (void)
Definition at line 101 of file misc.c.
 {
   int c;
   rl_message ("(arg: %d) ", rl_arg_sign * rl_numeric_arg);
   RL_SETSTATE(RL_STATE_MOREINPUT);
   c = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   return c;
 }
References c, rl_arg_sign, rl_message(), rl_numeric_arg, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, and RL_UNSETSTATE.
Referenced by _rl_arg_callback(), rl_digit_loop(), and rl_digit_loop1().
_rl_arg_init()
void _rl_arg_init (void)
Definition at line 93 of file misc.c.
 {
   rl_save_prompt ();
   _rl_argcxt = 0;
   RL_SETSTATE(RL_STATE_NUMERICARG);
 }
References _rl_argcxt, rl_save_prompt(), RL_SETSTATE, and RL_STATE_NUMERICARG.
Referenced by rl_digit_argument(), and rl_universal_argument().
_rl_arg_overflow()
int _rl_arg_overflow (void)
Definition at line 77 of file misc.c.
 {
   if (rl_numeric_arg > 1000000)
     {
       _rl_argcxt = 0;
       rl_explicit_arg = rl_numeric_arg = 0;
       rl_ding ();
       rl_restore_prompt ();
       rl_clear_message ();
       RL_UNSETSTATE(RL_STATE_NUMERICARG);
       return 1;
     }
   return 0;
 }
References _rl_argcxt, rl_clear_message(), rl_ding(), rl_explicit_arg, rl_numeric_arg, rl_restore_prompt(), RL_STATE_NUMERICARG, and RL_UNSETSTATE.
Referenced by rl_digit_loop(), and rl_digit_loop1().
_rl_audit_tty()
void _rl_audit_tty (char *)
Referenced by readline().
_rl_backspace()
int _rl_backspace (int count)
Definition at line 717 of file terminal.c.
 {
   register int i;
 #ifndef __MSDOS__
   if (_rl_term_backspace)
     for (i = 0; i < count; i++)
       tputs (_rl_term_backspace, 1, _rl_output_character_function);
   else
 #endif
     for (i = 0; i < count; i++)
       putc ('\b', _rl_out_stream);
   return 0;
 }
References _rl_out_stream, _rl_output_character_function(), _rl_term_backspace, count, i, putc(), and tputs().
Referenced by _rl_erase_at_end_of_line(), _rl_move_cursor_relative(), open_some_spaces(), and rl_redisplay().
_rl_backward_char_internal()
int _rl_backward_char_internal (int count)
Definition at line 319 of file text.c.
 {
   int point;
   point = rl_point;
 #if defined (HANDLE_MULTIBYTE)
   if (count > 0)
     {
       while (count > 0 && point > 0)
     {
       point = _rl_find_prev_mbchar (rl_line_buffer, point, MB_FIND_NONZERO);
       count--;
     }
       if (count > 0)
         return 0;   /* XXX - rl_ding() here? */
     }
 #else
   if (count > 0)
     point -= count;
 #endif
   if (point < 0)
     point = 0;
   return (point);
 }
References _rl_find_prev_mbchar, count, MB_FIND_NONZERO, rl_line_buffer, and rl_point.
Referenced by _rl_vi_backup_point().
_rl_block_sigint()
void _rl_block_sigint (void)
Definition at line 640 of file signals.c.
 {
   if (sigint_blocked)
     return;
   sigint_blocked = 1;
 }
References sigint_blocked.
Referenced by rl_deprep_terminal(), rl_prep_terminal(), and rl_redisplay().
_rl_block_sigwinch()
void _rl_block_sigwinch (void)
Definition at line 662 of file signals.c.
 {
   if (sigwinch_blocked)
     return;
 #if defined (SIGWINCH)
 #if defined (HAVE_POSIX_SIGNALS)
   sigemptyset (&sigwinch_set);
   sigemptyset (&sigwinch_oset);
   sigaddset (&sigwinch_set, SIGWINCH);
   sigprocmask (SIG_BLOCK, &sigwinch_set, &sigwinch_oset);
 #else /* !HAVE_POSIX_SIGNALS */
 #  if defined (HAVE_BSD_SIGNALS)
   sigwinch_oldmask = sigblock (sigmask (SIGWINCH));
 #  else /* !HAVE_BSD_SIGNALS */
 #    if defined (HAVE_USG_SIGHOLD)
   sighold (SIGWINCH);
 #    endif /* HAVE_USG_SIGHOLD */
 #  endif /* !HAVE_BSD_SIGNALS */
 #endif /* !HAVE_POSIX_SIGNALS */
 #endif /* SIGWINCH */
   sigwinch_blocked = 1;
 }
References SIG_BLOCK, sigaddset, sigemptyset, sighold(), sigmask, sigprocmask(), SIGWINCH, and sigwinch_blocked.
_rl_bracketed_read_key()
int _rl_bracketed_read_key (void)
Definition at line 809 of file kill.c.
 {
   int c, r;
   char *pbuf;
   size_t pblen;
   RL_SETSTATE(RL_STATE_MOREINPUT);
   c = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   if (c < 0)
     return -1;
   /* read pasted data with bracketed-paste mode enabled. */
   if (_rl_enable_bracketed_paste && c == ESC && (r = _rl_read_bracketed_paste_prefix (c)) == 1)
     {
       pbuf = _rl_bracketed_text (&pblen);
       if (pblen == 0)
     {
       xfree (pbuf);
       return 0;     /* XXX */
     }
       c = (unsigned char)pbuf[0];
       if (pblen > 1)
     {
       while (--pblen > 0)
         _rl_unget_char ((unsigned char)pbuf[pblen]);
     }
       xfree (pbuf);
     }
   return c;
 }
References _rl_bracketed_text(), _rl_enable_bracketed_paste, _rl_read_bracketed_paste_prefix(), _rl_unget_char(), c, ESC, r, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, RL_UNSETSTATE, and xfree.
Referenced by _rl_arg_dispatch(), _rl_bracketed_read_mbstring(), _rl_char_search(), and rl_vi_domove_getchar().
_rl_bracketed_read_mbstring()
int _rl_bracketed_read_mbstring (char * mb, int mlen)
Definition at line 847 of file kill.c.
 {
   int c, r;
   c = _rl_bracketed_read_key ();
   if (c < 0)
     return -1;
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     c = _rl_read_mbstring (c, mb, mlen);
   else
 #endif
     mb[0] = c;
   mb[mlen] = '\0';      /* just in case */
   return c;
 }
References _rl_bracketed_read_key(), c, MB_CUR_MAX, r, and rl_byte_oriented.
Referenced by _rl_vi_callback_getchar().
_rl_bracketed_text()
char* _rl_bracketed_text (size_t * lenp)
Definition at line 708 of file kill.c.
 {
   int c;
   size_t len, cap;
   char *buf;
   len = 0;
   buf = xmalloc (cap = 64);
   buf[0] = '\0';
   RL_SETSTATE (RL_STATE_MOREINPUT);
   while ((c = rl_read_key ()) >= 0)
     {
       if (RL_ISSTATE (RL_STATE_MACRODEF))
     _rl_add_macro_char (c);
       if (c == '\r')        /* XXX */
     c = '\n';
       if (len == cap)
     buf = xrealloc (buf, cap *= 2);
       buf[len++] = c;
       if (len >= BRACK_PASTE_SLEN && c == BRACK_PASTE_LAST &&
       STREQN (buf + len - BRACK_PASTE_SLEN, BRACK_PASTE_SUFF, BRACK_PASTE_SLEN))
     {
       len -= BRACK_PASTE_SLEN;
       break;
     }
     }
   RL_UNSETSTATE (RL_STATE_MOREINPUT);
   if (c >= 0)
     {
       if (len == cap)
     buf = xrealloc (buf, cap + 1);
       buf[len] = '\0';
     }
   if (lenp)
     *lenp = len;
   return (buf);
 }
References _rl_add_macro_char(), BRACK_PASTE_LAST, BRACK_PASTE_SLEN, BRACK_PASTE_SUFF, buf, c, len, RL_ISSTATE, rl_read_key(), RL_SETSTATE, RL_STATE_MACRODEF, RL_STATE_MOREINPUT, RL_UNSETSTATE, STREQN, xmalloc, and xrealloc.
Referenced by _rl_bracketed_read_key(), _rl_isearch_dispatch(), rl_bracketed_paste_begin(), and rl_vi_overstrike_bracketed_paste().
_rl_callback_data_alloc()
_rl_callback_generic_arg* _rl_callback_data_alloc (int count)
Definition at line 335 of file callback.c.
 {
   _rl_callback_generic_arg *arg;
   arg = (_rl_callback_generic_arg *)xmalloc (sizeof (_rl_callback_generic_arg));
   arg->count = count;
   arg->i1 = arg->i2 = 0;
   return arg;
 }
References count, and xmalloc.
Referenced by rl_backward_char_search(), rl_char_search(), rl_quoted_insert(), rl_vi_change_char(), and rl_vi_char_search().
_rl_callback_data_dispose()
void _rl_callback_data_dispose (_rl_callback_generic_arg * arg)
Definition at line 348 of file callback.c.
 {
   xfree (arg);
 }
References xfree.
Referenced by rl_callback_read_char().
_rl_char_search_internal()
int _rl_char_search_internal (int count, int dir, int schar)
Definition at line 1669 of file text.c.
 {
   int pos, inc;
 #if defined (HANDLE_MULTIBYTE)
   int prepos;
 #endif
   if (dir == 0)
     return 1;
   pos = rl_point;
   inc = (dir < 0) ? -1 : 1;
   while (count)
     {
       if ((dir < 0 && pos <= 0) || (dir > 0 && pos >= rl_end))
     {
       rl_ding ();
       return 1;
     }
 #if defined (HANDLE_MULTIBYTE)
       pos = (inc > 0) ? _rl_find_next_mbchar (rl_line_buffer, pos, 1, MB_FIND_ANY)
               : _rl_find_prev_mbchar (rl_line_buffer, pos, MB_FIND_ANY);
 #else
       pos += inc;
 #endif
       do
     {
 #if defined (HANDLE_MULTIBYTE)
       if (_rl_is_mbchar_matched (rl_line_buffer, pos, rl_end, smbchar, len))
 #else
       if (rl_line_buffer[pos] == schar)
 #endif
         {
           count--;
           if (dir < 0)
             rl_point = (dir == BTO) ? _rl_find_next_mbchar (rl_line_buffer, pos, 1, MB_FIND_ANY)
                     : pos;
           else
         rl_point = (dir == FTO) ? _rl_find_prev_mbchar (rl_line_buffer, pos, MB_FIND_ANY)
                     : pos;
           break;
         }
 #if defined (HANDLE_MULTIBYTE)
       prepos = pos;
 #endif
     }
 #if defined (HANDLE_MULTIBYTE)
       while ((dir < 0) ? (pos = _rl_find_prev_mbchar (rl_line_buffer, pos, MB_FIND_ANY)) != prepos
                : (pos = _rl_find_next_mbchar (rl_line_buffer, pos, 1, MB_FIND_ANY)) != prepos);
 #else
       while ((dir < 0) ? pos-- : ++pos < rl_end);
 #endif
     }
   return (0);
 }
References _rl_find_next_mbchar, _rl_find_prev_mbchar, BTO, count, FTO, len, MB_FIND_ANY, pos, rl_ding(), rl_end, rl_line_buffer, and rl_point.
Referenced by _rl_char_search(), _rl_vi_callback_char_search(), and rl_vi_char_search().
_rl_clean_up_for_exit()
void _rl_clean_up_for_exit (void)
Definition at line 3416 of file display.c.
 {
   if (_rl_echoing_p)
     {
       if (_rl_vis_botlin > 0)   /* minor optimization plus bug fix */
     _rl_move_vert (_rl_vis_botlin);
       _rl_vis_botlin = 0;
       fflush (rl_outstream);
       rl_restart_output (1, 0);
     }
 }
References _rl_echoing_p, _rl_move_vert(), _rl_vis_botlin, fflush(), rl_outstream, and rl_restart_output().
Referenced by rl_cleanup_after_signal().
_rl_clear_screen()
void _rl_clear_screen (int clrscr)
Definition at line 3220 of file display.c.
 {
 #if defined (__DJGPP__)
   ScreenClear ();
   ScreenSetCursor (0, 0);
 #else
   if (_rl_term_clrpag)
     {
       tputs (_rl_term_clrpag, 1, _rl_output_character_function);
       if (clrscr && _rl_term_clrscroll)
     tputs (_rl_term_clrscroll, 1, _rl_output_character_function);
     }
   else
     rl_crlf ();
 #endif /* __DJGPP__ */
 }
References _rl_output_character_function(), _rl_term_clrpag, _rl_term_clrscroll, rl_crlf(), and tputs().
Referenced by rl_clear_display(), and rl_clear_screen().
_rl_clear_to_eol()
void _rl_clear_to_eol (int count)
Definition at line 3195 of file display.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_clreol)
     tputs (_rl_term_clreol, 1, _rl_output_character_function);
   else
 #endif
     if (count)
       space_to_eol (count);
 }
References _rl_output_character_function(), _rl_term_clreol, count, space_to_eol(), and tputs().
Referenced by _rl_erase_entire_line(), _rl_update_final(), rl_clear_visible_line(), rl_redisplay(), and update_line().
_rl_control_keypad()
void _rl_control_keypad (int on)
Definition at line 904 of file terminal.c.
 {
 #if !defined (__DJGPP__)
   if (on && _rl_term_ks)
     tputs (_rl_term_ks, 1, _rl_output_character_function);
   else if (!on && _rl_term_ke)
     tputs (_rl_term_ke, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_ke, _rl_term_ks, and tputs().
Referenced by rl_deprep_terminal(), and rl_prep_terminal().
_rl_copy_undo_entry()
UNDO_LIST* _rl_copy_undo_entry (UNDO_LIST * entry)
Definition at line 128 of file undo.c.
 {
   UNDO_LIST *new;
   new = alloc_undo_entry (entry->what, entry->start, entry->end, (char *)NULL);
   new->text = entry->text ? savestring (entry->text) : 0;
   return new;
 }
References alloc_undo_entry(), NULL, and savestring().
Referenced by _rl_copy_undo_list().
_rl_copy_undo_list()
UNDO_LIST* _rl_copy_undo_list (UNDO_LIST * head)
Definition at line 138 of file undo.c.
 {
   UNDO_LIST *list, *new, *roving, *c;
   if (head == 0)
     return head;
   list = head;
   new = 0;
   while (list)
     {
       c = _rl_copy_undo_entry (list);
       if (new == 0)
     roving = new = c;
       else
     {
       roving->next = c;
       roving = roving->next;
     }
       list = list->next;
     }
   roving->next = 0;
   return new;
 }
References _rl_copy_undo_entry(), c, head, and undo_list::next.
_rl_cr()
void _rl_cr (void)
Definition at line 745 of file terminal.c.
 {
 #if defined (__MSDOS__)
   putc ('\r', rl_outstream);
 #else
   tputs (_rl_term_cr, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_cr, putc(), rl_outstream, and tputs().
Referenced by _rl_move_cursor_relative(), _rl_move_vert(), cr(), rl_clear_visible_line(), rl_redisplay(), and update_line().
_rl_current_display_line()
int _rl_current_display_line (void)
Definition at line 3446 of file display.c.
 {
   int ret, nleft;
   /* Find out whether or not there might be invisible characters in the
      editing buffer. */
   if (rl_display_prompt == rl_prompt)
     nleft = _rl_last_c_pos - _rl_screenwidth - rl_visible_prompt_length;
   else
     nleft = _rl_last_c_pos - _rl_screenwidth;
   if (nleft > 0)
     ret = 1 + nleft / _rl_screenwidth;
   else
     ret = 0;
   return ret;
 }
References _rl_last_c_pos, _rl_screenwidth, ret, rl_display_prompt, rl_prompt, and rl_visible_prompt_length.
_rl_del_executing_keyseq()
void _rl_del_executing_keyseq (void)
Definition at line 1571 of file readline.c.
 {
   if (rl_key_sequence_length > 0)
     rl_key_sequence_length--;
 }
References rl_key_sequence_length.
_rl_digit_p()
int() _rl_digit_p (int)
Referenced by _rl_arg_dispatch(), _rl_vi_arg_dispatch(), get_history_event(), get_history_word_specifier(), normalize_codeset(), parser_if(), rl_domove_read_callback(), and rl_trim_arg_from_keyseq().
_rl_digit_value()
int() _rl_digit_value (int)
Referenced by _rl_arg_dispatch(), _rl_vi_arg_dispatch(), get_history_event(), get_history_word_specifier(), parser_if(), and rl_domove_read_callback().
_rl_disable_meta_key()
void _rl_disable_meta_key (void)
Definition at line 892 of file terminal.c.
 {
 #if !defined (__DJGPP__)
   if (term_has_meta && _rl_term_mo && enabled_meta)
     {
       tputs (_rl_term_mo, 1, _rl_output_character_function);
       enabled_meta = 0;
     }
 #endif
 }
References _rl_output_character_function(), _rl_term_mo, enabled_meta, term_has_meta, and tputs().
Referenced by readline_internal_teardown().
_rl_disable_tty_signals()
int _rl_disable_tty_signals (void)
Definition at line 942 of file rltty.c.
 {
   return 0;
 }
Referenced by rl_quoted_insert().
_rl_dispatch()
int _rl_dispatch (int , Keymap)
_rl_dispatch_callback()
int _rl_dispatch_callback (_rl_keyseq_cxt * cxt)
Definition at line 806 of file readline.c.
 {
   int nkey, r;
   /* For now */
   /* The first time this context is used, we want to read input and dispatch
      on it.  When traversing the chain of contexts back `up', we want to use
      the value from the next context down.  We're simulating recursion using
      a chain of contexts. */
   if ((cxt->flags & KSEQ_DISPATCHED) == 0)
     {
       nkey = _rl_subseq_getchar (cxt->okey);
       if (nkey < 0)
     {
       _rl_abort_internal ();
       return -1;
     }
       r = _rl_dispatch_subseq (nkey, cxt->dmap, cxt->subseq_arg);
       cxt->flags |= KSEQ_DISPATCHED;
     }
   else
     r = cxt->childval;
   /* For now */
   if (r != -3)  /* don't do this if we indicate there will be other matches */
     r = _rl_subseq_result (r, cxt->oldmap, cxt->okey, (cxt->flags & KSEQ_SUBSEQ));
   RL_CHECK_SIGNALS ();
   /* We only treat values < 0 specially to simulate recursion. */
   if (r >= 0 || (r == -1 && (cxt->flags & KSEQ_SUBSEQ) == 0))   /* success! or failure! */
     {
       _rl_keyseq_chain_dispose ();
       RL_UNSETSTATE (RL_STATE_MULTIKEY);
       return r;
     }
   if (r != -3)          /* magic value that says we added to the chain */
     _rl_kscxt = cxt->ocxt;
   if (_rl_kscxt)
     _rl_kscxt->childval = r;
   if (r != -3)
     _rl_keyseq_cxt_dispose (cxt);
   return r;
 }
References _rl_abort_internal(), _rl_dispatch_subseq(), _rl_keyseq_chain_dispose(), _rl_keyseq_cxt_dispose(), _rl_kscxt, _rl_subseq_getchar(), _rl_subseq_result(), __rl_keyseq_context::childval, __rl_keyseq_context::dmap, __rl_keyseq_context::flags, KSEQ_DISPATCHED, KSEQ_SUBSEQ, __rl_keyseq_context::ocxt, __rl_keyseq_context::okey, __rl_keyseq_context::oldmap, r, RL_CHECK_SIGNALS, RL_STATE_MULTIKEY, RL_UNSETSTATE, and __rl_keyseq_context::subseq_arg.
Referenced by rl_callback_read_char().
_rl_dispatch_subseq()
int _rl_dispatch_subseq (int , Keymap , int)
_rl_enable_meta_key()
void _rl_enable_meta_key (void)
Definition at line 880 of file terminal.c.
 {
 #if !defined (__DJGPP__)
   if (term_has_meta && _rl_term_mm)
     {
       tputs (_rl_term_mm, 1, _rl_output_character_function);
       enabled_meta = 1;
     }
 #endif
 }
References _rl_output_character_function(), _rl_term_mm, enabled_meta, term_has_meta, and tputs().
Referenced by readline_internal_setup().
_rl_enable_paren_matching()
void _rl_enable_paren_matching (int on_or_off)
Definition at line 67 of file parens.c.
 {
   if (on_or_off)
     {
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert_close, emacs_standard_keymap);
       rl_bind_key_in_map (']', rl_insert_close, emacs_standard_keymap);
       rl_bind_key_in_map ('}', rl_insert_close, emacs_standard_keymap);
 #if defined (VI_MODE)
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert_close, vi_insertion_keymap);
       rl_bind_key_in_map (']', rl_insert_close, vi_insertion_keymap);
       rl_bind_key_in_map ('}', rl_insert_close, vi_insertion_keymap);
 #endif
     }
   else
     {
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert, emacs_standard_keymap);
       rl_bind_key_in_map (']', rl_insert, emacs_standard_keymap);
       rl_bind_key_in_map ('}', rl_insert, emacs_standard_keymap);
 #if defined (VI_MODE)
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert, vi_insertion_keymap);
       rl_bind_key_in_map (']', rl_insert, vi_insertion_keymap);
       rl_bind_key_in_map ('}', rl_insert, vi_insertion_keymap);
 #endif
     }
 }
References emacs_standard_keymap, rl_bind_key_in_map(), rl_insert(), rl_insert_close(), and vi_insertion_keymap.
Referenced by hack_special_boolean_var().
_rl_end_executing_keyseq()
void _rl_end_executing_keyseq (void)
Definition at line 1555 of file readline.c.
 {
   if (rl_key_sequence_length > 0)
     rl_executing_keyseq[--rl_key_sequence_length] = '\0';
 }
References rl_executing_keyseq, and rl_key_sequence_length.
_rl_erase_at_end_of_line()
void _rl_erase_at_end_of_line (int l)
Definition at line 3178 of file display.c.
 {
   register int i;
   _rl_backspace (l);
   for (i = 0; i < l; i++)
     putc (' ', rl_outstream);
   _rl_backspace (l);
   for (i = 0; i < l; i++)
     visible_line[--_rl_last_c_pos] = '\0';
   rl_display_fixed++;
 }
References _rl_backspace(), _rl_last_c_pos, i, putc(), rl_display_fixed, rl_outstream, and visible_line.
Referenced by _rl_rubout_char().
_rl_erase_entire_line()
void _rl_erase_entire_line (void)
Definition at line 3429 of file display.c.
 {
   cr ();
   _rl_clear_to_eol (0);
   cr ();
   fflush (rl_outstream);
 }
References _rl_clear_to_eol(), cr(), fflush(), and rl_outstream.
Referenced by _rl_internal_char_cleanup(), and _rl_internal_pager().
_rl_errmsg()
void _rl_errmsg ()
Referenced by _rl_parse_colors(), _rl_with_macro_input(), rl_callback_read_char(), and vidomove_dispatch().
_rl_find_completion_word()
char _rl_find_completion_word (int * fp, int * dp)
Definition at line 1079 of file complete.c.
 {
   int scan, end, found_quote, delimiter, pass_next, isbrk;
   char quote_char;
   const char *brkchars;
   end = rl_point;
   found_quote = delimiter = 0;
   quote_char = '\0';
   brkchars = 0;
   if (rl_completion_word_break_hook)
     brkchars = (*rl_completion_word_break_hook) ();
   if (brkchars == 0)
     brkchars = rl_completer_word_break_characters;
   if (rl_completer_quote_characters)
     {
       /* We have a list of characters which can be used in pairs to
      quote substrings for the completer.  Try to find the start
      of an unclosed quoted substring. */
       /* FOUND_QUOTE is set so we know what kind of quotes we found. */
       for (scan = pass_next = 0; scan < end; scan = MB_NEXTCHAR (rl_line_buffer, scan, 1, MB_FIND_ANY))
     {
       if (pass_next)
         {
           pass_next = 0;
           continue;
         }
       /* Shell-like semantics for single quotes -- don't allow backslash
          to quote anything in single quotes, especially not the closing
          quote.  If you don't like this, take out the check on the value
          of quote_char. */
       if (quote_char != '\'' && rl_line_buffer[scan] == '\\')
         {
           pass_next = 1;
           found_quote |= RL_QF_BACKSLASH;
           continue;
         }
       if (quote_char != '\0')
         {
           /* Ignore everything until the matching close quote char. */
           if (rl_line_buffer[scan] == quote_char)
         {
           /* Found matching close.  Abandon this substring. */
           quote_char = '\0';
           rl_point = end;
         }
         }
       else if (strchr (rl_completer_quote_characters, rl_line_buffer[scan]))
         {
           /* Found start of a quoted substring. */
           quote_char = rl_line_buffer[scan];
           rl_point = scan + 1;
           /* Shell-like quoting conventions. */
           if (quote_char == '\'')
         found_quote |= RL_QF_SINGLE_QUOTE;
           else if (quote_char == '"')
         found_quote |= RL_QF_DOUBLE_QUOTE;
           else
         found_quote |= RL_QF_OTHER_QUOTE;
         }
     }
     }
   if (rl_point == end && quote_char == '\0')
     {
       /* We didn't find an unclosed quoted substring upon which to do
          completion, so use the word break characters to find the
          substring on which to complete. */
       while (rl_point = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_ANY))
     {
       scan = rl_line_buffer[rl_point];
       if (strchr (brkchars, scan) == 0)
         continue;
       /* Call the application-specific function to tell us whether
          this word break character is quoted and should be skipped. */
       if (rl_char_is_quoted_p && found_quote &&
           (*rl_char_is_quoted_p) (rl_line_buffer, rl_point))
         continue;
       /* Convoluted code, but it avoids an n^2 algorithm with calls
          to char_is_quoted. */
       break;
     }
     }
   /* If we are at an unquoted word break, then advance past it. */
   scan = rl_line_buffer[rl_point];
   /* If there is an application-specific function to say whether or not
      a character is quoted and we found a quote character, let that
      function decide whether or not a character is a word break, even
      if it is found in rl_completer_word_break_characters.  Don't bother
      if we're at the end of the line, though. */
   if (scan)
     {
       if (rl_char_is_quoted_p)
     isbrk = (found_quote == 0 ||
         (*rl_char_is_quoted_p) (rl_line_buffer, rl_point) == 0) &&
         strchr (brkchars, scan) != 0;
       else
     isbrk = strchr (brkchars, scan) != 0;
       if (isbrk)
     {
       /* If the character that caused the word break was a quoting
          character, then remember it as the delimiter. */
       if (rl_basic_quote_characters &&
           strchr (rl_basic_quote_characters, scan) &&
           (end - rl_point) > 1)
         delimiter = scan;
       /* If the character isn't needed to determine something special
          about what kind of completion to perform, then advance past it. */
       if (rl_special_prefixes == 0 || strchr (rl_special_prefixes, scan) == 0)
         rl_point++;
     }
     }
   if (fp)
     *fp = found_quote;
   if (dp)
     *dp = delimiter;
   return (quote_char);
 }
References MB_FIND_ANY, MB_NEXTCHAR, MB_PREVCHAR, rl_basic_quote_characters, rl_char_is_quoted_p, rl_completer_quote_characters, rl_completer_word_break_characters, rl_completion_word_break_hook, rl_line_buffer, rl_point, RL_QF_BACKSLASH, RL_QF_DOUBLE_QUOTE, RL_QF_OTHER_QUOTE, RL_QF_SINGLE_QUOTE, rl_special_prefixes, scan, and strchr().
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
_rl_fix_last_undo_of_type()
int _rl_fix_last_undo_of_type (int type, int start, int end)
Definition at line 274 of file undo.c.
 {
   UNDO_LIST *rl;
   for (rl = rl_undo_list; rl; rl = rl->next)
     {
       if (rl->what == type)
     {
       rl->start = start;
       rl->end = end;
       return 0;
     }
     }
   return 1;
 }
References undo_list::end, undo_list::next, rl_undo_list, undo_list::start, start(), type, and undo_list::what.
_rl_fix_mark()
void _rl_fix_mark (void)
Definition at line 183 of file text.c.
 {
   _RL_FIX_POINT (rl_mark);
 }
References _RL_FIX_POINT, and rl_mark.
Referenced by rl_delete_text().
_rl_fix_point()
void _rl_fix_point (int fix_mark_too)
Definition at line 175 of file text.c.
 {
   _RL_FIX_POINT (rl_point);
   if (fix_mark_too)
     _RL_FIX_POINT (rl_mark);
 }
References _RL_FIX_POINT, rl_mark, and rl_point.
Referenced by _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_nsearch_abort(), _rl_vi_domove_motion_cleanup(), _rl_vi_goto_mark(), make_history_line_current(), region_kill_internal(), rl_do_undo(), rl_kill_region(), rl_replace_line(), rl_transpose_chars(), and vi_yank_dispatch().
_rl_forward_char_internal()
int _rl_forward_char_internal (int count)
Definition at line 295 of file text.c.
 {
   int point;
 #if defined (HANDLE_MULTIBYTE)
   point = _rl_find_next_mbchar (rl_line_buffer, rl_point, count, MB_FIND_NONZERO);
 #if defined (VI_MODE)
   if (point >= rl_end && VI_COMMAND_MODE())
     point = _rl_find_prev_mbchar (rl_line_buffer, rl_end, MB_FIND_NONZERO);
 #endif
     if (rl_end < 0)
       rl_end = 0;
 #else
   point = rl_point + count;
 #endif
   if (point > rl_end)
     point = rl_end;
   return (point);
 }
References _rl_find_next_mbchar, _rl_find_prev_mbchar, count, MB_FIND_NONZERO, rl_end, rl_line_buffer, rl_point, and VI_COMMAND_MODE.
Referenced by _rl_vi_advance_point(), and rl_vi_column().
_rl_free_match_list()
void _rl_free_match_list (char ** matches)
Definition at line 1958 of file complete.c.
 {
   register int i;
   if (matches == 0)
     return;
   for (i = 0; matches[i]; i++)
     xfree (matches[i]);
   xfree (matches);
 }
References i, and xfree.
Referenced by _rl_complete_sigcleanup(), gen_completion_matches(), rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
_rl_free_saved_history_line()
int _rl_free_saved_history_line (void)
Definition at line 383 of file misc.c.
 {
   UNDO_LIST *orig;
   if (_rl_saved_line_for_history)
     {
       if (rl_undo_list && rl_undo_list == (UNDO_LIST *)_rl_saved_line_for_history->data)
     rl_undo_list = 0;
       /* Have to free this separately because _rl_free_history entry can't:
      it doesn't know whether or not this has application data. Only the
      callers that know this is _rl_saved_line_for_history can know that
      it's an undo list. */
       if (_rl_saved_line_for_history->data)
     _rl_free_undo_list ((UNDO_LIST *)_rl_saved_line_for_history->data);
       _rl_free_history_entry (_rl_saved_line_for_history);
       _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
     }
   return 0;
 }
References _rl_free_history_entry(), _rl_free_undo_list(), _rl_saved_line_for_history, _hist_entry::data, NULL, and rl_undo_list.
Referenced by _rl_start_using_history(), rl_get_previous_history(), rl_history_search_reinit(), and rl_vi_search().
_rl_free_undo_list()
void _rl_free_undo_list (UNDO_LIST * ul)
Definition at line 99 of file undo.c.
 {
   UNDO_LIST *release;
   while (ul)
     {
       release = ul;
       ul = ul->next;
       if (release->what == UNDO_DELETE)
     xfree (release->text);
       xfree (release);
     }
 }
References undo_list::next, undo_list::text, UNDO_DELETE, undo_list::what, and xfree.
Referenced by _rl_free_saved_history_line(), rl_clear_history(), and rl_free_undo_list().
_rl_get_screen_size()
void _rl_get_screen_size (int tty, int ignore_env)
Definition at line 256 of file terminal.c.
 {
   char *ss;
 #if defined (TIOCGWINSZ)
   struct winsize window_size;
 #endif /* TIOCGWINSZ */
   int wr, wc;
   wr = wc = -1;
 #if defined (TIOCGWINSZ)
   if (ioctl (tty, TIOCGWINSZ, &window_size) == 0)
     {
       wc = (int) window_size.ws_col;
       wr = (int) window_size.ws_row;
     }
 #endif /* TIOCGWINSZ */
 #if defined (__EMX__)
   _emx_get_screensize (&wc, &wr);
 #elif defined (__MINGW32__)
   _win_get_screensize (&wc, &wr);
 #endif
   if (ignore_env || rl_prefer_env_winsize == 0)
     {
       _rl_screenwidth = wc;
       _rl_screenheight = wr;
     }
   else
     _rl_screenwidth = _rl_screenheight = -1;
   /* Environment variable COLUMNS overrides setting of "co" if IGNORE_ENV
      is unset.  If we prefer the environment, check it first before
      assigning the value returned by the kernel. */
   if (_rl_screenwidth <= 0)
     {
       if (ignore_env == 0 && (ss = sh_get_env_value ("COLUMNS")))
     _rl_screenwidth = atoi (ss);
       if (_rl_screenwidth <= 0)
         _rl_screenwidth = wc;
 #if defined (__DJGPP__)
       if (_rl_screenwidth <= 0)
     _rl_screenwidth = ScreenCols ();
 #else
       if (_rl_screenwidth <= 0 && term_string_buffer)
     _rl_screenwidth = tgetnum ("co");
 #endif
     }
   /* Environment variable LINES overrides setting of "li" if IGNORE_ENV
      is unset. */
   if (_rl_screenheight <= 0)
     {
       if (ignore_env == 0 && (ss = sh_get_env_value ("LINES")))
     _rl_screenheight = atoi (ss);
       if (_rl_screenheight <= 0)
         _rl_screenheight = wr;
 #if defined (__DJGPP__)
       if (_rl_screenheight <= 0)
     _rl_screenheight = ScreenRows ();
 #else
       if (_rl_screenheight <= 0 && term_string_buffer)
     _rl_screenheight = tgetnum ("li");
 #endif
     }
   /* If all else fails, default to 80x24 terminal. */
   if (_rl_screenwidth <= 1)
     _rl_screenwidth = 80;
   if (_rl_screenheight <= 0)
     _rl_screenheight = 24;
   /* If we're being compiled as part of bash, set the environment
      variables $LINES and $COLUMNS to new values.  Otherwise, just
      do a pair of putenv () or setenv () calls. */
   if (rl_change_environment)
     sh_set_lines_and_columns (_rl_screenheight, _rl_screenwidth);
   if (_rl_term_autowrap == 0)
     _rl_screenwidth--;
   _rl_screenchars = _rl_screenwidth * _rl_screenheight;
 }
References _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_autowrap, atoi(), int, ioctl(), rl_change_environment, rl_prefer_env_winsize, sh_get_env_value(), sh_set_lines_and_columns(), term_string_buffer, tgetnum(), TIOCGWINSZ, winsize::ws_col, and winsize::ws_row.
Referenced by _rl_init_terminal_io(), _rl_sigwinch_resize_terminal(), expand_prompt(), rl_reset_screen_size(), and rl_resize_terminal().
_rl_init_eightbit()
int _rl_init_eightbit (void)
Definition at line 226 of file nls.c.
 {
   char *t, *ol;
   ol = _rl_current_locale;
   t = _rl_init_locale ();   /* resets _rl_current_locale, returns static pointer */
   xfree (ol);
   return (_rl_set_localevars (t, 0));
 }
References _rl_current_locale, _rl_init_locale(), _rl_set_localevars(), t, and xfree.
Referenced by readline_initialize_everything().
_rl_init_executing_keyseq()
void _rl_init_executing_keyseq (void)
Definition at line 1543 of file readline.c.
 {
   rl_executing_keyseq[rl_key_sequence_length = 0] = '\0';
 }
References rl_executing_keyseq, and rl_key_sequence_length.
Referenced by _rl_isearch_dispatch(), and _rl_isearch_init().
_rl_init_line_state()
void _rl_init_line_state (void)
Definition at line 738 of file readline.c.
 {
   rl_point = rl_end = rl_mark = 0;
   the_line = rl_line_buffer;
   the_line[0] = 0;
 }
References rl_end, rl_line_buffer, rl_mark, rl_point, and the_line.
Referenced by rl_callback_read_char(), and rl_initialize().
_rl_init_locale()
char* _rl_init_locale (void)
Definition at line 127 of file nls.c.
 {
   char *ret, *lspec;
   /* Set the LC_CTYPE locale category from environment variables. */
   lspec = _rl_get_locale_var ("LC_CTYPE");
   /* Since _rl_get_locale_var queries the right environment variables,
      we query the current locale settings with setlocale(), and, if
      that doesn't return anything, we set lspec to the empty string to
      force the subsequent call to setlocale() to define the `native'
      environment. */
 #if defined (HAVE_SETLOCALE)
   if (lspec == 0 || *lspec == 0)
     lspec = setlocale (LC_CTYPE, (char *)NULL);
   if (lspec == 0)
     lspec = "";
   ret = setlocale (LC_CTYPE, lspec);    /* ok, since it does not change locale */
   if (ret == 0 || *ret == 0)
     ret = setlocale (LC_CTYPE, (char *)NULL);
   if (ret == 0 || *ret == 0)
     ret = RL_DEFAULT_LOCALE;
 #else
   ret = (lspec == 0 || *lspec == 0) ? RL_DEFAULT_LOCALE : lspec;
 #endif
   _rl_utf8locale = (ret && *ret) ? utf8locale (ret) : 0;
   _rl_current_locale = savestring (ret);
   return ret;
 }
References _rl_current_locale, _rl_get_locale_var(), _rl_utf8locale, LC_CTYPE, NULL, ret, RL_DEFAULT_LOCALE, savestring(), setlocale, and utf8locale().
Referenced by _rl_init_eightbit(), and _rl_reset_locale().
_rl_init_terminal_io()
int _rl_init_terminal_io (const char * terminal_name)
Definition at line 470 of file terminal.c.
 {
   const char *term;
   char *buffer;
   int tty, tgetent_ret, dumbterm, reset_region_colors;
   term = terminal_name ? terminal_name : sh_get_env_value ("TERM");
   _rl_term_clrpag = _rl_term_cr = _rl_term_clreol = _rl_term_clrscroll = (char *)NULL;
   tty = rl_instream ? fileno (rl_instream) : 0;
   if (term == 0)
     term = "dumb";
   dumbterm = STREQ (term, "dumb");
   reset_region_colors = 1;
 #ifdef __MSDOS__
   _rl_term_im = _rl_term_ei = _rl_term_ic = _rl_term_IC = (char *)NULL;
   _rl_term_up = _rl_term_dc = _rl_term_DC = _rl_visible_bell = (char *)NULL;
   _rl_term_ku = _rl_term_kd = _rl_term_kl = _rl_term_kr = (char *)NULL;
   _rl_term_mm = _rl_term_mo = (char *)NULL;
   _rl_terminal_can_insert = term_has_meta = _rl_term_autowrap = 0;
   _rl_term_cr = "\r";
   _rl_term_backspace = (char *)NULL;
   _rl_term_goto = _rl_term_pc = _rl_term_ip = (char *)NULL;
   _rl_term_ks = _rl_term_ke =_rl_term_vs = _rl_term_ve = (char *)NULL;
   _rl_term_kh = _rl_term_kH = _rl_term_at7 = _rl_term_kI = (char *)NULL;
   _rl_term_kN = _rl_term_kP = (char *)NULL;
   _rl_term_so = _rl_term_se = (char *)NULL;
 #if defined(HACK_TERMCAP_MOTION)
   _rl_term_forward_char = (char *)NULL;
 #endif
   _rl_get_screen_size (tty, 0);
 #else  /* !__MSDOS__ */
   /* I've separated this out for later work on not calling tgetent at all
      if the calling application has supplied a custom redisplay function,
      (and possibly if the application has supplied a custom input function). */
   if (CUSTOM_REDISPLAY_FUNC())
     {
       tgetent_ret = -1;
     }
   else
     {
       if (term_string_buffer == 0)
     term_string_buffer = (char *)xmalloc(2032);
       if (term_buffer == 0)
     term_buffer = (char *)xmalloc(4080);
       buffer = term_string_buffer;
       tgetent_ret = tgetent (term_buffer, term);
     }
   if (tgetent_ret != TGETENT_SUCCESS)
     {
       FREE (term_string_buffer);
       FREE (term_buffer);
       buffer = term_buffer = term_string_buffer = (char *)NULL;
       _rl_term_autowrap = 0;    /* used by _rl_get_screen_size */
       /* Allow calling application to set default height and width, using
      rl_set_screen_size */
       if (_rl_screenwidth <= 0 || _rl_screenheight <= 0)
     {
 #if defined (__EMX__)
       _emx_get_screensize (&_rl_screenwidth, &_rl_screenheight);
       _rl_screenwidth--;
 #else /* !__EMX__ */
       _rl_get_screen_size (tty, 0);
 #endif /* !__EMX__ */
     }
       /* Defaults. */
       if (_rl_screenwidth <= 0 || _rl_screenheight <= 0)
         {
       _rl_screenwidth = 79;
       _rl_screenheight = 24;
         }
       /* Everything below here is used by the redisplay code (tputs). */
       _rl_screenchars = _rl_screenwidth * _rl_screenheight;
       _rl_term_cr = "\r";
       _rl_term_im = _rl_term_ei = _rl_term_ic = _rl_term_IC = (char *)NULL;
       _rl_term_up = _rl_term_dc = _rl_term_DC = _rl_visible_bell = (char *)NULL;
       _rl_term_ku = _rl_term_kd = _rl_term_kl = _rl_term_kr = (char *)NULL;
       _rl_term_kh = _rl_term_kH = _rl_term_kI = _rl_term_kD = (char *)NULL;
       _rl_term_ks = _rl_term_ke = _rl_term_at7 = (char *)NULL;
       _rl_term_kN = _rl_term_kP = (char *)NULL;
       _rl_term_mm = _rl_term_mo = (char *)NULL;
       _rl_term_ve = _rl_term_vs = (char *)NULL;
       _rl_term_forward_char = (char *)NULL;
       _rl_term_so = _rl_term_se = (char *)NULL;
       _rl_terminal_can_insert = term_has_meta = 0;
       /* Assume generic unknown terminal can't handle the enable/disable
      escape sequences */
       _rl_enable_bracketed_paste = 0;
       /* No terminal so/se capabilities. */
       _rl_enable_active_region = 0;
       _rl_reset_region_color (0, NULL);
       _rl_reset_region_color (1, NULL);
       /* Reasonable defaults for tgoto().  Readline currently only uses
          tgoto if _rl_term_IC or _rl_term_DC is defined, but just in case we
          change that later... */
       PC = '\0';
       BC = _rl_term_backspace = "\b";
       UP = _rl_term_up;
       return 0;
     }
   get_term_capabilities (&buffer);
   /* Set up the variables that the termcap library expects the application
      to provide. */
   PC = _rl_term_pc ? *_rl_term_pc : 0;
   BC = _rl_term_backspace;
   UP = _rl_term_up;
   if (_rl_term_cr == 0)
     _rl_term_cr = "\r";
   _rl_term_autowrap = TGETFLAG ("am") && TGETFLAG ("xn");
   /* Allow calling application to set default height and width, using
      rl_set_screen_size */
   if (_rl_screenwidth <= 0 || _rl_screenheight <= 0)
     _rl_get_screen_size (tty, 0);
   /* "An application program can assume that the terminal can do
       character insertion if *any one of* the capabilities `IC',
       `im', `ic' or `ip' is provided."  But we can't do anything if
       only `ip' is provided, so... */
   _rl_terminal_can_insert = (_rl_term_IC || _rl_term_im || _rl_term_ic);
   /* Check to see if this terminal has a meta key and clear the capability
      variables if there is none. */
   term_has_meta = TGETFLAG ("km");
   if (term_has_meta == 0)
     _rl_term_mm = _rl_term_mo = (char *)NULL;
 #endif /* !__MSDOS__ */
   /* Attempt to find and bind the arrow keys.  Do not override already
      bound keys in an overzealous attempt, however. */
   bind_termcap_arrow_keys (emacs_standard_keymap);
 #if defined (VI_MODE)
   bind_termcap_arrow_keys (vi_movement_keymap);
   bind_termcap_arrow_keys (vi_insertion_keymap);
 #endif /* VI_MODE */
   /* There's no way to determine whether or not a given terminal supports
      bracketed paste mode, so we assume a terminal named "dumb" does not. */
   if (dumbterm)
     _rl_enable_bracketed_paste = _rl_enable_active_region = 0;
   if (reset_region_colors)
     {
       _rl_reset_region_color (0, _rl_term_so);
       _rl_reset_region_color (1, _rl_term_se);
     }
   return 0;
 }
References _rl_enable_active_region, _rl_enable_bracketed_paste, _rl_get_screen_size(), _rl_reset_region_color(), _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_at7, _rl_term_autowrap, _rl_term_backspace, _rl_term_clreol, _rl_term_clrpag, _rl_term_clrscroll, _rl_term_cr, _rl_term_dc, _rl_term_DC, _rl_term_ei, _rl_term_forward_char, _rl_term_goto, _rl_term_ic, _rl_term_IC, _rl_term_im, _rl_term_ip, _rl_term_kd, _rl_term_kD, _rl_term_ke, _rl_term_kh, _rl_term_kH, _rl_term_kI, _rl_term_kl, _rl_term_kN, _rl_term_kP, _rl_term_kr, _rl_term_ks, _rl_term_ku, _rl_term_mm, _rl_term_mo, _rl_term_pc, _rl_term_se, _rl_term_so, _rl_term_up, _rl_term_ve, _rl_term_vs, _rl_terminal_can_insert, _rl_visible_bell, BC, bind_termcap_arrow_keys(), buffer, CUSTOM_REDISPLAY_FUNC, emacs_standard_keymap, fileno(), FREE, get_term_capabilities(), NULL, PC, rl_instream, sh_get_env_value(), STREQ, term, term_buffer, term_has_meta, term_string_buffer, tgetent(), TGETENT_SUCCESS, TGETFLAG, UP, vi_insertion_keymap, vi_movement_keymap, and xmalloc.
Referenced by _rl_set_screen_size(), readline_initialize_everything(), and rl_reset_terminal().
_rl_input_available()
int _rl_input_available (void)
Definition at line 369 of file input.c.
 {
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
   fd_set readfds, exceptfds;
   struct timeval timeout;
 #endif
 #if !defined (HAVE_SELECT) && defined (FIONREAD)
   int chars_avail;
 #endif
   int tty;
   if (rl_input_available_hook)
     return (*rl_input_available_hook) ();
   tty = fileno (rl_instream);
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
   FD_ZERO (&readfds);
   FD_ZERO (&exceptfds);
   FD_SET (tty, &readfds);
   FD_SET (tty, &exceptfds);
   USEC_TO_TIMEVAL (_keyboard_input_timeout, timeout);
 #  if defined (RL_TIMEOUT_USE_SELECT)
   return (_rl_timeout_select (tty + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout, NULL) > 0);
 #  else
   return (select (tty + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout) > 0);
 #  endif
 #else
 #if defined (FIONREAD)
   if (ioctl (tty, FIONREAD, &chars_avail) == 0)
     return (chars_avail);
 #endif
 #endif
 #if defined (__MINGW32__)
   if (isatty (tty))
     return (_kbhit ());
 #endif
   return 0;
 }
References _keyboard_input_timeout, _rl_timeout_select(), FD_SET, FD_ZERO, fileno(), FIONREAD, ioctl(), isatty(), NULL, rl_input_available_hook, rl_instream, select(), and USEC_TO_TIMEVAL.
Referenced by _rl_input_queued(), and _rl_isearch_dispatch().
_rl_input_queued()
int _rl_input_queued (int t)
Definition at line 432 of file input.c.
 {
   int old_timeout, r;
   old_timeout = rl_set_keyboard_input_timeout (t);
   r = _rl_input_available ();
   rl_set_keyboard_input_timeout (old_timeout);
   return r;
 }
References _rl_input_available(), r, rl_set_keyboard_input_timeout(), and t.
Referenced by _rl_dispatch_subseq(), _rl_isearch_dispatch(), _rl_read_bracketed_paste_prefix(), and rl_insert().
_rl_insert_char()
int _rl_insert_char (int count, int c)
Definition at line 709 of file text.c.
 {
   register int i;
   char *string;
 #ifdef HANDLE_MULTIBYTE
   int string_size;
   char incoming[MB_LEN_MAX + 1];
   int incoming_length = 0;
   mbstate_t ps_back;
   static int stored_count = 0;
 #endif
   if (count <= 0)
     return 0;
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX == 1 || rl_byte_oriented)
     {
       incoming[0] = c;
       incoming[1] = '\0';
       incoming_length = 1;
     }
   else if (_rl_utf8locale && (c & 0x80) == 0)
     {
       incoming[0] = c;
       incoming[1] = '\0';
       incoming_length = 1;
     }
   else
     {
       WCHAR_T wc;
       size_t ret;
       if (stored_count <= 0)
     stored_count = count;
       else
     count = stored_count;
       ps_back = ps;
       pending_bytes[pending_bytes_length++] = c;
       ret = MBRTOWC (&wc, pending_bytes, pending_bytes_length, &ps);
       if (ret == (size_t)-2)
     {
       /* Bytes too short to compose character, try to wait for next byte.
          Restore the state of the byte sequence, because in this case the
          effect of mbstate is undefined. */
       ps = ps_back;
       return 1;
     }
       else if (ret == (size_t)-1)
     {
       /* Invalid byte sequence for the current locale.  Treat first byte
          as a single character. */
       incoming[0] = pending_bytes[0];
       incoming[1] = '\0';
       incoming_length = 1;
       pending_bytes_length--;
       memmove (pending_bytes, pending_bytes + 1, pending_bytes_length);
       /* Clear the state of the byte sequence, because in this case the
          effect of mbstate is undefined. */
       memset (&ps, 0, sizeof (mbstate_t));
     }
       else if (ret == (size_t)0)
     {
       incoming[0] = '\0';
       incoming_length = 0;
       pending_bytes_length--;
       /* Clear the state of the byte sequence, because in this case the
          effect of mbstate is undefined. */
       memset (&ps, 0, sizeof (mbstate_t));
     }
       else if (ret == 1)
     {
       incoming[0] = pending_bytes[0];
       incoming[incoming_length = 1] = '\0';
       pending_bytes_length = 0;
     }
       else
     {
       /* We successfully read a single multibyte character. */
       memcpy (incoming, pending_bytes, pending_bytes_length);
       incoming[pending_bytes_length] = '\0';
       incoming_length = pending_bytes_length;
       pending_bytes_length = 0;
     }
     }
 #endif /* HANDLE_MULTIBYTE */
   /* If we can optimize, then do it.  But don't let people crash
      readline because of extra large arguments. */
   if (count > 1 && count <= TEXT_COUNT_MAX)
     {
 #if defined (HANDLE_MULTIBYTE)
       string_size = count * incoming_length;
       string = (char *)xmalloc (1 + string_size);
       i = 0;
       while (i < string_size)
     {
       if (incoming_length == 1)
         string[i++] = *incoming;
       else
         {
           strncpy (string + i, incoming, incoming_length);
           i += incoming_length;
         }
     }
       incoming_length = 0;
       stored_count = 0;
 #else /* !HANDLE_MULTIBYTE */
       string = (char *)xmalloc (1 + count);
       for (i = 0; i < count; i++)
     string[i] = c;
 #endif /* !HANDLE_MULTIBYTE */
       string[i] = '\0';
       rl_insert_text (string);
       xfree (string);
       return 0;
     }
   if (count > TEXT_COUNT_MAX)
     {
       int decreaser;
 #if defined (HANDLE_MULTIBYTE)
       string_size = incoming_length * TEXT_COUNT_MAX;
       string = (char *)xmalloc (1 + string_size);
       i = 0;
       while (i < string_size)
     {
       if (incoming_length == 1)
         string[i++] = *incoming;
       else
         {
           strncpy (string + i, incoming, incoming_length);
           i += incoming_length;
         }
     }
       while (count)
     {
       decreaser = (count > TEXT_COUNT_MAX) ? TEXT_COUNT_MAX : count;
       string[decreaser*incoming_length] = '\0';
       rl_insert_text (string);
       count -= decreaser;
     }
       xfree (string);
       incoming_length = 0;
       stored_count = 0;
 #else /* !HANDLE_MULTIBYTE */
       char str[TEXT_COUNT_MAX+1];
       for (i = 0; i < TEXT_COUNT_MAX; i++)
     str[i] = c;
       while (count)
     {
       decreaser = (count > TEXT_COUNT_MAX ? TEXT_COUNT_MAX : count);
       str[decreaser] = '\0';
       rl_insert_text (str);
       count -= decreaser;
     }
 #endif /* !HANDLE_MULTIBYTE */
       return 0;
     }
   if (MB_CUR_MAX == 1 || rl_byte_oriented)
     {
       /* We are inserting a single character.
      If there is pending input, then make a string of all of the
      pending characters that are bound to rl_insert, and insert
      them all.  Don't do this if we're current reading input from
      a macro. */
       if ((RL_ISSTATE (RL_STATE_MACROINPUT) == 0) && _rl_pushed_input_available ())
     _rl_insert_typein (c);
       else
     {
       /* Inserting a single character. */
       char str[2];
       str[1] = '\0';
       str[0] = c;
       rl_insert_text (str);
     }
     }
 #if defined (HANDLE_MULTIBYTE)
   else
     {
       rl_insert_text (incoming);
       stored_count = 0;
     }
 #endif
   return 0;
 }
References _rl_insert_typein(), _rl_pushed_input_available(), _rl_utf8locale, c, count, i, MB_CUR_MAX, MB_LEN_MAX, MBRTOWC, memcpy, memmove, memset, ret, rl_byte_oriented, rl_insert_text(), RL_ISSTATE, RL_STATE_MACROINPUT, str, string, strncpy(), TEXT_COUNT_MAX, WCHAR_T, xfree, and xmalloc.
Referenced by _rl_insert_next(), _rl_nsearch_dispatch(), _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_vi_change_char(), rl_complete(), rl_insert(), rl_insert_close(), rl_tab_insert(), and rl_vi_change_case().
_rl_insert_typein()
void _rl_insert_typein (int c)
Definition at line 443 of file input.c.
 {
   int key, t, i;
   char *string;
   i = key = 0;
   string = (char *)xmalloc (ibuffer_len + 1);
   string[i++] = (char) c;
   while ((t = rl_get_char (&key)) &&
      _rl_keymap[key].type == ISFUNC &&
      _rl_keymap[key].function == rl_insert)
     string[i++] = key;
   if (t)
     _rl_unget_char (key);
   string[i] = '\0';
   rl_insert_text (string);
   xfree (string);
 }
References _rl_keymap, _rl_unget_char(), c, i, ibuffer_len, ISFUNC, rl_get_char(), rl_insert(), rl_insert_text(), string, t, type, xfree, and xmalloc.
Referenced by _rl_insert_char().
_rl_internal_char_cleanup()
void _rl_internal_char_cleanup (void)
Definition at line 526 of file readline.c.
 {
   if (_rl_keep_mark_active)
     _rl_keep_mark_active = 0;
   else if (rl_mark_active_p ())
     rl_deactivate_mark ();
 #if defined (VI_MODE)
   /* In vi mode, when you exit insert mode, the cursor moves back
      over the previous character.  We explicitly check for that here. */
   if (rl_editing_mode == vi_mode && _rl_keymap == vi_movement_keymap)
     rl_vi_check ();
 #endif /* VI_MODE */
   if (rl_num_chars_to_read && rl_end >= rl_num_chars_to_read)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
       rl_newline (1, '\n');
     }
   if (rl_done == 0)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
     }
   /* If the application writer has told us to erase the entire line if
      the only character typed was something bound to rl_newline, do so. */
   if (rl_erase_empty_line && rl_done && rl_last_func == rl_newline &&
       rl_point == 0 && rl_end == 0)
     _rl_erase_entire_line ();
 }
References _rl_erase_entire_line(), _rl_keep_mark_active, _rl_keymap, _rl_want_redisplay, rl_deactivate_mark(), rl_done, rl_editing_mode, rl_end, rl_erase_empty_line, rl_last_func, rl_mark_active_p(), rl_newline(), rl_num_chars_to_read, rl_point, rl_vi_check(), vi_mode, and vi_movement_keymap.
Referenced by readline_internal_char(), and rl_callback_read_char().
_rl_isearch_callback()
int _rl_isearch_callback (_rl_search_cxt * cxt)
Definition at line 883 of file isearch.c.
 {
   int c, r;
   c = _rl_search_getchar (cxt);
   /* We might want to handle EOF here */
   r = _rl_isearch_dispatch (cxt, cxt->lastc);
   return (r <= 0) ? _rl_isearch_cleanup (cxt, r) : 0;
 }
References _rl_isearch_cleanup(), _rl_isearch_dispatch(), _rl_search_getchar(), c, __rl_search_context::lastc, and r.
Referenced by rl_callback_read_char().
_rl_isearch_cleanup()
int _rl_isearch_cleanup (_rl_search_cxt * cxt, int r)
Definition at line 828 of file isearch.c.
 {
   if (r >= 0)
     _rl_isearch_fini (cxt);
   _rl_scxt_dispose (cxt, 0);
   _rl_iscxt = 0;
   RL_UNSETSTATE(RL_STATE_ISEARCH);
   return (r != 0);
 }
References _rl_iscxt, _rl_isearch_fini(), _rl_scxt_dispose(), r, RL_STATE_ISEARCH, and RL_UNSETSTATE.
Referenced by _rl_isearch_callback(), rl_callback_sigcleanup(), and rl_search_history().
_rl_isearch_dispatch()
int _rl_isearch_dispatch (_rl_search_cxt * cxt, int c)
Definition at line 341 of file isearch.c.
 {
   int n, wstart, wlen, limit, cval, incr;
   char *paste;
   size_t pastelen;
   int j;
   rl_command_func_t *f;
   f = (rl_command_func_t *)NULL;
   if (c < 0)
     {
       cxt->sflags |= SF_FAILED;
       cxt->history_pos = cxt->last_found_line;
       return -1;
     }
   _rl_add_executing_keyseq (c);
   /* XXX - experimental code to allow users to bracketed-paste into the search
      string even when ESC is one of the isearch-terminators. Not perfect yet. */
   if (_rl_enable_bracketed_paste && c == ESC && strchr (cxt->search_terminators, c) && (n = _rl_nchars_available ()) > (BRACK_PASTE_SLEN-1))
     {
       j = _rl_read_bracketed_paste_prefix (c);
       if (j == 1)
     {
       cxt->lastc = -7;      /* bracketed paste, see below */
       goto opcode_dispatch;
         }
       else if (_rl_pushed_input_available ())   /* eat extra char we pushed back */
     c = cxt->lastc = rl_read_key ();
       else
     c = cxt->lastc;         /* last ditch */
     }
   /* If we are moving into a new keymap, modify cxt->keymap and go on.
      This can be a problem if c == ESC and we want to terminate the
      incremental search, so we check */
   if (c >= 0 && cxt->keymap[c].type == ISKMAP && strchr (cxt->search_terminators, cxt->lastc) == 0)
     {
       /* _rl_keyseq_timeout specified in milliseconds; _rl_input_queued
      takes microseconds, so multiply by 1000.  If we don't get any
      additional input and this keymap shadows another function, process
      that key as if it was all we read. */
       if (_rl_keyseq_timeout > 0 &&
         RL_ISSTATE (RL_STATE_CALLBACK) == 0 &&
         RL_ISSTATE (RL_STATE_INPUTPENDING) == 0 &&
         _rl_pushed_input_available () == 0 &&
         ((Keymap)(cxt->keymap[c].function))[ANYOTHERKEY].function &&
         _rl_input_queued (_rl_keyseq_timeout*1000) == 0)
     goto add_character;
       cxt->okeymap = cxt->keymap;
       cxt->keymap = FUNCTION_TO_KEYMAP (cxt->keymap, c);
       cxt->sflags |= SF_CHGKMAP;
       /* XXX - we should probably save this sequence, so we can do
      something useful if this doesn't end up mapping to a command we
      interpret here.  Right now we just save the most recent character
      that caused the index into a new keymap. */
       cxt->prevc = c;
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       if (cxt->mb[1] == 0)
         {
           cxt->pmb[0] = c;      /* XXX should be == cxt->mb[0] */
           cxt->pmb[1] = '\0';
         }
       else
         memcpy (cxt->pmb, cxt->mb, sizeof (cxt->pmb));
     }
 #endif
       return 1;
     }
 add_character:
   /* Translate the keys we do something with to opcodes. */
   if (c >= 0 && cxt->keymap[c].type == ISFUNC)
     {
       /* If we have a multibyte character, see if it's bound to something that
      affects the search. */
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0 && cxt->mb[1])
     f = rl_function_of_keyseq (cxt->mb, cxt->keymap, (int *)NULL);
       else
 #endif
     {
       f = cxt->keymap[c].function;
       if (f == rl_do_lowercase_version)
         f = cxt->keymap[_rl_to_lower (c)].function;
     }
       if (f == rl_reverse_search_history)
     cxt->lastc = (cxt->sflags & SF_REVERSE) ? -1 : -2;
       else if (f == rl_forward_search_history)
     cxt->lastc = (cxt->sflags & SF_REVERSE) ? -2 : -1;
       else if (f == rl_rubout)
     cxt->lastc = -3;
       else if (c == CTRL ('G') || f == rl_abort)
     cxt->lastc = -4;
       else if (c == CTRL ('W') || f == rl_unix_word_rubout) /* XXX */
     cxt->lastc = -5;
       else if (c == CTRL ('Y') || f == rl_yank) /* XXX */
     cxt->lastc = -6;
       else if (f == rl_bracketed_paste_begin)
     cxt->lastc = -7;
     }
   /* If we changed the keymap earlier while translating a key sequence into
      a command, restore it now that we've succeeded. */
   if (cxt->sflags & SF_CHGKMAP)
     {
       cxt->keymap = cxt->okeymap;
       cxt->sflags &= ~SF_CHGKMAP;
       /* If we indexed into a new keymap, but didn't map to a command that
      affects the search (lastc > 0), and the character that mapped to a
      new keymap would have ended the search (ENDSRCH_CHAR(cxt->prevc)),
      handle that now as if the previous char would have ended the search
      and we would have read the current character. */
       /* XXX - should we check cxt->mb? */
       if (cxt->lastc > 0 && ENDSRCH_CHAR (cxt->prevc))
     {
       rl_stuff_char (cxt->lastc);
       rl_execute_next (cxt->prevc);
       /* XXX - do we insert everything in cxt->pmb? */
       return (0);
     }
       /* Otherwise, if the current character is mapped to self-insert or
      nothing (i.e., not an editing command), and the previous character
      was a keymap index, then we need to insert both the previous
      character and the current character into the search string. */
       else if (cxt->lastc > 0 && cxt->prevc > 0 &&
            cxt->keymap[cxt->prevc].type == ISKMAP &&
            (f == 0 || f == rl_insert))
     {
       /* Make lastc be the next character read */
       /* XXX - do we insert everything in cxt->mb? */
       rl_execute_next (cxt->lastc);
       /* Dispatch on the previous character (insert into search string) */
       cxt->lastc = cxt->prevc;
 #if defined (HANDLE_MULTIBYTE)
       /* Have to overwrite cxt->mb here because dispatch uses it below */
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
         {
           if (cxt->pmb[1] == 0)
         {
           cxt->mb[0] = cxt->lastc;  /* == cxt->prevc */
           cxt->mb[1] = '\0';
         }
           else
         memcpy (cxt->mb, cxt->pmb, sizeof (cxt->mb));
         }
 #endif
       cxt->prevc = 0;
     }
       else if (cxt->lastc > 0 && cxt->prevc > 0 && f && f != rl_insert)
     {
       _rl_term_executing_keyseq ();     /* should this go in the caller? */
       _rl_pending_command.map = cxt->keymap;
       _rl_pending_command.count = 1;    /* XXX */
       _rl_pending_command.key = cxt->lastc;
       _rl_pending_command.func = f;
       _rl_command_to_execute = &_rl_pending_command;
       return (0);
     }
     }
   /* The characters in isearch_terminators (set from the user-settable
      variable isearch-terminators) are used to terminate the search but
      not subsequently execute the character as a command.  The default
      value is "\033\012" (ESC and C-J). */
   if (cxt->lastc > 0 && strchr (cxt->search_terminators, cxt->lastc))
     {
       /* ESC still terminates the search, but if there is pending
      input or if input arrives within 0.1 seconds (on systems
      with select(2)) it is used as a prefix character
      with rl_execute_next.  WATCH OUT FOR THIS!  This is intended
      to allow the arrow keys to be used like ^F and ^B are used
      to terminate the search and execute the movement command.
      XXX - since _rl_input_available depends on the application-
      settable keyboard timeout value, this could alternatively
      use _rl_input_queued(100000) */
       if (cxt->lastc == ESC && (_rl_pushed_input_available () || _rl_input_available ()))
     rl_execute_next (ESC);
       return (0);
     }
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       if (cxt->lastc >= 0 && (cxt->mb[0] && cxt->mb[1] == '\0') && ENDSRCH_CHAR (cxt->lastc))
     {
       /* This sets rl_pending_input to LASTC; it will be picked up the next
          time rl_read_key is called. */
       rl_execute_next (cxt->lastc);
       return (0);
     }
     }
   else
 #endif
     if (cxt->lastc >= 0 && ENDSRCH_CHAR (cxt->lastc))
       {
     /* This sets rl_pending_input to LASTC; it will be picked up the next
        time rl_read_key is called. */
     rl_execute_next (cxt->lastc);
     return (0);
       }
   _rl_init_executing_keyseq ();
 opcode_dispatch:
   /* Now dispatch on the character.  `Opcodes' affect the search string or
      state.  Other characters are added to the string.  */
   switch (cxt->lastc)
     {
     /* search again */
     case -1:
       if (cxt->search_string_index == 0)
     {
       if (last_isearch_string)
         {
           cxt->search_string_size = 64 + last_isearch_string_len;
           cxt->search_string = (char *)xrealloc (cxt->search_string, cxt->search_string_size);
           strcpy (cxt->search_string, last_isearch_string);
           cxt->search_string_index = last_isearch_string_len;
           rl_display_search (cxt->search_string, cxt->sflags, -1);
           break;
         }
       /* XXX - restore keymap here? */
       return (1);
     }
       else if ((cxt->sflags & SF_REVERSE) && cxt->sline_index >= 0)
     cxt->sline_index--;
       else if (cxt->sline_index != cxt->sline_len)
     cxt->sline_index++;
       else
     rl_ding ();
       break;
     /* switch directions */
     case -2:
       cxt->direction = -cxt->direction;
       if (cxt->direction < 0)
     cxt->sflags |= SF_REVERSE;
       else
     cxt->sflags &= ~SF_REVERSE;
       break;
     /* delete character from search string. */
     case -3:    /* C-H, DEL */
       /* This is tricky.  To do this right, we need to keep a
      stack of search positions for the current search, with
      sentinels marking the beginning and end.  But this will
      do until we have a real isearch-undo. */
       if (cxt->search_string_index == 0)
     rl_ding ();
       else if (MB_CUR_MAX == 1 || rl_byte_oriented)
     cxt->search_string[--cxt->search_string_index] = '\0';
       else
     {
       wstart = _rl_find_prev_mbchar (cxt->search_string, cxt->search_string_index, MB_FIND_NONZERO);
       if (wstart >= 0)
         cxt->search_string[cxt->search_string_index = wstart] = '\0';
       else
         cxt->search_string[cxt->search_string_index = 0] = '\0';
     }
       if (cxt->search_string_index == 0)
     rl_ding ();
       break;
     case -4:    /* C-G, abort */
       rl_replace_line (cxt->lines[cxt->save_line], 0);
       rl_point = cxt->save_point;
       rl_mark = cxt->save_mark;
       rl_deactivate_mark ();
       rl_restore_prompt();
       rl_clear_message ();
       _rl_fix_point (1);    /* in case save_line and save_point are out of sync */
       return -1;
     case -5:    /* C-W */
       /* skip over portion of line we already matched and yank word */
       wstart = rl_point + cxt->search_string_index;
       if (wstart >= rl_end)
     {
       rl_ding ();
       break;
     }
       /* if not in a word, move to one. */
       cval = _rl_char_value (rl_line_buffer, wstart);
       if (_rl_walphabetic (cval) == 0)
     {
       rl_ding ();
       break;
     }
       n = MB_NEXTCHAR (rl_line_buffer, wstart, 1, MB_FIND_NONZERO);;
       while (n < rl_end)
     {
       cval = _rl_char_value (rl_line_buffer, n);
       if (_rl_walphabetic (cval) == 0)
         break;
       n = MB_NEXTCHAR (rl_line_buffer, n, 1, MB_FIND_NONZERO);;
     }
       wlen = n - wstart + 1;
       if (cxt->search_string_index + wlen + 1 >= cxt->search_string_size)
     {
       cxt->search_string_size += wlen + 1;
       cxt->search_string = (char *)xrealloc (cxt->search_string, cxt->search_string_size);
     }
       for (; wstart < n; wstart++)
     cxt->search_string[cxt->search_string_index++] = rl_line_buffer[wstart];
       cxt->search_string[cxt->search_string_index] = '\0';
       break;
     case -6:    /* C-Y */
       /* skip over portion of line we already matched and yank rest */
       wstart = rl_point + cxt->search_string_index;
       if (wstart >= rl_end)
     {
       rl_ding ();
       break;
     }
       n = rl_end - wstart + 1;
       if (cxt->search_string_index + n + 1 >= cxt->search_string_size)
     {
       cxt->search_string_size += n + 1;
       cxt->search_string = (char *)xrealloc (cxt->search_string, cxt->search_string_size);
     }
       for (n = wstart; n < rl_end; n++)
     cxt->search_string[cxt->search_string_index++] = rl_line_buffer[n];
       cxt->search_string[cxt->search_string_index] = '\0';
       break;
     case -7:    /* bracketed paste */
       paste = _rl_bracketed_text (&pastelen);
       if (paste == 0 || *paste == 0)
     {
       xfree (paste);
       break;
     }
       if (_rl_enable_active_region)
     rl_activate_mark ();
       if (cxt->search_string_index + pastelen + 1 >= cxt->search_string_size)
     {
       cxt->search_string_size += pastelen + 2;
       cxt->search_string = (char *)xrealloc (cxt->search_string, cxt->search_string_size);
     }
       memcpy (cxt->search_string + cxt->search_string_index, paste, pastelen);
       cxt->search_string_index += pastelen;
       cxt->search_string[cxt->search_string_index] = '\0';
       xfree (paste);
       break;
     /* Add character to search string and continue search. */
     default:
 #if defined (HANDLE_MULTIBYTE)
       wlen = (cxt->mb[0] == 0 || cxt->mb[1] == 0) ? 1 : RL_STRLEN (cxt->mb);
 #else
       wlen = 1;
 #endif
       if (cxt->search_string_index + wlen + 1 >= cxt->search_string_size)
     {
       cxt->search_string_size += 128;   /* 128 much greater than MB_CUR_MAX */
       cxt->search_string = (char *)xrealloc (cxt->search_string, cxt->search_string_size);
     }
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       int j;
       if (cxt->mb[0] == 0 || cxt->mb[1] == 0)
         cxt->search_string[cxt->search_string_index++] = cxt->mb[0];
       else
         for (j = 0; j < wlen; )
           cxt->search_string[cxt->search_string_index++] = cxt->mb[j++];
     }
       else
 #endif
     cxt->search_string[cxt->search_string_index++] = cxt->lastc;    /* XXX - was c instead of lastc */
       cxt->search_string[cxt->search_string_index] = '\0';
       break;
     }
   for (cxt->sflags &= ~(SF_FOUND|SF_FAILED);; )
     {
       if (cxt->search_string_index == 0)
     {
       cxt->sflags |= SF_FAILED;
       break;
     }
       limit = cxt->sline_len - cxt->search_string_index + 1;
       /* Search the current line. */
       while ((cxt->sflags & SF_REVERSE) ? (cxt->sline_index >= 0) : (cxt->sline_index < limit))
     {
       if (STREQN (cxt->search_string, cxt->sline + cxt->sline_index, cxt->search_string_index))
         {
           cxt->sflags |= SF_FOUND;
           break;
         }
       else
         cxt->sline_index += cxt->direction;
       if (cxt->sline_index < 0)
         {
           cxt->sline_index = 0;
           break;
         }
     }
       if (cxt->sflags & SF_FOUND)
     break;
       /* Move to the next line, but skip new copies of the line
      we just found and lines shorter than the string we're
      searching for. */
       do
     {
       /* Move to the next line. */
       cxt->history_pos += cxt->direction;
       /* At limit for direction? */
       if ((cxt->sflags & SF_REVERSE) ? (cxt->history_pos < 0) : (cxt->history_pos == cxt->hlen))
         {
           cxt->sflags |= SF_FAILED;
           break;
         }
       /* We will need these later. */
       cxt->sline = cxt->lines[cxt->history_pos];
       cxt->sline_len = strlen (cxt->sline);
     }
       while ((cxt->prev_line_found && STREQ (cxt->prev_line_found, cxt->lines[cxt->history_pos])) ||
          (cxt->search_string_index > cxt->sline_len));
       if (cxt->sflags & SF_FAILED)
     {
       /* XXX - reset sline_index if < 0 */
       if (cxt->sline_index < 0)
         cxt->sline_index = 0;
       break;
     }
       /* Now set up the line for searching... */
       cxt->sline_index = (cxt->sflags & SF_REVERSE) ? cxt->sline_len - cxt->search_string_index : 0;
     }
   /* reset the keymaps for the next time through the loop */
   cxt->keymap = cxt->okeymap = _rl_keymap;
   if (cxt->sflags & SF_FAILED)
     {
       /* We cannot find the search string.  Ding the bell. */
       rl_ding ();
       cxt->history_pos = cxt->last_found_line;
       rl_deactivate_mark ();
       rl_display_search (cxt->search_string, cxt->sflags, (cxt->history_pos == cxt->save_line) ? -1 : cxt->history_pos);
       return 1;
     }
   /* We have found the search string.  Just display it.  But don't
      actually move there in the history list until the user accepts
      the location. */
   if (cxt->sflags & SF_FOUND)
     {
       cxt->prev_line_found = cxt->lines[cxt->history_pos];
       rl_replace_line (cxt->lines[cxt->history_pos], 0);
       if (_rl_enable_active_region)
     rl_activate_mark ();
       rl_point = cxt->sline_index;
       if (rl_mark_active_p () && cxt->search_string_index > 0)
     rl_mark = rl_point + cxt->search_string_index;
       cxt->last_found_line = cxt->history_pos;
       rl_display_search (cxt->search_string, cxt->sflags, (cxt->history_pos == cxt->save_line) ? -1 : cxt->history_pos);
     }
   return 1;
 }
References _rl_add_executing_keyseq(), _rl_bracketed_text(), _rl_char_value, _rl_command_to_execute, _rl_enable_active_region, _rl_enable_bracketed_paste, _rl_find_prev_mbchar, _rl_fix_point(), _rl_init_executing_keyseq(), _rl_input_available(), _rl_input_queued(), _rl_keymap, _rl_keyseq_timeout, _rl_nchars_available(), _rl_pending_command, _rl_pushed_input_available(), _rl_read_bracketed_paste_prefix(), _rl_term_executing_keyseq(), _rl_to_lower(), _rl_walphabetic, ANYOTHERKEY, BRACK_PASTE_SLEN, c, _rl_cmd::count, CTRL, cval, __rl_search_context::direction, ENDSRCH_CHAR, ESC, f, _rl_cmd::func, _keymap_entry::function, FUNCTION_TO_KEYMAP, __rl_search_context::history_pos, __rl_search_context::hlen, if(), ISFUNC, ISKMAP, j, _rl_cmd::key, __rl_search_context::keymap, __rl_search_context::last_found_line, last_isearch_string, last_isearch_string_len, __rl_search_context::lastc, __rl_search_context::lines, _rl_cmd::map, MB_CUR_MAX, MB_FIND_NONZERO, MB_NEXTCHAR, memcpy, n, NULL, __rl_search_context::okeymap, __rl_search_context::prev_line_found, __rl_search_context::prevc, rl_abort(), rl_activate_mark(), rl_bracketed_paste_begin(), rl_byte_oriented, rl_clear_message(), rl_deactivate_mark(), rl_ding(), rl_display_search(), rl_do_lowercase_version(), rl_end, rl_execute_next(), rl_forward_search_history(), rl_function_of_keyseq(), rl_insert(), RL_ISSTATE, rl_line_buffer, rl_mark, rl_mark_active_p(), rl_point, rl_read_key(), rl_replace_line(), rl_restore_prompt(), rl_reverse_search_history(), rl_rubout(), RL_STATE_CALLBACK, RL_STATE_INPUTPENDING, RL_STRLEN, rl_stuff_char(), rl_unix_word_rubout(), rl_yank(), __rl_search_context::save_line, __rl_search_context::save_mark, __rl_search_context::save_point, __rl_search_context::search_string, __rl_search_context::search_string_index, __rl_search_context::search_string_size, __rl_search_context::search_terminators, SF_CHGKMAP, SF_FAILED, SF_FOUND, SF_REVERSE, __rl_search_context::sflags, __rl_search_context::sline, __rl_search_context::sline_index, __rl_search_context::sline_len, strchr(), strcpy, STREQ, STREQN, strlen(), _keymap_entry::type, xfree, and xrealloc.
Referenced by _rl_isearch_callback(), and rl_search_history().
_rl_keyseq_chain_dispose()
void _rl_keyseq_chain_dispose (void)
Definition at line 775 of file readline.c.
 {
   _rl_keyseq_cxt *cxt;
   while (_rl_kscxt)
     {
       cxt = _rl_kscxt;
       _rl_kscxt = _rl_kscxt->ocxt;
       _rl_keyseq_cxt_dispose (cxt);
     }
 }
References _rl_keyseq_cxt_dispose(), _rl_kscxt, and __rl_keyseq_context::ocxt.
Referenced by _rl_dispatch_callback(), and _rl_dispatch_subseq().
_rl_keyseq_cxt_alloc()
_rl_keyseq_cxt* _rl_keyseq_cxt_alloc (void)
Definition at line 753 of file readline.c.
 {
   _rl_keyseq_cxt *cxt;
   cxt = (_rl_keyseq_cxt *)xmalloc (sizeof (_rl_keyseq_cxt));
   cxt->flags = cxt->subseq_arg = cxt->subseq_retval = 0;
   cxt->okey = 0;
   cxt->ocxt = _rl_kscxt;
   cxt->childval = 42;       /* sentinel value */
   return cxt;
 }
References _rl_kscxt, __rl_keyseq_context::childval, __rl_keyseq_context::flags, __rl_keyseq_context::ocxt, __rl_keyseq_context::okey, __rl_keyseq_context::subseq_arg, __rl_keyseq_context::subseq_retval, and xmalloc.
Referenced by _rl_dispatch_subseq().
_rl_keyseq_cxt_dispose()
void _rl_keyseq_cxt_dispose (_rl_keyseq_cxt * cxt)
Definition at line 769 of file readline.c.
 {
   xfree (cxt);
 }
References xfree.
Referenced by _rl_dispatch_callback(), and _rl_keyseq_chain_dispose().
_rl_kill_kbd_macro()
void _rl_kill_kbd_macro (void)
Definition at line 223 of file macro.c.
 {
   if (current_macro)
     {
       xfree (current_macro);
       current_macro = (char *) NULL;
     }
   current_macro_size = current_macro_index = 0;
   FREE (rl_executing_macro);
   rl_executing_macro = (char *) NULL;
   executing_macro_index = 0;
   RL_UNSETSTATE(RL_STATE_MACRODEF);
 }
References current_macro, current_macro_index, current_macro_size, executing_macro_index, FREE, NULL, rl_executing_macro, RL_STATE_MACRODEF, RL_UNSETSTATE, and xfree.
Referenced by _rl_abort_internal(), and rl_free_line_state().
_rl_lowercase_p()
int() _rl_lowercase_p (int)
Referenced by invert_case_line(), and rl_vi_change_case().
_rl_make_prompt_for_search()
char* _rl_make_prompt_for_search (int pchar)
Definition at line 3140 of file display.c.
 {
   int len;
   char *pmt, *p;
   rl_save_prompt ();
   /* We've saved the prompt, and can do anything with the various prompt
      strings we need before they're restored.  We want the unexpanded
      portion of the prompt string after any final newline. */
   p = rl_prompt ? strrchr (rl_prompt, '\n') : 0;
   if (p == 0)
     {
       len = (rl_prompt && *rl_prompt) ? strlen (rl_prompt) : 0;
       pmt = (char *)xmalloc (len + 2);
       if (len)
     strcpy (pmt, rl_prompt);
       pmt[len] = pchar;
       pmt[len+1] = '\0';
     }
   else
     {
       p++;
       len = strlen (p);
       pmt = (char *)xmalloc (len + 2);
       if (len)
     strcpy (pmt, p);
       pmt[len] = pchar;
       pmt[len+1] = '\0';
     }
   /* will be overwritten by expand_prompt, called from rl_message */
   prompt_physical_chars = saved_physical_chars + 1;
   return pmt;
 }
References len, p, prompt_physical_chars, rl_prompt, rl_save_prompt(), saved_physical_chars, strcpy, strlen(), strrchr(), and xmalloc.
Referenced by _rl_nsearch_init().
_rl_move_vert()
void _rl_move_vert (int to)
Definition at line 2868 of file display.c.
 {
   register int delta, i;
   if (_rl_last_v_pos == to || to > _rl_screenheight)
     return;
   if ((delta = to - _rl_last_v_pos) > 0)
     {
       for (i = 0; i < delta; i++)
     putc ('\n', rl_outstream);
       _rl_cr ();
       _rl_last_c_pos = 0;
     }
   else
     {           /* delta < 0 */
 #ifdef __DJGPP__
       int row, col;
       fflush (rl_outstream);
       ScreenGetCursor (&row, &col);
       ScreenSetCursor (row + delta, col);
       i = -delta;
 #else
       if (_rl_term_up && *_rl_term_up)
     for (i = 0; i < -delta; i++)
       tputs (_rl_term_up, 1, _rl_output_character_function);
 #endif /* !__DJGPP__ */
     }
   _rl_last_v_pos = to;      /* Now TO is here */
 }
References _rl_cr(), _rl_last_c_pos, _rl_last_v_pos, _rl_output_character_function(), _rl_screenheight, _rl_term_up, fflush(), i, putc(), rl_outstream, and tputs().
Referenced by _rl_clean_up_for_exit(), _rl_redisplay_after_sigwinch(), _rl_update_final(), display_matches(), rl_clear_visible_line(), rl_redisplay(), and update_line().
_rl_nchars_available()
int _rl_nchars_available (void)
Definition at line 414 of file input.c.
 {
   int chars_avail, fd, result;
   chars_avail = 0;
 #if defined (FIONREAD)
   fd = fileno (rl_instream);
   errno = 0;
   result = ioctl (fd, FIONREAD, &chars_avail);
   if (result == -1 && errno == EIO)
     return -1;
 #endif
   return chars_avail;
 }
References EIO, errno, fileno(), FIONREAD, ioctl(), and rl_instream.
Referenced by _rl_isearch_dispatch(), and _rl_nsearch_dispatch().
_rl_next_macro_key()
int _rl_next_macro_key (void)
Definition at line 114 of file macro.c.
 {
   int c;
   if (rl_executing_macro == 0)
     return (0);
   if (rl_executing_macro[executing_macro_index] == 0)
     {
       _rl_pop_executing_macro ();
       return (_rl_next_macro_key ());
     }
 #if defined (READLINE_CALLBACKS)
   c = rl_executing_macro[executing_macro_index++];
   if (RL_ISSTATE (RL_STATE_CALLBACK) && RL_ISSTATE (RL_STATE_READCMD|RL_STATE_MOREINPUT) && rl_executing_macro[executing_macro_index] == 0)
       _rl_pop_executing_macro ();
   return c;
 #else
   /* XXX - consider doing the same as the callback code, just not testing
      whether we're running in callback mode */
   return (rl_executing_macro[executing_macro_index++]);
 #endif
 }
References _rl_pop_executing_macro(), c, executing_macro_index, rl_executing_macro, RL_ISSTATE, RL_STATE_CALLBACK, RL_STATE_MOREINPUT, and RL_STATE_READCMD.
Referenced by rl_read_key().
_rl_nsearch_callback()
int _rl_nsearch_callback (_rl_search_cxt * cxt)
Definition at line 508 of file search.c.
 {
   int c, r;
   c = _rl_search_getchar (cxt);
   if (c <= 0)
     {
       if (c < 0)
         _rl_nsearch_abort (cxt);
       return 1;
     }
   r = _rl_nsearch_dispatch (cxt, c);
   if (r != 0)
     return 1;
   r = _rl_nsearch_dosearch (cxt);
   return ((r >= 0) ? _rl_nsearch_cleanup (cxt, r) : (r != 1));
 }
References _rl_nsearch_abort(), _rl_nsearch_cleanup(), _rl_nsearch_dispatch(), _rl_nsearch_dosearch(), _rl_search_getchar(), c, and r.
Referenced by rl_callback_read_char().
_rl_nsearch_cleanup()
int _rl_nsearch_cleanup (_rl_search_cxt * cxt, int r)
Definition at line 262 of file search.c.
 {
   _rl_scxt_dispose (cxt, 0);
   _rl_nscxt = 0;
   RL_UNSETSTATE(RL_STATE_NSEARCH);
   return (r != 1);
 }
References _rl_nscxt, _rl_scxt_dispose(), r, RL_STATE_NSEARCH, and RL_UNSETSTATE.
Referenced by _rl_nsearch_callback(), noninc_search(), and rl_callback_sigcleanup().
_rl_null_function()
int _rl_null_function (int count, int key)
Definition at line 127 of file util.c.
 {
   return 0;
 }
Referenced by rl_generic_bind().
_rl_optimize_redisplay()
void _rl_optimize_redisplay (void)
Definition at line 755 of file display.c.
 {
   if (_rl_vis_botlin == 0)
     _rl_quick_redisplay = 1;
 }
References _rl_quick_redisplay, and _rl_vis_botlin.
Referenced by rl_display_search().
_rl_output_character_function()
int _rl_output_character_function (int c)
Definition at line 702 of file terminal.c.
 {
   return putc (c, _rl_out_stream);
 }
References _rl_out_stream, c, and putc().
Referenced by _rl_backspace(), _rl_clear_screen(), _rl_clear_to_eol(), _rl_control_keypad(), _rl_cr(), _rl_disable_meta_key(), _rl_enable_meta_key(), _rl_move_cursor_relative(), _rl_move_vert(), _rl_region_color_off(), _rl_region_color_on(), _rl_set_cursor(), _rl_standout_off(), _rl_standout_on(), delete_chars(), open_some_spaces(), rl_crlf(), and rl_ding().
_rl_output_some_chars()
void _rl_output_some_chars (const char * string, int count)
Definition at line 710 of file terminal.c.
 {
   fwrite (string, 1, count, _rl_out_stream);
 }
References _rl_out_stream, count, and fwrite().
Referenced by insert_some_chars(), rl_echo_signal_char(), rl_on_new_line_with_prompt(), rl_redisplay(), and update_line().
_rl_overwrite_char()
int _rl_overwrite_char (int count, int c)
Definition at line 915 of file text.c.
 {
   int i;
 #if defined (HANDLE_MULTIBYTE)
   char mbkey[MB_LEN_MAX];
   int k;
   /* Read an entire multibyte character sequence to insert COUNT times. */
   k = 1;
   if (count > 0 && MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     k = _rl_read_mbstring (c, mbkey, MB_LEN_MAX);
   if (k < 0)
     return 1;
 #endif
   rl_begin_undo_group ();
   for (i = 0; i < count; i++)
     {
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_insert_text (mbkey);
       else
 #endif
     _rl_insert_char (1, c);
       if (rl_point < rl_end)
     rl_delete (1, c);
     }
   rl_end_undo_group ();
   return 0;
 }
References _rl_insert_char(), c, count, i, k, MB_CUR_MAX, MB_LEN_MAX, rl_begin_undo_group(), rl_byte_oriented, rl_delete(), rl_end, rl_end_undo_group(), rl_insert_text(), and rl_point.
Referenced by rl_insert(), and rl_vi_overstrike().
_rl_overwrite_rubout()
int _rl_overwrite_rubout (int count, int key)
Definition at line 1146 of file text.c.
 {
   int opoint;
   int i, l;
   if (rl_point == 0)
     {
       rl_ding ();
       return 1;
     }
   opoint = rl_point;
   /* L == number of spaces to insert */
   for (i = l = 0; i < count; i++)
     {
       rl_backward_char (1, key);
       l += rl_character_len (rl_line_buffer[rl_point], rl_point);   /* not exactly right */
     }
   rl_begin_undo_group ();
   if (count > 1 || rl_explicit_arg)
     rl_kill_text (opoint, rl_point);
   else
     rl_delete_text (opoint, rl_point);
   /* Emacs puts point at the beginning of the sequence of spaces. */
   if (rl_point < rl_end)
     {
       opoint = rl_point;
       _rl_insert_char (l, ' ');
       rl_point = opoint;
     }
   rl_end_undo_group ();
   return 0;
 }
References _rl_insert_char(), count, i, rl_backward_char(), rl_begin_undo_group(), rl_character_len(), rl_delete_text(), rl_ding(), rl_end, rl_end_undo_group(), rl_explicit_arg, rl_kill_text(), rl_line_buffer, and rl_point.
Referenced by rl_rubout().
_rl_peek_macro_key()
int _rl_peek_macro_key (void)
Definition at line 140 of file macro.c.
 {
   if (rl_executing_macro == 0)
     return (0);
   if (rl_executing_macro[executing_macro_index] == 0 && (macro_list == 0 || macro_list->string == 0))
     return (0);
   if (rl_executing_macro[executing_macro_index] == 0 && macro_list && macro_list->string)
     return (macro_list->string[0]);
   return (rl_executing_macro[executing_macro_index]);
 }
References executing_macro_index, macro_list, rl_executing_macro, and saved_macro::string.
Referenced by _rl_dispatch_subseq().
_rl_pop_executing_macro()
void _rl_pop_executing_macro (void)
Definition at line 183 of file macro.c.
 {
   struct saved_macro *macro;
   FREE (rl_executing_macro);
   rl_executing_macro = (char *)NULL;
   executing_macro_index = 0;
   if (macro_list)
     {
       macro = macro_list;
       rl_executing_macro = macro_list->string;
       executing_macro_index = macro_list->sindex;
       macro_list = macro_list->next;
       xfree (macro);
     }
   macro_level--;
   if (rl_executing_macro == 0)
     RL_UNSETSTATE(RL_STATE_MACROINPUT);
 }
References executing_macro_index, FREE, macro_level, macro_list, saved_macro::next, NULL, rl_executing_macro, RL_STATE_MACROINPUT, RL_UNSETSTATE, saved_macro::sindex, saved_macro::string, and xfree.
Referenced by _rl_abort_internal(), and _rl_next_macro_key().
_rl_prev_macro_key()
int _rl_prev_macro_key (void)
Definition at line 152 of file macro.c.
 {
   if (rl_executing_macro == 0)
     return (0);
   if (executing_macro_index == 0)
     return (0);
   executing_macro_index--;
   return (rl_executing_macro[executing_macro_index]);
 }
References executing_macro_index, and rl_executing_macro.
Referenced by _rl_dispatch_subseq(), and _rl_subseq_result().
_rl_pure_alphabetic()
int() _rl_pure_alphabetic (int)
_rl_push_executing_macro()
void _rl_push_executing_macro (void)
Definition at line 166 of file macro.c.
 {
   struct saved_macro *saver;
   saver = (struct saved_macro *)xmalloc (sizeof (struct saved_macro));
   saver->next = macro_list;
   saver->sindex = executing_macro_index;
   saver->string = rl_executing_macro;
   macro_list = saver;
   macro_level++;
 }
References executing_macro_index, macro_level, macro_list, saved_macro::next, rl_executing_macro, saved_macro::sindex, saved_macro::string, and xmalloc.
Referenced by _rl_with_macro_input().
_rl_pushed_input_available()
int _rl_pushed_input_available (void)
Definition at line 188 of file input.c.
 {
   return (push_index != pop_index);
 }
References pop_index, and push_index.
Referenced by _rl_dispatch_subseq(), _rl_insert_char(), _rl_isearch_dispatch(), _rl_read_bracketed_paste_prefix(), rl_callback_read_char(), rl_insert(), and rl_vi_overstrike_bracketed_paste().
_rl_qsort_string_compare()
int _rl_qsort_string_compare (char ** s1, char ** s2)
Definition at line 422 of file util.c.
 {
 #if defined (HAVE_STRCOLL)
   return (strcoll (*s1, *s2));
 #else
   int result;
   result = **s1 - **s2;
   if (result == 0)
     result = strcmp (*s1, *s2);
   return result;
 #endif
 }
_rl_read_bracketed_paste_prefix()
int _rl_read_bracketed_paste_prefix (int c)
Definition at line 774 of file kill.c.
 {
   char pbuf[BRACK_PASTE_SLEN+1], *pbpref;
   int key, ind, j;
   pbpref = BRACK_PASTE_PREF;        /* XXX - debugging */
   if (c != pbpref[0])
     return (0);
   pbuf[ind = 0] = c;
   while (ind < BRACK_PASTE_SLEN-1 &&
      (RL_ISSTATE (RL_STATE_INPUTPENDING|RL_STATE_MACROINPUT) == 0) &&
          _rl_pushed_input_available () == 0 &&
          _rl_input_queued (0))
     {
       key = rl_read_key ();     /* XXX - for now */
       if (key < 0)
     break;
       pbuf[++ind] = key;
       if (pbuf[ind] != pbpref[ind])
         break;
     }
   if (ind < BRACK_PASTE_SLEN-1)     /* read incomplete sequence */
     {
       while (ind >= 0)
     _rl_unget_char (pbuf[ind--]);
       return (key < 0 ? key : 0);
     }
   return (key < 0 ? key : 1);
 }
References _rl_input_queued(), _rl_pushed_input_available(), _rl_unget_char(), BRACK_PASTE_PREF, BRACK_PASTE_SLEN, c, j, RL_ISSTATE, rl_read_key(), RL_STATE_INPUTPENDING, and RL_STATE_MACROINPUT.
Referenced by _rl_bracketed_read_key(), _rl_isearch_dispatch(), and _rl_nsearch_dispatch().
_rl_redisplay_after_sigwinch()
void _rl_redisplay_after_sigwinch (void)
Definition at line 3387 of file display.c.
 {
   char *t;
   /* Clear the last line (assuming that the screen size change will result in
      either more or fewer characters on that line only) and put the cursor at
      column 0.  Make sure the right thing happens if we have wrapped to a new
      screen line. */
   if (_rl_term_cr)
     {
       rl_clear_visible_line ();
       if (_rl_last_v_pos > 0)
     _rl_move_vert (0);
     }
   else
     rl_crlf ();
   if (_rl_screenwidth < prompt_visible_length)
     _rl_reset_prompt ();        /* update local_prompt_newlines array */
   /* Redraw only the last line of a multi-line prompt. */
   t = strrchr (rl_display_prompt, '\n');
   if (t)
     redraw_prompt (++t);
   else
     rl_forced_update_display ();
 }
References _rl_last_v_pos, _rl_move_vert(), _rl_reset_prompt(), _rl_screenwidth, _rl_term_cr, prompt_visible_length, redraw_prompt(), rl_clear_visible_line(), rl_crlf(), rl_display_prompt, rl_forced_update_display(), strrchr(), and t.
Referenced by rl_resize_terminal().
_rl_refresh_line()
void _rl_refresh_line (void)
Definition at line 3466 of file display.c.
 {
   rl_clear_visible_line ();
   rl_redraw_prompt_last_line ();
   rl_keep_mark_active ();
 }
References rl_clear_visible_line(), rl_keep_mark_active(), and rl_redraw_prompt_last_line().
Referenced by rl_refresh_line().
_rl_region_color_off()
void _rl_region_color_off (void)
Definition at line 863 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_active_region_start_color && _rl_active_region_end_color)
     tputs (_rl_active_region_end_color, 1, _rl_output_character_function);
 #endif
 }
References _rl_active_region_end_color, _rl_active_region_start_color, _rl_output_character_function(), and tputs().
Referenced by putc_face().
_rl_region_color_on()
void _rl_region_color_on (void)
Definition at line 854 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_active_region_start_color && _rl_active_region_end_color)
     tputs (_rl_active_region_start_color, 1, _rl_output_character_function);
 #endif
 }
References _rl_active_region_end_color, _rl_active_region_start_color, _rl_output_character_function(), and tputs().
Referenced by putc_face().
_rl_release_sigint()
void _rl_release_sigint (void)
Definition at line 650 of file signals.c.
 {
   if (sigint_blocked == 0)
     return;
   sigint_blocked = 0;
   RL_CHECK_SIGNALS ();
 }
References RL_CHECK_SIGNALS, and sigint_blocked.
Referenced by rl_deprep_terminal(), rl_prep_terminal(), and rl_redisplay().
_rl_release_sigwinch()
void _rl_release_sigwinch (void)
Definition at line 691 of file signals.c.
 {
   if (sigwinch_blocked == 0)
     return;
 #if defined (SIGWINCH)
 #if defined (HAVE_POSIX_SIGNALS)
   sigprocmask (SIG_SETMASK, &sigwinch_oset, (sigset_t *)NULL);
 #else
 #  if defined (HAVE_BSD_SIGNALS)
   sigsetmask (sigwinch_oldmask);
 #  else /* !HAVE_BSD_SIGNALS */
 #    if defined (HAVE_USG_SIGHOLD)
   sigrelse (SIGWINCH);
 #    endif /* HAVE_USG_SIGHOLD */
 #  endif /* !HAVE_BSD_SIGNALS */
 #endif /* !HAVE_POSIX_SIGNALS */
 #endif /* SIGWINCH */
   sigwinch_blocked = 0;
 }
References NULL, SIG_SETMASK, sigprocmask(), sigrelse(), SIGWINCH, and sigwinch_blocked.
_rl_replace_text()
int _rl_replace_text (const char * text, int start, int end)
Definition at line 193 of file text.c.
 {
   int n;
   n = 0;
   rl_begin_undo_group ();
   if (start <= end)
     rl_delete_text (start, end + 1);
   rl_point = start;
   if (*text)
     n = rl_insert_text (text);
   rl_end_undo_group ();
   return n;
 }
References n, rl_begin_undo_group(), rl_delete_text(), rl_end_undo_group(), rl_insert_text(), rl_point, and start().
Referenced by _rl_vi_replace_insert(), insert_match(), make_history_line_current(), and rl_tilde_expand().
_rl_reset_argument()
void _rl_reset_argument (void)
Definition at line 217 of file misc.c.
 {
   rl_numeric_arg = rl_arg_sign = 1;
   rl_explicit_arg = 0;
   _rl_argcxt = 0;
 }
References _rl_argcxt, rl_arg_sign, rl_explicit_arg, and rl_numeric_arg.
Referenced by _rl_abort_internal(), readline_internal_char(), rl_discard_argument(), rl_free_line_state(), and rl_insert().
_rl_reset_completion_state()
void _rl_reset_completion_state (void)
Definition at line 495 of file complete.c.
 {
   rl_completion_found_quote = 0;
   rl_completion_quote_character = 0;
 }
References rl_completion_found_quote, and rl_completion_quote_character.
Referenced by _rl_handle_signal(), and rl_complete_internal().
_rl_reset_locale()
void _rl_reset_locale (void)
Definition at line 335 of file nls.c.
 {
   char *ol, *nl;
   /* This should not be NULL; _rl_init_eightbit sets it on the first call to
      readline() or rl_initialize(). */
   ol = _rl_current_locale;
   nl = _rl_init_locale ();      /* resets _rl_current_locale */
   if ((ol == 0 && nl) || (ol && nl && (STREQ (ol, nl) == 0)))
     (void)_rl_set_localevars (nl, 1);
   xfree (ol);
 }
References _rl_current_locale, _rl_init_locale(), _rl_set_localevars(), STREQ, Driver::void(), and xfree.
Referenced by rl_initialize().
_rl_reset_prompt()
void _rl_reset_prompt (void)
Definition at line 556 of file display.c.
 {
   rl_visible_prompt_length = rl_expand_prompt (rl_prompt);
 }
References rl_expand_prompt(), rl_prompt, and rl_visible_prompt_length.
Referenced by _rl_redisplay_after_sigwinch(), hack_special_boolean_var(), readline_internal_setup(), rl_emacs_editing_mode(), rl_vi_insertion_mode(), and rl_vi_movement_mode().
_rl_reset_region_color()
int _rl_reset_region_color (int which, const char * value)
Definition at line 821 of file terminal.c.
 {
   int len;
   if (which == 0)
     {
       xfree (_rl_active_region_start_color);
       if (value && *value)
     {
       _rl_active_region_start_color = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_active_region_start_color, &len);
       _rl_active_region_start_color[len] = '\0';
     }
       else
     _rl_active_region_start_color = NULL;
     }
   else
     {
       xfree (_rl_active_region_end_color);
       if (value && *value)
     {
       _rl_active_region_end_color = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_active_region_end_color, &len);
       _rl_active_region_end_color[len] = '\0';
     }
       else
     _rl_active_region_end_color = NULL;
     }
   return 0;
 }
References _rl_active_region_end_color, _rl_active_region_start_color, len, NULL, rl_translate_keyseq(), strlen(), value, xfree, and xmalloc.
Referenced by _rl_init_terminal_io(), sv_region_end_color(), and sv_region_start_color().
_rl_restore_prompt()
void _rl_restore_prompt (void)
_rl_restore_tty_signals()
int _rl_restore_tty_signals (void)
Definition at line 948 of file rltty.c.
 {
   return 0;
 }
Referenced by _rl_insert_next().
_rl_revert_all_lines()
void _rl_revert_all_lines (void)
Definition at line 493 of file misc.c.
 {
   int pos;
   pos = where_history ();
   using_history ();
   _rl_revert_previous_lines ();
   history_set_pos (pos);
 }
References _rl_revert_previous_lines(), history_set_pos(), pos, using_history(), and where_history().
Referenced by readline_internal_teardown().
_rl_revert_previous_lines()
void _rl_revert_previous_lines (void)
Definition at line 446 of file misc.c.
 {
   int hpos;
   HIST_ENTRY *entry;
   UNDO_LIST *ul, *saved_undo_list;
   char *lbuf;
   lbuf = savestring (rl_line_buffer);
   saved_undo_list = rl_undo_list;
   hpos = where_history ();
   entry = (hpos == history_length) ? previous_history () : current_history ();
   while (entry)
     {
       if (ul = (UNDO_LIST *)entry->data)
     {
       if (ul == saved_undo_list)
         saved_undo_list = 0;
       /* Set up rl_line_buffer and other variables from history entry */
       rl_replace_from_history (entry, 0);   /* entry->line is now current */
       entry->data = 0;          /* entry->data is now current undo list */
       /* Undo all changes to this history entry */
       while (rl_undo_list)
         rl_do_undo ();
       /* And copy the reverted line back to the history entry, preserving
          the timestamp. */
       FREE (entry->line);
       entry->line = savestring (rl_line_buffer);
     }
       entry = previous_history ();
     }
   /* Restore history state */
   rl_undo_list = saved_undo_list;   /* may have been set to null */
   history_set_pos (hpos);
   /* reset the line buffer */
   rl_replace_line (lbuf, 0);
   _rl_set_the_line ();
   /* and clean up */
   xfree (lbuf);
 }
References _rl_set_the_line(), current_history(), entry::data, FREE, history_length, history_set_pos(), lbuf, previous_history(), rl_do_undo(), rl_line_buffer, rl_replace_from_history(), rl_replace_line(), rl_undo_list, savestring(), where_history(), and xfree.
Referenced by _rl_revert_all_lines().
_rl_rubout_char()
int _rl_rubout_char (int count, int key)
Definition at line 1206 of file text.c.
 {
   int orig_point;
   unsigned char c;
   /* Duplicated code because this is called from other parts of the library. */
   if (count < 0)
     return (rl_delete (-count, key));
   if (rl_point == 0)
     {
       rl_ding ();
       return 1;
     }
   orig_point = rl_point;
   if (count > 1 || rl_explicit_arg)
     {
       rl_backward_char (count, key);
       rl_kill_text (orig_point, rl_point);
     }
   else if (MB_CUR_MAX == 1 || rl_byte_oriented)
     {
       c = rl_line_buffer[--rl_point];
       rl_delete_text (rl_point, orig_point);
       /* The erase-at-end-of-line hack is of questionable merit now. */
       if (rl_point == rl_end && ISPRINT ((unsigned char)c) && _rl_last_c_pos)
     {
       int l;
       l = rl_character_len (c, rl_point);
       _rl_erase_at_end_of_line (l);
     }
     }
   else
     {
       rl_point = _rl_find_prev_mbchar (rl_line_buffer, rl_point, MB_FIND_NONZERO);
       rl_delete_text (rl_point, orig_point);
     }
   return 0;
 }
References _rl_erase_at_end_of_line(), _rl_find_prev_mbchar, _rl_last_c_pos, c, count, ISPRINT, MB_CUR_MAX, MB_FIND_NONZERO, rl_backward_char(), rl_byte_oriented, rl_character_len(), rl_delete(), rl_delete_text(), rl_ding(), rl_end, rl_explicit_arg, rl_kill_text(), rl_line_buffer, and rl_point.
Referenced by _rl_nsearch_dispatch(), rl_delete(), rl_rubout(), and rl_rubout_or_delete().
_rl_save_prompt()
void _rl_save_prompt (void)
_rl_savestring()
char* _rl_savestring (const char * s)
Definition at line 461 of file util.c.
 {
   return (strcpy ((char *)xmalloc (1 + (int)strlen (s)), (s)));
 }
References strcpy, strlen(), and xmalloc.
_rl_scxt_alloc()
_rl_search_cxt* _rl_scxt_alloc (int type, int flags)
Definition at line 78 of file isearch.c.
 {
   _rl_search_cxt *cxt;
   cxt = (_rl_search_cxt *)xmalloc (sizeof (_rl_search_cxt));
   cxt->type = type;
   cxt->sflags = flags;
   cxt->search_string = 0;
   cxt->search_string_size = cxt->search_string_index = 0;
   cxt->lines = 0;
   cxt->allocated_line = 0;
   cxt->hlen = cxt->hindex = 0;
   cxt->save_point = rl_point;
   cxt->save_mark = rl_mark;
   cxt->save_line = where_history ();
   cxt->last_found_line = cxt->save_line;
   cxt->prev_line_found = 0;
   cxt->save_undo_list = 0;
   cxt->keymap = _rl_keymap;
   cxt->okeymap = _rl_keymap;
   cxt->history_pos = 0;
   cxt->direction = 0;
   cxt->prevc = cxt->lastc = 0;
   cxt->sline = 0;
   cxt->sline_len = cxt->sline_index = 0;
   cxt->search_terminators = 0;
   return cxt;
 }
References _rl_keymap, __rl_search_context::allocated_line, __rl_search_context::direction, flags, __rl_search_context::hindex, __rl_search_context::history_pos, __rl_search_context::hlen, __rl_search_context::keymap, __rl_search_context::last_found_line, __rl_search_context::lastc, __rl_search_context::lines, __rl_search_context::okeymap, __rl_search_context::prev_line_found, __rl_search_context::prevc, rl_mark, rl_point, __rl_search_context::save_line, __rl_search_context::save_mark, __rl_search_context::save_point, __rl_search_context::save_undo_list, __rl_search_context::search_string, __rl_search_context::search_string_index, __rl_search_context::search_string_size, __rl_search_context::search_terminators, __rl_search_context::sflags, __rl_search_context::sline, __rl_search_context::sline_index, __rl_search_context::sline_len, type, __rl_search_context::type, where_history(), and xmalloc.
Referenced by _rl_isearch_init(), and _rl_nsearch_init().
_rl_scxt_dispose()
void _rl_scxt_dispose (_rl_search_cxt * cxt, int flags)
Definition at line 119 of file isearch.c.
 {
   FREE (cxt->search_string);
   FREE (cxt->allocated_line);
   FREE (cxt->lines);
   xfree (cxt);
 }
References __rl_search_context::allocated_line, FREE, __rl_search_context::lines, __rl_search_context::search_string, and xfree.
Referenced by _rl_isearch_cleanup(), and _rl_nsearch_cleanup().
_rl_search_getchar()
int _rl_search_getchar (_rl_search_cxt * cxt)
Definition at line 314 of file isearch.c.
 {
   int c;
   /* Read a key and decide how to proceed. */
   RL_SETSTATE(RL_STATE_MOREINPUT);
   c = cxt->lastc = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
 #if defined (HANDLE_MULTIBYTE)
   /* This ends up with C (and LASTC) being set to the last byte of the
      multibyte character.  In most cases c == lastc == mb[0] */
   if (c >= 0 && MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     c = cxt->lastc = _rl_read_mbstring (cxt->lastc, cxt->mb, MB_LEN_MAX);
 #endif
   RL_CHECK_SIGNALS ();
   return c;
 }
References c, __rl_search_context::lastc, MB_CUR_MAX, MB_LEN_MAX, rl_byte_oriented, RL_CHECK_SIGNALS, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, and RL_UNSETSTATE.
Referenced by _rl_isearch_callback(), _rl_nsearch_callback(), noninc_search(), and rl_search_history().
_rl_set_cursor()
void _rl_set_cursor (int im, int force)
Definition at line 925 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_ve && _rl_term_vs)
     {
       if (force || im != rl_insert_mode)
     {
       if (im == RL_IM_OVERWRITE)
         tputs (_rl_term_vs, 1, _rl_output_character_function);
       else
         tputs (_rl_term_ve, 1, _rl_output_character_function);
     }
     }
 #endif
 }
References _rl_output_character_function(), _rl_term_ve, _rl_term_vs, force, RL_IM_OVERWRITE, rl_insert_mode, and tputs().
Referenced by _rl_set_insert_mode().
_rl_set_insert_mode()
void _rl_set_insert_mode (int im, int force)
Definition at line 759 of file misc.c.
 {
 #ifdef CURSOR_MODE
   _rl_set_cursor (im, force);
 #endif
   rl_insert_mode = im;
 }
References _rl_set_cursor(), force, and rl_insert_mode.
Referenced by readline_internal_teardown(), rl_emacs_editing_mode(), rl_initialize(), rl_overwrite_mode(), and rl_vi_editing_mode().
_rl_set_mark_at_pos()
int _rl_set_mark_at_pos (int position)
Definition at line 1819 of file text.c.
 {
   if (position < 0 || position > rl_end)
     return 1;
   rl_mark = position;
   return 0;
 }
References rl_end, and rl_mark.
Referenced by rl_set_mark(), rl_yank(), and rl_yank_nth_arg_internal().
_rl_set_screen_size()
void _rl_set_screen_size (int rows, int cols)
Definition at line 346 of file terminal.c.
 {
   if (_rl_term_autowrap == -1)
     _rl_init_terminal_io (rl_terminal_name);
   if (rows > 0)
     _rl_screenheight = rows;
   if (cols > 0)
     {
       _rl_screenwidth = cols;
       if (_rl_term_autowrap == 0)
     _rl_screenwidth--;
     }
   if (rows > 0 || cols > 0)
     _rl_screenchars = _rl_screenwidth * _rl_screenheight;
 }
References _rl_init_terminal_io(), _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_autowrap, and rl_terminal_name.
Referenced by rl_set_screen_size().
_rl_set_the_line()
void _rl_set_the_line (void)
Definition at line 746 of file readline.c.
 {
   the_line = rl_line_buffer;
 }
References rl_line_buffer, and the_line.
Referenced by _rl_revert_previous_lines(), and rl_extend_line_buffer().
_rl_signal_handler()
void _rl_signal_handler (int sig)
Definition at line 128 of file signals.c.
 {
   _rl_caught_signal = 0;    /* XXX */
 #if defined (SIGWINCH)
   if (sig == SIGWINCH)
     {
       RL_SETSTATE(RL_STATE_SIGHANDLER);
       rl_resize_terminal ();
       /* XXX - experimental for now */
       /* Call a signal hook because though we called the original signal handler
      in rl_sigwinch_handler below, we will not resend the signal to
      ourselves. */
       if (rl_signal_event_hook)
     (*rl_signal_event_hook) ();
       RL_UNSETSTATE(RL_STATE_SIGHANDLER);
     }
   else
 #endif
     _rl_handle_signal (sig);
   SIGHANDLER_RETURN;
 }
References _rl_caught_signal, _rl_handle_signal(), rl_resize_terminal(), RL_SETSTATE, rl_signal_event_hook, RL_STATE_SIGHANDLER, RL_UNSETSTATE, SIGHANDLER_RETURN, and SIGWINCH.
_rl_sigwinch_resize_terminal()
void _rl_sigwinch_resize_terminal (void)
Definition at line 386 of file terminal.c.
 {
   _rl_get_screen_size (fileno (rl_instream), 1);
 }
References _rl_get_screen_size(), fileno(), and rl_instream.
_rl_standout_off()
void _rl_standout_off (void)
Definition at line 802 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_so && _rl_term_se)
     tputs (_rl_term_se, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_se, _rl_term_so, and tputs().
_rl_standout_on()
void _rl_standout_on (void)
Definition at line 793 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_so && _rl_term_se)
     tputs (_rl_term_so, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_se, _rl_term_so, and tputs().
_rl_start_using_history()
void _rl_start_using_history (void)
Definition at line 306 of file misc.c.
 {
   using_history ();
   if (_rl_saved_line_for_history)
     _rl_free_saved_history_line ();
   _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
   _rl_history_search_pos = -99;     /* some random invalid history position */
 }
References _rl_free_saved_history_line(), _rl_history_search_pos, _rl_saved_line_for_history, NULL, and using_history().
Referenced by rl_initialize().
_rl_strindex()
char* _rl_strindex (const char * s1, const char * s2)
Definition at line 322 of file util.c.
 {
   register int i, l, len;
   for (i = 0, l = strlen (s2), len = strlen (s1); (len - i) >= l; i++)
     if (_rl_strnicmp (s1 + i, s2, l) == 0)
       return ((char *) (s1 + i));
   return ((char *)NULL);
 }
References _rl_strnicmp(), i, len, NULL, s1, s2, and strlen().
Referenced by substring_member_of_array().
_rl_strip_prompt()
char* _rl_strip_prompt (char * pmt)
Definition at line 547 of file display.c.
 {
   char *ret;
   ret = expand_prompt (pmt, 0, (int *)NULL, (int *)NULL, (int *)NULL, (int *)NULL);
   return ret;
 }
References expand_prompt(), NULL, and ret.
Referenced by readline_internal_setup().
_rl_term_executing_keyseq()
void _rl_term_executing_keyseq (void)
Definition at line 1549 of file readline.c.
 {
   rl_executing_keyseq[rl_key_sequence_length] = '\0';
 }
References rl_executing_keyseq, and rl_key_sequence_length.
Referenced by _rl_isearch_dispatch().
_rl_timeout_handle_sigalrm()
int _rl_timeout_handle_sigalrm (void)
Definition at line 727 of file input.c.
 {
 #if defined (RL_TIMEOUT_USE_SIGALRM)
   if (timerisunset (&timeout_point))
     return -1;
   /* Reset `timeout_point' to the current time to ensure that later
      calls of `rl_timeout_pending ()' return 0 (timeout expired). */
   if (gettimeofday(&timeout_point, 0) != 0)
     timerclear (&timeout_point);
   reset_alarm ();
   _rl_timeout_handle ();
 #endif
   return -1;
 }
References _rl_timeout_handle(), gettimeofday(), reset_alarm(), timeout_point, timerclear, and timerisunset.
Referenced by _rl_handle_signal().
_rl_timeout_init()
int _rl_timeout_init (void)
Definition at line 568 of file input.c.
 {
   unsigned int secs, usecs;
   /* Clear the timeout state of the previous edit */
   RL_UNSETSTATE(RL_STATE_TIMEOUT);
   timerclear (&timeout_point);
   /* Return 0 when timeout is unset. */
   if (timerisunset (&timeout_duration))
     return 0;
   /* Return -1 on gettimeofday error. */
   if (gettimeofday(&timeout_point, 0) != 0)
     {
       timerclear (&timeout_point);
       return -1;
     }
   secs = timeout_duration.tv_sec;
   usecs = timeout_duration.tv_usec;
 #if defined (RL_TIMEOUT_USE_SIGALRM)
   /* If select(2)/pselect(2) is unavailable, use SIGALRM. */
   if (set_alarm (&secs, &usecs) < 0)
     return -1;
 #endif
   timeout_point.tv_sec += secs;
   timeout_point.tv_usec += usecs;
   if (timeout_point.tv_usec >= USEC_PER_SEC)
     {
       timeout_point.tv_sec++;
       timeout_point.tv_usec -= USEC_PER_SEC;
     }
   return 0;
 }
References gettimeofday(), RL_STATE_TIMEOUT, RL_UNSETSTATE, set_alarm(), timeout_duration, timeout_point, timerclear, timerisunset, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
Referenced by rl_initialize().
_rl_to_lower()
int() _rl_to_lower (int)
Referenced by _rl_dispatch_subseq(), _rl_get_keyname(), _rl_isearch_dispatch(), _rl_stricmp(), _rl_strnicmp(), _rl_subseq_result(), _rl_untranslate_macro_value(), complete_fncmp(), compute_lcd_of_matches(), invert_case_line(), normalize_codeset(), rl_change_case(), rl_invoking_keyseqs_in_map(), rl_untranslate_keyseq(), and rl_vi_change_case().
_rl_to_upper()
int() _rl_to_upper (int)
Referenced by _rl_vi_domove_motion_cleanup(), invert_case_line(), rl_arrow_keys(), rl_change_case(), rl_parse_and_bind(), rl_translate_keyseq(), rl_vi_change_case(), and vi_change_dispatch().
_rl_trace()
void _rl_trace ()
_rl_tropen()
int _rl_tropen (void)
_rl_ttymsg()
void _rl_ttymsg ()
Referenced by rl_complete_internal().
_rl_unget_char()
int _rl_unget_char (int key)
Definition at line 228 of file input.c.
 {
   if (ibuffer_space ())
     {
       pop_index--;
       if (pop_index < 0)
     pop_index = ibuffer_len;
       ibuffer[pop_index] = key;
       return (1);
     }
   return (0);
 }
References ibuffer, ibuffer_len, ibuffer_space(), and pop_index.
Referenced by _rl_bracketed_read_key(), _rl_dispatch_subseq(), _rl_insert_typein(), _rl_read_bracketed_paste_prefix(), _rl_subseq_result(), and rl_vi_overstrike_bracketed_paste().
_rl_untranslate_macro_value()
char* _rl_untranslate_macro_value (char * seq, int use_escapes)
Definition at line 735 of file bind.c.
 {
   char *ret, *r, *s;
   int c;
   r = ret = (char *)xmalloc (7 * strlen (seq) + 1);
   for (s = seq; *s; s++)
     {
       c = *s;
       if (META_CHAR (c))
     {
       *r++ = '\\';
       *r++ = 'M';
       *r++ = '-';
       c = UNMETA (c);
     }
       else if (c == ESC)
     {
       *r++ = '\\';
       c = 'e';
     }
       else if (CTRL_CHAR (c))
     {
       *r++ = '\\';
       if (use_escapes && _rl_isescape (c))
         c = _rl_escchar (c);
       else
         {
           *r++ = 'C';
           *r++ = '-';
           c = _rl_to_lower (UNCTRL (c));
         }
     }
       else if (c == RUBOUT)
     {
       *r++ = '\\';
       *r++ = 'C';
       *r++ = '-';
       c = '?';
     }
       if (c == ESC)
     {
       *r++ = '\\';
       c = 'e';
     }
       else if (c == '\\' || c == '"')
     *r++ = '\\';
       *r++ = (unsigned char)c;
     }
   *r = '\0';
   return ret;
 }
References _rl_escchar(), _rl_isescape(), _rl_to_lower(), c, CTRL_CHAR, ESC, META_CHAR, r, ret, RUBOUT, strlen(), UNCTRL, UNMETA, and xmalloc.
Referenced by _rl_get_string_variable_value(), _rl_macro_dumper_internal(), and rl_print_last_kbd_macro().
_rl_update_final()
void _rl_update_final (void)
Definition at line 3307 of file display.c.
 {
   int full_lines, woff, botline_length;
   if (line_structures_initialized == 0)
     return;
   full_lines = 0;
   /* If the cursor is the only thing on an otherwise-blank last line,
      compensate so we don't print an extra CRLF. */
   if (_rl_vis_botlin && _rl_last_c_pos == 0 &&
     visible_line[vis_lbreaks[_rl_vis_botlin]] == 0)
     {
       _rl_vis_botlin--;
       full_lines = 1;
     }
   _rl_move_vert (_rl_vis_botlin);
   woff = W_OFFSET(_rl_vis_botlin, wrap_offset);
   botline_length = VIS_LLEN(_rl_vis_botlin) - woff;
   /* If we've wrapped lines, remove the final xterm line-wrap flag. */
   if (full_lines && _rl_term_autowrap && botline_length == _rl_screenwidth)
     {
       char *last_line, *last_face;
       /* LAST_LINE includes invisible characters, so if you want to get the
      last character of the first line, you have to take WOFF into account.
      This needs to be done for both calls to _rl_move_cursor_relative,
      which takes a buffer position as the first argument, and any direct
      subscripts of LAST_LINE. */
       last_line = &visible_line[vis_lbreaks[_rl_vis_botlin]]; /* = VIS_CHARS(_rl_vis_botlin); */
       last_face = &vis_face[vis_lbreaks[_rl_vis_botlin]]; /* = VIS_CHARS(_rl_vis_botlin); */
       cpos_buffer_position = -1;    /* don't know where we are in buffer */
       _rl_move_cursor_relative (_rl_screenwidth - 1 + woff, last_line, last_face);  /* XXX */
       _rl_clear_to_eol (0);
       puts_face (&last_line[_rl_screenwidth - 1 + woff],
          &last_face[_rl_screenwidth - 1 + woff], 1);
     }
   _rl_vis_botlin = 0;
   if (botline_length > 0 || _rl_last_c_pos > 0)
     rl_crlf ();
   fflush (rl_outstream);
   rl_display_fixed++;
 }
References _rl_clear_to_eol(), _rl_last_c_pos, _rl_move_cursor_relative(), _rl_move_vert(), _rl_screenwidth, _rl_term_autowrap, _rl_vis_botlin, cpos_buffer_position, fflush(), line_structures_initialized, puts_face(), rl_crlf(), rl_display_fixed, rl_outstream, vis_face, vis_lbreaks, VIS_LLEN, visible_line, W_OFFSET, and wrap_offset.
Referenced by rl_newline().
_rl_uppercase_p()
int() _rl_uppercase_p (int)
Referenced by invert_case_line(), rl_vi_change_case(), rl_vi_change_to(), rl_vi_delete_to(), rl_vi_end_word(), rl_vi_next_word(), rl_vi_prev_word(), rl_vi_put(), rl_vi_yank_to(), and vi_change_dispatch().
_rl_vi_domove_callback()
int _rl_vi_domove_callback (_rl_vimotion_cxt * m)
Definition at line 1326 of file vi_mode.c.
 {
   int c, r;
   m->motion = c = rl_vi_domove_getchar (m);
   if (c < 0)
     return 1;       /* EOF */
   r = rl_domove_read_callback (m);
   return ((r == 0) ? r : 1);    /* normalize return values */
 }
References c, __rl_vimotion_context::motion, r, rl_domove_read_callback(), and rl_vi_domove_getchar().
Referenced by rl_callback_read_char().
_rl_vi_domove_motion_cleanup()
int _rl_vi_domove_motion_cleanup (int c, _rl_vimotion_cxt * m)
Definition at line 1188 of file vi_mode.c.
 {
   int r;
   /* Remove the blank that we added in rl_domove_motion_callback. */
   rl_end = m->end;
   rl_line_buffer[rl_end] = '\0';
   _rl_fix_point (0);
   /* No change in position means the command failed. */
   if (rl_mark == rl_point)
     {
       /* 'c' and 'C' enter insert mode after the delete even if the motion
      didn't delete anything, as long as the motion command is valid. */
       if (_rl_to_upper (m->key) == 'C' && _rl_vi_motion_command (c))
     return (vidomove_dispatch (m));
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       return (-1);
     }
   /* rl_vi_f[wW]ord () leaves the cursor on the first character of the next
      word.  If we are not at the end of the line, and we are on a
      non-whitespace character, move back one (presumably to whitespace). */
   if ((_rl_to_upper (c) == 'W') && rl_point < rl_end && rl_point > rl_mark &&
       !whitespace (rl_line_buffer[rl_point]))
     rl_point--;     /* XXX */
   /* If cw or cW, back up to the end of a word, so the behaviour of ce
      or cE is the actual result.  Brute-force, no subtlety. */
   if (m->key == 'c' && rl_point >= rl_mark && (_rl_to_upper (c) == 'W'))
     {
       /* Don't move farther back than where we started. */
       while (rl_point > rl_mark && whitespace (rl_line_buffer[rl_point]))
     rl_point--;
       /* Posix.2 says that if cw or cW moves the cursor towards the end of
      the line, the character under the cursor should be deleted. */
       if (rl_point == rl_mark)
     _rl_vi_advance_point ();
       else
     {
       /* Move past the end of the word so that the kill doesn't
          remove the last letter of the previous word.  Only do this
          if we are not at the end of the line. */
       if (rl_point >= 0 && rl_point < (rl_end - 1) && !whitespace (rl_line_buffer[rl_point]))
         _rl_vi_advance_point ();
     }
     }
   if (rl_mark < rl_point)
     SWAP (rl_point, rl_mark);
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     (*rl_redisplay_function)();     /* make sure motion is displayed */
 #endif
   r = vidomove_dispatch (m);
   return (r);
 }
References _rl_fix_point(), _rl_to_upper(), _rl_vi_advance_point(), _rl_vi_motion_command(), c, __rl_vimotion_context::end, __rl_vimotion_context::key, r, rl_end, RL_ISSTATE, rl_line_buffer, rl_mark, rl_point, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, SWAP, vidomove_dispatch(), and whitespace.
Referenced by rl_callback_read_char(), and rl_domove_motion_callback().
_rl_vi_done_inserting()
void _rl_vi_done_inserting (void)
Definition at line 857 of file vi_mode.c.
 {
   if (_rl_vi_doing_insert)
     {
       /* The `c', `s', `S', and `R' commands set this. */
       rl_end_undo_group (); /* for the group in rl_vi_start_inserting */
       /* Now, the text between rl_undo_list->next->start and
      rl_undo_list->next->end is what was inserted while in insert
      mode.  It gets copied to VI_INSERT_BUFFER because it depends
      on absolute indices into the line which may change (though they
      probably will not). */
       _rl_vi_doing_insert = 0;
       if (_rl_vi_last_key_before_insert == 'R')
     _rl_vi_save_replace ();     /* Half the battle */
       else
     _rl_vi_save_insert (rl_undo_list->next);
       /* sanity check, should always be >= 1 here */
       if (_rl_undo_group_level > 0)
     rl_end_undo_group ();   /* for the group in the command (change or replace) */
     }
   else
     {
       if (rl_undo_list && (_rl_vi_last_key_before_insert == 'i' ||
                _rl_vi_last_key_before_insert == 'a' ||
                _rl_vi_last_key_before_insert == 'I' ||
                _rl_vi_last_key_before_insert == 'A'))
     _rl_vi_save_insert (rl_undo_list);
       /* XXX - Other keys probably need to be checked. */
       else if (_rl_vi_last_key_before_insert == 'C')
     rl_end_undo_group ();
     }
   /* Sanity check, make sure all the undo groups are closed before we leave
      insert mode */
   while (_rl_undo_group_level > 0)
     rl_end_undo_group ();
 }
References _rl_undo_group_level, _rl_vi_doing_insert, _rl_vi_last_key_before_insert, _rl_vi_save_insert(), _rl_vi_save_replace(), undo_list::next, rl_end_undo_group(), and rl_undo_list.
Referenced by rl_newline(), and rl_vi_movement_mode().
_rl_vi_initialize_line()
void _rl_vi_initialize_line (void)
Definition at line 167 of file vi_mode.c.
 {
   register int i, n;
   n = sizeof (vi_mark_chars) / sizeof (vi_mark_chars[0]);
   for (i = 0; i < n; i++)
     vi_mark_chars[i] = -1;
   RL_UNSETSTATE(RL_STATE_VICMDONCE);
 }
References i, n, RL_STATE_VICMDONCE, RL_UNSETSTATE, and vi_mark_chars.
Referenced by rl_initialize().
_rl_vi_motion_command()
int _rl_vi_motion_command (int c)
Definition at line 213 of file vi_mode.c.
 {
   return (member (c, vi_motion));
 }
References c, member, and vi_motion.
Referenced by _rl_vi_domove_motion_cleanup().
_rl_vi_reset_last()
void _rl_vi_reset_last (void)
Definition at line 179 of file vi_mode.c.
 {
   _rl_vi_last_command = 'i';
   _rl_vi_last_repeat = 1;
   _rl_vi_last_arg_sign = 1;
   _rl_vi_last_motion = 0;
 }
References _rl_vi_last_arg_sign, _rl_vi_last_command, _rl_vi_last_motion, and _rl_vi_last_repeat.
Referenced by rl_newline().
_rl_vi_set_last()
void _rl_vi_set_last (int key, int repeat, int sign)
Definition at line 188 of file vi_mode.c.
 {
   _rl_vi_last_command = key;
   _rl_vi_last_repeat = repeat;
   _rl_vi_last_arg_sign = sign;
 }
References _rl_vi_last_arg_sign, _rl_vi_last_command, and _rl_vi_last_repeat.
Referenced by _rl_dispatch_subseq(), and rl_vi_start_inserting().
_rl_vi_textmod_command()
int _rl_vi_textmod_command (int c)
Definition at line 207 of file vi_mode.c.
 {
   return (member (c, vi_textmod));
 }
References c, member, and vi_textmod.
Referenced by _rl_dispatch_subseq(), and rl_newline().
_rl_with_macro_input()
void _rl_with_macro_input (char * string)
Definition at line 93 of file macro.c.
 {
   if (macro_level > MAX_MACRO_LEVEL)
     {
       _rl_errmsg ("maximum macro execution nesting level exceeded");
       _rl_abort_internal ();
       return;
     }
 #if 0
   if (rl_executing_macro)       /* XXX - later */
 #endif
     _rl_push_executing_macro ();
   rl_executing_macro = string;
   executing_macro_index = 0;
   RL_SETSTATE(RL_STATE_MACROINPUT);
 }
References _rl_abort_internal(), _rl_errmsg(), _rl_push_executing_macro(), executing_macro_index, macro_level, MAX_MACRO_LEVEL, rl_executing_macro, RL_SETSTATE, RL_STATE_MACROINPUT, and string.
Referenced by _rl_dispatch_subseq(), rl_call_last_kbd_macro(), rl_push_macro_input(), and rl_start_kbd_macro().
readline_internal_char()
int readline_internal_char (void)
Definition at line 562 of file readline.c.
 {
   static int lastc, eof_found;
   int c, code, lk, r;
   lastc = EOF;
 #if !defined (READLINE_CALLBACKS)
   eof_found = 0;
   while (rl_done == 0)
     {
 #endif
       lk = _rl_last_command_was_kill;
 #if defined (HAVE_POSIX_SIGSETJMP)
       code = sigsetjmp (_rl_top_level, 0);
 #else
       code = setjmp (_rl_top_level);
 #endif
       if (code)
     {
       (*rl_redisplay_function) ();
       _rl_want_redisplay = 0;
       /* If we longjmped because of a timeout, handle it here. */
       if (RL_ISSTATE (RL_STATE_TIMEOUT))
         {
           RL_SETSTATE (RL_STATE_DONE);
           rl_done = 1;
           return 1;
         }
       /* If we get here, we're not being called from something dispatched
          from _rl_callback_read_char(), which sets up its own value of
          _rl_top_level (saving and restoring the old, of course), so
          we can just return here. */
       if (RL_ISSTATE (RL_STATE_CALLBACK))
         return (0);
     }
       if (rl_pending_input == 0)
     {
       /* Then initialize the argument and number of keys read. */
       _rl_reset_argument ();
       rl_executing_keyseq[rl_key_sequence_length = 0] = '\0';
     }
       RL_SETSTATE(RL_STATE_READCMD);
       c = rl_read_key ();
       RL_UNSETSTATE(RL_STATE_READCMD);
       /* look at input.c:rl_getc() for the circumstances under which this will
      be returned; punt immediately on read error without converting it to
      a newline; assume that rl_read_key has already called the signal
      handler. */
       if (c == READERR)
     {
 #if defined (READLINE_CALLBACKS)
       RL_SETSTATE(RL_STATE_DONE);
       return (rl_done = 1);
 #else
       RL_SETSTATE(RL_STATE_EOF);
       eof_found = 1;
       break;
 #endif
     }
       /* EOF typed to a non-blank line is ^D the first time, EOF the second
      time in a row.  This won't return any partial line read from the tty.
      If we want to change this, to force any existing line to be returned
      when read(2) reads EOF, for example, this is the place to change. */
       if (c == EOF && rl_end)
     {
       if (RL_SIG_RECEIVED ())
         {
           RL_CHECK_SIGNALS ();
           if (rl_signal_event_hook)
         (*rl_signal_event_hook) ();     /* XXX */
         }
       /* XXX - reading two consecutive EOFs returns EOF */
       if (RL_ISSTATE (RL_STATE_TERMPREPPED))
         {
           if (lastc == _rl_eof_char || lastc == EOF)
         rl_end = 0;
           else
             c = _rl_eof_char;
         }
       else
         c = NEWLINE;
     }
       /* The character _rl_eof_char typed to blank line, and not as the
      previous character is interpreted as EOF.  This doesn't work when
      READLINE_CALLBACKS is defined, so hitting a series of ^Ds will
      erase all the chars on the line and then return EOF. */
       if (((c == _rl_eof_char && lastc != c) || c == EOF) && rl_end == 0)
     {
 #if defined (READLINE_CALLBACKS)
       RL_SETSTATE(RL_STATE_DONE);
       return (rl_done = 1);
 #else
       RL_SETSTATE(RL_STATE_EOF);
       eof_found = 1;
       break;
 #endif
     }
       lastc = c;
       r = _rl_dispatch ((unsigned char)c, _rl_keymap);
       RL_CHECK_SIGNALS ();
       if (_rl_command_to_execute)
     {
       (*rl_redisplay_function) ();
       rl_executing_keymap = _rl_command_to_execute->map;
       rl_executing_key = _rl_command_to_execute->key;
       _rl_executing_func = _rl_command_to_execute->func;
       rl_dispatching = 1;
       RL_SETSTATE(RL_STATE_DISPATCHING);
       r = (*(_rl_command_to_execute->func)) (_rl_command_to_execute->count, _rl_command_to_execute->key);
       _rl_command_to_execute = 0;
       RL_UNSETSTATE(RL_STATE_DISPATCHING);
       rl_dispatching = 0;
       RL_CHECK_SIGNALS ();
     }
       /* If there was no change in _rl_last_command_was_kill, then no kill
      has taken place.  Note that if input is pending we are reading
      a prefix command, so nothing has changed yet. */
       if (rl_pending_input == 0 && lk == _rl_last_command_was_kill)
     _rl_last_command_was_kill = 0;
       _rl_internal_char_cleanup ();
 #if defined (READLINE_CALLBACKS)
       return 0;
 #else
     }
   return (eof_found);
 #endif
 }
References _rl_command_to_execute, _rl_dispatch(), _rl_eof_char, _rl_executing_func, _rl_internal_char_cleanup(), _rl_keymap, _rl_last_command_was_kill, _rl_reset_argument(), _rl_top_level, _rl_want_redisplay, c, _rl_cmd::count, EOF, _rl_cmd::func, _rl_cmd::key, _rl_cmd::map, NEWLINE, r, READERR, RL_CHECK_SIGNALS, rl_dispatching, rl_done, rl_end, rl_executing_key, rl_executing_keymap, rl_executing_keyseq, RL_ISSTATE, rl_key_sequence_length, rl_pending_input, rl_read_key(), RL_SETSTATE, RL_SIG_RECEIVED, rl_signal_event_hook, RL_STATE_CALLBACK, RL_STATE_DISPATCHING, RL_STATE_DONE, RL_STATE_EOF, RL_STATE_READCMD, RL_STATE_TERMPREPPED, RL_STATE_TIMEOUT, RL_UNSETSTATE, and setjmp.
Referenced by readline_internal_charloop(), and rl_callback_read_char().
readline_internal_setup()
void readline_internal_setup (void)
Definition at line 425 of file readline.c.
 {
   char *nprompt;
   _rl_in_stream = rl_instream;
   _rl_out_stream = rl_outstream;
   /* Enable the meta key only for the duration of readline(), if this
      terminal has one and the terminal has been initialized */
   if (_rl_enable_meta & RL_ISSTATE (RL_STATE_TERMPREPPED))
     _rl_enable_meta_key ();
   run_startup_hooks ();
   rl_deactivate_mark ();
 #if defined (VI_MODE)
   if (rl_editing_mode == vi_mode)
     rl_vi_insertion_mode (1, 'i');  /* don't want to reset last */
   else
 #endif /* VI_MODE */
     if (_rl_show_mode_in_prompt)
       _rl_reset_prompt ();
   /* If we're not echoing, we still want to at least print a prompt, because
      rl_redisplay will not do it for us.  If the calling application has a
      custom redisplay function, though, let that function handle it. */
   if (_rl_echoing_p == 0 && rl_redisplay_function == rl_redisplay)
     {
       if (rl_prompt && rl_already_prompted == 0)
     {
       nprompt = _rl_strip_prompt (rl_prompt);
       fprintf (_rl_out_stream, "%s", nprompt);
       fflush (_rl_out_stream);
       xfree (nprompt);
     }
     }
   else
     {
       if (rl_prompt && rl_already_prompted)
     rl_on_new_line_with_prompt ();
       else
     rl_on_new_line ();
       (*rl_redisplay_function) ();
     }
   if (rl_pre_input_hook)
     (*rl_pre_input_hook) ();
   RL_CHECK_SIGNALS ();
 }
References _rl_echoing_p, _rl_enable_meta, _rl_enable_meta_key(), _rl_in_stream, _rl_out_stream, _rl_reset_prompt(), _rl_show_mode_in_prompt, _rl_strip_prompt(), fflush(), fprintf(), rl_already_prompted, RL_CHECK_SIGNALS, rl_deactivate_mark(), rl_editing_mode, rl_instream, RL_ISSTATE, rl_on_new_line(), rl_on_new_line_with_prompt(), rl_outstream, rl_pre_input_hook, rl_prompt, rl_redisplay(), rl_redisplay_function, RL_STATE_TERMPREPPED, rl_vi_insertion_mode(), run_startup_hooks(), vi_mode, and xfree.
Referenced by _rl_callback_newline(), and readline_internal().
readline_internal_teardown()
char* readline_internal_teardown (int eof)
Definition at line 478 of file readline.c.
 {
   char *temp;
   HIST_ENTRY *entry;
   RL_CHECK_SIGNALS ();
   if (eof)
     RL_SETSTATE (RL_STATE_EOF);     /* XXX */
   /* Restore the original of this history line, iff the line that we
      are editing was originally in the history, AND the line has changed. */
   entry = current_history ();
   /* We don't want to do this if we executed functions that call
      history_set_pos to set the history offset to the line containing the
      non-incremental search string. */
   if (entry && rl_undo_list)
    {
       temp = savestring (the_line);
       rl_revert_line (1, 0);
       entry = replace_history_entry (where_history (), the_line, (histdata_t)NULL);
       _rl_free_history_entry (entry);
       strcpy (the_line, temp);
       xfree (temp);
     }
   if (_rl_revert_all_at_newline)
     _rl_revert_all_lines ();
   /* At any rate, it is highly likely that this line has an undo list.  Get
      rid of it now. */
   if (rl_undo_list)
     rl_free_undo_list ();
   /* Disable the meta key, if this terminal has one and we were told to use it.
      The check whether or not we sent the enable string is in
      _rl_disable_meta_key(); the flag is set in _rl_enable_meta_key */
   _rl_disable_meta_key ();
   /* Restore normal cursor, if available. */
   _rl_set_insert_mode (RL_IM_INSERT, 0);
   return (eof ? (char *)NULL : savestring (the_line));
 }
References _rl_disable_meta_key(), _rl_free_history_entry(), _rl_revert_all_at_newline, _rl_revert_all_lines(), _rl_set_insert_mode(), current_history(), NULL, replace_history_entry(), RL_CHECK_SIGNALS, rl_free_undo_list(), RL_IM_INSERT, rl_revert_line(), RL_SETSTATE, RL_STATE_EOF, rl_undo_list, savestring(), strcpy, the_line, where_history(), and xfree.
Referenced by readline_internal(), and rl_callback_read_char().
rl_set_retained_kills()
int rl_set_retained_kills (int num)
Definition at line 81 of file kill.c.
 {
   return 0;
 }
Variable Documentation
_rl_active_region_end_color
char* _rl_active_region_end_color extern
Definition at line 191 of file terminal.c.
Referenced by _rl_region_color_off(), _rl_region_color_on(), and _rl_reset_region_color().
_rl_active_region_start_color
char* _rl_active_region_start_color extern
Definition at line 190 of file terminal.c.
Referenced by _rl_region_color_off(), _rl_region_color_on(), and _rl_reset_region_color().
_rl_argcxt
_rl_arg_cxt _rl_argcxt extern
Definition at line 64 of file misc.c.
Referenced by _rl_arg_callback(), _rl_arg_dispatch(), _rl_arg_init(), _rl_arg_overflow(), _rl_reset_argument(), rl_callback_read_char(), rl_callback_sigcleanup(), rl_digit_argument(), and rl_digit_loop().
_rl_bell_preference
int _rl_bell_preference extern
Definition at line 235 of file readline.c.
Referenced by _rl_get_string_variable_value(), hack_special_boolean_var(), rl_ding(), and sv_bell_style().
_rl_bind_stty_chars
int _rl_bind_stty_chars extern
Definition at line 308 of file readline.c.
Referenced by readline_default_bindings(), reset_default_bindings(), and rl_prep_terminal().
_rl_callback_data
_rl_callback_generic_arg* _rl_callback_data extern
Definition at line 51 of file callback.c.
Referenced by rl_backward_char_search(), rl_callback_read_char(), rl_char_search(), rl_quoted_insert(), rl_vi_change_char(), rl_vi_char_search(), rl_vi_goto_mark(), and rl_vi_set_mark().
_rl_callback_func
_rl_callback_func_t* _rl_callback_func extern
Definition at line 50 of file callback.c.
Referenced by _rl_char_search_callback(), _rl_insert_next_callback(), _rl_vi_callback_change_char(), _rl_vi_callback_char_search(), _rl_vi_callback_goto_mark(), _rl_vi_callback_set_mark(), rl_backward_char_search(), rl_callback_read_char(), rl_callback_sigcleanup(), rl_char_search(), rl_quoted_insert(), rl_vi_change_char(), rl_vi_char_search(), rl_vi_goto_mark(), and rl_vi_set_mark().
_rl_caught_signal
int volatile _rl_caught_signal extern
Definition at line 90 of file signals.c.
Referenced by _rl_signal_handler(), rl_getc(), rl_pending_signal(), and rl_signal_handler().
_rl_colored_completion_prefix
int _rl_colored_completion_prefix extern
Definition at line 216 of file complete.c.
Referenced by fnprint(), readline_initialize_everything(), and rl_display_match_list().
_rl_colored_stats
int _rl_colored_stats extern
Definition at line 212 of file complete.c.
Referenced by _rl_parse_colors(), fnprint(), print_filename(), and readline_initialize_everything().
_rl_command_to_execute
struct _rl_cmd* _rl_command_to_execute extern
Definition at line 268 of file readline.c.
Referenced by _rl_isearch_dispatch(), and readline_internal_char().
_rl_comment_begin
char* _rl_comment_begin extern
Definition at line 238 of file readline.c.
Referenced by _rl_get_string_variable_value(), rl_insert_comment(), and sv_combegin().
_rl_complete_mark_directories
int _rl_complete_mark_directories extern
Definition at line 172 of file complete.c.
Referenced by append_to_match(), and print_filename().
_rl_complete_mark_symlink_dirs
int _rl_complete_mark_symlink_dirs extern
Definition at line 178 of file complete.c.
Referenced by set_completion_defaults().
_rl_complete_show_all
int _rl_complete_show_all extern
Definition at line 165 of file complete.c.
Referenced by rl_complete(), rl_completion_mode(), rl_menu_complete(), and rl_old_menu_complete().
_rl_complete_show_unmodified
int _rl_complete_show_unmodified extern
Definition at line 169 of file complete.c.
Referenced by rl_complete(), and rl_completion_mode().
_rl_completion_case_fold
int _rl_completion_case_fold extern
Definition at line 188 of file complete.c.
Referenced by complete_fncmp(), and compute_lcd_of_matches().
_rl_completion_case_map
int _rl_completion_case_map extern
Definition at line 193 of file complete.c.
Referenced by complete_fncmp().
_rl_completion_columns
int _rl_completion_columns extern
Definition at line 207 of file complete.c.
Referenced by _rl_get_string_variable_value(), complete_get_screenwidth(), and sv_compwidth().
_rl_completion_prefix_display_length
int _rl_completion_prefix_display_length extern
Definition at line 203 of file complete.c.
Referenced by _rl_get_string_variable_value(), fnprint(), rl_display_match_list(), and sv_dispprefix().
_rl_convert_meta_chars_to_ascii
int _rl_convert_meta_chars_to_ascii extern
Definition at line 300 of file readline.c.
Referenced by _rl_dispatch_subseq(), _rl_function_of_keyseq_internal(), _rl_set_localevars(), rl_bind_key(), rl_generic_bind(), rl_invoking_keyseqs_in_map(), and rl_translate_keyseq().
_rl_doing_an_undo
int _rl_doing_an_undo extern
Definition at line 56 of file undo.c.
Referenced by rl_delete_text(), rl_do_undo(), and rl_insert_text().
_rl_echo_control_chars
int _rl_echo_control_chars extern
Definition at line 317 of file readline.c.
Referenced by rl_echo_signal_char().
_rl_echoctl
int _rl_echoctl extern
Definition at line 94 of file signals.c.
Referenced by prepare_terminal_settings(), and rl_echo_signal_char().
_rl_echoing_p
int _rl_echoing_p extern
Definition at line 187 of file readline.c.
Referenced by _rl_clean_up_for_exit(), prepare_terminal_settings(), readline_internal_setup(), rl_deprep_terminal(), rl_ding(), rl_newline(), rl_prep_terminal(), rl_redisplay(), rl_resize_terminal(), rl_tty_set_echoing(), and set_tty_settings().
_rl_emacs_mode_str
char* _rl_emacs_mode_str extern
Definition at line 180 of file display.c.
Referenced by prompt_modestr().
_rl_emacs_modestr_len
int _rl_emacs_modestr_len extern
Definition at line 181 of file display.c.
Referenced by prompt_modestr(), and sv_emacs_modestr().
_rl_enable_active_region
int _rl_enable_active_region extern
Definition at line 327 of file readline.c.
Referenced by _rl_init_terminal_io(), _rl_isearch_dispatch(), hack_special_boolean_var(), noninc_dosearch(), and rl_bracketed_paste_begin().
_rl_enable_bracketed_paste
int _rl_enable_bracketed_paste extern
Definition at line 326 of file readline.c.
Referenced by _rl_bracketed_read_key(), _rl_init_terminal_io(), _rl_isearch_dispatch(), _rl_nsearch_dispatch(), hack_special_boolean_var(), rl_prep_terminal(), and rl_vi_replace().
_rl_enable_keypad
int _rl_enable_keypad extern
Definition at line 212 of file terminal.c.
Referenced by rl_deprep_terminal(), and rl_prep_terminal().
_rl_enable_meta
int _rl_enable_meta extern
Definition at line 215 of file terminal.c.
Referenced by readline_internal_setup().
_rl_eof_char
int _rl_eof_char extern
Definition at line 218 of file readline.c.
Referenced by prepare_terminal_settings(), and readline_internal_char().
_rl_executing_func
rl_command_func_t* _rl_executing_func extern
Definition at line 244 of file readline.c.
Referenced by _rl_dispatch_subseq(), and readline_internal_char().
_rl_executing_keyseq_size
int _rl_executing_keyseq_size extern
Definition at line 265 of file readline.c.
Referenced by readline_initialize_everything().
_rl_executing_macro
char* _rl_executing_macro extern
_rl_history_preserve_point
int _rl_history_preserve_point extern
Definition at line 62 of file misc.c.
Referenced by _rl_history_set_point(), and rl_newline().
_rl_history_saved_point
int _rl_history_saved_point extern
Definition at line 68 of file misc.c.
Referenced by _rl_history_set_point(), rl_get_next_history(), rl_get_previous_history(), and rl_newline().
_rl_history_search_pos
int _rl_history_search_pos extern
Definition at line 64 of file search.c.
Referenced by _rl_start_using_history(), rl_history_search_internal(), and rl_history_search_reinit().
_rl_horizontal_scroll_mode
int _rl_horizontal_scroll_mode extern
Definition at line 227 of file readline.c.
Referenced by readline_initialize_everything(), rl_redisplay(), and update_line().
_rl_in_stream
FILE* _rl_in_stream extern
Definition at line 177 of file readline.c.
Referenced by readline_initialize_everything(), and readline_internal_setup().
_rl_internal_startup_hook
rl_hook_func_t* _rl_internal_startup_hook extern
Definition at line 206 of file readline.c.
Referenced by rl_operate_and_get_next(), run_startup_hooks(), and set_saved_history().
_rl_intr_char
int _rl_intr_char extern
Definition at line 96 of file signals.c.
Referenced by rl_echo_signal_char(), and save_tty_chars().
_rl_iscxt
_rl_search_cxt* _rl_iscxt extern
Definition at line 60 of file isearch.c.
Referenced by _rl_isearch_cleanup(), _rl_isearch_init(), rl_callback_read_char(), and rl_callback_sigcleanup().
_rl_isearch_terminators
char* _rl_isearch_terminators extern
Definition at line 58 of file isearch.c.
Referenced by _rl_get_string_variable_value(), _rl_isearch_init(), and sv_isrchterm().
_rl_keep_mark_active
int _rl_keep_mark_active extern
Definition at line 1863 of file text.c.
Referenced by _rl_internal_char_cleanup(), and rl_keep_mark_active().
_rl_keymap
Keymap _rl_keymap extern
Definition at line 119 of file readline.c.
Referenced by _rl_arg_dispatch(), _rl_dispatch_subseq(), _rl_function_of_keyseq_internal(), _rl_get_string_variable_value(), _rl_history_set_point(), _rl_insert_typein(), _rl_internal_char_cleanup(), _rl_isearch_dispatch(), _rl_scxt_alloc(), _rl_vi_arg_dispatch(), bind_arrow_keys_internal(), bind_bracketed_paste_prefix(), bind_termcap_arrow_keys(), prompt_modestr(), readline_default_bindings(), readline_internal_char(), reset_default_bindings(), rl_bind_key(), rl_bind_key_if_unbound(), rl_bind_key_in_map(), rl_bind_keyseq(), rl_bind_keyseq_if_unbound(), rl_domove_motion_callback(), rl_emacs_editing_mode(), rl_function_dumper(), rl_get_keymap(), rl_insert(), rl_invoking_keyseqs(), rl_macro_dumper(), rl_parse_and_bind(), rl_prep_terminal(), rl_restore_state(), rl_save_state(), rl_set_keymap(), rl_set_keymap_from_edit_mode(), rl_trim_arg_from_keyseq(), rl_vi_insertion_mode(), rl_vi_movement_mode(), rl_vi_redo(), rl_vi_replace(), rl_yank_nth_arg_internal(), and sv_editmode().
_rl_keyseq_timeout
int _rl_keyseq_timeout extern
Definition at line 272 of file readline.c.
Referenced by _rl_dispatch_subseq(), _rl_get_string_variable_value(), _rl_isearch_dispatch(), and sv_seqtimeout().
_rl_kscxt
_rl_keyseq_cxt* _rl_kscxt extern
Definition at line 261 of file readline.c.
Referenced by _rl_dispatch_callback(), _rl_dispatch_subseq(), _rl_keyseq_chain_dispose(), _rl_keyseq_cxt_alloc(), and rl_callback_read_char().
_rl_last_c_pos
int _rl_last_c_pos extern
Definition at line 200 of file display.c.
Referenced by _rl_current_display_line(), _rl_erase_at_end_of_line(), _rl_move_cursor_relative(), _rl_move_vert(), _rl_rubout_char(), _rl_update_final(), cr(), rl_clear_visible_line(), rl_deprep_terminal(), rl_on_new_line(), rl_on_new_line_with_prompt(), rl_redisplay(), space_to_eol(), and update_line().
_rl_last_command_was_kill
int _rl_last_command_was_kill extern
Definition at line 133 of file readline.c.
Referenced by _rl_copy_to_kill_ring(), readline_internal_char(), region_kill_internal(), and rl_kill_text().
_rl_mark_modified_lines
int _rl_mark_modified_lines extern
Definition at line 231 of file readline.c.
Referenced by rl_redisplay().
_rl_match_hidden_files
int _rl_match_hidden_files extern
Definition at line 197 of file complete.c.
Referenced by rl_filename_completion_function().
_rl_menu_complete_prefix_first
int _rl_menu_complete_prefix_first extern
Definition at line 227 of file complete.c.
Referenced by rl_menu_complete().
_rl_meta_flag
int _rl_meta_flag extern
Definition at line 336 of file readline.c.
Referenced by _rl_callback_newline(), _rl_set_localevars(), readline(), and rl_reset_after_signal().
_rl_nscxt
_rl_search_cxt* _rl_nscxt extern
Definition at line 56 of file search.c.
Referenced by _rl_nsearch_cleanup(), _rl_nsearch_init(), rl_callback_read_char(), and rl_callback_sigcleanup().
_rl_optimize_typeahead
int _rl_optimize_typeahead extern
Definition at line 74 of file text.c.
Referenced by rl_insert().
_rl_out_stream
FILE* _rl_out_stream extern
Definition at line 177 of file readline.c.
Referenced by _rl_backspace(), _rl_output_character_function(), _rl_output_some_chars(), readline_initialize_everything(), readline_internal_setup(), and rl_crlf().
_rl_output_meta_chars
int _rl_output_meta_chars extern
Definition at line 304 of file readline.c.
Referenced by _rl_set_localevars(), rl_character_len(), rl_redisplay(), and rl_show_char().
_rl_page_completions
int _rl_page_completions extern
Definition at line 294 of file complete.c.
Referenced by rl_display_match_list().
_rl_parsing_conditionalized_out
unsigned char _rl_parsing_conditionalized_out extern
Definition at line 295 of file readline.c.
Referenced by parser_else(), parser_endif(), parser_if(), parser_include(), rl_initialize(), and rl_parse_and_bind().
_rl_pending_command
struct _rl_cmd _rl_pending_command extern
Definition at line 265 of file readline.c.
Referenced by _rl_isearch_dispatch().
_rl_possible_control_prefixes
const char* const _rl_possible_control_prefixes[] extern
Definition at line 1228 of file bind.c.
Referenced by rl_parse_and_bind().
_rl_possible_meta_prefixes
const char* const _rl_possible_meta_prefixes[] extern
Definition at line 1232 of file bind.c.
Referenced by rl_parse_and_bind().
_rl_print_completions_horizontally
int _rl_print_completions_horizontally extern
Definition at line 182 of file complete.c.
Referenced by rl_display_match_list().
_rl_quit_char
int _rl_quit_char extern
Definition at line 97 of file signals.c.
Referenced by rl_echo_signal_char(), and save_tty_chars().
_rl_revert_all_at_newline
int _rl_revert_all_at_newline extern
Definition at line 313 of file readline.c.
Referenced by readline_internal_teardown().
_rl_screenchars
int _rl_screenchars extern
Definition at line 209 of file terminal.c.
Referenced by _rl_get_screen_size(), _rl_init_terminal_io(), _rl_set_screen_size(), readline_initialize_everything(), and rl_redisplay().
_rl_screenheight
int _rl_screenheight extern
Definition at line 209 of file terminal.c.
Referenced by _rl_get_screen_size(), _rl_init_terminal_io(), _rl_move_vert(), _rl_set_screen_size(), readline_initialize_everything(), rl_display_match_list(), rl_get_screen_size(), rl_redisplay(), rl_reset_terminal(), and rl_resize_terminal().
_rl_screenwidth
int _rl_screenwidth extern
Definition at line 209 of file terminal.c.
Referenced by _rl_current_display_line(), _rl_get_screen_size(), _rl_init_terminal_io(), _rl_move_cursor_relative(), _rl_redisplay_after_sigwinch(), _rl_set_screen_size(), _rl_update_final(), complete_get_screenwidth(), delete_chars(), expand_prompt(), readline_initialize_everything(), realloc_line(), rl_clear_visible_line(), rl_display_match_list(), rl_get_screen_size(), rl_next_screen_line(), rl_on_new_line_with_prompt(), rl_previous_screen_line(), rl_redisplay(), rl_reset_terminal(), rl_resize_terminal(), and update_line().
_rl_show_mode_in_prompt
int _rl_show_mode_in_prompt extern
Definition at line 321 of file readline.c.
Referenced by expand_prompt(), readline_internal_setup(), rl_emacs_editing_mode(), rl_vi_insertion_mode(), and rl_vi_movement_mode().
_rl_sigcleanarg
void* _rl_sigcleanarg extern
Definition at line 122 of file signals.c.
Referenced by _rl_handle_signal(), and rl_complete_internal().
_rl_sigcleanup
_rl_sigcleanup_func_t* _rl_sigcleanup extern
Definition at line 121 of file signals.c.
Referenced by _rl_handle_signal(), and rl_complete_internal().
_rl_skip_completed_text
int _rl_skip_completed_text extern
Definition at line 223 of file complete.c.
Referenced by insert_match().
_rl_suppress_redisplay
int _rl_suppress_redisplay extern
Definition at line 192 of file display.c.
_rl_susp_char
int _rl_susp_char extern
Definition at line 98 of file signals.c.
Referenced by rl_echo_signal_char(), and save_tty_chars().
_rl_term_autowrap
int _rl_term_autowrap extern
Definition at line 145 of file terminal.c.
Referenced by _rl_get_screen_size(), _rl_init_terminal_io(), _rl_move_cursor_relative(), _rl_set_screen_size(), _rl_update_final(), readline_initialize_everything(), rl_next_screen_line(), rl_on_new_line_with_prompt(), rl_previous_screen_line(), and update_line().
_rl_term_clreol
char* _rl_term_clreol extern
Definition at line 113 of file terminal.c.
Referenced by _rl_clear_to_eol(), and _rl_init_terminal_io().
_rl_term_clrpag
char* _rl_term_clrpag extern
Definition at line 114 of file terminal.c.
Referenced by _rl_clear_screen(), and _rl_init_terminal_io().
_rl_term_clrscroll
char* _rl_term_clrscroll extern
Definition at line 115 of file terminal.c.
Referenced by _rl_clear_screen(), and _rl_init_terminal_io().
_rl_term_cr
char* _rl_term_cr extern
Definition at line 116 of file terminal.c.
Referenced by _rl_cr(), _rl_init_terminal_io(), _rl_redisplay_after_sigwinch(), rl_crlf(), and update_line().
_rl_term_DC
char* _rl_term_DC extern
Definition at line 133 of file terminal.c.
Referenced by _rl_init_terminal_io(), and delete_chars().
_rl_term_dc
char* _rl_term_dc extern
Definition at line 132 of file terminal.c.
Referenced by _rl_init_terminal_io(), delete_chars(), and update_line().
_rl_term_ei
char* _rl_term_ei extern
Definition at line 126 of file terminal.c.
Referenced by _rl_init_terminal_io(), and open_some_spaces().
_rl_term_forward_char
char* _rl_term_forward_char extern
Definition at line 136 of file terminal.c.
Referenced by _rl_init_terminal_io(), and _rl_move_cursor_relative().
_rl_term_ic
char* _rl_term_ic extern
Definition at line 127 of file terminal.c.
Referenced by _rl_init_terminal_io(), and open_some_spaces().
_rl_term_IC
char* _rl_term_IC extern
Definition at line 129 of file terminal.c.
Referenced by _rl_init_terminal_io(), open_some_spaces(), and update_line().
_rl_term_im
char* _rl_term_im extern
Definition at line 125 of file terminal.c.
Referenced by _rl_init_terminal_io(), and open_some_spaces().
_rl_term_up
char* _rl_term_up extern
Definition at line 139 of file terminal.c.
Referenced by _rl_init_terminal_io(), _rl_move_vert(), and rl_redisplay().
_rl_terminal_can_insert
int _rl_terminal_can_insert extern
Definition at line 122 of file terminal.c.
Referenced by _rl_init_terminal_io(), and update_line().
_rl_top_level
procenv_t _rl_top_level extern
Definition at line 174 of file readline.c.
Referenced by _rl_abort_internal(), readline_internal_char(), and rl_callback_read_char().
_rl_undo_group_level
int _rl_undo_group_level extern
Definition at line 59 of file undo.c.
Referenced by _rl_vi_done_inserting(), rl_begin_undo_group(), and rl_end_undo_group().
_rl_utf8locale
int _rl_utf8locale extern
Definition at line 68 of file mbutil.c.
Referenced by _rl_init_locale(), _rl_insert_char(), _rl_set_localevars(), rl_redisplay(), and update_line().
_rl_vi_cmd_mode_str
char* _rl_vi_cmd_mode_str extern
Definition at line 186 of file display.c.
Referenced by _rl_get_string_variable_value(), prompt_modestr(), and sv_vicmd_modestr().
_rl_vi_cmd_modestr_len
int _rl_vi_cmd_modestr_len extern
Definition at line 187 of file display.c.
Referenced by prompt_modestr(), and sv_vicmd_modestr().
_rl_vi_ins_mode_str
char* _rl_vi_ins_mode_str extern
Definition at line 183 of file display.c.
Referenced by _rl_get_string_variable_value(), prompt_modestr(), and sv_viins_modestr().
_rl_vi_ins_modestr_len
int _rl_vi_ins_modestr_len extern
Definition at line 184 of file display.c.
Referenced by prompt_modestr(), and sv_viins_modestr().
_rl_vi_last_command
int _rl_vi_last_command extern
Definition at line 81 of file vi_mode.c.
Referenced by _rl_vi_reset_last(), _rl_vi_set_last(), rl_newline(), and rl_vi_redo().
_rl_vi_redoing
int _rl_vi_redoing extern
Definition at line 86 of file vi_mode.c.
Referenced by _rl_dispatch_subseq(), rl_vi_change_char(), rl_vi_change_to(), rl_vi_char_search(), rl_vi_delete_to(), rl_vi_redo(), rl_vi_subst(), rl_vi_yank_to(), and vi_change_dispatch().
_rl_vimvcxt
_rl_vimotion_cxt* _rl_vimvcxt extern
Definition at line 83 of file vi_mode.c.
Referenced by rl_callback_read_char(), rl_vi_change_to(), rl_vi_delete_to(), rl_vi_domove(), and rl_vi_yank_to().
_rl_vis_botlin
int _rl_vis_botlin extern
Definition at line 205 of file display.c.
Referenced by _rl_clean_up_for_exit(), _rl_optimize_redisplay(), _rl_update_final(), display_matches(), rl_clear_visible_line(), rl_on_new_line(), rl_on_new_line_with_prompt(), rl_redisplay(), and update_line().
_rl_want_redisplay
int _rl_want_redisplay extern
Definition at line 193 of file display.c.
Referenced by _rl_char_search_callback(), _rl_insert_next_callback(), _rl_internal_char_cleanup(), _rl_vi_callback_change_char(), _rl_vi_callback_char_search(), _rl_vi_callback_goto_mark(), _rl_vi_callback_set_mark(), readline_internal_char(), rl_callback_read_char(), and rl_newline().
rl_arg_sign
int rl_arg_sign extern
Definition at line 142 of file readline.c.
Referenced by _rl_arg_callback(), _rl_arg_dispatch(), _rl_arg_getchar(), _rl_dispatch_subseq(), _rl_reset_argument(), rl_digit_argument(), rl_vi_append_mode(), rl_vi_complete(), rl_vi_insert_mode(), rl_vi_redo(), rl_vi_replace(), rl_vi_tilde_expand(), and vi_change_dispatch().
rl_blink_matching_paren
int rl_blink_matching_paren extern
Definition at line 60 of file parens.c.
Referenced by hack_special_boolean_var(), and rl_insert_close().
rl_byte_oriented
int rl_byte_oriented extern
Definition at line 64 of file mbutil.c.
Referenced by _rl_bracketed_read_mbstring(), _rl_insert_char(), _rl_isearch_dispatch(), _rl_move_cursor_relative(), _rl_nsearch_dispatch(), _rl_overwrite_char(), _rl_rubout_char(), _rl_search_getchar(), _rl_strpbrk(), _rl_vi_advance_point(), _rl_vi_backup(), _rl_vi_backup_point(), _rl_vi_callback_change_char(), _rl_vi_change_char(), complete_fncmp(), compute_lcd_of_matches(), expand_prompt(), get_history_event(), get_subst_pattern(), history_expand(), history_expand_internal(), rl_arrow_keys(), rl_change_case(), rl_delete(), rl_on_new_line_with_prompt(), rl_redisplay(), rl_vi_change_case(), rl_vi_change_char(), rl_vi_delete(), rl_vi_match(), rl_vi_rubout(), and update_line().
rl_complete_with_tilde_expansion
int rl_complete_with_tilde_expansion extern
Definition at line 259 of file complete.c.
Referenced by rl_filename_completion_function().
rl_display_fixed
int rl_display_fixed extern
Definition at line 173 of file display.c.
Referenced by _rl_erase_at_end_of_line(), _rl_update_final(), display_matches(), rl_clear_display(), rl_clear_screen(), rl_print_last_kbd_macro(), rl_redisplay(), and rl_refresh_line().
rl_line_buffer_len
int rl_line_buffer_len extern
Definition at line 258 of file readline.c.
Referenced by readline_initialize_everything(), rl_extend_line_buffer(), rl_insert_text(), rl_replace_line(), rl_restore_state(), and rl_save_state().
rl_visible_prompt_length
int rl_visible_prompt_length extern
Definition at line 191 of file readline.c.
Referenced by _rl_current_display_line(), _rl_reset_prompt(), and rl_set_prompt().
rl_visible_stats
int rl_visible_stats extern
Definition at line 235 of file complete.c.
Referenced by print_filename().