Fennix: Userspace/musl/src/stdlib/ecvt.c File Reference
ecvt.c File Reference
#include <stdlib.h>
#include <stdio.h>
Macros
#define _GNU_SOURCE
Functions
char * ecvt (double x, int n, int *dp, int *sign)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file ecvt.c.
Function Documentation
ecvt()
char* ecvt (double x, int n, int * dp, int * sign)
Definition at line 5 of file ecvt.c.
 {
     static char buf[16];
     char tmp[32];
     int i, j;
     if (n-1U > 15) n = 15;
     sprintf(tmp, "%.*e", n-1, x);
     i = *sign = (tmp[0]=='-');
     for (j=0; tmp[i]!='e'; j+=(tmp[i++]!='.'))
         buf[j] = tmp[i];
     buf[j] = 0;
     *dp = atoi(tmp+i+1)+1;
     return buf;
 }
References atoi(), buf, i, j, n, sprintf(), and x.
Referenced by fcvt().