Fennix: Kernel/syscalls/native/mprotect.cpp File Reference
mprotect.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
#include "../../ipc.h"
Macros
#define SysFrm SyscallsFrame
Functions
int sys_mprotect (SysFrm *, void *addr, size_t len, int prot)
Macro Definition Documentation
SysFrm
#define SysFrm SyscallsFrame
Definition at line 38 of file mprotect.cpp.
Function Documentation
sys_mprotect()
int sys_mprotect (SysFrm * , void * addr, size_t len, int prot)
Definition at line 47 of file mprotect.cpp.
 {
     if (len == 0)
         return -EINVAL;
     if (uintptr_t(addr) % PAGE_SIZE)
         return -EINVAL;
     bool p_None = prot & sc_PROT_NONE;
     bool p_Read = prot & sc_PROT_READ;
     bool p_Write = prot & sc_PROT_WRITE;
     // bool p_Exec = prot & sc_PROT_EXEC;
     Tasking::PCB *pcb = thisProcess;
     Memory::Virtual vmm = Memory::Virtual(pcb->PageTable);
     for (uintptr_t i = uintptr_t(addr);
          i < uintptr_t(addr) + len;
          i += PAGE_SIZE)
     {
         if (likely(!vmm.Check((void *)i, Memory::G)))
         {
             Memory::PageTableEntry *pte = vmm.GetPTE(addr);
             if (!pte->Present ||
                 (!pte->UserSupervisor && p_Read) ||
                 (!pte->ReadWrite && p_Write))
             {
                 debug("Page %p is not mapped with the correct permissions",
                       (void *)i);
                 return -EACCES;
             }
             pte->Present = p_None;
             pte->UserSupervisor = p_Read;
             pte->ReadWrite = p_Write;
             // pte->ExecuteDisable = p_Exec;
 #if defined(a64)
             CPU::x64::invlpg(addr);
 #elif defined(a32)
             CPU::x32::invlpg(addr);
 #elif defined(aa64)
             asmv("dsb sy");
             asmv("tlbi vae1is, %0"
                  :
                  : "r"(addr)
                  : "memory");
             asmv("dsb sy");
             asmv("isb");
 #endif
         }
         else
         {
             warn("%p is a global page", (void *)i);
             return -ENOMEM;
         }
     }
     return 0;
 }
References addr, asmv(), Memory::Virtual::Check(), debug, EACCES, EINVAL, ENOMEM, Memory::G, Memory::Virtual::GetPTE(), i, x32::invlpg(), len, likely, PAGE_SIZE, Tasking::PCB::PageTable, sc_PROT_NONE, sc_PROT_READ, sc_PROT_WRITE, thisProcess, and warn.
Referenced by linux_mprotect().