Fennix: Memory::VirtualMemoryArea Class Reference
Memory::VirtualMemoryArea Class Reference
#include <vma.hpp>
Data Structures
struct AllocatedPages
struct SharedRegion
Public Member Functions
uint64_t GetAllocatedMemorySize ()
void * RequestPages (size_t Count, bool User=false, bool Protect=false)
void FreePages (void *Address, size_t Count)
void DetachAddress (void *Address)
void * CreateCoWRegion (void *Address, size_t Length, bool Read, bool Write, bool Exec, bool Fixed, bool Shared)
bool HandleCoW (uintptr_t PFA)
void FreeAllPages ()
void Fork (VirtualMemoryArea *Parent)
void Reserve (void *Address, size_t Length)
void Unreserve (void *Address, size_t Length)
int Map (void *VirtualAddress, void *PhysicalAddress, size_t Length, uint64_t Flags)
int Remap (void *VirtualAddress, void *PhysicalAddress, uint64_t Flags)
int Unmap (void *VirtualAddress, size_t Length)
void * __UserCheckAndGetAddress (void *Address, size_t Length)
int __UserCheck (void *Address, size_t Length)
template<typename T >
T UserCheckAndGetAddress (T Address, size_t Length=0)
template<typename T >
int UserCheck (T Address, size_t Length=0)
VirtualMemoryArea (PageTable *Table)
~VirtualMemoryArea ()
Data Fields
PageTable * Table = nullptr
Private Member Functions
NewLock (MgrLock)
Private Attributes
Bitmap PageBitmap
std::list< AllocatedPages > AllocatedPagesList
std::list< SharedRegion > SharedRegions
Detailed Description
Definition at line 32 of file vma.hpp.
Data Structure Documentation
Memory::VirtualMemoryArea::AllocatedPages
struct Memory::VirtualMemoryArea::AllocatedPages
Definition at line 35 of file vma.hpp.
Data Fields
void * Address
size_t PageCount
bool Protected
Memory::VirtualMemoryArea::SharedRegion
struct Memory::VirtualMemoryArea::SharedRegion
Definition at line 42 of file vma.hpp.
Data Fields
void * Address
bool Exec
bool Fixed
size_t Length
bool Read
size_t ReferenceCount
bool Shared
bool Write
Constructor & Destructor Documentation
VirtualMemoryArea()
Memory::VirtualMemoryArea::VirtualMemoryArea (PageTable * Table)
Definition at line 469 of file vma.cpp.
         : Table(_Table)
     {
         SmartLock(MgrLock);
         if (_Table == nullptr)
         {
             if (TaskManager)
             {
                 Tasking::PCB *pcb = thisProcess;
                 assert(pcb);
                 this->Table = thisProcess->PageTable;
             }
             else
                 this->Table = (PageTable *)CPU::PageTable();
         }
     }
References assert, CPU::PageTable(), pcb, Table, TaskManager, and thisProcess.
~VirtualMemoryArea()
Memory::VirtualMemoryArea::~VirtualMemoryArea ()
Definition at line 486 of file vma.cpp.
     {
         /* No need to remap pages, the page table will be destroyed */
         SmartLock(MgrLock);
         foreach (auto ap in AllocatedPagesList)
             KernelAllocator.FreePages(ap.Address, ap.PageCount);
     }
References AllocatedPagesList, and KernelAllocator.
Member Function Documentation
__UserCheck()
int Memory::VirtualMemoryArea::__UserCheck (void * Address, size_t Length)
Definition at line 457 of file vma.cpp.
     {
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         if (vmm.Check(Address, PTFlag::US))
             return 0;
         debug("Address %#lx is not user accessible", Address);
         return -EFAULT;
     }
References Address, Memory::Virtual::Check(), debug, EFAULT, Table, and Memory::US.
Referenced by UserCheck().
__UserCheckAndGetAddress()
void * Memory::VirtualMemoryArea::__UserCheckAndGetAddress (void * Address, size_t Length)
Definition at line 431 of file vma.cpp.
     {
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         void *pAddress = this->Table->Get(Address);
         if (pAddress == nullptr)
         {
             debug("Virtual address %#lx returns nullptr", Address);
             return nullptr;
         }
         uintptr_t intAddress = (uintptr_t)Address;
         intAddress = ALIGN_DOWN(intAddress, PAGE_SIZE);
         for (uintptr_t va = intAddress; va < intAddress + Length; va += PAGE_SIZE)
         {
             if (vmm.Check((void *)va, PTFlag::US))
                 continue;
             debug("Unable to get address %#lx, page is not user accessible", va);
             return nullptr;
         }
         return pAddress;
     }
References Address, ALIGN_DOWN, Memory::Virtual::Check(), debug, Memory::PageTable::Get(), Length, PAGE_SIZE, Table, and Memory::US.
Referenced by linux_reboot(), and UserCheckAndGetAddress().
CreateCoWRegion()
void * Memory::VirtualMemoryArea::CreateCoWRegion (void * Address, size_t Length, bool Read, bool Write, bool Exec, bool Fixed, bool Shared)
Create a Copy-on-Write region
Parameters
Address Hint address
Length Length of the region
Read Make the region readable
Write Make the region writable
Exec Make the region executable
Fixed Fixed address
Shared Shared region
Returns
Address of the region
Definition at line 126 of file vma.cpp.
     {
         func("%#lx, %lld, %s, %s, %s, %s, %s", Address, Length,
              Read ? "true" : "false",
              Write ? "true" : "false",
              Exec ? "true" : "false",
              Fixed ? "true" : "false",
              Shared ? "true" : "false");
         Virtual vmm(this->Table);
         // FIXME
         // for (uintptr_t j = uintptr_t(Address);
         //   j < uintptr_t(Address) + Length;
         //   j += PAGE_SIZE)
         // {
         //  if (vmm.Check((void *)j, G))
         //  {
         //      if (Fixed)
         //          return (void *)-EINVAL;
         //      Address = (void *)(j + PAGE_SIZE);
         //  }
         // }
         bool AnyAddress = Address == nullptr;
         debug("AnyAddress: %s", AnyAddress ? "true" : "false");
         if (AnyAddress)
         {
             Address = this->RequestPages(TO_PAGES(Length), true);
             debug("Allocated %#lx-%#lx for pt %#lx",
                   Address, (uintptr_t)Address + Length, this->Table);
             return Address;
         }
         SmartLock(MgrLock);
         if (vmm.Check(Address, PTFlag::KRsv))
         {
             error("Cannot create CoW region at %#lx", Address);
             return (void *)-EPERM;
         }
         debug("unmapping %#lx-%#lx", Address, (uintptr_t)Address + Length);
         vmm.Unmap(Address, Length);
         debug("mapping cow at %#lx-%#lx", Address, (uintptr_t)Address + Length);
         vmm.Map(Address, nullptr, Length, PTFlag::CoW);
         debug("CoW region created at range %#lx-%#lx for pt %#lx",
               Address, (uintptr_t)Address + Length, this->Table);
         SharedRegion sr{
             .Address = Address,
             .Read = Read,
             .Write = Write,
             .Exec = Exec,
             .Fixed = Fixed,
             .Shared = Shared,
             .Length = Length,
             .ReferenceCount = 0,
         };
         SharedRegions.push_back(sr);
         debug("CoW region created at %#lx for pt %#lx",
               Address, this->Table);
         return Address;
     }
References Address, Memory::VirtualMemoryArea::SharedRegion::Address, Memory::Virtual::Check(), Memory::CoW, debug, EPERM, error, APIC::Fixed, func(), Memory::KRsv, Length, Memory::Virtual::Map(), Read, RequestPages(), SharedRegions, Table, TO_PAGES, Memory::Virtual::Unmap(), and Write.
Referenced by Fork(), and linux_mmap().
DetachAddress()
void Memory::VirtualMemoryArea::DetachAddress (void * Address)
Definition at line 105 of file vma.cpp.
     {
         func("%#lx", Address);
         SmartLock(MgrLock);
         forItr(itr, AllocatedPagesList)
         {
             if (itr->Address == Address)
             {
                 if (itr->Protected)
                 {
                     error("Address %#lx is protected", Address);
                     return;
                 }
                 AllocatedPagesList.erase(itr);
                 return;
             }
         }
     }
References Address, AllocatedPagesList, error, and func().
Fork()
void Memory::VirtualMemoryArea::Fork (VirtualMemoryArea * Parent)
Definition at line 272 of file vma.cpp.
     {
         func("%#lx", Parent);
         assert(Parent);
         debug("parent apl:%d sr:%d [P:%#lx C:%#lx]",
               Parent->AllocatedPagesList.size(), Parent->SharedRegions.size(),
               Parent->Table, this->Table);
         debug("ctx: this: %#lx parent: %#lx", this, Parent);
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         foreach (auto &ap in Parent->AllocatedPagesList)
         {
             if (ap.Protected)
             {
                 debug("Protected %#lx-%#lx", ap.Address,
                       (uintptr_t)ap.Address + (ap.PageCount * PAGE_SIZE));
                 continue; /* We don't want to modify these pages. */
             }
             MgrLock.Unlock();
             void *Address = this->RequestPages(ap.PageCount);
             MgrLock.Lock(__FUNCTION__);
             if (Address == nullptr)
                 return;
             memcpy(Address, ap.Address, FROM_PAGES(ap.PageCount));
             for (size_t i = 0; i < ap.PageCount; i++)
             {
                 void *AddressToMap = (void *)((uintptr_t)ap.Address + (i * PAGE_SIZE));
                 void *RealAddress = (void *)((uintptr_t)Address + (i * PAGE_SIZE));
 #if defined(a86)
                 PageTableEntry *pte = vmm.GetPTE(AddressToMap);
                 uintptr_t Flags = 0;
                 Flags |= pte->Present ? (uintptr_t)PTFlag::P : 0;
                 Flags |= pte->ReadWrite ? (uintptr_t)PTFlag::RW : 0;
                 Flags |= pte->UserSupervisor ? (uintptr_t)PTFlag::US : 0;
                 Flags |= pte->CopyOnWrite ? (uintptr_t)PTFlag::CoW : 0;
                 Flags |= pte->KernelReserve ? (uintptr_t)PTFlag::KRsv : 0;
                 debug("Mapping %#lx to %#lx (flags %s/%s/%s/%s/%s)",
                       RealAddress, AddressToMap,
                       Flags & PTFlag::P ? "P" : "-",
                       Flags & PTFlag::RW ? "RW" : "-",
                       Flags & PTFlag::US ? "US" : "-",
                       Flags & PTFlag::CoW ? "CoW" : "-",
                       Flags & PTFlag::KRsv ? "KRsv" : "-");
                 MgrLock.Unlock();
                 this->Map(AddressToMap, RealAddress, PAGE_SIZE, Flags);
                 MgrLock.Lock(__FUNCTION__);
 #else
 #error "Not implemented"
 #endif
             }
             debug("Forked %#lx-%#lx", ap.Address,
                   (uintptr_t)ap.Address + (ap.PageCount * PAGE_SIZE));
         }
         foreach (auto &sr in Parent->SharedRegions)
         {
             MgrLock.Unlock();
             void *Address = this->CreateCoWRegion(sr.Address, sr.Length,
                                                   sr.Read, sr.Write, sr.Exec,
                                                   sr.Fixed, sr.Shared);
             MgrLock.Lock(__FUNCTION__);
             if (Address == nullptr)
                 return;
             memcpy(Address, sr.Address, sr.Length);
             debug("Forked CoW region %#lx-%#lx", sr.Address,
                   (uintptr_t)sr.Address + sr.Length);
         }
     }
References Address, AllocatedPagesList, assert, Memory::CoW, CreateCoWRegion(), debug, Flags, FROM_PAGES, func(), i, Memory::KRsv, Map(), memcpy, Memory::P, PAGE_SIZE, RequestPages(), Memory::RW, SharedRegions, Table, and Memory::US.
Referenced by linux_fork().
FreeAllPages()
void Memory::VirtualMemoryArea::FreeAllPages ()
Definition at line 257 of file vma.cpp.
     {
         SmartLock(MgrLock);
         foreach (auto ap in AllocatedPagesList)
         {
             KernelAllocator.FreePages(ap.Address, ap.PageCount);
             Virtual vmm(this->Table);
             for (size_t i = 0; i < ap.PageCount; i++)
                 vmm.Remap((void *)((uintptr_t)ap.Address + (i * PAGE_SIZE)),
                           (void *)((uintptr_t)ap.Address + (i * PAGE_SIZE)),
                           PTFlag::RW);
         }
         AllocatedPagesList.clear();
     }
References AllocatedPagesList, i, KernelAllocator, PAGE_SIZE, Memory::Virtual::Remap(), Memory::RW, and Table.
Referenced by Driver::Manager::LoadAllDrivers().
FreePages()
void Memory::VirtualMemoryArea::FreePages (void * Address, size_t Count)
TODO: Advanced checks. Allow if the page count is less than the requested one. This will allow the user to free only a part of the allocated pages.
But this will be in a separate function because we need to specify if we want to free from the start or from the end and return the new address.
Definition at line 62 of file vma.cpp.
     {
         func("%#lx, %lld", Address, Count);
         SmartLock(MgrLock);
         forItr(itr, AllocatedPagesList)
         {
             if (itr->Address != Address)
                 continue;
             if (itr->Protected)
             {
                 error("Address %#lx is protected", Address);
                 return;
             }
             if (itr->PageCount != Count)
             {
                 error("Page count mismatch! (Allocated: %lld, Requested: %lld)",
                       itr->PageCount, Count);
                 return;
             }
             Virtual vmm(this->Table);
             for (size_t i = 0; i < Count; i++)
             {
                 void *AddressToMap = (void *)((uintptr_t)Address + (i * PAGE_SIZE));
                 vmm.Remap(AddressToMap, AddressToMap, PTFlag::RW);
             }
             KernelAllocator.FreePages(Address, Count);
             AllocatedPagesList.erase(itr);
             debug("%#lx -{%#lx, %lld}", this, Address, Count);
             return;
         }
     }
References Address, AllocatedPagesList, debug, error, func(), i, KernelAllocator, PAGE_SIZE, Memory::Virtual::Remap(), Memory::RW, and Table.
Referenced by Memory::ProgramBreak::brk(), linux_munmap(), and NetworkInterfaceManager::NetworkInterface::Send().
GetAllocatedMemorySize()
uint64_t Memory::VirtualMemoryArea::GetAllocatedMemorySize ()
Definition at line 28 of file vma.cpp.
     {
         SmartLock(MgrLock);
         uint64_t Size = 0;
         foreach (auto ap in AllocatedPagesList)
             Size += ap.PageCount;
         return FROM_PAGES(Size);
     }
References AllocatedPagesList, FROM_PAGES, and Driver::Size.
Referenced by cmd_modinfo(), Tasking::TCB::GetSize(), and Tasking::PCB::GetSize().
HandleCoW()
bool Memory::VirtualMemoryArea::HandleCoW (uintptr_t PFA)
Definition at line 194 of file vma.cpp.
     {
         func("%#lx", PFA);
         Virtual vmm(this->Table);
         PageTableEntry *pte = vmm.GetPTE((void *)PFA);
         debug("ctx: %#lx", this);
         if (!pte)
         {
             /* Unmapped page */
             debug("PTE is null!");
             return false;
         }
         if (!pte->CopyOnWrite)
         {
             debug("PFA %#lx is not CoW (pt %#lx) (flags %#lx)",
                   PFA, this->Table, pte->raw);
             return false;
         }
         foreach (auto sr in SharedRegions)
         {
             uintptr_t Start = (uintptr_t)sr.Address;
             uintptr_t End = (uintptr_t)sr.Address + sr.Length;
             debug("Start: %#lx, End: %#lx (PFA: %#lx)",
                   Start, End, PFA);
             if (PFA >= Start && PFA < End)
             {
                 if (sr.Shared)
                 {
                     fixme("Shared CoW");
                     return false;
                 }
                 void *pAddr = this->RequestPages(1);
                 if (pAddr == nullptr)
                     return false;
                 memset(pAddr, 0, PAGE_SIZE);
                 assert(pte->Present == true);
                 pte->ReadWrite = sr.Write;
                 pte->UserSupervisor = sr.Read;
                 pte->ExecuteDisable = sr.Exec;
                 pte->CopyOnWrite = false;
                 debug("PFA %#lx is CoW (pt %#lx, flags %#lx)",
                       PFA, this->Table, pte->raw);
 #if defined(a64)
                 CPU::x64::invlpg((void *)PFA);
 #elif defined(a32)
                 CPU::x32::invlpg((void *)PFA);
 #endif
                 return true;
             }
         }
         debug("%#lx not found in CoW regions", PFA);
         return false;
     }
References assert, debug, fixme, func(), Memory::Virtual::GetPTE(), CPU::x32::invlpg(), CPU::x64::invlpg(), memset, PAGE_SIZE, Memory::PageTableEntry::raw, RequestPages(), SharedRegions, and Table.
Referenced by UserModeExceptionHandler().
Map()
int Memory::VirtualMemoryArea::Map (void * VirtualAddress, void * PhysicalAddress, size_t Length, uint64_t Flags)
Definition at line 349 of file vma.cpp.
     {
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         uintptr_t intVirtualAddress = (uintptr_t)VirtualAddress;
         uintptr_t intPhysicalAddress = (uintptr_t)PhysicalAddress;
         for (uintptr_t va = intVirtualAddress;
              va < intVirtualAddress + Length; va += PAGE_SIZE)
         {
             if (vmm.Check(VirtualAddress, PTFlag::KRsv))
             {
                 error("Virtual address %#lx is reserved", VirtualAddress);
                 return -EPERM;
             }
         }
         for (uintptr_t va = intPhysicalAddress;
              va < intPhysicalAddress + Length; va += PAGE_SIZE)
         {
             if (vmm.Check(PhysicalAddress, PTFlag::KRsv))
             {
                 error("Physical address %#lx is reserved", PhysicalAddress);
                 return -EPERM;
             }
         }
         vmm.Map(VirtualAddress, PhysicalAddress, Length, Flags);
         debug("Mapped %#lx-%#lx to %#lx-%#lx (flags %#lx)",
               VirtualAddress, intVirtualAddress + Length,
               PhysicalAddress, intPhysicalAddress + Length,
               Flags);
         return 0;
     }
References Memory::Virtual::Check(), debug, EPERM, error, Flags, Memory::KRsv, Length, Memory::Virtual::Map(), PAGE_SIZE, PhysicalAddress, and Table.
Referenced by Memory::StackGuard::Expand(), Fork(), linux_mmap(), and Memory::StackGuard::StackGuard().
NewLock()
Memory::VirtualMemoryArea::NewLock (MgrLock) private
Remap()
int Memory::VirtualMemoryArea::Remap (void * VirtualAddress, void * PhysicalAddress, uint64_t Flags)
Definition at line 386 of file vma.cpp.
     {
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         if (vmm.Check(VirtualAddress, PTFlag::KRsv))
         {
             error("Virtual address %#lx is reserved", VirtualAddress);
             return -EPERM;
         }
         if (vmm.Check(PhysicalAddress, PTFlag::KRsv))
         {
             error("Physical address %#lx is reserved", PhysicalAddress);
             return -EPERM;
         }
         vmm.Remap(VirtualAddress, PhysicalAddress, Flags);
         debug("Remapped %#lx to %#lx (flags %#lx)",
               VirtualAddress, PhysicalAddress, Flags);
         return 0;
     }
References Memory::Virtual::Check(), debug, EPERM, error, Flags, Memory::KRsv, PhysicalAddress, Memory::Virtual::Remap(), and Table.
Referenced by Memory::StackGuard::Fork().
RequestPages()
void * Memory::VirtualMemoryArea::RequestPages (size_t Count, bool User = false, bool Protect = false)
Definition at line 37 of file vma.cpp.
     {
         func("%lld, %s, %s", Count,
              User ? "true" : "false",
              Protect ? "true" : "false");
         void *Address = KernelAllocator.RequestPages(Count);
         memset(Address, 0, Count * PAGE_SIZE);
         int Flags = PTFlag::RW;
         if (User)
             Flags |= PTFlag::US;
         if (Protect)
             Flags |= PTFlag::KRsv;
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         vmm.Map(Address, Address, FROM_PAGES(Count), Flags);
         AllocatedPagesList.push_back({Address, Count, Protect});
         debug("%#lx +{%#lx, %lld}", this, Address, Count);
         return Address;
     }
References Address, AllocatedPagesList, debug, Flags, FROM_PAGES, func(), KernelAllocator, Memory::KRsv, Memory::Virtual::Map(), memset, PAGE_SIZE, Memory::RW, Table, Memory::US, and Tasking::User.
Referenced by Memory::ProgramBreak::brk(), CreateCoWRegion(), Execute::ELFObject::ELFObject(), Memory::StackGuard::Expand(), NetworkInterfaceManager::NetworkInterface::FetchNetworkCards(), for(), Memory::StackGuard::Fork(), Fork(), Execute::ELFObject::GenerateAuxiliaryVector_x86_64(), v0::GetPCIDevices(), HandleCoW(), if(), linux_mmap(), Driver::Manager::LoadDriverFile(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), NetworkInterfaceManager::NetworkInterface::Send(), Tasking::TCB::SetupThreadLocalStorage(), and Memory::StackGuard::StackGuard().
Reserve()
void Memory::VirtualMemoryArea::Reserve (void * Address, size_t Length)
Unmap()
int Memory::VirtualMemoryArea::Unmap (void * VirtualAddress, size_t Length)
Definition at line 409 of file vma.cpp.
     {
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         uintptr_t intVirtualAddress = (uintptr_t)VirtualAddress;
         for (uintptr_t va = intVirtualAddress;
              va < intVirtualAddress + Length; va += PAGE_SIZE)
         {
             if (vmm.Check(VirtualAddress, PTFlag::KRsv))
             {
                 error("Virtual address %#lx is reserved", VirtualAddress);
                 return -EPERM;
             }
         }
         vmm.Unmap(VirtualAddress, Length);
         debug("Unmapped %#lx-%#lx", VirtualAddress, intVirtualAddress + Length);
         return 0;
     }
References Memory::Virtual::Check(), debug, EPERM, error, Memory::KRsv, Length, PAGE_SIZE, Table, and Memory::Virtual::Unmap().
Unreserve()
void Memory::VirtualMemoryArea::Unreserve (void * Address, size_t Length)
UserCheck()
template<typename T > int Memory::VirtualMemoryArea::UserCheck (T Address, size_t Length = 0) inline
Definition at line 109 of file vma.hpp.
         {
             if (Length == 0)
                 Length = sizeof(T);
             return __UserCheck((void *)Address, Length);
         }
References __UserCheck(), Address, Length, and T.
Referenced by for(), linux_arch_prctl(), linux_sigaction(), and linux_sigprocmask().
UserCheckAndGetAddress()
template<typename T > T Memory::VirtualMemoryArea::UserCheckAndGetAddress (T Address, size_t Length = 0) inline
Definition at line 97 of file vma.hpp.
         {
             if (Length == 0)
                 Length = sizeof(T);
             void *PhysAddr = __UserCheckAndGetAddress((void *)Address, Length);
             if (PhysAddr == nullptr)
                 return {};
             return T(PhysAddr);
         }
References __UserCheckAndGetAddress(), Address, Length, and T.
Referenced by linux_access(), linux_chdir(), linux_clock_gettime(), linux_clock_nanosleep(), linux_fstat(), linux_getcwd(), linux_getrandom(), linux_getrusage(), linux_ioctl(), linux_lstat(), linux_mkdir(), linux_nanosleep(), linux_newfstatat(), linux_open(), linux_openat(), linux_pipe(), linux_pipe2(), linux_pread64(), linux_prlimit64(), linux_pwrite64(), linux_read(), linux_readlink(), linux_readv(), linux_sched_getaffinity(), linux_sched_setaffinity(), linux_setitimer(), linux_stat(), linux_uname(), linux_wait4(), linux_write(), and linux_writev().
Field Documentation
AllocatedPagesList
std::list<AllocatedPages> Memory::VirtualMemoryArea::AllocatedPagesList private
Definition at line 55 of file vma.hpp.
Referenced by DetachAddress(), Fork(), FreeAllPages(), FreePages(), GetAllocatedMemorySize(), RequestPages(), and ~VirtualMemoryArea().
PageBitmap
Bitmap Memory::VirtualMemoryArea::PageBitmap private
Definition at line 53 of file vma.hpp.
SharedRegions
std::list<SharedRegion> Memory::VirtualMemoryArea::SharedRegions private
Definition at line 56 of file vma.hpp.
Referenced by CreateCoWRegion(), Fork(), and HandleCoW().
Table
PageTable* Memory::VirtualMemoryArea::Table = nullptr
Definition at line 59 of file vma.hpp.
Referenced by __UserCheck(), __UserCheckAndGetAddress(), CreateCoWRegion(), Fork(), FreeAllPages(), FreePages(), HandleCoW(), linux_fork(), Map(), Remap(), RequestPages(), Unmap(), and VirtualMemoryArea().
The documentation for this class was generated from the following files:
Kernel/include/memory/vma.hpp
Kernel/core/memory/vma.cpp