Fennix Userspace: Userspace/mlibc/options/glibc/generic/getopt-stubs.cpp File Reference
getopt-stubs.cpp File Reference
#include <assert.h>
#include <bits/ensure.h>
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <frg/optional.hpp>
#include <mlibc/debug.hpp>
Namespaces
anonymous_namespace{getopt-stubs.cpp}
Enumerations
enum anonymous_namespace{getopt-stubs.cpp}::GetoptMode { anonymous_namespace{getopt-stubs.cpp}::Short , anonymous_namespace{getopt-stubs.cpp}::Long , anonymous_namespace{getopt-stubs.cpp}::LongOnly }
Functions
int anonymous_namespace{getopt-stubs.cpp}::getopt_common (int argc, char *const argv[], const char *optstring, const struct option *longopts, int *longindex, enum GetoptMode mode)
int getopt_long (int argc, char *const argv[], const char *optstring, const struct option *longopts, int *longindex)
int getopt_long_only (int argc, char *const argv[], const char *optstring, const struct option *longopts, int *longindex)
Variables
char * optarg
int optind = 1
int opterr = 1
int optopt
int anonymous_namespace{getopt-stubs.cpp}::__optpos = 1
Function Documentation
getopt_long()
int getopt_long (int argc, char *const argv[], const char * optstring, const struct option * longopts, int * longindex)
Definition at line 245 of file getopt-stubs.cpp.
{
     return getopt_common(argc, argv, optstring, longopts, longindex, GetoptMode::Long);
 }
References anonymous_namespace{getopt-stubs.cpp}::getopt_common(), and anonymous_namespace{getopt-stubs.cpp}::Long.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), and test7().
getopt_long_only()
int getopt_long_only (int argc, char *const argv[], const char * optstring, const struct option * longopts, int * longindex)
Definition at line 250 of file getopt-stubs.cpp.
{
     return getopt_common(argc, argv, optstring, longopts, longindex, GetoptMode::LongOnly);
 }
References anonymous_namespace{getopt-stubs.cpp}::getopt_common(), and anonymous_namespace{getopt-stubs.cpp}::LongOnly.
Referenced by test8().
Variable Documentation
optarg
char* optarg
Definition at line 11 of file getopt-stubs.cpp.
Referenced by getopt(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), test1(), test3(), test4(), and test6().
opterr
int opterr = 1
Definition at line 13 of file getopt-stubs.cpp.
Referenced by anonymous_namespace{getopt-stubs.cpp}::getopt_common().
optind
int optind = 1
Definition at line 12 of file getopt-stubs.cpp.
Referenced by getopt(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), test1(), test2(), test3(), test4(), test5(), test6(), test7(), and test8().
optopt
int optopt
Definition at line 14 of file getopt-stubs.cpp.
Referenced by anonymous_namespace{getopt-stubs.cpp}::getopt_common(), test2(), and test8().