Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/m_bbox.c File Reference
m_bbox.c File Reference
#include "m_bbox.h"
Functions
void M_ClearBox (fixed_t *box)
void M_AddToBox (fixed_t *box, fixed_t x, fixed_t y)
Function Documentation
M_AddToBox()
void M_AddToBox (fixed_t * box, fixed_t x, fixed_t y)
Definition at line 36 of file m_bbox.c.
 {
     if (x<box[BOXLEFT])
     box[BOXLEFT] = x;
     else if (x>box[BOXRIGHT])
     box[BOXRIGHT] = x;
     if (y<box[BOXBOTTOM])
     box[BOXBOTTOM] = y;
     else if (y>box[BOXTOP])
     box[BOXTOP] = y;
 }
References BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, x, and y.
Referenced by P_GroupLines(), and V_MarkRect().
M_ClearBox()
void M_ClearBox (fixed_t * box)
Definition at line 29 of file m_bbox.c.
 {
     box[BOXTOP] = box[BOXRIGHT] = INT_MIN;
     box[BOXBOTTOM] = box[BOXLEFT] = INT_MAX;
 }
References BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, INT_MAX, and INT_MIN.
Referenced by P_GroupLines().