Fennix: AdvancedTechnologyAttachment Namespace Reference
AdvancedTechnologyAttachment Namespace Reference
Functions
bool IsATAPresent ()
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *Registers)
Variables
KernelAPI KAPI
Function Documentation
CallbackHandler()
int AdvancedTechnologyAttachment::CallbackHandler (KernelCallback * Data)
Definition at line 58 of file AdvancedTechnologyAttachment.cpp.
     {
         switch (Data->Reason)
         {
         case AcknowledgeReason:
         {
             debug("Kernel acknowledged the driver.");
             break;
         }
         case ConfigurationReason:
         {
             debug("Module received configuration data.");
             break;
         }
         case QueryReason:
         {
             break;
         }
         case SendReason:
         case ReceiveReason:
         {
             break;
         }
         case StopReason:
         {
             // TODO: Stop the driver.
             debug("Module stopped.");
             break;
         }
         default:
         {
             warn("Unknown reason.");
             break;
         }
         }
         return OK;
     }
References AcknowledgeReason, ConfigurationReason, Data, debug, OK, QueryReason, ReceiveReason, SendReason, StopReason, and warn.
DriverEntry()
int AdvancedTechnologyAttachment::DriverEntry (void * Data)
Definition at line 43 of file AdvancedTechnologyAttachment.cpp.
     {
         if (!Data)
             return INVALID_KERNEL_API;
         KAPI = *(KernelAPI *)Data;
         if (KAPI.Version.Major < 0 || KAPI.Version.Minor < 0 || KAPI.Version.Patch < 0)
             return KERNEL_API_VERSION_NOT_SUPPORTED;
         if (!IsATAPresent())
             return NOT_AVAILABLE;
         trace("ATA device found.");
         return NOT_IMPLEMENTED;
     }
References Data, INVALID_KERNEL_API, IsATAPresent(), KAPI, KERNEL_API_VERSION_NOT_SUPPORTED, KernelAPI::KAPIVersion::Major, KernelAPI::KAPIVersion::Minor, NOT_AVAILABLE, NOT_IMPLEMENTED, KernelAPI::KAPIVersion::Patch, trace, and KernelAPI::Version.
Referenced by StartATA().
InterruptCallback()
int AdvancedTechnologyAttachment::InterruptCallback (CPURegisters * Registers)
Definition at line 96 of file AdvancedTechnologyAttachment.cpp.
     {
         if (Registers->InterruptNumber == 0xE)
         {
             fixme("IRQ14");
         }
         else if (Registers->InterruptNumber == 0xF)
         {
             fixme("IRQ15");
         }
         return OK;
     }
References fixme, and OK.
IsATAPresent()
bool AdvancedTechnologyAttachment::IsATAPresent ()
Definition at line 31 of file AdvancedTechnologyAttachment.cpp.
     {
         outb(0x1F0 + 2, 0);
         outb(0x1F0 + 3, 0);
         outb(0x1F0 + 4, 0);
         outb(0x1F0 + 5, 0);
         outb(0x1F0 + 7, 0xEC);
         if (inb(0x1F0 + 7) == 0 || inb(0x1F0 + 1) != 0)
             return false;
         return true;
     }
References inb(), and outb().
Referenced by DriverEntry().
Variable Documentation
KAPI
KernelAPI AdvancedTechnologyAttachment::KAPI
Definition at line 29 of file AdvancedTechnologyAttachment.cpp.
Referenced by DriverEntry().