Fennix: Memory::KernelStackManager Class Reference
Memory::KernelStackManager Class Reference
#include <kstack.hpp>
Data Structures
struct StackAllocation
Public Member Functions
StackAllocation DetailedAllocate (size_t Size)
void * Allocate (size_t Size)
void Free (void *Address)
KernelStackManager ()
~KernelStackManager ()
Private Member Functions
NewLock (StackLock)
Private Attributes
std::list< StackAllocation > AllocatedStacks
size_t TotalSize = 0
uintptr_t CurrentStackTop = KERNEL_STACK_END
Detailed Description
Definition at line 25 of file kstack.hpp.
Data Structure Documentation
Memory::KernelStackManager::StackAllocation
struct Memory::KernelStackManager::StackAllocation
Definition at line 28 of file kstack.hpp.
Data Fields
void * PhysicalAddress
size_t Size
void * VirtualAddress
Constructor & Destructor Documentation
KernelStackManager()
Memory::KernelStackManager::KernelStackManager ()
Definition at line 73 of file kstack.cpp.
 {}
~KernelStackManager()
Memory::KernelStackManager::~KernelStackManager ()
Definition at line 74 of file kstack.cpp.
 {}
Member Function Documentation
Allocate()
void * Memory::KernelStackManager::Allocate (size_t Size)
Allocate a new stack
Parameters
Size Size in bytes to allocate
Returns
Pointer to the BASE of the stack
Definition at line 46 of file kstack.cpp.
     {
         return this->DetailedAllocate(Size).VirtualAddress;
     }
References DetailedAllocate(), and Memory::KernelStackManager::StackAllocation::VirtualAddress.
Referenced by GlobalDescriptorTable::Init(), and Interrupts::Initialize().
DetailedAllocate()
KernelStackManager::StackAllocation Memory::KernelStackManager::DetailedAllocate (size_t Size)
Allocate a new stack with detailed information
Parameters
Size Size in bytes to allocate
Returns
{PhysicalAddress, VirtualAddress, Size}
Definition at line 24 of file kstack.cpp.
     {
         SmartLock(StackLock);
         Size += 0x10;
         size_t pagesNeeded = TO_PAGES(Size);
         size_t stackSize = pagesNeeded * PAGE_SIZE;
         assert((CurrentStackTop - stackSize) > KERNEL_STACK_BASE);
         void *physicalMemory = KernelAllocator.RequestPages(pagesNeeded);
         void *virtualAddress = (void *)(CurrentStackTop - stackSize);
         Memory::Virtual vmm(KernelPageTable);
         vmm.Map(virtualAddress, physicalMemory, stackSize, Memory::RW | Memory::G);
         AllocatedStacks.push_back({physicalMemory, virtualAddress, stackSize});
         CurrentStackTop -= stackSize;
         TotalSize += stackSize;
         return {physicalMemory, virtualAddress, stackSize};
     }
References AllocatedStacks, assert, CurrentStackTop, Memory::G, KernelAllocator, KernelPageTable, Memory::Virtual::Map(), PAGE_SIZE, Memory::RW, Driver::Size, TO_PAGES, and TotalSize.
Referenced by Allocate(), and Memory::StackGuard::StackGuard().
Free()
void Memory::KernelStackManager::Free (void * Address)
Free a previously allocated stack
Parameters
Address Virtual Address
Definition at line 51 of file kstack.cpp.
     {
         SmartLock(StackLock);
         auto it = std::find_if(AllocatedStacks.begin(), AllocatedStacks.end(),
                                [Address](const StackAllocation &stack)
{
                                    return stack.VirtualAddress == Address;
                                });
         if (it == AllocatedStacks.end())
             return;
         size_t pagesToFree = TO_PAGES(it->Size);
         Memory::Virtual vmm(KernelPageTable);
         vmm.Unmap(Address, it->Size);
         KernelAllocator.FreePages(it->PhysicalAddress, pagesToFree);
         TotalSize -= it->Size;
         AllocatedStacks.erase(it);
     }
References Address, AllocatedStacks, it, KernelAllocator, KernelPageTable, TO_PAGES, TotalSize, and Memory::Virtual::Unmap().
Referenced by Memory::StackGuard::~StackGuard().
NewLock()
Memory::KernelStackManager::NewLock (StackLock) private
Field Documentation
AllocatedStacks
std::list<StackAllocation> Memory::KernelStackManager::AllocatedStacks private
Definition at line 37 of file kstack.hpp.
Referenced by DetailedAllocate(), and Free().
CurrentStackTop
uintptr_t Memory::KernelStackManager::CurrentStackTop = KERNEL_STACK_END private
Definition at line 39 of file kstack.hpp.
Referenced by DetailedAllocate().
TotalSize
size_t Memory::KernelStackManager::TotalSize = 0 private
Definition at line 38 of file kstack.hpp.
Referenced by DetailedAllocate(), and Free().
The documentation for this class was generated from the following files:
Kernel/include/memory/kstack.hpp
Kernel/core/memory/kstack.cpp