Fennix: Userspace/apps/base/busybox/include/inet_common.h File Reference
inet_common.h File Reference
Functions
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN int INET_resolve (const char *name, struct sockaddr_in *s_in, int hostfirst) FAST_FUNC
int INET6_resolve (const char *name, struct sockaddr_in6 *sin6) FAST_FUNC
char * INET_rresolve (struct sockaddr_in *s_in, int numeric, uint32_t netmask) FAST_FUNC
char * INET6_rresolve (struct sockaddr_in6 *sin6, int numeric) FAST_FUNC
Function Documentation
INET6_resolve()
int INET6_resolve (const char * name, struct sockaddr_in6 * sin6)
INET6_rresolve()
char* INET6_rresolve (struct sockaddr_in6 * sin6, int numeric)
INET_resolve()
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN int INET_resolve (const char * name, struct sockaddr_in * s_in, int hostfirst)
Definition at line 19 of file inet_common.c.
 {
     struct hostent *hp;
 #if ENABLE_FEATURE_ETC_NETWORKS
     struct netent *np;
 #endif
     /* Grmpf. -FvK */
     s_in->sin_family = AF_INET;
     s_in->sin_port = 0;
     /* Default is special, meaning 0.0.0.0. */
     if (strcmp(name, "default") == 0) {
         s_in->sin_addr.s_addr = INADDR_ANY;
         return 1;
     }
     /* Look to see if it's a dotted quad. */
     if (inet_aton(name, &s_in->sin_addr)) {
         return 0;
     }
     /* If we expect this to be a hostname, try hostname database first */
     if (hostfirst) {
         dbg("gethostbyname(%s)", name);
         hp = gethostbyname(name);
         if (hp) {
             memcpy(&s_in->sin_addr, hp->h_addr_list[0],
                 sizeof(struct in_addr));
             return 0;
         }
     }
 #if ENABLE_FEATURE_ETC_NETWORKS
     /* Try the NETWORKS database to see if this is a known network. */
     dbg("getnetbyname(%s)", name);
     np = getnetbyname(name);
     if (np) {
         s_in->sin_addr.s_addr = htonl(np->n_net);
         return 1;
     }
 #endif
     if (hostfirst) {
         /* Don't try again */
         return -1;
     }
 #ifdef DEBUG
     res_init();
     _res.options |= RES_DEBUG;
 #endif
     dbg("gethostbyname(%s)", name);
     hp = gethostbyname(name);
     if (!hp) {
         return -1;
     }
     memcpy(&s_in->sin_addr, hp->h_addr_list[0], sizeof(struct in_addr));
     return 0;
 }
References _res, AF_INET, dbg, gethostbyname(), getnetbyname(), hostent::h_addr_list, htonl(), INADDR_ANY, inet_aton(), memcpy, netent::n_net, RES_DEBUG, res_init(), in_addr::s_addr, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, and strcmp.
Referenced by INET_setroute().
INET_rresolve()
char* INET_rresolve (struct sockaddr_in * s_in, int numeric, uint32_t netmask)
Definition at line 80 of file inet_common.c.
 {
     /* addr-to-name cache */
     struct addr {
         struct addr *next;
         uint32_t nip;
         smallint is_host;
         char name[1];
     };
     static struct addr *cache = NULL;
     struct addr *pn;
     char *name;
     uint32_t nip;
     smallint is_host;
     if (s_in->sin_family != AF_INET) {
         dbg("rresolve: unsupported address family %d!", s_in->sin_family);
         errno = EAFNOSUPPORT;
         return NULL;
     }
     nip = s_in->sin_addr.s_addr;
     dbg("rresolve: %08x mask:%08x num:%08x", (unsigned)nip, netmask, numeric);
     if (numeric & 0x0FFF)
         return xmalloc_sockaddr2dotted_noport((void*)s_in);
     if (nip == INADDR_ANY) {
         if (numeric & 0x8000)
             return xstrdup("default");
         return xstrdup("*");
     }
     is_host = ((nip & (~netmask)) != 0 || (numeric & 0x4000));
     pn = cache;
     while (pn) {
         if (pn->nip == nip && pn->is_host == is_host) {
             dbg("rresolve: found %s %08x in cache",
                 (is_host ? "host" : "net"), (unsigned)nip);
             return xstrdup(pn->name);
         }
         pn = pn->next;
     }
     name = NULL;
     if (is_host) {
         dbg("sockaddr2host_noport(%08x)", (unsigned)nip);
         name = xmalloc_sockaddr2host_noport((void*)s_in);
     }
 #if ENABLE_FEATURE_ETC_NETWORKS
     else {
         struct netent *np;
         dbg("getnetbyaddr(%08x)", (unsigned)ntohl(nip));
         np = getnetbyaddr(ntohl(nip), AF_INET);
         if (np)
             name = xstrdup(np->n_name);
     }
 #endif
     if (!name)
         name = xmalloc_sockaddr2dotted_noport((void*)s_in);
     pn = xmalloc(sizeof(*pn) + strlen(name)); /* no '+ 1', it's already accounted for */
     pn->next = cache;
     pn->nip = nip;
     pn->is_host = is_host;
     strcpy(pn->name, name);
     cache = pn;
     return name;
 }
References addr, AF_INET, dbg, EAFNOSUPPORT, errno, getnetbyaddr(), INADDR_ANY, netent::n_name, netmask, next, ntohl(), NULL, in_addr::s_addr, sockaddr_in::sin_addr, sockaddr_in::sin_family, strcpy, strlen(), xmalloc, xmalloc_sockaddr2dotted_noport(), xmalloc_sockaddr2host_noport(), and xstrdup().
Referenced by bb_displayroutes(), and INET_sprint().