Fennix Userspace: Userspace/musl/src/ctype/iswblank.c File Reference
iswblank.c File Reference
#include <wctype.h>
#include <ctype.h>
Functions
int iswblank (wint_t wc)
int __iswblank_l (wint_t c, locale_t l)
weak_alias (__iswblank_l, iswblank_l)
Function Documentation
__iswblank_l()
int __iswblank_l (wint_t c, locale_t l)
Definition at line 9 of file iswblank.c.
 {
     return iswblank(c);
 }
References c, and iswblank().
iswblank()
int iswblank (wint_t wc)
Definition at line 4 of file iswblank.c.
 {
     return isblank(wc);
 }
References isblank.
Referenced by __iswblank_l(), and iswctype().
weak_alias()
weak_alias (__iswblank_l , iswblank_l)