Fennix Userspace: Userspace/apps/base/bash/lib/tilde/tilde.h File Reference
tilde.h File Reference
Typedefs
typedef char * tilde_hook_func_t(char *)
Functions
char * tilde_expand (const char *)
char * tilde_expand_word (const char *)
char * tilde_find_word (const char *, int, int *)
Variables
tilde_hook_func_t * tilde_expansion_preexpansion_hook
tilde_hook_func_t * tilde_expansion_failure_hook
char ** tilde_additional_prefixes
char ** tilde_additional_suffixes
Typedef Documentation
tilde_hook_func_t
typedef char* tilde_hook_func_t(char *)
Definition at line 30 of file tilde.h.
Function Documentation
tilde_expand()
char* tilde_expand (const char * string)
Definition at line 189 of file tilde.c.
 {
   char *result;
   int result_size, result_index;
   result_index = result_size = 0;
   if (result = strchr (string, '~'))
     result = (char *)xmalloc (result_size = (strlen (string) + 16));
   else
     result = (char *)xmalloc (result_size = (strlen (string) + 1));
   /* Scan through STRING expanding tildes as we come to them. */
   while (1)
     {
       register int start, end;
       char *tilde_word, *expansion;
       int len;
       /* Make START point to the tilde which starts the expansion. */
       start = tilde_find_prefix (string, &len);
       /* Copy the skipped text into the result. */
       if ((result_index + start + 1) > result_size)
     result = (char *)xrealloc (result, 1 + (result_size += (start + 20)));
       strncpy (result + result_index, string, start);
       result_index += start;
       /* Advance STRING to the starting tilde. */
       string += start;
       /* Make END be the index of one after the last character of the
      username. */
       end = tilde_find_suffix (string);
       /* If both START and END are zero, we are all done. */
       if (!start && !end)
     break;
       /* Expand the entire tilde word, and copy it into RESULT. */
       tilde_word = (char *)xmalloc (1 + end);
       strncpy (tilde_word, string, end);
       tilde_word[end] = '\0';
       string += end;
       expansion = tilde_expand_word (tilde_word);
       if (expansion == 0)
     expansion = tilde_word;
       else
     xfree (tilde_word);
       len = strlen (expansion);
 #ifdef __CYGWIN__
       /* Fix for Cygwin to prevent ~user/xxx from expanding to //xxx when
      $HOME for `user' is /.  On cygwin, // denotes a network drive. */
       if (len > 1 || *expansion != '/' || *string != '/')
 #endif
     {
       if ((result_index + len + 1) > result_size)
         result = (char *)xrealloc (result, 1 + (result_size += (len + 20)));
       strcpy (result + result_index, expansion);
       result_index += len;
     }
       xfree (expansion);
     }
   result[result_index] = '\0';
   return (result);
 }
References start(), strchr(), strcpy(), strlen(), strncpy(), tilde_expand_word(), tilde_find_prefix(), tilde_find_suffix(), xfree, xmalloc, and xrealloc.
Referenced by _rl_read_init_file(), append_to_match(), bash_tilde_expand(), print_filename(), rl_filename_completion_function(), and rl_tilde_expand().
tilde_expand_word()
char* tilde_expand_word (const char * filename)
Definition at line 336 of file tilde.c.
 {
   char *dirname, *expansion, *username;
   int user_len;
   struct passwd *user_entry;
   if (filename == 0)
     return ((char *)NULL);
   if (*filename != '~')
     return (savestring (filename));
   /* A leading `~/' or a bare `~' is *always* translated to the value of
      $HOME or the home directory of the current user, regardless of any
      preexpansion hook. */
   if (filename[1] == '\0' || filename[1] == '/')
     {
       /* Prefix $HOME to the rest of the string. */
       expansion = sh_get_env_value ("HOME");
 #if defined (_WIN32)
       if (expansion == 0)
     expansion = sh_get_env_value ("APPDATA");
 #endif
       /* If there is no HOME variable, look up the directory in
      the password database. */
       if (expansion == 0)
     expansion = sh_get_home_dir ();
       return (glue_prefix_and_suffix (expansion, filename, 1));
     }
   username = isolate_tilde_prefix (filename, &user_len);
   if (tilde_expansion_preexpansion_hook)
     {
       expansion = (*tilde_expansion_preexpansion_hook) (username);
       if (expansion)
     {
       dirname = glue_prefix_and_suffix (expansion, filename, user_len);
       xfree (username);
       xfree (expansion);
       return (dirname);
     }
     }
   /* No preexpansion hook, or the preexpansion hook failed.  Look in the
      password database. */
   dirname = (char *)NULL;
 #if defined (HAVE_GETPWNAM)
   user_entry = getpwnam (username);
 #else
   user_entry = 0;
 #endif
   if (user_entry == 0)
     {
       /* If the calling program has a special syntax for expanding tildes,
      and we couldn't find a standard expansion, then let them try. */
       if (tilde_expansion_failure_hook)
     {
       expansion = (*tilde_expansion_failure_hook) (username);
       if (expansion)
         {
           dirname = glue_prefix_and_suffix (expansion, filename, user_len);
           xfree (expansion);
         }
     }
       /* If we don't have a failure hook, or if the failure hook did not
      expand the tilde, return a copy of what we were passed. */
       if (dirname == 0)
     dirname = savestring (filename);
     }
 #if defined (HAVE_GETPWENT)
   else
     dirname = glue_prefix_and_suffix (user_entry->pw_dir, filename, user_len);
 #endif
   xfree (username);
 #if defined (HAVE_GETPWENT)
   endpwent ();
 #endif
   return (dirname);
 }
References dirname, endpwent(), getpwnam(), glue_prefix_and_suffix(), isolate_tilde_prefix(), NULL, passwd::pw_dir, savestring, sh_get_env_value(), sh_get_home_dir(), tilde_expansion_failure_hook, tilde_expansion_preexpansion_hook, and xfree.
Referenced by tilde_expand().
tilde_find_word()
char* tilde_find_word (const char * , int , int *)
Variable Documentation
tilde_additional_prefixes
char** tilde_additional_prefixes extern
Definition at line 112 of file tilde.c.
Referenced by bash_tilde_expand(), tilde_find_prefix(), and tilde_initialize().
tilde_additional_suffixes
char** tilde_additional_suffixes extern
Definition at line 117 of file tilde.c.
Referenced by bash_tilde_expand(), tilde_find_suffix(), and tilde_initialize().
tilde_expansion_failure_hook
tilde_hook_func_t* tilde_expansion_failure_hook extern
Definition at line 107 of file tilde.c.
Referenced by tilde_expand_word().
tilde_expansion_preexpansion_hook
tilde_hook_func_t* tilde_expansion_preexpansion_hook extern
Definition at line 101 of file tilde.c.
Referenced by tilde_expand_word(), and tilde_initialize().