Fennix: Userspace/mlibc/options/ansi/generic/stdio-stubs.cpp File Reference
stdio-stubs.cpp File Reference
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <wchar.h>
#include <ctype.h>
#include <limits.h>
#include <abi-bits/fcntl.h>
#include <bits/ensure.h>
#include <mlibc/lock.hpp>
#include <mlibc/allocator.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/file-io.hpp>
#include <mlibc/ansi-sysdeps.hpp>
#include <frg/mutex.hpp>
#include <frg/expected.hpp>
#include <frg/printf.hpp>
Data Structures
struct PrintfAgent< F >
struct StreamPrinter
struct BufferPrinter
struct LimitedPrinter
struct ResizePrinter
Namespaces
anonymous_namespace{stdio-stubs.cpp}
Enumerations
enum {
anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_CHAR , anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_SHORT , anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_INTMAX , anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_L ,
anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_LL , anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_PTRDIFF , anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_SIZE_T , anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_INT
}
Functions
int remove (const char *filename)
int rename (const char *path, const char *new_path)
int renameat (int olddirfd, const char *old_path, int newdirfd, const char *new_path)
FILE * tmpfile (void)
char * tmpnam (char *)
FILE * freopen (const char *__restrict, const char *__restrict, FILE *__restrict)
void setbuf (FILE *__restrict stream, char *__restrict buffer)
void setlinebuf (FILE *stream)
void setbuffer (FILE *f, char *buf, size_t size)
int fprintf (FILE *__restrict stream, const char *__restrict format,...)
int fscanf (FILE *__restrict stream, const char *__restrict format,...)
int printf (const char *__restrict format,...)
static void store_int (void *dest, unsigned int size, unsigned long long i)
template<typename H >
static int do_scanf (H &handler, const char *fmt, __gnuc_va_list args)
int scanf (const char *__restrict format,...)
int snprintf (char *__restrict buffer, size_t max_size, const char *__restrict format,...)
int sprintf (char *__restrict buffer, const char *__restrict format,...)
int sscanf (const char *__restrict buffer, const char *__restrict format,...)
int vfprintf (FILE *__restrict stream, const char *__restrict format, __gnuc_va_list args)
int vfscanf (FILE *__restrict stream, const char *__restrict format, __gnuc_va_list args)
int vprintf (const char *__restrict format, __gnuc_va_list args)
int vscanf (const char *__restrict, __gnuc_va_list)
int vsnprintf (char *__restrict buffer, size_t max_size, const char *__restrict format, __gnuc_va_list args)
int vsprintf (char *__restrict buffer, const char *__restrict format, __gnuc_va_list args)
int vsscanf (const char *__restrict buffer, const char *__restrict format, __gnuc_va_list args)
int fwprintf (FILE *__restrict, const wchar_t *__restrict,...) MLIBC_STUB_BODY int fwscanf(FILE *__restrict
int const wchar_t MLIBC_STUB_BODY int vfwprintf (FILE *__restrict, const wchar_t *__restrict, __gnuc_va_list) MLIBC_STUB_BODY int vfwscanf(FILE *__restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int swprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict,...) MLIBC_STUB_BODY int swscanf(wchar_t *__restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int vswprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict, __gnuc_va_list) MLIBC_STUB_BODY int vswscanf(wchar_t *__restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int wprintf (const wchar_t *__restrict,...) MLIBC_STUB_BODY int wscanf(const wchar_t *__restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int MLIBC_STUB_BODY int vwprintf (const wchar_t *__restrict, __gnuc_va_list) MLIBC_STUB_BODY int vwscanf(const wchar_t *__restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int MLIBC_STUB_BODY int __gnuc_va_list MLIBC_STUB_BODY int fgetc (FILE *stream)
char * fgets (char *__restrict buffer, size_t max_size, FILE *__restrict stream)
int fputc_unlocked (int c, FILE *stream)
int fputc (int c, FILE *stream)
int fputs_unlocked (const char *__restrict string, FILE *__restrict stream)
int fputs (const char *__restrict string, FILE *__restrict stream)
int getc_unlocked (FILE *stream)
int getc (FILE *stream)
int getchar_unlocked (void)
int getchar (void)
char * gets (char *s)
int putc_unlocked (int c, FILE *stream)
int putc (int c, FILE *stream)
int putchar_unlocked (int c)
int putchar (int c)
int puts (const char *string)
wint_t fgetwc (FILE *) MLIBC_STUB_BODY wchar_t *fgetws(wchar_t *__restrict
wint_t FILE *__restrict MLIBC_STUB_BODY wint_t fputwc (wchar_t, FILE *) MLIBC_STUB_BODY int fputws(const wchar_t *__restrict
wint_t FILE *__restrict MLIBC_STUB_BODY wint_t FILE *__restrict MLIBC_STUB_BODY int fwide (FILE *, int) MLIBC_STUB_BODY wint_t getwc(FILE *) MLIBC_STUB_BODY wint_t getwchar(void) MLIBC_STUB_BODY wint_t putwc(wchar_t
wint_t FILE *__restrict MLIBC_STUB_BODY wint_t FILE *__restrict MLIBC_STUB_BODY int FILE *MLIBC_STUB_BODY wint_t putwchar (wchar_t) MLIBC_STUB_BODY wint_t ungetwc(wint_t
wint_t FILE *__restrict MLIBC_STUB_BODY wint_t FILE *__restrict MLIBC_STUB_BODY int FILE *MLIBC_STUB_BODY wint_t FILE *MLIBC_STUB_BODY size_t fread (void *buffer, size_t size, size_t count, FILE *file_base)
size_t fwrite (const void *buffer, size_t size, size_t count, FILE *file_base)
int fgetpos (FILE *__restrict, fpos_t *__restrict)
int fsetpos (FILE *, const fpos_t *)
void clearerr (FILE *file_base)
int feof (FILE *file_base)
int ferror (FILE *file_base)
void perror (const char *string)
ssize_t getline (char **line, size_t *n, FILE *stream)
ssize_t getdelim (char **line, size_t *n, int delim, FILE *stream)
int asprintf (char **out, const char *format,...)
int vasprintf (char **out, const char *format, __gnuc_va_list args)
void flockfile (FILE *file_base)
void funlockfile (FILE *file_base)
int ftrylockfile (FILE *file_base)
void clearerr_unlocked (FILE *file_base)
int feof_unlocked (FILE *file_base)
int ferror_unlocked (FILE *file_base)
int fgetc_unlocked (FILE *stream)
size_t fread_unlocked (void *buffer, size_t size, size_t count, FILE *file_base)
size_t fwrite_unlocked (const void *buffer, size_t size, size_t count, FILE *file_base)
char * fgets_unlocked (char *__restrict buffer, int max_size, FILE *stream)
Variables
int const wchar_t * __restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int size_t
wint_t int
Function Documentation
asprintf()
int asprintf (char ** out, const char * format, ...)
Definition at line 1061 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vasprintf(out, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, va_end(), va_start(), and vasprintf().
Referenced by main(), and wordexp_return_stringify().
clearerr()
void clearerr (FILE * file_base)
Definition at line 978 of file stdio-stubs.cpp.
{
     file_base->__status_bits = 0;
 }
clearerr_unlocked()
void clearerr_unlocked (FILE * file_base)
Definition at line 1100 of file stdio-stubs.cpp.
{
     file_base->__status_bits = 0;
 }
do_scanf()
template<typename H > static int do_scanf (H & handler, const char * fmt, __gnuc_va_list args) static
Definition at line 343 of file stdio-stubs.cpp.
{
     int match_count = 0;
     for (; *fmt; fmt++) {
         if (isspace(*fmt)) {
             while (isspace(fmt[1])) fmt++;
             while (isspace(handler.look_ahead()))
                     handler.consume();
             continue;
         }
         if (*fmt != '%' || fmt[1] == '%') {
             if (*fmt == '%')
                 fmt++;
             char c = handler.consume();
             if (c != *fmt)
                 break;
             continue;
         }
         void *dest = NULL;
         /* %n$ format */
         if (isdigit(*fmt) && fmt[1] == '$') {
             /* TODO: dest = get_arg_at_pos(args, *fmt -'0'); */
             fmt += 3;
         } else {
             if (fmt[1] != '*') {
                 dest = va_arg(args, void*);
             }
             fmt++;
         }
         int width = 0;
         if (*fmt == '*') {
             fmt++;
         } else if (*fmt == '\'') {
         /* TODO: numeric seperators locale stuff */
              mlibc::infoLogger() << "do_scanf: \' not implemented!" << frg::endlog;
             fmt++;
             continue;
         } else if (*fmt == 'm') {
             /* TODO: allocate buffer for them */
             mlibc::infoLogger() << "do_scanf: m not implemented!" << frg::endlog;
             fmt++;
             continue;
         } else if (*fmt >= '0' && *fmt <= '9') {
             /* read in width specifier */
             width = 0;
             while (*fmt >= '0' && *fmt <= '9') {
                 width = width * 10 + (*fmt - '0');
                 fmt++;
                 continue;
             }
         }
         /* type modifiers */
         unsigned int type = SCANF_TYPE_INT;
         unsigned int base = 10;
         switch (*fmt) {
             case 'h': {
                 if (fmt[1] == 'h') {
                     type = SCANF_TYPE_CHAR;
                     fmt += 2;
                     break;
                 }
                 type = SCANF_TYPE_SHORT;
                 fmt++;
                 break;
             }
             case 'j': {
                 type = SCANF_TYPE_INTMAX;
                 fmt++;
                 break;
             }
             case 'l': {
                 if (fmt[1] == 'l') {
                     type = SCANF_TYPE_LL;
                     fmt += 2;
                     break;
                 }
                 type = SCANF_TYPE_L;
                 fmt++;
                 break;
             }
             case 'L': {
                 type = SCANF_TYPE_LL;
                 fmt++;
                 break;
             }
             case 'q': {
                 type = SCANF_TYPE_LL;
                 fmt++;
                 break;
             }
             case 't': {
                 type = SCANF_TYPE_PTRDIFF;
                 fmt++;
                 break;
             }
              case 'z': {
                 type = SCANF_TYPE_SIZE_T;
                 fmt++;
                 break;
             }
             case '0': {
                 if (fmt[1] == 'x' || fmt[1] == 'X') {
                     base = 16;
                     fmt += 2;
                     break;
                 }
                 base = 8;
                 fmt++;
                 break;
             }
         }
         // Leading whitespace is skipped for most conversions except these.
         if (*fmt != 'c' && *fmt != '[' && *fmt != 'n') {
             while (isspace(handler.look_ahead()))
                 handler.consume();
         }
         switch (*fmt) {
             case 'd':
             case 'u':
                 base = 10;
                 [[fallthrough]];
             case 'i': {
                 unsigned long long res = 0;
                 char c = handler.look_ahead();
                 switch (base) {
                     case 10:
                         while (c >= '0' && c <= '9') {
                             handler.consume();
                             res = res * 10 + (c - '0');
                             c = handler.look_ahead();
                         }
                         break;
                     case 16:
                         if (c == '0') {
                             handler.consume();
                             c = handler.look_ahead();
                             if (c == 'x') {
                                 handler.consume();
                                 c = handler.look_ahead();
                             }
                         }
                         while (true) {
                             if (c >= '0' && c <= '9') {
                                 handler.consume();
                                 res = res * 16 + (c - '0');
                             } else if (c >= 'a' && c <= 'f') {
                                 handler.consume();
                                 res = res * 16 + (c - 'a' + 10);
                             } else if (c >= 'A' && c <= 'F') {
                                 handler.consume();
                                 res = res * 16 + (c - 'A' + 10);
                             } else {
                                 break;
                             }
                             c = handler.look_ahead();
                         }
                         break;
                     case 8:
                         while (c >= '0' && c <= '7') {
                             handler.consume();
                             res = res * 10 + (c - '0');
                             c = handler.look_ahead();
                         }
                         break;
                 }
                 if (dest)
                     store_int(dest, type, res);
                 break;
             }
             case 'o': {
                 unsigned long long res = 0;
                 char c = handler.look_ahead();
                 while (c >= '0' && c <= '7') {
                     handler.consume();
                     res = res * 10 + (c - '0');
                     c = handler.look_ahead();
                 }
                 if (dest)
                     store_int(dest, type, res);
                 break;
             }
             case 'x':
             case 'X': {
                 unsigned long long res = 0;
                 char c = handler.look_ahead();
                 if (c == '0') {
                     handler.consume();
                     c = handler.look_ahead();
                     if (c == 'x') {
                         handler.consume();
                         c = handler.look_ahead();
                     }
                 }
                 while (true) {
                     if (c >= '0' && c <= '9') {
                         handler.consume();
                         res = res * 16 + (c - '0');
                     } else if (c >= 'a' && c <= 'f') {
                         handler.consume();
                         res = res * 16 + (c - 'a' + 10);
                     } else if (c >= 'A' && c <= 'F') {
                         handler.consume();
                         res = res * 16 + (c - 'A' + 10);
                     } else {
                         break;
                     }
                     c = handler.look_ahead();
                 }
                 if (dest)
                     store_int(dest, type, res);
                 break;
             }
             case 's': {
                 char *typed_dest = (char *)dest;
                 char c = handler.look_ahead();
                 int count = 0;
                 while (c && !isspace(c)) {
                     handler.consume();
                     if (typed_dest)
                         typed_dest[count] = c;
                     c = handler.look_ahead();
                     count++;
                     if (width && count >= width)
                         break;
                 }
                 if (typed_dest)
                     typed_dest[count] = '\0';
                 break;
             }
             case 'c': {
                 char *typed_dest = (char *)dest;
                 char c = handler.look_ahead();
                 int count = 0;
                 if (!width)
                     width = 1;
                 while (c && count < width) {
                     handler.consume();
                     if (typed_dest)
                         typed_dest[count] = c;
                     c = handler.look_ahead();
                     count++;
                 }
                 break;
             }
             case '[': {
                 fmt++;
                 int invert = 0;
                 if (*fmt == '^') {
                     invert = 1;
                     fmt++;
                 }
                 char scanset[257];
                 memset(&scanset[0], invert, sizeof(char) * 257);
                 scanset[0] = '\0';
                 if (*fmt == '-') {
                     fmt++;
                     scanset[1+'-'] = 1 - invert;
                 } else if (*fmt == ']') {
                     fmt++;
                     scanset[1+']'] = 1 - invert;
                 }
                 for (; *fmt != ']'; fmt++) {
                     if (!*fmt) return EOF;
                     if (*fmt == '-' && *fmt != ']') {
                         fmt++;
                         for (char c = *(fmt - 2); c < *fmt; c++)
                             scanset[1 + c] = 1 - invert;
                     }
                     scanset[1 + *fmt] = 1 - invert;
                 }
                 char *typed_dest = (char *)dest;
                 int count = 0;
                 char c = handler.look_ahead();
                 while (c && (!width || count < width)) {
                     handler.consume();
                     if (!scanset[1 + c])
                         break;
                     if (typed_dest)
                         typed_dest[count] = c;
                     c = handler.look_ahead();
                     count++;
                 }
                 if (typed_dest)
                     typed_dest[count] = '\0';
                 break;
             }
             case 'p': {
                 unsigned long long res = 0;
                 char c = handler.look_ahead();
                 if (c == '0') {
                     handler.consume();
                     c = handler.look_ahead();
                     if (c == 'x') {
                         handler.consume();
                         c = handler.look_ahead();
                     }
                 }
                 while (true) {
                     if (c >= '0' && c <= '9') {
                         handler.consume();
                         res = res * 16 + (c - '0');
                     } else if (c >= 'a' && c <= 'f') {
                         handler.consume();
                         res = res * 16 + (c - 'a');
                     } else if (c >= 'A' && c <= 'F') {
                         handler.consume();
                         res = res * 16 + (c - 'A');
                     } else {
                         break;
                     }
                     c = handler.look_ahead();
                 }
                 void **typed_dest = (void **)dest;
                 *typed_dest = (void *)(uintptr_t)res;
                 break;
             }
             case 'n': {
                 int *typed_dest = (int *)dest;
                 if (typed_dest)
                     *typed_dest = handler.num_consumed;
                 continue;
             }
         }
         if (dest) match_count++;
     }
     return match_count;
 }
References base, c, count, EOF, fmt, handler(), mlibc::infoLogger, isdigit(), isspace(), memset, NULL, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_CHAR, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_INT, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_INTMAX, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_L, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_LL, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_PTRDIFF, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_SHORT, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_SIZE_T, store_int(), type, and va_arg.
Referenced by vfscanf(), and vsscanf().
feof()
int feof (FILE * file_base)
Definition at line 982 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_EOF_BIT;
 }
References __MLIBC_EOF_BIT.
Referenced by mlibc::get_nameserver(), LoadDefaultCollection(), and main().
feof_unlocked()
int feof_unlocked (FILE * file_base)
Definition at line 1104 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_EOF_BIT;
 }
References __MLIBC_EOF_BIT.
ferror()
int ferror (FILE * file_base)
Definition at line 986 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_ERROR_BIT;
 }
References __MLIBC_ERROR_BIT.
Referenced by getdelim(), getgrent(), getpwent(), getpwnam(), getpwnam_r(), getpwuid(), getpwuid_r(), main(), and anonymous_namespace{grp-stubs.cpp}::walk_file().
ferror_unlocked()
int ferror_unlocked (FILE * file_base)
Definition at line 1108 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_ERROR_BIT;
 }
References __MLIBC_ERROR_BIT.
fgetc()
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int MLIBC_STUB_BODY int __gnuc_va_list MLIBC_STUB_BODY int fgetc (FILE * stream)
Definition at line 835 of file stdio-stubs.cpp.
{
     char c;
     auto bytes_read = fread(&c, 1, 1, stream);
     if(bytes_read != 1)
         return EOF;
     return c;
 }
References c, EOF, and fread().
Referenced by getc(), getchar(), and test().
fgetc_unlocked()
int fgetc_unlocked (FILE * stream)
Definition at line 1112 of file stdio-stubs.cpp.
{
     unsigned char d;
     if(fread_unlocked(&d, 1, 1, stream) != 1)
         return EOF;
     return (int)d;
 }
References EOF, and fread_unlocked().
Referenced by fgets_unlocked(), getc_unlocked(), getchar_unlocked(), and getdelim().
fgetpos()
int fgetpos (FILE * __restrict, fpos_t * __restrict)
Definition at line 966 of file stdio-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fgets()
char* fgets (char *__restrict buffer, size_t max_size, FILE *__restrict stream)
Definition at line 843 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     return fgets_unlocked(buffer, max_size, stream);
 }
References fgets_unlocked(), and max_size.
Referenced by mlibc::get_nameserver(), anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo(), getgrent(), getpwent(), getpwnam(), getpwnam_r(), getpwuid(), getpwuid_r(), gets(), getspnam_r(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), and anonymous_namespace{grp-stubs.cpp}::walk_file().
fgets_unlocked()
char* fgets_unlocked (char *__restrict buffer, int max_size, FILE * stream)
Definition at line 1221 of file stdio-stubs.cpp.
{
     __ensure(max_size > 0);
     for(int i = 0; ; i++) {
         if(i == max_size - 1) {
             buffer[i] = 0;
             return buffer;
         }
         auto c = fgetc_unlocked(stream);
         // If fgetc() fails, there is either an EOF or an I/O error.
         if(c == EOF) {
             if(i) {
                 buffer[i] = 0;
                 return buffer;
             } else {
                 // In this case, the buffer is not changed.
                 return nullptr;
             }
         } else {
             buffer[i] = c;
         }
         if(c == '\n') {
             buffer[i + 1] = 0;
             return buffer;
         }
     }
 }
References __ensure, c, EOF, fgetc_unlocked(), i, and max_size.
Referenced by fgets().
fgetwc()
wint_t fgetwc (FILE *)
flockfile()
void flockfile (FILE * file_base)
Definition at line 1087 of file stdio-stubs.cpp.
{
     static_cast<mlibc::abstract_file *>(file_base)->_lock.lock();
 }
Referenced by main(), and worker().
fprintf()
int fprintf (FILE *__restrict stream, const char *__restrict format, ...)
Definition at line 274 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vfprintf(stream, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, va_end(), va_start(), and vfprintf().
Referenced by perror().
fputc()
int fputc (int c, FILE * stream)
Definition at line 856 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     return fputc_unlocked(c, stream);
 }
References _Print, c, fputc_unlocked(), and syscall2().
Referenced by main(), and test().
fputc_unlocked()
int fputc_unlocked (int c, FILE * stream)
Definition at line 849 of file stdio-stubs.cpp.
{
     char d = c;
     if(fwrite_unlocked(&d, 1, 1, stream) != 1)
         return EOF;
     return 1;
 }
References c, EOF, and fwrite_unlocked().
Referenced by fputc().
fputs()
int fputs (const char *__restrict string, FILE *__restrict stream)
Definition at line 868 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     return fputs_unlocked(string, stream);
 }
References fputs_unlocked().
fputs_unlocked()
int fputs_unlocked (const char *__restrict string, FILE *__restrict stream)
Definition at line 862 of file stdio-stubs.cpp.
{
     if(fwrite_unlocked(string, strlen(string), 1, stream) != 1)
         return EOF;
     return 1;
 }
References EOF, fwrite_unlocked(), and strlen().
Referenced by fputs(), and worker().
fputwc()
wint_t FILE* __restrict MLIBC_STUB_BODY wint_t fputwc (wchar_t , FILE *) const
fread()
wint_t FILE* __restrict MLIBC_STUB_BODY wint_t FILE* __restrict MLIBC_STUB_BODY int FILE* MLIBC_STUB_BODY wint_t FILE* MLIBC_STUB_BODY size_t fread (void * buffer, size_t size, size_t count, FILE * file_base)
Definition at line 954 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     return fread_unlocked(buffer, size, count, file_base);
 }
References _FileRead, count, EINVAL, errno, fread_unlocked(), NULL, size, and syscall4().
Referenced by fgetc(), LoadResponseFile(), M_ReadFile(), M_ReadSaveStrings(), main(), saveg_read8(), and W_StdC_Read().
fread_unlocked()
size_t fread_unlocked (void * buffer, size_t size, size_t count, FILE * file_base)
Definition at line 1119 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(!size || !count)
         return 0;
     // Distinguish two cases here: If the object size is one, we perform byte-wise reads.
     // Otherwise, we try to read each object individually.
     if(size == 1) {
         size_t progress = 0;
         while(progress < count) {
             size_t chunk;
             if(int e = file->read((char *)buffer + progress,
                     count - progress, &chunk)) {
                 errno = e;
                 return 0;
             }else if(!chunk) {
                 // TODO: Handle eof.
                 break;
             }
             progress += chunk;
         }
         return progress;
     }else{
         for(size_t i = 0; i < count; i++) {
             size_t progress = 0;
             while(progress < size) {
                 size_t chunk;
                 if(int e = file->read((char *)buffer + i * size + progress,
                         size - progress, &chunk)) {
                     errno = e;
                     return 0;
                 }else if(!chunk) {
                     // TODO: Handle eof.
                     break;
                 }
                 progress += chunk;
             }
             if(progress < size)
                 return i;
         }
         return count;
     }
 }
References count, errno, i, and size.
Referenced by fgetc_unlocked(), and fread().
freopen()
FILE* freopen (const char * __restrict, const char * __restrict, FILE * __restrict)
Definition at line 256 of file stdio-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fscanf()
int fscanf (FILE *__restrict stream, const char *__restrict format, ...)
Definition at line 282 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vfscanf(stream, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, va_end(), va_start(), and vfscanf().
Referenced by LoadDefaultCollection().
fsetpos()
int fsetpos (FILE * stream, const fpos_t * position)
Definition at line 972 of file stdio-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
ftrylockfile()
int ftrylockfile (FILE * file_base)
Definition at line 1095 of file stdio-stubs.cpp.
{
     static_cast<mlibc::abstract_file *>(file_base)->_lock.try_lock();
     return 0;
 }
Referenced by main().
funlockfile()
void funlockfile (FILE * file_base)
Definition at line 1091 of file stdio-stubs.cpp.
{
     static_cast<mlibc::abstract_file *>(file_base)->_lock.unlock();
 }
Referenced by main(), and worker().
fwide()
wint_t FILE* __restrict MLIBC_STUB_BODY wint_t FILE* __restrict MLIBC_STUB_BODY int fwide (FILE * , int)
fwprintf()
int fwprintf (FILE * __restrict, const wchar_t * __restrict, ...)
fwrite()
size_t fwrite (const void * buffer, size_t size, size_t count, FILE * file_base)
Definition at line 960 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     return fwrite_unlocked(buffer, size, count, file_base);
 }
References _FileWrite, count, EINVAL, errno, fwrite_unlocked(), NULL, size, and syscall4().
Referenced by M_WriteFile(), main(), saveg_write8(), and vwarn().
fwrite_unlocked()
size_t fwrite_unlocked (const void * buffer, size_t size, size_t count, FILE * file_base)
Definition at line 1168 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(!size || !count)
         return 0;
     // Distinguish two cases here: If the object size is one, we perform byte-wise writes.
     // Otherwise, we try to write each object individually.
     if(size == 1) {
         size_t progress = 0;
         while(progress < count) {
             size_t chunk;
             if(file->write((const char *)buffer + progress,
                     count - progress, &chunk)) {
                 // TODO: Handle I/O errors.
                 mlibc::infoLogger() << "mlibc: fwrite() I/O errors are not handled"
                         << frg::endlog;
                 break;
             }else if(!chunk) {
                 // TODO: Handle eof.
                 break;
             }
             progress += chunk;
         }
         return progress;
     }else{
         for(size_t i = 0; i < count; i++) {
             size_t progress = 0;
             while(progress < size) {
                 size_t chunk;
                 if(file->write((const char *)buffer + i * size + progress,
                         size - progress, &chunk)) {
                     // TODO: Handle I/O errors.
                     mlibc::infoLogger() << "mlibc: fwrite() I/O errors are not handled"
                             << frg::endlog;
                     break;
                 }else if(!chunk) {
                     // TODO: Handle eof.
                     break;
                 }
                 progress += chunk;
             }
             if(progress < size)
                 return i;
         }
         return count;
     }
 }
References count, i, mlibc::infoLogger, and size.
Referenced by StreamPrinter::append(), fputc_unlocked(), fputs_unlocked(), fwrite(), and putc_unlocked().
getc()
int getc (FILE * stream)
Definition at line 878 of file stdio-stubs.cpp.
{
     return fgetc(stream);
 }
References fgetc().
Referenced by mlibc::get_nameserver().
getc_unlocked()
int getc_unlocked (FILE * stream)
Definition at line 874 of file stdio-stubs.cpp.
{
     return fgetc_unlocked(stream);
 }
References fgetc_unlocked().
getchar()
int getchar (void)
Definition at line 886 of file stdio-stubs.cpp.
                   {
     return fgetc(stdin);
 }
References fgetc(), and stdin.
getchar_unlocked()
int getchar_unlocked (void)
Definition at line 882 of file stdio-stubs.cpp.
{
     return fgetc_unlocked(stdin);
 }
References fgetc_unlocked(), and stdin.
getdelim()
ssize_t getdelim (char ** line, size_t * n, int delim, FILE * stream)
Definition at line 1004 of file stdio-stubs.cpp.
{
     // Otherwise, we cannot store the buffer / size.
     if(!line || !n) {
         errno = EINVAL;
         return -1;
     }
     char *buffer = *line;
     /* set the starting capacity to 512 if buffer = NULL */
     size_t capacity = (!buffer) ? 512 : *n;
     size_t nwritten = 0;
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     // Avoid allocating if we've already hit the end
     auto c = fgetc_unlocked(stream);
     if (c == EOF || ferror(stream)) {
         return -1;
     } else {
         file->unget(c);
     }
     while (true) {
         // Fill the buffer
         while (buffer && capacity > 0 && nwritten < capacity - 1) {
             auto c = fgetc_unlocked(stream);
             if (ferror(stream)) {
                 return -1;
             } else if (c == EOF) {
                 buffer[nwritten] = 0;
                 return nwritten;
             }
             buffer[nwritten++] = c;
             if (c == delim) {
                 buffer[nwritten] = 0;
                 return nwritten;
             }
         }
         // Double the size of the buffer (but make sure it's at least 1024)
         capacity = (capacity >= 1024) ? capacity * 2 : 1024;
         buffer = reinterpret_cast<char *>(getAllocator().reallocate(*line, capacity));
         if (!buffer) {
             errno = ENOMEM;
             return -1;
         }
         *line = buffer;
         *n = capacity;
     }
 }
References c, EINVAL, ENOMEM, EOF, errno, ferror(), fgetc_unlocked(), getAllocator(), and n.
Referenced by getline(), and main().
getline()
ssize_t getline (char ** line, size_t * n, FILE * stream)
Definition at line 1000 of file stdio-stubs.cpp.
{
     return getdelim(line, n, '\n', stream);
 }
References getdelim(), and n.
Referenced by main().
gets()
char* gets (char * s)
Definition at line 890 of file stdio-stubs.cpp.
                    {
     return fgets(s, SIZE_MAX, stdin);
 }
References fgets(), SIZE_MAX, and stdin.
perror()
void perror (const char * string)
Definition at line 990 of file stdio-stubs.cpp.
{
     int error = errno;
     if (string && *string) {
         fprintf(stderr, "%s: ", string);
     }
     fprintf(stderr, "%s\n", strerror(error));
 }
References errno, fprintf(), fputs(), stderr, and strerror().
Referenced by main(), run_cmd(), and vwarn().
printf()
int printf (const char *__restrict format, ...)
Definition at line 290 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vfprintf(stdout, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, stdout, va_end(), va_start(), and vfprintf().
putc()
int putc (int c, FILE * stream)
Definition at line 901 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     return putc_unlocked(c, stream);
 }
References c, fputc(), and putc_unlocked().
Referenced by vwarnx().
putc_unlocked()
int putc_unlocked (int c, FILE * stream)
Definition at line 894 of file stdio-stubs.cpp.
{
     char d = c;
     if(fwrite_unlocked(&d, 1, 1, stream) != 1)
         return EOF;
     return c;
 }
References c, EOF, and fwrite_unlocked().
Referenced by putc(), and putchar_unlocked().
putchar()
int putchar (int c)
Definition at line 911 of file stdio-stubs.cpp.
                    {
     auto file = static_cast<mlibc::abstract_file *>(stdout);
     frg::unique_lock lock(file->_lock);
     return putchar_unlocked(c);
 }
References c, fputc(), putchar_unlocked(), and stdout.
putchar_unlocked()
int putchar_unlocked (int c)
Definition at line 907 of file stdio-stubs.cpp.
{
     return putc_unlocked(c, stdout);
 }
References c, putc_unlocked(), and stdout.
Referenced by putchar().
puts()
int puts (const char * string)
Definition at line 917 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stdout);
     frg::unique_lock lock(file->_lock);
     size_t progress = 0;
     size_t len = strlen(string);
     while(progress < len) {
         size_t chunk;
         if(file->write(string + progress,
                 len - progress, &chunk)) {
             return EOF;
         }else if(!chunk) {
             return EOF;
         }
         progress += chunk;
     }
     size_t unused;
     if (!file->write("\n", 1, &unused)) {
         return EOF;
     }
     return 1;
 }
References EOF, fputc(), i, len, stdout, and strlen().
Referenced by I_InitSquashTable(), I_InitStretchTables(), and I_PrintBanner().
putwchar()
wint_t FILE* __restrict MLIBC_STUB_BODY wint_t FILE* __restrict MLIBC_STUB_BODY int FILE* MLIBC_STUB_BODY wint_t putwchar (wchar_t)
remove()
int remove (const char * filename)
Definition at line 208 of file stdio-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_rmdir, -1);
     if(int e = mlibc::sys_rmdir(filename); e) {
         if (e == ENOTDIR) {
             MLIBC_CHECK_OR_ENOSYS(mlibc::sys_unlinkat, -1);
             if(e = mlibc::sys_unlinkat(AT_FDCWD, filename, 0); e) {
                 errno = e;
                 return -1;
             }
             return 0;
         }
         return -1;
     }
     return 0;
 }
References AT_FDCWD, ENOTDIR, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_rmdir(), and mlibc::sys_unlinkat().
Referenced by G_DoSaveGame().
rename()
int rename (const char * path, const char * new_path)
Definition at line 226 of file stdio-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_rename, -1);
     if(int e = mlibc::sys_rename(path, new_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_rename().
Referenced by G_DoSaveGame().
renameat()
int renameat (int olddirfd, const char * old_path, int newdirfd, const char * new_path)
Definition at line 235 of file stdio-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_renameat, -1);
     if(int e = mlibc::sys_renameat(olddirfd, old_path, newdirfd, new_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_renameat().
scanf()
int scanf (const char *__restrict format, ...)
Definition at line 681 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vfscanf(stdin, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, stdin, va_end(), va_start(), and vfscanf().
setbuf()
void setbuf (FILE *__restrict stream, char *__restrict buffer)
Definition at line 261 of file stdio-stubs.cpp.
{
     setvbuf(stream, buffer, buffer ? _IOFBF : _IONBF, BUFSIZ);
 }
References _IOFBF, _IONBF, BUFSIZ, and setvbuf().
setbuffer()
void setbuffer (FILE * f, char * buf, size_t size)
Definition at line 270 of file stdio-stubs.cpp.
{
     setvbuf(f, buf, buf ? _IOFBF : _IONBF, size);
 }
References _IOFBF, _IONBF, buf, setvbuf(), and size.
setlinebuf()
void setlinebuf (FILE * stream)
Definition at line 266 of file stdio-stubs.cpp.
{
     setvbuf(stream, NULL, _IOLBF, 0);
 }
References _IOLBF, NULL, and setvbuf().
snprintf()
int snprintf (char *__restrict buffer, size_t max_size, const char *__restrict format, ...)
Definition at line 689 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vsnprintf(buffer, max_size, format, args);
     va_end(args);
     return result;
 }
References args, format, max_size, mlibc::result, va_end(), va_start(), and vsnprintf().
sprintf()
int sprintf (char *__restrict buffer, const char *__restrict format, ...)
Definition at line 697 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vsprintf(buffer, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, va_end(), va_start(), and vsprintf().
sscanf()
int sscanf (const char *__restrict buffer, const char *__restrict format, ...)
Definition at line 705 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vsscanf(buffer, format, args);
     va_end(args);
     return result;
 }
References args, format, mlibc::result, va_end(), va_start(), and vsscanf().
store_int()
static void store_int (void * dest, unsigned int size, unsigned long long i) static
Definition at line 311 of file stdio-stubs.cpp.
{
     switch (size) {
         case SCANF_TYPE_CHAR:
             *(char *)dest = i;
             break;
         case SCANF_TYPE_SHORT:
             *(short *)dest = i;
             break;
         case SCANF_TYPE_INTMAX:
             *(intmax_t *)dest = i;
             break;
         case SCANF_TYPE_L:
             *(long *)dest = i;
             break;
         case SCANF_TYPE_LL:
             *(long long *)dest = i;
             break;
         case SCANF_TYPE_PTRDIFF:
             *(ptrdiff_t *)dest = i;
             break;
         case SCANF_TYPE_SIZE_T:
             *(size_t *)dest = i;
             break;
         /* fallthrough */
         case SCANF_TYPE_INT:
         default:
             *(int *)dest = i;
             break;
     }
 }
References i, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_CHAR, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_INT, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_INTMAX, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_L, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_LL, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_PTRDIFF, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_SHORT, anonymous_namespace{stdio-stubs.cpp}::SCANF_TYPE_SIZE_T, and size.
Referenced by do_scanf().
swprintf()
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int swprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, ...)
tmpfile()
FILE* tmpfile (void)
Definition at line 244 of file stdio-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by main().
tmpnam()
char* tmpnam (char * buffer)
Definition at line 249 of file stdio-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
vasprintf()
int vasprintf (char ** out, const char * format, __gnuc_va_list args)
Definition at line 1069 of file stdio-stubs.cpp.
{
     frg::va_struct vs;
     frg::arg arg_list[NL_ARGMAX + 1];
     vs.arg_list = arg_list;
     va_copy(vs.args, args);
     ResizePrinter p;
 //  mlibc::infoLogger() << "printf(" << format << ")" << frg::endlog;
     auto res = frg::printf_format(PrintfAgent{&p, &vs}, format, &vs);
     if (!res)
         return -static_cast<int>(res.error());
     p.expand();
     p.buffer[p.count] = 0;
     *out = p.buffer;
     return p.count;
 }
References arg, format, NL_ARGMAX, p, and va_copy.
Referenced by asprintf().
vfprintf()
int vfprintf (FILE *__restrict stream, const char *__restrict format, __gnuc_va_list args)
Definition at line 715 of file stdio-stubs.cpp.
{
     frg::va_struct vs;
     frg::arg arg_list[NL_ARGMAX + 1];
     vs.arg_list = arg_list;
     va_copy(vs.args, args);
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     StreamPrinter p{stream};
 //  mlibc::infoLogger() << "printf(" << format << ")" << frg::endlog;
     auto res = frg::printf_format(PrintfAgent{&p, &vs}, format, &vs);
     if (!res)
         return -static_cast<int>(res.error());
     return p.count;
 }
References arg, format, NL_ARGMAX, p, and va_copy.
Referenced by fprintf(), printf(), and vprintf().
vfscanf()
int vfscanf (FILE *__restrict stream, const char *__restrict format, __gnuc_va_list args)
Definition at line 731 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     struct {
         char look_ahead() {
             char c;
             size_t actual_size;
             file->read(&c, 1, &actual_size);
             if (actual_size)
                 file->unget(c);
             return actual_size ? c : 0;
         }
         char consume() {
             char c;
             size_t actual_size;
             file->read(&c, 1, &actual_size);
             if (actual_size)
                 num_consumed++;
             return actual_size ? c : 0;
         }
         mlibc::abstract_file *file;
         int num_consumed;
     } handler = {file, 0};
     return do_scanf(handler, format, args);
 }
References c, do_scanf(), format, and handler().
Referenced by fscanf(), and scanf().
vfwprintf()
int const wchar_t MLIBC_STUB_BODY int vfwprintf (FILE * __restrict, const wchar_t * __restrict, __gnuc_va_list)
vprintf()
int vprintf (const char *__restrict format, __gnuc_va_list args)
Definition at line 761 of file stdio-stubs.cpp.
{
     return vfprintf(stdout, format, args);
 }
References format, stdout, and vfprintf().
vscanf()
int vscanf (const char * __restrict, __gnuc_va_list)
Definition at line 765 of file stdio-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
vsnprintf()
int vsnprintf (char *__restrict buffer, size_t max_size, const char *__restrict format, __gnuc_va_list args)
Definition at line 770 of file stdio-stubs.cpp.
{
     frg::va_struct vs;
     frg::arg arg_list[NL_ARGMAX + 1];
     vs.arg_list = arg_list;
     va_copy(vs.args, args);
     LimitedPrinter p{buffer, max_size ? max_size - 1 : 0};
 //  mlibc::infoLogger() << "printf(" << format << ")" << frg::endlog;
     auto res = frg::printf_format(PrintfAgent{&p, &vs}, format, &vs);
     if (!res)
         return -static_cast<int>(res.error());
     if (max_size)
         p.buffer[frg::min(max_size - 1, p.count)] = 0;
     return p.count;
 }
References arg, format, max_size, NL_ARGMAX, p, and va_copy.
Referenced by snprintf().
vsprintf()
int vsprintf (char *__restrict buffer, const char *__restrict format, __gnuc_va_list args)
Definition at line 786 of file stdio-stubs.cpp.
{
     frg::va_struct vs;
     frg::arg arg_list[NL_ARGMAX + 1];
     vs.arg_list = arg_list;
     va_copy(vs.args, args);
     BufferPrinter p(buffer);
 //  mlibc::infoLogger() << "printf(" << format << ")" << frg::endlog;
     auto res = frg::printf_format(PrintfAgent{&p, &vs}, format, &vs);
     if (!res)
         return -static_cast<int>(res.error());
     p.buffer[p.count] = 0;
     return p.count;
 }
References arg, format, NL_ARGMAX, p, and va_copy.
Referenced by sprintf().
vsscanf()
int vsscanf (const char *__restrict buffer, const char *__restrict format, __gnuc_va_list args)
Definition at line 800 of file stdio-stubs.cpp.
{
     struct {
         char look_ahead() {
             return *buffer;
         }
         char consume() {
             num_consumed++;
             return *buffer++;
         }
         const char *buffer;
         int num_consumed;
     } handler = {buffer, 0};
     int result = do_scanf(handler, format, args);
     return result;
 }
References do_scanf(), format, handler(), and mlibc::result.
Referenced by sscanf().
vswprintf()
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int vswprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, __gnuc_va_list)
vwprintf()
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int MLIBC_STUB_BODY int vwprintf (const wchar_t * __restrict, __gnuc_va_list) const
wprintf()
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int wprintf (const wchar_t * __restrict, ...) const
Variable Documentation
__restrict
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int const wchar_t * __restrict
Definition at line 821 of file stdio-stubs.cpp.
Referenced by child().
int
wint_t int
Definition at line 944 of file stdio-stubs.cpp.
Referenced by __lgamma_r(), __lgammaf_r(), __mlibc_dev_major(), __mlibc_dev_minor(), bastardized_floor(), Driver::Driver::BindInputInput(), Driver::Driver::BindInterruptInput(), Driver::Driver::BindInterruptStorage(), Driver::Driver::BindPCIAudio(), Driver::Driver::BindPCINetwork(), Driver::Driver::BindPCIStorage(), Driver::Driver::CallDriverEntryPoint(), ceilf(), std::string::erase(), exp(), exp10(), exp10f(), F_BunnyScroll(), F_TextWrite(), floorf(), GenerateStretchTable(), inet_ntop(), Driver::Driver::IOCB(), mlibc::ioctl_drm(), liballoc_memcpy(), log(), log10(), log10f(), log1p(), log1pf(), log2(), log2f(), logf(), main(), mem_fseek(), modf(), modff(), print_exponential_number(), R_ProjectSprite(), remquo(), remquof(), sin_pi(), sqrt(), sqrtf(), StartCPU(), sys_fork(), tgamma(), trunc(), truncf(), CrashHandler::UserInput(), V_DrawMouseSpeedBox(), wipe_ScreenWipe(), and xatol().
size_t
int const wchar_t MLIBC_STUB_BODY int const wchar_t __gnuc_va_list MLIBC_STUB_BODY int const wchar_t MLIBC_STUB_BODY int size_t
Definition at line 826 of file stdio-stubs.cpp.
Referenced by PrintfAgent< F >::operator()().