Fennix Userspace: Userspace/musl/include/signal.h File Reference
signal.h File Reference
#include <features.h>
#include <bits/signal.h>
Macros
#define SIG_ERR ((void (*)(int))-1)
#define SIG_DFL ((void (*)(int)) 0)
#define SIG_IGN ((void (*)(int)) 1)
Typedefs
typedef int sig_atomic_t
Functions
int raise (int)
Variables
void(*)(int) signal (int, void(*)(int))
Macro Definition Documentation
SIG_DFL
#define SIG_DFL ((void (*)(int)) 0)
Definition at line 284 of file signal.h.
SIG_ERR
#define SIG_ERR ((void (*)(int))-1)
Definition at line 283 of file signal.h.
SIG_IGN
#define SIG_IGN ((void (*)(int)) 1)
Definition at line 285 of file signal.h.
Typedef Documentation
sig_atomic_t
typedef int sig_atomic_t
Definition at line 287 of file signal.h.
Function Documentation
raise()
int raise (int sig)
Definition at line 6 of file raise.c.
 {
     sigset_t set;
     __block_app_sigs(&set);
     int ret = syscall(SYS_tkill, __pthread_self()->tid, sig);
     __restore_sigs(&set);
     return ret;
 }
References __block_app_sigs(), __pthread_self, __restore_sigs(), and syscall().
Variable Documentation
signal
void(*)(int) signal(int, void(*)(int)) (int , void(*)(int))
Definition at line 289 of file signal.h.
Referenced by _rl_handle_signal(), alarm_handler(), alarm_intr(), arm(), askremotedate(), bb_signals(), chat_main(), check_blocks(), common_ping_main(), data_extract_to_command(), do_syslogd(), dolisten(), edit_file(), exec_conf(), fakeidentd_main(), ftpd_main(), getty_main(), handle_incoming_and_exit(), HandleSignal(), httpd_main(), ignoresig(), initialize_terminating_signals(), kill_myself_with_sig(), kill_pid(), klogd_main(), less_main(), login_main(), main(), mini_httpd_nommu(), nc_main(), nohup_main(), openhere(), parse(), procargs(), raise_interrupt(), reset_terminating_signals(), rl_set_sighandler(), rl_sigaction(), run_command(), script_main(), send_file_and_exit(), sigint_sighandler(), start_shell_in_child(), startservice(), stop_handler(), tar_main(), tcpudpsvd_main(), tee_main(), telnet_main(), telnetd_main(), test_signal(), unarm(), and wget_main().