Fennix Userspace: Userspace/musl/src/internal/floatscan.h File Reference
floatscan.h File Reference
#include <stdio.h>
Functions
hidden long double __floatscan (FILE *, int, int)
Function Documentation
__floatscan()
hidden long double __floatscan (FILE * f, int prec, int pok)
Definition at line 426 of file floatscan.c.
 {
     int sign = 1;
     size_t i;
     int bits;
     int emin;
     int c;
     switch (prec) {
     case 0:
         bits = FLT_MANT_DIG;
         emin = FLT_MIN_EXP-bits;
         break;
     case 1:
         bits = DBL_MANT_DIG;
         emin = DBL_MIN_EXP-bits;
         break;
     case 2:
         bits = LDBL_MANT_DIG;
         emin = LDBL_MIN_EXP-bits;
         break;
     default:
         return 0;
     }
     while (isspace((c=shgetc(f))));
     if (c=='+' || c=='-') {
         sign -= 2*(c=='-');
         c = shgetc(f);
     }
     for (i=0; i<8 && (c|32)=="infinity"[i]; i++)
         if (i<7) c = shgetc(f);
     if (i==3 || i==8 || (i>3 && pok)) {
         if (i!=8) {
             shunget(f);
             if (pok) for (; i>3; i--) shunget(f);
         }
         return sign * INFINITY;
     }
     if (!i) for (i=0; i<3 && (c|32)=="nan"[i]; i++)
         if (i<2) c = shgetc(f);
     if (i==3) {
         if (shgetc(f) != '(') {
             shunget(f);
             return NAN;
         }
         for (i=1; ; i++) {
             c = shgetc(f);
             if (c-'0'<10U || c-'A'<26U || c-'a'<26U || c=='_')
                 continue;
             if (c==')') return NAN;
             shunget(f);
             if (!pok) {
                 errno = EINVAL;
                 shlim(f, 0);
                 return 0;
             }
             while (i--) shunget(f);
             return NAN;
         }
         return NAN;
     }
     if (i) {
         shunget(f);
         errno = EINVAL;
         shlim(f, 0);
         return 0;
     }
     if (c=='0') {
         c = shgetc(f);
         if ((c|32) == 'x')
             return hexfloat(f, bits, emin, sign, pok);
         shunget(f);
         c = '0';
     }
     return decfloat(f, c, bits, emin, sign, pok);
 }
References c, DBL_MANT_DIG, DBL_MIN_EXP, decfloat(), EINVAL, errno, f, FLT_MANT_DIG, FLT_MIN_EXP, hexfloat(), i, INFINITY, isspace, LDBL_MANT_DIG, LDBL_MIN_EXP, NAN, prec, shgetc, shlim, and shunget.
Referenced by strtox(), vfscanf(), and wcstox().