Fennix Userspace: Userspace/apps/base/busybox/coreutils/ls.c File Reference
ls.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "unicode.h"
Data Structures
struct dnode
struct globals
Macros
#define ls_options
#define G_show_color 0
#define G_terminal_width TERMINAL_WIDTH
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define ESC "\033"
#define TYPEINDEX(mode) (((mode) >> 12) & 0x0f)
#define APPCHAR(mode) ("\0""|""\0""\0""/""\0""\0""\0""\0""\0""@""\0""=""\0""\0""\0" [TYPEINDEX(mode)])
#define COLOR(mode)
#define ATTR(mode)
#define dfree(...) ((void)0)
#define dnsort(dn, size) ((void)0)
#define sort_and_display_files(dn, nfiles) display_files(dn, nfiles)
Enumerations
enum { TERMINAL_WIDTH = 80 , SPLIT_FILE = 0 , SPLIT_DIR = 1 , SPLIT_SUBDIR = 2 }
enum {
OPT_C = (1 << 0) , OPT_a = (1 << 1) , OPT_d = (1 << 2) , OPT_i = (1 << 3) ,
OPT_1 = (1 << 4) , OPT_l = (1 << 5) , OPT_g = (1 << 6) , OPT_n = (1 << 7) ,
OPT_s = (1 << 8) , OPT_x = (1 << 9) , OPT_A = (1 << 10) , OPTBIT_F = 12 ,
OPTBIT_p , OPTBIT_R = OPTBIT_F + 2 * ENABLE_FEATURE_LS_FILETYPES , OPTBIT_Z = OPTBIT_R + 1 * ENABLE_FEATURE_LS_RECURSIVE , OPTBIT_Q = OPTBIT_Z + 1 * ENABLE_SELINUX ,
OPTBIT_c , OPTBIT_t , OPTBIT_u , OPTBIT_S = OPTBIT_c + 3 * ENABLE_FEATURE_LS_TIMESTAMPS ,
OPTBIT_X , OPTBIT_r , OPTBIT_v , OPTBIT_L = OPTBIT_S + 4 * ENABLE_FEATURE_LS_SORTFILES ,
OPTBIT_H , OPTBIT_h = OPTBIT_L + 2 * ENABLE_FEATURE_LS_FOLLOWLINKS , OPTBIT_T = OPTBIT_h + 1 * ENABLE_FEATURE_HUMAN_READABLE , OPTBIT_w ,
OPTBIT_full_time = OPTBIT_T + 2 * ENABLE_FEATURE_LS_WIDTH , OPTBIT_dirs_first , OPTBIT_color , OPT_F = (1 << OPTBIT_F) * ENABLE_FEATURE_LS_FILETYPES ,
OPT_p = (1 << OPTBIT_p) * ENABLE_FEATURE_LS_FILETYPES , OPT_R = (1 << OPTBIT_R) * ENABLE_FEATURE_LS_RECURSIVE , OPT_Z = (1 << OPTBIT_Z) * ENABLE_SELINUX , OPT_Q = (1 << OPTBIT_Q) ,
OPT_c = (1 << OPTBIT_c) * ENABLE_FEATURE_LS_TIMESTAMPS , OPT_t = (1 << OPTBIT_t) * ENABLE_FEATURE_LS_TIMESTAMPS , OPT_u = (1 << OPTBIT_u) * ENABLE_FEATURE_LS_TIMESTAMPS , OPT_S = (1 << OPTBIT_S) * ENABLE_FEATURE_LS_SORTFILES ,
OPT_X = (1 << OPTBIT_X) * ENABLE_FEATURE_LS_SORTFILES , OPT_r = (1 << OPTBIT_r) * ENABLE_FEATURE_LS_SORTFILES , OPT_v = (1 << OPTBIT_v) * ENABLE_FEATURE_LS_SORTFILES , OPT_L = (1 << OPTBIT_L) * ENABLE_FEATURE_LS_FOLLOWLINKS ,
OPT_H = (1 << OPTBIT_H) * ENABLE_FEATURE_LS_FOLLOWLINKS , OPT_h = (1 << OPTBIT_h) * ENABLE_FEATURE_HUMAN_READABLE , OPT_T = (1 << OPTBIT_T) * ENABLE_FEATURE_LS_WIDTH , OPT_w = (1 << OPTBIT_w) * ENABLE_FEATURE_LS_WIDTH ,
OPT_full_time = (1 << OPTBIT_full_time) * ENABLE_LONG_OPTS , OPT_dirs_first = (1 << OPTBIT_dirs_first) * ENABLE_LONG_OPTS , OPT_color = (1 << OPTBIT_color) * ENABLE_FEATURE_LS_COLOR
}
Functions
static unsigned calc_name_len (const char *name)
static unsigned print_name (const char *name)
static NOINLINE unsigned display_single (const struct dnode *dn)
static void display_files (struct dnode **dn, unsigned nfiles)
static struct dnode * my_stat (const char *fullname, const char *name, int force_follow)
static unsigned count_dirs (struct dnode **dn, int which)
static struct dnode ** dnalloc (unsigned num)
static struct dnode ** splitdnarray (struct dnode **dn, int which)
static struct dnode ** scan_one_dir (const char *path, unsigned *nfiles_p)
static void scan_and_display_dirs_recur (struct dnode **dn, int first)
int ls_main (int argc UNUSED_PARAM, char **argv)
Variables
struct globals FIX_ALIASING
Data Structure Documentation
dnode
struct dnode
Definition at line 282 of file ls.c.
Data Fields
blkcnt_t dn_blocks
gid_t dn_gid
ino_t dn_ino
mode_t dn_mode
mode_t dn_mode_lstat
mode_t dn_mode_stat
struct dnode * dn_next
nlink_t dn_nlink
int dn_rdev_maj
int dn_rdev_min
off_t dn_size
uid_t dn_uid
smallint fname_allocated
const char * fullname
const char * name
Macro Definition Documentation
APPCHAR
#define APPCHAR (mode) ("\0""|""\0""\0""/""\0""\0""\0""\0""\0""@""\0""=""\0""\0""\0" [TYPEINDEX(mode)])
Definition at line 362 of file ls.c.
ATTR
#define ATTR (mode)
Value:
    ( \
    /*un fi chr - dir - blk - file- link- sock- -  exe */ \
    "\01\00\01\07\01\07\01\07\00\07\01\07\01\07\07\01" \
    [TYPEINDEX(mode)])
Definition at line 381 of file ls.c.
COLOR
#define COLOR (mode)
Value:
    ( \
    /*un  fi  chr  -  dir  -  blk  -  file -  link -  sock -   -  exe */ \
    "\037\043\043\045\042\045\043\043\000\045\044\045\043\045\045\040" \
    [TYPEINDEX(mode)])
Definition at line 372 of file ls.c.
dfree
#define dfree (...) ((void)0)
Definition at line 816 of file ls.c.
dnsort
#define dnsort (dn, size) ((void)0)
Definition at line 919 of file ls.c.
ESC
#define ESC "\033"
Definition at line 350 of file ls.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 341 of file ls.c.
G_show_color
#define G_show_color 0
Definition at line 326 of file ls.c.
G_terminal_width
#define G_terminal_width TERMINAL_WIDTH
Definition at line 334 of file ls.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    /* we have to zero it out because of NOEXEC */ \
    memset(&G, 0, sizeof(G)); \
    IF_FEATURE_LS_WIDTH(G_terminal_width = TERMINAL_WIDTH;) \
    IF_FEATURE_LS_TIMESTAMPS(time(&G.current_time_t);) \
} while (0)
Definition at line 342 of file ls.c.
ls_options
#define ls_options
Value:
    "Cadi1lgnsxAk"       /* 12 opts, total 12 */ \
    IF_FEATURE_LS_FILETYPES("Fp")    /* 2, 14 */ \
    IF_FEATURE_LS_RECURSIVE("R")     /* 1, 15 */ \
    IF_SELINUX("Z")                  /* 1, 16 */ \
    "Q"                              /* 1, 17 */ \
    IF_FEATURE_LS_TIMESTAMPS("ctu")  /* 3, 20 */ \
    IF_FEATURE_LS_SORTFILES("SXrv")  /* 4, 24 */ \
    IF_FEATURE_LS_FOLLOWLINKS("LH")  /* 2, 26 */ \
    IF_FEATURE_HUMAN_READABLE("h")   /* 1, 27 */ \
    IF_FEATURE_LS_WIDTH("T:w:")      /* 2, 29 */
Definition at line 209 of file ls.c.
sort_and_display_files
#define sort_and_display_files (dn, nfiles) display_files(dn, nfiles)
Definition at line 920 of file ls.c.
TYPEINDEX
#define TYPEINDEX (mode) (((mode) >> 12) & 0x0f)
Definition at line 360 of file ls.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TERMINAL_WIDTH
SPLIT_FILE
SPLIT_DIR
SPLIT_SUBDIR
Definition at line 189 of file ls.c.
      {
 TERMINAL_WIDTH  = 80, /* use 79 if terminal has linefold bug */
 SPLIT_FILE      = 0,
 SPLIT_DIR       = 1,
 SPLIT_SUBDIR    = 2,
 };
anonymous enum
anonymous enum
Enumerator
OPT_C
OPT_a
OPT_d
OPT_i
OPT_1
OPT_l
OPT_g
OPT_n
OPT_s
OPT_x
OPT_A
OPTBIT_F
OPTBIT_p
OPTBIT_R
OPTBIT_Z
OPTBIT_Q
OPTBIT_c
OPTBIT_t
OPTBIT_u
OPTBIT_S
OPTBIT_X
OPTBIT_r
OPTBIT_v
OPTBIT_L
OPTBIT_H
OPTBIT_h
OPTBIT_T
OPTBIT_w
OPTBIT_full_time
OPTBIT_dirs_first
OPTBIT_color
OPT_F
OPT_p
OPT_R
OPT_Z
OPT_Q
OPT_c
OPT_t
OPT_u
OPT_S
OPT_X
OPT_r
OPT_v
OPT_L
OPT_H
OPT_h
OPT_T
OPT_w
OPT_full_time
OPT_dirs_first
OPT_color
Definition at line 221 of file ls.c.
      {
     OPT_C = (1 << 0),
     OPT_a = (1 << 1),
     OPT_d = (1 << 2),
     OPT_i = (1 << 3),
     OPT_1 = (1 << 4),
     OPT_l = (1 << 5),
     OPT_g = (1 << 6),
     OPT_n = (1 << 7),
     OPT_s = (1 << 8),
     OPT_x = (1 << 9),
     OPT_A = (1 << 10),
     //OPT_k = (1 << 11),
     OPTBIT_F = 12,
     OPTBIT_p, /* 13 */
     OPTBIT_R = OPTBIT_F + 2 * ENABLE_FEATURE_LS_FILETYPES,
     OPTBIT_Z = OPTBIT_R + 1 * ENABLE_FEATURE_LS_RECURSIVE,
     OPTBIT_Q = OPTBIT_Z + 1 * ENABLE_SELINUX,
     OPTBIT_c, /* 17 */
     OPTBIT_t, /* 18 */
     OPTBIT_u, /* 19 */
     OPTBIT_S = OPTBIT_c + 3 * ENABLE_FEATURE_LS_TIMESTAMPS,
     OPTBIT_X, /* 21 */
     OPTBIT_r, /* 22 */
     OPTBIT_v, /* 23 */
     OPTBIT_L = OPTBIT_S + 4 * ENABLE_FEATURE_LS_SORTFILES,
     OPTBIT_H, /* 25 */
     OPTBIT_h = OPTBIT_L + 2 * ENABLE_FEATURE_LS_FOLLOWLINKS,
     OPTBIT_T = OPTBIT_h + 1 * ENABLE_FEATURE_HUMAN_READABLE,
     OPTBIT_w, /* 28 */
     OPTBIT_full_time = OPTBIT_T + 2 * ENABLE_FEATURE_LS_WIDTH,
     OPTBIT_dirs_first,
     OPTBIT_color, /* 31 */
     /* with long opts, we use all 32 bits */
     OPT_F = (1 << OPTBIT_F) * ENABLE_FEATURE_LS_FILETYPES,
     OPT_p = (1 << OPTBIT_p) * ENABLE_FEATURE_LS_FILETYPES,
     OPT_R = (1 << OPTBIT_R) * ENABLE_FEATURE_LS_RECURSIVE,
     OPT_Z = (1 << OPTBIT_Z) * ENABLE_SELINUX,
     OPT_Q = (1 << OPTBIT_Q),
     OPT_c = (1 << OPTBIT_c) * ENABLE_FEATURE_LS_TIMESTAMPS,
     OPT_t = (1 << OPTBIT_t) * ENABLE_FEATURE_LS_TIMESTAMPS,
     OPT_u = (1 << OPTBIT_u) * ENABLE_FEATURE_LS_TIMESTAMPS,
     OPT_S = (1 << OPTBIT_S) * ENABLE_FEATURE_LS_SORTFILES,
     OPT_X = (1 << OPTBIT_X) * ENABLE_FEATURE_LS_SORTFILES,
     OPT_r = (1 << OPTBIT_r) * ENABLE_FEATURE_LS_SORTFILES,
     OPT_v = (1 << OPTBIT_v) * ENABLE_FEATURE_LS_SORTFILES,
     OPT_L = (1 << OPTBIT_L) * ENABLE_FEATURE_LS_FOLLOWLINKS,
     OPT_H = (1 << OPTBIT_H) * ENABLE_FEATURE_LS_FOLLOWLINKS,
     OPT_h = (1 << OPTBIT_h) * ENABLE_FEATURE_HUMAN_READABLE,
     OPT_T = (1 << OPTBIT_T) * ENABLE_FEATURE_LS_WIDTH,
     OPT_w = (1 << OPTBIT_w) * ENABLE_FEATURE_LS_WIDTH,
     OPT_full_time  = (1 << OPTBIT_full_time ) * ENABLE_LONG_OPTS,
     OPT_dirs_first = (1 << OPTBIT_dirs_first) * ENABLE_LONG_OPTS,
     OPT_color      = (1 << OPTBIT_color     ) * ENABLE_FEATURE_LS_COLOR,
 };
Function Documentation
calc_name_len()
static unsigned calc_name_len (const char * name) static
Definition at line 418 of file ls.c.
 {
     unsigned len;
     uni_stat_t uni_stat;
     // TODO: quote tab as \t, etc, if -Q
     name = printable_string2(&uni_stat, name);
     if (!(option_mask32 & OPT_Q)) {
         return uni_stat.unicode_width;
     }
     len = 2 + uni_stat.unicode_width;
     while (*name) {
         if (*name == '"' || *name == '\\') {
             len++;
         }
         name++;
     }
     return len;
 }
References OPT_Q, option_mask32, printable_string2(), and uni_stat_t::unicode_width.
Referenced by display_files().
count_dirs()
static unsigned count_dirs (struct dnode ** dn, int which) static
Definition at line 762 of file ls.c.
 {
     unsigned dirs, all;
     if (!dn)
         return 0;
     dirs = all = 0;
     for (; *dn; dn++) {
         const char *name;
         all++;
         if (!S_ISDIR((*dn)->dn_mode))
             continue;
         name = (*dn)->name;
         if (which != SPLIT_SUBDIR /* if not requested to skip . / .. */
          /* or if it's not . or .. */
          || name[0] != '.'
          || (name[1] && (name[1] != '.' || name[2]))
         ) {
             dirs++;
         }
     }
     return which != SPLIT_FILE ? dirs : all - dirs;
 }
References dnode::name, S_ISDIR, SPLIT_FILE, and SPLIT_SUBDIR.
Referenced by ls_main(), main(), scan_and_display_dirs_recur(), and splitdnarray().
display_files()
static void display_files (struct dnode ** dn, unsigned nfiles) static
Definition at line 644 of file ls.c.
 {
     unsigned i, ncols, nrows, row, nc;
     unsigned column;
     unsigned nexttab;
     unsigned column_width = 0; /* used only by coulmnal output */
     if (option_mask32 & (OPT_l|OPT_1)) {
         ncols = 1;
     } else {
         /* find the longest file name, use that as the column width */
         for (i = 0; dn[i]; i++) {
             int len = calc_name_len(dn[i]->name);
             if (column_width < len)
                 column_width = len;
         }
         column_width += 2
             + ((option_mask32 & OPT_Z) ? 33 : 0) /* context width */
             + ((option_mask32 & OPT_i) ? 8 : 0) /* inode# width */
             + ((option_mask32 & OPT_s) ? 5 : 0) /* "alloc block" width */
         ;
         ncols = (unsigned)G_terminal_width / column_width;
     }
     if (ncols > 1) {
         nrows = nfiles / ncols;
         if (nrows * ncols < nfiles)
             nrows++;                /* round up fractionals */
     } else {
         nrows = nfiles;
         ncols = 1;
     }
     column = 0;
     nexttab = 0;
     for (row = 0; row < nrows; row++) {
         for (nc = 0; nc < ncols; nc++) {
             /* reach into the array based on the column and row */
             if (option_mask32 & OPT_x)
                 i = (row * ncols) + nc; /* display across row */
             else
                 i = (nc * nrows) + row; /* display by column */
             if (i < nfiles) {
                 if (column > 0) {
                     nexttab -= column;
                     printf("%*s", nexttab, "");
                     column += nexttab;
                 }
                 nexttab = column + column_width;
                 column += display_single(dn[i]);
             }
         }
         putchar('\n');
         column = 0;
     }
 }
References calc_name_len(), display_single(), G_terminal_width, i, OPT_1, OPT_i, OPT_l, OPT_s, OPT_x, OPT_Z, option_mask32, printf(), and putchar.
display_single()
static NOINLINE unsigned display_single (const struct dnode * dn) static
Definition at line 478 of file ls.c.
 {
     unsigned column = 0;
     char *lpath;
     int opt;
 #if ENABLE_FEATURE_LS_FILETYPES || ENABLE_FEATURE_LS_COLOR
     struct stat statbuf;
 #endif
 #if ENABLE_FEATURE_LS_FILETYPES
     char append = append_char(dn->dn_mode);
 #endif
     opt = option_mask32;
     /* Do readlink early, so that if it fails, error message
      * does not appear *inside* the "ls -l" line */
     lpath = NULL;
     if (opt & OPT_l)
         if (S_ISLNK(dn->dn_mode))
             lpath = xmalloc_readlink_or_warn(dn->fullname);
     if (opt & OPT_i) /* show inode# */
         column += printf("%7llu ", (long long) dn->dn_ino);
     if (opt & OPT_s) { /* show allocated blocks */
         if (opt & OPT_h) {
             column += printf("%"HUMAN_READABLE_MAX_WIDTH_STR"s ",
                 /* print size, show one fractional, use suffixes */
                 make_human_readable_str((off_t)dn->dn_blocks << 9, 1, 0)
             );
         } else {
             column += printf("%6"OFF_FMT"u ", (off_t)(dn->dn_blocks >> 1));
         }
     }
     if (opt & OPT_l) {
         /* long listing: show mode */
         char modestr[12];
         column += printf("%-10s ", bb_mode_string(modestr, dn->dn_mode));
         /* long listing: show number of links */
         column += printf("%4lu ", (long) dn->dn_nlink);
         /* long listing: show user/group */
         if (opt & OPT_n) {
             if (opt & OPT_g)
                 column += printf("%-8u ", (int) dn->dn_gid);
             else
                 column += printf("%-8u %-8u ",
                         (int) dn->dn_uid,
                         (int) dn->dn_gid);
         }
 #if ENABLE_FEATURE_LS_USERNAME
         else {
             if (opt & OPT_g) {
                 column += printf("%-8.8s ",
                     get_cached_groupname(dn->dn_gid));
             } else {
                 column += printf("%-8.8s %-8.8s ",
                     get_cached_username(dn->dn_uid),
                     get_cached_groupname(dn->dn_gid));
             }
         }
 #endif
 #if ENABLE_SELINUX
     }
     if (opt & OPT_Z) {
         column += printf("%-32s ", dn->sid ? dn->sid : "?");
         freecon(dn->sid);
     }
     if (opt & OPT_l) {
 #endif
         /* long listing: show size */
         if (S_ISBLK(dn->dn_mode) || S_ISCHR(dn->dn_mode)) {
             column += printf("%4u, %3u ",
                     dn->dn_rdev_maj,
                     dn->dn_rdev_min);
         } else {
             if (opt & OPT_h) {
                 column += printf("%"HUMAN_READABLE_MAX_WIDTH_STR"s ",
                     /* print size, show one fractional, use suffixes */
                     make_human_readable_str(dn->dn_size, 1, 0)
                 );
             } else {
                 column += printf("%9"OFF_FMT"u ", dn->dn_size);
             }
         }
 #if ENABLE_FEATURE_LS_TIMESTAMPS
         /* long listing: show {m,c,a}time */
         if (opt & OPT_full_time) { /* --full-time */
             /* coreutils 8.4 ls --full-time prints:
              * 2009-07-13 17:49:27.000000000 +0200
              * we don't show fractional seconds.
              */
             char buf[sizeof("YYYY-mm-dd HH:MM:SS TIMEZONE")];
             strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S %z",
                     localtime(&dn->dn_time));
             column += printf("%s ", buf);
         } else { /* ordinary time format */
             /* G.current_time_t is ~== time(NULL) */
             char *filetime = ctime(&dn->dn_time);
             /* filetime's format: "Wed Jun 30 21:49:08 1993\n" */
             time_t age = G.current_time_t - dn->dn_time;
             if (age < 3600L * 24 * 365 / 2 && age > -15 * 60) {
                 /* less than 6 months old */
                 /* "mmm dd hh:mm " */
                 printf("%.12s ", filetime + 4);
             } else {
                 /* "mmm dd  yyyy " */
                 /* "mmm dd yyyyy " after year 9999 :) */
                 strchr(filetime + 20, '\n')[0] = ' ';
                 printf("%.7s%6s", filetime + 4, filetime + 20);
             }
             column += 13;
         }
 #endif
     }
 #if ENABLE_FEATURE_LS_COLOR
     if (G_show_color) {
         mode_t mode = dn->dn_mode_lstat;
         if (!mode)
             if (lstat(dn->fullname, &statbuf) == 0)
                 mode = statbuf.st_mode;
         printf(ESC"[%u;%um", bold(mode), fgcolor(mode));
     }
 #endif
     column += print_name(dn->name);
     if (G_show_color) {
         printf(ESC"[m");
     }
     if (lpath) {
         printf(" -> ");
 #if ENABLE_FEATURE_LS_FILETYPES || ENABLE_FEATURE_LS_COLOR
         if ((opt & (OPT_F|OPT_p))
          || G_show_color
         ) {
             mode_t mode = dn->dn_mode_stat;
             if (!mode)
                 if (stat(dn->fullname, &statbuf) == 0)
                     mode = statbuf.st_mode;
 # if ENABLE_FEATURE_LS_FILETYPES
             append = append_char(mode);
 # endif
 # if ENABLE_FEATURE_LS_COLOR
             if (G_show_color) {
                 printf(ESC"[%u;%um", bold(mode), fgcolor(mode));
             }
 # endif
         }
 #endif
         column += print_name(lpath) + 4;
         free(lpath);
         if (G_show_color) {
             printf(ESC"[m");
         }
     }
 #if ENABLE_FEATURE_LS_FILETYPES
     if (opt & (OPT_F|OPT_p)) {
         if (append) {
             putchar(append);
             column++;
         }
     }
 #endif
     return column;
 }
References append(), bb_mode_string(), buf, ctime(), dnode::dn_blocks, dnode::dn_gid, dnode::dn_ino, dnode::dn_mode, dnode::dn_mode_lstat, dnode::dn_mode_stat, dnode::dn_nlink, dnode::dn_rdev_maj, dnode::dn_rdev_min, dnode::dn_size, dnode::dn_uid, ESC, free, dnode::fullname, G, G_show_color, get_cached_groupname(), get_cached_username(), HUMAN_READABLE_MAX_WIDTH_STR, localtime(), lstat, make_human_readable_str(), mode_t, dnode::name, NULL, OFF_FMT, off_t, opt, OPT_F, OPT_full_time, OPT_g, OPT_h, OPT_i, OPT_l, OPT_n, OPT_p, OPT_s, OPT_Z, option_mask32, print_name(), printf(), putchar, S_ISBLK, S_ISCHR, S_ISLNK, stat::st_mode, stat(), strchr(), strftime(), and xmalloc_readlink_or_warn().
Referenced by display_files().
dnalloc()
static struct dnode** dnalloc (unsigned num) static
Definition at line 790 of file ls.c.
 {
     if (num < 1)
         return NULL;
     num++; /* so that we have terminating NULL */
     return xzalloc(num * sizeof(struct dnode *));
 }
References NULL, and xzalloc().
Referenced by ls_main(), scan_one_dir(), and splitdnarray().
ls_main()
int ls_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1064 of file ls.c.
 {   /*      ^^^^^^^^^^^^^^^^^ note: if FTPD, argc can be wrong, see ftpd.c */
     struct dnode **dnd;
     struct dnode **dnf;
     struct dnode **dnp;
     struct dnode *dn;
     struct dnode *cur;
     unsigned opt;
     unsigned nfiles;
     unsigned dnfiles;
     unsigned dndirs;
     unsigned i;
 #if ENABLE_FEATURE_LS_COLOR
     /* colored LS support by JaWi, janwillem.janssen@lxtreme.nl */
     /* coreutils 6.10:
      * # ls --color=BOGUS
      * ls: invalid argument 'BOGUS' for '--color'
      * Valid arguments are:
      * 'always', 'yes', 'force'
      * 'never', 'no', 'none'
      * 'auto', 'tty', 'if-tty'
      * (and substrings: "--color=alwa" work too)
      */
     static const char color_str[] ALIGN1 =
         "always\0""yes\0""force\0"
         "auto\0""tty\0""if-tty\0";
     /* need to initialize since --color has _an optional_ argument */
     const char *color_opt = color_str; /* "always" */
 #endif
 #if ENABLE_LONG_OPTS
     static const char ls_longopts[] ALIGN1 =
         "full-time\0" No_argument "\xff"
         "group-directories-first\0" No_argument "\xfe"
         IF_FEATURE_LS_COLOR("color\0" Optional_argument "\xfd")
     ;
 #endif
     INIT_G();
     init_unicode();
 #if ENABLE_FEATURE_LS_WIDTH
     /* obtain the terminal width */
     G_terminal_width = get_terminal_width(STDIN_FILENO);
     /* go one less... */
     G_terminal_width--;
 #endif
     /* process options */
     opt = getopt32long(argv, "^"
         ls_options
             "\0"
             /* -n and -g imply -l */
             "nl:gl"
             /* --full-time implies -l */
             IF_FEATURE_LS_TIMESTAMPS(IF_LONG_OPTS(":\xff""l"))
             /* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html:
              * in some pairs of opts, only last one takes effect:
              */
             IF_FEATURE_LS_TIMESTAMPS(IF_FEATURE_LS_SORTFILES(":t-S:S-t")) /* time/size */
             // ":m-l:l-m" - we don't have -m
             IF_FEATURE_LS_FOLLOWLINKS(":H-L:L-H")
             ":C-xl:x-Cl:l-xC" /* bycols/bylines/long */
             ":C-1:1-C" /* bycols/oneline */
             ":x-1:1-x" /* bylines/oneline (not in SuS, but in GNU coreutils 8.4) */
             IF_FEATURE_LS_TIMESTAMPS(":c-u:u-c") /* mtime/atime */
             /* -w NUM: */
             IF_FEATURE_LS_WIDTH(":w+")
         , ls_longopts
         IF_FEATURE_LS_WIDTH(, /*-T*/ NULL, /*-w*/ &G_terminal_width)
         IF_FEATURE_LS_COLOR(, &color_opt)
     );
 #if 0 /* option bits debug */
     bb_error_msg("opt:0x%08x l:%x H:%x color:%x dirs:%x", opt, OPT_l, OPT_H, OPT_color, OPT_dirs_first);
     if (opt & OPT_c         ) bb_error_msg("-c");
     if (opt & OPT_l         ) bb_error_msg("-l");
     if (opt & OPT_H         ) bb_error_msg("-H");
     if (opt & OPT_color     ) bb_error_msg("--color");
     if (opt & OPT_dirs_first) bb_error_msg("--group-directories-first");
     if (opt & OPT_full_time ) bb_error_msg("--full-time");
     exit(0);
 #endif
 #if ENABLE_SELINUX
     if (opt & OPT_Z) {
         if (!is_selinux_enabled())
             option_mask32 &= ~OPT_Z;
     }
 #endif
 #if ENABLE_FEATURE_LS_COLOR
     /* set G_show_color = 1/0 */
     if (ENABLE_FEATURE_LS_COLOR_IS_DEFAULT && !is_TERM_dumb()) {
         char *p = getenv("LS_COLORS");
         /* LS_COLORS is unset, or (not empty && not "none") ? */
         if (!p || (p[0] && strcmp(p, "none") != 0)) {
             if (isatty(STDOUT_FILENO)) {
                 /* check isatty() last because it's expensive (syscall) */
                 G_show_color = 1;
             }
         }
     }
     if (opt & OPT_color) {
         if (color_opt[0] == 'n')
             G_show_color = 0;
         else switch (index_in_substrings(color_str, color_opt)) {
         case 3:
         case 4:
         case 5:
             if (!is_TERM_dumb() && isatty(STDOUT_FILENO)) {
         case 0:
         case 1:
         case 2:
                 G_show_color = 1;
             }
         }
     }
 #endif
     /* sort out which command line options take precedence */
     if (ENABLE_FEATURE_LS_RECURSIVE && (opt & OPT_d))
         option_mask32 &= ~OPT_R;    /* no recurse if listing only dir */
     if (!(opt & OPT_l)) { /* not -l? */
         if (ENABLE_FEATURE_LS_TIMESTAMPS && ENABLE_FEATURE_LS_SORTFILES) {
             /* when to sort by time? -t[cu] sorts by time even with -l */
             /* (this is achieved by opt_flags[] element for -t) */
             /* without -l, bare -c or -u enable sort too */
             /* (with -l, bare -c or -u just select which time to show) */
             if (opt & (OPT_c|OPT_u)) {
                 option_mask32 |= OPT_t;
             }
         }
     }
     /* choose a display format if one was not already specified by an option */
     if (!(option_mask32 & (OPT_l|OPT_1|OPT_x|OPT_C)))
         option_mask32 |= (isatty(STDOUT_FILENO) ? OPT_C : OPT_1);
     if (ENABLE_FTPD && applet_name[0] == 'f') {
         /* ftpd secret backdoor. dirs first are much nicer */
         option_mask32 |= OPT_dirs_first;
     }
     argv += optind;
     if (!argv[0])
         *--argv = (char*)".";
     if (argv[1])
         G.show_dirname = 1; /* 2 or more items? label directories */
     /* stuff the command line file names into a dnode array */
     dn = NULL;
     nfiles = 0;
     do {
         cur = my_stat(*argv, *argv,
             /* follow links on command line unless -l, -i, -s or -F: */
             !(option_mask32 & (OPT_l|OPT_i|OPT_s|OPT_F))
             /* ... or if -H: */
             || (option_mask32 & OPT_H)
             /* ... or if -L, but my_stat always follows links if -L */
         );
         argv++;
         if (!cur)
             continue;
         /*cur->fname_allocated = 0; - already is */
         cur->dn_next = dn;
         dn = cur;
         nfiles++;
     } while (*argv);
     /* nfiles _may_ be 0 here - try "ls doesnt_exist" */
     if (nfiles == 0)
         return G.exit_code;
     /* now that we know how many files there are
      * allocate memory for an array to hold dnode pointers
      */
     dnp = dnalloc(nfiles);
     for (i = 0; /* i < nfiles - detected via !dn below */; i++) {
         dnp[i] = dn;    /* save pointer to node in array */
         dn = dn->dn_next;
         if (!dn)
             break;
     }
     if (option_mask32 & OPT_d) {
         sort_and_display_files(dnp, nfiles);
     } else {
         dnd = splitdnarray(dnp, SPLIT_DIR);
         dnf = splitdnarray(dnp, SPLIT_FILE);
         dndirs = count_dirs(dnp, SPLIT_DIR);
         dnfiles = nfiles - dndirs;
         if (dnfiles > 0) {
             sort_and_display_files(dnf, dnfiles);
             if (ENABLE_FEATURE_CLEAN_UP)
                 free(dnf);
         }
         if (dndirs > 0) {
             dnsort(dnd, dndirs);
             scan_and_display_dirs_recur(dnd, dnfiles == 0);
             if (ENABLE_FEATURE_CLEAN_UP)
                 free(dnd);
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         dfree(dnp);
     return G.exit_code;
 }
References ALIGN1, applet_name, argv, bb_error_msg(), count_dirs(), cur, dfree, dnode::dn_next, dnalloc(), dnsort, exit(), free, G, G_show_color, G_terminal_width, get_terminal_width(), getenv, getopt32long, i, index_in_substrings(), INIT_G, init_unicode, is_TERM_dumb(), isatty(), ls_options, my_stat(), No_argument, NULL, opt, OPT_1, OPT_C, OPT_c, OPT_color, OPT_d, OPT_dirs_first, OPT_F, OPT_full_time, OPT_H, OPT_i, OPT_l, OPT_R, OPT_s, OPT_t, OPT_u, OPT_x, OPT_Z, optind, option_mask32, Optional_argument, p, scan_and_display_dirs_recur(), sort_and_display_files, SPLIT_DIR, SPLIT_FILE, splitdnarray(), STDIN_FILENO, STDOUT_FILENO, and strcmp.
Referenced by ftpd_main(), and popen_ls().
my_stat()
static struct dnode* my_stat (const char * fullname, const char * name, int force_follow) static
Definition at line 704 of file ls.c.
 {
     struct stat statbuf;
     struct dnode *cur;
     cur = xzalloc(sizeof(*cur));
     cur->fullname = fullname;
     cur->name = name;
     if ((option_mask32 & OPT_L) || force_follow) {
 #if ENABLE_SELINUX
         if (option_mask32 & OPT_Z) {
             getfilecon(fullname, &cur->sid);
         }
 #endif
         if (stat(fullname, &statbuf)) {
             bb_simple_perror_msg(fullname);
             G.exit_code = EXIT_FAILURE;
             free(cur);
             return NULL;
         }
         cur->dn_mode_stat = statbuf.st_mode;
     } else {
 #if ENABLE_SELINUX
         if (option_mask32 & OPT_Z) {
             lgetfilecon(fullname, &cur->sid);
         }
 #endif
         if (lstat(fullname, &statbuf)) {
             bb_simple_perror_msg(fullname);
             G.exit_code = EXIT_FAILURE;
             free(cur);
             return NULL;
         }
         cur->dn_mode_lstat = statbuf.st_mode;
     }
     /* cur->dstat = statbuf: */
     cur->dn_mode   = statbuf.st_mode  ;
     cur->dn_size   = statbuf.st_size  ;
 #if ENABLE_FEATURE_LS_TIMESTAMPS || ENABLE_FEATURE_LS_SORTFILES
     cur->dn_time   = statbuf.st_mtime ;
     if (option_mask32 & OPT_u)
         cur->dn_time = statbuf.st_atime;
     if (option_mask32 & OPT_c)
         cur->dn_time = statbuf.st_ctime;
 #endif
     cur->dn_ino    = statbuf.st_ino   ;
     cur->dn_blocks = statbuf.st_blocks;
     cur->dn_nlink  = statbuf.st_nlink ;
     cur->dn_uid    = statbuf.st_uid   ;
     cur->dn_gid    = statbuf.st_gid   ;
     cur->dn_rdev_maj = major(statbuf.st_rdev);
     cur->dn_rdev_min = minor(statbuf.st_rdev);
     return cur;
 }
References bb_simple_perror_msg(), cur, EXIT_FAILURE, free, dnode::fullname, G, lstat, major, minor, dnode::name, NULL, OPT_c, OPT_L, OPT_u, OPT_Z, option_mask32, stat::st_blocks, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, stat(), and xzalloc().
Referenced by ls_main(), and scan_one_dir().
print_name()
static unsigned print_name (const char * name) static
Definition at line 447 of file ls.c.
 {
     unsigned len;
     uni_stat_t uni_stat;
     // TODO: quote tab as \t, etc, if -Q
     name = printable_string2(&uni_stat, name);
     if (!(option_mask32 & OPT_Q)) {
         fputs_stdout(name);
         return uni_stat.unicode_width;
     }
     len = 2 + uni_stat.unicode_width;
     putchar('"');
     while (*name) {
         if (*name == '"' || *name == '\\') {
             putchar('\\');
             len++;
         }
         putchar(*name);
         name++;
     }
     putchar('"');
     return len;
 }
References fputs_stdout(), OPT_Q, option_mask32, printable_string2(), putchar, and uni_stat_t::unicode_width.
Referenced by display_single().
scan_and_display_dirs_recur()
static void scan_and_display_dirs_recur (struct dnode ** dn, int first) static
Definition at line 1012 of file ls.c.
 {
     unsigned nfiles;
     struct dnode **subdnp;
     for (; *dn; dn++) {
         if (G.show_dirname || (option_mask32 & OPT_R)) {
             if (!first)
                 bb_putchar('\n');
             first = 0;
             printf("%s:\n", (*dn)->fullname);
         }
         subdnp = scan_one_dir((*dn)->fullname, &nfiles);
 #if ENABLE_DESKTOP
         if (option_mask32 & (OPT_s|OPT_l)) {
             if (option_mask32 & OPT_h) {
                 printf("total %-"HUMAN_READABLE_MAX_WIDTH_STR"s\n",
                     /* print size, no fractions, use suffixes */
                     make_human_readable_str(calculate_blocks(subdnp) * 1024,
                                 0, 0)
                 );
             } else {
                 printf("total %"OFF_FMT"u\n", calculate_blocks(subdnp));
             }
         }
 #endif
         if (nfiles > 0) {
             /* list all files at this level */
             sort_and_display_files(subdnp, nfiles);
             if (ENABLE_FEATURE_LS_RECURSIVE
              && (option_mask32 & OPT_R)
             ) {
                 struct dnode **dnd;
                 unsigned dndirs;
                 /* recursive - list the sub-dirs */
                 dnd = splitdnarray(subdnp, SPLIT_SUBDIR);
                 dndirs = count_dirs(subdnp, SPLIT_SUBDIR);
                 if (dndirs > 0) {
                     dnsort(dnd, dndirs);
                     scan_and_display_dirs_recur(dnd, 0);
                     /* free the array of dnode pointers to the dirs */
                     free(dnd);
                 }
             }
             /* free the dnodes and the fullname mem */
             dfree(subdnp);
         }
     }
 }
References bb_putchar(), count_dirs(), dfree, dnsort, first, free, G, HUMAN_READABLE_MAX_WIDTH_STR, make_human_readable_str(), OFF_FMT, OPT_h, OPT_l, OPT_R, OPT_s, option_mask32, printf(), scan_one_dir(), sort_and_display_files, SPLIT_SUBDIR, and splitdnarray().
Referenced by ls_main().
scan_one_dir()
static struct dnode** scan_one_dir (const char * path, unsigned * nfiles_p) static
Definition at line 924 of file ls.c.
 {
     struct dnode *dn, *cur, **dnp;
     struct dirent *entry;
     DIR *dir;
     unsigned i, nfiles;
     *nfiles_p = 0;
     dir = warn_opendir(path);
     if (dir == NULL) {
         G.exit_code = EXIT_FAILURE;
         return NULL;    /* could not open the dir */
     }
     dn = NULL;
     nfiles = 0;
     while ((entry = readdir(dir)) != NULL) {
         char *fullname;
         /* are we going to list the file- it may be . or .. or a hidden file */
         if (entry->d_name[0] == '.') {
             if (!(option_mask32 & (OPT_a|OPT_A)))
                 continue; /* skip all dotfiles if no -a/-A */
             if (!(option_mask32 & OPT_a)
              && (!entry->d_name[1] || (entry->d_name[1] == '.' && !entry->d_name[2]))
             ) {
                 continue; /* if only -A, skip . and .. but show other dotfiles */
             }
         }
         fullname = concat_path_file(path, entry->d_name);
         cur = my_stat(fullname, bb_basename(fullname), 0);
         if (!cur) {
             free(fullname);
             continue;
         }
         cur->fname_allocated = 1;
         cur->dn_next = dn;
         dn = cur;
         nfiles++;
     }
     closedir(dir);
     if (dn == NULL)
         return NULL;
     /* now that we know how many files there are
      * allocate memory for an array to hold dnode pointers
      */
     *nfiles_p = nfiles;
     dnp = dnalloc(nfiles);
     for (i = 0; /* i < nfiles - detected via !dn below */; i++) {
         dnp[i] = dn;    /* save pointer to node in array */
         dn = dn->dn_next;
         if (!dn)
             break;
     }
     return dnp;
 }
References bb_basename(), closedir(), concat_path_file(), cur, dir, dnode::dn_next, dnalloc(), EXIT_FAILURE, free, G, i, my_stat(), NULL, OPT_a, OPT_A, option_mask32, readdir(), and warn_opendir().
Referenced by scan_and_display_dirs_recur().
splitdnarray()
static struct dnode** splitdnarray (struct dnode ** dn, int which) static
Definition at line 820 of file ls.c.
 {
     unsigned dncnt, d;
     struct dnode **dnp;
     if (dn == NULL)
         return NULL;
     /* count how many dirs or files there are */
     dncnt = count_dirs(dn, which);
     /* allocate a file array and a dir array */
     dnp = dnalloc(dncnt);
     /* copy the entrys into the file or dir array */
     for (d = 0; *dn; dn++) {
         if (S_ISDIR((*dn)->dn_mode)) {
             const char *name;
             if (which == SPLIT_FILE)
                 continue;
             name = (*dn)->name;
             if ((which & SPLIT_DIR) /* any dir... */
             /* ... or not . or .. */
              || name[0] != '.'
              || (name[1] && (name[1] != '.' || name[2]))
             ) {
                 dnp[d++] = *dn;
             }
         } else
         if (which == SPLIT_FILE) {
             dnp[d++] = *dn;
         }
     }
     return dnp;
 }
References count_dirs(), dnalloc(), dnode::name, NULL, S_ISDIR, SPLIT_DIR, and SPLIT_FILE.
Referenced by ls_main(), and scan_and_display_dirs_recur().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING