Fennix: Kernel/kshell/cmds.hpp File Reference
cmds.hpp File Reference
#include <types.h>
Macros
#define IF_ARG(x) strcmp(args, x) == 0
Functions
void cmd_clear (const char *args)
void cmd_echo (const char *args)
void cmd_ls (const char *args)
void cmd_tree (const char *args)
void cmd_cd (const char *args)
void cmd_cat (const char *args)
void cmd_ps (const char *args)
void cmd_uptime (const char *args)
void cmd_whoami (const char *args)
void cmd_uname (const char *args)
void cmd_mem (const char *args)
void cmd_kill (const char *args)
void cmd_killall (const char *args)
void cmd_top (const char *args)
void cmd_exit (const char *args)
void cmd_shutdown (const char *args)
void cmd_reboot (const char *args)
void cmd_lspci (const char *args)
void cmd_lsacpi (const char *args)
void cmd_lsmod (const char *args)
void cmd_modinfo (const char *args)
void cmd_panic (const char *args)
void cmd_dump (const char *args)
void cmd_theme (const char *args)
Macro Definition Documentation
IF_ARG
#define IF_ARG (x) strcmp(args, x) == 0
Definition at line 48 of file cmds.hpp.
Function Documentation
cmd_cat()
void cmd_cat (const char * args)
Definition at line 26 of file cat.cpp.
 {
     if (args[0] == '\0')
         return;
     FileNode *node = fs->GetByPath(args, nullptr);
     if (node == nullptr)
     {
         printf("cat: %s: No such file or directory\n", args);
         return;
     }
     if (!node->IsRegularFile() && !node->IsCharacterDevice())
     {
         printf("cat: %s: Not a regular file or character device\n", args);
         return;
     }
     if (node->IsCharacterDevice())
     {
         printf("cat: %s: Character devices are not supported yet\n", args);
         return;
     }
     kstat stat = {};
     node->Stat(&stat);
     uint8_t *buffer = new uint8_t[stat.Size + 1];
     ssize_t rBytes = node->Read(buffer, stat.Size, 0);
     if (rBytes > 0)
         printf("%s\n", buffer);
     else
         printf("cat: %s: Could not read file\n", args);
     delete[] buffer;
 }
References fs, vfs::Virtual::GetByPath(), and printf.
cmd_cd()
void cmd_cd (const char * args)
Definition at line 26 of file cd.cpp.
 {
     if (args[0] == '\0')
         return;
     FileNode *node = fs->GetByPath(args, nullptr);
     if (node == nullptr)
     {
         printf("cd: %s: No such file or directory\n", args);
         return;
     }
     if (!node->IsDirectory())
     {
         printf("cd: %s: Not a directory\n", args);
         return;
     }
     thisProcess->CWD = node;
 }
References fs, vfs::Virtual::GetByPath(), printf, and thisProcess.
cmd_clear()
void cmd_clear (const char * args)
Definition at line 22 of file clear.cpp.
 {
     printf("\x1b[2J");
 }
References printf.
cmd_dump()
void cmd_dump (const char * args)
Definition at line 27 of file dump.cpp.
 {
     if (args[0] == '\0')
         return;
     // args == "0xdeadbeef 512" aka "address size"
     char *strAddr = (char *)args;
     char *strLen = (char *)args;
     while (*strLen != ' ')
         strLen++;
     *strLen = '\0';
     strLen++;
     void *Address = (void *)strtoul(strAddr, nullptr, 16);
     unsigned long Length = strtoul(strLen, nullptr, 10);
     {
         unsigned char *AddressChar = (unsigned char *)Address;
         unsigned char Buffer[17];
         uint32_t Iterate;
         printf("Dumping %lu bytes from %#lx\n", Length, (uintptr_t)AddressChar);
         for (Iterate = 0; Iterate < (uint32_t)Length; Iterate++)
         {
             if ((Iterate % 16) == 0)
             {
                 if (Iterate != 0)
                     printf("  %s\n", Buffer);
                 printf("  %04x ", Iterate);
             }
             printf(" %02x", AddressChar[Iterate]);
             if ((AddressChar[Iterate] < 0x20) || (AddressChar[Iterate] > 0x7E))
                 Buffer[Iterate % 16] = '.';
             else
                 Buffer[Iterate % 16] = AddressChar[Iterate];
             Buffer[(Iterate % 16) + 1] = '\0';
         }
         while ((Iterate % 16) != 0)
         {
             printf("   ");
             Iterate++;
         }
         putchar('\n');
     }
 }
References Address, vfs::Buffer, Length, printf, putchar(), and strtoul().
cmd_echo()
void cmd_echo (const char * args)
Definition at line 22 of file echo.cpp.
 {
     printf("%s\n", args);
 }
References printf.
cmd_exit()
void cmd_exit (const char * args)
Definition at line 28 of file exit.cpp.
 {
    KernelShutdownThread(false);
     // TaskManager->KillThread(thisThread, KILL_SUCCESS);
     CPU::Halt(true);
 }
References CPU::Halt(), and KernelShutdownThread().
cmd_kill()
void cmd_kill (const char * args)
Definition at line 28 of file kill.cpp.
 {
     PID pid = atoi(args);
     PCB *pcb = TaskManager->GetProcessByID(pid);
     if (pcb == nullptr)
     {
         printf("No process with PID %d\n", pid);
         return;
     }
     TaskManager->KillProcess(pcb, KILL_BY_OTHER_PROCESS);
 }
References atoi(), Tasking::Task::GetProcessByID(), Tasking::KILL_BY_OTHER_PROCESS, Tasking::Task::KillProcess(), pcb, printf, and TaskManager.
cmd_killall()
void cmd_killall (const char * args)
Definition at line 28 of file killall.cpp.
 {
     foreach (auto Proc in TaskManager->GetProcessList())
     {
         if (strcmp(Proc->Name, args) == 0)
         {
             TaskManager->KillProcess(Proc, KILL_BY_OTHER_PROCESS);
         }
     }
 }
References Tasking::Task::GetProcessList(), Tasking::KILL_BY_OTHER_PROCESS, Tasking::Task::KillProcess(), strcmp, and TaskManager.
cmd_ls()
void cmd_ls (const char * args)
Definition at line 107 of file ls.cpp.
 {
     if (args[0] == '\0')
     {
         FileNode *rootNode = thisProcess->CWD;
         if (rootNode == nullptr)
             rootNode = fs->GetRoot(0);
         PrintLS(rootNode);
         return;
     }
     FileNode *thisNode = fs->GetByPath(args, nullptr);
     if (thisNode == nullptr)
     {
         printf("ls: %s: No such file or directory\n", args);
         return;
     }
     if (!thisNode->IsDirectory())
     {
         printf("%s%s\n", ColorNodeType(thisNode), thisNode->Path.c_str());
         return;
     }
     PrintLS(thisNode);
 }
References ColorNodeType(), fs, vfs::Virtual::GetByPath(), vfs::Virtual::GetRoot(), FileNode::IsDirectory(), FileNode::Path, printf, and thisProcess.
cmd_lsacpi()
void cmd_lsacpi (const char * args)
Definition at line 27 of file lsacpi.cpp.
 {
     ACPI::ACPI *acpi = (ACPI::ACPI *)PowerManager->GetACPI();
     foreach (auto Table in acpi->Tables)
     {
         printf("%#lx: %.4s [%.6s:%.8s] %d bytes\n",
                (uintptr_t)Table.second,
                Table.second->Signature,
                Table.second->OEMID,
                Table.second->OEMTableID,
                Table.second->Length);
     }
 }
References Power::Power::GetACPI(), PowerManager, and printf.
cmd_lsmod()
void cmd_lsmod (const char * args)
Definition at line 22 of file lsmod.cpp.
 {
     std::unordered_map<dev_t, Driver::DriverObject> drivers =
         DriverManager->GetDrivers();
     printf("DRIVER          |    ID | INIT | MEMORY\n");
     foreach (auto &drv in drivers)
     {
         printf("%-15s | %5ld |  %s   | %ld KiB\n",
                drv.second.Name,
                drv.first,
                drv.second.Initialized ? "Y" : "N",
                TO_KiB(drv.second.vma->GetAllocatedMemorySize()));
     }
 }
References DriverManager, Driver::Manager::GetDrivers(), printf, and TO_KiB.
cmd_lspci()
void cmd_lspci (const char * args)
Definition at line 26 of file lspci.cpp.
 {
     if (args)
     {
         if (IF_ARG("-i") || IF_ARG("--info"))
         {
             foreach (auto Device in PCIManager->GetDevices())
             {
                 const char *HdrType;
                 switch (Device.Header->HeaderType)
                 {
                 case 0:
                     HdrType = "Normal ";
                     break;
                 case 1:
                     HdrType = "PCI-PCI";
                     break;
                 case 2:
                     HdrType = "Cardbus";
                     break;
                 default:
                     HdrType = "Unknown";
                     break;
                 }
                 printf("%04x:%04x | %s:%03d | %02x:%02x.%d | %s:  %s  %s\n",
                        Device.Header->VendorID,
                        Device.Header->DeviceID,
                        HdrType, Device.Header->HeaderType,
                        Device.Bus,
                        Device.Device,
                        Device.Function,
                        PCI::Descriptors::GetSubclassName(Device.Header->Class,
                                                          Device.Header->Subclass),
                        PCI::Descriptors::GetVendorName(Device.Header->VendorID),
                        PCI::Descriptors::GetDeviceName(Device.Header->VendorID,
                                                        Device.Header->DeviceID));
             }
             return;
         }
     }
     foreach (auto Device in PCIManager->GetDevices())
     {
         printf("%02x:%02x.%d: %s:  %s  %s\n",
                Device.Bus,
                Device.Device,
                Device.Function,
                PCI::Descriptors::GetSubclassName(Device.Header->Class,
                                                  Device.Header->Subclass),
                PCI::Descriptors::GetVendorName(Device.Header->VendorID),
                PCI::Descriptors::GetDeviceName(Device.Header->VendorID,
                                                Device.Header->DeviceID));
     }
 }
References PCI::Descriptors::GetDeviceName(), PCI::Manager::GetDevices(), PCI::Descriptors::GetSubclassName(), PCI::Descriptors::GetVendorName(), IF_ARG, PCIManager, and printf.
cmd_mem()
void cmd_mem (const char * args)
Definition at line 28 of file mem.cpp.
 {
     uint64_t total = KernelAllocator.GetTotalMemory();
     uint64_t used = KernelAllocator.GetUsedMemory();
     uint64_t free = KernelAllocator.GetFreeMemory();
     uint64_t reserved = KernelAllocator.GetReservedMemory();
     int usedPercent = (int)((used * 100) / total);
     int usedBar = (int)(usedPercent / 2);
     int reservedPercent = (int)((reserved * 100) / total);
     int reservedBar = (int)(reservedPercent / 2);
     printf("[");
     for (int i = 0; i < usedBar; i++)
         printf("=");
     for (int i = 0; i < 50 - usedBar; i++)
         printf(" ");
     printf("] %d%% Used\n", usedPercent);
     printf("[");
     for (int i = 0; i < reservedBar; i++)
         printf("=");
     for (int i = 0; i < 50 - reservedBar; i++)
         printf(" ");
     printf("] %d%% Reserved\n", reservedPercent);
     // printf("Total: %d MiB\n", (int)(TO_MiB(total)));
     // printf("Used: %d MiB\n", (int)(TO_MiB(used)));
     // printf("Free: %d MiB\n", (int)(TO_MiB(free)));
     // printf("Reserved: %d MiB\n", (int)(TO_MiB(reserved)));
     printf("TOTAL      USED      FREE      RESERVED\n");
     printf("%d MiB    %d MiB    %d MiB    %d MiB\n",
            (int)(TO_MiB(total)), (int)(TO_MiB(used)),
            (int)(TO_MiB(free)), (int)(TO_MiB(reserved)));
 }
References free, i, KernelAllocator, printf, TO_MiB, and total.
cmd_modinfo()
void cmd_modinfo (const char * args)
Definition at line 22 of file modinfo.cpp.
 {
     if (args[0] == '\0')
     {
         printf("Usage: modinfo <driver id/name>\n");
         return;
     }
     dev_t id = atoi(args);
     std::unordered_map<dev_t, Driver::DriverObject> drivers =
         DriverManager->GetDrivers();
     if (drivers.find(id) == drivers.end())
     {
         bool found = false;
         foreach (auto var in drivers)
         {
             if (strcmp(var.second.Name, args) == 0)
             {
                 id = var.first;
                 found = true;
                 break;
             }
         }
         if (!found)
         {
             printf("Driver not found\n");
             return;
         }
     }
     Driver::DriverObject drv = drivers[id];
     char drvVersion[32];
     snprintf(drvVersion, sizeof(drvVersion), "%d.%d.%d",
              drv.Version.Major, drv.Version.Minor, drv.Version.Patch);
     printf("Base Info:\n");
     printf(" Name: %s\n", drv.Name);
     printf(" Description: %s\n", drv.Description);
     printf(" Author: %s\n", drv.Author);
     printf(" Version: %s\n", drvVersion);
     printf(" License: %s\n", drv.License);
     printf("Resource Info:\n");
     printf(" Initialized: %s\n", drv.Initialized ? "yes" : "no");
     printf(" Error Code: %i (%s)\n", drv.ErrorCode, strerror(drv.ErrorCode));
     printf(" Path: %s\n", drv.Path.c_str());
     printf(" Used Memory: %ld KiB\n", TO_KiB(drv.vma->GetAllocatedMemorySize()));
     printf(" Used IRQs:%s\n", drv.InterruptHandlers->empty() ? " none" : "");
     foreach (auto var in *drv.InterruptHandlers)
     {
         printf("  IRQ%-2d: %#lx\n",
                var.first, (uintptr_t)var.second);
     }
 }
References atoi(), Driver::DriverObject::Author, Driver::DriverObject::Description, dev_t, DriverManager, Driver::DriverObject::ErrorCode, Memory::VirtualMemoryArea::GetAllocatedMemorySize(), Driver::Manager::GetDrivers(), Driver::DriverObject::Initialized, Driver::DriverObject::InterruptHandlers, Driver::DriverObject::License, Driver::DriverObject::Name, Driver::DriverObject::Path, printf, snprintf(), strcmp, strerror(), TO_KiB, Driver::DriverObject::Version, and Driver::DriverObject::vma.
cmd_panic()
void cmd_panic (const char * args)
Definition at line 26 of file panic.cpp.
 {
     asmv("int $0x0");
     __unreachable;
 }
References __unreachable, and asmv().
cmd_ps()
void cmd_ps (const char * args)
Definition at line 28 of file ps.cpp.
 {
     printf("PID  Name\n");
     foreach (auto p in TaskManager->GetProcessList())
         printf("%d   %s\n", p->ID, p->Name);
 }
References Tasking::Task::GetProcessList(), p, printf, and TaskManager.
cmd_reboot()
void cmd_reboot (const char * args)
Definition at line 28 of file reboot.cpp.
 {
     KernelShutdownThread(true);
     CPU::Halt(true);
 }
References CPU::Halt(), and KernelShutdownThread().
cmd_shutdown()
void cmd_shutdown (const char * args)
Definition at line 28 of file shutdown.cpp.
 {
     KernelShutdownThread(false);
     CPU::Halt(true);
 }
References CPU::Halt(), and KernelShutdownThread().
cmd_theme()
void cmd_theme (const char * args)
Definition at line 22 of file theme.cpp.
 {
     KernelConsole::SetTheme(args);
 }
References KernelConsole::SetTheme().
cmd_top()
void cmd_top (const char * args)
Definition at line 43 of file top.cpp.
 {
     printf("PID    Name                State    Priority    Memory Usage    CPU Usage\n");
     foreach (auto Proc in TaskManager->GetProcessList())
     {
 #if defined(a64)
         printf("%-4d %-20s %s       %d           %ld KiB         %ld\n",
                Proc->ID, Proc->Name, TaskStateStrings[Proc->State.load()],
                Proc->Info.Priority, TO_KiB(Proc->GetSize()),
                Proc->Info.UserTime + Proc->Info.KernelTime);
 #elif defined(a32)
         printf("%-4d %-20s %s       %d           %lld KiB         %lld\n",
                Proc->ID, Proc->Name, TaskStateStrings[Proc->State.load()],
                Proc->Info.Priority, TO_KiB(Proc->GetSize()),
                Proc->Info.UserTime + Proc->Info.KernelTime);
 #endif
         foreach (auto Thrd in Proc->Threads)
         {
 #if defined(a64)
             printf(" %-4d %-20s %s       %d           %ld KiB         %ld\n",
                    Thrd->ID, Thrd->Name, TaskStateStrings[Thrd->State.load()],
                    Thrd->Info.Priority, TO_KiB(Thrd->GetSize()),
                    Thrd->Info.UserTime + Thrd->Info.KernelTime);
 #elif defined(a32)
             printf(" %-4d %-20s %s       %d           %lld KiB         %lld\n",
                    Thrd->ID, Thrd->Name, TaskStateStrings[Thrd->State.load()],
                    Thrd->Info.Priority, TO_KiB(Thrd->GetSize()),
                    Thrd->Info.UserTime + Thrd->Info.KernelTime);
 #endif
         }
     }
 }
References Tasking::Task::GetProcessList(), printf, TaskManager, TaskStateStrings, and TO_KiB.
cmd_tree()
void cmd_tree (const char * args)
Definition at line 81 of file tree.cpp.
 {
     FileNode *rootNode = thisProcess->CWD;
     if (args[0] == '\0')
     {
         if (rootNode == nullptr)
             rootNode = fs->GetRoot(0);
     }
     else
     {
         rootNode = fs->GetByPath(args, nullptr);
         if (rootNode == nullptr)
         {
             printf("ls: %s: No such file or directory\n", args);
             return;
         }
     }
     printf("%s\n", rootNode->Name.c_str());
     tree_loop(rootNode);
 }
References fs, vfs::Virtual::GetByPath(), vfs::Virtual::GetRoot(), FileNode::Name, printf, thisProcess, and tree_loop().
cmd_uname()
void cmd_uname (const char * args)
Definition at line 26 of file uname.cpp.
 {
     if (args)
     {
         if (IF_ARG("-a") || IF_ARG("--all"))
         {
             printf("Fennix Kernel %s %s %s %s\n",
                    KERNEL_VERSION, KERNEL_NAME, __DATE__,
                    KERNEL_ARCH);
         }
         else if (IF_ARG("-s") || IF_ARG("--kernel-name"))
         {
             printf("%s\n", KERNEL_NAME);
         }
         else if (IF_ARG("-v") || IF_ARG("--kernel-version"))
         {
             printf("%s\n", KERNEL_VERSION);
         }
         else if (IF_ARG("-n") || IF_ARG("--nodename"))
         {
             printf("unknown\n");
         }
         else if (IF_ARG("-r") || IF_ARG("--kernel-release"))
         {
             printf("%s\n", KERNEL_NAME);
         }
         else if (IF_ARG("-m") || IF_ARG("--machine"))
         {
             printf("%s\n", KERNEL_ARCH);
         }
         else
         {
             printf("uname: invalid option: %s\n", args);
         }
     }
     else
     {
         printf("Fennix Kernel\n");
     }
 }
References IF_ARG, and printf.
cmd_uptime()
void cmd_uptime (const char * args)
Definition at line 26 of file uptime.cpp.
 {
     if (TimeManager)
     {
         uint64_t Nanoseconds =
             TimeManager->GetNanosecondsSinceClassCreation();
         uint64_t Seconds = Nanoseconds / 10000000;
         uint64_t Minutes = Seconds / 60;
         uint64_t Hours = Minutes / 60;
         uint64_t Days = Hours / 24;
         debug("Nanoseconds: %ld", Nanoseconds);
         Seconds %= 60;
         Minutes %= 60;
         Hours %= 24;
 #if defined(a64)
         printf("%ld days, %ld hours, %ld minutes, %ld %s\n",
                Days, Hours, Minutes, Seconds,
                Seconds == 1 ? "second" : "seconds");
 #elif defined(a32)
         printf("%lld days, %lld hours, %lld minutes, %lld %s\n",
                Days, Hours, Minutes, Seconds,
                Seconds == 1 ? "second" : "seconds");
 #endif
     }
     else
     {
         printf("Could not get uptime\n");
     }
 }
References Time::Days, debug, Time::time::GetNanosecondsSinceClassCreation(), Time::Hours, Time::Minutes, Time::Nanoseconds, printf, Time::Seconds, and TimeManager.
cmd_whoami()
void cmd_whoami (const char * args)
Definition at line 26 of file whoami.cpp.
 {
     printf("kernel\n");
 }
References printf.