Fennix Userspace: Userspace/musl/src/dirent/readdir.c File Reference
readdir.c File Reference
#include <dirent.h>
#include <errno.h>
#include <stddef.h>
#include "__dirent.h"
#include "syscall.h"
Typedefs
typedef char dirstream_buf_alignment_check[1-2 *(int) (offsetof(struct __dirstream, buf) % sizeof(off_t))]
Functions
struct dirent * readdir (DIR *dir)
Typedef Documentation
dirstream_buf_alignment_check
typedef char dirstream_buf_alignment_check[1-2 *(int)(offsetof(struct __dirstream, buf) % sizeof(off_t))]
Definition at line 7 of file readdir.c.
Function Documentation
readdir()
struct dirent* readdir (DIR * dir)
Definition at line 10 of file readdir.c.
 {
     struct dirent *de;
     if (dir->buf_pos >= dir->buf_end) {
         int len = __syscall(SYS_getdents, dir->fd, dir->buf, sizeof dir->buf);
         if (len <= 0) {
             if (len < 0 && len != -ENOENT) errno = -len;
             return 0;
         }
         dir->buf_end = len;
         dir->buf_pos = 0;
     }
     de = (void *)(dir->buf + dir->buf_pos);
     dir->buf_pos += de->d_reclen;
     dir->tell = de->d_off;
     return de;
 }
References __syscall, __dirstream::buf, __dirstream::buf_end, __dirstream::buf_pos, dirent::d_off, dirent::d_reclen, ENOENT, errno, __dirstream::fd, and __dirstream::tell.
Referenced by do_glob(), do_nftw(), readdir_r(), scandir(), and test_dirent().