Fennix Userspace: Userspace/musl/src/ipc/semctl.c File Reference
semctl.c File Reference
#include <sys/sem.h>
#include <stdarg.h>
#include <endian.h>
#include "syscall.h"
#include "ipc.h"
Data Structures
union semun
Functions
int semctl (int id, int num, int cmd,...)
Data Structure Documentation
semun
union semun
Definition at line 11 of file semctl.c.
Data Fields
unsigned short * array
struct semid_ds * buf
int val
Function Documentation
semctl()
int semctl (int id, int num, int cmd, ...)
Definition at line 17 of file semctl.c.
 {
     union semun arg = {0};
     va_list ap;
     switch (cmd & ~IPC_TIME64) {
     case SETVAL: case GETALL: case SETALL: case IPC_SET:
     case IPC_INFO: case SEM_INFO:
     case IPC_STAT & ~IPC_TIME64:
     case SEM_STAT & ~IPC_TIME64:
     case SEM_STAT_ANY & ~IPC_TIME64:
         va_start(ap, cmd);
         arg = va_arg(ap, union semun);
         va_end(ap);
     }
 #if IPC_TIME64
     struct semid_ds out, *orig;
     if (cmd&IPC_TIME64) {
         out = (struct semid_ds){0};
         orig = arg.buf;
         arg.buf = &out;
     }
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     struct semid_ds tmp;
     if (cmd == IPC_SET) {
         tmp = *arg.buf;
         tmp.sem_perm.mode *= 0x10000U;
         arg.buf = &tmp;
     }
 #endif
 #ifndef SYS_ipc
     int r = __syscall(SYS_semctl, id, num, IPC_CMD(cmd), arg.buf);
 #else
     int r = __syscall(SYS_ipc, IPCOP_semctl, id, num, IPC_CMD(cmd), &arg.buf);
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     if (r >= 0) switch (cmd | IPC_TIME64) {
     case IPC_STAT:
     case SEM_STAT:
     case SEM_STAT_ANY:
         arg.buf->sem_perm.mode >>= 16;
     }
 #endif
 #if IPC_TIME64
     if (r >= 0 && (cmd&IPC_TIME64)) {
         arg.buf = orig;
         *arg.buf = out;
         IPC_HILO(arg.buf, sem_otime);
         IPC_HILO(arg.buf, sem_ctime);
     }
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), GETALL, IPC_CMD, IPC_HILO, IPC_INFO, IPC_SET, IPC_STAT, IPC_TIME64, IPCOP_semctl, ipc_perm::mode, out(), r, semid_ds::sem_ctime, SEM_INFO, semid_ds::sem_otime, semid_ds::sem_perm, SEM_STAT, SEM_STAT_ANY, SETALL, SETVAL, va_arg, va_end(), and va_start().