Fennix: Userspace/mlibc/options/lsb/generic/dso_exit.cpp File Reference
dso_exit.cpp File Reference
#include <string.h>
#include <bits/ensure.h>
#include <mlibc/allocator.hpp>
#include <frg/eternal.hpp>
#include <frg/vector.hpp>
Data Structures
struct ExitHandler
Typedefs
using ExitQueue = frg::vector< ExitHandler, MemoryAllocator >
Functions
ExitQueue & getExitQueue ()
int __cxa_atexit (void(*function)(void *), void *argument, void *handle)
void __mlibc_do_finalize ()
Typedef Documentation
ExitQueue
using ExitQueue = frg::vector<ExitHandler, MemoryAllocator>
Definition at line 17 of file dso_exit.cpp.
Function Documentation
__cxa_atexit()
int __cxa_atexit (void(*)(void *) function, void * argument, void * handle)
Definition at line 26 of file dso_exit.cpp.
{
     ExitHandler handler;
     handler.function = function;
     handler.argument = argument;
     handler.dsoHandle = handle;
     getExitQueue().push(handler);
     return 0;
 }
References getExitQueue(), and handler().
Referenced by atexit().
__mlibc_do_finalize()
void __mlibc_do_finalize ()
Definition at line 35 of file dso_exit.cpp.
{
     ExitQueue &eq = getExitQueue();
     for(size_t i = eq.size(); i > 0; i--) {
         auto handler = &eq[i - 1];
         handler->function(handler->argument);
     }
 }
References getExitQueue(), handler(), and i.
Referenced by exit().
getExitQueue()
ExitQueue& getExitQueue ()
Definition at line 19 of file dso_exit.cpp.
{
     // use frg::eternal to prevent the compiler from scheduling the destructor
     // by generating a call to __cxa_atexit().
     static frg::eternal<ExitQueue> singleton(getAllocator());
     return singleton.get();
 }
References getAllocator().
Referenced by __cxa_atexit(), and __mlibc_do_finalize().