Fennix Userspace: Userspace/apps/base/bash/lib/sh/memset.c File Reference
memset.c File Reference
Functions
char * memset (char *str, int c, unsigned int len)
Function Documentation
memset()
char* memset (char * str, int c, unsigned int len)
Definition at line 22 of file memset.c.
 {
   register char *st = str;
   while (len-- > 0)
     *st++ = c;
   return str;
 }
References c, and str.
Referenced by __crypt_blowfish(), __fdopen(), __fopen_rb_ca(), __membarrier(), __netlink_enumerate(), __nscd_query(), __pthread_create(), __res_mkquery(), __res_msend_rc(), __reset_tls(), __stpncpy(), __synccall(), _rl_insert_char(), _rl_strpbrk(), accept_builtin(), add_lease(), adjtimex_main(), allocate(), AM_clearFB(), arp_del(), arp_set(), arpping(), bb_ask_noecho(), bb_displayroutes(), bb_progress_update(), bb_signals_norestart(), binop(), blank_string(), build_row(), BuildNewTic(), bzero(), calloc(), char_insert(), chattr_main(), check(), chksum_and_xwrite_tar_header(), clear_if_addr(), clear_leases(), clear_partition(), collect_cpu(), colon(), common64_end(), complete_fncmp(), compute_lcd_of_matches(), config_read(), convert_to_struct(), cprint_init(), create_socket(), curve25519(), cutbytes(), cutchars(), cutfields(), d4_recv_raw_packet(), d6_listen_socket(), d6_raw_socket(), d6_recv_kernel_packet(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), data_extract_to_command(), day_array(), dbg_print_flags(), dbg_print_ptype(), dbg_print_stype(), dd_main(), depmod_main(), detect_link_wlan(), DG_Init(), do_add_or_delete(), do_cmd(), do_getaffinity(), do_lzo_compress(), do_tunnels_list(), docolon(), donate(), done_command(), dump(), dump_bad(), ether_wake_main(), explicit_bzero(), expr_alloc_comp(), expr_alloc_one(), expr_alloc_symbol(), expr_alloc_two(), fbset_main(), file_lookup(), fill_pkt_header(), fill_row(), find_match(), FixDayDow(), flashcp_main(), fmemopen(), fnprint(), fnwidth(), fopencookie(), format_line(), fstrim_main(), G_BuildTiccmd(), G_DoLoadLevel(), G_PlayerFinishLevel(), G_PlayerReborn(), gen_netmask(), GenerateTextureHashTable(), get(), get_addr_1(), get_address(), get_cpu_statistics(), get_dev_fields(), get_drv_info(), get_header_cpio(), get_history_event(), get_prefix_1(), get_subst_pattern(), get_termios_and_make_raw(), get_word_from_string(), getifaddrs(), GetSectorAtNullAddress(), grep_file(), history_expand(), history_expand_internal(), huft_build(), I_Error(), I_InitGraphics(), I_Stretch5x(), IF_DESKTOP(), if_fetch(), if_nameindex(), INET_setroute(), inetd_main(), init_cancellation(), init_d6_packet(), init_main(), init_text_buffer(), init_transformer_state(), initialize_context(), internal_calloc(), iostat_main(), ipaddr_list_or_flush(), ipaddr_modify(), ipaddr_reset_filter(), ipneigh_reset_filter(), iproute_get(), iproute_modify(), iproute_reset_filter(), iprule_modify(), ll_remember_index(), lm_init(), LoadResponseFile(), lpd_main(), M_ExtractFileBase(), main_loop(), mainSort(), make_bad_inode(), make_device(), makejob(), mal0_clear(), map_library(), mbschr(), md5_crypt(), md5_end(), md5_transform(), menu_add_entry(), mini_httpd_inetd(), mkfs_ext2_main(), mkfs_reiser_main(), mkfs_vfat_main(), mmap_fixed(), mount_main(), mpstat_main(), ms_write(), nameif_main(), nandwrite_main(), netlink_msg_to_ifaddr(), new_fd_bitmap(), norm_face(), nsenter_main(), ntpd_main(), o_free_and_set_NULL(), open_memstream(), open_wmemstream(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_ReadSaveGameHeader(), P_SpawnMobj(), P_SpawnSpecials(), P_UpdateSpecials(), P_WriteSaveGameHeader(), pad(), PadRejectArray(), parse_address(), parse_args(), parse_meminfo(), parse_rtattr(), ParseDMXConfig(), perform_glob(), pgrep_main(), powertop_main(), print_addrinfo(), print_class(), print_host(), print_neigh(), print_qdisc(), print_queuelen(), print_route(), process_pid_str(), procps_get_maps(), procps_scan(), prop_alloc(), psRsaCrypt(), pstm_montgomery_reduce(), pstm_mul_comba_gen(), pstm_sqr_comba_gen(), R_CheckPlane(), R_ClearPlanes(), R_FindPlane(), R_GenerateLookup(), R_InitSpriteDefs(), R_PrecacheLevel(), read_block(), read_comsub(), readcmd(), realloc_line(), recv_from_to(), regcomp(), remove_pattern(), reverse(), rfkill_main(), rl_change_case(), rl_redisplay(), rtc_read_tm(), rtnl_dump_request(), rtnl_rtcache_request(), rtnl_talk(), safe_write_to_pty_decode_iac(), screen_erase(), send_arp_request(), send_client_hello_and_alloc_hsd(), send_client_key_exchange(), send_to_from(), service(), set_if_addr(), set_ifreq_to_ifname(), set_loopdev_params(), set_master(), set_mtu(), set_netns(), set_qlen(), setifs(), setup_file_in_str(), setup_string_in_str(), setup_tables(), sh_modcase(), SHA1_Final(), sha_crypt(), shtimer_zero(), signal_no_SA_RESTART_empty_mask(), signal_SA_RESTART_empty_mask(), sigqueue(), slattach_main(), smemcap_main(), sp_256_ecc_gen_k_8(), sp_256_ecc_mulmod_8(), sp_256_map_8(), sp_256_mont_mul_and_reduce_8(), sp_256_point_from_bin2x32(), sp_ecc_make_key_256(), sp_ecc_secret_gen_256(), split_main(), str2sockaddr(), strcspn(), stty_main(), stzalloc(), swd_init(), sym_lookup(), synstack_push(), tc_main(), tcp_do_one(), text_hole_make(), tls_get_zeroed_outbuf(), tls_run_copy_loop(), tre_mem_alloc_impl(), tre_mem_new_impl(), tre_tnfa_run_backtrack(), tre_tnfa_run_parallel(), tunctl_main(), ubi_tools_main(), udhcp_listen_socket(), udhcp_raw_socket(), udhcp_read_interface(), udhcp_recv_kernel_packet(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), udhcpd_main(), udp_do_one(), unshare_main(), update_line(), update_local_clock(), update_status(), update_utmp(), vconfig_main(), vfscanf(), vgetopt32(), W_GenerateHashTable(), wc_main(), wms_seek(), wms_write(), write_new_utmp(), writeheader(), WritePCXfile(), xrealloc_vector_helper(), xrtnl_open(), and xzalloc().