Fennix: Kernel/include/debug.h File Reference
debug.h File Reference
#include <types.h>
Macros
#define error(Format, ...) SysDbgWriteLine(DebugLevelError, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define warn(Format, ...) SysDbgWriteLine(DebugLevelWarning, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define info(Format, ...) SysDbgWriteLine(DebugLevelInfo, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define debug(Format, ...)
#define ubsan(Format, ...)
#define function(Format, ...)
#define trace(Format, ...) SysDbgWriteLine(DebugLevelTrace, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define fixme(Format, ...) SysDbgWriteLine(DebugLevelFixme, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define stub SysDbgWriteLine(DebugLevelStub, __FILE__, __LINE__, __FUNCTION__, "stub")
#define l_error(Format, ...) SysDbgLockedWriteLine(DebugLevelError, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define l_warn(Format, ...) SysDbgLockedWriteLine(DebugLevelWarning, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define l_info(Format, ...) SysDbgLockedWriteLine(DebugLevelInfo, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define l_debug(Format, ...)
#define l_ubsan(Format, ...)
#define l_function(Format, ...)
#define l_trace(Format, ...) SysDbgLockedWriteLine(DebugLevelTrace, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define l_fixme(Format, ...) SysDbgLockedWriteLine(DebugLevelFixme, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
#define l_stub SysDbgLockedWriteLine(DebugLevelStub, __FILE__, __LINE__, __FUNCTION__, "stub")
Enumerations
enum DebugLevel {
DebugLevelNone = 0 , DebugLevelError , DebugLevelWarning , DebugLevelInfo ,
DebugLevelDebug , DebugLevelTrace , DebugLevelFixme , DebugLevelUbsan ,
DebugLevelStub , DebugLevelFunction
}
Functions
void SysDbgWrite (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
void SysDbgWriteLine (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
void SysDbgLockedWrite (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
void SysDbgLockedWriteLine (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
EXTERNC void uart_wrapper (char c, void *unused)
Macro Definition Documentation
debug
#define debug (Format, ...)
Definition at line 94 of file debug.h.
error
#define error (Format, ...) SysDbgWriteLine(DebugLevelError, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 86 of file debug.h.
fixme
#define fixme (Format, ...) SysDbgWriteLine(DebugLevelFixme, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 99 of file debug.h.
function
#define function (Format, ...)
Definition at line 96 of file debug.h.
info
#define info (Format, ...) SysDbgWriteLine(DebugLevelInfo, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 88 of file debug.h.
l_debug
#define l_debug (Format, ...)
Definition at line 110 of file debug.h.
l_error
#define l_error (Format, ...) SysDbgLockedWriteLine(DebugLevelError, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 102 of file debug.h.
l_fixme
#define l_fixme (Format, ...) SysDbgLockedWriteLine(DebugLevelFixme, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 115 of file debug.h.
l_function
#define l_function (Format, ...)
Definition at line 112 of file debug.h.
l_info
#define l_info (Format, ...) SysDbgLockedWriteLine(DebugLevelInfo, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 104 of file debug.h.
l_stub
#define l_stub SysDbgLockedWriteLine(DebugLevelStub, __FILE__, __LINE__, __FUNCTION__, "stub")
Definition at line 116 of file debug.h.
l_trace
#define l_trace (Format, ...) SysDbgLockedWriteLine(DebugLevelTrace, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 114 of file debug.h.
l_ubsan
#define l_ubsan (Format, ...)
Definition at line 111 of file debug.h.
l_warn
#define l_warn (Format, ...) SysDbgLockedWriteLine(DebugLevelWarning, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 103 of file debug.h.
stub
#define stub SysDbgWriteLine(DebugLevelStub, __FILE__, __LINE__, __FUNCTION__, "stub")
Definition at line 100 of file debug.h.
trace
#define trace (Format, ...) SysDbgWriteLine(DebugLevelTrace, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 98 of file debug.h.
ubsan
#define ubsan (Format, ...)
Definition at line 95 of file debug.h.
warn
#define warn (Format, ...) SysDbgWriteLine(DebugLevelWarning, __FILE__, __LINE__, __FUNCTION__, Format, ##__VA_ARGS__)
Definition at line 87 of file debug.h.
Enumeration Type Documentation
DebugLevel
enum DebugLevel
Enumerator
DebugLevelNone
DebugLevelError
DebugLevelWarning
DebugLevelInfo
DebugLevelDebug
DebugLevelTrace
DebugLevelFixme
DebugLevelUbsan
DebugLevelStub
DebugLevelFunction
Definition at line 23 of file debug.h.
 {
     DebugLevelNone = 0,
     DebugLevelError,
     DebugLevelWarning,
     DebugLevelInfo,
     DebugLevelDebug,
     DebugLevelTrace,
     DebugLevelFixme,
     DebugLevelUbsan,
     DebugLevelStub,
     DebugLevelFunction,
 };
Function Documentation
SysDbgLockedWrite()
void SysDbgLockedWrite (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 208 of file debugger.cpp.
 {
     SmartTimeoutLock(DebuggerLock, 1000);
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
 }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
SysDbgLockedWriteLine()
void SysDbgLockedWriteLine (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 223 of file debugger.cpp.
 {
     SmartTimeoutLock(DebuggerLock, 1000);
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
     uart_wrapper('\n', nullptr);
 }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
SysDbgWrite()
void SysDbgWrite (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 179 of file debugger.cpp.
 {
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
 }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
SysDbgWriteLine()
void SysDbgWriteLine (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 193 of file debugger.cpp.
 {
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
     uart_wrapper('\n', nullptr);
 }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
uart_wrapper()
EXTERNC void uart_wrapper (char c, void * unused)
Definition at line 30 of file debugger.cpp.
 {
     static int once = 0;
     if (unlikely(!once++))
     {
         uint8_t com = inb(0x3F8);
         if (com != 0xFF)
         {
             outb(s_cst(uint16_t, 0x3F8 + 1), 0x00); // Disable all interrupts
             outb(s_cst(uint16_t, 0x3F8 + 3), 0x80); // Enable DLAB (set baud rate divisor)
             outb(s_cst(uint16_t, 0x3F8 + 0), 0x1);  // Set divisor to 1 (lo byte) 115200 baud
             outb(s_cst(uint16_t, 0x3F8 + 1), 0x0);  //                  (hi byte)
             outb(s_cst(uint16_t, 0x3F8 + 3), 0x03); // 8 bits, no parity, one stop bit
             outb(s_cst(uint16_t, 0x3F8 + 2), 0xC7); // Enable FIFO, clear them, with 14-byte threshold
             outb(s_cst(uint16_t, 0x3F8 + 4), 0x0B); // IRQs enabled, RTS/DSR set
             /* FIXME  https://wiki.osdev.org/Serial_Ports */
             // outb(s_cst(uint16_t, 0x3F8 + 0), 0x1E);
             // outb(s_cst(uint16_t, 0x3F8 + 0), 0xAE);
             // Check if the serial port is faulty.
             // if (inb(s_cst(uint16_t, 0x3F8 + 0)) != 0xAE)
             // {
             //     static int once = 0;
             //     if (!once++)
             //         warn("Serial port %#llx is faulty.", 0x3F8);
             //     // serialports[0x3F8] = false; // ignore for now
             //     // return;
             // }
             // Set to normal operation mode.
             outb(s_cst(uint16_t, 0x3F8 + 4), 0x0F);
             serialports[0] = true;
         }
     }
     if (likely(serialports[0]))
     {
         while ((inb(s_cst(uint16_t, 0x3F8 + 5)) & 0x20) == 0)
             ;
         outb(0x3F8, c);
     }
     UNUSED(unused);
 }
References c, inb(), likely, outb(), serialports, unlikely, and UNUSED.
Referenced by Driver::KernelLog(), KPrint(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), vprintf_dumper(), SysDbg::Write(), SysDbg::WriteLine(), and WritePrefix().