Fennix Userspace: Userspace/apps/base/busybox/coreutils/mktemp.c File Reference
mktemp.c File Reference
#include "libbb.h"
Functions
int mktemp_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
mktemp_main()
int mktemp_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 64 of file mktemp.c.
 {
     const char *path;
     char *chp;
     unsigned opts;
     enum {
         OPT_d = 1 << 0,
         OPT_q = 1 << 1,
         OPT_t = 1 << 2,
         OPT_p = 1 << 3,
         OPT_u = 1 << 4,
         OPT_tmpdir = (1 << 5) * ENABLE_LONG_OPTS,
     };
     path = getenv("TMPDIR");
     if (!path || path[0] == '\0')
         path = "/tmp";
 #if ENABLE_LONG_OPTS
     opts = getopt32long(argv, "^"
         "dqtp:u"
         "\0"
         "?1" /* 1 arg max */,
         "directory\0" No_argument       "d"
         "quiet\0"     No_argument       "q"
         "dry-run\0"   No_argument       "u"
         "tmpdir\0"    Optional_argument "\xff"
         , &path, &path
     );
 #else
     opts = getopt32(argv, "^" "dqtp:u" "\0" "?1"/*1 arg max*/, &path);
 #endif
     chp = argv[optind];
     if (!chp) {
         /* GNU coreutils 8.4:
          * bare "mktemp" -> "mktemp -t tmp.XXXXXX"
          */
         chp = xstrdup("tmp.XXXXXX");
         opts |= OPT_t;
     }
 #if 0
     /* Don't allow directory separator in template */
     if ((opts & OPT_t) && bb_basename(chp) != chp) {
         errno = EINVAL;
         goto error;
     }
 #endif
     if (opts & (OPT_t|OPT_p|OPT_tmpdir))
         chp = concat_path_file(path, chp);
     if (opts & OPT_u) {
         chp = mktemp(chp);
         if (chp[0] == '\0')
             goto error;
     } else if (opts & OPT_d) {
         if (mkdtemp(chp) == NULL)
             goto error;
     } else {
         if (mkstemp(chp) < 0)
             goto error;
     }
     puts(chp);
     return EXIT_SUCCESS;
  error:
     if (opts & OPT_q)
         return EXIT_FAILURE;
     /* don't use chp as it gets mangled in case of error */
     bb_perror_nomsg_and_die();
 }
References argv, bb_basename(), bb_perror_nomsg_and_die(), concat_path_file(), EINVAL, errno, error, EXIT_FAILURE, EXIT_SUCCESS, getenv, getopt32(), getopt32long, mkdtemp(), mkstemp(), mktemp(), No_argument, NULL, OPT_d, OPT_p, OPT_q, OPT_t, OPT_u, optind, Optional_argument, puts(), and xstrdup().