Fennix: Userspace/musl/src/process/fexecve.c File Reference
fexecve.c File Reference
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
int fexecve (int fd, char *const argv[], char *const envp[])
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file fexecve.c.
Function Documentation
fexecve()
int fexecve (int fd, char *const argv[], char *const envp[])
Definition at line 7 of file fexecve.c.
 {
     int r = __syscall(SYS_execveat, fd, "", argv, envp, AT_EMPTY_PATH);
     if (r != -ENOSYS) return __syscall_ret(r);
     char buf[15 + 3*sizeof(int)];
     __procfdname(buf, fd);
     execve(buf, argv, envp);
     if (errno == ENOENT) errno = EBADF;
     return -1;
 }
References __procfdname(), __syscall, __syscall_ret(), argv, AT_EMPTY_PATH, buf, EBADF, ENOENT, ENOSYS, errno, execve(), and fd.