Fennix: MediaAccessControl Struct Reference
MediaAccessControl Struct Reference
#include <net.hpp>
Public Member Functions
bool operator== (const MediaAccessControl &lhs) const
bool operator== (const uint48_t &lhs) const
bool operator!= (const MediaAccessControl &lhs) const
bool operator!= (const uint48_t &lhs) const
uint48_t ToHex ()
MediaAccessControl FromHex (uint48_t Hex)
bool Valid ()
char * ToString ()
bool operator== (const MediaAccessControl &lhs) const
bool operator== (const uint48_t &lhs) const
bool operator!= (const MediaAccessControl &lhs) const
bool operator!= (const uint48_t &lhs) const
uint48_t ToHex ()
MediaAccessControl FromHex (uint48_t Hex)
bool Valid ()
Data Fields
uint8_t Address [6] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
Endianness Endianess = LITTLE_ENDIAN
Detailed Description
Definition at line 48 of file net.hpp.
Member Function Documentation
FromHex() [1/2]
MediaAccessControl MediaAccessControl::FromHex (uint48_t Hex) inline
Definition at line 69 of file netools.h.
     {
         this->Address[0] = (uint8_t)((Hex >> 40) & 0xFF);
         this->Address[1] = (uint8_t)((Hex >> 32) & 0xFF);
         this->Address[2] = (uint8_t)((Hex >> 24) & 0xFF);
         this->Address[3] = (uint8_t)((Hex >> 16) & 0xFF);
         this->Address[4] = (uint8_t)((Hex >> 8) & 0xFF);
         this->Address[5] = (uint8_t)(Hex & 0xFF);
         return *this;
     }
FromHex() [2/2]
MediaAccessControl MediaAccessControl::FromHex (uint48_t Hex) inline
Definition at line 93 of file net.hpp.
     {
         this->Address[0] = (uint8_t)((Hex >> 40) & 0xFF);
         this->Address[1] = (uint8_t)((Hex >> 32) & 0xFF);
         this->Address[2] = (uint8_t)((Hex >> 24) & 0xFF);
         this->Address[3] = (uint8_t)((Hex >> 16) & 0xFF);
         this->Address[4] = (uint8_t)((Hex >> 8) & 0xFF);
         this->Address[5] = (uint8_t)(Hex & 0xFF);
         return *this;
     }
Referenced by NetworkEthernet::Ethernet::Receive().
operator!=() [1/4]
bool MediaAccessControl::operator!= (const MediaAccessControl & lhs) const inline
Definition at line 56 of file netools.h.
 { return !(*this == lhs); }
operator!=() [2/4]
bool MediaAccessControl::operator!= (const MediaAccessControl & lhs) const inline
Definition at line 80 of file net.hpp.
 { return !(*this == lhs); }
operator!=() [3/4]
bool MediaAccessControl::operator!= (const uint48_t & lhs) const inline
Definition at line 57 of file netools.h.
 { return !(*this == lhs); }
operator!=() [4/4]
bool MediaAccessControl::operator!= (const uint48_t & lhs) const inline
Definition at line 81 of file net.hpp.
 { return !(*this == lhs); }
operator==() [1/4]
bool MediaAccessControl::operator== (const MediaAccessControl & lhs) const inline
Definition at line 29 of file netools.h.
     {
         return lhs.Address[0] == this->Address[0] &&
                lhs.Address[1] == this->Address[1] &&
                lhs.Address[2] == this->Address[2] &&
                lhs.Address[3] == this->Address[3] &&
                lhs.Address[4] == this->Address[4] &&
                lhs.Address[5] == this->Address[5];
     }
References Address.
operator==() [2/4]
bool MediaAccessControl::operator== (const MediaAccessControl & lhs) const inline
Definition at line 53 of file net.hpp.
     {
         return lhs.Address[0] == this->Address[0] &&
                lhs.Address[1] == this->Address[1] &&
                lhs.Address[2] == this->Address[2] &&
                lhs.Address[3] == this->Address[3] &&
                lhs.Address[4] == this->Address[4] &&
                lhs.Address[5] == this->Address[5];
     }
References Address.
operator==() [3/4]
bool MediaAccessControl::operator== (const uint48_t & lhs) const inline
Definition at line 39 of file netools.h.
     {
         MediaAccessControl MAC;
         MAC.Address[0] = (uint8_t)((lhs >> 40) & 0xFF);
         MAC.Address[1] = (uint8_t)((lhs >> 32) & 0xFF);
         MAC.Address[2] = (uint8_t)((lhs >> 24) & 0xFF);
         MAC.Address[3] = (uint8_t)((lhs >> 16) & 0xFF);
         MAC.Address[4] = (uint8_t)((lhs >> 8) & 0xFF);
         MAC.Address[5] = (uint8_t)(lhs & 0xFF);
         return MAC.Address[0] == this->Address[0] &&
                MAC.Address[1] == this->Address[1] &&
                MAC.Address[2] == this->Address[2] &&
                MAC.Address[3] == this->Address[3] &&
                MAC.Address[4] == this->Address[4] &&
                MAC.Address[5] == this->Address[5];
     }
References Address.
operator==() [4/4]
bool MediaAccessControl::operator== (const uint48_t & lhs) const inline
Definition at line 63 of file net.hpp.
     {
         MediaAccessControl MAC;
         MAC.Address[0] = (uint8_t)((lhs >> 40) & 0xFF);
         MAC.Address[1] = (uint8_t)((lhs >> 32) & 0xFF);
         MAC.Address[2] = (uint8_t)((lhs >> 24) & 0xFF);
         MAC.Address[3] = (uint8_t)((lhs >> 16) & 0xFF);
         MAC.Address[4] = (uint8_t)((lhs >> 8) & 0xFF);
         MAC.Address[5] = (uint8_t)(lhs & 0xFF);
         return MAC.Address[0] == this->Address[0] &&
                MAC.Address[1] == this->Address[1] &&
                MAC.Address[2] == this->Address[2] &&
                MAC.Address[3] == this->Address[3] &&
                MAC.Address[4] == this->Address[4] &&
                MAC.Address[5] == this->Address[5];
     }
References Address.
ToHex() [1/2]
uint48_t MediaAccessControl::ToHex () inline
Definition at line 59 of file netools.h.
     {
         return ((uint48_t)this->Address[0] << 40) |
                ((uint48_t)this->Address[1] << 32) |
                ((uint48_t)this->Address[2] << 24) |
                ((uint48_t)this->Address[3] << 16) |
                ((uint48_t)this->Address[4] << 8) |
                ((uint48_t)this->Address[5]);
     }
ToHex() [2/2]
uint48_t MediaAccessControl::ToHex () inline
Definition at line 83 of file net.hpp.
     {
         return ((uint48_t)this->Address[0] << 40) |
                ((uint48_t)this->Address[1] << 32) |
                ((uint48_t)this->Address[2] << 24) |
                ((uint48_t)this->Address[3] << 16) |
                ((uint48_t)this->Address[4] << 8) |
                ((uint48_t)this->Address[5]);
     }
Referenced by NetworkARP::ARP::Broadcast(), E1000Device::ioctl(), NetworkARP::ARP::OnEthernetPacketReceived(), NetworkARP::ARP::Resolve(), and NetworkEthernet::Ethernet::Send().
ToString()
char* MediaAccessControl::ToString () inline
Definition at line 121 of file net.hpp.
     {
         static char Buffer[18];
         sprintf(Buffer, "%02X:%02X:%02X:%02X:%02X:%02X", this->Address[0], this->Address[1], this->Address[2], this->Address[3], this->Address[4], this->Address[5]);
         return Buffer;
     }
References Buffer, and sprintf().
Referenced by NetworkEthernet::Ethernet::GetInterface(), NetworkEthernet::Ethernet::Receive(), and NetworkEthernet::Ethernet::Send().
Valid() [1/2]
bool MediaAccessControl::Valid () inline
Definition at line 80 of file netools.h.
     {
         // TODO: More complex MAC validation
         return (this->Address[0] != 0 ||
                 this->Address[1] != 0 ||
                 this->Address[2] != 0 ||
                 this->Address[3] != 0 ||
                 this->Address[4] != 0 ||
                 this->Address[5] != 0) &&
                (this->Address[0] != 0xFF ||
                 this->Address[1] != 0xFF ||
                 this->Address[2] != 0xFF ||
                 this->Address[3] != 0xFF ||
                 this->Address[4] != 0xFF ||
                 this->Address[5] != 0xFF);
     }
Valid() [2/2]
bool MediaAccessControl::Valid () inline
Definition at line 104 of file net.hpp.
     {
         // TODO: More complex MAC validation
         return (this->Address[0] != 0 ||
                 this->Address[1] != 0 ||
                 this->Address[2] != 0 ||
                 this->Address[3] != 0 ||
                 this->Address[4] != 0 ||
                 this->Address[5] != 0) &&
                (this->Address[0] != 0xFF ||
                 this->Address[1] != 0xFF ||
                 this->Address[2] != 0xFF ||
                 this->Address[3] != 0xFF ||
                 this->Address[4] != 0xFF ||
                 this->Address[5] != 0xFF);
     }
Field Documentation
Address
uint8_t MediaAccessControl::Address = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
Definition at line 50 of file net.hpp.
Referenced by E1000Device::GetMAC(), operator==(), and RTL8139Device::RTL8139Device().
Endianess
Endianness MediaAccessControl::Endianess = LITTLE_ENDIAN
Definition at line 51 of file net.hpp.
The documentation for this struct was generated from the following files:
Kernel/include/net/net.hpp
Drivers/include/netools.h