Fennix: Userspace/musl/src/locale/wcsxfrm.c File Reference
wcsxfrm.c File Reference
#include <wchar.h>
#include <locale.h>
#include "locale_impl.h"
Functions
size_t __wcsxfrm_l (wchar_t *restrict dest, const wchar_t *restrict src, size_t n, locale_t loc)
size_t wcsxfrm (wchar_t *restrict dest, const wchar_t *restrict src, size_t n)
weak_alias (__wcsxfrm_l, wcsxfrm_l)
Function Documentation
__wcsxfrm_l()
size_t __wcsxfrm_l (wchar_t *restrict dest, const wchar_t *restrict src, size_t n, locale_t loc)
Definition at line 6 of file wcsxfrm.c.
 {
     size_t l = wcslen(src);
     if (l < n) {
         wmemcpy(dest, src, l+1);
     } else if (n) {
         wmemcpy(dest, src, n-1);
         dest[n-1] = 0;
     }
     return l;
 }
References l, n, src, wcslen(), and wmemcpy().
Referenced by wcsxfrm().
wcsxfrm()
size_t wcsxfrm (wchar_t *restrict dest, const wchar_t *restrict src, size_t n)
Definition at line 18 of file wcsxfrm.c.
 {
     return __wcsxfrm_l(dest, src, n, CURRENT_LOCALE);
 }
References __wcsxfrm_l(), CURRENT_LOCALE, n, and src.
weak_alias()
weak_alias (__wcsxfrm_l , wcsxfrm_l)