Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/linux_swap.c File Reference
linux_swap.c File Reference
#include "volume_id_internal.h"
Data Structures
struct swap_header_v1_2
Macros
#define LARGEST_PAGESIZE 0x4000
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_linux_swap (struct volume_id *id)
Variables
struct swap_header_v1_2 PACKED
Data Structure Documentation
swap_header_v1_2
struct swap_header_v1_2
Definition at line 29 of file linux_swap.c.
Data Fields
uint8_t bootbits[1024]
uint32_t last_page
uint32_t nr_badpages
uint8_t uuid[16]
uint32_t version
uint8_t volume_name[16]
Macro Definition Documentation
LARGEST_PAGESIZE
#define LARGEST_PAGESIZE 0x4000
Definition at line 38 of file linux_swap.c.
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_linux_swap()
int FAST_FUNC volume_id_probe_linux_swap (struct volume_id * id)
Definition at line 40 of file linux_swap.c.
 {
 #define off ((uint64_t)0)
     struct swap_header_v1_2 *sw;
     const uint8_t *buf;
     unsigned page;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     /* the swap signature is at the end of the PAGE_SIZE */
     for (page = 0x1000; page <= LARGEST_PAGESIZE; page <<= 1) {
             buf = volume_id_get_buffer(id, off + page-10, 10);
             if (buf == NULL)
                 return -1;
             if (memcmp(buf, "SWAP-SPACE", 10) == 0) {
 //              id->type_version[0] = '1';
 //              id->type_version[1] = '\0';
                 goto found;
             }
             if (memcmp(buf, "SWAPSPACE2", 10) == 0
              || memcmp(buf, "S1SUSPEND", 9) == 0
              || memcmp(buf, "S2SUSPEND", 9) == 0
              || memcmp(buf, "ULSUSPEND", 9) == 0
             ) {
                 sw = volume_id_get_buffer(id, off, sizeof(struct swap_header_v1_2));
                 if (sw == NULL)
                     return -1;
 //              id->type_version[0] = '2';
 //              id->type_version[1] = '\0';
 //              volume_id_set_label_raw(id, sw->volume_name, 16);
                 volume_id_set_label_string(id, sw->volume_name, 16);
                 volume_id_set_uuid(id, sw->uuid, UUID_DCE);
                 goto found;
             }
     }
     return -1;
 found:
 //  volume_id_set_usage(id, VOLUME_ID_OTHER);
     IF_FEATURE_BLKID_TYPE(id->type = "swap";)
     return 0;
 }
References buf, dbg, found, LARGEST_PAGESIZE, memcmp(), NULL, off, page, swap_header_v1_2::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), volume_id_set_uuid(), and swap_header_v1_2::volume_name.
Variable Documentation
PACKED
struct swap_header_v1_2 PACKED