Fennix Userspace: Userspace/apps/base/busybox/coreutils/head.c File Reference
head.c File Reference
#include "libbb.h"
Macros
#define print_first_N(fp, count, bytes) print_first_N(fp,count)
#define eat_num(negative_N, p) eat_num(p)
#define header_fmt_str "\n==> %s <==\n"
#define header_threshhold 1
#define count_bytes 0
#define negative_N 0
Functions
static void print_first_N (FILE *fp, unsigned long count, bool count_bytes)
void print_except_N_last_bytes (FILE *fp, unsigned count)
void print_except_N_last_lines (FILE *fp, unsigned count)
static unsigned long eat_num (bool *negative_N, const char *p)
int head_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char head_opts[] ALIGN1
Macro Definition Documentation
count_bytes
#define count_bytes 0
eat_num
#define eat_num (negative_N, p) eat_num(p)
Definition at line 144 of file head.c.
header_fmt_str
#define header_fmt_str "\n==> %s <==\n"
Definition at line 165 of file head.c.
header_threshhold
#define header_threshhold 1
negative_N
#define negative_N 0
print_first_N
#define print_first_N (fp, count, bytes) print_first_N(fp,count)
Definition at line 55 of file head.c.
Function Documentation
eat_num()
static unsigned long eat_num (bool * negative_N, const char * p) static
Definition at line 147 of file head.c.
 {
 #if ENABLE_FEATURE_FANCY_HEAD
     if (*p == '-') {
         *negative_N = 1;
         p++;
     }
 #endif
     return xatoul_sfx(p, bkm_suffixes);
 }
References bkm_suffixes, negative_N, and p.
head_main()
int head_main (int argc, char ** argv)
Definition at line 168 of file head.c.
 {
     unsigned long count = 10;
 #if ENABLE_FEATURE_FANCY_HEAD
     int header_threshhold = 1;
     bool count_bytes = 0;
     bool negative_N = 0;
 #else
 # define header_threshhold 1
 # define count_bytes       0
 # define negative_N        0
 #endif
     FILE *fp;
     const char *fmt;
     char *p;
     int opt;
     int retval = EXIT_SUCCESS;
 #if ENABLE_INCLUDE_SUSv2 || ENABLE_FEATURE_FANCY_HEAD
     /* Allow legacy syntax of an initial numeric option without -n. */
     if (argv[1] && argv[1][0] == '-'
      && isdigit(argv[1][1])
     ) {
         --argc;
         ++argv;
         p = argv[0] + 1;
         goto GET_COUNT;
     }
 #endif
     /* No size benefit in converting this to getopt32 */
     while ((opt = getopt(argc, argv, head_opts)) > 0) {
         switch (opt) {
 #if ENABLE_FEATURE_FANCY_HEAD
         case 'q':
             header_threshhold = INT_MAX;
             break;
         case 'v':
             header_threshhold = -1;
             break;
         case 'c':
             count_bytes = 1;
             /* fall through */
 #endif
         case 'n':
             p = optarg;
 #if ENABLE_INCLUDE_SUSv2 || ENABLE_FEATURE_FANCY_HEAD
  GET_COUNT:
 #endif
             count = eat_num(&negative_N, p);
             break;
         default:
             bb_show_usage();
         }
     }
     argc -= optind;
     argv += optind;
     if (!*argv)
         *--argv = (char*)"-";
     fmt = header_fmt_str + 1;
     if (argc <= header_threshhold) {
 #if ENABLE_FEATURE_FANCY_HEAD
         header_threshhold = 0;
 #else
         fmt += 11; /* "" */
 #endif
     }
     if (negative_N) {
         if (count >= INT_MAX / sizeof(char*))
             bb_error_msg("count is too big: %lu", count);
     }
     do {
         fp = fopen_or_warn_stdin(*argv);
         if (fp) {
             if (fp == stdin) {
                 *argv = (char *) bb_msg_standard_input;
             }
             if (header_threshhold) {
                 printf(fmt, *argv);
             }
             if (negative_N) {
                 if (count_bytes) {
                     print_except_N_last_bytes(fp, count);
                 } else {
                     print_except_N_last_lines(fp, count);
                 }
             } else {
                 print_first_N(fp, count, count_bytes);
             }
             die_if_ferror_stdout();
             if (fclose_if_not_stdin(fp)) {
                 bb_simple_perror_msg(*argv);
                 retval = EXIT_FAILURE;
             }
         } else {
             retval = EXIT_FAILURE;
         }
         fmt = header_fmt_str;
     } while (*++argv);
     fflush_stdout_and_exit(retval);
 }
References argc, argv, bb_error_msg(), bb_show_usage(), bb_simple_perror_msg(), count, count_bytes, die_if_ferror_stdout(), eat_num, EXIT_FAILURE, EXIT_SUCCESS, fclose_if_not_stdin(), fflush_stdout_and_exit(), fopen_or_warn_stdin(), getopt(), header_fmt_str, header_threshhold, INT_MAX, isdigit, negative_N, opt, optarg, optind, p, print_except_N_last_bytes(), print_except_N_last_lines(), print_first_N, printf(), retval, and stdin.
print_except_N_last_bytes()
void print_except_N_last_bytes (FILE * fp, unsigned count)
Referenced by head_main().
print_except_N_last_lines()
void print_except_N_last_lines (FILE * fp, unsigned count)
Referenced by head_main().
print_first_N()
static void print_first_N (FILE * fp, unsigned long count, bool count_bytes) static
Definition at line 58 of file head.c.
 {
 #if !ENABLE_FEATURE_FANCY_HEAD
     const int count_bytes = 0;
 #endif
     while (count) {
         int c = getc(fp);
         if (c == EOF)
             break;
         if (count_bytes || (c == '\n'))
             --count;
         putchar(c);
     }
 }
References c, count, count_bytes, EOF, getc, and putchar.
Variable Documentation
ALIGN1
const char head_opts [] ALIGN1 static
Initial value:
=
    "n:"
Definition at line 158 of file head.c.