Fennix: Kernel/profiling/cyg.cpp File Reference
cyg.cpp File Reference
#include <types.h>
#include <printf.h>
#include <uart.hpp>
#include "../kernel.h"
Functions
static nsa NIF void profiler_uart_wrapper (char c, void *unused)
EXTERNC nsa NIF void __cyg_profile_func_enter (void *Function, void *CallSite)
EXTERNC nsa NIF void __cyg_profile_func_exit (void *Function, void *CallSite)
Variables
bool EnableProfiler = false
bool Wait = false
unsigned long long LogDepth = 0
unsigned int Level = 0
UART com2 (COM2)
Function Documentation
__cyg_profile_func_enter()
EXTERNC nsa NIF void __cyg_profile_func_enter (void * Function, void * CallSite)
Definition at line 41 of file cyg.cpp.
 {
     if (!EnableProfiler)
         return;
     while (Wait)
 #if defined(a86)
         asmv("pause");
 #elif defined(aa64)
         asmv("yield");
 #endif
     Wait = true;
     if (Level > 40)
         Level--;
     Level++;
     if (!KernelSymbolTable)
         fctprintf(profiler_uart_wrapper, nullptr, "%lld [%02d]: \033[42m->\033[0m%*c \033[33m%p\033[0m  -  \033[33m%p\033[0m\n",
                   LogDepth++,
                   Level - 1,
                   Level,
                   ' ',
                   Function,
                   CallSite);
     else
         fctprintf(profiler_uart_wrapper, nullptr, "%lld [%02d]: \033[42m->\033[0m%*c \033[33m%s\033[0m  -  \033[33m%s\033[0m\n",
                   LogDepth++,
                   Level - 1,
                   Level,
                   ' ',
                   KernelSymbolTable->GetSymbol((uintptr_t)Function),
                   KernelSymbolTable->GetSymbol((uintptr_t)CallSite));
     Wait = false;
 }
References asmv(), EnableProfiler, fctprintf(), SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, Level, LogDepth, profiler_uart_wrapper(), and Wait.
__cyg_profile_func_exit()
EXTERNC nsa NIF void __cyg_profile_func_exit (void * Function, void * CallSite)
Definition at line 78 of file cyg.cpp.
 {
     if (!EnableProfiler)
         return;
     while (Wait)
 #if defined(a86)
         asmv("pause");
 #elif defined(aa64)
         asmv("yield");
 #endif
     Wait = true;
     if (Level > 40)
         Level--;
     Level--;
     if (!KernelSymbolTable)
         fctprintf(profiler_uart_wrapper, nullptr, "%lld [%02d]: \033[41m<-\033[0m%*c \033[33m%p\033[0m  -  \033[33m%p\033[0m\n",
                   LogDepth++,
                   Level - 1,
                   Level,
                   ' ',
                   Function,
                   CallSite);
     else
         fctprintf(profiler_uart_wrapper, nullptr, "%lld [%02d]: \033[41m<-\033[0m%*c \033[33m%s\033[0m  -  \033[33m%s\033[0m\n",
                   LogDepth++,
                   Level - 1,
                   Level,
                   ' ',
                   KernelSymbolTable->GetSymbol((uintptr_t)Function),
                   KernelSymbolTable->GetSymbol((uintptr_t)CallSite));
     Wait = false;
 }
References asmv(), EnableProfiler, fctprintf(), SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, Level, LogDepth, profiler_uart_wrapper(), and Wait.
profiler_uart_wrapper()
static nsa NIF void profiler_uart_wrapper (char c, void * unused) inline static
Definition at line 31 of file cyg.cpp.
 {
     bool renable = EnableProfiler;
     EnableProfiler = false;
     com2.Write(c);
     UNUSED(unused);
     if (renable)
         EnableProfiler = true;
 }
References c, com2, EnableProfiler, UNUSED, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by __cyg_profile_func_enter(), and __cyg_profile_func_exit().
Variable Documentation
com2
UART com2(COM2) (COM2)
Referenced by command_connect(), Main(), and profiler_uart_wrapper().
EnableProfiler
bool EnableProfiler = false
Definition at line 24 of file cyg.cpp.
Referenced by __cyg_profile_func_enter(), __cyg_profile_func_exit(), Entry(), and profiler_uart_wrapper().
Level
unsigned int Level = 0
Definition at line 27 of file cyg.cpp.
Referenced by __cyg_profile_func_enter(), __cyg_profile_func_exit(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), SysDbg::Write(), SysDbg::WriteLine(), and WritePrefix().
LogDepth
unsigned long long LogDepth = 0
Definition at line 26 of file cyg.cpp.
Referenced by __cyg_profile_func_enter(), and __cyg_profile_func_exit().
Wait
bool Wait = false
Definition at line 25 of file cyg.cpp.
Referenced by __cyg_profile_func_enter(), and __cyg_profile_func_exit().