Fennix: Userspace/mlibc/options/posix/include/wordexp.h File Reference
wordexp.h File Reference
#include <bits/size_t.h>
Data Structures
struct wordexp_t
Macros
#define WRDE_APPEND 1
#define WRDE_DOOFFS 2
#define WRDE_NOCMD 4
#define WRDE_REUSE 8
#define WRDE_SHOWERR 16
#define WRDE_UNDEF 32
#define WRDE_SUCCESS 1
#define WRDE_BADCHAR 1
#define WRDE_BADVAL 2
#define WRDE_CMDSUB 3
#define WRDE_NOSPACE 4
#define WRDE_SYNTAX 5
Functions
int wordexp (const char *s, wordexp_t *p, int flags)
void wordfree (wordexp_t *p)
Data Structure Documentation
wordexp_t
struct wordexp_t
Definition at line 24 of file wordexp.h.
Data Fields
size_t we_nbytes
size_t we_offs
char * we_strings
size_t we_wordc
char ** we_wordv
Macro Definition Documentation
WRDE_APPEND
#define WRDE_APPEND 1
Definition at line 10 of file wordexp.h.
WRDE_BADCHAR
#define WRDE_BADCHAR 1
Definition at line 18 of file wordexp.h.
WRDE_BADVAL
#define WRDE_BADVAL 2
Definition at line 19 of file wordexp.h.
WRDE_CMDSUB
#define WRDE_CMDSUB 3
Definition at line 20 of file wordexp.h.
WRDE_DOOFFS
#define WRDE_DOOFFS 2
Definition at line 11 of file wordexp.h.
WRDE_NOCMD
#define WRDE_NOCMD 4
Definition at line 12 of file wordexp.h.
WRDE_NOSPACE
#define WRDE_NOSPACE 4
Definition at line 21 of file wordexp.h.
WRDE_REUSE
#define WRDE_REUSE 8
Definition at line 13 of file wordexp.h.
WRDE_SHOWERR
#define WRDE_SHOWERR 16
Definition at line 14 of file wordexp.h.
WRDE_SUCCESS
#define WRDE_SUCCESS 1
Definition at line 17 of file wordexp.h.
WRDE_SYNTAX
#define WRDE_SYNTAX 5
Definition at line 22 of file wordexp.h.
WRDE_UNDEF
#define WRDE_UNDEF 32
Definition at line 15 of file wordexp.h.
Function Documentation
wordexp()
int wordexp (const char * s, wordexp_t * p, int flags)
wordfree()
void wordfree (wordexp_t * p)
Definition at line 333 of file wordexp-stubs.cpp.
{
     if (we == NULL)
         return;
     free(we->we_wordv);
     free(we->we_strings);
     we->we_wordv = NULL;
     we->we_strings = NULL;
     we->we_nbytes = 0;
     we->we_wordc = 0;
 }
References free(), NULL, wordexp_t::we_nbytes, wordexp_t::we_strings, wordexp_t::we_wordc, and wordexp_t::we_wordv.
Referenced by main(), and wordexp().