Fennix Userspace: Userspace/apps/base/busybox/coreutils/hostid.c File Reference
hostid.c File Reference
#include "libbb.h"
Functions
int hostid_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int hostid_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
hostid_main() [1/2]
int hostid_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 32 of file hostid.c.
 {
     if (argv[1]) {
         bb_show_usage();
     }
     /* POSIX says gethostid returns a "32-bit identifier" */
     printf("%08x\n", (unsigned)(uint32_t)gethostid());
     return fflush_all();
 }
References argv, bb_show_usage(), fflush_all(), gethostid(), and printf().
hostid_main() [2/2]
int hostid_main (int argc, char ** argv)