Fennix Userspace: Userspace/musl/include/mntent.h File Reference
mntent.h File Reference
#include <bits/alltypes.h>
Data Structures
struct mntent
Macros
#define __NEED_FILE
#define MOUNTED "/etc/mtab"
#define MNTTYPE_IGNORE "ignore"
#define MNTTYPE_NFS "nfs"
#define MNTTYPE_SWAP "swap"
#define MNTOPT_DEFAULTS "defaults"
#define MNTOPT_RO "ro"
#define MNTOPT_RW "rw"
#define MNTOPT_SUID "suid"
#define MNTOPT_NOSUID "nosuid"
#define MNTOPT_NOAUTO "noauto"
Functions
FILE * setmntent (const char *, const char *)
int endmntent (FILE *)
struct mntent * getmntent (FILE *)
struct mntent * getmntent_r (FILE *, struct mntent *, char *, int)
int addmntent (FILE *, const struct mntent *)
char * hasmntopt (const struct mntent *, const char *)
Data Structure Documentation
mntent
struct mntent
Definition at line 23 of file mntent.h.
Data Fields
char * mnt_dir
int mnt_freq
char * mnt_fsname
char * mnt_opts
int mnt_passno
char * mnt_type
Macro Definition Documentation
__NEED_FILE
#define __NEED_FILE
Definition at line 8 of file mntent.h.
MNTOPT_DEFAULTS
#define MNTOPT_DEFAULTS "defaults"
Definition at line 16 of file mntent.h.
MNTOPT_NOAUTO
#define MNTOPT_NOAUTO "noauto"
Definition at line 21 of file mntent.h.
MNTOPT_NOSUID
#define MNTOPT_NOSUID "nosuid"
Definition at line 20 of file mntent.h.
MNTOPT_RO
#define MNTOPT_RO "ro"
Definition at line 17 of file mntent.h.
MNTOPT_RW
#define MNTOPT_RW "rw"
Definition at line 18 of file mntent.h.
MNTOPT_SUID
#define MNTOPT_SUID "suid"
Definition at line 19 of file mntent.h.
MNTTYPE_IGNORE
#define MNTTYPE_IGNORE "ignore"
Definition at line 13 of file mntent.h.
MNTTYPE_NFS
#define MNTTYPE_NFS "nfs"
Definition at line 14 of file mntent.h.
MNTTYPE_SWAP
#define MNTTYPE_SWAP "swap"
Definition at line 15 of file mntent.h.
MOUNTED
#define MOUNTED "/etc/mtab"
Definition at line 11 of file mntent.h.
Function Documentation
addmntent()
int addmntent (FILE * f, const struct mntent * mnt)
Definition at line 72 of file mntent.c.
 {
     if (fseek(f, 0, SEEK_END)) return 1;
     return fprintf(f, "%s\t%s\t%s\t%s\t%d\t%d\n",
         mnt->mnt_fsname, mnt->mnt_dir, mnt->mnt_type, mnt->mnt_opts,
         mnt->mnt_freq, mnt->mnt_passno) < 0;
 }
References f, fprintf(), fseek(), mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, and SEEK_END.
Referenced by mount_it_now().
endmntent()
int endmntent (FILE * f)
Definition at line 17 of file mntent.c.
 {
     if (f) fclose(f);
     return 1;
 }
References f, and fclose().
Referenced by df_main(), do_em_all_in_fstab(), find_mount_point(), load_fs_info(), mount_it_now(), mount_main(), and umount_main().
getmntent()
struct mntent* getmntent (FILE * f)
Definition at line 66 of file mntent.c.
 {
     static struct mntent mnt;
     return getmntent_r(f, &mnt, SENTINEL, 0);
 }
References f, getmntent_r(), and SENTINEL.
Referenced by df_main(), do_em_all_in_fstab(), and find_mount_point().
getmntent_r()
struct mntent* getmntent_r (FILE * f, struct mntent * mnt, char * linebuf, int buflen)
Definition at line 23 of file mntent.c.
 {
     int n[8], use_internal = (linebuf == SENTINEL);
     size_t len, i;
     mnt->mnt_freq = 0;
     mnt->mnt_passno = 0;
     do {
         if (use_internal) {
             getline(&internal_buf, &internal_bufsize, f);
             linebuf = internal_buf;
         } else {
             fgets(linebuf, buflen, f);
         }
         if (feof(f) || ferror(f)) return 0;
         if (!strchr(linebuf, '\n')) {
             fscanf(f, "%*[^\n]%*[\n]");
             errno = ERANGE;
             return 0;
         }
         len = strlen(linebuf);
         if (len > INT_MAX) continue;
         for (i = 0; i < sizeof n / sizeof *n; i++) n[i] = len;
         sscanf(linebuf, " %n%*s%n %n%*s%n %n%*s%n %n%*s%n %d %d",
             n, n+1, n+2, n+3, n+4, n+5, n+6, n+7,
             &mnt->mnt_freq, &mnt->mnt_passno);
     } while (linebuf[n[0]] == '#' || n[1]==len);
     linebuf[n[1]] = 0;
     linebuf[n[3]] = 0;
     linebuf[n[5]] = 0;
     linebuf[n[7]] = 0;
     mnt->mnt_fsname = linebuf+n[0];
     mnt->mnt_dir = linebuf+n[2];
     mnt->mnt_type = linebuf+n[4];
     mnt->mnt_opts = linebuf+n[6];
     return mnt;
 }
References buflen, ERANGE, errno, f, feof, ferror, fgets, fscanf(), getline(), i, INT_MAX, internal_buf, internal_bufsize, mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, n, SENTINEL, sscanf(), strchr(), and strlen().
Referenced by getmntent(), load_fs_info(), mount_main(), and umount_main().
hasmntopt()
char* hasmntopt (const struct mntent * mnt, const char * opt)
Definition at line 80 of file mntent.c.
 {
     return strstr(mnt->mnt_opts, opt);
 }
References mntent::mnt_opts, opt, and strstr().
Referenced by do_em_all_in_fstab().
setmntent()
FILE* setmntent (const char * name, const char * mode)
Definition at line 12 of file mntent.c.
 {
     return fopen(name, mode);
 }
References fopen().
Referenced by df_main(), find_mount_point(), load_fs_info(), mount_it_now(), mount_main(), and umount_main().