Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/jfs.c File Reference
jfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct jfs_super_block
Macros
#define JFS_SUPERBLOCK_OFFSET 0x8000
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_jfs (struct volume_id *id)
Variables
struct jfs_super_block PACKED
Data Structure Documentation
jfs_super_block
struct jfs_super_block
Definition at line 29 of file jfs.c.
Data Fields
uint32_t bsize
uint32_t dummy1
uint32_t dummy2[27]
uint8_t label[16]
uint8_t loguuid[16]
uint8_t magic[4]
uint32_t pbsize
uint64_t size
uint8_t uuid[16]
uint32_t version
Macro Definition Documentation
JFS_SUPERBLOCK_OFFSET
#define JFS_SUPERBLOCK_OFFSET 0x8000
Definition at line 42 of file jfs.c.
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_jfs()
int FAST_FUNC volume_id_probe_jfs (struct volume_id * id)
Definition at line 44 of file jfs.c.
 {
 #define off ((uint64_t)0)
     struct jfs_super_block *js;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     js = volume_id_get_buffer(id, off + JFS_SUPERBLOCK_OFFSET, 0x200);
     if (js == NULL)
         return -1;
     if (memcmp(js->magic, "JFS1", 4) != 0)
         return -1;
 //  volume_id_set_label_raw(id, js->label, 16);
     volume_id_set_label_string(id, js->label, 16);
     volume_id_set_uuid(id, js->uuid, UUID_DCE);
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "jfs";)
     return 0;
 }
References dbg, JFS_SUPERBLOCK_OFFSET, js, memcmp(), NULL, off, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct jfs_super_block PACKED