Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/net_server.h File Reference
net_server.h File Reference
Functions
void NET_SV_Init (void)
void NET_SV_Run (void)
void NET_SV_Shutdown (void)
void NET_SV_AddModule (net_module_t *module)
void NET_SV_RegisterWithMaster (void)
Function Documentation
NET_SV_AddModule()
void NET_SV_AddModule (net_module_t * module)
Referenced by D_InitNetGame().
NET_SV_Init()
void NET_SV_Init (void)
Referenced by D_InitNetGame().
NET_SV_RegisterWithMaster()
void NET_SV_RegisterWithMaster (void)
Referenced by D_InitNetGame().
NET_SV_Run()
void NET_SV_Run (void)
Referenced by NetUpdate().
NET_SV_Shutdown()
void NET_SV_Shutdown (void)
Referenced by D_QuitNetGame().