Fennix: Userspace/musl/src/stdio/wprintf.c File Reference
wprintf.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <wchar.h>
Functions
int wprintf (const wchar_t *restrict fmt,...)
Function Documentation
wprintf()
int wprintf (const wchar_t *restrict fmt, ...)
Definition at line 5 of file wprintf.c.
 {
     int ret;
     va_list ap;
     va_start(ap, fmt);
     ret = vwprintf(fmt, ap);
     va_end(ap);
     return ret;
 }
References fmt, ret, va_end(), va_start(), and vwprintf().