Fennix Userspace: Userspace/musl/src/complex/catanl.c File Reference
catanl.c File Reference
#include <complex.h>
#include <float.h>
#include "complex_impl.h"
Functions
static long double redupil (long double x)
long double complex catanl (long double complex z)
Variables
static const long double PIL = 3.141592653589793238462643383279502884197169L
static const long double DP1 = 3.14159265358979323829596852490908531763125L
static const long double DP2 = 1.6667485837041756656403424829301998703007e-19L
static const long double DP3 = 1.8830410776607851167459095484560349402753e-39L
Function Documentation
catanl()
long double complex catanl (long double complex z)
Definition at line 92 of file catanl.c.
 {
     long double complex w;
     long double a, t, x, x2, y;
     x = creall(z);
     y = cimagl(z);
     x2 = x * x;
     a = 1.0L - x2 - (y * y);
     t = atan2l(2.0L * x, a) * 0.5L;
     w = redupil(t);
     t = y - 1.0L;
     a = x2 + (t * t);
     t = y + 1.0L;
     a = (x2 + (t * t)) / a;
     w = CMPLXF(w, 0.25L * logl(a));
     return w;
 }
References atan2l(), cimagl, CMPLXF, complex, creall, logl(), redupil(), t, w, x, and y.
Referenced by catanhl().
redupil()
static long double redupil (long double x) static
Definition at line 75 of file catanl.c.
 {
     long double t;
     long i;
     t = x / PIL;
     if (t >= 0.0L)
         t += 0.5L;
     else
         t -= 0.5L;
     i = t;  /* the multiple */
     t = i;
     t = ((x - t * DP1) - t * DP2) - t * DP3;
     return t;
 }
References DP1, DP2, DP3, i, PIL, t, and x.
Referenced by catanl().
Variable Documentation
DP1
const long double DP1 = 3.14159265358979323829596852490908531763125L static
Definition at line 71 of file catanl.c.
Referenced by redupil().
DP2
const long double DP2 = 1.6667485837041756656403424829301998703007e-19L static
Definition at line 72 of file catanl.c.
Referenced by redupil().
DP3
const long double DP3 = 1.8830410776607851167459095484560349402753e-39L static
Definition at line 73 of file catanl.c.
Referenced by redupil().
PIL
const long double PIL = 3.141592653589793238462643383279502884197169L static
Definition at line 70 of file catanl.c.
Referenced by redupil().