Fennix Userspace: Userspace/apps/base/bash/examples/loadables/basename.c File Reference
basename.c File Reference
#include "config.h"
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
#include "bashgetopt.h"
Functions
int basename_builtin (WORD_LIST *list)
Variables
char * basename_doc []
struct builtin basename_struct
Function Documentation
basename_builtin()
int basename_builtin (WORD_LIST * list)
Definition at line 36 of file basename.c.
 {
   int slen, sufflen, off;
   char *string, *suffix, *fn;
   if (no_options (list))
     return (EX_USAGE);
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   string = list->word->word;
   suffix = (char *)NULL;
   if (list->next)
     {
       list = list->next;
       suffix = list->word->word;
     }
   if (list->next)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   slen = strlen (string);
   /* Strip trailing slashes */
   while (slen > 0 && string[slen - 1] == '/')
     slen--;
   /* (2) If string consists entirely of slash characters, string shall be
      set to a single slash character.  In this case, skip steps (3)
      through (5). */
   if (slen == 0)
     {
       fputs ("/\n", stdout);
       return (EXECUTION_SUCCESS);
     }
   /* (3) If there are any trailing slash characters in string, they
      shall be removed. */
   string[slen] = '\0';
   /* (4) If there are any slash characters remaining in string, the prefix
      of string up to an including the last slash character in string
      shall be removed. */
   while (--slen >= 0)
     if (string[slen] == '/')
       break;
   fn = string + slen + 1;
   /* (5) If the suffix operand is present, is not identical to the
      characters remaining in string, and is identical to a suffix
      of the characters remaining in string, the suffix suffix
      shall be removed from string.  Otherwise, string shall not be
      modified by this step. */
   if (suffix)
     {
       sufflen = strlen (suffix);
       slen = strlen (fn);
       if (sufflen < slen)
         {
           off = slen - sufflen;
           if (strcmp (fn + off, suffix) == 0)
             fn[off] = '\0';
         }
     }
   printf ("%s\n", fn);
   return (EXECUTION_SUCCESS);
 }
References builtin_usage(), EX_USAGE, EXECUTION_SUCCESS, fputs, list(), loptend, node::next, no_options(), NULL, off, printf(), stdout, strcmp, string, and strlen().
Variable Documentation
basename_doc
char* basename_doc[]
Initial value:
= {
    "Return non-directory portion of pathname.",
    "",
    "The STRING is converted to a filename corresponding to the last",
    "pathname component in STRING.  If the suffix string SUFFIX is",
    "supplied, it is removed.",
    (char *)NULL
}
Definition at line 113 of file basename.c.
basename_struct
struct builtin basename_struct
Initial value:
= {
    "basename",
    basename_builtin,
    BUILTIN_ENABLED,
    basename_doc,
    "basename string [suffix]",
    0
}
Definition at line 113 of file basename.c.