Fennix: Userspace/musl/include/resolv.h File Reference
resolv.h File Reference
#include <stdint.h>
#include <arpa/nameser.h>
#include <netinet/in.h>
Data Structures
struct __res_state
struct res_sym
struct __res_state.sort_list
union __res_state._u
struct __res_state._u._ext
Macros
#define MAXNS 3
#define MAXDFLSRCH 3
#define MAXDNSRCH 6
#define LOCALDOMAINPARTS 2
#define RES_TIMEOUT 5
#define MAXRESOLVSORT 10
#define RES_MAXNDOTS 15
#define RES_MAXRETRANS 30
#define RES_MAXRETRY 5
#define RES_DFLRETRY 2
#define RES_MAXTIME 65535
#define nsaddr nsaddr_list[0]
#define __RES 19960801
#define _PATH_RESCONF "/etc/resolv.conf"
#define RES_F_VC 0x00000001
#define RES_F_CONN 0x00000002
#define RES_F_EDNS0ERR 0x00000004
#define RES_EXHAUSTIVE 0x00000001
#define RES_INIT 0x00000001
#define RES_DEBUG 0x00000002
#define RES_AAONLY 0x00000004
#define RES_USEVC 0x00000008
#define RES_PRIMARY 0x00000010
#define RES_IGNTC 0x00000020
#define RES_RECURSE 0x00000040
#define RES_DEFNAMES 0x00000080
#define RES_STAYOPEN 0x00000100
#define RES_DNSRCH 0x00000200
#define RES_INSECURE1 0x00000400
#define RES_INSECURE2 0x00000800
#define RES_NOALIASES 0x00001000
#define RES_USE_INET6 0x00002000
#define RES_ROTATE 0x00004000
#define RES_NOCHECKNAME 0x00008000
#define RES_KEEPTSIG 0x00010000
#define RES_BLAST 0x00020000
#define RES_USEBSTRING 0x00040000
#define RES_NOIP6DOTINT 0x00080000
#define RES_USE_EDNS0 0x00100000
#define RES_SNGLKUP 0x00200000
#define RES_SNGLKUPREOP 0x00400000
#define RES_USE_DNSSEC 0x00800000
#define RES_DEFAULT (RES_RECURSE|RES_DEFNAMES|RES_DNSRCH|RES_NOIP6DOTINT)
#define RES_PRF_STATS 0x00000001
#define RES_PRF_UPDATE 0x00000002
#define RES_PRF_CLASS 0x00000004
#define RES_PRF_CMD 0x00000008
#define RES_PRF_QUES 0x00000010
#define RES_PRF_ANS 0x00000020
#define RES_PRF_AUTH 0x00000040
#define RES_PRF_ADD 0x00000080
#define RES_PRF_HEAD1 0x00000100
#define RES_PRF_HEAD2 0x00000200
#define RES_PRF_TTLID 0x00000400
#define RES_PRF_HEADX 0x00000800
#define RES_PRF_QUERY 0x00001000
#define RES_PRF_REPLY 0x00002000
#define RES_PRF_INIT 0x00004000
#define _res (*__res_state())
Typedefs
typedef struct __res_state * res_state
Functions
struct __res_state * __res_state (void)
int res_init (void)
int res_query (const char *, int, int, unsigned char *, int)
int res_querydomain (const char *, const char *, int, int, unsigned char *, int)
int res_search (const char *, int, int, unsigned char *, int)
int res_mkquery (int, const char *, int, int, const unsigned char *, int, const unsigned char *, unsigned char *, int)
int res_send (const unsigned char *, int, unsigned char *, int)
int dn_comp (const char *, unsigned char *, int, unsigned char **, unsigned char **)
int dn_expand (const unsigned char *, const unsigned char *, const unsigned char *, char *, int)
int dn_skipname (const unsigned char *, const unsigned char *)
Data Structure Documentation
__res_state
struct __res_state
Definition at line 26 of file resolv.h.
Data Fields
unsigned _flags
union __res_state _u
int _vcsock
char defdname[256]
char * dnsrch[MAXDNSRCH+1]
unsigned short id
unsigned ipv6_unavail:1
unsigned ndots:4
struct sockaddr_in nsaddr_list[MAXNS]
int nscount
unsigned nsort:4
unsigned long options
unsigned long pfcode
void * qhook
int res_h_errno
int retrans
int retry
void * rhook
struct __res_state sort_list[MAXRESOLVSORT]
unsigned unused:23
res_sym
struct res_sym
Definition at line 70 of file resolv.h.
Data Fields
char * humanname
char * name
int number
__res_state.sort_list
struct __res_state.sort_list
Definition at line 41 of file resolv.h.
Data Fields
struct in_addr addr
uint32_t mask
__res_state._u
union __res_state._u
Definition at line 50 of file resolv.h.
Data Fields
_u _ext
char pad[52]
__res_state._u._ext
struct __res_state._u._ext
Definition at line 52 of file resolv.h.
Data Fields
unsigned int _initstamp[2]
struct sockaddr_in6 * nsaddrs[MAXNS]
uint16_t nscount
uint16_t nscount6
uint16_t nsinit
uint16_t nsmap[MAXNS]
int nssocks[MAXNS]
Macro Definition Documentation
__RES
#define __RES 19960801
Definition at line 64 of file resolv.h.
_PATH_RESCONF
#define _PATH_RESCONF "/etc/resolv.conf"
Definition at line 67 of file resolv.h.
_res
#define _res (*__res_state())
Definition at line 126 of file resolv.h.
LOCALDOMAINPARTS
#define LOCALDOMAINPARTS 2
Definition at line 15 of file resolv.h.
MAXDFLSRCH
#define MAXDFLSRCH 3
Definition at line 13 of file resolv.h.
MAXDNSRCH
#define MAXDNSRCH 6
Definition at line 14 of file resolv.h.
MAXNS
#define MAXNS 3
Definition at line 12 of file resolv.h.
MAXRESOLVSORT
#define MAXRESOLVSORT 10
Definition at line 18 of file resolv.h.
nsaddr
#define nsaddr nsaddr_list[0]
Definition at line 32 of file resolv.h.
RES_AAONLY
#define RES_AAONLY 0x00000004
Definition at line 84 of file resolv.h.
RES_BLAST
#define RES_BLAST 0x00020000
Definition at line 99 of file resolv.h.
RES_DEBUG
#define RES_DEBUG 0x00000002
Definition at line 83 of file resolv.h.
RES_DEFAULT
#define RES_DEFAULT (RES_RECURSE|RES_DEFNAMES|RES_DNSRCH|RES_NOIP6DOTINT)
Definition at line 107 of file resolv.h.
RES_DEFNAMES
#define RES_DEFNAMES 0x00000080
Definition at line 89 of file resolv.h.
RES_DFLRETRY
#define RES_DFLRETRY 2
Definition at line 22 of file resolv.h.
RES_DNSRCH
#define RES_DNSRCH 0x00000200
Definition at line 91 of file resolv.h.
RES_EXHAUSTIVE
#define RES_EXHAUSTIVE 0x00000001
Definition at line 80 of file resolv.h.
RES_F_CONN
#define RES_F_CONN 0x00000002
Definition at line 77 of file resolv.h.
RES_F_EDNS0ERR
#define RES_F_EDNS0ERR 0x00000004
Definition at line 78 of file resolv.h.
RES_F_VC
#define RES_F_VC 0x00000001
Definition at line 76 of file resolv.h.
RES_IGNTC
#define RES_IGNTC 0x00000020
Definition at line 87 of file resolv.h.
RES_INIT
#define RES_INIT 0x00000001
Definition at line 82 of file resolv.h.
RES_INSECURE1
#define RES_INSECURE1 0x00000400
Definition at line 92 of file resolv.h.
RES_INSECURE2
#define RES_INSECURE2 0x00000800
Definition at line 93 of file resolv.h.
RES_KEEPTSIG
#define RES_KEEPTSIG 0x00010000
Definition at line 98 of file resolv.h.
RES_MAXNDOTS
#define RES_MAXNDOTS 15
Definition at line 19 of file resolv.h.
RES_MAXRETRANS
#define RES_MAXRETRANS 30
Definition at line 20 of file resolv.h.
RES_MAXRETRY
#define RES_MAXRETRY 5
Definition at line 21 of file resolv.h.
RES_MAXTIME
#define RES_MAXTIME 65535
Definition at line 23 of file resolv.h.
RES_NOALIASES
#define RES_NOALIASES 0x00001000
Definition at line 94 of file resolv.h.
RES_NOCHECKNAME
#define RES_NOCHECKNAME 0x00008000
Definition at line 97 of file resolv.h.
RES_NOIP6DOTINT
#define RES_NOIP6DOTINT 0x00080000
Definition at line 101 of file resolv.h.
RES_PRF_ADD
#define RES_PRF_ADD 0x00000080
Definition at line 116 of file resolv.h.
RES_PRF_ANS
#define RES_PRF_ANS 0x00000020
Definition at line 114 of file resolv.h.
RES_PRF_AUTH
#define RES_PRF_AUTH 0x00000040
Definition at line 115 of file resolv.h.
RES_PRF_CLASS
#define RES_PRF_CLASS 0x00000004
Definition at line 111 of file resolv.h.
RES_PRF_CMD
#define RES_PRF_CMD 0x00000008
Definition at line 112 of file resolv.h.
RES_PRF_HEAD1
#define RES_PRF_HEAD1 0x00000100
Definition at line 117 of file resolv.h.
RES_PRF_HEAD2
#define RES_PRF_HEAD2 0x00000200
Definition at line 118 of file resolv.h.
RES_PRF_HEADX
#define RES_PRF_HEADX 0x00000800
Definition at line 120 of file resolv.h.
RES_PRF_INIT
#define RES_PRF_INIT 0x00004000
Definition at line 123 of file resolv.h.
RES_PRF_QUERY
#define RES_PRF_QUERY 0x00001000
Definition at line 121 of file resolv.h.
RES_PRF_QUES
#define RES_PRF_QUES 0x00000010
Definition at line 113 of file resolv.h.
RES_PRF_REPLY
#define RES_PRF_REPLY 0x00002000
Definition at line 122 of file resolv.h.
RES_PRF_STATS
#define RES_PRF_STATS 0x00000001
Definition at line 109 of file resolv.h.
RES_PRF_TTLID
#define RES_PRF_TTLID 0x00000400
Definition at line 119 of file resolv.h.
RES_PRF_UPDATE
#define RES_PRF_UPDATE 0x00000002
Definition at line 110 of file resolv.h.
RES_PRIMARY
#define RES_PRIMARY 0x00000010
Definition at line 86 of file resolv.h.
RES_RECURSE
#define RES_RECURSE 0x00000040
Definition at line 88 of file resolv.h.
RES_ROTATE
#define RES_ROTATE 0x00004000
Definition at line 96 of file resolv.h.
RES_SNGLKUP
#define RES_SNGLKUP 0x00200000
Definition at line 103 of file resolv.h.
RES_SNGLKUPREOP
#define RES_SNGLKUPREOP 0x00400000
Definition at line 104 of file resolv.h.
RES_STAYOPEN
#define RES_STAYOPEN 0x00000100
Definition at line 90 of file resolv.h.
RES_TIMEOUT
#define RES_TIMEOUT 5
Definition at line 17 of file resolv.h.
RES_USE_DNSSEC
#define RES_USE_DNSSEC 0x00800000
Definition at line 105 of file resolv.h.
RES_USE_EDNS0
#define RES_USE_EDNS0 0x00100000
Definition at line 102 of file resolv.h.
RES_USE_INET6
#define RES_USE_INET6 0x00002000
Definition at line 95 of file resolv.h.
RES_USEBSTRING
#define RES_USEBSTRING 0x00040000
Definition at line 100 of file resolv.h.
RES_USEVC
#define RES_USEVC 0x00000008
Definition at line 85 of file resolv.h.
Typedef Documentation
res_state
typedef struct __res_state * res_state
Function Documentation
__res_state()
struct __res_state* __res_state (void)
Definition at line 5 of file res_state.c.
 {
     static struct __res_state res;
     return &res;
 }
dn_comp()
int dn_comp (const char * src, unsigned char * dst, int space, unsigned char ** dnptrs, unsigned char ** lastdnptr)
Definition at line 57 of file dn_comp.c.
 {
     int i, j, n, m=0, offset, bestlen=0, bestoff;
     unsigned char lens[127];
     unsigned char **p;
     const char *end;
     size_t l = strnlen(src, 255);
     if (l && src[l-1] == '.') l--;
     if (l>253 || space<=0) return -1;
     if (!l) {
         *dst = 0;
         return 1;
     }
     end = src+l;
     n = getlens(lens, src, l);
     if (!n) return -1;
     p = dnptrs;
     if (p && *p) for (p++; *p; p++) {
         m = match(&offset, *dnptrs, *p, end, lens, n);
         if (m > bestlen) {
             bestlen = m;
             bestoff = offset;
             if (m == l)
                 break;
         }
     }
     /* encode unmatched part */
     if (space < l-bestlen+2+(bestlen-1 < l-1)) return -1;
     memcpy(dst+1, src, l-bestlen);
     for (i=j=0; i<l-bestlen; i+=lens[j++]+1)
         dst[i] = lens[j];
     /* add tail */
     if (bestlen) {
         dst[i++] = 0xc0 | bestoff>>8;
         dst[i++] = bestoff;
     } else
         dst[i++] = 0;
     /* save dst pointer */
     if (i>2 && lastdnptr && dnptrs && *dnptrs) {
         while (*p) p++;
         if (p+1 < lastdnptr) {
             *p++ = dst;
             *p=0;
         }
     }
     return i;
 }
References dst, end, getlens(), i, j, l, match(), memcpy, n, offset, p, src, and strnlen().
dn_expand()
int dn_expand (const unsigned char * , const unsigned char * , const unsigned char * , char * , int)
Referenced by ns_name_uncompress().
dn_skipname()
int dn_skipname (const unsigned char * s, const unsigned char * end)
Definition at line 3 of file dn_skipname.c.
 {
     const unsigned char *p = s;
     while (p < end)
         if (!*p) return p-s+1;
         else if (*p>=192)
             if (p+1<end) return p-s+2;
             else break;
         else
             if (end-p<*p+1) break;
             else p += *p + 1;
     return -1;
 }
References end, p, and s.
Referenced by ns_skiprr().
res_init()
int res_init (void)
Definition at line 3 of file res_init.c.
 {
     return 0;
 }
Referenced by INET_resolve(), and nslookup_main().
res_mkquery()
int res_mkquery (int , const char * , int , int , const unsigned char * , int , const unsigned char * , unsigned char * , int)
res_query()
int res_query (const char * name, int class, int type, unsigned char * dest, int len)
Definition at line 5 of file res_query.c.
 {
     unsigned char q[280];
     int ql = __res_mkquery(0, name, class, type, 0, 0, 0, q, sizeof q);
     if (ql < 0) return ql;
     int r = __res_send(q, ql, dest, len);
     if (r<12) {
         h_errno = TRY_AGAIN;
         return -1;
     }
     if ((dest[3] & 15) == 3) {
         h_errno = HOST_NOT_FOUND;
         return -1;
     }
     if ((dest[3] & 15) == 0 && !dest[6] && !dest[7]) {
         h_errno = NO_DATA;
         return -1;
     }
     return r;
 }
References __res_mkquery(), __res_send(), h_errno, len, and type.
Referenced by res_querydomain().
res_querydomain()
int res_querydomain (const char * name, const char * domain, int class, int type, unsigned char * dest, int len)
Definition at line 4 of file res_querydomain.c.
 {
     char tmp[255];
     size_t nl = strnlen(name, 255);
     size_t dl = strnlen(domain, 255);
     if (nl+dl+1 > 254) return -1;
     memcpy(tmp, name, nl);
     tmp[nl] = '.';
     memcpy(tmp+nl+1, domain, dl+1);
     return res_query(tmp, class, type, dest, len);
 }
References domain, len, memcpy, res_query(), strnlen(), and type.
res_search()
int res_search (const char * , int , int , unsigned char * , int)
res_send()
int res_send (const unsigned char * , int , unsigned char * , int)