Fennix: Userspace/apps/base/bash/lib/readline/vi_mode.c File Reference
vi_mode.c File Reference
#include "rlconf.h"
#include <sys/types.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "rlmbutil.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define member(c, s) ((c) ? (char *)strchr ((s), (c)) != (char *)NULL : 0)
#define INCREMENT_POS(start) (start)++
#define RL_VIMOVENUMARG() (RL_ISSTATE (RL_STATE_VIMOTION) && RL_ISSTATE (RL_STATE_NUMERICARG))
#define vi_unix_word_boundary(c) (whitespace(c) || ispunct(c))
Functions
static void _rl_vi_replace_insert (int)
static void _rl_vi_save_replace (void)
static void _rl_vi_stuff_insert (int)
static void _rl_vi_save_insert (UNDO_LIST *)
static void vi_save_insert_buffer (int, int)
static void _rl_vi_backup (void)
static int _rl_vi_arg_dispatch (int)
static int rl_digit_loop1 (void)
static int _rl_vi_set_mark (void)
static int _rl_vi_goto_mark (void)
static int _rl_vi_advance_point (void)
static int _rl_vi_backup_point (void)
static void _rl_vi_append_forward (int)
static int _rl_vi_callback_getchar (char *, int)
static int _rl_vi_callback_set_mark (_rl_callback_generic_arg *)
static int _rl_vi_callback_goto_mark (_rl_callback_generic_arg *)
static int _rl_vi_callback_change_char (_rl_callback_generic_arg *)
static int _rl_vi_callback_char_search (_rl_callback_generic_arg *)
static int rl_domove_read_callback (_rl_vimotion_cxt *)
static int rl_domove_motion_callback (_rl_vimotion_cxt *)
static int rl_vi_domove_getchar (_rl_vimotion_cxt *)
static int vi_change_dispatch (_rl_vimotion_cxt *)
static int vi_delete_dispatch (_rl_vimotion_cxt *)
static int vi_yank_dispatch (_rl_vimotion_cxt *)
static int vidomove_dispatch (_rl_vimotion_cxt *)
void _rl_vi_initialize_line (void)
void _rl_vi_reset_last (void)
void _rl_vi_set_last (int key, int repeat, int sign)
void rl_vi_start_inserting (int key, int repeat, int sign)
int _rl_vi_textmod_command (int c)
int _rl_vi_motion_command (int c)
int rl_vi_redo (int count, int c)
int rl_vi_undo (int count, int key)
int rl_vi_yank_arg (int count, int key)
int rl_vi_fetch_history (int count, int c)
int rl_vi_search_again (int count, int key)
int rl_vi_search (int count, int key)
int rl_vi_complete (int ignore, int key)
int rl_vi_tilde_expand (int ignore, int key)
int rl_vi_prev_word (int count, int key)
int rl_vi_next_word (int count, int key)
int rl_vi_end_word (int count, int key)
int rl_vi_fWord (int count, int ignore)
int rl_vi_bWord (int count, int ignore)
int rl_vi_eWord (int count, int ignore)
int rl_vi_fword (int count, int ignore)
int rl_vi_bword (int count, int ignore)
int rl_vi_eword (int count, int ignore)
int rl_vi_insert_beg (int count, int key)
int rl_vi_append_mode (int count, int key)
int rl_vi_append_eol (int count, int key)
int rl_vi_eof_maybe (int count, int c)
int rl_vi_insertion_mode (int count, int key)
int rl_vi_insert_mode (int count, int key)
void _rl_vi_done_inserting (void)
int rl_vi_movement_mode (int count, int key)
int rl_vi_arg_digit (int count, int c)
int rl_vi_change_case (int count, int ignore)
int rl_vi_put (int count, int key)
int rl_vi_check (void)
int rl_vi_column (int count, int key)
static void _rl_mvcxt_init (_rl_vimotion_cxt *m, int op, int key)
static _rl_vimotion_cxt * _rl_mvcxt_alloc (int op, int key)
static void _rl_mvcxt_dispose (_rl_vimotion_cxt *m)
int _rl_vi_domove_motion_cleanup (int c, _rl_vimotion_cxt *m)
int _rl_vi_domove_callback (_rl_vimotion_cxt *m)
int rl_vi_domove (int x, int *ignore)
int rl_vi_delete_to (int count, int key)
int rl_vi_change_to (int count, int key)
int rl_vi_yank_to (int count, int key)
int rl_vi_rubout (int count, int key)
int rl_vi_delete (int count, int key)
int rl_vi_unix_word_rubout (int count, int key)
int rl_vi_back_to_indent (int count, int key)
int rl_vi_first_print (int count, int key)
int rl_vi_char_search (int count, int key)
int rl_vi_match (int ignore, int key)
int rl_vi_bracktype (int c)
static int _rl_vi_change_char (int count, int c, char *mb)
int rl_vi_change_char (int count, int key)
int rl_vi_subst (int count, int key)
int rl_vi_overstrike (int count, int key)
int rl_vi_overstrike_delete (int count, int key)
static int rl_vi_overstrike_kill_line (int count, int key)
static int rl_vi_overstrike_kill_word (int count, int key)
static int rl_vi_overstrike_yank (int count, int key)
static int rl_vi_overstrike_bracketed_paste (int count, int key)
int rl_vi_replace (int count, int key)
int rl_vi_set_mark (int count, int key)
int rl_vi_goto_mark (int count, int key)
Variables
int _rl_vi_last_command = 'i'
_rl_vimotion_cxt * _rl_vimvcxt = 0
int _rl_vi_redoing
static int _rl_vi_doing_insert
static const char *const vi_motion = " hl^$0ftFT;,%wbeWBE|`"
static Keymap vi_replace_map
static int vi_replace_count
static int vi_continued_command
static char * vi_insert_buffer
static int vi_insert_buffer_size
static int _rl_vi_last_repeat = 1
static int _rl_vi_last_arg_sign = 1
static int _rl_vi_last_motion
static int _rl_vi_last_search_char
static char _rl_vi_last_replacement [MB_LEN_MAX+1]
static int _rl_vi_last_key_before_insert
static const char *const vi_textmod = "_*\\AaIiCcDdPpYyRrSsXx~"
static int vi_mark_chars ['z' - 'a'+1]
static int _rl_cs_dir
static int _rl_cs_orig_dir
Macro Definition Documentation
INCREMENT_POS
#define INCREMENT_POS (start) (start)++
Definition at line 76 of file vi_mode.c.
member
#define member (c, s) ((c) ? (char *)strchr ((s), (c)) != (char *)NULL : 0)
Definition at line 63 of file vi_mode.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 23 of file vi_mode.c.
RL_VIMOVENUMARG
#define RL_VIMOVENUMARG () (RL_ISSTATE (RL_STATE_VIMOTION) && RL_ISSTATE (RL_STATE_NUMERICARG))
Definition at line 1250 of file vi_mode.c.
vi_unix_word_boundary
#define vi_unix_word_boundary (c) (whitespace(c) || ispunct(c))
Definition at line 1697 of file vi_mode.c.
Function Documentation
_rl_mvcxt_alloc()
static _rl_vimotion_cxt* _rl_mvcxt_alloc (int op, int key) static
Definition at line 1138 of file vi_mode.c.
 {
   _rl_vimotion_cxt *m;
   m = xmalloc (sizeof (_rl_vimotion_cxt));
   _rl_mvcxt_init (m, op, key);
   return m;
 }
References _rl_mvcxt_init(), and xmalloc.
Referenced by rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
_rl_mvcxt_dispose()
static void _rl_mvcxt_dispose (_rl_vimotion_cxt * m) static
Definition at line 1148 of file vi_mode.c.
 {
   xfree (m);
 }
References xfree.
Referenced by rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
_rl_mvcxt_init()
static void _rl_mvcxt_init (_rl_vimotion_cxt * m, int op, int key) static
Definition at line 1125 of file vi_mode.c.
 {
   m->op = op;
   m->state = m->flags = 0;
   m->ncxt = 0;
   m->numeric_arg = -1;
   m->start = rl_point;
   m->end = rl_end;
   m->key = key;
   m->motion = -1;
 }
References __rl_vimotion_context::end, __rl_vimotion_context::flags, __rl_vimotion_context::key, __rl_vimotion_context::motion, __rl_vimotion_context::ncxt, __rl_vimotion_context::numeric_arg, __rl_vimotion_context::op, rl_end, rl_point, __rl_vimotion_context::start, and __rl_vimotion_context::state.
Referenced by _rl_mvcxt_alloc(), rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
_rl_vi_advance_point()
static int _rl_vi_advance_point (void) inline static
Definition at line 460 of file vi_mode.c.
 {
   int point;
   point = rl_point;
   if (rl_point < rl_end)
 #if defined (HANDLE_MULTIBYTE)
     {
       if (MB_CUR_MAX == 1 || rl_byte_oriented)
     rl_point++;
       else
     {
       point = rl_point;
       rl_point = _rl_forward_char_internal (1);
       if (point == rl_point || rl_point > rl_end)
         rl_point = rl_end;
     }
     }
 #else
     rl_point++;
 #endif
   return point;
 }
References _rl_forward_char_internal(), MB_CUR_MAX, rl_byte_oriented, rl_end, and rl_point.
Referenced by _rl_vi_append_forward(), _rl_vi_domove_motion_cleanup(), rl_vi_complete(), rl_vi_eWord(), rl_vi_eword(), rl_vi_fWord(), and rl_vi_fword().
_rl_vi_append_forward()
static void _rl_vi_append_forward (int key) static
Definition at line 746 of file vi_mode.c.
 {
   _rl_vi_advance_point ();
 }
References _rl_vi_advance_point().
Referenced by _rl_vi_change_char(), rl_vi_append_mode(), and rl_vi_redo().
_rl_vi_arg_dispatch()
static int _rl_vi_arg_dispatch (int c) static
Definition at line 1066 of file vi_mode.c.
 {
   int key;
   key = c;
   if (c >= 0 && _rl_keymap[c].type == ISFUNC && _rl_keymap[c].function == rl_universal_argument)
     {
       rl_numeric_arg *= 4;
       return 1;
     }
   c = UNMETA (c);
   if (_rl_digit_p (c))
     {
       if (rl_explicit_arg)
     rl_numeric_arg = (rl_numeric_arg * 10) + _rl_digit_value (c);
       else
     rl_numeric_arg = _rl_digit_value (c);
       rl_explicit_arg = 1;
       return 1;     /* keep going */
     }
   else
     {
       rl_clear_message ();
       rl_stuff_char (key);
       return 0;     /* done */
     }
 }
References _rl_digit_p(), _rl_digit_value(), _rl_keymap, c, ISFUNC, rl_clear_message(), rl_explicit_arg, rl_numeric_arg, rl_stuff_char(), rl_universal_argument(), type, and UNMETA.
Referenced by rl_digit_loop1(), and rl_domove_read_callback().
_rl_vi_backup()
static void _rl_vi_backup (void) inline static
Definition at line 487 of file vi_mode.c.
 {
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_point = _rl_find_prev_mbchar (rl_line_buffer, rl_point, MB_FIND_NONZERO);
   else
     rl_point--;
 }
References _rl_find_prev_mbchar, MB_CUR_MAX, MB_FIND_NONZERO, rl_byte_oriented, rl_line_buffer, and rl_point.
Referenced by rl_vi_check(), and rl_vi_redo().
_rl_vi_backup_point()
static int _rl_vi_backup_point (void) inline static
Definition at line 498 of file vi_mode.c.
 {
   int point;
   point = rl_point;
   if (rl_point > 0)
 #if defined (HANDLE_MULTIBYTE)
     {
       if (MB_CUR_MAX == 1 || rl_byte_oriented)
     rl_point--;
       else
     {
       point = rl_point;
       rl_point = _rl_backward_char_internal (1);
       if (rl_point < 0)
         rl_point = 0;       /* XXX - not really necessary */
     }
     }
 #else
     rl_point--;
 #endif
   return point;
 }
References _rl_backward_char_internal(), MB_CUR_MAX, rl_byte_oriented, and rl_point.
Referenced by rl_vi_bWord(), rl_vi_bword(), and rl_vi_unix_word_rubout().
_rl_vi_callback_change_char()
static int _rl_vi_callback_change_char (_rl_callback_generic_arg * data) static
Definition at line 2037 of file vi_mode.c.
 {
   int c;
   char mb[MB_LEN_MAX+1];
   c = _rl_vi_callback_getchar (mb, MB_LEN_MAX);
   if (c < 0)
     return -1;
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     strncpy (_rl_vi_last_replacement, mb, MB_LEN_MAX);
   else
 #endif
     _rl_vi_last_replacement[0] = c;
   _rl_vi_last_replacement[MB_LEN_MAX] = '\0';   /* XXX */
   _rl_callback_func = 0;
   _rl_want_redisplay = 1;
   return (_rl_vi_change_char (data->count, c, mb));
 }
References _rl_callback_func, _rl_vi_callback_getchar(), _rl_vi_change_char(), _rl_vi_last_replacement, _rl_want_redisplay, c, __rl_callback_generic_arg::count, MB_CUR_MAX, MB_LEN_MAX, rl_byte_oriented, and strncpy().
Referenced by rl_vi_change_char().
_rl_vi_callback_char_search()
static int _rl_vi_callback_char_search (_rl_callback_generic_arg * data) static
Definition at line 1768 of file vi_mode.c.
 {
   int c;
 #if defined (HANDLE_MULTIBYTE)
   c = _rl_vi_last_search_mblen = _rl_read_mbchar (_rl_vi_last_search_mbchar, MB_LEN_MAX);
 #else
   RL_SETSTATE(RL_STATE_MOREINPUT);
   c = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
 #endif
   if (c <= 0)
     {
       RL_UNSETSTATE (RL_STATE_CHARSEARCH);
       return -1;
     }
 #if !defined (HANDLE_MULTIBYTE)
   _rl_vi_last_search_char = c;
 #endif
   _rl_callback_func = 0;
   _rl_want_redisplay = 1;
   RL_UNSETSTATE (RL_STATE_CHARSEARCH);
 #if defined (HANDLE_MULTIBYTE)
   return (_rl_char_search_internal (data->count, _rl_cs_dir, _rl_vi_last_search_mbchar, _rl_vi_last_search_mblen));
 #else
   return (_rl_char_search_internal (data->count, _rl_cs_dir, _rl_vi_last_search_char));
 #endif
 }
References _rl_callback_func, _rl_char_search_internal(), _rl_cs_dir, _rl_vi_last_search_char, _rl_want_redisplay, c, __rl_callback_generic_arg::count, MB_LEN_MAX, rl_read_key(), RL_SETSTATE, RL_STATE_CHARSEARCH, RL_STATE_MOREINPUT, and RL_UNSETSTATE.
Referenced by rl_vi_char_search().
_rl_vi_callback_getchar()
static int _rl_vi_callback_getchar (char * mb, int mlen) static
Definition at line 2030 of file vi_mode.c.
 {
   return (_rl_bracketed_read_mbstring (mb, mlen));
 }
References _rl_bracketed_read_mbstring().
Referenced by _rl_vi_callback_change_char(), and rl_vi_change_char().
_rl_vi_callback_goto_mark()
static int _rl_vi_callback_goto_mark (_rl_callback_generic_arg * data) static
Definition at line 2392 of file vi_mode.c.
 {
   _rl_callback_func = 0;
   _rl_want_redisplay = 1;
   return (_rl_vi_goto_mark ());
 }
References _rl_callback_func, _rl_vi_goto_mark(), and _rl_want_redisplay.
Referenced by rl_vi_goto_mark().
_rl_vi_callback_set_mark()
static int _rl_vi_callback_set_mark (_rl_callback_generic_arg * data) static
Definition at line 2334 of file vi_mode.c.
 {
   _rl_callback_func = 0;
   _rl_want_redisplay = 1;
   return (_rl_vi_set_mark ());
 }
References _rl_callback_func, _rl_vi_set_mark(), and _rl_want_redisplay.
Referenced by rl_vi_set_mark().
_rl_vi_change_char()
static int _rl_vi_change_char (int count, int c, char * mb) static
Definition at line 1999 of file vi_mode.c.
 {
   int p;
   if (c == '\033' || c == CTRL ('C'))
     return -1;
   rl_begin_undo_group ();
   while (count-- && rl_point < rl_end)
     {
       p = rl_point;
       rl_vi_delete (1, c);
       if (rl_point < p)     /* Did we retreat at EOL? */
     _rl_vi_append_forward (c);
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_insert_text (mb);
       else
 #endif
     _rl_insert_char (1, c);
     }
   /* The cursor shall be left on the last character changed. */
   rl_backward_char (1, c);
   rl_end_undo_group ();
   return (0);
 }
References _rl_insert_char(), _rl_vi_append_forward(), c, count, CTRL, MB_CUR_MAX, p, rl_backward_char(), rl_begin_undo_group(), rl_byte_oriented, rl_end, rl_end_undo_group(), rl_insert_text(), rl_point, and rl_vi_delete().
Referenced by _rl_vi_callback_change_char(), and rl_vi_change_char().
_rl_vi_domove_callback()
int _rl_vi_domove_callback (_rl_vimotion_cxt * m)
Definition at line 1326 of file vi_mode.c.
 {
   int c, r;
   m->motion = c = rl_vi_domove_getchar (m);
   if (c < 0)
     return 1;       /* EOF */
   r = rl_domove_read_callback (m);
   return ((r == 0) ? r : 1);    /* normalize return values */
 }
References c, __rl_vimotion_context::motion, rl_domove_read_callback(), and rl_vi_domove_getchar().
Referenced by rl_callback_read_char().
_rl_vi_domove_motion_cleanup()
int _rl_vi_domove_motion_cleanup (int c, _rl_vimotion_cxt * m)
Definition at line 1188 of file vi_mode.c.
 {
   int r;
   /* Remove the blank that we added in rl_domove_motion_callback. */
   rl_end = m->end;
   rl_line_buffer[rl_end] = '\0';
   _rl_fix_point (0);
   /* No change in position means the command failed. */
   if (rl_mark == rl_point)
     {
       /* 'c' and 'C' enter insert mode after the delete even if the motion
      didn't delete anything, as long as the motion command is valid. */
       if (_rl_to_upper (m->key) == 'C' && _rl_vi_motion_command (c))
     return (vidomove_dispatch (m));
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       return (-1);
     }
   /* rl_vi_f[wW]ord () leaves the cursor on the first character of the next
      word.  If we are not at the end of the line, and we are on a
      non-whitespace character, move back one (presumably to whitespace). */
   if ((_rl_to_upper (c) == 'W') && rl_point < rl_end && rl_point > rl_mark &&
       !whitespace (rl_line_buffer[rl_point]))
     rl_point--;     /* XXX */
   /* If cw or cW, back up to the end of a word, so the behaviour of ce
      or cE is the actual result.  Brute-force, no subtlety. */
   if (m->key == 'c' && rl_point >= rl_mark && (_rl_to_upper (c) == 'W'))
     {
       /* Don't move farther back than where we started. */
       while (rl_point > rl_mark && whitespace (rl_line_buffer[rl_point]))
     rl_point--;
       /* Posix.2 says that if cw or cW moves the cursor towards the end of
      the line, the character under the cursor should be deleted. */
       if (rl_point == rl_mark)
     _rl_vi_advance_point ();
       else
     {
       /* Move past the end of the word so that the kill doesn't
          remove the last letter of the previous word.  Only do this
          if we are not at the end of the line. */
       if (rl_point >= 0 && rl_point < (rl_end - 1) && !whitespace (rl_line_buffer[rl_point]))
         _rl_vi_advance_point ();
     }
     }
   if (rl_mark < rl_point)
     SWAP (rl_point, rl_mark);
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     (*rl_redisplay_function)();     /* make sure motion is displayed */
 #endif
   r = vidomove_dispatch (m);
   return (r);
 }
References _rl_fix_point(), _rl_to_upper(), _rl_vi_advance_point(), _rl_vi_motion_command(), c, __rl_vimotion_context::end, __rl_vimotion_context::key, rl_end, RL_ISSTATE, rl_line_buffer, rl_mark, rl_point, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, SWAP, vidomove_dispatch(), and whitespace.
Referenced by rl_callback_read_char(), and rl_domove_motion_callback().
_rl_vi_done_inserting()
void _rl_vi_done_inserting (void)
Definition at line 857 of file vi_mode.c.
 {
   if (_rl_vi_doing_insert)
     {
       /* The `c', `s', `S', and `R' commands set this. */
       rl_end_undo_group (); /* for the group in rl_vi_start_inserting */
       /* Now, the text between rl_undo_list->next->start and
      rl_undo_list->next->end is what was inserted while in insert
      mode.  It gets copied to VI_INSERT_BUFFER because it depends
      on absolute indices into the line which may change (though they
      probably will not). */
       _rl_vi_doing_insert = 0;
       if (_rl_vi_last_key_before_insert == 'R')
     _rl_vi_save_replace ();     /* Half the battle */
       else
     _rl_vi_save_insert (rl_undo_list->next);
       /* sanity check, should always be >= 1 here */
       if (_rl_undo_group_level > 0)
     rl_end_undo_group ();   /* for the group in the command (change or replace) */
     }
   else
     {
       if (rl_undo_list && (_rl_vi_last_key_before_insert == 'i' ||
                _rl_vi_last_key_before_insert == 'a' ||
                _rl_vi_last_key_before_insert == 'I' ||
                _rl_vi_last_key_before_insert == 'A'))
     _rl_vi_save_insert (rl_undo_list);
       /* XXX - Other keys probably need to be checked. */
       else if (_rl_vi_last_key_before_insert == 'C')
     rl_end_undo_group ();
     }
   /* Sanity check, make sure all the undo groups are closed before we leave
      insert mode */
   while (_rl_undo_group_level > 0)
     rl_end_undo_group ();
 }
References _rl_undo_group_level, _rl_vi_doing_insert, _rl_vi_last_key_before_insert, _rl_vi_save_insert(), _rl_vi_save_replace(), undo_list::next, rl_end_undo_group(), and rl_undo_list.
Referenced by rl_newline(), and rl_vi_movement_mode().
_rl_vi_goto_mark()
static int _rl_vi_goto_mark (void) static
Definition at line 2359 of file vi_mode.c.
 {
   int ch;
   RL_SETSTATE(RL_STATE_MOREINPUT);
   ch = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   if (ch == '`')
     {
       rl_point = rl_mark;
       _rl_fix_point (1);
       return 0;
     }
   else if (ch < 0 || ch < 'a' || ch > 'z')  /* make test against 0 explicit */
     {
       rl_ding ();
       return 1;
     }
   ch -= 'a';
   if (vi_mark_chars[ch] == -1)
     {
       rl_ding ();
       return 1;
     }
   rl_point = vi_mark_chars[ch];
   _rl_fix_point (1);
   return 0;
 }
References _rl_fix_point(), rl_ding(), rl_mark, rl_point, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, RL_UNSETSTATE, and vi_mark_chars.
Referenced by _rl_vi_callback_goto_mark(), and rl_vi_goto_mark().
_rl_vi_initialize_line()
void _rl_vi_initialize_line (void)
Definition at line 167 of file vi_mode.c.
 {
   register int i, n;
   n = sizeof (vi_mark_chars) / sizeof (vi_mark_chars[0]);
   for (i = 0; i < n; i++)
     vi_mark_chars[i] = -1;
   RL_UNSETSTATE(RL_STATE_VICMDONCE);
 }
References i, n, RL_STATE_VICMDONCE, RL_UNSETSTATE, and vi_mark_chars.
Referenced by rl_initialize().
_rl_vi_motion_command()
int _rl_vi_motion_command (int c)
Definition at line 213 of file vi_mode.c.
 {
   return (member (c, vi_motion));
 }
References c, member, and vi_motion.
Referenced by _rl_vi_domove_motion_cleanup().
_rl_vi_replace_insert()
static void _rl_vi_replace_insert (int count) static
Definition at line 219 of file vi_mode.c.
 {
   int nchars;
   nchars = strlen (vi_insert_buffer);
   rl_begin_undo_group ();
   while (count--)
     /* nchars-1 to compensate for _rl_replace_text using `end+1' in call
        to rl_delete_text */
     _rl_replace_text (vi_insert_buffer, rl_point, rl_point+nchars-1);
   rl_end_undo_group ();
 }
References _rl_replace_text(), count, rl_begin_undo_group(), rl_end_undo_group(), rl_point, strlen(), and vi_insert_buffer.
Referenced by rl_vi_redo().
_rl_vi_reset_last()
void _rl_vi_reset_last (void)
Definition at line 179 of file vi_mode.c.
 {
   _rl_vi_last_command = 'i';
   _rl_vi_last_repeat = 1;
   _rl_vi_last_arg_sign = 1;
   _rl_vi_last_motion = 0;
 }
References _rl_vi_last_arg_sign, _rl_vi_last_command, _rl_vi_last_motion, and _rl_vi_last_repeat.
Referenced by rl_newline().
_rl_vi_save_insert()
static void _rl_vi_save_insert (UNDO_LIST * up) static
Definition at line 838 of file vi_mode.c.
 {
   int len, start, end;
   if (up == 0 || up->what != UNDO_INSERT)
     {
       if (vi_insert_buffer_size >= 1)
     vi_insert_buffer[0] = '\0';
       return;
     }
   start = up->start;
   end = up->end;
   len = end - start + 1;
   vi_save_insert_buffer (start, len);
 }
References end, len, start, UNDO_INSERT, up, vi_insert_buffer, vi_insert_buffer_size, and vi_save_insert_buffer().
Referenced by _rl_vi_done_inserting().
_rl_vi_save_replace()
static void _rl_vi_save_replace (void) static
Definition at line 809 of file vi_mode.c.
 {
   int len, start, end;
   UNDO_LIST *up;
   up = rl_undo_list;
   if (up == 0 || up->what != UNDO_END || vi_replace_count <= 0)
     {
       if (vi_insert_buffer_size >= 1)
     vi_insert_buffer[0] = '\0';
       return;
     }
   /* Let's try it the quick and easy way for now.  This should essentially
      accommodate every UNDO_INSERT and save the inserted text to
      vi_insert_buffer */
   end = rl_point;
   start = end - vi_replace_count + 1;
   len = vi_replace_count + 1;
   if (start < 0)
     {
       len = end + 1;
       start = 0;
     }
   vi_save_insert_buffer (start, len);
 }
References end, len, rl_point, rl_undo_list, start, UNDO_END, up, vi_insert_buffer, vi_insert_buffer_size, vi_replace_count, and vi_save_insert_buffer().
Referenced by _rl_vi_done_inserting().
_rl_vi_set_last()
void _rl_vi_set_last (int key, int repeat, int sign)
Definition at line 188 of file vi_mode.c.
 {
   _rl_vi_last_command = key;
   _rl_vi_last_repeat = repeat;
   _rl_vi_last_arg_sign = sign;
 }
References _rl_vi_last_arg_sign, _rl_vi_last_command, and _rl_vi_last_repeat.
Referenced by _rl_dispatch_subseq(), and rl_vi_start_inserting().
_rl_vi_set_mark()
static int _rl_vi_set_mark (void) static
Definition at line 2314 of file vi_mode.c.
 {
   int ch;
   RL_SETSTATE(RL_STATE_MOREINPUT);
   ch = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   if (ch < 0 || ch < 'a' || ch > 'z')   /* make test against 0 explicit */
     {
       rl_ding ();
       return 1;
     }
   ch -= 'a';
   vi_mark_chars[ch] = rl_point;
   return 0;
 }
References rl_ding(), rl_point, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, RL_UNSETSTATE, and vi_mark_chars.
Referenced by _rl_vi_callback_set_mark(), and rl_vi_set_mark().
_rl_vi_stuff_insert()
static void _rl_vi_stuff_insert (int count) static
Definition at line 234 of file vi_mode.c.
 {
   rl_begin_undo_group ();
   while (count--)
     rl_insert_text (vi_insert_buffer);
   rl_end_undo_group ();
 }
References count, rl_begin_undo_group(), rl_end_undo_group(), rl_insert_text(), and vi_insert_buffer.
Referenced by rl_vi_redo().
_rl_vi_textmod_command()
int _rl_vi_textmod_command (int c)
Definition at line 207 of file vi_mode.c.
 {
   return (member (c, vi_textmod));
 }
References c, member, and vi_textmod.
Referenced by _rl_dispatch_subseq(), and rl_newline().
rl_digit_loop1()
static int rl_digit_loop1 (void) static
Definition at line 1100 of file vi_mode.c.
 {
   int c, r;
   while (1)
     {
       if (_rl_arg_overflow ())
     return 1;
       c = _rl_arg_getchar ();
       r = _rl_vi_arg_dispatch (c);
       if (r <= 0)
     break;
     }
   RL_UNSETSTATE(RL_STATE_NUMERICARG);
   return (0);
 }
References _rl_arg_getchar(), _rl_arg_overflow(), _rl_vi_arg_dispatch(), c, RL_STATE_NUMERICARG, and RL_UNSETSTATE.
Referenced by rl_domove_read_callback().
rl_domove_motion_callback()
static int rl_domove_motion_callback (_rl_vimotion_cxt * m) static
Definition at line 1154 of file vi_mode.c.
 {
   int c;
   _rl_vi_last_motion = c = m->motion;
   /* Append a blank character temporarily so that the motion routines
      work right at the end of the line.  Original value of rl_end is saved
      as m->end. */
   rl_extend_line_buffer (rl_end + 1);
   rl_line_buffer[rl_end++] = ' ';
   rl_line_buffer[rl_end] = '\0';
   _rl_dispatch (c, _rl_keymap);
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       /* Messy case where char search can be vi motion command; see rest of
      details in callback.c.  vi_char_search and callback_char_search just
      set and unset the CHARSEARCH state.  This is where any vi motion
      command that needs to set its own state should be handled, with any
      corresponding code to manage that state in callback.c */
       if (RL_ISSTATE (RL_STATE_CHARSEARCH))
     return 0;
       else
     return (_rl_vi_domove_motion_cleanup (c, m));
     }
 #endif
   return (_rl_vi_domove_motion_cleanup (c, m));
 }
References _rl_dispatch(), _rl_keymap, _rl_vi_domove_motion_cleanup(), _rl_vi_last_motion, c, __rl_vimotion_context::motion, rl_end, rl_extend_line_buffer(), RL_ISSTATE, rl_line_buffer, RL_STATE_CALLBACK, and RL_STATE_CHARSEARCH.
Referenced by rl_domove_read_callback(), rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
rl_domove_read_callback()
static int rl_domove_read_callback (_rl_vimotion_cxt * m) static
Definition at line 1253 of file vi_mode.c.
 {
   int c, save;
   c = m->motion;
   if (member (c, vi_motion))
     {
 #if defined (READLINE_CALLBACKS)
       /* If we just read a vi-mode motion command numeric argument, turn off
      the `reading numeric arg' state */
       if (RL_ISSTATE (RL_STATE_CALLBACK) && RL_VIMOVENUMARG())
     RL_UNSETSTATE (RL_STATE_NUMERICARG);
 #endif
       /* Should do everything, including turning off RL_STATE_VIMOTION */
       return (rl_domove_motion_callback (m));
     }
   else if (m->key == c && (m->key == 'd' || m->key == 'y' || m->key == 'c'))
     {
       rl_mark = rl_end;
       rl_beg_of_line (1, c);
       _rl_vi_last_motion = c;
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       return (vidomove_dispatch (m));
     }
 #if defined (READLINE_CALLBACKS)
   /* XXX - these need to handle rl_universal_argument bindings */
   /* Reading vi motion char continuing numeric argument */
   else if (_rl_digit_p (c) && RL_ISSTATE (RL_STATE_CALLBACK) && RL_VIMOVENUMARG())
     {
       return (_rl_vi_arg_dispatch (c));
     }
   /* Readine vi motion char starting numeric argument */
   else if (_rl_digit_p (c) && RL_ISSTATE (RL_STATE_CALLBACK) && RL_ISSTATE (RL_STATE_VIMOTION) && (RL_ISSTATE (RL_STATE_NUMERICARG) == 0))
     {
       RL_SETSTATE (RL_STATE_NUMERICARG);
       return (_rl_vi_arg_dispatch (c));
     }
 #endif
   else if (_rl_digit_p (c))
     {
       /* This code path taken when not in callback mode */
       save = rl_numeric_arg;
       rl_numeric_arg = _rl_digit_value (c);
       rl_explicit_arg = 1;
       RL_SETSTATE (RL_STATE_NUMERICARG);
       rl_digit_loop1 ();
       rl_numeric_arg *= save;
       c = rl_vi_domove_getchar (m);
       if (c < 0)
     {
       m->motion = 0;
       return -1;
     }
       m->motion = c;
       return (rl_domove_motion_callback (m));
     }
   else
     {
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       RL_UNSETSTATE (RL_STATE_NUMERICARG);
       return (1);
     }
 }
References _rl_digit_p(), _rl_digit_value(), _rl_vi_arg_dispatch(), _rl_vi_last_motion, c, __rl_vimotion_context::key, member, __rl_vimotion_context::motion, rl_beg_of_line(), rl_digit_loop1(), rl_domove_motion_callback(), rl_end, rl_explicit_arg, RL_ISSTATE, rl_mark, rl_numeric_arg, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_NUMERICARG, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove_getchar(), RL_VIMOVENUMARG, vi_motion, and vidomove_dispatch().
Referenced by _rl_vi_domove_callback(), and rl_vi_domove().
rl_vi_append_eol()
int rl_vi_append_eol (int count, int key)
Definition at line 760 of file vi_mode.c.
 {
   rl_end_of_line (1, key);
   rl_vi_append_mode (1, key);
   return (0);
 }
References rl_end_of_line(), and rl_vi_append_mode().
rl_vi_append_mode()
int rl_vi_append_mode (int count, int key)
Definition at line 752 of file vi_mode.c.
 {
   _rl_vi_append_forward (key);
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References _rl_vi_append_forward(), rl_arg_sign, and rl_vi_start_inserting().
Referenced by rl_vi_append_eol(), and rl_yank_nth_arg_internal().
rl_vi_arg_digit()
int rl_vi_arg_digit (int count, int c)
Definition at line 917 of file vi_mode.c.
 {
   if (c == '0' && rl_numeric_arg == 1 && !rl_explicit_arg)
     return (rl_beg_of_line (1, c));
   else
     return (rl_digit_argument (count, c));
 }
References c, count, rl_beg_of_line(), rl_digit_argument(), rl_explicit_arg, and rl_numeric_arg.
Referenced by _rl_dispatch_subseq(), and rl_trim_arg_from_keyseq().
rl_vi_back_to_indent()
int rl_vi_back_to_indent (int count, int key)
Definition at line 1750 of file vi_mode.c.
 {
   rl_beg_of_line (1, key);
   while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     rl_point++;
   return (0);
 }
References rl_beg_of_line(), rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_first_print().
rl_vi_bracktype()
int rl_vi_bracktype (int c)
Definition at line 1984 of file vi_mode.c.
 {
   switch (c)
     {
     case '(': return  1;
     case ')': return -1;
     case '[': return  2;
     case ']': return -2;
     case '{': return  3;
     case '}': return -3;
     default:  return  0;
     }
 }
References c.
Referenced by rl_vi_match().
rl_vi_bWord()
int rl_vi_bWord (int count, int ignore)
Definition at line 557 of file vi_mode.c.
 {
   while (count-- && rl_point > 0)
     {
       /* If we are at the start of a word, move back to whitespace so
      we will go back to the start of the previous word. */
       if (!whitespace (rl_line_buffer[rl_point]) &&
       whitespace (rl_line_buffer[rl_point - 1]))
     rl_point--;
       while (rl_point > 0 && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_backup_point ();
       if (rl_point > 0)
     {
       do
         _rl_vi_backup_point ();
       while (rl_point > 0 && !whitespace (rl_line_buffer[rl_point]));
       if (rl_point > 0) /* hit whitespace */
         rl_point++;
       if (rl_point < 0)
         rl_point = 0;
     }
     }
   return (0);
 }
References _rl_vi_backup_point(), count, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_prev_word().
rl_vi_bword()
int rl_vi_bword (int count, int ignore)
Definition at line 649 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point > 0)
     {
       int prev_is_ident, cur_is_ident;
       /* If we are at the start of a word, move back to whitespace
      so we will go back to the start of the previous word. */
       if (!whitespace (rl_line_buffer[rl_point]) &&
       whitespace (rl_line_buffer[rl_point - 1]))
     if (--rl_point == 0)
       break;
       /* If this character and the previous character are `opposite', move
      back so we don't get messed up by the rl_point++ down there in
      the while loop.  Without this code, words like `l;' screw up the
      function. */
       cur_is_ident = _rl_isident (rl_line_buffer[rl_point]);
       opoint = _rl_vi_backup_point ();
       prev_is_ident = _rl_isident (rl_line_buffer[rl_point]);
       if ((cur_is_ident && !prev_is_ident) || (!cur_is_ident && prev_is_ident))
     ;   /* leave point alone, we backed it up one character */
       else
     rl_point = opoint;
       while (rl_point > 0 && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_backup_point ();
       if (rl_point > 0)
     {
       opoint = rl_point;
       if (_rl_isident (rl_line_buffer[rl_point]))
         do
           opoint = _rl_vi_backup_point ();
         while (rl_point > 0 && _rl_isident (rl_line_buffer[rl_point]));
       else
         do
           opoint = _rl_vi_backup_point ();
         while (rl_point > 0 && !_rl_isident (rl_line_buffer[rl_point]) &&
            !whitespace (rl_line_buffer[rl_point]));
       if (rl_point > 0)
         rl_point = opoint;
       if (rl_point < 0)
         rl_point = 0;
     }
     }
   return (0);
 }
References _rl_isident, _rl_vi_backup_point(), count, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_prev_word().
rl_vi_change_case()
int rl_vi_change_case (int count, int ignore)
Definition at line 981 of file vi_mode.c.
 {
   int c, p;
   /* Don't try this on an empty line. */
   if (rl_point >= rl_end)
     return (0);
   c = 0;
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     return (_rl_vi_change_mbchar_case (count));
 #endif
   while (count-- && rl_point < rl_end)
     {
       if (_rl_uppercase_p (rl_line_buffer[rl_point]))
     c = _rl_to_lower (rl_line_buffer[rl_point]);
       else if (_rl_lowercase_p (rl_line_buffer[rl_point]))
     c = _rl_to_upper (rl_line_buffer[rl_point]);
       else
     {
       /* Just skip over characters neither upper nor lower case. */
       rl_forward_char (1, c);
       continue;
     }
       /* Vi is kind of strange here. */
       if (c)
     {
       p = rl_point;
       rl_begin_undo_group ();
       rl_vi_delete (1, c);
       if (rl_point < p) /* Did we retreat at EOL? */
         rl_point++;
       _rl_insert_char (1, c);
       rl_end_undo_group ();
       rl_vi_check ();
     }
       else
     rl_forward_char (1, c);
     }
   return (0);
 }
References _rl_insert_char(), _rl_lowercase_p(), _rl_to_lower(), _rl_to_upper(), _rl_uppercase_p(), c, count, MB_CUR_MAX, p, rl_begin_undo_group(), rl_byte_oriented, rl_end, rl_end_undo_group(), rl_forward_char(), rl_line_buffer, rl_point, rl_vi_check(), and rl_vi_delete().
rl_vi_change_char()
int rl_vi_change_char (int count, int key)
Definition at line 2062 of file vi_mode.c.
 {
   int c;
   char mb[MB_LEN_MAX+1];
   if (_rl_vi_redoing)
     {
       strncpy (mb, _rl_vi_last_replacement, MB_LEN_MAX);
       c = (unsigned char)_rl_vi_last_replacement[0];    /* XXX */
       mb[MB_LEN_MAX] = '\0';
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_func = _rl_vi_callback_change_char;
       return (0);
     }
 #endif
   else
     {
       c = _rl_vi_callback_getchar (mb, MB_LEN_MAX);
       if (c < 0)
     return -1;
 #ifdef HANDLE_MULTIBYTE
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     strncpy (_rl_vi_last_replacement, mb, MB_LEN_MAX);
       else
 #endif
     _rl_vi_last_replacement[0] = c;
       _rl_vi_last_replacement[MB_LEN_MAX] = '\0';   /* just in case */
     }
   if (c < 0)
     return -1;
   return (_rl_vi_change_char (count, c, mb));
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_vi_callback_change_char(), _rl_vi_callback_getchar(), _rl_vi_change_char(), _rl_vi_last_replacement, _rl_vi_redoing, c, count, MB_CUR_MAX, MB_LEN_MAX, rl_byte_oriented, RL_ISSTATE, RL_STATE_CALLBACK, and strncpy().
rl_vi_change_to()
int rl_vi_change_to (int count, int key)
Definition at line 1471 of file vi_mode.c.
 {
   int c, r;
   _rl_vimotion_cxt *savecxt;
   savecxt = 0;
   if (_rl_vi_redoing)
     {
       savecxt = _rl_vimvcxt;
       _rl_vimvcxt = _rl_mvcxt_alloc (VIM_CHANGE, key);
     }
   else if (_rl_vimvcxt)
     _rl_mvcxt_init (_rl_vimvcxt, VIM_CHANGE, key);
   else
     _rl_vimvcxt = _rl_mvcxt_alloc (VIM_CHANGE, key);
   _rl_vimvcxt->start = rl_point;
   rl_mark = rl_point;
   if (_rl_uppercase_p (key))
     {
       _rl_vimvcxt->motion = '$';
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing && _rl_vi_last_motion != 'c') /* `cc' is special */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing)      /* handle redoing `cc' here */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       rl_mark = rl_end;
       rl_beg_of_line (1, key);
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       r = vidomove_dispatch (_rl_vimvcxt);
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       RL_SETSTATE (RL_STATE_VIMOTION);
       return (0);
     }
 #endif
   else
     r = rl_vi_domove (key, &c);
   if (r < 0)
     {
       rl_ding ();
       r = -1;   /* normalize return value */
     }
   _rl_mvcxt_dispose (_rl_vimvcxt);
   _rl_vimvcxt = savecxt;
   return r;
 }
References _rl_mvcxt_alloc(), _rl_mvcxt_dispose(), _rl_mvcxt_init(), _rl_uppercase_p(), _rl_vi_last_motion, _rl_vi_redoing, _rl_vimvcxt, c, __rl_vimotion_context::motion, rl_beg_of_line(), rl_ding(), rl_domove_motion_callback(), rl_end, RL_ISSTATE, rl_mark, rl_point, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove(), __rl_vimotion_context::start, vidomove_dispatch(), and VIM_CHANGE.
Referenced by rl_vi_subst().
rl_vi_char_search()
int rl_vi_char_search (int count, int key)
Definition at line 1802 of file vi_mode.c.
 {
   int c;
 #if defined (HANDLE_MULTIBYTE)
   static char *target;
   static int tlen;
 #else
   static char target;
 #endif
   if (key == ';' || key == ',')
     {
       if (_rl_cs_orig_dir == 0)
     return 1;
 #if defined (HANDLE_MULTIBYTE)
       if (_rl_vi_last_search_mblen == 0)
     return 1;
 #else
       if (_rl_vi_last_search_char == 0)
     return 1;
 #endif
       _rl_cs_dir = (key == ';') ? _rl_cs_orig_dir : -_rl_cs_orig_dir;
     }
   else
     {
       switch (key)
     {
     case 't':
       _rl_cs_orig_dir = _rl_cs_dir = FTO;
       break;
     case 'T':
       _rl_cs_orig_dir = _rl_cs_dir = BTO;
       break;
     case 'f':
       _rl_cs_orig_dir = _rl_cs_dir = FFIND;
       break;
     case 'F':
       _rl_cs_orig_dir = _rl_cs_dir = BFIND;
       break;
     }
       if (_rl_vi_redoing)
     {
       /* set target and tlen below */
     }
 #if defined (READLINE_CALLBACKS)
       else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = _rl_callback_data_alloc (count);
       _rl_callback_data->i1 = _rl_cs_dir;
       _rl_callback_data->i2 = key;
       _rl_callback_func = _rl_vi_callback_char_search;
       RL_SETSTATE (RL_STATE_CHARSEARCH);
       return (0);
     }
 #endif
       else
     {
 #if defined (HANDLE_MULTIBYTE)
       c = _rl_read_mbchar (_rl_vi_last_search_mbchar, MB_LEN_MAX);
       if (c <= 0)
         return -1;
       _rl_vi_last_search_mblen = c;
 #else
       RL_SETSTATE(RL_STATE_MOREINPUT);
       c = rl_read_key ();
       RL_UNSETSTATE(RL_STATE_MOREINPUT);
       if (c < 0)
         return -1;
       _rl_vi_last_search_char = c;
 #endif
     }
     }
 #if defined (HANDLE_MULTIBYTE)
   target = _rl_vi_last_search_mbchar;
   tlen = _rl_vi_last_search_mblen;
 #else
   target = _rl_vi_last_search_char;
 #endif
 #if defined (HANDLE_MULTIBYTE)
   return (_rl_char_search_internal (count, _rl_cs_dir, target, tlen));
 #else
   return (_rl_char_search_internal (count, _rl_cs_dir, target));
 #endif
 }
References _rl_callback_data, _rl_callback_data_alloc(), _rl_callback_func, _rl_char_search_internal(), _rl_cs_dir, _rl_cs_orig_dir, _rl_vi_callback_char_search(), _rl_vi_last_search_char, _rl_vi_redoing, BFIND, BTO, c, count, FFIND, FTO, __rl_callback_generic_arg::i1, __rl_callback_generic_arg::i2, MB_LEN_MAX, RL_ISSTATE, rl_read_key(), RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_CHARSEARCH, RL_STATE_MOREINPUT, RL_UNSETSTATE, and target.
rl_vi_check()
int rl_vi_check (void)
Definition at line 1041 of file vi_mode.c.
 {
   if (rl_point && rl_point == rl_end)
     _rl_vi_backup ();
   return (0);
 }
References _rl_vi_backup(), rl_end, and rl_point.
Referenced by _rl_internal_char_cleanup(), and rl_vi_change_case().
rl_vi_column()
int rl_vi_column (int count, int key)
Definition at line 1050 of file vi_mode.c.
 {
   if (count > rl_end)
     rl_end_of_line (1, key);
   else
     {
       rl_point = 0;
       rl_point = _rl_forward_char_internal (count - 1);
     }
   return (0);
 }
References _rl_forward_char_internal(), count, rl_end, rl_end_of_line(), and rl_point.
rl_vi_complete()
int rl_vi_complete (int ignore, int key)
Definition at line 385 of file vi_mode.c.
 {
   if ((rl_point < rl_end) && (!whitespace (rl_line_buffer[rl_point])))
     {
       if (!whitespace (rl_line_buffer[rl_point + 1]))
     rl_vi_end_word (1, 'E');
       _rl_vi_advance_point ();
     }
   if (key == '*')
     rl_complete_internal ('*'); /* Expansion and replacement. */
   else if (key == '=')
     rl_complete_internal ('?'); /* List possible completions. */
   else if (key == '\\')
     rl_complete_internal (TAB); /* Standard Readline completion. */
   else
     rl_complete (0, key);
   if (key == '*' || key == '\\')
     rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References _rl_vi_advance_point(), rl_arg_sign, rl_complete(), rl_complete_internal(), rl_end, rl_line_buffer, rl_point, rl_vi_end_word(), rl_vi_start_inserting(), TAB, and whitespace.
rl_vi_delete()
int rl_vi_delete (int count, int key)
Definition at line 1665 of file vi_mode.c.
 {
   int end;
   if (count < 0)
     return (rl_vi_rubout (-count, key));
   if (rl_end == 0)
     {
       rl_ding ();
       return 1;
     }
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     end = _rl_find_next_mbchar (rl_line_buffer, rl_point, count, MB_FIND_NONZERO);
   else
     end = rl_point + count;
   if (end >= rl_end)
     end = rl_end;
   rl_kill_text (rl_point, end);
   if (rl_point > 0 && rl_point == rl_end)
     rl_backward_char (1, key);
   return (0);
 }
References _rl_find_next_mbchar, count, end, MB_CUR_MAX, MB_FIND_NONZERO, rl_backward_char(), rl_byte_oriented, rl_ding(), rl_end, rl_kill_text(), rl_line_buffer, rl_point, and rl_vi_rubout().
Referenced by _rl_vi_change_char(), rl_vi_change_case(), and rl_vi_rubout().
rl_vi_delete_to()
int rl_vi_delete_to (int count, int key)
Definition at line 1372 of file vi_mode.c.
 {
   int c, r;
   _rl_vimotion_cxt *savecxt;
   savecxt = 0;
   if (_rl_vi_redoing)
     {
       savecxt = _rl_vimvcxt;
       _rl_vimvcxt = _rl_mvcxt_alloc (VIM_DELETE, key);
     }
   else if (_rl_vimvcxt)
     _rl_mvcxt_init (_rl_vimvcxt, VIM_DELETE, key);
   else
     _rl_vimvcxt = _rl_mvcxt_alloc (VIM_DELETE, key);
   _rl_vimvcxt->start = rl_point;
   rl_mark = rl_point;
   if (_rl_uppercase_p (key))
     {
       _rl_vimvcxt->motion = '$';
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing && _rl_vi_last_motion != 'd') /* `dd' is special */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing)      /* handle redoing `dd' here */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       rl_mark = rl_end;
       rl_beg_of_line (1, key);
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       r = vidomove_dispatch (_rl_vimvcxt);
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       RL_SETSTATE (RL_STATE_VIMOTION);
       return (0);
     }
 #endif
   else
     r = rl_vi_domove (key, &c);
   if (r < 0)
     {
       rl_ding ();
       r = -1;
     }
   _rl_mvcxt_dispose (_rl_vimvcxt);
   _rl_vimvcxt = savecxt;
   return r;
 }
References _rl_mvcxt_alloc(), _rl_mvcxt_dispose(), _rl_mvcxt_init(), _rl_uppercase_p(), _rl_vi_last_motion, _rl_vi_redoing, _rl_vimvcxt, c, __rl_vimotion_context::motion, rl_beg_of_line(), rl_ding(), rl_domove_motion_callback(), rl_end, RL_ISSTATE, rl_mark, rl_point, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove(), __rl_vimotion_context::start, vidomove_dispatch(), and VIM_DELETE.
rl_vi_domove()
int rl_vi_domove (int x, int * ignore)
Definition at line 1341 of file vi_mode.c.
 {
   int r;
   _rl_vimotion_cxt *m;
   m = _rl_vimvcxt;
   *ignore = m->motion = rl_vi_domove_getchar (m);
   if (m->motion < 0)
     {
       m->motion = 0;
       return -1;
     }
   return (rl_domove_read_callback (m));
 }
References _rl_vimvcxt, ignore(), __rl_vimotion_context::motion, rl_domove_read_callback(), and rl_vi_domove_getchar().
Referenced by rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
rl_vi_domove_getchar()
static int rl_vi_domove_getchar (_rl_vimotion_cxt * m) static
Definition at line 1319 of file vi_mode.c.
 {
   return (_rl_bracketed_read_key ());
 }
References _rl_bracketed_read_key().
Referenced by _rl_vi_domove_callback(), rl_domove_read_callback(), and rl_vi_domove().
rl_vi_end_word()
int rl_vi_end_word (int count, int key)
Definition at line 524 of file vi_mode.c.
 {
   if (count < 0)
     {
       rl_ding ();
       return 1;
     }
   if (_rl_uppercase_p (key))
     rl_vi_eWord (count, key);
   else
     rl_vi_eword (count, key);
   return (0);
 }
References _rl_uppercase_p(), count, rl_ding(), rl_vi_eWord(), and rl_vi_eword().
Referenced by rl_vi_complete().
rl_vi_eof_maybe()
int rl_vi_eof_maybe (int count, int c)
Definition at line 769 of file vi_mode.c.
 {
   return (rl_newline (1, '\n'));
 }
References rl_newline().
rl_vi_eWord()
int rl_vi_eWord (int count, int ignore)
Definition at line 586 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point < (rl_end - 1))
     {
       if (whitespace (rl_line_buffer[rl_point]) == 0)
     _rl_vi_advance_point ();
       /* Move to the next non-whitespace character (to the start of the
      next word). */
       while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_advance_point ();
       if (rl_point && rl_point < rl_end)
     {
       opoint = rl_point;
       /* Skip whitespace. */
       while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
         opoint = _rl_vi_advance_point ();   /* XXX - why? */
       /* Skip until whitespace. */
       while (rl_point < rl_end && !whitespace (rl_line_buffer[rl_point]))
         opoint = _rl_vi_advance_point ();
       /* Move back to the last character of the word. */
       rl_point = opoint;
     }
     }
   return (0);
 }
References _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_end_word().
rl_vi_eword()
int rl_vi_eword (int count, int ignore)
Definition at line 703 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point < (rl_end - 1))
     {
       if (whitespace (rl_line_buffer[rl_point]) == 0)
     _rl_vi_advance_point ();
       while (rl_point < rl_end && whitespace (rl_line_buffer[rl_point]))
     _rl_vi_advance_point ();
       opoint = rl_point;
       if (rl_point < rl_end)
     {
       if (_rl_isident (rl_line_buffer[rl_point]))
         do
           {
         opoint = _rl_vi_advance_point ();
           }
         while (rl_point < rl_end && _rl_isident (rl_line_buffer[rl_point]));
       else
         do
           {
         opoint = _rl_vi_advance_point ();
           }
         while (rl_point < rl_end && !_rl_isident (rl_line_buffer[rl_point])
            && !whitespace (rl_line_buffer[rl_point]));
     }
       rl_point = opoint;
     }
   return (0);
 }
References _rl_isident, _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_end_word().
rl_vi_fetch_history()
int rl_vi_fetch_history (int count, int c)
Definition at line 338 of file vi_mode.c.
 {
   return (rl_fetch_history (count, c));
 }
References c, count, and rl_fetch_history().
rl_vi_first_print()
int rl_vi_first_print (int count, int key)
Definition at line 1759 of file vi_mode.c.
 {
   return (rl_vi_back_to_indent (1, key));
 }
References rl_vi_back_to_indent().
rl_vi_fWord()
int rl_vi_fWord (int count, int ignore)
Definition at line 541 of file vi_mode.c.
 {
   while (count-- && rl_point < (rl_end - 1))
     {
       /* Skip until whitespace. */
       while (!whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
     _rl_vi_advance_point ();
       /* Now skip whitespace. */
       while (whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
     _rl_vi_advance_point ();
     }
   return (0);
 }
References _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_next_word().
rl_vi_fword()
int rl_vi_fword (int count, int ignore)
Definition at line 620 of file vi_mode.c.
 {
   int opoint;
   while (count-- && rl_point < (rl_end - 1))
     {
       /* Move to white space (really non-identifer). */
       if (_rl_isident (rl_line_buffer[rl_point]))
     {
       while (_rl_isident (rl_line_buffer[rl_point]) && rl_point < rl_end)
         _rl_vi_advance_point ();
     }
       else /* if (!whitespace (rl_line_buffer[rl_point])) */
     {
       while (!_rl_isident (rl_line_buffer[rl_point]) &&
          !whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
         _rl_vi_advance_point ();
     }
       opoint = rl_point;
       /* Move past whitespace. */
       while (whitespace (rl_line_buffer[rl_point]) && rl_point < rl_end)
     opoint = _rl_vi_advance_point ();
     }
   return (0);
 }
References _rl_isident, _rl_vi_advance_point(), count, rl_end, rl_line_buffer, rl_point, and whitespace.
Referenced by rl_vi_next_word().
rl_vi_goto_mark()
int rl_vi_goto_mark (int count, int key)
Definition at line 2402 of file vi_mode.c.
 {
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = 0;
       _rl_callback_func = _rl_vi_callback_goto_mark;
       return (0);
     }
 #endif
   return (_rl_vi_goto_mark ());
 }
References _rl_callback_data, _rl_callback_func, _rl_vi_callback_goto_mark(), _rl_vi_goto_mark(), RL_ISSTATE, and RL_STATE_CALLBACK.
rl_vi_insert_beg()
int rl_vi_insert_beg (int count, int key)
Definition at line 738 of file vi_mode.c.
 {
   rl_beg_of_line (1, key);
   rl_vi_insert_mode (1, key);
   return (0);
 }
References rl_beg_of_line(), and rl_vi_insert_mode().
rl_vi_insert_mode()
int rl_vi_insert_mode (int count, int key)
Definition at line 789 of file vi_mode.c.
 {
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References rl_arg_sign, and rl_vi_start_inserting().
Referenced by rl_vi_editing_mode(), and rl_vi_insert_beg().
rl_vi_insertion_mode()
int rl_vi_insertion_mode (int count, int key)
Definition at line 779 of file vi_mode.c.
 {
   _rl_keymap = vi_insertion_keymap;
   _rl_vi_last_key_before_insert = key;
   if (_rl_show_mode_in_prompt)
     _rl_reset_prompt ();
   return (0);
 }
References _rl_keymap, _rl_reset_prompt(), _rl_show_mode_in_prompt, _rl_vi_last_key_before_insert, and vi_insertion_keymap.
Referenced by readline_internal_setup(), and rl_vi_start_inserting().
rl_vi_match()
int rl_vi_match (int ignore, int key)
Definition at line 1895 of file vi_mode.c.
 {
   int count = 1, brack, pos, tmp, pre;
   pos = rl_point;
   if ((brack = rl_vi_bracktype (rl_line_buffer[rl_point])) == 0)
     {
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       while ((brack = rl_vi_bracktype (rl_line_buffer[rl_point])) == 0)
         {
           pre = rl_point;
           rl_forward_char (1, key);
           if (pre == rl_point)
         break;
         }
     }
       else
     while ((brack = rl_vi_bracktype (rl_line_buffer[rl_point])) == 0 &&
         rl_point < rl_end - 1)
       rl_forward_char (1, key);
       if (brack <= 0)
     {
       rl_point = pos;
       rl_ding ();
       return 1;
     }
     }
   pos = rl_point;
   if (brack < 0)
     {
       while (count)
     {
       tmp = pos;
       if (MB_CUR_MAX == 1 || rl_byte_oriented)
         pos--;
       else
         {
           pos = _rl_find_prev_mbchar (rl_line_buffer, pos, MB_FIND_ANY);
           if (tmp == pos)
         pos--;
         }
       if (pos >= 0)
         {
           int b = rl_vi_bracktype (rl_line_buffer[pos]);
           if (b == -brack)
         count--;
           else if (b == brack)
         count++;
         }
       else
         {
           rl_ding ();
           return 1;
         }
     }
     }
   else
     {           /* brack > 0 */
       while (count)
     {
       if (MB_CUR_MAX == 1 || rl_byte_oriented)
         pos++;
       else
         pos = _rl_find_next_mbchar (rl_line_buffer, pos, 1, MB_FIND_ANY);
       if (pos < rl_end)
         {
           int b = rl_vi_bracktype (rl_line_buffer[pos]);
           if (b == -brack)
         count--;
           else if (b == brack)
         count++;
         }
       else
         {
           rl_ding ();
           return 1;
         }
     }
     }
   rl_point = pos;
   return (0);
 }
References _rl_find_next_mbchar, _rl_find_prev_mbchar, count, MB_CUR_MAX, MB_FIND_ANY, pos, rl_byte_oriented, rl_ding(), rl_end, rl_forward_char(), rl_line_buffer, rl_point, and rl_vi_bracktype().
rl_vi_movement_mode()
int rl_vi_movement_mode (int count, int key)
Definition at line 896 of file vi_mode.c.
 {
   if (rl_point > 0)
     rl_backward_char (1, key);
   _rl_keymap = vi_movement_keymap;
   _rl_vi_done_inserting ();
   /* This is how POSIX.2 says `U' should behave -- everything up until the
      first time you go into command mode should not be undone. */
   if (RL_ISSTATE (RL_STATE_VICMDONCE) == 0)
     rl_free_undo_list ();
   if (_rl_show_mode_in_prompt)
     _rl_reset_prompt ();
   RL_SETSTATE (RL_STATE_VICMDONCE);
   return (0);
 }
References _rl_keymap, _rl_reset_prompt(), _rl_show_mode_in_prompt, _rl_vi_done_inserting(), rl_backward_char(), rl_free_undo_list(), RL_ISSTATE, rl_point, RL_SETSTATE, RL_STATE_VICMDONCE, and vi_movement_keymap.
Referenced by rl_bind_keyseq_if_unbound_in_map(), and rl_vi_replace().
rl_vi_next_word()
int rl_vi_next_word (int count, int key)
Definition at line 441 of file vi_mode.c.
 {
   if (count < 0)
     return (rl_vi_prev_word (-count, key));
   if (rl_point >= (rl_end - 1))
     {
       rl_ding ();
       return (0);
     }
   if (_rl_uppercase_p (key))
     rl_vi_fWord (count, key);
   else
     rl_vi_fword (count, key);
   return (0);
 }
References _rl_uppercase_p(), count, rl_ding(), rl_end, rl_point, rl_vi_fWord(), rl_vi_fword(), and rl_vi_prev_word().
Referenced by rl_vi_prev_word().
rl_vi_overstrike()
int rl_vi_overstrike (int count, int key)
Definition at line 2112 of file vi_mode.c.
 {
   if (_rl_vi_doing_insert == 0)
     {
       _rl_vi_doing_insert = 1;
       rl_begin_undo_group ();
     }
   if (count > 0)
     {
       if (_rl_overwrite_char (count, key) != 0)
     return (1);
       vi_replace_count += count;
     }
   return (0);
 }
References _rl_overwrite_char(), _rl_vi_doing_insert, count, rl_begin_undo_group(), and vi_replace_count.
Referenced by rl_vi_overstrike_bracketed_paste(), and rl_vi_replace().
rl_vi_overstrike_bracketed_paste()
static int rl_vi_overstrike_bracketed_paste (int count, int key) static
Definition at line 2195 of file vi_mode.c.
 {
   int r;
   char *pbuf;
   size_t pblen;
   pbuf = _rl_bracketed_text (&pblen);
   if (pblen == 0)
     {
       xfree (pbuf);
       return 0;
     }
   r = pblen;
   while (--r >= 0)
     _rl_unget_char ((unsigned char)pbuf[r]);
   xfree (pbuf);
   while (_rl_pushed_input_available ())
     {
       key = rl_read_key ();
       r = rl_vi_overstrike (1, key);
     }
   return r;
 }
References _rl_bracketed_text(), _rl_pushed_input_available(), _rl_unget_char(), rl_read_key(), rl_vi_overstrike(), and xfree.
Referenced by rl_vi_replace().
rl_vi_overstrike_delete()
int rl_vi_overstrike_delete (int count, int key)
Definition at line 2131 of file vi_mode.c.
 {
   int i, s;
   for (i = 0; i < count; i++)
     {
       if (vi_replace_count == 0)
     {
       rl_ding ();
       break;
     }
       s = rl_point;
       if (rl_do_undo ())
     vi_replace_count--;     /* XXX */
       if (rl_point == s)
     rl_backward_char (1, key);
     }
   if (vi_replace_count == 0 && _rl_vi_doing_insert)
     {
       rl_end_undo_group ();
       rl_do_undo ();
       _rl_vi_doing_insert = 0;
     }
   return (0);
 }
References _rl_vi_doing_insert, count, i, rl_backward_char(), rl_ding(), rl_do_undo(), rl_end_undo_group(), rl_point, s, and vi_replace_count.
Referenced by rl_vi_replace().
rl_vi_overstrike_kill_line()
static int rl_vi_overstrike_kill_line (int count, int key) static
Definition at line 2161 of file vi_mode.c.
 {
   int r, end;
   end = rl_end;
   r = rl_unix_line_discard (count, key);
   vi_replace_count -= end - rl_end;
   return r;
 }
References count, end, rl_end, rl_unix_line_discard(), and vi_replace_count.
Referenced by rl_vi_replace().
rl_vi_overstrike_kill_word()
static int rl_vi_overstrike_kill_word (int count, int key) static
Definition at line 2172 of file vi_mode.c.
 {
   int r, end;
   end = rl_end;
   r = rl_vi_unix_word_rubout (count, key);
   vi_replace_count -= end - rl_end;
   return r;
 }
References count, end, rl_end, rl_vi_unix_word_rubout(), and vi_replace_count.
Referenced by rl_vi_replace().
rl_vi_overstrike_yank()
static int rl_vi_overstrike_yank (int count, int key) static
Definition at line 2183 of file vi_mode.c.
 {
   int r, end;
   end = rl_end;
   r = rl_yank (count, key);
   vi_replace_count += rl_end - end;
   return r;
 }
References count, end, rl_end, rl_yank(), and vi_replace_count.
Referenced by rl_vi_replace().
rl_vi_prev_word()
int rl_vi_prev_word (int count, int key)
Definition at line 420 of file vi_mode.c.
 {
   if (count < 0)
     return (rl_vi_next_word (-count, key));
   if (rl_point == 0)
     {
       rl_ding ();
       return (0);
     }
   if (_rl_uppercase_p (key))
     rl_vi_bWord (count, key);
   else
     rl_vi_bword (count, key);
   return (0);
 }
References _rl_uppercase_p(), count, rl_ding(), rl_point, rl_vi_bWord(), rl_vi_bword(), and rl_vi_next_word().
Referenced by rl_vi_next_word().
rl_vi_put()
int rl_vi_put (int count, int key)
Definition at line 1027 of file vi_mode.c.
 {
   if (!_rl_uppercase_p (key) && (rl_point + 1 <= rl_end))
     rl_point = _rl_find_next_mbchar (rl_line_buffer, rl_point, 1, MB_FIND_NONZERO);
   while (count--)
     rl_yank (1, key);
   rl_backward_char (1, key);
   return (0);
 }
References _rl_find_next_mbchar, _rl_uppercase_p(), count, MB_FIND_NONZERO, rl_backward_char(), rl_end, rl_line_buffer, rl_point, and rl_yank().
Referenced by rl_vi_yank_pop().
rl_vi_redo()
int rl_vi_redo (int count, int c)
Definition at line 246 of file vi_mode.c.
 {
   int r;
   if (rl_explicit_arg == 0)
     {
       rl_numeric_arg = _rl_vi_last_repeat;
       rl_arg_sign = _rl_vi_last_arg_sign;
     }
   r = 0;
   _rl_vi_redoing = 1;
   /* If we're redoing an insert with `i', stuff in the inserted text
      and do not go into insertion mode. */
   if (_rl_vi_last_command == 'i' && vi_insert_buffer && *vi_insert_buffer)
     {
       _rl_vi_stuff_insert (count);
       /* And back up point over the last character inserted. */
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   else if (_rl_vi_last_command == 'R' && vi_insert_buffer && *vi_insert_buffer)
     {
       _rl_vi_replace_insert (count);
       /* And back up point over the last character inserted. */
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   /* Ditto for redoing an insert with `I', but move to the beginning of the
      line like the `I' command does. */
   else if (_rl_vi_last_command == 'I' && vi_insert_buffer && *vi_insert_buffer)
     {
       rl_beg_of_line (1, 'I');
       _rl_vi_stuff_insert (count);
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   /* Ditto for redoing an insert with `a', but move forward a character first
      like the `a' command does. */
   else if (_rl_vi_last_command == 'a' && vi_insert_buffer && *vi_insert_buffer)
     {
       _rl_vi_append_forward ('a');
       _rl_vi_stuff_insert (count);
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   /* Ditto for redoing an insert with `A', but move to the end of the line
      like the `A' command does. */
   else if (_rl_vi_last_command == 'A' && vi_insert_buffer && *vi_insert_buffer)
     {
       rl_end_of_line (1, 'A');
       _rl_vi_stuff_insert (count);
       if (rl_point > 0)
     _rl_vi_backup ();
     }
   else if (_rl_vi_last_command == '.' && _rl_keymap == vi_movement_keymap)
     {
       rl_ding ();
       r = 0;
     }
   else
     r = _rl_dispatch (_rl_vi_last_command, _rl_keymap);
   _rl_vi_redoing = 0;
   return (r);
 }
References _rl_dispatch(), _rl_keymap, _rl_vi_append_forward(), _rl_vi_backup(), _rl_vi_last_arg_sign, _rl_vi_last_command, _rl_vi_last_repeat, _rl_vi_redoing, _rl_vi_replace_insert(), _rl_vi_stuff_insert(), count, rl_arg_sign, rl_beg_of_line(), rl_ding(), rl_end_of_line(), rl_explicit_arg, rl_numeric_arg, rl_point, vi_insert_buffer, and vi_movement_keymap.
rl_vi_replace()
int rl_vi_replace (int count, int key)
Definition at line 2222 of file vi_mode.c.
 {
   int i;
   vi_replace_count = 0;
   if (vi_replace_map == 0)
     {
       vi_replace_map = rl_make_bare_keymap ();
       for (i = 0; i < ' '; i++)
     if (vi_insertion_keymap[i].type == ISFUNC)
       vi_replace_map[i].function = vi_insertion_keymap[i].function;
       for (i = ' '; i < KEYMAP_SIZE; i++)
     vi_replace_map[i].function = rl_vi_overstrike;
       vi_replace_map[RUBOUT].function = rl_vi_overstrike_delete;
       /* Make sure these are what we want. */
       vi_replace_map[ESC].function = rl_vi_movement_mode;
       vi_replace_map[RETURN].function = rl_newline;
       vi_replace_map[NEWLINE].function = rl_newline;
       /* If the normal vi insertion keymap has ^H bound to erase, do the
      same here.  Probably should remove the assignment to RUBOUT up
      there, but I don't think it will make a difference in real life. */
       if (vi_insertion_keymap[CTRL ('H')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('H')].function == rl_rubout)
     vi_replace_map[CTRL ('H')].function = rl_vi_overstrike_delete;
       /* Same for ^U and unix-line-discard. */
       if (vi_insertion_keymap[CTRL ('U')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('U')].function == rl_unix_line_discard)
     vi_replace_map[CTRL ('U')].function = rl_vi_overstrike_kill_line;
       /* And for ^W and unix-word-rubout. */
       if (vi_insertion_keymap[CTRL ('W')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('W')].function == rl_vi_unix_word_rubout)
     vi_replace_map[CTRL ('W')].function = rl_vi_overstrike_kill_word;
       /* And finally for ^Y and yank. */
       if (vi_insertion_keymap[CTRL ('Y')].type == ISFUNC &&
       vi_insertion_keymap[CTRL ('Y')].function == rl_yank)
     vi_replace_map[CTRL ('Y')].function = rl_vi_overstrike_yank;
       /* Make sure this is the value we need. */
       vi_replace_map[ANYOTHERKEY].type = ISFUNC;
       vi_replace_map[ANYOTHERKEY].function = (rl_command_func_t *)NULL;
     }
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   _rl_vi_last_key_before_insert = 'R';  /* in case someone rebinds it */
   _rl_keymap = vi_replace_map;
   if (_rl_enable_bracketed_paste)
     rl_bind_keyseq_if_unbound (BRACK_PASTE_PREF, rl_vi_overstrike_bracketed_paste);
   return (0);
 }
References _rl_enable_bracketed_paste, _rl_keymap, _rl_vi_last_key_before_insert, ANYOTHERKEY, BRACK_PASTE_PREF, CTRL, ESC, _keymap_entry::function, i, ISFUNC, KEYMAP_SIZE, NEWLINE, NULL, RETURN, rl_arg_sign, rl_bind_keyseq_if_unbound(), rl_make_bare_keymap(), rl_newline(), rl_rubout(), rl_unix_line_discard(), rl_vi_movement_mode(), rl_vi_overstrike(), rl_vi_overstrike_bracketed_paste(), rl_vi_overstrike_delete(), rl_vi_overstrike_kill_line(), rl_vi_overstrike_kill_word(), rl_vi_overstrike_yank(), rl_vi_start_inserting(), rl_vi_unix_word_rubout(), rl_yank(), RUBOUT, _keymap_entry::type, type, vi_insertion_keymap, vi_replace_count, and vi_replace_map.
rl_vi_rubout()
int rl_vi_rubout (int count, int key)
Definition at line 1635 of file vi_mode.c.
 {
   int opoint;
   if (count < 0)
     return (rl_vi_delete (-count, key));
   if (rl_point == 0)
     {
       rl_ding ();
       return 1;
     }
   opoint = rl_point;
   if (count > 1 && MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_backward_char (count, key);
   else if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_point = _rl_find_prev_mbchar (rl_line_buffer, rl_point, MB_FIND_NONZERO);
   else
     rl_point -= count;
   if (rl_point < 0)
     rl_point = 0;
   rl_kill_text (rl_point, opoint);
   return (0);
 }
References _rl_find_prev_mbchar, count, MB_CUR_MAX, MB_FIND_NONZERO, rl_backward_char(), rl_byte_oriented, rl_ding(), rl_kill_text(), rl_line_buffer, rl_point, and rl_vi_delete().
Referenced by rl_vi_delete().
rl_vi_search()
int rl_vi_search (int count, int key)
Definition at line 362 of file vi_mode.c.
 {
   switch (key)
     {
     case '?':
       _rl_free_saved_history_line ();
       rl_noninc_forward_search (count, key);
       break;
     case '/':
       _rl_free_saved_history_line ();
       rl_noninc_reverse_search (count, key);
       break;
     default:
       rl_ding ();
       break;
     }
   return (0);
 }
References _rl_free_saved_history_line(), count, rl_ding(), rl_noninc_forward_search(), and rl_noninc_reverse_search().
rl_vi_search_again()
int rl_vi_search_again (int count, int key)
Definition at line 345 of file vi_mode.c.
 {
   switch (key)
     {
     case 'n':
       rl_noninc_reverse_search_again (count, key);
       break;
     case 'N':
       rl_noninc_forward_search_again (count, key);
       break;
     }
   return (0);
 }
References count, rl_noninc_forward_search_again(), and rl_noninc_reverse_search_again().
rl_vi_set_mark()
int rl_vi_set_mark (int count, int key)
Definition at line 2344 of file vi_mode.c.
 {
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_callback_data = 0;
       _rl_callback_func = _rl_vi_callback_set_mark;
       return (0);
     }
 #endif
   return (_rl_vi_set_mark ());
 }
References _rl_callback_data, _rl_callback_func, _rl_vi_callback_set_mark(), _rl_vi_set_mark(), RL_ISSTATE, and RL_STATE_CALLBACK.
rl_vi_start_inserting()
void rl_vi_start_inserting (int key, int repeat, int sign)
Definition at line 198 of file vi_mode.c.
 {
   _rl_vi_set_last (key, repeat, sign);
   rl_begin_undo_group ();       /* ensure inserts aren't concatenated */
   rl_vi_insertion_mode (1, key);
 }
References _rl_vi_set_last(), rl_begin_undo_group(), and rl_vi_insertion_mode().
Referenced by rl_vi_append_mode(), rl_vi_complete(), rl_vi_insert_mode(), rl_vi_replace(), rl_vi_tilde_expand(), and vi_change_dispatch().
rl_vi_subst()
int rl_vi_subst (int count, int key)
Definition at line 2102 of file vi_mode.c.
 {
   /* If we are redoing, rl_vi_change_to will stuff the last motion char */
   if (_rl_vi_redoing == 0)
     rl_stuff_char ((key == 'S') ? 'c' : 'l');   /* `S' == `cc', `s' == `cl' */
   return (rl_vi_change_to (count, 'c'));
 }
References _rl_vi_redoing, count, rl_stuff_char(), and rl_vi_change_to().
rl_vi_tilde_expand()
int rl_vi_tilde_expand (int ignore, int key)
Definition at line 411 of file vi_mode.c.
 {
   rl_tilde_expand (0, key);
   rl_vi_start_inserting (key, 1, rl_arg_sign);
   return (0);
 }
References rl_arg_sign, rl_tilde_expand(), and rl_vi_start_inserting().
rl_vi_undo()
int rl_vi_undo (int count, int key)
Definition at line 316 of file vi_mode.c.
 {
   return (rl_undo_command (count, key));
 }
References count, and rl_undo_command().
rl_vi_unix_word_rubout()
int rl_vi_unix_word_rubout (int count, int key)
Definition at line 1700 of file vi_mode.c.
 {
   int orig_point;
   if (rl_point == 0)
     rl_ding ();
   else
     {
       orig_point = rl_point;
       if (count <= 0)
     count = 1;
       while (count--)
     {
       /* This isn't quite what ksh93 does but it seems to match what the
          Posix description of sh specifies, with a few accommodations
          for sequences of whitespace characters between words and at
          the end of the line. */
       /* Skip over whitespace at the end of the line as a special case */
       if (rl_point > 0 && (rl_line_buffer[rl_point] == 0) &&
         whitespace (rl_line_buffer[rl_point - 1]))
         while (--rl_point > 0 && whitespace (rl_line_buffer[rl_point]))
           ;
       /* If we're at the start of a word, move back to word boundary so we
          move back to the `preceding' word */
       if (rl_point > 0 && (vi_unix_word_boundary (rl_line_buffer[rl_point]) == 0) &&
         vi_unix_word_boundary (rl_line_buffer[rl_point - 1]))
         rl_point--;
       /* If we are at a word boundary (whitespace/punct), move backward
          past a sequence of word boundary characters.  If we are at the
          end of a word (non-word boundary), move back to a word boundary */
       if (rl_point > 0 && vi_unix_word_boundary (rl_line_buffer[rl_point]))
         while (rl_point && vi_unix_word_boundary (rl_line_buffer[rl_point - 1]))
           rl_point--;
       else if (rl_point > 0 && vi_unix_word_boundary (rl_line_buffer[rl_point]) == 0)
         while (rl_point > 0 && (vi_unix_word_boundary (rl_line_buffer[rl_point - 1]) == 0))
           _rl_vi_backup_point ();
     }
       rl_kill_text (orig_point, rl_point);
     }
   return 0;
 }
References _rl_vi_backup_point(), count, rl_ding(), rl_kill_text(), rl_line_buffer, rl_point, vi_unix_word_boundary, and whitespace.
Referenced by rl_vi_overstrike_kill_word(), and rl_vi_replace().
rl_vi_yank_arg()
int rl_vi_yank_arg (int count, int key)
Definition at line 323 of file vi_mode.c.
 {
   /* Readline thinks that the first word on a line is the 0th, while vi
      thinks the first word on a line is the 1st.  Compensate. */
   if (rl_explicit_arg)
     rl_yank_nth_arg (count - 1, key);
   else
     rl_yank_nth_arg ('$', key);
   return (0);
 }
References count, rl_explicit_arg, and rl_yank_nth_arg().
rl_vi_yank_to()
int rl_vi_yank_to (int count, int key)
Definition at line 1550 of file vi_mode.c.
 {
   int c, r;
   _rl_vimotion_cxt *savecxt;
   savecxt = 0;
   if (_rl_vi_redoing)
     {
       savecxt = _rl_vimvcxt;
       _rl_vimvcxt = _rl_mvcxt_alloc (VIM_YANK, key);
     }
   else if (_rl_vimvcxt)
     _rl_mvcxt_init (_rl_vimvcxt, VIM_YANK, key);
   else
     _rl_vimvcxt = _rl_mvcxt_alloc (VIM_YANK, key);
   _rl_vimvcxt->start = rl_point;
   rl_mark = rl_point;
   if (_rl_uppercase_p (key))
     {
       _rl_vimvcxt->motion = '$';
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing && _rl_vi_last_motion != 'y') /* `yy' is special */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       r = rl_domove_motion_callback (_rl_vimvcxt);
     }
   else if (_rl_vi_redoing)          /* handle redoing `yy' here */
     {
       _rl_vimvcxt->motion = _rl_vi_last_motion;
       rl_mark = rl_end;
       rl_beg_of_line (1, key);
       RL_UNSETSTATE (RL_STATE_VIMOTION);
       r = vidomove_dispatch (_rl_vimvcxt);
     }
 #if defined (READLINE_CALLBACKS)
   else if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       RL_SETSTATE (RL_STATE_VIMOTION);
       return (0);
     }
 #endif
   else
     r = rl_vi_domove (key, &c);
   if (r < 0)
     {
       rl_ding ();
       r = -1;
     }
   _rl_mvcxt_dispose (_rl_vimvcxt);
   _rl_vimvcxt = savecxt;
   return r;
 }
References _rl_mvcxt_alloc(), _rl_mvcxt_dispose(), _rl_mvcxt_init(), _rl_uppercase_p(), _rl_vi_last_motion, _rl_vi_redoing, _rl_vimvcxt, c, __rl_vimotion_context::motion, rl_beg_of_line(), rl_ding(), rl_domove_motion_callback(), rl_end, RL_ISSTATE, rl_mark, rl_point, RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_VIMOTION, RL_UNSETSTATE, rl_vi_domove(), __rl_vimotion_context::start, vidomove_dispatch(), and VIM_YANK.
vi_change_dispatch()
static int vi_change_dispatch (_rl_vimotion_cxt * m) static
Definition at line 1432 of file vi_mode.c.
 {
   /* These are the motion commands that do not require adjusting the
      mark.  c[wW] are handled by special-case code in rl_vi_domove(),
      and already leave the mark at the correct location. */
   if (((strchr (" l|hwW^0bBFT`", m->motion) == 0) && (rl_point >= m->start)) &&
       (rl_mark < rl_end))
     INCREMENT_POS (rl_mark);
   /* The cursor never moves with c[wW]. */
   if ((_rl_to_upper (m->motion) == 'W') && rl_point < m->start)
     rl_point = m->start;
   if (_rl_vi_redoing)
     {
       if (vi_insert_buffer && *vi_insert_buffer)
     rl_begin_undo_group ();
       rl_delete_text (rl_point, rl_mark);
       if (vi_insert_buffer && *vi_insert_buffer)
     {
       rl_insert_text (vi_insert_buffer);
       rl_end_undo_group ();
     }
     }
   else
     {
       rl_begin_undo_group ();       /* to make the `u' command work */
       rl_kill_text (rl_point, rl_mark);
       /* `C' does not save the text inserted for undoing or redoing. */
       if (_rl_uppercase_p (m->key) == 0)
     _rl_vi_doing_insert = 1;
       /* XXX -- TODO -- use m->numericarg? */
       rl_vi_start_inserting (m->key, rl_numeric_arg, rl_arg_sign);
     }
   return (0);
 }
References _rl_to_upper(), _rl_uppercase_p(), _rl_vi_doing_insert, _rl_vi_redoing, INCREMENT_POS, __rl_vimotion_context::key, __rl_vimotion_context::motion, rl_arg_sign, rl_begin_undo_group(), rl_delete_text(), rl_end, rl_end_undo_group(), rl_insert_text(), rl_kill_text(), rl_mark, rl_numeric_arg, rl_point, rl_vi_start_inserting(), __rl_vimotion_context::start, start, strchr(), and vi_insert_buffer.
Referenced by vidomove_dispatch().
vi_delete_dispatch()
static int vi_delete_dispatch (_rl_vimotion_cxt * m) static
Definition at line 1359 of file vi_mode.c.
 {
   /* These are the motion commands that do not require adjusting the
      mark. */
   if (((strchr (" l|h^0bBFT`", m->motion) == 0) && (rl_point >= m->start)) &&
       (rl_mark < rl_end))
     INCREMENT_POS (rl_mark);
   rl_kill_text (rl_point, rl_mark);
   return (0);
 }
References INCREMENT_POS, __rl_vimotion_context::motion, rl_end, rl_kill_text(), rl_mark, rl_point, __rl_vimotion_context::start, and strchr().
Referenced by vidomove_dispatch().
vi_save_insert_buffer()
static void vi_save_insert_buffer (int start, int len) static
Definition at line 796 of file vi_mode.c.
 {
   /* Same code as _rl_vi_save_insert below */
   if (len >= vi_insert_buffer_size)
     {
       vi_insert_buffer_size += (len + 32) - (len % 32);
       vi_insert_buffer = (char *)xrealloc (vi_insert_buffer, vi_insert_buffer_size);
     }
   strncpy (vi_insert_buffer, rl_line_buffer + start, len - 1);
   vi_insert_buffer[len-1] = '\0';
 }
References len, rl_line_buffer, start, strncpy(), vi_insert_buffer, vi_insert_buffer_size, and xrealloc.
Referenced by _rl_vi_save_insert(), and _rl_vi_save_replace().
vi_yank_dispatch()
static int vi_yank_dispatch (_rl_vimotion_cxt * m) static
Definition at line 1530 of file vi_mode.c.
 {
   /* These are the motion commands that do not require adjusting the
      mark. */
   if (((strchr (" l|h^0%bBFT`", m->motion) == 0) && (rl_point >= m->start)) &&
       (rl_mark < rl_end))
     INCREMENT_POS (rl_mark);
   rl_begin_undo_group ();
   rl_kill_text (rl_point, rl_mark);
   rl_end_undo_group ();
   rl_do_undo ();
   rl_point = m->start;
   _rl_fix_point (1);
   return (0);
 }
References _rl_fix_point(), INCREMENT_POS, __rl_vimotion_context::motion, rl_begin_undo_group(), rl_do_undo(), rl_end, rl_end_undo_group(), rl_kill_text(), rl_mark, rl_point, __rl_vimotion_context::start, and strchr().
Referenced by vidomove_dispatch().
vidomove_dispatch()
static int vidomove_dispatch (_rl_vimotion_cxt * m) static
Definition at line 1609 of file vi_mode.c.
 {
   int r;
   switch (m->op)
     {
     case VIM_DELETE:
       r = vi_delete_dispatch (m);
       break;
     case VIM_CHANGE:
       r = vi_change_dispatch (m);
       break;
     case VIM_YANK:
       r = vi_yank_dispatch (m);
       break;
     default:
       _rl_errmsg ("vidomove_dispatch: unknown operator %d", m->op);
       r = 1;
       break;
     }
   RL_UNSETSTATE (RL_STATE_VIMOTION);
   return r;
 }
References _rl_errmsg(), __rl_vimotion_context::op, RL_STATE_VIMOTION, RL_UNSETSTATE, vi_change_dispatch(), vi_delete_dispatch(), vi_yank_dispatch(), VIM_CHANGE, VIM_DELETE, and VIM_YANK.
Referenced by _rl_vi_domove_motion_cleanup(), rl_domove_read_callback(), rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
Variable Documentation
_rl_cs_dir
int _rl_cs_dir static
Definition at line 1764 of file vi_mode.c.
Referenced by _rl_vi_callback_char_search(), and rl_vi_char_search().
_rl_cs_orig_dir
int _rl_cs_orig_dir static
Definition at line 1764 of file vi_mode.c.
Referenced by rl_vi_char_search().
_rl_vi_doing_insert
int _rl_vi_doing_insert static
Definition at line 89 of file vi_mode.c.
Referenced by _rl_vi_done_inserting(), rl_vi_overstrike(), rl_vi_overstrike_delete(), and vi_change_dispatch().
_rl_vi_last_arg_sign
int _rl_vi_last_arg_sign = 1 static
Definition at line 109 of file vi_mode.c.
Referenced by _rl_vi_reset_last(), _rl_vi_set_last(), and rl_vi_redo().
_rl_vi_last_command
int _rl_vi_last_command = 'i'
Definition at line 81 of file vi_mode.c.
Referenced by _rl_vi_reset_last(), _rl_vi_set_last(), rl_newline(), and rl_vi_redo().
_rl_vi_last_key_before_insert
int _rl_vi_last_key_before_insert static
Definition at line 119 of file vi_mode.c.
Referenced by _rl_vi_done_inserting(), rl_vi_insertion_mode(), and rl_vi_replace().
_rl_vi_last_motion
int _rl_vi_last_motion static
Definition at line 110 of file vi_mode.c.
Referenced by _rl_vi_reset_last(), rl_domove_motion_callback(), rl_domove_read_callback(), rl_vi_change_to(), rl_vi_delete_to(), and rl_vi_yank_to().
_rl_vi_last_repeat
int _rl_vi_last_repeat = 1 static
Definition at line 108 of file vi_mode.c.
Referenced by _rl_vi_reset_last(), _rl_vi_set_last(), and rl_vi_redo().
_rl_vi_last_replacement
char _rl_vi_last_replacement[MB_LEN_MAX+1] static
Definition at line 117 of file vi_mode.c.
Referenced by _rl_vi_callback_change_char(), and rl_vi_change_char().
_rl_vi_last_search_char
int _rl_vi_last_search_char static
Definition at line 115 of file vi_mode.c.
Referenced by _rl_vi_callback_char_search(), and rl_vi_char_search().
_rl_vi_redoing
int _rl_vi_redoing
Definition at line 86 of file vi_mode.c.
Referenced by _rl_dispatch_subseq(), rl_vi_change_char(), rl_vi_change_to(), rl_vi_char_search(), rl_vi_delete_to(), rl_vi_redo(), rl_vi_subst(), rl_vi_yank_to(), and vi_change_dispatch().
_rl_vimvcxt
_rl_vimotion_cxt* _rl_vimvcxt = 0
Definition at line 83 of file vi_mode.c.
Referenced by rl_callback_read_char(), rl_vi_change_to(), rl_vi_delete_to(), rl_vi_domove(), and rl_vi_yank_to().
vi_continued_command
int vi_continued_command static
Definition at line 104 of file vi_mode.c.
vi_insert_buffer
char* vi_insert_buffer static
Definition at line 105 of file vi_mode.c.
Referenced by _rl_vi_replace_insert(), _rl_vi_save_insert(), _rl_vi_save_replace(), _rl_vi_stuff_insert(), rl_vi_redo(), vi_change_dispatch(), and vi_save_insert_buffer().
vi_insert_buffer_size
int vi_insert_buffer_size static
Definition at line 106 of file vi_mode.c.
Referenced by _rl_vi_save_insert(), _rl_vi_save_replace(), and vi_save_insert_buffer().
vi_mark_chars
int vi_mark_chars[ 'z' - 'a'+1] static
Definition at line 125 of file vi_mode.c.
Referenced by _rl_vi_goto_mark(), _rl_vi_initialize_line(), and _rl_vi_set_mark().
vi_motion
const char* const vi_motion = " hl^$0ftFT;,%wbeWBE|`" static
Definition at line 92 of file vi_mode.c.
Referenced by _rl_vi_motion_command(), and rl_domove_read_callback().
vi_replace_count
int vi_replace_count static
Definition at line 99 of file vi_mode.c.
Referenced by _rl_vi_save_replace(), rl_vi_overstrike(), rl_vi_overstrike_delete(), rl_vi_overstrike_kill_line(), rl_vi_overstrike_kill_word(), rl_vi_overstrike_yank(), and rl_vi_replace().
vi_replace_map
Keymap vi_replace_map static
Definition at line 96 of file vi_mode.c.
Referenced by rl_vi_replace().
vi_textmod
const char* const vi_textmod = "_*\\AaIiCcDdPpYyRrSsXx~" static
Definition at line 122 of file vi_mode.c.
Referenced by _rl_vi_textmod_command().