Fennix: Userspace/apps/base/busybox/util-linux/lsusb.c File Reference
lsusb.c File Reference
#include "libbb.h"
Functions
static int FAST_FUNC fileAction (struct recursive_state *state UNUSED_PARAM, const char *fileName, struct stat *statbuf UNUSED_PARAM)
int lsusb_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int lsusb_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
fileAction()
static int FAST_FUNC fileAction (struct recursive_state *state UNUSED_PARAM, const char * fileName, struct stat *statbuf UNUSED_PARAM) static
Definition at line 27 of file lsusb.c.
 {
     parser_t *parser;
     char *tokens[4];
     char *busnum = NULL, *devnum = NULL;
     int product_vid = 0, product_did = 0;
     char *uevent_filename = concat_path_file(fileName, "/uevent");
     parser = config_open2(uevent_filename, fopen_for_read);
     free(uevent_filename);
     while (config_read(parser, tokens, 4, 2, "\\/=", PARSE_NORMAL)) {
         if ((parser->lineno == 1) && strcmp(tokens[0], "DEVTYPE") == 0) {
             break;
         }
         if (strcmp(tokens[0], "PRODUCT") == 0) {
             product_vid = xstrtou(tokens[1], 16);
             product_did = xstrtou(tokens[2], 16);
             continue;
         }
         if (strcmp(tokens[0], "BUSNUM") == 0) {
             busnum = xstrdup(tokens[1]);
             continue;
         }
         if (strcmp(tokens[0], "DEVNUM") == 0) {
             devnum = xstrdup(tokens[1]);
             continue;
         }
     }
     config_close(parser);
     if (busnum) {
         printf("Bus %s Device %s: ID %04x:%04x\n", busnum, devnum, product_vid, product_did);
         free(busnum);
         free(devnum);
     }
     return TRUE;
 }
References concat_path_file(), config_close(), config_open2(), config_read, fileName, fopen_for_read(), free, NULL, PARSE_NORMAL, parser, printf, strcmp, TRUE, xstrdup(), and xstrtou().
Referenced by lsusb_main().
lsusb_main() [1/2]
int lsusb_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 73 of file lsusb.c.
 {
     /* no options, no getopt */
     recursive_action("/sys/bus/usb/devices",
             ACTION_RECURSE,
             fileAction,
             NULL, /* dirAction */
             NULL /* userData */
     );
     return EXIT_SUCCESS;
 }
References ACTION_RECURSE, EXIT_SUCCESS, fileAction(), NULL, and recursive_action().
lsusb_main() [2/2]
int lsusb_main (int argc, char ** argv)