Fennix Userspace: Userspace/apps/base/busybox/libbb/u_signal_names.c File Reference
u_signal_names.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC get_signum (const char *name)
const char *FAST_FUNC get_signame (int number)
void FAST_FUNC print_signames (void)
Variables
static const char signals[][7] ALIGN1
Function Documentation
get_signame()
const char* FAST_FUNC get_signame (int number)
Definition at line 234 of file u_signal_names.c.
 {
     if ((unsigned)number < ARRAY_SIZE(signals)) {
         if (signals[number][0]) /* if it's not an empty str */
             return signals[number];
     }
     return itoa(number);
 }
References ARRAY_SIZE, itoa, and number().
Referenced by kill_main(), and trapcmd().
get_signum()
int FAST_FUNC get_signum (const char * name)
Definition at line 152 of file u_signal_names.c.
 {
     unsigned i;
     /* bb_strtou returns UINT_MAX on error. NSIG is smaller
      * than UINT_MAX on any sane Unix. Hence no need
      * to check errno after bb_strtou().
      */
     i = bb_strtou(name, NULL, 10);
     if (i < NSIG) /* for shells, we allow 0 too */
         return i;
     if (strncasecmp(name, "SIG", 3) == 0)
         name += 3;
     for (i = 0; i < ARRAY_SIZE(signals); i++)
         if (strcasecmp(name, signals[i]) == 0)
             return i;
 #if ENABLE_DESKTOP
 # if defined(SIGIOT) || defined(SIGIO)
     /* SIGIO[T] are aliased to other names,
      * thus cannot be stored in the signals[] array.
      * Need special code to recognize them */
     if ((name[0] | 0x20) == 'i' && (name[1] | 0x20) == 'o') {
 #  ifdef SIGIO
         if (!name[2])
             return SIGIO;
 #  endif
 #  ifdef SIGIOT
         if ((name[2] | 0x20) == 't' && !name[3])
             return SIGIOT;
 #  endif
     }
 # endif
 #endif
 #if ENABLE_FEATURE_RTMINMAX && defined(SIGRTMIN) && defined(SIGRTMAX)
     {
 # if ENABLE_FEATURE_RTMINMAX_USE_LIBC_DEFINITIONS
         /* Use the libc provided values. */
         unsigned sigrtmin = SIGRTMIN;
         unsigned sigrtmax = SIGRTMAX;
 # else
     /* Use the "raw" SIGRTMIN/MAX. Underscored names, if exist, provide
      * them. If they don't exist, fall back to non-underscored ones: */
 #  if !defined(__SIGRTMIN)
 #   define __SIGRTMIN SIGRTMIN
 #  endif
 #  if !defined(__SIGRTMAX)
 #   define __SIGRTMAX SIGRTMAX
 #  endif
 #  define sigrtmin __SIGRTMIN
 #  define sigrtmax __SIGRTMAX
 # endif
         if (strncasecmp(name, "RTMIN", 5) == 0) {
             if (!name[5])
                 return sigrtmin;
             if (name[5] == '+') {
                 i = bb_strtou(name + 6, NULL, 10);
                 if (i <= sigrtmax - sigrtmin)
                     return sigrtmin + i;
             }
         }
         else if (strncasecmp(name, "RTMAX", 5) == 0) {
             if (!name[5])
                 return sigrtmax;
             if (name[5] == '-') {
                 i = bb_strtou(name + 6, NULL, 10);
                 if (i <= sigrtmax - sigrtmin)
                     return sigrtmax - i;
             }
         }
 # undef sigrtmin
 # undef sigrtmax
     }
 #endif
     return -1;
 }
References ARRAY_SIZE, bb_strtou(), i, NSIG, NULL, SIGIO, SIGIOT, strcasecmp, and strncasecmp.
Referenced by fuser_main(), kill_main(), pgrep_main(), start_stop_daemon_main(), timeout_main(), and trapcmd().
print_signames()
void FAST_FUNC print_signames (void)
Definition at line 247 of file u_signal_names.c.
 {
     unsigned signo;
     for (signo = 1; signo < ARRAY_SIZE(signals); signo++) {
         const char *name = signals[signo];
         if (name[0])
             printf("%2u) %s\n", signo, name);
     }
 #if ENABLE_FEATURE_RTMINMAX
 # if ENABLE_FEATURE_RTMINMAX_USE_LIBC_DEFINITIONS
 #  if defined(SIGRTMIN) && defined(SIGRTMAX)
     printf("%2u) %s\n", SIGRTMIN, "RTMIN");
     printf("%2u) %s\n", SIGRTMAX, "RTMAX");
 #  endif
 # else
 // __SIGRTMIN is included in signals[] array.
 #  ifdef __SIGRTMAX
     printf("%2u) %s\n", __SIGRTMAX, "RTMAX");
 #  endif
 # endif
 #endif
 }
References ARRAY_SIZE, and printf().
Referenced by kill_main(), and pgrep_main().
Variable Documentation
ALIGN1
const char signals [][7] ALIGN1 static
Definition at line 33 of file u_signal_names.c.