Fennix: Userspace/mlibc/options/posix/include/bits/posix/posix_stdio.h File Reference
posix_stdio.h File Reference
#include <bits/off_t.h>
#include <bits/ssize_t.h>
Macros
#define P_tmpdir "/tmp"
Functions
int fileno (FILE *file)
FILE * fdopen (int fd, const char *mode)
FILE * fmemopen (void *__restrict, size_t, const char *__restrict)
int pclose (FILE *)
FILE * popen (const char *, const char *)
FILE * open_memstream (char **, size_t *)
int fseeko (FILE *stream, off_t offset, int whence)
off_t ftello (FILE *stream)
int dprintf (int fd, const char *format,...)
int vdprintf (int fd, const char *format, __gnuc_va_list args)
char * fgetln (FILE *, size_t *)
Macro Definition Documentation
P_tmpdir
#define P_tmpdir "/tmp"
Definition at line 14 of file posix_stdio.h.
Function Documentation
dprintf()
int dprintf (int fd, const char * format, ...)
Definition at line 179 of file posix_stdio.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vdprintf(fd, format, args);
     va_end(args);
     return result;
 }
References args, fd, format, mlibc::result, va_end(), va_start(), and vdprintf().
Referenced by __attribute__(), _vsyslog(), getpass(), main(), preInit1(), and preInit2().
fdopen()
FILE* fdopen (int fd, const char * mode)
Definition at line 82 of file posix-file-io.cpp.
{
     int flags = mlibc::fd_file::parse_modestring(mode);
     flags &= ~O_TRUNC; // 'w' should not truncate the file
     if (flags & O_APPEND) {
         int cur_flags = fcntl(fd, F_GETFL, 0);
         if (cur_flags < 0) {
             errno = EINVAL;
             return nullptr;
         } else if (!(cur_flags & O_APPEND)) {
             if (fcntl(fd, F_SETFL, cur_flags | O_APPEND)) {
                 errno = EINVAL;
                 return nullptr;
             }
         }
     }
     if (flags & O_CLOEXEC) {
         if (fcntl(fd, F_SETFD, FD_CLOEXEC)) {
             errno = EINVAL;
             return nullptr;
         }
     }
     // TODO: We may need to activate line buffered mode for terminals.
     return frg::construct<mlibc::fd_file>(getAllocator(), fd,
             mlibc::file_dispose_cb<mlibc::fd_file>);
 }
References EINVAL, errno, F_GETFL, F_SETFD, F_SETFL, fcntl(), fd, FD_CLOEXEC, mlibc::flags, getAllocator(), O_APPEND, O_CLOEXEC, O_TRUNC, and mlibc::fd_file::parse_modestring().
Referenced by getspnam_r(), and main().
fgetln()
char* fgetln (FILE * , size_t *)
Definition at line 194 of file posix_stdio.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fileno()
int fileno (FILE * file)
Definition at line 585 of file file-io.cpp.
{
     auto file = static_cast<mlibc::fd_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     return fileno_unlocked(file_base);
 }
References fileno_unlocked().
Referenced by I_ConsoleStdout().
fmemopen()
FILE* fmemopen (void * __restrict, size_t , const char * __restrict)
Definition at line 32 of file posix_stdio.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fseeko()
int fseeko (FILE * stream, off_t offset, int whence)
Definition at line 160 of file posix_stdio.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(int e = file->seek(offset, whence); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, offset, and mlibc::whence.
ftello()
off_t ftello (FILE * stream)
Definition at line 169 of file posix_stdio.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     off_t current_offset;
     if(int e = file->tell(&current_offset); e) {
         errno = e;
         return -1;
     }
     return current_offset;
 }
References errno.
open_memstream()
FILE* open_memstream (char ** buf, size_t * sizeloc)
Definition at line 155 of file posix_stdio.cpp.
{
     return frg::construct<mlibc::mem_file>(getAllocator(), buf, sizeloc,
             mlibc::file_dispose_cb<mlibc::mem_file>);
 }
References buf, and getAllocator().
Referenced by main().
pclose()
int pclose (FILE * stream)
Definition at line 37 of file posix_stdio.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_waitpid, -1);
     auto file = static_cast<popen_file *>(stream);
     int status;
     pid_t pid = file->get_popen_pid();
     fclose(file);
     if (mlibc::sys_waitpid(pid, &status, 0, NULL, &pid) != 0) {
         errno = ECHILD;
         return -1;
     }
     return status;
 }
References ECHILD, errno, fclose(), MLIBC_CHECK_OR_ENOSYS, NULL, mlibc::status, and mlibc::sys_waitpid().
Referenced by main().
popen()
FILE* popen (const char * command, const char * typestr)
Definition at line 55 of file posix_stdio.cpp.
{
     bool is_write;
     pid_t child;
     FILE *ret = nullptr;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fork && mlibc::sys_dup2 && mlibc::sys_execve &&
             mlibc::sys_sigprocmask && mlibc::sys_sigaction && mlibc::sys_pipe, nullptr);
     if (typestr == NULL) {
         errno = EINVAL;
         return nullptr;
     }
     if (strstr(typestr, "w") != NULL) {
         is_write = true;
     } else if (strstr(typestr, "r") != NULL) {
         is_write = false;
     } else {
         errno = EINVAL;
         return nullptr;
     }
     bool cloexec = false;
     if (strstr(typestr, "e") != NULL) {
         // Set FD_CLOEXEC on the new file descriptor
         cloexec = true;
     }
     int fds[2];
     if (int e = mlibc::sys_pipe(fds, 0)) {
         errno = e;
         return nullptr;
     }
     struct sigaction new_sa, old_int, old_quit;
     sigset_t new_mask, old_mask;
     new_sa.sa_handler = SIG_IGN;
     new_sa.sa_flags = 0;
     sigemptyset(&new_sa.sa_mask);
     mlibc::sys_sigaction(SIGINT, &new_sa, &old_int);
     mlibc::sys_sigaction(SIGQUIT, &new_sa, &old_quit);
     sigemptyset(&new_mask);
     sigaddset(&new_mask, SIGCHLD);
     mlibc::sys_sigprocmask(SIG_BLOCK, &new_mask, &old_mask);
     int parent_end = is_write ? 1 : 0;
     int child_end = is_write ? 0 : 1;
     if (int e = mlibc::sys_fork(&child)) {
         errno = e;
         mlibc::sys_close(fds[0]);
         mlibc::sys_close(fds[1]);
     } else if (!child) {
         // For the child
         mlibc::sys_sigaction(SIGINT, &old_int, nullptr);
         mlibc::sys_sigaction(SIGQUIT, &old_quit, nullptr);
         mlibc::sys_sigprocmask(SIG_SETMASK, &old_mask, nullptr);
         mlibc::sys_close(fds[parent_end]);
         if (mlibc::sys_dup2(fds[child_end], 0, is_write ? 0 : 1)) {
             __ensure(!"sys_dup2() failed in popen()");
         }
         mlibc::sys_close(fds[child_end]);
         const char *args[] = {
             "sh", "-c", command, nullptr
         };
         mlibc::sys_execve("/bin/sh", const_cast<char **>(args), environ);
         _Exit(127);
     } else {
         // For the parent
         mlibc::sys_close(fds[child_end]);
         ret = frg::construct<popen_file>(
             getAllocator(),
             fds[parent_end],
             mlibc::file_dispose_cb<popen_file>
         );
         __ensure(ret);
         auto file = static_cast<popen_file *>(ret);
         file->set_popen_pid(child);
         if (cloexec == true) {
             fcntl(file->fd(), F_SETFD, O_CLOEXEC);
         }
     }
     mlibc::sys_sigaction(SIGINT, &old_int, nullptr);
     mlibc::sys_sigaction(SIGQUIT, &old_quit, nullptr);
     mlibc::sys_sigprocmask(SIG_SETMASK, &old_mask, nullptr);
     return ret;
 }
References __ensure, _Exit, child, EINVAL, environ, errno, F_SETFD, fcntl(), fds, getAllocator(), MLIBC_CHECK_OR_ENOSYS, NULL, O_CLOEXEC, ret, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, popen_file::set_popen_pid(), SIG_BLOCK, SIG_IGN, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, SIGQUIT, strstr(), mlibc::sys_close(), mlibc::sys_dup2(), mlibc::sys_execve(), mlibc::sys_fork(), mlibc::sys_pipe(), mlibc::sys_sigaction(), and mlibc::sys_sigprocmask().
Referenced by main().
vdprintf()
int vdprintf (int fd, const char * format, __gnuc_va_list args)
Definition at line 187 of file posix_stdio.cpp.
{
     mlibc::fd_file file{fd};
     int ret = vfprintf(&file, format, args);
     file.flush();
     return ret;
 }
References fd, format, ret, and vfprintf().
Referenced by dprintf().