Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/r_main.h File Reference
r_main.h File Reference
#include "d_player.h"
#include "r_data.h"
Macros
#define LIGHTLEVELS 16
#define LIGHTSEGSHIFT 4
#define MAXLIGHTSCALE 48
#define LIGHTSCALESHIFT 12
#define MAXLIGHTZ 128
#define LIGHTZSHIFT 20
#define NUMCOLORMAPS 32
Functions
int R_PointOnSide (fixed_t x, fixed_t y, node_t *node)
int R_PointOnSegSide (fixed_t x, fixed_t y, seg_t *line)
angle_t R_PointToAngle (fixed_t x, fixed_t y)
angle_t R_PointToAngle2 (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2)
fixed_t R_PointToDist (fixed_t x, fixed_t y)
fixed_t R_ScaleFromGlobalAngle (angle_t visangle)
subsector_t * R_PointInSubsector (fixed_t x, fixed_t y)
void R_AddPointToBox (int x, int y, fixed_t *box)
void R_RenderPlayerView (player_t *player)
void R_Init (void)
void R_SetViewSize (int blocks, int detail)
Variables
fixed_t viewcos
fixed_t viewsin
int viewwindowx
int viewwindowy
int centerx
int centery
fixed_t centerxfrac
fixed_t centeryfrac
fixed_t projection
int validcount
int linecount
int loopcount
lighttable_t * scalelight [LIGHTLEVELS][MAXLIGHTSCALE]
lighttable_t * scalelightfixed [MAXLIGHTSCALE]
lighttable_t * zlight [LIGHTLEVELS][MAXLIGHTZ]
int extralight
lighttable_t * fixedcolormap
int detailshift
void(* colfunc)(void)
void(* transcolfunc)(void)
void(* basecolfunc)(void)
void(* fuzzcolfunc)(void)
void(* spanfunc)(void)
Macro Definition Documentation
LIGHTLEVELS
#define LIGHTLEVELS 16
Definition at line 61 of file r_main.h.
LIGHTSCALESHIFT
#define LIGHTSCALESHIFT 12
Definition at line 65 of file r_main.h.
LIGHTSEGSHIFT
#define LIGHTSEGSHIFT 4
Definition at line 62 of file r_main.h.
LIGHTZSHIFT
#define LIGHTZSHIFT 20
Definition at line 67 of file r_main.h.
MAXLIGHTSCALE
#define MAXLIGHTSCALE 48
Definition at line 64 of file r_main.h.
MAXLIGHTZ
#define MAXLIGHTZ 128
Definition at line 66 of file r_main.h.
NUMCOLORMAPS
#define NUMCOLORMAPS 32
Definition at line 79 of file r_main.h.
Function Documentation
R_AddPointToBox()
void R_AddPointToBox (int x, int y, fixed_t * box)
Definition at line 123 of file r_main.c.
 {
     if (x< box[BOXLEFT])
     box[BOXLEFT] = x;
     if (x> box[BOXRIGHT])
     box[BOXRIGHT] = x;
     if (y< box[BOXBOTTOM])
     box[BOXBOTTOM] = y;
     if (y> box[BOXTOP])
     box[BOXTOP] = y;
 }
References BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, x, and y.
R_Init()
void R_Init (void)
Definition at line 767 of file r_main.c.
 {
     R_InitData ();
     printf (".");
     R_InitPointToAngle ();
     printf (".");
     R_InitTables ();
     // viewwidth / viewheight / detailLevel are set by the defaults
     printf (".");
     R_SetViewSize (screenblocks, detailLevel);
     R_InitPlanes ();
     printf (".");
     R_InitLightTables ();
     printf (".");
     R_InitSkyMap ();
     R_InitTranslationTables ();
     printf (".");
     framecount = 0;
 }
References detailLevel, framecount, printf(), R_InitData(), R_InitLightTables(), R_InitPlanes(), R_InitPointToAngle(), R_InitSkyMap(), R_InitTables(), R_InitTranslationTables(), R_SetViewSize(), and screenblocks.
Referenced by D_DoomMain().
R_PointInSubsector()
subsector_t* R_PointInSubsector (fixed_t x, fixed_t y)
Definition at line 794 of file r_main.c.
 {
     node_t* node;
     int     side;
     int     nodenum;
     // single subsector is a special case
     if (!numnodes)
     return subsectors;
     nodenum = numnodes-1;
     while (! (nodenum & NF_SUBSECTOR) )
     {
     node = &nodes[nodenum];
     side = R_PointOnSide (x, y, node);
     nodenum = node->children[side];
     }
     return &subsectors[nodenum & ~NF_SUBSECTOR];
 }
References NF_SUBSECTOR, nodes, numnodes, R_PointOnSide(), subsectors, x, and y.
Referenced by G_CheckSpot(), P_CheckPosition(), P_NightmareRespawn(), P_RespawnSpecials(), P_SetThingPosition(), and P_TeleportMove().
R_PointOnSegSide()
int R_PointOnSegSide (fixed_t x, fixed_t y, seg_t * line)
Definition at line 199 of file r_main.c.
 {
     fixed_t lx;
     fixed_t ly;
     fixed_t ldx;
     fixed_t ldy;
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     lx = line->v1->x;
     ly = line->v1->y;
     ldx = line->v2->x - lx;
     ldy = line->v2->y - ly;
     if (!ldx)
     {
     if (x <= lx)
         return ldy > 0;
     return ldy < 0;
     }
     if (!ldy)
     {
     if (y <= ly)
         return ldx < 0;
     return ldx > 0;
     }
     dx = (x - lx);
     dy = (y - ly);
     // Try to quickly decide by looking at sign bits.
     if ( (ldy ^ ldx ^ dx ^ dy)&0x80000000 )
     {
     if  ( (ldy ^ dx) & 0x80000000 )
     {
         // (left is negative)
         return 1;
     }
     return 0;
     }
     left = FixedMul ( ldy>>FRACBITS , dx );
     right = FixedMul ( dy , ldx>>FRACBITS );
     if (right < left)
     {
     // front side
     return 0;
     }
     // back side
     return 1;
 }
References FixedMul(), FRACBITS, seg_t::v1, seg_t::v2, vertex_t::x, x, y, and vertex_t::y.
Referenced by R_DrawSprite().
R_PointOnSide()
int R_PointOnSide (fixed_t x, fixed_t y, node_t * node)
Definition at line 146 of file r_main.c.
 {
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     if (!node->dx)
     {
     if (x <= node->x)
         return node->dy > 0;
     return node->dy < 0;
     }
     if (!node->dy)
     {
     if (y <= node->y)
         return node->dx < 0;
     return node->dx > 0;
     }
     dx = (x - node->x);
     dy = (y - node->y);
     // Try to quickly decide by looking at sign bits.
     if ( (node->dy ^ node->dx ^ dx ^ dy)&0x80000000 )
     {
     if  ( (node->dy ^ dx) & 0x80000000 )
     {
         // (left is negative)
         return 1;
     }
     return 0;
     }
     left = FixedMul ( node->dy>>FRACBITS , dx );
     right = FixedMul ( dy , node->dx>>FRACBITS );
     if (right < left)
     {
     // front side
     return 0;
     }
     // back side
     return 1;
 }
References FixedMul(), FRACBITS, x, and y.
Referenced by R_PointInSubsector(), and R_RenderBSPNode().
R_PointToAngle()
angle_t R_PointToAngle (fixed_t x, fixed_t y)
Definition at line 276 of file r_main.c.
 {
     x -= viewx;
     y -= viewy;
     if ( (!x) && (!y) )
     return 0;
     if (x>= 0)
     {
     // x >=0
     if (y>= 0)
     {
         // y>= 0
         if (x>y)
         {
         // octant 0
         return tantoangle[ SlopeDiv(y,x)];
         }
         else
         {
         // octant 1
         return ANG90-1-tantoangle[ SlopeDiv(x,y)];
         }
     }
     else
     {
         // y<0
         y = -y;
         if (x>y)
         {
         // octant 8
         return -tantoangle[SlopeDiv(y,x)];
         }
         else
         {
         // octant 7
         return ANG270+tantoangle[ SlopeDiv(x,y)];
         }
     }
     }
     else
     {
     // x<0
     x = -x;
     if (y>= 0)
     {
         // y>= 0
         if (x>y)
         {
         // octant 3
         return ANG180-1-tantoangle[ SlopeDiv(y,x)];
         }
         else
         {
         // octant 2
         return ANG90+ tantoangle[ SlopeDiv(x,y)];
         }
     }
     else
     {
         // y<0
         y = -y;
         if (x>y)
         {
         // octant 4
         return ANG180+tantoangle[ SlopeDiv(y,x)];
         }
         else
         {
          // octant 5
         return ANG270-1-tantoangle[ SlopeDiv(x,y)];
         }
     }
     }
     return 0;
 }
References ANG180, ANG270, ANG90, SlopeDiv(), tantoangle, viewx, viewy, x, and y.
Referenced by R_AddLine(), R_CheckBBox(), R_PointToAngle2(), and R_ProjectSprite().
R_PointToAngle2()
angle_t R_PointToAngle2 (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2)
Definition at line 362 of file r_main.c.
 {
     viewx = x1;
     viewy = y1;
     return R_PointToAngle (x2, y2);
 }
References R_PointToAngle(), viewx, viewy, and y1().
Referenced by A_FaceTarget(), A_Punch(), A_Saw(), A_Tracer(), P_DamageMobj(), P_DeathThink(), P_HitSlideLine(), P_LookForPlayers(), P_SpawnMissile(), S_AdjustSoundParams(), and ST_updateFaceWidget().
R_PointToDist()
fixed_t R_PointToDist (fixed_t x, fixed_t y)
Definition at line 376 of file r_main.c.
 {
     int     angle;
     fixed_t dx;
     fixed_t dy;
     fixed_t temp;
     fixed_t dist;
     fixed_t     frac;
     dx = abs(x - viewx);
     dy = abs(y - viewy);
     if (dy>dx)
     {
     temp = dx;
     dx = dy;
     dy = temp;
     }
     // Fix crashes in udm1.wad
     if (dx != 0)
     {
         frac = FixedDiv(dy, dx);
     }
     else
     {
     frac = 0;
     }
     angle = (tantoangle[frac>>DBITS]+ANG90) >> ANGLETOFINESHIFT;
     // use as cosine
     dist = FixedDiv (dx, finesine[angle] );
     return dist;
 }
References abs(), ANG90, ANGLETOFINESHIFT, DBITS, finesine, FixedDiv(), tantoangle, viewx, viewy, x, and y.
Referenced by R_StoreWallRange().
R_RenderPlayerView()
void R_RenderPlayerView (player_t * player)
Definition at line 863 of file r_main.c.
 {
     R_SetupFrame (player);
     // Clear buffers.
     R_ClearClipSegs ();
     R_ClearDrawSegs ();
     R_ClearPlanes ();
     R_ClearSprites ();
     // check for new console commands.
     NetUpdate ();
     // The head node is the last node output.
     R_RenderBSPNode (numnodes-1);
     // Check for new console commands.
     NetUpdate ();
     R_DrawPlanes ();
     // Check for new console commands.
     NetUpdate ();
     R_DrawMasked ();
     // Check for new console commands.
     NetUpdate ();
 }
References NetUpdate(), numnodes, R_ClearClipSegs(), R_ClearDrawSegs(), R_ClearPlanes(), R_ClearSprites(), R_DrawMasked(), R_DrawPlanes(), R_RenderBSPNode(), and R_SetupFrame().
Referenced by D_Display().
R_ScaleFromGlobalAngle()
fixed_t R_ScaleFromGlobalAngle (angle_t visangle)
Definition at line 449 of file r_main.c.
 {
     fixed_t     scale;
     angle_t     anglea;
     angle_t     angleb;
     int         sinea;
     int         sineb;
     fixed_t     num;
     int         den;
     // UNUSED
 #if 0
 {
     fixed_t     dist;
     fixed_t     z;
     fixed_t     sinv;
     fixed_t     cosv;
     sinv = finesine[(visangle-rw_normalangle)>>ANGLETOFINESHIFT];
     dist = FixedDiv (rw_distance, sinv);
     cosv = finecosine[(viewangle-visangle)>>ANGLETOFINESHIFT];
     z = abs(FixedMul (dist, cosv));
     scale = FixedDiv(projection, z);
     return scale;
 }
 #endif
     anglea = ANG90 + (visangle-viewangle);
     angleb = ANG90 + (visangle-rw_normalangle);
     // both sines are allways positive
     sinea = finesine[anglea>>ANGLETOFINESHIFT];
     sineb = finesine[angleb>>ANGLETOFINESHIFT];
     num = FixedMul(projection,sineb)<<detailshift;
     den = FixedMul(rw_distance,sinea);
     if (den > num>>16)
     {
     scale = FixedDiv (num, den);
     if (scale > 64*FRACUNIT)
         scale = 64*FRACUNIT;
     else if (scale < 256)
         scale = 256;
     }
     else
     scale = 64*FRACUNIT;
     return scale;
 }
References abs(), ANG90, ANGLETOFINESHIFT, detailshift, finecosine, finesine, FixedDiv(), FixedMul(), FRACUNIT, num, projection, rw_distance, rw_normalangle, and viewangle.
Referenced by R_StoreWallRange().
R_SetViewSize()
void R_SetViewSize (int blocks, int detail)
Definition at line 654 of file r_main.c.
 {
     setsizeneeded = true;
     setblocks = blocks;
     setdetail = detail;
 }
References detail, setblocks, setdetail, and setsizeneeded.
Referenced by M_ChangeDetail(), M_SizeDisplay(), and R_Init().
Variable Documentation
basecolfunc
void(* basecolfunc) (void) (void) extern
Definition at line 110 of file r_main.c.
Referenced by R_DrawVisSprite(), and R_ExecuteSetViewSize().
centerx
int centerx extern
Definition at line 56 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), and R_InitTextureMapping().
centerxfrac
fixed_t centerxfrac extern
Definition at line 59 of file r_main.c.
Referenced by R_ClearPlanes(), R_DrawPSprite(), R_ExecuteSetViewSize(), R_InitTextureMapping(), and R_ProjectSprite().
centery
int centery extern
Definition at line 57 of file r_main.c.
Referenced by R_DrawColumn(), R_DrawColumnLow(), R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawTranslatedColumn(), R_DrawTranslatedColumnLow(), and R_ExecuteSetViewSize().
centeryfrac
fixed_t centeryfrac extern
Definition at line 60 of file r_main.c.
Referenced by R_DrawVisSprite(), R_ExecuteSetViewSize(), R_RenderMaskedSegRange(), and R_StoreWallRange().
colfunc
void(* colfunc) (void) (void) extern
Definition at line 109 of file r_main.c.
Referenced by R_DrawMaskedColumn(), R_DrawPlanes(), R_DrawVisSprite(), R_ExecuteSetViewSize(), and R_RenderSegLoop().
detailshift
int detailshift extern
Definition at line 82 of file r_main.c.
Referenced by R_DrawPlanes(), R_DrawPSprite(), R_DrawVisSprite(), R_ExecuteSetViewSize(), R_ProjectSprite(), R_ScaleFromGlobalAngle(), and R_StoreWallRange().
extralight
int extralight extern
Definition at line 105 of file r_main.c.
Referenced by R_AddSprites(), R_DrawPlanes(), R_DrawPlayerSprites(), R_RenderMaskedSegRange(), R_SetupFrame(), and R_StoreWallRange().
fixedcolormap
lighttable_t* fixedcolormap extern
Definition at line 53 of file r_main.c.
Referenced by R_DrawPSprite(), R_MapPlane(), R_ProjectSprite(), R_RenderMaskedSegRange(), R_SetupFrame(), and R_StoreWallRange().
fuzzcolfunc
void(* fuzzcolfunc) (void) (void) extern
Definition at line 111 of file r_main.c.
Referenced by R_DrawVisSprite(), and R_ExecuteSetViewSize().
linecount
int linecount extern
Definition at line 67 of file r_main.c.
loopcount
int loopcount extern
Definition at line 68 of file r_main.c.
projection
fixed_t projection extern
Definition at line 61 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), R_ProjectSprite(), R_ScaleFromGlobalAngle(), and R_StoreWallRange().
scalelight
lighttable_t* scalelight[LIGHTLEVELS][MAXLIGHTSCALE] extern
Definition at line 100 of file r_main.c.
Referenced by R_AddSprites(), R_DrawPlayerSprites(), R_ExecuteSetViewSize(), R_RenderMaskedSegRange(), and R_StoreWallRange().
scalelightfixed
lighttable_t* scalelightfixed[MAXLIGHTSCALE] extern
Definition at line 101 of file r_main.c.
Referenced by R_SetupFrame().
spanfunc
void(* spanfunc) (void) (void) extern
Definition at line 113 of file r_main.c.
Referenced by R_ExecuteSetViewSize(), and R_MapPlane().
transcolfunc
void(* transcolfunc) (void) (void) extern
Definition at line 112 of file r_main.c.
Referenced by R_DrawVisSprite(), and R_ExecuteSetViewSize().
validcount
int validcount extern
Definition at line 50 of file r_main.c.
Referenced by P_BlockLinesIterator(), P_CheckPosition(), P_CheckSight(), P_CrossSubsector(), P_NoiseAlert(), P_PathTraverse(), P_RecursiveSound(), P_TeleportMove(), R_AddSprites(), and R_SetupFrame().
viewcos
fixed_t viewcos extern
Definition at line 76 of file r_main.c.
Referenced by R_ProjectSprite(), R_SetupFrame(), and R_StoreWallRange().
viewsin
fixed_t viewsin extern
Definition at line 77 of file r_main.c.
Referenced by R_ProjectSprite(), R_SetupFrame(), and R_StoreWallRange().
viewwindowx
int viewwindowx extern
Definition at line 61 of file r_draw.c.
Referenced by D_Display(), HUlib_eraseTextLine(), R_FillBackScreen(), and R_InitBuffer().
viewwindowy
int viewwindowy extern
Definition at line 62 of file r_draw.c.
Referenced by D_Display(), HUlib_eraseTextLine(), R_FillBackScreen(), and R_InitBuffer().
zlight
lighttable_t* zlight[LIGHTLEVELS][MAXLIGHTZ] extern
Definition at line 102 of file r_main.c.
Referenced by R_DrawPlanes(), and R_InitLightTables().