Fennix: Userspace/musl/src/malloc/oldmalloc/malloc.c File Reference
malloc.c File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <stdint.h>
#include <errno.h>
#include <sys/mman.h>
#include "libc.h"
#include "atomic.h"
#include "pthread_impl.h"
#include "malloc_impl.h"
#include "fork_impl.h"
Macros
#define _GNU_SOURCE
#define malloc __libc_malloc_impl
#define realloc __libc_realloc
#define free __libc_free
Functions
static void lock (volatile int *lk)
static void unlock (volatile int *lk)
static void lock_bin (int i)
static void unlock_bin (int i)
static int first_set (uint64_t x)
static int bin_index (size_t x)
static int bin_index_up (size_t x)
static int traverses_stack_p (uintptr_t old, uintptr_t new)
static void * __expand_heap (size_t *pn)
static struct chunk * expand_heap (size_t n)
static int adjust_size (size_t *n)
static void unbin (struct chunk *c, int i)
static void bin_chunk (struct chunk *self, int i)
static void trim (struct chunk *self, size_t n)
void * malloc (size_t n)
The standard function.
int __malloc_allzerop (void *p)
void * realloc (void *p, size_t n)
The standard function.
void __bin_chunk (struct chunk *self)
static void unmap_chunk (struct chunk *self)
void free (void *p)
The standard function.
void __malloc_donate (char *start, char *end)
void __malloc_atfork (int who)
Variables
struct {
volatile uint64_t binmap
struct bin bins [64]
volatile int split_merge_lock [2]
} mal
static const unsigned char bin_tab [60]
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file malloc.c.
free
#define free __libc_free
Definition at line 16 of file malloc.c.
malloc
#define malloc __libc_malloc_impl
Definition at line 14 of file malloc.c.
realloc
#define realloc __libc_realloc
Definition at line 15 of file malloc.c.
Function Documentation
__bin_chunk()
void __bin_chunk (struct chunk * self)
Definition at line 434 of file malloc.c.
 {
     struct chunk *next = NEXT_CHUNK(self);
     /* Crash on corrupted footer (likely from buffer overflow) */
     if (next->psize != self->csize) a_crash();
     lock(mal.split_merge_lock);
     size_t osize = CHUNK_SIZE(self), size = osize;
     /* Since we hold split_merge_lock, only transition from free to
      * in-use can race; in-use to free is impossible */
     size_t psize = self->psize & C_INUSE ? 0 : CHUNK_PSIZE(self);
     size_t nsize = next->csize & C_INUSE ? 0 : CHUNK_SIZE(next);
     if (psize) {
         int i = bin_index(psize);
         lock_bin(i);
         if (!(self->psize & C_INUSE)) {
             struct chunk *prev = PREV_CHUNK(self);
             unbin(prev, i);
             self = prev;
             size += psize;
         }
         unlock_bin(i);
     }
     if (nsize) {
         int i = bin_index(nsize);
         lock_bin(i);
         if (!(next->csize & C_INUSE)) {
             unbin(next, i);
             next = NEXT_CHUNK(next);
             size += nsize;
         }
         unlock_bin(i);
     }
     int i = bin_index(size);
     lock_bin(i);
     self->csize = size;
     next->psize = size;
     bin_chunk(self, i);
     unlock(mal.split_merge_lock);
     /* Replace middle of large chunks with fresh zero pages */
     if (size > RECLAIM && (size^(size-osize)) > size-osize) {
         uintptr_t a = (uintptr_t)self + SIZE_ALIGN+PAGE_SIZE-1 & -PAGE_SIZE;
         uintptr_t b = (uintptr_t)next - SIZE_ALIGN & -PAGE_SIZE;
         int e = errno;
 #if 1
         __madvise((void *)a, b-a, MADV_DONTNEED);
 #else
         __mmap((void *)a, b-a, PROT_READ|PROT_WRITE,
             MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0);
 #endif
         errno = e;
     }
     unlock_bin(i);
 }
References __madvise(), __mmap(), a_crash, bin_chunk(), bin_index(), C_INUSE, CHUNK_PSIZE, CHUNK_SIZE, errno, i, lock(), lock_bin(), mal, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, next, NEXT_CHUNK, PAGE_SIZE, chunk::prev, PREV_CHUNK, PROT_READ, PROT_WRITE, chunk::psize, RECLAIM, size, SIZE_ALIGN, unbin(), unlock(), and unlock_bin().
Referenced by __malloc_donate(), aligned_alloc(), free(), and realloc().
__expand_heap()
static void* __expand_heap (size_t * pn) static
Definition at line 162 of file malloc.c.
 {
     static uintptr_t brk;
     static unsigned mmap_step;
     size_t n = *pn;
     if (n > SIZE_MAX/2 - PAGE_SIZE) {
         errno = ENOMEM;
         return 0;
     }
     n += -n & PAGE_SIZE-1;
     if (!brk) {
         brk = __syscall(SYS_brk, 0);
         brk += -brk & PAGE_SIZE-1;
     }
     if (n < SIZE_MAX-brk && !traverses_stack_p(brk, brk+n)
         && __syscall(SYS_brk, brk+n)==brk+n) {
         *pn = n;
         brk += n;
         return (void *)(brk-n);
     }
     size_t min = (size_t)PAGE_SIZE << mmap_step/2;
     if (n < min) n = min;
     void *area = __mmap(0, n, PROT_READ|PROT_WRITE,
         MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
     if (area == MAP_FAILED) return 0;
     *pn = n;
     mmap_step++;
     return area;
 }
References __mmap(), __syscall, brk(), ENOMEM, errno, MAP_ANONYMOUS, MAP_FAILED, MAP_PRIVATE, min, n, PAGE_SIZE, PROT_READ, PROT_WRITE, SIZE_MAX, and traverses_stack_p().
Referenced by expand_heap().
__malloc_allzerop()
int __malloc_allzerop (void * p)
Definition at line 347 of file malloc.c.
 {
     return IS_MMAPPED(MEM_TO_CHUNK(p));
 }
References IS_MMAPPED, MEM_TO_CHUNK, and p.
Referenced by calloc().
__malloc_atfork()
void __malloc_atfork (int who)
Definition at line 540 of file malloc.c.
 {
     if (who<0) {
         lock(mal.split_merge_lock);
         for (int i=0; i<64; i++)
             lock(mal.bins[i].lock);
     } else if (!who) {
         for (int i=0; i<64; i++)
             unlock(mal.bins[i].lock);
         unlock(mal.split_merge_lock);
     } else {
         for (int i=0; i<64; i++)
             mal.bins[i].lock[0] = mal.bins[i].lock[1] = 0;
         mal.split_merge_lock[1] = 0;
         mal.split_merge_lock[0] = 0;
     }
 }
References i, lock(), mal, and unlock().
Referenced by fork().
__malloc_donate()
void __malloc_donate (char * start, char * end)
Definition at line 521 of file malloc.c.
 {
     size_t align_start_up = (SIZE_ALIGN-1) & (-(uintptr_t)start - OVERHEAD);
     size_t align_end_down = (SIZE_ALIGN-1) & (uintptr_t)end;
     /* Getting past this condition ensures that the padding for alignment
      * and header overhead will not overflow and will leave a nonzero
      * multiple of SIZE_ALIGN bytes between start and end. */
     if (end - start <= OVERHEAD + align_start_up + align_end_down)
         return;
     start += align_start_up + OVERHEAD;
     end   -= align_end_down;
     struct chunk *c = MEM_TO_CHUNK(start), *n = MEM_TO_CHUNK(end);
     c->psize = n->csize = C_INUSE;
     c->csize = n->psize = C_INUSE | (end-start);
     __bin_chunk(c);
 }
References __bin_chunk(), c, C_INUSE, donate(), end, MEM_TO_CHUNK, n, OVERHEAD, SIZE_ALIGN, and start.
Referenced by reclaim().
adjust_size()
static int adjust_size (size_t * n) static
Definition at line 234 of file malloc.c.
 {
     /* Result of pointer difference must fit in ptrdiff_t. */
     if (*n-1 > PTRDIFF_MAX - SIZE_ALIGN - PAGE_SIZE) {
         if (*n) {
             errno = ENOMEM;
             return -1;
         } else {
             *n = SIZE_ALIGN;
             return 0;
         }
     }
     *n = (*n + OVERHEAD + SIZE_ALIGN - 1) & SIZE_MASK;
     return 0;
 }
References ENOMEM, errno, n, OVERHEAD, PAGE_SIZE, PTRDIFF_MAX, SIZE_ALIGN, and SIZE_MASK.
Referenced by malloc(), and realloc().
bin_chunk()
static void bin_chunk (struct chunk * self, int i) static
Definition at line 260 of file malloc.c.
 {
     self->next = BIN_TO_CHUNK(i);
     self->prev = mal.bins[i].tail;
     self->next->prev = self;
     self->prev->next = self;
     if (self->prev == BIN_TO_CHUNK(i))
         a_or_64(&mal.binmap, 1ULL<<i);
 }
References a_or_64, BIN_TO_CHUNK, i, and mal.
Referenced by __bin_chunk(), and trim().
bin_index()
static int bin_index (size_t x) static
Definition at line 93 of file malloc.c.
 {
     x = x / SIZE_ALIGN - 1;
     if (x <= 32) return x;
     if (x < 512) return bin_tab[x/8-4];
     if (x > 0x1c00) return 63;
     return bin_tab[x/128-4] + 16;
 }
References bin_tab, SIZE_ALIGN, and x.
Referenced by __bin_chunk(), realloc(), and trim().
bin_index_up()
static int bin_index_up (size_t x) static
Definition at line 102 of file malloc.c.
 {
     x = x / SIZE_ALIGN - 1;
     if (x <= 32) return x;
     x--;
     if (x < 512) return bin_tab[x/8-4] + 1;
     return bin_tab[x/128-4] + 17;
 }
References bin_tab, SIZE_ALIGN, and x.
Referenced by malloc(), and realloc().
expand_heap()
static struct chunk* expand_heap (size_t n) static
Definition at line 196 of file malloc.c.
 {
     static void *end;
     void *p;
     struct chunk *w;
     /* The argument n already accounts for the caller's chunk
      * overhead needs, but if the heap can't be extended in-place,
      * we need room for an extra zero-sized sentinel chunk. */
     n += SIZE_ALIGN;
     p = __expand_heap(&n);
     if (!p) return 0;
     /* If not just expanding existing space, we need to make a
      * new sentinel chunk below the allocated space. */
     if (p != end) {
         /* Valid/safe because of the prologue increment. */
         n -= SIZE_ALIGN;
         p = (char *)p + SIZE_ALIGN;
         w = MEM_TO_CHUNK(p);
         w->psize = 0 | C_INUSE;
     }
     /* Record new heap end and fill in footer. */
     end = (char *)p + n;
     w = MEM_TO_CHUNK(end);
     w->psize = n | C_INUSE;
     w->csize = 0 | C_INUSE;
     /* Fill in header, which may be new or may be replacing a
      * zero-size sentinel header at the old end-of-heap. */
     w = MEM_TO_CHUNK(p);
     w->csize = n | C_INUSE;
     return w;
 }
References __expand_heap(), C_INUSE, end, MEM_TO_CHUNK, n, p, SIZE_ALIGN, and w.
Referenced by malloc().
first_set()
static int first_set (uint64_t x) static
Definition at line 59 of file malloc.c.
 {
 #if 1
     return a_ctz_64(x);
 #else
     static const char debruijn64[64] = {
         0, 1, 2, 53, 3, 7, 54, 27, 4, 38, 41, 8, 34, 55, 48, 28,
         62, 5, 39, 46, 44, 42, 22, 9, 24, 35, 59, 56, 49, 18, 29, 11,
         63, 52, 6, 26, 37, 40, 33, 47, 61, 45, 43, 21, 23, 58, 17, 10,
         51, 25, 36, 32, 60, 20, 57, 16, 50, 31, 19, 15, 30, 14, 13, 12
     };
     static const char debruijn32[32] = {
         0, 1, 23, 2, 29, 24, 19, 3, 30, 27, 25, 11, 20, 8, 4, 13,
         31, 22, 28, 18, 26, 10, 7, 12, 21, 17, 9, 6, 16, 5, 15, 14
     };
     if (sizeof(long) < 8) {
         uint32_t y = x;
         if (!y) {
             y = x>>32;
             return 32 + debruijn32[(y&-y)*0x076be629 >> 27];
         }
         return debruijn32[(y&-y)*0x076be629 >> 27];
     }
     return debruijn64[(x&-x)*0x022fdd63cc95386dull >> 58];
 #endif
 }
References a_ctz_64, x, and y.
Referenced by malloc().
lock()
static void lock (volatile int * lk) inline static
Definition at line 30 of file malloc.c.
 {
     int need_locks = libc.need_locks;
     if (need_locks) {
         while(a_swap(lk, 1)) __wait(lk, lk+1, 1, 1);
         if (need_locks < 0) libc.need_locks = 0;
     }
 }
References __wait(), a_swap, and libc.
Referenced by __bin_chunk(), __malloc_atfork(), lock_bin(), malloc(), and realloc().
lock_bin()
static void lock_bin (int i) inline static
Definition at line 47 of file malloc.c.
 {
     lock(mal.bins[i].lock);
     if (!mal.bins[i].head)
         mal.bins[i].head = mal.bins[i].tail = BIN_TO_CHUNK(i);
 }
References BIN_TO_CHUNK, i, lock(), and mal.
Referenced by __bin_chunk(), malloc(), realloc(), and trim().
traverses_stack_p()
static int traverses_stack_p (uintptr_t old, uintptr_t new) static
Definition at line 138 of file malloc.c.
 {
     const uintptr_t len = 8<<20;
     uintptr_t a, b;
     b = (uintptr_t)libc.auxv;
     a = b > len ? b-len : 0;
     if (new>a && old<b) return 1;
     b = (uintptr_t)&b;
     a = b > len ? b-len : 0;
     if (new>a && old<b) return 1;
     return 0;
 }
References if(), len, libc, and old.
Referenced by __expand_heap().
trim()
static void trim (struct chunk * self, size_t n) static
Definition at line 270 of file malloc.c.
 {
     size_t n1 = CHUNK_SIZE(self);
     struct chunk *next, *split;
     if (n >= n1 - DONTCARE) return;
     next = NEXT_CHUNK(self);
     split = (void *)((char *)self + n);
     split->psize = n | C_INUSE;
     split->csize = n1-n;
     next->psize = n1-n;
     self->csize = n | C_INUSE;
     int i = bin_index(n1-n);
     lock_bin(i);
     bin_chunk(split, i);
     unlock_bin(i);
 }
References bin_chunk(), bin_index(), C_INUSE, CHUNK_SIZE, chunk::csize, DONTCARE, i, lock_bin(), n, next, NEXT_CHUNK, chunk::psize, and unlock_bin().
Referenced by malloc(), and realloc().
unbin()
static void unbin (struct chunk * c, int i) static
Definition at line 250 of file malloc.c.
 {
     if (c->prev == c->next)
         a_and_64(&mal.binmap, ~(1ULL<<i));
     c->prev->next = c->next;
     c->next->prev = c->prev;
     c->csize |= C_INUSE;
     NEXT_CHUNK(c)->psize |= C_INUSE;
 }
References a_and_64, c, C_INUSE, i, mal, and NEXT_CHUNK.
Referenced by __bin_chunk(), malloc(), and realloc().
unlock()
static void unlock (volatile int * lk) inline static
Definition at line 39 of file malloc.c.
 {
     if (lk[0]) {
         a_store(lk, 0);
         if (lk[1]) __wake(lk, 1, 1);
     }
 }
References __wake(), and a_store.
Referenced by __bin_chunk(), __malloc_atfork(), malloc(), realloc(), and unlock_bin().
unlock_bin()
static void unlock_bin (int i) inline static
Definition at line 54 of file malloc.c.
 {
     unlock(mal.bins[i].lock);
 }
References i, mal, and unlock().
Referenced by __bin_chunk(), malloc(), realloc(), and trim().
unmap_chunk()
static void unmap_chunk (struct chunk * self) static
Definition at line 497 of file malloc.c.
 {
     size_t extra = self->psize;
     char *base = (char *)self - extra;
     size_t len = CHUNK_SIZE(self) + extra;
     /* Crash on double free */
     if (extra & 1) a_crash();
     int e = errno;
     __munmap(base, len);
     errno = e;
 }
References __munmap(), a_crash, base, CHUNK_SIZE, errno, and len.
Referenced by free().
Variable Documentation
bin_tab
const unsigned char bin_tab[60] static
Initial value:
= {
                32,33,34,35,36,36,37,37,38,38,39,39,
    40,40,40,40,41,41,41,41,42,42,42,42,43,43,43,43,
    44,44,44,44,44,44,44,44,45,45,45,45,45,45,45,45,
    46,46,46,46,46,46,46,46,47,47,47,47,47,47,47,47,
}
Definition at line 86 of file malloc.c.
Referenced by bin_index(), and bin_index_up().
struct { ... } mal
Referenced by __bin_chunk(), __malloc_atfork(), bin_chunk(), lock_bin(), malloc(), realloc(), unbin(), and unlock_bin().