Fennix: Userspace/apps/base/busybox/networking/udhcp/domain_codec.c File Reference
domain_codec.c File Reference
#include "common.h"
Macros
#define NS_MAXDNAME 1025 /* max domain name length */
#define NS_MAXCDNAME 255 /* max compressed domain name length */
#define NS_MAXLABEL 63 /* max label length */
#define NS_MAXDNSRCH 6 /* max domains in search path */
#define NS_CMPRSFLGS 0xc0 /* name compression pointer flag */
Functions
char *FAST_FUNC dname_dec (const uint8_t *cstr, int clen, const char *pre)
static uint8_t * convert_dname (const char *src, int *retlen)
uint8_t *FAST_FUNC dname_enc (const char *src, int *retlen)
Macro Definition Documentation
NS_CMPRSFLGS
#define NS_CMPRSFLGS 0xc0 /* name compression pointer flag */
Definition at line 29 of file domain_codec.c.
NS_MAXCDNAME
#define NS_MAXCDNAME 255 /* max compressed domain name length */
Definition at line 26 of file domain_codec.c.
NS_MAXDNAME
#define NS_MAXDNAME 1025 /* max domain name length */
Definition at line 25 of file domain_codec.c.
NS_MAXDNSRCH
#define NS_MAXDNSRCH 6 /* max domains in search path */
Definition at line 28 of file domain_codec.c.
NS_MAXLABEL
#define NS_MAXLABEL 63 /* max label length */
Definition at line 27 of file domain_codec.c.
Function Documentation
convert_dname()
static uint8_t* convert_dname (const char * src, int * retlen) static
Definition at line 111 of file domain_codec.c.
 {
     uint8_t *res, *lenptr, *dst;
     res = xzalloc(strlen(src) + 2);
     dst = lenptr = res;
     dst++;
     for (;;) {
         uint8_t c;
         int len;
         c = (uint8_t)*src++;
         if (c == '.' || c == '\0') {  /* end of label */
             len = dst - lenptr - 1;
             /* label too long, too short, or two '.'s in a row (len will be 0) */
             if (len > NS_MAXLABEL || len == 0)
                 goto error;
             *lenptr = len;
             if (c == '\0' || *src == '\0')  /* "" or ".": end of src */
                 break;
             lenptr = dst++;
             continue;
         }
         *dst++ = tolower(c);
     }
     *retlen = dst + 1 - res;
     if (*retlen > NS_MAXCDNAME) {  /* dname too long? abort */
  error:
         free(res);
         *retlen = 0;
         return NULL;
     }
     return res;
 }
References c, dst, error, free, len, NS_MAXCDNAME, NS_MAXLABEL, NULL, retlen, src, strlen, tolower, and xzalloc().
Referenced by dname_enc().
dname_dec()
char* FAST_FUNC dname_dec (const uint8_t * cstr, int clen, const char * pre)
Definition at line 36 of file domain_codec.c.
 {
     char *ret, *end;
     unsigned len, crtpos, retpos, depth;
     crtpos = retpos = depth = 0;
     len = strlen(pre);
     end = ret = xstrdup(pre);
     /* Scan the string once, allocating new memory as needed */
     while (crtpos < clen) {
         const uint8_t *c;
         c = cstr + crtpos;
         if ((*c & NS_CMPRSFLGS) == NS_CMPRSFLGS) {
             /* pointer */
             if (crtpos + 2 > clen) /* no offset to jump to? abort */
                 goto error;
             if (retpos == 0) /* toplevel? save return spot */
                 retpos = crtpos + 2;
             depth++;
             crtpos = ((c[0] << 8) | c[1]) & 0x3fff; /* jump */
         } else if (*c) {
             unsigned label_len;
             /* label */
             if (crtpos + *c + 1 > clen) /* label too long? abort */
                 goto error;
             ret = xrealloc(ret, len + *c + 1);
             /* \3com ---> "com." */
             end = (char *)mempcpy(ret + len, c + 1, *c);
             *end = '.';
             label_len = *c + 1;
             len += label_len;
             crtpos += label_len;
         } else {
             /* NUL: end of current domain name */
             if (retpos == 0) {
                 /* toplevel? keep going */
                 crtpos++;
             } else {
                 /* return to toplevel saved spot */
                 crtpos = retpos;
                 retpos = depth = 0;
             }
             if (len != 0) {
                 /* \4host\3com\0\4host and we are at \0:
                  * \3com was converted to "com.", change dot to space.
                  */
                 ret[len - 1] = ' ';
             }
         }
         if (depth > NS_MAXDNSRCH /* too many jumps? abort, it's a loop */
          || len > NS_MAXDNAME * NS_MAXDNSRCH /* result too long? abort */
         ) {
             goto error;
         }
     }
     if (ret == end) { /* expanded string is empty? abort */
  error:
         free(ret);
         return NULL;
     }
     *end = '\0';
     return ret;
 }
References c, end, error, free, len, mempcpy(), NS_CMPRSFLGS, NS_MAXDNAME, NS_MAXDNSRCH, NULL, strlen, xrealloc, and xstrdup().
Referenced by option_to_env(), and xmalloc_optname_optval().
dname_enc()
uint8_t* FAST_FUNC dname_enc (const char * src, int * retlen)
Definition at line 190 of file domain_codec.c.
 {
 #if 0 //UNUSED, was intended for long, repetitive DHCP_DOMAIN_SEARCH options?
     uint8_t *d, *dname;
 /* Computes string to be appended to cstr so that src would be added to
  * the compression (best case, it's a 2-byte pointer to some offset within
  * cstr; worst case, it's all of src, converted to <4>host<3>com<0> format).
  * The computed string is returned directly; its length is returned via retlen;
  * NULL and 0, respectively, are returned if an error occurs.
  */
     dname = convert_dname(src, retlen);
     if (dname == NULL) {
         return NULL;
     }
     d = dname;
     while (*d) {
         if (cstr) {
             int off = find_offset(cstr, clen, d);
             if (off >= 0) { /* found a match, add pointer and return */
                 *d++ = NS_CMPRSFLGS | (off >> 8);
                 *d = off;
                 break;
             }
         }
         d += *d + 1;
     }
     *retlen = d - dname + 1;
     return dname;
 #endif
     return convert_dname(src, retlen);
 }
References convert_dname(), NS_CMPRSFLGS, NULL, off, retlen, and src.
Referenced by attach_option().