Fennix Userspace: Userspace/apps/base/bash/examples/loadables/perl/bperl.c File Reference
bperl.c File Reference
#include <config.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
Functions
char ** make_builtin_argv (WORD_LIST *, int *)
void perl_close (void)
int perl_main (int, char **, char **)
int bperl_builtin (WORD_LIST *list)
void bperl_builtin_unload (char *s)
Variables
int errno
char ** export_env
char * bperl_doc []
struct builtin bperl_struct
Function Documentation
bperl_builtin()
int bperl_builtin (WORD_LIST * list)
Definition at line 23 of file bperl.c.
 {
     char    **v;
     int c, r;
     v = make_builtin_argv(list, &c);
     r = perl_main(c, v, export_env);
     free(v);
     return r;
 }
References c, export_env, free, make_builtin_argv(), perl_main(), and r.
bperl_builtin_unload()
void bperl_builtin_unload (char * s)
Definition at line 36 of file bperl.c.
 {
     perl_close();
 }
References perl_close().
make_builtin_argv()
char** make_builtin_argv (WORD_LIST * list, int * ip)
Definition at line 370 of file common.c.
 {
   char **argv;
   argv = strvec_from_word_list (list, 0, 1, ip);
   argv[0] = this_command_name;
   return argv;
 }
References argv, strvec_from_word_list(), and this_command_name.
Referenced by bperl_builtin().
perl_close()
void perl_close (void)
Definition at line 13 of file iperl.c.
 {
     PERL_SYS_TERM();
 }
Referenced by bperl_builtin_unload().
perl_main()
int perl_main (int argc, char ** argv, char ** env)
Definition at line 19 of file iperl.c.
 {
     int r;
     if (first) {
         first = 0;
         PERL_SYS_INIT3(&argc, &argv, &env);
     }
     iperl = perl_alloc();
     perl_construct(iperl);
     perl_parse(iperl, xs_init, argc, argv, (char **)NULL);
     r = perl_run(iperl);
 PerlIO_flush(PerlIO_stdout());
 PerlIO_flush(PerlIO_stderr());
     perl_destruct(iperl);
     perl_free(iperl);
     return (r);
 }
References argc, argv, env, first, iperl, NULL, r, and xs_init().
Referenced by bperl_builtin().
Variable Documentation
bperl_doc
char* bperl_doc[]
Initial value:
= {
    "An interface to a perl5 interpreter.",
    (char *)0
}
Definition at line 41 of file bperl.c.
bperl_struct
struct builtin bperl_struct
Initial value:
= {
    "bperl",
    bperl_builtin,
    BUILTIN_ENABLED,
    bperl_doc,
    "bperl [perl options] [file ...]",
    0
}
Definition at line 41 of file bperl.c.
errno
int errno extern
export_env
char** export_env extern
Definition at line 176 of file variables.c.
Referenced by bperl_builtin(), and execute_disk_command().