Fennix Userspace: Userspace/musl/include/link.h File Reference
link.h File Reference
#include <elf.h>
#include <bits/alltypes.h>
#include <bits/link.h>
Data Structures
struct dl_phdr_info
struct link_map
struct r_debug
Macros
#define __NEED_size_t
#define __NEED_uint32_t
#define ElfW(type) Elf32_ ## type
Functions
int dl_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *), void *)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 9 of file link.h.
__NEED_uint32_t
#define __NEED_uint32_t
Definition at line 10 of file link.h.
ElfW
#define ElfW (type) Elf32_ ## type
Definition at line 16 of file link.h.
Function Documentation
dl_iterate_phdr()
int dl_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *) callback, void * data)
Definition at line 8 of file phdr.cpp.
{
     return __dlapi_iterate_phdr(callback, data);
 }
References __dlapi_iterate_phdr(), and callback.
Referenced by __gnu_Unwind_Find_exidx(), and main().