Fennix Userspace: Userspace/musl/include/pthread.h File Reference
pthread.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <sched.h>
#include <time.h>
Data Structures
struct __ptcb
Macros
#define __NEED_time_t
#define __NEED_clockid_t
#define __NEED_struct_timespec
#define __NEED_sigset_t
#define __NEED_pthread_t
#define __NEED_pthread_attr_t
#define __NEED_pthread_mutexattr_t
#define __NEED_pthread_condattr_t
#define __NEED_pthread_rwlockattr_t
#define __NEED_pthread_barrierattr_t
#define __NEED_pthread_mutex_t
#define __NEED_pthread_cond_t
#define __NEED_pthread_rwlock_t
#define __NEED_pthread_barrier_t
#define __NEED_pthread_spinlock_t
#define __NEED_pthread_key_t
#define __NEED_pthread_once_t
#define __NEED_size_t
#define PTHREAD_CREATE_JOINABLE 0
#define PTHREAD_CREATE_DETACHED 1
#define PTHREAD_MUTEX_NORMAL 0
#define PTHREAD_MUTEX_DEFAULT 0
#define PTHREAD_MUTEX_RECURSIVE 1
#define PTHREAD_MUTEX_ERRORCHECK 2
#define PTHREAD_MUTEX_STALLED 0
#define PTHREAD_MUTEX_ROBUST 1
#define PTHREAD_PRIO_NONE 0
#define PTHREAD_PRIO_INHERIT 1
#define PTHREAD_PRIO_PROTECT 2
#define PTHREAD_INHERIT_SCHED 0
#define PTHREAD_EXPLICIT_SCHED 1
#define PTHREAD_SCOPE_SYSTEM 0
#define PTHREAD_SCOPE_PROCESS 1
#define PTHREAD_PROCESS_PRIVATE 0
#define PTHREAD_PROCESS_SHARED 1
#define PTHREAD_MUTEX_INITIALIZER {{{0}}}
#define PTHREAD_RWLOCK_INITIALIZER {{{0}}}
#define PTHREAD_COND_INITIALIZER {{{0}}}
#define PTHREAD_ONCE_INIT 0
#define PTHREAD_CANCEL_ENABLE 0
#define PTHREAD_CANCEL_DISABLE 1
#define PTHREAD_CANCEL_MASKED 2
#define PTHREAD_CANCEL_DEFERRED 0
#define PTHREAD_CANCEL_ASYNCHRONOUS 1
#define PTHREAD_CANCELED ((void *)-1)
#define PTHREAD_BARRIER_SERIAL_THREAD (-1)
#define PTHREAD_NULL ((pthread_t)0)
#define pthread_equal(x, y) ((x)==(y))
#define pthread_cleanup_push(f, x) do { struct __ptcb __cb; _pthread_cleanup_push(&__cb, f, x);
#define pthread_cleanup_pop(r) _pthread_cleanup_pop(&__cb, (r)); } while(0)
Functions
int pthread_create (pthread_t *__restrict, const pthread_attr_t *__restrict, void *(*)(void *), void *__restrict)
int pthread_detach (pthread_t)
_Noreturn void pthread_exit (void *)
int pthread_join (pthread_t, void **)
pthread_t pthread_self (void)
int pthread_equal (pthread_t, pthread_t)
int pthread_setcancelstate (int, int *)
int pthread_setcanceltype (int, int *)
void pthread_testcancel (void)
int pthread_cancel (pthread_t)
int pthread_getschedparam (pthread_t, int *__restrict, struct sched_param *__restrict)
int pthread_setschedparam (pthread_t, int, const struct sched_param *)
int pthread_setschedprio (pthread_t, int)
int pthread_once (pthread_once_t *, void(*)(void))
int pthread_mutex_init (pthread_mutex_t *__restrict, const pthread_mutexattr_t *__restrict)
int pthread_mutex_lock (pthread_mutex_t *)
int pthread_mutex_unlock (pthread_mutex_t *)
int pthread_mutex_trylock (pthread_mutex_t *)
int pthread_mutex_timedlock (pthread_mutex_t *__restrict, const struct timespec *__restrict)
int pthread_mutex_destroy (pthread_mutex_t *)
int pthread_mutex_consistent (pthread_mutex_t *)
int pthread_mutex_getprioceiling (const pthread_mutex_t *__restrict, int *__restrict)
int pthread_mutex_setprioceiling (pthread_mutex_t *__restrict, int, int *__restrict)
int pthread_cond_init (pthread_cond_t *__restrict, const pthread_condattr_t *__restrict)
int pthread_cond_destroy (pthread_cond_t *)
int pthread_cond_wait (pthread_cond_t *__restrict, pthread_mutex_t *__restrict)
int pthread_cond_timedwait (pthread_cond_t *__restrict, pthread_mutex_t *__restrict, const struct timespec *__restrict)
int pthread_cond_broadcast (pthread_cond_t *)
int pthread_cond_signal (pthread_cond_t *)
int pthread_rwlock_init (pthread_rwlock_t *__restrict, const pthread_rwlockattr_t *__restrict)
int pthread_rwlock_destroy (pthread_rwlock_t *)
int pthread_rwlock_rdlock (pthread_rwlock_t *)
int pthread_rwlock_tryrdlock (pthread_rwlock_t *)
int pthread_rwlock_timedrdlock (pthread_rwlock_t *__restrict, const struct timespec *__restrict)
int pthread_rwlock_wrlock (pthread_rwlock_t *)
int pthread_rwlock_trywrlock (pthread_rwlock_t *)
int pthread_rwlock_timedwrlock (pthread_rwlock_t *__restrict, const struct timespec *__restrict)
int pthread_rwlock_unlock (pthread_rwlock_t *)
int pthread_spin_init (pthread_spinlock_t *, int)
int pthread_spin_destroy (pthread_spinlock_t *)
int pthread_spin_lock (pthread_spinlock_t *)
int pthread_spin_trylock (pthread_spinlock_t *)
int pthread_spin_unlock (pthread_spinlock_t *)
int pthread_barrier_init (pthread_barrier_t *__restrict, const pthread_barrierattr_t *__restrict, unsigned)
int pthread_barrier_destroy (pthread_barrier_t *)
int pthread_barrier_wait (pthread_barrier_t *)
int pthread_key_create (pthread_key_t *, void(*)(void *))
int pthread_key_delete (pthread_key_t)
void * pthread_getspecific (pthread_key_t)
int pthread_setspecific (pthread_key_t, const void *)
int pthread_attr_init (pthread_attr_t *)
int pthread_attr_destroy (pthread_attr_t *)
int pthread_attr_getguardsize (const pthread_attr_t *__restrict, size_t *__restrict)
int pthread_attr_setguardsize (pthread_attr_t *, size_t)
int pthread_attr_getstacksize (const pthread_attr_t *__restrict, size_t *__restrict)
int pthread_attr_setstacksize (pthread_attr_t *, size_t)
int pthread_attr_getdetachstate (const pthread_attr_t *, int *)
int pthread_attr_setdetachstate (pthread_attr_t *, int)
int pthread_attr_getstack (const pthread_attr_t *__restrict, void **__restrict, size_t *__restrict)
int pthread_attr_setstack (pthread_attr_t *, void *, size_t)
int pthread_attr_getscope (const pthread_attr_t *__restrict, int *__restrict)
int pthread_attr_setscope (pthread_attr_t *, int)
int pthread_attr_getschedpolicy (const pthread_attr_t *__restrict, int *__restrict)
int pthread_attr_setschedpolicy (pthread_attr_t *, int)
int pthread_attr_getschedparam (const pthread_attr_t *__restrict, struct sched_param *__restrict)
int pthread_attr_setschedparam (pthread_attr_t *__restrict, const struct sched_param *__restrict)
int pthread_attr_getinheritsched (const pthread_attr_t *__restrict, int *__restrict)
int pthread_attr_setinheritsched (pthread_attr_t *, int)
int pthread_mutexattr_destroy (pthread_mutexattr_t *)
int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_getprotocol (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_getpshared (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_getrobust (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_gettype (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_init (pthread_mutexattr_t *)
int pthread_mutexattr_setprioceiling (pthread_mutexattr_t *, int)
int pthread_mutexattr_setprotocol (pthread_mutexattr_t *, int)
int pthread_mutexattr_setpshared (pthread_mutexattr_t *, int)
int pthread_mutexattr_setrobust (pthread_mutexattr_t *, int)
int pthread_mutexattr_settype (pthread_mutexattr_t *, int)
int pthread_condattr_init (pthread_condattr_t *)
int pthread_condattr_destroy (pthread_condattr_t *)
int pthread_condattr_setclock (pthread_condattr_t *, clockid_t)
int pthread_condattr_setpshared (pthread_condattr_t *, int)
int pthread_condattr_getclock (const pthread_condattr_t *__restrict, clockid_t *__restrict)
int pthread_condattr_getpshared (const pthread_condattr_t *__restrict, int *__restrict)
int pthread_rwlockattr_init (pthread_rwlockattr_t *)
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *)
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *, int)
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t *__restrict, int *__restrict)
int pthread_barrierattr_destroy (pthread_barrierattr_t *)
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *__restrict, int *__restrict)
int pthread_barrierattr_init (pthread_barrierattr_t *)
int pthread_barrierattr_setpshared (pthread_barrierattr_t *, int)
int pthread_atfork (void(*)(void), void(*)(void), void(*)(void))
int pthread_getconcurrency (void)
int pthread_setconcurrency (int)
int pthread_getcpuclockid (pthread_t, clockid_t *)
void _pthread_cleanup_push (struct __ptcb *, void(*)(void *), void *)
void _pthread_cleanup_pop (struct __ptcb *, int)
Macro Definition Documentation
__NEED_clockid_t
#define __NEED_clockid_t
Definition at line 10 of file pthread.h.
__NEED_pthread_attr_t
#define __NEED_pthread_attr_t
Definition at line 14 of file pthread.h.
__NEED_pthread_barrier_t
#define __NEED_pthread_barrier_t
Definition at line 22 of file pthread.h.
__NEED_pthread_barrierattr_t
#define __NEED_pthread_barrierattr_t
Definition at line 18 of file pthread.h.
__NEED_pthread_cond_t
#define __NEED_pthread_cond_t
Definition at line 20 of file pthread.h.
__NEED_pthread_condattr_t
#define __NEED_pthread_condattr_t
Definition at line 16 of file pthread.h.
__NEED_pthread_key_t
#define __NEED_pthread_key_t
Definition at line 24 of file pthread.h.
__NEED_pthread_mutex_t
#define __NEED_pthread_mutex_t
Definition at line 19 of file pthread.h.
__NEED_pthread_mutexattr_t
#define __NEED_pthread_mutexattr_t
Definition at line 15 of file pthread.h.
__NEED_pthread_once_t
#define __NEED_pthread_once_t
Definition at line 25 of file pthread.h.
__NEED_pthread_rwlock_t
#define __NEED_pthread_rwlock_t
Definition at line 21 of file pthread.h.
__NEED_pthread_rwlockattr_t
#define __NEED_pthread_rwlockattr_t
Definition at line 17 of file pthread.h.
__NEED_pthread_spinlock_t
#define __NEED_pthread_spinlock_t
Definition at line 23 of file pthread.h.
__NEED_pthread_t
#define __NEED_pthread_t
Definition at line 13 of file pthread.h.
__NEED_sigset_t
#define __NEED_sigset_t
Definition at line 12 of file pthread.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 26 of file pthread.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 11 of file pthread.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 9 of file pthread.h.
PTHREAD_BARRIER_SERIAL_THREAD
#define PTHREAD_BARRIER_SERIAL_THREAD (-1)
Definition at line 74 of file pthread.h.
PTHREAD_CANCEL_ASYNCHRONOUS
#define PTHREAD_CANCEL_ASYNCHRONOUS 1
Definition at line 69 of file pthread.h.
PTHREAD_CANCEL_DEFERRED
#define PTHREAD_CANCEL_DEFERRED 0
Definition at line 68 of file pthread.h.
PTHREAD_CANCEL_DISABLE
#define PTHREAD_CANCEL_DISABLE 1
Definition at line 65 of file pthread.h.
PTHREAD_CANCEL_ENABLE
#define PTHREAD_CANCEL_ENABLE 0
Definition at line 64 of file pthread.h.
PTHREAD_CANCEL_MASKED
#define PTHREAD_CANCEL_MASKED 2
Definition at line 66 of file pthread.h.
PTHREAD_CANCELED
#define PTHREAD_CANCELED ((void *)-1)
Definition at line 71 of file pthread.h.
pthread_cleanup_pop
#define pthread_cleanup_pop (r) _pthread_cleanup_pop(&__cb, (r)); } while(0)
Definition at line 216 of file pthread.h.
pthread_cleanup_push
#define pthread_cleanup_push (f, x) do { struct __ptcb __cb; _pthread_cleanup_push(&__cb, f, x);
Definition at line 215 of file pthread.h.
PTHREAD_COND_INITIALIZER
#define PTHREAD_COND_INITIALIZER {{{0}}}
Definition at line 60 of file pthread.h.
PTHREAD_CREATE_DETACHED
#define PTHREAD_CREATE_DETACHED 1
Definition at line 34 of file pthread.h.
PTHREAD_CREATE_JOINABLE
#define PTHREAD_CREATE_JOINABLE 0
Definition at line 33 of file pthread.h.
pthread_equal
#define pthread_equal (x, y) ((x)==(y))
Definition at line 92 of file pthread.h.
PTHREAD_EXPLICIT_SCHED
#define PTHREAD_EXPLICIT_SCHED 1
Definition at line 49 of file pthread.h.
PTHREAD_INHERIT_SCHED
#define PTHREAD_INHERIT_SCHED 0
Definition at line 48 of file pthread.h.
PTHREAD_MUTEX_DEFAULT
#define PTHREAD_MUTEX_DEFAULT 0
Definition at line 37 of file pthread.h.
PTHREAD_MUTEX_ERRORCHECK
#define PTHREAD_MUTEX_ERRORCHECK 2
Definition at line 39 of file pthread.h.
PTHREAD_MUTEX_INITIALIZER
#define PTHREAD_MUTEX_INITIALIZER {{{0}}}
Definition at line 58 of file pthread.h.
PTHREAD_MUTEX_NORMAL
#define PTHREAD_MUTEX_NORMAL 0
Definition at line 36 of file pthread.h.
PTHREAD_MUTEX_RECURSIVE
#define PTHREAD_MUTEX_RECURSIVE 1
Definition at line 38 of file pthread.h.
PTHREAD_MUTEX_ROBUST
#define PTHREAD_MUTEX_ROBUST 1
Definition at line 42 of file pthread.h.
PTHREAD_MUTEX_STALLED
#define PTHREAD_MUTEX_STALLED 0
Definition at line 41 of file pthread.h.
PTHREAD_NULL
#define PTHREAD_NULL ((pthread_t)0)
Definition at line 77 of file pthread.h.
PTHREAD_ONCE_INIT
#define PTHREAD_ONCE_INIT 0
Definition at line 61 of file pthread.h.
PTHREAD_PRIO_INHERIT
#define PTHREAD_PRIO_INHERIT 1
Definition at line 45 of file pthread.h.
PTHREAD_PRIO_NONE
#define PTHREAD_PRIO_NONE 0
Definition at line 44 of file pthread.h.
PTHREAD_PRIO_PROTECT
#define PTHREAD_PRIO_PROTECT 2
Definition at line 46 of file pthread.h.
PTHREAD_PROCESS_PRIVATE
#define PTHREAD_PROCESS_PRIVATE 0
Definition at line 54 of file pthread.h.
PTHREAD_PROCESS_SHARED
#define PTHREAD_PROCESS_SHARED 1
Definition at line 55 of file pthread.h.
PTHREAD_RWLOCK_INITIALIZER
#define PTHREAD_RWLOCK_INITIALIZER {{{0}}}
Definition at line 59 of file pthread.h.
PTHREAD_SCOPE_PROCESS
#define PTHREAD_SCOPE_PROCESS 1
Definition at line 52 of file pthread.h.
PTHREAD_SCOPE_SYSTEM
#define PTHREAD_SCOPE_SYSTEM 0
Definition at line 51 of file pthread.h.
Function Documentation
_pthread_cleanup_pop()
void _pthread_cleanup_pop (struct __ptcb * cb, int run)
Definition at line 16 of file pthread_cleanup_push.c.
 {
     __do_cleanup_pop(cb);
     if (run) cb->__f(cb->__x);
 }
References __do_cleanup_pop(), __ptcb::__f, __ptcb::__x, and run().
_pthread_cleanup_push()
void _pthread_cleanup_push (struct __ptcb * cb, void(*)(void *) f, void * x)
Definition at line 9 of file pthread_cleanup_push.c.
 {
     cb->__f = f;
     cb->__x = x;
     __do_cleanup_push(cb);
 }
References __do_cleanup_push(), __ptcb::__f, __ptcb::__x, f, and x.
pthread_atfork()
int pthread_atfork (void(*)(void) prepare, void(*)(void) parent, void(*)(void) child)
Definition at line 40 of file pthread_atfork.c.
 {
     struct atfork_funcs *new = malloc(sizeof *new);
     if (!new) return ENOMEM;
     LOCK(lock);
     new->next = funcs;
     new->prev = 0;
     new->prepare = prepare;
     new->parent = parent;
     new->child = child;
     if (funcs) funcs->prev = new;
     funcs = new;
     UNLOCK(lock);
     return 0;
 }
References child(), ENOMEM, funcs, LOCK, lock, malloc, parent, prepare(), atfork_funcs::prepare, atfork_funcs::prev, and UNLOCK.
pthread_attr_destroy()
int pthread_attr_destroy (pthread_attr_t * a)
Definition at line 3 of file pthread_attr_destroy.c.
 {
     return 0;
 }
pthread_attr_getdetachstate()
int pthread_attr_getdetachstate (const pthread_attr_t * a, int * state)
Definition at line 3 of file pthread_attr_get.c.
 {
     *state = a->_a_detach;
     return 0;
 }
References state.
pthread_attr_getguardsize()
int pthread_attr_getguardsize (const pthread_attr_t * __restrict, size_t * __restrict)
pthread_attr_getinheritsched()
int pthread_attr_getinheritsched (const pthread_attr_t * __restrict, int * __restrict)
pthread_attr_getschedparam()
int pthread_attr_getschedparam (const pthread_attr_t * __restrict, struct sched_param * __restrict)
pthread_attr_getschedpolicy()
int pthread_attr_getschedpolicy (const pthread_attr_t * __restrict, int * __restrict)
pthread_attr_getscope()
int pthread_attr_getscope (const pthread_attr_t * __restrict, int * __restrict)
pthread_attr_getstack()
int pthread_attr_getstack (const pthread_attr_t * __restrict, void ** __restrict, size_t * __restrict)
pthread_attr_getstacksize()
int pthread_attr_getstacksize (const pthread_attr_t * __restrict, size_t * __restrict)
pthread_attr_init()
int pthread_attr_init (pthread_attr_t * a)
Definition at line 3 of file pthread_attr_init.c.
 {
     *a = (pthread_attr_t){0};
     __acquire_ptc();
     a->_a_stacksize = __default_stacksize;
     a->_a_guardsize = __default_guardsize;
     __release_ptc();
     return 0;
 }
References __acquire_ptc(), __default_guardsize, __default_stacksize, and __release_ptc().
Referenced by lio_listio(), mq_notify(), and submit().
pthread_attr_setdetachstate()
int pthread_attr_setdetachstate (pthread_attr_t * a, int state)
Definition at line 3 of file pthread_attr_setdetachstate.c.
 {
     if (state > 1U) return EINVAL;
     a->_a_detach = state;
     return 0;
 }
References EINVAL, and state.
Referenced by lio_listio(), mq_notify(), and submit().
pthread_attr_setguardsize()
int pthread_attr_setguardsize (pthread_attr_t * a, size_t size)
Definition at line 3 of file pthread_attr_setguardsize.c.
 {
     if (size > SIZE_MAX/8) return EINVAL;
     a->_a_guardsize = size;
     return 0;
 }
References EINVAL, size, and SIZE_MAX.
Referenced by lio_listio(), and submit().
pthread_attr_setinheritsched()
int pthread_attr_setinheritsched (pthread_attr_t * a, int inherit)
Definition at line 4 of file pthread_attr_setinheritsched.c.
 {
     if (inherit > 1U) return EINVAL;
     a->_a_sched = inherit;
     return 0;
 }
References EINVAL.
pthread_attr_setschedparam()
int pthread_attr_setschedparam (pthread_attr_t * __restrict, const struct sched_param * __restrict)
pthread_attr_setschedpolicy()
int pthread_attr_setschedpolicy (pthread_attr_t * a, int policy)
Definition at line 3 of file pthread_attr_setschedpolicy.c.
 {
     a->_a_policy = policy;
     return 0;
 }
pthread_attr_setscope()
int pthread_attr_setscope (pthread_attr_t * a, int scope)
Definition at line 3 of file pthread_attr_setscope.c.
 {
     switch (scope) {
     case PTHREAD_SCOPE_SYSTEM:
         return 0;
     case PTHREAD_SCOPE_PROCESS:
         return ENOTSUP;
     default:
         return EINVAL;
     }
 }
References EINVAL, ENOTSUP, PTHREAD_SCOPE_PROCESS, and PTHREAD_SCOPE_SYSTEM.
pthread_attr_setstack()
int pthread_attr_setstack (pthread_attr_t * a, void * addr, size_t size)
Definition at line 3 of file pthread_attr_setstack.c.
 {
     if (size-PTHREAD_STACK_MIN > SIZE_MAX/4) return EINVAL;
     a->_a_stackaddr = (size_t)addr + size;
     a->_a_stacksize = size;
     return 0;
 }
References addr, EINVAL, size, and SIZE_MAX.
pthread_attr_setstacksize()
int pthread_attr_setstacksize (pthread_attr_t * a, size_t size)
Definition at line 3 of file pthread_attr_setstacksize.c.
 {
     if (size-PTHREAD_STACK_MIN > SIZE_MAX/4) return EINVAL;
     a->_a_stackaddr = 0;
     a->_a_stacksize = size;
     return 0;
 }
References EINVAL, size, and SIZE_MAX.
Referenced by lio_listio(), and submit().
pthread_barrier_destroy()
int pthread_barrier_destroy (pthread_barrier_t * b)
Definition at line 3 of file pthread_barrier_destroy.c.
 {
     if (b->_b_limit < 0) {
         if (b->_b_lock) {
             int v;
             a_or(&b->_b_lock, INT_MIN);
             while ((v = b->_b_lock) & INT_MAX)
                 __wait(&b->_b_lock, 0, v, 0);
         }
         __vm_wait();
     }
     return 0;
 }
References __vm_wait(), __wait(), a_or, INT_MAX, and INT_MIN.
pthread_barrier_init()
int pthread_barrier_init (pthread_barrier_t * __restrict, const pthread_barrierattr_t * __restrict, unsigned)
pthread_barrier_wait()
int pthread_barrier_wait (pthread_barrier_t * b)
Definition at line 60 of file pthread_barrier_wait.c.
 {
     int limit = b->_b_limit;
     struct instance *inst;
     /* Trivial case: count was set at 1 */
     if (!limit) return PTHREAD_BARRIER_SERIAL_THREAD;
     /* Process-shared barriers require a separate, inefficient wait */
     if (limit < 0) return pshared_barrier_wait(b);
     /* Otherwise we need a lock on the barrier object */
     while (a_swap(&b->_b_lock, 1))
         __wait(&b->_b_lock, &b->_b_waiters, 1, 1);
     inst = b->_b_inst;
     /* First thread to enter the barrier becomes the "instance owner" */
     if (!inst) {
         struct instance new_inst = { 0 };
         int spins = 200;
         b->_b_inst = inst = &new_inst;
         a_store(&b->_b_lock, 0);
         if (b->_b_waiters) __wake(&b->_b_lock, 1, 1);
         while (spins-- && !inst->finished)
             a_spin();
         a_inc(&inst->finished);
         while (inst->finished == 1)
             __syscall(SYS_futex,&inst->finished,FUTEX_WAIT|FUTEX_PRIVATE,1,0) != -ENOSYS
             || __syscall(SYS_futex,&inst->finished,FUTEX_WAIT,1,0);
         return PTHREAD_BARRIER_SERIAL_THREAD;
     }
     /* Last thread to enter the barrier wakes all non-instance-owners */
     if (++inst->count == limit) {
         b->_b_inst = 0;
         a_store(&b->_b_lock, 0);
         if (b->_b_waiters) __wake(&b->_b_lock, 1, 1);
         a_store(&inst->last, 1);
         if (inst->waiters)
             __wake(&inst->last, -1, 1);
     } else {
         a_store(&b->_b_lock, 0);
         if (b->_b_waiters) __wake(&b->_b_lock, 1, 1);
         __wait(&inst->last, &inst->waiters, 0, 1);
     }
     /* Last thread to exit the barrier wakes the instance owner */
     if (a_fetch_add(&inst->count,-1)==1 && a_fetch_add(&inst->finished,1))
         __wake(&inst->finished, 1, 1);
     return 0;
 }
References __syscall, __wait(), __wake(), a_fetch_add, a_inc, a_spin, a_store, a_swap, instance::count, ENOSYS, instance::finished, FUTEX_PRIVATE, FUTEX_WAIT, instance::last, limit(), pshared_barrier_wait(), PTHREAD_BARRIER_SERIAL_THREAD, SYS_futex, and instance::waiters.
Referenced by start().
pthread_barrierattr_destroy()
int pthread_barrierattr_destroy (pthread_barrierattr_t * a)
Definition at line 3 of file pthread_barrierattr_destroy.c.
 {
     return 0;
 }
pthread_barrierattr_getpshared()
int pthread_barrierattr_getpshared (const pthread_barrierattr_t * __restrict, int * __restrict)
pthread_barrierattr_init()
int pthread_barrierattr_init (pthread_barrierattr_t * a)
Definition at line 3 of file pthread_barrierattr_init.c.
 {
     *a = (pthread_barrierattr_t){0};
     return 0;
 }
pthread_barrierattr_setpshared()
int pthread_barrierattr_setpshared (pthread_barrierattr_t * a, int pshared)
Definition at line 3 of file pthread_barrierattr_setpshared.c.
 {
     if (pshared > 1U) return EINVAL;
     a->__attr = pshared ? INT_MIN : 0;
     return 0;
 }
References EINVAL, and INT_MIN.
pthread_cancel()
int pthread_cancel (pthread_t t)
Definition at line 92 of file pthread_cancel.c.
 {
     static int init;
     if (!init) {
         init_cancellation();
         init = 1;
     }
     a_store(&t->cancel, 1);
     if (t == pthread_self()) {
         if (t->canceldisable == PTHREAD_CANCEL_ENABLE && t->cancelasync)
             pthread_exit(PTHREAD_CANCELED);
         return 0;
     }
     return pthread_kill(t, SIGCANCEL);
 }
References a_store, init, init_cancellation(), PTHREAD_CANCEL_ENABLE, PTHREAD_CANCELED, pthread_exit(), pthread_kill(), pthread_self(), SIGCANCEL, and t.
Referenced by aio_cancel().
pthread_cond_broadcast()
int pthread_cond_broadcast (pthread_cond_t * c)
Definition at line 3 of file pthread_cond_broadcast.c.
 {
     if (!c->_c_shared) return __private_cond_signal(c, -1);
     if (!c->_c_waiters) return 0;
     a_inc(&c->_c_seq);
     __wake(&c->_c_seq, -1, 0);
     return 0;
 }
References __private_cond_signal(), __wake(), a_inc, and c.
Referenced by cleanup(), and do_init_fini().
pthread_cond_destroy()
int pthread_cond_destroy (pthread_cond_t * c)
Definition at line 3 of file pthread_cond_destroy.c.
 {
     if (c->_c_shared && c->_c_waiters) {
         int cnt;
         a_or(&c->_c_waiters, 0x80000000);
         a_inc(&c->_c_seq);
         __wake(&c->_c_seq, -1, 0);
         while ((cnt = c->_c_waiters) & 0x7fffffff)
             __wait(&c->_c_waiters, 0, cnt, 0);
     }
     return 0;
 }
References __wait(), __wake(), a_inc, a_or, c, and cnt.
pthread_cond_init()
int pthread_cond_init (pthread_cond_t * __restrict, const pthread_condattr_t * __restrict)
Referenced by __aio_get_queue().
pthread_cond_signal()
int pthread_cond_signal (pthread_cond_t * c)
Definition at line 3 of file pthread_cond_signal.c.
 {
     if (!c->_c_shared) return __private_cond_signal(c, 1);
     if (!c->_c_waiters) return 0;
     a_inc(&c->_c_seq);
     __wake(&c->_c_seq, 1, 0);
     return 0;
 }
References __private_cond_signal(), __wake(), a_inc, and c.
pthread_cond_timedwait()
int pthread_cond_timedwait (pthread_cond_t * __restrict, pthread_mutex_t * __restrict, const struct timespec * __restrict)
Referenced by __pthread_cond_timedwait_time32(), and pthread_cond_wait().
pthread_cond_wait()
int pthread_cond_wait (pthread_cond_t * __restrict, pthread_mutex_t * __restrict)
Referenced by __libc_exit_fini(), do_init_fini(), and io_thread_func().
pthread_condattr_destroy()
int pthread_condattr_destroy (pthread_condattr_t * a)
Definition at line 3 of file pthread_condattr_destroy.c.
 {
     return 0;
 }
pthread_condattr_getclock()
int pthread_condattr_getclock (const pthread_condattr_t * __restrict, clockid_t * __restrict)
pthread_condattr_getpshared()
int pthread_condattr_getpshared (const pthread_condattr_t * __restrict, int * __restrict)
pthread_condattr_init()
int pthread_condattr_init (pthread_condattr_t * a)
Definition at line 3 of file pthread_condattr_init.c.
 {
     *a = (pthread_condattr_t){0};
     return 0;
 }
pthread_condattr_setclock()
int pthread_condattr_setclock (pthread_condattr_t * a, clockid_t clk)
Definition at line 3 of file pthread_condattr_setclock.c.
 {
     if (clk < 0 || clk-2U < 2) return EINVAL;
     a->__attr &= 0x80000000;
     a->__attr |= clk;
     return 0;
 }
References EINVAL.
pthread_condattr_setpshared()
int pthread_condattr_setpshared (pthread_condattr_t * a, int pshared)
Definition at line 3 of file pthread_condattr_setpshared.c.
 {
     if (pshared > 1U) return EINVAL;
     a->__attr &= 0x7fffffff;
     a->__attr |= (unsigned)pshared<<31;
     return 0;
 }
References EINVAL.
pthread_create()
int pthread_create (pthread_t * __restrict, const pthread_attr_t * __restrict, void * *)(void *, void * __restrict)
Referenced by lio_listio(), mq_notify(), and submit().
pthread_detach()
int pthread_detach (pthread_t)
Referenced by start().
pthread_equal()
int pthread_equal (pthread_t , pthread_t)
pthread_exit()
_Noreturn void pthread_exit (void *)
Referenced by __cancel(), and pthread_cancel().
pthread_getconcurrency()
int pthread_getconcurrency (void)
Definition at line 3 of file pthread_getconcurrency.c.
 {
     return 0;
 }
pthread_getcpuclockid()
int pthread_getcpuclockid (pthread_t t, clockid_t * clockid)
Definition at line 3 of file pthread_getcpuclockid.c.
 {
     *clockid = (-t->tid-1)*8U + 6;
     return 0;
 }
References t.
pthread_getschedparam()
int pthread_getschedparam (pthread_t , int * __restrict, struct sched_param * __restrict)
pthread_getspecific()
void* pthread_getspecific (pthread_key_t)
pthread_join()
int pthread_join (pthread_t , void **)
Referenced by mq_notify().
pthread_key_create()
int pthread_key_create (pthread_key_t * , void(*)(void *))
pthread_key_delete()
int pthread_key_delete (pthread_key_t)
pthread_mutex_consistent()
int pthread_mutex_consistent (pthread_mutex_t * m)
Definition at line 4 of file pthread_mutex_consistent.c.
 {
     int old = m->_m_lock;
     int own = old & 0x3fffffff;
     if (!(m->_m_type & 4) || !own || !(old & 0x40000000))
         return EINVAL;
     if (own != __pthread_self()->tid)
         return EPERM;
     a_and(&m->_m_lock, ~0x40000000);
     return 0;
 }
References __pthread_self, a_and, EINVAL, EPERM, and old.
pthread_mutex_destroy()
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 3 of file pthread_mutex_destroy.c.
 {
     /* If the mutex being destroyed is process-shared and has nontrivial
      * type (tracking ownership), it might be in the pending slot of a
      * robust_list; wait for quiescence. */
     if (mutex->_m_type > 128) __vm_wait();
     return 0;
 }
References __vm_wait().
pthread_mutex_getprioceiling()
int pthread_mutex_getprioceiling (const pthread_mutex_t * __restrict, int * __restrict)
pthread_mutex_init()
int pthread_mutex_init (pthread_mutex_t * __restrict, const pthread_mutexattr_t * __restrict)
Referenced by __aio_get_queue().
pthread_mutex_lock()
int pthread_mutex_lock (pthread_mutex_t *)
Referenced by __aio_get_queue(), __aio_unref_queue(), __ldso_atfork(), __libc_exit_fini(), __pthread_cond_timedwait(), cleanup(), dlopen(), do_init_fini(), io_thread_func(), and submit().
pthread_mutex_setprioceiling()
int pthread_mutex_setprioceiling (pthread_mutex_t * __restrict, int , int * __restrict)
pthread_mutex_timedlock()
int pthread_mutex_timedlock (pthread_mutex_t * __restrict, const struct timespec * __restrict)
Referenced by __pthread_mutex_timedlock_time32().
pthread_mutex_trylock()
int pthread_mutex_trylock (pthread_mutex_t *)
pthread_mutex_unlock()
int pthread_mutex_unlock (pthread_mutex_t *)
Referenced by __aio_unref_queue(), __ldso_atfork(), aio_cancel(), dlopen(), do_init_fini(), io_thread_func(), and submit().
pthread_mutexattr_destroy()
int pthread_mutexattr_destroy (pthread_mutexattr_t * a)
Definition at line 3 of file pthread_mutexattr_destroy.c.
 {
     return 0;
 }
pthread_mutexattr_getprioceiling()
int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_getprotocol()
int pthread_mutexattr_getprotocol (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_getpshared()
int pthread_mutexattr_getpshared (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_getrobust()
int pthread_mutexattr_getrobust (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_gettype()
int pthread_mutexattr_gettype (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_init()
int pthread_mutexattr_init (pthread_mutexattr_t * a)
Definition at line 3 of file pthread_mutexattr_init.c.
 {
     *a = (pthread_mutexattr_t){0};
     return 0;
 }
pthread_mutexattr_setprioceiling()
int pthread_mutexattr_setprioceiling (pthread_mutexattr_t * , int)
pthread_mutexattr_setprotocol()
int pthread_mutexattr_setprotocol (pthread_mutexattr_t * a, int protocol)
Definition at line 6 of file pthread_mutexattr_setprotocol.c.
 {
     int r;
     switch (protocol) {
     case PTHREAD_PRIO_NONE:
         a->__attr &= ~8;
         return 0;
     case PTHREAD_PRIO_INHERIT:
         r = check_pi_result;
         if (r < 0) {
             volatile int lk = 0;
             r = -__syscall(SYS_futex, &lk, FUTEX_LOCK_PI, 0, 0);
             a_store(&check_pi_result, r);
         }
         if (r) return r;
         a->__attr |= 8;
         return 0;
     case PTHREAD_PRIO_PROTECT:
         return ENOTSUP;
     default:
         return EINVAL;
     }
 }
References __syscall, a_store, check_pi_result, EINVAL, ENOTSUP, FUTEX_LOCK_PI, PTHREAD_PRIO_INHERIT, PTHREAD_PRIO_NONE, PTHREAD_PRIO_PROTECT, and SYS_futex.
pthread_mutexattr_setpshared()
int pthread_mutexattr_setpshared (pthread_mutexattr_t * a, int pshared)
Definition at line 3 of file pthread_mutexattr_setpshared.c.
 {
     if (pshared > 1U) return EINVAL;
     a->__attr &= ~128U;
     a->__attr |= pshared<<7;
     return 0;
 }
References EINVAL.
pthread_mutexattr_setrobust()
int pthread_mutexattr_setrobust (pthread_mutexattr_t * a, int robust)
Definition at line 6 of file pthread_mutexattr_setrobust.c.
 {
     if (robust > 1U) return EINVAL;
     if (robust) {
         int r = check_robust_result;
         if (r < 0) {
             void *p;
             size_t l;
             r = -__syscall(SYS_get_robust_list, 0, &p, &l);
             a_store(&check_robust_result, r);
         }
         if (r) return r;
         a->__attr |= 4;
         return 0;
     }
     a->__attr &= ~4;
     return 0;
 }
References __syscall, a_store, check_robust_result, EINVAL, l, and p.
pthread_mutexattr_settype()
int pthread_mutexattr_settype (pthread_mutexattr_t * a, int type)
Definition at line 3 of file pthread_mutexattr_settype.c.
 {
     if ((unsigned)type > 2) return EINVAL;
     a->__attr = (a->__attr & ~3) | type;
     return 0;
 }
References EINVAL, and type.
pthread_once()
int pthread_once (pthread_once_t * , void(*)(void))
pthread_rwlock_destroy()
int pthread_rwlock_destroy (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_destroy.c.
 {
     return 0;
 }
pthread_rwlock_init()
int pthread_rwlock_init (pthread_rwlock_t * __restrict, const pthread_rwlockattr_t * __restrict)
Referenced by __aio_atfork().
pthread_rwlock_rdlock()
int pthread_rwlock_rdlock (pthread_rwlock_t *)
Referenced by __acquire_ptc(), __aio_atfork(), __aio_get_queue(), __dlsym(), dl_iterate_phdr(), and dladdr().
pthread_rwlock_timedrdlock()
int pthread_rwlock_timedrdlock (pthread_rwlock_t * __restrict, const struct timespec * __restrict)
Referenced by __pthread_rwlock_timedrdlock_time32().
pthread_rwlock_timedwrlock()
int pthread_rwlock_timedwrlock (pthread_rwlock_t * __restrict, const struct timespec * __restrict)
Referenced by __pthread_rwlock_timedwrlock_time32().
pthread_rwlock_tryrdlock()
int pthread_rwlock_tryrdlock (pthread_rwlock_t *)
Referenced by __aio_atfork(), and __pthread_rwlock_timedrdlock().
pthread_rwlock_trywrlock()
int pthread_rwlock_trywrlock (pthread_rwlock_t *)
Referenced by __pthread_rwlock_timedwrlock().
pthread_rwlock_unlock()
int pthread_rwlock_unlock (pthread_rwlock_t *)
Referenced by __aio_atfork(), __aio_get_queue(), __aio_unref_queue(), __dlsym(), __ldso_atfork(), __libc_exit_fini(), __release_ptc(), dl_iterate_phdr(), dladdr(), and dlopen().
pthread_rwlock_wrlock()
int pthread_rwlock_wrlock (pthread_rwlock_t *)
Referenced by __aio_get_queue(), __aio_unref_queue(), __inhibit_ptc(), __ldso_atfork(), __libc_exit_fini(), and dlopen().
pthread_rwlockattr_destroy()
int pthread_rwlockattr_destroy (pthread_rwlockattr_t * a)
Definition at line 3 of file pthread_rwlockattr_destroy.c.
 {
     return 0;
 }
pthread_rwlockattr_getpshared()
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t * __restrict, int * __restrict)
pthread_rwlockattr_init()
int pthread_rwlockattr_init (pthread_rwlockattr_t * a)
Definition at line 3 of file pthread_rwlockattr_init.c.
 {
     *a = (pthread_rwlockattr_t){0};
     return 0;
 }
pthread_rwlockattr_setpshared()
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t * a, int pshared)
Definition at line 3 of file pthread_rwlockattr_setpshared.c.
 {
     if (pshared > 1U) return EINVAL;
     a->__attr[0] = pshared;
     return 0;
 }
References EINVAL.
pthread_self()
pthread_t pthread_self (void)
Referenced by pthread_cancel(), pthread_getname_np(), pthread_setname_np(), and start().
pthread_setcancelstate()
int pthread_setcancelstate (int , int *)
Referenced by __getgr_a(), __getgrent_a(), __getpw_a(), __getpwent_a(), __lookup_name(), __res_msend_rc(), __synccall(), __vsyslog(), closelog(), dlopen(), fgetspent(), fmtmsg(), forkpty(), getaddrinfo(), getdate(), getentropy(), getgr_r(), getpw_r(), getspnam_r(), if_nameindex(), mq_notify(), nftw(), openlog(), openpty(), posix_spawn(), pthread_getname_np(), pthread_setname_np(), sem_open(), shm_open(), and wordexp().
pthread_setcanceltype()
int pthread_setcanceltype (int new, int * old)
Definition at line 3 of file pthread_setcanceltype.c.
 {
     struct pthread *self = __pthread_self();
     if (new > 1U) return EINVAL;
     if (old) *old = self->cancelasync;
     self->cancelasync = new;
     if (new) pthread_testcancel();
     return 0;
 }
References __pthread_self, EINVAL, old, and pthread_testcancel().
pthread_setconcurrency()
int pthread_setconcurrency (int val)
Definition at line 4 of file pthread_setconcurrency.c.
 {
     if (val < 0) return EINVAL;
     if (val > 0) return EAGAIN;
     return 0;
 }
References EAGAIN, EINVAL, and val.
pthread_setschedparam()
int pthread_setschedparam (pthread_t t, int policy, const struct sched_param * param)
Definition at line 4 of file pthread_setschedparam.c.
 {
     int r;
     sigset_t set;
     __block_app_sigs(&set);
     LOCK(t->killlock);
     r = !t->tid ? ESRCH : -__syscall(SYS_sched_setscheduler, t->tid, policy, param);
     UNLOCK(t->killlock);
     __restore_sigs(&set);
     return r;
 }
References __block_app_sigs(), __restore_sigs(), __syscall, ESRCH, LOCK, param, t, and UNLOCK.
pthread_setschedprio()
int pthread_setschedprio (pthread_t t, int prio)
Definition at line 4 of file pthread_setschedprio.c.
 {
     int r;
     sigset_t set;
     __block_app_sigs(&set);
     LOCK(t->killlock);
     r = !t->tid ? ESRCH : -__syscall(SYS_sched_setparam, t->tid, &prio);
     UNLOCK(t->killlock);
     __restore_sigs(&set);
     return r;
 }
References __block_app_sigs(), __restore_sigs(), __syscall, ESRCH, LOCK, t, and UNLOCK.
pthread_setspecific()
int pthread_setspecific (pthread_key_t k, const void * x)
Definition at line 3 of file pthread_setspecific.c.
 {
     struct pthread *self = __pthread_self();
     /* Avoid unnecessary COW */
     if (self->tsd[k] != x) {
         self->tsd[k] = (void *)x;
         self->tsd_used = 1;
     }
     return 0;
 }
References __pthread_self, k, pthread::self, pthread::tsd, and x.
pthread_spin_destroy()
int pthread_spin_destroy (pthread_spinlock_t * s)
Definition at line 3 of file pthread_spin_destroy.c.
 {
     return 0;
 }
pthread_spin_init()
int pthread_spin_init (pthread_spinlock_t * s, int shared)
Definition at line 3 of file pthread_spin_init.c.
 {
     return *s = 0;
 }
References s.
pthread_spin_lock()
int pthread_spin_lock (pthread_spinlock_t * s)
Definition at line 4 of file pthread_spin_lock.c.
 {
     while (*(volatile int *)s || a_cas(s, 0, EBUSY)) a_spin();
     return 0;
 }
References a_cas, a_spin, EBUSY, and s.
pthread_spin_trylock()
int pthread_spin_trylock (pthread_spinlock_t * s)
Definition at line 4 of file pthread_spin_trylock.c.
 {
     return a_cas(s, 0, EBUSY);
 }
References a_cas, EBUSY, and s.
pthread_spin_unlock()
int pthread_spin_unlock (pthread_spinlock_t * s)
Definition at line 3 of file pthread_spin_unlock.c.
 {
     a_store(s, 0);
     return 0;
 }
References a_store, and s.
pthread_testcancel()
void pthread_testcancel (void)
Referenced by aio_suspend(), pthread_setcanceltype(), sem_timedwait(), and system().