Fennix: Userspace/apps/base/busybox/util-linux/fsck_minix.c File Reference
fsck_minix.c File Reference
#include <mntent.h>
#include "libbb.h"
#include "minix.h"
Data Structures
struct BUG_bad_inode_size
struct globals
union globals.u
Macros
#define BLKGETSIZE _IO(0x12,96) /* return device size */
#define G (*ptr_to_globals)
#define changed (G.changed)
#define errors_uncorrected (G.errors_uncorrected)
#define termios_set (G.termios_set)
#define dirsize (G.dirsize)
#define namelen (G.namelen)
#define device_name (G.device_name)
#define directory (G.directory)
#define regular (G.regular)
#define blockdev (G.blockdev)
#define chardev (G.chardev)
#define links (G.links)
#define symlinks (G.symlinks)
#define total (G.total)
#define inode_buffer (G.inode_buffer)
#define inode_map (G.inode_map)
#define zone_map (G.zone_map)
#define inode_count (G.inode_count)
#define zone_count (G.zone_count)
#define name_depth (G.name_depth)
#define name_component (G.name_component)
#define sv_termios (G.sv_termios)
#define superblock_buffer (G.u.superblock_buffer)
#define add_zone_ind_blk (G.add_zone_ind_blk)
#define add_zone_dind_blk (G.add_zone_dind_blk)
#define add_zone_tind_blk (G.add_zone_tind_blk)
#define check_file_blk (G.check_file_blk)
#define current_name (G.current_name)
#define INIT_G()
#define OPTION_STR "larvsmf"
#define OPT_list (option_mask32 & OPT_l)
#define OPT_automatic (option_mask32 & OPT_a)
#define OPT_repair (option_mask32 & OPT_r)
#define OPT_verbose (option_mask32 & OPT_v)
#define OPT_show (option_mask32 & OPT_s)
#define OPT_warn_mode (option_mask32 & OPT_w)
#define OPT_force (option_mask32 & OPT_f)
#define OPT_manual ((option_mask32 & (OPT_a|OPT_r)) == OPT_r)
#define Inode1 (((struct minix1_inode *) inode_buffer)-1)
#define Inode2 (((struct minix2_inode *) inode_buffer)-1)
#define Super (G.u.Super)
#define ZONES ((unsigned)(Super.s_nzones))
#define INODES ((unsigned)Super.s_ninodes)
#define IMAPS ((unsigned)Super.s_imap_blocks)
#define ZMAPS ((unsigned)Super.s_zmap_blocks)
#define FIRSTZONE ((unsigned)Super.s_firstdatazone)
#define ZONESIZE ((unsigned)Super.s_log_zone_size)
#define MAXSIZE ((unsigned)Super.s_max_size)
#define MAGIC (Super.s_magic)
#define INODE_BLOCKS div_roundup(INODES, MINIX1_INODES_PER_BLOCK)
#define INODE_BUFFER_SIZE (INODE_BLOCKS * BLOCK_SIZE)
#define NORM_FIRSTZONE (2 + IMAPS + ZMAPS + INODE_BLOCKS)
#define zone_in_use(x) (minix_bit(zone_map,(x)-FIRSTZONE+1))
#define inode_in_use(x) (minix_bit(inode_map,(x)))
#define mark_inode(x) (minix_setbit(inode_map,(x)))
#define unmark_inode(x) (minix_clrbit(inode_map,(x)))
#define mark_zone(x) (minix_setbit(zone_map,(x)-FIRSTZONE+1))
#define unmark_zone(x) (minix_clrbit(zone_map,(x)-FIRSTZONE+1))
Enumerations
enum { MINIX_NAME_MAX = 255 }
enum { version2 = 0 }
enum { MAX_DEPTH = 32 }
enum { dev_fd = 3 }
enum {
OPT_l = (1 << 0) , OPT_a = (1 << 1) , OPT_r = (1 << 2) , OPT_v = (1 << 3) ,
OPT_s = (1 << 4) , OPT_w = (1 << 5) , OPT_f = (1 << 6)
}
Functions
static ALWAYS_INLINE unsigned div_roundup (unsigned size, unsigned n)
static int minix_bit (const char *a, unsigned i)
static void minix_setbit (char *a, unsigned i)
static void minix_clrbit (char *a, unsigned i)
static void recursive_check (unsigned ino)
static void die (const char *str) NORETURN
static void push_filename (const char *name)
static void pop_filename (void)
static int ask (const char *string, int def)
static void check_mount (void)
static int check_zone_nr2 (uint32_t *nr, smallint *corrected)
static int check_zone_nr (uint16_t *nr, smallint *corrected)
static void read_block (unsigned nr, void *addr)
static void write_block (unsigned nr, void *addr)
static int map_block (struct minix1_inode *inode, unsigned blknr)
static void write_superblock (void)
static void write_tables (void)
static void get_dirsize (void)
static void read_superblock (void)
static void read_tables (void)
static void get_inode_common (unsigned nr, uint16_t i_mode)
static struct minix1_inode * get_inode (unsigned nr)
static void check_root (void)
void check_root2 (void)
static int add_zone_common (int block, smallint *corrected)
static int add_zone (uint16_t *znr, smallint *corrected)
static void add_zone_ind (uint16_t *znr, smallint *corrected)
static void add_zone_dind (uint16_t *znr, smallint *corrected)
static void check_zones (unsigned i)
static void check_file (struct minix1_inode *dir, unsigned offset)
static int bad_zone (int i)
static void check_counts (void)
static void check (void)
void check2 (void)
int fsck_minix_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
BUG_bad_inode_size
struct BUG_bad_inode_size
Definition at line 123 of file fsck_minix.c.
Data Fields
char BUG_bad_inode1_size[(INODE_SIZE1 *MINIX1_INODES_PER_BLOCK !=BLOCK_SIZE) ? -1 :1]
globals.u
union globals.u
Definition at line 144 of file mkfs_minix.c.
Data Fields
struct minix_superblock SB
struct minix_superblock Super
char superblock_buffer[BLOCK_SIZE]
char superblock_buffer[BLOCK_SIZE]
Macro Definition Documentation
add_zone_dind_blk
#define add_zone_dind_blk (G.add_zone_dind_blk)
Definition at line 215 of file fsck_minix.c.
add_zone_ind_blk
#define add_zone_ind_blk (G.add_zone_ind_blk)
Definition at line 214 of file fsck_minix.c.
add_zone_tind_blk
#define add_zone_tind_blk (G.add_zone_tind_blk)
Definition at line 216 of file fsck_minix.c.
BLKGETSIZE
#define BLKGETSIZE _IO(0x12,96) /* return device size */
Definition at line 120 of file fsck_minix.c.
blockdev
#define blockdev (G.blockdev)
Definition at line 200 of file fsck_minix.c.
changed
#define changed (G.changed)
Definition at line 192 of file fsck_minix.c.
chardev
#define chardev (G.chardev)
Definition at line 201 of file fsck_minix.c.
check_file_blk
#define check_file_blk (G.check_file_blk)
Definition at line 217 of file fsck_minix.c.
current_name
#define current_name (G.current_name)
Definition at line 218 of file fsck_minix.c.
device_name
#define device_name (G.device_name)
Definition at line 197 of file fsck_minix.c.
directory
#define directory (G.directory)
Definition at line 198 of file fsck_minix.c.
dirsize
#define dirsize (G.dirsize)
Definition at line 195 of file fsck_minix.c.
errors_uncorrected
#define errors_uncorrected (G.errors_uncorrected)
Definition at line 193 of file fsck_minix.c.
FIRSTZONE
#define FIRSTZONE ((unsigned)Super.s_firstdatazone)
Definition at line 263 of file fsck_minix.c.
G
#define G (*ptr_to_globals)
Definition at line 188 of file fsck_minix.c.
IMAPS
#define IMAPS ((unsigned)Super.s_imap_blocks)
Definition at line 261 of file fsck_minix.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    dirsize = 16; \
    namelen = 14; \
    current_name[0] = '/'; \
    /*current_name[1] = '\0';*/ \
    name_component[0] = &current_name[0]; \
} while (0)
Definition at line 219 of file fsck_minix.c.
Inode1
#define Inode1 (((struct minix1_inode *) inode_buffer)-1)
Definition at line 250 of file fsck_minix.c.
Inode2
#define Inode2 (((struct minix2_inode *) inode_buffer)-1)
Definition at line 251 of file fsck_minix.c.
INODE_BLOCKS
#define INODE_BLOCKS div_roundup(INODES, MINIX1_INODES_PER_BLOCK)
Definition at line 275 of file fsck_minix.c.
inode_buffer
#define inode_buffer (G.inode_buffer)
Definition at line 205 of file fsck_minix.c.
INODE_BUFFER_SIZE
#define INODE_BUFFER_SIZE (INODE_BLOCKS * BLOCK_SIZE)
Definition at line 281 of file fsck_minix.c.
inode_count
#define inode_count (G.inode_count)
Definition at line 208 of file fsck_minix.c.
inode_in_use
#define inode_in_use (x) (minix_bit(inode_map,(x)))
Definition at line 305 of file fsck_minix.c.
inode_map
#define inode_map (G.inode_map)
Definition at line 206 of file fsck_minix.c.
INODES
#define INODES ((unsigned)Super.s_ninodes)
Definition at line 260 of file fsck_minix.c.
links
#define links (G.links)
Definition at line 202 of file fsck_minix.c.
MAGIC
#define MAGIC (Super.s_magic)
Definition at line 266 of file fsck_minix.c.
mark_inode
#define mark_inode (x) (minix_setbit(inode_map,(x)))
Definition at line 307 of file fsck_minix.c.
mark_zone
#define mark_zone (x) (minix_setbit(zone_map,(x)-FIRSTZONE+1))
Definition at line 310 of file fsck_minix.c.
MAXSIZE
#define MAXSIZE ((unsigned)Super.s_max_size)
Definition at line 265 of file fsck_minix.c.
name_component
#define name_component (G.name_component)
Definition at line 211 of file fsck_minix.c.
name_depth
#define name_depth (G.name_depth)
Definition at line 210 of file fsck_minix.c.
namelen
#define namelen (G.namelen)
Definition at line 196 of file fsck_minix.c.
NORM_FIRSTZONE
#define NORM_FIRSTZONE (2 + IMAPS + ZMAPS + INODE_BLOCKS)
Definition at line 282 of file fsck_minix.c.
OPT_automatic
#define OPT_automatic (option_mask32 & OPT_a)
Definition at line 240 of file fsck_minix.c.
OPT_force
#define OPT_force (option_mask32 & OPT_f)
Definition at line 245 of file fsck_minix.c.
OPT_list
#define OPT_list (option_mask32 & OPT_l)
Definition at line 239 of file fsck_minix.c.
OPT_manual
#define OPT_manual ((option_mask32 & (OPT_a|OPT_r)) == OPT_r)
Definition at line 247 of file fsck_minix.c.
OPT_repair
#define OPT_repair (option_mask32 & OPT_r)
Definition at line 241 of file fsck_minix.c.
OPT_show
#define OPT_show (option_mask32 & OPT_s)
Definition at line 243 of file fsck_minix.c.
OPT_verbose
#define OPT_verbose (option_mask32 & OPT_v)
Definition at line 242 of file fsck_minix.c.
OPT_warn_mode
#define OPT_warn_mode (option_mask32 & OPT_w)
Definition at line 244 of file fsck_minix.c.
OPTION_STR
#define OPTION_STR "larvsmf"
Definition at line 229 of file fsck_minix.c.
regular
#define regular (G.regular)
Definition at line 199 of file fsck_minix.c.
Super
#define Super (G.u.Super)
Definition at line 253 of file fsck_minix.c.
superblock_buffer
#define superblock_buffer (G.u.superblock_buffer)
Definition at line 213 of file fsck_minix.c.
sv_termios
#define sv_termios (G.sv_termios)
Definition at line 212 of file fsck_minix.c.
symlinks
#define symlinks (G.symlinks)
Definition at line 203 of file fsck_minix.c.
termios_set
#define termios_set (G.termios_set)
Definition at line 194 of file fsck_minix.c.
total
#define total (G.total)
Definition at line 204 of file fsck_minix.c.
unmark_inode
#define unmark_inode (x) (minix_clrbit(inode_map,(x)))
Definition at line 308 of file fsck_minix.c.
unmark_zone
#define unmark_zone (x) (minix_clrbit(zone_map,(x)-FIRSTZONE+1))
Definition at line 311 of file fsck_minix.c.
ZMAPS
#define ZMAPS ((unsigned)Super.s_zmap_blocks)
Definition at line 262 of file fsck_minix.c.
zone_count
#define zone_count (G.zone_count)
Definition at line 209 of file fsck_minix.c.
zone_in_use
#define zone_in_use (x) (minix_bit(zone_map,(x)-FIRSTZONE+1))
Definition at line 304 of file fsck_minix.c.
zone_map
#define zone_map (G.zone_map)
Definition at line 207 of file fsck_minix.c.
ZONES
#define ZONES ((unsigned)(Super.s_nzones))
Definition at line 258 of file fsck_minix.c.
ZONESIZE
#define ZONESIZE ((unsigned)Super.s_log_zone_size)
Definition at line 264 of file fsck_minix.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MINIX_NAME_MAX
Definition at line 130 of file fsck_minix.c.
      {
 #ifdef UNUSED
     MINIX1_LINK_MAX = 250,
     MINIX2_LINK_MAX = 65530,
     MINIX_I_MAP_SLOTS = 8,
     MINIX_Z_MAP_SLOTS = 64,
     MINIX_V1 = 0x0001,      /* original minix fs */
     MINIX_V2 = 0x0002,      /* minix V2 fs */
 #endif
     MINIX_NAME_MAX = 255,         /* # chars in a file name */
 };
anonymous enum
anonymous enum
Enumerator
version2
Definition at line 144 of file fsck_minix.c.
 { version2 = 0 };
anonymous enum
anonymous enum
Enumerator
MAX_DEPTH
Definition at line 147 of file fsck_minix.c.
 { MAX_DEPTH = 32 };
anonymous enum
anonymous enum
Enumerator
dev_fd
Definition at line 149 of file fsck_minix.c.
 { dev_fd = 3 };
anonymous enum
anonymous enum
Enumerator
OPT_l
OPT_a
OPT_r
OPT_v
OPT_s
OPT_w
OPT_f
Definition at line 230 of file fsck_minix.c.
      {
     OPT_l = (1 << 0),
     OPT_a = (1 << 1),
     OPT_r = (1 << 2),
     OPT_v = (1 << 3),
     OPT_s = (1 << 4),
     OPT_w = (1 << 5),
     OPT_f = (1 << 6),
 };
Function Documentation
add_zone()
static int add_zone (uint16_t * znr, smallint * corrected) static
Definition at line 807 of file fsck_minix.c.
 {
     int block;
     block = check_zone_nr(znr, corrected);
     block = add_zone_common(block, corrected);
     if (block == -1) {
         *znr = 0;
         block = 0;
     }
     return block;
 }
References add_zone_common(), and check_zone_nr().
Referenced by add_zone_dind(), add_zone_ind(), and check_zones().
add_zone_common()
static int add_zone_common (int block, smallint * corrected) static
Definition at line 783 of file fsck_minix.c.
 {
     if (!block)
         return 0;
     if (zone_count[block]) {
         printf("Already used block is reused in file '%s'. ",
                 current_name);
         if (ask("Clear", 1)) {
             block = 0;
             *corrected = 1;
             return -1; /* "please zero out *znr" */
         }
     }
     if (!zone_in_use(block)) {
         printf("Block %d in file '%s' is marked as 'unused'. ",
                 block, current_name);
         if (ask("Correct", 1))
             mark_zone(block);
     }
     if (!++zone_count[block])
         zone_count[block]--;
     return block;
 }
References ask(), current_name, mark_zone, printf, zone_count, and zone_in_use.
Referenced by add_zone().
add_zone_dind()
static void add_zone_dind (uint16_t * znr, smallint * corrected) static
Definition at line 869 of file fsck_minix.c.
 {
     int i;
     int block;
     smallint chg_blk = 0;
     block = add_zone(znr, corrected);
     if (!block)
         return;
     read_block(block, add_zone_dind_blk);
     for (i = 0; i < (BLOCK_SIZE >> 1); i++)
         add_zone_ind(i + (uint16_t *) add_zone_dind_blk, &chg_blk);
     if (chg_blk)
         write_block(block, add_zone_dind_blk);
 }
References add_zone(), add_zone_dind_blk, add_zone_ind(), BLOCK_SIZE, i, read_block(), and write_block().
Referenced by check_zones().
add_zone_ind()
static void add_zone_ind (uint16_t * znr, smallint * corrected) static
Definition at line 835 of file fsck_minix.c.
 {
     int i;
     int block;
     smallint chg_blk = 0;
     block = add_zone(znr, corrected);
     if (!block)
         return;
     read_block(block, add_zone_ind_blk);
     for (i = 0; i < (BLOCK_SIZE >> 1); i++)
         add_zone(i + (uint16_t *) add_zone_ind_blk, &chg_blk);
     if (chg_blk)
         write_block(block, add_zone_ind_blk);
 }
References add_zone(), add_zone_ind_blk, BLOCK_SIZE, i, read_block(), and write_block().
Referenced by add_zone_dind(), and check_zones().
ask()
static int ask (const char * string, int def) static
Definition at line 354 of file fsck_minix.c.
 {
     int c;
     if (!OPT_repair) {
         bb_putchar('\n');
         errors_uncorrected = 1;
         return 0;
     }
     if (OPT_automatic) {
         bb_putchar('\n');
         if (!def)
             errors_uncorrected = 1;
         return def;
     }
     printf(def ? "%s (y/n)? " : "%s (n/y)? ", string);
     for (;;) {
         fflush_all();
         c = getchar();
         if (c == EOF) {
             if (!def)
                 errors_uncorrected = 1;
             return def;
         }
         if (c == '\n')
             break;
         c |= 0x20; /* tolower */
         if (c == 'y') {
             def = 1;
             break;
         }
         if (c == 'n') {
             def = 0;
             break;
         }
     }
     if (def)
         puts("y");
     else {
         puts("n");
         errors_uncorrected = 1;
     }
     return def;
 }
References bb_putchar(), c, EOF, errors_uncorrected, fflush_all(), getchar, OPT_automatic, OPT_repair, printf, and puts().
Referenced by add_zone_common(), check_counts(), check_file(), check_mount(), check_zone_nr2(), and get_inode_common().
bad_zone()
static int bad_zone (int i) static
Definition at line 1095 of file fsck_minix.c.
 {
     char buffer[BLOCK_SIZE];
     xlseek(dev_fd, BLOCK_SIZE * i, SEEK_SET);
     return (BLOCK_SIZE != full_read(dev_fd, buffer, BLOCK_SIZE));
 }
References BLOCK_SIZE, dev_fd, full_read(), i, SEEK_SET, and xlseek().
Referenced by check_counts().
check()
static void check (void) static
Definition at line 1207 of file fsck_minix.c.
 {
     memset(inode_count, 0, (INODES + 1) * sizeof(*inode_count));
     memset(zone_count, 0, ZONES * sizeof(*zone_count));
     check_zones(MINIX_ROOT_INO);
     recursive_check(MINIX_ROOT_INO);
     check_counts();
 }
References check_counts(), check_zones(), inode_count, INODES, memset, MINIX_ROOT_INO, recursive_check(), zone_count, and ZONES.
Referenced by fsck_minix_main().
check2()
void check2 (void)
Referenced by fsck_minix_main().
check_counts()
static void check_counts (void) static
Definition at line 1103 of file fsck_minix.c.
 {
     int i;
     for (i = 1; i <= INODES; i++) {
         if (OPT_warn_mode && Inode1[i].i_mode && !inode_in_use(i)) {
             printf("Inode %d has non-zero mode. ", i);
             if (ask("Clear", 1)) {
                 Inode1[i].i_mode = 0;
                 changed = 1;
             }
         }
         if (!inode_count[i]) {
             if (!inode_in_use(i))
                 continue;
             printf("Unused inode %d is marked as 'used' in the bitmap. ", i);
             if (ask("Clear", 1))
                 unmark_inode(i);
             continue;
         }
         if (!inode_in_use(i)) {
             printf("Inode %d is used, but marked as 'unused' in the bitmap. ", i);
             if (ask("Set", 1))
                 mark_inode(i);
         }
         if (Inode1[i].i_nlinks != inode_count[i]) {
             printf("Inode %d (mode=%07o), i_nlinks=%d, counted=%d. ",
                 i, Inode1[i].i_mode, Inode1[i].i_nlinks,
                 inode_count[i]);
             if (ask("Set i_nlinks to count", 1)) {
                 Inode1[i].i_nlinks = inode_count[i];
                 changed = 1;
             }
         }
     }
     for (i = FIRSTZONE; i < ZONES; i++) {
         if ((zone_in_use(i) != 0) == zone_count[i])
             continue;
         if (!zone_count[i]) {
             if (bad_zone(i))
                 continue;
             printf("Zone %d is marked 'in use', but no file uses it. ", i);
             if (ask("Unmark", 1))
                 unmark_zone(i);
             continue;
         }
         printf("Zone %d: %sin use, counted=%d\n",
             i, zone_in_use(i) ? "" : "not ", zone_count[i]);
     }
 }
References ask(), bad_zone(), changed, FIRSTZONE, i, minix2_inode::i_mode, minix2_inode::i_nlinks, Inode1, inode_count, inode_in_use, INODES, mark_inode, OPT_warn_mode, printf, unmark_inode, unmark_zone, zone_count, zone_in_use, and ZONES.
Referenced by check().
check_file()
static void check_file (struct minix1_inode * dir, unsigned offset) static
Definition at line 961 of file fsck_minix.c.
 {
     struct minix1_inode *inode;
     int ino;
     char *name;
     int block;
     block = map_block(dir, offset / BLOCK_SIZE);
     read_block(block, check_file_blk);
     name = check_file_blk + (offset % BLOCK_SIZE) + 2;
     ino = *(uint16_t *) (name - 2);
     if (ino > INODES) {
         printf("%s contains a bad inode number for file '%.*s'. ",
                 current_name, namelen, name);
         if (ask("Remove", 1)) {
             *(uint16_t *) (name - 2) = 0;
             write_block(block, check_file_blk);
         }
         ino = 0;
     }
     push_filename(name);
     inode = get_inode(ino);
     pop_filename();
     if (!offset) {
         if (inode && LONE_CHAR(name, '.'))
             return;
         printf("%s: bad directory: '.' isn't first\n", current_name);
         errors_uncorrected = 1;
     }
     if (offset == dirsize) {
         if (inode && strcmp("..", name) == 0)
             return;
         printf("%s: bad directory: '..' isn't second\n", current_name);
         errors_uncorrected = 1;
     }
     if (!inode)
         return;
     push_filename(name);
     if (OPT_list) {
         if (OPT_verbose)
             printf("%6d %07o %3d ", ino, inode->i_mode, inode->i_nlinks);
         printf("%s%s\n", current_name, S_ISDIR(inode->i_mode) ? ":" : "");
     }
     check_zones(ino);
     if (inode && S_ISDIR(inode->i_mode))
         recursive_check(ino);
     pop_filename();
 }
References ask(), BLOCK_SIZE, check_file_blk, check_zones(), current_name, dir, dirsize, errors_uncorrected, get_inode(), minix1_inode::i_mode, minix1_inode::i_nlinks, INODES, LONE_CHAR, map_block(), namelen, offset, OPT_list, OPT_verbose, pop_filename(), printf, push_filename(), read_block(), recursive_check(), S_ISDIR, strcmp, and write_block().
Referenced by recursive_check(), and unzip_main().
check_mount()
static void check_mount (void) static
Definition at line 404 of file fsck_minix.c.
 {
     if (find_mount_point(device_name, 0)) {
         int cont;
 #if ENABLE_FEATURE_MTAB_SUPPORT
         /*
          * If the root is mounted read-only, then /etc/mtab is
          * probably not correct; so we won't issue a warning based on
          * it.
          */
         int fd = open(bb_path_mtab_file, O_RDWR);
         if (fd < 0 && errno == EROFS)
             return;
         close(fd);
 #endif
         printf("%s is mounted. ", device_name);
         cont = 0;
         if (isatty(0) && isatty(1))
             cont = ask("Do you really want to continue", 0);
         if (!cont) {
             puts("Check aborted");
             exit_SUCCESS();
         }
     }
 }
References ask(), bb_path_mtab_file, close(), device_name, EROFS, errno, exit_SUCCESS(), fd, find_mount_point(), isatty(), O_RDWR, open(), printf, and puts().
Referenced by fsck_minix_main().
check_root()
static void check_root (void) static
Definition at line 763 of file fsck_minix.c.
 {
     struct minix1_inode *inode = Inode1 + MINIX_ROOT_INO;
     if (!inode || !S_ISDIR(inode->i_mode))
         die("root inode isn't a directory");
 }
References die(), minix1_inode::i_mode, Inode1, MINIX_ROOT_INO, and S_ISDIR.
Referenced by fsck_minix_main().
check_root2()
void check_root2 (void)
Referenced by fsck_minix_main().
check_zone_nr()
static int check_zone_nr (uint16_t * nr, smallint * corrected) static
Definition at line 456 of file fsck_minix.c.
 {
     uint32_t nr32 = *nr;
     int r = check_zone_nr2(&nr32, corrected);
     *nr = (uint16_t)nr32;
     return r;
 }
References check_zone_nr2().
Referenced by add_zone(), and map_block().
check_zone_nr2()
static int check_zone_nr2 (uint32_t * nr, smallint * corrected) static
Definition at line 437 of file fsck_minix.c.
 {
     const char *msg;
     if (!*nr)
         return 0;
     if (*nr < FIRSTZONE)
         msg = "< FIRSTZONE";
     else if (*nr >= ZONES)
         msg = ">= ZONES";
     else
         return *nr;
     printf("Zone nr %s in file '%s'. ", msg, current_name);
     if (ask("Remove block", 1)) {
         *nr = 0;
         *corrected = 1;
     }
     return 0;
 }
References ask(), current_name, FIRSTZONE, printf, and ZONES.
Referenced by check_zone_nr().
check_zones()
static void check_zones (unsigned i) static
Definition at line 919 of file fsck_minix.c.
 {
     struct minix1_inode *inode;
     if (!i || i > INODES)
         return;
     if (inode_count[i] > 1)     /* have we counted this file already? */
         return;
     inode = Inode1 + i;
     if (!S_ISDIR(inode->i_mode)
      && !S_ISREG(inode->i_mode)
      && !S_ISLNK(inode->i_mode)
     ) {
         return;
     }
     for (i = 0; i < 7; i++)
         add_zone(i + inode->i_zone, &changed);
     add_zone_ind(7 + inode->i_zone, &changed);
     add_zone_dind(8 + inode->i_zone, &changed);
 }
References add_zone(), add_zone_dind(), add_zone_ind(), changed, i, minix1_inode::i_mode, minix1_inode::i_zone, Inode1, inode_count, INODES, S_ISDIR, S_ISLNK, and S_ISREG.
Referenced by check(), and check_file().
die()
static void die (const char * str) static
Definition at line 320 of file fsck_minix.c.
 {
     if (termios_set)
         tcsetattr_stdin_TCSANOW(&sv_termios);
     bb_simple_error_msg_and_die(str);
 }
References bb_simple_error_msg_and_die(), str, sv_termios, tcsetattr_stdin_TCSANOW(), and termios_set.
Referenced by check_root(), fsck_minix_main(), read_superblock(), read_tables(), recursive_check(), write_superblock(), and write_tables().
div_roundup()
static ALWAYS_INLINE unsigned div_roundup (unsigned size, unsigned n) static
Definition at line 269 of file fsck_minix.c.
 {
     return (size + n-1) / n;
 }
References n, and size.
fsck_minix_main()
int fsck_minix_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1230 of file fsck_minix.c.
 {
     int retcode = 0;
     xfunc_error_retval = 8;
     INIT_G();
     getopt32(argv, "^" OPTION_STR "\0" "=1:ar" /* one arg; -a assumes -r */);
     argv += optind;
     device_name = argv[0];
     check_mount();  /* trying to check a mounted filesystem? */
     if (OPT_manual) {
         if (!isatty(0) || !isatty(1))
             die("need terminal for interactive repairs");
     }
     xmove_fd(xopen(device_name, OPT_repair ? O_RDWR : O_RDONLY), dev_fd);
     /*sync(); paranoia? */
     read_superblock();
     /*
      * Determine whether or not we should continue with the checking.
      * This is based on the status of the filesystem valid and error
      * flags and whether or not the -f switch was specified on the
      * command line.
      */
     printf("%s: %s\n", applet_name, bb_banner);
     if (!(Super.s_state & MINIX_ERROR_FS)
      && (Super.s_state & MINIX_VALID_FS) && !OPT_force
     ) {
         if (OPT_repair)
             printf("%s is clean, check is skipped\n", device_name);
         return 0;
     } else if (OPT_force)
         printf("Forcing filesystem check on %s\n", device_name);
     else if (OPT_repair)
         printf("Filesystem on %s is dirty, needs checking\n",
             device_name);
     read_tables();
     if (OPT_manual) {
         set_termios_to_raw(STDIN_FILENO, &sv_termios, 0);
         termios_set = 1;
     }
     if (version2) {
         check_root2();
         check2();
     } else {
         check_root();
         check();
     }
     if (OPT_verbose) {
         int i, free_cnt;
         for (i = 1, free_cnt = 0; i <= INODES; i++)
             if (!inode_in_use(i))
                 free_cnt++;
         printf("\n%6u inodes used (%u%%)\n", (INODES - free_cnt),
             100 * (INODES - free_cnt) / INODES);
         for (i = FIRSTZONE, free_cnt = 0; i < ZONES; i++)
             if (!zone_in_use(i))
                 free_cnt++;
         printf("%6u zones used (%u%%)\n\n"
             "%6u regular files\n"
             "%6u directories\n"
             "%6u character device files\n"
             "%6u block device files\n"
             "%6u links\n"
             "%6u symbolic links\n"
             "------\n"
             "%6u files\n",
             (ZONES - free_cnt), 100 * (ZONES - free_cnt) / ZONES,
             regular, directory, chardev, blockdev,
             links - 2 * directory + 1, symlinks,
             total - 2 * directory + 1);
     }
     if (changed) {
         write_tables();
         puts("FILE SYSTEM HAS BEEN CHANGED");
         sync();
     } else if (OPT_repair)
         write_superblock();
     if (OPT_manual)
         tcsetattr_stdin_TCSANOW(&sv_termios);
     if (changed)
         retcode += 3;
     if (errors_uncorrected)
         retcode += 4;
     return retcode;
 }
References applet_name, argv, blockdev, changed, chardev, check(), check2(), check_mount(), check_root(), check_root2(), dev_fd, device_name, die(), directory, errors_uncorrected, FIRSTZONE, getopt32(), i, INIT_G, inode_in_use, INODES, isatty(), links, MINIX_ERROR_FS, MINIX_VALID_FS, O_RDONLY, O_RDWR, OPT_force, OPT_manual, OPT_repair, OPT_verbose, optind, OPTION_STR, printf, puts(), read_superblock(), read_tables(), regular, set_termios_to_raw(), STDIN_FILENO, Super, sv_termios, symlinks, sync(), tcsetattr_stdin_TCSANOW(), termios_set, total, version2, write_superblock(), write_tables(), xfunc_error_retval, xmove_fd(), xopen(), zone_in_use, and ZONES.
get_dirsize()
static void get_dirsize (void) static
Definition at line 610 of file fsck_minix.c.
 {
     int block;
     char blk[BLOCK_SIZE];
     int size;
 #if ENABLE_FEATURE_MINIX2
     if (version2)
         block = Inode2[MINIX_ROOT_INO].i_zone[0];
     else
 #endif
         block = Inode1[MINIX_ROOT_INO].i_zone[0];
     read_block(block, blk);
     for (size = 16; size < BLOCK_SIZE; size <<= 1) {
         if (strcmp(blk + size + 2, "..") == 0) {
             dirsize = size;
             namelen = size - 2;
             return;
         }
     }
     /* use defaults */
 }
References BLOCK_SIZE, dirsize, Inode1, Inode2, MINIX_ROOT_INO, namelen, read_block(), size, strcmp, and version2.
Referenced by read_tables().
get_inode()
static struct minix1_inode* get_inode (unsigned nr) static
Definition at line 739 of file fsck_minix.c.
 {
     struct minix1_inode *inode;
     if (!nr || nr > INODES)
         return NULL;
     inode = Inode1 + nr;
     get_inode_common(nr, inode->i_mode);
     return inode;
 }
References get_inode_common(), minix1_inode::i_mode, Inode1, INODES, and NULL.
Referenced by check_file().
get_inode_common()
static void get_inode_common (unsigned nr, uint16_t i_mode) static
Definition at line 701 of file fsck_minix.c.
 {
     total++;
     if (!inode_count[nr]) {
         if (!inode_in_use(nr)) {
             printf("Inode %u is marked as 'unused', but it is used "
                     "for file '%s'\n", nr, current_name);
             if (OPT_repair) {
                 if (ask("Mark as 'in use'", 1))
                     mark_inode(nr);
                 else
                     errors_uncorrected = 1;
             }
         }
         if (S_ISDIR(i_mode))
             directory++;
         else if (S_ISREG(i_mode))
             regular++;
         else if (S_ISCHR(i_mode))
             chardev++;
         else if (S_ISBLK(i_mode))
             blockdev++;
         else if (S_ISLNK(i_mode))
             symlinks++;
         else if (S_ISSOCK(i_mode));
         else if (S_ISFIFO(i_mode));
         else {
             printf("%s has mode %05o\n", current_name, i_mode);
         }
     } else
         links++;
     if (!++inode_count[nr]) {
         puts("Warning: inode count too big");
         inode_count[nr]--;
         errors_uncorrected = 1;
     }
 }
References ask(), blockdev, chardev, current_name, directory, errors_uncorrected, inode_count, inode_in_use, links, mark_inode, OPT_repair, printf, puts(), regular, S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISLNK, S_ISREG, S_ISSOCK, symlinks, and total.
Referenced by get_inode().
map_block()
static int map_block (struct minix1_inode * inode, unsigned blknr) static
Definition at line 508 of file fsck_minix.c.
 {
     uint16_t ind[BLOCK_SIZE >> 1];
     int block, result;
     smallint blk_chg;
     if (blknr < 7)
         return check_zone_nr(inode->i_zone + blknr, &changed);
     blknr -= 7;
     if (blknr < 512) {
         block = check_zone_nr(inode->i_zone + 7, &changed);
         goto common;
     }
     blknr -= 512;
     block = check_zone_nr(inode->i_zone + 8, &changed);
     read_block(block, ind); /* double indirect */
     blk_chg = 0;
     result = check_zone_nr(&ind[blknr / 512], &blk_chg);
     if (blk_chg)
         write_block(block, ind);
     block = result;
  common:
     read_block(block, ind);
     blk_chg = 0;
     result = check_zone_nr(&ind[blknr % 512], &blk_chg);
     if (blk_chg)
         write_block(block, ind);
     return result;
 }
References BLOCK_SIZE, changed, check_zone_nr(), common(), minix1_inode::i_zone, read_block(), and write_block().
Referenced by check_file().
minix_bit()
static int minix_bit (const char * a, unsigned i) static
Definition at line 287 of file fsck_minix.c.
 {
     return (a[i >> 3] & (1<<(i & 7)));
 }
References i.
minix_clrbit()
static void minix_clrbit (char * a, unsigned i) static
Definition at line 297 of file fsck_minix.c.
 {
     clrbit(a, i);
     changed = 1;
 }
References changed, clrbit, and i.
minix_setbit()
static void minix_setbit (char * a, unsigned i) static
Definition at line 292 of file fsck_minix.c.
 {
     setbit(a, i);
     changed = 1;
 }
References changed, i, and setbit.
pop_filename()
static void pop_filename (void) static
Definition at line 342 of file fsck_minix.c.
 {
     name_depth--;
     if (name_depth < MAX_DEPTH) {
         *name_component[name_depth] = '\0';
         if (!name_depth) {
             current_name[0] = '/';
             current_name[1] = '\0';
         }
     }
 }
References current_name, MAX_DEPTH, name_component, and name_depth.
Referenced by check_file().
push_filename()
static void push_filename (const char * name) static
Definition at line 327 of file fsck_minix.c.
 {
     //  /dir/dir/dir/file
     //  ^   ^   ^
     // [0] [1] [2] <-name_component[i]
     if (name_depth < MAX_DEPTH) {
         int len;
         char *p = name_component[name_depth];
         *p++ = '/';
         len = sprintf(p, "%.*s", namelen, name);
         name_component[name_depth + 1] = p + len;
     }
     name_depth++;
 }
References len, MAX_DEPTH, name_component, name_depth, namelen, p, and sprintf().
Referenced by check_file().
read_block()
static void read_block (unsigned nr, void * addr) static
Definition at line 467 of file fsck_minix.c.
 {
     if (!nr) {
         memset(addr, 0, BLOCK_SIZE);
         return;
     }
     xlseek(dev_fd, BLOCK_SIZE * nr, SEEK_SET);
     if (BLOCK_SIZE != full_read(dev_fd, addr, BLOCK_SIZE)) {
         printf("%s: bad block %u in file '%s'\n",
                 bb_msg_read_error, nr, current_name);
         errors_uncorrected = 1;
         memset(addr, 0, BLOCK_SIZE);
     }
 }
References addr, bb_msg_read_error, BLOCK_SIZE, current_name, dev_fd, errors_uncorrected, full_read(), memset, printf, SEEK_SET, and xlseek().
Referenced by add_zone_dind(), add_zone_ind(), check_file(), get_dirsize(), and map_block().
read_superblock()
static void read_superblock (void) static
Definition at line 633 of file fsck_minix.c.
 {
     xlseek(dev_fd, BLOCK_SIZE, SEEK_SET);
     if (BLOCK_SIZE != full_read(dev_fd, superblock_buffer, BLOCK_SIZE))
         die("can't read superblock");
     /* already initialized to:
     namelen = 14;
     dirsize = 16;
     version2 = 0;
     */
     if (MAGIC == MINIX1_SUPER_MAGIC) {
     } else if (MAGIC == MINIX1_SUPER_MAGIC2) {
         namelen = 30;
         dirsize = 32;
 #if ENABLE_FEATURE_MINIX2
     } else if (MAGIC == MINIX2_SUPER_MAGIC) {
         version2 = 1;
     } else if (MAGIC == MINIX2_SUPER_MAGIC2) {
         namelen = 30;
         dirsize = 32;
         version2 = 1;
 #endif
     } else
         die("bad magic number in superblock");
     if (ZONESIZE != 0 || BLOCK_SIZE != 1024)
         die("only 1k blocks/zones supported");
     if (IMAPS * BLOCK_SIZE * 8 < INODES + 1)
         die("bad s_imap_blocks field in superblock");
     if (ZMAPS * BLOCK_SIZE * 8 < ZONES - FIRSTZONE + 1)
         die("bad s_zmap_blocks field in superblock");
 }
References BLOCK_SIZE, dev_fd, die(), dirsize, FIRSTZONE, full_read(), IMAPS, INODES, MAGIC, MINIX1_SUPER_MAGIC, MINIX1_SUPER_MAGIC2, MINIX2_SUPER_MAGIC, MINIX2_SUPER_MAGIC2, namelen, SEEK_SET, superblock_buffer, version2, xlseek(), ZMAPS, ZONES, and ZONESIZE.
Referenced by fsck_minix_main().
read_tables()
static void read_tables (void) static
Definition at line 665 of file fsck_minix.c.
 {
     inode_map = xzalloc(IMAPS * BLOCK_SIZE);
     zone_map = xzalloc(ZMAPS * BLOCK_SIZE);
     inode_buffer = xmalloc(INODE_BUFFER_SIZE);
     inode_count = xmalloc(INODES + 1);
     zone_count = xmalloc(ZONES);
     if (IMAPS * BLOCK_SIZE != read(dev_fd, inode_map, IMAPS * BLOCK_SIZE))
         die("can't read inode map");
     if (ZMAPS * BLOCK_SIZE != read(dev_fd, zone_map, ZMAPS * BLOCK_SIZE))
         die("can't read zone map");
     if (INODE_BUFFER_SIZE != read(dev_fd, inode_buffer, INODE_BUFFER_SIZE))
         die("can't read inodes");
     if (NORM_FIRSTZONE != FIRSTZONE) {
         puts("warning: firstzone!=norm_firstzone");
         errors_uncorrected = 1;
     }
     get_dirsize();
     if (OPT_show) {
         printf("%u inodes\n"
             "%u blocks\n"
             "Firstdatazone=%u (%u)\n"
             "Zonesize=%u\n"
             "Maxsize=%u\n"
             "Filesystem state=%u\n"
             "namelen=%u\n\n",
             INODES,
             ZONES,
             FIRSTZONE, NORM_FIRSTZONE,
             BLOCK_SIZE << ZONESIZE,
             MAXSIZE,
             Super.s_state,
             namelen);
     }
 }
References BLOCK_SIZE, dev_fd, die(), errors_uncorrected, FIRSTZONE, get_dirsize(), IMAPS, inode_buffer, INODE_BUFFER_SIZE, inode_count, inode_map, INODES, MAXSIZE, namelen, NORM_FIRSTZONE, OPT_show, printf, puts(), read(), Super, xmalloc, xzalloc(), ZMAPS, zone_count, zone_map, ZONES, and ZONESIZE.
Referenced by fsck_minix_main().
recursive_check()
static void recursive_check (unsigned ino) static
Definition at line 1061 of file fsck_minix.c.
 {
     struct minix1_inode *dir;
     unsigned offset;
     dir = Inode1 + ino;
     if (!S_ISDIR(dir->i_mode))
         die("internal error");
     if (dir->i_size < 2 * dirsize) {
         printf("%s: bad directory: size<32", current_name);
         errors_uncorrected = 1;
     }
     for (offset = 0; offset < dir->i_size; offset += dirsize)
         check_file(dir, offset);
 }
References check_file(), current_name, die(), dir, dirsize, errors_uncorrected, Inode1, offset, printf, and S_ISDIR.
Referenced by check(), and check_file().
write_block()
static void write_block (unsigned nr, void * addr) static
Definition at line 485 of file fsck_minix.c.
 {
     if (!nr)
         return;
     if (nr < FIRSTZONE || nr >= ZONES) {
         puts("Internal error: trying to write bad block\n"
             "Write request ignored");
         errors_uncorrected = 1;
         return;
     }
     xlseek(dev_fd, BLOCK_SIZE * nr, SEEK_SET);
     if (BLOCK_SIZE != full_write(dev_fd, addr, BLOCK_SIZE)) {
         printf("%s: bad block %u in file '%s'\n",
                 bb_msg_write_error, nr, current_name);
         errors_uncorrected = 1;
     }
 }
References addr, bb_msg_write_error, BLOCK_SIZE, current_name, dev_fd, errors_uncorrected, full_write(), printf, puts(), SEEK_SET, xlseek(), and ZONES.
Referenced by add_zone_dind(), add_zone_ind(), check_file(), and map_block().
write_superblock()
static void write_superblock (void) static
Definition at line 582 of file fsck_minix.c.
 {
     /*
      * Set the state of the filesystem based on whether or not there
      * are uncorrected errors.  The filesystem valid flag is
      * unconditionally set if we get this far.
      */
     Super.s_state |= MINIX_VALID_FS | MINIX_ERROR_FS;
     if (!errors_uncorrected)
         Super.s_state &= ~MINIX_ERROR_FS;
     xlseek(dev_fd, BLOCK_SIZE, SEEK_SET);
     if (BLOCK_SIZE != full_write(dev_fd, superblock_buffer, BLOCK_SIZE))
         die("can't write superblock");
 }
References BLOCK_SIZE, dev_fd, die(), errors_uncorrected, full_write(), MINIX_ERROR_FS, MINIX_VALID_FS, SEEK_SET, Super, superblock_buffer, and xlseek().
Referenced by fsck_minix_main(), and write_tables().
write_tables()
static void write_tables (void) static
Definition at line 598 of file fsck_minix.c.
 {
     write_superblock();
     if (IMAPS * BLOCK_SIZE != write(dev_fd, inode_map, IMAPS * BLOCK_SIZE))
         die("can't write inode map");
     if (ZMAPS * BLOCK_SIZE != write(dev_fd, zone_map, ZMAPS * BLOCK_SIZE))
         die("can't write zone map");
     if (INODE_BUFFER_SIZE != write(dev_fd, inode_buffer, INODE_BUFFER_SIZE))
         die("can't write inodes");
 }
References BLOCK_SIZE, dev_fd, die(), IMAPS, inode_buffer, INODE_BUFFER_SIZE, inode_map, write(), write_superblock(), ZMAPS, and zone_map.
Referenced by fsck_minix_main().