Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/w_checksum.h File Reference
w_checksum.h File Reference
#include "doomtype.h"
Functions
void W_Checksum (sha1_digest_t digest)
Function Documentation
W_Checksum()
void W_Checksum (sha1_digest_t digest)
Definition at line 68 of file w_checksum.c.
 {
     sha1_context_t sha1_context;
     unsigned int i;
     SHA1_Init(&sha1_context);
     num_open_wadfiles = 0;
     // Go through each entry in the WAD directory, adding information
     // about each entry to the SHA1 hash.
     for (i=0; i<numlumps; ++i)
     {
         ChecksumAddLump(&sha1_context, &lumpinfo[i]);
     }
     SHA1_Final(digest, &sha1_context);
 }
References ChecksumAddLump(), i, lumpinfo, num_open_wadfiles, numlumps, SHA1_Final(), and SHA1_Init().
Referenced by InitConnectData().