Fennix: Userspace/mlibc/tests/posix/rlimits.c File Reference
rlimits.c File Reference
#include <sys/resource.h>
#include <stdio.h>
#include <errno.h>
#include <assert.h>
#include <string.h>
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 7 of file rlimits.c.
            {
     struct rlimit getlim, setlim;
     setlim.rlim_cur = 16;
     setlim.rlim_max = 4096;
     int ret = setrlimit(RLIMIT_NOFILE, &setlim);
     if(ret == -1) {
         fprintf(stderr, "%s\n", strerror(errno));
         assert(!ret);
     }
     assert(!getrlimit(RLIMIT_NOFILE, &getlim));
     assert(setlim.rlim_cur == getlim.rlim_cur);
     assert(setlim.rlim_max == getlim.rlim_max);
     return 0;
 }
References assert, errno, fprintf(), getrlimit(), ret, rlimit::rlim_cur, rlimit::rlim_max, RLIMIT_NOFILE, setrlimit(), stderr, and strerror().