Fennix Userspace: Userspace/mlibc/options/ansi/musl-generic-math/exp.c File Reference
exp.c File Reference
#include "libm.h"
Functions
double exp (double x)
Variables
static const double half [2] = {0.5,-0.5}
static const double ln2hi = 6.93147180369123816490e-01
static const double ln2lo = 1.90821492927058770002e-10
static const double invln2 = 1.44269504088896338700e+00
static const double P1 = 1.66666666666666019037e-01
static const double P2 = -2.77777777770155933842e-03
static const double P3 = 6.61375632143793436117e-05
static const double P4 = -1.65339022054652515390e-06
static const double P5 = 4.13813679705723846039e-08
Function Documentation
exp()
double exp (double x)
Definition at line 81 of file exp.c.
 {
     double_t hi, lo, c, xx, y;
     int k, sign;
     uint32_t hx;
     GET_HIGH_WORD(hx, x);
     sign = hx>>31;
     hx &= 0x7fffffff;  /* high word of |x| */
     /* special cases */
     if (hx >= 0x4086232b) {  /* if |x| >= 708.39... */
         if (isnan(x))
             return x;
         if (x > 709.782712893383973096) {
             /* overflow if x!=inf */
             x *= 0x1p1023;
             return x;
         }
         if (x < -708.39641853226410622) {
             /* underflow if x!=-inf */
             FORCE_EVAL((float)(-0x1p-149/x));
             if (x < -745.13321910194110842)
                 return 0;
         }
     }
     /* argument reduction */
     if (hx > 0x3fd62e42) {  /* if |x| > 0.5 ln2 */
         if (hx >= 0x3ff0a2b2)  /* if |x| >= 1.5 ln2 */
             k = (int)(invln2*x + half[sign]);
         else
             k = 1 - sign - sign;
         hi = x - k*ln2hi;  /* k*ln2hi is exact here */
         lo = k*ln2lo;
         x = hi - lo;
     } else if (hx > 0x3e300000)  {  /* if |x| > 2**-28 */
         k = 0;
         hi = x;
         lo = 0;
     } else {
         /* inexact if x!=0 */
         FORCE_EVAL(0x1p1023 + x);
         return 1 + x;
     }
     /* x is now in primary range */
     xx = x*x;
     c = x - xx*(P1+xx*(P2+xx*(P3+xx*(P4+xx*P5))));
     y = 1 + (x*c/(2-c) - lo + hi);
     if (k == 0)
         return y;
     return scalbn(y, k);
 }
References c, FORCE_EVAL, GET_HIGH_WORD, half, int, invln2, isnan, k, ln2hi, ln2lo, P1, P2, P3, P4, P5, scalbn(), x, and y.
Referenced by __expo2(), __mlibc_cchsh(), cexp(), cosh(), cpow(), erfc2(), and tgamma().
Variable Documentation
half
const double half[2] = {0.5,-0.5} static
Definition at line 71 of file exp.c.
Referenced by exp().
invln2
const double invln2 = 1.44269504088896338700e+00 static
Definition at line 74 of file exp.c.
Referenced by exp().
ln2hi
const double ln2hi = 6.93147180369123816490e-01 static
Definition at line 72 of file exp.c.
Referenced by exp().
ln2lo
const double ln2lo = 1.90821492927058770002e-10 static
Definition at line 73 of file exp.c.
Referenced by exp().
P1
const double P1 = 1.66666666666666019037e-01 static
Definition at line 75 of file exp.c.
Referenced by exp().
P2
const double P2 = -2.77777777770155933842e-03 static
Definition at line 76 of file exp.c.
Referenced by exp().
P3
const double P3 = 6.61375632143793436117e-05 static
Definition at line 77 of file exp.c.
Referenced by exp().
P4
const double P4 = -1.65339022054652515390e-06 static
Definition at line 78 of file exp.c.
Referenced by exp().
P5
const double P5 = 4.13813679705723846039e-08 static
Definition at line 79 of file exp.c.
Referenced by exp().