Fennix Userspace: Userspace/musl/include/sys/prctl.h File Reference
prctl.h File Reference
#include <stdint.h>
Data Structures
struct prctl_mm_map
Macros
#define PR_SET_PDEATHSIG 1
#define PR_GET_PDEATHSIG 2
#define PR_GET_DUMPABLE 3
#define PR_SET_DUMPABLE 4
#define PR_GET_UNALIGN 5
#define PR_SET_UNALIGN 6
#define PR_UNALIGN_NOPRINT 1
#define PR_UNALIGN_SIGBUS 2
#define PR_GET_KEEPCAPS 7
#define PR_SET_KEEPCAPS 8
#define PR_GET_FPEMU 9
#define PR_SET_FPEMU 10
#define PR_FPEMU_NOPRINT 1
#define PR_FPEMU_SIGFPE 2
#define PR_GET_FPEXC 11
#define PR_SET_FPEXC 12
#define PR_FP_EXC_SW_ENABLE 0x80
#define PR_FP_EXC_DIV 0x010000
#define PR_FP_EXC_OVF 0x020000
#define PR_FP_EXC_UND 0x040000
#define PR_FP_EXC_RES 0x080000
#define PR_FP_EXC_INV 0x100000
#define PR_FP_EXC_DISABLED 0
#define PR_FP_EXC_NONRECOV 1
#define PR_FP_EXC_ASYNC 2
#define PR_FP_EXC_PRECISE 3
#define PR_GET_TIMING 13
#define PR_SET_TIMING 14
#define PR_TIMING_STATISTICAL 0
#define PR_TIMING_TIMESTAMP 1
#define PR_SET_NAME 15
#define PR_GET_NAME 16
#define PR_GET_ENDIAN 19
#define PR_SET_ENDIAN 20
#define PR_ENDIAN_BIG 0
#define PR_ENDIAN_LITTLE 1
#define PR_ENDIAN_PPC_LITTLE 2
#define PR_GET_SECCOMP 21
#define PR_SET_SECCOMP 22
#define PR_CAPBSET_READ 23
#define PR_CAPBSET_DROP 24
#define PR_GET_TSC 25
#define PR_SET_TSC 26
#define PR_TSC_ENABLE 1
#define PR_TSC_SIGSEGV 2
#define PR_GET_SECUREBITS 27
#define PR_SET_SECUREBITS 28
#define PR_SET_TIMERSLACK 29
#define PR_GET_TIMERSLACK 30
#define PR_TASK_PERF_EVENTS_DISABLE 31
#define PR_TASK_PERF_EVENTS_ENABLE 32
#define PR_MCE_KILL 33
#define PR_MCE_KILL_CLEAR 0
#define PR_MCE_KILL_SET 1
#define PR_MCE_KILL_LATE 0
#define PR_MCE_KILL_EARLY 1
#define PR_MCE_KILL_DEFAULT 2
#define PR_MCE_KILL_GET 34
#define PR_SET_MM 35
#define PR_SET_MM_START_CODE 1
#define PR_SET_MM_END_CODE 2
#define PR_SET_MM_START_DATA 3
#define PR_SET_MM_END_DATA 4
#define PR_SET_MM_START_STACK 5
#define PR_SET_MM_START_BRK 6
#define PR_SET_MM_BRK 7
#define PR_SET_MM_ARG_START 8
#define PR_SET_MM_ARG_END 9
#define PR_SET_MM_ENV_START 10
#define PR_SET_MM_ENV_END 11
#define PR_SET_MM_AUXV 12
#define PR_SET_MM_EXE_FILE 13
#define PR_SET_MM_MAP 14
#define PR_SET_MM_MAP_SIZE 15
#define PR_SET_PTRACER 0x59616d61
#define PR_SET_PTRACER_ANY (-1UL)
#define PR_SET_CHILD_SUBREAPER 36
#define PR_GET_CHILD_SUBREAPER 37
#define PR_SET_NO_NEW_PRIVS 38
#define PR_GET_NO_NEW_PRIVS 39
#define PR_GET_TID_ADDRESS 40
#define PR_SET_THP_DISABLE 41
#define PR_GET_THP_DISABLE 42
#define PR_MPX_ENABLE_MANAGEMENT 43
#define PR_MPX_DISABLE_MANAGEMENT 44
#define PR_SET_FP_MODE 45
#define PR_GET_FP_MODE 46
#define PR_FP_MODE_FR (1 << 0)
#define PR_FP_MODE_FRE (1 << 1)
#define PR_CAP_AMBIENT 47
#define PR_CAP_AMBIENT_IS_SET 1
#define PR_CAP_AMBIENT_RAISE 2
#define PR_CAP_AMBIENT_LOWER 3
#define PR_CAP_AMBIENT_CLEAR_ALL 4
#define PR_SVE_SET_VL 50
#define PR_SVE_SET_VL_ONEXEC (1 << 18)
#define PR_SVE_GET_VL 51
#define PR_SVE_VL_LEN_MASK 0xffff
#define PR_SVE_VL_INHERIT (1 << 17)
#define PR_GET_SPECULATION_CTRL 52
#define PR_SET_SPECULATION_CTRL 53
#define PR_SPEC_STORE_BYPASS 0
#define PR_SPEC_INDIRECT_BRANCH 1
#define PR_SPEC_NOT_AFFECTED 0
#define PR_SPEC_PRCTL (1UL << 0)
#define PR_SPEC_ENABLE (1UL << 1)
#define PR_SPEC_DISABLE (1UL << 2)
#define PR_SPEC_FORCE_DISABLE (1UL << 3)
#define PR_SPEC_DISABLE_NOEXEC (1UL << 4)
#define PR_PAC_RESET_KEYS 54
#define PR_PAC_APIAKEY (1UL << 0)
#define PR_PAC_APIBKEY (1UL << 1)
#define PR_PAC_APDAKEY (1UL << 2)
#define PR_PAC_APDBKEY (1UL << 3)
#define PR_PAC_APGAKEY (1UL << 4)
#define PR_SET_TAGGED_ADDR_CTRL 55
#define PR_GET_TAGGED_ADDR_CTRL 56
#define PR_TAGGED_ADDR_ENABLE (1UL << 0)
#define PR_MTE_TCF_SHIFT 1
#define PR_MTE_TCF_NONE (0UL << 1)
#define PR_MTE_TCF_SYNC (1UL << 1)
#define PR_MTE_TCF_ASYNC (2UL << 1)
#define PR_MTE_TCF_MASK (3UL << 1)
#define PR_MTE_TAG_SHIFT 3
#define PR_MTE_TAG_MASK (0xffffUL << 3)
#define PR_SET_IO_FLUSHER 57
#define PR_GET_IO_FLUSHER 58
#define PR_SET_SYSCALL_USER_DISPATCH 59
#define PR_SYS_DISPATCH_OFF 0
#define PR_SYS_DISPATCH_ON 1
#define SYSCALL_DISPATCH_FILTER_ALLOW 0
#define SYSCALL_DISPATCH_FILTER_BLOCK 1
#define PR_PAC_SET_ENABLED_KEYS 60
#define PR_PAC_GET_ENABLED_KEYS 61
Functions
int prctl (int,...)
Data Structure Documentation
prctl_mm_map
struct prctl_mm_map
Definition at line 88 of file prctl.h.
Data Fields
uint64_t arg_end
uint64_t arg_start
uint64_t * auxv
uint32_t auxv_size
uint64_t brk
uint64_t end_code
uint64_t end_data
uint64_t env_end
uint64_t env_start
uint32_t exe_fd
uint64_t start_brk
uint64_t start_code
uint64_t start_data
uint64_t start_stack
Macro Definition Documentation
PR_CAP_AMBIENT
#define PR_CAP_AMBIENT 47
Definition at line 127 of file prctl.h.
PR_CAP_AMBIENT_CLEAR_ALL
#define PR_CAP_AMBIENT_CLEAR_ALL 4
Definition at line 131 of file prctl.h.
PR_CAP_AMBIENT_IS_SET
#define PR_CAP_AMBIENT_IS_SET 1
Definition at line 128 of file prctl.h.
PR_CAP_AMBIENT_LOWER
#define PR_CAP_AMBIENT_LOWER 3
Definition at line 130 of file prctl.h.
PR_CAP_AMBIENT_RAISE
#define PR_CAP_AMBIENT_RAISE 2
Definition at line 129 of file prctl.h.
PR_CAPBSET_DROP
#define PR_CAPBSET_DROP 24
Definition at line 50 of file prctl.h.
PR_CAPBSET_READ
#define PR_CAPBSET_READ 23
Definition at line 49 of file prctl.h.
PR_ENDIAN_BIG
#define PR_ENDIAN_BIG 0
Definition at line 44 of file prctl.h.
PR_ENDIAN_LITTLE
#define PR_ENDIAN_LITTLE 1
Definition at line 45 of file prctl.h.
PR_ENDIAN_PPC_LITTLE
#define PR_ENDIAN_PPC_LITTLE 2
Definition at line 46 of file prctl.h.
PR_FP_EXC_ASYNC
#define PR_FP_EXC_ASYNC 2
Definition at line 34 of file prctl.h.
PR_FP_EXC_DISABLED
#define PR_FP_EXC_DISABLED 0
Definition at line 32 of file prctl.h.
PR_FP_EXC_DIV
#define PR_FP_EXC_DIV 0x010000
Definition at line 27 of file prctl.h.
PR_FP_EXC_INV
#define PR_FP_EXC_INV 0x100000
Definition at line 31 of file prctl.h.
PR_FP_EXC_NONRECOV
#define PR_FP_EXC_NONRECOV 1
Definition at line 33 of file prctl.h.
PR_FP_EXC_OVF
#define PR_FP_EXC_OVF 0x020000
Definition at line 28 of file prctl.h.
PR_FP_EXC_PRECISE
#define PR_FP_EXC_PRECISE 3
Definition at line 35 of file prctl.h.
PR_FP_EXC_RES
#define PR_FP_EXC_RES 0x080000
Definition at line 30 of file prctl.h.
PR_FP_EXC_SW_ENABLE
#define PR_FP_EXC_SW_ENABLE 0x80
Definition at line 26 of file prctl.h.
PR_FP_EXC_UND
#define PR_FP_EXC_UND 0x040000
Definition at line 29 of file prctl.h.
PR_FP_MODE_FR
#define PR_FP_MODE_FR (1 << 0)
Definition at line 124 of file prctl.h.
PR_FP_MODE_FRE
#define PR_FP_MODE_FRE (1 << 1)
Definition at line 125 of file prctl.h.
PR_FPEMU_NOPRINT
#define PR_FPEMU_NOPRINT 1
Definition at line 22 of file prctl.h.
PR_FPEMU_SIGFPE
#define PR_FPEMU_SIGFPE 2
Definition at line 23 of file prctl.h.
PR_GET_CHILD_SUBREAPER
#define PR_GET_CHILD_SUBREAPER 37
Definition at line 109 of file prctl.h.
PR_GET_DUMPABLE
#define PR_GET_DUMPABLE 3
Definition at line 12 of file prctl.h.
PR_GET_ENDIAN
#define PR_GET_ENDIAN 19
Definition at line 42 of file prctl.h.
PR_GET_FP_MODE
#define PR_GET_FP_MODE 46
Definition at line 123 of file prctl.h.
PR_GET_FPEMU
#define PR_GET_FPEMU 9
Definition at line 20 of file prctl.h.
PR_GET_FPEXC
#define PR_GET_FPEXC 11
Definition at line 24 of file prctl.h.
PR_GET_IO_FLUSHER
#define PR_GET_IO_FLUSHER 58
Definition at line 169 of file prctl.h.
PR_GET_KEEPCAPS
#define PR_GET_KEEPCAPS 7
Definition at line 18 of file prctl.h.
PR_GET_NAME
#define PR_GET_NAME 16
Definition at line 41 of file prctl.h.
PR_GET_NO_NEW_PRIVS
#define PR_GET_NO_NEW_PRIVS 39
Definition at line 112 of file prctl.h.
PR_GET_PDEATHSIG
#define PR_GET_PDEATHSIG 2
Definition at line 11 of file prctl.h.
PR_GET_SECCOMP
#define PR_GET_SECCOMP 21
Definition at line 47 of file prctl.h.
PR_GET_SECUREBITS
#define PR_GET_SECUREBITS 27
Definition at line 55 of file prctl.h.
PR_GET_SPECULATION_CTRL
#define PR_GET_SPECULATION_CTRL 52
Definition at line 139 of file prctl.h.
PR_GET_TAGGED_ADDR_CTRL
#define PR_GET_TAGGED_ADDR_CTRL 56
Definition at line 158 of file prctl.h.
PR_GET_THP_DISABLE
#define PR_GET_THP_DISABLE 42
Definition at line 117 of file prctl.h.
PR_GET_TID_ADDRESS
#define PR_GET_TID_ADDRESS 40
Definition at line 114 of file prctl.h.
PR_GET_TIMERSLACK
#define PR_GET_TIMERSLACK 30
Definition at line 58 of file prctl.h.
PR_GET_TIMING
#define PR_GET_TIMING 13
Definition at line 36 of file prctl.h.
PR_GET_TSC
#define PR_GET_TSC 25
Definition at line 51 of file prctl.h.
PR_GET_UNALIGN
#define PR_GET_UNALIGN 5
Definition at line 14 of file prctl.h.
PR_MCE_KILL
#define PR_MCE_KILL 33
Definition at line 63 of file prctl.h.
PR_MCE_KILL_CLEAR
#define PR_MCE_KILL_CLEAR 0
Definition at line 64 of file prctl.h.
PR_MCE_KILL_DEFAULT
#define PR_MCE_KILL_DEFAULT 2
Definition at line 68 of file prctl.h.
PR_MCE_KILL_EARLY
#define PR_MCE_KILL_EARLY 1
Definition at line 67 of file prctl.h.
PR_MCE_KILL_GET
#define PR_MCE_KILL_GET 34
Definition at line 69 of file prctl.h.
PR_MCE_KILL_LATE
#define PR_MCE_KILL_LATE 0
Definition at line 66 of file prctl.h.
PR_MCE_KILL_SET
#define PR_MCE_KILL_SET 1
Definition at line 65 of file prctl.h.
PR_MPX_DISABLE_MANAGEMENT
#define PR_MPX_DISABLE_MANAGEMENT 44
Definition at line 120 of file prctl.h.
PR_MPX_ENABLE_MANAGEMENT
#define PR_MPX_ENABLE_MANAGEMENT 43
Definition at line 119 of file prctl.h.
PR_MTE_TAG_MASK
#define PR_MTE_TAG_MASK (0xffffUL << 3)
Definition at line 166 of file prctl.h.
PR_MTE_TAG_SHIFT
#define PR_MTE_TAG_SHIFT 3
Definition at line 165 of file prctl.h.
PR_MTE_TCF_ASYNC
#define PR_MTE_TCF_ASYNC (2UL << 1)
Definition at line 163 of file prctl.h.
PR_MTE_TCF_MASK
#define PR_MTE_TCF_MASK (3UL << 1)
Definition at line 164 of file prctl.h.
PR_MTE_TCF_NONE
#define PR_MTE_TCF_NONE (0UL << 1)
Definition at line 161 of file prctl.h.
PR_MTE_TCF_SHIFT
#define PR_MTE_TCF_SHIFT 1
Definition at line 160 of file prctl.h.
PR_MTE_TCF_SYNC
#define PR_MTE_TCF_SYNC (1UL << 1)
Definition at line 162 of file prctl.h.
PR_PAC_APDAKEY
#define PR_PAC_APDAKEY (1UL << 2)
Definition at line 153 of file prctl.h.
PR_PAC_APDBKEY
#define PR_PAC_APDBKEY (1UL << 3)
Definition at line 154 of file prctl.h.
PR_PAC_APGAKEY
#define PR_PAC_APGAKEY (1UL << 4)
Definition at line 155 of file prctl.h.
PR_PAC_APIAKEY
#define PR_PAC_APIAKEY (1UL << 0)
Definition at line 151 of file prctl.h.
PR_PAC_APIBKEY
#define PR_PAC_APIBKEY (1UL << 1)
Definition at line 152 of file prctl.h.
PR_PAC_GET_ENABLED_KEYS
#define PR_PAC_GET_ENABLED_KEYS 61
Definition at line 178 of file prctl.h.
PR_PAC_RESET_KEYS
#define PR_PAC_RESET_KEYS 54
Definition at line 150 of file prctl.h.
PR_PAC_SET_ENABLED_KEYS
#define PR_PAC_SET_ENABLED_KEYS 60
Definition at line 177 of file prctl.h.
PR_SET_CHILD_SUBREAPER
#define PR_SET_CHILD_SUBREAPER 36
Definition at line 108 of file prctl.h.
PR_SET_DUMPABLE
#define PR_SET_DUMPABLE 4
Definition at line 13 of file prctl.h.
PR_SET_ENDIAN
#define PR_SET_ENDIAN 20
Definition at line 43 of file prctl.h.
PR_SET_FP_MODE
#define PR_SET_FP_MODE 45
Definition at line 122 of file prctl.h.
PR_SET_FPEMU
#define PR_SET_FPEMU 10
Definition at line 21 of file prctl.h.
PR_SET_FPEXC
#define PR_SET_FPEXC 12
Definition at line 25 of file prctl.h.
PR_SET_IO_FLUSHER
#define PR_SET_IO_FLUSHER 57
Definition at line 168 of file prctl.h.
PR_SET_KEEPCAPS
#define PR_SET_KEEPCAPS 8
Definition at line 19 of file prctl.h.
PR_SET_MM
#define PR_SET_MM 35
Definition at line 71 of file prctl.h.
PR_SET_MM_ARG_END
#define PR_SET_MM_ARG_END 9
Definition at line 80 of file prctl.h.
PR_SET_MM_ARG_START
#define PR_SET_MM_ARG_START 8
Definition at line 79 of file prctl.h.
PR_SET_MM_AUXV
#define PR_SET_MM_AUXV 12
Definition at line 83 of file prctl.h.
PR_SET_MM_BRK
#define PR_SET_MM_BRK 7
Definition at line 78 of file prctl.h.
PR_SET_MM_END_CODE
#define PR_SET_MM_END_CODE 2
Definition at line 73 of file prctl.h.
PR_SET_MM_END_DATA
#define PR_SET_MM_END_DATA 4
Definition at line 75 of file prctl.h.
PR_SET_MM_ENV_END
#define PR_SET_MM_ENV_END 11
Definition at line 82 of file prctl.h.
PR_SET_MM_ENV_START
#define PR_SET_MM_ENV_START 10
Definition at line 81 of file prctl.h.
PR_SET_MM_EXE_FILE
#define PR_SET_MM_EXE_FILE 13
Definition at line 84 of file prctl.h.
PR_SET_MM_MAP
#define PR_SET_MM_MAP 14
Definition at line 85 of file prctl.h.
PR_SET_MM_MAP_SIZE
#define PR_SET_MM_MAP_SIZE 15
Definition at line 86 of file prctl.h.
PR_SET_MM_START_BRK
#define PR_SET_MM_START_BRK 6
Definition at line 77 of file prctl.h.
PR_SET_MM_START_CODE
#define PR_SET_MM_START_CODE 1
Definition at line 72 of file prctl.h.
PR_SET_MM_START_DATA
#define PR_SET_MM_START_DATA 3
Definition at line 74 of file prctl.h.
PR_SET_MM_START_STACK
#define PR_SET_MM_START_STACK 5
Definition at line 76 of file prctl.h.
PR_SET_NAME
#define PR_SET_NAME 15
Definition at line 40 of file prctl.h.
PR_SET_NO_NEW_PRIVS
#define PR_SET_NO_NEW_PRIVS 38
Definition at line 111 of file prctl.h.
PR_SET_PDEATHSIG
#define PR_SET_PDEATHSIG 1
Definition at line 10 of file prctl.h.
PR_SET_PTRACER
#define PR_SET_PTRACER 0x59616d61
Definition at line 105 of file prctl.h.
PR_SET_PTRACER_ANY
#define PR_SET_PTRACER_ANY (-1UL)
Definition at line 106 of file prctl.h.
PR_SET_SECCOMP
#define PR_SET_SECCOMP 22
Definition at line 48 of file prctl.h.
PR_SET_SECUREBITS
#define PR_SET_SECUREBITS 28
Definition at line 56 of file prctl.h.
PR_SET_SPECULATION_CTRL
#define PR_SET_SPECULATION_CTRL 53
Definition at line 140 of file prctl.h.
PR_SET_SYSCALL_USER_DISPATCH
#define PR_SET_SYSCALL_USER_DISPATCH 59
Definition at line 171 of file prctl.h.
PR_SET_TAGGED_ADDR_CTRL
#define PR_SET_TAGGED_ADDR_CTRL 55
Definition at line 157 of file prctl.h.
PR_SET_THP_DISABLE
#define PR_SET_THP_DISABLE 41
Definition at line 116 of file prctl.h.
PR_SET_TIMERSLACK
#define PR_SET_TIMERSLACK 29
Definition at line 57 of file prctl.h.
PR_SET_TIMING
#define PR_SET_TIMING 14
Definition at line 37 of file prctl.h.
PR_SET_TSC
#define PR_SET_TSC 26
Definition at line 52 of file prctl.h.
PR_SET_UNALIGN
#define PR_SET_UNALIGN 6
Definition at line 15 of file prctl.h.
PR_SPEC_DISABLE
#define PR_SPEC_DISABLE (1UL << 2)
Definition at line 146 of file prctl.h.
PR_SPEC_DISABLE_NOEXEC
#define PR_SPEC_DISABLE_NOEXEC (1UL << 4)
Definition at line 148 of file prctl.h.
PR_SPEC_ENABLE
#define PR_SPEC_ENABLE (1UL << 1)
Definition at line 145 of file prctl.h.
PR_SPEC_FORCE_DISABLE
#define PR_SPEC_FORCE_DISABLE (1UL << 3)
Definition at line 147 of file prctl.h.
PR_SPEC_INDIRECT_BRANCH
#define PR_SPEC_INDIRECT_BRANCH 1
Definition at line 142 of file prctl.h.
PR_SPEC_NOT_AFFECTED
#define PR_SPEC_NOT_AFFECTED 0
Definition at line 143 of file prctl.h.
PR_SPEC_PRCTL
#define PR_SPEC_PRCTL (1UL << 0)
Definition at line 144 of file prctl.h.
PR_SPEC_STORE_BYPASS
#define PR_SPEC_STORE_BYPASS 0
Definition at line 141 of file prctl.h.
PR_SVE_GET_VL
#define PR_SVE_GET_VL 51
Definition at line 135 of file prctl.h.
PR_SVE_SET_VL
#define PR_SVE_SET_VL 50
Definition at line 133 of file prctl.h.
PR_SVE_SET_VL_ONEXEC
#define PR_SVE_SET_VL_ONEXEC (1 << 18)
Definition at line 134 of file prctl.h.
PR_SVE_VL_INHERIT
#define PR_SVE_VL_INHERIT (1 << 17)
Definition at line 137 of file prctl.h.
PR_SVE_VL_LEN_MASK
#define PR_SVE_VL_LEN_MASK 0xffff
Definition at line 136 of file prctl.h.
PR_SYS_DISPATCH_OFF
#define PR_SYS_DISPATCH_OFF 0
Definition at line 172 of file prctl.h.
PR_SYS_DISPATCH_ON
#define PR_SYS_DISPATCH_ON 1
Definition at line 173 of file prctl.h.
PR_TAGGED_ADDR_ENABLE
#define PR_TAGGED_ADDR_ENABLE (1UL << 0)
Definition at line 159 of file prctl.h.
PR_TASK_PERF_EVENTS_DISABLE
#define PR_TASK_PERF_EVENTS_DISABLE 31
Definition at line 60 of file prctl.h.
PR_TASK_PERF_EVENTS_ENABLE
#define PR_TASK_PERF_EVENTS_ENABLE 32
Definition at line 61 of file prctl.h.
PR_TIMING_STATISTICAL
#define PR_TIMING_STATISTICAL 0
Definition at line 38 of file prctl.h.
PR_TIMING_TIMESTAMP
#define PR_TIMING_TIMESTAMP 1
Definition at line 39 of file prctl.h.
PR_TSC_ENABLE
#define PR_TSC_ENABLE 1
Definition at line 53 of file prctl.h.
PR_TSC_SIGSEGV
#define PR_TSC_SIGSEGV 2
Definition at line 54 of file prctl.h.
PR_UNALIGN_NOPRINT
#define PR_UNALIGN_NOPRINT 1
Definition at line 16 of file prctl.h.
PR_UNALIGN_SIGBUS
#define PR_UNALIGN_SIGBUS 2
Definition at line 17 of file prctl.h.
SYSCALL_DISPATCH_FILTER_ALLOW
#define SYSCALL_DISPATCH_FILTER_ALLOW 0
Definition at line 174 of file prctl.h.
SYSCALL_DISPATCH_FILTER_BLOCK
#define SYSCALL_DISPATCH_FILTER_BLOCK 1
Definition at line 175 of file prctl.h.
Function Documentation
prctl()
int prctl (int op, ...)
Definition at line 5 of file prctl.c.
 {
     unsigned long x[4];
     int i;
     va_list ap;
     va_start(ap, op);
     for (i=0; i<4; i++) x[i] = va_arg(ap, unsigned long);
     va_end(ap);
     return syscall(SYS_prctl, op, x[0], x[1], x[2], x[3]);
 }
References ap, i, syscall(), va_arg, va_end, va_start, and x.
Referenced by launch_helper(), pthread_getname_np(), pthread_setname_np(), and setpriv_main().