Fennix Userspace: file_window Struct Reference
file_window Struct Reference
#include <file-window.hpp>
Public Member Functions
file_window (const char *path)
void * get ()
Private Attributes
void * _ptr
Detailed Description
Definition at line 10 of file file-window.hpp.
Constructor & Destructor Documentation
file_window()
file_window::file_window (const char * path) inline
Definition at line 11 of file file-window.hpp.
{
         int fd;
         if(mlibc::sys_open("/etc/localtime", O_RDONLY, 0, &fd))
             mlibc::panicLogger() << "mlibc: Error opening file_window to "
                     << path << frg::endlog;
         if(!mlibc::sys_stat) {
             MLIBC_MISSING_SYSDEP();
             __ensure(!"cannot proceed without sys_stat");
         }
         struct stat info;
         if(mlibc::sys_stat(mlibc::fsfd_target::fd, fd, "", 0, &info))
             mlibc::panicLogger() << "mlibc: Error getting TZinfo stats" << frg::endlog;
 #if MLIBC_MAP_FILE_WINDOWS
         if(mlibc::sys_vm_map(nullptr, (size_t)info.st_size, PROT_READ, MAP_PRIVATE,
                 fd, 0, &_ptr))
             mlibc::panicLogger() << "mlibc: Error mapping TZinfo" << frg::endlog;
 #else
         _ptr = getAllocator().allocate(info.st_size);
         __ensure(_ptr);
         size_t progress = 0;
         size_t st_size = static_cast<size_t>(info.st_size);
         while(progress < st_size) {
             ssize_t chunk;
             if(int e = mlibc::sys_read(fd, reinterpret_cast<char *>(_ptr) + progress,
                     st_size - progress, &chunk); e)
                 mlibc::panicLogger() << "mlibc: Read from file_window failed" << frg::endlog;
             if(!chunk)
                 break;
             progress += chunk;
         }
         if(progress != st_size)
             mlibc::panicLogger() << "stat reports " << info.st_size << " but we only read "
                     << progress << " bytes" << frg::endlog;
 #endif
         if(mlibc::sys_close(fd))
             mlibc::panicLogger() << "mlibc: Error closing TZinfo" << frg::endlog;
     }
References __ensure, _ptr, mlibc::fd, fd, getAllocator(), MAP_PRIVATE, MLIBC_MISSING_SYSDEP, O_RDONLY, mlibc::panicLogger, PROT_READ, stat::st_size, mlibc::sys_close(), mlibc::sys_open(), mlibc::sys_read(), mlibc::sys_stat(), and mlibc::sys_vm_map().
Member Function Documentation
get()
void* file_window::get () inline
Definition at line 55 of file file-window.hpp.
                 {
         return _ptr;
     }
References _ptr.
Referenced by tzset(), and anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt().
Field Documentation
_ptr
void* file_window::_ptr private
Definition at line 60 of file file-window.hpp.
Referenced by file_window(), and get().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/internal/include/mlibc/file-window.hpp