Fennix Userspace: Userspace/mlibc/tests/posix/pthread_rwlock.c File Reference
pthread_rwlock.c File Reference
#include <assert.h>
#include <errno.h>
#include <pthread.h>
Functions
static void test_write_lock_unlock ()
static void test_read_lock_unlock ()
static void test_write_trylock_unlock ()
static void test_read_trylock_unlock ()
static void test_write_prevents_read ()
static void test_write_prevents_write ()
static void test_read_prevents_write ()
static void test_read_allows_read ()
static void test_attr ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 104 of file pthread_rwlock.c.
            {
     test_write_lock_unlock();
     test_read_lock_unlock();
     test_write_trylock_unlock();
     test_read_trylock_unlock();
     test_write_prevents_read();
     test_write_prevents_write();
     test_read_prevents_write();
     test_read_allows_read();
     test_attr();
 }
References test_attr(), test_read_allows_read(), test_read_lock_unlock(), test_read_prevents_write(), test_read_trylock_unlock(), test_write_lock_unlock(), test_write_prevents_read(), test_write_prevents_write(), and test_write_trylock_unlock().
test_attr()
static void test_attr () static
Definition at line 85 of file pthread_rwlock.c.
{
     pthread_rwlockattr_t attr;
     pthread_rwlockattr_init(&attr);
     int pshared;
     pthread_rwlockattr_getpshared(&attr, &pshared);
     assert(pshared == PTHREAD_PROCESS_PRIVATE);
     pthread_rwlockattr_setpshared(&attr, PTHREAD_PROCESS_SHARED);
     pthread_rwlockattr_getpshared(&attr, &pshared);
     assert(pshared == PTHREAD_PROCESS_SHARED);
     pthread_rwlockattr_setpshared(&attr, PTHREAD_PROCESS_PRIVATE);
     pthread_rwlockattr_getpshared(&attr, &pshared);
     assert(pshared == PTHREAD_PROCESS_PRIVATE);
     pthread_rwlockattr_destroy(&attr);
 }
References assert, mlibc::attr, PTHREAD_PROCESS_PRIVATE, PTHREAD_PROCESS_SHARED, pthread_rwlockattr_destroy(), pthread_rwlockattr_getpshared(), pthread_rwlockattr_init(), and pthread_rwlockattr_setpshared().
Referenced by main().
test_read_allows_read()
static void test_read_allows_read () static
Definition at line 74 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_rdlock(&rw);
     assert(!res);
     res = pthread_rwlock_tryrdlock(&rw);
     assert(!res);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_rdlock(), pthread_rwlock_tryrdlock(), and pthread_rwlock_unlock().
Referenced by main().
test_read_lock_unlock()
static void test_read_lock_unlock () static
Definition at line 14 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_rdlock(&rw);
     assert(!res);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_rdlock(), and pthread_rwlock_unlock().
Referenced by main().
test_read_prevents_write()
static void test_read_prevents_write () static
Definition at line 63 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_rdlock(&rw);
     assert(!res);
     res = pthread_rwlock_trywrlock(&rw);
     assert(res == EBUSY);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, EBUSY, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_rdlock(), pthread_rwlock_trywrlock(), and pthread_rwlock_unlock().
Referenced by main().
test_read_trylock_unlock()
static void test_read_trylock_unlock () static
Definition at line 32 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_tryrdlock(&rw);
     assert(!res);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_tryrdlock(), and pthread_rwlock_unlock().
Referenced by main().
test_write_lock_unlock()
static void test_write_lock_unlock () static
Definition at line 5 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_wrlock(&rw);
     assert(!res);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_unlock(), and pthread_rwlock_wrlock().
Referenced by main().
test_write_prevents_read()
static void test_write_prevents_read () static
Definition at line 41 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_wrlock(&rw);
     assert(!res);
     res = pthread_rwlock_tryrdlock(&rw);
     assert(res == EBUSY);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, EBUSY, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_tryrdlock(), pthread_rwlock_unlock(), and pthread_rwlock_wrlock().
Referenced by main().
test_write_prevents_write()
static void test_write_prevents_write () static
Definition at line 52 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_wrlock(&rw);
     assert(!res);
     res = pthread_rwlock_trywrlock(&rw);
     assert(res == EBUSY);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, EBUSY, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_trywrlock(), pthread_rwlock_unlock(), and pthread_rwlock_wrlock().
Referenced by main().
test_write_trylock_unlock()
static void test_write_trylock_unlock () static
Definition at line 23 of file pthread_rwlock.c.
{
     int res;
     pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;
     res = pthread_rwlock_trywrlock(&rw);
     assert(!res);
     res = pthread_rwlock_unlock(&rw);
     assert(!res);
 }
References assert, PTHREAD_RWLOCK_INITIALIZER, pthread_rwlock_trywrlock(), and pthread_rwlock_unlock().
Referenced by main().