Fennix Userspace: Userspace/libc/src/std/io/file.c File Reference
file.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <errno.h>
#include <fennix/syscall.h>
#include <sys/types.h>
Functions
PUBLIC FILE * freopen (const char *filename, const char *mode, FILE *stream)
PUBLIC FILE * fopen (const char *filename, const char *mode)
PUBLIC size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
PUBLIC size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
PUBLIC int fclose (FILE *fp)
PUBLIC off_t fseek (FILE *stream, off_t offset, int whence)
PUBLIC long ftell (FILE *stream)
PUBLIC int fflush (FILE *stream)
PUBLIC int fprintf (FILE *stream, const char *format,...)
PUBLIC void setbuf (FILE *stream, char *buf)
PUBLIC int vfprintf (FILE *stream, const char *format, va_list arg)
PUBLIC int vsscanf (const char *s, const char *format, va_list arg)
PUBLIC int sscanf (const char *s, const char *format,...)
Variables
PUBLIC FILE * stdin = NULL
PUBLIC FILE * stdout = NULL
PUBLIC FILE * stderr = NULL
Function Documentation
fclose()
PUBLIC int fclose (FILE * fp)
Definition at line 54 of file file.c.
 {
     if (fp == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     return syscall1(sc_close, fp->_fileno);
 }
fflush()
PUBLIC int fflush (FILE * stream)
Definition at line 85 of file file.c.
 {
     if (stream == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     errno = ENOSYS;
     return EOF;
 }
fopen()
PUBLIC FILE* fopen (const char * filename, const char * mode)
Definition at line 19 of file file.c.
 {
     int fd = syscall2(sc_open, (uint64_t)filename, (uint64_t)mode);
     if (fd < 0)
         return NULL;
     FILE *FilePtr = malloc(sizeof(FILE));
     FilePtr->_fileno = fd;
     return FilePtr;
 }
References _IO_FILE::_fileno, fd, filename, malloc, and NULL.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), _nl_log_untranslated(), conf_write(), create_file(), dialog_menu(), file_write_dep(), find_export_symbols(), fopen_for_read(), fopen_for_write(), fopen_or_warn(), freopen(), G_DoLoadGame(), G_DoSaveGame(), get_charset_aliases(), getdate(), getgrent(), getgrouplist(), getpwent(), getspnam_r(), head_builtin(), LoadDefaultCollection(), LoadResponseFile(), M_FileExists(), M_ReadFile(), M_ReadSaveStrings(), M_WriteFile(), main(), process_includes(), produces_handler(), read_alias_file(), read_man_page(), SaveDefaultCollection(), setmntent(), setusershell(), StatDump(), stdcat(), test_file(), update_passwd(), W_StdC_OpenFile(), write_helpfiles(), WriteTimidityConfig(), and xfopen().
fprintf()
PUBLIC int fprintf (FILE * stream, const char * format, ...)
Definition at line 97 of file file.c.
 {
     if (stream == NULL || format == NULL)
     {
         errno = EINVAL;
         return -1;
     }
     va_list args;
     va_start(args, format);
     const int ret = vfprintf(stream, format, args);
     va_end(args);
     return ret;
 }
References args, EINVAL, errno, format(), NULL, va_end, va_start, and vfprintf().
Referenced by __assert_fail(), _nl_log_untranslated(), _rl_errmsg(), _rl_init_file_error(), _rl_internal_pager(), _rl_macro_dumper_internal(), _rl_ttymsg(), addcchar(), addcstr(), addmntent(), ash_vmsg(), ask_and_unlink(), back_lines(), bad_record_die(), bb_progress_update(), bbunpack(), botch(), builtin_error(), builtin_error_prolog(), builtin_usage(), builtin_warning(), catch(), cmp_main(), conf_warning(), conf_write(), confirm_or_abort(), const_des_init(), dd_output_status(), describe_pid(), dialog_checklist(), dialog_menu(), dialog_textbox(), display_matches(), do_check(), do_config_file(), dolisten(), DonutOverrun(), download_one_url(), dump_lsyntax(), error_prolog(), escape_input(), EV_DoDonut(), EV_VerticalDoor(), exec_kernel_doc(), execute_line(), extract_info(), fatal_error(), fgets_trim_sanitize(), file_write_dep(), finalize(), find_export_symbols(), ftpcmd(), get_line(), get_working_directory(), glob_filename(), handle_eof_input_unit(), herror(), I_CDMusPrintStartup(), I_Error(), ifupdown_main(), init_wsize(), initialize_signames(), internal_debug(), internal_error(), internal_inform(), internal_warning(), ipaddr_modify(), j_inputbox(), kconfig_load(), klogd_setloglevel(), line_error(), M_Episode(), main(), make_here_document(), memory_error_and_abort(), menu_warn(), mkfs_vfat_main(), mv_main(), nc_main(), notify_of_job_status(), pad(), PadRejectArray(), parse_dep_file(), ParseField(), parser_error(), pretty_print_job(), print_builtin(), print_deps(), print_pipeline(), print_position(), print_prompt(), print_route(), printargs(), process_files(), process_line(), produces_handler(), programming_error(), prop_warn(), psignal(), putgrent(), putpwent(), putspent(), reader_loop(), readline_internal_setup(), readwrite(), remove_file(), report_error(), resize_main(), restore(), retrieve_file_data(), rl_deprep_terminal(), rl_ding(), rl_dump_functions(), rl_dump_macros(), rl_dump_variables(), rl_function_dumper(), rl_list_funmap_names(), rl_prep_terminal(), rl_show_char(), rl_variable_dumper(), safe_write_to_pty_decode_iac(), save_input_to_file(), SaveDefaultCollection(), saveg_read8(), saveg_write8(), scan_expression(), scan_request(), script_main(), send_headers(), send_pwd_to_eterm(), shell_getc(), show_shell_usage(), sigpipe(), sigstat(), sort_main(), SpechitOverrun(), stdcat(), stralloc(), strgrow(), sys_error(), table_lookup(), throw_to_top_level(), too_dangerous(), unpack_package(), update_passwd(), usage(), Usage(), valid_argument(), vwarn(), vwarnx(), wait_for(), wcomment(), wprintf_core(), write_buffer_no_status(), write_builtins(), write_documentation(), write_dummy_declarations(), write_endifs(), write_file_footers(), write_file_headers(), write_helpfiles(), write_ifdefs(), write_longdocs(), write_signames(), write_status_file(), WriteTimidityConfig(), xargs_main(), xbotch(), xgetpty(), xmalloc(), xtrace_print_assignment(), xtrace_print_case_command_head(), xtrace_print_for_command_head(), xtrace_print_word_list(), and Z_FileDumpHeap().
fread()
PUBLIC size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 30 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_read, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
References _IO_FILE::_fileno, _IO_FILE::_offset, EINVAL, errno, NULL, SEEK_SET, and size.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), diffreg(), encode_n_base64(), fb_drawimage(), get(), getgrouplist(), getw(), LoadResponseFile(), M_ReadFile(), M_ReadSaveStrings(), read_block(), read_man_page(), retrieve_file_data(), saveg_read8(), skip(), and W_StdC_Read().
freopen()
PUBLIC FILE* freopen (const char * filename, const char * mode, FILE * stream)
Definition at line 13 of file file.c.
 {
     errno = ENOSYS;
     return NULL;
 }
References ENOSYS, errno, and NULL.
Referenced by command_substitute(), do_piping(), main(), makemime_main(), next(), and xfreopen_write().
fseek()
PUBLIC off_t fseek (FILE * stream, off_t offset, int whence)
Definition at line 65 of file file.c.
 {
     if (stream == NULL || whence < 0 || whence > 2)
     {
         errno = EINVAL;
         return -1;
     }
     off_t new_offset = syscall3(sc_lseek, stream->_fileno, offset, whence);
     if (new_offset < 0)
         return -1;
     stream->_offset = new_offset;
     return new_offset;
 }
References _IO_FILE::_fileno, _IO_FILE::_offset, EINVAL, errno, NULL, off_t, and offset.
ftell()
PUBLIC long ftell (FILE * stream)
Definition at line 80 of file file.c.
 {
     return stream->_offset;
 }
fwrite()
PUBLIC size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 42 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_write, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
References _IO_FILE::_fileno, _IO_FILE::_offset, EINVAL, errno, NULL, SEEK_SET, and size.
Referenced by __getopt_msg(), _rl_output_some_chars(), _rl_put_indicator(), buffer_pwrite(), conf_write(), encode_n_base64(), evaluate(), expr_print_file_helper(), fnprint(), fputs(), M_WriteFile(), perror(), print_line(), putw(), read_base64(), refresh(), saveg_write8(), svlogd_main(), tee_main(), write2stdout(), and write_zeros().
setbuf()
PUBLIC void setbuf (FILE * stream, char * buf)
Definition at line 112 of file file.c.
 {
 }
Referenced by fsck_main(), main(), mpstat_main(), open_next_file(), and tee_main().
sscanf()
PUBLIC int sscanf (const char * s, const char * format, ...)
Definition at line 125 of file file.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsscanf(s, format, args);
     va_end(args);
     return ret;
 }
References args, format(), s, va_end, va_start, and vsscanf().
Referenced by action_compat(), arp_show(), build_ipv4_addr(), cap_name_to_number(), colon(), conf(), conf_choice(), depmod_main(), do_disk_statistics(), do_mktime(), do_tunnels_list(), fb_drawimage(), fuser_main(), get_cpu_count(), get_cpu_statistics(), get_dev_fields(), get_header_cpio(), get_irqs_from_stat(), get_num_from_file(), get_uptime(), get_wol_pw(), getmntent_r(), list_devs_in_proc_partititons(), ll_addr_a2n(), M_StrToInt(), main(), make_device(), name_to_dev_t(), parse_datestr(), parse_meminfo(), ParseIntParameter(), patch_main(), process_config_line(), procps_scan(), readprofile_main(), recover_mode(), scan_inet_proc_line(), scan_proc_net_or_maps(), ubi_devnum_from_devname(), ubi_tools_main(), and unix_do_one().
vfprintf()
PUBLIC int vfprintf (FILE * stream, const char * format, va_list arg)
Definition at line 116 of file file.c.
 {
     return 0;
 }
Referenced by _rl_init_file_error(), ash_vmsg(), builtin_error(), builtin_warning(), conf_warning(), dprintf(), fatal_error(), fprintf(), I_Error(), internal_debug(), internal_error(), internal_inform(), internal_warning(), menu_warn(), parser_error(), printf(), programming_error(), prop_warn(), report_error(), sys_error(), vdprintf(), vprintf(), vsnprintf(), vwarn(), and vwarnx().
vsscanf()
PUBLIC int vsscanf (const char * s, const char * format, va_list arg)
Definition at line 121 of file file.c.
 {
 }
Referenced by sscanf().
Variable Documentation
stderr
PUBLIC FILE* stderr = NULL
Definition at line 11 of file file.c.
stdin
PUBLIC FILE* stdin = NULL
Definition at line 9 of file file.c.
stdout
PUBLIC FILE* stdout = NULL
Definition at line 10 of file file.c.