Fennix: Userspace/apps/base/busybox/networking/udhcp/packet.c File Reference
packet.c File Reference
#include "common.h"
#include "dhcpd.h"
#include <netinet/in.h>
#include <netinet/if_ether.h>
#include <netpacket/packet.h>
Functions
int FAST_FUNC udhcp_recv_kernel_packet (struct dhcp_packet *packet, int fd)
int FAST_FUNC udhcp_send_raw_packet (struct dhcp_packet *dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const uint8_t *dest_arp, int ifindex)
int FAST_FUNC udhcp_send_kernel_packet (struct dhcp_packet *dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const char *ifname)
Function Documentation
udhcp_recv_kernel_packet()
int FAST_FUNC udhcp_recv_kernel_packet (struct dhcp_packet * packet, int fd)
Definition at line 81 of file packet.c.
 {
     int bytes;
     memset(packet, 0, sizeof(*packet));
     bytes = safe_read(fd, packet, sizeof(*packet));
     if (bytes < 0) {
         log1s("packet read error, ignoring");
         return bytes; /* returns -1 */
     }
     if (bytes < offsetof(struct dhcp_packet, options)
      || packet->cookie != htonl(DHCP_MAGIC)
     ) {
         bb_simple_info_msg("packet with bad magic, ignoring");
         return -2;
     }
     log2("received %s", "a packet");
     /* log2 because more informative msg for valid packets is printed later at log1 level */
     udhcp_dump_packet(packet);
     return bytes;
 }
References bb_simple_info_msg, dhcp_packet::cookie, DHCP_MAGIC, fd, htonl(), log1s, log2, memset, offsetof, safe_read(), and udhcp_dump_packet.
Referenced by dhcprelay_main(), udhcpc_main(), and udhcpd_main().
udhcp_send_kernel_packet()
int FAST_FUNC udhcp_send_kernel_packet (struct dhcp_packet * dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const char * ifname)
Definition at line 192 of file packet.c.
 {
     struct sockaddr_in sa;
     unsigned padding;
     int fd;
     int result = -1;
     const char *msg;
     fd = socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP);
     if (fd < 0) {
         msg = "socket(%s)";
         goto ret_msg;
     }
     setsockopt_reuseaddr(fd);
     /* If interface carrier goes down, unless we
      * bind socket to a particular netdev, the packet
      * can go out through another interface, eg. via
      * default route despite being bound to a specific
      * source IP. As such, bind to device hard and fail
      * otherwise. Sending renewal packets on foreign
      * interfaces makes no sense.
      */
     if (ifname) {
         if (setsockopt_bindtodevice(fd, ifname) < 0) {
             msg = "bindtodevice";
             goto ret_close;
         }
     }
     memset(&sa, 0, sizeof(sa));
     sa.sin_family = AF_INET;
     sa.sin_port = htons(source_port);
     sa.sin_addr.s_addr = source_nip;
     if (bind(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
         msg = "bind(%s)";
         goto ret_close;
     }
     memset(&sa, 0, sizeof(sa));
     sa.sin_family = AF_INET;
     sa.sin_port = htons(dest_port);
     sa.sin_addr.s_addr = dest_nip;
     if (connect(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
         msg = "connect";
         goto ret_close;
     }
     udhcp_dump_packet(dhcp_pkt);
     padding = DHCP_OPTIONS_BUFSIZE - 1 - udhcp_end_option(dhcp_pkt->options);
     if (padding > DHCP_SIZE - 300)
         padding = DHCP_SIZE - 300;
     result = safe_write(fd, dhcp_pkt, DHCP_SIZE - padding);
     msg = "write";
  ret_close:
     close(fd);
     if (result < 0) {
  ret_msg:
         bb_perror_msg(msg, "UDP");
     }
     return result;
 }
References AF_INET, bb_perror_msg(), bind(), close(), connect(), DHCP_OPTIONS_BUFSIZE, DHCP_SIZE, fd, htons(), IPPROTO_UDP, memset, dhcp_packet::options, PF_INET, in_addr::s_addr, safe_write(), setsockopt_bindtodevice(), setsockopt_reuseaddr(), sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, SOCK_DGRAM, socket(), udhcp_dump_packet, and udhcp_end_option().
Referenced by bcast_or_ucast(), and send_packet_to_relay().
udhcp_send_raw_packet()
int FAST_FUNC udhcp_send_raw_packet (struct dhcp_packet * dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const uint8_t * dest_arp, int ifindex)
Definition at line 106 of file packet.c.
 {
     struct sockaddr_ll dest_sll;
     struct ip_udp_dhcp_packet packet;
     unsigned padding;
     int fd;
     int result = -1;
     const char *msg;
     fd = socket(PF_PACKET, SOCK_DGRAM, htons(ETH_P_IP));
     if (fd < 0) {
         msg = "socket(%s)";
         goto ret_msg;
     }
     memset(&dest_sll, 0, sizeof(dest_sll));
     memset(&packet, 0, offsetof(struct ip_udp_dhcp_packet, data));
     packet.data = *dhcp_pkt; /* struct copy */
     dest_sll.sll_family = AF_PACKET;
     dest_sll.sll_protocol = htons(ETH_P_IP);
     dest_sll.sll_ifindex = ifindex;
     /*dest_sll.sll_hatype = ARPHRD_???;*/
     /*dest_sll.sll_pkttype = PACKET_???;*/
     dest_sll.sll_halen = 6;
     memcpy(dest_sll.sll_addr, dest_arp, 6);
 //TODO: is bind() necessary? we sendto() to this destination, should work anyway
     if (bind(fd, (struct sockaddr *)&dest_sll, sizeof(dest_sll)) < 0) {
         msg = "bind(%s)";
         goto ret_close;
     }
     /* We were sending full-sized DHCP packets (zero padded),
      * but some badly configured servers were seen dropping them.
      * Apparently they drop all DHCP packets >576 *ethernet* octets big,
      * whereas they may only drop packets >576 *IP* octets big
      * (which for typical Ethernet II means 590 octets: 6+6+2 + 576).
      *
      * In order to work with those buggy servers,
      * we truncate packets after end option byte.
      *
      * However, RFC 1542 says "The IP Total Length and UDP Length
      * must be large enough to contain the minimal BOOTP header of 300 octets".
      * Thus, we retain enough padding to not go below 300 BOOTP bytes.
      * Some devices have filters which drop DHCP packets shorter than that.
      */
     padding = DHCP_OPTIONS_BUFSIZE - 1 - udhcp_end_option(packet.data.options);
     if (padding > DHCP_SIZE - 300)
         padding = DHCP_SIZE - 300;
     packet.ip.protocol = IPPROTO_UDP;
     packet.ip.saddr = source_nip;
     packet.ip.daddr = dest_nip;
     packet.udp.source = htons(source_port);
     packet.udp.dest = htons(dest_port);
     /* size, excluding IP header: */
     packet.udp.len = htons(UDP_DHCP_SIZE - padding);
     /* for UDP checksumming, ip.len is set to UDP packet len */
     packet.ip.tot_len = packet.udp.len;
     packet.udp.check = inet_cksum(&packet,
             IP_UDP_DHCP_SIZE - padding);
     /* but for sending, it is set to IP packet len */
     packet.ip.tot_len = htons(IP_UDP_DHCP_SIZE - padding);
     packet.ip.ihl = sizeof(packet.ip) >> 2;
     packet.ip.version = IPVERSION;
     packet.ip.ttl = IPDEFTTL;
     packet.ip.check = inet_cksum(&packet.ip, sizeof(packet.ip));
     udhcp_dump_packet(dhcp_pkt);
     result = sendto(fd, &packet, IP_UDP_DHCP_SIZE - padding, /*flags:*/ 0,
             (struct sockaddr *) &dest_sll, sizeof(dest_sll));
     msg = "sendto";
  ret_close:
     close(fd);
     if (result < 0) {
  ret_msg:
         bb_perror_msg(msg, "PACKET");
     }
     return result;
 }
References AF_PACKET, bb_perror_msg(), bind(), iphdr::check, close(), iphdr::daddr, ip_udp_dhcp_packet::data, DHCP_OPTIONS_BUFSIZE, DHCP_SIZE, ETH_P_IP, fd, htons(), iphdr::ihl, inet_cksum(), ip_udp_dhcp_packet::ip, IP_UDP_DHCP_SIZE, IPDEFTTL, IPPROTO_UDP, IPVERSION, memcpy, memset, offsetof, dhcp_packet::options, PF_PACKET, iphdr::protocol, iphdr::saddr, sendto(), sockaddr_ll::sll_addr, sockaddr_ll::sll_family, sockaddr_ll::sll_halen, sockaddr_ll::sll_ifindex, sockaddr_ll::sll_protocol, SOCK_DGRAM, socket(), iphdr::tot_len, iphdr::ttl, udhcp_dump_packet, udhcp_end_option(), ip_udp_dhcp_packet::udp, UDP_DHCP_SIZE, and iphdr::version.
Referenced by raw_bcast_from_client_data_ifindex(), and send_packet_to_client().