Fennix Userspace: Userspace/musl/src/legacy/cuserid.c File Reference
cuserid.c File Reference
#include <pwd.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
Macros
#define _GNU_SOURCE
Functions
char * cuserid (char *buf)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file cuserid.c.
Function Documentation
cuserid()
char* cuserid (char * buf)
Definition at line 7 of file cuserid.c.
 {
     static char usridbuf[L_cuserid];
     struct passwd pw, *ppw;
     long pwb[256];
     if (buf) *buf = 0;
     getpwuid_r(geteuid(), &pw, (void *)pwb, sizeof pwb, &ppw);
     if (!ppw)
         return buf;
     size_t len = strnlen(pw.pw_name, L_cuserid);
     if (len == L_cuserid)
         return buf;
     if (!buf) buf = usridbuf;
     memcpy(buf, pw.pw_name, len+1);
     return buf;
 }
References buf, geteuid, getpwuid_r(), memcpy(), pw, passwd::pw_name, and strnlen().