Fennix Userspace: Userspace/apps/base/busybox/libbb/procps.c File Reference
procps.c File Reference
#include "libbb.h"
Data Structures
struct id_to_name_map_t
struct cache_t
Macros
#define PROCPS_BUFSIZE 1024
Typedefs
typedef struct id_to_name_map_t id_to_name_map_t
typedef struct cache_t cache_t
Functions
void FAST_FUNC clear_username_cache (void)
static char * get_cached (int user_group, uid_t id, char *FAST_FUNC x2x_utoa(uid_t id))
const char *FAST_FUNC get_cached_username (uid_t uid)
const char *FAST_FUNC get_cached_groupname (gid_t gid)
static int read_to_buf (const char *filename, void *buf)
static procps_status_t *FAST_FUNC alloc_procps_scan (void)
void FAST_FUNC free_procps_scan (procps_status_t *sp)
procps_status_t *FAST_FUNC procps_scan (procps_status_t *sp, int flags)
void FAST_FUNC read_cmdline (char *buf, int col, unsigned pid, const char *comm)
Variables
static cache_t * cache_user_group
Data Structure Documentation
id_to_name_map_t
struct id_to_name_map_t
Definition at line 14 of file procps.c.
Data Fields
uid_t id
char name[USERNAME_MAX_SIZE]
cache_t
struct cache_t
Definition at line 19 of file procps.c.
Data Fields
id_to_name_map_t * cache
int size
Macro Definition Documentation
PROCPS_BUFSIZE
#define PROCPS_BUFSIZE 1024
Definition at line 67 of file procps.c.
Typedef Documentation
cache_t
typedef struct cache_t cache_t
id_to_name_map_t
typedef struct id_to_name_map_t id_to_name_map_t
Function Documentation
alloc_procps_scan()
static procps_status_t* FAST_FUNC alloc_procps_scan (void) static
Definition at line 84 of file procps.c.
 {
     procps_status_t* sp = xzalloc(sizeof(procps_status_t));
     unsigned n = bb_getpagesize();
     while (1) {
         n >>= 1;
         if (!n) break;
         sp->shift_pages_to_bytes++;
     }
     sp->shift_pages_to_kb = sp->shift_pages_to_bytes - 10;
     sp->dir = xopendir("/proc");
     return sp;
 }
References bb_getpagesize, n, sp, xopendir(), and xzalloc().
Referenced by procps_scan().
clear_username_cache()
void FAST_FUNC clear_username_cache (void)
Definition at line 26 of file procps.c.
 {
     if (cache_user_group) {
         free(cache_user_group[0].cache);
         free(cache_user_group[1].cache);
         free(cache_user_group);
         cache_user_group = NULL;
     }
 }
References cache_user_group, free, and NULL.
Referenced by clearmems(), and ps_main().
free_procps_scan()
void FAST_FUNC free_procps_scan (procps_status_t * sp)
Definition at line 98 of file procps.c.
 {
     closedir(sp->dir);
 #if ENABLE_FEATURE_SHOW_THREADS
     if (sp->task_dir)
         closedir(sp->task_dir);
 #endif
     free(sp->argv0);
     free(sp->exe);
     IF_SELINUX(free(sp->context);)
     free(sp);
 }
References closedir(), free, and sp.
Referenced by procps_scan().
get_cached()
static char* get_cached (int user_group, uid_t id, char *FAST_FUNC x2x_utoauid_t id) static
Definition at line 36 of file procps.c.
 {
     cache_t *cp;
     int i;
     if (!cache_user_group)
         cache_user_group = xzalloc(sizeof(cache_user_group[0]) * 2);
     cp = &cache_user_group[user_group];
     for (i = 0; i < cp->size; i++)
         if (cp->cache[i].id == id)
             return cp->cache[i].name;
     i = cp->size++;
     cp->cache = xrealloc_vector(cp->cache, 2, i);
     cp->cache[i].id = id;
     /* Never fails. Generates numeric string if name isn't found */
     safe_strncpy(cp->cache[i].name, x2x_utoa(id), sizeof(cp->cache[i].name));
     return cp->cache[i].name;
 }
References cache_t::cache, cache_user_group, i, id_to_name_map_t::id, id_to_name_map_t::name, safe_strncpy(), cache_t::size, xrealloc_vector, and xzalloc().
Referenced by get_cached_groupname(), and get_cached_username().
get_cached_groupname()
const char* FAST_FUNC get_cached_groupname (gid_t gid)
Definition at line 61 of file procps.c.
 {
     return get_cached(1, gid, gid2group_utoa);
 }
References get_cached(), and gid2group_utoa().
Referenced by display_single().
get_cached_username()
const char* FAST_FUNC get_cached_username (uid_t uid)
Definition at line 57 of file procps.c.
 {
     return get_cached(0, uid, uid2uname_utoa);
 }
References get_cached(), and uid2uname_utoa().
Referenced by display_process_list(), display_single(), and ps_main().
procps_scan()
procps_status_t* FAST_FUNC procps_scan (procps_status_t * sp, int flags)
Definition at line 282 of file procps.c.
 {
     if (!sp)
         sp = alloc_procps_scan();
     for (;;) {
         struct dirent *entry;
         char buf[PROCPS_BUFSIZE];
         long tasknice;
         unsigned pid;
         int n;
         char filename[sizeof("/proc/%u/task/%u/cmdline") + sizeof(int)*3 * 2];
         char *filename_tail;
 #if ENABLE_FEATURE_SHOW_THREADS
         if (sp->task_dir) {
             entry = readdir(sp->task_dir);
             if (entry)
                 goto got_entry;
             closedir(sp->task_dir);
             sp->task_dir = NULL;
         }
 #endif
         entry = readdir(sp->dir);
         if (entry == NULL) {
             free_procps_scan(sp);
             return NULL;
         }
  IF_FEATURE_SHOW_THREADS(got_entry:)
         pid = bb_strtou(entry->d_name, NULL, 10);
         if (errno)
             continue;
 #if ENABLE_FEATURE_SHOW_THREADS
         if ((flags & PSSCAN_TASKS) && !sp->task_dir) {
             /* We found another /proc/PID. Do not use it,
              * there will be /proc/PID/task/PID (same PID!),
              * so just go ahead and dive into /proc/PID/task. */
             sprintf(filename, "/proc/%u/task", pid);
             /* Note: if opendir fails, we just go to next /proc/XXX */
             sp->task_dir = opendir(filename);
             sp->main_thread_pid = pid;
             continue;
         }
 #endif
         /* After this point we can:
          * "break": stop parsing, return the data
          * "continue": try next /proc/XXX
          */
         memset(&sp->vsz, 0, sizeof(*sp) - offsetof(procps_status_t, vsz));
         sp->pid = pid;
         if (!(flags & ~PSSCAN_PID))
             break; /* we needed only pid, we got it */
 #if ENABLE_SELINUX
         if (flags & PSSCAN_CONTEXT) {
             if (getpidcon(sp->pid, &sp->context) < 0)
                 sp->context = NULL;
         }
 #endif
 #if ENABLE_FEATURE_SHOW_THREADS
         if (sp->task_dir)
             filename_tail = filename + sprintf(filename, "/proc/%u/task/%u/", sp->main_thread_pid, pid);
         else
 #endif
             filename_tail = filename + sprintf(filename, "/proc/%u/", pid);
         if (flags & PSSCAN_UIDGID) {
             struct stat sb;
             if (stat(filename, &sb))
                 continue; /* process probably exited */
             /* Effective UID/GID, not real */
             sp->uid = sb.st_uid;
             sp->gid = sb.st_gid;
         }
         /* These are all retrieved from proc/NN/stat in one go: */
         if (flags & (PSSCAN_PPID | PSSCAN_PGID | PSSCAN_SID
             | PSSCAN_COMM | PSSCAN_STATE
             | PSSCAN_VSZ | PSSCAN_RSS
             | PSSCAN_STIME | PSSCAN_UTIME | PSSCAN_START_TIME
             | PSSCAN_TTY | PSSCAN_NICE
             | PSSCAN_CPU)
         ) {
             int s_idx;
             char *cp, *comm1;
             int tty;
 #if !ENABLE_FEATURE_FAST_TOP
             unsigned long vsz, rss;
 #endif
             /* see proc(5) for some details on this */
             strcpy(filename_tail, "stat");
             n = read_to_buf(filename, buf);
             if (n < 0)
                 continue; /* process probably exited */
             cp = strrchr(buf, ')'); /* split into "PID (cmd" and "<rest>" */
             /*if (!cp || cp[1] != ' ')
                 continue;*/
             cp[0] = '\0';
             BUILD_BUG_ON(sizeof(sp->comm) < 16);
             comm1 = strchr(buf, '(');
             /*if (comm1)*/
                 safe_strncpy(sp->comm, comm1 + 1, sizeof(sp->comm));
 #if !ENABLE_FEATURE_FAST_TOP
             n = sscanf(cp+2,
                 "%c %u "               /* state, ppid */
                 "%u %u %d %*s "        /* pgid, sid, tty, tpgid */
                 "%*s %*s %*s %*s %*s " /* flags, min_flt, cmin_flt, maj_flt, cmaj_flt */
                 "%lu %lu "             /* utime, stime */
                 "%*s %*s %*s "         /* cutime, cstime, priority */
                 "%ld "                 /* nice */
                 "%*s %*s "             /* timeout, it_real_value */
                 "%lu "                 /* start_time */
                 "%lu "                 /* vsize */
                 "%lu "                 /* rss */
 # if ENABLE_FEATURE_TOP_SMP_PROCESS
                 "%*s %*s %*s %*s %*s %*s " /*rss_rlim, start_code, end_code, start_stack, kstk_esp, kstk_eip */
                 "%*s %*s %*s %*s "         /*signal, blocked, sigignore, sigcatch */
                 "%*s %*s %*s %*s "         /*wchan, nswap, cnswap, exit_signal */
                 "%d"                       /*cpu last seen on*/
 # endif
                 ,
                 sp->state, &sp->ppid,
                 &sp->pgid, &sp->sid, &tty,
                 &sp->utime, &sp->stime,
                 &tasknice,
                 &sp->start_time,
                 &vsz,
                 &rss
 # if ENABLE_FEATURE_TOP_SMP_PROCESS
                 , &sp->last_seen_on_cpu
 # endif
                 );
             if (n < 11)
                 continue; /* bogus data, get next /proc/XXX */
 # if ENABLE_FEATURE_TOP_SMP_PROCESS
             if (n == 11)
                 sp->last_seen_on_cpu = 0;
 # endif
             /* vsz is in bytes and we want kb */
             sp->vsz = vsz >> 10;
             /* vsz is in bytes but rss is in *PAGES*! Can you believe that? */
             sp->rss = rss << sp->shift_pages_to_kb;
             sp->tty_major = (tty >> 8) & 0xfff;
             sp->tty_minor = (tty & 0xff) | ((tty >> 12) & 0xfff00);
 #else
 /* This costs ~100 bytes more but makes top faster by 20%
  * If you run 10000 processes, this may be important for you */
             sp->state[0] = cp[2];
             cp += 4;
             sp->ppid = fast_strtoul_10(&cp);
             sp->pgid = fast_strtoul_10(&cp);
             sp->sid = fast_strtoul_10(&cp);
             tty = fast_strtoul_10(&cp);
             sp->tty_major = (tty >> 8) & 0xfff;
             sp->tty_minor = (tty & 0xff) | ((tty >> 12) & 0xfff00);
             cp = skip_fields(cp, 6); /* tpgid, flags, min_flt, cmin_flt, maj_flt, cmaj_flt */
             sp->utime = fast_strtoul_10(&cp);
             sp->stime = fast_strtoul_10(&cp);
             cp = skip_fields(cp, 3); /* cutime, cstime, priority */
             tasknice = fast_strtol_10(&cp);
             cp = skip_fields(cp, 2); /* timeout, it_real_value */
             sp->start_time = fast_strtoul_10(&cp);
             /* vsz is in bytes and we want kb */
             sp->vsz = fast_strtoul_10(&cp) >> 10;
             /* vsz is in bytes but rss is in *PAGES*! Can you believe that? */
             sp->rss = fast_strtoul_10(&cp) << sp->shift_pages_to_kb;
 # if ENABLE_FEATURE_TOP_SMP_PROCESS
             /* (6): rss_rlim, start_code, end_code, start_stack, kstk_esp, kstk_eip */
             /* (4): signal, blocked, sigignore, sigcatch */
             /* (4): wchan, nswap, cnswap, exit_signal */
             cp = skip_fields(cp, 14);
 //FIXME: is it safe to assume this field exists?
             sp->last_seen_on_cpu = fast_strtoul_10(&cp);
 # endif
 #endif /* FEATURE_FAST_TOP */
 #if ENABLE_FEATURE_PS_ADDITIONAL_COLUMNS
             sp->niceness = tasknice;
 #endif
             sp->state[1] = ' ';
             sp->state[2] = ' ';
             s_idx = 1;
             if (sp->vsz == 0 && sp->state[0] != 'Z') {
                 /* not sure what the purpose of this flag */
                 sp->state[1] = 'W';
                 s_idx = 2;
             }
             if (tasknice != 0) {
                 if (tasknice < 0)
                     sp->state[s_idx] = '<';
                 else /* > 0 */
                     sp->state[s_idx] = 'N';
             }
         }
 #if ENABLE_FEATURE_TOPMEM
         if (flags & PSSCAN_SMAPS)
             procps_read_smaps(pid, &sp->smaps, NULL, NULL);
 #endif /* TOPMEM */
 #if ENABLE_FEATURE_PS_ADDITIONAL_COLUMNS
         if (flags & PSSCAN_RUIDGID) {
             FILE *file;
             strcpy(filename_tail, "status");
             file = fopen_for_read(filename);
             if (file) {
                 while (fgets(buf, sizeof(buf), file)) {
                     char *tp;
 #define SCAN_TWO(str, name, statement) \
     if ((tp = is_prefixed_with(buf, str)) != NULL) { \
         tp = skip_whitespace(tp); \
         sscanf(tp, "%u", &sp->name); \
         statement; \
     }
                     SCAN_TWO("Uid:", ruid, continue);
                     SCAN_TWO("Gid:", rgid, break);
 #undef SCAN_TWO
                 }
                 fclose(file);
             }
         }
 #endif /* PS_ADDITIONAL_COLUMNS */
         if (flags & PSSCAN_EXE) {
             strcpy(filename_tail, "exe");
             free(sp->exe);
             sp->exe = xmalloc_readlink(filename);
         }
         /* Note: if /proc/PID/cmdline is empty,
          * code below "breaks". Therefore it must be
          * the last code to parse /proc/PID/xxx data
          * (we used to have /proc/PID/exe parsing after it
          * and were getting stale sp->exe).
          */
 #if 0 /* PSSCAN_CMD is not used */
         if (flags & (PSSCAN_CMD|PSSCAN_ARGV0)) {
             free(sp->argv0);
             sp->argv0 = NULL;
             free(sp->cmd);
             sp->cmd = NULL;
             strcpy(filename_tail, "cmdline");
             /* TODO: to get rid of size limits, read into malloc buf,
              * then realloc it down to real size. */
             n = read_to_buf(filename, buf);
             if (n <= 0)
                 break;
             if (flags & PSSCAN_ARGV0)
                 sp->argv0 = xstrdup(buf);
             if (flags & PSSCAN_CMD) {
                 do {
                     n--;
                     if ((unsigned char)(buf[n]) < ' ')
                         buf[n] = ' ';
                 } while (n);
                 sp->cmd = xstrdup(buf);
             }
         }
 #else
         if (flags & (PSSCAN_ARGV0|PSSCAN_ARGVN)) {
             free(sp->argv0);
             sp->argv0 = NULL;
             strcpy(filename_tail, "cmdline");
             n = read_to_buf(filename, buf);
             if (n <= 0)
                 break;
             if (flags & PSSCAN_ARGVN) {
                 sp->argv_len = n;
                 sp->argv0 = xmemdup(buf, n + 1);
                 /* sp->argv0[n] = '\0'; - buf has it */
             } else {
                 sp->argv_len = 0;
                 sp->argv0 = xstrdup(buf);
             }
         }
 #endif
         break;
     } /* for (;;) */
     return sp;
 }
References alloc_procps_scan(), bb_strtou(), buf, BUILD_BUG_ON, closedir(), errno, fclose(), fgets, filename, flags, fopen_for_read(), free, free_procps_scan(), memset(), n, NULL, offsetof, opendir(), pid, PROCPS_BUFSIZE, procps_read_smaps(), PSSCAN_ARGV0, PSSCAN_ARGVN, PSSCAN_COMM, PSSCAN_CONTEXT, PSSCAN_CPU, PSSCAN_EXE, PSSCAN_NICE, PSSCAN_PGID, PSSCAN_PID, PSSCAN_PPID, PSSCAN_RSS, PSSCAN_RUIDGID, PSSCAN_SID, PSSCAN_SMAPS, PSSCAN_START_TIME, PSSCAN_STATE, PSSCAN_STIME, PSSCAN_TASKS, PSSCAN_TTY, PSSCAN_UIDGID, PSSCAN_UTIME, PSSCAN_VSZ, read_to_buf(), readdir(), rgid, ruid, safe_strncpy(), sp, sprintf(), sscanf(), stat::st_gid, stat::st_uid, stat(), strchr(), strcpy(), strrchr(), tp, xmalloc_readlink(), xmemdup(), and xstrdup().
Referenced by find_pid_by_name(), kill_main(), lsof_main(), mread_proc(), pgrep_main(), ps_main(), signal_mdevs(), and top_main().
read_cmdline()
void FAST_FUNC read_cmdline (char * buf, int col, unsigned pid, const char * comm)
Definition at line 569 of file procps.c.
 {
     int sz;
     char filename[sizeof("/proc/%u/cmdline") + sizeof(int)*3];
     sprintf(filename, "/proc/%u/cmdline", pid);
     sz = open_read_close(filename, buf, col - 1);
     if (sz > 0) {
         const char *base;
         int comm_len;
         buf[sz] = '\0';
         while (--sz >= 0 && buf[sz] == '\0')
             continue;
         /* Prevent basename("process foo/bar") = "bar" */
         strchrnul(buf, ' ')[0] = '\0';
         base = bb_basename(buf); /* before we replace argv0's NUL with space */
         while (sz >= 0) {
             if ((unsigned char)(buf[sz]) < ' ')
                 buf[sz] = ' ';
             sz--;
         }
         if (base[0] == '-') /* "-sh" (login shell)? */
             base++;
         /* If comm differs from argv0, prepend "{comm} ".
          * It allows to see thread names set by prctl(PR_SET_NAME).
          */
         if (!comm)
             return;
         comm_len = strlen(comm);
         /* Why compare up to comm_len, not COMM_LEN-1?
          * Well, some processes rewrite argv, and use _spaces_ there
          * while rewriting. (KDE is observed to do it).
          * I prefer to still treat argv0 "process foo bar"
          * as 'equal' to comm "process".
          */
         if (strncmp(base, comm, comm_len) != 0) {
             comm_len += 3;
             if (col > comm_len)
                 memmove(buf + comm_len, buf, col - comm_len);
             snprintf(buf, col, "{%s}", comm);
             if (col <= comm_len)
                 return;
             buf[comm_len - 1] = ' ';
             buf[col - 1] = '\0';
         }
     } else {
         snprintf(buf, col, "[%s]", comm ? comm : "?");
     }
 }
References base, bb_basename(), buf, filename, memmove(), open_read_close(), pid, snprintf(), sprintf(), strchrnul(), strlen(), and strncmp().
Referenced by display_process_list(), procps_get_maps(), and ps_main().
read_to_buf()
static int read_to_buf (const char * filename, void * buf) static
Definition at line 69 of file procps.c.
 {
     int fd;
     /* open_read_close() would do two reads, checking for EOF.
      * When you have 10000 /proc/$NUM/stat to read, it isn't desirable */
     ssize_t ret = -1;
     fd = open(filename, O_RDONLY);
     if (fd >= 0) {
         ret = read(fd, buf, PROCPS_BUFSIZE-1);
         close(fd);
     }
     ((char *)buf)[ret > 0 ? ret : 0] = '\0';
     return ret;
 }
References buf, close(), fd, filename, O_RDONLY, open(), PROCPS_BUFSIZE, and read().
Referenced by procps_scan().
Variable Documentation
cache_user_group
cache_t* cache_user_group static
Definition at line 24 of file procps.c.
Referenced by clear_username_cache(), and get_cached().