Fennix: Userspace/apps/base/busybox/selinux/setenforce.c File Reference
setenforce.c File Reference
#include "libbb.h"
Functions
int setenforce_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char *const setenforce_cmd[] ALIGN_PTR
Function Documentation
setenforce_main()
int setenforce_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 38 of file setenforce.c.
 {
     int i, rc;
     if (!argv[1] || argv[2])
         bb_show_usage();
     selinux_or_die();
     for (i = 0; setenforce_cmd[i]; i++) {
         if (strcasecmp(argv[1], setenforce_cmd[i]) != 0)
             continue;
         rc = security_setenforce(i & 1);
         if (rc < 0)
             bb_simple_perror_msg_and_die("setenforce() failed");
         return 0;
     }
     bb_show_usage();
 }
References argv, bb_show_usage(), bb_simple_perror_msg_and_die(), i, rc, selinux_or_die(), and strcasecmp.
Variable Documentation
ALIGN_PTR
const char* const setenforce_cmd [] ALIGN_PTR static
Initial value:
= {
    "0",
    "1",
    "permissive",
    "enforcing",
    NULL,
}
Definition at line 29 of file setenforce.c.