Fennix: Userspace/apps/base/bash/lib/readline/examples/rl-callbacktest.c File Reference
rl-callbacktest.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/select.h>
#include <signal.h>
#include <errno.h>
#include <stdio.h>
#include <locale.h>
#include <readline/readline.h>
#include <readline/history.h>
Functions
static void cb_linehandler (char *)
static void signandler (int)
static void sighandler (int sig)
int main (int c, char **v)
Variables
int errno
int running
int sigwinch_received
const char * prompt = "rltest$ "
Function Documentation
cb_linehandler()
static void cb_linehandler (char * line) static
Definition at line 46 of file rl-callbacktest.c.
 {
   /* Can use ^D (stty eof) or `exit' to exit. */
   if (line == NULL || strcmp (line, "exit") == 0)
     {
       if (line == 0)
         printf ("\n");
       printf ("exit\n");
       /* This function needs to be called to reset the terminal settings,
      and calling it from the line handler keeps one extra prompt from
      being displayed. */
       rl_callback_handler_remove ();
       running = 0;
     }
   else
     {
       if (*line)
     add_history (line);
       printf ("input line: %s\n", line);
       free (line);
     }
 }
References add_history(), free, NULL, printf, rl_callback_handler_remove(), running, and strcmp.
Referenced by main().
main()
int main (int c, char ** v)
Definition at line 71 of file rl-callbacktest.c.
 {
   fd_set fds;
   int r;
   setlocale (LC_ALL, "");
   /* Handle SIGWINCH */
   signal (SIGWINCH, sighandler);
   /* Install the line handler. */
   rl_callback_handler_install (prompt, cb_linehandler);
   /* Enter a simple event loop.  This waits until something is available
      to read on readline's input stream (defaults to standard input) and
      calls the builtin character read callback to read it.  It does not
      have to modify the user's terminal settings. */
   running = 1;
   while (running)
     {
       FD_ZERO (&fds);
       FD_SET (fileno (rl_instream), &fds);
       r = select (FD_SETSIZE, &fds, NULL, NULL, NULL);
       if (r < 0 && errno != EINTR)
     {
       perror ("rltest: select");
       rl_callback_handler_remove ();
       break;
     }
       if (sigwinch_received)
     {
       rl_resize_terminal ();
       sigwinch_received = 0;
     }
       if (r < 0)
     continue;
       if (FD_ISSET (fileno (rl_instream), &fds))
     rl_callback_read_char ();
     }
   printf ("rltest: Event loop has exited\n");
   return 0;
 }
References cb_linehandler(), EINTR, errno, FD_ISSET, FD_SET, FD_SETSIZE, FD_ZERO, fileno(), LC_ALL, NULL, perror(), printf, prompt, rl_callback_handler_install(), rl_callback_handler_remove(), rl_callback_read_char(), rl_instream, rl_resize_terminal(), running, select(), setlocale, sighandler(), signal, SIGWINCH, and sigwinch_received.
sighandler()
static void sighandler (int sig) static
Definition at line 37 of file rl-callbacktest.c.
 {
   sigwinch_received = 1;
 }
References sigwinch_received.
Referenced by main().
signandler()
static void signandler (int) static
Variable Documentation
errno
int errno extern
Referenced by main().
prompt
const char* prompt = "rltest$ "
Definition at line 32 of file rl-callbacktest.c.
Referenced by main().
running
int running
Definition at line 31 of file rl-callbacktest.c.
Referenced by cb_linehandler(), and main().
sigwinch_received
int sigwinch_received
Definition at line 31 of file rl-callbacktest.c.
Referenced by main(), shell_getc(), and sighandler().