Fennix: vfs::USTAR Class Reference
vfs::USTAR Class Reference
#include <ustar.hpp>
Data Structures
struct FileHeader
struct USTARInode
Public Types
enum TypeFlag {
AREGTYPE = '\0' , REGTYPE = '0' , LNKTYPE = '1' , SYMTYPE = '2' ,
CHRTYPE = '3' , BLKTYPE = '4' , DIRTYPE = '5' , FIFOTYPE = '6' ,
CONTTYPE = '7'
}
enum ModeFlag {
TSUID = 04000 , TSGID = 02000 , TSVTX = 01000 , TUREAD = 00400 ,
TUWRITE = 00200 , TUEXEC = 00100 , TGREAD = 00040 , TGWRITE = 00020 ,
TGEXEC = 00010 , TOREAD = 00004 , TOWRITE = 00002 , TOEXEC = 00001
}
Public Member Functions
int Lookup (struct Inode *Parent, const char *Name, struct Inode **Result)
int Create (struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
ssize_t Read (struct Inode *Node, void *Buffer, size_t Size, off_t Offset)
ssize_t ReadDir (struct Inode *Node, struct kdirent *Buffer, size_t Size, off_t Offset, off_t Entries)
int SymLink (struct Inode *Node, const char *Name, const char *Target, struct Inode **Result)
ssize_t ReadLink (struct Inode *Node, char *Buffer, size_t Size)
int Stat (struct Inode *Node, struct kstat *Stat)
bool TestArchive (uintptr_t Address)
void ReadArchive (uintptr_t Address, size_t Size)
USTAR ()
~USTAR ()
Data Fields
dev_t DeviceID = -1
ino_t NextInode = 0
Static Public Attributes
constexpr static int INODE_CHECKSUM = 0x7757A4
Private Member Functions
uint32_t GetSize (const char *String)
int StringToInt (const char *String)
Private Attributes
std::unordered_map< ino_t, USTARInode * > Files
Detailed Description
Definition at line 25 of file ustar.hpp.
Data Structure Documentation
vfs::USTAR::FileHeader
struct vfs::USTAR::FileHeader
Definition at line 57 of file ustar.hpp.
Data Fields
char chksum[8]
char dev_maj[8]
char dev_min[8]
char gid[8]
char group[32]
char link[100]
char mode[8]
char mtime[12]
char name[100]
char owner[32]
char pad[12]
char prefix[155]
char signature[6]
char size[12]
char typeflag[1]
char uid[8]
char version[2]
vfs::USTAR::USTARInode
struct vfs::USTAR::USTARInode
Definition at line 80 of file ustar.hpp.
Data Fields
int Checksum
vector< USTARInode * > Children
bool Deleted
FileHeader * Header
string Name
struct Inode Node
USTARInode * Parent
string Path
Member Enumeration Documentation
ModeFlag
enum vfs::USTAR::ModeFlag
Enumerator
TSUID
TSGID
TSVTX
TUREAD
TUWRITE
TUEXEC
TGREAD
TGWRITE
TGEXEC
TOREAD
TOWRITE
TOEXEC
Definition at line 41 of file ustar.hpp.
         {
             TSUID = 04000,
             TSGID = 02000,
             TSVTX = 01000,
             TUREAD = 00400,
             TUWRITE = 00200,
             TUEXEC = 00100,
             TGREAD = 00040,
             TGWRITE = 00020,
             TGEXEC = 00010,
             TOREAD = 00004,
             TOWRITE = 00002,
             TOEXEC = 00001,
         };
TypeFlag
enum vfs::USTAR::TypeFlag
Enumerator
AREGTYPE
REGTYPE
LNKTYPE
SYMTYPE
CHRTYPE
BLKTYPE
DIRTYPE
FIFOTYPE
CONTTYPE
Definition at line 28 of file ustar.hpp.
         {
             AREGTYPE = '\0',
             REGTYPE = '0',
             LNKTYPE = '1',
             SYMTYPE = '2',
             CHRTYPE = '3',
             BLKTYPE = '4',
             DIRTYPE = '5',
             FIFOTYPE = '6',
             CONTTYPE = '7'
         };
Constructor & Destructor Documentation
USTAR()
vfs::USTAR::USTAR () inline
Definition at line 130 of file ustar.hpp.
 {};
~USTAR()
vfs::USTAR::~USTAR () inline
Definition at line 131 of file ustar.hpp.
 {};
Member Function Documentation
Create()
int vfs::USTAR::Create (struct Inode * Parent, const char * Name, mode_t Mode, struct Inode ** Result)
Definition at line 84 of file ustar.cpp.
     {
         USTARInode *Parent = (USTARInode *)_Parent;
         Inode inode{};
         inode.Mode = Mode;
         inode.Device = this->DeviceID;
         inode.RawDevice = 0;
         inode.Index = NextInode;
         inode.Offset = 0;
         inode.PrivateData = this;
         inode.Flags = I_FLAG_CACHE_KEEP;
         const char *basename;
         size_t length;
         cwk_path_get_basename(Name, &basename, &length);
         auto SetMode = [&](mode_t &Mode, FileHeader *header)
         {
             if (Mode & S_IFREG)
                 header->typeflag[0] = REGTYPE;
             else if (Mode & S_IFLNK)
                 header->typeflag[0] = SYMTYPE;
             else if (Mode & S_IFCHR)
                 header->typeflag[0] = CHRTYPE;
             else if (Mode & S_IFBLK)
                 header->typeflag[0] = BLKTYPE;
             else if (Mode & S_IFDIR)
                 header->typeflag[0] = DIRTYPE;
             else if (Mode & S_IFIFO)
                 header->typeflag[0] = FIFOTYPE;
             mode_t final = 0;
             if (Mode & S_ISUID)
                 final |= TSUID;
             else if (Mode & S_ISGID)
                 final |= TSGID;
             else if (Mode & S_ISVTX)
                 final |= TSVTX;
             else if (Mode & S_IRUSR)
                 final |= TUREAD;
             else if (Mode & S_IWUSR)
                 final |= TUWRITE;
             else if (Mode & S_IXUSR)
                 final |= TUEXEC;
             else if (Mode & S_IRGRP)
                 final |= TGREAD;
             else if (Mode & S_IWGRP)
                 final |= TGWRITE;
             else if (Mode & S_IXGRP)
                 final |= TGEXEC;
             else if (Mode & S_IROTH)
                 final |= TOREAD;
             else if (Mode & S_IWOTH)
                 final |= TOWRITE;
             else if (Mode & S_IXOTH)
                 final |= TOEXEC;
             snprintf(header->mode, sizeof(header->mode), "%07o", final);
         };
         FileHeader *hdr = new FileHeader{};
         SetMode(inode.Mode, hdr);
         strncpy(hdr->name, basename, sizeof(hdr->name));
         strncpy(hdr->signature, TMAGIC, TMAGLEN);
         strncpy(hdr->version, TVERSION, TVERSLEN);
         USTARInode *node = new USTARInode{.Node = inode,
                                           .Header = hdr,
                                           .Parent = Parent,
                                           .Name{},
                                           .Path{},
                                           .Children{},
                                           .Deleted = false,
                                           .Checksum = INODE_CHECKSUM};
         node->Name.assign(basename, length);
         node->Path.assign(Name, strlen(Name));
         Files.insert(std::make_pair(NextInode, node));
         *Result = &Files.at(NextInode)->Node;
         if (Parent)
             Parent->Children.push_back(Files.at(NextInode));
         NextInode++;
         return 0;
     }
References basename(), BLKTYPE, vfs::USTAR::USTARInode::Children, CHRTYPE, cwk_path_get_basename(), DeviceID, DIRTYPE, FIFOTYPE, Files, I_FLAG_CACHE_KEEP, INODE_CHECKSUM, Inode::Mode, mode_t, vfs::USTAR::FileHeader::name, vfs::USTAR::USTARInode::Name, Name, NextInode, vfs::USTAR::USTARInode::Node, REGTYPE, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFREG, S_IRGRP, S_IROTH, S_IRUSR, S_ISGID, S_ISUID, S_ISVTX, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, S_IXUSR, vfs::USTAR::FileHeader::signature, snprintf(), strlen, strncpy(), SYMTYPE, TGEXEC, TGREAD, TGWRITE, TMAGIC, TMAGLEN, TOEXEC, TOREAD, TOWRITE, TSGID, TSUID, TSVTX, TUEXEC, TUREAD, TUWRITE, TVERSION, TVERSLEN, and vfs::USTAR::FileHeader::version.
Referenced by SymLink().
GetSize()
uint32_t vfs::USTAR::GetSize (const char * String) inline private
Definition at line 95 of file ustar.hpp.
         {
             uint32_t ret = 0;
             while (*String)
             {
                 ret *= 8;
                 ret += *String - '0';
                 String++;
             }
             return ret;
         }
References ret.
Referenced by Read(), ReadArchive(), and Stat().
Lookup()
int vfs::USTAR::Lookup (struct Inode * Parent, const char * Name, struct Inode ** Result)
Definition at line 33 of file ustar.cpp.
     {
         auto Parent = (USTARInode *)_Parent;
         const char *basename;
         size_t length;
         cwk_path_get_basename(Name, &basename, &length);
         if (basename == NULL)
         {
             if (strcmp(Name, "/") == 0)
             {
                 auto &it = Files.at(0);
                 *Result = &it->Node;
                 return 0;
             }
             error("Invalid name %s", Name);
             return -EINVAL;
         }
         if (_Parent)
         {
             for (const auto &child : Parent->Children)
             {
                 if (child->Deleted || strcmp(child->Name.c_str(), basename) != 0)
                     continue;
                 *Result = &child->Node;
                 return 0;
             }
             return -ENOENT;
         }
         auto fileItr = Files.begin();
         while (fileItr != Files.end())
         {
             USTARInode *node = fileItr->second;
             if (node->Deleted || strcmp(node->Name.c_str(), basename) != 0)
             {
                 fileItr++;
                 continue;
             }
             *Result = &fileItr->second->Node;
             return 0;
         }
         return -ENOENT;
     }
References basename(), child(), cwk_path_get_basename(), EINVAL, ENOENT, error, Files, it, Name, NULL, and strcmp.
Referenced by TestAndInitializeUSTAR().
Read()
ssize_t vfs::USTAR::Read (struct Inode * Node, void * Buffer, size_t Size, off_t Offset)
Definition at line 171 of file ustar.cpp.
     {
         auto fileItr = Files.find(Node->Index);
         assert(fileItr != Files.end());
         if (fileItr->second->Deleted)
             return -ENOENT;
         USTARInode *node = fileItr->second;
         size_t fileSize = GetSize(node->Header->size);
         if (Size <= 0)
         {
             debug("Size is less than or equal to 0");
             Size = fileSize;
         }
         if ((size_t)Offset > fileSize)
         {
             debug("Offset %d is greater than file size %d", Offset, fileSize);
             return 0;
         }
         if ((fileSize - Offset) == 0)
         {
             debug("Offset %d is equal to file size %d", Offset, fileSize);
             return 0; /* EOF */
         }
         if ((size_t)Offset + Size > fileSize)
         {
             debug("Offset %d + Size %d is greater than file size %d",
                   Offset, Size, fileSize);
             Size = fileSize;
         }
         memcpy(Buffer, (uint8_t *)((uintptr_t)node->Header + sizeof(FileHeader) + Offset), Size);
         // debug("Read %d bytes from %d[%d]", Size, Node->Index, Offset);
         return Size;
     }
References assert, vfs::Buffer, debug, ENOENT, Files, GetSize(), memcpy, vfs::Node, vfs::Offset, and vfs::Size.
ReadArchive()
void vfs::USTAR::ReadArchive (uintptr_t Address, size_t Size)
Definition at line 500 of file ustar.cpp.
     {
         trace("Initializing USTAR with address %#lx and size %d", Address, Size);
         auto SetMode = [&](Inode &uNode, FileHeader *header)
         {
             mode_t hdrMode = StringToInt(header->mode);
             if (hdrMode & TSUID)
                 uNode.Mode |= S_ISUID;
             else if (hdrMode & TSGID)
                 uNode.Mode |= S_ISGID;
             else if (hdrMode & TSVTX)
                 uNode.Mode |= S_ISVTX;
             else if (hdrMode & TUREAD)
                 uNode.Mode |= S_IRUSR;
             else if (hdrMode & TUWRITE)
                 uNode.Mode |= S_IWUSR;
             else if (hdrMode & TUEXEC)
                 uNode.Mode |= S_IXUSR;
             else if (hdrMode & TGREAD)
                 uNode.Mode |= S_IRGRP;
             else if (hdrMode & TGWRITE)
                 uNode.Mode |= S_IWGRP;
             else if (hdrMode & TGEXEC)
                 uNode.Mode |= S_IXGRP;
             else if (hdrMode & TOREAD)
                 uNode.Mode |= S_IROTH;
             else if (hdrMode & TOWRITE)
                 uNode.Mode |= S_IWOTH;
             else if (hdrMode & TOEXEC)
                 uNode.Mode |= S_IXOTH;
             switch (header->typeflag[0])
             {
             case AREGTYPE:
             case REGTYPE:
                 uNode.Mode |= S_IFREG;
                 break;
             case LNKTYPE:
                 uNode.Mode |= S_IFLNK;
                 break;
             case SYMTYPE:
                 uNode.Mode |= S_IFLNK;
                 break;
             case CHRTYPE:
                 uNode.Mode |= S_IFCHR;
                 break;
             case BLKTYPE:
                 uNode.Mode |= S_IFBLK;
                 break;
             case DIRTYPE:
                 uNode.Mode |= S_IFDIR;
                 break;
             case FIFOTYPE:
                 uNode.Mode |= S_IFIFO;
                 break;
             case CONTTYPE:
                 warn("Reserved type for %s", header->name);
                 __fallthrough;
             default:
                 error("Unknown type: %d for %s", header->typeflag[0], header->name);
                 break;
             }
         };
         FileHeader *header = (FileHeader *)Address;
         debug("USTAR signature valid! Name:%s Signature:%s Mode:%d Size:%lu",
               header->name, header->signature, StringToInt(header->mode), header->size);
         Memory::Virtual vmm;
         std::vector<USTARInode *> tmpNodes; /* FIXME: bug in unordered_map for iterators */
         for (size_t i = 0;; i++)
         {
             if (!vmm.Check((void *)header))
             {
                 error("Address %#lx is not mapped!", header);
                 return;
             }
             if (strncmp(header->signature, TMAGIC, TMAGLEN) != 0)
                 break;
             // debug("\"%s\"", header->name);
             /* This removes the "." at the beginning of the file name
                 "./foo/bar" > "/foo/bar" */
             if (header->name[0] == '.' && header->name[1] == '/')
                 memmove(header->name, header->name + 1, strlen(header->name));
             if (isempty((char *)header->name))
                 fixme("Ignoring empty file name \"%.*s\"", sizeof(struct FileHeader), header);
             struct Inode uNode;
             uNode.Device = this->DeviceID;
             uNode.RawDevice = 0;
             uNode.Index = NextInode;
             SetMode(uNode, header);
             uNode.Flags = I_FLAG_CACHE_KEEP;
             uNode.Offset = 0;
             uNode.PrivateData = this;
             const char *basename;
             size_t length;
             cwk_path_get_basename(header->name, &basename, &length);
             USTARInode *node = new USTARInode{.Node = uNode,
                                               .Header = header,
                                               .Parent = nullptr,
                                               .Name{},
                                               .Path{},
                                               .Children{},
                                               .Deleted = false,
                                               .Checksum = INODE_CHECKSUM};
             if (basename)
                 node->Name.assign(basename, length);
             else
                 node->Name.assign((const char *)header->name, strlen(header->name));
             node->Path.assign((const char *)header->name, strlen(header->name));
             Files.insert(std::make_pair(NextInode, node));
             tmpNodes.push_back(node);
             size_t size = GetSize(header->size);
             Address += ((size / 512) + 1) * 512;
             if (size % 512)
                 Address += 512;
             header = (FileHeader *)Address;
             NextInode++;
         }
         /* TODO: This code can be significantly optimized but good luck understanding it */
         USTARInode *parent = nullptr;
         std::vector<USTARInode *> parentStack;
         std::vector<std::string *> pathStack;
         for (auto &file : tmpNodes)
         {
             if (file->Path == "/") /* This is root / */
             {
                 parentStack.push_back(file);
                 pathStack.push_back(&file->Path);
                 // debug("root / generated");
                 continue;
             }
             /* pathStack is never empty */
             if (file->Path.back() == '/') /* This is a directory */
             {
                 const char *path = file->Path.c_str();
                 size_t length;
                 /* This converts /one/two/path.txt to /one/two/ */
                 cwk_path_get_dirname(path, &length);
                 std::string dirName(path, length);
                 /* Check if the directory is at the same level as the current directory */
                 if (dirName == *pathStack.back())
                 {
                     parent = parentStack.back();
                     parentStack.push_back(file);
                     pathStack.push_back(&file->Path);
                     parent->Children.push_back(file);
                     file->Parent = parent;
                     // debug("adding \"%s\" to \"%s\"", file->Path.c_str(), parent->Path.c_str());
                     continue;
                 }
                 else
                 {
                     /* Check if the directory is at a higher level */
                     for (size_t i = 0; i < parentStack.size(); i++)
                     {
                         if (dirName != *pathStack[i])
                             continue;
                         /* Adjust vectors */
                         while (!parentStack.empty())
{
                             if (dirName == *pathStack.back())
                                 break;
                             // debug("popping \"%s\"", pathStack.back()->c_str());
                             parentStack.pop_back();
                             pathStack.pop_back();
                         }
                         parent = parentStack.back();
                         parentStack.push_back(file);
                         pathStack.push_back(&file->Path);
                         parent->Children.push_back(file);
                         file->Parent = parent;
                         // debug("adding \"%s\" to \"%s\"", file->Path.c_str(), parent->Path.c_str());
                         goto foundEnd;
                     }
                     // This is a new directory level
                     parentStack.pop_back();
                     pathStack.pop_back();
                     parent = parentStack.back();
                     parentStack.push_back(file);
                     pathStack.push_back(&file->Path);
                     parent->Children.push_back(file);
                     file->Parent = parent;
                     // debug("adding \"%s\" to \"%s\"", file->Path.c_str(), parent->Path.c_str());
                 foundEnd:
                     continue;
                 }
             }
             /* From here, it's a file */
             const char *path = file->Path.c_str();
             size_t length;
             /* This converts /one/two/path.txt to /one/two/ */
             cwk_path_get_dirname(path, &length);
             std::string dirName(path, length);
             /* Check if the file is at the same level as the current directory */
             if (dirName == *pathStack.back())
             {
                 parent = parentStack.back();
                 parent->Children.push_back(file);
                 file->Parent = parent;
                 // debug("adding \"%s\" to \"%s\"", file->Path.c_str(), parent->Path.c_str());
                 continue;
             }
             /* Check if the file is at a higher level */
             for (size_t i = 0; i < parentStack.size(); i++)
             {
                 if (dirName != *pathStack[i])
                     continue;
                 /* Adjust vectors */
                 while (!parentStack.empty())
                 {
                     if (dirName == *pathStack.back())
                         break;
                     // debug("popping \"%s\"", pathStack.back()->c_str());
                     parentStack.pop_back();
                     pathStack.pop_back();
                 }
                 parent = parentStack.back();
                 parent->Children.push_back(file);
                 file->Parent = parent;
                 // debug("adding \"%s\" to \"%s\"", file->Path.c_str(), parent->Path.c_str());
             }
         }
         std::function<void(vfs::USTAR::USTARInode *, int, const std::string &)> ustarTree = [&](vfs::USTAR::USTARInode *node, int level, const std::string &prefix)
         {
             debug("%*s\"%s\"%ld", level * 4, prefix.c_str(), node->Name.c_str(), node->Node.Offset);
             off_t offset = 2; /* 0 . | 1 .. */
             for (auto &child : node->Children)
             {
 #ifdef DEBUG
                 if (offset <= 2)
                 {
                     if (offset == 2)
                         offset = 0;
                     /* Pseudo directories . and .. */
                     USTARInode pseudoDot{};
                     pseudoDot.Node = node->Node;
                     pseudoDot.Name = ".";
                     pseudoDot.Node.Offset = offset++;
                     USTARInode pseudoDDot{};
                     pseudoDDot.Node = node->Parent ? node->Parent->Node : node->Node;
                     pseudoDDot.Name = "..";
                     pseudoDDot.Node.Offset = offset++;
                     ustarTree(&pseudoDot, level + 1, "|-- ");
                     ustarTree(&pseudoDDot, level + 1, "|-- ");
                 }
 #endif
                 child->Node.Offset = offset++;
                 ustarTree(child, level + 1, child == node->Children.back() ? "`-- " : "|-- ");
             }
         };
         ustarTree(tmpNodes[0], 0, "");
     }
References __fallthrough, Address, AREGTYPE, basename(), BLKTYPE, Memory::Virtual::Check(), child(), vfs::USTAR::USTARInode::Children, CHRTYPE, CONTTYPE, cwk_path_get_basename(), cwk_path_get_dirname(), debug, Inode::Device, DeviceID, DIRTYPE, error, FIFOTYPE, file, Files, vfs::fixme(), Inode::Flags, GetSize(), i, I_FLAG_CACHE_KEEP, Inode::Index, INODE_CHECKSUM, isempty(), LNKTYPE, memmove, vfs::USTAR::FileHeader::mode, Inode::Mode, mode_t, vfs::USTAR::FileHeader::name, NextInode, vfs::USTAR::USTARInode::Node, off_t, Inode::Offset, FileNode::Parent, FileNode::Path, Inode::PrivateData, Inode::RawDevice, REGTYPE, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFREG, S_IRGRP, S_IROTH, S_IRUSR, S_ISGID, S_ISUID, S_ISVTX, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, S_IXUSR, vfs::USTAR::FileHeader::signature, size, vfs::USTAR::FileHeader::size, vfs::Size, StringToInt(), strlen, strncmp(), SYMTYPE, TGEXEC, TGREAD, TGWRITE, TMAGIC, TMAGLEN, TOEXEC, TOREAD, TOWRITE, trace, TSGID, TSUID, TSVTX, TUEXEC, TUREAD, TUWRITE, and warn.
Referenced by TestAndInitializeUSTAR().
ReadDir()
ssize_t vfs::USTAR::ReadDir (struct Inode * Node, struct kdirent * Buffer, size_t Size, off_t Offset, off_t Entries)
ReadLink()
ssize_t vfs::USTAR::ReadLink (struct Inode * Node, char * Buffer, size_t Size)
Definition at line 378 of file ustar.cpp.
     {
         auto fileItr = Files.find(Node->Index);
         assert(fileItr != Files.end());
         if (fileItr->second->Deleted)
             return -ENOENT;
         USTARInode *node = fileItr->second;
         if (strlen(node->Header->link) > Size)
             Size = strlen(node->Header->link);
         strncpy(Buffer, node->Header->link, Size);
         debug("Read %d bytes from %d", Size, Node->Index);
         return Size;
     }
References assert, vfs::Buffer, debug, ENOENT, Files, vfs::Node, vfs::Size, strlen, and strncpy().
Stat()
int vfs::USTAR::Stat (struct Inode * Node, struct kstat * Stat)
Definition at line 396 of file ustar.cpp.
     {
         auto fileItr = Files.find(Node->Index);
         assert(fileItr != Files.end());
         if (fileItr->second->Deleted)
             return -ENOENT;
         USTARInode *node = fileItr->second;
         size_t fileSize = GetSize(node->Header->size);
         debug("Header: \"%.*s\"", sizeof(struct FileHeader), node->Header);
         Stat->Device = this->DeviceID;
         Stat->Index = Node->Index;
         Stat->HardLinks = 1;
         Stat->UserID = GetSize(node->Header->uid);
         Stat->GroupID = GetSize(node->Header->gid);
         Stat->RawDevice = Stat->MakeDevice(GetSize(node->Header->dev_maj), GetSize(node->Header->dev_min));
         Stat->Size = fileSize;
         Stat->AccessTime = GetSize(node->Header->mtime);
         Stat->ModifyTime = GetSize(node->Header->mtime);
         Stat->ChangeTime = GetSize(node->Header->mtime);
         Stat->BlockSize = 512;
         Stat->Blocks = (fileSize + 511) / 512;
         Stat->Attribute = 0;
         mode_t hdrMode = StringToInt(node->Header->mode);
         if (hdrMode & TSUID)
             Stat->Mode |= S_ISUID;
         else if (hdrMode & TSGID)
             Stat->Mode |= S_ISGID;
         else if (hdrMode & TSVTX)
             Stat->Mode |= S_ISVTX;
         else if (hdrMode & TUREAD)
             Stat->Mode |= S_IRUSR;
         else if (hdrMode & TUWRITE)
             Stat->Mode |= S_IWUSR;
         else if (hdrMode & TUEXEC)
             Stat->Mode |= S_IXUSR;
         else if (hdrMode & TGREAD)
             Stat->Mode |= S_IRGRP;
         else if (hdrMode & TGWRITE)
             Stat->Mode |= S_IWGRP;
         else if (hdrMode & TGEXEC)
             Stat->Mode |= S_IXGRP;
         else if (hdrMode & TOREAD)
             Stat->Mode |= S_IROTH;
         else if (hdrMode & TOWRITE)
             Stat->Mode |= S_IWOTH;
         else if (hdrMode & TOEXEC)
             Stat->Mode |= S_IXOTH;
         switch (node->Header->typeflag[0])
         {
         case AREGTYPE:
         case REGTYPE:
             Stat->Mode |= S_IFREG;
             break;
         case LNKTYPE:
             fixme("Hard link not implemented for %s", node->Header->name);
             Stat->Mode |= S_IFLNK;
             break;
         case SYMTYPE:
             Stat->Mode |= S_IFLNK;
             break;
         case CHRTYPE:
             Stat->Mode |= S_IFCHR;
             break;
         case BLKTYPE:
             Stat->Mode |= S_IFBLK;
             break;
         case DIRTYPE:
             Stat->Mode |= S_IFDIR;
             break;
         case FIFOTYPE:
             Stat->Mode |= S_IFIFO;
             break;
         case CONTTYPE:
             warn("Reserved type for %s", node->Header->name);
             __fallthrough;
         default:
             error("Unknown type: %d for %s", node->Header->typeflag[0], node->Header->name);
             break;
         }
         return 0;
     }
References __fallthrough, AREGTYPE, assert, BLKTYPE, CHRTYPE, CONTTYPE, debug, DeviceID, DIRTYPE, ENOENT, error, FIFOTYPE, Files, vfs::fixme(), GetSize(), kstat::Index, LNKTYPE, mode_t, vfs::Node, REGTYPE, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFREG, S_IRGRP, S_IROTH, S_IRUSR, S_ISGID, S_ISUID, S_ISVTX, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, S_IXUSR, StringToInt(), SYMTYPE, TGEXEC, TGREAD, TGWRITE, TOEXEC, TOREAD, TOWRITE, TSGID, TSUID, TSVTX, TUEXEC, TUREAD, TUWRITE, and warn.
StringToInt()
int vfs::USTAR::StringToInt (const char * String) inline private
Definition at line 107 of file ustar.hpp.
         {
             int ret = 0;
             for (int i = 0; String[i] != '\0'; ++i)
                 ret = ret * 10 + String[i] - '0';
             return ret;
         }
References i, and ret.
Referenced by ReadArchive(), and Stat().
SymLink()
int vfs::USTAR::SymLink (struct Inode * Node, const char * Name, const char * Target, struct Inode ** Result)
Definition at line 366 of file ustar.cpp.
     {
         int ret = this->Create(Node, Name, S_IFLNK, Result);
         if (ret < 0)
             return ret;
         USTARInode *node = (USTARInode *)*Result;
         FileHeader *hdr = node->Header;
         strncpy(hdr->link, Target, MIN(sizeof(hdr->link) - 1, strlen(Target)));
         return 0;
     }
References Create(), vfs::USTAR::FileHeader::link, MIN, Name, ret, S_IFLNK, strlen, and strncpy().
TestArchive()
bool vfs::USTAR::TestArchive (uintptr_t Address)
Definition at line 483 of file ustar.cpp.
     {
         if (!Memory::Virtual().Check((void *)Address))
         {
             error("Address %#lx is not mapped!", Address);
             return false;
         }
         FileHeader *header = (FileHeader *)Address;
         if (strncmp(header->signature, TMAGIC, TMAGLEN) != 0)
         {
             error("Invalid signature!");
             return false;
         }
         return true;
     }
References Address, CPU::Check, error, vfs::USTAR::FileHeader::signature, strncmp(), TMAGIC, and TMAGLEN.
Referenced by TestAndInitializeUSTAR().
Field Documentation
DeviceID
dev_t vfs::USTAR::DeviceID = -1
Definition at line 116 of file ustar.hpp.
Referenced by Create(), ReadArchive(), Stat(), and TestAndInitializeUSTAR().
Files
std::unordered_map<ino_t, USTARInode *> vfs::USTAR::Files private
Definition at line 93 of file ustar.hpp.
Referenced by Create(), Lookup(), Read(), ReadArchive(), ReadLink(), and Stat().
INODE_CHECKSUM
constexpr static int vfs::USTAR::INODE_CHECKSUM = 0x7757A4 static constexpr
Definition at line 78 of file ustar.hpp.
Referenced by Create(), and ReadArchive().
NextInode
ino_t vfs::USTAR::NextInode = 0
Definition at line 117 of file ustar.hpp.
Referenced by Create(), and ReadArchive().
The documentation for this class was generated from the following files:
Kernel/include/filesystem/ustar.hpp
Kernel/storage/fs/ustar.cpp