Fennix Userspace: Userspace/apps/base/busybox/networking/httpd.c File Reference
httpd.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct has_next_ptr
struct Htaccess
struct Htaccess_Proxy
struct globals
Macros
#define DEBUG 0
#define dbg(...) ((void)0)
#define IOBUF_SIZE 8192
#define MAX_HTTP_HEADERS_SIZE (32*1024)
#define HEADER_READ_TIMEOUT 60
#define STR1(s) #s
#define STR(s) STR1(s)
#define hdr_buf bb_common_bufsiz1
#define sizeof_hdr_buf COMMON_BUFSIZE
#define G (*ptr_to_globals)
#define verbose (G.verbose)
#define flg_deny_all (G.flg_deny_all)
#define content_gzip 0
#define bind_addr_or_port (G.bind_addr_or_port)
#define g_query (G.g_query)
#define opt_c_configFile (G.opt_c_configFile)
#define home_httpd (G.home_httpd)
#define index_page (G.index_page)
#define found_mime_type (G.found_mime_type)
#define found_moved_temporarily (G.found_moved_temporarily)
#define last_mod (G.last_mod)
#define g_realm (G.g_realm)
#define remoteuser (G.remoteuser)
#define file_size (G.file_size)
#define rmt_ip_str (G.rmt_ip_str)
#define g_auth (G.g_auth)
#define mime_a (G.mime_a)
#define script_i (G.script_i)
#define iobuf (G.iobuf)
#define hdr_ptr (G.hdr_ptr)
#define hdr_cnt (G.hdr_cnt)
#define http_error_page (G.http_error_page)
#define proxy (G.proxy)
#define INIT_G()
#define STRNCASECMP(a, str) strncasecmp((a), (str), sizeof(str)-1)
#define if_ip_denied_send_HTTP_FORBIDDEN_and_exit(arg) ((void)0)
Typedefs
typedef struct has_next_ptr has_next_ptr
typedef struct Htaccess Htaccess
typedef struct Htaccess_Proxy Htaccess_Proxy
Enumerations
enum {
HTTP_OK = 200 , HTTP_PARTIAL_CONTENT = 206 , HTTP_MOVED_TEMPORARILY = 302 , HTTP_NOT_MODIFIED = 304 ,
HTTP_BAD_REQUEST = 400 , HTTP_UNAUTHORIZED = 401 , HTTP_NOT_FOUND = 404 , HTTP_FORBIDDEN = 403 ,
HTTP_REQUEST_TIMEOUT = 408 , HTTP_NOT_IMPLEMENTED = 501 , HTTP_INTERNAL_SERVER_ERROR = 500 , HTTP_ENTITY_TOO_LARGE = 413 ,
HTTP_CONTINUE = 100
}
enum { range_start = -1 , range_end = MAXINT(off_t) - 1 , range_len = MAXINT(off_t) }
enum { SEND_HEADERS = (1 << 0) , SEND_BODY = (1 << 1) }
enum { FIRST_PARSE = 0 , SIGNALED_PARSE = 1 , SUBDIR_PARSE = 2 }
enum {
c_opt_config_file = 0 , d_opt_decode_url , h_opt_home_httpd , p_opt_port ,
p_opt_inetd , p_opt_foreground , p_opt_verbose , OPT_CONFIG_FILE = 1 << c_opt_config_file ,
OPT_DECODE_URL = 1 << d_opt_decode_url , OPT_HOME_HTTPD = 1 << h_opt_home_httpd , OPT_ENCODE_URL = IF_FEATURE_HTTPD_ENCODE_URL_STR((1 << e_opt_encode_url)) + 0 , OPT_REALM = IF_FEATURE_HTTPD_BASIC_AUTH((1 << r_opt_realm)) + 0 ,
OPT_MD5 = IF_FEATURE_HTTPD_AUTH_MD5((1 << m_opt_md5)) + 0 , OPT_SETUID = IF_FEATURE_HTTPD_SETUID((1 << u_opt_setuid)) + 0 , OPT_PORT = 1 << p_opt_port , OPT_INETD = 1 << p_opt_inetd ,
OPT_FOREGROUND = 1 << p_opt_foreground , OPT_VERBOSE = 1 << p_opt_verbose
}
Functions
static void send_file_and_exit (const char *url, int what) NORETURN
static void free_llist (has_next_ptr **pptr)
static ALWAYS_INLINE void free_Htaccess_list (Htaccess **pptr)
static int parse_conf (const char *path, int flag)
static int openServer (void)
static void log_and_exit (void)
static void send_headers (unsigned responseNum)
static void send_headers_and_exit (int responseNum) NORETURN
static unsigned get_line (void)
static void send_REQUEST_TIMEOUT_and_exit (int sig) NORETURN
static void handle_incoming_and_exit (const len_and_sockaddr *fromAddr) NORETURN
static void mini_httpd_nommu (int server_socket, int argc, char **argv) NORETURN
static void mini_httpd_inetd (void)
static void sighup_handler (int sig UNUSED_PARAM)
int httpd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char DEFAULT_PATH_HTTPD_CONF[] ALIGN1 = "/etc"
static const uint16_t http_response_type[] ALIGN2
struct {
const char * name
const char * info
} http_response [ARRAY_SIZE(http_response_type)]
Data Structure Documentation
has_next_ptr
struct has_next_ptr
Definition at line 333 of file httpd.c.
Data Fields
struct has_next_ptr * next
Htaccess
struct Htaccess
Definition at line 338 of file httpd.c.
Data Fields
char * after_colon
char before_colon[1]
struct Htaccess * next
Htaccess_Proxy
struct Htaccess_Proxy
Definition at line 355 of file httpd.c.
Data Fields
char * host_port
struct Htaccess_Proxy * next
char * url_from
char * url_to
Macro Definition Documentation
bind_addr_or_port
#define bind_addr_or_port (G.bind_addr_or_port)
Definition at line 518 of file httpd.c.
content_gzip
#define content_gzip 0
Definition at line 516 of file httpd.c.
dbg
#define dbg (...) ((void)0)
Definition at line 317 of file httpd.c.
DEBUG
#define DEBUG 0
Definition at line 312 of file httpd.c.
file_size
#define file_size (G.file_size)
Definition at line 528 of file httpd.c.
flg_deny_all
#define flg_deny_all (G.flg_deny_all)
Definition at line 512 of file httpd.c.
found_mime_type
#define found_mime_type (G.found_mime_type)
Definition at line 523 of file httpd.c.
found_moved_temporarily
#define found_moved_temporarily (G.found_moved_temporarily)
Definition at line 524 of file httpd.c.
G
#define G (*ptr_to_globals)
Definition at line 510 of file httpd.c.
g_auth
#define g_auth (G.g_auth)
Definition at line 541 of file httpd.c.
g_query
#define g_query (G.g_query)
Definition at line 519 of file httpd.c.
g_realm
#define g_realm (G.g_realm)
Definition at line 526 of file httpd.c.
hdr_buf
#define hdr_buf bb_common_bufsiz1
Definition at line 496 of file httpd.c.
hdr_cnt
#define hdr_cnt (G.hdr_cnt)
Definition at line 546 of file httpd.c.
hdr_ptr
#define hdr_ptr (G.hdr_ptr)
Definition at line 545 of file httpd.c.
HEADER_READ_TIMEOUT
#define HEADER_READ_TIMEOUT 60
Definition at line 323 of file httpd.c.
home_httpd
#define home_httpd (G.home_httpd)
Definition at line 521 of file httpd.c.
http_error_page
#define http_error_page (G.http_error_page)
Definition at line 547 of file httpd.c.
if_ip_denied_send_HTTP_FORBIDDEN_and_exit
#define if_ip_denied_send_HTTP_FORBIDDEN_and_exit (arg) ((void)0)
Definition at line 1951 of file httpd.c.
index_page
#define index_page (G.index_page)
Definition at line 522 of file httpd.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    IF_FEATURE_HTTPD_BASIC_AUTH(g_realm = "Web Server Authentication";) \
    IF_FEATURE_HTTPD_RANGES(range_start = -1;) \
    bind_addr_or_port = STR(CONFIG_FEATURE_HTTPD_PORT_DEFAULT); \
    index_page = index_html; \
    file_size = -1; \
} while (0)
Definition at line 549 of file httpd.c.
iobuf
#define iobuf (G.iobuf)
Definition at line 544 of file httpd.c.
IOBUF_SIZE
#define IOBUF_SIZE 8192
Definition at line 320 of file httpd.c.
last_mod
#define last_mod (G.last_mod)
Definition at line 525 of file httpd.c.
MAX_HTTP_HEADERS_SIZE
#define MAX_HTTP_HEADERS_SIZE (32*1024)
Definition at line 321 of file httpd.c.
mime_a
#define mime_a (G.mime_a)
Definition at line 542 of file httpd.c.
opt_c_configFile
#define opt_c_configFile (G.opt_c_configFile)
Definition at line 520 of file httpd.c.
proxy
#define proxy (G.proxy)
Definition at line 548 of file httpd.c.
remoteuser
#define remoteuser (G.remoteuser)
Definition at line 527 of file httpd.c.
rmt_ip_str
#define rmt_ip_str (G.rmt_ip_str)
Definition at line 540 of file httpd.c.
script_i
#define script_i (G.script_i)
Definition at line 543 of file httpd.c.
sizeof_hdr_buf
#define sizeof_hdr_buf COMMON_BUFSIZE
Definition at line 497 of file httpd.c.
STR
#define STR (s) STR1(s)
Definition at line 326 of file httpd.c.
STR1
#define STR1 (s) #s
Definition at line 325 of file httpd.c.
STRNCASECMP
#define STRNCASECMP (a, str) strncasecmp((a), (str), sizeof(str)-1)
Definition at line 560 of file httpd.c.
verbose
#define verbose (G.verbose)
Definition at line 511 of file httpd.c.
Typedef Documentation
has_next_ptr
typedef struct has_next_ptr has_next_ptr
Htaccess
typedef struct Htaccess Htaccess
Htaccess_Proxy
typedef struct Htaccess_Proxy Htaccess_Proxy
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HTTP_OK
HTTP_PARTIAL_CONTENT
HTTP_MOVED_TEMPORARILY
HTTP_NOT_MODIFIED
HTTP_BAD_REQUEST
HTTP_UNAUTHORIZED
HTTP_NOT_FOUND
HTTP_FORBIDDEN
HTTP_REQUEST_TIMEOUT
HTTP_NOT_IMPLEMENTED
HTTP_INTERNAL_SERVER_ERROR
HTTP_ENTITY_TOO_LARGE
HTTP_CONTINUE
Definition at line 362 of file httpd.c.
      {
     HTTP_OK = 200,
     HTTP_PARTIAL_CONTENT = 206,
     HTTP_MOVED_TEMPORARILY = 302,
     HTTP_NOT_MODIFIED = 304,
     HTTP_BAD_REQUEST = 400,       /* malformed syntax */
     HTTP_UNAUTHORIZED = 401, /* authentication needed, respond with auth hdr */
     HTTP_NOT_FOUND = 404,
     HTTP_FORBIDDEN = 403,
     HTTP_REQUEST_TIMEOUT = 408,
     HTTP_NOT_IMPLEMENTED = 501,   /* used for unrecognized requests */
     HTTP_INTERNAL_SERVER_ERROR = 500,
     HTTP_ENTITY_TOO_LARGE = 413,
     HTTP_CONTINUE = 100,
 #if 0   /* future use */
     HTTP_SWITCHING_PROTOCOLS = 101,
     HTTP_CREATED = 201,
     HTTP_ACCEPTED = 202,
     HTTP_NON_AUTHORITATIVE_INFO = 203,
     HTTP_NO_CONTENT = 204,
     HTTP_MULTIPLE_CHOICES = 300,
     HTTP_MOVED_PERMANENTLY = 301,
     HTTP_PAYMENT_REQUIRED = 402,
     HTTP_BAD_GATEWAY = 502,
     HTTP_SERVICE_UNAVAILABLE = 503, /* overload, maintenance */
 #endif
 };
anonymous enum
anonymous enum
Enumerator
range_start
range_end
range_len
Definition at line 534 of file httpd.c.
      {
     range_start = -1,
     range_end = MAXINT(off_t) - 1,
     range_len = MAXINT(off_t),
 };
anonymous enum
anonymous enum
Enumerator
SEND_HEADERS
SEND_BODY
Definition at line 563 of file httpd.c.
      {
     SEND_HEADERS     = (1 << 0),
     SEND_BODY        = (1 << 1),
 };
anonymous enum
anonymous enum
Enumerator
FIRST_PARSE
SIGNALED_PARSE
SUBDIR_PARSE
Definition at line 692 of file httpd.c.
      {
     FIRST_PARSE    = 0, /* path will be "/etc" */
     SIGNALED_PARSE = 1, /* path will be "/etc" */
     SUBDIR_PARSE   = 2, /* path will be derived from URL */
 };
anonymous enum
anonymous enum
Enumerator
c_opt_config_file
d_opt_decode_url
h_opt_home_httpd
p_opt_port
p_opt_inetd
p_opt_foreground
p_opt_verbose
OPT_CONFIG_FILE
OPT_DECODE_URL
OPT_HOME_HTTPD
OPT_ENCODE_URL
OPT_REALM
OPT_MD5
OPT_SETUID
OPT_PORT
OPT_INETD
OPT_FOREGROUND
OPT_VERBOSE
Definition at line 2745 of file httpd.c.
      {
     c_opt_config_file = 0,
     d_opt_decode_url,
     h_opt_home_httpd,
     IF_FEATURE_HTTPD_ENCODE_URL_STR(e_opt_encode_url,)
     IF_FEATURE_HTTPD_BASIC_AUTH(    r_opt_realm     ,)
     IF_FEATURE_HTTPD_AUTH_MD5(      m_opt_md5       ,)
     IF_FEATURE_HTTPD_SETUID(        u_opt_setuid    ,)
     p_opt_port      ,
     p_opt_inetd     ,
     p_opt_foreground,
     p_opt_verbose   ,
     OPT_CONFIG_FILE = 1 << c_opt_config_file,
     OPT_DECODE_URL  = 1 << d_opt_decode_url,
     OPT_HOME_HTTPD  = 1 << h_opt_home_httpd,
     OPT_ENCODE_URL  = IF_FEATURE_HTTPD_ENCODE_URL_STR((1 << e_opt_encode_url)) + 0,
     OPT_REALM       = IF_FEATURE_HTTPD_BASIC_AUTH(    (1 << r_opt_realm     )) + 0,
     OPT_MD5         = IF_FEATURE_HTTPD_AUTH_MD5(      (1 << m_opt_md5       )) + 0,
     OPT_SETUID      = IF_FEATURE_HTTPD_SETUID(        (1 << u_opt_setuid    )) + 0,
     OPT_PORT        = 1 << p_opt_port,
     OPT_INETD       = 1 << p_opt_inetd,
     OPT_FOREGROUND  = 1 << p_opt_foreground,
     OPT_VERBOSE     = 1 << p_opt_verbose,
 };
Function Documentation
free_Htaccess_list()
static ALWAYS_INLINE void free_Htaccess_list (Htaccess ** pptr) static
Definition at line 580 of file httpd.c.
 {
     free_llist((has_next_ptr**)pptr);
 }
References free_llist().
Referenced by parse_conf().
free_llist()
static void free_llist (has_next_ptr ** pptr) static
Definition at line 569 of file httpd.c.
 {
     has_next_ptr *cur = *pptr;
     while (cur) {
         has_next_ptr *t = cur;
         cur = cur->next;
         free(t);
     }
     *pptr = NULL;
 }
References cur, free, NULL, and t.
Referenced by free_Htaccess_list().
get_line()
static unsigned get_line (void) static
Definition at line 1306 of file httpd.c.
 {
     unsigned count;
     char c;
     count = 0;
     while (1) {
         if (hdr_cnt <= 0) {
             alarm(HEADER_READ_TIMEOUT);
             hdr_cnt = safe_read(STDIN_FILENO, hdr_buf, sizeof_hdr_buf);
             if (hdr_cnt <= 0)
                 goto ret;
             hdr_ptr = hdr_buf;
         }
         hdr_cnt--;
         c = *hdr_ptr++;
         if (c == '\r')
             continue;
         if (c == '\n')
             break;
         iobuf[count] = c;
         if (count < (IOBUF_SIZE - 1))      /* check overflow */
             count++;
     }
  ret:
     iobuf[count] = '\0';
     return count;
 }
References alarm(), c, count, hdr_buf, hdr_cnt, hdr_ptr, HEADER_READ_TIMEOUT, iobuf, IOBUF_SIZE, safe_read(), sizeof_hdr_buf, and STDIN_FILENO.
Referenced by handle_incoming_and_exit().
handle_incoming_and_exit()
static void handle_incoming_and_exit (const len_and_sockaddr * fromAddr) static
Definition at line 2180 of file httpd.c.
 {
     struct stat sb;
     char *urlcopy;
     char *urlp;
     char *tptr;
 #if ENABLE_FEATURE_HTTPD_ACL_IP
     unsigned remote_ip;
 #endif
 #if ENABLE_FEATURE_HTTPD_CGI
     unsigned total_headers_len;
 #endif
     const char *prequest;
     static const char request_GET[]  ALIGN1 = "GET";
     static const char request_HEAD[] ALIGN1 = "HEAD";
 #if ENABLE_FEATURE_HTTPD_CGI
     static const char request_POST[] ALIGN1 = "POST";
     unsigned long POST_length;
     enum CGI_type {
         CGI_NONE = 0,
         CGI_NORMAL,
         CGI_INDEX,
         CGI_INTERPRETER,
     } cgi_type = CGI_NONE;
 #endif
 #if ENABLE_FEATURE_HTTPD_PROXY
     Htaccess_Proxy *proxy_entry;
 #endif
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
     smallint authorized = -1;
 #endif
     char *HTTP_slash;
     /* Allocation of iobuf is postponed until now
      * (IOW, server process doesn't need to waste 8k) */
     iobuf = xmalloc(IOBUF_SIZE);
     if (ENABLE_FEATURE_HTTPD_CGI || DEBUG || verbose) {
         /* NB: can be NULL (user runs httpd -i by hand?) */
         rmt_ip_str = xmalloc_sockaddr2dotted(&fromAddr->u.sa);
     }
     if (verbose) {
         /* this trick makes -v logging much simpler */
         if (rmt_ip_str)
             applet_name = rmt_ip_str;
         if (verbose > 2)
             bb_simple_error_msg("connected");
     }
 #if ENABLE_FEATURE_HTTPD_ACL_IP
     remote_ip = 0;
     if (fromAddr->u.sa.sa_family == AF_INET) {
         remote_ip = ntohl(fromAddr->u.sin.sin_addr.s_addr);
     }
 # if ENABLE_FEATURE_IPV6
     if (fromAddr->u.sa.sa_family == AF_INET6
      && fromAddr->u.sin6.sin6_addr.s6_addr32[0] == 0
      && fromAddr->u.sin6.sin6_addr.s6_addr32[1] == 0
      && ntohl(fromAddr->u.sin6.sin6_addr.s6_addr32[2]) == 0xffff)
         remote_ip = ntohl(fromAddr->u.sin6.sin6_addr.s6_addr32[3]);
 # endif
     if_ip_denied_send_HTTP_FORBIDDEN_and_exit(remote_ip);
 #endif
     /* Install timeout handler. get_line() needs it. */
     signal(SIGALRM, send_REQUEST_TIMEOUT_and_exit);
     if (!get_line()) { /* EOF or error or empty line */
         /* Observed Firefox to "speculatively" open
          * extra connections to a new site on first access,
          * they are closed in ~5 seconds with nothing
          * being sent at all.
          * (Presumably it's a method to decrease latency?)
          */
         if (verbose > 2)
             bb_simple_error_msg("eof on read, closing");
         /* Don't bother generating error page in this case,
          * just close the socket.
          */
         //send_headers_and_exit(HTTP_BAD_REQUEST);
         _exit(xfunc_error_retval);
     }
     dbg("Request:'%s'\n", iobuf);
     /* Find URL */
     // rfc2616: method and URI is separated by exactly one space
     //urlp = strpbrk(iobuf, " \t"); - no, tab isn't allowed
     urlp = strchr(iobuf, ' ');
     if (urlp == NULL)
         send_headers_and_exit(HTTP_BAD_REQUEST);
     *urlp++ = '\0';
     //urlp = skip_whitespace(urlp); - should not be necessary
     if (urlp[0] != '/')
         send_headers_and_exit(HTTP_BAD_REQUEST);
     /* Find end of URL */
     HTTP_slash = strchr(urlp, ' ');
     /* Is it " HTTP/"? */
     if (!HTTP_slash || strncmp(HTTP_slash + 1, HTTP_200, 5) != 0)
         send_headers_and_exit(HTTP_BAD_REQUEST);
     *HTTP_slash++ = '\0';
 #if ENABLE_FEATURE_HTTPD_PROXY
     proxy_entry = find_proxy_entry(urlp);
     if (proxy_entry) {
         int proxy_fd;
         len_and_sockaddr *lsa;
         if (verbose > 1)
             bb_error_msg("proxy:%s", urlp);
         lsa = host2sockaddr(proxy_entry->host_port, 80);
         if (!lsa)
             send_headers_and_exit(HTTP_INTERNAL_SERVER_ERROR);
         proxy_fd = socket(lsa->u.sa.sa_family, SOCK_STREAM, 0);
         if (proxy_fd < 0)
             send_headers_and_exit(HTTP_INTERNAL_SERVER_ERROR);
         if (connect(proxy_fd, &lsa->u.sa, lsa->len) < 0)
             send_headers_and_exit(HTTP_INTERNAL_SERVER_ERROR);
         /* Disable peer header reading timeout */
         alarm(0);
         /* Config directive was of the form:
          *   P:/url:[http://]hostname[:port]/new/path
          * When /urlSFX is requested, reverse proxy it
          * to http://hostname[:port]/new/pathSFX
          */
         fdprintf(proxy_fd, "%s %s%s %s\r\n",
                 iobuf, /* "GET" / "POST" / etc */
                 proxy_entry->url_to, /* "/new/path" */
                 urlp + strlen(proxy_entry->url_from), /* "SFX" */
                 HTTP_slash /* "HTTP/xyz" */
         );
         cgi_io_loop_and_exit(proxy_fd, proxy_fd, /*max POST length:*/ INT_MAX);
     }
 #endif
     /* Determine type of request (GET/POST/...) */
     prequest = request_GET;
     if (strcasecmp(iobuf, prequest) == 0)
         goto found;
     prequest = request_HEAD;
     if (strcasecmp(iobuf, prequest) == 0)
         goto found;
 #if !ENABLE_FEATURE_HTTPD_CGI
     send_headers_and_exit(HTTP_NOT_IMPLEMENTED);
 #else
     prequest = request_POST;
     if (strcasecmp(iobuf, prequest) == 0)
         goto found;
     /* For CGI, allow DELETE, PUT, OPTIONS, etc too */
     prequest = alloca(16);
     safe_strncpy((char*)prequest, iobuf, 16);
 #endif
  found:
     /* Copy URL to stack-allocated char[] */
     urlcopy = alloca((HTTP_slash - urlp) + 2 + strlen(index_page));
     strcpy(urlcopy, urlp);
     /* NB: urlcopy ptr is never changed after this */
     /* Extract url args if present */
     g_query = strchr(urlcopy, '?');
     if (g_query)
         *g_query++ = '\0';
     /* Decode URL escape sequences */
     tptr = percent_decode_in_place(urlcopy, /*strict:*/ 1);
     if (tptr == NULL)
         send_headers_and_exit(HTTP_BAD_REQUEST);
     if (tptr == urlcopy + 1) {
         /* '/' or NUL is encoded */
         send_headers_and_exit(HTTP_NOT_FOUND);
     }
     /* Canonicalize path */
     /* Algorithm stolen from libbb bb_simplify_path(),
      * but don't strdup, retain trailing slash, protect root */
     urlp = tptr = urlcopy;
     while (1) {
         if (*urlp == '/') {
             /* skip duplicate (or initial) slash */
             if (*tptr == '/') {
                 goto next_char;
             }
             if (*tptr == '.') {
                 if (tptr[1] == '.' && (tptr[2] == '/' || tptr[2] == '\0')) {
                     /* "..": be careful */
                     /* protect root */
                     if (urlp == urlcopy)
                         send_headers_and_exit(HTTP_BAD_REQUEST);
                     /* omit previous dir */
                     while (*--urlp != '/')
                         continue;
                     /* skip to "./" or ".<NUL>" */
                     tptr++;
                 }
                 if (tptr[1] == '/' || tptr[1] == '\0') {
                     /* skip extra "/./" */
                     goto next_char;
                 }
             }
         }
         *++urlp = *tptr;
         if (*tptr == '\0')
             break;
  next_char:
         tptr++;
     }
     /* Log it */
     if (verbose > 1)
         bb_error_msg("url:%s", urlcopy);
     tptr = urlcopy;
     while ((tptr = strchr(tptr + 1, '/')) != NULL) {
         /* have path1/path2 */
         *tptr = '\0';
         /* may have subdir config */
         if (parse_conf(urlcopy + 1, SUBDIR_PARSE) == 0)
             if_ip_denied_send_HTTP_FORBIDDEN_and_exit(remote_ip);
         *tptr = '/';
     }
     tptr = urlcopy + 1;      /* skip first '/' */
 #if ENABLE_FEATURE_HTTPD_CGI
     if (is_prefixed_with(tptr, "cgi-bin/")) {
         if (tptr[8] == '\0') {
             /* protect listing "cgi-bin/" */
             send_headers_and_exit(HTTP_FORBIDDEN);
         }
         cgi_type = CGI_NORMAL;
     }
 #endif
     if (urlp[-1] == '/') {
         /* When index_page string is appended to <dir>/ URL, it overwrites
          * the query string. If we fall back to call /cgi-bin/index.cgi,
          * query string would be lost and not available to the CGI.
          * Work around it by making a deep copy.
          */
         if (ENABLE_FEATURE_HTTPD_CGI)
             g_query = xstrdup(g_query); /* ok for NULL too */
         strcpy(urlp, index_page);
     }
     if (stat(tptr, &sb) == 0) {
         /* If URL is a directory with no slash, set up
          * "HTTP/1.1 302 Found" "Location: /dir/" reply */
         if (urlp[-1] != '/' && S_ISDIR(sb.st_mode)) {
             found_moved_temporarily = urlcopy;
         } else {
 #if ENABLE_FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR
             char *suffix = strrchr(tptr, '.');
             if (suffix) {
                 Htaccess *cur;
                 for (cur = script_i; cur; cur = cur->next) {
                     if (strcmp(cur->before_colon + 1, suffix) == 0) {
                         cgi_type = CGI_INTERPRETER;
                         break;
                     }
                 }
             }
 #endif
             file_size = sb.st_size;
             last_mod = sb.st_mtime;
         }
     }
 #if ENABLE_FEATURE_HTTPD_CGI
     else if (urlp[-1] == '/') {
         /* It's a dir URL and there is no index.html */
         /* Is there cgi-bin/index.cgi? */
         if (access("/cgi-bin/index.cgi"+1, X_OK) != 0)
             send_headers_and_exit(HTTP_NOT_FOUND); /* no */
         cgi_type = CGI_INDEX;
     }
 #endif
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH || ENABLE_FEATURE_HTTPD_CGI
     /* check_user_passwd() would be confused by added .../index.html, truncate it */
     urlp[0] = '\0';
 #endif
 #if ENABLE_FEATURE_HTTPD_CGI
     total_headers_len = 0;
     POST_length = 0;
 #endif
     /* Read until blank line */
     while (1) {
         unsigned iobuf_len = get_line();
         if (!iobuf_len)
             break; /* EOF or error or empty line */
 #if ENABLE_FEATURE_HTTPD_CGI
         /* Prevent unlimited growth of HTTP_xyz envvars */
         total_headers_len += iobuf_len;
         if (total_headers_len >= MAX_HTTP_HEADERS_SIZE)
             send_headers_and_exit(HTTP_ENTITY_TOO_LARGE);
 #endif
         dbg("header:'%s'\n", iobuf);
 #if ENABLE_FEATURE_HTTPD_CGI
         /* Only POST needs to know POST_length */
         if (prequest == request_POST && STRNCASECMP(iobuf, "Content-Length:") == 0) {
             tptr = skip_whitespace(iobuf + sizeof("Content-Length:") - 1);
             if (!tptr[0])
                 send_headers_and_exit(HTTP_BAD_REQUEST);
             /* not using strtoul: it ignores leading minus! */
             POST_length = bb_strtou(tptr, NULL, 10);
             /* length is "ulong", but we need to pass it to int later */
             if (errno || POST_length > INT_MAX)
                 send_headers_and_exit(HTTP_BAD_REQUEST);
             continue;
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
         if (STRNCASECMP(iobuf, "Authorization:") == 0) {
             /* We only allow Basic credentials.
              * It shows up as "Authorization: Basic <user>:<passwd>" where
              * "<user>:<passwd>" is base64 encoded.
              */
             tptr = skip_whitespace(iobuf + sizeof("Authorization:")-1);
             if (STRNCASECMP(tptr, "Basic") == 0) {
                 tptr += sizeof("Basic")-1;
                 /* decodeBase64() skips whitespace itself */
                 decodeBase64(tptr);
                 authorized = check_user_passwd(urlcopy, tptr);
                 continue;
             }
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_RANGES
         if (STRNCASECMP(iobuf, "Range:") == 0) {
             /* We know only bytes=NNN-[MMM] */
             char *s = skip_whitespace(iobuf + sizeof("Range:")-1);
             s = is_prefixed_with(s, "bytes=");
             if (s) {
                 range_start = BB_STRTOOFF(s, &s, 10);
                 if (s[0] != '-' || range_start < 0) {
                     range_start = -1;
                 } else if (s[1]) {
                     range_end = BB_STRTOOFF(s+1, NULL, 10);
                     if (errno || range_end < range_start)
                         range_start = -1;
                 }
             }
             continue;
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_GZIP
         if (STRNCASECMP(iobuf, "Accept-Encoding:") == 0) {
             /* Note: we do not support "gzip;q=0"
              * method of _disabling_ gzip
              * delivery. No one uses that, though */
             const char *s = strstr(iobuf, "gzip");
             if (s) {
                 // want more thorough checks?
                 //if (s[-1] == ' '
                 // || s[-1] == ','
                 // || s[-1] == ':'
                 //) {
                     content_gzip = 1;
                 //}
             }
             continue;
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_ETAG
         if (STRNCASECMP(iobuf, "If-None-Match:") == 0) {
             free(G.if_none_match);
             G.if_none_match = xstrdup(skip_whitespace(iobuf + sizeof("If-None-Match:") - 1));
             continue;
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_CGI
         if (cgi_type != CGI_NONE) {
             bool ct = (STRNCASECMP(iobuf, "Content-Type:") == 0);
             char *cp;
             char *colon = strchr(iobuf, ':');
             if (!colon)
                 continue;
             cp = iobuf;
             while (cp < colon) {
                 /* a-z => A-Z, not-alnum => _ */
                 char c = (*cp & ~0x20); /* toupper for A-Za-z, undef for others */
                 if ((unsigned)(c - 'A') <= ('Z' - 'A')) {
                     *cp++ = c;
                     continue;
                 }
                 if (!isdigit(*cp))
                     *cp = '_';
                 cp++;
             }
             /* "Content-Type:" gets no HTTP_ prefix, all others do */
             cp = xasprintf(ct ? "HTTP_%.*s=%s" + 5 : "HTTP_%.*s=%s",
                 (int)(colon - iobuf), iobuf,
                 skip_whitespace(colon + 1)
             );
             putenv(cp);
         }
 #endif
     } /* while extra header reading */
     /* We are done reading headers, disable peer timeout */
     alarm(0);
     if (strcmp(bb_basename(urlcopy), HTTPD_CONF) == 0) {
         /* protect listing [/path]/httpd.conf or IP deny */
         send_headers_and_exit(HTTP_FORBIDDEN);
     }
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
     /* Case: no "Authorization:" was seen, but page might require passwd.
      * Check that with dummy user:pass */
     if (authorized < 0)
         authorized = check_user_passwd(urlcopy, (char *) "");
     if (!authorized)
         send_headers_and_exit(HTTP_UNAUTHORIZED);
 #endif
     if (found_moved_temporarily)
         send_headers_and_exit(HTTP_MOVED_TEMPORARILY);
 #if ENABLE_FEATURE_HTTPD_CGI
     if (cgi_type != CGI_NONE) {
         send_cgi_and_exit(
             (cgi_type == CGI_INDEX) ? "/cgi-bin/index.cgi"
             /*CGI_NORMAL or CGI_INTERPRETER*/ : urlcopy,
             urlcopy, prequest, POST_length
         );
     }
 #endif
 #if ENABLE_FEATURE_HTTPD_CGI
     if (prequest != request_GET && prequest != request_HEAD) {
         /* POST / DELETE / PUT / OPTIONS for files do not make sense */
         send_headers_and_exit(HTTP_NOT_IMPLEMENTED);
     }
 #else
     /* !CGI: it can be only GET or HEAD */
 #endif
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
     /* Restore truncated .../index.html */
     if (urlp[-1] == '/')
         urlp[0] = index_page[0];
 #endif
     send_file_and_exit(urlcopy + 1,
         (prequest != request_HEAD ? (SEND_HEADERS + SEND_BODY) : SEND_HEADERS)
     );
 }
References _exit(), access(), AF_INET, AF_INET6, alarm(), ALIGN1, alloca, applet_name, bb_basename(), bb_error_msg(), bb_simple_error_msg(), BB_STRTOOFF, bb_strtou(), c, colon, connect(), content_gzip, cur, dbg, DEBUG, errno, fdprintf, file_size, found, found_moved_temporarily, free, G, g_query, get_line(), host2sockaddr(), Htaccess_Proxy::host_port, HTTP_BAD_REQUEST, HTTP_ENTITY_TOO_LARGE, HTTP_FORBIDDEN, HTTP_INTERNAL_SERVER_ERROR, HTTP_MOVED_TEMPORARILY, HTTP_NOT_FOUND, HTTP_NOT_IMPLEMENTED, HTTP_UNAUTHORIZED, if_ip_denied_send_HTTP_FORBIDDEN_and_exit, index_page, INT_MAX, iobuf, IOBUF_SIZE, is_prefixed_with(), isdigit, last_mod, lsa, MAX_HTTP_HEADERS_SIZE, ntohl(), NULL, parse_conf(), percent_decode_in_place(), putenv(), range_end, range_start, rmt_ip_str, s, S_ISDIR, safe_strncpy(), script_i, SEND_BODY, send_file_and_exit(), SEND_HEADERS, send_headers_and_exit(), send_REQUEST_TIMEOUT_and_exit(), SIGALRM, signal, skip_whitespace(), SOCK_STREAM, socket(), stat::st_mode, stat::st_size, stat(), strcasecmp, strchr(), strcmp, strcpy(), strlen(), STRNCASECMP, strncmp(), strrchr(), strstr(), SUBDIR_PARSE, len_and_sockaddr::u, Htaccess_Proxy::url_from, Htaccess_Proxy::url_to, verbose, X_OK, xasprintf(), xfunc_error_retval, xmalloc, xmalloc_sockaddr2dotted(), and xstrdup().
Referenced by mini_httpd_inetd().
httpd_main()
int httpd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 2772 of file httpd.c.
 {
     int server_socket = server_socket; /* for gcc */
     unsigned opt;
     char *url_for_decode;
     IF_FEATURE_HTTPD_ENCODE_URL_STR(const char *url_for_encode;)
     IF_FEATURE_HTTPD_SETUID(const char *s_ugid = NULL;)
     IF_FEATURE_HTTPD_SETUID(struct bb_uidgid_t ugid;)
     IF_FEATURE_HTTPD_AUTH_MD5(const char *pass;)
     INIT_G();
 #if ENABLE_LOCALE_SUPPORT
     /* Undo busybox.c: we want to speak English in http (dates etc) */
     setlocale(LC_TIME, "C");
 #endif
     home_httpd = xrealloc_getcwd_or_warn(NULL);
     /* We do not "absolutize" path given by -h (home) opt.
      * If user gives relative path in -h,
      * $SCRIPT_FILENAME will not be set. */
     opt = getopt32(argv, "^"
             "c:d:h:"
             IF_FEATURE_HTTPD_ENCODE_URL_STR("e:")
             IF_FEATURE_HTTPD_BASIC_AUTH("r:")
             IF_FEATURE_HTTPD_AUTH_MD5("m:")
             IF_FEATURE_HTTPD_SETUID("u:")
             "p:ifv"
             "\0"
             /* -v counts, -i implies -f */
             "vv:if",
             &opt_c_configFile, &url_for_decode, &home_httpd
             IF_FEATURE_HTTPD_ENCODE_URL_STR(, &url_for_encode)
             IF_FEATURE_HTTPD_BASIC_AUTH(, &g_realm)
             IF_FEATURE_HTTPD_AUTH_MD5(, &pass)
             IF_FEATURE_HTTPD_SETUID(, &s_ugid)
             , &bind_addr_or_port
             , &verbose
         );
     if (opt & OPT_DECODE_URL) {
         fputs_stdout(percent_decode_in_place(url_for_decode, /*strict:*/ 0));
         return 0;
     }
 #if ENABLE_FEATURE_HTTPD_ENCODE_URL_STR
     if (opt & OPT_ENCODE_URL) {
         fputs_stdout(encodeString(url_for_encode));
         return 0;
     }
 #endif
 #if ENABLE_FEATURE_HTTPD_AUTH_MD5
     if (opt & OPT_MD5) {
         char salt[sizeof("$1$XXXXXXXX")];
         salt[0] = '$';
         salt[1] = '1';
         salt[2] = '$';
         crypt_make_salt(salt + 3, 4);
         puts(pw_encrypt(pass, salt, /*cleanup:*/ 0));
         return 0;
     }
 #endif
 #if ENABLE_FEATURE_HTTPD_SETUID
     if (opt & OPT_SETUID) {
         xget_uidgid(&ugid, s_ugid);
     }
 #endif
 #if !BB_MMU
     if (!(opt & OPT_FOREGROUND)) {
         bb_daemonize_or_rexec(0, argv); /* don't change current directory */
         re_execed = 0; /* for the following chdir to work */
     }
 #endif
     /* Chdir to home (unless we were re_exec()ed for NOMMU case
      * in mini_httpd_nommu(): we are already in the home dir then).
      */
     if (!re_execed)
         xchdir(home_httpd);
     if (!(opt & OPT_INETD)) {
         signal(SIGCHLD, SIG_IGN);
         server_socket = openServer();
 #if ENABLE_FEATURE_HTTPD_SETUID
         /* drop privileges */
         if (opt & OPT_SETUID) {
             if (ugid.gid != (gid_t)-1) {
                 if (setgroups(1, &ugid.gid) == -1)
                     bb_simple_perror_msg_and_die("setgroups");
                 xsetgid(ugid.gid);
             }
             xsetuid(ugid.uid);
         }
 #endif
     }
 #if 0
     /* User can do it himself: 'env - PATH="$PATH" httpd'
      * We don't do it because we don't want to screw users
      * which want to do
      * 'env - VAR1=val1 VAR2=val2 httpd'
      * and have VAR1 and VAR2 values visible in their CGIs.
      * Besides, it is also smaller. */
     {
         char *p = getenv("PATH");
         /* env strings themself are not freed, no need to xstrdup(p): */
         clearenv();
         if (p)
             putenv(p - 5);
 //      if (!(opt & OPT_INETD))
 //          setenv_long("SERVER_PORT", ???);
     }
 #endif
     parse_conf(DEFAULT_PATH_HTTPD_CONF, FIRST_PARSE);
     if (!(opt & OPT_INETD))
         signal(SIGHUP, sighup_handler);
     xfunc_error_retval = 0;
     if (opt & OPT_INETD)
         mini_httpd_inetd(); /* never returns */
 #if BB_MMU
     if (!(opt & OPT_FOREGROUND))
         bb_daemonize(0); /* don't change current directory */
     mini_httpd(server_socket); /* never returns */
 #else
     mini_httpd_nommu(server_socket, argc, argv); /* never returns */
 #endif
     /* return 0; */
 }
References argc, argv, bb_daemonize, bb_daemonize_or_rexec, bb_simple_perror_msg_and_die(), bind_addr_or_port, clearenv(), crypt_make_salt(), FIRST_PARSE, fputs_stdout(), g_realm, getenv, getopt32(), home_httpd, INIT_G, LC_TIME, mini_httpd_inetd(), mini_httpd_nommu(), NULL, openServer(), opt, opt_c_configFile, OPT_DECODE_URL, OPT_ENCODE_URL, OPT_FOREGROUND, OPT_INETD, OPT_MD5, OPT_SETUID, p, parse_conf(), percent_decode_in_place(), putenv(), puts(), pw_encrypt, re_execed, setgroups(), setlocale, SIG_IGN, SIGCHLD, SIGHUP, sighup_handler(), signal, verbose, xchdir(), xfunc_error_retval, xget_uidgid(), xrealloc_getcwd_or_warn(), xsetgid(), and xsetuid().
log_and_exit()
static void log_and_exit (void) static
Definition at line 1054 of file httpd.c.
 {
     /* Paranoia. IE said to be buggy. It may send some extra data
      * or be confused by us just exiting without SHUT_WR. Oh well. */
     shutdown(1, SHUT_WR);
     /* Why??
     (this also messes up stdin when user runs httpd -i from terminal)
     ndelay_on(0);
     while (read(STDIN_FILENO, iobuf, IOBUF_SIZE) > 0)
         continue;
     */
     if (verbose > 2)
         bb_simple_error_msg("closed");
     _exit(xfunc_error_retval);
 }
References _exit(), bb_simple_error_msg(), SHUT_WR, shutdown(), verbose, and xfunc_error_retval.
Referenced by send_file_and_exit(), send_headers(), and send_headers_and_exit().
mini_httpd_inetd()
static void mini_httpd_inetd (void) static
Definition at line 2726 of file httpd.c.
 {
     len_and_sockaddr fromAddr;
     memset(&fromAddr, 0, sizeof(fromAddr));
     fromAddr.len = LSA_SIZEOF_SA;
     /* NB: can fail if user runs it by hand and types in http cmds */
     getpeername(0, &fromAddr.u.sa, &fromAddr.len);
     handle_incoming_and_exit(&fromAddr);
 }
References getpeername(), handle_incoming_and_exit(), len_and_sockaddr::len, LSA_SIZEOF_SA, memset(), and len_and_sockaddr::u.
Referenced by httpd_main().
mini_httpd_nommu()
static void mini_httpd_nommu (int server_socket, int argc, char ** argv) static
Definition at line 2679 of file httpd.c.
 {
     char *argv_copy[argc + 2];
     argv_copy[0] = argv[0];
     argv_copy[1] = (char*)"-i";
     memcpy(&argv_copy[2], &argv[1], argc * sizeof(argv[0]));
     /* NB: it's best to not use xfuncs in this loop before vfork().
      * Otherwise server may die on transient errors (temporary
      * out-of-memory condition, etc), which is Bad(tm).
      * Try to do any dangerous calls after fork.
      */
     while (1) {
         int n;
         /* Wait for connections... */
         n = accept(server_socket, NULL, NULL);
         if (n < 0)
             continue;
         /* set the KEEPALIVE option to cull dead connections */
         setsockopt_keepalive(n);
         if (vfork() == 0) {
             /* child */
             /* Do not reload config on HUP */
             signal(SIGHUP, SIG_IGN);
             close(server_socket);
             xmove_fd(n, 0);
             xdup2(0, 1);
             /* Run a copy of ourself in inetd mode */
             re_exec(argv_copy);
         }
         argv_copy[0][0] &= 0x7f;
         /* parent, or vfork failed */
         close(n);
     } /* while (1) */
     /* never reached */
 }
References accept(), argc, argv, close(), memcpy(), n, NULL, re_exec(), setsockopt_keepalive(), SIG_IGN, SIGHUP, signal, vfork(), xdup2(), and xmove_fd().
Referenced by httpd_main().
openServer()
static int openServer (void) static
Definition at line 1040 of file httpd.c.
 {
     unsigned n = bb_strtou(bind_addr_or_port, NULL, 10);
     if (!errno && n && n <= 0xffff)
         n = create_and_bind_stream_or_die(NULL, n);
     else
         n = create_and_bind_stream_or_die(bind_addr_or_port, 80);
     xlisten(n, 9);
     return n;
 }
References bb_strtou(), bind_addr_or_port, create_and_bind_stream_or_die(), errno, n, NULL, and xlisten().
Referenced by httpd_main().
parse_conf()
static int parse_conf (const char * path, int flag) static
Definition at line 697 of file httpd.c.
 {
     /* internally used extra flag state */
     enum { TRY_CURDIR_PARSE = 3 };
     FILE *f;
     const char *filename;
     char buf[160];
     /* discard old rules */
 #if ENABLE_FEATURE_HTTPD_ACL_IP
     free_Htaccess_IP_list(&G.ip_a_d);
 #endif
     flg_deny_all = 0;
     /* retain previous auth and mime config only for subdir parse */
     if (flag != SUBDIR_PARSE) {
         free_Htaccess_list(&mime_a);
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
         free_Htaccess_list(&g_auth);
 #endif
 #if ENABLE_FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR
         free_Htaccess_list(&script_i);
 #endif
     }
     filename = opt_c_configFile;
     if (flag == SUBDIR_PARSE || filename == NULL) {
         filename = alloca(strlen(path) + sizeof(HTTPD_CONF) + 2);
         sprintf((char *)filename, "%s/%s", path, HTTPD_CONF);
     }
     while ((f = fopen_for_read(filename)) == NULL) {
         if (flag >= SUBDIR_PARSE) { /* SUBDIR or TRY_CURDIR */
             /* config file not found, no changes to config */
             return -1;
         }
         if (flag == FIRST_PARSE) {
             /* -c CONFFILE given, but CONFFILE doesn't exist? */
             if (opt_c_configFile)
                 bb_simple_perror_msg_and_die(opt_c_configFile);
             /* else: no -c, thus we looked at /etc/httpd.conf,
              * and it's not there. try ./httpd.conf: */
         }
         flag = TRY_CURDIR_PARSE;
         filename = HTTPD_CONF;
     }
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
     /* in "/file:user:pass" lines, we prepend path in subdirs */
     if (flag != SUBDIR_PARSE)
         path = "";
 #endif
     /* The lines can be:
      *
      * I:default_index_file
      * H:http_home
      * [AD]:IP[/mask]   # allow/deny, * for wildcard
      * Ennn:error.html  # error page for status nnn
      * P:/url:[http://]hostname[:port]/new/path # reverse proxy
      * .ext:mime/type   # mime type
      * *.php:/path/php  # run xxx.php through an interpreter
      * /file:user:pass  # username and password
      */
     while (fgets(buf, sizeof(buf), f) != NULL) {
         unsigned strlen_buf;
         unsigned char ch;
         char *after_colon;
         { /* remove all whitespace, and # comments */
             char *p, *p0;
             p0 = buf;
             /* skip non-whitespace beginning. Often the whole line
              * is non-whitespace. We want this case to work fast,
              * without needless copying, therefore we don't merge
              * this operation into next while loop. */
             while ((ch = *p0) != '\0' && ch != '\n' && ch != '#'
              && ch != ' ' && ch != '\t'
             ) {
                 p0++;
             }
             p = p0;
             /* if we enter this loop, we have some whitespace.
              * discard it */
             while (ch != '\0' && ch != '\n' && ch != '#') {
                 if (ch != ' ' && ch != '\t') {
                     *p++ = ch;
                 }
                 ch = *++p0;
             }
             *p = '\0';
             strlen_buf = p - buf;
             if (strlen_buf == 0)
                 continue; /* empty line */
         }
         after_colon = strchr(buf, ':');
         /* strange line? */
         if (after_colon == NULL || *++after_colon == '\0')
             goto config_error;
         ch = (buf[0] & ~0x20); /* toupper if it's a letter */
         if (ch == 'I') {
             if (index_page != index_html)
                 free((char*)index_page);
             index_page = xstrdup(after_colon);
             continue;
         }
         /* do not allow jumping around using H in subdir's configs */
         if (flag == FIRST_PARSE && ch == 'H') {
             home_httpd = xstrdup(after_colon);
             xchdir(home_httpd);
             continue;
         }
 #if ENABLE_FEATURE_HTTPD_ACL_IP
         if (ch == 'A' || ch == 'D') {
             Htaccess_IP *pip;
             if (*after_colon == '*') {
                 if (ch == 'D') {
                     /* memorize "deny all" */
                     flg_deny_all = 1;
                 }
                 /* skip assumed "A:*", it is a default anyway */
                 continue;
             }
             /* store "allow/deny IP/mask" line */
             pip = xzalloc(sizeof(*pip));
             if (scan_ip_mask(after_colon, &pip->ip, &pip->mask)) {
                 /* IP{/mask} syntax error detected, protect all */
                 ch = 'D';
                 pip->mask = 0;
             }
             pip->allow_deny = ch;
             if (ch == 'D') {
                 /* Deny:from_IP - prepend */
                 pip->next = G.ip_a_d;
                 G.ip_a_d = pip;
             } else {
                 /* A:from_IP - append (thus all D's precedes A's) */
                 Htaccess_IP *prev_IP = G.ip_a_d;
                 if (prev_IP == NULL) {
                     G.ip_a_d = pip;
                 } else {
                     while (prev_IP->next)
                         prev_IP = prev_IP->next;
                     prev_IP->next = pip;
                 }
             }
             continue;
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_ERROR_PAGES
         if (flag == FIRST_PARSE && ch == 'E') {
             unsigned i;
             int status = atoi(buf + 1); /* error status code */
             if (status < HTTP_CONTINUE) {
                 goto config_error;
             }
             /* then error page; find matching status */
             for (i = 0; i < ARRAY_SIZE(http_response_type); i++) {
                 if (http_response_type[i] == status) {
                     /* We chdir to home_httpd, thus no need to
                      * concat_path_file(home_httpd, after_colon)
                      * here */
                     http_error_page[i] = xstrdup(after_colon);
                     break;
                 }
             }
             continue;
         }
 #endif
 #if ENABLE_FEATURE_HTTPD_PROXY
         if (flag == FIRST_PARSE && ch == 'P') {
             /* P:/url:[http://]hostname[:port]/new/path */
             char *url_from, *host_port, *url_to;
             Htaccess_Proxy *proxy_entry;
             url_from = after_colon;
             host_port = strchr(after_colon, ':');
             if (host_port == NULL) {
                 goto config_error;
             }
             *host_port++ = '\0';
             if (is_prefixed_with(host_port, "http://"))
                 host_port += 7;
             if (*host_port == '\0') {
                 goto config_error;
             }
             url_to = strchr(host_port, '/');
             if (url_to == NULL) {
                 goto config_error;
             }
             *url_to = '\0';
             proxy_entry = xzalloc(sizeof(*proxy_entry));
             proxy_entry->url_from = xstrdup(url_from);
             proxy_entry->host_port = xstrdup(host_port);
             *url_to = '/';
             proxy_entry->url_to = xstrdup(url_to);
             proxy_entry->next = proxy;
             proxy = proxy_entry;
             continue;
         }
 #endif
         /* the rest of directives are non-alphabetic,
          * must avoid using "toupper'ed" ch */
         ch = buf[0];
         if (ch == '.' /* ".ext:mime/type" */
 #if ENABLE_FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR
          || (ch == '*' && buf[1] == '.') /* "*.php:/path/php" */
 #endif
         ) {
             char *p;
             Htaccess *cur;
             cur = xzalloc(sizeof(*cur) /* includes space for NUL */ + strlen_buf);
             strcpy(cur->before_colon, buf);
             p = cur->before_colon + (after_colon - buf);
             p[-1] = '\0';
             cur->after_colon = p;
             if (ch == '.') {
                 /* .mime line: prepend to mime_a list */
                 cur->next = mime_a;
                 mime_a = cur;
             }
 #if ENABLE_FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR
             else {
                 /* script interpreter line: prepend to script_i list */
                 cur->next = script_i;
                 script_i = cur;
             }
 #endif
             continue;
         }
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
         if (ch == '/') { /* "/file:user:pass" */
             char *p;
             Htaccess *cur;
             unsigned file_len;
             /* note: path is "" unless we are in SUBDIR parse,
              * otherwise it does NOT start with "/" */
             cur = xzalloc(sizeof(*cur) /* includes space for NUL */
                 + 1 + strlen(path)
                 + strlen_buf
                 );
             /* form "/path/file" */
             sprintf(cur->before_colon, "/%s%.*s",
                 path,
                 (int) (after_colon - buf - 1), /* includes "/", but not ":" */
                 buf);
             /* canonicalize it */
             p = bb_simplify_abs_path_inplace(cur->before_colon);
             file_len = p - cur->before_colon;
             /* add "user:pass" after NUL */
             strcpy(++p, after_colon);
             cur->after_colon = p;
             /* insert cur into g_auth */
             /* g_auth is sorted by decreased filename length */
             {
                 Htaccess *auth, **authp;
                 authp = &g_auth;
                 while ((auth = *authp) != NULL) {
                     if (file_len >= strlen(auth->before_colon)) {
                         /* insert cur before auth */
                         cur->next = auth;
                         break;
                     }
                     authp = &auth->next;
                 }
                 *authp = cur;
             }
             continue;
         }
 #endif /* BASIC_AUTH */
         /* the line is not recognized */
  config_error:
         bb_error_msg("config error '%s' in '%s'", buf, filename);
     } /* while (fgets) */
     fclose(f);
     return 0;
 }
References alloca, ARRAY_SIZE, atoi(), bb_error_msg(), bb_simple_perror_msg_and_die(), bb_simplify_abs_path_inplace(), Htaccess::before_colon, buf, cur, f, fclose(), fgets, filename, FIRST_PARSE, flg_deny_all, fopen_for_read(), free, free_Htaccess_list(), G, g_auth, home_httpd, Htaccess_Proxy::host_port, HTTP_CONTINUE, http_error_page, i, index_page, is_prefixed_with(), mime_a, Htaccess::next, Htaccess_Proxy::next, NULL, opt_c_configFile, p, proxy, script_i, sprintf(), status, strchr(), strcpy(), strlen(), SUBDIR_PARSE, Htaccess_Proxy::url_from, Htaccess_Proxy::url_to, xchdir(), xstrdup(), and xzalloc().
Referenced by handle_incoming_and_exit(), httpd_main(), and sighup_handler().
send_file_and_exit()
static NOINLINE void send_file_and_exit (const char * url, int what) static
Definition at line 1738 of file httpd.c.
 {
     char *suffix;
     int fd;
     ssize_t count;
     if (content_gzip) {
         /* does <url>.gz exist? Then use it instead */
         char *gzurl = xasprintf("%s.gz", url);
         fd = open(gzurl, O_RDONLY);
         free(gzurl);
         if (fd != -1) {
             struct stat sb;
             fstat(fd, &sb);
             file_size = sb.st_size;
             last_mod = sb.st_mtime;
         } else {
             IF_FEATURE_HTTPD_GZIP(content_gzip = 0;)
             fd = open(url, O_RDONLY);
         }
     } else {
         fd = open(url, O_RDONLY);
         /* file_size and last_mod are already populated */
     }
     if (fd < 0) {
         dbg("can't open '%s'\n", url);
         /* Error pages are sent by using send_file_and_exit(SEND_BODY).
          * IOW: it is unsafe to call send_headers_and_exit
          * if what is SEND_BODY! Can recurse! */
         if (what != SEND_BODY)
             send_headers_and_exit(HTTP_NOT_FOUND);
         log_and_exit();
     }
 #if ENABLE_FEATURE_HTTPD_ETAG
     /* ETag is "hex(last_mod)-hex(file_size)" e.g. "5e132e20-417" */
     sprintf(G.etag, "\"%llx-%llx\"", (unsigned long long)last_mod, (unsigned long long)file_size);
     if (G.if_none_match) {
         dbg("If-None-Match:'%s' file's ETag:'%s'\n", G.if_none_match, G.etag);
         /* Weak ETag comparision.
          * If-None-Match may have many ETags but they are quoted so we can use simple substring search */
         if (strstr(G.if_none_match, G.etag))
             send_headers_and_exit(HTTP_NOT_MODIFIED);
     }
 #endif
     /* If you want to know about EPIPE below
      * (happens if you abort downloads from local httpd): */
     signal(SIGPIPE, SIG_IGN);
     /* If not found, default is to not send "Content-type:" */
     /*found_mime_type = NULL; - already is */
     suffix = strrchr(url, '.');
     if (suffix) {
         static const char suffixTable[] ALIGN1 =
             /* Shorter suffix must be first:
              * ".html.htm" will fail for ".htm"
              */
             ".txt.h.c.cc.cpp\0" "text/plain\0"
             /* .htm line must be after .h line */
             ".htm.html\0" "text/html\0"
             ".jpg.jpeg\0" "image/jpeg\0"
             ".gif\0"      "image/gif\0"
             ".png\0"      "image/png\0"
             ".svg\0"      "image/svg+xml\0"
             /* .css line must be after .c line */
             ".css\0"      "text/css\0"
             ".js\0"       "application/javascript\0"
             ".wav\0"      "audio/wav\0"
             ".avi\0"      "video/x-msvideo\0"
             ".qt.mov\0"   "video/quicktime\0"
             ".mpe.mpeg\0" "video/mpeg\0"
             ".mid.midi\0" "audio/midi\0"
             ".mp3\0"      "audio/mpeg\0"
 #if 0  /* unpopular */
             ".au\0"       "audio/basic\0"
             ".pac\0"      "application/x-ns-proxy-autoconfig\0"
             ".vrml.wrl\0" "model/vrml\0"
 #endif
             /* compiler adds another "\0" here */
         ;
         Htaccess *cur;
         /* Examine built-in table */
         const char *table = suffixTable;
         const char *table_next;
         for (; *table; table = table_next) {
             const char *try_suffix;
             const char *mime_type;
             mime_type  = table + strlen(table) + 1;
             table_next = mime_type + strlen(mime_type) + 1;
             try_suffix = strstr(table, suffix);
             if (!try_suffix)
                 continue;
             try_suffix += strlen(suffix);
             if (*try_suffix == '\0' || *try_suffix == '.') {
                 found_mime_type = mime_type;
                 break;
             }
             /* Example: strstr(table, ".av") != NULL, but it
              * does not match ".avi" after all and we end up here.
              * The table is arranged so that in this case we know
              * that it can't match anything in the following lines,
              * and we stop the search: */
             break;
         }
         /* ...then user's table */
         for (cur = mime_a; cur; cur = cur->next) {
             if (strcmp(cur->before_colon, suffix) == 0) {
                 found_mime_type = cur->after_colon;
                 break;
             }
         }
     }
     dbg("sending file '%s' content-type:%s\n", url, found_mime_type);
 #if ENABLE_FEATURE_HTTPD_RANGES
     if (what == SEND_BODY /* err pages and ranges don't mix */
      || content_gzip /* we are sending compressed page: can't do ranges */
     ) {
         range_start = -1;
     }
     range_len = MAXINT(off_t);
     if (range_start >= 0) {
         if (!range_end || range_end > file_size - 1) {
             range_end = file_size - 1;
         }
         if (range_end < range_start
          || lseek(fd, range_start, SEEK_SET) != range_start
         ) {
             lseek(fd, 0, SEEK_SET);
             range_start = -1;
         } else {
             range_len = range_end - range_start + 1;
             send_headers(HTTP_PARTIAL_CONTENT);
             what = SEND_BODY;
         }
     }
 #endif
     if (what & SEND_HEADERS)
         send_headers(HTTP_OK);
 #if ENABLE_FEATURE_USE_SENDFILE
     {
         off_t offset;
 # if ENABLE_FEATURE_HTTPD_RANGES
         if (range_start < 0)
             range_start = 0;
         offset = range_start;
 # else
         offset = 0;
 # endif
         while (1) {
             /* sz is rounded down to 64k */
             ssize_t sz = MAXINT(ssize_t) - 0xffff;
             IF_FEATURE_HTTPD_RANGES(if (sz > range_len) sz = range_len;)
             count = sendfile(STDOUT_FILENO, fd, &offset, sz);
             if (count < 0) {
                 if (offset == range_start) /* was it the very 1st sendfile? */
                     break; /* fall back to read/write loop */
                 goto fin;
             }
             IF_FEATURE_HTTPD_RANGES(range_len -= count;)
             if (count == 0 || range_len == 0)
                 log_and_exit();
         }
     }
 #endif
     while ((count = safe_read(fd, iobuf, IOBUF_SIZE)) > 0) {
         ssize_t n;
         IF_FEATURE_HTTPD_RANGES(if (count > range_len) count = range_len;)
         n = full_write(STDOUT_FILENO, iobuf, count);
         if (count != n)
             break;
         IF_FEATURE_HTTPD_RANGES(range_len -= count;)
         if (range_len == 0)
             break;
     }
     if (count < 0) {
  IF_FEATURE_USE_SENDFILE(fin:)
         if (verbose > 1)
             bb_simple_perror_msg("error");
     }
     log_and_exit();
 }
References ALIGN1, bb_simple_perror_msg(), content_gzip, count, cur, dbg, fd, file_size, found_mime_type, free, fstat(), full_write(), G, HTTP_NOT_FOUND, HTTP_NOT_MODIFIED, HTTP_OK, HTTP_PARTIAL_CONTENT, iobuf, IOBUF_SIZE, last_mod, log_and_exit(), lseek(), MAXINT, mime_a, n, O_RDONLY, off_t, offset, open(), range_end, range_len, range_start, safe_read(), SEEK_SET, SEND_BODY, SEND_HEADERS, send_headers(), send_headers_and_exit(), sendfile, SIG_IGN, signal, SIGPIPE, sprintf(), stat::st_size, STDOUT_FILENO, strcmp, strlen(), strrchr(), strstr(), table, verbose, and xasprintf().
Referenced by handle_incoming_and_exit(), and send_headers().
send_headers()
static void send_headers (unsigned responseNum) static
Definition at line 1079 of file httpd.c.
 {
 #if ENABLE_FEATURE_HTTPD_DATE || ENABLE_FEATURE_HTTPD_LAST_MODIFIED
     static const char RFC1123FMT[] ALIGN1 = "%a, %d %b %Y %H:%M:%S GMT";
     /* Fixed size 29-byte string. Example: Sun, 06 Nov 1994 08:49:37 GMT */
     char date_str[40]; /* using a bit larger buffer to paranoia reasons */
     struct tm tm;
 #endif
     const char *responseString = "";
     const char *infoString = NULL;
 #if ENABLE_FEATURE_HTTPD_ERROR_PAGES
     const char *error_page = NULL;
 #endif
     unsigned len;
     unsigned i;
     for (i = 0; i < ARRAY_SIZE(http_response_type); i++) {
         if (http_response_type[i] == responseNum) {
             responseString = http_response[i].name;
             infoString = http_response[i].info;
 #if ENABLE_FEATURE_HTTPD_ERROR_PAGES
             error_page = http_error_page[i];
 #endif
             break;
         }
     }
     if (verbose)
         bb_error_msg("response:%u", responseNum);
     /* We use sprintf, not snprintf (it's less code).
      * iobuf[] is several kbytes long and all headers we generate
      * always fit into those kbytes.
      */
     {
 #if ENABLE_FEATURE_HTTPD_DATE
         time_t timer = time(NULL);
         strftime(date_str, sizeof(date_str), RFC1123FMT, gmtime_r(&timer, &tm));
         /* ^^^ using gmtime_r() instead of gmtime() to not use static data */
 #endif
         len = sprintf(iobuf,
             "HTTP/1.1 %u %s\r\n"
 #if ENABLE_FEATURE_HTTPD_DATE
             "Date: %s\r\n"
 #endif
             "Connection: close\r\n",
             responseNum, responseString
 #if ENABLE_FEATURE_HTTPD_DATE
             , date_str
 #endif
         );
     }
     if (responseNum != HTTP_OK || found_mime_type) {
         len += sprintf(iobuf + len,
                 "Content-type: %s\r\n",
                 /* if it's error message, then it's HTML */
                 (responseNum != HTTP_OK ? "text/html" : found_mime_type)
         );
     }
 #if ENABLE_FEATURE_HTTPD_BASIC_AUTH
     if (responseNum == HTTP_UNAUTHORIZED) {
         len += sprintf(iobuf + len,
                 "WWW-Authenticate: Basic realm=\"%.999s\"\r\n",
                 g_realm /* %.999s protects from overflowing iobuf[] */
         );
     }
 #endif
     if (responseNum == HTTP_MOVED_TEMPORARILY) {
         /* Responding to "GET /dir" with
          * "HTTP/1.1 302 Found" "Location: /dir/"
          * - IOW, asking them to repeat with a slash.
          * Here, overflow IS possible, can't use sprintf:
          * mkdir test
          * python -c 'print("get /test?" + ("x" * 8192))' | busybox httpd -i -h .
          */
         len += snprintf(iobuf + len, IOBUF_SIZE-3 - len,
                 "Location: %s/%s%s\r\n",
                 found_moved_temporarily,
                 (g_query ? "?" : ""),
                 (g_query ? g_query : "")
         );
         if (len > IOBUF_SIZE-3)
             len = IOBUF_SIZE-3;
     }
 #if ENABLE_FEATURE_HTTPD_ERROR_PAGES
     if (error_page && access(error_page, R_OK) == 0) {
         iobuf[len++] = '\r';
         iobuf[len++] = '\n';
         if (DEBUG) {
             iobuf[len] = '\0';
             fprintf(stderr, "headers: '%s'\n", iobuf);
         }
         full_write(STDOUT_FILENO, iobuf, len);
         dbg("writing error page: '%s'\n", error_page);
         return send_file_and_exit(error_page, SEND_BODY);
     }
 #endif
     if (file_size != -1) {    /* file */
 #if ENABLE_FEATURE_HTTPD_LAST_MODIFIED
         strftime(date_str, sizeof(date_str), RFC1123FMT, gmtime_r(&last_mod, &tm));
 #endif
 #if ENABLE_FEATURE_HTTPD_RANGES
         if (responseNum == HTTP_PARTIAL_CONTENT) {
             len += sprintf(iobuf + len,
                 "Content-Range: bytes %"OFF_FMT"u-%"OFF_FMT"u/%"OFF_FMT"u\r\n",
                     range_start,
                     range_end,
                     file_size
             );
             file_size = range_end - range_start + 1;
         }
 #endif
 //RFC 2616 4.4 Message Length
 // The transfer-length of a message is the length of the message-body as
 // it appears in the message; that is, after any transfer-codings have
 // been applied. When a message-body is included with a message, the
 // transfer-length of that body is determined by one of the following
 // (in order of precedence):
 // 1.Any response message which "MUST NOT" include a message-body (such
 //   as the 1xx, 204, and 304 responses and any response to a HEAD
 //   request) is always terminated by the first empty line after the
 //   header fields, regardless of the entity-header fields present in
 //   the message.
 // 2.If a Transfer-Encoding header field (section 14.41) is present and
 //   has any value other than "identity", then the transfer-length is
 //   defined by use of the "chunked" transfer-coding (section 3.6),
 //   unless the message is terminated by closing the connection.
 // 3.If a Content-Length header field (section 14.13) is present, its
 //   decimal value in OCTETs represents both the entity-length and the
 //   transfer-length. The Content-Length header field MUST NOT be sent
 //   if these two lengths are different (i.e., if a Transfer-Encoding
 //   header field is present). If a message is received with both a
 //   Transfer-Encoding header field and a Content-Length header field,
 //   the latter MUST be ignored.
 // 4.If the message uses the media type "multipart/byteranges" ...
 // 5.By the server closing the connection.
 //
 // (NB: standards do not define "Transfer-Length:" _header_,
 // transfer-length above is just a concept).
         len += sprintf(iobuf + len,
 #if ENABLE_FEATURE_HTTPD_RANGES
             "Accept-Ranges: bytes\r\n"
 #endif
 #if ENABLE_FEATURE_HTTPD_LAST_MODIFIED
             "Last-Modified: %s\r\n"
 #endif
 #if ENABLE_FEATURE_HTTPD_ETAG
             "ETag: %s\r\n"
 #endif
     /* Because of 4.4 (5), we can forgo sending of "Content-Length"
      * since we close connection afterwards, but it helps clients
      * to e.g. estimate download times, show progress bars etc.
      * Theoretically we should not send it if page is compressed,
      * but de-facto standard is to send it (see comment below).
      */
             "Content-Length: %"OFF_FMT"u\r\n",
 #if ENABLE_FEATURE_HTTPD_LAST_MODIFIED
                 date_str,
 #endif
 #if ENABLE_FEATURE_HTTPD_ETAG
                 G.etag,
 #endif
                 file_size
         );
     }
     /* This should be "Transfer-Encoding", not "Content-Encoding":
      * "data is compressed for transfer", not "data is an archive".
      * But many clients were not handling "Transfer-Encoding" correctly
      * (they were not uncompressing gzipped pages, tried to show
      * raw compressed data), and servers worked around it by using
      * "Content-Encoding" instead... and this become de-facto standard.
      * https://bugzilla.mozilla.org/show_bug.cgi?id=68517
      * https://bugs.chromium.org/p/chromium/issues/detail?id=94730
      */
     if (content_gzip)
         len += sprintf(iobuf + len, "Content-Encoding: gzip\r\n");
     iobuf[len++] = '\r';
     iobuf[len++] = '\n';
     if (infoString) {
         len += sprintf(iobuf + len,
                 "<HTML><HEAD><TITLE>%u %s</TITLE></HEAD>\n"
                 "<BODY><H1>%u %s</H1>\n"
                 "%s\n"
                 "</BODY></HTML>\n",
                 responseNum, responseString,
                 responseNum, responseString,
                 infoString
         );
     }
     if (DEBUG) {
         iobuf[len] = '\0';
         fprintf(stderr, "headers: '%s'\n", iobuf);
     }
     if (full_write(STDOUT_FILENO, iobuf, len) != len) {
         if (verbose > 1)
             bb_simple_perror_msg("error");
         log_and_exit();
     }
 }
References access(), ALIGN1, ARRAY_SIZE, bb_error_msg(), bb_simple_perror_msg(), content_gzip, date_str, dbg, DEBUG, file_size, found_mime_type, found_moved_temporarily, fprintf(), full_write(), G, g_query, g_realm, http_error_page, HTTP_MOVED_TEMPORARILY, HTTP_OK, HTTP_PARTIAL_CONTENT, http_response, HTTP_UNAUTHORIZED, i, iobuf, IOBUF_SIZE, last_mod, log_and_exit(), NULL, OFF_FMT, R_OK, range_end, range_start, SEND_BODY, send_file_and_exit(), snprintf(), sprintf(), stderr, STDOUT_FILENO, strftime(), time(), and verbose.
Referenced by send_file_and_exit(), and send_headers_and_exit().
send_headers_and_exit()
static void send_headers_and_exit (int responseNum) static
Definition at line 1290 of file httpd.c.
 {
     IF_FEATURE_HTTPD_GZIP(content_gzip = 0;)
     file_size = -1; /* no Last-Modified:, ETag:, Content-Length: */
     send_headers(responseNum);
     log_and_exit();
 }
References content_gzip, file_size, log_and_exit(), and send_headers().
Referenced by handle_incoming_and_exit(), send_file_and_exit(), and send_REQUEST_TIMEOUT_and_exit().
send_REQUEST_TIMEOUT_and_exit()
static void send_REQUEST_TIMEOUT_and_exit (int sig UNUSED_PARAM) static
Definition at line 2171 of file httpd.c.
 {
     send_headers_and_exit(HTTP_REQUEST_TIMEOUT);
 }
References HTTP_REQUEST_TIMEOUT, and send_headers_and_exit().
Referenced by handle_incoming_and_exit().
sighup_handler()
static void sighup_handler (int sig UNUSED_PARAM) static
Definition at line 2738 of file httpd.c.
 {
     int sv = errno;
     parse_conf(DEFAULT_PATH_HTTPD_CONF, SIGNALED_PARSE);
     errno = sv;
 }
References errno, parse_conf(), SIGNALED_PARSE, and sv.
Referenced by httpd_main().
Variable Documentation
ALIGN1
const char index_html [] ALIGN1 = "/etc" static
Definition at line 328 of file httpd.c.
Referenced by handle_incoming_and_exit(), send_file_and_exit(), and send_headers().
ALIGN2
const uint16_t http_response_type [] ALIGN2 static
Initial value:
= {
    HTTP_OK,
    HTTP_MOVED_TEMPORARILY,
    HTTP_REQUEST_TIMEOUT,
    HTTP_NOT_IMPLEMENTED,
    HTTP_NOT_FOUND,
    HTTP_BAD_REQUEST,
    HTTP_FORBIDDEN,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_ENTITY_TOO_LARGE,
}
Definition at line 390 of file httpd.c.
const { ... } http_response[ARRAY_SIZE(http_response_type)]
Initial value:
= {
    { "OK", NULL },
    { "Found", NULL },
    { "Request Timeout", "No request appeared within 60 seconds" },
    { "Not Implemented", "The requested method is not recognized" },
    { "Not Found", "The requested URL was not found" },
    { "Bad Request", "Unsupported method" },
    { "Forbidden", ""  },
    { "Internal Server Error", "Internal Server Error" },
    { "Entity Too Large", "Entity Too Large" },
}
Referenced by send_headers().