Fennix: Userspace/libc/ElfInterpreter/fcts.h File Reference
fcts.h File Reference
#include <types.h>
#include "elf.h"
Macros
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#define MAX(a, b) (((a) > (b)) ? (a) : (b))
Functions
uintptr_t RequestPages (size_t Count)
int FreePages (uintptr_t Address, size_t Count)
int IPC (int Command, int Type, int ID, int Flags, void *Buffer, size_t Size)
uintptr_t KernelCTL (int Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
int abs (int i)
void swap (char *x, char *y)
char * reverse (char *Buffer, int i, int j)
char * ltoa (long Value, char *Buffer, int Base)
void PutCharToKernelConsole (char c)
void Print__ (char *String)
void PrintNL__ (char *String)
void * memcpy (void *dest, const void *src, size_t n)
void * memset (void *s, int c, size_t n)
int strcmp (const char *l, const char *r)
struct Elf64_Dyn ELFGetDynamicTag (char *Path, enum DynamicTags Tag)
Elf64_Shdr * GetELFSheader (Elf64_Ehdr *Header)
Elf64_Shdr * GetELFSection (Elf64_Ehdr *Header, uint64_t Index)
char * GetELFStringTable (Elf64_Ehdr *Header)
Elf64_Sym ELFLookupSymbol (char *Path, const char *Name)
Macro Definition Documentation
MAX
#define MAX (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 8 of file fcts.h.
MIN
#define MIN (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 7 of file fcts.h.
Function Documentation
abs()
int abs (int i)
Definition at line 26 of file fcts.c.
 { return i < 0 ? -i : i; }
ELFGetDynamicTag()
struct Elf64_Dyn ELFGetDynamicTag (char * Path, enum DynamicTags Tag)
Definition at line 106 of file fcts.c.
 {
     int fd = syscall2(sys_FileOpen, Path, (long)"r");
     if (fd < 0)
         syscall1(sys_Exit, -0xF17E);
     Elf64_Ehdr ELFHeader;
     syscall3(sys_FileRead, fd, &ELFHeader, sizeof(Elf64_Ehdr));
     Elf64_Phdr ItrProgramHeader;
     for (Elf64_Half i = 0; i < ELFHeader.e_phnum; i++)
     {
         // memcpy(&ItrProgramHeader, (uint8_t *)ElfFile + ELFHeader.e_phoff + ELFHeader.e_phentsize * i, sizeof(Elf64_Phdr));
         syscall3(sys_FileSeek, fd, ELFHeader.e_phoff + ELFHeader.e_phentsize * i, SYSCALL_SEEK_SET);
         syscall3(sys_FileRead, fd, &ItrProgramHeader, sizeof(Elf64_Phdr));
         if (ItrProgramHeader.p_type == PT_DYNAMIC)
         {
             struct Elf64_Dyn Dynamic; // = (struct Elf64_Dyn *)((uint8_t *)ElfFile + ItrProgramHeader.p_offset);
             syscall3(sys_FileSeek, fd, ItrProgramHeader.p_offset, SYSCALL_SEEK_SET);
             syscall3(sys_FileRead, fd, &Dynamic, ItrProgramHeader.p_filesz);
             for (size_t i = 0; i < ItrProgramHeader.p_filesz / sizeof(struct Elf64_Dyn); i++)
             {
                 if (Dynamic.d_tag == Tag || Dynamic.d_tag == DT_NULL)
                 {
                     syscall1(sys_FileClose, fd);
                     return Dynamic;
                 }
                 syscall3(sys_FileSeek, fd, ItrProgramHeader.p_offset + (i + 1) * sizeof(struct Elf64_Dyn), SYSCALL_SEEK_SET);
                 syscall3(sys_FileRead, fd, &Dynamic, sizeof(struct Elf64_Dyn));
             }
         }
     }
     syscall1(sys_FileClose, fd);
     return (struct Elf64_Dyn){0};
 }
References r.
Referenced by ELFAddLazyResolverToGOT().
ELFLookupSymbol()
Elf64_Sym ELFLookupSymbol (char * Path, const char * Name)
Definition at line 169 of file fcts.c.
 {
     int fd = syscall2(sys_FileOpen, Path, (long)"r");
     if (fd < 0)
         syscall1(sys_Exit, -0xF17E);
     Elf64_Ehdr ELFHeader;
     syscall3(sys_FileRead, fd, &ELFHeader, sizeof(Elf64_Ehdr));
     Elf64_Shdr SymbolTable;
     Elf64_Shdr StringTable;
     Elf64_Sym Symbol;
     char *String = NULL;
     for (Elf64_Half i = 0; i < ELFHeader.e_shnum; i++)
     {
         Elf64_Shdr shdr;
         syscall3(sys_FileSeek, fd,
                  ELFHeader.e_shoff + ELFHeader.e_shentsize * i,
                  SYSCALL_SEEK_SET);
         syscall3(sys_FileRead, fd, &shdr, sizeof(Elf64_Shdr));
         switch (shdr.sh_type)
         {
         case SHT_SYMTAB:
         {
             SymbolTable = shdr;
             syscall3(sys_FileSeek, fd,
                      ELFHeader.e_shoff + ELFHeader.e_shentsize * shdr.sh_link,
                      SYSCALL_SEEK_SET);
             syscall3(sys_FileRead, fd, &StringTable, sizeof(Elf64_Shdr));
             break;
         }
         default:
         {
             break;
         }
         }
     }
     if (SymbolTable.sh_size == 0 || StringTable.sh_size == 0)
     {
         syscall1(sys_FileClose, fd);
         return (Elf64_Sym){0};
     }
     for (size_t i = 0; i < (SymbolTable.sh_size / sizeof(Elf64_Sym)); i++)
     {
         // Symbol = (Elf64_Sym *)((uintptr_t)Header + SymbolTable->sh_offset + (i * sizeof(Elf64_Sym)));
         // String = (char *)((uintptr_t)Header + StringTable->sh_offset + Symbol->st_name);
         syscall3(sys_FileSeek, fd, SymbolTable.sh_offset + (i * sizeof(Elf64_Sym)), SYSCALL_SEEK_SET);
         syscall3(sys_FileRead, fd, &Symbol, sizeof(Elf64_Sym));
         syscall3(sys_FileSeek, fd, StringTable.sh_offset + Symbol.st_name, SYSCALL_SEEK_SET);
         syscall3(sys_FileRead, fd, &String, sizeof(char *));
         if (strcmp(String, Name) == 0)
         {
             syscall1(sys_FileClose, fd);
             return Symbol;
         }
     }
     syscall1(sys_FileClose, fd);
     return (Elf64_Sym){0};
 }
References Elf64_Ehdr::e_shentsize, Elf64_Ehdr::e_shnum, Elf64_Ehdr::e_shoff, i, CPU::Name(), NULL, Elf64_Shdr::sh_link, Elf64_Shdr::sh_offset, Elf64_Shdr::sh_size, Elf64_Shdr::sh_type, SHT_SYMTAB, Elf64_Sym::st_name, strcmp(), sys_Exit, sys_FileClose, sys_FileOpen, sys_FileRead, sys_FileSeek, syscall1(), syscall2(), syscall3(), and SYSCALL_SEEK_SET.
FreePages()
int FreePages (uintptr_t Address, size_t Count)
Definition at line 11 of file fcts.c.
 {
     return syscall2(sys_FreePages, Address, Count);
 }
References Address, sys_FreePages, and syscall2().
GetELFSection()
Elf64_Shdr* GetELFSection (Elf64_Ehdr * Header, uint64_t Index)
Definition at line 156 of file fcts.c.
 {
     Elf64_Shdr *Sheader = GetELFSheader(Header);
     return &Sheader[Index];
 }
References GetELFSheader().
Referenced by GetELFStringTable().
GetELFSheader()
Elf64_Shdr* GetELFSheader (Elf64_Ehdr * Header)
Definition at line 150 of file fcts.c.
 {
     Elf64_Off SheaderOffset = Header->e_shoff;
     return (Elf64_Shdr *)((uintptr_t)Header + SheaderOffset);
 }
References Elf64_Ehdr::e_shoff.
Referenced by GetELFSection().
GetELFStringTable()
char* GetELFStringTable (Elf64_Ehdr * Header)
Definition at line 162 of file fcts.c.
 {
     if (Header->e_shstrndx == SHN_UNDEF)
         return NULL;
     return (char *)Header + GetELFSection(Header, Header->e_shstrndx)->sh_offset;
 }
References Elf64_Ehdr::e_shstrndx, GetELFSection(), NULL, Elf64_Shdr::sh_offset, and SHN_UNDEF.
IPC()
int IPC (int Command, int Type, int ID, int Flags, void * Buffer, size_t Size)
Definition at line 16 of file fcts.c.
 {
     return syscall6(sys_IPC, (long)Command, (long)Type, (long)ID, (long)Flags, (long)Buffer, (long)Size);
 }
References Flags, ID, Size, sys_IPC, syscall6(), and Type.
Referenced by Tasking::PCB::~PCB().
KernelCTL()
uintptr_t KernelCTL (int Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
Definition at line 21 of file fcts.c.
 {
     return syscall5(sys_KernelCTL, Command, Arg1, Arg2, Arg3, Arg4);
 }
References sys_KernelCTL, and syscall5().
Referenced by ld_main().
ltoa()
char* ltoa (long Value, char * Buffer, int Base)
Definition at line 659 of file Convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     long n = abs(Value);
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), i, n, r, and reverse().
memcpy()
void* memcpy (void * dest, const void * src, size_t n)
Definition at line 1061 of file Convert.cpp.
 {
     void *ret = __memcpy_chk(dest, src, len, __builtin_object_size(dest, 0));
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "!memcpy( %p %p %ld )=%p~%p\n\r",
                 dest, src, len,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
memset()
void* memset (void * s, int c, size_t n)
Definition at line 1088 of file Convert.cpp.
 {
     void *ret = __memset_chk(dest, val, len, __builtin_object_size(dest, 0));
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "!memset( %p %d %ld )=%p~%p\n\r",
                 dest, val, len,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
Print__()
void Print__ (char * String)
Definition at line 78 of file fcts.c.
 {
     for (short i = 0; String[i] != '\0'; i++)
         PutCharToKernelConsole(String[i]);
 }
References i, and PutCharToKernelConsole().
Referenced by PrintNL__().
PrintNL__()
void PrintNL__ (char * String)
Definition at line 84 of file fcts.c.
 {
     Print__(String);
     Print__("\n");
 }
References Print__().
PutCharToKernelConsole()
void PutCharToKernelConsole (char c)
Definition at line 70 of file fcts.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(1), "D"(c), "S"(0)
                          : "rcx", "r11", "memory");
 }
References __asm__(), and c.
Referenced by Print__().
RequestPages()
uintptr_t RequestPages (size_t Count)
Definition at line 6 of file fcts.c.
 {
     return syscall1(sys_RequestPages, Count);
 }
References sys_RequestPages, and syscall1().
reverse()
char* reverse (char * Buffer, int i, int j)
Definition at line 344 of file Convert.cpp.
 {
     while (i < j)
         swap(&Buffer[i++], &Buffer[j--]);
     return Buffer;
 }
References i, j, and swap().
Referenced by itoa(), ltoa(), and ultoa().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 120 of file Convert.cpp.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
swap()
void swap (char * x, char * y)
Definition at line 337 of file Convert.cpp.
 {
     char t = *x;
     *x = *y;
     *y = t;
 }
References t, x, and y.
Referenced by reverse().