Fennix Userspace: Userspace/musl/src/env/__init_tls.c File Reference
__init_tls.c File Reference
#include <elf.h>
#include <limits.h>
#include <sys/mman.h>
#include <string.h>
#include <stddef.h>
#include "pthread_impl.h"
#include "libc.h"
#include "atomic.h"
#include "syscall.h"
Data Structures
struct builtin_tls
Macros
#define SYSCALL_NO_TLS 1
#define MIN_TLS_ALIGN offsetof(struct builtin_tls, pt)
#define SYS_mmap2 SYS_mmap
Typedefs
typedef Elf64_Phdr Phdr
Functions
int __init_tp (void *p)
void * __copy_tls (unsigned char *mem)
static void static_init_tls (size_t *aux)
weak_alias (static_init_tls, __init_tls)
Variables
volatile int __thread_list_lock
static struct builtin_tls builtin_tls [1]
static struct tls_module main_tls
weak hidden const size_t _DYNAMIC []
Data Structure Documentation
builtin_tls
struct builtin_tls
Definition at line 124 of file dynlink.c.
Data Fields
char c
struct pthread pt
void * space[16]
Macro Definition Documentation
MIN_TLS_ALIGN
#define MIN_TLS_ALIGN offsetof(struct builtin_tls, pt)
Definition at line 35 of file __init_tls.c.
SYS_mmap2
#define SYS_mmap2 SYS_mmap
SYSCALL_NO_TLS
#define SYSCALL_NO_TLS 1
Definition at line 1 of file __init_tls.c.
Typedef Documentation
Phdr
typedef Elf64_Phdr Phdr
Definition at line 77 of file __init_tls.c.
Function Documentation
__copy_tls()
void* __copy_tls (unsigned char * mem)
Definition at line 39 of file __init_tls.c.
 {
     pthread_t td;
     struct tls_module *p;
     size_t i;
     uintptr_t *dtv;
 #ifdef TLS_ABOVE_TP
     dtv = (uintptr_t*)(mem + libc.tls_size) - (libc.tls_cnt + 1);
     mem += -((uintptr_t)mem + sizeof(struct pthread)) & (libc.tls_align-1);
     td = (pthread_t)mem;
     mem += sizeof(struct pthread);
     for (i=1, p=libc.tls_head; p; i++, p=p->next) {
         dtv[i] = (uintptr_t)(mem + p->offset) + DTP_OFFSET;
         memcpy(mem + p->offset, p->image, p->len);
     }
 #else
     dtv = (uintptr_t *)mem;
     mem += libc.tls_size - sizeof(struct pthread);
     mem -= (uintptr_t)mem & (libc.tls_align-1);
     td = (pthread_t)mem;
     for (i=1, p=libc.tls_head; p; i++, p=p->next) {
         dtv[i] = (uintptr_t)(mem - p->offset) + DTP_OFFSET;
         memcpy(mem - p->offset, p->image, p->len);
     }
 #endif
     dtv[0] = libc.tls_cnt;
     td->dtv = dtv;
     return td;
 }
References DTP_OFFSET, pthread::dtv, i, libc, mem, memcpy(), p, and td.
Referenced by __dls2b(), __dls3(), __pthread_create(), and static_init_tls().
__init_tp()
int __init_tp (void * p)
Definition at line 14 of file __init_tls.c.
 {
     pthread_t td = p;
     td->self = td;
     int r = __set_thread_area(TP_ADJ(p));
     if (r < 0) return -1;
     if (!r) libc.can_do_threads = 1;
     td->detach_state = DT_JOINABLE;
     td->tid = __syscall(SYS_set_tid_address, &__thread_list_lock);
     td->locale = &libc.global_locale;
     td->robust_list.head = &td->robust_list.head;
     td->sysinfo = __sysinfo;
     td->next = td->prev = td;
     return 0;
 }
References __set_thread_area(), __syscall, __sysinfo, __thread_list_lock, DT_JOINABLE, libc, p, td, and TP_ADJ.
Referenced by __dls2b(), __dls3(), and static_init_tls().
static_init_tls()
static void static_init_tls (size_t * aux) static
Definition at line 82 of file __init_tls.c.
 {
     unsigned char *p;
     size_t n;
     Phdr *phdr, *tls_phdr=0;
     size_t base = 0;
     void *mem;
     for (p=(void *)aux[AT_PHDR],n=aux[AT_PHNUM]; n; n--,p+=aux[AT_PHENT]) {
         phdr = (void *)p;
         if (phdr->p_type == PT_PHDR)
             base = aux[AT_PHDR] - phdr->p_vaddr;
         if (phdr->p_type == PT_DYNAMIC && _DYNAMIC)
             base = (size_t)_DYNAMIC - phdr->p_vaddr;
         if (phdr->p_type == PT_TLS)
             tls_phdr = phdr;
         if (phdr->p_type == PT_GNU_STACK &&
             phdr->p_memsz > __default_stacksize)
             __default_stacksize =
                 phdr->p_memsz < DEFAULT_STACK_MAX ?
                 phdr->p_memsz : DEFAULT_STACK_MAX;
     }
     if (tls_phdr) {
         main_tls.image = (void *)(base + tls_phdr->p_vaddr);
         main_tls.len = tls_phdr->p_filesz;
         main_tls.size = tls_phdr->p_memsz;
         main_tls.align = tls_phdr->p_align;
         libc.tls_cnt = 1;
         libc.tls_head = &main_tls;
     }
     main_tls.size += (-main_tls.size - (uintptr_t)main_tls.image)
         & (main_tls.align-1);
 #ifdef TLS_ABOVE_TP
     main_tls.offset = GAP_ABOVE_TP;
     main_tls.offset += (-GAP_ABOVE_TP + (uintptr_t)main_tls.image)
         & (main_tls.align-1);
 #else
     main_tls.offset = main_tls.size;
 #endif
     if (main_tls.align < MIN_TLS_ALIGN) main_tls.align = MIN_TLS_ALIGN;
     libc.tls_align = main_tls.align;
     libc.tls_size = 2*sizeof(void *) + sizeof(struct pthread)
 #ifdef TLS_ABOVE_TP
         + main_tls.offset
 #endif
         + main_tls.size + main_tls.align
         + MIN_TLS_ALIGN-1 & -MIN_TLS_ALIGN;
     if (libc.tls_size > sizeof builtin_tls) {
 #ifndef SYS_mmap2
 #define SYS_mmap2 SYS_mmap
 #endif
         mem = (void *)__syscall(
             SYS_mmap2,
             0, libc.tls_size, PROT_READ|PROT_WRITE,
             MAP_ANONYMOUS|MAP_PRIVATE, -1, 0);
         /* -4095...-1 cast to void * will crash on dereference anyway,
          * so don't bloat the init code checking for error codes and
          * explicitly calling a_crash(). */
     } else {
         mem = builtin_tls;
     }
     /* Failure to initialize thread pointer is always fatal. */
     if (__init_tp(__copy_tls(mem)) < 0)
         a_crash();
 }
References __copy_tls(), __default_stacksize, __init_tp(), __syscall, _DYNAMIC, a_crash, tls_module::align, AT_PHDR, AT_PHENT, AT_PHNUM, base, builtin_tls, DEFAULT_STACK_MAX, GAP_ABOVE_TP, if(), tls_module::image, tls_module::len, libc, main_tls, MAP_ANONYMOUS, MAP_PRIVATE, mem, MIN_TLS_ALIGN, n, tls_module::offset, p, Elf64_Phdr::p_align, Elf64_Phdr::p_filesz, Elf64_Phdr::p_memsz, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, PROT_READ, PROT_WRITE, PT_DYNAMIC, PT_GNU_STACK, PT_PHDR, PT_TLS, tls_module::size, and SYS_mmap2.
weak_alias()
weak_alias (static_init_tls , __init_tls)
Variable Documentation
__thread_list_lock
volatile int __thread_list_lock
Definition at line 12 of file __init_tls.c.
Referenced by __init_tp(), __pthread_create(), __tl_lock(), __tl_sync(), __tl_unlock(), and _Fork().
_DYNAMIC
weak hidden const size_t _DYNAMIC[] extern
Referenced by static_init_tls().
builtin_tls
struct builtin_tls builtin_tls[1] static
Referenced by static_init_tls().
main_tls
struct tls_module main_tls static
Definition at line 14 of file __init_tls.c.
Referenced by static_init_tls().