Fennix Userspace: Userspace/apps/base/bash/lib/intl/textdomain.c File Reference
textdomain.c File Reference
#include <stdlib.h>
#include <string.h>
#include "libgnuintl.h"
#include "gettextP.h"
Macros
#define __libc_rwlock_define(CLASS, NAME)
#define __libc_rwlock_wrlock(NAME)
#define __libc_rwlock_unlock(NAME)
#define _nl_default_default_domain libintl_nl_default_default_domain
#define _nl_current_default_domain libintl_nl_current_default_domain
#define TEXTDOMAIN libintl_textdomain
Functions
__libc_rwlock_define (extern, _nl_state_lock attribute_hidden) char *const char *domainname
if (if(domainname[0]=='\0'||strcmp(domainname==NULL)
else if (strcmp(domainname, old_domain)==0)
if (new_domain !=NULL)
__libc_rwlock_unlock (_nl_state_lock)
Variables
const char _nl_default_default_domain[] attribute_hidden
char * old_domain
return new_domain
Macro Definition Documentation
__libc_rwlock_define
#define __libc_rwlock_define (CLASS, NAME)
Definition at line 40 of file textdomain.c.
__libc_rwlock_unlock
#define __libc_rwlock_unlock (NAME)
Definition at line 42 of file textdomain.c.
__libc_rwlock_wrlock
#define __libc_rwlock_wrlock (NAME)
Definition at line 41 of file textdomain.c.
_nl_current_default_domain
#define _nl_current_default_domain libintl_nl_current_default_domain
Definition at line 50 of file textdomain.c.
_nl_default_default_domain
#define _nl_default_default_domain libintl_nl_default_default_domain
Definition at line 49 of file textdomain.c.
TEXTDOMAIN
#define TEXTDOMAIN libintl_textdomain
Definition at line 72 of file textdomain.c.
Function Documentation
__libc_rwlock_define()
__libc_rwlock_define (extern , _nl_state_lock attribute_hidden) const
References new_domain.
__libc_rwlock_unlock()
__libc_rwlock_unlock (_nl_state_lock)
if() [1/3]
if (if (domainname[0] == '\0' || strcmp (domainname = = NULL)
Definition at line 89 of file textdomain.c.
     {
       _nl_current_default_domain = _nl_default_default_domain;
       new_domain = (char *) _nl_current_default_domain;
     }
if() [2/3]
if (new_domain ! = NULL)
Definition at line 128 of file textdomain.c.
     {
       ++_nl_msg_cat_cntr;
       if (old_domain != new_domain && old_domain != _nl_default_default_domain)
     free (old_domain);
     }
References _nl_default_default_domain, _nl_msg_cat_cntr, free, new_domain, and old_domain.
if() [3/3]
else if (strcmp(domainname, old_domain) = = 0) new
Definition at line 103 of file textdomain.c.
     {
       /* If the following malloc fails `_nl_current_default_domain'
      will be NULL.  This value will be returned and so signals we
      are out of core.  */
 #if defined _LIBC || defined HAVE_STRDUP
       new_domain = strdup (domainname);
 #else
       size_t len = strlen (domainname) + 1;
       new_domain = (char *) malloc (len);
       if (new_domain != NULL)
     memcpy (new_domain, domainname, len);
 #endif
       if (new_domain != NULL)
     _nl_current_default_domain = new_domain;
     }
References _nl_current_default_domain, domainname, malloc, memcpy(), new_domain, NULL, strdup(), and strlen().
Variable Documentation
attribute_hidden
const char* _nl_current_default_domain attribute_hidden extern
Definition at line 59 of file textdomain.c.
new_domain
return new_domain
Definition at line 138 of file textdomain.c.
Referenced by __libc_rwlock_define(), and if().
old_domain
char* old_domain
Initial value:
{
  char *new_domain
Definition at line 86 of file textdomain.c.
Referenced by if().