Fennix: Userspace/mlibc/tests/ansi/utf8.c File Reference
utf8.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include <locale.h>
Macros
#define EXPECT(func)
#define verify_decode(in, out) verify_decode(in, out, __LINE__)
Functions
void verify_decode (const char *input, wchar_t expected, int line)
int main ()
Macro Definition Documentation
EXPECT
#define EXPECT (func)
Value:
        ({ \
        if(res != expected_ret) { \
            printf(#func " decoded %d bytes (expected %d bytes), at %s:%d\n", \
                    res, expected_ret, __FILE__, line); \
            fflush(stdout); \
            abort(); \
        } \
        if(wc != expected) { \
            printf(#func " output cp %x (expected cp %x), at %s:%d\n", wc, \
                    expected, __FILE__, line); \
            fflush(stdout); \
            abort(); \
        } \
    })
Definition at line 8 of file utf8.c.
verify_decode
#define verify_decode (in, out) verify_decode(in, out, __LINE__)
Function Documentation
main()
int main (void)
Definition at line 45 of file utf8.c.
            {
     setlocale(LC_ALL, "C.UTF-8");
 #define verify_decode(in, out) verify_decode(in, out, __LINE__)
     verify_decode("\x24", 0x24);
     verify_decode("\xC2\xA2", 0xA2);
     verify_decode("\xE0\xA4\xB9", 0x939);
     verify_decode("\xE2\x82\xAC", 0x20AC);
     verify_decode("\xED\x95\x9C", 0xD55C);
     verify_decode("\xF0\x90\x8D\x88", 0x10348);
     verify_decode("", L'\0');
 }
References L, LC_ALL, setlocale(), and verify_decode.
verify_decode()
void verify_decode (const char * input, wchar_t expected, int line)
Definition at line 23 of file utf8.c.
{
     wchar_t wc;
     int bytes = *input ? strlen(input) : 1;
     int expected_ret = *input ? strlen(input) : 0;
     // Check mbrtowc().
     mbstate_t state;
     memset(&state, 0, sizeof(state));
     assert(mbrtowc(NULL, NULL, -1, &state) == 0);
     int res = mbrtowc(&wc, input, bytes, &state);
     EXPECT("mbrtowc");
     res = mbrtowc(NULL, input, bytes, &state);
     EXPECT("mbrtowc (pwc == NULL)");
     // Check mbtowc().
     assert(mbtowc(NULL, NULL, -1) == 0);
     res = mbtowc(&wc, input, bytes);
     EXPECT("mbtowc");
     res = mbtowc(NULL, input, bytes);
     EXPECT("mbtowc (pwc == NULL)");
 }
References assert, EXPECT, mbrtowc(), mbtowc(), memset, NULL, state, and strlen().