Fennix: Userspace/apps/base/busybox/util-linux/switch_root.c File Reference
switch_root.c File Reference
#include <sys/vfs.h>
#include <sys/mount.h>
#include "libbb.h"
Macros
#define RAMFS_MAGIC ((unsigned)0x858458f6)
#define TMPFS_MAGIC ((unsigned)0x01021994)
#define MS_MOVE 8192
Functions
static void delete_contents (const char *directory, dev_t rootdev)
static int FAST_FUNC rmrf (const char *directory, struct dirent *d, void *rootdevp)
int switch_root_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
MS_MOVE
#define MS_MOVE 8192
Definition at line 68 of file switch_root.c.
RAMFS_MAGIC
#define RAMFS_MAGIC ((unsigned)0x858458f6)
Definition at line 62 of file switch_root.c.
TMPFS_MAGIC
#define TMPFS_MAGIC ((unsigned)0x01021994)
Definition at line 65 of file switch_root.c.
Function Documentation
delete_contents()
static void delete_contents (const char * directory, dev_t rootdev) static
Definition at line 85 of file switch_root.c.
 {
     struct stat st;
     // Don't descend into other filesystems
     if (lstat(directory, &st) || st.st_dev != rootdev)
         return;
     // Recursively delete the contents of directories
     if (S_ISDIR(st.st_mode)) {
         iterate_on_dir(directory, rmrf, &rootdev);
     } else {
         // It wasn't a directory, zap it
         unlink(directory);
     }
 }
References directory, iterate_on_dir(), lstat, rmrf(), S_ISDIR, and unlink().
Referenced by rmrf(), and switch_root_main().
rmrf()
static int FAST_FUNC rmrf (const char * directory, struct dirent * d, void * rootdevp) static
Definition at line 73 of file switch_root.c.
 {
     char *newdir = concat_subpath_file(directory, d->d_name);
     if (newdir) { // not . or ..
         // Recurse to delete contents
         delete_contents(newdir, *(dev_t*)rootdevp);
         free(newdir);
     }
     return 0;
 }
References concat_subpath_file(), dirent::d_name, delete_contents(), dev_t, directory, and free.
Referenced by delete_contents().
switch_root_main()
int switch_root_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 176 of file switch_root.c.
 {
     char *newroot, *console = NULL;
     struct stat st;
     struct statfs stfs;
     unsigned dry_run = 0;
     dev_t rootdev;
     // Parse args. '+': stop at first non-option
     if (ENABLE_SWITCH_ROOT && (!ENABLE_RUN_INIT || applet_name[0] == 's')) {
 //usage:#define switch_root_trivial_usage
 //usage:       "[-c CONSOLE_DEV] NEW_ROOT NEW_INIT [ARGS]"
 //usage:#define switch_root_full_usage "\n\n"
 //usage:       "Free initramfs and switch to another root fs:\n"
 //usage:       "chroot to NEW_ROOT, delete all in /, move NEW_ROOT to /,\n"
 //usage:       "execute NEW_INIT. PID must be 1. NEW_ROOT must be a mountpoint.\n"
 //usage:     "\n    -c DEV  Reopen stdio to DEV after switch"
         getopt32(argv, "^+"
             "c:"
             "\0" "-2" /* minimum 2 args */,
             &console
         );
     } else {
 #if ENABLE_RUN_INIT
 //usage:#define run_init_trivial_usage
 //usage:       "[-d CAP,CAP...] [-n] [-c CONSOLE_DEV] NEW_ROOT NEW_INIT [ARGS]"
 //usage:#define run_init_full_usage "\n\n"
 //usage:       "Free initramfs and switch to another root fs:\n"
 //usage:       "chroot to NEW_ROOT, delete all in /, move NEW_ROOT to /,\n"
 //usage:       "execute NEW_INIT. PID must be 1. NEW_ROOT must be a mountpoint.\n"
 //usage:     "\n    -c DEV  Reopen stdio to DEV after switch"
 //usage:     "\n    -d CAPS Drop capabilities"
 //usage:     "\n    -n  Dry run"
         char *cap_list = NULL;
         dry_run = getopt32(argv, "^+"
             "c:d:n"
             "\0" "-2" /* minimum 2 args */,
             &console,
             &cap_list
         );
         dry_run >>= 2; // -n
         if (cap_list)
             drop_capabilities(cap_list);
 #endif
     }
     argv += optind;
     newroot = *argv++;
     // Change to new root directory and verify it's a different fs
     xchdir(newroot);
     xstat("/", &st);
     rootdev = st.st_dev;
     xstat(".", &st);
     if (st.st_dev == rootdev) {
         // Show usage, it says new root must be a mountpoint
         bb_show_usage();
     }
     if (!dry_run && getpid() != 1) {
         // Show usage, it says we must be PID 1
         bb_show_usage();
     }
     // Additional sanity checks: we're about to rm -rf /, so be REALLY SURE
     // we mean it. I could make this a CONFIG option, but I would get email
     // from all the people who WILL destroy their filesystems.
     if (stat("/init", &st) != 0 || !S_ISREG(st.st_mode)) {
         bb_error_msg_and_die("'%s' is not a regular file", "/init");
     }
     statfs("/", &stfs); // this never fails
     if ((unsigned)stfs.f_type != RAMFS_MAGIC
      && (unsigned)stfs.f_type != TMPFS_MAGIC
     ) {
         bb_simple_error_msg_and_die("root filesystem is not ramfs/tmpfs");
     }
     if (!dry_run) {
         // Zap everything out of rootdev
         delete_contents("/", rootdev);
         // Overmount / with newdir and chroot into it
         if (mount(".", "/", NULL, MS_MOVE, NULL)) {
             // For example, fails when newroot is not a mountpoint
             bb_simple_perror_msg_and_die("error moving root");
         }
     }
     xchroot(".");
     // The chdir is needed to recalculate "." and ".." links
     /*xchdir("/"); - done in xchroot */
     // If a new console specified, redirect stdin/stdout/stderr to it
     if (console) {
         int fd = open_or_warn(console, O_RDWR);
         if (fd >= 0) {
             xmove_fd(fd, 0);
             xdup2(0, 1);
             xdup2(0, 2);
         }
     }
     if (dry_run) {
         // Does NEW_INIT look like it can be executed?
         //xstat(argv[0], &st);
         //if (!S_ISREG(st.st_mode))
         //  bb_perror_msg_and_die("'%s' is not a regular file", argv[0]);
         if (access(argv[0], X_OK) == 0)
             return 0;
     } else {
         // Exec NEW_INIT
         execv(argv[0], argv);
     }
     bb_perror_msg_and_die("can't execute '%s'", argv[0]);
 }
References access(), applet_name, argv, bb_error_msg_and_die(), bb_perror_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), delete_contents(), dev_t, execv(), statfs::f_type, fd, getopt32(), getpid(), mount(), MS_MOVE, NULL, O_RDWR, open_or_warn(), optind, RAMFS_MAGIC, S_ISREG, stat(), statfs(), TMPFS_MAGIC, X_OK, xchdir(), xchroot(), xdup2(), xmove_fd(), and xstat().