Fennix: Userspace/apps/base/busybox/scripts/kconfig/mconf.c File Reference
mconf.c File Reference
#include <sys/ioctl.h>
#include <sys/wait.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <termios.h>
#include <unistd.h>
#include <locale.h>
#include "lkc.h"
Macros
#define _XOPEN_SOURCE 700
#define _DARWIN_C_SOURCE 1
#define SIGWINCH 28
#define LKC_DIRECT_LINK
Functions
static void conf (struct menu *menu)
static void conf_choice (struct menu *menu)
static void conf_string (struct menu *menu)
static void conf_load (void)
static void conf_save (void)
static void show_textbox (const char *title, const char *text, int r, int c)
static void show_helptext (const char *title, const char *text)
static void show_help (struct menu *menu)
static void show_file (const char *filename, const char *title, int r, int c)
static void cprint_init (void)
static int cprint1 (const char *fmt,...)
static void cprint_done (void)
static int cprint (const char *fmt,...)
static void init_wsize (void)
static void get_prompt_str (struct gstr *r, struct property *prop)
static void get_symbol_str (struct gstr *r, struct symbol *sym)
static struct gstr get_relations_str (struct symbol **sym_arr)
static void winch_handler (int sig)
static int exec_conf (void)
static void search_conf (void)
static void build_conf (struct menu *menu)
static void conf_cleanup (void)
int main (int ac, char **av)
Variables
static char menu_backtitle [128]
static const char mconf_readme []
static const char menu_instructions []
static const char radiolist_instructions []
static const char inputbox_instructions_int []
static const char inputbox_instructions_hex []
static const char inputbox_instructions_string []
static const char setmod_text []
static const char nohelp_text []
static const char load_config_text []
static const char load_config_help []
static const char save_config_text []
static const char save_config_help []
static const char search_help []
static char buf [4096 *10]
static char * bufptr = buf
static char input_buf [4096]
static const char filename [] = ".config"
static char * args [1024]
static char ** argptr = args
static int indent
static struct termios ios_org
static int rows = 0
static int cols = 0
static struct menu * current_menu
static int child_count
static int do_resize
static int single_menu_mode
pid_t pid
Macro Definition Documentation
_DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE 1
Definition at line 13 of file mconf.c.
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 11 of file mconf.c.
LKC_DIRECT_LINK
#define LKC_DIRECT_LINK
Definition at line 34 of file mconf.c.
SIGWINCH
#define SIGWINCH 28
Definition at line 31 of file mconf.c.
Function Documentation
build_conf()
static void build_conf (struct menu * menu) static
Definition at line 575 of file mconf.c.
 {
     struct symbol *sym;
     struct property *prop;
     struct menu *child;
     int type, tmp, doint = 2;
     tristate val;
     char ch;
     if (!menu_is_visible(menu))
         return;
     sym = menu->sym;
     prop = menu->prompt;
     if (!sym) {
         if (prop && menu != current_menu) {
             const char *prompt = menu_get_prompt(menu);
             switch (prop->type) {
             case P_MENU:
                 child_count++;
                 cprint("m%p", menu);
                 if (single_menu_mode) {
                     cprint1("%s%*c%s",
                         menu->data ? "-->" : "++>",
                         indent + 1, ' ', prompt);
                 } else
                     cprint1("   %*c%s  --->", indent + 1, ' ', prompt);
                 cprint_done();
                 if (single_menu_mode && menu->data)
                     goto conf_childs;
                 return;
             default:
                 if (prompt) {
                     child_count++;
                     cprint(":%p", menu);
                     cprint("---%*c%s", indent + 1, ' ', prompt);
                 }
             }
         } else
             doint = 0;
         goto conf_childs;
     }
     type = sym_get_type(sym);
     if (sym_is_choice(sym)) {
         struct symbol *def_sym = sym_get_choice_value(sym);
         struct menu *def_menu = NULL;
         child_count++;
         for (child = menu->list; child; child = child->next) {
             if (menu_is_visible(child) && child->sym == def_sym)
                 def_menu = child;
         }
         val = sym_get_tristate_value(sym);
         if (sym_is_changable(sym)) {
             cprint("t%p", menu);
             switch (type) {
             case S_BOOLEAN:
                 cprint1("[%c]", val == no ? ' ' : '*');
                 break;
             case S_TRISTATE:
                 switch (val) {
                 case yes: ch = '*'; break;
                 case mod: ch = 'M'; break;
                 default:  ch = ' '; break;
                 }
                 cprint1("<%c>", ch);
                 break;
             }
         } else {
             cprint("%c%p", def_menu ? 't' : ':', menu);
             cprint1("   ");
         }
         cprint1("%*c%s", indent + 1, ' ', menu_get_prompt(menu));
         if (val == yes) {
             if (def_menu) {
                 cprint1(" (%s)", menu_get_prompt(def_menu));
                 cprint1("  --->");
                 cprint_done();
                 if (def_menu->list) {
                     indent += 2;
                     build_conf(def_menu);
                     indent -= 2;
                 }
             } else
                 cprint_done();
             return;
         }
         cprint_done();
     } else {
         if (menu == current_menu) {
             cprint(":%p", menu);
             cprint("---%*c%s", indent + 1, ' ', menu_get_prompt(menu));
             goto conf_childs;
         }
         child_count++;
         val = sym_get_tristate_value(sym);
         if (sym_is_choice_value(sym) && val == yes) {
             cprint(":%p", menu);
             cprint1("   ");
         } else {
             switch (type) {
             case S_BOOLEAN:
                 cprint("t%p", menu);
                 if (sym_is_changable(sym))
                     cprint1("[%c]", val == no ? ' ' : '*');
                 else
                     cprint1("---");
                 break;
             case S_TRISTATE:
                 cprint("t%p", menu);
                 switch (val) {
                 case yes: ch = '*'; break;
                 case mod: ch = 'M'; break;
                 default:  ch = ' '; break;
                 }
                 if (sym_is_changable(sym))
                     cprint1("<%c>", ch);
                 else
                     cprint1("---");
                 break;
             default:
                 cprint("s%p", menu);
                 tmp = cprint1("(%s)", sym_get_string_value(sym));
                 tmp = indent - tmp + 4;
                 if (tmp < 0)
                     tmp = 0;
                 cprint1("%*c%s%s", tmp, ' ', menu_get_prompt(menu),
                     (sym_has_value(sym) || !sym_is_changable(sym)) ?
                     "" : " (NEW)");
                 cprint_done();
                 goto conf_childs;
             }
         }
         cprint1("%*c%s%s", indent + 1, ' ', menu_get_prompt(menu),
             (sym_has_value(sym) || !sym_is_changable(sym)) ?
             "" : " (NEW)");
         if (menu->prompt->type == P_MENU) {
             cprint1("  --->");
             cprint_done();
             return;
         }
         cprint_done();
     }
 conf_childs:
     indent += doint;
     for (child = menu->list; child; child = child->next)
         build_conf(child);
     indent -= doint;
 }
References child(), child_count, cprint(), cprint1(), cprint_done(), current_menu, menu::data, indent, menu::list, menu_get_prompt(), menu_is_visible(), mod, child::next, no, NULL, P_MENU, prompt, menu::prompt, S_BOOLEAN, S_TRISTATE, single_menu_mode, menu::sym, sym_get_choice_value(), sym_get_string_value(), sym_get_tristate_value(), sym_get_type(), sym_has_value(), sym_is_changable(), sym_is_choice(), sym_is_choice_value(), type, property::type, val, and yes.
Referenced by conf().
conf()
static void conf (struct menu * menu) static
Definition at line 731 of file mconf.c.
 {
     struct menu *submenu;
     const char *prompt = menu_get_prompt(menu);
     struct symbol *sym;
     char active_entry[40];
     int stat, type, i;
     unlink("lxdialog.scrltmp");
     active_entry[0] = 0;
     while (1) {
         cprint_init();
         cprint("--title");
         cprint("%s", prompt ? prompt : _("Main Menu"));
         cprint("--menu");
         cprint(_(menu_instructions));
         cprint("%d", rows);
         cprint("%d", cols);
         cprint("%d", rows - 10);
         cprint("%s", active_entry);
         current_menu = menu;
         build_conf(menu);
         if (!child_count)
             break;
         if (menu == &rootmenu) {
             cprint(":");
             cprint("--- ");
             cprint("L");
             cprint(_("    Load an Alternate Configuration File"));
             cprint("S");
             cprint(_("    Save Configuration to an Alternate File"));
         }
         stat = exec_conf();
         if (stat < 0)
             continue;
         if (stat == 1 || stat == 255)
             break;
         type = input_buf[0];
         if (!type)
             continue;
         for (i = 0; input_buf[i] && !isspace((unsigned char)input_buf[i]); i++)
             ;
         if (i >= sizeof(active_entry))
             i = sizeof(active_entry) - 1;
         input_buf[i] = 0;
         strcpy(active_entry, input_buf);
         sym = NULL;
         submenu = NULL;
         if (sscanf(input_buf + 1, "%p", &submenu) == 1)
             sym = submenu->sym;
         switch (stat) {
         case 0:
             switch (type) {
             case 'm':
                 if (single_menu_mode)
                     submenu->data = (void *) (long) !submenu->data;
                 else
                     conf(submenu);
                 break;
             case 't':
                 if (sym_is_choice(sym) && sym_get_tristate_value(sym) == yes)
                     conf_choice(submenu);
                 else if (submenu->prompt->type == P_MENU)
                     conf(submenu);
                 break;
             case 's':
                 conf_string(submenu);
                 break;
             case 'L':
                 conf_load();
                 break;
             case 'S':
                 conf_save();
                 break;
             }
             break;
         case 2:
             if (sym)
                 show_help(submenu);
             else
                 show_helptext("README", _(mconf_readme));
             break;
         case 3:
             if (type == 't') {
                 if (sym_set_tristate_value(sym, yes))
                     break;
                 if (sym_set_tristate_value(sym, mod))
                     show_textbox(NULL, setmod_text, 6, 74);
             }
             break;
         case 4:
             if (type == 't')
                 sym_set_tristate_value(sym, no);
             break;
         case 5:
             if (type == 't')
                 sym_set_tristate_value(sym, mod);
             break;
         case 6:
             if (type == 't')
                 sym_toggle_tristate_value(sym);
             else if (type == 'm')
                 conf(submenu);
             break;
         case 7:
             search_conf();
             break;
         }
     }
 }
References _, build_conf(), child_count, cols, conf_choice(), conf_load(), conf_save(), conf_string(), cprint(), cprint_init(), current_menu, menu::data, exec_conf(), i, input_buf, isspace, mconf_readme, menu_get_prompt(), menu_instructions, mod, no, NULL, P_MENU, prompt, menu::prompt, rootmenu, rows, search_conf(), setmod_text, show_help(), show_helptext(), show_textbox(), single_menu_mode, sscanf(), stat(), strcpy, menu::sym, sym_get_tristate_value(), sym_is_choice(), sym_set_tristate_value(), sym_toggle_tristate_value(), type, property::type, unlink(), and yes.
Referenced by main().
conf_choice()
static void conf_choice (struct menu * menu) static
Definition at line 900 of file mconf.c.
 {
     const char *prompt = menu_get_prompt(menu);
     struct menu *child;
     struct symbol *active;
     int stat;
     active = sym_get_choice_value(menu->sym);
     while (1) {
         cprint_init();
         cprint("--title");
         cprint("%s", prompt ? prompt : _("Main Menu"));
         cprint("--radiolist");
         cprint(_(radiolist_instructions));
         cprint("15");
         cprint("70");
         cprint("6");
         current_menu = menu;
         for (child = menu->list; child; child = child->next) {
             if (!menu_is_visible(child))
                 continue;
             cprint("%p", child);
             cprint("%s", menu_get_prompt(child));
             if (child->sym == sym_get_choice_value(menu->sym))
                 cprint("ON");
             else if (child->sym == active)
                 cprint("SELECTED");
             else
                 cprint("OFF");
         }
         stat = exec_conf();
         switch (stat) {
         case 0:
             if (sscanf(input_buf, "%p", &child) != 1)
                 break;
             sym_set_tristate_value(child->sym, yes);
             return;
         case 1:
             if (sscanf(input_buf, "%p", &child) == 1) {
                 show_help(child);
                 active = child->sym;
             } else
                 show_help(menu);
             break;
         case 255:
             return;
         }
     }
 }
References _, child(), cprint(), cprint_init(), current_menu, exec_conf(), input_buf, menu::list, menu_get_prompt(), menu_is_visible(), child::next, prompt, radiolist_instructions, show_help(), sscanf(), stat(), menu::sym, sym_get_choice_value(), sym_set_tristate_value(), and yes.
Referenced by conf().
conf_cleanup()
static void conf_cleanup (void) static
Definition at line 1052 of file mconf.c.
 {
     tcsetattr(1, TCSAFLUSH, &ios_org);
     unlink(".help.tmp");
     unlink("lxdialog.scrltmp");
 }
References ios_org, TCSAFLUSH, tcsetattr(), and unlink().
Referenced by main().
conf_load()
static void conf_load (void) static
Definition at line 994 of file mconf.c.
 {
     int stat;
     while (1) {
         cprint_init();
         cprint("--inputbox");
         cprint(load_config_text);
         cprint("11");
         cprint("55");
         cprint("%s", filename);
         stat = exec_conf();
         switch(stat) {
         case 0:
             if (!input_buf[0])
                 return;
             if (!conf_read(input_buf))
                 return;
             show_textbox(NULL, _("File does not exist!"), 5, 38);
             break;
         case 1:
             show_helptext(_("Load Alternate Configuration"), load_config_help);
             break;
         case 255:
             return;
         }
     }
 }
References _, conf_read(), cprint(), cprint_init(), exec_conf(), filename, input_buf, load_config_help, load_config_text, NULL, show_helptext(), show_textbox(), and stat().
Referenced by conf().
conf_save()
static void conf_save (void) static
Definition at line 1023 of file mconf.c.
 {
     int stat;
     while (1) {
         cprint_init();
         cprint("--inputbox");
         cprint(save_config_text);
         cprint("11");
         cprint("55");
         cprint("%s", filename);
         stat = exec_conf();
         switch(stat) {
         case 0:
             if (!input_buf[0])
                 return;
             if (!conf_write(input_buf))
                 return;
             show_textbox(NULL, _("Can't create file!  Probably a nonexistent directory."), 5, 60);
             break;
         case 1:
             show_helptext(_("Save Alternate Configuration"), save_config_help);
             break;
         case 255:
             return;
         }
     }
 }
References _, conf_write(), cprint(), cprint_init(), exec_conf(), filename, input_buf, NULL, save_config_help, save_config_text, show_helptext(), show_textbox(), and stat().
Referenced by conf().
conf_string()
static void conf_string (struct menu * menu) static
Definition at line 952 of file mconf.c.
 {
     const char *prompt = menu_get_prompt(menu);
     int stat;
     while (1) {
         cprint_init();
         cprint("--title");
         cprint("%s", prompt ? prompt : _("Main Menu"));
         cprint("--inputbox");
         switch (sym_get_type(menu->sym)) {
         case S_INT:
             cprint(_(inputbox_instructions_int));
             break;
         case S_HEX:
             cprint(_(inputbox_instructions_hex));
             break;
         case S_STRING:
             cprint(_(inputbox_instructions_string));
             break;
         default:
             /* panic? */;
         }
         cprint("10");
         cprint("75");
         cprint("%s", sym_get_string_value(menu->sym));
         stat = exec_conf();
         switch (stat) {
         case 0:
             if (sym_set_string_value(menu->sym, input_buf))
                 return;
             show_textbox(NULL, _("You have made an invalid entry."), 5, 43);
             break;
         case 1:
             show_help(menu);
             break;
         case 255:
             return;
         }
     }
 }
References _, cprint(), cprint_init(), exec_conf(), input_buf, inputbox_instructions_hex, inputbox_instructions_int, inputbox_instructions_string, menu_get_prompt(), NULL, prompt, S_HEX, S_INT, S_STRING, show_help(), show_textbox(), stat(), menu::sym, sym_get_string_value(), sym_get_type(), and sym_set_string_value().
Referenced by conf().
cprint()
static int cprint (const char * fmt, ...) static
Definition at line 363 of file mconf.c.
 {
     va_list ap;
     int res;
     *argptr++ = bufptr;
     va_start(ap, fmt);
     res = vsprintf(bufptr, fmt, ap);
     va_end(ap);
     bufptr += res;
     *bufptr++ = 0;
     return res;
 }
References ap, argptr, bufptr, va_end, va_start, and vsprintf().
Referenced by build_conf(), conf(), conf_choice(), conf_load(), conf_save(), conf_string(), cprint_init(), main(), search_conf(), and show_file().
cprint1()
static int cprint1 (const char * fmt, ...) static
Definition at line 342 of file mconf.c.
 {
     va_list ap;
     int res;
     if (!*argptr)
         *argptr = bufptr;
     va_start(ap, fmt);
     res = vsprintf(bufptr, fmt, ap);
     va_end(ap);
     bufptr += res;
     return res;
 }
References ap, argptr, bufptr, va_end, va_start, and vsprintf().
Referenced by build_conf().
cprint_done()
static void cprint_done (void) static
Definition at line 357 of file mconf.c.
 {
     *bufptr++ = 0;
     argptr++;
 }
References argptr, and bufptr.
Referenced by build_conf().
cprint_init()
static void cprint_init (void) static
Definition at line 330 of file mconf.c.
 {
     bufptr = buf;
     argptr = args;
     memset(args, 0, sizeof(args));
     indent = 0;
     child_count = 0;
     cprint("./scripts/kconfig/lxdialog/lxdialog");
     cprint("--backtitle");
     cprint(menu_backtitle);
 }
References argptr, args, buf, bufptr, child_count, cprint(), indent, memset, and menu_backtitle.
Referenced by conf(), conf_choice(), conf_load(), conf_save(), conf_string(), main(), search_conf(), and show_file().
exec_conf()
static int exec_conf (void) static
Definition at line 462 of file mconf.c.
 {
     int pipefd[2], stat, size;
     sigset_t sset, osset;
     sigemptyset(&sset);
     sigaddset(&sset, SIGINT);
     sigprocmask(SIG_BLOCK, &sset, &osset);
     signal(SIGINT, SIG_DFL);
 #ifdef SIGWINCH
     {
         struct sigaction sa;
         sa.sa_handler = winch_handler;
         sigemptyset(&sa.sa_mask);
         sa.sa_flags = SA_RESTART;
         sigaction(SIGWINCH, &sa, NULL);
     }
 #endif
     *argptr++ = NULL;
     if (pipe(pipefd))
         _exit(EXIT_FAILURE);
     pid = fork();
     if (pid == 0) {
         sigprocmask(SIG_SETMASK, &osset, NULL);
         dup2(pipefd[1], 2);
         close(pipefd[0]);
         close(pipefd[1]);
         execv(args[0], args);
         _exit(EXIT_FAILURE);
     }
     close(pipefd[1]);
     bufptr = input_buf;
     while (1) {
         size = input_buf + sizeof(input_buf) - bufptr;
         size = read(pipefd[0], bufptr, size);
         if (size <= 0) {
             if (size < 0) {
                 if (errno == EINTR || errno == EAGAIN)
                     continue;
                 perror("read");
             }
             break;
         }
         bufptr += size;
     }
     *bufptr++ = 0;
     close(pipefd[0]);
     waitpid(pid, &stat, 0);
     if (do_resize) {
         init_wsize();
         do_resize = 0;
         sigprocmask(SIG_SETMASK, &osset, NULL);
         return -1;
     }
     if (WIFSIGNALED(stat)) {
         printf("\finterrupted(%d)\n", WTERMSIG(stat));
         exit(1);
     }
 #if 0
     printf("\fexit state: %d\nexit data: '%s'\n", WEXITSTATUS(stat), input_buf);
     sleep(1);
 #endif
     sigpending(&sset);
     if (sigismember(&sset, SIGINT)) {
         printf("\finterrupted\n");
         exit(1);
     }
     sigprocmask(SIG_SETMASK, &osset, NULL);
     return WEXITSTATUS(stat);
 }
References _exit(), argptr, bufptr, close(), do_resize, dup2(), EAGAIN, EINTR, errno, execv(), exit(), EXIT_FAILURE, fork(), init_wsize(), input_buf, NULL, perror(), pid, pipe(), printf, read(), SA_RESTART, SIG_BLOCK, SIG_DFL, SIG_SETMASK, sigaddset(), sigemptyset(), SIGINT, sigismember(), signal, sigpending(), sigprocmask(), SIGWINCH, size, sleep(), stat(), waitpid(), WEXITSTATUS, WIFSIGNALED, winch_handler(), and WTERMSIG.
Referenced by conf(), conf_choice(), conf_load(), conf_save(), conf_string(), main(), search_conf(), and show_file().
get_prompt_str()
static void get_prompt_str (struct gstr * r, struct property * prop) static
Definition at line 378 of file mconf.c.
 {
     int i, j;
     struct menu *submenu[8], *menu;
     str_printf(r, "Prompt: %s\n", prop->text);
     str_printf(r, "  Defined at %s:%d\n", prop->menu->file->name,
         prop->menu->lineno);
     if (!expr_is_yes(prop->visible.expr)) {
         str_append(r, "  Depends on: ");
         expr_gstr_print(prop->visible.expr, r);
         str_append(r, "\n");
     }
     menu = prop->menu->parent;
     for (i = 0; menu != &rootmenu && i < 8; menu = menu->parent)
         submenu[i++] = menu;
     if (i > 0) {
         str_printf(r, "  Location:\n");
         for (j = 4; --i >= 0; j += 2) {
             menu = submenu[i];
             str_printf(r, "%*c-> %s", j, ' ', menu_get_prompt(menu));
             if (menu->sym) {
                 str_printf(r, " (%s [=%s])", menu->sym->name ?
                     menu->sym->name : "<choice>",
                     sym_get_string_value(menu->sym));
             }
             str_append(r, "\n");
         }
     }
 }
References expr_value::expr, expr_gstr_print(), expr_is_yes(), menu::file, i, j, menu::lineno, property::menu, menu_get_prompt(), file::name, symbol::name, menu::parent, rootmenu, str_append(), str_printf(), menu::sym, sym_get_string_value(), property::text, and property::visible.
Referenced by get_relations_str().
get_relations_str()
static struct gstr get_relations_str (struct symbol ** sym_arr) static
Definition at line 409 of file mconf.c.
 {
     struct symbol *sym;
     struct gstr res = str_new();
     int i;
     for (i = 0; sym_arr && (sym = sym_arr[i]); i++)
         get_symbol_str(&res, sym);
     if (!i)
         str_append(&res, "No matches found.\n");
     return res;
 }
References expr_value::expr, property::expr, expr_gstr_print(), for_all_prompts, for_all_properties, get_prompt_str(), symbol::name, P_SELECT, symbol::rev_dep, str_append(), str_printf(), property::sym, and sym_get_string_value().
Referenced by search_conf().
get_symbol_str()
static void get_symbol_str (struct gstr * r, struct symbol * sym) static
Definition at line 409 of file mconf.c.
 {
     bool hit;
     struct property *prop;
     str_printf(r, "Symbol: %s [=%s]\n", sym->name,
                                    sym_get_string_value(sym));
     for_all_prompts(sym, prop)
         get_prompt_str(r, prop);
     hit = false;
     for_all_properties(sym, prop, P_SELECT) {
         if (!hit) {
             str_append(r, "  Selects: ");
             hit = true;
         } else
             str_printf(r, " && ");
         expr_gstr_print(prop->expr, r);
     }
     if (hit)
         str_append(r, "\n");
     if (sym->rev_dep.expr) {
         str_append(r, "  Selected by: ");
         expr_gstr_print(sym->rev_dep.expr, r);
         str_append(r, "\n");
     }
     str_append(r, "\n\n");
 }
Referenced by show_help().
init_wsize()
static void init_wsize (void) static
Definition at line 295 of file mconf.c.
 {
     struct winsize ws;
     char *env;
     if (!ioctl(STDIN_FILENO, TIOCGWINSZ, &ws)) {
         rows = ws.ws_row;
         cols = ws.ws_col;
     }
     if (!rows) {
         env = getenv("LINES");
         if (env)
             rows = atoi(env);
         if (!rows)
             rows = 24;
     }
     if (!cols) {
         env = getenv("COLUMNS");
         if (env)
             cols = atoi(env);
         if (!cols)
             cols = 80;
     }
     if (rows < 19 || cols < 80) {
         fprintf(stderr, N_("Your display is too small to run Menuconfig!\n"));
         fprintf(stderr, N_("It must be at least 19 lines by 80 columns.\n"));
         exit(1);
     }
     rows -= 4;
     cols -= 5;
 }
References atoi(), cols, env, exit(), fprintf(), getenv, ioctl(), N_, rows, stderr, STDIN_FILENO, TIOCGWINSZ, winsize::ws_col, and winsize::ws_row.
Referenced by exec_conf(), and main().
main()
int main (int ac, char ** av)
Definition at line 1059 of file mconf.c.
 {
     struct symbol *sym;
     char *mode;
     int stat;
     setlocale(LC_ALL, "");
     bindtextdomain(PACKAGE, LOCALEDIR);
     textdomain(PACKAGE);
     conf_parse(av[1]);
     conf_read(NULL);
     sym = sym_lookup("KERNELVERSION", 0);
     sym_calc_value(sym);
     sprintf(menu_backtitle, _("BusyBox %s Configuration"),
         sym_get_string_value(sym));
     mode = getenv("MENUCONFIG_MODE");
     if (mode) {
         if (!strcasecmp(mode, "single_menu"))
             single_menu_mode = 1;
     }
     tcgetattr(1, &ios_org);
     atexit(conf_cleanup);
     init_wsize();
     conf(&rootmenu);
     do {
         cprint_init();
         cprint("--yesno");
         cprint(_("Do you wish to save your new configuration?"));
         cprint("5");
         cprint("60");
         stat = exec_conf();
     } while (stat < 0);
     if (stat == 0) {
         if (conf_write(NULL)) {
             fprintf(stderr, _("\n\n"
                 "Error during writing of the configuration.\n"
                 "Your configuration changes were NOT saved."
                 "\n\n"));
             return 1;
         }
         printf(_("\n\n"
             "*** End of configuration.\n"
             "*** Execute 'make' to build the project or try 'make help'."
             "\n\n"));
     } else {
         fprintf(stderr, _("\n\n"
             "Your configuration changes were NOT saved."
             "\n\n"));
     }
     return 0;
 }
References _, atexit, bindtextdomain, conf(), conf_cleanup(), conf_read(), conf_write(), cprint(), cprint_init(), exec_conf(), fprintf(), getenv, init_wsize(), ios_org, LC_ALL, LOCALEDIR, menu_backtitle, NULL, PACKAGE, printf, rootmenu, setlocale, single_menu_mode, sprintf(), stat(), stderr, strcasecmp, sym_calc_value(), sym_get_string_value(), sym_lookup(), tcgetattr(), and textdomain.
search_conf()
static void search_conf (void) static
Definition at line 540 of file mconf.c.
 {
     struct symbol **sym_arr;
     int stat;
     struct gstr res;
 again:
     cprint_init();
     cprint("--title");
     cprint(_("Search Configuration Parameter"));
     cprint("--inputbox");
     cprint(_("Enter CONFIG_ (sub)string to search for (omit CONFIG_)"));
     cprint("10");
     cprint("75");
     cprint("");
     stat = exec_conf();
     if (stat < 0)
         goto again;
     switch (stat) {
     case 0:
         break;
     case 1:
         show_helptext(_("Search Configuration"), search_help);
         goto again;
     default:
         return;
     }
     sym_arr = sym_re_search(input_buf);
     res = get_relations_str(sym_arr);
     free(sym_arr);
     show_textbox(_("Search Results"), str_get(&res), 0, 0);
     str_free(&res);
 }
References _, cprint(), cprint_init(), exec_conf(), free, get_relations_str(), input_buf, search_help, show_helptext(), show_textbox(), stat(), str_free(), str_get(), and sym_re_search().
Referenced by conf().
show_file()
static void show_file (const char * filename, const char * title, int r, int c) static
Definition at line 885 of file mconf.c.
 {
     do {
         cprint_init();
         if (title) {
             cprint("--title");
             cprint("%s", title);
         }
         cprint("--textbox");
         cprint("%s", filename);
         cprint("%d", r ? r : rows);
         cprint("%d", c ? c : cols);
     } while (exec_conf() < 0);
 }
References c, cols, cprint(), cprint_init(), exec_conf(), filename, rows, and title.
Referenced by show_textbox().
show_help()
static void show_help (struct menu * menu) static
Definition at line 865 of file mconf.c.
 {
     struct gstr help = str_new();
     struct symbol *sym = menu->sym;
     if (sym->help)
     {
         if (sym->name) {
             str_printf(&help, "CONFIG_%s:\n\n", sym->name);
             str_append(&help, _(sym->help));
             str_append(&help, "\n");
         }
     } else {
         str_append(&help, nohelp_text);
     }
     get_symbol_str(&help, sym);
     show_helptext(menu_get_prompt(menu), str_get(&help));
     str_free(&help);
 }
References _, get_symbol_str(), symbol::help, menu_get_prompt(), symbol::name, nohelp_text, show_helptext(), str_append(), str_free(), str_get(), str_new(), str_printf(), and menu::sym.
Referenced by conf(), conf_choice(), and conf_string().
show_helptext()
static void show_helptext (const char * title, const char * text) static
Definition at line 860 of file mconf.c.
 {
     show_textbox(title, text, 0, 0);
 }
References show_textbox(), text, and title.
Referenced by conf(), conf_load(), conf_save(), search_conf(), and show_help().
show_textbox()
static void show_textbox (const char * title, const char * text, int r, int c) static
Definition at line 847 of file mconf.c.
 {
     int fd;
     int len = strlen(text);
     fd = creat(".help.tmp", 0777);
     if (write(fd, text, len) != len)
         exit(1);
     close(fd);
     show_file(".help.tmp", title, r, c);
     unlink(".help.tmp");
 }
References c, close(), creat(), exit(), fd, len, show_file(), strlen(), text, title, unlink(), and write().
Referenced by conf(), conf_load(), conf_save(), conf_string(), search_conf(), and show_helptext().
winch_handler()
static void winch_handler (int sig) static
Definition at line 453 of file mconf.c.
 {
     if (!do_resize) {
         kill(pid, SIGINT);
         do_resize = 1;
     }
 }
References do_resize, kill(), pid, and SIGINT.
Referenced by edit_file(), and exec_conf().
Variable Documentation
argptr
char ** argptr = args static
Definition at line 271 of file mconf.c.
Referenced by cprint(), cprint1(), cprint_done(), cprint_init(), exec_conf(), and I_Error().
args
char* args[1024] static
Definition at line 271 of file mconf.c.
Referenced by cprint_init().
buf
char buf[4096 *10] static
Definition at line 268 of file mconf.c.
Referenced by cprint_init().
bufptr
char * bufptr = buf static
Definition at line 268 of file mconf.c.
Referenced by cprint(), cprint1(), cprint_done(), cprint_init(), exec_conf(), normalize(), and scan_request().
child_count
int child_count static
Definition at line 276 of file mconf.c.
Referenced by build_conf(), conf(), and cprint_init().
cols
int cols = 0 static
Definition at line 274 of file mconf.c.
Referenced by _rl_set_screen_size(), complete_get_screenwidth(), conf(), init_wsize(), rl_display_match_list(), rl_get_screen_size(), rl_set_screen_size(), sh_set_lines_and_columns(), show_file(), and xxd_main().
current_menu
struct menu* current_menu static
Definition at line 275 of file mconf.c.
Referenced by build_conf(), conf(), conf_choice(), menu_add_entry(), menu_add_menu(), menu_end_menu(), and menu_init().
do_resize
int do_resize static
Definition at line 277 of file mconf.c.
Referenced by exec_conf(), and winch_handler().
filename
const char filename[] = ".config" static
Definition at line 270 of file mconf.c.
Referenced by conf_load(), conf_save(), and show_file().
indent
int indent static
Definition at line 272 of file mconf.c.
Referenced by build_conf(), and cprint_init().
input_buf
char input_buf[4096] static
Definition at line 269 of file mconf.c.
Referenced by conf(), conf_choice(), conf_load(), conf_save(), conf_string(), exec_conf(), and search_conf().
inputbox_instructions_hex
const char inputbox_instructions_hex[] static
Initial value:
= N_(
    "Please enter a hexadecimal value. "
    "Use the <TAB> key to move from the input field to the buttons below it.")
Definition at line 188 of file mconf.c.
Referenced by conf_string().
inputbox_instructions_int
const char inputbox_instructions_int[] static
Initial value:
= N_(
    "Please enter a decimal value. "
    "Fractions will not be accepted.  "
    "Use the <TAB> key to move from the input field to the buttons below it.")
Definition at line 184 of file mconf.c.
Referenced by conf_string().
inputbox_instructions_string
const char inputbox_instructions_string[] static
Initial value:
= N_(
    "Please enter a string value. "
    "Use the <TAB> key to move from the input field to the buttons below it.")
Definition at line 191 of file mconf.c.
Referenced by conf_string().
ios_org
struct termios ios_org static
Definition at line 272 of file mconf.c.
Referenced by conf_cleanup(), and main().
load_config_help
const char load_config_help[] static
Initial value:
= N_(
    "\n"
    "For various reasons, one may wish to keep several different\n"
    "configurations available on a single machine.\n"
    "\n"
    "If you have saved a previous configuration in a file other than\n"
    "default, entering the name of the file here will allow you\n"
    "to modify that configuration.\n"
    "\n"
    "If you are uncertain, then you have probably never used alternate\n"
    "configuration files.  You should therefor leave this blank to abort.\n")
Definition at line 203 of file mconf.c.
Referenced by conf_load().
load_config_text
const char load_config_text[] static
Initial value:
= N_(
    "Enter the name of the configuration file you wish to load.  "
    "Accept the name shown to restore the configuration you "
    "last retrieved.  Leave blank to abort.")
Definition at line 199 of file mconf.c.
Referenced by conf_load().
mconf_readme
const char mconf_readme[] static
Definition at line 38 of file mconf.c.
Referenced by conf().
menu_backtitle
char menu_backtitle[128] static
Definition at line 37 of file mconf.c.
Referenced by cprint_init(), and main().
menu_instructions
const char menu_instructions[] static
Initial value:
= N_(
    "Arrow keys navigate the menu.  "
    "<Enter> selects submenus --->.  "
    "Highlighted letters are hotkeys.  "
    "Pressing <Y> includes, <N> excludes, <M> modularizes features.  "
    "Press <Esc><Esc> to exit, <?> for Help, </> for Search.  "
    "Legend: [*] built-in  [ ] excluded  <M> module  < > module capable")
Definition at line 172 of file mconf.c.
Referenced by conf().
nohelp_text
const char nohelp_text[] static
Initial value:
= N_(
    "There is no help available for this option.\n")
Definition at line 197 of file mconf.c.
Referenced by show_help().
pid
pid_t pid
Definition at line 450 of file mconf.c.
Referenced by __sched_rr_get_interval_time32(), __wait4_time32(), _vsyslog(), act(), add_pid(), add_proc(), add_process(), append_process(), bgp_add(), bgp_delete(), bgp_search(), bootchartd_main(), check(), chrt_main(), cleanup_dead_jobs(), clock_getcpuclockid(), cmd_kill(), command_substitute(), custom(), data_extract_to_command(), delete_old_job(), describe_pid(), do_pidfile(), do_procinit(), do_rescan(), do_wordexp(), dowait(), dump_procs(), edit_file(), exec_conf(), exec_kernel_doc(), execute(), execute_disk_command(), faccessat(), find_index_by_pid(), find_job(), find_pid_in_pipeline(), find_pipeline(), find_proc(), find_proc_slot(), find_process(), find_status_by_pid(), find_termsig_by_pid(), fork_or_rexec(), fork_transformer(), forkparent(), forkpty(), forkshell(), generate_uuid(), get_aff(), get_bashpid(), get_job_by_pid(), get_pid_flags(), get_random_number(), getpgid(), getsid(), getty_main(), handle_sigchld(), history_tempfile(), inetd_main(), ionice_main(), ipsvd_perhost_remove(), kill(), kill_main(), kill_pid(), launch_helper(), linux_wait4(), main(), make_child(), make_new_session(), mark_dead_jobs_as_notified(), mark_terminated(), mount_namespaces(), nc_main(), new_proc(), parse(), pause_and_low_level_reboot(), pclose(), pgrep_main(), pid_is_exec(), pid_is_name(), pid_is_user(), pmap_main(), popen(), popen_ls(), popmaildir_main(), posix_spawn(), print_sem(), print_waitstat(), prlimit(), process_pid_str(), process_vm_readv(), process_vm_writev(), processorstart(), procps_get_maps(), procps_scan(), pshash_getbucket(), pstree_main(), ptrace(), push_builtin(), pwdx_main(), read_cmdline(), reap(), reap_child(), resuse_end(), run(), run_actions(), run_command(), runsv(), runsv_main(), runsvdir_main(), safe_waitpid(), save_proc_status(), scan_recursive(), sched_rr_get_interval(), set_pid_flags(), set_pid_status(), setpgid(), setpgid_builtin(), setsid_main(), setup_heredoc(), sig_child_handler(), sigqueue(), spawn(), start_job(), start_jobs(), start_one_job(), start_shell_in_child(), start_stop_daemon_main(), system(), tcpudpsvd_main(), timeout_main(), timeout_wait(), unset_pid_flags(), update_utmp(), update_utmp_DEAD_PROCESS(), wait4(), wait4pid(), wait_for(), wait_for_any_job(), wait_for_background_pids(), wait_for_exitstatus(), wait_for_job(), wait_for_single_pid(), wait_one(), waitchld(), waitcmd(), waitfor(), waitone(), waitpid(), winch_handler(), write_new_utmp(), xargs_exec(), xspawn(), and xvfork_parent_waits_and_exits().
radiolist_instructions
const char radiolist_instructions[] static
Initial value:
= N_(
    "Use the arrow keys to navigate this window or "
    "press the hotkey of the item you wish to select "
    "followed by the <SPACE BAR>. "
    "Press <?> for additional information about this option.")
Definition at line 179 of file mconf.c.
Referenced by conf_choice().
rows
int rows = 0 static
Definition at line 274 of file mconf.c.
Referenced by conf(), init_wsize(), and show_file().
save_config_help
const char save_config_help[] static
Initial value:
= N_(
    "\n"
    "For various reasons, one may wish to keep different\n"
    "configurations available on a single machine.\n"
    "\n"
    "Entering a file name here will allow you to later retrieve, modify\n"
    "and use the current configuration as an alternate to whatever\n"
    "configuration options you have selected at that time.\n"
    "\n"
    "If you are uncertain what all this means then you should probably\n"
    "leave this blank.\n")
Definition at line 217 of file mconf.c.
Referenced by conf_save().
save_config_text
const char save_config_text[] static
Initial value:
= N_(
    "Enter a filename to which this configuration should be saved "
    "as an alternate.  Leave blank to abort.")
Definition at line 214 of file mconf.c.
Referenced by conf_save().
search_help
const char search_help[] static
Definition at line 228 of file mconf.c.
Referenced by search_conf().
setmod_text
const char setmod_text[] static
Initial value:
= N_(
    "This feature depends on another which has been configured as a module.\n"
    "As a result, this feature will be built as a module.")
Definition at line 194 of file mconf.c.
Referenced by conf().
single_menu_mode
int single_menu_mode static
Definition at line 278 of file mconf.c.
Referenced by build_conf(), conf(), and main().