Fennix Userspace: Userspace/apps/base/bash/lib/sh/strtoimax.c File Reference
strtoimax.c File Reference
#include <stdc.h>
Macros
#define verify(name, assertion) struct name { char a[(assertion) ? 1 : -1]; }
Functions
this configure time declaration test was not run long strtol PARAMS ((const char *, char **, int))
this configure time declaration test was not run intmax_t strtoimax (char *ptr, char **endptr, int base) const
Macro Definition Documentation
verify
#define verify (name, assertion) struct name { char a[(assertion) ? 1 : -1]; }
Definition at line 42 of file strtoimax.c.
Function Documentation
PARAMS()
this configure time declaration test was not run long strtol PARAMS ((const char *, char **, int))
strtoimax()
this configure time declaration test was not run intmax_t strtoimax (char * ptr, char ** endptr, int base) const
Definition at line 63 of file strtoimax.c.
 {
 #if HAVE_LONG_LONG_INT
   verify(size_is_that_of_long_or_long_long,
      (sizeof (intmax_t) == sizeof (long) ||
       sizeof (intmax_t) == sizeof (long long)));
   if (sizeof (intmax_t) != sizeof (long))
     return (strtoll (ptr, endptr, base));
 #else
   verify (size_is_that_of_long, sizeof (intmax_t) == sizeof (long));
 #endif
   return (strtol (ptr, endptr, base));
 }
References base, endptr, strtol(), strtoll(), and verify.
Referenced by legal_number().