Fennix: Userspace/libc/ElfInterpreter/resolve.c File Reference
resolve.c File Reference
#include "elf.h"
Data Structures
struct LibAddressCollection
Macros
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#define MAX(a, b) (((a) > (b)) ? (a) : (b))
Functions
__attribute__ ((naked, used, no_stack_protector))
long abs (long i)
void swap (char *x, char *y)
char * reverse (char *Buffer, int i, int j)
char * ltoa (long Value, char *Buffer, int Base)
static void PutCharToKernelConsole (char c)
void * memcpy (void *dest, const void *src, __SIZE_TYPE__ n)
int strcmp (const char *l, const char *r)
Elf64_Sym * ELFGetSymbol (__UINTPTR_TYPE__ *ElfFile, char *SymbolName)
void Print (char *String)
void PrintNL (char *String)
void * SymbolNotFound ()
Variables
static char Lock = 0
long RelTmpIndex = 0xdead
void(*)() ELF_LAZY_RESOLVE_MAIN (struct LibAddressCollection *Info, long RelIndex)
Data Structure Documentation
LibAddressCollection
struct LibAddressCollection
Definition at line 3 of file resolve.c.
Data Fields
__UINTPTR_TYPE__ * ElfFile
__UINTPTR_TYPE__ * MemoryImage
char Name[32]
struct LibAddressCollection * Next
__UINTPTR_TYPE__ * ParentElfFile
__UINTPTR_TYPE__ * ParentMemoryImage
char Valid
Macro Definition Documentation
MAX
#define MAX (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 15 of file resolve.c.
MIN
#define MIN (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 14 of file resolve.c.
Function Documentation
__attribute__()
__attribute__ ((naked, used, no_stack_protector))
Definition at line 19 of file resolve.c.
 {
     while (Lock == 1)
         ;
     __asm__ __volatile__("mfence\n");
     Lock = 1;
     __asm__ __volatile__("pop %r11\n"
                          "pop %r10\n"
                          "push %rdi\n"
                          "push %rsi\n"
                          "push %rdx\n"
                          "push %rcx\n"
                          "push %r8\n"
                          "push %r9\n"
                          "mov %r11, %rdi\n"
                          "mov %r10, %rsi\n"
                          "call ELF_LAZY_RESOLVE_MAIN\n"
                          "mov %rax, %r11\n"
                          "pop %r9\n"
                          "pop %r8\n"
                          "pop %rcx\n"
                          "pop %rdx\n"
                          "pop %rsi\n"
                          "pop %rdi\n"
                          "jmp *%r11\n");
 }
References Lock.
abs()
long abs (long i)
Definition at line 52 of file resolve.c.
 { return i < 0 ? -i : i; }
Referenced by ltoa().
ELFGetSymbol()
Elf64_Sym* ELFGetSymbol (__UINTPTR_TYPE__ * ElfFile, char * SymbolName)
Definition at line 120 of file resolve.c.
 {
     struct Elf64_Dyn *_SymTab = ELFGetDynamicTag(ElfFile, DT_SYMTAB);
     struct Elf64_Dyn *_StrTab = ELFGetDynamicTag(ElfFile, DT_STRTAB);
     Elf64_Sym *DynSym = (Elf64_Sym *)(ElfFile + _SymTab->d_un.d_ptr);
     char *DynStr = (char *)(ElfFile + _StrTab->d_un.d_ptr);
     for (int i = 0; i < _SymTab->d_un.d_val; i++)
     {
         if (strcmp(DynStr + DynSym[i].st_name, SymbolName) == 0)
             return &DynSym[i];
     }
     return (Elf64_Sym *)0;
 }
References Elf64_Dyn::d_un, DT_STRTAB, DT_SYMTAB, Execute::ELFGetDynamicTag(), and strcmp().
ltoa()
char* ltoa (long Value, char * Buffer, int Base)
Definition at line 68 of file resolve.c.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     long n = abs(Value);
     int i = 0;
     while (n)
     {
         int r = n % Base;
         if (r >= 10)
             Buffer[i++] = 65 + (r - 10);
         else
             Buffer[i++] = 48 + r;
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), and reverse().
Referenced by SymbolNotFound().
memcpy()
void* memcpy (void * dest, const void * src, __SIZE_TYPE__ n)
Definition at line 104 of file resolve.c.
 {
     __UINT8_TYPE__ *d = dest;
     const __UINT8_TYPE__ *s = src;
     while (n--)
         *d++ = *s++;
     return dest;
 }
Print()
void Print (char * String)
Definition at line 135 of file resolve.c.
 {
     for (short i = 0; String[i] != '\0'; i++)
         PutCharToKernelConsole(String[i]);
 }
References PutCharToKernelConsole().
Referenced by efi_main(), and SymbolNotFound().
PrintNL()
void PrintNL (char * String)
Definition at line 141 of file resolve.c.
 {
     for (short i = 0; String[i] != '\0'; i++)
         PutCharToKernelConsole(String[i]);
     PutCharToKernelConsole('\n');
 }
References PutCharToKernelConsole().
Referenced by SymbolNotFound().
PutCharToKernelConsole()
static void PutCharToKernelConsole (char c) inline static
Definition at line 96 of file resolve.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(1), "D"(c), "S"(0)
                          : "rcx", "r11", "memory");
 }
Referenced by Print(), and PrintNL().
reverse()
char* reverse (char * Buffer, int i, int j)
Definition at line 61 of file resolve.c.
 {
     while (i < j)
         swap(&Buffer[i++], &Buffer[j--]);
     return Buffer;
 }
References swap().
Referenced by ltoa().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 113 of file resolve.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
Referenced by APIC::APIC::APIC(), CPU::CheckSIMD(), Driver::Driver::Driver(), ELFGetSymbol(), Execute::ELFLoadExec(), Execute::ELFLookupSymbol(), VirtualFileSystem::Virtual::GetChild(), VirtualFileSystem::Virtual::GetNodeFromPath(), VirtualFileSystem::Virtual::GetParent(), CPU::InitializeFeatures(), APIC::Timer::OneShot(), VirtualFileSystem::Virtual::Open(), String::operator!=(), String::operator==(), ParseConfig(), Random::rand16(), Random::rand32(), Random::rand64(), VirtualFileSystem::Virtual::RemoveChild(), InterProcessCommunication::IPC::SearchByToken(), Tasking::Task::Task(), and CrashHandler::UserInput().
swap()
void swap (char * x, char * y)
Definition at line 54 of file resolve.c.
 {
     char t = *x;
     *x = *y;
     *y = t;
 }
Referenced by reverse().
SymbolNotFound()
void* SymbolNotFound ()
Definition at line 151 of file resolve.c.
 {
     // TODO: Print the symbol name and the library name.
     // TODO: This should go to the stderr.
     char Buffer[32];
     Print("Symbol index ");
     ltoa(RelTmpIndex, Buffer, 10);
     Print(Buffer);
     PrintNL(" not found");
     return (void *)0xdeadbeef;
 }
References ltoa(), Print(), PrintNL(), and RelTmpIndex.
Variable Documentation
ELF_LAZY_RESOLVE_MAIN
void(*)() ELF_LAZY_RESOLVE_MAIN(struct LibAddressCollection *Info, long RelIndex) (struct LibAddressCollection * Info, long RelIndex)
Definition at line 164 of file resolve.c.
 {
     RelTmpIndex = RelIndex;
     if (Info)
     {
         struct LibAddressCollection *tmp = Info;
         PrintNL("________________");
         // The last entry is the null entry (Valid == false) which determines the end of the list.
         while (tmp->Valid)
         {
             Print("-- ");
             Print(tmp->Name);
             PrintNL(" --");
             __UINTPTR_TYPE__ BaseAddress = __UINTPTR_MAX__;
             Elf64_Phdr ItrProgramHeader;
             for (Elf64_Half i = 0; i < ((Elf64_Ehdr *)tmp->ElfFile)->e_phnum; i++)
             {
                 memcpy(&ItrProgramHeader, (__UINT8_TYPE__ *)tmp->ElfFile + ((Elf64_Ehdr *)tmp->ElfFile)->e_phoff + ((Elf64_Ehdr *)tmp->ElfFile)->e_phentsize * i, sizeof(Elf64_Phdr));
                 BaseAddress = MIN(BaseAddress, ItrProgramHeader.p_vaddr);
             }
             char LibAddressBuffer[32];
             ltoa(tmp->MemoryImage, LibAddressBuffer, 16);
             Print("MemoryImage: 0x");
             PrintNL(LibAddressBuffer);
             char BaseAddressBuffer[32];
             ltoa(BaseAddress, BaseAddressBuffer, 16);
             Print("BaseAddress: 0x");
             PrintNL(BaseAddressBuffer);
             struct Elf64_Dyn *_JmpRel = ELFGetDynamicTag(tmp->ElfFile, DT_JMPREL);
             struct Elf64_Dyn *_SymTab = ELFGetDynamicTag(tmp->ElfFile, DT_SYMTAB);
             struct Elf64_Dyn *_StrTab = ELFGetDynamicTag(tmp->ElfFile, DT_STRTAB);
             if (!_JmpRel)
             {
                 PrintNL("No DT_JMPREL");
                 goto RetryNextLib;
             }
             else if (RelIndex >= _JmpRel->d_un.d_val / sizeof(Elf64_Rela))
             {
                 PrintNL("RelIndex is greater than the number of relocations");
                 goto RetryNextLib;
             }
             if (!_SymTab)
             {
                 PrintNL("No DT_SYMTAB");
                 goto RetryNextLib;
             }
             if (!_StrTab)
             {
                 PrintNL("No DT_STRTAB");
                 goto RetryNextLib;
             }
             if (!_JmpRel && !_SymTab && !_StrTab)
                 goto RetryNextLib;
             char JmpRel_d_ptr[32];
             ltoa(_JmpRel->d_un.d_ptr, JmpRel_d_ptr, 16);
             Print("JmpRel_d_ptr: 0x");
             PrintNL(JmpRel_d_ptr);
             char SymTab_d_ptr[32];
             ltoa(_SymTab->d_un.d_ptr, SymTab_d_ptr, 16);
             Print("SymTab_d_ptr: 0x");
             PrintNL(SymTab_d_ptr);
             char StrTab_d_ptr[32];
             ltoa(_StrTab->d_un.d_ptr, StrTab_d_ptr, 16);
             Print("StrTab_d_ptr: 0x");
             PrintNL(StrTab_d_ptr);
             Elf64_Rela *JmpRel = tmp->MemoryImage + (_JmpRel->d_un.d_ptr - BaseAddress);
             Elf64_Sym *SymTab = tmp->MemoryImage + (_SymTab->d_un.d_ptr - BaseAddress);
             char *DynStr = tmp->MemoryImage + (_StrTab->d_un.d_ptr - BaseAddress);
             Elf64_Rela *Rel = JmpRel + RelIndex;
             // Elf64_Rela *Rel = &JmpRel[RelIndex];
             Elf64_Addr *GOTEntry = (Elf64_Addr *)(tmp->MemoryImage + Rel->r_offset);
             int RelType = ELF64_R_TYPE(Rel->r_info);
             char RelBuffer[32];
             ltoa(Rel, RelBuffer, 16);
             Print("Rel: 0x");
             PrintNL(RelBuffer);
             char LibRelInfoBuffer[32];
             ltoa(Rel->r_info, LibRelInfoBuffer, 16);
             Print("  Rel->r_info: 0x");
             PrintNL(LibRelInfoBuffer);
             char LibRelOffsetBuffer[32];
             ltoa(Rel->r_offset, LibRelOffsetBuffer, 16);
             Print("  Rel->r_offset: 0x");
             PrintNL(LibRelOffsetBuffer);
             char LibRelAddEntBuffer[32];
             ltoa(Rel->r_addend, LibRelAddEntBuffer, 16);
             Print("  Rel->r_addend: 0x");
             PrintNL(LibRelAddEntBuffer);
             char RelIndexBuffer[32];
             ltoa(RelIndex, RelIndexBuffer, 16);
             Print("RelIndex: 0x");
             PrintNL(RelIndexBuffer);
             char GotAddressBuffer[32];
             ltoa(GOTEntry, GotAddressBuffer, 16);
             Print("GOTEntry: 0x");
             PrintNL(GotAddressBuffer);
             if (GOTEntry && GOTEntry < 0x10000000)
             {
                 char GotInsideBuffer[32];
                 ltoa(*GOTEntry, GotInsideBuffer, 16);
                 Print("*GOTEntry: 0x");
                 PrintNL(GotInsideBuffer);
             }
             switch (RelType)
             {
             case R_X86_64_NONE:
             {
                 PrintNL("R_X86_64_NONE");
                 if (*GOTEntry == 0)
                 {
                     PrintNL("GOTEntry is 0");
                     break;
                 }
                 Lock = 0;
                 return (void (*)()) * GOTEntry;
             }
             case R_X86_64_JUMP_SLOT:
             {
                 PrintNL("R_X86_64_JUMP_SLOT");
                 int SymIndex = ELF64_R_SYM(Rel->r_info);
                 Elf64_Sym *Sym = SymTab + SymIndex;
                 // Elf64_Sym *Sym = &SymTab[SymIndex];
                 if (Sym->st_name)
                 {
                     char *SymName = DynStr + Sym->st_name;
                     PrintNL(SymName);
                     Elf64_Sym *LibSym = ELFGetSymbol(tmp->ElfFile, SymName);
                     if (LibSym)
                     {
                         *GOTEntry = (Elf64_Addr)(tmp->MemoryImage + LibSym->st_value);
                         Lock = 0;
                         return (void (*)()) * GOTEntry;
                     }
                 }
                 break;
             }
             default:
             {
                 char RelTypeBuffer[32];
                 ltoa(RelType, RelTypeBuffer, 10);
                 Print("RelType not supported ");
                 PrintNL(RelTypeBuffer);
                 break;
             }
             }
         RetryNextLib:
             tmp = tmp->Next;
         }
     }
     Lock = 0;
     __asm__ __volatile__("mfence\n");
     return SymbolNotFound;
 }
Lock
int LockClass::Lock = 0 static
Definition at line 17 of file resolve.c.
Referenced by __attribute__().
RelTmpIndex
long RelTmpIndex = 0xdead
Definition at line 149 of file resolve.c.
Referenced by SymbolNotFound().