Fennix Userspace: Userspace/libc/src/std/uni/sleep.c File Reference
sleep.c File Reference
#include <unistd.h>
#include <stddef.h>
#include <errno.h>
#include "../../../Kernel/syscalls.h"
Functions
PUBLIC unsigned int sleep (unsigned int seconds)
PUBLIC int usleep (useconds_t usec)
Function Documentation
sleep()
PUBLIC unsigned int sleep (unsigned int seconds)
Definition at line 6 of file sleep.c.
 {
     // return syscall1(sys_Sleep, seconds * 1000000);
 }
Referenced by crond_main(), exec_conf(), fsleep(), halt_main(), iostat_main(), main(), make_child(), nc_main(), pause1cannot(), pause2cannot(), pause_after_failed_login(), pause_nomem(), powertop_main(), process_line(), readwrite(), runsvdir_main(), sendmail_main(), slattach_main(), sleep1(), sleep10(), sleep_main(), sleep_much(), startservice(), tail_main(), udhcpc6_main(), and udhcpc_main().
usleep()
PUBLIC int usleep (useconds_t usec)
Definition at line 11 of file sleep.c.
 {
     // return syscall1(sys_Sleep, usec);
 }