Fennix: Userspace/mlibc/tests/posix/pthread_cancel.c File Reference
pthread_cancel.c File Reference
#include <assert.h>
#include <pthread.h>
#include <unistd.h>
Functions
static void * worker1 (void *arg)
static void * worker2 (void *arg)
static void * worker3 (void *arg)
static void * worker4 (void *arg)
static void * worker5 (void *arg)
static void check_result (pthread_t thread)
int main ()
Variables
_Atomic int worker_ready = 0
_Atomic int main_ready = 0
Function Documentation
check_result()
static void check_result (pthread_t thread) static
Definition at line 79 of file pthread_cancel.c.
{
     void *ret_val = NULL;
     int ret = pthread_join(thread, &ret_val);
     assert(!ret);
     assert(ret_val == PTHREAD_CANCELED);
 }
References assert, NULL, PTHREAD_CANCELED, pthread_join(), and ret.
Referenced by main().
main()
int main (void)
Definition at line 87 of file pthread_cancel.c.
            {
     pthread_t thread;
     int ret = pthread_create(&thread, NULL, &worker1, NULL);
     assert(!ret);
     while (!worker_ready);
     ret = pthread_cancel(thread);
     assert(!ret);
     check_result(thread);
     main_ready = 0;
     worker_ready = 0;
     main_ready = 0;
     ret = pthread_create(&thread, NULL, &worker2, NULL);
     assert(!ret);
     while(!worker_ready);
     ret = pthread_cancel(thread);
     assert(!ret);
     main_ready = 1;
     check_result(thread);
     main_ready = 0;
     worker_ready = 0;
     main_ready = 0;
     ret = pthread_create(&thread, NULL, &worker3, NULL);
     assert(!ret);
     while(!worker_ready);
     ret = pthread_cancel(thread);
     assert(!ret);
     main_ready = 1;
     check_result(thread);
     worker_ready = 0;
     main_ready = 0;
     ret = pthread_create(&thread, NULL, &worker4, NULL);
     assert(!ret);
     while(!worker_ready);
     ret = pthread_cancel(thread);
     assert(!ret);
     main_ready = 1;
     check_result(thread);
     // Test for bug where pthread_testcancel() was not checking if
     // cancellation was triggered properly.
     worker_ready = 0;
     int pthread_arg = 0;
     main_ready = 0;
     ret = pthread_create(&thread, NULL, &worker5, &pthread_arg);
     assert(!ret);
     while(!worker_ready);
     main_ready = 1;
     void *ret_val = NULL;
     ret = pthread_join(thread, &ret_val);
     assert(!ret);
     assert(!ret_val);
     assert(pthread_arg == 1);
     return 0;
 }
References assert, check_result(), main_ready, NULL, pthread_cancel(), pthread_create(), pthread_join(), ret, worker1(), worker2(), worker3(), worker4(), worker5(), and worker_ready.
worker1()
static void* worker1 (void * arg) static
Definition at line 8 of file pthread_cancel.c.
{
     (void)arg;
     assert(!pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL));
     assert(!pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL));
     worker_ready = 1;
     while (1) sleep(1);
     return NULL;
 }
References mlibc::arg, assert, NULL, PTHREAD_CANCEL_ASYNCHRONOUS, PTHREAD_CANCEL_ENABLE, pthread_setcancelstate(), pthread_setcanceltype(), sleep(), Driver::void(), and worker_ready.
Referenced by main().
worker2()
static void* worker2 (void * arg) static
Definition at line 20 of file pthread_cancel.c.
{
     (void) arg;
     assert(!pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL));
     worker_ready = 1;
     while(!main_ready);
     // Cancellation point - we should cancel right now
     sleep(1);
     assert(!"Expected to be cancelled!");
     __builtin_unreachable();
 }
References mlibc::arg, assert, main_ready, NULL, PTHREAD_CANCEL_ENABLE, pthread_setcancelstate(), sleep(), Driver::void(), and worker_ready.
Referenced by main().
worker3()
static void* worker3 (void * arg) static
Definition at line 35 of file pthread_cancel.c.
{
     (void) arg;
     assert(!pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL));
     worker_ready = 1;
     while(!main_ready);
     // Cancellation point - we should cancel right now
     pthread_testcancel();
     assert(!"Expected to be cancelled!");
     __builtin_unreachable();
 }
References mlibc::arg, assert, main_ready, NULL, PTHREAD_CANCEL_ENABLE, pthread_setcancelstate(), pthread_testcancel(), Driver::void(), and worker_ready.
Referenced by main().
worker4()
static void* worker4 (void * arg) static
Definition at line 50 of file pthread_cancel.c.
{
     (void) arg;
     assert(!pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL));
     worker_ready = 1;
     sleep(1);
     // We expect to be canceled during the sleep
     assert(!"Expected to be cancelled!");
     __builtin_unreachable();
 }
References mlibc::arg, assert, NULL, PTHREAD_CANCEL_ENABLE, pthread_setcancelstate(), sleep(), Driver::void(), and worker_ready.
Referenced by main().
worker5()
static void* worker5 (void * arg) static
Definition at line 63 of file pthread_cancel.c.
{
     assert(!pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL));
     worker_ready = 1;
     while(!main_ready);
     // Cancellation point - we should NOT cancel right now
     pthread_testcancel();
     int *arg_int = (int*)arg;
     *arg_int = 1;
     return NULL;
 }
References mlibc::arg, assert, main_ready, NULL, PTHREAD_CANCEL_ENABLE, pthread_setcancelstate(), pthread_testcancel(), and worker_ready.
Referenced by main().
Variable Documentation
main_ready
_Atomic int main_ready = 0
Definition at line 6 of file pthread_cancel.c.
Referenced by main(), worker2(), worker3(), and worker5().
worker_ready
_Atomic int worker_ready = 0
Definition at line 5 of file pthread_cancel.c.
Referenced by main(), worker1(), worker2(), worker3(), worker4(), and worker5().