Fennix: std::shared_ptr< T >::counter Class Reference
std::shared_ptr< T >::counter Class Reference
Public Member Functions
counter ()
counter (const counter &)=delete
counter & operator= (const counter &)=delete
~counter ()
void reset ()
unsigned int get ()
void operator++ ()
void operator++ (int)
void operator-- ()
void operator-- (int)
Private Attributes
unsigned int RefCount {}
Detailed Description
template<typename T>
class std::shared_ptr< T >::counter
Definition at line 105 of file smart_ptr.hpp.
Constructor & Destructor Documentation
counter() [1/2]
template<typename T > std::shared_ptr< T >::counter::counter () inline
Definition at line 111 of file smart_ptr.hpp.
 : RefCount(0) { spdbg("Counter %#lx created", this); };
References spdbg.
counter() [2/2]
template<typename T > std::shared_ptr< T >::counter::counter (const counter &) delete
~counter()
template<typename T > std::shared_ptr< T >::counter::~counter () inline
Definition at line 114 of file smart_ptr.hpp.
 { spdbg("Counter %#lx deleted", this); }
References spdbg.
Member Function Documentation
get()
template<typename T > unsigned int std::shared_ptr< T >::counter::get () inline
Definition at line 121 of file smart_ptr.hpp.
             {
                 return this->RefCount;
                 spdbg("return");
             }
References std::shared_ptr< T >::counter::RefCount, and spdbg.
Referenced by std::shared_ptr< T >::get_count(), std::shared_ptr< T >::reset(), and std::shared_ptr< T >::~shared_ptr().
operator++() [1/2]
template<typename T > void std::shared_ptr< T >::counter::operator++ () inline
Definition at line 127 of file smart_ptr.hpp.
             {
                 this->RefCount++;
                 spdbg("increment");
             }
References std::shared_ptr< T >::counter::RefCount, and spdbg.
operator++() [2/2]
template<typename T > void std::shared_ptr< T >::counter::operator++ (int) inline
Definition at line 133 of file smart_ptr.hpp.
             {
                 this->RefCount++;
                 spdbg("increment");
             }
References std::shared_ptr< T >::counter::RefCount, and spdbg.
operator--() [1/2]
template<typename T > void std::shared_ptr< T >::counter::operator-- () inline
Definition at line 139 of file smart_ptr.hpp.
             {
                 this->RefCount--;
                 spdbg("decrement");
             }
References std::shared_ptr< T >::counter::RefCount, and spdbg.
operator--() [2/2]
template<typename T > void std::shared_ptr< T >::counter::operator-- (int) inline
Definition at line 145 of file smart_ptr.hpp.
             {
                 this->RefCount--;
                 spdbg("decrement");
             }
References std::shared_ptr< T >::counter::RefCount, and spdbg.
operator=()
template<typename T > counter& std::shared_ptr< T >::counter::operator= (const counter &) delete
reset()
template<typename T > void std::shared_ptr< T >::counter::reset () inline
Definition at line 115 of file smart_ptr.hpp.
             {
                 this->RefCount = 0;
                 spdbg("reset");
             }
References std::shared_ptr< T >::counter::RefCount, and spdbg.
Field Documentation
RefCount
template<typename T > unsigned int std::shared_ptr< T >::counter::RefCount {} private
Definition at line 108 of file smart_ptr.hpp.
Referenced by std::shared_ptr< T >::counter::get(), std::shared_ptr< T >::counter::operator++(), std::shared_ptr< T >::counter::operator--(), and std::shared_ptr< T >::counter::reset().
The documentation for this class was generated from the following file:
Kernel/include_std/std/smart_ptr.hpp