Fennix Userspace: mlibc::anonymous_namespace{file-io.cpp} Namespace Reference
mlibc::anonymous_namespace{file-io.cpp} Namespace Reference
Typedefs
using file_list = frg::intrusive_list< abstract_file, frg::locate_member< abstract_file, frg::default_list_hook< abstract_file >, &abstract_file::_list_hook > >
Functions
file_list & global_file_list ()
Variables
constexpr bool globallyDisableBuffering = false
constexpr size_t ungetBufferSize = 8
Typedef Documentation
file_list
using mlibc::anonymous_namespace{file-io.cpp}::file_list = typedef frg::intrusive_list< abstract_file, frg::locate_member< abstract_file, frg::default_list_hook<abstract_file>, &abstract_file::_list_hook > >
Definition at line 30 of file file-io.cpp.
Function Documentation
global_file_list()
file_list& mlibc::anonymous_namespace{file-io.cpp}::global_file_list ()
Definition at line 46 of file file-io.cpp.
{
         static frg::eternal<file_list> list;
         return list.get();
     };
Referenced by mlibc::abstract_file::abstract_file(), fflush(), fflush_unlocked(), mlibc::abstract_file::~abstract_file(), and anonymous_namespace{file-io.cpp}::stdio_guard::~stdio_guard().
Variable Documentation
globallyDisableBuffering
constexpr bool mlibc::anonymous_namespace{file-io.cpp}::globallyDisableBuffering = false constexpr
Definition at line 40 of file file-io.cpp.
Referenced by mlibc::abstract_file::read(), and mlibc::abstract_file::write().
ungetBufferSize
constexpr size_t mlibc::anonymous_namespace{file-io.cpp}::ungetBufferSize = 8 constexpr
Definition at line 43 of file file-io.cpp.
Referenced by mlibc::abstract_file::_ensure_allocation(), mlibc::abstract_file::unget(), and mlibc::abstract_file::~abstract_file().