Fennix: Userspace/musl/src/process/waitpid.c File Reference
waitpid.c File Reference
#include <sys/wait.h>
#include "syscall.h"
Functions
pid_t waitpid (pid_t pid, int *status, int options)
Function Documentation
waitpid()
pid_t waitpid (pid_t pid, int * status, int options)
Definition at line 4 of file waitpid.c.
 {
     return syscall_cp(SYS_wait4, pid, status, options, 0);
 }
References options, mlibc::status, and syscall_cp.
Referenced by forkpty(), main(), posix_spawn(), reap(), run_cmd(), system(), and we_askshell().