Fennix: Userspace/apps/base/busybox/libbb/selinux_common.c File Reference
selinux_common.c File Reference
#include "libbb.h"
#include <selinux/context.h>
Functions
context_t FAST_FUNC set_security_context_component (security_context_t cur_context, char *user, char *role, char *type, char *range)
void FAST_FUNC setfscreatecon_or_die (security_context_t scontext)
void FAST_FUNC selinux_preserve_fcontext (int fdesc)
Function Documentation
selinux_preserve_fcontext()
void FAST_FUNC selinux_preserve_fcontext (int fdesc)
Definition at line 44 of file selinux_common.c.
 {
     security_context_t context;
     if (fgetfilecon(fdesc, &context) < 0) {
         if (errno == ENODATA || errno == ENOTSUP)
             return;
         bb_simple_perror_msg_and_die("fgetfilecon failed");
     }
     setfscreatecon_or_die(context);
     freecon(context);
 }
References bb_simple_perror_msg_and_die(), context, ENODATA, ENOTSUP, errno, and setfscreatecon_or_die().
Referenced by update_passwd().
set_security_context_component()
context_t FAST_FUNC set_security_context_component (security_context_t cur_context, char * user, char * role, char * type, char * range)
Definition at line 12 of file selinux_common.c.
 {
     context_t con = context_new(cur_context);
     if (!con)
         return NULL;
     if (user && context_user_set(con, user))
         goto error;
     if (type && context_type_set(con, type))
         goto error;
     if (range && context_range_set(con, range))
         goto error;
     if (role && context_role_set(con, role))
         goto error;
     return con;
 error:
     context_free(con);
     return NULL;
 }
References error, NULL, range, role, and type.
Referenced by change_filedir_context().
setfscreatecon_or_die()
void FAST_FUNC setfscreatecon_or_die (security_context_t scontext)
Definition at line 34 of file selinux_common.c.
 {
     if (setfscreatecon(scontext) < 0) {
         /* Can be NULL. All known printf implementations
          * display "(null)", "<null>" etc */
         bb_perror_msg_and_die("can't set default "
                 "file creation context to %s", scontext);
     }
 }
References bb_perror_msg_and_die().
Referenced by copy_file(), getopt_mk_fifo_nod(), install_main(), mkdir_main(), and selinux_preserve_fcontext().