Fennix Userspace: Userspace/musl/src/linux/x32/sysinfo.c File Reference
sysinfo.c File Reference
#include <sys/sysinfo.h>
#include "syscall.h"
Data Structures
struct kernel_sysinfo
Macros
#define klong long long
#define kulong unsigned long long
Functions
int __lsysinfo (struct sysinfo *info)
weak_alias (__lsysinfo, sysinfo)
Data Structure Documentation
kernel_sysinfo
struct kernel_sysinfo
Definition at line 7 of file sysinfo.c.
Data Fields
kulong bufferram
kulong freehigh
kulong freeram
kulong freeswap
kulong loads[3]
unsigned mem_unit
short pad
short procs
kulong sharedram
kulong totalhigh
kulong totalram
kulong totalswap
klong uptime
Macro Definition Documentation
klong
#define klong long long
Definition at line 4 of file sysinfo.c.
kulong
#define kulong unsigned long long
Definition at line 5 of file sysinfo.c.
Function Documentation
__lsysinfo()
int __lsysinfo (struct sysinfo * info)
Definition at line 23 of file sysinfo.c.
 {
     struct kernel_sysinfo tmp;
     int ret = syscall(SYS_sysinfo, &tmp);
     if(ret == -1) return ret;
     info->uptime = tmp.uptime;
     info->loads[0] = tmp.loads[0];
     info->loads[1] = tmp.loads[1];
     info->loads[2] = tmp.loads[2];
     kulong shifts;
     kulong max = tmp.totalram | tmp.totalswap;
     __asm__("bsr %1,%0" : "=r"(shifts) : "r"(max));
     shifts = shifts >= 32 ? shifts - 31 : 0;
     info->totalram = tmp.totalram >> shifts;
     info->freeram = tmp.freeram >> shifts;
     info->sharedram = tmp.sharedram >> shifts;
     info->bufferram = tmp.bufferram >> shifts;
     info->totalswap = tmp.totalswap >> shifts;
     info->freeswap = tmp.freeswap >> shifts;
     info->procs = tmp.procs ;
     info->totalhigh = tmp.totalhigh >> shifts;
     info->freehigh = tmp.freehigh >> shifts;
     info->mem_unit = (tmp.mem_unit ? tmp.mem_unit : 1) << shifts;
     return ret;
 }
References __asm__(), sysinfo::bufferram, kernel_sysinfo::bufferram, sysinfo::freehigh, kernel_sysinfo::freehigh, sysinfo::freeram, kernel_sysinfo::freeram, sysinfo::freeswap, kernel_sysinfo::freeswap, kulong, sysinfo::loads, kernel_sysinfo::loads, sysinfo::mem_unit, kernel_sysinfo::mem_unit, sysinfo::procs, kernel_sysinfo::procs, sysinfo::sharedram, kernel_sysinfo::sharedram, syscall(), sysinfo::totalhigh, kernel_sysinfo::totalhigh, sysinfo::totalram, kernel_sysinfo::totalram, sysinfo::totalswap, kernel_sysinfo::totalswap, sysinfo::uptime, and kernel_sysinfo::uptime.
Referenced by sysconf().
weak_alias()
weak_alias (__lsysinfo , sysinfo)