Fennix Userspace: Userspace/musl/src/network/netlink.c File Reference
netlink.c File Reference
#include <errno.h>
#include <string.h>
#include <syscall.h>
#include <sys/socket.h>
#include "netlink.h"
Functions
static int __netlink_enumerate (int fd, unsigned int seq, int type, int af, int(*cb)(void *ctx, struct nlmsghdr *h), void *ctx)
int __rtnetlink_enumerate (int link_af, int addr_af, int(*cb)(void *ctx, struct nlmsghdr *h), void *ctx)
Function Documentation
__netlink_enumerate()
static int __netlink_enumerate (int fd, unsigned int seq, int type, int af, int(*)(void *ctx, struct nlmsghdr *h) cb, void * ctx) static
Definition at line 7 of file netlink.c.
 {
     struct nlmsghdr *h;
     union {
         uint8_t buf[8192];
         struct {
             struct nlmsghdr nlh;
             struct rtgenmsg g;
         } req;
         struct nlmsghdr reply;
     } u;
     int r, ret;
     memset(&u.req, 0, sizeof(u.req));
     u.req.nlh.nlmsg_len = sizeof(u.req);
     u.req.nlh.nlmsg_type = type;
     u.req.nlh.nlmsg_flags = NLM_F_DUMP | NLM_F_REQUEST;
     u.req.nlh.nlmsg_seq = seq;
     u.req.g.rtgen_family = af;
     r = send(fd, &u.req, sizeof(u.req), 0);
     if (r < 0) return r;
     while (1) {
         r = recv(fd, u.buf, sizeof(u.buf), MSG_DONTWAIT);
         if (r <= 0) return -1;
         for (h = &u.reply; NLMSG_OK(h, (void*)&u.buf[r]); h = NLMSG_NEXT(h)) {
             if (h->nlmsg_type == NLMSG_DONE) return 0;
             if (h->nlmsg_type == NLMSG_ERROR) return -1;
             ret = cb(ctx, h);
             if (ret) return ret;
         }
     }
 }
References buf, g, memset(), MSG_DONTWAIT, NLM_F_DUMP, NLM_F_REQUEST, NLMSG_DONE, NLMSG_ERROR, NLMSG_NEXT, NLMSG_OK, nlmsghdr::nlmsg_type, r, recv(), ret, and send().
Referenced by __rtnetlink_enumerate().
__rtnetlink_enumerate()
int __rtnetlink_enumerate (int link_af, int addr_af, int(*)(void *ctx, struct nlmsghdr *h) cb, void * ctx)
Definition at line 42 of file netlink.c.
 {
     int fd, r;
     fd = socket(PF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE);
     if (fd < 0) return -1;
     r = __netlink_enumerate(fd, 1, RTM_GETLINK, link_af, cb, ctx);
     if (!r) r = __netlink_enumerate(fd, 2, RTM_GETADDR, addr_af, cb, ctx);
     __syscall(SYS_close,fd);
     return r;
 }
References __netlink_enumerate(), __syscall, NETLINK_ROUTE, PF_NETLINK, r, RTM_GETADDR, RTM_GETLINK, SOCK_CLOEXEC, SOCK_RAW, and socket().
Referenced by getifaddrs(), and if_nameindex().