Fennix: Userspace/apps/base/bash/lib/sh/winsize.c File Reference
winsize.c File Reference
#include "config.h"
#include <stdc.h>
#include "bashtypes.h"
#include <sys/ioctl.h>
#include <stdio.h>
Macros
#define input_tty() (shell_tty != -1) ? shell_tty : fileno (stderr)
Functions
void sh_set_lines_and_columns PARAMS ((int, int))
void get_new_window_size (int from_sig, int *rp, int *cp)
Variables
int errno
int shell_tty
Macro Definition Documentation
input_tty
#define input_tty () (shell_tty != -1) ? shell_tty : fileno (stderr)
Definition at line 62 of file winsize.c.
Function Documentation
get_new_window_size()
void get_new_window_size (int from_sig, int * rp, int * cp)
Definition at line 81 of file winsize.c.
 {
 #if defined (TIOCGWINSZ)
   struct winsize win;
   int tty;
   tty = input_tty ();
   if (tty >= 0 && (ioctl (tty, TIOCGWINSZ, &win) == 0) &&
       win.ws_row > 0 && win.ws_col > 0)
     {
       sh_set_lines_and_columns (win.ws_row, win.ws_col);
 #if defined (READLINE)
       if ((interactive_shell && no_line_editing == 0) || bash_readline_initialized)
     rl_set_screen_size (win.ws_row, win.ws_col);
 #endif
       if (rp)
     *rp = win.ws_row;
       if (cp)
     *cp = win.ws_col;
     }
 #endif
 }
References bash_readline_initialized, input_tty, interactive_shell, ioctl(), no_line_editing, rl_set_screen_size(), sh_set_lines_and_columns(), TIOCGWINSZ, winsize::ws_col, and winsize::ws_row.
Referenced by default_columns(), get_tty_state(), shell_getc(), and wait_for().
PARAMS()
void sh_set_lines_and_columns PARAMS ((int, int))
Variable Documentation
errno
int errno extern
shell_tty
int shell_tty extern
Definition at line 191 of file jobs.c.
Referenced by give_terminal_to(), initialize_job_control(), maybe_give_terminal_to(), restart_job_control(), and set_job_control().