Fennix: Userspace/apps/base/bash/lib/sh/uconvert.c File Reference
uconvert.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixtime.h"
#include <stdio.h>
#include "chartypes.h"
#include "shell.h"
#include "builtins.h"
Macros
#define DECIMAL '.' /* XXX - should use locale */
#define RETURN(x)
Functions
int uconvert (char *s, long *ip, long *up, char **ep)
Variables
static int multiplier [7] = { 1, 100000, 10000, 1000, 100, 10, 1 }
Macro Definition Documentation
DECIMAL
#define DECIMAL '.' /* XXX - should use locale */
Definition at line 38 of file uconvert.c.
RETURN
#define RETURN (x)
Value:
do { \
  if (ip) *ip = ipart * mult; \
  if (up) *up = upart; \
  if (ep) *ep = p; \
  return (x); \
} while (0)
Definition at line 40 of file uconvert.c.
Function Documentation
uconvert()
int uconvert (char * s, long * ip, long * up, char ** ep)
Definition at line 60 of file uconvert.c.
 {
   int n, mult;
   long ipart, upart;
   char *p;
   ipart = upart = 0;
   mult = 1;
   if (s && (*s == '-' || *s == '+'))
     {
       mult = (*s == '-') ? -1 : 1;
       p = s + 1;
     }
   else
     p = s;
   for ( ; p && *p; p++)
     {
       if (*p == DECIMAL)        /* decimal point */
     break;
       if (DIGIT(*p) == 0)
     RETURN(0);
       ipart = (ipart * 10) + (*p - '0');
     }
   if (p == 0 || *p == 0)    /* callers ensure p can never be 0; this is to shut up clang */
     RETURN(1);
   if (*p == DECIMAL)
     p++;
   /* Look for up to six digits past a decimal point. */
   for (n = 0; n < 6 && p[n]; n++)
     {
       if (DIGIT(p[n]) == 0)
     {
       if (ep)
         {
           upart *= multiplier[n];
           p += n;       /* To set EP */
         }
       RETURN(0);
     }
       upart = (upart * 10) + (p[n] - '0');
     }
   /* Now convert to millionths */
   upart *= multiplier[n];
   if (n == 6 && p[6] >= '5' && p[6] <= '9')
     upart++;            /* round up 1 */
   if (ep)
     {
       p += n;
       while (DIGIT(*p))
     p++;
     }
   RETURN(1);
 }
References DECIMAL, DIGIT, mult, multiplier, n, p, RETURN, and s.
Referenced by accept_builtin(), parse_gnutimefmt(), and sleep_builtin().
Variable Documentation
multiplier
int multiplier[7] = { 1, 100000, 10000, 1000, 100, 10, 1 } static
Definition at line 51 of file uconvert.c.
Referenced by readprofile_main(), and uconvert().