Fennix Kernel: Memory::StackGuard Class Reference
Memory::StackGuard Class Reference
#include <stack.hpp>
Data Structures
struct AllocatedPages
Public Member Functions
std::vector< AllocatedPages > GetAllocatedPages ()
void Fork (StackGuard *Parent)
uint64_t GetSize ()
bool GetUserMode ()
bool IsExpanded ()
void * GetStackBottom ()
void * GetStackTop ()
void * GetStackPhysicalBottom ()
void * GetStackPhysicalTop ()
bool Expand (uintptr_t FaultAddress)
StackGuard (bool User, VirtualMemoryArea *vma)
~StackGuard ()
Private Attributes
void * StackBottom = nullptr
void * StackTop = nullptr
void * StackPhysicalBottom = nullptr
void * StackPhysicalTop = nullptr
uint64_t Size = 0
bool UserMode = false
bool Expanded = false
VirtualMemoryArea * vma = nullptr
std::vector< AllocatedPages > AllocatedPagesList
Detailed Description
Definition at line 28 of file stack.hpp.
Data Structure Documentation
Memory::StackGuard::AllocatedPages
struct Memory::StackGuard::AllocatedPages
Definition at line 31 of file stack.hpp.
Data Fields
void * PhysicalAddress
void * VirtualAddress
Constructor & Destructor Documentation
StackGuard()
Memory::StackGuard::StackGuard (bool User, VirtualMemoryArea * vma)
Construct a new Stack Guard object
Parameters
User Stack for user mode?
Definition at line 105 of file stack_guard.cpp.
     {
         this->UserMode = User;
         this->vma = vma;
         if (this->UserMode)
         {
             void *AllocatedStack = vma->RequestPages(TO_PAGES(USER_STACK_SIZE) + 1);
             memset(AllocatedStack, 0, USER_STACK_SIZE);
             debug("AllocatedStack: %#lx", AllocatedStack);
             {
                 Virtual vmm = Virtual(vma->GetTable());
                 for (size_t i = 0; i < TO_PAGES(USER_STACK_SIZE); i++)
                 {
                     void *VirtualPage = (void *)(USER_STACK_BASE + (i * PAGE_SIZE));
                     void *PhysicalPage = (void *)((uintptr_t)AllocatedStack + (i * PAGE_SIZE));
                     vmm.Map(VirtualPage, PhysicalPage, PTFlag::RW | PTFlag::US);
                     AllocatedPages ap = {
                         .PhysicalAddress = PhysicalPage,
                         .VirtualAddress = VirtualPage,
                     };
                     AllocatedPagesList.push_back(ap);
                     debug("Mapped %#lx to %#lx", PhysicalPage, VirtualPage);
                 }
             }
             this->StackBottom = (void *)USER_STACK_BASE;
             this->StackTop = (void *)(USER_STACK_BASE + USER_STACK_SIZE);
             this->StackPhysicalBottom = AllocatedStack;
             this->StackPhysicalTop = (void *)((uintptr_t)AllocatedStack + USER_STACK_SIZE);
             this->Size = USER_STACK_SIZE;
         }
         else
         {
             this->StackBottom = vma->RequestPages(TO_PAGES(STACK_SIZE) + 1);
             memset(this->StackBottom, 0, STACK_SIZE);
             debug("StackBottom: %#lx", this->StackBottom);
             this->StackTop = (void *)((uintptr_t)this->StackBottom + STACK_SIZE);
             this->StackPhysicalBottom = this->StackBottom;
             this->StackPhysicalTop = this->StackTop;
             this->Size = STACK_SIZE;
             for (size_t i = 0; i < TO_PAGES(STACK_SIZE); i++)
             {
                 AllocatedPages pa = {
                     .PhysicalAddress = (void *)((uintptr_t)this->StackBottom + (i * PAGE_SIZE)),
                     .VirtualAddress = (void *)((uintptr_t)this->StackBottom + (i * PAGE_SIZE)),
                 };
                 AllocatedPagesList.push_back(pa);
             }
         }
         debug("Allocated stack at %#lx", this->StackBottom);
         debug("Stack Range: %#lx - %#lx", this->StackBottom, this->StackTop);
     }
References AllocatedPagesList, debug, Memory::VirtualMemoryArea::GetTable(), Memory::Virtual::Map(), memset(), PAGE_SIZE, Memory::StackGuard::AllocatedPages::PhysicalAddress, Memory::VirtualMemoryArea::RequestPages(), Memory::RW, Size, STACK_SIZE, StackBottom, StackPhysicalBottom, StackPhysicalTop, StackTop, TO_PAGES, Memory::US, Tasking::User, USER_STACK_SIZE, UserMode, and vma.
~StackGuard()
Memory::StackGuard::~StackGuard ()
Destroy the Stack Guard object
Definition at line 168 of file stack_guard.cpp.
     {
         /* VMA will free the stack */
     }
Member Function Documentation
Expand()
bool Memory::StackGuard::Expand (uintptr_t FaultAddress)
Called by exception handler
Definition at line 24 of file stack_guard.cpp.
     {
         if (this->UserMode)
         {
             if (FaultAddress < (uintptr_t)this->StackBottom - 0x100 ||
                 FaultAddress > (uintptr_t)this->StackTop)
             {
                 info("Fault address %#lx is not in range of stack %#lx - %#lx", FaultAddress,
                      (uintptr_t)this->StackBottom - 0x100, (uintptr_t)this->StackTop);
                 return false; /* It's not about the stack. */
             }
             else
             {
                 void *AllocatedStack = this->vma->RequestPages(TO_PAGES(USER_STACK_SIZE) + 1);
                 debug("AllocatedStack: %#lx", AllocatedStack);
                 memset(AllocatedStack, 0, USER_STACK_SIZE);
                 Virtual vmm = Virtual(this->vma->GetTable());
                 for (size_t i = 0; i < TO_PAGES(USER_STACK_SIZE); i++)
                 {
                     void *VirtualPage = (void *)((uintptr_t)this->StackBottom - (i * PAGE_SIZE));
                     void *PhysicalPage = (void *)((uintptr_t)AllocatedStack + (i * PAGE_SIZE));
                     vmm.Map(VirtualPage, PhysicalPage, PTFlag::RW | PTFlag::US);
                     AllocatedPages ap = {
                         .PhysicalAddress = PhysicalPage,
                         .VirtualAddress = VirtualPage,
                     };
                     AllocatedPagesList.push_back(ap);
                     debug("Mapped %#lx to %#lx", PhysicalPage, VirtualPage);
                 }
                 this->StackBottom = (void *)((uintptr_t)this->StackBottom - USER_STACK_SIZE);
                 this->Size += USER_STACK_SIZE;
                 debug("Stack expanded to %#lx", this->StackBottom);
                 this->Expanded = true;
                 return true;
             }
         }
         else
         {
             fixme("Not implemented and probably not needed");
             return false;
         }
     }
References AllocatedPagesList, debug, Expanded, fixme, Memory::VirtualMemoryArea::GetTable(), info, Memory::Virtual::Map(), memset(), PAGE_SIZE, Memory::StackGuard::AllocatedPages::PhysicalAddress, Memory::VirtualMemoryArea::RequestPages(), Memory::RW, Size, StackBottom, StackTop, TO_PAGES, Memory::US, USER_STACK_SIZE, UserMode, and vma.
Referenced by UserModeExceptionHandler().
Fork()
void Memory::StackGuard::Fork (StackGuard * Parent)
Fork stack guard
Definition at line 70 of file stack_guard.cpp.
     {
         this->UserMode = Parent->GetUserMode();
         this->StackBottom = Parent->GetStackBottom();
         this->StackTop = Parent->GetStackTop();
         this->StackPhysicalBottom = Parent->GetStackPhysicalBottom();
         this->StackPhysicalTop = Parent->GetStackPhysicalTop();
         this->Size = Parent->GetSize();
         this->Expanded = Parent->IsExpanded();
         if (this->UserMode)
         {
             std::vector<AllocatedPages> ParentAllocatedPages = Parent->GetAllocatedPages();
             Virtual vma(this->vma->GetTable());
             foreach (auto Page in ParentAllocatedPages)
             {
                 void *NewPhysical = this->vma->RequestPages(1);
                 debug("Forking address %#lx to %#lx", Page.PhysicalAddress, NewPhysical);
                 memcpy(NewPhysical, Page.PhysicalAddress, PAGE_SIZE);
                 vma.Map(Page.VirtualAddress, NewPhysical, PTFlag::RW | PTFlag::US);
                 AllocatedPages ap = {
                     .PhysicalAddress = NewPhysical,
                     .VirtualAddress = Page.VirtualAddress,
                 };
                 AllocatedPagesList.push_back(ap);
                 debug("Mapped %#lx to %#lx", NewPhysical, Page.VirtualAddress);
             }
         }
         else
         {
             fixme("Kernel mode stack fork not implemented");
         }
     }
References AllocatedPagesList, debug, Expanded, fixme, GetAllocatedPages(), GetSize(), GetStackBottom(), GetStackPhysicalBottom(), GetStackPhysicalTop(), GetStackTop(), Memory::VirtualMemoryArea::GetTable(), GetUserMode(), IsExpanded(), memcpy(), PAGE_SIZE, Memory::StackGuard::AllocatedPages::PhysicalAddress, Memory::VirtualMemoryArea::RequestPages(), Memory::RW, Size, StackBottom, StackPhysicalBottom, StackPhysicalTop, StackTop, Memory::US, UserMode, and vma.
Referenced by linux_fork(), and sys_fork().
GetAllocatedPages()
std::vector<AllocatedPages> Memory::StackGuard::GetAllocatedPages () inline
Definition at line 48 of file stack.hpp.
         {
             return AllocatedPagesList;
         }
References AllocatedPagesList.
Referenced by Fork().
GetSize()
uint64_t Memory::StackGuard::GetSize () inline
For general info
Definition at line 57 of file stack.hpp.
 { return Size; }
References Size.
Referenced by Fork(), and Tasking::TCB::GetSize().
GetStackBottom()
void* Memory::StackGuard::GetStackBottom () inline
For general info
Definition at line 66 of file stack.hpp.
 { return StackBottom; }
References StackBottom.
Referenced by Fork(), and Tasking::TCB::TCB().
GetStackPhysicalBottom()
void* Memory::StackGuard::GetStackPhysicalBottom () inline
For general info (avoid if possible)
Note
This can be used only if the stack was NOT expanded.
Definition at line 77 of file stack.hpp.
         {
             if (Expanded)
                 return nullptr;
             return StackPhysicalBottom;
         }
References Expanded, and StackPhysicalBottom.
Referenced by Fork().
GetStackPhysicalTop()
void* Memory::StackGuard::GetStackPhysicalTop () inline
For general info (avoid if possible)
Note
This can be used only if the stack was NOT expanded.
Definition at line 90 of file stack.hpp.
         {
             if (Expanded)
                 return nullptr;
             return StackPhysicalTop;
         }
References Expanded, and StackPhysicalTop.
Referenced by Fork().
GetStackTop()
void* Memory::StackGuard::GetStackTop () inline
For RSP
Definition at line 69 of file stack.hpp.
 { return StackTop; }
References StackTop.
Referenced by Fork(), and Tasking::TCB::TCB().
GetUserMode()
bool Memory::StackGuard::GetUserMode () inline
For general info
Definition at line 60 of file stack.hpp.
 { return UserMode; }
References UserMode.
Referenced by Fork().
IsExpanded()
bool Memory::StackGuard::IsExpanded () inline
For general info
Definition at line 63 of file stack.hpp.
 { return Expanded; }
References Expanded.
Referenced by Fork().
Field Documentation
AllocatedPagesList
std::vector<AllocatedPages> Memory::StackGuard::AllocatedPagesList private
Definition at line 45 of file stack.hpp.
Referenced by Expand(), Fork(), GetAllocatedPages(), and StackGuard().
Expanded
bool Memory::StackGuard::Expanded = false private
Definition at line 43 of file stack.hpp.
Referenced by Expand(), Fork(), GetStackPhysicalBottom(), GetStackPhysicalTop(), and IsExpanded().
Size
uint64_t Memory::StackGuard::Size = 0 private
Definition at line 41 of file stack.hpp.
Referenced by Expand(), Fork(), GetSize(), and StackGuard().
StackBottom
void* Memory::StackGuard::StackBottom = nullptr private
Definition at line 37 of file stack.hpp.
Referenced by Expand(), Fork(), GetStackBottom(), and StackGuard().
StackPhysicalBottom
void* Memory::StackGuard::StackPhysicalBottom = nullptr private
Definition at line 39 of file stack.hpp.
Referenced by Fork(), GetStackPhysicalBottom(), and StackGuard().
StackPhysicalTop
void* Memory::StackGuard::StackPhysicalTop = nullptr private
Definition at line 40 of file stack.hpp.
Referenced by Fork(), GetStackPhysicalTop(), and StackGuard().
StackTop
void* Memory::StackGuard::StackTop = nullptr private
Definition at line 38 of file stack.hpp.
Referenced by Expand(), Fork(), GetStackTop(), and StackGuard().
UserMode
bool Memory::StackGuard::UserMode = false private
Definition at line 42 of file stack.hpp.
Referenced by Expand(), Fork(), GetUserMode(), and StackGuard().
vma
VirtualMemoryArea* Memory::StackGuard::vma = nullptr private
Definition at line 44 of file stack.hpp.
Referenced by Expand(), Fork(), and StackGuard().
The documentation for this class was generated from the following files:
Kernel/include/memory/stack.hpp
Kernel/core/memory/stack_guard.cpp