Fennix Userspace: Userspace/mlibc/options/posix/include/grp.h File Reference
grp.h File Reference
#include <stddef.h>
#include <stdio.h>
#include <abi-bits/gid_t.h>
Data Structures
struct group
Functions
void endgrent (void)
struct group * getgrent (void)
struct group * getgrgid (gid_t)
int getgrgid_r (gid_t, struct group *, char *, size_t, struct group **)
struct group * getgrnam (const char *)
int getgrnam_r (const char *, struct group *, char *, size_t, struct group **)
void setgrent (void)
int putgrent (const struct group *, FILE *)
struct group * fgetgrent (FILE *)
int setgroups (size_t size, const gid_t *list)
int initgroups (const char *user, gid_t group)
int getgrouplist (const char *, gid_t, gid_t *, int *)
Data Structure Documentation
group
struct group
Definition at line 12 of file grp.h.
Data Fields
unsigned char active_idx:5
gid_t gr_gid
char ** gr_mem
char * gr_name
char * gr_passwd
struct meta * meta
char pad[UNIT - sizeof(struct meta *) - 1]
unsigned char storage[]
Function Documentation
endgrent()
void endgrent (void)
Definition at line 185 of file grp-stubs.cpp.
                     {
     close_global_file();
 }
References anonymous_namespace{grp-stubs.cpp}::close_global_file().
Referenced by main().
fgetgrent()
struct group* fgetgrent (FILE * f)
Definition at line 308 of file grp-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __getgrent_a(), f, gr, line, mem, and size.
getgrent()
struct group* getgrent (void)
Definition at line 189 of file grp-stubs.cpp.
{
     static group entry;
     char line[512];
     if(!open_global_file()) {
         return nullptr;
     }
     if(fgets(line, 512, global_file)) {
         clear_entry(&entry);
         if(!extract_entry(line, &entry)) {
             errno = EINVAL;
             return nullptr;
         }
         return &entry;
     }
     if(ferror(global_file)) {
         errno = EIO;
     }
     return nullptr;
 }
References __getgrent_a(), anonymous_namespace{grp-stubs.cpp}::clear_entry(), EINVAL, EIO, errno, anonymous_namespace{grp-stubs.cpp}::extract_entry(), f, ferror, fgets(), fopen(), anonymous_namespace{grp-stubs.cpp}::global_file, gr, line, mem, anonymous_namespace{grp-stubs.cpp}::open_global_file(), and size.
Referenced by main().
getgrgid()
struct group* getgrgid (gid_t gid)
Definition at line 213 of file grp-stubs.cpp.
{
     static group entry;
     int err = walk_file(&entry, [&] (group *entry) {
         return entry->gr_gid == gid;
     });
     if (err) {
         errno = err;
         return nullptr;
     }
     return &entry;
 }
getgrgid_r()
int getgrgid_r (gid_t gid, struct group * grp, char * buffer, size_t size, struct group ** result)
Definition at line 228 of file grp-stubs.cpp.
{
     *result = nullptr;
     int err = walk_file(grp, [&] (group *entry) {
         return entry->gr_gid == gid;
     });
     if (err) {
         return err;
     }
     err = copy_to_buffer(grp, buffer, size);
     if (err) {
         return err;
     }
     *result = grp;
     return 0;
 }
getgrnam()
struct group* getgrnam (const char * name)
Definition at line 247 of file grp-stubs.cpp.
{
     static group entry;
     int err = walk_file(&entry, [&] (group *entry) {
         return !strcmp(entry->gr_name, name);
     });
     if (err) {
         errno = err;
         return nullptr;
     }
     return &entry;
 }
getgrnam_r()
int getgrnam_r (const char * name, struct group * grp, char * buffer, size_t size, struct group ** result)
Definition at line 262 of file grp-stubs.cpp.
{
     *result = nullptr;
     int err = walk_file(grp, [&] (group *entry) {
         return !strcmp(entry->gr_name, name);
     });
     if (err) {
         return err;
     }
     err = copy_to_buffer(grp, buffer, size);
     if (err) {
         return err;
     }
     *result = grp;
     return 0;
 }
getgrouplist()
int getgrouplist (const char * user, gid_t gid, gid_t * groups, int * ngroups)
Definition at line 313 of file grp-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: getgrouplist is a stub" << frg::endlog;
     return 0;
 }
References __getgrent_a(), __nscd_query(), bswap_32, buf, calloc, cleanup(), EIO, ENOENT, ENOTDIR, errno, f, fclose(), ferror, fopen(), fread(), free, GETINITGR, gr, group::gr_gid, group::gr_mem, i, mlibc::infoLogger, INITGR_LEN, INITGRFOUND, INITGRNGRPS, mem, n, ngroups, ret, size, strcmp, and swap().
Referenced by initgroups().
initgroups()
int initgroups (const char * user, gid_t group)
Definition at line 298 of file grp-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: initgroups is a stub" << frg::endlog;
     return 0;
 }
References count, getgrouplist(), mlibc::infoLogger, NGROUPS_MAX, and setgroups().
putgrent()
int putgrent (const struct group * gr, FILE * f)
Definition at line 303 of file grp-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, done, f, flockfile(), fprintf(), fputc(), funlockfile(), gr, group::gr_gid, group::gr_mem, group::gr_name, group::gr_passwd, i, and r.
setgrent()
void setgrent (void)
Definition at line 282 of file grp-stubs.cpp.
                     {
     if(!open_global_file()) {
         return;
     }
     rewind(global_file);
 }
References f, fclose(), anonymous_namespace{grp-stubs.cpp}::global_file, anonymous_namespace{grp-stubs.cpp}::open_global_file(), and rewind().
Referenced by main().
setgroups()
int setgroups (size_t size, const gid_t * list)
Definition at line 289 of file grp-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setgroups, -1);
     if(int e = mlibc::sys_setgroups(size, list); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_setgroups().
Referenced by initgroups().