Fennix: Userspace/musl/src/stdlib/atoi.c File Reference
atoi.c File Reference
#include <stdlib.h>
#include <ctype.h>
Functions
int atoi (const char *s)
Function Documentation
atoi()
int atoi (const char * s)
Definition at line 4 of file atoi.c.
 {
     int n=0, neg=0;
     while (isspace(*s)) s++;
     switch (*s) {
     case '-': neg=1;
     case '+': s++;
     }
     /* Compute n as a negative number to avoid overflow on INT_MIN */
     while (isdigit(*s))
         n = 10*n - (*s++ - '0');
     return neg ? n : -n;
 }
References i, isdigit, isspace, Length, n, s, and strlen().
Referenced by _rl_get_screen_size(), action_compat(), bb_dump_add(), bb_dump_size(), chat_main(), cmd_kill(), compare_keys(), complete_get_screenwidth(), conf_choice(), D_DoomMain(), D_StartNetGame(), decode(), default_columns(), download_one_url(), ecvt(), evalcommand(), fbsplash_main(), G_RecordDemo(), get_linux_version_code(), get_old_name(), get_uid_gid(), getjob(), head_builtin(), I_InitGraphics(), I_ZoneBase(), init(), init_wsize(), j_infobox(), j_inputbox(), j_menu(), j_msgbox(), j_radiolist(), j_textbox(), j_yesno(), main(), number(), parse_conf(), ParseConfig(), ParseLine(), patch_main(), popmaildir_main(), preadfd(), read_command(), readtoken1(), rewrite(), sendmail_main(), smtp_checkp(), sv_compquery(), sv_compwidth(), sv_dispprefix(), sv_histsize(), sv_ignoreeof(), sv_opterr(), sv_optind(), sv_seqtimeout(), tgetnum(), CrashHandler::UserInput(), varvalue(), version_compare(), and wh_helper().