Fennix Kernel: Kernel/include/filesystem/ustar.hpp File Reference
ustar.hpp File Reference
#include <filesystem.hpp>
Data Structures
class vfs::USTAR
struct vfs::USTAR::FileHeader
struct vfs::USTAR::USTARInode
Namespaces
vfs
Functions
bool TestAndInitializeUSTAR (uintptr_t Address, size_t Size)
Data Structure Documentation
vfs::USTAR::FileHeader
struct vfs::USTAR::FileHeader
Definition at line 57 of file ustar.hpp.
Data Fields
char chksum[8]
char dev_maj[8]
char dev_min[8]
char gid[8]
char group[32]
char link[100]
char mode[8]
char mtime[12]
char name[100]
char owner[32]
char pad[12]
char prefix[155]
char signature[6]
char size[12]
char typeflag[1]
char uid[8]
char version[2]
vfs::USTAR::USTARInode
struct vfs::USTAR::USTARInode
Definition at line 80 of file ustar.hpp.
Data Fields
int Checksum
vector< USTARInode * > Children
bool Deleted
FileHeader * Header
string Name
struct Inode Node
USTARInode * Parent
string Path
Function Documentation
TestAndInitializeUSTAR()
bool TestAndInitializeUSTAR (uintptr_t Address, size_t Size)
Definition at line 834 of file ustar.cpp.
 {
     vfs::USTAR *ustar = new vfs::USTAR();
     if (!ustar->TestArchive(Address))
     {
         delete ustar;
         return false;
     }
     ustar->DeviceID = fs->EarlyReserveDevice();
     ustar->ReadArchive(Address, Size);
     Inode *initrd = nullptr;
     ustar->Lookup(nullptr, "/", &initrd);
     assert(initrd != nullptr);
     FileSystemInfo *fsi = new FileSystemInfo;
     fsi->Name = "ustar";
     fsi->RootName = "/";
     fsi->Flags = I_FLAG_ROOT | I_FLAG_MOUNTPOINT | I_FLAG_CACHE_KEEP;
     fsi->SuperOps.DeleteInode = __ustar_DestroyInode;
     fsi->SuperOps.Destroy = __ustar_Destroy;
     fsi->Ops.Lookup = __ustar_Lookup;
     fsi->Ops.Create = __ustar_Create;
     fsi->Ops.Read = __ustar_Read;
     fsi->Ops.ReadDir = __ustar_Readdir;
     fsi->Ops.SymLink = __ustar_SymLink;
     fsi->Ops.ReadLink = __ustar_ReadLink;
     fsi->Ops.Stat = __ustar_Stat;
     fsi->PrivateData = ustar;
     fs->LateRegisterFileSystem(ustar->DeviceID, fsi, initrd);
     fs->AddRoot(initrd);
     return true;
 }
References __ustar_Create(), __ustar_Destroy(), __ustar_DestroyInode(), __ustar_Lookup(), __ustar_Read(), __ustar_Readdir(), __ustar_ReadLink(), __ustar_Stat(), __ustar_SymLink(), Address, vfs::Virtual::AddRoot(), assert, InodeOperations::Create, SuperBlockOperations::DeleteInode, SuperBlockOperations::Destroy, vfs::USTAR::DeviceID, vfs::Virtual::EarlyReserveDevice(), FileSystemInfo::Flags, fs, I_FLAG_CACHE_KEEP, I_FLAG_MOUNTPOINT, I_FLAG_ROOT, vfs::Virtual::LateRegisterFileSystem(), vfs::USTAR::Lookup(), InodeOperations::Lookup, FileSystemInfo::Name, FileSystemInfo::Ops, FileSystemInfo::PrivateData, InodeOperations::Read, vfs::USTAR::ReadArchive(), InodeOperations::ReadDir, InodeOperations::ReadLink, FileSystemInfo::RootName, Size, InodeOperations::Stat, FileSystemInfo::SuperOps, InodeOperations::SymLink, and vfs::USTAR::TestArchive().
Referenced by SearchForInitrd().