Fennix Userspace: ConfigLineEdit Class Reference
ConfigLineEdit Class Reference
#include <qconf.h>
Public Member Functions
ConfigLineEdit (ConfigView *parent)
ConfigView * parent (void) const
void show (ConfigItem *i)
void keyPressEvent (QKeyEvent *e)
Data Fields
ConfigItem * item
Private Types
typedef class QLineEdit Parent
Detailed Description
Definition at line 207 of file qconf.h.
Member Typedef Documentation
Parent
typedef class QLineEdit ConfigLineEdit::Parent private
Definition at line 204 of file qconf.h.
Constructor & Destructor Documentation
ConfigLineEdit()
ConfigLineEdit::ConfigLineEdit (ConfigView * parent) inline
Definition at line 211 of file qconf.h.
     : Parent(parent)
     { }
Member Function Documentation
keyPressEvent()
void ConfigLineEdit::keyPressEvent (QKeyEvent * e)
Definition at line 369 of file qconf.cc.
 {
     switch (e->key()) {
     case Key_Escape:
         break;
     case Key_Return:
     case Key_Enter:
         sym_set_string_value(item->menu->sym, text().latin1());
         parent()->updateList(item);
         break;
     default:
         Parent::keyPressEvent(e);
         return;
     }
     e->accept();
     parent()->list->setFocus();
     hide();
 }
References item, ConfigView::list, ConfigItem::menu, parent(), menu::sym, sym_set_string_value(), text, and ConfigView::updateList().
parent()
ConfigView* ConfigLineEdit::parent (void) const inline
Definition at line 214 of file qconf.h.
     {
         return (ConfigView*)Parent::parent();
     }
References parent.
Referenced by keyPressEvent().
show()
void ConfigLineEdit::show (ConfigItem * i)
Definition at line 358 of file qconf.cc.
 {
     item = i;
     if (sym_get_string_value(item->menu->sym))
         setText(QString::fromLocal8Bit(sym_get_string_value(item->menu->sym)));
     else
         setText(QString::null);
     Parent::show();
     setFocus();
 }
References i, item, ConfigItem::menu, null(), menu::sym, and sym_get_string_value().
Referenced by ConfigList::changeValue().
Field Documentation
item
ConfigItem* ConfigLineEdit::item
Definition at line 222 of file qconf.h.
Referenced by keyPressEvent(), and show().
The documentation for this class was generated from the following files:
Userspace/apps/base/busybox/scripts/kconfig/qconf.h
Userspace/apps/base/busybox/scripts/kconfig/qconf.cc