Fennix Userspace: Userspace/musl/include/fcntl.h File Reference
fcntl.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/fcntl.h>
Data Structures
struct flock
Macros
#define __NEED_off_t
#define __NEED_pid_t
#define __NEED_mode_t
#define O_SEARCH O_PATH
#define O_EXEC O_PATH
#define O_TTY_INIT 0
#define O_ACCMODE (03|O_SEARCH)
#define O_RDONLY 00
#define O_WRONLY 01
#define O_RDWR 02
#define F_OFD_GETLK 36
#define F_OFD_SETLK 37
#define F_OFD_SETLKW 38
#define F_DUPFD_CLOEXEC 1030
#define F_RDLCK 0
#define F_WRLCK 1
#define F_UNLCK 2
#define FD_CLOEXEC 1
#define AT_FDCWD (-100)
#define AT_SYMLINK_NOFOLLOW 0x100
#define AT_REMOVEDIR 0x200
#define AT_SYMLINK_FOLLOW 0x400
#define AT_EACCESS 0x200
#define POSIX_FADV_NORMAL 0
#define POSIX_FADV_RANDOM 1
#define POSIX_FADV_SEQUENTIAL 2
#define POSIX_FADV_WILLNEED 3
#define POSIX_FADV_DONTNEED 4
#define POSIX_FADV_NOREUSE 5
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define S_ISUID 04000
#define S_ISGID 02000
#define S_ISVTX 01000
#define S_IRUSR 0400
#define S_IWUSR 0200
#define S_IXUSR 0100
#define S_IRWXU 0700
#define S_IRGRP 0040
#define S_IWGRP 0020
#define S_IXGRP 0010
#define S_IRWXG 0070
#define S_IROTH 0004
#define S_IWOTH 0002
#define S_IXOTH 0001
#define S_IRWXO 0007
Functions
int creat (const char *, mode_t)
int fcntl (int, int,...)
int open (const char *, int,...)
int openat (int, const char *, int,...)
int posix_fadvise (int, off_t, off_t, int)
int posix_fallocate (int, off_t, off_t)
Data Structure Documentation
flock
struct flock
Definition at line 24 of file fcntl.h.
Data Fields
off_t l_len
pid_t l_pid
off_t l_start
short l_type
short l_whence
Macro Definition Documentation
__NEED_mode_t
#define __NEED_mode_t
Definition at line 12 of file fcntl.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 10 of file fcntl.h.
__NEED_pid_t
#define __NEED_pid_t
Definition at line 11 of file fcntl.h.
AT_EACCESS
#define AT_EACCESS 0x200
Definition at line 64 of file fcntl.h.
AT_FDCWD
#define AT_FDCWD (-100)
Definition at line 60 of file fcntl.h.
AT_REMOVEDIR
#define AT_REMOVEDIR 0x200
Definition at line 62 of file fcntl.h.
AT_SYMLINK_FOLLOW
#define AT_SYMLINK_FOLLOW 0x400
Definition at line 63 of file fcntl.h.
AT_SYMLINK_NOFOLLOW
#define AT_SYMLINK_NOFOLLOW 0x100
Definition at line 61 of file fcntl.h.
F_DUPFD_CLOEXEC
#define F_DUPFD_CLOEXEC 1030
Definition at line 52 of file fcntl.h.
F_OFD_GETLK
#define F_OFD_GETLK 36
Definition at line 48 of file fcntl.h.
F_OFD_SETLK
#define F_OFD_SETLK 37
Definition at line 49 of file fcntl.h.
F_OFD_SETLKW
#define F_OFD_SETLKW 38
Definition at line 50 of file fcntl.h.
F_RDLCK
#define F_RDLCK 0
Definition at line 54 of file fcntl.h.
F_UNLCK
#define F_UNLCK 2
Definition at line 56 of file fcntl.h.
F_WRLCK
#define F_WRLCK 1
Definition at line 55 of file fcntl.h.
FD_CLOEXEC
#define FD_CLOEXEC 1
Definition at line 58 of file fcntl.h.
O_ACCMODE
#define O_ACCMODE (03|O_SEARCH)
Definition at line 43 of file fcntl.h.
O_EXEC
#define O_EXEC O_PATH
Definition at line 40 of file fcntl.h.
O_RDONLY
#define O_RDONLY 00
Definition at line 44 of file fcntl.h.
O_RDWR
#define O_RDWR 02
Definition at line 46 of file fcntl.h.
O_SEARCH
#define O_SEARCH O_PATH
Definition at line 39 of file fcntl.h.
O_TTY_INIT
#define O_TTY_INIT 0
Definition at line 41 of file fcntl.h.
O_WRONLY
#define O_WRONLY 01
Definition at line 45 of file fcntl.h.
POSIX_FADV_DONTNEED
#define POSIX_FADV_DONTNEED 4
Definition at line 71 of file fcntl.h.
POSIX_FADV_NOREUSE
#define POSIX_FADV_NOREUSE 5
Definition at line 72 of file fcntl.h.
POSIX_FADV_NORMAL
#define POSIX_FADV_NORMAL 0
Definition at line 66 of file fcntl.h.
POSIX_FADV_RANDOM
#define POSIX_FADV_RANDOM 1
Definition at line 67 of file fcntl.h.
POSIX_FADV_SEQUENTIAL
#define POSIX_FADV_SEQUENTIAL 2
Definition at line 68 of file fcntl.h.
POSIX_FADV_WILLNEED
#define POSIX_FADV_WILLNEED 3
Definition at line 69 of file fcntl.h.
S_IRGRP
#define S_IRGRP 0040
Definition at line 90 of file fcntl.h.
S_IROTH
#define S_IROTH 0004
Definition at line 94 of file fcntl.h.
S_IRUSR
#define S_IRUSR 0400
Definition at line 86 of file fcntl.h.
S_IRWXG
#define S_IRWXG 0070
Definition at line 93 of file fcntl.h.
S_IRWXO
#define S_IRWXO 0007
Definition at line 97 of file fcntl.h.
S_IRWXU
#define S_IRWXU 0700
Definition at line 89 of file fcntl.h.
S_ISGID
#define S_ISGID 02000
Definition at line 84 of file fcntl.h.
S_ISUID
#define S_ISUID 04000
Definition at line 83 of file fcntl.h.
S_ISVTX
#define S_ISVTX 01000
Definition at line 85 of file fcntl.h.
S_IWGRP
#define S_IWGRP 0020
Definition at line 91 of file fcntl.h.
S_IWOTH
#define S_IWOTH 0002
Definition at line 95 of file fcntl.h.
S_IWUSR
#define S_IWUSR 0200
Definition at line 87 of file fcntl.h.
S_IXGRP
#define S_IXGRP 0010
Definition at line 92 of file fcntl.h.
S_IXOTH
#define S_IXOTH 0001
Definition at line 96 of file fcntl.h.
S_IXUSR
#define S_IXUSR 0100
Definition at line 88 of file fcntl.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 79 of file fcntl.h.
SEEK_END
#define SEEK_END 2
Definition at line 80 of file fcntl.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 78 of file fcntl.h.
Function Documentation
creat()
int creat (const char * filename, mode_t mode)
Definition at line 3 of file creat.c.
 {
     return open(filename, O_CREAT|O_WRONLY|O_TRUNC, mode);
 }
References filename, O_CREAT, O_TRUNC, O_WRONLY, and open().
Referenced by show_textbox(), and writeLines().
fcntl()
int fcntl (int fd, int cmd, ...)
Definition at line 7 of file fcntl.c.
 {
     unsigned long arg;
     va_list ap;
     va_start(ap, cmd);
     arg = va_arg(ap, unsigned long);
     va_end(ap);
     if (cmd == F_SETFL) arg |= O_LARGEFILE;
     if (cmd == F_SETLKW) return syscall_cp(SYS_fcntl, fd, cmd, (void *)arg);
     if (cmd == F_GETOWN) {
         struct f_owner_ex ex;
         int ret = __syscall(SYS_fcntl, fd, F_GETOWN_EX, &ex);
         if (ret == -EINVAL) return __syscall(SYS_fcntl, fd, cmd, (void *)arg);
         if (ret) return __syscall_ret(ret);
         return ex.type == F_OWNER_PGRP ? -ex.pid : ex.pid;
     }
     if (cmd == F_DUPFD_CLOEXEC) {
         int ret = __syscall(SYS_fcntl, fd, F_DUPFD_CLOEXEC, arg);
         if (ret != -EINVAL) {
             if (ret >= 0)
                 __syscall(SYS_fcntl, ret, F_SETFD, FD_CLOEXEC);
             return __syscall_ret(ret);
         }
         ret = __syscall(SYS_fcntl, fd, F_DUPFD_CLOEXEC, 0);
         if (ret != -EINVAL) {
             if (ret >= 0) __syscall(SYS_close, ret);
             return __syscall_ret(-EINVAL);
         }
         ret = __syscall(SYS_fcntl, fd, F_DUPFD, arg);
         if (ret >= 0) __syscall(SYS_fcntl, ret, F_SETFD, FD_CLOEXEC);
         return __syscall_ret(ret);
     }
     switch (cmd) {
     case F_SETLK:
     case F_GETLK:
     case F_GETOWN_EX:
     case F_SETOWN_EX:
         return syscall(SYS_fcntl, fd, cmd, (void *)arg);
     default:
         return syscall(SYS_fcntl, fd, cmd, arg);
     }
 }
References __syscall, __syscall_ret(), ap, cmd, EINVAL, F_DUPFD, F_DUPFD_CLOEXEC, F_GETLK, F_GETOWN, F_GETOWN_EX, F_SETFD, F_SETFL, F_SETLK, F_SETLKW, F_SETOWN_EX, fd, FD_CLOEXEC, O_LARGEFILE, syscall(), syscall_cp, va_arg, va_end, and va_start.
Referenced by __aio_get_queue(), add_undo_redirect(), close_conn_and_exit(), close_on_exec_on(), device_open(), do_redirection_internal(), do_wordexp(), dup2(), dup_CLOEXEC(), evalbackcmd(), fdopendir(), getflags(), getmaxfd(), handle_accept(), here_document_to_fd(), io_thread_func(), isastream(), isrv_run(), lockf(), log_locally(), main(), microcom_main(), move_to_high_fd(), ndelay_off(), ndelay_on(), ndelay_read(), open_tty(), popen(), preadfd(), printf_main(), read_lines(), redir_special_open(), rl_gather_tyi(), savefd(), setone(), sh_unset_nodelay_mode(), sh_validfd(), svlogd_main(), undoablefd(), update_passwd(), and xdup_CLOEXEC_and_close().
open()
int open (const char * filename, int flags, ...)
Definition at line 5 of file open.c.
 {
     mode_t mode = 0;
     if ((flags & O_CREAT) || (flags & O_TMPFILE) == O_TMPFILE) {
         va_list ap;
         va_start(ap, flags);
         mode = va_arg(ap, mode_t);
         va_end(ap);
     }
     int fd = __sys_open_cp(filename, flags, mode);
     if (fd>=0 && (flags & O_CLOEXEC))
         __syscall(SYS_fcntl, fd, F_SETFD, FD_CLOEXEC);
     return __syscall_ret(fd);
 }
References __sys_open_cp, __syscall, __syscall_ret(), ap, F_SETFD, fd, FD_CLOEXEC, filename, flags, mode_t, O_CLOEXEC, O_CREAT, O_TMPFILE, va_arg, va_end, and va_start.
Referenced by __dls3(), __mkostemps(), _evalfile(), _nl_load_domain(), _rl_read_file(), _vsyslog(), acpid_main(), add_to_uuid_cache(), archivefile(), async_redirect_stdin(), bb_daemonize_or_rexec(), bb_init_module(), cat_main(), check_dev_tty(), check_mount(), console_init(), copy_file(), copy_inode(), creat(), create_cdev_if_doesnt_exist(), crontab_main(), cttyhack_main(), cutfile(), daemon(), del_loop(), device_open(), dialog_textbox(), diffreg(), do_config_file(), do_nftw(), download_one_url(), dump_file(), dump_procs(), edir(), extract_info(), fbsplash_main(), file_insert(), file_write(), filter_rename_config(), flock_main(), fmtmsg(), forkchild(), get_boot(), get_free_loop(), get_terminal_width_height(), get_vt_fd(), getpass(), getrandom(), getspnam_r(), getty_main(), handle_retr(), here_document_to_fd(), hfopen(), history_do_write(), history_truncate_file(), i2c_dev_open(), initialize_job_control(), is_whole_disk(), less_main(), load_firmware(), load_library(), log_locally(), logdir_open(), main(), microcom_main(), motd(), nbdclient_main(), noclobber_open(), nohup_main(), open3_or_warn(), open_a_console(), open_loop_on_busy(), open_mdev_log(), open_new_state_file(), open_read_close(), open_redir_file(), open_shell_script(), open_trunc_or_warn(), opendir(), openpty(), openredirect(), parse_comsub(), parse_matched_pair(), path_open(), posix_openpt(), print_deps(), process_includes(), processorstart(), pscan_main(), pthread_getname_np(), pthread_setname_np(), query_loop(), read_history_range(), read_to_buf(), readLines(), redir_open(), redir_special_open(), rotate(), run_pipe(), runsv_main(), runsvdir_main(), sem_open(), send_file_and_exit(), set_loop(), ConfigList::setAllOpen(), setinputfile(), sh_mktmpfd(), shm_open(), shred_main(), skip_matched_pair(), skip_to_delim(), slattach_main(), sysctl_act_on_setting(), tail_main(), tee_builtin(), tgetent(), touch(), touch_main(), truncate_main(), unquoted_glob_pattern_p(), unzip_main(), update_passwd(), wait_for_seqfile(), write_pidfile(), xgetpty(), xmalloc_open_read_close(), and xopen3().
openat()
int openat (int fd, const char * filename, int flags, ...)
Definition at line 5 of file openat.c.
 {
     mode_t mode = 0;
     if ((flags & O_CREAT) || (flags & O_TMPFILE) == O_TMPFILE) {
         va_list ap;
         va_start(ap, flags);
         mode = va_arg(ap, mode_t);
         va_end(ap);
     }
     return syscall_cp(SYS_openat, fd, filename, flags|O_LARGEFILE, mode);
 }
References ap, fd, filename, flags, mode_t, O_CREAT, O_LARGEFILE, O_TMPFILE, syscall_cp, va_arg, va_end, and va_start.
posix_fadvise()
int posix_fadvise (int fd, off_t base, off_t len, int advice)
Definition at line 4 of file posix_fadvise.c.
 {
 #if defined(SYSCALL_FADVISE_6_ARG)
     /* Some archs, at least arm and powerpc, have the syscall
      * arguments reordered to avoid needing 7 argument registers
      * due to 64-bit argument alignment. */
     return -__syscall(SYS_fadvise, fd, advice,
         __SYSCALL_LL_E(base), __SYSCALL_LL_E(len));
 #else
     return -__syscall(SYS_fadvise, fd, __SYSCALL_LL_O(base),
         __SYSCALL_LL_E(len), advice);
 #endif
 }
References __syscall, __SYSCALL_LL_E, __SYSCALL_LL_O, base, and fd.
posix_fallocate()
int posix_fallocate (int fd, off_t base, off_t len)
Definition at line 4 of file posix_fallocate.c.
 {
     return -__syscall(SYS_fallocate, fd, 0, __SYSCALL_LL_E(base),
         __SYSCALL_LL_E(len));
 }
References __syscall, __SYSCALL_LL_E, base, and fd.
Referenced by fallocate_main().