Fennix Userspace: Userspace/apps/base/bash/lib/readline/terminal.c File Reference
terminal.c File Reference
#include <sys/types.h>
#include "posixstat.h"
#include <fcntl.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "rltty.h"
#include "tcap.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "rlshell.h"
#include "xmalloc.h"
Data Structures
struct _tc_string
Macros
#define READLINE_LIBRARY
#define TGETENT_SUCCESS 1
#define TGETFLAG_SUCCESS 1
#define TGETFLAG(cap) (tgetflag (cap) == TGETFLAG_SUCCESS)
#define NUM_TC_STRINGS (sizeof (tc_strings) / sizeof (struct _tc_string))
Functions
static void bind_termcap_arrow_keys (Keymap)
void _rl_get_screen_size (int tty, int ignore_env)
void _rl_set_screen_size (int rows, int cols)
void rl_set_screen_size (int rows, int cols)
void rl_get_screen_size (int *rows, int *cols)
void rl_reset_screen_size (void)
void _rl_sigwinch_resize_terminal (void)
void rl_resize_terminal (void)
static void get_term_capabilities (char **bp)
int _rl_init_terminal_io (const char *terminal_name)
char * rl_get_termcap (const char *cap)
int rl_reset_terminal (const char *terminal_name)
int _rl_output_character_function (int c)
void _rl_output_some_chars (const char *string, int count)
int _rl_backspace (int count)
int rl_crlf (void)
void _rl_cr (void)
int rl_ding (void)
void _rl_standout_on (void)
void _rl_standout_off (void)
int _rl_reset_region_color (int which, const char *value)
void _rl_region_color_on (void)
void _rl_region_color_off (void)
void _rl_enable_meta_key (void)
void _rl_disable_meta_key (void)
void _rl_control_keypad (int on)
void _rl_set_cursor (int im, int force)
Variables
int rl_prefer_env_winsize = 0
int rl_change_environment = 1
static char * term_buffer = (char *)NULL
static char * term_string_buffer = (char *)NULL
static int tcap_initialized
char PC
char * BC
char * UP
char * _rl_term_clreol
char * _rl_term_clrpag
char * _rl_term_clrscroll
char * _rl_term_cr
char * _rl_term_backspace
char * _rl_term_goto
char * _rl_term_pc
int _rl_terminal_can_insert = 0
char * _rl_term_im
char * _rl_term_ei
char * _rl_term_ic
char * _rl_term_ip
char * _rl_term_IC
char * _rl_term_dc
char * _rl_term_DC
char * _rl_term_forward_char
char * _rl_term_up
static char * _rl_visible_bell
int _rl_term_autowrap = -1
static int term_has_meta
static char * _rl_term_mm
static char * _rl_term_mo
static char * _rl_term_so
static char * _rl_term_se
static char * _rl_term_ku
static char * _rl_term_kd
static char * _rl_term_kr
static char * _rl_term_kl
static char * _rl_term_ks
static char * _rl_term_ke
static char * _rl_term_kh
static char * _rl_term_kH
static char * _rl_term_at7
static char * _rl_term_kD
static char * _rl_term_kI
static char * _rl_term_kP
static char * _rl_term_kN
static char * _rl_term_vs
static char * _rl_term_ve
char * _rl_active_region_start_color = NULL
char * _rl_active_region_end_color = NULL
int _rl_screenwidth
int _rl_screenheight
int _rl_screenchars
int _rl_enable_keypad
int _rl_enable_meta = 1
static const struct _tc_string tc_strings []
static int enabled_meta = 0
Data Structure Documentation
_tc_string
struct _tc_string
Definition at line 408 of file terminal.c.
Data Fields
char ** tc_value
const char *const tc_var
Macro Definition Documentation
NUM_TC_STRINGS
#define NUM_TC_STRINGS (sizeof (tc_strings) / sizeof (struct _tc_string))
Definition at line 453 of file terminal.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file terminal.c.
TGETENT_SUCCESS
#define TGETENT_SUCCESS 1
Definition at line 197 of file terminal.c.
TGETFLAG
#define TGETFLAG (cap) (tgetflag (cap) == TGETFLAG_SUCCESS)
Definition at line 204 of file terminal.c.
TGETFLAG_SUCCESS
#define TGETFLAG_SUCCESS 1
Definition at line 202 of file terminal.c.
Function Documentation
_rl_backspace()
int _rl_backspace (int count)
Definition at line 717 of file terminal.c.
 {
   register int i;
 #ifndef __MSDOS__
   if (_rl_term_backspace)
     for (i = 0; i < count; i++)
       tputs (_rl_term_backspace, 1, _rl_output_character_function);
   else
 #endif
     for (i = 0; i < count; i++)
       putc ('\b', _rl_out_stream);
   return 0;
 }
References _rl_out_stream, _rl_output_character_function(), _rl_term_backspace, count, i, putc, and tputs().
Referenced by _rl_erase_at_end_of_line(), _rl_move_cursor_relative(), open_some_spaces(), and rl_redisplay().
_rl_control_keypad()
void _rl_control_keypad (int on)
Definition at line 904 of file terminal.c.
 {
 #if !defined (__DJGPP__)
   if (on && _rl_term_ks)
     tputs (_rl_term_ks, 1, _rl_output_character_function);
   else if (!on && _rl_term_ke)
     tputs (_rl_term_ke, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_ke, _rl_term_ks, and tputs().
Referenced by rl_deprep_terminal(), and rl_prep_terminal().
_rl_cr()
void _rl_cr (void)
Definition at line 745 of file terminal.c.
 {
 #if defined (__MSDOS__)
   putc ('\r', rl_outstream);
 #else
   tputs (_rl_term_cr, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_cr, putc, rl_outstream, and tputs().
Referenced by _rl_move_cursor_relative(), _rl_move_vert(), cr(), rl_clear_visible_line(), rl_redisplay(), and update_line().
_rl_disable_meta_key()
void _rl_disable_meta_key (void)
Definition at line 892 of file terminal.c.
 {
 #if !defined (__DJGPP__)
   if (term_has_meta && _rl_term_mo && enabled_meta)
     {
       tputs (_rl_term_mo, 1, _rl_output_character_function);
       enabled_meta = 0;
     }
 #endif
 }
References _rl_output_character_function(), _rl_term_mo, enabled_meta, term_has_meta, and tputs().
Referenced by readline_internal_teardown().
_rl_enable_meta_key()
void _rl_enable_meta_key (void)
Definition at line 880 of file terminal.c.
 {
 #if !defined (__DJGPP__)
   if (term_has_meta && _rl_term_mm)
     {
       tputs (_rl_term_mm, 1, _rl_output_character_function);
       enabled_meta = 1;
     }
 #endif
 }
References _rl_output_character_function(), _rl_term_mm, enabled_meta, term_has_meta, and tputs().
Referenced by readline_internal_setup().
_rl_get_screen_size()
void _rl_get_screen_size (int tty, int ignore_env)
Definition at line 256 of file terminal.c.
 {
   char *ss;
 #if defined (TIOCGWINSZ)
   struct winsize window_size;
 #endif /* TIOCGWINSZ */
   int wr, wc;
   wr = wc = -1;
 #if defined (TIOCGWINSZ)
   if (ioctl (tty, TIOCGWINSZ, &window_size) == 0)
     {
       wc = (int) window_size.ws_col;
       wr = (int) window_size.ws_row;
     }
 #endif /* TIOCGWINSZ */
 #if defined (__EMX__)
   _emx_get_screensize (&wc, &wr);
 #elif defined (__MINGW32__)
   _win_get_screensize (&wc, &wr);
 #endif
   if (ignore_env || rl_prefer_env_winsize == 0)
     {
       _rl_screenwidth = wc;
       _rl_screenheight = wr;
     }
   else
     _rl_screenwidth = _rl_screenheight = -1;
   /* Environment variable COLUMNS overrides setting of "co" if IGNORE_ENV
      is unset.  If we prefer the environment, check it first before
      assigning the value returned by the kernel. */
   if (_rl_screenwidth <= 0)
     {
       if (ignore_env == 0 && (ss = sh_get_env_value ("COLUMNS")))
     _rl_screenwidth = atoi (ss);
       if (_rl_screenwidth <= 0)
         _rl_screenwidth = wc;
 #if defined (__DJGPP__)
       if (_rl_screenwidth <= 0)
     _rl_screenwidth = ScreenCols ();
 #else
       if (_rl_screenwidth <= 0 && term_string_buffer)
     _rl_screenwidth = tgetnum ("co");
 #endif
     }
   /* Environment variable LINES overrides setting of "li" if IGNORE_ENV
      is unset. */
   if (_rl_screenheight <= 0)
     {
       if (ignore_env == 0 && (ss = sh_get_env_value ("LINES")))
     _rl_screenheight = atoi (ss);
       if (_rl_screenheight <= 0)
         _rl_screenheight = wr;
 #if defined (__DJGPP__)
       if (_rl_screenheight <= 0)
     _rl_screenheight = ScreenRows ();
 #else
       if (_rl_screenheight <= 0 && term_string_buffer)
     _rl_screenheight = tgetnum ("li");
 #endif
     }
   /* If all else fails, default to 80x24 terminal. */
   if (_rl_screenwidth <= 1)
     _rl_screenwidth = 80;
   if (_rl_screenheight <= 0)
     _rl_screenheight = 24;
   /* If we're being compiled as part of bash, set the environment
      variables $LINES and $COLUMNS to new values.  Otherwise, just
      do a pair of putenv () or setenv () calls. */
   if (rl_change_environment)
     sh_set_lines_and_columns (_rl_screenheight, _rl_screenwidth);
   if (_rl_term_autowrap == 0)
     _rl_screenwidth--;
   _rl_screenchars = _rl_screenwidth * _rl_screenheight;
 }
References _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_autowrap, atoi(), ioctl(), rl_change_environment, rl_prefer_env_winsize, sh_get_env_value(), sh_set_lines_and_columns(), term_string_buffer, tgetnum(), and TIOCGWINSZ.
Referenced by _rl_init_terminal_io(), _rl_sigwinch_resize_terminal(), expand_prompt(), rl_reset_screen_size(), and rl_resize_terminal().
_rl_init_terminal_io()
int _rl_init_terminal_io (const char * terminal_name)
Definition at line 470 of file terminal.c.
 {
   const char *term;
   char *buffer;
   int tty, tgetent_ret, dumbterm, reset_region_colors;
   term = terminal_name ? terminal_name : sh_get_env_value ("TERM");
   _rl_term_clrpag = _rl_term_cr = _rl_term_clreol = _rl_term_clrscroll = (char *)NULL;
   tty = rl_instream ? fileno (rl_instream) : 0;
   if (term == 0)
     term = "dumb";
   dumbterm = STREQ (term, "dumb");
   reset_region_colors = 1;
 #ifdef __MSDOS__
   _rl_term_im = _rl_term_ei = _rl_term_ic = _rl_term_IC = (char *)NULL;
   _rl_term_up = _rl_term_dc = _rl_term_DC = _rl_visible_bell = (char *)NULL;
   _rl_term_ku = _rl_term_kd = _rl_term_kl = _rl_term_kr = (char *)NULL;
   _rl_term_mm = _rl_term_mo = (char *)NULL;
   _rl_terminal_can_insert = term_has_meta = _rl_term_autowrap = 0;
   _rl_term_cr = "\r";
   _rl_term_backspace = (char *)NULL;
   _rl_term_goto = _rl_term_pc = _rl_term_ip = (char *)NULL;
   _rl_term_ks = _rl_term_ke =_rl_term_vs = _rl_term_ve = (char *)NULL;
   _rl_term_kh = _rl_term_kH = _rl_term_at7 = _rl_term_kI = (char *)NULL;
   _rl_term_kN = _rl_term_kP = (char *)NULL;
   _rl_term_so = _rl_term_se = (char *)NULL;
 #if defined(HACK_TERMCAP_MOTION)
   _rl_term_forward_char = (char *)NULL;
 #endif
   _rl_get_screen_size (tty, 0);
 #else  /* !__MSDOS__ */
   /* I've separated this out for later work on not calling tgetent at all
      if the calling application has supplied a custom redisplay function,
      (and possibly if the application has supplied a custom input function). */
   if (CUSTOM_REDISPLAY_FUNC())
     {
       tgetent_ret = -1;
     }
   else
     {
       if (term_string_buffer == 0)
     term_string_buffer = (char *)xmalloc(2032);
       if (term_buffer == 0)
     term_buffer = (char *)xmalloc(4080);
       buffer = term_string_buffer;
       tgetent_ret = tgetent (term_buffer, term);
     }
   if (tgetent_ret != TGETENT_SUCCESS)
     {
       FREE (term_string_buffer);
       FREE (term_buffer);
       buffer = term_buffer = term_string_buffer = (char *)NULL;
       _rl_term_autowrap = 0;    /* used by _rl_get_screen_size */
       /* Allow calling application to set default height and width, using
      rl_set_screen_size */
       if (_rl_screenwidth <= 0 || _rl_screenheight <= 0)
     {
 #if defined (__EMX__)
       _emx_get_screensize (&_rl_screenwidth, &_rl_screenheight);
       _rl_screenwidth--;
 #else /* !__EMX__ */
       _rl_get_screen_size (tty, 0);
 #endif /* !__EMX__ */
     }
       /* Defaults. */
       if (_rl_screenwidth <= 0 || _rl_screenheight <= 0)
         {
       _rl_screenwidth = 79;
       _rl_screenheight = 24;
         }
       /* Everything below here is used by the redisplay code (tputs). */
       _rl_screenchars = _rl_screenwidth * _rl_screenheight;
       _rl_term_cr = "\r";
       _rl_term_im = _rl_term_ei = _rl_term_ic = _rl_term_IC = (char *)NULL;
       _rl_term_up = _rl_term_dc = _rl_term_DC = _rl_visible_bell = (char *)NULL;
       _rl_term_ku = _rl_term_kd = _rl_term_kl = _rl_term_kr = (char *)NULL;
       _rl_term_kh = _rl_term_kH = _rl_term_kI = _rl_term_kD = (char *)NULL;
       _rl_term_ks = _rl_term_ke = _rl_term_at7 = (char *)NULL;
       _rl_term_kN = _rl_term_kP = (char *)NULL;
       _rl_term_mm = _rl_term_mo = (char *)NULL;
       _rl_term_ve = _rl_term_vs = (char *)NULL;
       _rl_term_forward_char = (char *)NULL;
       _rl_term_so = _rl_term_se = (char *)NULL;
       _rl_terminal_can_insert = term_has_meta = 0;
       /* Assume generic unknown terminal can't handle the enable/disable
      escape sequences */
       _rl_enable_bracketed_paste = 0;
       /* No terminal so/se capabilities. */
       _rl_enable_active_region = 0;
       _rl_reset_region_color (0, NULL);
       _rl_reset_region_color (1, NULL);
       /* Reasonable defaults for tgoto().  Readline currently only uses
          tgoto if _rl_term_IC or _rl_term_DC is defined, but just in case we
          change that later... */
       PC = '\0';
       BC = _rl_term_backspace = "\b";
       UP = _rl_term_up;
       return 0;
     }
   get_term_capabilities (&buffer);
   /* Set up the variables that the termcap library expects the application
      to provide. */
   PC = _rl_term_pc ? *_rl_term_pc : 0;
   BC = _rl_term_backspace;
   UP = _rl_term_up;
   if (_rl_term_cr == 0)
     _rl_term_cr = "\r";
   _rl_term_autowrap = TGETFLAG ("am") && TGETFLAG ("xn");
   /* Allow calling application to set default height and width, using
      rl_set_screen_size */
   if (_rl_screenwidth <= 0 || _rl_screenheight <= 0)
     _rl_get_screen_size (tty, 0);
   /* "An application program can assume that the terminal can do
       character insertion if *any one of* the capabilities `IC',
       `im', `ic' or `ip' is provided."  But we can't do anything if
       only `ip' is provided, so... */
   _rl_terminal_can_insert = (_rl_term_IC || _rl_term_im || _rl_term_ic);
   /* Check to see if this terminal has a meta key and clear the capability
      variables if there is none. */
   term_has_meta = TGETFLAG ("km");
   if (term_has_meta == 0)
     _rl_term_mm = _rl_term_mo = (char *)NULL;
 #endif /* !__MSDOS__ */
   /* Attempt to find and bind the arrow keys.  Do not override already
      bound keys in an overzealous attempt, however. */
   bind_termcap_arrow_keys (emacs_standard_keymap);
 #if defined (VI_MODE)
   bind_termcap_arrow_keys (vi_movement_keymap);
   bind_termcap_arrow_keys (vi_insertion_keymap);
 #endif /* VI_MODE */
   /* There's no way to determine whether or not a given terminal supports
      bracketed paste mode, so we assume a terminal named "dumb" does not. */
   if (dumbterm)
     _rl_enable_bracketed_paste = _rl_enable_active_region = 0;
   if (reset_region_colors)
     {
       _rl_reset_region_color (0, _rl_term_so);
       _rl_reset_region_color (1, _rl_term_se);
     }
   return 0;
 }
References _rl_enable_active_region, _rl_enable_bracketed_paste, _rl_get_screen_size(), _rl_reset_region_color(), _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_at7, _rl_term_autowrap, _rl_term_backspace, _rl_term_clreol, _rl_term_clrpag, _rl_term_clrscroll, _rl_term_cr, _rl_term_dc, _rl_term_DC, _rl_term_ei, _rl_term_forward_char, _rl_term_goto, _rl_term_ic, _rl_term_IC, _rl_term_im, _rl_term_ip, _rl_term_kd, _rl_term_kD, _rl_term_ke, _rl_term_kh, _rl_term_kH, _rl_term_kI, _rl_term_kl, _rl_term_kN, _rl_term_kP, _rl_term_kr, _rl_term_ks, _rl_term_ku, _rl_term_mm, _rl_term_mo, _rl_term_pc, _rl_term_se, _rl_term_so, _rl_term_up, _rl_term_ve, _rl_term_vs, _rl_terminal_can_insert, _rl_visible_bell, BC, bind_termcap_arrow_keys(), buffer, CUSTOM_REDISPLAY_FUNC, emacs_standard_keymap, fileno(), FREE, get_term_capabilities(), NULL, PC, rl_instream, sh_get_env_value(), STREQ, term, term_buffer, term_has_meta, term_string_buffer, tgetent(), TGETENT_SUCCESS, TGETFLAG, UP, vi_insertion_keymap, vi_movement_keymap, and xmalloc.
Referenced by _rl_set_screen_size(), readline_initialize_everything(), and rl_reset_terminal().
_rl_output_character_function()
int _rl_output_character_function (int c)
Definition at line 702 of file terminal.c.
 {
   return putc (c, _rl_out_stream);
 }
References _rl_out_stream, c, and putc.
Referenced by _rl_backspace(), _rl_clear_screen(), _rl_clear_to_eol(), _rl_control_keypad(), _rl_cr(), _rl_disable_meta_key(), _rl_enable_meta_key(), _rl_move_cursor_relative(), _rl_move_vert(), _rl_region_color_off(), _rl_region_color_on(), _rl_set_cursor(), _rl_standout_off(), _rl_standout_on(), delete_chars(), open_some_spaces(), rl_crlf(), and rl_ding().
_rl_output_some_chars()
void _rl_output_some_chars (const char * string, int count)
Definition at line 710 of file terminal.c.
 {
   fwrite (string, 1, count, _rl_out_stream);
 }
References _rl_out_stream, count, and fwrite().
Referenced by insert_some_chars(), rl_echo_signal_char(), rl_on_new_line_with_prompt(), rl_redisplay(), and update_line().
_rl_region_color_off()
void _rl_region_color_off (void)
Definition at line 863 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_active_region_start_color && _rl_active_region_end_color)
     tputs (_rl_active_region_end_color, 1, _rl_output_character_function);
 #endif
 }
References _rl_active_region_end_color, _rl_active_region_start_color, _rl_output_character_function(), and tputs().
Referenced by putc_face().
_rl_region_color_on()
void _rl_region_color_on (void)
Definition at line 854 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_active_region_start_color && _rl_active_region_end_color)
     tputs (_rl_active_region_start_color, 1, _rl_output_character_function);
 #endif
 }
References _rl_active_region_end_color, _rl_active_region_start_color, _rl_output_character_function(), and tputs().
Referenced by putc_face().
_rl_reset_region_color()
int _rl_reset_region_color (int which, const char * value)
Definition at line 821 of file terminal.c.
 {
   int len;
   if (which == 0)
     {
       xfree (_rl_active_region_start_color);
       if (value && *value)
     {
       _rl_active_region_start_color = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_active_region_start_color, &len);
       _rl_active_region_start_color[len] = '\0';
     }
       else
     _rl_active_region_start_color = NULL;
     }
   else
     {
       xfree (_rl_active_region_end_color);
       if (value && *value)
     {
       _rl_active_region_end_color = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_active_region_end_color, &len);
       _rl_active_region_end_color[len] = '\0';
     }
       else
     _rl_active_region_end_color = NULL;
     }
   return 0;
 }
References _rl_active_region_end_color, _rl_active_region_start_color, NULL, rl_translate_keyseq(), strlen(), value, xfree, and xmalloc.
Referenced by _rl_init_terminal_io(), sv_region_end_color(), and sv_region_start_color().
_rl_set_cursor()
void _rl_set_cursor (int im, int force)
Definition at line 925 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_ve && _rl_term_vs)
     {
       if (force || im != rl_insert_mode)
     {
       if (im == RL_IM_OVERWRITE)
         tputs (_rl_term_vs, 1, _rl_output_character_function);
       else
         tputs (_rl_term_ve, 1, _rl_output_character_function);
     }
     }
 #endif
 }
References _rl_output_character_function(), _rl_term_ve, _rl_term_vs, force, RL_IM_OVERWRITE, rl_insert_mode, and tputs().
Referenced by _rl_set_insert_mode().
_rl_set_screen_size()
void _rl_set_screen_size (int rows, int cols)
Definition at line 346 of file terminal.c.
 {
   if (_rl_term_autowrap == -1)
     _rl_init_terminal_io (rl_terminal_name);
   if (rows > 0)
     _rl_screenheight = rows;
   if (cols > 0)
     {
       _rl_screenwidth = cols;
       if (_rl_term_autowrap == 0)
     _rl_screenwidth--;
     }
   if (rows > 0 || cols > 0)
     _rl_screenchars = _rl_screenwidth * _rl_screenheight;
 }
References _rl_init_terminal_io(), _rl_screenchars, _rl_screenheight, _rl_screenwidth, _rl_term_autowrap, cols, rl_terminal_name, and rows.
Referenced by rl_set_screen_size().
_rl_sigwinch_resize_terminal()
void _rl_sigwinch_resize_terminal (void)
Definition at line 386 of file terminal.c.
 {
   _rl_get_screen_size (fileno (rl_instream), 1);
 }
References _rl_get_screen_size(), fileno(), and rl_instream.
_rl_standout_off()
void _rl_standout_off (void)
Definition at line 802 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_so && _rl_term_se)
     tputs (_rl_term_se, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_se, _rl_term_so, and tputs().
_rl_standout_on()
void _rl_standout_on (void)
Definition at line 793 of file terminal.c.
 {
 #ifndef __MSDOS__
   if (_rl_term_so && _rl_term_se)
     tputs (_rl_term_so, 1, _rl_output_character_function);
 #endif
 }
References _rl_output_character_function(), _rl_term_se, _rl_term_so, and tputs().
bind_termcap_arrow_keys()
static void bind_termcap_arrow_keys (Keymap map) static
Definition at line 644 of file terminal.c.
 {
   Keymap xkeymap;
   xkeymap = _rl_keymap;
   _rl_keymap = map;
   rl_bind_keyseq_if_unbound (_rl_term_ku, rl_get_previous_history);
   rl_bind_keyseq_if_unbound (_rl_term_kd, rl_get_next_history);
   rl_bind_keyseq_if_unbound (_rl_term_kr, rl_forward_char);
   rl_bind_keyseq_if_unbound (_rl_term_kl, rl_backward_char);
   rl_bind_keyseq_if_unbound (_rl_term_kh, rl_beg_of_line);  /* Home */
   rl_bind_keyseq_if_unbound (_rl_term_at7, rl_end_of_line); /* End */
   rl_bind_keyseq_if_unbound (_rl_term_kD, rl_delete);
   rl_bind_keyseq_if_unbound (_rl_term_kI, rl_overwrite_mode);   /* Insert */
   rl_bind_keyseq_if_unbound (_rl_term_kN, rl_history_search_forward);   /* Page Down */
   rl_bind_keyseq_if_unbound (_rl_term_kP, rl_history_search_backward);  /* Page Up */
   _rl_keymap = xkeymap;
 }
References _rl_keymap, _rl_term_at7, _rl_term_kd, _rl_term_kD, _rl_term_kh, _rl_term_kI, _rl_term_kl, _rl_term_kN, _rl_term_kP, _rl_term_kr, _rl_term_ku, map, rl_backward_char(), rl_beg_of_line(), rl_bind_keyseq_if_unbound(), rl_delete(), rl_end_of_line(), rl_forward_char(), rl_get_next_history(), rl_get_previous_history(), rl_history_search_backward(), rl_history_search_forward(), and rl_overwrite_mode().
Referenced by _rl_init_terminal_io().
get_term_capabilities()
static void get_term_capabilities (char ** bp) static
Definition at line 458 of file terminal.c.
 {
 #if !defined (__DJGPP__)    /* XXX - doesn't DJGPP have a termcap library? */
   register int i;
   for (i = 0; i < NUM_TC_STRINGS; i++)
     *(tc_strings[i].tc_value) = tgetstr ((char *)tc_strings[i].tc_var, bp);
 #endif
   tcap_initialized = 1;
 }
References bp, i, NUM_TC_STRINGS, tc_strings, _tc_string::tc_value, _tc_string::tc_var, tcap_initialized, and tgetstr().
Referenced by _rl_init_terminal_io().
rl_crlf()
int rl_crlf (void)
Definition at line 734 of file terminal.c.
 {
 #if defined (NEW_TTY_DRIVER) || defined (__MINT__)
   if (_rl_term_cr)
     tputs (_rl_term_cr, 1, _rl_output_character_function);
 #endif /* NEW_TTY_DRIVER || __MINT__ */
   putc ('\n', _rl_out_stream);
   return 0;
 }
References _rl_out_stream, _rl_output_character_function(), _rl_term_cr, putc, and tputs().
Referenced by _rl_clear_screen(), _rl_redisplay_after_sigwinch(), _rl_update_final(), crlf(), display_matches(), rl_display_match_list(), and rl_print_last_kbd_macro().
rl_ding()
int rl_ding (void)
Definition at line 756 of file terminal.c.
 {
   if (_rl_echoing_p)
     {
       switch (_rl_bell_preference)
         {
     case NO_BELL:
     default:
       break;
     case VISIBLE_BELL:
       if (_rl_visible_bell)
         {
 #ifdef __DJGPP__
           ScreenVisualBell ();
 #else
           tputs (_rl_visible_bell, 1, _rl_output_character_function);
 #endif
           break;
         }
       /* FALLTHROUGH */
     case AUDIBLE_BELL:
       fprintf (stderr, "\007");
       fflush (stderr);
       break;
         }
       return (0);
     }
   return (-1);
 }
References _rl_bell_preference, _rl_echoing_p, _rl_output_character_function(), _rl_visible_bell, AUDIBLE_BELL, fflush(), fprintf(), NO_BELL, stderr, tputs(), and VISIBLE_BELL.
Referenced by _rl_abort_internal(), _rl_arg_overflow(), _rl_char_search_internal(), _rl_dispatch_subseq(), _rl_isearch_dispatch(), _rl_nsearch_dispatch(), _rl_nsearch_dosearch(), _rl_overwrite_rubout(), _rl_rubout_char(), _rl_vi_goto_mark(), _rl_vi_set_mark(), ding(), get_y_or_n(), noninc_dosearch(), rl_arrow_keys(), rl_backward_byte(), rl_backward_kill_line(), rl_call_last_kbd_macro(), rl_change_case(), rl_complete_internal(), rl_delete(), rl_discard_argument(), rl_do_undo(), rl_exchange_point_and_mark(), rl_fetch_history(), rl_forward_byte(), rl_get_previous_history(), rl_history_search_internal(), rl_maybe_unsave_line(), rl_menu_complete(), rl_noninc_forward_search_again(), rl_noninc_reverse_search_again(), rl_old_menu_complete(), rl_print_last_kbd_macro(), rl_revert_line(), rl_rubout(), rl_transpose_chars(), rl_transpose_words(), rl_tty_status(), rl_undo_command(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_change_to(), rl_vi_delete(), rl_vi_delete_to(), rl_vi_end_word(), rl_vi_match(), rl_vi_next_word(), rl_vi_overstrike_delete(), rl_vi_prev_word(), rl_vi_redo(), rl_vi_rubout(), rl_vi_search(), rl_vi_unix_word_rubout(), rl_vi_yank_to(), and rl_yank_nth_arg_internal().
rl_get_screen_size()
void rl_get_screen_size (int * rows, int * cols)
Definition at line 371 of file terminal.c.
 {
   if (rows)
     *rows = _rl_screenheight;
   if (cols)
     *cols = _rl_screenwidth;
 }
References _rl_screenheight, _rl_screenwidth, cols, and rows.
rl_get_termcap()
char* rl_get_termcap (const char * cap)
Definition at line 669 of file terminal.c.
 {
   register int i;
   if (tcap_initialized == 0)
     return ((char *)NULL);
   for (i = 0; i < NUM_TC_STRINGS; i++)
     {
       if (tc_strings[i].tc_var[0] == cap[0] && strcmp (tc_strings[i].tc_var, cap) == 0)
         return *(tc_strings[i].tc_value);
     }
   return ((char *)NULL);
 }
References i, NULL, NUM_TC_STRINGS, strcmp, tc_strings, _tc_string::tc_value, _tc_string::tc_var, and tcap_initialized.
rl_reset_screen_size()
void rl_reset_screen_size (void)
Definition at line 380 of file terminal.c.
 {
   _rl_get_screen_size (fileno (rl_instream), 0);
 }
References _rl_get_screen_size(), fileno(), and rl_instream.
rl_reset_terminal()
int rl_reset_terminal (const char * terminal_name)
Definition at line 686 of file terminal.c.
 {
   _rl_screenwidth = _rl_screenheight = 0;
   _rl_init_terminal_io (terminal_name);
   return 0;
 }
References _rl_init_terminal_io(), _rl_screenheight, and _rl_screenwidth.
rl_resize_terminal()
void rl_resize_terminal (void)
Definition at line 392 of file terminal.c.
 {
   int width, height;
   width = _rl_screenwidth;
   height = _rl_screenheight;
   _rl_get_screen_size (fileno (rl_instream), 1);
   if (_rl_echoing_p && (width != _rl_screenwidth || height != _rl_screenheight))
     {
       if (CUSTOM_REDISPLAY_FUNC ())
     rl_forced_update_display ();
       else if (RL_ISSTATE(RL_STATE_REDISPLAYING) == 0)
     _rl_redisplay_after_sigwinch ();
     }
 }
References _rl_echoing_p, _rl_get_screen_size(), _rl_redisplay_after_sigwinch(), _rl_screenheight, _rl_screenwidth, CUSTOM_REDISPLAY_FUNC, fileno(), height(), rl_forced_update_display(), rl_instream, RL_ISSTATE, RL_STATE_REDISPLAYING, and width.
Referenced by _rl_signal_handler(), and main().
rl_set_screen_size()
void rl_set_screen_size (int rows, int cols)
Definition at line 365 of file terminal.c.
 {
   _rl_set_screen_size (rows, cols);
 }
References _rl_set_screen_size(), cols, and rows.
Referenced by get_new_window_size().
Variable Documentation
_rl_active_region_end_color
char* _rl_active_region_end_color = NULL
Definition at line 191 of file terminal.c.
Referenced by _rl_region_color_off(), _rl_region_color_on(), and _rl_reset_region_color().
_rl_active_region_start_color
char* _rl_active_region_start_color = NULL
Definition at line 190 of file terminal.c.
Referenced by _rl_region_color_off(), _rl_region_color_on(), and _rl_reset_region_color().
_rl_enable_keypad
int _rl_enable_keypad
Definition at line 212 of file terminal.c.
Referenced by rl_deprep_terminal(), and rl_prep_terminal().
_rl_enable_meta
int _rl_enable_meta = 1
Definition at line 215 of file terminal.c.
Referenced by readline_internal_setup().
_rl_screenchars
int _rl_screenchars
Definition at line 209 of file terminal.c.
Referenced by _rl_get_screen_size(), _rl_init_terminal_io(), _rl_set_screen_size(), readline_initialize_everything(), and rl_redisplay().
_rl_screenheight
int _rl_screenheight
Definition at line 209 of file terminal.c.
Referenced by _rl_get_screen_size(), _rl_init_terminal_io(), _rl_move_vert(), _rl_set_screen_size(), readline_initialize_everything(), rl_display_match_list(), rl_get_screen_size(), rl_redisplay(), rl_reset_terminal(), and rl_resize_terminal().
_rl_screenwidth
int _rl_screenwidth
Definition at line 209 of file terminal.c.
Referenced by _rl_current_display_line(), _rl_get_screen_size(), _rl_init_terminal_io(), _rl_move_cursor_relative(), _rl_redisplay_after_sigwinch(), _rl_set_screen_size(), _rl_update_final(), complete_get_screenwidth(), delete_chars(), expand_prompt(), readline_initialize_everything(), realloc_line(), rl_clear_visible_line(), rl_display_match_list(), rl_get_screen_size(), rl_next_screen_line(), rl_on_new_line_with_prompt(), rl_previous_screen_line(), rl_redisplay(), rl_reset_terminal(), rl_resize_terminal(), and update_line().
_rl_term_at7
char* _rl_term_at7 static
Definition at line 172 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_autowrap
int _rl_term_autowrap = -1
Definition at line 145 of file terminal.c.
Referenced by _rl_get_screen_size(), _rl_init_terminal_io(), _rl_move_cursor_relative(), _rl_set_screen_size(), _rl_update_final(), readline_initialize_everything(), rl_next_screen_line(), rl_on_new_line_with_prompt(), rl_previous_screen_line(), and update_line().
_rl_term_backspace
char* _rl_term_backspace
Definition at line 117 of file terminal.c.
Referenced by _rl_backspace(), and _rl_init_terminal_io().
_rl_term_clreol
char* _rl_term_clreol
Definition at line 113 of file terminal.c.
Referenced by _rl_clear_to_eol(), and _rl_init_terminal_io().
_rl_term_clrpag
char* _rl_term_clrpag
Definition at line 114 of file terminal.c.
Referenced by _rl_clear_screen(), and _rl_init_terminal_io().
_rl_term_clrscroll
char* _rl_term_clrscroll
Definition at line 115 of file terminal.c.
Referenced by _rl_clear_screen(), and _rl_init_terminal_io().
_rl_term_cr
char* _rl_term_cr
Definition at line 116 of file terminal.c.
Referenced by _rl_cr(), _rl_init_terminal_io(), _rl_redisplay_after_sigwinch(), rl_crlf(), and update_line().
_rl_term_dc
char* _rl_term_dc
Definition at line 132 of file terminal.c.
Referenced by _rl_init_terminal_io(), delete_chars(), and update_line().
_rl_term_DC
char* _rl_term_DC
Definition at line 133 of file terminal.c.
Referenced by _rl_init_terminal_io(), and delete_chars().
_rl_term_ei
char* _rl_term_ei
Definition at line 126 of file terminal.c.
Referenced by _rl_init_terminal_io(), and open_some_spaces().
_rl_term_forward_char
char* _rl_term_forward_char
Definition at line 136 of file terminal.c.
Referenced by _rl_init_terminal_io(), and _rl_move_cursor_relative().
_rl_term_goto
char* _rl_term_goto
Definition at line 118 of file terminal.c.
Referenced by _rl_init_terminal_io().
_rl_term_ic
char* _rl_term_ic
Definition at line 127 of file terminal.c.
Referenced by _rl_init_terminal_io(), and open_some_spaces().
_rl_term_IC
char* _rl_term_IC
Definition at line 129 of file terminal.c.
Referenced by _rl_init_terminal_io(), open_some_spaces(), and update_line().
_rl_term_im
char* _rl_term_im
Definition at line 125 of file terminal.c.
Referenced by _rl_init_terminal_io(), and open_some_spaces().
_rl_term_ip
char* _rl_term_ip
Definition at line 128 of file terminal.c.
Referenced by _rl_init_terminal_io().
_rl_term_kd
char* _rl_term_kd static
Definition at line 161 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_kD
char* _rl_term_kD static
Definition at line 175 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_ke
char* _rl_term_ke static
Definition at line 167 of file terminal.c.
Referenced by _rl_control_keypad(), and _rl_init_terminal_io().
_rl_term_kh
char* _rl_term_kh static
Definition at line 170 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_kH
char* _rl_term_kH static
Definition at line 171 of file terminal.c.
Referenced by _rl_init_terminal_io().
_rl_term_kI
char* _rl_term_kI static
Definition at line 178 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_kl
char* _rl_term_kl static
Definition at line 163 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_kN
char* _rl_term_kN static
Definition at line 182 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_kP
char* _rl_term_kP static
Definition at line 181 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_kr
char* _rl_term_kr static
Definition at line 162 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_ks
char* _rl_term_ks static
Definition at line 166 of file terminal.c.
Referenced by _rl_control_keypad(), and _rl_init_terminal_io().
_rl_term_ku
char* _rl_term_ku static
Definition at line 160 of file terminal.c.
Referenced by _rl_init_terminal_io(), and bind_termcap_arrow_keys().
_rl_term_mm
char* _rl_term_mm static
Definition at line 152 of file terminal.c.
Referenced by _rl_enable_meta_key(), and _rl_init_terminal_io().
_rl_term_mo
char* _rl_term_mo static
Definition at line 153 of file terminal.c.
Referenced by _rl_disable_meta_key(), and _rl_init_terminal_io().
_rl_term_pc
char* _rl_term_pc
Definition at line 119 of file terminal.c.
Referenced by _rl_init_terminal_io().
_rl_term_se
char* _rl_term_se static
Definition at line 157 of file terminal.c.
Referenced by _rl_init_terminal_io(), _rl_standout_off(), and _rl_standout_on().
_rl_term_so
char* _rl_term_so static
Definition at line 156 of file terminal.c.
Referenced by _rl_init_terminal_io(), _rl_standout_off(), and _rl_standout_on().
_rl_term_up
char* _rl_term_up
Definition at line 139 of file terminal.c.
Referenced by _rl_init_terminal_io(), _rl_move_vert(), and rl_redisplay().
_rl_term_ve
char* _rl_term_ve static
Definition at line 186 of file terminal.c.
Referenced by _rl_init_terminal_io(), and _rl_set_cursor().
_rl_term_vs
char* _rl_term_vs static
Definition at line 185 of file terminal.c.
Referenced by _rl_init_terminal_io(), and _rl_set_cursor().
_rl_terminal_can_insert
int _rl_terminal_can_insert = 0
Definition at line 122 of file terminal.c.
Referenced by _rl_init_terminal_io(), and update_line().
_rl_visible_bell
char* _rl_visible_bell static
Definition at line 142 of file terminal.c.
Referenced by _rl_init_terminal_io(), and rl_ding().
BC
char * BC
Definition at line 109 of file terminal.c.
Referenced by _rl_init_terminal_io().
enabled_meta
int enabled_meta = 0 static
Definition at line 877 of file terminal.c.
Referenced by _rl_disable_meta_key(), and _rl_enable_meta_key().
PC
char PC
Definition at line 109 of file terminal.c.
Referenced by _rl_init_terminal_io().
rl_change_environment
int rl_change_environment = 1
Definition at line 90 of file terminal.c.
Referenced by _rl_get_screen_size().
rl_prefer_env_winsize
int rl_prefer_env_winsize = 0
Definition at line 86 of file terminal.c.
Referenced by _rl_get_screen_size(), and initialize_shell_variables().
tc_strings
const struct _tc_string tc_strings[] static
Definition at line 392 of file terminal.c.
Referenced by get_term_capabilities(), and rl_get_termcap().
tcap_initialized
int tcap_initialized static
Definition at line 103 of file terminal.c.
Referenced by get_term_capabilities(), and rl_get_termcap().
term_buffer
char* term_buffer = (char *)NULL static
Definition at line 99 of file terminal.c.
Referenced by _rl_init_terminal_io().
term_has_meta
int term_has_meta static
Definition at line 148 of file terminal.c.
Referenced by _rl_disable_meta_key(), _rl_enable_meta_key(), and _rl_init_terminal_io().
term_string_buffer
char* term_string_buffer = (char *)NULL static
Definition at line 100 of file terminal.c.
Referenced by _rl_get_screen_size(), and _rl_init_terminal_io().
UP
char * UP
Definition at line 109 of file terminal.c.
Referenced by _rl_init_terminal_io().