Fennix: Userspace/apps/base/busybox/libbb/appletlib.c File Reference
appletlib.c File Reference
#include <errno.h>
#include "busybox.h"
#include <malloc.h>
#include "applets.h"
#include "applet_tables.h"
#include "usage_compressed.h"
Macros
#define PROTOTYPES
#define NUM_SCRIPTS 0
#define ENABLE_FEATURE_COMPRESS_USAGE 0
#define usage_messages 0
#define unpack_usage_messages() usage_messages
#define dealloc_usage_messages(s) ((void)(s))
#define check_suid(x) ((void)0)
Functions
static int * get_perrno (void)
unsigned FAST_FUNC string_array_len (char **argv)
void FAST_FUNC bb_show_usage (void)
int FAST_FUNC find_applet_by_name (const char *name)
void lbb_prepare (const char *applet IF_FEATURE_INDIVIDUAL(, char **argv)) MAIN_EXTERNALLY_VISIBLE
IF_FEATURE_SUID (static uid_t ruid;)
int main (int argc UNUSED_PARAM, char **argv)
Variables
const char * applet_name
bool re_execed
Macro Definition Documentation
check_suid
#define check_suid (x) ((void)0)
Definition at line 646 of file appletlib.c.
dealloc_usage_messages
#define dealloc_usage_messages (s) ((void)(s))
Definition at line 122 of file appletlib.c.
ENABLE_FEATURE_COMPRESS_USAGE
#define ENABLE_FEATURE_COMPRESS_USAGE 0
Definition at line 90 of file appletlib.c.
NUM_SCRIPTS
#define NUM_SCRIPTS 0
Definition at line 62 of file appletlib.c.
PROTOTYPES
#define PROTOTYPES
Definition at line 42 of file appletlib.c.
unpack_usage_messages
#define unpack_usage_messages () usage_messages
Definition at line 121 of file appletlib.c.
usage_messages
#define usage_messages 0
Definition at line 108 of file appletlib.c.
Function Documentation
bb_show_usage()
void FAST_FUNC bb_show_usage (void)
Definition at line 127 of file appletlib.c.
 {
     if (ENABLE_SHOW_USAGE) {
 #ifdef SINGLE_APPLET_STR
         /* Imagine that this applet is "true". Dont link in printf! */
         const char *usage_string = unpack_usage_messages();
         if (usage_string) {
             if (*usage_string == '\b') {
                 full_write2_str("No help available\n");
             } else {
                 full_write2_str("Usage: "SINGLE_APPLET_STR" ");
                 full_write2_str(usage_string);
                 full_write2_str("\n");
             }
             if (ENABLE_FEATURE_CLEAN_UP)
                 dealloc_usage_messages((char*)usage_string);
         }
 #else
         const char *p;
         const char *usage_string = p = unpack_usage_messages();
         int ap = find_applet_by_name(applet_name);
         if (ap < 0 || usage_string == NULL)
             xfunc_die();
         while (ap) {
             while (*p++) continue;
             ap--;
         }
         full_write2_str(bb_banner);
         full_write2_str(" multi-call binary.\n"); /* common string */
         if (*p == '\b')
             full_write2_str("\nNo help available\n");
         else {
             full_write2_str("\nUsage: ");
             full_write2_str(applet_name);
             if (p[0]) {
                 if (p[0] != '\n')
                     full_write2_str(" ");
                 full_write2_str(p);
             }
             full_write2_str("\n");
         }
         if (ENABLE_FEATURE_CLEAN_UP)
             dealloc_usage_messages((char*)usage_string);
 #endif
     }
     xfunc_die();
 }
References ap, applet_name, dealloc_usage_messages, find_applet_by_name(), full_write2_str(), NULL, p, unpack_usage_messages, and xfunc_die().
Referenced by lbb_prepare().
find_applet_by_name()
int FAST_FUNC find_applet_by_name (const char * name)
Definition at line 177 of file appletlib.c.
 {
     unsigned i;
     int j;
     const char *p;
 /* The commented-out word-at-a-time code is ~40% faster, but +160 bytes.
  * "Faster" here saves ~0.5 microsecond of real time - not worth it.
  */
 #if 0 /*BB_UNALIGNED_MEMACCESS_OK && BB_LITTLE_ENDIAN*/
     uint32_t n32;
     /* Handle all names < 2 chars long early */
     if (name[0] == '\0')
         return -1; /* "" is not a valid applet name */
     if (name[1] == '\0') {
         if (!ENABLE_TEST)
             return -1; /* 1-char name is not valid */
         if (name[0] != ']')
             return -1; /* 1-char name which isn't "[" is not valid */
         /* applet "[" is always applet #0: */
         return 0;
     }
 #endif
     p = applet_names;
 #if KNOWN_APPNAME_OFFSETS <= 0
     i = 0;
 #else
     i = NUM_APPLETS * (KNOWN_APPNAME_OFFSETS - 1);
     for (j = ARRAY_SIZE(applet_nameofs)-1; j >= 0; j--) {
         const char *pp = applet_names + applet_nameofs[j];
         if (strcmp(name, pp) >= 0) {
             //bb_error_msg("name:'%s' >= pp:'%s'", name, pp);
             p = pp;
             break;
         }
         i -= NUM_APPLETS;
     }
     i /= (unsigned)KNOWN_APPNAME_OFFSETS;
     //bb_error_msg("name:'%s' starting from:'%s' i:%u", name, p, i);
 #endif
     /* Open-coded linear search without strcmp/strlen calls for speed */
     while (*p) {
         /* Do we see "name\0" at current position in applet_names? */
         for (j = 0; *p == name[j]; ++j) {
             if (*p++ == '\0') {
                 //bb_error_msg("found:'%s' i:%u", name, i);
                 return i; /* yes */
             }
         }
         /* No. Have we gone too far, alphabetically? */
         if (*p > name[j]) {
             //bb_error_msg("break:'%s' i:%u", name, i);
             break;
         }
         /* No. Move to the start of the next applet name. */
         while (*p++ != '\0')
             continue;
         i++;
     }
     return -1;
 }
References ARRAY_SIZE, i, j, NUM_APPLETS, p, and strcmp.
Referenced by bb_show_usage(), find_command(), pseudo_exec_argv(), run_pipe(), shellexec(), and spawn_and_wait().
get_perrno()
static int* get_perrno (void) inline static
Definition at line 31 of file appletlib.c.
 { return &errno; }
References errno.
Referenced by lbb_prepare().
IF_FEATURE_SUID()
IF_FEATURE_SUID (static uid_t ruid;)
Definition at line 295 of file appletlib.c.
{
     /* next ptr must be first: this struct needs to be llist-compatible */
     struct suid_config_t *m_next;
     struct bb_uidgid_t m_ugid;
     int m_applet;
     mode_t m_mode;
 } *suid_config;
 static bool suid_cfg_readable;
 /* libbb candidate */
 static char *get_trimmed_slice(char *s, char *e)
 {
     /* First, consider the value at e to be nul and back up until we
      * reach a non-space char.  Set the char after that (possibly at
      * the original e) to nul. */
     while (e-- > s) {
         if (!isspace(*e)) {
             break;
         }
     }
     e[1] = '\0';
     /* Next, advance past all leading space and return a ptr to the
      * first non-space char; possibly the terminating nul. */
     return skip_whitespace(s);
 }
 static void parse_config_file(void)
 {
     /* Don't depend on the tools to combine strings. */
     static const char config_file[] ALIGN1 = "/etc/busybox.conf";
     struct suid_config_t *sct_head;
     int applet_no;
     FILE *f;
     const char *errmsg;
     unsigned lc;
     smallint section;
     struct stat st;
     ruid = getuid();
     if (ruid == 0) /* run by root - don't need to even read config file */
         return;
     if ((stat(config_file, &st) != 0)       /* No config file? */
      || !S_ISREG(st.st_mode)                /* Not a regular file? */
      || (st.st_uid != 0)                    /* Not owned by root? */
      || (st.st_mode & (S_IWGRP | S_IWOTH))  /* Writable by non-root? */
      || !(f = fopen_for_read(config_file))  /* Cannot open? */
     ) {
         return;
     }
     suid_cfg_readable = 1;
     sct_head = NULL;
     section = lc = 0;
     while (1) {
         char buffer[256];
         char *s;
         if (!fgets(buffer, sizeof(buffer), f)) { /* Are we done? */
             // Looks like bloat
             //if (ferror(f)) {   /* Make sure it wasn't a read error. */
             //  errmsg = "reading";
             //  goto pe_label;
             //}
             fclose(f);
             suid_config = sct_head; /* Success, so set the pointer. */
             return;
         }
         s = buffer;
         lc++;                   /* Got a (partial) line. */
         /* If a line is too long for our buffer, we consider it an error.
          * The following test does mistreat one corner case though.
          * If the final line of the file does not end with a newline and
          * yet exactly fills the buffer, it will be treated as too long
          * even though there isn't really a problem.  But it isn't really
          * worth adding code to deal with such an unlikely situation, and
          * we do err on the side of caution.  Besides, the line would be
          * too long if it did end with a newline. */
         if (!strchr(s, '\n') && !feof(f)) {
             errmsg = "line too long";
             goto pe_label;
         }
         /* Trim leading and trailing whitespace, ignoring comments, and
          * check if the resulting string is empty. */
         s = get_trimmed_slice(s, strchrnul(s, '#'));
         if (!*s) {
             continue;
         }
         /* Check for a section header. */
         if (*s == '[') {
             /* Unlike the old code, we ignore leading and trailing
              * whitespace for the section name.  We also require that
              * there are no stray characters after the closing bracket. */
             char *e = strchr(s, ']');
             if (!e   /* Missing right bracket? */
              || e[1] /* Trailing characters? */
              || !*(s = get_trimmed_slice(s+1, e)) /* Missing name? */
             ) {
                 errmsg = "section header";
                 goto pe_label;
             }
             /* Right now we only have one section so just check it.
              * If more sections are added in the future, please don't
              * resort to cascading ifs with multiple strcasecmp calls.
              * That kind of bloated code is all too common.  A loop
              * and a string table would be a better choice unless the
              * number of sections is very small. */
             if (strcasecmp(s, "SUID") == 0) {
                 section = 1;
                 continue;
             }
             section = -1;   /* Unknown section so set to skip. */
             continue;
         }
         /* Process sections. */
         if (section == 1) {     /* SUID */
             /* Since we trimmed leading and trailing space above, we're
              * now looking for strings of the form
              *    <key>[::space::]*=[::space::]*<value>
              * where both key and value could contain inner whitespace. */
             /* First get the key (an applet name in our case). */
             char *e = strchr(s, '=');
             if (e) {
                 s = get_trimmed_slice(s, e);
             }
             if (!e || !*s) {    /* Missing '=' or empty key. */
                 errmsg = "keyword";
                 goto pe_label;
             }
             /* Ok, we have an applet name.  Process the rhs if this
              * applet is currently built in and ignore it otherwise.
              * Note: this can hide config file bugs which only pop
              * up when the busybox configuration is changed. */
             applet_no = find_applet_by_name(s);
             if (applet_no >= 0) {
                 unsigned i;
                 struct suid_config_t *sct;
                 /* Note: We currently don't check for duplicates!
                  * The last config line for each applet will be the
                  * one used since we insert at the head of the list.
                  * I suppose this could be considered a feature. */
                 sct = xzalloc(sizeof(*sct));
                 sct->m_applet = applet_no;
                 /*sct->m_mode = 0;*/
                 sct->m_next = sct_head;
                 sct_head = sct;
                 /* Get the specified mode. */
                 e = skip_whitespace(e+1);
                 for (i = 0; i < 3; i++) {
                     /* There are 4 chars for each of user/group/other.
                      * "x-xx" instead of "x-" are to make
                      * "idx > 3" check catch invalid chars.
                      */
                     static const char mode_chars[] ALIGN1 = "Ssx-" "Ssx-" "x-xx";
                     static const unsigned short mode_mask[] ALIGN2 = {
                         S_ISUID, S_ISUID|S_IXUSR, S_IXUSR, 0, /* Ssx- */
                         S_ISGID, S_ISGID|S_IXGRP, S_IXGRP, 0, /* Ssx- */
                                                   S_IXOTH, 0  /*   x- */
                     };
                     const char *q = strchrnul(mode_chars + 4*i, *e);
                     unsigned idx = q - (mode_chars + 4*i);
                     if (idx > 3) {
                         errmsg = "mode";
                         goto pe_label;
                     }
                     sct->m_mode |= mode_mask[q - mode_chars];
                     e++;
                 }
                 /* Now get the user/group info. */
                 s = skip_whitespace(e);
                 /* Default is 0.0, else parse USER.GROUP: */
                 if (*s) {
                     /* We require whitespace between mode and USER.GROUP */
                     if ((s == e) || !(e = strchr(s, '.'))) {
                         errmsg = "uid.gid";
                         goto pe_label;
                     }
                     *e = ':'; /* get_uidgid needs USER:GROUP syntax */
                     if (get_uidgid(&sct->m_ugid, s) == 0) {
                         errmsg = "unknown user/group";
                         goto pe_label;
                     }
                 }
             }
             continue;
         }
         /* Unknown sections are ignored. */
         /* Encountering configuration lines prior to seeing a
          * section header is treated as an error.  This is how
          * the old code worked, but it may not be desirable.
          * We may want to simply ignore such lines in case they
          * are used in some future version of busybox. */
         if (!section) {
             errmsg = "keyword outside section";
             goto pe_label;
         }
     } /* while (1) */
  pe_label:
     fclose(f);
     bb_error_msg("parse error in %s, line %u: %s", config_file, lc, errmsg);
     /* Release any allocated memory before returning. */
     llist_free((llist_t*)sct_head, NULL);
 }
 # else
 static inline void parse_config_file(void)
 {
     IF_FEATURE_SUID(ruid = getuid();)
 }
References mode_t.
lbb_prepare()
void lbb_prepare (const char *applet IF_FEATURE_INDIVIDUAL, char **argv)
Definition at line 246 of file appletlib.c.
 {
 #ifdef bb_cached_errno_ptr
     ASSIGN_CONST_PTR(&bb_errno, get_perrno());
 #endif
     applet_name = applet;
     if (ENABLE_LOCALE_SUPPORT)
         setlocale(LC_ALL, "");
 #if ENABLE_FEATURE_INDIVIDUAL
     /* Redundant for busybox (run_applet_and_exit covers that case)
      * but needed for "individual applet" mode */
     if (argv[1]
      && strcmp(argv[1], "--help") == 0
      && !is_prefixed_with(applet, "busybox")
     ) {
         /* Special cases. POSIX says "test --help"
          * should be no different from e.g. "test --foo".
          */
         if (!(ENABLE_TEST && strcmp(applet_name, "test") == 0)
          && !(ENABLE_TRUE && strcmp(applet_name, "true") == 0)
          && !(ENABLE_FALSE && strcmp(applet_name, "false") == 0)
          && !(ENABLE_ECHO && strcmp(applet_name, "echo") == 0)
         )
             bb_show_usage();
     }
 #endif
 }
References applet_name, argv, ASSIGN_CONST_PTR, bb_show_usage(), get_perrno(), is_prefixed_with(), LC_ALL, setlocale, and strcmp.
Referenced by main().
main()
int main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1032 of file appletlib.c.
 {
 #if 0
     /* TODO: find a use for a block of memory between end of .bss
      * and end of page. For example, I'm getting "_end:0x812e698 2408 bytes"
      * - more than 2k of wasted memory (in this particular build)
      * *per each running process*!
      * (If your linker does not generate "_end" name, weak attribute
      * makes &_end == NULL, end_len == 0 here.)
      */
     extern char _end[] __attribute__((weak));
     unsigned end_len = (-(int)_end) & 0xfff;
     printf("_end:%p %u bytes\n", &_end, end_len);
 #endif
     /* Tweak malloc for reduced memory consumption */
 #ifdef M_TRIM_THRESHOLD
     /* M_TRIM_THRESHOLD is the maximum amount of freed top-most memory
      * to keep before releasing to the OS
      * Default is way too big: 256k
      */
     mallopt(M_TRIM_THRESHOLD, 8 * 1024);
 #endif
 #ifdef M_MMAP_THRESHOLD
     /* M_MMAP_THRESHOLD is the request size threshold for using mmap()
      * Default is too big: 256k
      */
     mallopt(M_MMAP_THRESHOLD, 32 * 1024 - 256);
 #endif
 #if 0 /*def M_TOP_PAD*/
     /* When the program break is increased, then M_TOP_PAD bytes are added
      * to the sbrk(2) request. When the heap is trimmed because of free(3),
      * this much free space is preserved at the top of the heap.
      * glibc default seems to be way too big: 128k, but need to verify.
      */
     mallopt(M_TOP_PAD, 8 * 1024);
 #endif
 #if !BB_MMU
     /* NOMMU re-exec trick sets high-order bit in first byte of name */
     if (argv[0][0] & 0x80) {
         re_execed = 1;
         argv[0][0] &= 0x7f;
     }
 #endif
 #if defined(SINGLE_APPLET_MAIN)
     /* Only one applet is selected in .config */
     if (argv[1] && is_prefixed_with(argv[0], "busybox")) {
         /* "busybox <applet> <params>" should still work as expected */
         argv++;
     }
     /* applet_names in this case is just "applet\0\0" */
     lbb_prepare(applet_names IF_FEATURE_INDIVIDUAL(, argv));
 # if ENABLE_BUILD_LIBBUSYBOX
     return SINGLE_APPLET_MAIN(string_array_len(argv), argv);
 # else
     return SINGLE_APPLET_MAIN(argc, argv);
 # endif
 #elif !ENABLE_BUSYBOX && NUM_APPLETS == 0
     full_write2_str(bb_basename(argv[0]));
     full_write2_str(": no applets enabled\n");
     return 127;
 #else
     lbb_prepare("busybox" IF_FEATURE_INDIVIDUAL(, argv));
 # if !ENABLE_BUSYBOX
     if (argv[1] && is_prefixed_with(bb_basename(argv[0]), "busybox"))
         argv++;
 # endif
     applet_name = argv[0];
     if (applet_name[0] == '-')
         applet_name++;
     applet_name = bb_basename(applet_name);
     /* If we are a result of execv("/proc/self/exe"), fix ugly comm of "exe" */
     if (ENABLE_FEATURE_SH_STANDALONE
      || ENABLE_FEATURE_PREFER_APPLETS
      || !BB_MMU
     ) {
         if (NUM_APPLETS > 1) {
             /* Careful, do not trash comm of "SCRIPT.sh" -
              * the case when started from e.g. #!/bin/ash script.
              * (not limited to shells - #!/bin/awk scripts also exist)
              */
             if (re_execed_comm())
                 set_task_comm(applet_name);
         }
     }
     parse_config_file(); /* ...maybe, if FEATURE_SUID_CONFIG */
     run_applet_and_exit(applet_name, argv);
 #endif
 }
References __attribute__, applet_name, argc, argv, bb_basename(), BB_MMU, full_write2_str(), is_prefixed_with(), lbb_prepare(), NUM_APPLETS, parse_config_file(), printf, re_execed, re_execed_comm, set_task_comm, string_array_len(), and weak.
string_array_len()
unsigned FAST_FUNC string_array_len (char ** argv)
Definition at line 94 of file appletlib.c.
 {
     char **start = argv;
     while (*argv)
         argv++;
     return argv - start;
 }
References argv, and start.
Referenced by hush_main(), main(), save_and_replace_G_args(), shell_builtin_ulimit(), and vgetopt32().
Variable Documentation
applet_name
const char* applet_name
Definition at line 286 of file appletlib.c.
Referenced by bb_show_usage(), lbb_prepare(), and main().
re_execed
bool re_execed
Definition at line 288 of file appletlib.c.
Referenced by main().