Fennix: Userspace/musl/src/include/string.h File Reference
string.h File Reference
#include "../../include/string.h"
Functions
hidden void * __memrchr (const void *, int, size_t)
hidden char * __stpcpy (char *, const char *)
hidden char * __stpncpy (char *, const char *, size_t)
hidden char * __strchrnul (const char *, int)
Function Documentation
__memrchr()
hidden void* __memrchr (const void * m, int c, size_t n)
Definition at line 3 of file memrchr.c.
 {
     const unsigned char *s = m;
     c = (unsigned char)c;
     while (n--) if (s[n]==c) return (void *)(s+n);
     return 0;
 }
References c, n, and s.
Referenced by strrchr().
__stpcpy()
hidden char* __stpcpy (char * , const char *)
Referenced by strcpy().
__stpncpy()
hidden char* __stpncpy (char * , const char * , size_t)
Referenced by strncpy().
__strchrnul()
hidden char* __strchrnul (const char * s, int c)
Definition at line 10 of file strchrnul.c.
 {
     c = (unsigned char)c;
     if (!c) return (char *)s + strlen(s);
 #ifdef __GNUC__
     typedef size_t __attribute__((__may_alias__)) word;
     const word *w;
     for (; (uintptr_t)s % ALIGN; s++)
         if (!*s || *(unsigned char *)s == c) return (char *)s;
     size_t k = ONES * c;
     for (w = (void *)s; !HASZERO(*w) && !HASZERO(*w^k); w++);
     s = (void *)w;
 #endif
     for (; *s && *(unsigned char *)s != c; s++);
     return (char *)s;
 }
References __attribute__, ALIGN, c, HASZERO, k, ONES, s, strlen, and w.
Referenced by __execvpe(), __get_locale(), __shm_mapname(), catopen(), expand_tilde(), getenv(), putenv(), realpath(), setenv(), setlocale(), strchr(), strcspn(), and unsetenv().