Fennix Userspace: Userspace/apps/base/busybox/coreutils/libcoreutils/getopt_mk_fifo_nod.c File Reference
getopt_mk_fifo_nod.c File Reference
#include "libbb.h"
#include "coreutils.h"
Functions
mode_t FAST_FUNC getopt_mk_fifo_nod (char **argv)
Function Documentation
getopt_mk_fifo_nod()
mode_t FAST_FUNC getopt_mk_fifo_nod (char ** argv)
Definition at line 24 of file getopt_mk_fifo_nod.c.
 {
     mode_t mode = 0666;
     char *smode = NULL;
 #if ENABLE_SELINUX
     security_context_t scontext;
 #endif
     int opt;
     opt = getopt32(argv, "m:" IF_SELINUX("Z:"), &smode IF_SELINUX(,&scontext));
     if (opt & 1) {
         mode = bb_parse_mode(smode, mode);
         if (mode != (mode_t)-1) /* if mode is valid */
             /* make future mknod/mkfifo set mode bits exactly */
             umask(0);
     }
 #if ENABLE_SELINUX
     if (opt & 2) {
         selinux_or_die();
         setfscreatecon_or_die(scontext);
     }
 #endif
     return mode;
 }
References argv, bb_parse_mode(), getopt32(), mode_t, NULL, opt, selinux_or_die(), setfscreatecon_or_die(), and umask().
Referenced by mkfifo_main(), and mknod_main().