Fennix Userspace: Userspace/apps/base/busybox/libbb/printable.c File Reference
printable.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC fputc_printable (int ch, FILE *file)
void FAST_FUNC visible (unsigned ch, char *buf, int flags)
Function Documentation
fputc_printable()
void FAST_FUNC fputc_printable (int ch, FILE * file)
Definition at line 11 of file printable.c.
 {
     if ((ch & (0x80 + PRINTABLE_META)) == (0x80 + PRINTABLE_META)) {
         fputs("M-", file);
         ch &= 0x7f;
     }
     ch = (unsigned char) ch;
     if (ch == 0x9b) {
         /* VT100's CSI, aka Meta-ESC, is not printable on vt-100 */
         ch = '{';
         goto print_caret;
     }
     if (ch < ' ') {
         ch += '@';
         goto print_caret;
     }
     if (ch == 0x7f) {
         ch = '?';
  print_caret:
         fputc('^', file);
     }
     fputc(ch, file);
 }
References fputc, fputs, and PRINTABLE_META.
Referenced by printLines(), and unix_do_one().
visible()
void FAST_FUNC visible (unsigned ch, char * buf, int flags)
Definition at line 35 of file printable.c.
 {
     if (ch == '\t' && !(flags & VISIBLE_SHOW_TABS)) {
         goto raw;
     }
     if (ch == '\n') {
         if (flags & VISIBLE_ENDLINE)
             *buf++ = '$';
     } else {
         if (ch >= 128) {
             ch -= 128;
             *buf++ = 'M';
             *buf++ = '-';
         }
         if (ch < 32 || ch == 127) {
             *buf++ = '^';
             ch ^= 0x40;
         }
     }
  raw:
     *buf++ = ch;
     *buf = '\0';
 }
References buf, flags, VISIBLE_ENDLINE, and VISIBLE_SHOW_TABS.
Referenced by do_display(), menu_is_visible(), and ConfigList::updateMenuList().