Fennix: Userspace/apps/base/bash/lib/sh/mailstat.c File Reference
mailstat.c File Reference
#include <config.h>
#include <stdio.h>
#include <errno.h>
#include <bashtypes.h>
#include <posixstat.h>
#include <posixdir.h>
#include <bashansi.h>
#include <maxpath.h>
Functions
int mailstat (char *path, struct stat *st) const
Function Documentation
mailstat()
int mailstat (char * path, struct stat * st) const
Definition at line 55 of file mailstat.c.
 {
   static struct stat st_new_last, st_ret_last;
   struct stat st_ret, st_tmp;
   DIR *dd;
   struct dirent *fn;
   char dir[PATH_MAX * 2], file[PATH_MAX * 2 + 1];
   int i, l;
   time_t atime, mtime;
   atime = mtime = 0;
   /* First see if it's a directory. */
   if ((i = stat(path, st)) != 0 || S_ISDIR(st->st_mode) == 0)
     return i;
   if (strlen(path) > sizeof(dir) - 5)
     {
 #ifdef ENAMETOOLONG
       errno = ENAMETOOLONG;
 #else
       errno = EINVAL;
 #endif
       return -1;
     }
   st_ret = *st;
   st_ret.st_nlink = 1;
   st_ret.st_size  = 0;
 #ifdef HAVE_STRUCT_STAT_ST_BLOCKS
   st_ret.st_blocks  = 0;
 #else
   st_ret.st_nlink = 0;
 #endif
   st_ret.st_mode  &= ~S_IFDIR;
   st_ret.st_mode  |= S_IFREG;
   /* See if cur/ is present */
   sprintf(dir, "%s/cur", path);
   if (stat(dir, &st_tmp) || S_ISDIR(st_tmp.st_mode) == 0)
     return 0;
   st_ret.st_atime = st_tmp.st_atime;
   /* See if tmp/ is present */
   sprintf(dir, "%s/tmp", path);
   if (stat(dir, &st_tmp) || S_ISDIR(st_tmp.st_mode) == 0)
     return 0;
   st_ret.st_mtime = st_tmp.st_mtime;
   /* And new/ */
   sprintf(dir, "%s/new", path);
   if (stat(dir, &st_tmp) || S_ISDIR(st_tmp.st_mode) == 0)
     return 0;
   st_ret.st_mtime = st_tmp.st_mtime;
   /* Optimization - if new/ didn't change, nothing else did. */
   if (st_tmp.st_dev == st_new_last.st_dev &&
       st_tmp.st_ino == st_new_last.st_ino &&
       st_tmp.st_atime == st_new_last.st_atime &&
       st_tmp.st_mtime == st_new_last.st_mtime)
     {
       *st = st_ret_last;
       return 0;
     }
   st_new_last = st_tmp;
   /* Loop over new/ and cur/ */
   for (i = 0; i < 2; i++)
     {
       sprintf(dir, "%s/%s", path, i ? "cur" : "new");
       sprintf(file, "%s/", dir);
       l = strlen(file);
       if ((dd = opendir(dir)) == NULL)
     return 0;
       while ((fn = readdir(dd)) != NULL)
     {
       if (fn->d_name[0] == '.' || strlen(fn->d_name) + l >= sizeof(file))
         continue;
       strcpy(file + l, fn->d_name);
       if (stat(file, &st_tmp) != 0)
         continue;
       st_ret.st_size += st_tmp.st_size;
 #ifdef HAVE_STRUCT_STAT_ST_BLOCKS
       st_ret.st_blocks++;
 #else
       st_ret.st_nlink++;
 #endif
       if (st_tmp.st_atime != st_tmp.st_mtime && st_tmp.st_atime > atime)
         atime = st_tmp.st_atime;
       if (st_tmp.st_mtime > mtime)
         mtime = st_tmp.st_mtime;
     }
       closedir(dd);
     }
 /*  if (atime) */   /* Set atime even if cur/ is empty */
       st_ret.st_atime = atime;
     if (mtime)
       st_ret.st_mtime = mtime;
     *st = st_ret_last = st_ret;
     return 0;
 }
References atime, closedir(), dirent::d_name, dd, dir, EINVAL, ENAMETOOLONG, errno, i, l, mtime, NULL, opendir(), PATH_MAX, readdir(), S_IFDIR, S_IFREG, S_ISDIR, sprintf(), stat::st_atime, stat::st_blocks, stat::st_dev, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_size, stat(), strcpy, and strlen().
Referenced by add_mail_file(), file_access_date_changed(), file_has_grown(), file_mod_date_changed(), and update_mail_file().