Fennix Userspace: Userspace/apps/base/bash/externs.h File Reference
externs.h File Reference
#include "stdc.h"
Data Structures
struct _list_of_strings
Macros
#define EXP_EXPANDED 0x01
#define FUNC_MULTILINE 0x01
#define FUNC_EXTERNAL 0x02
#define CASE_LOWER 0x0001
#define CASE_UPPER 0x0002
#define CASE_CAPITALIZE 0x0004
#define CASE_UNCAP 0x0008
#define CASE_TOGGLE 0x0010
#define CASE_TOGGLEALL 0x0020
#define CASE_UPFIRST 0x0040
#define CASE_LOWFIRST 0x0080
#define CASE_USEWORDS 0x1000
#define FL_PREFIX 0x01 /* add 0x, 0X, or 0 prefix as appropriate */
#define FL_ADDBASE 0x02 /* add base# prefix to converted value */
#define FL_HEXUPPER 0x04 /* use uppercase when converting to hex */
#define FL_UNSIGNED 0x08 /* don't add any sign */
#define MP_DOTILDE 0x01
#define MP_DOCWD 0x02
#define MP_RMDOT 0x04
#define MP_IGNDOT 0x08
#define PATH_CHECKDOTDOT 0x0001
#define PATH_CHECKEXISTS 0x0002
#define PATH_HARDPATH 0x0004
#define PATH_NOALLOC 0x0008
#define SHMAT_SUBEXP 0x001 /* save subexpressions in SH_REMATCH */
#define SHMAT_PWARN 0x002 /* print a warning message on invalid regexp */
#define MT_USETMPDIR 0x0001
#define MT_READWRITE 0x0002
#define MT_USERANDOM 0x0004
#define MT_TEMPLATE 0x0008
Typedefs
typedef struct _list_of_strings STRINGLIST
typedef int sh_strlist_map_func_t PARAMS((char *))
Functions
intmax_t evalexp PARAMS ((char *, int, int *))
char *make_command_string PARAMS ((COMMAND *))
char *named_function_string PARAMS ((char *, COMMAND *, int))
void print_simple_command PARAMS ((SIMPLE_COM *))
void print_word_list PARAMS ((WORD_LIST *, char *))
void print_for_command_head PARAMS ((FOR_COM *))
void print_case_command_head PARAMS ((CASE_COM *))
void xtrace_init PARAMS ((void))
void xtrace_fdchk PARAMS ((int))
void xtrace_print_assignment PARAMS ((char *, char *, int, int))
void xtrace_print_word_list PARAMS ((WORD_LIST *, int))
char *xparse_dolparen PARAMS ((char *, char *, int *, int))
COMMAND *parse_string_to_command PARAMS ((char *, int))
WORD_LIST *parse_string_to_word_list PARAMS ((char *, int, const char *))
int set_locale_var PARAMS ((char *, char *))
char *mk_msgstr PARAMS ((char *, int *))
char *locale_expand PARAMS ((char *, int, int, int, int *))
void list_walk PARAMS ((GENERIC_LIST *, sh_glist_func_t *))
void wlist_walk PARAMS ((WORD_LIST *, sh_icpfunc_t *))
GENERIC_LIST * list_reverse ()
int list_length ()
GENERIC_LIST * list_append ()
GENERIC_LIST * list_remove ()
int find_string_in_alist PARAMS ((char *, STRING_INT_ALIST *, int))
char *find_token_in_alist PARAMS ((int, STRING_INT_ALIST *, int))
char *substring PARAMS ((const char *, int, int))
char *strsub PARAMS ((char *, char *, char *, int))
char *strcreplace PARAMS ((char *, int, const char *, int))
void strip_trailing PARAMS ((char *, int, int))
void xbcopy PARAMS ((char *, char *, int))
char *sh_modcase PARAMS ((const char *, char *, int))
void clock_t_to_secs ()
void print_clock_t ()
void dprintf PARAMS ((int, const char *,...)) __attribute__((__format__(printf
char *fmtulong PARAMS ((unsigned long int, int, char *, size_t, int))
char *fmtumax PARAMS ((uintmax_t, int, char *, size_t, int))
char *fnx_fromfs PARAMS ((char *, size_t))
char *inttostr PARAMS ((intmax_t, char *, size_t))
char *itos PARAMS ((intmax_t))
char *uinttostr PARAMS ((uintmax_t, char *, size_t))
char *uitos PARAMS ((uintmax_t))
char *sh_makepath PARAMS ((const char *, const char *, int))
char *mbscasecmp PARAMS ((const char *, const char *))
char *mbschr PARAMS ((const char *, int))
int dup2 PARAMS ((int, int))
char *sh_realpath PARAMS ((const char *, char *))
void sbrand PARAMS ((unsigned long))
size_t mbstrlen PARAMS ((const char *))
int sh_mbsnlen PARAMS ((const char *, size_t, int))
int strncasecmp PARAMS ((const char *, const char *, size_t))
STRINGLIST *strlist_resize PARAMS ((STRINGLIST *, int))
void strlist_flush PARAMS ((STRINGLIST *))
int strlist_remove PARAMS ((STRINGLIST *, char *))
STRINGLIST *strlist_merge PARAMS ((STRINGLIST *, STRINGLIST *))
STRINGLIST *strlist_prefix_suffix PARAMS ((STRINGLIST *, char *, char *))
void strlist_walk PARAMS ((STRINGLIST *, sh_strlist_map_func_t *))
char **strvec_resize PARAMS ((char **, int))
void strvec_flush PARAMS ((char **))
int strvec_remove PARAMS ((char **, char *))
int strvec_posixcmp PARAMS ((char **, char **))
char **strvec_from_word_list PARAMS ((WORD_LIST *, int, int, int *))
WORD_LIST *strvec_to_word_list PARAMS ((char **, int, int))
size_t strnlen PARAMS ((const char *, size_t))
double strtod PARAMS ((const char *, char **))
long strtol PARAMS ((const char *, char **, int))
char *ansicstr PARAMS ((char *, int, int, int *, int *))
char *ansiexpand PARAMS ((char *, int, int, int *))
int sh_charvis PARAMS ((const char *, size_t *, size_t, char *, size_t *))
void timeval_to_secs ()
void print_timeval ()
int sh_mktmpfd PARAMS ((char *, int, char **))
int uconvert PARAMS ((char *, long *, long *, char **))
unsigned int falarm PARAMS ((unsigned int, unsigned int))
int u32cconv PARAMS ((unsigned long, char *))
void get_new_window_size PARAMS ((int, int *, int *))
int zcatfd PARAMS ((int, int, char *))
ssize_t zgetline PARAMS ((int, char **, size_t *, int, int))
int zmapfd PARAMS ((int, char **, char *))
ssize_t zread PARAMS ((int, char *, size_t))
ssize_t zreadc PARAMS ((int, char *))
Data Structure Documentation
_list_of_strings
struct _list_of_strings
Definition at line 384 of file externs.h.
Data Fields
char ** list
int list_len
int list_size
Macro Definition Documentation
CASE_CAPITALIZE
#define CASE_CAPITALIZE 0x0004
Definition at line 186 of file externs.h.
CASE_LOWER
#define CASE_LOWER 0x0001
Definition at line 184 of file externs.h.
CASE_LOWFIRST
#define CASE_LOWFIRST 0x0080
Definition at line 191 of file externs.h.
CASE_TOGGLE
#define CASE_TOGGLE 0x0010
Definition at line 188 of file externs.h.
CASE_TOGGLEALL
#define CASE_TOGGLEALL 0x0020
Definition at line 189 of file externs.h.
CASE_UNCAP
#define CASE_UNCAP 0x0008
Definition at line 187 of file externs.h.
CASE_UPFIRST
#define CASE_UPFIRST 0x0040
Definition at line 190 of file externs.h.
CASE_UPPER
#define CASE_UPPER 0x0002
Definition at line 185 of file externs.h.
CASE_USEWORDS
#define CASE_USEWORDS 0x1000
Definition at line 193 of file externs.h.
EXP_EXPANDED
#define EXP_EXPANDED 0x01
Definition at line 30 of file externs.h.
FL_ADDBASE
#define FL_ADDBASE 0x02 /* add base# prefix to converted value */
Definition at line 209 of file externs.h.
FL_HEXUPPER
#define FL_HEXUPPER 0x04 /* use uppercase when converting to hex */
Definition at line 210 of file externs.h.
FL_PREFIX
#define FL_PREFIX 0x01 /* add 0x, 0X, or 0 prefix as appropriate */
Definition at line 208 of file externs.h.
FL_UNSIGNED
#define FL_UNSIGNED 0x08 /* don't add any sign */
Definition at line 211 of file externs.h.
FUNC_EXTERNAL
#define FUNC_EXTERNAL 0x02
Definition at line 36 of file externs.h.
FUNC_MULTILINE
#define FUNC_MULTILINE 0x01
Definition at line 35 of file externs.h.
MP_DOCWD
#define MP_DOCWD 0x02
Definition at line 257 of file externs.h.
MP_DOTILDE
#define MP_DOTILDE 0x01
Definition at line 256 of file externs.h.
MP_IGNDOT
#define MP_IGNDOT 0x08
Definition at line 259 of file externs.h.
MP_RMDOT
#define MP_RMDOT 0x04
Definition at line 258 of file externs.h.
MT_READWRITE
#define MT_READWRITE 0x0002
Definition at line 487 of file externs.h.
MT_TEMPLATE
#define MT_TEMPLATE 0x0008
Definition at line 489 of file externs.h.
MT_USERANDOM
#define MT_USERANDOM 0x0004
Definition at line 488 of file externs.h.
MT_USETMPDIR
#define MT_USETMPDIR 0x0001
Definition at line 486 of file externs.h.
PATH_CHECKDOTDOT
#define PATH_CHECKDOTDOT 0x0001
Definition at line 302 of file externs.h.
PATH_CHECKEXISTS
#define PATH_CHECKEXISTS 0x0002
Definition at line 303 of file externs.h.
PATH_HARDPATH
#define PATH_HARDPATH 0x0004
Definition at line 304 of file externs.h.
PATH_NOALLOC
#define PATH_NOALLOC 0x0008
Definition at line 305 of file externs.h.
SHMAT_PWARN
#define SHMAT_PWARN 0x002 /* print a warning message on invalid regexp */
Definition at line 333 of file externs.h.
SHMAT_SUBEXP
#define SHMAT_SUBEXP 0x001 /* save subexpressions in SH_REMATCH */
Definition at line 332 of file externs.h.
Typedef Documentation
PARAMS
typedef int sh_strlist_map_func_t PARAMS((char *))
Definition at line 390 of file externs.h.
STRINGLIST
typedef struct _list_of_strings STRINGLIST
Function Documentation
clock_t_to_secs()
void clock_t_to_secs ()
list_append()
GENERIC_LIST* list_append ()
Referenced by glob_expand_word_list(), and shell_expand_word_list().
list_length()
int list_length ()
Referenced by getconf_builtin(), remember_args(), strlist_from_word_list(), and strvec_from_word_list().
list_remove()
GENERIC_LIST* list_remove ()
list_reverse()
GENERIC_LIST* list_reverse ()
PARAMS() [1/72]
void print_case_command_head PARAMS ((CASE_COM *))
PARAMS() [2/72]
void strvec_flush PARAMS ((char **))
PARAMS() [3/72]
int strvec_remove PARAMS ((char **, char *))
PARAMS() [4/72]
int strvec_posixcmp PARAMS ((char **, char **))
PARAMS() [5/72]
char** strvec_resize PARAMS ((char **, int))
PARAMS() [6/72]
WORD_LIST* strvec_to_word_list PARAMS ((char **, int, int))
PARAMS() [7/72]
int set_locale_var PARAMS ((char *, char *))
PARAMS() [8/72]
char* strsub PARAMS ((char *, char *, char *, int))
PARAMS() [9/72]
char* xparse_dolparen PARAMS ((char *, char *, int *, int))
PARAMS() [10/72]
void xbcopy PARAMS ((char *, char *, int))
PARAMS() [11/72]
void xtrace_print_assignment PARAMS ((char *, char *, int, int))
PARAMS() [12/72]
char* named_function_string PARAMS ((char *, COMMAND *, int))
PARAMS() [13/72]
char* mk_msgstr PARAMS ((char *, int *))
PARAMS() [14/72]
COMMAND* parse_string_to_command PARAMS ((char *, int))
PARAMS() [15/72]
int sh_mktmpfd PARAMS ((char *, int, char **))
PARAMS() [16/72]
WORD_LIST* parse_string_to_word_list PARAMS ((char *, int, const char *))
PARAMS() [17/72]
char* strcreplace PARAMS ((char *, int, const char *, int))
PARAMS() [18/72]
intmax_t evalexp PARAMS ((char *, int, int *))
PARAMS() [19/72]
void strip_trailing PARAMS ((char *, int, int))
PARAMS() [20/72]
char* ansiexpand PARAMS ((char *, int, int, int *))
PARAMS() [21/72]
char* ansicstr PARAMS ((char *, int, int, int *, int *))
PARAMS() [22/72]
char* locale_expand PARAMS ((char *, int, int, int, int *))
PARAMS() [23/72]
int uconvert PARAMS ((char *, long *, long *, char **))
PARAMS() [24/72]
char* fnx_fromfs PARAMS ((char *, size_t))
PARAMS() [25/72]
int find_string_in_alist PARAMS ((char *, STRING_INT_ALIST *, int))
PARAMS() [26/72]
char* make_command_string PARAMS ((COMMAND *))
PARAMS() [27/72]
size_t mbstrlen PARAMS ((const char *))
PARAMS() [28/72]
char* sh_realpath PARAMS ((const char *, char *))
PARAMS() [29/72]
double strtod PARAMS ((const char *, char **))
PARAMS() [30/72]
long strtol PARAMS ((const char *, char **, int))
PARAMS() [31/72]
char* sh_modcase PARAMS ((const char *, char *, int))
PARAMS() [32/72]
char* mbscasecmp PARAMS ((const char *, const char *))
PARAMS() [33/72]
char* sh_makepath PARAMS ((const char *, const char *, int))
PARAMS() [34/72]
int strncasecmp PARAMS ((const char *, const char *, size_t))
PARAMS() [35/72]
char* mbschr PARAMS ((const char *, int))
PARAMS() [36/72]
char* substring PARAMS ((const char *, int, int))
PARAMS() [37/72]
int sh_charvis PARAMS ((const char *, size_t *, size_t, char *, size_t *))
PARAMS() [38/72]
size_t strnlen PARAMS ((const char *, size_t))
PARAMS() [39/72]
int sh_mbsnlen PARAMS ((const char *, size_t, int))
PARAMS() [40/72]
void print_for_command_head PARAMS ((FOR_COM *))
PARAMS() [41/72]
void list_walk PARAMS ((GENERIC_LIST *, sh_glist_func_t *))
PARAMS() [42/72]
void xtrace_fdchk PARAMS ((int))
PARAMS() [43/72]
ssize_t zreadc PARAMS ((int, char *))
PARAMS() [44/72]
int zmapfd PARAMS ((int, char **, char *))
PARAMS() [45/72]
ssize_t zgetline PARAMS ((int, char **, size_t *, int, int))
PARAMS() [46/72]
ssize_t zread PARAMS ((int, char *, size_t))
PARAMS() [47/72]
void dprintf PARAMS ((int, const char *,...))
PARAMS() [48/72]
void get_new_window_size PARAMS ((int, int *, int *))
PARAMS() [49/72]
int dup2 PARAMS ((int, int))
PARAMS() [50/72]
int zcatfd PARAMS ((int, int, char *))
PARAMS() [51/72]
char* find_token_in_alist PARAMS ((int, STRING_INT_ALIST *, int))
PARAMS() [52/72]
char* itos PARAMS ((intmax_t))
PARAMS() [53/72]
char* inttostr PARAMS ((intmax_t, char *, size_t))
PARAMS() [54/72]
void print_simple_command PARAMS ((SIMPLE_COM *))
PARAMS() [55/72]
void strlist_flush PARAMS ((STRINGLIST *))
PARAMS() [56/72]
int strlist_remove PARAMS ((STRINGLIST *, char *))
PARAMS() [57/72]
STRINGLIST* strlist_prefix_suffix PARAMS ((STRINGLIST *, char *, char *))
PARAMS() [58/72]
STRINGLIST* strlist_resize PARAMS ((STRINGLIST *, int))
PARAMS() [59/72]
void strlist_walk PARAMS ((STRINGLIST *, sh_strlist_map_func_t *))
PARAMS() [60/72]
STRINGLIST* strlist_merge PARAMS ((STRINGLIST *, STRINGLIST *))
PARAMS() [61/72]
char* uitos PARAMS ((uintmax_t))
PARAMS() [62/72]
char* uinttostr PARAMS ((uintmax_t, char *, size_t))
PARAMS() [63/72]
char* fmtumax PARAMS ((uintmax_t, int, char *, size_t, int))
PARAMS() [64/72]
unsigned int falarm PARAMS ((unsigned int, unsigned int))
PARAMS() [65/72]
char* fmtulong PARAMS ((unsigned long int, int, char *, size_t, int))
PARAMS() [66/72]
void sbrand PARAMS ((unsigned long))
PARAMS() [67/72]
int u32cconv PARAMS ((unsigned long, char *))
PARAMS() [68/72]
void xtrace_init PARAMS ((void))
PARAMS() [69/72]
void print_word_list PARAMS ((WORD_LIST *, char *))
PARAMS() [70/72]
void xtrace_print_word_list PARAMS ((WORD_LIST *, int))
PARAMS() [71/72]
char** strvec_from_word_list PARAMS ((WORD_LIST *, int, int, int *))
PARAMS() [72/72]
void wlist_walk PARAMS ((WORD_LIST *, sh_icpfunc_t *))
print_clock_t()
void print_clock_t ()
print_timeval()
void print_timeval ()
timeval_to_secs()
void timeval_to_secs ()