Fennix Kernel: Kernel/core/debugger.cpp File Reference
debugger.cpp File Reference
#include <debug.h>
#include <printf.h>
#include <lock.hpp>
#include <io.h>
#include "../kernel.h"
Namespaces
SysDbg
Functions
NewLock (DebuggerLock)
EXTERNC NIF void uart_wrapper (char c, void *unused)
static NIF bool WritePrefix (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format, va_list args)
NIF void SysDbg::Write (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbg::WriteLine (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbg::LockedWrite (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbg::LockedWriteLine (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbgWrite (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbgWriteLine (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbgLockedWrite (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void SysDbgLockedWriteLine (enum DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
Variables
bool serialports [8]
Function Documentation
NewLock()
NewLock (DebuggerLock)
SysDbgLockedWrite()
NIF void SysDbgLockedWrite (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 208 of file debugger.cpp.
 {
     SmartTimeoutLock(DebuggerLock, 1000);
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
 }
References Level, Line, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
SysDbgLockedWriteLine()
NIF void SysDbgLockedWriteLine (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 223 of file debugger.cpp.
 {
     SmartTimeoutLock(DebuggerLock, 1000);
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
     uart_wrapper('\n', nullptr);
 }
References Level, Line, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
SysDbgWrite()
NIF void SysDbgWrite (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 179 of file debugger.cpp.
 {
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
 }
References Level, Line, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
SysDbgWriteLine()
NIF void SysDbgWriteLine (enum DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 193 of file debugger.cpp.
 {
     va_list args;
     va_start(args, Format);
     if (!WritePrefix(Level, File, Line, Function, Format, args))
     {
         va_end(args);
         return;
     }
     vfctprintf(uart_wrapper, nullptr, Format, args);
     va_end(args);
     uart_wrapper('\n', nullptr);
 }
References Level, Line, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
uart_wrapper()
EXTERNC NIF void uart_wrapper (char c, void * unused)
Definition at line 30 of file debugger.cpp.
 {
     static int once = 0;
     if (unlikely(!once++))
     {
         uint8_t com = inb(0x3F8);
         if (com != 0xFF)
         {
             outb(s_cst(uint16_t, 0x3F8 + 1), 0x00); // Disable all interrupts
             outb(s_cst(uint16_t, 0x3F8 + 3), 0x80); // Enable DLAB (set baud rate divisor)
             outb(s_cst(uint16_t, 0x3F8 + 0), 0x1);  // Set divisor to 1 (lo byte) 115200 baud
             outb(s_cst(uint16_t, 0x3F8 + 1), 0x0);  //                  (hi byte)
             outb(s_cst(uint16_t, 0x3F8 + 3), 0x03); // 8 bits, no parity, one stop bit
             outb(s_cst(uint16_t, 0x3F8 + 2), 0xC7); // Enable FIFO, clear them, with 14-byte threshold
             outb(s_cst(uint16_t, 0x3F8 + 4), 0x0B); // IRQs enabled, RTS/DSR set
             /* FIXME  https://wiki.osdev.org/Serial_Ports */
             // outb(s_cst(uint16_t, 0x3F8 + 0), 0x1E);
             // outb(s_cst(uint16_t, 0x3F8 + 0), 0xAE);
             // Check if the serial port is faulty.
             // if (inb(s_cst(uint16_t, 0x3F8 + 0)) != 0xAE)
             // {
             //     static int once = 0;
             //     if (!once++)
             //         warn("Serial port %#llx is faulty.", 0x3F8);
             //     // serialports[0x3F8] = false; // ignore for now
             //     // return;
             // }
             // Set to normal operation mode.
             outb(s_cst(uint16_t, 0x3F8 + 4), 0x0F);
             serialports[0] = true;
         }
     }
     if (likely(serialports[0]))
     {
         while ((inb(s_cst(uint16_t, 0x3F8 + 5)) & 0x20) == 0)
             ;
         outb(0x3F8, c);
     }
     UNUSED(unused);
 }
References likely, serialports, unlikely, and UNUSED.
Referenced by Driver::KernelLog(), KPrint(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), vprintf_dumper(), SysDbg::Write(), SysDbg::WriteLine(), and WritePrefix().
WritePrefix()
static NIF bool WritePrefix (DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, va_list args) inline static
Definition at line 74 of file debugger.cpp.
 {
     const char *DbgLvlString;
     switch (Level)
     {
     case DebugLevelError:
         DbgLvlString = "ERROR";
         break;
     case DebugLevelWarning:
         DbgLvlString = "WARN ";
         break;
     case DebugLevelInfo:
         DbgLvlString = "INFO ";
         break;
     case DebugLevelDebug:
         DbgLvlString = "DEBUG";
         break;
     case DebugLevelTrace:
         DbgLvlString = "TRACE";
         break;
     case DebugLevelFixme:
         DbgLvlString = "FIXME";
         break;
     case DebugLevelStub:
         fctprintf(uart_wrapper, nullptr, "STUB | %s>%s() is stub\n", File, Function);
         return false;
     case DebugLevelFunction:
         fctprintf(uart_wrapper, nullptr, "FUNC | %s>%s( ", File, Function);
         vfctprintf(uart_wrapper, nullptr, Format, args);
         fctprintf(uart_wrapper, nullptr, " )\n");
         return false;
     case DebugLevelUbsan:
     {
         DbgLvlString = "UBSAN";
         fctprintf(uart_wrapper, nullptr, "%s| ", DbgLvlString);
         return true;
     }
     default:
         DbgLvlString = "UNKNW";
         break;
     }
     fctprintf(uart_wrapper, nullptr, "%s| %s>%s:%d: ", DbgLvlString, File, Function, Line);
     return true;
 }
References DebugLevelDebug, DebugLevelError, DebugLevelFixme, DebugLevelFunction, DebugLevelInfo, DebugLevelStub, DebugLevelTrace, DebugLevelUbsan, DebugLevelWarning, fctprintf(), Level, Line, uart_wrapper(), and vfctprintf().
Referenced by SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), SysDbg::Write(), and SysDbg::WriteLine().
Variable Documentation
serialports
bool serialports[8] extern
Definition at line 23 of file uart.cpp.
Referenced by UniversalAsynchronousReceiverTransmitter::UART::UART(), and uart_wrapper().