Fennix Userspace: Userspace/musl/src/thread/pthread_testcancel.c File Reference
pthread_testcancel.c File Reference
#include "pthread_impl.h"
Functions
static void dummy ()
weak_alias (dummy, __testcancel)
void __pthread_testcancel ()
weak_alias (__pthread_testcancel, pthread_testcancel)
Function Documentation
__pthread_testcancel()
void __pthread_testcancel (void)
Definition at line 9 of file pthread_testcancel.c.
 {
     __testcancel();
 }
References __testcancel().
Referenced by __pthread_cond_timedwait(), and __pthread_timedjoin_np().
dummy()
static void dummy (void) static
Definition at line 3 of file pthread_testcancel.c.
 {
 }
weak_alias() [1/2]
weak_alias (__pthread_testcancel , pthread_testcancel)
weak_alias() [2/2]
weak_alias (dummy , __testcancel)