Fennix Kernel: Kernel/include/md5.h File Reference
md5.h File Reference
#include <types.h>
Data Structures
struct MD5Context
Functions
void md5Init (MD5Context *ctx)
void md5Update (MD5Context *ctx, uint8_t *input, size_t input_len)
void md5Finalize (MD5Context *ctx)
void md5Step (uint32_t *buffer, uint32_t *input)
uint8_t * md5String (char *input)
uint8_t * md5File (uint8_t *buffer, size_t input_len)
uint32_t F (uint32_t X, uint32_t Y, uint32_t Z)
uint32_t G (uint32_t X, uint32_t Y, uint32_t Z)
uint32_t H (uint32_t X, uint32_t Y, uint32_t Z)
uint32_t I (uint32_t X, uint32_t Y, uint32_t Z)
uint32_t rotateLeft (uint32_t x, uint32_t n)
Data Structure Documentation
MD5Context
struct MD5Context
Definition at line 29 of file md5.h.
Data Fields
uint32_t buffer[4]
uint8_t digest[16]
uint8_t input[64]
size_t size
Function Documentation
F()
uint32_t F (uint32_t X, uint32_t Y, uint32_t Z)
G()
uint32_t G (uint32_t X, uint32_t Y, uint32_t Z)
Referenced by MapFramebuffer(), MapKernel(), PageFaultExceptionHandler(), and UserModeExceptionHandler().
H()
uint32_t H (uint32_t X, uint32_t Y, uint32_t Z)
I()
uint32_t I (uint32_t X, uint32_t Y, uint32_t Z)
md5File()
uint8_t* md5File (uint8_t * buffer, size_t input_len)
Definition at line 221 of file md5.c.
 {
     char *input_buffer = (char *)buffer;
     size_t input_size = input_len;
     MD5Context ctx;
     md5Init(&ctx);
     while (input_size > 0)
     {
         size_t chunk_size = input_size > 1024 ? 1024 : input_size;
         md5Update(&ctx, (uint8_t *)input_buffer, chunk_size);
         input_buffer += chunk_size;
         input_size -= chunk_size;
     }
     // while ((input_size = fread(input_buffer, 1, 1024, file)) > 0)
     // {
     //     md5Update(&ctx, (uint8_t *)input_buffer, input_size);
     // }
     md5Finalize(&ctx);
     uint8_t *result = kmalloc(16);
     if (result == NULL)
         return (uint8_t *)"error";
     memcpy(result, ctx.digest, 16);
     return result;
 }
References MD5Context::digest, kmalloc, md5Finalize(), md5Init(), md5Update(), memcpy(), and NULL.
Referenced by DumpData().
md5Finalize()
void md5Finalize (MD5Context * ctx)
Definition at line 117 of file md5.c.
 {
     uint32_t input[16];
     unsigned int offset = ctx->size % 64;
     unsigned int padding_length = offset < 56 ? 56 - offset : (56 + 64) - offset;
     // Fill in the padding and do the changes to size that resulted from the update
     md5Update(ctx, PADDING, padding_length);
     ctx->size -= (uint64_t)padding_length;
     // Do a final update (internal to this function)
     // Last two 32-bit words are the two halves of the size (converted from bytes to bits)
     for (unsigned int j = 0; j < 14; ++j)
     {
         input[j] = (uint32_t)(ctx->input[(j * 4) + 3]) << 24 |
                    (uint32_t)(ctx->input[(j * 4) + 2]) << 16 |
                    (uint32_t)(ctx->input[(j * 4) + 1]) << 8 |
                    (uint32_t)(ctx->input[(j * 4)]);
     }
     input[14] = (uint32_t)(ctx->size * 8);
 #ifdef a32
     input[15] = (uint32_t)((uint64_t)(((uint64_t)ctx->size >> 32) | ((uint64_t)ctx->size << 32)) >> 32);
 #else
     input[15] = (uint32_t)((ctx->size * 8) >> 32);
 #endif
     md5Step(ctx->buffer, input);
     // Move the result into digest (convert from little-endian)
     for (unsigned int i = 0; i < 4; ++i)
     {
         ctx->digest[(i * 4) + 0] = (uint8_t)((ctx->buffer[i] & 0x000000FF));
         ctx->digest[(i * 4) + 1] = (uint8_t)((ctx->buffer[i] & 0x0000FF00) >> 8);
         ctx->digest[(i * 4) + 2] = (uint8_t)((ctx->buffer[i] & 0x00FF0000) >> 16);
         ctx->digest[(i * 4) + 3] = (uint8_t)((ctx->buffer[i] & 0xFF000000) >> 24);
     }
 }
References MD5Context::buffer, MD5Context::digest, MD5Context::input, md5Step(), md5Update(), PADDING, and MD5Context::size.
Referenced by md5File(), and md5String().
md5Init()
void md5Init (MD5Context * ctx)
Definition at line 64 of file md5.c.
 {
     ctx->size = (uint64_t)0;
     ctx->buffer[0] = (uint32_t)A;
     ctx->buffer[1] = (uint32_t)B;
     ctx->buffer[2] = (uint32_t)C;
     ctx->buffer[3] = (uint32_t)D;
 }
References A, B, MD5Context::buffer, C, D, and MD5Context::size.
Referenced by md5File(), and md5String().
md5Step()
void md5Step (uint32_t * buffer, uint32_t * input)
Definition at line 158 of file md5.c.
 {
     uint32_t AA = buffer[0];
     uint32_t BB = buffer[1];
     uint32_t CC = buffer[2];
     uint32_t DD = buffer[3];
     uint32_t E;
     unsigned int j;
     for (unsigned int i = 0; i < 64; ++i)
     {
         switch (i / 16)
         {
         case 0:
             E = F(BB, CC, DD);
             j = i;
             break;
         case 1:
             E = G(BB, CC, DD);
             j = ((i * 5) + 1) % 16;
             break;
         case 2:
             E = H(BB, CC, DD);
             j = ((i * 3) + 5) % 16;
             break;
         default:
             E = I(BB, CC, DD);
             j = (i * 7) % 16;
             break;
         }
         uint32_t temp = DD;
         DD = CC;
         CC = BB;
         BB = BB + rotateLeft(AA + E + K[i] + input[j], S[i]);
         AA = temp;
     }
     buffer[0] += AA;
     buffer[1] += BB;
     buffer[2] += CC;
     buffer[3] += DD;
 }
References Gigabit::DD, F, G, H, I, K, rotateLeft(), and S.
Referenced by md5Finalize(), and md5Update().
md5String()
uint8_t* md5String (char * input)
Definition at line 207 of file md5.c.
 {
     MD5Context ctx;
     md5Init(&ctx);
     md5Update(&ctx, (uint8_t *)input, strlen(input));
     md5Finalize(&ctx);
     uint8_t *result = kmalloc(16);
     if (result == NULL)
         return (uint8_t *)"error";
     memcpy(result, ctx.digest, 16);
     return result;
 }
References MD5Context::digest, kmalloc, md5Finalize(), md5Init(), md5Update(), memcpy(), NULL, and strlen().
md5Update()
void md5Update (MD5Context * ctx, uint8_t * input, size_t input_len)
Definition at line 80 of file md5.c.
 {
     uint32_t input[16];
     unsigned int offset = ctx->size % 64;
     ctx->size += (uint64_t)input_len;
     // Copy each byte in input_buffer into the next space in our context input
     for (unsigned int i = 0; i < input_len; ++i)
     {
         ctx->input[offset++] = (uint8_t) * (input_buffer + i);
         // If we've filled our context input, copy it into our local array input
         // then reset the offset to 0 and fill in a new buffer.
         // Every time we fill out a chunk, we run it through the algorithm
         // to enable some back and forth between cpu and i/o
         if (offset % 64 == 0)
         {
             for (unsigned int j = 0; j < 16; ++j)
             {
                 // Convert to little-endian
                 // The local variable `input` our 512-bit chunk separated into 32-bit words
                 // we can use in calculations
                 input[j] = (uint32_t)(ctx->input[(j * 4) + 3]) << 24 |
                            (uint32_t)(ctx->input[(j * 4) + 2]) << 16 |
                            (uint32_t)(ctx->input[(j * 4) + 1]) << 8 |
                            (uint32_t)(ctx->input[(j * 4)]);
             }
             md5Step(ctx->buffer, input);
             offset = 0;
         }
     }
 }
References MD5Context::buffer, MD5Context::input, md5Step(), and MD5Context::size.
Referenced by md5File(), md5Finalize(), and md5String().
rotateLeft()
uint32_t rotateLeft (uint32_t x, uint32_t n)
Definition at line 254 of file md5.c.
 {
     return (x << n) | (x >> (32 - n));
 }
Referenced by md5Step().