Fennix Userspace: Userspace/musl/include/stdio.h File Reference
stdio.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
union _G_fpos64_t
Macros
#define __NEED_FILE
#define __NEED___isoc_va_list
#define __NEED_size_t
#define __NEED_struct__IO_FILE
#define NULL ((void*)0)
#define EOF (-1)
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define _IOFBF 0
#define _IOLBF 1
#define _IONBF 2
#define BUFSIZ 1024
#define FILENAME_MAX 4096
#define FOPEN_MAX 1000
#define TMP_MAX 10000
#define L_tmpnam 20
#define stdin (stdin)
#define stdout (stdout)
#define stderr (stderr)
Typedefs
typedef union _G_fpos64_t fpos_t
Functions
FILE * fopen (const char *__restrict, const char *__restrict)
FILE * freopen (const char *__restrict, const char *__restrict, FILE *__restrict)
int fclose (FILE *)
int remove (const char *)
int rename (const char *, const char *)
int feof (FILE *)
int ferror (FILE *)
int fflush (FILE *)
void clearerr (FILE *)
int fseek (FILE *, long, int)
long ftell (FILE *)
void rewind (FILE *)
int fgetpos (FILE *__restrict, fpos_t *__restrict)
int fsetpos (FILE *, const fpos_t *)
size_t fread (void *__restrict, size_t, size_t, FILE *__restrict)
size_t fwrite (const void *__restrict, size_t, size_t, FILE *__restrict)
int fgetc (FILE *)
int getc (FILE *)
int getchar (void)
int ungetc (int, FILE *)
int fputc (int, FILE *)
int putc (int, FILE *)
int putchar (int)
char * fgets (char *__restrict, int, FILE *__restrict)
char * gets (char *)
int fputs (const char *__restrict, FILE *__restrict)
int puts (const char *)
int printf (const char *__restrict,...)
int fprintf (FILE *__restrict, const char *__restrict,...)
int sprintf (char *__restrict, const char *__restrict,...)
int snprintf (char *__restrict, size_t, const char *__restrict,...)
int vprintf (const char *__restrict, __isoc_va_list)
int vfprintf (FILE *__restrict, const char *__restrict, __isoc_va_list)
int vsprintf (char *__restrict, const char *__restrict, __isoc_va_list)
int vsnprintf (char *__restrict, size_t, const char *__restrict, __isoc_va_list)
int scanf (const char *__restrict,...)
int fscanf (FILE *__restrict, const char *__restrict,...)
int sscanf (const char *__restrict, const char *__restrict,...)
int vscanf (const char *__restrict, __isoc_va_list)
int vfscanf (FILE *__restrict, const char *__restrict, __isoc_va_list)
int vsscanf (const char *__restrict, const char *__restrict, __isoc_va_list)
void perror (const char *)
int setvbuf (FILE *__restrict, char *__restrict, int, size_t)
void setbuf (FILE *__restrict, char *__restrict)
char * tmpnam (char *)
FILE * tmpfile (void)
Variables
FILE *const stdin
FILE *const stdout
FILE *const stderr
Data Structure Documentation
_G_fpos64_t
union _G_fpos64_t
Definition at line 56 of file stdio.h.
Data Fields
double __align
long long __lldata
char __opaque[16]
Macro Definition Documentation
__NEED___isoc_va_list
#define __NEED___isoc_va_list
Definition at line 11 of file stdio.h.
__NEED_FILE
#define __NEED_FILE
Definition at line 10 of file stdio.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 12 of file stdio.h.
__NEED_struct__IO_FILE
#define __NEED_struct__IO_FILE
Definition at line 15 of file stdio.h.
_IOFBF
#define _IOFBF 0
Definition at line 46 of file stdio.h.
_IOLBF
#define _IOLBF 1
Definition at line 47 of file stdio.h.
_IONBF
#define _IONBF 2
Definition at line 48 of file stdio.h.
BUFSIZ
#define BUFSIZ 1024
Definition at line 50 of file stdio.h.
EOF
#define EOF (-1)
Definition at line 37 of file stdio.h.
FILENAME_MAX
#define FILENAME_MAX 4096
Definition at line 51 of file stdio.h.
FOPEN_MAX
#define FOPEN_MAX 1000
Definition at line 52 of file stdio.h.
L_tmpnam
#define L_tmpnam 20
Definition at line 54 of file stdio.h.
NULL
#define NULL ((void*)0)
Definition at line 33 of file stdio.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 43 of file stdio.h.
SEEK_END
#define SEEK_END 2
Definition at line 44 of file stdio.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 42 of file stdio.h.
stderr
#define stderr (stderr)
Definition at line 68 of file stdio.h.
stdin
#define stdin (stdin)
Definition at line 66 of file stdio.h.
stdout
#define stdout (stdout)
Definition at line 67 of file stdio.h.
TMP_MAX
#define TMP_MAX 10000
Definition at line 53 of file stdio.h.
Typedef Documentation
fpos_t
typedef union _G_fpos64_t fpos_t
Function Documentation
clearerr()
void clearerr (FILE * f)
Definition at line 3 of file clearerr.c.
 {
     FLOCK(f);
     f->flags &= ~(F_EOF|F_ERR);
     FUNLOCK(f);
 }
References f, F_EOF, F_ERR, _IO_FILE::flags, FLOCK, and FUNLOCK.
Referenced by evalbltin(), execute_builtin_or_function(), expand_main(), read_a_line(), retrieve_file_data(), sh_chkwrite(), and shell_getc().
fclose()
int fclose (FILE * fp)
Definition at line 54 of file file.c.
 {
     if (fp == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     return syscall1(sc_close, fp->_fileno);
 }
References __ofl_lock(), __ofl_unlock(), __unlist_locked_file(), _IO_FILE::close, f, F_PERM, fflush(), _IO_FILE::flags, FLOCK, free, FUNLOCK, _IO_FILE::getln_buf, head, _IO_FILE::next, and _IO_FILE::prev.
feof()
int feof (FILE * f)
Definition at line 5 of file feof.c.
 {
     FLOCK(f);
     int ret = !!(f->flags & F_EOF);
     FUNLOCK(f);
     return ret;
 }
References f, F_EOF, _IO_FILE::flags, FLOCK, and FUNLOCK.
ferror()
int ferror (FILE * f)
Definition at line 5 of file ferror.c.
 {
     FLOCK(f);
     int ret = !!(f->flags & F_ERR);
     FUNLOCK(f);
     return ret;
 }
References f, F_ERR, _IO_FILE::flags, FLOCK, and FUNLOCK.
fflush()
int fflush (FILE * stream)
Definition at line 85 of file file.c.
 {
     if (stream == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     errno = ENOSYS;
     return EOF;
 }
References __ofl_lock(), __ofl_unlock(), __stderr_used, __stdout_used, EOF, f, FLOCK, FUNLOCK, _IO_FILE::next, _IO_FILE::rend, _IO_FILE::rpos, _IO_FILE::seek, SEEK_CUR, _IO_FILE::wbase, _IO_FILE::wend, _IO_FILE::wpos, and _IO_FILE::write.
fgetc()
int fgetc (FILE * stream)
Definition at line 7 of file get.c.
 {
 }
References do_getc(), and f.
fgetpos()
int fgetpos (FILE * __restrict, fpos_t * __restrict)
fgets()
char* fgets (char * __restrict, int , FILE * __restrict)
fopen()
FILE* fopen (const char * __restrict, const char * __restrict)
Definition at line 19 of file file.c.
 {
     int fd = syscall2(sc_open, (uint64_t)filename, (uint64_t)mode);
     if (fd < 0)
         return NULL;
     FILE *FilePtr = malloc(sizeof(FILE));
     FilePtr->_fileno = fd;
     return FilePtr;
 }
fprintf()
int fprintf (FILE * __restrict, const char * __restrict, ...)
Definition at line 97 of file file.c.
 {
     if (stream == NULL || format == NULL)
     {
         errno = EINVAL;
         return -1;
     }
     va_list args;
     va_start(args, format);
     const int ret = vfprintf(stream, format, args);
     va_end(args);
     return ret;
 }
fputc()
int fputc (int c, FILE * stream)
Definition at line 7 of file put.c.
 {
     // FIXME
     // if (stream == NULL)
     // {
     //     errno = EBADF;
     //     return EOF;
     // }
     char str[2] = {c, '\0'};
     // return syscall3(sys_KernelCTL, KCTL_PRINT, str, 0);
 }
References c, do_putc(), and f.
Referenced by fputs(), putc(), putchar(), and puts().
fputs()
int fputs (const char * __restrict, FILE * __restrict)
Definition at line 21 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stream);
 }
Referenced by perror().
fread()
size_t fread (void * __restrict, size_t size, size_t nmemb, FILE * __restrict)
Definition at line 30 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_read, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
freopen()
FILE* freopen (const char * __restrict, const char * __restrict, FILE * __restrict)
Definition at line 13 of file file.c.
 {
     errno = ENOSYS;
     return NULL;
 }
fscanf()
int fscanf (FILE * __restrict, const char * __restrict, ...)
Referenced by bb_displayroutes(), dialog_menu(), do_pidfile(), get_charset_aliases(), get_hz(), get_list_blocks(), get_smp_uptime(), getmntent_r(), LoadDefaultCollection(), scriptreplay_main(), and vfwscanf().
fseek()
int fseek (FILE * f, long off, int whence)
Definition at line 43 of file fseek.c.
 {
     return __fseeko(f, off, whence);
 }
fsetpos()
int fsetpos (FILE * f, const fpos_t * pos)
Definition at line 3 of file fsetpos.c.
 {
     return __fseeko(f, *(const long long *)pos, SEEK_SET);
 }
References __fseeko(), f, pos, and SEEK_SET.
ftell()
long ftell (FILE * stream)
Definition at line 80 of file file.c.
 {
     return stream->_offset;
 }
References __ftello(), EOVERFLOW, errno, f, LONG_MAX, off_t, and pos.
fwrite()
size_t fwrite (const void * __restrict, size_t size, size_t nmemb, FILE * __restrict)
Definition at line 42 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_write, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
getc()
int getc (FILE * f)
Definition at line 4 of file getc.c.
 {
     return do_getc(f);
 }
References do_getc(), and f.
getchar()
int getchar (void)
Definition at line 4 of file getchar.c.
 {
     return do_getc(stdin);
 }
References do_getc(), and stdin.
gets()
char* gets (char * s)
Definition at line 5 of file gets.c.
 {
     size_t i=0;
     int c;
     FLOCK(stdin);
     while ((c=getc_unlocked(stdin)) != EOF && c != '\n') s[i++] = c;
     s[i] = 0;
     if (c != '\n' && (!feof(stdin) || !i)) s = 0;
     FUNLOCK(stdin);
     return s;
 }
References c, EOF, feof, FLOCK, FUNLOCK, getc_unlocked(), i, s, and stdin.
perror()
void perror (const char * s)
Definition at line 34 of file put.c.
 { fputs(s, stderr); }
References errno, f, FLOCK, fputc, FUNLOCK, fwrite(), _IO_FILE::locale, _IO_FILE::mode, stderr, strerror(), and strlen().
printf()
int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 1554 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vprintf(format, args);
     va_end(args);
     return ret;
 }
Referenced by print_direc().
putc()
int putc (int c, FILE * stream)
Definition at line 19 of file put.c.
 { return fputc(c, stream); }
References c, do_putc(), and f.
putchar()
int putchar (int c)
Definition at line 33 of file put.c.
 { return fputc(c, stdout); }
References c, do_putc(), and stdout.
puts()
int puts (const char * s)
Definition at line 27 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stdout);
 }
References FLOCK, fputs, FUNLOCK, putc_unlocked(), s, and stdout.
remove()
int remove (const char * pathname)
Definition at line 10 of file sys_stat.c.
 {
     return 0;
 }
References __syscall, __syscall_ret(), AT_FDCWD, AT_REMOVEDIR, and EISDIR.
rename()
int rename (const char * oldpath, const char * newpath)
Definition at line 15 of file sys_stat.c.
 {
     return 0;
 }
References AT_FDCWD, old, and syscall().
rewind()
void rewind (FILE * f)
Definition at line 3 of file rewind.c.
 {
     FLOCK(f);
     __fseeko_unlocked(f, 0, SEEK_SET);
     f->flags &= ~F_ERR;
     FUNLOCK(f);
 }
References __fseeko_unlocked(), f, F_ERR, _IO_FILE::flags, FLOCK, FUNLOCK, and SEEK_SET.
Referenced by setpwent().
scanf()
int scanf (const char * __restrict, ...)
Referenced by resize_main().
setbuf()
void setbuf (FILE * __restrict, char * __restrict)
Definition at line 112 of file file.c.
 {
 }
setvbuf()
int setvbuf (FILE * __restrict, char * __restrict, int , size_t)
Referenced by hexedit_main(), logdir_open(), rotate(), setbuf(), setbuffer(), setlinebuf(), sh_setlinebuf(), svlogd_main(), and tee_main().
snprintf()
int snprintf (char * s, size_t count, const char * format, ...)
An implementation of the C standard's snprintf/vsnprintf
Parameters
s An array in which to store the formatted string. It must be large enough to fit either the entire formatted output, or at least n characters. Alternatively, it can be NULL, in which case nothing will be printed, and only the number of characters which could have been printed is tallied and returned.
n The maximum number of characters to write to the array, including a terminating null character
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters that COULD have been written into s, not counting the terminating null character. A value equal or larger than n indicates truncation. Only when the returned value is non-negative and less than n, the null-terminated string has been fully and successfully printed.
Definition at line 1572 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsnprintf(s, n, format, args);
     va_end(args);
     return ret;
 }
References args, format(), n, s, va_end, va_start, and vsnprintf().
sprintf()
int sprintf (char * s, const char * format, ...)
An implementation of the C standard's sprintf/vsprintf
Note
For security considerations (the potential for exceeding the buffer bounds), please consider using the size-constrained variant, snprintf / vsnprintf , instead.
Parameters
s An array in which to store the formatted string. It must be large enough to fit the formatted output!
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 1563 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsprintf(s, format, args);
     va_end(args);
     return ret;
 }
References args, format(), s, va_end, va_start, and vsprintf().
Referenced by _rl_get_string_variable_value(), action_compat(), add_to_index(), archivejoin(), arith_apply(), awk_printf(), cal_main(), cdesc(), chksum_and_xwrite_tar_header(), chs_string11(), collect_tv(), com_list(), com_view(), conf_get_default_confname(), conf_write(), conspy_main(), conv_c(), cprintf(), create_directory(), create_file(), cttyhack_main(), curtime(), date_main(), decode_prompt_string(), dfallback(), display_process_list(), dump_procs(), dump_tree(), ecvt(), ether_ntoa_r(), execute_all(), expand_variable(), expand_vars_to_list(), expbackq(), expr_print(), fcvt(), fill_envp(), filter_rename_config(), fmt_time_human_30nul(), format_line(), gather_options_str(), gcvt(), genformat(), get_local_var_value(), get_next_free_loop(), get_old_name(), get_prompt(), handle_size_or_mdtm(), header_verbose_list(), hist_inittime(), human_time(), i2c_dev_open(), idle_string(), init_exec(), init_main_window(), init_signames(), initialize_siglist(), initialize_signames(), iso_8601_2000_year(), j_strsignal(), list_devs_in_proc_partititons(), list_table(), ll_type_n2a(), locale_charset(), log_locally(), logger_main(), losetup_main(), lsof_main(), mailstat(), main(), maybe_up_new_iface(), mkfs_vfat_main(), mkptr4(), mount_namespaces(), nbdclient_main(), openvt_main(), out_args(), parse(), parse_conf(), parse_conf_file(), pid_is_exec(), pid_is_name(), pid_is_user(), place_cursor(), powertop_main(), print_addrinfo(), process_irq_counts(), process_timer_stats(), procps_scan(), ps_main(), purge_package(), push_filename(), pwdx_main(), raise_error_unexpected_syntax(), re_execute_shell(), read_cmdline(), read_cstate_counts(), remove_package(), rfkill_main(), rl_display_search(), rl_invoking_keyseqs_in_map(), rl_message(), rl_redisplay(), rtnl_tab_initialize(), scan_request(), scan_table(), send_file_and_exit(), send_headers(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), sh_set_lines_and_columns(), sha256crypt(), sha512crypt(), sha_crypt(), shell_version_string(), show_entry(), sprint_nip(), sprint_nip6(), strerror(), strftime(), string_var_assignment(), sym_validate_range(), timestamp_and_log(), tokname(), ttyname_r(), ubi_get_volid_by_name(), ubi_tools_main(), unshare_main(), UNSPEC_print(), unzip_main(), update_status(), volume_id_set_uuid(), wget_main(), write_helpfiles(), write_longdocs(), write_old_sd_name(), writeheader(), xmalloc_optname_optval(), and xxd_main().
sscanf()
int sscanf (const char * __restrict, const char * __restrict, ...)
Definition at line 125 of file file.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsscanf(s, format, args);
     va_end(args);
     return ret;
 }
tmpfile()
FILE* tmpfile (void)
Definition at line 8 of file tmpfile.c.
 {
     char s[] = "/tmp/tmpfile_XXXXXX";
     int fd;
     FILE *f;
     int try;
     for (try=0; try<MAXTRIES; try++) {
         __randname(s+13);
         fd = sys_open(s, O_RDWR|O_CREAT|O_EXCL, 0600);
         if (fd >= 0) {
 #ifdef SYS_unlink
             __syscall(SYS_unlink, s);
 #else
             __syscall(SYS_unlinkat, AT_FDCWD, s, 0);
 #endif
             f = __fdopen(fd, "w+");
             if (!f) __syscall(SYS_close, fd);
             return f;
         }
     }
     return 0;
 }
References __fdopen(), __randname(), __syscall, AT_FDCWD, f, fd, MAXTRIES, O_CREAT, O_EXCL, O_RDWR, s, and sys_open.
tmpnam()
char* tmpnam (char * buf)
Definition at line 11 of file tmpnam.c.
 {
     static char internal[L_tmpnam];
     char s[] = "/tmp/tmpnam_XXXXXX";
     int try;
     int r;
     for (try=0; try<MAXTRIES; try++) {
         __randname(s+12);
 #ifdef SYS_readlink
         r = __syscall(SYS_readlink, s, (char[1]){0}, 1);
 #else
         r = __syscall(SYS_readlinkat, AT_FDCWD, s, (char[1]){0}, 1);
 #endif
         if (r == -ENOENT) return strcpy(buf ? buf : internal, s);
     }
     return 0;
 }
References __randname(), __syscall, AT_FDCWD, buf, ENOENT, L_tmpnam, MAXTRIES, s, and strcpy().
ungetc()
int ungetc (int c, FILE * f)
Definition at line 3 of file ungetc.c.
 {
     if (c == EOF) return c;
     FLOCK(f);
     if (!f->rpos) __toread(f);
     if (!f->rpos || f->rpos <= f->buf - UNGET) {
         FUNLOCK(f);
         return EOF;
     }
     *--f->rpos = c;
     f->flags &= ~F_EOF;
     FUNLOCK(f);
     return (unsigned char)c;
 }
References __toread(), _IO_FILE::buf, c, EOF, f, F_EOF, _IO_FILE::flags, FLOCK, FUNLOCK, _IO_FILE::rpos, and UNGET.
Referenced by __fgetwc_unlocked_internal(), fgetln(), get_charset_aliases(), and get_next_line().
vfprintf()
int vfprintf (FILE * __restrict, const char * __restrict, __isoc_va_list)
vfscanf()
int vfscanf (FILE * __restrict, const char * __restrict, __isoc_va_list)
Referenced by fscanf(), vscanf(), and vsscanf().
vprintf()
int vprintf (const char * __restrict, __isoc_va_list)
vscanf()
int vscanf (const char * __restrict, __isoc_va_list)
Referenced by scanf().
vsnprintf()
int vsnprintf (char * __restrict, size_t , const char * __restrict, __isoc_va_list)
vsprintf()
int vsprintf (char * __restrict, const char * __restrict, __isoc_va_list)
vsscanf()
int vsscanf (const char * __restrict, const char * __restrict, __isoc_va_list)
Variable Documentation
stderr
FILE* const stderr extern
Definition at line 11 of file file.c.
stdin
FILE* const stdin extern
Definition at line 9 of file file.c.
stdout
FILE* const stdout extern
Definition at line 10 of file file.c.