Fennix: Userspace/musl/include/sys/timex.h File Reference
timex.h File Reference
#include <bits/alltypes.h>
#include <sys/time.h>
Data Structures
struct ntptimeval
struct timex
Macros
#define __NEED_clockid_t
#define ADJ_OFFSET 0x0001
#define ADJ_FREQUENCY 0x0002
#define ADJ_MAXERROR 0x0004
#define ADJ_ESTERROR 0x0008
#define ADJ_STATUS 0x0010
#define ADJ_TIMECONST 0x0020
#define ADJ_TAI 0x0080
#define ADJ_SETOFFSET 0x0100
#define ADJ_MICRO 0x1000
#define ADJ_NANO 0x2000
#define ADJ_TICK 0x4000
#define ADJ_OFFSET_SINGLESHOT 0x8001
#define ADJ_OFFSET_SS_READ 0xa001
#define MOD_OFFSET ADJ_OFFSET
#define MOD_FREQUENCY ADJ_FREQUENCY
#define MOD_MAXERROR ADJ_MAXERROR
#define MOD_ESTERROR ADJ_ESTERROR
#define MOD_STATUS ADJ_STATUS
#define MOD_TIMECONST ADJ_TIMECONST
#define MOD_CLKB ADJ_TICK
#define MOD_CLKA ADJ_OFFSET_SINGLESHOT
#define MOD_TAI ADJ_TAI
#define MOD_MICRO ADJ_MICRO
#define MOD_NANO ADJ_NANO
#define STA_PLL 0x0001
#define STA_PPSFREQ 0x0002
#define STA_PPSTIME 0x0004
#define STA_FLL 0x0008
#define STA_INS 0x0010
#define STA_DEL 0x0020
#define STA_UNSYNC 0x0040
#define STA_FREQHOLD 0x0080
#define STA_PPSSIGNAL 0x0100
#define STA_PPSJITTER 0x0200
#define STA_PPSWANDER 0x0400
#define STA_PPSERROR 0x0800
#define STA_CLOCKERR 0x1000
#define STA_NANO 0x2000
#define STA_MODE 0x4000
#define STA_CLK 0x8000
#define STA_RONLY
#define TIME_OK 0
#define TIME_INS 1
#define TIME_DEL 2
#define TIME_OOP 3
#define TIME_WAIT 4
#define TIME_ERROR 5
#define TIME_BAD TIME_ERROR
#define MAXTC 6
Functions
int adjtimex (struct timex *)
int clock_adjtime (clockid_t, struct timex *)
Data Structure Documentation
ntptimeval
struct ntptimeval
Definition at line 14 of file timex.h.
Data Fields
long esterror
long maxerror
struct timeval time
timex
struct timex
Definition at line 19 of file timex.h.
Data Fields
int __padding[11]
long calcnt
long constant
long errcnt
long esterror
long freq
long jitcnt
long jitter
long maxerror
unsigned modes
long offset
long ppsfreq
long precision
int shift
long stabil
int status
long stbcnt
int tai
long tick
struct timeval time
long tolerance
Macro Definition Documentation
__NEED_clockid_t
#define __NEED_clockid_t
Definition at line 8 of file timex.h.
ADJ_ESTERROR
#define ADJ_ESTERROR 0x0008
Definition at line 35 of file timex.h.
ADJ_FREQUENCY
#define ADJ_FREQUENCY 0x0002
Definition at line 33 of file timex.h.
ADJ_MAXERROR
#define ADJ_MAXERROR 0x0004
Definition at line 34 of file timex.h.
ADJ_MICRO
#define ADJ_MICRO 0x1000
Definition at line 40 of file timex.h.
ADJ_NANO
#define ADJ_NANO 0x2000
Definition at line 41 of file timex.h.
ADJ_OFFSET
#define ADJ_OFFSET 0x0001
Definition at line 32 of file timex.h.
ADJ_OFFSET_SINGLESHOT
#define ADJ_OFFSET_SINGLESHOT 0x8001
Definition at line 43 of file timex.h.
ADJ_OFFSET_SS_READ
#define ADJ_OFFSET_SS_READ 0xa001
Definition at line 44 of file timex.h.
ADJ_SETOFFSET
#define ADJ_SETOFFSET 0x0100
Definition at line 39 of file timex.h.
ADJ_STATUS
#define ADJ_STATUS 0x0010
Definition at line 36 of file timex.h.
ADJ_TAI
#define ADJ_TAI 0x0080
Definition at line 38 of file timex.h.
ADJ_TICK
#define ADJ_TICK 0x4000
Definition at line 42 of file timex.h.
ADJ_TIMECONST
#define ADJ_TIMECONST 0x0020
Definition at line 37 of file timex.h.
MAXTC
#define MAXTC 6
Definition at line 89 of file timex.h.
MOD_CLKA
#define MOD_CLKA ADJ_OFFSET_SINGLESHOT
Definition at line 53 of file timex.h.
MOD_CLKB
#define MOD_CLKB ADJ_TICK
Definition at line 52 of file timex.h.
MOD_ESTERROR
#define MOD_ESTERROR ADJ_ESTERROR
Definition at line 49 of file timex.h.
MOD_FREQUENCY
#define MOD_FREQUENCY ADJ_FREQUENCY
Definition at line 47 of file timex.h.
MOD_MAXERROR
#define MOD_MAXERROR ADJ_MAXERROR
Definition at line 48 of file timex.h.
MOD_MICRO
#define MOD_MICRO ADJ_MICRO
Definition at line 55 of file timex.h.
MOD_NANO
#define MOD_NANO ADJ_NANO
Definition at line 56 of file timex.h.
MOD_OFFSET
#define MOD_OFFSET ADJ_OFFSET
Definition at line 46 of file timex.h.
MOD_STATUS
#define MOD_STATUS ADJ_STATUS
Definition at line 50 of file timex.h.
MOD_TAI
#define MOD_TAI ADJ_TAI
Definition at line 54 of file timex.h.
MOD_TIMECONST
#define MOD_TIMECONST ADJ_TIMECONST
Definition at line 51 of file timex.h.
STA_CLK
#define STA_CLK 0x8000
Definition at line 76 of file timex.h.
STA_CLOCKERR
#define STA_CLOCKERR 0x1000
Definition at line 73 of file timex.h.
STA_DEL
#define STA_DEL 0x0020
Definition at line 64 of file timex.h.
STA_FLL
#define STA_FLL 0x0008
Definition at line 61 of file timex.h.
STA_FREQHOLD
#define STA_FREQHOLD 0x0080
Definition at line 66 of file timex.h.
STA_INS
#define STA_INS 0x0010
Definition at line 63 of file timex.h.
STA_MODE
#define STA_MODE 0x4000
Definition at line 75 of file timex.h.
STA_NANO
#define STA_NANO 0x2000
Definition at line 74 of file timex.h.
STA_PLL
#define STA_PLL 0x0001
Definition at line 58 of file timex.h.
STA_PPSERROR
#define STA_PPSERROR 0x0800
Definition at line 71 of file timex.h.
STA_PPSFREQ
#define STA_PPSFREQ 0x0002
Definition at line 59 of file timex.h.
STA_PPSJITTER
#define STA_PPSJITTER 0x0200
Definition at line 69 of file timex.h.
STA_PPSSIGNAL
#define STA_PPSSIGNAL 0x0100
Definition at line 68 of file timex.h.
STA_PPSTIME
#define STA_PPSTIME 0x0004
Definition at line 60 of file timex.h.
STA_PPSWANDER
#define STA_PPSWANDER 0x0400
Definition at line 70 of file timex.h.
STA_RONLY
#define STA_RONLY
Value:
    (STA_PPSSIGNAL | STA_PPSJITTER | STA_PPSWANDER | \
    STA_PPSERROR | STA_CLOCKERR | STA_NANO | STA_MODE | STA_CLK)
Definition at line 78 of file timex.h.
STA_UNSYNC
#define STA_UNSYNC 0x0040
Definition at line 65 of file timex.h.
TIME_BAD
#define TIME_BAD TIME_ERROR
Definition at line 87 of file timex.h.
TIME_DEL
#define TIME_DEL 2
Definition at line 83 of file timex.h.
TIME_ERROR
#define TIME_ERROR 5
Definition at line 86 of file timex.h.
TIME_INS
#define TIME_INS 1
Definition at line 82 of file timex.h.
TIME_OK
#define TIME_OK 0
Definition at line 81 of file timex.h.
TIME_OOP
#define TIME_OOP 3
Definition at line 84 of file timex.h.
TIME_WAIT
#define TIME_WAIT 4
Definition at line 85 of file timex.h.
Function Documentation
adjtimex()
int adjtimex (struct timex * tx)
Definition at line 4 of file adjtimex.c.
 {
     return clock_adjtime(CLOCK_REALTIME, tx);
 }
References clock_adjtime().
Referenced by adjtime(), adjtimex_main(), and update_local_clock().
clock_adjtime()
int clock_adjtime (clockid_t clock_id, struct timex * utx)
Definition at line 37 of file clock_adjtime.c.
 {
     int r = -ENOSYS;
 #ifdef SYS_clock_adjtime64
     struct ktimex64 ktx = {
         .modes = utx->modes,
         .offset = utx->offset,
         .freq = utx->freq,
         .maxerror = utx->maxerror,
         .esterror = utx->esterror,
         .status = utx->status,
         .constant = utx->constant,
         .precision = utx->precision,
         .tolerance = utx->tolerance,
         .time_sec = utx->time.tv_sec,
         .time_usec = utx->time.tv_usec,
         .tick = utx->tick,
         .ppsfreq = utx->ppsfreq,
         .jitter = utx->jitter,
         .shift = utx->shift,
         .stabil = utx->stabil,
         .jitcnt = utx->jitcnt,
         .calcnt = utx->calcnt,
         .errcnt = utx->errcnt,
         .stbcnt = utx->stbcnt,
         .tai = utx->tai,
     };
     r = __syscall(SYS_clock_adjtime64, clock_id, &ktx);
     if (r>=0) {
         utx->modes = ktx.modes;
         utx->offset = ktx.offset;
         utx->freq = ktx.freq;
         utx->maxerror = ktx.maxerror;
         utx->esterror = ktx.esterror;
         utx->status = ktx.status;
         utx->constant = ktx.constant;
         utx->precision = ktx.precision;
         utx->tolerance = ktx.tolerance;
         utx->time.tv_sec = ktx.time_sec;
         utx->time.tv_usec = ktx.time_usec;
         utx->tick = ktx.tick;
         utx->ppsfreq = ktx.ppsfreq;
         utx->jitter = ktx.jitter;
         utx->shift = ktx.shift;
         utx->stabil = ktx.stabil;
         utx->jitcnt = ktx.jitcnt;
         utx->calcnt = ktx.calcnt;
         utx->errcnt = ktx.errcnt;
         utx->stbcnt = ktx.stbcnt;
         utx->tai = ktx.tai;
     }
     if (SYS_clock_adjtime == SYS_clock_adjtime64 || r!=-ENOSYS)
         return __syscall_ret(r);
     if ((utx->modes & ADJ_SETOFFSET) && !IS32BIT(utx->time.tv_sec))
         return __syscall_ret(-ENOTSUP);
 #endif
     if (sizeof(time_t) > sizeof(long)) {
         struct ktimex ktx = {
             .modes = utx->modes,
             .offset = utx->offset,
             .freq = utx->freq,
             .maxerror = utx->maxerror,
             .esterror = utx->esterror,
             .status = utx->status,
             .constant = utx->constant,
             .precision = utx->precision,
             .tolerance = utx->tolerance,
             .time_sec = utx->time.tv_sec,
             .time_usec = utx->time.tv_usec,
             .tick = utx->tick,
             .ppsfreq = utx->ppsfreq,
             .jitter = utx->jitter,
             .shift = utx->shift,
             .stabil = utx->stabil,
             .jitcnt = utx->jitcnt,
             .calcnt = utx->calcnt,
             .errcnt = utx->errcnt,
             .stbcnt = utx->stbcnt,
             .tai = utx->tai,
         };
 #ifdef SYS_adjtimex
         if (clock_id==CLOCK_REALTIME) r = __syscall(SYS_adjtimex, &ktx);
         else
 #endif
         r = __syscall(SYS_clock_adjtime, clock_id, &ktx);
         if (r>=0) {
             utx->modes = ktx.modes;
             utx->offset = ktx.offset;
             utx->freq = ktx.freq;
             utx->maxerror = ktx.maxerror;
             utx->esterror = ktx.esterror;
             utx->status = ktx.status;
             utx->constant = ktx.constant;
             utx->precision = ktx.precision;
             utx->tolerance = ktx.tolerance;
             utx->time.tv_sec = ktx.time_sec;
             utx->time.tv_usec = ktx.time_usec;
             utx->tick = ktx.tick;
             utx->ppsfreq = ktx.ppsfreq;
             utx->jitter = ktx.jitter;
             utx->shift = ktx.shift;
             utx->stabil = ktx.stabil;
             utx->jitcnt = ktx.jitcnt;
             utx->calcnt = ktx.calcnt;
             utx->errcnt = ktx.errcnt;
             utx->stbcnt = ktx.stbcnt;
             utx->tai = ktx.tai;
         }
         return __syscall_ret(r);
     }
 #ifdef SYS_adjtimex
     if (clock_id==CLOCK_REALTIME) return syscall(SYS_adjtimex, utx);
 #endif
     return syscall(SYS_clock_adjtime, clock_id, utx);
 }
References __syscall, __syscall_ret(), ADJ_SETOFFSET, timex::calcnt, ktimex64::calcnt, ktimex::calcnt, timex::constant, ktimex64::constant, ktimex::constant, ENOSYS, ENOTSUP, timex::errcnt, ktimex64::errcnt, ktimex::errcnt, timex::esterror, ktimex64::esterror, ktimex::esterror, timex::freq, ktimex64::freq, ktimex::freq, IS32BIT, timex::jitcnt, ktimex64::jitcnt, ktimex::jitcnt, timex::jitter, ktimex64::jitter, ktimex::jitter, timex::maxerror, ktimex64::maxerror, ktimex::maxerror, timex::modes, ktimex64::modes, ktimex::modes, timex::offset, ktimex64::offset, ktimex::offset, timex::ppsfreq, ktimex64::ppsfreq, ktimex::ppsfreq, timex::precision, ktimex64::precision, ktimex::precision, timex::shift, ktimex64::shift, ktimex::shift, timex::stabil, ktimex64::stabil, ktimex::stabil, timex::status, ktimex64::status, ktimex::status, timex::stbcnt, ktimex64::stbcnt, ktimex::stbcnt, SYS_clock_adjtime, SYS_clock_adjtime64, syscall(), timex::tai, ktimex64::tai, ktimex::tai, timex::tick, ktimex64::tick, ktimex::tick, timex::time, ktimex64::time_sec, ktimex::time_sec, ktimex64::time_usec, ktimex::time_usec, timex::tolerance, ktimex64::tolerance, ktimex::tolerance, timeval::tv_sec, and timeval::tv_usec.
Referenced by __clock_adjtime32(), and adjtimex().