Fennix Userspace: Userspace/mlibc/tests/posix/sigaltstack.c File Reference
sigaltstack.c File Reference
#include <assert.h>
#include <setjmp.h>
#include <signal.h>
#include <stdlib.h>
Functions
static void sig_handler (int sig, siginfo_t *info, void *ctx)
int main ()
Variables
static jmp_buf env
static char * sigStack
Function Documentation
main()
int main (void)
Definition at line 17 of file sigaltstack.c.
            {
     if (setjmp(env)) {
         free(sigStack);
         return 0;
     }
     sigStack = malloc(SIGSTKSZ);
     stack_t ss;
     ss.ss_sp = sigStack;
     ss.ss_size = SIGSTKSZ;
     ss.ss_flags = 0;
     assert(!sigaltstack(&ss, NULL));
     struct sigaction sa;
     sigemptyset(&sa.sa_mask);
     sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
     sa.sa_sigaction = sig_handler;
     assert(!sigaction(SIGSEGV, &sa, NULL));
     // This is used to trash the stack to ensure sigaltstack actually switched stacks.
 #if defined(__x86_64__)
     asm volatile ("mov $0, %rsp\n"
             "\t" "push $0");
 #elif defined(__aarch64__)
     asm volatile ("mov sp, %0\n"
             "\t" "stp x0, x1, [sp, #-16]!" :: "r"((uint64_t)0));
 #elif defined(__riscv) && __riscv_xlen == 64
     asm volatile ("li sp, 0\n"
             "\t" "sd zero, 0(sp)");
 #else
 #   error Unknown architecture
 #endif
 }
References assert, env, free, malloc, NULL, sigaction::sa_flags, sigaction::sa_mask, SA_ONSTACK, sigaction::sa_sigaction, SA_SIGINFO, setjmp, sig_handler(), sigaction(), sigaltstack(), sigemptyset, SIGSEGV, sigStack, SIGSTKSZ, __stack::ss_flags, __stack::ss_size, and __stack::ss_sp.
sig_handler()
static void sig_handler (int sig, siginfo_t * info, void * ctx) static
Definition at line 9 of file sigaltstack.c.
{
     (void)sig;
     (void)info;
     (void)ctx;
     longjmp(env, 1);
 }
References env, and longjmp().
Referenced by main().
Variable Documentation
env
jmp_buf env static
Definition at line 6 of file sigaltstack.c.
Referenced by mlibc::envEnabled(), execute_shell_script(), getenv(), initialize_shell_variables(), interpreterMain(), main(), perl_main(), shell_execve(), and sig_handler().
sigStack
char* sigStack static
Definition at line 7 of file sigaltstack.c.
Referenced by main().