Fennix Userspace: Userspace/musl/include/glob.h File Reference
glob.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct glob_t
Macros
#define __NEED_size_t
#define GLOB_ERR 0x01
#define GLOB_MARK 0x02
#define GLOB_NOSORT 0x04
#define GLOB_DOOFFS 0x08
#define GLOB_NOCHECK 0x10
#define GLOB_APPEND 0x20
#define GLOB_NOESCAPE 0x40
#define GLOB_PERIOD 0x80
#define GLOB_TILDE 0x1000
#define GLOB_TILDE_CHECK 0x4000
#define GLOB_NOSPACE 1
#define GLOB_ABORTED 2
#define GLOB_NOMATCH 3
#define GLOB_NOSYS 4
Functions
int glob (const char *__restrict, int, int(*)(const char *, int), glob_t *__restrict)
void globfree (glob_t *)
Data Structure Documentation
glob_t
struct glob_t
Definition at line 14 of file glob.h.
Data Fields
int __dummy1
void * __dummy2[5]
size_t gl_offs
size_t gl_pathc
char ** gl_pathv
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file glob.h.
GLOB_ABORTED
#define GLOB_ABORTED 2
Definition at line 38 of file glob.h.
GLOB_APPEND
#define GLOB_APPEND 0x20
Definition at line 30 of file glob.h.
GLOB_DOOFFS
#define GLOB_DOOFFS 0x08
Definition at line 28 of file glob.h.
GLOB_ERR
#define GLOB_ERR 0x01
Definition at line 25 of file glob.h.
GLOB_MARK
#define GLOB_MARK 0x02
Definition at line 26 of file glob.h.
GLOB_NOCHECK
#define GLOB_NOCHECK 0x10
Definition at line 29 of file glob.h.
GLOB_NOESCAPE
#define GLOB_NOESCAPE 0x40
Definition at line 31 of file glob.h.
GLOB_NOMATCH
#define GLOB_NOMATCH 3
Definition at line 39 of file glob.h.
GLOB_NOSORT
#define GLOB_NOSORT 0x04
Definition at line 27 of file glob.h.
GLOB_NOSPACE
#define GLOB_NOSPACE 1
Definition at line 37 of file glob.h.
GLOB_NOSYS
#define GLOB_NOSYS 4
Definition at line 40 of file glob.h.
GLOB_PERIOD
#define GLOB_PERIOD 0x80
Definition at line 32 of file glob.h.
GLOB_TILDE
#define GLOB_TILDE 0x1000
Definition at line 34 of file glob.h.
GLOB_TILDE_CHECK
#define GLOB_TILDE_CHECK 0x4000
Definition at line 35 of file glob.h.
Function Documentation
glob()
int glob (const char * __restrict, int , int(*)(const char *, int) , glob_t * __restrict)
Referenced by expandmeta(), and perform_glob().
globfree()
void globfree (glob_t * g)
Definition at line 300 of file glob.c.
 {
     size_t i;
     for (i=0; i<g->gl_pathc; i++)
         free(g->gl_pathv[g->gl_offs + i] - offsetof(struct match, name));
     free(g->gl_pathv);
     g->gl_pathc = 0;
     g->gl_pathv = NULL;
 }
References free, g, i, match::name, NULL, and offsetof.
Referenced by expandmeta(), and perform_glob().