Fennix: Drivers/misc/vmware/main.c File Reference
main.c File Reference
#include <driver.h>
#include <errno.h>
#include <input.h>
#include <regs.h>
#include <base.h>
#include <aip.h>
#include <vm.h>
#include <io.h>
Data Structures
struct VMwareCommand
struct ToolboxContext
union VMwareCommand.__unnamed1262__
union VMwareCommand.__unnamed1264__
union VMwareCommand.__unnamed1266__
union VMwareCommand.__unnamed1268__
Macros
#define VMWARE_MAGIC 0x564D5868
#define VMWARE_PORT 0x5658
#define VMWARE_PORTHB 0x5659
#define VMWARE_HYPERVISOR_HB 0x00000000
#define VMWARE_HYPERVISOR_OUT 0x00000001
#define CMD_GETVERSION 0xA
#define CMD_MESSAGE 0x1E
#define CMD_ABSPOINTER_DATA 0x27
#define CMD_ABSPOINTER_STATUS 0x28
#define CMD_ABSPOINTER_COMMAND 0x29
#define ABSPOINTER_ENABLE 0x45414552
#define ABSPOINTER_RELATIVE 0xF5
#define ABSPOINTER_ABSOLUTE 0x53424152
#define MESSAGE_RPCI 0x49435052
#define MESSAGE_TCLO 0x4f4c4354
#define FLAG_COOKIE 0x80000000
#define ToMsg(x) ((x) << 16 | CMD_MESSAGE)
#define HighWord(x) ((x & 0xFFFF0000) >> 16)
#define MESSAGE_HB_MSG 0
#define MESSAGE_OPEN_CHANNEL ToMsg(MSG_OPEN)
#define MESSAGE_CLOSE_CHANNEL ToMsg(MSG_CLOSE)
#define MESSAGE_SEND_SIZE ToMsg(MSG_SENDSIZE)
#define MESSAGE_SEND_PAYLOAD ToMsg(MSG_SENDPAYLOAD)
#define MESSAGE_RECV_SIZE ToMsg(MSG_RECVSIZE)
#define MESSAGE_RECV_PAYLOAD ToMsg(MSG_RECVPAYLOAD)
#define MESSAGE_RECV_STATUS ToMsg(MSG_RECVSTATUS)
#define VM_PORT(cmd, in_ebx, isi, idi, flags, magic, ax, bx, cx, dx, si, di)
#define VM_PORT_HB_OUT(cmd, in_ecx, isi, idi, flags, magic, bp, ax, bx, cx, dx, si, di)
#define VM_PORT_HB_IN(cmd, in_ecx, isi, idi, flags, magic, bp, ax, bx, cx, dx, si, di)
Enumerations
enum RPCMessages {
MSG_OPEN , MSG_SENDSIZE , MSG_SENDPAYLOAD , MSG_RECVSIZE ,
MSG_RECVPAYLOAD , MSG_RECVSTATUS , MSG_CLOSE
}
enum RPCStatus { STATUS_SUCCESS = 0x1 , STATUS_DORECV = 0x2 , STATUS_CPT = 0x10 , STATUS_HB = 0x80 }
Functions
static int OpenMessageChannel (ToolboxContext *ctx, uint32_t Protocol)
static void MessageClose (ToolboxContext *ctx)
static uintptr_t MessageSendHB (ToolboxContext *ctx, const char *Message)
static uintptr_t MessageSendLB (ToolboxContext *ctx, const char *Message)
static uintptr_t MessageReceiveHB (ToolboxContext *ctx, char *Buffer, size_t BufferSize)
static uintptr_t MessageReceiveLB (ToolboxContext *ctx, char *Buffer, size_t BufferSize)
static int MessageSend (ToolboxContext *ctx, const char *Message)
static int MessageReceive (ToolboxContext *ctx, char **Buffer, size_t *BufferSize)
static int SendRPCI (ToolboxContext *, const char *Request)
int MsgEqual (const char *haystack, const char *needle)
static int DisplayGetSize (ToolboxContext *ctx)
void DisplayScaleThread ()
void CommandSend (VMwareCommand *cmd)
void Absolute ()
void Relative ()
void InterruptHandler (TrapFrame *)
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
int DriverProbe ()
DriverInfo ("vmware", "VMware Tools Driver", "EnderIce2", "0.1", "GPLv3")
Variables
dev_t MouseDevID = -1
pid_t dst_id = -1
ToolboxContext * tb_ctx = NULL
bool ToolboxSupported = false
Data Structure Documentation
VMwareCommand
struct VMwareCommand
Definition at line 46 of file main.c.
Data Fields
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
uint32_t di
uint32_t si
ToolboxContext
struct ToolboxContext
Definition at line 176 of file main.c.
Data Fields
uint16_t ChannelID
uint32_t CookieHigh
uint32_t CookieLow
int TCLOChannel
VMwareCommand.__unnamed1262__
union VMwareCommand.__unnamed1262__
Definition at line 48 of file main.c.
Data Fields
uint32_t ax
uint32_t magic
VMwareCommand.__unnamed1264__
union VMwareCommand.__unnamed1264__
Definition at line 53 of file main.c.
Data Fields
uint32_t bx
size_t size
VMwareCommand.__unnamed1266__
union VMwareCommand.__unnamed1266__
Definition at line 58 of file main.c.
Data Fields
uint16_t command
uint32_t cx
VMwareCommand.__unnamed1268__
union VMwareCommand.__unnamed1268__
Definition at line 63 of file main.c.
Data Fields
uint32_t dx
uint16_t port
Macro Definition Documentation
ABSPOINTER_ABSOLUTE
#define ABSPOINTER_ABSOLUTE 0x53424152
Definition at line 88 of file main.c.
ABSPOINTER_ENABLE
#define ABSPOINTER_ENABLE 0x45414552
Definition at line 86 of file main.c.
ABSPOINTER_RELATIVE
#define ABSPOINTER_RELATIVE 0xF5
Definition at line 87 of file main.c.
CMD_ABSPOINTER_COMMAND
#define CMD_ABSPOINTER_COMMAND 0x29
Definition at line 84 of file main.c.
CMD_ABSPOINTER_DATA
#define CMD_ABSPOINTER_DATA 0x27
Definition at line 82 of file main.c.
CMD_ABSPOINTER_STATUS
#define CMD_ABSPOINTER_STATUS 0x28
Definition at line 83 of file main.c.
CMD_GETVERSION
#define CMD_GETVERSION 0xA
Definition at line 80 of file main.c.
CMD_MESSAGE
#define CMD_MESSAGE 0x1E
Definition at line 81 of file main.c.
FLAG_COOKIE
#define FLAG_COOKIE 0x80000000
Definition at line 93 of file main.c.
HighWord
#define HighWord (x) ((x & 0xFFFF0000) >> 16)
Definition at line 96 of file main.c.
MESSAGE_CLOSE_CHANNEL
#define MESSAGE_CLOSE_CHANNEL ToMsg(MSG_CLOSE)
Definition at line 101 of file main.c.
MESSAGE_HB_MSG
#define MESSAGE_HB_MSG 0
Definition at line 98 of file main.c.
MESSAGE_OPEN_CHANNEL
#define MESSAGE_OPEN_CHANNEL ToMsg(MSG_OPEN)
Definition at line 100 of file main.c.
MESSAGE_RECV_PAYLOAD
#define MESSAGE_RECV_PAYLOAD ToMsg(MSG_RECVPAYLOAD)
Definition at line 107 of file main.c.
MESSAGE_RECV_SIZE
#define MESSAGE_RECV_SIZE ToMsg(MSG_RECVSIZE)
Definition at line 106 of file main.c.
MESSAGE_RECV_STATUS
#define MESSAGE_RECV_STATUS ToMsg(MSG_RECVSTATUS)
Definition at line 108 of file main.c.
MESSAGE_RPCI
#define MESSAGE_RPCI 0x49435052
Definition at line 90 of file main.c.
MESSAGE_SEND_PAYLOAD
#define MESSAGE_SEND_PAYLOAD ToMsg(MSG_SENDPAYLOAD)
Definition at line 104 of file main.c.
MESSAGE_SEND_SIZE
#define MESSAGE_SEND_SIZE ToMsg(MSG_SENDSIZE)
Definition at line 103 of file main.c.
MESSAGE_TCLO
#define MESSAGE_TCLO 0x4f4c4354
Definition at line 91 of file main.c.
ToMsg
#define ToMsg (x) ((x) << 16 | CMD_MESSAGE)
Definition at line 95 of file main.c.
VM_PORT
#define VM_PORT (cmd, in_ebx, isi, idi, flags, magic, ax, bx, cx, dx, si, di)
Value:
    __asm__ __volatile__("movw $0x5658, %%dx\n" \
                         "inl %%dx, %%eax\n"    \
                         : "=a"(ax),            \
                           "=b"(bx),            \
                           "=c"(cx),            \
                           "=d"(dx),            \
                           "=S"(si),            \
                           "=D"(di)             \
                         : "a"(magic),          \
                           "b"(in_ebx),         \
                           "c"(cmd),            \
                           "d"(flags),          \
                           "S"(isi),            \
                           "D"(idi) : "memory")
Definition at line 110 of file main.c.
VM_PORT_HB_IN
#define VM_PORT_HB_IN (cmd, in_ecx, isi, idi, flags, magic, bp, ax, bx, cx, dx, si, di)
Value:
    __asm__ __volatile__("push %%rbp\n"         \
                         "mov %12, %%rbp\n"     \
                         "movw $0x5659, %%dx\n" \
                         "rep insb\n"           \
                         "pop %%rbp\n"          \
                         : "=a"(ax),            \
                           "=b"(bx),            \
                           "=c"(cx),            \
                           "=d"(dx),            \
                           "=S"(si),            \
                           "=D"(di)             \
                         : "a"(magic),          \
                           "b"(cmd),            \
                           "c"(in_ecx),         \
                           "d"(flags),          \
                           "S"(isi),            \
                           "D"(idi),            \
                           "r"(bp) : "memory", "cc")
Definition at line 150 of file main.c.
VM_PORT_HB_OUT
#define VM_PORT_HB_OUT (cmd, in_ecx, isi, idi, flags, magic, bp, ax, bx, cx, dx, si, di)
Value:
    __asm__ __volatile__("push %%rbp\n"         \
                         "mov %12, %%rbp\n"     \
                         "movw $0x5659, %%dx\n" \
                         "rep outsb\n"          \
                         "pop %%rbp\n"          \
                         : "=a"(ax),            \
                           "=b"(bx),            \
                           "=c"(cx),            \
                           "=d"(dx),            \
                           "=S"(si),            \
                           "=D"(di)             \
                         : "a"(magic),          \
                           "b"(cmd),            \
                           "c"(in_ecx),         \
                           "d"(flags),          \
                           "S"(isi),            \
                           "D"(idi),            \
                           "r"(bp) : "memory", "cc")
Definition at line 128 of file main.c.
VMWARE_HYPERVISOR_HB
#define VMWARE_HYPERVISOR_HB 0x00000000
Definition at line 77 of file main.c.
VMWARE_HYPERVISOR_OUT
#define VMWARE_HYPERVISOR_OUT 0x00000001
Definition at line 78 of file main.c.
VMWARE_MAGIC
#define VMWARE_MAGIC 0x564D5868
Definition at line 72 of file main.c.
VMWARE_PORT
#define VMWARE_PORT 0x5658
Definition at line 74 of file main.c.
VMWARE_PORTHB
#define VMWARE_PORTHB 0x5659
Definition at line 75 of file main.c.
Enumeration Type Documentation
RPCMessages
enum RPCMessages
Enumerator
MSG_OPEN
MSG_SENDSIZE
MSG_SENDPAYLOAD
MSG_RECVSIZE
MSG_RECVPAYLOAD
MSG_RECVSTATUS
MSG_CLOSE
Definition at line 27 of file main.c.
 {
     MSG_OPEN,
     MSG_SENDSIZE,
     MSG_SENDPAYLOAD,
     MSG_RECVSIZE,
     MSG_RECVPAYLOAD,
     MSG_RECVSTATUS,
     MSG_CLOSE,
 };
RPCStatus
enum RPCStatus
Enumerator
STATUS_SUCCESS
STATUS_DORECV
STATUS_CPT
STATUS_HB
Definition at line 38 of file main.c.
 {
     STATUS_SUCCESS = 0x1,
     STATUS_DORECV = 0x2,
     STATUS_CPT = 0x10,
     STATUS_HB = 0x80,
 };
Function Documentation
Absolute()
void Absolute ()
Definition at line 596 of file main.c.
 {
     VMwareCommand cmd = {0};
     /* Enable */
     cmd.bx = ABSPOINTER_ENABLE;
     cmd.command = CMD_ABSPOINTER_COMMAND;
     CommandSend(&cmd);
     /* Status */
     cmd.bx = 0;
     cmd.command = CMD_ABSPOINTER_STATUS;
     CommandSend(&cmd);
     /* Read data (1) */
     cmd.bx = 1;
     cmd.command = CMD_ABSPOINTER_DATA;
     CommandSend(&cmd);
     /* Enable absolute */
     cmd.bx = ABSPOINTER_ABSOLUTE;
     cmd.command = CMD_ABSPOINTER_COMMAND;
     CommandSend(&cmd);
 }
References ABSPOINTER_ABSOLUTE, ABSPOINTER_ENABLE, cmd, CMD_ABSPOINTER_COMMAND, CMD_ABSPOINTER_DATA, CMD_ABSPOINTER_STATUS, and CommandSend().
Referenced by DriverEntry(), and InterruptHandler().
CommandSend()
void CommandSend (VMwareCommand * cmd)
Definition at line 586 of file main.c.
 {
     cmd->magic = VMWARE_MAGIC;
     cmd->port = VMWARE_PORT;
     asm volatile("in %%dx, %0"
                  : "+a"(cmd->ax), "+b"(cmd->bx),
                    "+c"(cmd->cx), "+d"(cmd->dx),
                    "+S"(cmd->si), "+D"(cmd->di));
 }
References cmd, VMWARE_MAGIC, and VMWARE_PORT.
Referenced by Absolute(), InterruptHandler(), and Relative().
DisplayGetSize()
static int DisplayGetSize (ToolboxContext * ctx) static
Definition at line 504 of file main.c.
 {
     if (ctx->TCLOChannel != -1)
         MessageClose(ctx);
     OpenMessageChannel(ctx, MESSAGE_TCLO);
     char EmptyBuffer[256] = {'\0'};
     MessageSend(ctx, EmptyBuffer);
     while (true)
     {
         /* FIXME: buf memory leak */
         char *buf;
         size_t len;
         int status = MessageReceive(ctx, &buf, &len);
         if (status == -EAGAIN)
         {
             Sleep(1000);
             continue;
         }
         else if (status < 0)
         {
             Log("Failed to receive message");
             return 1;
         }
         buf[StringLength(buf)] = '\0';
         if (MsgEqual(buf, "reset"))
         {
             if (MessageSend(ctx, "OK ATR toolbox") < 0)
                 return 1;
         }
         else if (MsgEqual(buf, "ping"))
         {
             if (MessageSend(ctx, "OK ") < 0)
                 return 1;
         }
         else if (MsgEqual(buf, "Capabilities_Register"))
         {
             SendRPCI(ctx, "tools.capability.resolution_set 1");
             SendRPCI(ctx, "tools.capability.resolution_server toolbox 1");
             SendRPCI(ctx, "tools.capability.display_topology_set 1");
             SendRPCI(ctx, "tools.capability.color_depth_set 1");
             SendRPCI(ctx, "tools.capability.resolution_min 0 0");
             SendRPCI(ctx, "tools.capability.unity 1");
             if (MessageSend(ctx, "OK ") < 0)
                 return 1;
         }
         else if (MsgEqual(buf, "Resolution_Set"))
         {
             DebugLog("%s", buf);
             if (MessageSend(ctx, "OK ") < 0)
                 return 1;
             MessageClose(ctx);
             return 0;
         }
         else
         {
             if (MessageSend(ctx, "ERROR Unknown command") < 0)
                 return 1;
         }
     }
 }
References buf, DebugLog, EAGAIN, len, Log(), MESSAGE_TCLO, MessageClose(), MessageReceive(), MessageSend(), MsgEqual(), OpenMessageChannel(), SendRPCI(), Driver::Sleep(), status, and StringLength().
Referenced by DisplayScaleThread().
DisplayScaleThread()
void DisplayScaleThread ()
Definition at line 572 of file main.c.
 {
     /* sizeof ToolboxContext */
     tb_ctx = AllocateMemory(1);
     Sleep(2000);
     while (true)
     {
         if (DisplayGetSize(tb_ctx) != 0)
             Log("Failed to scale display");
         Sleep(1000);
     }
 }
References AllocateMemory(), DisplayGetSize(), Log(), Driver::Sleep(), and tb_ctx.
Referenced by DriverEntry().
DriverEntry()
int DriverEntry ()
If we have another driver using the PS/2 mouse, we need to override its interrupt handler.
Definition at line 678 of file main.c.
 {
     ToolboxContext tb_ctx = {0};
     /* Test if it's supported */
     int status = OpenMessageChannel(&tb_ctx, MESSAGE_TCLO);
     if (status == 0)
     {
         ToolboxSupported = true;
         MessageClose(&tb_ctx);
         dst_id = CreateKernelThread(0, "VMware Display Scale",
                                     (void *)DisplayScaleThread, NULL);
     }
     PS2WriteCommand(PS2_CMD_ENABLE_PORT_2);
     PS2WriteCommand(PS2_CMD_READ_CONFIG);
     PS2_CONFIGURATION config = {.Raw = PS2ReadData()};
     config.Port2Interrupt = 1;
     PS2WriteCommand(PS2_CMD_WRITE_CONFIG);
     PS2WriteData(config.Raw);
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_SET_DEFAULTS);
     PS2ReadData();
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_ENABLE_DATA_REPORTING);
     PS2ReadData();
     Absolute();
     OverrideInterruptHandler(12, InterruptHandler);
     MouseDevID = RegisterInputDevice(ddt_Mouse);
     return 0;
 }
References Absolute(), Driver::CreateKernelThread(), ddt_Mouse, DisplayScaleThread(), dst_id, InterruptHandler(), MESSAGE_TCLO, MessageClose(), MouseDevID, NULL, OpenMessageChannel(), Driver::OverrideInterruptHandler(), PS2_CMD_ENABLE_PORT_2, PS2_CMD_READ_CONFIG, PS2_CMD_WRITE_CONFIG, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_ENABLE_DATA_REPORTING, PS2_MOUSE_CMD_SET_DEFAULTS, PS2ReadData(), PS2WriteCommand(), PS2WriteData(), PS2_CONFIGURATION::Raw, Driver::RegisterInputDevice(), status, tb_ctx, and ToolboxSupported.
DriverFinal()
int DriverFinal ()
This function is called when the driver is unloaded. This function should be used to stop the PCI device and free any resources.
Definition at line 716 of file main.c.
 {
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_DISABLE_DATA_REPORTING);
     Relative();
     UnregisterInputDevice(MouseDevID, ddt_Mouse);
     if (ToolboxSupported)
     {
         KillThread(dst_id, 0);
         if (tb_ctx->TCLOChannel != -1)
             MessageClose(tb_ctx);
         FreeMemory(tb_ctx, 1);
     }
     return 0;
 }
References ddt_Mouse, dst_id, FreeMemory(), Driver::KillThread(), MessageClose(), MouseDevID, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, PS2WriteCommand(), PS2WriteData(), Relative(), tb_ctx, ToolboxContext::TCLOChannel, ToolboxSupported, and Driver::UnregisterInputDevice().
DriverInfo()
DriverInfo ("vmware" , "VMware Tools Driver" , "EnderIce2" , "0.1" , "GPLv3")
DriverPanic()
int DriverPanic ()
This function is called when the kernel panics. This function should be used to stop the driver from receiving interrupts or anything else that is not safe to do when the kernel panics.
Definition at line 734 of file main.c.
 {
     Relative();
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_DISABLE_DATA_REPORTING);
     return 0;
 }
References PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, PS2WriteCommand(), PS2WriteData(), and Relative().
DriverProbe()
int DriverProbe ()
This is the first function that is called when the driver is loaded. We can use this function to test if the driver is compatible with the hardware. Like if we have a specific PCI device or if we have a specific CPU feature.
Return 0 if the driver is compatible with the hardware. Otherwise, we return a value from the errno.h header.
Note: In this function you cannot use variables that have constructors or destructors. Before DriverEntry, the constructors are called and after DriverFinalize, the destructors are called.
Definition at line 742 of file main.c.
 {
     if (!IsVMwareBackdoorAvailable())
         return -ENODEV;
     return 0;
 }
References ENODEV, and IsVMwareBackdoorAvailable().
InterruptHandler()
void InterruptHandler (TrapFrame *)
How should I handle this? (cmd.[bx,cx] * Width) / 0xFFFF Maybe TODO: Width and Height API?
Definition at line 629 of file main.c.
 {
     uint8_t Data = inb(0x60);
     (void)Data;
     VMwareCommand cmd = {0};
     cmd.bx = 0;
     cmd.command = CMD_ABSPOINTER_STATUS;
     CommandSend(&cmd);
     if (cmd.ax == 0xFFFF0000)
     {
         Log("VMware mouse is not connected?");
         Relative();
         Absolute();
         return;
     }
     if ((cmd.ax & 0xFFFF) < 4)
         return;
     cmd.bx = 4;
     cmd.command = CMD_ABSPOINTER_DATA;
     CommandSend(&cmd);
     int Buttons = (cmd.ax & 0xFFFF);
     MouseReport mr = {
         .LeftButton = Buttons & 0x20,
         .RightButton = Buttons & 0x10,
         .MiddleButton = Buttons & 0x08,
         .Button4 = 0x0,
         .Button5 = 0x0,
         .X = 0,
         .Y = 0,
         .Z = (int8_t)cmd.dx,
     };
     uintptr_t AbsoluteX = cmd.bx;
     uintptr_t AbsoluteY = cmd.cx;
     ReportAbsoluteMouseEvent(MouseDevID, mr, AbsoluteX, AbsoluteY);
 }
References Absolute(), cmd, CMD_ABSPOINTER_DATA, CMD_ABSPOINTER_STATUS, CommandSend(), Data, inb(), Log(), MouseDevID, Relative(), Driver::ReportAbsoluteMouseEvent(), and MouseReport::X.
Referenced by DriverEntry().
MessageClose()
static void MessageClose (ToolboxContext * ctx) static
Definition at line 209 of file main.c.
 {
     uintptr_t ax, bx, cx, dx,
         si = ctx->CookieHigh,
         di = ctx->CookieLow;
     VM_PORT(MESSAGE_CLOSE_CHANNEL,
             0, si, di,
             ctx->ChannelID << 16,
             VMWARE_MAGIC,
             ax, bx, cx, dx, si, di);
     DebugLog("Closed message channel %d", ctx->ChannelID);
 }
References DebugLog, MESSAGE_CLOSE_CHANNEL, VM_PORT, and VMWARE_MAGIC.
Referenced by DisplayGetSize(), DriverEntry(), DriverFinal(), and SendRPCI().
MessageReceive()
static int MessageReceive (ToolboxContext * ctx, char ** Buffer, size_t * BufferSize) static
Definition at line 377 of file main.c.
 {
     uintptr_t ax, bx, cx, dx, si, di;
     int Retries = 0;
     *Buffer = NULL;
     *BufferSize = 0;
     char *ReplyBuf = NULL;
     size_t ReplyBufPages = 0;
     size_t ReplySize = 0;
     while (Retries < 2)
     {
         Retries++;
         si = ctx->CookieHigh;
         di = ctx->CookieLow;
         VM_PORT(MESSAGE_RECV_SIZE,
                 0, si, di,
                 ctx->ChannelID << 16,
                 VMWARE_MAGIC,
                 ax, bx, cx, dx, si, di);
         if ((HighWord(cx) & STATUS_SUCCESS) == 0)
         {
             Log("Failed to receive message size: %d", cx);
             return -EINVAL;
         }
         else if ((HighWord(cx) & STATUS_DORECV) == 0)
         {
             // Log("No message to receive");
             return -EAGAIN;
         }
         ReplySize = bx;
         if (ReplyBuf != NULL)
             FreeMemory(ReplyBuf, ReplyBufPages);
         ReplyBufPages = ReplySize / 0x1000 + 1;
         ReplyBuf = AllocateMemory(ReplyBufPages);
         bool HighBand = (HighWord(cx) & STATUS_HB) != 0;
         if (HighBand)
             bx = MessageReceiveHB(ctx, ReplyBuf, ReplySize);
         else
             bx = MessageReceiveLB(ctx, ReplyBuf, ReplySize);
         if ((HighWord(bx) & STATUS_SUCCESS) == 0)
         {
             if ((HighWord(bx) & STATUS_CPT) == 0)
             {
                 Log("Checkpoint occurred for message payload");
                 continue;
             }
             Log("Failed to receive message payload: %d", HighWord(bx));
             FreeMemory(ReplyBuf, ReplyBufPages);
             return -EINVAL;
         }
         ReplyBuf[ReplySize] = '\0';
         si = ctx->CookieHigh;
         di = ctx->CookieLow;
         VM_PORT(MESSAGE_RECV_STATUS,
                 STATUS_SUCCESS, si, di,
                 ctx->ChannelID << 16,
                 VMWARE_MAGIC,
                 ax, bx, cx, dx, si, di);
         if ((HighWord(cx) & STATUS_SUCCESS) == 0)
         {
             if ((HighWord(cx) & STATUS_CPT) == 0)
             {
                 Log("Retrying message receive");
                 continue;
             }
             Log("Failed to receive message status: %d", HighWord(cx));
             FreeMemory(ReplyBuf, ReplyBufPages);
             return -EINVAL;
         }
         break;
     }
     if (ReplyBuf == NULL)
     {
         Log("Failed to receive message");
         return -EINVAL;
     }
     *Buffer = ReplyBuf;
     *BufferSize = ReplySize;
     DebugLog("Received message \"%s\"", ReplyBuf);
     return 0;
 }
References AllocateMemory(), Buffer, DebugLog, EAGAIN, EINVAL, FreeMemory(), HighWord, Log(), MESSAGE_RECV_SIZE, MESSAGE_RECV_STATUS, MessageReceiveHB(), MessageReceiveLB(), NULL, STATUS_CPT, STATUS_DORECV, STATUS_HB, STATUS_SUCCESS, VM_PORT, and VMWARE_MAGIC.
Referenced by DisplayGetSize().
MessageReceiveHB()
static uintptr_t MessageReceiveHB (ToolboxContext * ctx, char * Buffer, size_t BufferSize) static
Definition at line 273 of file main.c.
 {
     uintptr_t ax, bx, cx, dx,
         si = ctx->CookieHigh,
         di = (uintptr_t)Buffer,
         bp = ctx->CookieLow;
     uint32_t ChannelID = ctx->ChannelID << 16;
     VM_PORT_HB_IN((STATUS_SUCCESS << 16) | MESSAGE_HB_MSG,
                   BufferSize, si, di,
                   VMWARE_HYPERVISOR_HB | ChannelID | VMWARE_HYPERVISOR_OUT,
                   VMWARE_MAGIC, bp,
                   ax, bx, cx, dx, si, di);
     return bx;
 }
References bp, Buffer, MESSAGE_HB_MSG, STATUS_SUCCESS, VM_PORT_HB_IN, VMWARE_HYPERVISOR_HB, VMWARE_HYPERVISOR_OUT, and VMWARE_MAGIC.
Referenced by MessageReceive().
MessageReceiveLB()
static uintptr_t MessageReceiveLB (ToolboxContext * ctx, char * Buffer, size_t BufferSize) static
Definition at line 293 of file main.c.
 {
     uintptr_t ax, bx,
         cx = STATUS_SUCCESS << 16,
         dx, si, di;
     while (BufferSize)
     {
         uint32_t TotalBytes = MIN((uint32_t)BufferSize, (uint32_t)4);
         si = ctx->CookieHigh;
         di = ctx->CookieLow;
         VM_PORT(MESSAGE_RECV_PAYLOAD,
                 STATUS_SUCCESS, si, di,
                 ctx->ChannelID << 16,
                 VMWARE_MAGIC,
                 ax, bx, cx, dx, si, di);
         if ((HighWord(cx) & STATUS_SUCCESS) == 0)
             break;
         MemoryCopy(Buffer, &bx, TotalBytes);
         Buffer += TotalBytes;
         BufferSize -= TotalBytes;
     }
     return cx;
 }
References Buffer, HighWord, MemoryCopy(), MESSAGE_RECV_PAYLOAD, MIN, STATUS_SUCCESS, VM_PORT, and VMWARE_MAGIC.
Referenced by MessageReceive().
MessageSend()
static int MessageSend (ToolboxContext * ctx, const char * Message) static
Definition at line 325 of file main.c.
 {
     uintptr_t ax, bx, cx, dx, si, di;
     size_t Size = StringLength(Message);
     int Retries = 0;
     while (Retries < 2)
     {
         Retries++;
         si = ctx->CookieHigh;
         di = ctx->CookieLow;
         VM_PORT(MESSAGE_SEND_SIZE,
                 Size, si, di,
                 ctx->ChannelID << 16,
                 VMWARE_MAGIC,
                 ax, bx, cx, dx, si, di);
         if ((HighWord(cx) & STATUS_SUCCESS) == 0)
         {
             Log("Failed to send message size for \"%s\": %d",
                 Message, cx);
             return -EINVAL;
         }
         bool HighBand = (HighWord(cx) & STATUS_HB) != 0;
         if (HighBand)
             bx = MessageSendHB(ctx, Message);
         else
             bx = MessageSendLB(ctx, Message);
         int status = HighWord(bx);
         if ((status & STATUS_SUCCESS) != 0)
         {
             DebugLog("Message \"%s\" sent", Message);
             return 0;
         }
         else if ((status & STATUS_CPT) == 0)
         {
             Log("Checkpoint occurred for message \"%s\"", Message);
             continue;
         }
         else
             break;
     }
     Log("Failed to send message \"%s\": %#lx", Message, bx);
     return -EINVAL;
 }
References DebugLog, EINVAL, HighWord, Log(), MESSAGE_SEND_SIZE, MessageSendHB(), MessageSendLB(), Size, status, STATUS_CPT, STATUS_HB, STATUS_SUCCESS, StringLength(), VM_PORT, and VMWARE_MAGIC.
Referenced by DisplayGetSize(), and SendRPCI().
MessageSendHB()
static uintptr_t MessageSendHB (ToolboxContext * ctx, const char * Message) static
Definition at line 224 of file main.c.
 {
     uintptr_t ax, bx, cx, dx,
         si = (uintptr_t)Message,
         di = ctx->CookieLow,
         bp = ctx->CookieHigh;
     uint32_t ChannelID = ctx->ChannelID << 16;
     size_t Size = StringLength(Message);
     VM_PORT_HB_OUT((STATUS_SUCCESS << 16) | MESSAGE_HB_MSG,
                    Size, si, di,
                    VMWARE_HYPERVISOR_HB | ChannelID | VMWARE_HYPERVISOR_OUT,
                    VMWARE_MAGIC, bp,
                    ax, bx, cx, dx, si, di);
     return bx;
 }
References bp, MESSAGE_HB_MSG, Size, STATUS_SUCCESS, StringLength(), VM_PORT_HB_OUT, VMWARE_HYPERVISOR_HB, VMWARE_HYPERVISOR_OUT, and VMWARE_MAGIC.
Referenced by MessageSend().
MessageSendLB()
static uintptr_t MessageSendLB (ToolboxContext * ctx, const char * Message) static
Definition at line 244 of file main.c.
 {
     uintptr_t ax, bx,
         cx = STATUS_SUCCESS << 16,
         dx, si, di;
     size_t Size = StringLength(Message);
     while (Size &&
            (HighWord(cx) & STATUS_SUCCESS))
     {
         uint32_t TotalBytes = MIN((uint32_t)Size, (uint32_t)4);
         uint32_t Word = 0;
         MemoryCopy(&Word, Message, TotalBytes);
         Message += TotalBytes;
         si = ctx->CookieHigh;
         di = ctx->CookieLow;
         VM_PORT(MESSAGE_SEND_PAYLOAD,
                 Word, si, di,
                 ctx->ChannelID << 16,
                 VMWARE_MAGIC,
                 ax, bx, cx, dx, si, di);
     }
     return cx;
 }
References HighWord, MemoryCopy(), MESSAGE_SEND_PAYLOAD, MIN, Size, STATUS_SUCCESS, StringLength(), VM_PORT, and VMWARE_MAGIC.
Referenced by MessageSend().
MsgEqual()
int MsgEqual (const char * haystack, const char * needle)
Definition at line 499 of file main.c.
 {
     return strstr(haystack, needle) == haystack;
 }
References strstr().
Referenced by DisplayGetSize().
OpenMessageChannel()
static int OpenMessageChannel (ToolboxContext * ctx, uint32_t Protocol) static
Definition at line 186 of file main.c.
 {
     uintptr_t ax, bx, cx, dx, si = 0, di = 0;
     VM_PORT(MESSAGE_OPEN_CHANNEL,
             (Protocol | FLAG_COOKIE), si, di,
             0, VMWARE_MAGIC,
             ax, bx, cx, dx, si, di);
     if ((HighWord(cx) & STATUS_SUCCESS) == 0)
     {
         Log("Failed to open message channel %#lx", Protocol);
         return -EINVAL;
     }
     DebugLog("Opened message channel %d (Protocol: %#lx)",
              HighWord(dx), Protocol);
     ctx->ChannelID = (uint16_t)HighWord(dx);
     ctx->CookieHigh = si;
     ctx->CookieLow = di;
     return 0;
 }
References DebugLog, EINVAL, FLAG_COOKIE, HighWord, Log(), MESSAGE_OPEN_CHANNEL, STATUS_SUCCESS, VM_PORT, and VMWARE_MAGIC.
Referenced by DisplayGetSize(), DriverEntry(), and SendRPCI().
Relative()
void Relative ()
Definition at line 621 of file main.c.
 {
     VMwareCommand cmd = {0};
     cmd.bx = ABSPOINTER_RELATIVE;
     cmd.command = CMD_ABSPOINTER_COMMAND;
     CommandSend(&cmd);
 }
References ABSPOINTER_RELATIVE, cmd, CMD_ABSPOINTER_COMMAND, and CommandSend().
Referenced by DriverFinal(), DriverPanic(), and InterruptHandler().
SendRPCI()
static int SendRPCI (ToolboxContext * , const char * Request) static
Definition at line 478 of file main.c.
 {
     ToolboxContext rpci_ctx = {0};
     int status = OpenMessageChannel(&rpci_ctx, MESSAGE_RPCI);
     if (status < 0)
     {
         Log("Failed to open RPCI channel: %d", status);
         return status;
     }
     status = MessageSend(&rpci_ctx, Request);
     if (status < 0)
     {
         Log("Failed to send RPCI request: %d", status);
         return status;
     }
     MessageClose(&rpci_ctx);
     return 0;
 }
References Log(), MESSAGE_RPCI, MessageClose(), MessageSend(), OpenMessageChannel(), and status.
Referenced by DisplayGetSize().
Variable Documentation
dst_id
pid_t dst_id = -1
Definition at line 570 of file main.c.
Referenced by DriverEntry(), and DriverFinal().
MouseDevID
dev_t MouseDevID = -1
Definition at line 184 of file main.c.
Referenced by DriverEntry(), DriverFinal(), and InterruptHandler().
tb_ctx
ToolboxContext* tb_ctx = NULL
Definition at line 571 of file main.c.
Referenced by DisplayScaleThread(), DriverEntry(), and DriverFinal().
ToolboxSupported
bool ToolboxSupported = false
Definition at line 677 of file main.c.
Referenced by DriverEntry(), and DriverFinal().