Fennix: Userspace/mlibc/sysdeps/lemon/generic/thread.cpp File Reference
thread.cpp File Reference
#include <mlibc/thread-entry.hpp>
#include <mlibc/all-sysdeps.hpp>
#include <mlibc/tcb.hpp>
#include <bits/ensure.h>
#include <sys/mman.h>
#include <stdint.h>
#include <stddef.h>
Namespaces
mlibc
Functions
void __mlibc_enter_thread (void *entry, void *user_arg, Tcb *tcb)
int mlibc::sys_prepare_stack (void **stack, void *entry, void *user_arg, void *tcb, size_t *stack_size, size_t *guard_size)
Variables
static constexpr size_t mlibc::default_stacksize = 0x200000
Function Documentation
__mlibc_enter_thread()
void __mlibc_enter_thread (void * entry, void * user_arg, Tcb * tcb)
Definition at line 9 of file thread.cpp.
{
     // Wait until our parent sets up the TID.
     while(!__atomic_load_n(&tcb->tid, __ATOMIC_RELAXED))
         mlibc::sys_futex_wait(&tcb->tid, 0, nullptr);
     if(mlibc::sys_tcb_set(tcb))
         __ensure(!"sys_tcb_set() failed");
     void *(*func)(void *) = reinterpret_cast<void *(*)(void *)>(entry);
     auto result = func(user_arg);
     auto self = reinterpret_cast<Tcb *>(tcb);
     self->returnValue = result;
     __atomic_store_n(&self->didExit, 1, __ATOMIC_RELEASE);
     mlibc::sys_futex_wake(&self->didExit);
     mlibc::sys_thread_exit();
 }
References __ensure, mlibc::result, Tcb::returnValue, mlibc::sys_futex_wait(), mlibc::sys_futex_wake(), mlibc::sys_tcb_set(), mlibc::sys_thread_exit(), and Tcb::tid.