Fennix Userspace: anonymous_namespace{environment.cpp} Namespace Reference
anonymous_namespace{environment.cpp} Namespace Reference
Functions
size_t find_environ_index (frg::string_view name)
frg::vector< char *, MemoryAllocator > & get_vector ()
void update_vector ()
void assign_variable (frg::string_view name, const char *string, bool overwrite)
void unassign_variable (frg::string_view name)
Variables
char * empty_environment [] = { nullptr }
Function Documentation
assign_variable()
void anonymous_namespace{environment.cpp}::assign_variable (frg::string_view name, const char * string, bool overwrite)
Definition at line 59 of file environment.cpp.
{
     auto &vector = get_vector();
     __ensure(environ == vector.data());
     auto k = find_environ_index(name);
     if(k != size_t(-1)) {
         if(overwrite)
             vector[k] = const_cast<char *>(string);
     }else{
         // Last pointer of environ must always be a null delimiter.
         __ensure(!vector.back());
         vector.back() = const_cast<char *>(string);
         vector.push(nullptr);
     }
     // push() might have re-allocated the vector.
     environ = vector.data();
 }
References __ensure, environ, find_environ_index(), get_vector(), k, name, and string.
Referenced by mlibc::putenv().
find_environ_index()
size_t anonymous_namespace{environment.cpp}::find_environ_index (frg::string_view name)
Definition at line 20 of file environment.cpp.
{
     for(size_t i = 0; environ[i]; i++) {
         frg::string_view view{environ[i]};
         size_t s = view.find_first('=');
         if(s == size_t(-1)) {
             mlibc::infoLogger() << "mlibc: environment string \""
                     << frg::escape_fmt{view.data(), view.size()}
                     << "\" does not contain an equals sign (=)" << frg::endlog;
             continue;
         }
         if(view.sub_string(0, s) == name)
             return i;
     }
     return -1;
 }
References environ, i, mlibc::infoLogger, and name.
Referenced by assign_variable(), getenv(), and unassign_variable().
get_vector()
frg::vector<char *, MemoryAllocator>& anonymous_namespace{environment.cpp}::get_vector ()
Definition at line 39 of file environment.cpp.
{
     static frg::vector<char *, MemoryAllocator> vector{getAllocator()};
     return vector;
 }
References getAllocator().
Referenced by assign_variable(), unassign_variable(), and update_vector().
unassign_variable()
void anonymous_namespace{environment.cpp}::unassign_variable (frg::string_view name)
Definition at line 78 of file environment.cpp.
{
     auto &vector = get_vector();
     __ensure(environ == vector.data());
     auto k = find_environ_index(name);
     if(k == size_t(-1))
         return;
     // Last pointer of environ must always be a null delimiter.
     __ensure(vector.size() >= 2 && !vector.back());
     std::swap(vector[k], vector[vector.size() - 2]);
     vector.pop();
     vector.back() = nullptr;
     // pop() might have re-allocated the vector.
     environ = vector.data();
 }
References __ensure, environ, find_environ_index(), get_vector(), k, name, and swap().
update_vector()
void anonymous_namespace{environment.cpp}::update_vector ()
Definition at line 44 of file environment.cpp.
                      {
     auto &vector = get_vector();
     if(environ == vector.data())
         return;
     // If the environ variable was changed, we copy the environment.
     // Note that we must only copy the pointers but not the strings themselves!
     vector.clear();
     for(size_t i = 0; environ[i]; i++)
         vector.push(environ[i]);
     vector.push(nullptr);
     environ = vector.data();
 }
References environ, get_vector(), and i.
Referenced by mlibc::putenv().
Variable Documentation
empty_environment
char* anonymous_namespace{environment.cpp}::empty_environment[] = { nullptr }
Definition at line 13 of file environment.cpp.