Fennix Userspace: Userspace/musl/src/misc/ioctl.c File Reference
ioctl.c File Reference
#include <sys/ioctl.h>
#include <stdarg.h>
#include <errno.h>
#include <time.h>
#include <sys/time.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <endian.h>
#include "syscall.h"
Data Structures
struct ioctl_compat_map
struct v4l2_event
Macros
#define alignof(t) offsetof(struct { char c; t x; }, x)
#define W 1
#define R 2
#define WR 3
#define NINTH(a, b, c, d, e, f, g, h, i, ...) i
#define COUNT(...) NINTH(__VA_ARGS__,8,7,6,5,4,3,2,1,0)
#define OFFS(...) COUNT(__VA_ARGS__), { __VA_ARGS__ }
#define new_misaligned(n) struct { int i; time_t t; char c[(n)-4]; }
Functions
static void convert_ioctl_struct (const struct ioctl_compat_map *map, char *old, char *new, int dir)
int ioctl (int fd, int req,...)
Variables
static const struct ioctl_compat_map compat_map []
Data Structure Documentation
ioctl_compat_map
struct ioctl_compat_map
Definition at line 18 of file ioctl.c.
Data Fields
unsigned char dir
unsigned char force_align
int new_req
unsigned char noffs
unsigned char offsets[8]
int old_req
unsigned char old_size
v4l2_event
struct v4l2_event
Definition at line 33 of file ioctl.c.
Data Fields
uint32_t a
uint64_t b[8]
uint32_t c[2]
uint32_t d[9]
uint32_t ts[2]
Macro Definition Documentation
alignof
#define alignof (t) offsetof(struct { char c; t x; }, x)
Definition at line 12 of file ioctl.c.
COUNT
#define COUNT (...) NINTH(__VA_ARGS__,8,7,6,5,4,3,2,1,0)
Definition at line 25 of file ioctl.c.
new_misaligned
#define new_misaligned (n) struct { int i; time_t t; char c[(n)-4]; }
Definition at line 31 of file ioctl.c.
NINTH
#define NINTH (a, b, c, d, e, f, g, h, i, ...) i
Definition at line 24 of file ioctl.c.
OFFS
#define OFFS (...) COUNT(__VA_ARGS__), { __VA_ARGS__ }
Definition at line 26 of file ioctl.c.
R
#define R 2
Definition at line 15 of file ioctl.c.
W
#define W 1
Definition at line 14 of file ioctl.c.
WR
#define WR 3
Definition at line 16 of file ioctl.c.
Function Documentation
convert_ioctl_struct()
static void convert_ioctl_struct (const struct ioctl_compat_map * map, char * old, char * new, int dir) static
Definition at line 83 of file ioctl.c.
 {
     int new_offset = 0;
     int old_offset = 0;
     int old_size = map->old_size;
     if (!(dir & map->dir)) return;
     if (!map->old_size) {
         /* offsets hard-coded for SNDRV_PCM_IOCTL_SYNC_PTR;
          * if another exception appears this needs changing. */
         convert_ioctl_struct(map+1, old, new, dir);
         convert_ioctl_struct(map+2, old+4, new+8, dir);
         /* snd_pcm_mmap_control, special-cased due to kernel
          * type definition having been botched. */
         int adj = BYTE_ORDER==BIG_ENDIAN ? 4 : 0;
         convert_ioctl_struct(map+3, old+68, new+72+adj, dir);
         convert_ioctl_struct(map+3, old+72, new+76+3*adj, dir);
         return;
     }
     for (int i=0; i < map->noffs; i++) {
         int ts_offset = map->offsets[i];
         int len = ts_offset-old_offset;
         if (dir==W) memcpy(old+old_offset, new+new_offset, len);
         else memcpy(new+new_offset, old+old_offset, len);
         new_offset += len;
         old_offset += len;
         long long new_ts;
         long old_ts;
         int align = map->force_align ? sizeof(time_t) : alignof(time_t);
         new_offset += (align-1) & -new_offset;
         if (dir==W) {
             memcpy(&new_ts, new+new_offset, sizeof new_ts);
             old_ts = new_ts;
             memcpy(old+old_offset, &old_ts, sizeof old_ts);
         } else {
             memcpy(&old_ts, old+old_offset, sizeof old_ts);
             new_ts = old_ts;
             memcpy(new+new_offset, &new_ts, sizeof new_ts);
         }
         new_offset += sizeof new_ts;
         old_offset += sizeof old_ts;
     }
     if (dir==W) memcpy(old+old_offset, new+new_offset, old_size-old_offset);
     else memcpy(new+new_offset, old+old_offset, old_size-old_offset);
 }
References BIG_ENDIAN, BYTE_ORDER, dir, i, map, memcpy(), old, old_offset, and W.
Referenced by ioctl().
ioctl()
int ioctl (int fd, int req, ...)
Definition at line 128 of file ioctl.c.
 {
     void *arg;
     va_list ap;
     va_start(ap, req);
     arg = va_arg(ap, void *);
     va_end(ap);
     int r = __syscall(SYS_ioctl, fd, req, arg);
     if (SIOCGSTAMP != SIOCGSTAMP_OLD && req && r==-ENOTTY) {
         for (int i=0; i<sizeof compat_map/sizeof *compat_map; i++) {
             if (compat_map[i].new_req != req) continue;
             union {
                 long long align;
                 char buf[256];
             } u;
             convert_ioctl_struct(&compat_map[i], u.buf, arg, W);
             r = __syscall(SYS_ioctl, fd, compat_map[i].old_req, u.buf);
             if (r<0) break;
             convert_ioctl_struct(&compat_map[i], u.buf, arg, R);
             break;
         }
     }
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ap, buf, compat_map, convert_ioctl_struct(), ENOTTY, fd, i, R, SIOCGSTAMP, SIOCGSTAMP_OLD, va_arg, va_end, va_start, and W.
Referenced by _rl_get_screen_size(), _rl_input_available(), _rl_nchars_available(), arp_del(), bb_BLKGETSIZE_sectors(), bb_ioctl_or_warn(), bb_xioctl(), beep_main(), blockdev_main(), change_attributes(), console_init(), conspy_main(), copy_file(), cttyhack_main(), d6_read_interface(), del_loop(), eject_cdrom(), find_free_vtno(), flash_eraseall_main(), flashcp_main(), get_console_fd_or_die(), get_free_loop(), get_kernel_geometry(), get_label_uuid(), get_new_window_size(), get_sectorsize(), get_terminal_width_height(), get_tty_settings(), get_tty_state(), getty_main(), i2c_smbus_access(), if_fetch(), if_indextoname(), if_nametoindex(), init_exec(), init_wsize(), input_avail(), ioctl_on_skfd(), ioctl_or_perror(), ioctl_or_perror_and_die(), is_whole_disk(), list_attributes(), loadkmap_main(), login_tty(), mkfs_vfat_main(), nameif_main(), nbdclient_main(), nchars_avail(), network_ioctl(), not_vt_fd(), openpty(), query_loop(), resize_main(), rl_gather_tyi(), rl_restart_output(), rl_stop_output(), rl_tty_status(), safe_write_to_pty_decode_iac(), script_main(), serial_ctl(), set_loopdev_params(), set_new_line_discipline(), set_tty_settings(), set_tty_state(), set_winsize(), setsid_main(), slattach_main(), sockatmark(), start_shell_in_child(), sulogin_main(), tcflow(), tcflush(), tcgetattr(), tcgetpgrp(), tcgetsid(), tcsendbreak(), tcsetattr(), tcsetpgrp(), ttgetattr(), ttsetattr(), ttysize_main(), unlockpt(), vfork_child(), and vlock_main().
Variable Documentation
compat_map
const struct ioctl_compat_map compat_map[] static
Definition at line 1 of file ioctl.c.
Referenced by ioctl().