Fennix: Userspace/apps/base/busybox/util-linux/mkfs_minix.c File Reference
mkfs_minix.c File Reference
#include "libbb.h"
#include <mntent.h>
#include "minix.h"
Data Structures
struct globals
union globals.u
Macros
#define CUR_TIME 0
#define GETUID 0
#define GETGID 0
#define G (*ptr_to_globals)
#define INIT_G()
#define INODE_BUF1 (((struct minix1_inode*)G.inode_buffer) - 1)
#define INODE_BUF2 (((struct minix2_inode*)G.inode_buffer) - 1)
#define SB (G.u.SB)
#define SB_INODES (SB.s_ninodes)
#define SB_IMAPS (SB.s_imap_blocks)
#define SB_ZMAPS (SB.s_zmap_blocks)
#define SB_FIRSTZONE (SB.s_firstdatazone)
#define SB_ZONE_SIZE (SB.s_log_zone_size)
#define SB_MAXSIZE (SB.s_max_size)
#define SB_MAGIC (SB.s_magic)
#define SB_ZONES (SB.s_nzones)
#define INODE_BLOCKS div_roundup(SB_INODES, MINIX1_INODES_PER_BLOCK)
#define INODE_BUFFER_SIZE (INODE_BLOCKS * BLOCK_SIZE)
#define NORM_FIRSTZONE (2 + SB_IMAPS + SB_ZMAPS + INODE_BLOCKS)
#define zone_in_use(x) minix_bit(G.zone_map,(x)-SB_FIRSTZONE+1)
#define mark_inode(x) minix_setbit(G.inode_map,(x))
#define unmark_inode(x) minix_clrbit(G.inode_map,(x))
#define mark_zone(x) minix_setbit(G.zone_map,(x)-SB_FIRSTZONE+1)
#define unmark_zone(x) minix_clrbit(G.zone_map,(x)-SB_FIRSTZONE+1)
#define BLKGETSIZE _IO(0x12,96) /* return device size */
#define ind_block (G.ind_block1)
#define dind_block (G.dind_block1)
#define NEXT_BAD (zone = next(zone))
Enumerations
enum { MAX_GOOD_BLOCKS = 512 , TEST_BUFFER_BLOCKS = 16 }
enum { version2 = 0 }
enum { dev_fd = 3 }
Functions
static ALWAYS_INLINE unsigned div_roundup (unsigned size, unsigned n)
static int minix_bit (const char *a, unsigned i)
static void minix_setbit (char *a, unsigned i)
static void minix_clrbit (char *a, unsigned i)
static void write_tables (void)
static void write_block (int blk, char *buffer)
static int get_free_block (void)
static void mark_good_blocks (void)
static int next (int zone)
static void make_bad_inode (void)
void make_bad_inode2 (void)
static void make_root_inode (void)
void make_root_inode2 (void)
static size_t do_check (char *buffer, size_t try, unsigned current_block)
static void alarm_intr (int alnum UNUSED_PARAM)
static void check_blocks (void)
static void get_list_blocks (char *filename)
static void setup_tables (void)
int mkfs_minix_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
globals.u
union globals.u
Definition at line 144 of file mkfs_minix.c.
Data Fields
struct minix_superblock SB
struct minix_superblock Super
char superblock_buffer[BLOCK_SIZE]
char superblock_buffer[BLOCK_SIZE]
Macro Definition Documentation
BLKGETSIZE
#define BLKGETSIZE _IO(0x12,96) /* return device size */
Definition at line 220 of file mkfs_minix.c.
CUR_TIME
#define CUR_TIME 0
Definition at line 104 of file mkfs_minix.c.
dind_block
#define dind_block (G.dind_block1)
G
#define G (*ptr_to_globals)
Definition at line 158 of file mkfs_minix.c.
GETGID
#define GETGID 0
Definition at line 106 of file mkfs_minix.c.
GETUID
#define GETUID 0
Definition at line 105 of file mkfs_minix.c.
ind_block
#define ind_block (G.ind_block1)
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 159 of file mkfs_minix.c.
INODE_BLOCKS
#define INODE_BLOCKS div_roundup(SB_INODES, MINIX1_INODES_PER_BLOCK)
Definition at line 183 of file mkfs_minix.c.
INODE_BUF1
#define INODE_BUF1 (((struct minix1_inode*)G.inode_buffer) - 1)
Definition at line 168 of file mkfs_minix.c.
INODE_BUF2
#define INODE_BUF2 (((struct minix2_inode*)G.inode_buffer) - 1)
Definition at line 169 of file mkfs_minix.c.
INODE_BUFFER_SIZE
#define INODE_BUFFER_SIZE (INODE_BLOCKS * BLOCK_SIZE)
Definition at line 190 of file mkfs_minix.c.
mark_inode
#define mark_inode (x) minix_setbit(G.inode_map,(x))
Definition at line 214 of file mkfs_minix.c.
mark_zone
#define mark_zone (x) minix_setbit(G.zone_map,(x)-SB_FIRSTZONE+1)
Definition at line 216 of file mkfs_minix.c.
NEXT_BAD
#define NEXT_BAD (zone = next(zone))
NORM_FIRSTZONE
#define NORM_FIRSTZONE (2 + SB_IMAPS + SB_ZMAPS + INODE_BLOCKS)
Definition at line 191 of file mkfs_minix.c.
SB
#define SB (G.u.SB)
Definition at line 171 of file mkfs_minix.c.
SB_FIRSTZONE
#define SB_FIRSTZONE (SB.s_firstdatazone)
Definition at line 176 of file mkfs_minix.c.
SB_IMAPS
#define SB_IMAPS (SB.s_imap_blocks)
Definition at line 174 of file mkfs_minix.c.
SB_INODES
#define SB_INODES (SB.s_ninodes)
Definition at line 173 of file mkfs_minix.c.
SB_MAGIC
#define SB_MAGIC (SB.s_magic)
Definition at line 179 of file mkfs_minix.c.
SB_MAXSIZE
#define SB_MAXSIZE (SB.s_max_size)
Definition at line 178 of file mkfs_minix.c.
SB_ZMAPS
#define SB_ZMAPS (SB.s_zmap_blocks)
Definition at line 175 of file mkfs_minix.c.
SB_ZONE_SIZE
#define SB_ZONE_SIZE (SB.s_log_zone_size)
Definition at line 177 of file mkfs_minix.c.
SB_ZONES
#define SB_ZONES (SB.s_nzones)
Definition at line 182 of file mkfs_minix.c.
unmark_inode
#define unmark_inode (x) minix_clrbit(G.inode_map,(x))
Definition at line 215 of file mkfs_minix.c.
unmark_zone
#define unmark_zone (x) minix_clrbit(G.zone_map,(x)-SB_FIRSTZONE+1)
Definition at line 217 of file mkfs_minix.c.
zone_in_use
#define zone_in_use (x) minix_bit(G.zone_map,(x)-SB_FIRSTZONE+1)
Definition at line 211 of file mkfs_minix.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_GOOD_BLOCKS
TEST_BUFFER_BLOCKS
Definition at line 114 of file mkfs_minix.c.
      {
     MAX_GOOD_BLOCKS         = 512,
     TEST_BUFFER_BLOCKS      = 16,
 };
anonymous enum
anonymous enum
Enumerator
version2
Definition at line 120 of file mkfs_minix.c.
 { version2 = 0 };
anonymous enum
anonymous enum
Enumerator
dev_fd
Definition at line 123 of file mkfs_minix.c.
 { dev_fd = 3 };
Function Documentation
alarm_intr()
static void alarm_intr (int alnum UNUSED_PARAM) static
Definition at line 485 of file mkfs_minix.c.
 {
     if (G.currently_testing >= SB_ZONES)
         return;
     signal(SIGALRM, alarm_intr);
     alarm(5);
     if (!G.currently_testing)
         return;
     printf("%d ...", G.currently_testing);
     fflush_all();
 }
References alarm(), fflush_all(), G, printf, SB_ZONES, SIGALRM, and signal.
Referenced by check_blocks().
check_blocks()
static void check_blocks (void) static
Definition at line 497 of file mkfs_minix.c.
 {
     size_t try, got;
     G.currently_testing = 0;
     signal(SIGALRM, alarm_intr);
     alarm(5);
     while (G.currently_testing < SB_ZONES) {
         msg_eol = "seek failed in check_blocks";
         xlseek(dev_fd, G.currently_testing * BLOCK_SIZE, SEEK_SET);
         msg_eol = "\n";
         try = TEST_BUFFER_BLOCKS;
         if (G.currently_testing + try > SB_ZONES)
             try = SB_ZONES - G.currently_testing;
         got = do_check(G.check_blocks_buffer, try, G.currently_testing);
         G.currently_testing += got;
         if (got == try)
             continue;
         if (G.currently_testing < SB_FIRSTZONE)
             bb_simple_error_msg_and_die("bad blocks before data-area: cannot make fs");
         mark_zone(G.currently_testing);
         G.badblocks++;
         G.currently_testing++;
     }
     alarm(0);
     printf("%d bad block(s)\n", G.badblocks);
 }
References alarm(), alarm_intr(), bb_simple_error_msg_and_die(), BLOCK_SIZE, dev_fd, do_check(), G, mark_zone, msg_eol, printf, SB_FIRSTZONE, SB_ZONES, SEEK_SET, SIGALRM, signal, TEST_BUFFER_BLOCKS, and xlseek().
Referenced by mkfs_minix_main().
div_roundup()
static ALWAYS_INLINE unsigned div_roundup (unsigned size, unsigned n) static
Definition at line 163 of file mkfs_minix.c.
 {
     return (size + n-1) / n;
 }
References n, and size.
Referenced by setup_tables().
do_check()
static size_t do_check (char * buffer, size_t try, unsigned current_block) static
Definition at line 465 of file mkfs_minix.c.
 {
     ssize_t got;
     /* Seek to the correct loc. */
     msg_eol = "seek failed during testing of blocks";
     xlseek(dev_fd, current_block * BLOCK_SIZE, SEEK_SET);
     msg_eol = "\n";
     /* Try the read */
     got = read(dev_fd, buffer, try * BLOCK_SIZE);
     if (got < 0)
         got = 0;
     try = ((size_t)got) / BLOCK_SIZE;
     if (got & (BLOCK_SIZE - 1))
         fprintf(stderr, "Short read at block %u\n", (unsigned)(current_block + try));
     return try;
 }
References BLOCK_SIZE, dev_fd, fprintf(), msg_eol, read(), SEEK_SET, stderr, and xlseek().
Referenced by check_blocks().
get_free_block()
static int get_free_block (void) static
Definition at line 259 of file mkfs_minix.c.
 {
     int blk;
     if (G.used_good_blocks + 1 >= MAX_GOOD_BLOCKS)
         bb_simple_error_msg_and_die("too many bad blocks");
     if (G.used_good_blocks)
         blk = G.good_blocks_table[G.used_good_blocks - 1] + 1;
     else
         blk = SB_FIRSTZONE;
     while (blk < SB_ZONES && zone_in_use(blk))
         blk++;
     if (blk >= SB_ZONES)
         bb_simple_error_msg_and_die("not enough good blocks");
     G.good_blocks_table[G.used_good_blocks] = blk;
     G.used_good_blocks++;
     return blk;
 }
References bb_simple_error_msg_and_die(), G, MAX_GOOD_BLOCKS, SB_FIRSTZONE, SB_ZONES, and zone_in_use.
Referenced by make_bad_inode(), and make_root_inode().
get_list_blocks()
static void get_list_blocks (char * filename) static
Definition at line 525 of file mkfs_minix.c.
 {
     FILE *listfile;
     unsigned long blockno;
     listfile = xfopen_for_read(filename);
     while (!feof(listfile)) {
         fscanf(listfile, "%lu\n", &blockno);
         mark_zone(blockno);
         G.badblocks++;
     }
     printf("%d bad block(s)\n", G.badblocks);
 }
References feof, filename, fscanf(), G, mark_zone, printf, and xfopen_for_read().
Referenced by mkfs_minix_main().
make_bad_inode()
static void make_bad_inode (void) static
Definition at line 296 of file mkfs_minix.c.
 {
     struct minix1_inode *inode = &INODE_BUF1[MINIX_BAD_INO];
     int i, j, zone;
     int ind = 0, dind = 0;
     /* moved to globals to reduce stack usage
     unsigned short ind_block[BLOCK_SIZE >> 1];
     unsigned short dind_block[BLOCK_SIZE >> 1];
     */
 #define ind_block (G.ind_block1)
 #define dind_block (G.dind_block1)
 #define NEXT_BAD (zone = next(zone))
     if (!G.badblocks)
         return;
     mark_inode(MINIX_BAD_INO);
     inode->i_nlinks = 1;
     /* BTW, setting this makes all images different */
     /* it's harder to check for bugs then - diff isn't helpful :(... */
     inode->i_time = CUR_TIME;
     inode->i_mode = S_IFREG + 0000;
     inode->i_size = G.badblocks * BLOCK_SIZE;
     zone = next(0);
     for (i = 0; i < 7; i++) {
         inode->i_zone[i] = zone;
         if (!NEXT_BAD)
             goto end_bad;
     }
     inode->i_zone[7] = ind = get_free_block();
     memset(ind_block, 0, BLOCK_SIZE);
     for (i = 0; i < 512; i++) {
         ind_block[i] = zone;
         if (!NEXT_BAD)
             goto end_bad;
     }
     inode->i_zone[8] = dind = get_free_block();
     memset(dind_block, 0, BLOCK_SIZE);
     for (i = 0; i < 512; i++) {
         write_block(ind, (char *) ind_block);
         dind_block[i] = ind = get_free_block();
         memset(ind_block, 0, BLOCK_SIZE);
         for (j = 0; j < 512; j++) {
             ind_block[j] = zone;
             if (!NEXT_BAD)
                 goto end_bad;
         }
     }
     bb_simple_error_msg_and_die("too many bad blocks");
  end_bad:
     if (ind)
         write_block(ind, (char *) ind_block);
     if (dind)
         write_block(dind, (char *) dind_block);
 #undef ind_block
 #undef dind_block
 }
References bb_simple_error_msg_and_die(), BLOCK_SIZE, CUR_TIME, dind_block, G, get_free_block(), i, minix1_inode::i_mode, minix1_inode::i_nlinks, minix1_inode::i_size, minix1_inode::i_time, minix1_inode::i_zone, ind_block, INODE_BUF1, j, mark_inode, memset, MINIX_BAD_INO, next(), NEXT_BAD, S_IFREG, and write_block().
Referenced by mkfs_minix_main().
make_bad_inode2()
void make_bad_inode2 (void)
Referenced by mkfs_minix_main().
make_root_inode()
static void make_root_inode (void) static
Definition at line 413 of file mkfs_minix.c.
 {
     struct minix1_inode *inode = &INODE_BUF1[MINIX_ROOT_INO];
     mark_inode(MINIX_ROOT_INO);
     inode->i_zone[0] = get_free_block();
     inode->i_nlinks = 2;
     inode->i_time = CUR_TIME;
     if (G.badblocks)
         inode->i_size = 3 * G.dirsize;
     else {
         G.root_block[2 * G.dirsize] = '\0';
         G.root_block[2 * G.dirsize + 1] = '\0';
         inode->i_size = 2 * G.dirsize;
     }
     inode->i_mode = S_IFDIR + 0755;
     inode->i_uid = GETUID;
     if (inode->i_uid)
         inode->i_gid = GETGID;
     write_block(inode->i_zone[0], G.root_block);
 }
References CUR_TIME, G, get_free_block(), GETGID, GETUID, minix1_inode::i_gid, minix1_inode::i_mode, minix1_inode::i_nlinks, minix1_inode::i_size, minix1_inode::i_time, minix1_inode::i_uid, minix1_inode::i_zone, INODE_BUF1, mark_inode, MINIX_ROOT_INO, S_IFDIR, and write_block().
Referenced by mkfs_minix_main().
make_root_inode2()
void make_root_inode2 (void)
Referenced by mkfs_minix_main().
mark_good_blocks()
static void mark_good_blocks (void) static
Definition at line 278 of file mkfs_minix.c.
 {
     int blk;
     for (blk = 0; blk < G.used_good_blocks; blk++)
         mark_zone(G.good_blocks_table[blk]);
 }
References G, and mark_zone.
Referenced by mkfs_minix_main().
minix_bit()
static int minix_bit (const char * a, unsigned i) static
Definition at line 196 of file mkfs_minix.c.
 {
     return a[i >> 3] & (1<<(i & 7));
 }
References i.
minix_clrbit()
static void minix_clrbit (char * a, unsigned i) static
Definition at line 205 of file mkfs_minix.c.
 {
     clrbit(a, i);
 }
References clrbit, and i.
minix_setbit()
static void minix_setbit (char * a, unsigned i) static
Definition at line 201 of file mkfs_minix.c.
 {
     setbit(a, i);
 }
References i, and setbit.
mkfs_minix_main()
int mkfs_minix_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 611 of file mkfs_minix.c.
 {
     unsigned opt;
     char *tmp;
     char *str_i;
     char *listfile = NULL;
     INIT_G();
 /* default (changed to 30, per Linus's suggestion, Sun Nov 21 08:05:07 1993) */
     G.namelen = 30;
     G.dirsize = 32;
     G.magic = MINIX1_SUPER_MAGIC2;
     if (INODE_SIZE1 * MINIX1_INODES_PER_BLOCK != BLOCK_SIZE)
         bb_simple_error_msg_and_die("bad inode size");
 #if ENABLE_FEATURE_MINIX2
     if (INODE_SIZE2 * MINIX2_INODES_PER_BLOCK != BLOCK_SIZE)
         bb_simple_error_msg_and_die("bad inode size");
 #endif
     opt = getopt32(argv, "ci:l:n:+v", &str_i, &listfile, &G.namelen);
     argv += optind;
     //if (opt & 1) -c
     if (opt & 2) G.req_nr_inodes = xatoul(str_i); // -i
     //if (opt & 4) -l
     if (opt & 8) { // -n
         if (G.namelen == 14) G.magic = MINIX1_SUPER_MAGIC;
         else if (G.namelen == 30) G.magic = MINIX1_SUPER_MAGIC2;
         else bb_show_usage();
         G.dirsize = G.namelen + 2;
     }
     if (opt & 0x10) { // -v
 #if ENABLE_FEATURE_MINIX2
         version2 = 1;
 #else
         bb_simple_error_msg_and_die("not compiled with minix v2 support");
 #endif
     }
     G.device_name = argv[0];
     if (!G.device_name)
         bb_show_usage();
     /* Check if it is mounted */
     if (find_mount_point(G.device_name, 0))
         bb_simple_error_msg_and_die("can't format mounted filesystem");
     xmove_fd(xopen(G.device_name, O_RDWR), dev_fd);
     G.total_blocks = get_volume_size_in_bytes(dev_fd, argv[1], 1024, /*extend:*/ 1) / 1024;
     if (G.total_blocks < 10)
         bb_simple_error_msg_and_die("must have at least 10 blocks");
     if (version2) {
         G.magic = MINIX2_SUPER_MAGIC2;
         if (G.namelen == 14)
             G.magic = MINIX2_SUPER_MAGIC;
     } else if (G.total_blocks > 65535)
         G.total_blocks = 65535;
 #if 0
     struct stat statbuf;
     xfstat(dev_fd, &statbuf, G.device_name);
 /* why? */
     if (!S_ISBLK(statbuf.st_mode))
         opt &= ~1; // clear -c (check)
 #if 0
 /* I don't know why someone has special code to prevent mkfs.minix
  * on IDE devices. Why IDE but not SCSI, etc?... */
     else if (statbuf.st_rdev == 0x0300 || statbuf.st_rdev == 0x0340)
         /* what is this? */
         bb_error_msg_and_die("will not try "
             "to make filesystem on '%s'", G.device_name);
 #endif
 #endif
     tmp = G.root_block;
     *(short *) tmp = 1;
     strcpy(tmp + 2, ".");
     tmp += G.dirsize;
     *(short *) tmp = 1;
     strcpy(tmp + 2, "..");
     tmp += G.dirsize;
     *(short *) tmp = 2;
     strcpy(tmp + 2, ".badblocks");
     setup_tables();
     if (opt & 1) // -c ?
         check_blocks();
     else if (listfile)
         get_list_blocks(listfile);
     if (version2) {
         make_root_inode2();
         make_bad_inode2();
     } else {
         make_root_inode();
         make_bad_inode();
     }
     mark_good_blocks();
     write_tables();
     return 0;
 }
References argv, bb_error_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), BLOCK_SIZE, check_blocks(), dev_fd, find_mount_point(), G, get_list_blocks(), get_volume_size_in_bytes(), getopt32(), INIT_G, INODE_SIZE1, INODE_SIZE2, make_bad_inode(), make_bad_inode2(), make_root_inode(), make_root_inode2(), mark_good_blocks(), MINIX1_INODES_PER_BLOCK, MINIX1_SUPER_MAGIC, MINIX1_SUPER_MAGIC2, MINIX2_INODES_PER_BLOCK, MINIX2_SUPER_MAGIC, MINIX2_SUPER_MAGIC2, NULL, O_RDWR, opt, optind, S_ISBLK, setup_tables(), stat::st_mode, stat::st_rdev, strcpy, version2, write_tables(), xfstat(), xmove_fd(), and xopen().
next()
static int next (int zone) static
Definition at line 286 of file mkfs_minix.c.
 {
     if (!zone)
         zone = SB_FIRSTZONE - 1;
     while (++zone < SB_ZONES)
         if (zone_in_use(zone))
             return zone;
     return 0;
 }
References SB_FIRSTZONE, SB_ZONES, and zone_in_use.
Referenced by make_bad_inode().
setup_tables()
static void setup_tables (void) static
Definition at line 539 of file mkfs_minix.c.
 {
     unsigned long inodes;
     unsigned norm_firstzone;
     unsigned sb_zmaps;
     unsigned i;
     /* memset(G.u.superblock_buffer, 0, BLOCK_SIZE); */
     /* memset(G.boot_block_buffer, 0, 512); */
     SB_MAGIC = G.magic;
     SB_ZONE_SIZE = 0;
     SB_MAXSIZE = version2 ? 0x7fffffff : (7 + 512 + 512 * 512) * 1024;
     if (version2)
         SB.s_zones = G.total_blocks;
     else
         SB.s_nzones = G.total_blocks;
     /* some magic nrs: 1 inode / 3 blocks */
     if (G.req_nr_inodes == 0)
         inodes = G.total_blocks / 3;
     else
         inodes = G.req_nr_inodes;
     /* Round up inode count to fill block size */
     if (version2)
         inodes = (inodes + MINIX2_INODES_PER_BLOCK - 1) &
                          ~(MINIX2_INODES_PER_BLOCK - 1);
     else
         inodes = (inodes + MINIX1_INODES_PER_BLOCK - 1) &
                          ~(MINIX1_INODES_PER_BLOCK - 1);
     if (inodes > 65535)
         inodes = 65535;
     SB_INODES = inodes;
     SB_IMAPS = div_roundup(SB_INODES + 1, BITS_PER_BLOCK);
     /* Real bad hack but overwise mkfs.minix can be thrown
      * in infinite loop...
      * try:
      * dd if=/dev/zero of=test.fs count=10 bs=1024
      * mkfs.minix -i 200 test.fs
      */
     /* This code is not insane: NORM_FIRSTZONE is not a constant,
      * it is calculated from SB_INODES, SB_IMAPS and SB_ZMAPS */
     i = 999;
     SB_ZMAPS = 0;
     do {
         norm_firstzone = NORM_FIRSTZONE;
         sb_zmaps = div_roundup(G.total_blocks - norm_firstzone + 1, BITS_PER_BLOCK);
         if (SB_ZMAPS == sb_zmaps) goto got_it;
         SB_ZMAPS = sb_zmaps;
         /* new SB_ZMAPS, need to recalc NORM_FIRSTZONE */
     } while (--i);
     bb_simple_error_msg_and_die("incompatible size/inode count, try different -i N");
  got_it:
     SB_FIRSTZONE = norm_firstzone;
     G.inode_map = xmalloc(SB_IMAPS * BLOCK_SIZE);
     G.zone_map = xmalloc(SB_ZMAPS * BLOCK_SIZE);
     memset(G.inode_map, 0xff, SB_IMAPS * BLOCK_SIZE);
     memset(G.zone_map, 0xff, SB_ZMAPS * BLOCK_SIZE);
     for (i = SB_FIRSTZONE; i < SB_ZONES; i++)
         unmark_zone(i);
     for (i = MINIX_ROOT_INO; i <= SB_INODES; i++)
         unmark_inode(i);
     G.inode_buffer = xzalloc(INODE_BUFFER_SIZE);
     printf("%lu inodes\n", (unsigned long)SB_INODES);
     printf("%lu blocks\n", (unsigned long)SB_ZONES);
     printf("Firstdatazone=%lu (%lu)\n", (unsigned long)SB_FIRSTZONE, (unsigned long)norm_firstzone);
     printf("Zonesize=%u\n", BLOCK_SIZE << SB_ZONE_SIZE);
     printf("Maxsize=%lu\n", (unsigned long)SB_MAXSIZE);
 }
References bb_simple_error_msg_and_die(), BITS_PER_BLOCK, BLOCK_SIZE, div_roundup(), G, i, INODE_BUFFER_SIZE, memset, MINIX1_INODES_PER_BLOCK, MINIX2_INODES_PER_BLOCK, MINIX_ROOT_INO, NORM_FIRSTZONE, printf, SB, SB_FIRSTZONE, SB_IMAPS, SB_INODES, SB_MAGIC, SB_MAXSIZE, SB_ZMAPS, SB_ZONE_SIZE, SB_ZONES, unmark_inode, unmark_zone, version2, xmalloc, and xzalloc().
Referenced by mkfs_minix_main().
write_block()
static void write_block (int blk, char * buffer) static
Definition at line 253 of file mkfs_minix.c.
 {
     xlseek(dev_fd, blk * BLOCK_SIZE, SEEK_SET);
     xwrite(dev_fd, buffer, BLOCK_SIZE);
 }
References BLOCK_SIZE, dev_fd, SEEK_SET, xlseek(), and xwrite().
Referenced by make_bad_inode(), and make_root_inode().
write_tables()
static void write_tables (void) static
Definition at line 223 of file mkfs_minix.c.
 {
     /* Mark the superblock valid. */
     SB.s_state |= MINIX_VALID_FS;
     SB.s_state &= ~MINIX_ERROR_FS;
     msg_eol = "seek to 0 failed";
     xlseek(dev_fd, 0, SEEK_SET);
     msg_eol = "can't clear boot sector";
     xwrite(dev_fd, G.boot_block_buffer, 512);
     msg_eol = "seek to BLOCK_SIZE failed";
     xlseek(dev_fd, BLOCK_SIZE, SEEK_SET);
     msg_eol = "can't write superblock";
     xwrite(dev_fd, G.u.superblock_buffer, BLOCK_SIZE);
     msg_eol = "can't write inode map";
     xwrite(dev_fd, G.inode_map, SB_IMAPS * BLOCK_SIZE);
     msg_eol = "can't write zone map";
     xwrite(dev_fd, G.zone_map, SB_ZMAPS * BLOCK_SIZE);
     msg_eol = "can't write inodes";
     xwrite(dev_fd, G.inode_buffer, INODE_BUFFER_SIZE);
     msg_eol = "\n";
 }
References BLOCK_SIZE, dev_fd, G, INODE_BUFFER_SIZE, MINIX_ERROR_FS, MINIX_VALID_FS, msg_eol, SB, SB_IMAPS, SB_ZMAPS, SEEK_SET, xlseek(), and xwrite().
Referenced by mkfs_minix_main().