Fennix: Kernel/core/memory/heap_allocators/rpmalloc/rpmalloc.h File Reference
rpmalloc.h File Reference
#include <stddef.h>
Data Structures
struct rpmalloc_global_statistics_t
struct rpmalloc_thread_statistics_t
struct rpmalloc_config_t
struct rpmalloc_thread_statistics_t.span_use
Per span count statistics (only if ENABLE_STATISTICS=1)
struct rpmalloc_thread_statistics_t.size_use
Per size class statistics (only if ENABLE_STATISTICS=1)
Macros
#define RPMALLOC_EXPORT
#define RPMALLOC_ALLOCATOR
#define RPMALLOC_ATTRIB_MALLOC
#define RPMALLOC_ATTRIB_ALLOC_SIZE(size)
#define RPMALLOC_ATTRIB_ALLOC_SIZE2(count, size)
#define RPMALLOC_CDECL
#define RPMALLOC_CONFIGURABLE 1
Define RPMALLOC_CONFIGURABLE to enable configuring sizes. Will introduce.
#define RPMALLOC_FIRST_CLASS_HEAPS 0
Define RPMALLOC_FIRST_CLASS_HEAPS to enable heap based API (rpmalloc_heap_* functions).
#define RPMALLOC_NO_PRESERVE 1
Flag to rpaligned_realloc to not preserve content in reallocation.
#define RPMALLOC_GROW_OR_FAIL 2
Flag to rpaligned_realloc to fail and return null pointer if grow cannot be done in-place,.
Typedefs
typedef struct rpmalloc_global_statistics_t rpmalloc_global_statistics_t
typedef struct rpmalloc_thread_statistics_t rpmalloc_thread_statistics_t
typedef struct rpmalloc_config_t rpmalloc_config_t
Functions
RPMALLOC_EXPORT int rpmalloc_initialize (void)
Initialize allocator with default configuration.
RPMALLOC_EXPORT int rpmalloc_initialize_config (const rpmalloc_config_t *config)
Initialize allocator with given configuration.
RPMALLOC_EXPORT const rpmalloc_config_t * rpmalloc_config (void)
Get allocator configuration.
RPMALLOC_EXPORT void rpmalloc_finalize (void)
Finalize allocator.
RPMALLOC_EXPORT void rpmalloc_thread_initialize (void)
Initialize allocator for calling thread.
RPMALLOC_EXPORT void rpmalloc_thread_finalize (int release_caches)
Finalize allocator for calling thread.
RPMALLOC_EXPORT void rpmalloc_thread_collect (void)
Perform deferred deallocations pending for the calling thread heap.
RPMALLOC_EXPORT int rpmalloc_is_thread_initialized (void)
Query if allocator is initialized for calling thread.
RPMALLOC_EXPORT void rpmalloc_thread_statistics (rpmalloc_thread_statistics_t *stats)
Get per-thread statistics.
RPMALLOC_EXPORT void rpmalloc_global_statistics (rpmalloc_global_statistics_t *stats)
Get global statistics.
RPMALLOC_EXPORT void rpmalloc_dump_statistics (void *file)
Dump all statistics in human readable format to file (should be a FILE*)
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rpmalloc (size_t size) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE(1)
Allocate a memory block of at least the given size.
RPMALLOC_EXPORT void rpfree (void *ptr)
Free the given memory block.
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rpcalloc (size_t num, size_t size) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE2(1
Allocate a memory block of at least the given size and zero initialize it.
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rprealloc (void *ptr, size_t size) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE(2)
Reallocate the given block to at least the given size.
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rpaligned_realloc (void *ptr, size_t alignment, size_t size, size_t oldsize, unsigned int flags) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE(3)
Reallocate the given block to at least the given size and alignment,.
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rpaligned_alloc (size_t alignment, size_t size) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE(2)
Allocate a memory block of at least the given size and alignment.
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rpaligned_calloc (size_t alignment, size_t num, size_t size) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE2(2
Allocate a memory block of at least the given size and alignment, and zero initialize it.
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void * rpmemalign (size_t alignment, size_t size) RPMALLOC_ATTRIB_MALLOC RPMALLOC_ATTRIB_ALLOC_SIZE(2)
Allocate a memory block of at least the given size and alignment.
RPMALLOC_EXPORT int rpposix_memalign (void **memptr, size_t alignment, size_t size)
Allocate a memory block of at least the given size and alignment.
RPMALLOC_EXPORT size_t rpmalloc_usable_size (void *ptr)
Query the usable size of the given memory block (from given pointer to the end of block)
Data Structure Documentation
rpmalloc_global_statistics_t
struct rpmalloc_global_statistics_t
Definition at line 69 of file rpmalloc.h.
Data Fields
size_t cached Current amount of memory in global caches for small and medium sizes (<32KiB)
size_t huge_alloc Current amount of memory allocated in huge allocations, i.e larger than LARGE_SIZE_LIMIT which is 2MiB by default (only if ENABLE_STATISTICS=1)
size_t huge_alloc_peak Peak amount of memory allocated in huge allocations, i.e larger than LARGE_SIZE_LIMIT which is 2MiB by default (only if ENABLE_STATISTICS=1)
size_t mapped Current amount of virtual memory mapped, all of which might not have been committed (only if ENABLE_STATISTICS=1)
size_t mapped_peak Peak amount of virtual memory mapped, all of which might not have been committed (only if ENABLE_STATISTICS=1)
size_t mapped_total Total amount of memory mapped since initialization (only if ENABLE_STATISTICS=1)
size_t unmapped_total Total amount of memory unmapped since initialization (only if ENABLE_STATISTICS=1)
rpmalloc_thread_statistics_t
struct rpmalloc_thread_statistics_t
Definition at line 87 of file rpmalloc.h.
Data Fields
size_t global_to_thread Total number of bytes transitioned from global cache to thread cache (only if ENABLE_STATISTICS=1)
struct rpmalloc_thread_statistics_t size_use[128] Per size class statistics (only if ENABLE_STATISTICS=1)
size_t sizecache Current number of bytes available in thread size class caches for small and medium sizes (<32KiB)
struct rpmalloc_thread_statistics_t span_use[64] Per span count statistics (only if ENABLE_STATISTICS=1)
size_t spancache Current number of bytes available in thread span caches for small and medium sizes (<32KiB)
size_t thread_to_global Total number of bytes transitioned from thread cache to global cache (only if ENABLE_STATISTICS=1)
rpmalloc_thread_statistics_t.span_use
struct rpmalloc_thread_statistics_t.span_use
Per span count statistics (only if ENABLE_STATISTICS=1)
Definition at line 98 of file rpmalloc.h.
Data Fields
size_t current Currently used number of spans.
size_t from_cache Number of spans transitioned from thread cache.
size_t from_global Number of spans transitioned from global cache.
size_t from_reserved Number of spans transitioned from reserved state.
size_t map_calls Number of raw memory map calls (not hitting the reserve spans but resulting in actual OS mmap calls)
size_t peak High water mark of spans used.
size_t to_cache Number of spans transitioned to thread cache.
size_t to_global Number of spans transitioned to global cache.
size_t to_reserved Number of spans transitioned to reserved state.
rpmalloc_thread_statistics_t.size_use
struct rpmalloc_thread_statistics_t.size_use
Per size class statistics (only if ENABLE_STATISTICS=1)
Definition at line 120 of file rpmalloc.h.
Data Fields
size_t alloc_current Current number of allocations.
size_t alloc_peak Peak number of allocations.
size_t alloc_total Total number of allocations.
size_t free_total Total number of frees.
size_t map_calls Number of raw memory map calls (not hitting the reserve spans but resulting in actual OS mmap calls)
size_t spans_from_cache Number of spans transitioned from cache.
size_t spans_from_reserved Number of spans transitioned from reserved state.
size_t spans_to_cache Number of spans transitioned to cache.
Macro Definition Documentation
RPMALLOC_ALLOCATOR
#define RPMALLOC_ALLOCATOR
Definition at line 43 of file rpmalloc.h.
RPMALLOC_ATTRIB_ALLOC_SIZE
#define RPMALLOC_ATTRIB_ALLOC_SIZE (size)
Definition at line 45 of file rpmalloc.h.
RPMALLOC_ATTRIB_ALLOC_SIZE2
#define RPMALLOC_ATTRIB_ALLOC_SIZE2 (count, size)
Definition at line 46 of file rpmalloc.h.
RPMALLOC_ATTRIB_MALLOC
#define RPMALLOC_ATTRIB_MALLOC
Definition at line 44 of file rpmalloc.h.
RPMALLOC_CDECL
#define RPMALLOC_CDECL
Definition at line 47 of file rpmalloc.h.
RPMALLOC_CONFIGURABLE
#define RPMALLOC_CONFIGURABLE 1
Define RPMALLOC_CONFIGURABLE to enable configuring sizes. Will introduce.
Definition at line 53 of file rpmalloc.h.
RPMALLOC_EXPORT
#define RPMALLOC_EXPORT
Definition at line 42 of file rpmalloc.h.
RPMALLOC_FIRST_CLASS_HEAPS
#define RPMALLOC_FIRST_CLASS_HEAPS 0
Define RPMALLOC_FIRST_CLASS_HEAPS to enable heap based API (rpmalloc_heap_* functions).
Definition at line 59 of file rpmalloc.h.
RPMALLOC_GROW_OR_FAIL
#define RPMALLOC_GROW_OR_FAIL 2
Flag to rpaligned_realloc to fail and return null pointer if grow cannot be done in-place,.
Definition at line 67 of file rpmalloc.h.
RPMALLOC_NO_PRESERVE
#define RPMALLOC_NO_PRESERVE 1
Flag to rpaligned_realloc to not preserve content in reallocation.
Definition at line 63 of file rpmalloc.h.
Typedef Documentation
rpmalloc_config_t
typedef struct rpmalloc_config_t rpmalloc_config_t
rpmalloc_global_statistics_t
typedef struct rpmalloc_global_statistics_t rpmalloc_global_statistics_t
rpmalloc_thread_statistics_t
typedef struct rpmalloc_thread_statistics_t rpmalloc_thread_statistics_t
Function Documentation
rpaligned_alloc()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rpaligned_alloc (size_t alignment, size_t size)
Allocate a memory block of at least the given size and alignment.
Definition at line 3140 of file rpmalloc.c.
 {
     heap_t *heap = get_thread_heap();
     return _rpmalloc_aligned_allocate(heap, alignment, size);
 }
References _rpmalloc_aligned_allocate(), get_thread_heap(), heap, and size.
Referenced by rpaligned_calloc(), rpmemalign(), and rpposix_memalign().
rpaligned_calloc()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rpaligned_calloc (size_t alignment, size_t num, size_t size)
Allocate a memory block of at least the given size and alignment, and zero initialize it.
rpaligned_realloc()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rpaligned_realloc (void * ptr, size_t alignment, size_t size, size_t oldsize, unsigned int flags)
Reallocate the given block to at least the given size and alignment,.
Definition at line 3129 of file rpmalloc.c.
 {
 #if ENABLE_VALIDATE_ARGS
     assert((size + alignment) >= size && (alignment <= _memory_page_size));
 #endif
     heap_t *heap = get_thread_heap();
     return _rpmalloc_aligned_reallocate(heap, ptr, alignment, size, oldsize, flags);
 }
References _memory_page_size, _rpmalloc_aligned_reallocate(), assert, flags, get_thread_heap(), heap, and size.
rpcalloc()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rpcalloc (size_t num, size_t size)
Allocate a memory block of at least the given size and zero initialize it.
rpfree()
RPMALLOC_EXPORT void rpfree (void * ptr) inline
Free the given memory block.
Definition at line 3096 of file rpmalloc.c.
 {
     _rpmalloc_deallocate(ptr);
 }
References _rpmalloc_deallocate().
Referenced by free().
rpmalloc()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rpmalloc (size_t size) inline
Allocate a memory block of at least the given size.
Definition at line 3086 of file rpmalloc.c.
 {
 #if ENABLE_VALIDATE_ARGS
     assert(size < MAX_ALLOC_SIZE);
 #endif
     heap_t *heap = get_thread_heap();
     return _rpmalloc_allocate(heap, size);
 }
References _rpmalloc_allocate(), assert, get_thread_heap(), heap, MAX_ALLOC_SIZE, and size.
Referenced by malloc().
rpmalloc_config()
RPMALLOC_EXPORT const rpmalloc_config_t* rpmalloc_config (void)
Get allocator configuration.
Definition at line 3078 of file rpmalloc.c.
 {
     return &_memory_config;
 }
References _memory_config.
rpmalloc_dump_statistics()
RPMALLOC_EXPORT void rpmalloc_dump_statistics (void * file)
Dump all statistics in human readable format to file (should be a FILE*)
Definition at line 3335 of file rpmalloc.c.
 {
 #if ENABLE_STATISTICS
     for (size_t list_idx = 0; list_idx < HEAP_ARRAY_SIZE; ++list_idx)
     {
         heap_t *heap = _memory_heaps[list_idx];
         while (heap)
         {
             int need_dump = 0;
             for (size_t iclass = 0; !need_dump && (iclass < SIZE_CLASS_COUNT); ++iclass)
             {
                 if (!atomic_load32(&heap->size_class_use[iclass].alloc_total))
                 {
                     rpmalloc_assert(!atomic_load32(&heap->size_class_use[iclass].free_total), "Heap statistics counter mismatch");
                     rpmalloc_assert(!atomic_load32(&heap->size_class_use[iclass].spans_map_calls), "Heap statistics counter mismatch");
                     continue;
                 }
                 need_dump = 1;
             }
             for (size_t iclass = 0; !need_dump && (iclass < LARGE_CLASS_COUNT); ++iclass)
             {
                 if (!atomic_load32(&heap->span_use[iclass].high) && !atomic_load32(&heap->span_use[iclass].spans_map_calls))
                     continue;
                 need_dump = 1;
             }
             if (need_dump)
                 _memory_heap_dump_statistics(heap, file);
             heap = heap->next_heap;
         }
     }
     fprintf(file, "Global stats:\n");
     size_t huge_current = (size_t)atomic_load32(&_huge_pages_current) * _memory_page_size;
     size_t huge_peak = (size_t)_huge_pages_peak * _memory_page_size;
     fprintf(file, "HugeCurrentMiB HugePeakMiB\n");
     fprintf(file, "%14zu %11zu\n", huge_current / (size_t)(1024 * 1024), huge_peak / (size_t)(1024 * 1024));
     fprintf(file, "GlobalCacheMiB\n");
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         global_cache_t *cache = _memory_span_cache + iclass;
         size_t global_cache = (size_t)cache->count * iclass * _memory_span_size;
         size_t global_overflow_cache = 0;
         span_t *span = cache->overflow;
         while (span)
         {
             global_overflow_cache += iclass * _memory_span_size;
             span = span->next;
         }
         if (global_cache || global_overflow_cache || cache->insert_count || cache->extract_count)
             fprintf(file, "%4zu: %8zuMiB (%8zuMiB overflow) %14zu insert %14zu extract\n", iclass + 1, global_cache / (size_t)(1024 * 1024), global_overflow_cache / (size_t)(1024 * 1024), cache->insert_count, cache->extract_count);
     }
     size_t mapped = (size_t)atomic_load32(&_mapped_pages) * _memory_page_size;
     size_t mapped_os = (size_t)atomic_load32(&_mapped_pages_os) * _memory_page_size;
     size_t mapped_peak = (size_t)_mapped_pages_peak * _memory_page_size;
     size_t mapped_total = (size_t)atomic_load32(&_mapped_total) * _memory_page_size;
     size_t unmapped_total = (size_t)atomic_load32(&_unmapped_total) * _memory_page_size;
     fprintf(file, "MappedMiB MappedOSMiB MappedPeakMiB MappedTotalMiB UnmappedTotalMiB\n");
     fprintf(file, "%9zu %11zu %13zu %14zu %16zu\n",
             mapped / (size_t)(1024 * 1024),
             mapped_os / (size_t)(1024 * 1024),
             mapped_peak / (size_t)(1024 * 1024),
             mapped_total / (size_t)(1024 * 1024),
             unmapped_total / (size_t)(1024 * 1024));
     fprintf(file, "\n");
 #if 0
     int64_t allocated = atomic_load64(&_allocation_counter);
     int64_t deallocated = atomic_load64(&_deallocation_counter);
     fprintf(file, "Allocation count: %lli\n", allocated);
     fprintf(file, "Deallocation count: %lli\n", deallocated);
     fprintf(file, "Current allocations: %lli\n", (allocated - deallocated));
     fprintf(file, "Master spans: %d\n", atomic_load32(&_master_spans));
     fprintf(file, "Dangling master spans: %d\n", atomic_load32(&_unmapped_master_spans));
 #endif
 #endif
     (void)sizeof(file);
 }
References _memory_heaps, _memory_page_size, _memory_span_cache, _memory_span_size, atomic_load64(), global_cache_t::count, fprintf(), heap, HEAP_ARRAY_SIZE, LARGE_CLASS_COUNT, span_t::next, global_cache_t::overflow, rpmalloc_assert, SIZE_CLASS_COUNT, and while().
rpmalloc_finalize()
RPMALLOC_EXPORT void rpmalloc_finalize (void)
Finalize allocator.
Finalize allocator.
Definition at line 2993 of file rpmalloc.c.
 {
     rpmalloc_thread_finalize(1);
     // rpmalloc_dump_statistics(stdout);
     if (_memory_global_reserve)
     {
         atomic_add32(&_memory_global_reserve_master->remaining_spans, -(int32_t)_memory_global_reserve_count);
         _memory_global_reserve_master = 0;
         _memory_global_reserve_count = 0;
         _memory_global_reserve = 0;
     }
     atomic_store32_release(&_memory_global_lock, 0);
     // Free all thread caches and fully free spans
     for (size_t list_idx = 0; list_idx < HEAP_ARRAY_SIZE; ++list_idx)
     {
         heap_t *heap = _memory_heaps[list_idx];
         while (heap)
         {
             heap_t *next_heap = heap->next_heap;
             heap->finalize = 1;
             _rpmalloc_heap_global_finalize(heap);
             heap = next_heap;
         }
     }
 #if ENABLE_GLOBAL_CACHE
     // Free global caches
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
         _rpmalloc_global_cache_finalize(&_memory_span_cache[iclass]);
 #endif
 #if (defined(__APPLE__) || defined(__HAIKU__)) && ENABLE_PRELOAD
     pthread_key_delete(_memory_thread_heap);
 #endif
 #if defined(_WIN32) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
     FlsFree(fls_key);
     fls_key = 0;
 #endif
 #if ENABLE_STATISTICS
     // If you hit these asserts you probably have memory leaks (perhaps global scope data doing dynamic allocations) or double frees in your code
     rpmalloc_assert(atomic_load32(&_mapped_pages) == 0, "Memory leak detected");
     rpmalloc_assert(atomic_load32(&_mapped_pages_os) == 0, "Memory leak detected");
 #endif
     _rpmalloc_initialized = 0;
 }
References _memory_global_lock, _memory_global_reserve, _memory_global_reserve_count, _memory_global_reserve_master, _memory_heaps, _memory_span_cache, _memory_thread_heap, _rpmalloc_global_cache_finalize(), _rpmalloc_heap_global_finalize(), _rpmalloc_initialized, atomic_add32(), atomic_store32_release(), heap, HEAP_ARRAY_SIZE, LARGE_CLASS_COUNT, pthread_key_delete(), span_t::remaining_spans, rpmalloc_assert, and rpmalloc_thread_finalize().
rpmalloc_global_statistics()
RPMALLOC_EXPORT void rpmalloc_global_statistics (rpmalloc_global_statistics_t * stats)
Get global statistics.
Definition at line 3262 of file rpmalloc.c.
 {
     memset_unsafe(stats, 0, sizeof(rpmalloc_global_statistics_t));
 #if ENABLE_STATISTICS
     stats->mapped = (size_t)atomic_load32(&_mapped_pages) * _memory_page_size;
     stats->mapped_peak = (size_t)_mapped_pages_peak * _memory_page_size;
     stats->mapped_total = (size_t)atomic_load32(&_mapped_total) * _memory_page_size;
     stats->unmapped_total = (size_t)atomic_load32(&_unmapped_total) * _memory_page_size;
     stats->huge_alloc = (size_t)atomic_load32(&_huge_pages_current) * _memory_page_size;
     stats->huge_alloc_peak = (size_t)_huge_pages_peak * _memory_page_size;
 #endif
 #if ENABLE_GLOBAL_CACHE
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
         stats->cached += _memory_span_cache[iclass].count * (iclass + 1) * _memory_span_size;
 #endif
 }
References _memory_page_size, _memory_span_cache, _memory_span_size, rpmalloc_global_statistics_t::cached, global_cache_t::count, rpmalloc_global_statistics_t::huge_alloc, rpmalloc_global_statistics_t::huge_alloc_peak, LARGE_CLASS_COUNT, rpmalloc_global_statistics_t::mapped, rpmalloc_global_statistics_t::mapped_peak, rpmalloc_global_statistics_t::mapped_total, memset_unsafe(), and rpmalloc_global_statistics_t::unmapped_total.
rpmalloc_initialize()
RPMALLOC_EXPORT int rpmalloc_initialize (void) inline
Initialize allocator with default configuration.
Initialize allocator with default configuration.
Definition at line 2814 of file rpmalloc.c.
 {
     if (_rpmalloc_initialized)
     {
         rpmalloc_thread_initialize();
         return 0;
     }
     return rpmalloc_initialize_config(0);
 }
References _rpmalloc_initialized, rpmalloc_initialize_config(), and rpmalloc_thread_initialize().
Referenced by get_thread_heap(), and InitializeMemoryManagement().
rpmalloc_initialize_config()
RPMALLOC_EXPORT int rpmalloc_initialize_config (const rpmalloc_config_t * config)
Initialize allocator with given configuration.
Definition at line 2824 of file rpmalloc.c.
 {
     if (_rpmalloc_initialized)
     {
         rpmalloc_thread_initialize();
         return 0;
     }
     _rpmalloc_initialized = 1;
     if (config)
         memcpy_unsafe(&_memory_config, config, sizeof(rpmalloc_config_t));
     else
         memset_unsafe(&_memory_config, 0, sizeof(rpmalloc_config_t));
     if (!_memory_config.memory_map || !_memory_config.memory_unmap)
     {
         _memory_config.memory_map = _rpmalloc_mmap_os;
         _memory_config.memory_unmap = _rpmalloc_unmap_os;
     }
     _memory_map_granularity = (size_t)__rpmalloc_sysconf(_SC_PAGESIZE);
 #if RPMALLOC_CONFIGURABLE
     _memory_page_size = _memory_config.page_size;
 #else
     _memory_page_size = 0;
 #endif
     _memory_huge_pages = 0;
     if (!_memory_page_size)
     {
         _memory_page_size = _memory_map_granularity;
         if (_memory_config.enable_huge_pages)
         {
 #if defined(__linux__)
             size_t huge_page_size = 0;
             FILE *meminfo = fopen("/proc/meminfo", "r");
             if (meminfo)
             {
                 char line[128];
                 while (!huge_page_size && fgets(line, sizeof(line) - 1, meminfo))
                 {
                     line[sizeof(line) - 1] = 0;
                     if (strstr(line, "Hugepagesize:"))
                         huge_page_size = (size_t)strtol(line + 13, 0, 10) * 1024;
                 }
                 fclose(meminfo);
             }
             if (huge_page_size)
             {
                 _memory_huge_pages = 1;
                 _memory_page_size = huge_page_size;
                 _memory_map_granularity = huge_page_size;
             }
 #endif
         }
     }
     else
     {
         if (_memory_config.enable_huge_pages)
             _memory_huge_pages = 1;
     }
     size_t min_span_size = 256;
     size_t max_page_size;
 #if UINTPTR_MAX > 0xFFFFFFFF
     max_page_size = 4096ULL * 1024ULL * 1024ULL;
 #else
     max_page_size = 4 * 1024 * 1024;
 #endif
     if (_memory_page_size < min_span_size)
         _memory_page_size = min_span_size;
     if (_memory_page_size > max_page_size)
         _memory_page_size = max_page_size;
     _memory_page_size_shift = 0;
     size_t page_size_bit = _memory_page_size;
     while (page_size_bit != 1)
     {
         ++_memory_page_size_shift;
         page_size_bit >>= 1;
     }
     _memory_page_size = ((size_t)1 << _memory_page_size_shift);
 #if RPMALLOC_CONFIGURABLE
     if (!_memory_config.span_size)
     {
         _memory_span_size = _memory_default_span_size;
         _memory_span_size_shift = _memory_default_span_size_shift;
         _memory_span_mask = _memory_default_span_mask;
     }
     else
     {
         size_t span_size = _memory_config.span_size;
         if (span_size > (256 * 1024))
             span_size = (256 * 1024);
         _memory_span_size = 4096;
         _memory_span_size_shift = 12;
         while (_memory_span_size < span_size)
         {
             _memory_span_size <<= 1;
             ++_memory_span_size_shift;
         }
         _memory_span_mask = ~(uintptr_t)(_memory_span_size - 1);
     }
 #endif
     _memory_span_map_count = (_memory_config.span_map_count ? _memory_config.span_map_count : DEFAULT_SPAN_MAP_COUNT);
     if ((_memory_span_size * _memory_span_map_count) < _memory_page_size)
         _memory_span_map_count = (_memory_page_size / _memory_span_size);
     if ((_memory_page_size >= _memory_span_size) && ((_memory_span_map_count * _memory_span_size) % _memory_page_size))
         _memory_span_map_count = (_memory_page_size / _memory_span_size);
     _memory_heap_reserve_count = (_memory_span_map_count > DEFAULT_SPAN_MAP_COUNT) ? DEFAULT_SPAN_MAP_COUNT : _memory_span_map_count;
     _memory_config.page_size = _memory_page_size;
     _memory_config.span_size = _memory_span_size;
     _memory_config.span_map_count = _memory_span_map_count;
     _memory_config.enable_huge_pages = _memory_huge_pages;
 #if ((defined(__APPLE__) || defined(__HAIKU__)) && ENABLE_PRELOAD) || defined(__TINYC__)
     if (pthread_key_create(&_memory_thread_heap, _rpmalloc_heap_release_raw_fc))
         return -1;
 #endif
     // Setup all small and medium size classes
     size_t iclass = 0;
     _memory_size_class[iclass].block_size = SMALL_GRANULARITY;
     _rpmalloc_adjust_size_class(iclass);
     for (iclass = 1; iclass < SMALL_CLASS_COUNT; ++iclass)
     {
         size_t size = iclass * SMALL_GRANULARITY;
         _memory_size_class[iclass].block_size = (uint32_t)size;
         _rpmalloc_adjust_size_class(iclass);
     }
     // At least two blocks per span, then fall back to large allocations
     _memory_medium_size_limit = (_memory_span_size - SPAN_HEADER_SIZE) >> 1;
     if (_memory_medium_size_limit > MEDIUM_SIZE_LIMIT)
         _memory_medium_size_limit = MEDIUM_SIZE_LIMIT;
     for (iclass = 0; iclass < MEDIUM_CLASS_COUNT; ++iclass)
     {
         size_t size = SMALL_SIZE_LIMIT + ((iclass + 1) * MEDIUM_GRANULARITY);
         if (size > _memory_medium_size_limit)
             break;
         _memory_size_class[SMALL_CLASS_COUNT + iclass].block_size = (uint32_t)size;
         _rpmalloc_adjust_size_class(SMALL_CLASS_COUNT + iclass);
     }
     _memory_orphan_heaps = 0;
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _memory_first_class_orphan_heaps = 0;
 #endif
 #if ENABLE_STATISTICS
     atomic_store32(&_memory_active_heaps, 0);
     atomic_store32(&_mapped_pages, 0);
     _mapped_pages_peak = 0;
     atomic_store32(&_master_spans, 0);
     atomic_store32(&_mapped_total, 0);
     atomic_store32(&_unmapped_total, 0);
     atomic_store32(&_mapped_pages_os, 0);
     atomic_store32(&_huge_pages_current, 0);
     _huge_pages_peak = 0;
 #endif
     memset_unsafe(_memory_heaps, 0, sizeof(_memory_heaps));
     atomic_store32_release(&_memory_global_lock, 0);
     // Initialize this thread
     rpmalloc_thread_initialize();
     return 0;
 }
References __rpmalloc_sysconf(), _memory_config, _memory_default_span_mask, _memory_default_span_size, _memory_default_span_size_shift, _memory_global_lock, _memory_heap_reserve_count, _memory_heaps, _memory_huge_pages, _memory_map_granularity, _memory_medium_size_limit, _memory_orphan_heaps, _memory_page_size, _memory_page_size_shift, _memory_size_class, _memory_span_map_count, _memory_span_mask, _memory_span_size, _memory_span_size_shift, _memory_thread_heap, _rpmalloc_adjust_size_class(), _rpmalloc_heap_release_raw_fc(), _rpmalloc_initialized, _rpmalloc_mmap_os(), _rpmalloc_unmap_os(), _SC_PAGESIZE, atomic_store32(), atomic_store32_release(), size_class_t::block_size, DEFAULT_SPAN_MAP_COUNT, rpmalloc_config_t::enable_huge_pages, fclose(), fgets, fopen(), line, MEDIUM_CLASS_COUNT, MEDIUM_GRANULARITY, MEDIUM_SIZE_LIMIT, memcpy_unsafe(), rpmalloc_config_t::memory_map, rpmalloc_config_t::memory_unmap, memset_unsafe(), rpmalloc_config_t::page_size, pthread_key_create(), rpmalloc_thread_initialize(), size, SMALL_CLASS_COUNT, SMALL_GRANULARITY, SMALL_SIZE_LIMIT, SPAN_HEADER_SIZE, rpmalloc_config_t::span_map_count, rpmalloc_config_t::span_size, strstr(), and strtol().
Referenced by InitializeMemoryManagement(), and rpmalloc_initialize().
rpmalloc_is_thread_initialized()
RPMALLOC_EXPORT int rpmalloc_is_thread_initialized (void)
Query if allocator is initialized for calling thread.
Definition at line 3072 of file rpmalloc.c.
 {
     return (get_thread_heap_raw() != 0) ? 1 : 0;
 }
References get_thread_heap_raw().
rpmalloc_thread_collect()
RPMALLOC_EXPORT void rpmalloc_thread_collect (void) inline
Perform deferred deallocations pending for the calling thread heap.
Definition at line 3185 of file rpmalloc.c.
 {
 }
rpmalloc_thread_finalize()
RPMALLOC_EXPORT void rpmalloc_thread_finalize (int release_caches)
Finalize allocator for calling thread.
Finalize allocator for calling thread.
Definition at line 3061 of file rpmalloc.c.
 {
     heap_t *heap = get_thread_heap_raw();
     if (heap)
         _rpmalloc_heap_release_raw(heap, release_caches);
     set_thread_heap(0);
 #if defined(_WIN32) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
     FlsSetValue(fls_key, 0);
 #endif
 }
References _rpmalloc_heap_release_raw(), get_thread_heap_raw(), heap, and set_thread_heap().
Referenced by rpmalloc_finalize().
rpmalloc_thread_initialize()
RPMALLOC_EXPORT void rpmalloc_thread_initialize (void) inline
Initialize allocator for calling thread.
Initialize allocator for calling thread.
Definition at line 3044 of file rpmalloc.c.
 {
     if (!get_thread_heap_raw())
     {
         heap_t *heap = _rpmalloc_heap_allocate(0);
         if (heap)
         {
             _rpmalloc_stat_inc(&_memory_active_heaps);
             set_thread_heap(heap);
 #if defined(_WIN32) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
             FlsSetValue(fls_key, heap);
 #endif
         }
     }
 }
References _rpmalloc_heap_allocate(), _rpmalloc_stat_inc, get_thread_heap_raw(), heap, and set_thread_heap().
Referenced by rpmalloc_initialize(), and rpmalloc_initialize_config().
rpmalloc_thread_statistics()
RPMALLOC_EXPORT void rpmalloc_thread_statistics (rpmalloc_thread_statistics_t * stats)
Get per-thread statistics.
Definition at line 3189 of file rpmalloc.c.
 {
     memset_unsafe(stats, 0, sizeof(rpmalloc_thread_statistics_t));
     heap_t *heap = get_thread_heap_raw();
     if (!heap)
         return;
     for (size_t iclass = 0; iclass < SIZE_CLASS_COUNT; ++iclass)
     {
         size_class_t *size_class = _memory_size_class + iclass;
         span_t *span = heap->size_class[iclass].partial_span;
         while (span)
         {
             size_t free_count = span->list_size;
             size_t block_count = size_class->block_count;
             if (span->free_list_limit < block_count)
                 block_count = span->free_list_limit;
             free_count += (block_count - span->used_count);
             stats->sizecache = free_count * size_class->block_size;
             span = span->next;
         }
     }
 #if ENABLE_THREAD_CACHE
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         span_cache_t *span_cache;
         if (!iclass)
             span_cache = &heap->span_cache;
         else
             span_cache = (span_cache_t *)(heap->span_large_cache + (iclass - 1));
         stats->spancache = span_cache->count * (iclass + 1) * _memory_span_size;
     }
 #endif
     span_t *deferred = (span_t *)atomic_load_ptr(&heap->span_free_deferred);
     while (deferred)
     {
         if (deferred->size_class != SIZE_CLASS_HUGE)
             stats->spancache = (size_t)deferred->span_count * _memory_span_size;
         deferred = (span_t *)deferred->free_list;
     }
 #if ENABLE_STATISTICS
     stats->thread_to_global = (size_t)atomic_load64(&heap->thread_to_global);
     stats->global_to_thread = (size_t)atomic_load64(&heap->global_to_thread);
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         stats->span_use[iclass].current = (size_t)atomic_load32(&heap->span_use[iclass].current);
         stats->span_use[iclass].peak = (size_t)atomic_load32(&heap->span_use[iclass].high);
         stats->span_use[iclass].to_global = (size_t)atomic_load32(&heap->span_use[iclass].spans_to_global);
         stats->span_use[iclass].from_global = (size_t)atomic_load32(&heap->span_use[iclass].spans_from_global);
         stats->span_use[iclass].to_cache = (size_t)atomic_load32(&heap->span_use[iclass].spans_to_cache);
         stats->span_use[iclass].from_cache = (size_t)atomic_load32(&heap->span_use[iclass].spans_from_cache);
         stats->span_use[iclass].to_reserved = (size_t)atomic_load32(&heap->span_use[iclass].spans_to_reserved);
         stats->span_use[iclass].from_reserved = (size_t)atomic_load32(&heap->span_use[iclass].spans_from_reserved);
         stats->span_use[iclass].map_calls = (size_t)atomic_load32(&heap->span_use[iclass].spans_map_calls);
     }
     for (size_t iclass = 0; iclass < SIZE_CLASS_COUNT; ++iclass)
     {
         stats->size_use[iclass].alloc_current = (size_t)atomic_load32(&heap->size_class_use[iclass].alloc_current);
         stats->size_use[iclass].alloc_peak = (size_t)heap->size_class_use[iclass].alloc_peak;
         stats->size_use[iclass].alloc_total = (size_t)atomic_load32(&heap->size_class_use[iclass].alloc_total);
         stats->size_use[iclass].free_total = (size_t)atomic_load32(&heap->size_class_use[iclass].free_total);
         stats->size_use[iclass].spans_to_cache = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_to_cache);
         stats->size_use[iclass].spans_from_cache = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_from_cache);
         stats->size_use[iclass].spans_from_reserved = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_from_reserved);
         stats->size_use[iclass].map_calls = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_map_calls);
     }
 #endif
 }
References _memory_size_class, _memory_span_size, atomic_load64(), atomic_load_ptr(), size_class_t::block_count, size_class_t::block_size, span_cache_t::count, span_t::free_list, span_t::free_list_limit, get_thread_heap_raw(), rpmalloc_thread_statistics_t::global_to_thread, heap, LARGE_CLASS_COUNT, span_t::list_size, memset_unsafe(), span_t::next, span_t::size_class, SIZE_CLASS_COUNT, SIZE_CLASS_HUGE, rpmalloc_thread_statistics_t::size_use, rpmalloc_thread_statistics_t::sizecache, span_t::span_count, rpmalloc_thread_statistics_t::span_use, rpmalloc_thread_statistics_t::spancache, rpmalloc_thread_statistics_t::thread_to_global, and span_t::used_count.
rpmalloc_usable_size()
RPMALLOC_EXPORT size_t rpmalloc_usable_size (void * ptr) inline
Query the usable size of the given memory block (from given pointer to the end of block)
Definition at line 3179 of file rpmalloc.c.
 {
     return (ptr ? _rpmalloc_usable_size(ptr) : 0);
 }
References _rpmalloc_usable_size().
rpmemalign()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rpmemalign (size_t alignment, size_t size) inline
Allocate a memory block of at least the given size and alignment.
Definition at line 3163 of file rpmalloc.c.
 {
     return rpaligned_alloc(alignment, size);
 }
References rpaligned_alloc(), and size.
rpposix_memalign()
RPMALLOC_EXPORT int rpposix_memalign (void ** memptr, size_t alignment, size_t size) inline
Allocate a memory block of at least the given size and alignment.
Definition at line 3169 of file rpmalloc.c.
 {
     if (memptr)
         *memptr = rpaligned_alloc(alignment, size);
     else
         return EINVAL;
     return *memptr ? 0 : ENOMEM;
 }
References EINVAL, ENOMEM, rpaligned_alloc(), and size.
rprealloc()
RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void RPMALLOC_EXPORT RPMALLOC_ALLOCATOR void* rprealloc (void * ptr, size_t size) inline
Reallocate the given block to at least the given size.
Definition at line 3119 of file rpmalloc.c.
 {
 #if ENABLE_VALIDATE_ARGS
     assert(size < MAX_ALLOC_SIZE);
 #endif
     heap_t *heap = get_thread_heap();
     return _rpmalloc_reallocate(heap, ptr, size, 0, 0);
 }
References _rpmalloc_reallocate(), assert, get_thread_heap(), heap, MAX_ALLOC_SIZE, and size.
Referenced by realloc().