Fennix Userspace: Userspace/musl/src/legacy/daemon.c File Reference
daemon.c File Reference
#include <fcntl.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE
Functions
int daemon (int nochdir, int noclose)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file daemon.c.
Function Documentation
daemon()
int daemon (int nochdir, int noclose)
Definition at line 5 of file daemon.c.
 {
     if (!nochdir && chdir("/"))
         return -1;
     if (!noclose) {
         int fd, failed = 0;
         if ((fd = open("/dev/null", O_RDWR)) < 0) return -1;
         if (dup2(fd, 0) < 0 || dup2(fd, 1) < 0 || dup2(fd, 2) < 0)
             failed++;
         if (fd > 2) close(fd);
         if (failed) return -1;
     }
     switch(fork()) {
     case 0: break;
     case -1: return -1;
     default: _exit(0);
     }
     if (setsid() < 0) return -1;
     switch(fork()) {
     case 0: break;
     case -1: return -1;
     default: _exit(0);
     }
     return 0;
 }
References _exit(), chdir(), close(), dup2(), fd, fork(), O_RDWR, open(), and setsid().
Referenced by nbdclient_main().