Fennix: Userspace/apps/base/busybox/networking/libiproute/utils.c File Reference
utils.c File Reference
#include "libbb.h"
#include "utils.h"
#include "inet_common.h"
Functions
unsigned FAST_FUNC get_hz (void)
unsigned FAST_FUNC get_unsigned (char *arg, const char *errmsg)
uint32_t FAST_FUNC get_u32 (char *arg, const char *errmsg)
uint16_t FAST_FUNC get_u16 (char *arg, const char *errmsg)
int FAST_FUNC get_addr_1 (inet_prefix *addr, char *name, int family)
static void get_prefix_1 (inet_prefix *dst, char *arg, int family)
int FAST_FUNC get_addr (inet_prefix *dst, char *arg, int family)
void FAST_FUNC get_prefix (inet_prefix *dst, char *arg, int family)
uint32_t FAST_FUNC get_addr32 (char *name)
char **FAST_FUNC next_arg (char **argv)
void FAST_FUNC invarg_1_to_2 (const char *arg, const char *opt)
void FAST_FUNC duparg (const char *key, const char *arg)
void FAST_FUNC duparg2 (const char *key, const char *arg)
int FAST_FUNC inet_addr_match (const inet_prefix *a, const inet_prefix *b, int bits)
const char *FAST_FUNC rt_addr_n2a (int af, void *addr)
Function Documentation
duparg()
void FAST_FUNC duparg (const char * key, const char * arg)
Definition at line 242 of file utils.c.
 {
     bb_error_msg_and_die("duplicate \"%s\": \"%s\" is the second value", key, arg);
 }
References bb_error_msg_and_die().
Referenced by do_add_or_delete(), do_set(), ipaddr_modify(), and tc_main().
duparg2()
void FAST_FUNC duparg2 (const char * key, const char * arg)
Definition at line 247 of file utils.c.
 {
     bb_error_msg_and_die("either \"%s\" is duplicate, or \"%s\" is garbage", key, arg);
 }
References bb_error_msg_and_die().
Referenced by do_set(), ipaddr_list_or_flush(), ipaddr_modify(), iproute_modify(), parse_args(), and tc_main().
get_addr()
int FAST_FUNC get_addr (inet_prefix * dst, char * arg, int family)
Definition at line 201 of file utils.c.
 {
     if (family == AF_PACKET) {
         bb_error_msg_and_die("\"%s\" may be inet %s, but it is not allowed in this context", arg, "address");
     }
     if (get_addr_1(dst, arg, family)) {
         bb_error_msg_and_die("an %s %s is expected rather than \"%s\"", "inet", "address", arg);
     }
     return 0;
 }
References AF_PACKET, bb_error_msg_and_die(), dst, and get_addr_1().
Referenced by ipaddr_modify(), and iproute_modify().
get_addr32()
uint32_t FAST_FUNC get_addr32 (char * name)
Definition at line 220 of file utils.c.
 {
     inet_prefix addr;
     if (get_addr_1(&addr, name, AF_INET)) {
         bb_error_msg_and_die("an %s %s is expected rather than \"%s\"", "IP", "address", name);
     }
     return addr.data[0];
 }
References addr, AF_INET, bb_error_msg_and_die(), and get_addr_1().
Referenced by iprule_modify(), and parse_args().
get_addr_1()
int FAST_FUNC get_addr_1 (inet_prefix * addr, char * name, int family)
Definition at line 82 of file utils.c.
 {
     memset(addr, 0, sizeof(*addr));
     if (strcmp(name, "default") == 0
      || strcmp(name, "all") == 0
      || strcmp(name, "any") == 0
     ) {
         addr->family = family;
         addr->bytelen = (family == AF_INET6 ? 16 : 4);
         addr->bitlen = -1;
         return 0;
     }
     if (strchr(name, ':')) {
         addr->family = AF_INET6;
         if (family != AF_UNSPEC && family != AF_INET6)
             return -1;
         if (inet_pton(AF_INET6, name, addr->data) <= 0)
             return -1;
         addr->bytelen = 16;
         addr->bitlen = -1;
         return 0;
     }
     if (family != AF_UNSPEC && family != AF_INET)
         return -1;
     /* Try to parse it as IPv4 */
     addr->family = AF_INET;
 #if 0 /* Doesn't handle e.g. "10.10", for example, "ip r l root 10.10/16" */
     if (inet_pton(AF_INET, name, addr->data) <= 0)
         return -1;
 #else
     {
         unsigned i = 0;
         unsigned n = 0;
         const char *cp = name - 1;
         while (*++cp) {
             if ((unsigned char)(*cp - '0') <= 9) {
                 n = 10 * n + (unsigned char)(*cp - '0');
                 if (n >= 256)
                     return -1;
                 ((uint8_t*)addr->data)[i] = n;
                 continue;
             }
             if (*cp == '.' && ++i <= 3) {
                 n = 0;
                 continue;
             }
             return -1;
         }
     }
 #endif
     addr->bytelen = 4;
     addr->bitlen = -1;
     return 0;
 }
References addr, AF_INET, AF_INET6, AF_UNSPEC, i, inet_pton(), memset, n, strchr(), and strcmp.
Referenced by get_addr(), get_addr32(), get_prefix_1(), and ll_addr_a2n().
get_hz()
unsigned FAST_FUNC get_hz (void)
Definition at line 15 of file utils.c.
 {
     static unsigned hz_internal;
     FILE *fp;
     if (hz_internal)
         return hz_internal;
     fp = fopen_for_read("/proc/net/psched");
     if (fp) {
         unsigned nom, denom;
         if (fscanf(fp, "%*08x%*08x%08x%08x", &nom, &denom) == 2)
             if (nom == 1000000)
                 hz_internal = denom;
         fclose(fp);
     }
     if (!hz_internal)
         hz_internal = bb_clk_tck();
     return hz_internal;
 }
References bb_clk_tck(), fclose(), fopen_for_read(), and fscanf().
Referenced by print_neigh(), and print_route().
get_prefix()
void FAST_FUNC get_prefix (inet_prefix * dst, char * arg, int family)
Definition at line 212 of file utils.c.
 {
     if (family == AF_PACKET) {
         bb_error_msg_and_die("\"%s\" may be inet %s, but it is not allowed in this context", arg, "prefix");
     }
     get_prefix_1(dst, arg, family);
 }
References AF_PACKET, bb_error_msg_and_die(), dst, and get_prefix_1().
get_prefix_1()
static void get_prefix_1 (inet_prefix * dst, char * arg, int family) static
Definition at line 142 of file utils.c.
 {
     char *slash;
     memset(dst, 0, sizeof(*dst));
     if (strcmp(arg, "default") == 0
      || strcmp(arg, "all") == 0
      || strcmp(arg, "any") == 0
     ) {
         dst->family = family;
         /*dst->bytelen = 0; - done by memset */
         /*dst->bitlen = 0;*/
         return;
     }
     slash = strchr(arg, '/');
     if (slash)
         *slash = '\0';
     if (get_addr_1(dst, arg, family) == 0) {
         dst->bitlen = (dst->family == AF_INET6) ? 128 : 32;
         if (slash) {
             unsigned plen;
             inet_prefix netmask_pfx;
             netmask_pfx.family = AF_UNSPEC;
             plen = bb_strtou(slash + 1, NULL, 0);
             if ((errno || plen > dst->bitlen)
              && get_addr_1(&netmask_pfx, slash + 1, family) != 0
             ) {
                 goto bad;
             }
             if (netmask_pfx.family == AF_INET) {
                 /* fill in prefix length of dotted quad */
                 uint32_t mask = ntohl(netmask_pfx.data[0]);
                 uint32_t host = ~mask;
                 /* a valid netmask must be 2^n - 1 */
                 if (host & (host + 1))
                     goto bad;
                 for (plen = 0; mask; mask <<= 1)
                     ++plen;
                 if (plen > dst->bitlen)
                     goto bad;
                 /* dst->flags |= PREFIXLEN_SPECIFIED; */
             }
             dst->bitlen = plen;
         }
     }
     if (slash)
         *slash = '/';
     return;
  bad:
     bb_error_msg_and_die("an %s %s is expected rather than \"%s\"", "inet", "prefix", arg);
 }
References AF_INET, AF_INET6, AF_UNSPEC, bb_error_msg_and_die(), bb_strtou(), inet_prefix::data, dst, errno, inet_prefix::family, get_addr_1(), memset, ntohl(), NULL, strchr(), and strcmp.
Referenced by get_prefix().
get_u16()
uint16_t FAST_FUNC get_u16 (char * arg, const char * errmsg)
Definition at line 67 of file utils.c.
 {
     unsigned long res;
     char *ptr;
     if (*arg) {
         res = strtoul(arg, &ptr, 0);
 //FIXME: "" will be accepted too, is it correct?!
         if (!*ptr && res <= 0xFFFF) {
             return res;
         }
     }
     invarg_1_to_2(arg, errmsg); /* does not return */
 }
References errmsg(), invarg_1_to_2(), and strtoul().
Referenced by vlan_parse_opt().
get_u32()
uint32_t FAST_FUNC get_u32 (char * arg, const char * errmsg)
Definition at line 52 of file utils.c.
 {
     unsigned long res;
     char *ptr;
     if (*arg) {
         res = strtoul(arg, &ptr, 0);
 //FIXME: "" will be accepted too, is it correct?!
         if (!*ptr && res <= 0xFFFFFFFFUL) {
             return res;
         }
     }
     invarg_1_to_2(arg, errmsg); /* does not return */
 }
References errmsg(), invarg_1_to_2(), and strtoul().
Referenced by iproute_modify(), iprule_modify(), set_lifetime(), tc_main(), and vrf_parse_opt().
get_unsigned()
unsigned FAST_FUNC get_unsigned (char * arg, const char * errmsg)
Definition at line 37 of file utils.c.
 {
     unsigned long res;
     char *ptr;
     if (*arg) {
         res = strtoul(arg, &ptr, 0);
 //FIXME: "" will be accepted too, is it correct?!
         if (!*ptr && res <= UINT_MAX) {
             return res;
         }
     }
     invarg_1_to_2(arg, errmsg); /* does not return */
 }
References errmsg(), invarg_1_to_2(), strtoul(), and UINT_MAX.
Referenced by do_set(), iproute_modify(), and parse_args().
inet_addr_match()
int FAST_FUNC inet_addr_match (const inet_prefix * a, const inet_prefix * b, int bits)
Definition at line 252 of file utils.c.
 {
     const uint32_t *a1 = a->data;
     const uint32_t *a2 = b->data;
     int words = bits >> 5;
     bits &= 0x1f;
     if (words)
         if (memcmp(a1, a2, words << 2))
             return -1;
     if (bits) {
         uint32_t w1, w2;
         uint32_t mask;
         w1 = a1[words];
         w2 = a2[words];
         mask = htonl((0xffffffff) << (0x20 - bits));
         if ((w1 ^ w2) & mask)
             return 1;
     }
     return 0;
 }
References a1, a2, inet_prefix::data, htonl(), memcmp(), w1, and w2.
Referenced by ipaddr_list_or_flush(), print_addrinfo(), print_neigh(), and print_route().
invarg_1_to_2()
void FAST_FUNC invarg_1_to_2 (const char * arg, const char * opt)
Definition at line 237 of file utils.c.
 {
     bb_error_msg_and_die(bb_msg_invalid_arg_to, arg, opt);
 }
References bb_error_msg_and_die(), and opt.
Referenced by do_add_or_delete(), do_ipaddr(), do_iplink(), do_ipneigh(), do_iproute(), do_iprule(), do_iptunnel(), do_set(), get_u16(), get_u32(), get_unsigned(), ip_parse_common_args(), ipaddr_list_or_flush(), ipaddr_modify(), iproute_list_or_flush(), iproute_modify(), iprule_modify(), parse_args(), slattach_main(), tc_main(), vlan_parse_opt(), and vrf_parse_opt().
next_arg()
char** FAST_FUNC next_arg (char ** argv)
Definition at line 230 of file utils.c.
 {
     if (!*++argv)
         bb_simple_error_msg_and_die("command line is not complete, try \"help\"");
     return argv;
 }
References argv, and bb_simple_error_msg_and_die().
rt_addr_n2a()
const char* FAST_FUNC rt_addr_n2a (int af, void * addr)
Definition at line 280 of file utils.c.
 {
     switch (af) {
     case AF_INET:
     case AF_INET6:
         return inet_ntop(af, addr,
             auto_string(xzalloc(INET6_ADDRSTRLEN)), INET6_ADDRSTRLEN
         );
     default:
         return "???";
     }
 }
References addr, AF_INET, AF_INET6, auto_string(), INET6_ADDRSTRLEN, inet_ntop(), and xzalloc().
Referenced by print_addrinfo(), print_route(), and print_rule().