Fennix: Userspace/mlibc/options/bsd/generic/arpa-nameser-stubs.cpp File Reference
arpa-nameser-stubs.cpp File Reference
#include <arpa/nameser.h>
Functions
unsigned ns_get16 (const unsigned char *cp)
unsigned long ns_get32 (const unsigned char *cp)
void ns_put16 (unsigned s, unsigned char *cp)
void ns_put32 (unsigned long l, unsigned char *cp)
Function Documentation
ns_get16()
unsigned ns_get16 (const unsigned char * cp)
Definition at line 4 of file arpa-nameser-stubs.cpp.
{
     return cp[0] << 8 | cp[1];
 }
References cp.
Referenced by main().
ns_get32()
unsigned long ns_get32 (const unsigned char * cp)
Definition at line 8 of file arpa-nameser-stubs.cpp.
{
     return (unsigned)cp[0] << 24 | cp[1] << 16 | cp[2] << 8 | cp[3];
 }
References cp.
Referenced by main().
ns_put16()
void ns_put16 (unsigned s, unsigned char * cp)
Definition at line 12 of file arpa-nameser-stubs.cpp.
{
     *cp++ = s >> 8;
     *cp++ = s;
 }
References cp.
Referenced by main().
ns_put32()
void ns_put32 (unsigned long l, unsigned char * cp)
Definition at line 17 of file arpa-nameser-stubs.cpp.
{
     *cp++ = l >> 24;
     *cp++ = l >> 16;
     *cp++ = l >> 8;
     *cp++ = l;
 }
References cp.
Referenced by main().