Fennix: Userspace/musl/src/thread/pthread_setattr_default_np.c File Reference
pthread_setattr_default_np.c File Reference
#include "pthread_impl.h"
#include <string.h>
Macros
#define _GNU_SOURCE
#define MIN(a, b) ((a)<(b) ? (a) : (b))
#define MAX(a, b) ((a)>(b) ? (a) : (b))
Functions
int pthread_setattr_default_np (const pthread_attr_t *attrp)
int pthread_getattr_default_np (pthread_attr_t *attrp)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file pthread_setattr_default_np.c.
MAX
#define MAX (a, b) ((a)>(b) ? (a) : (b))
Definition at line 6 of file pthread_setattr_default_np.c.
MIN
#define MIN (a, b) ((a)<(b) ? (a) : (b))
Definition at line 5 of file pthread_setattr_default_np.c.
Function Documentation
pthread_getattr_default_np()
int pthread_getattr_default_np (pthread_attr_t * attrp)
Definition at line 28 of file pthread_setattr_default_np.c.
 {
     __acquire_ptc();
     *attrp = (pthread_attr_t) {
         ._a_stacksize = __default_stacksize,
         ._a_guardsize = __default_guardsize,
     };
     __release_ptc();
     return 0;
 }
References __acquire_ptc(), __default_guardsize, __default_stacksize, and __release_ptc().
pthread_setattr_default_np()
int pthread_setattr_default_np (const pthread_attr_t * attrp)
Definition at line 8 of file pthread_setattr_default_np.c.
 {
     /* Reject anything in the attr object other than stack/guard size. */
     pthread_attr_t tmp = *attrp, zero = { 0 };
     tmp._a_stacksize = 0;
     tmp._a_guardsize = 0;
     if (memcmp(&tmp, &zero, sizeof tmp))
         return EINVAL;
     unsigned stack = MIN(attrp->_a_stacksize, DEFAULT_STACK_MAX);
     unsigned guard = MIN(attrp->_a_guardsize, DEFAULT_GUARD_MAX);
     __inhibit_ptc();
     __default_stacksize = MAX(__default_stacksize, stack);
     __default_guardsize = MAX(__default_guardsize, guard);
     __release_ptc();
     return 0;
 }
References __default_guardsize, __default_stacksize, __inhibit_ptc(), __release_ptc(), DEFAULT_GUARD_MAX, DEFAULT_STACK_MAX, EINVAL, MAX, memcmp(), and MIN.