Fennix: NetworkIPv4::IPv4 Class Reference
NetworkIPv4::IPv4 Class Reference
#include <ipv4.hpp>
Public Member Functions
IPv4 (NetworkARP::ARP *ARP, NetworkEthernet::Ethernet *Ethernet)
~IPv4 ()
void Send (uint8_t *Data, uint64_t Length, uint8_t Protocol, InternetProtocol DestinationIP)
Send an IPv4 packet.
Public Member Functions inherited from NetworkEthernet::EthernetEvents
FrameType GetFrameType ()
virtual void OnEthernetPacketSent (EthernetPacket *Packet)
Data Fields
InternetProtocol GatewayIP
InternetProtocol SubNetworkMaskIP
Private Member Functions
virtual bool OnEthernetPacketReceived (uint8_t *Data, uint64_t Length)
Private Attributes
NetworkARP::ARP * ARP
NetworkEthernet::Ethernet * Ethernet
Additional Inherited Members
Protected Member Functions inherited from NetworkEthernet::EthernetEvents
EthernetEvents (FrameType Type)
~EthernetEvents ()
Detailed Description
Definition at line 71 of file ipv4.hpp.
Constructor & Destructor Documentation
IPv4()
NetworkIPv4::IPv4::IPv4 (NetworkARP::ARP * ARP, NetworkEthernet::Ethernet * Ethernet)
Definition at line 8 of file InternetProtocol.cpp.
                                                                     : NetworkEthernet::EthernetEvents(NetworkEthernet::TYPE_IPV4)
     {
         debug("IPv4 interface %#lx created.", this);
         this->ARP = ARP;
         this->Ethernet = Ethernet;
     }
References ARP, debug, and Ethernet.
~IPv4()
NetworkIPv4::IPv4::~IPv4 ()
Definition at line 15 of file InternetProtocol.cpp.
     {
         debug("IPv4 interface %#lx destroyed.", this);
     }
References debug.
Member Function Documentation
OnEthernetPacketReceived()
bool NetworkIPv4::IPv4::OnEthernetPacketReceived (uint8_t * Data, uint64_t Length) private virtual
Reimplemented from NetworkEthernet::EthernetEvents.
Definition at line 54 of file InternetProtocol.cpp.
     {
         IPv4Packet *Packet = (IPv4Packet *)Data;
         netdbg("Received %d bytes [Protocol %ld]", Length, Packet->Header.Protocol);
         if (Length < sizeof(IPv4Header))
         {
             warn("Packet too short");
             return false;
         }
         bool Reply = false;
         if (b32(Packet->Header.DestinationIP) == Ethernet->GetInterface()->IP.v4.ToHex() || b32(Packet->Header.DestinationIP) == 0xFFFFFFFF || Ethernet->GetInterface()->IP.v4.ToHex() == 0)
         {
             uint64_t TotalLength = Packet->Header.TotalLength;
             if (TotalLength > Length)
                 TotalLength = Length;
             foreach (auto Event in RegisteredEvents)
                 if (Packet->Header.Protocol == Event->GetProtocol())
                 {
                     InternetProtocol SourceIP;
                     InternetProtocol DestinationIP;
                     SourceIP.v4 = SourceIP.v4.FromHex(b32(Packet->Header.SourceIP));
                     DestinationIP.v4 = DestinationIP.v4.FromHex(b32(Packet->Header.DestinationIP));
                     if (Event->OnIPv4PacketReceived(SourceIP, DestinationIP, (uint8_t *)((uint64_t)Data + 4 * Packet->Header.IHL), TotalLength - 4 * Packet->Header.IHL))
                         Reply = true;
                 }
         }
         else
         {
             netdbg("Not for us. We are %s but this is for %s",
                    Ethernet->GetInterface()->IP.v4.ToHex(),
                    Packet->Header.DestinationIP);
         }
         if (Reply)
         {
             uint32_t SwapIP = Packet->Header.DestinationIP;
             Packet->Header.DestinationIP = Packet->Header.SourceIP;
             Packet->Header.SourceIP = SwapIP;
             Packet->Header.TimeToLive = 0x40;
             Packet->Header.HeaderChecksum = 0x0;
             Packet->Header.HeaderChecksum = CalculateChecksum((uint16_t *)Data, 4 * Packet->Header.TotalLength);
             NIManager->Send(Ethernet->GetInterface(), (uint8_t *)Data, Length);
         }
         return Reply;
     }
References b32, CalculateChecksum(), Data, NetworkIPv4::IPv4Header::DestinationIP, Ethernet, InternetProtocol::Version4::FromHex(), NetworkEthernet::Ethernet::GetInterface(), NetworkIPv4::IPv4Packet::Header, NetworkIPv4::IPv4Header::HeaderChecksum, NetworkIPv4::IPv4Header::IHL, NetworkInterfaceManager::DeviceInterface::IP, Length, netdbg, NIManager, NetworkIPv4::IPv4Header::Protocol, NetworkIPv4::RegisteredEvents, NetworkInterfaceManager::NetworkInterface::Send(), NetworkIPv4::IPv4Header::SourceIP, NetworkIPv4::IPv4Header::TimeToLive, InternetProtocol::Version4::ToHex(), NetworkIPv4::IPv4Header::TotalLength, InternetProtocol::v4, and warn.
Send()
void NetworkIPv4::IPv4::Send (uint8_t * Data, uint64_t Length, uint8_t Protocol, InternetProtocol DestinationIP)
Send an IPv4 packet.
Parameters
Data The data to send.
Length The length of the data.
Protocol The protocol of the packet.
DestinationIP The IP address of the destination. (Big-endian)
Definition at line 20 of file InternetProtocol.cpp.
     {
         netdbg("Sending %ld bytes to %s", Length, DestinationIP.v4.ToStringLittleEndian());
         IPv4Packet *Packet = (IPv4Packet *)kmalloc(Length + sizeof(IPv4Header));
         /* This part is the most confusing one for me. */
         Packet->Header.Version = b8(4);
         Packet->Header.IHL = b8(sizeof(IPv4Header) / 4);
         Packet->Header.TypeOfService = b8(0);
         /* We don't byteswap. */
         Packet->Header.TotalLength = Length + sizeof(IPv4Header);
         Packet->Header.TotalLength = ((Packet->Header.TotalLength & 0xFF00) >> 8) | ((Packet->Header.TotalLength & 0x00FF) << 8);
         Packet->Header.Identification = b16(0x0000);
         Packet->Header.Flags = b8(0x0);
         Packet->Header.FragmentOffset = b8(0x0);
         Packet->Header.TimeToLive = b8(64);
         Packet->Header.Protocol = b8(Protocol);
         Packet->Header.DestinationIP = b32(DestinationIP.v4.ToHex());
         Packet->Header.SourceIP = b32(Ethernet->GetInterface()->IP.v4.ToHex());
         Packet->Header.HeaderChecksum = b16(0x0);
         Packet->Header.HeaderChecksum = CalculateChecksum((uint16_t *)Packet, sizeof(IPv4Header));
         memcpy(Packet->Data, Data, Length);
         InternetProtocol DestinationRoute = DestinationIP;
         if ((DestinationIP.v4.ToHex() & SubNetworkMaskIP.v4.ToHex()) != (b32(Packet->Header.SourceIP) & SubNetworkMaskIP.v4.ToHex()))
             DestinationRoute = SubNetworkMaskIP;
         Ethernet->Send(MediaAccessControl().FromHex(ARP->Resolve(DestinationRoute)), this->GetFrameType(), (uint8_t *)Packet, Length + sizeof(IPv4Header));
         kfree(Packet);
     }
References ARP, b16, b32, b8, CalculateChecksum(), Data, NetworkIPv4::IPv4Packet::Data, NetworkIPv4::IPv4Header::DestinationIP, Ethernet, NetworkIPv4::IPv4Header::Flags, NetworkIPv4::IPv4Header::FragmentOffset, NetworkEthernet::Ethernet::GetInterface(), NetworkIPv4::IPv4Packet::Header, NetworkIPv4::IPv4Header::HeaderChecksum, NetworkIPv4::IPv4Header::Identification, NetworkIPv4::IPv4Header::IHL, NetworkInterfaceManager::DeviceInterface::IP, kfree, kmalloc, Length, memcpy, netdbg, NetworkIPv4::IPv4Header::Protocol, NetworkARP::ARP::Resolve(), NetworkEthernet::Ethernet::Send(), NetworkIPv4::IPv4Header::SourceIP, SubNetworkMaskIP, NetworkIPv4::IPv4Header::TimeToLive, InternetProtocol::Version4::ToHex(), InternetProtocol::Version4::ToStringLittleEndian(), NetworkIPv4::IPv4Header::TotalLength, NetworkIPv4::IPv4Header::TypeOfService, InternetProtocol::v4, and NetworkIPv4::IPv4Header::Version.
Referenced by NetworkUDP::UDP::Send().
Field Documentation
ARP
NetworkARP::ARP* NetworkIPv4::IPv4::ARP private
Definition at line 74 of file ipv4.hpp.
Referenced by IPv4(), and Send().
Ethernet
NetworkEthernet::Ethernet* NetworkIPv4::IPv4::Ethernet private
Definition at line 75 of file ipv4.hpp.
Referenced by IPv4(), OnEthernetPacketReceived(), and Send().
GatewayIP
InternetProtocol NetworkIPv4::IPv4::GatewayIP
Definition at line 80 of file ipv4.hpp.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
SubNetworkMaskIP
InternetProtocol NetworkIPv4::IPv4::SubNetworkMaskIP
Definition at line 81 of file ipv4.hpp.
Referenced by Send(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
The documentation for this class was generated from the following files:
Kernel/include/net/ipv4.hpp
Kernel/Network/InternetProtocol.cpp