Fennix: Userspace/musl/src/passwd/putgrent.c File Reference
putgrent.c File Reference
#include <grp.h>
#include <stdio.h>
Macros
#define _GNU_SOURCE
Functions
int putgrent (const struct group *gr, FILE *f)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file putgrent.c.
Function Documentation
putgrent()
int putgrent (const struct group * gr, FILE * f)
Definition at line 5 of file putgrent.c.
 {
     int r;
     size_t i;
     flockfile(f);
     if ((r = fprintf(f, "%s:%s:%u:", gr->gr_name, gr->gr_passwd, gr->gr_gid))<0) goto done;
     if (gr->gr_mem) for (i=0; gr->gr_mem[i]; i++)
         if ((r = fprintf(f, "%s%s", i?",":"", gr->gr_mem[i]))<0) goto done;
     r = fputc('\n', f);
 done:
     funlockfile(f);
     return r<0 ? -1 : 0;
 }
References done, f, flockfile(), fprintf(), fputc, funlockfile(), gr, group::gr_gid, group::gr_mem, group::gr_name, group::gr_passwd, and i.