Fennix: mlibc::char_detail< wchar_t > Struct Reference
mlibc::char_detail< wchar_t > Struct Reference
#include <strtol.hpp>
Static Public Member Functions
static bool isSpace (wchar_t c)
static bool isDigit (wchar_t c)
static bool isHexDigit (wchar_t c)
static bool isLower (wchar_t c)
static bool isUpper (wchar_t c)
Detailed Description
Definition at line 49 of file strtol.hpp.
Member Function Documentation
isDigit()
static bool mlibc::char_detail< wchar_t >::isDigit (wchar_t c) inline static
Definition at line 51 of file strtol.hpp.
 { return iswdigit(c); }
References c, and iswdigit().
isHexDigit()
static bool mlibc::char_detail< wchar_t >::isHexDigit (wchar_t c) inline static
Definition at line 52 of file strtol.hpp.
 { return iswxdigit(c); }
References c, and iswxdigit().
isLower()
static bool mlibc::char_detail< wchar_t >::isLower (wchar_t c) inline static
Definition at line 53 of file strtol.hpp.
 { return iswlower(c); }
References c, and iswlower().
isSpace()
static bool mlibc::char_detail< wchar_t >::isSpace (wchar_t c) inline static
Definition at line 50 of file strtol.hpp.
 { return iswspace(c); }
References c, and iswspace().
isUpper()
static bool mlibc::char_detail< wchar_t >::isUpper (wchar_t c) inline static
Definition at line 54 of file strtol.hpp.
 { return iswupper(c); }
References c, and iswupper().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/internal/include/mlibc/strtol.hpp