Fennix: Userspace/apps/base/busybox/util-linux/taskset.c File Reference
taskset.c File Reference
#include <sched.h>
#include "libbb.h"
Macros
#define SZOF_UL (unsigned)(sizeof(ul))
#define BITS_UL (unsigned)(sizeof(ul)*8)
#define MASK_UL (unsigned)(sizeof(ul)*8 - 1)
#define TASKSET_PRINTF_MASK "%lx"
Typedefs
typedef unsigned long ul
Enumerations
enum { OPT_p = 1 << 0 , OPT_a = 1 << 1 , OPT_c = (1 << 2) * ENABLE_FEATURE_TASKSET_CPULIST }
Functions
static unsigned long from_mask (ul *mask, unsigned sz_in_bytes UNUSED_PARAM)
static unsigned long * get_aff (int pid, unsigned *sz)
static int process_pid_str (const char *pid_str, unsigned opts, char *aff)
static int FAST_FUNC iter (const char *dn UNUSED_PARAM, struct dirent *ent, void *aff)
int taskset_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BITS_UL
#define BITS_UL (unsigned)(sizeof(ul)*8)
Definition at line 65 of file taskset.c.
MASK_UL
#define MASK_UL (unsigned)(sizeof(ul)*8 - 1)
Definition at line 66 of file taskset.c.
SZOF_UL
#define SZOF_UL (unsigned)(sizeof(ul))
Definition at line 64 of file taskset.c.
TASKSET_PRINTF_MASK
#define TASKSET_PRINTF_MASK "%lx"
Definition at line 92 of file taskset.c.
Typedef Documentation
ul
typedef unsigned long ul
Definition at line 63 of file taskset.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_p
OPT_a
OPT_c
Definition at line 209 of file taskset.c.
      {
     OPT_p = 1 << 0,
     OPT_a = 1 << 1,
     OPT_c = (1 << 2) * ENABLE_FEATURE_TASKSET_CPULIST,
 };
Function Documentation
from_mask()
static unsigned long from_mask (ul * mask, unsigned sz_in_bytes UNUSED_PARAM) static
Definition at line 93 of file taskset.c.
 {
     return *mask;
 }
Referenced by process_pid_str().
get_aff()
static unsigned long* get_aff (int pid, unsigned * sz) static
Definition at line 99 of file taskset.c.
 {
     int r;
     unsigned long *mask = NULL;
     unsigned sz_in_bytes = *sz;
     for (;;) {
         mask = xrealloc(mask, sz_in_bytes);
         r = sched_getaffinity(pid, sz_in_bytes, (void*)mask);
         if (r == 0)
             break;
         sz_in_bytes *= 2;
         if (errno == EINVAL && (int)sz_in_bytes > 0)
             continue;
         bb_perror_msg_and_die("can't %cet pid %d's affinity", 'g', pid);
     }
     //bb_error_msg("get mask[0]:%lx sz_in_bytes:%d", mask[0], sz_in_bytes);
     *sz = sz_in_bytes;
     return mask;
 }
References bb_perror_msg_and_die(), EINVAL, errno, NULL, pid, sched_getaffinity(), and xrealloc.
Referenced by process_pid_str().
iter()
static int FAST_FUNC iter (const char *dn UNUSED_PARAM, struct dirent * ent, void * aff) static
Definition at line 317 of file taskset.c.
 {
     if (isdigit(ent->d_name[0]))
         return process_pid_str(ent->d_name, option_mask32, aff);
     return 0;
 }
References dirent::d_name, isdigit, option_mask32, and process_pid_str().
Referenced by gtktree_iter_find_node(), on_treeview1_button_press_event(), on_treeview2_button_press_event(), on_treeview2_cursor_changed(), on_treeview2_key_press_event(), renderer_edited(), renderer_toggled(), sendMTFValues(), taskset_main(), tre_add_tags(), tre_ast_new_iter(), tre_ast_to_tnfa(), tre_compute_nfl(), tre_copy_ast(), tre_expand_ast(), tre_match_empty(), and update_tree().
process_pid_str()
static int process_pid_str (const char * pid_str, unsigned opts, char * aff) static
Definition at line 215 of file taskset.c.
 {
     ul *mask;
     unsigned mask_size_in_bytes;
     const char *current_new;
     pid_t pid = !pid_str ? 0 : xatou_range(pid_str, 1, INT_MAX); /* disallow "0": "taskset -p 0" should fail */
     mask_size_in_bytes = SZOF_UL;
     current_new = "current";
  print_aff:
     mask = get_aff(pid, &mask_size_in_bytes);
     if (opts & OPT_p) {
 #if ENABLE_FEATURE_TASKSET_CPULIST
         if (opts & OPT_c) {
             printf("pid %d's %s affinity list: ", pid, current_new);
             print_cpulist(mask, mask_size_in_bytes);
         } else
 #endif
             printf("pid %d's %s affinity mask: "TASKSET_PRINTF_MASK"\n",
                 pid, current_new, from_mask(mask, mask_size_in_bytes));
         if (!aff) {
             /* Either it was just "-p <pid>",
              * or it was "-p <aff> <pid>" and we came here
              * for the second time (see goto below) */
             return 0;
         }
         current_new = "new";
     }
     memset(mask, 0, mask_size_in_bytes);
     if (!ENABLE_FEATURE_TASKSET_FANCY) {
         /* Affinity was specified, translate it into mask */
         /* it is always in hex, skip "0x" if it exists */
         if (aff[0] == '0' && (aff[1]|0x20) == 'x')
             aff += 2;
         mask[0] = xstrtoul(aff, 16);
     }
 #if ENABLE_FEATURE_TASKSET_CPULIST
     else if (opts & OPT_c) {
         parse_cpulist(mask, mask_size_in_bytes * 8, aff);
     }
 #endif
     else {
         unsigned i;
         char *last_char;
         /* Affinity was specified, translate it into mask */
         /* it is always in hex, skip "0x" if it exists */
         if (aff[0] == '0' && (aff[1]|0x20) == 'x')
             aff += 2;
         i = 0; /* bit pos in mask[] */
         /* aff is ASCII hex string, accept very long masks in this form.
          * Process hex string AABBCCDD... to ulong mask[]
          * from the rightmost nibble, which is least-significant.
          * Bits not fitting into mask[] are ignored: (example: 1234
          * in 12340000000000000000000000000000000000000ff)
          */
         last_char = strchrnul(aff, '\0');
         while (last_char > aff) {
             char c;
             ul val;
             last_char--;
             c = *last_char;
             if (isdigit(c))
                 val = c - '0';
             else if ((c|0x20) >= 'a' && (c|0x20) <= 'f')
                 val = (c|0x20) - ('a' - 10);
             else
                 bb_error_msg_and_die("bad affinity '%s'", aff);
             if (i < mask_size_in_bytes * 8) {
                 mask[i / BITS_UL] |= val << (i & MASK_UL);
                 //bb_error_msg("bit %d set", i);
             }
             /* else:
              * We can error out here, but we don't.
              * For one, kernel itself ignores bits in mask[]
              * which do not map to any CPUs:
              * if mask[] has one 32-bit long element,
              * but you have only 8 CPUs, all bits beyond first 8
              * are ignored, silently.
              * No point in making bits past 31th to be errors.
              */
             i += 4;
         }
     }
     /* Set pid's or our own (pid==0) affinity */
     if (sched_setaffinity(pid, mask_size_in_bytes, (void*)mask))
         bb_perror_msg_and_die("can't %cet pid %d's affinity", 's', pid);
     //bb_error_msg("set mask[0]:%lx", mask[0]);
     if ((opts & OPT_p) && aff) { /* "-p <aff> <pid> [...ignored...]" */
         aff = NULL;
         goto print_aff; /* print new affinity and exit */
     }
     return 0;
 }
References bb_error_msg_and_die(), bb_perror_msg_and_die(), BITS_UL, c, from_mask(), get_aff(), i, INT_MAX, isdigit, MASK_UL, memset, NULL, OPT_c, OPT_p, pid, printf, sched_setaffinity(), strchrnul(), SZOF_UL, TASKSET_PRINTF_MASK, and val.
Referenced by iter(), and taskset_main().
taskset_main()
int taskset_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 325 of file taskset.c.
 {
     const char *pid_str;
     char *aff;
     unsigned opts;
     /* NB: we mimic util-linux's taskset: -p does not take
      * an argument, i.e., "-pN" is NOT valid, only "-p N"!
      * Indeed, util-linux-2.13-pre7 uses:
      * getopt_long(argc, argv, "+pchV", ...), not "...p:..." */
     opts = getopt32(argv, "^+" "pa"IF_FEATURE_TASKSET_CPULIST("c")
             "\0" "-1" /* at least 1 arg */);
     argv += optind;
     aff = *argv++;
     if (!(opts & OPT_p)) {
         /* <aff> <cmd...> */
         if (!*argv)
             bb_show_usage();
         process_pid_str(NULL, opts, aff);
         BB_EXECVP_or_die(argv);
     }
     pid_str = aff;
     if (*argv) /* "-p <aff> <pid> ...rest.is.ignored..." */
         pid_str = *argv;
     else
         aff = NULL;
     if (opts & OPT_a) {
         char *dn;
         int r;
         dn = xasprintf("/proc/%s/task", pid_str);
         r = iterate_on_dir(dn, iter, aff);
         IF_FEATURE_CLEAN_UP(free(dn);)
         if (r == 0)
             return r; /* EXIT_SUCCESS */
         /* else: no /proc/PID/task, act as if no -a was given */
     }
     return process_pid_str(pid_str, opts, aff);
 }
References argv, BB_EXECVP_or_die(), bb_show_usage(), free, getopt32(), iter(), iterate_on_dir(), NULL, OPT_a, OPT_p, optind, process_pid_str(), and xasprintf().