Fennix Userspace: anonymous_namespace{sys-mman-stubs.cpp} Namespace Reference
anonymous_namespace{sys-mman-stubs.cpp} Namespace Reference
Functions
char * shm_mapname (const char *name, char *buf)
Function Documentation
shm_mapname()
char* anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname (const char * name, char * buf)
Definition at line 109 of file sys-mman-stubs.cpp.
{
         char *p;
         while(*name == '/')
             name++;
         if(*(p = strchrnul(name, '/')) || p == name ||
             (p - name <= 2 && name[0] == '.' && p[-1] == '.')) {
             errno = EINVAL;
             return 0;
         }
         if(p - name > NAME_MAX) {
             errno = ENAMETOOLONG;
             return 0;
         }
         memcpy(buf, "/dev/shm/", 9);
         memcpy(buf + 9, name, p - name + 1);
         return buf;
     }
References buf, EINVAL, ENAMETOOLONG, errno, memcpy(), name, NAME_MAX, p, and strchrnul().
Referenced by shm_open(), and shm_unlink().