Fennix: Userspace/apps/base/busybox/networking/ifupdown.c File Reference
ifupdown.c File Reference
#include <net/if.h>
#include "libbb.h"
#include "common_bufsiz.h"
#include <sys/utsname.h>
#include <fnmatch.h>
Data Structures
struct method_t
struct address_family_t
struct mapping_defn_t
struct variable_t
struct interface_defn_t
struct interfaces_file_t
struct globals
Macros
#define MAX_OPT_DEPTH 10
#define UDHCPC_CMD_OPTIONS CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS
#define IFSTATE_FILE_PATH CONFIG_IFUPDOWN_IFSTATE_PATH
#define debug_noise(args...) /*fprintf(stderr, args)*/
#define OPTION_STR "anvf" IF_FEATURE_IFUPDOWN_MAPPING("m") "i:"
#define DO_ALL (option_mask32 & OPT_do_all)
#define NO_ACT (option_mask32 & OPT_no_act)
#define VERBOSE (option_mask32 & OPT_verbose)
#define FORCE (option_mask32 & OPT_force)
#define NO_MAPPINGS (option_mask32 & OPT_no_mappings)
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Typedefs
typedef int execfn(char *command)
Enumerations
enum {
OPT_do_all = 0x1 , OPT_no_act = 0x2 , OPT_verbose = 0x4 , OPT_force = 0x8 ,
OPT_no_mappings = 0x10
}
Functions
static int FAST_FUNC link_up_down (struct interface_defn_t *ifd UNUSED_PARAM, execfn *exec UNUSED_PARAM)
static char * next_word (char **buf)
static const struct address_family_t * get_address_family (const struct address_family_t *const af[], char *name)
static const struct method_t * get_method (const struct address_family_t *af, char *name)
static struct interfaces_file_t * read_interfaces (const char *filename, struct interfaces_file_t *defn)
static char * setlocalenv (const char *format, const char *name, const char *value)
static void set_environ (struct interface_defn_t *iface, const char *mode, const char *opt)
static int doit (char *str)
static int execute_all (struct interface_defn_t *ifd, const char *opt)
static int check (char *str)
static int iface_up (struct interface_defn_t *iface)
static int iface_down (struct interface_defn_t *iface)
static llist_t * find_iface_state (llist_t *state_list, const char *iface)
static llist_t * read_iface_state (void)
static FILE * open_new_state_file (void)
int ifupdown_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
static const char keywords_up_down[] ALIGN1
static const struct method_t link_methods[] ALIGN_PTR
static const struct address_family_t addr_link
Data Structure Documentation
address_family_t
struct address_family_t
Definition at line 170 of file ifupdown.c.
Data Fields
const struct method_t * method
int n_methods
const char * name
mapping_defn_t
struct mapping_defn_t
Definition at line 176 of file ifupdown.c.
Data Fields
char ** mapping
char ** match
int max_matches
int n_mappings
int n_matches
struct mapping_defn_t * next
char * script
variable_t
struct variable_t
Definition at line 189 of file ifupdown.c.
Data Fields
char * name
char * value
interface_defn_t
struct interface_defn_t
Definition at line 194 of file ifupdown.c.
Data Fields
const struct address_family_t * address_family
char * iface
const struct method_t * method
int n_options
struct variable_t * option
interfaces_file_t
struct interfaces_file_t
Definition at line 203 of file ifupdown.c.
Data Fields
llist_t * autointerfaces
llist_t * ifaces
struct mapping_defn_t * mappings
Macro Definition Documentation
debug_noise
#define debug_noise (args...) /*fprintf(stderr, args)*/
Definition at line 157 of file ifupdown.c.
DO_ALL
#define DO_ALL (option_mask32 & OPT_do_all)
Definition at line 218 of file ifupdown.c.
FORCE
#define FORCE (option_mask32 & OPT_force)
Definition at line 221 of file ifupdown.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 230 of file ifupdown.c.
IFSTATE_FILE_PATH
#define IFSTATE_FILE_PATH CONFIG_IFUPDOWN_IFSTATE_PATH
Definition at line 155 of file ifupdown.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 231 of file ifupdown.c.
MAX_OPT_DEPTH
#define MAX_OPT_DEPTH 10
Definition at line 148 of file ifupdown.c.
NO_ACT
#define NO_ACT (option_mask32 & OPT_no_act)
Definition at line 219 of file ifupdown.c.
NO_MAPPINGS
#define NO_MAPPINGS (option_mask32 & OPT_no_mappings)
Definition at line 222 of file ifupdown.c.
OPTION_STR
#define OPTION_STR "anvf" IF_FEATURE_IFUPDOWN_MAPPING("m") "i:"
Definition at line 210 of file ifupdown.c.
UDHCPC_CMD_OPTIONS
#define UDHCPC_CMD_OPTIONS CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS
Definition at line 154 of file ifupdown.c.
VERBOSE
#define VERBOSE (option_mask32 & OPT_verbose)
Definition at line 220 of file ifupdown.c.
Typedef Documentation
execfn
typedef int execfn(char *command)
Definition at line 162 of file ifupdown.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_do_all
OPT_no_act
OPT_verbose
OPT_force
OPT_no_mappings
Definition at line 211 of file ifupdown.c.
      {
     OPT_do_all      = 0x1,
     OPT_no_act      = 0x2,
     OPT_verbose     = 0x4,
     OPT_force       = 0x8,
     OPT_no_mappings = 0x10,
 };
Function Documentation
check()
static int check (char * str) static
Definition at line 1206 of file ifupdown.c.
 {
     return str != NULL;
 }
References NULL, and str.
Referenced by iface_down(), and iface_up().
doit()
static int doit (char * str) static
Definition at line 1153 of file ifupdown.c.
 {
     if (option_mask32 & (OPT_no_act|OPT_verbose)) {
         puts(str);
     }
     if (!(option_mask32 & OPT_no_act)) {
         pid_t child;
         int status;
         fflush_all();
         child = vfork();
         if (child < 0) /* failure */
             return 0;
         if (child == 0) { /* child */
             execle(G.shell, G.shell, "-c", str, (char *) NULL, G.my_environ);
             _exit(127);
         }
         safe_waitpid(child, &status, 0);
         if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
             return 0;
         }
     }
     return 1;
 }
References _exit(), child(), execle(), fflush_all(), G, NULL, OPT_no_act, OPT_verbose, option_mask32, puts(), safe_waitpid(), status, str, vfork(), WEXITSTATUS, and WIFEXITED.
Referenced by execute_all(), iface_down(), and iface_up().
execute_all()
static int execute_all (struct interface_defn_t * ifd, const char * opt) static
Definition at line 1178 of file ifupdown.c.
 {
     /* 'opt' is always short, the longest value is "post-down".
      * Can use on-stack buffer instead of xasprintf'ed one.
      */
     char buf[sizeof("run-parts /etc/network/if-%s.d")
         + sizeof("post-down")
         /*paranoia:*/ + 8
     ];
     int i;
     for (i = 0; i < ifd->n_options; i++) {
         if (strcmp(ifd->option[i].name, opt) == 0) {
             if (!doit(ifd->option[i].value)) {
                 return 0;
             }
         }
     }
     /* Tested on Debian Squeeze: "standard" ifup runs this without
      * checking that directory exists. If it doesn't, run-parts
      * complains, and this message _is_ annoyingly visible.
      * Don't "fix" this (unless newer Debian does).
      */
     sprintf(buf, "run-parts /etc/network/if-%s.d", opt);
     return doit(buf);
 }
References buf, doit(), i, ifd, opt, sprintf(), and strcmp.
Referenced by iface_down(), and iface_up().
find_iface_state()
static llist_t* find_iface_state (llist_t * state_list, const char * iface) static
Definition at line 1307 of file ifupdown.c.
 {
     llist_t *search = state_list;
     while (search) {
         char *after_iface = is_prefixed_with(search->data, iface);
         if (after_iface
          && *after_iface == '='
         ) {
             return search;
         }
         search = search->link;
     }
     return NULL;
 }
References is_prefixed_with(), NULL, and search().
Referenced by ifupdown_main().
get_address_family()
static const struct address_family_t* get_address_family (const struct address_family_t *const af[], char * name) static
Definition at line 835 of file ifupdown.c.
 {
     int i;
     if (!name)
         return NULL;
     for (i = 0; af[i]; i++) {
         if (strcmp(af[i]->name, name) == 0) {
             return af[i];
         }
     }
     return NULL;
 }
References i, address_family_t::name, NULL, and strcmp.
Referenced by read_interfaces().
get_method()
static const struct method_t* get_method (const struct address_family_t * af, char * name) static
Definition at line 850 of file ifupdown.c.
 {
     int i;
     if (!name)
         return NULL;
     /* TODO: use index_in_str_array() */
     for (i = 0; i < af->n_methods; i++) {
         if (strcmp(af->method[i].name, name) == 0) {
             return &af->method[i];
         }
     }
     return NULL;
 }
References i, address_family_t::method, address_family_t::n_methods, method_t::name, NULL, and strcmp.
Referenced by read_interfaces().
iface_down()
static int iface_down (struct interface_defn_t * iface) static
Definition at line 1222 of file ifupdown.c.
 {
     if (!iface->method->down(iface, check)) return -1;
     set_environ(iface, "stop", "pre-down");
     if (!execute_all(iface, "down")) return 0;
     if (!iface->method->down(iface, doit)) return 0;
     set_environ(iface, "stop", "post-down");
     if (!execute_all(iface, "post-down")) return 0;
     return 1;
 }
References check(), doit(), method_t::down, execute_all(), interface_defn_t::method, and set_environ().
Referenced by ifupdown_main().
iface_up()
static int iface_up (struct interface_defn_t * iface) static
Definition at line 1211 of file ifupdown.c.
 {
     if (!iface->method->up(iface, check)) return -1;
     set_environ(iface, "start", "pre-up");
     if (!execute_all(iface, "pre-up")) return 0;
     if (!iface->method->up(iface, doit)) return 0;
     set_environ(iface, "start", "post-up");
     if (!execute_all(iface, "up")) return 0;
     return 1;
 }
References check(), doit(), execute_all(), interface_defn_t::method, set_environ(), and method_t::up.
Referenced by ifupdown_main().
ifupdown_main()
int ifupdown_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1375 of file ifupdown.c.
 {
     int (*cmds)(struct interface_defn_t *);
     struct interfaces_file_t *defn;
     llist_t *target_list = NULL;
     const char *interfaces = "/etc/network/interfaces";
     bool any_failures = 0;
     INIT_G();
     G.startup_PATH = getenv("PATH");
     G.shell = xstrdup(get_shell_name());
     if (ENABLE_IFUP
      && (!ENABLE_IFDOWN || applet_name[2] == 'u')
     ) {
         /* ifup command */
         cmds = iface_up;
     } else {
         cmds = iface_down;
     }
     getopt32(argv, OPTION_STR, &interfaces);
     argv += optind;
     if (argv[0]) {
         if (DO_ALL) bb_show_usage();
     } else {
         if (!DO_ALL) bb_show_usage();
     }
     defn = read_interfaces(interfaces, NULL);
     /* Create a list of interfaces to work on */
     if (DO_ALL) {
         target_list = defn->autointerfaces;
     } else {
         llist_add_to_end(&target_list, argv[0]);
     }
     /* Update the interfaces */
     while (target_list) {
         llist_t *iface_list;
         struct interface_defn_t *currif;
         char *iface;
         char *liface;
         char *pch;
         bool okay = 0;
         int cmds_ret;
         bool curr_failure = 0;
         iface = xstrdup(target_list->data);
         target_list = target_list->link;
         pch = strchr(iface, '=');
         if (pch) {
             *pch = '\0';
             liface = xstrdup(pch + 1);
         } else {
             liface = xstrdup(iface);
         }
         if (!FORCE) {
             llist_t *state_list = read_iface_state();
             const llist_t *iface_state = find_iface_state(state_list, iface);
             if (cmds == iface_up) {
                 /* ifup */
                 if (iface_state) {
                     bb_error_msg("interface %s already configured", iface);
                     goto next;
                 }
             } else {
                 /* ifdown */
                 if (!iface_state) {
                     bb_error_msg("interface %s not configured", iface);
                     goto next;
                 }
             }
             llist_free(state_list, free);
         }
 #if ENABLE_FEATURE_IFUPDOWN_MAPPING
         if ((cmds == iface_up) && !NO_MAPPINGS) {
             struct mapping_defn_t *currmap;
             for (currmap = defn->mappings; currmap; currmap = currmap->next) {
                 int i;
                 for (i = 0; i < currmap->n_matches; i++) {
                     if (fnmatch(currmap->match[i], liface, 0) != 0)
                         continue;
                     if (VERBOSE) {
                         printf("Running mapping script %s on %s\n", currmap->script, liface);
                     }
                     liface = run_mapping(iface, currmap);
                     break;
                 }
             }
         }
 #endif
         iface_list = defn->ifaces;
         while (iface_list) {
             currif = (struct interface_defn_t *) iface_list->data;
             if (strcmp(liface, currif->iface) == 0) {
                 char *oldiface = currif->iface;
                 okay = 1;
                 currif->iface = iface;
                 debug_noise("\nConfiguring interface %s (%s)\n", liface, currif->address_family->name);
                 /* Call the cmds function pointer, does either iface_up() or iface_down() */
                 cmds_ret = cmds(currif);
                 if (cmds_ret == -1) {
                     bb_error_msg("don't have all variables for %s/%s",
                             liface, currif->address_family->name);
                     any_failures = curr_failure = 1;
                 } else if (cmds_ret == 0) {
                     any_failures = curr_failure = 1;
                 }
                 currif->iface = oldiface;
             }
             iface_list = iface_list->link;
         }
         if (VERBOSE) {
             bb_putchar('\n');
         }
         if (!okay && !FORCE) {
             bb_error_msg("ignoring unknown interface %s", liface);
             any_failures = 1;
         } else if (!NO_ACT) {
             /* update the state file */
             FILE *new_state_fp = open_new_state_file();
             llist_t *state;
             llist_t *state_list = read_iface_state();
             llist_t *iface_state = find_iface_state(state_list, iface);
             if (cmds == iface_up && !curr_failure) {
                 char *newiface = xasprintf("%s=%s", iface, liface);
                 if (!iface_state) {
                     llist_add_to_end(&state_list, newiface);
                 } else {
                     free(iface_state->data);
                     iface_state->data = newiface;
                 }
             } else {
                 /* Remove an interface from state_list */
                 llist_unlink(&state_list, iface_state);
                 free(llist_pop(&iface_state));
             }
             /* Actually write the new state */
             state = state_list;
             while (state) {
                 if (state->data) {
                     fprintf(new_state_fp, "%s\n", state->data);
                 }
                 state = state->link;
             }
             fclose(new_state_fp);
             xrename(IFSTATE_FILE_PATH".new", IFSTATE_FILE_PATH);
             llist_free(state_list, free);
         }
  next:
         free(iface);
         free(liface);
     }
     return any_failures;
 }
References interface_defn_t::address_family, applet_name, argv, interfaces_file_t::autointerfaces, bb_error_msg(), bb_putchar(), bb_show_usage(), llist_t::data, debug_noise, DO_ALL, fclose(), find_iface_state(), fnmatch(), FORCE, fprintf(), free, G, get_shell_name(), getenv, getopt32(), i, if(), interface_defn_t::iface, iface_down(), iface_up(), interfaces_file_t::ifaces, IFSTATE_FILE_PATH, INIT_G, llist_t::link, llist_add_to_end(), llist_free(), llist_pop(), llist_unlink(), interfaces_file_t::mappings, mapping_defn_t::match, mapping_defn_t::n_matches, address_family_t::name, mapping_defn_t::next, next, NO_ACT, NO_MAPPINGS, NULL, open_new_state_file(), optind, OPTION_STR, printf, read_iface_state(), read_interfaces(), mapping_defn_t::script, state, strchr(), strcmp, VERBOSE, xasprintf(), xrename(), and xstrdup().
link_up_down()
static int FAST_FUNC link_up_down (struct interface_defn_t *ifd UNUSED_PARAM, execfn *exec UNUSED_PARAM) static
Definition at line 795 of file ifupdown.c.
 {
     return 1;
 }
next_word()
static char* next_word (char ** buf) static
Definition at line 811 of file ifupdown.c.
 {
     unsigned length;
     char *word;
     /* Skip over leading whitespace */
     word = skip_whitespace(*buf);
     /* Stop on EOL */
     if (*word == '\0')
         return NULL;
     /* Find the length of this word (can't be 0) */
     length = strcspn(word, " \t\n");
     /* Unless we are already at NUL, store NUL and advance */
     if (word[length] != '\0')
         word[length++] = '\0';
     *buf = skip_whitespace(word + length);
     return word;
 }
References buf, NULL, skip_whitespace(), and strcspn().
Referenced by read_interfaces().
open_new_state_file()
static FILE* open_new_state_file (void) static
Definition at line 1343 of file ifupdown.c.
 {
     int fd, flags, cnt;
     cnt = 0;
     flags = (O_WRONLY | O_CREAT | O_EXCL);
     for (;;) {
         fd = open(IFSTATE_FILE_PATH".new", flags, 0666);
         if (fd >= 0)
             break;
         if (errno != EEXIST
          || flags == (O_WRONLY | O_CREAT | O_TRUNC)
         ) {
             bb_perror_msg_and_die("can't open '%s'",
                     IFSTATE_FILE_PATH".new");
         }
         /* Someone else created the .new file */
         if (cnt > 30) {
             /* Waited for 30*30/2 = 450 milliseconds, still EEXIST.
              * Assuming a stale file, rewriting it.
              */
             flags = (O_WRONLY | O_CREAT | O_TRUNC);
             continue;
         }
         msleep(cnt);
         cnt++;
     }
     return xfdopen_for_write(fd);
 }
References bb_perror_msg_and_die(), cnt, EEXIST, errno, fd, flags, IFSTATE_FILE_PATH, msleep(), O_CREAT, O_EXCL, O_TRUNC, O_WRONLY, open(), and xfdopen_for_write().
Referenced by ifupdown_main().
read_iface_state()
static llist_t* read_iface_state (void) static
Definition at line 1324 of file ifupdown.c.
 {
     llist_t *state_list = NULL;
     FILE *state_fp = fopen_for_read(IFSTATE_FILE_PATH);
     if (state_fp) {
         char *start, *end_ptr;
         while ((start = xmalloc_fgets(state_fp)) != NULL) {
             /* We should only need to check for a single character */
             end_ptr = start + strcspn(start, " \t\n");
             *end_ptr = '\0';
             llist_add_to(&state_list, start);
         }
         fclose(state_fp);
     }
     return state_list;
 }
References fclose(), fopen_for_read(), IFSTATE_FILE_PATH, llist_add_to(), NULL, start, strcspn(), and xmalloc_fgets().
Referenced by ifupdown_main().
read_interfaces()
static struct interfaces_file_t* read_interfaces (const char * filename, struct interfaces_file_t * defn) static
Definition at line 865 of file ifupdown.c.
 {
     /* Let's try to be compatible.
      *
      * "man 5 interfaces" says:
      * Lines starting with "#" are ignored. Note that end-of-line
      * comments are NOT supported, comments must be on a line of their own.
      * A line may be extended across multiple lines by making
      * the last character a backslash.
      *
      * Seen elsewhere in example config file:
      * A first non-blank "#" character makes the rest of the line
      * be ignored. Blank lines are ignored. Lines may be indented freely.
      * A "\" character at the very end of the line indicates the next line
      * should be treated as a continuation of the current one.
      *
      * Lines  beginning with "source" are used to include stanzas from
      * other files, so configuration can be split into many files.
      * The word "source" is followed by the path of file to be sourced.
      */
 #if ENABLE_FEATURE_IFUPDOWN_MAPPING
     struct mapping_defn_t *currmap = NULL;
 #endif
     struct interface_defn_t *currif = NULL;
     FILE *f;
     char *buf;
     char *first_word;
     char *rest_of_line;
     enum { NONE, IFACE, MAPPING } currently_processing = NONE;
     if (!defn)
         defn = xzalloc(sizeof(*defn));
     debug_noise("reading %s file:\n", filename);
     f = xfopen_for_read(filename);
     while ((buf = xmalloc_fgetline(f)) != NULL) {
 #if ENABLE_DESKTOP
         /* Trailing "\" concatenates lines */
         char *p;
         while ((p = last_char_is(buf, '\\')) != NULL) {
             *p = '\0';
             rest_of_line = xmalloc_fgetline(f);
             if (!rest_of_line)
                 break;
             p = xasprintf("%s%s", buf, rest_of_line);
             free(buf);
             free(rest_of_line);
             buf = p;
         }
 #endif
         rest_of_line = buf;
         first_word = next_word(&rest_of_line);
         if (!first_word || *first_word == '#') {
             free(buf);
             continue; /* blank/comment line */
         }
         if (strcmp(first_word, "mapping") == 0) {
 #if ENABLE_FEATURE_IFUPDOWN_MAPPING
             currmap = xzalloc(sizeof(*currmap));
             while ((first_word = next_word(&rest_of_line)) != NULL) {
                 currmap->match = xrealloc_vector(currmap->match, 4, currmap->n_matches);
                 currmap->match[currmap->n_matches++] = xstrdup(first_word);
             }
             /*currmap->n_mappings = 0;*/
             /*currmap->mapping = NULL;*/
             /*currmap->script = NULL;*/
             {
                 struct mapping_defn_t **where = &defn->mappings;
                 while (*where != NULL) {
                     where = &(*where)->next;
                 }
                 *where = currmap;
                 /*currmap->next = NULL;*/
             }
             debug_noise("Added mapping\n");
 #endif
             currently_processing = MAPPING;
         } else if (strcmp(first_word, "iface") == 0) {
             static const struct address_family_t *const addr_fams[] = {
 #if ENABLE_FEATURE_IFUPDOWN_IPV4
                 &addr_inet,
 #endif
 #if ENABLE_FEATURE_IFUPDOWN_IPV6
                 &addr_inet6,
 #endif
                 &addr_link,
                 NULL
             };
             char *iface_name;
             char *address_family_name;
             char *method_name;
             currif = xzalloc(sizeof(*currif));
             iface_name = next_word(&rest_of_line);
             address_family_name = next_word(&rest_of_line);
             method_name = next_word(&rest_of_line);
             if (method_name == NULL)
                 bb_error_msg_and_die("too few parameters for line \"%s\"", buf);
             /* ship any trailing whitespace */
             rest_of_line = skip_whitespace(rest_of_line);
             if (rest_of_line[0] != '\0' /* && rest_of_line[0] != '#' */)
                 bb_error_msg_and_die("too many parameters \"%s\"", buf);
             currif->iface = xstrdup(iface_name);
             currif->address_family = get_address_family(addr_fams, address_family_name);
             if (!currif->address_family)
                 bb_error_msg_and_die("unknown address type \"%s\"", address_family_name);
             currif->method = get_method(currif->address_family, method_name);
             if (!currif->method)
                 bb_error_msg_and_die("unknown method \"%s\"", method_name);
 #if 0
 // Allegedly, Debian allows a duplicate definition:
 // iface eth0 inet static
 //     address 192.168.0.15
 //     netmask 255.255.0.0
 //     gateway 192.168.0.1
 //
 // iface eth0 inet static
 //     address 10.0.0.1
 //     netmask 255.255.255.0
 //
 // This adds *two* addresses to eth0 (probably requires use of "ip", not "ifconfig"
 //
             llist_t *iface_list;
             for (iface_list = defn->ifaces; iface_list; iface_list = iface_list->link) {
                 struct interface_defn_t *tmp = (struct interface_defn_t *) iface_list->data;
                 if ((strcmp(tmp->iface, currif->iface) == 0)
                  && (tmp->address_family == currif->address_family)
                 ) {
                     bb_error_msg_and_die("duplicate interface \"%s\"", tmp->iface);
                 }
             }
 #endif
             llist_add_to_end(&(defn->ifaces), (char*)currif);
             debug_noise("iface %s %s %s\n", currif->iface, address_family_name, method_name);
             currently_processing = IFACE;
         } else if (strcmp(first_word, "auto") == 0) {
             while ((first_word = next_word(&rest_of_line)) != NULL) {
                 /* Check the interface isnt already listed */
                 if (llist_find_str(defn->autointerfaces, first_word)) {
                     bb_perror_msg_and_die("interface declared auto twice \"%s\"", buf);
                 }
                 /* Add the interface to the list */
                 llist_add_to_end(&(defn->autointerfaces), xstrdup(first_word));
                 debug_noise("\nauto %s\n", first_word);
             }
             currently_processing = NONE;
         } else if (strcmp(first_word, "source") == 0) {
             read_interfaces(next_word(&rest_of_line), defn);
         } else if (is_prefixed_with(first_word, "source-dir")) {
             const char *dirpath;
             DIR *dir;
             struct dirent *entry;
             dirpath = next_word(&rest_of_line);
             dir = xopendir(dirpath);
             while ((entry = readdir(dir)) != NULL) {
                 char *path;
                 if (entry->d_name[0] == '.')
                     continue;
                 path = concat_path_file(dirpath, entry->d_name);
                 read_interfaces(path, defn);
                 free(path);
             }
             closedir(dir);
         } else {
             switch (currently_processing) {
             case IFACE:
                 if (rest_of_line[0] == '\0')
                     bb_error_msg_and_die("option with empty value \"%s\"", buf);
                 if (strcmp(first_word, "post-up") == 0)
                     first_word += 5; /* "up" */
                 else if (strcmp(first_word, "pre-down") == 0)
                     first_word += 4; /* "down" */
                 /* If not one of "up", "down",... words... */
                 if (index_in_strings(keywords_up_down, first_word) < 0) {
                     int i;
                     for (i = 0; i < currif->n_options; i++) {
                         if (strcmp(currif->option[i].name, first_word) == 0)
                             bb_error_msg_and_die("duplicate option \"%s\"", buf);
                     }
                 }
                 debug_noise("\t%s=%s\n", first_word, rest_of_line);
                 currif->option = xrealloc_vector(currif->option, 4, currif->n_options);
                 currif->option[currif->n_options].name = xstrdup(first_word);
                 currif->option[currif->n_options].value = xstrdup(rest_of_line);
                 currif->n_options++;
                 break;
             case MAPPING:
 #if ENABLE_FEATURE_IFUPDOWN_MAPPING
                 if (strcmp(first_word, "script") == 0) {
                     if (currmap->script != NULL)
                         bb_error_msg_and_die("duplicate script in mapping \"%s\"", buf);
                     currmap->script = xstrdup(next_word(&rest_of_line));
                 } else if (strcmp(first_word, "map") == 0) {
                     currmap->mapping = xrealloc_vector(currmap->mapping, 2, currmap->n_mappings);
                     currmap->mapping[currmap->n_mappings] = xstrdup(next_word(&rest_of_line));
                     currmap->n_mappings++;
                 } else {
                     bb_error_msg_and_die("misplaced option \"%s\"", buf);
                 }
 #endif
                 break;
             case NONE:
             default:
                 bb_error_msg_and_die("misplaced option \"%s\"", buf);
             }
         }
         free(buf);
     } /* while (fgets) */
     if (ferror(f) != 0) {
         /* ferror does NOT set errno! */
         bb_error_msg_and_die("%s: I/O error", filename);
     }
     fclose(f);
     debug_noise("\ndone reading %s\n\n", filename);
     return defn;
 }
References addr_link, interface_defn_t::address_family, interfaces_file_t::autointerfaces, bb_error_msg_and_die(), bb_perror_msg_and_die(), buf, closedir(), concat_path_file(), debug_noise, dir, f, fclose(), ferror, filename, free, get_address_family(), get_method(), i, if(), interface_defn_t::iface, interfaces_file_t::ifaces, index_in_strings(), is_prefixed_with(), last_char_is(), llist_add_to_end(), llist_find_str(), mapping_defn_t::mapping, interfaces_file_t::mappings, mapping_defn_t::match, interface_defn_t::method, mapping_defn_t::n_mappings, mapping_defn_t::n_matches, interface_defn_t::n_options, variable_t::name, mapping_defn_t::next, next_word(), NULL, interface_defn_t::option, p, readdir(), mapping_defn_t::script, skip_whitespace(), strcmp, variable_t::value, xasprintf(), xfopen_for_read(), xmalloc_fgetline(), xopendir(), xrealloc_vector, xstrdup(), and xzalloc().
Referenced by ifupdown_main().
set_environ()
static void set_environ (struct interface_defn_t * iface, const char * mode, const char * opt) static
Definition at line 1121 of file ifupdown.c.
 {
     int i;
     char **pp;
     if (G.my_environ != NULL) {
         for (pp = G.my_environ; *pp; pp++) {
             free(*pp);
         }
         free(G.my_environ);
     }
     /* note: last element will stay NULL: */
     G.my_environ = xzalloc(sizeof(char *) * (iface->n_options + 7));
     pp = G.my_environ;
     for (i = 0; i < iface->n_options; i++) {
         if (index_in_strings(keywords_up_down, iface->option[i].name) >= 0) {
             continue;
         }
         *pp++ = setlocalenv("IF_%s=%s", iface->option[i].name, iface->option[i].value);
     }
     *pp++ = setlocalenv("%s=%s", "IFACE", iface->iface);
     *pp++ = setlocalenv("%s=%s", "ADDRFAM", iface->address_family->name);
     *pp++ = setlocalenv("%s=%s", "METHOD", iface->method->name);
     *pp++ = setlocalenv("%s=%s", "MODE", mode);
     *pp++ = setlocalenv("%s=%s", "PHASE", opt);
     if (G.startup_PATH)
         *pp++ = setlocalenv("%s=%s", "PATH", G.startup_PATH);
 }
References interface_defn_t::address_family, free, G, i, interface_defn_t::iface, index_in_strings(), interface_defn_t::method, interface_defn_t::n_options, method_t::name, address_family_t::name, variable_t::name, NULL, opt, interface_defn_t::option, setlocalenv(), variable_t::value, and xzalloc().
Referenced by iface_down(), and iface_up().
setlocalenv()
static char* setlocalenv (const char * format, const char * name, const char * value) static
Definition at line 1099 of file ifupdown.c.
 {
     char *result;
     char *dst;
     char *src;
     char c;
     result = xasprintf(format, name, value);
     for (dst = src = result; (c = *src) != '=' && c; src++) {
         if (c == '-')
             c = '_';
         if (c >= 'a' && c <= 'z')
             c -= ('a' - 'A');
         if (isalnum(c) || c == '_')
             *dst++ = c;
     }
     overlapping_strcpy(dst, src);
     return result;
 }
References c, dst, format(), isalnum, overlapping_strcpy(), src, value, and xasprintf().
Referenced by set_environ().
Variable Documentation
addr_link
const struct address_family_t addr_link static
Initial value:
= {
    "link", ARRAY_SIZE(link_methods), link_methods
}
Definition at line 800 of file ifupdown.c.
Referenced by read_interfaces().
ALIGN1
const char keywords_up_down [] ALIGN1 static
Initial value:
=
    "up\0"
    "down\0"
    "pre-up\0"
    "post-down\0"
Definition at line 234 of file ifupdown.c.
ALIGN_PTR
const struct method_t link_methods [] ALIGN_PTR static
Initial value:
= {
    { "none", link_up_down, link_up_down }
}
Definition at line 800 of file ifupdown.c.
FIX_ALIASING
struct globals FIX_ALIASING