Fennix Userspace: Userspace/musl/include/unistd.h File Reference
unistd.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/posix.h>
Macros
#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_DATA 3
#define SEEK_HOLE 4
#define NULL ((void*)0)
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_uid_t
#define __NEED_gid_t
#define __NEED_off_t
#define __NEED_pid_t
#define __NEED_intptr_t
#define __NEED_useconds_t
#define F_OK 0
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define POSIX_CLOSE_RESTART 0
#define _XOPEN_VERSION 700
#define _XOPEN_UNIX 1
#define _XOPEN_ENH_I18N 1
#define _POSIX_VERSION 200809L
#define _POSIX2_VERSION _POSIX_VERSION
#define _POSIX_ADVISORY_INFO _POSIX_VERSION
#define _POSIX_CHOWN_RESTRICTED 1
#define _POSIX_IPV6 _POSIX_VERSION
#define _POSIX_JOB_CONTROL 1
#define _POSIX_MAPPED_FILES _POSIX_VERSION
#define _POSIX_MEMLOCK _POSIX_VERSION
#define _POSIX_MEMLOCK_RANGE _POSIX_VERSION
#define _POSIX_MEMORY_PROTECTION _POSIX_VERSION
#define _POSIX_MESSAGE_PASSING _POSIX_VERSION
#define _POSIX_FSYNC _POSIX_VERSION
#define _POSIX_NO_TRUNC 1
#define _POSIX_RAW_SOCKETS _POSIX_VERSION
#define _POSIX_REALTIME_SIGNALS _POSIX_VERSION
#define _POSIX_REGEXP 1
#define _POSIX_SAVED_IDS 1
#define _POSIX_SHELL 1
#define _POSIX_SPAWN _POSIX_VERSION
#define _POSIX_VDISABLE 0
#define _POSIX_THREADS _POSIX_VERSION
#define _POSIX_THREAD_PROCESS_SHARED _POSIX_VERSION
#define _POSIX_THREAD_SAFE_FUNCTIONS _POSIX_VERSION
#define _POSIX_THREAD_ATTR_STACKADDR _POSIX_VERSION
#define _POSIX_THREAD_ATTR_STACKSIZE _POSIX_VERSION
#define _POSIX_THREAD_PRIORITY_SCHEDULING _POSIX_VERSION
#define _POSIX_THREAD_CPUTIME _POSIX_VERSION
#define _POSIX_TIMERS _POSIX_VERSION
#define _POSIX_TIMEOUTS _POSIX_VERSION
#define _POSIX_MONOTONIC_CLOCK _POSIX_VERSION
#define _POSIX_CPUTIME _POSIX_VERSION
#define _POSIX_CLOCK_SELECTION _POSIX_VERSION
#define _POSIX_BARRIERS _POSIX_VERSION
#define _POSIX_SPIN_LOCKS _POSIX_VERSION
#define _POSIX_READER_WRITER_LOCKS _POSIX_VERSION
#define _POSIX_ASYNCHRONOUS_IO _POSIX_VERSION
#define _POSIX_SEMAPHORES _POSIX_VERSION
#define _POSIX_SHARED_MEMORY_OBJECTS _POSIX_VERSION
#define _POSIX2_C_BIND _POSIX_VERSION
#define _PC_LINK_MAX 0
#define _PC_MAX_CANON 1
#define _PC_MAX_INPUT 2
#define _PC_NAME_MAX 3
#define _PC_PATH_MAX 4
#define _PC_PIPE_BUF 5
#define _PC_CHOWN_RESTRICTED 6
#define _PC_NO_TRUNC 7
#define _PC_VDISABLE 8
#define _PC_SYNC_IO 9
#define _PC_ASYNC_IO 10
#define _PC_PRIO_IO 11
#define _PC_SOCK_MAXBUF 12
#define _PC_FILESIZEBITS 13
#define _PC_REC_INCR_XFER_SIZE 14
#define _PC_REC_MAX_XFER_SIZE 15
#define _PC_REC_MIN_XFER_SIZE 16
#define _PC_REC_XFER_ALIGN 17
#define _PC_ALLOC_SIZE_MIN 18
#define _PC_SYMLINK_MAX 19
#define _PC_2_SYMLINKS 20
#define _SC_ARG_MAX 0
#define _SC_CHILD_MAX 1
#define _SC_CLK_TCK 2
#define _SC_NGROUPS_MAX 3
#define _SC_OPEN_MAX 4
#define _SC_STREAM_MAX 5
#define _SC_TZNAME_MAX 6
#define _SC_JOB_CONTROL 7
#define _SC_SAVED_IDS 8
#define _SC_REALTIME_SIGNALS 9
#define _SC_PRIORITY_SCHEDULING 10
#define _SC_TIMERS 11
#define _SC_ASYNCHRONOUS_IO 12
#define _SC_PRIORITIZED_IO 13
#define _SC_SYNCHRONIZED_IO 14
#define _SC_FSYNC 15
#define _SC_MAPPED_FILES 16
#define _SC_MEMLOCK 17
#define _SC_MEMLOCK_RANGE 18
#define _SC_MEMORY_PROTECTION 19
#define _SC_MESSAGE_PASSING 20
#define _SC_SEMAPHORES 21
#define _SC_SHARED_MEMORY_OBJECTS 22
#define _SC_AIO_LISTIO_MAX 23
#define _SC_AIO_MAX 24
#define _SC_AIO_PRIO_DELTA_MAX 25
#define _SC_DELAYTIMER_MAX 26
#define _SC_MQ_OPEN_MAX 27
#define _SC_MQ_PRIO_MAX 28
#define _SC_VERSION 29
#define _SC_PAGE_SIZE 30
#define _SC_PAGESIZE 30 /* !! */
#define _SC_RTSIG_MAX 31
#define _SC_SEM_NSEMS_MAX 32
#define _SC_SEM_VALUE_MAX 33
#define _SC_SIGQUEUE_MAX 34
#define _SC_TIMER_MAX 35
#define _SC_BC_BASE_MAX 36
#define _SC_BC_DIM_MAX 37
#define _SC_BC_SCALE_MAX 38
#define _SC_BC_STRING_MAX 39
#define _SC_COLL_WEIGHTS_MAX 40
#define _SC_EXPR_NEST_MAX 42
#define _SC_LINE_MAX 43
#define _SC_RE_DUP_MAX 44
#define _SC_2_VERSION 46
#define _SC_2_C_BIND 47
#define _SC_2_C_DEV 48
#define _SC_2_FORT_DEV 49
#define _SC_2_FORT_RUN 50
#define _SC_2_SW_DEV 51
#define _SC_2_LOCALEDEF 52
#define _SC_UIO_MAXIOV 60 /* !! */
#define _SC_IOV_MAX 60
#define _SC_THREADS 67
#define _SC_THREAD_SAFE_FUNCTIONS 68
#define _SC_GETGR_R_SIZE_MAX 69
#define _SC_GETPW_R_SIZE_MAX 70
#define _SC_LOGIN_NAME_MAX 71
#define _SC_TTY_NAME_MAX 72
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 73
#define _SC_THREAD_KEYS_MAX 74
#define _SC_THREAD_STACK_MIN 75
#define _SC_THREAD_THREADS_MAX 76
#define _SC_THREAD_ATTR_STACKADDR 77
#define _SC_THREAD_ATTR_STACKSIZE 78
#define _SC_THREAD_PRIORITY_SCHEDULING 79
#define _SC_THREAD_PRIO_INHERIT 80
#define _SC_THREAD_PRIO_PROTECT 81
#define _SC_THREAD_PROCESS_SHARED 82
#define _SC_NPROCESSORS_CONF 83
#define _SC_NPROCESSORS_ONLN 84
#define _SC_PHYS_PAGES 85
#define _SC_AVPHYS_PAGES 86
#define _SC_ATEXIT_MAX 87
#define _SC_PASS_MAX 88
#define _SC_XOPEN_VERSION 89
#define _SC_XOPEN_XCU_VERSION 90
#define _SC_XOPEN_UNIX 91
#define _SC_XOPEN_CRYPT 92
#define _SC_XOPEN_ENH_I18N 93
#define _SC_XOPEN_SHM 94
#define _SC_2_CHAR_TERM 95
#define _SC_2_UPE 97
#define _SC_XOPEN_XPG2 98
#define _SC_XOPEN_XPG3 99
#define _SC_XOPEN_XPG4 100
#define _SC_NZERO 109
#define _SC_XBS5_ILP32_OFF32 125
#define _SC_XBS5_ILP32_OFFBIG 126
#define _SC_XBS5_LP64_OFF64 127
#define _SC_XBS5_LPBIG_OFFBIG 128
#define _SC_XOPEN_LEGACY 129
#define _SC_XOPEN_REALTIME 130
#define _SC_XOPEN_REALTIME_THREADS 131
#define _SC_ADVISORY_INFO 132
#define _SC_BARRIERS 133
#define _SC_CLOCK_SELECTION 137
#define _SC_CPUTIME 138
#define _SC_THREAD_CPUTIME 139
#define _SC_MONOTONIC_CLOCK 149
#define _SC_READER_WRITER_LOCKS 153
#define _SC_SPIN_LOCKS 154
#define _SC_REGEXP 155
#define _SC_SHELL 157
#define _SC_SPAWN 159
#define _SC_SPORADIC_SERVER 160
#define _SC_THREAD_SPORADIC_SERVER 161
#define _SC_TIMEOUTS 164
#define _SC_TYPED_MEMORY_OBJECTS 165
#define _SC_2_PBS 168
#define _SC_2_PBS_ACCOUNTING 169
#define _SC_2_PBS_LOCATE 170
#define _SC_2_PBS_MESSAGE 171
#define _SC_2_PBS_TRACK 172
#define _SC_SYMLOOP_MAX 173
#define _SC_STREAMS 174
#define _SC_2_PBS_CHECKPOINT 175
#define _SC_V6_ILP32_OFF32 176
#define _SC_V6_ILP32_OFFBIG 177
#define _SC_V6_LP64_OFF64 178
#define _SC_V6_LPBIG_OFFBIG 179
#define _SC_HOST_NAME_MAX 180
#define _SC_TRACE 181
#define _SC_TRACE_EVENT_FILTER 182
#define _SC_TRACE_INHERIT 183
#define _SC_TRACE_LOG 184
#define _SC_IPV6 235
#define _SC_RAW_SOCKETS 236
#define _SC_V7_ILP32_OFF32 237
#define _SC_V7_ILP32_OFFBIG 238
#define _SC_V7_LP64_OFF64 239
#define _SC_V7_LPBIG_OFFBIG 240
#define _SC_SS_REPL_MAX 241
#define _SC_TRACE_EVENT_NAME_MAX 242
#define _SC_TRACE_NAME_MAX 243
#define _SC_TRACE_SYS_MAX 244
#define _SC_TRACE_USER_EVENT_MAX 245
#define _SC_XOPEN_STREAMS 246
#define _SC_THREAD_ROBUST_PRIO_INHERIT 247
#define _SC_THREAD_ROBUST_PRIO_PROTECT 248
#define _SC_MINSIGSTKSZ 249
#define _SC_SIGSTKSZ 250
#define _CS_PATH 0
#define _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS 1
#define _CS_GNU_LIBC_VERSION 2
#define _CS_GNU_LIBPTHREAD_VERSION 3
#define _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS 4
#define _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS 5
#define _CS_POSIX_V6_ILP32_OFF32_CFLAGS 1116
#define _CS_POSIX_V6_ILP32_OFF32_LDFLAGS 1117
#define _CS_POSIX_V6_ILP32_OFF32_LIBS 1118
#define _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS 1119
#define _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS 1120
#define _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS 1121
#define _CS_POSIX_V6_ILP32_OFFBIG_LIBS 1122
#define _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS 1123
#define _CS_POSIX_V6_LP64_OFF64_CFLAGS 1124
#define _CS_POSIX_V6_LP64_OFF64_LDFLAGS 1125
#define _CS_POSIX_V6_LP64_OFF64_LIBS 1126
#define _CS_POSIX_V6_LP64_OFF64_LINTFLAGS 1127
#define _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS 1128
#define _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS 1129
#define _CS_POSIX_V6_LPBIG_OFFBIG_LIBS 1130
#define _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS 1131
#define _CS_POSIX_V7_ILP32_OFF32_CFLAGS 1132
#define _CS_POSIX_V7_ILP32_OFF32_LDFLAGS 1133
#define _CS_POSIX_V7_ILP32_OFF32_LIBS 1134
#define _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS 1135
#define _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS 1136
#define _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS 1137
#define _CS_POSIX_V7_ILP32_OFFBIG_LIBS 1138
#define _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS 1139
#define _CS_POSIX_V7_LP64_OFF64_CFLAGS 1140
#define _CS_POSIX_V7_LP64_OFF64_LDFLAGS 1141
#define _CS_POSIX_V7_LP64_OFF64_LIBS 1142
#define _CS_POSIX_V7_LP64_OFF64_LINTFLAGS 1143
#define _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS 1144
#define _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS 1145
#define _CS_POSIX_V7_LPBIG_OFFBIG_LIBS 1146
#define _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS 1147
#define _CS_V6_ENV 1148
#define _CS_V7_ENV 1149
#define _CS_POSIX_V7_THREADS_CFLAGS 1150
#define _CS_POSIX_V7_THREADS_LDFLAGS 1151
Functions
int pipe (int[2])
int pipe2 (int[2], int)
int close (int)
int posix_close (int, int)
int dup (int)
int dup2 (int, int)
int dup3 (int, int, int)
off_t lseek (int, off_t, int)
int fsync (int)
int fdatasync (int)
ssize_t read (int, void *, size_t)
ssize_t write (int, const void *, size_t)
ssize_t pread (int, void *, size_t, off_t)
ssize_t pwrite (int, const void *, size_t, off_t)
int chown (const char *, uid_t, gid_t)
int fchown (int, uid_t, gid_t)
int lchown (const char *, uid_t, gid_t)
int fchownat (int, const char *, uid_t, gid_t, int)
int link (const char *, const char *)
int linkat (int, const char *, int, const char *, int)
int symlink (const char *, const char *)
int symlinkat (const char *, int, const char *)
ssize_t readlink (const char *__restrict, char *__restrict, size_t)
ssize_t readlinkat (int, const char *__restrict, char *__restrict, size_t)
int unlink (const char *)
int unlinkat (int, const char *, int)
int rmdir (const char *)
int truncate (const char *, off_t)
int ftruncate (int, off_t)
int access (const char *, int)
int faccessat (int, const char *, int, int)
int chdir (const char *)
int fchdir (int)
char * getcwd (char *, size_t)
unsigned alarm (unsigned)
unsigned sleep (unsigned)
int pause (void)
pid_t fork (void)
pid_t _Fork (void)
int execve (const char *, char *const [], char *const [])
int execv (const char *, char *const [])
int execle (const char *, const char *,...)
int execl (const char *, const char *,...)
int execvp (const char *, char *const [])
int execlp (const char *, const char *,...)
int fexecve (int, char *const [], char *const [])
_Noreturn void _exit (int)
pid_t getpid (void)
pid_t getppid (void)
pid_t getpgrp (void)
pid_t getpgid (pid_t)
int setpgid (pid_t, pid_t)
pid_t setsid (void)
pid_t getsid (pid_t)
char * ttyname (int)
int ttyname_r (int, char *, size_t)
int isatty (int)
pid_t tcgetpgrp (int)
int tcsetpgrp (int, pid_t)
uid_t getuid (void)
uid_t geteuid (void)
gid_t getgid (void)
gid_t getegid (void)
int getgroups (int, gid_t[])
int setuid (uid_t)
int seteuid (uid_t)
int setgid (gid_t)
int setegid (gid_t)
char * getlogin (void)
int getlogin_r (char *, size_t)
int gethostname (char *, size_t)
char * ctermid (char *)
int getopt (int, char *const [], const char *)
long pathconf (const char *, int)
long fpathconf (int, int)
long sysconf (int)
size_t confstr (int, char *, size_t)
Variables
char * optarg
int optind
int opterr
int optopt
Macro Definition Documentation
__NEED_gid_t
#define __NEED_gid_t
Definition at line 31 of file unistd.h.
__NEED_intptr_t
#define __NEED_intptr_t
Definition at line 34 of file unistd.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 32 of file unistd.h.
__NEED_pid_t
#define __NEED_pid_t
Definition at line 33 of file unistd.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 28 of file unistd.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 29 of file unistd.h.
__NEED_uid_t
#define __NEED_uid_t
Definition at line 30 of file unistd.h.
__NEED_useconds_t
#define __NEED_useconds_t
Definition at line 35 of file unistd.h.
_CS_GNU_LIBC_VERSION
#define _CS_GNU_LIBC_VERSION 2
Definition at line 433 of file unistd.h.
_CS_GNU_LIBPTHREAD_VERSION
#define _CS_GNU_LIBPTHREAD_VERSION 3
Definition at line 434 of file unistd.h.
_CS_PATH
#define _CS_PATH 0
Definition at line 431 of file unistd.h.
_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS 4
Definition at line 435 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_CFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_CFLAGS 1116
Definition at line 438 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LDFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_LDFLAGS 1117
Definition at line 439 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LIBS
#define _CS_POSIX_V6_ILP32_OFF32_LIBS 1118
Definition at line 440 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS 1119
Definition at line 441 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS 1120
Definition at line 442 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS 1121
Definition at line 443 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LIBS
#define _CS_POSIX_V6_ILP32_OFFBIG_LIBS 1122
Definition at line 444 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS 1123
Definition at line 445 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_CFLAGS
#define _CS_POSIX_V6_LP64_OFF64_CFLAGS 1124
Definition at line 446 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LDFLAGS
#define _CS_POSIX_V6_LP64_OFF64_LDFLAGS 1125
Definition at line 447 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LIBS
#define _CS_POSIX_V6_LP64_OFF64_LIBS 1126
Definition at line 448 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LINTFLAGS
#define _CS_POSIX_V6_LP64_OFF64_LINTFLAGS 1127
Definition at line 449 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS 1128
Definition at line 450 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS 1129
Definition at line 451 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LIBS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LIBS 1130
Definition at line 452 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS 1131
Definition at line 453 of file unistd.h.
_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS 1
Definition at line 432 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_CFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_CFLAGS 1132
Definition at line 454 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LDFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_LDFLAGS 1133
Definition at line 455 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LIBS
#define _CS_POSIX_V7_ILP32_OFF32_LIBS 1134
Definition at line 456 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS 1135
Definition at line 457 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS 1136
Definition at line 458 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS 1137
Definition at line 459 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LIBS
#define _CS_POSIX_V7_ILP32_OFFBIG_LIBS 1138
Definition at line 460 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS 1139
Definition at line 461 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_CFLAGS
#define _CS_POSIX_V7_LP64_OFF64_CFLAGS 1140
Definition at line 462 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LDFLAGS
#define _CS_POSIX_V7_LP64_OFF64_LDFLAGS 1141
Definition at line 463 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LIBS
#define _CS_POSIX_V7_LP64_OFF64_LIBS 1142
Definition at line 464 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LINTFLAGS
#define _CS_POSIX_V7_LP64_OFF64_LINTFLAGS 1143
Definition at line 465 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS 1144
Definition at line 466 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS 1145
Definition at line 467 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LIBS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LIBS 1146
Definition at line 468 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS 1147
Definition at line 469 of file unistd.h.
_CS_POSIX_V7_THREADS_CFLAGS
#define _CS_POSIX_V7_THREADS_CFLAGS 1150
Definition at line 472 of file unistd.h.
_CS_POSIX_V7_THREADS_LDFLAGS
#define _CS_POSIX_V7_THREADS_LDFLAGS 1151
Definition at line 473 of file unistd.h.
_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS 5
Definition at line 436 of file unistd.h.
_CS_V6_ENV
#define _CS_V6_ENV 1148
Definition at line 470 of file unistd.h.
_CS_V7_ENV
#define _CS_V7_ENV 1149
Definition at line 471 of file unistd.h.
_PC_2_SYMLINKS
#define _PC_2_SYMLINKS 20
Definition at line 284 of file unistd.h.
_PC_ALLOC_SIZE_MIN
#define _PC_ALLOC_SIZE_MIN 18
Definition at line 282 of file unistd.h.
_PC_ASYNC_IO
#define _PC_ASYNC_IO 10
Definition at line 274 of file unistd.h.
_PC_CHOWN_RESTRICTED
#define _PC_CHOWN_RESTRICTED 6
Definition at line 270 of file unistd.h.
_PC_FILESIZEBITS
#define _PC_FILESIZEBITS 13
Definition at line 277 of file unistd.h.
_PC_LINK_MAX
#define _PC_LINK_MAX 0
Definition at line 264 of file unistd.h.
_PC_MAX_CANON
#define _PC_MAX_CANON 1
Definition at line 265 of file unistd.h.
_PC_MAX_INPUT
#define _PC_MAX_INPUT 2
Definition at line 266 of file unistd.h.
_PC_NAME_MAX
#define _PC_NAME_MAX 3
Definition at line 267 of file unistd.h.
_PC_NO_TRUNC
#define _PC_NO_TRUNC 7
Definition at line 271 of file unistd.h.
_PC_PATH_MAX
#define _PC_PATH_MAX 4
Definition at line 268 of file unistd.h.
_PC_PIPE_BUF
#define _PC_PIPE_BUF 5
Definition at line 269 of file unistd.h.
_PC_PRIO_IO
#define _PC_PRIO_IO 11
Definition at line 275 of file unistd.h.
_PC_REC_INCR_XFER_SIZE
#define _PC_REC_INCR_XFER_SIZE 14
Definition at line 278 of file unistd.h.
_PC_REC_MAX_XFER_SIZE
#define _PC_REC_MAX_XFER_SIZE 15
Definition at line 279 of file unistd.h.
_PC_REC_MIN_XFER_SIZE
#define _PC_REC_MIN_XFER_SIZE 16
Definition at line 280 of file unistd.h.
_PC_REC_XFER_ALIGN
#define _PC_REC_XFER_ALIGN 17
Definition at line 281 of file unistd.h.
_PC_SOCK_MAXBUF
#define _PC_SOCK_MAXBUF 12
Definition at line 276 of file unistd.h.
_PC_SYMLINK_MAX
#define _PC_SYMLINK_MAX 19
Definition at line 283 of file unistd.h.
_PC_SYNC_IO
#define _PC_SYNC_IO 9
Definition at line 273 of file unistd.h.
_PC_VDISABLE
#define _PC_VDISABLE 8
Definition at line 272 of file unistd.h.
_POSIX2_C_BIND
#define _POSIX2_C_BIND _POSIX_VERSION
Definition at line 258 of file unistd.h.
_POSIX2_VERSION
#define _POSIX2_VERSION _POSIX_VERSION
Definition at line 218 of file unistd.h.
_POSIX_ADVISORY_INFO
#define _POSIX_ADVISORY_INFO _POSIX_VERSION
Definition at line 220 of file unistd.h.
_POSIX_ASYNCHRONOUS_IO
#define _POSIX_ASYNCHRONOUS_IO _POSIX_VERSION
Definition at line 254 of file unistd.h.
_POSIX_BARRIERS
#define _POSIX_BARRIERS _POSIX_VERSION
Definition at line 251 of file unistd.h.
_POSIX_CHOWN_RESTRICTED
#define _POSIX_CHOWN_RESTRICTED 1
Definition at line 221 of file unistd.h.
_POSIX_CLOCK_SELECTION
#define _POSIX_CLOCK_SELECTION _POSIX_VERSION
Definition at line 250 of file unistd.h.
_POSIX_CPUTIME
#define _POSIX_CPUTIME _POSIX_VERSION
Definition at line 249 of file unistd.h.
_POSIX_FSYNC
#define _POSIX_FSYNC _POSIX_VERSION
Definition at line 229 of file unistd.h.
_POSIX_IPV6
#define _POSIX_IPV6 _POSIX_VERSION
Definition at line 222 of file unistd.h.
_POSIX_JOB_CONTROL
#define _POSIX_JOB_CONTROL 1
Definition at line 223 of file unistd.h.
_POSIX_MAPPED_FILES
#define _POSIX_MAPPED_FILES _POSIX_VERSION
Definition at line 224 of file unistd.h.
_POSIX_MEMLOCK
#define _POSIX_MEMLOCK _POSIX_VERSION
Definition at line 225 of file unistd.h.
_POSIX_MEMLOCK_RANGE
#define _POSIX_MEMLOCK_RANGE _POSIX_VERSION
Definition at line 226 of file unistd.h.
_POSIX_MEMORY_PROTECTION
#define _POSIX_MEMORY_PROTECTION _POSIX_VERSION
Definition at line 227 of file unistd.h.
_POSIX_MESSAGE_PASSING
#define _POSIX_MESSAGE_PASSING _POSIX_VERSION
Definition at line 228 of file unistd.h.
_POSIX_MONOTONIC_CLOCK
#define _POSIX_MONOTONIC_CLOCK _POSIX_VERSION
Definition at line 248 of file unistd.h.
_POSIX_NO_TRUNC
#define _POSIX_NO_TRUNC 1
Definition at line 230 of file unistd.h.
_POSIX_RAW_SOCKETS
#define _POSIX_RAW_SOCKETS _POSIX_VERSION
Definition at line 231 of file unistd.h.
_POSIX_READER_WRITER_LOCKS
#define _POSIX_READER_WRITER_LOCKS _POSIX_VERSION
Definition at line 253 of file unistd.h.
_POSIX_REALTIME_SIGNALS
#define _POSIX_REALTIME_SIGNALS _POSIX_VERSION
Definition at line 232 of file unistd.h.
_POSIX_REGEXP
#define _POSIX_REGEXP 1
Definition at line 233 of file unistd.h.
_POSIX_SAVED_IDS
#define _POSIX_SAVED_IDS 1
Definition at line 234 of file unistd.h.
_POSIX_SEMAPHORES
#define _POSIX_SEMAPHORES _POSIX_VERSION
Definition at line 255 of file unistd.h.
_POSIX_SHARED_MEMORY_OBJECTS
#define _POSIX_SHARED_MEMORY_OBJECTS _POSIX_VERSION
Definition at line 256 of file unistd.h.
_POSIX_SHELL
#define _POSIX_SHELL 1
Definition at line 235 of file unistd.h.
_POSIX_SPAWN
#define _POSIX_SPAWN _POSIX_VERSION
Definition at line 236 of file unistd.h.
_POSIX_SPIN_LOCKS
#define _POSIX_SPIN_LOCKS _POSIX_VERSION
Definition at line 252 of file unistd.h.
_POSIX_THREAD_ATTR_STACKADDR
#define _POSIX_THREAD_ATTR_STACKADDR _POSIX_VERSION
Definition at line 242 of file unistd.h.
_POSIX_THREAD_ATTR_STACKSIZE
#define _POSIX_THREAD_ATTR_STACKSIZE _POSIX_VERSION
Definition at line 243 of file unistd.h.
_POSIX_THREAD_CPUTIME
#define _POSIX_THREAD_CPUTIME _POSIX_VERSION
Definition at line 245 of file unistd.h.
_POSIX_THREAD_PRIORITY_SCHEDULING
#define _POSIX_THREAD_PRIORITY_SCHEDULING _POSIX_VERSION
Definition at line 244 of file unistd.h.
_POSIX_THREAD_PROCESS_SHARED
#define _POSIX_THREAD_PROCESS_SHARED _POSIX_VERSION
Definition at line 240 of file unistd.h.
_POSIX_THREAD_SAFE_FUNCTIONS
#define _POSIX_THREAD_SAFE_FUNCTIONS _POSIX_VERSION
Definition at line 241 of file unistd.h.
_POSIX_THREADS
#define _POSIX_THREADS _POSIX_VERSION
Definition at line 239 of file unistd.h.
_POSIX_TIMEOUTS
#define _POSIX_TIMEOUTS _POSIX_VERSION
Definition at line 247 of file unistd.h.
_POSIX_TIMERS
#define _POSIX_TIMERS _POSIX_VERSION
Definition at line 246 of file unistd.h.
_POSIX_VDISABLE
#define _POSIX_VDISABLE 0
Definition at line 237 of file unistd.h.
_POSIX_VERSION
#define _POSIX_VERSION 200809L
Definition at line 217 of file unistd.h.
_SC_2_C_BIND
#define _SC_2_C_BIND 47
Definition at line 332 of file unistd.h.
_SC_2_C_DEV
#define _SC_2_C_DEV 48
Definition at line 333 of file unistd.h.
_SC_2_CHAR_TERM
#define _SC_2_CHAR_TERM 95
Definition at line 368 of file unistd.h.
_SC_2_FORT_DEV
#define _SC_2_FORT_DEV 49
Definition at line 334 of file unistd.h.
_SC_2_FORT_RUN
#define _SC_2_FORT_RUN 50
Definition at line 335 of file unistd.h.
_SC_2_LOCALEDEF
#define _SC_2_LOCALEDEF 52
Definition at line 337 of file unistd.h.
_SC_2_PBS
#define _SC_2_PBS 168
Definition at line 396 of file unistd.h.
_SC_2_PBS_ACCOUNTING
#define _SC_2_PBS_ACCOUNTING 169
Definition at line 397 of file unistd.h.
_SC_2_PBS_CHECKPOINT
#define _SC_2_PBS_CHECKPOINT 175
Definition at line 403 of file unistd.h.
_SC_2_PBS_LOCATE
#define _SC_2_PBS_LOCATE 170
Definition at line 398 of file unistd.h.
_SC_2_PBS_MESSAGE
#define _SC_2_PBS_MESSAGE 171
Definition at line 399 of file unistd.h.
_SC_2_PBS_TRACK
#define _SC_2_PBS_TRACK 172
Definition at line 400 of file unistd.h.
_SC_2_SW_DEV
#define _SC_2_SW_DEV 51
Definition at line 336 of file unistd.h.
_SC_2_UPE
#define _SC_2_UPE 97
Definition at line 369 of file unistd.h.
_SC_2_VERSION
#define _SC_2_VERSION 46
Definition at line 331 of file unistd.h.
_SC_ADVISORY_INFO
#define _SC_ADVISORY_INFO 132
Definition at line 381 of file unistd.h.
_SC_AIO_LISTIO_MAX
#define _SC_AIO_LISTIO_MAX 23
Definition at line 309 of file unistd.h.
_SC_AIO_MAX
#define _SC_AIO_MAX 24
Definition at line 310 of file unistd.h.
_SC_AIO_PRIO_DELTA_MAX
#define _SC_AIO_PRIO_DELTA_MAX 25
Definition at line 311 of file unistd.h.
_SC_ARG_MAX
#define _SC_ARG_MAX 0
Definition at line 286 of file unistd.h.
_SC_ASYNCHRONOUS_IO
#define _SC_ASYNCHRONOUS_IO 12
Definition at line 298 of file unistd.h.
_SC_ATEXIT_MAX
#define _SC_ATEXIT_MAX 87
Definition at line 360 of file unistd.h.
_SC_AVPHYS_PAGES
#define _SC_AVPHYS_PAGES 86
Definition at line 359 of file unistd.h.
_SC_BARRIERS
#define _SC_BARRIERS 133
Definition at line 382 of file unistd.h.
_SC_BC_BASE_MAX
#define _SC_BC_BASE_MAX 36
Definition at line 323 of file unistd.h.
_SC_BC_DIM_MAX
#define _SC_BC_DIM_MAX 37
Definition at line 324 of file unistd.h.
_SC_BC_SCALE_MAX
#define _SC_BC_SCALE_MAX 38
Definition at line 325 of file unistd.h.
_SC_BC_STRING_MAX
#define _SC_BC_STRING_MAX 39
Definition at line 326 of file unistd.h.
_SC_CHILD_MAX
#define _SC_CHILD_MAX 1
Definition at line 287 of file unistd.h.
_SC_CLK_TCK
#define _SC_CLK_TCK 2
Definition at line 288 of file unistd.h.
_SC_CLOCK_SELECTION
#define _SC_CLOCK_SELECTION 137
Definition at line 383 of file unistd.h.
_SC_COLL_WEIGHTS_MAX
#define _SC_COLL_WEIGHTS_MAX 40
Definition at line 327 of file unistd.h.
_SC_CPUTIME
#define _SC_CPUTIME 138
Definition at line 384 of file unistd.h.
_SC_DELAYTIMER_MAX
#define _SC_DELAYTIMER_MAX 26
Definition at line 312 of file unistd.h.
_SC_EXPR_NEST_MAX
#define _SC_EXPR_NEST_MAX 42
Definition at line 328 of file unistd.h.
_SC_FSYNC
#define _SC_FSYNC 15
Definition at line 301 of file unistd.h.
_SC_GETGR_R_SIZE_MAX
#define _SC_GETGR_R_SIZE_MAX 69
Definition at line 342 of file unistd.h.
_SC_GETPW_R_SIZE_MAX
#define _SC_GETPW_R_SIZE_MAX 70
Definition at line 343 of file unistd.h.
_SC_HOST_NAME_MAX
#define _SC_HOST_NAME_MAX 180
Definition at line 408 of file unistd.h.
_SC_IOV_MAX
#define _SC_IOV_MAX 60
Definition at line 339 of file unistd.h.
_SC_IPV6
#define _SC_IPV6 235
Definition at line 414 of file unistd.h.
_SC_JOB_CONTROL
#define _SC_JOB_CONTROL 7
Definition at line 293 of file unistd.h.
_SC_LINE_MAX
#define _SC_LINE_MAX 43
Definition at line 329 of file unistd.h.
_SC_LOGIN_NAME_MAX
#define _SC_LOGIN_NAME_MAX 71
Definition at line 344 of file unistd.h.
_SC_MAPPED_FILES
#define _SC_MAPPED_FILES 16
Definition at line 302 of file unistd.h.
_SC_MEMLOCK
#define _SC_MEMLOCK 17
Definition at line 303 of file unistd.h.
_SC_MEMLOCK_RANGE
#define _SC_MEMLOCK_RANGE 18
Definition at line 304 of file unistd.h.
_SC_MEMORY_PROTECTION
#define _SC_MEMORY_PROTECTION 19
Definition at line 305 of file unistd.h.
_SC_MESSAGE_PASSING
#define _SC_MESSAGE_PASSING 20
Definition at line 306 of file unistd.h.
_SC_MINSIGSTKSZ
#define _SC_MINSIGSTKSZ 249
Definition at line 428 of file unistd.h.
_SC_MONOTONIC_CLOCK
#define _SC_MONOTONIC_CLOCK 149
Definition at line 386 of file unistd.h.
_SC_MQ_OPEN_MAX
#define _SC_MQ_OPEN_MAX 27
Definition at line 313 of file unistd.h.
_SC_MQ_PRIO_MAX
#define _SC_MQ_PRIO_MAX 28
Definition at line 314 of file unistd.h.
_SC_NGROUPS_MAX
#define _SC_NGROUPS_MAX 3
Definition at line 289 of file unistd.h.
_SC_NPROCESSORS_CONF
#define _SC_NPROCESSORS_CONF 83
Definition at line 356 of file unistd.h.
_SC_NPROCESSORS_ONLN
#define _SC_NPROCESSORS_ONLN 84
Definition at line 357 of file unistd.h.
_SC_NZERO
#define _SC_NZERO 109
Definition at line 373 of file unistd.h.
_SC_OPEN_MAX
#define _SC_OPEN_MAX 4
Definition at line 290 of file unistd.h.
_SC_PAGE_SIZE
#define _SC_PAGE_SIZE 30
Definition at line 316 of file unistd.h.
_SC_PAGESIZE
#define _SC_PAGESIZE 30 /* !! */
Definition at line 317 of file unistd.h.
_SC_PASS_MAX
#define _SC_PASS_MAX 88
Definition at line 361 of file unistd.h.
_SC_PHYS_PAGES
#define _SC_PHYS_PAGES 85
Definition at line 358 of file unistd.h.
_SC_PRIORITIZED_IO
#define _SC_PRIORITIZED_IO 13
Definition at line 299 of file unistd.h.
_SC_PRIORITY_SCHEDULING
#define _SC_PRIORITY_SCHEDULING 10
Definition at line 296 of file unistd.h.
_SC_RAW_SOCKETS
#define _SC_RAW_SOCKETS 236
Definition at line 415 of file unistd.h.
_SC_RE_DUP_MAX
#define _SC_RE_DUP_MAX 44
Definition at line 330 of file unistd.h.
_SC_READER_WRITER_LOCKS
#define _SC_READER_WRITER_LOCKS 153
Definition at line 387 of file unistd.h.
_SC_REALTIME_SIGNALS
#define _SC_REALTIME_SIGNALS 9
Definition at line 295 of file unistd.h.
_SC_REGEXP
#define _SC_REGEXP 155
Definition at line 389 of file unistd.h.
_SC_RTSIG_MAX
#define _SC_RTSIG_MAX 31
Definition at line 318 of file unistd.h.
_SC_SAVED_IDS
#define _SC_SAVED_IDS 8
Definition at line 294 of file unistd.h.
_SC_SEM_NSEMS_MAX
#define _SC_SEM_NSEMS_MAX 32
Definition at line 319 of file unistd.h.
_SC_SEM_VALUE_MAX
#define _SC_SEM_VALUE_MAX 33
Definition at line 320 of file unistd.h.
_SC_SEMAPHORES
#define _SC_SEMAPHORES 21
Definition at line 307 of file unistd.h.
_SC_SHARED_MEMORY_OBJECTS
#define _SC_SHARED_MEMORY_OBJECTS 22
Definition at line 308 of file unistd.h.
_SC_SHELL
#define _SC_SHELL 157
Definition at line 390 of file unistd.h.
_SC_SIGQUEUE_MAX
#define _SC_SIGQUEUE_MAX 34
Definition at line 321 of file unistd.h.
_SC_SIGSTKSZ
#define _SC_SIGSTKSZ 250
Definition at line 429 of file unistd.h.
_SC_SPAWN
#define _SC_SPAWN 159
Definition at line 391 of file unistd.h.
_SC_SPIN_LOCKS
#define _SC_SPIN_LOCKS 154
Definition at line 388 of file unistd.h.
_SC_SPORADIC_SERVER
#define _SC_SPORADIC_SERVER 160
Definition at line 392 of file unistd.h.
_SC_SS_REPL_MAX
#define _SC_SS_REPL_MAX 241
Definition at line 420 of file unistd.h.
_SC_STREAM_MAX
#define _SC_STREAM_MAX 5
Definition at line 291 of file unistd.h.
_SC_STREAMS
#define _SC_STREAMS 174
Definition at line 402 of file unistd.h.
_SC_SYMLOOP_MAX
#define _SC_SYMLOOP_MAX 173
Definition at line 401 of file unistd.h.
_SC_SYNCHRONIZED_IO
#define _SC_SYNCHRONIZED_IO 14
Definition at line 300 of file unistd.h.
_SC_THREAD_ATTR_STACKADDR
#define _SC_THREAD_ATTR_STACKADDR 77
Definition at line 350 of file unistd.h.
_SC_THREAD_ATTR_STACKSIZE
#define _SC_THREAD_ATTR_STACKSIZE 78
Definition at line 351 of file unistd.h.
_SC_THREAD_CPUTIME
#define _SC_THREAD_CPUTIME 139
Definition at line 385 of file unistd.h.
_SC_THREAD_DESTRUCTOR_ITERATIONS
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 73
Definition at line 346 of file unistd.h.
_SC_THREAD_KEYS_MAX
#define _SC_THREAD_KEYS_MAX 74
Definition at line 347 of file unistd.h.
_SC_THREAD_PRIO_INHERIT
#define _SC_THREAD_PRIO_INHERIT 80
Definition at line 353 of file unistd.h.
_SC_THREAD_PRIO_PROTECT
#define _SC_THREAD_PRIO_PROTECT 81
Definition at line 354 of file unistd.h.
_SC_THREAD_PRIORITY_SCHEDULING
#define _SC_THREAD_PRIORITY_SCHEDULING 79
Definition at line 352 of file unistd.h.
_SC_THREAD_PROCESS_SHARED
#define _SC_THREAD_PROCESS_SHARED 82
Definition at line 355 of file unistd.h.
_SC_THREAD_ROBUST_PRIO_INHERIT
#define _SC_THREAD_ROBUST_PRIO_INHERIT 247
Definition at line 426 of file unistd.h.
_SC_THREAD_ROBUST_PRIO_PROTECT
#define _SC_THREAD_ROBUST_PRIO_PROTECT 248
Definition at line 427 of file unistd.h.
_SC_THREAD_SAFE_FUNCTIONS
#define _SC_THREAD_SAFE_FUNCTIONS 68
Definition at line 341 of file unistd.h.
_SC_THREAD_SPORADIC_SERVER
#define _SC_THREAD_SPORADIC_SERVER 161
Definition at line 393 of file unistd.h.
_SC_THREAD_STACK_MIN
#define _SC_THREAD_STACK_MIN 75
Definition at line 348 of file unistd.h.
_SC_THREAD_THREADS_MAX
#define _SC_THREAD_THREADS_MAX 76
Definition at line 349 of file unistd.h.
_SC_THREADS
#define _SC_THREADS 67
Definition at line 340 of file unistd.h.
_SC_TIMEOUTS
#define _SC_TIMEOUTS 164
Definition at line 394 of file unistd.h.
_SC_TIMER_MAX
#define _SC_TIMER_MAX 35
Definition at line 322 of file unistd.h.
_SC_TIMERS
#define _SC_TIMERS 11
Definition at line 297 of file unistd.h.
_SC_TRACE
#define _SC_TRACE 181
Definition at line 409 of file unistd.h.
_SC_TRACE_EVENT_FILTER
#define _SC_TRACE_EVENT_FILTER 182
Definition at line 410 of file unistd.h.
_SC_TRACE_EVENT_NAME_MAX
#define _SC_TRACE_EVENT_NAME_MAX 242
Definition at line 421 of file unistd.h.
_SC_TRACE_INHERIT
#define _SC_TRACE_INHERIT 183
Definition at line 411 of file unistd.h.
_SC_TRACE_LOG
#define _SC_TRACE_LOG 184
Definition at line 412 of file unistd.h.
_SC_TRACE_NAME_MAX
#define _SC_TRACE_NAME_MAX 243
Definition at line 422 of file unistd.h.
_SC_TRACE_SYS_MAX
#define _SC_TRACE_SYS_MAX 244
Definition at line 423 of file unistd.h.
_SC_TRACE_USER_EVENT_MAX
#define _SC_TRACE_USER_EVENT_MAX 245
Definition at line 424 of file unistd.h.
_SC_TTY_NAME_MAX
#define _SC_TTY_NAME_MAX 72
Definition at line 345 of file unistd.h.
_SC_TYPED_MEMORY_OBJECTS
#define _SC_TYPED_MEMORY_OBJECTS 165
Definition at line 395 of file unistd.h.
_SC_TZNAME_MAX
#define _SC_TZNAME_MAX 6
Definition at line 292 of file unistd.h.
_SC_UIO_MAXIOV
#define _SC_UIO_MAXIOV 60 /* !! */
Definition at line 338 of file unistd.h.
_SC_V6_ILP32_OFF32
#define _SC_V6_ILP32_OFF32 176
Definition at line 404 of file unistd.h.
_SC_V6_ILP32_OFFBIG
#define _SC_V6_ILP32_OFFBIG 177
Definition at line 405 of file unistd.h.
_SC_V6_LP64_OFF64
#define _SC_V6_LP64_OFF64 178
Definition at line 406 of file unistd.h.
_SC_V6_LPBIG_OFFBIG
#define _SC_V6_LPBIG_OFFBIG 179
Definition at line 407 of file unistd.h.
_SC_V7_ILP32_OFF32
#define _SC_V7_ILP32_OFF32 237
Definition at line 416 of file unistd.h.
_SC_V7_ILP32_OFFBIG
#define _SC_V7_ILP32_OFFBIG 238
Definition at line 417 of file unistd.h.
_SC_V7_LP64_OFF64
#define _SC_V7_LP64_OFF64 239
Definition at line 418 of file unistd.h.
_SC_V7_LPBIG_OFFBIG
#define _SC_V7_LPBIG_OFFBIG 240
Definition at line 419 of file unistd.h.
_SC_VERSION
#define _SC_VERSION 29
Definition at line 315 of file unistd.h.
_SC_XBS5_ILP32_OFF32
#define _SC_XBS5_ILP32_OFF32 125
Definition at line 374 of file unistd.h.
_SC_XBS5_ILP32_OFFBIG
#define _SC_XBS5_ILP32_OFFBIG 126
Definition at line 375 of file unistd.h.
_SC_XBS5_LP64_OFF64
#define _SC_XBS5_LP64_OFF64 127
Definition at line 376 of file unistd.h.
_SC_XBS5_LPBIG_OFFBIG
#define _SC_XBS5_LPBIG_OFFBIG 128
Definition at line 377 of file unistd.h.
_SC_XOPEN_CRYPT
#define _SC_XOPEN_CRYPT 92
Definition at line 365 of file unistd.h.
_SC_XOPEN_ENH_I18N
#define _SC_XOPEN_ENH_I18N 93
Definition at line 366 of file unistd.h.
_SC_XOPEN_LEGACY
#define _SC_XOPEN_LEGACY 129
Definition at line 378 of file unistd.h.
_SC_XOPEN_REALTIME
#define _SC_XOPEN_REALTIME 130
Definition at line 379 of file unistd.h.
_SC_XOPEN_REALTIME_THREADS
#define _SC_XOPEN_REALTIME_THREADS 131
Definition at line 380 of file unistd.h.
_SC_XOPEN_SHM
#define _SC_XOPEN_SHM 94
Definition at line 367 of file unistd.h.
_SC_XOPEN_STREAMS
#define _SC_XOPEN_STREAMS 246
Definition at line 425 of file unistd.h.
_SC_XOPEN_UNIX
#define _SC_XOPEN_UNIX 91
Definition at line 364 of file unistd.h.
_SC_XOPEN_VERSION
#define _SC_XOPEN_VERSION 89
Definition at line 362 of file unistd.h.
_SC_XOPEN_XCU_VERSION
#define _SC_XOPEN_XCU_VERSION 90
Definition at line 363 of file unistd.h.
_SC_XOPEN_XPG2
#define _SC_XOPEN_XPG2 98
Definition at line 370 of file unistd.h.
_SC_XOPEN_XPG3
#define _SC_XOPEN_XPG3 99
Definition at line 371 of file unistd.h.
_SC_XOPEN_XPG4
#define _SC_XOPEN_XPG4 100
Definition at line 372 of file unistd.h.
_XOPEN_ENH_I18N
#define _XOPEN_ENH_I18N 1
Definition at line 215 of file unistd.h.
_XOPEN_UNIX
#define _XOPEN_UNIX 1
Definition at line 214 of file unistd.h.
_XOPEN_VERSION
#define _XOPEN_VERSION 700
Definition at line 213 of file unistd.h.
F_OK
#define F_OK 0
Definition at line 72 of file unistd.h.
NULL
#define NULL ((void*)0)
Definition at line 25 of file unistd.h.
POSIX_CLOSE_RESTART
#define POSIX_CLOSE_RESTART 0
Definition at line 211 of file unistd.h.
R_OK
#define R_OK 4
Definition at line 73 of file unistd.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 15 of file unistd.h.
SEEK_DATA
#define SEEK_DATA 3
Definition at line 17 of file unistd.h.
SEEK_END
#define SEEK_END 2
Definition at line 16 of file unistd.h.
SEEK_HOLE
#define SEEK_HOLE 4
Definition at line 18 of file unistd.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 14 of file unistd.h.
STDERR_FILENO
#define STDERR_FILENO 2
Definition at line 12 of file unistd.h.
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 10 of file unistd.h.
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 11 of file unistd.h.
W_OK
#define W_OK 2
Definition at line 74 of file unistd.h.
X_OK
#define X_OK 1
Definition at line 75 of file unistd.h.
Function Documentation
_exit()
_Noreturn void _exit (int Code)
Definition at line 28 of file ldstart.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(0), "D"(Code)
                          : "rcx", "r11", "memory");
     while (1)
         ;
 }
References __asm__(), __libc_fini_array(), __libc_fini_std(), _Exit(), mlibc::status, mlibc::sys_exit(), and syscall1().
Referenced by __attribute__(), __dls3(), child(), daemon(), do_wordexp(), exit(), forkpty(), main(), and we_askshell().
_Fork()
pid_t _Fork (void)
Definition at line 12 of file _Fork.c.
 {
     pid_t ret;
     sigset_t set;
     __block_all_sigs(&set);
     LOCK(__abort_lock);
 #ifdef SYS_fork
     ret = __syscall(SYS_fork);
 #else
     ret = __syscall(SYS_clone, SIGCHLD, 0);
 #endif
     if (!ret) {
         pthread_t self = __pthread_self();
         self->tid = __syscall(SYS_gettid);
         self->robust_list.off = 0;
         self->robust_list.pending = 0;
         self->next = self->prev = self;
         __thread_list_lock = 0;
         libc.threads_minus_1 = 0;
         if (libc.need_locks) libc.need_locks = -1;
     }
     UNLOCK(__abort_lock);
     if (!ret) __aio_atfork(1);
     __restore_sigs(&set);
     return __syscall_ret(ret);
 }
References __abort_lock, __aio_atfork(), __block_all_sigs(), __pthread_self, __restore_sigs(), __syscall, __syscall_ret(), __thread_list_lock, libc, LOCK, ret, SIGCHLD, and UNLOCK.
Referenced by fork().
access()
int access (const char * path, int mode)
Definition at line 1074 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_access, -1);
     if(int e = mlibc::sys_access(path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_access(), and syscall().
Referenced by dir_ok(), file_status(), main(), run_test(), sem_open(), sh_eaccess(), and stat_char().
alarm()
unsigned alarm (unsigned seconds)
Definition at line 5 of file alarm.c.
 {
     struct itimerval it = { .it_value.tv_sec = seconds }, old = { 0 };
     setitimer(ITIMER_REAL, &it, &old);
     return old.it_value.tv_sec + !!old.it_value.tv_usec;
 }
References itimerval::it_value, ITIMER_REAL, setitimer(), and timeval::tv_sec.
Referenced by main().
chdir()
int chdir (const char * path)
Definition at line 25 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_chdir, -1);
     if(int e = mlibc::sys_chdir(path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_chdir(), and syscall().
Referenced by child(), com_cd(), daemon(), and prepare().
chown()
int chown (const char * path, uid_t uid, gid_t gid)
Definition at line 43 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(AT_FDCWD, path, uid, gid, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_fchownat(), and syscall().
Referenced by history_do_write(), and history_truncate_file().
close()
int close (int fd)
Definition at line 899 of file unistd-stubs.cpp.
                   {
     return mlibc::sys_close(fd);
 }
References __aio_close(), __syscall_cp, __syscall_ret(), EINTR, r, and mlibc::sys_close().
Referenced by __dls3(), __lookup_name(), __nscd_query(), __res_msend_rc(), _evalfile(), _nl_load_domain(), _rl_read_file(), _vsyslog(), accept_builtin(), async_redirect_stdin(), cat_file(), cat_main(), check_dev_tty(), child(), close_fd_bitmap(), close_pipes(), closedir(), closelog(), command_substitute(), cutfile(), daemon(), do_nftw(), do_piping(), do_redirection_internal(), do_wordexp(), dprintf(), dup2(), execute_pipeline(), extract_info(), fmtmsg(), forkpty(), getaddrinfo(), getpass(), getspnam_r(), here_document_to_fd(), history_do_write(), history_truncate_file(), load_library(), login_tty(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), main(), mktemp_builtin(), move_to_high_fd(), noclobber_open(), open_shell_script(), openpty(), optimize_cat_file(), parse_comsub(), parse_matched_pair(), posix_close(), posix_spawn(), pthread_getname_np(), pthread_setname_np(), read_history_range(), restart_job_control(), restore_stdin(), run_test(), sem_open(), sh_closepipe(), sh_mktmpfp(), skip_matched_pair(), start(), start_tcp(), tee_builtin(), tgetent(), urandom_close(), we_askshell(), and xtrace_reset().
confstr()
size_t confstr (int name, char * buf, size_t len)
Definition at line 52 of file unistd-stubs.cpp.
{
     const char *str = "";
     if (name == _CS_PATH) {
         str = "/bin:/usr/bin";
     } else if(name == _CS_GNU_LIBPTHREAD_VERSION) {
         // We are not glibc, so we can return 0 here.
         return 0;
     } else if(name == _CS_GNU_LIBC_VERSION) {
         // We are not glibc, so we can return 0 here.
         return 0;
     } else {
         mlibc::infoLogger() << "\e[31mmlibc: confstr() request " << name << " is unimplemented\e[39m"
                 << frg::endlog;
         __ensure(!"Not implemented");
     }
     return snprintf(buf, len, "%s", str) + 1;
 }
References __ensure, _CS_GNU_LIBC_VERSION, _CS_GNU_LIBPTHREAD_VERSION, _CS_PATH, _CS_POSIX_V6_ILP32_OFF32_CFLAGS, buf, EINVAL, errno, mlibc::infoLogger, name, snprintf(), and str.
Referenced by conf_standard_path(), and getconf_print().
ctermid()
char* ctermid (char * s)
Definition at line 1121 of file unistd-stubs.cpp.
{
     return s ? strcpy(s, "/dev/tty") : const_cast<char *>("/dev/tty");
 }
References strcpy().
dup()
int dup (int fd)
Definition at line 925 of file unistd-stubs.cpp.
                 {
     int newfd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_dup, -1);
     if(int e = mlibc::sys_dup(fd, 0, &newfd); e) {
         errno = e;
         return -1;
     }
     return newfd;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_dup(), and syscall().
Referenced by child(), dprintf(), initialize_job_control(), print_builtin(), and tre_make_trans().
dup2()
int dup2 (int fd1, int fd2)
Definition at line 88 of file oslib.c.
 {
   int saved_errno, r;
   /* If FD1 is not a valid file descriptor, then return immediately with
      an error. */
   if (fcntl (fd1, F_GETFL, 0) == -1)
     return (-1);
   if (fd2 < 0 || fd2 >= getdtablesize ())
     {
       errno = EBADF;
       return (-1);
     }
   if (fd1 == fd2)
     return (0);
   saved_errno = errno;
   (void) close (fd2);
   r = fcntl (fd1, F_DUPFD, fd2);
   if (r >= 0)
     errno = saved_errno;
   else
     if (errno == EINVAL)
       errno = EBADF;
   /* Force the new file descriptor to remain open across exec () calls. */
   SET_OPEN_ON_EXEC (fd2);
   return (r);
 }
References __syscall, __syscall_ret(), close(), EBADF, EBUSY, EINVAL, errno, F_DUPFD, F_GETFD, F_GETFL, fcntl(), getdtablesize(), MLIBC_CHECK_OR_ENOSYS, r, saved_errno, SET_OPEN_ON_EXEC, and mlibc::sys_dup2().
Referenced by async_redirect_stdin(), child(), command_substitute(), daemon(), do_piping(), do_redirection_internal(), do_wordexp(), login_tty(), move_to_high_fd(), open_shell_script(), restore_stdin(), and we_askshell().
dup3()
int dup3 (int fd, int newfd, int flags)
Definition at line 6 of file linux-unistd.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
execl()
int execl (const char * pathname, const char * arg, ...)
Definition at line 6 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References __ensure, arg0, argc, args, argv, environ, execv(), execve(), i, n, NULL, va_arg, va_end(), and va_start().
execle()
int execle (const char * pathname, const char * arg, ...)
Definition at line 18 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References arg0, argc, argv, execve(), i, va_arg, va_end(), and va_start().
execlp()
int execlp (const char * file, const char * arg, ...)
Definition at line 12 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References argc, argv, execvp(), i, NULL, va_arg, va_end(), and va_start().
execv()
int execv (const char * pathname, char * const argv[])
Definition at line 24 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References __environ, argv, environ, and execve().
execve()
int execve (const char * pathname, char * const argv[], char * const envp[])
Definition at line 42 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References __ensure, argv, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_execve(), and syscall().
Referenced by execl(), execle(), and execv().
execvp()
int execvp (const char * file, char * const argv[])
Definition at line 30 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References __environ, __execvpe(), argv, environ, and execvpe().
Referenced by execlp().
faccessat()
int faccessat (int dirfd, const char * pathname, int mode, int flags)
Definition at line 207 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_faccessat, -1);
     if(int e = mlibc::sys_faccessat(dirfd, pathname, mode, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __block_all_sigs(), __clone(), __restore_sigs(), __syscall, __syscall_ret(), __WCLONE, ctx::amode, AT_EACCESS, c, checker(), dirfd, EBUSY, EINVAL, ENOSYS, errno, ctx::fd, ctx::filename, flags, getegid, geteuid, getgid, getuid, MLIBC_CHECK_OR_ENOSYS, O_CLOEXEC, p, pipe2(), ret, mlibc::stack, mlibc::status, mlibc::sys_faccessat(), and syscall().
Referenced by euidaccess(), and sh_eaccess().
fchdir()
int fchdir (int fd)
Definition at line 34 of file unistd-stubs.cpp.
                    {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchdir, -1);
     if(int e = mlibc::sys_fchdir(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __procfdname(), __syscall, __syscall_ret(), buf, EBADF, errno, F_GETFD, int, MLIBC_CHECK_OR_ENOSYS, ret, mlibc::sys_fchdir(), and syscall().
Referenced by child().
fchown()
int fchown (int fd, uid_t uid, gid_t gid)
Definition at line 216 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(fd, "", uid, gid, AT_EMPTY_PATH); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __procfdname(), __syscall, __syscall_ret(), AT_EMPTY_PATH, AT_FDCWD, buf, EBADF, errno, F_GETFD, int, MLIBC_CHECK_OR_ENOSYS, ret, mlibc::sys_fchownat(), and syscall().
fchownat()
int fchownat (int fd, const char * path, uid_t uid, gid_t gid, int flags)
Definition at line 225 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(fd, path, uid, gid, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_fchownat(), and syscall().
fdatasync()
int fdatasync (int fd)
Definition at line 234 of file unistd-stubs.cpp.
                       {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fdatasync, -1);
     if(int e = mlibc::sys_fdatasync(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_fdatasync(), and syscall_cp.
Referenced by io_thread_func().
fexecve()
int fexecve (int fd, char * const argv[], char * const envp[])
Definition at line 243 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __procfdname(), __syscall, __syscall_ret(), argv, AT_EMPTY_PATH, buf, EBADF, ENOENT, ENOSYS, errno, execve(), int, and r.
fork()
pid_t fork (void)
Definition at line 48 of file exe.c.
 {
     return syscall0(sys_Fork);
 }
References __aio_atfork(), __block_app_sigs(), __fork_handler(), __inhibit_ptc(), __ldso_atfork(), __malloc_atfork(), __pthread_key_atfork(), __pthread_self, __release_ptc(), __restore_sigs(), __tl_lock(), __tl_unlock(), __vmlock_lockptr, _Fork(), atfork_locks, child(), errno, mlibc::get_current_tcb(), i, if(), libc, LOCK, MLIBC_CHECK_OR_ENOSYS, ret, mlibc::sys_fork(), and UNLOCK.
Referenced by daemon(), do_wordexp(), forkpty(), main(), make_child(), posix_spawn(), and we_askshell().
fpathconf()
long fpathconf (int fd, int name)
Definition at line 248 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, _PC_2_SYMLINKS, _PC_ALLOC_SIZE_MIN, _PC_ASYNC_IO, _PC_CHOWN_RESTRICTED, _PC_FILESIZEBITS, _PC_LINK_MAX, _PC_MAX_CANON, _PC_MAX_INPUT, _PC_NAME_MAX, _PC_NO_TRUNC, _PC_PATH_MAX, _PC_PIPE_BUF, _PC_PRIO_IO, _PC_REC_INCR_XFER_SIZE, _PC_REC_MAX_XFER_SIZE, _PC_REC_MIN_XFER_SIZE, _PC_REC_XFER_ALIGN, _PC_SOCK_MAXBUF, _PC_SYMLINK_MAX, _PC_SYNC_IO, _PC_VDISABLE, _POSIX_LINK_MAX, _POSIX_MAX_CANON, _POSIX_MAX_INPUT, EINVAL, errno, name, NAME_MAX, PATH_MAX, and PIPE_BUF.
Referenced by pathconf().
fsync()
int fsync (int fd)
Definition at line 253 of file unistd-stubs.cpp.
                   {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fsync, -1);
     if(auto e = mlibc::sys_fsync(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_fsync(), and syscall_cp.
Referenced by io_thread_func().
ftruncate()
int ftruncate (int fd, off_t size)
Definition at line 262 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ftruncate, -1);
     if(int e = mlibc::sys_ftruncate(fd, size); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __SYSCALL_LL_O, errno, mlibc::length, MLIBC_CHECK_OR_ENOSYS, size, mlibc::sys_ftruncate(), and syscall().
Referenced by history_do_write().
getcwd()
char* getcwd (char * buf, size_t size)
Definition at line 110 of file getcwd.c.
 {
   static const char dots[]
     = "../../../../../../../../../../../../../../../../../../../../../../../\
 ../../../../../../../../../../../../../../../../../../../../../../../../../../\
 ../../../../../../../../../../../../../../../../../../../../../../../../../..";
   const char *dotp, *dotlist;
   size_t dotsize;
   dev_t rootdev, thisdev;
   ino_t rootino, thisino;
   char path[PATH_MAX + 1];
   register char *pathp;
   char *pathbuf;
   size_t pathsize;
   struct stat st;
   int saved_errno;
   if (buf != NULL && size == 0)
     {
       errno = EINVAL;
       return ((char *)NULL);
     }
   pathsize = sizeof (path);
   pathp = &path[pathsize];
   *--pathp = '\0';
   pathbuf = path;
   if (stat (".", &st) < 0)
     return ((char *)NULL);
   thisdev = st.st_dev;
   thisino = st.st_ino;
   if (stat ("/", &st) < 0)
     return ((char *)NULL);
   rootdev = st.st_dev;
   rootino = st.st_ino;
   saved_errno = 0;
   dotsize = sizeof (dots) - 1;
   dotp = &dots[sizeof (dots)];
   dotlist = dots;
   while (!(thisdev == rootdev && thisino == rootino))
     {
       register DIR *dirstream;
       register struct dirent *d;
       dev_t dotdev;
       ino_t dotino;
       char mount_point;
       int namlen;
       /* Look at the parent directory.  */
       if (dotp == dotlist)
     {
       /* My, what a deep directory tree you have, Grandma.  */
       char *new;
       if (dotlist == dots)
         {
           new = (char *)malloc (dotsize * 2 + 1);
           if (new == NULL)
         goto lose;
           memcpy (new, dots, dotsize);
         }
       else
         {
           new = (char *)realloc ((PTR_T) dotlist, dotsize * 2 + 1);
           if (new == NULL)
         goto lose;
         }
       memcpy (&new[dotsize], new, dotsize);
       dotp = &new[dotsize];
       dotsize *= 2;
       new[dotsize] = '\0';
       dotlist = new;
     }
       dotp -= 3;
       /* Figure out if this directory is a mount point.  */
       if (stat (dotp, &st) < 0)
     goto lose;
       dotdev = st.st_dev;
       dotino = st.st_ino;
       mount_point = dotdev != thisdev;
       /* Search for the last directory.  */
       dirstream = opendir (dotp);
       if (dirstream == NULL)
     goto lose;
       while ((d = readdir (dirstream)) != NULL)
     {
       if (d->d_name[0] == '.' &&
           (d->d_name[1] == '\0' ||
         (d->d_name[1] == '.' && d->d_name[2] == '\0')))
         continue;
 #if defined (D_FILENO_AVAILABLE)
       if (mount_point || d->d_fileno == thisino)
 #else
       if (mount_point || _path_checkino (dotp, d->d_name, thisino))
 #endif
         {
           char *name;
           namlen = D_NAMLEN(d);
           name = (char *)
         alloca (dotlist + dotsize - dotp + 1 + namlen + 1);
           memcpy (name, dotp, dotlist + dotsize - dotp);
           name[dotlist + dotsize - dotp] = '/';
           memcpy (&name[dotlist + dotsize - dotp + 1],
               d->d_name, namlen + 1);
           if (lstat (name, &st) < 0)
         {
 #if 0
           int save = errno;
           (void) closedir (dirstream);
           errno = save;
           goto lose;
 #else
           saved_errno = errno;
 #endif
         }
           if (st.st_dev == thisdev && st.st_ino == thisino)
         break;
         }
     }
       if (d == NULL)
     {
 #if 0
       int save = errno;
 #else
       int save = errno ? errno : saved_errno;
 #endif
       (void) closedir (dirstream);
       errno = save;
       goto lose;
     }
       else
     {
       size_t space;
       while ((space = pathp - pathbuf) <= namlen)
         {
           char *new;
           if (pathbuf == path)
         {
           new = (char *)malloc (pathsize * 2);
           if (!new)
             goto lose;
         }
           else
         {
           new = (char *)realloc ((PTR_T) pathbuf, (pathsize * 2));
           if (!new)
             goto lose;
           pathp = new + space;
         }
           (void) memcpy (new + pathsize + space, pathp, pathsize - space);
           pathp = new + pathsize + space;
           pathbuf = new;
           pathsize *= 2;
         }
       pathp -= namlen;
       (void) memcpy (pathp, d->d_name, namlen);
       *--pathp = '/';
       (void) closedir (dirstream);
     }
       thisdev = dotdev;
       thisino = dotino;
     }
   if (pathp == &path[sizeof(path) - 1])
     *--pathp = '/';
   if (dotlist != dots)
     free ((PTR_T) dotlist);
   {
     size_t len = pathbuf + pathsize - pathp;
     if (buf == NULL && size <= 0)
       size = len;
     if ((size_t) size < len)
       {
     errno = ERANGE;
     goto lose2;
       }
     if (buf == NULL)
       {
     buf = (char *) malloc (size);
     if (buf == NULL)
       goto lose2;
       }
     (void) memcpy((PTR_T) buf, (PTR_T) pathp, len);
   }
   if (pathbuf != path)
     free (pathbuf);
   return (buf);
  lose:
   if ((dotlist != dots) && dotlist)
     {
       int e = errno;
       free ((PTR_T) dotlist);
       errno = e;
     }
  lose2:
   if ((pathbuf != path) && pathbuf)
     {
       int e = errno;
       free ((PTR_T) pathbuf);
       errno = e;
     }
   return ((char *)NULL);
 }
References _path_checkino(), alloca, buf, buffer, closedir(), dirent::d_name, D_NAMLEN, EINVAL, ENOENT, ERANGE, errno, free, lstat, malloc, memcpy(), MLIBC_CHECK_OR_ENOSYS, name, NULL, opendir(), PATH_MAX, PTR_T, readdir(), realloc, ret, saved_errno, size, strdup(), mlibc::sys_getcwd(), and syscall().
Referenced by main().
getegid()
gid_t getegid (void)
Definition at line 1034 of file unistd-stubs.cpp.
                     {
     if(!mlibc::sys_getegid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getegid()");
     }
     return mlibc::sys_getegid();
 }
References __ensure, __syscall, MLIBC_MISSING_SYSDEP, and mlibc::sys_getegid().
geteuid()
uid_t geteuid (void)
Definition at line 1050 of file unistd-stubs.cpp.
                     {
     if(!mlibc::sys_geteuid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_geteuid()");
     }
     return mlibc::sys_geteuid();
 }
References __ensure, __syscall, MLIBC_MISSING_SYSDEP, and mlibc::sys_geteuid().
getgid()
gid_t getgid (void)
Definition at line 1026 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_getgid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getgid()");
     }
     return mlibc::sys_getgid();
 }
References __ensure, __syscall, MLIBC_MISSING_SYSDEP, and mlibc::sys_getgid().
getgroups()
int getgroups (int size, gid_t list[])
Definition at line 293 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getgroups, -1);
     int ret;
     if(int e = mlibc::sys_getgroups(size, list, &ret); e) {
         errno = e;
         return -1;
     }
     return ret;
 }
References count, errno, MLIBC_CHECK_OR_ENOSYS, ret, size, mlibc::sys_getgroups(), and syscall().
Referenced by initialize_group_array().
gethostname()
int gethostname (char * name, size_t namelen)
Definition at line 215 of file oslib.c.
 {
   strncpy (name, "unknown", namelen);
   name[namelen] = '\0';
   return 0;
 }
References errno, i, MLIBC_CHECK_OR_ENOSYS, name, utsname::nodename, strncpy(), mlibc::sys_gethostname(), and uname().
Referenced by shell_initialize().
getlogin()
char* getlogin (void)
Definition at line 327 of file unistd-stubs.cpp.
                      {
     return getenv("LOGNAME");
 }
References getenv.
Referenced by get_current_user_info(), getlogin_r(), logname_builtin(), and sh_get_home_dir().
getlogin_r()
int getlogin_r (char * name, size_t size)
Definition at line 331 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, ENXIO, ERANGE, getlogin(), name, size, strcpy(), and strlen().
getopt()
int getopt (int argc, char * const argv[], const char * optstring)
Definition at line 340 of file unistd-stubs.cpp.
{
     char c;
     char *place;
     optarg = NULL;
     if (!scan || *scan == '\0') {
         if (optind == 0)
             optind++;
         if (optind >= argc || argv[optind][0] != '-' || argv[optind][1] == '\0')
             return EOF;
         if (argv[optind][1] == '-' && argv[optind][2] == '\0') {
             optind++;
             return EOF;
         }
         scan = argv[optind]+1;
         optind++;
     }
     c = *scan++;
     place = strchr(optstring, c);
     if (!place || c == ':') {
         fprintf(stderr, "%s: unknown option -%c\n", argv[0], c);
         return '?';
     }
     place++;
     if (*place == ':') {
         if (*scan != '\0') {
             optarg = scan;
             scan = NULL;
         } else if( optind < argc ) {
             optarg = argv[optind];
             optind++;
         } else {
             fprintf(stderr, "%s: option requires argument -%c\n", argv[0], c);
             return ':';
         }
     }
     return c;
 }
References __getopt_msg(), __optpos, __optreset, argc, argv, c, i, k, MB_LEN_MAX, mbtowc(), optarg, opterr, optind, optopt, and optpos.
getpgid()
pid_t getpgid (pid_t pid)
Definition at line 386 of file unistd-stubs.cpp.
{
     pid_t pgid;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getpgid, -1);
     if(int e = mlibc::sys_getpgid(pid, &pgid); e) {
         errno = e;
         return -1;
     }
     return pgid;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_getpgid(), and syscall().
Referenced by getpgrp().
getpgrp()
pid_t getpgrp (void)
Definition at line 397 of file unistd-stubs.cpp.
                     {
     return getpgid(0);
 }
References __syscall.
getpid()
pid_t getpid (void)
Definition at line 1058 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_getpid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getpid()");
     }
     return mlibc::sys_getpid();
 }
References __ensure, __syscall, MLIBC_MISSING_SYSDEP, and mlibc::sys_getpid().
Referenced by _rl_handle_signal(), _vsyslog(), assign_random(), cleanup(), command_substitute(), genseed(), get_bashpid(), get_mypid(), get_random_number(), get_tty_state(), give_terminal_to(), history_tempfile(), initialize_job_control(), initialize_shell_variables(), kill_shell(), lockf(), main(), make_child(), maybe_give_terminal_to(), notify_signal(), pthread_cancel(), pthread_kill(), push_builtin(), run_pending_traps(), set_tty_state(), sh_seedrand(), anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler(), sigcont_sighandler(), sigqueue(), sigstop_sighandler(), trap_handler(), wait_for(), and wait_sigint_handler().
getppid()
pid_t getppid (void)
Definition at line 1066 of file unistd-stubs.cpp.
                     {
     if(!mlibc::sys_getppid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getppid()");
     }
     return mlibc::sys_getppid();
 }
References __ensure, __syscall, MLIBC_MISSING_SYSDEP, and mlibc::sys_getppid().
Referenced by genseed(), and set_ppid().
getsid()
pid_t getsid (pid_t pid)
Definition at line 401 of file unistd-stubs.cpp.
{
     if(!mlibc::sys_getsid) {
         MLIBC_MISSING_SYSDEP();
         return -1;
     }
     pid_t sid;
     if(int e = mlibc::sys_getsid(pid, &sid); e) {
         errno = e;
         return -1;
     }
     return sid;
 }
References errno, MLIBC_MISSING_SYSDEP, mlibc::sys_getsid(), and syscall().
getuid()
uid_t getuid (void)
Definition at line 1042 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_getuid) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_getuid()");
     }
     return mlibc::sys_getuid();
 }
References __ensure, __syscall, MLIBC_MISSING_SYSDEP, and mlibc::sys_getuid().
isatty()
int isatty (int fd)
Definition at line 1098 of file unistd-stubs.cpp.
                    {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_isatty, 0);
     if(int e = mlibc::sys_isatty(fd); e) {
         errno = e;
         return 0;
     }
     return 1;
 }
References EBADF, ENOTTY, errno, MLIBC_CHECK_OR_ENOSYS, r, mlibc::sys_isatty(), syscall(), and TIOCGWINSZ.
Referenced by _rl_input_available(), I_ConsoleStdout(), initialize_job_control(), isnetconn(), main(), open_shell_script(), rl_gather_tyi(), rl_getc(), ttyname_r(), and unary_test().
lchown()
int lchown (const char * path, uid_t uid, gid_t gid)
Definition at line 414 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchownat, -1);
     if(int e = mlibc::sys_fchownat(AT_FDCWD, path, uid, gid, AT_SYMLINK_NOFOLLOW); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, AT_SYMLINK_NOFOLLOW, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_fchownat(), and syscall().
link()
int link (const char * old_path, const char * new_path)
Definition at line 423 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_link, -1);
     if(int e = mlibc::sys_link(old_path, new_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_link(), and syscall().
Referenced by ln_builtin(), P_SetThingPosition(), rename(), and sem_open().
linkat()
int linkat (int olddirfd, const char * old_path, int newdirfd, const char * new_path, int flags)
Definition at line 432 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_linkat, -1);
     if(int e = mlibc::sys_linkat(olddirfd, old_path, newdirfd, new_path, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_linkat(), and syscall().
lseek()
off_t lseek (int fd, off_t offset, int whence)
Definition at line 881 of file unistd-stubs.cpp.
{
     off_t new_offset;
     if(int e = mlibc::sys_seek(fd, offset, whence, &new_offset); e) {
         errno = e;
         return (off_t)-1;
     }
     return new_offset;
 }
References errno, mlibc::new_offset, offset, mlibc::sys_seek(), and mlibc::whence.
Referenced by cutfile(), fd_ispipe(), history_do_write(), io_thread_func(), main(), mmap_fixed(), open_shell_script(), rewinddir(), scan_file(), seekdir(), and zsyncfd().
pathconf()
long pathconf (const char * path, int name)
Definition at line 478 of file unistd-stubs.cpp.
{
     switch (name) {
     case _PC_NAME_MAX:
         return NAME_MAX;
     default:
         mlibc::infoLogger() << "missing pathconf() entry " << name << frg::endlog;
         errno = EINVAL;
         return -1;
     }
 }
References _PC_NAME_MAX, EINVAL, errno, fpathconf(), mlibc::infoLogger, name, and NAME_MAX.
Referenced by get_tmpdir(), and getconf_print().
pause()
int pause (void)
Definition at line 489 of file unistd-stubs.cpp.
                 {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pause, -1);
     if(int e = mlibc::sys_pause(); e) {
         errno = e;
         return -1;
     }
     __ensure(!"There is no successful completion return value for pause");
     __builtin_unreachable();
 }
References __ensure, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_pause(), SYS_ppoll, and syscall_cp.
Referenced by main().
pipe()
int pipe (int fd[2])
Definition at line 4 of file pipe.c.
 {
 #ifdef SYS_pipe
     return syscall(SYS_pipe, fd);
 #else
     return syscall(SYS_pipe2, fd, 0);
 #endif
 }
pipe2()
int pipe2 (int fd[2], int flag)
Definition at line 6 of file pipe2.c.
 {
     if (!flag) return pipe(fd);
     int ret = __syscall(SYS_pipe2, fd, flag);
     if (ret != -ENOSYS) return __syscall_ret(ret);
     if (flag & ~(O_CLOEXEC|O_NONBLOCK)) return __syscall_ret(-EINVAL);
     ret = pipe(fd);
     if (ret) return ret;
     if (flag & O_CLOEXEC) {
         __syscall(SYS_fcntl, fd[0], F_SETFD, FD_CLOEXEC);
         __syscall(SYS_fcntl, fd[1], F_SETFD, FD_CLOEXEC);
     }
     if (flag & O_NONBLOCK) {
         __syscall(SYS_fcntl, fd[0], F_SETFL, O_NONBLOCK);
         __syscall(SYS_fcntl, fd[1], F_SETFL, O_NONBLOCK);
     }
     return 0;
 }
References __syscall, __syscall_ret(), EINVAL, ENOSYS, F_SETFD, F_SETFL, FD_CLOEXEC, O_CLOEXEC, O_NONBLOCK, pipe(), and ret.
posix_close()
int posix_close (int fd, int flags)
Definition at line 3 of file posix_close.c.
 {
     return close(fd);
 }
References close().
pread()
ssize_t pread (int fd, void * buf, size_t n, off_t off)
Definition at line 517 of file unistd-stubs.cpp.
{
     ssize_t num_read;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pread, -1);
     if(int e = mlibc::sys_pread(fd, buf, n, off, &num_read); e) {
         errno = e;
         return -1;
     }
     return num_read;
 }
References __SYSCALL_LL_PRW, buf, errno, MLIBC_CHECK_OR_ENOSYS, n, mlibc::off, size, mlibc::sys_pread(), and syscall_cp.
Referenced by io_thread_func(), and map_library().
pwrite()
ssize_t pwrite (int fd, const void * buf, size_t n, off_t off)
Definition at line 528 of file unistd-stubs.cpp.
{
     ssize_t num_written;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pwrite, -1);
     if(int e = mlibc::sys_pwrite(fd, buf, n, off, &num_written); e) {
         errno = e;
         return -1;
     }
     return num_written;
 }
References __SYSCALL_LL_PRW, buf, errno, MLIBC_CHECK_OR_ENOSYS, n, mlibc::off, size, mlibc::sys_pwrite(), and syscall_cp.
Referenced by io_thread_func().
read()
ssize_t read (int fd, void * buf, size_t count)
Definition at line 872 of file unistd-stubs.cpp.
{
     ssize_t bytes_read;
     if(int e = mlibc::sys_read(fd, buf, count, &bytes_read); e) {
         errno = e;
         return (ssize_t)-1;
     }
     return bytes_read;
 }
References buf, count, errno, mlibc::sys_read(), and syscall_cp.
Referenced by _evalfile(), _nl_load_domain(), _rl_read_file(), eventfd_read(), extract_info(), fcopy(), forkpty(), getc_with_restart(), getpass(), getrandom(), gobble_line(), history_truncate_file(), io_thread_func(), main(), map_library(), mmap_fixed(), open_shell_script(), posix_spawn(), pthread_getname_np(), read_history_range(), read_loop(), rl_gather_tyi(), rl_getc(), tee_builtin(), vswscanf(), we_read_fully(), zread(), zreadintr(), and zreadretry().
readlink()
ssize_t readlink (const char * __restrict, char * __restrict, size_t)
readlinkat()
ssize_t readlinkat (int , const char * __restrict, char * __restrict, size_t)
Definition at line 549 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
rmdir()
int rmdir (const char * path)
Definition at line 554 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_rmdir, -1);
     if(int e = mlibc::sys_rmdir(path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, AT_REMOVEDIR, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_rmdir(), and syscall().
Referenced by _remove_directory(), cleanup(), mktemp_builtin(), and rmdir_builtin().
setegid()
int setegid (gid_t egid)
Definition at line 563 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setegid, 0);
     if(int e = mlibc::sys_setegid(egid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __setxid(), egid, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setegid().
seteuid()
int seteuid (uid_t euid)
Definition at line 572 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_seteuid, 0);
     if(int e = mlibc::sys_seteuid(euid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __setxid(), errno, euid, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_seteuid().
setgid()
int setgid (gid_t gid)
Definition at line 581 of file unistd-stubs.cpp.
                       {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setgid, 0);
     if(int e = mlibc::sys_setgid(gid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __setxid(), errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setgid().
Referenced by child(), and disable_priv_mode().
setpgid()
int setpgid (pid_t pid, pid_t pgid)
Definition at line 590 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setpgid, -1);
     if(int e = mlibc::sys_setpgid(pid, pgid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_setpgid(), and syscall().
Referenced by setpgrp().
setsid()
pid_t setsid (void)
Definition at line 621 of file unistd-stubs.cpp.
                    {
     if(!mlibc::sys_setsid) {
         MLIBC_MISSING_SYSDEP();
         return -1;
     }
     pid_t sid;
     if(int e = mlibc::sys_setsid(&sid); e) {
         errno = e;
         return -1;
     }
     return sid;
 }
References errno, MLIBC_MISSING_SYSDEP, mlibc::sys_setsid(), and syscall().
Referenced by child(), daemon(), and login_tty().
setuid()
int setuid (uid_t uid)
Definition at line 634 of file unistd-stubs.cpp.
                       {
     if(!mlibc::sys_setuid) {
         MLIBC_MISSING_SYSDEP();
         mlibc::infoLogger() << "mlibc: missing sysdep sys_setuid(). Returning 0" << frg::endlog;
         return 0;
     }
     if(int e = mlibc::sys_setuid(uid); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __setxid(), errno, mlibc::infoLogger, MLIBC_MISSING_SYSDEP, and mlibc::sys_setuid().
Referenced by child(), and disable_priv_mode().
sleep()
unsigned sleep (unsigned seconds)
Definition at line 4 of file sleep.c.
 {
     struct timespec tv = { .tv_sec = seconds, .tv_nsec = 0 };
     if (nanosleep(&tv, &tv))
         return tv.tv_sec;
     return 0;
 }
References nanosleep(), and timespec::tv_sec.
symlink()
int symlink (const char * target_path, const char * link_path)
Definition at line 652 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_symlink, -1);
     if(int e = mlibc::sys_symlink(target_path, link_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_symlink(), and syscall().
Referenced by ln_builtin(), and prepare().
symlinkat()
int symlinkat (const char * target_path, int dirfd, const char * link_path)
Definition at line 661 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_symlinkat, -1);
     if(int e = mlibc::sys_symlinkat(target_path, dirfd, link_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_symlinkat(), and syscall().
sysconf()
long sysconf (int number)
Definition at line 678 of file unistd-stubs.cpp.
{
     switch(number) {
         case _SC_ARG_MAX:
             // On linux, it is defined to 2097152 in most cases, so define it to be 2097152
             return 2097152;
         case _SC_PAGE_SIZE:
             return mlibc::page_size;
         case _SC_OPEN_MAX:
             // TODO: actually return a proper value for _SC_OPEN_MAX
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_OPEN_MAX) returns arbitrary value 256\e[39m" << frg::endlog;
             return 256;
         case _SC_PHYS_PAGES:
             // TODO: actually return a proper value for _SC_PHYS_PAGES
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_PHYS_PAGES) returns arbitrary value 1024\e[39m" << frg::endlog;
             return 1024;
         case _SC_NPROCESSORS_ONLN:
             // TODO: actually return a proper value for _SC_NPROCESSORS_ONLN
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_NPROCESSORS_ONLN) unconditionally returns 1\e[39m" << frg::endlog;
             return 1;
         case _SC_GETPW_R_SIZE_MAX:
             return 1024;
         case _SC_GETGR_R_SIZE_MAX:
             return 1024;
         case _SC_CHILD_MAX:
             // On linux, it is defined to 25 in most cases, so define it to be 25
             return 25;
         case _SC_JOB_CONTROL:
             // If 1, job control is supported
             return 1;
         case _SC_CLK_TCK:
             // TODO: This should be obsolete?
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_CLK_TCK) is obsolete and returns arbitrary value 1000000\e[39m" << frg::endlog;
             return 1000000;
         case _SC_NGROUPS_MAX:
             // On linux, it is defined to 65536 in most cases, so define it to be 65536
             return 65536;
         case _SC_RE_DUP_MAX:
             return RE_DUP_MAX;
         case _SC_LINE_MAX:
             // Linux defines it as 2048.
             return 2048;
         case _SC_XOPEN_CRYPT:
 #if __MLIBC_CRYPT_OPTION
             return _XOPEN_CRYPT;
 #else
             return -1;
 #endif /* __MLIBC_CRYPT_OPTION */
         case _SC_NPROCESSORS_CONF:
             // TODO: actually return a proper value for _SC_NPROCESSORS_CONF
             mlibc::infoLogger() << "\e[31mmlibc: sysconf(_SC_NPROCESSORS_CONF) unconditionally returns 1\e[39m" << frg::endlog;
             return 1;
         default:
             mlibc::panicLogger() << "\e[31mmlibc: sysconf() call is not implemented, number: " << number << "\e[39m" << frg::endlog;
             __builtin_unreachable();
     }
 }
References __getauxval(), __lsysinfo(), __syscall, _NSIG, _POSIX2_BC_BASE_MAX, _POSIX2_BC_DIM_MAX, _POSIX2_BC_SCALE_MAX, _POSIX2_BC_STRING_MAX, _POSIX_VERSION, _SC_2_C_BIND, _SC_2_C_DEV, _SC_2_CHAR_TERM, _SC_2_FORT_DEV, _SC_2_FORT_RUN, _SC_2_LOCALEDEF, _SC_2_PBS, _SC_2_PBS_ACCOUNTING, _SC_2_PBS_CHECKPOINT, _SC_2_PBS_LOCATE, _SC_2_PBS_MESSAGE, _SC_2_PBS_TRACK, _SC_2_SW_DEV, _SC_2_UPE, _SC_2_VERSION, _SC_ADVISORY_INFO, _SC_AIO_LISTIO_MAX, _SC_AIO_MAX, _SC_AIO_PRIO_DELTA_MAX, _SC_ARG_MAX, _SC_ASYNCHRONOUS_IO, _SC_ATEXIT_MAX, _SC_AVPHYS_PAGES, _SC_BARRIERS, _SC_BC_BASE_MAX, _SC_BC_DIM_MAX, _SC_BC_SCALE_MAX, _SC_BC_STRING_MAX, _SC_CHILD_MAX, _SC_CLK_TCK, _SC_CLOCK_SELECTION, _SC_COLL_WEIGHTS_MAX, _SC_CPUTIME, _SC_DELAYTIMER_MAX, _SC_EXPR_NEST_MAX, _SC_FSYNC, _SC_GETGR_R_SIZE_MAX, _SC_GETPW_R_SIZE_MAX, _SC_HOST_NAME_MAX, _SC_IOV_MAX, _SC_IPV6, _SC_JOB_CONTROL, _SC_LINE_MAX, _SC_LOGIN_NAME_MAX, _SC_MAPPED_FILES, _SC_MEMLOCK, _SC_MEMLOCK_RANGE, _SC_MEMORY_PROTECTION, _SC_MESSAGE_PASSING, _SC_MINSIGSTKSZ, _SC_MONOTONIC_CLOCK, _SC_MQ_OPEN_MAX, _SC_MQ_PRIO_MAX, _SC_NGROUPS_MAX, _SC_NPROCESSORS_CONF, _SC_NPROCESSORS_ONLN, _SC_NZERO, _SC_OPEN_MAX, _SC_PAGE_SIZE, _SC_PASS_MAX, _SC_PHYS_PAGES, _SC_PRIORITIZED_IO, _SC_PRIORITY_SCHEDULING, _SC_RAW_SOCKETS, _SC_RE_DUP_MAX, _SC_READER_WRITER_LOCKS, _SC_REALTIME_SIGNALS, _SC_REGEXP, _SC_RTSIG_MAX, _SC_SAVED_IDS, _SC_SEM_NSEMS_MAX, _SC_SEM_VALUE_MAX, _SC_SEMAPHORES, _SC_SHARED_MEMORY_OBJECTS, _SC_SHELL, _SC_SIGQUEUE_MAX, _SC_SIGSTKSZ, _SC_SPAWN, _SC_SPIN_LOCKS, _SC_SPORADIC_SERVER, _SC_SS_REPL_MAX, _SC_STREAM_MAX, _SC_STREAMS, _SC_SYMLOOP_MAX, _SC_SYNCHRONIZED_IO, _SC_THREAD_ATTR_STACKADDR, _SC_THREAD_ATTR_STACKSIZE, _SC_THREAD_CPUTIME, _SC_THREAD_DESTRUCTOR_ITERATIONS, _SC_THREAD_KEYS_MAX, _SC_THREAD_PRIO_INHERIT, _SC_THREAD_PRIO_PROTECT, _SC_THREAD_PRIORITY_SCHEDULING, _SC_THREAD_PROCESS_SHARED, _SC_THREAD_ROBUST_PRIO_INHERIT, _SC_THREAD_ROBUST_PRIO_PROTECT, _SC_THREAD_SAFE_FUNCTIONS, _SC_THREAD_SPORADIC_SERVER, _SC_THREAD_STACK_MIN, _SC_THREAD_THREADS_MAX, _SC_THREADS, _SC_TIMEOUTS, _SC_TIMER_MAX, _SC_TIMERS, _SC_TRACE, _SC_TRACE_EVENT_FILTER, _SC_TRACE_EVENT_NAME_MAX, _SC_TRACE_INHERIT, _SC_TRACE_LOG, _SC_TRACE_NAME_MAX, _SC_TRACE_SYS_MAX, _SC_TRACE_USER_EVENT_MAX, _SC_TTY_NAME_MAX, _SC_TYPED_MEMORY_OBJECTS, _SC_TZNAME_MAX, _SC_V6_ILP32_OFF32, _SC_V6_ILP32_OFFBIG, _SC_V6_LP64_OFF64, _SC_V6_LPBIG_OFFBIG, _SC_V7_ILP32_OFF32, _SC_V7_ILP32_OFFBIG, _SC_V7_LP64_OFF64, _SC_V7_LPBIG_OFFBIG, _SC_VERSION, _SC_XBS5_ILP32_OFF32, _SC_XBS5_ILP32_OFFBIG, _SC_XBS5_LP64_OFF64, _SC_XBS5_LPBIG_OFFBIG, _SC_XOPEN_CRYPT, _SC_XOPEN_ENH_I18N, _SC_XOPEN_LEGACY, _SC_XOPEN_REALTIME, _SC_XOPEN_REALTIME_THREADS, _SC_XOPEN_SHM, _SC_XOPEN_STREAMS, _SC_XOPEN_UNIX, _SC_XOPEN_VERSION, _SC_XOPEN_XCU_VERSION, _SC_XOPEN_XPG2, _SC_XOPEN_XPG3, _SC_XOPEN_XPG4, _XOPEN_VERSION, AT_MINSIGSTKSZ, sysinfo::bufferram, cnt, EINVAL, errno, sysinfo::freeram, getrlimit(), HOST_NAME_MAX, i, mlibc::infoLogger, IOV_MAX, JT_ARG_MAX, JT_AVPHYS_PAGES, JT_DELAYTIMER_MAX, JT_MINSIGSTKSZ, JT_MQ_PRIO_MAX, JT_NPROCESSORS_CONF, JT_NPROCESSORS_ONLN, JT_PAGE_SIZE, JT_PHYS_PAGES, JT_SEM_VALUE_MAX, JT_SIGSTKSZ, JT_ZERO, LONG_MAX, mem, sysinfo::mem_unit, MINSIGSTKSZ, name, NOFILE, number, NZERO, mlibc::page_size, PAGE_SIZE, mlibc::panicLogger, PTHREAD_DESTRUCTOR_ITERATIONS, PTHREAD_KEYS_MAX, PTHREAD_STACK_MIN, RE_DUP_MAX, RLIM, rlimit::rlim_cur, RLIM_INFINITY, SEM_VALUE_MAX, SIGSTKSZ, sysinfo::totalram, val, and VER.
Referenced by get_avphys_pages(), get_clk_tck(), get_nprocs(), get_nprocs_conf(), get_phys_pages(), getconf_print(), getdtablesize(), getmaxchild(), getmaxgroups(), and main().
tcgetpgrp()
pid_t tcgetpgrp (int fd)
Definition at line 358 of file jobs.c.
 {
   pid_t pgrp;
   /* ioctl will handle setting errno correctly. */
   if (ioctl (fd, TIOCGPGRP, &pgrp) < 0)
     return (-1);
   return (pgrp);
 }
References ioctl(), and TIOCGPGRP.
Referenced by initialize_job_control(), maybe_give_terminal_to(), and set_job_control().
tcsetpgrp()
int tcsetpgrp (int fd, pid_t pgrp)
Definition at line 743 of file unistd-stubs.cpp.
{
     return ioctl(fd, TIOCSPGRP, &pgrp);
 }
References ioctl(), and TIOCSPGRP.
truncate()
int truncate (const char * path, off_t length)
Definition at line 747 of file unistd-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __SYSCALL_LL_O, mlibc::length, and syscall().
ttyname()
char* ttyname (int fd)
Definition at line 752 of file unistd-stubs.cpp.
                       {
     const size_t size = 128;
     static thread_local char buf[size];
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ttyname, nullptr);
     if(int e = mlibc::sys_ttyname(fd, buf, size); e) {
         errno = e;
         return nullptr;
     }
     return buf;
 }
References buf, errno, MLIBC_CHECK_OR_ENOSYS, NULL, size, mlibc::sys_ttyname(), thread_local, and ttyname_r().
ttyname_r()
int ttyname_r (int fd, char * buf, size_t size)
Definition at line 763 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ttyname, -1);
     if(int e = mlibc::sys_ttyname(fd, buf, size); e) {
         return e;
     }
     return 0;
 }
References __procfdname(), buf, ENODEV, ERANGE, errno, fstat(), int, isatty(), MLIBC_CHECK_OR_ENOSYS, name, readlink(), size, stat::st_dev, stat::st_ino, stat(), and mlibc::sys_ttyname().
Referenced by ttyname().
unlink()
int unlink (const char * path)
Definition at line 771 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_unlinkat, -1);
     if(int e = mlibc::sys_unlinkat(AT_FDCWD, path, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_unlinkat(), and syscall().
Referenced by cleanup(), dolink(), here_document_to_fd(), history_do_write(), history_truncate_file(), main(), mktemp_builtin(), rename(), rm_file(), sem_open(), shm_unlink(), and unlink_builtin().
unlinkat()
int unlinkat (int fd, const char * path, int flags)
Definition at line 780 of file unistd-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_unlinkat, -1);
     if(int e = mlibc::sys_unlinkat(fd, path, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_unlinkat(), and syscall().
write()
ssize_t write (int fd, const void * buf, size_t count)
Definition at line 863 of file unistd-stubs.cpp.
{
     ssize_t bytes_written;
     if(int e = mlibc::sys_write(fd, buf, count, &bytes_written); e) {
         errno = e;
         return (ssize_t)-1;
     }
     return bytes_written;
 }
References buf, count, errno, mlibc::sys_write(), and syscall_cp.
Referenced by alrm_catcher(), cat_main(), child(), eventfd_write(), fcopy(), forkpty(), heredoc_write(), history_do_write(), history_truncate_file(), io_thread_func(), main(), memory_out(), pthread_setname_np(), sem_open(), tee_builtin(), writev(), and zwrite().
Variable Documentation
optarg
char* optarg extern
Definition at line 12 of file getopt-stubs.cpp.
Referenced by getopt(), getopt_long(), test1(), test3(), test4(), and test6().
opterr
int opterr
Definition at line 129 of file unistd.h.
optind
int optind extern
Definition at line 13 of file getopt-stubs.cpp.
Referenced by getopt(), getopt_long(), test1(), test2(), test3(), test4(), test5(), test6(), and test7().
optopt
int optopt
Definition at line 129 of file unistd.h.