Fennix Userspace: Userspace/musl/src/termios/cfsetospeed.c File Reference
cfsetospeed.c File Reference
#include <termios.h>
#include <sys/ioctl.h>
#include <errno.h>
Macros
#define _BSD_SOURCE
Functions
int cfsetospeed (struct termios *tio, speed_t speed)
int cfsetispeed (struct termios *tio, speed_t speed)
weak_alias (cfsetospeed, cfsetspeed)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file cfsetospeed.c.
Function Documentation
cfsetispeed()
int cfsetispeed (struct termios * tio, speed_t speed)
Definition at line 17 of file cfsetospeed.c.
 {
     return speed ? cfsetospeed(tio, speed) : 0;
 }
References cfsetospeed(), and tio.
Referenced by restore_state_and_exit(), set_speed_or_die(), and slattach_main().
cfsetospeed()
int cfsetospeed (struct termios * tio, speed_t speed)
Definition at line 6 of file cfsetospeed.c.
 {
     if (speed & ~CBAUD) {
         errno = EINVAL;
         return -1;
     }
     tio->c_cflag &= ~CBAUD;
     tio->c_cflag |= speed;
     return 0;
 }
References CBAUD, EINVAL, errno, and tio.
Referenced by cfsetispeed(), restore_state_and_exit(), set_speed_or_die(), and slattach_main().
weak_alias()
weak_alias (cfsetospeed , cfsetspeed)