Fennix: E1000Device Class Reference
E1000Device Class Reference
Data Structures
struct BARData
Public Member Functions
bool IsInitialized ()
size_t write (uint8_t *Buffer, size_t Size)
MediaAccessControl GetMAC ()
int ioctl (NetIoctl req, void *arg)
void OnInterruptReceived (TrapFrame *)
void Panic ()
E1000Device (PCIHeader0 *_Header, uint16_t _DeviceID)
~E1000Device ()
Data Fields
dev_t ID
Private Member Functions
void WriteCMD (uint16_t Address, uint32_t Value)
uint32_t ReadCMD (uint16_t Address)
uint32_t ReadEEPROM (uint8_t Address)
void InitializeRX ()
void InitializeTX ()
Private Attributes
PCIHeader0 * Header
uint16_t DeviceID
bool Initialized = false
bool EEPROMAvailable
struct E1000Device::BARData BAR
RXDescriptor * RX [E1000_NUM_RX_DESC]
TXDescriptor * TX [E1000_NUM_TX_DESC]
uint16_t RXCurrent
uint16_t TXCurrent
const int BaseBufferSize = 8192
const int AdditionalBytes = 16
uint32_t CurrentPacket
Detailed Description
Definition at line 28 of file e1000.cpp.
Data Structure Documentation
E1000Device::BARData
struct E1000Device::BARData
Definition at line 37 of file e1000.cpp.
Data Fields
uint16_t IOBase
uint64_t MemoryBase
uint8_t Type
Constructor & Destructor Documentation
E1000Device()
E1000Device::E1000Device (PCIHeader0 * _Header, uint16_t _DeviceID) inline
Definition at line 259 of file e1000.cpp.
         : Header(_Header),
           DeviceID(_DeviceID)
     {
         uint32_t PCIBAR0 = Header->BAR0;
         uint32_t PCIBAR1 = Header->BAR1;
         BAR.Type = PCIBAR0 & 1;
         BAR.IOBase = (uint16_t)(PCIBAR0 & (~3));
         BAR.MemoryBase = PCIBAR1 & (~15);
         switch (DeviceID)
         {
         case 0x100E:
         {
             Log("Found Intel 82540EM Gigabit Ethernet Controller.");
             /* Detect EEPROM */
             WriteCMD(REG::EEPROM, 0x1);
             for (int i = 0; i < 1000 && !EEPROMAvailable; i++)
                 if (ReadCMD(REG::EEPROM) & 0x10)
                     EEPROMAvailable = true;
                 else
                     EEPROMAvailable = false;
             if (!GetMAC().Valid())
             {
                 Log("Failed to get MAC");
                 return;
             }
             /* Start link */
             uint32_t cmdret = ReadCMD(REG::CTRL);
             WriteCMD(REG::CTRL, cmdret | ECTRL::SLU);
             for (int i = 0; i < 0x80; i++)
                 WriteCMD((uint16_t)(0x5200 + i * 4), 0);
             WriteCMD(REG::IMASK, 0x1F6DC);
             WriteCMD(REG::IMASK, 0xFF & ~4);
             ReadCMD(0xC0);
             InitializeRX();
             InitializeTX();
             break;
         }
         default:
         {
             Log("Unimplemented E1000 device.");
             return;
         }
         }
         Initialized = true;
     }
References CTRL, i, and Log().
~E1000Device()
E1000Device::~E1000Device () inline
Definition at line 314 of file e1000.cpp.
     {
         if (!Initialized)
             return;
         switch (DeviceID)
         {
         case 0x100E:
         {
             // Clearing Enable bit in Receive Control Register
             uint32_t cmdret = ReadCMD(REG::RCTRL);
             WriteCMD(REG::RCTRL, cmdret & ~RCTL::EN);
             // Masking Interrupt Mask, Interrupt Throttling Rate & Interrupt Auto-Mask
             WriteCMD(REG::IMASK, 0x00000000);
             WriteCMD(REG::ITR, 0x00000000);
             WriteCMD(REG::IAM, 0x00000000);
             // Clearing SLU bit in Device Control Register
             cmdret = ReadCMD(REG::CTRL);
             WriteCMD(REG::CTRL, cmdret & ~ECTRL::SLU);
             // Clear the Interrupt Cause Read register by reading it
             ReadCMD(REG::ICR);
             // Powering down the device (?)
             WriteCMD(REG::CTRL, PCTRL::POWER_DOWN);
             /* TODO: Stop link; further testing required */
             break;
         }
         default:
         {
             Log("Unimplemented E1000 device.");
             return;
         }
         }
     }
References CTRL, and Log().
Member Function Documentation
GetMAC()
MediaAccessControl E1000Device::GetMAC () inline
Definition at line 183 of file e1000.cpp.
     {
         MediaAccessControl mac;
         if (EEPROMAvailable)
         {
             uint32_t temp;
             temp = ReadEEPROM(0);
             mac.Address[0] = temp & 0xff;
             mac.Address[1] = (uint8_t)(temp >> 8);
             temp = ReadEEPROM(1);
             mac.Address[2] = temp & 0xff;
             mac.Address[3] = (uint8_t)(temp >> 8);
             temp = ReadEEPROM(2);
             mac.Address[4] = temp & 0xff;
             mac.Address[5] = (uint8_t)(temp >> 8);
         }
         else
         {
             uint8_t *BaseMac8 = (uint8_t *)(BAR.MemoryBase + 0x5400);
             uint32_t *BaseMac32 = (uint32_t *)(BAR.MemoryBase + 0x5400);
             if (BaseMac32[0] != 0)
                 for (int i = 0; i < 6; i++)
                     mac.Address[i] = BaseMac8[i];
             else
             {
                 Log("No MAC address found.");
                 return MediaAccessControl();
             }
         }
         return mac;
     }
References MediaAccessControl::Address, BAR, EEPROMAvailable, i, Log(), E1000Device::BARData::MemoryBase, and ReadEEPROM().
InitializeRX()
void E1000Device::InitializeRX () inline private
Definition at line 99 of file e1000.cpp.
     {
         DebugLog("Initializing RX...");
         uintptr_t Ptr = (uintptr_t)AllocateMemory(TO_PAGES(sizeof(RXDescriptor) *
                                                                E1000_NUM_RX_DESC +
                                                            AdditionalBytes));
         for (int i = 0; i < E1000_NUM_RX_DESC; i++)
         {
             RX[i] = (RXDescriptor *)(Ptr + i * 16);
             RX[i]->Address = (uint64_t)AllocateMemory(TO_PAGES(BaseBufferSize + AdditionalBytes));
             RX[i]->Status = 0;
         }
 #pragma GCC diagnostic ignored "-Wshift-count-overflow"
         WriteCMD(REG::TXDESCLO, (uint32_t)(Ptr >> 32));
         WriteCMD(REG::TXDESCHI, (uint32_t)(Ptr & 0xFFFFFFFF));
         WriteCMD(REG::RXDESCLO, (uint32_t)Ptr);
         WriteCMD(REG::RXDESCHI, 0);
         WriteCMD(REG::RXDESCLEN, E1000_NUM_RX_DESC * 16);
         WriteCMD(REG::RXDESCHEAD, 0);
         WriteCMD(REG::RXDESCTAIL, E1000_NUM_RX_DESC - 1);
         RXCurrent = 0;
         WriteCMD(REG::RCTRL, RCTL::EN | RCTL::SBP | RCTL::UPE |
                                  RCTL::MPE | RCTL::LBM_NONE |
                                  RTCL::RDMTS_HALF | RCTL::BAM |
                                  RCTL::SECRC | RCTL::BSIZE_8192);
     }
References AdditionalBytes, AllocateMemory(), BaseBufferSize, DebugLog, E1000_NUM_RX_DESC, i, RX, RXCurrent, TO_PAGES, and WriteCMD().
InitializeTX()
void E1000Device::InitializeTX () inline private
Definition at line 132 of file e1000.cpp.
     {
         DebugLog("Initializing TX...");
         uintptr_t Ptr = (uintptr_t)AllocateMemory(TO_PAGES(sizeof(TXDescriptor) *
                                                                E1000_NUM_RX_DESC +
                                                            AdditionalBytes));
         for (short i = 0; i < E1000_NUM_TX_DESC; i++)
         {
             TX[i] = (TXDescriptor *)((uintptr_t)Ptr + i * 16);
             TX[i]->Address = 0;
             TX[i]->Command = 0;
             TX[i]->Status = TSTA::DD;
         }
         WriteCMD(REG::TXDESCHI, (uint32_t)((uint64_t)Ptr >> 32));
         WriteCMD(REG::TXDESCLO, (uint32_t)((uint64_t)Ptr & 0xFFFFFFFF));
         WriteCMD(REG::TXDESCLEN, E1000_NUM_TX_DESC * 16);
         WriteCMD(REG::TXDESCHEAD, 0);
         WriteCMD(REG::TXDESCTAIL, 0);
         TXCurrent = 0;
         WriteCMD(REG::TCTRL, TCTL::EN_ | TCTL::PSP |
                                  (15 << TCTL::CT_SHIFT) |
                                  (64 << TCTL::COLD_SHIFT) |
                                  TCTL::RTLC);
         WriteCMD(REG::TCTRL, 0b0110000000000111111000011111010);
         WriteCMD(REG::TIPG, 0x0060200A);
     }
References AdditionalBytes, AllocateMemory(), DebugLog, E1000_NUM_RX_DESC, E1000_NUM_TX_DESC, i, TO_PAGES, TX, TXCurrent, and WriteCMD().
ioctl()
int E1000Device::ioctl (NetIoctl req, void * arg) inline
Definition at line 216 of file e1000.cpp.
     {
         switch (req)
         {
         case IOCTL_NET_GET_MAC:
         {
             MediaAccessControl mac = GetMAC();
             *((uint48_t *)arg) = mac.ToHex(); /* UNTESTED */
             return 0;
         }
         default:
             return -EINVAL;
         }
         return 0;
     }
References EINVAL, IOCTL_NET_GET_MAC, and MediaAccessControl::ToHex().
Referenced by drvIoctl().
IsInitialized()
bool E1000Device::IsInitialized () inline
Definition at line 167 of file e1000.cpp.
 { return Initialized; }
References Initialized.
OnInterruptReceived()
void E1000Device::OnInterruptReceived (TrapFrame *) inline
Definition at line 232 of file e1000.cpp.
     {
         WriteCMD(REG::IMASK, 0x1);
         uint32_t status = ReadCMD(0xC0);
         UNUSED(status);
         while ((RX[RXCurrent]->Status & 0x1))
         {
             uint8_t *data = (uint8_t *)RX[RXCurrent]->Address;
             uint16_t dataSz = RX[RXCurrent]->Length;
             ReportNetworkPacket(ID, data, dataSz);
             RX[RXCurrent]->Status = 0;
             uint16_t OldRXCurrent = RXCurrent;
             RXCurrent = (uint16_t)((RXCurrent + 1) % E1000_NUM_RX_DESC);
             WriteCMD(REG::RXDESCTAIL, OldRXCurrent);
         }
     }
References Address, E1000_NUM_RX_DESC, ID, Driver::ReportNetworkPacket(), status, and UNUSED.
Panic()
void E1000Device::Panic () inline
Definition at line 252 of file e1000.cpp.
     {
         WriteCMD(REG::IMASK, 0x00000000);
         WriteCMD(REG::ITR, 0x00000000);
         WriteCMD(REG::IAM, 0x00000000);
     }
Referenced by cxx_Panic().
ReadCMD()
uint32_t E1000Device::ReadCMD (uint16_t Address) inline private
Definition at line 68 of file e1000.cpp.
     {
         if (BAR.Type == 0)
             return mminl((void *)(BAR.MemoryBase + Address));
         else
         {
             outl(BAR.IOBase, Address);
             return inl(BAR.IOBase + 0x4);
         }
     }
References Address, BAR, inl(), E1000Device::BARData::IOBase, E1000Device::BARData::MemoryBase, outl(), and E1000Device::BARData::Type.
Referenced by ReadEEPROM().
ReadEEPROM()
uint32_t E1000Device::ReadEEPROM (uint8_t Address) inline private
Definition at line 79 of file e1000.cpp.
     {
         uint16_t Data = 0;
         uint32_t temp = 0;
         if (EEPROMAvailable)
         {
             WriteCMD(REG::EEPROM, (1) | ((uint32_t)(Address) << 8));
             while (!((temp = ReadCMD(REG::EEPROM)) & (1 << 4)))
                 ;
         }
         else
         {
             WriteCMD(REG::EEPROM, (1) | ((uint32_t)(Address) << 2));
             while (!((temp = ReadCMD(REG::EEPROM)) & (1 << 1)))
                 ;
         }
         Data = (uint16_t)((temp >> 16) & 0xFFFF);
         return Data;
     }
References Address, Data, EEPROMAvailable, ReadCMD(), and WriteCMD().
Referenced by GetMAC().
write()
size_t E1000Device::write (uint8_t * Buffer, size_t Size) inline
Definition at line 169 of file e1000.cpp.
     {
         TX[TXCurrent]->Address = (uint64_t)Buffer;
         TX[TXCurrent]->Length = (uint16_t)Size;
         TX[TXCurrent]->Command = CMD::EOP | CMD::IFCS | CMD::RS;
         TX[TXCurrent]->Status = 0;
         uint16_t OldTXCurrent = TXCurrent;
         TXCurrent = (uint16_t)((TXCurrent + 1) % E1000_NUM_TX_DESC);
         WriteCMD(REG::TXDESCTAIL, TXCurrent);
         while (!(TX[OldTXCurrent]->Status & 0xFF))
             Yield();
         return Size;
     }
References Buffer, E1000_NUM_TX_DESC, RS, Size, TX, TXCurrent, WriteCMD(), and Driver::Yield().
Referenced by drvWrite().
WriteCMD()
void E1000Device::WriteCMD (uint16_t Address, uint32_t Value) inline private
Definition at line 57 of file e1000.cpp.
     {
         if (BAR.Type == 0)
             mmoutl((void *)(BAR.MemoryBase + Address), Value);
         else
         {
             outl(BAR.IOBase, Address);
             outl(BAR.IOBase + 4, Value);
         }
     }
References Address, BAR, E1000Device::BARData::IOBase, E1000Device::BARData::MemoryBase, outl(), and E1000Device::BARData::Type.
Referenced by InitializeRX(), InitializeTX(), ReadEEPROM(), and write().
Field Documentation
AdditionalBytes
const int E1000Device::AdditionalBytes = 16 private
Definition at line 53 of file e1000.cpp.
Referenced by InitializeRX(), and InitializeTX().
BAR
struct E1000Device::BARData E1000Device::BAR private
Referenced by GetMAC(), ReadCMD(), and WriteCMD().
BaseBufferSize
const int E1000Device::BaseBufferSize = 8192 private
Definition at line 52 of file e1000.cpp.
Referenced by InitializeRX().
CurrentPacket
uint32_t E1000Device::CurrentPacket private
Definition at line 55 of file e1000.cpp.
DeviceID
uint16_t E1000Device::DeviceID private
Definition at line 32 of file e1000.cpp.
EEPROMAvailable
bool E1000Device::EEPROMAvailable private
Definition at line 35 of file e1000.cpp.
Referenced by GetMAC(), and ReadEEPROM().
Header
PCIHeader0* E1000Device::Header private
Definition at line 31 of file e1000.cpp.
ID
dev_t E1000Device::ID
Definition at line 165 of file e1000.cpp.
Referenced by cxx_Initialize().
Initialized
bool E1000Device::Initialized = false private
Definition at line 33 of file e1000.cpp.
Referenced by IsInitialized().
RX
RXDescriptor* E1000Device::RX[E1000_NUM_RX_DESC] private
Definition at line 46 of file e1000.cpp.
Referenced by InitializeRX().
RXCurrent
uint16_t E1000Device::RXCurrent private
Definition at line 49 of file e1000.cpp.
Referenced by InitializeRX().
TX
TXDescriptor* E1000Device::TX[E1000_NUM_TX_DESC] private
Definition at line 47 of file e1000.cpp.
Referenced by InitializeTX(), and write().
TXCurrent
uint16_t E1000Device::TXCurrent private
Definition at line 50 of file e1000.cpp.
Referenced by InitializeTX(), and write().
The documentation for this class was generated from the following file:
Drivers/network/e1000/e1000.cpp