Fennix Userspace: Userspace/musl/src/stdio/fgetws.c File Reference
fgetws.c File Reference
#include "stdio_impl.h"
#include <wchar.h>
Functions
wint_t __fgetwc_unlocked (FILE *)
wchar_t * fgetws (wchar_t *restrict s, int n, FILE *restrict f)
weak_alias (fgetws, fgetws_unlocked)
Function Documentation
__fgetwc_unlocked()
wint_t __fgetwc_unlocked (FILE * f)
Definition at line 48 of file fgetwc.c.
 {
     locale_t *ploc = &CURRENT_LOCALE, loc = *ploc;
     if (f->mode <= 0) fwide(f, 1);
     *ploc = f->locale;
     wchar_t wc = __fgetwc_unlocked_internal(f);
     *ploc = loc;
     return wc;
 }
References __fgetwc_unlocked_internal(), CURRENT_LOCALE, f, fwide(), _IO_FILE::locale, and _IO_FILE::mode.
Referenced by fgetwc(), and fgetws().
fgetws()
wchar_t* fgetws (wchar_t *restrict s, int n, FILE *restrict f)
Definition at line 6 of file fgetws.c.
 {
     wchar_t *p = s;
     if (!n--) return s;
     FLOCK(f);
     for (; n; n--) {
         wint_t c = __fgetwc_unlocked(f);
         if (c == WEOF) break;
         *p++ = c;
         if (c == '\n') break;
     }
     *p = 0;
     if (ferror(f)) p = s;
     FUNLOCK(f);
     return (p == s) ? NULL : s;
 }
References __fgetwc_unlocked(), c, f, ferror, FLOCK, FUNLOCK, n, NULL, p, s, and WEOF.
weak_alias()
weak_alias (fgetws , fgetws_unlocked)