Fennix: Userspace/apps/base/bash/examples/loadables/whoami.c File Reference
whoami.c File Reference
#include <config.h>
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Functions
int whoami_builtin (WORD_LIST *list)
Variables
char * whoami_doc []
struct builtin whoami_struct
Function Documentation
whoami_builtin()
int whoami_builtin (WORD_LIST * list)
Definition at line 32 of file whoami.c.
 {
   int opt;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "")) != -1)
     {
       switch (opt)
     {
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   if (current_user.user_name == 0)
     get_current_user_info ();
   printf ("%s\n", current_user.user_name);
   return (EXECUTION_SUCCESS);
 }
References builtin_usage(), CASE_HELPOPT, current_user, EX_USAGE, EXECUTION_SUCCESS, get_current_user_info(), internal_getopt(), loptend, printf, reset_internal_getopt(), and user_info::user_name.
Variable Documentation
whoami_doc
char* whoami_doc[]
Initial value:
= {
    "Print user name",
    "",
    "Display name of current user.",
    (char *)NULL
}
Definition at line 61 of file whoami.c.
whoami_struct
struct builtin whoami_struct
Initial value:
= {
    "whoami",
    whoami_builtin,
    BUILTIN_ENABLED,
    whoami_doc,
    "whoami",
    0
}
Definition at line 61 of file whoami.c.