Fennix Userspace: Userspace/apps/base/fsh/fsh.c File Reference
fsh.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <signal.h>
#include <termios.h>
#include <string.h>
Macros
#define _GNU_SOURCE
#define _POSIX_SOURCE
#define MAX_COMMAND_LENGTH 1024
#define MAX_ARGS 10
Functions
void DisableInputBuffering ()
void EnableInputBuffering ()
void ReadLine (char *Buffer, size_t BufferSize)
void ExecuteCommand (char *command)
void HandleSignal (int signal)
int main ()
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 7 of file fsh.c.
_POSIX_SOURCE
#define _POSIX_SOURCE
Definition at line 10 of file fsh.c.
MAX_ARGS
#define MAX_ARGS 10
Definition at line 14 of file fsh.c.
MAX_COMMAND_LENGTH
#define MAX_COMMAND_LENGTH 1024
Definition at line 13 of file fsh.c.
Function Documentation
DisableInputBuffering()
void DisableInputBuffering ()
Definition at line 16 of file fsh.c.
 {
     struct termios tty_attr;
     tcgetattr(STDIN_FILENO, &tty_attr);
     tty_attr.c_lflag &= ~(ICANON | ECHO);
     tcsetattr(STDIN_FILENO, TCSANOW, &tty_attr);
 }
References termios::c_lflag, ECHO, ICANON, STDIN_FILENO, tcgetattr(), TCSANOW, and tcsetattr().
Referenced by main().
EnableInputBuffering()
void EnableInputBuffering ()
Definition at line 24 of file fsh.c.
 {
     struct termios tty_attr;
     tcgetattr(STDIN_FILENO, &tty_attr);
     tty_attr.c_lflag |= ICANON | ECHO;
     tcsetattr(STDIN_FILENO, TCSANOW, &tty_attr);
 }
References termios::c_lflag, ECHO, ICANON, STDIN_FILENO, tcgetattr(), TCSANOW, and tcsetattr().
Referenced by HandleSignal(), and main().
ExecuteCommand()
void ExecuteCommand (char * command)
Definition at line 71 of file fsh.c.
 {
     char *args[MAX_ARGS];
     int i = 0;
     char *token = strtok(command, " ");
     while (token != NULL && i < MAX_ARGS - 1)
     {
         args[i++] = token;
         token = strtok(NULL, " ");
     }
     args[i] = NULL;
     pid_t pid = fork();
     if (pid == 0)
     {
         execvp(args[0], args);
         perror("execvp");
         exit(EXIT_FAILURE);
     }
     else if (pid > 0)
         wait(NULL);
     else
     {
         perror("fork");
         exit(EXIT_FAILURE);
     }
 }
References execvp(), exit(), EXIT_FAILURE, fork(), i, MAX_ARGS, NULL, perror(), pid, strtok(), and wait().
Referenced by main().
HandleSignal()
void HandleSignal (int signal)
Definition at line 100 of file fsh.c.
 {
     if (signal == SIGQUIT)
     {
         EnableInputBuffering();
         printf("\n");
         exit(EXIT_SUCCESS);
     }
     else if (signal == SIGINT)
     {
         putchar('\n');
     }
     else if (signal == SIGHUP)
     {
         EnableInputBuffering();
         exit(EXIT_SUCCESS);
     }
     else if (signal == SIGCHLD)
         wait(NULL);
     else if (signal == SIGSEGV)
     {
         printf("Segmentation fault\n");
         while (1)
             sleep(1000);
     }
     else
     {
         printf("Signal %s(%d) received\n",
                strsignal(signal), signal);
     }
 }
References EnableInputBuffering(), exit(), EXIT_SUCCESS, NULL, printf(), putchar, SIGCHLD, SIGHUP, SIGINT, signal, SIGQUIT, SIGSEGV, sleep(), strsignal(), and wait().
Referenced by main().
main()
int main (void)
Definition at line 132 of file fsh.c.
 {
     char command[MAX_COMMAND_LENGTH];
     for (int i = 0; i < NSIG; ++i)
         signal(i, HandleSignal);
     char hostname[256];
     gethostname(hostname, sizeof(hostname));
     while (1)
     {
         printf("\033[1;32m");
         printf("(%s@%s)-[%s]\n", getenv("USER"), hostname, getenv("PWD"));
         printf("$ ");
         printf("\033[0m");
         DisableInputBuffering();
         ReadLine(command, sizeof(command));
         EnableInputBuffering();
         putchar('\n');
         if (strcmp(command, "exit") == 0)
             break;
         ExecuteCommand(command);
     }
     return 0;
 }
References DisableInputBuffering(), EnableInputBuffering(), ExecuteCommand(), getenv, gethostname(), HandleSignal(), i, MAX_COMMAND_LENGTH, NSIG, printf(), putchar, ReadLine(), signal, and strcmp.
Referenced by __dls2(), and _start_c().
ReadLine()
void ReadLine (char * Buffer, size_t BufferSize)
Definition at line 32 of file fsh.c.
 {
     size_t index = 0;
     int c;
     while (1)
     {
         c = getchar();
         if (c == EOF || c == '\n')
         {
             Buffer[index] = '\0';
             break;
         }
         else if (c == 127 || c == 8) // Backspace
         {
             if (index > 0)
             {
                 printf("\b \b");
                 index--;
             }
         }
         else if (c == 4) // Ctrl + D
         {
             if (index == 0)
                 kill(getpid(), SIGQUIT);
             else
                 putchar('\a');
         }
         else
         {
             if (index < BufferSize - 1)
             {
                 putchar(c);
                 Buffer[index] = (char)c;
                 index++;
             }
         }
     }
 }
References c, EOF, getchar, getpid(), index(), kill(), printf(), putchar, and SIGQUIT.
Referenced by main().