Fennix: Userspace/musl/src/misc/getentropy.c File Reference
getentropy.c File Reference
#include <unistd.h>
#include <sys/random.h>
#include <pthread.h>
#include <errno.h>
Macros
#define _BSD_SOURCE
Functions
int getentropy (void *buffer, size_t len)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file getentropy.c.
Function Documentation
getentropy()
int getentropy (void * buffer, size_t len)
Definition at line 7 of file getentropy.c.
 {
     int cs, ret = 0;
     char *pos = buffer;
     if (len > 256) {
         errno = EIO;
         return -1;
     }
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     while (len) {
         ret = getrandom(pos, len, 0);
         if (ret < 0) {
             if (errno == EINTR) continue;
             else break;
         }
         pos += ret;
         len -= ret;
         ret = 0;
     }
     pthread_setcancelstate(cs, 0);
     return ret;
 }
References buffer, EINTR, EIO, errno, getrandom(), len, pos, PTHREAD_CANCEL_DISABLE, and pthread_setcancelstate().
Referenced by getrandom().