Fennix Userspace: Userspace/apps/base/busybox/libbb/replace.c File Reference
replace.c File Reference
#include "libbb.h"
Functions
unsigned FAST_FUNC count_strstr (const char *str, const char *sub)
char *FAST_FUNC xmalloc_substitute_string (const char *src, int count, const char *sub, const char *repl)
Function Documentation
count_strstr()
unsigned FAST_FUNC count_strstr (const char * str, const char * sub)
Definition at line 13 of file replace.c.
 {
     size_t sub_len = strlen(sub);
     unsigned count = 0;
     /* If sub is empty, avoid an infinite loop */
     if (sub_len == 0)
         return strlen(str) + 1;
     while ((str = strstr(str, sub)) != NULL) {
         count++;
         str += sub_len;
     }
     return count;
 }
References count, NULL, str, strlen(), strstr(), and sub().
Referenced by parse_params().
xmalloc_substitute_string()
char* FAST_FUNC xmalloc_substitute_string (const char * src, int count, const char * sub, const char * repl)
Definition at line 29 of file replace.c.
 {
     char *buf, *dst, *end;
     size_t sub_len = strlen(sub);
     size_t repl_len = strlen(repl);
     //dbg_msg("subst(s:'%s',count:%d,sub:'%s',repl:'%s'", src, count, sub, repl);
     buf = dst = xmalloc(strlen(src) + count * ((int)repl_len - (int)sub_len) + 1);
     /* we replace each sub with repl */
     while ((end = strstr(src, sub)) != NULL) {
         dst = mempcpy(dst, src, end - src);
         dst = mempcpy(dst, repl, repl_len);
         /*src = end + 1; - GNU findutils 4.5.10 doesn't do this... */
         src = end + sub_len; /* but this. Try "xargs -Iaa echo aaa" */
     }
     strcpy(dst, src);
     //dbg_msg("subst9:'%s'", buf);
     return buf;
 }
References buf, count, dst, end, mempcpy(), NULL, repl, src, strcpy(), strlen(), strstr(), sub(), and xmalloc.