Fennix Kernel: Tasking::Security Class Reference
Tasking::Security Class Reference
#include <task.hpp>
Data Structures
struct TokenData
Public Member Functions
Token CreateToken ()
bool TrustToken (Token token, TTL TrustLevel)
bool AddTrustLevel (Token token, TTL TrustLevel)
bool RemoveTrustLevel (Token token, TTL TrustLevel)
bool UntrustToken (Token token)
bool DestroyToken (Token token)
bool IsTokenTrusted (Token token, TTL TrustLevel)
bool IsTokenTrusted (Token token, int TrustLevel)
int GetTokenTrustLevel (Token token)
Security ()
~Security ()
Private Attributes
Vector< TokenData > Tokens
Detailed Description
Definition at line 195 of file task.hpp.
Data Structure Documentation
Tasking::Security::TokenData
struct Tasking::Security::TokenData
Definition at line 198 of file task.hpp.
Data Fields
uint64_t OwnerID
bool Process
Token token
int TrustLevel
Constructor & Destructor Documentation
Security()
Tasking::Security::Security ()
Definition at line 130 of file Security.cpp.
 {}
~Security()
Tasking::Security::~Security ()
Definition at line 132 of file Security.cpp.
     {
         for (size_t i = 0; i < Tokens.size(); i++)
             Tokens.remove(i);
     }
References Tokens.
Member Function Documentation
AddTrustLevel()
bool Tasking::Security::AddTrustLevel (Token token, TTL TrustLevel)
Definition at line 53 of file Security.cpp.
     {
         foreach (auto &t in Tokens)
         {
             if (t.token == token)
             {
                 t.TrustLevel |= TrustLevel;
                 debug("Added trust level %d to token %#lx", t.TrustLevel, token);
                 return true;
             }
         }
         warn("Failed to add trust level %d to token %#lx", TrustLevel, token);
         return false;
     }
References debug, Tokens, and warn.
CreateToken()
Token Tasking::Security::CreateToken ()
Definition at line 9 of file Security.cpp.
     {
         uint64_t ret = 0;
     Retry:
         ret = Random::rand64();
         foreach (auto t in Tokens)
             if (t.token == ret)
                 goto Retry;
         Tokens.push_back({ret, UnknownTrustLevel, 0, false});
         debug("Created token %#lx", ret);
         return ret;
     }
References debug, Random::rand64(), Tokens, and Tasking::UnknownTrustLevel.
Referenced by Tasking::Task::CreateThread().
DestroyToken()
bool Tasking::Security::DestroyToken (Token token)
Definition at line 83 of file Security.cpp.
     {
         fixme("DestroyToken->true");
         UNUSED(token);
         return true;
     }
References fixme, and UNUSED.
Referenced by Tasking::Task::RemoveProcess(), Tasking::Task::RemoveThread(), Tasking::Task::RevertProcessCreation(), and Tasking::Task::RevertThreadCreation().
GetTokenTrustLevel()
int Tasking::Security::GetTokenTrustLevel (Token token)
Definition at line 120 of file Security.cpp.
     {
         foreach (auto t in Tokens)
             if (t.token == token)
                 return t.TrustLevel;
         warn("Failed to get trust level of token %#lx", token);
         return UnknownTrustLevel;
     }
References Tokens, Tasking::UnknownTrustLevel, and warn.
Referenced by CheckTrust().
IsTokenTrusted() [1/2]
bool Tasking::Security::IsTokenTrusted (Token token, int TrustLevel)
Definition at line 105 of file Security.cpp.
     {
         foreach (auto t in Tokens)
             if (t.token == token)
             {
                 if (t.TrustLevel & TrustLevel)
                     return true;
                 else
                     return false;
             }
         warn("Failed to check trust level of token %#lx", token);
         return false;
     }
References Tokens, and warn.
IsTokenTrusted() [2/2]
bool Tasking::Security::IsTokenTrusted (Token token, TTL TrustLevel)
Definition at line 90 of file Security.cpp.
     {
         foreach (auto t in Tokens)
             if (t.token == token)
             {
                 if (t.TrustLevel == TrustLevel)
                     return true;
                 else
                     return false;
             }
         warn("Failed to check trust level of token %#lx", token);
         return false;
     }
References Tokens, and warn.
Referenced by CheckTrust().
RemoveTrustLevel()
bool Tasking::Security::RemoveTrustLevel (Token token, TTL TrustLevel)
Definition at line 68 of file Security.cpp.
     {
         foreach (auto &t in Tokens)
         {
             if (t.token == token)
             {
                 t.TrustLevel &= ~TrustLevel;
                 debug("Removed trust level %d from token %#lx", t.TrustLevel, token);
                 return true;
             }
         }
         warn("Failed to remove trust level %d from token %#lx", TrustLevel, token);
         return false;
     }
References debug, Tokens, and warn.
TrustToken()
bool Tasking::Security::TrustToken (Token token, TTL TrustLevel)
Definition at line 23 of file Security.cpp.
     {
         foreach (auto &t in Tokens)
         {
             if (t.token == token)
             {
                 t.TrustLevel = TrustLevel;
                 debug("Trusted token %#lx to level %d", token, t.TrustLevel);
                 return true;
             }
         }
         warn("Failed to trust token %#lx", token);
         return false;
     }
References debug, Tokens, and warn.
Referenced by Tasking::Task::CreateThread(), and KernelMainThread().
UntrustToken()
bool Tasking::Security::UntrustToken (Token token)
Definition at line 38 of file Security.cpp.
     {
         foreach (auto &t in Tokens)
         {
             if (t.token == token)
             {
                 t.TrustLevel = Untrusted;
                 debug("Untrusted token %#lx", token);
                 return true;
             }
         }
         warn("Failed to untrust token %#lx", token);
         return false;
     }
References debug, Tokens, Tasking::Untrusted, and warn.
Field Documentation
Tokens
Vector<TokenData> Tasking::Security::Tokens private
Definition at line 206 of file task.hpp.
Referenced by AddTrustLevel(), CreateToken(), GetTokenTrustLevel(), IsTokenTrusted(), RemoveTrustLevel(), TrustToken(), UntrustToken(), and ~Security().
The documentation for this class was generated from the following files:
Kernel/include/task.hpp
Kernel/Tasking/Security.cpp