Fennix: __driverAPI Struct Reference
__driverAPI Struct Reference
#include <driver.h>
Data Fields
struct {
uint8_t Major
uint8_t Minor
uint8_t Patch
} APIVersion
dev_t MajorID
uintptr_t Base
int(* RegisterFunction)(dev_t MajorID, void *Function, __driverRegFunc Type)
int(* GetDriverInfo)(dev_t MajorID, const char *Name, const char *Description, const char *Author, const char *Version, const char *License)
int(* RegisterInterruptHandler)(dev_t MajorID, uint8_t IRQ, void *Handler)
int(* OverrideInterruptHandler)(dev_t MajorID, uint8_t IRQ, void *Handler)
int(* UnregisterInterruptHandler)(dev_t MajorID, uint8_t IRQ, void *Handler)
int(* UnregisterAllInterruptHandlers)(dev_t MajorID, void *Handler)
dev_t(* RegisterInputDevice)(dev_t MajorID, DeviceDriverType Type)
int(* UnregisterInputDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
int(* ReportKeyboardEvent)(dev_t MajorID, dev_t MinorID, uint8_t ScanCode)
int(* ReportRelativeMouseEvent)(dev_t MajorID, dev_t MinorID, __MouseButtons Button, int X, int Y, int8_t Z)
int(* ReportAbsoluteMouseEvent)(dev_t MajorID, dev_t MinorID, __MouseButtons Button, uintptr_t X, uintptr_t Y, int8_t Z)
dev_t(* RegisterBlockDevice)(dev_t MajorID, DeviceDriverType Type, void *Open, void *Close, void *Read, void *Write, void *Ioctl)
int(* UnregisterBlockDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
dev_t(* RegisterAudioDevice)(dev_t MajorID, DeviceDriverType Type, void *Open, void *Close, void *Read, void *Write, void *Ioctl)
int(* UnregisterAudioDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
dev_t(* RegisterNetDevice)(dev_t MajorID, DeviceDriverType Type, void *Open, void *Close, void *Read, void *Write, void *Ioctl)
int(* UnregisterNetDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
int(* ReportNetworkPacket)(dev_t MajorID, dev_t MinorID, void *Buffer, size_t Size)
void(* KPrint)(dev_t MajorID, const char *Format, va_list args)
void(* KernelLog)(dev_t MajorID, const char *Format, va_list args)
void *(* RequestPages)(dev_t MajorID, size_t Pages)
void(* FreePages)(dev_t MajorID, void *Pointer, size_t Pages)
void(* AppendMapFlag)(dev_t MajorID, void *Address, PageMapFlags Flag)
void(* RemoveMapFlag)(dev_t MajorID, void *Address, PageMapFlags Flag)
void(* MapPages)(dev_t MajorID, void *PhysicalAddress, void *VirtualAddress, size_t Pages, uint32_t Flags)
void(* UnmapPages)(dev_t MajorID, void *VirtualAddress, size_t Pages)
pid_t(* CreateKernelProcess)(dev_t MajorID, const char *Name)
pid_t(* CreateKernelThread)(dev_t MajorID, pid_t pId, const char *Name, void *EntryPoint, void *Argument)
int(* KillProcess)(dev_t MajorID, pid_t pId, int ExitCode)
int(* KillThread)(dev_t MajorID, pid_t tId, int ExitCode)
void(* Yield)(dev_t MajorID)
void(* Sleep)(dev_t MajorID, uint64_t Milliseconds)
__PCIArray *(* GetPCIDevices)(dev_t MajorID, uint16_t Vendors[], uint16_t Devices[])
void(* InitializePCI)(dev_t MajorID, void *Header)
uint32_t(* GetBAR)(dev_t MajorID, uint8_t Index, void *Header)
void *(* memcpy)(dev_t MajorID, void *Destination, const void *Source, size_t Length)
void *(* memset)(dev_t MajorID, void *Destination, int Value, size_t Length)
void *(* memmove)(dev_t MajorID, void *Destination, const void *Source, size_t Length)
int(* memcmp)(dev_t MajorID, const void *Left, const void *Right, size_t Length)
size_t(* strlen)(dev_t MajorID, const char *String)
char *(* strcpy)(dev_t MajorID, char *Destination, const char *Source)
char *(* strcat)(dev_t MajorID, char *Destination, const char *Source)
int(* strcmp)(dev_t MajorID, const char *Left, const char *Right)
int(* strncmp)(dev_t MajorID, const char *Left, const char *Right, size_t Length)
char *(* strchr)(dev_t MajorID, const char *String, int Character)
char *(* strrchr)(dev_t MajorID, const char *String, int Character)
char *(* strstr)(dev_t MajorID, const char *Haystack, const char *Needle)
struct {
uint8_t Major
uint8_t Minor
uint8_t Patch
} APIVersion
Detailed Description
Definition at line 242 of file driver.h.
Field Documentation
[1/2]
struct { ... } __driverAPI::APIVersion
[2/2]
struct { ... } __driverAPI::APIVersion
Referenced by _start(), and Driver::Manager::LoadAllDrivers().
AppendMapFlag
void(* __driverAPI::AppendMapFlag)(dev_t MajorID, void *Address, PageMapFlags Flag)
Definition at line 293 of file driver.h.
Referenced by AppendMapFlag(), and Driver::PopulateDriverAPI().
Base
uintptr_t __driverAPI::Base
Definition at line 252 of file driver.h.
Referenced by Driver::Manager::LoadAllDrivers().
CreateKernelProcess
pid_t(* __driverAPI::CreateKernelProcess)(dev_t MajorID, const char *Name)
Definition at line 299 of file driver.h.
Referenced by CreateKernelProcess(), and Driver::PopulateDriverAPI().
CreateKernelThread
pid_t(* __driverAPI::CreateKernelThread)(dev_t MajorID, pid_t pId, const char *Name, void *EntryPoint, void *Argument)
Definition at line 300 of file driver.h.
Referenced by CreateKernelThread(), and Driver::PopulateDriverAPI().
FreePages
void(* __driverAPI::FreePages)(dev_t MajorID, void *Pointer, size_t Pages)
Definition at line 290 of file driver.h.
Referenced by __delete_alloc_page(), FreeMemory(), and Driver::PopulateDriverAPI().
GetBAR
uint32_t(* __driverAPI::GetBAR)(dev_t MajorID, uint8_t Index, void *Header)
Definition at line 309 of file driver.h.
Referenced by GetBAR(), and Driver::PopulateDriverAPI().
GetDriverInfo
int(* __driverAPI::GetDriverInfo)(dev_t MajorID, const char *Name, const char *Description, const char *Author, const char *Version, const char *License)
Definition at line 256 of file driver.h.
Referenced by _start(), and Driver::PopulateDriverAPI().
GetPCIDevices
__PCIArray *(* __driverAPI::GetPCIDevices)(dev_t MajorID, uint16_t Vendors[], uint16_t Devices[])
Definition at line 307 of file driver.h.
Referenced by FindPCIDevices(), and Driver::PopulateDriverAPI().
InitializePCI
void(* __driverAPI::InitializePCI)(dev_t MajorID, void *Header)
Definition at line 308 of file driver.h.
Referenced by InitializePCI(), and Driver::PopulateDriverAPI().
KernelLog
void(* __driverAPI::KernelLog)(dev_t MajorID, const char *Format, va_list args)
Definition at line 286 of file driver.h.
Referenced by Log(), and Driver::PopulateDriverAPI().
KillProcess
int(* __driverAPI::KillProcess)(dev_t MajorID, pid_t pId, int ExitCode)
Definition at line 301 of file driver.h.
Referenced by KillProcess(), and Driver::PopulateDriverAPI().
KillThread
int(* __driverAPI::KillThread)(dev_t MajorID, pid_t tId, int ExitCode)
Definition at line 302 of file driver.h.
Referenced by KillThread(), and Driver::PopulateDriverAPI().
KPrint
void(* __driverAPI::KPrint)(dev_t MajorID, const char *Format, va_list args)
Definition at line 285 of file driver.h.
Referenced by KPrint(), and Driver::PopulateDriverAPI().
MajorID
dev_t __driverAPI::MajorID
Definition at line 251 of file driver.h.
Referenced by __delete_alloc_page(), __new_alloc_page(), _start(), AllocateMemory(), AppendMapFlag(), CreateKernelProcess(), CreateKernelThread(), FindPCIDevices(), FreeMemory(), GetBAR(), InitializePCI(), KillProcess(), KillThread(), KPrint(), Driver::Manager::LoadAllDrivers(), Log(), MapPages(), MemoryCopy(), MemoryMove(), MemorySet(), OverrideInterruptHandler(), RegisterAudioDevice(), RegisterBlockDevice(), RegisterInputDevice(), RegisterInterruptHandler(), RegisterNetDevice(), RemoveMapFlag(), ReportAbsoluteMouseEvent(), ReportKeyboardEvent(), ReportNetworkPacket(), ReportRelativeMouseEvent(), Sleep(), StringLength(), strstr(), UnmapPages(), UnregisterAllInterruptHandlers(), UnregisterAudioDevice(), UnregisterBlockDevice(), UnregisterInputDevice(), UnregisterInterruptHandler(), UnregisterNetDevice(), and Yield().
MapPages
void(* __driverAPI::MapPages)(dev_t MajorID, void *PhysicalAddress, void *VirtualAddress, size_t Pages, uint32_t Flags)
Definition at line 295 of file driver.h.
Referenced by MapPages(), and Driver::PopulateDriverAPI().
memcmp
int(* __driverAPI::memcmp)(dev_t MajorID, const void *Left, const void *Right, size_t Length)
Definition at line 315 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
memcpy
void *(* __driverAPI::memcpy)(dev_t MajorID, void *Destination, const void *Source, size_t Length)
Definition at line 312 of file driver.h.
Referenced by MemoryCopy(), and Driver::PopulateDriverAPI().
memmove
void *(* __driverAPI::memmove)(dev_t MajorID, void *Destination, const void *Source, size_t Length)
Definition at line 314 of file driver.h.
Referenced by MemoryMove(), and Driver::PopulateDriverAPI().
memset
void *(* __driverAPI::memset)(dev_t MajorID, void *Destination, int Value, size_t Length)
Definition at line 313 of file driver.h.
Referenced by MemorySet(), and Driver::PopulateDriverAPI().
OverrideInterruptHandler
int(* __driverAPI::OverrideInterruptHandler)(dev_t MajorID, uint8_t IRQ, void *Handler)
Definition at line 260 of file driver.h.
Referenced by OverrideInterruptHandler(), and Driver::PopulateDriverAPI().
RegisterAudioDevice
dev_t(* __driverAPI::RegisterAudioDevice)(dev_t MajorID, DeviceDriverType Type, void *Open, void *Close, void *Read, void *Write, void *Ioctl)
Definition at line 276 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and RegisterAudioDevice().
RegisterBlockDevice
dev_t(* __driverAPI::RegisterBlockDevice)(dev_t MajorID, DeviceDriverType Type, void *Open, void *Close, void *Read, void *Write, void *Ioctl)
Definition at line 272 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and RegisterBlockDevice().
RegisterFunction
int(* __driverAPI::RegisterFunction)(dev_t MajorID, void *Function, __driverRegFunc Type)
Definition at line 255 of file driver.h.
Referenced by _start(), and Driver::PopulateDriverAPI().
RegisterInputDevice
dev_t(* __driverAPI::RegisterInputDevice)(dev_t MajorID, DeviceDriverType Type)
Definition at line 265 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and RegisterInputDevice().
RegisterInterruptHandler
int(* __driverAPI::RegisterInterruptHandler)(dev_t MajorID, uint8_t IRQ, void *Handler)
Definition at line 259 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and RegisterInterruptHandler().
RegisterNetDevice
dev_t(* __driverAPI::RegisterNetDevice)(dev_t MajorID, DeviceDriverType Type, void *Open, void *Close, void *Read, void *Write, void *Ioctl)
Definition at line 280 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and RegisterNetDevice().
RemoveMapFlag
void(* __driverAPI::RemoveMapFlag)(dev_t MajorID, void *Address, PageMapFlags Flag)
Definition at line 294 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and RemoveMapFlag().
ReportAbsoluteMouseEvent
int(* __driverAPI::ReportAbsoluteMouseEvent)(dev_t MajorID, dev_t MinorID, __MouseButtons Button, uintptr_t X, uintptr_t Y, int8_t Z)
Definition at line 269 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and ReportAbsoluteMouseEvent().
ReportKeyboardEvent
int(* __driverAPI::ReportKeyboardEvent)(dev_t MajorID, dev_t MinorID, uint8_t ScanCode)
Definition at line 267 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and ReportKeyboardEvent().
ReportNetworkPacket
int(* __driverAPI::ReportNetworkPacket)(dev_t MajorID, dev_t MinorID, void *Buffer, size_t Size)
Definition at line 282 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and ReportNetworkPacket().
ReportRelativeMouseEvent
int(* __driverAPI::ReportRelativeMouseEvent)(dev_t MajorID, dev_t MinorID, __MouseButtons Button, int X, int Y, int8_t Z)
Definition at line 268 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and ReportRelativeMouseEvent().
RequestPages
void *(* __driverAPI::RequestPages)(dev_t MajorID, size_t Pages)
Definition at line 289 of file driver.h.
Referenced by __new_alloc_page(), AllocateMemory(), and Driver::PopulateDriverAPI().
Sleep
void(* __driverAPI::Sleep)(dev_t MajorID, uint64_t Milliseconds)
Definition at line 304 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and Sleep().
strcat
char *(* __driverAPI::strcat)(dev_t MajorID, char *Destination, const char *Source)
Definition at line 318 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
strchr
char *(* __driverAPI::strchr)(dev_t MajorID, const char *String, int Character)
Definition at line 321 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
strcmp
int(* __driverAPI::strcmp)(dev_t MajorID, const char *Left, const char *Right)
Definition at line 319 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
strcpy
char *(* __driverAPI::strcpy)(dev_t MajorID, char *Destination, const char *Source)
Definition at line 317 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
strlen
size_t(* __driverAPI::strlen)(dev_t MajorID, const char *String)
Definition at line 316 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and StringLength().
strncmp
int(* __driverAPI::strncmp)(dev_t MajorID, const char *Left, const char *Right, size_t Length)
Definition at line 320 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
strrchr
char *(* __driverAPI::strrchr)(dev_t MajorID, const char *String, int Character)
Definition at line 322 of file driver.h.
Referenced by Driver::PopulateDriverAPI().
strstr
char *(* __driverAPI::strstr)(dev_t MajorID, const char *Haystack, const char *Needle)
Definition at line 323 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and strstr().
UnmapPages
void(* __driverAPI::UnmapPages)(dev_t MajorID, void *VirtualAddress, size_t Pages)
Definition at line 296 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnmapPages().
UnregisterAllInterruptHandlers
int(* __driverAPI::UnregisterAllInterruptHandlers)(dev_t MajorID, void *Handler)
Definition at line 262 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnregisterAllInterruptHandlers().
UnregisterAudioDevice
int(* __driverAPI::UnregisterAudioDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
Definition at line 277 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnregisterAudioDevice().
UnregisterBlockDevice
int(* __driverAPI::UnregisterBlockDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
Definition at line 273 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnregisterBlockDevice().
UnregisterInputDevice
int(* __driverAPI::UnregisterInputDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
Definition at line 266 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnregisterInputDevice().
UnregisterInterruptHandler
int(* __driverAPI::UnregisterInterruptHandler)(dev_t MajorID, uint8_t IRQ, void *Handler)
Definition at line 261 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnregisterInterruptHandler().
UnregisterNetDevice
int(* __driverAPI::UnregisterNetDevice)(dev_t MajorID, dev_t MinorID, DeviceDriverType Type)
Definition at line 281 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and UnregisterNetDevice().
Yield
void(* __driverAPI::Yield)(dev_t MajorID)
Definition at line 303 of file driver.h.
Referenced by Driver::PopulateDriverAPI(), and Yield().
The documentation for this struct was generated from the following file:
Kernel/driver.h