Fennix: Userspace/musl/src/time/__map_file.c File Reference
__map_file.c File Reference
#include <sys/mman.h>
#include <fcntl.h>
#include <sys/stat.h>
#include "syscall.h"
Functions
const char unsigned * __map_file (const char *pathname, size_t *size)
Function Documentation
__map_file()
const char unsigned* __map_file (const char * pathname, size_t * size)
Definition at line 6 of file __map_file.c.
 {
     struct stat st;
     const unsigned char *map = MAP_FAILED;
     int fd = sys_open(pathname, O_RDONLY|O_CLOEXEC|O_NONBLOCK);
     if (fd < 0) return 0;
     if (!__fstat(fd, &st)) {
         map = __mmap(0, st.st_size, PROT_READ, MAP_SHARED, fd, 0);
         *size = st.st_size;
     }
     __syscall(SYS_close, fd);
     return map == MAP_FAILED ? 0 : map;
 }
References __fstat(), __mmap(), __syscall, fd, map, MAP_FAILED, MAP_SHARED, O_CLOEXEC, O_NONBLOCK, O_RDONLY, PROT_READ, size, and sys_open.
Referenced by __get_locale(), dcngettext(), do_catopen(), and do_tzset().