Fennix: Userspace/apps/base/bash/lib/readline/input.c File Reference
input.c File Reference
#include <sys/types.h>
#include <fcntl.h>
#include "ansi_stdlib.h"
#include <signal.h>
#include "posixselect.h"
#include "posixtime.h"
#include <stdio.h>
#include <errno.h>
#include "rldefs.h"
#include "rlmbutil.h"
#include "readline.h"
#include "rlprivate.h"
#include "rlshell.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define RL_TIMEOUT_USE_SIGALRM
#define any_typein (push_index != pop_index)
#define X_EWOULDBLOCK -99
#define X_EAGAIN -99
Functions
static int ibuffer_space (void)
static int rl_get_char (int *)
static int rl_gather_tyi (void)
int rl_set_timeout (unsigned int, unsigned int)
int rl_timeout_remaining (unsigned int *, unsigned int *)
int _rl_timeout_init (void)
int _rl_timeout_sigalrm_handler (void)
int _rl_timeout_select (int, fd_set *, fd_set *, fd_set *, const struct timeval *, const sigset_t *)
static void _rl_timeout_handle (void)
static int set_alarm (unsigned int *, unsigned int *)
static void reset_alarm (void)
int _rl_any_typein (void)
int _rl_pushed_input_available (void)
int _rl_unget_char (int key)
int rl_set_keyboard_input_timeout (int u)
int _rl_input_available (void)
int _rl_nchars_available ()
int _rl_input_queued (int t)
void _rl_insert_typein (int c)
int rl_stuff_char (int key)
int rl_execute_next (int c)
int rl_clear_pending_input (void)
int _rl_timeout_handle_sigalrm ()
int rl_read_key (void)
int rl_getc (FILE *stream)
Variables
int errno
rl_hook_func_t * rl_event_hook = (rl_hook_func_t *)NULL
rl_hook_func_t * rl_signal_event_hook = (rl_hook_func_t *)NULL
rl_hook_func_t * rl_timeout_event_hook = (rl_hook_func_t *)NULL
rl_hook_func_t * rl_input_available_hook = (rl_hook_func_t *)NULL
rl_getc_func_t * rl_getc_function = rl_getc
static int _keyboard_input_timeout = 100000
static struct timeval timeout_point
static struct timeval timeout_duration
static int pop_index
static int push_index
static unsigned char ibuffer [512]
static int ibuffer_len = sizeof (ibuffer) - 1
Macro Definition Documentation
any_typein
#define any_typein (push_index != pop_index)
Definition at line 179 of file input.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file input.c.
RL_TIMEOUT_USE_SIGALRM
#define RL_TIMEOUT_USE_SIGALRM
Definition at line 146 of file input.c.
X_EAGAIN
#define X_EAGAIN -99
X_EWOULDBLOCK
#define X_EWOULDBLOCK -99
Function Documentation
_rl_any_typein()
int _rl_any_typein (void)
Definition at line 182 of file input.c.
 {
   return any_typein;
 }
References any_typein.
_rl_input_available()
int _rl_input_available (void)
Definition at line 369 of file input.c.
 {
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
   fd_set readfds, exceptfds;
   struct timeval timeout;
 #endif
 #if !defined (HAVE_SELECT) && defined (FIONREAD)
   int chars_avail;
 #endif
   int tty;
   if (rl_input_available_hook)
     return (*rl_input_available_hook) ();
   tty = fileno (rl_instream);
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
   FD_ZERO (&readfds);
   FD_ZERO (&exceptfds);
   FD_SET (tty, &readfds);
   FD_SET (tty, &exceptfds);
   USEC_TO_TIMEVAL (_keyboard_input_timeout, timeout);
 #  if defined (RL_TIMEOUT_USE_SELECT)
   return (_rl_timeout_select (tty + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout, NULL) > 0);
 #  else
   return (select (tty + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout) > 0);
 #  endif
 #else
 #if defined (FIONREAD)
   if (ioctl (tty, FIONREAD, &chars_avail) == 0)
     return (chars_avail);
 #endif
 #endif
 #if defined (__MINGW32__)
   if (isatty (tty))
     return (_kbhit ());
 #endif
   return 0;
 }
References _keyboard_input_timeout, _rl_timeout_select(), FD_SET, FD_ZERO, fileno(), FIONREAD, ioctl(), isatty(), NULL, rl_input_available_hook, rl_instream, select(), timeout(), and USEC_TO_TIMEVAL.
Referenced by _rl_input_queued(), and _rl_isearch_dispatch().
_rl_input_queued()
int _rl_input_queued (int t)
Definition at line 432 of file input.c.
 {
   int old_timeout, r;
   old_timeout = rl_set_keyboard_input_timeout (t);
   r = _rl_input_available ();
   rl_set_keyboard_input_timeout (old_timeout);
   return r;
 }
References _rl_input_available(), rl_set_keyboard_input_timeout(), and t.
Referenced by _rl_dispatch_subseq(), _rl_isearch_dispatch(), _rl_read_bracketed_paste_prefix(), and rl_insert().
_rl_insert_typein()
void _rl_insert_typein (int c)
Definition at line 443 of file input.c.
 {
   int key, t, i;
   char *string;
   i = key = 0;
   string = (char *)xmalloc (ibuffer_len + 1);
   string[i++] = (char) c;
   while ((t = rl_get_char (&key)) &&
      _rl_keymap[key].type == ISFUNC &&
      _rl_keymap[key].function == rl_insert)
     string[i++] = key;
   if (t)
     _rl_unget_char (key);
   string[i] = '\0';
   rl_insert_text (string);
   xfree (string);
 }
References _rl_keymap, _rl_unget_char(), c, i, ibuffer_len, ISFUNC, rl_get_char(), rl_insert(), rl_insert_text(), string, t, type, xfree, and xmalloc.
Referenced by _rl_insert_char().
_rl_nchars_available()
int _rl_nchars_available (void)
Definition at line 414 of file input.c.
 {
   int chars_avail, fd, result;
   chars_avail = 0;
 #if defined (FIONREAD)
   fd = fileno (rl_instream);
   errno = 0;
   result = ioctl (fd, FIONREAD, &chars_avail);
   if (result == -1 && errno == EIO)
     return -1;
 #endif
   return chars_avail;
 }
References EIO, errno, fd, fileno(), FIONREAD, ioctl(), and rl_instream.
Referenced by _rl_isearch_dispatch(), and _rl_nsearch_dispatch().
_rl_pushed_input_available()
int _rl_pushed_input_available (void)
Definition at line 188 of file input.c.
 {
   return (push_index != pop_index);
 }
References pop_index, and push_index.
Referenced by _rl_dispatch_subseq(), _rl_insert_char(), _rl_isearch_dispatch(), _rl_read_bracketed_paste_prefix(), rl_callback_read_char(), rl_insert(), and rl_vi_overstrike_bracketed_paste().
_rl_timeout_handle()
static void _rl_timeout_handle (void) static
Definition at line 717 of file input.c.
 {
   if (rl_timeout_event_hook)
     (*rl_timeout_event_hook) ();
   RL_SETSTATE(RL_STATE_TIMEOUT);
   _rl_abort_internal ();
 }
References _rl_abort_internal(), RL_SETSTATE, RL_STATE_TIMEOUT, and rl_timeout_event_hook.
Referenced by _rl_timeout_handle_sigalrm(), and rl_getc().
_rl_timeout_handle_sigalrm()
int _rl_timeout_handle_sigalrm (void)
Definition at line 727 of file input.c.
 {
 #if defined (RL_TIMEOUT_USE_SIGALRM)
   if (timerisunset (&timeout_point))
     return -1;
   /* Reset `timeout_point' to the current time to ensure that later
      calls of `rl_timeout_pending ()' return 0 (timeout expired). */
   if (gettimeofday(&timeout_point, 0) != 0)
     timerclear (&timeout_point);
   reset_alarm ();
   _rl_timeout_handle ();
 #endif
   return -1;
 }
References _rl_timeout_handle(), gettimeofday(), reset_alarm(), timeout_point, timerclear, and timerisunset.
Referenced by _rl_handle_signal().
_rl_timeout_init()
int _rl_timeout_init (void)
Definition at line 568 of file input.c.
 {
   unsigned int secs, usecs;
   /* Clear the timeout state of the previous edit */
   RL_UNSETSTATE(RL_STATE_TIMEOUT);
   timerclear (&timeout_point);
   /* Return 0 when timeout is unset. */
   if (timerisunset (&timeout_duration))
     return 0;
   /* Return -1 on gettimeofday error. */
   if (gettimeofday(&timeout_point, 0) != 0)
     {
       timerclear (&timeout_point);
       return -1;
     }
   secs = timeout_duration.tv_sec;
   usecs = timeout_duration.tv_usec;
 #if defined (RL_TIMEOUT_USE_SIGALRM)
   /* If select(2)/pselect(2) is unavailable, use SIGALRM. */
   if (set_alarm (&secs, &usecs) < 0)
     return -1;
 #endif
   timeout_point.tv_sec += secs;
   timeout_point.tv_usec += usecs;
   if (timeout_point.tv_usec >= USEC_PER_SEC)
     {
       timeout_point.tv_sec++;
       timeout_point.tv_usec -= USEC_PER_SEC;
     }
   return 0;
 }
References gettimeofday(), RL_STATE_TIMEOUT, RL_UNSETSTATE, set_alarm(), timeout_duration, timeout_point, timerclear, timerisunset, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
Referenced by rl_initialize().
_rl_timeout_select()
int _rl_timeout_select (int , fd_set * , fd_set * , fd_set * , const struct timeval * , const sigset_t *)
Referenced by _rl_input_available(), rl_gather_tyi(), rl_getc(), and rl_insert_close().
_rl_timeout_sigalrm_handler()
int _rl_timeout_sigalrm_handler (void)
_rl_unget_char()
int _rl_unget_char (int key)
Definition at line 228 of file input.c.
 {
   if (ibuffer_space ())
     {
       pop_index--;
       if (pop_index < 0)
     pop_index = ibuffer_len;
       ibuffer[pop_index] = key;
       return (1);
     }
   return (0);
 }
References ibuffer, ibuffer_len, ibuffer_space(), and pop_index.
Referenced by _rl_bracketed_read_key(), _rl_dispatch_subseq(), _rl_insert_typein(), _rl_read_bracketed_paste_prefix(), _rl_subseq_result(), and rl_vi_overstrike_bracketed_paste().
ibuffer_space()
static int ibuffer_space (void) static
Definition at line 196 of file input.c.
 {
   if (pop_index > push_index)
     return (pop_index - push_index - 1);
   else
     return (ibuffer_len - (push_index - pop_index));
 }
References ibuffer_len, pop_index, and push_index.
Referenced by _rl_unget_char(), rl_gather_tyi(), and rl_stuff_char().
reset_alarm()
static void reset_alarm (void) static
Definition at line 547 of file input.c.
 {
   alarm (0);
 }
References alarm().
Referenced by _rl_timeout_handle_sigalrm().
rl_clear_pending_input()
int rl_clear_pending_input (void)
Definition at line 501 of file input.c.
 {
   rl_pending_input = 0;
   RL_UNSETSTATE (RL_STATE_INPUTPENDING);
   return 0;
 }
References rl_pending_input, RL_STATE_INPUTPENDING, and RL_UNSETSTATE.
Referenced by _rl_abort_internal(), readline(), rl_cleanup_after_signal(), and rl_read_key().
rl_execute_next()
int rl_execute_next (int c)
Definition at line 492 of file input.c.
 {
   rl_pending_input = c;
   RL_SETSTATE (RL_STATE_INPUTPENDING);
   return 0;
 }
References c, rl_pending_input, RL_SETSTATE, and RL_STATE_INPUTPENDING.
Referenced by _rl_arg_callback(), _rl_isearch_dispatch(), rl_digit_argument(), and rl_insert().
rl_gather_tyi()
static int rl_gather_tyi (void) static
Definition at line 245 of file input.c.
 {
   int tty;
   register int tem, result;
   int chars_avail, k;
   char input;
 #if defined(HAVE_SELECT)
   fd_set readfds, exceptfds;
   struct timeval timeout;
 #endif
   chars_avail = 0;
   input = 0;
   tty = fileno (rl_instream);
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
   FD_ZERO (&readfds);
   FD_ZERO (&exceptfds);
   FD_SET (tty, &readfds);
   FD_SET (tty, &exceptfds);
   USEC_TO_TIMEVAL (_keyboard_input_timeout, timeout);
 #if defined (RL_TIMEOUT_USE_SELECT)
   result = _rl_timeout_select (tty + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout, NULL);
 #else
   result = select (tty + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout);
 #endif
   if (result <= 0)
     return 0;   /* Nothing to read. */
 #endif
   result = -1;
   errno = 0;
 #if defined (FIONREAD)
   result = ioctl (tty, FIONREAD, &chars_avail);
   if (result == -1 && errno == EIO)
     return -1;
   if (result == -1)
     chars_avail = 0;
 #endif
 #if defined (O_NDELAY)
   if (result == -1)
     {
       tem = fcntl (tty, F_GETFL, 0);
       fcntl (tty, F_SETFL, (tem | O_NDELAY));
       chars_avail = read (tty, &input, 1);
       fcntl (tty, F_SETFL, tem);
       if (chars_avail == -1 && errno == EAGAIN)
     return 0;
       if (chars_avail == -1 && errno == EIO)
     return -1;
       if (chars_avail == 0) /* EOF */
     {
       rl_stuff_char (EOF);
       return (0);
     }
     }
 #endif /* O_NDELAY */
 #if defined (__MINGW32__)
   /* Use getch/_kbhit to check for available console input, in the same way
      that we read it normally. */
    chars_avail = isatty (tty) ? _kbhit () : 0;
    result = 0;
 #endif
   /* If there's nothing available, don't waste time trying to read
      something. */
   if (chars_avail <= 0)
     return 0;
   tem = ibuffer_space ();
   if (chars_avail > tem)
     chars_avail = tem;
   /* One cannot read all of the available input.  I can only read a single
      character at a time, or else programs which require input can be
      thwarted.  If the buffer is larger than one character, I lose.
      Damn! */
   if (tem < ibuffer_len)
     chars_avail = 0;
   if (result != -1)
     {
       while (chars_avail--)
     {
       RL_CHECK_SIGNALS ();
       k = (*rl_getc_function) (rl_instream);
       if (rl_stuff_char (k) == 0)
         break;          /* some problem; no more room */
       if (k == NEWLINE || k == RETURN)
         break;
     }
     }
   else
     {
       if (chars_avail)
     rl_stuff_char (input);
     }
   return 1;
 }
References _keyboard_input_timeout, _rl_timeout_select(), EAGAIN, EIO, EOF, errno, F_GETFL, F_SETFL, fcntl(), FD_SET, FD_ZERO, fileno(), FIONREAD, ibuffer_len, ibuffer_space(), input, ioctl(), isatty(), k, NEWLINE, NULL, O_NDELAY, read(), RETURN, RL_CHECK_SIGNALS, rl_instream, rl_stuff_char(), select(), timeout(), and USEC_TO_TIMEVAL.
Referenced by rl_read_key().
rl_get_char()
static int rl_get_char (int * key) static
Definition at line 208 of file input.c.
 {
   if (push_index == pop_index)
     return (0);
   *key = ibuffer[pop_index++];
 #if 0
   if (pop_index >= ibuffer_len)
 #else
   if (pop_index > ibuffer_len)
 #endif
     pop_index = 0;
   return (1);
 }
References ibuffer, ibuffer_len, pop_index, and push_index.
Referenced by _rl_insert_typein(), and rl_read_key().
rl_getc()
int rl_getc (FILE * stream)
Definition at line 803 of file input.c.
 {
   int result;
   unsigned char c;
   int fd;
 #if defined (HAVE_PSELECT)
   sigset_t empty_set;
   fd_set readfds;
 #endif
   fd = fileno (stream);
   while (1)
     {
       RL_CHECK_SIGNALS ();
       /* We know at this point that _rl_caught_signal == 0 */
 #if defined (__MINGW32__)
       if (isatty (fd)
     return (_getch ()); /* "There is no error return." */
 #endif
       result = 0;
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
       /* At this point, if we have pselect, we're using select/pselect for the
      timeouts. We handled MinGW above. */
       FD_ZERO (&readfds);
       FD_SET (fd, &readfds);
 #  if defined (HANDLE_SIGNALS)
       result = _rl_timeout_select (fd + 1, &readfds, NULL, NULL, NULL, &_rl_orig_sigset);
 #  else
       sigemptyset (&empty_set);
       sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &empty_set);
       result = _rl_timeout_select (fd + 1, &readfds, NULL, NULL, NULL, &empty_set);
 #  endif /* HANDLE_SIGNALS */
       if (result == 0)
         _rl_timeout_handle ();      /* check the timeout */
 #endif
       if (result >= 0)
     result = read (fd, &c, sizeof (unsigned char));
       if (result == sizeof (unsigned char))
     return (c);
       /* If zero characters are returned, then the file that we are
      reading from is empty!  Return EOF in that case. */
       if (result == 0)
     return (EOF);
 #if defined (__BEOS__)
       if (errno == EINTR)
     continue;
 #endif
 #if defined (EWOULDBLOCK)
 #  define X_EWOULDBLOCK EWOULDBLOCK
 #else
 #  define X_EWOULDBLOCK -99
 #endif
 #if defined (EAGAIN)
 #  define X_EAGAIN EAGAIN
 #else
 #  define X_EAGAIN -99
 #endif
       if (errno == X_EWOULDBLOCK || errno == X_EAGAIN)
     {
       if (sh_unset_nodelay_mode (fd) < 0)
         return (EOF);
       continue;
     }
 #undef X_EWOULDBLOCK
 #undef X_EAGAIN
 /* fprintf(stderr, "rl_getc: result = %d errno = %d\n", result, errno); */
 handle_error:
       /* If the error that we received was EINTR, then try again,
      this is simply an interrupted system call to read ().  We allow
      the read to be interrupted if we caught SIGHUP, SIGTERM, or any
      of the other signals readline treats specially. If the
      application sets an event hook, call it for other signals.
      Otherwise (not EINTR), some error occurred, also signifying EOF. */
       if (errno != EINTR)
     return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
       /* fatal signals of interest */
 #if defined (SIGHUP)
       else if (_rl_caught_signal == SIGHUP || _rl_caught_signal == SIGTERM)
 #else
       else if (_rl_caught_signal == SIGTERM)
 #endif
     return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
       /* keyboard-generated signals of interest */
 #if defined (SIGQUIT)
       else if (_rl_caught_signal == SIGINT || _rl_caught_signal == SIGQUIT)
 #else
       else if (_rl_caught_signal == SIGINT)
 #endif
         RL_CHECK_SIGNALS ();
 #if defined (SIGTSTP)
       else if (_rl_caught_signal == SIGTSTP)
     RL_CHECK_SIGNALS ();
 #endif
       /* non-keyboard-generated signals of interest */
 #if defined (SIGWINCH)
       else if (_rl_caught_signal == SIGWINCH)
     RL_CHECK_SIGNALS ();
 #endif /* SIGWINCH */
 #if defined (SIGALRM)
       else if (_rl_caught_signal == SIGALRM
 #  if defined (SIGVTALRM)
         || _rl_caught_signal == SIGVTALRM
 #  endif
           )
         RL_CHECK_SIGNALS ();
 #endif  /* SIGALRM */
       if (rl_signal_event_hook)
     (*rl_signal_event_hook) ();
     }
 }
References _rl_caught_signal, _rl_timeout_handle(), _rl_timeout_select(), c, EINTR, EOF, errno, fd, FD_SET, FD_ZERO, fileno(), isatty(), NULL, read(), READERR, RL_CHECK_SIGNALS, RL_ISSTATE, rl_signal_event_hook, RL_STATE_READCMD, sh_unset_nodelay_mode(), SIG_BLOCK, SIGALRM, sigemptyset(), SIGHUP, SIGINT, sigprocmask(), SIGQUIT, SIGTERM, SIGTSTP, SIGVTALRM, SIGWINCH, X_EAGAIN, and X_EWOULDBLOCK.
rl_read_key()
int rl_read_key (void)
Definition at line 752 of file input.c.
 {
   int c, r;
   if (rl_pending_input)
     {
       c = rl_pending_input; /* XXX - cast to unsigned char if > 0? */
       rl_clear_pending_input ();
     }
   else
     {
       /* If input is coming from a macro, then use that. */
       if (c = _rl_next_macro_key ())
     return ((unsigned char)c);
       /* If the user has an event function, then call it periodically. */
       if (rl_event_hook)
     {
       while (rl_event_hook)
         {
           if (rl_get_char (&c) != 0)
         break;
           if ((r = rl_gather_tyi ()) < 0)   /* XXX - EIO */
         {
           rl_done = 1;
           RL_SETSTATE (RL_STATE_DONE);
           return (errno == EIO ? (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF) : '\n');
         }
           else if (r > 0)           /* read something */
         continue;
           RL_CHECK_SIGNALS ();
           if (rl_done)      /* XXX - experimental */
         return ('\n');
           (*rl_event_hook) ();
         }
     }
       else
     {
       if (rl_get_char (&c) == 0)
         c = (*rl_getc_function) (rl_instream);
 /* fprintf(stderr, "rl_read_key: calling RL_CHECK_SIGNALS: _rl_caught_signal = %d\r\n", _rl_caught_signal); */
       RL_CHECK_SIGNALS ();
     }
     }
   return (c);
 }
References _rl_next_macro_key(), c, EIO, EOF, errno, READERR, RL_CHECK_SIGNALS, rl_clear_pending_input(), rl_done, rl_event_hook, rl_gather_tyi(), rl_get_char(), rl_getc_function, rl_instream, RL_ISSTATE, rl_pending_input, RL_SETSTATE, RL_STATE_DONE, and RL_STATE_READCMD.
Referenced by _rl_arg_getchar(), _rl_bracketed_read_key(), _rl_bracketed_text(), _rl_insert_next(), _rl_isearch_dispatch(), _rl_nsearch_dispatch(), _rl_read_bracketed_paste_prefix(), _rl_search_getchar(), _rl_subseq_getchar(), _rl_vi_callback_char_search(), _rl_vi_goto_mark(), _rl_vi_set_mark(), get_y_or_n(), readline_internal_char(), rl_arrow_keys(), rl_insert(), rl_skip_csi_sequence(), rl_vi_char_search(), and rl_vi_overstrike_bracketed_paste().
rl_set_keyboard_input_timeout()
int rl_set_keyboard_input_timeout (int u)
Definition at line 352 of file input.c.
 {
   int o;
   o = _keyboard_input_timeout;
   if (u >= 0)
     _keyboard_input_timeout = u;
   return (o);
 }
References _keyboard_input_timeout.
Referenced by _rl_input_queued().
rl_set_timeout()
int rl_set_timeout (unsigned int secs, unsigned int usecs)
Definition at line 557 of file input.c.
 {
   timeout_duration.tv_sec = secs + usecs / USEC_PER_SEC;
   timeout_duration.tv_usec = usecs % USEC_PER_SEC;
   return 0;
 }
References timeout_duration, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
rl_stuff_char()
int rl_stuff_char (int key)
Definition at line 468 of file input.c.
 {
   if (ibuffer_space () == 0)
     return 0;
   if (key == EOF)
     {
       key = NEWLINE;
       rl_pending_input = EOF;
       RL_SETSTATE (RL_STATE_INPUTPENDING);
     }
   ibuffer[push_index++] = key;
 #if 0
   if (push_index >= ibuffer_len)
 #else
   if (push_index > ibuffer_len)
 #endif
     push_index = 0;
   return 1;
 }
References EOF, ibuffer, ibuffer_len, ibuffer_space(), NEWLINE, push_index, rl_pending_input, RL_SETSTATE, and RL_STATE_INPUTPENDING.
Referenced by _rl_isearch_dispatch(), _rl_vi_arg_dispatch(), rl_gather_tyi(), and rl_vi_subst().
rl_timeout_remaining()
int rl_timeout_remaining (unsigned int * secs, unsigned int * usecs)
Definition at line 614 of file input.c.
 {
   struct timeval current_time;
   /* Return -1 when timeout is unset. */
   if (timerisunset (&timeout_point))
     {
       errno = 0;
       return -1;
     }
   /* Return -1 on error. errno is set by gettimeofday. */
   if (gettimeofday(&current_time, 0) != 0)
     return -1;
   /* Return 0 when timeout has already expired. */
   /* could use timercmp (&timeout_point, &current_time, <) here */
   if (current_time.tv_sec > timeout_point.tv_sec ||
     (current_time.tv_sec == timeout_point.tv_sec &&
      current_time.tv_usec >= timeout_point.tv_usec))
     return 0;
   if (secs && usecs)
     {
       *secs = timeout_point.tv_sec - current_time.tv_sec;
       *usecs = timeout_point.tv_usec - current_time.tv_usec;
       if (timeout_point.tv_usec < current_time.tv_usec)
     {
       (*secs)--;
       *usecs += USEC_PER_SEC;
     }
     }
   return 1;
 }
References errno, gettimeofday(), timeout_point, timerisunset, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
set_alarm()
static int set_alarm (unsigned int * secs, unsigned int * usecs) static
Definition at line 538 of file input.c.
 {
   if (*secs == 0 || *usecs >= USEC_PER_SEC / 2)
     (*secs)++;
   *usecs = 0;
   return alarm (*secs);
 }
References alarm(), and USEC_PER_SEC.
Referenced by _rl_timeout_init().
Variable Documentation
_keyboard_input_timeout
int _keyboard_input_timeout = 100000 static
Definition at line 102 of file input.c.
Referenced by _rl_input_available(), rl_gather_tyi(), and rl_set_keyboard_input_timeout().
errno
int errno extern
ibuffer
unsigned char ibuffer[512] static
Definition at line 176 of file input.c.
Referenced by _rl_unget_char(), rl_get_char(), and rl_stuff_char().
ibuffer_len
int ibuffer_len = sizeof (ibuffer) - 1 static
Definition at line 177 of file input.c.
Referenced by _rl_insert_typein(), _rl_unget_char(), ibuffer_space(), rl_gather_tyi(), rl_get_char(), and rl_stuff_char().
pop_index
int pop_index static
Definition at line 175 of file input.c.
Referenced by _rl_pushed_input_available(), _rl_unget_char(), ibuffer_space(), and rl_get_char().
push_index
int push_index static
Definition at line 175 of file input.c.
Referenced by _rl_pushed_input_available(), ibuffer_space(), rl_get_char(), and rl_stuff_char().
rl_event_hook
rl_hook_func_t* rl_event_hook = (rl_hook_func_t *)NULL
Definition at line 88 of file input.c.
Referenced by rl_read_key().
rl_getc_function
rl_getc_func_t* rl_getc_function = rl_getc
Definition at line 100 of file input.c.
Referenced by rl_read_key().
rl_input_available_hook
rl_hook_func_t* rl_input_available_hook = (rl_hook_func_t *)NULL
Definition at line 98 of file input.c.
Referenced by _rl_input_available().
rl_signal_event_hook
rl_hook_func_t* rl_signal_event_hook = (rl_hook_func_t *)NULL
Definition at line 91 of file input.c.
Referenced by _rl_signal_handler(), readline_internal_char(), rl_complete_internal(), and rl_getc().
rl_timeout_event_hook
rl_hook_func_t* rl_timeout_event_hook = (rl_hook_func_t *)NULL
Definition at line 94 of file input.c.
Referenced by _rl_timeout_handle().
timeout_duration
struct timeval timeout_duration static
Definition at line 159 of file input.c.
Referenced by _rl_timeout_init(), and rl_set_timeout().
timeout_point
struct timeval timeout_point static
Definition at line 159 of file input.c.
Referenced by _rl_timeout_handle_sigalrm(), _rl_timeout_init(), and rl_timeout_remaining().