Fennix: Kernel/Library/dumper.cpp File Reference
dumper.cpp File Reference
#include "dumper.hpp"
#include <memory.hpp>
#include <printf.h>
#include <uart.hpp>
#include <lock.hpp>
#include <md5.h>
Functions
NewLock (DumperLock)
static void print_wrapper (char c, void *unused)
int vprintf_dumper (const char *format, va_list list)
void WriteRaw (const char *format,...)
void DumpData (const char *Description, void *Address, unsigned long Length)
Function Documentation
DumpData()
void DumpData (const char * Description, void * Address, unsigned long Length)
Definition at line 46 of file dumper.cpp.
 {
     SmartLock(DumperLock);
     WriteRaw("-------------------------------------------------------------------------\n");
     unsigned char *AddressChar = (unsigned char *)Address;
     unsigned char Buffer[17];
     unsigned long Iterate;
     if (Description != nullptr)
         WriteRaw("%s:\n", Description);
     for (Iterate = 0; Iterate < Length; Iterate++)
     {
         if ((Iterate % 16) == 0)
         {
             if (Iterate != 0)
                 WriteRaw("  %s\n", Buffer);
             WriteRaw("  %04x ", Iterate);
         }
         WriteRaw(" %02x", AddressChar[Iterate]);
         if ((AddressChar[Iterate] < 0x20) || (AddressChar[Iterate] > 0x7e))
             Buffer[Iterate % 16] = '.';
         else
             Buffer[Iterate % 16] = AddressChar[Iterate];
         Buffer[(Iterate % 16) + 1] = '\0';
     }
     while ((Iterate % 16) != 0)
     {
         WriteRaw("   ");
         Iterate++;
     }
     WriteRaw("  %s\n", Buffer);
     WriteRaw("-------------------------------------------------------------------------\n");
     WriteRaw("Length: %ld bytes\n", Length);
     uint8_t *result = md5File(AddressChar, Length);
     WriteRaw("MD5: ");
     for (int i = 0; i < 16; i++)
         WriteRaw("%02x", result[i]);
     kfree(result);
     WriteRaw("\n-------------------------------------------------------------------------\n");
 }
References Address, i, kfree, Length, md5File(), and WriteRaw().
Referenced by DriverAHCIDiskRead(), and DriverAHCIDiskWrite().
NewLock()
NewLock (DumperLock)
print_wrapper()
static void print_wrapper (char c, void * unused) inline static
Definition at line 30 of file dumper.cpp.
 {
     UART(COM1).Write(c);
     UNUSED(unused);
 }
References c, UniversalAsynchronousReceiverTransmitter::COM1, UNUSED, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by vprintf_dumper().
vprintf_dumper()
int vprintf_dumper (const char * format, va_list list)
Definition at line 36 of file dumper.cpp.
 { return vfctprintf(print_wrapper, NULL, format, list); }
References format, NULL, print_wrapper(), and vfctprintf().
Referenced by WriteRaw().
WriteRaw()
void WriteRaw (const char * format, ...)
Definition at line 38 of file dumper.cpp.
 {
     va_list args;
     va_start(args, format);
     vprintf_dumper(format, args);
     va_end(args);
 }
References args, format, va_end(), va_start(), and vprintf_dumper().
Referenced by DumpData().