Fennix Userspace: Userspace/musl/src/stdlib/strtol.c File Reference
strtol.c File Reference
#include "stdio_impl.h"
#include "intscan.h"
#include "shgetc.h"
#include <inttypes.h>
#include <limits.h>
#include <ctype.h>
Functions
static unsigned long long strtox (const char *s, char **p, int base, unsigned long long lim)
unsigned long long strtoull (const char *restrict s, char **restrict p, int base)
long long strtoll (const char *restrict s, char **restrict p, int base)
unsigned long strtoul (const char *restrict s, char **restrict p, int base)
long strtol (const char *restrict s, char **restrict p, int base)
intmax_t strtoimax (const char *restrict s, char **restrict p, int base)
uintmax_t strtoumax (const char *restrict s, char **restrict p, int base)
weak_alias (strtol, __strtol_internal)
weak_alias (strtoul, __strtoul_internal)
weak_alias (strtoll, __strtoll_internal)
weak_alias (strtoull, __strtoull_internal)
weak_alias (strtoimax, __strtoimax_internal)
weak_alias (strtoumax, __strtoumax_internal)
Function Documentation
strtoimax()
intmax_t strtoimax (const char *restrict s, char **restrict p, int base)
Definition at line 41 of file strtol.c.
 {
     return strtoll(s, p, base);
 }
References base, p, s, and strtoll().
strtol()
long strtol (const char *restrict s, char **restrict p, int base)
Definition at line 36 of file strtol.c.
 {
     return strtox(s, p, base, 0UL+LONG_MIN);
 }
References base, LONG_MIN, p, s, strtox(), and UL.
strtoll()
long long strtoll (const char *restrict s, char **restrict p, int base)
Definition at line 26 of file strtol.c.
 {
     return strtox(s, p, base, LLONG_MIN);
 }
References base, LLONG_MIN, p, s, and strtox().
Referenced by strtoimax().
strtoul()
unsigned long strtoul (const char *restrict s, char **restrict p, int base)
Definition at line 31 of file strtol.c.
 {
     return strtox(s, p, base, ULONG_MAX);
 }
References base, p, s, strtox(), and ULONG_MAX.
strtoull()
unsigned long long strtoull (const char *restrict s, char **restrict p, int base)
Definition at line 21 of file strtol.c.
 {
     return strtox(s, p, base, ULLONG_MAX);
 }
References base, p, s, strtox(), and ULLONG_MAX.
Referenced by strtoumax().
strtoumax()
uintmax_t strtoumax (const char *restrict s, char **restrict p, int base)
Definition at line 46 of file strtol.c.
 {
     return strtoull(s, p, base);
 }
References base, p, s, and strtoull().
strtox()
static unsigned long long strtox (const char * s, char ** p, int base, unsigned long long lim) static
Definition at line 8 of file strtol.c.
 {
     FILE f;
     sh_fromstring(&f, s);
     shlim(&f, 0);
     unsigned long long y = __intscan(&f, base, 1, lim);
     if (p) {
         size_t cnt = shcnt(&f);
         *p = (char *)s + cnt;
     }
     return y;
 }
References __intscan(), base, cnt, f, p, s, sh_fromstring, shcnt, shlim, and y.
Referenced by strtol(), strtoll(), strtoul(), and strtoull().
weak_alias() [1/6]
weak_alias (strtoimax , __strtoimax_internal)
weak_alias() [2/6]
weak_alias (strtol , __strtol_internal)
weak_alias() [3/6]
weak_alias (strtoll , __strtoll_internal)
weak_alias() [4/6]
weak_alias (strtoul , __strtoul_internal)
weak_alias() [5/6]
weak_alias (strtoull , __strtoull_internal)
weak_alias() [6/6]
weak_alias (strtoumax , __strtoumax_internal)