Fennix: Userspace/apps/base/busybox/scripts/kconfig/expr.h File Reference
expr.h File Reference
#include <stdio.h>
#include <stdbool.h>
Data Structures
struct file
union expr_data
struct expr
struct expr_value
struct symbol_value
struct symbol
struct property
struct menu
Macros
#define FILE_BUSY 0x0001
#define FILE_SCANNED 0x0002
#define FILE_PRINTED 0x0004
#define E_OR(dep1, dep2) (((dep1)>(dep2))?(dep1):(dep2))
#define E_AND(dep1, dep2) (((dep1)<(dep2))?(dep1):(dep2))
#define E_NOT(dep) (2-(dep))
#define for_all_symbols(i, sym) for (i = 0; i < 257; i++) for (sym = symbol_hash[i]; sym; sym = sym->next) if (sym->type != S_OTHER)
#define SYMBOL_YES 0x0001
#define SYMBOL_MOD 0x0002
#define SYMBOL_NO 0x0004
#define SYMBOL_CONST 0x0007
#define SYMBOL_CHECK 0x0008
#define SYMBOL_CHOICE 0x0010
#define SYMBOL_CHOICEVAL 0x0020
#define SYMBOL_PRINTED 0x0040
#define SYMBOL_VALID 0x0080
#define SYMBOL_OPTIONAL 0x0100
#define SYMBOL_WRITE 0x0200
#define SYMBOL_CHANGED 0x0400
#define SYMBOL_NEW 0x0800
#define SYMBOL_AUTO 0x1000
#define SYMBOL_CHECKED 0x2000
#define SYMBOL_WARNED 0x8000
#define SYMBOL_MAXLENGTH 256
#define SYMBOL_HASHSIZE 257
#define SYMBOL_HASHMASK 0xff
#define for_all_properties(sym, st, tok)
#define for_all_defaults(sym, st) for_all_properties(sym, st, P_DEFAULT)
#define for_all_choices(sym, st) for_all_properties(sym, st, P_CHOICE)
#define for_all_prompts(sym, st)
#define MENU_CHANGED 0x0001
#define MENU_ROOT 0x0002
Typedefs
typedef enum tristate tristate
Enumerations
enum tristate { no , mod , yes }
enum expr_type {
E_NONE , E_OR , E_AND , E_NOT ,
E_EQUAL , E_UNEQUAL , E_CHOICE , E_SYMBOL ,
E_RANGE
}
enum symbol_type {
S_UNKNOWN , S_BOOLEAN , S_TRISTATE , S_INT ,
S_HEX , S_STRING , S_OTHER
}
enum prop_type {
P_UNKNOWN , P_PROMPT , P_COMMENT , P_MENU ,
P_DEFAULT , P_CHOICE , P_SELECT , P_RANGE
}
Functions
struct file * lookup_file (const char *name)
struct expr * expr_alloc_symbol (struct symbol *sym)
struct expr * expr_alloc_one (enum expr_type type, struct expr *ce)
struct expr * expr_alloc_two (enum expr_type type, struct expr *e1, struct expr *e2)
struct expr * expr_alloc_comp (enum expr_type type, struct symbol *s1, struct symbol *s2)
struct expr * expr_alloc_and (struct expr *e1, struct expr *e2)
struct expr * expr_alloc_or (struct expr *e1, struct expr *e2)
struct expr * expr_copy (struct expr *org)
void expr_free (struct expr *e)
int expr_eq (struct expr *e1, struct expr *e2)
void expr_eliminate_eq (struct expr **ep1, struct expr **ep2)
tristate expr_calc_value (struct expr *e)
struct expr * expr_eliminate_yn (struct expr *e)
struct expr * expr_trans_bool (struct expr *e)
struct expr * expr_eliminate_dups (struct expr *e)
struct expr * expr_transform (struct expr *e)
int expr_contains_symbol (struct expr *dep, struct symbol *sym)
bool expr_depends_symbol (struct expr *dep, struct symbol *sym)
struct expr * expr_extract_eq_and (struct expr **ep1, struct expr **ep2)
struct expr * expr_extract_eq_or (struct expr **ep1, struct expr **ep2)
void expr_extract_eq (enum expr_type type, struct expr **ep, struct expr **ep1, struct expr **ep2)
struct expr * expr_trans_compare (struct expr *e, enum expr_type type, struct symbol *sym)
void expr_fprint (struct expr *e, FILE *out)
void expr_gstr_print (struct expr *e, struct gstr *gs)
static int expr_is_yes (struct expr *e)
static int expr_is_no (struct expr *e)
Variables
struct file * file_list
struct file * current_file
struct symbol symbol_yes symbol_no symbol_mod
struct symbol * modules_sym
int cdebug
Data Structure Documentation
file
struct file
Definition at line 18 of file expr.h.
Data Fields
int flags
int lineno
char * name
struct file * next
struct file * parent
expr_data
union expr_data
Definition at line 38 of file expr.h.
Data Fields
struct expr * expr
struct symbol * sym
expr
struct expr
Definition at line 43 of file expr.h.
Data Fields
union expr_data left right
enum expr_type type
expr_value
struct expr_value
Definition at line 52 of file expr.h.
Data Fields
struct expr * expr
tristate tri
symbol_value
struct symbol_value
Definition at line 57 of file expr.h.
Data Fields
tristate tri
void * val
symbol
struct symbol
Definition at line 66 of file expr.h.
Data Fields
struct expr * dep
struct expr * dep2
int flags
char * help
char * name
struct symbol * next
struct property * prop
struct expr_value rev_dep
enum symbol_type type
struct symbol_value curr user
tristate visible
property
struct property
Definition at line 106 of file expr.h.
Data Fields
struct expr * expr
struct file * file
int lineno
struct menu * menu
struct property * next
struct symbol * sym
const char * text
enum prop_type type
struct expr_value visible
menu
struct menu
Definition at line 127 of file expr.h.
Data Fields
void * data
struct expr * dep
struct file * file
unsigned int flags
int lineno
struct menu * list
struct menu * next
struct menu * parent
struct property * prompt
struct symbol * sym
Macro Definition Documentation
E_AND
#define E_AND (dep1, dep2) (((dep1)<(dep2))?(dep1):(dep2))
Definition at line 49 of file expr.h.
E_NOT
#define E_NOT (dep) (2-(dep))
Definition at line 50 of file expr.h.
E_OR
#define E_OR (dep1, dep2) (((dep1)>(dep2))?(dep1):(dep2))
Definition at line 48 of file expr.h.
FILE_BUSY
#define FILE_BUSY 0x0001
Definition at line 26 of file expr.h.
FILE_PRINTED
#define FILE_PRINTED 0x0004
Definition at line 28 of file expr.h.
FILE_SCANNED
#define FILE_SCANNED 0x0002
Definition at line 27 of file expr.h.
for_all_choices
#define for_all_choices (sym, st) for_all_properties(sym, st, P_CHOICE)
Definition at line 122 of file expr.h.
for_all_defaults
#define for_all_defaults (sym, st) for_all_properties(sym, st, P_DEFAULT)
Definition at line 121 of file expr.h.
for_all_prompts
#define for_all_prompts (sym, st)
Value:
    for (st = sym->prop; st; st = st->next) \
        if (st->text)
Definition at line 123 of file expr.h.
for_all_properties
#define for_all_properties (sym, st, tok)
Value:
    for (st = sym->prop; st; st = st->next) \
        if (st->type == (tok))
Definition at line 118 of file expr.h.
for_all_symbols
#define for_all_symbols (i, sym) for (i = 0; i < 257; i++) for (sym = symbol_hash[i]; sym; sym = sym->next) if (sym->type != S_OTHER)
Definition at line 79 of file expr.h.
MENU_CHANGED
#define MENU_CHANGED 0x0001
Definition at line 141 of file expr.h.
MENU_ROOT
#define MENU_ROOT 0x0002
Definition at line 142 of file expr.h.
SYMBOL_AUTO
#define SYMBOL_AUTO 0x1000
Definition at line 94 of file expr.h.
SYMBOL_CHANGED
#define SYMBOL_CHANGED 0x0400
Definition at line 92 of file expr.h.
SYMBOL_CHECK
#define SYMBOL_CHECK 0x0008
Definition at line 85 of file expr.h.
SYMBOL_CHECKED
#define SYMBOL_CHECKED 0x2000
Definition at line 95 of file expr.h.
SYMBOL_CHOICE
#define SYMBOL_CHOICE 0x0010
Definition at line 86 of file expr.h.
SYMBOL_CHOICEVAL
#define SYMBOL_CHOICEVAL 0x0020
Definition at line 87 of file expr.h.
SYMBOL_CONST
#define SYMBOL_CONST 0x0007
Definition at line 84 of file expr.h.
SYMBOL_HASHMASK
#define SYMBOL_HASHMASK 0xff
Definition at line 100 of file expr.h.
SYMBOL_HASHSIZE
#define SYMBOL_HASHSIZE 257
Definition at line 99 of file expr.h.
SYMBOL_MAXLENGTH
#define SYMBOL_MAXLENGTH 256
Definition at line 98 of file expr.h.
SYMBOL_MOD
#define SYMBOL_MOD 0x0002
Definition at line 82 of file expr.h.
SYMBOL_NEW
#define SYMBOL_NEW 0x0800
Definition at line 93 of file expr.h.
SYMBOL_NO
#define SYMBOL_NO 0x0004
Definition at line 83 of file expr.h.
SYMBOL_OPTIONAL
#define SYMBOL_OPTIONAL 0x0100
Definition at line 90 of file expr.h.
SYMBOL_PRINTED
#define SYMBOL_PRINTED 0x0040
Definition at line 88 of file expr.h.
SYMBOL_VALID
#define SYMBOL_VALID 0x0080
Definition at line 89 of file expr.h.
SYMBOL_WARNED
#define SYMBOL_WARNED 0x8000
Definition at line 96 of file expr.h.
SYMBOL_WRITE
#define SYMBOL_WRITE 0x0200
Definition at line 91 of file expr.h.
SYMBOL_YES
#define SYMBOL_YES 0x0001
Definition at line 81 of file expr.h.
Typedef Documentation
tristate
typedef enum tristate tristate
Enumeration Type Documentation
expr_type
enum expr_type
Enumerator
E_NONE
E_OR
E_AND
E_NOT
E_EQUAL
E_UNEQUAL
E_CHOICE
E_SYMBOL
E_RANGE
Definition at line 34 of file expr.h.
                {
     E_NONE, E_OR, E_AND, E_NOT, E_EQUAL, E_UNEQUAL, E_CHOICE, E_SYMBOL, E_RANGE
 };
prop_type
enum prop_type
Enumerator
P_UNKNOWN
P_PROMPT
P_COMMENT
P_MENU
P_DEFAULT
P_CHOICE
P_SELECT
P_RANGE
Definition at line 102 of file expr.h.
                {
     P_UNKNOWN, P_PROMPT, P_COMMENT, P_MENU, P_DEFAULT, P_CHOICE, P_SELECT, P_RANGE
 };
symbol_type
enum symbol_type
Enumerator
S_UNKNOWN
S_BOOLEAN
S_TRISTATE
S_INT
S_HEX
S_STRING
S_OTHER
Definition at line 62 of file expr.h.
                  {
     S_UNKNOWN, S_BOOLEAN, S_TRISTATE, S_INT, S_HEX, S_STRING, S_OTHER
 };
tristate
enum tristate
Enumerator
no
mod
yes
Definition at line 30 of file expr.h.
                       {
     no, mod, yes
 } tristate;
Function Documentation
expr_alloc_and()
struct expr* expr_alloc_and (struct expr * e1, struct expr * e2)
Definition at line 53 of file expr.c.
 {
     if (!e1)
         return e2;
     return e2 ? expr_alloc_two(E_AND, e1, e2) : e1;
 }
References e1, e2, E_AND, and expr_alloc_two().
Referenced by menu_add_dep(), menu_check_dep(), and menu_finalize().
expr_alloc_comp()
struct expr* expr_alloc_comp (enum expr_type type, struct symbol * s1, struct symbol * s2)
Definition at line 43 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = type;
     e->left.sym = s1;
     e->right.sym = s2;
     return e;
 }
References malloc, memset, expr::right, s1, s2, expr_data::sym, type, and expr::type.
Referenced by expr_join_and(), expr_join_or(), and expr_trans_compare().
expr_alloc_one()
struct expr* expr_alloc_one (enum expr_type type, struct expr * ce)
Definition at line 24 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = type;
     e->left.expr = ce;
     return e;
 }
References malloc, memset, type, and expr::type.
Referenced by expr_eliminate_dups2(), expr_trans_compare(), expr_transform(), and menu_finalize().
expr_alloc_or()
struct expr* expr_alloc_or (struct expr * e1, struct expr * e2)
Definition at line 60 of file expr.c.
 {
     if (!e1)
         return e2;
     return e2 ? expr_alloc_two(E_OR, e1, e2) : e1;
 }
References e1, e2, E_OR, and expr_alloc_two().
Referenced by menu_finalize().
expr_alloc_symbol()
struct expr* expr_alloc_symbol (struct symbol * sym)
Definition at line 15 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = E_SYMBOL;
     e->left.sym = sym;
     return e;
 }
References E_SYMBOL, malloc, memset, and expr::type.
Referenced by __expr_eliminate_eq(), expr_eliminate_dups1(), expr_eliminate_dups2(), expr_extract_eq(), expr_join_and(), expr_join_or(), expr_trans_compare(), expr_transform(), menu_add_symbol(), menu_check_dep(), menu_finalize(), and sym_add_default().
expr_alloc_two()
struct expr* expr_alloc_two (enum expr_type type, struct expr * e1, struct expr * e2)
Definition at line 33 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = type;
     e->left.expr = e1;
     e->right.expr = e2;
     return e;
 }
References e1, e2, expr_data::expr, malloc, memset, expr::right, type, and expr::type.
Referenced by expr_alloc_and(), expr_alloc_or(), expr_extract_eq(), and expr_trans_compare().
expr_calc_value()
tristate expr_calc_value (struct expr * e)
Definition at line 942 of file expr.c.
 {
     tristate val1, val2;
     const char *str1, *str2;
     if (!e)
         return yes;
     switch (e->type) {
     case E_SYMBOL:
         sym_calc_value(e->left.sym);
         return e->left.sym->curr.tri;
     case E_AND:
         val1 = expr_calc_value(e->left.expr);
         val2 = expr_calc_value(e->right.expr);
         return E_AND(val1, val2);
     case E_OR:
         val1 = expr_calc_value(e->left.expr);
         val2 = expr_calc_value(e->right.expr);
         return E_OR(val1, val2);
     case E_NOT:
         val1 = expr_calc_value(e->left.expr);
         return E_NOT(val1);
     case E_EQUAL:
         sym_calc_value(e->left.sym);
         sym_calc_value(e->right.sym);
         str1 = sym_get_string_value(e->left.sym);
         str2 = sym_get_string_value(e->right.sym);
         return !strcmp(str1, str2) ? yes : no;
     case E_UNEQUAL:
         sym_calc_value(e->left.sym);
         sym_calc_value(e->right.sym);
         str1 = sym_get_string_value(e->left.sym);
         str2 = sym_get_string_value(e->right.sym);
         return !strcmp(str1, str2) ? no : yes;
     default:
         printf("expr_calc_value: %d?\n", e->type);
         return no;
     }
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, no, printf, expr::right, strcmp, expr_data::sym, sym_calc_value(), sym_get_string_value(), expr::type, and yes.
Referenced by menu_is_visible(), sym_calc_choice(), sym_calc_value(), sym_calc_visibility(), sym_get_default_prop(), and sym_get_range_prop().
expr_contains_symbol()
int expr_contains_symbol (struct expr * dep, struct symbol * sym)
Definition at line 777 of file expr.c.
 {
     if (!dep)
         return 0;
     switch (dep->type) {
     case E_AND:
     case E_OR:
         return expr_contains_symbol(dep->left.expr, sym) ||
                expr_contains_symbol(dep->right.expr, sym);
     case E_SYMBOL:
         return dep->left.sym == sym;
     case E_EQUAL:
     case E_UNEQUAL:
         return dep->left.sym == sym ||
                dep->right.sym == sym;
     case E_NOT:
         return expr_contains_symbol(dep->left.expr, sym);
     default:
         ;
     }
     return 0;
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr::right, expr_data::sym, and expr::type.
Referenced by menu_finalize().
expr_copy()
struct expr* expr_copy (struct expr * org)
Definition at line 67 of file expr.c.
 {
     struct expr *e;
     if (!org)
         return NULL;
     e = malloc(sizeof(*org));
     memcpy(e, org, sizeof(*org));
     switch (org->type) {
     case E_SYMBOL:
         e->left = org->left;
         break;
     case E_NOT:
         e->left.expr = expr_copy(org->left.expr);
         break;
     case E_EQUAL:
     case E_UNEQUAL:
         e->left.sym = org->left.sym;
         e->right.sym = org->right.sym;
         break;
     case E_AND:
     case E_OR:
     case E_CHOICE:
         e->left.expr = expr_copy(org->left.expr);
         e->right.expr = expr_copy(org->right.expr);
         break;
     default:
         printf("can't copy type %d\n", e->type);
         free(e);
         e = NULL;
         break;
     }
     return e;
 }
References E_AND, E_CHOICE, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, free, malloc, memcpy, NULL, printf, expr::right, expr_data::sym, and expr::type.
Referenced by expr_eliminate_dups2(), expr_eq(), expr_join_and(), expr_join_or(), expr_trans_compare(), and menu_finalize().
expr_depends_symbol()
bool expr_depends_symbol (struct expr * dep, struct symbol * sym)
Definition at line 801 of file expr.c.
 {
     if (!dep)
         return false;
     switch (dep->type) {
     case E_AND:
         return expr_depends_symbol(dep->left.expr, sym) ||
                expr_depends_symbol(dep->right.expr, sym);
     case E_SYMBOL:
         return dep->left.sym == sym;
     case E_EQUAL:
         if (dep->left.sym == sym) {
             if (dep->right.sym == &symbol_yes || dep->right.sym == &symbol_mod)
                 return true;
         }
         break;
     case E_UNEQUAL:
         if (dep->left.sym == sym) {
             if (dep->right.sym == &symbol_no)
                 return true;
         }
         break;
     default:
         ;
     }
     return false;
 }
References E_AND, E_EQUAL, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr::right, expr_data::sym, symbol_mod, symbol_no, symbol_yes, and expr::type.
Referenced by menu_finalize().
expr_eliminate_dups()
struct expr* expr_eliminate_dups (struct expr * e)
Definition at line 616 of file expr.c.
 {
     int oldcount;
     if (!e)
         return e;
     oldcount = trans_count;
     while (1) {
         trans_count = 0;
         switch (e->type) {
         case E_OR: case E_AND:
             expr_eliminate_dups1(e->type, &e, &e);
             expr_eliminate_dups2(e->type, &e, &e);
         default:
             ;
         }
         if (!trans_count)
             break;
         e = expr_eliminate_yn(e);
     }
     trans_count = oldcount;
     return e;
 }
References E_AND, E_OR, expr_eliminate_dups1(), expr_eliminate_dups2(), expr_eliminate_yn(), trans_count, and expr::type.
Referenced by menu_finalize().
expr_eliminate_eq()
void expr_eliminate_eq (struct expr ** ep1, struct expr ** ep2)
Definition at line 168 of file expr.c.
 {
     if (!e1 || !e2)
         return;
     switch (e1->type) {
     case E_OR:
     case E_AND:
         __expr_eliminate_eq(e1->type, ep1, ep2);
     default:
         ;
     }
     if (e1->type != e2->type) switch (e2->type) {
     case E_OR:
     case E_AND:
         __expr_eliminate_eq(e2->type, ep1, ep2);
     default:
         ;
     }
     e1 = expr_eliminate_yn(e1);
     e2 = expr_eliminate_yn(e2);
 }
References __expr_eliminate_eq(), e1, e2, E_AND, E_OR, ep1, ep2, and expr_eliminate_yn().
Referenced by expr_eq(), and menu_finalize().
expr_eliminate_yn()
struct expr* expr_eliminate_yn (struct expr * e)
Definition at line 235 of file expr.c.
 {
     struct expr *tmp;
     if (e) switch (e->type) {
     case E_AND:
         e->left.expr = expr_eliminate_yn(e->left.expr);
         e->right.expr = expr_eliminate_yn(e->right.expr);
         if (e->left.expr->type == E_SYMBOL) {
             if (e->left.expr->left.sym == &symbol_no) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_no;
                 e->right.expr = NULL;
                 return e;
             } else if (e->left.expr->left.sym == &symbol_yes) {
                 free(e->left.expr);
                 tmp = e->right.expr;
                 *e = *(e->right.expr);
                 free(tmp);
                 return e;
             }
         }
         if (e->right.expr->type == E_SYMBOL) {
             if (e->right.expr->left.sym == &symbol_no) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_no;
                 e->right.expr = NULL;
                 return e;
             } else if (e->right.expr->left.sym == &symbol_yes) {
                 free(e->right.expr);
                 tmp = e->left.expr;
                 *e = *(e->left.expr);
                 free(tmp);
                 return e;
             }
         }
         break;
     case E_OR:
         e->left.expr = expr_eliminate_yn(e->left.expr);
         e->right.expr = expr_eliminate_yn(e->right.expr);
         if (e->left.expr->type == E_SYMBOL) {
             if (e->left.expr->left.sym == &symbol_no) {
                 free(e->left.expr);
                 tmp = e->right.expr;
                 *e = *(e->right.expr);
                 free(tmp);
                 return e;
             } else if (e->left.expr->left.sym == &symbol_yes) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_yes;
                 e->right.expr = NULL;
                 return e;
             }
         }
         if (e->right.expr->type == E_SYMBOL) {
             if (e->right.expr->left.sym == &symbol_no) {
                 free(e->right.expr);
                 tmp = e->left.expr;
                 *e = *(e->left.expr);
                 free(tmp);
                 return e;
             } else if (e->right.expr->left.sym == &symbol_yes) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_yes;
                 e->right.expr = NULL;
                 return e;
             }
         }
         break;
     default:
         ;
     }
     return e;
 }
References E_AND, E_OR, E_SYMBOL, expr_data::expr, expr_free(), free, NULL, expr::right, symbol_no, symbol_yes, and expr::type.
Referenced by expr_eliminate_dups(), expr_eliminate_eq(), expr_extract_eq_and(), and expr_extract_eq_or().
expr_eq()
int expr_eq (struct expr * e1, struct expr * e2)
Definition at line 193 of file expr.c.
 {
     int res, old_count;
     if (e1->type != e2->type)
         return 0;
     switch (e1->type) {
     case E_EQUAL:
     case E_UNEQUAL:
         return e1->left.sym == e2->left.sym && e1->right.sym == e2->right.sym;
     case E_SYMBOL:
         return e1->left.sym == e2->left.sym;
     case E_NOT:
         return expr_eq(e1->left.expr, e2->left.expr);
     case E_AND:
     case E_OR:
         e1 = expr_copy(e1);
         e2 = expr_copy(e2);
         old_count = trans_count;
         expr_eliminate_eq(&e1, &e2);
         res = (e1->type == E_SYMBOL && e2->type == E_SYMBOL &&
                e1->left.sym == e2->left.sym);
         expr_free(e1);
         expr_free(e2);
         trans_count = old_count;
         return res;
     case E_CHOICE:
     case E_RANGE:
     case E_NONE:
         /* panic */;
     }
     if (DEBUG_EXPR) {
         expr_fprint(e1, stdout);
         printf(" = ");
         expr_fprint(e2, stdout);
         printf(" ?\n");
     }
     return 0;
 }
References DEBUG_EXPR, e1, e2, E_AND, E_CHOICE, E_EQUAL, E_NONE, E_NOT, E_OR, E_RANGE, E_SYMBOL, E_UNEQUAL, expr_copy(), expr_eliminate_eq(), expr_fprint(), expr_free(), printf, stdout, and trans_count.
Referenced by __expr_eliminate_eq(), expr_extract_eq(), expr_join_and(), and expr_join_or().
expr_extract_eq()
void expr_extract_eq (enum expr_type type, struct expr ** ep, struct expr ** ep1, struct expr ** ep2)
Definition at line 852 of file expr.c.
 {
 #define e1 (*ep1)
 #define e2 (*ep2)
     if (e1->type == type) {
         expr_extract_eq(type, ep, &e1->left.expr, &e2);
         expr_extract_eq(type, ep, &e1->right.expr, &e2);
         return;
     }
     if (e2->type == type) {
         expr_extract_eq(type, ep, ep1, &e2->left.expr);
         expr_extract_eq(type, ep, ep1, &e2->right.expr);
         return;
     }
     if (expr_eq(e1, e2)) {
         *ep = *ep ? expr_alloc_two(type, *ep, e1) : e1;
         expr_free(e2);
         if (type == E_AND) {
             e1 = expr_alloc_symbol(&symbol_yes);
             e2 = expr_alloc_symbol(&symbol_yes);
         } else if (type == E_OR) {
             e1 = expr_alloc_symbol(&symbol_no);
             e2 = expr_alloc_symbol(&symbol_no);
         }
     }
 #undef e1
 #undef e2
 }
References e1, e2, E_AND, E_OR, ep1, expr_alloc_symbol(), expr_alloc_two(), expr_eq(), expr_free(), symbol_no, symbol_yes, and type.
Referenced by expr_extract_eq_and(), and expr_extract_eq_or().
expr_extract_eq_and()
struct expr* expr_extract_eq_and (struct expr ** ep1, struct expr ** ep2)
Definition at line 830 of file expr.c.
 {
     struct expr *tmp = NULL;
     expr_extract_eq(E_AND, &tmp, ep1, ep2);
     if (tmp) {
         *ep1 = expr_eliminate_yn(*ep1);
         *ep2 = expr_eliminate_yn(*ep2);
     }
     return tmp;
 }
References E_AND, ep1, ep2, expr_eliminate_yn(), expr_extract_eq(), and NULL.
Referenced by expr_eliminate_dups2().
expr_extract_eq_or()
struct expr* expr_extract_eq_or (struct expr ** ep1, struct expr ** ep2)
Definition at line 841 of file expr.c.
 {
     struct expr *tmp = NULL;
     expr_extract_eq(E_OR, &tmp, ep1, ep2);
     if (tmp) {
         *ep1 = expr_eliminate_yn(*ep1);
         *ep2 = expr_eliminate_yn(*ep2);
     }
     return tmp;
 }
References E_OR, ep1, ep2, expr_eliminate_yn(), expr_extract_eq(), and NULL.
Referenced by expr_eliminate_dups2().
expr_fprint()
void expr_fprint (struct expr * e, FILE * out)
Definition at line 1086 of file expr.c.
 {
     expr_print(e, expr_print_file_helper, out, E_NONE);
 }
References E_NONE, expr_print(), expr_print_file_helper(), and out().
Referenced by expr_eq(), expr_join_and(), and expr_join_or().
expr_free()
void expr_free (struct expr * e)
Definition at line 104 of file expr.c.
 {
     if (!e)
         return;
     switch (e->type) {
     case E_SYMBOL:
         break;
     case E_NOT:
         expr_free(e->left.expr);
         return;
     case E_EQUAL:
     case E_UNEQUAL:
         break;
     case E_OR:
     case E_AND:
         expr_free(e->left.expr);
         expr_free(e->right.expr);
         break;
     default:
         printf("how to free type %d?\n", e->type);
         break;
     }
     free(e);
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, free, printf, expr::right, and expr::type.
Referenced by __expr_eliminate_eq(), expr_eliminate_dups1(), expr_eliminate_dups2(), expr_eliminate_yn(), expr_eq(), expr_extract_eq(), and menu_finalize().
expr_gstr_print()
void expr_gstr_print (struct expr * e, struct gstr * gs)
Definition at line 1096 of file expr.c.
 {
     expr_print(e, expr_print_gstr_helper, gs, E_NONE);
 }
References E_NONE, expr_print(), and expr_print_gstr_helper().
Referenced by get_prompt_str(), and get_relations_str().
expr_is_no()
static int expr_is_no (struct expr * e) inline static
Definition at line 184 of file expr.h.
 {
     return e && (e->type == E_SYMBOL && e->left.sym == &symbol_no);
 }
References E_SYMBOL, symbol_no, and expr::type.
Referenced by expr_eliminate_dups2().
expr_is_yes()
static int expr_is_yes (struct expr * e) inline static
Definition at line 179 of file expr.h.
 {
     return !e || (e->type == E_SYMBOL && e->left.sym == &symbol_yes);
 }
References E_SYMBOL, symbol_yes, and expr::type.
Referenced by expr_eliminate_dups2(), get_prompt_str(), and menu_finalize().
expr_trans_bool()
struct expr* expr_trans_bool (struct expr * e)
Definition at line 321 of file expr.c.
 {
     if (!e)
         return NULL;
     switch (e->type) {
     case E_AND:
     case E_OR:
     case E_NOT:
         e->left.expr = expr_trans_bool(e->left.expr);
         e->right.expr = expr_trans_bool(e->right.expr);
         break;
     case E_UNEQUAL:
         // FOO!=n -> FOO
         if (e->left.sym->type == S_TRISTATE) {
             if (e->right.sym == &symbol_no) {
                 e->type = E_SYMBOL;
                 e->right.sym = NULL;
             }
         }
         break;
     default:
         ;
     }
     return e;
 }
References E_AND, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, NULL, expr::right, S_TRISTATE, expr_data::sym, symbol_no, and expr::type.
Referenced by menu_finalize().
expr_trans_compare()
struct expr* expr_trans_compare (struct expr * e, enum expr_type type, struct symbol * sym)
Definition at line 881 of file expr.c.
 {
     struct expr *e1, *e2;
     if (!e) {
         e = expr_alloc_symbol(sym);
         if (type == E_UNEQUAL)
             e = expr_alloc_one(E_NOT, e);
         return e;
     }
     switch (e->type) {
     case E_AND:
         e1 = expr_trans_compare(e->left.expr, E_EQUAL, sym);
         e2 = expr_trans_compare(e->right.expr, E_EQUAL, sym);
         if (sym == &symbol_yes)
             e = expr_alloc_two(E_AND, e1, e2);
         if (sym == &symbol_no)
             e = expr_alloc_two(E_OR, e1, e2);
         if (type == E_UNEQUAL)
             e = expr_alloc_one(E_NOT, e);
         return e;
     case E_OR:
         e1 = expr_trans_compare(e->left.expr, E_EQUAL, sym);
         e2 = expr_trans_compare(e->right.expr, E_EQUAL, sym);
         if (sym == &symbol_yes)
             e = expr_alloc_two(E_OR, e1, e2);
         if (sym == &symbol_no)
             e = expr_alloc_two(E_AND, e1, e2);
         if (type == E_UNEQUAL)
             e = expr_alloc_one(E_NOT, e);
         return e;
     case E_NOT:
         return expr_trans_compare(e->left.expr, type == E_EQUAL ? E_UNEQUAL : E_EQUAL, sym);
     case E_UNEQUAL:
     case E_EQUAL:
         if (type == E_EQUAL) {
             if (sym == &symbol_yes)
                 return expr_copy(e);
             if (sym == &symbol_mod)
                 return expr_alloc_symbol(&symbol_no);
             if (sym == &symbol_no)
                 return expr_alloc_one(E_NOT, expr_copy(e));
         } else {
             if (sym == &symbol_yes)
                 return expr_alloc_one(E_NOT, expr_copy(e));
             if (sym == &symbol_mod)
                 return expr_alloc_symbol(&symbol_yes);
             if (sym == &symbol_no)
                 return expr_copy(e);
         }
         break;
     case E_SYMBOL:
         return expr_alloc_comp(type, e->left.sym, sym);
     case E_CHOICE:
     case E_RANGE:
     case E_NONE:
         /* panic */;
     }
     return NULL;
 }
References e1, e2, E_AND, E_CHOICE, E_EQUAL, E_NONE, E_NOT, E_OR, E_RANGE, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr_alloc_comp(), expr_alloc_one(), expr_alloc_symbol(), expr_alloc_two(), expr_copy(), NULL, expr::right, symbol_mod, symbol_no, symbol_yes, type, and expr::type.
Referenced by menu_finalize().
expr_transform()
struct expr* expr_transform (struct expr * e)
Definition at line 640 of file expr.c.
 {
     struct expr *tmp;
     if (!e)
         return NULL;
     switch (e->type) {
     case E_EQUAL:
     case E_UNEQUAL:
     case E_SYMBOL:
     case E_CHOICE:
         break;
     default:
         e->left.expr = expr_transform(e->left.expr);
         e->right.expr = expr_transform(e->right.expr);
     }
     switch (e->type) {
     case E_EQUAL:
         if (e->left.sym->type != S_BOOLEAN)
             break;
         if (e->right.sym == &symbol_no) {
             e->type = E_NOT;
             e->left.expr = expr_alloc_symbol(e->left.sym);
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_mod) {
             printf("boolean symbol %s tested for 'm'? test forced to 'n'\n", e->left.sym->name);
             e->type = E_SYMBOL;
             e->left.sym = &symbol_no;
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_yes) {
             e->type = E_SYMBOL;
             e->right.sym = NULL;
             break;
         }
         break;
     case E_UNEQUAL:
         if (e->left.sym->type != S_BOOLEAN)
             break;
         if (e->right.sym == &symbol_no) {
             e->type = E_SYMBOL;
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_mod) {
             printf("boolean symbol %s tested for 'm'? test forced to 'y'\n", e->left.sym->name);
             e->type = E_SYMBOL;
             e->left.sym = &symbol_yes;
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_yes) {
             e->type = E_NOT;
             e->left.expr = expr_alloc_symbol(e->left.sym);
             e->right.sym = NULL;
             break;
         }
         break;
     case E_NOT:
         switch (e->left.expr->type) {
         case E_NOT:
             // !!a -> a
             tmp = e->left.expr->left.expr;
             free(e->left.expr);
             free(e);
             e = tmp;
             e = expr_transform(e);
             break;
         case E_EQUAL:
         case E_UNEQUAL:
             // !a='x' -> a!='x'
             tmp = e->left.expr;
             free(e);
             e = tmp;
             e->type = e->type == E_EQUAL ? E_UNEQUAL : E_EQUAL;
             break;
         case E_OR:
             // !(a || b) -> !a && !b
             tmp = e->left.expr;
             e->type = E_AND;
             e->right.expr = expr_alloc_one(E_NOT, tmp->right.expr);
             tmp->type = E_NOT;
             tmp->right.expr = NULL;
             e = expr_transform(e);
             break;
         case E_AND:
             // !(a && b) -> !a || !b
             tmp = e->left.expr;
             e->type = E_OR;
             e->right.expr = expr_alloc_one(E_NOT, tmp->right.expr);
             tmp->type = E_NOT;
             tmp->right.expr = NULL;
             e = expr_transform(e);
             break;
         case E_SYMBOL:
             if (e->left.expr->left.sym == &symbol_yes) {
                 // !'y' -> 'n'
                 tmp = e->left.expr;
                 free(e);
                 e = tmp;
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_no;
                 break;
             }
             if (e->left.expr->left.sym == &symbol_mod) {
                 // !'m' -> 'm'
                 tmp = e->left.expr;
                 free(e);
                 e = tmp;
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_mod;
                 break;
             }
             if (e->left.expr->left.sym == &symbol_no) {
                 // !'n' -> 'y'
                 tmp = e->left.expr;
                 free(e);
                 e = tmp;
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_yes;
                 break;
             }
             break;
         default:
             ;
         }
         break;
     default:
         ;
     }
     return e;
 }
References E_AND, E_CHOICE, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr_alloc_one(), expr_alloc_symbol(), free, NULL, printf, expr::right, S_BOOLEAN, expr_data::sym, symbol_mod, symbol_no, symbol_yes, and expr::type.
Referenced by expr_eliminate_dups2(), and menu_finalize().
lookup_file()
struct file* lookup_file (const char * name)
Variable Documentation
cdebug
int cdebug extern
current_file
struct file* current_file extern
Definition at line 16 of file menu.c.
Referenced by menu_add_entry().
file_list
struct file* file_list extern
Definition at line 15 of file menu.c.
Referenced by create_list(), file_lookup(), and file_write_dep().
modules_sym
struct symbol* modules_sym extern
Definition at line 34 of file symbol.c.
Referenced by conf_read_simple(), conf_write(), menu_check_dep(), sym_calc_value(), sym_clear_all_valid(), and sym_set_tristate_value().
symbol_mod
struct symbol symbol_yes symbol_no symbol_mod extern
Definition at line 19 of file symbol.c.
Referenced by expr_depends_symbol(), expr_join_and(), expr_join_or(), expr_trans_compare(), expr_transform(), menu_check_dep(), menu_finalize(), sym_find(), and sym_lookup().