Fennix: Port Class Reference
Port Class Reference
Public Member Functions
Port (PortType Type, HBAPort *PortPtr, uint8_t PortNumber)
~Port ()
void StartCMD ()
void StopCMD ()
void Configure ()
bool ReadWrite (uint64_t Sector, uint32_t SectorCount, uint8_t *Buffer, bool Write)
void Identify ()
Data Fields
PortType AHCIPortType
HBAPort * HBAPortPtr
uint8_t * Buffer
uint8_t PortNumber
ATA_IDENTIFY * IdentifyData
Detailed Description
Definition at line 563 of file ahci.cpp.
Constructor & Destructor Documentation
Port()
Port::Port (PortType Type, HBAPort * PortPtr, uint8_t PortNumber) inline
Definition at line 572 of file ahci.cpp.
     {
         this->AHCIPortType = Type;
         this->HBAPortPtr = PortPtr;
         this->Buffer = static_cast<uint8_t *>(AllocateMemory(1));
         MemorySet(this->Buffer, 0, PAGE_SIZE);
         this->IdentifyData = static_cast<ATA_IDENTIFY *>(AllocateMemory(1));
         MemorySet(this->IdentifyData, 0, PAGE_SIZE);
         this->PortNumber = PortNumber;
     }
References AllocateMemory(), MemorySet(), PAGE_SIZE, and PortNumber.
~Port()
Port::~Port () inline
Definition at line 583 of file ahci.cpp.
     {
         FreeMemory(this->Buffer, 1);
     }
References FreeMemory().
Member Function Documentation
Configure()
void Port::Configure () inline
Definition at line 610 of file ahci.cpp.
     {
         this->StopCMD();
         void *CmdBase = AllocateMemory(1);
         HBAPortPtr->CommandListBase = (uint32_t)(uint64_t)CmdBase;
         HBAPortPtr->CommandListBaseUpper = (uint32_t)((uint64_t)CmdBase >> 32);
         MemorySet(reinterpret_cast<void *>(HBAPortPtr->CommandListBase), 0, 1024);
         void *FISBase = AllocateMemory(1);
         HBAPortPtr->FISBaseAddress = (uint32_t)(uint64_t)FISBase;
         HBAPortPtr->FISBaseAddressUpper = (uint32_t)((uint64_t)FISBase >> 32);
         MemorySet(FISBase, 0, 256);
         HBACommandHeader *CommandHeader = (HBACommandHeader *)((uint64_t)HBAPortPtr->CommandListBase + ((uint64_t)HBAPortPtr->CommandListBaseUpper << 32));
         for (int i = 0; i < 32; i++)
         {
             CommandHeader[i].PRDTLength = 8;
             void *CommandTableAddress = AllocateMemory(1);
             uint64_t Address = (uint64_t)CommandTableAddress + (i << 8);
             CommandHeader[i].CommandTableBaseAddress = (uint32_t)(uint64_t)Address;
             CommandHeader[i].CommandTableBaseAddressUpper = (uint32_t)((uint64_t)Address >> 32);
             MemorySet(CommandTableAddress, 0, 256);
         }
         this->StartCMD();
         Identify();
         Log("Port %d \"%x %x %x %x\" configured", PortNumber,
             HBAPortPtr->Vendor[0], HBAPortPtr->Vendor[1],
             HBAPortPtr->Vendor[2], HBAPortPtr->Vendor[3]);
     }
References Address, AllocateMemory(), HBAPort::CommandListBase, HBAPort::CommandListBaseUpper, HBACommandHeader::CommandTableBaseAddress, HBACommandHeader::CommandTableBaseAddressUpper, HBAPort::FISBaseAddress, HBAPort::FISBaseAddressUpper, HBAPortPtr, i, Identify(), Log(), MemorySet(), HBACommandHeader::PRDTLength, StartCMD(), StopCMD(), and HBAPort::Vendor.
Identify()
void Port::Identify () inline
Definition at line 741 of file ahci.cpp.
     {
         MemorySet(this->IdentifyData, 0, sizeof(ATA_IDENTIFY));
         HBACommandHeader *CommandHeader = reinterpret_cast<HBACommandHeader *>(HBAPortPtr->CommandListBase);
         CommandHeader->CommandFISLength = sizeof(FIS_REG_H2D) / sizeof(uint32_t);
         CommandHeader->Write = 0;
         CommandHeader->PRDTLength = 1;
         HBACommandTable *CommandTable = reinterpret_cast<HBACommandTable *>(CommandHeader->CommandTableBaseAddress);
         MemorySet(CommandTable, 0, sizeof(HBACommandTable) + (CommandHeader->PRDTLength - 1) * sizeof(HBAPRDTEntry));
         CommandTable->PRDTEntry[0].DataBaseAddress = (uint32_t)(uint64_t)this->IdentifyData;
         CommandTable->PRDTEntry[0].DataBaseAddressUpper = (uint32_t)((uint64_t)this->IdentifyData >> 32);
         CommandTable->PRDTEntry[0].ByteCount = 511;
         CommandTable->PRDTEntry[0].InterruptOnCompletion = 1;
         FIS_REG_H2D *CommandFIS = (FIS_REG_H2D *)(&CommandTable->CommandFIS);
         CommandFIS->FISType = FIS_TYPE_REG_H2D;
         CommandFIS->CommandControl = 1;
         CommandFIS->Command = this->AHCIPortType == PortType::SATAPI ? ATAPI_CMD_IDENTIFY_PACKET : ATA_CMD_IDENTIFY;
         HBAPortPtr->CommandIssue = 1;
         while (HBAPortPtr->CommandIssue)
             Yield();
         if (HBAPortPtr->InterruptStatus & HBA_PxIS_TFES)
         {
             Log("Error reading IDENTIFY command.");
             return;
         }
         if (IdentifyData->Signature != 0xA5)
             Log("Port %d has no validity signature.", PortNumber);
         else
         {
             uint8_t *ptr = (uint8_t *)IdentifyData;
             uint8_t sum = 0;
             for (size_t i = 0; i < sizeof(ATA_IDENTIFY); i++)
                 sum += ptr[i];
             if (sum != 0)
             {
                 Log("Port %d has invalid checksum.", PortNumber);
                 return;
             }
             else
                 Log("Port %d has valid checksum.", PortNumber);
         }
         char *Model = (char *)this->IdentifyData->ModelNumber;
         char ModelSwap[41];
         for (size_t i = 0; i < 40; i += 2)
         {
             ModelSwap[i] = Model[i + 1];
             ModelSwap[i + 1] = Model[i];
         }
         ModelSwap[40] = 0;
         Log("Port %d \"%s\" identified", PortNumber,
             ModelSwap);
         Log("Port %d is %s (%d rotation rate)", PortNumber,
             IdentifyData->NominalMediaRotationRate == 1 ? "SSD" : "HDD",
             IdentifyData->NominalMediaRotationRate);
     }
References ATA_CMD_IDENTIFY, ATAPI_CMD_IDENTIFY_PACKET, HBAPRDTEntry::ByteCount, FIS_REG_H2D::Command, FIS_REG_H2D::CommandControl, HBACommandTable::CommandFIS, HBACommandHeader::CommandFISLength, HBAPort::CommandIssue, HBAPort::CommandListBase, HBACommandHeader::CommandTableBaseAddress, HBAPRDTEntry::DataBaseAddress, HBAPRDTEntry::DataBaseAddressUpper, FIS_TYPE_REG_H2D, FIS_REG_H2D::FISType, for(), HBA_PxIS_TFES, HBAPortPtr, i, IdentifyData, HBAPRDTEntry::InterruptOnCompletion, HBAPort::InterruptStatus, Log(), MemorySet(), PortNumber, HBACommandTable::PRDTEntry, HBACommandHeader::PRDTLength, SATAPI, HBACommandHeader::Write, and Driver::Yield().
Referenced by Configure().
ReadWrite()
bool Port::ReadWrite (uint64_t Sector, uint32_t SectorCount, uint8_t * Buffer, bool Write) inline
Definition at line 642 of file ahci.cpp.
     {
         if (this->AHCIPortType == PortType::SATAPI &&
             Write == true)
         {
             Log("SATAPI port does not support write.");
             return false;
         }
         uint32_t SectorL = (uint32_t)Sector;
         uint32_t SectorH = (uint32_t)(Sector >> 32);
         HBAPortPtr->InterruptStatus = 0xFFFFFFFF; /* Clear pending interrupt bits */
         HBACommandHeader *CommandHeader = reinterpret_cast<HBACommandHeader *>(HBAPortPtr->CommandListBase);
         CommandHeader->CommandFISLength = sizeof(FIS_REG_H2D) / sizeof(uint32_t);
         if (Write)
             CommandHeader->Write = 1;
         else
             CommandHeader->Write = 0;
         CommandHeader->PRDTLength = 1;
         HBACommandTable *CommandTable = reinterpret_cast<HBACommandTable *>(CommandHeader->CommandTableBaseAddress);
         MemorySet(CommandTable, 0, sizeof(HBACommandTable) + (CommandHeader->PRDTLength - 1) * sizeof(HBAPRDTEntry));
         CommandTable->PRDTEntry[0].DataBaseAddress = (uint32_t)(uint64_t)Buffer;
         CommandTable->PRDTEntry[0].DataBaseAddressUpper = (uint32_t)((uint64_t)Buffer >> 32);
 #pragma GCC diagnostic push
 /* conversion from 'uint32_t' {aka 'unsigned int'} to 'unsigned int:22' may change value */
 #pragma GCC diagnostic ignored "-Wconversion"
         CommandTable->PRDTEntry[0].ByteCount = (SectorCount << 9) - 1; /* 512 bytes per sector */
 #pragma GCC diagnostic pop
         CommandTable->PRDTEntry[0].InterruptOnCompletion = 1;
         FIS_REG_H2D *CommandFIS = (FIS_REG_H2D *)(&CommandTable->CommandFIS);
         CommandFIS->FISType = FIS_TYPE_REG_H2D;
         CommandFIS->CommandControl = 1;
         if (Write)
             CommandFIS->Command = ATA_CMD_WRITE_DMA_EX;
         else
             CommandFIS->Command = ATA_CMD_READ_DMA_EX;
         CommandFIS->LBA0 = (uint8_t)SectorL;
         CommandFIS->LBA1 = (uint8_t)(SectorL >> 8);
         CommandFIS->LBA2 = (uint8_t)(SectorL >> 16);
         CommandFIS->LBA3 = (uint8_t)SectorH;
         CommandFIS->LBA4 = (uint8_t)(SectorH >> 8);
         CommandFIS->LBA5 = (uint8_t)(SectorH >> 16);
         CommandFIS->DeviceRegister = 1 << 6; // LBA mode
         CommandFIS->CountLow = SectorCount & 0xFF;
         CommandFIS->CountHigh = (SectorCount >> 8) & 0xFF;
         uint64_t Spin = 0;
         while ((HBAPortPtr->TaskFileData & (ATA_DEV_BUSY | ATA_DEV_DRQ)) && Spin < 1000000)
             Spin++;
         if (Spin == 1000000)
         {
             Log("Port not responding.");
             return false;
         }
         HBAPortPtr->CommandIssue = 1;
         Spin = 0;
         int TryCount = 0;
         while (true)
         {
             if (Spin > 100000000)
             {
                 Log("Port %d not responding. (%d)",
                     this->PortNumber, TryCount);
                 Spin = 0;
                 TryCount++;
                 if (TryCount > 10)
                     return false;
             }
             if (HBAPortPtr->CommandIssue == 0)
                 break;
             Spin++;
             if (HBAPortPtr->InterruptStatus & HBA_PxIS_TFES)
             {
                 Log("Error reading/writing (%d).", Write);
                 return false;
             }
         }
         return true;
     }
References ATA_CMD_READ_DMA_EX, ATA_CMD_WRITE_DMA_EX, ATA_DEV_BUSY, ATA_DEV_DRQ, Buffer, HBAPRDTEntry::ByteCount, FIS_REG_H2D::Command, FIS_REG_H2D::CommandControl, HBACommandTable::CommandFIS, HBACommandHeader::CommandFISLength, HBAPort::CommandIssue, HBAPort::CommandListBase, HBACommandHeader::CommandTableBaseAddress, FIS_REG_H2D::CountHigh, FIS_REG_H2D::CountLow, HBAPRDTEntry::DataBaseAddress, HBAPRDTEntry::DataBaseAddressUpper, FIS_REG_H2D::DeviceRegister, FIS_TYPE_REG_H2D, FIS_REG_H2D::FISType, HBA_PxIS_TFES, HBAPortPtr, HBAPRDTEntry::InterruptOnCompletion, HBAPort::InterruptStatus, FIS_REG_H2D::LBA0, FIS_REG_H2D::LBA1, FIS_REG_H2D::LBA2, FIS_REG_H2D::LBA3, FIS_REG_H2D::LBA4, FIS_REG_H2D::LBA5, Log(), MemorySet(), HBACommandTable::PRDTEntry, HBACommandHeader::PRDTLength, SATAPI, HBAPort::TaskFileData, HBACommandHeader::Write, and SysDbg::Write().
Referenced by drvRead(), and drvWrite().
StartCMD()
void Port::StartCMD () inline
Definition at line 588 of file ahci.cpp.
     {
         while (HBAPortPtr->CommandStatus & HBA_PxCMD_CR)
             Yield();
         HBAPortPtr->CommandStatus |= HBA_PxCMD_FRE;
         HBAPortPtr->CommandStatus |= HBA_PxCMD_ST;
     }
References HBAPort::CommandStatus, HBA_PxCMD_CR, HBA_PxCMD_FRE, HBA_PxCMD_ST, HBAPortPtr, and Driver::Yield().
Referenced by Configure().
StopCMD()
void Port::StopCMD () inline
Definition at line 596 of file ahci.cpp.
     {
         HBAPortPtr->CommandStatus &= ~HBA_PxCMD_ST;
         HBAPortPtr->CommandStatus &= ~HBA_PxCMD_FRE;
         while (true)
         {
             if (HBAPortPtr->CommandStatus & HBA_PxCMD_FR)
                 continue;
             if (HBAPortPtr->CommandStatus & HBA_PxCMD_CR)
                 continue;
             break;
         }
     }
References HBAPort::CommandStatus, HBA_PxCMD_CR, HBA_PxCMD_FR, HBA_PxCMD_FRE, HBA_PxCMD_ST, and HBAPortPtr.
Referenced by Configure(), and cxx_Finalize().
Field Documentation
AHCIPortType
PortType Port::AHCIPortType
Definition at line 566 of file ahci.cpp.
Buffer
uint8_t* Port::Buffer
Definition at line 568 of file ahci.cpp.
Referenced by ReadWrite().
HBAPortPtr
HBAPort* Port::HBAPortPtr
Definition at line 567 of file ahci.cpp.
Referenced by Configure(), Identify(), ReadWrite(), StartCMD(), and StopCMD().
IdentifyData
ATA_IDENTIFY* Port::IdentifyData
Definition at line 570 of file ahci.cpp.
Referenced by Identify().
PortNumber
uint8_t Port::PortNumber
Definition at line 569 of file ahci.cpp.
Referenced by Identify(), and Port().
The documentation for this class was generated from the following file:
Drivers/storage/ahci/ahci.cpp