Fennix: Userspace/apps/base/busybox/coreutils/rmdir.c File Reference
rmdir.c File Reference
#include "libbb.h"
Macros
#define PARENTS (1 << 0)
#define VERBOSE ((1 << 1) * ENABLE_FEATURE_VERBOSE)
#define IGNORE_NON_EMPTY ((1 << 2) * ENABLE_LONG_OPTS)
Functions
int rmdir_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
IGNORE_NON_EMPTY
#define IGNORE_NON_EMPTY ((1 << 2) * ENABLE_LONG_OPTS)
Definition at line 41 of file rmdir.c.
PARENTS
#define PARENTS (1 << 0)
Definition at line 39 of file rmdir.c.
VERBOSE
#define VERBOSE ((1 << 1) * ENABLE_FEATURE_VERBOSE)
Definition at line 40 of file rmdir.c.
Function Documentation
rmdir_main()
int rmdir_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 44 of file rmdir.c.
 {
     int status = EXIT_SUCCESS;
     int flags;
     char *path;
     flags = getopt32long(argv, "pv",
         "parents\0"                  No_argument "p"
         /* Debian etch: many packages fail to be purged or installed
          * because they desperately want this option: */
         "ignore-fail-on-non-empty\0" No_argument "\xff"
         IF_FEATURE_VERBOSE(
         "verbose\0"                  No_argument "v"
         )
     );
     argv += optind;
     if (!*argv) {
         bb_show_usage();
     }
     do {
         path = *argv;
         while (1) {
             if (flags & VERBOSE) {
                 printf("rmdir: removing directory, '%s'\n", path);
             }
             if (rmdir(path) < 0) {
 #if ENABLE_LONG_OPTS
                 if ((flags & IGNORE_NON_EMPTY) && errno == ENOTEMPTY)
                     break;
 #endif
                 bb_perror_msg("'%s'", path);  /* Match gnu rmdir msg. */
                 status = EXIT_FAILURE;
             } else if (flags & PARENTS) {
                 /* Note: path was not "" since rmdir succeeded. */
                 path = dirname(path);
                 /* Path is now just the parent component.  Dirname
                  * returns "." if there are no parents.
                  */
                 if (NOT_LONE_CHAR(path, '.')) {
                     continue;
                 }
             }
             break;
         }
     } while (*++argv);
     return status;
 }
References argv, bb_perror_msg(), bb_show_usage(), dirname, ENOTEMPTY, errno, EXIT_FAILURE, EXIT_SUCCESS, flags, getopt32long, IGNORE_NON_EMPTY, No_argument, NOT_LONE_CHAR, optind, PARENTS, printf, rmdir(), status, and VERBOSE.