Fennix Userspace: Userspace/apps/base/busybox/debianutils/start_stop_daemon.c File Reference
start_stop_daemon.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct pid_list
struct globals
Macros
#define WANT_PIDFILE 1
#define QUIET (option_mask32 & OPT_QUIET)
#define TEST (option_mask32 & OPT_TEST)
#define G (*(struct globals*)bb_common_bufsiz1)
#define userspec (G.userspec)
#define cmdname (G.cmdname)
#define execname (G.execname)
#define pidfile (G.pidfile)
#define user_id (G.user_id)
#define signal_nr (G.signal_nr)
#define INIT_G()
#define GETOPT32 getopt32
#define LONGOPTS
Enumerations
enum {
CTX_STOP = (1 << 0) , CTX_START = (1 << 1) , OPT_BACKGROUND = (1 << 2) , OPT_QUIET = (1 << 3) ,
OPT_TEST = (1 << 4) , OPT_MAKEPID = (1 << 5) , OPT_a = (1 << 6) , OPT_n = (1 << 7) ,
OPT_s = (1 << 8) , OPT_u = (1 << 9) , OPT_c = (1 << 10) , OPT_x = (1 << 11) ,
OPT_p = (1 << 12) , OPT_OKNODO = (1 << 13) * ENABLE_FEATURE_START_STOP_DAEMON_FANCY , OPT_VERBOSE = (1 << 14) * ENABLE_FEATURE_START_STOP_DAEMON_FANCY , OPT_NICELEVEL = (1 << 15) * ENABLE_FEATURE_START_STOP_DAEMON_FANCY
}
Functions
static int pid_is_exec (pid_t pid)
static int pid_is_name (pid_t pid)
static int pid_is_user (int pid)
static void check (int pid)
static void do_pidfile (void)
static void do_procinit (void)
static int do_stop (void)
int start_stop_daemon_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Data Structure Documentation
pid_list
struct pid_list
Definition at line 124 of file start_stop_daemon.c.
Data Fields
struct pid_list * next
pid_t pid
Macro Definition Documentation
cmdname
#define cmdname (G.cmdname)
Definition at line 166 of file start_stop_daemon.c.
execname
#define execname (G.execname)
Definition at line 167 of file start_stop_daemon.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 164 of file start_stop_daemon.c.
GETOPT32
#define GETOPT32 getopt32
Definition at line 403 of file start_stop_daemon.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    user_id = -1; \
    signal_nr = 15; \
} while (0)
Definition at line 171 of file start_stop_daemon.c.
LONGOPTS
#define LONGOPTS
Definition at line 404 of file start_stop_daemon.c.
pidfile
#define pidfile (G.pidfile)
Definition at line 168 of file start_stop_daemon.c.
QUIET
#define QUIET (option_mask32 & OPT_QUIET)
Definition at line 147 of file start_stop_daemon.c.
signal_nr
#define signal_nr (G.signal_nr)
Definition at line 170 of file start_stop_daemon.c.
TEST
#define TEST (option_mask32 & OPT_TEST)
Definition at line 148 of file start_stop_daemon.c.
user_id
#define user_id (G.user_id)
Definition at line 169 of file start_stop_daemon.c.
userspec
#define userspec (G.userspec)
Definition at line 165 of file start_stop_daemon.c.
WANT_PIDFILE
#define WANT_PIDFILE 1
Definition at line 120 of file start_stop_daemon.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CTX_STOP
CTX_START
OPT_BACKGROUND
OPT_QUIET
OPT_TEST
OPT_MAKEPID
OPT_a
OPT_n
OPT_s
OPT_u
OPT_c
OPT_x
OPT_p
OPT_OKNODO
OPT_VERBOSE
OPT_NICELEVEL
Definition at line 129 of file start_stop_daemon.c.
      {
     CTX_STOP       = (1 <<  0),
     CTX_START      = (1 <<  1),
     OPT_BACKGROUND = (1 <<  2), // -b
     OPT_QUIET      = (1 <<  3), // -q
     OPT_TEST       = (1 <<  4), // -t
     OPT_MAKEPID    = (1 <<  5), // -m
     OPT_a          = (1 <<  6), // -a
     OPT_n          = (1 <<  7), // -n
     OPT_s          = (1 <<  8), // -s
     OPT_u          = (1 <<  9), // -u
     OPT_c          = (1 << 10), // -c
     OPT_x          = (1 << 11), // -x
     OPT_p          = (1 << 12), // -p
     OPT_OKNODO     = (1 << 13) * ENABLE_FEATURE_START_STOP_DAEMON_FANCY, // -o
     OPT_VERBOSE    = (1 << 14) * ENABLE_FEATURE_START_STOP_DAEMON_FANCY, // -v
     OPT_NICELEVEL  = (1 << 15) * ENABLE_FEATURE_START_STOP_DAEMON_FANCY, // -N
 };
Function Documentation
check()
static void check (int pid) static
Definition at line 257 of file start_stop_daemon.c.
 {
     struct pid_list *p;
     if (execname && !pid_is_exec(pid)) {
         return;
     }
     if (cmdname && !pid_is_name(pid)) {
         return;
     }
     if (userspec && !pid_is_user(pid)) {
         return;
     }
     p = xmalloc(sizeof(*p));
     p->next = G.found_procs;
     p->pid = pid;
     G.found_procs = p;
 }
References cmdname, execname, G, p, pid, pid_is_exec(), pid_is_name(), pid_is_user(), userspec, and xmalloc.
Referenced by apply_one_hunk(), d4_recv_raw_packet(), do_pidfile(), do_procinit(), getjob(), M_CheckParm(), M_CheckParmWithArgs(), M_ParmExists(), P_FindHighestCeilingSurrounding(), P_FindHighestFloorSurrounding(), P_FindLowestCeilingSurrounding(), P_FindLowestFloorSurrounding(), P_FindMinSurroundingLight(), P_FindNextHighestFloor(), P_RecursiveSound(), PIT_VileCheck(), R_FindPlane(), and R_InitSpriteDefs().
do_pidfile()
static void do_pidfile (void) static
Definition at line 276 of file start_stop_daemon.c.
 {
     FILE *f;
     unsigned pid;
     f = fopen_for_read(pidfile);
     if (f) {
         if (fscanf(f, "%u", &pid) == 1)
             check(pid);
         fclose(f);
     } else if (errno != ENOENT)
         bb_perror_msg_and_die("open pidfile %s", pidfile);
 }
References bb_perror_msg_and_die(), check(), ENOENT, errno, f, fclose(), fopen_for_read(), fscanf(), pid, and pidfile.
Referenced by do_procinit().
do_procinit()
static void do_procinit (void) static
Definition at line 290 of file start_stop_daemon.c.
 {
     DIR *procdir;
     struct dirent *entry;
     int pid;
     if (pidfile) {
         do_pidfile();
         return;
     }
     procdir = xopendir("/proc");
     pid = 0;
     while (1) {
         errno = 0; /* clear any previous error */
         entry = readdir(procdir);
 // TODO: this check is too generic, it's better
 // to check for exact errno(s) which mean that we got stale entry
         if (errno) /* Stale entry, process has died after opendir */
             continue;
         if (!entry) /* EOF, no more entries */
             break;
         pid = bb_strtou(entry->d_name, NULL, 10);
         if (errno) /* NaN */
             continue;
         check(pid);
     }
     closedir(procdir);
     if (!pid)
         bb_simple_error_msg_and_die("nothing in /proc - not mounted?");
 }
References bb_simple_error_msg_and_die(), bb_strtou(), check(), closedir(), do_pidfile(), errno, NULL, pid, pidfile, readdir(), and xopendir().
Referenced by start_stop_daemon_main().
do_stop()
static int do_stop (void) static
Definition at line 323 of file start_stop_daemon.c.
 {
     char *what;
     struct pid_list *p;
     int killed = 0;
     if (cmdname) {
         if (ENABLE_FEATURE_CLEAN_UP) what = xstrdup(cmdname);
         if (!ENABLE_FEATURE_CLEAN_UP) what = cmdname;
     } else if (execname) {
         if (ENABLE_FEATURE_CLEAN_UP) what = xstrdup(execname);
         if (!ENABLE_FEATURE_CLEAN_UP) what = execname;
     } else if (pidfile) {
         what = xasprintf("process in pidfile '%s'", pidfile);
     } else if (userspec) {
         what = xasprintf("process(es) owned by '%s'", userspec);
     } else {
         bb_simple_error_msg_and_die("internal error, please report");
     }
     if (!G.found_procs) {
         if (!QUIET)
             printf("no %s found; none killed\n", what);
         killed = -1;
         goto ret;
     }
     for (p = G.found_procs; p; p = p->next) {
         if (kill(p->pid, TEST ? 0 : signal_nr) == 0) {
             killed++;
         } else {
             bb_perror_msg("warning: killing process %u", (unsigned)p->pid);
             p->pid = 0;
             if (TEST) {
                 /* Example: -K --test --pidfile PIDFILE detected
                  * that PIDFILE's pid doesn't exist */
                 killed = -1;
                 goto ret;
             }
         }
     }
     if (!QUIET && killed) {
         printf("stopped %s (pid", what);
         for (p = G.found_procs; p; p = p->next)
             if (p->pid)
                 printf(" %u", (unsigned)p->pid);
         puts(")");
     }
  ret:
     if (ENABLE_FEATURE_CLEAN_UP)
         free(what);
     return killed;
 }
References bb_perror_msg(), bb_simple_error_msg_and_die(), cmdname, execname, free, G, kill(), p, pidfile, printf(), puts(), QUIET, signal_nr, TEST, userspec, xasprintf(), and xstrdup().
Referenced by start_stop_daemon_main().
pid_is_exec()
static int pid_is_exec (pid_t pid) static
Definition at line 196 of file start_stop_daemon.c.
 {
     ssize_t bytes;
     char buf[sizeof("/proc/%u/cmdline") + sizeof(int)*3];
     char *procname, *exelink;
     int match;
     procname = buf + sprintf(buf, "/proc/%u/exe", (unsigned)pid) - 3;
     exelink = xmalloc_readlink(buf);
     match = (exelink && strcmp(execname, exelink) == 0);
     free(exelink);
     if (match)
         return match;
     strcpy(procname, "cmdline");
     bytes = open_read_close(buf, G.execname_cmpbuf, G.execname_sizeof);
     if (bytes > 0) {
         G.execname_cmpbuf[bytes] = '\0';
         return strcmp(execname, G.execname_cmpbuf) == 0;
     }
     return 0;
 }
References buf, execname, free, G, match(), open_read_close(), pid, sprintf(), strcmp, strcpy(), and xmalloc_readlink().
Referenced by check().
pid_is_name()
static int pid_is_name (pid_t pid) static
Definition at line 221 of file start_stop_daemon.c.
 {
     /* /proc/PID/stat is "PID (comm_15_bytes_max) ..." */
     char buf[32]; /* should be enough */
     char *p, *pe;
     sprintf(buf, "/proc/%u/stat", (unsigned)pid);
     if (open_read_close(buf, buf, sizeof(buf) - 1) < 0)
         return 0;
     buf[sizeof(buf) - 1] = '\0'; /* paranoia */
     p = strchr(buf, '(');
     if (!p)
         return 0;
     pe = strrchr(++p, ')');
     if (!pe)
         return 0;
     *pe = '\0';
     /* we require comm to match and to not be truncated */
     /* in Linux, if comm is 15 chars, it may be a truncated
      * name, so we don't allow that to match */
     if (strlen(p) >= COMM_LEN - 1) /* COMM_LEN is 16 */
         return 0;
     return strcmp(p, cmdname) == 0;
 }
References buf, cmdname, COMM_LEN, open_read_close(), p, pid, sprintf(), strchr(), strcmp, strlen(), and strrchr().
Referenced by check().
pid_is_user()
static int pid_is_user (int pid) static
Definition at line 246 of file start_stop_daemon.c.
 {
     struct stat sb;
     char buf[sizeof("/proc/") + sizeof(int)*3];
     sprintf(buf, "/proc/%u", (unsigned)pid);
     if (stat(buf, &sb) != 0)
         return 0;
     return (sb.st_uid == (uid_t)user_id);
 }
References buf, pid, sprintf(), stat::st_uid, stat(), and user_id.
Referenced by check().
start_stop_daemon_main()
int start_stop_daemon_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 408 of file start_stop_daemon.c.
 {
     unsigned opt;
     char *signame;
     char *startas = NULL;
     char *chuid;
 #if ENABLE_FEATURE_START_STOP_DAEMON_FANCY
 //  char *retry_arg = NULL;
 //  int retries = -1;
     char *opt_N;
 #endif
     INIT_G();
     opt = GETOPT32(argv, "^"
         "KSbqtma:n:s:u:c:x:p:"
         IF_FEATURE_START_STOP_DAEMON_FANCY("ovN:R:")
             /* -K or -S is required; they are mutually exclusive */
             /* -p is required if -m is given */
             /* -xpun (at least one) is required if -K is given */
 //          /* -xa (at least one) is required if -S is given */
 //WRONG: "start-stop-daemon -S -- sleep 5" is a valid invocation
             /* -q turns off -v */
             "\0"
             "K:S:K--S:S--K:m?p:K?xpun"
             IF_FEATURE_START_STOP_DAEMON_FANCY("q-v"),
         LONGOPTS
         &startas, &cmdname, &signame, &userspec, &chuid, &execname, &pidfile
         IF_FEATURE_START_STOP_DAEMON_FANCY(,&opt_N)
         /* We accept and ignore -R <param> / --retry <param> */
         IF_FEATURE_START_STOP_DAEMON_FANCY(,NULL)
     );
     if (opt & OPT_s) {
         signal_nr = get_signum(signame);
         if (signal_nr < 0) bb_show_usage();
     }
     //argc -= optind;
     argv += optind;
 // ARGS contains zeroth arg if -x/-a is not given, else it starts with 1st arg.
 // These will try to execute "[/bin/]sleep 5":
 // "start-stop-daemon -S               -- sleep 5"
 // "start-stop-daemon -S -x /bin/sleep -- 5"
 // "start-stop-daemon -S -a sleep      -- 5"
 // NB: -n option does _not_ behave in this way: this will try to execute "5":
 // "start-stop-daemon -S -n sleep      -- 5"
     if (opt & CTX_START) {
         if (!execname) { /* -x is not given */
             execname = startas;
             if (!execname) { /* neither -x nor -a is given */
                 execname = argv[0];
                 if (!execname)
                     bb_show_usage();
                 argv++;
             }
         }
         if (!startas) /* -a is not given: use -x EXECUTABLE or argv[0] */
             startas = execname;
         *--argv = startas;
     }
     if (execname) {
         G.execname_sizeof = strlen(execname) + 1;
         G.execname_cmpbuf = xmalloc(G.execname_sizeof + 1);
     }
 //  IF_FEATURE_START_STOP_DAEMON_FANCY(
 //      if (retry_arg)
 //          retries = xatoi_positive(retry_arg);
 //  )
     if (userspec) {
         user_id = bb_strtou(userspec, NULL, 10);
         if (errno)
             user_id = xuname2uid(userspec);
     }
     /* Both start and stop need to know current processes */
     do_procinit();
     if (opt & CTX_STOP) {
         int i = do_stop();
         return (opt & OPT_OKNODO) ? 0 : (i <= 0);
     }
     /* else: CTX_START (-S). execname can't be NULL. */
     if (G.found_procs) {
         if (!QUIET)
             printf("%s is already running\n", execname);
         return !(opt & OPT_OKNODO);
     }
 #ifdef OLDER_VERSION_OF_X
     if (execname)
         xstat(execname, &G.execstat);
 #endif
     if (opt & OPT_BACKGROUND) {
         /* Daemons usually call bb_daemonize_or_rexec(), but SSD can do
          * without: SSD is not itself a daemon, it _execs_ a daemon.
          * The usual NOMMU problem of "child can't run indefinitely,
          * it must exec" does not bite us: we exec anyway.
          *
          * bb_daemonize(DAEMON_DEVNULL_STDIO | DAEMON_CLOSE_EXTRA_FDS | DAEMON_DOUBLE_FORK)
          * can be used on MMU systems, but use of vfork()
          * is preferable since we want to create pidfile
          * _before_ parent returns, and vfork() on Linux
          * ensures that (by blocking parent until exec in the child).
          */
         pid_t pid = xvfork();
         if (pid != 0) {
             /* Parent */
             /* why _exit? the child may have changed the stack,
              * so "return 0" may do bad things
              */
             _exit_SUCCESS();
         }
         /* Child */
         setsid(); /* detach from controlling tty */
         /* Redirect stdio to /dev/null, close extra FDs */
         bb_daemon_helper(DAEMON_DEVNULL_STDIO + DAEMON_CLOSE_EXTRA_FDS);
         /* On Linux, session leader can acquire ctty
          * unknowingly, by opening a tty.
          * Prevent this: stop being a session leader.
          */
         pid = xvfork();
         if (pid != 0)
             _exit_SUCCESS(); /* Parent */
     }
     if (opt & OPT_MAKEPID) {
         /* User wants _us_ to make the pidfile */
         write_pidfile(pidfile);
     }
 #if ENABLE_FEATURE_START_STOP_DAEMON_FANCY
     if (opt & OPT_NICELEVEL) {
         /* Set process priority (must be before OPT_c) */
         int prio = getpriority(PRIO_PROCESS, 0) + xatoi_range(opt_N, INT_MIN/2, INT_MAX/2);
         if (setpriority(PRIO_PROCESS, 0, prio) < 0) {
             bb_perror_msg_and_die("setpriority(%d)", prio);
         }
     }
 #endif
     if (opt & OPT_c) {
         struct bb_uidgid_t ugid;
         parse_chown_usergroup_or_die(&ugid, chuid);
         if (ugid.uid != (uid_t) -1L) {
             struct passwd *pw = xgetpwuid(ugid.uid);
             if (ugid.gid != (gid_t) -1L)
                 pw->pw_gid = ugid.gid;
             /* initgroups, setgid, setuid: */
             change_identity(pw);
         } else if (ugid.gid != (gid_t) -1L) {
             xsetgid(ugid.gid);
             setgroups(1, &ugid.gid);
         }
     }
     /* Try:
      * strace -oLOG start-stop-daemon -S -x /bin/usleep -a qwerty 500000
      * should exec "/bin/usleep", but argv[0] should be "qwerty":
      */
     execvp(execname, argv);
     bb_perror_msg_and_die("can't execute '%s'", startas);
 }
References _exit_SUCCESS(), argv, bb_daemon_helper, bb_perror_msg_and_die(), bb_show_usage(), bb_strtou(), change_identity(), cmdname, CTX_START, CTX_STOP, DAEMON_CLOSE_EXTRA_FDS, DAEMON_DEVNULL_STDIO, do_procinit(), do_stop(), errno, execname, execvp(), G, get_signum(), GETOPT32, getpriority(), bb_uidgid_t::gid, i, INIT_G, INT_MAX, INT_MIN, LONGOPTS, NULL, opt, OPT_BACKGROUND, OPT_c, OPT_MAKEPID, OPT_NICELEVEL, OPT_OKNODO, OPT_s, optind, parse_chown_usergroup_or_die(), pid, pidfile, printf(), PRIO_PROCESS, pw, passwd::pw_gid, QUIET, setgroups(), setpriority(), setsid(), signal_nr, strlen(), bb_uidgid_t::uid, user_id, userspec, write_pidfile(), xgetpwuid(), xmalloc, xsetgid(), xstat(), xuname2uid(), and xvfork.
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING