Fennix: Userspace/apps/base/bash/support/man2html.c File Reference
man2html.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <ctype.h>
#include <sys/types.h>
#include <time.h>
#include <sys/time.h>
#include <errno.h>
Data Structures
struct STRDEF
struct INTDEF
struct TABLEITEM
struct TABLEROW
Macros
#define NROFF 0
#define NULL_TERMINATED(n) ((n) + 1)
#define HUGE_STR_MAX 10000
#define LARGE_STR_MAX 2000
#define MED_STR_MAX 500
#define SMALL_STR_MAX 100
#define TINY_STR_MAX 10
#define MAX_MAN_PATHS 100 /* Max number of directories */
#define MAX_ZCATS 10 /* Max number of zcat style programs */
#define MAX_WORDLIST 100
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#define EXIT_USAGE 2
#define TIMEFORMAT "%d %B %Y %T %Z"
#define BL_DESC_LIST 1
#define BL_BULLET_LIST 2
#define BL_ENUM_LIST 4
#define BD_LITERAL 1
#define BD_INDENT 2
#define INDEXFILE "/tmp/manindex.list"
#define V(A, B) ((A)*256+(B))
#define FO0 ""
#define FC0 ""
#define FO1 "<I>"
#define FC1 "</I>"
#define FO2 "<B>"
#define FC2 "</B>"
#define FO3 "<TT>"
#define FC3 "</TT>"
#define SKIPEOL while (*c && *c++!='\n')
#define FLUSHIBP if (ibp) { intbuff[ibp]=0; out_html(intbuff); ibp=0; }
Typedefs
typedef struct STRDEF STRDEF
typedef struct INTDEF INTDEF
typedef struct TABLEITEM TABLEITEM
typedef struct TABLEROW TABLEROW
Functions
static char * strerror (int e)
static char * strgrow (char *old, int len)
static char * stralloc (int len)
void * xmalloc (size_t size)
static char * strduplicate (char *from)
static char * strmaxcpy (char *to, char *from, int n)
static char * strmaxcat (char *to, char *from, int n)
static char * strlimitcpy (char *to, char *from, int n, int limit)
static char * escape_input (char *str)
static void usage (void)
static char * scan_troff (char *c, int san, char **result)
static char * scan_troff_mandoc (char *c, int san, char **result)
static void print_sig (void)
static char * expand_char (int nr)
static char * expand_string (int nr)
static char * read_man_page (char *filename)
static void add_links (char *c)
static void out_html (char *c)
static char * change_to_font (int nr)
static char * change_to_size (int nr)
static char * scan_escape (char *c)
static void clear_table (TABLEROW *table)
static char * scan_expression (char *c, int *result)
static char * scan_format (char *c, TABLEROW **result, int *maxcol)
static TABLEROW * next_row (TABLEROW *tr)
static char * scan_table (char *c)
static void trans_char (char *c, char s, char t)
static char * unescape (char *c)
static char * fill_words (char *c, char *words[], int *n)
static char * lookup_abbrev (char *c)
static void add_to_index (int level, char *item)
static char * skip_till_newline (char *c)
static void outputPageHeader (char *l, char *c, char *r)
static void outputPageFooter (char *l, char *c, char *r)
static char * scan_request (char *c)
static void flush (void)
int main (int argc, char **argv)
Variables
static char location_base [NULL_TERMINATED(MED_STR_MAX)] = ""
static char th_page_and_sec [128] = { '\0' }
static char th_datestr [128] = { '\0' }
static char th_version [128] = { '\0' }
char * signature = "<HR>\nThis document was created by man2html from %s.<BR>\nTime: %s\n"
char * manpage
static char NEWLINE [2] = "\n"
static char idxlabel [6] = "ixAAA"
static char * fname
static FILE * idxfile
static STRDEF * chardef
static STRDEF * strdef
static STRDEF * defdef
static INTDEF * intdef
static INTDEF standardint []
static STRDEF standardstring []
static STRDEF standardchar []
static char eqndelimopen = 0
static char eqndelimclose = 0
static char escapesym = '\\'
static char nobreaksym = '\''
static char controlsym = '.'
static char fieldsym = 0
static char padsym = 0
static char * buffer = NULL
static int buffpos = 0
static int buffmax = 0
static int scaninbuff = 0
static int itemdepth = 0
static int dl_set [20] = {0}
static int still_dd = 0
static int tabstops [20] = {8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96}
static int maxtstop = 12
static int curpos = 0
static char ** argument = NULL
static char charb [TINY_STR_MAX]
static char outbuffer [NULL_TERMINATED(HUGE_STR_MAX)]
static int obp = 0
static int no_newline_output = 0
static int newline_for_fun = 0
static int output_possible = 0
static int out_length = 0
static int current_font = 0
static int current_size = 0
static int fillout = 1
static char * switchfont [16]
static char sizebuf [200]
static int asint = 0
static int intresult = 0
static int skip_escape = 0
static int single_escape = 0
static TABLEITEM emptyfield = {NULL, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, NULL}
static char * tableopt []
static int tableoptl [] = {6, 6, 3, 6, 9, 3, 8, 5, 0}
static char itemreset [20] = "\\fR\\s0"
static char * abbrev_list []
static char manidx [NULL_TERMINATED(HUGE_STR_MAX)]
static int subs = 0
static int mip = 0
static char label [5] = "lbAA"
static int ifelseval = 0
static int contained_tab = 0
static int mandoc_line = 0
Data Structure Documentation
STRDEF
struct STRDEF
Definition at line 279 of file man2html.c.
Data Fields
STRDEF * next
int nr
int slen
char * st
INTDEF
struct INTDEF
Definition at line 286 of file man2html.c.
Data Fields
int incr
INTDEF * next
int nr
int val
TABLEITEM
struct TABLEITEM
Definition at line 1211 of file man2html.c.
Data Fields
int align
int colspan
char * contents
int font
TABLEITEM * next
int rowspan
int size
int space
int valign
int vleft
int vright
int width
TABLEROW
struct TABLEROW
Definition at line 1222 of file man2html.c.
Data Fields
TABLEITEM * first
TABLEROW * next
TABLEROW * prev
Macro Definition Documentation
BD_INDENT
#define BD_INDENT 2
Definition at line 124 of file man2html.c.
BD_LITERAL
#define BD_LITERAL 1
Definition at line 123 of file man2html.c.
BL_BULLET_LIST
#define BL_BULLET_LIST 2
Definition at line 119 of file man2html.c.
BL_DESC_LIST
#define BL_DESC_LIST 1
Definition at line 118 of file man2html.c.
BL_ENUM_LIST
#define BL_ENUM_LIST 4
Definition at line 120 of file man2html.c.
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 98 of file man2html.c.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 95 of file man2html.c.
EXIT_USAGE
#define EXIT_USAGE 2
Definition at line 101 of file man2html.c.
FC0
#define FC0 ""
Definition at line 823 of file man2html.c.
FC1
#define FC1 "</I>"
Definition at line 825 of file man2html.c.
FC2
#define FC2 "</B>"
Definition at line 827 of file man2html.c.
FC3
#define FC3 "</TT>"
Definition at line 829 of file man2html.c.
FLUSHIBP
#define FLUSHIBP if (ibp) { intbuff[ibp]=0; out_html(intbuff); ibp=0; }
FO0
#define FO0 ""
Definition at line 822 of file man2html.c.
FO1
#define FO1 "<I>"
Definition at line 824 of file man2html.c.
FO2
#define FO2 "<B>"
Definition at line 826 of file man2html.c.
FO3
#define FO3 "<TT>"
Definition at line 828 of file man2html.c.
HUGE_STR_MAX
#define HUGE_STR_MAX 10000
Definition at line 84 of file man2html.c.
INDEXFILE
#define INDEXFILE "/tmp/manindex.list"
Definition at line 296 of file man2html.c.
LARGE_STR_MAX
#define LARGE_STR_MAX 2000
Definition at line 85 of file man2html.c.
MAX_MAN_PATHS
#define MAX_MAN_PATHS 100 /* Max number of directories */
Definition at line 90 of file man2html.c.
MAX_WORDLIST
#define MAX_WORDLIST 100
Definition at line 92 of file man2html.c.
MAX_ZCATS
#define MAX_ZCATS 10 /* Max number of zcat style programs */
Definition at line 91 of file man2html.c.
MED_STR_MAX
#define MED_STR_MAX 500
Definition at line 86 of file man2html.c.
NROFF
#define NROFF 0
Definition at line 69 of file man2html.c.
NULL_TERMINATED
#define NULL_TERMINATED (n) ((n) + 1)
Definition at line 82 of file man2html.c.
SKIPEOL
#define SKIPEOL while (*c && *c++!='\n')
Definition at line 940 of file man2html.c.
SMALL_STR_MAX
#define SMALL_STR_MAX 100
Definition at line 87 of file man2html.c.
TIMEFORMAT
#define TIMEFORMAT "%d %B %Y %T %Z"
Definition at line 113 of file man2html.c.
TINY_STR_MAX
#define TINY_STR_MAX 10
Definition at line 88 of file man2html.c.
V
#define V (A, B) ((A)*256+(B))
Definition at line 304 of file man2html.c.
Typedef Documentation
INTDEF
typedef struct INTDEF INTDEF
Definition at line 266 of file man2html.c.
STRDEF
typedef struct STRDEF STRDEF
Definition at line 266 of file man2html.c.
TABLEITEM
typedef struct TABLEITEM TABLEITEM
Definition at line 946 of file man2html.c.
TABLEROW
typedef struct TABLEROW TABLEROW
Definition at line 1218 of file man2html.c.
Function Documentation
add_links()
static void add_links (char * c) static
Definition at line 559 of file man2html.c.
 {
     int     i, j, nr;
     char   *f, *g, *h;
     char   *idtest[6];  /* url, mailto, www, ftp, manpage */
     out_length += strlen(c);
     /* search for (section) */
     nr = 0;
     idtest[0] = strstr(c + 1, "://");
     idtest[1] = strchr(c + 1, '@');
     idtest[2] = strstr(c, "www.");
     idtest[3] = strstr(c, "ftp.");
 #if 0
     idtest[4] = strchr(c + 1, '(');
 #else
     idtest[4] = 0;
 #endif
     idtest[5] = strstr(c + 1, ".h&gt;");
     for (i = 0; i < 6; i++)
         nr += (idtest[i] != NULL);
     while (nr) {
         j = -1;
         for (i = 0; i < 6; i++)
             if (idtest[i] && (j < 0 || idtest[i] < idtest[j]))
                 j = i;
         switch (j) {
         case 5: /* <name.h> */
             f = idtest[5];
             h = f + 2;
             g = f;
             while (g > c && g[-1] != ';')
                 g--;
             if (g != c) {
                 char    t;
                 t = *g;
                 *g = '\0';
                 fputs(c, stdout);
                 *g = t;
                 *h = '\0';
                 printf("<A HREF=\"file:/usr/include/%s\">%s</A>&gt;", g, g);
                 c = f + 6;
             } else {
                 f[5] = '\0';
                 fputs(c, stdout);
                 f[5] = ';';
                 c = f + 5;
             }
             break;
         case 4: /* manpage */
 #if 0
             f = idtest[j];
             /* check section */
             g = strchr(f, ')');
             if (g && f - g < 6 && (isalnum(f[-1]) || f[-1] == '>') &&
                 ((isdigit(f[1]) && f[1] != '0' &&
                   (f[2] == ')' || (isalpha(f[2]) && f[3] == ')') || f[2] == 'X')) ||
                (f[2] == ')' && (f[1] == 'n' || f[1] == 'l')))) {
                 /* this might be a link */
                 h = f - 1;
                 /* skip html makeup */
                 while (h > c && *h == '>') {
                     while (h != c && *h != '<')
                         h--;
                     if (h != c)
                         h--;
                 }
                 if (isalnum(*h)) {
                     char    t, sec, subsec, *e;
                     e = h + 1;
                     sec = f[1];
                     subsec = f[2];
                     if ((subsec == 'X' && f[3] != ')') || subsec == ')')
                         subsec = '\0';
                     while (h > c && (isalnum(h[-1]) || h[-1] == '_' ||
                           h[-1] == '-' || h[-1] == '.'))
                         h--;
                     t = *h;
                     *h = '\0';
                     fputs(c, stdout);
                     *h = t;
                     t = *e;
                     *e = '\0';
                     if (subsec)
                         printf("<A HREF=\""
                                CGIBASE
                           "?man%c/%s.%c%c\">%s</A>",
                                sec, h, sec, tolower(subsec), h);
                     else
                         printf("<A HREF=\""
                                CGIBASE
                             "?man%c/%s.%c\">%s</A>",
                                sec, h, sec, h);
                     *e = t;
                     c = e;
                 }
             }
             *f = '\0';
             fputs(c, stdout);
             *f = '(';
             idtest[4] = f - 1;
             c = f;
 #endif
             break;  /* manpage */
         case 3: /* ftp */
         case 2: /* www */
             g = f = idtest[j];
             while (*g && (isalnum(*g) || *g == '_' || *g == '-' || *g == '+' ||
                       *g == '.'))
                 g++;
             if (g[-1] == '.')
                 g--;
             if (g - f > 4) {
                 char    t;
                 t = *f;
                 *f = '\0';
                 fputs(c, stdout);
                 *f = t;
                 t = *g;
                 *g = '\0';
                 printf("<A HREF=\"%s://%s\">%s</A>", (j == 3 ? "ftp" : "http"),
                        f, f);
                 *g = t;
                 c = g;
             } else {
                 f[3] = '\0';
                 fputs(c, stdout);
                 c = f + 3;
                 f[3] = '.';
             }
             break;
         case 1: /* mailto */
             g = f = idtest[1];
             while (g > c && (isalnum(g[-1]) || g[-1] == '_' || g[-1] == '-' ||
                   g[-1] == '+' || g[-1] == '.' || g[-1] == '%'))
                 g--;
             h = f + 1;
             while (*h && (isalnum(*h) || *h == '_' || *h == '-' || *h == '+' ||
                       *h == '.'))
                 h++;
             if (*h == '.')
                 h--;
             if (h - f > 4 && f - g > 1) {
                 char    t;
                 t = *g;
                 *g = '\0';
                 fputs(c, stdout);
                 *g = t;
                 t = *h;
                 *h = '\0';
                 printf("<A HREF=\"mailto:%s\">%s</A>", g, g);
                 *h = t;
                 c = h;
             } else {
                 *f = '\0';
                 fputs(c, stdout);
                 *f = '@';
                 idtest[1] = c;
                 c = f;
             }
             break;
         case 0: /* url */
             g = f = idtest[0];
             while (g > c && isalpha(g[-1]) && islower(g[-1]))
                 g--;
             h = f + 3;
             while (*h && !isspace(*h) && *h != '<' && *h != '>' && *h != '"' &&
                    *h != '&')
                 h++;
             if (f - g > 2 && f - g < 7 && h - f > 3) {
                 char    t;
                 t = *g;
                 *g = '\0';
                 fputs(c, stdout);
                 *g = t;
                 t = *h;
                 *h = '\0';
                 printf("<A HREF=\"%s\">%s</A>", g, g);
                 *h = t;
                 c = h;
             } else {
                 f[1] = '\0';
                 fputs(c, stdout);
                 f[1] = '/';
                 c = f + 1;
             }
             break;
         default:
             break;
         }
         nr = 0;
         if (idtest[0] && idtest[0] < c)
             idtest[0] = strstr(c + 1, "://");
         if (idtest[1] && idtest[1] < c)
             idtest[1] = strchr(c + 1, '@');
         if (idtest[2] && idtest[2] < c)
             idtest[2] = strstr(c, "www.");
         if (idtest[3] && idtest[3] < c)
             idtest[3] = strstr(c, "ftp.");
         if (idtest[4] && idtest[4] < c)
             idtest[4] = strchr(c + 1, '(');
         if (idtest[5] && idtest[5] < c)
             idtest[5] = strstr(c + 1, ".h&gt;");
         for (i = 0; i < 6; i++)
             nr += (idtest[i] != NULL);
     }
     fputs(c, stdout);
 }
References c, f, fputs(), g, i, isalnum(), isalpha, isdigit, islower, isspace, j, NULL, out_length, printf, stdout, strchr(), strlen(), strstr(), t, and tolower.
Referenced by out_html().
add_to_index()
static void add_to_index (int level, char * item) static
Definition at line 2119 of file man2html.c.
 {
     char   *c = NULL;
     label[3]++;
     if (label[3] > 'Z') {
         label[3] = 'A';
         label[2]++;
     }
     if (level != subs) {
         if (subs) {
             strmaxcpy(manidx + mip, "</DL>\n", HUGE_STR_MAX - mip);
             mip += 6;
         } else {
             strmaxcpy(manidx + mip, "<DL>\n", HUGE_STR_MAX - mip);
             mip += 5;
         }
     }
     subs = level;
     scan_troff(item, 1, &c);
     sprintf(manidx + mip, "<DT><A HREF=\"#%s\">%s</A><DD>\n", label, c);
     if (c)
         free(c);
     while (manidx[mip])
         mip++;
 }
References c, free, HUGE_STR_MAX, label, update-syscall-list::level, manidx, mip, NULL, scan_troff(), sprintf(), strmaxcpy(), and subs.
Referenced by scan_request().
change_to_font()
static char* change_to_font (int nr) static
Definition at line 839 of file man2html.c.
 {
     int     i;
     switch (nr) {
     case '0':
         nr++;
     case '1':
     case '2':
     case '3':
     case '4':
         nr = nr - '1';
         break;
     case V('C', 'W'):
         nr = 3;
         break;
     case 'L':
         nr = 3;
         break;
     case 'B':
         nr = 2;
         break;
     case 'I':
         nr = 1;
         break;
     case 'P':
     case 'R':
         nr = 0;
         break;
     case 0:
     case 1:
     case 2:
     case 3:
         break;
     default:
         nr = 0;
         break;
     }
     i = current_font * 4 + nr % 4;
     current_font = nr % 4;
     return switchfont[i];
 }
References current_font, i, switchfont, and V.
Referenced by change_to_size(), main(), scan_escape(), scan_request(), and scan_table().
change_to_size()
static char* change_to_size (int nr) static
Definition at line 885 of file man2html.c.
 {
     int     i;
     switch (nr) {
     case '0':
     case '1':
     case '2':
     case '3':
     case '4':
     case '5':
     case '6':
     case '7':
     case '8':
     case '9':
         nr = nr - '0';
         break;
     case '\0':
         break;
     default:
         nr = current_size + nr;
         if (nr > 9)
             nr = 9;
         if (nr < -9)
             nr = -9;
         break;
     }
     if (nr == current_size)
         return "";
     i = current_font;
     sizebuf[0] = '\0';
     strcat(sizebuf, change_to_font(0));
     if (current_size)
         strcat(sizebuf, "</FONT>");
     current_size = nr;
     if (nr) {
         int     l;
         strcat(sizebuf, "<FONT SIZE=");
         l = strlen(sizebuf);
         if (nr > 0)
             sizebuf[l++] = '+';
         else
             sizebuf[l++] = '-', nr = -nr;
         sizebuf[l++] = nr + '0';
         sizebuf[l++] = '>';
         sizebuf[l] = '\0';
     }
     strcat(sizebuf, change_to_font(i));
     return sizebuf;
 }
References change_to_font(), current_font, current_size, i, sizebuf, strcat, and strlen().
Referenced by main(), scan_escape(), scan_request(), and scan_table().
clear_table()
static void clear_table (TABLEROW * table) static
Definition at line 1234 of file man2html.c.
 {
     TABLEROW *tr1, *tr2;
     TABLEITEM *ti1, *ti2;
     tr1 = table;
     while (tr1->prev)
         tr1 = tr1->prev;
     while (tr1) {
         ti1 = tr1->first;
         while (ti1) {
             ti2 = ti1->next;
             if (ti1->contents)
                 free(ti1->contents);
             free(ti1);
             ti1 = ti2;
         }
         tr2 = tr1;
         tr1 = tr1->next;
         free(tr2);
     }
 }
References TABLEITEM::contents, TABLEROW::first, free, TABLEITEM::next, TABLEROW::next, TABLEROW::prev, and table.
Referenced by scan_format(), and scan_table().
escape_input()
static char* escape_input (char * str) static
Definition at line 240 of file man2html.c.
 {
     int     i, j = 0;
     static char new[NULL_TERMINATED(MED_STR_MAX)];
     if (strlen(str) * 2 + 1 > MED_STR_MAX) {
         fprintf(stderr,
             "man2html: escape_input - str too long:\n%-80s...\n",
             str);
         exit(EXIT_FAILURE);
     }
     for (i = 0; i < strlen(str); i++) {
         if (!(((str[i] >= 'A') && (str[i] <= 'Z')) ||
               ((str[i] >= 'a') && (str[i] <= 'z')) ||
               ((str[i] >= '0') && (str[i] <= '9')))) {
             new[j] = '\\';
             j++;
         }
         new[j] = str[i];
         j++;
     }
     new[j] = '\0';
     return new;
 }
References exit(), EXIT_FAILURE, fprintf(), i, j, MED_STR_MAX, NULL_TERMINATED, stderr, str, and strlen().
expand_char()
static char* expand_char (int nr) static
Definition at line 463 of file man2html.c.
 {
     STRDEF *h;
     h = chardef;
     if (!nr)
         return NULL;
     while (h)
         if (h->nr == nr) {
             curpos += h->slen;
             return h->st;
         } else
             h = h->next;
     charb[0] = nr / 256;
     charb[1] = nr % 256;
     charb[2] = '\0';
     if (charb[0] == '<') {  /* Fix up <= */
         charb[4] = charb[1];
         strncpy(charb, "&lt;", 4);
         charb[5] = '\0';
     }
     curpos += 2;
     return charb;
 }
References charb, chardef, curpos, STRDEF::next, STRDEF::nr, NULL, STRDEF::slen, STRDEF::st, and strncpy().
Referenced by scan_escape().
expand_string()
static char* expand_string (int nr) static
Definition at line 489 of file man2html.c.
 {
     STRDEF *h = strdef;
     if (!nr)
         return NULL;
     while (h)
         if (h->nr == nr) {
             curpos += h->slen;
             return h->st;
         } else
             h = h->next;
     return NULL;
 }
References curpos, STRDEF::next, STRDEF::nr, NULL, STRDEF::slen, STRDEF::st, and strdef.
Referenced by scan_escape().
fill_words()
static char* fill_words (char * c, char * words[], int * n) static
Definition at line 2008 of file man2html.c.
 {
     char   *sl = c;
     int     slash = 0;
     int     skipspace = 0;
     *n = 0;
     words[*n] = sl;
     while (*sl && (*sl != '\n' || slash)) {
         if (!slash) {
             if (*sl == '"') {
                 *sl = '\a';
                 skipspace = !skipspace;
             } else if (*sl == '\a') {
                 /* handle already-translated " */
                 skipspace = !skipspace;
             } else if (*sl == escapesym)
                 slash = 1;
             else if ((*sl == ' ' || *sl == '\t') && !skipspace) {
                 *sl = '\n';
                 if (words[*n] != sl)
                     (*n)++;
                 words[*n] = sl + 1;
             }
         } else {
             if (*sl == '"') {
                 sl--;
                 *sl = '\n';
                 if (words[*n] != sl)
                     (*n)++;
                 sl++;
                 while (*sl && *sl != '\n')
                     sl++;
                 words[*n] = sl;
                 sl--;
             }
             slash = 0;
         }
         sl++;
     }
     if (sl != words[*n])
         (*n)++;
     return sl;
 }
References c, escapesym, n, and skipspace().
Referenced by scan_request().
flush()
static void flush (void) static
Definition at line 3748 of file man2html.c.
 {
 }
lookup_abbrev()
static char* lookup_abbrev (char * c) static
Definition at line 2099 of file man2html.c.
 {
     int     i = 0;
     if (!c)
         return "";
     while (abbrev_list[i] && strcmp(c, abbrev_list[i]))
         i = i + 2;
     if (abbrev_list[i])
         return abbrev_list[i + 1];
     else
         return c;
 }
References abbrev_list, c, i, and strcmp.
Referenced by scan_request().
main()
int main (int argc, char ** argv)
Definition at line 3990 of file man2html.c.
 {
     FILE   *f;
     char   *t;
     int     l, i;
     char   *buf;
     char   *h, *fullname;
     STRDEF *stdf;
     t = NULL;
     while ((i = getopt(argc, argv, "")) != EOF) {
         switch (i) {
         default:
             usage();
             exit(EXIT_USAGE);
         }
     }
     if (argc != 2) {
         usage();
         exit(EXIT_USAGE);
     }
     manpage = h = t = argv[1];
     i = 0;
     buf = read_man_page(h);
     if (!buf) {
         fprintf(stderr, "man2html: cannot read %s: %s\n", h, strerror(errno));
         exit(1);
     }
 #ifdef MAKEINDEX
     idxfile = fopen(INDEXFILE, "a");
 #endif
     stdf = &standardchar[0];
     i = 0;
     while (stdf->nr) {
         stdf->next = &standardchar[i];
         stdf = stdf->next;
         i++;
     }
     chardef = &standardchar[0];
     stdf = &standardstring[0];
     i = 0;
     while (stdf->nr) {
         stdf->next = &standardstring[i];
         stdf = stdf->next;
         i++;
     }
     strdef = &standardstring[0];
     intdef = &standardint[0];
     i = 0;
     while (intdef->nr) {
         intdef->next = &standardint[i];
         intdef = intdef->next;
         i++;
     }
     intdef = &standardint[0];
     defdef = NULL;
     scan_troff(buf + 1, 0, NULL);
     while (itemdepth || dl_set[itemdepth]) {
         out_html("</DL>\n");
         if (dl_set[itemdepth])
             dl_set[itemdepth] = 0;
         else if (itemdepth > 0)
             itemdepth--;
     }
     out_html(change_to_font(0));
     out_html(change_to_size(0));
     if (!fillout) {
         fillout = 1;
         out_html("</PRE>");
     }
     out_html(NEWLINE);
     if (output_possible) {
         outputPageFooter(th_version, th_datestr, th_page_and_sec);
         /* &nbsp; for mosaic users */
         fputs("<HR>\n<A NAME=\"index\">&nbsp;</A><H2>Index</H2>\n<DL>\n", stdout);
         manidx[mip] = 0;
         fputs(manidx, stdout);
         if (subs)
             fputs("</DL>\n", stdout);
         fputs("</DL>\n", stdout);
         print_sig();
         fputs("</BODY>\n</HTML>\n", stdout);
     } else
         fprintf(stderr, "man2html: no output produced\n");
 #ifdef MAKEINDEX
     if (idxfile)
         fclose(idxfile);
 #endif
     exit(EXIT_SUCCESS);
 }
References argc, argv, buf, change_to_font(), change_to_size(), chardef, defdef, dl_set, EOF, errno, exit(), EXIT_SUCCESS, EXIT_USAGE, f, fclose(), fillout, fopen(), fprintf(), fputs(), getopt(), i, idxfile, INDEXFILE, intdef, itemdepth, manidx, manpage, mip, NEWLINE, STRDEF::next, INTDEF::next, STRDEF::nr, INTDEF::nr, NULL, out_html(), output_possible, outputPageFooter(), print_sig(), read_man_page(), scan_troff(), standardchar, standardint, standardstring, stderr, stdout, strdef, strerror(), subs, t, th_datestr, th_page_and_sec, th_version, and usage().
next_row()
static TABLEROW* next_row (TABLEROW * tr) static
Definition at line 1403 of file man2html.c.
 {
     if (tr->next) {
         tr = tr->next;
         if (!tr->next)
             next_row(tr);
         return tr;
     } else {
         TABLEITEM *ti, *ti2;
         tr->next = (TABLEROW *) xmalloc(sizeof(TABLEROW));
         tr->next->prev = tr;
         ti = tr->first;
         tr = tr->next;
         tr->next = NULL;
         if (ti)
             tr->first = ti2 = (TABLEITEM *) xmalloc(sizeof(TABLEITEM));
         else
             tr->first = ti2 = NULL;
         while (ti != ti2) {
             *ti2 = *ti;
             ti2->contents = NULL;
             if ((ti = ti->next)) {
                 ti2->next = (TABLEITEM *) xmalloc(sizeof(TABLEITEM));
             }
             ti2 = ti2->next;
         }
         return tr;
     }
 }
References TABLEITEM::contents, TABLEROW::first, TABLEITEM::next, TABLEROW::next, NULL, TABLEROW::prev, and xmalloc().
Referenced by scan_table().
out_html()
static void out_html (char * c) static
Definition at line 778 of file man2html.c.
 {
     if (!c)
         return;
     if (no_newline_output) {
         int     i = 0;
         no_newline_output = 1;
         while (c[i]) {
             if (!no_newline_output)
                 c[i - 1] = c[i];
             if (c[i] == '\n')
                 no_newline_output = 1;
             i++;
         }
         if (!no_newline_output)
             c[i - 1] = 0;
     }
     if (scaninbuff) {
         while (*c) {
             if (buffpos >= buffmax) {
                 char   *h;
                 h = realloc(buffer, buffmax * 2);
                 if (!h)
                     return;
                 buffer = h;
                 buffmax *= 2;
             }
             buffer[buffpos++] = *c++;
         }
     } else if (output_possible) {
         while (*c) {
             outbuffer[obp++] = *c;
             if (*c == '\n' || obp > HUGE_STR_MAX) {
                 outbuffer[obp] = '\0';
                 add_links(outbuffer);
                 obp = 0;
             }
             c++;
         }
     }
 }
References add_links(), buffmax, buffpos, c, HUGE_STR_MAX, i, no_newline_output, obp, outbuffer, output_possible, realloc, and scaninbuff.
Referenced by main(), outputPageFooter(), outputPageHeader(), scan_escape(), scan_request(), scan_table(), and scan_troff().
outputPageFooter()
static void outputPageFooter (char * l, char * c, char * r) static
Definition at line 2184 of file man2html.c.
 {
     out_html("<HR>\n");
     outputPageHeader(l, c, r);
 }
References c, out_html(), outputPageHeader(), and r.
Referenced by main().
outputPageHeader()
static void outputPageHeader (char * l, char * c, char * r) static
Definition at line 2171 of file man2html.c.
 {
     out_html("<TABLE WIDTH=100%>\n<TR>\n");
     out_html("<TH ALIGN=LEFT width=33%>");
     out_html(l);
     out_html("<TH ALIGN=CENTER width=33%>");
     out_html(c);
     out_html("<TH ALIGN=RIGHT width=33%>");
     out_html(r);
     out_html("\n</TR>\n</TABLE>\n");
 }
References c, out_html(), and r.
Referenced by outputPageFooter(), and scan_request().
print_sig()
static void print_sig (void) static
Definition at line 449 of file man2html.c.
 {
     char    datbuf[NULL_TERMINATED(MED_STR_MAX)];
     struct tm *timetm;
     time_t  clock;
     datbuf[0] = '\0';
     clock = time(NULL);
     timetm = localtime(&clock);
     strftime(datbuf, MED_STR_MAX, TIMEFORMAT, timetm);
     printf(signature, manpage, datbuf);
 }
References clock(), localtime(), manpage, MED_STR_MAX, NULL, NULL_TERMINATED, printf, signature, strftime(), time(), and TIMEFORMAT.
Referenced by main().
read_man_page()
static char* read_man_page (char * filename) static
Definition at line 505 of file man2html.c.
 {
     char   *man_buf = NULL;
     int     i;
     FILE   *man_stream = NULL;
     struct stat stbuf;
     int     buf_size;
     if (stat(filename, &stbuf) == -1)
         return NULL;
     buf_size = stbuf.st_size;
     man_buf = stralloc(buf_size + 5);
     man_stream = fopen(filename, "r");
     if (man_stream) {
         man_buf[0] = '\n';
         if (fread(man_buf + 1, 1, buf_size, man_stream) == buf_size) {
             man_buf[buf_size] = '\n';
             man_buf[buf_size + 1] = man_buf[buf_size + 2] = '\0';
         } else {
             free(man_buf);
             man_buf = NULL;
         }
         fclose(man_stream);
     }
     return man_buf;
 }
References fclose(), fopen(), fread(), free, i, NULL, stat::st_size, stat(), and stralloc().
Referenced by main(), and scan_request().
scan_escape()
static char* scan_escape (char * c) static
Definition at line 946 of file man2html.c.
 {
     char   *h = NULL;
     char    b[5];
     INTDEF *intd;
     int     exoutputp, exskipescape;
     int     i, j;
     intresult = 0;
     switch (*c) {
     case 'e':
         h = "\\";
         curpos++;
         break;
     case '0':
     case ' ':
         h = "&nbsp;";
         curpos++;
         break;
     case '|':
         h = "";
         break;
     case '"':
         SKIPEOL;
         c--;
         h = "";
         break;
     case '$':
         if (argument) {
             c++;
             i = (*c - '1');
             if (!(h = argument[i]))
                 h = "";
         }
         break;
     case 'z':
         c++;
         if (*c == '\\') {
             c = scan_escape(c + 1);
             c--;
             h = "";
         } else {
             b[0] = *c;
             b[1] = '\0';
             h = "";
         }
         break;
     case 'k':
         c++;
         if (*c == '(')
             c += 2;
     case '^':
     case '!':
     case '%':
     case 'a':
     case 'd':
     case 'r':
     case 'u':
     case '\n':
     case '&':
         h = "";
         break;
     case '(':
         c++;
         i = c[0] * 256 + c[1];
         c++;
         h = expand_char(i);
         break;
     case '*':
         c++;
         if (*c == '(') {
             c++;
             i = c[0] * 256 + c[1];
             c++;
         } else
             i = *c * 256 + ' ';
         h = expand_string(i);
         break;
     case 'f':
         c++;
         if (*c == '\\') {
             c++;
             c = scan_escape(c);
             c--;
             i = intresult;
         } else if (*c != '(')
             i = *c;
         else {
             c++;
             i = c[0] * 256 + c[1];
             c++;
         }
         if (!skip_escape)
             h = change_to_font(i);
         else
             h = "";
         break;
     case 's':
         c++;
         j = 0;
         i = 0;
         if (*c == '-') {
             j = -1;
             c++;
         } else if (*c == '+') {
             j = 1;
             c++;
         }
         if (*c == '0')
             c++;
         else if (*c == '\\') {
             c++;
             c = scan_escape(c);
             i = intresult;
             if (!j)
                 j = 1;
         } else
             while (isdigit(*c) && (!i || (!j && i < 4)))
                 i = i * 10 + (*c++) - '0';
         if (!j) {
             j = 1;
             if (i)
                 i = i - 10;
         }
         if (!skip_escape)
             h = change_to_size(i * j);
         else
             h = "";
         c--;
         break;
     case 'n':
         c++;
         j = 0;
         switch (*c) {
         case '+':
             j = 1;
             c++;
             break;
         case '-':
             j = -1;
             c++;
             break;
         default:
             break;
         }
         if (*c == '(') {
             c++;
             i = V(c[0], c[1]);
             c = c + 1;
         } else {
             i = V(c[0], ' ');
         }
         intd = intdef;
         while (intd && intd->nr != i)
             intd = intd->next;
         if (intd) {
             intd->val = intd->val + j * intd->incr;
             intresult = intd->val;
         } else {
             switch (i) {
             case V('.', 's'):
                 intresult = current_size;
                 break;
             case V('.', 'f'):
                 intresult = current_font;
                 break;
             default:
                 intresult = 0;
                 break;
             }
         }
         h = "";
         break;
     case 'w':
         c++;
         i = *c;
         c++;
         exoutputp = output_possible;
         exskipescape = skip_escape;
         output_possible = 0;
         skip_escape = 1;
         j = 0;
         while (*c != i) {
             j++;
             if (*c == escapesym)
                 c = scan_escape(c + 1);
             else
                 c++;
         }
         output_possible = exoutputp;
         skip_escape = exskipescape;
         intresult = j;
         break;
     case 'l':
         h = "<HR>";
         curpos = 0;
     case 'b':
     case 'v':
     case 'x':
     case 'o':
     case 'L':
     case 'h':
         c++;
         i = *c;
         c++;
         exoutputp = output_possible;
         exskipescape = skip_escape;
         output_possible = 0;
         skip_escape = 1;
         while (*c != i)
             if (*c == escapesym)
                 c = scan_escape(c + 1);
             else
                 c++;
         output_possible = exoutputp;
         skip_escape = exskipescape;
         break;
     case 'c':
         no_newline_output = 1;
         break;
     case '{':
         newline_for_fun++;
         h = "";
         break;
     case '}':
         if (newline_for_fun)
             newline_for_fun--;
         h = "";
         break;
     case 'p':
         h = "<BR>\n";
         curpos = 0;
         break;
     case 't':
         h = "\t";
         curpos = (curpos + 8) & 0xfff8;
         break;
     case '<':
         h = "&lt;";
         curpos++;
         break;
     case '>':
         h = "&gt;";
         curpos++;
         break;
     case '\\':
         if (single_escape) {
             c--;
             break;
         }
     default:
         b[0] = *c;
         b[1] = 0;
         h = b;
         curpos++;
         break;
     }
     c++;
     if (!skip_escape)
         out_html(h);
     return c;
 }
References argument, b, c, change_to_font(), change_to_size(), curpos, current_font, current_size, escapesym, expand_char(), expand_string(), i, INTDEF::incr, intdef, intresult, isdigit, j, newline_for_fun, INTDEF::next, no_newline_output, INTDEF::nr, NULL, out_html(), output_possible, single_escape, skip_escape, SKIPEOL, V, and INTDEF::val.
Referenced by scan_expression(), scan_request(), and scan_troff().
scan_expression()
static char * scan_expression (char * c, int * result) static
Definition at line 1772 of file man2html.c.
 {
     int     value = 0, value2, j = 0, sign = 1, opex = 0;
     char    oper = 'c';
     if (*c == '!') {
         c = scan_expression(c + 1, &value);
         value = (!value);
     } else if (*c == 'n') {
         c++;
         value = NROFF;
     } else if (*c == 't') {
         c++;
         value = 1 - NROFF;
     } else if (*c == '\'' || *c == '"' || *c < ' ' || (*c == '\\' && c[1] == '(')) {
         /*
          * ?string1?string2? test if string1 equals string2.
          */
         char   *st1 = NULL, *st2 = NULL, *h;
         char   *tcmp = NULL;
         char    sep;
         sep = *c;
         if (sep == '\\') {
             tcmp = c;
             c = c + 3;
         }
         c++;
         h = c;
         while (*c != sep && (!tcmp || strncmp(c, tcmp, 4)))
             c++;
         *c = '\n';
         scan_troff(h, 1, &st1);
         *c = sep;
         if (tcmp)
             c = c + 3;
         c++;
         h = c;
         while (*c != sep && (!tcmp || strncmp(c, tcmp, 4)))
             c++;
         *c = '\n';
         scan_troff(h, 1, &st2);
         *c = sep;
         if (!st1 && !st2)
             value = 1;
         else if (!st1 || !st2)
             value = 0;
         else
             value = (!strcmp(st1, st2));
         if (st1)
             free(st1);
         if (st2)
             free(st2);
         if (tcmp)
             c = c + 3;
         c++;
     } else {
         while (*c && !isspace(*c) && *c != ')') {
             opex = 0;
             switch (*c) {
             case '(':
                 c = scan_expression(c + 1, &value2);
                 value2 = sign * value2;
                 opex = 1;
                 break;
             case '.':
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':{
                     int     num = 0, denum = 1;
                     value2 = 0;
                     while (isdigit(*c))
                         value2 = value2 * 10 + ((*c++) - '0');
                     if (*c == '.') {
                         c++;
                         while (isdigit(*c)) {
                             num = num * 10 + ((*c++) - '0');
                             denum = denum * 10;
                         }
                     }
                     if (isalpha(*c)) {
                         /* scale indicator */
                         switch (*c) {
                         case 'i':   /* inch -> 10pt */
                             value2 = value2 * 10 + (num * 10 + denum / 2) / denum;
                             num = 0;
                             break;
                         default:
                             break;
                         }
                         c++;
                     }
                     value2 = value2 + (num + denum / 2) / denum;
                     value2 = sign * value2;
                     opex = 1;
                     break;
                 }
             case '\\':
                 c = scan_escape(c + 1);
                 value2 = intresult * sign;
                 if (isalpha(*c))
                     c++;    /* scale indicator */
                 opex = 1;
                 break;
             case '-':
                 if (oper) {
                     sign = -1;
                     c++;
                     break;
                 }
             case '>':
             case '<':
             case '+':
             case '/':
             case '*':
             case '%':
             case '&':
             case '=':
             case ':':
                 if (c[1] == '=')
                     oper = (*c++) + 16;
                 else
                     oper = *c;
                 c++;
                 break;
             default:
                 c++;
                 break;
             }
             if (opex) {
                 sign = 1;
                 switch (oper) {
                 case 'c':
                     value = value2;
                     break;
                 case '-':
                     value = value - value2;
                     break;
                 case '+':
                     value = value + value2;
                     break;
                 case '*':
                     value = value * value2;
                     break;
                 case '/':
                     if (value2)
                         value = value / value2;
                     break;
                 case '%':
                     if (value2)
                         value = value % value2;
                     break;
                 case '<':
                     value = (value < value2);
                     break;
                 case '>':
                     value = (value > value2);
                     break;
                 case '>' + 16:
                     value = (value >= value2);
                     break;
                 case '<' + 16:
                     value = (value <= value2);
                     break;
                 case '=':
                 case '=' + 16:
                     value = (value == value2);
                     break;
                 case '&':
                     value = (value && value2);
                     break;
                 case ':':
                     value = (value || value2);
                     break;
                 default:
                     fprintf(stderr, "man2html: unknown operator %c.\n", oper);
                 }
                 oper = 0;
             }
         }
         if (*c == ')')
             c++;
     }
     *result = value;
     return c;
 }
References c, fprintf(), free, intresult, isalpha, isdigit, isspace, j, NROFF, NULL, scan_escape(), scan_troff(), stderr, strcmp, strncmp(), and value.
Referenced by scan_format(), and scan_request().
scan_format()
static char* scan_format (char * c, TABLEROW ** result, int * maxcol) static
Definition at line 1260 of file man2html.c.
 {
     TABLEROW *layout, *currow;
     TABLEITEM *curfield;
     int     i, j;
     if (*result) {
         clear_table(*result);
     }
     layout = currow = (TABLEROW *) xmalloc(sizeof(TABLEROW));
     currow->next = currow->prev = NULL;
     currow->first = curfield = (TABLEITEM *) xmalloc(sizeof(TABLEITEM));
     *curfield = emptyfield;
     while (*c && *c != '.') {
         switch (*c) {
         case 'C':
         case 'c':
         case 'N':
         case 'n':
         case 'R':
         case 'r':
         case 'A':
         case 'a':
         case 'L':
         case 'l':
         case 'S':
         case 's':
         case '^':
         case '_':
             if (curfield->align) {
                 curfield->next = (TABLEITEM *) xmalloc(sizeof(TABLEITEM));
                 curfield = curfield->next;
                 *curfield = emptyfield;
             }
             curfield->align = toupper(*c);
             c++;
             break;
         case 'i':
         case 'I':
         case 'B':
         case 'b':
             curfield->font = toupper(*c);
             c++;
             break;
         case 'f':
         case 'F':
             c++;
             curfield->font = toupper(*c);
             c++;
             if (!isspace(*c))
                 c++;
             break;
         case 't':
         case 'T':
             curfield->valign = 't';
             c++;
             break;
         case 'p':
         case 'P':
             c++;
             i = j = 0;
             if (*c == '+') {
                 j = 1;
                 c++;
             }
             if (*c == '-') {
                 j = -1;
                 c++;
             }
             while (isdigit(*c))
                 i = i * 10 + (*c++) - '0';
             if (j)
                 curfield->size = i * j;
             else
                 curfield->size = j - 10;
             break;
         case 'v':
         case 'V':
         case 'w':
         case 'W':
             c = scan_expression(c + 2, &curfield->width);
             break;
         case '|':
             if (curfield->align)
                 curfield->vleft++;
             else
                 curfield->vright++;
             c++;
             break;
         case 'e':
         case 'E':
             c++;
             break;
         case '0':
         case '1':
         case '2':
         case '3':
         case '4':
         case '5':
         case '6':
         case '7':
         case '8':
         case '9':
             i = 0;
             while (isdigit(*c))
                 i = i * 10 + (*c++) - '0';
             curfield->space = i;
             break;
         case ',':
         case '\n':
             currow->next = (TABLEROW *) xmalloc(sizeof(TABLEROW));
             currow->next->prev = currow;
             currow = currow->next;
             currow->next = NULL;
             curfield = currow->first = (TABLEITEM *) xmalloc(sizeof(TABLEITEM));
             *curfield = emptyfield;
             c++;
             break;
         default:
             c++;
             break;
         }
     }
     if (*c == '.')
         while (*c++ != '\n');
     *maxcol = 0;
     currow = layout;
     while (currow) {
         curfield = layout->first;
         i = 0;
         while (curfield) {
             i++;
             curfield = curfield->next;
         }
         if (i > *maxcol)
             *maxcol = i;
         currow = currow->next;
     }
     *result = layout;
     return c;
 }
References TABLEITEM::align, c, clear_table(), emptyfield, TABLEROW::first, TABLEITEM::font, i, isdigit, isspace, j, TABLEITEM::next, TABLEROW::next, NULL, TABLEROW::prev, scan_expression(), TABLEITEM::size, TABLEITEM::space, toupper, TABLEITEM::valign, TABLEITEM::vleft, TABLEITEM::vright, TABLEITEM::width, and xmalloc().
Referenced by scan_table().
scan_request()
static char* scan_request (char * c) static
Definition at line 2193 of file man2html.c.
 {
     /* BSD Mandoc stuff */
     static int mandoc_synopsis = 0; /* True if we are in the synopsis
                      * section */
     static int mandoc_command = 0;  /* True if this is mandoc page */
     static int mandoc_bd_options;   /* Only copes with non-nested Bd's */
     int     i, j, mode = 0;
     char   *h;
     char   *wordlist[MAX_WORDLIST];
     int     words;
     char   *sl;
     STRDEF *owndef;
     while (*c == ' ' || *c == '\t')
         c++;
     if (c[0] == '\n')
         return c + 1;
     if (c[1] == '\n')
         j = 1;
     else
         j = 2;
     while (c[j] == ' ' || c[j] == '\t')
         j++;
     if (c[0] == escapesym) {
         /* some pages use .\" .\$1 .\} */
         /* .\$1 is too difficult/stupid */
         if (c[1] == '$')
             c = skip_till_newline(c);
         else
             c = scan_escape(c + 1);
     } else {
         i = V(c[0], c[1]);
         switch (i) {
         case V('a', 'b'):
             h = c + j;
             while (*h && *h != '\n')
                 h++;
             *h = '\0';
             if (scaninbuff && buffpos) {
                 buffer[buffpos] = '\0';
                 puts(buffer);
             }
             /* fprintf(stderr, "%s\n", c+2); */
             exit(0);
             break;
         case V('d', 'i'):
             {
                 STRDEF *de;
                 int     oldcurpos = curpos;
                 c = c + j;
                 i = V(c[0], c[1]);
                 if (*c == '\n') {
                     c++;
                     break;
                 }
                 while (*c && *c != '\n')
                     c++;
                 c++;
                 h = c;
                 while (*c && strncmp(c, ".di", 3))
                     while (*c && *c++ != '\n');
                 *c = '\0';
                 de = strdef;
                 while (de && de->nr != i)
                     de = de->next;
                 if (!de) {
                     de = (STRDEF *) xmalloc(sizeof(STRDEF));
                     de->nr = i;
                     de->slen = 0;
                     de->next = strdef;
                     de->st = NULL;
                     strdef = de;
                 } else {
                     if (de->st)
                         free(de->st);
                     de->slen = 0;
                     de->st = NULL;
                 }
                 scan_troff(h, 0, &de->st);
                 *c = '.';
                 while (*c && *c++ != '\n');
                 break;
             }
         case V('d', 's'):
             mode = 1;
         case V('a', 's'):
             {
                 STRDEF *de;
                 int     oldcurpos = curpos;
                 c = c + j;
                 i = V(c[0], c[1]);
                 j = 0;
                 while (c[j] && c[j] != '\n')
                     j++;
                 if (j < 3) {
                     c = c + j;
                     break;
                 }
                 if (c[1] == ' ')
                     c = c + 1;
                 else
                     c = c + 2;
                 while (isspace(*c))
                     c++;
                 if (*c == '"')
                     c++;
                 de = strdef;
                 while (de && de->nr != i)
                     de = de->next;
                 single_escape = 1;
                 curpos = 0;
                 if (!de) {
                     char   *h;
                     de = (STRDEF *) xmalloc(sizeof(STRDEF));
                     de->nr = i;
                     de->slen = 0;
                     de->next = strdef;
                     de->st = NULL;
                     strdef = de;
                     h = NULL;
                     c = scan_troff(c, 1, &h);
                     de->st = h;
                     de->slen = curpos;
                 } else {
                     if (mode) {
                         char   *h = NULL;
                         c = scan_troff(c, 1, &h);
                         free(de->st);
                         de->slen = 0;
                         de->st = h;
                     } else
                         c = scan_troff(c, 1, &de->st);
                     de->slen += curpos;
                 }
                 single_escape = 0;
                 curpos = oldcurpos;
             }
             break;
         case V('b', 'r'):
             if (still_dd)
                 out_html("<DD>");
             else
                 out_html("<BR>\n");
             curpos = 0;
             c = c + j;
             if (c[0] == escapesym) {
                 c = scan_escape(c + 1);
             }
             c = skip_till_newline(c);
             break;
         case V('c', '2'):
             c = c + j;
             if (*c != '\n') {
                 nobreaksym = *c;
             } else
                 nobreaksym = '\'';
             c = skip_till_newline(c);
             break;
         case V('c', 'c'):
             c = c + j;
             if (*c != '\n') {
                 controlsym = *c;
             } else
                 controlsym = '.';
             c = skip_till_newline(c);
             break;
         case V('c', 'e'):
             c = c + j;
             if (*c == '\n') {
                 i = 1;
             } else {
                 i = 0;
                 while ('0' <= *c && *c <= '9') {
                     i = i * 10 + *c - '0';
                     c++;
                 }
             }
             c = skip_till_newline(c);
             /* center next i lines */
             if (i > 0) {
                 out_html("<CENTER>\n");
                 while (i && *c) {
                     char   *line = NULL;
                     c = scan_troff(c, 1, &line);
                     if (line && strncmp(line, "<BR>", 4)) {
                         out_html(line);
                         out_html("<BR>\n");
                         i--;
                     }
                 }
                 out_html("</CENTER>\n");
                 curpos = 0;
             }
             break;
         case V('e', 'c'):
             c = c + j;
             if (*c != '\n') {
                 escapesym = *c;
             } else
                 escapesym = '\\';
             break;
             c = skip_till_newline(c);
         case V('e', 'o'):
             escapesym = '\0';
             c = skip_till_newline(c);
             break;
         case V('e', 'x'):
             exit(0);
             break;
         case V('f', 'c'):
             c = c + j;
             if (*c == '\n') {
                 fieldsym = padsym = '\0';
             } else {
                 fieldsym = c[0];
                 padsym = c[1];
             }
             c = skip_till_newline(c);
             break;
         case V('f', 'i'):
             if (!fillout) {
                 out_html(change_to_font(0));
                 out_html(change_to_size('0'));
                 out_html("</PRE>\n");
             }
             curpos = 0;
             fillout = 1;
             c = skip_till_newline(c);
             break;
         case V('f', 't'):
             c = c + j;
             if (*c == '\n') {
                 out_html(change_to_font(0));
             } else {
                 if (*c == escapesym) {
                     int     fn;
                     c = scan_expression(c, &fn);
                     c--;
                     out_html(change_to_font(fn));
                 } else {
                     out_html(change_to_font(*c));
                     c++;
                 }
             }
             c = skip_till_newline(c);
             break;
         case V('e', 'l'):
             /* .el anything : else part of if else */
             if (ifelseval) {
                 c = c + j;
                 c[-1] = '\n';
                 c = scan_troff(c, 1, NULL);
             } else
                 c = skip_till_newline(c + j);
             break;
         case V('i', 'e'):
             /* .ie c anything : then part of if else */
         case V('i', 'f'):
             /*
              * .if c anything .if !c anything .if N anything .if
              * !N anything .if 'string1'string2' anything .if
              * !'string1'string2' anything
              */
             c = c + j;
             c = scan_expression(c, &i);
             ifelseval = !i;
             if (i) {
                 *c = '\n';
                 c++;
                 c = scan_troff(c, 1, NULL);
             } else
                 c = skip_till_newline(c);
             break;
         case V('i', 'g'):
             {
                 char   *endwith = "..\n";
                 i = 3;
                 c = c + j;
                 if (*c != '\n') {
                     endwith = c - 1;
                     i = 1;
                     c[-1] = '.';
                     while (*c && *c != '\n')
                         c++, i++;
                 }
                 c++;
                 while (*c && strncmp(c, endwith, i))
                     while (*c++ != '\n');
                 while (*c++ != '\n');
                 break;
             }
         case V('n', 'f'):
             if (fillout) {
                 out_html(change_to_font(0));
                 out_html(change_to_size('0'));
                 out_html("<PRE>\n");
             }
             curpos = 0;
             fillout = 0;
             c = skip_till_newline(c);
             break;
         case V('p', 's'):
             c = c + j;
             if (*c == '\n') {
                 out_html(change_to_size('0'));
             } else {
                 j = 0;
                 i = 0;
                 if (*c == '-') {
                     j = -1;
                     c++;
                 } else if (*c == '+') {
                     j = 1;
                     c++;
                 }
                 c = scan_expression(c, &i);
                 if (!j) {
                     j = 1;
                     if (i > 5)
                         i = i - 10;
                 }
                 out_html(change_to_size(i * j));
             }
             c = skip_till_newline(c);
             break;
         case V('s', 'p'):
             c = c + j;
             if (fillout)
                 out_html("<P>");
             else {
                 out_html(NEWLINE);
                 NEWLINE[0] = '\n';
             }
             curpos = 0;
             c = skip_till_newline(c);
             break;
         case V('s', 'o'):
             {
                 FILE   *f;
                 struct stat stbuf;
                 int     l = 0;
                 char   *buf;
                 char   *name = NULL;
                 curpos = 0;
                 c = c + j;
                 if (*c == '/') {
                     h = c;
                 } else {
                     h = c - 3;
                     h[0] = '.';
                     h[1] = '.';
                     h[2] = '/';
                 }
                 while (*c != '\n')
                     c++;
                 *c = '\0';
                 scan_troff(h, 1, &name);
                 if (name[3] == '/')
                     h = name + 3;
                 else
                     h = name;
                 if (stat(h, &stbuf) != -1)
                     l = stbuf.st_size;
 #if NOCGI
                 if (!out_length) {
                     char   *t, *s;
                     t = strrchr(fname, '/');
                     if (!t)
                         t = fname;
                     fprintf(stderr, "ln -s %s.html %s.html\n", h, t);
                     s = strrchr(t, '.');
                     if (!s)
                         s = t;
                     printf("<HTML><HEAD><TITLE> Manpage of %s</TITLE>\n"
                            "</HEAD><BODY>\n"
                            "See the manpage for <A HREF=\"%s.html\">%s</A>.\n"
                            "</BODY></HTML>\n",
                            s, h, h);
                 } else
 #endif
                 {
                     /*
                      * this works alright, except for
                      * section 3
                      */
                     buf = read_man_page(h);
                     if (!buf) {
                         fprintf(stderr, "man2html: unable to open or read file %s.\n",
                             h);
                         out_html("<BLOCKQUOTE>"
                              "man2html: unable to open or read file.\n");
                         out_html(h);
                         out_html("</BLOCKQUOTE>\n");
                     } else {
                         buf[0] = buf[l] = '\n';
                         buf[l + 1] = buf[l + 2] = '\0';
                         scan_troff(buf + 1, 0, NULL);
                     }
                     if (buf)
                         free(buf);
                 }
                 *c++ = '\n';
                 break;
             }
         case V('t', 'a'):
             c = c + j;
             j = 0;
             while (*c != '\n') {
                 sl = scan_expression(c, &tabstops[j]);
                 if (*c == '-' || *c == '+')
                     tabstops[j] += tabstops[j - 1];
                 c = sl;
                 while (*c == ' ' || *c == '\t')
                     c++;
                 j++;
             }
             maxtstop = j;
             curpos = 0;
             break;
         case V('t', 'i'):
             /*
              * while (itemdepth || dl_set[itemdepth]) {
              * out_html("</DL>\n"); if (dl_set[itemdepth])
              * dl_set[itemdepth]=0; else itemdepth--; }
              */
             out_html("<BR>\n");
             c = c + j;
             c = scan_expression(c, &j);
             for (i = 0; i < j; i++)
                 out_html("&nbsp;");
             curpos = j;
             c = skip_till_newline(c);
             break;
         case V('t', 'm'):
             c = c + j;
             h = c;
             while (*c != '\n')
                 c++;
             *c = '\0';
             /* fprintf(stderr,"%s\n", h); */
             *c = '\n';
             break;
         case V('B', ' '):
         case V('B', '\n'):
         case V('I', ' '):
         case V('I', '\n'):
             /* parse one line in a certain font */
             out_html(change_to_font(*c));
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             c = scan_troff(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('O', 'P'):   /* groff manpages use this
                      * construction */
             /* .OP a b : [ <B>a</B> <I>b</I> ] */
             mode = 1;
             c[0] = 'B';
             c[1] = 'I';
             out_html(change_to_font('R'));
             out_html("[");
             curpos++;
         case V('B', 'R'):
         case V('B', 'I'):
         case V('I', 'B'):
         case V('I', 'R'):
         case V('R', 'B'):
         case V('R', 'I'):
             {
                 char    font[2];
                 font[0] = c[0];
                 font[1] = c[1];
                 c = c + j;
                 if (*c == '\n')
                     c++;
                 sl = fill_words(c, wordlist, &words);
                 c = sl + 1;
                 /*
                  * .BR name (section) indicates a link. It
                  * will be added in the output routine.
                  */
                 for (i = 0; i < words; i++) {
                     if (mode) {
                         out_html(" ");
                         curpos++;
                     }
                     wordlist[i][-1] = ' ';
                     out_html(change_to_font(font[i & 1]));
                     scan_troff(wordlist[i], 1, NULL);
                 }
                 out_html(change_to_font('R'));
                 if (mode) {
                     out_html(" ]");
                     curpos++;
                 }
                 out_html(NEWLINE);
                 if (!fillout)
                     curpos = 0;
                 else
                     curpos++;
             }
             break;
         case V('D', 'T'):
             for (j = 0; j < 20; j++)
                 tabstops[j] = (j + 1) * 8;
             maxtstop = 20;
             c = skip_till_newline(c);
             break;
         case V('I', 'P'):
             sl = fill_words(c + j, wordlist, &words);
             c = sl + 1;
             if (!dl_set[itemdepth]) {
                 out_html("<DL COMPACT>\n");
                 dl_set[itemdepth] = 1;
             }
             out_html("<DT>");
             if (words) {
                 scan_troff(wordlist[0], 1, NULL);
             }
             out_html("<DD>");
             curpos = 0;
             break;
         case V('T', 'P'):
             if (!dl_set[itemdepth]) {
                 out_html("<DL COMPACT>\n");
                 dl_set[itemdepth] = 1;
             }
             out_html("<DT>");
             c = skip_till_newline(c);
             /* somewhere a definition ends with '.TP' */
             if (!*c)
                 still_dd = 1;
             else {
                 c = scan_troff(c, 1, NULL);
                 out_html("<DD>");
             }
             curpos = 0;
             break;
         case V('I', 'X'):
             /* general index */
             sl = fill_words(c + j, wordlist, &words);
             c = sl + 1;
             j = 4;
             while (idxlabel[j] == 'Z')
                 idxlabel[j--] = 'A';
             idxlabel[j]++;
 #ifdef MAKEINDEX
             fprintf(idxfile, "%s@%s@", fname, idxlabel);
             for (j = 0; j < words; j++) {
                 h = NULL;
                 scan_troff(wordlist[j], 1, &h);
                 fprintf(idxfile, "_\b@%s", h);
                 free(h);
             }
             fprintf(idxfile, "\n");
 #endif
             out_html("<A NAME=\"");
             out_html(idxlabel);
             /*
              * this will not work in mosaic (due to a bug).
              * Adding '&nbsp;' between '>' and '<' solves it, but
              * creates some space. A normal space does not work.
              */
             out_html("\"></A>");
             break;
         case V('L', 'P'):
         case V('P', 'P'):
             if (dl_set[itemdepth]) {
                 out_html("</DL>\n");
                 dl_set[itemdepth] = 0;
             }
             if (fillout)
                 out_html("<P>\n");
             else {
                 out_html(NEWLINE);
                 NEWLINE[0] = '\n';
             }
             curpos = 0;
             c = skip_till_newline(c);
             break;
         case V('H', 'P'):
             if (!dl_set[itemdepth]) {
                 out_html("<DL COMPACT>");
                 dl_set[itemdepth] = 1;
             }
             out_html("<DT>\n");
             still_dd = 1;
             c = skip_till_newline(c);
             curpos = 0;
             break;
         case V('P', 'D'):
             c = skip_till_newline(c);
             break;
         case V('R', 's'):   /* BSD mandoc */
         case V('R', 'S'):
             sl = fill_words(c + j, wordlist, &words);
             j = 1;
             if (words > 0)
                 scan_expression(wordlist[0], &j);
             if (j >= 0) {
                 itemdepth++;
                 dl_set[itemdepth] = 0;
                 out_html("<DL COMPACT><DT><DD>");
                 c = skip_till_newline(c);
                 curpos = 0;
                 break;
             }
         case V('R', 'e'):   /* BSD mandoc */
         case V('R', 'E'):
             if (itemdepth > 0) {
                 if (dl_set[itemdepth])
                     out_html("</DL>");
                 out_html("</DL>\n");
                 itemdepth--;
             }
             c = skip_till_newline(c);
             curpos = 0;
             break;
         case V('S', 'B'):
             out_html(change_to_size(-1));
             out_html(change_to_font('B'));
             c = scan_troff(c + j, 1, NULL);
             out_html(change_to_font('R'));
             out_html(change_to_size('0'));
             break;
         case V('S', 'M'):
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html(change_to_size(-1));
             trans_char(c, '"', '\a');
             c = scan_troff(c, 1, NULL);
             out_html(change_to_size('0'));
             break;
         case V('S', 's'):   /* BSD mandoc */
             mandoc_command = 1;
         case V('S', 'S'):
             mode = 1;
         case V('S', 'h'):   /* BSD mandoc */
             /* hack for fallthru from above */
             mandoc_command = !mode || mandoc_command;
         case V('S', 'H'):
             c = c + j;
             if (*c == '\n')
                 c++;
             while (itemdepth || dl_set[itemdepth]) {
                 out_html("</DL>\n");
                 if (dl_set[itemdepth])
                     dl_set[itemdepth] = 0;
                 else if (itemdepth > 0)
                     itemdepth--;
             }
             out_html(change_to_font(0));
             out_html(change_to_size(0));
             if (!fillout) {
                 fillout = 1;
                 out_html("</PRE>");
             }
             trans_char(c, '"', '\a');
             add_to_index(mode, c);
             out_html("<A NAME=\"");
             out_html(label);
             /* &nbsp; for mosaic users */
             if (mode)
                 out_html("\">&nbsp;</A>\n<H4>");
             else
                 out_html("\">&nbsp;</A>\n<H3>");
             mandoc_synopsis = strncmp(c, "SYNOPSIS", 8) == 0;
             c = mandoc_command ? scan_troff_mandoc(c, 1, NULL) : scan_troff(c, 1, NULL);
             if (mode)
                 out_html("</H4>\n");
             else
                 out_html("</H3>\n");
             curpos = 0;
             break;
         case V('T', 'S'):
             c = scan_table(c);
             break;
         case V('D', 't'):   /* BSD mandoc */
             mandoc_command = 1;
         case V('T', 'H'):
             if (!output_possible) {
                 sl = fill_words(c + j, wordlist, &words);
                 if (words > 1) {
                     char    *t;
                     for (i = 1; i < words; i++)
                         wordlist[i][-1] = '\0';
                     *sl = '\0';
                     output_possible = 1;
                     sprintf(th_page_and_sec, "%s(%s)", wordlist[0], wordlist[1]);
                     if (words > 2) {
                         t = unescape(wordlist[2]);
                         strncpy(th_datestr, t, sizeof(th_datestr));
                         th_datestr[sizeof(th_datestr) - 1] = '\0';
                     } else
                         th_datestr[0] = '\0';
                     if (words > 3) {
                         t = unescape(wordlist[3]);
                         strncpy(th_version, t, sizeof(th_version));
                         th_version[sizeof(th_version) - 1] = '\0';
                     } else
                         th_version[0] = '\0';
                     out_html("<HTML><HEAD>\n<TITLE>");
                     out_html(th_page_and_sec);
                     out_html(" Manual Page");
                     out_html("</TITLE>\n</HEAD>\n<BODY>");
                     outputPageHeader(th_page_and_sec, th_datestr, th_page_and_sec);
                     out_html("<BR><A HREF=\"#index\">Index</A>\n");
                     *sl = '\n';
                     out_html("<HR>\n");
                     if (mandoc_command)
                         out_html("<BR>BSD mandoc<BR>");
                 }
                 c = sl + 1;
             } else
                 c = skip_till_newline(c);
             curpos = 0;
             break;
         case V('T', 'X'):
             sl = fill_words(c + j, wordlist, &words);
             *sl = '\0';
             out_html(change_to_font('I'));
             if (words > 1)
                 wordlist[1][-1] = '\0';
             c = lookup_abbrev(wordlist[0]);
             curpos += strlen(c);
             out_html(c);
             out_html(change_to_font('R'));
             if (words > 1)
                 out_html(wordlist[1]);
             *sl = '\n';
             c = sl + 1;
             break;
         case V('r', 'm'):
             /* .rm xx : Remove request, macro or string */
         case V('r', 'n'):
             /*
              * .rn xx yy : Rename request, macro or string xx to
              * yy
              */
             {
                 STRDEF *de;
                 c = c + j;
                 i = V(c[0], c[1]);
                 c = c + 2;
                 while (isspace(*c) && *c != '\n')
                     c++;
                 j = V(c[0], c[1]);
                 while (*c && *c != '\n')
                     c++;
                 c++;
                 de = strdef;
                 while (de && de->nr != j)
                     de = de->next;
                 if (de) {
                     if (de->st)
                         free(de->st);
                     de->nr = 0;
                 }
                 de = strdef;
                 while (de && de->nr != i)
                     de = de->next;
                 if (de)
                     de->nr = j;
                 break;
             }
         case V('n', 'x'):
             /* .nx filename : next file. */
         case V('i', 'n'):
             /* .in +-N : Indent */
             c = skip_till_newline(c);
             break;
         case V('n', 'r'):
             /*
              * .nr R +-N M: define and set number register R by
              * +-N; auto-increment by M
              */
             {
                 INTDEF *intd;
                 c = c + j;
                 i = V(c[0], c[1]);
                 c = c + 2;
                 intd = intdef;
                 while (intd && intd->nr != i)
                     intd = intd->next;
                 if (!intd) {
                     intd = (INTDEF *) xmalloc(sizeof(INTDEF));
                     intd->nr = i;
                     intd->val = 0;
                     intd->incr = 0;
                     intd->next = intdef;
                     intdef = intd;
                 }
                 while (*c == ' ' || *c == '\t')
                     c++;
                 c = scan_expression(c, &intd->val);
                 if (*c != '\n') {
                     while (*c == ' ' || *c == '\t')
                         c++;
                     c = scan_expression(c, &intd->incr);
                 }
                 c = skip_till_newline(c);
                 break;
             }
         case V('a', 'm'):
             /* .am xx yy : append to a macro. */
             /* define or handle as .ig yy */
             mode = 1;
         case V('d', 'e'):
             /*
              * .de xx yy : define or redefine macro xx; end at
              * .yy (..)
              */
             /* define or handle as .ig yy */
             {
                 STRDEF *de;
                 int     olen = 0;
                 c = c + j;
                 sl = fill_words(c, wordlist, &words);
                 i = V(c[0], c[1]);
                 j = 2;
                 if (words == 1)
                     wordlist[1] = "..";
                 else {
                     wordlist[1]--;
                     wordlist[1][0] = '.';
                     j = 3;
                 }
                 c = sl + 1;
                 sl = c;
                 while (*c && strncmp(c, wordlist[1], j))
                     c = skip_till_newline(c);
                 de = defdef;
                 while (de && de->nr != i)
                     de = de->next;
                 if (mode && de)
                     olen = strlen(de->st);
                 j = olen + c - sl;
                 h = stralloc(j * 2 + 4);
                 if (h) {
                     for (j = 0; j < olen; j++)
                         h[j] = de->st[j];
                     if (!j || h[j - 1] != '\n')
                         h[j++] = '\n';
                     while (sl != c) {
                         if (sl[0] == '\\' && sl[1] == '\\') {
                             h[j++] = '\\';
                             sl++;
                         } else
                             h[j++] = *sl;
                         sl++;
                     }
                     h[j] = '\0';
                     if (de) {
                         if (de->st)
                             free(de->st);
                         de->st = h;
                     } else {
                         de = (STRDEF *) xmalloc(sizeof(STRDEF));
                         de->nr = i;
                         de->next = defdef;
                         de->st = h;
                         defdef = de;
                     }
                 }
             }
             c = skip_till_newline(c);
             break;
         case V('B', 'l'):   /* BSD mandoc */
             {
                 char    list_options[NULL_TERMINATED(MED_STR_MAX)];
                 char   *nl = strchr(c, '\n');
                 c = c + j;
                 if (dl_set[itemdepth]) {    /* These things can
                                  * nest. */
                     itemdepth++;
                 }
                 if (nl) {   /* Parse list options */
                     strlimitcpy(list_options, c, nl - c, MED_STR_MAX);
                 }
                 if (strstr(list_options, "-bullet")) {  /* HTML Unnumbered List */
                     dl_set[itemdepth] = BL_BULLET_LIST;
                     out_html("<UL>\n");
                 } else if (strstr(list_options, "-enum")) { /* HTML Ordered List */
                     dl_set[itemdepth] = BL_ENUM_LIST;
                     out_html("<OL>\n");
                 } else {    /* HTML Descriptive List */
                     dl_set[itemdepth] = BL_DESC_LIST;
                     out_html("<DL COMPACT>\n");
                 }
                 if (fillout)
                     out_html("<P>\n");
                 else {
                     out_html(NEWLINE);
                     NEWLINE[0] = '\n';
                 }
                 curpos = 0;
                 c = skip_till_newline(c);
                 break;
             }
         case V('E', 'l'):   /* BSD mandoc */
             c = c + j;
             if (dl_set[itemdepth] & BL_DESC_LIST) {
                 out_html("</DL>\n");
             } else if (dl_set[itemdepth] & BL_BULLET_LIST) {
                 out_html("</UL>\n");
             } else if (dl_set[itemdepth] & BL_ENUM_LIST) {
                 out_html("</OL>\n");
             }
             dl_set[itemdepth] = 0;
             if (itemdepth > 0)
                 itemdepth--;
             if (fillout)
                 out_html("<P>\n");
             else {
                 out_html(NEWLINE);
                 NEWLINE[0] = '\n';
             }
             curpos = 0;
             c = skip_till_newline(c);
             break;
         case V('I', 't'):   /* BSD mandoc */
             c = c + j;
             if (strncmp(c, "Xo", 2) == 0 && isspace(*(c + 2))) {
                 c = skip_till_newline(c);
             }
             if (dl_set[itemdepth] & BL_DESC_LIST) {
                 out_html("<DT>");
                 out_html(change_to_font('B'));
                 if (*c == '\n') {   /* Don't allow embedded
                              * comms after a newline */
                     c++;
                     c = scan_troff(c, 1, NULL);
                 } else {    /* Do allow embedded comms on
                          * the same line. */
                     c = scan_troff_mandoc(c, 1, NULL);
                 }
                 out_html(change_to_font('R'));
                 out_html(NEWLINE);
                 out_html("<DD>");
             } else if (dl_set[itemdepth] & (BL_BULLET_LIST | BL_ENUM_LIST)) {
                 out_html("<LI>");
                 c = scan_troff_mandoc(c, 1, NULL);
                 out_html(NEWLINE);
             }
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('B', 'k'):   /* BSD mandoc */
         case V('E', 'k'):   /* BSD mandoc */
         case V('D', 'd'):   /* BSD mandoc */
         case V('O', 's'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('B', 't'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             out_html(" is currently in beta test.");
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('B', 'x'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html("BSD ");
             c = scan_troff_mandoc(c, 1, NULL);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('D', 'l'):   /* BSD mandoc */
             c = c + j;
             out_html(NEWLINE);
             out_html("<BLOCKQUOTE>");
             out_html(change_to_font('L'));
             if (*c == '\n')
                 c++;
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html("</BLOCKQUOTE>");
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('B', 'd'):   /* BSD mandoc */
             {   /* Seems like a kind of example/literal mode */
                 char    bd_options[NULL_TERMINATED(MED_STR_MAX)];
                 char   *nl = strchr(c, '\n');
                 c = c + j;
                 if (nl) {
                     strlimitcpy(bd_options, c, nl - c, MED_STR_MAX);
                 }
                 out_html(NEWLINE);
                 mandoc_bd_options = 0;  /* Remember options for
                              * terminating Bl */
                 if (strstr(bd_options, "-offset indent")) {
                     mandoc_bd_options |= BD_INDENT;
                     out_html("<BLOCKQUOTE>\n");
                 }
                 if (strstr(bd_options, "-literal")
                     || strstr(bd_options, "-unfilled")) {
                     if (fillout) {
                         mandoc_bd_options |= BD_LITERAL;
                         out_html(change_to_font(0));
                         out_html(change_to_size('0'));
                         out_html("<PRE>\n");
                     }
                     curpos = 0;
                     fillout = 0;
                 }
                 c = skip_till_newline(c);
                 break;
             }
         case V('E', 'd'):   /* BSD mandoc */
             if (mandoc_bd_options & BD_LITERAL) {
                 if (!fillout) {
                     out_html(change_to_font(0));
                     out_html(change_to_size('0'));
                     out_html("</PRE>\n");
                 }
             }
             if (mandoc_bd_options & BD_INDENT)
                 out_html("</BLOCKQUOTE>\n");
             curpos = 0;
             fillout = 1;
             c = skip_till_newline(c);
             break;
         case V('B', 'e'):   /* BSD mandoc */
             c = c + j;
             if (fillout)
                 out_html("<P>");
             else {
                 out_html(NEWLINE);
                 NEWLINE[0] = '\n';
             }
             curpos = 0;
             c = skip_till_newline(c);
             break;
         case V('X', 'r'):   /* BSD mandoc */
             {
                 /*
                  * Translate xyz 1 to xyz(1) Allow for
                  * multiple spaces.  Allow the section to be
                  * missing.
                  */
                 char    buff[NULL_TERMINATED(MED_STR_MAX)];
                 char   *bufptr;
                 trans_char(c, '"', '\a');
                 bufptr = buff;
                 c = c + j;
                 if (*c == '\n')
                     c++;    /* Skip spaces */
                 while (isspace(*c) && *c != '\n')
                     c++;
                 while (isalnum(*c)) {   /* Copy the xyz part */
                     *bufptr = *c;
                     bufptr++;
                     if (bufptr >= buff + MED_STR_MAX)
                         break;
                     c++;
                 }
                 while (isspace(*c) && *c != '\n')
                     c++;    /* Skip spaces */
                 if (isdigit(*c)) {  /* Convert the number if
                              * there is one */
                     *bufptr = '(';
                     bufptr++;
                     if (bufptr < buff + MED_STR_MAX) {
                         while (isalnum(*c)) {
                             *bufptr = *c;
                             bufptr++;
                             if (bufptr >= buff + MED_STR_MAX)
                                 break;
                             c++;
                         }
                         if (bufptr < buff + MED_STR_MAX) {
                             *bufptr = ')';
                             bufptr++;
                         }
                     }
                 }
                 while (*c != '\n') {    /* Copy the remainder */
                     if (!isspace(*c)) {
                         *bufptr = *c;
                         bufptr++;
                         if (bufptr >= buff + MED_STR_MAX)
                             break;
                     }
                     c++;
                 }
                 *bufptr = '\n';
                 scan_troff_mandoc(buff, 1, NULL);
                 out_html(NEWLINE);
                 if (fillout)
                     curpos++;
                 else
                     curpos = 0;
             }
             break;
         case V('F', 'l'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             out_html("-");
             if (*c != '\n') {
                 out_html(change_to_font('B'));
                 c = scan_troff_mandoc(c, 1, NULL);
                 out_html(change_to_font('R'));
             }
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('P', 'a'):   /* BSD mandoc */
         case V('P', 'f'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('P', 'p'):   /* BSD mandoc */
             if (fillout)
                 out_html("<P>\n");
             else {
                 out_html(NEWLINE);
                 NEWLINE[0] = '\n';
             }
             curpos = 0;
             c = skip_till_newline(c);
             break;
         case V('D', 'q'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html("``");
             c = scan_troff_mandoc(c, 1, NULL);
             out_html("''");
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('O', 'p'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html(change_to_font('R'));
             out_html("[");
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html("]");
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('O', 'o'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html(change_to_font('R'));
             out_html("[");
             c = scan_troff_mandoc(c, 1, NULL);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('O', 'c'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html("]");
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('P', 'q'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html("(");
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(")");
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('Q', 'l'):   /* BSD mandoc */
             {   /* Single quote first word in the line */
                 char   *sp;
                 trans_char(c, '"', '\a');
                 c = c + j;
                 if (*c == '\n')
                     c++;
                 sp = c;
                 do {    /* Find first whitespace after the
                      * first word that isn't a mandoc
                      * macro */
                     while (*sp && isspace(*sp))
                         sp++;
                     while (*sp && !isspace(*sp))
                         sp++;
                 } while (*sp && isupper(*(sp - 2)) && islower(*(sp - 1)));
                 /*
                  * Use a newline to mark the end of text to
                  * be quoted
                  */
                 if (*sp)
                     *sp = '\n';
                 out_html("`");  /* Quote the text */
                 c = scan_troff_mandoc(c, 1, NULL);
                 out_html("'");
                 out_html(NEWLINE);
                 if (fillout)
                     curpos++;
                 else
                     curpos = 0;
                 break;
             }
         case V('S', 'q'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html("`");
             c = scan_troff_mandoc(c, 1, NULL);
             out_html("'");
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('A', 'r'):   /* BSD mandoc */
             /* parse one line in italics */
             out_html(change_to_font('I'));
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n') {   /* An empty Ar means "file
                          * ..." */
                 out_html("file ...");
             } else {
                 c = scan_troff_mandoc(c, 1, NULL);
             }
             out_html(change_to_font('R'));
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('A', 'd'):   /* BSD mandoc */
         case V('E', 'm'):   /* BSD mandoc */
         case V('V', 'a'):   /* BSD mandoc */
         case V('X', 'c'):   /* BSD mandoc */
             /* parse one line in italics */
             out_html(change_to_font('I'));
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('N', 'd'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html(" - ");
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('N', 'm'):   /* BSD mandoc */
             {
                 static char mandoc_name[NULL_TERMINATED(SMALL_STR_MAX)] = "";
                 trans_char(c, '"', '\a');
                 c = c + j;
                 if (mandoc_synopsis) {  /* Break lines only in
                              * the Synopsis. The
                              * Synopsis section
                              * seems to be treated
                              * as a special case -
                              * Bummer! */
                     static int count = 0;   /* Don't break on the
                                  * first Nm */
                     if (count) {
                         out_html("<BR>");
                     } else {
                         char   *end = strchr(c, '\n');
                         if (end) {  /* Remember the name for
                                  * later. */
                             strlimitcpy(mandoc_name, c, end - c, SMALL_STR_MAX);
                         }
                     }
                     count++;
                 }
                 out_html(change_to_font('B'));
                 while (*c == ' ' || *c == '\t')
                     c++;
                 if (*c == '\n') {   /* If Nm has no
                              * argument, use one
                              * from an earlier Nm
                              * command that did have
                              * one.  Hope there
                              * aren't too many
                              * commands that do
                              * this. */
                     out_html(mandoc_name);
                 } else {
                     c = scan_troff_mandoc(c, 1, NULL);
                 }
                 out_html(change_to_font('R'));
                 out_html(NEWLINE);
                 if (fillout)
                     curpos++;
                 else
                     curpos = 0;
                 break;
             }
         case V('C', 'd'):   /* BSD mandoc */
         case V('C', 'm'):   /* BSD mandoc */
         case V('I', 'c'):   /* BSD mandoc */
         case V('M', 's'):   /* BSD mandoc */
         case V('O', 'r'):   /* BSD mandoc */
         case V('S', 'y'):   /* BSD mandoc */
             /* parse one line in bold */
             out_html(change_to_font('B'));
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('D', 'v'):   /* BSD mandoc */
         case V('E', 'v'):   /* BSD mandoc */
         case V('F', 'r'):   /* BSD mandoc */
         case V('L', 'i'):   /* BSD mandoc */
         case V('N', 'o'):   /* BSD mandoc */
         case V('N', 's'):   /* BSD mandoc */
         case V('T', 'n'):   /* BSD mandoc */
         case V('n', 'N'):   /* BSD mandoc */
             trans_char(c, '"', '\a');
             c = c + j;
             if (*c == '\n')
                 c++;
             out_html(change_to_font('B'));
             c = scan_troff_mandoc(c, 1, NULL);
             out_html(change_to_font('R'));
             out_html(NEWLINE);
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('%', 'A'):   /* BSD mandoc biblio stuff */
         case V('%', 'D'):
         case V('%', 'N'):
         case V('%', 'O'):
         case V('%', 'P'):
         case V('%', 'Q'):
         case V('%', 'V'):
             c = c + j;
             if (*c == '\n')
                 c++;
             c = scan_troff(c, 1, NULL); /* Don't allow embedded
                              * mandoc coms */
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         case V('%', 'B'):
         case V('%', 'J'):
         case V('%', 'R'):
         case V('%', 'T'):
             c = c + j;
             out_html(change_to_font('I'));
             if (*c == '\n')
                 c++;
             c = scan_troff(c, 1, NULL); /* Don't allow embedded
                              * mandoc coms */
             out_html(change_to_font('R'));
             if (fillout)
                 curpos++;
             else
                 curpos = 0;
             break;
         default:
             /* search macro database of self-defined macros */
             owndef = defdef;
             while (owndef && owndef->nr != i)
                 owndef = owndef->next;
             if (owndef) {
                 char  **oldargument;
                 int     deflen;
                 int     onff;
                 sl = fill_words(c + j, wordlist, &words);
                 c = sl + 1;
                 *sl = '\0';
                 for (i = 1; i < words; i++)
                     wordlist[i][-1] = '\0';
                 for (i = 0; i < words; i++) {
                     char   *h = NULL;
                     if (mandoc_command) {
                         scan_troff_mandoc(wordlist[i], 1, &h);
                     } else {
                         scan_troff(wordlist[i], 1, &h);
                     }
                     wordlist[i] = h;
                 }
                 for (i = words; i < 20; i++)
                     wordlist[i] = NULL;
                 deflen = strlen(owndef->st);
                 for (i = 0; owndef->st[deflen + 2 + i] = owndef->st[i]; i++);
                 oldargument = argument;
                 argument = wordlist;
                 onff = newline_for_fun;
                 if (mandoc_command) {
                     scan_troff_mandoc(owndef->st + deflen + 2, 0, NULL);
                 } else {
                     scan_troff(owndef->st + deflen + 2, 0, NULL);
                 }
                 newline_for_fun = onff;
                 argument = oldargument;
                 for (i = 0; i < words; i++)
                     if (wordlist[i])
                         free(wordlist[i]);
                 *sl = '\n';
             } else if (mandoc_command &&
                    ((isupper(*c) && islower(*(c + 1)))
                     || (islower(*c) && isupper(*(c + 1))))
                 ) { /* Let through any BSD mandoc
                      * commands that haven't been delt
                      * with. I don't want to miss
                      * anything out of the text. */
                 char    buf[4];
                 strncpy(buf, c, 2);
                 buf[2] = ' ';
                 buf[3] = '\0';
                 out_html(buf);  /* Print the command (it
                          * might just be text). */
                 c = c + j;
                 trans_char(c, '"', '\a');
                 if (*c == '\n')
                     c++;
                 out_html(change_to_font('R'));
                 c = scan_troff(c, 1, NULL);
                 out_html(NEWLINE);
                 if (fillout)
                     curpos++;
                 else
                     curpos = 0;
             } else {
                 c = skip_till_newline(c);
             }
             break;
         }
     }
     if (fillout) {
         out_html(NEWLINE);
         curpos++;
     }
     NEWLINE[0] = '\n';
     return c;
 }
References add_to_index(), argument, BD_INDENT, BD_LITERAL, BL_BULLET_LIST, BL_DESC_LIST, BL_ENUM_LIST, buf, buffpos, c, change_to_font(), change_to_size(), controlsym, count, curpos, defdef, dl_set, escapesym, exit(), f, fieldsym, fill_words(), fillout, fname, fprintf(), free, i, idxfile, idxlabel, if(), ifelseval, INTDEF::incr, intdef, isalnum(), isdigit, islower, isspace, isupper, itemdepth, j, label, line, lookup_abbrev(), MAX_WORDLIST, maxtstop, MED_STR_MAX, name, NEWLINE, newline_for_fun, STRDEF::next, INTDEF::next, nobreaksym, STRDEF::nr, INTDEF::nr, NULL, NULL_TERMINATED, out_html(), out_length, output_possible, outputPageHeader(), padsym, printf, puts(), read_man_page(), scan_escape(), scan_expression(), scan_table(), scan_troff(), scan_troff_mandoc(), scaninbuff, single_escape, skip_till_newline(), STRDEF::slen, SMALL_STR_MAX, sp, sprintf(), STRDEF::st, stat::st_size, stat(), stderr, still_dd, stralloc(), strchr(), strdef, strlen(), strlimitcpy(), strncmp(), strncpy(), strrchr(), strstr(), t, tabstops, th_datestr, th_page_and_sec, th_version, trans_char(), unescape(), V, INTDEF::val, and xmalloc().
Referenced by scan_troff().
scan_table()
static char* scan_table (char * c) static
Definition at line 1437 of file man2html.c.
 {
     char   *t, *h, *g;
     int     center = 0, expand = 0, box = 0, border = 0, linesize = 1;
     int     i, j, maxcol = 0, finished = 0;
     int     oldfont, oldsize, oldfillout;
     char    itemsep = '\t';
     TABLEROW *layout = NULL, *currow, *ftable;
     TABLEITEM *curfield;
     while (*c++ != '\n');
     h = c;
     if (*h == '.')
         return c - 1;
     oldfont = current_font;
     oldsize = current_size;
     oldfillout = fillout;
     out_html(change_to_font(0));
     out_html(change_to_size(0));
     if (!fillout) {
         fillout = 1;
         out_html("</PRE>");
     }
     while (*h && *h != '\n')
         h++;
     if (h[-1] == ';') {
         /* scan table options */
         while (c < h) {
             while (isspace(*c))
                 c++;
             for (i = 0; tableopt[i] && strncmp(tableopt[i], c, tableoptl[i]); i++);
             c = c + tableoptl[i];
             switch (i) {
             case 0:
                 center = 1;
                 break;
             case 1:
                 expand = 1;
                 break;
             case 2:
                 box = 1;
                 break;
             case 3:
                 border = 1;
                 break;
             case 4:
                 box = 2;
                 break;
             case 5:
                 while (*c++ != '(');
                 itemsep = *c++;
                 break;
             case 6:
                 while (*c++ != '(');
                 linesize = 0;
                 while (isdigit(*c))
                     linesize = linesize * 10 + (*c++) - '0';
                 break;
             case 7:
                 while (*c != ')')
                     c++;
             default:
                 break;
             }
             c++;
         }
         c = h + 1;
     }
     /* scan layout */
     c = scan_format(c, &layout, &maxcol);
     currow = layout;
     next_row(currow);
     curfield = layout->first;
     i = 0;
     while (!finished) {
         /* search item */
         h = c;
         if ((*c == '_' || *c == '=') && (c[1] == itemsep || c[1] == '\n')) {
             if (c[-1] == '\n' && c[1] == '\n') {
                 if (currow->prev) {
                     currow->prev->next = (TABLEROW *) xmalloc(sizeof(TABLEROW));
                     currow->prev->next->next = currow;
                     currow->prev->next->prev = currow->prev;
                     currow->prev = currow->prev->next;
                 } else {
                     currow->prev = layout = (TABLEROW *) xmalloc(sizeof(TABLEROW));
                     currow->prev->prev = NULL;
                     currow->prev->next = currow;
                 }
                 curfield = currow->prev->first =
                     (TABLEITEM *) xmalloc(sizeof(TABLEITEM));
                 *curfield = emptyfield;
                 curfield->align = *c;
                 curfield->colspan = maxcol;
                 curfield = currow->first;
                 c = c + 2;
             } else {
                 if (curfield) {
                     curfield->align = *c;
                     do {
                         curfield = curfield->next;
                     } while (curfield && curfield->align == 'S');
                 }
                 if (c[1] == '\n') {
                     currow = next_row(currow);
                     curfield = currow->first;
                 }
                 c = c + 2;
             }
         } else if (*c == 'T' && c[1] == '{') {
             h = c + 2;
             c = strstr(h, "\nT}");
             c++;
             *c = '\0';
             g = NULL;
             scan_troff(h, 0, &g);
             scan_troff(itemreset, 0, &g);
             *c = 'T';
             c += 3;
             if (curfield) {
                 curfield->contents = g;
                 do {
                     curfield = curfield->next;
                 } while (curfield && curfield->align == 'S');
             } else if (g)
                 free(g);
             if (c[-1] == '\n') {
                 currow = next_row(currow);
                 curfield = currow->first;
             }
         } else if (*c == '.' && c[1] == 'T' && c[2] == '&' && c[-1] == '\n') {
             TABLEROW *hr;
             while (*c++ != '\n');
             hr = currow;
             currow = currow->prev;
             hr->prev = NULL;
             c = scan_format(c, &hr, &i);
             hr->prev = currow;
             currow->next = hr;
             currow = hr;
             next_row(currow);
             curfield = currow->first;
         } else if (*c == '.' && c[1] == 'T' && c[2] == 'E' && c[-1] == '\n') {
             finished = 1;
             while (*c++ != '\n');
             if (currow->prev)
                 currow->prev->next = NULL;
             currow->prev = NULL;
             clear_table(currow);
         } else if (*c == '.' && c[-1] == '\n' && !isdigit(c[1])) {
             /*
              * skip troff request inside table (usually only .sp
              * )
              */
             while (*c++ != '\n');
         } else {
             h = c;
             while (*c && (*c != itemsep || c[-1] == '\\') &&
                    (*c != '\n' || c[-1] == '\\'))
                 c++;
             i = 0;
             if (*c == itemsep) {
                 i = 1;
                 *c = '\n';
             }
             if (h[0] == '\\' && h[2] == '\n' &&
                 (h[1] == '_' || h[1] == '^')) {
                 if (curfield) {
                     curfield->align = h[1];
                     do {
                         curfield = curfield->next;
                     } while (curfield && curfield->align == 'S');
                 }
                 h = h + 3;
             } else {
                 g = NULL;
                 h = scan_troff(h, 1, &g);
                 scan_troff(itemreset, 0, &g);
                 if (curfield) {
                     curfield->contents = g;
                     do {
                         curfield = curfield->next;
                     } while (curfield && curfield->align == 'S');
                 } else if (g)
                     free(g);
             }
             if (i)
                 *c = itemsep;
             c = h;
             if (c[-1] == '\n') {
                 currow = next_row(currow);
                 curfield = currow->first;
             }
         }
     }
     /* calculate colspan and rowspan */
     currow = layout;
     while (currow->next)
         currow = currow->next;
     while (currow) {
         TABLEITEM *ti, *ti1 = NULL, *ti2 = NULL;
         ti = currow->first;
         if (currow->prev)
             ti1 = currow->prev->first;
         while (ti) {
             switch (ti->align) {
             case 'S':
                 if (ti2) {
                     ti2->colspan++;
                     if (ti2->rowspan < ti->rowspan)
                         ti2->rowspan = ti->rowspan;
                 }
                 break;
             case '^':
                 if (ti1)
                     ti1->rowspan++;
             default:
                 if (!ti2)
                     ti2 = ti;
                 else {
                     do {
                         ti2 = ti2->next;
                     } while (ti2 && curfield->align == 'S');
                 }
                 break;
             }
             ti = ti->next;
             if (ti1)
                 ti1 = ti1->next;
         }
         currow = currow->prev;
     }
     /* produce html output */
     if (center)
         out_html("<CENTER>");
     if (box == 2)
         out_html("<TABLE BORDER><TR><TD>");
     out_html("<TABLE");
     if (box || border) {
         out_html(" BORDER");
         if (!border)
             out_html("><TR><TD><TABLE");
         if (expand)
             out_html(" WIDTH=100%");
     }
     out_html(">\n");
     currow = layout;
     while (currow) {
         j = 0;
         out_html("<TR VALIGN=top>");
         curfield = currow->first;
         while (curfield) {
             if (curfield->align != 'S' && curfield->align != '^') {
                 out_html("<TD");
                 switch (curfield->align) {
                 case 'N':
                     curfield->space += 4;
                 case 'R':
                     out_html(" ALIGN=right");
                     break;
                 case 'C':
                     out_html(" ALIGN=center");
                 default:
                     break;
                 }
                 if (!curfield->valign && curfield->rowspan > 1)
                     out_html(" VALIGN=center");
                 if (curfield->colspan > 1) {
                     char    buf[5];
                     out_html(" COLSPAN=");
                     sprintf(buf, "%i", curfield->colspan);
                     out_html(buf);
                 }
                 if (curfield->rowspan > 1) {
                     char    buf[5];
                     out_html(" ROWSPAN=");
                     sprintf(buf, "%i", curfield->rowspan);
                     out_html(buf);
                 }
                 j = j + curfield->colspan;
                 out_html(">");
                 if (curfield->size)
                     out_html(change_to_size(curfield->size));
                 if (curfield->font)
                     out_html(change_to_font(curfield->font));
                 switch (curfield->align) {
                 case '=':
                     out_html("<HR><HR>");
                     break;
                 case '_':
                     out_html("<HR>");
                     break;
                 default:
                     if (curfield->contents)
                         out_html(curfield->contents);
                     break;
                 }
                 if (curfield->space)
                     for (i = 0; i < curfield->space; i++)
                         out_html("&nbsp;");
                 if (curfield->font)
                     out_html(change_to_font(0));
                 if (curfield->size)
                     out_html(change_to_size(0));
                 if (j >= maxcol && curfield->align > '@' && curfield->align != '_')
                     out_html("<BR>");
                 out_html("</TD>");
             }
             curfield = curfield->next;
         }
         out_html("</TR>\n");
         currow = currow->next;
     }
     if (box && !border)
         out_html("</TABLE>");
     out_html("</TABLE>");
     if (box == 2)
         out_html("</TABLE>");
     if (center)
         out_html("</CENTER>\n");
     else
         out_html("\n");
     if (!oldfillout)
         out_html("<PRE>");
     fillout = oldfillout;
     out_html(change_to_size(oldsize));
     out_html(change_to_font(oldfont));
     return c;
 }
References TABLEITEM::align, buf, c, change_to_font(), change_to_size(), clear_table(), TABLEITEM::colspan, TABLEITEM::contents, current_font, current_size, emptyfield, fillout, finished, TABLEROW::first, TABLEITEM::font, free, g, i, isdigit, isspace, itemreset, j, linesize, TABLEITEM::next, TABLEROW::next, next_row(), NULL, out_html(), TABLEROW::prev, TABLEITEM::rowspan, scan_format(), scan_troff(), TABLEITEM::size, TABLEITEM::space, sprintf(), strncmp(), strstr(), t, tableopt, tableoptl, TABLEITEM::valign, and xmalloc().
Referenced by scan_request().
scan_troff()
static char * scan_troff (char * c, int san, char ** result) static
Definition at line 3758 of file man2html.c.
 {
     char   *h;
     char    intbuff[NULL_TERMINATED(MED_STR_MAX)];
     int     ibp = 0;
     int     i;
     char   *exbuffer;
     int     exbuffpos, exbuffmax, exscaninbuff, exnewline_for_fun;
     int     usenbsp = 0;
 #define FLUSHIBP  if (ibp) { intbuff[ibp]=0; out_html(intbuff); ibp=0; }
     exbuffer = buffer;
     exbuffpos = buffpos;
     exbuffmax = buffmax;
     exnewline_for_fun = newline_for_fun;
     exscaninbuff = scaninbuff;
     newline_for_fun = 0;
     if (result) {
         if (*result) {
             buffer = *result;
             buffpos = strlen(buffer);
             buffmax = buffpos;
         } else {
             buffer = stralloc(LARGE_STR_MAX);
             buffpos = 0;
             buffmax = LARGE_STR_MAX;
         }
         scaninbuff = 1;
     }
     h = c;
     /* start scanning */
     while (*h && (!san || newline_for_fun || *h != '\n')) {
         if (*h == escapesym) {
             h++;
             FLUSHIBP;
             h = scan_escape(h);
         } else if (*h == controlsym && h[-1] == '\n') {
             h++;
             FLUSHIBP;
             h = scan_request(h);
             if (san && h[-1] == '\n')
                 h--;
         } else if (mandoc_line
                && *(h) && isupper(*(h))
                && *(h + 1) && islower(*(h + 1))
                && *(h + 2) && isspace(*(h + 2))) {
             /*
              * BSD embedded command eg ".It Fl Ar arg1 Fl Ar
              * arg2"
              */
             FLUSHIBP;
             h = scan_request(h);
             if (san && h[-1] == '\n')
                 h--;
         } else if (*h == nobreaksym && h[-1] == '\n') {
             h++;
             FLUSHIBP;
             h = scan_request(h);
             if (san && h[-1] == '\n')
                 h--;
         } else {
             int     mx;
             if (h[-1] == '\n' && still_dd && isalnum(*h)) {
                 /*
                  * sometimes a .HP request is not followed by
                  * a .br request
                  */
                 FLUSHIBP;
                 out_html("<DD>");
                 curpos = 0;
                 still_dd = 0;
             }
             switch (*h) {
             case '&':
                 intbuff[ibp++] = '&';
                 intbuff[ibp++] = 'a';
                 intbuff[ibp++] = 'm';
                 intbuff[ibp++] = 'p';
                 intbuff[ibp++] = ';';
                 curpos++;
                 break;
             case '<':
                 intbuff[ibp++] = '&';
                 intbuff[ibp++] = 'l';
                 intbuff[ibp++] = 't';
                 intbuff[ibp++] = ';';
                 curpos++;
                 break;
             case '>':
                 intbuff[ibp++] = '&';
                 intbuff[ibp++] = 'g';
                 intbuff[ibp++] = 't';
                 intbuff[ibp++] = ';';
                 curpos++;
                 break;
             case '"':
                 intbuff[ibp++] = '&';
                 intbuff[ibp++] = 'q';
                 intbuff[ibp++] = 'u';
                 intbuff[ibp++] = 'o';
                 intbuff[ibp++] = 't';
                 intbuff[ibp++] = ';';
                 curpos++;
                 break;
             case '\n':
                 if (h[-1] == '\n' && fillout) {
                     intbuff[ibp++] = '<';
                     intbuff[ibp++] = 'P';
                     intbuff[ibp++] = '>';
                 }
                 if (contained_tab && fillout) {
                     intbuff[ibp++] = '<';
                     intbuff[ibp++] = 'B';
                     intbuff[ibp++] = 'R';
                     intbuff[ibp++] = '>';
                 }
                 contained_tab = 0;
                 curpos = 0;
                 usenbsp = 0;
                 intbuff[ibp++] = '\n';
                 break;
             case '\t':
                 {
                     int     curtab = 0;
                     contained_tab = 1;
                     FLUSHIBP;
                     /* like a typewriter, not like TeX */
                     tabstops[19] = curpos + 1;
                     while (curtab < maxtstop && tabstops[curtab] <= curpos)
                         curtab++;
                     if (curtab < maxtstop) {
                         if (!fillout) {
                             while (curpos < tabstops[curtab]) {
                                 intbuff[ibp++] = ' ';
                                 if (ibp > 480) {
                                     FLUSHIBP;
                                 }
                                 curpos++;
                             }
                         } else {
                             out_html("<TT>");
                             while (curpos < tabstops[curtab]) {
                                 out_html("&nbsp;");
                                 curpos++;
                             }
                             out_html("</TT>");
                         }
                     }
                 }
                 break;
             default:
                 if (*h == ' ' && (h[-1] == '\n' || usenbsp)) {
                     FLUSHIBP;
                     if (!usenbsp && fillout) {
                         out_html("<BR>");
                         curpos = 0;
                     }
                     usenbsp = fillout;
                     if (usenbsp)
                         out_html("&nbsp;");
                     else
                         intbuff[ibp++] = ' ';
                 } else if (*h > 31 && *h < 127)
                     intbuff[ibp++] = *h;
                 else if (((unsigned char) (*h)) > 127) {
                     intbuff[ibp++] = '&';
                     intbuff[ibp++] = '#';
                     intbuff[ibp++] = '0' + ((unsigned char) (*h)) / 100;
                     intbuff[ibp++] = '0' + (((unsigned char) (*h)) % 100) / 10;
                     intbuff[ibp++] = '0' + ((unsigned char) (*h)) % 10;
                     intbuff[ibp++] = ';';
                 }
                 curpos++;
                 break;
             }
             if (ibp > (MED_STR_MAX - 20))
                 FLUSHIBP;
             h++;
         }
     }
     FLUSHIBP;
     if (buffer)
         buffer[buffpos] = '\0';
     if (san && *h)
         h++;
     newline_for_fun = exnewline_for_fun;
     if (result) {
         *result = buffer;
         buffer = exbuffer;
         buffpos = exbuffpos;
         buffmax = exbuffmax;
         scaninbuff = exscaninbuff;
     }
     return h;
 }
References buffer, buffmax, buffpos, c, contained_tab, controlsym, curpos, escapesym, fillout, FLUSHIBP, i, isalnum(), islower, isspace, isupper, LARGE_STR_MAX, mandoc_line, maxtstop, MED_STR_MAX, newline_for_fun, nobreaksym, NULL_TERMINATED, out_html(), scan_escape(), scan_request(), scaninbuff, still_dd, stralloc(), strlen(), and tabstops.
Referenced by add_to_index(), main(), scan_expression(), scan_request(), scan_table(), and scan_troff_mandoc().
scan_troff_mandoc()
static char * scan_troff_mandoc (char * c, int san, char ** result) static
Definition at line 3961 of file man2html.c.
 {
     char   *ret, *end = c;
     int     oldval = mandoc_line;
     mandoc_line = 1;
     while (*end && *end != '\n') {
         end++;
     }
     if (end > c + 2
         && ispunct(*(end - 1))
         && isspace(*(end - 2)) && *(end - 2) != '\n') {
         /*
          * Don't format lonely punctuation E.g. in "xyz ," format the
          * xyz and then append the comma removing the space.
          */
         *(end - 2) = '\n';
         ret = scan_troff(c, san, result);
         *(end - 2) = *(end - 1);
         *(end - 1) = ' ';
     } else {
         ret = scan_troff(c, san, result);
     }
     mandoc_line = oldval;
     return ret;
 }
References c, ispunct(), isspace, mandoc_line, ret, and scan_troff().
Referenced by scan_request().
skip_till_newline()
static char* skip_till_newline (char * c) static
Definition at line 2147 of file man2html.c.
 {
     int     lvl = 0;
     while (*c && *c != '\n' || lvl > 0) {
         if (*c == '\\') {
             c++;
             if (*c == '}')
                 lvl--;
             else if (*c == '{')
                 lvl++;
         }
         c++;
     }
     c++;
     if (lvl < 0 && newline_for_fun) {
         newline_for_fun = newline_for_fun + lvl;
         if (newline_for_fun < 0)
             newline_for_fun = 0;
     }
     return c;
 }
References c, and newline_for_fun.
Referenced by scan_request().
stralloc()
static char* stralloc (int len) static
Definition at line 160 of file man2html.c.
 {
     /* allocate enough for len + NULL */
     char   *new = malloc((len + 1) * sizeof(char));
     if (!new) {
         fprintf(stderr, "man2html: out of memory");
         exit(EXIT_FAILURE);
     }
     return new;
 }
References exit(), EXIT_FAILURE, fprintf(), len, malloc, and stderr.
Referenced by read_man_page(), scan_request(), scan_troff(), and strduplicate().
strduplicate()
static char* strduplicate (char * from) static
Definition at line 190 of file man2html.c.
 {
     char   *new = stralloc(strlen(from));
     strcpy(new, from);
     return new;
 }
References stralloc(), strcpy, and strlen().
strerror()
static char* strerror (int e) static
Definition at line 128 of file man2html.c.
 {
     static char emsg[40];
 #if defined (HAVE_SYS_ERRLIST)
     extern int sys_nerr;
     extern char *sys_errlist[];
     if (e > 0 && e < sys_nerr)
         return (sys_errlist[e]);
     else
 #endif              /* HAVE_SYS_ERRLIST */
     {
         sprintf(emsg, "Unknown system error %d", e);
         return (&emsg[0]);
     }
 }
References sprintf(), and sys_nerr.
Referenced by main().
strgrow()
static char* strgrow (char * old, int len) static
Definition at line 148 of file man2html.c.
 {
     char   *new = realloc(old, (strlen(old) + len + 1) * sizeof(char));
     if (!new) {
         fprintf(stderr, "man2html: out of memory");
         exit(EXIT_FAILURE);
     }
     return new;
 }
References exit(), EXIT_FAILURE, fprintf(), len, realloc, stderr, and strlen().
strlimitcpy()
static char* strlimitcpy (char * to, char * from, int n, int limit) static
Definition at line 226 of file man2html.c.
 {
     int     len = n > limit ? limit : n;
     strmaxcpy(to, from, len);
     to[len] = '\0';
     return to;
 }
References len, n, and strmaxcpy().
Referenced by scan_request().
strmaxcat()
static char* strmaxcat (char * to, char * from, int n) static
Definition at line 210 of file man2html.c.
 {
     int     to_len = strlen(to);
     if (to_len < n) {
         int     from_len = strlen(from);
         int     cp = (to_len + from_len <= n) ? from_len : n - to_len;
         strncpy(to + to_len, from, cp);
         to[to_len + cp] = '\0';
     }
     return to;
 }
References cp, n, strlen(), and strncpy().
strmaxcpy()
static char* strmaxcpy (char * to, char * from, int n) static
Definition at line 200 of file man2html.c.
 {
     int     len = strlen(from);
     strncpy(to, from, n);
     to[(len <= n) ? len : n] = '\0';
     return to;
 }
References len, n, strlen(), and strncpy().
Referenced by add_to_index(), and strlimitcpy().
trans_char()
static void trans_char (char * c, char s, char t) static
Definition at line 1968 of file man2html.c.
 {
     char   *sl = c;
     int     slash = 0;
     while (*sl != '\n' || slash) {
         if (!slash) {
             if (*sl == escapesym)
                 slash = 1;
             else if (*sl == s)
                 *sl = t;
         } else
             slash = 0;
         sl++;
     }
 }
References c, escapesym, and t.
Referenced by scan_request().
unescape()
static char* unescape (char * c) static
Definition at line 1987 of file man2html.c.
 {
     int i, l;
     l = strlen (c);
     i = 0;
     while (i < l && c[i]) {
         if (c[i] == '\a') {
             if (c[i+1])
                 memmove (c + i, c + i + 1, l - i);
             else {
                 c[i] = '\0';
                 break;
             }
         }
         i++;
     }
     return c;
 }
References c, i, memmove, and strlen().
Referenced by scan_request().
usage()
static void usage (void) static
Definition at line 266 of file man2html.c.
 {
     fprintf(stderr, "man2html: usage: man2html filename\n");
 }
Referenced by main().
xmalloc()
void* xmalloc (size_t size)
Definition at line 173 of file man2html.c.
 {
     void *ret;
     ret = malloc (size);
     if (ret == 0) {
         fprintf(stderr, "man2html: out of memory");
         exit(EXIT_FAILURE);
     }
     return ret;
 }
References exit(), EXIT_FAILURE, fprintf(), malloc, ret, size, and stderr.
Referenced by next_row(), scan_format(), scan_request(), and scan_table().
Variable Documentation
abbrev_list
char* abbrev_list[] static
Definition at line 2053 of file man2html.c.
Referenced by lookup_abbrev().
argument
char** argument = NULL static
Definition at line 444 of file man2html.c.
Referenced by __cxa_atexit(), scan_escape(), and scan_request().
asint
int asint = 0 static
Definition at line 937 of file man2html.c.
buffer
char* buffer = NULL static
Definition at line 431 of file man2html.c.
Referenced by _rl_init_terminal_io(), _rl_read_file(), _rl_read_init_file(), accessDtv(), AM_Responder(), buffer_gadget(), buffer_gadget_libint(), cmd_cat(), anonymous_namespace{pwd-stubs.cpp}::copy_to_buffer(), anonymous_namespace{grp-stubs.cpp}::copy_to_buffer(), delete_chars(), extract_info(), fgets(), gai_strerror(), getcwd(), getdelim(), getentropy(), history_do_write(), history_truncate_file(), inet_ntoa(), open_some_spaces(), ptsname(), read_history_range(), scan_troff(), sendto(), V_UseBuffer(), vsnprintf(), and vsscanf().
buffmax
int buffmax = 0 static
Definition at line 432 of file man2html.c.
Referenced by out_html(), and scan_troff().
buffpos
int buffpos = 0 static
Definition at line 432 of file man2html.c.
Referenced by out_html(), scan_request(), and scan_troff().
charb
char charb[TINY_STR_MAX] static
Definition at line 446 of file man2html.c.
Referenced by expand_char().
chardef
STRDEF* chardef static
Definition at line 301 of file man2html.c.
Referenced by expand_char(), and main().
contained_tab
int contained_tab = 0 static
Definition at line 3752 of file man2html.c.
Referenced by scan_troff().
controlsym
char controlsym = '.' static
Definition at line 429 of file man2html.c.
Referenced by scan_request(), and scan_troff().
curpos
int curpos = 0 static
Definition at line 439 of file man2html.c.
Referenced by expand_char(), expand_string(), scan_escape(), scan_request(), and scan_troff().
current_font
int current_font = 0 static
Definition at line 773 of file man2html.c.
Referenced by change_to_font(), change_to_size(), scan_escape(), and scan_table().
current_size
int current_size = 0 static
Definition at line 774 of file man2html.c.
Referenced by change_to_size(), scan_escape(), and scan_table().
defdef
STRDEF * defdef static
Definition at line 301 of file man2html.c.
Referenced by main(), and scan_request().
dl_set
int dl_set[20] = {0} static
Definition at line 435 of file man2html.c.
Referenced by main(), and scan_request().
emptyfield
TABLEITEM emptyfield = {NULL, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, NULL} static
Definition at line 1218 of file man2html.c.
Referenced by scan_format(), and scan_table().
eqndelimclose
char eqndelimclose = 0 static
Definition at line 428 of file man2html.c.
eqndelimopen
char eqndelimopen = 0 static
Definition at line 428 of file man2html.c.
escapesym
char escapesym = '\\' static
Definition at line 429 of file man2html.c.
Referenced by fill_words(), scan_escape(), scan_request(), scan_troff(), and trans_char().
fieldsym
char fieldsym = 0 static
Definition at line 429 of file man2html.c.
Referenced by scan_request().
fillout
int fillout = 1 static
Definition at line 775 of file man2html.c.
Referenced by main(), scan_request(), scan_table(), and scan_troff().
fname
char* fname static
Definition at line 298 of file man2html.c.
Referenced by _remove_directory(), force_execute_file(), getstat(), history_truncate_file(), isolate_tilde_prefix(), loadstat(), maybe_execute_file(), memory_error_and_abort(), read_alias_file(), rm_file(), scan_request(), stat_builtin(), statlink(), statval(), and write_helpfiles().
idxfile
FILE* idxfile static
Definition at line 299 of file man2html.c.
Referenced by main(), and scan_request().
idxlabel
char idxlabel[6] = "ixAAA" static
Definition at line 294 of file man2html.c.
Referenced by scan_request().
ifelseval
int ifelseval = 0 static
Definition at line 2190 of file man2html.c.
Referenced by scan_request().
intdef
INTDEF* intdef static
Definition at line 302 of file man2html.c.
Referenced by main(), scan_escape(), and scan_request().
intresult
int intresult = 0 static
Definition at line 938 of file man2html.c.
Referenced by scan_escape(), and scan_expression().
itemdepth
int itemdepth = 0 static
Definition at line 434 of file man2html.c.
Referenced by main(), and scan_request().
itemreset
char itemreset[20] = "\\fR\\s0" static
Definition at line 1434 of file man2html.c.
Referenced by scan_table().
label
char label[5] = "lbAA" static
Definition at line 2116 of file man2html.c.
Referenced by _rl_parse_colors(), add_to_index(), fmtmsg(), and scan_request().
location_base
char location_base[NULL_TERMINATED(MED_STR_MAX)] = "" static
Definition at line 104 of file man2html.c.
mandoc_line
int mandoc_line = 0 static
Definition at line 3753 of file man2html.c.
Referenced by scan_troff(), and scan_troff_mandoc().
manidx
char manidx[NULL_TERMINATED(HUGE_STR_MAX)] static
Definition at line 2113 of file man2html.c.
Referenced by add_to_index(), and main().
manpage
char* manpage
Definition at line 115 of file man2html.c.
Referenced by main(), and print_sig().
maxtstop
int maxtstop = 12 static
Definition at line 438 of file man2html.c.
Referenced by scan_request(), and scan_troff().
mip
int mip = 0 static
Definition at line 2115 of file man2html.c.
Referenced by add_to_index(), and main().
NEWLINE
char NEWLINE[2] = "\n" static
Definition at line 293 of file man2html.c.
Referenced by main(), and scan_request().
newline_for_fun
int newline_for_fun = 0 static
Definition at line 537 of file man2html.c.
Referenced by scan_escape(), scan_request(), scan_troff(), and skip_till_newline().
no_newline_output
int no_newline_output = 0 static
Definition at line 536 of file man2html.c.
Referenced by out_html(), and scan_escape().
nobreaksym
char nobreaksym = '\'' static
Definition at line 429 of file man2html.c.
Referenced by scan_request(), and scan_troff().
obp
int obp = 0 static
Definition at line 535 of file man2html.c.
Referenced by out_html().
out_length
int out_length = 0 static
Definition at line 539 of file man2html.c.
Referenced by add_links(), and scan_request().
outbuffer
char outbuffer[NULL_TERMINATED(HUGE_STR_MAX)] static
Definition at line 534 of file man2html.c.
Referenced by out_html().
output_possible
int output_possible = 0 static
Definition at line 538 of file man2html.c.
Referenced by main(), out_html(), scan_escape(), and scan_request().
padsym
char padsym = 0 static
Definition at line 429 of file man2html.c.
Referenced by scan_request().
scaninbuff
int scaninbuff = 0 static
Definition at line 433 of file man2html.c.
Referenced by out_html(), scan_request(), and scan_troff().
signature
char* signature = "<HR>\nThis document was created by man2html from %s.<BR>\nTime: %s\n"
Definition at line 110 of file man2html.c.
Referenced by print_sig(), VirtualFileSystem::USTAR::ReadArchive(), and VirtualFileSystem::USTAR::TestArchive().
single_escape
int single_escape = 0 static
Definition at line 943 of file man2html.c.
Referenced by scan_escape(), and scan_request().
sizebuf
char sizebuf[200] static
Definition at line 882 of file man2html.c.
Referenced by change_to_size().
skip_escape
int skip_escape = 0 static
Definition at line 942 of file man2html.c.
Referenced by scan_escape().
standardchar
STRDEF standardchar[] static
Definition at line 326 of file man2html.c.
Referenced by main().
standardint
INTDEF standardint[] static
Initial value:
= {
    {V('n', ' '), NROFF, 0, NULL},
    {V('t', ' '), 1 - NROFF, 0, NULL},
    {V('o', ' '), 1, 0, NULL},
    {V('e', ' '), 0, 0, NULL},
    {V('.', 'l'), 70, 0, NULL},
    {V('.', '$'), 0, 0, NULL},
    {V('.', 'A'), NROFF, 0, NULL},
    {V('.', 'T'), 1 - NROFF, 0, NULL},
    {V('.', 'V'), 1, 0, NULL},
{0, 0, 0, NULL}}
Definition at line 306 of file man2html.c.
Referenced by main().
standardstring
STRDEF standardstring[] static
Initial value:
= {
    {V('R', ' '), 1, "&#174;", NULL},
    {V('l', 'q'), 2, "``", NULL},
    {V('r', 'q'), 2, "''", NULL},
    {0, 0, NULL, NULL}
}
Definition at line 318 of file man2html.c.
Referenced by main().
still_dd
int still_dd = 0 static
Definition at line 436 of file man2html.c.
Referenced by scan_request(), and scan_troff().
strdef
STRDEF * strdef static
Definition at line 301 of file man2html.c.
Referenced by expand_string(), main(), and scan_request().
subs
int subs = 0 static
Definition at line 2114 of file man2html.c.
Referenced by add_to_index(), and main().
switchfont
char* switchfont[16] static
Initial value:
= {
    "", FC0 FO1, FC0 FO2, FC0 FO3,
    FC1 FO0, "", FC1 FO2, FC1 FO3,
    FC2 FO0, FC2 FO1, "", FC2 FO3,
    FC3 FO0, FC3 FO1, FC3 FO2, ""
}
Definition at line 831 of file man2html.c.
Referenced by change_to_font().
tableopt
char* tableopt[] static
Initial value:
= {
    "center", "expand", "box", "allbox", "doublebox",
    "tab", "linesize", "delim", NULL
}
Definition at line 1227 of file man2html.c.
Referenced by scan_table().
tableoptl
int tableoptl[] = {6, 6, 3, 6, 9, 3, 8, 5, 0} static
Definition at line 1231 of file man2html.c.
Referenced by scan_table().
tabstops
int tabstops[20] = {8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96} static
Definition at line 437 of file man2html.c.
Referenced by scan_request(), and scan_troff().
th_datestr
char th_datestr[128] = { '\0' } static
Definition at line 107 of file man2html.c.
Referenced by main(), and scan_request().
th_page_and_sec
char th_page_and_sec[128] = { '\0' } static
Definition at line 106 of file man2html.c.
Referenced by main(), and scan_request().
th_version
char th_version[128] = { '\0' } static
Definition at line 108 of file man2html.c.
Referenced by main(), and scan_request().