Fennix Userspace: Userspace/musl/include/fmtmsg.h File Reference
fmtmsg.h File Reference
Macros
#define MM_HARD 1
#define MM_SOFT 2
#define MM_FIRM 4
#define MM_APPL 8
#define MM_UTIL 16
#define MM_OPSYS 32
#define MM_RECOVER 64
#define MM_NRECOV 128
#define MM_PRINT 256
#define MM_CONSOLE 512
#define MM_NULLMC 0L
#define MM_HALT 1
#define MM_ERROR 2
#define MM_WARNING 3
#define MM_INFO 4
#define MM_NOSEV 0
#define MM_OK 0
#define MM_NOTOK (-1)
#define MM_NOMSG 1
#define MM_NOCON 4
#define MM_NULLLBL ((char*)0)
#define MM_NULLTXT ((char*)0)
#define MM_NULLACT ((char*)0)
#define MM_NULLTAG ((char*)0)
#define MM_NULLSEV 0
Functions
int fmtmsg (long, const char *, int, const char *, const char *, const char *)
Macro Definition Documentation
MM_APPL
#define MM_APPL 8
Definition at line 12 of file fmtmsg.h.
MM_CONSOLE
#define MM_CONSOLE 512
Definition at line 20 of file fmtmsg.h.
MM_ERROR
#define MM_ERROR 2
Definition at line 25 of file fmtmsg.h.
MM_FIRM
#define MM_FIRM 4
Definition at line 10 of file fmtmsg.h.
MM_HALT
#define MM_HALT 1
Definition at line 24 of file fmtmsg.h.
MM_HARD
#define MM_HARD 1
Definition at line 8 of file fmtmsg.h.
MM_INFO
#define MM_INFO 4
Definition at line 27 of file fmtmsg.h.
MM_NOCON
#define MM_NOCON 4
Definition at line 33 of file fmtmsg.h.
MM_NOMSG
#define MM_NOMSG 1
Definition at line 32 of file fmtmsg.h.
MM_NOSEV
#define MM_NOSEV 0
Definition at line 28 of file fmtmsg.h.
MM_NOTOK
#define MM_NOTOK (-1)
Definition at line 31 of file fmtmsg.h.
MM_NRECOV
#define MM_NRECOV 128
Definition at line 17 of file fmtmsg.h.
MM_NULLACT
#define MM_NULLACT ((char*)0)
Definition at line 37 of file fmtmsg.h.
MM_NULLLBL
#define MM_NULLLBL ((char*)0)
Definition at line 35 of file fmtmsg.h.
MM_NULLMC
#define MM_NULLMC 0L
Definition at line 22 of file fmtmsg.h.
MM_NULLSEV
#define MM_NULLSEV 0
Definition at line 39 of file fmtmsg.h.
MM_NULLTAG
#define MM_NULLTAG ((char*)0)
Definition at line 38 of file fmtmsg.h.
MM_NULLTXT
#define MM_NULLTXT ((char*)0)
Definition at line 36 of file fmtmsg.h.
MM_OK
#define MM_OK 0
Definition at line 30 of file fmtmsg.h.
MM_OPSYS
#define MM_OPSYS 32
Definition at line 14 of file fmtmsg.h.
MM_PRINT
#define MM_PRINT 256
Definition at line 19 of file fmtmsg.h.
MM_RECOVER
#define MM_RECOVER 64
Definition at line 16 of file fmtmsg.h.
MM_SOFT
#define MM_SOFT 2
Definition at line 9 of file fmtmsg.h.
MM_UTIL
#define MM_UTIL 16
Definition at line 13 of file fmtmsg.h.
MM_WARNING
#define MM_WARNING 3
Definition at line 26 of file fmtmsg.h.
Function Documentation
fmtmsg()
int fmtmsg (long classification, const char * label, int severity, const char * text, const char * action, const char * tag)
Definition at line 24 of file fmtmsg.c.
 {
     int ret = 0, i, consolefd, verb = 0;
     char *errstring = MM_NULLSEV, *cmsg = getenv("MSGVERB");
     char *const msgs[] = {
         "label", "severity", "text", "action", "tag", NULL
     };
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (severity == MM_HALT) errstring = "HALT: ";
     else if (severity == MM_ERROR) errstring = "ERROR: ";
     else if (severity == MM_WARNING) errstring = "WARNING: ";
     else if (severity == MM_INFO) errstring = "INFO: ";
     if (classification & MM_CONSOLE) {
         consolefd = open("/dev/console", O_WRONLY);
         if (consolefd < 0) {
             ret = MM_NOCON;
         } else {
             if (dprintf(consolefd, "%s%s%s%s%s%s%s%s\n",
                         label?label:"", label?": ":"",
                         severity?errstring:"", text?text:"",
                         action?"\nTO FIX: ":"",
                         action?action:"", action?" ":"",
                         tag?tag:"" )<1)
                 ret = MM_NOCON;
             close(consolefd);
         }
     }
     if (classification & MM_PRINT) {
         while (cmsg && cmsg[0]) {
             for(i=0; msgs[i]; i++) {
                 if (!_strcolcmp(msgs[i], cmsg)) break;
             }
             if (msgs[i] == NULL) {
                 //ignore MSGVERB-unrecognized component
                 verb = 0xFF;
                 break;
             } else {
                 verb |= (1 << i);
                 cmsg = strchr(cmsg, ':');
                 if (cmsg) cmsg++;
             }
         }
         if (!verb) verb = 0xFF;
         if (dprintf(2, "%s%s%s%s%s%s%s%s\n",
                     (verb&1 && label) ? label : "",
                     (verb&1 && label) ? ": " : "",
                     (verb&2 && severity) ? errstring : "",
                     (verb&4 && text) ? text : "",
                     (verb&8 && action) ? "\nTO FIX: " : "",
                     (verb&8 && action) ? action : "",
                     (verb&8 && action) ? " " : "",
                     (verb&16 && tag) ? tag : "" ) < 1)
             ret |= MM_NOMSG;
     }
     if ((ret & (MM_NOCON|MM_NOMSG)) == (MM_NOCON|MM_NOMSG))
         ret = MM_NOTOK;
     pthread_setcancelstate(cs, 0);
     return ret;
 }
References _strcolcmp(), close(), dprintf(), getenv, i, label, MM_CONSOLE, MM_ERROR, MM_HALT, MM_INFO, MM_NOCON, MM_NOMSG, MM_NOTOK, MM_NULLSEV, MM_PRINT, MM_WARNING, msgs, NULL, O_WRONLY, open(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), strchr(), and text.