Fennix Userspace: Userspace/apps/base/busybox/coreutils/df.c File Reference
df.c File Reference
#include <mntent.h>
#include <sys/statvfs.h>
#include "libbb.h"
#include "unicode.h"
Functions
static unsigned long kscale (unsigned long b, unsigned long bs)
int df_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
df_main()
int df_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 113 of file df.c.
 {
     unsigned long df_disp_hr = 1024;
     int status = EXIT_SUCCESS;
     unsigned opt;
     FILE *mount_table;
     struct mntent *mount_entry;
     struct statvfs s;
     enum {
         OPT_KILO     = (1 << 0),
         OPT_POSIX    = (1 << 1),
         OPT_FSTYPE   = (1 << 2),
         OPT_t        = (1 << 3),
         OPT_ALL      = (1 << 4) * ENABLE_FEATURE_DF_FANCY,
         OPT_INODE    = (1 << 5) * ENABLE_FEATURE_DF_FANCY,
         OPT_BSIZE    = (1 << 6) * ENABLE_FEATURE_DF_FANCY,
         OPT_HUMAN    = (1 << (4 + 3*ENABLE_FEATURE_DF_FANCY)) * ENABLE_FEATURE_HUMAN_READABLE,
         OPT_HUMANDEC = (1 << (5 + 3*ENABLE_FEATURE_DF_FANCY)) * ENABLE_FEATURE_HUMAN_READABLE,
         OPT_MEGA     = (1 << (6 + 3*ENABLE_FEATURE_DF_FANCY)) * ENABLE_FEATURE_HUMAN_READABLE,
     };
     const char *disp_units_hdr = NULL;
     char *chp, *opt_t;
     init_unicode();
     /* From the manpage of df from coreutils-6.10:
      * Disk space is shown in 1K blocks by default, unless the environment
      * variable POSIXLY_CORRECT is set, in which case 512-byte blocks are used.
      */
     if (getenv("POSIXLY_CORRECT")) /* TODO - a new libbb function? */
         df_disp_hr = 512;
     opt = getopt32(argv, "^"
             "kPTt:"
             IF_FEATURE_DF_FANCY("aiB:")
             IF_FEATURE_HUMAN_READABLE("hHm")
             "\0"
 #if ENABLE_FEATURE_HUMAN_READABLE && ENABLE_FEATURE_DF_FANCY
             "k-mB:m-Bk:B-km"
 #elif ENABLE_FEATURE_HUMAN_READABLE
             "k-m:m-k"
 #endif
             , &opt_t
             IF_FEATURE_DF_FANCY(, &chp)
     );
     if (opt & OPT_MEGA)
         df_disp_hr = 1024*1024;
     if (opt & OPT_BSIZE) {
         /* GNU coreutils 8.25 accepts "-BMiB" form too */
         int i;
         for (i = 0; kmg_i_suffixes[i].suffix[0]; i++) {
             if (strcmp(kmg_i_suffixes[i].suffix, chp) == 0) {
                 df_disp_hr = kmg_i_suffixes[i].mult;
                 goto got_it;
             }
         }
         /* Range used to disallow 0 */
         df_disp_hr = xatoul_range_sfx(chp, 1, ULONG_MAX, kmg_i_suffixes);
  got_it: ;
     }
     if (opt & (OPT_HUMAN|OPT_HUMANDEC)) {
         df_disp_hr = 0;
 //TODO: need to add support in make_human_readable_str() for "decimal human readable"
         //if (opt & OPT_HUMANDEC)
         //  df_disp_hr--;
         disp_units_hdr = "     Size";
     }
     if (opt & OPT_INODE)
         disp_units_hdr = "   Inodes";
     if (disp_units_hdr == NULL) {
 #if ENABLE_FEATURE_HUMAN_READABLE
         disp_units_hdr = xasprintf("%s-blocks",
             /* print df_disp_hr, show no fractionals,
              * use suffixes if OPT_POSIX is set in opt */
             make_human_readable_str(df_disp_hr, 0, !!(opt & OPT_POSIX))
         );
 #else
         disp_units_hdr = xasprintf("%lu-blocks", df_disp_hr);
 #endif
     }
     printf("Filesystem           %s%-15sUsed Available %s Mounted on\n",
             (opt & OPT_FSTYPE) ? "Type       " : "",
             disp_units_hdr,
             (opt & OPT_POSIX) ? "Capacity" : "Use%");
     mount_table = NULL;
     argv += optind;
     if (!argv[0]) {
         mount_table = setmntent(bb_path_mtab_file, "r");
         if (!mount_table)
             bb_simple_perror_msg_and_die(bb_path_mtab_file);
     }
     while (1) {
         const char *device;
         const char *mount_point;
         const char *fs_type;
         if (mount_table) {
             mount_entry = getmntent(mount_table);
             if (!mount_entry) {
                 endmntent(mount_table);
                 break;
             }
         } else {
             mount_point = *argv++;
             if (!mount_point)
                 break;
             mount_entry = find_mount_point(mount_point, 1);
             if (!mount_entry) {
                 bb_error_msg("%s: can't find mount point", mount_point);
  set_error:
                 status = EXIT_FAILURE;
                 continue;
             }
         }
         device = mount_entry->mnt_fsname;
         /* GNU coreutils 6.10 skips certain mounts, try to be compatible */
         if (ENABLE_FEATURE_SKIP_ROOTFS && strcmp(device, "rootfs") == 0)
             continue;
         mount_point = mount_entry->mnt_dir;
         fs_type = mount_entry->mnt_type;
         if (opt & OPT_t) {
             if (strcmp(fs_type, opt_t) != 0)
                 continue;
         }
         if (statvfs(mount_point, &s) != 0) {
             bb_simple_perror_msg(mount_point);
             goto set_error;
         }
         /* Some uclibc versions were seen to lose f_frsize
          * (kernel does return it, but then uclibc does not copy it)
          */
         if (s.f_frsize == 0)
             s.f_frsize = s.f_bsize;
         if ((s.f_blocks > 0) || !mount_table || (opt & OPT_ALL)) {
             unsigned long long blocks_used;
             unsigned long long blocks_total;
             unsigned blocks_percent_used;
             if (opt & OPT_INODE) {
                 s.f_blocks = s.f_files;
                 s.f_bavail = s.f_bfree = s.f_ffree;
                 s.f_frsize = 1;
                 if (df_disp_hr)
                     df_disp_hr = 1;
             }
             blocks_used = s.f_blocks - s.f_bfree;
             blocks_total = blocks_used + s.f_bavail;
             blocks_percent_used = blocks_total; /* 0% if blocks_total == 0, else... */
             if (blocks_total != 0) {
                 /* Downscale sizes for narrower division */
                 unsigned u;
                 while (blocks_total >= INT_MAX / 101) {
                     blocks_total >>= 1;
                     blocks_used >>= 1;
                 }
                 u = (unsigned)blocks_used * 100u + (unsigned)blocks_total / 2;
                 blocks_percent_used = u / (unsigned)blocks_total;
             }
 #ifdef WHY_WE_DO_IT_FOR_DEV_ROOT_ONLY
             if (strcmp(device, "/dev/root") == 0) {
                 /* Adjusts device to be the real root device,
                  * or leaves device alone if it can't find it */
                 device = find_block_device("/");
                 if (!device) {
                     goto set_error;
                 }
             }
 #endif
 #if ENABLE_UNICODE_SUPPORT
             {
                 uni_stat_t uni_stat;
                 char *uni_dev = unicode_conv_to_printable(&uni_stat, device);
                 if (uni_stat.unicode_width > 20 && !(opt & OPT_POSIX)) {
                     printf("%s\n%20s", uni_dev, "");
                 } else {
                     printf("%s%*s", uni_dev, 20 - (int)uni_stat.unicode_width, "");
                 }
                 free(uni_dev);
                 if (opt & OPT_FSTYPE) {
                     char *uni_type = unicode_conv_to_printable(&uni_stat, fs_type);
                     if (uni_stat.unicode_width > 10 && !(opt & OPT_POSIX))
                         printf(" %s\n%31s", uni_type, "");
                     else
                         printf(" %s%*s", uni_type, 10 - (int)uni_stat.unicode_width, "");
                     free(uni_type);
                 }
             }
 #else
             if (printf("\n%-20s" + 1, device) > 20 && !(opt & OPT_POSIX))
                 printf("\n%-20s", "");
             if (opt & OPT_FSTYPE) {
                 if (printf(" %-10s", fs_type) > 11 && !(opt & OPT_POSIX))
                     printf("\n%-30s", "");
             }
 #endif
 #if ENABLE_FEATURE_HUMAN_READABLE
             printf(" %9s ",
                 /* f_blocks x f_frsize / df_disp_hr, show one fractional,
                  * use suffixes if df_disp_hr == 0 */
                 make_human_readable_str(s.f_blocks, s.f_frsize, df_disp_hr));
             printf(" %9s " + 1,
                 /* EXPR x f_frsize / df_disp_hr, show one fractional,
                  * use suffixes if df_disp_hr == 0 */
                 make_human_readable_str((s.f_blocks - s.f_bfree),
                         s.f_frsize, df_disp_hr));
             printf("%9s %3u%% %s\n",
                 /* f_bavail x f_frsize / df_disp_hr, show one fractional,
                  * use suffixes if df_disp_hr == 0 */
                 make_human_readable_str(s.f_bavail, s.f_frsize, df_disp_hr),
                 blocks_percent_used, mount_point);
 #else
             printf(" %9lu %9lu %9lu %3u%% %s\n",
                 kscale(s.f_blocks, s.f_frsize),
                 kscale(s.f_blocks - s.f_bfree, s.f_frsize),
                 kscale(s.f_bavail, s.f_frsize),
                 blocks_percent_used, mount_point);
 #endif
         }
     }
     return status;
 }
References argv, bb_error_msg(), bb_path_mtab_file, bb_simple_perror_msg(), bb_simple_perror_msg_and_die(), device, endmntent(), EXIT_FAILURE, EXIT_SUCCESS, find_block_device(), find_mount_point(), free, getenv, getmntent(), getopt32(), i, init_unicode, INT_MAX, kmg_i_suffixes, kscale(), make_human_readable_str(), mntent::mnt_dir, mntent::mnt_fsname, mntent::mnt_type, mount_point, suffix_mult::mult, NULL, opt, OPT_ALL, OPT_t, optind, printf(), s, setmntent(), status, statvfs(), strcmp, suffix_mult::suffix, ULONG_MAX, unicode_conv_to_printable(), uni_stat_t::unicode_width, and xasprintf().
kscale()
static unsigned long kscale (unsigned long b, unsigned long bs) static
Definition at line 106 of file df.c.
 {
     return (b * (unsigned long long) bs + 1024/2) / 1024;
 }
Referenced by df_main().