Fennix Userspace: Userspace/apps/base/busybox/libbb/find_pid_by_name.c File Reference
find_pid_by_name.c File Reference
#include "libbb.h"
Functions
static int comm_match (procps_status_t *p, const char *procName)
pid_t *FAST_FUNC find_pid_by_name (const char *procName)
pid_t *FAST_FUNC pidlist_reverse (pid_t *pidList)
Function Documentation
comm_match()
static int comm_match (procps_status_t * p, const char * procName) static
Definition at line 40 of file find_pid_by_name.c.
 {
     int argv1idx;
     const char *argv1;
     if (strncmp(p->comm, procName, 15) != 0)
         return 0; /* comm does not match */
     /* In Linux, if comm is 15 chars, it is truncated.
      * (or maybe the name was exactly 15 chars, but there is
      * no way to know that) */
     if (p->comm[14] == '\0')
         return 1; /* comm is not truncated - matches */
     /* comm is truncated, but first 15 chars match.
      * This can be crazily_long_script_name.sh!
      * The telltale sign is basename(argv[1]) == procName */
     if (!p->argv0)
         return 0;
     argv1idx = strlen(p->argv0) + 1;
     if (argv1idx >= p->argv_len)
         return 0;
     argv1 = p->argv0 + argv1idx;
     if (strcmp(bb_basename(argv1), procName) != 0)
         return 0;
     return 1;
 }
References bb_basename(), p, strcmp, strlen(), and strncmp().
Referenced by find_pid_by_name().
find_pid_by_name()
pid_t* FAST_FUNC find_pid_by_name (const char * procName)
Definition at line 81 of file find_pid_by_name.c.
 {
     pid_t* pidList;
     int i = 0;
     procps_status_t* p = NULL;
     pidList = xzalloc(sizeof(*pidList));
     while ((p = procps_scan(p, PSSCAN_PID|PSSCAN_COMM|PSSCAN_ARGVN|PSSCAN_EXE))) {
         if (comm_match(p, procName)
         /* or we require argv0 to match (essential for matching reexeced /proc/self/exe)*/
          || (p->argv0 && strcmp(bb_basename(p->argv0), procName) == 0)
         /* or we require /proc/PID/exe link to match */
          || (p->exe && strcmp(
                     procName[0] == '/' ? p->exe /* support "pidof /path/to/binary" case too */
                             : bb_basename(p->exe),
                     procName
                     ) == 0)
         ) {
             pidList = xrealloc_vector(pidList, 2, i);
             pidList[i++] = p->pid;
         }
     }
     pidList[i] = 0;
     return pidList;
 }
References bb_basename(), comm_match(), i, NULL, p, procps_scan(), PSSCAN_ARGVN, PSSCAN_COMM, PSSCAN_EXE, PSSCAN_PID, strcmp, xrealloc_vector, and xzalloc().
Referenced by bootchartd_main(), display_verbose(), halt_main(), kill_main(), and pidof_main().
pidlist_reverse()
pid_t* FAST_FUNC pidlist_reverse (pid_t * pidList)
Definition at line 108 of file find_pid_by_name.c.
 {
     int i = 0;
     while (pidList[i])
         i++;
     if (--i >= 0) {
         pid_t k;
         int j;
         for (j = 0; i > j; i--, j++) {
             k = pidList[i];
             pidList[i] = pidList[j];
             pidList[j] = k;
         }
     }
     return pidList;
 }
References i, j, and k.
Referenced by pidof_main().