Fennix: Module::Module Class Reference
Module::Module Class Reference
#include <module.hpp>
Public Member Functions
ModuleCode ModuleLoadBindPCI (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn=false)
Load and bind a module to a PCI device.
ModuleCode ModuleLoadBindInterrupt (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn=false)
Load and bind a module to an interrupt.
ModuleCode ModuleLoadBindInput (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn=false)
Load and bind a module to an input device.
ModuleCode ModuleLoadBindProcess (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn=false)
Load and bind a module to a process.
std::vector< ModuleFile > GetModules ()
Get the currently loaded drivers.
void Panic ()
void UnloadAllModules ()
Unload all drivers.
bool UnloadModule (unsigned long id)
Unload a module.
int IOCB (unsigned long id, void *KCB)
Send a callback to a module.
ModuleCode LoadModule (vfs::Node *fildes)
Load a module.
void LoadModules ()
Module ()
~Module ()
Private Member Functions
NewLock (ModuleInitLock)
ModuleCode CallModuleEntryPoint (void *fex, bool BuiltIn=false)
Private Attributes
std::vector< ModuleFile > Modules
unsigned int modUIDs = 0
Detailed Description
Definition at line 113 of file module.hpp.
Constructor & Destructor Documentation
Module()
Module::Module::Module ()
Definition at line 253 of file module.cpp.
 {}
~Module()
Module::Module::~Module ()
Definition at line 255 of file module.cpp.
     {
         debug("Destructor called");
         this->UnloadAllModules();
     }
References debug.
Member Function Documentation
CallModuleEntryPoint()
ModuleCode Module::Module::CallModuleEntryPoint (void * fex, bool BuiltIn = false) private
Definition at line 129 of file module.cpp.
     {
         ModuleCode ret{};
         KernelAPI modKAPI = KernelAPITemplate;
         modKAPI.Info.modUniqueID = modUIDs++;
         modKAPI.Info.KernelDebug = DebuggerIsAttached;
         debug("Calling module entry point ( %#lx %ld )", (unsigned long)fex, modKAPI.Info.modUniqueID);
         if (!BuiltIn)
         {
             modKAPI.Info.Offset = (unsigned long)fex;
             debug("MODULE: %s HAS MODULE ID %ld",
                   ((FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS))->Module.Name,
                   modKAPI.Info.modUniqueID);
             ret = ((ModuleCode(*)(KernelAPI *))((uintptr_t)((Fex *)fex)->EntryPoint + (uintptr_t)fex))(((KernelAPI *)&modKAPI));
         }
         else
         {
             debug("MODULE: BUILTIN HAS MODULE ID %ld", modKAPI.Info.modUniqueID);
             ret = ((ModuleCode(*)(KernelAPI *))((uintptr_t)fex))(((KernelAPI *)&modKAPI));
         }
         if (ModuleCode::OK != ret)
         {
             modUIDs--;
             return ret;
         }
         return ModuleCode::OK;
     }
References debug, DebuggerIsAttached, EntryPoint, EXTENDED_SECTION_ADDRESS, KernelAPI::Info, KernelAPITemplate, KernelAPI::KAPIInfo::KernelDebug, KernelAPI::KAPIInfo::modUniqueID, KernelAPI::KAPIInfo::Offset, and OK.
GetModules()
std::vector<ModuleFile> Module::Module::GetModules () inline
Get the currently loaded drivers.
This function returns a clone of the drivers vector. This means that the vector can be modified without affecting the drivers.
Returns
std::vector<ModuleFile> A clone of the drivers vector.
Definition at line 182 of file module.hpp.
 { return Modules; }
Referenced by KernelMainThread(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), and StartKernelShell().
IOCB()
int Module::Module::IOCB (unsigned long id, void * KCB)
Send a callback to a module.
This function will send a callback to a module with the given module unique ID. This is used to communicate with drivers.
Parameters
id The module unique ID.
KCB The
See also
KernelCallback structure.
Returns
int The result of the operation.
Definition at line 116 of file module.cpp.
     {
         foreach (auto Drv in Modules)
         {
             if (Drv.modUniqueID != id)
                 continue;
             FexExtended *fexE = (FexExtended *)Drv.ExtendedHeaderAddress;
             return ((int (*)(void *))((uintptr_t)fexE->Module.Callback + (uintptr_t)Drv.Address))(KCB);
         }
         return -1;
     }
References FexExtended::Module, and return().
Referenced by Disk::Manager::FetchDisks(), NetworkInterfaceManager::NetworkInterface::FetchNetworkCards(), Panic(), NetworkInterfaceManager::NetworkInterface::Send(), StartKernelShell(), and UnloadAllModules().
LoadModule()
ModuleCode Module::Module::LoadModule (vfs::Node * fildes)
Load a module.
Parameters
fildes The file descriptor of the module file.
Returns
ModuleCode The result of the operation.
Definition at line 162 of file module.cpp.
     {
         Fex DrvHdr;
         fildes->read((uint8_t *)&DrvHdr, sizeof(Fex), 0);
         if (DrvHdr.Magic[0] != 'F' || DrvHdr.Magic[1] != 'E' || DrvHdr.Magic[2] != 'X' || DrvHdr.Magic[3] != '\0')
             return ModuleCode::INVALID_FEX_HEADER;
         debug("Fex Magic: \"%s\"; Type: %d; OS: %d; EntryPoint: %#lx", DrvHdr.Magic, DrvHdr.Type, DrvHdr.OS, DrvHdr.EntryPoint);
         if (DrvHdr.Type != FexFormatType::FexFormatType_Module)
             return ModuleCode::NOT_MODULE;
         FexExtended fexE;
         fildes->read((uint8_t *)&fexE, sizeof(FexExtended), EXTENDED_SECTION_ADDRESS);
         debug("Name: \"%s\"; Type: %d; Callback: %#lx", fexE.Module.Name, fexE.Module.Type, fexE.Module.Callback);
         Memory::SmartHeap ModuleAddress(fildes->Size);
         fildes->read(ModuleAddress, fildes->Size, 0);
         switch (fexE.Module.Bind.Type)
         {
         case ModuleBindType::BIND_PCI:
             return this->ModuleLoadBindPCI(ModuleAddress, fildes->Size);
         case ModuleBindType::BIND_INTERRUPT:
             return this->ModuleLoadBindInterrupt(ModuleAddress, fildes->Size);
         case ModuleBindType::BIND_PROCESS:
             return this->ModuleLoadBindProcess(ModuleAddress, fildes->Size);
         case ModuleBindType::BIND_INPUT:
             return this->ModuleLoadBindInput(ModuleAddress, fildes->Size);
         default:
         {
             error("Unknown module bind type: %d", fexE.Module.Bind.Type);
             return ModuleCode::UNKNOWN_MODULE_BIND_TYPE;
         }
         }
     }
References BIND_INPUT, BIND_INTERRUPT, BIND_PCI, BIND_PROCESS, debug, Fex::EntryPoint, error, EXTENDED_SECTION_ADDRESS, FexFormatType_Module, Module::INVALID_FEX_HEADER, Fex::Magic, FexExtended::Module, Module::NOT_MODULE, Fex::OS, vfs::Node::read(), vfs::Node::Size, Fex::Type, and Module::UNKNOWN_MODULE_BIND_TYPE.
LoadModules()
void Module::Module::LoadModules ()
Definition at line 201 of file module.cpp.
     {
         SmartCriticalSection(ModuleInitLock);
         const char *ModuleConfigFile = new char[256];
         assert(strlen(Config.ModuleDirectory) < 255 - 12);
         strcpy((char *)ModuleConfigFile, Config.ModuleDirectory);
         strcat((char *)ModuleConfigFile, "/config.ini");
         fixme("Loading module config file: %s", ModuleConfigFile);
         delete[] ModuleConfigFile;
         debug("Loading built-in modules");
         StartBuiltInModules();
         RefNode *ModuleDirectory = fs->Open(Config.ModuleDirectory);
         if (!ModuleDirectory)
         {
             KPrint("\eE85230Failed to open %s: %d)",
                    Config.ModuleDirectory, errno);
             return;
         }
         debug("Loading modules from %s", Config.ModuleDirectory);
         foreach (auto DrvFile in ModuleDirectory->node->Children)
         {
             if (DrvFile->Type != vfs::NodeType::FILE)
                 continue;
             if (cwk_path_has_extension(DrvFile->Name))
             {
                 const char *extension;
                 size_t extension_length;
                 cwk_path_get_extension(DrvFile->Name, &extension, &extension_length);
                 debug("File: %s; Extension: %s", DrvFile->Name, extension);
                 if (strcmp(extension, ".fex") == 0)
                 {
                     uintptr_t ret = this->LoadModule(DrvFile);
                     char *RetString = new char[256];
                     if (ret == ModuleCode::OK)
                         strcpy(RetString, "\e058C19OK");
                     else if (ret == ModuleCode::NOT_AVAILABLE)
                         strcpy(RetString, "\eFF7900NOT AVAILABLE");
                     else
                         strcpy(RetString, "\eE85230FAILED");
                     KPrint("%s %s %#lx", DrvFile->Name, RetString, ret);
                     delete[] RetString;
                 }
             }
         }
         delete ModuleDirectory;
     }
References assert, cwk_path_get_extension(), cwk_path_has_extension(), debug, errno, fixme, fs, KPrint(), NOT_AVAILABLE, OK, vfs::Virtual::Open(), StartBuiltInModules(), strcat, strcmp, strcpy, and strlen().
Referenced by KernelMainThread().
ModuleLoadBindInput()
ModuleCode Module::Module::ModuleLoadBindInput (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn = false)
Load and bind a module to an input device.
This function will attach the module to the input device.
Parameters
ModuleAddress The address of the module. The file will be copied to a new location.
Size The size of the module.
IsBuiltIn If the module is built-in, the
ModuleAddress will be
See also
BuiltInModuleInfo and the
Parameters
Size will be ignored.
Returns
ModuleCode The result of the operation.
Definition at line 34 of file bind_input.cpp.
     {
         stub;
       UNUSED(ModuleAddress);
       UNUSED(Size);
       UNUSED(IsBuiltIn);
         return ModuleCode::NOT_IMPLEMENTED;
     }
References NOT_IMPLEMENTED, Size, stub, and Module::UNUSED().
ModuleLoadBindInterrupt()
ModuleCode Module::Module::ModuleLoadBindInterrupt (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn = false)
Load and bind a module to an interrupt.
This function will search for an interrupt with the given IRQ. If the interrupt is found, the module will be loaded and bound to the interrupt.
Parameters
ModuleAddress The address of the module. The file will be copied to a new location.
Size The size of the module.
IsBuiltIn If the module is built-in, the
ModuleAddress will be
See also
BuiltInModuleInfo and the
Parameters
Size will be ignored.
Returns
ModuleCode The result of the operation.
Definition at line 34 of file bind_interrupt.cpp.
     {
         Memory::VirtualMemoryArea *vma = new Memory::VirtualMemoryArea(nullptr);
         BuiltInModuleInfo *bidi = (BuiltInModuleInfo *)ModuleAddress;
         Fex *fex = nullptr;
         if (!IsBuiltIn)
         {
             fex = (Fex *)vma->RequestPages(TO_PAGES(Size + 1));
             memcpy(fex, (void *)ModuleAddress, Size);
             debug("Module allocated at %#lx-%#lx", fex, (uintptr_t)fex + Size);
         }
         else
             fex = (Fex *)bidi->EntryPoint;
         ModuleCode ret = CallModuleEntryPoint(fex, IsBuiltIn);
         if (ret != ModuleCode::OK)
         {
             delete vma;
             return ret;
         }
         if (IsBuiltIn)
             fex = 0x0; /* Addresses are absolute if built-in. */
         FexExtended *fexE = IsBuiltIn ? (FexExtended *)bidi->ExtendedHeader : (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         debug("Starting driver %s", fexE->Module.Name);
         switch (fexE->Module.Type)
         {
         case FexModuleType::FexModuleType_Generic:
         case FexModuleType::FexModuleType_Display:
         case FexModuleType::FexModuleType_Network:
         case FexModuleType::FexModuleType_Storage:
         case FexModuleType::FexModuleType_FileSystem:
         case FexModuleType::FexModuleType_Input:
         case FexModuleType::FexModuleType_Audio:
         {
             FexExtended *DriverExtendedHeader = (FexExtended *)vma->RequestPages(TO_PAGES(sizeof(FexExtended) + 1));
             memcpy(DriverExtendedHeader, fexE, sizeof(FexExtended));
             ModuleFile DrvFile = {
                 .Enabled = true,
                 .BuiltIn = IsBuiltIn,
                 .modUniqueID = this->modUIDs - 1,
                 .Address = (void *)fex,
                 .ExtendedHeaderAddress = (void *)DriverExtendedHeader,
                 .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexE->Module.InterruptCallback),
                 .vma = vma,
             };
             if (fexE->Module.InterruptCallback)
             {
                 for (uint16_t i = 0; i < sizeof(fexE->Module.Bind.Interrupt.Vector) / sizeof(fexE->Module.Bind.Interrupt.Vector[0]); i++)
                 {
                     if (fexE->Module.Bind.Interrupt.Vector[i] == 0)
                         break;
                     DrvFile.InterruptHook[i] = new ModuleInterruptHook(fexE->Module.Bind.Interrupt.Vector[i], DrvFile);
                 }
             }
             KernelCallback KCallback{};
             KCallback.RawPtr = nullptr;
             KCallback.Reason = CallbackReason::ConfigurationReason;
             ModuleCode CallbackRet = ((ModuleCode(*)(KernelCallback *))((uintptr_t)fexE->Module.Callback + (uintptr_t)fex))(&KCallback);
             if (CallbackRet != ModuleCode::OK)
             {
                 error("Module %s returned error %d", fexE->Module.Name, CallbackRet);
                 delete vma;
                 return CallbackRet;
             }
             Modules.push_back(DrvFile);
             return ModuleCode::OK;
         }
         default:
         {
             warn("Unknown driver type: %d", fexE->Module.Type);
             delete vma;
             return ModuleCode::UNKNOWN_MODULE_TYPE;
         }
         }
     }
References ConfigurationReason, debug, Module::ModuleFile::Enabled, Module::BuiltInModuleInfo::EntryPoint, error, EXTENDED_SECTION_ADDRESS, Module::BuiltInModuleInfo::ExtendedHeader, FexModuleType_Audio, FexModuleType_Display, FexModuleType_FileSystem, FexModuleType_Generic, FexModuleType_Input, FexModuleType_Network, FexModuleType_Storage, i, Module::ModuleFile::InterruptHook, memcpy, FexExtended::Module, OK, Memory::VirtualMemoryArea::RequestPages(), Size, TO_PAGES, Module::UNKNOWN_MODULE_TYPE, and warn.
Referenced by StartATA(), StartPS2Keyboard(), StartPS2Mouse(), and StartVMwareMouse().
ModuleLoadBindPCI()
ModuleCode Module::Module::ModuleLoadBindPCI (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn = false)
Load and bind a module to a PCI device.
This function will search for a PCI device with the given VendorID and DeviceID. If the device is found, the module will be loaded and bound to the device.
Parameters
ModuleAddress The address of the module. The file will be copied to a new location.
Size The size of the module.
IsBuiltIn If the module is built-in, the
ModuleAddress will be
See also
BuiltInModuleInfo and the
Parameters
Size will be ignored.
Returns
ModuleCode The result of the operation.
Definition at line 34 of file bind_pci.cpp.
     {
         FexExtended *DrvExtHdr = (FexExtended *)(ModuleAddress + EXTENDED_SECTION_ADDRESS);
         if (IsBuiltIn)
             DrvExtHdr = (FexExtended *)(((BuiltInModuleInfo *)ModuleAddress)->ExtendedHeader);
         uint16_t SizeOfVendorID = sizeof(DrvExtHdr->Module.Bind.PCI.VendorID) /
                                   sizeof(DrvExtHdr->Module.Bind.PCI.VendorID[0]);
         uint16_t SizeOfDeviceID = sizeof(DrvExtHdr->Module.Bind.PCI.DeviceID) /
                                   sizeof(DrvExtHdr->Module.Bind.PCI.DeviceID[0]);
         for (uint16_t vID = 0; vID < SizeOfVendorID; vID++)
         {
             for (uint16_t dID = 0; dID < SizeOfDeviceID; dID++)
             {
                 if (DrvExtHdr->Module.Bind.PCI.VendorID[vID] == 0 ||
                     DrvExtHdr->Module.Bind.PCI.DeviceID[dID] == 0)
                     continue;
                 std::vector<PCI::PCIDevice> devices =
                     PCIManager->FindPCIDevice(DrvExtHdr->Module.Bind.PCI.VendorID[vID],
                                               DrvExtHdr->Module.Bind.PCI.DeviceID[dID]);
                 if (devices.size() == 0)
                     continue;
                 foreach (auto Device in devices)
                 {
                     debug("[%ld] VendorID: %#x; DeviceID: %#x",
                           devices.size(), Device.Header->VendorID,
                           Device.Header->DeviceID);
                     Memory::VirtualMemoryArea *vma = new Memory::VirtualMemoryArea(nullptr);
                     BuiltInModuleInfo *bidi = (BuiltInModuleInfo *)ModuleAddress;
                     Fex *fex = nullptr;
                     if (!IsBuiltIn)
                     {
                         fex = (Fex *)vma->RequestPages(TO_PAGES(Size + 1));
                         memcpy(fex, (void *)ModuleAddress, Size);
                         debug("Module allocated at %#lx-%#lx", fex, (uintptr_t)fex + Size);
                     }
                     else
                         fex = (Fex *)bidi->EntryPoint;
                     ModuleCode ret = CallModuleEntryPoint(fex, IsBuiltIn);
                     if (ret != ModuleCode::OK)
                     {
                         delete vma;
                         return ret;
                     }
                     if (IsBuiltIn)
                         fex = 0x0; /* Addresses are absolute if built-in. */
                     FexExtended *fexE = IsBuiltIn ? (FexExtended *)bidi->ExtendedHeader : (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
                     debug("Starting driver %s", fexE->Module.Name);
                     PCIManager->MapPCIAddresses(Device);
                     switch (fexE->Module.Type)
                     {
                     case FexModuleType::FexModuleType_Generic:
                     case FexModuleType::FexModuleType_Display:
                     case FexModuleType::FexModuleType_Network:
                     case FexModuleType::FexModuleType_Storage:
                     case FexModuleType::FexModuleType_FileSystem:
                     case FexModuleType::FexModuleType_Input:
                     case FexModuleType::FexModuleType_Audio:
                     {
                         FexExtended *DriverExtendedHeader = (FexExtended *)vma->RequestPages(TO_PAGES(sizeof(FexExtended) + 1));
                         memcpy(DriverExtendedHeader, fexE, sizeof(FexExtended));
                         ModuleFile DrvFile = {
                             .Enabled = true,
                             .BuiltIn = IsBuiltIn,
                             .modUniqueID = this->modUIDs - 1,
                             .Address = (void *)fex,
                             .ExtendedHeaderAddress = (void *)DriverExtendedHeader,
                             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexE->Module.InterruptCallback),
                             .vma = vma,
                         };
                         if (fexE->Module.InterruptCallback)
                             DrvFile.InterruptHook[0] = new ModuleInterruptHook(((int)((PCI::PCIHeader0 *)Device.Header)->InterruptLine), DrvFile);
                         KernelCallback KCallback{};
                         KCallback.RawPtr = Device.Header;
                         KCallback.Reason = CallbackReason::ConfigurationReason;
                         ModuleCode CallbackRet = ((ModuleCode(*)(KernelCallback *))((uintptr_t)fexE->Module.Callback + (uintptr_t)fex))(&KCallback);
                         if (CallbackRet != ModuleCode::OK)
{
                             error("Module %s returned error %d", fexE->Module.Name, CallbackRet);
                             delete vma;
                             return CallbackRet;
                         }
                         Modules.push_back(DrvFile);
                         return ModuleCode::OK;
                     }
                     default:
                     {
                         warn("Unknown driver type: %d", fexE->Module.Type);
                         delete vma;
                         return ModuleCode::UNKNOWN_MODULE_TYPE;
                     }
                     }
                 }
             }
         }
         return ModuleCode::PCI_DEVICE_NOT_FOUND;
     }
References ConfigurationReason, debug, Module::ModuleFile::Enabled, Module::BuiltInModuleInfo::EntryPoint, error, EXTENDED_SECTION_ADDRESS, Module::BuiltInModuleInfo::ExtendedHeader, FexModuleType_Audio, FexModuleType_Display, FexModuleType_FileSystem, FexModuleType_Generic, FexModuleType_Input, FexModuleType_Network, FexModuleType_Storage, PCI::PCI::FindPCIDevice(), Module::ModuleFile::InterruptHook, PCI::PCI::MapPCIAddresses(), memcpy, FexExtended::Module, OK, Module::PCI_DEVICE_NOT_FOUND, PCIManager, Memory::VirtualMemoryArea::RequestPages(), Size, TO_PAGES, Module::UNKNOWN_MODULE_TYPE, and warn.
Referenced by StartAC97(), StartAHCI(), StartGigabit(), StartPCNET(), and StartRTL8139().
ModuleLoadBindProcess()
ModuleCode Module::Module::ModuleLoadBindProcess (uintptr_t ModuleAddress, size_t Size, bool IsBuiltIn = false)
Load and bind a module to a process.
This function will attach the module to the process.
Parameters
ModuleAddress The address of the module. The file will be copied to a new location.
Size The size of the module.
IsBuiltIn If the module is built-in, the
ModuleAddress will be
See also
BuiltInModuleInfo and the
Parameters
Size will be ignored.
Returns
ModuleCode The result of the operation.
Definition at line 34 of file bind_process.cpp.
     {
         stub;
       UNUSED(ModuleAddress);
       UNUSED(Size);
       UNUSED(IsBuiltIn);
         return ModuleCode::NOT_IMPLEMENTED;
     }
References NOT_IMPLEMENTED, Size, stub, and Module::UNUSED().
NewLock()
Module::Module::NewLock (ModuleInitLock) private
Panic()
void Module::Module::Panic ()
Definition at line 37 of file module.cpp.
     {
         debug("%ld modules loaded, [modUIDs: %ld]", Modules.size(), modUIDs - 1);
         foreach (auto Drv in Modules)
         {
             KernelCallback callback{};
             callback.Reason = StopReason;
             ModuleManager->IOCB(Drv.modUniqueID, &callback);
             for (size_t j = 0; j < sizeof(Drv.InterruptHook) / sizeof(Drv.InterruptHook[0]); j++)
             {
                 if (!Drv.InterruptHook[j])
                     continue;
                 Drv.InterruptHook[j]->Disable();
                 debug("Interrupt hook %#lx disabled", Drv.InterruptHook[j]);
             }
         }
     }
References callback, debug, IOCB(), j, ModuleManager, and StopReason.
Referenced by CrashHandler::Handle().
UnloadAllModules()
void Module::Module::UnloadAllModules ()
Unload all drivers.
This function will unload all drivers.
Definition at line 58 of file module.cpp.
     {
         debug("%ld modules loaded, [modUIDs: %ld]", Modules.size(), modUIDs - 1);
         foreach (auto Drv in Modules)
         {
             KernelCallback callback{};
             callback.Reason = StopReason;
             debug("Stopping & unloading module %ld [%#lx]", Drv.modUniqueID, Drv.Address);
             ModuleManager->IOCB(Drv.modUniqueID, &callback);
             for (size_t j = 0; j < sizeof(Drv.InterruptHook) / sizeof(Drv.InterruptHook[0]); j++)
             {
                 if (!Drv.InterruptHook[j])
                     continue;
                 debug("Interrupt hook %#lx", Drv.InterruptHook[j]);
                 delete Drv.InterruptHook[j], Drv.InterruptHook[j] = nullptr;
             }
             if (Drv.vma)
                 delete Drv.vma, Drv.vma = nullptr;
         }
         Modules.clear();
     }
References callback, debug, IOCB(), j, ModuleManager, and StopReason.
UnloadModule()
bool Module::Module::UnloadModule (unsigned long id)
Unload a module.
This function will unload a module with the given module unique ID. It will free the memory and remove the module from the drivers vector.
Parameters
id The module unique ID.
Returns
true If the module was found and unloaded successfully, false otherwise.
Definition at line 84 of file module.cpp.
     {
         debug("Searching for module %ld", id);
         forItr(Drv, Modules)
         {
             if (Drv->modUniqueID != id)
                 continue;
             KernelCallback callback{};
             callback.Reason = StopReason;
             debug("Stopping & unloading module %ld [%#lx]", Drv->modUniqueID, Drv->Address);
             this->IOCB(Drv->modUniqueID, &callback);
             for (size_t j = 0; j < sizeof(Drv->InterruptHook) / sizeof(Drv->InterruptHook[0]); j++)
             {
                 if (!Drv->InterruptHook[j])
                     continue;
                 debug("Interrupt hook %#lx", Drv->InterruptHook[j]);
                 delete Drv->InterruptHook[j], Drv->InterruptHook[j] = nullptr;
             }
             if (Drv->vma)
                 delete Drv->vma, Drv->vma = nullptr;
             Modules.erase(Drv);
             return true;
         }
         return false;
     }
References callback, debug, j, and StopReason.
Field Documentation
modUIDs
unsigned int Module::Module::modUIDs = 0 private
Definition at line 119 of file module.hpp.
Modules
std::vector<ModuleFile> Module::Module::Modules private
Definition at line 118 of file module.hpp.
The documentation for this class was generated from the following files:
Kernel/include/module.hpp
Kernel/core/module/module.cpp
Kernel/core/module/module_binding/bind_input.cpp
Kernel/core/module/module_binding/bind_interrupt.cpp
Kernel/core/module/module_binding/bind_pci.cpp
Kernel/core/module/module_binding/bind_process.cpp