Fennix: Userspace/mlibc/options/ansi/generic/file-io.cpp File Reference
file-io.cpp File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <abi-bits/fcntl.h>
#include <frg/allocation.hpp>
#include <frg/mutex.hpp>
#include <mlibc/allocator.hpp>
#include <mlibc/file-io.hpp>
#include <mlibc/ansi-sysdeps.hpp>
#include <mlibc/lock.hpp>
Data Structures
struct anonymous_namespace{file-io.cpp}::stdio_guard
Namespaces
mlibc
mlibc::anonymous_namespace{file-io.cpp}
anonymous_namespace{file-io.cpp}
Typedefs
using mlibc::anonymous_namespace{file-io.cpp}::file_list = frg::intrusive_list< abstract_file, frg::locate_member< abstract_file, frg::default_list_hook< abstract_file >, &abstract_file::_list_hook > >
Functions
file_list & mlibc::anonymous_namespace{file-io.cpp}::global_file_list ()
int fileno_unlocked (FILE *file_base)
int fileno (FILE *file_base)
FILE * fopen (const char *path, const char *mode)
int fclose (FILE *file_base)
int fseek (FILE *file_base, long offset, int whence)
long ftell (FILE *file_base)
int fflush_unlocked (FILE *file_base)
int fflush (FILE *file_base)
int setvbuf (FILE *file_base, char *, int mode, size_t)
void rewind (FILE *file_base)
int ungetc (int c, FILE *file_base)
Variables
constexpr bool mlibc::anonymous_namespace{file-io.cpp}::globallyDisableBuffering = false
constexpr size_t mlibc::anonymous_namespace{file-io.cpp}::ungetBufferSize = 8
mlibc::fd_file anonymous_namespace{file-io.cpp}::stdin_file {0}
mlibc::fd_file anonymous_namespace{file-io.cpp}::stdout_file {1}
mlibc::fd_file anonymous_namespace{file-io.cpp}::stderr_file {2, nullptr, true}
struct anonymous_namespace{file-io.cpp}::stdio_guard anonymous_namespace{file-io.cpp}::global_stdio_guard
FILE * stderr = &stderr_file
FILE * stdin = &stdin_file
FILE * stdout = &stdout_file
Function Documentation
fclose()
int fclose (FILE * file_base)
Definition at line 604 of file file-io.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     int e = 0;
     if(file->flush())
         e = EOF;
     if(file->close())
         e = EOF;
     file->dispose();
     return e;
 }
References EOF.
fflush()
int fflush (FILE * file_base)
Definition at line 651 of file file-io.cpp.
{
     if(file_base == NULL) {
         // Only flush the files but do not close them.
         for(auto it : mlibc::global_file_list()) {
             frg::unique_lock lock(it->_lock);
             if(int e = it->flush(); e)
                 mlibc::infoLogger() << "mlibc warning: Failed to flush file"
                     << frg::endlog;
         }
         return 0;
     }
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     if (file->flush())
         return EOF;
     return 0;
 }
References EOF, mlibc::anonymous_namespace{file-io.cpp}::global_file_list(), mlibc::infoLogger, lock, and NULL.
fflush_unlocked()
int fflush_unlocked (FILE * file_base)
Definition at line 636 of file file-io.cpp.
{
     if(file_base == NULL) {
         // Only flush the files but do not close them.
         for(auto it : mlibc::global_file_list()) {
             if(int e = it->flush(); e)
                 mlibc::infoLogger() << "mlibc warning: Failed to flush file"
                     << frg::endlog;
         }
         return 0;
     }
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(file->flush())
         return EOF;
     return 0;
 }
References EOF, mlibc::anonymous_namespace{file-io.cpp}::global_file_list(), mlibc::infoLogger, and NULL.
fileno()
int fileno (FILE * file_base)
Definition at line 585 of file file-io.cpp.
{
     auto file = static_cast<mlibc::fd_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     return fileno_unlocked(file_base);
 }
References fileno_unlocked(), and lock.
Referenced by _rl_init_terminal_io(), _rl_input_available(), _rl_nchars_available(), _rl_sigwinch_resize_terminal(), check_dev_tty(), command_substitute(), decode_prompt_string(), do_redirection_internal(), getc_with_restart(), I_ConsoleStdout(), initialize_job_control(), main(), move_to_high_fd(), open_shell_script(), rl_deprep_terminal(), rl_gather_tyi(), rl_getc(), rl_insert_close(), rl_prep_terminal(), rl_reset_screen_size(), rl_resize_terminal(), rl_restart_output(), rl_stop_output(), rltty_set_default_bindings(), run_startup_files(), set_bash_input(), and xtrace_set().
fileno_unlocked()
int fileno_unlocked (FILE * file_base)
Definition at line 580 of file file-io.cpp.
{
     auto file = static_cast<mlibc::fd_file *>(file_base);
     return file->fd();
 }
References mlibc::fd_file::fd().
Referenced by fileno().
fopen()
FILE* fopen (const char * path, const char * mode)
Definition at line 591 of file file-io.cpp.
{
     int flags = mlibc::fd_file::parse_modestring(mode);
     int fd;
     if(int e = mlibc::sys_open(path, flags, 0666, &fd); e) {
         errno = e;
         return nullptr;
     }
     return frg::construct<mlibc::fd_file>(getAllocator(), fd,
             mlibc::file_dispose_cb<mlibc::fd_file>);
 }
References errno, flags, getAllocator(), mlibc::fd_file::parse_modestring(), and mlibc::sys_open().
fseek()
int fseek (FILE * file_base, long offset, int whence)
Definition at line 615 of file file-io.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     if(int e = file->seek(offset, whence); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, lock, offset, and mlibc::whence.
ftell()
long ftell (FILE * file_base)
Definition at line 625 of file file-io.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     off_t current_offset;
     if(int e = file->tell(&current_offset); e) {
         errno = e;
         return -1;
     }
     return current_offset;
 }
References errno, and lock.
rewind()
void rewind (FILE * file_base)
Definition at line 696 of file file-io.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     file->seek(0, SEEK_SET);
     file_base->__status_bits &= ~(__MLIBC_EOF_BIT | __MLIBC_ERROR_BIT);
 }
References __MLIBC_EOF_BIT, __MLIBC_ERROR_BIT, lock, and SEEK_SET.
Referenced by setgrent(), setpwent(), and test().
setvbuf()
int setvbuf (FILE * file_base, char * __restrict, int mode, size_t)
Definition at line 670 of file file-io.cpp.
{
     // TODO: We could also honor the buffer, but for now use just set the mode.
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(mode == _IONBF) {
         if(int e = file->update_bufmode(mlibc::buffer_mode::no_buffer); e) {
             errno = e;
             return -1;
         }
     }else if(mode == _IOLBF) {
         if(int e = file->update_bufmode(mlibc::buffer_mode::line_buffer); e) {
             errno = e;
             return -1;
         }
     }else if(mode == _IOFBF) {
         if(int e = file->update_bufmode(mlibc::buffer_mode::full_buffer); e) {
             errno = e;
             return -1;
         }
     }else{
         errno = EINVAL;
         return -1;
     }
     return 0;
 }
References _IOFBF, _IOLBF, _IONBF, EINVAL, errno, mlibc::full_buffer, mlibc::line_buffer, and mlibc::no_buffer.
Referenced by setbuf(), setbuffer(), setlinebuf(), and sh_setlinebuf().
ungetc()
int ungetc (int c, FILE * file_base)
Definition at line 703 of file file-io.cpp.
{
     if (c == EOF)
         return EOF;
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     return file->unget(c);
 }
References c, EOF, and lock.
Referenced by __fgetwc_unlocked_internal(), fgetln(), and get_charset_aliases().
Variable Documentation
stderr
FILE* stderr = &stderr_file
Definition at line 576 of file file-io.cpp.
stdin
FILE* stdin = &stdin_file
Definition at line 577 of file file-io.cpp.
stdout
FILE* stdout = &stdout_file
Definition at line 578 of file file-io.cpp.