Fennix: Userspace/musl/src/dirent/closedir.c File Reference
closedir.c File Reference
#include <dirent.h>
#include <unistd.h>
#include <stdlib.h>
#include "__dirent.h"
Functions
int closedir (DIR *dir)
Function Documentation
closedir()
int closedir (DIR * dir)
Definition at line 6 of file closedir.c.
 {
     int ret = close(dir->fd);
     free(dir);
     return ret;
 }
References close(), __dirstream::fd, free, and ret.
Referenced by do_glob(), do_nftw(), scandir(), and test_dirent().