Fennix Userspace: Userspace/apps/base/bash/examples/loadables/id.c File Reference
id.c File Reference
#include <config.h>
#include <stdio.h>
#include "bashtypes.h"
#include <pwd.h>
#include <grp.h>
#include "bashansi.h"
#include <sys/param.h>
#include "shell.h"
#include "builtins.h"
#include "stdc.h"
#include "common.h"
#include "bashgetopt.h"
Macros
#define ID_ALLGROUPS 0x001 /* -G */
#define ID_GIDONLY 0x002 /* -g */
#define ID_USENAME 0x004 /* -n */
#define ID_USEREAL 0x008 /* -r */
#define ID_USERONLY 0x010 /* -u */
#define ID_FLAGSET(s) ((id_flags & (s)) != 0)
Functions
struct passwd * getpwuid ()
struct group * getgrgid ()
static int inituser ()
static int id_pruser ()
static int id_prgrp ()
static int id_prgroups ()
static int id_prall ()
int id_builtin (WORD_LIST *list)
static int inituser (char *uname)
static int id_pruser (int uid)
static int id_prgrp (int gid)
static int id_prgroups (char *uname)
static int id_prall (char *uname)
Variables
static int id_flags
static uid_t ruid
static uid_t euid
static gid_t rgid
static gid_t egid
static char * id_user
char * id_doc []
struct builtin id_struct
Macro Definition Documentation
ID_ALLGROUPS
#define ID_ALLGROUPS 0x001 /* -G */
Definition at line 54 of file id.c.
ID_FLAGSET
#define ID_FLAGSET (s) ((id_flags & (s)) != 0)
Definition at line 60 of file id.c.
ID_GIDONLY
#define ID_GIDONLY 0x002 /* -g */
Definition at line 55 of file id.c.
ID_USENAME
#define ID_USENAME 0x004 /* -n */
Definition at line 56 of file id.c.
ID_USEREAL
#define ID_USEREAL 0x008 /* -r */
Definition at line 57 of file id.c.
ID_USERONLY
#define ID_USERONLY 0x010 /* -u */
Definition at line 58 of file id.c.
Function Documentation
getgrgid()
struct group* getgrgid ()
Referenced by id_prall(), id_prgrp(), main(), printsome(), and printst().
getpwuid()
struct passwd* getpwuid ()
Referenced by id_prall(), id_pruser(), main(), printsome(), and printst().
id_builtin()
int id_builtin (WORD_LIST * list)
Definition at line 77 of file id.c.
 {
   int opt;
   char *user;
   id_flags = 0;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "Ggnru")) != -1)
     {
       switch (opt)
     {
     case 'G': id_flags |= ID_ALLGROUPS; break;
     case 'g': id_flags |= ID_GIDONLY; break;
     case 'n': id_flags |= ID_USENAME; break;
     case 'r': id_flags |= ID_USEREAL; break;
     case 'u': id_flags |= ID_USERONLY; break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   user = list ? list->word->word : (char *)NULL;
   /* Check for some invalid option combinations */
   opt = ID_FLAGSET (ID_ALLGROUPS) + ID_FLAGSET (ID_GIDONLY) + ID_FLAGSET (ID_USERONLY);
   if (opt > 1 || (opt == 0 && ((id_flags & (ID_USEREAL|ID_USENAME)) != 0)))
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   if (list && list->next)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   if (inituser (user) < 0)
     return (EXECUTION_FAILURE);
   opt = 0;
   if (id_flags & ID_USERONLY)
     opt += id_pruser ((id_flags & ID_USEREAL) ? ruid : euid);
   else if (id_flags & ID_GIDONLY)
     opt += id_prgrp ((id_flags & ID_USEREAL) ? rgid : egid);
   else if (id_flags & ID_ALLGROUPS)
     opt += id_prgroups (user);
   else
     opt += id_prall (user);
   putchar ('\n');
   fflush (stdout);
   return (opt == 0 ? EXECUTION_SUCCESS : EXECUTION_FAILURE);
 }
References builtin_usage(), CASE_HELPOPT, egid, euid, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, fflush(), ID_ALLGROUPS, id_flags, ID_FLAGSET, ID_GIDONLY, id_prall(), id_prgroups(), id_prgrp(), id_pruser(), ID_USENAME, ID_USEREAL, ID_USERONLY, inituser(), internal_getopt(), loptend, word_list::next, NULL, putchar(), reset_internal_getopt(), rgid, ruid, stdout, word_desc::word, and word_list::word.
id_prall() [1/2]
static int id_prall () static
Referenced by id_builtin().
id_prall() [2/2]
static int id_prall (char * uname) static
Definition at line 246 of file id.c.
 {
   int r, i, ng, *glist;
   struct passwd *pwd;
   struct group *grp;
   r = 0;
   printf ("uid=%u", (unsigned) ruid);
   pwd = getpwuid (ruid);
   if (pwd == NULL)
     r = 1;
   else
     printf ("(%s)", pwd->pw_name);
   printf (" gid=%u", (unsigned) rgid);
   grp = getgrgid (rgid);
   if (grp == NULL)
     r = 1;
   else
     printf ("(%s)", grp->gr_name);
   if (euid != ruid)
     {
       printf (" euid=%u", (unsigned) euid);
       pwd = getpwuid (euid);
       if (pwd == NULL)
     r = 1;
       else
     printf ("(%s)", pwd->pw_name);
     }
   if (egid != rgid)
     {
       printf (" egid=%u", (unsigned) egid);
       grp = getgrgid (egid);
       if (grp == NULL)
     r = 1;
       else
     printf ("(%s)", grp->gr_name);
     }
   if (uname)
     {
       builtin_error ("supplementary groups for other users not yet implemented");
       glist = (int *)NULL;
       ng = 0;
       r = 1;
     }
   else
     glist = get_group_array (&ng);
   if (ng > 0)
     printf (" groups=");
   for (i = 0; i < ng; i++)
     {
       if (i > 0)
     printf (", ");
       printf ("%u", (unsigned) glist[i]);
       grp = getgrgid (glist[i]);
       if (grp == NULL)
     r = 1;
       else
     printf ("(%s)", grp->gr_name);
     }
   return r;
 }
References builtin_error(), egid, euid, get_group_array(), getgrgid(), getpwuid(), group::gr_name, i, NULL, printf(), passwd::pw_name, r, rgid, ruid, and uname().
id_prgroups() [1/2]
static int id_prgroups () static
Referenced by id_builtin().
id_prgroups() [2/2]
static int id_prgroups (char * uname) static
Definition at line 212 of file id.c.
 {
   int *glist, ng, i, r;
   r = 0;
   id_prgrp (rgid);
   if (egid != rgid)
     {
       putchar (' ');
       id_prgrp (egid);
     }
   if (uname)
     {
       builtin_error ("supplementary groups for other users not yet implemented");
       glist = (int *)NULL;
       ng = 0;
       r = 1;
     }
   else
     glist = get_group_array (&ng);
   for (i = 0; i < ng; i++)
     if (glist[i] != rgid && glist[i] != egid)
       {
     putchar (' ');
     id_prgrp (glist[i]);
       }
   return r;
 }
References builtin_error(), egid, get_group_array(), i, id_prgrp(), NULL, putchar(), r, rgid, and uname().
id_prgrp() [1/2]
static int id_prgrp () static
Referenced by id_builtin(), and id_prgroups().
id_prgrp() [2/2]
static int id_prgrp (int gid) static
Definition at line 189 of file id.c.
 {
   struct group *grp = NULL;
   int r;
   r = 0;
   if (id_flags & ID_USENAME)
     {
       grp = getgrgid (gid);
       if (grp == NULL)
     r = 1;
     }
   if (grp)
     printf ("%s", grp->gr_name);
   else
     printf ("%u", (unsigned) gid);
   return r;
 }
References getgrgid(), group::gr_name, id_flags, ID_USENAME, NULL, printf(), and r.
id_pruser() [1/2]
static int id_pruser () static
Referenced by id_builtin().
id_pruser() [2/2]
static int id_pruser (int uid) static
Definition at line 165 of file id.c.
 {
   struct passwd *pwd = NULL;
   int r;
   r = 0;
   if (id_flags & ID_USENAME)
     {
       pwd = getpwuid (uid);
       if (pwd == NULL)
         r = 1;
     }
   if (pwd)
     printf ("%s", pwd->pw_name);
   else
     printf ("%u", (unsigned) uid);
   return r;
 }
References getpwuid(), id_flags, ID_USENAME, NULL, printf(), passwd::pw_name, and r.
inituser() [1/2]
static int inituser () static
Referenced by id_builtin().
inituser() [2/2]
static int inituser (char * uname) static
Definition at line 137 of file id.c.
 {
   struct passwd *pwd;
   if (uname)
     {
       pwd = getpwnam (uname);
       if (pwd == 0)
     {
       builtin_error ("%s: no such user", uname);
       return -1;
     }
       ruid = euid = pwd->pw_uid;
       rgid = egid = pwd->pw_gid;
     }
   else
     {
       ruid = current_user.uid;
       euid = current_user.euid;
       rgid = current_user.gid;
       egid = current_user.egid;
     }
   return 0;
 }
References builtin_error(), current_user, egid, user_info::egid, euid, user_info::euid, getpwnam(), user_info::gid, passwd::pw_gid, passwd::pw_uid, rgid, ruid, user_info::uid, and uname().
Variable Documentation
egid
gid_t egid static
Definition at line 65 of file id.c.
Referenced by getresgid(), id_builtin(), id_prall(), id_prgroups(), inituser(), setegid(), setregid(), and setresgid().
euid
uid_t euid static
Definition at line 64 of file id.c.
Referenced by getresuid(), id_builtin(), id_prall(), inituser(), seteuid(), setresuid(), setreuid(), and mlibc::sys_seteuid().
id_doc
char* id_doc[]
Initial value:
= {
    "Display information about user."
    "",
    "Return information about user identity",
    (char *)NULL
}
Definition at line 315 of file id.c.
id_flags
int id_flags static
Definition at line 62 of file id.c.
Referenced by id_builtin(), id_prgrp(), and id_pruser().
id_struct
struct builtin id_struct
Initial value:
= {
    "id",
    id_builtin,
    BUILTIN_ENABLED,
    id_doc,
    "id [user]\n\tid -G [-n] [user]\n\tid -g [-nr] [user]\n\tid -u [-nr] [user]",
    0
}
Definition at line 315 of file id.c.
id_user
char* id_user static
Definition at line 67 of file id.c.
rgid
gid_t rgid static
Definition at line 65 of file id.c.
Referenced by getresgid(), id_builtin(), id_prall(), id_prgroups(), inituser(), setregid(), and setresgid().
ruid
uid_t ruid static
Definition at line 64 of file id.c.
Referenced by getresuid(), id_builtin(), id_prall(), inituser(), setresuid(), and setreuid().