Fennix Userspace: Userspace/apps/base/bash/lib/sh/shquote.c File Reference
shquote.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdc.h>
#include "syntax.h"
#include <xmalloc.h>
#include "shmbchar.h"
#include "shmbutil.h"
Functions
char *ansic_quote PARAMS ((char *, int, int *))
int ansic_shouldquote PARAMS ((const char *))
char * sh_single_quote (char *string) const
char * sh_double_quote (char *string) const
char * sh_mkdoublequoted (char *s, int slen, int flags) const
char * sh_un_double_quote (char *string)
char * sh_backslash_quote (char *string, char *table, int flags)
char * sh_quote_reusable (char *s, int flags)
int sh_contains_shell_metas (char *string) const
int sh_contains_quotes (char *string) const
Variables
static const char bstab [256]
Function Documentation
PARAMS() [1/2]
char* ansic_quote PARAMS ((char *, int, int *))
PARAMS() [2/2]
int ansic_shouldquote PARAMS ((const char *))
sh_backslash_quote()
char* sh_backslash_quote (char * string, char * table, int flags)
Definition at line 262 of file shquote.c.
 {
   int c, mb_cur_max;
   size_t slen;
   char *result, *r, *s, *backslash_table, *send;
   DECLARE_MBSTATE;
   slen = strlen (string);
   send = string + slen;
   result = (char *)xmalloc (2 * slen + 1);
   backslash_table = table ? table : (char *)bstab;
   mb_cur_max = MB_CUR_MAX;
   for (r = result, s = string; s && (c = *s); s++)
     {
 #if defined (HANDLE_MULTIBYTE)
       /* XXX - isascii, even if is_basic(c) == 0 - works in most cases. */
       if (c >= 0 && c <= 127 && backslash_table[(unsigned char)c] == 1)
     {
       *r++ = '\\';
       *r++ = c;
       continue;
     }
       if ((locale_utf8locale && (c & 0x80)) ||
       (locale_utf8locale == 0 && mb_cur_max > 1 && is_basic (c) == 0))
     {
       COPY_CHAR_P (r, s, send);
       s--;      /* compensate for auto-increment in loop above */
       continue;
     }
 #endif
       if (backslash_table[(unsigned char)c] == 1)
     *r++ = '\\';
       else if (c == '#' && s == string)         /* comment char */
     *r++ = '\\';
       else if ((flags&1) && c == '~' && (s == string || s[-1] == ':' || s[-1] == '='))
         /* Tildes are special at the start of a word or after a `:' or `='
        (technically unquoted, but it doesn't make a difference in practice) */
     *r++ = '\\';
       else if ((flags&2) && shellblank((unsigned char)c))
     *r++ = '\\';
       *r++ = c;
     }
   *r = '\0';
   return (result);
 }
References bstab, c, COPY_CHAR_P, DECLARE_MBSTATE, flags, locale_utf8locale, MB_CUR_MAX, s, send(), shellblank, strlen(), table, and xmalloc.
Referenced by sh_quote_reusable().
sh_contains_quotes()
int sh_contains_quotes (char * string) const
Definition at line 421 of file shquote.c.
 {
   const char *s;
   for (s = string; s && *s; s++)
     {
       if (*s == '\'' || *s == '"' || *s == '\\')
     return 1;
     }
   return 0;
 }
References s.
sh_contains_shell_metas()
int sh_contains_shell_metas (char * string) const
Definition at line 386 of file shquote.c.
 {
   const char *s;
   for (s = string; s && *s; s++)
     {
       switch (*s)
     {
     case ' ': case '\t': case '\n':     /* IFS white space */
     case '\'': case '"': case '\\':     /* quoting chars */
     case '|': case '&': case ';':       /* shell metacharacters */
     case '(': case ')': case '<': case '>':
     case '!': case '{': case '}':       /* reserved words */
     case '*': case '[': case '?': case ']': /* globbing chars */
     case '^':
     case '$': case '`':         /* expansion chars */
       return (1);
     case '~':               /* tilde expansion */
       if (s == string || s[-1] == '=' || s[-1] == ':')
         return (1);
       break;
     case '#':
       if (s == string)          /* comment char */
         return (1);
       /* FALLTHROUGH */
     default:
       break;
     }
     }
   return (0);
 }
References s.
Referenced by print_var_value(), printable_filename(), xtrace_print_assignment(), and xtrace_print_word_list().
sh_double_quote()
char* sh_double_quote (char * string) const
Definition at line 135 of file shquote.c.
 {
   register unsigned char c;
   int mb_cur_max;
   char *result, *r;
   size_t slen;
   const char *s, *send;
   DECLARE_MBSTATE;
   slen = strlen (string);
   send = string + slen;
   mb_cur_max = MB_CUR_MAX;
   result = (char *)xmalloc (3 + (2 * strlen (string)));
   r = result;
   *r++ = '"';
   for (s = string; s && (c = *s); s++)
     {
       /* Backslash-newline disappears within double quotes, so don't add one. */
       if ((sh_syntaxtab[c] & CBSDQUOTE) && c != '\n')
     *r++ = '\\';
 #if defined (HANDLE_MULTIBYTE)
       if ((locale_utf8locale && (c & 0x80)) ||
       (locale_utf8locale == 0 && mb_cur_max > 1 && is_basic (c) == 0))
     {
       COPY_CHAR_P (r, s, send);
       s--;      /* compensate for auto-increment in loop above */
       continue;
     }
 #endif
       /* Assume that the string will not be further expanded, so no need to
      add CTLESC to protect CTLESC or CTLNUL. */
       *r++ = c;
     }
   *r++ = '"';
   *r = '\0';
   return (result);
 }
References c, CBSDQUOTE, COPY_CHAR_P, DECLARE_MBSTATE, locale_utf8locale, MB_CUR_MAX, s, send(), sh_syntaxtab, strlen(), and xmalloc.
sh_mkdoublequoted()
char* sh_mkdoublequoted (char * s, int slen, int flags) const
Definition at line 183 of file shquote.c.
 {
   char *r, *ret;
   const char *send;
   int rlen, mb_cur_max;
   DECLARE_MBSTATE;
   send = s + slen;
   mb_cur_max = flags ? MB_CUR_MAX : 1;
   rlen = (flags == 0) ? slen + 3 : (2 * slen) + 1;
   ret = r = (char *)xmalloc (rlen);
   *r++ = '"';
   while (*s)
     {
       if (flags && *s == '"')
     *r++ = '\\';
 #if defined (HANDLE_MULTIBYTE)
       if  (flags && ((locale_utf8locale && (*s & 0x80)) ||
              (locale_utf8locale == 0 && mb_cur_max > 1 && is_basic (*s) == 0)))
     {
       COPY_CHAR_P (r, s, send);
       continue;
     }
 #endif
       *r++ = *s++;
     }
   *r++ = '"';
   *r = '\0';
   return ret;
 }
References COPY_CHAR_P, DECLARE_MBSTATE, flags, locale_utf8locale, MB_CUR_MAX, s, send(), and xmalloc.
Referenced by expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), parse_matched_pair(), and read_token_word().
sh_quote_reusable()
char* sh_quote_reusable (char * s, int flags)
Definition at line 361 of file shquote.c.
 {
   char *ret;
   if (s == 0)
     return s;
   else if (*s == 0)
     {
       ret = (char *)xmalloc (3);
       ret[0] = ret[1] = '\'';
       ret[2] = '\0';
     }
   else if (ansic_shouldquote (s))
     ret = ansic_quote (s, 0, (int *)0);
   else if (flags)
     ret = sh_backslash_quote (s, 0, 1);
   else
     ret = sh_single_quote (s);
   return ret;
 }
References ansic_quote(), ansic_shouldquote(), flags, s, sh_backslash_quote(), sh_single_quote(), and xmalloc.
Referenced by string_transform(), and string_var_assignment().
sh_single_quote()
char* sh_single_quote (char * string) const
Definition at line 95 of file shquote.c.
 {
   register int c;
   char *result, *r;
   const char *s;
   result = (char *)xmalloc (3 + (4 * strlen (string)));
   r = result;
   if (string[0] == '\'' && string[1] == 0)
     {
       *r++ = '\\';
       *r++ = '\'';
       *r++ = 0;
       return result;
     }
   *r++ = '\'';
   for (s = string; s && (c = *s); s++)
     {
       *r++ = c;
       if (c == '\'')
     {
       *r++ = '\\';  /* insert escaped single quote */
       *r++ = '\'';
       *r++ = '\'';  /* start new quoted string */
     }
     }
   *r++ = '\'';
   *r = '\0';
   return (result);
 }
References c, s, strlen(), and xmalloc.
Referenced by sh_quote_reusable().
sh_un_double_quote()
char* sh_un_double_quote (char * string)
Definition at line 223 of file shquote.c.
 {
   register int c, pass_next;
   char *result, *r, *s;
   r = result = (char *)xmalloc (strlen (string) + 1);
   for (pass_next = 0, s = string; s && (c = *s); s++)
     {
       if (pass_next)
     {
       *r++ = c;
       pass_next = 0;
       continue;
     }
       if (c == '\\' && (sh_syntaxtab[(unsigned char) s[1]] & CBSDQUOTE))
     {
       pass_next = 1;
       continue;
     }
       *r++ = c;
     }
   *r = '\0';
   return result;
 }
References c, CBSDQUOTE, s, sh_syntaxtab, strlen(), and xmalloc.
Variable Documentation
bstab
const char bstab[256] static
Definition at line 43 of file shquote.c.
Referenced by sh_backslash_quote().