Fennix Userspace: Userspace/musl/src/stat/statvfs.c File Reference
statvfs.c File Reference
#include <sys/statvfs.h>
#include <sys/statfs.h>
#include "syscall.h"
Functions
static int __statfs (const char *path, struct statfs *buf)
static int __fstatfs (int fd, struct statfs *buf)
weak_alias (__statfs, statfs)
weak_alias (__fstatfs, fstatfs)
static void fixup (struct statvfs *out, const struct statfs *in)
int statvfs (const char *restrict path, struct statvfs *restrict buf)
int fstatvfs (int fd, struct statvfs *buf)
Function Documentation
__fstatfs()
static int __fstatfs (int fd, struct statfs * buf) static
Definition at line 15 of file statvfs.c.
 {
     *buf = (struct statfs){0};
 #ifdef SYS_fstatfs64
     return syscall(SYS_fstatfs64, fd, sizeof *buf, buf);
 #else
     return syscall(SYS_fstatfs, fd, buf);
 #endif
 }
References buf, and syscall().
Referenced by fstatvfs().
__statfs()
static int __statfs (const char * path, struct statfs * buf) static
Definition at line 5 of file statvfs.c.
 {
     *buf = (struct statfs){0};
 #ifdef SYS_statfs64
     return syscall(SYS_statfs64, path, sizeof *buf, buf);
 #else
     return syscall(SYS_statfs, path, buf);
 #endif
 }
References buf, and syscall().
Referenced by statvfs().
fixup()
static void fixup (struct statvfs * out, const struct statfs * in) static
Definition at line 28 of file statvfs.c.
 {
     *out = (struct statvfs){0};
     out->f_bsize = in->f_bsize;
     out->f_frsize = in->f_frsize ? in->f_frsize : in->f_bsize;
     out->f_blocks = in->f_blocks;
     out->f_bfree = in->f_bfree;
     out->f_bavail = in->f_bavail;
     out->f_files = in->f_files;
     out->f_ffree = in->f_ffree;
     out->f_favail = in->f_ffree;
     out->f_fsid = in->f_fsid.__val[0];
     out->f_flag = in->f_flags;
     out->f_namemax = in->f_namelen;
 }
References __fsid_t::__val, statfs::f_bavail, statfs::f_bfree, statfs::f_blocks, statfs::f_bsize, statfs::f_ffree, statfs::f_files, statfs::f_flags, statfs::f_frsize, statfs::f_fsid, statfs::f_namelen, and out().
Referenced by fstatvfs(), and statvfs().
fstatvfs()
int fstatvfs (int fd, struct statvfs * buf)
Definition at line 52 of file statvfs.c.
 {
     struct statfs kbuf;
     if (__fstatfs(fd, &kbuf)<0) return -1;
     fixup(buf, &kbuf);
     return 0;
 }
References __fstatfs(), buf, and fixup().
statvfs()
int statvfs (const char *restrict path, struct statvfs *restrict buf)
Definition at line 44 of file statvfs.c.
 {
     struct statfs kbuf;
     if (__statfs(path, &kbuf)<0) return -1;
     fixup(buf, &kbuf);
     return 0;
 }
References __statfs(), buf, and fixup().
weak_alias() [1/2]
weak_alias (__fstatfs , fstatfs)
weak_alias() [2/2]
weak_alias (__statfs , statfs)