Fennix: Userspace/mlibc/options/linux/include/sys/epoll.h File Reference
epoll.h File Reference
#include <stdint.h>
#include <abi-bits/signal.h>
#include <abi-bits/epoll.h>
Data Structures
union epoll_data
struct epoll_event
Macros
#define EPOLLIN 0x001
#define EPOLLPRI 0x002
#define EPOLLOUT 0x004
#define EPOLLRDNORM 0x040
#define EPOLLRDBAND 0x080
#define EPOLLWRNORM 0x100
#define EPOLLWRBAND 0x200
#define EPOLLMSG 0x400
#define EPOLLERR 0x008
#define EPOLLHUP 0x010
#define EPOLLRDHUP 0x2000
#define EPOLLEXCLUSIVE (1U << 28)
#define EPOLLWAKEUP (1U << 29)
#define EPOLLONESHOT (1U << 30)
#define EPOLLET (1U << 31)
#define EPOLL_CTL_ADD 1
#define EPOLL_CTL_DEL 2
#define EPOLL_CTL_MOD 3
Typedefs
typedef union epoll_data epoll_data_t
Functions
int epoll_create (int)
int epoll_create1 (int)
int epoll_ctl (int, int, int, struct epoll_event *)
int epoll_wait (int, struct epoll_event *, int, int)
int epoll_pwait (int, struct epoll_event *, int, int, const sigset_t *)
Data Structure Documentation
epoll_data
union epoll_data
Definition at line 33 of file epoll.h.
Data Fields
int fd
void * ptr
uint32_t u32
uint64_t u64
epoll_event
struct epoll_event
Definition at line 40 of file epoll.h.
Data Fields
epoll_data_t data
uint32_t events
Macro Definition Documentation
EPOLL_CTL_ADD
#define EPOLL_CTL_ADD 1
Definition at line 25 of file epoll.h.
EPOLL_CTL_DEL
#define EPOLL_CTL_DEL 2
Definition at line 26 of file epoll.h.
EPOLL_CTL_MOD
#define EPOLL_CTL_MOD 3
Definition at line 27 of file epoll.h.
EPOLLERR
#define EPOLLERR 0x008
Definition at line 17 of file epoll.h.
EPOLLET
#define EPOLLET (1U << 31)
Definition at line 23 of file epoll.h.
EPOLLEXCLUSIVE
#define EPOLLEXCLUSIVE (1U << 28)
Definition at line 20 of file epoll.h.
EPOLLHUP
#define EPOLLHUP 0x010
Definition at line 18 of file epoll.h.
EPOLLIN
#define EPOLLIN 0x001
Definition at line 9 of file epoll.h.
EPOLLMSG
#define EPOLLMSG 0x400
Definition at line 16 of file epoll.h.
EPOLLONESHOT
#define EPOLLONESHOT (1U << 30)
Definition at line 22 of file epoll.h.
EPOLLOUT
#define EPOLLOUT 0x004
Definition at line 11 of file epoll.h.
EPOLLPRI
#define EPOLLPRI 0x002
Definition at line 10 of file epoll.h.
EPOLLRDBAND
#define EPOLLRDBAND 0x080
Definition at line 13 of file epoll.h.
EPOLLRDHUP
#define EPOLLRDHUP 0x2000
Definition at line 19 of file epoll.h.
EPOLLRDNORM
#define EPOLLRDNORM 0x040
Definition at line 12 of file epoll.h.
EPOLLWAKEUP
#define EPOLLWAKEUP (1U << 29)
Definition at line 21 of file epoll.h.
EPOLLWRBAND
#define EPOLLWRBAND 0x200
Definition at line 15 of file epoll.h.
EPOLLWRNORM
#define EPOLLWRNORM 0x100
Definition at line 14 of file epoll.h.
Typedef Documentation
epoll_data_t
typedef union epoll_data epoll_data_t
Function Documentation
epoll_create()
int epoll_create (int)
Definition at line 9 of file sys-epoll.cpp.
                       {
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_create, -1);
     if(int e = mlibc::sys_epoll_create(0, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_epoll_create().
epoll_create1()
int epoll_create1 (int flags)
Definition at line 30 of file sys-epoll.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_create, -1);
     if(int e = mlibc::sys_epoll_create(flags, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_epoll_create().
Referenced by mlibc::sys_pselect().
epoll_ctl()
int epoll_ctl (int epfd, int mode, int fd, struct epoll_event * ev)
Definition at line 40 of file sys-epoll.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_ctl, -1);
     if(int e = mlibc::sys_epoll_ctl(epfd, mode, fd, ev); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_epoll_ctl().
Referenced by mlibc::sys_pselect().
epoll_pwait()
int epoll_pwait (int epfd, struct epoll_event * evnts, int n, int timeout, const sigset_t * sigmask)
Definition at line 19 of file sys-epoll.cpp.
{
     int raised;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_pwait, -1);
     if(int e = mlibc::sys_epoll_pwait(epfd, evnts, n, timeout, sigmask, &raised)) {
         errno = e;
         return -1;
     }
     return raised;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, n, mlibc::sigmask, mlibc::sys_epoll_pwait(), and mlibc::timeout.
Referenced by mlibc::sys_pselect().
epoll_wait()
int epoll_wait (int epfd, struct epoll_event * evnts, int n, int timeout)
Definition at line 49 of file sys-epoll.cpp.
{
     int raised;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_epoll_pwait, -1);
     if(int e = mlibc::sys_epoll_pwait(epfd, evnts, n, timeout, NULL, &raised)) {
         errno = e;
         return -1;
     }
     return raised;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, n, NULL, mlibc::sys_epoll_pwait(), and mlibc::timeout.