Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_spec.h File Reference
p_spec.h File Reference
Data Structures
struct fireflicker_t
struct lightflash_t
struct strobe_t
struct glow_t
struct switchlist_t
struct button_t
struct plat_t
struct vldoor_t
struct ceiling_t
struct floormove_t
Macros
#define MO_TELEPORTMAN 14
#define GLOWSPEED 8
#define STROBEBRIGHT 5
#define FASTDARK 15
#define SLOWDARK 35
#define MAXSWITCHES 50
#define MAXBUTTONS 16
#define BUTTONTIME 35
#define PLATWAIT 3
#define PLATSPEED FRACUNIT
#define MAXPLATS 30
#define VDOORSPEED FRACUNIT*2
#define VDOORWAIT 150
#define CEILSPEED FRACUNIT
#define CEILWAIT 150
#define MAXCEILINGS 30
#define FLOORSPEED FRACUNIT
Enumerations
enum bwhere_e { top , middle , bottom }
enum plat_e { up , down , waiting , in_stasis }
enum plattype_e {
perpetualRaise , downWaitUpStay , raiseAndChange , raiseToNearestAndChange ,
blazeDWUS
}
enum vldoor_e {
vld_normal , vld_close30ThenOpen , vld_close , vld_open ,
vld_raiseIn5Mins , vld_blazeRaise , vld_blazeOpen , vld_blazeClose
}
enum ceiling_e {
lowerToFloor , raiseToHighest , lowerAndCrush , crushAndRaise ,
fastCrushAndRaise , silentCrushAndRaise
}
enum floor_e {
lowerFloor , lowerFloorToLowest , turboLower , raiseFloor ,
raiseFloorToNearest , raiseToTexture , lowerAndChange , raiseFloor24 ,
raiseFloor24AndChange , raiseFloorCrush , raiseFloorTurbo , donutRaise ,
raiseFloor512
}
enum stair_e { build8 , turbo16 }
enum result_e { ok , crushed , pastdest }
Functions
void P_InitPicAnims (void)
void P_SpawnSpecials (void)
void P_UpdateSpecials (void)
boolean P_UseSpecialLine (mobj_t *thing, line_t *line, int side)
void P_ShootSpecialLine (mobj_t *thing, line_t *line)
void P_CrossSpecialLine (int linenum, int side, mobj_t *thing)
void P_PlayerInSpecialSector (player_t *player)
int twoSided (int sector, int line)
sector_t * getSector (int currentSector, int line, int side)
side_t * getSide (int currentSector, int line, int side)
fixed_t P_FindLowestFloorSurrounding (sector_t *sec)
fixed_t P_FindHighestFloorSurrounding (sector_t *sec)
fixed_t P_FindNextHighestFloor (sector_t *sec, int currentheight)
fixed_t P_FindLowestCeilingSurrounding (sector_t *sec)
fixed_t P_FindHighestCeilingSurrounding (sector_t *sec)
int P_FindSectorFromLineTag (line_t *line, int start)
int P_FindMinSurroundingLight (sector_t *sector, int max)
sector_t * getNextSector (line_t *line, sector_t *sec)
int EV_DoDonut (line_t *line)
void P_SpawnFireFlicker (sector_t *sector)
void T_LightFlash (lightflash_t *flash)
void P_SpawnLightFlash (sector_t *sector)
void T_StrobeFlash (strobe_t *flash)
void P_SpawnStrobeFlash (sector_t *sector, int fastOrSlow, int inSync)
void EV_StartLightStrobing (line_t *line)
void EV_TurnTagLightsOff (line_t *line)
void EV_LightTurnOn (line_t *line, int bright)
void T_Glow (glow_t *g)
void P_SpawnGlowingLight (sector_t *sector)
void P_ChangeSwitchTexture (line_t *line, int useAgain)
void P_InitSwitchList (void)
void T_PlatRaise (plat_t *plat)
int EV_DoPlat (line_t *line, plattype_e type, int amount)
void P_AddActivePlat (plat_t *plat)
void P_RemoveActivePlat (plat_t *plat)
void EV_StopPlat (line_t *line)
void P_ActivateInStasis (int tag)
void EV_VerticalDoor (line_t *line, mobj_t *thing)
int EV_DoDoor (line_t *line, vldoor_e type)
int EV_DoLockedDoor (line_t *line, vldoor_e type, mobj_t *thing)
void T_VerticalDoor (vldoor_t *door)
void P_SpawnDoorCloseIn30 (sector_t *sec)
void P_SpawnDoorRaiseIn5Mins (sector_t *sec, int secnum)
int EV_DoCeiling (line_t *line, ceiling_e type)
void T_MoveCeiling (ceiling_t *ceiling)
void P_AddActiveCeiling (ceiling_t *c)
void P_RemoveActiveCeiling (ceiling_t *c)
int EV_CeilingCrushStop (line_t *line)
void P_ActivateInStasisCeiling (line_t *line)
result_e T_MovePlane (sector_t *sector, fixed_t speed, fixed_t dest, boolean crush, int floorOrCeiling, int direction)
int EV_BuildStairs (line_t *line, stair_e type)
int EV_DoFloor (line_t *line, floor_e floortype)
void T_MoveFloor (floormove_t *floor)
int EV_Teleport (line_t *line, int side, mobj_t *thing)
Variables
boolean levelTimer
int levelTimeCount
button_t buttonlist [MAXBUTTONS]
plat_t * activeplats [MAXPLATS]
ceiling_t * activeceilings [MAXCEILINGS]
Data Structure Documentation
fireflicker_t
struct fireflicker_t
Definition at line 121 of file p_spec.h.
Data Fields
int count
int maxlight
int minlight
sector_t * sector
thinker_t thinker
lightflash_t
struct lightflash_t
Definition at line 133 of file p_spec.h.
Data Fields
int count
int maxlight
int maxtime
int minlight
int mintime
sector_t * sector
thinker_t thinker
strobe_t
struct strobe_t
Definition at line 147 of file p_spec.h.
Data Fields
int brighttime
int count
int darktime
int maxlight
int minlight
sector_t * sector
thinker_t thinker
glow_t
struct glow_t
Definition at line 162 of file p_spec.h.
Data Fields
int direction
int maxlight
int minlight
sector_t * sector
thinker_t thinker
switchlist_t
struct switchlist_t
Definition at line 206 of file p_spec.h.
Data Fields
short episode
char name1[9]
char name2[9]
button_t
struct button_t
Definition at line 224 of file p_spec.h.
Data Fields
int btexture
int btimer
line_t * line
degenmobj_t * soundorg
bwhere_e where
plat_t
struct plat_t
Definition at line 282 of file p_spec.h.
Data Fields
int count
boolean crush
fixed_t high
fixed_t low
plat_e oldstatus
sector_t * sector
fixed_t speed
plat_e status
int tag
thinker_t thinker
plattype_e type
int wait
vldoor_t
struct vldoor_t
Definition at line 340 of file p_spec.h.
Data Fields
int direction
sector_t * sector
fixed_t speed
thinker_t thinker
int topcountdown
fixed_t topheight
int topwait
vldoor_e type
ceiling_t
struct ceiling_t
Definition at line 490 of file p_spec.h.
Data Fields
fixed_t bottomheight
boolean crush
int direction
int olddirection
sector_t * sector
fixed_t speed
int tag
thinker_t thinker
fixed_t topheight
ceiling_e type
floormove_t
struct floormove_t
Definition at line 581 of file p_spec.h.
Data Fields
boolean crush
int direction
fixed_t floordestheight
int newspecial
sector_t * sector
fixed_t speed
short texture
thinker_t thinker
floor_e type
Macro Definition Documentation
BUTTONTIME
#define BUTTONTIME 35
Definition at line 244 of file p_spec.h.
CEILSPEED
#define CEILSPEED FRACUNIT
Definition at line 513 of file p_spec.h.
CEILWAIT
#define CEILWAIT 150
Definition at line 514 of file p_spec.h.
FASTDARK
#define FASTDARK 15
Definition at line 175 of file p_spec.h.
FLOORSPEED
#define FLOORSPEED FRACUNIT
Definition at line 597 of file p_spec.h.
GLOWSPEED
#define GLOWSPEED 8
Definition at line 173 of file p_spec.h.
MAXBUTTONS
#define MAXBUTTONS 16
Definition at line 241 of file p_spec.h.
MAXCEILINGS
#define MAXCEILINGS 30
Definition at line 515 of file p_spec.h.
MAXPLATS
#define MAXPLATS 30
Definition at line 303 of file p_spec.h.
MAXSWITCHES
#define MAXSWITCHES 50
Definition at line 238 of file p_spec.h.
MO_TELEPORTMAN
#define MO_TELEPORTMAN 14
Definition at line 35 of file p_spec.h.
PLATSPEED
#define PLATSPEED FRACUNIT
Definition at line 302 of file p_spec.h.
PLATWAIT
#define PLATWAIT 3
Definition at line 301 of file p_spec.h.
SLOWDARK
#define SLOWDARK 35
Definition at line 176 of file p_spec.h.
STROBEBRIGHT
#define STROBEBRIGHT 5
Definition at line 174 of file p_spec.h.
VDOORSPEED
#define VDOORSPEED FRACUNIT*2
Definition at line 361 of file p_spec.h.
VDOORWAIT
#define VDOORWAIT 150
Definition at line 362 of file p_spec.h.
Enumeration Type Documentation
bwhere_e
enum bwhere_e
Enumerator
top
middle
bottom
Definition at line 215 of file p_spec.h.
 {
     top,
     middle,
     bottom
 } bwhere_e;
ceiling_e
enum ceiling_e
Enumerator
lowerToFloor
raiseToHighest
lowerAndCrush
crushAndRaise
fastCrushAndRaise
silentCrushAndRaise
Definition at line 477 of file p_spec.h.
 {
     lowerToFloor,
     raiseToHighest,
     lowerAndCrush,
     crushAndRaise,
     fastCrushAndRaise,
     silentCrushAndRaise
 } ceiling_e;
floor_e
enum floor_e
Enumerator
lowerFloor
lowerFloorToLowest
turboLower
raiseFloor
raiseFloorToNearest
raiseToTexture
lowerAndChange
raiseFloor24
raiseFloor24AndChange
raiseFloorCrush
raiseFloorTurbo
donutRaise
raiseFloor512
Definition at line 534 of file p_spec.h.
 {
     // lower floor to highest surrounding floor
     lowerFloor,
     // lower floor to lowest surrounding floor
     lowerFloorToLowest,
     // lower floor to highest surrounding floor VERY FAST
     turboLower,
     // raise floor to lowest surrounding CEILING
     raiseFloor,
     // raise floor to next highest surrounding floor
     raiseFloorToNearest,
     // raise floor to shortest height texture around it
     raiseToTexture,
     // lower floor to lowest surrounding floor
     //  and change floorpic
     lowerAndChange,
     raiseFloor24,
     raiseFloor24AndChange,
     raiseFloorCrush,
      // raise to next highest floor, turbo-speed
     raiseFloorTurbo,
     donutRaise,
     raiseFloor512
 } floor_e;
plat_e
enum plat_e
Enumerator
up
down
waiting
in_stasis
Definition at line 259 of file p_spec.h.
 {
     up,
     down,
     waiting,
     in_stasis
 } plat_e;
plattype_e
enum plattype_e
Enumerator
perpetualRaise
downWaitUpStay
raiseAndChange
raiseToNearestAndChange
blazeDWUS
Definition at line 270 of file p_spec.h.
 {
     perpetualRaise,
     downWaitUpStay,
     raiseAndChange,
     raiseToNearestAndChange,
     blazeDWUS
 } plattype_e;
result_e
enum result_e
Enumerator
ok
crushed
pastdest
Definition at line 599 of file p_spec.h.
 {
     ok,
     crushed,
     pastdest
 } result_e;
stair_e
enum stair_e
Enumerator
build8
turbo16
Definition at line 572 of file p_spec.h.
 {
     build8, // slowly build by 8
     turbo16 // quickly build by 16
 } stair_e;
vldoor_e
enum vldoor_e
Enumerator
vld_normal
vld_close30ThenOpen
vld_close
vld_open
vld_raiseIn5Mins
vld_blazeRaise
vld_blazeOpen
vld_blazeClose
Definition at line 325 of file p_spec.h.
 {
     vld_normal,
     vld_close30ThenOpen,
     vld_close,
     vld_open,
     vld_raiseIn5Mins,
     vld_blazeRaise,
     vld_blazeOpen,
     vld_blazeClose
 } vldoor_e;
Function Documentation
EV_BuildStairs()
int EV_BuildStairs (line_t * line, stair_e type)
Definition at line 444 of file p_floor.c.
 {
     int         secnum;
     int         height;
     int         i;
     int         newsecnum;
     int         texture;
     int         ok;
     int         rtn;
     sector_t*       sec;
     sector_t*       tsec;
     floormove_t*    floor;
     fixed_t     stairsize = 0;
     fixed_t     speed = 0;
     secnum = -1;
     rtn = 0;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     // ALREADY MOVING?  IF SO, KEEP GOING...
     if (sec->specialdata)
         continue;
     // new floor thinker
     rtn = 1;
     floor = Z_Malloc (sizeof(*floor), PU_LEVSPEC, 0);
     P_AddThinker (&floor->thinker);
     sec->specialdata = floor;
     floor->thinker.function.acp1 = (actionf_p1) T_MoveFloor;
     floor->direction = 1;
     floor->sector = sec;
     switch(type)
     {
       case build8:
         speed = FLOORSPEED/4;
         stairsize = 8*FRACUNIT;
         break;
       case turbo16:
         speed = FLOORSPEED*4;
         stairsize = 16*FRACUNIT;
         break;
     }
     floor->speed = speed;
     height = sec->floorheight + stairsize;
     floor->floordestheight = height;
     texture = sec->floorpic;
     // Find next sector to raise
     // 1.   Find 2-sided line with same sector side[0]
     // 2.   Other side is the next sector to raise
     do
     {
         ok = 0;
         for (i = 0;i < sec->linecount;i++)
         {
         if ( !((sec->lines[i])->flags & ML_TWOSIDED) )
             continue;
         tsec = (sec->lines[i])->frontsector;
         newsecnum = tsec-sectors;
         if (secnum != newsecnum)
             continue;
         tsec = (sec->lines[i])->backsector;
         newsecnum = tsec - sectors;
         if (tsec->floorpic != texture)
             continue;
         height += stairsize;
         if (tsec->specialdata)
             continue;
         sec = tsec;
         secnum = newsecnum;
         floor = Z_Malloc (sizeof(*floor), PU_LEVSPEC, 0);
         P_AddThinker (&floor->thinker);
         sec->specialdata = floor;
         floor->thinker.function.acp1 = (actionf_p1) T_MoveFloor;
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = speed;
         floor->floordestheight = height;
         ok = 1;
         break;
         }
     } while(ok);
     }
     return rtn;
 }
References backsector, build8, floor, sector_t::floorheight, sector_t::floorpic, FLOORSPEED, FRACUNIT, frontsector, height(), i, sector_t::linecount, sector_t::lines, ML_TWOSIDED, ok, P_AddThinker(), P_FindSectorFromLineTag(), PU_LEVSPEC, sectors, sector_t::specialdata, T_MoveFloor(), turbo16, type, and Z_Malloc().
Referenced by P_CrossSpecialLine(), and P_UseSpecialLine().
EV_CeilingCrushStop()
int EV_CeilingCrushStop (line_t * line)
Definition at line 303 of file p_ceilng.c.
 {
     int     i;
     int     rtn;
     rtn = 0;
     for (i = 0;i < MAXCEILINGS;i++)
     {
     if (activeceilings[i]
         && (activeceilings[i]->tag == line->tag)
         && (activeceilings[i]->direction != 0))
     {
         activeceilings[i]->olddirection = activeceilings[i]->direction;
         activeceilings[i]->thinker.function.acv = (actionf_v)NULL;
         activeceilings[i]->direction = 0;       // in-stasis
         rtn = 1;
     }
     }
     return rtn;
 }
References activeceilings, actionf_t::acv, ceiling_t::direction, thinker_s::function, i, MAXCEILINGS, NULL, ceiling_t::olddirection, and ceiling_t::thinker.
Referenced by P_CrossSpecialLine().
EV_DoCeiling()
int EV_DoCeiling (line_t * line, ceiling_e type)
Definition at line 161 of file p_ceilng.c.
 {
     int     secnum;
     int     rtn;
     sector_t*   sec;
     ceiling_t*  ceiling;
     secnum = -1;
     rtn = 0;
     //  Reactivate in-stasis ceilings...for certain types.
     switch(type)
     {
       case fastCrushAndRaise:
       case silentCrushAndRaise:
       case crushAndRaise:
     P_ActivateInStasisCeiling(line);
       default:
     break;
     }
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     // new door thinker
     rtn = 1;
     ceiling = Z_Malloc (sizeof(*ceiling), PU_LEVSPEC, 0);
     P_AddThinker (&ceiling->thinker);
     sec->specialdata = ceiling;
     ceiling->thinker.function.acp1 = (actionf_p1)T_MoveCeiling;
     ceiling->sector = sec;
     ceiling->crush = false;
     switch(type)
     {
       case fastCrushAndRaise:
         ceiling->crush = true;
         ceiling->topheight = sec->ceilingheight;
         ceiling->bottomheight = sec->floorheight + (8*FRACUNIT);
         ceiling->direction = -1;
         ceiling->speed = CEILSPEED * 2;
         break;
       case silentCrushAndRaise:
       case crushAndRaise:
         ceiling->crush = true;
         ceiling->topheight = sec->ceilingheight;
       case lowerAndCrush:
       case lowerToFloor:
         ceiling->bottomheight = sec->floorheight;
         if (type != lowerToFloor)
         ceiling->bottomheight += 8*FRACUNIT;
         ceiling->direction = -1;
         ceiling->speed = CEILSPEED;
         break;
       case raiseToHighest:
         ceiling->topheight = P_FindHighestCeilingSurrounding(sec);
         ceiling->direction = 1;
         ceiling->speed = CEILSPEED;
         break;
     }
     ceiling->tag = sec->tag;
     ceiling->type = type;
     P_AddActiveCeiling(ceiling);
     }
     return rtn;
 }
References actionf_t::acp1, ceiling_t::bottomheight, sector_t::ceilingheight, CEILSPEED, ceiling_t::crush, crushAndRaise, ceiling_t::direction, fastCrushAndRaise, sector_t::floorheight, FRACUNIT, thinker_s::function, lowerAndCrush, lowerToFloor, P_ActivateInStasisCeiling(), P_AddActiveCeiling(), P_AddThinker(), P_FindHighestCeilingSurrounding(), P_FindSectorFromLineTag(), PU_LEVSPEC, raiseToHighest, ceiling_t::sector, sectors, silentCrushAndRaise, sector_t::specialdata, ceiling_t::speed, T_MoveCeiling(), ceiling_t::tag, sector_t::tag, ceiling_t::thinker, ceiling_t::topheight, type, ceiling_t::type, and Z_Malloc().
Referenced by P_CrossSpecialLine(), and P_UseSpecialLine().
EV_DoDonut()
int EV_DoDonut (line_t * line)
Definition at line 1257 of file p_spec.c.
 {
     sector_t*       s1;
     sector_t*       s2;
     sector_t*       s3;
     int         secnum;
     int         rtn;
     int         i;
     floormove_t*    floor;
     fixed_t s3_floorheight;
     short s3_floorpic;
     secnum = -1;
     rtn = 0;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     s1 = &sectors[secnum];
     // ALREADY MOVING?  IF SO, KEEP GOING...
     if (s1->specialdata)
         continue;
     rtn = 1;
     s2 = getNextSector(s1->lines[0],s1);
         // Vanilla Doom does not check if the linedef is one sided.  The
         // game does not crash, but reads invalid memory and causes the
         // sector floor to move "down" to some unknown height.
         // DOSbox prints a warning about an invalid memory access.
         //
         // I'm not sure exactly what invalid memory is being read.  This
         // isn't something that should be done, anyway.
         // Just print a warning and return.
         if (s2 == NULL)
         {
             fprintf(stderr,
                     "EV_DoDonut: linedef had no second sidedef! "
                     "Unexpected behavior may occur in Vanilla Doom. \n");
         break;
         }
     for (i = 0; i < s2->linecount; i++)
     {
         s3 = s2->lines[i]->backsector;
         if (s3 == s1)
         continue;
             if (s3 == NULL)
             {
                 // e6y
                 // s3 is NULL, so
                 // s3->floorheight is an int at 0000:0000
                 // s3->floorpic is a short at 0000:0008
                 // Trying to emulate
                 fprintf(stderr,
                         "EV_DoDonut: WARNING: emulating buffer overrun due to "
                         "NULL back sector. "
                         "Unexpected behavior may occur in Vanilla Doom.\n");
                 DonutOverrun(&s3_floorheight, &s3_floorpic, line, s1);
             }
             else
             {
                 s3_floorheight = s3->floorheight;
                 s3_floorpic = s3->floorpic;
             }
         //  Spawn rising slime
         floor = Z_Malloc (sizeof(*floor), PU_LEVSPEC, 0);
         P_AddThinker (&floor->thinker);
         s2->specialdata = floor;
         floor->thinker.function.acp1 = (actionf_p1) T_MoveFloor;
         floor->type = donutRaise;
         floor->crush = false;
         floor->direction = 1;
         floor->sector = s2;
         floor->speed = FLOORSPEED / 2;
         floor->texture = s3_floorpic;
         floor->newspecial = 0;
         floor->floordestheight = s3_floorheight;
         //  Spawn lowering donut-hole
         floor = Z_Malloc (sizeof(*floor), PU_LEVSPEC, 0);
         P_AddThinker (&floor->thinker);
         s1->specialdata = floor;
         floor->thinker.function.acp1 = (actionf_p1) T_MoveFloor;
         floor->type = lowerFloor;
         floor->crush = false;
         floor->direction = -1;
         floor->sector = s1;
         floor->speed = FLOORSPEED / 2;
         floor->floordestheight = s3_floorheight;
         break;
     }
     }
     return rtn;
 }
References DonutOverrun(), donutRaise, floor, FLOORSPEED, fprintf(), getNextSector(), i, lowerFloor, NULL, P_AddThinker(), P_FindSectorFromLineTag(), PU_LEVSPEC, s1, s2, s3, sectors, stderr, T_MoveFloor(), and Z_Malloc().
Referenced by P_UseSpecialLine().
EV_DoDoor()
int EV_DoDoor (line_t * line, vldoor_e type)
Definition at line 252 of file p_doors.c.
 {
     int     secnum,rtn;
     sector_t*   sec;
     vldoor_t*   door;
     secnum = -1;
     rtn = 0;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     // new door thinker
     rtn = 1;
     door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
     door->sector = sec;
     door->type = type;
     door->topwait = VDOORWAIT;
     door->speed = VDOORSPEED;
     switch(type)
     {
       case vld_blazeClose:
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->direction = -1;
         door->speed = VDOORSPEED * 4;
         S_StartSound(&door->sector->soundorg, sfx_bdcls);
         break;
       case vld_close:
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->direction = -1;
         S_StartSound(&door->sector->soundorg, sfx_dorcls);
         break;
       case vld_close30ThenOpen:
         door->topheight = sec->ceilingheight;
         door->direction = -1;
         S_StartSound(&door->sector->soundorg, sfx_dorcls);
         break;
       case vld_blazeRaise:
       case vld_blazeOpen:
         door->direction = 1;
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->speed = VDOORSPEED * 4;
         if (door->topheight != sec->ceilingheight)
         S_StartSound(&door->sector->soundorg, sfx_bdopn);
         break;
       case vld_normal:
       case vld_open:
         door->direction = 1;
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         if (door->topheight != sec->ceilingheight)
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
       default:
         break;
     }
     }
     return rtn;
 }
References actionf_t::acp1, sector_t::ceilingheight, vldoor_t::direction, FRACUNIT, thinker_s::function, P_AddThinker(), P_FindLowestCeilingSurrounding(), P_FindSectorFromLineTag(), PU_LEVSPEC, S_StartSound(), vldoor_t::sector, sectors, sfx_bdcls, sfx_bdopn, sfx_dorcls, sfx_doropn, sector_t::soundorg, sector_t::specialdata, vldoor_t::speed, T_VerticalDoor(), vldoor_t::thinker, vldoor_t::topheight, vldoor_t::topwait, type, vldoor_t::type, VDOORSPEED, VDOORWAIT, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_close30ThenOpen, vld_normal, vld_open, and Z_Malloc().
Referenced by A_BossDeath(), A_KeenDie(), EV_DoLockedDoor(), P_CrossSpecialLine(), P_ShootSpecialLine(), and P_UseSpecialLine().
EV_DoFloor()
int EV_DoFloor (line_t * line, floor_e floortype)
Definition at line 251 of file p_floor.c.
 {
     int         secnum;
     int         rtn;
     int         i;
     sector_t*       sec;
     floormove_t*    floor;
     secnum = -1;
     rtn = 0;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     // ALREADY MOVING?  IF SO, KEEP GOING...
     if (sec->specialdata)
         continue;
     // new floor thinker
     rtn = 1;
     floor = Z_Malloc (sizeof(*floor), PU_LEVSPEC, 0);
     P_AddThinker (&floor->thinker);
     sec->specialdata = floor;
     floor->thinker.function.acp1 = (actionf_p1) T_MoveFloor;
     floor->type = floortype;
     floor->crush = false;
     switch(floortype)
     {
       case lowerFloor:
         floor->direction = -1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight =
         P_FindHighestFloorSurrounding(sec);
         break;
       case lowerFloorToLowest:
         floor->direction = -1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight =
         P_FindLowestFloorSurrounding(sec);
         break;
       case turboLower:
         floor->direction = -1;
         floor->sector = sec;
         floor->speed = FLOORSPEED * 4;
         floor->floordestheight =
         P_FindHighestFloorSurrounding(sec);
         if (floor->floordestheight != sec->floorheight)
         floor->floordestheight += 8*FRACUNIT;
         break;
       case raiseFloorCrush:
         floor->crush = true;
       case raiseFloor:
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight =
         P_FindLowestCeilingSurrounding(sec);
         if (floor->floordestheight > sec->ceilingheight)
         floor->floordestheight = sec->ceilingheight;
         floor->floordestheight -= (8*FRACUNIT)*
         (floortype == raiseFloorCrush);
         break;
       case raiseFloorTurbo:
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = FLOORSPEED*4;
         floor->floordestheight =
         P_FindNextHighestFloor(sec,sec->floorheight);
         break;
       case raiseFloorToNearest:
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight =
         P_FindNextHighestFloor(sec,sec->floorheight);
         break;
       case raiseFloor24:
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight = floor->sector->floorheight +
         24 * FRACUNIT;
         break;
       case raiseFloor512:
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight = floor->sector->floorheight +
         512 * FRACUNIT;
         break;
       case raiseFloor24AndChange:
         floor->direction = 1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight = floor->sector->floorheight +
         24 * FRACUNIT;
         sec->floorpic = line->frontsector->floorpic;
         sec->special = line->frontsector->special;
         break;
       case raiseToTexture:
       {
           int   minsize = __INT_MAX__;
           side_t*   side;
           floor->direction = 1;
           floor->sector = sec;
           floor->speed = FLOORSPEED;
           for (i = 0; i < sec->linecount; i++)
           {
           if (twoSided (secnum, i) )
           {
               side = getSide(secnum,i,0);
               if (side->bottomtexture >= 0)
               if (textureheight[side->bottomtexture] <
                   minsize)
                   minsize =
                   textureheight[side->bottomtexture];
               side = getSide(secnum,i,1);
               if (side->bottomtexture >= 0)
               if (textureheight[side->bottomtexture] <
                   minsize)
                   minsize =
                   textureheight[side->bottomtexture];
           }
           }
           floor->floordestheight =
           floor->sector->floorheight + minsize;
       }
       break;
       case lowerAndChange:
         floor->direction = -1;
         floor->sector = sec;
         floor->speed = FLOORSPEED;
         floor->floordestheight =
         P_FindLowestFloorSurrounding(sec);
         floor->texture = sec->floorpic;
         for (i = 0; i < sec->linecount; i++)
         {
         if ( twoSided(secnum, i) )
         {
             if (getSide(secnum,i,0)->sector-sectors == secnum)
             {
             sec = getSector(secnum,i,1);
             if (sec->floorheight == floor->floordestheight)
             {
                 floor->texture = sec->floorpic;
                 floor->newspecial = sec->special;
                 break;
             }
             }
             else
             {
             sec = getSector(secnum,i,0);
             if (sec->floorheight == floor->floordestheight)
             {
                 floor->texture = sec->floorpic;
                 floor->newspecial = sec->special;
                 break;
             }
             }
         }
         }
       default:
         break;
     }
     }
     return rtn;
 }
References side_t::bottomtexture, sector_t::ceilingheight, floor, sector_t::floorheight, sector_t::floorpic, FLOORSPEED, FRACUNIT, getSector(), getSide(), i, sector_t::linecount, lowerAndChange, lowerFloor, lowerFloorToLowest, P_AddThinker(), P_FindHighestFloorSurrounding(), P_FindLowestCeilingSurrounding(), P_FindLowestFloorSurrounding(), P_FindNextHighestFloor(), P_FindSectorFromLineTag(), PU_LEVSPEC, raiseFloor, raiseFloor24, raiseFloor24AndChange, raiseFloor512, raiseFloorCrush, raiseFloorToNearest, raiseFloorTurbo, raiseToTexture, sector, sectors, sector_t::special, sector_t::specialdata, T_MoveFloor(), textureheight, turboLower, twoSided(), and Z_Malloc().
Referenced by A_BossDeath(), P_CrossSpecialLine(), P_ShootSpecialLine(), and P_UseSpecialLine().
EV_DoLockedDoor()
int EV_DoLockedDoor (line_t * line, vldoor_e type, mobj_t * thing)
Definition at line 195 of file p_doors.c.
 {
     player_t*   p;
     p = thing->player;
     if (!p)
     return 0;
     switch(line->special)
     {
       case 99:  // Blue Lock
       case 133:
     if ( !p )
         return 0;
     if (!p->cards[it_bluecard] && !p->cards[it_blueskull])
     {
         p->message = DEH_String(PD_BLUEO);
         S_StartSound(NULL,sfx_oof);
         return 0;
     }
     break;
       case 134: // Red Lock
       case 135:
     if ( !p )
         return 0;
     if (!p->cards[it_redcard] && !p->cards[it_redskull])
     {
         p->message = DEH_String(PD_REDO);
         S_StartSound(NULL,sfx_oof);
         return 0;
     }
     break;
       case 136: // Yellow Lock
       case 137:
     if ( !p )
         return 0;
     if (!p->cards[it_yellowcard] &&
         !p->cards[it_yellowskull])
     {
         p->message = DEH_String(PD_YELLOWO);
         S_StartSound(NULL,sfx_oof);
         return 0;
     }
     break;
     }
     return EV_DoDoor(line,type);
 }
References DEH_String, EV_DoDoor(), it_bluecard, it_blueskull, it_redcard, it_redskull, it_yellowcard, it_yellowskull, NULL, p, PD_BLUEO, PD_REDO, PD_YELLOWO, mobj_s::player, S_StartSound(), sfx_oof, and type.
Referenced by P_UseSpecialLine().
EV_DoPlat()
int EV_DoPlat (line_t * line, plattype_e type, int amount)
Definition at line 129 of file p_plats.c.
 {
     plat_t* plat;
     int     secnum;
     int     rtn;
     sector_t*   sec;
     secnum = -1;
     rtn = 0;
     //  Activate all <type> plats that are in_stasis
     switch(type)
     {
       case perpetualRaise:
     P_ActivateInStasis(line->tag);
     break;
       default:
     break;
     }
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     // Find lowest & highest floors around sector
     rtn = 1;
     plat = Z_Malloc( sizeof(*plat), PU_LEVSPEC, 0);
     P_AddThinker(&plat->thinker);
     plat->type = type;
     plat->sector = sec;
     plat->sector->specialdata = plat;
     plat->thinker.function.acp1 = (actionf_p1) T_PlatRaise;
     plat->crush = false;
     plat->tag = line->tag;
     switch(type)
     {
       case raiseToNearestAndChange:
         plat->speed = PLATSPEED/2;
         sec->floorpic = sides[line->sidenum[0]].sector->floorpic;
         plat->high = P_FindNextHighestFloor(sec,sec->floorheight);
         plat->wait = 0;
         plat->status = up;
         // NO MORE DAMAGE, IF APPLICABLE
         sec->special = 0;
         S_StartSound(&sec->soundorg,sfx_stnmov);
         break;
       case raiseAndChange:
         plat->speed = PLATSPEED/2;
         sec->floorpic = sides[line->sidenum[0]].sector->floorpic;
         plat->high = sec->floorheight + amount*FRACUNIT;
         plat->wait = 0;
         plat->status = up;
         S_StartSound(&sec->soundorg,sfx_stnmov);
         break;
       case downWaitUpStay:
         plat->speed = PLATSPEED * 4;
         plat->low = P_FindLowestFloorSurrounding(sec);
         if (plat->low > sec->floorheight)
         plat->low = sec->floorheight;
         plat->high = sec->floorheight;
         plat->wait = TICRATE*PLATWAIT;
         plat->status = down;
         S_StartSound(&sec->soundorg,sfx_pstart);
         break;
       case blazeDWUS:
         plat->speed = PLATSPEED * 8;
         plat->low = P_FindLowestFloorSurrounding(sec);
         if (plat->low > sec->floorheight)
         plat->low = sec->floorheight;
         plat->high = sec->floorheight;
         plat->wait = TICRATE*PLATWAIT;
         plat->status = down;
         S_StartSound(&sec->soundorg,sfx_pstart);
         break;
       case perpetualRaise:
         plat->speed = PLATSPEED;
         plat->low = P_FindLowestFloorSurrounding(sec);
         if (plat->low > sec->floorheight)
         plat->low = sec->floorheight;
         plat->high = P_FindHighestFloorSurrounding(sec);
         if (plat->high < sec->floorheight)
         plat->high = sec->floorheight;
         plat->wait = TICRATE*PLATWAIT;
         plat->status = P_Random()&1;
         S_StartSound(&sec->soundorg,sfx_pstart);
         break;
     }
     P_AddActivePlat(plat);
     }
     return rtn;
 }
References actionf_t::acp1, blazeDWUS, plat_t::crush, down, downWaitUpStay, sector_t::floorheight, sector_t::floorpic, FRACUNIT, thinker_s::function, plat_t::high, plat_t::low, P_ActivateInStasis(), P_AddActivePlat(), P_AddThinker(), P_FindHighestFloorSurrounding(), P_FindLowestFloorSurrounding(), P_FindNextHighestFloor(), P_FindSectorFromLineTag(), P_Random(), perpetualRaise, PLATSPEED, PLATWAIT, PU_LEVSPEC, raiseAndChange, raiseToNearestAndChange, S_StartSound(), plat_t::sector, side_t::sector, sectors, sfx_pstart, sfx_stnmov, sides, sector_t::soundorg, sector_t::special, sector_t::specialdata, plat_t::speed, plat_t::status, T_PlatRaise(), plat_t::tag, plat_t::thinker, TICRATE, type, plat_t::type, up, plat_t::wait, and Z_Malloc().
Referenced by P_CrossSpecialLine(), P_ShootSpecialLine(), and P_UseSpecialLine().
EV_LightTurnOn()
void EV_LightTurnOn (line_t * line, int bright)
Definition at line 264 of file p_lights.c.
 {
     int     i;
     int     j;
     sector_t*   sector;
     sector_t*   temp;
     line_t* templine;
     sector = sectors;
     for (i=0;i<numsectors;i++, sector++)
     {
     if (sector->tag == line->tag)
     {
         // bright = 0 means to search
         // for highest light level
         // surrounding sector
         if (!bright)
         {
         for (j = 0;j < sector->linecount; j++)
         {
             templine = sector->lines[j];
             temp = getNextSector(templine,sector);
             if (!temp)
             continue;
             if (temp->lightlevel > bright)
             bright = temp->lightlevel;
         }
         }
         sector-> lightlevel = bright;
     }
     }
 }
References getNextSector(), i, j, sector_t::lightlevel, numsectors, sector, and sectors.
Referenced by P_CrossSpecialLine(), and P_UseSpecialLine().
EV_StartLightStrobing()
void EV_StartLightStrobing (line_t * line)
Definition at line 208 of file p_lights.c.
 {
     int     secnum;
     sector_t*   sec;
     secnum = -1;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     P_SpawnStrobeFlash (sec,SLOWDARK, 0);
     }
 }
References P_FindSectorFromLineTag(), P_SpawnStrobeFlash(), sectors, SLOWDARK, and sector_t::specialdata.
Referenced by P_CrossSpecialLine().
EV_StopPlat()
void EV_StopPlat (line_t * line)
Definition at line 263 of file p_plats.c.
 {
     int     j;
     for (j = 0;j < MAXPLATS;j++)
     if (activeplats[j]
         && ((activeplats[j])->status != in_stasis)
         && ((activeplats[j])->tag == line->tag))
     {
         (activeplats[j])->oldstatus = (activeplats[j])->status;
         (activeplats[j])->status = in_stasis;
         (activeplats[j])->thinker.function.acv = (actionf_v)NULL;
     }
 }
References activeplats, in_stasis, j, MAXPLATS, NULL, and status.
Referenced by P_CrossSpecialLine().
EV_Teleport()
int EV_Teleport (line_t * line, int side, mobj_t * thing)
Definition at line 42 of file p_telept.c.
 {
     int     i;
     int     tag;
     mobj_t* m;
     mobj_t* fog;
     unsigned    an;
     thinker_t*  thinker;
     sector_t*   sector;
     fixed_t oldx;
     fixed_t oldy;
     fixed_t oldz;
     // don't teleport missiles
     if (thing->flags & MF_MISSILE)
     return 0;
     // Don't teleport if hit back of line,
     //  so you can get out of teleporter.
     if (side == 1)
     return 0;
     tag = line->tag;
     for (i = 0; i < numsectors; i++)
     {
     if (sectors[ i ].tag == tag )
     {
         thinker = thinkercap.next;
         for (thinker = thinkercap.next;
          thinker != &thinkercap;
          thinker = thinker->next)
         {
         // not a mobj
         if (thinker->function.acp1 != (actionf_p1)P_MobjThinker)
             continue;
         m = (mobj_t *)thinker;
         // not a teleportman
         if (m->type != MT_TELEPORTMAN )
             continue;
         sector = m->subsector->sector;
         // wrong sector
         if (sector-sectors != i )
             continue;
         oldx = thing->x;
         oldy = thing->y;
         oldz = thing->z;
         if (!P_TeleportMove (thing, m->x, m->y))
             return 0;
                 // The first Final Doom executable does not set thing->z
                 // when teleporting. This quirk is unique to this
                 // particular version; the later version included in
                 // some versions of the Id Anthology fixed this.
                 if (gameversion != exe_final)
             thing->z = thing->floorz;
         if (thing->player)
             thing->player->viewz = thing->z+thing->player->viewheight;
         // spawn teleport fog at source and destination
         fog = P_SpawnMobj (oldx, oldy, oldz, MT_TFOG);
         S_StartSound (fog, sfx_telept);
         an = m->angle >> ANGLETOFINESHIFT;
         fog = P_SpawnMobj (m->x+20*finecosine[an], m->y+20*finesine[an]
                    , thing->z, MT_TFOG);
         // emit sound, where?
         S_StartSound (fog, sfx_telept);
         // don't move for a bit
         if (thing->player)
             thing->reactiontime = 18;
         thing->angle = m->angle;
         thing->momx = thing->momy = thing->momz = 0;
         return 1;
         }
     }
     }
     return 0;
 }
References actionf_t::acp1, mobj_s::angle, ANGLETOFINESHIFT, exe_final, finecosine, finesine, mobj_s::flags, mobj_s::floorz, thinker_s::function, gameversion, i, MF_MISSILE, mobj_s::momx, mobj_s::momy, mobj_s::momz, MT_TELEPORTMAN, MT_TFOG, thinker_s::next, numsectors, P_MobjThinker(), P_SpawnMobj(), P_TeleportMove(), mobj_s::player, mobj_s::reactiontime, S_StartSound(), sector, subsector_s::sector, sectors, sfx_telept, mobj_s::subsector, thinkercap, mobj_s::type, player_s::viewheight, player_s::viewz, mobj_s::x, mobj_s::y, and mobj_s::z.
Referenced by P_CrossSpecialLine().
EV_TurnTagLightsOff()
void EV_TurnTagLightsOff (line_t * line)
Definition at line 229 of file p_lights.c.
 {
     int         i;
     int         j;
     int         min;
     sector_t*       sector;
     sector_t*       tsec;
     line_t*     templine;
     sector = sectors;
     for (j = 0;j < numsectors; j++, sector++)
     {
     if (sector->tag == line->tag)
     {
         min = sector->lightlevel;
         for (i = 0;i < sector->linecount; i++)
         {
         templine = sector->lines[i];
         tsec = getNextSector(templine,sector);
         if (!tsec)
             continue;
         if (tsec->lightlevel < min)
             min = tsec->lightlevel;
         }
         sector->lightlevel = min;
     }
     }
 }
References getNextSector(), i, j, sector_t::lightlevel, min, numsectors, sector, and sectors.
Referenced by P_CrossSpecialLine().
EV_VerticalDoor()
void EV_VerticalDoor (line_t * line, mobj_t * thing)
Definition at line 337 of file p_doors.c.
 {
     player_t*   player;
     sector_t*   sec;
     vldoor_t*   door;
     int     side;
     side = 0;   // only front sides can be used
     //  Check for locks
     player = thing->player;
     switch(line->special)
     {
       case 26: // Blue Lock
       case 32:
     if ( !player )
         return;
     if (!player->cards[it_bluecard] && !player->cards[it_blueskull])
     {
         player->message = DEH_String(PD_BLUEK);
         S_StartSound(NULL,sfx_oof);
         return;
     }
     break;
       case 27: // Yellow Lock
       case 34:
     if ( !player )
         return;
     if (!player->cards[it_yellowcard] &&
         !player->cards[it_yellowskull])
     {
         player->message = DEH_String(PD_YELLOWK);
         S_StartSound(NULL,sfx_oof);
         return;
     }
     break;
       case 28: // Red Lock
       case 33:
     if ( !player )
         return;
     if (!player->cards[it_redcard] && !player->cards[it_redskull])
     {
         player->message = DEH_String(PD_REDK);
         S_StartSound(NULL,sfx_oof);
         return;
     }
     break;
     }
     // if the sector has an active thinker, use it
     sec = sides[ line->sidenum[side^1]] .sector;
     if (sec->specialdata)
     {
     door = sec->specialdata;
     switch(line->special)
     {
       case  1: // ONLY FOR "RAISE" DOORS, NOT "OPEN"s
       case  26:
       case  27:
       case  28:
       case  117:
         if (door->direction == -1)
         door->direction = 1;    // go back up
         else
         {
         if (!thing->player)
             return;     // JDC: bad guys never close doors
                 // When is a door not a door?
                 // In Vanilla, door->direction is set, even though
                 // "specialdata" might not actually point at a door.
                 if (door->thinker.function.acp1 == (actionf_p1) T_VerticalDoor)
                 {
                     door->direction = -1;   // start going down immediately
                 }
                 else if (door->thinker.function.acp1 == (actionf_p1) T_PlatRaise)
                 {
                     // Erm, this is a plat, not a door.
                     // This notably causes a problem in ep1-0500.lmp where
                     // a plat and a door are cross-referenced; the door
                     // doesn't open on 64-bit.
                     // The direction field in vldoor_t corresponds to the wait
                     // field in plat_t.  Let's set that to -1 instead.
                     plat_t *plat;
                     plat = (plat_t *) door;
                     plat->wait = -1;
                 }
                 else
                 {
                     // This isn't a door OR a plat.  Now we're in trouble.
                     fprintf(stderr, "EV_VerticalDoor: Tried to close "
                                     "something that wasn't a door.\n");
                     // Try closing it anyway. At least it will work on 32-bit
                     // machines.
                     door->direction = -1;
                 }
         }
         return;
     }
     }
     // for proper sound
     switch(line->special)
     {
       case 117: // BLAZING DOOR RAISE
       case 118: // BLAZING DOOR OPEN
     S_StartSound(&sec->soundorg,sfx_bdopn);
     break;
       case 1:   // NORMAL DOOR SOUND
       case 31:
     S_StartSound(&sec->soundorg,sfx_doropn);
     break;
       default:  // LOCKED DOOR SOUND
     S_StartSound(&sec->soundorg,sfx_doropn);
     break;
     }
     // new door thinker
     door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
     door->sector = sec;
     door->direction = 1;
     door->speed = VDOORSPEED;
     door->topwait = VDOORWAIT;
     switch(line->special)
     {
       case 1:
       case 26:
       case 27:
       case 28:
     door->type = vld_normal;
     break;
       case 31:
       case 32:
       case 33:
       case 34:
     door->type = vld_open;
     line->special = 0;
     break;
       case 117: // blazing door raise
     door->type = vld_blazeRaise;
     door->speed = VDOORSPEED*4;
     break;
       case 118: // blazing door open
     door->type = vld_blazeOpen;
     line->special = 0;
     door->speed = VDOORSPEED*4;
     break;
     }
     // find the top and bottom of the movement range
     door->topheight = P_FindLowestCeilingSurrounding(sec);
     door->topheight -= 4*FRACUNIT;
 }
References actionf_t::acp1, player_s::cards, DEH_String, vldoor_t::direction, fprintf(), FRACUNIT, thinker_s::function, it_bluecard, it_blueskull, it_redcard, it_redskull, it_yellowcard, it_yellowskull, player_s::message, NULL, P_AddThinker(), P_FindLowestCeilingSurrounding(), PD_BLUEK, PD_REDK, PD_YELLOWK, mobj_s::player, PU_LEVSPEC, S_StartSound(), vldoor_t::sector, side_t::sector, sfx_bdopn, sfx_doropn, sfx_oof, sides, sector_t::soundorg, sector_t::specialdata, vldoor_t::speed, stderr, T_PlatRaise(), T_VerticalDoor(), vldoor_t::thinker, vldoor_t::topheight, vldoor_t::topwait, vldoor_t::type, VDOORSPEED, VDOORWAIT, vld_blazeOpen, vld_blazeRaise, vld_normal, vld_open, plat_t::wait, and Z_Malloc().
Referenced by P_UseSpecialLine().
getNextSector()
sector_t* getNextSector (line_t * line, sector_t * sec)
Definition at line 250 of file p_spec.c.
 {
     if (!(line->flags & ML_TWOSIDED))
     return NULL;
     if (line->frontsector == sec)
     return line->backsector;
     return line->frontsector;
 }
References ML_TWOSIDED, and NULL.
Referenced by EV_DoDonut(), EV_LightTurnOn(), EV_TurnTagLightsOff(), P_FindHighestCeilingSurrounding(), P_FindHighestFloorSurrounding(), P_FindLowestCeilingSurrounding(), P_FindLowestFloorSurrounding(), P_FindMinSurroundingLight(), and P_FindNextHighestFloor().
getSector()
sector_t* getSector (int currentSector, int line, int side)
Definition at line 219 of file p_spec.c.
 {
     return sides[ (sectors[currentSector].lines[line])->sidenum[side] ].sector;
 }
References line, sector_t::lines, sector, sectors, and sides.
Referenced by EV_DoFloor().
getSide()
side_t* getSide (int currentSector, int line, int side)
Definition at line 203 of file p_spec.c.
 {
     return &sides[ (sectors[currentSector].lines[line])->sidenum[side] ];
 }
References line, sector_t::lines, sectors, and sides.
Referenced by EV_DoFloor().
P_ActivateInStasis()
void P_ActivateInStasis (int tag)
Definition at line 248 of file p_plats.c.
 {
     int     i;
     for (i = 0;i < MAXPLATS;i++)
     if (activeplats[i]
         && (activeplats[i])->tag == tag
         && (activeplats[i])->status == in_stasis)
     {
         (activeplats[i])->status = (activeplats[i])->oldstatus;
         (activeplats[i])->thinker.function.acp1
           = (actionf_p1) T_PlatRaise;
     }
 }
References activeplats, i, in_stasis, MAXPLATS, status, and T_PlatRaise().
Referenced by EV_DoPlat().
P_ActivateInStasisCeiling()
void P_ActivateInStasisCeiling (line_t * line)
Definition at line 280 of file p_ceilng.c.
 {
     int     i;
     for (i = 0;i < MAXCEILINGS;i++)
     {
     if (activeceilings[i]
         && (activeceilings[i]->tag == line->tag)
         && (activeceilings[i]->direction == 0))
     {
         activeceilings[i]->direction = activeceilings[i]->olddirection;
         activeceilings[i]->thinker.function.acp1
           = (actionf_p1)T_MoveCeiling;
     }
     }
 }
References actionf_t::acp1, activeceilings, ceiling_t::direction, thinker_s::function, i, MAXCEILINGS, ceiling_t::olddirection, T_MoveCeiling(), and ceiling_t::thinker.
Referenced by EV_DoCeiling().
P_AddActiveCeiling()
void P_AddActiveCeiling (ceiling_t * c)
Definition at line 240 of file p_ceilng.c.
 {
     int     i;
     for (i = 0; i < MAXCEILINGS;i++)
     {
     if (activeceilings[i] == NULL)
     {
         activeceilings[i] = c;
         return;
     }
     }
 }
References activeceilings, c, i, MAXCEILINGS, and NULL.
Referenced by EV_DoCeiling(), and P_UnArchiveSpecials().
P_AddActivePlat()
void P_AddActivePlat (plat_t * plat)
Definition at line 278 of file p_plats.c.
 {
     int     i;
     for (i = 0;i < MAXPLATS;i++)
     if (activeplats[i] == NULL)
     {
         activeplats[i] = plat;
         return;
     }
     I_Error ("P_AddActivePlat: no more plats!");
 }
References activeplats, i, I_Error(), MAXPLATS, and NULL.
Referenced by EV_DoPlat(), and P_UnArchiveSpecials().
P_ChangeSwitchTexture()
void P_ChangeSwitchTexture (line_t * line, int useAgain)
Definition at line 195 of file p_switch.c.
 {
     int     texTop;
     int     texMid;
     int     texBot;
     int     i;
     int     sound;
     if (!useAgain)
     line->special = 0;
     texTop = sides[line->sidenum[0]].toptexture;
     texMid = sides[line->sidenum[0]].midtexture;
     texBot = sides[line->sidenum[0]].bottomtexture;
     sound = sfx_swtchn;
     // EXIT SWITCH?
     if (line->special == 11)
     sound = sfx_swtchx;
     for (i = 0;i < numswitches*2;i++)
     {
     if (switchlist[i] == texTop)
     {
         S_StartSound(buttonlist->soundorg,sound);
         sides[line->sidenum[0]].toptexture = switchlist[i^1];
         if (useAgain)
         P_StartButton(line,top,switchlist[i],BUTTONTIME);
         return;
     }
     else
     {
         if (switchlist[i] == texMid)
         {
         S_StartSound(buttonlist->soundorg,sound);
         sides[line->sidenum[0]].midtexture = switchlist[i^1];
         if (useAgain)
             P_StartButton(line, middle,switchlist[i],BUTTONTIME);
         return;
         }
         else
         {
         if (switchlist[i] == texBot)
         {
             S_StartSound(buttonlist->soundorg,sound);
             sides[line->sidenum[0]].bottomtexture = switchlist[i^1];
             if (useAgain)
             P_StartButton(line, bottom,switchlist[i],BUTTONTIME);
             return;
         }
         }
     }
     }
 }
References bottom, side_t::bottomtexture, buttonlist, BUTTONTIME, i, middle, side_t::midtexture, numswitches, P_StartButton(), S_StartSound(), sfx_swtchn, sfx_swtchx, sides, button_t::soundorg, switchlist, top, and side_t::toptexture.
Referenced by P_ShootSpecialLine(), and P_UseSpecialLine().
P_CrossSpecialLine()
void P_CrossSpecialLine (int linenum, int side, mobj_t * thing)
Definition at line 502 of file p_spec.c.
 {
     line_t* line;
     int     ok;
     line = &lines[linenum];
     //  Triggers that other things can activate
     if (!thing->player)
     {
     // Things that should NOT trigger specials...
     switch(thing->type)
     {
       case MT_ROCKET:
       case MT_PLASMA:
       case MT_BFG:
       case MT_TROOPSHOT:
       case MT_HEADSHOT:
       case MT_BRUISERSHOT:
         return;
         break;
       default: break;
     }
     ok = 0;
     switch(line->special)
     {
       case 39:  // TELEPORT TRIGGER
       case 97:  // TELEPORT RETRIGGER
       case 125: // TELEPORT MONSTERONLY TRIGGER
       case 126: // TELEPORT MONSTERONLY RETRIGGER
       case 4:   // RAISE DOOR
       case 10:  // PLAT DOWN-WAIT-UP-STAY TRIGGER
       case 88:  // PLAT DOWN-WAIT-UP-STAY RETRIGGER
         ok = 1;
         break;
     }
     if (!ok)
         return;
     }
     // Note: could use some const's here.
     switch (line->special)
     {
     // TRIGGERS.
     // All from here to RETRIGGERS.
       case 2:
     // Open Door
     EV_DoDoor(line,vld_open);
     line->special = 0;
     break;
       case 3:
     // Close Door
     EV_DoDoor(line,vld_close);
     line->special = 0;
     break;
       case 4:
     // Raise Door
     EV_DoDoor(line,vld_normal);
     line->special = 0;
     break;
       case 5:
     // Raise Floor
     EV_DoFloor(line,raiseFloor);
     line->special = 0;
     break;
       case 6:
     // Fast Ceiling Crush & Raise
     EV_DoCeiling(line,fastCrushAndRaise);
     line->special = 0;
     break;
       case 8:
     // Build Stairs
     EV_BuildStairs(line,build8);
     line->special = 0;
     break;
       case 10:
     // PlatDownWaitUp
     EV_DoPlat(line,downWaitUpStay,0);
     line->special = 0;
     break;
       case 12:
     // Light Turn On - brightest near
     EV_LightTurnOn(line,0);
     line->special = 0;
     break;
       case 13:
     // Light Turn On 255
     EV_LightTurnOn(line,255);
     line->special = 0;
     break;
       case 16:
     // Close Door 30
     EV_DoDoor(line,vld_close30ThenOpen);
     line->special = 0;
     break;
       case 17:
     // Start Light Strobing
     EV_StartLightStrobing(line);
     line->special = 0;
     break;
       case 19:
     // Lower Floor
     EV_DoFloor(line,lowerFloor);
     line->special = 0;
     break;
       case 22:
     // Raise floor to nearest height and change texture
     EV_DoPlat(line,raiseToNearestAndChange,0);
     line->special = 0;
     break;
       case 25:
     // Ceiling Crush and Raise
     EV_DoCeiling(line,crushAndRaise);
     line->special = 0;
     break;
       case 30:
     // Raise floor to shortest texture height
     //  on either side of lines.
     EV_DoFloor(line,raiseToTexture);
     line->special = 0;
     break;
       case 35:
     // Lights Very Dark
     EV_LightTurnOn(line,35);
     line->special = 0;
     break;
       case 36:
     // Lower Floor (TURBO)
     EV_DoFloor(line,turboLower);
     line->special = 0;
     break;
       case 37:
     // LowerAndChange
     EV_DoFloor(line,lowerAndChange);
     line->special = 0;
     break;
       case 38:
     // Lower Floor To Lowest
     EV_DoFloor( line, lowerFloorToLowest );
     line->special = 0;
     break;
       case 39:
     // TELEPORT!
     EV_Teleport( line, side, thing );
     line->special = 0;
     break;
       case 40:
     // RaiseCeilingLowerFloor
     EV_DoCeiling( line, raiseToHighest );
     EV_DoFloor( line, lowerFloorToLowest );
     line->special = 0;
     break;
       case 44:
     // Ceiling Crush
     EV_DoCeiling( line, lowerAndCrush );
     line->special = 0;
     break;
       case 52:
     // EXIT!
     G_ExitLevel ();
     break;
       case 53:
     // Perpetual Platform Raise
     EV_DoPlat(line,perpetualRaise,0);
     line->special = 0;
     break;
       case 54:
     // Platform Stop
     EV_StopPlat(line);
     line->special = 0;
     break;
       case 56:
     // Raise Floor Crush
     EV_DoFloor(line,raiseFloorCrush);
     line->special = 0;
     break;
       case 57:
     // Ceiling Crush Stop
     EV_CeilingCrushStop(line);
     line->special = 0;
     break;
       case 58:
     // Raise Floor 24
     EV_DoFloor(line,raiseFloor24);
     line->special = 0;
     break;
       case 59:
     // Raise Floor 24 And Change
     EV_DoFloor(line,raiseFloor24AndChange);
     line->special = 0;
     break;
       case 104:
     // Turn lights off in sector(tag)
     EV_TurnTagLightsOff(line);
     line->special = 0;
     break;
       case 108:
     // Blazing Door Raise (faster than TURBO!)
     EV_DoDoor (line,vld_blazeRaise);
     line->special = 0;
     break;
       case 109:
     // Blazing Door Open (faster than TURBO!)
     EV_DoDoor (line,vld_blazeOpen);
     line->special = 0;
     break;
       case 100:
     // Build Stairs Turbo 16
     EV_BuildStairs(line,turbo16);
     line->special = 0;
     break;
       case 110:
     // Blazing Door Close (faster than TURBO!)
     EV_DoDoor (line,vld_blazeClose);
     line->special = 0;
     break;
       case 119:
     // Raise floor to nearest surr. floor
     EV_DoFloor(line,raiseFloorToNearest);
     line->special = 0;
     break;
       case 121:
     // Blazing PlatDownWaitUpStay
     EV_DoPlat(line,blazeDWUS,0);
     line->special = 0;
     break;
       case 124:
     // Secret EXIT
     G_SecretExitLevel ();
     break;
       case 125:
     // TELEPORT MonsterONLY
     if (!thing->player)
     {
         EV_Teleport( line, side, thing );
         line->special = 0;
     }
     break;
       case 130:
     // Raise Floor Turbo
     EV_DoFloor(line,raiseFloorTurbo);
     line->special = 0;
     break;
       case 141:
     // Silent Ceiling Crush & Raise
     EV_DoCeiling(line,silentCrushAndRaise);
     line->special = 0;
     break;
     // RETRIGGERS.  All from here till end.
       case 72:
     // Ceiling Crush
     EV_DoCeiling( line, lowerAndCrush );
     break;
       case 73:
     // Ceiling Crush and Raise
     EV_DoCeiling(line,crushAndRaise);
     break;
       case 74:
     // Ceiling Crush Stop
     EV_CeilingCrushStop(line);
     break;
       case 75:
     // Close Door
     EV_DoDoor(line,vld_close);
     break;
       case 76:
     // Close Door 30
     EV_DoDoor(line,vld_close30ThenOpen);
     break;
       case 77:
     // Fast Ceiling Crush & Raise
     EV_DoCeiling(line,fastCrushAndRaise);
     break;
       case 79:
     // Lights Very Dark
     EV_LightTurnOn(line,35);
     break;
       case 80:
     // Light Turn On - brightest near
     EV_LightTurnOn(line,0);
     break;
       case 81:
     // Light Turn On 255
     EV_LightTurnOn(line,255);
     break;
       case 82:
     // Lower Floor To Lowest
     EV_DoFloor( line, lowerFloorToLowest );
     break;
       case 83:
     // Lower Floor
     EV_DoFloor(line,lowerFloor);
     break;
       case 84:
     // LowerAndChange
     EV_DoFloor(line,lowerAndChange);
     break;
       case 86:
     // Open Door
     EV_DoDoor(line,vld_open);
     break;
       case 87:
     // Perpetual Platform Raise
     EV_DoPlat(line,perpetualRaise,0);
     break;
       case 88:
     // PlatDownWaitUp
     EV_DoPlat(line,downWaitUpStay,0);
     break;
       case 89:
     // Platform Stop
     EV_StopPlat(line);
     break;
       case 90:
     // Raise Door
     EV_DoDoor(line,vld_normal);
     break;
       case 91:
     // Raise Floor
     EV_DoFloor(line,raiseFloor);
     break;
       case 92:
     // Raise Floor 24
     EV_DoFloor(line,raiseFloor24);
     break;
       case 93:
     // Raise Floor 24 And Change
     EV_DoFloor(line,raiseFloor24AndChange);
     break;
       case 94:
     // Raise Floor Crush
     EV_DoFloor(line,raiseFloorCrush);
     break;
       case 95:
     // Raise floor to nearest height
     // and change texture.
     EV_DoPlat(line,raiseToNearestAndChange,0);
     break;
       case 96:
     // Raise floor to shortest texture height
     // on either side of lines.
     EV_DoFloor(line,raiseToTexture);
     break;
       case 97:
     // TELEPORT!
     EV_Teleport( line, side, thing );
     break;
       case 98:
     // Lower Floor (TURBO)
     EV_DoFloor(line,turboLower);
     break;
       case 105:
     // Blazing Door Raise (faster than TURBO!)
     EV_DoDoor (line,vld_blazeRaise);
     break;
       case 106:
     // Blazing Door Open (faster than TURBO!)
     EV_DoDoor (line,vld_blazeOpen);
     break;
       case 107:
     // Blazing Door Close (faster than TURBO!)
     EV_DoDoor (line,vld_blazeClose);
     break;
       case 120:
     // Blazing PlatDownWaitUpStay.
     EV_DoPlat(line,blazeDWUS,0);
     break;
       case 126:
     // TELEPORT MonsterONLY.
     if (!thing->player)
         EV_Teleport( line, side, thing );
     break;
       case 128:
     // Raise To Nearest Floor
     EV_DoFloor(line,raiseFloorToNearest);
     break;
       case 129:
     // Raise Floor Turbo
     EV_DoFloor(line,raiseFloorTurbo);
     break;
     }
 }
References blazeDWUS, build8, crushAndRaise, downWaitUpStay, EV_BuildStairs(), EV_CeilingCrushStop(), EV_DoCeiling(), EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), EV_LightTurnOn(), EV_StartLightStrobing(), EV_StopPlat(), EV_Teleport(), EV_TurnTagLightsOff(), fastCrushAndRaise, G_ExitLevel(), G_SecretExitLevel(), line, lines, lowerAndChange, lowerAndCrush, lowerFloor, lowerFloorToLowest, MT_BFG, MT_BRUISERSHOT, MT_HEADSHOT, MT_PLASMA, MT_ROCKET, MT_TROOPSHOT, ok, perpetualRaise, mobj_s::player, raiseFloor, raiseFloor24, raiseFloor24AndChange, raiseFloorCrush, raiseFloorToNearest, raiseFloorTurbo, raiseToHighest, raiseToNearestAndChange, raiseToTexture, silentCrushAndRaise, turbo16, turboLower, mobj_s::type, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_close30ThenOpen, vld_normal, and vld_open.
Referenced by P_TryMove().
P_FindHighestCeilingSurrounding()
fixed_t P_FindHighestCeilingSurrounding (sector_t * sec)
Definition at line 417 of file p_spec.c.
 {
     int     i;
     line_t* check;
     sector_t*   other;
     fixed_t height = 0;
     for (i=0 ;i < sec->linecount ; i++)
     {
     check = sec->lines[i];
     other = getNextSector(check,sec);
     if (!other)
         continue;
     if (other->ceilingheight > height)
         height = other->ceilingheight;
     }
     return height;
 }
References sector_t::ceilingheight, check(), getNextSector(), height(), i, sector_t::linecount, and sector_t::lines.
Referenced by EV_DoCeiling().
P_FindHighestFloorSurrounding()
fixed_t P_FindHighestFloorSurrounding (sector_t * sec)
Definition at line 296 of file p_spec.c.
 {
     int         i;
     line_t*     check;
     sector_t*       other;
     fixed_t     floor = -500*FRACUNIT;
     for (i=0 ;i < sec->linecount ; i++)
     {
     check = sec->lines[i];
     other = getNextSector(check,sec);
     if (!other)
         continue;
     if (other->floorheight > floor)
         floor = other->floorheight;
     }
     return floor;
 }
References check(), floor, sector_t::floorheight, FRACUNIT, getNextSector(), i, sector_t::linecount, and sector_t::lines.
Referenced by EV_DoFloor(), and EV_DoPlat().
P_FindLowestCeilingSurrounding()
fixed_t P_FindLowestCeilingSurrounding (sector_t * sec)
Definition at line 392 of file p_spec.c.
 {
     int         i;
     line_t*     check;
     sector_t*       other;
     fixed_t     height = __INT_MAX__;
     for (i=0 ;i < sec->linecount ; i++)
     {
     check = sec->lines[i];
     other = getNextSector(check,sec);
     if (!other)
         continue;
     if (other->ceilingheight < height)
         height = other->ceilingheight;
     }
     return height;
 }
References sector_t::ceilingheight, check(), getNextSector(), height(), i, sector_t::linecount, and sector_t::lines.
Referenced by EV_DoDoor(), EV_DoFloor(), EV_VerticalDoor(), and P_SpawnDoorRaiseIn5Mins().
P_FindLowestFloorSurrounding()
fixed_t P_FindLowestFloorSurrounding (sector_t * sec)
Definition at line 269 of file p_spec.c.
 {
     int         i;
     line_t*     check;
     sector_t*       other;
     fixed_t     floor = sec->floorheight;
     for (i=0 ;i < sec->linecount ; i++)
     {
     check = sec->lines[i];
     other = getNextSector(check,sec);
     if (!other)
         continue;
     if (other->floorheight < floor)
         floor = other->floorheight;
     }
     return floor;
 }
References check(), floor, sector_t::floorheight, getNextSector(), i, sector_t::linecount, and sector_t::lines.
Referenced by EV_DoFloor(), and EV_DoPlat().
P_FindMinSurroundingLight()
int P_FindMinSurroundingLight (sector_t * sector, int max)
Definition at line 464 of file p_spec.c.
 {
     int     i;
     int     min;
     line_t* line;
     sector_t*   check;
     min = max;
     for (i=0 ; i < sector->linecount ; i++)
     {
     line = sector->lines[i];
     check = getNextSector(line,sector);
     if (!check)
         continue;
     if (check->lightlevel < min)
         min = check->lightlevel;
     }
     return min;
 }
References check(), getNextSector(), i, line, max, min, and sector.
Referenced by P_SpawnFireFlicker(), P_SpawnGlowingLight(), P_SpawnLightFlash(), and P_SpawnStrobeFlash().
P_FindNextHighestFloor()
fixed_t P_FindNextHighestFloor (sector_t * sec, int currentheight)
Definition at line 330 of file p_spec.c.
 {
     int         i;
     int         h;
     int         min;
     line_t*     check;
     sector_t*   other;
     fixed_t     height = currentheight;
     fixed_t     heightlist[MAX_ADJOINING_SECTORS + 2];
     for (i=0, h=0; i < sec->linecount; i++)
     {
         check = sec->lines[i];
         other = getNextSector(check,sec);
         if (!other)
             continue;
         if (other->floorheight > height)
         {
             // Emulation of memory (stack) overflow
             if (h == MAX_ADJOINING_SECTORS + 1)
             {
                 height = other->floorheight;
             }
             else if (h == MAX_ADJOINING_SECTORS + 2)
             {
                 // Fatal overflow: game crashes at 22 textures
                 I_Error("Sector with more than 22 adjoining sectors. "
                         "Vanilla will crash here");
             }
             heightlist[h++] = other->floorheight;
         }
     }
     // Find lowest height in list
     if (!h)
     {
         return currentheight;
     }
     min = heightlist[0];
     // Range checking?
     for (i = 1; i < h; i++)
     {
         if (heightlist[i] < min)
         {
             min = heightlist[i];
         }
     }
     return min;
 }
References check(), sector_t::floorheight, getNextSector(), h, height(), i, I_Error(), sector_t::linecount, sector_t::lines, MAX_ADJOINING_SECTORS, and min.
Referenced by EV_DoFloor(), and EV_DoPlat().
P_FindSectorFromLineTag()
int P_FindSectorFromLineTag (line_t * line, int start)
Definition at line 444 of file p_spec.c.
 {
     int i;
     for (i=start+1;i<numsectors;i++)
     if (sectors[i].tag == line->tag)
         return i;
     return -1;
 }
References i, numsectors, sectors, and start.
Referenced by EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), and EV_StartLightStrobing().
P_InitPicAnims()
void P_InitPicAnims (void)
Definition at line 143 of file p_spec.c.
 {
     int     i;
     //  Init animation
     lastanim = anims;
     for (i=0 ; animdefs[i].istexture != -1 ; i++)
     {
         char *startname, *endname;
         startname = DEH_String(animdefs[i].startname);
         endname = DEH_String(animdefs[i].endname);
     if (animdefs[i].istexture)
     {
         // different episode ?
         if (R_CheckTextureNumForName(startname) == -1)
         continue;
         lastanim->picnum = R_TextureNumForName(endname);
         lastanim->basepic = R_TextureNumForName(startname);
     }
     else
     {
         if (W_CheckNumForName(startname) == -1)
         continue;
         lastanim->picnum = R_FlatNumForName(endname);
         lastanim->basepic = R_FlatNumForName(startname);
     }
     lastanim->istexture = animdefs[i].istexture;
     lastanim->numpics = lastanim->picnum - lastanim->basepic + 1;
     if (lastanim->numpics < 2)
         I_Error ("P_InitPicAnims: bad cycle from %s to %s",
              startname, endname);
     lastanim->speed = animdefs[i].speed;
     lastanim++;
     }
 }
References animdefs, anims, anim_t::basepic, DEH_String, i, I_Error(), anim_t::istexture, animdef_t::istexture, lastanim, anim_t::numpics, anim_t::picnum, R_CheckTextureNumForName(), R_FlatNumForName(), R_TextureNumForName(), anim_t::speed, animdef_t::speed, and W_CheckNumForName().
Referenced by P_Init().
P_InitSwitchList()
void P_InitSwitchList (void)
Definition at line 101 of file p_switch.c.
 {
     int     i;
     int     index;
     int     episode;
     episode = 1;
     if (gamemode == registered || gamemode == retail)
     episode = 2;
     else
     if ( gamemode == commercial )
         episode = 3;
     for (index = 0,i = 0;i < MAXSWITCHES;i++)
     {
     if (!alphSwitchList[i].episode)
     {
         numswitches = index/2;
         switchlist[index] = -1;
         break;
     }
     if (alphSwitchList[i].episode <= episode)
     {
 #if 0   // UNUSED - debug?
         int     value;
         if (R_CheckTextureNumForName(alphSwitchList[i].name1) < 0)
         {
         I_Error("Can't find switch texture '%s'!",
             alphSwitchList[i].name1);
         continue;
         }
         value = R_TextureNumForName(alphSwitchList[i].name1);
 #endif
         switchlist[index++] = R_TextureNumForName(DEH_String(alphSwitchList[i].name1));
         switchlist[index++] = R_TextureNumForName(DEH_String(alphSwitchList[i].name2));
     }
     }
 }
References alphSwitchList, commercial, DEH_String, gamemode, i, I_Error(), index(), MAXSWITCHES, numswitches, R_CheckTextureNumForName(), R_TextureNumForName(), registered, retail, switchlist, and value.
Referenced by P_Init().
P_PlayerInSpecialSector()
void P_PlayerInSpecialSector (player_t * player)
Definition at line 1019 of file p_spec.c.
 {
     sector_t*   sector;
     sector = player->mo->subsector->sector;
     // Falling, not all the way down yet?
     if (player->mo->z != sector->floorheight)
     return;
     // Has hitten ground.
     switch (sector->special)
     {
       case 5:
     // HELLSLIME DAMAGE
     if (!player->powers[pw_ironfeet])
         if (!(leveltime&0x1f))
         P_DamageMobj (player->mo, NULL, NULL, 10);
     break;
       case 7:
     // NUKAGE DAMAGE
     if (!player->powers[pw_ironfeet])
         if (!(leveltime&0x1f))
         P_DamageMobj (player->mo, NULL, NULL, 5);
     break;
       case 16:
     // SUPER HELLSLIME DAMAGE
       case 4:
     // STROBE HURT
     if (!player->powers[pw_ironfeet]
         || (P_Random()<5) )
     {
         if (!(leveltime&0x1f))
         P_DamageMobj (player->mo, NULL, NULL, 20);
     }
     break;
       case 9:
     // SECRET SECTOR
     player->secretcount++;
     sector->special = 0;
     break;
       case 11:
     // EXIT SUPER DAMAGE! (for E1M8 finale)
     player->cheats &= ~CF_GODMODE;
     if (!(leveltime&0x1f))
         P_DamageMobj (player->mo, NULL, NULL, 20);
     if (player->health <= 10)
         G_ExitLevel();
     break;
       default:
     I_Error ("P_PlayerInSpecialSector: "
          "unknown special %i",
          sector->special);
     break;
     };
 }
References CF_GODMODE, player_s::cheats, G_ExitLevel(), player_s::health, I_Error(), leveltime, player_s::mo, NULL, P_DamageMobj(), P_Random(), player_s::powers, pw_ironfeet, player_s::secretcount, sector, subsector_s::sector, mobj_s::subsector, and mobj_s::z.
Referenced by P_PlayerThink().
P_RemoveActiveCeiling()
void P_RemoveActiveCeiling (ceiling_t * c)
Definition at line 259 of file p_ceilng.c.
 {
     int     i;
     for (i = 0;i < MAXCEILINGS;i++)
     {
     if (activeceilings[i] == c)
     {
         activeceilings[i]->sector->specialdata = NULL;
         P_RemoveThinker (&activeceilings[i]->thinker);
         activeceilings[i] = NULL;
         break;
     }
     }
 }
References activeceilings, c, i, MAXCEILINGS, NULL, P_RemoveThinker(), ceiling_t::sector, and sector_t::specialdata.
Referenced by T_MoveCeiling().
P_RemoveActivePlat()
void P_RemoveActivePlat (plat_t * plat)
Definition at line 291 of file p_plats.c.
 {
     int     i;
     for (i = 0;i < MAXPLATS;i++)
     if (plat == activeplats[i])
     {
         (activeplats[i])->sector->specialdata = NULL;
         P_RemoveThinker(&(activeplats[i])->thinker);
         activeplats[i] = NULL;
         return;
     }
     I_Error ("P_RemoveActivePlat: can't find plat!");
 }
References activeplats, i, I_Error(), MAXPLATS, NULL, P_RemoveThinker(), and sector.
Referenced by T_PlatRaise().
P_ShootSpecialLine()
void P_ShootSpecialLine (mobj_t * thing, line_t * line)
Definition at line 969 of file p_spec.c.
 {
     int     ok;
     //  Impacts that other things can activate.
     if (!thing->player)
     {
     ok = 0;
     switch(line->special)
     {
       case 46:
         // OPEN DOOR IMPACT
         ok = 1;
         break;
     }
     if (!ok)
         return;
     }
     switch(line->special)
     {
       case 24:
     // RAISE FLOOR
     EV_DoFloor(line,raiseFloor);
     P_ChangeSwitchTexture(line,0);
     break;
       case 46:
     // OPEN DOOR
     EV_DoDoor(line,vld_open);
     P_ChangeSwitchTexture(line,1);
     break;
       case 47:
     // RAISE FLOOR NEAR AND CHANGE
     EV_DoPlat(line,raiseToNearestAndChange,0);
     P_ChangeSwitchTexture(line,0);
     break;
     }
 }
References EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), ok, P_ChangeSwitchTexture(), mobj_s::player, raiseFloor, raiseToNearestAndChange, and vld_open.
Referenced by PTR_ShootTraverse().
P_SpawnDoorCloseIn30()
void P_SpawnDoorCloseIn30 (sector_t * sec)
Definition at line 519 of file p_doors.c.
 {
     vldoor_t*   door;
     door = Z_Malloc ( sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     sec->special = 0;
     door->thinker.function.acp1 = (actionf_p1)T_VerticalDoor;
     door->sector = sec;
     door->direction = 0;
     door->type = vld_normal;
     door->speed = VDOORSPEED;
     door->topcountdown = 30 * TICRATE;
 }
References actionf_t::acp1, vldoor_t::direction, thinker_s::function, P_AddThinker(), PU_LEVSPEC, vldoor_t::sector, sector_t::special, sector_t::specialdata, vldoor_t::speed, T_VerticalDoor(), vldoor_t::thinker, TICRATE, vldoor_t::topcountdown, vldoor_t::type, VDOORSPEED, vld_normal, and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnDoorRaiseIn5Mins()
void P_SpawnDoorRaiseIn5Mins (sector_t * sec, int secnum)
Definition at line 542 of file p_doors.c.
 {
     vldoor_t*   door;
     door = Z_Malloc ( sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     sec->special = 0;
     door->thinker.function.acp1 = (actionf_p1)T_VerticalDoor;
     door->sector = sec;
     door->direction = 2;
     door->type = vld_raiseIn5Mins;
     door->speed = VDOORSPEED;
     door->topheight = P_FindLowestCeilingSurrounding(sec);
     door->topheight -= 4*FRACUNIT;
     door->topwait = VDOORWAIT;
     door->topcountdown = 5 * 60 * TICRATE;
 }
References actionf_t::acp1, vldoor_t::direction, FRACUNIT, thinker_s::function, P_AddThinker(), P_FindLowestCeilingSurrounding(), PU_LEVSPEC, vldoor_t::sector, sector_t::special, sector_t::specialdata, vldoor_t::speed, T_VerticalDoor(), vldoor_t::thinker, TICRATE, vldoor_t::topcountdown, vldoor_t::topheight, vldoor_t::topwait, vldoor_t::type, VDOORSPEED, VDOORWAIT, vld_raiseIn5Mins, and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnFireFlicker()
void P_SpawnFireFlicker (sector_t * sector)
Definition at line 61 of file p_lights.c.
 {
     fireflicker_t*  flick;
     // Note that we are resetting sector attributes.
     // Nothing special about it during gameplay.
     sector->special = 0;
     flick = Z_Malloc ( sizeof(*flick), PU_LEVSPEC, 0);
     P_AddThinker (&flick->thinker);
     flick->thinker.function.acp1 = (actionf_p1) T_FireFlicker;
     flick->sector = sector;
     flick->maxlight = sector->lightlevel;
     flick->minlight = P_FindMinSurroundingLight(sector,sector->lightlevel)+16;
     flick->count = 4;
 }
References actionf_t::acp1, fireflicker_t::count, thinker_s::function, fireflicker_t::maxlight, fireflicker_t::minlight, P_AddThinker(), P_FindMinSurroundingLight(), PU_LEVSPEC, sector, fireflicker_t::sector, T_FireFlicker(), fireflicker_t::thinker, and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnGlowingLight()
void P_SpawnGlowingLight (sector_t * sector)
Definition at line 334 of file p_lights.c.
 {
     glow_t* g;
     g = Z_Malloc( sizeof(*g), PU_LEVSPEC, 0);
     P_AddThinker(&g->thinker);
     g->sector = sector;
     g->minlight = P_FindMinSurroundingLight(sector,sector->lightlevel);
     g->maxlight = sector->lightlevel;
     g->thinker.function.acp1 = (actionf_p1) T_Glow;
     g->direction = -1;
     sector->special = 0;
 }
References g, P_AddThinker(), P_FindMinSurroundingLight(), PU_LEVSPEC, sector, T_Glow(), and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnLightFlash()
void P_SpawnLightFlash (sector_t * sector)
Definition at line 117 of file p_lights.c.
 {
     lightflash_t*   flash;
     // nothing special about it during gameplay
     sector->special = 0;
     flash = Z_Malloc ( sizeof(*flash), PU_LEVSPEC, 0);
     P_AddThinker (&flash->thinker);
     flash->thinker.function.acp1 = (actionf_p1) T_LightFlash;
     flash->sector = sector;
     flash->maxlight = sector->lightlevel;
     flash->minlight = P_FindMinSurroundingLight(sector,sector->lightlevel);
     flash->maxtime = 64;
     flash->mintime = 7;
     flash->count = (P_Random()&flash->maxtime)+1;
 }
References flash(), P_AddThinker(), P_FindMinSurroundingLight(), P_Random(), PU_LEVSPEC, sector, T_LightFlash(), and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnSpecials()
void P_SpawnSpecials (void)
Definition at line 1374 of file p_spec.c.
 {
     sector_t*   sector;
     int     i;
     // See if -TIMER was specified.
     if (timelimit > 0 && deathmatch)
     {
         levelTimer = true;
         levelTimeCount = timelimit * 60 * TICRATE;
     }
     else
     {
     levelTimer = false;
     }
     //  Init special SECTORs.
     sector = sectors;
     for (i=0 ; i<numsectors ; i++, sector++)
     {
     if (!sector->special)
         continue;
     switch (sector->special)
     {
       case 1:
         // FLICKERING LIGHTS
         P_SpawnLightFlash (sector);
         break;
       case 2:
         // STROBE FAST
         P_SpawnStrobeFlash(sector,FASTDARK,0);
         break;
       case 3:
         // STROBE SLOW
         P_SpawnStrobeFlash(sector,SLOWDARK,0);
         break;
       case 4:
         // STROBE FAST/DEATH SLIME
         P_SpawnStrobeFlash(sector,FASTDARK,0);
         sector->special = 4;
         break;
       case 8:
         // GLOWING LIGHT
         P_SpawnGlowingLight(sector);
         break;
       case 9:
         // SECRET SECTOR
         totalsecret++;
         break;
       case 10:
         // DOOR CLOSE IN 30 SECONDS
         P_SpawnDoorCloseIn30 (sector);
         break;
       case 12:
         // SYNC STROBE SLOW
         P_SpawnStrobeFlash (sector, SLOWDARK, 1);
         break;
       case 13:
         // SYNC STROBE FAST
         P_SpawnStrobeFlash (sector, FASTDARK, 1);
         break;
       case 14:
         // DOOR RAISE IN 5 MINUTES
         P_SpawnDoorRaiseIn5Mins (sector, i);
         break;
       case 17:
         P_SpawnFireFlicker(sector);
         break;
     }
     }
     //  Init line EFFECTs
     numlinespecials = 0;
     for (i = 0;i < numlines; i++)
     {
     switch(lines[i].special)
     {
       case 48:
             if (numlinespecials >= MAXLINEANIMS)
             {
                 I_Error("Too many scrolling wall linedefs! "
                         "(Vanilla limit is 64)");
             }
         // EFFECT FIRSTCOL SCROLL+
         linespeciallist[numlinespecials] = &lines[i];
         numlinespecials++;
         break;
     }
     }
     //  Init other misc stuff
     for (i = 0;i < MAXCEILINGS;i++)
     activeceilings[i] = NULL;
     for (i = 0;i < MAXPLATS;i++)
     activeplats[i] = NULL;
     for (i = 0;i < MAXBUTTONS;i++)
     memset(&buttonlist[i],0,sizeof(button_t));
     // UNUSED: no horizonal sliders.
     //  P_InitSlidingDoorFrames();
 }
References activeceilings, activeplats, buttonlist, deathmatch, FASTDARK, i, I_Error(), levelTimeCount, levelTimer, lines, linespeciallist, MAXBUTTONS, MAXCEILINGS, MAXLINEANIMS, MAXPLATS, memset, NULL, numlines, numlinespecials, numsectors, P_SpawnDoorCloseIn30(), P_SpawnDoorRaiseIn5Mins(), P_SpawnFireFlicker(), P_SpawnGlowingLight(), P_SpawnLightFlash(), P_SpawnStrobeFlash(), sector, sectors, SLOWDARK, TICRATE, timelimit, and totalsecret.
Referenced by P_SetupLevel().
P_SpawnStrobeFlash()
void P_SpawnStrobeFlash (sector_t * sector, int fastOrSlow, int inSync)
Definition at line 174 of file p_lights.c.
 {
     strobe_t*   flash;
     flash = Z_Malloc ( sizeof(*flash), PU_LEVSPEC, 0);
     P_AddThinker (&flash->thinker);
     flash->sector = sector;
     flash->darktime = fastOrSlow;
     flash->brighttime = STROBEBRIGHT;
     flash->thinker.function.acp1 = (actionf_p1) T_StrobeFlash;
     flash->maxlight = sector->lightlevel;
     flash->minlight = P_FindMinSurroundingLight(sector, sector->lightlevel);
     if (flash->minlight == flash->maxlight)
     flash->minlight = 0;
     // nothing special about it during gameplay
     sector->special = 0;
     if (!inSync)
     flash->count = (P_Random()&7)+1;
     else
     flash->count = 1;
 }
References flash(), P_AddThinker(), P_FindMinSurroundingLight(), P_Random(), PU_LEVSPEC, sector, STROBEBRIGHT, T_StrobeFlash(), and Z_Malloc().
Referenced by EV_StartLightStrobing(), and P_SpawnSpecials().
P_UpdateSpecials()
void P_UpdateSpecials (void)
Definition at line 1093 of file p_spec.c.
 {
     anim_t* anim;
     int     pic;
     int     i;
     line_t* line;
     //  LEVEL TIMER
     if (levelTimer == true)
     {
     levelTimeCount--;
     if (!levelTimeCount)
         G_ExitLevel();
     }
     //  ANIMATE FLATS AND TEXTURES GLOBALLY
     for (anim = anims ; anim < lastanim ; anim++)
     {
     for (i=anim->basepic ; i<anim->basepic+anim->numpics ; i++)
     {
         pic = anim->basepic + ( (leveltime/anim->speed + i)%anim->numpics );
         if (anim->istexture)
         texturetranslation[i] = pic;
         else
         flattranslation[i] = pic;
     }
     }
     //  ANIMATE LINE SPECIALS
     for (i = 0; i < numlinespecials; i++)
     {
     line = linespeciallist[i];
     switch(line->special)
     {
       case 48:
         // EFFECT FIRSTCOL SCROLL +
         sides[line->sidenum[0]].textureoffset += FRACUNIT;
         break;
     }
     }
     //  DO BUTTONS
     for (i = 0; i < MAXBUTTONS; i++)
     if (buttonlist[i].btimer)
     {
         buttonlist[i].btimer--;
         if (!buttonlist[i].btimer)
         {
         switch(buttonlist[i].where)
         {
           case top:
             sides[buttonlist[i].line->sidenum[0]].toptexture =
             buttonlist[i].btexture;
             break;
           case middle:
             sides[buttonlist[i].line->sidenum[0]].midtexture =
             buttonlist[i].btexture;
             break;
           case bottom:
             sides[buttonlist[i].line->sidenum[0]].bottomtexture =
             buttonlist[i].btexture;
             break;
         }
         S_StartSound(&buttonlist[i].soundorg,sfx_swtchn);
         memset(&buttonlist[i],0,sizeof(button_t));
         }
     }
 }
References anims, anim_t::basepic, bottom, side_t::bottomtexture, button_t::btexture, button_t::btimer, buttonlist, flattranslation, FRACUNIT, G_ExitLevel(), i, anim_t::istexture, lastanim, leveltime, levelTimeCount, levelTimer, line, button_t::line, linespeciallist, MAXBUTTONS, memset, middle, side_t::midtexture, numlinespecials, anim_t::numpics, S_StartSound(), sfx_swtchn, line_s::sidenum, sides, anim_t::speed, side_t::textureoffset, texturetranslation, top, and side_t::toptexture.
Referenced by P_Ticker().
P_UseSpecialLine()
boolean P_UseSpecialLine (mobj_t * thing, line_t * line, int side)
Definition at line 270 of file p_switch.c.
 {
     // Err...
     // Use the back sides of VERY SPECIAL lines...
     if (side)
     {
     switch(line->special)
     {
       case 124:
         // Sliding door open&close
         // UNUSED?
         break;
       default:
         return false;
         break;
     }
     }
     // Switches that other things can activate.
     if (!thing->player)
     {
     // never open secret doors
     if (line->flags & ML_SECRET)
         return false;
     switch(line->special)
     {
       case 1:   // MANUAL DOOR RAISE
       case 32:  // MANUAL BLUE
       case 33:  // MANUAL RED
       case 34:  // MANUAL YELLOW
         break;
       default:
         return false;
         break;
     }
     }
     // do something
     switch (line->special)
     {
     // MANUALS
       case 1:       // Vertical Door
       case 26:      // Blue Door/Locked
       case 27:      // Yellow Door /Locked
       case 28:      // Red Door /Locked
       case 31:      // Manual door open
       case 32:      // Blue locked door open
       case 33:      // Red locked door open
       case 34:      // Yellow locked door open
       case 117:     // Blazing door raise
       case 118:     // Blazing door open
     EV_VerticalDoor (line, thing);
     break;
     //UNUSED - Door Slide Open&Close
     // case 124:
     // EV_SlidingDoor (line, thing);
     // break;
     // SWITCHES
       case 7:
     // Build Stairs
     if (EV_BuildStairs(line,build8))
         P_ChangeSwitchTexture(line,0);
     break;
       case 9:
     // Change Donut
     if (EV_DoDonut(line))
         P_ChangeSwitchTexture(line,0);
     break;
       case 11:
     // Exit level
     P_ChangeSwitchTexture(line,0);
     G_ExitLevel ();
     break;
       case 14:
     // Raise Floor 32 and change texture
     if (EV_DoPlat(line,raiseAndChange,32))
         P_ChangeSwitchTexture(line,0);
     break;
       case 15:
     // Raise Floor 24 and change texture
     if (EV_DoPlat(line,raiseAndChange,24))
         P_ChangeSwitchTexture(line,0);
     break;
       case 18:
     // Raise Floor to next highest floor
     if (EV_DoFloor(line, raiseFloorToNearest))
         P_ChangeSwitchTexture(line,0);
     break;
       case 20:
     // Raise Plat next highest floor and change texture
     if (EV_DoPlat(line,raiseToNearestAndChange,0))
         P_ChangeSwitchTexture(line,0);
     break;
       case 21:
     // PlatDownWaitUpStay
     if (EV_DoPlat(line,downWaitUpStay,0))
         P_ChangeSwitchTexture(line,0);
     break;
       case 23:
     // Lower Floor to Lowest
     if (EV_DoFloor(line,lowerFloorToLowest))
         P_ChangeSwitchTexture(line,0);
     break;
       case 29:
     // Raise Door
     if (EV_DoDoor(line,vld_normal))
         P_ChangeSwitchTexture(line,0);
     break;
       case 41:
     // Lower Ceiling to Floor
     if (EV_DoCeiling(line,lowerToFloor))
         P_ChangeSwitchTexture(line,0);
     break;
       case 71:
     // Turbo Lower Floor
     if (EV_DoFloor(line,turboLower))
         P_ChangeSwitchTexture(line,0);
     break;
       case 49:
     // Ceiling Crush And Raise
     if (EV_DoCeiling(line,crushAndRaise))
         P_ChangeSwitchTexture(line,0);
     break;
       case 50:
     // Close Door
     if (EV_DoDoor(line,vld_close))
         P_ChangeSwitchTexture(line,0);
     break;
       case 51:
     // Secret EXIT
     P_ChangeSwitchTexture(line,0);
     G_SecretExitLevel ();
     break;
       case 55:
     // Raise Floor Crush
     if (EV_DoFloor(line,raiseFloorCrush))
         P_ChangeSwitchTexture(line,0);
     break;
       case 101:
     // Raise Floor
     if (EV_DoFloor(line,raiseFloor))
         P_ChangeSwitchTexture(line,0);
     break;
       case 102:
     // Lower Floor to Surrounding floor height
     if (EV_DoFloor(line,lowerFloor))
         P_ChangeSwitchTexture(line,0);
     break;
       case 103:
     // Open Door
     if (EV_DoDoor(line,vld_open))
         P_ChangeSwitchTexture(line,0);
     break;
       case 111:
     // Blazing Door Raise (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeRaise))
         P_ChangeSwitchTexture(line,0);
     break;
       case 112:
     // Blazing Door Open (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeOpen))
         P_ChangeSwitchTexture(line,0);
     break;
       case 113:
     // Blazing Door Close (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeClose))
         P_ChangeSwitchTexture(line,0);
     break;
       case 122:
     // Blazing PlatDownWaitUpStay
     if (EV_DoPlat(line,blazeDWUS,0))
         P_ChangeSwitchTexture(line,0);
     break;
       case 127:
     // Build Stairs Turbo 16
     if (EV_BuildStairs(line,turbo16))
         P_ChangeSwitchTexture(line,0);
     break;
       case 131:
     // Raise Floor Turbo
     if (EV_DoFloor(line,raiseFloorTurbo))
         P_ChangeSwitchTexture(line,0);
     break;
       case 133:
     // BlzOpenDoor BLUE
       case 135:
     // BlzOpenDoor RED
       case 137:
     // BlzOpenDoor YELLOW
     if (EV_DoLockedDoor (line,vld_blazeOpen,thing))
         P_ChangeSwitchTexture(line,0);
     break;
       case 140:
     // Raise Floor 512
     if (EV_DoFloor(line,raiseFloor512))
         P_ChangeSwitchTexture(line,0);
     break;
     // BUTTONS
       case 42:
     // Close Door
     if (EV_DoDoor(line,vld_close))
         P_ChangeSwitchTexture(line,1);
     break;
       case 43:
     // Lower Ceiling to Floor
     if (EV_DoCeiling(line,lowerToFloor))
         P_ChangeSwitchTexture(line,1);
     break;
       case 45:
     // Lower Floor to Surrounding floor height
     if (EV_DoFloor(line,lowerFloor))
         P_ChangeSwitchTexture(line,1);
     break;
       case 60:
     // Lower Floor to Lowest
     if (EV_DoFloor(line,lowerFloorToLowest))
         P_ChangeSwitchTexture(line,1);
     break;
       case 61:
     // Open Door
     if (EV_DoDoor(line,vld_open))
         P_ChangeSwitchTexture(line,1);
     break;
       case 62:
     // PlatDownWaitUpStay
     if (EV_DoPlat(line,downWaitUpStay,1))
         P_ChangeSwitchTexture(line,1);
     break;
       case 63:
     // Raise Door
     if (EV_DoDoor(line,vld_normal))
         P_ChangeSwitchTexture(line,1);
     break;
       case 64:
     // Raise Floor to ceiling
     if (EV_DoFloor(line,raiseFloor))
         P_ChangeSwitchTexture(line,1);
     break;
       case 66:
     // Raise Floor 24 and change texture
     if (EV_DoPlat(line,raiseAndChange,24))
         P_ChangeSwitchTexture(line,1);
     break;
       case 67:
     // Raise Floor 32 and change texture
     if (EV_DoPlat(line,raiseAndChange,32))
         P_ChangeSwitchTexture(line,1);
     break;
       case 65:
     // Raise Floor Crush
     if (EV_DoFloor(line,raiseFloorCrush))
         P_ChangeSwitchTexture(line,1);
     break;
       case 68:
     // Raise Plat to next highest floor and change texture
     if (EV_DoPlat(line,raiseToNearestAndChange,0))
         P_ChangeSwitchTexture(line,1);
     break;
       case 69:
     // Raise Floor to next highest floor
     if (EV_DoFloor(line, raiseFloorToNearest))
         P_ChangeSwitchTexture(line,1);
     break;
       case 70:
     // Turbo Lower Floor
     if (EV_DoFloor(line,turboLower))
         P_ChangeSwitchTexture(line,1);
     break;
       case 114:
     // Blazing Door Raise (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeRaise))
         P_ChangeSwitchTexture(line,1);
     break;
       case 115:
     // Blazing Door Open (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeOpen))
         P_ChangeSwitchTexture(line,1);
     break;
       case 116:
     // Blazing Door Close (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeClose))
         P_ChangeSwitchTexture(line,1);
     break;
       case 123:
     // Blazing PlatDownWaitUpStay
     if (EV_DoPlat(line,blazeDWUS,0))
         P_ChangeSwitchTexture(line,1);
     break;
       case 132:
     // Raise Floor Turbo
     if (EV_DoFloor(line,raiseFloorTurbo))
         P_ChangeSwitchTexture(line,1);
     break;
       case 99:
     // BlzOpenDoor BLUE
       case 134:
     // BlzOpenDoor RED
       case 136:
     // BlzOpenDoor YELLOW
     if (EV_DoLockedDoor (line,vld_blazeOpen,thing))
         P_ChangeSwitchTexture(line,1);
     break;
       case 138:
     // Light Turn On
     EV_LightTurnOn(line,255);
     P_ChangeSwitchTexture(line,1);
     break;
       case 139:
     // Light Turn Off
     EV_LightTurnOn(line,35);
     P_ChangeSwitchTexture(line,1);
     break;
     }
     return true;
 }
References blazeDWUS, build8, crushAndRaise, downWaitUpStay, EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoLockedDoor(), EV_DoPlat(), EV_LightTurnOn(), EV_VerticalDoor(), G_ExitLevel(), G_SecretExitLevel(), lowerFloor, lowerFloorToLowest, lowerToFloor, ML_SECRET, P_ChangeSwitchTexture(), mobj_s::player, raiseAndChange, raiseFloor, raiseFloor512, raiseFloorCrush, raiseFloorToNearest, raiseFloorTurbo, raiseToNearestAndChange, turbo16, turboLower, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_normal, and vld_open.
Referenced by P_Move(), and PTR_UseTraverse().
T_Glow()
void T_Glow (glow_t * g)
Definition at line 307 of file p_lights.c.
 {
     switch(g->direction)
     {
       case -1:
     // DOWN
     g->sector->lightlevel -= GLOWSPEED;
     if (g->sector->lightlevel <= g->minlight)
     {
         g->sector->lightlevel += GLOWSPEED;
         g->direction = 1;
     }
     break;
       case 1:
     // UP
     g->sector->lightlevel += GLOWSPEED;
     if (g->sector->lightlevel >= g->maxlight)
     {
         g->sector->lightlevel -= GLOWSPEED;
         g->direction = -1;
     }
     break;
     }
 }
References g, and GLOWSPEED.
Referenced by P_ArchiveSpecials(), P_SpawnGlowingLight(), and P_UnArchiveSpecials().
T_LightFlash()
void T_LightFlash (lightflash_t * flash)
Definition at line 91 of file p_lights.c.
 {
     if (--flash->count)
     return;
     if (flash->sector->lightlevel == flash->maxlight)
     {
     flash-> sector->lightlevel = flash->minlight;
     flash->count = (P_Random()&flash->mintime)+1;
     }
     else
     {
     flash-> sector->lightlevel = flash->maxlight;
     flash->count = (P_Random()&flash->maxtime)+1;
     }
 }
References flash(), P_Random(), and sector.
Referenced by P_ArchiveSpecials(), P_SpawnLightFlash(), and P_UnArchiveSpecials().
T_MoveCeiling()
void T_MoveCeiling (ceiling_t * ceiling)
Definition at line 45 of file p_ceilng.c.
 {
     result_e    res;
     switch(ceiling->direction)
     {
       case 0:
     // IN STASIS
     break;
       case 1:
     // UP
     res = T_MovePlane(ceiling->sector,
               ceiling->speed,
               ceiling->topheight,
               false,1,ceiling->direction);
     if (!(leveltime&7))
     {
         switch(ceiling->type)
         {
           case silentCrushAndRaise:
         break;
           default:
         S_StartSound(&ceiling->sector->soundorg, sfx_stnmov);
         // ?
         break;
         }
     }
     if (res == pastdest)
     {
         switch(ceiling->type)
         {
           case raiseToHighest:
         P_RemoveActiveCeiling(ceiling);
         break;
           case silentCrushAndRaise:
         S_StartSound(&ceiling->sector->soundorg, sfx_pstop);
           case fastCrushAndRaise:
           case crushAndRaise:
         ceiling->direction = -1;
         break;
           default:
         break;
         }
     }
     break;
       case -1:
     // DOWN
     res = T_MovePlane(ceiling->sector,
               ceiling->speed,
               ceiling->bottomheight,
               ceiling->crush,1,ceiling->direction);
     if (!(leveltime&7))
     {
         switch(ceiling->type)
         {
           case silentCrushAndRaise: break;
           default:
         S_StartSound(&ceiling->sector->soundorg, sfx_stnmov);
         }
     }
     if (res == pastdest)
     {
         switch(ceiling->type)
         {
           case silentCrushAndRaise:
         S_StartSound(&ceiling->sector->soundorg, sfx_pstop);
           case crushAndRaise:
         ceiling->speed = CEILSPEED;
           case fastCrushAndRaise:
         ceiling->direction = 1;
         break;
           case lowerAndCrush:
           case lowerToFloor:
         P_RemoveActiveCeiling(ceiling);
         break;
           default:
         break;
         }
     }
     else // ( res != pastdest )
     {
         if (res == crushed)
         {
         switch(ceiling->type)
         {
           case silentCrushAndRaise:
           case crushAndRaise:
           case lowerAndCrush:
             ceiling->speed = CEILSPEED / 8;
             break;
           default:
             break;
         }
         }
     }
     break;
     }
 }
References ceiling_t::bottomheight, CEILSPEED, ceiling_t::crush, crushAndRaise, crushed, ceiling_t::direction, fastCrushAndRaise, leveltime, lowerAndCrush, lowerToFloor, P_RemoveActiveCeiling(), pastdest, raiseToHighest, S_StartSound(), ceiling_t::sector, sfx_pstop, sfx_stnmov, silentCrushAndRaise, sector_t::soundorg, ceiling_t::speed, T_MovePlane(), ceiling_t::topheight, and ceiling_t::type.
Referenced by EV_DoCeiling(), P_ActivateInStasisCeiling(), P_ArchiveSpecials(), and P_UnArchiveSpecials().
T_MoveFloor()
void T_MoveFloor (floormove_t * floor)
Definition at line 202 of file p_floor.c.
 {
     result_e    res;
     res = T_MovePlane(floor->sector,
               floor->speed,
               floor->floordestheight,
               floor->crush,0,floor->direction);
     if (!(leveltime&7))
     S_StartSound(&floor->sector->soundorg, sfx_stnmov);
     if (res == pastdest)
     {
     floor->sector->specialdata = NULL;
     if (floor->direction == 1)
     {
         switch(floor->type)
         {
           case donutRaise:
         floor->sector->special = floor->newspecial;
         floor->sector->floorpic = floor->texture;
           default:
         break;
         }
     }
     else if (floor->direction == -1)
     {
         switch(floor->type)
         {
           case lowerAndChange:
         floor->sector->special = floor->newspecial;
         floor->sector->floorpic = floor->texture;
           default:
         break;
         }
     }
     P_RemoveThinker(&floor->thinker);
     S_StartSound(&floor->sector->soundorg, sfx_pstop);
     }
 }
References donutRaise, floor, leveltime, lowerAndChange, NULL, P_RemoveThinker(), pastdest, S_StartSound(), sfx_pstop, sfx_stnmov, and T_MovePlane().
Referenced by EV_BuildStairs(), EV_DoDonut(), EV_DoFloor(), P_ArchiveSpecials(), and P_UnArchiveSpecials().
T_MovePlane()
result_e T_MovePlane (sector_t * sector, fixed_t speed, fixed_t dest, boolean crush, int floorOrCeiling, int direction)
Definition at line 42 of file p_floor.c.
 {
     boolean flag;
     fixed_t lastpos;
     switch(floorOrCeiling)
     {
       case 0:
     // FLOOR
     switch(direction)
     {
       case -1:
         // DOWN
         if (sector->floorheight - speed < dest)
         {
         lastpos = sector->floorheight;
         sector->floorheight = dest;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             sector->floorheight =lastpos;
             P_ChangeSector(sector,crush);
             //return crushed;
         }
         return pastdest;
         }
         else
         {
         lastpos = sector->floorheight;
         sector->floorheight -= speed;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             sector->floorheight = lastpos;
             P_ChangeSector(sector,crush);
             return crushed;
         }
         }
         break;
       case 1:
         // UP
         if (sector->floorheight + speed > dest)
         {
         lastpos = sector->floorheight;
         sector->floorheight = dest;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             sector->floorheight = lastpos;
             P_ChangeSector(sector,crush);
             //return crushed;
         }
         return pastdest;
         }
         else
         {
         // COULD GET CRUSHED
         lastpos = sector->floorheight;
         sector->floorheight += speed;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             if (crush == true)
             return crushed;
             sector->floorheight = lastpos;
             P_ChangeSector(sector,crush);
             return crushed;
         }
         }
         break;
     }
     break;
       case 1:
     // CEILING
     switch(direction)
     {
       case -1:
         // DOWN
         if (sector->ceilingheight - speed < dest)
         {
         lastpos = sector->ceilingheight;
         sector->ceilingheight = dest;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             sector->ceilingheight = lastpos;
             P_ChangeSector(sector,crush);
             //return crushed;
         }
         return pastdest;
         }
         else
         {
         // COULD GET CRUSHED
         lastpos = sector->ceilingheight;
         sector->ceilingheight -= speed;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             if (crush == true)
             return crushed;
             sector->ceilingheight = lastpos;
             P_ChangeSector(sector,crush);
             return crushed;
         }
         }
         break;
       case 1:
         // UP
         if (sector->ceilingheight + speed > dest)
         {
         lastpos = sector->ceilingheight;
         sector->ceilingheight = dest;
         flag = P_ChangeSector(sector,crush);
         if (flag == true)
         {
             sector->ceilingheight = lastpos;
             P_ChangeSector(sector,crush);
             //return crushed;
         }
         return pastdest;
         }
         else
         {
         lastpos = sector->ceilingheight;
         sector->ceilingheight += speed;
         flag = P_ChangeSector(sector,crush);
 // UNUSED
 #if 0
         if (flag == true)
         {
             sector->ceilingheight = lastpos;
             P_ChangeSector(sector,crush);
             return crushed;
         }
 #endif
         }
         break;
     }
     break;
     }
     return ok;
 }
References crushed, ok, P_ChangeSector(), pastdest, and sector.
Referenced by T_MoveCeiling(), T_MoveFloor(), T_PlatRaise(), and T_VerticalDoor().
T_PlatRaise()
void T_PlatRaise (plat_t * plat)
Definition at line 45 of file p_plats.c.
 {
     result_e    res;
     switch(plat->status)
     {
       case up:
     res = T_MovePlane(plat->sector,
               plat->speed,
               plat->high,
               plat->crush,0,1);
     if (plat->type == raiseAndChange
         || plat->type == raiseToNearestAndChange)
     {
         if (!(leveltime&7))
         S_StartSound(&plat->sector->soundorg, sfx_stnmov);
     }
     if (res == crushed && (!plat->crush))
     {
         plat->count = plat->wait;
         plat->status = down;
         S_StartSound(&plat->sector->soundorg, sfx_pstart);
     }
     else
     {
         if (res == pastdest)
         {
         plat->count = plat->wait;
         plat->status = waiting;
         S_StartSound(&plat->sector->soundorg, sfx_pstop);
         switch(plat->type)
         {
           case blazeDWUS:
           case downWaitUpStay:
             P_RemoveActivePlat(plat);
             break;
           case raiseAndChange:
           case raiseToNearestAndChange:
             P_RemoveActivePlat(plat);
             break;
           default:
             break;
         }
         }
     }
     break;
       case  down:
     res = T_MovePlane(plat->sector,plat->speed,plat->low,false,0,-1);
     if (res == pastdest)
     {
         plat->count = plat->wait;
         plat->status = waiting;
         S_StartSound(&plat->sector->soundorg,sfx_pstop);
     }
     break;
       case  waiting:
     if (!--plat->count)
     {
         if (plat->sector->floorheight == plat->low)
         plat->status = up;
         else
         plat->status = down;
         S_StartSound(&plat->sector->soundorg,sfx_pstart);
     }
       case  in_stasis:
     break;
     }
 }
References blazeDWUS, plat_t::count, plat_t::crush, crushed, down, downWaitUpStay, sector_t::floorheight, plat_t::high, in_stasis, leveltime, plat_t::low, P_RemoveActivePlat(), pastdest, raiseAndChange, raiseToNearestAndChange, S_StartSound(), plat_t::sector, sfx_pstart, sfx_pstop, sfx_stnmov, sector_t::soundorg, plat_t::speed, plat_t::status, T_MovePlane(), plat_t::type, up, plat_t::wait, and waiting.
Referenced by EV_DoPlat(), EV_VerticalDoor(), P_ActivateInStasis(), P_ArchiveSpecials(), and P_UnArchiveSpecials().
T_StrobeFlash()
void T_StrobeFlash (strobe_t * flash)
Definition at line 148 of file p_lights.c.
 {
     if (--flash->count)
     return;
     if (flash->sector->lightlevel == flash->minlight)
     {
     flash-> sector->lightlevel = flash->maxlight;
     flash->count = flash->brighttime;
     }
     else
     {
     flash-> sector->lightlevel = flash->minlight;
     flash->count =flash->darktime;
     }
 }
References flash(), and sector.
Referenced by P_ArchiveSpecials(), P_SpawnStrobeFlash(), and P_UnArchiveSpecials().
T_VerticalDoor()
void T_VerticalDoor (vldoor_t * door)
Definition at line 57 of file p_doors.c.
 {
     result_e    res;
     switch(door->direction)
     {
       case 0:
     // WAITING
     if (!--door->topcountdown)
     {
         switch(door->type)
         {
           case vld_blazeRaise:
         door->direction = -1; // time to go back down
         S_StartSound(&door->sector->soundorg, sfx_bdcls);
         break;
           case vld_normal:
         door->direction = -1; // time to go back down
         S_StartSound(&door->sector->soundorg, sfx_dorcls);
         break;
           case vld_close30ThenOpen:
         door->direction = 1;
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
           default:
         break;
         }
     }
     break;
       case 2:
     //  INITIAL WAIT
     if (!--door->topcountdown)
     {
         switch(door->type)
         {
           case vld_raiseIn5Mins:
         door->direction = 1;
         door->type = vld_normal;
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
           default:
         break;
         }
     }
     break;
       case -1:
     // DOWN
     res = T_MovePlane(door->sector,
               door->speed,
               door->sector->floorheight,
               false,1,door->direction);
     if (res == pastdest)
     {
         switch(door->type)
         {
           case vld_blazeRaise:
           case vld_blazeClose:
         door->sector->specialdata = NULL;
         P_RemoveThinker (&door->thinker);  // unlink and free
         S_StartSound(&door->sector->soundorg, sfx_bdcls);
         break;
           case vld_normal:
           case vld_close:
         door->sector->specialdata = NULL;
         P_RemoveThinker (&door->thinker);  // unlink and free
         break;
           case vld_close30ThenOpen:
         door->direction = 0;
         door->topcountdown = TICRATE*30;
         break;
           default:
         break;
         }
     }
     else if (res == crushed)
     {
         switch(door->type)
         {
           case vld_blazeClose:
           case vld_close:       // DO NOT GO BACK UP!
         break;
           default:
         door->direction = 1;
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
         }
     }
     break;
       case 1:
     // UP
     res = T_MovePlane(door->sector,
               door->speed,
               door->topheight,
               false,1,door->direction);
     if (res == pastdest)
     {
         switch(door->type)
         {
           case vld_blazeRaise:
           case vld_normal:
         door->direction = 0; // wait at top
         door->topcountdown = door->topwait;
         break;
           case vld_close30ThenOpen:
           case vld_blazeOpen:
           case vld_open:
         door->sector->specialdata = NULL;
         P_RemoveThinker (&door->thinker);  // unlink and free
         break;
           default:
         break;
         }
     }
     break;
     }
 }
References crushed, vldoor_t::direction, sector_t::floorheight, NULL, P_RemoveThinker(), pastdest, S_StartSound(), vldoor_t::sector, sfx_bdcls, sfx_dorcls, sfx_doropn, sector_t::soundorg, sector_t::specialdata, vldoor_t::speed, T_MovePlane(), vldoor_t::thinker, TICRATE, vldoor_t::topcountdown, vldoor_t::topheight, vldoor_t::topwait, vldoor_t::type, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_close30ThenOpen, vld_normal, vld_open, and vld_raiseIn5Mins.
Referenced by EV_DoDoor(), EV_VerticalDoor(), P_ArchiveSpecials(), P_SpawnDoorCloseIn30(), P_SpawnDoorRaiseIn5Mins(), and P_UnArchiveSpecials().
twoSided()
int twoSided (int sector, int line)
Definition at line 234 of file p_spec.c.
 {
     return (sectors[sector].lines[line])->flags & ML_TWOSIDED;
 }
References lines, ML_TWOSIDED, sector, and sectors.
Referenced by EV_DoFloor().
Variable Documentation
activeceilings
ceiling_t* activeceilings[MAXCEILINGS] extern
Definition at line 38 of file p_ceilng.c.
Referenced by EV_CeilingCrushStop(), P_ActivateInStasisCeiling(), P_AddActiveCeiling(), P_ArchiveSpecials(), P_RemoveActiveCeiling(), and P_SpawnSpecials().
activeplats
plat_t* activeplats[MAXPLATS] extern
Definition at line 38 of file p_plats.c.
Referenced by EV_StopPlat(), P_ActivateInStasis(), P_AddActivePlat(), P_RemoveActivePlat(), and P_SpawnSpecials().
buttonlist
button_t buttonlist[MAXBUTTONS] extern
Definition at line 95 of file p_switch.c.
Referenced by P_ChangeSwitchTexture(), P_SpawnSpecials(), P_StartButton(), and P_UpdateSpecials().
levelTimeCount
int levelTimeCount extern
Definition at line 1091 of file p_spec.c.
Referenced by P_SpawnSpecials(), and P_UpdateSpecials().
levelTimer
boolean levelTimer extern
Definition at line 1090 of file p_spec.c.
Referenced by P_SpawnSpecials(), and P_UpdateSpecials().