Fennix Userspace: Userspace/mlibc/tests/posix/realpath.c File Reference
realpath.c File Reference
#include <unistd.h>
#include <sys/stat.h>
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
Macros
#define TEST_BASE "/tmp/mlibc-realpath"
Functions
void prepare ()
void cleanup (int do_assert)
void signal_handler (int sig, siginfo_t *info, void *ctx)
int main ()
Macro Definition Documentation
TEST_BASE
#define TEST_BASE "/tmp/mlibc-realpath"
Definition at line 12 of file realpath.c.
Function Documentation
cleanup()
void cleanup (int do_assert)
Definition at line 24 of file realpath.c.
{
     if (do_assert) {
         assert(!unlink(TEST_BASE "/dir1/rel-link"));
         assert(!unlink(TEST_BASE "/dir1/abs-link"));
         assert(!rmdir(TEST_BASE "/dir2"));
         assert(!rmdir(TEST_BASE "/dir1"));
         assert(!rmdir(TEST_BASE "/"));
     } else {
         unlink(TEST_BASE "/dir1/rel-link");
         unlink(TEST_BASE "/dir1/abs-link");
         rmdir(TEST_BASE "/dir2");
         rmdir(TEST_BASE "/dir1");
         rmdir(TEST_BASE "/");
     }
 }
References assert, rmdir(), TEST_BASE, and unlink().
Referenced by main(), run_test(), signal_handler(), and we_askshell().
main()
int main (void)
Definition at line 56 of file realpath.c.
            {
     char *path;
     struct sigaction sa;
     sigemptyset(&sa.sa_mask);
     sa.sa_sigaction = signal_handler;
     sa.sa_flags = SA_SIGINFO;
     sigaction(SIGABRT, &sa, NULL);
     prepare();
     path = realpath(TEST_BASE "/dir1/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir1"));
     free(path);
     path = realpath(TEST_BASE "/dir1/../dir2", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath(TEST_BASE "/dir1/abs-link/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath(TEST_BASE "/dir1/rel-link/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath(TEST_BASE "/dir1/abs-link/../", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE ""));
     free(path);
     path = realpath(TEST_BASE "/dir1/rel-link/../", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE ""));
     free(path);
     path = realpath(TEST_BASE "/dir1/abs-link/../dir1/abs-link/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath(TEST_BASE "/dir1/rel-link/../dir1/rel-link/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath(TEST_BASE "/dir1/abs-link/../dir1/rel-link/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath(TEST_BASE "/dir1/rel-link/../dir1/abs-link/", NULL);
     assert(path);
     assert(!strcmp(path, TEST_BASE "/dir2"));
     free(path);
     path = realpath("/tmp", NULL);
     assert(path);
     assert(!strcmp(path, "/tmp"));
     free(path);
     path = realpath("/", NULL);
     assert(path);
     assert(!strcmp(path, "/"));
     free(path);
     path = realpath("//", NULL);
     assert(path);
     assert(!strcmp(path, "/"));
     free(path);
     cleanup(1);
 }
References assert, cleanup(), free(), NULL, prepare(), realpath(), sigaction::sa_flags, sigaction::sa_mask, sigaction::sa_sigaction, SA_SIGINFO, SIGABRT, sigaction(), sigemptyset(), signal_handler(), strcmp(), and TEST_BASE.
prepare()
void prepare ()
Definition at line 15 of file realpath.c.
                {
     assert(!mkdir(TEST_BASE "/", S_IRWXU));
     assert(!mkdir(TEST_BASE "/dir1", S_IRWXU));
     assert(!mkdir(TEST_BASE "/dir2", S_IRWXU));
     assert(!symlink(TEST_BASE "/dir2/", TEST_BASE "/dir1/abs-link"));
     assert(!chdir(TEST_BASE "/dir1"));
     assert(!symlink("../dir2/", TEST_BASE "/dir1/rel-link"));
 }
References assert, chdir(), mkdir(), S_IRWXU, symlink(), and TEST_BASE.
Referenced by main(), and pthread_atfork().
signal_handler()
void signal_handler (int sig, siginfo_t * info, void * ctx)
Definition at line 40 of file realpath.c.
{
     (void)sig;
     (void)info;
     (void)ctx;
     cleanup(0);
     struct sigaction sa;
     sigemptyset(&sa.sa_mask);
     sa.sa_handler = SIG_DFL;
     sa.sa_flags = 0;
     sigaction(SIGABRT, &sa, NULL);
     abort();
 }
References abort(), cleanup(), NULL, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SIG_DFL, SIGABRT, sigaction(), and sigemptyset().
Referenced by main().