Fennix: Userspace/apps/base/busybox/libbb/time.c File Reference
time.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC parse_datestr (const char *date_str, struct tm *ptm)
time_t FAST_FUNC validate_tm_time (const char *date_str, struct tm *ptm)
static char * strftime_fmt (char *buf, unsigned len, time_t *tp, const char *fmt)
char *FAST_FUNC strftime_HHMMSS (char *buf, unsigned len, time_t *tp)
char *FAST_FUNC strftime_YYYYMMDDHHMMSS (char *buf, unsigned len, time_t *tp)
unsigned long long FAST_FUNC monotonic_ns (void)
unsigned long long FAST_FUNC monotonic_us (void)
unsigned long long FAST_FUNC monotonic_ms (void)
unsigned FAST_FUNC monotonic_sec (void)
Function Documentation
monotonic_ms()
unsigned long long FAST_FUNC monotonic_ms (void)
Definition at line 350 of file time.c.
 {
     struct timeval tv;
     xgettimeofday(&tv);
     return tv.tv_sec * 1000ULL + tv.tv_usec / 1000;
 }
References timeval::tv_sec, timeval::tv_usec, and xgettimeofday().
Referenced by arpping(), resuse_end(), run_command(), and shell_builtin_read().
monotonic_ns()
unsigned long long FAST_FUNC monotonic_ns (void)
Definition at line 338 of file time.c.
 {
     struct timeval tv;
     xgettimeofday(&tv);
     return tv.tv_sec * 1000000000ULL + tv.tv_usec * 1000;
 }
References timeval::tv_sec, timeval::tv_usec, and xgettimeofday().
monotonic_sec()
unsigned FAST_FUNC monotonic_sec (void)
Definition at line 356 of file time.c.
 {
     return time(NULL);
 }
References NULL, and time().
Referenced by bb_progress_init(), bb_progress_update(), buffer_pread(), ftpd_main(), handle_fd_set(), ifplugd_main(), inetd_main(), init_d6_packet(), init_packet(), isrv_run(), logdir_open(), rotate(), runsvdir_main(), syslogd_main(), timeout_handler(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), xid_add(), and xid_expire().
monotonic_us()
unsigned long long FAST_FUNC monotonic_us (void)
Definition at line 344 of file time.c.
 {
     struct timeval tv;
     xgettimeofday(&tv);
     return tv.tv_sec * 1000000ULL + tv.tv_usec;
 }
References timeval::tv_sec, timeval::tv_usec, and xgettimeofday().
Referenced by common_traceroute_main(), crypt_make_salt(), dd_main(), dd_output_status(), generate_uuid(), makemime_main(), next_random(), parse(), popmaildir_main(), shuffle_lines(), udhcpc6_main(), udhcpc_main(), and wait_for_reply().
parse_datestr()
int FAST_FUNC parse_datestr (const char * date_str, struct tm * ptm)
Definition at line 13 of file time.c.
 {
     char end = '\0';
     time_t t;
 #if ENABLE_DESKTOP
 /*
  * strptime is BIG: ~1k in uclibc, ~10k in glibc
  * We need it for 'month_name d HH:MM:SS YYYY', supported by GNU date,
  * but if we've linked it we might as well use it for everything.
  */
     static const char fmt_str[] ALIGN1 =
         "%R" "\0"               /* HH:MM */
         "%T" "\0"               /* HH:MM:SS */
         "%m.%d-%R" "\0"         /* mm.dd-HH:MM */
         "%m.%d-%T" "\0"         /* mm.dd-HH:MM:SS */
         "%Y.%m.%d-%R" "\0"      /* yyyy.mm.dd-HH:MM */
         "%Y.%m.%d-%T" "\0"      /* yyyy.mm.dd-HH:MM:SS */
         "%b %d %T %Y" "\0"      /* month_name d HH:MM:SS YYYY */
         "%Y-%m-%d %R" "\0"      /* yyyy-mm-dd HH:MM */
         "%Y-%m-%d %T" "\0"      /* yyyy-mm-dd HH:MM:SS */
 # if ENABLE_FEATURE_TIMEZONE
         "%Y-%m-%d %R %z" "\0"   /* yyyy-mm-dd HH:MM TZ */
         "%Y-%m-%d %T %z" "\0"   /* yyyy-mm-dd HH:MM:SS TZ */
 # endif
         "%Y-%m-%d %H" "\0"      /* yyyy-mm-dd HH */
         "%Y-%m-%d" "\0"         /* yyyy-mm-dd */
         /* extra NUL */;
     struct tm save;
     const char *fmt;
     char *endp;
     save = *ptm;
     fmt = fmt_str;
     while (*fmt) {
         endp = strptime(date_str, fmt, ptm);
         if (endp && *endp == '\0') {
 # if ENABLE_FEATURE_TIMEZONE
             if (strchr(fmt, 'z')) {
                 /* we have timezone offset: obtain Unix time_t */
                 ptm->tm_sec -= ptm->tm_gmtoff;
                 ptm->tm_isdst = 0;
                 t = timegm(ptm);
                 if (t == (time_t)-1)
                     break;
                 /* convert Unix time_t to struct tm in user's locale */
                 goto localise;
             }
 # endif
             return 1;
         }
         *ptm = save;
         while (*++fmt)
             continue;
         ++fmt;
     }
 #else
     const char *last_colon = strrchr(date_str, ':');
     if (last_colon != NULL) {
         /* Parse input and assign appropriately to ptm */
         /* HH:MM */
         if (sscanf(date_str, "%u:%u%c",
                     &ptm->tm_hour,
                     &ptm->tm_min,
                     &end) >= 2
         ) {
             /* no adjustments needed */
         } else
         /* mm.dd-HH:MM */
         if (sscanf(date_str, "%u.%u-%u:%u%c",
                     &ptm->tm_mon, &ptm->tm_mday,
                     &ptm->tm_hour, &ptm->tm_min,
                     &end) >= 4
         ) {
             /* Adjust month from 1-12 to 0-11 */
             ptm->tm_mon -= 1;
         } else
         /* yyyy.mm.dd-HH:MM */
         if (sscanf(date_str, "%u.%u.%u-%u:%u%c", &ptm->tm_year,
                     &ptm->tm_mon, &ptm->tm_mday,
                     &ptm->tm_hour, &ptm->tm_min,
                     &end) >= 5
         /* yyyy-mm-dd HH:MM */
          || sscanf(date_str, "%u-%u-%u %u:%u%c", &ptm->tm_year,
                     &ptm->tm_mon, &ptm->tm_mday,
                     &ptm->tm_hour, &ptm->tm_min,
                     &end) >= 5
         ) {
             ptm->tm_year -= 1900; /* Adjust years */
             ptm->tm_mon -= 1; /* Adjust month from 1-12 to 0-11 */
         } else
         {
             bb_error_msg_and_die(bb_msg_invalid_date, date_str);
         }
         if (end == ':') {
             /* xxx:SS */
             if (sscanf(last_colon + 1, "%u%c", &ptm->tm_sec, &end) == 1)
                 end = '\0';
             /* else end != NUL and we error out */
         }
     } else
     if (strchr(date_str, '-')
         /* Why strchr('-') check?
          * sscanf below will trash ptm->tm_year, this breaks
          * if parse_str is "10101010" (iow, "MMddhhmm" form)
          * because we destroy year. Do these sscanf
          * only if we saw a dash in parse_str.
          */
         /* yyyy-mm-dd HH */
      && (sscanf(date_str, "%u-%u-%u %u%c", &ptm->tm_year,
                 &ptm->tm_mon, &ptm->tm_mday,
                 &ptm->tm_hour,
                 &end) >= 4
         /* yyyy-mm-dd */
          || sscanf(date_str, "%u-%u-%u%c", &ptm->tm_year,
                 &ptm->tm_mon, &ptm->tm_mday,
                 &end) >= 3
         )
     ) {
         ptm->tm_year -= 1900; /* Adjust years */
         ptm->tm_mon -= 1; /* Adjust month from 1-12 to 0-11 */
     } else
 #endif /* ENABLE_DESKTOP */
     if (date_str[0] == '@') {
         if (sizeof(t) <= sizeof(long))
             t = bb_strtol(date_str + 1, NULL, 10);
         else /* time_t is 64 bits but longs are smaller */
             t = bb_strtoll(date_str + 1, NULL, 10);
         if (!errno) {
             struct tm *lt;
  IF_FEATURE_TIMEZONE(localise:)
             lt = localtime(&t);
             if (lt) {
                 *ptm = *lt;
                 return 0;
             }
         }
         end = '1';
     } else {
         /* Googled the following on an old date manpage:
          *
          * The canonical representation for setting the date/time is:
          * cc   Century (either 19 or 20)
          * yy   Year in abbreviated form (e.g. 89, 06)
          * mm   Numeric month, a number from 1 to 12
          * dd   Day, a number from 1 to 31
          * HH   Hour, a number from 0 to 23
          * MM   Minutes, a number from 0 to 59
          * .SS  Seconds, a number from 0 to 61 (with leap seconds)
          * Everything but the minutes is optional
          *
          * "touch -t DATETIME" format: [[[[[YY]YY]MM]DD]hh]mm[.ss]
          * Some, but not all, Unix "date DATETIME" commands
          * move [[YY]YY] past minutes mm field (!).
          * Coreutils date does it, and SUS mandates it.
          * (date -s DATETIME does not support this format. lovely!)
          * In bbox, this format is special-cased in date applet
          * (IOW: this function assumes "touch -t" format).
          */
         unsigned cur_year = ptm->tm_year;
         int len = strchrnul(date_str, '.') - date_str;
         /* MM[.SS] */
         if (len == 2 && sscanf(date_str, "%2u%2u%2u%2u""%2u%c" + 12,
                     &ptm->tm_min,
                     &end) >= 1) {
         } else
         /* HHMM[.SS] */
         if (len == 4 && sscanf(date_str, "%2u%2u%2u""%2u%2u%c" + 9,
                     &ptm->tm_hour,
                     &ptm->tm_min,
                     &end) >= 2) {
         } else
         /* ddHHMM[.SS] */
         if (len == 6 && sscanf(date_str, "%2u%2u""%2u%2u%2u%c" + 6,
                     &ptm->tm_mday,
                     &ptm->tm_hour,
                     &ptm->tm_min,
                     &end) >= 3) {
         } else
         /* mmddHHMM[.SS] */
         if (len == 8 && sscanf(date_str, "%2u""%2u%2u%2u%2u%c" + 3,
                     &ptm->tm_mon,
                     &ptm->tm_mday,
                     &ptm->tm_hour,
                     &ptm->tm_min,
                     &end) >= 4) {
             /* Adjust month from 1-12 to 0-11 */
             ptm->tm_mon -= 1;
         } else
         /* yymmddHHMM[.SS] */
         if (len == 10 && sscanf(date_str, "%2u%2u%2u%2u%2u%c",
                     &ptm->tm_year,
                     &ptm->tm_mon,
                     &ptm->tm_mday,
                     &ptm->tm_hour,
                     &ptm->tm_min,
                     &end) >= 5) {
             /* Adjust month from 1-12 to 0-11 */
             ptm->tm_mon -= 1;
             if ((int)cur_year >= 50) { /* >= 1950 */
                 /* Adjust year: */
                 /* 1. Put it in the current century */
                 ptm->tm_year += (cur_year / 100) * 100;
                 /* 2. If too far in the past, +100 years */
                 if (ptm->tm_year < cur_year - 50)
                     ptm->tm_year += 100;
                 /* 3. If too far in the future, -100 years */
                 if (ptm->tm_year > cur_year + 50)
                     ptm->tm_year -= 100;
             }
         } else
         /* ccyymmddHHMM[.SS] */
         if (len == 12 && sscanf(date_str, "%4u%2u%2u%2u%2u%c",
                     &ptm->tm_year,
                     &ptm->tm_mon,
                     &ptm->tm_mday,
                     &ptm->tm_hour,
                     &ptm->tm_min,
                     &end) >= 5) {
             ptm->tm_year -= 1900; /* Adjust years */
             ptm->tm_mon -= 1; /* Adjust month from 1-12 to 0-11 */
         } else {
  err:
             bb_error_msg_and_die(bb_msg_invalid_date, date_str);
         }
         ptm->tm_sec = 0; /* assume zero if [.SS] is not given */
         if (end == '.') {
             /* xxx.SS */
             if (sscanf(strchr(date_str, '.') + 1, "%u%c",
                     &ptm->tm_sec, &end) == 1)
                 end = '\0';
             /* else end != NUL and we error out */
         }
         /* Users were confused by "date -s 20180923"
          * working (not in the way they were expecting).
          * It was interpreted as MMDDhhmm, and not bothered by
          * "month #20" in the least. Prevent such cases:
          */
         if (ptm->tm_sec > 60 /* allow "23:60" leap second */
          || ptm->tm_min > 59
          || ptm->tm_hour > 23
          || ptm->tm_mday > 31
          || ptm->tm_mon > 11 /* month# is 0..11, not 1..12 */
         ) {
             goto err;
         }
     }
     if (end != '\0') {
         bb_error_msg_and_die(bb_msg_invalid_date, date_str);
     }
     return 1;
 }
References ALIGN1, bb_error_msg_and_die(), bb_strtol(), bb_strtoll(), date_str, end, err(), errno, fmt_str(), len, localtime(), NULL, sscanf(), strchr(), strchrnul(), strptime(), strrchr(), t, timegm(), tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, and tm::tm_year.
Referenced by date_main(), and touch_main().
strftime_fmt()
static char* strftime_fmt (char * buf, unsigned len, time_t * tp, const char * fmt) static
Definition at line 277 of file time.c.
 {
     time_t t;
     if (!tp) {
         tp = &t;
         time(tp);
     }
     /* Returns pointer to NUL */
     return buf + strftime(buf, len, fmt, localtime(tp));
 }
References buf, len, localtime(), strftime(), t, time(), and tp.
Referenced by strftime_HHMMSS(), and strftime_YYYYMMDDHHMMSS().
strftime_HHMMSS()
char* FAST_FUNC strftime_HHMMSS (char * buf, unsigned len, time_t * tp)
Definition at line 288 of file time.c.
 {
     return strftime_fmt(buf, len, tp, "%H:%M:%S");
 }
References buf, len, strftime_fmt(), and tp.
Referenced by curtime(), and print_login_issue().
strftime_YYYYMMDDHHMMSS()
char* FAST_FUNC strftime_YYYYMMDDHHMMSS (char * buf, unsigned len, time_t * tp)
Definition at line 293 of file time.c.
 {
     return strftime_fmt(buf, len, tp, "%Y-%m-%d %H:%M:%S");
 }
References buf, len, strftime_fmt(), and tp.
Referenced by step_time(), and watch_main().
validate_tm_time()
time_t FAST_FUNC validate_tm_time (const char * date_str, struct tm * ptm)
Definition at line 268 of file time.c.
 {
     time_t t = mktime(ptm);
     if (t == (time_t) -1L) {
         bb_error_msg_and_die(bb_msg_invalid_date, date_str);
     }
     return t;
 }
References bb_error_msg_and_die(), date_str, mktime(), and t.
Referenced by date_main(), and touch_main().