Fennix: Userspace/apps/base/busybox/coreutils/mknod.c File Reference
mknod.c File Reference
#include "libbb.h"
#include "libcoreutils/coreutils.h"
Functions
int mknod_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char modes_chars[] ALIGN1 = { 'p', 'c', 'u', 'b', 0, 1, 1, 2 }
static const mode_t modes_cubp [] = { S_IFIFO, S_IFCHR, S_IFBLK }
Function Documentation
mknod_main()
int mknod_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 52 of file mknod.c.
 {
     mode_t mode;
     dev_t dev;
     const char *type, *arg;
     mode = getopt_mk_fifo_nod(argv);
     argv += optind;
     //argc -= optind;
     if (!argv[0] || !argv[1])
         bb_show_usage();
     type = strchr(modes_chars, argv[1][0]);
     if (!type)
         bb_show_usage();
     mode |= modes_cubp[(int)(type[4])];
     dev = 0;
     arg = argv[2];
     if (*type != 'p') {
         if (!argv[2] || !argv[3])
             bb_show_usage();
         /* Autodetect what the system supports; these macros should
          * optimize out to two constants. */
         dev = makedev(xatoul_range(argv[2], 0, major(UINT_MAX)),
                 xatoul_range(argv[3], 0, minor(UINT_MAX)));
         arg = argv[4];
     }
     if (arg)
         bb_show_usage();
     if (mknod(argv[0], mode, dev) != 0) {
         bb_simple_perror_msg_and_die(argv[0]);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_show_usage(), bb_simple_perror_msg_and_die(), EXIT_SUCCESS, getopt_mk_fifo_nod(), major, makedev, minor, mknod(), modes_cubp, optind, strchr(), type, and UINT_MAX.
Variable Documentation
ALIGN1
const char modes_chars [] ALIGN1 = { 'p', 'c', 'u', 'b', 0, 1, 1, 2 } static
Definition at line 48 of file mknod.c.
modes_cubp
const mode_t modes_cubp[] = { S_IFIFO, S_IFCHR, S_IFBLK } static
Definition at line 49 of file mknod.c.
Referenced by mknod_main().