Fennix: Userspace/musl/include/ftw.h File Reference
ftw.h File Reference
#include <features.h>
#include <sys/stat.h>
Data Structures
struct FTW
Macros
#define FTW_F 1
#define FTW_D 2
#define FTW_DNR 3
#define FTW_NS 4
#define FTW_SL 5
#define FTW_DP 6
#define FTW_SLN 7
#define FTW_PHYS 1
#define FTW_MOUNT 2
#define FTW_CHDIR 4
#define FTW_DEPTH 8
Functions
int ftw (const char *, int(*)(const char *, const struct stat *, int), int)
int nftw (const char *, int(*)(const char *, const struct stat *, int, struct FTW *), int, int)
Data Structure Documentation
FTW
struct FTW
Definition at line 24 of file ftw.h.
Data Fields
int base
int level
Macro Definition Documentation
FTW_CHDIR
#define FTW_CHDIR 4
Definition at line 21 of file ftw.h.
FTW_D
#define FTW_D 2
Definition at line 12 of file ftw.h.
FTW_DEPTH
#define FTW_DEPTH 8
Definition at line 22 of file ftw.h.
FTW_DNR
#define FTW_DNR 3
Definition at line 13 of file ftw.h.
FTW_DP
#define FTW_DP 6
Definition at line 16 of file ftw.h.
FTW_F
#define FTW_F 1
Definition at line 11 of file ftw.h.
FTW_MOUNT
#define FTW_MOUNT 2
Definition at line 20 of file ftw.h.
FTW_NS
#define FTW_NS 4
Definition at line 14 of file ftw.h.
FTW_PHYS
#define FTW_PHYS 1
Definition at line 19 of file ftw.h.
FTW_SL
#define FTW_SL 5
Definition at line 15 of file ftw.h.
FTW_SLN
#define FTW_SLN 7
Definition at line 17 of file ftw.h.
Function Documentation
ftw()
int ftw (const char * path, int(*)(const char *, const struct stat *, int) fn, int fd_limit)
Definition at line 3 of file ftw.c.
 {
     /* The following cast assumes that calling a function with one
      * argument more than it needs behaves as expected. This is
      * actually undefined, but works on all real-world machines. */
     return nftw(path, (int (*)())fn, fd_limit, FTW_PHYS);
 }
References FTW_PHYS, and nftw().
nftw()
int nftw (const char * path, int(*)(const char *, const struct stat *, int, struct FTW *) fn, int fd_limit, int flags)
Definition at line 123 of file nftw.c.
 {
     int r, cs;
     size_t l;
     char pathbuf[PATH_MAX+1];
     if (fd_limit <= 0) return 0;
     l = strlen(path);
     if (l > PATH_MAX) {
         errno = ENAMETOOLONG;
         return -1;
     }
     memcpy(pathbuf, path, l+1);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     r = do_nftw(pathbuf, fn, fd_limit, flags, NULL);
     pthread_setcancelstate(cs, 0);
     return r;
 }
References do_nftw(), ENAMETOOLONG, errno, flags, l, memcpy, NULL, PATH_MAX, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and strlen().
Referenced by ftw().