Fennix Userspace: Userspace/musl/src/math/copysignf.c File Reference
copysignf.c File Reference
#include <math.h>
#include <stdint.h>
Functions
float copysignf (float x, float y)
Function Documentation
copysignf()
float copysignf (float x, float y)
Definition at line 4 of file copysignf.c.
 {
     union {float f; uint32_t i;} ux={x}, uy={y};
     ux.i &= 0x7fffffff;
     ux.i |= uy.i & 0x80000000;
     return ux.f;
 }
References f, i, x, and y.
Referenced by ccoshf(), cprojf(), csinhf(), csqrtf(), and ctanhf().