Fennix Userspace: Userspace/apps/base/busybox/util-linux/freeramdisk.c File Reference
freeramdisk.c File Reference
#include <sys/mount.h>
#include "libbb.h"
Macros
#define FDFLUSH _IO(2,0x4b)
Functions
int freeramdisk_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
FDFLUSH
#define FDFLUSH _IO(2,0x4b)
Definition at line 58 of file freeramdisk.c.
Function Documentation
freeramdisk_main()
int freeramdisk_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 61 of file freeramdisk.c.
 {
     int fd;
     fd = xopen(single_argv(argv), O_RDWR);
     // Act like freeramdisk, fdflush, or both depending on configuration.
     ioctl_or_perror_and_die(fd,
         ((ENABLE_FREERAMDISK && applet_name[1] == 'r') || !ENABLE_FDFLUSH)
                 ? BLKFLSBUF
                 : FDFLUSH,
         NULL, "%s", argv[1]
     );
     if (ENABLE_FEATURE_CLEAN_UP) close(fd);
     return EXIT_SUCCESS;
 }
References applet_name, argv, BLKFLSBUF, close(), EXIT_SUCCESS, fd, FDFLUSH, ioctl_or_perror_and_die(), NULL, O_RDWR, single_argv(), and xopen().