Fennix: Userspace/apps/base/bash/lib/sh/zgetline.c File Reference
zgetline.c File Reference
#include <config.h>
#include <sys/types.h>
#include <errno.h>
#include "xmalloc.h"
Macros
#define GET_LINE_INITIAL_ALLOCATION 16
Typedefs
typedef ssize_t breadfunc_t PARAMS((int, char *, size_t))
Functions
ssize_t zreadc PARAMS ((int, char *))
ssize_t zgetline (int fd, char **lineptr, size_t *n, int delim, int unbuffered_read)
Variables
int errno
Macro Definition Documentation
GET_LINE_INITIAL_ALLOCATION
#define GET_LINE_INITIAL_ALLOCATION 16
Definition at line 46 of file zgetline.c.
Typedef Documentation
PARAMS
typedef ssize_t creadfunc_t PARAMS((int, char *))
Definition at line 42 of file zgetline.c.
Function Documentation
PARAMS()
ssize_t zreadc PARAMS ((int, char *))
zgetline()
ssize_t zgetline (int fd, char ** lineptr, size_t * n, int delim, int unbuffered_read)
Definition at line 64 of file zgetline.c.
 {
   int retval;
   size_t nr;
   char *line, c;
   if (lineptr == 0 || n == 0 || (*lineptr == 0 && *n != 0))
     return -1;
   nr = 0;
   line = *lineptr;
   while (1)
     {
       retval = unbuffered_read ? zread (fd, &c, 1) : zreadc(fd, &c);
       if (retval <= 0)
     {
       if (line && nr > 0)
         line[nr] = '\0';
       break;
     }
       if (nr + 2 >= *n)
     {
       size_t new_size;
       new_size = (*n == 0) ? GET_LINE_INITIAL_ALLOCATION : *n * 2;
       line = (*n >= new_size) ? NULL : xrealloc (*lineptr, new_size);
       if (line)
         {
           *lineptr = line;
           *n = new_size;
         }
       else
         {
           if (*n > 0)
         {
           (*lineptr)[*n - 1] = '\0';
           nr = *n - 2;
         }
           break;
         }
     }
       line[nr] = c;
       nr++;
       if (c == delim)
     {
       line[nr] = '\0';
       break;
     }
     }
   return nr - 1;
 }
References c, fd, GET_LINE_INITIAL_ALLOCATION, line, n, NULL, retval, xrealloc, zread(), and zreadc().
Referenced by cutfile().
Variable Documentation
errno
int errno extern