Fennix: Userspace/musl/src/unistd/read.c File Reference
read.c File Reference
#include <unistd.h>
#include "syscall.h"
Functions
ssize_t read (int fd, void *buf, size_t count)
Function Documentation
read()
ssize_t read (int fd, void * buf, size_t count)
Definition at line 4 of file read.c.
 {
     return syscall_cp(SYS_read, fd, buf, count);
 }
References buf, count, fd, and syscall_cp.
Referenced by _evalfile(), _nl_load_domain(), _rl_read_file(), back_lines(), bb_ask_noecho(), con_escape(), conspy_main(), dialog_textbox(), do_check(), do_io_until_eof_and_exit(), do_servicing(), do_syslogd(), eventfd_read(), exec_conf(), expbackq(), extract_info(), fcopy(), forkpty(), get_bits(), get_header_ar(), get_line(), get_logname(), get_rawline(), getc_with_restart(), getpass(), getrandom(), gobble_line(), history_truncate_file(), io_thread_func(), klogd_read(), map_library(), mkfs_vfat_main(), mmap_fixed(), open_shell_script(), posix_spawn(), pthread_getname_np(), read_byte(), read_history_range(), read_key(), read_loop(), read_tables(), read_to_buf(), readfile_z(), readwrite(), rl_gather_tyi(), rl_getc(), runsv_main(), runsvdir_main(), safe_read(), shell_builtin_read(), showkey_main(), tee_builtin(), unshare_main(), vswscanf(), zread(), zreadintr(), and zreadretry().