Fennix Kernel: Kernel/FileSystem/Mounts/Random.cpp File Reference
Random.cpp File Reference
#include <filesystem.hpp>
#include <rand.hpp>
#include <errno.h>
#include "../../kernel.h"
Functions
ReadFSFunction (Random_Read)
ReadFSFunction (Random_Write)
void Init_Random (Virtual *vfs_ctx)
Variables
FileSystemOperations random_op
Function Documentation
Init_Random()
void Init_Random (Virtual * vfs_ctx)
Definition at line 48 of file Random.cpp.
 {
     Node *n = vfs_ctx->Create("random", CHARDEVICE, DevFS);
     n->Operator = &random_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, VirtualFileSystem::Node::Operator, and random_op.
Referenced by Main().
ReadFSFunction() [1/2]
ReadFSFunction (Random_Read)
Definition at line 26 of file Random.cpp.
 {
     if (Size <= 0)
         return 0;
     uint64_t *buf = (uint64_t *)Buffer;
     for (size_t i = 0; i < Size / sizeof(uint64_t); i++)
         buf[i] = Random::rand64();
     return Size;
 }
References Random::rand64(), and Size.
ReadFSFunction() [2/2]
ReadFSFunction (Random_Write)
Definition at line 37 of file Random.cpp.
 {
     return Size;
 }
References Size.
Variable Documentation
random_op
FileSystemOperations random_op
Initial value:
= {
    .Name = "Random",
    .Read = Random_Read,
    .Write = Random_Write,
}
Definition at line 42 of file Random.cpp.
Referenced by Init_Random().