Fennix Userspace: Userspace/mlibc/options/linux/generic/sys-prctl-stubs.cpp File Reference
sys-prctl-stubs.cpp File Reference
#include <stdarg.h>
#include <errno.h>
#include <bits/ensure.h>
#include <sys/prctl.h>
#include <mlibc/debug.hpp>
#include "mlibc/linux-sysdeps.hpp"
Functions
int prctl (int op,...)
Function Documentation
prctl()
int prctl (int op, ...)
Definition at line 11 of file sys-prctl-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_prctl, -1);
     int val;
     va_list ap;
     va_start(ap, op);
     if(int e = mlibc::sys_prctl(op, ap, &val); e) {
         errno = e;
         return -1;
     }
     va_end(ap);
     return val;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_prctl(), va_end(), and va_start().