Fennix Lynx Bootloader: Lynx/UEFI/src/cxxabi.cpp File Reference
cxxabi.cpp File Reference
Data Structures
struct atexit_func_entry_t
struct _Unwind_Exception
Macros
#define LYNX_CXXABI_TYPES_H
#define NULL ((void *)0)
#define ALIGN_UP(x, align) ((__typeof__(x))(((uint64_t)(x) + ((align)-1)) & (~((align)-1))))
#define ALIGN_DOWN(x, align) ((__typeof__(x))((x) & (~((align)-1))))
#define ATEXIT_MAX_FUNCS 128
Typedefs
typedef __UINT8_TYPE__ uint8_t
typedef __UINT16_TYPE__ uint16_t
typedef __UINT32_TYPE__ uint32_t
typedef __UINT64_TYPE__ uint64_t
typedef __SIZE_TYPE__ size_t
typedef __UINTPTR_TYPE__ uintptr_t
typedef unsigned uarch_t
typedef unsigned _Unwind_Exception_Class __attribute__((__mode__(__DI__)))
typedef void(* _Unwind_Exception_Cleanup_Fn) (_Unwind_Reason_Code, struct _Unwind_Exception *)
typedef int _Unwind_Action
Enumerations
enum _Unwind_Reason_Code {
_URC_NO_REASON = 0 , _URC_FOREIGN_EXCEPTION_CAUGHT = 1 , _URC_FATAL_PHASE2_ERROR = 2 , _URC_FATAL_PHASE1_ERROR = 3 ,
_URC_NORMAL_STOP = 4 , _URC_END_OF_STACK = 5 , _URC_HANDLER_FOUND = 6 , _URC_INSTALL_CONTEXT = 7 ,
_URC_CONTINUE_UNWIND = 8
}
Functions
void printf (const char *format,...)
struct _Unwind_Exception __attribute__ ((__aligned__))
int __cxa_atexit (void(*f)(void *), void *objptr, void *dso)
void __cxa_finalize (void *f)
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception *ue_header, _Unwind_Context *context)
void _Unwind_Resume (struct _Unwind_Exception *exc)
void * __cxa_allocate_exception (uint64_t thrown_size) throw ()
void __cxa_throw (void *thrown_object, void *tinfo, void(*dest)(void *))
void __cxa_rethrow ()
void __cxa_pure_virtual ()
void __cxa_throw_bad_array_new_length ()
void __cxa_free_exception (void *thrown_exception)
void * __cxa_begin_catch (void *e)
void __cxa_end_catch ()
__extension__ typedef int __guard __attribute__ ((mode(__DI__)))
int __cxa_guard_acquire (__guard *g)
void __cxa_guard_release (__guard *g)
void __cxa_guard_abort (__guard *g)
Variables
_Unwind_Exception_Class exception_class
_Unwind_Exception_Cleanup_Fn exception_cleanup
_Unwind_Word private_1
_Unwind_Word private_2
void * __dso_handle = 0
atexit_func_entry_t __atexit_funcs [ATEXIT_MAX_FUNCS]
uarch_t __atexit_func_count = 0
Data Structure Documentation
_Unwind_Exception
struct _Unwind_Exception
Definition at line 58 of file cxxabi.cpp.
Data Fields
_Unwind_Exception_Class exception_class
_Unwind_Exception_Cleanup_Fn exception_cleanup
_Unwind_Word private_1
_Unwind_Word private_2
Macro Definition Documentation
ALIGN_DOWN
#define ALIGN_DOWN (x, align) ((__typeof__(x))((x) & (~((align)-1))))
Definition at line 15 of file cxxabi.cpp.
ALIGN_UP
#define ALIGN_UP (x, align) ((__typeof__(x))(((uint64_t)(x) + ((align)-1)) & (~((align)-1))))
Definition at line 14 of file cxxabi.cpp.
ATEXIT_MAX_FUNCS
#define ATEXIT_MAX_FUNCS 128
Definition at line 24 of file cxxabi.cpp.
LYNX_CXXABI_TYPES_H
#define LYNX_CXXABI_TYPES_H
Definition at line 2 of file cxxabi.cpp.
NULL
#define NULL ((void *)0)
Definition at line 11 of file cxxabi.cpp.
Typedef Documentation
__attribute__
typedef unsigned _Unwind_Word __attribute__((__mode__(__unwind_word__)))
Definition at line 53 of file cxxabi.cpp.
_Unwind_Action
typedef int _Unwind_Action
Definition at line 56 of file cxxabi.cpp.
_Unwind_Exception_Cleanup_Fn
typedef void(* _Unwind_Exception_Cleanup_Fn) (_Unwind_Reason_Code, struct _Unwind_Exception *)
Definition at line 55 of file cxxabi.cpp.
size_t
typedef __SIZE_TYPE__ size_t
Definition at line 8 of file cxxabi.cpp.
uarch_t
typedef unsigned uarch_t
Definition at line 26 of file cxxabi.cpp.
uint16_t
typedef __UINT16_TYPE__ uint16_t
Definition at line 5 of file cxxabi.cpp.
uint32_t
typedef __UINT32_TYPE__ uint32_t
Definition at line 6 of file cxxabi.cpp.
uint64_t
typedef __UINT64_TYPE__ uint64_t
Definition at line 7 of file cxxabi.cpp.
uint8_t
typedef __UINT8_TYPE__ uint8_t
Definition at line 4 of file cxxabi.cpp.
uintptr_t
typedef __UINTPTR_TYPE__ uintptr_t
Definition at line 9 of file cxxabi.cpp.
Enumeration Type Documentation
_Unwind_Reason_Code
enum _Unwind_Reason_Code
Enumerator
_URC_NO_REASON
_URC_FOREIGN_EXCEPTION_CAUGHT
_URC_FATAL_PHASE2_ERROR
_URC_FATAL_PHASE1_ERROR
_URC_NORMAL_STOP
_URC_END_OF_STACK
_URC_HANDLER_FOUND
_URC_INSTALL_CONTEXT
_URC_CONTINUE_UNWIND
Definition at line 39 of file cxxabi.cpp.
 {
     _URC_NO_REASON = 0,
     _URC_FOREIGN_EXCEPTION_CAUGHT = 1,
     _URC_FATAL_PHASE2_ERROR = 2,
     _URC_FATAL_PHASE1_ERROR = 3,
     _URC_NORMAL_STOP = 4,
     _URC_END_OF_STACK = 5,
     _URC_HANDLER_FOUND = 6,
     _URC_INSTALL_CONTEXT = 7,
     _URC_CONTINUE_UNWIND = 8
 } _Unwind_Reason_Code;
Function Documentation
__attribute__() [1/2]
struct _Unwind_Exception __attribute__ ((__aligned__))
__attribute__() [2/2]
__extension__ typedef int __guard __attribute__ ((mode(__DI__)))
__cxa_allocate_exception()
void* __cxa_allocate_exception (uint64_t thrown_size) throw ()
Definition at line 115 of file cxxabi.cpp.
 {
     printf("__cxa_allocate_exception( %#llu ) triggered.", thrown_size);
     return (void *)0;
 }
References printf().
__cxa_atexit()
int __cxa_atexit (void(*)(void *) f, void * objptr, void * dso)
Definition at line 74 of file cxxabi.cpp.
 {
     printf("__cxa_atexit( %p %p %p ) triggered.", f, objptr, dso);
     if (__atexit_func_count >= ATEXIT_MAX_FUNCS)
         return -1;
     __atexit_funcs[__atexit_func_count].destructor_func = f;
     __atexit_funcs[__atexit_func_count].obj_ptr = objptr;
     __atexit_funcs[__atexit_func_count].dso_handle = dso;
     __atexit_func_count++;
     return 0;
 }
References __atexit_func_count, __atexit_funcs, ATEXIT_MAX_FUNCS, atexit_func_entry_t::destructor_func, atexit_func_entry_t::dso_handle, atexit_func_entry_t::obj_ptr, and printf().
__cxa_begin_catch()
void* __cxa_begin_catch (void * e)
Definition at line 134 of file cxxabi.cpp.
 {
     printf("__cxa_begin_catch( %p ) triggered.", e);
     return (void *)0;
 }
References printf().
__cxa_end_catch()
void __cxa_end_catch ()
Definition at line 141 of file cxxabi.cpp.
 { printf("__cxa_end_catch() triggered."); }
References printf().
__cxa_finalize()
void __cxa_finalize (void * f)
Definition at line 86 of file cxxabi.cpp.
 {
     printf("__cxa_finalize( %p ) triggered.", f);
     uarch_t i = __atexit_func_count;
     if (!f)
     {
         while (i--)
             if (__atexit_funcs[i].destructor_func)
                 (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
         return;
     }
     while (i--)
         if (__atexit_funcs[i].destructor_func == f)
         {
             (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
             __atexit_funcs[i].destructor_func = 0;
         }
 }
References __atexit_func_count, __atexit_funcs, atexit_func_entry_t::destructor_func, and printf().
__cxa_free_exception()
void __cxa_free_exception (void * thrown_exception)
Definition at line 129 of file cxxabi.cpp.
 { printf("__cxa_free_exception( %p ) triggered.", thrown_exception); }
References printf().
__cxa_guard_abort()
void __cxa_guard_abort (__guard * g)
Definition at line 157 of file cxxabi.cpp.
 { printf("__cxa_guard_abort( %p ) triggered.", g); }
References printf().
__cxa_guard_acquire()
int __cxa_guard_acquire (__guard * g)
Definition at line 145 of file cxxabi.cpp.
 {
     printf("__cxa_guard_acquire( %p ) triggered.", g);
     return !*(char *)(g);
 }
References printf().
__cxa_guard_release()
void __cxa_guard_release (__guard * g)
Definition at line 151 of file cxxabi.cpp.
 {
     printf("__cxa_guard_release( %p ) triggered.", g);
     *(char *)g = 1;
 }
References printf().
__cxa_pure_virtual()
void __cxa_pure_virtual ()
Definition at line 125 of file cxxabi.cpp.
 { printf("__cxa_pure_virtual() triggered."); }
References printf().
__cxa_rethrow()
void __cxa_rethrow ()
Definition at line 123 of file cxxabi.cpp.
 { printf("__cxa_rethrow() triggered."); }
References printf().
__cxa_throw()
void __cxa_throw (void * thrown_object, void * tinfo, void(*)(void *) dest)
Definition at line 121 of file cxxabi.cpp.
 { printf("__cxa_throw( %p %p %p ) triggered.", thrown_object, tinfo, dest); }
References printf().
__cxa_throw_bad_array_new_length()
void __cxa_throw_bad_array_new_length ()
Definition at line 127 of file cxxabi.cpp.
 { printf("__cxa_throw_bad_array_new_length() triggered."); }
References printf().
__gxx_personality_v0()
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception * ue_header, _Unwind_Context * context)
Definition at line 107 of file cxxabi.cpp.
 {
     printf("__gxx_personality_v0( %d %p %p %p %p ) triggered.", version, actions, exception_class, ue_header, context);
     return _URC_NO_REASON;
 }
References _URC_NO_REASON, exception_class, and printf().
_Unwind_Resume()
void _Unwind_Resume (struct _Unwind_Exception * exc)
Definition at line 113 of file cxxabi.cpp.
 { printf("_Unwind_Resume( %p ) triggered.", exc); }
References printf().
printf()
void printf (const char * format, ...)
Definition at line 53 of file Lynx.c.
 {
     va_list args;
     va_start(args, format);
     printf_(format, args);
     va_end(args);
 }
References printf_().
Referenced by __cxa_allocate_exception(), __cxa_atexit(), __cxa_begin_catch(), __cxa_end_catch(), __cxa_finalize(), __cxa_free_exception(), __cxa_guard_abort(), __cxa_guard_acquire(), __cxa_guard_release(), __cxa_pure_virtual(), __cxa_rethrow(), __cxa_throw(), __cxa_throw_bad_array_new_length(), __gxx_personality_v0(), and _Unwind_Resume().
Variable Documentation
__atexit_func_count
uarch_t __atexit_func_count = 0
Definition at line 72 of file cxxabi.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__atexit_funcs
atexit_func_entry_t __atexit_funcs[ATEXIT_MAX_FUNCS]
Definition at line 71 of file cxxabi.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__dso_handle
void* __dso_handle = 0 extern
exception_class
_Unwind_Exception_Class exception_class
Definition at line 0 of file cxxabi.cpp.
Referenced by __gxx_personality_v0().
exception_cleanup
_Unwind_Exception_Cleanup_Fn exception_cleanup
Definition at line 1 of file cxxabi.cpp.
private_1
_Unwind_Word private_1
Definition at line 5 of file cxxabi.cpp.
private_2
_Unwind_Word private_2
Definition at line 6 of file cxxabi.cpp.