Fennix Kernel: Kernel/Core/StackGuard.cpp File Reference
StackGuard.cpp File Reference
#include <types.h>
#include <debug.h>
#include <rand.hpp>
#include "../kernel.h"
Functions
__attribute__ ((weak)) uintptr_t __stack_chk_guard=0
EXTERNC __attribute__ ((weak, no_stack_protector)) uintptr_t __stack_chk_guard_init(void)
EXTERNC __attribute__ ((constructor, no_stack_protector)) void __guard_setup(void)
EXTERNC __attribute__ ((weak, noreturn, no_stack_protector)) void __stack_chk_fail(void)
Function Documentation
__attribute__() [1/4]
EXTERNC __attribute__ ((constructor, no_stack_protector))
Definition at line 30 of file StackGuard.cpp.
 {
     debug("StackGuard: __guard_setup");
     if (__stack_chk_guard == 0)
         __stack_chk_guard = __stack_chk_guard_init();
     debug("Stack guard value: %ld", __stack_chk_guard);
 }
References debug.
__attribute__() [2/4]
__attribute__ ((weak)) pure virtual
__attribute__() [3/4]
EXTERNC __attribute__ ((weak, no_stack_protector))
Definition at line 9 of file StackGuard.cpp.
 {
     int MaxRetries = 0;
 #if UINTPTR_MAX == UINT32_MAX
     uint32_t num;
 Retry:
     num = Random::rand32();
     if (num < 0x1000 && MaxRetries++ < 10)
         goto Retry;
     return num;
 #else
     uint64_t num;
 Retry:
     num = Random::rand64();
     if (num < 0x100000 && MaxRetries++ < 10)
         goto Retry;
     return num;
 #endif
 }
References Random::rand32(), and Random::rand64().
__attribute__() [4/4]
EXTERNC __attribute__ ((weak, noreturn, no_stack_protector))
Definition at line 38 of file StackGuard.cpp.
 {
     TaskingPanic();
     for (short i = 0; i < 10; i++)
         error("Stack smashing detected!");
     debug("Current stack check guard value: %#lx", __stack_chk_guard);
     KPrint("\eFF0000Stack smashing detected!");
 #if defined(a64) || defined(a32)
     void *Stack = nullptr;
 #if defined(a64)
     asmv("movq %%rsp, %0"
          : "=r"(Stack));
 #elif defined(a32)
     asmv("movl %%esp, %0"
          : "=r"(Stack));
 #endif
     error("Stack address: %#lx", Stack);
     while (1)
         asmv("cli; hlt");
 #elif defined(aa64)
     asmv("wfe");
 #endif
     CPU::Stop();
 }
References asmv, debug, error, KPrint(), Stack, CPU::Stop(), and TaskingPanic().