Fennix Userspace: Userspace/musl/include/sys/timerfd.h File Reference
timerfd.h File Reference
#include <time.h>
#include <fcntl.h>
Macros
#define TFD_NONBLOCK O_NONBLOCK
#define TFD_CLOEXEC O_CLOEXEC
#define TFD_TIMER_ABSTIME 1
#define TFD_TIMER_CANCEL_ON_SET (1 << 1)
Functions
int timerfd_create (int, int)
int timerfd_settime (int, int, const struct itimerspec *, struct itimerspec *)
int timerfd_gettime (int, struct itimerspec *)
Macro Definition Documentation
TFD_CLOEXEC
#define TFD_CLOEXEC O_CLOEXEC
Definition at line 12 of file timerfd.h.
TFD_NONBLOCK
#define TFD_NONBLOCK O_NONBLOCK
Definition at line 11 of file timerfd.h.
TFD_TIMER_ABSTIME
#define TFD_TIMER_ABSTIME 1
Definition at line 14 of file timerfd.h.
TFD_TIMER_CANCEL_ON_SET
#define TFD_TIMER_CANCEL_ON_SET (1 << 1)
Definition at line 15 of file timerfd.h.
Function Documentation
timerfd_create()
int timerfd_create (int clockid, int flags)
Definition at line 9 of file sys-timerfd.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_timerfd_create, -1);
     int fd;
     if(int e = mlibc::sys_timerfd_create(clockid, flags, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_timerfd_create(), and syscall().
timerfd_gettime()
int timerfd_gettime (int fd, struct itimerspec * cur)
Definition at line 29 of file sys-timerfd.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __syscall, __syscall_ret(), ENOSYS, itimerspec::it_interval, itimerspec::it_value, r, SYS_timerfd_gettime, SYS_timerfd_gettime64, syscall(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by __timerfd_gettime32().
timerfd_settime()
int timerfd_settime (int fd, int flags, const struct itimerspec * value, struct itimerspec * oldvalue)
Definition at line 19 of file sys-timerfd.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_timerfd_settime, -1);
     if(int e = mlibc::sys_timerfd_settime(fd, flags, value, oldvalue); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __syscall, __syscall_ret(), ENOSYS, ENOTSUP, errno, flags, IS32BIT, itimerspec::it_interval, itimerspec::it_value, MLIBC_CHECK_OR_ENOSYS, r, mlibc::sys_timerfd_settime(), SYS_timerfd_settime, SYS_timerfd_settime64, syscall(), timespec::tv_nsec, timespec::tv_sec, and value.
Referenced by __timerfd_settime32().