Fennix: Userspace/musl/src/linux/inotify.c File Reference
inotify.c File Reference
#include <sys/inotify.h>
#include <errno.h>
#include "syscall.h"
Functions
int inotify_init ()
int inotify_init1 (int flags)
int inotify_add_watch (int fd, const char *pathname, uint32_t mask)
int inotify_rm_watch (int fd, int wd)
Function Documentation
inotify_add_watch()
int inotify_add_watch (int fd, const char * pathname, uint32_t mask)
Definition at line 18 of file inotify.c.
 {
     return syscall(SYS_inotify_add_watch, fd, pathname, mask);
 }
References fd, and syscall().
Referenced by inotifyd_main(), test_watch_directory(), and test_watch_file().
inotify_init()
int inotify_init (void)
Definition at line 5 of file inotify.c.
 {
     return inotify_init1(0);
 }
References inotify_init1().
Referenced by inotifyd_main(), test_watch_directory(), and test_watch_file().
inotify_init1()
int inotify_init1 (int flags)
Definition at line 9 of file inotify.c.
 {
     int r = __syscall(SYS_inotify_init1, flags);
 #ifdef SYS_inotify_init
     if (r==-ENOSYS && !flags) r = __syscall(SYS_inotify_init);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ENOSYS, and flags.
Referenced by inotify_init().
inotify_rm_watch()
int inotify_rm_watch (int fd, int wd)
Definition at line 23 of file inotify.c.
 {
     return syscall(SYS_inotify_rm_watch, fd, wd);
 }
References fd, and syscall().
Referenced by inotifyd_main(), test_watch_directory(), and test_watch_file().