Fennix: Userspace/apps/base/busybox/miscutils/dc.c File Reference
dc.c File Reference
#include <math.h>
Data Structures
struct globals
struct op
Macros
#define DATA_FMT "ll"
#define G (*(struct globals*)bb_common_bufsiz1)
#define pointer (G.pointer)
#define base (G.base)
#define stack (G.stack)
#define INIT_G()
Typedefs
typedef unsigned long long data_t
Enumerations
enum { STACK_SIZE = (COMMON_BUFSIZE - offsetof(struct globals, stack)) / sizeof(double) }
Functions
static unsigned check_under (void)
static void push (double a)
static double pop (void)
static void add (void)
static void sub (void)
static void mul (void)
static void divide (void)
static void mod (void)
static void and (void)
static void or (void)
static void eor (void)
static void not (void)
static void set_output_base (void)
static void print_base (double print)
static void print_stack_no_pop (void)
static void print_no_pop (void)
static void stack_machine (const char *argument)
static void process_file (FILE *fp)
int dc_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
static const struct op operators[] ALIGN_PTR
Macro Definition Documentation
base
type FAST_FUNC int base (G.base)
Definition at line 31 of file dc.c.
Referenced by print_base(), and set_output_base().
DATA_FMT
#define DATA_FMT "ll"
Definition at line 20 of file dc.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 29 of file dc.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    base = 10; \
} while (0)
Definition at line 33 of file dc.c.
pointer
#define pointer (G.pointer)
Definition at line 30 of file dc.c.
stack
#define stack (G.stack)
Definition at line 32 of file dc.c.
Typedef Documentation
data_t
typedef unsigned long long data_t
Definition at line 19 of file dc.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STACK_SIZE
Definition at line 28 of file dc.c.
 { STACK_SIZE = (COMMON_BUFSIZE - offsetof(struct globals, stack)) / sizeof(double) };
Function Documentation
add()
static void add (void) static
Definition at line 60 of file dc.c.
 {
     push(pop() + pop());
 }
References pop(), and push().
Referenced by add_string_to_strings(), add_strings_to_strings(), cmdlookup(), dump_tree(), ifsbreakup(), o_addchr(), order_dep_list(), and regcomp().
and()
static void and (void) static
Definition at line 113 of file dc.c.
 {
     push((data_t) pop() & (data_t) pop());
 }
References pop(), and push().
check_under()
static unsigned check_under (void) static
Definition at line 38 of file dc.c.
 {
     unsigned p = pointer;
     if (p == 0)
         bb_simple_error_msg_and_die("stack underflow");
     return p - 1;
 }
References bb_simple_error_msg_and_die(), p, and pointer.
Referenced by pop(), and print_no_pop().
dc_main()
int dc_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 270 of file dc.c.
 {
     bool script = 0;
     INIT_G();
     /* Run -e'SCRIPT' and -fFILE in order of appearance, then handle FILEs */
     for (;;) {
         int n = getopt(argc, argv, "e:f:");
         if (n <= 0)
             break;
         switch (n) {
         case 'e':
             script = 1;
             stack_machine(optarg);
             break;
         case 'f':
             script = 1;
             process_file(xfopen_for_read(optarg));
             break;
         default:
             bb_show_usage();
         }
     }
     argv += optind;
     if (*argv) {
         do
             process_file(xfopen_for_read(*argv++));
         while (*argv);
     } else if (!script) {
         /* Take stuff from stdin if no args are given */
         process_file(stdin);
     }
     return EXIT_SUCCESS;
 }
References argc, argv, bb_show_usage(), EXIT_SUCCESS, getopt(), INIT_G, n, optarg, optind, process_file(), stack_machine(), stdin, and xfopen_for_read().
divide()
static void divide (void) static
Definition at line 86 of file dc.c.
 {
     double divisor = pop();
     push(pop() / divisor);
 }
References pop(), and push().
Referenced by yylex().
eor()
static void eor (void) static
Definition at line 123 of file dc.c.
 {
     push((data_t) pop() ^ (data_t) pop());
 }
References pop(), and push().
mod()
static void mod (void) static
Definition at line 93 of file dc.c.
 {
     data_t d = pop();
     /* compat with dc (GNU bc 1.07.1) 1.4.1:
      * $ dc -e '4 0 % p'
      * dc: remainder by zero
      * 0
      */
     if (d == 0) {
         bb_simple_error_msg("remainder by zero");
         pop();
         push(0);
         return;
     }
     /* ^^^^ without this, we simply get SIGFPE and die */
     push((data_t) pop() % d);
 }
References bb_simple_error_msg(), pop(), and push().
mul()
static void mul (void) static
Definition at line 72 of file dc.c.
 {
     push(pop() * pop());
 }
References pop(), and push().
Referenced by sleep_builtin().
not()
static void not (void) static
Definition at line 128 of file dc.c.
 {
     push(~(data_t) pop());
 }
References pop(), and push().
or()
static void or (void) static
Definition at line 118 of file dc.c.
 {
     push((data_t) pop() | (data_t) pop());
 }
References pop(), and push().
pop()
static double pop (void) static
Definition at line 53 of file dc.c.
 {
     unsigned p = check_under();
     pointer = p;
     return stack[p];
 }
References check_under(), p, and stack.
Referenced by add(), and(), divide(), eor(), mod(), mul(), not(), or(), set_output_base(), and sub().
print_base()
static void print_base (double print) static
Definition at line 145 of file dc.c.
 {
     data_t x, i;
     x = (data_t) print;
     if (base == 10) {
         if (x == print) /* exactly representable as unsigned integer */
             printf("%"DATA_FMT"u\n", x);
         else
             printf("%g\n", print);
         return;
     }
     switch (base) {
     case 16:
         printf("%"DATA_FMT"x\n", x);
         break;
     case 8:
         printf("%"DATA_FMT"o\n", x);
         break;
     default: /* base 2 */
         i = MAXINT(data_t) - (MAXINT(data_t) >> 1);
         /* i is 100000...00000 */
         do {
             if (x & i)
                 break;
             i >>= 1;
         } while (i > 1);
         do {
             bb_putchar('1' - !(x & i));
             i >>= 1;
         } while (i);
         bb_putchar('\n');
     }
 }
References base, bb_putchar(), DATA_FMT, i, MAXINT, print, printf, and x.
Referenced by print_no_pop(), and print_stack_no_pop().
print_no_pop()
static void print_no_pop (void) static
Definition at line 188 of file dc.c.
 {
     print_base(stack[check_under()]);
 }
References check_under(), print_base(), and stack.
print_stack_no_pop()
static void print_stack_no_pop (void) static
Definition at line 181 of file dc.c.
 {
     unsigned i = pointer;
     while (i)
         print_base(stack[--i]);
 }
References i, pointer, print_base(), and stack.
process_file()
static void process_file (FILE * fp) static
Definition at line 260 of file dc.c.
 {
     char *line;
     while ((line = xmalloc_fgetline(fp)) != NULL) {
         stack_machine(line);
         free(line);
     }
 }
References free, line, NULL, stack_machine(), and xmalloc_fgetline().
Referenced by dc_main().
push()
static void push (double a) static
Definition at line 46 of file dc.c.
 {
     if (pointer >= STACK_SIZE)
         bb_simple_error_msg_and_die("stack overflow");
     stack[pointer++] = a;
 }
References bb_simple_error_msg_and_die(), stack, and STACK_SIZE.
Referenced by add(), and(), divide(), eor(), mod(), mul(), not(), or(), pushlocalvars(), setinputfd(), stack_machine(), and sub().
set_output_base()
static void set_output_base (void) static
Definition at line 133 of file dc.c.
 {
     static const char bases[] ALIGN1 = { 2, 8, 10, 16, 0 };
     unsigned b = (unsigned)pop();
     base = *strchrnul(bases, b);
     if (base == 0) {
         bb_error_msg("error, base %u is not supported", b);
         base = 10;
     }
 }
References ALIGN1, base, bb_error_msg(), pop(), and strchrnul().
stack_machine()
static void stack_machine (const char * argument) static
Definition at line 225 of file dc.c.
 {
     char *end;
     double number;
     const struct op *o;
  next:
 //TODO: needs setlocale(LC_NUMERIC, "C")?
     number = strtod(argument, &end);
     if (end != argument) {
         argument = end;
         push(number);
         goto next;
     }
     /* We might have matched a digit, eventually advance the argument */
     argument = skip_whitespace(argument);
     if (*argument == '\0')
         return;
     o = operators;
     do {
         char *after_name = is_prefixed_with(argument, o->name);
         if (after_name) {
             argument = after_name;
             o->function();
             goto next;
         }
         o++;
     } while (o != operators + ARRAY_SIZE(operators));
     bb_error_msg_and_die("syntax error at '%s'", argument);
 }
References argument, ARRAY_SIZE, bb_error_msg_and_die(), end, op::function, is_prefixed_with(), op::name, next, number(), push(), skip_whitespace(), and strtod().
Referenced by dc_main(), and process_file().
sub()
static void sub (void) static
Definition at line 65 of file dc.c.
 {
     double subtrahend = pop();
     push(pop() - subtrahend);
 }
References pop(), and push().
Referenced by _nl_locale_name(), archivejoin(), count_strstr(), P_CrossSubsector(), R_Subsector(), redir_varvalue(), strrcmp(), and xmalloc_substitute_string().
Variable Documentation
ALIGN_PTR
const struct op operators [] ALIGN_PTR static
Initial value:
= {
    {"%",   mod},
    {"and", and},
    {"or",  or},
    {"not", not},
    {"xor", eor},
    {"+",   add},
    {"-",   sub},
    {"*",   mul},
    {"/",   divide},
    {"p", print_no_pop},
    {"f", print_stack_no_pop},
    {"o", set_output_base},
}
Definition at line 198 of file dc.c.
FIX_ALIASING
struct globals FIX_ALIASING