Fennix: Userspace/apps/base/busybox/coreutils/wc.c File Reference
wc.c File Reference
#include "libbb.h"
#include "unicode.h"
Macros
#define isprint(c) ((unsigned)((c) - 0x20) <= (0x7e - 0x20))
#define isspace(c) ((c) == ' ')
#define COUNT_T unsigned
#define COUNT_FMT "u"
Enumerations
enum {
WC_LINES = 0 , WC_WORDS = 1 , WC_UNICHARS = 2 , WC_BYTES = 3 ,
WC_LENGTH = 4 , NUM_WCS = 5
}
Functions
int wc_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
COUNT_FMT
#define COUNT_FMT "u"
Definition at line 71 of file wc.c.
COUNT_T
#define COUNT_T unsigned
Definition at line 70 of file wc.c.
isprint
#define isprint (c) ((unsigned)((c) - 0x20) <= (0x7e - 0x20))
Definition at line 62 of file wc.c.
isspace
#define isspace (c) ((c) == ' ')
Definition at line 63 of file wc.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WC_LINES
WC_WORDS
WC_UNICHARS
WC_BYTES
WC_LENGTH
NUM_WCS
Definition at line 99 of file wc.c.
      {
     WC_LINES    = 0, /* -l */
     WC_WORDS    = 1, /* -w */
     WC_UNICHARS = 2, /* -m */
     WC_BYTES    = 3, /* -c */
     WC_LENGTH   = 4, /* -L */
     NUM_WCS     = 5,
 };
Function Documentation
wc_main()
int wc_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 109 of file wc.c.
 {
     const char *arg;
     const char *start_fmt = " %9"COUNT_FMT + 1;
     const char *fname_fmt = " %s\n";
     COUNT_T *pcounts;
     COUNT_T counts[NUM_WCS];
     COUNT_T totals[NUM_WCS];
     int num_files;
     smallint status = EXIT_SUCCESS;
     unsigned print_type;
     init_unicode();
     print_type = getopt32(argv, "lwmcL");
     if (print_type == 0) {
         print_type = (1 << WC_LINES) | (1 << WC_WORDS) | (1 << WC_BYTES);
     }
     argv += optind;
     if (!argv[0]) {
         *--argv = (char *) bb_msg_standard_input;
         fname_fmt = "\n";
     }
     if (!argv[1]) { /* zero or one filename? */
         if (!((print_type-1) & print_type)) /* exactly one option? */
             start_fmt = "%"COUNT_FMT;
     }
     memset(totals, 0, sizeof(totals));
     pcounts = counts;
     num_files = 0;
     while ((arg = *argv++) != NULL) {
         FILE *fp;
         const char *s;
         unsigned u;
         unsigned linepos;
         smallint in_word;
         ++num_files;
         fp = fopen_or_warn_stdin(arg);
         if (!fp) {
             status = EXIT_FAILURE;
             continue;
         }
         memset(counts, 0, sizeof(counts));
         linepos = 0;
         in_word = 0;
         while (1) {
             int c;
             /* Our -w doesn't match GNU wc exactly... oh well */
             c = getc(fp);
             if (c == EOF) {
                 if (ferror(fp)) {
                     bb_simple_perror_msg(arg);
                     status = EXIT_FAILURE;
                 }
                 goto DO_EOF;  /* Treat an EOF as '\r'. */
             }
             /* Cater for -c and -m */
             ++counts[WC_BYTES];
             if (unicode_status != UNICODE_ON /* every byte is a new char */
              || (c & 0xc0) != 0x80 /* it isn't a 2nd+ byte of a Unicode char */
             ) {
                 ++counts[WC_UNICHARS];
             }
             if (isprint_asciionly(c)) { /* FIXME: not unicode-aware */
                 ++linepos;
                 if (!isspace(c)) {
                     in_word = 1;
                     continue;
                 }
             } else if ((unsigned)(c - 9) <= 4) {
                 /* \t  9
                  * \n 10
                  * \v 11
                  * \f 12
                  * \r 13
                  */
                 if (c == '\t') {
                     linepos = (linepos | 7) + 1;
                 } else {  /* '\n', '\r', '\f', or '\v' */
  DO_EOF:
                     if (linepos > counts[WC_LENGTH]) {
                         counts[WC_LENGTH] = linepos;
                     }
                     if (c == '\n') {
                         ++counts[WC_LINES];
                     }
                     if (c != '\v') {
                         linepos = 0;
                     }
                 }
             } else {
                 continue;
             }
             counts[WC_WORDS] += in_word;
             in_word = 0;
             if (c == EOF) {
                 break;
             }
         }
         fclose_if_not_stdin(fp);
         if (totals[WC_LENGTH] < counts[WC_LENGTH]) {
             totals[WC_LENGTH] = counts[WC_LENGTH];
         }
         totals[WC_LENGTH] -= counts[WC_LENGTH];
  OUTPUT:
         /* coreutils wc tries hard to print pretty columns
          * (saves results for all files, finds max col len etc...)
          * we won't try that hard, it will bloat us too much */
         s = start_fmt;
         u = 0;
         do {
             if (print_type & (1 << u)) {
                 printf(s, pcounts[u]);
                 s = " %9"COUNT_FMT; /* Ok... restore the leading space. */
             }
             totals[u] += pcounts[u];
         } while (++u < NUM_WCS);
         printf(fname_fmt, arg);
     }
     /* If more than one file was processed, we want the totals.  To save some
      * space, we set the pcounts ptr to the totals array.  This has the side
      * effect of trashing the totals array after outputting it, but that's
      * irrelavent since we no longer need it. */
     if (num_files > 1) {
         num_files = 0;  /* Make sure we don't get here again. */
         arg = "total";
         pcounts = totals;
         --argv;
         goto OUTPUT;
     }
     fflush_stdout_and_exit(status);
 }
References argv, bb_simple_perror_msg(), c, COUNT_FMT, COUNT_T, EOF, EXIT_FAILURE, EXIT_SUCCESS, fclose_if_not_stdin(), ferror, fflush_stdout_and_exit(), fopen_or_warn_stdin(), getc, getopt32(), init_unicode, isprint_asciionly, isspace, memset, NULL, num_files, NUM_WCS, optind, printf, s, status, UNICODE_ON, unicode_status, WC_BYTES, WC_LENGTH, WC_LINES, WC_UNICHARS, and WC_WORDS.