Fennix: Userspace/apps/base/busybox/networking/ftpgetput.c File Reference
ftpgetput.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define user (G.user)
#define password (G.password)
#define lsa (G.lsa)
#define control_stream (G.control_stream)
#define verbose_flag (G.verbose_flag)
#define do_continue (G.do_continue)
#define buf (G.buf)
#define INIT_G()
#define OPTSTRING "^cvu:p:P:" "\0" "-2:?3:vv:cc"
Enumerations
enum { BUFSZ = COMMON_BUFSIZE - offsetof(struct globals, buf) }
Functions
static void ftp_die (const char *msg) NORETURN
static int ftpcmd (const char *s1, const char *s2)
static void ftp_login (void)
static int xconnect_ftpdata (void)
static int pump_data_and_QUIT (int from, int to)
int ftp_receive (const char *local_path, char *server_path)
int ftp_send (const char *server_path, char *local_path)
int ftpgetput_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
buf
#define buf (G.buf)
Definition at line 77 of file ftpgetput.c.
control_stream
#define control_stream (G.control_stream)
Definition at line 74 of file ftpgetput.c.
do_continue
#define do_continue (G.do_continue)
Definition at line 76 of file ftpgetput.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 69 of file ftpgetput.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    BUILD_BUG_ON(sizeof(G) > COMMON_BUFSIZE); \
} while (0)
Definition at line 78 of file ftpgetput.c.
lsa
#define lsa (G.lsa)
Definition at line 73 of file ftpgetput.c.
OPTSTRING
#define OPTSTRING "^cvu:p:P:" "\0" "-2:?3:vv:cc"
password
#define password (G.password)
Definition at line 72 of file ftpgetput.c.
user
#define user (G.user)
Definition at line 71 of file ftpgetput.c.
verbose_flag
#define verbose_flag (G.verbose_flag)
Definition at line 75 of file ftpgetput.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BUFSZ
Definition at line 70 of file ftpgetput.c.
 { BUFSZ = COMMON_BUFSIZE - offsetof(struct globals, buf) };
Function Documentation
ftp_die()
static void ftp_die (const char * msg) static
Definition at line 85 of file ftpgetput.c.
 {
     char *cp = buf; /* buf holds peer's response */
     /* Guard against garbage from remote server */
     while (*cp >= ' ' && *cp < '\x7f')
         cp++;
     *cp = '\0';
     bb_error_msg_and_die("unexpected server response%s%s: %s",
             (msg ? " to " : ""), (msg ? msg : ""), buf);
 }
References bb_error_msg_and_die(), and buf.
Referenced by ftp_login(), ftpcmd(), pump_data_and_QUIT(), and xconnect_ftpdata().
ftp_login()
static void ftp_login (void) static
Definition at line 124 of file ftpgetput.c.
 {
     /* Connect to the command socket */
     control_stream = fdopen(xconnect_stream(lsa), "r+");
     if (control_stream == NULL) {
         /* fdopen failed - extremely unlikely */
         bb_perror_nomsg_and_die();
     }
     if (ftpcmd(NULL, NULL) != 220) {
         ftp_die(NULL);
     }
     /*  Login to the server */
     switch (ftpcmd("USER", user)) {
     case 230:
         break;
     case 331:
         if (ftpcmd("PASS", password) != 230) {
             ftp_die("PASS");
         }
         break;
     default:
         ftp_die("USER");
     }
     ftpcmd("TYPE I", NULL);
 }
References bb_perror_nomsg_and_die(), control_stream, ftp_die(), ftpcmd(), lsa, NULL, password, and xconnect_stream().
Referenced by ftpgetput_main().
ftp_receive()
int ftp_receive (const char * local_path, char * server_path)
Referenced by ftpgetput_main().
ftp_send()
int ftp_send (const char * server_path, char * local_path)
Referenced by ftpgetput_main().
ftpcmd()
static int ftpcmd (const char * s1, const char * s2) static
Definition at line 97 of file ftpgetput.c.
 {
     unsigned n;
     if (verbose_flag) {
         bb_error_msg("cmd %s %s", s1, s2);
     }
     if (s1) {
         fprintf(control_stream, (s2 ? "%s %s\r\n" : "%s %s\r\n"+3),
                         s1, s2);
         fflush(control_stream);
     }
     do {
         strcpy(buf, "EOF"); /* for ftp_die */
         if (fgets(buf, BUFSZ - 2, control_stream) == NULL) {
             ftp_die(NULL);
         }
     } while (!isdigit(buf[0]) || buf[3] != ' ');
     buf[3] = '\0';
     n = xatou(buf);
     buf[3] = ' ';
     return n;
 }
References bb_error_msg(), buf, BUFSZ, control_stream, fflush(), fgets, fprintf(), ftp_die(), isdigit, n, NULL, s1, s2, strcpy, verbose_flag, and xatou().
Referenced by download_one_url(), ftp_login(), pump_data_and_QUIT(), and xconnect_ftpdata().
ftpgetput_main()
int ftpgetput_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 291 of file ftpgetput.c.
 {
     const char *port = NULL;
 #if ENABLE_FTPPUT && !ENABLE_FTPGET
 # define ftp_action ftp_send
 #elif ENABLE_FTPGET && !ENABLE_FTPPUT
 # define ftp_action ftp_receive
 #else
     int (*ftp_action)(const char *, char *) = ftp_send;
     /* Check to see if the command is ftpget or ftput */
     if (applet_name[3] == 'g') {
         ftp_action = ftp_receive;
     }
 #endif
     INIT_G();
     /* Set default values */
     user = "anonymous";
     password = "busybox";
     /*
      * Decipher the command line
      */
     /* must have 2 to 3 params; -v and -c count */
 #define OPTSTRING "^cvu:p:P:" "\0" "-2:?3:vv:cc"
 #if ENABLE_FEATURE_FTPGETPUT_LONG_OPTIONS
     getopt32long(argv, OPTSTRING, ftpgetput_longopts,
 #else
     getopt32(argv, OPTSTRING,
 #endif
             &user, &password, &port, &verbose_flag, &do_continue
     );
     argv += optind;
     /* We want to do exactly _one_ DNS lookup, since some
      * sites (i.e. ftp.us.debian.org) use round-robin DNS
      * and we want to connect to only one IP... */
     lsa = xhost2sockaddr(argv[0], bb_lookup_port(port, "tcp", 21));
     if (verbose_flag) {
         printf("Connecting to %s (%s)\n", argv[0],
             xmalloc_sockaddr2dotted(&lsa->u.sa));
     }
     ftp_login();
     return ftp_action(argv[1], argv[2] ? argv[2] : argv[1]);
 }
References applet_name, argv, bb_lookup_port(), do_continue, ftp_login(), ftp_receive(), ftp_send(), getopt32(), getopt32long, INIT_G, lsa, NULL, optind, OPTSTRING, password, port, printf, verbose_flag, xhost2sockaddr(), and xmalloc_sockaddr2dotted().
pump_data_and_QUIT()
static int pump_data_and_QUIT (int from, int to) static
Definition at line 170 of file ftpgetput.c.
 {
     /* copy the file */
     if (bb_copyfd_eof(from, to) == -1) {
         /* error msg is already printed by bb_copyfd_eof */
         return EXIT_FAILURE;
     }
     /* close data connection */
     close(from); /* don't know which one is that, so we close both */
     close(to);
     /* does server confirm that transfer is finished? */
     if (ftpcmd(NULL, NULL) != 226) {
         ftp_die(NULL);
     }
     ftpcmd("QUIT", NULL);
     return EXIT_SUCCESS;
 }
References bb_copyfd_eof(), close(), EXIT_FAILURE, EXIT_SUCCESS, ftp_die(), ftpcmd(), and NULL.
xconnect_ftpdata()
static int xconnect_ftpdata (void) static
Definition at line 153 of file ftpgetput.c.
 {
     int port_num;
     if (ENABLE_FEATURE_IPV6 && ftpcmd("EPSV", NULL) == 229) {
         /* good */
     } else if (ftpcmd("PASV", NULL) != 227) {
         ftp_die("PASV");
     }
     port_num = parse_pasv_epsv(buf);
     if (port_num < 0)
         ftp_die("PASV");
     set_nport(&lsa->u.sa, htons(port_num));
     return xconnect_stream(lsa);
 }
References buf, ftp_die(), ftpcmd(), htons(), lsa, NULL, parse_pasv_epsv(), set_nport(), and xconnect_stream().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING