Fennix: Userspace/apps/base/busybox/libbb/full_write.c File Reference
full_write.c File Reference
#include "libbb.h"
Functions
ssize_t FAST_FUNC full_write (int fd, const void *buf, size_t len)
Function Documentation
full_write()
ssize_t FAST_FUNC full_write (int fd, const void * buf, size_t len)
Definition at line 17 of file full_write.c.
 {
     ssize_t cc;
     ssize_t total;
     total = 0;
     while (len) {
         cc = safe_write(fd, buf, len);
         if (cc < 0) {
             if (total) {
                 /* we already wrote some! */
                 /* user can do another write to know the error code */
                 return total;
             }
             return cc;  /* write() returns -1 on failure. */
         }
         total += cc;
         buf = ((const char *)buf) + cc;
         len -= cc;
     }
     return total;
 }
References buf, fd, len, safe_write(), and total.
Referenced by basename_main(), bb_full_fd_action(), bb_verror_msg(), chat_main(), dmesg_main(), dprintf(), echo_main(), fbsplash_main(), file_write(), flashcp_main(), full_write1_str(), full_write2_str(), get_logname(), handle_net_input(), handle_net_output(), iac_flush(), IF_DESKTOP(), load_firmware(), log_locally(), lpqr_main(), message(), microcom_main(), pipe_progress_main(), receive(), run(), script_main(), send_file_and_exit(), send_headers(), setup_heredoc(), transformer_write(), write_and_stats(), write_block(), write_leases(), write_pidfile(), write_superblock(), writeLines(), and xwrite().