Fennix Userspace: Userspace/apps/base/busybox/console-tools/resize.c File Reference
resize.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define ESC "\033"
#define old_termios_p ((struct termios*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Functions
static void onintr (int sig UNUSED_PARAM)
int resize_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int resize_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Macro Definition Documentation
ESC
#define ESC "\033"
Definition at line 39 of file resize.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 42 of file resize.c.
old_termios_p
#define old_termios_p ((struct termios*)bb_common_bufsiz1)
Definition at line 41 of file resize.c.
Function Documentation
onintr()
static void onintr (int sig UNUSED_PARAM) static
Definition at line 45 of file resize.c.
 {
     tcsetattr(STDERR_FILENO, TCSANOW, old_termios_p);
     _exit(EXIT_FAILURE);
 }
References _exit(), EXIT_FAILURE, old_termios_p, STDERR_FILENO, TCSANOW, and tcsetattr().
Referenced by resize_main().
resize_main() [1/2]
int resize_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 52 of file resize.c.
 {
     struct termios new;
     struct winsize w = { 0, 0, 0, 0 };
     int ret;
     INIT_G();
     /* We use _stderr_ in order to make resize usable
      * in shell backticks (those redirect stdout away from tty).
      * NB: other versions of resize open "/dev/tty"
      * and operate on it - should we do the same?
      */
     tcgetattr(STDERR_FILENO, old_termios_p); /* fiddle echo */
 //TODO: die if the above fails?
     memcpy(&new, old_termios_p, sizeof(new));
     new.c_cflag |= (CLOCAL | CREAD);
     new.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG);
     bb_signals(0
         + (1 << SIGINT)
         + (1 << SIGQUIT)
         + (1 << SIGTERM)
         + (1 << SIGALRM)
         , onintr);
     /* Users report:
      *  The resize command messes up the terminal.
      *  In my case it looks like it is hanging and
      *  I need to press ctrl-c to get a prompt.
      *  Actually the program does not hang but just
      *  the terminal is messed up.
      * Replaced TCSANOW with TCSAFLUSH:
      * "the change occurs after all output written to fd
      * has been transmitted, and all input that has been
      * received but not read will be discarded before
      * the change is made.
      */
     tcsetattr(STDERR_FILENO, TCSAFLUSH, &new);
     /* save_cursor_pos 7
      * scroll_whole_screen [r
      * put_cursor_waaaay_off [$x;$yH
      * get_cursor_pos [6n
      * restore_cursor_pos 8
      */
     fprintf(stderr, ESC"7" ESC"[r" ESC"[999;999H" ESC"[6n");
     alarm(3); /* Just in case terminal won't answer */
 //BUG: death by signal won't restore termios
     scanf(ESC"[%hu;%huR", &w.ws_row, &w.ws_col);
     fprintf(stderr, ESC"8");
     /* BTW, other versions of resize recalculate w.ws_xpixel, ws.ws_ypixel
      * by calculating character cell HxW from old values
      * (gotten via TIOCGWINSZ) and recomputing *pixel values */
     ret = ioctl(STDERR_FILENO, TIOCSWINSZ, &w);
     tcsetattr(STDERR_FILENO, TCSANOW, old_termios_p);
     if (ENABLE_FEATURE_RESIZE_PRINT)
         printf("COLUMNS=%d;LINES=%d;export COLUMNS LINES;\n",
             w.ws_col, w.ws_row);
     return ret;
 }
References alarm(), bb_signals(), CLOCAL, CREAD, ECHO, ECHOE, ESC, fprintf(), ICANON, INIT_G, ioctl(), ISIG, memcpy(), old_termios_p, onintr(), printf(), scanf(), SIGALRM, SIGINT, SIGQUIT, SIGTERM, stderr, STDERR_FILENO, tcgetattr(), TCSAFLUSH, TCSANOW, tcsetattr(), TIOCSWINSZ, and w.
resize_main() [2/2]
int resize_main (int argc, char ** argv)