Fennix Userspace: Userspace/apps/base/busybox/libbb/xatonum_template.c File Reference
xatonum_template.c File Reference
Functions
unsigned type FAST_FUNC xstrtou() _range_sfx (const char *numstr, int base, unsigned type lower, unsigned type upper, const struct suffix_mult *suffixes)
unsigned type FAST_FUNC xstrtou() _range (const char *numstr, int base, unsigned type lower, unsigned type upper)
unsigned type FAST_FUNC xstrtou() _sfx (const char *numstr, int base, const struct suffix_mult *suffixes)
unsigned type FAST_FUNC xstrtou ()(const char *numstr
unsigned type FAST_FUNC xatou() _range_sfx (const char *numstr, unsigned type lower, unsigned type upper, const struct suffix_mult *suffixes)
unsigned type FAST_FUNC xatou() _range (const char *numstr, unsigned type lower, unsigned type upper)
unsigned type FAST_FUNC xatou() _sfx (const char *numstr, const struct suffix_mult *suffixes)
unsigned type FAST_FUNC xatou ()(const char *numstr)
type FAST_FUNC xstrto() _range_sfx (const char *numstr, int base, type lower, type upper, const struct suffix_mult *suffixes)
type FAST_FUNC xstrto() _range (const char *numstr, int base, type lower, type upper)
type FAST_FUNC xstrto ()(const char *numstr
type FAST_FUNC xato() _range_sfx (const char *numstr, type lower, type upper, const struct suffix_mult *suffixes)
type FAST_FUNC xato() _range (const char *numstr, type lower, type upper)
type FAST_FUNC xato ()(const char *numstr)
Variables
unsigned type FAST_FUNC int base
Function Documentation
_range() [1/4]
type FAST_FUNC xstrto() _range (const char * numstr, int base, type lower, type upper)
Definition at line 154 of file xatonum_template.c.
 {
     return xstrto(_range_sfx)(numstr, base, lower, upper, NULL);
 }
References _range_sfx(), base, NULL, and xstrto().
_range() [2/4]
unsigned type FAST_FUNC xstrtou() _range (const char * numstr, int base, unsigned type lower, unsigned type upper)
Definition at line 77 of file xatonum_template.c.
 {
     return xstrtou(_range_sfx)(numstr, base, lower, upper, NULL);
 }
References _range_sfx(), base, NULL, and xstrtou().
_range() [3/4]
type FAST_FUNC xato() _range (const char * numstr, type lower, type upper)
Definition at line 172 of file xatonum_template.c.
 {
     return xstrto(_range_sfx)(numstr, 10, lower, upper, NULL);
 }
References _range_sfx(), NULL, and xstrto().
_range() [4/4]
unsigned type FAST_FUNC xatou() _range (const char * numstr, unsigned type lower, unsigned type upper)
Definition at line 103 of file xatonum_template.c.
 {
     return xstrtou(_range_sfx)(numstr, 10, lower, upper, NULL);
 }
References _range_sfx(), NULL, and xstrtou().
_range_sfx() [1/4]
type FAST_FUNC xstrto() _range_sfx (const char * numstr, int base, type lower, type upper, const struct suffix_mult * suffixes)
Definition at line 123 of file xatonum_template.c.
 {
     unsigned type u = XSTR_TYPE_MAX;
     type r;
     const char *p = numstr;
     /* NB: if you'll decide to disallow '+':
      * at least renice applet needs to allow it */
     if (p[0] == '+' || p[0] == '-') {
         ++p;
         if (p[0] == '-')
             ++u; /* = <type>_MIN (01111... + 1 == 10000...) */
     }
     r = xstrtou(_range_sfx)(p, base, 0, u, suffixes);
     if (*numstr == '-') {
         r = -r;
     }
     if (r < lower || r > upper) {
         bb_error_msg_and_die("number %s is not in %lld..%lld range",
                 numstr, (long long)lower, (long long)upper);
     }
     return r;
 }
References _range_sfx(), base, bb_error_msg_and_die(), p, type, XSTR_TYPE_MAX, and xstrtou().
_range_sfx() [2/4]
unsigned type FAST_FUNC xstrtou() _range_sfx (const char * numstr, int base, unsigned type lower, unsigned type upper, const struct suffix_mult * suffixes)
Definition at line 19 of file xatonum_template.c.
 {
     unsigned type r;
     int old_errno;
     char *e;
     /* Disallow '-' and any leading whitespace. */
     if (*numstr == '-' || *numstr == '+' || isspace(*numstr))
         goto inval;
     /* Since this is a lib function, we're not allowed to reset errno to 0.
      * Doing so could break an app that is deferring checking of errno.
      * So, save the old value so that we can restore it if successful. */
     old_errno = errno;
     errno = 0;
     r = XSTR_STRTOU(numstr, &e, base);
     /* Do the initial validity check.  Note: The standards do not
      * guarantee that errno is set if no digits were found.  So we
      * must test for this explicitly. */
     if (errno || numstr == e)
         goto inval; /* error / no digits / illegal trailing chars */
     errno = old_errno;  /* Ok.  So restore errno. */
     /* Do optional suffix parsing.  Allow 'empty' suffix tables.
      * Note that we also allow nul suffixes with associated multipliers,
      * to allow for scaling of the numstr by some default multiplier. */
     if (suffixes) {
         while (suffixes->mult) {
             if (strcmp(suffixes->suffix, e) == 0) {
                 if (XSTR_UTYPE_MAX / suffixes->mult < r)
                     goto range; /* overflow! */
                 r *= suffixes->mult;
                 goto chk_range;
             }
             ++suffixes;
         }
     }
     /* Note: trailing space is an error.
      * It would be easy enough to allow though if desired. */
     if (*e)
         goto inval;
  chk_range:
     /* Finally, check for range limits. */
     if (r >= lower && r <= upper)
         return r;
  range:
     bb_error_msg_and_die("number %s is not in %llu..%llu range",
         numstr, (unsigned long long)lower,
         (unsigned long long)upper);
  inval:
     bb_error_msg_and_die("invalid number '%s'", numstr);
 }
References base, bb_error_msg_and_die(), errno, isspace, range, strcmp, type, XSTR_STRTOU, and XSTR_UTYPE_MAX.
Referenced by _range(), _range_sfx(), _sfx(), xato(), and xstrto().
_range_sfx() [3/4]
type FAST_FUNC xato() _range_sfx (const char * numstr, type lower, type upper, const struct suffix_mult * suffixes)
Definition at line 164 of file xatonum_template.c.
 {
     return xstrto(_range_sfx)(numstr, 10, lower, upper, suffixes);
 }
References _range_sfx(), and xstrto().
_range_sfx() [4/4]
unsigned type FAST_FUNC xatou() _range_sfx (const char * numstr, unsigned type lower, unsigned type upper, const struct suffix_mult * suffixes)
Definition at line 95 of file xatonum_template.c.
 {
     return xstrtou(_range_sfx)(numstr, 10, lower, upper, suffixes);
 }
References _range_sfx(), and xstrtou().
_sfx() [1/2]
unsigned type FAST_FUNC xatou() _sfx (const char * numstr, const struct suffix_mult * suffixes)
Definition at line 110 of file xatonum_template.c.
 {
     return xstrtou(_range_sfx)(numstr, 10, 0, XSTR_UTYPE_MAX, suffixes);
 }
References _range_sfx(), XSTR_UTYPE_MAX, and xstrtou().
_sfx() [2/2]
unsigned type FAST_FUNC xstrtou() _sfx (const char * numstr, int base, const struct suffix_mult * suffixes)
Definition at line 84 of file xatonum_template.c.
 {
     return xstrtou(_range_sfx)(numstr, base, 0, XSTR_UTYPE_MAX, suffixes);
 }
References _range_sfx(), base, XSTR_UTYPE_MAX, and xstrtou().
Referenced by xatou().
xato()
type FAST_FUNC xato () const
Definition at line 182 of file xatonum_template.c.
 {
     return xstrto(_range_sfx)(numstr, 10, XSTR_TYPE_MIN, XSTR_TYPE_MAX, NULL);
 }
References _range_sfx(), NULL, XSTR_TYPE_MAX, XSTR_TYPE_MIN, and xstrto().
xatou()
unsigned type FAST_FUNC xatou () const
Definition at line 116 of file xatonum_template.c.
 {
     return xatou(_sfx)(numstr, NULL);
 }
References _sfx(), and NULL.
Referenced by beep_main(), decode_arg(), devmem_main(), ftpcmd(), nbdclient_main(), nc_main(), rtcwake_main(), set_speed_or_die(), shuf_main(), sleep_main(), stty_main(), top_main(), udhcpc_main(), udhcpd_main(), usleep_main(), vconfig_main(), and xatou32().
xstrto()
type FAST_FUNC xstrto () const
References _range_sfx(), base, NULL, XSTR_TYPE_MAX, and XSTR_TYPE_MIN.
Referenced by _range(), _range_sfx(), and xato().
xstrtou()
unsigned type FAST_FUNC xstrtou () const
Referenced by _range(), _range_sfx(), _sfx(), fileAction(), nandwrite_main(), and parse_map_file().
Variable Documentation
base
type FAST_FUNC int base
Initial value:
{
    return xstrtou(_range_sfx)(numstr, base, 0, XSTR_UTYPE_MAX, NULL)
Definition at line 90 of file xatonum_template.c.
Referenced by __dls2(), __dn_expand(), __intscan(), __qsort_r(), __timespec_get_time32(), __unmapself(), _dlstart_c(), _range(), _range_sfx(), _sfx(), addr2dso(), bb_process_escape_sequence(), bb_strtoi(), bb_strtoi32(), bb_strtol(), bb_strtoll(), bb_strtou(), bb_strtou32(), bb_strtoul(), bb_strtoull(), bsearch(), config_file_action(), copy_changed_values(), device_already_active(), do_mips_relocs(), do_relocs(), do_relr_relocs(), donate(), fallocate(), fmtulong(), format_string_loop(), free(), get_charset_aliases(), get_meta(), get_next_block(), getoffs(), ipow(), lfind(), lsearch(), malloc(), map_library(), match(), ms_seek(), mseek(), nuke_main(), number(), numtoa(), obj_create_image(), obj_relocate(), odoffset(), ParseField(), posix_fadvise(), posix_fallocate(), print_integer(), print_integer_finalization(), qsort(), read_cmdline(), read_num(), realloc(), reclaim(), rm_main(), rtnl_a2n(), sh_canonpath(), static_dl_iterate_phdr(), static_init_tls(), strlong(), strtoimax(), strtol(), strtoll(), strtoul(), strtoull(), strtoumax(), strtox(), sym_get_range_val(), sym_validate_range(), timespec_get(), ts_main(), unmap_chunk(), vfscanf(), wcstoimax(), wcstol(), wcstoll(), wcstoul(), wcstoull(), wcstoumax(), wcstox(), wms_seek(), xparse_dolparen(), xstrto(), and Z_Malloc().