Fennix Userspace: Userspace/apps/base/busybox/util-linux/fatattr.c File Reference
fatattr.c File Reference
#include "libbb.h"
Macros
#define FAT_IOCTL_GET_ATTRIBUTES _IOR('r', 0x10, uint32_t)
#define FAT_IOCTL_SET_ATTRIBUTES _IOW('r', 0x11, uint32_t)
Functions
static unsigned long get_flag (char c)
static unsigned decode_arg (const char *arg)
int fatattr_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char bit_to_char[] ALIGN1 = "rhsvda67 "
Macro Definition Documentation
FAT_IOCTL_GET_ATTRIBUTES
#define FAT_IOCTL_GET_ATTRIBUTES _IOR('r', 0x10, uint32_t)
Definition at line 37 of file fatattr.c.
FAT_IOCTL_SET_ATTRIBUTES
#define FAT_IOCTL_SET_ATTRIBUTES _IOW('r', 0x11, uint32_t)
Definition at line 38 of file fatattr.c.
Function Documentation
decode_arg()
static unsigned decode_arg (const char * arg) static
Definition at line 55 of file fatattr.c.
 {
     unsigned fl = 0;
     while (*++arg)
         fl |= get_flag(*arg);
     return fl;
 }
References get_flag().
Referenced by fatattr_main().
fatattr_main()
int fatattr_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 64 of file fatattr.c.
 {
     unsigned set_mask = 0;
     unsigned clear_mask = 0;
     for (;;) {
         unsigned fl;
         char *arg = *++argv;
         if (!arg)
             bb_show_usage();
         if (arg[0] != '-' && arg[0] != '+')
             break;
         fl = decode_arg(arg);
         if (arg[0] == '+')
             set_mask |= fl;
         else
             clear_mask |= fl;
     }
     do {
         int fd, i;
         uint32_t attr;
         fd = xopen(*argv, O_RDONLY);
         xioctl(fd, FAT_IOCTL_GET_ATTRIBUTES, &attr);
         attr = (attr | set_mask) & ~clear_mask;
         if (set_mask | clear_mask)
             xioctl(fd, FAT_IOCTL_SET_ATTRIBUTES, &attr);
         else {
             for (i = 0; bit_to_char[i]; i++) {
                 bb_putchar((attr & 1) ? bit_to_char[i] : ' ');
                 attr >>= 1;
             }
             puts(*argv);
         }
         close(fd);
     } while (*++argv);
     return EXIT_SUCCESS;
 }
References argv, bb_putchar(), bb_show_usage(), close(), decode_arg(), EXIT_SUCCESS, FAT_IOCTL_GET_ATTRIBUTES, FAT_IOCTL_SET_ATTRIBUTES, fd, i, O_RDONLY, puts(), xioctl, and xopen().
get_flag()
static unsigned long get_flag (char c) inline static
Definition at line 47 of file fatattr.c.
 {
     const char *fp = strchr(bit_to_char, c);
     if (!fp)
         bb_error_msg_and_die("invalid character '%c'", c);
     return 1 << (fp - bit_to_char);
 }
References bb_error_msg_and_die(), c, and strchr().
Referenced by decode_arg().
Variable Documentation
ALIGN1
const char bit_to_char [] ALIGN1 = "rhsvda67 " static
Definition at line 45 of file fatattr.c.