Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/r_bsp.c File Reference
r_bsp.c File Reference
#include "doomdef.h"
#include "m_bbox.h"
#include "i_system.h"
#include "r_main.h"
#include "r_plane.h"
#include "r_things.h"
#include "doomstat.h"
#include "r_state.h"
Data Structures
struct cliprange_t
Macros
#define MAXSEGS 32
Functions
void R_StoreWallRange (int start, int stop)
void R_ClearDrawSegs (void)
void R_ClipSolidWallSegment (int first, int last)
void R_ClipPassWallSegment (int first, int last)
void R_ClearClipSegs (void)
void R_AddLine (seg_t *line)
boolean R_CheckBBox (fixed_t *bspcoord)
void R_Subsector (int num)
void R_RenderBSPNode (int bspnum)
Variables
seg_t * curline
side_t * sidedef
line_t * linedef
sector_t * frontsector
sector_t * backsector
drawseg_t drawsegs [MAXDRAWSEGS]
drawseg_t * ds_p
cliprange_t * newend
cliprange_t solidsegs [MAXSEGS]
int checkcoord [12][4]
Data Structure Documentation
cliprange_t
struct cliprange_t
Definition at line 73 of file r_bsp.c.
Data Fields
int first
int last
Macro Definition Documentation
MAXSEGS
#define MAXSEGS 32
Definition at line 81 of file r_bsp.c.
Function Documentation
R_AddLine()
void R_AddLine (seg_t * line)
Definition at line 252 of file r_bsp.c.
 {
     int         x1;
     int         x2;
     angle_t     angle1;
     angle_t     angle2;
     angle_t     span;
     angle_t     tspan;
     curline = line;
     // OPTIMIZE: quickly reject orthogonal back sides.
     angle1 = R_PointToAngle (line->v1->x, line->v1->y);
     angle2 = R_PointToAngle (line->v2->x, line->v2->y);
     // Clip to view edges.
     // OPTIMIZE: make constant out of 2*clipangle (FIELDOFVIEW).
     span = angle1 - angle2;
     // Back side? I.e. backface culling?
     if (span >= ANG180)
     return;
     // Global angle needed by segcalc.
     rw_angle1 = angle1;
     angle1 -= viewangle;
     angle2 -= viewangle;
     tspan = angle1 + clipangle;
     if (tspan > 2*clipangle)
     {
     tspan -= 2*clipangle;
     // Totally off the left edge?
     if (tspan >= span)
         return;
     angle1 = clipangle;
     }
     tspan = clipangle - angle2;
     if (tspan > 2*clipangle)
     {
     tspan -= 2*clipangle;
     // Totally off the left edge?
     if (tspan >= span)
         return;
     angle2 = -clipangle;
     }
     // The seg is in the view range,
     // but not necessarily visible.
     angle1 = (angle1+ANG90)>>ANGLETOFINESHIFT;
     angle2 = (angle2+ANG90)>>ANGLETOFINESHIFT;
     x1 = viewangletox[angle1];
     x2 = viewangletox[angle2];
     // Does not cross a pixel?
     if (x1 == x2)
     return;
     backsector = line->backsector;
     // Single sided line?
     if (!backsector)
     goto clipsolid;
     // Closed door.
     if (backsector->ceilingheight <= frontsector->floorheight
     || backsector->floorheight >= frontsector->ceilingheight)
     goto clipsolid;
     // Window.
     if (backsector->ceilingheight != frontsector->ceilingheight
     || backsector->floorheight != frontsector->floorheight)
     goto clippass;
     // Reject empty lines used for triggers
     //  and special events.
     // Identical floor and ceiling on both sides,
     // identical light levels on both sides,
     // and no middle texture.
     if (backsector->ceilingpic == frontsector->ceilingpic
     && backsector->floorpic == frontsector->floorpic
     && backsector->lightlevel == frontsector->lightlevel
     && curline->sidedef->midtexture == 0)
     {
     return;
     }
   clippass:
     R_ClipPassWallSegment (x1, x2-1);
     return;
   clipsolid:
     R_ClipSolidWallSegment (x1, x2-1);
 }
References ANG180, ANG90, ANGLETOFINESHIFT, backsector, seg_t::backsector, sector_t::ceilingheight, sector_t::ceilingpic, clipangle, curline, sector_t::floorheight, sector_t::floorpic, frontsector, sector_t::lightlevel, side_t::midtexture, R_ClipPassWallSegment(), R_ClipSolidWallSegment(), R_PointToAngle(), rw_angle1, seg_t::sidedef, seg_t::v1, seg_t::v2, viewangle, viewangletox, vertex_t::x, and vertex_t::y.
Referenced by R_Subsector().
R_CheckBBox()
boolean R_CheckBBox (fixed_t * bspcoord)
Definition at line 374 of file r_bsp.c.
 {
     int         boxx;
     int         boxy;
     int         boxpos;
     fixed_t     x1;
     fixed_t     y1;
     fixed_t     x2;
     fixed_t     y2;
     angle_t     angle1;
     angle_t     angle2;
     angle_t     span;
     angle_t     tspan;
     cliprange_t*    start;
     int         sx1;
     int         sx2;
     // Find the corners of the box
     // that define the edges from current viewpoint.
     if (viewx <= bspcoord[BOXLEFT])
     boxx = 0;
     else if (viewx < bspcoord[BOXRIGHT])
     boxx = 1;
     else
     boxx = 2;
     if (viewy >= bspcoord[BOXTOP])
     boxy = 0;
     else if (viewy > bspcoord[BOXBOTTOM])
     boxy = 1;
     else
     boxy = 2;
     boxpos = (boxy<<2)+boxx;
     if (boxpos == 5)
     return true;
     x1 = bspcoord[checkcoord[boxpos][0]];
     y1 = bspcoord[checkcoord[boxpos][1]];
     x2 = bspcoord[checkcoord[boxpos][2]];
     y2 = bspcoord[checkcoord[boxpos][3]];
     // check clip list for an open space
     angle1 = R_PointToAngle (x1, y1) - viewangle;
     angle2 = R_PointToAngle (x2, y2) - viewangle;
     span = angle1 - angle2;
     // Sitting on a line?
     if (span >= ANG180)
     return true;
     tspan = angle1 + clipangle;
     if (tspan > 2*clipangle)
     {
     tspan -= 2*clipangle;
     // Totally off the left edge?
     if (tspan >= span)
         return false;
     angle1 = clipangle;
     }
     tspan = clipangle - angle2;
     if (tspan > 2*clipangle)
     {
     tspan -= 2*clipangle;
     // Totally off the left edge?
     if (tspan >= span)
         return false;
     angle2 = -clipangle;
     }
     // Find the first clippost
     //  that touches the source post
     //  (adjacent pixels are touching).
     angle1 = (angle1+ANG90)>>ANGLETOFINESHIFT;
     angle2 = (angle2+ANG90)>>ANGLETOFINESHIFT;
     sx1 = viewangletox[angle1];
     sx2 = viewangletox[angle2];
     // Does not cross a pixel.
     if (sx1 == sx2)
     return false;
     sx2--;
     start = solidsegs;
     while (start->last < sx2)
     start++;
     if (sx1 >= start->first
     && sx2 <= start->last)
     {
     // The clippost contains the new span.
     return false;
     }
     return true;
 }
References ANG180, ANG90, ANGLETOFINESHIFT, BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, checkcoord, clipangle, cliprange_t::first, cliprange_t::last, R_PointToAngle(), solidsegs, viewangle, viewangletox, viewx, viewy, and y1().
Referenced by R_RenderBSPNode().
R_ClearClipSegs()
void R_ClearClipSegs (void)
Definition at line 238 of file r_bsp.c.
 {
     solidsegs[0].first = -0x7fffffff;
     solidsegs[0].last = -1;
     solidsegs[1].first = viewwidth;
     solidsegs[1].last = 0x7fffffff;
     newend = solidsegs+2;
 }
References cliprange_t::first, cliprange_t::last, newend, solidsegs, and viewwidth.
Referenced by R_RenderPlayerView().
R_ClearDrawSegs()
void R_ClearDrawSegs (void)
Definition at line 61 of file r_bsp.c.
 {
     ds_p = drawsegs;
 }
References drawsegs, and ds_p.
Referenced by R_RenderPlayerView().
R_ClipPassWallSegment()
void R_ClipPassWallSegment (int first, int last)
Definition at line 190 of file r_bsp.c.
 {
     cliprange_t*    start;
     // Find the first range that touches the range
     //  (adjacent pixels are touching).
     start = solidsegs;
     while (start->last < first-1)
     start++;
     if (first < start->first)
     {
     if (last < start->first-1)
     {
         // Post is entirely visible (above start).
         R_StoreWallRange (first, last);
         return;
     }
     // There is a fragment above *start.
     R_StoreWallRange (first, start->first - 1);
     }
     // Bottom contained in start?
     if (last <= start->last)
     return;
     while (last >= (start+1)->first-1)
     {
     // There is a fragment between two posts.
     R_StoreWallRange (start->last + 1, (start+1)->first - 1);
     start++;
     if (last <= start->last)
         return;
     }
     // There is a fragment after *next.
     R_StoreWallRange (start->last + 1, last);
 }
References cliprange_t::first, cliprange_t::last, R_StoreWallRange(), and solidsegs.
Referenced by R_AddLine().
R_ClipSolidWallSegment()
void R_ClipSolidWallSegment (int first, int last)
Definition at line 97 of file r_bsp.c.
 {
     cliprange_t*    next;
     cliprange_t*    start;
     // Find the first range that touches the range
     //  (adjacent pixels are touching).
     start = solidsegs;
     while (start->last < first-1)
     start++;
     if (first < start->first)
     {
     if (last < start->first-1)
     {
         // Post is entirely visible (above start),
         //  so insert a new clippost.
         R_StoreWallRange (first, last);
         next = newend;
         newend++;
         while (next != start)
         {
         *next = *(next-1);
         next--;
         }
         next->first = first;
         next->last = last;
         return;
     }
     // There is a fragment above *start.
     R_StoreWallRange (first, start->first - 1);
     // Now adjust the clip size.
     start->first = first;
     }
     // Bottom contained in start?
     if (last <= start->last)
     return;
     next = start;
     while (last >= (next+1)->first-1)
     {
     // There is a fragment between two posts.
     R_StoreWallRange (next->last + 1, (next+1)->first - 1);
     next++;
     if (last <= next->last)
     {
         // Bottom is contained in next.
         // Adjust the clip size.
         start->last = next->last;
         goto crunch;
     }
     }
     // There is a fragment after *next.
     R_StoreWallRange (next->last + 1, last);
     // Adjust the clip size.
     start->last = last;
     // Remove start+1 to next from the clip list,
     // because start now covers their area.
   crunch:
     if (next == start)
     {
     // Post just extended past the bottom of one post.
     return;
     }
     while (next++ != newend)
     {
     // Remove a post.
     *++start = *next;
     }
     newend = start+1;
 }
References cliprange_t::first, cliprange_t::last, newend, R_StoreWallRange(), and solidsegs.
Referenced by R_AddLine().
R_RenderBSPNode()
void R_RenderBSPNode (int bspnum)
Definition at line 545 of file r_bsp.c.
 {
     node_t* bsp;
     int     side;
     // Found a subsector?
     if (bspnum & NF_SUBSECTOR)
     {
     if (bspnum == -1)
         R_Subsector (0);
     else
         R_Subsector (bspnum&(~NF_SUBSECTOR));
     return;
     }
     bsp = &nodes[bspnum];
     // Decide which side the view point is on.
     side = R_PointOnSide (viewx, viewy, bsp);
     // Recursively divide front space.
     R_RenderBSPNode (bsp->children[side]);
     // Possibly divide back space.
     if (R_CheckBBox (bsp->bbox[side^1]))
     R_RenderBSPNode (bsp->children[side^1]);
 }
References node_t::bbox, node_t::children, NF_SUBSECTOR, nodes, R_CheckBBox(), R_PointOnSide(), R_Subsector(), viewx, and viewy.
Referenced by R_RenderPlayerView().
R_StoreWallRange()
void R_StoreWallRange (int start, int stop)
Definition at line 372 of file r_segs.c.
 {
     fixed_t     hyp;
     fixed_t     sineval;
     angle_t     distangle, offsetangle;
     fixed_t     vtop;
     int         lightnum;
     // don't overflow and crash
     if (ds_p == &drawsegs[MAXDRAWSEGS])
     return;
 #ifdef RANGECHECK
     if (start >=viewwidth || start > stop)
     I_Error ("Bad R_RenderWallRange: %i to %i", start , stop);
 #endif
     sidedef = curline->sidedef;
     linedef = curline->linedef;
     // mark the segment as visible for auto map
     linedef->flags |= ML_MAPPED;
     // calculate rw_distance for scale calculation
     rw_normalangle = curline->angle + ANG90;
     offsetangle = abs(rw_normalangle-rw_angle1);
     if (offsetangle > ANG90)
     offsetangle = ANG90;
     distangle = ANG90 - offsetangle;
     hyp = R_PointToDist (curline->v1->x, curline->v1->y);
     sineval = finesine[distangle>>ANGLETOFINESHIFT];
     rw_distance = FixedMul (hyp, sineval);
     ds_p->x1 = rw_x = start;
     ds_p->x2 = stop;
     ds_p->curline = curline;
     rw_stopx = stop+1;
     // calculate scale at both ends and step
     ds_p->scale1 = rw_scale =
     R_ScaleFromGlobalAngle (viewangle + xtoviewangle[start]);
     if (stop > start )
     {
     ds_p->scale2 = R_ScaleFromGlobalAngle (viewangle + xtoviewangle[stop]);
     ds_p->scalestep = rw_scalestep =
         (ds_p->scale2 - rw_scale) / (stop-start);
     }
     else
     {
     // UNUSED: try to fix the stretched line bug
 #if 0
     if (rw_distance < FRACUNIT/2)
     {
         fixed_t     trx,try;
         fixed_t     gxt,gyt;
         trx = curline->v1->x - viewx;
         try = curline->v1->y - viewy;
         gxt = FixedMul(trx,viewcos);
         gyt = -FixedMul(try,viewsin);
         ds_p->scale1 = FixedDiv(projection, gxt-gyt)<<detailshift;
     }
 #endif
     ds_p->scale2 = ds_p->scale1;
     }
     // calculate texture boundaries
     //  and decide if floor / ceiling marks are needed
     worldtop = frontsector->ceilingheight - viewz;
     worldbottom = frontsector->floorheight - viewz;
     midtexture = toptexture = bottomtexture = maskedtexture = 0;
     ds_p->maskedtexturecol = NULL;
     if (!backsector)
     {
     // single sided line
     midtexture = texturetranslation[sidedef->midtexture];
     // a single sided line is terminal, so it must mark ends
     markfloor = markceiling = true;
     if (linedef->flags & ML_DONTPEGBOTTOM)
     {
         vtop = frontsector->floorheight +
         textureheight[sidedef->midtexture];
         // bottom of texture at bottom
         rw_midtexturemid = vtop - viewz;
     }
     else
     {
         // top of texture at top
         rw_midtexturemid = worldtop;
     }
     rw_midtexturemid += sidedef->rowoffset;
     ds_p->silhouette = SIL_BOTH;
     ds_p->sprtopclip = screenheightarray;
     ds_p->sprbottomclip = negonearray;
     ds_p->bsilheight = INT_MAX;
     ds_p->tsilheight = INT_MIN;
     }
     else
     {
     // two sided line
     ds_p->sprtopclip = ds_p->sprbottomclip = NULL;
     ds_p->silhouette = 0;
     if (frontsector->floorheight > backsector->floorheight)
     {
         ds_p->silhouette = SIL_BOTTOM;
         ds_p->bsilheight = frontsector->floorheight;
     }
     else if (backsector->floorheight > viewz)
     {
         ds_p->silhouette = SIL_BOTTOM;
         ds_p->bsilheight = INT_MAX;
         // ds_p->sprbottomclip = negonearray;
     }
     if (frontsector->ceilingheight < backsector->ceilingheight)
     {
         ds_p->silhouette |= SIL_TOP;
         ds_p->tsilheight = frontsector->ceilingheight;
     }
     else if (backsector->ceilingheight < viewz)
     {
         ds_p->silhouette |= SIL_TOP;
         ds_p->tsilheight = INT_MIN;
         // ds_p->sprtopclip = screenheightarray;
     }
     if (backsector->ceilingheight <= frontsector->floorheight)
     {
         ds_p->sprbottomclip = negonearray;
         ds_p->bsilheight = INT_MAX;
         ds_p->silhouette |= SIL_BOTTOM;
     }
     if (backsector->floorheight >= frontsector->ceilingheight)
     {
         ds_p->sprtopclip = screenheightarray;
         ds_p->tsilheight = INT_MIN;
         ds_p->silhouette |= SIL_TOP;
     }
     worldhigh = backsector->ceilingheight - viewz;
     worldlow = backsector->floorheight - viewz;
     // hack to allow height changes in outdoor areas
     if (frontsector->ceilingpic == skyflatnum
         && backsector->ceilingpic == skyflatnum)
     {
         worldtop = worldhigh;
     }
     if (worldlow != worldbottom
         || backsector->floorpic != frontsector->floorpic
         || backsector->lightlevel != frontsector->lightlevel)
     {
         markfloor = true;
     }
     else
     {
         // same plane on both sides
         markfloor = false;
     }
     if (worldhigh != worldtop
         || backsector->ceilingpic != frontsector->ceilingpic
         || backsector->lightlevel != frontsector->lightlevel)
     {
         markceiling = true;
     }
     else
     {
         // same plane on both sides
         markceiling = false;
     }
     if (backsector->ceilingheight <= frontsector->floorheight
         || backsector->floorheight >= frontsector->ceilingheight)
     {
         // closed door
         markceiling = markfloor = true;
     }
     if (worldhigh < worldtop)
     {
         // top texture
         toptexture = texturetranslation[sidedef->toptexture];
         if (linedef->flags & ML_DONTPEGTOP)
         {
         // top of texture at top
         rw_toptexturemid = worldtop;
         }
         else
         {
         vtop =
             backsector->ceilingheight
             + textureheight[sidedef->toptexture];
         // bottom of texture
         rw_toptexturemid = vtop - viewz;
         }
     }
     if (worldlow > worldbottom)
     {
         // bottom texture
         bottomtexture = texturetranslation[sidedef->bottomtexture];
         if (linedef->flags & ML_DONTPEGBOTTOM )
         {
         // bottom of texture at bottom
         // top of texture at top
         rw_bottomtexturemid = worldtop;
         }
         else    // top of texture at top
         rw_bottomtexturemid = worldlow;
     }
     rw_toptexturemid += sidedef->rowoffset;
     rw_bottomtexturemid += sidedef->rowoffset;
     // allocate space for masked texture tables
     if (sidedef->midtexture)
     {
         // masked midtexture
         maskedtexture = true;
         ds_p->maskedtexturecol = maskedtexturecol = lastopening - rw_x;
         lastopening += rw_stopx - rw_x;
     }
     }
     // calculate rw_offset (only needed for textured lines)
     segtextured = midtexture | toptexture | bottomtexture | maskedtexture;
     if (segtextured)
     {
     offsetangle = rw_normalangle-rw_angle1;
     if (offsetangle > ANG180)
         offsetangle = -offsetangle;
     if (offsetangle > ANG90)
         offsetangle = ANG90;
     sineval = finesine[offsetangle >>ANGLETOFINESHIFT];
     rw_offset = FixedMul (hyp, sineval);
     if (rw_normalangle-rw_angle1 < ANG180)
         rw_offset = -rw_offset;
     rw_offset += sidedef->textureoffset + curline->offset;
     rw_centerangle = ANG90 + viewangle - rw_normalangle;
     // calculate light table
     //  use different light tables
     //  for horizontal / vertical / diagonal
     // OPTIMIZE: get rid of LIGHTSEGSHIFT globally
     if (!fixedcolormap)
     {
         lightnum = (frontsector->lightlevel >> LIGHTSEGSHIFT)+extralight;
         if (curline->v1->y == curline->v2->y)
         lightnum--;
         else if (curline->v1->x == curline->v2->x)
         lightnum++;
         if (lightnum < 0)
         walllights = scalelight[0];
         else if (lightnum >= LIGHTLEVELS)
         walllights = scalelight[LIGHTLEVELS-1];
         else
         walllights = scalelight[lightnum];
     }
     }
     // if a floor / ceiling plane is on the wrong side
     //  of the view plane, it is definitely invisible
     //  and doesn't need to be marked.
     if (frontsector->floorheight >= viewz)
     {
     // above view plane
     markfloor = false;
     }
     if (frontsector->ceilingheight <= viewz
     && frontsector->ceilingpic != skyflatnum)
     {
     // below view plane
     markceiling = false;
     }
     // calculate incremental stepping values for texture edges
     worldtop >>= 4;
     worldbottom >>= 4;
     topstep = -FixedMul (rw_scalestep, worldtop);
     topfrac = (centeryfrac>>4) - FixedMul (worldtop, rw_scale);
     bottomstep = -FixedMul (rw_scalestep,worldbottom);
     bottomfrac = (centeryfrac>>4) - FixedMul (worldbottom, rw_scale);
     if (backsector)
     {
     worldhigh >>= 4;
     worldlow >>= 4;
     if (worldhigh < worldtop)
     {
         pixhigh = (centeryfrac>>4) - FixedMul (worldhigh, rw_scale);
         pixhighstep = -FixedMul (rw_scalestep,worldhigh);
     }
     if (worldlow > worldbottom)
     {
         pixlow = (centeryfrac>>4) - FixedMul (worldlow, rw_scale);
         pixlowstep = -FixedMul (rw_scalestep,worldlow);
     }
     }
     // render it
     if (markceiling)
     ceilingplane = R_CheckPlane (ceilingplane, rw_x, rw_stopx-1);
     if (markfloor)
     floorplane = R_CheckPlane (floorplane, rw_x, rw_stopx-1);
     R_RenderSegLoop ();
     // save sprite clipping info
     if ( ((ds_p->silhouette & SIL_TOP) || maskedtexture)
      && !ds_p->sprtopclip)
     {
     memcpy (lastopening, ceilingclip+start, 2*(rw_stopx-start));
     ds_p->sprtopclip = lastopening - start;
     lastopening += rw_stopx - start;
     }
     if ( ((ds_p->silhouette & SIL_BOTTOM) || maskedtexture)
      && !ds_p->sprbottomclip)
     {
     memcpy (lastopening, floorclip+start, 2*(rw_stopx-start));
     ds_p->sprbottomclip = lastopening - start;
     lastopening += rw_stopx - start;
     }
     if (maskedtexture && !(ds_p->silhouette&SIL_TOP))
     {
     ds_p->silhouette |= SIL_TOP;
     ds_p->tsilheight = INT_MIN;
     }
     if (maskedtexture && !(ds_p->silhouette&SIL_BOTTOM))
     {
     ds_p->silhouette |= SIL_BOTTOM;
     ds_p->bsilheight = INT_MAX;
     }
     ds_p++;
 }
References abs(), ANG180, ANG90, seg_t::angle, ANGLETOFINESHIFT, backsector, bottomfrac, bottomstep, side_t::bottomtexture, bottomtexture, drawseg_s::bsilheight, ceilingclip, sector_t::ceilingheight, sector_t::ceilingpic, ceilingplane, centeryfrac, curline, drawseg_s::curline, detailshift, drawsegs, ds_p, extralight, finesine, fixedcolormap, FixedDiv(), FixedMul(), line_s::flags, floorclip, sector_t::floorheight, sector_t::floorpic, floorplane, FRACUNIT, frontsector, I_Error(), INT_MAX, INT_MIN, lastopening, sector_t::lightlevel, LIGHTLEVELS, LIGHTSEGSHIFT, linedef, seg_t::linedef, markceiling, markfloor, maskedtexture, drawseg_s::maskedtexturecol, maskedtexturecol, MAXDRAWSEGS, memcpy, side_t::midtexture, midtexture, ML_DONTPEGBOTTOM, ML_DONTPEGTOP, ML_MAPPED, negonearray, NULL, seg_t::offset, pixhigh, pixhighstep, pixlow, pixlowstep, projection, R_CheckPlane(), R_PointToDist(), R_RenderSegLoop(), R_ScaleFromGlobalAngle(), side_t::rowoffset, rw_angle1, rw_bottomtexturemid, rw_centerangle, rw_distance, rw_midtexturemid, rw_normalangle, rw_offset, rw_scale, rw_scalestep, rw_stopx, rw_toptexturemid, rw_x, drawseg_s::scale1, drawseg_s::scale2, scalelight, drawseg_s::scalestep, screenheightarray, segtextured, sidedef, seg_t::sidedef, SIL_BOTH, SIL_BOTTOM, SIL_TOP, drawseg_s::silhouette, skyflatnum, drawseg_s::sprbottomclip, drawseg_s::sprtopclip, textureheight, side_t::textureoffset, texturetranslation, topfrac, topstep, side_t::toptexture, toptexture, drawseg_s::tsilheight, seg_t::v1, seg_t::v2, viewangle, viewcos, viewsin, viewwidth, viewx, viewy, viewz, walllights, worldbottom, worldhigh, worldlow, worldtop, vertex_t::x, drawseg_s::x1, drawseg_s::x2, xtoviewangle, and vertex_t::y.
Referenced by R_ClipPassWallSegment(), and R_ClipSolidWallSegment().
R_Subsector()
void R_Subsector (int num)
Definition at line 490 of file r_bsp.c.
 {
     int         count;
     seg_t*      line;
     subsector_t*    sub;
 #ifdef RANGECHECK
     if (num>=numsubsectors)
     I_Error ("R_Subsector: ss %i with numss = %i",
          num,
          numsubsectors);
 #endif
     sscount++;
     sub = &subsectors[num];
     frontsector = sub->sector;
     count = sub->numlines;
     line = &segs[sub->firstline];
     if (frontsector->floorheight < viewz)
     {
     floorplane = R_FindPlane (frontsector->floorheight,
                   frontsector->floorpic,
                   frontsector->lightlevel);
     }
     else
     floorplane = NULL;
     if (frontsector->ceilingheight > viewz
     || frontsector->ceilingpic == skyflatnum)
     {
     ceilingplane = R_FindPlane (frontsector->ceilingheight,
                     frontsector->ceilingpic,
                     frontsector->lightlevel);
     }
     else
     ceilingplane = NULL;
     R_AddSprites (frontsector);
     while (count--)
     {
     R_AddLine (line);
     line++;
     }
 }
References sector_t::ceilingheight, sector_t::ceilingpic, ceilingplane, mlibc::count, subsector_s::firstline, sector_t::floorheight, sector_t::floorpic, floorplane, frontsector, I_Error(), sector_t::lightlevel, NULL, num, subsector_s::numlines, numsubsectors, R_AddLine(), R_AddSprites(), R_FindPlane(), subsector_s::sector, segs, skyflatnum, sscount, subsectors, and viewz.
Referenced by R_RenderBSPNode().
Variable Documentation
backsector
sector_t* backsector
Definition at line 44 of file r_bsp.c.
Referenced by AM_drawWalls(), EV_BuildStairs(), R_AddLine(), R_RenderMaskedSegRange(), and R_StoreWallRange().
checkcoord
int checkcoord[12][4]
Initial value:
=
{
    {3,0,2,1},
    {3,0,2,0},
    {3,1,2,0},
    {0},
    {2,0,2,1},
    {0,0,0,0},
    {3,1,3,0},
    {0},
    {2,0,3,1},
    {2,1,3,1},
    {2,1,3,0}
}
Definition at line 358 of file r_bsp.c.
Referenced by R_CheckBBox().
curline
seg_t* curline
Definition at line 40 of file r_bsp.c.
Referenced by R_AddLine(), R_RenderMaskedSegRange(), and R_StoreWallRange().
drawsegs
drawseg_t drawsegs[MAXDRAWSEGS]
Definition at line 46 of file r_bsp.c.
Referenced by R_ClearDrawSegs(), R_DrawMasked(), R_DrawPlanes(), R_DrawSprite(), and R_StoreWallRange().
ds_p
drawseg_t* ds_p
Definition at line 47 of file r_bsp.c.
Referenced by R_ClearDrawSegs(), R_DrawMasked(), R_DrawPlanes(), R_DrawSprite(), and R_StoreWallRange().
frontsector
sector_t* frontsector
Definition at line 43 of file r_bsp.c.
Referenced by EV_BuildStairs(), R_AddLine(), R_RenderMaskedSegRange(), R_StoreWallRange(), and R_Subsector().
linedef
line_t* linedef
Definition at line 42 of file r_bsp.c.
Referenced by P_LineOpening(), P_LoadSegs(), and R_StoreWallRange().
newend
cliprange_t* newend
Definition at line 84 of file r_bsp.c.
Referenced by R_ClearClipSegs(), and R_ClipSolidWallSegment().
sidedef
side_t* sidedef
Definition at line 41 of file r_bsp.c.
Referenced by R_StoreWallRange().
solidsegs
cliprange_t solidsegs[MAXSEGS]
Definition at line 85 of file r_bsp.c.
Referenced by R_CheckBBox(), R_ClearClipSegs(), R_ClipPassWallSegment(), and R_ClipSolidWallSegment().