Fennix Userspace: Userspace/apps/base/busybox/modutils/insmod.c File Reference
insmod.c File Reference
#include "libbb.h"
#include "modutils.h"
Functions
int insmod_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
insmod_main()
int insmod_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 48 of file insmod.c.
 {
     char *filename;
     int rc;
     /* Compat note:
      * 2.6 style insmod has no options and required filename
      * (not module name - .ko can't be omitted).
      * 2.4 style insmod can take module name without .o
      * and performs module search in default directories
      * or in $MODPATH.
      */
     IF_FEATURE_2_4_MODULES(
         getopt32(argv, INSMOD_OPTS INSMOD_ARGS);
         argv += optind - 1;
     );
     filename = *++argv;
     if (!filename)
         bb_show_usage();
     rc = bb_init_module(filename, parse_cmdline_module_options(argv, /*quote_spaces:*/ 0));
     if (rc)
         bb_error_msg("can't insert '%s': %s", filename, moderror(rc));
     return rc;
 }
References argv, bb_error_msg(), bb_init_module(), bb_show_usage(), filename, getopt32(), INSMOD_ARGS, INSMOD_OPTS, moderror(), optind, parse_cmdline_module_options, and rc.