Fennix: Userspace/apps/base/busybox/procps/pmap.c File Reference
pmap.c File Reference
#include "libbb.h"
Macros
#define TABS "\t\t"
#define AFMTLL "16"
#define DASHES "--------"
Enumerations
enum { OPT_x = 1 << 0 , OPT_q = 1 << 1 }
Functions
static void print_smaprec (struct smaprec *currec, void *data)
static int procps_get_maps (pid_t pid, unsigned opt)
int pmap_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
AFMTLL
#define AFMTLL "16"
Definition at line 36 of file pmap.c.
DASHES
#define DASHES "--------"
Definition at line 37 of file pmap.c.
TABS
#define TABS "\t\t"
Definition at line 35 of file pmap.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_x
OPT_q
Definition at line 40 of file pmap.c.
      {
     OPT_x = 1 << 0,
     OPT_q = 1 << 1,
 };
Function Documentation
pmap_main()
int pmap_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 94 of file pmap.c.
 {
     unsigned opts;
     int ret;
     opts = getopt32(argv, "^" "xq" "\0" "-1"); /* min one arg */
     argv += optind;
     ret = 0;
     while (*argv) {
         pid_t pid = xatoi_positive(*argv++);
         /* GNU pmap returns 42 if any of the pids failed */
         if (procps_get_maps(pid, opts) != 0)
             ret = 42;
     }
     return ret;
 }
References argv, getopt32(), optind, pid, procps_get_maps(), and xatoi_positive().
print_smaprec()
static void print_smaprec (struct smaprec * currec, void * data) static
Definition at line 45 of file pmap.c.
 {
     unsigned opt = (uintptr_t)data;
     printf("%0" AFMTLL "llx ", currec->smap_start);
     if (opt & OPT_x)
         printf("%7lu %7lu %7lu %7lu ",
             currec->smap_size,
             currec->smap_pss,
             currec->private_dirty,
             currec->smap_swap);
     else
         printf("%7luK", currec->smap_size);
     printf(" %.4s  %s\n", currec->smap_mode, currec->smap_name);
 }
References AFMTLL, opt, OPT_x, printf, smaprec::private_dirty, smaprec::smap_mode, smaprec::smap_name, smaprec::smap_pss, smaprec::smap_size, smaprec::smap_start, and smaprec::smap_swap.
Referenced by procps_get_maps().
procps_get_maps()
static int procps_get_maps (pid_t pid, unsigned opt) static
Definition at line 63 of file pmap.c.
 {
     struct smaprec total;
     int ret;
     char buf[256];
     read_cmdline(buf, sizeof(buf), pid, NULL);
     printf("%u: %s\n", (int)pid, buf);
     if (!(opt & OPT_q) && (opt & OPT_x))
         puts("Address" TABS "  Kbytes     PSS   Dirty    Swap  Mode  Mapping");
     memset(&total, 0, sizeof(total));
     ret = procps_read_smaps(pid, &total, print_smaprec, (void*)(uintptr_t)opt);
     if (ret)
         return ret;
     if (!(opt & OPT_q)) {
         if (opt & OPT_x)
             printf("--------" DASHES "  ------  ------  ------  ------\n"
                 "total" TABS " %7lu %7lu %7lu %7lu\n",
                 total.smap_size, total.smap_pss, total.private_dirty, total.smap_swap);
         else
             printf("mapped: %luK\n", total.smap_size);
     }
     return 0;
 }
References buf, DASHES, memset, NULL, opt, OPT_q, OPT_x, pid, print_smaprec(), printf, procps_read_smaps(), puts(), read_cmdline(), TABS, and total.
Referenced by pmap_main().