Fennix Userspace: Userspace/apps/base/busybox/coreutils/seq.c File Reference
seq.c File Reference
#include "libbb.h"
Functions
int seq_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
seq_main()
int seq_main (int argc, char ** argv)
Definition at line 33 of file seq.c.
 {
     enum {
         OPT_w = (1 << 0),
         OPT_s = (1 << 1),
     };
     double first, last, increment, v;
     unsigned n;
     unsigned width;
     unsigned frac_part;
     const char *sep, *opt_s = "\n";
     unsigned opt;
 #if ENABLE_LOCALE_SUPPORT
     /* Undo busybox.c: on input, we want to use dot
      * as fractional separator, regardless of current locale */
     setlocale(LC_NUMERIC, "C");
 #endif
     opt = getopt32(argv, "+ws:", &opt_s);
     argc -= optind;
     argv += optind;
     first = increment = 1;
     errno = 0;
     switch (argc) {
             char *pp;
         case 3:
             increment = strtod(argv[1], &pp);
             errno |= *pp;
         case 2:
             first = strtod(argv[0], &pp);
             errno |= *pp;
         case 1:
             last = strtod(argv[argc-1], &pp);
             if (!errno && *pp == '\0')
                 break;
         default:
             bb_show_usage();
     }
 #if ENABLE_LOCALE_SUPPORT
     setlocale(LC_NUMERIC, "");
 #endif
     /* Last checked to be compatible with: coreutils-6.10 */
     width = 0;
     frac_part = 0;
     while (1) {
         char *dot = strchrnul(*argv, '.');
         int w = (dot - *argv);
         int f = strlen(dot);
         if (width < w)
             width = w;
         argv++;
         if (!*argv)
             break;
         /* Why do the above _before_ frac check below?
          * Try "seq 1 2.0" and "seq 1.0 2.0":
          * coreutils never pay attention to the number
          * of fractional digits in last arg. */
         if (frac_part < f)
             frac_part = f;
     }
     if (frac_part) {
         frac_part--;
         if (frac_part)
             width += frac_part + 1;
     }
     if (!(opt & OPT_w))
         width = 0;
     sep = "";
     v = first;
     n = 0;
     while (increment >= 0 ? v <= last : v >= last) {
         if (printf("%s%0*.*f", sep, width, frac_part, v) < 0)
             break; /* I/O error, bail out (yes, this really happens) */
         sep = opt_s;
         /* v += increment; - would accumulate floating point errors */
         n++;
         v = first + n * increment;
     }
     if (n) /* if while loop executed at least once */
         bb_putchar('\n');
     return fflush_all();
 }
References argc, argv, bb_putchar(), bb_show_usage(), dot, errno, f, fflush_all(), first, getopt32(), last, LC_NUMERIC, n, opt, OPT_s, OPT_w, optind, printf(), setlocale, strchrnul(), strlen(), strtod(), w, and width.