Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/i_video.h File Reference
i_video.h File Reference
#include "doomtype.h"
Data Structures
struct screen_mode_t
Macros
#define SCREENWIDTH 320
#define SCREENHEIGHT 200
#define SCREENWIDTH_4_3 256
#define SCREENHEIGHT_4_3 240
#define MAX_MOUSE_BUTTONS 8
Typedefs
typedef boolean(* grabmouse_callback_t) (void)
Functions
void I_InitGraphics (void)
void I_GraphicsCheckCommandLine (void)
void I_ShutdownGraphics (void)
void I_SetPalette (byte *palette)
int I_GetPaletteIndex (int r, int g, int b)
void I_UpdateNoBlit (void)
void I_FinishUpdate (void)
void I_ReadScreen (byte *scr)
void I_BeginRead (void)
void I_SetWindowTitle (char *title)
void I_CheckIsScreensaver (void)
void I_SetGrabMouseCallback (grabmouse_callback_t func)
void I_DisplayFPSDots (boolean dots_on)
void I_BindVideoVariables (void)
void I_InitWindowTitle (void)
void I_InitWindowIcon (void)
void I_StartFrame (void)
void I_StartTic (void)
void I_EnableLoadingDisk (void)
void I_EndRead (void)
Variables
char * video_driver
boolean screenvisible
float mouse_acceleration
int mouse_threshold
int vanilla_keyboard_mapping
boolean screensaver_mode
int usegamma
byte * I_VideoBuffer
int screen_width
int screen_height
int screen_bpp
int fullscreen
int aspect_ratio_correct
int show_diskicon
int diskicon_readbytes
Macro Definition Documentation
MAX_MOUSE_BUTTONS
#define MAX_MOUSE_BUTTONS 8
Definition at line 38 of file i_video.h.
SCREENHEIGHT
#define SCREENHEIGHT 200
Definition at line 28 of file i_video.h.
SCREENHEIGHT_4_3
#define SCREENHEIGHT_4_3 240
Definition at line 36 of file i_video.h.
SCREENWIDTH
#define SCREENWIDTH 320
Definition at line 27 of file i_video.h.
SCREENWIDTH_4_3
#define SCREENWIDTH_4_3 256
Definition at line 32 of file i_video.h.
Typedef Documentation
grabmouse_callback_t
typedef boolean(* grabmouse_callback_t) (void)
Definition at line 92 of file i_video.h.
Function Documentation
I_BeginRead()
void I_BeginRead (void)
Definition at line 379 of file i_video.c.
 {
 }
Referenced by W_ReadLump().
I_BindVideoVariables()
void I_BindVideoVariables (void)
Definition at line 404 of file i_video.c.
 {
 }
Referenced by D_BindVariables().
I_CheckIsScreensaver()
void I_CheckIsScreensaver (void)
Definition at line 412 of file i_video.c.
 {
 }
Referenced by D_DoomMain().
I_DisplayFPSDots()
void I_DisplayFPSDots (boolean dots_on)
Definition at line 408 of file i_video.c.
 {
 }
Referenced by D_DoomMain().
I_EnableLoadingDisk()
void I_EnableLoadingDisk (void)
Definition at line 400 of file i_video.c.
 {
 }
Referenced by D_DoomLoop().
I_EndRead()
void I_EndRead (void)
Definition at line 383 of file i_video.c.
 {
 }
Referenced by W_ReadLump().
I_FinishUpdate()
void I_FinishUpdate (void)
Definition at line 253 of file i_video.c.
 {
     int y;
     int x_offset, y_offset, x_offset_end;
     unsigned char *line_in, *line_out;
     /* Offsets in case FB is bigger than DOOM */
     /* 600 = s_Fb heigt, 200 screenheight */
     /* 600 = s_Fb heigt, 200 screenheight */
     /* 2048 =s_Fb width, 320 screenwidth */
     y_offset     = (((s_Fb.yres - (SCREENHEIGHT * fb_scaling)) * s_Fb.bits_per_pixel/8)) / 2;
     x_offset     = (((s_Fb.xres - (SCREENWIDTH  * fb_scaling)) * s_Fb.bits_per_pixel/8)) / 2; // XXX: siglent FB hack: /4 instead of /2, since it seems to handle the resolution in a funny way
     //x_offset     = 0;
     x_offset_end = ((s_Fb.xres - (SCREENWIDTH  * fb_scaling)) * s_Fb.bits_per_pixel/8) - x_offset;
     /* DRAW SCREEN */
     line_in  = (unsigned char *) I_VideoBuffer;
     line_out = (unsigned char *) DG_ScreenBuffer;
     y = SCREENHEIGHT;
     while (y--)
     {
         int i;
         for (i = 0; i < fb_scaling; i++) {
             line_out += x_offset;
 #ifdef CMAP256
             for (fb_scaling == 1) {
                 memcpy(line_out, line_in, SCREENWIDTH); /* fb_width is bigger than Doom SCREENWIDTH... */
             } else {
                 //XXX FIXME fb_scaling support!
             }
 #else
             //cmap_to_rgb565((void*)line_out, (void*)line_in, SCREENWIDTH);
             cmap_to_fb((void*)line_out, (void*)line_in, SCREENWIDTH);
 #endif
             line_out += (SCREENWIDTH * fb_scaling * (s_Fb.bits_per_pixel/8)) + x_offset_end;
         }
         line_in += SCREENWIDTH;
     }
     DG_DrawFrame();
 }
References FB_ScreenInfo::bits_per_pixel, cmap_to_fb(), DG_DrawFrame(), DG_ScreenBuffer, fb_scaling, i, I_VideoBuffer, memcpy, s_Fb, SCREENHEIGHT, SCREENWIDTH, FB_ScreenInfo::xres, y, and FB_ScreenInfo::yres.
Referenced by D_Display().
I_GetPaletteIndex()
int I_GetPaletteIndex (int r, int g, int b)
Definition at line 343 of file i_video.c.
 {
     int best, best_diff, diff;
     int i;
     col_t color;
     printf("I_GetPaletteIndex\n");
     best = 0;
     best_diff = __INT_MAX__;
     for (i = 0; i < 256; ++i)
     {
         color.r = GFX_RGB565_R(rgb565_palette[i]);
         color.g = GFX_RGB565_G(rgb565_palette[i]);
         color.b = GFX_RGB565_B(rgb565_palette[i]);
         diff = (r - color.r) * (r - color.r)
              + (g - color.g) * (g - color.g)
              + (b - color.b) * (b - color.b);
         if (diff < best_diff)
         {
             best = i;
             best_diff = diff;
         }
         if (diff == 0)
         {
             break;
         }
     }
     return best;
 }
References color::b, color, diff(), g, color::g, GFX_RGB565_B, GFX_RGB565_G, GFX_RGB565_R, i, printf, color::r, and rgb565_palette.
Referenced by V_DrawMouseSpeedBox().
I_GraphicsCheckCommandLine()
void I_GraphicsCheckCommandLine (void)
Definition at line 392 of file i_video.c.
 {
 }
Referenced by D_DoomLoop().
I_InitGraphics()
void I_InitGraphics (void)
Definition at line 177 of file i_video.c.
 {
     int i;
     memset(&s_Fb, 0, sizeof(struct FB_ScreenInfo));
     s_Fb.xres = DOOMGENERIC_RESX;
     s_Fb.yres = DOOMGENERIC_RESY;
     s_Fb.xres_virtual = s_Fb.xres;
     s_Fb.yres_virtual = s_Fb.yres;
     s_Fb.bits_per_pixel = 32;
     s_Fb.blue.length = 8;
     s_Fb.green.length = 8;
     s_Fb.red.length = 8;
     s_Fb.transp.length = 8;
     s_Fb.blue.offset = 0;
     s_Fb.green.offset = 8;
     s_Fb.red.offset = 16;
     s_Fb.transp.offset = 24;
     printf("I_InitGraphics: framebuffer: x_res: %d, y_res: %d, x_virtual: %d, y_virtual: %d, bpp: %d\n",
             s_Fb.xres, s_Fb.yres, s_Fb.xres_virtual, s_Fb.yres_virtual, s_Fb.bits_per_pixel);
     printf("I_InitGraphics: framebuffer: RGBA: %d%d%d%d, red_off: %d, green_off: %d, blue_off: %d, transp_off: %d\n",
             s_Fb.red.length, s_Fb.green.length, s_Fb.blue.length, s_Fb.transp.length, s_Fb.red.offset, s_Fb.green.offset, s_Fb.blue.offset, s_Fb.transp.offset);
     printf("I_InitGraphics: DOOM screen size: w x h: %d x %d\n", SCREENWIDTH, SCREENHEIGHT);
     i = M_CheckParmWithArgs("-scaling", 1);
     if (i > 0) {
         i = atoi(myargv[i + 1]);
         fb_scaling = i;
         printf("I_InitGraphics: Scaling factor: %d\n", fb_scaling);
     } else {
         fb_scaling = s_Fb.xres / SCREENWIDTH;
         if (s_Fb.yres / SCREENHEIGHT < fb_scaling)
             fb_scaling = s_Fb.yres / SCREENHEIGHT;
         printf("I_InitGraphics: Auto-scaling factor: %d\n", fb_scaling);
     }
     /* Allocate screen to draw to */
     I_VideoBuffer = (byte*)Z_Malloc (SCREENWIDTH * SCREENHEIGHT, PU_STATIC, NULL);  // For DOOM to draw on
     screenvisible = true;
     extern int I_InitInput(void);
     I_InitInput();
 }
References atoi(), FB_ScreenInfo::bits_per_pixel, FB_ScreenInfo::blue, DOOMGENERIC_RESX, DOOMGENERIC_RESY, fb_scaling, FB_ScreenInfo::green, i, I_InitInput(), I_VideoBuffer, FB_BitField::length, M_CheckParmWithArgs(), memset, myargv, NULL, FB_BitField::offset, printf, PU_STATIC, FB_ScreenInfo::red, s_Fb, SCREENHEIGHT, screenvisible, SCREENWIDTH, FB_ScreenInfo::transp, FB_ScreenInfo::xres, FB_ScreenInfo::xres_virtual, FB_ScreenInfo::yres, FB_ScreenInfo::yres_virtual, and Z_Malloc().
Referenced by D_DoomLoop().
I_InitWindowIcon()
void I_InitWindowIcon (void)
Referenced by I_Endoom().
I_InitWindowTitle()
void I_InitWindowTitle (void)
Referenced by I_Endoom().
I_ReadScreen()
void I_ReadScreen (byte * scr)
Definition at line 300 of file i_video.c.
 {
     memcpy (scr, I_VideoBuffer, SCREENWIDTH * SCREENHEIGHT);
 }
References I_VideoBuffer, memcpy, SCREENHEIGHT, and SCREENWIDTH.
Referenced by wipe_EndScreen(), and wipe_StartScreen().
I_SetGrabMouseCallback()
void I_SetGrabMouseCallback (grabmouse_callback_t func)
Definition at line 396 of file i_video.c.
 {
 }
Referenced by D_DoomLoop().
I_SetPalette()
void I_SetPalette (byte * palette)
Definition at line 313 of file i_video.c.
 {
     int i;
     //col_t* c;
     //for (i = 0; i < 256; i++)
     //{
     //  c = (col_t*)palette;
     //  rgb565_palette[i] = GFX_RGB565(gammatable[usegamma][c->r],
     //                                 gammatable[usegamma][c->g],
     //                                 gammatable[usegamma][c->b]);
     //  palette += 3;
     //}
     /* performance boost:
      * map to the right pixel format over here! */
     for (i=0; i<256; ++i ) {
         colors[i].a = 0;
         colors[i].r = gammatable[usegamma][*palette++];
         colors[i].g = gammatable[usegamma][*palette++];
         colors[i].b = gammatable[usegamma][*palette++];
     }
 }
References color::a, color::b, colors, color::g, gammatable, i, color::r, and usegamma.
Referenced by D_Display(), M_Responder(), ST_doPaletteStuff(), and ST_Stop().
I_SetWindowTitle()
void I_SetWindowTitle (char * title)
Definition at line 387 of file i_video.c.
 {
     DG_SetWindowTitle(title);
 }
References DG_SetWindowTitle(), and title.
Referenced by D_DoomLoop().
I_ShutdownGraphics()
void I_ShutdownGraphics (void)
Definition at line 230 of file i_video.c.
 {
     Z_Free (I_VideoBuffer);
 }
References I_VideoBuffer, and Z_Free().
I_StartFrame()
void I_StartFrame (void)
Definition at line 235 of file i_video.c.
 {
 }
Referenced by doomgeneric_Tick().
I_StartTic()
void I_StartTic (void)
Definition at line 240 of file i_video.c.
 {
     I_GetEvent();
 }
References I_GetEvent().
Referenced by BuildNewTic().
I_UpdateNoBlit()
void I_UpdateNoBlit (void)
Definition at line 245 of file i_video.c.
 {
 }
Referenced by D_Display().
Variable Documentation
aspect_ratio_correct
int aspect_ratio_correct extern
diskicon_readbytes
int diskicon_readbytes extern
fullscreen
int fullscreen extern
Referenced by D_Display(), and ST_Drawer().
I_VideoBuffer
byte* I_VideoBuffer extern
Definition at line 91 of file i_video.c.
Referenced by AM_initVariables(), F_DrawPatchCol(), F_TextWrite(), I_FinishUpdate(), I_InitGraphics(), I_ReadScreen(), I_ShutdownGraphics(), R_InitBuffer(), R_VideoErase(), V_DrawFilledBox(), V_DrawHorizLine(), V_DrawVertLine(), V_MarkRect(), V_RestoreBuffer(), V_ScreenShot(), and wipe_ScreenWipe().
mouse_acceleration
float mouse_acceleration extern
Definition at line 111 of file i_video.c.
Referenced by V_DrawMouseSpeedBox().
mouse_threshold
int mouse_threshold extern
Definition at line 112 of file i_video.c.
Referenced by V_DrawMouseSpeedBox().
screen_bpp
int screen_bpp extern
screen_height
int screen_height extern
screen_width
int screen_width extern
screensaver_mode
boolean screensaver_mode extern
Definition at line 95 of file i_video.c.
Referenced by D_Endoom(), and I_InitSound().
screenvisible
boolean screenvisible extern
Definition at line 100 of file i_video.c.
Referenced by doomgeneric_Tick(), and I_InitGraphics().
show_diskicon
int show_diskicon extern
usegamma
int usegamma extern
Definition at line 116 of file i_video.c.
Referenced by I_SetPalette(), and M_Responder().
vanilla_keyboard_mapping
int vanilla_keyboard_mapping extern
Definition at line 44 of file i_input.c.
Referenced by M_Responder().
video_driver
char* video_driver extern