Fennix: Userspace/mlibc/tests/posix/pthread_mutex.c File Reference
pthread_mutex.c File Reference
#include <pthread.h>
#include <assert.h>
#include <errno.h>
Macros
#define TEST_ATTR(attr, field, value)
Functions
static void * worker (void *arg)
static void testAttr ()
static void testNormal ()
static void testRecursive ()
int main ()
Variables
int variable
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
TEST_ATTR
#define TEST_ATTR (attr, field, value)
Value:
        ({ \
        int x; \
        assert(!pthread_mutexattr_set ## field (&(attr), (value))); \
        assert(!pthread_mutexattr_get ## field (&(attr), &x)); \
        assert(x == (value)); \
    })
Definition at line 5 of file pthread_mutex.c.
Function Documentation
main()
int main (void)
Definition at line 97 of file pthread_mutex.c.
            {
     testAttr();
     testNormal();
     testRecursive();
 }
References testAttr(), testNormal(), and testRecursive().
testAttr()
static void testAttr () static
Definition at line 23 of file pthread_mutex.c.
{
     pthread_mutexattr_t attr;
     pthread_mutexattr_init(&attr);
     TEST_ATTR(attr, type, PTHREAD_MUTEX_DEFAULT);
     TEST_ATTR(attr, type, PTHREAD_MUTEX_NORMAL);
     TEST_ATTR(attr, type, PTHREAD_MUTEX_ERRORCHECK);
     TEST_ATTR(attr, type, PTHREAD_MUTEX_RECURSIVE);
     TEST_ATTR(attr, robust, PTHREAD_MUTEX_STALLED);
     TEST_ATTR(attr, robust, PTHREAD_MUTEX_ROBUST);
     TEST_ATTR(attr, protocol, PTHREAD_PRIO_NONE);
     TEST_ATTR(attr, protocol, PTHREAD_PRIO_INHERIT);
     TEST_ATTR(attr, protocol, PTHREAD_PRIO_PROTECT);
     TEST_ATTR(attr, pshared, PTHREAD_PROCESS_PRIVATE);
     TEST_ATTR(attr, pshared, PTHREAD_PROCESS_SHARED);
     // TODO: sched_get_priority* is unimplemented.
     // int prio = sched_get_priority_max(SCHED_FIFO);
     // TEST_ATTR(attr, prioceiling, prio);
     pthread_mutexattr_destroy(&attr);
 }
References mlibc::attr, PTHREAD_MUTEX_DEFAULT, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_NORMAL, PTHREAD_MUTEX_RECURSIVE, PTHREAD_MUTEX_ROBUST, PTHREAD_MUTEX_STALLED, pthread_mutexattr_destroy(), pthread_mutexattr_init(), PTHREAD_PRIO_INHERIT, PTHREAD_PRIO_NONE, PTHREAD_PRIO_PROTECT, PTHREAD_PROCESS_PRIVATE, PTHREAD_PROCESS_SHARED, TEST_ATTR, and type.
Referenced by main().
testNormal()
static void testNormal () static
Definition at line 49 of file pthread_mutex.c.
{
     pthread_mutexattr_t attr;
     pthread_mutexattr_init(&attr);
     pthread_mutex_init(&mutex, &attr);
     pthread_mutexattr_destroy(&attr);
     pthread_mutex_lock(&mutex);
     variable = 0;
     pthread_t thread;
     int ret = pthread_create(&thread, NULL, &worker, NULL);
     assert(!ret);
     assert(pthread_mutex_trylock(&mutex) == EBUSY);
     pthread_mutex_unlock(&mutex);
     ret = pthread_join(thread, NULL);
     assert(!ret);
     assert(variable == 1);
     pthread_mutex_destroy(&mutex);
 }
References assert, mlibc::attr, EBUSY, mutex, NULL, pthread_create(), pthread_join(), pthread_mutex_destroy(), pthread_mutex_init(), pthread_mutex_lock(), pthread_mutex_trylock(), pthread_mutex_unlock(), pthread_mutexattr_destroy(), pthread_mutexattr_init(), ret, variable, and worker().
Referenced by main().
testRecursive()
static void testRecursive () static
Definition at line 72 of file pthread_mutex.c.
{
     pthread_mutexattr_t attr;
     pthread_mutexattr_init(&attr);
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
     pthread_mutex_init(&mutex, &attr);
     pthread_mutexattr_destroy(&attr);
     pthread_mutex_lock(&mutex);
     variable = 0;
     pthread_t thread;
     int ret = pthread_create(&thread, NULL, &worker, NULL);
     assert(!ret);
     assert(pthread_mutex_trylock(&mutex) == 0);
     pthread_mutex_unlock(&mutex);
     pthread_mutex_unlock(&mutex);
     ret = pthread_join(thread, NULL);
     assert(!ret);
     assert(variable == 1);
     pthread_mutex_destroy(&mutex);
 }
References assert, mlibc::attr, mutex, NULL, pthread_create(), pthread_join(), pthread_mutex_destroy(), pthread_mutex_init(), pthread_mutex_lock(), PTHREAD_MUTEX_RECURSIVE, pthread_mutex_trylock(), pthread_mutex_unlock(), pthread_mutexattr_destroy(), pthread_mutexattr_init(), pthread_mutexattr_settype(), ret, variable, and worker().
Referenced by main().
worker()
static void* worker (void * arg) static
Definition at line 15 of file pthread_mutex.c.
{
     (void)arg;
     pthread_mutex_lock(&mutex);
     variable = 1;
     pthread_mutex_unlock(&mutex);
     return NULL;
 }
References arg, mutex, NULL, pthread_mutex_lock(), pthread_mutex_unlock(), variable, and Driver::void().
Referenced by testNormal(), and testRecursive().
Variable Documentation
mutex
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 13 of file pthread_mutex.c.
Referenced by anonymous_namespace{guard-abi.cpp}::Guard::lock(), pthread_cond_timedwait(), pthread_cond_wait(), pthread_mutex_destroy(), pthread_mutex_init(), pthread_mutex_lock(), pthread_mutex_trylock(), pthread_mutex_unlock(), testNormal(), testRecursive(), anonymous_namespace{guard-abi.cpp}::Guard::unlock(), and worker().
variable
int variable
Definition at line 12 of file pthread_mutex.c.
Referenced by testNormal(), testRecursive(), and worker().