Fennix Userspace: Userspace/musl/src/passwd/pwf.h File Reference
pwf.h File Reference
#include <pwd.h>
#include <grp.h>
#include <shadow.h>
#include <stdio.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
Functions
hidden int __getpwent_a (FILE *f, struct passwd *pw, char **line, size_t *size, struct passwd **res)
hidden int __getpw_a (const char *name, uid_t uid, struct passwd *pw, char **buf, size_t *size, struct passwd **res)
hidden int __getgrent_a (FILE *f, struct group *gr, char **line, size_t *size, char ***mem, size_t *nmem, struct group **res)
hidden int __getgr_a (const char *name, gid_t gid, struct group *gr, char **buf, size_t *size, char ***mem, size_t *nmem, struct group **res)
hidden int __parsespent (char *s, struct spwd *sp)
Function Documentation
__getgr_a()
hidden int __getgr_a (const char * name, gid_t gid, struct group * gr, char ** buf, size_t * size, char *** mem, size_t * nmem, struct group ** res)
Definition at line 20 of file getgr_a.c.
 {
     FILE *f;
     int rv = 0;
     int cs;
     *res = 0;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     f = fopen("/etc/group", "rbe");
     if (!f) {
         rv = errno;
         goto done;
     }
     while (!(rv = __getgrent_a(f, gr, buf, size, mem, nmem, res)) && *res) {
         if (name && !strcmp(name, (*res)->gr_name)
         || !name && (*res)->gr_gid == gid) {
             break;
         }
     }
     fclose(f);
     if (!*res && (rv == 0 || rv == ENOENT || rv == ENOTDIR)) {
         int32_t req = name ? GETGRBYNAME : GETGRBYGID;
         int32_t i;
         const char *key;
         int32_t groupbuf[GR_LEN] = {0};
         size_t len = 0;
         size_t grlist_len = 0;
         char gidbuf[11] = {0};
         int swap = 0;
         char *ptr;
         if (name) {
             key = name;
         } else {
             if (gid < 0 || gid > UINT32_MAX) {
                 rv = 0;
                 goto done;
             }
             key = itoa(gidbuf, gid);
         }
         f = __nscd_query(req, key, groupbuf, sizeof groupbuf, &swap);
         if (!f) { rv = errno; goto done; }
         if (!groupbuf[GRFOUND]) { rv = 0; goto cleanup_f; }
         if (!groupbuf[GRNAMELEN] || !groupbuf[GRPASSWDLEN]) {
             rv = EIO;
             goto cleanup_f;
         }
         if (groupbuf[GRNAMELEN] > SIZE_MAX - groupbuf[GRPASSWDLEN]) {
             rv = ENOMEM;
             goto cleanup_f;
         }
         len = groupbuf[GRNAMELEN] + groupbuf[GRPASSWDLEN];
         for (i = 0; i < groupbuf[GRMEMCNT]; i++) {
             uint32_t name_len;
             if (fread(&name_len, sizeof name_len, 1, f) < 1) {
                 rv = ferror(f) ? errno : EIO;
                 goto cleanup_f;
             }
             if (swap) {
                 name_len = bswap_32(name_len);
             }
             if (name_len > SIZE_MAX - grlist_len
             || name_len > SIZE_MAX - len) {
                 rv = ENOMEM;
                 goto cleanup_f;
             }
             len += name_len;
             grlist_len += name_len;
         }
         if (len > *size || !*buf) {
             char *tmp = realloc(*buf, len);
             if (!tmp) {
                 rv = errno;
                 goto cleanup_f;
             }
             *buf = tmp;
             *size = len;
         }
         if (!fread(*buf, len, 1, f)) {
             rv = ferror(f) ? errno : EIO;
             goto cleanup_f;
         }
         if (groupbuf[GRMEMCNT] + 1 > *nmem) {
             if (groupbuf[GRMEMCNT] + 1 > SIZE_MAX/sizeof(char*)) {
                 rv = ENOMEM;
                 goto cleanup_f;
             }
             char **tmp = realloc(*mem, (groupbuf[GRMEMCNT]+1)*sizeof(char*));
             if (!tmp) {
                 rv = errno;
                 goto cleanup_f;
             }
             *mem = tmp;
             *nmem = groupbuf[GRMEMCNT] + 1;
         }
         if (groupbuf[GRMEMCNT]) {
             mem[0][0] = *buf + groupbuf[GRNAMELEN] + groupbuf[GRPASSWDLEN];
             for (ptr = mem[0][0], i = 0; ptr != mem[0][0]+grlist_len; ptr++)
                 if (!*ptr) mem[0][++i] = ptr+1;
             mem[0][i] = 0;
             if (i != groupbuf[GRMEMCNT]) {
                 rv = EIO;
                 goto cleanup_f;
             }
         } else {
             mem[0][0] = 0;
         }
         gr->gr_name = *buf;
         gr->gr_passwd = gr->gr_name + groupbuf[GRNAMELEN];
         gr->gr_gid = groupbuf[GRGID];
         gr->gr_mem = *mem;
         if (gr->gr_passwd[-1]
         || gr->gr_passwd[groupbuf[GRPASSWDLEN]-1]) {
             rv = EIO;
             goto cleanup_f;
         }
         if (name && strcmp(name, gr->gr_name)
         || !name && gid != gr->gr_gid) {
             rv = EIO;
             goto cleanup_f;
         }
         *res = gr;
 cleanup_f:
         fclose(f);
         goto done;
     }
 done:
     pthread_setcancelstate(cs, 0);
     if (rv) errno = rv;
     return rv;
 }
References __getgrent_a(), __nscd_query(), bswap_32, buf, done, EIO, ENOENT, ENOMEM, ENOTDIR, errno, f, fclose(), ferror, fopen(), fread(), GETGRBYGID, GETGRBYNAME, gr, group::gr_gid, GR_LEN, group::gr_mem, group::gr_name, group::gr_passwd, GRFOUND, GRGID, GRMEMCNT, GRNAMELEN, GRPASSWDLEN, i, itoa(), mem, name, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), realloc, size, SIZE_MAX, strcmp, swap(), and UINT32_MAX.
Referenced by getgr_r(), getgrgid(), and getgrnam().
__getgrent_a()
hidden int __getgrent_a (FILE * f, struct group * gr, char ** line, size_t * size, char *** mem, size_t * nmem, struct group ** res)
Definition at line 11 of file getgrent_a.c.
 {
     ssize_t l;
     char *s, *mems;
     size_t i;
     int rv = 0;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     for (;;) {
         if ((l=getline(line, size, f)) < 0) {
             rv = ferror(f) ? errno : 0;
             free(*line);
             *line = 0;
             gr = 0;
             goto end;
         }
         line[0][l-1] = 0;
         s = line[0];
         gr->gr_name = s++;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; gr->gr_passwd = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; gr->gr_gid = atou(&s);
         if (*s != ':') continue;
         *s++ = 0; mems = s;
         break;
     }
     for (*nmem=!!*s; *s; s++)
         if (*s==',') ++*nmem;
     free(*mem);
     *mem = calloc(sizeof(char *), *nmem+1);
     if (!*mem) {
         rv = errno;
         free(*line);
         *line = 0;
         gr = 0;
         goto end;
     }
     if (*mems) {
         mem[0][0] = mems;
         for (s=mems, i=0; *s; s++)
             if (*s==',') *s++ = 0, mem[0][++i] = s;
         mem[0][++i] = 0;
     } else {
         mem[0][0] = 0;
     }
     gr->gr_mem = *mem;
 end:
     pthread_setcancelstate(cs, 0);
     *res = gr;
     if(rv) errno = rv;
     return rv;
 }
References atou(), calloc, errno, f, ferror, free, getline(), gr, group::gr_gid, group::gr_mem, group::gr_name, group::gr_passwd, i, line, mem, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), size, and strchr().
Referenced by __getgr_a(), fgetgrent(), getgrent(), and getgrouplist().
__getpw_a()
hidden int __getpw_a (const char * name, uid_t uid, struct passwd * pw, char ** buf, size_t * size, struct passwd ** res)
Definition at line 20 of file getpw_a.c.
 {
     FILE *f;
     int cs;
     int rv = 0;
     *res = 0;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     f = fopen("/etc/passwd", "rbe");
     if (!f) {
         rv = errno;
         goto done;
     }
     while (!(rv = __getpwent_a(f, pw, buf, size, res)) && *res) {
         if (name && !strcmp(name, (*res)->pw_name)
         || !name && (*res)->pw_uid == uid)
             break;
     }
     fclose(f);
     if (!*res && (rv == 0 || rv == ENOENT || rv == ENOTDIR)) {
         int32_t req = name ? GETPWBYNAME : GETPWBYUID;
         const char *key;
         int32_t passwdbuf[PW_LEN] = {0};
         size_t len = 0;
         char uidbuf[11] = {0};
         if (name) {
             key = name;
         } else {
             /* uid outside of this range can't be queried with the
              * nscd interface, but might happen if uid_t ever
              * happens to be a larger type (this is not true as of
              * now)
              */
             if(uid < 0 || uid > UINT32_MAX) {
                 rv = 0;
                 goto done;
             }
             key = itoa(uidbuf, uid);
         }
         f = __nscd_query(req, key, passwdbuf, sizeof passwdbuf, (int[]){0});
         if (!f) { rv = errno; goto done; }
         if(!passwdbuf[PWFOUND]) { rv = 0; goto cleanup_f; }
         /* A zero length response from nscd is invalid. We ignore
          * invalid responses and just report an error, rather than
          * trying to do something with them.
          */
         if (!passwdbuf[PWNAMELEN] || !passwdbuf[PWPASSWDLEN]
         || !passwdbuf[PWGECOSLEN] || !passwdbuf[PWDIRLEN]
         || !passwdbuf[PWSHELLLEN]) {
             rv = EIO;
             goto cleanup_f;
         }
         if ((passwdbuf[PWNAMELEN]|passwdbuf[PWPASSWDLEN]
              |passwdbuf[PWGECOSLEN]|passwdbuf[PWDIRLEN]
              |passwdbuf[PWSHELLLEN]) >= SIZE_MAX/8) {
             rv = ENOMEM;
             goto cleanup_f;
         }
         len = passwdbuf[PWNAMELEN] + passwdbuf[PWPASSWDLEN]
             + passwdbuf[PWGECOSLEN] + passwdbuf[PWDIRLEN]
             + passwdbuf[PWSHELLLEN];
         if (len > *size || !*buf) {
             char *tmp = realloc(*buf, len);
             if (!tmp) {
                 rv = errno;
                 goto cleanup_f;
             }
             *buf = tmp;
             *size = len;
         }
         if (!fread(*buf, len, 1, f)) {
             rv = ferror(f) ? errno : EIO;
             goto cleanup_f;
         }
         pw->pw_name = *buf;
         pw->pw_passwd = pw->pw_name + passwdbuf[PWNAMELEN];
         pw->pw_gecos = pw->pw_passwd + passwdbuf[PWPASSWDLEN];
         pw->pw_dir = pw->pw_gecos + passwdbuf[PWGECOSLEN];
         pw->pw_shell = pw->pw_dir + passwdbuf[PWDIRLEN];
         pw->pw_uid = passwdbuf[PWUID];
         pw->pw_gid = passwdbuf[PWGID];
         /* Don't assume that nscd made sure to null terminate strings.
          * It's supposed to, but malicious nscd should be ignored
          * rather than causing a crash.
          */
         if (pw->pw_passwd[-1] || pw->pw_gecos[-1] || pw->pw_dir[-1]
         || pw->pw_shell[passwdbuf[PWSHELLLEN]-1]) {
             rv = EIO;
             goto cleanup_f;
         }
         if (name && strcmp(name, pw->pw_name)
         || !name && uid != pw->pw_uid) {
             rv = EIO;
             goto cleanup_f;
         }
         *res = pw;
 cleanup_f:
         fclose(f);
         goto done;
     }
 done:
     pthread_setcancelstate(cs, 0);
     if (rv) errno = rv;
     return rv;
 }
References __getpwent_a(), __nscd_query(), buf, done, EIO, ENOENT, ENOMEM, ENOTDIR, errno, f, fclose(), ferror, fopen(), fread(), GETPWBYNAME, GETPWBYUID, itoa(), name, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pw, passwd::pw_dir, passwd::pw_gecos, passwd::pw_gid, PW_LEN, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, PWDIRLEN, PWFOUND, PWGECOSLEN, PWGID, PWNAMELEN, PWPASSWDLEN, PWSHELLLEN, PWUID, realloc, size, SIZE_MAX, strcmp, and UINT32_MAX.
Referenced by getpw_r(), getpwnam(), and getpwuid().
__getpwent_a()
hidden int __getpwent_a (FILE * f, struct passwd * pw, char ** line, size_t * size, struct passwd ** res)
Definition at line 11 of file getpwent_a.c.
 {
     ssize_t l;
     char *s;
     int rv = 0;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     for (;;) {
         if ((l=getline(line, size, f)) < 0) {
             rv = ferror(f) ? errno : 0;
             free(*line);
             *line = 0;
             pw = 0;
             break;
         }
         line[0][l-1] = 0;
         s = line[0];
         pw->pw_name = s++;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_passwd = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_uid = atou(&s);
         if (*s != ':') continue;
         *s++ = 0; pw->pw_gid = atou(&s);
         if (*s != ':') continue;
         *s++ = 0; pw->pw_gecos = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_dir = s;
         if (!(s = strchr(s, ':'))) continue;
         *s++ = 0; pw->pw_shell = s;
         break;
     }
     pthread_setcancelstate(cs, 0);
     *res = pw;
     if (rv) errno = rv;
     return rv;
 }
References atou(), errno, f, ferror, free, getline(), line, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pw, passwd::pw_dir, passwd::pw_gecos, passwd::pw_gid, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, size, and strchr().
Referenced by __getpw_a(), fgetpwent(), and getpwent().
__parsespent()
hidden int __parsespent (char * s, struct spwd * sp)
Definition at line 23 of file getspnam_r.c.
 {
     sp->sp_namp = s;
     if (!(s = strchr(s, ':'))) return -1;
     *s = 0;
     sp->sp_pwdp = ++s;
     if (!(s = strchr(s, ':'))) return -1;
     *s = 0;
     s++; sp->sp_lstchg = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_min = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_max = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_warn = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_inact = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_expire = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_flag = xatol(&s);
     if (*s != '\n') return -1;
     return 0;
 }
References sp, strchr(), and xatol().
Referenced by fgetspent(), and getspnam_r().