Fennix: Userspace/apps/base/busybox/libbb/device_open.c File Reference
device_open.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC device_open (const char *device, int mode)
Function Documentation
device_open()
int FAST_FUNC device_open (const char * device, int mode)
Definition at line 12 of file device_open.c.
 {
     int m, f, fd;
     m = mode | O_NONBLOCK;
     /* Retry up to 5 times */
     /* TODO: explain why it can't be considered insane */
     for (f = 0; f < 5; f++) {
         fd = open(device, m, 0600);
         if (fd >= 0)
             break;
     }
     if (fd < 0)
         return fd;
     /* Reset original flags. */
     if (m != mode)
         fcntl(fd, F_SETFL, mode);
     return fd;
 }
References device, f, F_SETFL, fcntl(), fd, O_NONBLOCK, and open().
Referenced by log_locally(), message(), open_stdio_to_tty(), rfkill_main(), and serial_open().