Fennix: Userspace/musl/src/misc/syscall.c File Reference
syscall.c File Reference
#include <unistd.h>
#include "syscall.h"
#include <stdarg.h>
Macros
#define _BSD_SOURCE
Functions
long syscall (long n,...)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file syscall.c.
Function Documentation
syscall()
long syscall (long n, ...)
Definition at line 8 of file syscall.c.
 {
     va_list ap;
     syscall_arg_t a,b,c,d,e,f;
     va_start(ap, n);
     a=va_arg(ap, syscall_arg_t);
     b=va_arg(ap, syscall_arg_t);
     c=va_arg(ap, syscall_arg_t);
     d=va_arg(ap, syscall_arg_t);
     e=va_arg(ap, syscall_arg_t);
     f=va_arg(ap, syscall_arg_t);
     va_end(ap);
     return __syscall_ret(__syscall(n,a,b,c,d,e,f));
 }
References __syscall, __syscall_ret(), b, c, f, n, va_arg, va_end(), and va_start().
Referenced by mlibc::__attribute__(), __fstatfs(), __lseek(), __lsysinfo(), __madvise(), __mprotect(), __mremap(), __munmap(), __statfs(), __stdio_close(), __stdio_read(), __stdio_write(), access(), acct(), capget(), capset(), chdir(), chmod(), chown(), chroot(), clock_adjtime(), clock_getres(), clock_settime(), copy_file_range(), delete_module(), dup(), epoll_ctl(), execve(), faccessat(), fallocate(), fanotify_init(), fanotify_mark(), fchdir(), fchmod(), fchmodat(), fchown(), fchownat(), fcntl(), fgetxattr(), flistxattr(), flock(), fremovexattr(), freopen(), fsetxattr(), ftruncate(), getcwd(), getdents(), getgroups(), getitimer(), getpgid(), getpriority(), getresgid(), getresuid(), getrlimit(), getsid(), getxattr(), init_module(), inotify_add_watch(), inotify_rm_watch(), isatty(), kill(), klogctl(), lchown(), lgetxattr(), link(), linkat(), listxattr(), llistxattr(), lremovexattr(), lsetxattr(), main(), memfd_create(), mincore(), mkdir(), mkdirat(), mknod(), mknodat(), mlock(), mlock2(), mlockall(), mount(), mq_close(), mq_notify(), mq_open(), mq_setattr(), msgget(), munlock(), munlockall(), name_to_handle_at(), open_by_handle_at(), pipe(), pivot_root(), prctl(), prlimit(), process_vm_readv(), process_vm_writev(), ptrace(), quotactl(), raise(), readahead(), reboot(), remap_file_pages(), removexattr(), rename(), renameat(), rmdir(), sched_get_priority_max(), sched_get_priority_min(), sched_rr_get_interval(), sched_setaffinity(), sched_yield(), semget(), semop(), semtimedop(), sendfile(), setdomainname(), setfsgid(), setfsuid(), sethostname(), setitimer(), setns(), setpgid(), setpriority(), setsid(), setxattr(), shmat(), shmdt(), shmget(), sigaltstack(), sigpending(), sigqueue(), splice(), swapoff(), swapon(), symlink(), symlinkat(), sync_file_range(), syncfs(), mlibc::sys_accept(), mlibc::sys_access(), mlibc::sys_bind(), mlibc::sys_chdir(), mlibc::sys_chmod(), mlibc::sys_clock_get(), mlibc::sys_close(), mlibc::sys_connect(), mlibc::sys_dup(), mlibc::sys_dup2(), mlibc::sys_epoll_create(), mlibc::sys_epoll_ctl(), mlibc::sys_epoll_pwait(), mlibc::sys_eventfd_create(), mlibc::sys_execve(), mlibc::sys_exit(), mlibc::sys_fchdir(), mlibc::sys_fcntl(), mlibc::sys_fork(), mlibc::sys_futex_tid(), mlibc::sys_futex_wait(), mlibc::sys_futex_wake(), mlibc::sys_getcwd(), mlibc::sys_getentropy(), mlibc::sys_gethostname(), mlibc::sys_getpid(), mlibc::sys_getsockopt(), mlibc::sys_ioctl(), mlibc::sys_kill(), mlibc::sys_libc_log(), mlibc::sys_link(), mlibc::sys_listen(), mlibc::sys_mkdir(), mlibc::sys_msg_recv(), mlibc::sys_msg_send(), mlibc::sys_open(), mlibc::sys_peername(), mlibc::sys_pipe(), mlibc::sys_pread(), mlibc::sys_pwrite(), mlibc::sys_read(), mlibc::sys_read_entries(), mlibc::sys_readlink(), mlibc::sys_rename(), mlibc::sys_rmdir(), mlibc::sys_seteuid(), mlibc::sys_setsockopt(), mlibc::sys_sigaction(), mlibc::sys_sigprocmask(), mlibc::sys_sleep(), mlibc::sys_socket(), mlibc::sys_socketpair(), mlibc::sys_sockname(), mlibc::sys_stat(), mlibc::sys_tcb_set(), mlibc::sys_vm_map(), mlibc::sys_vm_unmap(), mlibc::sys_write(), mlibc::sys_yield(), syscall0(), syscall1(), syscall2(), syscall3(), syscall4(), syscall5(), syscall6(), tcgetwinsize(), tcsetwinsize(), tee(), timer_getoverrun(), timer_gettime(), timer_settime(), timerfd_create(), timerfd_gettime(), timerfd_settime(), truncate(), umask(), umount(), umount2(), uname(), unlink(), unlinkat(), unshare(), vfork(), vhangup(), and vmsplice().