Fennix Userspace: Userspace/apps/base/bash/lib/readline/signals.c File Reference
signals.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <signal.h>
#include "rldefs.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
Data Structures
struct sighandler_cxt
Macros
#define READLINE_LIBRARY
#define SIGHANDLER_RETURN return
#define sigemptyset(m)
#define SA_RESTART 0
Typedefs
typedef void SigHandler(int)
Functions
static SigHandler * rl_set_sighandler (int, SigHandler *, sighandler_cxt *)
static void rl_maybe_set_sighandler (int, SigHandler *, sighandler_cxt *)
static void rl_maybe_restore_sighandler (int, sighandler_cxt *)
static void rl_signal_handler (int)
static void _rl_handle_signal (int)
void _rl_signal_handler (int sig)
static int rl_sigaction (int sig, sighandler_cxt *nh, sighandler_cxt *oh)
int rl_set_signals (void)
int rl_clear_signals (void)
void rl_cleanup_after_signal (void)
void rl_reset_after_signal (void)
void rl_free_line_state (void)
int rl_pending_signal (void)
void rl_check_signals (void)
void _rl_block_sigint (void)
void _rl_release_sigint (void)
void _rl_block_sigwinch (void)
void _rl_release_sigwinch (void)
void rl_echo_signal_char (int sig)
Variables
int rl_catch_signals = 1
int rl_catch_sigwinch = 0
int volatile _rl_caught_signal = 0
int _rl_echoctl = 0
int _rl_intr_char = 0
int _rl_quit_char = 0
int _rl_susp_char = 0
static int signals_set_flag
static int sigwinch_set_flag
static sighandler_cxt old_int
static sighandler_cxt old_term
static sighandler_cxt old_hup
static sighandler_cxt old_alrm
static sighandler_cxt old_quit
_rl_sigcleanup_func_t * _rl_sigcleanup
void * _rl_sigcleanarg
static int sigint_blocked
static int sigwinch_blocked
Data Structure Documentation
sighandler_cxt
struct sighandler_cxt
Definition at line 61 of file signals.c.
Data Fields
int sa_flags
SigHandler * sa_handler
int sa_mask
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file signals.c.
SA_RESTART
#define SA_RESTART 0
Definition at line 66 of file signals.c.
sigemptyset
#define sigemptyset (m)
Definition at line 62 of file signals.c.
SIGHANDLER_RETURN
#define SIGHANDLER_RETURN return
Definition at line 51 of file signals.c.
Typedef Documentation
SigHandler
typedef void SigHandler(int)
Definition at line 55 of file signals.c.
Function Documentation
_rl_block_sigint()
void _rl_block_sigint (void)
Definition at line 640 of file signals.c.
 {
   if (sigint_blocked)
     return;
   sigint_blocked = 1;
 }
References sigint_blocked.
Referenced by rl_deprep_terminal(), rl_prep_terminal(), and rl_redisplay().
_rl_block_sigwinch()
void _rl_block_sigwinch (void)
Definition at line 662 of file signals.c.
 {
   if (sigwinch_blocked)
     return;
 #if defined (SIGWINCH)
 #if defined (HAVE_POSIX_SIGNALS)
   sigemptyset (&sigwinch_set);
   sigemptyset (&sigwinch_oset);
   sigaddset (&sigwinch_set, SIGWINCH);
   sigprocmask (SIG_BLOCK, &sigwinch_set, &sigwinch_oset);
 #else /* !HAVE_POSIX_SIGNALS */
 #  if defined (HAVE_BSD_SIGNALS)
   sigwinch_oldmask = sigblock (sigmask (SIGWINCH));
 #  else /* !HAVE_BSD_SIGNALS */
 #    if defined (HAVE_USG_SIGHOLD)
   sighold (SIGWINCH);
 #    endif /* HAVE_USG_SIGHOLD */
 #  endif /* !HAVE_BSD_SIGNALS */
 #endif /* !HAVE_POSIX_SIGNALS */
 #endif /* SIGWINCH */
   sigwinch_blocked = 1;
 }
References SIG_BLOCK, sigaddset(), sigemptyset, sighold(), sigmask, sigprocmask(), SIGWINCH, and sigwinch_blocked.
_rl_handle_signal()
static void _rl_handle_signal (int sig) static
Definition at line 165 of file signals.c.
 {
   int block_sig;
 #if defined (HAVE_POSIX_SIGNALS)
   sigset_t set, oset;
 #else /* !HAVE_POSIX_SIGNALS */
 #  if defined (HAVE_BSD_SIGNALS)
   long omask;
 #  else /* !HAVE_BSD_SIGNALS */
   sighandler_cxt dummy_cxt; /* needed for rl_set_sighandler call */
 #  endif /* !HAVE_BSD_SIGNALS */
 #endif /* !HAVE_POSIX_SIGNALS */
   RL_SETSTATE(RL_STATE_SIGHANDLER);
 #if !defined (HAVE_BSD_SIGNALS) && !defined (HAVE_POSIX_SIGNALS)
   /* Since the signal will not be blocked while we are in the signal
      handler, ignore it until rl_clear_signals resets the catcher. */
 #  if defined (SIGALRM)
   if (sig == SIGINT || sig == SIGALRM)
 #  else
   if (sig == SIGINT)
 #  endif
     rl_set_sighandler (sig, SIG_IGN, &dummy_cxt);
 #endif /* !HAVE_BSD_SIGNALS && !HAVE_POSIX_SIGNALS */
   /* If there's a sig cleanup function registered, call it and `deregister'
      the cleanup function to avoid multiple calls */
   if (_rl_sigcleanup)
     {
       (*_rl_sigcleanup) (sig, _rl_sigcleanarg);
       _rl_sigcleanup = 0;
       _rl_sigcleanarg = 0;
     }
 #if defined (HAVE_POSIX_SIGNALS)
   /* Get the current set of blocked signals. If we want to block a signal for
      the duration of the cleanup functions, make sure to add it to SET and
      set block_sig = 1 (see the SIGHUP case below). */
   block_sig = 0;    /* sentinel to block signals with sigprocmask */
   sigemptyset (&set);
   sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &set);
 #endif
   switch (sig)
     {
     case SIGINT:
       /* We will end up blocking SIGTTOU while we are resetting the tty, so
      watch out for this if it causes problems. We could prevent this by
      setting block_sig to 1 without modifying SET. */
       _rl_reset_completion_state ();
       rl_free_line_state ();
 #if defined (READLINE_CALLBACKS)
       rl_callback_sigcleanup ();
 #endif
       /* FALLTHROUGH */
 #if defined (SIGTSTP)
     case SIGTSTP:
     case SIGTTIN:
     case SIGTTOU:
 #  if defined (HAVE_POSIX_SIGNALS)
       /* Block SIGTTOU so we can restore the terminal settings to something
      sane without stopping on SIGTTOU if we have been placed into the
      background.  Even trying to get the current terminal pgrp with
      tcgetpgrp() will generate SIGTTOU, so we don't bother.  We still do
      this even if we've been stopped on SIGTTOU, since we handle signals
      when we have returned from the signal handler and the signal is no
      longer blocked. */
       if (block_sig == 0)
     {
       sigaddset (&set, SIGTTOU);
       block_sig = 1;
     }
 #  endif
 #endif /* SIGTSTP */
    /* Any signals that should be blocked during cleanup should go here. */
 #if defined (SIGHUP)
     case SIGHUP:
 #  if defined (_AIX)
       if (block_sig == 0)
     {
       sigaddset (&set, sig);
       block_sig = 1;
     }
 #  endif // _AIX
 #endif
     /* Signals that don't require blocking during cleanup should go here. */
     case SIGTERM:
 #if defined (SIGALRM)
     case SIGALRM:
       if (sig == SIGALRM)
     _rl_timeout_handle_sigalrm ();
 #endif
 #if defined (SIGQUIT)
     case SIGQUIT:
 #endif
 #if defined (HAVE_POSIX_SIGNALS)
       if (block_sig)
     sigprocmask (SIG_BLOCK, &set, &oset);
 #endif
       rl_echo_signal_char (sig);
       rl_cleanup_after_signal ();
       /* At this point, the application's signal handler, if any, is the
      current handler. */
 #if defined (HAVE_POSIX_SIGNALS)
       /* Unblock any signal(s) blocked above */
       if (block_sig)
     sigprocmask (SIG_UNBLOCK, &oset, (sigset_t *)NULL);
 #endif
       /* We don't have to bother unblocking the signal because we are not
      running in a signal handler context. */
 #if defined (__EMX__)
       signal (sig, SIG_ACK);
 #endif
 #if defined (HAVE_KILL)
       kill (getpid (), sig);
 #else
       raise (sig);      /* assume we have raise */
 #endif
       /* We don't need to modify the signal mask now that this is not run in
      a signal handler context. */
       rl_reset_after_signal ();
     }
   RL_UNSETSTATE(RL_STATE_SIGHANDLER);
   SIGHANDLER_RETURN;
 }
References _rl_reset_completion_state(), _rl_sigcleanarg, _rl_sigcleanup, _rl_timeout_handle_sigalrm(), getpid(), kill(), NULL, rl_callback_sigcleanup(), rl_cleanup_after_signal(), rl_echo_signal_char(), rl_free_line_state(), rl_reset_after_signal(), rl_set_sighandler(), RL_SETSTATE, RL_STATE_SIGHANDLER, RL_UNSETSTATE, SIG_BLOCK, SIG_IGN, sigaddset(), SIGALRM, sigemptyset, SIGHANDLER_RETURN, SIGHUP, SIGINT, signal, sigprocmask(), SIGQUIT, SIGTERM, SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by _rl_signal_handler().
_rl_release_sigint()
void _rl_release_sigint (void)
Definition at line 650 of file signals.c.
 {
   if (sigint_blocked == 0)
     return;
   sigint_blocked = 0;
   RL_CHECK_SIGNALS ();
 }
References RL_CHECK_SIGNALS, and sigint_blocked.
Referenced by rl_deprep_terminal(), rl_prep_terminal(), and rl_redisplay().
_rl_release_sigwinch()
void _rl_release_sigwinch (void)
Definition at line 691 of file signals.c.
 {
   if (sigwinch_blocked == 0)
     return;
 #if defined (SIGWINCH)
 #if defined (HAVE_POSIX_SIGNALS)
   sigprocmask (SIG_SETMASK, &sigwinch_oset, (sigset_t *)NULL);
 #else
 #  if defined (HAVE_BSD_SIGNALS)
   sigsetmask (sigwinch_oldmask);
 #  else /* !HAVE_BSD_SIGNALS */
 #    if defined (HAVE_USG_SIGHOLD)
   sigrelse (SIGWINCH);
 #    endif /* HAVE_USG_SIGHOLD */
 #  endif /* !HAVE_BSD_SIGNALS */
 #endif /* !HAVE_POSIX_SIGNALS */
 #endif /* SIGWINCH */
   sigwinch_blocked = 0;
 }
References NULL, SIG_SETMASK, sigprocmask(), sigrelse(), SIGWINCH, and sigwinch_blocked.
_rl_signal_handler()
void _rl_signal_handler (int sig)
Definition at line 128 of file signals.c.
 {
   _rl_caught_signal = 0;    /* XXX */
 #if defined (SIGWINCH)
   if (sig == SIGWINCH)
     {
       RL_SETSTATE(RL_STATE_SIGHANDLER);
       rl_resize_terminal ();
       /* XXX - experimental for now */
       /* Call a signal hook because though we called the original signal handler
      in rl_sigwinch_handler below, we will not resend the signal to
      ourselves. */
       if (rl_signal_event_hook)
     (*rl_signal_event_hook) ();
       RL_UNSETSTATE(RL_STATE_SIGHANDLER);
     }
   else
 #endif
     _rl_handle_signal (sig);
   SIGHANDLER_RETURN;
 }
References _rl_caught_signal, _rl_handle_signal(), rl_resize_terminal(), RL_SETSTATE, rl_signal_event_hook, RL_STATE_SIGHANDLER, RL_UNSETSTATE, SIGHANDLER_RETURN, and SIGWINCH.
rl_check_signals()
void rl_check_signals (void)
Definition at line 612 of file signals.c.
 {
   RL_CHECK_SIGNALS ();
 }
References RL_CHECK_SIGNALS.
rl_cleanup_after_signal()
void rl_cleanup_after_signal (void)
Definition at line 567 of file signals.c.
 {
   _rl_clean_up_for_exit ();
   if (rl_deprep_term_function)
     (*rl_deprep_term_function) ();
   rl_clear_pending_input ();
   rl_clear_signals ();
 }
References _rl_clean_up_for_exit(), rl_clear_pending_input(), rl_clear_signals(), and rl_deprep_term_function.
Referenced by _rl_handle_signal().
rl_clear_signals()
int rl_clear_signals (void)
Definition at line 514 of file signals.c.
 {
   sighandler_cxt dummy;
   if (rl_catch_signals && signals_set_flag == 1)
     {
       /* Since rl_maybe_set_sighandler doesn't override a SIG_IGN handler,
      we should in theory not have to restore a handler where
      old_xxx.sa_handler == SIG_IGN.  That's what rl_maybe_restore_sighandler
      does.  Fewer system calls should reduce readline's per-line
      overhead */
       rl_maybe_restore_sighandler (SIGINT, &old_int);
       rl_maybe_restore_sighandler (SIGTERM, &old_term);
 #if defined (SIGHUP)
       rl_maybe_restore_sighandler (SIGHUP, &old_hup);
 #endif
 #if defined (SIGQUIT)
       rl_maybe_restore_sighandler (SIGQUIT, &old_quit);
 #endif
 #if defined (SIGALRM)
       rl_maybe_restore_sighandler (SIGALRM, &old_alrm);
 #endif
 #if defined (SIGTSTP)
       rl_maybe_restore_sighandler (SIGTSTP, &old_tstp);
 #endif /* SIGTSTP */
 #if defined (SIGTTOU)
       rl_maybe_restore_sighandler (SIGTTOU, &old_ttou);
 #endif /* SIGTTOU */
 #if defined (SIGTTIN)
       rl_maybe_restore_sighandler (SIGTTIN, &old_ttin);
 #endif /* SIGTTIN */
       signals_set_flag = 0;
     }
 #if defined (SIGWINCH)
   if (rl_catch_sigwinch && sigwinch_set_flag == 1)
     {
       sigemptyset (&dummy.sa_mask);
       rl_sigaction (SIGWINCH, &old_winch, &dummy);
       sigwinch_set_flag = 0;
     }
 #endif
   return 0;
 }
References old_alrm, old_hup, old_int, old_quit, old_term, old_tstp, old_ttin, old_ttou, rl_catch_signals, rl_catch_sigwinch, rl_maybe_restore_sighandler(), rl_sigaction(), SIGALRM, sigemptyset, SIGHUP, SIGINT, signals_set_flag, SIGQUIT, SIGTERM, SIGTSTP, SIGTTIN, SIGTTOU, SIGWINCH, and sigwinch_set_flag.
Referenced by readline(), rl_callback_handler_remove(), rl_callback_read_char(), and rl_cleanup_after_signal().
rl_echo_signal_char()
void rl_echo_signal_char (int sig)
Definition at line 721 of file signals.c.
 {
   char cstr[3];
   int cslen, c;
   if (_rl_echoctl == 0 || _rl_echo_control_chars == 0)
     return;
   switch (sig)
     {
     case SIGINT:  c = _rl_intr_char; break;
 #if defined (SIGQUIT)
     case SIGQUIT: c = _rl_quit_char; break;
 #endif
 #if defined (SIGTSTP)
     case SIGTSTP: c = _rl_susp_char; break;
 #endif
     default: return;
     }
   if (CTRL_CHAR (c) || c == RUBOUT)
     {
       cstr[0] = '^';
       cstr[1] = CTRL_CHAR (c) ? UNCTRL (c) : '?';
       cstr[cslen = 2] = '\0';
     }
   else
     {
       cstr[0] = c;
       cstr[cslen = 1] = '\0';
     }
   _rl_output_some_chars (cstr, cslen);
 }
References _rl_echo_control_chars, _rl_echoctl, _rl_intr_char, _rl_output_some_chars(), _rl_quit_char, _rl_susp_char, c, CTRL_CHAR, RUBOUT, SIGINT, SIGQUIT, SIGTSTP, and UNCTRL.
Referenced by _rl_handle_signal().
rl_free_line_state()
void rl_free_line_state (void)
Definition at line 590 of file signals.c.
 {
   register HIST_ENTRY *entry;
   rl_free_undo_list ();
   entry = current_history ();
   if (entry)
     entry->data = (char *)NULL;
   _rl_kill_kbd_macro ();
   rl_clear_message ();
   _rl_reset_argument ();
 }
References _rl_kill_kbd_macro(), _rl_reset_argument(), current_history(), entry::data, NULL, rl_clear_message(), and rl_free_undo_list().
Referenced by _rl_handle_signal().
rl_maybe_restore_sighandler()
static void rl_maybe_restore_sighandler (int sig, sighandler_cxt * handler) static
Definition at line 397 of file signals.c.
 {
   sighandler_cxt dummy;
   sigemptyset (&dummy.sa_mask);
   dummy.sa_flags = 0;
   if (handler->sa_handler != SIG_IGN)
     rl_sigaction (sig, handler, &dummy);
 }
References handler(), rl_sigaction(), SIG_IGN, and sigemptyset.
Referenced by rl_clear_signals().
rl_maybe_set_sighandler()
static void rl_maybe_set_sighandler (int sig, SigHandler * handler, sighandler_cxt * ohandler) static
Definition at line 380 of file signals.c.
 {
   sighandler_cxt dummy;
   SigHandler *oh;
   sigemptyset (&dummy.sa_mask);
   dummy.sa_flags = 0;
   oh = rl_set_sighandler (sig, handler, ohandler);
   if (oh == (SigHandler *)SIG_IGN)
     rl_sigaction (sig, ohandler, &dummy);
 }
References handler(), rl_set_sighandler(), rl_sigaction(), SIG_IGN, and sigemptyset.
Referenced by rl_set_signals().
rl_pending_signal()
int rl_pending_signal (void)
Definition at line 606 of file signals.c.
 {
   return (_rl_caught_signal);
 }
References _rl_caught_signal.
rl_reset_after_signal()
void rl_reset_after_signal (void)
Definition at line 578 of file signals.c.
 {
   if (rl_prep_term_function)
     (*rl_prep_term_function) (_rl_meta_flag);
   rl_set_signals ();
 }
References _rl_meta_flag, rl_prep_term_function, and rl_set_signals().
Referenced by _rl_handle_signal().
rl_set_sighandler()
static SigHandler * rl_set_sighandler (int sig, SigHandler * handler, sighandler_cxt * ohandler) static
Definition at line 349 of file signals.c.
 {
   sighandler_cxt old_handler;
 #if defined (HAVE_POSIX_SIGNALS)
   struct sigaction act;
   act.sa_handler = handler;
 #  if defined (SIGWINCH)
   act.sa_flags = (sig == SIGWINCH) ? SA_RESTART : 0;
 #  else
   act.sa_flags = 0;
 #  endif /* SIGWINCH */
   sigemptyset (&act.sa_mask);
   sigemptyset (&ohandler->sa_mask);
   sigaction (sig, &act, &old_handler);
 #else
   old_handler.sa_handler = (SigHandler *)signal (sig, handler);
 #endif /* !HAVE_POSIX_SIGNALS */
   /* XXX -- assume we have memcpy */
   /* If rl_set_signals is called twice in a row, don't set the old handler to
      rl_signal_handler, because that would cause infinite recursion. */
   if (handler != rl_signal_handler || old_handler.sa_handler != rl_signal_handler)
     memcpy (ohandler, &old_handler, sizeof (sighandler_cxt));
   return (ohandler->sa_handler);
 }
References act(), handler(), memcpy(), rl_signal_handler(), sighandler_cxt::sa_handler, sighandler_cxt::sa_mask, SA_RESTART, sigemptyset, signal, and SIGWINCH.
Referenced by _rl_handle_signal(), rl_maybe_set_sighandler(), and rl_set_signals().
rl_set_signals()
int rl_set_signals (void)
Definition at line 408 of file signals.c.
 {
   sighandler_cxt dummy;
   SigHandler *oh;
 #if defined (HAVE_POSIX_SIGNALS)
   static int sigmask_set = 0;
   static sigset_t bset, oset;
 #endif
 #if defined (HAVE_POSIX_SIGNALS)
   if (rl_catch_signals && sigmask_set == 0)
     {
       sigemptyset (&bset);
       sigaddset (&bset, SIGINT);
       sigaddset (&bset, SIGTERM);
 #if defined (SIGHUP)
       sigaddset (&bset, SIGHUP);
 #endif
 #if defined (SIGQUIT)
       sigaddset (&bset, SIGQUIT);
 #endif
 #if defined (SIGALRM)
       sigaddset (&bset, SIGALRM);
 #endif
 #if defined (SIGTSTP)
       sigaddset (&bset, SIGTSTP);
 #endif
 #if defined (SIGTTIN)
       sigaddset (&bset, SIGTTIN);
 #endif
 #if defined (SIGTTOU)
       sigaddset (&bset, SIGTTOU);
 #endif
       sigmask_set = 1;
     }
 #endif /* HAVE_POSIX_SIGNALS */
   if (rl_catch_signals && signals_set_flag == 0)
     {
 #if defined (HAVE_POSIX_SIGNALS)
       sigemptyset (&_rl_orig_sigset);
       sigprocmask (SIG_BLOCK, &bset, &_rl_orig_sigset);
 #endif
       rl_maybe_set_sighandler (SIGINT, rl_signal_handler, &old_int);
       rl_maybe_set_sighandler (SIGTERM, rl_signal_handler, &old_term);
 #if defined (SIGHUP)
       rl_maybe_set_sighandler (SIGHUP, rl_signal_handler, &old_hup);
 #endif
 #if defined (SIGQUIT)
       rl_maybe_set_sighandler (SIGQUIT, rl_signal_handler, &old_quit);
 #endif
 #if defined (SIGALRM)
       oh = rl_set_sighandler (SIGALRM, rl_signal_handler, &old_alrm);
       if (oh == (SigHandler *)SIG_IGN)
     rl_sigaction (SIGALRM, &old_alrm, &dummy);
 #if defined (HAVE_POSIX_SIGNALS) && defined (SA_RESTART)
       /* If the application using readline has already installed a signal
      handler with SA_RESTART, SIGALRM will cause reads to be restarted
      automatically, so readline should just get out of the way.  Since
      we tested for SIG_IGN above, we can just test for SIG_DFL here. */
       if (oh != (SigHandler *)SIG_DFL && (old_alrm.sa_flags & SA_RESTART))
     rl_sigaction (SIGALRM, &old_alrm, &dummy);
 #endif /* HAVE_POSIX_SIGNALS */
 #endif /* SIGALRM */
 #if defined (SIGTSTP)
       rl_maybe_set_sighandler (SIGTSTP, rl_signal_handler, &old_tstp);
 #endif /* SIGTSTP */
 #if defined (SIGTTOU)
       rl_maybe_set_sighandler (SIGTTOU, rl_signal_handler, &old_ttou);
 #endif /* SIGTTOU */
 #if defined (SIGTTIN)
       rl_maybe_set_sighandler (SIGTTIN, rl_signal_handler, &old_ttin);
 #endif /* SIGTTIN */
       signals_set_flag = 1;
 #if defined (HAVE_POSIX_SIGNALS)
       sigprocmask (SIG_SETMASK, &_rl_orig_sigset, (sigset_t *)NULL);
 #endif
     }
   else if (rl_catch_signals == 0)
     {
 #if defined (HAVE_POSIX_SIGNALS)
       sigemptyset (&_rl_orig_sigset);
       sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &_rl_orig_sigset);
 #endif
     }
 #if defined (SIGWINCH)
   if (rl_catch_sigwinch && sigwinch_set_flag == 0)
     {
       rl_maybe_set_sighandler (SIGWINCH, rl_sigwinch_handler, &old_winch);
       sigwinch_set_flag = 1;
     }
 #endif /* SIGWINCH */
   return 0;
 }
References NULL, old_alrm, old_hup, old_int, old_quit, old_term, old_tstp, old_ttin, old_ttou, rl_catch_signals, rl_catch_sigwinch, rl_maybe_set_sighandler(), rl_set_sighandler(), rl_sigaction(), rl_signal_handler(), sighandler_cxt::sa_flags, SA_RESTART, SIG_BLOCK, SIG_DFL, SIG_IGN, SIG_SETMASK, sigaddset(), SIGALRM, sigemptyset, SIGHUP, SIGINT, signals_set_flag, sigprocmask(), SIGQUIT, SIGTERM, SIGTSTP, SIGTTIN, SIGTTOU, SIGWINCH, and sigwinch_set_flag.
Referenced by _rl_callback_newline(), readline(), rl_callback_read_char(), and rl_reset_after_signal().
rl_sigaction()
static int rl_sigaction (int sig, sighandler_cxt * nh, sighandler_cxt * oh) static
Definition at line 338 of file signals.c.
 {
   oh->sa_handler = signal (sig, nh->sa_handler);
   return 0;
 }
References sighandler_cxt::sa_handler, and signal.
Referenced by rl_clear_signals(), rl_maybe_restore_sighandler(), rl_maybe_set_sighandler(), and rl_set_signals().
rl_signal_handler()
static void rl_signal_handler (int sig) static
Definition at line 155 of file signals.c.
 {
   _rl_caught_signal = sig;
   SIGHANDLER_RETURN;
 }
References _rl_caught_signal, and SIGHANDLER_RETURN.
Referenced by rl_set_sighandler(), and rl_set_signals().
Variable Documentation
_rl_caught_signal
int volatile _rl_caught_signal = 0
Definition at line 90 of file signals.c.
Referenced by _rl_signal_handler(), rl_getc(), rl_pending_signal(), and rl_signal_handler().
_rl_echoctl
int _rl_echoctl = 0
Definition at line 94 of file signals.c.
Referenced by prepare_terminal_settings(), and rl_echo_signal_char().
_rl_intr_char
int _rl_intr_char = 0
Definition at line 96 of file signals.c.
Referenced by rl_echo_signal_char(), and save_tty_chars().
_rl_quit_char
int _rl_quit_char = 0
Definition at line 97 of file signals.c.
Referenced by rl_echo_signal_char(), and save_tty_chars().
_rl_sigcleanarg
void* _rl_sigcleanarg
Definition at line 122 of file signals.c.
Referenced by _rl_handle_signal(), and rl_complete_internal().
_rl_sigcleanup
_rl_sigcleanup_func_t* _rl_sigcleanup
Definition at line 121 of file signals.c.
Referenced by _rl_handle_signal(), and rl_complete_internal().
_rl_susp_char
int _rl_susp_char = 0
Definition at line 98 of file signals.c.
Referenced by rl_echo_signal_char(), and save_tty_chars().
old_alrm
sighandler_cxt old_alrm static
Definition at line 113 of file signals.c.
Referenced by read_command(), rl_clear_signals(), and rl_set_signals().
old_hup
sighandler_cxt old_hup static
Definition at line 113 of file signals.c.
Referenced by rl_clear_signals(), and rl_set_signals().
old_int
sighandler_cxt old_int static
Definition at line 113 of file signals.c.
Referenced by _run_trap_internal(), rl_clear_signals(), and rl_set_signals().
old_quit
sighandler_cxt old_quit static
Definition at line 113 of file signals.c.
Referenced by rl_clear_signals(), and rl_set_signals().
old_term
sighandler_cxt old_term static
Definition at line 113 of file signals.c.
Referenced by rl_clear_signals(), and rl_set_signals().
rl_catch_signals
int rl_catch_signals = 1
Definition at line 80 of file signals.c.
Referenced by rl_clear_signals(), rl_restore_state(), rl_save_state(), and rl_set_signals().
rl_catch_sigwinch
int rl_catch_sigwinch = 0
Definition at line 86 of file signals.c.
Referenced by rl_clear_signals(), rl_restore_state(), rl_save_state(), and rl_set_signals().
sigint_blocked
int sigint_blocked static
Definition at line 634 of file signals.c.
Referenced by _rl_block_sigint(), and _rl_release_sigint().
signals_set_flag
int signals_set_flag static
Definition at line 100 of file signals.c.
Referenced by rl_clear_signals(), and rl_set_signals().
sigwinch_blocked
int sigwinch_blocked static
Definition at line 635 of file signals.c.
Referenced by _rl_block_sigwinch(), and _rl_release_sigwinch().
sigwinch_set_flag
int sigwinch_set_flag static
Definition at line 101 of file signals.c.
Referenced by rl_clear_signals(), and rl_set_signals().