Fennix Userspace: Userspace/musl/src/signal/sigemptyset.c File Reference
sigemptyset.c File Reference
#include <signal.h>
#include <string.h>
Functions
int sigemptyset (sigset_t *set)
Function Documentation
sigemptyset()
int sigemptyset (sigset_t * set)
Definition at line 4 of file sigemptyset.c.
 {
     set->__bits[0] = 0;
     if (sizeof(long)==4 || _NSIG > 65) set->__bits[1] = 0;
     if (sizeof(long)==4 && _NSIG > 65) {
         set->__bits[2] = 0;
         set->__bits[3] = 0;
     }
     return 0;
 }
References _NSIG.
Referenced by block_CHLD_HUP_ALRM(), devfsd_main(), exec_conf(), give_terminal_to(), initialize_shell_signals(), initialize_terminating_signals(), make_child(), nchars_avail(), notify_of_job_status(), parse_and_execute(), parse_string(), reset_terminating_signals(), rl_getc(), sig_block(), sig_unblock(), sighold(), sigignore(), sigrelse(), sigstat(), svlogd_main(), system(), trap_handler(), wait_for_any_sig(), and wait_for_seqfile().