Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/r_plane.h File Reference
r_plane.h File Reference
#include "r_data.h"
Typedefs
typedef void(* planefunction_t) (int top, int bottom)
Functions
void R_InitPlanes (void)
void R_ClearPlanes (void)
void R_MapPlane (int y, int x1, int x2)
void R_MakeSpans (int x, int t1, int b1, int t2, int b2)
void R_DrawPlanes (void)
visplane_t * R_FindPlane (fixed_t height, int picnum, int lightlevel)
visplane_t * R_CheckPlane (visplane_t *pl, int start, int stop)
Variables
short * lastopening
planefunction_t floorfunc
planefunction_t ceilingfunc_t
short floorclip [SCREENWIDTH]
short ceilingclip [SCREENWIDTH]
fixed_t yslope [SCREENHEIGHT]
fixed_t distscale [SCREENWIDTH]
Typedef Documentation
planefunction_t
typedef void(* planefunction_t) (int top, int bottom)
Definition at line 32 of file r_plane.h.
Function Documentation
R_CheckPlane()
visplane_t* R_CheckPlane (visplane_t * pl, int start, int stop)
Definition at line 259 of file r_plane.c.
 {
     int     intrl;
     int     intrh;
     int     unionl;
     int     unionh;
     int     x;
     if (start < pl->minx)
     {
     intrl = pl->minx;
     unionl = start;
     }
     else
     {
     unionl = pl->minx;
     intrl = start;
     }
     if (stop > pl->maxx)
     {
     intrh = pl->maxx;
     unionh = stop;
     }
     else
     {
     unionh = pl->maxx;
     intrh = stop;
     }
     for (x=intrl ; x<= intrh ; x++)
     if (pl->top[x] != 0xff)
         break;
     if (x > intrh)
     {
     pl->minx = unionl;
     pl->maxx = unionh;
     // use the same one
     return pl;
     }
     // make a new visplane
     lastvisplane->height = pl->height;
     lastvisplane->picnum = pl->picnum;
     lastvisplane->lightlevel = pl->lightlevel;
     pl = lastvisplane++;
     pl->minx = start;
     pl->maxx = stop;
     memset (pl->top,0xff,sizeof(pl->top));
     return pl;
 }
References visplane_t::height, lastvisplane, visplane_t::lightlevel, visplane_t::maxx, memset, visplane_t::minx, visplane_t::picnum, start, stop, visplane_t::top, and x.
Referenced by R_StoreWallRange().
R_ClearPlanes()
void R_ClearPlanes (void)
Definition at line 178 of file r_plane.c.
 {
     int     i;
     angle_t angle;
     // opening / clipping determination
     for (i=0 ; i<viewwidth ; i++)
     {
     floorclip[i] = viewheight;
     ceilingclip[i] = -1;
     }
     lastvisplane = visplanes;
     lastopening = openings;
     // texture calculation
     memset (cachedheight, 0, sizeof(cachedheight));
     // left to right mapping
     angle = (viewangle-ANG90)>>ANGLETOFINESHIFT;
     // scale will be unit scale at SCREENWIDTH/2 distance
     basexscale = FixedDiv (finecosine[angle],centerxfrac);
     baseyscale = -FixedDiv (finesine[angle],centerxfrac);
 }
References ANG90, ANGLETOFINESHIFT, basexscale, baseyscale, cachedheight, ceilingclip, centerxfrac, finecosine, finesine, FixedDiv(), floorclip, i, lastopening, lastvisplane, memset, openings, viewangle, viewheight, viewwidth, and visplanes.
Referenced by R_RenderPlayerView().
R_DrawPlanes()
void R_DrawPlanes (void)
Definition at line 360 of file r_plane.c.
 {
     visplane_t*     pl;
     int         light;
     int         x;
     int         stop;
     int         angle;
     int                 lumpnum;
 #ifdef RANGECHECK
     if (ds_p - drawsegs > MAXDRAWSEGS)
     I_Error ("R_DrawPlanes: drawsegs overflow (%i)",
          ds_p - drawsegs);
     if (lastvisplane - visplanes > MAXVISPLANES)
     I_Error ("R_DrawPlanes: visplane overflow (%i)",
          lastvisplane - visplanes);
     if (lastopening - openings > MAXOPENINGS)
     I_Error ("R_DrawPlanes: opening overflow (%i)",
          lastopening - openings);
 #endif
     for (pl = visplanes ; pl < lastvisplane ; pl++)
     {
     if (pl->minx > pl->maxx)
         continue;
     // sky flat
     if (pl->picnum == skyflatnum)
     {
         dc_iscale = pspriteiscale>>detailshift;
         // Sky is allways drawn full bright,
         //  i.e. colormaps[0] is used.
         // Because of this hack, sky is not affected
         //  by INVUL inverse mapping.
         dc_colormap = colormaps;
         dc_texturemid = skytexturemid;
         for (x=pl->minx ; x <= pl->maxx ; x++)
         {
         dc_yl = pl->top[x];
         dc_yh = pl->bottom[x];
         if (dc_yl <= dc_yh)
         {
             angle = (viewangle + xtoviewangle[x])>>ANGLETOSKYSHIFT;
             dc_x = x;
             dc_source = R_GetColumn(skytexture, angle);
             colfunc ();
         }
         }
         continue;
     }
     // regular flat
         lumpnum = firstflat + flattranslation[pl->picnum];
     ds_source = W_CacheLumpNum(lumpnum, PU_STATIC);
     planeheight = abs(pl->height-viewz);
     light = (pl->lightlevel >> LIGHTSEGSHIFT)+extralight;
     if (light >= LIGHTLEVELS)
         light = LIGHTLEVELS-1;
     if (light < 0)
         light = 0;
     planezlight = zlight[light];
     pl->top[pl->maxx+1] = 0xff;
     pl->top[pl->minx-1] = 0xff;
     stop = pl->maxx + 1;
     for (x=pl->minx ; x<= stop ; x++)
     {
         R_MakeSpans(x,pl->top[x-1],
             pl->bottom[x-1],
             pl->top[x],
             pl->bottom[x]);
     }
         W_ReleaseLumpNum(lumpnum);
     }
 }
References abs, ANGLETOSKYSHIFT, visplane_t::bottom, colfunc, colormaps, dc_colormap, dc_iscale, dc_source, dc_texturemid, dc_x, dc_yh, dc_yl, detailshift, drawsegs, ds_p, ds_source, extralight, firstflat, flattranslation, visplane_t::height, I_Error(), lastopening, lastvisplane, visplane_t::lightlevel, LIGHTLEVELS, LIGHTSEGSHIFT, MAXDRAWSEGS, MAXOPENINGS, MAXVISPLANES, visplane_t::maxx, visplane_t::minx, openings, visplane_t::picnum, planeheight, planezlight, pspriteiscale, PU_STATIC, R_GetColumn(), R_MakeSpans(), skyflatnum, skytexture, skytexturemid, stop, visplane_t::top, viewangle, viewz, visplanes, W_CacheLumpNum(), W_ReleaseLumpNum(), x, xtoviewangle, and zlight.
Referenced by R_RenderPlayerView().
R_FindPlane()
visplane_t* R_FindPlane (fixed_t height, int picnum, int lightlevel)
Definition at line 211 of file r_plane.c.
 {
     visplane_t* check;
     if (picnum == skyflatnum)
     {
     height = 0;         // all skys map together
     lightlevel = 0;
     }
     for (check=visplanes; check<lastvisplane; check++)
     {
     if (height == check->height
         && picnum == check->picnum
         && lightlevel == check->lightlevel)
     {
         break;
     }
     }
     if (check < lastvisplane)
     return check;
     if (lastvisplane - visplanes == MAXVISPLANES)
     I_Error ("R_FindPlane: no more visplanes");
     lastvisplane++;
     check->height = height;
     check->picnum = picnum;
     check->lightlevel = lightlevel;
     check->minx = SCREENWIDTH;
     check->maxx = -1;
     memset (check->top,0xff,sizeof(check->top));
     return check;
 }
References check(), height(), I_Error(), lastvisplane, MAXVISPLANES, memset, SCREENWIDTH, skyflatnum, and visplanes.
Referenced by R_Subsector().
R_InitPlanes()
void R_InitPlanes (void)
Definition at line 94 of file r_plane.c.
 {
   // Doh!
 }
Referenced by R_Init().
R_MakeSpans()
void R_MakeSpans (int x, int t1, int b1, int t2, int b2)
Definition at line 324 of file r_plane.c.
 {
     while (t1 < t2 && t1<=b1)
     {
     R_MapPlane (t1,spanstart[t1],x-1);
     t1++;
     }
     while (b1 > b2 && b1>=t1)
     {
     R_MapPlane (b1,spanstart[b1],x-1);
     b1--;
     }
     while (t2 < t1 && t2<=b2)
     {
     spanstart[t2] = x;
     t2++;
     }
     while (b2 > b1 && b2>=t2)
     {
     spanstart[b2] = x;
     b2--;
     }
 }
References R_MapPlane(), spanstart, t1, t2, and x.
Referenced by R_DrawPlanes().
R_MapPlane()
void R_MapPlane (int y, int x1, int x2)
Definition at line 114 of file r_plane.c.
 {
     angle_t angle;
     fixed_t distance;
     fixed_t length;
     unsigned    index;
 #ifdef RANGECHECK
     if (x2 < x1
      || x1 < 0
      || x2 >= viewwidth
      || y > viewheight)
     {
     I_Error ("R_MapPlane: %i, %i at %i",x1,x2,y);
     }
 #endif
     if (planeheight != cachedheight[y])
     {
     cachedheight[y] = planeheight;
     distance = cacheddistance[y] = FixedMul (planeheight, yslope[y]);
     ds_xstep = cachedxstep[y] = FixedMul (distance,basexscale);
     ds_ystep = cachedystep[y] = FixedMul (distance,baseyscale);
     }
     else
     {
     distance = cacheddistance[y];
     ds_xstep = cachedxstep[y];
     ds_ystep = cachedystep[y];
     }
     length = FixedMul (distance,distscale[x1]);
     angle = (viewangle + xtoviewangle[x1])>>ANGLETOFINESHIFT;
     ds_xfrac = viewx + FixedMul(finecosine[angle], length);
     ds_yfrac = -viewy - FixedMul(finesine[angle], length);
     if (fixedcolormap)
     ds_colormap = fixedcolormap;
     else
     {
     index = distance >> LIGHTZSHIFT;
     if (index >= MAXLIGHTZ )
         index = MAXLIGHTZ-1;
     ds_colormap = planezlight[index];
     }
     ds_y = y;
     ds_x1 = x1;
     ds_x2 = x2;
     // high or low detail
     spanfunc ();
 }
References ANGLETOFINESHIFT, basexscale, baseyscale, cacheddistance, cachedheight, cachedxstep, cachedystep, distscale, ds_colormap, ds_x1, ds_x2, ds_xfrac, ds_xstep, ds_y, ds_yfrac, ds_ystep, finecosine, finesine, fixedcolormap, FixedMul(), I_Error(), index(), LIGHTZSHIFT, MAXLIGHTZ, planeheight, planezlight, spanfunc, viewangle, viewheight, viewwidth, viewx, viewy, xtoviewangle, y, and yslope.
Referenced by R_MakeSpans().
Variable Documentation
ceilingclip
short ceilingclip[SCREENWIDTH] extern
Definition at line 63 of file r_plane.c.
Referenced by R_ClearPlanes(), R_RenderSegLoop(), and R_StoreWallRange().
ceilingfunc_t
planefunction_t ceilingfunc_t extern
distscale
fixed_t distscale[SCREENWIDTH] extern
Definition at line 79 of file r_plane.c.
Referenced by R_ExecuteSetViewSize(), and R_MapPlane().
floorclip
short floorclip[SCREENWIDTH] extern
Definition at line 62 of file r_plane.c.
Referenced by R_ClearPlanes(), R_RenderSegLoop(), and R_StoreWallRange().
floorfunc
planefunction_t floorfunc extern
Definition at line 37 of file r_plane.c.
lastopening
short* lastopening extern
Definition at line 54 of file r_plane.c.
Referenced by R_ClearPlanes(), R_DrawPlanes(), and R_StoreWallRange().
yslope
fixed_t yslope[SCREENHEIGHT] extern
Definition at line 78 of file r_plane.c.
Referenced by R_ExecuteSetViewSize(), and R_MapPlane().