Fennix: Userspace/musl/src/stdio/fflush.c File Reference
fflush.c File Reference
#include "stdio_impl.h"
Functions
weak_alias (dummy, __stdout_used)
weak_alias (dummy, __stderr_used)
int fflush (FILE *f)
weak_alias (fflush, fflush_unlocked)
Variables
static FILE *volatile dummy = 0
Function Documentation
fflush()
int fflush (FILE * f)
Definition at line 8 of file fflush.c.
 {
     if (!f) {
         int r = 0;
         if (__stdout_used) r |= fflush(__stdout_used);
         if (__stderr_used) r |= fflush(__stderr_used);
         for (f=*__ofl_lock(); f; f=f->next) {
             FLOCK(f);
             if (f->wpos != f->wbase) r |= fflush(f);
             FUNLOCK(f);
         }
         __ofl_unlock();
         return r;
     }
     FLOCK(f);
     /* If writing, flush output */
     if (f->wpos != f->wbase) {
         f->write(f, 0, 0);
         if (!f->wpos) {
             FUNLOCK(f);
             return EOF;
         }
     }
     /* If reading, sync position, per POSIX */
     if (f->rpos != f->rend) f->seek(f, f->rpos-f->rend, SEEK_CUR);
     /* Clear read and write modes */
     f->wpos = f->wbase = f->wend = 0;
     f->rpos = f->rend = 0;
     FUNLOCK(f);
     return 0;
 }
References __ofl_lock(), __ofl_unlock(), __stderr_used, __stdout_used, EINVAL, ENOSYS, EOF, errno, f, FLOCK, FUNLOCK, NULL, and SEEK_CUR.
Referenced by _flushlbf(), _rl_clean_up_for_exit(), _rl_erase_entire_line(), _rl_init_file_error(), _rl_internal_pager(), _rl_move_vert(), _rl_ttyflush(), _rl_update_final(), botch(), builtin_usage(), conf_askvalue(), conf_choice(), create_directory(), create_file(), display_matches(), do_redirection_internal(), docfunctions(), download_one_url(), dprintf(), dump_file(), evaluate(), exec_kernel_doc(), execute_builtin_or_function(), execute_subshell_builtin_or_function(), exit_shell(), fclose(), fflush_all(), fflush_stdout_and_exit(), freopen(), ftpcmd(), hello_builtin(), hello_builtin_load(), hello_builtin_unload(), I_Error(), I_InitSquashTable(), I_InitStretchTables(), id_builtin(), inotifyd_main(), line_error(), logdir_close(), main(), necho_builtin(), newline_and_flush(), parse_file(), powertop_main(), print_builtin(), print_pipeline(), print_prompt(), printst(), programming_error(), reader_loop(), readline_internal_setup(), rl_deprep_terminal(), rl_ding(), rl_prep_terminal(), rl_print_last_kbd_macro(), rl_redisplay(), rl_show_char(), rotate(), sh_chkwrite(), subshell_exit(), test_brk(), test_dirent(), test_execve_fork(), test_file(), test_passwd(), test_ptmx(), test_stdio(), test_time(), test_watch_directory(), test_watch_file(), throw_to_top_level(), update_passwd(), uuencode_main(), wait_for(), write_helpfiles(), xbotch(), xtrace_print_assignment(), xtrace_print_word_list(), and xtrace_reset().
weak_alias() [1/3]
weak_alias (dummy , __stderr_used)
weak_alias() [2/3]
weak_alias (dummy , __stdout_used)
weak_alias() [3/3]
weak_alias (fflush , fflush_unlocked)
Variable Documentation
dummy
FILE* volatile dummy (void) = 0 static
Definition at line 4 of file fflush.c.