Fennix: Userspace/musl/include/mqueue.h File Reference
mqueue.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct mq_attr
Macros
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_pthread_attr_t
#define __NEED_time_t
#define __NEED_struct_timespec
Typedefs
typedef int mqd_t
Functions
int mq_close (mqd_t)
int mq_getattr (mqd_t, struct mq_attr *)
int mq_notify (mqd_t, const struct sigevent *)
mqd_t mq_open (const char *, int,...)
ssize_t mq_receive (mqd_t, char *, size_t, unsigned *)
int mq_send (mqd_t, const char *, size_t, unsigned)
int mq_setattr (mqd_t, const struct mq_attr *__restrict, struct mq_attr *__restrict)
ssize_t mq_timedreceive (mqd_t, char *__restrict, size_t, unsigned *__restrict, const struct timespec *__restrict)
int mq_timedsend (mqd_t, const char *, size_t, unsigned, const struct timespec *)
int mq_unlink (const char *)
Data Structure Documentation
mq_attr
struct mq_attr
Definition at line 17 of file mqueue.h.
Data Fields
long __unused[4]
long mq_curmsgs
long mq_flags
long mq_maxmsg
long mq_msgsize
Macro Definition Documentation
__NEED_pthread_attr_t
#define __NEED_pthread_attr_t
Definition at line 11 of file mqueue.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 9 of file mqueue.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 10 of file mqueue.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 13 of file mqueue.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 12 of file mqueue.h.
Typedef Documentation
mqd_t
typedef int mqd_t
Definition at line 16 of file mqueue.h.
Function Documentation
mq_close()
int mq_close (mqd_t mqd)
Definition at line 4 of file mq_close.c.
 {
     return syscall(SYS_close, mqd);
 }
References syscall().
mq_getattr()
int mq_getattr (mqd_t mqd, struct mq_attr * attr)
Definition at line 4 of file mq_getattr.c.
 {
     return mq_setattr(mqd, 0, attr);
 }
References mq_setattr().
mq_notify()
int mq_notify (mqd_t mqd, const struct sigevent * sev)
Definition at line 46 of file mq_notify.c.
 {
     struct args args = { .sev = sev };
     pthread_attr_t attr;
     pthread_t td;
     int s;
     int cs;
     sigset_t allmask, origmask;
     if (!sev || sev->sigev_notify != SIGEV_THREAD)
         return syscall(SYS_mq_notify, mqd, sev);
     s = socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, 0);
     if (s < 0) return -1;
     args.sock = s;
     args.mqd = mqd;
     if (sev->sigev_notify_attributes) attr = *sev->sigev_notify_attributes;
     else pthread_attr_init(&attr);
     pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
     sem_init(&args.sem, 0, 0);
     sigfillset(&allmask);
     pthread_sigmask(SIG_BLOCK, &allmask, &origmask);
     if (pthread_create(&td, &attr, start, &args)) {
         __syscall(SYS_close, s);
         pthread_sigmask(SIG_SETMASK, &origmask, 0);
         errno = EAGAIN;
         return -1;
     }
     pthread_sigmask(SIG_SETMASK, &origmask, 0);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     sem_wait(&args.sem);
     sem_destroy(&args.sem);
     if (args.err) {
         __syscall(SYS_close, s);
         pthread_join(td, 0);
         pthread_setcancelstate(cs, 0);
         errno = args.err;
         return -1;
     }
     pthread_setcancelstate(cs, 0);
     return 0;
 }
References __syscall, AF_NETLINK, args::attr, EAGAIN, args::err, errno, args::mqd, pthread_attr_init(), pthread_attr_setdetachstate(), PTHREAD_CANCEL_DISABLE, pthread_create(), PTHREAD_CREATE_JOINABLE, pthread_join(), pthread_setcancelstate(), pthread_sigmask(), s, args::sem, sem_destroy(), sem_init(), sem_wait(), args::sev, SIG_BLOCK, SIG_SETMASK, sigfillset(), args::sock, SOCK_CLOEXEC, SOCK_RAW, socket(), start(), syscall(), and td.
mq_open()
mqd_t mq_open (const char * name, int flags, ...)
Definition at line 6 of file mq_open.c.
 {
     mode_t mode = 0;
     struct mq_attr *attr = 0;
     if (*name == '/') name++;
     if (flags & O_CREAT) {
         va_list ap;
         va_start(ap, flags);
         mode = va_arg(ap, mode_t);
         attr = va_arg(ap, struct mq_attr *);
         va_end(ap);
     }
     return syscall(SYS_mq_open, name, flags, mode, attr);
 }
References ap, flags, mode_t, O_CREAT, syscall(), va_arg, va_end, and va_start.
mq_receive()
ssize_t mq_receive (mqd_t mqd, char * msg, size_t len, unsigned * prio)
Definition at line 3 of file mq_receive.c.
 {
     return mq_timedreceive(mqd, msg, len, prio, 0);
 }
References len, and mq_timedreceive().
mq_send()
int mq_send (mqd_t mqd, const char * msg, size_t len, unsigned prio)
Definition at line 3 of file mq_send.c.
 {
     return mq_timedsend(mqd, msg, len, prio, 0);
 }
References len, and mq_timedsend().
mq_setattr()
int mq_setattr (mqd_t , const struct mq_attr * __restrict, struct mq_attr * __restrict)
Referenced by mq_getattr().
mq_timedreceive()
ssize_t mq_timedreceive (mqd_t , char * __restrict, size_t , unsigned * __restrict, const struct timespec * __restrict)
Referenced by __mq_timedreceive_time32(), and mq_receive().
mq_timedsend()
int mq_timedsend (mqd_t mqd, const char * msg, size_t len, unsigned prio, const struct timespec * at)
Definition at line 8 of file mq_timedsend.c.
 {
 #ifdef SYS_mq_timedsend_time64
     time_t s = at ? at->tv_sec : 0;
     long ns = at ? at->tv_nsec : 0;
     long r = -ENOSYS;
     if (SYS_mq_timedsend == SYS_mq_timedsend_time64 || !IS32BIT(s))
         r = __syscall_cp(SYS_mq_timedsend_time64, mqd, msg, len, prio,
             at ? ((long long []){at->tv_sec, at->tv_nsec}) : 0);
     if (SYS_mq_timedsend == SYS_mq_timedsend_time64 || r != -ENOSYS)
         return __syscall_ret(r);
     return syscall_cp(SYS_mq_timedsend, mqd, msg, len, prio,
         at ? ((long[]){CLAMP(s), ns}) : 0);
 #else
     return syscall_cp(SYS_mq_timedsend, mqd, msg, len, prio, at);
 #endif
 }
References __syscall_cp, __syscall_ret(), CLAMP, ENOSYS, IS32BIT, len, s, SYS_mq_timedsend, SYS_mq_timedsend_time64, syscall_cp, timespec::tv_nsec, and timespec::tv_sec.
Referenced by __mq_timedsend_time32(), and mq_send().
mq_unlink()
int mq_unlink (const char * name)
Definition at line 5 of file mq_unlink.c.
 {
     int ret;
     if (*name == '/') name++;
     ret = __syscall(SYS_mq_unlink, name);
     if (ret < 0) {
         if (ret == -EPERM) ret = -EACCES;
         errno = -ret;
         return -1;
     }
     return ret;
 }
References __syscall, EACCES, EPERM, and errno.