Fennix: Userspace/apps/base/busybox/util-linux/swaponoff.c File Reference
swaponoff.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <mntent.h>
#include <sys/swap.h>
Macros
#define resolve_mount_spec(fsname) ((void)0)
#define MNTTYPE_SWAP "swap"
#define g_flags 0
#define save_g_flags() ((void)0)
#define restore_g_flags() ((void)0)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define do_swapoff 0
#define OPT_ALL (option_mask32 & OPT_a)
#define OPT_DISCARD (option_mask32 & OPT_d)
#define OPT_IFEXISTS (option_mask32 & OPT_e)
#define OPT_PRIO (option_mask32 & OPT_p)
#define set_discard_flag(s) ((void)0)
#define set_priority_flag(s) ((void)0)
#define OPTSTR_SWAPON
Enumerations
enum {
OPTBIT_a , OPTBIT_e , IF_FEATURE_SWAPON_DISCARD , OPT_e = 1 << OPTBIT_e ,
OPT_d = IF_FEATURE_SWAPON_DISCARD((1 << OPTBIT_d)) + 0 , OPT_p = IF_FEATURE_SWAPON_PRI ((1 << OPTBIT_p)) + 0
}
Functions
static int swap_enable_disable (char *device)
static int do_em_all_in_fstab (void)
static int do_all_in_proc_swaps (void)
int swap_on_off_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
do_swapoff
#define do_swapoff 0
Definition at line 129 of file swaponoff.c.
g_flags
#define g_flags 0
Definition at line 116 of file swaponoff.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 120 of file swaponoff.c.
MNTTYPE_SWAP
#define MNTTYPE_SWAP "swap"
Definition at line 89 of file swaponoff.c.
OPT_ALL
#define OPT_ALL (option_mask32 & OPT_a)
Definition at line 144 of file swaponoff.c.
OPT_DISCARD
#define OPT_DISCARD (option_mask32 & OPT_d)
Definition at line 145 of file swaponoff.c.
OPT_IFEXISTS
#define OPT_IFEXISTS (option_mask32 & OPT_e)
Definition at line 146 of file swaponoff.c.
OPT_PRIO
#define OPT_PRIO (option_mask32 & OPT_p)
Definition at line 147 of file swaponoff.c.
OPTSTR_SWAPON
#define OPTSTR_SWAPON
Value:
    "ae" \
    IF_FEATURE_SWAPON_DISCARD("d::") \
    IF_FEATURE_SWAPON_PRI("p:")
Definition at line 293 of file swaponoff.c.
resolve_mount_spec
#define resolve_mount_spec (fsname) ((void)0)
Definition at line 85 of file swaponoff.c.
restore_g_flags
#define restore_g_flags () ((void)0)
Definition at line 118 of file swaponoff.c.
save_g_flags
#define save_g_flags () ((void)0)
Definition at line 117 of file swaponoff.c.
set_discard_flag
#define set_discard_flag (s) ((void)0)
Definition at line 208 of file swaponoff.c.
set_priority_flag
#define set_priority_flag (s) ((void)0)
Definition at line 228 of file swaponoff.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTBIT_a
OPTBIT_e
IF_FEATURE_SWAPON_DISCARD
OPT_e
OPT_d
OPT_p
Definition at line 133 of file swaponoff.c.
      {
     OPTBIT_a,                              /* -a all      */
     OPTBIT_e,                              /* -e ifexists */
     IF_FEATURE_SWAPON_DISCARD( OPTBIT_d ,) /* -d discard  */
     IF_FEATURE_SWAPON_PRI    ( OPTBIT_p ,) /* -p priority */
     OPT_a = 1 << OPTBIT_a,
     OPT_e = 1 << OPTBIT_e,
     OPT_d = IF_FEATURE_SWAPON_DISCARD((1 << OPTBIT_d)) + 0,
     OPT_p = IF_FEATURE_SWAPON_PRI    ((1 << OPTBIT_p)) + 0,
 };
Function Documentation
do_all_in_proc_swaps()
static int do_all_in_proc_swaps (void) static
Definition at line 272 of file swaponoff.c.
 {
     char *line;
     int err = 0;
     FILE *f = fopen_for_read("/proc/swaps");
     /* Don't complain if missing */
     if (f) {
         while ((line = xmalloc_fgetline(f)) != NULL) {
             if (line[0] == '/') {
                 *strchrnul(line, ' ') = '\0';
                 err |= swap_enable_disable(line);
             }
             free(line);
         }
         if (ENABLE_FEATURE_CLEAN_UP)
             fclose(f);
     }
     return err;
 }
References err(), f, fclose(), fopen_for_read(), free, line, NULL, strchrnul(), swap_enable_disable(), and xmalloc_fgetline().
Referenced by swap_on_off_main().
do_em_all_in_fstab()
static int do_em_all_in_fstab (void) static
Definition at line 231 of file swaponoff.c.
 {
     struct mntent *m;
     int err = 0;
     FILE *f = xfopen_for_read("/etc/fstab");
     while ((m = getmntent(f)) != NULL) {
         if (strcmp(m->mnt_type, MNTTYPE_SWAP) == 0) {
             /* swapon -a should ignore entries with noauto,
              * but swapoff -a should process them
              */
             if (do_swapoff || hasmntopt(m, MNTOPT_NOAUTO) == NULL) {
                 /* each swap space might have different flags */
                 /* save global flags for the next round */
                 save_g_flags();
                 if (ENABLE_FEATURE_SWAPON_DISCARD) {
                     char *p = hasmntopt(m, "discard");
                     if (p) {
                         /* move to '=' or to end of string */
                         p += 7;
                         set_discard_flag(p);
                     }
                 }
                 if (ENABLE_FEATURE_SWAPON_PRI) {
                     char *p = hasmntopt(m, "pri");
                     if (p) {
                         set_priority_flag(p + 4);
                     }
                 }
                 err |= swap_enable_disable(m->mnt_fsname);
                 restore_g_flags();
             }
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         endmntent(f);
     return err;
 }
References do_swapoff, endmntent(), err(), f, getmntent(), hasmntopt(), mntent::mnt_fsname, mntent::mnt_type, MNTOPT_NOAUTO, MNTTYPE_SWAP, NULL, p, restore_g_flags, save_g_flags, set_discard_flag, set_priority_flag, strcmp, swap_enable_disable(), and xfopen_for_read().
Referenced by swap_on_off_main().
swap_enable_disable()
static int swap_enable_disable (char * device) static
Definition at line 149 of file swaponoff.c.
 {
     int err = 0;
     int quiet = 0;
     resolve_mount_spec(&device);
     if (do_swapoff) {
         err = swapoff(device);
         /* Don't complain on OPT_ALL if not a swap device or if it doesn't exist */
         quiet = (OPT_ALL && (errno == EINVAL || errno == ENOENT));
     } else {
         /* swapon */
         struct stat st;
         err = stat(device, &st);
         if (!err) {
             if (ENABLE_DESKTOP && S_ISREG(st.st_mode)) {
                 if (st.st_blocks * (off_t)512 < st.st_size) {
                     bb_error_msg("%s: file has holes", device);
                     return 1;
                 }
             }
             err = swapon(device, g_flags);
             /* Don't complain on swapon -a if device is already in use */
             quiet = (OPT_ALL && errno == EBUSY);
         }
         /* Don't complain if file does not exist with -e option */
         if (err && OPT_IFEXISTS && errno == ENOENT)
             err = 0;
     }
     if (err && !quiet) {
         bb_simple_perror_msg(device);
         return 1;
     }
     return 0;
 }
References bb_error_msg(), bb_simple_perror_msg(), device, do_swapoff, EBUSY, EINVAL, ENOENT, err(), errno, g_flags, off_t, OPT_ALL, OPT_IFEXISTS, resolve_mount_spec, S_ISREG, stat(), swapoff(), and swapon().
Referenced by do_all_in_proc_swaps(), do_em_all_in_fstab(), and swap_on_off_main().
swap_on_off_main()
int swap_on_off_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 298 of file swaponoff.c.
 {
     IF_FEATURE_SWAPON_PRI(char *prio;)
     IF_FEATURE_SWAPON_DISCARD(char *discard = NULL;)
     int ret = 0;
     INIT_G();
     getopt32(argv, do_swapoff ? "ae" : OPTSTR_SWAPON
             IF_FEATURE_SWAPON_DISCARD(, &discard)
             IF_FEATURE_SWAPON_PRI(, &prio)
     );
     argv += optind;
     if (OPT_DISCARD) {
         set_discard_flag(discard);
     }
     if (OPT_PRIO) {
         set_priority_flag(prio);
     }
     if (OPT_ALL) {
         /* swapoff -a does also /proc/swaps */
         if (do_swapoff)
             ret = do_all_in_proc_swaps();
         ret |= do_em_all_in_fstab();
     } else if (!*argv) {
         /* if not -a we need at least one arg */
         bb_show_usage();
     }
     /* Unset -a now to allow for more messages in swap_enable_disable */
     option_mask32 = option_mask32 & ~OPT_a;
     /* Now process devices on the commandline if any */
     while (*argv) {
         ret |= swap_enable_disable(*argv++);
     }
     return ret;
 }
References argv, bb_show_usage(), do_all_in_proc_swaps(), do_em_all_in_fstab(), do_swapoff, getopt32(), IF_FEATURE_SWAPON_DISCARD, INIT_G, NULL, OPT_a, OPT_ALL, OPT_DISCARD, OPT_PRIO, optind, option_mask32, OPTSTR_SWAPON, set_discard_flag, set_priority_flag, and swap_enable_disable().