Fennix: Userspace/apps/base/busybox/libbb/xconnect.c File Reference
xconnect.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <net/if.h>
#include <sys/un.h>
#include "libbb.h"
Macros
#define DIE_ON_ERROR AI_CANONNAME
#define str2sockaddr(host, port, af, ai_flags) str2sockaddr(host, port, ai_flags)
#define IGNORE_PORT NI_NUMERICSERV
#define NI_NUMERICSCOPE 0
Functions
int FAST_FUNC setsockopt_int (int fd, int level, int optname, int optval)
int FAST_FUNC setsockopt_1 (int fd, int level, int optname)
int FAST_FUNC setsockopt_SOL_SOCKET_int (int fd, int optname, int optval)
int FAST_FUNC setsockopt_SOL_SOCKET_1 (int fd, int optname)
void FAST_FUNC setsockopt_reuseaddr (int fd)
int FAST_FUNC setsockopt_broadcast (int fd)
int FAST_FUNC setsockopt_keepalive (int fd)
int FAST_FUNC setsockopt_bindtodevice (int fd UNUSED_PARAM, const char *iface UNUSED_PARAM)
static len_and_sockaddr * get_lsa (int fd, int(*get_name)(int fd, struct sockaddr *addr, socklen_t *addrlen))
len_and_sockaddr *FAST_FUNC get_sock_lsa (int fd)
len_and_sockaddr *FAST_FUNC get_peer_lsa (int fd)
void FAST_FUNC xconnect (int s, const struct sockaddr *s_addr, socklen_t addrlen)
unsigned FAST_FUNC bb_lookup_port (const char *port, const char *protocol, unsigned port_nr)
int FAST_FUNC get_nport (const struct sockaddr *sa)
void FAST_FUNC set_nport (struct sockaddr *sa, unsigned port)
static len_and_sockaddr * str2sockaddr (const char *host, int port, int ai_flags)
len_and_sockaddr *FAST_FUNC host2sockaddr (const char *host, int port)
len_and_sockaddr *FAST_FUNC xhost2sockaddr (const char *host, int port)
len_and_sockaddr *FAST_FUNC xdotted2sockaddr (const char *host, int port)
int FAST_FUNC xsocket_type (len_and_sockaddr **lsap, int family, int sock_type)
int FAST_FUNC xsocket_stream (len_and_sockaddr **lsap)
static int create_and_bind_or_die (const char *bindaddr, int port, int sock_type)
int FAST_FUNC create_and_bind_stream_or_die (const char *bindaddr, int port)
int FAST_FUNC create_and_bind_dgram_or_die (const char *bindaddr, int port)
int FAST_FUNC create_and_connect_stream_or_die (const char *peer, int port)
int FAST_FUNC xconnect_stream (const len_and_sockaddr *lsa)
static char *FAST_FUNC sockaddr2str (const struct sockaddr *sa, int flags)
char *FAST_FUNC xmalloc_sockaddr2host (const struct sockaddr *sa)
char *FAST_FUNC xmalloc_sockaddr2host_noport (const struct sockaddr *sa)
char *FAST_FUNC xmalloc_sockaddr2hostonly_noport (const struct sockaddr *sa)
char *FAST_FUNC xmalloc_sockaddr2dotted (const struct sockaddr *sa)
char *FAST_FUNC xmalloc_sockaddr2dotted_noport (const struct sockaddr *sa)
Macro Definition Documentation
DIE_ON_ERROR
#define DIE_ON_ERROR AI_CANONNAME
Definition at line 172 of file xconnect.c.
IGNORE_PORT
#define IGNORE_PORT NI_NUMERICSERV
Definition at line 469 of file xconnect.c.
NI_NUMERICSCOPE
#define NI_NUMERICSCOPE 0
Definition at line 531 of file xconnect.c.
str2sockaddr
#define str2sockaddr (host, port, af, ai_flags) str2sockaddr(host, port, ai_flags)
Definition at line 311 of file xconnect.c.
Function Documentation
bb_lookup_port()
unsigned FAST_FUNC bb_lookup_port (const char * port, const char * protocol, unsigned port_nr)
Definition at line 121 of file xconnect.c.
 {
     if (port) {
         port_nr = bb_strtou(port, NULL, 10);
         if (errno || port_nr > 65535) {
             struct servent *tserv = getservbyname(port, protocol);
             if (!tserv)
                 bb_error_msg_and_die("bad port '%s'", port);
             port_nr = ntohs(tserv->s_port);
         }
     }
     return (uint16_t)port_nr;
 }
References bb_error_msg_and_die(), bb_strtou(), errno, getservbyname(), ntohs(), NULL, port, and servent::s_port.
Referenced by ftpgetput_main(), nc_main(), tcpudpsvd_main(), and telnet_main().
create_and_bind_dgram_or_die()
int FAST_FUNC create_and_bind_dgram_or_die (const char * bindaddr, int port)
Definition at line 405 of file xconnect.c.
 {
     return create_and_bind_or_die(bindaddr, port, SOCK_DGRAM);
 }
References create_and_bind_or_die(), port, and SOCK_DGRAM.
Referenced by ntp_init().
create_and_bind_or_die()
static int create_and_bind_or_die (const char * bindaddr, int port, int sock_type) static
Definition at line 381 of file xconnect.c.
 {
     int fd;
     len_and_sockaddr *lsa;
     if (bindaddr && bindaddr[0]) {
         lsa = xdotted2sockaddr(bindaddr, port);
         /* user specified bind addr dictates family */
         fd = xsocket(lsa->u.sa.sa_family, sock_type, 0);
     } else {
         fd = xsocket_type(&lsa, AF_UNSPEC, sock_type);
         set_nport(&lsa->u.sa, htons(port));
     }
     setsockopt_reuseaddr(fd);
     xbind(fd, &lsa->u.sa, lsa->len);
     free(lsa);
     return fd;
 }
References AF_UNSPEC, fd, free, htons(), lsa, port, set_nport(), setsockopt_reuseaddr(), xbind(), xdotted2sockaddr(), xsocket(), and xsocket_type().
Referenced by create_and_bind_dgram_or_die(), and create_and_bind_stream_or_die().
create_and_bind_stream_or_die()
int FAST_FUNC create_and_bind_stream_or_die (const char * bindaddr, int port)
Definition at line 400 of file xconnect.c.
 {
     return create_and_bind_or_die(bindaddr, port, SOCK_STREAM);
 }
References create_and_bind_or_die(), port, and SOCK_STREAM.
Referenced by fakeidentd_main(), nc_main(), openServer(), and telnetd_main().
create_and_connect_stream_or_die()
int FAST_FUNC create_and_connect_stream_or_die (const char * peer, int port)
Definition at line 447 of file xconnect.c.
 {
     int fd;
     len_and_sockaddr *lsa;
     lsa = xhost2sockaddr(peer, port);
     fd = xsocket(lsa->u.sa.sa_family, SOCK_STREAM, 0);
     setsockopt_reuseaddr(fd);
     xconnect(fd, &lsa->u.sa, lsa->len);
     free(lsa);
     return fd;
 }
References fd, free, lsa, peer, port, setsockopt_reuseaddr(), SOCK_STREAM, xconnect(), xhost2sockaddr(), and xsocket().
Referenced by askremotedate(), lpqr_main(), nbdclient_main(), nc_main(), query(), sendmail_main(), ssl_client_main(), and telnet_main().
get_lsa()
static len_and_sockaddr* get_lsa (int fd, int(*)(int fd, struct sockaddr *addr, socklen_t *addrlen) get_name) static
Definition at line 74 of file xconnect.c.
 {
     len_and_sockaddr lsa;
     len_and_sockaddr *lsa_ptr;
     lsa.len = LSA_SIZEOF_SA;
     if (get_name(fd, &lsa.u.sa, &lsa.len) != 0)
         return NULL;
     lsa_ptr = xzalloc(LSA_LEN_SIZE + lsa.len);
     if (lsa.len > LSA_SIZEOF_SA) { /* rarely (if ever) happens */
         lsa_ptr->len = lsa.len;
         get_name(fd, &lsa_ptr->u.sa, &lsa_ptr->len);
     } else {
         memcpy(lsa_ptr, &lsa, LSA_LEN_SIZE + lsa.len);
     }
     return lsa_ptr;
 }
References fd, get_name(), len_and_sockaddr::len, lsa, LSA_LEN_SIZE, LSA_SIZEOF_SA, memcpy, NULL, len_and_sockaddr::u, and xzalloc().
Referenced by get_peer_lsa(), and get_sock_lsa().
get_nport()
int FAST_FUNC get_nport (const struct sockaddr * sa)
Definition at line 139 of file xconnect.c.
 {
 #if ENABLE_FEATURE_IPV6
     if (sa->sa_family == AF_INET6) {
         return ((struct sockaddr_in6*)sa)->sin6_port;
     }
 #endif
     if (sa->sa_family == AF_INET) {
         return ((struct sockaddr_in*)sa)->sin_port;
     }
     /* What? UNIX socket? IPX?? :) */
     return -1;
 }
References AF_INET, AF_INET6, and sockaddr::sa_family.
Referenced by bind_for_passive_mode(), dolisten(), and nc_main().
get_peer_lsa()
len_and_sockaddr* FAST_FUNC get_peer_lsa (int fd)
Definition at line 98 of file xconnect.c.
 {
     return get_lsa(fd, getpeername);
 }
References fd, get_lsa(), and getpeername().
Referenced by handle_port(), and make_new_session().
get_sock_lsa()
len_and_sockaddr* FAST_FUNC get_sock_lsa (int fd)
Definition at line 93 of file xconnect.c.
 {
     return get_lsa(fd, getsockname);
 }
References fd, get_lsa(), and getsockname().
Referenced by ftpd_main(), and traceroute_init().
host2sockaddr()
len_and_sockaddr* FAST_FUNC host2sockaddr (const char * host, int port)
Definition at line 326 of file xconnect.c.
 {
     return str2sockaddr(host, port, AF_UNSPEC, 0);
 }
References AF_UNSPEC, port, and str2sockaddr.
Referenced by handle_incoming_and_exit(), resolve_peer_hostname(), and singlemount().
set_nport()
void FAST_FUNC set_nport (struct sockaddr * sa, unsigned port)
Definition at line 153 of file xconnect.c.
 {
 #if ENABLE_FEATURE_IPV6
     if (sa->sa_family == AF_INET6) {
         struct sockaddr_in6 *sin6 = (void*) sa;
         sin6->sin6_port = port;
         return;
     }
 #endif
     if (sa->sa_family == AF_INET) {
         struct sockaddr_in *sin = (void*) sa;
         sin->sin_port = port;
         return;
     }
     /* What? UNIX socket? IPX?? :) */
 }
References AF_INET, AF_INET6, port, sockaddr::sa_family, sin, and sockaddr_in6::sin6_port.
Referenced by bind_for_passive_mode(), create_and_bind_or_die(), dolisten(), handle_port(), nc_main(), prepare_socket_fd(), pscan_main(), reread_config_file(), send_probe(), str2sockaddr(), tcpudpsvd_main(), traceroute_init(), and xconnect_ftpdata().
setsockopt_1()
int FAST_FUNC setsockopt_1 (int fd, int level, int optname)
Definition at line 23 of file xconnect.c.
 {
     return setsockopt_int(fd, level, optname, 1);
 }
References fd, and setsockopt_int().
Referenced by ftpd_main(), nbdclient_main(), socket_want_pktinfo(), traceroute_init(), and udhcp_raw_socket().
setsockopt_bindtodevice()
int FAST_FUNC setsockopt_bindtodevice (int fd UNUSED_PARAM, const char *iface UNUSED_PARAM)
Definition at line 66 of file xconnect.c.
 {
     bb_simple_error_msg("SO_BINDTODEVICE is not supported on this system");
     return -1;
 }
References bb_simple_error_msg().
setsockopt_broadcast()
int FAST_FUNC setsockopt_broadcast (int fd)
Definition at line 40 of file xconnect.c.
 {
     return setsockopt_SOL_SOCKET_1(fd, SO_BROADCAST);
 }
References fd, setsockopt_SOL_SOCKET_1(), and SO_BROADCAST.
Referenced by arpping(), d6_listen_socket(), ether_wake_main(), nc_main(), and udhcp_listen_socket().
setsockopt_int()
int FAST_FUNC setsockopt_int (int fd, int level, int optname, int optval)
Definition at line 19 of file xconnect.c.
 {
     return setsockopt(fd, level, optname, &optval, sizeof(int));
 }
References fd, and setsockopt().
Referenced by ntp_init(), send_probe(), send_query_to_peer(), setsockopt_1(), setsockopt_SOL_SOCKET_int(), and traceroute_init().
setsockopt_keepalive()
int FAST_FUNC setsockopt_keepalive (int fd)
Definition at line 44 of file xconnect.c.
 {
     return setsockopt_SOL_SOCKET_1(fd, SO_KEEPALIVE);
 }
References fd, setsockopt_SOL_SOCKET_1(), and SO_KEEPALIVE.
Referenced by ftpd_main(), ftpdataio_get_pasv_fd(), make_new_session(), mini_httpd_nommu(), and telnet_main().
setsockopt_reuseaddr()
void FAST_FUNC setsockopt_reuseaddr (int fd)
Definition at line 36 of file xconnect.c.
 {
     setsockopt_SOL_SOCKET_1(fd, SO_REUSEADDR);
 }
References fd, setsockopt_SOL_SOCKET_1(), and SO_REUSEADDR.
Referenced by bind_for_passive_mode(), create_and_bind_or_die(), create_and_connect_stream_or_die(), d6_listen_socket(), d6_send_kernel_packet_from_client_data_ifindex(), inetd_main(), nc_main(), prepare_socket_fd(), tcpudpsvd_main(), udhcp_listen_socket(), and udhcp_send_kernel_packet().
setsockopt_SOL_SOCKET_1()
int FAST_FUNC setsockopt_SOL_SOCKET_1 (int fd, int optname)
Definition at line 31 of file xconnect.c.
 {
     return setsockopt_SOL_SOCKET_int(fd, optname, 1);
 }
References fd, and setsockopt_SOL_SOCKET_int().
Referenced by setsockopt_broadcast(), setsockopt_keepalive(), setsockopt_reuseaddr(), and traceroute_init().
setsockopt_SOL_SOCKET_int()
int FAST_FUNC setsockopt_SOL_SOCKET_int (int fd, int optname, int optval)
Definition at line 27 of file xconnect.c.
 {
     return setsockopt_int(fd, SOL_SOCKET, optname, optval);
 }
References fd, setsockopt_int(), and SOL_SOCKET.
Referenced by nc_main(), setsockopt_SOL_SOCKET_1(), and traceroute_init().
sockaddr2str()
static char* FAST_FUNC sockaddr2str (const struct sockaddr * sa, int flags) static
Definition at line 470 of file xconnect.c.
 {
     char host[128];
     char serv[16];
     int rc;
     socklen_t salen;
     if (ENABLE_FEATURE_UNIX_LOCAL && sa->sa_family == AF_UNIX) {
         struct sockaddr_un *sun = (struct sockaddr_un *)sa;
         return xasprintf("local:%.*s",
                 (int) sizeof(sun->sun_path),
                 sun->sun_path);
     }
     salen = LSA_SIZEOF_SA;
 #if ENABLE_FEATURE_IPV6
     if (sa->sa_family == AF_INET)
         salen = sizeof(struct sockaddr_in);
     if (sa->sa_family == AF_INET6)
         salen = sizeof(struct sockaddr_in6);
 #endif
     rc = getnameinfo(sa, salen,
             host, sizeof(host),
     /* can do ((flags & IGNORE_PORT) ? NULL : serv) but why bother? */
             serv, sizeof(serv),
             /* do not resolve port# into service _name_ */
             flags | NI_NUMERICSERV
     );
     if (rc)
         return NULL;
     if (flags & IGNORE_PORT)
         return xstrdup(host);
 #if ENABLE_FEATURE_IPV6
     if (sa->sa_family == AF_INET6) {
         if (strchr(host, ':')) /* heh, it's not a resolved hostname */
             return xasprintf("[%s]:%s", host, serv);
         /*return xasprintf("%s:%s", host, serv);*/
         /* - fall through instead */
     }
 #endif
     /* For now we don't support anything else, so it has to be INET */
     /*if (sa->sa_family == AF_INET)*/
         return xasprintf("%s:%s", host, serv);
     /*return xstrdup(host);*/
 }
References AF_INET, AF_INET6, AF_UNIX, flags, getnameinfo(), IGNORE_PORT, LSA_SIZEOF_SA, NI_NUMERICSERV, NULL, rc, sockaddr::sa_family, strchr(), sockaddr_un::sun_path, xasprintf(), and xstrdup().
Referenced by xmalloc_sockaddr2dotted(), xmalloc_sockaddr2dotted_noport(), xmalloc_sockaddr2host(), xmalloc_sockaddr2host_noport(), and xmalloc_sockaddr2hostonly_noport().
str2sockaddr()
static len_and_sockaddr* str2sockaddr (const char * host, int port, int ai_flags) static
Definition at line 176 of file xconnect.c.
 {
 IF_NOT_FEATURE_IPV6(sa_family_t af = AF_INET;)
     int rc;
     len_and_sockaddr *r;
     struct addrinfo *result = NULL;
     struct addrinfo *used_res;
     const char *org_host = host; /* only for error msg */
     const char *cp;
     struct addrinfo hint;
     if (ENABLE_FEATURE_UNIX_LOCAL && is_prefixed_with(host, "local:")) {
         struct sockaddr_un *sun;
         r = xzalloc(LSA_LEN_SIZE + sizeof(struct sockaddr_un));
         r->len = sizeof(struct sockaddr_un);
         r->u.sa.sa_family = AF_UNIX;
         sun = (struct sockaddr_un *)&r->u.sa;
         safe_strncpy(sun->sun_path, host + 6, sizeof(sun->sun_path));
         return r;
     }
     r = NULL;
     /* Ugly parsing of host:addr */
     if (ENABLE_FEATURE_IPV6 && host[0] == '[') {
         /* Even uglier parsing of [xx]:nn */
         host++;
         cp = strchr(host, ']');
         if (!cp || (cp[1] != ':' && cp[1] != '\0')) {
             /* Malformed: must be [xx]:nn or [xx] */
             bb_error_msg("bad address '%s'", org_host);
             if (ai_flags & DIE_ON_ERROR)
                 xfunc_die();
             return NULL;
         }
     } else {
         cp = strrchr(host, ':');
         if (ENABLE_FEATURE_IPV6 && cp && strchr(host, ':') != cp) {
             /* There is more than one ':' (e.g. "::1") */
             cp = NULL; /* it's not a port spec */
         }
     }
     if (cp) { /* points to ":" or "]:" */
         int sz = cp - host + 1;
         host = safe_strncpy(alloca(sz), host, sz);
         if (ENABLE_FEATURE_IPV6 && *cp != ':') {
             cp++; /* skip ']' */
             if (*cp == '\0') /* [xx] without port */
                 goto skip;
         }
         cp++; /* skip ':' */
         port = bb_strtou(cp, NULL, 10);
         if (errno || (unsigned)port > 0xffff) {
             bb_error_msg("bad port '%s'", cp);
             if (ai_flags & DIE_ON_ERROR)
                 xfunc_die();
             return NULL;
         }
  skip: ;
     }
     /* Next two if blocks allow to skip getaddrinfo()
      * in case host name is a numeric IP(v6) address.
      * getaddrinfo() initializes DNS resolution machinery,
      * scans network config and such - tens of syscalls.
      */
     /* If we were not asked specifically for IPv6,
      * check whether this is a numeric IPv4 */
     IF_FEATURE_IPV6(if(af != AF_INET6)) {
         struct in_addr in4;
         if (inet_aton(host, &in4) != 0) {
             r = xzalloc(LSA_LEN_SIZE + sizeof(struct sockaddr_in));
             r->len = sizeof(struct sockaddr_in);
             r->u.sa.sa_family = AF_INET;
             r->u.sin.sin_addr = in4;
             goto set_port;
         }
     }
 #if ENABLE_FEATURE_IPV6
     /* If we were not asked specifically for IPv4,
      * check whether this is a numeric IPv6 */
     if (af != AF_INET) {
         struct in6_addr in6;
         if (inet_pton(AF_INET6, host, &in6) > 0) {
             r = xzalloc(LSA_LEN_SIZE + sizeof(struct sockaddr_in6));
             r->len = sizeof(struct sockaddr_in6);
             r->u.sa.sa_family = AF_INET6;
             r->u.sin6.sin6_addr = in6;
             goto set_port;
         }
     }
 #endif
     memset(&hint, 0 , sizeof(hint));
     hint.ai_family = af;
     /* Need SOCK_STREAM, or else we get each address thrice (or more)
      * for each possible socket type (tcp,udp,raw...): */
     hint.ai_socktype = SOCK_STREAM;
     hint.ai_flags = ai_flags & ~DIE_ON_ERROR;
     rc = getaddrinfo(host, NULL, &hint, &result);
     if (rc || !result) {
         bb_error_msg("bad address '%s'", org_host);
         if (ai_flags & DIE_ON_ERROR)
             xfunc_die();
         goto ret;
     }
     used_res = result;
 #if ENABLE_FEATURE_PREFER_IPV4_ADDRESS
     while (1) {
         if (used_res->ai_family == AF_INET)
             break;
         used_res = used_res->ai_next;
         if (!used_res) {
             used_res = result;
             break;
         }
     }
 #endif
     r = xmalloc(LSA_LEN_SIZE + used_res->ai_addrlen);
     r->len = used_res->ai_addrlen;
     memcpy(&r->u.sa, used_res->ai_addr, used_res->ai_addrlen);
  set_port:
     set_nport(&r->u.sa, htons(port));
  ret:
     if (result)
         freeaddrinfo(result);
     return r;
 }
References AF_INET, AF_INET6, AF_UNIX, addrinfo::ai_addr, addrinfo::ai_addrlen, addrinfo::ai_family, addrinfo::ai_flags, addrinfo::ai_next, addrinfo::ai_socktype, alloca, bb_error_msg(), bb_strtou(), DIE_ON_ERROR, errno, freeaddrinfo(), getaddrinfo(), htons(), IF_FEATURE_IPV6(), inet_aton(), inet_pton(), is_prefixed_with(), LSA_LEN_SIZE, memcpy, memset, NULL, port, rc, safe_strncpy(), set_nport(), skip, SOCK_STREAM, strchr(), strrchr(), sockaddr_un::sun_path, xfunc_die(), xmalloc, and xzalloc().
xconnect()
void FAST_FUNC xconnect (int s, const struct sockaddr * s_addr, socklen_t addrlen)
Definition at line 103 of file xconnect.c.
 {
     if (connect(s, s_addr, addrlen) < 0) {
         if (ENABLE_FEATURE_CLEAN_UP)
             close(s);
         if (s_addr->sa_family == AF_INET)
             bb_perror_msg_and_die("%s (%s)",
                 "can't connect to remote host",
                 inet_ntoa(((struct sockaddr_in *)s_addr)->sin_addr));
         bb_simple_perror_msg_and_die("can't connect to remote host");
     }
 }
References AF_INET, bb_perror_msg_and_die(), bb_simple_perror_msg_and_die(), close(), connect(), inet_ntoa(), s, and sockaddr::sa_family.
Referenced by create_and_connect_stream_or_die(), dolisten(), tcpudpsvd_main(), traceroute_init(), and xconnect_stream().
xconnect_stream()
int FAST_FUNC xconnect_stream (const len_and_sockaddr * lsa)
Definition at line 460 of file xconnect.c.
 {
     int fd = xsocket(lsa->u.sa.sa_family, SOCK_STREAM, 0);
     xconnect(fd, &lsa->u.sa, lsa->len);
     return fd;
 }
References fd, lsa, SOCK_STREAM, xconnect(), and xsocket().
Referenced by ftp_login(), get_remote_transfer_fd(), open_socket(), and xconnect_ftpdata().
xdotted2sockaddr()
len_and_sockaddr* FAST_FUNC xdotted2sockaddr (const char * host, int port)
Definition at line 336 of file xconnect.c.
 {
     return str2sockaddr(host, port, AF_UNSPEC, AI_NUMERICHOST | DIE_ON_ERROR);
 }
References AF_UNSPEC, AI_NUMERICHOST, DIE_ON_ERROR, port, and str2sockaddr.
Referenced by create_and_bind_or_die(), dnsd_main(), handle_port(), and traceroute_init().
xhost2sockaddr()
len_and_sockaddr* FAST_FUNC xhost2sockaddr (const char * host, int port)
Definition at line 331 of file xconnect.c.
 {
     return str2sockaddr(host, port, AF_UNSPEC, DIE_ON_ERROR);
 }
References AF_UNSPEC, DIE_ON_ERROR, port, and str2sockaddr.
Referenced by create_and_connect_stream_or_die(), download_one_url(), ftpgetput_main(), ifconfig_main(), nc_main(), nfsmount(), pscan_main(), set_default_dns(), and tcpudpsvd_main().
xmalloc_sockaddr2dotted()
char* FAST_FUNC xmalloc_sockaddr2dotted (const struct sockaddr * sa)
Definition at line 533 of file xconnect.c.
 {
     return sockaddr2str(sa, NI_NUMERICHOST | NI_NUMERICSCOPE);
 }
References NI_NUMERICHOST, NI_NUMERICSCOPE, and sockaddr2str().
Referenced by dnsd_main(), dolisten(), download_one_url(), ftpgetput_main(), handle_incoming_and_exit(), make_new_session(), nc_main(), and tcpudpsvd_main().
xmalloc_sockaddr2dotted_noport()
char* FAST_FUNC xmalloc_sockaddr2dotted_noport (const struct sockaddr * sa)
Definition at line 538 of file xconnect.c.
 {
     return sockaddr2str(sa, NI_NUMERICHOST | NI_NUMERICSCOPE | IGNORE_PORT);
 }
References IGNORE_PORT, NI_NUMERICHOST, NI_NUMERICSCOPE, and sockaddr2str().
Referenced by handle_pasv(), INET_rresolve(), ip_port_str(), nfsmount(), print(), print_host(), resolve_peer_hostname(), server_print(), singlemount(), tcpudpsvd_main(), and traceroute_init().
xmalloc_sockaddr2host()
char* FAST_FUNC xmalloc_sockaddr2host (const struct sockaddr * sa)
Definition at line 516 of file xconnect.c.
 {
     return sockaddr2str(sa, 0);
 }
References sockaddr2str().
Referenced by dolisten().
xmalloc_sockaddr2host_noport()
char* FAST_FUNC xmalloc_sockaddr2host_noport (const struct sockaddr * sa)
Definition at line 521 of file xconnect.c.
 {
     return sockaddr2str(sa, IGNORE_PORT);
 }
References IGNORE_PORT, and sockaddr2str().
Referenced by INET_rresolve(), ip_port_str(), print(), and tcpudpsvd_main().
xmalloc_sockaddr2hostonly_noport()
char* FAST_FUNC xmalloc_sockaddr2hostonly_noport (const struct sockaddr * sa)
Definition at line 526 of file xconnect.c.
 {
     return sockaddr2str(sa, NI_NAMEREQD | IGNORE_PORT);
 }
References IGNORE_PORT, NI_NAMEREQD, and sockaddr2str().
Referenced by print_host().
xsocket_stream()
int FAST_FUNC xsocket_stream (len_and_sockaddr ** lsap)
Definition at line 376 of file xconnect.c.
 {
     return xsocket_type(lsap, AF_UNSPEC, SOCK_STREAM);
 }
References AF_UNSPEC, SOCK_STREAM, and xsocket_type().
xsocket_type()
int FAST_FUNC xsocket_type (len_and_sockaddr ** lsap, int family, int sock_type)
Definition at line 341 of file xconnect.c.
 {
     len_and_sockaddr *lsa;
     int fd;
     int len;
     if (family == AF_UNSPEC) {
 #if ENABLE_FEATURE_IPV6
         fd = socket(AF_INET6, sock_type, 0);
         if (fd >= 0) {
             family = AF_INET6;
             goto done;
         }
 #endif
         family = AF_INET;
     }
     fd = xsocket(family, sock_type, 0);
     len = sizeof(struct sockaddr_in);
     if (family == AF_UNIX)
         len = sizeof(struct sockaddr_un);
 #if ENABLE_FEATURE_IPV6
     if (family == AF_INET6) {
  done:
         len = sizeof(struct sockaddr_in6);
     }
 #endif
     lsa = xzalloc(LSA_LEN_SIZE + len);
     lsa->len = len;
     lsa->u.sa.sa_family = family;
     *lsap = lsa;
     return fd;
 }
References AF_INET, AF_INET6, AF_UNIX, AF_UNSPEC, done, fd, len, lsa, LSA_LEN_SIZE, socket(), xsocket(), and xzalloc().
Referenced by create_and_bind_or_die(), nc_main(), send_query_to_peer(), and xsocket_stream().