Fennix: Userspace/musl/src/math/log2f.c File Reference
log2f.c File Reference
#include <math.h>
#include <stdint.h>
#include "libm.h"
#include "log2f_data.h"
Macros
#define N (1 << LOG2F_TABLE_BITS)
#define T __log2f_data.tab
#define A __log2f_data.poly
#define OFF 0x3f330000
Functions
float log2f (float x)
Macro Definition Documentation
A
#define A __log2f_data.poly
Definition at line 23 of file log2f.c.
N
#define N (1 << LOG2F_TABLE_BITS)
Definition at line 21 of file log2f.c.
OFF
#define OFF 0x3f330000
Definition at line 24 of file log2f.c.
T
#define T __log2f_data.tab
Definition at line 22 of file log2f.c.
Function Documentation
log2f()
float log2f (float x)
Definition at line 26 of file log2f.c.
 {
     double_t z, r, r2, p, y, y0, invc, logc;
     uint32_t ix, iz, top, tmp;
     int k, i;
     ix = asuint(x);
     /* Fix sign of zero with downward rounding when x==1.  */
     if (WANT_ROUNDING && predict_false(ix == 0x3f800000))
         return 0;
     if (predict_false(ix - 0x00800000 >= 0x7f800000 - 0x00800000)) {
         /* x < 0x1p-126 or inf or nan.  */
         if (ix * 2 == 0)
             return __math_divzerof(1);
         if (ix == 0x7f800000) /* log2(inf) == inf.  */
             return x;
         if ((ix & 0x80000000) || ix * 2 >= 0xff000000)
             return __math_invalidf(x);
         /* x is subnormal, normalize it.  */
         ix = asuint(x * 0x1p23f);
         ix -= 23 << 23;
     }
     /* x = 2^k z; where z is in range [OFF,2*OFF] and exact.
        The range is split into N subintervals.
        The ith subinterval contains z and c is near its center.  */
     tmp = ix - OFF;
     i = (tmp >> (23 - LOG2F_TABLE_BITS)) % N;
     top = tmp & 0xff800000;
     iz = ix - top;
     k = (int32_t)tmp >> 23; /* arithmetic shift */
     invc = T[i].invc;
     logc = T[i].logc;
     z = (double_t)asfloat(iz);
     /* log2(x) = log1p(z/c-1)/ln2 + log2(c) + k */
     r = z * invc - 1;
     y0 = logc + (double_t)k;
     /* Pipelined polynomial evaluation to approximate log1p(r)/ln2.  */
     r2 = r * r;
     y = A[1] * r + A[2];
     y = A[0] * r2 + y;
     p = A[3] * r + y0;
     y = y * r2 + p;
     return eval_as_float(y);
 }
References __math_divzerof(), __math_invalidf(), A, asfloat, asuint, eval_as_float(), f, i, int, ivln2hi, ivln2lo, k, Lg1, Lg2, Lg3, Lg4, LOG2F_TABLE_BITS, N, OFF, p, predict_false, R, r, r2, T, t1, t2, top, WANT_ROUNDING, x, y, and y0().