Fennix Userspace: Userspace/musl/src/stat/mkfifo.c File Reference
mkfifo.c File Reference
#include <sys/stat.h>
Functions
int mkfifo (const char *path, mode_t mode)
Function Documentation
mkfifo()
int mkfifo (const char * path, mode_t mode)
Definition at line 3 of file mkfifo.c.
 {
     return mknod(path, mode | S_IFIFO, 0);
 }
References mknod(), and S_IFIFO.
Referenced by mkfifo_builtin(), mkfifo_main(), open_control(), and runsv_main().