Fennix Userspace: Userspace/apps/base/bash/lib/readline/history.c File Reference
history.c File Reference
#include <stdio.h>
#include "ansi_stdlib.h"
#include <errno.h>
#include "history.h"
#include "histlib.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define DEFAULT_HISTORY_INITIAL_SIZE 502
#define MAX_HISTORY_INITIAL_SIZE 8192
#define DEFAULT_HISTORY_GROW_SIZE 50
Functions
static char * hist_inittime (void)
HISTORY_STATE * history_get_history_state (void)
void history_set_history_state (HISTORY_STATE *state)
void using_history (void)
int history_total_bytes (void)
int where_history (void)
int history_set_pos (int pos)
int _hs_at_end_of_history (void)
HIST_ENTRY ** history_list (void)
HIST_ENTRY * current_history (void)
HIST_ENTRY * previous_history (void)
HIST_ENTRY * next_history (void)
HIST_ENTRY * history_get (int offset)
HIST_ENTRY * alloc_history_entry (char *string, char *ts)
time_t history_get_time (HIST_ENTRY *hist)
void add_history (const char *string)
void add_history_time (const char *string)
histdata_t free_history_entry (HIST_ENTRY *hist)
HIST_ENTRY * copy_history_entry (HIST_ENTRY *hist)
HIST_ENTRY * replace_history_entry (int which, const char *line, histdata_t data)
void _hs_append_history_line (int which, const char *line)
void _hs_replace_history_data (int which, histdata_t *old, histdata_t *new)
HIST_ENTRY * remove_history (int which)
HIST_ENTRY ** remove_history_range (int first, int last)
void stifle_history (int max)
int unstifle_history (void)
int history_is_stifled (void)
void clear_history (void)
Variables
int errno
static HIST_ENTRY ** the_history = (HIST_ENTRY **)NULL
static int history_stifled
static int history_size
int history_max_entries
int max_input_history
int history_offset
int history_length
int history_base = 1
Macro Definition Documentation
DEFAULT_HISTORY_GROW_SIZE
#define DEFAULT_HISTORY_GROW_SIZE 50
Definition at line 63 of file history.c.
DEFAULT_HISTORY_INITIAL_SIZE
#define DEFAULT_HISTORY_INITIAL_SIZE 502
Definition at line 58 of file history.c.
MAX_HISTORY_INITIAL_SIZE
#define MAX_HISTORY_INITIAL_SIZE 8192
Definition at line 60 of file history.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 25 of file history.c.
Function Documentation
_hs_append_history_line()
void _hs_append_history_line (int which, const char * line)
Definition at line 410 of file history.c.
 {
   HIST_ENTRY *hent;
   size_t newlen, curlen, minlen;
   char *newline;
   hent = the_history[which];
   curlen = strlen (hent->line);
   minlen = curlen + strlen (line) + 2;  /* min space needed */
   if (curlen > 256)     /* XXX - for now */
     {
       newlen = 512;     /* now realloc in powers of 2 */
       /* we recalcluate every time; the operations are cheap */
       while (newlen < minlen)
     newlen <<= 1;
     }
   else
     newlen = minlen;
   /* Assume that realloc returns the same pointer and doesn't try a new
      alloc/copy if the new size is the same as the one last passed. */
   newline = realloc (hent->line, newlen);
   if (newline)
     {
       hent->line = newline;
       hent->line[curlen++] = '\n';
       strcpy (hent->line + curlen, line);
     }
 }
References _hist_entry::line, line, newline(), realloc, strcpy(), strlen(), and the_history.
Referenced by read_history_range().
_hs_at_end_of_history()
int _hs_at_end_of_history (void)
Definition at line 171 of file history.c.
 {
   return (the_history == 0 || history_offset == history_length);
 }
References history_length, history_offset, and the_history.
_hs_replace_history_data()
void _hs_replace_history_data (int which, histdata_t * old, histdata_t * new)
Definition at line 446 of file history.c.
 {
   HIST_ENTRY *entry;
   register int i, last;
   if (which < -2 || which >= history_length || history_length == 0 || the_history == 0)
     return;
   if (which >= 0)
     {
       entry = the_history[which];
       if (entry && entry->data == old)
     entry->data = new;
       return;
     }
   last = -1;
   for (i = 0; i < history_length; i++)
     {
       entry = the_history[i];
       if (entry == 0)
     continue;
       if (entry->data == old)
     {
       last = i;
       if (which == -1)
         entry->data = new;
     }
     }
   if (which == -2 && last >= 0)
     {
       entry = the_history[last];
       entry->data = new;    /* XXX - we don't check entry->old */
     }
 }
References entry::data, history_length, i, and the_history.
Referenced by rl_do_undo(), and rl_free_undo_list().
add_history()
void add_history (const char * string)
Definition at line 279 of file history.c.
 {
   HIST_ENTRY *temp;
   int new_length;
   if (history_stifled && (history_length == history_max_entries))
     {
       register int i;
       /* If the history is stifled, and history_length is zero,
      and it equals history_max_entries, we don't save items. */
       if (history_length == 0)
     return;
       /* If there is something in the slot, then remove it. */
       if (the_history[0])
     (void) free_history_entry (the_history[0]);
       /* Copy the rest of the entries, moving down one slot.  Copy includes
      trailing NULL.  */
       memmove (the_history, the_history + 1, history_length * sizeof (HIST_ENTRY *));
       new_length = history_length;
       history_base++;
     }
   else
     {
       if (history_size == 0)
     {
       if (history_stifled && history_max_entries > 0)
         history_size = (history_max_entries > MAX_HISTORY_INITIAL_SIZE)
                 ? MAX_HISTORY_INITIAL_SIZE
                 : history_max_entries + 2;
       else
         history_size = DEFAULT_HISTORY_INITIAL_SIZE;
       the_history = (HIST_ENTRY **)xmalloc (history_size * sizeof (HIST_ENTRY *));
       new_length = 1;
     }
       else
     {
       if (history_length == (history_size - 1))
         {
           history_size += DEFAULT_HISTORY_GROW_SIZE;
           the_history = (HIST_ENTRY **)
         xrealloc (the_history, history_size * sizeof (HIST_ENTRY *));
         }
       new_length = history_length + 1;
     }
     }
   temp = alloc_history_entry ((char *)string, hist_inittime ());
   the_history[new_length] = (HIST_ENTRY *)NULL;
   the_history[new_length - 1] = temp;
   history_length = new_length;
 }
References alloc_history_entry(), DEFAULT_HISTORY_GROW_SIZE, DEFAULT_HISTORY_INITIAL_SIZE, free_history_entry(), hist_inittime(), history_base, history_length, history_max_entries, history_size, history_stifled, i, MAX_HISTORY_INITIAL_SIZE, memmove(), NULL, the_history, xmalloc, and xrealloc.
Referenced by cb_linehandler(), history_expand(), main(), read_history_range(), and rl_gets().
add_history_time()
void add_history_time (const char * string)
Definition at line 338 of file history.c.
 {
   HIST_ENTRY *hs;
   if (string == 0 || history_length < 1)
     return;
   hs = the_history[history_length - 1];
   FREE (hs->timestamp);
   hs->timestamp = savestring (string);
 }
References FREE, history_length, savestring(), the_history, and _hist_entry::timestamp.
Referenced by read_history_range().
alloc_history_entry()
HIST_ENTRY* alloc_history_entry (char * string, char * ts)
Definition at line 227 of file history.c.
 {
   HIST_ENTRY *temp;
   temp = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
   temp->line = string ? savestring (string) : string;
   temp->data = (char *)NULL;
   temp->timestamp = ts;
   return temp;
 }
References _hist_entry::data, _hist_entry::line, NULL, savestring(), string, _hist_entry::timestamp, and xmalloc.
Referenced by add_history(), and copy_history_entry().
clear_history()
void clear_history (void)
Definition at line 601 of file history.c.
 {
   register int i;
   /* This loses because we cannot free the data. */
   for (i = 0; i < history_length; i++)
     {
       free_history_entry (the_history[i]);
       the_history[i] = (HIST_ENTRY *)NULL;
     }
   history_offset = history_length = 0;
   history_base = 1;     /* reset history base to default */
 }
References free_history_entry(), history_base, history_length, history_offset, i, NULL, and the_history.
copy_history_entry()
HIST_ENTRY* copy_history_entry (HIST_ENTRY * hist)
Definition at line 366 of file history.c.
 {
   HIST_ENTRY *ret;
   char *ts;
   if (hist == 0)
     return hist;
   ret = alloc_history_entry (hist->line, (char *)NULL);
   ts = hist->timestamp ? savestring (hist->timestamp) : hist->timestamp;
   ret->timestamp = ts;
   ret->data = hist->data;
   return ret;
 }
References alloc_history_entry(), _hist_entry::data, _hist_entry::line, NULL, ret, savestring(), and _hist_entry::timestamp.
current_history()
HIST_ENTRY* current_history (void)
Definition at line 188 of file history.c.
 {
   return ((history_offset == history_length) || the_history == 0)
         ? (HIST_ENTRY *)NULL
         : the_history[history_offset];
 }
References history_length, history_offset, NULL, and the_history.
Referenced by _rl_revert_previous_lines(), get_history_event(), noninc_dosearch(), readline_internal_teardown(), rl_do_undo(), rl_free_line_state(), rl_history_search_internal(), rl_maybe_replace_line(), and rl_redisplay().
free_history_entry()
histdata_t free_history_entry (HIST_ENTRY * hist)
Definition at line 352 of file history.c.
 {
   histdata_t x;
   if (hist == 0)
     return ((histdata_t) 0);
   FREE (hist->line);
   FREE (hist->timestamp);
   x = hist->data;
   xfree (hist);
   return (x);
 }
References _hist_entry::data, FREE, _hist_entry::line, _hist_entry::timestamp, x, and xfree.
Referenced by add_history(), clear_history(), and stifle_history().
hist_inittime()
static char * hist_inittime (void) static
Definition at line 259 of file history.c.
 {
   time_t t;
   char ts[64], *ret;
   t = (time_t) time ((time_t *)0);
 #if defined (HAVE_VSNPRINTF)        /* assume snprintf if vsnprintf exists */
   snprintf (ts, sizeof (ts) - 1, "X%lu", (unsigned long) t);
 #else
   sprintf (ts, "X%lu", (unsigned long) t);
 #endif
   ret = savestring (ts);
   ret[0] = history_comment_char;
   return ret;
 }
References history_comment_char, ret, savestring(), snprintf(), sprintf(), t, and time().
Referenced by add_history().
history_get()
HIST_ENTRY* history_get (int offset)
Definition at line 216 of file history.c.
 {
   int local_index;
   local_index = offset - history_base;
   return (local_index >= history_length || local_index < 0 || the_history == 0)
         ? (HIST_ENTRY *)NULL
         : the_history[local_index];
 }
References history_base, history_length, local_index, NULL, offset, and the_history.
history_get_history_state()
HISTORY_STATE* history_get_history_state (void)
Definition at line 100 of file history.c.
 {
   HISTORY_STATE *state;
   state = (HISTORY_STATE *)xmalloc (sizeof (HISTORY_STATE));
   state->entries = the_history;
   state->offset = history_offset;
   state->length = history_length;
   state->size = history_size;
   state->flags = 0;
   if (history_stifled)
     state->flags |= HS_STIFLED;
   return (state);
 }
References history_length, history_offset, history_size, history_stifled, HS_STIFLED, state, the_history, and xmalloc.
history_get_time()
time_t history_get_time (HIST_ENTRY * hist)
Definition at line 241 of file history.c.
 {
   char *ts;
   time_t t;
   if (hist == 0 || hist->timestamp == 0)
     return 0;
   ts = hist->timestamp;
   if (ts[0] != history_comment_char)
     return 0;
   errno = 0;
   t = (time_t) strtol (ts + 1, (char **)NULL, 10);      /* XXX - should use strtol() here */
   if (errno == ERANGE)
     return (time_t)0;
   return t;
 }
References ERANGE, errno, history_comment_char, NULL, strtol(), t, and _hist_entry::timestamp.
Referenced by main().
history_is_stifled()
int history_is_stifled (void)
Definition at line 595 of file history.c.
 {
   return (history_stifled);
 }
References history_stifled.
Referenced by _rl_get_string_variable_value().
history_list()
HIST_ENTRY** history_list (void)
Definition at line 180 of file history.c.
 {
   return (the_history);
 }
References the_history.
Referenced by _rl_isearch_init(), history_do_write(), history_search_internal(), main(), rl_clear_history(), and rl_get_previous_history().
history_set_history_state()
void history_set_history_state (HISTORY_STATE * state)
Definition at line 118 of file history.c.
 {
   the_history = state->entries;
   history_offset = state->offset;
   history_length = state->length;
   history_size = state->size;
   if (state->flags & HS_STIFLED)
     history_stifled = 1;
 }
References history_length, history_offset, history_size, history_stifled, HS_STIFLED, state, and the_history.
history_set_pos()
int history_set_pos (int pos)
Definition at line 161 of file history.c.
 {
   if (pos > history_length || pos < 0 || !the_history)
     return (0);
   history_offset = pos;
   return (1);
 }
References history_length, history_offset, pos, and the_history.
Referenced by _rl_revert_all_lines(), _rl_revert_previous_lines(), history_search_pos(), noninc_dosearch(), noninc_search_from_pos(), rl_history_search_internal(), and rl_yank_nth_arg_internal().
history_total_bytes()
int history_total_bytes (void)
Definition at line 140 of file history.c.
 {
   register int i, result;
   for (i = result = 0; the_history && the_history[i]; i++)
     result += HISTENT_BYTES (the_history[i]);
   return (result);
 }
References HISTENT_BYTES, i, and the_history.
next_history()
HIST_ENTRY* next_history (void)
Definition at line 208 of file history.c.
 {
   return (history_offset == history_length) ? (HIST_ENTRY *)NULL : the_history[++history_offset];
 }
References history_length, history_offset, NULL, and the_history.
Referenced by rl_get_next_history().
previous_history()
HIST_ENTRY* previous_history (void)
Definition at line 199 of file history.c.
 {
   return history_offset ? the_history[--history_offset] : (HIST_ENTRY *)NULL;
 }
References history_offset, NULL, and the_history.
Referenced by _rl_revert_previous_lines(), rl_get_previous_history(), and rl_yank_nth_arg_internal().
remove_history()
HIST_ENTRY* remove_history (int which)
Definition at line 486 of file history.c.
 {
   HIST_ENTRY *return_value;
   register int i;
 #if 1
   int nentries;
   HIST_ENTRY **start, **end;
 #endif
   if (which < 0 || which >= history_length || history_length ==  0 || the_history == 0)
     return ((HIST_ENTRY *)NULL);
   return_value = the_history[which];
 #if 1
   /* Copy the rest of the entries, moving down one slot.  Copy includes
      trailing NULL.  */
   nentries = history_length - which;
   start = the_history + which;
   end = start + 1;
   memmove (start, end, nentries * sizeof (HIST_ENTRY *));
 #else
   for (i = which; i < history_length; i++)
     the_history[i] = the_history[i + 1];
 #endif
   history_length--;
   return (return_value);
 }
References history_length, i, memmove(), NULL, start(), and the_history.
Referenced by main().
remove_history_range()
HIST_ENTRY** remove_history_range (int first, int last)
Definition at line 518 of file history.c.
 {
   HIST_ENTRY **return_value;
   register int i;
   int nentries;
   HIST_ENTRY **start, **end;
   if (the_history == 0 || history_length == 0)
     return ((HIST_ENTRY **)NULL);
   if (first < 0 || first >= history_length || last < 0 || last >= history_length)
     return ((HIST_ENTRY **)NULL);
   if (first > last)
     return (HIST_ENTRY **)NULL;
   nentries = last - first + 1;
   return_value = (HIST_ENTRY **)malloc ((nentries + 1) * sizeof (HIST_ENTRY *));
   if (return_value == 0)
     return return_value;
   /* Return all the deleted entries in a list */
   for (i = first ; i <= last; i++)
     return_value[i - first] = the_history[i];
   return_value[i - first] = (HIST_ENTRY *)NULL;
   /* Copy the rest of the entries, moving down NENTRIES slots.  Copy includes
      trailing NULL.  */
   start = the_history + first;
   end = the_history + last + 1;
   memmove (start, end, (history_length - last) * sizeof (HIST_ENTRY *));
   history_length -= nentries;
   return (return_value);
 }
References first, history_length, i, malloc, memmove(), NULL, start(), and the_history.
replace_history_entry()
HIST_ENTRY* replace_history_entry (int which, const char * line, histdata_t data)
Definition at line 388 of file history.c.
 {
   HIST_ENTRY *temp, *old_value;
   if (which < 0 || which >= history_length)
     return ((HIST_ENTRY *)NULL);
   temp = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
   old_value = the_history[which];
   temp->line = savestring (line);
   temp->data = data;
   temp->timestamp = old_value->timestamp ? savestring (old_value->timestamp) : 0;
   the_history[which] = temp;
   return (old_value);
 }
References _hist_entry::data, history_length, _hist_entry::line, line, NULL, savestring(), the_history, _hist_entry::timestamp, and xmalloc.
Referenced by readline_internal_teardown(), rl_do_undo(), and rl_maybe_replace_line().
stifle_history()
void stifle_history (int max)
Definition at line 555 of file history.c.
 {
   register int i, j;
   if (max < 0)
     max = 0;
   if (history_length > max)
     {
       /* This loses because we cannot free the data. */
       for (i = 0, j = history_length - max; i < j; i++)
     free_history_entry (the_history[i]);
       history_base = i;
       for (j = 0, i = history_length - max; j < max; i++, j++)
     the_history[j] = the_history[i];
       the_history[j] = (HIST_ENTRY *)NULL;
       history_length = j;
     }
   history_stifled = 1;
   max_input_history = history_max_entries = max;
 }
References free_history_entry(), history_base, history_length, history_max_entries, history_stifled, i, j, max, max_input_history, NULL, and the_history.
Referenced by sv_histsize().
unstifle_history()
int unstifle_history (void)
Definition at line 583 of file history.c.
 {
   if (history_stifled)
     {
       history_stifled = 0;
       return (history_max_entries);
     }
   else
     return (-history_max_entries);
 }
References history_max_entries, and history_stifled.
Referenced by sv_histsize().
using_history()
void using_history (void)
Definition at line 131 of file history.c.
 {
   history_offset = history_length;
 }
References history_length, and history_offset.
Referenced by _rl_revert_all_lines(), _rl_start_using_history(), main(), and rl_end_of_history().
where_history()
int where_history (void)
Definition at line 153 of file history.c.
 {
   return (history_offset);
 }
References history_offset.
Referenced by _rl_revert_all_lines(), _rl_revert_previous_lines(), _rl_scxt_alloc(), history_search_pos(), noninc_dosearch(), noninc_search_from_pos(), readline_internal_teardown(), rl_beginning_of_history(), rl_do_undo(), rl_fetch_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_maybe_replace_line(), rl_operate_and_get_next(), rl_yank_nth_arg_internal(), and set_saved_history().
Variable Documentation
errno
int errno extern
Referenced by history_get_time().
history_base
int history_base = 1
Definition at line 96 of file history.c.
Referenced by add_history(), clear_history(), get_history_event(), history_get(), main(), rl_display_search(), rl_fetch_history(), rl_operate_and_get_next(), set_saved_history(), and stifle_history().
history_length
int history_length
Definition at line 93 of file history.c.
Referenced by _hs_at_end_of_history(), _hs_replace_history_data(), _rl_revert_previous_lines(), add_history(), add_history_time(), clear_history(), current_history(), get_history_event(), history_do_write(), history_get(), history_get_history_state(), history_search_internal(), history_set_history_state(), history_set_pos(), next_history(), read_history_range(), remove_history(), remove_history_range(), replace_history_entry(), rl_clear_history(), stifle_history(), using_history(), and write_history().
history_max_entries
int history_max_entries
Definition at line 85 of file history.c.
Referenced by _rl_get_string_variable_value(), add_history(), stifle_history(), and unstifle_history().
history_offset
int history_offset
Definition at line 90 of file history.c.
Referenced by _hs_at_end_of_history(), clear_history(), current_history(), get_history_event(), history_get_history_state(), history_search_internal(), history_set_history_state(), history_set_pos(), next_history(), previous_history(), rl_clear_history(), using_history(), and where_history().
history_size
int history_size static
Definition at line 81 of file history.c.
Referenced by add_history(), history_get_history_state(), and history_set_history_state().
history_stifled
int history_stifled static
Definition at line 78 of file history.c.
Referenced by add_history(), history_get_history_state(), history_is_stifled(), history_set_history_state(), stifle_history(), and unstifle_history().
max_input_history
int max_input_history
Definition at line 86 of file history.c.
Referenced by stifle_history().
the_history
HIST_ENTRY** the_history = (HIST_ENTRY **)NULL static
Definition at line 74 of file history.c.
Referenced by _hs_append_history_line(), _hs_at_end_of_history(), _hs_replace_history_data(), add_history(), add_history_time(), clear_history(), current_history(), history_do_write(), history_get(), history_get_history_state(), history_list(), history_search_internal(), history_set_history_state(), history_set_pos(), history_total_bytes(), next_history(), previous_history(), remove_history(), remove_history_range(), replace_history_entry(), and stifle_history().