Fennix: Userspace/apps/base/busybox/libbb/rtc.c File Reference
rtc.c File Reference
#include "libbb.h"
#include "rtc_.h"
Functions
int FAST_FUNC rtc_adjtime_is_utc (void)
static int open_loop_on_busy (const char *name, int flags)
int FAST_FUNC rtc_xopen (const char **default_rtc, int flags)
void FAST_FUNC rtc_read_tm (struct tm *ptm, int fd)
time_t FAST_FUNC rtc_tm2time (struct tm *ptm, int utc)
Function Documentation
open_loop_on_busy()
static int open_loop_on_busy (const char * name, int flags) static
Definition at line 35 of file rtc.c.
 {
     int rtc;
     /*
      * Tested with two parallel "hwclock -w" loops.
      * With try = 10, no failures with 2x1000000 loop iterations.
      */
     int try = 1000 / 20;
  again:
     errno = 0;
     rtc = open(name, flags);
     if (errno == EBUSY) {
         usleep(20 * 1000);
         if (--try != 0)
             goto again;
         /* EBUSY. Last try, exit on error instead of returning -1 */
         return xopen(name, flags);
     }
     return rtc;
 }
References EBUSY, errno, flags, open(), usleep(), and xopen().
Referenced by rtc_xopen().
rtc_adjtime_is_utc()
int FAST_FUNC rtc_adjtime_is_utc (void)
Definition at line 10 of file rtc.c.
 {
     int utc = 0;
     FILE *f = fopen_for_read(ADJTIME_PATH);
     if (f) {
         char buffer[128];
         while (fgets(buffer, sizeof(buffer), f)) {
             if (is_prefixed_with(buffer, "UTC")) {
                 utc = 1;
                 break;
             }
         }
         fclose(f);
     }
     return utc;
 }
References ADJTIME_PATH, f, fclose(), fgets, fopen_for_read(), and is_prefixed_with().
Referenced by hwclock_main(), and rtcwake_main().
rtc_read_tm()
void FAST_FUNC rtc_read_tm (struct tm * ptm, int fd)
Definition at line 81 of file rtc.c.
 {
     memset(ptm, 0, sizeof(*ptm));
     xioctl(fd, RTC_RD_TIME, ptm);
     ptm->tm_isdst = -1; /* "not known" */
 }
References fd, memset, RTC_RD_TIME, tm::tm_isdst, and xioctl.
Referenced by read_rtc(), and rtcwake_main().
rtc_tm2time()
time_t FAST_FUNC rtc_tm2time (struct tm * ptm, int utc)
Definition at line 88 of file rtc.c.
 {
     char *oldtz = oldtz; /* for compiler */
     time_t t;
     if (utc) {
         oldtz = getenv("TZ");
         putenv((char*)"TZ=UTC0");
         tzset();
     }
     t = mktime(ptm);
     if (utc) {
         unsetenv("TZ");
         if (oldtz)
             putenv(oldtz - 3);
         tzset();
     }
     return t;
 }
References getenv, mktime(), putenv(), t, tzset(), and unsetenv().
Referenced by read_rtc(), and rtcwake_main().
rtc_xopen()
int FAST_FUNC rtc_xopen (const char ** default_rtc, int flags)
Definition at line 57 of file rtc.c.
 {
     int rtc;
     const char *name =
         "/dev/rtc""\0"
         "/dev/rtc0""\0"
         "/dev/misc/rtc""\0";
     if (!*default_rtc)
         goto try_name;
     name = ""; /*else: we have rtc name, don't try other names */
     for (;;) {
         rtc = open_loop_on_busy(*default_rtc, flags);
         if (rtc >= 0)
             return rtc;
         if (!name[0])
             return xopen(*default_rtc, flags);
  try_name:
         *default_rtc = name;
         name += strlen(name) + 1;
     }
 }
References flags, open_loop_on_busy(), strlen, and xopen().
Referenced by from_sys_clock(), read_rtc(), and rtcwake_main().