Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/i_scale.c File Reference
i_scale.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doomtype.h"
#include "i_video.h"
#include "m_argv.h"
#include "z_zone.h"
Macros
#define DRAW_PIXEL2 *dest++ = *dest2++ = c;
#define DRAW_PIXEL3 *dest++ = *dest2++ = *dest3++ = c
#define DRAW_PIXEL4 *dest++ = *dest2++ = *dest3++ = *dest4++ = c;
#define DRAW_PIXEL5 *dest++ = *dest2++ = *dest3++ = *dest4++ = *dest5++ = c
Functions
void I_InitScale (byte *_src_buffer, byte *_dest_buffer, int _dest_pitch)
static boolean I_Scale1x (int x1, int y1, int x2, int y2)
static boolean I_Scale2x (int x1, int y1, int x2, int y2)
static boolean I_Scale3x (int x1, int y1, int x2, int y2)
static boolean I_Scale4x (int x1, int y1, int x2, int y2)
static boolean I_Scale5x (int x1, int y1, int x2, int y2)
static int FindNearestColor (byte *palette, int r, int g, int b)
static byte * GenerateStretchTable (byte *palette, int pct)
static void I_InitStretchTables (byte *palette)
static void I_InitSquashTable (byte *palette)
void I_ResetScaleTables (byte *palette)
static void WriteBlendedLine1x (byte *dest, byte *src1, byte *src2, byte *stretch_table)
static boolean I_Stretch1x (int x1, int y1, int x2, int y2)
static void WriteLine2x (byte *dest, byte *src)
static void WriteBlendedLine2x (byte *dest, byte *src1, byte *src2, byte *stretch_table)
static boolean I_Stretch2x (int x1, int y1, int x2, int y2)
static void WriteLine3x (byte *dest, byte *src)
static void WriteBlendedLine3x (byte *dest, byte *src1, byte *src2, byte *stretch_table)
static boolean I_Stretch3x (int x1, int y1, int x2, int y2)
static void WriteLine4x (byte *dest, byte *src)
static void WriteBlendedLine4x (byte *dest, byte *src1, byte *src2, byte *stretch_table)
static boolean I_Stretch4x (int x1, int y1, int x2, int y2)
static void WriteLine5x (byte *dest, byte *src)
static boolean I_Stretch5x (int x1, int y1, int x2, int y2)
static void WriteSquashedLine1x (byte *dest, byte *src)
static boolean I_Squash1x (int x1, int y1, int x2, int y2)
static void WriteSquashedLine2x (byte *dest, byte *src)
static boolean I_Squash2x (int x1, int y1, int x2, int y2)
static void WriteSquashedLine3x (byte *dest, byte *src)
static boolean I_Squash3x (int x1, int y1, int x2, int y2)
static void WriteSquashedLine4x (byte *dest, byte *src)
static boolean I_Squash4x (int x1, int y1, int x2, int y2)
static void WriteSquashedLine5x (byte *dest, byte *src)
static boolean I_Squash5x (int x1, int y1, int x2, int y2)
Variables
static byte * src_buffer
static byte * dest_buffer
static int dest_pitch
static byte * stretch_tables [2] = { NULL, NULL }
static byte * half_stretch_table = NULL
screen_mode_t mode_scale_1x
screen_mode_t mode_scale_2x
screen_mode_t mode_scale_3x
screen_mode_t mode_scale_4x
screen_mode_t mode_scale_5x
screen_mode_t mode_stretch_1x
screen_mode_t mode_stretch_2x
screen_mode_t mode_stretch_3x
screen_mode_t mode_stretch_4x
screen_mode_t mode_stretch_5x
screen_mode_t mode_squash_1x
screen_mode_t mode_squash_2x
screen_mode_t mode_squash_3x
screen_mode_t mode_squash_4x
screen_mode_t mode_squash_5x
Macro Definition Documentation
DRAW_PIXEL2
#define DRAW_PIXEL2 *dest++ = *dest2++ = c;
Definition at line 1099 of file i_scale.c.
DRAW_PIXEL3
#define DRAW_PIXEL3 *dest++ = *dest2++ = *dest3++ = c
Definition at line 1194 of file i_scale.c.
DRAW_PIXEL4
#define DRAW_PIXEL4 *dest++ = *dest2++ = *dest3++ = *dest4++ = c;
Definition at line 1276 of file i_scale.c.
DRAW_PIXEL5
#define DRAW_PIXEL5 *dest++ = *dest2++ = *dest3++ = *dest4++ = *dest5++ = c
Definition at line 1387 of file i_scale.c.
Function Documentation
FindNearestColor()
static int FindNearestColor (byte * palette, int r, int g, int b) static
Definition at line 295 of file i_scale.c.
 {
     byte *col;
     int best;
     int best_diff;
     int diff;
     int i;
     best = 0;
     best_diff = __INT_MAX__;
     for (i=0; i<256; ++i)
     {
         col = palette + i * 3;
         diff = (r - col[0]) * (r - col[0])
              + (g - col[1]) * (g - col[1])
              + (b - col[2]) * (b - col[2]);
         if (diff == 0)
         {
             return i;
         }
         else if (diff < best_diff)
         {
             best = i;
             best_diff = diff;
         }
     }
     return best;
 }
References diff(), g, and i.
Referenced by GenerateStretchTable().
GenerateStretchTable()
static byte* GenerateStretchTable (byte * palette, int pct) static
Definition at line 332 of file i_scale.c.
 {
     byte *result;
     int x, y;
     int r, g, b;
     byte *col1;
     byte *col2;
     result = Z_Malloc(256 * 256, PU_STATIC, NULL);
     for (x=0; x<256; ++x)
     {
         for (y=0; y<256; ++y)
         {
             col1 = palette + x * 3;
             col2 = palette + y * 3;
             r = (((int) col1[0]) * pct + ((int) col2[0]) * (100 - pct)) / 100;
             g = (((int) col1[1]) * pct + ((int) col2[1]) * (100 - pct)) / 100;
             b = (((int) col1[2]) * pct + ((int) col2[2]) * (100 - pct)) / 100;
             result[x * 256 + y] = FindNearestColor(palette, r, g, b);
         }
     }
     return result;
 }
References FindNearestColor(), g, NULL, PU_STATIC, x, y, and Z_Malloc().
Referenced by I_InitSquashTable(), I_InitStretchTables(), and I_ResetScaleTables().
I_InitScale()
void I_InitScale (byte * _src_buffer, byte * _dest_buffer, int _dest_pitch)
Definition at line 61 of file i_scale.c.
 {
     src_buffer = _src_buffer;
     dest_buffer = _dest_buffer;
     dest_pitch = _dest_pitch;
 }
References dest_buffer, dest_pitch, and src_buffer.
I_InitSquashTable()
static void I_InitSquashTable (byte * palette) static
Definition at line 387 of file i_scale.c.
 {
     if (half_stretch_table != NULL)
     {
         return;
     }
     printf("I_InitSquashTable: Generating lookup table..");
     fflush(stdout);
     half_stretch_table = GenerateStretchTable(palette, 50);
     puts("");
 }
References fflush(), GenerateStretchTable(), half_stretch_table, NULL, printf(), puts(), and stdout.
I_InitStretchTables()
static void I_InitStretchTables (byte * palette) static
Definition at line 361 of file i_scale.c.
 {
     if (stretch_tables[0] != NULL)
     {
         return;
     }
     // We only actually need two lookup tables:
     //
     // mix 0%   =  just write line 1
     // mix 20%  =  stretch_tables[0]
     // mix 40%  =  stretch_tables[1]
     // mix 60%  =  stretch_tables[1] used backwards
     // mix 80%  =  stretch_tables[0] used backwards
     // mix 100% =  just write line 2
     printf("I_InitStretchTables: Generating lookup tables..");
     fflush(stdout);
     stretch_tables[0] = GenerateStretchTable(palette, 20);
     printf(".."); fflush(stdout);
     stretch_tables[1] = GenerateStretchTable(palette, 40);
     puts("");
 }
References fflush(), GenerateStretchTable(), NULL, printf(), puts(), stdout, and stretch_tables.
I_ResetScaleTables()
void I_ResetScaleTables (byte * palette)
Definition at line 404 of file i_scale.c.
 {
     if (stretch_tables[0] != NULL)
     {
         Z_Free(stretch_tables[0]);
         Z_Free(stretch_tables[1]);
         printf("I_ResetScaleTables: Regenerating lookup tables..\n");
         stretch_tables[0] = GenerateStretchTable(palette, 20);
         stretch_tables[1] = GenerateStretchTable(palette, 40);
     }
     if (half_stretch_table != NULL)
     {
         Z_Free(half_stretch_table);
         printf("I_ResetScaleTables: Regenerating lookup table..\n");
         half_stretch_table = GenerateStretchTable(palette, 50);
     }
 }
References GenerateStretchTable(), half_stretch_table, NULL, printf(), stretch_tables, and Z_Free().
I_Scale1x()
static boolean I_Scale1x (int x1, int y1, int x2, int y2) static
Definition at line 75 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     int w = x2 - x1;
     // Need to byte-copy from buffer into the screen buffer
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + y1 * dest_pitch + x1;
     for (y=y1; y<y2; ++y)
     {
         memcpy(screenp, bufp, w);
         screenp += dest_pitch;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, memcpy(), SCREENWIDTH, src_buffer, w, y, and y1().
I_Scale2x()
static boolean I_Scale2x (int x1, int y1, int x2, int y2) static
Definition at line 105 of file i_scale.c.
 {
     byte *bufp, *screenp, *screenp2;
     int x, y;
     int multi_pitch;
     multi_pitch = dest_pitch * 2;
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + (y1 * dest_pitch + x1) * 2;
     screenp2 = screenp + dest_pitch;
     for (y=y1; y<y2; ++y)
     {
         byte *sp, *sp2, *bp;
         sp = screenp;
         sp2 = screenp2;
         bp = bufp;
         for (x=x1; x<x2; ++x)
         {
             *sp++ = *bp;  *sp++ = *bp;
             *sp2++ = *bp; *sp2++ = *bp;
             ++bp;
         }
         screenp += multi_pitch;
         screenp2 += multi_pitch;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References bp, dest_buffer, dest_pitch, SCREENWIDTH, sp, src_buffer, x, y, and y1().
I_Scale3x()
static boolean I_Scale3x (int x1, int y1, int x2, int y2) static
Definition at line 146 of file i_scale.c.
 {
     byte *bufp, *screenp, *screenp2, *screenp3;
     int x, y;
     int multi_pitch;
     multi_pitch = dest_pitch * 3;
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + (y1 * dest_pitch + x1) * 3;
     screenp2 = screenp + dest_pitch;
     screenp3 = screenp + dest_pitch * 2;
     for (y=y1; y<y2; ++y)
     {
         byte *sp, *sp2, *sp3, *bp;
         sp = screenp;
         sp2 = screenp2;
         sp3 = screenp3;
         bp = bufp;
         for (x=x1; x<x2; ++x)
         {
             *sp++ = *bp;  *sp++ = *bp;  *sp++ = *bp;
             *sp2++ = *bp; *sp2++ = *bp; *sp2++ = *bp;
             *sp3++ = *bp; *sp3++ = *bp; *sp3++ = *bp;
             ++bp;
         }
         screenp += multi_pitch;
         screenp2 += multi_pitch;
         screenp3 += multi_pitch;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References bp, dest_buffer, dest_pitch, SCREENWIDTH, sp, src_buffer, x, y, and y1().
I_Scale4x()
static boolean I_Scale4x (int x1, int y1, int x2, int y2) static
Definition at line 191 of file i_scale.c.
 {
     byte *bufp, *screenp, *screenp2, *screenp3, *screenp4;
     int x, y;
     int multi_pitch;
     multi_pitch = dest_pitch * 4;
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + (y1 * dest_pitch + x1) * 4;
     screenp2 = screenp + dest_pitch;
     screenp3 = screenp + dest_pitch * 2;
     screenp4 = screenp + dest_pitch * 3;
     for (y=y1; y<y2; ++y)
     {
         byte *sp, *sp2, *sp3, *sp4, *bp;
         sp = screenp;
         sp2 = screenp2;
         sp3 = screenp3;
         sp4 = screenp4;
         bp = bufp;
         for (x=x1; x<x2; ++x)
         {
             *sp++ = *bp;  *sp++ = *bp;  *sp++ = *bp;  *sp++ = *bp;
             *sp2++ = *bp; *sp2++ = *bp; *sp2++ = *bp; *sp2++ = *bp;
             *sp3++ = *bp; *sp3++ = *bp; *sp3++ = *bp; *sp3++ = *bp;
             *sp4++ = *bp; *sp4++ = *bp; *sp4++ = *bp; *sp4++ = *bp;
             ++bp;
         }
         screenp += multi_pitch;
         screenp2 += multi_pitch;
         screenp3 += multi_pitch;
         screenp4 += multi_pitch;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References bp, dest_buffer, dest_pitch, SCREENWIDTH, sp, src_buffer, x, y, and y1().
I_Scale5x()
static boolean I_Scale5x (int x1, int y1, int x2, int y2) static
Definition at line 240 of file i_scale.c.
 {
     byte *bufp, *screenp, *screenp2, *screenp3, *screenp4, *screenp5;
     int x, y;
     int multi_pitch;
     multi_pitch = dest_pitch * 5;
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + (y1 * dest_pitch + x1) * 5;
     screenp2 = screenp + dest_pitch;
     screenp3 = screenp + dest_pitch * 2;
     screenp4 = screenp + dest_pitch * 3;
     screenp5 = screenp + dest_pitch * 4;
     for (y=y1; y<y2; ++y)
     {
         byte *sp, *sp2, *sp3, *sp4, *sp5, *bp;
         sp = screenp;
         sp2 = screenp2;
         sp3 = screenp3;
         sp4 = screenp4;
         sp5 = screenp5;
         bp = bufp;
         for (x=x1; x<x2; ++x)
         {
             *sp++ = *bp;  *sp++ = *bp;  *sp++ = *bp;  *sp++ = *bp;  *sp++ = *bp;
             *sp2++ = *bp; *sp2++ = *bp; *sp2++ = *bp; *sp2++ = *bp; *sp2++ = *bp;
             *sp3++ = *bp; *sp3++ = *bp; *sp3++ = *bp; *sp3++ = *bp; *sp3++ = *bp;
             *sp4++ = *bp; *sp4++ = *bp; *sp4++ = *bp; *sp4++ = *bp; *sp4++ = *bp;
             *sp5++ = *bp; *sp5++ = *bp; *sp5++ = *bp; *sp5++ = *bp; *sp5++ = *bp;
             ++bp;
         }
         screenp += multi_pitch;
         screenp2 += multi_pitch;
         screenp3 += multi_pitch;
         screenp4 += multi_pitch;
         screenp5 += multi_pitch;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References bp, dest_buffer, dest_pitch, SCREENWIDTH, sp, src_buffer, x, y, and y1().
I_Squash1x()
static boolean I_Squash1x (int x1, int y1, int x2, int y2) static
Definition at line 1061 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     bufp = src_buffer;
     screenp = (byte *) dest_buffer;
     for (y=0; y<SCREENHEIGHT; ++y)
     {
         WriteSquashedLine1x(screenp, bufp);
         screenp += dest_pitch;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, WriteSquashedLine1x(), y, and y1().
I_Squash2x()
static boolean I_Squash2x (int x1, int y1, int x2, int y2) static
Definition at line 1160 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     bufp = src_buffer;
     screenp = (byte *) dest_buffer;
     for (y=0; y<SCREENHEIGHT; ++y)
     {
         WriteSquashedLine2x(screenp, bufp);
         screenp += dest_pitch * 2;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, WriteSquashedLine2x(), y, and y1().
I_Squash3x()
static boolean I_Squash3x (int x1, int y1, int x2, int y2) static
Definition at line 1243 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     bufp = src_buffer;
     screenp = (byte *) dest_buffer;
     for (y=0; y<SCREENHEIGHT; ++y)
     {
         WriteSquashedLine3x(screenp, bufp);
         screenp += dest_pitch * 3;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, WriteSquashedLine3x(), y, and y1().
I_Squash4x()
static boolean I_Squash4x (int x1, int y1, int x2, int y2) static
Definition at line 1354 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     bufp = src_buffer;
     screenp = (byte *) dest_buffer;
     for (y=0; y<SCREENHEIGHT; ++y)
     {
         WriteSquashedLine4x(screenp, bufp);
         screenp += dest_pitch * 4;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, WriteSquashedLine4x(), y, and y1().
I_Squash5x()
static boolean I_Squash5x (int x1, int y1, int x2, int y2) static
Definition at line 1419 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     bufp = src_buffer;
     screenp = (byte *) dest_buffer;
     for (y=0; y<SCREENHEIGHT; ++y)
     {
         WriteSquashedLine5x(screenp, bufp);
         screenp += dest_pitch * 5;
         bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, WriteSquashedLine5x(), y, and y1().
I_Stretch1x()
static boolean I_Stretch1x (int x1, int y1, int x2, int y2) static
Definition at line 450 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     // Need to byte-copy from buffer into the screen buffer
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + y1 * dest_pitch + x1;
     // For every 5 lines of src_buffer, 6 lines are written to dest_buffer
     // (200 -> 240)
     for (y=0; y<SCREENHEIGHT; y += 5)
     {
         // 100% line 0
         memcpy(screenp, bufp, SCREENWIDTH);
         screenp += dest_pitch;
         // 20% line 0, 80% line 1
         WriteBlendedLine1x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 40% line 1, 60% line 2
         WriteBlendedLine1x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 60% line 2, 40% line 3
         WriteBlendedLine1x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 80% line 3, 20% line 4
         WriteBlendedLine1x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 4
         memcpy(screenp, bufp, SCREENWIDTH);
         screenp += dest_pitch; bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, memcpy(), SCREENHEIGHT, SCREENWIDTH, src_buffer, stretch_tables, WriteBlendedLine1x(), y, and y1().
I_Stretch2x()
static boolean I_Stretch2x (int x1, int y1, int x2, int y2) static
Definition at line 539 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     // Need to byte-copy from buffer into the screen buffer
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + y1 * dest_pitch + x1;
     // For every 5 lines of src_buffer, 12 lines are written to dest_buffer.
     // (200 -> 480)
     for (y=0; y<SCREENHEIGHT; y += 5)
     {
         // 100% line 0
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 40% line 0, 60% line 1
         WriteBlendedLine2x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 1
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 80% line 1, 20% line 2
         WriteBlendedLine2x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 2
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 2
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 20% line 2, 80% line 3
         WriteBlendedLine2x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 3
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 60% line 3, 40% line 4
         WriteBlendedLine2x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 4
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 4
         WriteLine2x(screenp, bufp);
         screenp += dest_pitch; bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, stretch_tables, WriteBlendedLine2x(), WriteLine2x(), y, and y1().
I_Stretch3x()
static boolean I_Stretch3x (int x1, int y1, int x2, int y2) static
Definition at line 654 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     // Need to byte-copy from buffer into the screen buffer
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + y1 * dest_pitch + x1;
     // For every 5 lines of src_buffer, 18 lines are written to dest_buffer.
     // (200 -> 720)
     for (y=0; y<SCREENHEIGHT; y += 5)
     {
         // 100% line 0
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 60% line 0, 40% line 1
         WriteBlendedLine3x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 1
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 1
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 1
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 20% line 1, 80% line 2
         WriteBlendedLine3x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 2
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 2
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 80% line 2, 20% line 3
         WriteBlendedLine3x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 3
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 3
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 3
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 40% line 3, 60% line 4
         WriteBlendedLine3x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 4
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 4
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 4
         WriteLine3x(screenp, bufp);
         screenp += dest_pitch; bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, stretch_tables, WriteBlendedLine3x(), WriteLine3x(), y, and y1().
I_Stretch4x()
static boolean I_Stretch4x (int x1, int y1, int x2, int y2) static
Definition at line 795 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     // Need to byte-copy from buffer into the screen buffer
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + y1 * dest_pitch + x1;
     // For every 5 lines of src_buffer, 24 lines are written to dest_buffer.
     // (200 -> 960)
     for (y=0; y<SCREENHEIGHT; y += 5)
     {
         // 100% line 0
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 90% line 0, 20% line 1
         WriteBlendedLine4x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 1
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 1
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 1
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 1
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 60% line 1, 40% line 2
         WriteBlendedLine4x(screenp, bufp + SCREENWIDTH, bufp, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 2
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 2
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 2
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 2
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 40% line 2, 60% line 3
         WriteBlendedLine4x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[1]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 3
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 3
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 3
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 3
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 20% line 3, 80% line 4
         WriteBlendedLine4x(screenp, bufp, bufp + SCREENWIDTH, stretch_tables[0]);
         screenp += dest_pitch; bufp += SCREENWIDTH;
         // 100% line 4
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 4
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 4
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 4
         WriteLine4x(screenp, bufp);
         screenp += dest_pitch; bufp += SCREENWIDTH;
     }
     return true;
 }
References dest_buffer, dest_pitch, SCREENHEIGHT, SCREENWIDTH, src_buffer, stretch_tables, WriteBlendedLine4x(), WriteLine4x(), y, and y1().
I_Stretch5x()
static boolean I_Stretch5x (int x1, int y1, int x2, int y2) static
Definition at line 942 of file i_scale.c.
 {
     byte *bufp, *screenp;
     int y;
     // Only works with full screen update
     if (x1 != 0 || y1 != 0 || x2 != SCREENWIDTH || y2 != SCREENHEIGHT)
     {
         return false;
     }
     // Need to byte-copy from buffer into the screen buffer
     bufp = src_buffer + y1 * SCREENWIDTH + x1;
     screenp = (byte *) dest_buffer + y1 * dest_pitch + x1;
     // For every 1 line of src_buffer, 6 lines are written to dest_buffer.
     // (200 -> 1200)
     for (y=0; y<SCREENHEIGHT; y += 1)
     {
         // 100% line 0
         WriteLine5x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine5x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine5x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine5x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine5x(screenp, bufp);
         screenp += dest_pitch;
         // 100% line 0
         WriteLine5x(screenp, bufp);
         screenp += dest_pitch; bufp += SCREENWIDTH;
     }
     // test hack for Porsche Monty... scan line simulation:
     // See here: http://www.doomworld.com/vb/post/962612
     if (M_CheckParm("-scanline") > 0)
     {
         screenp = (byte *) dest_buffer + 2 * dest_pitch;
         for (y=0; y<1198; y += 3)
         {
             memset(screenp, 0, 1600);
             screenp += dest_pitch * 3;
         }
     }
     return true;
 }
References dest_buffer, dest_pitch, M_CheckParm(), memset(), SCREENHEIGHT, SCREENWIDTH, src_buffer, WriteLine5x(), y, and y1().
WriteBlendedLine1x()
static void WriteBlendedLine1x (byte * dest, byte * src1, byte * src2, byte * stretch_table) inline static
Definition at line 434 of file i_scale.c.
 {
     int x;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         *dest = stretch_table[*src1 * 256 + *src2];
         ++dest;
         ++src1;
         ++src2;
     }
 }
References SCREENWIDTH, and x.
Referenced by I_Stretch1x().
WriteBlendedLine2x()
static void WriteBlendedLine2x (byte * dest, byte * src1, byte * src2, byte * stretch_table) inline static
Definition at line 520 of file i_scale.c.
 {
     int x;
     int val;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         val = stretch_table[*src1 * 256 + *src2];
         dest[0] = val;
         dest[1] = val;
         dest += 2;
         ++src1;
         ++src2;
     }
 }
References SCREENWIDTH, val, and x.
Referenced by I_Stretch2x().
WriteBlendedLine3x()
static void WriteBlendedLine3x (byte * dest, byte * src1, byte * src2, byte * stretch_table) inline static
Definition at line 634 of file i_scale.c.
 {
     int x;
     int val;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         val = stretch_table[*src1 * 256 + *src2];
         dest[0] = val;
         dest[1] = val;
         dest[2] = val;
         dest += 3;
         ++src1;
         ++src2;
     }
 }
References SCREENWIDTH, val, and x.
Referenced by I_Stretch3x().
WriteBlendedLine4x()
static void WriteBlendedLine4x (byte * dest, byte * src1, byte * src2, byte * stretch_table) inline static
Definition at line 774 of file i_scale.c.
 {
     int x;
     int val;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         val = stretch_table[*src1 * 256 + *src2];
         dest[0] = val;
         dest[1] = val;
         dest[2] = val;
         dest[3] = val;
         dest += 4;
         ++src1;
         ++src2;
     }
 }
References SCREENWIDTH, val, and x.
Referenced by I_Stretch4x().
WriteLine2x()
static void WriteLine2x (byte * dest, byte * src) inline static
Definition at line 507 of file i_scale.c.
 {
     int x;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         dest[0] = *src;
         dest[1] = *src;
         dest += 2;
         ++src;
     }
 }
References SCREENWIDTH, src, and x.
Referenced by I_Stretch2x().
WriteLine3x()
static void WriteLine3x (byte * dest, byte * src) inline static
Definition at line 620 of file i_scale.c.
 {
     int x;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         dest[0] = *src;
         dest[1] = *src;
         dest[2] = *src;
         dest += 3;
         ++src;
     }
 }
References SCREENWIDTH, src, and x.
Referenced by I_Stretch3x().
WriteLine4x()
static void WriteLine4x (byte * dest, byte * src) inline static
Definition at line 759 of file i_scale.c.
 {
     int x;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         dest[0] = *src;
         dest[1] = *src;
         dest[2] = *src;
         dest[3] = *src;
         dest += 4;
         ++src;
     }
 }
References SCREENWIDTH, src, and x.
Referenced by I_Stretch4x().
WriteLine5x()
static void WriteLine5x (byte * dest, byte * src) inline static
Definition at line 924 of file i_scale.c.
 {
     int x;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         dest[0] = *src;
         dest[1] = *src;
         dest[2] = *src;
         dest[3] = *src;
         dest[4] = *src;
         dest += 5;
         ++src;
     }
 }
References SCREENWIDTH, src, and x.
Referenced by I_Stretch5x().
WriteSquashedLine1x()
static void WriteSquashedLine1x (byte * dest, byte * src) inline static
Definition at line 1030 of file i_scale.c.
 {
     int x;
     for (x=0; x<SCREENWIDTH; )
     {
         // Draw in blocks of 5
         // 80% pixel 0,   20% pixel 1
         *dest++ = stretch_tables[0][src[1] * 256 + src[0]];
         // 60% pixel 1,   40% pixel 2
         *dest++ = stretch_tables[1][src[2] * 256 + src[1]];
         // 40% pixel 2,   60% pixel 3
         *dest++ = stretch_tables[1][src[2] * 256 + src[3]];
         // 20% pixel 3,   80% pixel 4
         *dest++ = stretch_tables[0][src[3] * 256 + src[4]];
         x += 5;
         src += 5;
     }
 }
References SCREENWIDTH, src, stretch_tables, and x.
Referenced by I_Squash1x().
WriteSquashedLine2x()
static void WriteSquashedLine2x (byte * dest, byte * src) inline static
Definition at line 1102 of file i_scale.c.
 {
     byte *dest2;
     int x, c;
     dest2 = dest + dest_pitch;
     for (x=0; x<SCREENWIDTH; )
     {
         // Draw in blocks of 5
         // 100% pixel 0
         c = src[0];
         DRAW_PIXEL2;
         // 60% pixel 0, 40% pixel 1
         c = stretch_tables[1][src[1] * 256 + src[0]];
         DRAW_PIXEL2;
         // 100% pixel 1
         c = src[1];
         DRAW_PIXEL2;
         // 20% pixel 1, 80% pixel 2
         c = stretch_tables[0][src[1] * 256 + src[2]];
         DRAW_PIXEL2;
         // 80% pixel 2, 20% pixel 3
         c = stretch_tables[0][src[3] * 256 + src[2]];
         DRAW_PIXEL2;
         // 100% pixel 3
         c = src[3];
         DRAW_PIXEL2;
         // 40% pixel 3, 60% pixel 4
         c = stretch_tables[1][src[3] * 256 + src[4]];
         DRAW_PIXEL2;
         // 100% pixel 4
         c = src[4];
         DRAW_PIXEL2;
         x += 5;
         src += 5;
     }
 }
References c, dest_pitch, DRAW_PIXEL2, SCREENWIDTH, src, stretch_tables, and x.
Referenced by I_Squash2x().
WriteSquashedLine3x()
static void WriteSquashedLine3x (byte * dest, byte * src) inline static
Definition at line 1197 of file i_scale.c.
 {
     byte *dest2, *dest3;
     int x, c;
     dest2 = dest + dest_pitch;
     dest3 = dest + dest_pitch * 2;
     for (x=0; x<SCREENWIDTH; )
     {
         // Every 2 pixels is expanded to 5 pixels
         // 100% pixel 0 x2
         c = src[0];
         DRAW_PIXEL3;
         DRAW_PIXEL3;
         // 50% pixel 0, 50% pixel 1
         c = half_stretch_table[src[0] * 256 + src[1]];
         DRAW_PIXEL3;
         // 100% pixel 1
         c = src[1];
         DRAW_PIXEL3;
         DRAW_PIXEL3;
         x += 2;
         src += 2;
     }
 }
References c, dest_pitch, DRAW_PIXEL3, half_stretch_table, SCREENWIDTH, src, and x.
Referenced by I_Squash3x().
WriteSquashedLine4x()
static void WriteSquashedLine4x (byte * dest, byte * src) inline static
Definition at line 1279 of file i_scale.c.
 {
     int x;
     int c;
     byte *dest2, *dest3, *dest4;
     dest2 = dest + dest_pitch;
     dest3 = dest + dest_pitch * 2;
     dest4 = dest + dest_pitch * 3;
     for (x=0; x<SCREENWIDTH; )
     {
         // Draw in blocks of 5
         // 100% pixel 0  x3
         c = src[0];
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         // 20% pixel 0,  80% pixel 1
         c = stretch_tables[0][src[0] * 256 + src[1]];
         DRAW_PIXEL4;
         // 100% pixel 1 x2
         c = src[1];
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         // 40% pixel 1, 60% pixel 2
         c = stretch_tables[1][src[1] * 256 + src[2]];
         DRAW_PIXEL4;
         // 100% pixel 2 x2
         c = src[2];
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         // 60% pixel 2, 40% pixel 3
         c = stretch_tables[1][src[3] * 256 + src[2]];
         DRAW_PIXEL4;
         // 100% pixel 3 x2
         c = src[3];
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         // 80% pixel 3, 20% pixel 4
         c = stretch_tables[0][src[4] * 256 + src[3]];
         DRAW_PIXEL4;
         // 100% pixel 4
         c = src[4];
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         DRAW_PIXEL4;
         x += 5;
         src += 5;
     }
 }
References c, dest_pitch, DRAW_PIXEL4, SCREENWIDTH, src, stretch_tables, and x.
Referenced by I_Squash4x().
WriteSquashedLine5x()
static void WriteSquashedLine5x (byte * dest, byte * src) inline static
Definition at line 1390 of file i_scale.c.
 {
     int x;
     int c;
     byte *dest2, *dest3, *dest4, *dest5;
     dest2 = dest + dest_pitch;
     dest3 = dest + dest_pitch * 2;
     dest4 = dest + dest_pitch * 3;
     dest5 = dest + dest_pitch * 4;
     for (x=0; x<SCREENWIDTH; ++x)
     {
         // Draw in blocks of 5
         // 100% pixel 0  x4
         c = *src++;
         DRAW_PIXEL5;
         DRAW_PIXEL5;
         DRAW_PIXEL5;
         DRAW_PIXEL5;
     }
 }
References c, dest_pitch, DRAW_PIXEL5, SCREENWIDTH, src, and x.
Referenced by I_Squash5x().
Variable Documentation
dest_buffer
byte* dest_buffer static
Definition at line 41 of file i_scale.c.
Referenced by I_InitScale(), I_Scale1x(), I_Scale2x(), I_Scale3x(), I_Scale4x(), I_Scale5x(), I_Squash1x(), I_Squash2x(), I_Squash3x(), I_Squash4x(), I_Squash5x(), I_Stretch1x(), I_Stretch2x(), I_Stretch3x(), I_Stretch4x(), and I_Stretch5x().
dest_pitch
int dest_pitch static
Definition at line 45 of file i_scale.c.
Referenced by I_InitScale(), I_Scale1x(), I_Scale2x(), I_Scale3x(), I_Scale4x(), I_Scale5x(), I_Squash1x(), I_Squash2x(), I_Squash3x(), I_Squash4x(), I_Squash5x(), I_Stretch1x(), I_Stretch2x(), I_Stretch3x(), I_Stretch4x(), I_Stretch5x(), WriteSquashedLine2x(), WriteSquashedLine3x(), WriteSquashedLine4x(), and WriteSquashedLine5x().
half_stretch_table
byte* half_stretch_table = NULL static
Definition at line 56 of file i_scale.c.
Referenced by I_InitSquashTable(), I_ResetScaleTables(), and WriteSquashedLine3x().
mode_scale_1x
screen_mode_t mode_scale_1x
Initial value:
= {
    SCREENWIDTH, SCREENHEIGHT,
    NULL,
    I_Scale1x,
    false,
}
Definition at line 96 of file i_scale.c.
mode_scale_2x
screen_mode_t mode_scale_2x
Initial value:
= {
    SCREENWIDTH * 2, SCREENHEIGHT * 2,
    NULL,
    I_Scale2x,
    false,
}
Definition at line 137 of file i_scale.c.
mode_scale_3x
screen_mode_t mode_scale_3x
Initial value:
= {
    SCREENWIDTH * 3, SCREENHEIGHT * 3,
    NULL,
    I_Scale3x,
    false,
}
Definition at line 182 of file i_scale.c.
mode_scale_4x
screen_mode_t mode_scale_4x
Initial value:
= {
    SCREENWIDTH * 4, SCREENHEIGHT * 4,
    NULL,
    I_Scale4x,
    false,
}
Definition at line 231 of file i_scale.c.
mode_scale_5x
screen_mode_t mode_scale_5x
Initial value:
= {
    SCREENWIDTH * 5, SCREENHEIGHT * 5,
    NULL,
    I_Scale5x,
    false,
}
Definition at line 284 of file i_scale.c.
mode_squash_1x
screen_mode_t mode_squash_1x
Initial value:
= {
    SCREENWIDTH_4_3, SCREENHEIGHT,
    I_InitStretchTables,
    I_Squash1x,
    true,
}
Definition at line 1087 of file i_scale.c.
mode_squash_2x
screen_mode_t mode_squash_2x
Initial value:
= {
    SCREENWIDTH_4_3 * 2, SCREENHEIGHT * 2,
    I_InitStretchTables,
    I_Squash2x,
    false,
}
Definition at line 1186 of file i_scale.c.
mode_squash_3x
screen_mode_t mode_squash_3x
Initial value:
= {
    800, 600,
    I_InitSquashTable,
    I_Squash3x,
    false,
}
Definition at line 1269 of file i_scale.c.
mode_squash_4x
screen_mode_t mode_squash_4x
Initial value:
= {
    SCREENWIDTH_4_3 * 4, SCREENHEIGHT * 4,
    I_InitStretchTables,
    I_Squash4x,
    false,
}
Definition at line 1380 of file i_scale.c.
mode_squash_5x
screen_mode_t mode_squash_5x
Initial value:
= {
    SCREENWIDTH_4_3 * 5, SCREENHEIGHT * 5,
    I_InitStretchTables,
    I_Squash5x,
    false,
}
Definition at line 1445 of file i_scale.c.
mode_stretch_1x
screen_mode_t mode_stretch_1x
Initial value:
= {
    SCREENWIDTH, SCREENHEIGHT_4_3,
    I_InitStretchTables,
    I_Stretch1x,
    true,
}
Definition at line 500 of file i_scale.c.
mode_stretch_2x
screen_mode_t mode_stretch_2x
Initial value:
= {
    SCREENWIDTH * 2, SCREENHEIGHT_4_3 * 2,
    I_InitStretchTables,
    I_Stretch2x,
    false,
}
Definition at line 613 of file i_scale.c.
mode_stretch_3x
screen_mode_t mode_stretch_3x
Initial value:
= {
    SCREENWIDTH * 3, SCREENHEIGHT_4_3 * 3,
    I_InitStretchTables,
    I_Stretch3x,
    false,
}
Definition at line 752 of file i_scale.c.
mode_stretch_4x
screen_mode_t mode_stretch_4x
Initial value:
= {
    SCREENWIDTH * 4, SCREENHEIGHT_4_3 * 4,
    I_InitStretchTables,
    I_Stretch4x,
    false,
}
Definition at line 917 of file i_scale.c.
mode_stretch_5x
screen_mode_t mode_stretch_5x
Initial value:
= {
    SCREENWIDTH * 5, SCREENHEIGHT_4_3 * 5,
    I_InitStretchTables,
    I_Stretch5x,
    false,
}
Definition at line 1007 of file i_scale.c.
src_buffer
byte* src_buffer static
Definition at line 37 of file i_scale.c.
Referenced by I_InitScale(), I_Scale1x(), I_Scale2x(), I_Scale3x(), I_Scale4x(), I_Scale5x(), I_Squash1x(), I_Squash2x(), I_Squash3x(), I_Squash4x(), I_Squash5x(), I_Stretch1x(), I_Stretch2x(), I_Stretch3x(), I_Stretch4x(), and I_Stretch5x().
stretch_tables
byte* stretch_tables[2] = { NULL, NULL } static
Definition at line 52 of file i_scale.c.
Referenced by I_InitStretchTables(), I_ResetScaleTables(), I_Stretch1x(), I_Stretch2x(), I_Stretch3x(), I_Stretch4x(), WriteSquashedLine1x(), WriteSquashedLine2x(), and WriteSquashedLine4x().