Fennix Userspace: Userspace/apps/base/busybox/libbb/copyfd.c File Reference
copyfd.c File Reference
#include "libbb.h"
Macros
#define sendfile(a, b, c, d) (-1)
#define SENDFILE_BIGBUF (16*1024*1024)
Functions
static off_t bb_full_fd_action (int src_fd, int dst_fd, off_t size)
off_t FAST_FUNC bb_copyfd_size (int fd1, int fd2, off_t size)
void FAST_FUNC bb_copyfd_exact_size (int fd1, int fd2, off_t size)
off_t FAST_FUNC bb_copyfd_eof (int fd1, int fd2)
Macro Definition Documentation
sendfile
#define sendfile (a, b, c, d) (-1)
Definition at line 13 of file copyfd.c.
SENDFILE_BIGBUF
#define SENDFILE_BIGBUF (16*1024*1024)
Definition at line 23 of file copyfd.c.
Function Documentation
bb_copyfd_eof()
off_t FAST_FUNC bb_copyfd_eof (int fd1, int fd2)
Definition at line 159 of file copyfd.c.
 {
     return bb_full_fd_action(fd1, fd2, 0);
 }
References bb_full_fd_action().
Referenced by bb_cat(), bbunpack(), copy_file(), crontab_main(), diffreg(), dump_file(), finish_oldfile(), handle_retr(), load_firmware(), lpqr_main(), motd(), pump_data_and_QUIT(), and xprint_and_close_file().
bb_copyfd_exact_size()
void FAST_FUNC bb_copyfd_exact_size (int fd1, int fd2, off_t size)
Definition at line 148 of file copyfd.c.
 {
     off_t sz = bb_copyfd_size(fd1, fd2, size);
     if (sz == (size >= 0 ? size : -size))
         return;
     if (sz != -1)
         bb_simple_error_msg_and_die("short read");
     /* if sz == -1, bb_copyfd_XX already complained */
     xfunc_die();
 }
References bb_copyfd_size(), bb_simple_error_msg_and_die(), off_t, size, and xfunc_die().
Referenced by data_extract_all(), data_extract_to_command(), data_extract_to_stdout(), scriptreplay_main(), seek_by_read(), unzip_extract(), and unzip_skip().
bb_copyfd_size()
off_t FAST_FUNC bb_copyfd_size (int fd1, int fd2, off_t size)
Definition at line 140 of file copyfd.c.
 {
     if (size) {
         return bb_full_fd_action(fd1, fd2, size);
     }
     return 0;
 }
References bb_full_fd_action(), and size.
Referenced by bb_copyfd_exact_size(), lpd_main(), lpqr_main(), shred_main(), and tail_main().
bb_full_fd_action()
static off_t bb_full_fd_action (int src_fd, int dst_fd, off_t size) static
Definition at line 29 of file copyfd.c.
 {
     int status = -1;
     off_t total = 0;
     bool continue_on_write_error = 0;
     ssize_t sendfile_sz;
 #if CONFIG_FEATURE_COPYBUF_KB > 4
     char *buffer = buffer; /* for compiler */
     int buffer_size = 0;
 #else
     char buffer[CONFIG_FEATURE_COPYBUF_KB * 1024];
     enum { buffer_size = sizeof(buffer) };
 #endif
     if (size < 0) {
         size = -size;
         continue_on_write_error = 1;
     }
     if (src_fd < 0)
         goto out;
     sendfile_sz = !ENABLE_FEATURE_USE_SENDFILE
         ? 0
         : SENDFILE_BIGBUF;
     if (!size) {
         size = SENDFILE_BIGBUF;
         status = 1; /* copy until eof */
     }
     while (1) {
         ssize_t rd;
         if (sendfile_sz) {
             /* dst_fd == -1 is a fake, else... */
             if (dst_fd >= 0) {
                 rd = sendfile(dst_fd, src_fd, NULL,
                     size > sendfile_sz ? sendfile_sz : size);
                 if (rd >= 0)
                     goto read_ok;
             }
             sendfile_sz = 0; /* do not try sendfile anymore */
         }
 #if CONFIG_FEATURE_COPYBUF_KB > 4
         if (buffer_size == 0) {
             if (size > 0 && size <= 4 * 1024)
                 goto use_small_buf;
             /* We want page-aligned buffer, just in case kernel is clever
              * and can do page-aligned io more efficiently */
             buffer = mmap_anon(CONFIG_FEATURE_COPYBUF_KB * 1024);
             buffer_size = CONFIG_FEATURE_COPYBUF_KB * 1024;
             if (buffer == MAP_FAILED) {
  use_small_buf:
                 buffer = alloca(4 * 1024);
                 buffer_size = 4 * 1024;
             }
         }
 #endif
         rd = safe_read(src_fd, buffer,
             size > buffer_size ? buffer_size : size);
         if (rd < 0) {
             bb_simple_perror_msg(bb_msg_read_error);
             break;
         }
  read_ok:
         if (!rd) { /* eof - all done */
             status = 0;
             break;
         }
         /* dst_fd == -1 is a fake, else... */
         if (dst_fd >= 0 && !sendfile_sz) {
             ssize_t wr = full_write(dst_fd, buffer, rd);
             if (wr < rd) {
                 if (!continue_on_write_error) {
                     bb_simple_perror_msg(bb_msg_write_error);
                     break;
                 }
                 dst_fd = -1;
             }
         }
         total += rd;
         if (status < 0) { /* if we aren't copying till EOF... */
             size -= rd;
             if (!size) {
                 /* 'size' bytes copied - all done */
                 status = 0;
                 break;
             }
         }
     }
  out:
 /* some environments don't have munmap(), hide it in #if */
 #if CONFIG_FEATURE_COPYBUF_KB > 4
     if (buffer_size > 4 * 1024)
         munmap(buffer, buffer_size);
 #endif
     return status ? -1 : total;
 }
References alloca, bb_msg_read_error, bb_msg_write_error, bb_simple_perror_msg(), buffer, full_write(), MAP_FAILED, mmap_anon(), munmap(), NULL, off_t, out(), rd, safe_read(), sendfile, SENDFILE_BIGBUF, size, status, and total.
Referenced by bb_copyfd_eof(), and bb_copyfd_size().