Fennix Userspace: Userspace/musl/src/stdio/__fdopen.c File Reference
__fdopen.c File Reference
#include "stdio_impl.h"
#include <stdlib.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include "libc.h"
Functions
FILE * __fdopen (int fd, const char *mode)
weak_alias (__fdopen, fdopen)
Function Documentation
__fdopen()
FILE* __fdopen (int fd, const char * mode)
Definition at line 9 of file __fdopen.c.
 {
     FILE *f;
     struct winsize wsz;
     /* Check for valid initial mode character */
     if (!strchr("rwa", *mode)) {
         errno = EINVAL;
         return 0;
     }
     /* Allocate FILE+buffer or fail */
     if (!(f=malloc(sizeof *f + UNGET + BUFSIZ))) return 0;
     /* Zero-fill only the struct, not the buffer */
     memset(f, 0, sizeof *f);
     /* Impose mode restrictions */
     if (!strchr(mode, '+')) f->flags = (*mode == 'r') ? F_NOWR : F_NORD;
     /* Apply close-on-exec flag */
     if (strchr(mode, 'e')) __syscall(SYS_fcntl, fd, F_SETFD, FD_CLOEXEC);
     /* Set append mode on fd if opened for append */
     if (*mode == 'a') {
         int flags = __syscall(SYS_fcntl, fd, F_GETFL);
         if (!(flags & O_APPEND))
             __syscall(SYS_fcntl, fd, F_SETFL, flags | O_APPEND);
         f->flags |= F_APP;
     }
     f->fd = fd;
     f->buf = (unsigned char *)f + sizeof *f + UNGET;
     f->buf_size = BUFSIZ;
     /* Activate line buffered mode for terminals */
     f->lbf = EOF;
     if (!(f->flags & F_NOWR) && !__syscall(SYS_ioctl, fd, TIOCGWINSZ, &wsz))
         f->lbf = '\n';
     /* Initialize op ptrs. No problem if some are unneeded. */
     f->read = __stdio_read;
     f->write = __stdio_write;
     f->seek = __stdio_seek;
     f->close = __stdio_close;
     if (!libc.threaded) f->lock = -1;
     /* Add new FILE to open file list */
     return __ofl_add(f);
 }
References __ofl_add(), __stdio_close(), __stdio_read(), __stdio_seek(), __stdio_write(), __syscall, _IO_FILE::buf, _IO_FILE::buf_size, BUFSIZ, _IO_FILE::close, EINVAL, EOF, errno, f, F_APP, F_GETFL, F_NORD, F_NOWR, F_SETFD, F_SETFL, _IO_FILE::fd, FD_CLOEXEC, _IO_FILE::flags, _IO_FILE::lbf, libc, _IO_FILE::lock, malloc, memset(), O_APPEND, _IO_FILE::read, _IO_FILE::seek, strchr(), TIOCGWINSZ, UNGET, and _IO_FILE::write.
Referenced by fopen(), and tmpfile().
weak_alias()
weak_alias (__fdopen , fdopen)