Fennix: Userspace/mlibc/options/ansi/musl-generic-math/expm1f.c File Reference
expm1f.c File Reference
#include "libm.h"
Functions
float expm1f (float x)
Variables
static const float o_threshold = 8.8721679688e+01
static const float ln2_hi = 6.9313812256e-01
static const float ln2_lo = 9.0580006145e-06
static const float invln2 = 1.4426950216e+00
static const float Q1 = -3.3333212137e-2
static const float Q2 = 1.5807170421e-3
Function Documentation
expm1f()
float expm1f (float x)
Definition at line 31 of file expm1f.c.
 {
     float_t y,hi,lo,c,t,e,hxs,hfx,r1,twopk;
     union {float f; uint32_t i;} u = {x};
     uint32_t hx = u.i & 0x7fffffff;
     int k, sign = u.i >> 31;
     /* filter out huge and non-finite argument */
     if (hx >= 0x4195b844) {  /* if |x|>=27*ln2 */
         if (hx > 0x7f800000)  /* NaN */
             return x;
         if (sign)
             return -1;
         if (x > o_threshold) {
             x *= 0x1p127f;
             return x;
         }
     }
     /* argument reduction */
     if (hx > 0x3eb17218) {           /* if  |x| > 0.5 ln2 */
         if (hx < 0x3F851592) {       /* and |x| < 1.5 ln2 */
             if (!sign) {
                 hi = x - ln2_hi;
                 lo = ln2_lo;
                 k =  1;
             } else {
                 hi = x + ln2_hi;
                 lo = -ln2_lo;
                 k = -1;
             }
         } else {
             k  = invln2*x + (sign ? -0.5f : 0.5f);
             t  = k;
             hi = x - t*ln2_hi;      /* t*ln2_hi is exact here */
             lo = t*ln2_lo;
         }
         x = hi-lo;
         c = (hi-x)-lo;
     } else if (hx < 0x33000000) {  /* when |x|<2**-25, return x */
         if (hx < 0x00800000)
             FORCE_EVAL(x*x);
         return x;
     } else
         k = 0;
     /* x is now in primary range */
     hfx = 0.5f*x;
     hxs = x*hfx;
     r1 = 1.0f+hxs*(Q1+hxs*Q2);
     t  = 3.0f - r1*hfx;
     e  = hxs*((r1-t)/(6.0f - x*t));
     if (k == 0)  /* c is 0 */
         return x - (x*e-hxs);
     e  = x*(e-c) - c;
     e -= hxs;
     /* exp(x) ~ 2^k (x_reduced - e + 1) */
     if (k == -1)
         return 0.5f*(x-e) - 0.5f;
     if (k == 1) {
         if (x < -0.25f)
             return -2.0f*(e-(x+0.5f));
         return 1.0f + 2.0f*(x-e);
     }
     u.i = (0x7f+k)<<23;  /* 2^k */
     twopk = u.f;
     if (k < 0 || k > 56) {   /* suffice to return exp(x)-1 */
         y = x - e + 1.0f;
         if (k == 128)
             y = y*2.0f*0x1p127f;
         else
             y = y*twopk;
         return y - 1.0f;
     }
     u.i = (0x7f-k)<<23;  /* 2^-k */
     if (k < 23)
         y = (x-e+(1-u.f))*twopk;
     else
         y = (x-(e+u.f)+1)*twopk;
     return y;
 }
References c, FORCE_EVAL, i, invln2, k, ln2_hi, ln2_lo, o_threshold, Q1, Q2, r1, x, and y.
Referenced by coshf(), sinhf(), and tanhf().
Variable Documentation
invln2
const float invln2 = 1.4426950216e+00 static
Definition at line 22 of file expm1f.c.
Referenced by expm1f().
ln2_hi
const float ln2_hi = 6.9313812256e-01 static
Definition at line 20 of file expm1f.c.
Referenced by expm1f().
ln2_lo
const float ln2_lo = 9.0580006145e-06 static
Definition at line 21 of file expm1f.c.
Referenced by expm1f().
o_threshold
const float o_threshold = 8.8721679688e+01 static
Definition at line 19 of file expm1f.c.
Referenced by expm1f().
Q1
const float Q1 = -3.3333212137e-2 static
Definition at line 28 of file expm1f.c.
Referenced by expm1f().
Q2
const float Q2 = 1.5807170421e-3 static
Definition at line 29 of file expm1f.c.
Referenced by expm1f().