Fennix Userspace: Userspace/mlibc/options/posix/include/dirent.h File Reference
dirent.h File Reference
#include <abi-bits/ino_t.h>
#include <bits/off_t.h>
#include <bits/types.h>
Data Structures
struct dirent
struct dirent64
struct __mlibc_dir_struct
Macros
#define DT_UNKNOWN 0
#define DT_FIFO 1
#define DT_CHR 2
#define DT_DIR 4
#define DT_BLK 6
#define DT_REG 8
#define DT_LNK 10
#define DT_SOCK 12
#define DT_WHT 14
#define __MLIBC_DIRENT_BODY
#define d_fileno d_ino
#define IFTODT(mode) (((mode) & 0170000) >> 12)
Typedefs
typedef struct __mlibc_dir_struct DIR
Functions
int alphasort (const struct dirent **, const struct dirent **)
int closedir (DIR *)
int dirfd (DIR *)
DIR * fdopendir (int)
DIR * opendir (const char *)
struct dirent * readdir (DIR *)
int readdir_r (DIR *__restrict, struct dirent *__restrict, struct dirent **__restrict)
void rewinddir (DIR *)
int scandir (const char *, struct dirent ***, int(*)(const struct dirent *), int(*)(const struct dirent **, const struct dirent **))
void seekdir (DIR *, long)
long telldir (DIR *)
int versionsort (const struct dirent **, const struct dirent **)
Data Structure Documentation
dirent
struct dirent
Definition at line 29 of file dirent.h.
dirent64
struct dirent64
Definition at line 33 of file dirent.h.
__mlibc_dir_struct
struct __mlibc_dir_struct
Definition at line 43 of file dirent.h.
Data Fields
struct dirent __current
char __ent_buffer[2048]
__mlibc_size __ent_limit
__mlibc_size __ent_next
int __handle
Macro Definition Documentation
__MLIBC_DIRENT_BODY
#define __MLIBC_DIRENT_BODY
Value:
            ino_t d_ino; \
            off_t d_off; \
            unsigned short d_reclen; \
            unsigned char d_type; \
            char d_name[1024];
Definition at line 23 of file dirent.h.
d_fileno
#define d_fileno d_ino
Definition at line 37 of file dirent.h.
DT_BLK
#define DT_BLK 6
Definition at line 17 of file dirent.h.
DT_CHR
#define DT_CHR 2
Definition at line 15 of file dirent.h.
DT_DIR
#define DT_DIR 4
Definition at line 16 of file dirent.h.
DT_FIFO
#define DT_FIFO 1
Definition at line 14 of file dirent.h.
DT_LNK
#define DT_LNK 10
Definition at line 19 of file dirent.h.
DT_REG
#define DT_REG 8
Definition at line 18 of file dirent.h.
DT_SOCK
#define DT_SOCK 12
Definition at line 20 of file dirent.h.
DT_UNKNOWN
#define DT_UNKNOWN 0
Definition at line 13 of file dirent.h.
DT_WHT
#define DT_WHT 14
Definition at line 21 of file dirent.h.
IFTODT
#define IFTODT (mode) (((mode) & 0170000) >> 12)
Definition at line 41 of file dirent.h.
Typedef Documentation
DIR
typedef struct __mlibc_dir_struct DIR
Definition at line 1 of file dirent.h.
Function Documentation
alphasort()
int alphasort (const struct dirent ** a, const struct dirent ** b)
Definition at line 16 of file dirent-stubs.cpp.
{
     return strcoll((*a)->d_name, (*b)->d_name);
 }
References strcoll().
closedir()
int closedir (DIR * dir)
Definition at line 20 of file dirent-stubs.cpp.
{
     // TODO: Deallocate the dir structure.
     close(dir->__handle);
     return 0;
 }
References __mlibc_dir_struct::__handle, and close().
Referenced by do_glob().
dirfd()
int dirfd (DIR * dir)
Definition at line 25 of file dirent-stubs.cpp.
                     {
     return dir->__handle;
 }
References __mlibc_dir_struct::__handle.
Referenced by faccessat(), fchmodat(), fstatat(), mkdirat(), mkfifoat(), mknodat(), openat(), symlinkat(), mlibc::sys_faccessat(), mlibc::sys_fchownat(), mlibc::sys_mkdirat(), mlibc::sys_mkfifoat(), mlibc::sys_mknodat(), mlibc::sys_openat(), mlibc::sys_symlinkat(), mlibc::sys_utimensat(), and utimensat().
fdopendir()
DIR* fdopendir (int fd)
Definition at line 28 of file dirent-stubs.cpp.
{
     struct stat st;
     if(fstat(fd, &st) < 0) {
         return nullptr;
     }
     // Musl implements this, but O_PATH is only declared on the linux abi
     /*if(fcntl(fd, F_GETFL) & O_PATH) {
         errno = EBADF;
         return nullptr;
     }*/
     if(!S_ISDIR(st.st_mode)) {
         errno = ENOTDIR;
         return nullptr;
     }
     auto dir = frg::construct<__mlibc_dir_struct>(getAllocator());
     __ensure(dir);
     dir->__ent_next = 0;
     dir->__ent_limit = 0;
     int flags = fcntl(fd, F_GETFD);
     fcntl(fd, F_SETFD, flags | FD_CLOEXEC);
     dir->__handle = fd;
     return dir;
 }
References __ensure, ENOTDIR, errno, F_GETFD, F_SETFD, fcntl(), fd, FD_CLOEXEC, mlibc::flags, fstat(), getAllocator(), S_ISDIR, and stat::st_mode.
opendir()
DIR* opendir (const char * path)
Definition at line 52 of file dirent-stubs.cpp.
{
     auto dir = frg::construct<__mlibc_dir_struct>(getAllocator());
     __ensure(dir);
     dir->__ent_next = 0;
     dir->__ent_limit = 0;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_open_dir, nullptr);
     if(int e = mlibc::sys_open_dir(path, &dir->__handle); e) {
         errno = e;
         frg::destruct(getAllocator(), dir);
         return nullptr;
     }else{
         return dir;
     }
 }
References __ensure, errno, getAllocator(), MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_open_dir().
Referenced by do_glob(), and scandir().
readdir()
struct dirent* readdir (DIR * dir)
Definition at line 67 of file dirent-stubs.cpp.
{
     __ensure(dir->__ent_next <= dir->__ent_limit);
     if(dir->__ent_next == dir->__ent_limit) {
         MLIBC_CHECK_OR_ENOSYS(mlibc::sys_read_entries, nullptr);
         if(int e = mlibc::sys_read_entries(dir->__handle, dir->__ent_buffer, 2048, &dir->__ent_limit); e)
             __ensure(!"mlibc::sys_read_entries() failed");
         dir->__ent_next = 0;
         if(!dir->__ent_limit)
             return nullptr;
     }
     auto entp = reinterpret_cast<struct dirent *>(dir->__ent_buffer + dir->__ent_next);
     // We only copy as many bytes as we need to avoid buffer-overflows.
     memcpy(&dir->__current, entp, offsetof(struct dirent, d_name) + strlen(entp->d_name) + 1);
     dir->__ent_next += entp->d_reclen;
     return &dir->__current;
 }
References __mlibc_dir_struct::__current, __ensure, __mlibc_dir_struct::__ent_buffer, __mlibc_dir_struct::__ent_limit, __mlibc_dir_struct::__ent_next, __mlibc_dir_struct::__handle, memcpy(), MLIBC_CHECK_OR_ENOSYS, offsetof, strlen(), and mlibc::sys_read_entries().
Referenced by do_glob(), and scandir().
readdir_r()
int readdir_r (DIR * __restrict, struct dirent * __restrict, struct dirent ** __restrict)
Definition at line 84 of file dirent-stubs.cpp.
{
     if(!mlibc::sys_read_entries) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     __ensure(dir->__ent_next <= dir->__ent_limit);
     if(dir->__ent_next == dir->__ent_limit) {
         if(int e = mlibc::sys_read_entries(dir->__handle, dir->__ent_buffer, 2048, &dir->__ent_limit); e)
             __ensure(!"mlibc::sys_read_entries() failed");
         dir->__ent_next = 0;
         if(!dir->__ent_limit) {
             *result = NULL;
             return 0;
         }
     }
     auto entp = reinterpret_cast<struct dirent *>(dir->__ent_buffer + dir->__ent_next);
     // We only copy as many bytes as we need to avoid buffer-overflows.
     memcpy(entry, entp, offsetof(struct dirent, d_name) + strlen(entp->d_name) + 1);
     dir->__ent_next += entp->d_reclen;
     *result = entry;
     return 0;
 }
References __ensure, __mlibc_dir_struct::__ent_buffer, __mlibc_dir_struct::__ent_limit, __mlibc_dir_struct::__ent_next, __mlibc_dir_struct::__handle, ENOSYS, memcpy(), MLIBC_MISSING_SYSDEP, NULL, offsetof, strlen(), and mlibc::sys_read_entries().
rewinddir()
void rewinddir (DIR * dir)
Definition at line 109 of file dirent-stubs.cpp.
{
     lseek(dir->__handle, 0, SEEK_SET);
     dir->__ent_next = 0;
 }
References __mlibc_dir_struct::__ent_next, __mlibc_dir_struct::__handle, lseek(), and SEEK_SET.
scandir()
int scandir (const char * path, struct dirent *** res, int(*)(const struct dirent *) select, int(*)(const struct dirent **, const struct dirent **) compare)
Definition at line 114 of file dirent-stubs.cpp.
{
     DIR *dir = opendir(path);
     if (!dir)
         return -1; // errno will be set by opendir()
     // we should save the errno
     int old_errno = errno;
     errno = 0;
     struct dirent *dir_ent;
     struct dirent **array = nullptr, **tmp = nullptr;
     int length = 0;
     int count = 0;
     while((dir_ent = readdir(dir)) && !errno) {
         if(select && !select(dir_ent))
             continue;
         if(count >= length) {
             length = 2*length + 1;
             tmp = static_cast<struct dirent**>(realloc(array,
                         length * sizeof(struct dirent*)));
             // we need to check the call actually goes through
             // before we overwrite array so that we can
             // deallocate the already written entries should realloc()
             // have failed
             if(!tmp)
                 break;
             array = tmp;
         }
         array[count] = static_cast<struct dirent*>(malloc(dir_ent->d_reclen));
         if(!array[count])
             break;
         memcpy(array[count], dir_ent, dir_ent->d_reclen);
         count++;
     }
     if(errno) {
         if(array)
             while(count-- > 0)
                 free(array[count]);
         free(array);
         return -1;
     }
     // from here we can set the old errno back
     errno = old_errno;
     if(compare)
         qsort(array, count, sizeof(struct dirent*),
                 (int (*)(const void *, const void *)) compare);
     *res = array;
     return count;
 }
References compare(), mlibc::count, errno, free(), malloc(), memcpy(), opendir(), qsort(), readdir(), realloc(), and select().
seekdir()
void seekdir (DIR * , long)
Definition at line 169 of file dirent-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
telldir()
long telldir (DIR *)
Definition at line 173 of file dirent-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
versionsort()
int versionsort (const struct dirent ** a, const struct dirent ** b)
Definition at line 178 of file dirent-stubs.cpp.
{
     return strverscmp((*a)->d_name, (*b)->d_name);
 }
References strverscmp().