Fennix: VMwareMouse Namespace Reference
VMwareMouse Namespace Reference
Data Structures
struct VMwareCommand
union VMwareCommand.__unnamed852__
union VMwareCommand.__unnamed854__
union VMwareCommand.__unnamed856__
union VMwareCommand.__unnamed858__
Enumerations
enum Config { READ_CONFIG = 0x20 , WRITE_CONFIG = 0x60 }
enum Ports { DATA = 0x60 , STATUS = 0x64 , COMMAND = 0x64 }
enum State { OUTPUT_FULL = (1 << 0) , INPUT_FULL = (1 << 1) , MOUSE_BYTE = (1 << 5) }
Functions
void CommandSend (VMwareCommand *cmd)
bool IsVMwareBackdoorAvailable (void)
int DriverEntry (void *Data)
void Absolute (void)
void Relative (void)
void WaitRead ()
void WaitWrite ()
void Write (uint16_t Port, uint8_t Value)
uint8_t Read ()
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *)
Variables
KernelAPI KAPI
int MouseX = 0
int MouseY = 0
int MouseZ = 0
int MouseButton = 0
bool InputReceived = false
Data Structure Documentation
VMwareMouse::VMwareCommand
struct VMwareMouse::VMwareCommand
Definition at line 38 of file mouse.hpp.
Data Fields
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
uint32_t di
uint32_t si
VMwareMouse::VMwareCommand.__unnamed852__
union VMwareMouse::VMwareCommand.__unnamed852__
Definition at line 40 of file mouse.hpp.
Data Fields
uint32_t ax
uint32_t magic
VMwareMouse::VMwareCommand.__unnamed854__
union VMwareMouse::VMwareCommand.__unnamed854__
Definition at line 45 of file mouse.hpp.
Data Fields
uint32_t bx
size_t size
VMwareMouse::VMwareCommand.__unnamed856__
union VMwareMouse::VMwareCommand.__unnamed856__
Definition at line 50 of file mouse.hpp.
Data Fields
uint16_t command
uint32_t cx
VMwareMouse::VMwareCommand.__unnamed858__
union VMwareMouse::VMwareCommand.__unnamed858__
Definition at line 55 of file mouse.hpp.
Data Fields
uint32_t dx
uint16_t port
Enumeration Type Documentation
Config
enum VMwareMouse::Config
Enumerator
READ_CONFIG
WRITE_CONFIG
Definition at line 82 of file Mouse.cpp.
     {
         READ_CONFIG = 0x20,
         WRITE_CONFIG = 0x60
     };
Ports
enum VMwareMouse::Ports
Enumerator
DATA
STATUS
COMMAND
Definition at line 88 of file Mouse.cpp.
     {
         DATA = 0x60,
         STATUS = 0x64,
         COMMAND = 0x64,
     };
State
enum VMwareMouse::State
Enumerator
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
Definition at line 95 of file Mouse.cpp.
     {
         OUTPUT_FULL = (1 << 0),
         INPUT_FULL = (1 << 1),
         MOUSE_BYTE = (1 << 5)
     };
Function Documentation
Absolute()
void VMwareMouse::Absolute (void)
Definition at line 49 of file Mouse.cpp.
     {
         VMwareCommand cmd;
         /* Enable */
         cmd.bx = ABSPOINTER_ENABLE;
         cmd.command = CMD_ABSPOINTER_COMMAND;
         CommandSend(&cmd);
         /* Status */
         cmd.bx = 0;
         cmd.command = CMD_ABSPOINTER_STATUS;
         CommandSend(&cmd);
         /* Read data (1) */
         cmd.bx = 1;
         cmd.command = CMD_ABSPOINTER_DATA;
         CommandSend(&cmd);
         /* Enable absolute */
         cmd.bx = ABSPOINTER_ABSOLUTE;
         cmd.command = CMD_ABSPOINTER_COMMAND;
         CommandSend(&cmd);
     }
References ABSPOINTER_ABSOLUTE, ABSPOINTER_ENABLE, CMD_ABSPOINTER_COMMAND, CMD_ABSPOINTER_DATA, CMD_ABSPOINTER_STATUS, and CommandSend().
Referenced by CallbackHandler(), and InterruptCallback().
CallbackHandler()
int VMwareMouse::CallbackHandler (KernelCallback * Data)
Definition at line 135 of file Mouse.cpp.
     {
         switch (Data->Reason)
         {
         case AcknowledgeReason:
         {
             debug("Kernel acknowledged the driver.");
             break;
         }
         case ConfigurationReason:
         {
             outb(COMMAND, 0xA8);
             Write(COMMAND, READ_CONFIG);
             uint8_t Status = Read();
             Status |= 0b10;
             Write(COMMAND, WRITE_CONFIG);
             Write(DATA, Status);
             Write(COMMAND, 0xD4);
             Write(DATA, 0xF6);
             Read();
             Write(COMMAND, 0xD4);
             Write(DATA, 0xF4);
             Read();
             Absolute();
             trace("VMware mouse configured.");
             break;
         }
         case QueryReason:
         {
             Data->InputCallback.Mouse.X = (MouseX * KAPI.Display.GetWidth()) / 0xFFFF;
             Data->InputCallback.Mouse.Y = (MouseY * KAPI.Display.GetHeight()) / 0xFFFF;
             Data->InputCallback.Mouse.Z = MouseZ;
             Data->InputCallback.Mouse.Buttons.Left = MouseButton & 0x20;
             Data->InputCallback.Mouse.Buttons.Right = MouseButton & 0x10;
             Data->InputCallback.Mouse.Buttons.Middle = MouseButton & 0x08;
             break;
         }
         case PollWaitReason:
         {
             while (!InputReceived)
                 TaskManager->Yield();
             InputReceived = false;
             Data->InputCallback.Mouse.X = (MouseX * KAPI.Display.GetWidth()) / 0xFFFF;
             Data->InputCallback.Mouse.Y = (MouseY * KAPI.Display.GetHeight()) / 0xFFFF;
             Data->InputCallback.Mouse.Z = MouseZ;
             Data->InputCallback.Mouse.Buttons.Left = MouseButton & 0x20;
             Data->InputCallback.Mouse.Buttons.Right = MouseButton & 0x10;
             Data->InputCallback.Mouse.Buttons.Middle = MouseButton & 0x08;
             break;
         }
         case StopReason:
         {
             Relative();
             // TODO: UNTESTED!!!
             outb(COMMAND, 0xA8);
             Write(COMMAND, READ_CONFIG);
             uint8_t Status = Read();
             Status &= ~0b10;
             Write(COMMAND, WRITE_CONFIG);
             Write(DATA, Status);
             Write(COMMAND, 0xD4);
             Write(DATA, 0xF5);
             Read();
             debug("Driver stopped.");
             break;
         }
         default:
         {
             warn("Unknown reason.");
             break;
         }
         }
         return OK;
     }
References Absolute(), AcknowledgeReason, ConfigurationReason, Data, debug, KernelAPI::Display, KernelAPI::KAPIDisplay::GetHeight, KernelAPI::KAPIDisplay::GetWidth, InputReceived, KAPI, MouseButton, MouseX, MouseY, MouseZ, OK, outb(), PollWaitReason, QueryReason, Read(), READ_CONFIG, Relative(), Status, StopReason, TaskManager, trace, warn, Write(), WRITE_CONFIG, and Tasking::Task::Yield().
CommandSend()
void VMwareMouse::CommandSend (VMwareCommand * cmd)
Definition at line 16 of file Mouse.cpp.
     {
         cmd->magic = VMWARE_MAGIC;
         cmd->port = VMWARE_PORT;
         asm volatile("in %%dx, %0"
                      : "+a"(cmd->ax), "+b"(cmd->bx), "+c"(cmd->cx), "+d"(cmd->dx), "+S"(cmd->si), "+D"(cmd->di));
     }
References VMwareMouse::VMwareCommand::di, VMwareMouse::VMwareCommand::si, VMWARE_MAGIC, and VMWARE_PORT.
Referenced by Absolute(), InterruptCallback(), IsVMwareBackdoorAvailable(), and Relative().
DriverEntry()
int VMwareMouse::DriverEntry (void * Data)
Definition at line 35 of file Mouse.cpp.
     {
         if (!Data)
             return INVALID_KERNEL_API;
         KAPI = *(KernelAPI *)Data;
         if (KAPI.Version.Major < 0 || KAPI.Version.Minor < 0 || KAPI.Version.Patch < 0)
             return KERNEL_API_VERSION_NOT_SUPPORTED;
         if (!IsVMwareBackdoorAvailable())
             return SYSTEM_NOT_SUPPORTED;
         return OK;
     }
References Data, INVALID_KERNEL_API, IsVMwareBackdoorAvailable(), KAPI, KERNEL_API_VERSION_NOT_SUPPORTED, KernelAPI::KAPIVersion::Major, KernelAPI::KAPIVersion::Minor, OK, KernelAPI::KAPIVersion::Patch, SYSTEM_NOT_SUPPORTED, and KernelAPI::Version.
Referenced by StartVMwareMouse().
InterruptCallback()
int VMwareMouse::InterruptCallback (CPURegisters *)
Definition at line 211 of file Mouse.cpp.
     {
         uint8_t Data = inb(0x60);
         (void)Data;
         VMwareCommand cmd;
         cmd.bx = 0;
         cmd.command = CMD_ABSPOINTER_STATUS;
         CommandSend(&cmd);
         if (cmd.ax == 0xFFFF0000)
         {
             warn("VMware mouse is not connected?");
             Relative();
             Absolute();
             return ERROR;
         }
         if ((cmd.ax & 0xFFFF) < 4)
             return ERROR;
         cmd.bx = 4;
         cmd.command = CMD_ABSPOINTER_DATA;
         CommandSend(&cmd);
         int flags = (cmd.ax & 0xFFFF0000) >> 16; /* Not important */
         (void)flags;
         MouseButton = (cmd.ax & 0xFFFF); /* 0x10 = Right, 0x20 = Left, 0x08 = Middle */
         MouseX = cmd.bx;                 /* Both X and Y are scaled from 0 to 0xFFFF */
         MouseY = cmd.cx;                 /* You should map these somewhere to the actual resolution. */
         MouseZ = (int8_t)cmd.dx;         /* Z is a single signed byte indicating scroll direction. */
         InputReceived = true;
         return OK;
     }
References Absolute(), CMD_ABSPOINTER_DATA, CMD_ABSPOINTER_STATUS, CommandSend(), Data, ERROR, flags, inb(), InputReceived, MouseButton, MouseX, MouseY, MouseZ, OK, Relative(), Driver::void(), and warn.
IsVMwareBackdoorAvailable()
bool VMwareMouse::IsVMwareBackdoorAvailable (void)
Definition at line 24 of file Mouse.cpp.
     {
         VMwareCommand cmd;
         cmd.bx = ~VMWARE_MAGIC;
         cmd.command = CMD_GETVERSION;
         CommandSend(&cmd);
         if (cmd.bx != VMWARE_MAGIC || cmd.ax == 0xFFFFFFFF)
             return false;
         return true;
     }
References CMD_GETVERSION, CommandSend(), and VMWARE_MAGIC.
Referenced by DriverEntry().
Read()
uint8_t VMwareMouse::Read ()
Definition at line 124 of file Mouse.cpp.
     {
         WaitRead();
         return inb(Ports::DATA);
     }
References DATA, inb(), and WaitRead().
Referenced by CallbackHandler().
Relative()
void VMwareMouse::Relative (void)
Definition at line 74 of file Mouse.cpp.
     {
         VMwareCommand cmd;
         cmd.bx = ABSPOINTER_RELATIVE;
         cmd.command = CMD_ABSPOINTER_COMMAND;
         CommandSend(&cmd);
     }
References ABSPOINTER_RELATIVE, CMD_ABSPOINTER_COMMAND, and CommandSend().
Referenced by CallbackHandler(), and InterruptCallback().
WaitRead()
void VMwareMouse::WaitRead ()
Definition at line 102 of file Mouse.cpp.
     {
         uint64_t Timeout = 100000;
         while (Timeout--)
             if (inb(Ports::STATUS) & State::OUTPUT_FULL)
                 return;
     }
References inb(), OUTPUT_FULL, and STATUS.
Referenced by Read().
WaitWrite()
void VMwareMouse::WaitWrite ()
Definition at line 110 of file Mouse.cpp.
     {
         uint64_t Timeout = 100000;
         while (Timeout--)
             if ((inb(Ports::STATUS) & State::INPUT_FULL) == 0)
                 return;
     }
References inb(), INPUT_FULL, and STATUS.
Referenced by Write().
Write()
void VMwareMouse::Write (uint16_t Port, uint8_t Value)
Definition at line 118 of file Mouse.cpp.
     {
         WaitWrite();
         outb(Port, Value);
     }
References outb(), and WaitWrite().
Referenced by CallbackHandler().
Variable Documentation
InputReceived
bool VMwareMouse::InputReceived = false
Definition at line 133 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
KAPI
KernelAPI VMwareMouse::KAPI
Definition at line 14 of file Mouse.cpp.
Referenced by CallbackHandler(), and DriverEntry().
MouseButton
int VMwareMouse::MouseButton = 0
Definition at line 131 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseX
int VMwareMouse::MouseX = 0
Definition at line 130 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseY
int VMwareMouse::MouseY = 0
Definition at line 130 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseZ
int VMwareMouse::MouseZ = 0
Definition at line 130 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().