Fennix: Userspace/apps/base/busybox/include/bb_archive.h File Reference
bb_archive.h File Reference
Data Structures
struct file_header_t
struct archive_handle_t
struct tar_header_t
struct BUG_tar_header
struct transformer_state_t
union transformer_state_t.magic
Macros
#define PAX_NEXT_FILE 0
#define PAX_GLOBAL 1
#define ARCHIVE_RESTORE_DATE (1 << 0)
#define ARCHIVE_CREATE_LEADING_DIRS (1 << 1)
#define ARCHIVE_UNLINK_OLD (1 << 2)
#define ARCHIVE_EXTRACT_NEWER (1 << 3)
#define ARCHIVE_DONT_RESTORE_OWNER (1 << 4)
#define ARCHIVE_DONT_RESTORE_PERM (1 << 5)
#define ARCHIVE_NUMERIC_OWNER (1 << 6)
#define ARCHIVE_O_TRUNC (1 << 7)
#define ARCHIVE_REMEMBER_NAMES (1 << 8)
#define TAR_BLOCK_SIZE 512
#define NAME_SIZE 100
#define NAME_SIZE_STR "100"
#define BBUNPK_OPTSTR "cfkvq"
#define BBUNPK_OPTSTRLEN 5
#define BBUNPK_OPTSTRMASK ((1 << BBUNPK_OPTSTRLEN) - 1)
#define fork_transformer_with_sig(fd, transformer, transform_prog) fork_transformer((fd), (transform_prog))
Typedefs
typedef struct file_header_t file_header_t
typedef struct archive_handle_t archive_handle_t
typedef struct tar_header_t tar_header_t
typedef struct transformer_state_t transformer_state_t
Enumerations
enum {
COMPRESS_MAGIC = 0x9d1f , GZIP_MAGIC = 0x8b1f , BZIP2_MAGIC = 'B' + 'Z' * 256 , XZ_MAGIC1 = 0xfd + '7' * 256 ,
XZ_MAGIC2 = 'z' + ('X' + ('Z' + 0 * 256) * 256) * 256 , XZ_MAGIC1a = 0xfd + ('7' + ('z' + 'X' * 256) * 256) * 256 , XZ_MAGIC2a = 'Z' + 0 * 256
}
enum {
BBUNPK_OPT_STDOUT = 1 << 0 , BBUNPK_OPT_FORCE = 1 << 1 , BBUNPK_OPT_KEEP = 1 << 2 , BBUNPK_OPT_VERBOSE = 1 << 3 ,
BBUNPK_OPT_QUIET = 1 << 4 , BBUNPK_OPT_DECOMPRESS = 1 << 5 , BBUNPK_OPT_TEST = 1 << 6 , BBUNPK_SEAMLESS_MAGIC = (1 << 31) * ENABLE_ZCAT * SEAMLESS_COMPRESSION
}
Functions
void chksum_and_xwrite_tar_header (int fd, struct tar_header_t *hp) FAST_FUNC
archive_handle_t * init_handle (void) FAST_FUNC
char filter_accept_all (archive_handle_t *archive_handle) FAST_FUNC
char filter_accept_list (archive_handle_t *archive_handle) FAST_FUNC
char filter_accept_list_reassign (archive_handle_t *archive_handle) FAST_FUNC
char filter_accept_reject_list (archive_handle_t *archive_handle) FAST_FUNC
void unpack_ar_archive (archive_handle_t *ar_archive) FAST_FUNC
void data_skip (archive_handle_t *archive_handle) FAST_FUNC
void data_extract_all (archive_handle_t *archive_handle) FAST_FUNC
void data_extract_to_stdout (archive_handle_t *archive_handle) FAST_FUNC
void data_extract_to_command (archive_handle_t *archive_handle) FAST_FUNC
void header_skip (const file_header_t *file_header) FAST_FUNC
void header_list (const file_header_t *file_header) FAST_FUNC
void header_verbose_list (const file_header_t *file_header) FAST_FUNC
char get_header_ar (archive_handle_t *archive_handle) FAST_FUNC
char get_header_cpio (archive_handle_t *archive_handle) FAST_FUNC
char get_header_tar (archive_handle_t *archive_handle) FAST_FUNC
char get_header_tar_gz (archive_handle_t *archive_handle) FAST_FUNC
char get_header_tar_bz2 (archive_handle_t *archive_handle) FAST_FUNC
char get_header_tar_lzma (archive_handle_t *archive_handle) FAST_FUNC
char get_header_tar_xz (archive_handle_t *archive_handle) FAST_FUNC
void seek_by_jump (int fd, off_t amount) FAST_FUNC
void seek_by_read (int fd, off_t amount) FAST_FUNC
const char * strip_unsafe_prefix (const char *str) FAST_FUNC
void create_or_remember_link (llist_t **link_placeholders, const char *target, const char *linkname, int hard_link) FAST_FUNC
void create_links_from_list (llist_t *list) FAST_FUNC
void data_align (archive_handle_t *archive_handle, unsigned boundary) FAST_FUNC
const llist_t * find_list_entry (const llist_t *list, const char *filename) FAST_FUNC
const llist_t * find_list_entry2 (const llist_t *list, const char *filename) FAST_FUNC
char * unpack_bz2_data (const char *packed, int packed_len, int unpacked_len) FAST_FUNC
void init_transformer_state (transformer_state_t *xstate) FAST_FUNC
ssize_t transformer_write (transformer_state_t *xstate, const void *buf, size_t bufsize) FAST_FUNC
ssize_t xtransformer_write (transformer_state_t *xstate, const void *buf, size_t bufsize) FAST_FUNC
int check_signature16 (transformer_state_t *xstate, unsigned magic16) FAST_FUNC
IF_DESKTOP (long long) int inflate_unzip(transformer_state_t *xstate) FAST_FUNC
char * append_ext (char *filename, const char *expected_ext) FAST_FUNC
int bbunpack (char **argv, IF_DESKTOP(long long) int FAST_FUNC(*unpacker)(transformer_state_t *xstate), char *FAST_FUNC(*make_new_name)(char *filename, const char *expected_ext), const char *expected_ext) FAST_FUNC
void check_errors_in_children (int signo)
void fork_transformer (int fd, const char *transform_prog) FAST_FUNC
Variables
const char cpio_TRAILER []
Data Structure Documentation
file_header_t
struct file_header_t
Definition at line 31 of file bb_archive.h.
Data Fields
dev_t device
gid_t gid
char * link_target
mode_t mode
time_t mtime
char * name
off_t size
uid_t uid
tar_header_t
struct tar_header_t
Definition at line 144 of file bb_archive.h.
Data Fields
char chksum[8]
char devmajor[8]
char devminor[8]
char gid[8]
char gname[32]
char linkname[NAME_SIZE]
char magic[8]
char mode[8]
char mtime[12]
char name[NAME_SIZE]
char padding[12]
char prefix[155]
char size[12]
char typeflag
char uid[8]
char uname[32]
BUG_tar_header
struct BUG_tar_header
Definition at line 167 of file bb_archive.h.
Data Fields
char c[sizeof(tar_header_t)==TAR_BLOCK_SIZE ? 1 :-1]
transformer_state_t.magic
union transformer_state_t.magic
Definition at line 239 of file bb_archive.h.
Data Fields
uint8_t b[8]
uint16_t b16[4]
uint32_t b32[2]
Macro Definition Documentation
ARCHIVE_CREATE_LEADING_DIRS
#define ARCHIVE_CREATE_LEADING_DIRS (1 << 1)
Definition at line 127 of file bb_archive.h.
ARCHIVE_DONT_RESTORE_OWNER
#define ARCHIVE_DONT_RESTORE_OWNER (1 << 4)
Definition at line 130 of file bb_archive.h.
ARCHIVE_DONT_RESTORE_PERM
#define ARCHIVE_DONT_RESTORE_PERM (1 << 5)
Definition at line 131 of file bb_archive.h.
ARCHIVE_EXTRACT_NEWER
#define ARCHIVE_EXTRACT_NEWER (1 << 3)
Definition at line 129 of file bb_archive.h.
ARCHIVE_NUMERIC_OWNER
#define ARCHIVE_NUMERIC_OWNER (1 << 6)
Definition at line 132 of file bb_archive.h.
ARCHIVE_O_TRUNC
#define ARCHIVE_O_TRUNC (1 << 7)
Definition at line 133 of file bb_archive.h.
ARCHIVE_REMEMBER_NAMES
#define ARCHIVE_REMEMBER_NAMES (1 << 8)
Definition at line 134 of file bb_archive.h.
ARCHIVE_RESTORE_DATE
#define ARCHIVE_RESTORE_DATE (1 << 0)
Definition at line 126 of file bb_archive.h.
ARCHIVE_UNLINK_OLD
#define ARCHIVE_UNLINK_OLD (1 << 2)
Definition at line 128 of file bb_archive.h.
BBUNPK_OPTSTR
#define BBUNPK_OPTSTR "cfkvq"
Definition at line 264 of file bb_archive.h.
BBUNPK_OPTSTRLEN
#define BBUNPK_OPTSTRLEN 5
Definition at line 265 of file bb_archive.h.
BBUNPK_OPTSTRMASK
#define BBUNPK_OPTSTRMASK ((1 << BBUNPK_OPTSTRLEN) - 1)
Definition at line 266 of file bb_archive.h.
fork_transformer_with_sig
#define fork_transformer_with_sig (fd, transformer, transform_prog) fork_transformer((fd), (transform_prog))
Definition at line 290 of file bb_archive.h.
NAME_SIZE
#define NAME_SIZE 100
Definition at line 142 of file bb_archive.h.
NAME_SIZE_STR
#define NAME_SIZE_STR "100"
Definition at line 143 of file bb_archive.h.
PAX_GLOBAL
#define PAX_GLOBAL 1
Definition at line 87 of file bb_archive.h.
PAX_NEXT_FILE
#define PAX_NEXT_FILE 0
Definition at line 86 of file bb_archive.h.
TAR_BLOCK_SIZE
#define TAR_BLOCK_SIZE 512
Definition at line 141 of file bb_archive.h.
Typedef Documentation
archive_handle_t
typedef struct archive_handle_t archive_handle_t
file_header_t
typedef struct file_header_t file_header_t
tar_header_t
typedef struct tar_header_t tar_header_t
transformer_state_t
typedef struct transformer_state_t transformer_state_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COMPRESS_MAGIC
GZIP_MAGIC
BZIP2_MAGIC
XZ_MAGIC1
XZ_MAGIC2
XZ_MAGIC1a
XZ_MAGIC2a
Definition at line 7 of file bb_archive.h.
      {
 #if BB_BIG_ENDIAN
     COMPRESS_MAGIC = 0x1f9d,
     GZIP_MAGIC  = 0x1f8b,
     BZIP2_MAGIC = 256 * 'B' + 'Z',
     /* .xz signature: 0xfd, '7', 'z', 'X', 'Z', 0x00 */
     /* More info at: http://tukaani.org/xz/xz-file-format.txt */
     XZ_MAGIC1   = 256 * 0xfd + '7',
     XZ_MAGIC2   = 256 * (unsigned)(256 * (256 * 'z' + 'X') + 'Z') + 0,
     /* Different form: 32 bits, then 16 bits: */
     /* (unsigned) cast suppresses "integer overflow in expression" warning */
     XZ_MAGIC1a  = 256 * (unsigned)(256 * (256 * 0xfd + '7') + 'z') + 'X',
     XZ_MAGIC2a  = 256 * 'Z' + 0,
 #else
     COMPRESS_MAGIC = 0x9d1f,
     GZIP_MAGIC  = 0x8b1f,
     BZIP2_MAGIC = 'B' + 'Z' * 256,
     XZ_MAGIC1   = 0xfd + '7' * 256,
     XZ_MAGIC2   = 'z' + ('X' + ('Z' + 0 * 256) * 256) * 256,
     XZ_MAGIC1a  = 0xfd + ('7' + ('z' + 'X' * 256) * 256) * 256,
     XZ_MAGIC2a  = 'Z' + 0 * 256,
 #endif
 };
anonymous enum
anonymous enum
Enumerator
BBUNPK_OPT_STDOUT
BBUNPK_OPT_FORCE
BBUNPK_OPT_KEEP
BBUNPK_OPT_VERBOSE
BBUNPK_OPT_QUIET
BBUNPK_OPT_DECOMPRESS
BBUNPK_OPT_TEST
BBUNPK_SEAMLESS_MAGIC
Definition at line 267 of file bb_archive.h.
      {
     BBUNPK_OPT_STDOUT     = 1 << 0,
     BBUNPK_OPT_FORCE      = 1 << 1,
     /* only some decompressors: */
     BBUNPK_OPT_KEEP       = 1 << 2,
     BBUNPK_OPT_VERBOSE    = 1 << 3,
     BBUNPK_OPT_QUIET      = 1 << 4,
     /* not included in BBUNPK_OPTSTR: */
     BBUNPK_OPT_DECOMPRESS = 1 << 5,
     BBUNPK_OPT_TEST       = 1 << 6,
     BBUNPK_SEAMLESS_MAGIC = (1 << 31) * ENABLE_ZCAT * SEAMLESS_COMPRESSION,
 };
Function Documentation
append_ext()
char* append_ext (char * filename, const char * expected_ext)
Definition at line 35 of file bbunzip.c.
 {
     return xasprintf("%s.%s", filename, expected_ext);
 }
References filename, and xasprintf().
Referenced by bzip2_main(), and gzip_main().
bbunpack()
int bbunpack (char ** argv, IF_DESKTOP(long long) int FAST_FUNC(*)(transformer_state_t *xstate) unpacker, char *FAST_FUNC(*)(char *filename, const char *expected_ext) make_new_name, const char * expected_ext)
Definition at line 40 of file bbunzip.c.
 {
     struct stat stat_buf;
     IF_DESKTOP(long long) int status = 0;
     char *filename, *new_name;
     smallint exitcode = 0;
     transformer_state_t xstate;
     do {
         /* NB: new_name is *maybe* malloc'ed! */
         new_name = NULL;
         filename = *argv; /* can be NULL - 'streaming' bunzip2 */
         if (filename && LONE_DASH(filename))
             filename = NULL;
         /* Open src */
         if (filename) {
             if (!(option_mask32 & BBUNPK_SEAMLESS_MAGIC)) {
                 if (stat(filename, &stat_buf) != 0) {
  err_name:
                     bb_simple_perror_msg(filename);
  err:
                     exitcode = 1;
                     goto free_name;
                 }
                 if (open_to_or_warn(STDIN_FILENO, filename, O_RDONLY, 0))
                     goto err;
             } else {
                 /* "clever zcat" with FILE */
                 /* fail_if_not_compressed because zcat refuses uncompressed input */
                 int fd = open_zipped(filename, /*fail_if_not_compressed:*/ 1);
                 if (fd < 0)
                     goto err_name;
                 xmove_fd(fd, STDIN_FILENO);
             }
         } else
         if (option_mask32 & BBUNPK_SEAMLESS_MAGIC) {
             /* "clever zcat" on stdin */
             if (setup_unzip_on_fd(STDIN_FILENO, /*fail_if_not_compressed*/ 1))
                 goto err;
         }
         /* Special cases: test, stdout */
         if (option_mask32 & (BBUNPK_OPT_STDOUT|BBUNPK_OPT_TEST)) {
             if (option_mask32 & BBUNPK_OPT_TEST)
                 if (open_to_or_warn(STDOUT_FILENO, bb_dev_null, O_WRONLY, 0))
                     xfunc_die();
             filename = NULL;
         }
         /* Open dst if we are going to unpack to file */
         if (filename) {
             new_name = make_new_name(filename, expected_ext);
             if (!new_name) {
                 bb_error_msg("%s: unknown suffix - ignored", filename);
                 goto err;
             }
             /* -f: overwrite existing output files */
             if (option_mask32 & BBUNPK_OPT_FORCE) {
                 unlink(new_name);
             }
             /* O_EXCL: "real" bunzip2 doesn't overwrite files */
             /* GNU gunzip does not bail out, but goes to next file */
             if (open_to_or_warn(STDOUT_FILENO, new_name, O_WRONLY | O_CREAT | O_EXCL,
                     stat_buf.st_mode))
                 goto err;
         }
         /* Check that the input is sane */
         if (!(option_mask32 & BBUNPK_OPT_FORCE) && isatty(STDIN_FILENO)) {
             bb_simple_error_msg_and_die("compressed data not read from terminal, "
                     "use -f to force it");
         }
         if (!(option_mask32 & BBUNPK_SEAMLESS_MAGIC)) {
             init_transformer_state(&xstate);
             /*xstate.signature_skipped = 0; - already is */
             /*xstate.src_fd = STDIN_FILENO; - already is */
             xstate.dst_fd = STDOUT_FILENO;
             status = unpacker(&xstate);
             if (status < 0)
                 exitcode = 1;
         } else {
             if (bb_copyfd_eof(STDIN_FILENO, STDOUT_FILENO) < 0)
                 /* Disk full, tty closed, etc. No point in continuing */
                 xfunc_die();
         }
         if (!(option_mask32 & BBUNPK_OPT_STDOUT))
             xclose(STDOUT_FILENO); /* with error check! */
         if (filename) {
             char *del = new_name;
             if (status >= 0) {
                 unsigned new_name_len;
                 /* TODO: restore other things? */
                 if (xstate.mtime != 0) {
                     struct timeval times[2];
                     times[1].tv_sec = times[0].tv_sec = xstate.mtime;
                     times[1].tv_usec = times[0].tv_usec = 0;
                     /* Note: we closed it first.
                      * On some systems calling utimes
                      * then closing resets the mtime
                      * back to current time. */
                     utimes(new_name, times); /* ignoring errors */
                 }
                 if (ENABLE_DESKTOP)
                     new_name_len = strlen(new_name);
                 /* Restore source filename (unless tgz -> tar case) */
                 if (new_name == filename) {
                     new_name_len = strlen(filename);
                     filename[new_name_len] = '.';
                 }
                 /* Extreme bloat for gunzip compat */
                 /* Some users do want this info... */
                 if (ENABLE_DESKTOP && (option_mask32 & BBUNPK_OPT_VERBOSE)) {
                     unsigned percent = status
                         ? ((uoff_t)stat_buf.st_size * 100u / (unsigned long long)status)
                         : 0;
                     fprintf(stderr, "%s: %u%% - replaced with %.*s\n",
                         filename,
                         100u - percent,
                         new_name_len, new_name
                     );
                 }
                 /* Delete _source_ file */
                 del = filename;
                 if (option_mask32 & BBUNPK_OPT_KEEP) /* ... unless -k */
                     del = NULL;
             }
             if (del)
                 xunlink(del);
  free_name:
             if (new_name != filename)
                 free(new_name);
         }
     } while (*argv && *++argv);
     if (option_mask32 & BBUNPK_OPT_STDOUT)
         xclose(STDOUT_FILENO); /* with error check! */
     return exitcode;
 }
References argv, bb_copyfd_eof(), bb_dev_null, bb_error_msg(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), BBUNPK_OPT_FORCE, BBUNPK_OPT_KEEP, BBUNPK_OPT_STDOUT, BBUNPK_OPT_TEST, BBUNPK_OPT_VERBOSE, BBUNPK_SEAMLESS_MAGIC, transformer_state_t::dst_fd, err(), exitcode, fd, filename, fprintf(), free, IF_DESKTOP(), init_transformer_state(), isatty(), LONE_DASH, transformer_state_t::mtime, NULL, O_CREAT, O_EXCL, O_RDONLY, O_WRONLY, open_to_or_warn(), open_zipped, option_mask32, percent, setup_unzip_on_fd, stat::st_mode, stat::st_size, stat(), status, stderr, STDIN_FILENO, STDOUT_FILENO, strlen(), times(), unlink(), utimes(), xclose(), xfunc_die(), xmove_fd(), and xunlink().
Referenced by bzip2_main(), gzip_main(), and lzop_main().
check_errors_in_children()
void check_errors_in_children (int signo)
Definition at line 67 of file open_transformer.c.
 {
     int status;
     if (!signo) {
         /* block waiting for any child */
         if (wait(&status) < 0)
 //FIXME: check EINTR?
             return; /* probably there are no children */
         goto check_status;
     }
     /* Wait for any child without blocking */
     for (;;) {
         if (wait_any_nohang(&status) < 0)
 //FIXME: check EINTR?
             /* wait failed?! I'm confused... */
             return;
  check_status:
         /*if (WIFEXITED(status) && WEXITSTATUS(status) == 0)*/
         /* On Linux, the above can be checked simply as: */
         if (status == 0)
             /* this child exited with 0 */
             continue;
         /* Cannot happen:
         if (!WIFSIGNALED(status) && !WIFEXITED(status)) ???;
          */
         bb_got_signal = 1;
     }
 }
References bb_got_signal, status, wait(), and wait_any_nohang().
Referenced by tar_main().
check_signature16()
int check_signature16 (transformer_state_t * xstate, unsigned magic16)
Definition at line 13 of file open_transformer.c.
 {
     if (!xstate->signature_skipped) {
         uint16_t magic2;
         if (full_read(xstate->src_fd, &magic2, 2) != 2 || magic2 != magic16) {
             bb_simple_error_msg("invalid magic");
             return -1;
         }
         xstate->signature_skipped = 2;
     }
     return 0;
 }
References bb_simple_error_msg(), full_read(), transformer_state_t::signature_skipped, and transformer_state_t::src_fd.
Referenced by IF_DESKTOP().
chksum_and_xwrite_tar_header()
void chksum_and_xwrite_tar_header (int fd, struct tar_header_t * hp)
Definition at line 12 of file chksum_and_xwrite_tar_header.c.
 {
     /* POSIX says that checksum is done on unsigned bytes
      * (Sun and HP-UX gets it wrong... more details in
      * GNU tar source) */
     const unsigned char *cp;
     unsigned int chksum, size;
     strcpy(hp->magic, "ustar  ");
     /* Calculate and store the checksum (the sum of all of the bytes of
      * the header).  The checksum field must be filled with blanks for the
      * calculation.  The checksum field is formatted differently from the
      * other fields: it has 6 digits, a NUL, then a space -- rather than
      * digits, followed by a NUL like the other fields... */
     memset(hp->chksum, ' ', sizeof(hp->chksum));
     cp = (const unsigned char *) hp;
     chksum = 0;
     size = sizeof(*hp);
     do { chksum += *cp++; } while (--size);
     sprintf(hp->chksum, "%06o", chksum);
     xwrite(fd, hp, sizeof(*hp));
 }
References tar_header_t::chksum, fd, tar_header_t::magic, memset, size, sprintf(), strcpy, and xwrite().
Referenced by writeheader().
create_links_from_list()
void create_links_from_list (llist_t * list)
Definition at line 27 of file unsafe_symlink_target.c.
 {
     while (list) {
         char *target;
         target = list->data + 1 + strlen(list->data + 1) + 1;
         if ((*list->data ? link : symlink) (target, list->data + 1)) {
             /* shared message */
             bb_error_msg_and_die("can't create %slink '%s' to '%s'",
                 *list->data ? "hard" : "sym",
                 list->data + 1, target
             );
         }
         list = list->link;
     }
 }
References bb_error_msg_and_die(), link(), list(), strlen(), symlink(), and target.
Referenced by get_header_ar(), tar_main(), and unzip_main().
create_or_remember_link()
void create_or_remember_link (llist_t ** link_placeholders, const char * target, const char * linkname, int hard_link)
Definition at line 8 of file unsafe_symlink_target.c.
 {
     if (hard_link || target[0] == '/' || strstr(target, "..")) {
         llist_add_to_end(link_placeholders,
             xasprintf("%c%s%c%s", hard_link, linkname, '\0', target)
         );
         return;
     }
     if (symlink(target, linkname) != 0) {
         /* shared message */
         bb_perror_msg_and_die("can't create %slink '%s' to '%s'",
             "sym", linkname, target
         );
     }
 }
References bb_perror_msg_and_die(), llist_add_to_end(), strstr(), symlink(), target, and xasprintf().
Referenced by data_extract_all().
data_align()
void data_align (archive_handle_t * archive_handle, unsigned boundary)
Definition at line 8 of file data_align.c.
 {
     unsigned skip_amount = (boundary - (archive_handle->offset % boundary)) % boundary;
     archive_handle->seek(archive_handle->src_fd, skip_amount);
     archive_handle->offset += skip_amount;
 }
References boundary, archive_handle_t::offset, archive_handle_t::seek, and archive_handle_t::src_fd.
Referenced by get_header_cpio(), and get_header_tar().
data_extract_all()
void data_extract_all (archive_handle_t * archive_handle)
Definition at line 8 of file data_extract_all.c.
 {
     file_header_t *file_header = archive_handle->file_header;
     int dst_fd;
     int res;
     char *hard_link;
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS
     char *dst_name;
 #else
 # define dst_name (file_header->name)
 #endif
 #if ENABLE_FEATURE_TAR_SELINUX
     char *sctx = archive_handle->tar__sctx[PAX_NEXT_FILE];
     if (!sctx)
         sctx = archive_handle->tar__sctx[PAX_GLOBAL];
     if (sctx) { /* setfscreatecon is 4 syscalls, avoid if possible */
         setfscreatecon(sctx);
         free(archive_handle->tar__sctx[PAX_NEXT_FILE]);
         archive_handle->tar__sctx[PAX_NEXT_FILE] = NULL;
     }
 #endif
     /* Hard links are encoded as regular files of size 0
      * with a nonempty link field */
     hard_link = NULL;
     if (S_ISREG(file_header->mode) && file_header->size == 0)
         hard_link = file_header->link_target;
 #if ENABLE_FEATURE_TAR_LONG_OPTIONS
     dst_name = file_header->name;
     if (archive_handle->tar__strip_components) {
         unsigned n = archive_handle->tar__strip_components;
         do {
             dst_name = strchr(dst_name, '/');
             if (!dst_name || dst_name[1] == '\0') {
                 data_skip(archive_handle);
                 goto ret;
             }
             dst_name++;
             /*
              * Link target is shortened only for hardlinks:
              * softlinks restored unchanged.
              */
             if (hard_link) {
 // GNU tar 1.26 does not check that we reached end of link name:
 // if "dir/hardlink" is hardlinked to "file",
 // tar xvf a.tar --strip-components=1 says:
 //  tar: hardlink: Cannot hard link to '': No such file or directory
 // and continues processing. We silently skip such entries.
                 hard_link = strchr(hard_link, '/');
                 if (!hard_link || hard_link[1] == '\0') {
                     data_skip(archive_handle);
                     goto ret;
                 }
                 hard_link++;
             }
         } while (--n != 0);
     }
 #endif
     if (archive_handle->ah_flags & ARCHIVE_CREATE_LEADING_DIRS) {
         char *slash = strrchr(dst_name, '/');
         if (slash) {
             *slash = '\0';
             bb_make_directory(dst_name, -1, FILEUTILS_RECUR);
             *slash = '/';
         }
     }
     if (archive_handle->ah_flags & ARCHIVE_UNLINK_OLD) {
         /* Remove the entry if it exists */
         if (!S_ISDIR(file_header->mode)) {
             if (hard_link) {
                 /* Ugly special case:
                  * tar cf t.tar hardlink1 hardlink2 hardlink1
                  * results in this tarball structure:
                  * hardlink1
                  * hardlink2 -> hardlink1
                  * hardlink1 -> hardlink1 <== !!!
                  */
                 if (strcmp(hard_link, dst_name) == 0)
                     goto ret;
             }
             /* Proceed with deleting */
             if (unlink(dst_name) == -1
              && errno != ENOENT
             ) {
                 bb_perror_msg_and_die("can't remove old file %s",
                         dst_name);
             }
         }
     }
     else if (archive_handle->ah_flags & ARCHIVE_EXTRACT_NEWER) {
         /* Remove the existing entry if its older than the extracted entry */
         struct stat existing_sb;
         if (lstat(dst_name, &existing_sb) == -1) {
             if (errno != ENOENT) {
                 bb_simple_perror_msg_and_die("can't stat old file");
             }
         }
         else if (existing_sb.st_mtime >= file_header->mtime) {
             if (!S_ISDIR(file_header->mode)) {
                 bb_error_msg("%s not created: newer or "
                     "same age file exists", dst_name);
             }
             data_skip(archive_handle);
             goto ret;
         }
         else if ((unlink(dst_name) == -1) && (errno != EISDIR)) {
             bb_perror_msg_and_die("can't remove old file %s",
                     dst_name);
         }
     }
     /* Handle hard links separately */
     if (hard_link) {
         create_or_remember_link(&archive_handle->link_placeholders,
                 hard_link,
                 dst_name,
                 1);
         /* Hardlinks have no separate mode/ownership, skip chown/chmod */
         goto ret;
     }
     /* Create the filesystem entry */
     switch (file_header->mode & S_IFMT) {
     case S_IFREG: {
         /* Regular file */
         char *dst_nameN;
         int flags = O_WRONLY | O_CREAT | O_EXCL;
         if (archive_handle->ah_flags & ARCHIVE_O_TRUNC)
             flags = O_WRONLY | O_CREAT | O_TRUNC;
         dst_nameN = dst_name;
 #ifdef ARCHIVE_REPLACE_VIA_RENAME
         if (archive_handle->ah_flags & ARCHIVE_REPLACE_VIA_RENAME)
             /* rpm-style temp file name */
             dst_nameN = xasprintf("%s;%x", dst_name, (int)getpid());
 #endif
         dst_fd = xopen3(dst_nameN,
             flags,
             file_header->mode
             );
         bb_copyfd_exact_size(archive_handle->src_fd, dst_fd, file_header->size);
         close(dst_fd);
 #ifdef ARCHIVE_REPLACE_VIA_RENAME
         if (archive_handle->ah_flags & ARCHIVE_REPLACE_VIA_RENAME) {
             xrename(dst_nameN, dst_name);
             free(dst_nameN);
         }
 #endif
         break;
     }
     case S_IFDIR:
 //TODO: this causes problems if tarball contains a r-xr-xr-x directory:
 // we create this directory, and then fail to create files inside it
 // (if tar xf isn't run as root).
 // GNU tar works around this by chmod-ing directories *after* all files are extracted.
         res = mkdir(dst_name, file_header->mode);
         if ((res != 0)
          && (errno != EISDIR) /* btw, Linux doesn't return this */
          && (errno != EEXIST)
         ) {
             bb_perror_msg("can't make dir %s", dst_name);
         }
         break;
     case S_IFLNK:
         /* Symlink */
 //TODO: what if file_header->link_target == NULL (say, corrupted tarball?)
         /* To avoid a directory traversal attack via symlinks,
          * do not restore symlinks with ".." components
          * or symlinks starting with "/", unless a magic
          * envvar is set.
          *
          * For example, consider a .tar created via:
          *  $ tar cvf bug.tar anything.txt
          *  $ ln -s /tmp symlink
          *  $ tar --append -f bug.tar symlink
          *  $ rm symlink
          *  $ mkdir symlink
          *  $ tar --append -f bug.tar symlink/evil.py
          *
          * This will result in an archive that contains:
          *  $ tar --list -f bug.tar
          *  anything.txt
          *  symlink [-> /tmp]
          *  symlink/evil.py
          *
          * Untarring bug.tar would otherwise place evil.py in '/tmp'.
          */
         create_or_remember_link(&archive_handle->link_placeholders,
                 file_header->link_target,
                 dst_name,
                 0);
         break;
     case S_IFSOCK:
     case S_IFBLK:
     case S_IFCHR:
     case S_IFIFO:
         res = mknod(dst_name, file_header->mode, file_header->device);
         if (res != 0) {
             bb_perror_msg("can't create node %s", dst_name);
         }
         break;
     default:
         bb_simple_error_msg_and_die("unrecognized file type");
     }
     if (!S_ISLNK(file_header->mode)) {
         if (!(archive_handle->ah_flags & ARCHIVE_DONT_RESTORE_OWNER)) {
             uid_t uid = file_header->uid;
             gid_t gid = file_header->gid;
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
             if (!(archive_handle->ah_flags & ARCHIVE_NUMERIC_OWNER)) {
                 if (file_header->tar__uname) {
 //TODO: cache last name/id pair?
                     struct passwd *pwd = getpwnam(file_header->tar__uname);
                     if (pwd) uid = pwd->pw_uid;
                 }
                 if (file_header->tar__gname) {
                     struct group *grp = getgrnam(file_header->tar__gname);
                     if (grp) gid = grp->gr_gid;
                 }
             }
 #endif
             /* GNU tar 1.15.1 uses chown, not lchown */
             chown(dst_name, uid, gid);
         }
         /* uclibc has no lchmod, glibc is even stranger -
          * it has lchmod which seems to do nothing!
          * so we use chmod... */
         if (!(archive_handle->ah_flags & ARCHIVE_DONT_RESTORE_PERM)) {
             chmod(dst_name, file_header->mode);
         }
         if (archive_handle->ah_flags & ARCHIVE_RESTORE_DATE) {
             struct timeval t[2];
             t[1].tv_sec = t[0].tv_sec = file_header->mtime;
             t[1].tv_usec = t[0].tv_usec = 0;
             utimes(dst_name, t);
         }
     }
  ret: ;
 #if ENABLE_FEATURE_TAR_SELINUX
     if (sctx) {
         /* reset the context after creating an entry */
         setfscreatecon(NULL);
     }
 #endif
 }
References archive_handle_t::ah_flags, ARCHIVE_CREATE_LEADING_DIRS, ARCHIVE_DONT_RESTORE_OWNER, ARCHIVE_DONT_RESTORE_PERM, ARCHIVE_EXTRACT_NEWER, ARCHIVE_NUMERIC_OWNER, ARCHIVE_O_TRUNC, ARCHIVE_RESTORE_DATE, ARCHIVE_UNLINK_OLD, bb_copyfd_exact_size(), bb_error_msg(), bb_make_directory(), bb_perror_msg(), bb_perror_msg_and_die(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), chmod(), chown(), close(), create_or_remember_link(), data_skip(), file_header_t::device, dst_name, EEXIST, EISDIR, ENOENT, errno, archive_handle_t::file_header, FILEUTILS_RECUR, flags, free, getgrnam, getpid(), getpwnam, file_header_t::gid, group::gr_gid, archive_handle_t::link_placeholders, file_header_t::link_target, lstat, mkdir(), mknod(), file_header_t::mode, file_header_t::mtime, n, file_header_t::name, NULL, O_CREAT, O_EXCL, O_TRUNC, O_WRONLY, PAX_GLOBAL, PAX_NEXT_FILE, passwd::pw_uid, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFMT, S_IFREG, S_IFSOCK, S_ISDIR, S_ISLNK, S_ISREG, file_header_t::size, archive_handle_t::src_fd, stat::st_mtime, strchr(), strcmp, strrchr(), t, file_header_t::uid, unlink(), utimes(), xasprintf(), xopen3(), and xrename().
Referenced by ar_main(), data_extract_all_prefix(), dpkg_deb_main(), and tar_main().
data_extract_to_command()
void data_extract_to_command (archive_handle_t * archive_handle)
Definition at line 61 of file data_extract_to_command.c.
 {
     file_header_t *file_header = archive_handle->file_header;
 #if 0 /* do we need this? ENABLE_FEATURE_TAR_SELINUX */
     char *sctx = archive_handle->tar__sctx[PAX_NEXT_FILE];
     if (!sctx)
         sctx = archive_handle->tar__sctx[PAX_GLOBAL];
     if (sctx) { /* setfscreatecon is 4 syscalls, avoid if possible */
         setfscreatecon(sctx);
         free(archive_handle->tar__sctx[PAX_NEXT_FILE]);
         archive_handle->tar__sctx[PAX_NEXT_FILE] = NULL;
     }
 #endif
     if ((file_header->mode & S_IFMT) == S_IFREG) {
         pid_t pid;
         int p[2], status;
         char *tar_env[TAR_MAX];
         memset(tar_env, 0, sizeof(tar_env));
         xpipe(p);
         pid = BB_MMU ? xfork() : xvfork();
         if (pid == 0) {
             /* Child */
             /* str2env(tar_env, TAR_FILETYPE, "f"); - parent should do it once */
             oct2env(tar_env, TAR_MODE, file_header->mode);
             str2env(tar_env, TAR_FILENAME, file_header->name);
             str2env(tar_env, TAR_REALNAME, file_header->name);
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
             str2env(tar_env, TAR_UNAME, file_header->tar__uname);
             str2env(tar_env, TAR_GNAME, file_header->tar__gname);
 #endif
             dec2env(tar_env, TAR_SIZE, file_header->size);
             dec2env(tar_env, TAR_UID, file_header->uid);
             dec2env(tar_env, TAR_GID, file_header->gid);
             close(p[1]);
             xdup2(p[0], STDIN_FILENO);
             signal(SIGPIPE, SIG_DFL);
             execl(archive_handle->tar__to_command_shell,
                 archive_handle->tar__to_command_shell,
                 "-c",
                 archive_handle->tar__to_command,
                 (char *)0);
             bb_perror_msg_and_die("can't execute '%s'", archive_handle->tar__to_command_shell);
         }
         close(p[0]);
         /* Our caller is expected to do signal(SIGPIPE, SIG_IGN)
          * so that we don't die if child don't read all the input: */
         bb_copyfd_exact_size(archive_handle->src_fd, p[1], -file_header->size);
         close(p[1]);
         status = wait_for_exitstatus(pid);
         if (WIFEXITED(status) && WEXITSTATUS(status))
             bb_error_msg_and_die("'%s' returned status %d",
                 archive_handle->tar__to_command, WEXITSTATUS(status));
         if (WIFSIGNALED(status))
             bb_error_msg_and_die("'%s' terminated by signal %d",
                 archive_handle->tar__to_command, WTERMSIG(status));
         if (!BB_MMU) {
             int i;
             for (i = 0; i < TAR_MAX; i++) {
                 if (tar_env[i])
                     bb_unsetenv_and_free(tar_env[i]);
             }
         }
     }
 #if 0 /* ENABLE_FEATURE_TAR_SELINUX */
     if (sctx)
         /* reset the context after creating an entry */
         setfscreatecon(NULL);
 #endif
 }
References bb_copyfd_exact_size(), bb_error_msg_and_die(), BB_MMU, bb_perror_msg_and_die(), bb_unsetenv_and_free(), close(), dec2env(), execl(), archive_handle_t::file_header, free, file_header_t::gid, i, memset, file_header_t::mode, file_header_t::name, NULL, oct2env(), p, PAX_GLOBAL, PAX_NEXT_FILE, pid, S_IFMT, S_IFREG, SIG_DFL, signal, SIGPIPE, file_header_t::size, archive_handle_t::src_fd, status, STDIN_FILENO, str2env(), TAR_FILENAME, TAR_GID, TAR_MAX, TAR_MODE, TAR_REALNAME, TAR_SIZE, TAR_UID, file_header_t::uid, wait_for_exitstatus(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, WTERMSIG, xdup2(), xfork(), xpipe(), and xvfork.
Referenced by tar_main().
data_extract_to_stdout()
void data_extract_to_stdout (archive_handle_t * archive_handle)
Definition at line 8 of file data_extract_to_stdout.c.
 {
     bb_copyfd_exact_size(archive_handle->src_fd,
             STDOUT_FILENO,
             archive_handle->file_header->size);
 }
References bb_copyfd_exact_size(), archive_handle_t::file_header, file_header_t::size, archive_handle_t::src_fd, and STDOUT_FILENO.
Referenced by ar_main(), dpkg_deb_main(), and tar_main().
data_skip()
void data_skip (archive_handle_t * archive_handle)
Definition at line 8 of file data_skip.c.
 {
     archive_handle->seek(archive_handle->src_fd, archive_handle->file_header->size);
 }
References archive_handle_t::file_header, archive_handle_t::seek, file_header_t::size, and archive_handle_t::src_fd.
Referenced by data_extract_all(), get_header_ar(), get_header_cpio(), get_header_tar(), and init_handle().
filter_accept_all()
char filter_accept_all (archive_handle_t * archive_handle)
Definition at line 11 of file filter_accept_all.c.
 {
     if (archive_handle->file_header->name)
         return EXIT_SUCCESS;
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, and file_header_t::name.
Referenced by init_handle().
filter_accept_list()
char filter_accept_list (archive_handle_t * archive_handle)
Definition at line 13 of file filter_accept_list.c.
 {
     if (find_list_entry(archive_handle->accept, archive_handle->file_header->name))
         return EXIT_SUCCESS;
     return EXIT_FAILURE;
 }
References archive_handle_t::accept, EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, find_list_entry(), and file_header_t::name.
Referenced by ar_main(), deb_extract_control_file_to_buffer(), dpkg_deb_main(), and unpack_package().
filter_accept_list_reassign()
char filter_accept_list_reassign (archive_handle_t * archive_handle)
Definition at line 17 of file filter_accept_list_reassign.c.
 {
     /* Check the file entry is in the accept list */
     if (find_list_entry(archive_handle->accept, archive_handle->file_header->name)) {
         const char *name_ptr;
         /* Find extension */
         name_ptr = strrchr(archive_handle->file_header->name, '.');
         if (!name_ptr)
             return EXIT_FAILURE;
         name_ptr++;
         /* Modify the subarchive handler based on the extension */
         if (strcmp(name_ptr, "tar") == 0) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_GZ
          && strcmp(name_ptr, "gz") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_gz;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_BZ2
          && strcmp(name_ptr, "bz2") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_bz2;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_LZMA
          && strcmp(name_ptr, "lzma") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_lzma;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_XZ
          && strcmp(name_ptr, "xz") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_xz;
             return EXIT_SUCCESS;
         }
     }
     return EXIT_FAILURE;
 }
References archive_handle_t::accept, EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, find_list_entry(), get_header_tar(), get_header_tar_bz2(), get_header_tar_gz(), get_header_tar_lzma(), get_header_tar_xz(), file_header_t::name, strcmp, and strrchr().
Referenced by dpkg_deb_main(), and init_archive_deb_ar().
filter_accept_reject_list()
char filter_accept_reject_list (archive_handle_t * archive_handle)
Definition at line 13 of file filter_accept_reject_list.c.
 {
     const char *key;
     const llist_t *reject_entry;
     const llist_t *accept_entry;
     key = archive_handle->file_header->name;
     /* If the key is in a reject list fail */
     reject_entry = find_list_entry2(archive_handle->reject, key);
     if (reject_entry) {
         return EXIT_FAILURE;
     }
     /* Fail if an accept list was specified and the key wasnt in there */
     if (archive_handle->accept) {
         accept_entry = find_list_entry2(archive_handle->accept, key);
         if (!accept_entry) {
             return EXIT_FAILURE;
         }
     }
     /* Accepted */
     return EXIT_SUCCESS;
 }
References archive_handle_t::accept, EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, find_list_entry2(), file_header_t::name, and archive_handle_t::reject.
Referenced by tar_main().
find_list_entry()
const llist_t* find_list_entry (const llist_t * list, const char * filename)
Definition at line 12 of file find_list_entry.c.
 {
     while (list) {
         if (fnmatch(list->data, filename, 0) == 0) {
             return list;
         }
         list = list->link;
     }
     return NULL;
 }
References filename, fnmatch(), list(), and NULL.
Referenced by filter_accept_list(), filter_accept_list_reassign(), filter_rename_config(), tar_main(), and unzip_main().
find_list_entry2()
const llist_t* find_list_entry2 (const llist_t * list, const char * filename)
Definition at line 26 of file find_list_entry.c.
 {
     char buf[PATH_MAX];
     int pattern_slash_cnt;
     const char *c;
     char *d;
     while (list) {
         c = list->data;
         pattern_slash_cnt = 0;
         while (*c)
             if (*c++ == '/') pattern_slash_cnt++;
         c = filename;
         d = buf;
         /* paranoia is better than buffer overflows */
         while (*c && d != buf + sizeof(buf)-1) {
             if (*c == '/' && --pattern_slash_cnt < 0)
                 break;
             *d++ = *c++;
         }
         *d = '\0';
         if (fnmatch(list->data, buf, 0) == 0) {
             return list;
         }
         list = list->link;
     }
     return NULL;
 }
References buf, c, filename, fnmatch(), list(), NULL, and PATH_MAX.
Referenced by filter_accept_reject_list().
fork_transformer()
void fork_transformer (int fd, const char * transform_prog)
Definition at line 105 of file open_transformer.c.
 {
     struct fd_pair fd_pipe;
     int pid;
     xpiped_pair(fd_pipe);
     pid = BB_MMU ? xfork() : xvfork();
     if (pid == 0) {
         /* Child */
         close(fd_pipe.rd); /* we don't want to read from the parent */
         // FIXME: error check?
 #if BB_MMU
         {
             IF_DESKTOP(long long) int r;
             transformer_state_t xstate;
             init_transformer_state(&xstate);
             xstate.signature_skipped = signature_skipped;
             xstate.src_fd = fd;
             xstate.dst_fd = fd_pipe.wr;
             r = transformer(&xstate);
             if (ENABLE_FEATURE_CLEAN_UP) {
                 close(fd_pipe.wr); /* send EOF */
                 close(fd);
             }
             /* must be _exit! bug was actually seen here */
             _exit(/*error if:*/ r < 0);
         }
 #else
         {
             char *argv[4];
             xmove_fd(fd, 0);
             xmove_fd(fd_pipe.wr, 1);
             argv[0] = (char*)transform_prog;
             argv[1] = (char*)"-cf";
             argv[2] = (char*)"-";
             argv[3] = NULL;
             BB_EXECVP(transform_prog, argv);
             bb_perror_msg_and_die("can't execute '%s'", transform_prog);
         }
 #endif
         /* notreached */
     }
     /* parent process */
     close(fd_pipe.wr); /* don't want to write to the child */
     xmove_fd(fd_pipe.rd, fd);
 }
References _exit(), argv, BB_EXECVP, BB_MMU, bb_perror_msg_and_die(), close(), transformer_state_t::dst_fd, fd, IF_DESKTOP(), init_transformer_state(), NULL, pid, fd_pair::rd, transformer_state_t::signature_skipped, transformer_state_t::src_fd, fd_pair::wr, xfork(), xmove_fd(), xpiped_pair, and xvfork.
get_header_ar()
char get_header_ar (archive_handle_t * archive_handle)
Definition at line 29 of file get_header_ar.c.
 {
     file_header_t *typed = archive_handle->file_header;
     unsigned size;
     union {
         char raw[60];
         struct ar_header formatted;
     } ar;
     /* dont use xread as we want to handle the error ourself */
     if (read(archive_handle->src_fd, ar.raw, 60) != 60) {
         /* End Of File */
         return EXIT_FAILURE;
     }
     /* ar header starts on an even byte (2 byte aligned)
      * '\n' is used for padding
      */
     if (ar.raw[0] == '\n') {
         /* fix up the header, we started reading 1 byte too early */
         memmove(ar.raw, &ar.raw[1], 59);
         ar.raw[59] = xread_char(archive_handle->src_fd);
         archive_handle->offset++;
     }
     archive_handle->offset += 60;
     if (ar.formatted.magic[0] != '`' || ar.formatted.magic[1] != '\n')
         bb_simple_error_msg_and_die("invalid ar header");
     /*
      * Note that the fields MUST be read in reverse order as
      * read_num() clobbers the next byte after the field!
      * Order is: name, date, uid, gid, mode, size, magic.
      */
     typed->size = size = read_num(ar.formatted.size, 10,
                       sizeof(ar.formatted.size));
     /* special filenames have '/' as the first character */
     if (ar.formatted.name[0] == '/') {
         if (ar.formatted.name[1] == ' ') {
             /* This is the index of symbols in the file for compilers */
             data_skip(archive_handle);
             archive_handle->offset += size;
             return get_header_ar(archive_handle); /* Return next header */
         }
 #if ENABLE_FEATURE_AR_LONG_FILENAMES
         if (ar.formatted.name[1] == '/') {
             /* If the second char is a '/' then this entries data section
              * stores long filename for multiple entries, they are stored
              * in static variable long_names for use in future entries
              */
             archive_handle->ar__long_name_size = size;
             free(archive_handle->ar__long_names);
             archive_handle->ar__long_names = xzalloc(size + 1);
             xread(archive_handle->src_fd, archive_handle->ar__long_names, size);
             archive_handle->offset += size;
             /* Return next header */
             return get_header_ar(archive_handle);
         }
 #else
         bb_simple_error_msg_and_die("long filenames not supported");
 #endif
     }
     /* Only size is always present, the rest may be missing in
      * long filename pseudo file. Thus we decode the rest
      * after dealing with long filename pseudo file.
      *
      * GNU binutils in deterministic mode hard codes mode to 0644 (NOT
      * 0100644). AR archives can only contain files, so force file
      * mode.
      */
     typed->mode = read_num(ar.formatted.mode, 8, sizeof(ar.formatted.mode)) | S_IFREG;
     typed->gid = read_num(ar.formatted.gid, 10, sizeof(ar.formatted.gid));
     typed->uid = read_num(ar.formatted.uid, 10, sizeof(ar.formatted.uid));
     typed->mtime = read_num(ar.formatted.date, 10, sizeof(ar.formatted.date));
 #if ENABLE_FEATURE_AR_LONG_FILENAMES
     if (ar.formatted.name[0] == '/') {
         unsigned long_offset;
         /* The number after the '/' indicates the offset in the ar data section
          * (saved in ar__long_names) that contains the real filename */
         long_offset = read_num(&ar.formatted.name[1], 10,
                        sizeof(ar.formatted.name) - 1);
         if (long_offset >= archive_handle->ar__long_name_size) {
             bb_simple_error_msg_and_die("can't resolve long filename");
         }
         typed->name = xstrdup(archive_handle->ar__long_names + long_offset);
     } else
 #endif
     {
         /* short filenames */
         typed->name = xstrndup(ar.formatted.name, 16);
     }
     typed->name[strcspn(typed->name, " /")] = '\0';
     if (archive_handle->filter(archive_handle) == EXIT_SUCCESS) {
         archive_handle->action_header(typed);
 #if ENABLE_DPKG || ENABLE_DPKG_DEB
         if (archive_handle->dpkg__sub_archive) {
             struct archive_handle_t *sa = archive_handle->dpkg__sub_archive;
             while (archive_handle->dpkg__action_data_subarchive(sa) == EXIT_SUCCESS)
                 continue;
             create_links_from_list(sa->link_placeholders);
         } else
 #endif
             archive_handle->action_data(archive_handle);
     } else {
         data_skip(archive_handle);
     }
     archive_handle->offset += typed->size;
     /* Set the file pointer to the correct spot, we may have been reading a compressed file */
     lseek(archive_handle->src_fd, archive_handle->offset, SEEK_SET);
     return EXIT_SUCCESS;
 }
References archive_handle_t::action_data, archive_handle_t::action_header, bb_simple_error_msg_and_die(), create_links_from_list(), data_skip(), EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, archive_handle_t::filter, free, file_header_t::gid, archive_handle_t::link_placeholders, lseek(), memmove, file_header_t::mode, file_header_t::mtime, file_header_t::name, archive_handle_t::offset, raw, read(), read_num(), S_IFREG, SEEK_SET, size, file_header_t::size, archive_handle_t::src_fd, strcspn(), file_header_t::uid, xread(), xread_char(), xstrdup(), xstrndup(), and xzalloc().
Referenced by unpack_ar_archive().
get_header_cpio()
char get_header_cpio (archive_handle_t * archive_handle)
Definition at line 20 of file get_header_cpio.c.
 {
     file_header_t *file_header = archive_handle->file_header;
     char cpio_header[111];
     int namesize;
     int major, minor, nlink, mode, inode;
     unsigned size, uid, gid, mtime;
     /* There can be padding before archive header */
     data_align(archive_handle, 4);
     size = full_read(archive_handle->src_fd, cpio_header, 110);
     if (size == 0) {
         goto create_hardlinks;
     }
     if (size != 110) {
         bb_simple_error_msg_and_die("short read");
     }
     archive_handle->offset += 110;
     if (!is_prefixed_with(&cpio_header[0], "07070")
      || (cpio_header[5] != '1' && cpio_header[5] != '2')
     ) {
         bb_simple_error_msg_and_die("unsupported cpio format, use newc or crc");
     }
     cpio_header[110] = '\0'; /* sscanf may call strlen which may break without this */
     if (sscanf(cpio_header + 6,
             "%8x" "%8x" "%8x" "%8x"
             "%8x" "%8x" "%8x" /*maj,min:*/ "%*16c"
             /*rmaj,rmin:*/"%8x" "%8x" "%8x" /*chksum: "%*8c"*/,
             &inode, &mode, &uid, &gid,
             &nlink, &mtime, &size,
             &major, &minor, &namesize) != 10)
         bb_simple_error_msg_and_die("damaged cpio file");
     file_header->mode = mode;
     /* "cpio -R USER:GRP" support: */
     if (archive_handle->cpio__owner.uid != (uid_t)-1L)
         uid = archive_handle->cpio__owner.uid;
     if (archive_handle->cpio__owner.gid != (gid_t)-1L)
         gid = archive_handle->cpio__owner.gid;
     file_header->uid = uid;
     file_header->gid = gid;
     file_header->mtime = mtime;
     file_header->size = size;
     namesize &= 0x1fff; /* paranoia: limit names to 8k chars */
     file_header->name = xzalloc(namesize + 1);
     /* Read in filename */
     xread(archive_handle->src_fd, file_header->name, namesize);
     if (file_header->name[0] == '/') {
         /* Testcase: echo /etc/hosts | cpio -pvd /tmp
          * Without this code, it tries to unpack /etc/hosts
          * into "/etc/hosts", not "etc/hosts".
          */
         char *p = file_header->name;
         do p++; while (*p == '/');
         overlapping_strcpy(file_header->name, p);
     }
     archive_handle->offset += namesize;
     /* Update offset amount and skip padding before file contents */
     data_align(archive_handle, 4);
     if (strcmp(file_header->name, cpio_TRAILER) == 0) {
         /* Always round up. ">> 9" divides by 512 */
         archive_handle->cpio__blocks = (uoff_t)(archive_handle->offset + 511) >> 9;
         goto create_hardlinks;
     }
     file_header->link_target = NULL;
     if (S_ISLNK(file_header->mode)) {
         file_header->size &= 0x1fff; /* paranoia: limit names to 8k chars */
         file_header->link_target = xzalloc(file_header->size + 1);
         xread(archive_handle->src_fd, file_header->link_target, file_header->size);
         archive_handle->offset += file_header->size;
         file_header->size = 0; /* Stop possible seeks in future */
     }
 // TODO: data_extract_all can't deal with hardlinks to non-files...
 // when fixed, change S_ISREG to !S_ISDIR here
     if (nlink > 1 && S_ISREG(file_header->mode)) {
         hardlinks_t *new = xmalloc(sizeof(*new) + namesize);
         new->inode = inode;
         new->mode  = mode ;
         new->mtime = mtime;
         new->uid   = uid  ;
         new->gid   = gid  ;
         strcpy(new->name, file_header->name);
         /* Put file on a linked list for later */
         if (size == 0) {
             new->next = archive_handle->cpio__hardlinks_to_create;
             archive_handle->cpio__hardlinks_to_create = new;
             return EXIT_SUCCESS; /* Skip this one */
             /* TODO: this breaks cpio -t (it does not show hardlinks) */
         }
         new->next = archive_handle->cpio__created_hardlinks;
         archive_handle->cpio__created_hardlinks = new;
     }
     file_header->device = makedev(major, minor);
     if (archive_handle->filter(archive_handle) == EXIT_SUCCESS) {
         archive_handle->action_data(archive_handle);
 //TODO: run "echo /etc/hosts | cpio -pv /tmp" twice. On 2nd run:
 //cpio: etc/hosts not created: newer or same age file exists
 //etc/hosts  <-- should NOT show it
 //2 blocks <-- should say "0 blocks"
         archive_handle->action_header(file_header);
     } else {
         data_skip(archive_handle);
     }
     archive_handle->offset += file_header->size;
     free(file_header->link_target);
     free(file_header->name);
     file_header->link_target = NULL;
     file_header->name = NULL;
     return EXIT_SUCCESS;
  create_hardlinks:
     free(file_header->link_target);
     free(file_header->name);
     while (archive_handle->cpio__hardlinks_to_create) {
         hardlinks_t *cur;
         hardlinks_t *make_me = archive_handle->cpio__hardlinks_to_create;
         archive_handle->cpio__hardlinks_to_create = make_me->next;
         memset(file_header, 0, sizeof(*file_header));
         file_header->mtime = make_me->mtime;
         file_header->name = make_me->name;
         file_header->mode = make_me->mode;
         file_header->uid = make_me->uid;
         file_header->gid = make_me->gid;
         /*file_header->size = 0;*/
         /*file_header->link_target = NULL;*/
         /* Try to find a file we are hardlinked to */
         cur = archive_handle->cpio__created_hardlinks;
         while (cur) {
             /* TODO: must match maj/min too! */
             if (cur->inode == make_me->inode) {
                 file_header->link_target = cur->name;
                  /* link_target != NULL, size = 0: "I am a hardlink" */
                 if (archive_handle->filter(archive_handle) == EXIT_SUCCESS)
                     archive_handle->action_data(archive_handle);
                 free(make_me);
                 goto next_link;
             }
             cur = cur->next;
         }
         /* Oops... no file with such inode was created... do it now
          * (happens when hardlinked files are empty (zero length)) */
         if (archive_handle->filter(archive_handle) == EXIT_SUCCESS)
             archive_handle->action_data(archive_handle);
         /* Move to the list of created hardlinked files */
         make_me->next = archive_handle->cpio__created_hardlinks;
         archive_handle->cpio__created_hardlinks = make_me;
  next_link: ;
     }
     while (archive_handle->cpio__created_hardlinks) {
         hardlinks_t *p = archive_handle->cpio__created_hardlinks;
         archive_handle->cpio__created_hardlinks = p->next;
         free(p);
     }
     return EXIT_FAILURE; /* "No more files to process" */
 }
References archive_handle_t::action_data, archive_handle_t::action_header, bb_simple_error_msg_and_die(), cpio_TRAILER, cur, data_align(), data_skip(), file_header_t::device, EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, archive_handle_t::filter, free, full_read(), hardlinks_t::gid, file_header_t::gid, hardlinks_t::inode, is_prefixed_with(), file_header_t::link_target, major, makedev, memset, minor, hardlinks_t::mode, file_header_t::mode, mtime, hardlinks_t::mtime, file_header_t::mtime, hardlinks_t::name, file_header_t::name, hardlinks_t::next, NULL, archive_handle_t::offset, overlapping_strcpy(), p, S_ISLNK, S_ISREG, size, file_header_t::size, archive_handle_t::src_fd, sscanf(), strcmp, strcpy, hardlinks_t::uid, file_header_t::uid, xmalloc, xread(), and xzalloc().
get_header_tar()
char get_header_tar (archive_handle_t * archive_handle)
Definition at line 158 of file get_header_tar.c.
 {
     file_header_t *file_header = archive_handle->file_header;
     struct tar_header_t tar;
     char *cp;
     int tar_typeflag; /* can be "char", "int" seems give smaller code */
     int i, sum_u, sum;
 #if ENABLE_FEATURE_TAR_OLDSUN_COMPATIBILITY
     int sum_s;
 #endif
     int parse_names;
     /* Our "private data" */
 #if ENABLE_FEATURE_TAR_GNU_EXTENSIONS
 # define p_longname (archive_handle->tar__longname)
 # define p_linkname (archive_handle->tar__linkname)
 #else
 # define p_longname 0
 # define p_linkname 0
 #endif
 #if ENABLE_FEATURE_TAR_GNU_EXTENSIONS || ENABLE_FEATURE_TAR_SELINUX
  again:
 #endif
     /* Align header */
     data_align(archive_handle, 512);
  again_after_align:
 #if ENABLE_DESKTOP || ENABLE_FEATURE_TAR_AUTODETECT
     /* to prevent misdetection of bz2 sig */
     *(aliased_uint32_t*)&tar = 0;
     i = full_read(archive_handle->src_fd, &tar, 512);
     /* If GNU tar sees EOF in above read, it says:
      * "tar: A lone zero block at N", where N = kilobyte
      * where EOF was met (not EOF block, actual EOF!),
      * and exits with EXIT_SUCCESS.
      * We will mimic exit(EXIT_SUCCESS), although we will not mimic
      * the message and we don't check whether we indeed
      * saw zero block directly before this. */
     if (i == 0) {
         /* GNU tar 1.29 will be silent if tar archive ends abruptly
          * (if there are no zero blocks at all, and last read returns zero,
          * not short read 0 < len < 512). Complain only if
          * the very first read fails. Grrr.
          */
         if (archive_handle->offset == 0)
             bb_simple_error_msg("short read");
         /* this merely signals end of archive, not exit(1): */
         return EXIT_FAILURE;
     }
     if (i != 512) {
         IF_FEATURE_TAR_AUTODETECT(goto autodetect;)
         bb_simple_error_msg_and_die("short read");
     }
 #else
     i = 512;
     xread(archive_handle->src_fd, &tar, i);
 #endif
     archive_handle->offset += i;
     /* If there is no filename its an empty header */
     if (tar.name[0] == 0 && tar.prefix[0] == 0
     /* Have seen a tar archive with pax 'x' header supplying UTF8 filename,
      * with actual file having all name fields NUL-filled. Check this: */
      && !p_longname
     ) {
         if (archive_handle->tar__end) {
             /* Second consecutive empty header - end of archive.
              * Read until the end to empty the pipe from gz or bz2
              */
             while (full_read(archive_handle->src_fd, &tar, 512) == 512)
                 continue;
             return EXIT_FAILURE; /* "end of archive" */
         }
         archive_handle->tar__end = 1;
         return EXIT_SUCCESS; /* "decoded one header" */
     }
     archive_handle->tar__end = 0;
     /* Check header has valid magic, "ustar" is for the proper tar,
      * five NULs are for the old tar format  */
     if (!is_prefixed_with(tar.magic, "ustar")
      && (!ENABLE_FEATURE_TAR_OLDGNU_COMPATIBILITY
          || memcmp(tar.magic, "\0\0\0\0", 5) != 0)
     ) {
 #if ENABLE_FEATURE_TAR_AUTODETECT
  autodetect:
         /* Two different causes for lseek() != 0:
          * unseekable fd (would like to support that too, but...),
          * or not first block (false positive, it's not .gz/.bz2!) */
         if (lseek(archive_handle->src_fd, -i, SEEK_CUR) != 0)
             goto err;
         if (setup_unzip_on_fd(archive_handle->src_fd, /*fail_if_not_compressed:*/ 0) != 0)
  err:
             bb_simple_error_msg_and_die("invalid tar magic");
         archive_handle->offset = 0;
         goto again_after_align;
 #endif
         bb_simple_error_msg_and_die("invalid tar magic");
     }
     /* Do checksum on headers.
      * POSIX says that checksum is done on unsigned bytes, but
      * Sun and HP-UX gets it wrong... more details in
      * GNU tar source. */
     sum_u = ' ' * sizeof(tar.chksum);
 #if ENABLE_FEATURE_TAR_OLDSUN_COMPATIBILITY
     sum_s = sum_u;
 #endif
     for (i = 0; i < 148; i++) {
         sum_u += ((unsigned char*)&tar)[i];
 #if ENABLE_FEATURE_TAR_OLDSUN_COMPATIBILITY
         sum_s += ((signed char*)&tar)[i];
 #endif
     }
     for (i = 156; i < 512; i++) {
         sum_u += ((unsigned char*)&tar)[i];
 #if ENABLE_FEATURE_TAR_OLDSUN_COMPATIBILITY
         sum_s += ((signed char*)&tar)[i];
 #endif
     }
     /* Most tarfiles have tar.chksum NUL or space terminated, but
      * github.com decided to be "special" and have unterminated field:
      * 0090: 30343300 30303031 33323731 30000000 |043.000132710...|
      *                                                ^^^^^^^^|
      * Need to use GET_OCTAL. This overwrites tar.typeflag ---+
      * (the '0' char immediately after chksum in example above) with NUL.
      */
     tar_typeflag = (uint8_t)tar.typeflag; /* save it */
     sum = GET_OCTAL(tar.chksum);
     if (sum_u != sum
         IF_FEATURE_TAR_OLDSUN_COMPATIBILITY(&& sum_s != sum)
     ) {
         bb_simple_error_msg_and_die("invalid tar header checksum");
     }
     /* GET_OCTAL trashes subsequent field, therefore we call it
      * on fields in reverse order */
     if (tar.devmajor[0]) {
         char t = tar.prefix[0];
         /* we trash prefix[0] here, but we DO need it later! */
         unsigned minor = GET_OCTAL(tar.devminor);
         unsigned major = GET_OCTAL(tar.devmajor);
         file_header->device = makedev(major, minor);
         tar.prefix[0] = t;
     }
     /* 0 is reserved for high perf file, treat as normal file */
     if (tar_typeflag == '\0') tar_typeflag = '0';
     parse_names = (tar_typeflag >= '0' && tar_typeflag <= '7');
     file_header->link_target = NULL;
     if (!p_linkname && parse_names && tar.linkname[0]) {
         file_header->link_target = xstrndup(tar.linkname, sizeof(tar.linkname));
         /* FIXME: what if we have non-link object with link_target? */
         /* Will link_target be free()ed? */
     }
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
     file_header->tar__uname = tar.uname[0] ? xstrndup(tar.uname, sizeof(tar.uname)) : NULL;
     file_header->tar__gname = tar.gname[0] ? xstrndup(tar.gname, sizeof(tar.gname)) : NULL;
 #endif
     file_header->mtime = GET_OCTAL(tar.mtime);
     file_header->size = GET_OCTAL(tar.size);
     file_header->gid = GET_OCTAL(tar.gid);
     file_header->uid = GET_OCTAL(tar.uid);
     /* Set bits 0-11 of the files mode */
     file_header->mode = 07777 & GET_OCTAL(tar.mode);
     file_header->name = NULL;
     if (!p_longname && parse_names) {
         /* we trash mode[0] here, it's ok */
         //tar.name[sizeof(tar.name)] = '\0'; - gcc 4.3.0 would complain
         tar.mode[0] = '\0';
         if (tar.prefix[0]) {
             /* and padding[0] */
             //tar.prefix[sizeof(tar.prefix)] = '\0'; - gcc 4.3.0 would complain
             tar.padding[0] = '\0';
             file_header->name = concat_path_file(tar.prefix, tar.name);
         } else
             file_header->name = xstrdup(tar.name);
     }
     switch (tar_typeflag) {
     case '1': /* hardlink */
         /* we mark hardlinks as regular files with zero size and a link name */
         file_header->mode |= S_IFREG;
         /* on size of link fields from star(4)
          * ... For tar archives written by pre POSIX.1-1988
          * implementations, the size field usually contains the size of
          * the file and needs to be ignored as no data may follow this
          * header type.  For POSIX.1-1988 compliant archives, the size
          * field needs to be 0.  For POSIX.1-2001 compliant archives,
          * the size field may be non zero, indicating that file data is
          * included in the archive.
          * i.e; always assume this is zero for safety.
          */
         goto size0;
     case '7':
     /* case 0: */
     case '0':
 #if ENABLE_FEATURE_TAR_OLDGNU_COMPATIBILITY
         if (file_header->name && last_char_is(file_header->name, '/')) {
             goto set_dir;
         }
 #endif
         file_header->mode |= S_IFREG;
         break;
     case '2':
         file_header->mode |= S_IFLNK;
         /* have seen tarballs with size field containing
          * the size of the link target's name */
  size0:
         file_header->size = 0;
         break;
     case '3':
         file_header->mode |= S_IFCHR;
         goto size0; /* paranoia */
     case '4':
         file_header->mode |= S_IFBLK;
         goto size0;
     case '5':
  IF_FEATURE_TAR_OLDGNU_COMPATIBILITY(set_dir:)
         file_header->mode |= S_IFDIR;
         goto size0;
     case '6':
         file_header->mode |= S_IFIFO;
         goto size0;
     case 'g':   /* pax global header */
     case 'x': { /* pax extended header */
         if ((uoff_t)file_header->size > 0xfffff) /* paranoia */
             goto skip_ext_hdr;
         process_pax_hdr(archive_handle, file_header->size, (tar_typeflag == 'g'));
         goto again_after_align;
 #if ENABLE_FEATURE_TAR_GNU_EXTENSIONS
 /* See http://www.gnu.org/software/tar/manual/html_node/Extensions.html */
     case 'L':
         /* free: paranoia: tar with several consecutive longnames */
         free(p_longname);
         /* For paranoia reasons we allocate extra NUL char */
         die_if_bad_fnamesize(file_header->size);
         p_longname = xzalloc(file_header->size + 1);
         /* We read ASCIZ string, including NUL */
         xread(archive_handle->src_fd, p_longname, file_header->size);
         archive_handle->offset += file_header->size;
         /* return get_header_tar(archive_handle); */
         /* gcc 4.1.1 didn't optimize it into jump */
         /* so we will do it ourself, this also saves stack */
         goto again;
     case 'K':
         free(p_linkname);
         die_if_bad_fnamesize(file_header->size);
         p_linkname = xzalloc(file_header->size + 1);
         xread(archive_handle->src_fd, p_linkname, file_header->size);
         archive_handle->offset += file_header->size;
         /* return get_header_tar(archive_handle); */
         goto again;
 /*
  *  case 'S':   // Sparse file
  * Was seen in the wild. Not supported (yet?).
  * See https://www.gnu.org/software/tar/manual/html_section/tar_92.html
  * for the format. (An "Old GNU Format" was seen, not PAX formats).
  */
 //  case 'D':   /* GNU dump dir */
 //  case 'M':   /* Continuation of multi volume archive */
 //  case 'N':   /* Old GNU for names > 100 characters */
     case 'V':   /* Volume header */
         ; /* Fall through to skip it */
 #endif
     }
  skip_ext_hdr:
     {
         off_t sz;
         bb_error_msg("warning: skipping header '%c'", tar_typeflag);
         sz = (file_header->size + 511) & ~(off_t)511;
         archive_handle->offset += sz;
         sz >>= 9; /* sz /= 512 but w/o contortions for signed div */
         while (sz--)
             xread(archive_handle->src_fd, &tar, 512);
         /* return get_header_tar(archive_handle); */
         goto again_after_align;
     }
     default:
         bb_error_msg_and_die("unknown typeflag: 0x%x", tar_typeflag);
     }
 #if ENABLE_FEATURE_TAR_GNU_EXTENSIONS
     if (p_longname) {
         file_header->name = p_longname;
         p_longname = NULL;
     }
     if (p_linkname) {
         file_header->link_target = p_linkname;
         p_linkname = NULL;
     }
 #endif
     /* Everything up to and including last ".." component is stripped */
     overlapping_strcpy(file_header->name, strip_unsafe_prefix(file_header->name));
 //TODO: do the same for file_header->link_target?
     /* Strip trailing '/' in directories */
     /* Must be done after mode is set as '/' is used to check if it's a directory */
     cp = last_char_is(file_header->name, '/');
     if (archive_handle->filter(archive_handle) == EXIT_SUCCESS) {
         archive_handle->action_header(/*archive_handle->*/ file_header);
         /* Note that we kill the '/' only after action_header() */
         /* (like GNU tar 1.15.1: verbose mode outputs "dir/dir/") */
         if (cp)
             *cp = '\0';
         archive_handle->action_data(archive_handle);
         if (archive_handle->accept || archive_handle->reject
          || (archive_handle->ah_flags & ARCHIVE_REMEMBER_NAMES)
         ) {
             llist_add_to(&archive_handle->passed, file_header->name);
         } else /* Caller isn't interested in list of unpacked files */
             free(file_header->name);
     } else {
         data_skip(archive_handle);
         free(file_header->name);
     }
     archive_handle->offset += file_header->size;
     free(file_header->link_target);
     /* Do not free(file_header->name)!
      * It might be inserted in archive_handle->passed - see above */
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
     free(file_header->tar__uname);
     free(file_header->tar__gname);
 #endif
     return EXIT_SUCCESS; /* "decoded one header" */
 }
References archive_handle_t::accept, archive_handle_t::action_data, archive_handle_t::action_header, archive_handle_t::ah_flags, ARCHIVE_REMEMBER_NAMES, bb_error_msg(), bb_error_msg_and_die(), bb_simple_error_msg(), bb_simple_error_msg_and_die(), tar_header_t::chksum, concat_path_file(), data_align(), data_skip(), file_header_t::device, tar_header_t::devmajor, tar_header_t::devminor, die_if_bad_fnamesize(), err(), EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, archive_handle_t::filter, free, full_read(), GET_OCTAL, file_header_t::gid, tar_header_t::gid, tar_header_t::gname, i, is_prefixed_with(), last_char_is(), file_header_t::link_target, tar_header_t::linkname, llist_add_to(), lseek(), tar_header_t::magic, major, makedev, memcmp(), minor, file_header_t::mode, tar_header_t::mode, file_header_t::mtime, tar_header_t::mtime, file_header_t::name, tar_header_t::name, NULL, off_t, archive_handle_t::offset, overlapping_strcpy(), p_linkname, p_longname, tar_header_t::padding, archive_handle_t::passed, tar_header_t::prefix, process_pax_hdr, archive_handle_t::reject, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFREG, SEEK_CUR, setup_unzip_on_fd, file_header_t::size, tar_header_t::size, archive_handle_t::src_fd, strip_unsafe_prefix(), t, tar_header_t::typeflag, file_header_t::uid, tar_header_t::uid, tar_header_t::uname, xread(), xstrdup(), xstrndup(), and xzalloc().
Referenced by filter_accept_list_reassign(), get_header_tar_bz2(), get_header_tar_gz(), get_header_tar_lzma(), get_header_tar_xz(), and tar_main().
get_header_tar_bz2()
char get_header_tar_bz2 (archive_handle_t * archive_handle)
Definition at line 8 of file get_header_tar_bz2.c.
 {
     /* Can't lseek over pipes */
     archive_handle->seek = seek_by_read;
     fork_transformer_with_sig(archive_handle->src_fd, unpack_bz2_stream, "bunzip2");
     archive_handle->offset = 0;
     while (get_header_tar(archive_handle) == EXIT_SUCCESS)
         continue;
     /* Can only do one file at a time */
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, fork_transformer_with_sig, get_header_tar(), archive_handle_t::offset, archive_handle_t::seek, seek_by_read(), and archive_handle_t::src_fd.
Referenced by filter_accept_list_reassign().
get_header_tar_gz()
char get_header_tar_gz (archive_handle_t * archive_handle)
Definition at line 8 of file get_header_tar_gz.c.
 {
     /* Can't lseek over pipes */
     archive_handle->seek = seek_by_read;
     fork_transformer_with_sig(archive_handle->src_fd, unpack_gz_stream, "gunzip");
     archive_handle->offset = 0;
     while (get_header_tar(archive_handle) == EXIT_SUCCESS)
         continue;
     /* Can only do one file at a time */
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, fork_transformer_with_sig, get_header_tar(), archive_handle_t::offset, archive_handle_t::seek, seek_by_read(), and archive_handle_t::src_fd.
Referenced by filter_accept_list_reassign().
get_header_tar_lzma()
char get_header_tar_lzma (archive_handle_t * archive_handle)
Definition at line 11 of file get_header_tar_lzma.c.
 {
     /* Can't lseek over pipes */
     archive_handle->seek = seek_by_read;
     fork_transformer_with_sig(archive_handle->src_fd, unpack_lzma_stream, "unlzma");
     archive_handle->offset = 0;
     while (get_header_tar(archive_handle) == EXIT_SUCCESS)
         continue;
     /* Can only do one file at a time */
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, fork_transformer_with_sig, get_header_tar(), archive_handle_t::offset, archive_handle_t::seek, seek_by_read(), and archive_handle_t::src_fd.
Referenced by filter_accept_list_reassign().
get_header_tar_xz()
char get_header_tar_xz (archive_handle_t * archive_handle)
Definition at line 8 of file get_header_tar_xz.c.
 {
     /* Can't lseek over pipes */
     archive_handle->seek = seek_by_read;
     fork_transformer_with_sig(archive_handle->src_fd, unpack_xz_stream, "unxz");
     archive_handle->offset = 0;
     while (get_header_tar(archive_handle) == EXIT_SUCCESS)
         continue;
     /* Can only do one file at a time */
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, fork_transformer_with_sig, get_header_tar(), archive_handle_t::offset, archive_handle_t::seek, seek_by_read(), and archive_handle_t::src_fd.
Referenced by filter_accept_list_reassign().
header_list()
void header_list (const file_header_t * file_header)
Definition at line 8 of file header_list.c.
 {
 //TODO: cpio -vp DIR should output "DIR/NAME", not just "NAME" */
     puts(file_header->name);
 }
References file_header_t::name, and puts().
Referenced by ar_main(), dpkg_deb_main(), and tar_main().
header_skip()
void header_skip (const file_header_t * file_header)
header_verbose_list()
void header_verbose_list (const file_header_t * file_header)
Definition at line 8 of file header_verbose_list.c.
 {
     struct tm tm_time;
     struct tm *ptm = &tm_time; //localtime(&file_header->mtime);
     char modestr[12];
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
     char uid[sizeof(int)*3 + 2];
     /*char gid[sizeof(int)*3 + 2];*/
     char *user;
     char *group;
     localtime_r(&file_header->mtime, ptm);
     user = file_header->tar__uname;
     if (user == NULL) {
         sprintf(uid, "%u", (unsigned)file_header->uid);
         user = uid;
     }
     group = file_header->tar__gname;
     if (group == NULL) {
         /*sprintf(gid, "%u", (unsigned)file_header->gid);*/
         group = utoa(file_header->gid);
     }
     printf("%s %s/%s %9"OFF_FMT"u %4u-%02u-%02u %02u:%02u:%02u %s",
         bb_mode_string(modestr, file_header->mode),
         user,
         group,
         file_header->size,
         1900 + ptm->tm_year,
         1 + ptm->tm_mon,
         ptm->tm_mday,
         ptm->tm_hour,
         ptm->tm_min,
         ptm->tm_sec,
         file_header->name);
 #else /* !FEATURE_TAR_UNAME_GNAME */
     localtime_r(&file_header->mtime, ptm);
     printf("%s %u/%u %9"OFF_FMT"u %4u-%02u-%02u %02u:%02u:%02u %s",
         bb_mode_string(modestr, file_header->mode),
         (unsigned)file_header->uid,
         (unsigned)file_header->gid,
         file_header->size,
         1900 + ptm->tm_year,
         1 + ptm->tm_mon,
         ptm->tm_mday,
         ptm->tm_hour,
         ptm->tm_min,
         ptm->tm_sec,
         file_header->name);
 #endif /* FEATURE_TAR_UNAME_GNAME */
     /* NB: GNU tar shows "->" for symlinks and "link to" for hardlinks */
     if (file_header->link_target) {
         printf(" -> %s", file_header->link_target);
     }
     bb_putchar('\n');
 }
References bb_mode_string(), bb_putchar(), file_header_t::gid, file_header_t::link_target, file_header_t::mode, file_header_t::mtime, file_header_t::name, NULL, OFF_FMT, printf, file_header_t::size, sprintf(), tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_year, file_header_t::uid, user, and utoa().
Referenced by dpkg_deb_main(), and tar_main().
IF_DESKTOP()
IF_DESKTOP (long long)
Definition at line 770 of file decompress_bunzip2.c.
 {
     IF_DESKTOP(long long total_written = 0;)
     bunzip_data *bd;
     char *outbuf;
     int i;
     unsigned len;
     if (check_signature16(xstate, BZIP2_MAGIC))
         return -1;
     outbuf = xmalloc(IOBUF_SIZE);
     len = 0;
     while (1) { /* "Process one BZ... stream" loop */
         jmp_buf jmpbuf;
         /* Setup for I/O error handling via longjmp */
         i = setjmp(jmpbuf);
         if (i == 0)
             i = start_bunzip(&jmpbuf, &bd, xstate->src_fd, outbuf + 2, len);
         if (i == 0) {
             while (1) { /* "Produce some output bytes" loop */
                 i = read_bunzip(bd, outbuf, IOBUF_SIZE);
                 if (i < 0) /* error? */
                     break;
                 i = IOBUF_SIZE - i; /* number of bytes produced */
                 if (i == 0) /* EOF? */
                     break;
                 if (i != transformer_write(xstate, outbuf, i)) {
                     i = RETVAL_SHORT_WRITE;
                     goto release_mem;
                 }
                 IF_DESKTOP(total_written += i;)
             }
         }
         if (i != RETVAL_LAST_BLOCK
         /* Observed case when i == RETVAL_OK:
          * "bzcat z.bz2", where "z.bz2" is a bzipped zero-length file
          * (to be exact, z.bz2 is exactly these 14 bytes:
          * 42 5a 68 39 17 72 45 38 50 90 00 00 00 00).
          */
          && i != RETVAL_OK
         ) {
             bb_error_msg("bunzip error %d", i);
             break;
         }
         if (bd->headerCRC != bd->totalCRC) {
             bb_simple_error_msg("CRC error");
             break;
         }
         /* Successfully unpacked one BZ stream */
         i = RETVAL_OK;
         /* Do we have "BZ..." after last processed byte?
          * pbzip2 (parallelized bzip2) produces such files.
          */
         len = bd->inbufCount - bd->inbufPos;
         memcpy(outbuf, &bd->inbuf[bd->inbufPos], len);
         if (len < 2) {
             if (safe_read(xstate->src_fd, outbuf + len, 2 - len) != 2 - len)
                 break;
             len = 2;
         }
         if (*(uint16_t*)outbuf != BZIP2_MAGIC) /* "BZ"? */
             break;
         dealloc_bunzip(bd);
         len -= 2;
     }
  release_mem:
     dealloc_bunzip(bd);
     free(outbuf);
     return i ? i : IF_DESKTOP(total_written) + 0;
 }
References bb_error_msg(), bb_msg_read_error, bb_simple_error_msg(), bb_simple_error_msg_and_die(), bd, BIT_MASK, BITS, BITS_STR, BLOCK_MODE, buffer, BUFSIZ, BZIP2_MAGIC, check_signature16(), CLEAR, clear_tab_prefixof, code, COMPRESS_MAGIC, dbg, de_stack, dealloc_bunzip(), end, err(), FIRST, free, full_read(), global_crc32_new_table_le(), global_crc32_table, HEADER_MAGIC, HEADER_MAGIC_SIZE, HSIZE, htab, htabof, i, IBUFSIZ, inbuf, INIT_BITS, iobuf, IOBUF_SIZE, len, LZMA_ALIGN, LZMA_BASE_SIZE, LZMA_END_POS_MODEL_INDEX, LZMA_IS_MATCH, LZMA_IS_REP, LZMA_IS_REP_0_LONG, LZMA_IS_REP_G0, LZMA_IS_REP_G1, LZMA_IS_REP_G2, LZMA_LEN_CHOICE, LZMA_LEN_CHOICE_2, LZMA_LEN_CODER, LZMA_LEN_HIGH, LZMA_LEN_LOW, LZMA_LEN_MID, LZMA_LEN_NUM_HIGH_BITS, LZMA_LEN_NUM_LOW_BITS, LZMA_LEN_NUM_MID_BITS, LZMA_LIT_SIZE, LZMA_LITERAL, LZMA_MATCH_MIN_LEN, LZMA_NUM_ALIGN_BITS, LZMA_NUM_LEN_TO_POS_STATES, LZMA_NUM_LIT_STATES, LZMA_NUM_POS_BITS_MAX, LZMA_NUM_POS_SLOT_BITS, LZMA_NUM_STATES, LZMA_POS_SLOT, LZMA_REP_LEN_CODER, LZMA_SPEC_POS, LZMA_START_POS_MODEL_INDEX, MAXCODE, memcpy, memset, MIN, OBUFSIZ, offset, outbuf, p, pos, prob_len, rc, rc_bit_tree_decode(), rc_direct_bit(), rc_free(), rc_get_bit(), rc_init(), rc_is_bit_1(), RC_MODEL_TOTAL_BITS, rd, read_bunzip(), retval, RETVAL_LAST_BLOCK, RETVAL_OK, RETVAL_SHORT_WRITE, safe_read(), setjmp, transformer_state_t::signature_skipped, transformer_state_t::src_fd, start_bunzip(), state, strcpy, string, SWAP_LE32, SWAP_LE64, tab_prefixof, tab_suffixof, total, transformer_write(), X_OK, xmalloc, xtransformer_write(), xz_dec_end(), xz_dec_init(), xz_dec_reset(), xz_dec_run(), XZ_DYNALLOC, XZ_OK, XZ_STREAM_END, XZ_UNSUPPORTED_CHECK, and xzalloc().
init_handle()
archive_handle_t* init_handle (void)
Definition at line 8 of file init_handle.c.
 {
     archive_handle_t *archive_handle;
     /* Initialize default values */
     archive_handle = xzalloc(sizeof(archive_handle_t));
     archive_handle->file_header = xzalloc(sizeof(file_header_t));
     archive_handle->action_header = header_skip;
     archive_handle->action_data = data_skip;
     archive_handle->filter = filter_accept_all;
     archive_handle->seek = seek_by_jump;
 #if ENABLE_CPIO || ENABLE_RPM2CPIO || ENABLE_RPM
     archive_handle->cpio__owner.uid = (uid_t)-1L;
     archive_handle->cpio__owner.gid = (gid_t)-1L;
 #endif
     return archive_handle;
 }
References archive_handle_t::action_data, archive_handle_t::action_header, data_skip(), archive_handle_t::file_header, archive_handle_t::filter, filter_accept_all(), header_skip(), archive_handle_t::seek, seek_by_jump(), and xzalloc().
Referenced by ar_main(), dpkg_deb_main(), init_archive_deb_ar(), init_archive_deb_control(), init_archive_deb_data(), and tar_main().
init_transformer_state()
void init_transformer_state (transformer_state_t * xstate)
Definition at line 8 of file open_transformer.c.
 {
     memset(xstate, 0, sizeof(*xstate));
 }
References memset.
Referenced by bbunpack(), fork_transformer(), and unzip_extract().
seek_by_jump()
void seek_by_jump (int fd, off_t amount)
Definition at line 8 of file seek_by_jump.c.
 {
     if (amount
      && lseek(fd, amount, SEEK_CUR) == (off_t) -1
     ) {
         if (errno == ESPIPE)
             seek_by_read(fd, amount);
         else
             bb_simple_perror_msg_and_die("seek failure");
     }
 }
References bb_simple_perror_msg_and_die(), errno, ESPIPE, fd, lseek(), off_t, seek_by_read(), and SEEK_CUR.
Referenced by init_handle().
seek_by_read()
void seek_by_read (int fd, off_t amount)
Definition at line 11 of file seek_by_read.c.
 {
     if (amount)
         bb_copyfd_exact_size(fd, -1, amount);
 }
References bb_copyfd_exact_size(), and fd.
Referenced by get_header_tar_bz2(), get_header_tar_gz(), get_header_tar_lzma(), get_header_tar_xz(), process_pax_hdr(), seek_by_jump(), and tar_main().
strip_unsafe_prefix()
const char* strip_unsafe_prefix (const char * str)
Definition at line 8 of file unsafe_prefix.c.
 {
     const char *cp = str;
     while (1) {
         char *cp2;
         if (*cp == '/') {
             cp++;
             continue;
         }
         if (is_prefixed_with(cp, "/../"+1)) {
             cp += 3;
             continue;
         }
         cp2 = strstr(cp, "/../");
         if (!cp2)
             break;
         cp = cp2 + 4;
     }
     if (cp != str) {
         static smallint warned = 0;
         if (!warned) {
             warned = 1;
             bb_error_msg("removing leading '%.*s' from member names",
                 (int)(cp - str), str);
         }
     }
     return cp;
 }
References bb_error_msg(), is_prefixed_with(), str, and strstr().
Referenced by get_header_tar(), and unzip_main().
transformer_write()
ssize_t transformer_write (transformer_state_t * xstate, const void * buf, size_t bufsize)
Definition at line 26 of file open_transformer.c.
 {
     ssize_t nwrote;
     if (xstate->mem_output_size_max != 0) {
         size_t pos = xstate->mem_output_size;
         size_t size;
         size = (xstate->mem_output_size += bufsize);
         if (size > xstate->mem_output_size_max) {
             free(xstate->mem_output_buf);
             xstate->mem_output_buf = NULL;
             bb_perror_msg("buffer %u too small", (unsigned)xstate->mem_output_size_max);
             nwrote = -1;
             goto ret;
         }
         xstate->mem_output_buf = xrealloc(xstate->mem_output_buf, size + 1);
         memcpy(xstate->mem_output_buf + pos, buf, bufsize);
         xstate->mem_output_buf[size] = '\0';
         nwrote = bufsize;
     } else {
         nwrote = full_write(xstate->dst_fd, buf, bufsize);
         if (nwrote != (ssize_t)bufsize) {
             bb_simple_perror_msg("write");
             nwrote = -1;
             goto ret;
         }
     }
  ret:
     return nwrote;
 }
References bb_perror_msg(), bb_simple_perror_msg(), buf, transformer_state_t::dst_fd, free, full_write(), transformer_state_t::mem_output_buf, transformer_state_t::mem_output_size, transformer_state_t::mem_output_size_max, memcpy, NULL, pos, size, and xrealloc.
Referenced by IF_DESKTOP(), and xtransformer_write().
unpack_ar_archive()
void unpack_ar_archive (archive_handle_t * ar_archive)
Definition at line 9 of file unpack_ar_archive.c.
 {
     char magic[7];
     xread(ar_archive->src_fd, magic, AR_MAGIC_LEN);
     if (!is_prefixed_with(magic, AR_MAGIC)) {
         bb_simple_error_msg_and_die("invalid ar magic");
     }
     ar_archive->offset += AR_MAGIC_LEN;
     while (get_header_ar(ar_archive) == EXIT_SUCCESS)
         continue;
 }
References AR_MAGIC, AR_MAGIC_LEN, bb_simple_error_msg_and_die(), EXIT_SUCCESS, get_header_ar(), is_prefixed_with(), archive_handle_t::offset, archive_handle_t::src_fd, and xread().
Referenced by ar_main(), deb_extract_control_file_to_buffer(), dpkg_deb_main(), and unpack_package().
unpack_bz2_data()
char* unpack_bz2_data (const char * packed, int packed_len, int unpacked_len)
Definition at line 851 of file decompress_bunzip2.c.
 {
     char *outbuf = NULL;
     bunzip_data *bd;
     int i;
     jmp_buf jmpbuf;
     /* Setup for I/O error handling via longjmp */
     i = setjmp(jmpbuf);
     if (i == 0) {
         i = start_bunzip(&jmpbuf,
             &bd,
             /* src_fd: */ -1,
             /* inbuf:  */ packed,
             /* len:    */ packed_len
         );
     }
     /* read_bunzip can longjmp and end up here with i != 0
      * on read data errors! Not trivial */
     if (i == 0) {
         /* Cannot use xmalloc: will leak bd in NOFORK case! */
         outbuf = malloc_or_warn(unpacked_len);
         if (outbuf)
             read_bunzip(bd, outbuf, unpacked_len);
     }
     dealloc_bunzip(bd);
     return outbuf;
 }
References bd, dealloc_bunzip(), i, malloc_or_warn(), NULL, outbuf, read_bunzip(), setjmp, and start_bunzip().
Referenced by bbconfig_main().
xtransformer_write()
ssize_t xtransformer_write (transformer_state_t * xstate, const void * buf, size_t bufsize)
Definition at line 58 of file open_transformer.c.
 {
     ssize_t nwrote = transformer_write(xstate, buf, bufsize);
     if (nwrote != (ssize_t)bufsize) {
         xfunc_die();
     }
     return nwrote;
 }
References buf, transformer_write(), and xfunc_die().
Referenced by IF_DESKTOP().
Variable Documentation
cpio_TRAILER
const char cpio_TRAILER[] extern
Referenced by get_header_cpio().