Fennix Userspace: Userspace/musl/src/unistd/write.c File Reference
write.c File Reference
#include <unistd.h>
#include "syscall.h"
Functions
ssize_t write (int fd, const void *buf, size_t count)
Function Documentation
write()
ssize_t write (int fd, const void * buf, size_t count)
Definition at line 4 of file write.c.
 {
     return syscall_cp(SYS_write, fd, buf, count);
 }
References buf, count, fd, and syscall_cp.
Referenced by alrm_catcher(), bb_putchar_stderr(), cat_main(), dumpkmap_main(), eventfd_write(), fcopy(), forkpty(), guarantee(), heredoc_write(), history_do_write(), history_truncate_file(), io_thread_func(), iproute_flush_cache(), lpqr_main(), main(), memory_out(), microcom_main(), preadfd(), printLines(), pscan_main(), pthread_setname_np(), readwrite(), rtnl_send_check(), runsvdir_main(), s_chld_term(), safe_write(), sem_open(), setup_heredoc(), show_textbox(), shutdown_watchdog(), signal_handler(), stunalloc(), tee_builtin(), test_ptmx(), update_status(), watchdog_main(), write_tables(), and zwrite().