Fennix: Userspace/apps/base/bash/lib/sh/snprintf.c File Reference
snprintf.c File Reference
#include <bashtypes.h>
#include <varargs.h>
#include <bashansi.h>
#include <chartypes.h>
#include <float.h>
#include <stdio.h>
#include <typemax.h>
#include "stdc.h"
#include <shmbutil.h>
#include "shell.h"
#include <xmalloc.h>
Data Structures
struct DATA
Macros
#define FLOATING_POINT
#define FREE(x) if (x) free (x)
#define INT_STRLEN_BOUND(t)
#define PF_ALTFORM 0x00001 /* # */
#define PF_HEXPREFIX 0x00002 /* 0[Xx] */
#define PF_LADJUST 0x00004 /* - */
#define PF_ZEROPAD 0x00008 /* 0 */
#define PF_PLUS 0x00010 /* + */
#define PF_SPACE 0x00020 /* ' ' */
#define PF_THOUSANDS 0x00040 /* ' */
#define PF_DOT 0x00080 /* `.precision' */
#define PF_STAR_P 0x00100 /* `*' after precision */
#define PF_STAR_W 0x00200 /* `*' before or without precision */
#define PF_SIGNEDCHAR 0x00400 /* hh */
#define PF_SHORTINT 0x00800 /* h */
#define PF_LONGINT 0x01000 /* l */
#define PF_LONGLONG 0x02000 /* ll */
#define PF_LONGDBL 0x04000 /* L */
#define PF_INTMAX_T 0x08000 /* j */
#define PF_SIZE_T 0x10000 /* z */
#define PF_PTRDIFF_T 0x20000 /* t */
#define PF_ALLOCBUF 0x40000 /* for asprintf, vasprintf */
#define PFM_SN 0x01 /* snprintf, vsnprintf */
#define PFM_AS 0x02 /* asprintf, vasprintf */
#define ASBUFSIZE 128
#define x_digs "0123456789abcdef"
#define X_digs "0123456789ABCDEF"
#define MAX_INT 99 + 1 /* 1 for the null */
#define MAX_FRACT 307 + 1
#define itoa(n) fmtulong(n, 10, intbuf, sizeof(intbuf), 0);
#define dtoa(n, p, f) numtoa(n, 10, p, f)
#define SWAP_INT(a, b) {int t; t = (a); (a) = (b); (b) = t;}
#define GETARG(type) (va_arg(args, type))
#define GETSIGNED(p)
#define GETUNSIGNED(p)
#define GETDOUBLE(p) GETARG (double)
#define SET_SIZE_FLAGS(p, type)
#define FALLBACK_FMTSIZE 32
#define FALLBACK_BASE 4096
#define LFALLBACK_BASE 5120
#define LONGDOUBLE double
#define isnan(x)
#define isinf(x)
#define RIGHT 1
#define LEFT 0
#define NOT_FOUND -1
#define FOUND 1
#define MAX_FIELD 15
#define ROUND(d, p)
#define DEF_PREC(p)
#define PUT_CHAR(c, p)
#define PUT_STRING(string, len, p)
#define PUT_PLUS(d, p, zero)
#define PUT_SPACE(d, p, zero)
#define PAD_RIGHT(p)
#define PAD_LEFT(p)
#define PAD_ZERO(p)
#define STAR_ARGS(p)
#define GETLOCALEDATA(d, t, g) ((d) = '.', (t) = ',', g = "\003")
#define PRECISION 1.e-6
Functions
static double pow_10 PARAMS ((int))
static int log_10 PARAMS ((double))
static double integral PARAMS ((double, double *))
static char *numtoa PARAMS ((double, int, int, char **))
static void init_data PARAMS ((struct DATA *, char *, size_t, const char *, int))
static void init_conv_flag PARAMS ((struct DATA *))
static void floating PARAMS ((struct DATA *, double))
static void number PARAMS ((struct DATA *, unsigned long, int))
static void pointer PARAMS ((struct DATA *, unsigned long))
static void strings PARAMS ((struct DATA *, char *))
static void dfallback PARAMS ((struct DATA *, const char *, const char *, double))
static char *groupnum PARAMS ((char *))
static int isnan_f (float x)
static int isnan_d (double x)
static int isnan_ld (LONGDOUBLE x)
static int isinf_f (float x)
static int isinf_d (double x)
static int isinf_ld (LONGDOUBLE x)
static double pow_10 (int n)
static int log_10 (double r)
static double integral (double real, double *ip)
static char * numtoa (double number, int base, int precision, char **fract)
static void number (struct DATA *p, unsigned long d, int base)
static void pointer (struct DATA *p, unsigned long d)
static void strings (struct DATA *p, char *tmp)
static int chkinfnan (struct DATA *p, double d, int mode)
static void floating (struct DATA *p, double d)
static void exponent (struct DATA *p, double d)
static char * groupnum (char *s)
static void init_conv_flag (struct DATA *p)
static void init_data (struct DATA *p, char *string, size_t length, const char *format, int mode)
static int vsnprintf_internal (struct DATA *data, char *string, size_t length, const char *format, va_list args)
static void dfallback (struct DATA *data, const char *fs, const char *fe, double d)
int vsnprintf (char *string, size_t length, const char *format, va_list args)
int snprintf (char *string, size_t length, const char *format, va_alist)
int vasprintf (char **stringp, const char *format, va_list args)
int asprintf (char **stringp, const char *format, va_alist)
Variables
static char intbuf [INT_STRLEN_BOUND(unsigned long)+1]
static int decpoint
static int thoussep
static char * grouping
Data Structure Documentation
DATA
struct DATA
Definition at line 257 of file snprintf.c.
Data Fields
char * base
int counter
int flags
char * holder
int justify
int length
char pad
const char * pf
int precision
int width
Macro Definition Documentation
ASBUFSIZE
#define ASBUFSIZE 128
Definition at line 179 of file snprintf.c.
DEF_PREC
#define DEF_PREC (p)
Value:
        if ((p)->precision == NOT_FOUND) \
          (p)->precision = 6
Definition at line 358 of file snprintf.c.
dtoa
#define dtoa (n, p, f) numtoa(n, 10, p, f)
Definition at line 224 of file snprintf.c.
FALLBACK_BASE
#define FALLBACK_BASE 4096
Definition at line 297 of file snprintf.c.
FALLBACK_FMTSIZE
#define FALLBACK_FMTSIZE 32
Definition at line 296 of file snprintf.c.
FLOATING_POINT
#define FLOATING_POINT
Definition at line 57 of file snprintf.c.
FOUND
#define FOUND 1
Definition at line 348 of file snprintf.c.
FREE
#define FREE (x) if (x) free (x)
Definition at line 137 of file snprintf.c.
GETARG
#define GETARG (type) (va_arg(args, type))
Definition at line 228 of file snprintf.c.
GETDOUBLE
#define GETDOUBLE (p) GETARG (double)
Definition at line 248 of file snprintf.c.
GETLOCALEDATA
#define GETLOCALEDATA (d, t, g) ((d) = '.', (t) = ',', g = "\003")
Definition at line 464 of file snprintf.c.
GETSIGNED
#define GETSIGNED (p)
Value:
  (((p)->flags & PF_LONGINT) \
    ? GETARG (long) \
    : (((p)->flags & PF_SHORTINT) ? (long)(short)GETARG (int) \
                      : (long)GETARG (int)))
Definition at line 232 of file snprintf.c.
GETUNSIGNED
#define GETUNSIGNED (p)
Value:
  (((p)->flags & PF_LONGINT) \
    ? GETARG (unsigned long) \
    : (((p)->flags & PF_SHORTINT) ? (unsigned long)(unsigned short)GETARG (int) \
                      : (unsigned long)GETARG (unsigned int)))
Definition at line 238 of file snprintf.c.
INT_STRLEN_BOUND
#define INT_STRLEN_BOUND (t)
Value:
  ((sizeof (t) * CHAR_BIT - TYPE_SIGNED (t)) * 302 / 1000 \
     + 1 + TYPE_SIGNED (t))
Definition at line 146 of file snprintf.c.
isinf
#define isinf (x)
Value:
      (sizeof (x) == sizeof (LONGDOUBLE) ? isinf_ld (x) \
       : sizeof (x) == sizeof (double) ? isinf_d (x) \
       : isinf_f (x))
Definition at line 327 of file snprintf.c.
isnan
#define isnan (x)
Value:
      (sizeof (x) == sizeof (LONGDOUBLE) ? isnan_ld (x) \
       : sizeof (x) == sizeof (double) ? isnan_d (x) \
       : isnan_f (x))
Definition at line 317 of file snprintf.c.
itoa
#define itoa (n) fmtulong(n, 10, intbuf, sizeof(intbuf), 0);
Definition at line 223 of file snprintf.c.
LEFT
#define LEFT 0
Definition at line 346 of file snprintf.c.
LFALLBACK_BASE
#define LFALLBACK_BASE 5120
Definition at line 298 of file snprintf.c.
LONGDOUBLE
#define LONGDOUBLE double
Definition at line 310 of file snprintf.c.
MAX_FIELD
#define MAX_FIELD 15
Definition at line 349 of file snprintf.c.
MAX_FRACT
#define MAX_FRACT 307 + 1
Definition at line 217 of file snprintf.c.
MAX_INT
#define MAX_INT 99 + 1 /* 1 for the null */
Definition at line 216 of file snprintf.c.
NOT_FOUND
#define NOT_FOUND -1
Definition at line 347 of file snprintf.c.
PAD_LEFT
#define PAD_LEFT (p)
Value:
        if ((p)->width > 0 && (p)->justify == LEFT) \
          for (; (p)->width > 0; (p)->width--) \
         PUT_CHAR((p)->pad, p)
Definition at line 408 of file snprintf.c.
PAD_RIGHT
#define PAD_RIGHT (p)
Value:
        if ((p)->width > 0 && (p)->justify != LEFT) \
          for (; (p)->width > 0; (p)->width--) \
         PUT_CHAR((p)->pad, p)
Definition at line 402 of file snprintf.c.
PAD_ZERO
#define PAD_ZERO (p)
Value:
    if ((p)->precision > 0) \
      for (; (p)->precision > 0; (p)->precision--) \
        PUT_CHAR('0', p)
Definition at line 414 of file snprintf.c.
PF_ALLOCBUF
#define PF_ALLOCBUF 0x40000 /* for asprintf, vasprintf */
Definition at line 174 of file snprintf.c.
PF_ALTFORM
#define PF_ALTFORM 0x00001 /* # */
Definition at line 152 of file snprintf.c.
PF_DOT
#define PF_DOT 0x00080 /* `.precision' */
Definition at line 160 of file snprintf.c.
PF_HEXPREFIX
#define PF_HEXPREFIX 0x00002 /* 0[Xx] */
Definition at line 153 of file snprintf.c.
PF_INTMAX_T
#define PF_INTMAX_T 0x08000 /* j */
Definition at line 170 of file snprintf.c.
PF_LADJUST
#define PF_LADJUST 0x00004 /* - */
Definition at line 154 of file snprintf.c.
PF_LONGDBL
#define PF_LONGDBL 0x04000 /* L */
Definition at line 169 of file snprintf.c.
PF_LONGINT
#define PF_LONGINT 0x01000 /* l */
Definition at line 167 of file snprintf.c.
PF_LONGLONG
#define PF_LONGLONG 0x02000 /* ll */
Definition at line 168 of file snprintf.c.
PF_PLUS
#define PF_PLUS 0x00010 /* + */
Definition at line 156 of file snprintf.c.
PF_PTRDIFF_T
#define PF_PTRDIFF_T 0x20000 /* t */
Definition at line 172 of file snprintf.c.
PF_SHORTINT
#define PF_SHORTINT 0x00800 /* h */
Definition at line 166 of file snprintf.c.
PF_SIGNEDCHAR
#define PF_SIGNEDCHAR 0x00400 /* hh */
Definition at line 165 of file snprintf.c.
PF_SIZE_T
#define PF_SIZE_T 0x10000 /* z */
Definition at line 171 of file snprintf.c.
PF_SPACE
#define PF_SPACE 0x00020 /* ' ' */
Definition at line 157 of file snprintf.c.
PF_STAR_P
#define PF_STAR_P 0x00100 /* `*' after precision */
Definition at line 161 of file snprintf.c.
PF_STAR_W
#define PF_STAR_W 0x00200 /* `*' before or without precision */
Definition at line 162 of file snprintf.c.
PF_THOUSANDS
#define PF_THOUSANDS 0x00040 /* ' */
Definition at line 158 of file snprintf.c.
PF_ZEROPAD
#define PF_ZEROPAD 0x00008 /* 0 */
Definition at line 155 of file snprintf.c.
PFM_AS
#define PFM_AS 0x02 /* asprintf, vasprintf */
Definition at line 177 of file snprintf.c.
PFM_SN
#define PFM_SN 0x01 /* snprintf, vsnprintf */
Definition at line 176 of file snprintf.c.
PRECISION
#define PRECISION 1.e-6
Definition at line 593 of file snprintf.c.
PUT_CHAR
#define PUT_CHAR (c, p)
Value:
    do \
      { \
        if (((p)->flags & PF_ALLOCBUF) && ((p)->counter >= (p)->length - 1)) \
          { \
        (p)->length += ASBUFSIZE; \
        (p)->base = (char *)xrealloc((p)->base, (p)->length); \
        (p)->holder = (p)->base + (p)->counter; /* in case reallocated */ \
          } \
        if ((p)->counter < (p)->length) \
          *(p)->holder++ = (c); \
        (p)->counter++; \
      } \
    while (0)
Definition at line 364 of file snprintf.c.
PUT_PLUS
#define PUT_PLUS (d, p, zero)
Value:
        if (((p)->flags & PF_PLUS) && (d) > zero) \
          PUT_CHAR('+', p)
Definition at line 393 of file snprintf.c.
PUT_SPACE
#define PUT_SPACE (d, p, zero)
Value:
        if (((p)->flags & PF_SPACE) && (d) > zero) \
          PUT_CHAR(' ', p)
Definition at line 397 of file snprintf.c.
PUT_STRING
#define PUT_STRING (string, len, p)
Value:
    do \
      { \
        PAD_RIGHT (p); \
        while ((len)-- > 0) \
          { \
        PUT_CHAR (*(string), (p)); \
        (string)++; \
          } \
        PAD_LEFT (p); \
      } \
    while (0)
Definition at line 380 of file snprintf.c.
RIGHT
#define RIGHT 1
Definition at line 345 of file snprintf.c.
ROUND
#define ROUND (d, p)
Value:
        (d < 0.) ? \
         d - pow_10(-(p)->precision) * 0.5 : \
         d + pow_10(-(p)->precision) * 0.5
Definition at line 352 of file snprintf.c.
SET_SIZE_FLAGS
#define SET_SIZE_FLAGS (p, type)
Value:
  if (sizeof (type) > sizeof (int)) \
    (p)->flags |= PF_LONGINT; \
  if (sizeof (type) > sizeof (long)) \
    (p)->flags |= PF_LONGLONG;
Definition at line 250 of file snprintf.c.
STAR_ARGS
#define STAR_ARGS (p)
Value:
    do { \
        if ((p)->flags & PF_STAR_W) \
          { \
        (p)->width = GETARG (int); \
        if ((p)->width < 0) \
          { \
            (p)->flags |= PF_LADJUST; \
            (p)->justify = LEFT; \
            (p)->width = -(p)->width; \
          } \
          } \
        if ((p)->flags & PF_STAR_P) \
          { \
        (p)->precision = GETARG (int); \
        if ((p)->precision < 0) \
          { \
            (p)->flags &= ~PF_STAR_P; \
            (p)->precision = NOT_FOUND; \
          } \
          } \
    } while (0)
Definition at line 420 of file snprintf.c.
SWAP_INT
#define SWAP_INT (a, b) {int t; t = (a); (a) = (b); (b) = t;}
Definition at line 226 of file snprintf.c.
x_digs
#define x_digs "0123456789abcdef"
Definition at line 181 of file snprintf.c.
X_digs
#define X_digs "0123456789ABCDEF"
Definition at line 182 of file snprintf.c.
Function Documentation
asprintf()
int asprintf (char ** stringp, const char * format, va_alist)
Definition at line 1779 of file snprintf.c.
 {
   int rval;
   va_list args;
   SH_VA_START(args, format);
   rval = vasprintf (stringp, format, args);
   va_end(args);
   return rval;
 }
References args, format(), SH_VA_START, va_end, and vasprintf().
Referenced by logdir_open().
chkinfnan()
static int chkinfnan (struct DATA * p, double d, int mode) static
Definition at line 959 of file snprintf.c.
 {
   int i;
   char *tmp;
   char *big, *small;
   i = (mode == 1) ? isinf(d) : isnan(d);
   if (i == 0)
     return 0;
   big = (mode == 1) ? "INF" : "NAN";
   small = (mode == 1) ? "inf" : "nan";
   tmp = (*p->pf == 'F' || *p->pf == 'G' || *p->pf == 'E') ? big : small;
   if (i < 0)
     PUT_CHAR('-', p);
   while (*tmp)
     {
       PUT_CHAR (*tmp, p);
       tmp++;
     }
   return 1;
 }
References i, isinf, isnan, p, and PUT_CHAR.
Referenced by exponent(), and floating().
dfallback()
static void dfallback (struct DATA * data, const char * fs, const char * fe, double d) static
Definition at line 1675 of file snprintf.c.
 {
   register char *x;
   char fmtbuf[FALLBACK_FMTSIZE], obuf[FALLBACK_BASE];
   int fl;
   fl = fe - fs + 1;
   strncpy (fmtbuf, fs, fl);
   fmtbuf[fl] = '\0';
   if ((data->flags & PF_STAR_W) && (data->flags & PF_STAR_P))
     sprintf (obuf, fmtbuf, data->width, data->precision, d);
   else if (data->flags & PF_STAR_W)
     sprintf (obuf, fmtbuf, data->width, d);
   else if (data->flags & PF_STAR_P)
     sprintf (obuf, fmtbuf, data->precision, d);
   else
     sprintf (obuf, fmtbuf, d);
   for (x = obuf; *x; x++)
     PUT_CHAR (*x, data);
 }
References FALLBACK_BASE, FALLBACK_FMTSIZE, DATA::flags, obuf, PF_STAR_P, PF_STAR_W, DATA::precision, PUT_CHAR, sprintf(), strncpy(), DATA::width, and x.
Referenced by vsnprintf_internal().
exponent()
static void exponent (struct DATA * p, double d) static
Definition at line 1061 of file snprintf.c.
 {
   char *tmp, *tmp2;
   int j, i;
   if (d != 0 && (chkinfnan(p, d, 1) || chkinfnan(p, d, 2)))
     return; /* already printed nan or inf */
   GETLOCALEDATA(decpoint, thoussep, grouping);
   DEF_PREC(p);
   if (d == 0.)
     j = 0;
   else
     {
       j = log_10(d);
       d = d / pow_10(j);  /* get the Mantissa */
       d = ROUND(d, p);
     }
   tmp = dtoa(d, p->precision, &tmp2);
   /* 1 for unit, 1 for the '.', 1 for 'e|E',
    * 1 for '+|-', 2 for 'exp'  (but no `.' if precision == 0 */
   /* calculate how much padding need */
   p->width = p->width -
         /* XXX - should this be d>0. && (p->flags & PF_PLUS) ? */
 #if 0
          ((d > 0. && p->justify == RIGHT) ? 1:0) -
 #else
          ((d > 0. && (p->flags & PF_PLUS)) ? 1:0) -
 #endif
          (p->precision != 0 || (p->flags & PF_ALTFORM)) -
          ((p->flags & PF_SPACE) ? 1:0) - p->precision - 5;
   if (p->pad == ' ')
     {
       PAD_RIGHT(p);
       PUT_PLUS(d, p, 0.);
     }
   else
     {
       if (*tmp == '-')
     PUT_CHAR(*tmp++, p);
       PUT_PLUS(d, p, 0.);
       PAD_RIGHT(p);
     }
   PUT_SPACE(d, p, 0.);
   while (*tmp)
     {
       PUT_CHAR(*tmp, p);
       tmp++;
     }
   if (p->precision != 0 || (p->flags & PF_ALTFORM))
       PUT_CHAR(decpoint, p);  /* the '.' */
   if ((*p->pf == 'g' || *p->pf == 'G') && (p->flags & PF_ALTFORM) == 0)
     /* smash the trailing zeros unless altform */
     for (i = strlen(tmp2) - 1; i >= 0 && tmp2[i] == '0'; i--)
       tmp2[i] = '\0';
   for (; *tmp2; tmp2++)
     PUT_CHAR(*tmp2, p); /* the fraction */
   /* the exponent put the 'e|E' */
   if (*p->pf == 'g' || *p->pf == 'e')
     PUT_CHAR('e', p);
   else
     PUT_CHAR('E', p);
   /* the sign of the exp */
   if (j >= 0)
     PUT_CHAR('+', p);
   else
     {
       PUT_CHAR('-', p);
       j = -j;
     }
    tmp = itoa(j);
    /* pad out to at least two spaces.  pad with `0' if the exponent is a
       single digit. */
    if (j <= 9)
      PUT_CHAR('0', p);
    /* the exponent */
    while (*tmp)
      {
        PUT_CHAR(*tmp, p);
        tmp++;
      }
    PAD_LEFT(p);
 }
References chkinfnan(), decpoint, DEF_PREC, dtoa, GETLOCALEDATA, grouping, i, if(), itoa, j, log_10(), p, PAD_LEFT, PAD_RIGHT, PF_ALTFORM, PF_PLUS, PF_SPACE, pow_10(), PUT_CHAR, PUT_PLUS, PUT_SPACE, RIGHT, ROUND, strlen(), and thoussep.
Referenced by strtod(), and vsnprintf_internal().
floating()
static void floating (struct DATA * p, double d) static
Definition at line 990 of file snprintf.c.
 {
   char *tmp, *tmp2, *t;
   int i;
   if (d != 0 && (chkinfnan(p, d, 1) || chkinfnan(p, d, 2)))
     return; /* already printed nan or inf */
   GETLOCALEDATA(decpoint, thoussep, grouping);
   DEF_PREC(p);
   d = ROUND(d, p);
   tmp = dtoa(d, p->precision, &tmp2);
   t = 0;
   if ((p->flags & PF_THOUSANDS) && grouping && (t = groupnum (tmp)))
     tmp = t;
   if ((*p->pf == 'g' || *p->pf == 'G') && (p->flags & PF_ALTFORM) == 0)
     {
       /* smash the trailing zeros unless altform */
       for (i = strlen(tmp2) - 1; i >= 0 && tmp2[i] == '0'; i--)
     tmp2[i] = '\0';
       if (tmp2[0] == '\0')
     p->precision = 0;
     }
   /* calculate the padding. 1 for the dot */
   p->width = p->width -
         /* XXX - should this be d>0. && (p->flags & PF_PLUS) ? */
 #if 0
         ((d > 0. && p->justify == RIGHT) ? 1:0) -
 #else
         ((d > 0. && (p->flags & PF_PLUS)) ? 1:0) -
 #endif
         ((p->flags & PF_SPACE) ? 1:0) -
         strlen(tmp) - p->precision -
         ((p->precision != 0 || (p->flags & PF_ALTFORM)) ? 1 : 0);   /* radix char */
   if (p->pad == ' ')
     {
       PAD_RIGHT(p);
       PUT_PLUS(d, p, 0.);
     }
   else
     {
       if (*tmp == '-')
     PUT_CHAR(*tmp++, p);
       PUT_PLUS(d, p, 0.);
       PAD_RIGHT(p);
     }
   PUT_SPACE(d, p, 0.);
   while (*tmp)
     {
       PUT_CHAR(*tmp, p);    /* the integral */
       tmp++;
     }
   FREE (t);
   if (p->precision != 0 || (p->flags & PF_ALTFORM))
     PUT_CHAR(decpoint, p);  /* put the '.' */
   for (; *tmp2; tmp2++)
     PUT_CHAR(*tmp2, p); /* the fraction */
   PAD_LEFT(p);
 }
References chkinfnan(), decpoint, DEF_PREC, dtoa, FREE, GETLOCALEDATA, grouping, groupnum(), i, p, PAD_LEFT, PAD_RIGHT, PF_ALTFORM, PF_PLUS, PF_SPACE, PF_THOUSANDS, PUT_CHAR, PUT_PLUS, PUT_SPACE, RIGHT, ROUND, strlen(), t, and thoussep.
Referenced by vsnprintf_internal().
groupnum()
static char* groupnum (char * s) static
Definition at line 1163 of file snprintf.c.
 {
   char *se, *ret, *re, *g;
   int len, slen;
   if (grouping == 0 || *grouping <= 0 || *grouping == CHAR_MAX)
     return ((char *)NULL);
   /* find min grouping to size returned string */
   for (len = *grouping, g = grouping; *g; g++)
       if (*g > 0 && *g < len)
     len = *g;
   slen = strlen (s);
   len = slen / len + 1;
   ret = (char *)xmalloc (slen + len + 1);
   re = ret + slen + len;
   *re = '\0';
   g = grouping;
   se = s + slen;
   len = *g;
   while (se > s)
     {
       *--re = *--se;
       /* handle `-' inserted by numtoa() and the fmtu* family here. */
       if (se > s && se[-1] == '-')
     continue;
       /* begin new group. */
       if (--len == 0 && se > s)
     {
       *--re = thoussep;
       len = *++g;       /* was g++, but that uses first char twice (glibc bug, too) */
       if (*g == '\0')
         len = *--g;     /* use previous grouping */
       else if (*g == CHAR_MAX)
         {
           do
         *--re = *--se;
           while (se > s);
           break;
         }
     }
     }
   if (re > ret)
 #ifdef HAVE_MEMMOVE
     memmove (ret, re, strlen (re) + 1);
 #else
     strcpy (ret, re);
 #endif
   return ret;
 }
References CHAR_MAX, g, grouping, len, memmove, NULL, s, strcpy, strlen(), thoussep, and xmalloc.
Referenced by floating(), and number().
init_conv_flag()
static void init_conv_flag (struct DATA * p) static
Definition at line 1224 of file snprintf.c.
 {
   p->flags &= PF_ALLOCBUF;      /* preserve PF_ALLOCBUF flag */
   p->precision = p->width = NOT_FOUND;
   p->justify = NOT_FOUND;
   p->pad = ' ';
 }
References NOT_FOUND, p, and PF_ALLOCBUF.
Referenced by vsnprintf_internal().
init_data()
static void init_data (struct DATA * p, char * string, size_t length, const char * format, int mode) static
Definition at line 1234 of file snprintf.c.
 {
   p->length = length - 1; /* leave room for '\0' */
   p->holder = p->base = string;
   p->pf = format;
   p->counter = 0;
   p->flags = (mode == PFM_AS) ? PF_ALLOCBUF : 0;
 }
References format(), DATA::length, p, PF_ALLOCBUF, PFM_AS, and string.
Referenced by snprintf(), vasprintf(), and vsnprintf().
integral()
static double integral (double real, double * ip) static
Definition at line 552 of file snprintf.c.
 {
   int j;
   double i, s, p;
   double real_integral = 0.;
   /* take care of the obvious */
   /* equal to zero ? */
   if (real == 0.)
     {
       *ip = 0.;
       return (0.);
     }
   /* negative number ? */
   if (real < 0.)
     real = -real;
   /* a fraction ? */
   if ( real < 1.)
     {
       *ip = 0.;
       return real;
     }
   /* the real work :-) */
   for (j = log_10(real); j >= 0; j--)
     {
       p = pow_10(j);
       s = (real - real_integral)/p;
       i = 0.;
       while (i + 1. <= s)
     i++;
       real_integral += i*p;
     }
   *ip = real_integral;
   return (real - real_integral);
 }
References i, j, log_10(), p, pow_10(), and s.
Referenced by numtoa().
isinf_d()
static int isinf_d (double x) inline static
Definition at line 325 of file snprintf.c.
 { return !isnan (x) && isnan (x - x); }
References isnan, and x.
isinf_f()
static int isinf_f (float x) inline static
Definition at line 324 of file snprintf.c.
 { return !isnan (x) && isnan (x - x); }
References isnan, and x.
isinf_ld()
static int isinf_ld (LONGDOUBLE x) inline static
Definition at line 326 of file snprintf.c.
 { return !isnan (x) && isnan (x - x); }
References isnan, and x.
isnan_d()
static int isnan_d (double x) inline static
Definition at line 315 of file snprintf.c.
 { return x != x; }
References x.
isnan_f()
static int isnan_f (float x) inline static
Definition at line 314 of file snprintf.c.
 { return x != x; }
References x.
isnan_ld()
static int isnan_ld (LONGDOUBLE x) inline static
Definition at line 316 of file snprintf.c.
 { return x != x; }
References x.
log_10()
static int log_10 (double r) static
Definition at line 517 of file snprintf.c.
 {
   int i = 0;
   double result = 1.;
   if (r < 0.)
     r = -r;
   if (r < 1.)
     {
       while (result >= r)
     {
       result /= 10.;
       i++;
     }
       return (-i);
     }
   else
     {
       while (result <= r)
     {
       result *= 10.;
       i++;
     }
       return (i - 1);
     }
 }
References i.
Referenced by exponent(), integral(), and vsnprintf_internal().
number()
static void number (struct DATA * p, unsigned long d, int base) static
Definition at line 699 of file snprintf.c.
 {
   char *tmp, *t;
   long sd;
   int flags;
   /* An explicit precision turns off the zero-padding flag and sets the
      pad character back to space. */
   if ((p->flags & PF_ZEROPAD) && p->precision >= 0 && (p->flags & PF_DOT))
     {
       p->flags &= ~PF_ZEROPAD;
       p->pad = ' ';
     }
   sd = d;   /* signed for ' ' padding in base 10 */
   flags = 0;
   flags = (*p->pf == 'x' || *p->pf == 'X' || *p->pf == 'o' || *p->pf == 'u' || *p->pf == 'U') ? FL_UNSIGNED : 0;
   if (*p->pf == 'X')
     flags |= FL_HEXUPPER;
   tmp = fmtulong (d, base, intbuf, sizeof(intbuf), flags);
   t = 0;
   if ((p->flags & PF_THOUSANDS))
     {
       GETLOCALEDATA(decpoint, thoussep, grouping);
       if (grouping && (t = groupnum (tmp)))
     tmp = t;
     }
   /* need to add one for any `+', but we only add one in base 10 */
   p->width -= strlen(tmp) + (base == 10 && d > 0 && (p->flags & PF_PLUS));
   PAD_RIGHT(p);
   if ((p->flags & PF_DOT) && p->precision > 0)
     {
       p->precision -= strlen(tmp);
       PAD_ZERO(p);
     }
   switch (base)
     {
     case 10:
       PUT_PLUS(sd, p, 0);
       PUT_SPACE(sd, p, 0);
       break;
     case 8:
       if (p->flags & PF_ALTFORM)
     PUT_CHAR('0', p);
       break;
     case 16:
       if (p->flags & PF_ALTFORM)
     {
       PUT_CHAR('0', p);
       PUT_CHAR(*p->pf, p);
     }
       break;
     }
   while (*tmp)
     {
       PUT_CHAR(*tmp, p);
       tmp++;
     }
   PAD_LEFT(p);
   FREE (t);
 }
References base, decpoint, FL_HEXUPPER, FL_UNSIGNED, flags, fmtulong(), FREE, GETLOCALEDATA, grouping, groupnum(), intbuf, p, PAD_LEFT, PAD_RIGHT, PAD_ZERO, PF_ALTFORM, PF_DOT, PF_PLUS, PF_THOUSANDS, PF_ZEROPAD, PUT_CHAR, PUT_PLUS, PUT_SPACE, strlen(), t, and thoussep.
Referenced by __strftime_fmt_1(), get_signame(), numtoa(), param_expand(), parameter_brace_expand(), parameter_brace_expand_length(), print_decimal_number(), print_exponential_number(), stack_machine(), vsnprintf_internal(), and yyparse().
numtoa()
static char* numtoa (double number, int base, int precision, char ** fract) static
Definition at line 601 of file snprintf.c.
 {
   register int i, j;
   double ip, fp; /* integer and fraction part */
   double fraction;
   int digits, sign;
   static char integral_part[MAX_INT];
   static char fraction_part[MAX_FRACT];
   int ch;
   /* taking care of the obvious case: 0.0 */
   if (number == 0.)
     {
       integral_part[0] = '0';
       integral_part[1] = '\0';
       /* The fractional part has to take the precision into account */
       for (ch = 0; ch < precision-1; ch++)
     fraction_part[ch] = '0';
       fraction_part[ch] = '0';
       fraction_part[ch+1] = '\0';
       if (fract)
     *fract = fraction_part;
       return integral_part;
     }
   /* -0 is tricky */
   sign = (number == -0.) ? '-' : ((number < 0.) ? '-' : '+');
   digits = MAX_INT - 1;
   /* for negative numbers */
   if (sign == '-')
     {
       number = -number;
       digits--; /* sign consume one digit */
     }
   fraction = integral(number, &ip);
   number = ip;
   /* do the integral part */
   if (ip == 0.)
     {
       integral_part[0] = '0';
       i = 1;
     }
   else
     {
       for ( i = 0; i < digits && number != 0.; ++i)
     {
       number /= base;
       fp = integral(number, &ip);
       ch = (int)((fp + PRECISION)*base); /* force to round */
       integral_part[i] = (ch <= 9) ? ch + '0' : ch + 'a' - 10;
       if (! ISXDIGIT((unsigned char)integral_part[i]))
         break;  /* bail out overflow !! */
       number = ip;
      }
     }
   /* Oh No !! out of bound, ho well fill it up ! */
   if (number != 0.)
     for (i = 0; i < digits; ++i)
       integral_part[i] = '9';
   /* put the sign ? */
   if (sign == '-')
     integral_part[i++] = '-';
   integral_part[i] = '\0';
   /* reverse every thing */
   for ( i--, j = 0; j < i; j++, i--)
     SWAP_INT(integral_part[i], integral_part[j]);
   /* the fractional part */
   for (i=0, fp=fraction; precision > 0 && i < MAX_FRACT ; i++, precision--)
     {
       fraction_part[i] = (int)((fp + PRECISION)*10. + '0');
       if (! DIGIT(fraction_part[i])) /* underflow ? */
     break;
       fp = (fp*10.0) - (double)(long)((fp + PRECISION)*10.);
     }
   fraction_part[i] = '\0';
   if (fract != (char **)0)
     *fract = fraction_part;
   return integral_part;
 }
References base, DIGIT, digits, i, integral(), ISXDIGIT, j, MAX_FRACT, MAX_INT, number(), PRECISION, and SWAP_INT.
PARAMS() [1/12]
static char* groupnum PARAMS ((char *)) static
PARAMS() [2/12]
static int log_10 PARAMS ((double)) static
PARAMS() [3/12]
static double integral PARAMS ((double, double *)) static
PARAMS() [4/12]
static char* numtoa PARAMS ((double, int, int, char **)) static
PARAMS() [5/12]
static double pow_10 PARAMS ((int)) static
PARAMS() [6/12]
static void init_conv_flag PARAMS ((struct DATA *)) static
PARAMS() [7/12]
static void strings PARAMS ((struct DATA *, char *)) static
PARAMS() [8/12]
static void init_data PARAMS ((struct DATA *, char *, size_t, const char *, int)) static
PARAMS() [9/12]
static void dfallback PARAMS ((struct DATA *, const char *, const char *, double)) static
PARAMS() [10/12]
static void floating PARAMS ((struct DATA *, double)) static
PARAMS() [11/12]
static void pointer PARAMS ((struct DATA *, unsigned long)) static
PARAMS() [12/12]
static void number PARAMS ((struct DATA *, unsigned long, int)) static
pointer()
static void pointer (struct DATA * p, unsigned long d) static
Definition at line 847 of file snprintf.c.
 {
   char *tmp;
   tmp = fmtulong(d, 16, intbuf, sizeof(intbuf), 0);
   p->width -= strlen(tmp);
   PAD_RIGHT(p);
   /* prefix '0x' for pointers */
   PUT_CHAR('0', p);
   PUT_CHAR('x', p);
   while (*tmp)
     {
       PUT_CHAR(*tmp, p);
       tmp++;
     }
   PAD_LEFT(p);
 }
References fmtulong(), intbuf, p, PAD_LEFT, PAD_RIGHT, PUT_CHAR, and strlen().
Referenced by vsnprintf_internal().
pow_10()
static double pow_10 (int n) static
Definition at line 473 of file snprintf.c.
 {
   double P;
   /* handle common cases with fast switch statement. */
   switch (n)
     {
     case -3:    return .001;
     case -2:    return .01;
     case -1:    return .1;
     case 0: return 1.;
     case 1: return 10.;
     case 2: return 100.;
     case 3: return 1000.;
     }
   if (n < 0)
     {
       P = .0001;
       for (n += 4; n < 0; n++)
     P /= 10.;
     }
   else
     {
       P = 10000.;
       for (n -= 4; n > 0; n--)
     P *= 10.;
     }
   return P;
 }
References n, and P.
Referenced by exponent(), and integral().
snprintf()
int snprintf (char * string, size_t length, const char * format, va_alist)
Definition at line 1727 of file snprintf.c.
 {
   struct DATA data;
   int rval;
   va_list args;
   SH_VA_START(args, format);
   if (string == 0 && length != 0)
     return 0;
   init_data (&data, string, length, format, PFM_SN);
   rval = vsnprintf_internal (&data, string, length, format, args);
   va_end(args);
   return rval;
 }
References args, format(), init_data(), DATA::length, PFM_SN, SH_VA_START, va_end, and vsnprintf_internal().
strings()
static void strings (struct DATA * p, char * tmp) static
Definition at line 872 of file snprintf.c.
 {
   size_t len;
   len = strlen(tmp);
   if (p->precision != NOT_FOUND) /* the smallest number */
     len = (len < p->precision ? len : p->precision);
   p->width -= len;
   PUT_STRING (tmp, len, p);
 }
References len, NOT_FOUND, p, PUT_STRING, and strlen().
Referenced by vsnprintf_internal().
vasprintf()
int vasprintf (char ** stringp, const char * format, va_list args)
Definition at line 1758 of file snprintf.c.
 {
   struct DATA data;
   char *string;
   int r;
   string = (char *)xmalloc(ASBUFSIZE);
   init_data (&data, string, ASBUFSIZE, format, PFM_AS);
   r = vsnprintf_internal(&data, string, ASBUFSIZE, format, args);
   *stringp = data.base;     /* not string in case reallocated */
   return r;
 }
References ASBUFSIZE, DATA::base, format(), init_data(), PFM_AS, string, vsnprintf_internal(), and xmalloc.
Referenced by asprintf(), bb_verror_msg(), and xasprintf().
vsnprintf()
int vsnprintf (char * string, size_t length, const char * format, va_list args)
Definition at line 1708 of file snprintf.c.
 {
   struct DATA data;
   if (string == 0 && length != 0)
     return 0;
   init_data (&data, string, length, format, PFM_SN);
   return (vsnprintf_internal(&data, string, length, format, args));
 }
References format(), init_data(), DATA::length, PFM_SN, and vsnprintf_internal().
Referenced by snprintf().
vsnprintf_internal()
static int vsnprintf_internal (struct DATA * data, char * string, size_t length, const char * format, va_list args) static
Definition at line 1252 of file snprintf.c.
 {
   double d; /* temporary holder */
 #ifdef HAVE_LONG_DOUBLE
   long double ld;   /* for later */
 #endif
   unsigned long ul;
 #ifdef HAVE_UNSIGNED_LONG_LONG_INT
   unsigned long long ull;
 #endif
   int state, i, c, n;
   char *s;
 #if HANDLE_MULTIBYTE
   wchar_t *ws;
   wint_t wc;
 #endif
   const char *convstart;
   int negprec;
   /* Sanity check, the string length must be >= 0.  C99 actually says that
      LENGTH can be zero here, in the case of snprintf/vsnprintf (it's never
      0 in the case of asprintf/vasprintf), and the return value is the number
      of characters that would have been written. */
   if (length < 0)
     return -1;
   if (format == 0)
     return 0;
   /* Reset these for each call because the locale might have changed. */
   decpoint = thoussep = 0;
   grouping = 0;
   negprec = 0;
   for (; c = *(data->pf); data->pf++)
     {
       if (c != '%')
     {
       PUT_CHAR (c, data);
       continue;
     }
       convstart = data->pf;
       init_conv_flag (data); /* initialise format flags */
       state = 1;
       for (state = 1; state && *data->pf; )
     {
       c = *(++data->pf);
           /* fmtend = data->pf */
 #if defined (FLOATING_POINT) && defined (HAVE_LONG_DOUBLE)
       if (data->flags & PF_LONGDBL)
         {
           switch (c)
         {
         case 'f': case 'F':
         case 'e': case 'E':
         case 'g': case 'G':
 #  ifdef HAVE_PRINTF_A_FORMAT
         case 'a': case 'A':
 #  endif
           STAR_ARGS (data);
           ld = GETLDOUBLE (data);
           ldfallback (data, convstart, data->pf, ld);
           goto conv_break;
         }
         }
 #endif /* FLOATING_POINT && HAVE_LONG_DOUBLE */
       switch (c)
         {
           /* Parse format flags */
           case '\0': /* a NULL here ? ? bail out */
         *data->holder = '\0';
         return data->counter;
         break;
           case '#':
         data->flags |= PF_ALTFORM;
         continue;
           case '*':
         if (data->flags & PF_DOT)
           data->flags |= PF_STAR_P;
         else
           data->flags |= PF_STAR_W;
         continue;
           case '-':
         if ((data->flags & PF_DOT) == 0)
           {
             data->flags |= PF_LADJUST;
             data->justify = LEFT;
           }
         else
           negprec = 1;
         continue;
           case ' ':
         if ((data->flags & PF_PLUS) == 0)
           data->flags |= PF_SPACE;
         continue;
           case '+':
         if ((data->flags & PF_DOT) == 0)
           {
             data->flags |= PF_PLUS;
             if ((data->flags & PF_LADJUST) == 0)
               data->justify = RIGHT;
           }
         continue;
           case '\'':
         data->flags |= PF_THOUSANDS;
         continue;
           case '0':
         /* If we're not specifying precision (in which case we've seen
            a `.') and we're not performing left-adjustment (in which
            case the `0' is ignored), a `0' is taken as the zero-padding
            flag. */
             if ((data->flags & (PF_DOT|PF_LADJUST)) == 0)
           {
             data->flags |= PF_ZEROPAD;
             data->pad = '0';
             continue;
           }
           case '1': case '2': case '3':
           case '4': case '5': case '6':
           case '7': case '8': case '9':
         n = 0;
         do
           {
             n = n * 10 + TODIGIT(c);
             c = *(++data->pf);
           }
         while (DIGIT(c));
         data->pf--;     /* went too far */
         if (n < 0)
           n = 0;
         if (data->flags & PF_DOT)
           data->precision = negprec ? NOT_FOUND : n;
         else
           data->width = n;
         continue;
           /* optional precision */
           case '.':
         data->flags |= PF_DOT;
         data->precision = 0;
         continue;
           /* length modifiers */
           case 'h':
         data->flags |= (data->flags & PF_SHORTINT) ? PF_SIGNEDCHAR : PF_SHORTINT;
         continue;
           case 'l':
         data->flags |= (data->flags & PF_LONGINT) ? PF_LONGLONG : PF_LONGINT;
         continue;
           case 'L':
         data->flags |= PF_LONGDBL;
         continue;
           case 'q':
         data->flags |= PF_LONGLONG;
         continue;
           case 'j':
         data->flags |= PF_INTMAX_T;
         SET_SIZE_FLAGS(data, intmax_t);
         continue;
           case 'z':
         data->flags |= PF_SIZE_T;
         SET_SIZE_FLAGS(data, size_t);
         continue;
           case 't':
         data->flags |= PF_PTRDIFF_T;
         SET_SIZE_FLAGS(data, ptrdiff_t);
         continue;
           /* Conversion specifiers */
 #ifdef FLOATING_POINT
           case 'f':  /* float, double */
           case 'F':
         STAR_ARGS(data);
         d = GETDOUBLE(data);
         floating(data, d);
 conv_break:
         state = 0;
         break;
           case 'g':
           case 'G':
         STAR_ARGS(data);
         DEF_PREC(data);
         d = GETDOUBLE(data);
         i = (d != 0.) ? log_10(d) : -1;
         /*
          * for '%g|%G' ANSI: use f if exponent
          * is in the range or [-4,p] exclusively
          * else use %e|%E
          */
         if (-4 < i && i < data->precision)
           {
             /* reset precision */
             data->precision -= i + 1;
             floating(data, d);
           }
         else
           {
             /* reduce precision by 1 because of leading digit before
                decimal point in e format, unless specified as 0. */
             if (data->precision > 0)
               data->precision--;
             exponent(data, d);
           }
         state = 0;
         break;
           case 'e':
           case 'E':  /* Exponent double */
         STAR_ARGS(data);
         d = GETDOUBLE(data);
         exponent(data, d);
         state = 0;
         break;
 #  ifdef HAVE_PRINTF_A_FORMAT
           case 'a':
           case 'A':
         STAR_ARGS(data);
         d = GETDOUBLE(data);
         dfallback(data, convstart, data->pf, d);
         state = 0;
         break;
 #  endif /* HAVE_PRINTF_A_FORMAT */
 #endif /* FLOATING_POINT */
           case 'U':
         data->flags |= PF_LONGINT;
         /* FALLTHROUGH */
           case 'u':
         STAR_ARGS(data);
 #ifdef HAVE_LONG_LONG_INT
         if (data->flags & PF_LONGLONG)
           {
             ull = GETARG (unsigned long long);
             lnumber(data, ull, 10);
           }
         else
 #endif
           {
             ul = GETUNSIGNED(data);
             number(data, ul, 10);
           }
         state = 0;
         break;
           case 'D':
         data->flags |= PF_LONGINT;
         /* FALLTHROUGH */
           case 'd':  /* decimal */
           case 'i':
         STAR_ARGS(data);
 #ifdef HAVE_LONG_LONG_INT
         if (data->flags & PF_LONGLONG)
           {
             ull = GETARG (long long);
             lnumber(data, ull, 10);
           }
         else
 #endif
           {
             ul = GETSIGNED(data);
             number(data, ul, 10);
           }
         state = 0;
         break;
           case 'o':  /* octal */
         STAR_ARGS(data);
 #ifdef HAVE_LONG_LONG_INT
         if (data->flags & PF_LONGLONG)
           {
             ull = GETARG (unsigned long long);
             lnumber(data, ull, 8);
           }
         else
 #endif
           {
             ul = GETUNSIGNED(data);
             number(data, ul, 8);
           }
         state = 0;
         break;
           case 'x':
           case 'X':  /* hexadecimal */
         STAR_ARGS(data);
 #ifdef HAVE_LONG_LONG_INT
         if (data->flags & PF_LONGLONG)
           {
             ull = GETARG (unsigned long long);
             lnumber(data, ull, 16);
           }
         else
 #endif
           {
             ul = GETUNSIGNED(data);
             number(data, ul, 16);
           }
         state = 0;
         break;
           case 'p':
         STAR_ARGS(data);
         ul = (unsigned long)GETARG (void *);
         pointer(data, ul);
         state = 0;
         break;
 #if HANDLE_MULTIBYTE
           case 'C':
         data->flags |= PF_LONGINT;
         /* FALLTHROUGH */
 #endif
           case 'c': /* character */
         STAR_ARGS(data);
 #if HANDLE_MULTIBYTE
         if (data->flags & PF_LONGINT)
           {
             wc = GETARG (wint_t);
             wchars (data, wc);
           }
         else
 #endif
           {
             ul = GETARG (int);
             PUT_CHAR(ul, data);
           }
         state = 0;
         break;
 #if HANDLE_MULTIBYTE
           case 'S':
         data->flags |= PF_LONGINT;
         /* FALLTHROUGH */
 #endif
           case 's':  /* string */
         STAR_ARGS(data);
 #if HANDLE_MULTIBYTE
         if (data->flags & PF_LONGINT)
           {
             ws = GETARG (wchar_t *);
             wstrings (data, ws);
           }
         else
 #endif
           {
             s = GETARG (char *);
             strings(data, s);
           }
         state = 0;
         break;
           case 'n':
 #ifdef HAVE_LONG_LONG_INT
         if (data->flags & PF_LONGLONG)
           *(GETARG (long long *)) = data->counter;
         else
 #endif
         if (data->flags & PF_LONGINT)
           *(GETARG (long *)) = data->counter;
         else if (data->flags & PF_SHORTINT)
           *(GETARG (short *)) = data->counter;
         else
           *(GETARG (int *)) = data->counter;
         state = 0;
         break;
           case '%':  /* nothing just % */
         PUT_CHAR('%', data);
         state = 0;
         break;
           default:
         /* is this an error ? maybe bail out */
         state = 0;
         break;
     } /* end switch */
       } /* end of `%' for loop */
     } /* end of format string for loop */
   if (data->length >= 0)
     *data->holder = '\0'; /* the end ye ! */
   return data->counter;
 }
References c, DATA::counter, decpoint, DEF_PREC, dfallback(), DIGIT, exponent(), DATA::flags, floating(), format(), GETARG, GETDOUBLE, GETSIGNED, GETUNSIGNED, grouping, DATA::holder, i, if(), init_conv_flag(), DATA::justify, LEFT, DATA::length, log_10(), n, NOT_FOUND, number(), DATA::pad, DATA::pf, PF_ALTFORM, PF_DOT, PF_INTMAX_T, PF_LADJUST, PF_LONGDBL, PF_LONGINT, PF_LONGLONG, PF_PLUS, PF_PTRDIFF_T, PF_SHORTINT, PF_SIGNEDCHAR, PF_SIZE_T, PF_SPACE, PF_STAR_P, PF_STAR_W, PF_THOUSANDS, PF_ZEROPAD, pointer(), DATA::precision, PUT_CHAR, RIGHT, s, SET_SIZE_FLAGS, STAR_ARGS, state, strings(), thoussep, TODIGIT, and DATA::width.
Referenced by snprintf(), vasprintf(), and vsnprintf().
Variable Documentation
decpoint
int decpoint static
Definition at line 186 of file snprintf.c.
Referenced by exponent(), floating(), number(), and vsnprintf_internal().
grouping
char* grouping static
Definition at line 188 of file snprintf.c.
Referenced by exponent(), floating(), groupnum(), number(), and vsnprintf_internal().
intbuf
char intbuf[INT_STRLEN_BOUND(unsigned long)+1] static
Definition at line 184 of file snprintf.c.
Referenced by cprintf(), number(), and pointer().
thoussep
int thoussep static
Definition at line 187 of file snprintf.c.
Referenced by exponent(), floating(), groupnum(), number(), and vsnprintf_internal().