Fennix Userspace: Userspace/apps/base/busybox/libbb/herror_msg.c File Reference
herror_msg.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC bb_herror_msg (const char *s,...)
void FAST_FUNC bb_herror_msg_and_die (const char *s,...)
void FAST_FUNC bb_simple_herror_msg (const char *s)
void FAST_FUNC bb_simple_herror_msg_and_die (const char *s)
Function Documentation
bb_herror_msg()
void FAST_FUNC bb_herror_msg (const char * s, ...)
Definition at line 11 of file herror_msg.c.
 {
     va_list p;
     va_start(p, s);
     bb_verror_msg(s, p, hstrerror(h_errno));
     va_end(p);
 }
References bb_verror_msg(), h_errno, hstrerror(), p, s, va_end, and va_start.
Referenced by bb_simple_herror_msg().
bb_herror_msg_and_die()
void FAST_FUNC bb_herror_msg_and_die (const char * s, ...)
Definition at line 20 of file herror_msg.c.
 {
     va_list p;
     va_start(p, s);
     bb_verror_msg(s, p, hstrerror(h_errno));
     va_end(p);
     xfunc_die();
 }
References bb_verror_msg(), h_errno, hstrerror(), p, s, va_end, va_start, and xfunc_die().
Referenced by bb_simple_herror_msg_and_die().
bb_simple_herror_msg()
void FAST_FUNC bb_simple_herror_msg (const char * s)
Definition at line 30 of file herror_msg.c.
 {
     bb_herror_msg("%s", s);
 }
References bb_herror_msg(), and s.
bb_simple_herror_msg_and_die()
void FAST_FUNC bb_simple_herror_msg_and_die (const char * s)
Definition at line 35 of file herror_msg.c.
 {
     bb_herror_msg_and_die("%s", s);
 }
References bb_herror_msg_and_die(), and s.
Referenced by arp_del(), arp_set(), arp_show(), and xgethostbyname().