Fennix Lynx Bootloader: Memory32::Virtual Class Reference
Memory32::Virtual Class Reference
#include <memory.hpp>
Data Structures
class PageMapIndexer
Public Member Functions
void Map (void *VirtualAddress, void *PhysicalAddress, uint64_t Flag=PTFlag::P)
__always_inline void Map (void *VirtualAddress, void *PhysicalAddress, size_t Length, uint64_t Flags)
Virtual (PageTable *Table=nullptr)
~Virtual ()
Private Attributes
PageTable * Table = nullptr
Detailed Description
Definition at line 204 of file memory.hpp.
Constructor & Destructor Documentation
Virtual()
Memory32::Virtual::Virtual (PageTable * Table = nullptr)
Definition at line 42 of file VirtualMemoryManager.cpp.
     {
         if (Table)
             this->Table = Table;
         else
         {
             asmv("movl %%cr3, %0"
                  : "=r"(this->Table));
         }
     }
References asmv, and Table.
~Virtual()
Memory32::Virtual::~Virtual ()
Definition at line 53 of file VirtualMemoryManager.cpp.
 {}
Member Function Documentation
Map() [1/2]
__always_inline void Memory32::Virtual::Map (void * VirtualAddress, void * PhysicalAddress, size_t Length, uint64_t Flags) inline
Definition at line 227 of file memory.hpp.
         {
             for (uintptr_t i = 0; i < Length; i += PAGE_SIZE_4K)
                 this->Map((void *)((uintptr_t)VirtualAddress + i), (void *)((uintptr_t)PhysicalAddress + i), Flags);
         }
References Length, Map(), and PAGE_SIZE_4K.
Map() [2/2]
void Memory32::Virtual::Map (void * VirtualAddress, void * PhysicalAddress, uint64_t Flag = PTFlag::P)
Definition at line 6 of file VirtualMemoryManager.cpp.
     {
         if (unlikely(!this->Table))
         {
             error("No page table");
             return;
         }
         Flags |= PTFlag::P;
         PageMapIndexer Index = PageMapIndexer((uintptr_t)VirtualAddress);
         // Clear any flags that are not 1 << 0 (Present) - 1 << 5 (Accessed) because rest are for page table entries only
         uint64_t DirectoryFlags = Flags & 0x3F;
         PageDirectoryEntry *PDE = &this->Table->Entries[Index.PDEIndex];
         PageTableEntryPtr *PTEPtr = nullptr;
         if (!PDE->Present)
         {
             PTEPtr = (PageTableEntryPtr *)KernelAllocator32.RequestPages(TO_PAGES(sizeof(PageTableEntryPtr) + 1));
             memset(PTEPtr, 0, sizeof(PageTableEntryPtr));
             PDE->Present = true;
             PDE->SetAddress((uintptr_t)PTEPtr >> 12);
         }
         else
             PTEPtr = (PageTableEntryPtr *)(PDE->GetAddress() << 12);
         PDE->raw |= DirectoryFlags;
         PageTableEntry *PTE = &PTEPtr->Entries[Index.PTEIndex];
         PTE->Present = true;
         PTE->raw |= Flags;
         PTE->SetAddress((uintptr_t)PhysicalAddress >> 12);
         asmv("invlpg (%0)" ::"r"(VirtualAddress)
              : "memory");
     }
References asmv, Memory32::PageTableEntryPtr::Entries, Memory32::PageTable::Entries, error, Memory32::PageDirectoryEntry::GetAddress(), KernelAllocator32, memset(), P, Memory32::Virtual::PageMapIndexer::PDEIndex, Memory32::Virtual::PageMapIndexer::PTEIndex, Memory32::PageTableEntry::raw, Memory32::PageDirectoryEntry::raw, Memory32::Physical::RequestPages(), Memory32::PageTableEntry::SetAddress(), Memory32::PageDirectoryEntry::SetAddress(), Table, TO_PAGES, and unlikely.
Referenced by InitializeMemoryManagement(), LoadElfInMemory(), and Map().
Field Documentation
Table
PageTable* Memory32::Virtual::Table = nullptr private
Definition at line 207 of file memory.hpp.
Referenced by Map(), and Virtual().
The documentation for this class was generated from the following files:
Lynx/FennixLoader/include/memory.hpp
Lynx/FennixLoader/Memory/VirtualMemoryManager.cpp