Fennix: Userspace/apps/base/busybox/networking/ether-wake.c File Reference
ether-wake.c File Reference
#include "libbb.h"
#include <netpacket/packet.h>
#include <netinet/ether.h>
#include <linux/if.h>
Macros
#define whereto_t sockaddr
#define make_socket() xsocket(AF_INET, SOCK_PACKET, SOCK_PACKET)
#define bb_debug_msg(fmt, args...) ((void)0)
#define bb_debug_dump_packet(outpack, pktsize) ((void)0)
#define PKT_HEADER_SIZE (20 + 16*6)
Functions
static void get_dest_addr (const char *hostid, struct ether_addr *eaddr)
static int fill_pkt_header (unsigned char *pkt, struct ether_addr *eaddr, int broadcast)
static int get_wol_pw (const char *ethoptarg, unsigned char *wol_passwd)
int ether_wake_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
bb_debug_dump_packet
#define bb_debug_dump_packet (outpack, pktsize) ((void)0)
Definition at line 117 of file ether-wake.c.
bb_debug_msg
#define bb_debug_msg (fmt, args...) ((void)0)
Definition at line 116 of file ether-wake.c.
make_socket
#define make_socket () xsocket(AF_INET, SOCK_PACKET, SOCK_PACKET)
Definition at line 100 of file ether-wake.c.
PKT_HEADER_SIZE
#define PKT_HEADER_SIZE (20 + 16*6)
Definition at line 142 of file ether-wake.c.
whereto_t
#define whereto_t sockaddr
Definition at line 99 of file ether-wake.c.
Function Documentation
ether_wake_main()
int ether_wake_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 199 of file ether-wake.c.
 {
     const char *ifname = "eth0";
     char *pass;
     unsigned flags;
     unsigned char wol_passwd[6];
     int wol_passwd_sz = 0;
     int s;  /* Raw socket */
     int pktsize;
     unsigned char outpack[PKT_HEADER_SIZE + 6 /* max passwd size */ + 16 /* paranoia */];
     struct ether_addr eaddr;
     struct whereto_t whereto;  /* who to wake up */
     /* handle misc user options */
     flags = getopt32(argv, "^" "bi:p:" "\0" "=1", &ifname, &pass);
     if (flags & 4) /* -p */
         wol_passwd_sz = get_wol_pw(pass, wol_passwd);
     flags &= 1; /* we further interested only in -b [bcast] flag */
     /* create the raw socket */
     s = make_socket();
     /* now that we have a raw socket we can drop root */
     /* xsetuid(getuid()); - but save on code size... */
     /* look up the dest mac address */
     get_dest_addr(argv[optind], &eaddr);
     /* fill out the header of the packet */
     pktsize = fill_pkt_header(outpack, &eaddr, flags /* & 1 OPT_BROADCAST */);
     bb_debug_dump_packet(outpack, pktsize);
     /* Fill in the source address, if possible. */
 #ifdef __linux__
     {
         struct ifreq if_hwaddr;
         strncpy_IFNAMSIZ(if_hwaddr.ifr_name, ifname);
         ioctl_or_perror_and_die(s, SIOCGIFHWADDR, &if_hwaddr, "SIOCGIFHWADDR on %s failed", ifname);
         memcpy(outpack+6, if_hwaddr.ifr_hwaddr.sa_data, 6);
 # ifdef DEBUG
         {
             unsigned char *hwaddr = if_hwaddr.ifr_hwaddr.sa_data;
             printf("The hardware address (SIOCGIFHWADDR) of %s is type %d  "
                 "%2.2x:%2.2x:%2.2x:%2.2x:%2.2x:%2.2x\n\n", ifname,
                 if_hwaddr.ifr_hwaddr.sa_family, hwaddr[0], hwaddr[1],
                 hwaddr[2], hwaddr[3], hwaddr[4], hwaddr[5]);
         }
 # endif
     }
 #endif /* __linux__ */
     bb_debug_dump_packet(outpack, pktsize);
     /* append the password if specified */
     if (wol_passwd_sz > 0) {
         memcpy(outpack+pktsize, wol_passwd, wol_passwd_sz);
         pktsize += wol_passwd_sz;
     }
     bb_debug_dump_packet(outpack, pktsize);
     /* This is necessary for broadcasts to work */
     if (flags /* & 1 OPT_BROADCAST */) {
         if (setsockopt_broadcast(s) != 0)
             bb_simple_perror_msg("SO_BROADCAST");
     }
 #if defined(PF_PACKET)
     {
         struct ifreq ifr;
         strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
         xioctl(s, SIOCGIFINDEX, &ifr);
         memset(&whereto, 0, sizeof(whereto));
         whereto.sll_family = AF_PACKET;
         whereto.sll_ifindex = ifr.ifr_ifindex;
         /* The manual page incorrectly claims the address must be filled.
            We do so because the code may change to match the docs. */
         whereto.sll_halen = ETH_ALEN;
         memcpy(whereto.sll_addr, outpack, ETH_ALEN);
     }
 #else
     whereto.sa_family = 0;
     strcpy(whereto.sa_data, ifname);
 #endif
     xsendto(s, outpack, pktsize, (struct sockaddr *)&whereto, sizeof(whereto));
     if (ENABLE_FEATURE_CLEAN_UP)
         close(s);
     return EXIT_SUCCESS;
 }
References AF_PACKET, argv, bb_debug_dump_packet, bb_simple_perror_msg(), close(), ETH_ALEN, EXIT_SUCCESS, fill_pkt_header(), flags, get_dest_addr(), get_wol_pw(), getopt32(), ifr, ioctl_or_perror_and_die(), make_socket, memcpy, memset, optind, PKT_HEADER_SIZE, printf, s, setsockopt_broadcast(), SIOCGIFHWADDR, SIOCGIFINDEX, strcpy, strncpy_IFNAMSIZ(), whereto_t, xioctl, and xsendto().
fill_pkt_header()
static int fill_pkt_header (unsigned char * pkt, struct ether_addr * eaddr, int broadcast) static
Definition at line 143 of file ether-wake.c.
 {
     int i;
     unsigned char *station_addr = eaddr->ether_addr_octet;
     memset(pkt, 0xff, 6);
     if (!broadcast)
         memcpy(pkt, station_addr, 6);
     pkt += 6;
     memcpy(pkt, station_addr, 6); /* 6 */
     pkt += 6;
     *pkt++ = 0x08; /* 12 */ /* Or 0x0806 for ARP, 0x8035 for RARP */
     *pkt++ = 0x42; /* 13 */
     memset(pkt, 0xff, 6); /* 14 */
     for (i = 0; i < 16; ++i) {
         pkt += 6;
         memcpy(pkt, station_addr, 6); /* 20,26,32,... */
     }
     return PKT_HEADER_SIZE; /* length of packet */
 }
References broadcast, ether_addr::ether_addr_octet, i, memcpy, memset, and PKT_HEADER_SIZE.
Referenced by ether_wake_main().
get_dest_addr()
static void get_dest_addr (const char * hostid, struct ether_addr * eaddr) static
Definition at line 126 of file ether-wake.c.
 {
     struct ether_addr *eap;
     eap = ether_aton_r(hostid, eaddr);
     if (eap) {
         bb_debug_msg("The target station address is %s\n\n", ether_ntoa(eap));
 #if !defined(__UCLIBC__) || UCLIBC_VERSION >= KERNEL_VERSION(0, 9, 30)
     } else if (ether_hostton(hostid, eaddr) == 0) {
         bb_debug_msg("Station address for hostname %s is %s\n\n", hostid, ether_ntoa(eaddr));
 #endif
     } else {
         bb_show_usage();
     }
 }
References bb_debug_msg, bb_show_usage(), ether_aton_r(), ether_hostton(), and ether_ntoa().
Referenced by ether_wake_main().
get_wol_pw()
static int get_wol_pw (const char * ethoptarg, unsigned char * wol_passwd) static
Definition at line 169 of file ether-wake.c.
 {
     unsigned passwd[6];
     int byte_cnt, i;
     /* handle MAC format */
     byte_cnt = sscanf(ethoptarg, "%2x:%2x:%2x:%2x:%2x:%2x",
                       &passwd[0], &passwd[1], &passwd[2],
                       &passwd[3], &passwd[4], &passwd[5]);
     /* handle IP format */
 // FIXME: why < 4?? should it be < 6?
     if (byte_cnt < 4)
         byte_cnt = sscanf(ethoptarg, "%u.%u.%u.%u",
                           &passwd[0], &passwd[1], &passwd[2], &passwd[3]);
     if (byte_cnt < 4) {
         bb_simple_error_msg("can't read Wake-On-LAN pass");
         return 0;
     }
 // TODO: check invalid numbers >255??
     for (i = 0; i < byte_cnt; ++i)
         wol_passwd[i] = passwd[i];
     bb_debug_msg("password: %2.2x %2.2x %2.2x %2.2x (%d)\n\n",
                  wol_passwd[0], wol_passwd[1], wol_passwd[2], wol_passwd[3],
                  byte_cnt);
     return byte_cnt;
 }
References bb_debug_msg, bb_simple_error_msg(), i, and sscanf().
Referenced by ether_wake_main().