Fennix: Kernel/include_std/stdlib.h File Reference
stdlib.h File Reference
#include <types.h>
Macros
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
Functions
START_EXTERNC void * malloc (size_t Size)
The standard function.
void * calloc (size_t n, size_t Size)
The standard function.
void * realloc (void *Address, size_t Size)
The standard function.
void free (void *Address)
The standard function.
void abort ()
Macro Definition Documentation
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 36 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 37 of file stdlib.h.
Function Documentation
abort()
void abort ()
Definition at line 22 of file stdlib.cpp.
 {
     error("abort() called");
     CPU::Stop();
     __builtin_unreachable();
 }
References __builtin_unreachable(), error, and CPU::Stop().
Referenced by __assert_fail().