Fennix: Userspace/apps/base/busybox/networking/libiproute/ll_proto.c File Reference
ll_proto.c File Reference
#include "libbb.h"
#include "rt_names.h"
#include "utils.h"
#include <netinet/if_ether.h>
Macros
#define __PF(f, n) ETH_P_##f,
#define __PF(f, n) #n "\0"
Functions
const char *FAST_FUNC ll_proto_n2a (unsigned short id, char *buf, int len)
int FAST_FUNC ll_proto_a2n (unsigned short *id, char *buf)
Variables
static const uint16_t llproto_ids[] ALIGN2
static const char llproto_names[] ALIGN1
Macro Definition Documentation
__PF [1/2]
#define __PF (f, n) ETH_P_##f,
__PF [2/2]
#define __PF (f, n) #n "\0"
Function Documentation
ll_proto_a2n()
int FAST_FUNC ll_proto_a2n (unsigned short * id, char * buf)
Definition at line 165 of file ll_proto.c.
 {
     unsigned i;
     const char *name = llproto_names;
     for (i = 0; i < ARRAY_SIZE(llproto_ids); i++) {
         if (strcasecmp(name, buf) == 0) {
             i = llproto_ids[i];
             goto good;
         }
         name += strlen(name) + 1;
     }
     errno = 0;
     i = bb_strtou(buf, NULL, 0);
     if (errno || i > 0xffff)
         return -1;
  good:
     *id = htons(i);
     return 0;
 }
References ARRAY_SIZE, bb_strtou(), buf, errno, htons(), i, NULL, strcasecmp, and strlen.
Referenced by tc_main().
ll_proto_n2a()
const char* FAST_FUNC ll_proto_n2a (unsigned short id, char * buf, int len)
Definition at line 153 of file ll_proto.c.
 {
     unsigned i;
     id = ntohs(id);
     for (i = 0; i < ARRAY_SIZE(llproto_ids); i++) {
         if (llproto_ids[i] == id)
             return nth_string(llproto_names, i);
     }
     snprintf(buf, len, "[%u]", id);
     return buf;
 }
References ARRAY_SIZE, buf, i, len, nth_string(), ntohs(), and snprintf().
Variable Documentation
ALIGN1
const char llproto_names [] ALIGN1 static
Definition at line 86 of file ll_proto.c.
ALIGN2
const uint16_t llproto_ids [] ALIGN2 static
Definition at line 18 of file ll_proto.c.