Fennix: Userspace/musl/src/stdio/ofl_add.c File Reference
ofl_add.c File Reference
#include "stdio_impl.h"
Functions
FILE * __ofl_add (FILE *f)
Function Documentation
__ofl_add()
FILE* __ofl_add (FILE * f)
Definition at line 3 of file ofl_add.c.
 {
     FILE **head = __ofl_lock();
     f->next = *head;
     if (*head) (*head)->prev = f;
     *head = f;
     __ofl_unlock();
     return f;
 }
References __ofl_lock(), __ofl_unlock(), f, and head.
Referenced by __fdopen(), fmemopen(), fopencookie(), open_memstream(), and open_wmemstream().