Fennix: Userspace/mlibc/tests/posix/pthread_schedparam.c File Reference
pthread_schedparam.c File Reference
#include <assert.h>
#include <errno.h>
#include <pthread.h>
#include <stdlib.h>
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 6 of file pthread_schedparam.c.
            {
     struct sched_param param = {
         .sched_priority = 100,
     };
     int policy = 0xDEADBEEF;
     int ret = pthread_getschedparam(pthread_self(), &policy, &param);
     assert(policy == SCHED_OTHER);
     assert(!ret);
     param.sched_priority = 10;
     ret = pthread_setschedparam(pthread_self(), SCHED_FIFO, &param);
     assert(!ret || ret == EPERM);
     if(ret == EPERM) {
         exit(0);
     }
     param.sched_priority = 0xDEADBEEF;
     ret = pthread_getschedparam(pthread_self(), &policy, &param);
     assert(policy == SCHED_FIFO);
     assert(param.sched_priority == 10);
     assert(!ret);
 }
References assert, EPERM, exit(), pthread_getschedparam(), pthread_self(), pthread_setschedparam(), ret, SCHED_FIFO, SCHED_OTHER, and sched_param::sched_priority.