Fennix Kernel: Kernel/Tasking/Scheduler.cpp File Reference
Scheduler.cpp File Reference
#include <task.hpp>
#include <dumper.hpp>
#include <convert.h>
#include <lock.hpp>
#include <printf.h>
#include <smp.hpp>
#include <io.h>
#include "../kernel.h"
Namespaces
Tasking
Macros
#define schedbg(m, ...)
#define gnap_schedbg(m, ...)
#define gnat_schedbg(m, ...)
#define fnp_schedbg(m, ...)
#define sspt_schedbg(m, ...)
#define wut_schedbg(m, ...)
Functions
NewLock (SchedulerLock)
SafeFunction NIF void TaskingScheduler_OneShot (int TimeSlice)
Macro Definition Documentation
fnp_schedbg
#define fnp_schedbg (m, ...)
Definition at line 89 of file Scheduler.cpp.
gnap_schedbg
#define gnap_schedbg (m, ...)
Definition at line 71 of file Scheduler.cpp.
gnat_schedbg
#define gnat_schedbg (m, ...)
Definition at line 80 of file Scheduler.cpp.
schedbg
#define schedbg (m, ...)
Definition at line 62 of file Scheduler.cpp.
sspt_schedbg
#define sspt_schedbg (m, ...)
Definition at line 98 of file Scheduler.cpp.
wut_schedbg
#define wut_schedbg (m, ...)
Definition at line 107 of file Scheduler.cpp.
Function Documentation
NewLock()
NewLock (SchedulerLock)
TaskingScheduler_OneShot()
SafeFunction NIF void TaskingScheduler_OneShot (int TimeSlice)
Definition at line 110 of file Scheduler.cpp.
 {
     if (TimeSlice == 0)
         TimeSlice = Tasking::TaskPriority::Normal;
 #if defined(a64)
     ((APIC::Timer *)Interrupts::apicTimer[GetCurrentCPU()->ID])->OneShot(CPU::x86::IRQ16, TimeSlice);
 #elif defined(a32)
 #elif defined(aa64)
 #endif
 }
References GetCurrentCPU(), CPUData::ID, CPU::x86::IRQ16, Tasking::Normal, and APIC::OneShot.
Referenced by Tasking::Task::Schedule(), and Tasking::Task::~Task().