Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/cephes_subr.c File Reference
cephes_subr.c File Reference
#include <complex.h>
#include <math.h>
#include "cephes_subr.h"
Macros
#define MACHEP 1.1e-16
Functions
void __mlibc_cchsh (double x, double *c, double *s)
double __mlibc_redupi (double x)
double __mlibc_ctans (double complex z)
Variables
static const double DP1 = 3.14159265160560607910E0
static const double DP2 = 1.98418714791870343106E-9
static const double DP3 = 1.14423774522196636802E-17
Macro Definition Documentation
MACHEP
#define MACHEP 1.1e-16
Definition at line 64 of file cephes_subr.c.
Function Documentation
__mlibc_cchsh()
void __mlibc_cchsh (double x, double * c, double * s)
Definition at line 42 of file cephes_subr.c.
 {
     double e, ei;
     if (fabs(x) <= 0.5) {
         *c = cosh(x);
         *s = sinh(x);
     } else {
         e = exp(x);
         ei = 0.5 / e;
         e = 0.5 * e;
         *s = e - ei;
         *c = e + ei;
     }
 }
References c, cosh(), exp(), fabs(), sinh(), and x.
Referenced by ccos(), and csin().
__mlibc_ctans()
double __mlibc_ctans (double complex z)
Definition at line 87 of file cephes_subr.c.
 {
     double f, x, x2, y, y2, rn, t;
     double d;
     x = fabs(2.0 * creal(z));
     y = fabs(2.0 * cimag(z));
     x = __mlibc_redupi(x);
     x = x * x;
     y = y * y;
     x2 = 1.0;
     y2 = 1.0;
     f = 1.0;
     rn = 0.0;
     d = 0.0;
     do {
         rn += 1.0;
         f *= rn;
         rn += 1.0;
         f *= rn;
         x2 *= x;
         y2 *= y;
         t = y2 + x2;
         t /= f;
         d += t;
         rn += 1.0;
         f *= rn;
         rn += 1.0;
         f *= rn;
         x2 *= x;
         y2 *= y;
         t = y2 - x2;
         t /= f;
         d += t;
     } while (fabs(t/d) > MACHEP);
     return d;
 }
References __mlibc_redupi(), cimag(), creal(), fabs(), MACHEP, x, and y.
Referenced by ctan().
__mlibc_redupi()
double __mlibc_redupi (double x)
Definition at line 67 of file cephes_subr.c.
 {
     double t;
     long i;
     t = x / M_PI;
     if (t >= 0.0)
         t += 0.5;
     else
         t -= 0.5;
     i = t;  /* the multiple */
     t = i;
     t = ((x - t * DP1) - t * DP2) - t * DP3;
     return t;
 }
References DP1, DP2, DP3, i, M_PI, and x.
Referenced by __mlibc_ctans(), and catan().
Variable Documentation
DP1
const double DP1 = 3.14159265160560607910E0 static
Definition at line 61 of file cephes_subr.c.
Referenced by __mlibc_redupi().
DP2
const double DP2 = 1.98418714791870343106E-9 static
Definition at line 62 of file cephes_subr.c.
Referenced by __mlibc_redupi().
DP3
const double DP3 = 1.14423774522196636802E-17 static
Definition at line 63 of file cephes_subr.c.
Referenced by __mlibc_redupi().