Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/doomgeneric.h File Reference
doomgeneric.h File Reference
#include <stdlib.h>
#include <stdint.h>
Macros
#define DOOMGENERIC_RESX 640
#define DOOMGENERIC_RESY 400
Functions
void doomgeneric_Create (int argc, char **argv)
void doomgeneric_Tick ()
void DG_Init ()
void DG_DrawFrame ()
void DG_SleepMs (uint32_t ms)
uint32_t DG_GetTicksMs ()
int DG_GetKey (int *pressed, unsigned char *key)
void DG_SetWindowTitle (const char *title)
Variables
uint32_t * DG_ScreenBuffer
Macro Definition Documentation
DOOMGENERIC_RESX
#define DOOMGENERIC_RESX 640
Definition at line 7 of file doomgeneric.h.
DOOMGENERIC_RESY
#define DOOMGENERIC_RESY 400
Definition at line 8 of file doomgeneric.h.
Function Documentation
DG_DrawFrame()
void DG_DrawFrame ()
Definition at line 69 of file doomgeneric_fennix.c.
 {
     // syscall1(sys_Print, 'H');
         // StretchDIBits(s_Hdc, 0, 0, DOOMGENERIC_RESX, DOOMGENERIC_RESY, 0, 0, DOOMGENERIC_RESX, DOOMGENERIC_RESY, DG_ScreenBuffer);
 }
Referenced by I_FinishUpdate().
DG_GetKey()
int DG_GetKey (int * pressed, unsigned char * key)
Definition at line 86 of file doomgeneric_fennix.c.
 {
     if (s_KeyQueueReadIndex == s_KeyQueueWriteIndex)
     {
         //key queue is empty
         return 0;
     }
     else
     {
         unsigned short keyData = s_KeyQueue[s_KeyQueueReadIndex];
         s_KeyQueueReadIndex++;
         s_KeyQueueReadIndex %= KEYQUEUE_SIZE;
         *pressed = keyData >> 8;
         *doomKey = keyData & 0xFF;
         return 1;
     }
 }
References KEYQUEUE_SIZE, s_KeyQueue, s_KeyQueueReadIndex, and s_KeyQueueWriteIndex.
Referenced by I_GetEvent().
DG_GetTicksMs()
uint32_t DG_GetTicksMs ()
Definition at line 80 of file doomgeneric_fennix.c.
 {
     static uint32_t stub;
     return ++stub; // TODO
 }
References stub.
Referenced by I_GetTicks().
DG_Init()
void DG_Init ()
Definition at line 64 of file doomgeneric_fennix.c.
 {
     memset(s_KeyQueue, 0, KEYQUEUE_SIZE * sizeof(unsigned short));
 }
References KEYQUEUE_SIZE, memset, and s_KeyQueue.
Referenced by doomgeneric_Create().
DG_SetWindowTitle()
void DG_SetWindowTitle (const char * title)
Definition at line 107 of file doomgeneric_fennix.c.
 {
     // for (int i = 0; i < 14; i++)
     //  syscall1(sys_Print, "Window Title: "[i]);
     // for (int i = 0; title[i] != '\0'; i++)
     // {
     //  syscall1(sys_Print, title[i]);
     // }
     // syscall1(sys_Print, '\n');
 }
Referenced by I_SetWindowTitle().
DG_SleepMs()
void DG_SleepMs (uint32_t ms)
Definition at line 75 of file doomgeneric_fennix.c.
 {
     // syscall1(sys_Sleep, ms);
 }
Referenced by I_Sleep().
doomgeneric_Create()
void doomgeneric_Create (int argc, char ** argv)
Definition at line 13 of file doomgeneric.c.
 {
     // save arguments
     myargc = argc;
     myargv = argv;
     M_FindResponseFile();
     DG_ScreenBuffer = malloc(DOOMGENERIC_RESX * DOOMGENERIC_RESY * 4);
     DG_Init();
     D_DoomMain ();
 }
References argc, argv, D_DoomMain(), DG_Init(), DG_ScreenBuffer, DOOMGENERIC_RESX, DOOMGENERIC_RESY, M_FindResponseFile(), malloc, myargc, and myargv.
Referenced by main().
doomgeneric_Tick()
void doomgeneric_Tick ()
Definition at line 405 of file d_main.c.
 {
     // frame syncronous IO operations
     I_StartFrame ();
     TryRunTics (); // will run at least one tic
     S_UpdateSounds (players[consoleplayer].mo);// move positional sounds
     // Update display, next frame, with current state.
     if (screenvisible)
     {
         D_Display ();
     }
 }
References consoleplayer, D_Display(), I_StartFrame(), players, S_UpdateSounds(), screenvisible, and TryRunTics().
Referenced by D_DoomLoop(), and main().
Variable Documentation
DG_ScreenBuffer
uint32_t* DG_ScreenBuffer extern
Definition at line 7 of file doomgeneric.c.
Referenced by doomgeneric_Create(), and I_FinishUpdate().