Fennix: Userspace/musl/include/sys/stat.h File Reference
stat.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/stat.h>
Macros
#define __NEED_dev_t
#define __NEED_ino_t
#define __NEED_mode_t
#define __NEED_nlink_t
#define __NEED_uid_t
#define __NEED_gid_t
#define __NEED_off_t
#define __NEED_time_t
#define __NEED_blksize_t
#define __NEED_blkcnt_t
#define __NEED_struct_timespec
#define st_atime st_atim.tv_sec
#define st_mtime st_mtim.tv_sec
#define st_ctime st_ctim.tv_sec
#define S_IFMT 0170000
#define S_IFDIR 0040000
#define S_IFCHR 0020000
#define S_IFBLK 0060000
#define S_IFREG 0100000
#define S_IFIFO 0010000
#define S_IFLNK 0120000
#define S_IFSOCK 0140000
#define S_TYPEISMQ(buf) 0
#define S_TYPEISSEM(buf) 0
#define S_TYPEISSHM(buf) 0
#define S_TYPEISTMO(buf) 0
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)
#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#define S_ISFIFO(mode) (((mode) & S_IFMT) == S_IFIFO)
#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)
#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)
#define S_ISUID 04000
#define S_ISGID 02000
#define S_ISVTX 01000
#define S_IRUSR 0400
#define S_IWUSR 0200
#define S_IXUSR 0100
#define S_IRWXU 0700
#define S_IRGRP 0040
#define S_IWGRP 0020
#define S_IXGRP 0010
#define S_IRWXG 0070
#define S_IROTH 0004
#define S_IWOTH 0002
#define S_IXOTH 0001
#define S_IRWXO 0007
#define UTIME_NOW 0x3fffffff
#define UTIME_OMIT 0x3ffffffe
Functions
int stat (const char *__restrict, struct stat *__restrict)
int fstat (int, struct stat *)
int lstat (const char *__restrict, struct stat *__restrict)
int fstatat (int, const char *__restrict, struct stat *__restrict, int)
int chmod (const char *, mode_t)
int fchmod (int, mode_t)
int fchmodat (int, const char *, mode_t, int)
mode_t umask (mode_t)
int mkdir (const char *, mode_t)
int mkfifo (const char *, mode_t)
int mkdirat (int, const char *, mode_t)
int mkfifoat (int, const char *, mode_t)
int futimens (int, const struct timespec[2])
int utimensat (int, const char *, const struct timespec[2], int)
Macro Definition Documentation
__NEED_blkcnt_t
#define __NEED_blkcnt_t
Definition at line 18 of file stat.h.
__NEED_blksize_t
#define __NEED_blksize_t
Definition at line 17 of file stat.h.
__NEED_dev_t
#define __NEED_dev_t
Definition at line 9 of file stat.h.
__NEED_gid_t
#define __NEED_gid_t
Definition at line 14 of file stat.h.
__NEED_ino_t
#define __NEED_ino_t
Definition at line 10 of file stat.h.
__NEED_mode_t
#define __NEED_mode_t
Definition at line 11 of file stat.h.
__NEED_nlink_t
#define __NEED_nlink_t
Definition at line 12 of file stat.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 15 of file stat.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 19 of file stat.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 16 of file stat.h.
__NEED_uid_t
#define __NEED_uid_t
Definition at line 13 of file stat.h.
S_IFBLK
#define S_IFBLK 0060000
Definition at line 33 of file stat.h.
S_IFCHR
#define S_IFCHR 0020000
Definition at line 32 of file stat.h.
S_IFDIR
#define S_IFDIR 0040000
Definition at line 31 of file stat.h.
S_IFIFO
#define S_IFIFO 0010000
Definition at line 35 of file stat.h.
S_IFLNK
#define S_IFLNK 0120000
Definition at line 36 of file stat.h.
S_IFMT
#define S_IFMT 0170000
Definition at line 29 of file stat.h.
S_IFREG
#define S_IFREG 0100000
Definition at line 34 of file stat.h.
S_IFSOCK
#define S_IFSOCK 0140000
Definition at line 37 of file stat.h.
S_IRGRP
#define S_IRGRP 0040
Definition at line 60 of file stat.h.
S_IROTH
#define S_IROTH 0004
Definition at line 64 of file stat.h.
S_IRUSR
#define S_IRUSR 0400
Definition at line 56 of file stat.h.
S_IRWXG
#define S_IRWXG 0070
Definition at line 63 of file stat.h.
S_IRWXO
#define S_IRWXO 0007
Definition at line 67 of file stat.h.
S_IRWXU
#define S_IRWXU 0700
Definition at line 59 of file stat.h.
S_ISBLK
#define S_ISBLK (mode) (((mode) & S_IFMT) == S_IFBLK)
Definition at line 46 of file stat.h.
S_ISCHR
#define S_ISCHR (mode) (((mode) & S_IFMT) == S_IFCHR)
Definition at line 45 of file stat.h.
S_ISDIR
#define S_ISDIR (mode) (((mode) & S_IFMT) == S_IFDIR)
Definition at line 44 of file stat.h.
S_ISFIFO
#define S_ISFIFO (mode) (((mode) & S_IFMT) == S_IFIFO)
Definition at line 48 of file stat.h.
S_ISGID
#define S_ISGID 02000
Definition at line 54 of file stat.h.
S_ISLNK
#define S_ISLNK (mode) (((mode) & S_IFMT) == S_IFLNK)
Definition at line 49 of file stat.h.
S_ISREG
#define S_ISREG (mode) (((mode) & S_IFMT) == S_IFREG)
Definition at line 47 of file stat.h.
S_ISSOCK
#define S_ISSOCK (mode) (((mode) & S_IFMT) == S_IFSOCK)
Definition at line 50 of file stat.h.
S_ISUID
#define S_ISUID 04000
Definition at line 53 of file stat.h.
S_ISVTX
#define S_ISVTX 01000
Definition at line 55 of file stat.h.
S_IWGRP
#define S_IWGRP 0020
Definition at line 61 of file stat.h.
S_IWOTH
#define S_IWOTH 0002
Definition at line 65 of file stat.h.
S_IWUSR
#define S_IWUSR 0200
Definition at line 57 of file stat.h.
S_IXGRP
#define S_IXGRP 0010
Definition at line 62 of file stat.h.
S_IXOTH
#define S_IXOTH 0001
Definition at line 66 of file stat.h.
S_IXUSR
#define S_IXUSR 0100
Definition at line 58 of file stat.h.
S_TYPEISMQ
#define S_TYPEISMQ (buf) 0
Definition at line 39 of file stat.h.
S_TYPEISSEM
#define S_TYPEISSEM (buf) 0
Definition at line 40 of file stat.h.
S_TYPEISSHM
#define S_TYPEISSHM (buf) 0
Definition at line 41 of file stat.h.
S_TYPEISTMO
#define S_TYPEISTMO (buf) 0
Definition at line 42 of file stat.h.
st_atime
#define st_atime st_atim.tv_sec
Definition at line 25 of file stat.h.
st_ctime
#define st_ctime st_ctim.tv_sec
Definition at line 27 of file stat.h.
st_mtime
#define st_mtime st_mtim.tv_sec
Definition at line 26 of file stat.h.
UTIME_NOW
#define UTIME_NOW 0x3fffffff
Definition at line 70 of file stat.h.
UTIME_OMIT
#define UTIME_OMIT 0x3ffffffe
Definition at line 71 of file stat.h.
Function Documentation
chmod()
int chmod (const char * path, mode_t mode)
Definition at line 5 of file chmod.c.
 {
 #ifdef SYS_chmod
     return syscall(SYS_chmod, path, mode);
 #else
     return syscall(SYS_fchmodat, AT_FDCWD, path, mode);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by action_permissions(), adduser_main(), bb_make_directory(), copy_file(), copy_inode(), create_socket(), data_extract_all(), fileAction(), install_main(), make_device(), make_path(), processorstop(), and shred_main().
fchmod()
int fchmod (int fd, mode_t mode)
Definition at line 6 of file fchmod.c.
 {
     int ret = __syscall(SYS_fchmod, fd, mode);
     if (ret != -EBADF || __syscall(SYS_fcntl, fd, F_GETFD) < 0)
         return __syscall_ret(ret);
     char buf[15+3*sizeof(int)];
     __procfdname(buf, fd);
 #ifdef SYS_chmod
     return syscall(SYS_chmod, buf, mode);
 #else
     return syscall(SYS_fchmodat, AT_FDCWD, buf, mode);
 #endif
 }
References __procfdname(), __syscall, __syscall_ret(), AT_FDCWD, buf, EBADF, F_GETFD, fd, and syscall().
Referenced by convert(), copy_tempfile(), here_document_to_fd(), logdir_close(), logdir_open(), login_main(), lpd_main(), mesg_main(), open_tty(), patch_main(), rotate(), sed_main(), and update_passwd().
fchmodat()
int fchmodat (int fd, const char * path, mode_t mode, int flag)
Definition at line 6 of file fchmodat.c.
 {
     if (!flag) return syscall(SYS_fchmodat, fd, path, mode, flag);
     if (flag != AT_SYMLINK_NOFOLLOW)
         return __syscall_ret(-EINVAL);
     struct stat st;
     int ret, fd2;
     char proc[15+3*sizeof(int)];
     if (fstatat(fd, path, &st, flag))
         return -1;
     if (S_ISLNK(st.st_mode))
         return __syscall_ret(-EOPNOTSUPP);
     if ((fd2 = __syscall(SYS_openat, fd, path, O_RDONLY|O_PATH|O_NOFOLLOW|O_NOCTTY|O_CLOEXEC)) < 0) {
         if (fd2 == -ELOOP)
             return __syscall_ret(-EOPNOTSUPP);
         return __syscall_ret(fd2);
     }
     __procfdname(proc, fd2);
     ret = stat(proc, &st);
     if (!ret) {
         if (S_ISLNK(st.st_mode)) ret = __syscall_ret(-EOPNOTSUPP);
         else ret = syscall(SYS_fchmodat, AT_FDCWD, proc, mode);
     }
     __syscall(SYS_close, fd2);
     return ret;
 }
References __procfdname(), __syscall, __syscall_ret(), AT_FDCWD, AT_SYMLINK_NOFOLLOW, EINVAL, ELOOP, EOPNOTSUPP, fd, fstatat(), O_CLOEXEC, O_NOCTTY, O_NOFOLLOW, O_PATH, O_RDONLY, S_ISLNK, stat(), and syscall().
Referenced by lchmod().
fstat()
int fstat (int fd, struct stat * statbuf)
Definition at line 110 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_fstat(fd, statbuf);
     return ret;
 }
fstatat()
int fstatat (int , const char * __restrict, struct stat * __restrict, int)
Referenced by __fstatat_time32(), __fxstatat(), fchmodat(), lstat(), and stat().
futimens()
int futimens (int fd, const struct timespec times[2])
Definition at line 3 of file futimens.c.
 {
     return utimensat(fd, 0, times, 0);
 }
References fd, times(), and utimensat().
Referenced by __futimens_time32(), futimes(), and touch_main().
lstat()
int lstat (const char * __restrict, struct stat * __restrict)
Definition at line 121 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_lstat(pathname, statbuf);
     return ret;
 }
mkdir()
int mkdir (const char * path, mode_t mode)
Definition at line 5 of file sys_stat.c.
 {
     return 0;
 }
References AT_FDCWD, and syscall().
Referenced by make_path(), and mkdir_builtin().
mkdirat()
int mkdirat (int fd, const char * path, mode_t mode)
Definition at line 4 of file mkdirat.c.
 {
     return syscall(SYS_mkdirat, fd, path, mode);
 }
References fd, and syscall().
mkfifo()
int mkfifo (const char * path, mode_t mode)
Definition at line 3 of file mkfifo.c.
 {
     return mknod(path, mode | S_IFIFO, 0);
 }
References mknod(), and S_IFIFO.
Referenced by mkfifo_builtin(), mkfifo_main(), open_control(), and runsv_main().
mkfifoat()
int mkfifoat (int fd, const char * path, mode_t mode)
Definition at line 3 of file mkfifoat.c.
 {
     return mknodat(fd, path, mode | S_IFIFO, 0);
 }
References fd, mknodat(), and S_IFIFO.
stat()
int stat (const char * __restrict, struct stat * __restrict)
Definition at line 99 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_stat(pathname, statbuf);
     return ret;
 }
umask()
mode_t umask (mode_t mode)
Definition at line 4 of file umask.c.
 {
     return syscall(SYS_umask, mode);
 }
References syscall().
Referenced by adduser_main(), bb_make_directory(), bb_parse_mode(), copy_file(), devfsd_main(), getopt_mk_fifo_nod(), make_path(), mdev_main(), mkdir_builtin(), mkdir_recursive(), mkfifo_builtin(), passwd_main(), run_parts_main(), seedrng_main(), umaskcmd(), uuencode_main(), and xmkpath().
utimensat()
int utimensat (int fd, const char * path, const struct timespec times[2], int flags)
Definition at line 10 of file utimensat.c.
 {
     int r;
     if (times && times[0].tv_nsec==UTIME_NOW && times[1].tv_nsec==UTIME_NOW)
         times = 0;
 #ifdef SYS_utimensat_time64
     r = -ENOSYS;
     time_t s0=0, s1=0;
     long ns0=0, ns1=0;
     if (times) {
         ns0 = times[0].tv_nsec;
         ns1 = times[1].tv_nsec;
         if (!NS_SPECIAL(ns0)) s0 = times[0].tv_sec;
         if (!NS_SPECIAL(ns1)) s1 = times[1].tv_sec;
     }
     if (SYS_utimensat == SYS_utimensat_time64 || !IS32BIT(s0) || !IS32BIT(s1))
         r = __syscall(SYS_utimensat_time64, fd, path, times ?
             ((long long[]){s0, ns0, s1, ns1}) : 0, flags);
     if (SYS_utimensat == SYS_utimensat_time64 || r!=-ENOSYS)
         return __syscall_ret(r);
     if (!IS32BIT(s0) || !IS32BIT(s1))
         return __syscall_ret(-ENOTSUP);
     r = __syscall(SYS_utimensat, fd, path,
         times ? ((long[]){s0, ns0, s1, ns1}) : 0, flags);
 #else
     r = __syscall(SYS_utimensat, fd, path, times, flags);
 #endif
 #ifdef SYS_futimesat
     if (r != -ENOSYS || flags) return __syscall_ret(r);
     long *tv=0, tmp[4];
     if (times) {
         int i;
         tv = tmp;
         for (i=0; i<2; i++) {
             if (times[i].tv_nsec >= 1000000000ULL) {
                 if (NS_SPECIAL(times[i].tv_nsec))
                     return __syscall_ret(-ENOSYS);
                 return __syscall_ret(-EINVAL);
             }
             tmp[2*i+0] = times[i].tv_sec;
             tmp[2*i+1] = times[i].tv_nsec / 1000;
         }
     }
     r = __syscall(SYS_futimesat, fd, path, tv);
     if (r != -ENOSYS || fd != AT_FDCWD) return __syscall_ret(r);
     r = __syscall(SYS_utimes, path, tv);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), AT_FDCWD, EINVAL, ENOSYS, ENOTSUP, fd, flags, i, IS32BIT, NS_SPECIAL, s0, s1, SYS_utimensat, SYS_utimensat_time64, times(), and UTIME_NOW.
Referenced by __futimesat(), __utimensat_time32(), futimens(), lutimes(), touch_main(), and utime().