Fennix: Userspace/mlibc/options/posix/include/sys/wait.h File Reference
wait.h File Reference
#include <bits/posix/id_t.h>
#include <abi-bits/pid_t.h>
#include <abi-bits/signal.h>
#include <abi-bits/wait.h>
Enumerations
enum idtype_t { P_ALL , P_PID , P_PGID }
Functions
pid_t wait (int *status)
int waitid (idtype_t idtype, id_t id, siginfo_t *siginfo, int flags)
pid_t waitpid (pid_t pid, int *status, int flags)
pid_t wait3 (int *, int, struct rusage *)
pid_t wait4 (pid_t pid, int *status, int options, struct rusage *ru)
Enumeration Type Documentation
idtype_t
enum idtype_t
Enumerator
P_ALL
P_PID
P_PGID
Definition at line 19 of file wait.h.
              {
     P_ALL, P_PID, P_PGID
 } idtype_t;
Function Documentation
wait()
pid_t wait (int * status)
Definition at line 29 of file sys-wait-stubs.cpp.
{
     return waitpid(-1, status, 0);
 }
References mlibc::status, and waitpid().
Referenced by main().
wait3()
pid_t wait3 (int * status, int options, struct rusage * rusage)
Definition at line 33 of file sys-wait-stubs.cpp.
{
     (void) rusage;
     mlibc::infoLogger() << "\e[31mmlibc: wait3() is not implemented correctly\e[39m"
         << frg::endlog;
     return waitpid(-1, status, options);
 }
References mlibc::infoLogger, options, mlibc::status, Driver::void(), and waitpid().
wait4()
pid_t wait4 (pid_t pid, int * status, int options, struct rusage * ru)
Definition at line 40 of file sys-wait-stubs.cpp.
{
     pid_t ret;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_waitpid, -1);
     if(int e = mlibc::sys_waitpid(pid, status, options, ru, &ret); e) {
         errno = e;
         return -1;
     }
     return ret;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, options, ret, mlibc::ru, mlibc::status, and mlibc::sys_waitpid().
waitid()
int waitid (idtype_t idtype, id_t id, siginfo_t * siginfo, int flags)
Definition at line 10 of file sys-wait-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
waitpid()
pid_t waitpid (pid_t pid, int * status, int flags)
Definition at line 15 of file sys-wait-stubs.cpp.
{
     pid_t ret;
     int tmp_status = 0;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_waitpid, -1);
     if(int e = mlibc::sys_waitpid(pid, &tmp_status, flags, NULL, &ret); e) {
         errno = e;
         return -1;
     }
     if(status) {
         *status = tmp_status;
     }
     return ret;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, NULL, ret, mlibc::status, and mlibc::sys_waitpid().
Referenced by main(), parent_fn(), posix_spawn(), run_cmd(), wait(), wait3(), and we_askshell().