Fennix: Userspace/musl/src/env/putenv.c File Reference
putenv.c File Reference
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
static void dummy (char *old, char *new)
weak_alias (dummy, __env_rm_add)
int __putenv (char *s, size_t l, char *r)
int putenv (char *s)
Function Documentation
__putenv()
int __putenv (char * s, size_t l, char * r)
Definition at line 8 of file putenv.c.
 {
     size_t i=0;
     if (__environ) {
         for (char **e = __environ; *e; e++, i++)
             if (!strncmp(s, *e, l+1)) {
                 char *tmp = *e;
                 *e = s;
                 __env_rm_add(tmp, r);
                 return 0;
             }
     }
     static char **oldenv;
     char **newenv;
     if (__environ == oldenv) {
         newenv = realloc(oldenv, sizeof *newenv * (i+2));
         if (!newenv) goto oom;
     } else {
         newenv = malloc(sizeof *newenv * (i+2));
         if (!newenv) goto oom;
         if (i) memcpy(newenv, __environ, sizeof *newenv * i);
         free(oldenv);
     }
     newenv[i] = s;
     newenv[i+1] = 0;
     __environ = oldenv = newenv;
     if (r) __env_rm_add(0, r);
     return 0;
 oom:
     free(r);
     return -1;
 }
References __env_rm_add(), __environ, free, i, l, malloc, memcpy, realloc, s, and strncmp().
Referenced by putenv(), and setenv().
dummy()
static void dummy (char * old, char * new) static
Definition at line 5 of file putenv.c.
 {}
putenv()
int putenv (char * s)
Definition at line 41 of file putenv.c.
 {
     size_t l = __strchrnul(s, '=') - s;
     if (!l || !s[l]) return unsetenv(s);
     return __putenv(s, l, 0);
 }
References __putenv(), __strchrnul(), l, s, and unsetenv().
Referenced by add_vars(), bootchartd_main(), console_init(), date_main(), env_main(), fileAction(), fill_envp(), handle_incoming_and_exit(), httpd_main(), hush_main(), init_main(), initial_scan(), login_main(), make_device(), man_main(), putenvp(), rtc_tm2time(), run(), run_script(), safe_setenv(), sanitize_env_if_suid(), set_local_var(), sh_set_lines_and_columns(), tar_main(), tryexec(), ts_main(), uevent_main(), xputenv(), xsetenv_plain(), and xsetenv_proto().
weak_alias()
weak_alias (dummy , __env_rm_add)