Fennix: Userspace/apps/base/busybox/sysklogd/klogd.c File Reference
klogd.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <syslog.h>
Macros
#define PATH_PRINTK "/proc/sys/kernel/printk"
#define READ_ERROR "read error"
#define log_buffer bb_common_bufsiz1
Enumerations
enum { klogfd = 3 }
enum { KLOGD_LOGBUF_SIZE = COMMON_BUFSIZE , OPT_LEVEL = (1 << 0) , OPT_FOREGROUND = (1 << 1) }
Functions
static void klogd_open (void)
static void klogd_setloglevel (int lvl)
static int klogd_read (char *bufp, int len)
static void klogd_close (void)
int klogd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
log_buffer
#define log_buffer bb_common_bufsiz1
Definition at line 149 of file klogd.c.
PATH_PRINTK
#define PATH_PRINTK "/proc/sys/kernel/printk"
Definition at line 109 of file klogd.c.
READ_ERROR
#define READ_ERROR "read error"
Definition at line 138 of file klogd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
klogfd
Definition at line 111 of file klogd.c.
 { klogfd = 3 };
anonymous enum
anonymous enum
Enumerator
KLOGD_LOGBUF_SIZE
OPT_LEVEL
OPT_FOREGROUND
Definition at line 150 of file klogd.c.
      {
     KLOGD_LOGBUF_SIZE = COMMON_BUFSIZE,
     OPT_LEVEL      = (1 << 0),
     OPT_FOREGROUND = (1 << 1),
 };
Function Documentation
klogd_close()
static void klogd_close (void) static
Definition at line 140 of file klogd.c.
 {
     klogd_setloglevel(7);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(klogfd);
 }
References close(), klogd_setloglevel(), and klogfd.
Referenced by klogd_main().
klogd_main()
int klogd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 170 of file klogd.c.
 {
     int i = 0;
     char *opt_c;
     int opt;
     int used;
     setup_common_bufsiz();
     opt = getopt32(argv, "c:n", &opt_c);
     if (opt & OPT_LEVEL) {
         /* Valid levels are between 1 and 8 */
         i = xatou_range(opt_c, 1, 8);
     }
     if (!(opt & OPT_FOREGROUND)) {
         bb_daemonize_or_rexec(DAEMON_CHDIR_ROOT, argv);
     }
     logmode = LOGMODE_SYSLOG;
     /* klogd_open() before openlog(), since it might use fixed fd 3,
      * and openlog() also may use the same fd 3 if we swap them:
      */
     klogd_open();
     openlog("kernel", 0, LOG_KERN);
     /*
      * glibc problem: for some reason, glibc changes LOG_KERN to LOG_USER
      * above. The logic behind this is that standard
      * http://pubs.opengroup.org/onlinepubs/9699919799/functions/syslog.html
      * says the following about openlog and syslog:
      * "LOG_USER
      *  Messages generated by arbitrary processes.
      *  This is the default facility identifier if none is specified."
      *
      * I believe glibc misinterpreted this text as "if openlog's
      * third parameter is 0 (=LOG_KERN), treat it as LOG_USER".
      * Whereas it was meant to say "if *syslog* is called with facility
      * 0 in its 1st parameter without prior call to openlog, then perform
      * implicit openlog(LOG_USER)".
      *
      * As a result of this, eh, feature, standard klogd was forced
      * to open-code its own openlog and syslog implementation (!).
      *
      * Note that prohibiting openlog(LOG_KERN) on libc level does not
      * add any security: any process can open a socket to "/dev/log"
      * and write a string "<0>Voila, a LOG_KERN + LOG_EMERG message"
      *
      * Google code search tells me there is no widespread use of
      * openlog("foo", 0, 0), thus fixing glibc won't break userspace.
      *
      * The bug against glibc was filed:
      * bugzilla.redhat.com/show_bug.cgi?id=547000
      */
     if (i)
         klogd_setloglevel(i);
     signal(SIGHUP, SIG_IGN);
     /* We want klogd_read to not be restarted, thus _norestart: */
     bb_signals_norestart(BB_FATAL_SIGS, record_signo);
     syslog(LOG_NOTICE, "klogd started: %s", bb_banner);
     write_pidfile_std_path_and_ext("klogd");
     used = 0;
     while (!bb_got_signal) {
         int n;
         int priority;
         char *start;
         start = log_buffer + used;
         n = klogd_read(start, KLOGD_LOGBUF_SIZE-1 - used);
         if (n < 0) {
             if (errno == EINTR)
                 continue;
             bb_simple_perror_msg(READ_ERROR);
             break;
         }
         start[n] = '\0';
         /* Process each newline-terminated line in the buffer */
         start = log_buffer;
         while (1) {
             char *newline = strchrnul(start, '\n');
             if (*newline == '\0') {
                 /* This line is incomplete */
                 /* move it to the front of the buffer */
                 overlapping_strcpy(log_buffer, start);
                 used = newline - start;
                 if (used < KLOGD_LOGBUF_SIZE-1) {
                     /* buffer isn't full */
                     break;
                 }
                 /* buffer is full, log it anyway */
                 used = 0;
                 newline = NULL;
             } else {
                 *newline++ = '\0';
             }
             /* Extract the priority */
             priority = LOG_INFO;
             if (*start == '<') {
                 start++;
                 if (*start) {
                     char *end;
                     priority = strtoul(start, &end, 10);
                     if (*end == '>')
                         end++;
                     start = end;
                 }
             }
             /* Log (only non-empty lines) */
             if (*start)
                 syslog(priority, "%s", start);
             if (!newline)
                 break;
             start = newline;
         }
     }
     klogd_close();
     syslog(LOG_NOTICE, "klogd: exiting");
     remove_pidfile_std_path_and_ext("klogd");
     if (bb_got_signal)
         kill_myself_with_sig(bb_got_signal);
     return EXIT_FAILURE;
 }
References argv, bb_daemonize_or_rexec, BB_FATAL_SIGS, bb_got_signal, bb_signals_norestart(), bb_simple_perror_msg(), DAEMON_CHDIR_ROOT, EINTR, end, errno, EXIT_FAILURE, getopt32(), i, kill_myself_with_sig(), klogd_close(), KLOGD_LOGBUF_SIZE, klogd_open(), klogd_read(), klogd_setloglevel(), log_buffer, LOG_INFO, LOG_KERN, LOG_NOTICE, logmode, LOGMODE_SYSLOG, n, newline(), NULL, openlog(), opt, OPT_FOREGROUND, OPT_LEVEL, overlapping_strcpy(), READ_ERROR, record_signo(), remove_pidfile_std_path_and_ext(), SIG_IGN, SIGHUP, signal, start, strchrnul(), strtoul(), syslog(), and write_pidfile_std_path_and_ext().
klogd_open()
static void klogd_open (void) static
Definition at line 113 of file klogd.c.
 {
     int fd = xopen(_PATH_KLOG, O_RDONLY);
     xmove_fd(fd, klogfd);
 }
References _PATH_KLOG, fd, klogfd, O_RDONLY, xmove_fd(), and xopen().
Referenced by klogd_main().
klogd_read()
static int klogd_read (char * bufp, int len) static
Definition at line 134 of file klogd.c.
 {
     return read(klogfd, bufp, len);
 }
References klogfd, len, and read().
Referenced by klogd_main().
klogd_setloglevel()
static void klogd_setloglevel (int lvl) static
Definition at line 119 of file klogd.c.
 {
     FILE *fp = fopen_or_warn(PATH_PRINTK, "w");
     if (fp) {
         /* This changes only first value:
          * "messages with a higher priority than this
          * [that is, with numerically lower value]
          * will be printed to the console".
          * The other three values in this pseudo-file aren't changed.
          */
         fprintf(fp, "%u\n", lvl);
         fclose(fp);
     }
 }
References fclose(), fopen_or_warn(), fprintf(), and PATH_PRINTK.
Referenced by klogd_close(), and klogd_main().