Fennix: Userspace/musl/arch/microblaze/atomic_arch.h File Reference
atomic_arch.h File Reference
Macros
#define a_cas a_cas
#define a_swap a_swap
#define a_fetch_add a_fetch_add
Functions
static int a_cas (volatile int *p, int t, int s)
static int a_swap (volatile int *x, int v)
static int a_fetch_add (volatile int *x, int v)
Macro Definition Documentation
a_cas
#define a_cas a_cas
Definition at line 1 of file atomic_arch.h.
a_fetch_add
#define a_fetch_add a_fetch_add
Definition at line 37 of file atomic_arch.h.
a_swap
#define a_swap a_swap
Definition at line 20 of file atomic_arch.h.
Function Documentation
a_cas()
static int a_cas (volatile int * p, int t, int s) inline static
Definition at line 2 of file atomic_arch.h.
 {
     register int old, tmp;
     __asm__ __volatile__ (
         "   addi %0, r0, 0\n"
         "1: lwx %0, %2, r0\n"
         "   rsubk %1, %0, %3\n"
         "   bnei %1, 1f\n"
         "   swx %4, %2, r0\n"
         "   addic %1, r0, 0\n"
         "   bnei %1, 1b\n"
         "1: "
         : "=&r"(old), "=&r"(tmp)
         : "r"(p), "r"(t), "r"(s)
         : "cc", "memory" );
     return old;
 }
References __asm__(), p, and t.
a_fetch_add()
static int a_fetch_add (volatile int * x, int v) inline static
Definition at line 38 of file atomic_arch.h.
 {
     register int new, tmp;
     __asm__ __volatile__ (
         "   addi %0, r0, 0\n"
         "1: lwx %0, %2, r0\n"
         "   addk %0, %0, %3\n"
         "   swx %0, %2, r0\n"
         "   addic %1, r0, 0\n"
         "   bnei %1, 1b\n"
         "1: "
         : "=&r"(new), "=&r"(tmp)
         : "r"(x), "r"(v)
         : "cc", "memory" );
     return new-v;
 }
References __asm__(), and x.
a_swap()
static int a_swap (volatile int * x, int v) inline static
Definition at line 21 of file atomic_arch.h.
 {
     register int old, tmp;
     __asm__ __volatile__ (
         "   addi %0, r0, 0\n"
         "1: lwx %0, %2, r0\n"
         "   swx %3, %2, r0\n"
         "   addic %1, r0, 0\n"
         "   bnei %1, 1b\n"
         "1: "
         : "=&r"(old), "=&r"(tmp)
         : "r"(x), "r"(v)
         : "cc", "memory" );
     return old;
 }
References __asm__(), and x.