Fennix: Userspace/musl/arch/x86_64/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x) (x)
#define __SYSCALL_LL_O(x) (x)
#define VDSO_USEFUL
#define VDSO_CGT_SYM "__vdso_clock_gettime"
#define VDSO_CGT_VER "LINUX_2.6"
#define VDSO_GETCPU_SYM "__vdso_getcpu"
#define VDSO_GETCPU_VER "LINUX_2.6"
#define IPC_64 0
Functions
static __inline long __syscall0 (long n)
static __inline long __syscall1 (long n, long a1)
static __inline long __syscall2 (long n, long a1, long a2)
static __inline long __syscall3 (long n, long a1, long a2, long a3)
static __inline long __syscall4 (long n, long a1, long a2, long a3, long a4)
static __inline long __syscall5 (long n, long a1, long a2, long a3, long a4, long a5)
static __inline long __syscall6 (long n, long a1, long a2, long a3, long a4, long a5, long a6)
Macro Definition Documentation
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x) (x)
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) (x)
Definition at line 2 of file syscall_arch.h.
IPC_64
#define IPC_64 0
Definition at line 70 of file syscall_arch.h.
VDSO_CGT_SYM
#define VDSO_CGT_SYM "__vdso_clock_gettime"
Definition at line 65 of file syscall_arch.h.
VDSO_CGT_VER
#define VDSO_CGT_VER "LINUX_2.6"
Definition at line 66 of file syscall_arch.h.
VDSO_GETCPU_SYM
#define VDSO_GETCPU_SYM "__vdso_getcpu"
Definition at line 67 of file syscall_arch.h.
VDSO_GETCPU_VER
#define VDSO_GETCPU_VER "LINUX_2.6"
Definition at line 68 of file syscall_arch.h.
VDSO_USEFUL
#define VDSO_USEFUL
Definition at line 64 of file syscall_arch.h.
Function Documentation
__syscall0()
static __inline long __syscall0 (long n) static
Definition at line 4 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), n, and ret.
__syscall1()
static __inline long __syscall1 (long n, long a1) static
Definition at line 11 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, n, and ret.
__syscall2()
static __inline long __syscall2 (long n, long a1, long a2) static
Definition at line 18 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2)
                           : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, n, and ret.
__syscall3()
static __inline long __syscall3 (long n, long a1, long a2, long a3) static
Definition at line 26 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                           "d"(a3) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, n, and ret.
__syscall4()
static __inline long __syscall4 (long n, long a1, long a2, long a3, long a4) static
Definition at line 34 of file syscall_arch.h.
 {
     unsigned long ret;
     register long r10 __asm__("r10") = a4;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                           "d"(a3), "r"(r10): "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, a4, n, and ret.
__syscall5()
static __inline long __syscall5 (long n, long a1, long a2, long a3, long a4, long a5) static
Definition at line 43 of file syscall_arch.h.
 {
     unsigned long ret;
     register long r10 __asm__("r10") = a4;
     register long r8 __asm__("r8") = a5;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                           "d"(a3), "r"(r10), "r"(r8) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, a4, a5, n, and ret.
__syscall6()
static __inline long __syscall6 (long n, long a1, long a2, long a3, long a4, long a5, long a6) static
Definition at line 53 of file syscall_arch.h.
 {
     unsigned long ret;
     register long r10 __asm__("r10") = a4;
     register long r8 __asm__("r8") = a5;
     register long r9 __asm__("r9") = a6;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                           "d"(a3), "r"(r10), "r"(r8), "r"(r9) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, a4, a5, a6, n, and ret.