Fennix: Userspace/apps/base/busybox/networking/ssl_client.c File Reference
ssl_client.c File Reference
#include "libbb.h"
Functions
int ssl_client_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
ssl_client_main()
int ssl_client_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 24 of file ssl_client.c.
 {
     tls_state_t *tls;
     const char *sni = NULL;
     int opt;
     // INIT_G();
     tls = new_tls_state();
     opt = getopt32(argv, "es:+r:+n:", &tls->ofd, &tls->ifd, &sni);
     if (!(opt & (1<<2))) {
         /* -r N defaults to -s N */
         tls->ifd = tls->ofd;
     }
     if (!(opt & (3<<1))) {
         if (!argv[1])
             bb_show_usage();
         /* Undocumented debug feature: without -s and -r, takes HOST arg and connects to it */
         //
         // Talk to kernel.org:
         // printf "GET / HTTP/1.1\r\nHost: kernel.org\r\n\r\n" | busybox ssl_client kernel.org
         if (!sni)
             sni = argv[1];
         tls->ifd = tls->ofd = create_and_connect_stream_or_die(argv[1], 443);
     }
     tls_handshake(tls, sni);
     BUILD_BUG_ON(TLSLOOP_EXIT_ON_LOCAL_EOF != 1);
     tls_run_copy_loop(tls, /*flags*/ opt & 1);
     return EXIT_SUCCESS;
 }
References argv, bb_show_usage(), BUILD_BUG_ON, create_and_connect_stream_or_die(), EXIT_SUCCESS, getopt32(), tls_state::ifd, new_tls_state(), NULL, tls_state::ofd, opt, tls_handshake(), tls_run_copy_loop(), and TLSLOOP_EXIT_ON_LOCAL_EOF.