Fennix: Userspace/apps/base/bash/examples/loadables/pathchk.c File Reference
pathchk.c File Reference
#include <config.h>
#include <sys/types.h>
#include "posixstat.h"
#include "bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "stdc.h"
#include "bashgetopt.h"
#include "maxpath.h"
#include "common.h"
Macros
#define _POSIX_PATH_MAX 255
#define _POSIX_NAME_MAX 14
#define PATH_MAX_FOR(p) PATH_MAX
#define NAME_MAX_FOR(p) NAME_MAX
#define SAFE_STAT(name, buf) stat (name, buf)
Functions
char * strerror ()
static int validate_path ()
int pathchk_builtin (WORD_LIST *list)
static int portable_chars_only (char *path) const
static int dir_ok (char *path) const
static char * xstrdup (char *s)
static int validate_path (char *path, int portability)
Variables
int errno
char * pathchk_doc []
struct builtin pathchk_struct
static char const portable_chars [256]
Macro Definition Documentation
_POSIX_NAME_MAX
#define _POSIX_NAME_MAX 14
Definition at line 76 of file pathchk.c.
_POSIX_PATH_MAX
#define _POSIX_PATH_MAX 255
Definition at line 73 of file pathchk.c.
NAME_MAX_FOR
#define NAME_MAX_FOR (p) NAME_MAX
Definition at line 94 of file pathchk.c.
PATH_MAX_FOR
#define PATH_MAX_FOR (p) PATH_MAX
Definition at line 90 of file pathchk.c.
SAFE_STAT
#define SAFE_STAT (name, buf) stat (name, buf)
Definition at line 205 of file pathchk.c.
Function Documentation
dir_ok()
static int dir_ok (char * path) const static
Definition at line 227 of file pathchk.c.
 {
   struct stat stats;
   if (SAFE_STAT (path, &stats))
     return 2;
   if (!S_ISDIR (stats.st_mode))
     {
       builtin_error ("`%s' is not a directory", path);
       return 0;
     }
   /* Use access to test for search permission because
      testing permission bits of st_mode can lose with new
      access control mechanisms.  Of course, access loses if you're
      running setuid. */
   if (access (path, X_OK) != 0)
     {
       if (errno == EACCES)
     builtin_error ("directory `%s' is not searchable", path);
       else
     builtin_error ("%s: %s", path, strerror (errno));
       return 0;
     }
   return 1;
 }
References access(), builtin_error(), EACCES, errno, S_ISDIR, SAFE_STAT, stat::st_mode, strerror(), and X_OK.
Referenced by validate_path().
pathchk_builtin()
int pathchk_builtin (WORD_LIST * list)
Definition at line 102 of file pathchk.c.
 {
   int retval, pflag, opt;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "p")) != -1)
     {
       switch (opt)
     {
     case 'p':
       pflag = 1;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   for (retval = 0; list; list = list->next)
     retval |= validate_path (list->word->word, pflag);
   return (retval ? EXECUTION_FAILURE : EXECUTION_SUCCESS);
 }
References builtin_usage(), CASE_HELPOPT, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, internal_getopt(), loptend, word_list::next, reset_internal_getopt(), retval, validate_path(), word_desc::word, and word_list::word.
portable_chars_only()
static int portable_chars_only (char * path) const static
Definition at line 188 of file pathchk.c.
 {
   const char *p;
   for (p = path; *p; ++p)
     if (portable_chars[(const unsigned char) *p] == 0)
       {
     builtin_error ("path `%s' contains nonportable character `%c'", path, *p);
     return 0;
       }
   return 1;
 }
References builtin_error(), p, and portable_chars.
Referenced by validate_path().
strerror()
char* strerror ()
Referenced by dir_ok().
validate_path() [1/2]
static int validate_path () static
Referenced by pathchk_builtin().
validate_path() [2/2]
static int validate_path (char * path, int portability) static
Definition at line 279 of file pathchk.c.
 {
   int path_max;
   int last_elem;        /* Nonzero if checking last element of path. */
   int exists;           /* 2 if the path element exists.  */
   char *slash;
   char *parent;         /* Last existing leading directory so far.  */
   if (portability && !portable_chars_only (path))
     return 1;
   if (*path == '\0')
     return 0;
 #ifdef lint
   /* Suppress `used before initialized' warning.  */
   exists = 0;
 #endif
   /* Figure out the parent of the first element in PATH.  */
   parent = xstrdup (*path == '/' ? "/" : ".");
   slash = path;
   last_elem = 0;
   while (1)
     {
       int name_max;
       int length;       /* Length of partial path being checked. */
       char *start;      /* Start of path element being checked. */
       /* Find the end of this element of the path.
      Then chop off the rest of the path after this element. */
       while (*slash == '/')
     slash++;
       start = slash;
       slash = strchr (slash, '/');
       if (slash != NULL)
     *slash = '\0';
       else
     {
       last_elem = 1;
       slash = strchr (start, '\0');
     }
       if (!last_elem)
     {
       exists = dir_ok (path);
       if (exists == 0)
         {
           free (parent);
           return 1;
         }
     }
       length = slash - start;
       /* Since we know that `parent' is a directory, it's ok to call
      pathconf with it as the argument.  (If `parent' isn't a directory
      or doesn't exist, the behavior of pathconf is undefined.)
      But if `parent' is a directory and is on a remote file system,
      it's likely that pathconf can't give us a reasonable value
      and will return -1.  (NFS and tempfs are not POSIX . . .)
      In that case, we have no choice but to assume the pessimal
      POSIX minimums.  */
       name_max = portability ? _POSIX_NAME_MAX : NAME_MAX_FOR (parent);
       if (name_max < 0)
     name_max = _POSIX_NAME_MAX;
       if (length > name_max)
     {
       builtin_error ("name `%s' has length %d; exceeds limit of %d",
          start, length, name_max);
       free (parent);
       return 1;
     }
       if (last_elem)
     break;
       if (exists == 1)
     {
       free (parent);
       parent = xstrdup (path);
     }
       *slash++ = '/';
     }
   /* `parent' is now the last existing leading directory in the whole path,
      so it's ok to call pathconf with it as the argument.  */
   path_max = portability ? _POSIX_PATH_MAX : PATH_MAX_FOR (parent);
   if (path_max < 0)
     path_max = _POSIX_PATH_MAX;
   free (parent);
   if (strlen (path) > path_max)
     {
       builtin_error ("path `%s' has length %lu; exceeds limit of %d",
          path, (unsigned long)strlen (path), path_max);
       return 1;
     }
   return 0;
 }
References _POSIX_NAME_MAX, _POSIX_PATH_MAX, builtin_error(), dir_ok(), free, mlibc::length, NAME_MAX_FOR, NULL, PATH_MAX_FOR, portable_chars_only(), start(), strchr(), strlen(), and xstrdup().
xstrdup()
static char* xstrdup (char * s) static
Definition at line 258 of file pathchk.c.
 {
   return (savestring (s));
 }
References savestring().
Referenced by validate_path().
Variable Documentation
errno
int errno extern
Referenced by dir_ok().
pathchk_doc
char* pathchk_doc[]
Initial value:
= {
    "Check pathnames for validity.",
    "",
    "Check each pathname argument for validity (i.e., it may be used to",
    "create or access a file without causing syntax errors) and portability",
    "(i.e., no filename truncation will result).  If the `-p' option is",
    "supplied, more extensive portability checks are performed.",
    (char *)NULL
}
Definition at line 135 of file pathchk.c.
pathchk_struct
struct builtin pathchk_struct
Initial value:
= {
    "pathchk",
    pathchk_builtin,
    BUILTIN_ENABLED,
    pathchk_doc,
    "pathchk [-p] pathname ...",
    0
}
Definition at line 135 of file pathchk.c.
portable_chars
char const portable_chars[256] static
Initial value:
=
{
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
  0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
  0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
}
Definition at line 165 of file pathchk.c.
Referenced by portable_chars_only().