Fennix Userspace: Userspace/apps/base/busybox/coreutils/install.c File Reference
install.c File Reference
#include "libbb.h"
#include "libcoreutils/coreutils.h"
Macros
#define GETOPT32 getopt32
#define LONGOPTS
Functions
int install_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
GETOPT32
#define GETOPT32 getopt32
Definition at line 67 of file install.c.
LONGOPTS
#define LONGOPTS
Definition at line 68 of file install.c.
Function Documentation
install_main()
int install_main (int argc, char ** argv)
Definition at line 106 of file install.c.
 {
     struct stat statbuf;
     mode_t mode;
     uid_t uid;
     gid_t gid;
     char *arg, *last;
     const char *gid_str;
     const char *uid_str;
     const char *mode_str;
     int mkdir_flags = FILEUTILS_RECUR;
     int copy_flags = FILEUTILS_DEREFERENCE | FILEUTILS_FORCE;
     int opts;
     int ret = EXIT_SUCCESS;
     int isdir;
 #if ENABLE_SELINUX
     security_context_t scontext;
     bool use_default_selinux_context = 1;
 #endif
     enum {
         OPT_c             = 1 << 0,
         OPT_v             = 1 << 1,
         OPT_b             = 1 << 2,
         OPT_MKDIR_LEADING = 1 << 3,
         OPT_DIRECTORY     = 1 << 4,
         OPT_PRESERVE_TIME = 1 << 5,
         OPT_STRIP         = 1 << 6,
         OPT_GROUP         = 1 << 7,
         OPT_MODE          = 1 << 8,
         OPT_OWNER         = 1 << 9,
         OPT_TARGET        = 1 << 10,
 #if ENABLE_SELINUX
         OPT_SET_SECURITY_CONTEXT = 1 << 11,
         OPT_PRESERVE_SECURITY_CONTEXT = 1 << 12,
 #endif
     };
     /* -c exists for backwards compatibility, it's needed */
     /* -b is ignored ("make a backup of each existing destination file") */
     opts = GETOPT32(argv, "^"
         "cvb" "Ddpsg:m:o:t:" IF_SELINUX("Z:")
         "\0"
         "t--d:d--t:s--d:d--s"
         IF_FEATURE_INSTALL_LONG_OPTIONS(IF_SELINUX(":Z--\xff:\xff--Z")),
         LONGOPTS
         &gid_str, &mode_str, &uid_str, &last
         IF_SELINUX(, &scontext)
     );
     argc -= optind;
     argv += optind;
 #if ENABLE_SELINUX
     if (opts & (OPT_PRESERVE_SECURITY_CONTEXT|OPT_SET_SECURITY_CONTEXT)) {
         selinux_or_die();
         use_default_selinux_context = 0;
         if (opts & OPT_PRESERVE_SECURITY_CONTEXT) {
             copy_flags |= FILEUTILS_PRESERVE_SECURITY_CONTEXT;
         }
         if (opts & OPT_SET_SECURITY_CONTEXT) {
             setfscreatecon_or_die(scontext);
             copy_flags |= FILEUTILS_SET_SECURITY_CONTEXT;
         }
     }
 #endif
     if ((opts & OPT_v) && FILEUTILS_VERBOSE) {
         mkdir_flags |= FILEUTILS_VERBOSE;
         copy_flags |= FILEUTILS_VERBOSE;
     }
     /* preserve access and modification time, this is GNU behaviour,
      * BSD only preserves modification time */
     if (opts & OPT_PRESERVE_TIME) {
         copy_flags |= FILEUTILS_PRESERVE_STATUS;
     }
     mode = 0755; /* GNU coreutils 6.10 compat */
     if (opts & OPT_MODE)
         mode = bb_parse_mode(mode_str, mode);
     uid = (opts & OPT_OWNER) ? get_ug_id(uid_str, xuname2uid) : getuid();
     gid = (opts & OPT_GROUP) ? get_ug_id(gid_str, xgroup2gid) : getgid();
     /* If -t DIR is in use, then isdir=true, last="DIR" */
     isdir = (opts & OPT_TARGET);
     if (!(opts & (OPT_TARGET|OPT_DIRECTORY))) {
         /* Neither -t DIR nor -d is in use */
         argc--;
         last = argv[argc];
         argv[argc] = NULL;
         /* coreutils install resolves link in this case, don't use lstat */
         isdir = stat(last, &statbuf) < 0 ? 0 : S_ISDIR(statbuf.st_mode);
     }
     if (argc < 1)
         bb_show_usage();
     while ((arg = *argv++) != NULL) {
         char *dest;
         if (opts & OPT_DIRECTORY) {
             dest = arg;
             /* GNU coreutils 6.9 does not set uid:gid
              * on intermediate created directories
              * (only on last one) */
             if (bb_make_directory(dest, 0755, mkdir_flags)) {
                 ret = EXIT_FAILURE;
                 goto next;
             }
         } else {
             dest = last;
             if (opts & OPT_MKDIR_LEADING) {
                 char *ddir = xstrdup(dest);
                 /*
                  * -D -t DIR1/DIR2/F3 FILE: create DIR1/DIR2/F3, copy FILE there
                  * -D FILE DIR1/DIR2/F3: create DIR1/DIR2, copy FILE there as F3
                  */
                 bb_make_directory((opts & OPT_TARGET) ? ddir : dirname(ddir), 0755, mkdir_flags);
                 /* errors are not checked. copy_file
                  * will fail if dir is not created.
                  */
                 free(ddir);
             }
             if (isdir)
                 dest = concat_path_file(last, bb_basename(arg));
             if (copy_file(arg, dest, copy_flags) != 0) {
                 /* copy is not made */
                 ret = EXIT_FAILURE;
                 goto next;
             }
             if (opts & OPT_STRIP) {
                 char *args[4];
                 args[0] = (char*)"strip";
                 args[1] = (char*)"-p"; /* -p --preserve-dates */
                 args[2] = dest;
                 args[3] = NULL;
                 if (spawn_and_wait(args)) {
                     bb_simple_perror_msg("strip");
                     ret = EXIT_FAILURE;
                 }
             }
         }
         /* Set the file mode (always, not only with -m).
          * GNU coreutils 6.10 is not affected by umask. */
         if (chmod(dest, mode) == -1) {
             bb_perror_msg("can't change %s of %s", "permissions", dest);
             ret = EXIT_FAILURE;
         }
 #if ENABLE_SELINUX
         if (use_default_selinux_context)
             setdefaultfilecon(dest);
 #endif
         /* Set the user and group id */
         if ((opts & (OPT_OWNER|OPT_GROUP))
          && lchown(dest, uid, gid) == -1
         ) {
             bb_perror_msg("can't change %s of %s", "ownership", dest);
             ret = EXIT_FAILURE;
         }
  next:
         if (ENABLE_FEATURE_CLEAN_UP && isdir)
             free(dest);
     }
     return ret;
 }
References argc, argv, bb_basename(), bb_make_directory(), bb_parse_mode(), bb_perror_msg(), bb_show_usage(), bb_simple_perror_msg(), chmod(), concat_path_file(), copy_file(), dirname, EXIT_FAILURE, EXIT_SUCCESS, FILEUTILS_DEREFERENCE, FILEUTILS_FORCE, FILEUTILS_PRESERVE_STATUS, FILEUTILS_RECUR, FILEUTILS_VERBOSE, free, get_ug_id(), getgid, GETOPT32, getuid, last, lchown(), LONGOPTS, mode_t, next, NULL, OPT_b, OPT_c, OPT_OWNER, OPT_v, optind, S_ISDIR, selinux_or_die(), setfscreatecon_or_die(), spawn_and_wait(), stat::st_mode, stat(), xgroup2gid(), xstrdup(), and xuname2uid().