Fennix Userspace: Userspace/musl/src/prng/mrand48.c File Reference
mrand48.c File Reference
#include <stdlib.h>
#include <inttypes.h>
#include "rand48.h"
Functions
long jrand48 (unsigned short s[3])
long mrand48 (void)
Function Documentation
jrand48()
long jrand48 (unsigned short s[3])
Definition at line 5 of file mrand48.c.
 {
     return (int32_t)(__rand48_step(s, __seed48+3) >> 16);
 }
References __rand48_step(), and __seed48.
Referenced by mrand48().
mrand48()
long mrand48 (void)
Definition at line 10 of file mrand48.c.
 {
     return jrand48(__seed48);
 }
References __seed48, and jrand48().