Fennix Drivers: Drivers/Input/PS2Mouse/PS2MouseDriver.cpp File Reference
PS2MouseDriver.cpp File Reference
#include <pci.h>
#include <io.h>
#include "../../../Kernel/DAPI.hpp"
#include "../../../Kernel/Fex.hpp"
Macros
#define print(msg) KAPI->Util.DebugPrint((char *)(msg), KAPI->Info.DriverUID)
#define PS2LeftButton 0b00000001
#define PS2MiddleButton 0b00000100
#define PS2RightButton 0b00000010
#define PS2XSign 0b00010000
#define PS2YSign 0b00100000
#define PS2XOverflow 0b01000000
#define PS2YOverflow 0b10000000
Enumerations
enum Config { READ_CONFIG = 0x20 , WRITE_CONFIG = 0x60 , READ_CONFIG = 0x20 , WRITE_CONFIG = 0x60 }
enum Ports {
DATA = 0x60 , STATUS = 0x64 , COMMAND = 0x64 , DATA = 0x60 ,
STATUS = 0x64 , COMMAND = 0x64
}
enum State {
OUTPUT_FULL = (1 << 0) , INPUT_FULL = (1 << 1) , MOUSE_BYTE = (1 << 5) , OUTPUT_FULL = (1 << 0) ,
INPUT_FULL = (1 << 1) , MOUSE_BYTE = (1 << 5)
}
Functions
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
HEAD (FexFormatType_Driver, FexOSType_Fennix, DriverEntry)
__attribute__ ((section(".extended"))) FexExtended ExtendedHeader
void WaitRead ()
void WaitWrite ()
uint8_t Read ()
void Write (uint16_t Port, uint8_t Value)
Variables
KernelAPI * KAPI
int MouseX = 0
int MouseY = 0
int MouseZ = 0
int MouseLeft = 0
int MouseMiddle = 0
int MouseRight = 0
uint8_t Packet [4]
bool PacketReady = false
uint8_t Cycle = 0
Macro Definition Documentation
print
#define print (msg) KAPI->Util.DebugPrint((char *)(msg), KAPI->Info.DriverUID)
Definition at line 29 of file PS2MouseDriver.cpp.
PS2LeftButton
#define PS2LeftButton 0b00000001
Definition at line 53 of file PS2MouseDriver.cpp.
PS2MiddleButton
#define PS2MiddleButton 0b00000100
Definition at line 54 of file PS2MouseDriver.cpp.
PS2RightButton
#define PS2RightButton 0b00000010
Definition at line 55 of file PS2MouseDriver.cpp.
PS2XOverflow
#define PS2XOverflow 0b01000000
Definition at line 58 of file PS2MouseDriver.cpp.
PS2XSign
#define PS2XSign 0b00010000
Definition at line 56 of file PS2MouseDriver.cpp.
PS2YOverflow
#define PS2YOverflow 0b10000000
Definition at line 59 of file PS2MouseDriver.cpp.
PS2YSign
#define PS2YSign 0b00100000
Definition at line 57 of file PS2MouseDriver.cpp.
Enumeration Type Documentation
Config
enum Config
Enumerator
READ_CONFIG
WRITE_CONFIG
READ_CONFIG
WRITE_CONFIG
Definition at line 33 of file PS2MouseDriver.cpp.
 {
     READ_CONFIG = 0x20,
     WRITE_CONFIG = 0x60
 };
Ports
enum Ports
Enumerator
DATA
STATUS
COMMAND
DATA
STATUS
COMMAND
Definition at line 39 of file PS2MouseDriver.cpp.
 {
     DATA = 0x60,
     STATUS = 0x64,
     COMMAND = 0x64,
 };
State
enum State
Enumerator
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
Definition at line 46 of file PS2MouseDriver.cpp.
 {
     OUTPUT_FULL = (1 << 0),
     INPUT_FULL = (1 << 1),
     MOUSE_BYTE = (1 << 5)
 };
Function Documentation
__attribute__()
__attribute__ ((section(".extended")))
References CallbackHandler().
CallbackHandler()
int CallbackHandler (KernelCallback * Data)
Definition at line 107 of file PS2MouseDriver.cpp.
 {
     switch (Data->Reason)
     {
     case AcknowledgeReason:
     {
         print("Kernel acknowledged the driver.");
         break;
     }
     case ConfigurationReason:
     {
         outb(COMMAND, 0xA8);
         Write(COMMAND, READ_CONFIG);
         uint8_t Status = Read();
         Status |= 0b10;
         Write(COMMAND, WRITE_CONFIG);
         Write(DATA, Status);
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF6);
         Read();
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF4);
         Read();
         print("PS/2 mouse configured.");
         break;
     }
     case FetchReason:
     {
         Data->InputCallback.Mouse.X = MouseX;
         Data->InputCallback.Mouse.Y = MouseY;
         Data->InputCallback.Mouse.Z = MouseZ;
         Data->InputCallback.Mouse.Buttons.Left = MouseLeft;
         Data->InputCallback.Mouse.Buttons.Right = MouseRight;
         Data->InputCallback.Mouse.Buttons.Middle = MouseMiddle;
         break;
     }
     case StopReason:
     {
         outb(COMMAND, 0xA8);
         Write(COMMAND, READ_CONFIG);
         uint8_t Status = Read();
         Status &= ~0b10;
         Write(COMMAND, WRITE_CONFIG);
         Write(DATA, Status);
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF5);
         Read();
         print("Driver stopped.");
         break;
     }
     case InterruptReason:
     {
         uint8_t Data = inb(0x60);
         if (__builtin_expect(!!(PacketReady), 0))
         {
             bool XNegative, YNegative, XOverflow, YOverflow;
             if (Packet[0] & PS2XSign)
                 XNegative = true;
             else
                 XNegative = false;
             if (Packet[0] & PS2YSign)
                 YNegative = true;
             else
                 YNegative = false;
             if (Packet[0] & PS2XOverflow)
                 XOverflow = true;
             else
                 XOverflow = false;
             if (Packet[0] & PS2YOverflow)
                 YOverflow = true;
             else
                 YOverflow = false;
             if (!XNegative)
             {
                 MouseX += Packet[1];
                 if (XOverflow)
                     MouseX += 255;
             }
             else
             {
                 Packet[1] = 256 - Packet[1];
                 MouseX -= Packet[1];
                 if (XOverflow)
                     MouseX -= 255;
             }
             if (!YNegative)
             {
                 MouseY -= Packet[2];
                 if (YOverflow)
                     MouseY -= 255;
             }
             else
             {
                 Packet[2] = 256 - Packet[2];
                 MouseY += Packet[2];
                 if (YOverflow)
                     MouseY += 255;
             }
             uint32_t Width = KAPI->Display.GetWidth();
             uint32_t Height = KAPI->Display.GetHeight();
             if (MouseX < 0)
                 MouseX = 0;
             if ((uint32_t)MouseX > Width - 1)
                 MouseX = Width - 1;
             if (MouseY < 0)
                 MouseY = 0;
             if ((uint32_t)MouseY > Height - 1)
                 MouseY = Height - 1;
             MouseLeft = 0;
             MouseMiddle = 0;
             MouseRight = 0;
             if (Packet[0] & PS2LeftButton)
                 MouseLeft = 1;
             if (Packet[0] & PS2MiddleButton)
                 MouseMiddle = 1;
             if (Packet[0] & PS2RightButton)
                 MouseRight = 1;
             PacketReady = false;
         }
         switch (Cycle)
         {
         case 0:
         {
             if ((Data & 0b00001000) == 0)
                 break;
             Packet[0] = Data;
             Cycle++;
             break;
         }
         case 1:
         {
             Packet[1] = Data;
             Cycle++;
             break;
         }
         case 2:
         {
             Packet[2] = Data;
             PacketReady = true;
             Cycle = 0;
             break;
         }
         }
         break;
     }
     default:
     {
         print("Unknown reason.");
         break;
     }
     }
     return OK;
 }
References COMMAND, Cycle, DATA, KAPI, MouseLeft, MouseMiddle, MouseRight, MouseX, MouseY, MouseZ, Packet, PacketReady, print, PS2LeftButton, PS2MiddleButton, PS2RightButton, PS2XOverflow, PS2XSign, PS2YOverflow, PS2YSign, Read(), READ_CONFIG, Status, Write(), and WRITE_CONFIG.
Referenced by __attribute__().
DriverEntry()
int DriverEntry (void * Data)
Definition at line 96 of file PS2MouseDriver.cpp.
 {
     if (!Data)
         return INVALID_KERNEL_API;
     KAPI = (KernelAPI *)Data;
     if (KAPI->Version.Major < 0 || KAPI->Version.Minor < 0 || KAPI->Version.Patch < 0)
         return KERNEL_API_VERSION_NOT_SUPPORTED;
     return OK;
 }
References KAPI.
HEAD()
HEAD (FexFormatType_Driver , FexOSType_Fennix , DriverEntry)
Read()
uint8_t Read ()
Definition at line 84 of file PS2MouseDriver.cpp.
 {
     WaitRead();
     return inb(Ports::DATA);
 }
References DATA, and WaitRead().
Referenced by CallbackHandler().
WaitRead()
void WaitRead ()
Definition at line 68 of file PS2MouseDriver.cpp.
 {
     uint64_t Timeout = 100000;
     while (Timeout--)
         if (inb(Ports::STATUS) & State::OUTPUT_FULL)
             return;
 }
References OUTPUT_FULL, and STATUS.
Referenced by Read().
WaitWrite()
void WaitWrite ()
Definition at line 76 of file PS2MouseDriver.cpp.
 {
     uint64_t Timeout = 100000;
     while (Timeout--)
         if ((inb(Ports::STATUS) & State::INPUT_FULL) == 0)
             return;
 }
References INPUT_FULL, and STATUS.
Referenced by Write().
Write()
void Write (uint16_t Port, uint8_t Value)
Definition at line 90 of file PS2MouseDriver.cpp.
 {
     WaitWrite();
     outb(Port, Value);
 }
References WaitWrite().
Referenced by CallbackHandler(), and Port::ReadWrite().
Variable Documentation
Cycle
uint8_t Cycle = 0
Definition at line 66 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
KAPI
KernelAPI* KAPI
Definition at line 27 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler(), and DriverEntry().
MouseLeft
int MouseLeft = 0
Definition at line 62 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
MouseMiddle
int MouseMiddle = 0
Definition at line 62 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
MouseRight
int MouseRight = 0
Definition at line 62 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
MouseX
int MouseX = 0
Definition at line 61 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
MouseY
int MouseY = 0
Definition at line 61 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
MouseZ
int MouseZ = 0
Definition at line 61 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
Packet
uint8_t Packet[4]
Definition at line 64 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().
PacketReady
bool PacketReady = false
Definition at line 65 of file PS2MouseDriver.cpp.
Referenced by CallbackHandler().