Fennix: Userspace/apps/base/busybox/libbb/str_tolower.c File Reference
str_tolower.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC str_tolower (char *str)
Function Documentation
str_tolower()
char* FAST_FUNC str_tolower (char * str)
Definition at line 8 of file str_tolower.c.
 {
     char *c;
     for (c = str; *c; ++c)
         *c = tolower(*c);
     return str;
 }
References c, str, and tolower.
Referenced by download_one_url(), ipcalc_main(), query(), and vlan_parse_opt().