Fennix Userspace: Userspace/apps/base/busybox/networking/nc_bloaty.c File Reference
nc_bloaty.c File Reference
Data Structures
struct globals
Macros
#define SENT_N_RECV_M "sent %u, rcvd %u\n"
#define G (*ptr_to_globals)
#define wrote_out (G.wrote_out)
#define wrote_net (G.wrote_net)
#define ouraddr (G.ouraddr)
#define themaddr (G.themaddr)
#define remend (G.remend)
#define jbuf (G.jbuf)
#define bigbuf_in (G.bigbuf_in)
#define bigbuf_net (G.bigbuf_net)
#define o_verbose (G.o_verbose)
#define o_wait (G.o_wait)
#define o_interval 0
#define INIT_G()
#define o_nflag (option_mask32 & OPT_n)
#define o_udpmode (option_mask32 & OPT_u)
#define o_bcmode (option_mask32 & OPT_b)
#define o_ofile 0
#define o_zero 0
#define Debug(...) do { } while (0)
#define holler_error(msg) do { if (o_verbose) bb_simple_error_msg(msg); } while (0)
#define holler_perror(msg) do { if (o_verbose) bb_simple_perror_msg(msg); } while (0)
Enumerations
enum { SLEAZE_PORT = 31337 , BIGSIZ = 8192 , netfd = 3 , ofd = 4 }
enum {
OPT_n = (1 << 0) , OPT_p = (1 << 1) , OPT_s = (1 << 2) , OPT_u = (1 << 3) ,
OPT_b = (1 << 4) , OPT_v = (1 << 5) , OPT_w = (1 << 6) , OPT_l = (1 << 7) * ENABLE_NC_SERVER ,
OPT_k = (1 << 8) * ENABLE_NC_SERVER , OPT_i = (1 << (7+2*ENABLE_NC_SERVER)) * ENABLE_NC_EXTRA , OPT_o = (1 << (8+2*ENABLE_NC_SERVER)) * ENABLE_NC_EXTRA , OPT_z = (1 << (9+2*ENABLE_NC_SERVER)) * ENABLE_NC_EXTRA
}
Functions
static void catch (int sig)
static void unarm (void)
static void tmtravel (int sig UNUSED_PARAM)
static void arm (unsigned secs)
static unsigned findline (char *buf, unsigned siz)
static int doexec (char **proggie) NORETURN
static int connect_w_timeout (int fd)
static void dolisten (int is_persistent, char **proggie)
int udptest (void)
void oprint (int direction, unsigned char *p, unsigned bc)
static int readwrite (void)
int nc_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
bigbuf_in
#define bigbuf_in (G.bigbuf_in)
Definition at line 155 of file nc_bloaty.c.
bigbuf_net
#define bigbuf_net (G.bigbuf_net)
Definition at line 156 of file nc_bloaty.c.
Debug
#define Debug (...) do { } while (0)
Definition at line 201 of file nc_bloaty.c.
G
#define G (*ptr_to_globals)
Definition at line 148 of file nc_bloaty.c.
holler_error
#define holler_error (msg) do { if (o_verbose) bb_simple_error_msg(msg); } while (0)
Definition at line 204 of file nc_bloaty.c.
holler_perror
#define holler_perror (msg) do { if (o_verbose) bb_simple_perror_msg(msg); } while (0)
Definition at line 205 of file nc_bloaty.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 164 of file nc_bloaty.c.
jbuf
#define jbuf (G.jbuf)
Definition at line 154 of file nc_bloaty.c.
o_bcmode
#define o_bcmode (option_mask32 & OPT_b)
Definition at line 187 of file nc_bloaty.c.
o_interval
#define o_interval 0
Definition at line 162 of file nc_bloaty.c.
o_nflag
#define o_nflag (option_mask32 & OPT_n)
Definition at line 185 of file nc_bloaty.c.
o_ofile
#define o_ofile 0
Definition at line 192 of file nc_bloaty.c.
o_udpmode
#define o_udpmode (option_mask32 & OPT_u)
Definition at line 186 of file nc_bloaty.c.
o_verbose
#define o_verbose (G.o_verbose)
Definition at line 157 of file nc_bloaty.c.
o_wait
#define o_wait (G.o_wait)
Definition at line 158 of file nc_bloaty.c.
o_zero
#define o_zero 0
Definition at line 193 of file nc_bloaty.c.
ouraddr
#define ouraddr (G.ouraddr)
Definition at line 151 of file nc_bloaty.c.
remend
#define remend (G.remend)
Definition at line 153 of file nc_bloaty.c.
SENT_N_RECV_M
#define SENT_N_RECV_M "sent %u, rcvd %u\n"
Definition at line 127 of file nc_bloaty.c.
themaddr
#define themaddr (G.themaddr)
Definition at line 152 of file nc_bloaty.c.
wrote_net
#define wrote_net (G.wrote_net)
Definition at line 150 of file nc_bloaty.c.
wrote_out
#define wrote_out (G.wrote_out)
Definition at line 149 of file nc_bloaty.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SLEAZE_PORT
BIGSIZ
netfd
ofd
Definition at line 104 of file nc_bloaty.c.
      {
     SLEAZE_PORT = 31337,               /* for UDP-scan RTT trick, change if ya want */
     BIGSIZ = 8192,                     /* big buffers */
     netfd = 3,
     ofd = 4,
 };
anonymous enum
anonymous enum
Enumerator
OPT_n
OPT_p
OPT_s
OPT_u
OPT_b
OPT_v
OPT_w
OPT_l
OPT_k
OPT_i
OPT_o
OPT_z
Definition at line 170 of file nc_bloaty.c.
      {
     OPT_n = (1 << 0),
     OPT_p = (1 << 1),
     OPT_s = (1 << 2),
     OPT_u = (1 << 3),
     OPT_b = (1 << 4),
     OPT_v = (1 << 5),
     OPT_w = (1 << 6),
     OPT_l = (1 << 7) * ENABLE_NC_SERVER,
     OPT_k = (1 << 8) * ENABLE_NC_SERVER,
     OPT_i = (1 << (7+2*ENABLE_NC_SERVER)) * ENABLE_NC_EXTRA,
     OPT_o = (1 << (8+2*ENABLE_NC_SERVER)) * ENABLE_NC_EXTRA,
     OPT_z = (1 << (9+2*ENABLE_NC_SERVER)) * ENABLE_NC_EXTRA,
 };
Function Documentation
arm()
static void arm (unsigned secs) static
Definition at line 231 of file nc_bloaty.c.
 {
     signal(SIGALRM, tmtravel);
     alarm(secs);
 }
References alarm(), SIGALRM, signal, and tmtravel().
Referenced by connect_w_timeout(), and dolisten().
catch()
static void catch (int sig) static
Definition at line 208 of file nc_bloaty.c.
 {
     if (o_verbose > 1)                /* normally we don't care */
         fprintf(stderr, SENT_N_RECV_M, wrote_net, wrote_out);
     fprintf(stderr, "punt!\n");
     kill_myself_with_sig(sig);
 }
References fprintf(), kill_myself_with_sig(), o_verbose, SENT_N_RECV_M, stderr, wrote_net, and wrote_out.
connect_w_timeout()
static int connect_w_timeout (int fd) static
Definition at line 287 of file nc_bloaty.c.
 {
     int rr;
     /* wrap connect inside a timer, and hit it */
     arm(o_wait);
     if (setjmp(jbuf) == 0) {
         rr = connect(fd, &themaddr->u.sa, themaddr->len);
         unarm();
     } else { /* setjmp: connect failed... */
         rr = -1;
         errno = ETIMEDOUT; /* fake it */
     }
     return rr;
 }
References arm(), connect(), errno, ETIMEDOUT, fd, jbuf, o_wait, setjmp, themaddr, and unarm().
Referenced by nc_main().
doexec()
static int doexec (char ** proggie) static
Definition at line 270 of file nc_bloaty.c.
 {
     if (G.proggie0saved)
         proggie[0] = G.proggie0saved;
     xmove_fd(netfd, 0);
     dup2(0, 1);
     /* dup2(0, 2); - do we *really* want this? NO!
      * exec'ed prog can do it yourself, if needed */
     BB_EXECVP_or_die(proggie);
 }
References BB_EXECVP_or_die(), dup2(), G, netfd, and xmove_fd().
Referenced by dolisten(), and nc_main().
dolisten()
static void dolisten (int is_persistent, char ** proggie) static
Definition at line 308 of file nc_bloaty.c.
 {
     int rr;
     if (!o_udpmode)
         xlisten(netfd, 1); /* TCP: gotta listen() before we can get */
     /* Various things that follow temporarily trash bigbuf_net, which might contain
      a copy of any recvfrom()ed packet, but we'll read() another copy later. */
     /* I can't believe I have to do all this to get my own goddamn bound address
      and port number.  It should just get filled in during bind() or something.
      All this is only useful if we didn't say -p for listening, since if we
      said -p we *know* what port we're listening on.  At any rate we won't bother
      with it all unless we wanted to see it, although listening quietly on a
      random unknown port is probably not very useful without "netstat". */
     if (o_verbose) {
         char *addr;
         getsockname(netfd, &ouraddr->u.sa, &ouraddr->len);
         //if (rr < 0)
         //  bb_perror_msg_and_die("getsockname after bind");
         addr = xmalloc_sockaddr2dotted(&ouraddr->u.sa);
         fprintf(stderr, "listening on %s ...\n", addr);
         free(addr);
     }
     if (o_udpmode) {
         /* UDP is a speeeeecial case -- we have to do I/O *and* get the calling
          party's particulars all at once, listen() and accept() don't apply.
          At least in the BSD universe, however, recvfrom/PEEK is enough to tell
          us something came in, and we can set things up so straight read/write
          actually does work after all.  Yow.  YMMV on strange platforms!  */
         /* I'm not completely clear on how this works -- BSD seems to make UDP
          just magically work in a connect()ed context, but we'll undoubtedly run
          into systems this deal doesn't work on.  For now, we apparently have to
          issue a connect() on our just-tickled socket so we can write() back.
          Again, why the fuck doesn't it just get filled in and taken care of?!
          This hack is anything but optimal.  Basically, if you want your listener
          to also be able to send data back, you need this connect() line, which
          also has the side effect that now anything from a different source or even a
          different port on the other end won't show up and will cause ICMP errors.
          I guess that's what they meant by "connect".
          Let's try to remember what the "U" is *really* for, eh? */
         /* If peer address is specified, connect to it */
         remend.len = LSA_SIZEOF_SA;
         if (themaddr) {
             remend = *themaddr;
             xconnect(netfd, &themaddr->u.sa, themaddr->len);
         }
         /* peek first packet and remember peer addr */
         arm(o_wait);                /* might as well timeout this, too */
         if (setjmp(jbuf) == 0) {       /* do timeout for initial connect */
             /* (*ouraddr) is prefilled with "default" address */
             /* and here we block... */
             rr = recv_from_to(netfd, NULL, 0, MSG_PEEK, /*was bigbuf_net, BIGSIZ*/
                 &remend.u.sa, &ouraddr->u.sa, ouraddr->len);
             if (rr < 0)
                 bb_simple_perror_msg_and_die("recvfrom");
             unarm();
         } else
             bb_simple_error_msg_and_die("timeout");
 /* Now we learned *to which IP* peer has connected, and we want to anchor
 our socket on it, so that our outbound packets will have correct local IP.
 Unfortunately, bind() on already bound socket will fail now (EINVAL):
     xbind(netfd, &ouraddr->u.sa, ouraddr->len);
 Need to read the packet, save data, close this socket and
 create new one, and bind() it. TODO */
         if (!themaddr)
             xconnect(netfd, &remend.u.sa, ouraddr->len);
     } else {
         /* TCP */
  another:
         arm(o_wait); /* wrap this in a timer, too; 0 = forever */
         if (setjmp(jbuf) == 0) {
  again:
             remend.len = LSA_SIZEOF_SA;
             rr = accept(netfd, &remend.u.sa, &remend.len);
             if (rr < 0)
                 bb_simple_perror_msg_and_die("accept");
             if (themaddr) {
                 int sv_port, port, r;
                 sv_port = get_nport(&remend.u.sa); /* save */
                 port = get_nport(&themaddr->u.sa);
                 if (port == 0) {
                     /* "nc -nl -p LPORT RHOST" (w/o RPORT!):
                      * we should accept any remote port */
                     set_nport(&remend.u.sa, 0); /* blot out remote port# */
                 }
                 r = memcmp(&remend.u.sa, &themaddr->u.sa, remend.len);
                 set_nport(&remend.u.sa, sv_port); /* restore */
                 if (r != 0) {
                     /* nc 1.10 bails out instead, and its error message
                      * is not suppressed by o_verbose */
                     if (o_verbose) {
                         char *remaddr = xmalloc_sockaddr2dotted(&remend.u.sa);
                         bb_error_msg("connect from wrong ip/port %s ignored", remaddr);
                         free(remaddr);
                     }
                     close(rr);
                     goto again;
                 }
             }
             unarm();
         } else
             bb_simple_error_msg_and_die("timeout");
         if (is_persistent && proggie) {
             /* -l -k -e PROG */
             signal(SIGCHLD, SIG_IGN); /* no zombies please */
             if (xvfork() != 0) {
                 /* parent: go back and accept more connections */
                 close(rr);
                 goto another;
             }
             /* child */
             signal(SIGCHLD, SIG_DFL);
         }
         xmove_fd(rr, netfd); /* dump the old socket, here's our new one */
         /* find out what address the connection was *to* on our end, in case we're
          doing a listen-on-any on a multihomed machine.  This allows one to
          offer different services via different alias addresses, such as the
          "virtual web site" hack. */
         getsockname(netfd, &ouraddr->u.sa, &ouraddr->len);
         //if (rr < 0)
         //  bb_perror_msg_and_die("getsockname after accept");
     }
     if (o_verbose) {
         char *lcladdr, *remaddr, *remhostname;
 #if ENABLE_NC_EXTRA && defined(IP_OPTIONS)
     /* If we can, look for any IP options.  Useful for testing the receiving end of
      such things, and is a good exercise in dealing with it.  We do this before
      the connect message, to ensure that the connect msg is uniformly the LAST
      thing to emerge after all the intervening crud.  Doesn't work for UDP on
      any machines I've tested, but feel free to surprise me. */
         char optbuf[40];
         socklen_t x = sizeof(optbuf);
         rr = getsockopt(netfd, IPPROTO_IP, IP_OPTIONS, optbuf, &x);
         if (rr >= 0 && x) {    /* we've got options, lessee em... */
             *bin2hex(bigbuf_net, optbuf, x) = '\0';
             fprintf(stderr, "IP options: %s\n", bigbuf_net);
         }
 #endif
     /* now check out who it is.  We don't care about mismatched DNS names here,
      but any ADDR and PORT we specified had better fucking well match the caller.
      Converting from addr to inet_ntoa and back again is a bit of a kludge, but
      gethostpoop wants a string and there's much gnarlier code out there already,
      so I don't feel bad.
      The *real* question is why BFD sockets wasn't designed to allow listens for
      connections *from* specific hosts/ports, instead of requiring the caller to
      accept the connection and then reject undesirable ones by closing.
      In other words, we need a TCP MSG_PEEK. */
     /* bbox: removed most of it */
         lcladdr = xmalloc_sockaddr2dotted(&ouraddr->u.sa);
         remaddr = xmalloc_sockaddr2dotted(&remend.u.sa);
         remhostname = o_nflag ? remaddr : xmalloc_sockaddr2host(&remend.u.sa);
         fprintf(stderr, "connect to %s from %s (%s)\n",
                 lcladdr, remhostname, remaddr);
         free(lcladdr);
         free(remaddr);
         if (!o_nflag)
             free(remhostname);
     }
     if (proggie)
         doexec(proggie);
 }
References accept(), addr, arm(), bb_error_msg(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), bigbuf_net, bin2hex(), close(), doexec(), fprintf(), free, get_nport(), getsockname(), getsockopt(), IP_OPTIONS, IPPROTO_IP, jbuf, LSA_SIZEOF_SA, memcmp(), MSG_PEEK, netfd, NULL, o_nflag, o_udpmode, o_verbose, o_wait, ouraddr, port, recv_from_to(), remend, set_nport(), setjmp, SIG_DFL, SIG_IGN, SIGCHLD, signal, stderr, themaddr, unarm(), x, xconnect(), xlisten(), xmalloc_sockaddr2dotted(), xmalloc_sockaddr2host(), xmove_fd(), and xvfork.
Referenced by nc_main().
findline()
static unsigned findline (char * buf, unsigned siz) static
Definition at line 241 of file nc_bloaty.c.
 {
     char * p;
     int x;
     if (!buf)                        /* various sanity checks... */
         return 0;
     if (siz > BIGSIZ)
         return 0;
     x = siz;
     for (p = buf; x > 0; x--) {
         if (*p == '\n') {
             x = (int) (p - buf);
             x++;                        /* 'sokay if it points just past the end! */
 Debug("findline returning %d", x);
             return x;
         }
         p++;
     } /* for */
 Debug("findline returning whole thing: %d", siz);
     return siz;
 } /* findline */
References BIGSIZ, buf, Debug, p, and x.
Referenced by readwrite().
nc_main()
int nc_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 741 of file nc_bloaty.c.
 {
     char *str_p, *str_s;
     IF_NC_EXTRA(char *str_i, *str_o;)
     char *themdotted = themdotted; /* for compiler */
     char **proggie;
     int x;
     unsigned cnt_l = 0;
     unsigned o_lport = 0;
     INIT_G();
     /* catch a signal or two for cleanup */
     bb_signals(0
         + (1 << SIGINT)
         + (1 << SIGQUIT)
         + (1 << SIGTERM)
         , catch);
     /* and suppress others... */
     bb_signals(0
 #ifdef SIGURG
         + (1 << SIGURG)
 #endif
         + (1 << SIGPIPE) /* important! */
         , SIG_IGN);
     proggie = argv;
     while (*++proggie) {
         if (strcmp(*proggie, "-e") == 0) {
             *proggie = NULL;
             proggie++;
             goto e_found;
         }
         /* -<other_opts>e PROG [ARGS] ? */
         /* (aboriginal linux uses this form) */
         if (proggie[0][0] == '-') {
             char *optpos = *proggie + 1;
             /* Skip all valid opts w/o params */
             optpos = optpos + strspn(optpos, "nuv"IF_NC_SERVER("lk")IF_NC_EXTRA("z"));
             if (*optpos == 'e' && !optpos[1]) {
                 *optpos = '\0';
                 proggie++;
                 G.proggie0saved = *proggie;
                 *proggie = NULL; /* terminate argv for getopt32 */
                 goto e_found;
             }
         }
     }
     proggie = NULL;
  e_found:
     // -g -G -t -r deleted, unimplemented -a deleted too
     getopt32(argv, "^"
         "np:s:ubvw:+"/* -w N */ IF_NC_SERVER("lk")
         IF_NC_EXTRA("i:o:z")
             "\0"
             "?2:vv"IF_NC_SERVER(":ll"), /* max 2 params; -v and -l are counters */
         &str_p, &str_s, &o_wait
         IF_NC_EXTRA(, &str_i, &str_o)
             , &o_verbose IF_NC_SERVER(, &cnt_l)
     );
     argv += optind;
 #if ENABLE_NC_EXTRA
     if (option_mask32 & OPT_i) /* line-interval time */
         o_interval = xatou_range(str_i, 1, 0xffff);
 #endif
 #if ENABLE_NC_SERVER
     //if (option_mask32 & OPT_l) /* listen mode */
     if (option_mask32 & OPT_k) /* persistent server mode */
         cnt_l = 2;
 #endif
     //if (option_mask32 & OPT_n) /* numeric-only, no DNS lookups */
     //if (option_mask32 & OPT_o) /* hexdump log */
     if (option_mask32 & OPT_p) { /* local source port */
         o_lport = bb_lookup_port(str_p, o_udpmode ? "udp" : "tcp", 0);
     }
     //if (option_mask32 & OPT_r) /* randomize various things */
     //if (option_mask32 & OPT_u) /* use UDP */
     //if (option_mask32 & OPT_v) /* verbose */
     //if (option_mask32 & OPT_w) /* wait time */
     //if (option_mask32 & OPT_z) /* little or no data xfer */
     /* We manage our fd's so that they are never 0,1,2 */
     /*bb_sanitize_stdio(); - not needed */
     if (argv[0]) {
         themaddr = xhost2sockaddr(argv[0],
             bb_lookup_port(argv[1], o_udpmode ? "udp" : "tcp", 0)
         );
     }
     /* create & bind network socket */
     x = (o_udpmode ? SOCK_DGRAM : SOCK_STREAM);
     if (option_mask32 & OPT_s) { /* local address */
         /* if o_lport is still 0, then we will use random port */
         ouraddr = xhost2sockaddr(str_s, o_lport);
 #ifdef BLOAT
         /* prevent spurious "UDP listen needs !0 port" */
         o_lport = get_nport(ouraddr);
         o_lport = ntohs(o_lport);
 #endif
         x = xsocket(ouraddr->u.sa.sa_family, x, 0);
     } else {
         /* We try IPv6, then IPv4, unless addr family is
          * implicitly set by way of remote addr/port spec */
         x = xsocket_type(&ouraddr,
                 (themaddr ? themaddr->u.sa.sa_family : AF_UNSPEC),
                 x);
         if (o_lport)
             set_nport(&ouraddr->u.sa, htons(o_lport));
     }
     xmove_fd(x, netfd);
     setsockopt_reuseaddr(netfd);
     if (o_udpmode) {
         if (o_bcmode)
             setsockopt_broadcast(netfd);
         socket_want_pktinfo(netfd);
     }
     if (!ENABLE_FEATURE_UNIX_LOCAL
      || cnt_l != 0 /* listen */
      || ouraddr->u.sa.sa_family != AF_UNIX
     ) {
         xbind(netfd, &ouraddr->u.sa, ouraddr->len);
     }
 #if 0
     setsockopt_SOL_SOCKET_int(netfd, SO_RCVBUF, o_rcvbuf);
     setsockopt_SOL_SOCKET_int(netfd, SO_SNDBUF, o_sndbuf);
 #endif
 #ifdef BLOAT
     if (OPT_l && (option_mask32 & (OPT_u|OPT_l)) == (OPT_u|OPT_l)) {
         /* apparently UDP can listen ON "port 0",
          but that's not useful */
         if (!o_lport)
             bb_simple_error_msg_and_die("UDP listen needs nonzero -p port");
     }
 #endif
     if (proggie) {
         close(STDIN_FILENO); /* won't need stdin */
         option_mask32 &= ~OPT_o; /* -o with -e is meaningless! */
     }
 #if ENABLE_NC_EXTRA
     if (o_ofile)
         xmove_fd(xopen(str_o, O_WRONLY|O_CREAT|O_TRUNC), ofd);
 #endif
     if (cnt_l != 0) {
         dolisten((cnt_l - 1), proggie);
         /* dolisten does its own connect reporting */
         x = readwrite(); /* it even works with UDP! */
     } else {
         /* Outbound connects.  Now we're more picky about args... */
         if (!themaddr)
             bb_show_usage();
         remend = *themaddr;
         if (o_verbose)
             themdotted = xmalloc_sockaddr2dotted(&themaddr->u.sa);
         x = connect_w_timeout(netfd);
         if (o_zero && x == 0 && o_udpmode)        /* if UDP scanning... */
             x = udptest();
         if (x == 0) {                        /* Yow, are we OPEN YET?! */
             if (o_verbose)
                 fprintf(stderr, "%s (%s) open\n", argv[0], themdotted);
             if (proggie)                        /* exec is valid for outbound, too */
                 doexec(proggie);
             if (!o_zero)
                 x = readwrite();
         } else { /* connect or udptest wasn't successful */
             x = 1;                                /* exit status */
             /* if we're scanning at a "one -v" verbosity level, don't print refusals.
              Give it another -v if you want to see everything. */
             if (o_verbose > 1 || (o_verbose && errno != ECONNREFUSED))
                 bb_perror_msg("%s (%s)", argv[0], themdotted);
         }
     }
     if (o_verbose > 1)                /* normally we don't care */
         fprintf(stderr, SENT_N_RECV_M, wrote_net, wrote_out);
     return x;
 }
References AF_UNIX, AF_UNSPEC, argv, bb_lookup_port(), bb_perror_msg(), bb_show_usage(), bb_signals(), bb_simple_error_msg_and_die(), close(), connect_w_timeout(), doexec(), dolisten(), ECONNREFUSED, errno, fprintf(), G, get_nport(), getopt32(), htons(), INIT_G, netfd, ntohs(), NULL, o_bcmode, O_CREAT, o_interval, o_ofile, O_TRUNC, o_udpmode, o_verbose, o_wait, O_WRONLY, o_zero, ofd, OPT_i, OPT_k, OPT_l, OPT_o, OPT_p, OPT_s, OPT_u, optind, option_mask32, optpos, ouraddr, readwrite(), remend, SENT_N_RECV_M, set_nport(), setsockopt_broadcast(), setsockopt_reuseaddr(), setsockopt_SOL_SOCKET_int(), SIG_IGN, SIGINT, SIGPIPE, SIGQUIT, SIGTERM, SIGURG, SO_RCVBUF, SO_SNDBUF, SOCK_DGRAM, SOCK_STREAM, socket_want_pktinfo(), stderr, STDIN_FILENO, strcmp, strspn(), themaddr, udptest(), wrote_net, wrote_out, x, xbind(), xhost2sockaddr(), xmalloc_sockaddr2dotted(), xmove_fd(), xopen(), xsocket(), and xsocket_type().
oprint()
void oprint (int direction, unsigned char * p, unsigned bc)
Referenced by readwrite().
readwrite()
static int readwrite (void) static
Definition at line 590 of file nc_bloaty.c.
 {
     char *zp = zp; /* gcc */  /* stdin buf ptr */
     char *np = np;            /* net-in buf ptr */
     unsigned rzleft;
     unsigned rnleft;
     unsigned netretry;              /* net-read retry counter */
     unsigned fds_open;
     struct pollfd pfds[2];
     pfds[0].fd = STDIN_FILENO;
     pfds[0].events = POLLIN;
     pfds[1].fd = netfd;
     pfds[1].events = POLLIN;
     fds_open = 2;
     netretry = 2;
     rzleft = rnleft = 0;
     if (o_interval)
         sleep(o_interval);                /* pause *before* sending stuff, too */
     /* and now the big ol' shoveling loop ... */
     /* nc 1.10 has "while (FD_ISSET(netfd)" here */
     while (fds_open) {
         int rr;
         int poll_tmout_ms;
         unsigned wretry = 8200;               /* net-write sanity counter */
         poll_tmout_ms = -1;
         if (o_wait) {
             poll_tmout_ms = INT_MAX;
             if (o_wait < INT_MAX / 1000)
                 poll_tmout_ms = o_wait * 1000;
         }
         rr = poll(pfds, 2, poll_tmout_ms);
         if (rr < 0 && errno != EINTR) {                /* might have gotten ^Zed, etc */
             holler_perror("poll");
             close(netfd);
             return 1;
         }
     /* if we have a timeout AND stdin is closed AND we haven't heard anything
      from the net during that time, assume it's dead and close it too. */
         if (rr == 0) {
             if (!pfds[0].revents) {
                 netretry--;                        /* we actually try a coupla times. */
                 if (!netretry) {
                     if (o_verbose > 1)         /* normally we don't care */
                         fprintf(stderr, "net timeout\n");
                     /*close(netfd); - redundant, exit will do it */
                     return 0;                  /* not an error! */
                 }
             }
         } /* timeout */
     /* Ding!!  Something arrived, go check all the incoming hoppers, net first */
         if (pfds[1].revents) {                /* net: ding! */
             rr = read(netfd, bigbuf_net, BIGSIZ);
             if (rr <= 0) {
                 if (rr < 0 && o_verbose > 1) {
                     /* nc 1.10 doesn't do this */
                     bb_simple_perror_msg("net read");
                 }
                 pfds[1].fd = -1;                   /* don't poll for netfd anymore */
                 fds_open--;
                 rzleft = 0;                        /* can't write anymore: broken pipe */
             } else {
                 rnleft = rr;
                 np = bigbuf_net;
             }
 Debug("got %d from the net, errno %d", rr, errno);
         } /* net:ding */
     /* if we're in "slowly" mode there's probably still stuff in the stdin
      buffer, so don't read unless we really need MORE INPUT!  MORE INPUT! */
         if (rzleft)
             goto shovel;
     /* okay, suck more stdin */
         if (pfds[0].revents) {                /* stdin: ding! */
             rr = read(STDIN_FILENO, bigbuf_in, BIGSIZ);
     /* Considered making reads here smaller for UDP mode, but 8192-byte
      mobygrams are kinda fun and exercise the reassembler. */
             if (rr <= 0) {                        /* at end, or fukt, or ... */
                 pfds[0].fd = -1;              /* disable stdin */
                 /*close(STDIN_FILENO); - not really necessary */
                 /* Let peer know we have no more data */
                 /* nc 1.10 doesn't do this: */
                 shutdown(netfd, SHUT_WR);
                 fds_open--;
             } else {
                 rzleft = rr;
                 zp = bigbuf_in;
             }
         } /* stdin:ding */
  shovel:
     /* now that we've dingdonged all our thingdings, send off the results.
      Geez, why does this look an awful lot like the big loop in "rsh"? ...
      not sure if the order of this matters, but write net -> stdout first. */
         if (rnleft) {
             rr = write(STDOUT_FILENO, np, rnleft);
             if (rr > 0) {
                 if (o_ofile) /* log the stdout */
                     oprint('<', (unsigned char *)np, rr);
                 np += rr;
                 rnleft -= rr;
                 wrote_out += rr; /* global count */
             }
 Debug("wrote %d to stdout, errno %d", rr, errno);
         } /* rnleft */
         if (rzleft) {
             if (o_interval)                        /* in "slowly" mode ?? */
                 rr = findline(zp, rzleft);
             else
                 rr = rzleft;
             rr = write(netfd, zp, rr);        /* one line, or the whole buffer */
             if (rr > 0) {
                 if (o_ofile) /* log what got sent */
                     oprint('>', (unsigned char *)zp, rr);
                 zp += rr;
                 rzleft -= rr;
                 wrote_net += rr; /* global count */
             }
 Debug("wrote %d to net, errno %d", rr, errno);
         } /* rzleft */
         if (o_interval) {                        /* cycle between slow lines, or ... */
             sleep(o_interval);
             continue;                        /* ...with hairy loop... */
         }
         if (rzleft || rnleft) {                  /* shovel that shit till they ain't */
             wretry--;                        /* none left, and get another load */
     /* net write retries sometimes happen on UDP connections */
             if (!wretry) {                   /* is something hung? */
                 holler_error("too many output retries");
                 return 1;
             }
             goto shovel;
         }
     } /* while (fds_open) */
     /* XXX: maybe want a more graceful shutdown() here, or screw around with
      linger times??  I suspect that I don't need to since I'm always doing
      blocking reads and writes and my own manual "last ditch" efforts to read
      the net again after a timeout.  I haven't seen any screwups yet, but it's
      not like my test network is particularly busy... */
     close(netfd);
     return 0;
 } /* readwrite */
References bb_simple_perror_msg(), bigbuf_in, bigbuf_net, BIGSIZ, close(), Debug, EINTR, errno, pollfd::events, pollfd::fd, findline(), fprintf(), holler_error, holler_perror, INT_MAX, netfd, o_interval, o_ofile, o_verbose, o_wait, oprint(), poll(), POLLIN, read(), pollfd::revents, SHUT_WR, shutdown(), sleep(), stderr, STDIN_FILENO, STDOUT_FILENO, write(), wrote_net, and wrote_out.
Referenced by nc_main().
tmtravel()
static void tmtravel (int sig UNUSED_PARAM) static
Definition at line 224 of file nc_bloaty.c.
 {
     unarm();
     longjmp(jbuf, 1);
 }
References jbuf, longjmp(), and unarm().
Referenced by arm().
udptest()
int udptest (void)
Referenced by nc_main().
unarm()
static void unarm (void) static
Definition at line 217 of file nc_bloaty.c.
 {
     signal(SIGALRM, SIG_IGN);
     alarm(0);
 }
References alarm(), SIG_IGN, SIGALRM, and signal.
Referenced by connect_w_timeout(), dolisten(), and tmtravel().