Fennix Userspace: Userspace/musl/src/string/strncmp.c File Reference
strncmp.c File Reference
#include <string.h>
Functions
int strncmp (const char *_l, const char *_r, size_t n)
Function Documentation
strncmp()
int strncmp (const char * _l, const char * _r, size_t n)
Definition at line 3 of file strncmp.c.
 {
     const unsigned char *l=(void *)_l, *r=(void *)_r;
     if (!n--) return 0;
     for (; *l && *r && n && *l == *r ; l++, r++, n--);
     return *l - *r;
 }
References i, l, n, s1, and s2.
Referenced by __dls3(), __get_resolv_conf(), __lookup_serv(), __putenv(), _rl_print_color_indicator(), add_or_supercede_exported_var(), add_split_dependencies(), append_mount_options(), bb_init_module_24(), check_existence_through_netlink(), colon(), comm_match(), command_generator(), complete_fncmp(), compute_lcd_of_matches(), conf_read_simple(), D_DoomMain(), dcngettext(), exclude(), extract_filename(), fixup_rpath(), get_local_var_value(), get_modinfo_value(), get_ptr_to_local_var(), getconf_one(), getenv(), getspnam_r(), getstat(), getsubopt(), handle_incoming_and_exit(), index_in_substrings(), is_colored(), is_prefixed_with(), last_main(), load_library(), M_StringReplace(), M_StringStartsWith(), main(), match(), match_opt(), md5crypt(), name_to_dev_t(), next_token(), ntp_init(), parse(), parse_one_line(), patch_main(), path_is_devfd(), polite_directory_format(), process_includes(), rdval_diskstats(), read_cmdline(), reverse_services(), scan_expression(), scan_request(), scan_table(), set_local_var(), sh_stat(), sha256crypt(), sha512crypt(), sha_crypt(), subevalvar(), tilde_find_prefix(), tilde_find_suffix(), tre_tnfa_run_backtrack(), uniq_main(), unsetenv(), utf8locale(), uuidcache_check_device(), and W_AddFile().