Fennix Kernel: x64 Namespace Reference
x64 Namespace Reference
Data Structures
union __packed
MSR_APIC_BASE structure.
union RFLAGS
struct TrapFrame
union EFER
union DR6
union DR7
union PageFaultErrorCode
union SelectorErrorCode
struct FXState
struct __packed.__aligned
struct __packed.__unnamed748__
struct RFLAGS.__unnamed757__
struct EFER.__unnamed773__
struct DR6.__unnamed775__
struct DR7.__unnamed777__
struct PageFaultErrorCode.__unnamed779__
struct SelectorErrorCode.__unnamed781__
Typedefs
typedef struct x64::TrapFrame TrapFrame
typedef union x64::EFER EFER
typedef union x64::DR6 DR6
typedef union x64::DR7 DR7
typedef union x64::PageFaultErrorCode PageFaultErrorCode
typedef union x64::SelectorErrorCode SelectorErrorCode
Functions
struct x64::FXState __aligned (16)
static SafeFunction void lgdt (void *gdt)
static SafeFunction void lidt (void *idt)
static SafeFunction void ltr (uint16_t Segment)
static SafeFunction void invlpg (void *Address)
static SafeFunction void cpuid (uint32_t Function, uint32_t *eax, uint32_t *ebx, uint32_t *ecx, uint32_t *edx)
CPUID.
static SafeFunction uint32_t GetHighestLeaf ()
static SafeFunction void fxsave (void *FXSaveArea)
static SafeFunction void fxrstor (void *FXRstorArea)
Data Structure Documentation
x64::__packed
union x64::__packed
MSR_APIC_BASE structure.
See also
MSR_APIC_BASE
Definition at line 529 of file cpu.hpp.
Data Fields
struct __packed __unnamed__
struct __packed __aligned
uint64_t raw
uint32_t raw
x64::RFLAGS
union x64::RFLAGS
Definition at line 563 of file cpu.hpp.
Data Fields
struct RFLAGS __unnamed__
uint64_t raw
x64::TrapFrame
struct x64::TrapFrame
Definition at line 615 of file cpu.hpp.
Data Fields
uint64_t cs
uint64_t ErrorCode
uint64_t InterruptNumber
uint64_t r10
uint64_t r11
uint64_t r12
uint64_t r13
uint64_t r14
uint64_t r15
uint64_t r8
uint64_t r9
uint64_t rax
uint64_t rbp
uint64_t rbx
uint64_t rcx
uint64_t rdi
uint64_t rdx
RFLAGS rflags
uint64_t rip
uint64_t rsi
uint64_t rsp
uint64_t ss
x64::EFER
union x64::EFER
Definition at line 644 of file cpu.hpp.
Data Fields
struct EFER __unnamed__
uint64_t raw
x64::DR6
union x64::DR6
Definition at line 674 of file cpu.hpp.
Data Fields
struct DR6 __unnamed__
uint64_t raw
x64::DR7
union x64::DR7
Definition at line 704 of file cpu.hpp.
Data Fields
struct DR7 __unnamed__
uint64_t raw
x64::PageFaultErrorCode
union x64::PageFaultErrorCode
Definition at line 758 of file cpu.hpp.
Data Fields
struct PageFaultErrorCode __unnamed__
uint64_t raw
x64::SelectorErrorCode
union x64::SelectorErrorCode
Definition at line 787 of file cpu.hpp.
Data Fields
struct SelectorErrorCode __unnamed__
uint64_t raw
x64::FXState
struct x64::FXState
Definition at line 808 of file cpu.hpp.
Data Fields
uint16_t fcw FPU control word.
uint16_t fop FPU opcode.
uint16_t fsw FPU status word.
uint8_t ftw FPU tag words.
uint32_t mxcsr SSE control register.
uint32_t mxcsrmask SSE control register mask.
uint64_t rdp FPU data pointer.
uint8_t Reserved Reserved (zero)
uint64_t rip PFU instruction pointer.
uint8_t st[8][16] FPU registers (last 6 bytes reserved)
uint8_t xmm[16][16] XMM registers.
x64::__packed.__aligned
struct x64::__packed.__aligned
Definition at line 531 of file cpu.hpp.
Data Fields
uint64_t ABAHigh: 32 APIC Base High Address.
uint64_t ABALow: 20 APIC Base Low Address.
uint64_t AE: 1
APIC Enable
uint64_t BSC: 1
Boot Strap CPU Core
uint64_t EXTD: 1
x2APIC Mode Enable
uint64_t Reserved0: 8
Reserved
uint64_t Reserved1: 1
Reserved
uint64_t Reserved2: 12
Reserved
x64::__packed.__unnamed748__
struct x64::__packed.__unnamed748__
Definition at line 555 of file cpu.hpp.
Data Fields
uint64_t AID: 8
uint64_t Reserved: 24
x64::RFLAGS.__unnamed757__
struct x64::RFLAGS.__unnamed757__
Definition at line 565 of file cpu.hpp.
Data Fields
uint64_t AC: 1 Alignment Check.
uint64_t AF: 1 Auxiliary Carry Flag.
uint64_t AlwaysOne: 1 Reserved.
uint64_t CF: 1 Carry Flag.
uint64_t DF: 1 Direction Flag.
uint64_t ID: 1 ID Flag (Allow using CPUID instruction)
uint64_t IF: 1 Interrupt Enable Flag.
uint64_t IOPL: 2 I/O Privilege Level.
uint64_t NT: 1 Nested Task.
uint64_t OF: 1 Overflow Flag.
uint64_t PF: 1 Parity Flag.
uint64_t Reserved0: 1 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 1 Reserved.
uint64_t Reserved3: 10 Reserved.
uint64_t RF: 1 Resume Flag.
uint64_t SF: 1 Sign Flag.
uint64_t TF: 1 Trap Flag.
uint64_t VIF: 1 Virtual Interrupt Flag.
uint64_t VIP: 1 Virtual Interrupt Pending.
uint64_t VM: 1 Virtual 8086 Mode.
uint64_t ZF: 1 Zero Flag.
x64::EFER.__unnamed773__
struct x64::EFER.__unnamed773__
Definition at line 646 of file cpu.hpp.
Data Fields
uint64_t FFXSR: 1 Enable Fast FXSAVE/FXRSTOR.
uint64_t LMA: 1 Indicates long.
uint64_t LME: 1 Enable long mode.
uint64_t LMSLE: 1 Enable Long Mode Segment Limit.
uint64_t NXE: 1 Enable No-Execute Bit.
uint64_t Reserved0: 7 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 32 Reserved.
uint64_t SCE: 1 Enable syscall & sysret instructions in 64-bit mode.
uint64_t SVME: 1 Enable Secure Virtual Machine.
uint64_t TCE: 1 Enable Translation Cache Extension.
x64::DR6.__unnamed775__
struct x64::DR6.__unnamed775__
Definition at line 676 of file cpu.hpp.
Data Fields
uint64_t B0: 1 Breakpoint #0 Condition Detected.
uint64_t B1: 1 Breakpoint #1 Condition Detected.
uint64_t B2: 1 Breakpoint #2 Condition Detected.
uint64_t B3: 1 Breakpoint #3 Condition Detected.
uint64_t BD: 1 Breakpoint Debug Access Detected.
uint64_t BS: 1 Breakpoint Single Step.
uint64_t BT: 1 Breakpoint Task Switch.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 1 Reserved.
uint64_t Reserved2: 15 Reserved.
uint64_t Reserved3: 32 Reserved.
x64::DR7.__unnamed777__
struct x64::DR7.__unnamed777__
Definition at line 706 of file cpu.hpp.
Data Fields
uint64_t G0: 1 Global Exact Breakpoint #0 Enabled.
uint64_t G1: 1 Global Exact Breakpoint #1 Enabled.
uint64_t G2: 1 Global Exact Breakpoint #2 Enabled.
uint64_t G3: 1 Global Exact Breakpoint #3 Enabled.
uint64_t GD: 1 General Detect Enabled.
uint64_t GE: 1 Global Exact Breakpoint Enabled.
uint64_t L0: 1 Local Exact Breakpoint #0 Enabled.
uint64_t L1: 1 Local Exact Breakpoint #1 Enabled.
uint64_t L2: 1 Local Exact Breakpoint #2 Enabled.
uint64_t L3: 1 Local Exact Breakpoint #3 Enabled.
uint64_t LE: 1 Local Exact Breakpoint Enabled.
uint64_t LEN0: 2 Length of Breakpoint #0.
uint64_t LEN1: 2 Length of Breakpoint #1.
uint64_t LEN2: 2 Length of Breakpoint #2.
uint64_t LEN3: 2 Length of Breakpoint #3.
uint64_t Reserved0: 1 Reserved.
uint64_t Reserved1: 2 Reserved.
uint64_t Reserved2: 2 Reserved.
uint64_t Reserved3: 32 Reserved.
uint64_t RW0: 2 Type of Transaction(s) to Trap.
uint64_t RW1: 2 Type of Transaction(s) to Trap.
uint64_t RW2: 2 Type of Transaction(s) to Trap.
uint64_t RW3: 2 Type of Transaction(s) to Trap.
x64::PageFaultErrorCode.__unnamed779__
struct x64::PageFaultErrorCode.__unnamed779__
Definition at line 760 of file cpu.hpp.
Data Fields
uint64_t I: 1 When set, the page fault was caused by an instruction fetch. This only applies when the No-Execute bit is supported and enabled.
uint64_t P: 1 When set, the page fault was caused by a page-protection violation. When not set, it was caused by a non-present page.
uint64_t PK: 1 When set, the page fault was caused by a protection-key violation. The PKRU register (for user-mode accesses) or PKRS MSR (for supervisor-mode accesses) specifies the protection key rights.
uint64_t R: 1 When set, one or more page directory entries contain reserved bits which are set to 1. This only applies when the PSE or PAE flags in CR4 are set to 1.
uint64_t Reserved0: 8 Reserved.
uint64_t Reserved1: 16 Reserved.
uint64_t SGX: 1 When set, the fault was due to an SGX violation. The fault is unrelated to ordinary paging.
uint64_t SS: 1 When set, the page fault was caused by a shadow stack access.
uint64_t U: 1 When set, the page fault was caused while CPL = 3. This does not necessarily mean that the page fault was a privilege violation.
uint64_t W: 1 When set, the page fault was caused by a write access. When not set, it was caused by a read access.
x64::SelectorErrorCode.__unnamed781__
struct x64::SelectorErrorCode.__unnamed781__
Definition at line 789 of file cpu.hpp.
Data Fields
uint64_t External: 1 When set, the exception originated externally to the processor.
uint64_t Idx: 13 The index in the GDT, IDT or LDT.
uint64_t Reserved: 16 Reserved.
uint64_t Table: 2 IDT/GDT/LDT Table.
0b00 - The Selector Index references a descriptor in the GDT.
0b01 - The Selector Index references a descriptor in the IDT.
0b10 - The Selector Index references a descriptor in the LDT.
0b11 - The Selector Index references a descriptor in the IDT.
Typedef Documentation
DR6
typedef union x64::DR6 x64::DR6
DR7
typedef union x64::DR7 x64::DR7
EFER
typedef union x64::EFER x64::EFER
PageFaultErrorCode
typedef union x64::PageFaultErrorCode x64::PageFaultErrorCode
SelectorErrorCode
typedef union x64::SelectorErrorCode x64::SelectorErrorCode
TrapFrame
typedef struct x64::TrapFrame x64::TrapFrame
Function Documentation
__aligned()
struct x64::FXState x64::__aligned (16)
cpuid()
static SafeFunction void x64::cpuid (uint32_t Function, uint32_t * eax, uint32_t * ebx, uint32_t * ecx, uint32_t * edx) inline static
CPUID.
Parameters
Function Leaf
eax EAX
ebx EBX
ecx ECX
edx EDX
Definition at line 880 of file cpu.hpp.
         {
 #ifdef a64
             asmv("cpuid"
                  : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx)
                  : "a"(Function));
 #endif
         }
References asmv().
Referenced by GetHighestLeaf(), CPU::Hypervisor(), CPU::Name(), and CPU::Vendor().
fxrstor()
static SafeFunction void x64::fxrstor (void * FXRstorArea) inline static
Definition at line 916 of file cpu.hpp.
         {
 #ifdef a64
             if (!FXRstorArea || FXRstorArea >= (char *)0xfffffffffffff000)
                 return;
             asmv("fxrstorq (%0)"
                  :
                  : "r"(FXRstorArea)
                  : "memory");
 #endif
         }
References asmv().
fxsave()
static SafeFunction void x64::fxsave (void * FXSaveArea) inline static
Definition at line 903 of file cpu.hpp.
         {
 #ifdef a64
             if (!FXSaveArea || FXSaveArea >= (char *)0xfffffffffffff000)
                 return;
             asmv("fxsaveq (%0)"
                  :
                  : "r"(FXSaveArea)
                  : "memory");
 #endif
         }
References asmv().
GetHighestLeaf()
static SafeFunction uint32_t x64::GetHighestLeaf () inline static
Definition at line 896 of file cpu.hpp.
         {
             uint32_t eax, ebx, ecx, edx;
             cpuid(0x0, &eax, &ebx, &ecx, &edx);
             return eax;
         }
References cpuid().
invlpg()
static SafeFunction void x64::invlpg (void * Address) inline static
Definition at line 861 of file cpu.hpp.
         {
 #ifdef a64
             asmv("invlpg (%0)"
                  :
                  : "r"(Address)
                  : "memory");
 #endif
         }
References Address, and asmv().
lgdt()
static SafeFunction void x64::lgdt (void * gdt) inline static
Definition at line 834 of file cpu.hpp.
         {
 #ifdef a64
             asmv("lgdt (%0)"
                  :
                  : "r"(gdt));
 #endif
         }
References asmv().
lidt()
static SafeFunction void x64::lidt (void * idt) inline static
Definition at line 843 of file cpu.hpp.
         {
 #ifdef a64
             asmv("lidt (%0)"
                  :
                  : "r"(idt));
 #endif
         }
References asmv().
ltr()
static SafeFunction void x64::ltr (uint16_t Segment) inline static
Definition at line 852 of file cpu.hpp.
         {
 #ifdef a64
             asmv("ltr %0"
                  :
                  : "r"(Segment));
 #endif
         }
References asmv().