Fennix Userspace: Userspace/apps/base/busybox/debianutils/pipe_progress.c File Reference
pipe_progress.c File Reference
#include "libbb.h"
Macros
#define PIPE_PROGRESS_SIZE 4096
Functions
int pipe_progress_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int pipe_progress_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Macro Definition Documentation
PIPE_PROGRESS_SIZE
#define PIPE_PROGRESS_SIZE 4096
Definition at line 24 of file pipe_progress.c.
Function Documentation
pipe_progress_main() [1/2]
int pipe_progress_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 30 of file pipe_progress.c.
 {
     char buf[PIPE_PROGRESS_SIZE];
     time_t t = time(NULL);
     int len;
     while ((len = safe_read(STDIN_FILENO, buf, PIPE_PROGRESS_SIZE)) > 0) {
         time_t new_time = time(NULL);
         if (new_time != t) {
             t = new_time;
             bb_putchar_stderr('.');
         }
         full_write(STDOUT_FILENO, buf, len);
     }
     bb_putchar_stderr('\n');
     return 0;
 }
References bb_putchar_stderr(), buf, full_write(), NULL, PIPE_PROGRESS_SIZE, safe_read(), STDIN_FILENO, STDOUT_FILENO, t, and time().
pipe_progress_main() [2/2]
int pipe_progress_main (int argc, char ** argv)