Fennix Userspace: Userspace/musl/src/ipc/semtimedop.c File Reference
semtimedop.c File Reference
#include <sys/sem.h>
#include <errno.h>
#include "syscall.h"
#include "ipc.h"
Macros
#define _GNU_SOURCE
#define IS32BIT(x) !((x)+0x80000000ULL>>32)
#define CLAMP(x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
#define NO_TIME32 1
Functions
int semtimedop (int id, struct sembuf *buf, size_t n, const struct timespec *ts)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file semtimedop.c.
CLAMP
#define CLAMP (x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Definition at line 8 of file semtimedop.c.
IS32BIT
#define IS32BIT (x) !((x)+0x80000000ULL>>32)
Definition at line 7 of file semtimedop.c.
NO_TIME32
#define NO_TIME32 1
Definition at line 12 of file semtimedop.c.
Function Documentation
semtimedop()
int semtimedop (int id, struct sembuf * buf, size_t n, const struct timespec * ts)
Definition at line 17 of file semtimedop.c.
 {
 #ifdef SYS_semtimedop_time64
     time_t s = ts ? ts->tv_sec : 0;
     long ns = ts ? ts->tv_nsec : 0;
     int r = -ENOSYS;
     if (NO_TIME32 || !IS32BIT(s))
         r = __syscall(SYS_semtimedop_time64, id, buf, n,
             ts ? ((long long[]){s, ns}) : 0);
     if (NO_TIME32 || r!=-ENOSYS) return __syscall_ret(r);
     ts = ts ? (void *)(long[]){CLAMP(s), ns} : 0;
 #endif
 #if defined(SYS_ipc)
     return syscall(SYS_ipc, IPCOP_semtimedop, id, n, 0, buf, ts);
 #elif defined(SYS_semtimedop)
     return syscall(SYS_semtimedop, id, buf, n, ts);
 #else
     return __syscall_ret(-ENOSYS);
 #endif
 }
References __syscall, __syscall_ret(), buf, CLAMP, ENOSYS, IPCOP_semtimedop, IS32BIT, n, NO_TIME32, SYS_semtimedop_time64, and syscall().
Referenced by __semtimedop_time32().