Fennix: Userspace/apps/base/busybox/procps/lsof.c File Reference
lsof.c File Reference
#include "libbb.h"
Functions
int lsof_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int lsof_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
lsof_main() [1/2]
int lsof_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 45 of file lsof.c.
 {
     procps_status_t *proc = NULL;
     while ((proc = procps_scan(proc, PSSCAN_PID|PSSCAN_EXE)) != NULL) {
         char name[sizeof("/proc/%u/fd/0123456789") + sizeof(int)*3];
         unsigned baseofs;
         DIR *d_fd;
         char *fdlink;
         struct dirent *entry;
         if (getpid() == proc->pid)
             continue;
         baseofs = sprintf(name, "/proc/%u/fd/", proc->pid);
         d_fd = opendir(name);
         if (d_fd) {
             while ((entry = readdir(d_fd)) != NULL) {
                 /* Skip entries '.' and '..' (and any hidden file) */
                 if (entry->d_name[0] == '.')
                     continue;
                 safe_strncpy(name + baseofs, entry->d_name, 10);
                 if ((fdlink = xmalloc_readlink(name)) != NULL) {
                     printf("%d\t%s\t%s\t%s\n", proc->pid, proc->exe, entry->d_name, fdlink);
                     free(fdlink);
                 }
             }
             closedir(d_fd);
         }
     }
     return EXIT_SUCCESS;
 }
References closedir(), EXIT_SUCCESS, free, getpid(), NULL, opendir(), proc::pid, printf, procps_scan(), PSSCAN_EXE, PSSCAN_PID, readdir(), safe_strncpy(), sprintf(), and xmalloc_readlink().
lsof_main() [2/2]
int lsof_main (int argc, char ** argv)