Fennix Userspace: Userspace/apps/base/busybox/coreutils/nl.c File Reference
nl.c File Reference
#include "libbb.h"
Functions
int nl_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
nl_main()
int nl_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 39 of file nl.c.
 {
     struct number_state ns;
     const char *opt_b = "t";
     enum {
         OPT_p = (1 << 0),
     };
 #if ENABLE_LONG_OPTS
     static const char nl_longopts[] ALIGN1 =
         "body-numbering\0"  Required_argument "b"
     //  "footer-numbering\0"    Required_argument "f" - not implemented yet
     //  "header-numbering\0"    Required_argument "h" - not implemented yet
     //  "section-delimiter\0"   Required_argument "d" - not implemented yet
         "line-increment\0"  Required_argument "i"
     //  "join-blank-lines\0"    Required_argument "l" - not implemented yet
     //  "number-format\0"   Required_argument "n" - not implemented yet
         "no-renumber\0"     No_argument       "p" // no-op so far
         "number-separator\0"    Required_argument "s"
         "starting-line-number\0"Required_argument "v"
         "number-width\0"    Required_argument "w"
     ;
 #endif
     int exitcode;
     ns.width = 6;
     ns.start = 1;
     ns.inc = 1;
     ns.sep = "\t";
     getopt32long(argv, "pw:+s:v:+i:+b:", nl_longopts,
             &ns.width, &ns.sep, &ns.start, &ns.inc, &opt_b);
     ns.all = (opt_b[0] == 'a');
     ns.nonempty = (opt_b[0] == 't');
     ns.empty_str = xasprintf("%*s", ns.width + (int)strlen(ns.sep), "");
     argv += optind;
     if (!*argv)
         *--argv = (char*)"-";
     exitcode = EXIT_SUCCESS;
     do {
         exitcode |= print_numbered_lines(&ns, *argv);
     } while (*++argv);
     fflush_stdout_and_exit(exitcode);
 }
References ALIGN1, number_state::all, argv, number_state::empty_str, EXIT_SUCCESS, exitcode, fflush_stdout_and_exit(), getopt32long, number_state::inc, No_argument, number_state::nonempty, OPT_p, optind, print_numbered_lines(), Required_argument, number_state::sep, number_state::start, strlen(), number_state::width, and xasprintf().