Fennix Userspace: Userspace/mlibc/tests/posix/getcwd.c File Reference
getcwd.c File Reference
#include <assert.h>
#include <limits.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 7 of file getcwd.c.
            {
     char buf[PATH_MAX];
     char *ret = getcwd(buf, PATH_MAX);
     assert(ret);
     assert((strlen(ret) == strlen(buf)) && strlen(ret));
     assert(!strcmp(ret, buf));
     char *ret2 = getcwd(NULL, 0);
     assert(ret2);
     assert(strlen(ret2));
     assert(!strcmp(ret, ret2));
     free(ret2);
     return 0;
 }
References assert, buf, free(), getcwd(), NULL, PATH_MAX, ret, strcmp(), and strlen().