Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/w_wad.h File Reference
w_wad.h File Reference
#include <stdio.h>
#include "doomtype.h"
#include "d_mode.h"
#include "w_file.h"
Data Structures
struct lumpinfo_s
Typedefs
typedef struct lumpinfo_s lumpinfo_t
Functions
wad_file_t * W_AddFile (char *filename)
int W_CheckNumForName (char *name)
int W_GetNumForName (char *name)
int W_LumpLength (unsigned int lump)
void W_ReadLump (unsigned int lump, void *dest)
void * W_CacheLumpNum (int lump, int tag)
void * W_CacheLumpName (char *name, int tag)
void W_GenerateHashTable (void)
unsigned int W_LumpNameHash (const char *s)
void W_ReleaseLumpNum (int lump)
void W_ReleaseLumpName (char *name)
void W_CheckCorrectIWAD (GameMission_t mission)
Variables
lumpinfo_t * lumpinfo
unsigned int numlumps
Data Structure Documentation
lumpinfo_s
struct lumpinfo_s
Definition at line 41 of file w_wad.h.
Data Fields
void * cache
char name[8]
lumpinfo_t * next
int position
int size
wad_file_t * wad_file
Typedef Documentation
lumpinfo_t
typedef struct lumpinfo_s lumpinfo_t
Definition at line 1 of file w_wad.h.
Function Documentation
W_AddFile()
wad_file_t* W_AddFile (char * filename)
Definition at line 139 of file w_wad.c.
 {
     wadinfo_t header;
     lumpinfo_t *lump_p;
     unsigned int i;
     wad_file_t *wad_file;
     int length;
     int startlump;
     filelump_t *fileinfo;
     filelump_t *filerover;
     int newnumlumps;
     // open the file and add to directory
     wad_file = W_OpenFile(filename);
     if (wad_file == NULL)
     {
         printf (" couldn't open %s\n", filename);
         return NULL;
     }
     newnumlumps = numlumps;
     if (strcasecmp(filename+strlen(filename)-3 , "wad" ) )
     {
         // single lump file
         // fraggle: Swap the filepos and size here.  The WAD directory
         // parsing code expects a little-endian directory, so will swap
         // them back.  Effectively we're constructing a "fake WAD directory"
         // here, as it would appear on disk.
         fileinfo = Z_Malloc(sizeof(filelump_t), PU_STATIC, 0);
         fileinfo->filepos = LONG(0);
         fileinfo->size = LONG(wad_file->length);
         // Name the lump after the base of the filename (without the
         // extension).
         M_ExtractFileBase (filename, fileinfo->name);
         newnumlumps++;
     }
     else
     {
         // WAD file
         W_Read(wad_file, 0, &header, sizeof(header));
         if (strncmp(header.identification,"IWAD",4))
         {
             // Homebrew levels?
             if (strncmp(header.identification,"PWAD",4))
             {
             I_Error ("Wad file %s doesn't have IWAD "
                  "or PWAD id\n", filename);
             }
             // ???modifiedgame = true;
         }
         header.numlumps = LONG(header.numlumps);
         header.infotableofs = LONG(header.infotableofs);
         length = header.numlumps*sizeof(filelump_t);
         fileinfo = Z_Malloc(length, PU_STATIC, 0);
         W_Read(wad_file, header.infotableofs, fileinfo, length);
         newnumlumps += header.numlumps;
     }
     // Increase size of numlumps array to accomodate the new file.
     startlump = numlumps;
     ExtendLumpInfo(newnumlumps);
     lump_p = &lumpinfo[startlump];
     filerover = fileinfo;
     for (i=startlump; i<numlumps; ++i)
     {
         lump_p->wad_file = wad_file;
         lump_p->position = LONG(filerover->filepos);
         lump_p->size = LONG(filerover->size);
             lump_p->cache = NULL;
         strncpy(lump_p->name, filerover->name, 8);
             ++lump_p;
             ++filerover;
     }
     Z_Free(fileinfo);
     if (lumphash != NULL)
     {
         Z_Free(lumphash);
         lumphash = NULL;
     }
     return wad_file;
 }
References lumpinfo_s::cache, ExtendLumpInfo(), i, I_Error(), _wad_file_s::length, LONG, lumphash, lumpinfo, M_ExtractFileBase(), lumpinfo_s::name, NULL, numlumps, lumpinfo_s::position, printf(), PU_STATIC, lumpinfo_s::size, strcasecmp(), strlen(), strncmp(), strncpy(), W_OpenFile(), W_Read(), lumpinfo_s::wad_file, Z_Free(), and Z_Malloc().
Referenced by D_AddFile(), and W_ParseCommandLine().
W_CacheLumpName()
void* W_CacheLumpName (char * name, int tag)
Definition at line 429 of file w_wad.c.
 {
     return W_CacheLumpNum(W_GetNumForName(name), tag);
 }
References name, W_CacheLumpNum(), and W_GetNumForName().
Referenced by AM_loadPics(), D_Display(), D_Endoom(), D_PageDrawer(), F_ArtScreenDrawer(), F_BunnyScroll(), F_CastDrawer(), F_TextWrite(), G_DoPlayDemo(), HU_Init(), M_DrawEmptyCell(), M_DrawEpisode(), M_Drawer(), M_DrawLoad(), M_DrawMainMenu(), M_DrawNewGame(), M_DrawOptions(), M_DrawReadThis1(), M_DrawReadThis2(), M_DrawSave(), M_DrawSaveLoadBorder(), M_DrawSelCell(), M_DrawSound(), M_DrawThermo(), M_Responder(), R_FillBackScreen(), R_InitTextures(), ST_loadCallback(), STlib_init(), V_LoadTintTable(), V_LoadXlaTable(), V_ScreenShot(), WI_loadCallback(), and WI_loadData().
W_CacheLumpNum()
void* W_CacheLumpNum (int lump, int tag)
Definition at line 382 of file w_wad.c.
 {
     byte *result;
     lumpinfo_t *lump;
     if ((unsigned)lumpnum >= numlumps)
     {
     I_Error ("W_CacheLumpNum: %i >= numlumps", lumpnum);
     }
     lump = &lumpinfo[lumpnum];
     // Get the pointer to return.  If the lump is in a memory-mapped
     // file, we can just return a pointer to within the memory-mapped
     // region.  If the lump is in an ordinary file, we may already
     // have it cached; otherwise, load it into memory.
     if (lump->wad_file->mapped != NULL)
     {
         // Memory mapped file, return from the mmapped region.
         result = lump->wad_file->mapped + lump->position;
     }
     else if (lump->cache != NULL)
     {
         // Already cached, so just switch the zone tag.
         result = lump->cache;
         Z_ChangeTag(lump->cache, tag);
     }
     else
     {
         // Not yet loaded, so load it now
         lump->cache = Z_Malloc(W_LumpLength(lumpnum), tag, &lump->cache);
     W_ReadLump (lumpnum, lump->cache);
         result = lump->cache;
     }
     return result;
 }
References lumpinfo_s::cache, I_Error(), lumpinfo, _wad_file_s::mapped, NULL, numlumps, lumpinfo_s::position, mlibc::result, W_LumpLength(), W_ReadLump(), lumpinfo_s::wad_file, Z_ChangeTag, and Z_Malloc().
Referenced by F_CastDrawer(), P_LoadLineDefs(), P_LoadNodes(), P_LoadReject(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_LoadThings(), P_LoadVertexes(), R_DrawPlanes(), R_DrawVisSprite(), R_GenerateComposite(), R_GenerateLookup(), R_GetColumn(), R_InitColormaps(), R_InitSpriteLumps(), R_PrecacheLevel(), S_ChangeMusic(), ST_doPaletteStuff(), ST_Stop(), and W_CacheLumpName().
W_CheckCorrectIWAD()
void W_CheckCorrectIWAD (GameMission_t mission)
Definition at line 586 of file w_wad.c.
 {
     int i;
     int lumpnum;
     for (i = 0; i < arrlen(unique_lumps); ++i)
     {
         if (mission != unique_lumps[i].mission)
         {
             lumpnum = W_CheckNumForName(unique_lumps[i].lumpname);
             if (lumpnum >= 0)
             {
                 I_Error("\nYou are trying to use a %s IWAD file with "
                         "the %s%s binary.\nThis isn't going to work.\n"
                         "You probably want to use the %s%s binary.",
                         D_SuggestGameName(unique_lumps[i].mission,
                                           indetermined),
                         PROGRAM_PREFIX,
                         D_GameMissionString(mission),
                         PROGRAM_PREFIX,
                         D_GameMissionString(unique_lumps[i].mission));
             }
         }
     }
 }
References arrlen, D_GameMissionString(), D_SuggestGameName(), i, I_Error(), indetermined, PROGRAM_PREFIX, unique_lumps, and W_CheckNumForName().
Referenced by D_DoomMain().
W_CheckNumForName()
int W_CheckNumForName (char * name)
Definition at line 256 of file w_wad.c.
 {
     lumpinfo_t *lump_p;
     int i;
     // Do we have a hash table yet?
     if (lumphash != NULL)
     {
         int hash;
         // We do! Excellent.
         hash = W_LumpNameHash(name) % numlumps;
         for (lump_p = lumphash[hash]; lump_p != NULL; lump_p = lump_p->next)
         {
             if (!strncasecmp(lump_p->name, name, 8))
             {
                 return lump_p - lumpinfo;
             }
         }
     }
     else
     {
         // We don't have a hash table generate yet. Linear search :-(
         //
         // scan backwards so patch lump files take precedence
         for (i=numlumps-1; i >= 0; --i)
         {
             if (!strncasecmp(lumpinfo[i].name, name, 8))
             {
                 return i;
             }
         }
     }
     // TFB. Not found.
     return -1;
 }
References i, lumphash, lumpinfo, lumpinfo_s::name, name, lumpinfo_s::next, NULL, numlumps, mlibc::strncasecmp(), and W_LumpNameHash().
Referenced by D_DoAdvanceDemo(), D_DoomMain(), D_IdentifyVersion(), D_SetGameDescription(), G_SecretExitLevel(), InitConnectData(), P_InitPicAnims(), R_FlatNumForName(), R_InitTextures(), ReadDMXConfig(), W_CheckCorrectIWAD(), W_GetNumForName(), and WI_loadUnloadData().
W_GenerateHashTable()
void W_GenerateHashTable (void)
Definition at line 539 of file w_wad.c.
 {
     unsigned int i;
     // Free the old hash table, if there is one
     if (lumphash != NULL)
     {
         Z_Free(lumphash);
     }
     // Generate hash table
     if (numlumps > 0)
     {
         lumphash = Z_Malloc(sizeof(lumpinfo_t *) * numlumps, PU_STATIC, NULL);
         memset(lumphash, 0, sizeof(lumpinfo_t *) * numlumps);
         for (i=0; i<numlumps; ++i)
         {
             unsigned int hash;
             hash = W_LumpNameHash(lumpinfo[i].name) % numlumps;
             // Hook into the hash table
             lumpinfo[i].next = lumphash[hash];
             lumphash[hash] = &lumpinfo[i];
         }
     }
     // All done!
 }
References i, lumphash, lumpinfo, memset(), name, lumpinfo_s::next, NULL, numlumps, PU_STATIC, W_LumpNameHash(), Z_Free(), and Z_Malloc().
Referenced by D_DoomMain().
W_GetNumForName()
int W_GetNumForName (char * name)
Definition at line 306 of file w_wad.c.
 {
     int i;
     i = W_CheckNumForName (name);
     if (i < 0)
     {
         I_Error ("W_GetNumForName: %s not found!", name);
     }
     return i;
 }
References i, I_Error(), name, and W_CheckNumForName().
Referenced by P_SetupLevel(), R_InitColormaps(), R_InitFlats(), R_InitSpriteDefs(), R_InitSpriteLumps(), R_InitTextures(), ReadDMXConfig(), S_ChangeMusic(), ST_loadData(), W_CacheLumpName(), and W_ReleaseLumpName().
W_LumpLength()
int W_LumpLength (unsigned int lump)
Definition at line 325 of file w_wad.c.
 {
     if (lump >= numlumps)
     {
     I_Error ("W_LumpLength: %i >= numlumps", lump);
     }
     return lumpinfo[lump].size;
 }
References I_Error(), lumpinfo, numlumps, and lumpinfo_s::size.
Referenced by P_LoadBlockMap(), P_LoadLineDefs(), P_LoadNodes(), P_LoadReject(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_LoadThings(), P_LoadVertexes(), R_InitTextures(), ReadDMXConfig(), S_ChangeMusic(), and W_CacheLumpNum().
W_LumpNameHash()
unsigned int W_LumpNameHash (const char * s)
Definition at line 70 of file w_wad.c.
 {
     // This is the djb2 string hash function, modded to work on strings
     // that have a maximum length of 8.
     unsigned int result = 5381;
     unsigned int i;
     for (i=0; i < 8 && s[i] != '\0'; ++i)
     {
         result = ((result << 5) ^ result ) ^ toupper((int)s[i]);
     }
     return result;
 }
References i, mlibc::result, and toupper.
Referenced by GenerateTextureHashTable(), R_CheckTextureNumForName(), W_CheckNumForName(), and W_GenerateHashTable().
W_ReadLump()
void W_ReadLump (unsigned int lump, void * dest)
Definition at line 342 of file w_wad.c.
 {
     int c;
     lumpinfo_t *l;
     if (lump >= numlumps)
     {
     I_Error ("W_ReadLump: %i >= numlumps", lump);
     }
     l = lumpinfo+lump;
     I_BeginRead ();
     c = W_Read(l->wad_file, l->position, dest, l->size);
     if (c < l->size)
     {
     I_Error ("W_ReadLump: only read %i of %i on lump %i",
          c, l->size, lump);
     }
     I_EndRead ();
 }
References c, I_BeginRead(), I_EndRead(), I_Error(), lumpinfo, numlumps, lumpinfo_s::position, lumpinfo_s::size, size, W_Read(), and lumpinfo_s::wad_file.
Referenced by P_LoadBlockMap(), P_LoadReject(), ReadDMXConfig(), and W_CacheLumpNum().
W_ReleaseLumpName()
void W_ReleaseLumpName (char * name)
Definition at line 465 of file w_wad.c.
 {
     W_ReleaseLumpNum(W_GetNumForName(name));
 }
References name, W_GetNumForName(), and W_ReleaseLumpNum().
Referenced by AM_unloadPics(), G_CheckDemoStatus(), R_InitTextures(), ST_unloadCallback(), and WI_unloadCallback().
W_ReleaseLumpNum()
void W_ReleaseLumpNum (int lump)
Definition at line 444 of file w_wad.c.
 {
     lumpinfo_t *lump;
     if ((unsigned)lumpnum >= numlumps)
     {
     I_Error ("W_ReleaseLumpNum: %i >= numlumps", lumpnum);
     }
     lump = &lumpinfo[lumpnum];
     if (lump->wad_file->mapped != NULL)
     {
         // Memory-mapped file, so nothing needs to be done here.
     }
     else
     {
         Z_ChangeTag(lump->cache, PU_CACHE);
     }
 }
References lumpinfo_s::cache, I_Error(), lumpinfo, _wad_file_s::mapped, NULL, numlumps, PU_CACHE, lumpinfo_s::wad_file, and Z_ChangeTag.
Referenced by P_LoadLineDefs(), P_LoadNodes(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_LoadThings(), P_LoadVertexes(), R_DrawPlanes(), S_StopMusic(), and W_ReleaseLumpName().
Variable Documentation
lumpinfo
lumpinfo_t* lumpinfo extern
Definition at line 61 of file w_wad.c.
Referenced by D_DoomMain(), D_IdentifyVersion(), ExtendLumpInfo(), R_InitSpriteDefs(), R_PrecacheLevel(), W_AddFile(), W_CacheLumpNum(), W_CheckNumForName(), W_Checksum(), W_GenerateHashTable(), W_LumpLength(), W_ReadLump(), and W_ReleaseLumpNum().
numlumps
unsigned int numlumps extern
Definition at line 62 of file w_wad.c.
Referenced by D_DoomMain(), D_IdentifyVersion(), ExtendLumpInfo(), W_AddFile(), W_CacheLumpNum(), W_CheckNumForName(), W_Checksum(), W_GenerateHashTable(), W_LumpLength(), W_NumLumps(), W_ReadLump(), and W_ReleaseLumpNum().