Fennix Userspace: Userspace/apps/base/busybox/libbb/run_shell.c File Reference
run_shell.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC exec_shell (const char *shell, int loginshell, const char **additional_args)
void FAST_FUNC exec_login_shell (const char *shell)
void FAST_FUNC exec_prog_or_SHELL (char **argv)
Function Documentation
exec_login_shell()
void FAST_FUNC exec_login_shell (const char * shell)
Definition at line 87 of file run_shell.c.
 {
     exec_shell(shell, 1, NULL);
 }
References exec_shell(), and NULL.
Referenced by exec_prog_or_SHELL(), and login_main().
exec_prog_or_SHELL()
void FAST_FUNC exec_prog_or_SHELL (char ** argv)
Definition at line 93 of file run_shell.c.
 {
     if (argv[0]) {
         BB_EXECVP_or_die(argv);
     }
     /* Both users (nsenter and unshare) do indeed exec
      * a _login_ shell (with dash in argv[0])!
      */
     exec_login_shell(getenv("SHELL"));
 }
References argv, BB_EXECVP_or_die(), exec_login_shell(), and getenv.
Referenced by nsenter_main(), and unshare_main().
exec_shell()
void FAST_FUNC exec_shell (const char * shell, int loginshell, const char ** additional_args)
Definition at line 54 of file run_shell.c.
 {
     const char **args;
     args = additional_args;
     while (args && *args)
         args++;
     args = xzalloc(sizeof(args[0]) * (2 + (args - additional_args)));
     if (!shell || !shell[0])
         shell = DEFAULT_SHELL;
     args[0] = bb_get_last_path_component_nostrip(shell);
     if (loginshell)
         args[0] = xasprintf("-%s", args[0]);
     /*args[1] = NULL; - already is */
     if (additional_args) {
         int cnt = 0;
         while (*additional_args)
             args[++cnt] = *additional_args++;
     }
 #if ENABLE_SELINUX
     if (current_sid)
         setexeccon(current_sid);
     if (ENABLE_FEATURE_CLEAN_UP)
         freecon(current_sid);
 #endif
     execv(shell, (char **) args);
     bb_perror_msg_and_die("can't execute '%s'", shell);
 }
References args, bb_get_last_path_component_nostrip(), bb_perror_msg_and_die(), cnt, DEFAULT_SHELL, execv(), xasprintf(), and xzalloc().
Referenced by exec_login_shell(), su_main(), and sulogin_main().