Fennix Userspace: Userspace/mlibc/options/ansi/musl-generic-math/__rem_pio2f.c File Reference
__rem_pio2f.c File Reference
#include "libm.h"
Macros
#define EPS DBL_EPSILON
Functions
int __rem_pio2f (float x, double *y)
Variables
static const double toint = 1.5/EPS
static const double invpio2 = 6.36619772367581382433e-01
static const double pio2_1 = 1.57079631090164184570e+00
static const double pio2_1t = 1.58932547735281966916e-08
Macro Definition Documentation
EPS
#define EPS DBL_EPSILON
Definition at line 26 of file __rem_pio2f.c.
Function Documentation
__rem_pio2f()
int __rem_pio2f (float x, double * y)
Definition at line 42 of file __rem_pio2f.c.
 {
     union {float f; uint32_t i;} u = {x};
     double tx[1],ty[1];
     double_t fn;
     uint32_t ix;
     int n, sign, e0;
     ix = u.i & 0x7fffffff;
     /* 25+53 bit pi is good enough for medium size */
     if (ix < 0x4dc90fdb) {  /* |x| ~< 2^28*(pi/2), medium size */
         /* Use a specialized rint() to get fn.  Assume round-to-nearest. */
         fn = (double_t)x*invpio2 + toint - toint;
         n  = (int32_t)fn;
         *y = x - fn*pio2_1 - fn*pio2_1t;
         return n;
     }
     if(ix>=0x7f800000) {  /* x is inf or NaN */
         *y = x-x;
         return 0;
     }
     /* scale x into [2^23, 2^24-1] */
     sign = u.i>>31;
     e0 = (ix>>23) - (0x7f+23);  /* e0 = ilogb(|x|)-23, positive */
     u.i = ix - (e0<<23);
     tx[0] = u.f;
     n  =  __rem_pio2_large(tx,ty,e0,1,0);
     if (sign) {
         *y = -ty[0];
         return -n;
     }
     *y = ty[0];
     return n;
 }
References __rem_pio2_large(), i, invpio2, n, pio2_1, pio2_1t, toint, x, and y.
Referenced by cosf(), sincosf(), sinf(), and tanf().
Variable Documentation
invpio2
const double invpio2 = 6.36619772367581382433e-01 static
Definition at line 38 of file __rem_pio2f.c.
Referenced by __rem_pio2f().
pio2_1
const double pio2_1 = 1.57079631090164184570e+00 static
Definition at line 39 of file __rem_pio2f.c.
Referenced by __rem_pio2f().
pio2_1t
const double pio2_1t = 1.58932547735281966916e-08 static
Definition at line 40 of file __rem_pio2f.c.
Referenced by __rem_pio2f().
toint
const double toint = 1.5/EPS static
Definition at line 37 of file __rem_pio2f.c.
Referenced by __rem_pio2f().