Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/v_video.h File Reference
v_video.h File Reference
#include "doomtype.h"
#include "v_patch.h"
Macros
#define CENTERY (SCREENHEIGHT/2)
Typedefs
typedef boolean(* vpatchclipfunc_t) (patch_t *, int, int)
Functions
void V_SetPatchClipCallback (vpatchclipfunc_t func)
void V_Init (void)
void V_CopyRect (int srcx, int srcy, byte *source, int width, int height, int destx, int desty)
void V_DrawPatch (int x, int y, patch_t *patch)
void V_DrawPatchFlipped (int x, int y, patch_t *patch)
void V_DrawTLPatch (int x, int y, patch_t *patch)
void V_DrawAltTLPatch (int x, int y, patch_t *patch)
void V_DrawShadowedPatch (int x, int y, patch_t *patch)
void V_DrawXlaPatch (int x, int y, patch_t *patch)
void V_DrawPatchDirect (int x, int y, patch_t *patch)
void V_DrawBlock (int x, int y, int width, int height, byte *src)
void V_MarkRect (int x, int y, int width, int height)
void V_DrawFilledBox (int x, int y, int w, int h, int c)
void V_DrawHorizLine (int x, int y, int w, int c)
void V_DrawVertLine (int x, int y, int h, int c)
void V_DrawBox (int x, int y, int w, int h, int c)
void V_DrawRawScreen (byte *raw)
void V_UseBuffer (byte *buffer)
void V_RestoreBuffer (void)
void V_ScreenShot (char *format)
void V_LoadTintTable (void)
void V_LoadXlaTable (void)
void V_DrawMouseSpeedBox (int speed)
Variables
int dirtybox [4]
byte * tinttable
Macro Definition Documentation
CENTERY
#define CENTERY (SCREENHEIGHT/2)
Definition at line 34 of file v_video.h.
Typedef Documentation
vpatchclipfunc_t
typedef boolean(* vpatchclipfunc_t) (patch_t *, int, int)
Definition at line 44 of file v_video.h.
Function Documentation
V_CopyRect()
void V_CopyRect (int srcx, int srcy, byte * source, int width, int height, int destx, int desty)
Definition at line 85 of file v_video.c.
 {
     byte *src;
     byte *dest;
 #ifdef RANGECHECK
     if (srcx < 0
      || srcx + width > SCREENWIDTH
      || srcy < 0
      || srcy + height > SCREENHEIGHT
      || destx < 0
      || destx + width > SCREENWIDTH
      || desty < 0
      || desty + height > SCREENHEIGHT)
     {
         I_Error ("Bad V_CopyRect");
     }
 #endif
     V_MarkRect(destx, desty, width, height);
     src = source + SCREENWIDTH * srcy + srcx;
     dest = dest_screen + SCREENWIDTH * desty + destx;
     for ( ; height>0 ; height--)
     {
         memcpy(dest, src, width);
         src += SCREENWIDTH;
         dest += SCREENWIDTH;
     }
 }
References dest_screen, height(), I_Error(), memcpy, SCREENHEIGHT, SCREENWIDTH, source, src, V_MarkRect(), and width.
Referenced by ST_refreshBackground(), STlib_drawNum(), STlib_updateBinIcon(), and STlib_updateMultIcon().
V_DrawAltTLPatch()
void V_DrawAltTLPatch (int x, int y, patch_t * patch)
Definition at line 378 of file v_video.c.
 {
     int count, col;
     column_t *column;
     byte *desttop, *dest, *source;
     int w;
     y -= SHORT(patch->topoffset);
     x -= SHORT(patch->leftoffset);
     if (x < 0
      || x + SHORT(patch->width) > SCREENWIDTH
      || y < 0
      || y + SHORT(patch->height) > SCREENHEIGHT)
     {
         I_Error("Bad V_DrawAltTLPatch");
     }
     col = 0;
     desttop = dest_screen + y * SCREENWIDTH + x;
     w = SHORT(patch->width);
     for (; col < w; x++, col++, desttop++)
     {
         column = (column_t *) ((byte *) patch + LONG(patch->columnofs[col]));
         // step through the posts in a column
         while (column->topdelta != 0xff)
         {
             source = (byte *) column + 3;
             dest = desttop + column->topdelta * SCREENWIDTH;
             count = column->length;
             while (count--)
             {
                 *dest = tinttable[((*dest) << 8) + *source++];
                 dest += SCREENWIDTH;
             }
             column = (column_t *) ((byte *) column + column->length + 4);
         }
     }
 }
References count, dest_screen, I_Error(), LONG, SCREENHEIGHT, SCREENWIDTH, SHORT, source, tinttable, w, x, and y.
V_DrawBlock()
void V_DrawBlock (int x, int y, int width, int height, byte * src)
Definition at line 503 of file v_video.c.
 {
     byte *dest;
 #ifdef RANGECHECK
     if (x < 0
      || x + width >SCREENWIDTH
      || y < 0
      || y + height > SCREENHEIGHT)
     {
     I_Error ("Bad V_DrawBlock");
     }
 #endif
     V_MarkRect (x, y, width, height);
     dest = dest_screen + y * SCREENWIDTH + x;
     while (height--)
     {
     memcpy (dest, src, width);
     src += width;
     dest += SCREENWIDTH;
     }
 }
References dest_screen, height(), I_Error(), memcpy, SCREENHEIGHT, SCREENWIDTH, src, V_MarkRect(), width, x, and y.
Referenced by wipe_EndScreen().
V_DrawBox()
void V_DrawBox (int x, int y, int w, int h, int c)
Definition at line 576 of file v_video.c.
 {
     V_DrawHorizLine(x, y, w, c);
     V_DrawHorizLine(x, y+h-1, w, c);
     V_DrawVertLine(x, y, h, c);
     V_DrawVertLine(x+w-1, y, h, c);
 }
References c, h, V_DrawHorizLine(), V_DrawVertLine(), w, x, and y.
Referenced by V_DrawMouseSpeedBox().
V_DrawFilledBox()
void V_DrawFilledBox (int x, int y, int w, int h, int c)
Definition at line 529 of file v_video.c.
 {
     uint8_t *buf, *buf1;
     int x1, y1;
     buf = I_VideoBuffer + SCREENWIDTH * y + x;
     for (y1 = 0; y1 < h; ++y1)
     {
         buf1 = buf;
         for (x1 = 0; x1 < w; ++x1)
         {
             *buf1++ = c;
         }
         buf += SCREENWIDTH;
     }
 }
References buf, c, h, I_VideoBuffer, SCREENWIDTH, w, x, y, and y1().
Referenced by V_DrawMouseSpeedBox().
V_DrawHorizLine()
void V_DrawHorizLine (int x, int y, int w, int c)
Definition at line 549 of file v_video.c.
 {
     uint8_t *buf;
     int x1;
     buf = I_VideoBuffer + SCREENWIDTH * y + x;
     for (x1 = 0; x1 < w; ++x1)
     {
         *buf++ = c;
     }
 }
References buf, c, I_VideoBuffer, SCREENWIDTH, w, x, and y.
Referenced by V_DrawBox(), and V_DrawMouseSpeedBox().
V_DrawMouseSpeedBox()
void V_DrawMouseSpeedBox (int speed)
Definition at line 846 of file v_video.c.
 {
     extern int usemouse;
     int bgcolor, bordercolor, red, black, white, yellow;
     int box_x, box_y;
     int original_speed;
     int redline_x;
     int linelen;
     // Get palette indices for colors for widget. These depend on the
     // palette of the game being played.
     bgcolor = I_GetPaletteIndex(0x77, 0x77, 0x77);
     bordercolor = I_GetPaletteIndex(0x55, 0x55, 0x55);
     red = I_GetPaletteIndex(0xff, 0x00, 0x00);
     black = I_GetPaletteIndex(0x00, 0x00, 0x00);
     yellow = I_GetPaletteIndex(0xff, 0xff, 0x00);
     white = I_GetPaletteIndex(0xff, 0xff, 0xff);
     // If the mouse is turned off or acceleration is turned off, don't
     // draw the box at all.
     if (!usemouse || fabs(mouse_acceleration - 1) < 0.01)
     {
         return;
     }
     // Calculate box position
     box_x = SCREENWIDTH - MOUSE_SPEED_BOX_WIDTH - 10;
     box_y = 15;
     V_DrawFilledBox(box_x, box_y,
                     MOUSE_SPEED_BOX_WIDTH, MOUSE_SPEED_BOX_HEIGHT, bgcolor);
     V_DrawBox(box_x, box_y,
               MOUSE_SPEED_BOX_WIDTH, MOUSE_SPEED_BOX_HEIGHT, bordercolor);
     // Calculate the position of the red line.  This is 1/3 of the way
     // along the box.
     redline_x = MOUSE_SPEED_BOX_WIDTH / 3;
     // Undo acceleration and get back the original mouse speed
     if (speed < mouse_threshold)
     {
         original_speed = speed;
     }
     else
     {
         original_speed = speed - mouse_threshold;
         original_speed = (int) (original_speed / mouse_acceleration);
         original_speed += mouse_threshold;
     }
     // Calculate line length
     linelen = (original_speed * redline_x) / mouse_threshold;
     // Draw horizontal "thermometer"
     if (linelen > MOUSE_SPEED_BOX_WIDTH - 1)
     {
         linelen = MOUSE_SPEED_BOX_WIDTH - 1;
     }
     V_DrawHorizLine(box_x + 1, box_y + 4, MOUSE_SPEED_BOX_WIDTH - 2, black);
     if (linelen < redline_x)
     {
         V_DrawHorizLine(box_x + 1, box_y + MOUSE_SPEED_BOX_HEIGHT / 2,
                       linelen, white);
     }
     else
     {
         V_DrawHorizLine(box_x + 1, box_y + MOUSE_SPEED_BOX_HEIGHT / 2,
                         redline_x, white);
         V_DrawHorizLine(box_x + redline_x, box_y + MOUSE_SPEED_BOX_HEIGHT / 2,
                         linelen - redline_x, yellow);
     }
     // Draw red line
     V_DrawVertLine(box_x + redline_x, box_y + 1,
                  MOUSE_SPEED_BOX_HEIGHT - 2, red);
 }
References fabs, I_GetPaletteIndex(), linelen, mouse_acceleration, MOUSE_SPEED_BOX_HEIGHT, MOUSE_SPEED_BOX_WIDTH, mouse_threshold, SCREENWIDTH, usemouse, V_DrawBox(), V_DrawFilledBox(), V_DrawHorizLine(), and V_DrawVertLine().
Referenced by D_Display().
V_DrawPatch()
void V_DrawPatch (int x, int y, patch_t * patch)
Definition at line 139 of file v_video.c.
 {
     int count;
     int col;
     column_t *column;
     byte *desttop;
     byte *dest;
     byte *source;
     int w;
     y -= SHORT(patch->topoffset);
     x -= SHORT(patch->leftoffset);
     // haleyjd 08/28/10: Strife needs silent error checking here.
     if(patchclip_callback)
     {
         if(!patchclip_callback(patch, x, y))
             return;
     }
 #ifdef RANGECHECK
     if (x < 0
      || x + SHORT(patch->width) > SCREENWIDTH
      || y < 0
      || y + SHORT(patch->height) > SCREENHEIGHT)
     {
         I_Error("Bad V_DrawPatch x=%i y=%i patch.width=%i patch.height=%i topoffset=%i leftoffset=%i", x, y, patch->width, patch->height, patch->topoffset, patch->leftoffset);
     }
 #endif
     V_MarkRect(x, y, SHORT(patch->width), SHORT(patch->height));
     col = 0;
     desttop = dest_screen + y * SCREENWIDTH + x;
     w = SHORT(patch->width);
     for ( ; col<w ; x++, col++, desttop++)
     {
         column = (column_t *)((byte *)patch + LONG(patch->columnofs[col]));
         // step through the posts in a column
         while (column->topdelta != 0xff)
         {
             source = (byte *)column + 3;
             dest = desttop + column->topdelta*SCREENWIDTH;
             count = column->length;
             while (count--)
             {
                 *dest = *source++;
                 dest += SCREENWIDTH;
             }
             column = (column_t *)((byte *)column + column->length + 4);
         }
     }
 }
References count, dest_screen, I_Error(), LONG, patchclip_callback, SCREENHEIGHT, SCREENWIDTH, SHORT, source, V_MarkRect(), w, x, and y.
Referenced by AM_drawMarks(), D_PageDrawer(), F_ArtScreenDrawer(), F_BunnyScroll(), F_CastDrawer(), F_CastPrint(), F_TextWrite(), R_FillBackScreen(), ST_refreshBackground(), STlib_drawNum(), STlib_updateBinIcon(), STlib_updateMultIcon(), STlib_updatePercent(), V_DrawPatchDirect(), WI_drawAnimatedBack(), WI_drawDeathmatchStats(), WI_drawEL(), WI_drawLF(), WI_drawNetgameStats(), WI_drawNum(), WI_drawOnLnode(), WI_drawPercent(), WI_drawStats(), WI_drawTime(), and WI_slamBackground().
V_DrawPatchDirect()
void V_DrawPatchDirect (int x, int y, patch_t * patch)
Definition at line 268 of file v_video.c.
 {
     V_DrawPatch(x, y, patch);
 }
References V_DrawPatch(), x, and y.
Referenced by D_Display(), HUlib_drawTextLine(), M_DrawEmptyCell(), M_DrawEpisode(), M_Drawer(), M_DrawLoad(), M_DrawMainMenu(), M_DrawNewGame(), M_DrawOptions(), M_DrawReadThis1(), M_DrawReadThis2(), M_DrawSave(), M_DrawSaveLoadBorder(), M_DrawSelCell(), M_DrawSound(), M_DrawThermo(), and M_WriteText().
V_DrawPatchFlipped()
void V_DrawPatchFlipped (int x, int y, patch_t * patch)
Definition at line 203 of file v_video.c.
 {
     int count;
     int col;
     column_t *column;
     byte *desttop;
     byte *dest;
     byte *source;
     int w;
     y -= SHORT(patch->topoffset);
     x -= SHORT(patch->leftoffset);
     // haleyjd 08/28/10: Strife needs silent error checking here.
     if(patchclip_callback)
     {
         if(!patchclip_callback(patch, x, y))
             return;
     }
 #ifdef RANGECHECK
     if (x < 0
      || x + SHORT(patch->width) > SCREENWIDTH
      || y < 0
      || y + SHORT(patch->height) > SCREENHEIGHT)
     {
         I_Error("Bad V_DrawPatchFlipped");
     }
 #endif
     V_MarkRect (x, y, SHORT(patch->width), SHORT(patch->height));
     col = 0;
     desttop = dest_screen + y * SCREENWIDTH + x;
     w = SHORT(patch->width);
     for ( ; col<w ; x++, col++, desttop++)
     {
         column = (column_t *)((byte *)patch + LONG(patch->columnofs[w-1-col]));
         // step through the posts in a column
         while (column->topdelta != 0xff )
         {
             source = (byte *)column + 3;
             dest = desttop + column->topdelta*SCREENWIDTH;
             count = column->length;
             while (count--)
             {
                 *dest = *source++;
                 dest += SCREENWIDTH;
             }
             column = (column_t *)((byte *)column + column->length + 4);
         }
     }
 }
References count, dest_screen, I_Error(), LONG, patchclip_callback, SCREENHEIGHT, SCREENWIDTH, SHORT, source, V_MarkRect(), w, x, and y.
Referenced by F_CastDrawer().
V_DrawRawScreen()
void V_DrawRawScreen (byte * raw)
Definition at line 589 of file v_video.c.
 {
     memcpy(dest_screen, raw, SCREENWIDTH * SCREENHEIGHT);
 }
References dest_screen, memcpy, raw, SCREENHEIGHT, and SCREENWIDTH.
V_DrawShadowedPatch()
void V_DrawShadowedPatch (int x, int y, patch_t * patch)
Definition at line 428 of file v_video.c.
 {
     int count, col;
     column_t *column;
     byte *desttop, *dest, *source;
     byte *desttop2, *dest2;
     int w;
     y -= SHORT(patch->topoffset);
     x -= SHORT(patch->leftoffset);
     if (x < 0
      || x + SHORT(patch->width) > SCREENWIDTH
      || y < 0
      || y + SHORT(patch->height) > SCREENHEIGHT)
     {
         I_Error("Bad V_DrawShadowedPatch");
     }
     col = 0;
     desttop = dest_screen + y * SCREENWIDTH + x;
     desttop2 = dest_screen + (y + 2) * SCREENWIDTH + x + 2;
     w = SHORT(patch->width);
     for (; col < w; x++, col++, desttop++, desttop2++)
     {
         column = (column_t *) ((byte *) patch + LONG(patch->columnofs[col]));
         // step through the posts in a column
         while (column->topdelta != 0xff)
         {
             source = (byte *) column + 3;
             dest = desttop + column->topdelta * SCREENWIDTH;
             dest2 = desttop2 + column->topdelta * SCREENWIDTH;
             count = column->length;
             while (count--)
             {
                 *dest2 = tinttable[((*dest2) << 8)];
                 dest2 += SCREENWIDTH;
                 *dest = *source++;
                 dest += SCREENWIDTH;
             }
             column = (column_t *) ((byte *) column + column->length + 4);
         }
     }
 }
References count, dest_screen, I_Error(), LONG, SCREENHEIGHT, SCREENWIDTH, SHORT, source, tinttable, w, x, and y.
V_DrawTLPatch()
void V_DrawTLPatch (int x, int y, patch_t * patch)
Definition at line 279 of file v_video.c.
 {
     int count, col;
     column_t *column;
     byte *desttop, *dest, *source;
     int w;
     y -= SHORT(patch->topoffset);
     x -= SHORT(patch->leftoffset);
     if (x < 0
      || x + SHORT(patch->width) > SCREENWIDTH
      || y < 0
      || y + SHORT(patch->height) > SCREENHEIGHT)
     {
         I_Error("Bad V_DrawTLPatch");
     }
     col = 0;
     desttop = dest_screen + y * SCREENWIDTH + x;
     w = SHORT(patch->width);
     for (; col < w; x++, col++, desttop++)
     {
         column = (column_t *) ((byte *) patch + LONG(patch->columnofs[col]));
         // step through the posts in a column
         while (column->topdelta != 0xff)
         {
             source = (byte *) column + 3;
             dest = desttop + column->topdelta * SCREENWIDTH;
             count = column->length;
             while (count--)
             {
                 *dest = tinttable[((*dest) << 8) + *source++];
                 dest += SCREENWIDTH;
             }
             column = (column_t *) ((byte *) column + column->length + 4);
         }
     }
 }
References count, dest_screen, I_Error(), LONG, SCREENHEIGHT, SCREENWIDTH, SHORT, source, tinttable, w, x, and y.
V_DrawVertLine()
void V_DrawVertLine (int x, int y, int h, int c)
Definition at line 562 of file v_video.c.
 {
     uint8_t *buf;
     int y1;
     buf = I_VideoBuffer + SCREENWIDTH * y + x;
     for (y1 = 0; y1 < h; ++y1)
     {
         *buf = c;
         buf += SCREENWIDTH;
     }
 }
References buf, c, h, I_VideoBuffer, SCREENWIDTH, x, y, and y1().
Referenced by V_DrawBox(), and V_DrawMouseSpeedBox().
V_DrawXlaPatch()
void V_DrawXlaPatch (int x, int y, patch_t * patch)
Definition at line 329 of file v_video.c.
 {
     int count, col;
     column_t *column;
     byte *desttop, *dest, *source;
     int w;
     y -= SHORT(patch->topoffset);
     x -= SHORT(patch->leftoffset);
     if(patchclip_callback)
     {
         if(!patchclip_callback(patch, x, y))
             return;
     }
     col = 0;
     desttop = dest_screen + y * SCREENWIDTH + x;
     w = SHORT(patch->width);
     for(; col < w; x++, col++, desttop++)
     {
         column = (column_t *) ((byte *) patch + LONG(patch->columnofs[col]));
         // step through the posts in a column
         while(column->topdelta != 0xff)
         {
             source = (byte *) column + 3;
             dest = desttop + column->topdelta * SCREENWIDTH;
             count = column->length;
             while(count--)
             {
                 *dest = xlatab[*dest + ((*source) << 8)];
                 source++;
                 dest += SCREENWIDTH;
             }
             column = (column_t *) ((byte *) column + column->length + 4);
         }
     }
 }
References count, dest_screen, LONG, patchclip_callback, SCREENWIDTH, SHORT, source, w, x, xlatab, and y.
V_Init()
void V_Init (void)
Definition at line 597 of file v_video.c.
 {
     // no-op!
     // There used to be separate screens that could be drawn to; these are
     // now handled in the upper layers.
 }
Referenced by D_DoomMain().
V_LoadTintTable()
void V_LoadTintTable (void)
Definition at line 482 of file v_video.c.
 {
     tinttable = W_CacheLumpName("TINTTAB", PU_STATIC);
 }
References PU_STATIC, tinttable, and W_CacheLumpName().
V_LoadXlaTable()
void V_LoadXlaTable (void)
Definition at line 493 of file v_video.c.
 {
     xlatab = W_CacheLumpName("XLATAB", PU_STATIC);
 }
References PU_STATIC, W_CacheLumpName(), and xlatab.
V_MarkRect()
void V_MarkRect (int x, int y, int width, int height)
Definition at line 69 of file v_video.c.
 {
     // If we are temporarily using an alternate screen, do not
     // affect the update box.
     if (dest_screen == I_VideoBuffer)
     {
         M_AddToBox (dirtybox, x, y);
         M_AddToBox (dirtybox, x + width-1, y + height-1);
     }
 }
References dest_screen, dirtybox, height(), I_VideoBuffer, M_AddToBox(), width, x, and y.
Referenced by AM_Drawer(), F_BunnyScroll(), F_TextWrite(), R_DrawViewBorder(), V_CopyRect(), V_DrawBlock(), V_DrawPatch(), V_DrawPatchFlipped(), and wipe_ScreenWipe().
V_RestoreBuffer()
void V_RestoreBuffer (void)
Definition at line 613 of file v_video.c.
 {
     dest_screen = I_VideoBuffer;
 }
References dest_screen, and I_VideoBuffer.
Referenced by D_DoomLoop(), R_FillBackScreen(), and ST_refreshBackground().
V_ScreenShot()
void V_ScreenShot (char * format)
Definition at line 791 of file v_video.c.
 {
     int i;
     char lbmname[16]; // haleyjd 20110213: BUG FIX - 12 is too small!
     char *ext;
     // find a file name to save it to
 #ifdef HAVE_LIBPNG
     extern int png_screenshots;
     if (png_screenshots)
     {
         ext = "png";
     }
     else
 #endif
     {
         ext = "pcx";
     }
     for (i=0; i<=99; i++)
     {
         M_snprintf(lbmname, sizeof(lbmname), format, i, ext);
         if (!M_FileExists(lbmname))
         {
             break;      // file doesn't exist
         }
     }
     if (i == 100)
     {
         I_Error ("V_ScreenShot: Couldn't create a PCX");
     }
 #ifdef HAVE_LIBPNG
     if (png_screenshots)
     {
     WritePNGfile(lbmname, I_VideoBuffer,
                  SCREENWIDTH, SCREENHEIGHT,
                  W_CacheLumpName (DEH_String("PLAYPAL"), PU_CACHE));
     }
     else
 #endif
     {
     // save the pcx file
     WritePCXfile(lbmname, I_VideoBuffer,
                  SCREENWIDTH, SCREENHEIGHT,
                  W_CacheLumpName (DEH_String("PLAYPAL"), PU_CACHE));
     }
 }
References DEH_String, format(), i, I_Error(), I_VideoBuffer, M_FileExists(), M_snprintf(), PU_CACHE, SCREENHEIGHT, SCREENWIDTH, W_CacheLumpName(), and WritePCXfile().
Referenced by G_Ticker().
V_SetPatchClipCallback()
void V_SetPatchClipCallback (vpatchclipfunc_t func)
Definition at line 129 of file v_video.c.
 {
     patchclip_callback = func;
 }
References patchclip_callback.
V_UseBuffer()
void V_UseBuffer (byte * buffer)
Definition at line 606 of file v_video.c.
 {
     dest_screen = buffer;
 }
References buffer, and dest_screen.
Referenced by R_FillBackScreen(), and ST_refreshBackground().
Variable Documentation
dirtybox
int dirtybox[4] extern
Definition at line 60 of file v_video.c.
Referenced by V_MarkRect().
tinttable
byte* tinttable extern
Definition at line 51 of file v_video.c.
Referenced by V_DrawAltTLPatch(), V_DrawShadowedPatch(), V_DrawTLPatch(), and V_LoadTintTable().