Fennix: Userspace/musl/src/locale/strtod_l.c File Reference
strtod_l.c File Reference
#include <stdlib.h>
#include <locale.h>
Macros
#define _GNU_SOURCE
Functions
float strtof_l (const char *restrict s, char **restrict p, locale_t l)
double strtod_l (const char *restrict s, char **restrict p, locale_t l)
long double strtold_l (const char *restrict s, char **restrict p, locale_t l)
weak_alias (strtof_l, __strtof_l)
weak_alias (strtod_l, __strtod_l)
weak_alias (strtold_l, __strtold_l)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file strtod_l.c.
Function Documentation
strtod_l()
double strtod_l (const char *restrict s, char **restrict p, locale_t l)
Definition at line 10 of file strtod_l.c.
 {
     return strtod(s, p);
 }
References p, s, and strtod().
strtof_l()
float strtof_l (const char *restrict s, char **restrict p, locale_t l)
Definition at line 5 of file strtod_l.c.
 {
     return strtof(s, p);
 }
References p, s, and strtof().
strtold_l()
long double strtold_l (const char *restrict s, char **restrict p, locale_t l)
Definition at line 15 of file strtod_l.c.
 {
     return strtold(s, p);
 }
References p, s, and strtold().
weak_alias() [1/3]
weak_alias (strtod_l , __strtod_l)
weak_alias() [2/3]
weak_alias (strtof_l , __strtof_l)
weak_alias() [3/3]
weak_alias (strtold_l , __strtold_l)