Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/st_stuff.h File Reference
st_stuff.h File Reference
#include "doomtype.h"
#include "d_event.h"
#include "m_cheat.h"
Macros
#define ST_HEIGHT 32
#define ST_WIDTH SCREENWIDTH
#define ST_Y (SCREENHEIGHT - ST_HEIGHT)
Enumerations
enum st_stateenum_t { AutomapState , FirstPersonState }
enum st_chatstateenum_t { StartChatState , WaitDestState , GetChatState }
Functions
boolean ST_Responder (event_t *ev)
void ST_Ticker (void)
void ST_Drawer (boolean fullscreen, boolean refresh)
void ST_Start (void)
void ST_Init (void)
Variables
byte * st_backing_screen
cheatseq_t cheat_mus
cheatseq_t cheat_god
cheatseq_t cheat_ammo
cheatseq_t cheat_ammonokey
cheatseq_t cheat_noclip
cheatseq_t cheat_commercial_noclip
cheatseq_t cheat_powerup [7]
cheatseq_t cheat_choppers
cheatseq_t cheat_clev
cheatseq_t cheat_mypos
Macro Definition Documentation
ST_HEIGHT
#define ST_HEIGHT 32
Definition at line 30 of file st_stuff.h.
ST_WIDTH
#define ST_WIDTH SCREENWIDTH
Definition at line 31 of file st_stuff.h.
ST_Y
#define ST_Y (SCREENHEIGHT - ST_HEIGHT)
Definition at line 32 of file st_stuff.h.
Enumeration Type Documentation
st_chatstateenum_t
enum st_chatstateenum_t
Enumerator
StartChatState
WaitDestState
GetChatState
Definition at line 66 of file st_stuff.h.
 {
     StartChatState,
     WaitDestState,
     GetChatState
 } st_chatstateenum_t;
st_stateenum_t
enum st_stateenum_t
Enumerator
AutomapState
FirstPersonState
Definition at line 57 of file st_stuff.h.
 {
     AutomapState,
     FirstPersonState
 } st_stateenum_t;
Function Documentation
ST_Drawer()
void ST_Drawer (boolean fullscreen, boolean refresh)
Definition at line 1055 of file st_stuff.c.
 {
     st_statusbaron = (!fullscreen) || automapactive;
     st_firsttime = st_firsttime || refresh;
     // Do red-/gold-shifts from damage/items
     ST_doPaletteStuff();
     // If just after ST_Start(), refresh all
     if (st_firsttime) ST_doRefresh();
     // Otherwise, update as little as possible
     else ST_diffDraw();
 }
References automapactive, fullscreen, ST_diffDraw(), ST_doPaletteStuff(), ST_doRefresh(), st_firsttime, and st_statusbaron.
Referenced by D_Display().
ST_Init()
void ST_Init (void)
Definition at line 1411 of file st_stuff.c.
 {
     ST_loadData();
     st_backing_screen = (byte *) Z_Malloc(ST_WIDTH * ST_HEIGHT, PU_STATIC, 0);
 }
References PU_STATIC, st_backing_screen, ST_HEIGHT, ST_loadData(), ST_WIDTH, and Z_Malloc().
Referenced by D_DoomMain().
ST_Responder()
boolean ST_Responder (event_t * ev)
Definition at line 439 of file st_stuff.c.
 {
   int       i;
   // Filter automap on/off.
   if (ev->type == ev_keyup
       && ((ev->data1 & 0xffff0000) == AM_MSGHEADER))
   {
     switch(ev->data1)
     {
       case AM_MSGENTERED:
     st_gamestate = AutomapState;
     st_firsttime = true;
     break;
       case AM_MSGEXITED:
     //  fprintf(stderr, "AM exited\n");
     st_gamestate = FirstPersonState;
     break;
     }
   }
   // if a user keypress...
   else if (ev->type == ev_keydown)
   {
     if (!netgame && gameskill != sk_nightmare)
     {
       // 'dqd' cheat for toggleable god mode
       if (cht_CheckCheat(&cheat_god, ev->data2))
       {
     plyr->cheats ^= CF_GODMODE;
     if (plyr->cheats & CF_GODMODE)
     {
       if (plyr->mo)
         plyr->mo->health = 100;
       plyr->health = deh_god_mode_health;
       plyr->message = DEH_String(STSTR_DQDON);
     }
     else
       plyr->message = DEH_String(STSTR_DQDOFF);
       }
       // 'fa' cheat for killer fucking arsenal
       else if (cht_CheckCheat(&cheat_ammonokey, ev->data2))
       {
     plyr->armorpoints = deh_idfa_armor;
     plyr->armortype = deh_idfa_armor_class;
     for (i=0;i<NUMWEAPONS;i++)
       plyr->weaponowned[i] = true;
     for (i=0;i<NUMAMMO;i++)
       plyr->ammo[i] = plyr->maxammo[i];
     plyr->message = DEH_String(STSTR_FAADDED);
       }
       // 'kfa' cheat for key full ammo
       else if (cht_CheckCheat(&cheat_ammo, ev->data2))
       {
     plyr->armorpoints = deh_idkfa_armor;
     plyr->armortype = deh_idkfa_armor_class;
     for (i=0;i<NUMWEAPONS;i++)
       plyr->weaponowned[i] = true;
     for (i=0;i<NUMAMMO;i++)
       plyr->ammo[i] = plyr->maxammo[i];
     for (i=0;i<NUMCARDS;i++)
       plyr->cards[i] = true;
     plyr->message = DEH_String(STSTR_KFAADDED);
       }
       // 'mus' cheat for changing music
       else if (cht_CheckCheat(&cheat_mus, ev->data2))
       {
     char    buf[3];
     int     musnum;
     plyr->message = DEH_String(STSTR_MUS);
     cht_GetParam(&cheat_mus, buf);
         // Note: The original v1.9 had a bug that tried to play back
         // the Doom II music regardless of gamemode.  This was fixed
         // in the Ultimate Doom executable so that it would work for
         // the Doom 1 music as well.
     if (gamemode == commercial || gameversion < exe_ultimate)
     {
       musnum = mus_runnin + (buf[0]-'0')*10 + buf[1]-'0' - 1;
       if (((buf[0]-'0')*10 + buf[1]-'0') > 35)
         plyr->message = DEH_String(STSTR_NOMUS);
       else
         S_ChangeMusic(musnum, 1);
     }
     else
     {
       musnum = mus_e1m1 + (buf[0]-'1')*9 + (buf[1]-'1');
       if (((buf[0]-'1')*9 + buf[1]-'1') > 31)
         plyr->message = DEH_String(STSTR_NOMUS);
       else
         S_ChangeMusic(musnum, 1);
     }
       }
       else if ( (logical_gamemission == doom
                  && cht_CheckCheat(&cheat_noclip, ev->data2))
              || (logical_gamemission != doom
                  && cht_CheckCheat(&cheat_commercial_noclip,ev->data2)))
       {
         // Noclip cheat.
         // For Doom 1, use the idspipsopd cheat; for all others, use
         // idclip
     plyr->cheats ^= CF_NOCLIP;
     if (plyr->cheats & CF_NOCLIP)
       plyr->message = DEH_String(STSTR_NCON);
     else
       plyr->message = DEH_String(STSTR_NCOFF);
       }
       // 'behold?' power-up cheats
       for (i=0;i<6;i++)
       {
     if (cht_CheckCheat(&cheat_powerup[i], ev->data2))
     {
       if (!plyr->powers[i])
         P_GivePower( plyr, i);
       else if (i!=pw_strength)
         plyr->powers[i] = 1;
       else
         plyr->powers[i] = 0;
       plyr->message = DEH_String(STSTR_BEHOLDX);
     }
       }
       // 'behold' power-up menu
       if (cht_CheckCheat(&cheat_powerup[6], ev->data2))
       {
     plyr->message = DEH_String(STSTR_BEHOLD);
       }
       // 'choppers' invulnerability & chainsaw
       else if (cht_CheckCheat(&cheat_choppers, ev->data2))
       {
     plyr->weaponowned[wp_chainsaw] = true;
     plyr->powers[pw_invulnerability] = true;
     plyr->message = DEH_String(STSTR_CHOPPERS);
       }
       // 'mypos' for player position
       else if (cht_CheckCheat(&cheat_mypos, ev->data2))
       {
         static char buf[ST_MSGWIDTH];
         M_snprintf(buf, sizeof(buf), "ang=0x%x;x,y=(0x%x,0x%x)",
                    players[consoleplayer].mo->angle,
                    players[consoleplayer].mo->x,
                    players[consoleplayer].mo->y);
         plyr->message = buf;
       }
     }
     // 'clev' change-level cheat
     if (!netgame && cht_CheckCheat(&cheat_clev, ev->data2))
     {
       char      buf[3];
       int       epsd;
       int       map;
       cht_GetParam(&cheat_clev, buf);
       if (gamemode == commercial)
       {
     epsd = 1;
     map = (buf[0] - '0')*10 + buf[1] - '0';
       }
       else
       {
     epsd = buf[0] - '0';
     map = buf[1] - '0';
       }
       // Chex.exe always warps to episode 1.
       if (gameversion == exe_chex)
       {
         epsd = 1;
       }
       // Catch invalid maps.
       if (epsd < 1)
     return false;
       if (map < 1)
     return false;
       // Ohmygod - this is not going to work.
       if ((gamemode == retail)
       && ((epsd > 4) || (map > 9)))
     return false;
       if ((gamemode == registered)
       && ((epsd > 3) || (map > 9)))
     return false;
       if ((gamemode == shareware)
       && ((epsd > 1) || (map > 9)))
     return false;
       // The source release has this check as map > 34. However, Vanilla
       // Doom allows IDCLEV up to MAP40 even though it normally crashes.
       if ((gamemode == commercial)
     && (( epsd > 1) || (map > 40)))
     return false;
       // So be it.
       plyr->message = DEH_String(STSTR_CLEV);
       G_DeferedInitNew(gameskill, epsd, map);
     }
   }
   return false;
 }
References AM_MSGENTERED, AM_MSGEXITED, AM_MSGHEADER, player_s::ammo, player_s::armorpoints, player_s::armortype, AutomapState, buf, player_s::cards, CF_GODMODE, CF_NOCLIP, cheat_ammo, cheat_ammonokey, cheat_choppers, cheat_clev, cheat_commercial_noclip, cheat_god, cheat_mus, cheat_mypos, cheat_noclip, cheat_powerup, player_s::cheats, cht_CheckCheat(), cht_GetParam(), commercial, consoleplayer, event_t::data1, event_t::data2, deh_god_mode_health, deh_idfa_armor, deh_idfa_armor_class, deh_idkfa_armor, deh_idkfa_armor_class, DEH_String, doom, ev_keydown, ev_keyup, exe_chex, exe_ultimate, FirstPersonState, for(), G_DeferedInitNew(), gamemode, gameskill, gameversion, player_s::health, mobj_s::health, i, logical_gamemission, M_snprintf(), map, player_s::maxammo, player_s::message, player_s::mo, mus_e1m1, mus_runnin, netgame, NUMAMMO, NUMCARDS, NUMWEAPONS, P_GivePower(), players, plyr, player_s::powers, pw_invulnerability, pw_strength, registered, retail, S_ChangeMusic(), shareware, sk_nightmare, st_firsttime, st_gamestate, ST_MSGWIDTH, STSTR_BEHOLD, STSTR_BEHOLDX, STSTR_CHOPPERS, STSTR_CLEV, STSTR_DQDOFF, STSTR_DQDON, STSTR_FAADDED, STSTR_KFAADDED, STSTR_MUS, STSTR_NCOFF, STSTR_NCON, STSTR_NOMUS, event_t::type, player_s::weaponowned, wp_chainsaw, mobj_s::x, and mobj_s::y.
Referenced by AM_initVariables(), AM_Stop(), and G_Responder().
ST_Start()
void ST_Start (void)
Definition at line 1389 of file st_stuff.c.
 {
     if (!st_stopped)
     ST_Stop();
     ST_initData();
     ST_createWidgets();
     st_stopped = false;
 }
References ST_createWidgets(), ST_initData(), ST_Stop(), and st_stopped.
Referenced by P_SpawnPlayer().
ST_Ticker()
void ST_Ticker (void)
Definition at line 924 of file st_stuff.c.
 {
     st_clock++;
     st_randomnumber = M_Random();
     ST_updateWidgets();
     st_oldhealth = plyr->health;
 }
References player_s::health, M_Random(), plyr, st_clock, st_oldhealth, st_randomnumber, and ST_updateWidgets().
Referenced by G_Ticker().
Variable Documentation
cheat_ammo
cheatseq_t cheat_ammo extern
Definition at line 390 of file st_stuff.c.
Referenced by ST_Responder().
cheat_ammonokey
cheatseq_t cheat_ammonokey extern
Definition at line 391 of file st_stuff.c.
Referenced by ST_Responder().
cheat_choppers
cheatseq_t cheat_choppers extern
Definition at line 406 of file st_stuff.c.
Referenced by ST_Responder().
cheat_clev
cheatseq_t cheat_clev extern
Definition at line 407 of file st_stuff.c.
Referenced by ST_Responder().
cheat_commercial_noclip
cheatseq_t cheat_commercial_noclip extern
Definition at line 393 of file st_stuff.c.
Referenced by ST_Responder().
cheat_god
cheatseq_t cheat_god extern
Definition at line 389 of file st_stuff.c.
Referenced by ST_Responder().
cheat_mus
cheatseq_t cheat_mus extern
Definition at line 388 of file st_stuff.c.
Referenced by ST_Responder().
cheat_mypos
cheatseq_t cheat_mypos extern
Definition at line 408 of file st_stuff.c.
Referenced by ST_Responder().
cheat_noclip
cheatseq_t cheat_noclip extern
Definition at line 392 of file st_stuff.c.
Referenced by ST_Responder().
cheat_powerup
cheatseq_t cheat_powerup[7] extern
Definition at line 395 of file st_stuff.c.
Referenced by ST_Responder().
st_backing_screen
byte* st_backing_screen extern
Definition at line 263 of file st_stuff.c.
Referenced by ST_Init(), ST_refreshBackground(), STlib_drawNum(), STlib_updateBinIcon(), and STlib_updateMultIcon().