Fennix: Userspace/apps/base/busybox/libbb/safe_write.c File Reference
safe_write.c File Reference
#include "libbb.h"
Functions
ssize_t FAST_FUNC safe_write (int fd, const void *buf, size_t count)
Function Documentation
safe_write()
ssize_t FAST_FUNC safe_write (int fd, const void * buf, size_t count)
Definition at line 11 of file safe_write.c.
 {
     ssize_t n;
     for (;;) {
         n = write(fd, buf, count);
         if (n >= 0 || errno != EINTR)
             break;
         /* Some callers set errno=0, are upset when they see EINTR.
          * Returning EINTR is wrong since we retry write(),
          * the "error" was transient.
          */
         errno = 0;
         /* repeat the write() */
     }
     return n;
 }
References buf, count, EINTR, errno, fd, n, and write().
Referenced by chat_main(), d6_send_kernel_packet_from_client_data_ifindex(), evalcommand(), full_write(), get_response_or_say_and_die(), lpd_main(), make_new_session(), receive(), safe_write_double_iac(), safe_write_to_pty_decode_iac(), and udhcp_send_kernel_packet().