Fennix: Kernel/KernelShell/Commands/cat.cpp File Reference
cat.cpp File Reference
#include "../cmds.hpp"
#include <filesystem.hpp>
#include "../../kernel.h"
Functions
void cmd_cat (const char *args)
Function Documentation
cmd_cat()
void cmd_cat (const char * args)
Definition at line 26 of file cat.cpp.
 {
     if (args[0] == '\0')
         return;
     Node *thisNode = vfs->GetNodeFromPath(args, thisProcess->CurrentWorkingDirectory);
     if (thisNode == nullptr)
     {
         printf("cat: %s: No such file or directory\n", args);
         return;
     }
     if (thisNode->Flags != NodeFlags::FILE &&
         thisNode->Flags != NodeFlags::CHARDEVICE)
     {
         printf("cat: %s: Not a file\n", args);
         return;
     }
     std::string path = vfs->GetPathFromNode(thisNode);
     int fd = fopen(path.c_str(), "r");
     struct stat st;
     fstat(fd, &st);
     char *buffer = new char[st.st_size + 1];
     fread(fd, buffer, st.st_size);
     printf("%s\n", buffer);
     delete[] buffer;
     fclose(fd);
 }
References buffer, std::string::c_str(), VirtualFileSystem::CHARDEVICE, fclose(), fd, VirtualFileSystem::Node::Flags, fopen(), fread(), fstat(), VirtualFileSystem::Virtual::GetNodeFromPath(), VirtualFileSystem::Virtual::GetPathFromNode(), printf, thisProcess, and vfs.