Fennix: Userspace/musl/src/network/sendto.c File Reference
sendto.c File Reference
#include <sys/socket.h>
#include "syscall.h"
Functions
ssize_t sendto (int fd, const void *buf, size_t len, int flags, const struct sockaddr *addr, socklen_t alen)
Function Documentation
sendto()
ssize_t sendto (int fd, const void * buf, size_t len, int flags, const struct sockaddr * addr, socklen_t alen)
Definition at line 4 of file sendto.c.
 {
     return socketcall_cp(sendto, fd, buf, len, flags, addr, alen);
 }
References addr, buf, fd, len, sendto(), and socketcall_cp.
Referenced by __res_msend_rc(), send(), and sendto().