Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/ctanf.c File Reference
ctanf.c File Reference
#include <complex.h>
#include <math.h>
#include "cephes_subrf.h"
Functions
float complex ctanf (float complex z)
Function Documentation
ctanf()
float complex ctanf (float complex z)
Definition at line 40 of file ctanf.c.
 {
     float complex w;
     float d;
     d = cosf(2.0f * crealf(z)) + coshf(2.0f * cimagf(z));
     if (fabsf(d) < 0.25f)
         d = __mlibc_ctansf(z);
     if (d == 0.0f) {
         /* mtherr ("ctan", OVERFLOW); */
         w = HUGE_VALF + HUGE_VALF * I;
         return w;
     }
     w = sinf(2.0f * crealf(z)) / d + (sinhf(2.0f * cimagf(z)) / d) * I;
     return w;
 }
References __mlibc_ctansf(), cimagf(), complex, cosf(), coshf(), crealf(), fabsf(), HUGE_VALF, I, sinf(), and sinhf().