Fennix Userspace: Userspace/apps/base/busybox/shell/hush.c File Reference
hush.c File Reference
#include <malloc.h>
#include <glob.h>
#include <sys/times.h>
#include <sys/utsname.h>
#include "busybox.h"
#include "unicode.h"
#include "shell_common.h"
#include "math.h"
#include "match.h"
#include "NUM_APPLETS.h"
Data Structures
struct nommu_save_t
struct o_string
struct HFILE
struct in_str
struct redir_struct
struct command
struct pipe
struct parse_context
struct variable
struct globals
struct built_in_command
struct save_arg_t
struct squirrel
Macros
#define CLEAR_RANDOM_T(rnd) ((void)0)
#define O_CLOEXEC 0
#define F_DUPFD_CLOEXEC F_DUPFD
#define NUM_SCRIPTS 0
#define BASH_PATTERN_SUBST ENABLE_HUSH_BASH_COMPAT
#define BASH_SUBSTR ENABLE_HUSH_BASH_COMPAT
#define BASH_SOURCE ENABLE_HUSH_BASH_COMPAT
#define BASH_DOLLAR_SQUOTE ENABLE_HUSH_BASH_COMPAT
#define BASH_HOSTNAME_VAR ENABLE_HUSH_BASH_COMPAT
#define BASH_EPOCH_VARS ENABLE_HUSH_BASH_COMPAT
#define BASH_TEST2 (ENABLE_HUSH_BASH_COMPAT && ENABLE_HUSH_TEST)
#define BASH_READ_D ENABLE_HUSH_BASH_COMPAT
#define LEAK_HUNTING 0
#define BUILD_AS_NOMMU 0
#define HUSH_DEBUG 1
#define ENABLE_HUSH_FAST 0
#define ENABLE_HUSH_DOLLAR_OPS 1
#define ENABLE_FEATURE_EDITING 0
#define ENABLE_FEATURE_EDITING_FANCY_PROMPT 0
#define ENABLE_FEATURE_EDITING_SAVE_ON_EXIT 0
#define HAS_KEYWORDS 0
#define IF_HAS_KEYWORDS(...)
#define IF_HAS_NO_KEYWORDS(...) __VA_ARGS__
#define debug_printf(...) do {} while (0)
#define debug_printf_parse(...) do {} while (0)
#define debug_printf_heredoc(...) do {} while (0)
#define debug_print_tree(a, b) do {} while (0)
#define debug_printf_exec(...) do {} while (0)
#define debug_printf_env(...) do {} while (0)
#define debug_printf_jobs(...) do {} while (0)
#define debug_printf_expand(...) do {} while (0)
#define debug_printf_varexp(...) do {} while (0)
#define debug_printf_glob(...) do {} while (0)
#define debug_printf_redir(...) do {} while (0)
#define debug_printf_list(...) do {} while (0)
#define debug_printf_subst(...) do {} while (0)
#define debug_printf_prompt(...) do {} while (0)
#define debug_printf_clean(...) do {} while (0)
#define ERR_PTR ((void*)(long)1)
#define JOB_STATUS_FORMAT "[%u] %-22s %.40s\n"
#define _SPECIAL_VARS_STR "_*@$!?#-"
#define SPECIAL_VARS_STR ("_*@$!?#-" + 1)
#define NUMERIC_SPECVARS_STR ("_*@$!?#-" + 3)
#define VAR_ENCODED_SUBST_OPS "%#:-=+?"
#define VAR_SUBST_OPS "%#:-=+?"
#define MINUS_PLUS_EQUAL_QUESTION ("%#:-=+?" + 3)
#define SPECIAL_VAR_SYMBOL_STR "\3"
#define SPECIAL_VAR_SYMBOL 3
#define SPECIAL_VAR_QUOTED_SVS 1
#define NULL_O_STRING { NULL }
#define CMD_NORMAL 0
#define CMD_SUBSHELL 1
#define IS_NULL_CMD(cmd) (!(cmd)->group && !(cmd)->argv && !(cmd)->redirects)
#define IS_NULL_PIPE(pi) ((pi)->num_cmds == 0 IF_HAS_KEYWORDS(&& (pi)->res_word == RES_NONE))
#define setenv(...) setenv_is_leaky_dont_use()
#define G_interactive_fd 0
#define G_saved_tty_pgrp 0
#define G_x_mode 0
#define G_flag_return_in_progress 0
#define G_global_args_malloced 0
#define G_fatal_sig_mask 0
#define G_traps ((char**)NULL)
#define G (*ptr_to_globals)
#define INIT_G()
#define BLTIN(cmd, func, help) { cmd, func }
#define indent() ((void)0)
#define debug_enter() ((void)0)
#define debug_leave() ((void)0)
#define DEBUG_JOBS 0
#define DEBUG_EXPAND 0
#define DEBUG_GLOB 0
#define DEBUG_CLEAN 0
#define debug_print_strings(prefix, vv) ((void)0)
#define msg_and_die_if_script(lineno, ...) msg_and_die_if_script(__VA_ARGS__)
#define syntax_error(lineno, msg) syntax_error(msg)
#define syntax_error_at(lineno, msg) syntax_error_at(msg)
#define syntax_error_unterm_ch(lineno, ch) syntax_error_unterm_ch(ch)
#define syntax_error_unterm_str(lineno, s) syntax_error_unterm_str(s)
#define syntax_error_unexpected_ch(lineno, ch) syntax_error_unexpected_ch(ch)
#define disable_restore_tty_pgrp_on_exit() ((void)0)
#define enable_restore_tty_pgrp_on_exit() ((void)0)
#define handle_changed_special_names(...) ((void)0)
#define SETFLAG_EXPORT (1 << 0)
#define SETFLAG_UNEXPORT (1 << 1)
#define SETFLAG_MAKE_RO (1 << 2)
#define SETFLAG_VARLVL_SHIFT 3
#define B_CHUNK (32 * sizeof(char*))
#define MAYBE_BRACES ""
#define debug_print_list(prefix, o, n) ((void)0)
#define DOUBLE_CLOSE_CHAR_FLAG 0x80
#define parse_dollar_squote(as_string, dest, input) 0
#define expand_string_to_string(str, EXP_flags, do_unbackslash) expand_string_to_string(str)
#define encode_then_expand_vararg(str, handle_squotes, do_unbackslash) encode_then_expand_vararg(str, handle_squotes)
#define NOMMU_HACK_FMT ("-$%x:%x:%x:%x:%x:%llx" IF_HUSH_LOOPS(":%x"))
#define exec_builtin(to_free, x, argv) exec_builtin(to_free, argv)
#define dump_cmd_in_x_mode(argv) ((void)0)
#define if_command_vV_print_and_exit(a, b, c) ((void)0)
#define redirect_and_varexp_helper(command, sqp, argv_expanded) redirect_and_varexp_helper(command, sqp)
Typedefs
typedef struct nommu_save_t nommu_save_t
typedef struct o_string o_string
typedef struct HFILE HFILE
typedef struct in_str in_str
typedef enum redir_type redir_type
typedef enum pipe_style pipe_style
typedef struct save_arg_t save_arg_t
Enumerations
enum { RES_NONE = 0 , RES_XXXX , RES_SNTX }
enum { EXP_FLAG_SINGLEWORD = 0x80 , EXP_FLAG_GLOB = 0x2 , EXP_FLAG_ESC_GLOB_CHARS = 0x1 }
enum redir_type {
REDIRECT_INPUT = 0 , REDIRECT_OVERWRITE = 1 , REDIRECT_APPEND = 2 , REDIRECT_IO = 3 ,
REDIRECT_HEREDOC = 4 , REDIRECT_HEREDOC2 = 5 , REDIRFD_CLOSE = -3 , REDIRFD_SYNTAX_ERR = -2 ,
REDIRFD_TO_FILE = -1 , HEREDOC_SKIPTABS = 1 , HEREDOC_QUOTED = 2
}
enum pipe_style { PIPE_SEQ = 0 , PIPE_AND = 1 , PIPE_OR = 2 , PIPE_BG = 3 }
enum { MAYBE_ASSIGNMENT = 0 , DEFINITELY_ASSIGNMENT = 1 , NOT_ASSIGNMENT = 2 , WORD_IS_KEYWORD = 3 }
enum { BC_BREAK = 1 , BC_CONTINUE = 2 }
enum { OPT_O_PIPEFAIL , OPT_O_NOEXEC , OPT_O_ERREXIT , NUM_OPT_O }
enum { SPECIAL_INTERACTIVE_SIGS , SPECIAL_JOBSTOP_SIGS = 0 }
Functions
static int builtin_cd (char **argv) FAST_FUNC
static int builtin_eval (char **argv) FAST_FUNC
static int builtin_exec (char **argv) FAST_FUNC
static int builtin_exit (char **argv) FAST_FUNC
static int builtin_pwd (char **argv) FAST_FUNC
static int builtin_shift (char **argv) FAST_FUNC
static int builtin_source (char **argv) FAST_FUNC
static int builtin_true (char **argv) FAST_FUNC
static void die_if_script (void)
static void msg_and_die_if_script (unsigned lineno, const char *fmt,...)
static void syntax_error (unsigned lineno UNUSED_PARAM, const char *msg)
static void syntax_error_at (unsigned lineno UNUSED_PARAM, const char *msg)
static void syntax_error_unterm_str (unsigned lineno UNUSED_PARAM, const char *s)
static void syntax_error_unterm_ch (unsigned lineno, char ch)
static void syntax_error_unexpected_ch (unsigned lineno UNUSED_PARAM, int ch)
static char * unbackslash (char *src)
static char ** add_strings_to_strings (char **strings, char **add, int need_to_dup)
static char ** add_string_to_strings (char **strings, char *add)
static void free_strings (char **strings)
static int dup_CLOEXEC (int fd, int avoid_fd)
static int xdup_CLOEXEC_and_close (int fd, int avoid_fd)
static HFILE * hfopen (const char *name)
static void hfclose (HFILE *fp)
static int refill_HFILE_and_getc (HFILE *fp)
static ALWAYS_INLINE int hfgetc (HFILE *fp)
static int move_HFILEs_on_redirect (int fd, int avoid_fd)
static int fd_in_HFILEs (int fd)
static void save_and_replace_G_args (save_arg_t *sv, char **argv)
static void restore_G_args (save_arg_t *sv, char **argv)
static void record_pending_signo (int sig)
static sighandler_t install_sighandler (int sig, sighandler_t handler)
static void hush_exit (int exitcode) NORETURN
static void restore_ttypgrp_and__exit (void)
static sighandler_t pick_sighandler (unsigned sig)
static int check_and_run_traps (void)
static const char * get_cwd (int force)
static struct variable ** get_ptr_to_local_var (const char *name, unsigned len)
static const char *FAST_FUNC get_local_var_value (const char *name)
static int set_local_var (char *str, unsigned flags)
static int set_local_var0 (char *str)
static void FAST_FUNC set_local_var_from_halves (const char *name, const char *val)
static void set_pwd_var (unsigned flag)
static void add_vars (struct variable *var)
static void set_vars_and_save_old (char **strings)
static void reinit_unicode_for_hush (void)
static ALWAYS_INLINE int fgetc_interactive (struct in_str *i)
static int i_getch (struct in_str *i)
static int i_peek (struct in_str *i)
static int i_peek2 (struct in_str *i)
static int i_getch_and_eat_bkslash_nl (struct in_str *input)
static int i_peek_and_eat_bkslash_nl (struct in_str *input)
static void setup_file_in_str (struct in_str *i, HFILE *fp)
static void setup_string_in_str (struct in_str *i, const char *s)
static void o_reset_to_empty_unquoted (o_string *o)
static void o_free_and_set_NULL (o_string *o)
static ALWAYS_INLINE void o_free (o_string *o)
static void o_grow_by (o_string *o, int len)
static void o_addchr (o_string *o, int ch)
static void o_addblock (o_string *o, const char *str, int len)
static void o_addstr (o_string *o, const char *str)
static void o_addstr_with_NUL (o_string *o, const char *str)
static void nommu_addchr (o_string *o, int ch)
static void o_addqchr (o_string *o, int ch)
static void o_addQchr (o_string *o, int ch)
static void o_addqblock (o_string *o, const char *str, int len)
static void o_addQblock (o_string *o, const char *str, int len)
static void o_addQstr (o_string *o, const char *str)
static int o_save_ptr_helper (o_string *o, int n)
static int o_get_last_ptr (o_string *o, int n)
static int glob_needed (const char *s)
static int perform_glob (o_string *o, int n)
static int o_save_ptr (o_string *o, int n)
static char ** o_finalize_list (o_string *o, int n)
static void free_pipe_list (struct pipe *pi)
static struct pipe * free_pipe (struct pipe *pi)
static struct pipe * new_pipe (void)
static int done_command (struct parse_context *ctx)
static void done_pipe (struct parse_context *ctx, pipe_style type)
static void initialize_context (struct parse_context *ctx)
static int done_word (struct parse_context *ctx)
static int parse_redir_right_fd (o_string *as_string, struct in_str *input)
static int parse_redirect (struct parse_context *ctx, int fd, redir_type style, struct in_str *input)
static int redirect_opt_num (o_string *o)
static char * fetch_till_str (o_string *as_string, struct in_str *input, const char *word, int heredoc_flags)
static int fetch_heredocs (o_string *as_string, struct pipe *pi, int heredoc_cnt, struct in_str *input)
static int run_list (struct pipe *pi)
static struct pipe * parse_stream (char **pstring, int *heredoc_cnt_ptr, struct in_str *input, int end_trigger)
static int parse_group (struct parse_context *ctx, struct in_str *input, int ch)
static int add_till_single_quote (o_string *dest, struct in_str *input)
static int add_till_single_quote_dquoted (o_string *dest, struct in_str *input)
static int add_till_backquote (o_string *dest, struct in_str *input, int in_dquote)
static int add_till_double_quote (o_string *dest, struct in_str *input)
static int add_till_closing_bracket (o_string *dest, struct in_str *input, unsigned end_ch)
static int parse_dollar (o_string *as_string, o_string *dest, struct in_str *input, unsigned char quote_mask)
static int encode_string (o_string *as_string, o_string *dest, struct in_str *input, int dquote_end)
static char * expand_string_to_string (const char *str, int EXP_flags, int do_unbackslash)
static int expand_vars_to_list (o_string *output, int n, char *arg)
static void o_addblock_duplicate_backslash (o_string *o, const char *str, int len)
static int expand_on_ifs (o_string *output, int n, const char *str)
static char * encode_then_expand_string (const char *str)
static const char * first_special_char_in_vararg (const char *cp)
static char * encode_then_expand_vararg (const char *str, int handle_squotes, int do_unbackslash)
static NOINLINE int encode_then_append_var_plusminus (o_string *output, int n, char *str, int dquoted)
static int append_str_maybe_ifs_split (o_string *output, int n, int first_ch, const char *val)
static NOINLINE int expand_one_var (o_string *output, int n, int first_ch, char *arg, char **pp)
static char ** expand_variables (char **argv, unsigned expflags)
static char ** expand_strvec_to_strvec (char **argv)
static char ** expand_assignments (char **argv, int count)
static void switch_off_special_sigs (unsigned mask)
static void re_execute_shell (char ***to_free, const char *s, char *g_argv0, char **g_argv, char **builtin_argv) NORETURN
static int run_and_free_list (struct pipe *pi)
static void parse_and_run_stream (struct in_str *inp, int end_trigger)
static void parse_and_run_string (const char *s)
static void parse_and_run_file (HFILE *fp)
static void setup_heredoc (struct redir_struct *redir)
static struct squirrel * append_squirrel (struct squirrel *sq, int i, int orig, int moved)
static struct squirrel * add_squirrel (struct squirrel *sq, int fd, int avoid_fd)
static struct squirrel * add_squirrel_closed (struct squirrel *sq, int fd)
static int save_fd_on_redirect (int fd, int avoid_fd, struct squirrel **sqp)
static void restore_redirects (struct squirrel *sq)
static int internally_opened_fd (int fd, struct squirrel *sq)
static int setup_redirects (struct command *prog, struct squirrel **sqp)
static char * find_in_path (const char *arg)
static const struct built_in_command * find_builtin_helper (const char *name, const struct built_in_command *x, const struct built_in_command *end)
static const struct built_in_command * find_builtin1 (const char *name)
static const struct built_in_command * find_builtin (const char *name)
static void remove_nested_vars (void)
static void enter_var_nest_level (void)
static void leave_var_nest_level (void)
static void exec_builtin (char ***to_free, const struct built_in_command *x, char **argv) NORETURN
static void execvp_or_die (char **argv) NORETURN
static void pseudo_exec_argv (nommu_save_t *nommu_save, char **argv, int assignment_cnt, char **argv_expanded) NORETURN
static void pseudo_exec (nommu_save_t *nommu_save, struct command *command, char **argv_expanded) NORETURN
static int job_exited_or_stopped (struct pipe *pi)
static int process_wait_result (struct pipe *fg_pipe, pid_t childpid, int status)
static int checkjobs (struct pipe *fg_pipe, pid_t waitfor_pid)
static int redirect_and_varexp_helper (struct command *command, struct squirrel **sqp, char **argv_expanded)
static NOINLINE int run_pipe (struct pipe *pi)
static void install_sighandlers (unsigned mask)
static void install_special_sighandlers (void)
static int set_mode (int state, char mode, const char *o_opt)
int hush_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
static int FAST_FUNC builtin_true (char **argv UNUSED_PARAM)
static char ** skip_dash_dash (char **argv)
static int FAST_FUNC builtin_pwd (char **argv UNUSED_PARAM)
Variables
static const char hush_version_str[] ALIGN1 = "HUSH_VERSION="BB_VER
struct {
int32_t mode
signed char default_fd
char descrip [3]
} ALIGN4 []
static const struct built_in_command bltins1[] ALIGN_PTR
Data Structure Documentation
nommu_save_t
struct nommu_save_t
Definition at line 507 of file hush.c.
Data Fields
char ** argv
char ** argv_from_re_execing
struct variable * old_vars
o_string
struct o_string
Definition at line 545 of file hush.c.
Data Fields
char * data
smallint ended_in_ifs
smallint has_empty_slot
smallint has_quoted_part
int length
int maxlen
int o_expflags
HFILE
struct HFILE
Definition at line 582 of file hush.c.
Data Fields
char buf[1024]
char * cur
char * end
int fd
struct HFILE * next_hfile
in_str
struct in_str
Definition at line 590 of file hush.c.
Data Fields
HFILE * file
int last_char
const char * p
int peek_buf[2]
redir_struct
struct redir_struct
Definition at line 613 of file hush.c.
Data Fields
struct redir_struct * next
int rd_dup
int rd_fd
char * rd_filename
smallint rd_type
command
struct command
Definition at line 197 of file command.h.
Data Fields
char ** argv
unsigned assignment_cnt
smalluint cmd_exitcode
smallint cmd_type
int flags
struct pipe * group
char * group_as_string
int line
pid_t pid
REDIRECT * redirects
struct redir_struct * redirects
enum command_type type
union command value
pipe
struct pipe
Definition at line 701 of file hush.c.
Data Fields
int alive_cmds
struct command * cmds
smallint followup
struct pipe * next
int num_cmds
int stopped_cmds
parse_context
struct parse_context
Definition at line 727 of file hush.c.
Data Fields
o_string as_string
struct command * command
smallint is_assignment
struct pipe * list_head
struct redir_struct * pending_redirect
struct pipe * pipe
o_string word
variable
struct variable
Definition at line 82 of file variables.h.
Data Fields
sh_var_assign_func_t * assign_func
int attributes
int context
sh_var_value_func_t * dynamic_value
char * exportstr
smallint flg_export
smallint flg_read_only
int max_len
char * name
struct variable * next
char * value
uint16_t var_nest_level
char * varstr
save_arg_t
struct save_arg_t
Definition at line 1756 of file hush.c.
Data Fields
char * sv_argv0
int sv_g_argc
char ** sv_g_argv
squirrel
struct squirrel
Definition at line 5676 of file ash.c.
Data Fields
int moved_to
int orig_fd
Macro Definition Documentation
_SPECIAL_VARS_STR
#define _SPECIAL_VARS_STR "_*@$!?#-"
Definition at line 479 of file hush.c.
B_CHUNK
#define B_CHUNK (32 * sizeof(char*))
Definition at line 2956 of file hush.c.
BASH_DOLLAR_SQUOTE
#define BASH_DOLLAR_SQUOTE ENABLE_HUSH_BASH_COMPAT
Definition at line 387 of file hush.c.
BASH_EPOCH_VARS
#define BASH_EPOCH_VARS ENABLE_HUSH_BASH_COMPAT
Definition at line 389 of file hush.c.
BASH_HOSTNAME_VAR
#define BASH_HOSTNAME_VAR ENABLE_HUSH_BASH_COMPAT
Definition at line 388 of file hush.c.
BASH_PATTERN_SUBST
#define BASH_PATTERN_SUBST ENABLE_HUSH_BASH_COMPAT
Definition at line 384 of file hush.c.
BASH_READ_D
#define BASH_READ_D ENABLE_HUSH_BASH_COMPAT
Definition at line 391 of file hush.c.
BASH_SOURCE
#define BASH_SOURCE ENABLE_HUSH_BASH_COMPAT
Definition at line 386 of file hush.c.
BASH_SUBSTR
#define BASH_SUBSTR ENABLE_HUSH_BASH_COMPAT
Definition at line 385 of file hush.c.
BASH_TEST2
#define BASH_TEST2 (ENABLE_HUSH_BASH_COMPAT && ENABLE_HUSH_TEST)
Definition at line 390 of file hush.c.
BLTIN
#define BLTIN (cmd, func, help) { cmd, func }
Definition at line 1141 of file hush.c.
BUILD_AS_NOMMU
#define BUILD_AS_NOMMU 0
Definition at line 396 of file hush.c.
CLEAR_RANDOM_T
#define CLEAR_RANDOM_T (rnd) ((void)0)
Definition at line 367 of file hush.c.
CMD_NORMAL
#define CMD_NORMAL 0
Definition at line 651 of file hush.c.
CMD_SUBSHELL
#define CMD_SUBSHELL 1
Definition at line 652 of file hush.c.
DEBUG_CLEAN
#define DEBUG_CLEAN 0
Definition at line 1328 of file hush.c.
debug_enter
#define debug_enter () ((void)0)
Definition at line 1259 of file hush.c.
DEBUG_EXPAND
#define DEBUG_EXPAND 0
Definition at line 1294 of file hush.c.
DEBUG_GLOB
#define DEBUG_GLOB 0
Definition at line 1305 of file hush.c.
DEBUG_JOBS
#define DEBUG_JOBS 0
Definition at line 1287 of file hush.c.
debug_leave
#define debug_leave () ((void)0)
Definition at line 1260 of file hush.c.
debug_print_list
#define debug_print_list (prefix, o, n) ((void)0)
Definition at line 3201 of file hush.c.
debug_print_strings
#define debug_print_strings (prefix, vv) ((void)0)
Definition at line 1340 of file hush.c.
debug_print_tree
#define debug_print_tree (a, b) do {} while (0)
Definition at line 462 of file hush.c.
debug_printf
#define debug_printf (...) do {} while (0)
Definition at line 458 of file hush.c.
debug_printf_clean
#define debug_printf_clean (...) do {} while (0)
Definition at line 473 of file hush.c.
debug_printf_env
#define debug_printf_env (...) do {} while (0)
Definition at line 464 of file hush.c.
debug_printf_exec
#define debug_printf_exec (...) do {} while (0)
Definition at line 463 of file hush.c.
debug_printf_expand
#define debug_printf_expand (...) do {} while (0)
Definition at line 466 of file hush.c.
debug_printf_glob
#define debug_printf_glob (...) do {} while (0)
Definition at line 468 of file hush.c.
debug_printf_heredoc
#define debug_printf_heredoc (...) do {} while (0)
Definition at line 461 of file hush.c.
debug_printf_jobs
#define debug_printf_jobs (...) do {} while (0)
Definition at line 465 of file hush.c.
debug_printf_list
#define debug_printf_list (...) do {} while (0)
Definition at line 470 of file hush.c.
debug_printf_parse
#define debug_printf_parse (...) do {} while (0)
Definition at line 460 of file hush.c.
debug_printf_prompt
#define debug_printf_prompt (...) do {} while (0)
Definition at line 472 of file hush.c.
debug_printf_redir
#define debug_printf_redir (...) do {} while (0)
Definition at line 469 of file hush.c.
debug_printf_subst
#define debug_printf_subst (...) do {} while (0)
Definition at line 471 of file hush.c.
debug_printf_varexp
#define debug_printf_varexp (...) do {} while (0)
Definition at line 467 of file hush.c.
disable_restore_tty_pgrp_on_exit
#define disable_restore_tty_pgrp_on_exit () ((void)0)
Definition at line 2042 of file hush.c.
DOUBLE_CLOSE_CHAR_FLAG
#define DOUBLE_CLOSE_CHAR_FLAG 0x80
Definition at line 4876 of file hush.c.
dump_cmd_in_x_mode
#define dump_cmd_in_x_mode (argv) ((void)0)
Definition at line 8558 of file hush.c.
ENABLE_FEATURE_EDITING
#define ENABLE_FEATURE_EDITING 0
Definition at line 438 of file hush.c.
ENABLE_FEATURE_EDITING_FANCY_PROMPT
#define ENABLE_FEATURE_EDITING_FANCY_PROMPT 0
Definition at line 440 of file hush.c.
ENABLE_FEATURE_EDITING_SAVE_ON_EXIT
#define ENABLE_FEATURE_EDITING_SAVE_ON_EXIT 0
Definition at line 442 of file hush.c.
ENABLE_HUSH_DOLLAR_OPS
#define ENABLE_HUSH_DOLLAR_OPS 1
Definition at line 412 of file hush.c.
ENABLE_HUSH_FAST
#define ENABLE_HUSH_FAST 0
Definition at line 408 of file hush.c.
enable_restore_tty_pgrp_on_exit
#define enable_restore_tty_pgrp_on_exit () ((void)0)
Definition at line 2043 of file hush.c.
encode_then_expand_vararg
#define encode_then_expand_vararg (str, handle_squotes, do_unbackslash) encode_then_expand_vararg(str, handle_squotes)
Definition at line 6250 of file hush.c.
ERR_PTR
#define ERR_PTR ((void*)(long)1)
Definition at line 475 of file hush.c.
exec_builtin
#define exec_builtin (to_free, x, argv) exec_builtin(to_free, argv)
Definition at line 8449 of file hush.c.
expand_string_to_string
#define expand_string_to_string (str, EXP_flags, do_unbackslash) expand_string_to_string(str)
Definition at line 6054 of file hush.c.
F_DUPFD_CLOEXEC
#define F_DUPFD_CLOEXEC F_DUPFD
Definition at line 373 of file hush.c.
G
#define G (*ptr_to_globals)
Definition at line 1038 of file hush.c.
G_fatal_sig_mask
#define G_fatal_sig_mask 0
Definition at line 1001 of file hush.c.
G_flag_return_in_progress
#define G_flag_return_in_progress 0
Definition at line 934 of file hush.c.
G_global_args_malloced
#define G_global_args_malloced 0
Definition at line 946 of file hush.c.
G_interactive_fd
#define G_interactive_fd 0
Definition at line 871 of file hush.c.
G_saved_tty_pgrp
#define G_saved_tty_pgrp 0
Definition at line 889 of file hush.c.
G_traps
#define G_traps ((char**)NULL)
Definition at line 1011 of file hush.c.
G_x_mode
#define G_x_mode 0
Definition at line 914 of file hush.c.
handle_changed_special_names
#define handle_changed_special_names (...) ((void)0)
Definition at line 2312 of file hush.c.
HAS_KEYWORDS
#define HAS_KEYWORDS 0
Definition at line 451 of file hush.c.
HUSH_DEBUG
#define HUSH_DEBUG 1
Definition at line 401 of file hush.c.
if_command_vV_print_and_exit
#define if_command_vV_print_and_exit (a, b, c) ((void)0)
Definition at line 8584 of file hush.c.
IF_HAS_KEYWORDS
#define IF_HAS_KEYWORDS (...)
Definition at line 452 of file hush.c.
IF_HAS_NO_KEYWORDS
#define IF_HAS_NO_KEYWORDS (...) __VA_ARGS__
Definition at line 453 of file hush.c.
indent
#define indent () ((void)0)
Definition at line 1258 of file hush.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    /* memset(&G.sa, 0, sizeof(G.sa)); */  \
    sigfillset(&G.sa.sa_mask); \
    G.sa.sa_flags = SA_RESTART; \
} while (0)
Definition at line 1042 of file hush.c.
IS_NULL_CMD
#define IS_NULL_CMD (cmd) (!(cmd)->group && !(cmd)->argv && !(cmd)->redirects)
Definition at line 698 of file hush.c.
IS_NULL_PIPE
#define IS_NULL_PIPE (pi) ((pi)->num_cmds == 0 IF_HAS_KEYWORDS(&& (pi)->res_word == RES_NONE))
Definition at line 723 of file hush.c.
JOB_STATUS_FORMAT
#define JOB_STATUS_FORMAT "[%u] %-22s %.40s\n"
Definition at line 477 of file hush.c.
LEAK_HUNTING
#define LEAK_HUNTING 0
Definition at line 395 of file hush.c.
MAYBE_BRACES
#define MAYBE_BRACES ""
Definition at line 3081 of file hush.c.
MINUS_PLUS_EQUAL_QUESTION
#define MINUS_PLUS_EQUAL_QUESTION ("%#:-=+?" + 3)
Definition at line 491 of file hush.c.
msg_and_die_if_script
#define msg_and_die_if_script (lineno, ...) msg_and_die_if_script(__VA_ARGS__)
Definition at line 1383 of file hush.c.
NOMMU_HACK_FMT
#define NOMMU_HACK_FMT ("-$%x:%x:%x:%x:%x:%llx" IF_HUSH_LOOPS(":%x"))
NULL_O_STRING
#define NULL_O_STRING { NULL }
Definition at line 564 of file hush.c.
NUM_SCRIPTS
#define NUM_SCRIPTS 0
Definition at line 379 of file hush.c.
NUMERIC_SPECVARS_STR
#define NUMERIC_SPECVARS_STR ("_*@$!?#-" + 3)
Definition at line 481 of file hush.c.
O_CLOEXEC
#define O_CLOEXEC 0
Definition at line 370 of file hush.c.
parse_dollar_squote
#define parse_dollar_squote (as_string, dest, input) 0
Definition at line 5053 of file hush.c.
redirect_and_varexp_helper
#define redirect_and_varexp_helper (command, sqp, argv_expanded) redirect_and_varexp_helper(command, sqp)
Definition at line 9212 of file hush.c.
setenv
#define setenv (...) setenv_is_leaky_dont_use()
Definition at line 774 of file hush.c.
SETFLAG_EXPORT
#define SETFLAG_EXPORT (1 << 0)
Definition at line 2318 of file hush.c.
SETFLAG_MAKE_RO
#define SETFLAG_MAKE_RO (1 << 2)
Definition at line 2320 of file hush.c.
SETFLAG_UNEXPORT
#define SETFLAG_UNEXPORT (1 << 1)
Definition at line 2319 of file hush.c.
SETFLAG_VARLVL_SHIFT
#define SETFLAG_VARLVL_SHIFT 3
Definition at line 2321 of file hush.c.
SPECIAL_VAR_QUOTED_SVS
#define SPECIAL_VAR_QUOTED_SVS 1
Definition at line 497 of file hush.c.
SPECIAL_VAR_SYMBOL
#define SPECIAL_VAR_SYMBOL 3
Definition at line 495 of file hush.c.
SPECIAL_VAR_SYMBOL_STR
#define SPECIAL_VAR_SYMBOL_STR "\3"
Definition at line 494 of file hush.c.
SPECIAL_VARS_STR
#define SPECIAL_VARS_STR ("_*@$!?#-" + 1)
Definition at line 480 of file hush.c.
syntax_error
#define syntax_error (lineno, msg) syntax_error(msg)
Definition at line 1384 of file hush.c.
syntax_error_at
#define syntax_error_at (lineno, msg) syntax_error_at(msg)
Definition at line 1385 of file hush.c.
syntax_error_unexpected_ch
#define syntax_error_unexpected_ch (lineno, ch) syntax_error_unexpected_ch(ch)
Definition at line 1388 of file hush.c.
syntax_error_unterm_ch
#define syntax_error_unterm_ch (lineno, ch) syntax_error_unterm_ch(ch)
Definition at line 1386 of file hush.c.
syntax_error_unterm_str
#define syntax_error_unterm_str (lineno, s) syntax_error_unterm_str(s)
Definition at line 1387 of file hush.c.
VAR_ENCODED_SUBST_OPS
#define VAR_ENCODED_SUBST_OPS "%#:-=+?"
Definition at line 489 of file hush.c.
VAR_SUBST_OPS
#define VAR_SUBST_OPS "%#:-=+?"
Definition at line 490 of file hush.c.
Typedef Documentation
HFILE
typedef struct HFILE HFILE
in_str
typedef struct in_str in_str
nommu_save_t
typedef struct nommu_save_t nommu_save_t
o_string
typedef struct o_string o_string
pipe_style
typedef enum pipe_style pipe_style
redir_type
typedef enum redir_type redir_type
save_arg_t
typedef struct save_arg_t save_arg_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RES_NONE
RES_XXXX
RES_SNTX
Definition at line 514 of file hush.c.
      {
     RES_NONE  = 0,
 #if ENABLE_HUSH_IF
     RES_IF    ,
     RES_THEN  ,
     RES_ELIF  ,
     RES_ELSE  ,
     RES_FI    ,
 #endif
 #if ENABLE_HUSH_LOOPS
     RES_FOR   ,
     RES_WHILE ,
     RES_UNTIL ,
     RES_DO    ,
     RES_DONE  ,
 #endif
 #if ENABLE_HUSH_LOOPS || ENABLE_HUSH_CASE
     RES_IN    ,
 #endif
 #if ENABLE_HUSH_CASE
     RES_CASE  ,
     /* three pseudo-keywords support contrived "case" syntax: */
     RES_CASE_IN,   /* "case ... IN", turns into RES_MATCH when IN is observed */
     RES_MATCH ,    /* "word)" */
     RES_CASE_BODY, /* "this command is inside CASE" */
     RES_ESAC  ,
 #endif
     RES_XXXX  ,
     RES_SNTX
 };
anonymous enum
anonymous enum
Enumerator
EXP_FLAG_SINGLEWORD
EXP_FLAG_GLOB
EXP_FLAG_ESC_GLOB_CHARS
Definition at line 556 of file hush.c.
      {
     EXP_FLAG_SINGLEWORD     = 0x80, /* must be 0x80 */
     EXP_FLAG_GLOB           = 0x2,
     /* Protect newly added chars against globbing
      * by prepending \ to *, ?, [, \ */
     EXP_FLAG_ESC_GLOB_CHARS = 0x1,
 };
anonymous enum
anonymous enum
Enumerator
MAYBE_ASSIGNMENT
DEFINITELY_ASSIGNMENT
NOT_ASSIGNMENT
WORD_IS_KEYWORD
Definition at line 761 of file hush.c.
      {
     MAYBE_ASSIGNMENT      = 0,
     DEFINITELY_ASSIGNMENT = 1,
     NOT_ASSIGNMENT        = 2,
     /* Not an assignment, but next word may be: "if v=xyz cmd;" */
     WORD_IS_KEYWORD       = 3,
 };
anonymous enum
anonymous enum
Enumerator
BC_BREAK
BC_CONTINUE
Definition at line 784 of file hush.c.
      {
     BC_BREAK = 1,
     BC_CONTINUE = 2,
 };
anonymous enum
anonymous enum
Enumerator
OPT_O_PIPEFAIL
OPT_O_NOEXEC
OPT_O_ERREXIT
NUM_OPT_O
Definition at line 840 of file hush.c.
      {
     OPT_O_PIPEFAIL,
     OPT_O_NOEXEC,
     OPT_O_ERREXIT,
 #if ENABLE_HUSH_MODE_X
     OPT_O_XTRACE,
 #endif
     NUM_OPT_O
 };
anonymous enum
anonymous enum
Enumerator
SPECIAL_INTERACTIVE_SIGS
SPECIAL_JOBSTOP_SIGS
Definition at line 1930 of file hush.c.
      {
     SPECIAL_INTERACTIVE_SIGS = 0
         | (1 << SIGTERM)
         | (1 << SIGINT)
         | (1 << SIGHUP)
         ,
     SPECIAL_JOBSTOP_SIGS = 0
 #if ENABLE_HUSH_JOB
         | (1 << SIGTTIN)
         | (1 << SIGTTOU)
         | (1 << SIGTSTP)
 #endif
         ,
 };
pipe_style
enum pipe_style
Enumerator
PIPE_SEQ
PIPE_AND
PIPE_OR
PIPE_BG
Definition at line 716 of file hush.c.
{
     PIPE_SEQ = 0,
     PIPE_AND = 1,
     PIPE_OR  = 2,
     PIPE_BG  = 3,
 } pipe_style;
redir_type
enum redir_type
Enumerator
REDIRECT_INPUT
REDIRECT_OVERWRITE
REDIRECT_APPEND
REDIRECT_IO
REDIRECT_HEREDOC
REDIRECT_HEREDOC2
REDIRFD_CLOSE
REDIRFD_SYNTAX_ERR
REDIRFD_TO_FILE
HEREDOC_SKIPTABS
HEREDOC_QUOTED
Definition at line 626 of file hush.c.
{
     REDIRECT_INPUT     = 0,
     REDIRECT_OVERWRITE = 1,
     REDIRECT_APPEND    = 2,
     REDIRECT_IO        = 3,
     REDIRECT_HEREDOC   = 4,
     REDIRECT_HEREDOC2  = 5, /* REDIRECT_HEREDOC after heredoc is loaded */
     REDIRFD_CLOSE      = -3,
     REDIRFD_SYNTAX_ERR = -2,
     REDIRFD_TO_FILE    = -1,
     /* otherwise, rd_fd is redirected to rd_dup */
     HEREDOC_SKIPTABS = 1,
     HEREDOC_QUOTED   = 2,
 } redir_type;
Function Documentation
add_squirrel()
static struct squirrel* add_squirrel (struct squirrel * sq, int fd, int avoid_fd) static
Definition at line 7846 of file hush.c.
 {
     int moved_to;
     int i;
     i = 0;
     if (sq) for (; sq[i].orig_fd >= 0; i++) {
         /* If we collide with an already moved fd... */
         if (fd == sq[i].moved_to) {
             sq[i].moved_to = dup_CLOEXEC(sq[i].moved_to, avoid_fd);
             debug_printf_redir("redirect_fd %d: already busy, moving to %d\n", fd, sq[i].moved_to);
             if (sq[i].moved_to < 0) /* what? */
                 xfunc_die();
             return sq;
         }
         if (fd == sq[i].orig_fd) {
             /* Example: echo Hello >/dev/null 1>&2 */
             debug_printf_redir("redirect_fd %d: already moved\n", fd);
             return sq;
         }
     }
     /* If this fd is open, we move and remember it; if it's closed, moved_to = -1 */
     moved_to = dup_CLOEXEC(fd, avoid_fd);
     debug_printf_redir("redirect_fd %d: previous fd is moved to %d (-1 if it was closed)\n", fd, moved_to);
     if (moved_to < 0 && errno != EBADF)
         xfunc_die();
     return append_squirrel(sq, i, fd, moved_to);
 }
References append_squirrel(), debug_printf_redir, dup_CLOEXEC(), EBADF, errno, fd, i, squirrel::moved_to, squirrel::orig_fd, sq(), and xfunc_die().
Referenced by save_fd_on_redirect().
add_squirrel_closed()
static struct squirrel* add_squirrel_closed (struct squirrel * sq, int fd) static
Definition at line 7876 of file hush.c.
 {
     int i;
     i = 0;
     if (sq) for (; sq[i].orig_fd >= 0; i++) {
         /* If we collide with an already moved fd... */
         if (fd == sq[i].orig_fd) {
             /* Examples:
              * "echo 3>FILE 3>&- 3>FILE"
              * "echo 3>&- 3>FILE"
              * No need for last redirect to insert
              * another "need to close 3" indicator.
              */
             debug_printf_redir("redirect_fd %d: already moved or closed\n", fd);
             return sq;
         }
     }
     debug_printf_redir("redirect_fd %d: previous fd was closed\n", fd);
     return append_squirrel(sq, i, fd, -1);
 }
References append_squirrel(), debug_printf_redir, fd, i, squirrel::orig_fd, and sq().
Referenced by setup_redirects().
add_string_to_strings()
static char** add_string_to_strings (char ** strings, char * add) static
Definition at line 1536 of file hush.c.
 {
     char *v[2];
     v[0] = add;
     v[1] = NULL;
     return add_strings_to_strings(strings, v, /*dup:*/ 0);
 }
References add(), add_strings_to_strings(), NULL, and strings.
Referenced by done_word(), and expand_assignments().
add_strings_to_strings()
static char** add_strings_to_strings (char ** strings, char ** add, int need_to_dup) static
Definition at line 1496 of file hush.c.
 {
     int i;
     unsigned count1;
     unsigned count2;
     char **v;
     v = strings;
     count1 = 0;
     if (v) {
         while (*v) {
             count1++;
             v++;
         }
     }
     count2 = 0;
     v = add;
     while (*v) {
         count2++;
         v++;
     }
     v = xrealloc(strings, (count1 + count2 + 1) * sizeof(char*));
     v[count1 + count2] = NULL;
     i = count2;
     while (--i >= 0)
         v[count1 + i] = (need_to_dup ? xstrdup(add[i]) : add[i]);
     return v;
 }
References add(), i, NULL, strings, xrealloc, and xstrdup().
Referenced by add_string_to_strings().
add_till_backquote()
static int add_till_backquote (o_string * dest, struct in_str * input, int in_dquote) static
Definition at line 4835 of file hush.c.
 {
     while (1) {
         int ch = i_getch(input);
         if (ch == '`')
             return 1;
         if (ch == '\\') {
             /* \x. Copy both unless it is \`, \$, \\ and maybe \" */
             ch = i_getch(input);
             if (ch != '`'
              && ch != '$'
              && ch != '\\'
              && (!in_dquote || ch != '"')
             ) {
                 o_addchr(dest, '\\');
             }
         }
         if (ch == EOF) {
             syntax_error_unterm_ch('`');
             return 0;
         }
         o_addchr(dest, ch);
     }
 }
References EOF, i_getch(), input, o_addchr(), and syntax_error_unterm_ch.
Referenced by add_till_closing_bracket(), add_till_double_quote(), encode_string(), encode_then_append_var_plusminus(), encode_then_expand_vararg(), and parse_stream().
add_till_closing_bracket()
static int add_till_closing_bracket (o_string * dest, struct in_str * input, unsigned end_ch) static
Definition at line 4877 of file hush.c.
 {
     int ch;
     char dbl = end_ch & DOUBLE_CLOSE_CHAR_FLAG;
 # if BASH_SUBSTR || BASH_PATTERN_SUBST
     char end_char2 = end_ch >> 8;
 # endif
     end_ch &= (DOUBLE_CLOSE_CHAR_FLAG - 1);
 # if ENABLE_HUSH_INTERACTIVE
     G.promptmode = 1; /* PS2 */
 # endif
     debug_printf_prompt("%s promptmode=%d\n", __func__, G.promptmode);
     while (1) {
         ch = i_getch(input);
         if (ch == EOF) {
             syntax_error_unterm_ch(end_ch);
             return 0;
         }
         if (ch == end_ch
 # if BASH_SUBSTR || BASH_PATTERN_SUBST
          || ch == end_char2
 # endif
         ) {
             if (!dbl)
                 break;
             /* we look for closing )) of $((EXPR)) */
             if (i_peek_and_eat_bkslash_nl(input) == end_ch) {
                 i_getch(input); /* eat second ')' */
                 break;
             }
         }
         o_addchr(dest, ch);
         //bb_error_msg("%s:o_addchr('%c')", __func__, ch);
         if (ch == '(' || ch == '{') {
             ch = (ch == '(' ? ')' : '}');
             if (!add_till_closing_bracket(dest, input, ch))
                 return 0;
             o_addchr(dest, ch);
             continue;
         }
         if (ch == '\'') {
             if (!add_till_single_quote(dest, input))
                 return 0;
             o_addchr(dest, ch);
             continue;
         }
         if (ch == '"') {
             if (!add_till_double_quote(dest, input))
                 return 0;
             o_addchr(dest, ch);
             continue;
         }
         if (ch == '`') {
             if (!add_till_backquote(dest, input, /*in_dquote:*/ 0))
                 return 0;
             o_addchr(dest, ch);
             continue;
         }
         if (ch == '\\') {
             /* \x. Copy verbatim. Important for  \‍(, \‍) */
             ch = i_getch(input);
             if (ch == EOF) {
                 syntax_error_unterm_ch(end_ch);
                 return 0;
             }
 # if 0
             if (ch == '\n') {
                 /* "backslash+newline", ignore both */
                 o_delchr(dest); /* undo insertion of '\' */
                 continue;
             }
 # endif
             o_addchr(dest, ch);
             //bb_error_msg("%s:o_addchr('%c') after '\\'", __func__, ch);
             continue;
         }
     }
     debug_printf_parse("%s return '%s' ch:'%c'\n", __func__, dest->data, ch);
     return ch;
 }
References add_till_backquote(), add_till_double_quote(), add_till_single_quote(), BASH_PATTERN_SUBST, BASH_SUBSTR, o_string::data, debug_printf_parse, debug_printf_prompt, DOUBLE_CLOSE_CHAR_FLAG, EOF, G, i_getch(), i_peek_and_eat_bkslash_nl(), input, o_addchr(), and syntax_error_unterm_ch.
Referenced by parse_dollar().
add_till_double_quote()
static int add_till_double_quote (o_string * dest, struct in_str * input) static
Definition at line 4797 of file hush.c.
 {
     while (1) {
         int ch = i_getch(input);
         if (ch == EOF) {
             syntax_error_unterm_ch('"');
             return 0;
         }
         if (ch == '"')
             return 1;
         if (ch == '\\') {  /* \x. Copy both chars. */
             o_addchr(dest, ch);
             ch = i_getch(input);
         }
         o_addchr(dest, ch);
         if (ch == '`') {
             if (!add_till_backquote(dest, input, /*in_dquote:*/ 1))
                 return 0;
             o_addchr(dest, ch);
             continue;
         }
         //if (ch == '$') ...
     }
 }
References add_till_backquote(), EOF, i_getch(), input, o_addchr(), and syntax_error_unterm_ch.
Referenced by add_till_closing_bracket().
add_till_single_quote()
static int add_till_single_quote (o_string * dest, struct in_str * input) static
Definition at line 4769 of file hush.c.
 {
     while (1) {
         int ch = i_getch(input);
         if (ch == EOF) {
             syntax_error_unterm_ch('\'');
             return 0;
         }
         if (ch == '\'')
             return 1;
         o_addchr(dest, ch);
     }
 }
References EOF, i_getch(), input, o_addchr(), and syntax_error_unterm_ch.
Referenced by add_till_closing_bracket().
add_till_single_quote_dquoted()
static int add_till_single_quote_dquoted (o_string * dest, struct in_str * input) static
Definition at line 4782 of file hush.c.
 {
     while (1) {
         int ch = i_getch(input);
         if (ch == EOF) {
             syntax_error_unterm_ch('\'');
             return 0;
         }
         if (ch == '\'')
             return 1;
         o_addqchr(dest, ch);
     }
 }
References EOF, i_getch(), input, o_addqchr(), and syntax_error_unterm_ch.
Referenced by encode_then_append_var_plusminus(), and encode_then_expand_vararg().
add_vars()
static void add_vars (struct variable * var) static
Definition at line 2524 of file hush.c.
 {
     struct variable *next;
     while (var) {
         next = var->next;
         var->next = G.top_var;
         G.top_var = var;
         if (var->flg_export) {
             debug_printf_env("%s: restoring exported '%s'/%u\n", __func__, var->varstr, var->var_nest_level);
             putenv(var->varstr);
         } else {
             debug_printf_env("%s: restoring variable '%s'/%u\n", __func__, var->varstr, var->var_nest_level);
         }
         var = next;
     }
 }
References debug_printf_env, G, var::next, next, and putenv().
Referenced by run_pipe().
append_squirrel()
static struct squirrel* append_squirrel (struct squirrel * sq, int i, int orig, int moved) static
Definition at line 7837 of file hush.c.
 {
     sq = xrealloc(sq, (i + 2) * sizeof(sq[0]));
     sq[i].orig_fd = orig;
     sq[i].moved_to = moved;
     sq[i+1].orig_fd = -1; /* end marker */
     return sq;
 }
References i, sq(), and xrealloc.
Referenced by add_squirrel(), and add_squirrel_closed().
append_str_maybe_ifs_split()
static int append_str_maybe_ifs_split (o_string * output, int n, int first_ch, const char * val) static
Definition at line 6576 of file hush.c.
 {
     if (!(first_ch & 0x80)) { /* unquoted $VAR */
         debug_printf_expand("unquoted '%s', output->o_escape:%d\n", val,
                 !!(output->o_expflags & EXP_FLAG_ESC_GLOB_CHARS));
         if (val && val[0])
             n = expand_on_ifs(output, n, val);
     } else { /* quoted "$VAR" */
         output->has_quoted_part = 1;
         debug_printf_expand("quoted '%s', output->o_escape:%d\n", val,
                 !!(output->o_expflags & EXP_FLAG_ESC_GLOB_CHARS));
         if (val && val[0])
             o_addQstr(output, val);
     }
     return n;
 }
References debug_printf_expand, EXP_FLAG_ESC_GLOB_CHARS, expand_on_ifs(), n, o_addQstr(), output, and val.
Referenced by expand_one_var(), and expand_vars_to_list().
builtin_cd()
static int FAST_FUNC builtin_cd (char ** argv) static
Definition at line 10823 of file hush.c.
 {
     const char *newdir;
     argv = skip_dash_dash(argv);
     newdir = argv[0];
     if (newdir == NULL) {
         /* bash does nothing (exitcode 0) if HOME is ""; if it's unset,
          * bash says "bash: cd: HOME not set" and does nothing
          * (exitcode 1)
          */
         const char *home = get_local_var_value("HOME");
         newdir = home ? home : "/";
     }
     if (chdir(newdir)) {
         /* Mimic bash message exactly */
         bb_perror_msg("cd: %s", newdir);
         return EXIT_FAILURE;
     }
     /* Read current dir (get_cwd(1) is inside) and set PWD.
      * Note: do not enforce exporting. If PWD was unset or unexported,
      * set it again, but do not export. bash does the same.
      */
     set_pwd_var(/*flag:*/ 0);
     return EXIT_SUCCESS;
 }
References argv, bb_perror_msg(), chdir(), EXIT_FAILURE, EXIT_SUCCESS, get_local_var_value(), NULL, set_pwd_var(), and skip_dash_dash().
builtin_eval()
static int FAST_FUNC builtin_eval (char ** argv) static
Definition at line 10856 of file hush.c.
 {
     argv = skip_dash_dash(argv);
     if (!argv[0])
         return EXIT_SUCCESS;
     IF_HUSH_MODE_X(G.x_mode_depth++;)
     //bb_error_msg("%s: ++x_mode_depth=%d", __func__, G.x_mode_depth);
     if (!argv[1]) {
         /* bash:
          * eval "echo Hi; done" ("done" is syntax error):
          * "echo Hi" will not execute too.
          */
         parse_and_run_string(argv[0]);
     } else {
         /* "The eval utility shall construct a command by
          * concatenating arguments together, separating
          * each with a <space> character."
          */
         char *str, *p;
         unsigned len = 0;
         char **pp = argv;
         do
             len += strlen(*pp) + 1;
         while (*++pp);
         str = p = xmalloc(len);
         pp = argv;
         for (;;) {
             p = stpcpy(p, *pp);
             pp++;
             if (!*pp)
                 break;
             *p++ = ' ';
         }
         parse_and_run_string(str);
         free(str);
     }
     IF_HUSH_MODE_X(G.x_mode_depth--;)
     //bb_error_msg("%s: --x_mode_depth=%d", __func__, G.x_mode_depth);
     return G.last_exitcode;
 }
References argv, EXIT_SUCCESS, free, G, p, parse_and_run_string(), skip_dash_dash(), stpcpy(), str, strlen(), and xmalloc.
Referenced by check_and_run_traps(), and hush_exit().
builtin_exec()
static int FAST_FUNC builtin_exec (char ** argv) static
Definition at line 10899 of file hush.c.
 {
     argv = skip_dash_dash(argv);
     if (argv[0] == NULL)
         return EXIT_SUCCESS; /* bash does this */
     /* Careful: we can end up here after [v]fork. Do not restore
      * tty pgrp then, only top-level shell process does that */
     if (G_saved_tty_pgrp && getpid() == G.root_pid)
         tcsetpgrp(G_interactive_fd, G_saved_tty_pgrp);
     /* Saved-redirect fds, script fds and G_interactive_fd are still
      * open here. However, they are all CLOEXEC, and execv below
      * closes them. Try interactive "exec ls -l /proc/self/fd",
      * it should show no extra open fds in the "ls" process.
      * If we'd try to run builtins/NOEXECs, this would need improving.
      */
     //close_saved_fds_and_FILE_fds();
     /* TODO: if exec fails, bash does NOT exit! We do.
      * We'll need to undo trap cleanup (it's inside execvp_or_die)
      * and tcsetpgrp, and this is inherently racy.
      */
     execvp_or_die(argv);
 }
References argv, execvp_or_die(), EXIT_SUCCESS, G, G_interactive_fd, G_saved_tty_pgrp, getpid(), NULL, skip_dash_dash(), and tcsetpgrp.
Referenced by run_pipe().
builtin_exit()
static int FAST_FUNC builtin_exit (char ** argv) static
Definition at line 10925 of file hush.c.
 {
     debug_printf_exec("%s()\n", __func__);
     /* interactive bash:
      * # trap "echo EEE" EXIT
      * # exit
      * exit
      * There are stopped jobs.
      * (if there are _stopped_ jobs, running ones don't count)
      * # exit
      * exit
      * EEE (then bash exits)
      *
      * TODO: we can use G.exiting = -1 as indicator "last cmd was exit"
      */
     /* note: EXIT trap is run by hush_exit */
     argv = skip_dash_dash(argv);
     if (argv[0] == NULL) {
 #if ENABLE_HUSH_TRAP
         if (G.pre_trap_exitcode >= 0) /* "exit" in trap uses $? from before the trap */
             hush_exit(G.pre_trap_exitcode);
 #endif
         hush_exit(G.last_exitcode);
     }
     /* mimic bash: exit 123abc == exit 255 + error msg */
     xfunc_error_retval = 255;
     /* bash: exit -2 == exit 254, no error msg */
     hush_exit(xatoi(argv[0]) & 0xff);
 }
References argv, debug_printf_exec, G, hush_exit(), NULL, skip_dash_dash(), and xfunc_error_retval.
builtin_pwd() [1/2]
static int FAST_FUNC builtin_pwd (char **argv UNUSED_PARAM) static
Definition at line 10850 of file hush.c.
 {
     puts(get_cwd(0));
     return EXIT_SUCCESS;
 }
References EXIT_SUCCESS, get_cwd(), and puts().
builtin_pwd() [2/2]
static int builtin_pwd (char ** argv) static
builtin_shift()
static int FAST_FUNC builtin_shift (char ** argv) static
Definition at line 11408 of file hush.c.
 {
     int n = 1;
     argv = skip_dash_dash(argv);
     if (argv[0]) {
         n = bb_strtou(argv[0], NULL, 10);
         if (errno || n < 0) {
             /* shared string with ash.c */
             bb_error_msg("Illegal number: %s", argv[0]);
             /*
              * ash aborts in this case.
              * bash prints error message and set $? to 1.
              * Interestingly, for "shift 99999" bash does not
              * print error message, but does set $? to 1
              * (and does no shifting at all).
              */
         }
     }
     if (n >= 0 && n < G.global_argc) {
         if (G_global_args_malloced) {
             int m = 1;
             while (m <= n)
                 free(G.global_argv[m++]);
         }
         G.global_argc -= n;
         memmove(&G.global_argv[1], &G.global_argv[n+1],
                 G.global_argc * sizeof(G.global_argv[0]));
         return EXIT_SUCCESS;
     }
     return EXIT_FAILURE;
 }
References argv, bb_error_msg(), bb_strtou(), errno, EXIT_FAILURE, EXIT_SUCCESS, free, G, G_global_args_malloced, memmove(), n, NULL, and skip_dash_dash().
builtin_source()
static int FAST_FUNC builtin_source (char ** argv) static
Definition at line 11565 of file hush.c.
 {
     char *arg_path, *filename;
     HFILE *input;
     save_arg_t sv;
     char *args_need_save;
 #if ENABLE_HUSH_FUNCTIONS
     smallint sv_flg;
 #endif
     argv = skip_dash_dash(argv);
     filename = argv[0];
     if (!filename) {
         /* bash says: "bash: .: filename argument required" */
         return 2; /* bash compat */
     }
     arg_path = NULL;
     if (!strchr(filename, '/')) {
         arg_path = find_in_path(filename);
         if (arg_path)
             filename = arg_path;
         else if (!ENABLE_HUSH_BASH_SOURCE_CURDIR) {
             errno = ENOENT;
             bb_simple_perror_msg(filename);
             return EXIT_FAILURE;
         }
     }
     input = hfopen(filename);
     free(arg_path);
     if (!input) {
         bb_perror_msg("%s", filename);
         /* POSIX: non-interactive shell should abort here,
          * not merely fail. So far no one complained :)
          */
         return EXIT_FAILURE;
     }
 #if ENABLE_HUSH_FUNCTIONS
     sv_flg = G_flag_return_in_progress;
     /* "we are inside sourced file, ok to use return" */
     G_flag_return_in_progress = -1;
 #endif
     args_need_save = argv[1]; /* used as a boolean variable */
     if (args_need_save)
         save_and_replace_G_args(&sv, argv);
     /* "false; . ./empty_line; echo Zero:$?" should print 0 */
     G.last_exitcode = 0;
     parse_and_run_file(input);
     hfclose(input);
     if (args_need_save) /* can't use argv[1] instead: "shift" can mangle it */
         restore_G_args(&sv, argv);
 #if ENABLE_HUSH_FUNCTIONS
     G_flag_return_in_progress = sv_flg;
 #endif
     return G.last_exitcode;
 }
References argv, bb_perror_msg(), bb_simple_perror_msg(), ENOENT, errno, EXIT_FAILURE, filename, find_in_path(), free, G, G_flag_return_in_progress, hfclose(), hfopen(), input, NULL, parse_and_run_file(), restore_G_args(), save_and_replace_G_args(), skip_dash_dash(), strchr(), and sv.
builtin_true() [1/2]
static int FAST_FUNC builtin_true (char **argv UNUSED_PARAM) static
Definition at line 10760 of file hush.c.
 {
     return 0;
 }
builtin_true() [2/2]
static int builtin_true (char ** argv) static
check_and_run_traps()
static int check_and_run_traps (void) static
Definition at line 2119 of file hush.c.
 {
     int last_sig = 0;
     while (1) {
         int sig;
         if (sigisemptyset(&G.pending_set))
             break;
         sig = 0;
         do {
             sig++;
             if (sigismember(&G.pending_set, sig)) {
                 sigdelset(&G.pending_set, sig);
                 goto got_sig;
             }
         } while (sig < NSIG);
         break;
  got_sig:
 #if ENABLE_HUSH_TRAP
         if (G_traps && G_traps[sig]) {
             debug_printf_exec("%s: sig:%d handler:'%s'\n", __func__, sig, G.traps[sig]);
             if (G_traps[sig][0]) {
                 /* We have user-defined handler */
                 smalluint save_rcode;
                 int save_pre;
                 char *argv[3];
                 /* argv[0] is unused */
                 argv[1] = xstrdup(G_traps[sig]);
                 /* why strdup? trap can modify itself: trap 'trap "echo oops" INT' INT */
                 argv[2] = NULL;
                 save_pre = G.pre_trap_exitcode;
                 G.pre_trap_exitcode = save_rcode = G.last_exitcode;
                 builtin_eval(argv);
                 free(argv[1]);
                 G.pre_trap_exitcode = save_pre;
                 G.last_exitcode = save_rcode;
 # if ENABLE_HUSH_FUNCTIONS
                 if (G.return_exitcode >= 0) {
                     debug_printf_exec("trap exitcode:%d\n", G.return_exitcode);
                     G.last_exitcode = G.return_exitcode;
                 }
 # endif
                 last_sig = sig;
             } /* else: "" trap, ignoring signal */
             continue;
         }
 #endif
         /* not a trap: special action */
         switch (sig) {
         case SIGINT:
             debug_printf_exec("%s: sig:%d default SIGINT handler\n", __func__, sig);
             G.flag_SIGINT = 1;
             last_sig = sig;
             break;
 #if ENABLE_HUSH_JOB
         case SIGHUP: {
 //TODO: why are we doing this? ash and dash don't do this,
 //they have no handler for SIGHUP at all,
 //they rely on kernel to send SIGHUP+SIGCONT to orphaned process groups
             struct pipe *job;
             debug_printf_exec("%s: sig:%d default SIGHUP handler\n", __func__, sig);
             /* bash is observed to signal whole process groups,
              * not individual processes */
             for (job = G.job_list; job; job = job->next) {
                 if (job->pgrp <= 0)
                     continue;
                 debug_printf_exec("HUPing pgrp %d\n", job->pgrp);
                 if (kill(- job->pgrp, SIGHUP) == 0)
                     kill(- job->pgrp, SIGCONT);
             }
             sigexit(SIGHUP);
         }
 #endif
 #if ENABLE_HUSH_FAST
         case SIGCHLD:
             debug_printf_exec("%s: sig:%d default SIGCHLD handler\n", __func__, sig);
             G.count_SIGCHLD++;
 //bb_error_msg("[%d] check_and_run_traps: G.count_SIGCHLD:%d G.handled_SIGCHLD:%d", getpid(), G.count_SIGCHLD, G.handled_SIGCHLD);
             /* Note:
              * We don't do 'last_sig = sig' here -> NOT returning this sig.
              * This simplifies wait builtin a bit.
              */
             break;
 #endif
         default: /* ignored: */
             debug_printf_exec("%s: sig:%d default handling is to ignore\n", __func__, sig);
             /* SIGTERM, SIGQUIT, SIGTTIN, SIGTTOU, SIGTSTP */
             /* Note:
              * We don't do 'last_sig = sig' here -> NOT returning this sig.
              * Example: wait is not interrupted by TERM
              * in interactive shell, because TERM is ignored.
              */
             break;
         }
     }
     return last_sig;
 }
References argv, builtin_eval(), debug_printf_exec, free, G, G_traps, kill(), NSIG, NULL, job::pgrp, SIGCHLD, SIGCONT, sigdelset(), SIGHUP, SIGINT, sigisemptyset(), sigismember(), and xstrdup().
Referenced by run_list().
checkjobs()
static int checkjobs (struct pipe * fg_pipe, pid_t waitfor_pid) static
Definition at line 9077 of file hush.c.
 {
     int attributes;
     int status;
     int rcode = 0;
     debug_printf_jobs("checkjobs %p\n", fg_pipe);
     attributes = WUNTRACED;
     if (fg_pipe == NULL)
         attributes |= WNOHANG;
     errno = 0;
 #if ENABLE_HUSH_FAST
     if (G.handled_SIGCHLD == G.count_SIGCHLD) {
 //bb_error_msg("[%d] checkjobs: G.count_SIGCHLD:%d G.handled_SIGCHLD:%d children?:%d fg_pipe:%p",
 //getpid(), G.count_SIGCHLD, G.handled_SIGCHLD, G.we_have_children, fg_pipe);
         /* There was neither fork nor SIGCHLD since last waitpid */
         /* Avoid doing waitpid syscall if possible */
         if (!G.we_have_children) {
             errno = ECHILD;
             return -1;
         }
         if (fg_pipe == NULL) { /* is WNOHANG set? */
             /* We have children, but they did not exit
              * or stop yet (we saw no SIGCHLD) */
             return 0;
         }
         /* else: !WNOHANG, waitpid will block, can't short-circuit */
     }
 #endif
 /* Do we do this right?
  * bash-3.00# sleep 20 | false
  * <ctrl-Z pressed>
  * [3]+  Stopped          sleep 20 | false
  * bash-3.00# echo $?
  * 1   <========== bg pipe is not fully done, but exitcode is already known!
  * [hush 1.14.0: yes we do it right]
  */
     while (1) {
         pid_t childpid;
 #if ENABLE_HUSH_FAST
         int i;
         i = G.count_SIGCHLD;
 #endif
         childpid = waitpid(-1, &status, attributes);
         if (childpid <= 0) {
             if (childpid && errno != ECHILD)
                 bb_simple_perror_msg("waitpid");
 #if ENABLE_HUSH_FAST
             else { /* Until next SIGCHLD, waitpid's are useless */
                 G.we_have_children = (childpid == 0);
                 G.handled_SIGCHLD = i;
 //bb_error_msg("[%d] checkjobs: waitpid returned <= 0, G.count_SIGCHLD:%d G.handled_SIGCHLD:%d", getpid(), G.count_SIGCHLD, G.handled_SIGCHLD);
             }
 #endif
             /* ECHILD (no children), or 0 (no change in children status) */
             rcode = childpid;
             break;
         }
         rcode = process_wait_result(fg_pipe, childpid, status);
         if (rcode >= 0) {
             /* fg_pipe exited or stopped */
             break;
         }
         if (childpid == waitfor_pid) { /* "wait PID" */
             debug_printf_exec("childpid==waitfor_pid:%d status:0x%08x\n", childpid, status);
             rcode = WEXITSTATUS(status);
             if (WIFSIGNALED(status))
                 rcode = 128 | WTERMSIG(status);
             if (WIFSTOPPED(status))
                 /* bash: "cmd & wait $!" and cmd stops: $? = 128 | stopsig */
                 rcode = 128 | WSTOPSIG(status);
             rcode++;
             break; /* "wait PID" called us, give it exitcode+1 */
         }
 #if ENABLE_HUSH_BASH_COMPAT
         if (-1 == waitfor_pid /* "wait -n" (wait for any one job) */
          && G.dead_job_exitcode >= 0 /* some job did finish */
         ) {
             debug_printf_exec("waitfor_pid:-1\n");
             rcode = G.dead_job_exitcode + 1;
             break;
         }
 #endif
         /* This wasn't one of our processes, or */
         /* fg_pipe still has running processes, do waitpid again */
     } /* while (waitpid succeeds)... */
     return rcode;
 }
References attributes, bb_simple_perror_msg(), debug_printf_exec, debug_printf_jobs, ECHILD, errno, G, i, NULL, process_wait_result(), status, waitpid(), WEXITSTATUS, WIFSIGNALED, WIFSTOPPED, WNOHANG, WSTOPSIG, WTERMSIG, and WUNTRACED.
Referenced by run_list().
die_if_script()
static void die_if_script (void) static
Definition at line 1391 of file hush.c.
 {
     if (!G_interactive_fd) {
         if (G.last_exitcode) /* sometines it's 2, not 1 (bash compat) */
             xfunc_error_retval = G.last_exitcode;
         xfunc_die();
     }
 }
References G, G_interactive_fd, xfunc_die(), and xfunc_error_retval.
Referenced by msg_and_die_if_script(), syntax_error(), syntax_error_at(), and syntax_error_unexpected_ch().
done_command()
static int done_command (struct parse_context * ctx) static
Definition at line 3798 of file hush.c.
 {
     /* The command is really already in the pipe structure, so
      * advance the pipe counter and make a new, null command. */
     struct pipe *pi = ctx->pipe;
     struct command *command = ctx->command;
 #if 0   /* Instead we emit error message at run time */
     if (ctx->pending_redirect) {
         /* For example, "cmd >" (no filename to redirect to) */
         syntax_error("invalid redirect");
         ctx->pending_redirect = NULL;
     }
 #endif
     if (command) {
         if (IS_NULL_CMD(command)) {
             debug_printf_parse("done_command: skipping null cmd, num_cmds=%d\n", pi->num_cmds);
             goto clear_and_ret;
         }
         pi->num_cmds++;
         debug_printf_parse("done_command: ++num_cmds=%d\n", pi->num_cmds);
         //debug_print_tree(ctx->list_head, 20);
     } else {
         debug_printf_parse("done_command: initializing, num_cmds=%d\n", pi->num_cmds);
     }
     /* Only real trickiness here is that the uncommitted
      * command structure is not counted in pi->num_cmds. */
     pi->cmds = xrealloc(pi->cmds, sizeof(*pi->cmds) * (pi->num_cmds+1));
     ctx->command = command = &pi->cmds[pi->num_cmds];
  clear_and_ret:
     memset(command, 0, sizeof(*command));
 #if ENABLE_HUSH_LINENO_VAR
     command->lineno = G.parse_lineno;
     debug_printf_parse("command->lineno = G.parse_lineno (%u)\n", G.parse_lineno);
 #endif
     return pi->num_cmds; /* used only for 0/nonzero check */
 }
References debug_printf_parse, G, IS_NULL_CMD, memset(), NULL, pi, syntax_error, and xrealloc.
Referenced by done_pipe(), initialize_context(), and parse_stream().
done_pipe()
static void done_pipe (struct parse_context * ctx, pipe_style type) static
Definition at line 3838 of file hush.c.
 {
     int not_null;
     debug_printf_parse("done_pipe entered, followup %d\n", type);
     /* Close previous command */
     not_null = done_command(ctx);
 #if HAS_KEYWORDS
     ctx->pipe->pi_inverted = ctx->ctx_inverted;
     ctx->ctx_inverted = 0;
     ctx->pipe->res_word = ctx->ctx_res_w;
 #endif
     if (type == PIPE_BG && ctx->list_head != ctx->pipe) {
         /* Necessary since && and || have precedence over &:
          * "cmd1 && cmd2 &" must spawn both cmds, not only cmd2,
          * in a backgrounded subshell.
          */
         struct pipe *pi;
         struct command *command;
         /* Is this actually this construct, all pipes end with && or ||? */
         pi = ctx->list_head;
         while (pi != ctx->pipe) {
             if (pi->followup != PIPE_AND && pi->followup != PIPE_OR)
                 goto no_conv;
             pi = pi->next;
         }
         debug_printf_parse("BG with more than one pipe, converting to { p1 &&...pN; } &\n");
         pi->followup = PIPE_SEQ; /* close pN _not_ with "&"! */
         pi = xzalloc(sizeof(*pi));
         pi->followup = PIPE_BG;
         pi->num_cmds = 1;
         pi->cmds = xzalloc(sizeof(pi->cmds[0]));
         command = &pi->cmds[0];
         if (CMD_NORMAL != 0) /* "if xzalloc didn't do that already" */
             command->cmd_type = CMD_NORMAL;
         command->group = ctx->list_head;
 #if !BB_MMU
         command->group_as_string = xstrndup(
                 ctx->as_string.data,
                 ctx->as_string.length - 1 /* do not copy last char, "&" */
         );
 #endif
         /* Replace all pipes in ctx with one newly created */
         ctx->list_head = ctx->pipe = pi;
         /* for cases like "cmd && &", do not be tricked by last command
          * being null - the entire {...} & is NOT null! */
         not_null = 1;
     } else {
  no_conv:
         ctx->pipe->followup = type;
     }
     /* Without this check, even just <enter> on command line generates
      * tree of three NOPs (!). Which is harmless but annoying.
      * IOW: it is safe to do it unconditionally. */
     if (not_null
 #if ENABLE_HUSH_IF
      || ctx->ctx_res_w == RES_FI
 #endif
 #if ENABLE_HUSH_LOOPS
      || ctx->ctx_res_w == RES_DONE
      || ctx->ctx_res_w == RES_FOR
      || ctx->ctx_res_w == RES_IN
 #endif
 #if ENABLE_HUSH_CASE
      || ctx->ctx_res_w == RES_ESAC
 #endif
     ) {
         struct pipe *new_p;
         debug_printf_parse("done_pipe: adding new pipe: "
                 "not_null:%d ctx->ctx_res_w:%d\n",
                 not_null, ctx->ctx_res_w);
         new_p = new_pipe();
         ctx->pipe->next = new_p;
         ctx->pipe = new_p;
         /* RES_THEN, RES_DO etc are "sticky" -
          * they remain set for pipes inside if/while.
          * This is used to control execution.
          * RES_FOR and RES_IN are NOT sticky (needed to support
          * cases where variable or value happens to match a keyword):
          */
 #if ENABLE_HUSH_LOOPS
         if (ctx->ctx_res_w == RES_FOR
          || ctx->ctx_res_w == RES_IN)
             ctx->ctx_res_w = RES_NONE;
 #endif
 #if ENABLE_HUSH_CASE
         if (ctx->ctx_res_w == RES_MATCH)
             ctx->ctx_res_w = RES_CASE_BODY;
         if (ctx->ctx_res_w == RES_CASE)
             ctx->ctx_res_w = RES_CASE_IN;
 #endif
         ctx->command = NULL; /* trick done_command below */
         /* Create the memory for command, roughly:
          * ctx->pipe->cmds = new struct command;
          * ctx->command = &ctx->pipe->cmds[0];
          */
         done_command(ctx);
         //debug_print_tree(ctx->list_head, 10);
     }
     debug_printf_parse("done_pipe return\n");
 }
References CMD_NORMAL, command::cmd_type, debug_printf_parse, done_command(), command::group, command::group_as_string, new_pipe(), NULL, pi, PIPE_AND, PIPE_BG, PIPE_OR, PIPE_SEQ, RES_NONE, type, xstrndup(), and xzalloc().
Referenced by done_word(), and parse_stream().
done_word()
static int done_word (struct parse_context * ctx) static
Definition at line 4127 of file hush.c.
 {
     struct command *command = ctx->command;
     debug_printf_parse("done_word entered: '%s' %p\n", ctx->word.data, command);
     if (ctx->word.length == 0 && !ctx->word.has_quoted_part) {
         debug_printf_parse("done_word return 0: true null, ignored\n");
         return 0;
     }
     if (ctx->pending_redirect) {
         /* We do not glob in e.g. >*.tmp case. bash seems to glob here
          * only if run as "bash", not "sh" */
         /* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html
          * "2.7 Redirection
          * If the redirection operator is "<<" or "<<-", the word
          * that follows the redirection operator shall be
          * subjected to quote removal; it is unspecified whether
          * any of the other expansions occur. For the other
          * redirection operators, the word that follows the
          * redirection operator shall be subjected to tilde
          * expansion, parameter expansion, command substitution,
          * arithmetic expansion, and quote removal.
          * Pathname expansion shall not be performed
          * on the word by a non-interactive shell; an interactive
          * shell may perform it, but shall do so only when
          * the expansion would result in one word."
          */
 //bash does not do parameter/command substitution or arithmetic expansion
 //for _heredoc_ redirection word: these constructs look for exact eof marker
 // as written:
 // <<EOF$t
 // <<EOF$((1))
 // <<EOF`true`  [this case also makes heredoc "quoted", a-la <<"EOF". Probably bash-4.3.43 bug]
         ctx->pending_redirect->rd_filename = xstrdup(ctx->word.data);
         /* Cater for >\file case:
          * >\a creates file a; >\\a, >"\a", >"\\a" create file \a
          * Same with heredocs:
          * for <<\H delim is H; <<\\H, <<"\H", <<"\\H" - \H
          */
         if (ctx->pending_redirect->rd_type == REDIRECT_HEREDOC) {
             unbackslash(ctx->pending_redirect->rd_filename);
             /* Is it <<"HEREDOC"? */
             if (ctx->word.has_quoted_part) {
                 ctx->pending_redirect->rd_dup |= HEREDOC_QUOTED;
             }
         }
         debug_printf_parse("word stored in rd_filename: '%s'\n", ctx->word.data);
         ctx->pending_redirect = NULL;
     } else {
 #if HAS_KEYWORDS
 # if ENABLE_HUSH_CASE
         if (ctx->ctx_dsemicolon
          && strcmp(ctx->word.data, "esac") != 0 /* not "... pattern) cmd;; esac" */
         ) {
             /* already done when ctx_dsemicolon was set to 1: */
             /* ctx->ctx_res_w = RES_MATCH; */
             ctx->ctx_dsemicolon = 0;
         } else
 # endif
 # if defined(CMD_TEST2_SINGLEWORD_NOGLOB)
         if (command->cmd_type == CMD_TEST2_SINGLEWORD_NOGLOB
          && strcmp(ctx->word.data, "]]") == 0
         ) {
             /* allow "[[ ]] >file" etc */
             command->cmd_type = CMD_SINGLEWORD_NOGLOB;
         } else
 # endif
         if (!command->argv /* if it's the first word... */
 # if ENABLE_HUSH_LOOPS
          && ctx->ctx_res_w != RES_FOR /* ...not after FOR or IN */
          && ctx->ctx_res_w != RES_IN
 # endif
 # if ENABLE_HUSH_CASE
          && ctx->ctx_res_w != RES_CASE
 # endif
         ) {
             const struct reserved_combo *reserved;
             reserved = reserved_word(ctx);
             debug_printf_parse("checking for reserved-ness: %d\n", !!reserved);
             if (reserved) {
 # if ENABLE_HUSH_LINENO_VAR
 /* Case:
  * "while ...; do
  *  cmd ..."
  * If we don't close the pipe _now_, immediately after "do", lineno logic
  * sees "cmd" as starting at "do" - i.e., at the previous line.
  */
                 if (0
                  IF_HUSH_IF(|| reserved->res == RES_THEN)
                  IF_HUSH_IF(|| reserved->res == RES_ELIF)
                  IF_HUSH_IF(|| reserved->res == RES_ELSE)
                  IF_HUSH_LOOPS(|| reserved->res == RES_DO)
                 ) {
                     done_pipe(ctx, PIPE_SEQ);
                 }
 # endif
                 o_reset_to_empty_unquoted(&ctx->word);
                 debug_printf_parse("done_word return %d\n",
                         (ctx->ctx_res_w == RES_SNTX));
                 return (ctx->ctx_res_w == RES_SNTX);
             }
 # if defined(CMD_TEST2_SINGLEWORD_NOGLOB)
             if (strcmp(ctx->word.data, "[[") == 0) {
                 command->cmd_type = CMD_TEST2_SINGLEWORD_NOGLOB;
             } else
 # endif
 # if defined(CMD_SINGLEWORD_NOGLOB)
             if (0
             /* In bash, local/export/readonly are special, args
              * are assignments and therefore expansion of them
              * should be "one-word" expansion:
              *  $ export i=`echo 'a  b'` # one arg: "i=a  b"
              * compare with:
              *  $ ls i=`echo 'a  b'`     # two args: "i=a" and "b"
              *  ls: cannot access i=a: No such file or directory
              *  ls: cannot access b: No such file or directory
              * Note: bash 3.2.33(1) does this only if export word
              * itself is not quoted:
              *  $ export i=`echo 'aaa  bbb'`; echo "$i"
              *  aaa  bbb
              *  $ "export" i=`echo 'aaa  bbb'`; echo "$i"
              *  aaa
              */
              IF_HUSH_LOCAL(   || strcmp(ctx->word.data, "local") == 0)
              IF_HUSH_EXPORT(  || strcmp(ctx->word.data, "export") == 0)
              IF_HUSH_READONLY(|| strcmp(ctx->word.data, "readonly") == 0)
             ) {
                 command->cmd_type = CMD_SINGLEWORD_NOGLOB;
             }
 # else
             { /* empty block to pair "if ... else" */ }
 # endif
         }
 #endif /* HAS_KEYWORDS */
         if (command->group) {
             /* "{ echo foo; } echo bar" - bad */
             syntax_error_at(ctx->word.data);
             debug_printf_parse("done_word return 1: syntax error, "
                     "groups and arglists don't mix\n");
             return 1;
         }
         /* If this word wasn't an assignment, next ones definitely
          * can't be assignments. Even if they look like ones. */
         if (ctx->is_assignment != DEFINITELY_ASSIGNMENT
          && ctx->is_assignment != WORD_IS_KEYWORD
         ) {
             ctx->is_assignment = NOT_ASSIGNMENT;
         } else {
             if (ctx->is_assignment == DEFINITELY_ASSIGNMENT) {
                 command->assignment_cnt++;
                 debug_printf_parse("++assignment_cnt=%d\n", command->assignment_cnt);
             }
             debug_printf_parse("ctx->is_assignment was:'%s'\n", assignment_flag[ctx->is_assignment]);
             ctx->is_assignment = MAYBE_ASSIGNMENT;
         }
         debug_printf_parse("ctx->is_assignment='%s'\n", assignment_flag[ctx->is_assignment]);
         command->argv = add_string_to_strings(command->argv, xstrdup(ctx->word.data));
         debug_print_strings("word appended to argv", command->argv);
     }
 #if ENABLE_HUSH_LOOPS
     if (ctx->ctx_res_w == RES_FOR) {
         if (ctx->word.has_quoted_part
          || endofname(command->argv[0])[0] != '\0'
         ) {
             /* bash says just "not a valid identifier" */
             syntax_error("bad variable name in for");
             return 1;
         }
         /* Force FOR to have just one word (variable name) */
         /* NB: basically, this makes hush see "for v in ..."
          * syntax as if it is "for v; in ...". FOR and IN become
          * two pipe structs in parse tree. */
         done_pipe(ctx, PIPE_SEQ);
     }
 #endif
 #if ENABLE_HUSH_CASE
     /* Force CASE to have just one word */
     if (ctx->ctx_res_w == RES_CASE) {
         done_pipe(ctx, PIPE_SEQ);
     }
 #endif
     o_reset_to_empty_unquoted(&ctx->word);
     debug_printf_parse("done_word return 0\n");
     return 0;
 }
References add_string_to_strings(), command::argv, command::assignment_cnt, command::cmd_type, debug_print_strings, debug_printf_parse, DEFINITELY_ASSIGNMENT, done_pipe(), endofname(), command::group, HEREDOC_QUOTED, MAYBE_ASSIGNMENT, NOT_ASSIGNMENT, NULL, o_reset_to_empty_unquoted(), PIPE_SEQ, REDIRECT_HEREDOC, RES_SNTX, strcmp, syntax_error, syntax_error_at, unbackslash(), WORD_IS_KEYWORD, and xstrdup().
Referenced by parse_group(), and parse_stream().
dup_CLOEXEC()
static int dup_CLOEXEC (int fd, int avoid_fd) static
Definition at line 1568 of file hush.c.
 {
     int newfd;
  repeat:
     newfd = fcntl(fd, F_DUPFD_CLOEXEC, avoid_fd + 1);
     if (newfd >= 0) {
         if (F_DUPFD_CLOEXEC == F_DUPFD) /* if old libc (w/o F_DUPFD_CLOEXEC) */
             fcntl(newfd, F_SETFD, FD_CLOEXEC);
     } else { /* newfd < 0 */
         if (errno == EBUSY)
             goto repeat;
         if (errno == EINTR)
             goto repeat;
     }
     return newfd;
 }
References EBUSY, EINTR, errno, F_DUPFD, F_DUPFD_CLOEXEC, F_SETFD, fcntl(), fd, and FD_CLOEXEC.
Referenced by add_squirrel(), hush_main(), and set_mode().
encode_string()
static int encode_string (o_string * as_string, o_string * dest, struct in_str * input, int dquote_end) static
Definition at line 5330 of file hush.c.
 {
     int ch;
     int next;
  again:
     ch = i_getch(input);
     if (ch != EOF)
         nommu_addchr(as_string, ch);
     if (ch == dquote_end) { /* may be only '"' or EOF */
         debug_printf_parse("encode_string return 1 (ok)\n");
         return 1;
     }
     /* note: can't move it above ch == dquote_end check! */
     if (ch == EOF) {
         syntax_error_unterm_ch('"');
         return 0; /* error */
     }
     next = '\0';
     if (ch != '\n') {
         next = i_peek(input);
     }
     debug_printf_parse("\" ch=%c (%d) escape=%d\n",
             ch, ch, !!(dest->o_expflags & EXP_FLAG_ESC_GLOB_CHARS));
     if (ch == '\\') {
         if (next == EOF) {
             /* Testcase: in interactive shell a file with
              *  echo "unterminated string<eof>
              * is sourced.
              */
             syntax_error_unterm_ch('"');
             return 0; /* error */
         }
         /* bash:
          * "The backslash retains its special meaning [in "..."]
          * only when followed by one of the following characters:
          * $, `, ", \, or <newline>.  A double quote may be quoted
          * within double quotes by preceding it with a backslash."
          * NB: in (unquoted) heredoc, above does not apply to ",
          * therefore we check for it by "next == dquote_end" cond.
          */
         if (next == dquote_end || strchr("$`\\\n", next)) {
             ch = i_getch(input); /* eat next */
             if (ch == '\n')
                 goto again; /* skip <newline> */
         } /* else: ch remains == '\\', and we double it below: */
         o_addqchr(dest, ch); /* \c if c is a glob char, else just c */
         nommu_addchr(as_string, ch);
         goto again;
     }
     if (ch == '$') {
         //if (parse_dollar_squote(as_string, dest, input))
         //  goto again;
         if (!parse_dollar(as_string, dest, input, /*quote_mask:*/ 0x80)) {
             debug_printf_parse("encode_string return 0: "
                     "parse_dollar returned 0 (error)\n");
             return 0;
         }
         goto again;
     }
 #if ENABLE_HUSH_TICK
     if (ch == '`') {
         //unsigned pos = dest->length;
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         o_addchr(dest, 0x80 | '`');
         if (!add_till_backquote(dest, input, /*in_dquote:*/ dquote_end == '"'))
             return 0; /* error */
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         //debug_printf_subst("SUBST RES3 '%s'\n", dest->data + pos);
         goto again;
     }
 #endif
     o_addQchr(dest, ch);
     if (ch == SPECIAL_VAR_SYMBOL) {
         /* Convert "^C" to corresponding special variable reference */
         o_addchr(dest, SPECIAL_VAR_QUOTED_SVS);
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
     }
     goto again;
 #undef as_string
 }
References add_till_backquote(), debug_printf_parse, EOF, EXP_FLAG_ESC_GLOB_CHARS, i_getch(), i_peek(), input, next, nommu_addchr(), o_addchr(), o_addqchr(), o_addQchr(), o_string::o_expflags, parse_dollar(), SPECIAL_VAR_QUOTED_SVS, SPECIAL_VAR_SYMBOL, strchr(), and syntax_error_unterm_ch.
Referenced by encode_then_expand_string(), and parse_stream().
encode_then_append_var_plusminus()
static NOINLINE int encode_then_append_var_plusminus (o_string * output, int n, char * str, int dquoted) static
Definition at line 6346 of file hush.c.
 {
     struct in_str input;
     o_string dest = NULL_O_STRING;
     if (!first_special_char_in_vararg(str)
      && '\0' == str[strcspn(str, G.ifs)]
     ) {
         /* string has no special chars
          * && string has no $IFS chars
          */
         if (dquoted) {
             /* Prints 1 (quoted expansion is a "" word, not nothing):
              * set -- "${notexist-}"; echo $#
              */
             output->has_quoted_part = 1;
         }
         return expand_vars_to_list(output, n, str);
     }
     setup_string_in_str(&input, str);
     for (;;) {
         int ch;
         ch = i_getch(&input);
         debug_printf_parse("%s: ch=%c (%d) escape=%x\n",
                 __func__, ch, ch, dest.o_expflags);
         if (!dest.o_expflags) {
             if (ch == EOF)
                 break;
             if (!dquoted && strchr(G.ifs, ch)) {
                 /* PREFIX${x:d${e}f ...} and we met space: expand "d${e}f" and start new word.
                  * do not assume we are at the start of the word (PREFIX above).
                  */
                 if (dest.data) {
                     n = expand_vars_to_list(output, n, dest.data);
                     o_free_and_set_NULL(&dest);
                     o_addchr(output, '\0');
                     n = o_save_ptr(output, n); /* create next word */
                 } else
                 if (output->length != o_get_last_ptr(output, n)
                  || output->has_quoted_part
                 ) {
                     /* For these cases:
                      * f() { for i; do echo "|$i|"; done; }; x=x
                      * f a${x:+ }b  # 1st condition
                      * |a|
                      * |b|
                      * f ""${x:+ }b  # 2nd condition
                      * ||
                      * |b|
                      */
                     o_addchr(output, '\0');
                     n = o_save_ptr(output, n); /* create next word */
                 }
                 continue;
             }
             if (!dquoted && ch == '\'') {
                 if (!add_till_single_quote_dquoted(&dest, &input))
                     goto ret; /* error */
                 o_addchr(&dest, SPECIAL_VAR_SYMBOL);
                 o_addchr(&dest, SPECIAL_VAR_SYMBOL);
                 continue;
             }
         }
         if (ch == EOF) {
             syntax_error_unterm_ch('"');
             goto ret; /* error */
         }
         if (ch == '"') {
             dest.o_expflags ^= EXP_FLAG_ESC_GLOB_CHARS;
             if (dest.o_expflags) {
                 o_addchr(&dest, SPECIAL_VAR_SYMBOL);
                 o_addchr(&dest, SPECIAL_VAR_SYMBOL);
             }
             continue;
         }
         if (ch == '\\') {
             ch = i_getch(&input);
             if (ch == EOF) {
 //example? error message?   syntax_error_unterm_ch('"');
                 debug_printf_parse("%s: error: \\<eof>\n", __func__);
                 goto ret;
             }
             o_addqchr(&dest, ch);
             continue;
         }
         if (ch == '$') {
             if (!parse_dollar(NULL, &dest, &input, /*quote_mask:*/ (dest.o_expflags || dquoted) ? 0x80 : 0)) {
                 debug_printf_parse("%s: error: parse_dollar returned 0 (error)\n", __func__);
                 goto ret;
             }
             continue;
         }
 #if ENABLE_HUSH_TICK
         if (ch == '`') {
             //unsigned pos = dest->length;
             o_addchr(&dest, SPECIAL_VAR_SYMBOL);
             o_addchr(&dest, (dest.o_expflags || dquoted) ? 0x80 | '`' : '`');
             if (!add_till_backquote(&dest, &input,
                     /*in_dquote:*/ dest.o_expflags /* nonzero if EXP_FLAG_ESC_GLOB_CHARS set */
                 )
             ) {
                 goto ret; /* error */
             }
             o_addchr(&dest, SPECIAL_VAR_SYMBOL);
             //debug_printf_subst("SUBST RES3 '%s'\n", dest->data + pos);
             continue;
         }
 #endif
         if (dquoted) {
             /* Always glob-protect if in dquotes:
              * x=x; echo "${x:+/bin/c*}" - prints: /bin/c*
              * x=x; echo "${x:+"/bin/c*"}" - prints: /bin/c*
              */
             o_addqchr(&dest, ch);
         } else {
             /* Glob-protect only if char is quoted:
              * x=x; echo ${x:+/bin/c*} - prints many filenames
              * x=x; echo ${x:+"/bin/c*"} - prints: /bin/c*
              */
             o_addQchr(&dest, ch);
         }
     } /* for (;;) */
     if (dest.data) {
         n = expand_vars_to_list(output, n, dest.data);
     }
  ret:
     o_free(&dest);
     return n;
 }
References add_till_backquote(), add_till_single_quote_dquoted(), debug_printf_parse, EOF, EXP_FLAG_ESC_GLOB_CHARS, expand_vars_to_list(), first_special_char_in_vararg(), G, i_getch(), input, n, NULL, NULL_O_STRING, o_addchr(), o_addqchr(), o_addQchr(), o_free(), o_free_and_set_NULL(), o_get_last_ptr(), o_save_ptr(), output, parse_dollar(), setup_string_in_str(), SPECIAL_VAR_SYMBOL, str, strchr(), strcspn(), and syntax_error_unterm_ch.
Referenced by expand_one_var().
encode_then_expand_string()
static char* encode_then_expand_string (const char * str) static
Definition at line 6188 of file hush.c.
 {
     char *exp_str;
     struct in_str input;
     o_string dest = NULL_O_STRING;
     const char *cp;
     cp = str;
     for (;;) {
         if (!*cp) return NULL; /* string has no special chars */
         if (*cp == '$') break;
         if (*cp == '\\') break;
 #if ENABLE_HUSH_TICK
         if (*cp == '`') break;
 #endif
         cp++;
     }
     /* We need to expand. Example:
      * echo $(($a + `echo 1`)) $((1 + $((2)) ))
      */
     setup_string_in_str(&input, str);
     encode_string(NULL, &dest, &input, EOF);
 //TODO: error check (encode_string returns 0 on error)?
     //bb_error_msg("'%s' -> '%s'", str, dest.data);
     exp_str = expand_string_to_string(dest.data,
             EXP_FLAG_ESC_GLOB_CHARS,
             /*unbackslash:*/ 1
     );
     //bb_error_msg("'%s' -> '%s'", dest.data, exp_str);
     o_free(&dest);
     return exp_str;
 }
References encode_string(), EOF, EXP_FLAG_ESC_GLOB_CHARS, expand_string_to_string, input, NULL, NULL_O_STRING, o_free(), setup_string_in_str(), and str.
Referenced by setup_heredoc().
encode_then_expand_vararg()
static char* encode_then_expand_vararg (const char * str, int handle_squotes, int do_unbackslash) static
Definition at line 6253 of file hush.c.
 {
 #if !BASH_PATTERN_SUBST && ENABLE_HUSH_CASE
     const int do_unbackslash = 0;
 #endif
     char *exp_str;
     struct in_str input;
     o_string dest = NULL_O_STRING;
     if (!first_special_char_in_vararg(str)) {
         /* string has no special chars */
         return NULL;
     }
     setup_string_in_str(&input, str);
     dest.data = xzalloc(1); /* start as "", not as NULL */
     exp_str = NULL;
     for (;;) {
         int ch;
         ch = i_getch(&input);
         debug_printf_parse("%s: ch=%c (%d) escape=%d\n",
                 __func__, ch, ch, !!dest.o_expflags);
         if (!dest.o_expflags) {
             if (ch == EOF)
                 break;
             if (handle_squotes && ch == '\'') {
                 if (!add_till_single_quote_dquoted(&dest, &input))
                     goto ret; /* error */
                 continue;
             }
         }
         if (ch == EOF) {
             syntax_error_unterm_ch('"');
             goto ret; /* error */
         }
         if (ch == '"') {
             dest.o_expflags ^= EXP_FLAG_ESC_GLOB_CHARS;
             continue;
         }
         if (ch == '\\') {
             ch = i_getch(&input);
             if (ch == EOF) {
 //example? error message?   syntax_error_unterm_ch('"');
                 debug_printf_parse("%s: error: \\<eof>\n", __func__);
                 goto ret;
             }
             o_addqchr(&dest, ch);
             continue;
         }
         if (ch == '$') {
             if (parse_dollar_squote(NULL, &dest, &input))
                 continue;
             if (!parse_dollar(NULL, &dest, &input, /*quote_mask:*/ 0x80)) {
                 debug_printf_parse("%s: error: parse_dollar returned 0 (error)\n", __func__);
                 goto ret;
             }
             continue;
         }
 #if ENABLE_HUSH_TICK
         if (ch == '`') {
             //unsigned pos = dest->length;
             o_addchr(&dest, SPECIAL_VAR_SYMBOL);
             o_addchr(&dest, 0x80 | '`');
             if (!add_till_backquote(&dest, &input,
                     /*in_dquote:*/ dest.o_expflags /* nonzero if EXP_FLAG_ESC_GLOB_CHARS set */
                 )
             ) {
                 goto ret; /* error */
             }
             o_addchr(&dest, SPECIAL_VAR_SYMBOL);
             //debug_printf_subst("SUBST RES3 '%s'\n", dest->data + pos);
             continue;
         }
 #endif
         o_addQchr(&dest, ch);
     } /* for (;;) */
     debug_printf_parse("encode: '%s' -> '%s'\n", str, dest.data);
     exp_str = expand_string_to_string(dest.data,
             do_unbackslash ? EXP_FLAG_ESC_GLOB_CHARS : 0,
             do_unbackslash
     );
  ret:
     debug_printf_parse("expand: '%s' -> '%s'\n", dest.data, exp_str);
     o_free(&dest);
     return exp_str;
 }
References add_till_backquote(), add_till_single_quote_dquoted(), debug_printf_parse, EOF, EXP_FLAG_ESC_GLOB_CHARS, expand_string_to_string, first_special_char_in_vararg(), i_getch(), input, NULL, NULL_O_STRING, o_addchr(), o_addqchr(), o_addQchr(), o_free(), parse_dollar(), parse_dollar_squote, setup_string_in_str(), SPECIAL_VAR_SYMBOL, str, syntax_error_unterm_ch, and xzalloc().
enter_var_nest_level()
static void enter_var_nest_level (void) static
Definition at line 8237 of file hush.c.
 {
     G.var_nest_level++;
     debug_printf_env("var_nest_level++ %u\n", G.var_nest_level);
     /* Try: f() { echo -n .; f; }; f
      * struct variable::var_nest_level is uint16_t,
      * thus limiting recursion to < 2^16.
      * In any case, with 8 Mbyte stack SEGV happens
      * not too long after 2^16 recursions anyway.
      */
     if (G.var_nest_level > 0xff00)
         bb_error_msg_and_die("fatal recursion (depth %u)", G.var_nest_level);
 }
References bb_error_msg_and_die(), debug_printf_env, and G.
Referenced by run_pipe().
exec_builtin()
static void exec_builtin (char *** to_free, const struct built_in_command * x, char ** argv) static
Definition at line 8455 of file hush.c.
 {
 #if BB_MMU
     int rcode;
 //? close_saved_fds_and_FILE_fds();
     rcode = x->b_function(argv);
     fflush_all();
     _exit(rcode);
 #else
     fflush_all();
     /* On NOMMU, we must never block!
      * Example: { sleep 99 | read line; } & echo Ok
      */
     re_execute_shell(to_free,
             argv[0],
             G.global_argv[0],
             G.global_argv + 1,
             argv);
 #endif
 }
References _exit(), argv, fflush_all(), G, re_execute_shell(), and x.
execvp_or_die()
static void execvp_or_die (char ** argv) static
Definition at line 8480 of file hush.c.
 {
     int e;
     debug_printf_exec("execing '%s'\n", argv[0]);
     /* Don't propagate SIG_IGN to the child */
     if (SPECIAL_JOBSTOP_SIGS != 0)
         switch_off_special_sigs(G.special_sig_mask & SPECIAL_JOBSTOP_SIGS);
     execvp(argv[0], argv);
     e = 2;
     if (errno == EACCES) e = 126;
     if (errno == ENOENT) e = 127;
     bb_perror_msg("can't execute '%s'", argv[0]);
     _exit(e);
 }
References _exit(), argv, bb_perror_msg(), debug_printf_exec, EACCES, ENOENT, errno, execvp(), G, SPECIAL_JOBSTOP_SIGS, and switch_off_special_sigs().
Referenced by builtin_exec(), and pseudo_exec_argv().
expand_assignments()
static char** expand_assignments (char ** argv, int count) static
Definition at line 7294 of file hush.c.
 {
     int i;
     char **p;
     G.expanded_assignments = p = NULL;
     /* Expand assignments into one string each */
     for (i = 0; i < count; i++) {
         p = add_string_to_strings(p,
             expand_string_to_string(argv[i],
                 EXP_FLAG_ESC_GLOB_CHARS,
                 /*unbackslash:*/ 1
             )
         );
         G.expanded_assignments = p;
     }
     G.expanded_assignments = NULL;
     return p;
 }
References add_string_to_strings(), argv, count, EXP_FLAG_ESC_GLOB_CHARS, expand_string_to_string, G, i, NULL, and p.
Referenced by pseudo_exec_argv(), and redirect_and_varexp_helper().
expand_on_ifs()
static int expand_on_ifs (o_string * output, int n, const char * str) static
Definition at line 6109 of file hush.c.
 {
     int last_is_ifs = 0;
     while (1) {
         int word_len;
         if (!*str)  /* EOL - do not finalize word */
             break;
         word_len = strcspn(str, G.ifs);
         if (word_len) {
             /* We have WORD_LEN leading non-IFS chars */
             if (!(output->o_expflags & EXP_FLAG_GLOB)) {
                 o_addblock(output, str, word_len);
             } else {
                 /* Protect backslashes against globbing up :)
                  * Example: "v='\*'; echo b$v" prints "b\*"
                  * (and does not try to glob on "*")
                  */
                 o_addblock_duplicate_backslash(output, str, word_len);
                 /*/ Why can't we do it easier? */
                 /*o_addblock(output, str, word_len); - WRONG: "v='\*'; echo Z$v" prints "Z*" instead of "Z\*" */
                 /*o_addqblock(output, str, word_len); - WRONG: "v='*'; echo Z$v" prints "Z*" instead of Z* files */
             }
             last_is_ifs = 0;
             str += word_len;
             if (!*str)  /* EOL - do not finalize word */
                 break;
         }
         /* We know str here points to at least one IFS char */
         last_is_ifs = 1;
         str += strspn(str, G.ifs_whitespace); /* skip IFS whitespace chars */
         if (!*str)  /* EOL - do not finalize word */
             break;
         if (G.ifs_whitespace != G.ifs /* usually false ($IFS is usually all whitespace), */
          && strchr(G.ifs, *str)       /* the second check would fail */
         ) {
             /* This is a non-whitespace $IFS char */
             /* Skip it and IFS whitespace chars, start new word */
             str++;
             str += strspn(str, G.ifs_whitespace);
             goto new_word;
         }
         /* Start new word... but not always! */
         /* Case "v=' a'; echo ''$v": we do need to finalize empty word: */
         if (output->has_quoted_part
         /*
          * Case "v=' a'; echo $v":
          * here nothing precedes the space in $v expansion,
          * therefore we should not finish the word
          * (IOW: if there *is* word to finalize, only then do it):
          * It's okay if this accesses the byte before first argv[]:
          * past call to o_save_ptr() cleared it to zero byte
          * (grep for -prev-ifs-check-).
          */
          || output->data[output->length - 1]
         ) {
  new_word:
             o_addchr(output, '\0');
             debug_print_list("expand_on_ifs", output, n);
             n = o_save_ptr(output, n);
         }
     }
     output->ended_in_ifs = last_is_ifs;
     debug_print_list("expand_on_ifs[1]", output, n);
     return n;
 }
References debug_print_list, EXP_FLAG_GLOB, G, n, o_addblock(), o_addblock_duplicate_backslash(), o_addchr(), o_save_ptr(), output, str, strchr(), strcspn(), and strspn().
Referenced by append_str_maybe_ifs_split(), and expand_vars_to_list().
expand_one_var()
static NOINLINE int expand_one_var (o_string * output, int n, int first_ch, char * arg, char ** pp) static
Definition at line 6596 of file hush.c.
 {
     const char *val;
     char *to_be_freed;
     char *p;
     char *var;
     char exp_op;
     char exp_save = exp_save; /* for compiler */
     char *exp_saveptr; /* points to expansion operator */
     char *exp_word = exp_word; /* for compiler */
     char arg0;
     val = NULL;
     to_be_freed = NULL;
     p = *pp;
     *p = '\0'; /* replace trailing SPECIAL_VAR_SYMBOL */
     var = arg;
     exp_saveptr = arg[1] ? strchr(VAR_ENCODED_SUBST_OPS, arg[1]) : NULL;
     arg0 = arg[0];
     arg[0] = (arg0 & 0x7f);
     exp_op = 0;
     if (arg[0] == '#' && arg[1] /* ${#...} but not ${#} */
      && (!exp_saveptr               /* and ( not(${#<op_char>...}) */
         || (arg[2] == '\0' && strchr(SPECIAL_VARS_STR, arg[1])) /* or ${#C} "len of $C" ) */
         )       /* NB: skipping ^^^specvar check mishandles ${#::2} */
     ) {
         /* It must be length operator: ${#var} */
         var++;
         exp_op = 'L';
     } else {
         /* Maybe handle parameter expansion */
         if (exp_saveptr /* if 2nd char is one of expansion operators */
          && strchr(NUMERIC_SPECVARS_STR, arg[0]) /* 1st char is special variable */
         ) {
             /* ${?:0}, ${#[:]%0} etc */
             exp_saveptr = var + 1;
         } else {
             /* ${?}, ${var}, ${var:0}, ${var[:]%0} etc */
             exp_saveptr = var+1 + strcspn(var+1, VAR_ENCODED_SUBST_OPS);
         }
         exp_op = exp_save = *exp_saveptr;
         if (exp_op) {
             exp_word = exp_saveptr + 1;
             if (exp_op == ':') {
                 exp_op = *exp_word++;
 //TODO: try ${var:} and ${var:bogus} in non-bash config
                 if (BASH_SUBSTR
                  && (!exp_op || !strchr(MINUS_PLUS_EQUAL_QUESTION, exp_op))
                 ) {
                     /* oops... it's ${var:N[:M]}, not ${var:?xxx} or some such */
                     exp_op = ':';
                     exp_word--;
                 }
             }
             *exp_saveptr = '\0';
         } /* else: it's not an expansion op, but bare ${var} */
     }
     /* Look up the variable in question */
     if (isdigit(var[0])) {
         /* parse_dollar should have vetted var for us */
         int nn = xatoi_positive(var);
         if (nn < G.global_argc)
             val = G.global_argv[nn];
         /* else val remains NULL: $N with too big N */
     } else {
         switch (var[0]) {
         case '$': /* pid */
             val = utoa(G.root_pid);
             break;
         case '!': /* bg pid */
             val = G.last_bg_pid ? utoa(G.last_bg_pid) : "";
             break;
         case '?': /* exitcode */
             val = utoa(G.last_exitcode);
             break;
         case '#': /* argc */
             val = utoa(G.global_argc ? G.global_argc-1 : 0);
             break;
         case '-': { /* active options */
             /* Check set_mode() to see what option chars we support */
             char *cp;
             val = cp = G.optstring_buf;
             if (G.o_opt[OPT_O_ERREXIT])
                 *cp++ = 'e';
             if (G_interactive_fd)
                 *cp++ = 'i';
             if (G_x_mode)
                 *cp++ = 'x';
             /* If G.o_opt[OPT_O_NOEXEC] is true,
              * commands read but are not executed,
              * so $- can not execute too, 'n' is never seen in $-.
              */
             if (G.opt_c)
                 *cp++ = 'c';
             if (G.opt_s)
                 *cp++ = 's';
             *cp = '\0';
             break;
         }
         default:
             val = get_local_var_value(var);
         }
     }
     /* Handle any expansions */
     if (exp_op == 'L') {
         reinit_unicode_for_hush();
         debug_printf_expand("expand: length(%s)=", val);
         val = utoa(val ? unicode_strlen(val) : 0);
         debug_printf_expand("%s\n", val);
     } else if (exp_op) {
         if (exp_op == '%' || exp_op == '#') {
             /* Standard-mandated substring removal ops:
              * ${parameter%word} - remove smallest suffix pattern
              * ${parameter%%word} - remove largest suffix pattern
              * ${parameter#word} - remove smallest prefix pattern
              * ${parameter##word} - remove largest prefix pattern
              *
              * Word is expanded to produce a glob pattern.
              * Then var's value is matched to it and matching part removed.
              */
             /* bash compat: if x is "" and no shrinking of it is possible,
              * inner ${...} is not evaluated. Example:
              *  unset b; : ${a%${b=B}}; echo $b
              * assignment b=B only happens if $a is not "".
              */
             if (val && val[0]) {
                 char *t;
                 char *exp_exp_word;
                 char *loc;
                 unsigned scan_flags = pick_scan(exp_op, *exp_word);
                 if (exp_op == *exp_word)  /* ## or %% */
                     exp_word++;
                 debug_printf_expand("expand: exp_word:'%s'\n", exp_word);
                 exp_exp_word = encode_then_expand_vararg(exp_word, /*handle_squotes:*/ 1, /*unbackslash:*/ 0);
                 if (exp_exp_word)
                     exp_word = exp_exp_word;
                 debug_printf_expand("expand: exp_word:'%s'\n", exp_word);
                 /*
                  * HACK ALERT. We depend here on the fact that
                  * G.global_argv and results of utoa and get_local_var_value
                  * are actually in writable memory:
                  * scan_and_match momentarily stores NULs there.
                  */
                 t = (char*)val;
                 loc = scan_and_match(t, exp_word, scan_flags);
                 debug_printf_expand("op:%c str:'%s' pat:'%s' res:'%s'\n", exp_op, t, exp_word, loc);
                 free(exp_exp_word);
                 if (loc) { /* match was found */
                     if (scan_flags & SCAN_MATCH_LEFT_HALF) /* #[#] */
                         val = loc; /* take right part */
                     else /* %[%] */
                         val = to_be_freed = xstrndup(val, loc - val); /* left */
                 }
             }
         }
 #if BASH_PATTERN_SUBST
         else if (exp_op == '/' || exp_op == '\\') {
             /* It's ${var/[/]pattern[/repl]} thing.
              * Note that in encoded form it has TWO parts:
              * var/pattern<SPECIAL_VAR_SYMBOL>repl<SPECIAL_VAR_SYMBOL>
              * and if // is used, it is encoded as \:
              * var\pattern<SPECIAL_VAR_SYMBOL>repl<SPECIAL_VAR_SYMBOL>
              */
             /* bash compat: if var is "", both pattern and repl
              * are still evaluated, if it is unset, then not:
              * unset b; a=; : ${a/z/${b=3}}; echo $b      # b=3
              * unset b; unset a; : ${a/z/${b=3}}; echo $b # b not set
              */
             if (val /*&& val[0]*/) {
                 /* pattern uses non-standard expansion.
                  * repl should be unbackslashed and globbed
                  * by the usual expansion rules:
                  *  >az >bz
                  *  v='a bz'; echo "${v/a*z/a*z}" #prints "a*z"
                  *  v='a bz'; echo "${v/a*z/\z}"  #prints "z"
                  *  v='a bz'; echo ${v/a*z/a*z}   #prints "az"
                  *  v='a bz'; echo ${v/a*z/\z}    #prints "z"
                  * (note that a*z _pattern_ is never globbed!)
                  */
                 char *pattern, *repl, *t;
                 pattern = encode_then_expand_vararg(exp_word, /*handle_squotes:*/ 1, /*unbackslash:*/ 0);
                 if (!pattern)
                     pattern = xstrdup(exp_word);
                 debug_printf_varexp("pattern:'%s'->'%s'\n", exp_word, pattern);
                 *p++ = SPECIAL_VAR_SYMBOL;
                 exp_word = p;
                 p = strchr(p, SPECIAL_VAR_SYMBOL);
                 *p = '\0';
                 repl = encode_then_expand_vararg(exp_word, /*handle_squotes:*/ 1, /*unbackslash:*/ 1);
                 debug_printf_varexp("repl:'%s'->'%s'\n", exp_word, repl);
                 /* HACK ALERT. We depend here on the fact that
                  * G.global_argv and results of utoa and get_local_var_value
                  * are actually in writable memory:
                  * replace_pattern momentarily stores NULs there. */
                 t = (char*)val;
                 to_be_freed = replace_pattern(t,
                         pattern,
                         (repl ? repl : exp_word),
                         exp_op);
                 if (to_be_freed) /* at least one replace happened */
                     val = to_be_freed;
                 free(pattern);
                 free(repl);
             } else {
                 /* Unset variable always gives nothing */
                 //  a=; echo ${a/*/w}      # "w"
                 //  unset a; echo ${a/*/w} # ""
                 /* Just skip "replace" part */
                 *p++ = SPECIAL_VAR_SYMBOL;
                 p = strchr(p, SPECIAL_VAR_SYMBOL);
                 *p = '\0';
             }
         }
 #endif /* BASH_PATTERN_SUBST */
         else if (exp_op == ':') {
 #if BASH_SUBSTR && ENABLE_FEATURE_SH_MATH
             /* It's ${var:N[:M]} bashism.
              * Note that in encoded form it has TWO parts:
              * var:N<SPECIAL_VAR_SYMBOL>M<SPECIAL_VAR_SYMBOL>
              */
             arith_t beg, len;
             unsigned vallen;
             const char *errmsg;
             beg = expand_and_evaluate_arith(exp_word, &errmsg);
             if (errmsg)
                 goto empty_result;
             debug_printf_varexp("beg:'%s'=%lld\n", exp_word, (long long)beg);
             *p++ = SPECIAL_VAR_SYMBOL;
             exp_word = p;
             p = strchr(p, SPECIAL_VAR_SYMBOL);
             *p = '\0';
             vallen = val ? strlen(val) : 0;
             if (beg < 0) {
                 /* negative beg counts from the end */
                 beg = (arith_t)vallen + beg;
             }
             /* If expansion will be empty, do not even evaluate len */
             if (!val || beg < 0 || beg > vallen) {
                 /* Why > vallen, not >=? bash:
                  * unset b; a=ab; : ${a:2:${b=3}}; echo $b  # "", b=3 (!!!)
                  * unset b; a=a; : ${a:2:${b=3}}; echo $b   # "", b not set
                  */
                 goto empty_result;
             }
             len = expand_and_evaluate_arith(exp_word, &errmsg);
             if (errmsg)
                 goto empty_result;
             debug_printf_varexp("len:'%s'=%lld\n", exp_word, (long long)len);
             debug_printf_varexp("from val:'%s'\n", val);
             if (len < 0) {
                 /* in bash, len=-n means strlen()-n */
                 len = (arith_t)vallen - beg + len;
                 if (len < 0) /* bash compat */
                     msg_and_die_if_script("%s: substring expression < 0", var);
             }
             if (len <= 0 || !val /*|| beg >= vallen*/) {
  empty_result:
                 val = NULL;
             } else {
                 /* Paranoia. What if user entered 9999999999999
                  * which fits in arith_t but not int? */
                 if (len > INT_MAX)
                     len = INT_MAX;
                 val = to_be_freed = xstrndup(val + beg, len);
             }
             debug_printf_varexp("val:'%s'\n", val);
 #else /* not (HUSH_SUBSTR_EXPANSION && FEATURE_SH_MATH) */
             msg_and_die_if_script("malformed ${%s:...}", var);
             val = NULL;
 #endif
         } else { /* one of "-=+?" */
             /* Standard-mandated substitution ops:
              * ${var?word} - indicate error if unset
              *      If var is unset, word (or a message indicating it is unset
              *      if word is null) is written to standard error
              *      and the shell exits with a non-zero exit status.
              *      Otherwise, the value of var is substituted.
              * ${var-word} - use default value
              *      If var is unset, word is substituted.
              * ${var=word} - assign and use default value
              *      If var is unset, word is assigned to var.
              *      In all cases, final value of var is substituted.
              * ${var+word} - use alternative value
              *      If var is unset, null is substituted.
              *      Otherwise, word is substituted.
              *
              * Word is subjected to tilde expansion, parameter expansion,
              * command substitution, and arithmetic expansion.
              * If word is not needed, it is not expanded.
              *
              * Colon forms (${var:-word}, ${var:=word} etc) do the same,
              * but also treat null var as if it is unset.
              *
              * Word-splitting and single quote behavior:
              *
              * $ f() { for i; do echo "|$i|"; done; }
              *
              * $ x=; f ${x:?'x y' z}; echo $?
              * bash: x: x y z       # neither f nor "echo $?" executes
              * (if interactive, bash does not exit, but merely aborts to prompt. $? is set to 1)
              * $ x=; f "${x:?'x y' z}"
              * bash: x: x y z       # dash prints: dash: x: 'x y' z
              *
              * $ x=; f ${x:='x y' z}
              * |x|
              * |y|
              * |z|
              * $ x=; f "${x:='x y' z}"
              * |'x y' z|
              *
              * $ x=x; f ${x:+'x y' z}
              * |x y|
              * |z|
              * $ x=x; f "${x:+'x y' z}"
              * |'x y' z|
              *
              * $ x=; f ${x:-'x y' z}
              * |x y|
              * |z|
              * $ x=; f "${x:-'x y' z}"
              * |'x y' z|
              */
             int use_word = (!val || ((exp_save == ':') && !val[0]));
             if (exp_op == '+')
                 use_word = !use_word;
             debug_printf_expand("expand: op:%c (null:%s) test:%i\n", exp_op,
                     (exp_save == ':') ? "true" : "false", use_word);
             if (use_word) {
                 if (exp_op == '+' || exp_op == '-') {
                     /* ${var+word} - use alternative value */
                     /* ${var-word} - use default value */
                     n = encode_then_append_var_plusminus(output, n, exp_word,
                             /*dquoted:*/ (arg0 & 0x80)
                     );
                     val = NULL;
                 } else {
                     /* ${var?word} - indicate error if unset */
                     /* ${var=word} - assign and use default value */
                     to_be_freed = encode_then_expand_vararg(exp_word,
                             /*handle_squotes:*/ !(arg0 & 0x80),
                             /*unbackslash:*/ 0
                     );
                     if (to_be_freed)
                         exp_word = to_be_freed;
                     if (exp_op == '?') {
                         /* mimic bash message */
                         msg_and_die_if_script("%s: %s",
                             var,
                             exp_word[0]
                             ? exp_word
                             : "parameter null or not set"
                             /* ash has more specific messages, a-la: */
                             /*: (exp_save == ':' ? "parameter null or not set" : "parameter not set")*/
                         );
 //TODO: how interactive bash aborts expansion mid-command?
 //It aborts the entire line, returns to prompt:
 // $ f() { for i; do echo "|$i|"; done; }; x=; f "${x:?'x y' z}"; echo YO
 // bash: x: x y z
 // $
 // ("echo YO" is not executed, neither the f function call)
                     } else {
                         val = exp_word;
                     }
                     if (exp_op == '=') {
                         /* ${var=[word]} or ${var:=[word]} */
                         if (isdigit(var[0]) || var[0] == '#') {
                             /* mimic bash message */
                             msg_and_die_if_script("$%s: cannot assign in this way", var);
                             val = NULL;
                         } else {
                             char *new_var = xasprintf("%s=%s", var, val);
                             set_local_var0(new_var);
                         }
                     }
                 }
             }
         } /* one of "-=+?" */
         *exp_saveptr = exp_save;
     } /* if (exp_op) */
     arg[0] = arg0;
     *pp = p;
     n = append_str_maybe_ifs_split(output, n, first_ch, val);
     free(to_be_freed);
     return n;
 }
References append_str_maybe_ifs_split(), arg0, BASH_SUBSTR, debug_printf_expand, debug_printf_varexp, encode_then_append_var_plusminus(), encode_then_expand_vararg, errmsg(), free, G, G_interactive_fd, G_x_mode, get_local_var_value(), INT_MAX, isdigit, MINUS_PLUS_EQUAL_QUESTION, msg_and_die_if_script, n, nn, NULL, NUMERIC_SPECVARS_STR, OPT_O_ERREXIT, output, p, pattern, pick_scan(), reinit_unicode_for_hush(), repl, scan_and_match(), SCAN_MATCH_LEFT_HALF, set_local_var0(), SPECIAL_VAR_SYMBOL, SPECIAL_VARS_STR, strchr(), strcspn(), strlen(), t, unicode_strlen(), utoa(), val, VAR_ENCODED_SUBST_OPS, xasprintf(), xatoi_positive(), xstrdup(), and xstrndup().
Referenced by expand_vars_to_list().
expand_string_to_string()
static char * expand_string_to_string (const char * str, int EXP_flags, int do_unbackslash) static
Definition at line 7230 of file hush.c.
 {
 #if !BASH_PATTERN_SUBST && !ENABLE_HUSH_CASE
     const int do_unbackslash = 1;
     const int EXP_flags = EXP_FLAG_ESC_GLOB_CHARS;
 #endif
     char *argv[2], **list;
     debug_printf_expand("string_to_string<='%s'\n", str);
     /* This is generally an optimization, but it also
      * handles "", which otherwise trips over !list[0] check below.
      * (is this ever happens that we actually get str="" here?)
      */
     if (!strchr(str, SPECIAL_VAR_SYMBOL) && !strchr(str, '\\')) {
         //TODO: Can use on strings with \ too, just unbackslash() them?
         debug_printf_expand("string_to_string(fast)=>'%s'\n", str);
         return xstrdup(str);
     }
     argv[0] = (char*)str;
     argv[1] = NULL;
     list = expand_variables(argv, EXP_flags | EXP_FLAG_SINGLEWORD);
     if (!list[0]) {
         /* Example where it happens:
          * x=; echo ${x:-"$@"}
          */
         ((char*)list)[0] = '\0';
     } else {
         if (HUSH_DEBUG)
             if (list[1])
                 bb_simple_error_msg_and_die("BUG in varexp2");
         /* actually, just move string 2*sizeof(char*) bytes back */
         overlapping_strcpy((char*)list, list[0]);
         if (do_unbackslash)
             unbackslash((char*)list);
     }
     debug_printf_expand("string_to_string=>'%s'\n", (char*)list);
     return (char*)list;
 }
References argv, bb_simple_error_msg_and_die(), debug_printf_expand, EXP_FLAG_ESC_GLOB_CHARS, EXP_FLAG_SINGLEWORD, expand_variables(), HUSH_DEBUG, list(), NULL, overlapping_strcpy(), SPECIAL_VAR_SYMBOL, str, strchr(), unbackslash(), and xstrdup().
expand_strvec_to_strvec()
static char** expand_strvec_to_strvec (char ** argv) static
Definition at line 7212 of file hush.c.
 {
     return expand_variables(argv, EXP_FLAG_GLOB | EXP_FLAG_ESC_GLOB_CHARS);
 }
References argv, EXP_FLAG_ESC_GLOB_CHARS, EXP_FLAG_GLOB, and expand_variables().
Referenced by pseudo_exec_argv(), run_list(), and run_pipe().
expand_variables()
static char** expand_variables (char ** argv, unsigned expflags) static
Definition at line 7182 of file hush.c.
 {
     int n;
     char **list;
     o_string output = NULL_O_STRING;
     output.o_expflags = expflags;
     n = 0;
     for (;;) {
         /* go to next list[n] */
         output.ended_in_ifs = 0;
         n = o_save_ptr(&output, n);
         if (!*argv)
             break;
         /* expand argv[i] */
         n = expand_vars_to_list(&output, n, *argv++);
         /* if (!output->has_empty_slot) -- need this?? */
             o_addchr(&output, '\0');
     }
     debug_print_list("expand_variables", &output, n);
     /* output.data (malloced in one block) gets returned in "list" */
     list = o_finalize_list(&output, n);
     debug_print_strings("expand_variables[1]", list);
     return list;
 }
References argv, debug_print_list, debug_print_strings, expand_vars_to_list(), list(), n, NULL_O_STRING, o_addchr(), o_finalize_list(), o_save_ptr(), and output.
Referenced by expand_string_to_string(), and expand_strvec_to_strvec().
expand_vars_to_list()
static NOINLINE int expand_vars_to_list (o_string * output, int n, char * arg) static
Definition at line 6996 of file hush.c.
 {
     /* output->o_expflags & EXP_FLAG_SINGLEWORD (0x80) if we are in
      * expansion of right-hand side of assignment == 1-element expand.
      */
     char cant_be_null = 0; /* only bit 0x80 matters */
     char *p;
     debug_printf_expand("expand_vars_to_list: arg:'%s' singleword:%x\n", arg,
             !!(output->o_expflags & EXP_FLAG_SINGLEWORD));
     debug_print_list("expand_vars_to_list[0]", output, n);
     while ((p = strchr(arg, SPECIAL_VAR_SYMBOL)) != NULL) {
         char first_ch;
 #if ENABLE_FEATURE_SH_MATH
         char arith_buf[sizeof(arith_t)*3 + 2];
 #endif
         if (output->ended_in_ifs) {
             o_addchr(output, '\0');
             n = o_save_ptr(output, n);
             output->ended_in_ifs = 0;
         }
         o_addblock(output, arg, p - arg);
         debug_print_list("expand_vars_to_list[1]", output, n);
         arg = ++p;
         p = strchr(p, SPECIAL_VAR_SYMBOL);
         /* Fetch special var name (if it is indeed one of them)
          * and quote bit, force the bit on if singleword expansion -
          * important for not getting v=$@ expand to many words. */
         first_ch = arg[0] | (output->o_expflags & EXP_FLAG_SINGLEWORD);
         /* Is this variable quoted and thus expansion can't be null?
          * "$@" is special. Even if quoted, it can still
          * expand to nothing (not even an empty string),
          * thus it is excluded. */
         if ((first_ch & 0x7f) != '@')
             cant_be_null |= first_ch;
         switch (first_ch & 0x7f) {
         /* Highest bit in first_ch indicates that var is double-quoted */
         case '*':
         case '@': {
             int i;
             if (!G.global_argv[1])
                 break;
             i = 1;
             cant_be_null |= first_ch; /* do it for "$@" _now_, when we know it's not empty */
             if (!(first_ch & 0x80)) { /* unquoted $* or $@ */
                 while (G.global_argv[i]) {
                     n = expand_on_ifs(output, n, G.global_argv[i]);
                     debug_printf_expand("expand_vars_to_list: argv %d (last %d)\n", i, G.global_argc - 1);
                     if (G.global_argv[i++][0] && G.global_argv[i]) {
                         /* this argv[] is not empty and not last:
                          * put terminating NUL, start new word */
                         o_addchr(output, '\0');
                         debug_print_list("expand_vars_to_list[2]", output, n);
                         n = o_save_ptr(output, n);
                         debug_print_list("expand_vars_to_list[3]", output, n);
                     }
                 }
             } else
             /* If EXP_FLAG_SINGLEWORD, we handle assignment 'a=....$@.....'
              * and in this case should treat it like '$*' - see 'else...' below */
             if (first_ch == (char)('@'|0x80)  /* quoted $@ */
              && !(output->o_expflags & EXP_FLAG_SINGLEWORD) /* not v="$@" case */
             ) {
                 while (1) {
                     o_addQstr(output, G.global_argv[i]);
                     if (++i >= G.global_argc)
                         break;
                     o_addchr(output, '\0');
                     debug_print_list("expand_vars_to_list[4]", output, n);
                     n = o_save_ptr(output, n);
                 }
             } else { /* quoted $* (or v="$@" case): add as one word */
                 while (1) {
                     o_addQstr(output, G.global_argv[i]);
                     if (!G.global_argv[++i])
                         break;
                     if (G.ifs[0])
                         o_addchr(output, G.ifs[0]);
                 }
                 output->has_quoted_part = 1;
             }
             break;
         }
         case SPECIAL_VAR_SYMBOL: {
             /* <SPECIAL_VAR_SYMBOL><SPECIAL_VAR_SYMBOL> */
             /* "Empty variable", used to make "" etc to not disappear */
             output->has_quoted_part = 1;
             cant_be_null = 0x80;
             arg++;
             break;
         }
         case SPECIAL_VAR_QUOTED_SVS:
             /* <SPECIAL_VAR_SYMBOL><SPECIAL_VAR_QUOTED_SVS><SPECIAL_VAR_SYMBOL> */
             /* "^C variable", represents literal ^C char (possible in scripts) */
             o_addchr(output, SPECIAL_VAR_SYMBOL);
             arg++;
             break;
 #if ENABLE_HUSH_TICK
         case '`': {
             /* <SPECIAL_VAR_SYMBOL>`cmd<SPECIAL_VAR_SYMBOL> */
             o_string subst_result = NULL_O_STRING;
             *p = '\0'; /* replace trailing <SPECIAL_VAR_SYMBOL> */
             arg++;
             /* Can't just stuff it into output o_string,
              * expanded result may need to be globbed
              * and $IFS-split */
             debug_printf_subst("SUBST '%s' first_ch %x\n", arg, first_ch);
             G.last_exitcode = process_command_subs(&subst_result, arg);
             G.expand_exitcode = G.last_exitcode;
             debug_printf_subst("SUBST RES:%d '%s'\n", G.last_exitcode, subst_result.data);
             n = append_str_maybe_ifs_split(output, n, first_ch, subst_result.data);
             o_free(&subst_result);
             break;
         }
 #endif
 #if ENABLE_FEATURE_SH_MATH
         case '+': {
             /* <SPECIAL_VAR_SYMBOL>+arith<SPECIAL_VAR_SYMBOL> */
             arith_t res;
             arg++; /* skip '+' */
             *p = '\0'; /* replace trailing <SPECIAL_VAR_SYMBOL> */
             debug_printf_subst("ARITH '%s' first_ch %x\n", arg, first_ch);
             res = expand_and_evaluate_arith(arg, NULL);
             debug_printf_subst("ARITH RES '"ARITH_FMT"'\n", res);
             sprintf(arith_buf, ARITH_FMT, res);
             if (res < 0
              && first_ch == (char)('+'|0x80)
             /* && (output->o_expflags & EXP_FLAG_ESC_GLOB_CHARS) */
             ) {
                 /* Quoted negative ariths, like filename[0"$((-9))"],
                  * should not be interpreted as glob ranges.
                  * Convert leading '-' to '\-':
                  */
                 o_grow_by(output, 1);
                 output->data[output->length++] = '\\';
             }
             o_addstr(output, arith_buf);
             break;
         }
 #endif
         default:
             /* <SPECIAL_VAR_SYMBOL>varname[ops]<SPECIAL_VAR_SYMBOL> */
             n = expand_one_var(output, n, first_ch, arg, &p);
             break;
         } /* switch (char after <SPECIAL_VAR_SYMBOL>) */
         /* Restore NULL'ed SPECIAL_VAR_SYMBOL.
          * Do the check to avoid writing to a const string. */
         if (*p != SPECIAL_VAR_SYMBOL)
             *p = SPECIAL_VAR_SYMBOL;
         arg = ++p;
     } /* end of "while (SPECIAL_VAR_SYMBOL is found) ..." */
     if (*arg) {
         /* handle trailing string */
         if (output->ended_in_ifs) {
             o_addchr(output, '\0');
             n = o_save_ptr(output, n);
         }
         debug_print_list("expand_vars_to_list[a]", output, n);
         /* this part is literal, and it was already pre-quoted
          * if needed (much earlier), do not use o_addQstr here!
          */
         o_addstr(output, arg);
         debug_print_list("expand_vars_to_list[b]", output, n);
     } else
     if (output->length == o_get_last_ptr(output, n) /* expansion is empty */
      && !(cant_be_null & 0x80)   /* and all vars were not quoted */
      && !output->has_quoted_part
     ) {
         n--;
         /* allow to reuse list[n] later without re-growth */
         output->has_empty_slot = 1;
     }
     return n;
 }
References append_str_maybe_ifs_split(), ARITH_FMT, o_string::data, debug_print_list, debug_printf_expand, debug_printf_subst, EXP_FLAG_SINGLEWORD, expand_on_ifs(), expand_one_var(), G, i, n, NULL, NULL_O_STRING, o_addblock(), o_addchr(), o_addQstr(), o_addstr(), o_free(), o_get_last_ptr(), o_grow_by(), o_save_ptr(), output, p, SPECIAL_VAR_QUOTED_SVS, SPECIAL_VAR_SYMBOL, sprintf(), and strchr().
Referenced by encode_then_append_var_plusminus(), and expand_variables().
fd_in_HFILEs()
static int fd_in_HFILEs (int fd) static
Definition at line 1742 of file hush.c.
 {
     HFILE *fl = G.HFILE_list;
     while (fl) {
         if (fl->fd == fd)
             return 1;
         fl = fl->next_hfile;
     }
     return 0;
 }
References fd, and G.
Referenced by internally_opened_fd().
fetch_heredocs()
static int fetch_heredocs (o_string * as_string, struct pipe * pi, int heredoc_cnt, struct in_str * input) static
Definition at line 4569 of file hush.c.
 {
     while (pi && heredoc_cnt) {
         int i;
         struct command *cmd = pi->cmds;
         debug_printf_heredoc("fetch_heredocs: num_cmds:%d cmd argv0:'%s'\n",
                 pi->num_cmds,
                 cmd->argv ? cmd->argv[0] : "NONE"
         );
         for (i = 0; i < pi->num_cmds; i++) {
             struct redir_struct *redir = cmd->redirects;
             debug_printf_heredoc("fetch_heredocs: %d cmd argv0:'%s'\n",
                     i, cmd->argv ? cmd->argv[0] : "NONE");
             while (redir) {
                 if (redir->rd_type == REDIRECT_HEREDOC) {
                     char *p;
                     redir->rd_type = REDIRECT_HEREDOC2;
                     /* redir->rd_dup is (ab)used to indicate <<- */
                     p = fetch_till_str(as_string, input,
                             redir->rd_filename, redir->rd_dup);
                     if (!p) {
                         syntax_error("unexpected EOF in here document");
                         return -1;
                     }
                     free(redir->rd_filename);
                     redir->rd_filename = p;
                     heredoc_cnt--;
                 }
                 redir = redir->next;
             }
             if (cmd->group) {
                 //bb_error_msg("%s:%u heredoc_cnt:%d", __func__, __LINE__, heredoc_cnt);
                 heredoc_cnt = fetch_heredocs(as_string, cmd->group, heredoc_cnt, input);
                 //bb_error_msg("%s:%u heredoc_cnt:%d", __func__, __LINE__, heredoc_cnt);
                 if (heredoc_cnt < 0)
                     return heredoc_cnt; /* error */
             }
             cmd++;
         }
         pi = pi->next;
     }
     return heredoc_cnt;
 }
References cmd, debug_printf_heredoc, fetch_till_str(), free, i, input, p, pi, redir, REDIRECT_HEREDOC, REDIRECT_HEREDOC2, and syntax_error.
Referenced by parse_stream().
fetch_till_str()
static char* fetch_till_str (o_string * as_string, struct in_str * input, const char * word, int heredoc_flags) static
Definition at line 4478 of file hush.c.
 {
     o_string heredoc = NULL_O_STRING;
     unsigned past_EOL;
     int prev = 0; /* not \ */
     int ch;
     /* Starting with "" is necessary for this case:
      * cat <<EOF
      *
      * xxx
      * EOF
      */
     heredoc.data = xzalloc(1); /* start as "", not as NULL */
     goto jump_in;
     while (1) {
         ch = i_getch(input);
         if (ch != EOF)
             nommu_addchr(as_string, ch);
         if (ch == '\n' || ch == EOF) {
  check_heredoc_end:
             if ((heredoc_flags & HEREDOC_QUOTED) || prev != '\\') {
                 /* End-of-line, and not a line continuation */
                 if (strcmp(heredoc.data + past_EOL, word) == 0) {
                     heredoc.data[past_EOL] = '\0';
                     debug_printf_heredoc("parsed '%s' heredoc '%s'\n", word, heredoc.data);
                     return heredoc.data;
                 }
                 if (ch == '\n') {
                     /* This is a new line.
                      * Remember position and backslash-escaping status.
                      */
                     o_addchr(&heredoc, ch);
                     prev = ch;
  jump_in:
                     past_EOL = heredoc.length;
                     /* Get 1st char of next line, possibly skipping leading tabs */
                     do {
                         ch = i_getch(input);
                         if (ch != EOF)
                             nommu_addchr(as_string, ch);
                     } while ((heredoc_flags & HEREDOC_SKIPTABS) && ch == '\t');
                     /* If this immediately ended the line,
                      * go back to end-of-line checks.
                      */
                     if (ch == '\n')
                         goto check_heredoc_end;
                 }
             } else {
                 /* Backslash-line continuation in an unquoted
                  * heredoc. This does not need special handling
                  * for heredoc body (unquoted heredocs are
                  * expanded on "execution" and that would take
                  * care of this case too), but not the case
                  * of line continuation *in terminator*:
                  *  cat <<EOF
                  *  Ok1
                  *  EO\
                  *  F
                  */
                 heredoc.data[--heredoc.length] = '\0';
                 prev = 0; /* not '\' */
                 continue;
             }
         }
         if (ch == EOF) {
             o_free(&heredoc);
             return NULL; /* error */
         }
         o_addchr(&heredoc, ch);
         nommu_addchr(as_string, ch);
         if (prev == '\\' && ch == '\\')
             /* Correctly handle foo\<eol> (not a line cont.) */
             prev = 0; /* not '\' */
         else
             prev = ch;
     }
 }
References debug_printf_heredoc, EOF, HEREDOC_QUOTED, HEREDOC_SKIPTABS, i_getch(), input, nommu_addchr(), NULL, NULL_O_STRING, o_addchr(), o_free(), strcmp, and xzalloc().
Referenced by fetch_heredocs().
fgetc_interactive()
static ALWAYS_INLINE int fgetc_interactive (struct in_str * i) static
Definition at line 2770 of file hush.c.
 {
     int ch;
     do ch = hfgetc(i->file); while (ch == '\0');
     return ch;
 }
References hfgetc(), and i.
Referenced by i_getch(), and i_peek().
find_builtin()
static const struct built_in_command* find_builtin (const char * name) static
Definition at line 8188 of file hush.c.
 {
     const struct built_in_command *x = find_builtin1(name);
     if (x)
         return x;
     return find_builtin_helper(name, bltins2, &bltins2[ARRAY_SIZE(bltins2)]);
 }
References ARRAY_SIZE, find_builtin1(), find_builtin_helper(), and x.
Referenced by hush_main(), pseudo_exec_argv(), and run_pipe().
find_builtin1()
static const struct built_in_command* find_builtin1 (const char * name) static
Definition at line 8184 of file hush.c.
 {
     return find_builtin_helper(name, bltins1, &bltins1[ARRAY_SIZE(bltins1)]);
 }
References ARRAY_SIZE, and find_builtin_helper().
Referenced by find_builtin(), and pseudo_exec_argv().
find_builtin_helper()
static const struct built_in_command* find_builtin_helper (const char * name, const struct built_in_command * x, const struct built_in_command * end) static
Definition at line 8170 of file hush.c.
 {
     while (x != end) {
         if (strcmp(name, x->b_cmd) != 0) {
             x++;
             continue;
         }
         debug_printf_exec("found builtin '%s'\n", name);
         return x;
     }
     return NULL;
 }
References debug_printf_exec, end, NULL, strcmp, and x.
Referenced by find_builtin(), and find_builtin1().
find_in_path()
static char* find_in_path (const char * arg) static
Definition at line 8137 of file hush.c.
 {
     char *ret = NULL;
     const char *PATH = get_local_var_value("PATH");
     if (!PATH)
         return NULL;
     while (1) {
         const char *end = strchrnul(PATH, ':');
         int sz = end - PATH; /* must be int! */
         free(ret);
         if (sz != 0) {
             ret = xasprintf("%.*s/%s", sz, PATH, arg);
         } else {
             /* We have xxx::yyyy in $PATH,
              * it means "use current dir" */
             ret = xstrdup(arg);
         }
         if (access(ret, F_OK) == 0)
             break;
         if (*end == '\0') {
             free(ret);
             return NULL;
         }
         PATH = end + 1;
     }
     return ret;
 }
References access(), end, F_OK, free, get_local_var_value(), NULL, strchrnul(), xasprintf(), and xstrdup().
Referenced by builtin_source().
first_special_char_in_vararg()
static const char* first_special_char_in_vararg (const char * cp) static
Definition at line 6222 of file hush.c.
 {
     for (;;) {
         if (!*cp) return NULL; /* string has no special chars */
         if (*cp == '$') return cp;
         if (*cp == '\\') return cp;
         if (*cp == '\'') return cp;
         if (*cp == '"') return cp;
 #if ENABLE_HUSH_TICK
         if (*cp == '`') return cp;
 #endif
         /* dquoted "${x:+ARG}" should not glob, therefore
          * '*' et al require some non-literal processing: */
         if (*cp == '*') return cp;
         if (*cp == '?') return cp;
         if (*cp == '[') return cp;
         cp++;
     }
 }
References NULL.
Referenced by encode_then_append_var_plusminus(), and encode_then_expand_vararg().
free_pipe()
static struct pipe* free_pipe (struct pipe * pi) static
Definition at line 3603 of file hush.c.
 {
     struct pipe *next;
     int i;
     debug_printf_clean("free_pipe (pid %d)\n", getpid());
     for (i = 0; i < pi->num_cmds; i++) {
         struct command *command;
         struct redir_struct *r, *rnext;
         command = &pi->cmds[i];
         debug_printf_clean("  command %d:\n", i);
         if (command->argv) {
             if (DEBUG_CLEAN) {
                 int a;
                 char **p;
                 for (a = 0, p = command->argv; *p; a++, p++) {
                     debug_printf_clean("   argv[%d] = %s\n", a, *p);
                 }
             }
             free_strings(command->argv);
             //command->argv = NULL;
         }
         /* not "else if": on syntax error, we may have both! */
         if (command->group) {
             debug_printf_clean("   begin group (cmd_type:%d)\n",
                     command->cmd_type);
             free_pipe_list(command->group);
             debug_printf_clean("   end group\n");
             //command->group = NULL;
         }
         /* else is crucial here.
          * If group != NULL, child_func is meaningless */
 #if ENABLE_HUSH_FUNCTIONS
         else if (command->child_func) {
             debug_printf_exec("cmd %p releases child func at %p\n", command, command->child_func);
             command->child_func->parent_cmd = NULL;
         }
 #endif
 #if !BB_MMU
         free(command->group_as_string);
         //command->group_as_string = NULL;
 #endif
         for (r = command->redirects; r; r = rnext) {
             debug_printf_clean("   redirect %d%s",
                     r->rd_fd, redir_table[r->rd_type].descrip);
             /* guard against the case >$FOO, where foo is unset or blank */
             if (r->rd_filename) {
                 debug_printf_clean(" fname:'%s'\n", r->rd_filename);
                 free(r->rd_filename);
                 //r->rd_filename = NULL;
             }
             debug_printf_clean(" rd_dup:%d\n", r->rd_dup);
             rnext = r->next;
             free(r);
         }
         //command->redirects = NULL;
     }
     free(pi->cmds);   /* children are an array, they get freed all at once */
     //pi->cmds = NULL;
 #if ENABLE_HUSH_JOB
     free(pi->cmdtext);
     //pi->cmdtext = NULL;
 #endif
     next = pi->next;
     free(pi);
     return next;
 }
References command::argv, command::cmd_type, DEBUG_CLEAN, debug_printf_clean, debug_printf_exec, free, free_pipe_list(), free_strings(), getpid(), command::group, command::group_as_string, i, redir_struct::next, next, NULL, p, pi, redir_struct::rd_dup, redir_struct::rd_fd, redir_struct::rd_filename, redir_struct::rd_type, and command::redirects.
Referenced by free_pipe_list().
free_pipe_list()
static void free_pipe_list (struct pipe * pi) static
Definition at line 3673 of file hush.c.
 {
     while (pi) {
 #if HAS_KEYWORDS
         debug_printf_clean("pipe reserved word %d\n", pi->res_word);
 #endif
         debug_printf_clean("pipe followup code %d\n", pi->followup);
         pi = free_pipe(pi);
     }
 }
References debug_printf_clean, free_pipe(), and pi.
Referenced by free_pipe(), parse_stream(), and run_and_free_list().
free_strings()
static void free_strings (char ** strings) static
Definition at line 1554 of file hush.c.
 {
     char **v;
     if (!strings)
         return;
     v = strings;
     while (*v) {
         free(*v);
         v++;
     }
     free(strings);
 }
References free, and strings.
Referenced by free_pipe(), and pseudo_exec_argv().
get_cwd()
static const char* get_cwd (int force) static
Definition at line 2219 of file hush.c.
 {
     if (force || G.cwd == NULL) {
         /* xrealloc_getcwd_or_warn(arg) calls free(arg),
          * we must not try to free(bb_msg_unknown) */
         if (G.cwd == bb_msg_unknown)
             G.cwd = NULL;
         G.cwd = xrealloc_getcwd_or_warn((char *)G.cwd);
         if (!G.cwd)
             G.cwd = bb_msg_unknown;
     }
     return G.cwd;
 }
References force, G, NULL, and xrealloc_getcwd_or_warn().
Referenced by builtin_pwd(), and set_pwd_var().
get_local_var_value()
static const char* FAST_FUNC get_local_var_value (const char * name) static
Definition at line 2251 of file hush.c.
 {
     struct variable **vpp;
     unsigned len = strlen(name);
     if (G.expanded_assignments) {
         char **cpp = G.expanded_assignments;
         while (*cpp) {
             char *cp = *cpp;
             if (strncmp(cp, name, len) == 0 && cp[len] == '=')
                 return cp + len + 1;
             cpp++;
         }
     }
     vpp = get_ptr_to_local_var(name, len);
     if (vpp)
         return (*vpp)->varstr + len + 1;
     if (strcmp(name, "PPID") == 0)
         return utoa(G.root_ppid);
     // bash compat: UID? EUID?
 #if ENABLE_HUSH_RANDOM_SUPPORT
     if (strcmp(name, "RANDOM") == 0)
         return utoa(next_random(&G.random_gen));
 #endif
 #if ENABLE_HUSH_LINENO_VAR
     if (strcmp(name, "LINENO") == 0)
         return utoa(G.execute_lineno);
 #endif
 #if BASH_EPOCH_VARS
     {
         const char *fmt = NULL;
         if (strcmp(name, "EPOCHSECONDS") == 0)
             fmt = "%llu";
         else if (strcmp(name, "EPOCHREALTIME") == 0)
             fmt = "%llu.%06u";
         if (fmt) {
             struct timeval tv;
             xgettimeofday(&tv);
             sprintf(G.epoch_buf, fmt, (unsigned long long)tv.tv_sec,
                     (unsigned)tv.tv_usec);
             return G.epoch_buf;
         }
     }
 #endif
     return NULL;
 }
References G, get_ptr_to_local_var(), if(), variable::name, next_random(), NULL, sprintf(), strcmp, strlen(), strncmp(), timeval::tv_sec, timeval::tv_usec, utoa(), and xgettimeofday().
Referenced by builtin_cd(), expand_one_var(), find_in_path(), hush_main(), reinit_unicode_for_hush(), and run_pipe().
get_ptr_to_local_var()
static struct variable** get_ptr_to_local_var (const char * name, unsigned len) static
Definition at line 2237 of file hush.c.
 {
     struct variable **pp;
     struct variable *cur;
     pp = &G.top_var;
     while ((cur = *pp) != NULL) {
         if (strncmp(cur->varstr, name, len) == 0 && cur->varstr[len] == '=')
             return pp;
         pp = &cur->next;
     }
     return NULL;
 }
References cur, G, variable::name, NULL, and strncmp().
Referenced by get_local_var_value(), and set_vars_and_save_old().
glob_needed()
static int glob_needed (const char * s) static
Definition at line 3491 of file hush.c.
 {
     while (*s) {
         if (*s == '\\') {
             if (!s[1])
                 return 0;
             s += 2;
             continue;
         }
         if (*s == '*' || *s == '[' || *s == '?')
             return 1;
         s++;
     }
     return 0;
 }
References s.
Referenced by perform_glob().
hfclose()
static void hfclose (HFILE * fp) static
Definition at line 1631 of file hush.c.
 {
     HFILE **pp = &G.HFILE_list;
     while (*pp) {
         HFILE *cur = *pp;
         if (cur == fp) {
             *pp = cur->next_hfile;
             break;
         }
         pp = &cur->next_hfile;
     }
     if (fp->fd >= 0)
         close(fp->fd);
     free(fp);
 }
References close(), cur, HFILE::fd, free, and G.
Referenced by builtin_source(), and hush_main().
hfgetc()
static ALWAYS_INLINE int hfgetc (HFILE * fp) static
Definition at line 1692 of file hush.c.
 {
     if (fp->cur < fp->end)
         return (unsigned char)(*fp->cur++);
     /* Buffer empty */
     return refill_HFILE_and_getc(fp);
 }
References HFILE::cur, HFILE::end, and refill_HFILE_and_getc().
Referenced by fgetc_interactive(), and i_peek2().
hfopen()
static HFILE* hfopen (const char * name) static
Definition at line 1608 of file hush.c.
 {
     HFILE *fp;
     int fd;
     fd = STDIN_FILENO;
     if (name) {
         fd = open(name, O_RDONLY | O_CLOEXEC);
         if (fd < 0)
             return NULL;
         if (O_CLOEXEC == 0) /* ancient libc */
             close_on_exec_on(fd);
     }
     fp = xmalloc(sizeof(*fp));
     if (name == NULL)
         G.HFILE_stdin = fp;
     fp->fd = fd;
     fp->cur = fp->end = fp->buf;
     fp->next_hfile = G.HFILE_list;
     G.HFILE_list = fp;
     return fp;
 }
References HFILE::buf, close_on_exec_on(), HFILE::cur, HFILE::end, fd, HFILE::fd, G, HFILE::next_hfile, NULL, O_CLOEXEC, O_RDONLY, open(), STDIN_FILENO, and xmalloc.
Referenced by builtin_source(), and hush_main().
hush_exit()
static void hush_exit (int exitcode) static
Definition at line 2075 of file hush.c.
 {
 #if ENABLE_FEATURE_EDITING_SAVE_ON_EXIT
     save_history(G.line_input_state); /* may be NULL */
 #endif
     fflush_all();
     if (G.exiting <= 0 && G_traps && G_traps[0] && G_traps[0][0]) {
         char *argv[3];
         /* argv[0] is unused */
         argv[1] = xstrdup(G_traps[0]); /* copy, since EXIT trap handler may modify G_traps[0] */
         argv[2] = NULL;
         G.exiting = 1; /* prevent EXIT trap recursion */
         /* Note: G_traps[0] is not cleared!
          * "trap" will still show it, if executed
          * in the handler */
         builtin_eval(argv);
     }
 #if ENABLE_FEATURE_CLEAN_UP
     {
         struct variable *cur_var;
         if (G.cwd != bb_msg_unknown)
             free((char*)G.cwd);
         cur_var = G.top_var;
         while (cur_var) {
             struct variable *tmp = cur_var;
             if (!cur_var->max_len)
                 free(cur_var->varstr);
             cur_var = cur_var->next;
             free(tmp);
         }
     }
 #endif
     fflush_all();
 #if ENABLE_HUSH_JOB
     sigexit(- (exitcode & 0xff));
 #else
     _exit(exitcode);
 #endif
 }
References _exit(), argv, builtin_eval(), exitcode, fflush_all(), free, G, G_traps, variable::max_len, variable::next, NULL, variable::varstr, and xstrdup().
Referenced by builtin_exit(), hush_main(), restore_ttypgrp_and__exit(), and run_list().
hush_main()
int hush_main (int argc, char ** argv)
Definition at line 10227 of file hush.c.
 {
     pid_t cached_getpid;
     enum {
         OPT_login = (1 << 0),
     };
     unsigned flags;
 #if !BB_MMU
     unsigned builtin_argc = 0;
 #endif
     char **e;
     struct variable *cur_var;
     struct variable *shell_ver;
     INIT_G();
     if (EXIT_SUCCESS != 0) /* if EXIT_SUCCESS == 0, it is already done */
         G.last_exitcode = EXIT_SUCCESS;
 #if ENABLE_HUSH_TRAP
 # if ENABLE_HUSH_FUNCTIONS
     G.return_exitcode = -1;
 # endif
     G.pre_trap_exitcode = -1;
 #endif
 #if ENABLE_HUSH_FAST
     G.count_SIGCHLD++; /* ensure it is != G.handled_SIGCHLD */
 #endif
 #if !BB_MMU
     G.argv0_for_re_execing = argv[0];
 #endif
     cached_getpid = getpid();   /* for tcsetpgrp() during init */
     G.root_pid = cached_getpid; /* for $PID  (NOMMU can override via -$HEXPID:HEXPPID:...) */
     G.root_ppid = getppid();    /* for $PPID (NOMMU can override) */
     /* Deal with HUSH_VERSION */
     debug_printf_env("unsetenv '%s'\n", "HUSH_VERSION");
     unsetenv("HUSH_VERSION"); /* in case it exists in initial env */
     shell_ver = xzalloc(sizeof(*shell_ver));
     shell_ver->flg_export = 1;
     shell_ver->flg_read_only = 1;
     /* Code which handles ${var<op>...} needs writable values for all variables,
      * therefore we xstrdup: */
     shell_ver->varstr = xstrdup(hush_version_str);
     /* Create shell local variables from the values
      * currently living in the environment */
     G.top_var = shell_ver;
     cur_var = G.top_var;
     e = environ;
     if (e) while (*e) {
         char *value = strchr(*e, '=');
         if (value) { /* paranoia */
             cur_var->next = xzalloc(sizeof(*cur_var));
             cur_var = cur_var->next;
             cur_var->varstr = *e;
             cur_var->max_len = strlen(*e);
             cur_var->flg_export = 1;
         }
         e++;
     }
     /* (Re)insert HUSH_VERSION into env (AFTER we scanned the env!) */
     debug_printf_env("putenv '%s'\n", shell_ver->varstr);
     putenv(shell_ver->varstr);
     /* Export PWD */
     set_pwd_var(SETFLAG_EXPORT);
 #if BASH_HOSTNAME_VAR
     /* Set (but not export) HOSTNAME unless already set */
     if (!get_local_var_value("HOSTNAME")) {
         struct utsname uts;
         uname(&uts);
         set_local_var_from_halves("HOSTNAME", uts.nodename);
     }
 #endif
     /* IFS is not inherited from the parent environment */
     set_local_var_from_halves("IFS", defifs);
     if (!get_local_var_value("PATH"))
         set_local_var_from_halves("PATH", bb_default_root_path);
     /* PS1/PS2 are set later, if we determine that we are interactive */
     /* bash also exports SHLVL and _,
      * and sets (but doesn't export) the following variables:
      * BASH=/bin/bash
      * BASH_VERSINFO=([0]="3" [1]="2" [2]="0" [3]="1" [4]="release" [5]="i386-pc-linux-gnu")
      * BASH_VERSION='3.2.0(1)-release'
      * HOSTTYPE=i386
      * MACHTYPE=i386-pc-linux-gnu
      * OSTYPE=linux-gnu
      * PPID=<NNNNN> - we also do it elsewhere
      * EUID=<NNNNN>
      * UID=<NNNNN>
      * GROUPS=()
      * LINES=<NNN>
      * COLUMNS=<NNN>
      * BASH_ARGC=()
      * BASH_ARGV=()
      * BASH_LINENO=()
      * BASH_SOURCE=()
      * DIRSTACK=()
      * PIPESTATUS=([0]="0")
      * HISTFILE=/<xxx>/.bash_history
      * HISTFILESIZE=500
      * HISTSIZE=500
      * MAILCHECK=60
      * PATH=/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
      * SHELL=/bin/bash
      * SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
      * TERM=dumb
      * OPTERR=1
      * OPTIND=1
      * PS4='+ '
      */
 #if NUM_SCRIPTS > 0
     if (argc < 0) {
         char *script = get_script_content(-argc - 1);
         G.global_argv = argv;
         G.global_argc = string_array_len(argv);
         //install_special_sighandlers(); - needed?
         parse_and_run_string(script);
         goto final_return;
     }
 #endif
     /* Initialize some more globals to non-zero values */
     die_func = restore_ttypgrp_and__exit;
     /* Shell is non-interactive at first. We need to call
      * install_special_sighandlers() if we are going to execute "sh <script>",
      * "sh -c <cmds>" or login shell's /etc/profile and friends.
      * If we later decide that we are interactive, we run install_special_sighandlers()
      * in order to intercept (more) signals.
      */
     /* Parse options */
     /* http://www.opengroup.org/onlinepubs/9699919799/utilities/sh.html */
     flags = (argv[0] && argv[0][0] == '-') ? OPT_login : 0;
     while (1) {
         int opt = getopt(argc, argv, "+" /* stop at 1st non-option */
                 "cexinsl"
 #if !BB_MMU
                 "<:$:R:V:"
 # if ENABLE_HUSH_FUNCTIONS
                 "F:"
 # endif
 #endif
         );
         if (opt <= 0)
             break;
         switch (opt) {
         case 'c':
             /* Note: -c is not an option with param!
              * "hush -c -l SCRIPT" is valid. "hush -cSCRIPT" is not.
              */
             G.opt_c = 1;
             break;
         case 'i':
             /* Well, we cannot just declare interactiveness,
              * we have to have some stuff (ctty, etc) */
             /* G_interactive_fd++; */
 //There are a few cases where bash -i -c 'SCRIPT'
 //has visible effect (differs from bash -c 'SCRIPT'):
 //it ignores TERM:
 //  bash -i -c 'kill $$; echo ALIVE'
 //  ALIVE
 //it resets SIG_IGNed HUP to SIG_DFL:
 //  trap '' hup; bash -i -c 'kill -hup $$; echo ALIVE'
 //  Hangup   [the message is not printed by bash, it's the shell which started it]
 //is talkative about jobs and exiting:
 //  bash -i -c 'sleep 1 & exit'
 //  [1] 16170
 //  exit
 //includes $ENV file (only if run as "sh"):
 //  echo last >/tmp/ENV; ENV=/tmp/ENV sh -i -c 'echo HERE'
 //  last: cannot open /var/log/wtmp: No such file or directory
 //  HERE
 //(under "bash", it's the opposite: it runs $BASH_ENV file only *without* -i).
 //
 //ash -i -c 'sleep 3; sleep 3', on ^C, drops into a prompt instead of exiting
 //(this may be a bug, bash does not do this).
 //(ash -i -c 'sleep 3' won't show this, the last command gets auto-"exec"ed)
 //
 //None of the above feel like useful features people would rely on.
             break;
         case 's':
             G.opt_s = 1;
             break;
         case 'l':
             flags |= OPT_login;
             break;
 #if !BB_MMU
         case '<': /* "big heredoc" support */
             full_write1_str(optarg);
             _exit(0);
         case '$': {
             unsigned long long empty_trap_mask;
             G.root_pid = bb_strtou(optarg, &optarg, 16);
             optarg++;
             G.root_ppid = bb_strtou(optarg, &optarg, 16);
             optarg++;
             G.last_bg_pid = bb_strtou(optarg, &optarg, 16);
             optarg++;
             G.last_exitcode = bb_strtou(optarg, &optarg, 16);
             optarg++;
             builtin_argc = bb_strtou(optarg, &optarg, 16);
             optarg++;
             empty_trap_mask = bb_strtoull(optarg, &optarg, 16);
             if (empty_trap_mask != 0) {
                 IF_HUSH_TRAP(int sig;)
                 install_special_sighandlers();
 # if ENABLE_HUSH_TRAP
                 G_traps = xzalloc(sizeof(G_traps[0]) * NSIG);
                 for (sig = 1; sig < NSIG; sig++) {
                     if (empty_trap_mask & (1LL << sig)) {
                         G_traps[sig] = xzalloc(1); /* == xstrdup(""); */
                         install_sighandler(sig, SIG_IGN);
                     }
                 }
 # endif
             }
 # if ENABLE_HUSH_LOOPS
             optarg++;
             G.depth_of_loop = bb_strtou(optarg, &optarg, 16);
 # endif
             /* Suppress "killed by signal" message, -$ hack is used
              * for subshells: echo `sh -c 'kill -9 $$'`
              * should be silent.
              */
             IF_HUSH_JOB(G.run_list_level = 1;)
 # if ENABLE_HUSH_FUNCTIONS
             /* nommu uses re-exec trick for "... | func | ...",
              * should allow "return".
              * This accidentally allows returns in subshells.
              */
             G_flag_return_in_progress = -1;
 # endif
             break;
         }
         case 'R':
         case 'V':
             set_local_var(xstrdup(optarg), opt == 'R' ? SETFLAG_MAKE_RO : 0);
             break;
 # if ENABLE_HUSH_FUNCTIONS
         case 'F': {
             struct function *funcp = new_function(optarg);
             /* funcp->name is already set to optarg */
             /* funcp->body is set to NULL. It's a special case. */
             funcp->body_as_string = argv[optind];
             optind++;
             break;
         }
 # endif
 #endif
         /*case '?': invalid option encountered (set_mode('?') will fail) */
         /*case 'n':*/
         /*case 'x':*/
         /*case 'e':*/
         default:
             if (set_mode(1, opt, NULL) == 0) /* no error */
                 break;
             bb_show_usage();
         }
     } /* option parsing loop */
     /* Skip options. Try "hush -l": $1 should not be "-l"! */
     G.global_argc = argc - (optind - 1);
     G.global_argv = argv + (optind - 1);
     G.global_argv[0] = argv[0];
     /* If we are login shell... */
     if (flags & OPT_login) {
         const char *hp = NULL;
         HFILE *input;
         debug_printf("sourcing /etc/profile\n");
         input = hfopen("/etc/profile");
  run_profile:
         if (input != NULL) {
             install_special_sighandlers();
             parse_and_run_file(input);
             hfclose(input);
         }
         /* bash: after sourcing /etc/profile,
          * tries to source (in the given order):
          * ~/.bash_profile, ~/.bash_login, ~/.profile,
          * stopping on first found. --noprofile turns this off.
          * bash also sources ~/.bash_logout on exit.
          * If called as sh, skips .bash_XXX files.
          */
         if (!hp) { /* unless we looped on the "goto" already */
             hp = get_local_var_value("HOME");
             if (hp && hp[0]) {
                 debug_printf("sourcing ~/.profile\n");
                 hp = concat_path_file(hp, ".profile");
                 input = hfopen(hp);
                 free((char*)hp);
                 goto run_profile;
             }
         }
     }
     /* -c takes effect *after* -l */
     if (G.opt_c) {
         /* Possibilities:
          * sh ... -c 'script'
          * sh ... -c 'script' ARG0 [ARG1...]
          * On NOMMU, if builtin_argc != 0,
          * sh ... -c 'builtin' BARGV... "" ARG0 [ARG1...]
          * "" needs to be replaced with NULL
          * and BARGV vector fed to builtin function.
          * Note: the form without ARG0 never happens:
          * sh ... -c 'builtin' BARGV... ""
          */
         char *script;
         install_special_sighandlers();
         G.global_argc--;
         G.global_argv++;
 #if !BB_MMU
         if (builtin_argc) {
             /* -c 'builtin' [BARGV...] "" ARG0 [ARG1...] */
             const struct built_in_command *x;
             x = find_builtin(G.global_argv[0]);
             if (x) { /* paranoia */
                 argv = G.global_argv;
                 G.global_argc -= builtin_argc + 1; /* skip [BARGV...] "" */
                 G.global_argv += builtin_argc + 1;
                 G.global_argv[-1] = NULL; /* replace "" */
                 G.last_exitcode = x->b_function(argv);
             }
             goto final_return;
         }
 #endif
         script = G.global_argv[0];
         if (!script)
             bb_error_msg_and_die(bb_msg_requires_arg, "-c");
         if (!G.global_argv[1]) {
             /* -c 'script' (no params): prevent empty $0 */
             G.global_argv[0] = argv[0];
         } else { /* else -c 'script' ARG0 [ARG1...]: $0 is ARG0 */
             G.global_argc--;
             G.global_argv++;
         }
         parse_and_run_string(script);
         goto final_return;
     }
     /* -s is: hush -s ARGV1 ARGV2 (no SCRIPT) */
     if (!G.opt_s && G.global_argv[1]) {
         HFILE *input;
         /*
          * "bash <script>" (which is never interactive (unless -i?))
          * sources $BASH_ENV here (without scanning $PATH).
          * If called as sh, does the same but with $ENV.
          * Also NB, per POSIX, $ENV should undergo parameter expansion.
          */
         G.global_argc--;
         G.global_argv++;
         debug_printf("running script '%s'\n", G.global_argv[0]);
         xfunc_error_retval = 127; /* for "hush /does/not/exist" case */
         input = hfopen(G.global_argv[0]);
         if (!input) {
             bb_simple_perror_msg_and_die(G.global_argv[0]);
         }
         xfunc_error_retval = 1;
         install_special_sighandlers();
         parse_and_run_file(input);
 #if ENABLE_FEATURE_CLEAN_UP
         hfclose(input);
 #endif
         goto final_return;
     }
     /* "implicit" -s: bare interactive hush shows 's' in $- */
     G.opt_s = 1;
     /* Up to here, shell was non-interactive. Now it may become one.
      * NB: don't forget to (re)run install_special_sighandlers() as needed.
      */
     /* A shell is interactive if the '-i' flag was given,
      * or if all of the following conditions are met:
      *    no -c command
      *    no arguments remaining or the -s flag given
      *    standard input is a terminal
      *    standard output is a terminal
      * Refer to Posix.2, the description of the 'sh' utility.
      */
 #if ENABLE_HUSH_JOB
     if (isatty(STDIN_FILENO) && isatty(STDOUT_FILENO)) {
         G_saved_tty_pgrp = tcgetpgrp(STDIN_FILENO);
         debug_printf("saved_tty_pgrp:%d\n", G_saved_tty_pgrp);
         if (G_saved_tty_pgrp < 0)
             G_saved_tty_pgrp = 0;
         /* try to dup stdin to high fd#, >= 255 */
         G_interactive_fd = dup_CLOEXEC(STDIN_FILENO, 254);
         if (G_interactive_fd < 0) {
             /* try to dup to any fd */
             G_interactive_fd = dup(STDIN_FILENO);
             if (G_interactive_fd < 0) {
                 /* give up */
                 G_interactive_fd = 0;
                 G_saved_tty_pgrp = 0;
             }
         }
     }
     debug_printf("interactive_fd:%d\n", G_interactive_fd);
     if (G_interactive_fd) {
         close_on_exec_on(G_interactive_fd);
         if (G_saved_tty_pgrp) {
             /* If we were run as 'hush &', sleep until we are
              * in the foreground (tty pgrp == our pgrp).
              * If we get started under a job aware app (like bash),
              * make sure we are now in charge so we don't fight over
              * who gets the foreground */
             while (1) {
                 pid_t shell_pgrp = getpgrp();
                 G_saved_tty_pgrp = tcgetpgrp(G_interactive_fd);
                 if (G_saved_tty_pgrp == shell_pgrp)
                     break;
                 /* send TTIN to ourself (should stop us) */
                 kill(- shell_pgrp, SIGTTIN);
             }
         }
         /* Install more signal handlers */
         install_special_sighandlers();
         if (G_saved_tty_pgrp) {
             /* Set other signals to restore saved_tty_pgrp */
             install_fatal_sighandlers();
             /* Put ourselves in our own process group
              * (bash, too, does this only if ctty is available) */
             bb_setpgrp(); /* is the same as setpgid(our_pid, our_pid); */
             /* Grab control of the terminal */
             tcsetpgrp(G_interactive_fd, cached_getpid);
         }
         enable_restore_tty_pgrp_on_exit();
 # if ENABLE_FEATURE_EDITING
         G.line_input_state = new_line_input_t(FOR_SHELL);
 #  if ENABLE_FEATURE_TAB_COMPLETION
         G.line_input_state->get_exe_name = get_builtin_name;
 #  endif
 #  if EDITING_HAS_sh_get_var
         G.line_input_state->sh_get_var = get_local_var_value;
 #  endif
 # endif
 # if ENABLE_HUSH_SAVEHISTORY && MAX_HISTORY > 0
         {
             const char *hp = get_local_var_value("HISTFILE");
             if (!hp) {
                 hp = get_local_var_value("HOME");
                 if (hp)
                     hp = concat_path_file(hp, ".hush_history");
             } else {
                 hp = xstrdup(hp);
             }
             if (hp) {
                 G.line_input_state->hist_file = hp;
                 //set_local_var(xasprintf("HISTFILE=%s", ...));
             }
 #  if ENABLE_FEATURE_SH_HISTFILESIZE
             hp = get_local_var_value("HISTFILESIZE");
             G.line_input_state->max_history = size_from_HISTFILESIZE(hp);
 #  endif
         }
 # endif
     } else {
         install_special_sighandlers();
     }
 #elif ENABLE_HUSH_INTERACTIVE
     /* No job control compiled in, only prompt/line editing */
     if (isatty(STDIN_FILENO) && isatty(STDOUT_FILENO)) {
         G_interactive_fd = dup_CLOEXEC(STDIN_FILENO, 254);
         if (G_interactive_fd < 0) {
             /* try to dup to any fd */
             G_interactive_fd = dup_CLOEXEC(STDIN_FILENO, -1);
             if (G_interactive_fd < 0)
                 /* give up */
                 G_interactive_fd = 0;
         }
     }
     if (G_interactive_fd) {
         close_on_exec_on(G_interactive_fd);
     }
     install_special_sighandlers();
 #else
     /* We have interactiveness code disabled */
     install_special_sighandlers();
 #endif
     /* bash:
      * if interactive but not a login shell, sources ~/.bashrc
      * (--norc turns this off, --rcfile <file> overrides)
      */
     if (G_interactive_fd) {
 #if ENABLE_HUSH_INTERACTIVE && ENABLE_FEATURE_EDITING_FANCY_PROMPT
         /* Set (but not export) PS1/2 unless already set */
         if (!get_local_var_value("PS1"))
             set_local_var_from_halves("PS1", "\\w \\$ ");
         if (!get_local_var_value("PS2"))
             set_local_var_from_halves("PS2", "> ");
 #endif
         if (!ENABLE_FEATURE_SH_EXTRA_QUIET) {
             /* note: ash and hush share this string */
             printf("\n\n%s %s\n"
                 IF_HUSH_HELP("Enter 'help' for a list of built-in commands.\n")
                 "\n",
                 bb_banner,
                 "hush - the humble shell"
             );
         }
     }
     parse_and_run_file(hfopen(NULL)); /* stdin */
  final_return:
     hush_exit(G.last_exitcode);
 }
References _exit(), argc, argv, bb_default_root_path, bb_error_msg_and_die(), BB_MMU, bb_setpgrp, bb_show_usage(), bb_simple_perror_msg_and_die(), bb_strtou(), bb_strtoull(), close_on_exec_on(), concat_path_file(), debug_printf, debug_printf_env, defifs, die_func, dup(), dup_CLOEXEC(), enable_restore_tty_pgrp_on_exit, environ, EXIT_SUCCESS, find_builtin(), flags, variable::flg_export, variable::flg_read_only, free, full_write1_str(), G, G_flag_return_in_progress, G_interactive_fd, G_saved_tty_pgrp, G_traps, get_local_var_value(), get_script_content(), getopt(), getpgrp(), getpid(), getppid(), hfclose(), hfopen(), hush_exit(), INIT_G, input, install_sighandler(), install_special_sighandlers(), isatty(), kill(), variable::max_len, variable::next, utsname::nodename, NSIG, NULL, opt, optarg, optind, parse_and_run_file(), parse_and_run_string(), printf(), putenv(), restore_ttypgrp_and__exit(), set_local_var(), set_local_var_from_halves(), set_mode(), set_pwd_var(), SETFLAG_EXPORT, SETFLAG_MAKE_RO, shell_pgrp, SIG_IGN, SIGTTIN, STDIN_FILENO, STDOUT_FILENO, strchr(), string_array_len(), strlen(), tcgetpgrp(), tcsetpgrp, uname(), unsetenv(), value, variable::varstr, x, xfunc_error_retval, xstrdup(), and xzalloc().
i_getch()
static int i_getch (struct in_str * i) static
Definition at line 2778 of file hush.c.
 {
     int ch;
     if (!i->file) {
         /* string-based in_str */
         ch = (unsigned char)*i->p;
         if (ch != '\0') {
             i->p++;
             i->last_char = ch;
 #if ENABLE_HUSH_LINENO_VAR
             if (ch == '\n') {
                 G.parse_lineno++;
                 debug_printf_parse("G.parse_lineno++ = %u\n", G.parse_lineno);
             }
 #endif
             return ch;
         }
         return EOF;
     }
     /* FILE-based in_str */
 #if ENABLE_FEATURE_EDITING
     /* This can be stdin, check line editing char[] buffer */
     if (i->p && *i->p != '\0') {
         ch = (unsigned char)*i->p++;
         goto out;
     }
 #endif
     /* peek_buf[] is an int array, not char. Can contain EOF. */
     ch = i->peek_buf[0];
     if (ch != 0) {
         int ch2 = i->peek_buf[1];
         i->peek_buf[0] = ch2;
         if (ch2 == 0) /* very likely, avoid redundant write */
             goto out;
         i->peek_buf[1] = 0;
         goto out;
     }
     ch = fgetc_interactive(i);
  out:
     debug_printf("file_get: got '%c' %d\n", ch, ch);
     i->last_char = ch;
 #if ENABLE_HUSH_LINENO_VAR
     if (ch == '\n') {
         G.parse_lineno++;
         debug_printf_parse("G.parse_lineno++ = %u\n", G.parse_lineno);
     }
 #endif
     return ch;
 }
References debug_printf, debug_printf_parse, EOF, fgetc_interactive(), G, i, if(), and out().
Referenced by add_till_backquote(), add_till_closing_bracket(), add_till_double_quote(), add_till_single_quote(), add_till_single_quote_dquoted(), encode_string(), encode_then_append_var_plusminus(), encode_then_expand_vararg(), fetch_till_str(), i_getch_and_eat_bkslash_nl(), i_peek_and_eat_bkslash_nl(), parse_and_run_stream(), parse_dollar(), parse_group(), parse_redir_right_fd(), parse_redirect(), and parse_stream().
i_getch_and_eat_bkslash_nl()
static int i_getch_and_eat_bkslash_nl (struct in_str * input) static
Definition at line 2902 of file hush.c.
 {
     for (;;) {
         int ch, ch2;
         ch = i_getch(input);
         if (ch != '\\')
             return ch;
         ch2 = i_peek(input);
         if (ch2 != '\n')
             return ch;
         /* backslash+newline, skip it */
         i_getch(input);
     }
 }
References i_getch(), i_peek(), and input.
Referenced by parse_dollar().
i_peek()
static int i_peek (struct in_str * i) static
Definition at line 2832 of file hush.c.
 {
     int ch;
     if (!i->file) {
         /* string-based in_str */
         /* Doesn't report EOF on NUL. None of the callers care. */
         return (unsigned char)*i->p;
     }
     /* FILE-based in_str */
 #if ENABLE_FEATURE_EDITING && ENABLE_HUSH_INTERACTIVE
     /* This can be stdin, check line editing char[] buffer */
     if (i->p && *i->p != '\0')
         return (unsigned char)*i->p;
 #endif
     /* peek_buf[] is an int array, not char. Can contain EOF. */
     ch = i->peek_buf[0];
     if (ch != 0)
         return ch;
     /* Need to get a new char */
     ch = fgetc_interactive(i);
     debug_printf("file_peek: got '%c' %d\n", ch, ch);
     /* Save it by either rolling back line editing buffer, or in i->peek_buf[0] */
 #if ENABLE_FEATURE_EDITING && ENABLE_HUSH_INTERACTIVE
     if (i->p) {
         i->p -= 1;
         return ch;
     }
 #endif
     i->peek_buf[0] = ch;
     /*i->peek_buf[1] = 0; - already is */
     return ch;
 }
References debug_printf, fgetc_interactive(), and i.
Referenced by encode_string(), i_getch_and_eat_bkslash_nl(), i_peek_and_eat_bkslash_nl(), parse_dollar(), parse_group(), parse_redir_right_fd(), parse_redirect(), and parse_stream().
i_peek2()
static int i_peek2 (struct in_str * i) static
Definition at line 2874 of file hush.c.
 {
     int ch;
     /* There are two cases when i->p[] buffer exists.
      * (1) it's a string in_str.
      * (2) It's a file, and we have a saved line editing buffer.
      * In both cases, we know that i->p[0] exists and not NUL, and
      * the peek2 result is in i->p[1].
      */
     if (i->p)
         return (unsigned char)i->p[1];
     /* Now we know it is a file-based in_str. */
     /* peek_buf[] is an int array, not char. Can contain EOF. */
     /* Is there 2nd char? */
     ch = i->peek_buf[1];
     if (ch == 0) {
         /* We did not read it yet, get it now */
         do ch = hfgetc(i->file); while (ch == '\0');
         i->peek_buf[1] = ch;
     }
     debug_printf("file_peek2: got '%c' %d\n", ch, ch);
     return ch;
 }
References debug_printf, hfgetc(), and i.
Referenced by i_peek_and_eat_bkslash_nl().
i_peek_and_eat_bkslash_nl()
static int i_peek_and_eat_bkslash_nl (struct in_str * input) static
Definition at line 2921 of file hush.c.
 {
     for (;;) {
         int ch, ch2;
         ch = i_peek(input);
         if (ch != '\\')
             return ch;
         ch2 = i_peek2(input);
         if (ch2 != '\n')
             return ch;
         /* backslash+newline, skip it */
         i_getch(input);
         i_getch(input);
     }
 }
References i_getch(), i_peek(), i_peek2(), and input.
Referenced by add_till_closing_bracket(), parse_dollar(), parse_redirect(), and parse_stream().
initialize_context()
static void initialize_context (struct parse_context * ctx) static
Definition at line 3943 of file hush.c.
 {
     memset(ctx, 0, sizeof(*ctx));
     if (MAYBE_ASSIGNMENT != 0)
         ctx->is_assignment = MAYBE_ASSIGNMENT;
     ctx->pipe = ctx->list_head = new_pipe();
     /* Create the memory for command, roughly:
      * ctx->pipe->cmds = new struct command;
      * ctx->command = &ctx->pipe->cmds[0];
      */
     done_command(ctx);
 }
References done_command(), MAYBE_ASSIGNMENT, memset(), and new_pipe().
Referenced by parse_stream().
install_sighandler()
static sighandler_t install_sighandler (int sig, sighandler_t handler) static
Definition at line 1959 of file hush.c.
 {
     struct sigaction old_sa;
     /* We could use signal() to install handlers... almost:
      * except that we need to mask ALL signals while handlers run.
      * I saw signal nesting in strace, race window isn't small.
      * SA_RESTART is also needed, but in Linux, signal()
      * sets SA_RESTART too.
      */
     /* memset(&G.sa, 0, sizeof(G.sa)); - already done */
     /* sigfillset(&G.sa.sa_mask);      - already done */
     /* G.sa.sa_flags = SA_RESTART;     - already done */
     G.sa.sa_handler = handler;
     sigaction(sig, &G.sa, &old_sa);
     return old_sa.sa_handler;
 }
References G, and handler().
Referenced by hush_main(), install_sighandlers(), and switch_off_special_sigs().
install_sighandlers()
static void install_sighandlers (unsigned mask) static
Definition at line 10091 of file hush.c.
 {
     sighandler_t old_handler;
     unsigned sig = 0;
     while ((mask >>= 1) != 0) {
         sig++;
         if (!(mask & 1))
             continue;
         old_handler = install_sighandler(sig, pick_sighandler(sig));
         /* POSIX allows shell to re-enable SIGCHLD
          * even if it was SIG_IGN on entry.
          * Therefore we skip IGN check for it:
          */
         if (sig == SIGCHLD)
             continue;
         /* Interactive bash re-enables SIGHUP which is SIG_IGNed on entry.
          * Try:
          * trap '' hup; bash; echo RET  # type "kill -hup $$", see SIGHUP having effect
          * trap '' hup; bash -c 'kill -hup $$; echo ALIVE'  # here SIGHUP is SIG_IGNed
          */
         if (sig == SIGHUP && G_interactive_fd)
             continue;
         /* Unless one of the above signals, is it SIG_IGN? */
         if (old_handler == SIG_IGN) {
             /* oops... restore back to IGN, and record this fact */
             install_sighandler(sig, old_handler);
 #if ENABLE_HUSH_TRAP
             if (!G_traps)
                 G_traps = xzalloc(sizeof(G_traps[0]) * NSIG);
             free(G_traps[sig]);
             G_traps[sig] = xzalloc(1); /* == xstrdup(""); */
 #endif
         }
     }
 }
References free, G_interactive_fd, G_traps, install_sighandler(), NSIG, pick_sighandler(), SIG_IGN, SIGCHLD, SIGHUP, and xzalloc().
Referenced by install_special_sighandlers().
install_special_sighandlers()
static void install_special_sighandlers (void) static
Definition at line 10128 of file hush.c.
 {
     unsigned mask;
     /* Which signals are shell-special? */
     mask = (1 << SIGQUIT) | (1 << SIGCHLD);
     if (G_interactive_fd) {
         mask |= SPECIAL_INTERACTIVE_SIGS;
         if (G_saved_tty_pgrp) /* we have ctty, job control sigs work */
             mask |= SPECIAL_JOBSTOP_SIGS;
     }
     /* Careful, do not re-install handlers we already installed */
     if (G.special_sig_mask != mask) {
         unsigned diff = mask & ~G.special_sig_mask;
         G.special_sig_mask = mask;
         install_sighandlers(diff);
     }
 }
References diff(), G, G_interactive_fd, G_saved_tty_pgrp, install_sighandlers(), SIGCHLD, SIGQUIT, SPECIAL_INTERACTIVE_SIGS, and SPECIAL_JOBSTOP_SIGS.
Referenced by hush_main().
internally_opened_fd()
static int internally_opened_fd (int fd, struct squirrel * sq) static
Definition at line 8020 of file hush.c.
 {
     int i;
 #if ENABLE_HUSH_INTERACTIVE
     if (fd == G_interactive_fd)
         return 1;
 #endif
     /* If this one of script's fds? */
     if (fd_in_HFILEs(fd))
         return 1;
     if (sq) for (i = 0; sq[i].orig_fd >= 0; i++) {
         if (fd == sq[i].moved_to)
             return 1;
     }
     return 0;
 }
References fd, fd_in_HFILEs(), G_interactive_fd, i, squirrel::moved_to, and sq().
Referenced by setup_redirects().
job_exited_or_stopped()
static int job_exited_or_stopped (struct pipe * pi) static
Definition at line 8902 of file hush.c.
 {
     int rcode, i;
     if (pi->alive_cmds != pi->stopped_cmds)
         return -1;
     /* All processes in fg pipe have exited or stopped */
     rcode = 0;
     i = pi->num_cmds;
     while (--i >= 0) {
         rcode = pi->cmds[i].cmd_exitcode;
         /* usually last process gives overall exitstatus,
          * but with "set -o pipefail", last *failed* process does */
         if (G.o_opt[OPT_O_PIPEFAIL] == 0 || rcode != 0)
             break;
     }
     IF_HAS_KEYWORDS(if (pi->pi_inverted) rcode = !rcode;)
     return rcode;
 }
References G, i, IF_HAS_KEYWORDS, OPT_O_PIPEFAIL, and pi.
Referenced by process_wait_result().
leave_var_nest_level()
static void leave_var_nest_level (void) static
Definition at line 8252 of file hush.c.
 {
     G.var_nest_level--;
     debug_printf_env("var_nest_level-- %u\n", G.var_nest_level);
     if (HUSH_DEBUG && (int)G.var_nest_level < 0)
         bb_simple_error_msg_and_die("BUG: nesting underflow");
     remove_nested_vars();
 }
References bb_simple_error_msg_and_die(), debug_printf_env, G, HUSH_DEBUG, and remove_nested_vars().
Referenced by run_pipe().
move_HFILEs_on_redirect()
static int move_HFILEs_on_redirect (int fd, int avoid_fd) static
Definition at line 1699 of file hush.c.
 {
     HFILE *fl = G.HFILE_list;
     while (fl) {
         if (fd == fl->fd) {
             /* We use it only on script files, they are all CLOEXEC */
             fl->fd = xdup_CLOEXEC_and_close(fd, avoid_fd);
             debug_printf_redir("redirect_fd %d: matches a script fd, moving it to %d\n", fd, fl->fd);
             return 1; /* "found and moved" */
         }
         fl = fl->next_hfile;
     }
 #if ENABLE_HUSH_MODE_X
     if (G.x_mode_fd > 0 && fd == G.x_mode_fd) {
         G.x_mode_fd = xdup_CLOEXEC_and_close(fd, avoid_fd);
         return 1; /* "found and moved" */
     }
 #endif
     return 0; /* "not in the list" */
 }
References debug_printf_redir, fd, G, and xdup_CLOEXEC_and_close().
Referenced by save_fd_on_redirect().
msg_and_die_if_script()
static void msg_and_die_if_script (unsigned lineno, const char * fmt, ...) static
Definition at line 1400 of file hush.c.
 {
     va_list p;
 #if HUSH_DEBUG >= 2
     bb_error_msg("hush.c:%u", lineno);
 #endif
     va_start(p, fmt);
     bb_verror_msg(fmt, p, NULL);
     va_end(p);
     die_if_script();
 }
References bb_error_msg(), bb_verror_msg(), die_if_script(), lineno, NULL, p, va_end, and va_start.
new_pipe()
static struct pipe* new_pipe (void) static
Definition at line 3786 of file hush.c.
 {
     struct pipe *pi;
     pi = xzalloc(sizeof(struct pipe));
     /*pi->res_word = RES_NONE; - RES_NONE is 0 anyway */
     return pi;
 }
References pi, and xzalloc().
Referenced by done_pipe(), initialize_context(), and parse_group().
nommu_addchr()
static void nommu_addchr (o_string * o, int ch) static
Definition at line 3027 of file hush.c.
 {
     if (o)
         o_addchr(o, ch);
 }
References o_addchr().
Referenced by encode_string(), fetch_till_str(), parse_dollar(), parse_group(), parse_redir_right_fd(), parse_redirect(), and parse_stream().
o_addblock()
static void o_addblock (o_string * o, const char * str, int len) static
Definition at line 3009 of file hush.c.
 {
     o_grow_by(o, len);
     ((char*)mempcpy(&o->data[o->length], str, len))[0] = '\0';
     o->length += len;
 }
References o_string::data, o_string::length, mempcpy(), o_grow_by(), and str.
Referenced by expand_on_ifs(), expand_vars_to_list(), o_addqblock(), o_addQblock(), o_addstr(), and o_addstr_with_NUL().
o_addblock_duplicate_backslash()
static void o_addblock_duplicate_backslash (o_string * o, const char * str, int len) static
Definition at line 6074 of file hush.c.
 {
     while (--len >= 0) {
         char c = *str++;
 #if ENABLE_HUSH_BRACE_EXPANSION
         if (c == '{' || c == '}') {
             /* { -> \{, } -> \} */
             o_addchr(o, '\\');
             /* And now we want to add { or } and continue:
              *  o_addchr(o, c);
              *  continue;
              * luckily, just falling through achieves this.
              */
         }
 #endif
         o_addchr(o, c);
         if (c == '\\') {
             /* \z -> \\\z; <eol> -> \<eol> */
             o_addchr(o, '\\');
             if (len) {
                 len--;
                 o_addchr(o, '\\');
                 o_addchr(o, *str++);
             }
         }
     }
 }
References c, o_addchr(), and str.
Referenced by expand_on_ifs().
o_addchr()
static void o_addchr (o_string * o, int ch) static
Definition at line 2985 of file hush.c.
 {
     debug_printf("o_addchr: '%c' o->length=%d o=%p\n", ch, o->length, o);
     if (o->length < o->maxlen) {
         /* likely. avoid o_grow_by() call */
  add:
         o->data[o->length] = ch;
         o->length++;
         o->data[o->length] = '\0';
         return;
     }
     o_grow_by(o, 1);
     goto add;
 }
References add(), o_string::data, debug_printf, o_string::length, o_string::maxlen, and o_grow_by().
Referenced by add_till_backquote(), add_till_closing_bracket(), add_till_double_quote(), add_till_single_quote(), encode_string(), encode_then_append_var_plusminus(), encode_then_expand_vararg(), expand_on_ifs(), expand_variables(), expand_vars_to_list(), fetch_till_str(), nommu_addchr(), o_addblock_duplicate_backslash(), parse_dollar(), and parse_stream().
o_addqblock()
static void o_addqblock (o_string * o, const char * str, int len) static
Definition at line 3122 of file hush.c.
 {
     while (len) {
         char ch;
         int sz;
         int ordinary_cnt = strcspn(str, "*?[-\\" MAYBE_BRACES);
         if (ordinary_cnt > len) /* paranoia */
             ordinary_cnt = len;
         o_addblock(o, str, ordinary_cnt);
         if (ordinary_cnt == len)
             return; /* NUL is already added by o_addblock */
         str += ordinary_cnt;
         len -= ordinary_cnt + 1; /* we are processing + 1 char below */
         ch = *str++;
         sz = 1;
         if (ch) { /* it is necessarily one of "*?[-\\" MAYBE_BRACES */
             sz++;
             o->data[o->length] = '\\';
             o->length++;
         }
         o_grow_by(o, sz);
         o->data[o->length] = ch;
         o->length++;
     }
     o->data[o->length] = '\0';
 }
References o_string::data, o_string::length, MAYBE_BRACES, o_addblock(), o_grow_by(), str, and strcspn().
Referenced by o_addQblock().
o_addQblock()
static void o_addQblock (o_string * o, const char * str, int len) static
Definition at line 3150 of file hush.c.
 {
     if (!(o->o_expflags & EXP_FLAG_ESC_GLOB_CHARS)) {
         o_addblock(o, str, len);
         return;
     }
     o_addqblock(o, str, len);
 }
References EXP_FLAG_ESC_GLOB_CHARS, o_addblock(), o_addqblock(), o_string::o_expflags, and str.
Referenced by o_addQstr().
o_addqchr()
static void o_addqchr (o_string * o, int ch) static
Definition at line 3087 of file hush.c.
 {
     int sz = 1;
     /* '-' is included because of this case:
      * >filename0 >filename1 >filename9; v='-'; echo filename[0"$v"9]
      */
     char *found = strchr("*?[-\\" MAYBE_BRACES, ch);
     if (found)
         sz++;
     o_grow_by(o, sz);
     if (found) {
         o->data[o->length] = '\\';
         o->length++;
     }
     o->data[o->length] = ch;
     o->length++;
     o->data[o->length] = '\0';
 }
References o_string::data, found, o_string::length, MAYBE_BRACES, o_grow_by(), and strchr().
Referenced by add_till_single_quote_dquoted(), encode_string(), encode_then_append_var_plusminus(), encode_then_expand_vararg(), and parse_stream().
o_addQchr()
static void o_addQchr (o_string * o, int ch) static
Definition at line 3106 of file hush.c.
 {
     int sz = 1;
     if ((o->o_expflags & EXP_FLAG_ESC_GLOB_CHARS)
      && strchr("*?[-\\" MAYBE_BRACES, ch)
     ) {
         sz++;
         o->data[o->length] = '\\';
         o->length++;
     }
     o_grow_by(o, sz);
     o->data[o->length] = ch;
     o->length++;
     o->data[o->length] = '\0';
 }
References o_string::data, EXP_FLAG_ESC_GLOB_CHARS, o_string::length, MAYBE_BRACES, o_string::o_expflags, o_grow_by(), and strchr().
Referenced by encode_string(), encode_then_append_var_plusminus(), encode_then_expand_vararg(), parse_dollar(), and parse_stream().
o_addQstr()
static void o_addQstr (o_string * o, const char * str) static
Definition at line 3159 of file hush.c.
 {
     o_addQblock(o, str, strlen(str));
 }
References o_addQblock(), str, and strlen().
Referenced by append_str_maybe_ifs_split(), and expand_vars_to_list().
o_addstr()
static void o_addstr (o_string * o, const char * str) static
Definition at line 3016 of file hush.c.
 {
     o_addblock(o, str, strlen(str));
 }
References o_addblock(), str, and strlen().
Referenced by expand_vars_to_list(), parse_dollar(), parse_group(), and parse_stream().
o_addstr_with_NUL()
static void o_addstr_with_NUL (o_string * o, const char * str) static
Definition at line 3021 of file hush.c.
 {
     o_addblock(o, str, strlen(str) + 1);
 }
References o_addblock(), str, and strlen().
Referenced by perform_glob().
o_finalize_list()
static char** o_finalize_list (o_string * o, int n) static
Definition at line 3582 of file hush.c.
 {
     char **list;
     int string_start;
     if (DEBUG_EXPAND)
         debug_print_list("finalized", o, n);
     debug_printf_expand("finalized n:%d\n", n);
     list = (char**)o->data;
     string_start = ((n + 0xf) & ~0xf) * sizeof(list[0]);
     list[--n] = NULL;
     while (n) {
         n--;
         list[n] = o->data + (int)(uintptr_t)list[n] + string_start;
     }
     return list;
 }
References o_string::data, DEBUG_EXPAND, debug_print_list, debug_printf_expand, list(), n, and NULL.
Referenced by expand_variables().
o_free()
static ALWAYS_INLINE void o_free (o_string * o) static
Definition at line 2972 of file hush.c.
 {
     free(o->data);
 }
References o_string::data, and free.
Referenced by encode_then_append_var_plusminus(), encode_then_expand_string(), encode_then_expand_vararg(), expand_vars_to_list(), fetch_till_str(), and parse_stream().
o_free_and_set_NULL()
static void o_free_and_set_NULL (o_string * o) static
Definition at line 2966 of file hush.c.
 {
     free(o->data);
     memset(o, 0, sizeof(*o));
 }
References o_string::data, free, and memset().
Referenced by encode_then_append_var_plusminus(), and parse_stream().
o_get_last_ptr()
static int o_get_last_ptr (o_string * o, int n) static
Definition at line 3249 of file hush.c.
 {
     char **list = (char**)o->data;
     int string_start = ((n + 0xf) & ~0xf) * sizeof(list[0]);
     return ((int)(uintptr_t)list[n-1]) + string_start;
 }
References o_string::data, list(), and n.
Referenced by encode_then_append_var_plusminus(), expand_vars_to_list(), and perform_glob().
o_grow_by()
static void o_grow_by (o_string * o, int len) static
Definition at line 2977 of file hush.c.
 {
     if (o->length + len > o->maxlen) {
         o->maxlen += (2 * len) | (B_CHUNK-1);
         o->data = xrealloc(o->data, 1 + o->maxlen);
     }
 }
References B_CHUNK, o_string::data, o_string::length, o_string::maxlen, and xrealloc.
Referenced by expand_vars_to_list(), o_addblock(), o_addchr(), o_addqblock(), o_addqchr(), and o_addQchr().
o_reset_to_empty_unquoted()
static void o_reset_to_empty_unquoted (o_string * o) static
Definition at line 2958 of file hush.c.
 {
     o->length = 0;
     o->has_quoted_part = 0;
     if (o->data)
         o->data[0] = '\0';
 }
References o_string::data, o_string::has_quoted_part, and o_string::length.
Referenced by done_word(), and redirect_opt_num().
o_save_ptr()
static int o_save_ptr (o_string * o, int n) static
Definition at line 3569 of file hush.c.
 {
     if (o->o_expflags & EXP_FLAG_GLOB) {
         /* If o->has_empty_slot, list[n] was already globbed
          * (if it was requested back then when it was filled)
          * so don't do that again! */
         if (!o->has_empty_slot)
             return perform_glob(o, n); /* o_save_ptr_helper is inside */
     }
     return o_save_ptr_helper(o, n);
 }
References EXP_FLAG_GLOB, o_string::has_empty_slot, n, o_string::o_expflags, o_save_ptr_helper(), and perform_glob().
Referenced by encode_then_append_var_plusminus(), expand_on_ifs(), expand_variables(), and expand_vars_to_list().
o_save_ptr_helper()
static int o_save_ptr_helper (o_string * o, int n) static
Definition at line 3207 of file hush.c.
 {
     char **list = (char**)o->data;
     int string_start;
     int string_len;
     if (!o->has_empty_slot) {
         string_start = ((n + 0xf) & ~0xf) * sizeof(list[0]);
         string_len = o->length - string_start;
         if (!(n & 0xf)) { /* 0, 0x10, 0x20...? */
             debug_printf_list("list[%d]=%d string_start=%d (growing)\n", n, string_len, string_start);
             /* list[n] points to string_start, make space for 16 more pointers */
             o->maxlen += 0x10 * sizeof(list[0]);
             o->data = xrealloc(o->data, o->maxlen + 1);
             list = (char**)o->data;
             memmove(list + n + 0x10, list + n, string_len);
             /*
              * expand_on_ifs() has a "previous argv[] ends in IFS?"
              * check. (grep for -prev-ifs-check-).
              * Ensure that argv[-1][last] is not garbage
              * but zero bytes, to save index check there.
              */
             list[n + 0x10 - 1] = 0;
             o->length += 0x10 * sizeof(list[0]);
         } else {
             debug_printf_list("list[%d]=%d string_start=%d\n",
                     n, string_len, string_start);
         }
     } else {
         /* We have empty slot at list[n], reuse without growth */
         string_start = ((n+1 + 0xf) & ~0xf) * sizeof(list[0]); /* NB: n+1! */
         string_len = o->length - string_start;
         debug_printf_list("list[%d]=%d string_start=%d (empty slot)\n",
                 n, string_len, string_start);
         o->has_empty_slot = 0;
     }
     o->has_quoted_part = 0;
     list[n] = (char*)(uintptr_t)string_len;
     return n + 1;
 }
References o_string::data, debug_printf_list, o_string::has_empty_slot, o_string::has_quoted_part, if(), o_string::length, list(), o_string::maxlen, memmove(), n, and xrealloc.
Referenced by o_save_ptr(), and perform_glob().
parse_and_run_file()
static void parse_and_run_file (HFILE * fp) static
Definition at line 7593 of file hush.c.
 {
     struct in_str input;
     IF_HUSH_LINENO_VAR(unsigned sv = G.parse_lineno;)
     IF_HUSH_LINENO_VAR(G.parse_lineno = 1;)
     setup_file_in_str(&input, fp);
     parse_and_run_stream(&input, ';');
     IF_HUSH_LINENO_VAR(G.parse_lineno = sv;)
 }
References G, input, parse_and_run_stream(), setup_file_in_str(), and sv.
Referenced by builtin_source(), and hush_main().
parse_and_run_stream()
static void parse_and_run_stream (struct in_str * inp, int end_trigger) static
Definition at line 7534 of file hush.c.
 {
     /* Why we need empty flag?
      * An obscure corner case "false; ``; echo $?":
      * empty command in `` should still set $? to 0.
      * But we can't just set $? to 0 at the start,
      * this breaks "false; echo `echo $?`" case.
      */
     bool empty = 1;
     while (1) {
         struct pipe *pipe_list;
 #if ENABLE_HUSH_INTERACTIVE
         if (end_trigger == ';') {
             G.promptmode = 0; /* PS1 */
             debug_printf_prompt("%s promptmode=%d\n", __func__, G.promptmode);
         }
 #endif
         pipe_list = parse_stream(NULL, NULL, inp, end_trigger);
         if (!pipe_list || pipe_list == ERR_PTR) { /* EOF/error */
             /* If we are in "big" script
              * (not in `cmd` or something similar)...
              */
             if (pipe_list == ERR_PTR && end_trigger == ';') {
                 /* Discard cached input (rest of line) */
                 int ch = inp->last_char;
                 while (ch != EOF && ch != '\n') {
                     //bb_error_msg("Discarded:'%c'", ch);
                     ch = i_getch(inp);
                 }
                 /* Force prompt */
                 inp->p = NULL;
                 /* This stream isn't empty */
                 empty = 0;
                 continue;
             }
             if (!pipe_list && empty)
                 G.last_exitcode = 0;
             break;
         }
         debug_print_tree(pipe_list, 0);
         debug_printf_exec("parse_and_run_stream: run_and_free_list\n");
         run_and_free_list(pipe_list);
         empty = 0;
         if (G_flag_return_in_progress == 1)
             break;
     }
 }
References debug_print_tree, debug_printf_exec, debug_printf_prompt, EOF, ERR_PTR, G, G_flag_return_in_progress, i_getch(), in_str::last_char, NULL, in_str::p, parse_stream(), and run_and_free_list().
Referenced by parse_and_run_file(), and parse_and_run_string().
parse_and_run_string()
static void parse_and_run_string (const char * s) static
Definition at line 7583 of file hush.c.
 {
     struct in_str input;
     IF_HUSH_LINENO_VAR(unsigned sv = G.parse_lineno;)
     setup_string_in_str(&input, s);
     parse_and_run_stream(&input, '\0');
     IF_HUSH_LINENO_VAR(G.parse_lineno = sv;)
 }
References G, input, parse_and_run_stream(), s, setup_string_in_str(), and sv.
Referenced by builtin_eval(), and hush_main().
parse_dollar()
static int parse_dollar (o_string * as_string, o_string * dest, struct in_str * input, unsigned char quote_mask) static
Definition at line 5062 of file hush.c.
 {
     int ch = i_peek_and_eat_bkslash_nl(input);  /* first character after the $ */
     debug_printf_parse("parse_dollar entered: ch='%c' quote_mask:0x%x\n", ch, quote_mask);
     if (isalpha(ch)) {
  make_var:
         ch = i_getch(input);
         nommu_addchr(as_string, ch);
  /*make_var1:*/
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         while (1) {
             debug_printf_parse(": '%c'\n", ch);
             o_addchr(dest, ch | quote_mask);
             quote_mask = 0;
             ch = i_peek_and_eat_bkslash_nl(input);
             if (!isalnum(ch) && ch != '_') {
                 /* End of variable name reached */
                 break;
             }
             ch = i_getch(input);
             nommu_addchr(as_string, ch);
         }
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
     } else if (isdigit(ch)) {
  make_one_char_var:
         ch = i_getch(input);
         nommu_addchr(as_string, ch);
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         debug_printf_parse(": '%c'\n", ch);
         o_addchr(dest, ch | quote_mask);
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
     } else switch (ch) {
     case '$': /* pid */
     case '!': /* last bg pid */
     case '?': /* last exit code */
     case '#': /* number of args */
     case '*': /* args */
     case '@': /* args */
     case '-': /* $- option flags set by set builtin or shell options (-i etc) */
         goto make_one_char_var;
     case '{': {
         char len_single_ch;
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         ch = i_getch(input); /* eat '{' */
         nommu_addchr(as_string, ch);
         ch = i_getch_and_eat_bkslash_nl(input); /* first char after '{' */
         /* It should be ${?}, or ${#var},
          * or even ${?+subst} - operator acting on a special variable,
          * or the beginning of variable name.
          */
         if (ch == EOF
          || (!strchr(_SPECIAL_VARS_STR, ch) && !isalnum(ch)) /* not one of those */
         ) {
  bad_dollar_syntax:
             syntax_error_unterm_str("${name}");
             debug_printf_parse("parse_dollar return 0: unterminated ${name}\n");
             return 0;
         }
         nommu_addchr(as_string, ch);
         len_single_ch = ch;
         ch |= quote_mask;
         /* It's possible to just call add_till_closing_bracket() at this point.
          * However, this regresses some of our testsuite cases
          * which check invalid constructs like ${%}.
          * Oh well... let's check that the var name part is fine... */
         if (isdigit(len_single_ch)
          || (len_single_ch == '#' && isdigit(i_peek_and_eat_bkslash_nl(input)))
         ) {
             /* Execution engine uses plain xatoi_positive()
              * to interpret ${NNN} and {#NNN},
              * check syntax here in the parser.
              * (bash does not support expressions in ${#NN},
              * e.g. ${#$var} and {#1:+WORD} are not supported).
              */
             unsigned cnt = 9; /* max 9 digits for ${NN} and 8 for {#NN} */
             while (1) {
                 o_addchr(dest, ch);
                 debug_printf_parse(": '%c'\n", ch);
                 ch = i_getch_and_eat_bkslash_nl(input);
                 nommu_addchr(as_string, ch);
                 if (ch == '}')
                     break;
                 if (--cnt == 0)
                     goto bad_dollar_syntax;
                 if (len_single_ch != '#' && strchr(VAR_SUBST_OPS, ch))
                     /* ${NN<op>...} is valid */
                     goto eat_until_closing;
                 if (!isdigit(ch))
                     goto bad_dollar_syntax;
             }
         } else
         while (1) {
             unsigned pos;
             o_addchr(dest, ch);
             debug_printf_parse(": '%c'\n", ch);
             ch = i_getch(input);
             nommu_addchr(as_string, ch);
             if (ch == '}')
                 break;
             if (!isalnum(ch) && ch != '_') {
                 unsigned end_ch;
                 unsigned char last_ch;
                 /* handle parameter expansions
                  * http://www.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02
                  */
                 if (!strchr(VAR_SUBST_OPS, ch)) { /* ${var<bad_char>... */
                     if (len_single_ch != '#'
                     /*|| !strchr(SPECIAL_VARS_STR, ch) - disallow errors like ${#+} ? */
                      || i_peek(input) != '}'
                     ) {
                         goto bad_dollar_syntax;
                     }
                     /* else: it's "length of C" ${#C} op,
                      * where C is a single char
                      * special var name, e.g. ${#!}.
                      */
                 }
  eat_until_closing:
                 /* Eat everything until closing '}' (or ':') */
                 end_ch = '}';
                 if (BASH_SUBSTR
                  && ch == ':'
                  && !strchr(MINUS_PLUS_EQUAL_QUESTION, i_peek(input))
                 ) {
                     /* It's ${var:N[:M]} thing */
                     end_ch = '}' * 0x100 + ':';
                 }
                 if (BASH_PATTERN_SUBST
                  && ch == '/'
                 ) {
                     /* It's ${var/[/]pattern[/repl]} thing */
                     if (i_peek(input) == '/') { /* ${var//pattern[/repl]}? */
                         i_getch(input);
                         nommu_addchr(as_string, '/');
                         ch = '\\';
                     }
                     end_ch = '}' * 0x100 + '/';
                 }
                 o_addchr(dest, ch);
                 /* The pattern can't be empty.
                  * IOW: if the first char after "${v//" is a slash,
                  * it does not terminate the pattern - it's the first char of the pattern:
                  *  v=/dev/ram; echo ${v////-}  prints -dev-ram (pattern is "/")
                  *  v=/dev/ram; echo ${v///r/-} prints /dev-am  (pattern is "/r")
                  */
                 if (i_peek(input) == '/') {
                     o_addchr(dest, i_getch(input));
                 }
  again:
                 if (!BB_MMU)
                     pos = dest->length;
 #if ENABLE_HUSH_DOLLAR_OPS
                 last_ch = add_till_closing_bracket(dest, input, end_ch);
                 if (last_ch == 0) /* error? */
                     return 0;
 #else
 # error Simple code to only allow ${var} is not implemented
 #endif
                 if (as_string) {
                     o_addstr(as_string, dest->data + pos);
                     o_addchr(as_string, last_ch);
                 }
                 if ((BASH_SUBSTR || BASH_PATTERN_SUBST)
                      && (end_ch & 0xff00)
                 ) {
                     /* close the first block: */
                     o_addchr(dest, SPECIAL_VAR_SYMBOL);
                     /* while parsing N from ${var:N[:M]}
                      * or pattern from ${var/[/]pattern[/repl]} */
                     if ((end_ch & 0xff) == last_ch) {
                         /* got ':' or '/'- parse the rest */
                         end_ch = '}';
                         goto again;
                     }
                     /* got '}' */
                     if (BASH_SUBSTR && end_ch == '}' * 0x100 + ':') {
                         /* it's ${var:N} - emulate :999999999 */
                         o_addstr(dest, "999999999");
                     } /* else: it's ${var/[/]pattern} */
                 }
                 break;
             }
             len_single_ch = 0; /* it can't be ${#C} op */
         }
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         break;
     }
 #if ENABLE_FEATURE_SH_MATH || ENABLE_HUSH_TICK
     case '(': {
         unsigned pos;
         ch = i_getch(input);
         nommu_addchr(as_string, ch);
 # if ENABLE_FEATURE_SH_MATH
         if (i_peek_and_eat_bkslash_nl(input) == '(') {
             ch = i_getch(input);
             nommu_addchr(as_string, ch);
             o_addchr(dest, SPECIAL_VAR_SYMBOL);
             o_addchr(dest, quote_mask | '+');
             if (!BB_MMU)
                 pos = dest->length;
             if (!add_till_closing_bracket(dest, input, ')' | DOUBLE_CLOSE_CHAR_FLAG))
                 return 0; /* error */
             if (as_string) {
                 o_addstr(as_string, dest->data + pos);
                 o_addchr(as_string, ')');
                 o_addchr(as_string, ')');
             }
             o_addchr(dest, SPECIAL_VAR_SYMBOL);
             break;
         }
 # endif
 # if ENABLE_HUSH_TICK
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
         o_addchr(dest, quote_mask | '`');
         if (!BB_MMU)
             pos = dest->length;
         if (!add_till_closing_bracket(dest, input, ')'))
             return 0; /* error */
         if (as_string) {
             o_addstr(as_string, dest->data + pos);
             o_addchr(as_string, ')');
         }
         o_addchr(dest, SPECIAL_VAR_SYMBOL);
 # endif
         break;
     }
 #endif
     case '_':
         goto make_var;
 #if 0
     /* TODO: $_: */
     /* $_ Shell or shell script name; or last argument of last command
      * (if last command wasn't a pipe; if it was, bash sets $_ to "");
      * but in command's env, set to full pathname used to invoke it */
         ch = i_getch(input);
         nommu_addchr(as_string, ch);
         ch = i_peek_and_eat_bkslash_nl(input);
         if (isalnum(ch)) { /* it's $_name or $_123 */
             ch = '_';
             goto make_var1;
         }
         /* else: it's $_ */
 #endif
     default:
         o_addQchr(dest, '$');
     }
     debug_printf_parse("parse_dollar return 1 (ok)\n");
     return 1;
 #undef as_string
 }
References _SPECIAL_VARS_STR, add_till_closing_bracket(), BASH_PATTERN_SUBST, BASH_SUBSTR, BB_MMU, cnt, o_string::data, debug_printf_parse, DOUBLE_CLOSE_CHAR_FLAG, EOF, i_getch(), i_getch_and_eat_bkslash_nl(), i_peek(), i_peek_and_eat_bkslash_nl(), input, isalnum, isalpha, isdigit, o_string::length, MINUS_PLUS_EQUAL_QUESTION, nommu_addchr(), o_addchr(), o_addQchr(), o_addstr(), pos, SPECIAL_VAR_SYMBOL, strchr(), syntax_error_unterm_str, and VAR_SUBST_OPS.
Referenced by encode_string(), encode_then_append_var_plusminus(), encode_then_expand_vararg(), and parse_stream().
parse_group()
static int parse_group (struct parse_context * ctx, struct in_str * input, int ch) static
Definition at line 4630 of file hush.c.
 {
     /* ctx->word contains characters seen prior to ( or {.
      * Typically it's empty, but for function defs,
      * it contains function name (without '()'). */
 #if BB_MMU
 # define as_string NULL
 #else
     char *as_string = NULL;
 #endif
     struct pipe *pipe_list;
     int heredoc_cnt = 0;
     int endch;
     struct command *command = ctx->command;
     debug_printf_parse("parse_group entered\n");
 #if ENABLE_HUSH_FUNCTIONS
     if (ch == '(' && !ctx->word.has_quoted_part) {
         if (ctx->word.length)
             if (done_word(ctx))
                 return -1;
         if (!command->argv)
             goto skip; /* (... */
         if (command->argv[1]) { /* word word ... (... */
             syntax_error_unexpected_ch('(');
             return -1;
         }
         /* it is "word(..." or "word (..." */
         do
             ch = i_getch(input);
         while (ch == ' ' || ch == '\t');
         if (ch != ')') {
             syntax_error_unexpected_ch(ch);
             return -1;
         }
         nommu_addchr(&ctx->as_string, ch);
         do
             ch = i_getch(input);
         while (ch == ' ' || ch == '\t' || ch == '\n');
         if (ch != '{' && ch != '(') {
             syntax_error_unexpected_ch(ch);
             return -1;
         }
         nommu_addchr(&ctx->as_string, ch);
         command->cmd_type = CMD_FUNCDEF;
         goto skip;
     }
 #endif
 #if 0 /* Prevented by caller */
     if (command->argv /* word [word]{... */
      || ctx->word.length /* word{... */
      || ctx->word.has_quoted_part /* ""{... */
     ) {
         syntax_error(NULL);
         debug_printf_parse("parse_group return -1: "
             "syntax error, groups and arglists don't mix\n");
         return -1;
     }
 #endif
  IF_HUSH_FUNCTIONS(skip:)
     endch = '}';
     if (ch == '(') {
         endch = ')';
         IF_HUSH_FUNCTIONS(if (command->cmd_type != CMD_FUNCDEF))
             command->cmd_type = CMD_SUBSHELL;
     } else {
         /* bash does not allow "{echo...", requires whitespace */
         ch = i_peek(input);
         if (ch != ' ' && ch != '\t' && ch != '\n'
          && ch != '('   /* but "{(..." is allowed (without whitespace) */
         ) {
             syntax_error_unexpected_ch(ch);
             return -1;
         }
         if (ch != '(') {
             ch = i_getch(input);
             nommu_addchr(&ctx->as_string, ch);
         }
     }
     debug_printf_heredoc("calling parse_stream, heredoc_cnt:%d\n", heredoc_cnt);
     pipe_list = parse_stream(&as_string, &heredoc_cnt, input, endch);
     debug_printf_heredoc("parse_stream returned: heredoc_cnt:%d\n", heredoc_cnt);
 #if !BB_MMU
     if (as_string)
         o_addstr(&ctx->as_string, as_string);
 #endif
     /* empty ()/{} or parse error? */
     if (!pipe_list || pipe_list == ERR_PTR) {
         /* parse_stream already emitted error msg */
         if (!BB_MMU)
             free(as_string);
         debug_printf_parse("parse_group return -1: "
             "parse_stream returned %p\n", pipe_list);
         return -1;
     }
 #if !BB_MMU
     as_string[strlen(as_string) - 1] = '\0'; /* plink ')' or '}' */
     command->group_as_string = as_string;
     debug_printf_parse("end of group, remembering as:'%s'\n",
             command->group_as_string);
 #endif
 #if ENABLE_HUSH_FUNCTIONS
     /* Convert "f() (cmds)" to "f() {(cmds)}" */
     if (command->cmd_type == CMD_FUNCDEF && endch == ')') {
         struct command *cmd2;
         cmd2 = xzalloc(sizeof(*cmd2));
         cmd2->cmd_type = CMD_SUBSHELL;
         cmd2->group = pipe_list;
 # if !BB_MMU
 //UNTESTED!
         cmd2->group_as_string = command->group_as_string;
         command->group_as_string = xasprintf("(%s)", command->group_as_string);
 # endif
         pipe_list = new_pipe();
         pipe_list->cmds = cmd2;
         pipe_list->num_cmds = 1;
     }
 #endif
     command->group = pipe_list;
     debug_printf_parse("parse_group return %d\n", heredoc_cnt);
     return heredoc_cnt;
     /* command remains "open", available for possible redirects */
 #undef as_string
 }
References command::argv, BB_MMU, CMD_SUBSHELL, command::cmd_type, pipe::cmds, debug_printf_heredoc, debug_printf_parse, done_word(), ERR_PTR, free, command::group, command::group_as_string, i_getch(), i_peek(), input, new_pipe(), nommu_addchr(), NULL, pipe::num_cmds, o_addstr(), parse_stream(), skip, strlen(), syntax_error, syntax_error_unexpected_ch, xasprintf(), and xzalloc().
Referenced by parse_stream().
parse_redir_right_fd()
static int parse_redir_right_fd (o_string * as_string, struct in_str * input) static
Definition at line 4333 of file hush.c.
 {
     int ch, d, ok;
     ch = i_peek(input);
     if (ch != '&')
         return REDIRFD_TO_FILE;
     ch = i_getch(input);  /* get the & */
     nommu_addchr(as_string, ch);
     ch = i_peek(input);
     if (ch == '-') {
         ch = i_getch(input);
         nommu_addchr(as_string, ch);
         return REDIRFD_CLOSE;
     }
     d = 0;
     ok = 0;
     while (ch != EOF && isdigit(ch)) {
         d = d*10 + (ch-'0');
         ok = 1;
         ch = i_getch(input);
         nommu_addchr(as_string, ch);
         ch = i_peek(input);
     }
     if (ok) return d;
 //TODO: this is the place to catch ">&file" bashism (redirect both fd 1 and 2)
     bb_simple_error_msg("ambiguous redirect");
     return REDIRFD_SYNTAX_ERR;
 }
References bb_simple_error_msg(), EOF, i_getch(), i_peek(), input, isdigit, nommu_addchr(), ok, REDIRFD_CLOSE, REDIRFD_SYNTAX_ERR, and REDIRFD_TO_FILE.
Referenced by parse_redirect().
parse_redirect()
static int parse_redirect (struct parse_context * ctx, int fd, redir_type style, struct in_str * input) static
Definition at line 4368 of file hush.c.
 {
     struct command *command = ctx->command;
     struct redir_struct *redir;
     struct redir_struct **redirp;
     int dup_num;
     dup_num = REDIRFD_TO_FILE;
     if (style != REDIRECT_HEREDOC) {
         /* Check for a '>&1' type redirect */
         dup_num = parse_redir_right_fd(&ctx->as_string, input);
         if (dup_num == REDIRFD_SYNTAX_ERR)
             return 1;
     } else {
         int ch = i_peek_and_eat_bkslash_nl(input);
         dup_num = (ch == '-'); /* HEREDOC_SKIPTABS bit is 1 */
         if (dup_num) { /* <<-... */
             ch = i_getch(input);
             nommu_addchr(&ctx->as_string, ch);
             ch = i_peek(input);
         }
     }
     if (style == REDIRECT_OVERWRITE && dup_num == REDIRFD_TO_FILE) {
         int ch = i_peek_and_eat_bkslash_nl(input);
         if (ch == '|') {
             /* >|FILE redirect ("clobbering" >).
              * Since we do not support "set -o noclobber" yet,
              * >| and > are the same for now. Just eat |.
              */
             ch = i_getch(input);
             nommu_addchr(&ctx->as_string, ch);
         }
     }
     /* Create a new redir_struct and append it to the linked list */
     redirp = &command->redirects;
     while ((redir = *redirp) != NULL) {
         redirp = &(redir->next);
     }
     *redirp = redir = xzalloc(sizeof(*redir));
     /* redir->next = NULL; */
     /* redir->rd_filename = NULL; */
     redir->rd_type = style;
     redir->rd_fd = (fd == -1) ? redir_table[style].default_fd : fd;
     debug_printf_parse("redirect type %d %s\n", redir->rd_fd,
                 redir_table[style].descrip);
     redir->rd_dup = dup_num;
     if (style != REDIRECT_HEREDOC && dup_num != REDIRFD_TO_FILE) {
         /* Erik had a check here that the file descriptor in question
          * is legit; I postpone that to "run time"
          * A "-" representation of "close me" shows up as a -3 here */
         debug_printf_parse("duplicating redirect '%d>&%d'\n",
                 redir->rd_fd, redir->rd_dup);
     } else {
 #if 0       /* Instead we emit error message at run time */
         if (ctx->pending_redirect) {
             /* For example, "cmd > <file" */
             syntax_error("invalid redirect");
         }
 #endif
         /* Set ctx->pending_redirect, so we know what to do at the
          * end of the next parsed word. */
         ctx->pending_redirect = redir;
     }
     return 0;
 }
References debug_printf_parse, fd, i_getch(), i_peek(), i_peek_and_eat_bkslash_nl(), input, nommu_addchr(), NULL, parse_redir_right_fd(), redir, REDIRECT_HEREDOC, REDIRECT_OVERWRITE, command::redirects, REDIRFD_SYNTAX_ERR, REDIRFD_TO_FILE, syntax_error, and xzalloc().
Referenced by parse_stream().
parse_stream()
static struct pipe * parse_stream (char ** pstring, int * heredoc_cnt_ptr, struct in_str * input, int end_trigger) static
Definition at line 5423 of file hush.c.
 {
     struct parse_context ctx;
     int heredoc_cnt;
     /* Single-quote triggers a bypass of the main loop until its mate is
      * found.  When recursing, quote state is passed in via ctx.word.o_expflags.
      */
     debug_printf_parse("parse_stream entered, end_trigger='%c'\n",
             end_trigger ? end_trigger : 'X');
     debug_enter();
     initialize_context(&ctx);
     /* If very first arg is "" or '', ctx.word.data may end up NULL.
      * Preventing this:
      */
     ctx.word.data = xzalloc(1); /* start as "", not as NULL */
     /* We used to separate words on $IFS here. This was wrong.
      * $IFS is used only for word splitting when $var is expanded,
      * here we should use blank chars as separators, not $IFS
      */
     heredoc_cnt = 0;
     while (1) {
         const char *is_blank;
         const char *is_special;
         int ch;
         int next;
         int redir_fd;
         redir_type redir_style;
         ch = i_getch(input);
         debug_printf_parse(": ch=%c (%d) escape=%d\n",
                 ch, ch, !!(ctx.word.o_expflags & EXP_FLAG_ESC_GLOB_CHARS));
         if (ch == EOF) {
             struct pipe *pi;
             if (heredoc_cnt) {
                 syntax_error_unterm_str("here document");
                 goto parse_error_exitcode1;
             }
             if (end_trigger == ')') {
                 syntax_error_unterm_ch('(');
                 goto parse_error_exitcode1;
             }
             if (end_trigger == '}') {
                 syntax_error_unterm_ch('{');
                 goto parse_error_exitcode1;
             }
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             o_free_and_set_NULL(&ctx.word);
             done_pipe(&ctx, PIPE_SEQ);
             pi = ctx.list_head;
             /* If we got nothing... */
             /* (this makes bare "&" cmd a no-op.
              * bash says: "syntax error near unexpected token '&'") */
             if (pi->num_cmds == 0
             IF_HAS_KEYWORDS(&& pi->res_word == RES_NONE)
             ) {
                 free_pipe_list(pi);
                 pi = NULL;
             }
 #if !BB_MMU
             debug_printf_parse("as_string1 '%s'\n", ctx.as_string.data);
             if (pstring)
                 *pstring = ctx.as_string.data;
             else
                 o_free(&ctx.as_string);
 #endif
             // heredoc_cnt must be 0 here anyway
             //if (heredoc_cnt_ptr)
             //  *heredoc_cnt_ptr = heredoc_cnt;
             debug_leave();
             debug_printf_heredoc("parse_stream return heredoc_cnt:%d\n", heredoc_cnt);
             debug_printf_parse("parse_stream return %p\n", pi);
             return pi;
         }
         /* Handle "'" and "\" first, as they won't play nice with
          * i_peek_and_eat_bkslash_nl() anyway:
          *   echo z\\
          * and
          *   echo '\
          *   '
          * would break.
          */
         if (ch == '\\') {
             ch = i_getch(input);
             if (ch == '\n')
                 continue; /* drop <newline>, get next char */
             nommu_addchr(&ctx.as_string, '\\');
             if (ch == SPECIAL_VAR_SYMBOL) {
                 nommu_addchr(&ctx.as_string, ch);
                 /* Convert \^C to corresponding special variable reference */
                 goto case_SPECIAL_VAR_SYMBOL;
             }
             o_addchr(&ctx.word, '\\');
             if (ch == EOF) {
                 /* Testcase: eval 'echo Ok\' */
                 /* bash-4.3.43 was removing backslash,
                  * but 4.4.19 retains it, most other shells too
                  */
                 continue; /* get next char */
             }
             /* Example: echo Hello \2>file
              * we need to know that word 2 is quoted
              */
             ctx.word.has_quoted_part = 1;
             nommu_addchr(&ctx.as_string, ch);
             o_addchr(&ctx.word, ch);
             continue; /* get next char */
         }
         nommu_addchr(&ctx.as_string, ch);
         if (ch == '\'') {
             ctx.word.has_quoted_part = 1;
             next = i_getch(input);
             if (next == '\'' && !ctx.pending_redirect)
                 goto insert_empty_quoted_str_marker;
             ch = next;
             while (1) {
                 if (ch == EOF) {
                     syntax_error_unterm_ch('\'');
                     goto parse_error_exitcode1;
                 }
                 nommu_addchr(&ctx.as_string, ch);
                 if (ch == '\'')
                     break;
                 if (ch == SPECIAL_VAR_SYMBOL) {
                     /* Convert raw ^C to corresponding special variable reference */
                     o_addchr(&ctx.word, SPECIAL_VAR_SYMBOL);
                     o_addchr(&ctx.word, SPECIAL_VAR_QUOTED_SVS);
                 }
                 o_addqchr(&ctx.word, ch);
                 ch = i_getch(input);
             }
             continue; /* get next char */
         }
         next = '\0';
         if (ch != '\n')
             next = i_peek_and_eat_bkslash_nl(input);
         is_special = "{}<>&|();#" /* special outside of "str" */
                 "$\"" IF_HUSH_TICK("`") /* always special */
                 SPECIAL_VAR_SYMBOL_STR;
 #if defined(CMD_TEST2_SINGLEWORD_NOGLOB)
         if (ctx.command->cmd_type == CMD_TEST2_SINGLEWORD_NOGLOB) {
             /* In [[ ]], {}<>&|() are not special */
             is_special += 8;
         } else
 #endif
         /* Are { and } special here? */
         if (ctx.command->argv /* word [word]{... - non-special */
          || ctx.word.length       /* word{... - non-special */
          || ctx.word.has_quoted_part     /* ""{... - non-special */
          || (next != ';'             /* }; - special */
             && next != ')'           /* }) - special */
             && next != '('           /* {( - special */
             && next != '&'           /* }& and }&& ... - special */
             && next != '|'           /* }|| ... - special */
             && !strchr(defifs, next) /* {word - non-special */
             )
         ) {
             /* They are not special, skip "{}" */
             is_special += 2;
         }
         is_special = strchr(is_special, ch);
         is_blank = strchr(defifs, ch);
         if (!is_special && !is_blank) { /* ordinary char */
  ordinary_char:
             o_addQchr(&ctx.word, ch);
             if ((ctx.is_assignment == MAYBE_ASSIGNMENT
                 || ctx.is_assignment == WORD_IS_KEYWORD)
              && ch == '='
              && endofname(ctx.word.data)[0] == '='
             ) {
                 ctx.is_assignment = DEFINITELY_ASSIGNMENT;
                 debug_printf_parse("ctx.is_assignment='%s'\n", assignment_flag[ctx.is_assignment]);
             }
             continue;
         }
         if (is_blank) {
 #if ENABLE_HUSH_LINENO_VAR
 /* Case:
  * "while ...; do<whitespace><newline>
  *  cmd ..."
  * would think that "cmd" starts in <whitespace> -
  * i.e., at the previous line.
  * We need to skip all whitespace before newlines.
  */
             while (ch != '\n') {
                 next = i_peek(input);
                 if (next != ' ' && next != '\t' && next != '\n')
                     break; /* next char is not ws */
                 ch = i_getch(input);
             }
             /* ch == last eaten whitespace char */
 #endif
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             if (ch == '\n') {
                 /* Is this a case when newline is simply ignored?
                  * Some examples:
                  * "cmd | <newline> cmd ..."
                  * "case ... in <newline> word) ..."
                  */
                 if (IS_NULL_CMD(ctx.command)
                  && ctx.word.length == 0
                  && !ctx.word.has_quoted_part
                  && heredoc_cnt == 0
                 ) {
                     /* This newline can be ignored. But...
                      * Without check #1, interactive shell
                      * ignores even bare <newline>,
                      * and shows the continuation prompt:
                      * ps1_prompt$ <enter>
                      * ps2> _   <=== wrong, should be ps1
                      * Without check #2, "cmd & <newline>"
                      * is similarly mistreated.
                      * (BTW, this makes "cmd & cmd"
                      * and "cmd && cmd" non-orthogonal.
                      * Really, ask yourself, why
                      * "cmd && <newline>" doesn't start
                      * cmd but waits for more input?
                      * The only reason is that it might be
                      * a "cmd1 && <nl> cmd2 &" construct,
                      * cmd1 may need to run in BG).
                      */
                     struct pipe *pi = ctx.list_head;
                     if (pi->num_cmds != 0       /* check #1 */
                      && pi->followup != PIPE_BG /* check #2 */
                     ) {
                         continue;
                     }
                 }
                 /* Treat newline as a command separator. */
                 done_pipe(&ctx, PIPE_SEQ);
                 debug_printf_heredoc("heredoc_cnt:%d\n", heredoc_cnt);
                 if (heredoc_cnt) {
                     heredoc_cnt = fetch_heredocs(&ctx.as_string, ctx.list_head, heredoc_cnt, input);
                     if (heredoc_cnt != 0)
                         goto parse_error_exitcode1;
                 }
                 ctx.is_assignment = MAYBE_ASSIGNMENT;
                 debug_printf_parse("ctx.is_assignment='%s'\n", assignment_flag[ctx.is_assignment]);
                 ch = ';';
                 /* note: if (is_blank) continue;
                  * will still trigger for us */
             }
         }
         /* "cmd}" or "cmd }..." without semicolon or &:
          * } is an ordinary char in this case, even inside { cmd; }
          * Pathological example: { ""}; } should exec "}" cmd
          */
         if (ch == '}') {
             if (ctx.word.length != 0 /* word} */
              || ctx.word.has_quoted_part    /* ""} */
             ) {
                 goto ordinary_char;
             }
             if (!IS_NULL_CMD(ctx.command)) { /* cmd } */
                 /* Generally, there should be semicolon: "cmd; }"
                  * However, bash allows to omit it if "cmd" is
                  * a group. Examples:
                  * { { echo 1; } }
                  * {(echo 1)}
                  * { echo 0 >&2 | { echo 1; } }
                  * { while false; do :; done }
                  * { case a in b) ;; esac }
                  */
                 if (ctx.command->group)
                     goto term_group;
                 goto ordinary_char;
             }
             if (!IS_NULL_PIPE(ctx.pipe)) /* cmd | } */
                 /* Can't be an end of {cmd}, skip the check */
                 goto skip_end_trigger;
             /* else: } does terminate a group */
         }
  term_group:
         if (end_trigger && end_trigger == ch
          && (ch != ';' || heredoc_cnt == 0)
 #if ENABLE_HUSH_CASE
          && (ch != ')'
             || ctx.ctx_res_w != RES_MATCH
             || (!ctx.word.has_quoted_part && strcmp(ctx.word.data, "esac") == 0)
             )
 #endif
         ) {
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             done_pipe(&ctx, PIPE_SEQ);
             ctx.is_assignment = MAYBE_ASSIGNMENT;
             debug_printf_parse("ctx.is_assignment='%s'\n", assignment_flag[ctx.is_assignment]);
             /* Do we sit outside of any if's, loops or case's? */
             if (!HAS_KEYWORDS
             IF_HAS_KEYWORDS(|| (ctx.ctx_res_w == RES_NONE && ctx.old_flag == 0))
             ) {
                 o_free_and_set_NULL(&ctx.word);
 #if !BB_MMU
                 debug_printf_parse("as_string2 '%s'\n", ctx.as_string.data);
                 if (pstring)
                     *pstring = ctx.as_string.data;
                 else
                     o_free(&ctx.as_string);
 #endif
                 if (ch != ';' && IS_NULL_PIPE(ctx.list_head)) {
                     /* Example: bare "{ }", "()" */
                     G.last_exitcode = 2; /* bash compat */
                     syntax_error_unexpected_ch(ch);
                     goto parse_error;
                 }
                 if (heredoc_cnt_ptr)
                     *heredoc_cnt_ptr = heredoc_cnt;
                 debug_printf_heredoc("parse_stream return heredoc_cnt:%d\n", heredoc_cnt);
                 debug_printf_parse("parse_stream return %p: "
                         "end_trigger char found\n",
                         ctx.list_head);
                 debug_leave();
                 return ctx.list_head;
             }
         }
         if (is_blank)
             continue;
         /* Catch <, > before deciding whether this word is
          * an assignment. a=1 2>z b=2: b=2 is still assignment */
         switch (ch) {
         case '>':
             redir_fd = redirect_opt_num(&ctx.word);
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             redir_style = REDIRECT_OVERWRITE;
             if (next == '>') {
                 redir_style = REDIRECT_APPEND;
                 ch = i_getch(input);
                 nommu_addchr(&ctx.as_string, ch);
             }
 #if 0
             else if (next == '(') {
                 syntax_error(">(process) not supported");
                 goto parse_error_exitcode1;
             }
 #endif
             if (parse_redirect(&ctx, redir_fd, redir_style, input))
                 goto parse_error_exitcode1;
             continue; /* get next char */
         case '<':
             redir_fd = redirect_opt_num(&ctx.word);
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             redir_style = REDIRECT_INPUT;
             if (next == '<') {
                 redir_style = REDIRECT_HEREDOC;
                 heredoc_cnt++;
                 debug_printf_heredoc("++heredoc_cnt=%d\n", heredoc_cnt);
                 ch = i_getch(input);
                 nommu_addchr(&ctx.as_string, ch);
             } else if (next == '>') {
                 redir_style = REDIRECT_IO;
                 ch = i_getch(input);
                 nommu_addchr(&ctx.as_string, ch);
             }
 #if 0
             else if (next == '(') {
                 syntax_error("<(process) not supported");
                 goto parse_error_exitcode1;
             }
 #endif
             if (parse_redirect(&ctx, redir_fd, redir_style, input))
                 goto parse_error_exitcode1;
             continue; /* get next char */
         case '#':
             if (ctx.word.length == 0 && !ctx.word.has_quoted_part) {
                 /* skip "#comment" */
                 /* note: we do not add it to &ctx.as_string */
 /* TODO: in bash:
  * comment inside $() goes to the next \n, even inside quoted string (!):
  * cmd "$(cmd2 #comment)" - syntax error
  * cmd "`cmd2 #comment`" - ok
  * We accept both (comment ends where command subst ends, in both cases).
  */
                 while (1) {
                     ch = i_peek(input);
                     if (ch == '\n') {
                         nommu_addchr(&ctx.as_string, '\n');
                         break;
                     }
                     ch = i_getch(input);
                     if (ch == EOF)
                         break;
                 }
                 continue; /* get next char */
             }
             break;
         }
  skip_end_trigger:
         if (ctx.is_assignment == MAYBE_ASSIGNMENT
          /* check that we are not in word in "a=1 2>word b=1": */
          && !ctx.pending_redirect
         ) {
             /* ch is a special char and thus this word
              * cannot be an assignment */
             ctx.is_assignment = NOT_ASSIGNMENT;
             debug_printf_parse("ctx.is_assignment='%s'\n", assignment_flag[ctx.is_assignment]);
         }
         /* Note: nommu_addchr(&ctx.as_string, ch) is already done */
         switch (ch) {
         case_SPECIAL_VAR_SYMBOL:
         case SPECIAL_VAR_SYMBOL:
             /* Convert raw ^C to corresponding special variable reference */
             o_addchr(&ctx.word, SPECIAL_VAR_SYMBOL);
             o_addchr(&ctx.word, SPECIAL_VAR_QUOTED_SVS);
             /* fall through */
         case '#':
             /* non-comment #: "echo a#b" etc */
             o_addchr(&ctx.word, ch);
             continue; /* get next char */
         case '$':
             if (parse_dollar_squote(&ctx.as_string, &ctx.word, input))
                 continue; /* get next char */
             if (!parse_dollar(&ctx.as_string, &ctx.word, input, /*quote_mask:*/ 0)) {
                 debug_printf_parse("parse_stream parse error: "
                     "parse_dollar returned 0 (error)\n");
                 goto parse_error_exitcode1;
             }
             continue; /* get next char */
         case '"':
             ctx.word.has_quoted_part = 1;
             if (next == '"' && !ctx.pending_redirect) {
                 i_getch(input); /* eat second " */
  insert_empty_quoted_str_marker:
                 nommu_addchr(&ctx.as_string, next);
                 o_addchr(&ctx.word, SPECIAL_VAR_SYMBOL);
                 o_addchr(&ctx.word, SPECIAL_VAR_SYMBOL);
                 continue; /* get next char */
             }
             if (ctx.is_assignment == NOT_ASSIGNMENT)
                 ctx.word.o_expflags |= EXP_FLAG_ESC_GLOB_CHARS;
             if (!encode_string(&ctx.as_string, &ctx.word, input, '"'))
                 goto parse_error_exitcode1;
             ctx.word.o_expflags &= ~EXP_FLAG_ESC_GLOB_CHARS;
             continue; /* get next char */
 #if ENABLE_HUSH_TICK
         case '`': {
             USE_FOR_NOMMU(unsigned pos;)
             o_addchr(&ctx.word, SPECIAL_VAR_SYMBOL);
             o_addchr(&ctx.word, '`');
             USE_FOR_NOMMU(pos = ctx.word.length;)
             if (!add_till_backquote(&ctx.word, input, /*in_dquote:*/ 0))
                 goto parse_error_exitcode1;
 # if !BB_MMU
             o_addstr(&ctx.as_string, ctx.word.data + pos);
             o_addchr(&ctx.as_string, '`');
 # endif
             o_addchr(&ctx.word, SPECIAL_VAR_SYMBOL);
             //debug_printf_subst("SUBST RES3 '%s'\n", ctx.word.data + pos);
             continue; /* get next char */
         }
 #endif
         case ';':
 #if ENABLE_HUSH_CASE
  case_semi:
 #endif
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             done_pipe(&ctx, PIPE_SEQ);
 #if ENABLE_HUSH_CASE
             /* Eat multiple semicolons, detect
              * whether it means something special */
             while (1) {
                 ch = i_peek_and_eat_bkslash_nl(input);
                 if (ch != ';')
                     break;
                 ch = i_getch(input);
                 nommu_addchr(&ctx.as_string, ch);
                 if (ctx.ctx_res_w == RES_CASE_BODY) {
                     ctx.ctx_dsemicolon = 1;
                     ctx.ctx_res_w = RES_MATCH;
                     break;
                 }
             }
 #endif
  new_cmd:
             /* We just finished a cmd. New one may start
              * with an assignment */
             ctx.is_assignment = MAYBE_ASSIGNMENT;
             debug_printf_parse("ctx.is_assignment='%s'\n", assignment_flag[ctx.is_assignment]);
             continue; /* get next char */
         case '&':
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
             if (next == '&') {
                 ch = i_getch(input);
                 nommu_addchr(&ctx.as_string, ch);
                 done_pipe(&ctx, PIPE_AND);
             } else {
                 done_pipe(&ctx, PIPE_BG);
             }
             goto new_cmd;
         case '|':
             if (done_word(&ctx)) {
                 goto parse_error_exitcode1;
             }
 #if ENABLE_HUSH_CASE
             if (ctx.ctx_res_w == RES_MATCH)
                 break; /* we are in case's "word | word)" */
 #endif
             if (next == '|') { /* || */
                 ch = i_getch(input);
                 nommu_addchr(&ctx.as_string, ch);
                 done_pipe(&ctx, PIPE_OR);
             } else {
                 /* we could pick up a file descriptor choice here
                  * with redirect_opt_num(), but bash doesn't do it.
                  * "echo foo 2| cat" yields "foo 2". */
                 done_command(&ctx);
             }
             goto new_cmd;
         case '(':
 #if ENABLE_HUSH_CASE
             /* "case... in [(]word)..." - skip '(' */
             if (ctx.ctx_res_w == RES_MATCH
              && ctx.command->argv == NULL /* not (word|(... */
              && ctx.word.length == 0 /* not word(... */
              && ctx.word.has_quoted_part == 0 /* not ""(... */
             ) {
                 continue; /* get next char */
             }
 #endif
             /* fall through */
         case '{': {
             int n = parse_group(&ctx, input, ch);
             if (n < 0) {
                 goto parse_error_exitcode1;
             }
             debug_printf_heredoc("parse_group done, needs heredocs:%d\n", n);
             heredoc_cnt += n;
             goto new_cmd;
         }
         case ')':
 #if ENABLE_HUSH_CASE
             if (ctx.ctx_res_w == RES_MATCH)
                 goto case_semi;
 #endif
         case '}':
             /* proper use of this character is caught by end_trigger:
              * if we see {, we call parse_group(..., end_trigger='}')
              * and it will match } earlier (not here). */
             G.last_exitcode = 2;
             syntax_error_unexpected_ch(ch);
             goto parse_error;
         default:
             if (HUSH_DEBUG)
                 bb_error_msg_and_die("BUG: unexpected %c", ch);
         }
     } /* while (1) */
  parse_error_exitcode1:
     G.last_exitcode = 1;
  parse_error:
     {
         struct parse_context *pctx;
         IF_HAS_KEYWORDS(struct parse_context *p2;)
         /* Clean up allocated tree.
          * Sample for finding leaks on syntax error recovery path.
          * Run it from interactive shell, watch pmap `pidof hush`.
          * while if false; then false; fi; do break; fi
          * Samples to catch leaks at execution:
          * while if (true | { true;}); then echo ok; fi; do break; done
          * while if (true | { true;}); then echo ok; fi; do (if echo ok; break; then :; fi) | cat; break; done
          */
         pctx = &ctx;
         do {
             /* Update pipe/command counts,
              * otherwise freeing may miss some */
             done_pipe(pctx, PIPE_SEQ);
             debug_printf_clean("freeing list %p from ctx %p\n",
                     pctx->list_head, pctx);
             debug_print_tree(pctx->list_head, 0);
             free_pipe_list(pctx->list_head);
             debug_printf_clean("freed list %p\n", pctx->list_head);
 #if !BB_MMU
             o_free(&pctx->as_string);
 #endif
             IF_HAS_KEYWORDS(p2 = pctx->stack;)
             if (pctx != &ctx) {
                 free(pctx);
             }
             IF_HAS_KEYWORDS(pctx = p2;)
         } while (HAS_KEYWORDS && pctx);
         o_free(&ctx.word);
 #if !BB_MMU
         if (pstring)
             *pstring = NULL;
 #endif
         debug_leave();
         return ERR_PTR;
     }
 }
References add_till_backquote(), parse_context::as_string, bb_error_msg_and_die(), debug_enter, debug_leave, debug_print_tree, debug_printf_clean, debug_printf_heredoc, debug_printf_parse, defifs, DEFINITELY_ASSIGNMENT, done_command(), done_pipe(), done_word(), encode_string(), endofname(), EOF, ERR_PTR, EXP_FLAG_ESC_GLOB_CHARS, fetch_heredocs(), free, free_pipe_list(), G, HAS_KEYWORDS, HUSH_DEBUG, i_getch(), i_peek(), i_peek_and_eat_bkslash_nl(), IF_HAS_KEYWORDS, initialize_context(), input, IS_NULL_CMD, IS_NULL_PIPE, is_special, parse_context::list_head, MAYBE_ASSIGNMENT, n, next, nommu_addchr(), NOT_ASSIGNMENT, NULL, o_addchr(), o_addqchr(), o_addQchr(), o_addstr(), o_free(), o_free_and_set_NULL(), parse_dollar(), parse_dollar_squote, parse_group(), parse_redirect(), pi, PIPE_AND, PIPE_BG, PIPE_OR, PIPE_SEQ, pos, REDIRECT_APPEND, REDIRECT_HEREDOC, REDIRECT_INPUT, REDIRECT_IO, redirect_opt_num(), REDIRECT_OVERWRITE, RES_NONE, SPECIAL_VAR_QUOTED_SVS, SPECIAL_VAR_SYMBOL, SPECIAL_VAR_SYMBOL_STR, strchr(), strcmp, syntax_error, syntax_error_unexpected_ch, syntax_error_unterm_ch, syntax_error_unterm_str, USE_FOR_NOMMU, WORD_IS_KEYWORD, and xzalloc().
Referenced by parse_and_run_stream(), and parse_group().
perform_glob()
static int perform_glob (o_string * o, int n) static
Definition at line 3509 of file hush.c.
 {
     glob_t globdata;
     int gr;
     char *pattern;
     debug_printf_glob("start perform_glob: n:%d o->data:%p\n", n, o->data);
     if (!o->data)
         return o_save_ptr_helper(o, n);
     pattern = o->data + o_get_last_ptr(o, n);
     debug_printf_glob("glob pattern '%s'\n", pattern);
     if (!glob_needed(pattern)) {
  literal:
         /* unbackslash last string in o in place, fix length */
         o->length = unbackslash(pattern) - o->data;
         debug_printf_glob("glob pattern '%s' is literal\n", pattern);
         return o_save_ptr_helper(o, n);
     }
     memset(&globdata, 0, sizeof(globdata));
     /* Can't use GLOB_NOCHECK: it does not unescape the string.
      * If we glob "*.\*" and don't find anything, we need
      * to fall back to using literal "*.*", but GLOB_NOCHECK
      * will return "*.\*"!
      */
     gr = glob(pattern, 0, NULL, &globdata);
     debug_printf_glob("glob('%s'):%d\n", pattern, gr);
     if (gr != 0) {
         if (gr == GLOB_NOMATCH) {
             globfree(&globdata);
             goto literal;
         }
         if (gr == GLOB_NOSPACE)
             bb_die_memory_exhausted();
         /* GLOB_ABORTED? Only happens with GLOB_ERR flag,
          * but we didn't specify it. Paranoia again. */
         bb_error_msg_and_die("glob error %d on '%s'", gr, pattern);
     }
     if (globdata.gl_pathv && globdata.gl_pathv[0]) {
         char **argv = globdata.gl_pathv;
         /* "forget" pattern in o */
         o->length = pattern - o->data;
         while (1) {
             o_addstr_with_NUL(o, *argv);
             n = o_save_ptr_helper(o, n);
             argv++;
             if (!*argv)
                 break;
         }
     }
     globfree(&globdata);
     if (DEBUG_GLOB)
         debug_print_list("perform_glob returning", o, n);
     return n;
 }
References argv, bb_die_memory_exhausted(), bb_error_msg_and_die(), o_string::data, DEBUG_GLOB, debug_print_list, debug_printf_glob, glob_t::gl_pathv, glob(), glob_needed(), GLOB_NOMATCH, GLOB_NOSPACE, globfree(), gr, o_string::length, memset(), n, NULL, o_addstr_with_NUL(), o_get_last_ptr(), o_save_ptr_helper(), pattern, and unbackslash().
Referenced by o_save_ptr().
pick_sighandler()
static sighandler_t pick_sighandler (unsigned sig) static
Definition at line 2047 of file hush.c.
 {
     sighandler_t handler = SIG_DFL;
     if (sig < sizeof(unsigned)*8) {
         unsigned sigmask = (1 << sig);
 #if ENABLE_HUSH_JOB
         /* is sig fatal? */
         if (G_fatal_sig_mask & sigmask)
             handler = sigexit;
         else
 #endif
         /* sig has special handling? */
         if (G.special_sig_mask & sigmask) {
             handler = record_pending_signo;
             /* TTIN/TTOU/TSTP can't be set to record_pending_signo
              * in order to ignore them: they will be raised
              * in an endless loop when we try to do some
              * terminal ioctls! We do have to _ignore_ these.
              */
             if (SPECIAL_JOBSTOP_SIGS & sigmask)
                 handler = SIG_IGN;
         }
     }
     return handler;
 }
References G, G_fatal_sig_mask, handler(), record_pending_signo(), SIG_DFL, SIG_IGN, sigmask, and SPECIAL_JOBSTOP_SIGS.
Referenced by install_sighandlers().
process_wait_result()
static int process_wait_result (struct pipe * fg_pipe, pid_t childpid, int status) static
Definition at line 8923 of file hush.c.
 {
 #if ENABLE_HUSH_JOB
     struct pipe *pi;
 #endif
     int i, dead;
     dead = WIFEXITED(status) || WIFSIGNALED(status);
 #if DEBUG_JOBS
     if (WIFSTOPPED(status))
         debug_printf_jobs("pid %d stopped by sig %d (exitcode %d)\n",
                 childpid, WSTOPSIG(status), WEXITSTATUS(status));
     if (WIFSIGNALED(status))
         debug_printf_jobs("pid %d killed by sig %d (exitcode %d)\n",
                 childpid, WTERMSIG(status), WEXITSTATUS(status));
     if (WIFEXITED(status))
         debug_printf_jobs("pid %d exited, exitcode %d\n",
                 childpid, WEXITSTATUS(status));
 #endif
     /* Were we asked to wait for a fg pipe? */
     if (fg_pipe) {
         i = fg_pipe->num_cmds;
         while (--i >= 0) {
             int rcode;
             debug_printf_jobs("check pid %d\n", fg_pipe->cmds[i].pid);
             if (fg_pipe->cmds[i].pid != childpid)
                 continue;
             if (dead) {
                 int ex;
                 fg_pipe->cmds[i].pid = 0;
                 fg_pipe->alive_cmds--;
                 ex = WEXITSTATUS(status);
                 /* bash prints killer signal's name for *last*
                  * process in pipe (prints just newline for SIGINT/SIGPIPE).
                  * Mimic this. Example: "sleep 5" + (^\ or kill -QUIT)
                  */
                 if (WIFSIGNALED(status)) {
                     int sig = WTERMSIG(status);
 #if ENABLE_HUSH_JOB
                     if (G.run_list_level == 1
                     /* ^^^^^ Do not print in nested contexts, example:
                      * echo `sleep 1; sh -c 'kill -9 $$'` - prints "137", NOT "Killed 137"
                      */
                      && i == fg_pipe->num_cmds-1
                     ) {
                         /* strsignal() is for bash compat. ~600 bloat versus bbox's get_signame() */
                         puts(sig == SIGINT || sig == SIGPIPE ? "" : strsignal(sig));
                     }
 #endif
                     /* TODO: if (WCOREDUMP(status)) + " (core dumped)"; */
                     /* MIPS has 128 sigs (1..128), if sig==128,
                      * 128 + sig would result in exitcode 256 -> 0!
                      */
                     ex = 128 | sig;
                 }
                 fg_pipe->cmds[i].cmd_exitcode = ex;
             } else {
                 fg_pipe->stopped_cmds++;
             }
             debug_printf_jobs("fg_pipe: alive_cmds %d stopped_cmds %d\n",
                     fg_pipe->alive_cmds, fg_pipe->stopped_cmds);
             rcode = job_exited_or_stopped(fg_pipe);
             if (rcode >= 0) {
 /* Note: *non-interactive* bash does not continue if all processes in fg pipe
  * are stopped. Testcase: "cat | cat" in a script (not on command line!)
  * and "killall -STOP cat" */
                 if (G_interactive_fd) {
 #if ENABLE_HUSH_JOB
                     if (fg_pipe->alive_cmds != 0)
                         insert_job_into_table(fg_pipe);
 #endif
                     return rcode;
                 }
                 if (fg_pipe->alive_cmds == 0)
                     return rcode;
             }
             /* There are still running processes in the fg_pipe */
             return -1;
         }
         /* It wasn't in fg_pipe, look for process in bg pipes */
     }
 #if ENABLE_HUSH_JOB
     /* We were asked to wait for bg or orphaned children */
     /* No need to remember exitcode in this case */
     for (pi = G.job_list; pi; pi = pi->next) {
         for (i = 0; i < pi->num_cmds; i++) {
             if (pi->cmds[i].pid == childpid)
                 goto found_pi_and_prognum;
         }
     }
     /* Happens when shell is used as init process (init=/bin/sh) */
     debug_printf("checkjobs: pid %d was not in our list!\n", childpid);
     return -1; /* this wasn't a process from fg_pipe */
  found_pi_and_prognum:
     if (dead) {
         /* child exited */
         int rcode = WEXITSTATUS(status);
         if (WIFSIGNALED(status))
             /* NB: not 128 + sig, MIPS has sig 128 */
             rcode = 128 | WTERMSIG(status);
         pi->cmds[i].cmd_exitcode = rcode;
         if (G.last_bg_pid == pi->cmds[i].pid)
             G.last_bg_pid_exitcode = rcode;
         pi->cmds[i].pid = 0;
         pi->alive_cmds--;
         if (!pi->alive_cmds) {
 # if ENABLE_HUSH_BASH_COMPAT
             G.dead_job_exitcode = job_exited_or_stopped(pi);
 # endif
             if (G_interactive_fd) {
                 printf(JOB_STATUS_FORMAT, pi->jobid,
                         "Done", pi->cmdtext);
                 delete_finished_job(pi);
             } else {
 /*
  * bash deletes finished jobs from job table only in interactive mode,
  * after "jobs" cmd, or if pid of a new process matches one of the old ones
  * (see cleanup_dead_jobs(), delete_old_job(), J_NOTIFIED in bash source).
  * Testcase script: "(exit 3) & sleep 1; wait %1; echo $?" prints 3 in bash.
  * We only retain one "dead" job, if it's the single job on the list.
  * This covers most of real-world scenarios where this is useful.
  */
                 if (pi != G.job_list)
                     delete_finished_job(pi);
             }
         }
     } else {
         /* child stopped */
         pi->stopped_cmds++;
     }
 #endif
     return -1; /* this wasn't a process from fg_pipe */
 }
References pipe::alive_cmds, command::cmd_exitcode, pipe::cmds, debug_printf, debug_printf_jobs, G, G_interactive_fd, i, job_exited_or_stopped(), JOB_STATUS_FORMAT, pipe::num_cmds, pi, command::pid, printf(), puts(), SIGINT, SIGPIPE, status, pipe::stopped_cmds, strsignal(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, WIFSTOPPED, WSTOPSIG, and WTERMSIG.
Referenced by checkjobs().
pseudo_exec()
static void pseudo_exec (nommu_save_t * nommu_save, struct command * command, char ** argv_expanded) static
Definition at line 8759 of file hush.c.
 {
 #if ENABLE_HUSH_FUNCTIONS
     if (command->cmd_type == CMD_FUNCDEF) {
         /* Ignore funcdefs in pipes:
          * true | f() { cmd }
          */
         _exit(0);
     }
 #endif
     if (command->argv) {
         pseudo_exec_argv(nommu_save, command->argv,
                 command->assignment_cnt, argv_expanded);
     }
     if (command->group) {
         /* Cases when we are here:
          * ( list )
          * { list } &
          * ... | ( list ) | ...
          * ... | { list } | ...
          */
 #if BB_MMU
         int rcode;
         debug_printf_exec("pseudo_exec: run_list\n");
         reset_traps_to_defaults();
         rcode = run_list(command->group);
         /* OK to leak memory by not calling free_pipe_list,
          * since this process is about to exit */
         _exit(rcode);
 #else
         re_execute_shell(&nommu_save->argv_from_re_execing,
                 command->group_as_string,
                 G.global_argv[0],
                 G.global_argv + 1,
                 NULL);
 #endif
     }
     /* Case when we are here: ... | >file */
     debug_printf_exec("pseudo_exec'ed null command\n");
     _exit_SUCCESS();
 }
References _exit(), _exit_SUCCESS(), command::argv, nommu_save_t::argv_from_re_execing, command::assignment_cnt, command::cmd_type, debug_printf_exec, G, command::group, command::group_as_string, NULL, pseudo_exec_argv(), re_execute_shell(), and run_list().
Referenced by run_pipe().
pseudo_exec_argv()
static NOINLINE void pseudo_exec_argv (nommu_save_t * nommu_save, char ** argv, int assignment_cnt, char ** argv_expanded) static
Definition at line 8603 of file hush.c.
 {
     const struct built_in_command *x;
     struct variable **sv_shadowed;
     char **new_env;
     IF_HUSH_COMMAND(char opt_vV = 0;)
     IF_HUSH_FUNCTIONS(const struct function *funcp;)
     new_env = expand_assignments(argv, assignment_cnt);
     dump_cmd_in_x_mode(new_env);
     if (!argv[assignment_cnt]) {
         /* Case when we are here: ... | var=val | ...
          * (note that we do not exit early, i.e., do not optimize out
          * expand_assignments(): think about ... | var=`sleep 1` | ...
          */
         free_strings(new_env);
         _exit_SUCCESS();
     }
     sv_shadowed = G.shadowed_vars_pp;
 #if BB_MMU
     G.shadowed_vars_pp = NULL; /* "don't save, free them instead" */
 #else
     G.shadowed_vars_pp = &nommu_save->old_vars;
     G.var_nest_level++;
 #endif
     set_vars_and_save_old(new_env);
     G.shadowed_vars_pp = sv_shadowed;
     if (argv_expanded) {
         argv = argv_expanded;
     } else {
         argv = expand_strvec_to_strvec(argv + assignment_cnt);
 #if !BB_MMU
         nommu_save->argv = argv;
 #endif
     }
     dump_cmd_in_x_mode(argv);
 #if ENABLE_FEATURE_SH_STANDALONE || BB_MMU
     if (strchr(argv[0], '/') != NULL)
         goto skip;
 #endif
 #if ENABLE_HUSH_FUNCTIONS
     /* Check if the command matches any functions (this goes before bltins) */
     funcp = find_function(argv[0]);
     if (funcp)
         exec_function(&nommu_save->argv_from_re_execing, funcp, argv);
 #endif
 #if ENABLE_HUSH_COMMAND
     /* "command BAR": run BAR without looking it up among functions
      * "command -v BAR": print "BAR" or "/path/to/BAR"; or exit 1
      * "command -V BAR": print "BAR is {a function,a shell builtin,/path/to/BAR}"
      */
     while (strcmp(argv[0], "command") == 0 && argv[1]) {
         char *p;
         argv++;
         p = *argv;
         if (p[0] != '-' || !p[1])
             continue; /* bash allows "command command command [-OPT] BAR" */
         for (;;) {
             p++;
             switch (*p) {
             case '\0':
                 argv++;
                 p = *argv;
                 if (p[0] != '-' || !p[1])
                     goto after_opts;
                 continue; /* next arg is also -opts, process it too */
             case 'v':
             case 'V':
                 opt_vV = *p;
                 continue;
             default:
                 bb_error_msg_and_die("%s: %s: invalid option", "command", argv[0]);
             }
         }
     }
  after_opts:
 # if ENABLE_HUSH_FUNCTIONS
     if (opt_vV && find_function(argv[0]))
         if_command_vV_print_and_exit(opt_vV, argv[0], "a function");
 # endif
 #endif
     /* Check if the command matches any of the builtins.
      * Depending on context, this might be redundant.  But it's
      * easier to waste a few CPU cycles than it is to figure out
      * if this is one of those cases.
      */
     /* Why "BB_MMU ? :" difference in logic? -
      * On NOMMU, it is more expensive to re-execute shell
      * just in order to run echo or test builtin.
      * It's better to skip it here and run corresponding
      * non-builtin later. */
     x = BB_MMU ? find_builtin(argv[0]) : find_builtin1(argv[0]);
     if (x) {
         if_command_vV_print_and_exit(opt_vV, argv[0], "a shell builtin");
         exec_builtin(&nommu_save->argv_from_re_execing, x, argv);
     }
 #if ENABLE_FEATURE_SH_STANDALONE
     /* Check if the command matches any busybox applets */
     {
         int a = find_applet_by_name(argv[0]);
         if (a >= 0) {
             if_command_vV_print_and_exit(opt_vV, argv[0], "an applet");
 # if BB_MMU /* see above why on NOMMU it is not allowed */
             if (APPLET_IS_NOEXEC(a)) {
                 /* Do not leak open fds from opened script files etc.
                  * Testcase: interactive "ls -l /proc/self/fd"
                  * should not show tty fd open.
                  */
                 close_saved_fds_and_FILE_fds();
 //FIXME: should also close saved redir fds
 //This casuses test failures in
 //redir_children_should_not_see_saved_fd_2.tests
 //redir_children_should_not_see_saved_fd_3.tests
 //if you replace "busybox find" with just "find" in them
                 /* Without this, "rm -i FILE" can't be ^C'ed: */
                 switch_off_special_sigs(G.special_sig_mask);
                 debug_printf_exec("running applet '%s'\n", argv[0]);
                 run_noexec_applet_and_exit(a, argv[0], argv);
             }
 # endif
             /* Re-exec ourselves */
             debug_printf_exec("re-execing applet '%s'\n", argv[0]);
             /* Don't propagate SIG_IGN to the child */
             if (SPECIAL_JOBSTOP_SIGS != 0)
                 switch_off_special_sigs(G.special_sig_mask & SPECIAL_JOBSTOP_SIGS);
             execv(bb_busybox_exec_path, argv);
             /* If they called chroot or otherwise made the binary no longer
              * executable, fall through */
         }
     }
 #endif
 #if ENABLE_FEATURE_SH_STANDALONE || BB_MMU
  skip:
 #endif
     if_command_vV_print_and_exit(opt_vV, argv[0], NULL);
     execvp_or_die(argv);
 }
References _exit_SUCCESS(), APPLET_IS_NOEXEC, argv, nommu_save_t::argv, nommu_save_t::argv_from_re_execing, bb_error_msg_and_die(), BB_MMU, debug_printf_exec, dump_cmd_in_x_mode, exec_builtin, execv(), execvp_or_die(), expand_assignments(), expand_strvec_to_strvec(), find_applet_by_name(), find_builtin(), find_builtin1(), find_function(), free_strings(), G, if_command_vV_print_and_exit, new_env(), NULL, nommu_save_t::old_vars, p, run_noexec_applet_and_exit(), set_vars_and_save_old(), skip, SPECIAL_JOBSTOP_SIGS, strchr(), strcmp, switch_off_special_sigs(), and x.
Referenced by pseudo_exec().
re_execute_shell()
static void re_execute_shell (char *** to_free, const char * s, char * g_argv0, char ** g_argv, char ** builtin_argv) static
Definition at line 7394 of file hush.c.
 {
 # define NOMMU_HACK_FMT ("-$%x:%x:%x:%x:%x:%llx" IF_HUSH_LOOPS(":%x"))
     /* delims + 2 * (number of bytes in printed hex numbers) */
     char param_buf[sizeof(NOMMU_HACK_FMT) + 2 * (sizeof(int)*6 + sizeof(long long)*1)];
     char *heredoc_argv[4];
     struct variable *cur;
 # if ENABLE_HUSH_FUNCTIONS
     struct function *funcp;
 # endif
     char **argv, **pp;
     unsigned cnt;
     unsigned long long empty_trap_mask;
     if (!g_argv0) { /* heredoc */
         argv = heredoc_argv;
         argv[0] = (char *) G.argv0_for_re_execing;
         argv[1] = (char *) "-<";
         argv[2] = (char *) s;
         argv[3] = NULL;
         pp = &argv[3]; /* used as pointer to empty environment */
         goto do_exec;
     }
     cnt = 0;
     pp = builtin_argv;
     if (pp) while (*pp++)
         cnt++;
     empty_trap_mask = 0;
     if (G_traps) {
         int sig;
         for (sig = 1; sig < NSIG; sig++) {
             if (G_traps[sig] && !G_traps[sig][0])
                 empty_trap_mask |= 1LL << sig;
         }
     }
     sprintf(param_buf, NOMMU_HACK_FMT
             , (unsigned) G.root_pid
             , (unsigned) G.root_ppid
             , (unsigned) G.last_bg_pid
             , (unsigned) G.last_exitcode
             , cnt
             , empty_trap_mask
             IF_HUSH_LOOPS(, G.depth_of_loop)
             );
 # undef NOMMU_HACK_FMT
     /* 1:hush 2:-$<pid>:<pid>:<exitcode>:<etc...> <vars...> <funcs...>
      * 3:-c 4:<cmd> 5:<arg0> <argN...> 6:NULL
      */
     cnt += 6;
     for (cur = G.top_var; cur; cur = cur->next) {
         if (!cur->flg_export || cur->flg_read_only)
             cnt += 2;
     }
 # if ENABLE_HUSH_FUNCTIONS
     for (funcp = G.top_func; funcp; funcp = funcp->next)
         cnt += 3;
 # endif
     pp = g_argv;
     while (*pp++)
         cnt++;
     *to_free = argv = pp = xzalloc(sizeof(argv[0]) * cnt);
     *pp++ = (char *) G.argv0_for_re_execing;
     *pp++ = param_buf;
     for (cur = G.top_var; cur; cur = cur->next) {
         if (strcmp(cur->varstr, hush_version_str) == 0)
             continue;
         if (cur->flg_read_only) {
             *pp++ = (char *) "-R";
             *pp++ = cur->varstr;
         } else if (!cur->flg_export) {
             *pp++ = (char *) "-V";
             *pp++ = cur->varstr;
         }
     }
 # if ENABLE_HUSH_FUNCTIONS
     for (funcp = G.top_func; funcp; funcp = funcp->next) {
         *pp++ = (char *) "-F";
         *pp++ = funcp->name;
         *pp++ = funcp->body_as_string;
     }
 # endif
     /* We can pass activated traps here. Say, -Tnn:trap_string
      *
      * However, POSIX says that subshells reset signals with traps
      * to SIG_DFL.
      * I tested bash-3.2 and it not only does that with true subshells
      * of the form ( list ), but with any forked children shells.
      * I set trap "echo W" WINCH; and then tried:
      *
      * { echo 1; sleep 20; echo 2; } &
      * while true; do echo 1; sleep 20; echo 2; break; done &
      * true | { echo 1; sleep 20; echo 2; } | cat
      *
      * In all these cases sending SIGWINCH to the child shell
      * did not run the trap. If I add trap "echo V" WINCH;
      * _inside_ group (just before echo 1), it works.
      *
      * I conclude it means we don't need to pass active traps here.
      */
     *pp++ = (char *) "-c";
     *pp++ = (char *) s;
     if (builtin_argv) {
         while (*++builtin_argv)
             *pp++ = *builtin_argv;
         *pp++ = (char *) "";
     }
     *pp++ = g_argv0;
     while (*g_argv)
         *pp++ = *g_argv++;
     /* *pp = NULL; - is already there */
     pp = environ;
  do_exec:
     debug_printf_exec("re_execute_shell pid:%d cmd:'%s'\n", getpid(), s);
     /* Don't propagate SIG_IGN to the child */
     if (SPECIAL_JOBSTOP_SIGS != 0)
         switch_off_special_sigs(G.special_sig_mask & SPECIAL_JOBSTOP_SIGS);
     execve(bb_busybox_exec_path, argv, pp);
     /* Fallback. Useful for init=/bin/hush usage etc */
     if (argv[0][0] == '/')
         execve(argv[0], argv, pp);
     xfunc_error_retval = 127;
     bb_simple_error_msg_and_die("can't re-execute the shell");
 }
References argv, bb_simple_error_msg_and_die(), cnt, cur, debug_printf_exec, environ, execve(), for(), G, G_traps, getpid(), NOMMU_HACK_FMT, NSIG, NULL, s, SPECIAL_JOBSTOP_SIGS, sprintf(), strcmp, switch_off_special_sigs(), xfunc_error_retval, and xzalloc().
Referenced by exec_builtin(), pseudo_exec(), and setup_heredoc().
record_pending_signo()
static void record_pending_signo (int sig) static
Definition at line 1945 of file hush.c.
 {
     sigaddset(&G.pending_set, sig);
 #if ENABLE_FEATURE_EDITING
     bb_got_signal = sig; /* for read_line_input: "we got a signal" */
 #endif
 #if ENABLE_HUSH_FAST
     if (sig == SIGCHLD) {
         G.count_SIGCHLD++;
 //bb_error_msg("[%d] SIGCHLD_handler: G.count_SIGCHLD:%d G.handled_SIGCHLD:%d", getpid(), G.count_SIGCHLD, G.handled_SIGCHLD);
     }
 #endif
 }
References bb_got_signal, G, sigaddset(), and SIGCHLD.
Referenced by pick_sighandler().
redirect_and_varexp_helper()
static int redirect_and_varexp_helper (struct command * command, struct squirrel ** sqp, char ** argv_expanded) static
Definition at line 9215 of file hush.c.
 {
     /* Assignments occur before redirects. Try:
      * a=`sleep 1` sleep 2 3>/qwe/rty
      */
     char **new_env = expand_assignments(command->argv, command->assignment_cnt);
     dump_cmd_in_x_mode(new_env);
     dump_cmd_in_x_mode(argv_expanded);
     /* this takes ownership of new_env[i] elements, and frees new_env: */
     set_vars_and_save_old(new_env);
     return setup_redirects(command, sqp);
 }
References command::argv, command::assignment_cnt, dump_cmd_in_x_mode, expand_assignments(), new_env(), set_vars_and_save_old(), and setup_redirects().
redirect_opt_num()
static int redirect_opt_num (o_string * o) static
Definition at line 4461 of file hush.c.
 {
     int num;
     if (o->data == NULL)
         return -1;
     num = bb_strtou(o->data, NULL, 10);
     if (errno || num < 0)
         return -1;
     o_reset_to_empty_unquoted(o);
     return num;
 }
References bb_strtou(), o_string::data, errno, NULL, num, and o_reset_to_empty_unquoted().
Referenced by parse_stream().
refill_HFILE_and_getc()
static int refill_HFILE_and_getc (HFILE * fp) static
Definition at line 1646 of file hush.c.
 {
     int n;
     if (fp->fd < 0) {
         /* Already saw EOF */
         return EOF;
     }
 #if ENABLE_HUSH_INTERACTIVE && !ENABLE_FEATURE_EDITING
     /* If user presses ^C, read() restarts after SIGINT (we use SA_RESTART).
      * IOW: ^C will not immediately stop line input.
      * But poll() is different: it does NOT restart after signals.
      */
     if (fp == G.HFILE_stdin) {
         struct pollfd pfd[1];
         pfd[0].fd = fp->fd;
         pfd[0].events = POLLIN;
         n = poll(pfd, 1, -1);
         if (n < 0
          /*&& errno == EINTR - assumed true */
          && sigismember(&G.pending_set, SIGINT)
         ) {
             return '\0';
         }
     }
 #else
 /* if FEATURE_EDITING=y, we do not use this routine for interactive input */
 #endif
     /* Try to buffer more input */
     n = safe_read(fp->fd, fp->buf, sizeof(fp->buf));
     if (n < 0) {
         bb_simple_perror_msg("read error");
         n = 0;
     }
     fp->cur = fp->buf;
     fp->end = fp->buf + n;
     if (n == 0) {
         /* EOF/error */
         close(fp->fd);
         fp->fd = -1;
         return EOF;
     }
     return (unsigned char)(*fp->cur++);
 }
References bb_simple_perror_msg(), HFILE::buf, close(), HFILE::cur, HFILE::end, EOF, HFILE::fd, G, n, pfd, poll(), POLLIN, safe_read(), SIGINT, and sigismember().
Referenced by hfgetc().
reinit_unicode_for_hush()
static void reinit_unicode_for_hush (void) static
Definition at line 2598 of file hush.c.
 {
     /* Unicode support should be activated even if LANG is set
      * _during_ shell execution, not only if it was set when
      * shell was started. Therefore, re-check LANG every time:
      */
     if (ENABLE_FEATURE_CHECK_UNICODE_IN_ENV
      || ENABLE_UNICODE_USING_LOCALE
     ) {
         const char *s = get_local_var_value("LC_ALL");
         if (!s) s = get_local_var_value("LC_CTYPE");
         if (!s) s = get_local_var_value("LANG");
         reinit_unicode(s);
     }
 }
References get_local_var_value(), reinit_unicode, and s.
Referenced by expand_one_var().
remove_nested_vars()
static void remove_nested_vars (void) static
Definition at line 8210 of file hush.c.
 {
     struct variable *cur;
     struct variable **cur_pp;
     cur_pp = &G.top_var;
     while ((cur = *cur_pp) != NULL) {
         if (cur->var_nest_level <= G.var_nest_level) {
             cur_pp = &cur->next;
             continue;
         }
         /* Unexport */
         if (cur->flg_export) {
             debug_printf_env("unexporting nested '%s'/%u\n", cur->varstr, cur->var_nest_level);
             bb_unsetenv(cur->varstr);
         }
         /* Remove from global list */
         *cur_pp = cur->next;
         /* Free */
         if (!cur->max_len) {
             debug_printf_env("freeing nested '%s'/%u\n", cur->varstr, cur->var_nest_level);
             free(cur->varstr);
         }
         free(cur);
     }
 }
References bb_unsetenv(), cur, debug_printf_env, free, G, and NULL.
Referenced by leave_var_nest_level(), and run_pipe().
restore_G_args()
static void restore_G_args (save_arg_t * sv, char ** argv) static
Definition at line 1777 of file hush.c.
 {
 #if ENABLE_HUSH_SET
     if (G.global_args_malloced) {
         /* someone ran "set -- arg1 arg2 ...", undo */
         char **pp = G.global_argv;
         while (*++pp) /* note: does not free $0 */
             free(*pp);
         free(G.global_argv);
     }
 #endif
     argv[0] = sv->sv_argv0;
     G.global_argv = sv->sv_g_argv;
     G.global_argc = sv->sv_g_argc;
     IF_HUSH_SET(G.global_args_malloced = sv->sv_g_malloced;)
 }
References argv, free, G, and sv.
Referenced by builtin_source().
restore_redirects()
static void restore_redirects (struct squirrel * sq) static
Definition at line 7972 of file hush.c.
 {
     if (sq) {
         int i;
         for (i = 0; sq[i].orig_fd >= 0; i++) {
             if (sq[i].moved_to >= 0) {
                 /* We simply die on error */
                 debug_printf_redir("restoring redirected fd from %d to %d\n", sq[i].moved_to, sq[i].orig_fd);
                 xmove_fd(sq[i].moved_to, sq[i].orig_fd);
             } else {
                 /* cmd1 9>FILE; cmd2_should_see_fd9_closed */
                 debug_printf_redir("restoring redirected fd %d: closing it\n", sq[i].orig_fd);
                 close(sq[i].orig_fd);
             }
         }
         free(sq);
     }
     if (G.HFILE_stdin
      && G.HFILE_stdin->fd > STDIN_FILENO
     /* we compare > STDIN, not == STDIN, since hfgetc()
      * closes fd and sets ->fd to -1 if EOF is reached.
      * Testcase: echo 'pwd' | hush
      */
     ) {
         /* Testcase: interactive "read r <FILE; echo $r; read r; echo $r".
          * Redirect moves ->fd to e.g. 10,
          * and it is not restored above (we do not restore script fds
          * after redirects, we just use new, "moved" fds).
          * However for stdin, get_user_input() -> read_line_input(),
          * and read builtin, depend on fd == STDIN_FILENO.
          */
         debug_printf_redir("restoring %d to stdin\n", G.HFILE_stdin->fd);
         xmove_fd(G.HFILE_stdin->fd, STDIN_FILENO);
         G.HFILE_stdin->fd = STDIN_FILENO;
     }
     /* If moved, G_interactive_fd stays on new fd, not restoring it */
 }
References close(), debug_printf_redir, free, G, i, squirrel::moved_to, squirrel::orig_fd, sq(), STDIN_FILENO, and xmove_fd().
Referenced by run_pipe().
restore_ttypgrp_and__exit()
static void restore_ttypgrp_and__exit (void) static
Definition at line 1979 of file hush.c.
 {
     /* xfunc has failed! die die die */
     /* no EXIT traps, this is an escape hatch! */
     G.exiting = 1;
     hush_exit(xfunc_error_retval);
 }
References G, hush_exit(), and xfunc_error_retval.
Referenced by hush_main().
run_and_free_list()
static int run_and_free_list (struct pipe * pi) static
Definition at line 10074 of file hush.c.
 {
     int rcode = 0;
     debug_printf_exec("run_and_free_list entered\n");
     if (!G.o_opt[OPT_O_NOEXEC]) {
         debug_printf_exec(": run_list: 1st pipe with %d cmds\n", pi->num_cmds);
         rcode = run_list(pi);
     }
     /* free_pipe_list has the side effect of clearing memory.
      * In the long run that function can be merged with run_list,
      * but doing that now would hobble the debugging effort. */
     free_pipe_list(pi);
     debug_printf_exec("run_and_free_list return %d\n", rcode);
     return rcode;
 }
References debug_printf_exec, free_pipe_list(), G, OPT_O_NOEXEC, pi, and run_list().
Referenced by parse_and_run_stream().
run_list()
static int run_list (struct pipe * pi) static
Definition at line 9694 of file hush.c.
 {
 #if ENABLE_HUSH_CASE
     char *case_word = NULL;
 #endif
 #if ENABLE_HUSH_LOOPS
     struct pipe *loop_top = NULL;
     char **for_lcur = NULL;
     char **for_list = NULL;
 #endif
     smallint last_followup;
     smalluint rcode;
 #if ENABLE_HUSH_IF || ENABLE_HUSH_CASE
     smalluint cond_code = 0;
 #else
     enum { cond_code = 0 };
 #endif
 #if HAS_KEYWORDS
     smallint rword;      /* RES_foo */
     smallint last_rword; /* ditto */
 #endif
     debug_printf_exec("run_list start lvl %d\n", G.run_list_level);
     debug_enter();
 #if ENABLE_HUSH_LOOPS
     /* Check syntax for "for" */
     {
         struct pipe *cpipe;
         for (cpipe = pi; cpipe; cpipe = cpipe->next) {
             if (cpipe->res_word != RES_FOR && cpipe->res_word != RES_IN)
                 continue;
             /* current word is FOR or IN (BOLD in comments below) */
             if (cpipe->next == NULL) {
                 syntax_error("malformed for");
                 debug_leave();
                 debug_printf_exec("run_list lvl %d return 1\n", G.run_list_level);
                 return 1;
             }
             /* "FOR v; do ..." and "for v IN a b; do..." are ok */
             if (cpipe->next->res_word == RES_DO)
                 continue;
             /* next word is not "do". It must be "in" then ("FOR v in ...") */
             if (cpipe->res_word == RES_IN /* "for v IN a b; not_do..."? */
              || cpipe->next->res_word != RES_IN /* FOR v not_do_and_not_in..."? */
             ) {
                 syntax_error("malformed for");
                 debug_leave();
                 debug_printf_exec("run_list lvl %d return 1\n", G.run_list_level);
                 return 1;
             }
         }
     }
 #endif
     /* Past this point, all code paths should jump to ret: label
      * in order to return, no direct "return" statements please.
      * This helps to ensure that no memory is leaked. */
 #if ENABLE_HUSH_JOB
     G.run_list_level++;
 #endif
 #if HAS_KEYWORDS
     rword = RES_NONE;
     last_rword = RES_XXXX;
 #endif
     last_followup = PIPE_SEQ;
     rcode = G.last_exitcode;
     /* Go through list of pipes, (maybe) executing them. */
     for (; pi; pi = IF_HUSH_LOOPS(rword == RES_DONE ? loop_top : ) pi->next) {
         int r;
         int sv_errexit_depth;
         if (G.flag_SIGINT)
             break;
         if (G_flag_return_in_progress == 1)
             break;
         IF_HAS_KEYWORDS(rword = pi->res_word;)
         debug_printf_exec(": rword=%d cond_code=%d last_rword=%d\n",
                 rword, cond_code, last_rword);
         sv_errexit_depth = G.errexit_depth;
         if (
 #if ENABLE_HUSH_IF
             rword == RES_IF || rword == RES_ELIF ||
 #endif
             pi->followup != PIPE_SEQ
         ) {
             G.errexit_depth++;
         }
 #if ENABLE_HUSH_LOOPS
         if ((rword == RES_WHILE || rword == RES_UNTIL || rword == RES_FOR)
          && loop_top == NULL /* avoid bumping G.depth_of_loop twice */
         ) {
             /* start of a loop: remember where loop starts */
             loop_top = pi;
             G.depth_of_loop++;
         }
 #endif
         /* Still in the same "if...", "then..." or "do..." branch? */
         if (IF_HAS_KEYWORDS(rword == last_rword &&) 1) {
             if ((rcode == 0 && last_followup == PIPE_OR)
              || (rcode != 0 && last_followup == PIPE_AND)
             ) {
                 /* It is "<true> || CMD" or "<false> && CMD"
                  * and we should not execute CMD */
                 debug_printf_exec("skipped cmd because of || or &&\n");
                 last_followup = pi->followup;
                 goto dont_check_jobs_but_continue;
             }
         }
         last_followup = pi->followup;
         IF_HAS_KEYWORDS(last_rword = rword;)
 #if ENABLE_HUSH_IF
         if (cond_code) {
             if (rword == RES_THEN) {
                 /* if false; then ... fi has exitcode 0! */
                 G.last_exitcode = rcode = EXIT_SUCCESS;
                 /* "if <false> THEN cmd": skip cmd */
                 continue;
             }
         } else {
             if (rword == RES_ELSE || rword == RES_ELIF) {
                 /* "if <true> then ... ELSE/ELIF cmd":
                  * skip cmd and all following ones */
                 break;
             }
         }
 #endif
 #if ENABLE_HUSH_LOOPS
         if (rword == RES_FOR) { /* && pi->num_cmds - always == 1 */
             if (!for_lcur) {
                 /* first loop through for */
                 static const char encoded_dollar_at[] ALIGN1 = {
                     SPECIAL_VAR_SYMBOL, '@' | 0x80, SPECIAL_VAR_SYMBOL, '\0'
                 }; /* encoded representation of "$@" */
                 static const char *const encoded_dollar_at_argv[] ALIGN_PTR = {
                     encoded_dollar_at, NULL
                 }; /* argv list with one element: "$@" */
                 char **vals;
                 G.last_exitcode = rcode = EXIT_SUCCESS;
                 vals = (char**)encoded_dollar_at_argv;
                 if (pi->next->res_word == RES_IN) {
                     /* if no variable values after "in" we skip "for" */
                     if (!pi->next->cmds[0].argv) {
                         debug_printf_exec(": null FOR: exitcode EXIT_SUCCESS\n");
                         break;
                     }
                     vals = pi->next->cmds[0].argv;
                 } /* else: "for var; do..." -> assume "$@" list */
                 /* create list of variable values */
                 debug_print_strings("for_list made from", vals);
                 for_list = expand_strvec_to_strvec(vals);
                 for_lcur = for_list;
                 debug_print_strings("for_list", for_list);
             }
             if (!*for_lcur) {
                 /* "for" loop is over, clean up */
                 free(for_list);
                 for_list = NULL;
                 for_lcur = NULL;
                 break;
             }
             /* Insert next value from for_lcur */
             /* note: *for_lcur already has quotes removed, $var expanded, etc */
             set_local_var_from_halves(pi->cmds[0].argv[0], *for_lcur++);
             continue;
         }
         if (rword == RES_IN) {
             continue; /* "for v IN list;..." - "in" has no cmds anyway */
         }
         if (rword == RES_DONE) {
             continue; /* "done" has no cmds too */
         }
 #endif
 #if ENABLE_HUSH_CASE
         if (rword == RES_CASE) {
             debug_printf_exec("CASE cond_code:%d\n", cond_code);
             case_word = expand_string_to_string(pi->cmds->argv[0],
                 EXP_FLAG_ESC_GLOB_CHARS, /*unbackslash:*/ 1);
             debug_printf_exec("CASE word1:'%s'\n", case_word);
             //unbackslash(case_word);
             //debug_printf_exec("CASE word2:'%s'\n", case_word);
             continue;
         }
         if (rword == RES_MATCH) {
             char **argv;
             debug_printf_exec("MATCH cond_code:%d\n", cond_code);
             if (!case_word) /* "case ... matched_word) ... WORD)": we executed selected branch, stop */
                 break;
             /* all prev words didn't match, does this one match? */
             argv = pi->cmds->argv;
             while (*argv) {
                 char *pattern;
                 debug_printf_exec("expand_string_to_string('%s')\n", *argv);
                 pattern = expand_string_to_string(*argv,
                         EXP_FLAG_ESC_GLOB_CHARS,
                         /*unbackslash:*/ 0
                 );
                 /* TODO: which FNM_xxx flags to use? */
                 cond_code = (fnmatch(pattern, case_word, /*flags:*/ 0) != 0);
                 debug_printf_exec("fnmatch(pattern:'%s',str:'%s'):%d\n",
                         pattern, case_word, cond_code);
                 free(pattern);
                 if (cond_code == 0) {
                     /* match! we will execute this branch */
                     free(case_word);
                     case_word = NULL; /* make future "word)" stop */
                     break;
                 }
                 argv++;
             }
             continue;
         }
         if (rword == RES_CASE_BODY) { /* inside of a case branch */
             debug_printf_exec("CASE_BODY cond_code:%d\n", cond_code);
             if (cond_code != 0)
                 continue; /* not matched yet, skip this pipe */
         }
         if (rword == RES_ESAC) {
             debug_printf_exec("ESAC cond_code:%d\n", cond_code);
             if (case_word) {
                 /* "case" did not match anything: still set $? (to 0) */
                 G.last_exitcode = rcode = EXIT_SUCCESS;
             }
         }
 #endif
         /* Just pressing <enter> in shell should check for jobs.
          * OTOH, in non-interactive shell this is useless
          * and only leads to extra job checks */
         if (pi->num_cmds == 0) {
             if (G_interactive_fd)
                 goto check_jobs_and_continue;
             continue;
         }
         /* After analyzing all keywords and conditions, we decided
          * to execute this pipe. NB: have to do checkjobs(NULL)
          * after run_pipe to collect any background children,
          * even if list execution is to be stopped. */
         debug_printf_exec(": run_pipe with %d members\n", pi->num_cmds);
 #if ENABLE_HUSH_LOOPS
         G.flag_break_continue = 0;
 #endif
         rcode = r = G.o_opt[OPT_O_NOEXEC] ? 0 : run_pipe(pi);
         /* NB: rcode is a smalluint, r is int */
         if (r != -1) {
             /* We ran a builtin, function, or group.
              * rcode is already known
              * and we don't need to wait for anything. */
             debug_printf_exec(": builtin/func exitcode %d\n", rcode);
             G.last_exitcode = rcode;
             check_and_run_traps();
 #if ENABLE_HUSH_TRAP && ENABLE_HUSH_FUNCTIONS
             rcode = G.last_exitcode; /* "return" in trap can change it, read back */
 #endif
 #if ENABLE_HUSH_LOOPS
             /* Was it "break" or "continue"? */
             if (G.flag_break_continue) {
                 smallint fbc = G.flag_break_continue;
                 /* We might fall into outer *loop*,
                  * don't want to break it too */
                 if (loop_top) {
                     G.depth_break_continue--;
                     if (G.depth_break_continue == 0)
                         G.flag_break_continue = 0;
                     /* else: e.g. "continue 2" should *break* once, *then* continue */
                 } /* else: "while... do... { we are here (innermost list is not a loop!) };...done" */
                 if (G.depth_break_continue != 0 || fbc == BC_BREAK) {
                     checkjobs(NULL, 0 /*(no pid to wait for)*/);
                     break;
                 }
                 /* "continue": simulate end of loop */
                 rword = RES_DONE;
                 continue;
             }
 #endif
             if (G_flag_return_in_progress == 1) {
                 checkjobs(NULL, 0 /*(no pid to wait for)*/);
                 break;
             }
         } else if (pi->followup == PIPE_BG) {
             /* What does bash do with attempts to background builtins? */
             /* even bash 3.2 doesn't do that well with nested bg:
              * try "{ { sleep 10; echo DEEP; } & echo HERE; } &".
              * I'm NOT treating inner &'s as jobs */
 #if ENABLE_HUSH_JOB
             if (G.run_list_level == 1)
                 insert_job_into_table(pi);
 #endif
             /* Last command's pid goes to $! */
             G.last_bg_pid = pi->cmds[pi->num_cmds - 1].pid;
             G.last_bg_pid_exitcode = 0;
             debug_printf_exec(": cmd&: exitcode EXIT_SUCCESS\n");
 /* Check pi->pi_inverted? "! sleep 1 & echo $?": bash says 1. dash and ash say 0 */
             rcode = EXIT_SUCCESS;
             goto check_traps;
         } else {
 #if ENABLE_HUSH_JOB
             if (G.run_list_level == 1 && G_interactive_fd) {
                 /* Waits for completion, then fg's main shell */
                 rcode = checkjobs_and_fg_shell(pi);
                 debug_printf_exec(": checkjobs_and_fg_shell exitcode %d\n", rcode);
                 goto check_traps;
             }
 #endif
             /* This one just waits for completion */
             rcode = checkjobs(pi, 0 /*(no pid to wait for)*/);
             debug_printf_exec(": checkjobs exitcode %d\n", rcode);
  check_traps:
             G.last_exitcode = rcode;
             check_and_run_traps();
 #if ENABLE_HUSH_TRAP && ENABLE_HUSH_FUNCTIONS
             rcode = G.last_exitcode; /* "return" in trap can change it, read back */
 #endif
         }
         /* Handle "set -e" */
         if (rcode != 0 && G.o_opt[OPT_O_ERREXIT]) {
             debug_printf_exec("ERREXIT:1 errexit_depth:%d\n", G.errexit_depth);
             if (G.errexit_depth == 0)
                 hush_exit(rcode);
         }
         G.errexit_depth = sv_errexit_depth;
         /* Analyze how result affects subsequent commands */
 #if ENABLE_HUSH_IF
         if (rword == RES_IF || rword == RES_ELIF)
             cond_code = rcode;
 #endif
  check_jobs_and_continue:
         checkjobs(NULL, 0 /*(no pid to wait for)*/);
  dont_check_jobs_but_continue: ;
 #if ENABLE_HUSH_LOOPS
         /* Beware of "while false; true; do ..."! */
         if (pi->next
          && (pi->next->res_word == RES_DO || pi->next->res_word == RES_DONE)
          /* check for RES_DONE is needed for "while ...; do \n done" case */
         ) {
             if (rword == RES_WHILE) {
                 if (rcode) {
                     /* "while false; do...done" - exitcode 0 */
                     G.last_exitcode = rcode = EXIT_SUCCESS;
                     debug_printf_exec(": while expr is false: breaking (exitcode:EXIT_SUCCESS)\n");
                     break;
                 }
             }
             if (rword == RES_UNTIL) {
                 if (!rcode) {
                     debug_printf_exec(": until expr is true: breaking\n");
                     break;
                 }
             }
         }
 #endif
     } /* for (pi) */
 #if ENABLE_HUSH_JOB
     G.run_list_level--;
 #endif
 #if ENABLE_HUSH_LOOPS
     if (loop_top)
         G.depth_of_loop--;
     free(for_list);
 #endif
 #if ENABLE_HUSH_CASE
     free(case_word);
 #endif
     debug_leave();
     debug_printf_exec("run_list lvl %d return %d\n", G.run_list_level + 1, rcode);
     return rcode;
 }
References ALIGN1, ALIGN_PTR, argv, BC_BREAK, check_and_run_traps(), checkjobs(), debug_enter, debug_leave, debug_print_strings, debug_printf_exec, EXIT_SUCCESS, EXP_FLAG_ESC_GLOB_CHARS, expand_string_to_string, expand_strvec_to_strvec(), fnmatch(), free, G, G_flag_return_in_progress, G_interactive_fd, hush_exit(), IF_HAS_KEYWORDS, pipe::next, NULL, OPT_O_ERREXIT, OPT_O_NOEXEC, pattern, pi, PIPE_AND, PIPE_BG, PIPE_OR, PIPE_SEQ, RES_NONE, RES_XXXX, run_pipe(), set_local_var_from_halves(), SPECIAL_VAR_SYMBOL, and syntax_error.
Referenced by pseudo_exec(), run_and_free_list(), and run_pipe().
run_pipe()
static NOINLINE int run_pipe (struct pipe * pi) static
Definition at line 9232 of file hush.c.
 {
     static const char *const null_ptr = NULL;
     int cmd_no;
     int next_infd;
     struct command *command;
     char **argv_expanded;
     char **argv;
     struct squirrel *squirrel = NULL;
     int rcode;
     debug_printf_exec("run_pipe start: members:%d\n", pi->num_cmds);
     debug_enter();
     /* Testcase: set -- q w e; (IFS='' echo "$*"; IFS=''; echo "$*"); echo "$*"
      * Result should be 3 lines: q w e, qwe, q w e
      */
     if (G.ifs_whitespace != G.ifs)
         free(G.ifs_whitespace);
     G.ifs = get_local_var_value("IFS");
     if (G.ifs) {
         char *p;
         G.ifs_whitespace = (char*)G.ifs;
         p = skip_whitespace(G.ifs);
         if (*p) {
             /* Not all $IFS is whitespace */
             char *d;
             int len = p - G.ifs;
             p = skip_non_whitespace(p);
             G.ifs_whitespace = xmalloc(len + strlen(p) + 1); /* can overestimate */
             d = mempcpy(G.ifs_whitespace, G.ifs, len);
             while (*p) {
                 if (isspace(*p))
                     *d++ = *p;
                 p++;
             }
             *d = '\0';
         }
     } else {
         G.ifs = defifs;
         G.ifs_whitespace = (char*)G.ifs;
     }
     IF_HUSH_JOB(pi->pgrp = -1;)
     pi->stopped_cmds = 0;
     command = &pi->cmds[0];
     argv_expanded = NULL;
     if (pi->num_cmds != 1
      || pi->followup == PIPE_BG
      || command->cmd_type == CMD_SUBSHELL
     ) {
         goto must_fork;
     }
     pi->alive_cmds = 1;
     debug_printf_exec(": group:%p argv:'%s'\n",
         command->group, command->argv ? command->argv[0] : "NONE");
     if (command->group) {
 #if ENABLE_HUSH_FUNCTIONS
         if (command->cmd_type == CMD_FUNCDEF) {
             /* "executing" func () { list } */
             struct function *funcp;
             funcp = new_function(command->argv[0]);
             /* funcp->name is already set to argv[0] */
             funcp->body = command->group;
 # if !BB_MMU
             funcp->body_as_string = command->group_as_string;
             command->group_as_string = NULL;
 # endif
             command->group = NULL;
             command->argv[0] = NULL;
             debug_printf_exec("cmd %p has child func at %p\n", command, funcp);
             funcp->parent_cmd = command;
             command->child_func = funcp;
             debug_printf_exec("run_pipe: return EXIT_SUCCESS\n");
             debug_leave();
             return EXIT_SUCCESS;
         }
 #endif
         /* { list } */
         debug_printf_exec("non-subshell group\n");
         rcode = 1; /* exitcode if redir failed */
         if (setup_redirects(command, &squirrel) == 0) {
             debug_printf_exec(": run_list\n");
 //FIXME: we need to pass squirrel down into run_list()
 //for SH_STANDALONE case, or else this construct:
 // { find /proc/self/fd; true; } >FILE; cmd2
 //has no way of closing saved fd#1 for "find",
 //and in SH_STANDALONE mode, "find" is not execed,
 //therefore CLOEXEC on saved fd does not help.
             rcode = run_list(command->group) & 0xff;
         }
         restore_redirects(squirrel);
         IF_HAS_KEYWORDS(if (pi->pi_inverted) rcode = !rcode;)
         debug_leave();
         debug_printf_exec("run_pipe: return %d\n", rcode);
         return rcode;
     }
     argv = command->argv ? command->argv : (char **) &null_ptr;
     {
         const struct built_in_command *x;
         IF_HUSH_FUNCTIONS(const struct function *funcp;)
         IF_NOT_HUSH_FUNCTIONS(enum { funcp = 0 };)
         struct variable **sv_shadowed;
         struct variable *old_vars;
 #if ENABLE_HUSH_LINENO_VAR
         G.execute_lineno = command->lineno;
 #endif
         if (argv[command->assignment_cnt] == NULL) {
             /* Assignments, but no command.
              * Ensure redirects take effect (that is, create files).
              * Try "a=t >file"
              */
             unsigned i;
             G.expand_exitcode = 0;
  only_assignments:
             rcode = setup_redirects(command, &squirrel);
             restore_redirects(squirrel);
             /* Set shell variables */
             i = 0;
             while (i < command->assignment_cnt) {
                 char *p = expand_string_to_string(argv[i],
                         EXP_FLAG_ESC_GLOB_CHARS,
                         /*unbackslash:*/ 1
                 );
 #if ENABLE_HUSH_MODE_X
                 if (G_x_mode) {
                     char *eq;
                     if (i == 0)
                         x_mode_prefix();
                     x_mode_addchr(' ');
                     eq = strchrnul(p, '=');
                     if (*eq) eq++;
                     x_mode_addblock(p, (eq - p));
                     x_mode_print_optionally_squoted(eq);
                     x_mode_flush();
                 }
 #endif
                 debug_printf_env("set shell var:'%s'->'%s'\n", *argv, p);
                 if (set_local_var0(p)) {
                     /* assignment to readonly var / putenv error? */
                     rcode = 1;
                 }
                 i++;
             }
             /* Redirect error sets $? to 1. Otherwise,
              * if evaluating assignment value set $?, retain it.
              * Else, clear $?:
              *  false; q=`exit 2`; echo $? - should print 2
              *  false; x=1; echo $? - should print 0
              * Because of the 2nd case, we can't just use G.last_exitcode.
              */
             if (rcode == 0)
                 rcode = G.expand_exitcode;
             IF_HAS_KEYWORDS(if (pi->pi_inverted) rcode = !rcode;)
             debug_leave();
             debug_printf_exec("run_pipe: return %d\n", rcode);
             return rcode;
         }
         /* Expand the rest into (possibly) many strings each */
 #if defined(CMD_TEST2_SINGLEWORD_NOGLOB)
         if (command->cmd_type == CMD_TEST2_SINGLEWORD_NOGLOB)
             argv_expanded = expand_strvec_to_strvec_singleword_noglob(argv + command->assignment_cnt);
         else
 #endif
 #if defined(CMD_SINGLEWORD_NOGLOB)
         if (command->cmd_type == CMD_SINGLEWORD_NOGLOB)
             argv_expanded = expand_strvec_to_strvec_singleword_noglob(argv + command->assignment_cnt);
         else
 #endif
             argv_expanded = expand_strvec_to_strvec(argv + command->assignment_cnt);
         /* If someone gives us an empty string: `cmd with empty output` */
         if (!argv_expanded[0]) {
             free(argv_expanded);
             /* `false` still has to set exitcode 1 */
             G.expand_exitcode = G.last_exitcode;
             goto only_assignments;
         }
         old_vars = NULL;
         sv_shadowed = G.shadowed_vars_pp;
         /* Check if argv[0] matches any functions (this goes before bltins) */
         IF_HUSH_FUNCTIONS(funcp = find_function(argv_expanded[0]);)
         IF_HUSH_FUNCTIONS(x = NULL;)
         IF_HUSH_FUNCTIONS(if (!funcp))
             x = find_builtin(argv_expanded[0]);
         if (x || funcp) {
             if (x && x->b_function == builtin_exec && argv_expanded[1] == NULL) {
                 debug_printf("exec with redirects only\n");
                 /*
                  * Variable assignments are executed, but then "forgotten":
                  *  a=`sleep 1;echo A` exec 3>&-; echo $a
                  * sleeps, but prints nothing.
                  */
                 enter_var_nest_level();
                 G.shadowed_vars_pp = &old_vars;
                 rcode = redirect_and_varexp_helper(command,
                     /*squirrel:*/ ERR_PTR,
                     argv_expanded
                 );
                 G.shadowed_vars_pp = sv_shadowed;
                 /* rcode=1 can be if redir file can't be opened */
                 goto clean_up_and_ret1;
             }
             /* Bump var nesting, or this will leak exported $a:
              * a=b true; env | grep ^a=
              */
             enter_var_nest_level();
             /* Collect all variables "shadowed" by helper
              * (IOW: old vars overridden by "var1=val1 var2=val2 cmd..." syntax)
              * into old_vars list:
              */
             G.shadowed_vars_pp = &old_vars;
             rcode = redirect_and_varexp_helper(command, &squirrel, argv_expanded);
             if (rcode == 0) {
                 if (!funcp) {
                     /* Do not collect *to old_vars list* vars shadowed
                      * by e.g. "local VAR" builtin (collect them
                      * in the previously nested list instead):
                      * don't want them to be restored immediately
                      * after "local" completes.
                      */
                     G.shadowed_vars_pp = sv_shadowed;
                     debug_printf_exec(": builtin '%s' '%s'...\n",
                         x->b_cmd, argv_expanded[1]);
                     fflush_all();
                     rcode = x->b_function(argv_expanded) & 0xff;
                     fflush_all();
                 }
 #if ENABLE_HUSH_FUNCTIONS
                 else {
                     debug_printf_exec(": function '%s' '%s'...\n",
                         funcp->name, argv_expanded[1]);
                     rcode = run_function(funcp, argv_expanded) & 0xff;
                     /*
                      * But do collect *to old_vars list* vars shadowed
                      * within function execution. To that end, restore
                      * this pointer _after_ function run:
                      */
                     G.shadowed_vars_pp = sv_shadowed;
                 }
 #endif
             }
         } else
         if (ENABLE_FEATURE_SH_NOFORK && NUM_APPLETS > 1) {
             int n = find_applet_by_name(argv_expanded[0]);
             if (n < 0 || !APPLET_IS_NOFORK(n))
                 goto must_fork;
             enter_var_nest_level();
             /* Collect all variables "shadowed" by helper into old_vars list */
             G.shadowed_vars_pp = &old_vars;
             rcode = redirect_and_varexp_helper(command, &squirrel, argv_expanded);
             G.shadowed_vars_pp = sv_shadowed;
             if (rcode == 0) {
                 debug_printf_exec(": run_nofork_applet '%s' '%s'...\n",
                     argv_expanded[0], argv_expanded[1]);
                 /*
                  * Note: signals (^C) can't interrupt here.
                  * We remember them and they will be acted upon
                  * after applet returns.
                  * This makes applets which can run for a long time
                  * and/or wait for user input ineligible for NOFORK:
                  * for example, "yes" or "rm" (rm -i waits for input).
                  */
                 rcode = run_nofork_applet(n, argv_expanded);
             }
         } else
             goto must_fork;
         restore_redirects(squirrel);
  clean_up_and_ret1:
         leave_var_nest_level();
         add_vars(old_vars);
         /*
          * Try "usleep 99999999" + ^C + "echo $?"
          * with FEATURE_SH_NOFORK=y.
          */
         if (!funcp) {
             /* It was builtin or nofork.
              * if this would be a real fork/execed program,
              * it should have died if a fatal sig was received.
              * But OTOH, there was no separate process,
              * the sig was sent to _shell_, not to non-existing
              * child.
              * Let's just handle ^C only, this one is obvious:
              * we aren't ok with exitcode 0 when ^C was pressed
              * during builtin/nofork.
              */
             if (sigismember(&G.pending_set, SIGINT))
                 rcode = 128 | SIGINT;
         }
         free(argv_expanded);
         IF_HAS_KEYWORDS(if (pi->pi_inverted) rcode = !rcode;)
         debug_leave();
         debug_printf_exec("run_pipe return %d\n", rcode);
         return rcode;
     }
  must_fork:
     /* NB: argv_expanded may already be created, and that
      * might include `cmd` runs! Do not rerun it! We *must*
      * use argv_expanded if it's non-NULL */
     /* Going to fork a child per each pipe member */
     pi->alive_cmds = 0;
     next_infd = 0;
     cmd_no = 0;
     while (cmd_no < pi->num_cmds) {
         struct fd_pair pipefds;
 #if !BB_MMU
         int sv_var_nest_level = G.var_nest_level;
         volatile nommu_save_t nommu_save;
         nommu_save.old_vars = NULL;
         nommu_save.argv = NULL;
         nommu_save.argv_from_re_execing = NULL;
 #endif
         command = &pi->cmds[cmd_no];
         cmd_no++;
         if (command->argv) {
             debug_printf_exec(": pipe member '%s' '%s'...\n",
                     command->argv[0], command->argv[1]);
         } else {
             debug_printf_exec(": pipe member with no argv\n");
         }
         /* pipes are inserted between pairs of commands */
         pipefds.rd = 0;
         pipefds.wr = 1;
         if (cmd_no < pi->num_cmds)
             xpiped_pair(pipefds);
 #if ENABLE_HUSH_LINENO_VAR
         G.execute_lineno = command->lineno;
 #endif
         command->pid = BB_MMU ? fork() : vfork();
         if (!command->pid) { /* child */
 #if ENABLE_HUSH_JOB
             disable_restore_tty_pgrp_on_exit();
             CLEAR_RANDOM_T(&G.random_gen); /* or else $RANDOM repeats in child */
             /* Every child adds itself to new process group
              * with pgid == pid_of_first_child_in_pipe */
             if (G.run_list_level == 1 && G_interactive_fd) {
                 pid_t pgrp;
                 pgrp = pi->pgrp;
                 if (pgrp < 0) /* true for 1st process only */
                     pgrp = getpid();
                 if (setpgid(0, pgrp) == 0
                  && pi->followup != PIPE_BG
                  && G_saved_tty_pgrp /* we have ctty */
                 ) {
                     /* We do it in *every* child, not just first,
                      * to avoid races */
                     tcsetpgrp(G_interactive_fd, pgrp);
                 }
             }
 #endif
             if (pi->alive_cmds == 0 && pi->followup == PIPE_BG) {
                 /* 1st cmd in backgrounded pipe
                  * should have its stdin /dev/null'ed */
                 close(0);
                 if (open(bb_dev_null, O_RDONLY))
                     xopen("/", O_RDONLY);
             } else {
                 xmove_fd(next_infd, 0);
             }
             xmove_fd(pipefds.wr, 1);
             if (pipefds.rd > 1)
                 close(pipefds.rd);
             /* Like bash, explicit redirects override pipes,
              * and the pipe fd (fd#1) is available for dup'ing:
              * "cmd1 2>&1 | cmd2": fd#1 is duped to fd#2, thus stderr
              * of cmd1 goes into pipe.
              */
             if (setup_redirects(command, NULL)) {
                 /* Happens when redir file can't be opened:
                  * $ hush -c 'echo FOO >&2 | echo BAR 3>/qwe/rty; echo BAZ'
                  * FOO
                  * hush: can't open '/qwe/rty': No such file or directory
                  * BAZ
                  * (echo BAR is not executed, it hits _exit(1) below)
                  */
                 _exit(1);
             }
             /* Stores to nommu_save list of env vars putenv'ed
              * (NOMMU, on MMU we don't need that) */
             /* cast away volatility... */
             pseudo_exec((nommu_save_t*) &nommu_save, command, argv_expanded);
             /* pseudo_exec() does not return */
         }
         /* parent or error */
 #if ENABLE_HUSH_FAST
         G.count_SIGCHLD++;
 //bb_error_msg("[%d] fork in run_pipe: G.count_SIGCHLD:%d G.handled_SIGCHLD:%d", getpid(), G.count_SIGCHLD, G.handled_SIGCHLD);
 #endif
         enable_restore_tty_pgrp_on_exit();
 #if !BB_MMU
         /* Clean up after vforked child */
         free(nommu_save.argv);
         free(nommu_save.argv_from_re_execing);
         G.var_nest_level = sv_var_nest_level;
         remove_nested_vars();
         add_vars(nommu_save.old_vars);
 #endif
         free(argv_expanded);
         argv_expanded = NULL;
         if (command->pid < 0) { /* [v]fork failed */
             /* Clearly indicate, was it fork or vfork */
             bb_simple_perror_msg(BB_MMU ? "vfork"+1 : "vfork");
         } else {
             pi->alive_cmds++;
 #if ENABLE_HUSH_JOB
             /* Second and next children need to know pid of first one */
             if (pi->pgrp < 0)
                 pi->pgrp = command->pid;
 #endif
         }
         if (cmd_no > 1)
             close(next_infd);
         if (cmd_no < pi->num_cmds)
             close(pipefds.wr);
         /* Pass read (output) pipe end to next iteration */
         next_infd = pipefds.rd;
     }
     if (!pi->alive_cmds) {
         debug_leave();
         debug_printf_exec("run_pipe return 1 (all forks failed, no children)\n");
         return 1;
     }
     debug_leave();
     debug_printf_exec("run_pipe return -1 (%u children started)\n", pi->alive_cmds);
     return -1;
 }
References _exit(), add_vars(), APPLET_IS_NOFORK, argv, nommu_save_t::argv, command::argv, nommu_save_t::argv_from_re_execing, command::assignment_cnt, bb_dev_null, BB_MMU, bb_simple_perror_msg(), builtin_exec(), CLEAR_RANDOM_T, close(), CMD_SUBSHELL, command::cmd_type, debug_enter, debug_leave, debug_printf, debug_printf_env, debug_printf_exec, defifs, disable_restore_tty_pgrp_on_exit, enable_restore_tty_pgrp_on_exit, enter_var_nest_level(), ERR_PTR, EXIT_SUCCESS, EXP_FLAG_ESC_GLOB_CHARS, expand_string_to_string, expand_strvec_to_strvec(), fflush_all(), find_applet_by_name(), find_builtin(), find_function(), fork(), free, G, G_interactive_fd, G_saved_tty_pgrp, G_x_mode, get_local_var_value(), getpid(), command::group, command::group_as_string, i, IF_HAS_KEYWORDS, isspace, leave_var_nest_level(), mempcpy(), n, NULL, NUM_APPLETS, O_RDONLY, nommu_save_t::old_vars, open(), p, pi, command::pid, PIPE_BG, pseudo_exec(), fd_pair::rd, redirect_and_varexp_helper, remove_nested_vars(), restore_redirects(), run_list(), run_nofork_applet(), set_local_var0(), setpgid, setup_redirects(), SIGINT, sigismember(), skip_non_whitespace(), skip_whitespace(), strchrnul(), strlen(), tcsetpgrp, vfork(), fd_pair::wr, x, xmalloc, xmove_fd(), xopen(), and xpiped_pair.
Referenced by run_list().
save_and_replace_G_args()
static void save_and_replace_G_args (save_arg_t * sv, char ** argv) static
Definition at line 1763 of file hush.c.
 {
     sv->sv_argv0 = argv[0];
     sv->sv_g_argv = G.global_argv;
     sv->sv_g_argc = G.global_argc;
     IF_HUSH_SET(sv->sv_g_malloced = G.global_args_malloced;)
     argv[0] = G.global_argv[0]; /* retain $0 */
     G.global_argv = argv;
     IF_HUSH_SET(G.global_args_malloced = 0;)
     G.global_argc = 1 + string_array_len(argv + 1);
 }
References argv, G, string_array_len(), and sv.
Referenced by builtin_source().
save_fd_on_redirect()
static int save_fd_on_redirect (int fd, int avoid_fd, struct squirrel ** sqp) static
Definition at line 7903 of file hush.c.
 {
     if (avoid_fd < 9) /* the important case here is that it can be -1 */
         avoid_fd = 9;
 #if ENABLE_HUSH_INTERACTIVE
     if (fd != 0 /* don't trigger for G_interactive_fd == 0 (that's "not interactive" flag) */
      && fd == G_interactive_fd
     ) {
         /* Testcase: "ls -l /proc/$$/fd 255>&-" should work */
         G_interactive_fd = xdup_CLOEXEC_and_close(G_interactive_fd, avoid_fd);
         debug_printf_redir("redirect_fd %d: matches interactive_fd, moving it to %d\n", fd, G_interactive_fd);
         return 1; /* "we closed fd" */
     }
 #endif
     /* Are we called from setup_redirects(squirrel==NULL)
      * in redirect in a [v]forked child?
      */
     if (sqp == NULL) {
         /* No need to move script fds.
          * For NOMMU case, it's actively wrong: we'd change ->fd
          * fields in memory for the parent, but parent's fds
          * aren't moved, it would use wrong fd!
          * Reproducer: "cmd 3>FILE" in script.
          * If we would call move_HFILEs_on_redirect(), child would:
          *  fcntl64(3, F_DUPFD_CLOEXEC, 10)   = 10
          *  close(3)                          = 0
          * and change ->fd to 10 if fd#3 is a script fd. WRONG.
          */
         //bb_error_msg("sqp == NULL: [v]forked child");
         return 0;
     }
     /* If this one of script's fds? */
     if (move_HFILEs_on_redirect(fd, avoid_fd))
         return 1; /* yes. "we closed fd" (actually moved it) */
     /* Are we called for "exec 3>FILE"? Came through
      * redirect_and_varexp_helper(squirrel=ERR_PTR) -> setup_redirects(ERR_PTR)
      * This case used to fail for this script:
      *  exec 3>FILE
      *  echo Ok
      *  ...100000 more lines...
      *  echo Ok
      * as follows:
      *  read(3, "exec 3>FILE\necho Ok\necho Ok"..., 1024) = 1024
      *  open("FILE", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 4
      *  dup2(4, 3)                        = 3
      *  ^^^^^^^^ oops, we lost fd#3 opened to our script!
      *  close(4)                          = 0
      *  write(1, "Ok\n", 3)               = 3
      *  ...                               = 3
      *  write(1, "Ok\n", 3)               = 3
      *  read(3, 0x94fbc08, 1024)          = -1 EBADF (Bad file descriptor)
      *  ^^^^^^^^ oops, wrong fd!!!
      * With this case separate from sqp == NULL and *after* move_HFILEs,
      * it now works:
      */
     if (sqp == ERR_PTR) {
         /* Don't preserve redirected fds: exec is _meant_ to change these */
         //bb_error_msg("sqp == ERR_PTR: exec >FILE");
         return 0;
     }
     /* Check whether it collides with any open fds (e.g. stdio), save fds as needed */
     *sqp = add_squirrel(*sqp, fd, avoid_fd);
     return 0; /* "we did not close fd" */
 }
References add_squirrel(), debug_printf_redir, ERR_PTR, fd, G_interactive_fd, move_HFILEs_on_redirect(), NULL, and xdup_CLOEXEC_and_close().
Referenced by setup_redirects().
set_local_var()
static int set_local_var (char * str, unsigned flags) static
Definition at line 2322 of file hush.c.
 {
     struct variable **cur_pp;
     struct variable *cur;
     char *free_me = NULL;
     char *eq_sign;
     int name_len;
     int retval;
     unsigned local_lvl = (flags >> SETFLAG_VARLVL_SHIFT);
     eq_sign = strchr(str, '=');
     if (HUSH_DEBUG && !eq_sign)
         bb_simple_error_msg_and_die("BUG in setvar");
     name_len = eq_sign - str + 1; /* including '=' */
     cur_pp = &G.top_var;
     while ((cur = *cur_pp) != NULL) {
         if (strncmp(cur->varstr, str, name_len) != 0) {
             cur_pp = &cur->next;
             continue;
         }
         /* We found an existing var with this name */
         if (cur->flg_read_only) {
             bb_error_msg("%s: readonly variable", str);
             free(str);
 //NOTE: in bash, assignment in "export READONLY_VAR=Z" fails, and sets $?=1,
 //but export per se succeeds (does put the var in env). We don't mimic that.
             return -1;
         }
         if (flags & SETFLAG_UNEXPORT) { // && cur->flg_export ?
             debug_printf_env("%s: unsetenv '%s'\n", __func__, str);
             *eq_sign = '\0';
             unsetenv(str);
             *eq_sign = '=';
         }
         if (cur->var_nest_level < local_lvl) {
             /* bash 3.2.33(1) and exported vars:
              * # export z=z
              * # f() { local z=a; env | grep ^z; }
              * # f
              * z=a
              * # env | grep ^z
              * z=z
              */
             if (cur->flg_export)
                 flags |= SETFLAG_EXPORT;
             /* New variable is local ("local VAR=VAL" or
              * "VAR=VAL cmd")
              * and existing one is global, or local
              * on a lower level that new one.
              * Remove it from global variable list:
              */
             *cur_pp = cur->next;
             if (G.shadowed_vars_pp) {
                 /* Save in "shadowed" list */
                 debug_printf_env("shadowing %s'%s'/%u by '%s'/%u\n",
                     cur->flg_export ? "exported " : "",
                     cur->varstr, cur->var_nest_level, str, local_lvl
                 );
                 cur->next = *G.shadowed_vars_pp;
                 *G.shadowed_vars_pp = cur;
             } else {
                 /* Came from pseudo_exec_argv(), no need to save: delete it */
                 debug_printf_env("shadow-deleting %s'%s'/%u by '%s'/%u\n",
                     cur->flg_export ? "exported " : "",
                     cur->varstr, cur->var_nest_level, str, local_lvl
                 );
                 if (cur->max_len == 0) /* allocated "VAR=VAL"? */
                     free_me = cur->varstr; /* then free it later */
                 free(cur);
             }
             break;
         }
         if (strcmp(cur->varstr + name_len, eq_sign + 1) == 0) {
             debug_printf_env("assignement '%s' does not change anything\n", str);
  free_and_exp:
             free(str);
             goto exp;
         }
         /* Replace the value in the found "struct variable" */
         if (cur->max_len != 0) {
             if (cur->max_len >= strnlen(str, cur->max_len + 1)) {
                 /* This one is from startup env, reuse space */
                 debug_printf_env("reusing startup env for '%s'\n", str);
                 strcpy(cur->varstr, str);
                 goto free_and_exp;
             }
             /* Can't reuse */
             cur->max_len = 0;
             goto set_str_and_exp;
         }
         /* max_len == 0 signifies "malloced" var, which we can
          * (and have to) free. But we can't free(cur->varstr) here:
          * if cur->flg_export is 1, it is in the environment.
          * We should either unsetenv+free, or wait until putenv,
          * then putenv(new)+free(old).
          */
         free_me = cur->varstr;
         goto set_str_and_exp;
     }
     /* Not found or shadowed - create new variable struct */
     debug_printf_env("%s: alloc new var '%s'/%u\n", __func__, str, local_lvl);
     cur = xzalloc(sizeof(*cur));
     cur->var_nest_level = local_lvl;
     cur->next = *cur_pp;
     *cur_pp = cur;
  set_str_and_exp:
     cur->varstr = str;
  exp:
 #if !BB_MMU || ENABLE_HUSH_READONLY
     if (flags & SETFLAG_MAKE_RO) {
         cur->flg_read_only = 1;
     }
 #endif
     if (flags & SETFLAG_EXPORT)
         cur->flg_export = 1;
     retval = 0;
     if (cur->flg_export) {
         if (flags & SETFLAG_UNEXPORT) {
             cur->flg_export = 0;
             /* unsetenv was already done */
         } else {
             debug_printf_env("%s: putenv '%s'/%u\n", __func__, cur->varstr, cur->var_nest_level);
             retval = putenv(cur->varstr);
             /* fall through to "free(free_me)" -
              * only now we can free old exported malloced string
              */
         }
     }
     free(free_me);
     handle_changed_special_names(cur->varstr, name_len - 1);
     return retval;
 }
References bb_error_msg(), bb_simple_error_msg_and_die(), cur, debug_printf_env, exp, flags, free, G, handle_changed_special_names, HUSH_DEBUG, NULL, putenv(), retval, SETFLAG_EXPORT, SETFLAG_MAKE_RO, SETFLAG_UNEXPORT, SETFLAG_VARLVL_SHIFT, str, strchr(), strcmp, strcpy(), strncmp(), strnlen(), unsetenv(), and xzalloc().
Referenced by hush_main(), set_local_var0(), set_pwd_var(), and set_vars_and_save_old().
set_local_var0()
static int set_local_var0 (char * str) static
Definition at line 2463 of file hush.c.
 {
     return set_local_var(str, 0);
 }
References set_local_var(), and str.
Referenced by expand_one_var(), run_pipe(), and set_local_var_from_halves().
set_local_var_from_halves()
static void FAST_FUNC set_local_var_from_halves (const char * name, const char * val) static
Definition at line 2468 of file hush.c.
 {
     char *var = xasprintf("%s=%s", name, val);
     set_local_var0(var);
 }
References variable::name, set_local_var0(), val, and xasprintf().
Referenced by hush_main(), and run_list().
set_mode()
static int set_mode (int state, char mode, const char * o_opt) static
Definition at line 10179 of file hush.c.
 {
     int idx;
     switch (mode) {
     case 'n':
         /* set -n has no effect in interactive shell */
         /* Try: while set -n; do echo $-; done */
         if (!G_interactive_fd)
             G.o_opt[OPT_O_NOEXEC] = state;
         break;
     case 'x':
         IF_HUSH_MODE_X(G_x_mode = state;)
         IF_HUSH_MODE_X(if (G.x_mode_fd <= 0) G.x_mode_fd = dup_CLOEXEC(2, 10);)
         break;
     case 'e':
         G.o_opt[OPT_O_ERREXIT] = state;
         break;
     case 'o':
         if (!o_opt) {
             /* "set -o" or "set +o" without parameter.
              * in bash, set -o produces this output:
              *  pipefail        off
              * and set +o:
              *  set +o pipefail
              * We always use the second form.
              */
             const char *p = o_opt_strings;
             idx = 0;
             while (*p) {
                 printf("set %co %s\n", (G.o_opt[idx] ? '-' : '+'), p);
                 idx++;
                 p += strlen(p) + 1;
             }
             break;
         }
         idx = index_in_strings(o_opt_strings, o_opt);
         if (idx >= 0) {
             G.o_opt[idx] = state;
             break;
         }
         /* fall through to error */
     default:
         return EXIT_FAILURE;
     }
     return EXIT_SUCCESS;
 }
References dup_CLOEXEC(), EXIT_FAILURE, EXIT_SUCCESS, G, G_interactive_fd, G_x_mode, idx, index_in_strings(), OPT_O_ERREXIT, OPT_O_NOEXEC, p, printf(), state, and strlen().
Referenced by hush_main().
set_pwd_var()
static void set_pwd_var (unsigned flag) static
Definition at line 2475 of file hush.c.
 {
     set_local_var(xasprintf("PWD=%s", get_cwd(/*force:*/ 1)), flag);
 }
References get_cwd(), set_local_var(), and xasprintf().
Referenced by builtin_cd(), and hush_main().
set_vars_and_save_old()
static void set_vars_and_save_old (char ** strings) static
Definition at line 2547 of file hush.c.
 {
     char **s;
     if (!strings)
         return;
     s = strings;
     while (*s) {
         struct variable *var_p;
         struct variable **var_pp;
         char *eq;
         eq = strchr(*s, '=');
         if (HUSH_DEBUG && !eq)
             bb_simple_error_msg_and_die("BUG in varexp4");
         var_pp = get_ptr_to_local_var(*s, eq - *s);
         if (var_pp) {
             var_p = *var_pp;
             if (var_p->flg_read_only) {
                 char **p;
                 bb_error_msg("%s: readonly variable", *s);
                 /*
                  * "VAR=V BLTIN" unsets VARs after BLTIN completes.
                  * If VAR is readonly, leaving it in the list
                  * after asssignment error (msg above)
                  * causes doubled error message later, on unset.
                  */
                 debug_printf_env("removing/freeing '%s' element\n", *s);
                 free(*s);
                 p = s;
                 do { *p = p[1]; p++; } while (*p);
                 goto next;
             }
             /* below, set_local_var() with nest level will
              * "shadow" (remove) this variable from
              * global linked list.
              */
         }
         debug_printf_env("%s: env override '%s'/%u\n", __func__, *s, G.var_nest_level);
         set_local_var(*s, (G.var_nest_level << SETFLAG_VARLVL_SHIFT) | SETFLAG_EXPORT);
         s++;
  next: ;
     }
     free(strings);
 }
References bb_error_msg(), bb_simple_error_msg_and_die(), debug_printf_env, variable::flg_read_only, free, G, get_ptr_to_local_var(), HUSH_DEBUG, next, p, s, set_local_var(), SETFLAG_EXPORT, SETFLAG_VARLVL_SHIFT, strchr(), and strings.
Referenced by pseudo_exec_argv(), and redirect_and_varexp_helper().
setup_file_in_str()
static void setup_file_in_str (struct in_str * i, HFILE * fp) static
Definition at line 2938 of file hush.c.
 {
     memset(i, 0, sizeof(*i));
     i->file = fp;
     /* i->p = NULL; */
 }
References i, and memset().
Referenced by parse_and_run_file().
setup_heredoc()
static void setup_heredoc (struct redir_struct * redir) static
Definition at line 7749 of file hush.c.
 {
     struct fd_pair pair;
     pid_t pid;
     int len, written;
     /* the _body_ of heredoc (misleading field name) */
     const char *heredoc = redir->rd_filename;
     char *expanded;
 #if !BB_MMU
     char **to_free;
 #endif
     expanded = NULL;
     if (!(redir->rd_dup & HEREDOC_QUOTED)) {
         expanded = encode_then_expand_string(heredoc);
         if (expanded)
             heredoc = expanded;
     }
     len = strlen(heredoc);
     close(redir->rd_fd); /* often saves dup2+close in xmove_fd */
     xpiped_pair(pair);
     xmove_fd(pair.rd, redir->rd_fd);
     /* Try writing without forking. Newer kernels have
      * dynamically growing pipes. Must use non-blocking write! */
     ndelay_on(pair.wr);
     while (1) {
         written = write(pair.wr, heredoc, len);
         if (written <= 0)
             break;
         len -= written;
         if (len == 0) {
             close(pair.wr);
             free(expanded);
             return;
         }
         heredoc += written;
     }
     ndelay_off(pair.wr);
     /* Okay, pipe buffer was not big enough */
     /* Note: we must not create a stray child (bastard? :)
      * for the unsuspecting parent process. Child creates a grandchild
      * and exits before parent execs the process which consumes heredoc
      * (that exec happens after we return from this function) */
 #if !BB_MMU
     to_free = NULL;
 #endif
     pid = xvfork();
     if (pid == 0) {
         /* child */
         disable_restore_tty_pgrp_on_exit();
         pid = BB_MMU ? xfork() : xvfork();
         if (pid != 0)
             _exit(0);
         /* grandchild */
         close(redir->rd_fd); /* read side of the pipe */
 #if BB_MMU
         full_write(pair.wr, heredoc, len); /* may loop or block */
         _exit(0);
 #else
         /* Delegate blocking writes to another process */
         xmove_fd(pair.wr, STDOUT_FILENO);
         re_execute_shell(&to_free, heredoc, NULL, NULL, NULL);
 #endif
     }
     /* parent */
 #if ENABLE_HUSH_FAST
     G.count_SIGCHLD++;
 //bb_error_msg("[%d] fork in setup_heredoc: G.count_SIGCHLD:%d G.handled_SIGCHLD:%d", getpid(), G.count_SIGCHLD, G.handled_SIGCHLD);
 #endif
     enable_restore_tty_pgrp_on_exit();
 #if !BB_MMU
     free(to_free);
 #endif
     close(pair.wr);
     free(expanded);
     wait(NULL); /* wait till child has died */
 }
References _exit(), BB_MMU, close(), disable_restore_tty_pgrp_on_exit, enable_restore_tty_pgrp_on_exit, encode_then_expand_string(), free, full_write(), G, HEREDOC_QUOTED, ndelay_off(), ndelay_on(), NULL, pid, fd_pair::rd, re_execute_shell(), redir, STDOUT_FILENO, strlen(), wait(), fd_pair::wr, write(), xfork(), xmove_fd(), xpiped_pair, and xvfork.
Referenced by setup_redirects().
setup_redirects()
static int setup_redirects (struct command * prog, struct squirrel ** sqp) static
Definition at line 8041 of file hush.c.
 {
     struct redir_struct *redir;
     for (redir = prog->redirects; redir; redir = redir->next) {
         int newfd;
         int closed;
         if (redir->rd_type == REDIRECT_HEREDOC2) {
             /* "rd_fd<<HERE" case */
             save_fd_on_redirect(redir->rd_fd, /*avoid:*/ 0, sqp);
             /* for REDIRECT_HEREDOC2, rd_filename holds _contents_
              * of the heredoc */
             debug_printf_redir("set heredoc '%s'\n",
                     redir->rd_filename);
             setup_heredoc(redir);
             continue;
         }
         if (redir->rd_dup == REDIRFD_TO_FILE) {
             /* "rd_fd<*>file" case (<*> is <,>,>>,<>) */
             char *p;
             int mode;
             if (redir->rd_filename == NULL) {
                 /* Examples:
                  * "cmd >" (no filename)
                  * "cmd > <file" (2nd redirect starts too early)
                  */
                 syntax_error("invalid redirect");
                 continue;
             }
             mode = redir_table[redir->rd_type].mode;
             p = expand_string_to_string(redir->rd_filename,
                 EXP_FLAG_ESC_GLOB_CHARS, /*unbackslash:*/ 1);
             newfd = open_or_warn(p, mode);
             free(p);
             if (newfd < 0) {
                 /* Error message from open_or_warn can be lost
                  * if stderr has been redirected, but bash
                  * and ash both lose it as well
                  * (though zsh doesn't!)
                  */
                 return 1;
             }
             if (newfd == redir->rd_fd && sqp) {
                 /* open() gave us precisely the fd we wanted.
                  * This means that this fd was not busy
                  * (not opened to anywhere).
                  * Remember to close it on restore:
                  */
                 *sqp = add_squirrel_closed(*sqp, newfd);
                 debug_printf_redir("redir to previously closed fd %d\n", newfd);
             }
         } else {
             /* "rd_fd>&rd_dup" or "rd_fd>&-" case */
             newfd = redir->rd_dup;
         }
         if (newfd == redir->rd_fd)
             continue;
         /* if "N>FILE": move newfd to redir->rd_fd */
         /* if "N>&M": dup newfd to redir->rd_fd */
         /* if "N>&-": close redir->rd_fd (newfd is REDIRFD_CLOSE) */
         closed = save_fd_on_redirect(redir->rd_fd, /*avoid:*/ newfd, sqp);
         if (newfd == REDIRFD_CLOSE) {
             /* "N>&-" means "close me" */
             if (!closed) {
                 /* ^^^ optimization: saving may already
                  * have closed it. If not... */
                 close(redir->rd_fd);
             }
             /* Sometimes we do another close on restore, getting EBADF.
              * Consider "echo 3>FILE 3>&-"
              * first redirect remembers "need to close 3",
              * and second redirect closes 3! Restore code then closes 3 again.
              */
         } else {
             /* if newfd is a script fd or saved fd, simulate EBADF */
             if (internally_opened_fd(newfd, sqp && sqp != ERR_PTR ? *sqp : NULL)) {
                 //errno = EBADF;
                 //bb_perror_msg_and_die("can't duplicate file descriptor");
                 newfd = -1; /* same effect as code above */
             }
             xdup2(newfd, redir->rd_fd);
             if (redir->rd_dup == REDIRFD_TO_FILE)
                 /* "rd_fd > FILE" */
                 close(newfd);
             /* else: "rd_fd > rd_dup" */
         }
     }
     return 0;
 }
References add_squirrel_closed(), close(), debug_printf_redir, ERR_PTR, EXP_FLAG_ESC_GLOB_CHARS, expand_string_to_string, free, internally_opened_fd(), NULL, open_or_warn(), p, prog, redir, REDIRECT_HEREDOC2, REDIRFD_CLOSE, REDIRFD_TO_FILE, save_fd_on_redirect(), setup_heredoc(), syntax_error, and xdup2().
Referenced by redirect_and_varexp_helper(), and run_pipe().
setup_string_in_str()
static void setup_string_in_str (struct in_str * i, const char * s) static
Definition at line 2945 of file hush.c.
 {
     memset(i, 0, sizeof(*i));
     /*i->file = NULL */;
     i->p = s;
 }
References i, memset(), and s.
Referenced by encode_then_append_var_plusminus(), encode_then_expand_string(), encode_then_expand_vararg(), and parse_and_run_string().
skip_dash_dash()
static char** skip_dash_dash (char ** argv) static
Definition at line 10815 of file hush.c.
 {
     argv++;
     if (argv[0] && argv[0][0] == '-' && argv[0][1] == '-' && argv[0][2] == '\0')
         argv++;
     return argv;
 }
References argv.
Referenced by builtin_cd(), builtin_eval(), builtin_exec(), builtin_exit(), builtin_shift(), and builtin_source().
switch_off_special_sigs()
static void switch_off_special_sigs (unsigned mask) static
Definition at line 7315 of file hush.c.
 {
     unsigned sig = 0;
     while ((mask >>= 1) != 0) {
         sig++;
         if (!(mask & 1))
             continue;
 #if ENABLE_HUSH_TRAP
         if (G_traps) {
             if (G_traps[sig] && !G_traps[sig][0])
                 /* trap is '', has to remain SIG_IGN */
                 continue;
             free(G_traps[sig]);
             G_traps[sig] = NULL;
         }
 #endif
         /* We are here only if no trap or trap was not '' */
         install_sighandler(sig, SIG_DFL);
     }
 }
References free, G_traps, install_sighandler(), NULL, and SIG_DFL.
Referenced by execvp_or_die(), pseudo_exec_argv(), and re_execute_shell().
syntax_error()
static void syntax_error (unsigned lineno UNUSED_PARAM, const char * msg) static
Definition at line 1413 of file hush.c.
 {
     if (msg)
         bb_error_msg("syntax error: %s", msg);
     else
         bb_simple_error_msg("syntax error");
     die_if_script();
 }
References bb_error_msg(), bb_simple_error_msg(), and die_if_script().
syntax_error_at()
static void syntax_error_at (unsigned lineno UNUSED_PARAM, const char * msg) static
Definition at line 1422 of file hush.c.
 {
     bb_error_msg("syntax error at '%s'", msg);
     die_if_script();
 }
References bb_error_msg(), and die_if_script().
syntax_error_unexpected_ch()
static void syntax_error_unexpected_ch (unsigned lineno UNUSED_PARAM, int ch) static
Definition at line 1441 of file hush.c.
 {
     char msg[2];
     msg[0] = ch;
     msg[1] = '\0';
 #if HUSH_DEBUG >= 2
     bb_error_msg("hush.c:%u", lineno);
 #endif
     bb_error_msg("syntax error: unexpected %s", ch == EOF ? "EOF" : msg);
     die_if_script();
 }
References bb_error_msg(), die_if_script(), EOF, and lineno.
syntax_error_unterm_ch()
static void syntax_error_unterm_ch (unsigned lineno, char ch) static
Definition at line 1435 of file hush.c.
 {
     char msg[2] = { ch, '\0' };
     syntax_error_unterm_str(lineno, msg);
 }
References lineno, and syntax_error_unterm_str.
syntax_error_unterm_str()
static void syntax_error_unterm_str (unsigned lineno UNUSED_PARAM, const char * s) static
Definition at line 1428 of file hush.c.
 {
     bb_error_msg("syntax error: unterminated %s", s);
 //? source4.tests fails: in bash, echo ${^} in script does not terminate the script
 //  die_if_script();
 }
References bb_error_msg(), and s.
unbackslash()
static char* unbackslash (char * src) static
Definition at line 1473 of file hush.c.
 {
     char *dst = src = strchrnul(src, '\\');
     while (1) {
         if (*src == '\\') {
             src++;
             if (*src != '\0') {
                 /* \x -> x */
                 *dst++ = *src++;
                 continue;
             }
             /* else: "<nul>". Do not delete this backslash.
              * Testcase: eval 'echo ok\'
              */
             *dst++ = '\\';
             /* fallthrough */
         }
         if ((*dst++ = *src++) == '\0')
             break;
     }
     return dst;
 }
References dst, src, and strchrnul().
Referenced by done_word(), expand_string_to_string(), and perform_glob().
xdup_CLOEXEC_and_close()
static int xdup_CLOEXEC_and_close (int fd, int avoid_fd) static
Definition at line 1585 of file hush.c.
 {
     int newfd;
  repeat:
     newfd = fcntl(fd, F_DUPFD_CLOEXEC, avoid_fd + 1);
     if (newfd < 0) {
         if (errno == EBUSY)
             goto repeat;
         if (errno == EINTR)
             goto repeat;
         /* fd was not open? */
         if (errno == EBADF)
             return fd;
         xfunc_die();
     }
     if (F_DUPFD_CLOEXEC == F_DUPFD) /* if old libc (w/o F_DUPFD_CLOEXEC) */
         fcntl(newfd, F_SETFD, FD_CLOEXEC);
     close(fd);
     return newfd;
 }
References close(), EBADF, EBUSY, EINTR, errno, F_DUPFD, F_DUPFD_CLOEXEC, F_SETFD, fcntl(), fd, FD_CLOEXEC, and xfunc_die().
Referenced by move_HFILEs_on_redirect(), and save_fd_on_redirect().
Variable Documentation
ALIGN1
const char o_opt_strings [] ALIGN1 = "HUSH_VERSION="BB_VER static
Definition at line 501 of file hush.c.
Referenced by run_list().
const { ... } ALIGN4[]
Initial value:
= {
    { O_RDONLY,                  0, "<"  },
    { O_CREAT|O_TRUNC|O_WRONLY,  1, ">"  },
    { O_CREAT|O_APPEND|O_WRONLY, 1, ">>" },
    { O_CREAT|O_RDWR,            1, "<>" },
    { O_RDONLY,                  0, "<<" },
}
ALIGN_PTR
const struct built_in_command bltins2 [] ALIGN_PTR static
Definition at line 1145 of file hush.c.
Referenced by run_list().