Fennix: Userspace/apps/base/busybox/networking/ifplugd.c File Reference
ifplugd.c File Reference
#include "libbb.h"
#include "fix_u32.h"
#include <linux/if.h>
#include <linux/mii.h>
#include <linux/ethtool.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/sockios.h>
#include <syslog.h>
#include <linux/wireless.h>
Data Structures
struct globals
Macros
#define __user
#define ETH_ALEN 6
#define IFPLUGD_ENV_PREVIOUS "IFPLUGD_PREVIOUS"
#define IFPLUGD_ENV_CURRENT "IFPLUGD_CURRENT"
#define OPTION_STR "+ansfFi:r:It:+u:+d:+m:pqlx:MA"
#define G (*ptr_to_globals)
#define INIT_G()
Enumerations
enum {
FLAG_NO_AUTO = 1 << 0 , FLAG_NO_DAEMON = 1 << 1 , FLAG_NO_SYSLOG = 1 << 2 , FLAG_IGNORE_FAIL = 1 << 3 ,
FLAG_IGNORE_FAIL_POSITIVE = 1 << 4 , FLAG_IFACE = 1 << 5 , FLAG_RUN = 1 << 6 , FLAG_IGNORE_RETVAL = 1 << 7 ,
FLAG_POLL_TIME = 1 << 8 , FLAG_DELAY_UP = 1 << 9 , FLAG_DELAY_DOWN = 1 << 10 , FLAG_API_MODE = 1 << 11 ,
FLAG_NO_STARTUP = 1 << 12 , FLAG_NO_SHUTDOWN = 1 << 13 , FLAG_INITIAL_DOWN = 1 << 14 , FLAG_EXTRA_ARG = 1 << 15 ,
FLAG_MONITOR = 1 << 16 , FLAG_NO_UP_NEW_IFACE = 1 << 17
}
enum { IFSTATUS_ERR = -1 , IFSTATUS_DOWN = 0 , IFSTATUS_UP = 1 }
enum { ioctl_fd = 3 , netlink_fd = 4 }
enum {
API_ETHTOOL , API_MII , API_PRIVATE , API_WLAN ,
API_IFF , API_AUTO
}
Functions
static void set_ifreq_to_ifname (struct ifreq *ifreq)
static int network_ioctl (int request, void *data, const char *errmsg)
static smallint detect_link_mii (void)
static smallint detect_link_priv (void)
static smallint detect_link_ethtool (void)
static smallint detect_link_iff (void)
static smallint detect_link_wlan (void)
static const char * strstatus (int status)
static int run_script (const char *action)
static void up_iface (void)
static void maybe_up_new_iface (void)
static smallint detect_link (void)
static NOINLINE int check_existence_through_netlink (void)
int ifplugd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char api_modes[] ALIGN1 = "empwia"
struct {
const char * name
smallint(* func)(void)
} ALIGN_PTR []
Macro Definition Documentation
__user
#define __user
Definition at line 68 of file ifplugd.c.
ETH_ALEN
#define ETH_ALEN 6
Definition at line 72 of file ifplugd.c.
G
#define G (*ptr_to_globals)
Definition at line 153 of file ifplugd.c.
IFPLUGD_ENV_CURRENT
#define IFPLUGD_ENV_CURRENT "IFPLUGD_CURRENT"
Definition at line 95 of file ifplugd.c.
IFPLUGD_ENV_PREVIOUS
#define IFPLUGD_ENV_PREVIOUS "IFPLUGD_PREVIOUS"
Definition at line 94 of file ifplugd.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    G.iface_last_status = -1; \
    G.iface_exists   = 1; \
    G.poll_time      = 1; \
    G.delay_down     = 5; \
    G.iface          = "eth0"; \
    G.api_mode       = "a"; \
    G.script_name    = "/etc/ifplugd/ifplugd.action"; \
} while (0)
Definition at line 154 of file ifplugd.c.
OPTION_STR
#define OPTION_STR "+ansfFi:r:It:+u:+d:+m:pqlx:MA"
Definition at line 123 of file ifplugd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FLAG_NO_AUTO
FLAG_NO_DAEMON
FLAG_NO_SYSLOG
FLAG_IGNORE_FAIL
FLAG_IGNORE_FAIL_POSITIVE
FLAG_IFACE
FLAG_RUN
FLAG_IGNORE_RETVAL
FLAG_POLL_TIME
FLAG_DELAY_UP
FLAG_DELAY_DOWN
FLAG_API_MODE
FLAG_NO_STARTUP
FLAG_NO_SHUTDOWN
FLAG_INITIAL_DOWN
FLAG_EXTRA_ARG
FLAG_MONITOR
FLAG_NO_UP_NEW_IFACE
Definition at line 97 of file ifplugd.c.
      {
     FLAG_NO_AUTO            = 1 <<  0, // -a, Don't up interface at each link probe
     FLAG_NO_DAEMON          = 1 <<  1, // -n, Do not daemonize
     FLAG_NO_SYSLOG          = 1 <<  2, // -s, Do not use syslog, use stderr instead
     FLAG_IGNORE_FAIL        = 1 <<  3, // -f, Ignore detection failure, retry instead (failure is treated as DOWN)
     FLAG_IGNORE_FAIL_POSITIVE   = 1 <<  4, // -F, Ignore detection failure, retry instead (failure is treated as UP)
     FLAG_IFACE          = 1 <<  5, // -i, Specify ethernet interface
     FLAG_RUN            = 1 <<  6, // -r, Specify program to execute
     FLAG_IGNORE_RETVAL      = 1 <<  7, // -I, Don't exit on nonzero return value of program executed
     FLAG_POLL_TIME          = 1 <<  8, // -t, Specify poll time in seconds
     FLAG_DELAY_UP           = 1 <<  9, // -u, Specify delay for configuring interface
     FLAG_DELAY_DOWN         = 1 << 10, // -d, Specify delay for deconfiguring interface
     FLAG_API_MODE           = 1 << 11, // -m, Force API mode (mii, priv, ethtool, wlan, auto)
     FLAG_NO_STARTUP         = 1 << 12, // -p, Don't run script on daemon startup
     FLAG_NO_SHUTDOWN        = 1 << 13, // -q, Don't run script on daemon quit
     FLAG_INITIAL_DOWN       = 1 << 14, // -l, Run "down" script on startup if no cable is detected
     FLAG_EXTRA_ARG          = 1 << 15, // -x, Specify an extra argument for action script
     FLAG_MONITOR            = 1 << 16, // -M, Use interface monitoring
     FLAG_NO_UP_NEW_IFACE        = 1 << 17, // -A, Don't up newly appeared interface
 #if ENABLE_FEATURE_PIDFILE
     FLAG_KILL           = 1 << 18, // -k, Kill a running daemon
 #endif
 };
anonymous enum
anonymous enum
Enumerator
IFSTATUS_ERR
IFSTATUS_DOWN
IFSTATUS_UP
Definition at line 126 of file ifplugd.c.
      { // interface status
     IFSTATUS_ERR = -1,
     IFSTATUS_DOWN = 0,
     IFSTATUS_UP = 1,
 };
anonymous enum
anonymous enum
Enumerator
ioctl_fd
netlink_fd
Definition at line 132 of file ifplugd.c.
      { // constant fds
     ioctl_fd = 3,
     netlink_fd = 4,
 };
anonymous enum
anonymous enum
Enumerator
API_ETHTOOL
API_MII
API_PRIVATE
API_WLAN
API_IFF
API_AUTO
Definition at line 295 of file ifplugd.c.
      { // api mode
     API_ETHTOOL, // 'e'
     API_MII,     // 'm'
     API_PRIVATE, // 'p'
     API_WLAN,    // 'w'
     API_IFF,     // 'i'
     API_AUTO,    // 'a'
 };
Function Documentation
check_existence_through_netlink()
static NOINLINE int check_existence_through_netlink (void) static
Definition at line 476 of file ifplugd.c.
 {
     int iface_len;
     /* Buffer was 1K, but on linux-3.9.9 it was reported to be too small.
      * netlink.h: "limit to 8K to avoid MSG_TRUNC when PAGE_SIZE is very large".
      * Note: on error returns (-1) we exit, no need to free replybuf.
      */
     enum { BUF_SIZE = 8 * 1024 };
     char *replybuf = xmalloc(BUF_SIZE);
     iface_len = strlen(G.iface);
     while (1) {
         struct nlmsghdr *mhdr;
         ssize_t bytes;
         bytes = recv(netlink_fd, replybuf, BUF_SIZE, MSG_DONTWAIT);
         if (bytes < 0) {
             if (errno == EAGAIN)
                 goto ret;
             if (errno == EINTR)
                 continue;
             bb_simple_perror_msg("netlink: recv");
             return -1;
         }
         mhdr = (struct nlmsghdr*)replybuf;
         while (bytes > 0) {
             if (!NLMSG_OK(mhdr, bytes)) {
                 bb_simple_error_msg("netlink packet too small or truncated");
                 return -1;
             }
             if (mhdr->nlmsg_type == RTM_NEWLINK || mhdr->nlmsg_type == RTM_DELLINK) {
                 struct rtattr *attr;
                 int attr_len;
                 if (mhdr->nlmsg_len < NLMSG_LENGTH(sizeof(struct ifinfomsg))) {
                     bb_simple_error_msg("netlink packet too small or truncated");
                     return -1;
                 }
                 attr = IFLA_RTA(NLMSG_DATA(mhdr));
                 attr_len = IFLA_PAYLOAD(mhdr);
                 while (RTA_OK(attr, attr_len)) {
                     if (attr->rta_type == IFLA_IFNAME) {
                         int len = RTA_PAYLOAD(attr);
                         if (len > IFNAMSIZ)
                             len = IFNAMSIZ;
                         if (iface_len <= len
                          && strncmp(G.iface, RTA_DATA(attr), len) == 0
                         ) {
                             G.iface_exists = (mhdr->nlmsg_type == RTM_NEWLINK);
                         }
                     }
                     attr = RTA_NEXT(attr, attr_len);
                 }
             }
             mhdr = NLMSG_NEXT(mhdr, bytes);
         }
     }
  ret:
     free(replybuf);
     return G.iface_exists;
 }
References bb_simple_error_msg(), bb_simple_perror_msg(), BUF_SIZE, EAGAIN, EINTR, errno, free, G, IFLA_IFNAME, IFNAMSIZ, len, MSG_DONTWAIT, netlink_fd, NLMSG_DATA, nlmsghdr::nlmsg_len, NLMSG_NEXT, NLMSG_OK, nlmsghdr::nlmsg_type, recv(), RTA_DATA, RTA_NEXT, RTA_OK, rtattr::rta_type, RTM_NEWLINK, strlen(), strncmp(), and xmalloc.
Referenced by ifplugd_main().
detect_link()
static smallint detect_link (void) static
Definition at line 426 of file ifplugd.c.
 {
     smallint status;
     if (!G.iface_exists)
         return (option_mask32 & FLAG_MONITOR) ? IFSTATUS_DOWN : IFSTATUS_ERR;
     /* Some drivers can't detect link status when the interface is down.
      * I imagine detect_link_iff() is the most vulnerable.
      * That's why -a "noauto" in an option, not a hardwired behavior.
      */
     if (!(option_mask32 & FLAG_NO_AUTO))
         up_iface();
     if (G.api_method_num == API_AUTO) {
         int i;
         smallint sv_logmode;
         sv_logmode = logmode;
         for (i = 0; i < ARRAY_SIZE(method_table); i++) {
             logmode = LOGMODE_NONE;
             status = method_table[i].func();
             logmode = sv_logmode;
             if (status != IFSTATUS_ERR) {
                 G.api_method_num = i;
                 bb_info_msg("using %s detection mode", method_table[i].name);
                 break;
             }
         }
     } else {
         status = method_table[G.api_method_num].func();
     }
     if (status == IFSTATUS_ERR) {
         if (option_mask32 & FLAG_IGNORE_FAIL)
             status = IFSTATUS_DOWN;
         else if (option_mask32 & FLAG_IGNORE_FAIL_POSITIVE)
             status = IFSTATUS_UP;
         else if (G.api_mode[0] == 'a')
             bb_simple_error_msg("can't detect link status");
     }
     if (status != G.iface_last_status) {
         G.iface_prev_status = G.iface_last_status;
         G.iface_last_status = status;
     }
     return status;
 }
References API_AUTO, ARRAY_SIZE, bb_info_msg, bb_simple_error_msg(), FLAG_IGNORE_FAIL, FLAG_IGNORE_FAIL_POSITIVE, FLAG_MONITOR, FLAG_NO_AUTO, G, i, IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, logmode, LOGMODE_NONE, option_mask32, status, and up_iface().
Referenced by ifplugd_main().
detect_link_ethtool()
static smallint detect_link_ethtool (void) static
Definition at line 230 of file ifplugd.c.
 {
     struct ifreq ifreq;
     struct ethtool_value edata;
     set_ifreq_to_ifname(&ifreq);
     edata.cmd = ETHTOOL_GLINK;
     ifreq.ifr_data = (void*) &edata;
     if (network_ioctl(SIOCETHTOOL, &ifreq, "ETHTOOL_GLINK") < 0) {
         return IFSTATUS_ERR;
     }
     return edata.data ? IFSTATUS_UP : IFSTATUS_DOWN;
 }
References IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, network_ioctl(), and set_ifreq_to_ifname().
detect_link_iff()
static smallint detect_link_iff (void) static
Definition at line 247 of file ifplugd.c.
 {
     struct ifreq ifreq;
     set_ifreq_to_ifname(&ifreq);
     if (network_ioctl(SIOCGIFFLAGS, &ifreq, "SIOCGIFFLAGS") < 0) {
         return IFSTATUS_ERR;
     }
     /* If IFF_UP is not set (interface is down), IFF_RUNNING is never set
      * regardless of link status. Simply continue to report last status -
      * no point in reporting spurious link downs if interface is disabled
      * by admin. When/if it will be brought up,
      * we'll report real link status.
      */
     if (!(ifreq.ifr_flags & IFF_UP) && G.iface_last_status != IFSTATUS_ERR)
         return G.iface_last_status;
     return (ifreq.ifr_flags & IFF_RUNNING) ? IFSTATUS_UP : IFSTATUS_DOWN;
 }
References G, IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, network_ioctl(), set_ifreq_to_ifname(), and SIOCGIFFLAGS.
detect_link_mii()
static smallint detect_link_mii (void) static
Definition at line 184 of file ifplugd.c.
 {
     /* char buffer instead of bona-fide struct avoids aliasing warning */
     char buf[sizeof(struct ifreq)];
     struct ifreq *const ifreq = (void *)buf;
     struct mii_ioctl_data *mii = (void *)&ifreq->ifr_data;
     set_ifreq_to_ifname(ifreq);
     if (network_ioctl(SIOCGMIIPHY, ifreq, "SIOCGMIIPHY") < 0) {
         return IFSTATUS_ERR;
     }
     mii->reg_num = 1;
     if (network_ioctl(SIOCGMIIREG, ifreq, "SIOCGMIIREG") < 0) {
         return IFSTATUS_ERR;
     }
     return (mii->val_out & 0x0004) ? IFSTATUS_UP : IFSTATUS_DOWN;
 }
References buf, IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, network_ioctl(), and set_ifreq_to_ifname().
detect_link_priv()
static smallint detect_link_priv (void) static
Definition at line 207 of file ifplugd.c.
 {
     /* char buffer instead of bona-fide struct avoids aliasing warning */
     char buf[sizeof(struct ifreq)];
     struct ifreq *const ifreq = (void *)buf;
     struct mii_ioctl_data *mii = (void *)&ifreq->ifr_data;
     set_ifreq_to_ifname(ifreq);
     if (network_ioctl(SIOCDEVPRIVATE, ifreq, "SIOCDEVPRIVATE") < 0) {
         return IFSTATUS_ERR;
     }
     mii->reg_num = 1;
     if (network_ioctl(SIOCDEVPRIVATE+1, ifreq, "SIOCDEVPRIVATE+1") < 0) {
         return IFSTATUS_ERR;
     }
     return (mii->val_out & 0x0004) ? IFSTATUS_UP : IFSTATUS_DOWN;
 }
References buf, IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, network_ioctl(), set_ifreq_to_ifname(), and SIOCDEVPRIVATE.
detect_link_wlan()
static smallint detect_link_wlan (void) static
Definition at line 269 of file ifplugd.c.
 {
     int i;
     struct iwreq iwrequest;
     uint8_t mac[ETH_ALEN];
     memset(&iwrequest, 0, sizeof(iwrequest));
     strncpy_IFNAMSIZ(iwrequest.ifr_ifrn.ifrn_name, G.iface);
     if (network_ioctl(SIOCGIWAP, &iwrequest, "SIOCGIWAP") < 0) {
         return IFSTATUS_ERR;
     }
     memcpy(mac, &iwrequest.u.ap_addr.sa_data, ETH_ALEN);
     if (mac[0] == 0xFF || mac[0] == 0x44 || mac[0] == 0x00) {
         for (i = 1; i < ETH_ALEN; ++i) {
             if (mac[i] != mac[0])
                 return IFSTATUS_UP;
         }
         return IFSTATUS_DOWN;
     }
     return IFSTATUS_UP;
 }
References ETH_ALEN, G, i, IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, memcpy, memset, network_ioctl(), and strncpy_IFNAMSIZ().
ifplugd_main()
int ifplugd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 561 of file ifplugd.c.
 {
     int iface_status;
     int delay_time;
     const char *iface_status_str;
     struct pollfd netlink_pollfd[1];
     unsigned opts;
     const char *api_mode_found;
 #if ENABLE_FEATURE_PIDFILE
     char *pidfile_name;
     pid_t pid_from_pidfile;
 #endif
     INIT_G();
     opts = getopt32(argv, OPTION_STR,
         &G.iface, &G.script_name, &G.poll_time, &G.delay_up,
         &G.delay_down, &G.api_mode, &G.extra_arg);
     G.poll_time *= 1000;
     applet_name = xasprintf("ifplugd(%s)", G.iface);
 #if ENABLE_FEATURE_PIDFILE
     pidfile_name = xasprintf(CONFIG_PID_FILE_PATH "/ifplugd.%s.pid", G.iface);
     pid_from_pidfile = read_pid(pidfile_name);
     if (opts & FLAG_KILL) {
         if (pid_from_pidfile > 0)
             /* Upstream tool use SIGINT for -k */
             kill(pid_from_pidfile, SIGINT);
         return EXIT_SUCCESS;
     }
     if (pid_from_pidfile > 0 && kill(pid_from_pidfile, 0) == 0)
         bb_simple_error_msg_and_die("daemon already running");
 #endif
     api_mode_found = strchr(api_modes, G.api_mode[0]);
     if (!api_mode_found)
         bb_error_msg_and_die("unknown API mode '%s'", G.api_mode);
     G.api_method_num = api_mode_found - api_modes;
     if (!(opts & FLAG_NO_DAEMON))
         bb_daemonize_or_rexec(DAEMON_CHDIR_ROOT, argv);
     xmove_fd(xsocket(AF_INET, SOCK_DGRAM, 0), ioctl_fd);
     if (opts & FLAG_MONITOR) {
         int fd = create_and_bind_to_netlink(NETLINK_ROUTE, RTMGRP_LINK, 0);
         xmove_fd(fd, netlink_fd);
     }
     write_pidfile(pidfile_name);
     /* this can't be moved before socket creation */
     if (!(opts & FLAG_NO_SYSLOG)) {
         openlog(applet_name, 0, LOG_DAEMON);
         logmode |= LOGMODE_SYSLOG;
     }
     bb_signals(0
         | (1 << SIGINT )
         | (1 << SIGTERM)
         | (1 << SIGQUIT)
         | (1 << SIGHUP ) /* why we ignore it? */
         /* | (1 << SIGCHLD) - run_script does not use it anymore */
         , record_signo);
     bb_info_msg("started: %s", bb_banner);
     if (opts & FLAG_MONITOR) {
         struct ifreq ifrequest;
         set_ifreq_to_ifname(&ifrequest);
         G.iface_exists = (network_ioctl(SIOCGIFINDEX, &ifrequest, NULL) == 0);
     }
     if (G.iface_exists)
         maybe_up_new_iface();
     iface_status = detect_link();
     if (iface_status == IFSTATUS_ERR)
         goto exiting;
     iface_status_str = strstatus(iface_status);
     if (opts & FLAG_MONITOR) {
         bb_info_msg("interface %s",
             G.iface_exists ? "exists"
             : "doesn't exist, waiting");
     }
     /* else we assume it always exists, but don't mislead user
      * by potentially lying that it really exists */
     if (G.iface_exists) {
         bb_info_msg("link is %s", iface_status_str);
     }
     if ((!(opts & FLAG_NO_STARTUP)
          && iface_status == IFSTATUS_UP
         )
      || (opts & FLAG_INITIAL_DOWN)
     ) {
         if (run_script(iface_status_str) != 0)
             goto exiting;
     }
     /* Main loop */
     netlink_pollfd[0].fd = netlink_fd;
     netlink_pollfd[0].events = POLLIN;
     delay_time = 0;
     while (1) {
         int iface_status_old;
         switch (bb_got_signal) {
         case SIGINT:
         case SIGTERM:
             bb_got_signal = 0;
             goto cleanup;
         case SIGQUIT:
             bb_got_signal = 0;
             goto exiting;
         default:
             bb_got_signal = 0;
         /* do not clear bb_got_signal if already 0, this can lose signals */
         case 0:
             break;
         }
         if (poll(netlink_pollfd,
                 (opts & FLAG_MONITOR) ? 1 : 0,
                 G.poll_time
             ) < 0
         ) {
             if (errno == EINTR)
                 continue;
             bb_simple_perror_msg("poll");
             goto exiting;
         }
         if ((opts & FLAG_MONITOR)
          && (netlink_pollfd[0].revents & POLLIN)
         ) {
             int iface_exists_old;
             iface_exists_old = G.iface_exists;
             G.iface_exists = check_existence_through_netlink();
             if (G.iface_exists < 0) /* error */
                 goto exiting;
             if (iface_exists_old != G.iface_exists) {
                 bb_info_msg("interface %sappeared",
                         G.iface_exists ? "" : "dis");
                 if (G.iface_exists)
                     maybe_up_new_iface();
             }
         }
         /* note: if !G.iface_exists, returns DOWN */
         iface_status_old = iface_status;
         iface_status = detect_link();
         if (iface_status == IFSTATUS_ERR) {
             if (!(opts & FLAG_MONITOR))
                 goto exiting;
             iface_status = IFSTATUS_DOWN;
         }
         iface_status_str = strstatus(iface_status);
         if (iface_status_old != iface_status) {
             bb_info_msg("link is %s", iface_status_str);
             if (delay_time) {
                 /* link restored its old status before
                  * we ran script. don't run the script: */
                 delay_time = 0;
             } else {
                 delay_time = monotonic_sec();
                 if (iface_status == IFSTATUS_UP)
                     delay_time += G.delay_up;
                 if (iface_status == IFSTATUS_DOWN)
                     delay_time += G.delay_down;
 #if 0  /* if you are back in 1970... */
                 if (delay_time == 0) {
                     sleep1();
                     delay_time = 1;
                 }
 #endif
             }
         }
         if (delay_time && (int)(monotonic_sec() - delay_time) >= 0) {
             if (run_script(iface_status_str) != 0)
                 goto exiting;
             delay_time = 0;
         }
     } /* while (1) */
  cleanup:
     if (!(opts & FLAG_NO_SHUTDOWN)
      && (iface_status == IFSTATUS_UP
          || (iface_status == IFSTATUS_DOWN && delay_time)
         )
     ) {
         setenv(IFPLUGD_ENV_PREVIOUS, strstatus(iface_status), 1);
         setenv(IFPLUGD_ENV_CURRENT, strstatus(-1), 1);
         run_script("down\0up"); /* reusing string */
     }
  exiting:
     remove_pidfile(pidfile_name);
     bb_simple_error_msg_and_die("exiting");
 }
References AF_INET, applet_name, argv, bb_daemonize_or_rexec, bb_error_msg_and_die(), bb_got_signal, bb_info_msg, bb_signals(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), check_existence_through_netlink(), cleanup(), create_and_bind_to_netlink(), DAEMON_CHDIR_ROOT, detect_link(), EINTR, errno, pollfd::events, EXIT_SUCCESS, exiting, fd, pollfd::fd, FLAG_INITIAL_DOWN, FLAG_MONITOR, FLAG_NO_DAEMON, FLAG_NO_SHUTDOWN, FLAG_NO_STARTUP, FLAG_NO_SYSLOG, G, getopt32(), IFPLUGD_ENV_CURRENT, IFPLUGD_ENV_PREVIOUS, IFSTATUS_DOWN, IFSTATUS_ERR, IFSTATUS_UP, INIT_G, ioctl_fd, kill(), LOG_DAEMON, logmode, LOGMODE_SYSLOG, maybe_up_new_iface(), monotonic_sec(), netlink_fd, NETLINK_ROUTE, network_ioctl(), NULL, openlog(), OPTION_STR, poll(), POLLIN, record_signo(), remove_pidfile, run_script(), set_ifreq_to_ifname(), setenv(), SIGHUP, SIGINT, SIGQUIT, SIGTERM, SIOCGIFINDEX, sleep1(), SOCK_DGRAM, strchr(), strstatus(), write_pidfile(), xasprintf(), xmove_fd(), and xsocket().
maybe_up_new_iface()
static void maybe_up_new_iface (void) static
Definition at line 390 of file ifplugd.c.
 {
     if (!(option_mask32 & FLAG_NO_UP_NEW_IFACE))
         up_iface();
 #if 0 /* bloat */
     struct ifreq ifrequest;
     struct ethtool_drvinfo driver_info;
     set_ifreq_to_ifname(&ifrequest);
     driver_info.cmd = ETHTOOL_GDRVINFO;
     ifrequest.ifr_data = &driver_info;
     if (network_ioctl(SIOCETHTOOL, &ifrequest, NULL) == 0) {
         char buf[sizeof("/xx:xx:xx:xx:xx:xx")];
         /* Get MAC */
         buf[0] = '\0';
         set_ifreq_to_ifname(&ifrequest);
         if (network_ioctl(SIOCGIFHWADDR, &ifrequest, NULL) == 0) {
             sprintf(buf, "/%02X:%02X:%02X:%02X:%02X:%02X",
                 (uint8_t)(ifrequest.ifr_hwaddr.sa_data[0]),
                 (uint8_t)(ifrequest.ifr_hwaddr.sa_data[1]),
                 (uint8_t)(ifrequest.ifr_hwaddr.sa_data[2]),
                 (uint8_t)(ifrequest.ifr_hwaddr.sa_data[3]),
                 (uint8_t)(ifrequest.ifr_hwaddr.sa_data[4]),
                 (uint8_t)(ifrequest.ifr_hwaddr.sa_data[5]));
         }
         bb_info_msg("using interface %s%s with driver<%s> (version: %s)",
             G.iface, buf, driver_info.driver, driver_info.version);
     }
 #endif
     if (G.api_mode[0] == 'a')
         G.api_method_num = API_AUTO;
 }
References API_AUTO, bb_info_msg, buf, FLAG_NO_UP_NEW_IFACE, G, network_ioctl(), NULL, option_mask32, set_ifreq_to_ifname(), SIOCGIFHWADDR, sprintf(), and up_iface().
Referenced by ifplugd_main().
network_ioctl()
static int network_ioctl (int request, void * data, const char * errmsg) static
Definition at line 174 of file ifplugd.c.
 {
     int r = ioctl(ioctl_fd, request, data);
     if (r < 0 && errmsg)
         bb_perror_msg("%s failed", errmsg);
     return r;
 }
References bb_perror_msg(), errmsg(), ioctl(), and ioctl_fd.
Referenced by detect_link_ethtool(), detect_link_iff(), detect_link_mii(), detect_link_priv(), detect_link_wlan(), ifplugd_main(), maybe_up_new_iface(), and up_iface().
run_script()
static int run_script (const char * action) static
Definition at line 324 of file ifplugd.c.
 {
     char *env_PREVIOUS, *env_CURRENT;
     char *argv[5];
     int r;
     bb_info_msg("executing '%s %s %s'", G.script_name, G.iface, action);
     argv[0] = (char*) G.script_name;
     argv[1] = (char*) G.iface;
     argv[2] = (char*) action;
     argv[3] = (char*) G.extra_arg;
     argv[4] = NULL;
     env_PREVIOUS = xasprintf("%s=%s", IFPLUGD_ENV_PREVIOUS, strstatus(G.iface_prev_status));
     putenv(env_PREVIOUS);
     env_CURRENT = xasprintf("%s=%s", IFPLUGD_ENV_CURRENT, strstatus(G.iface_last_status));
     putenv(env_CURRENT);
     /* r < 0 - can't exec, 0 <= r < 0x180 - exited, >=0x180 - killed by sig (r-0x180) */
     r = spawn_and_wait(argv);
     bb_unsetenv_and_free(env_PREVIOUS);
     bb_unsetenv_and_free(env_CURRENT);
     bb_info_msg("exit code: %d", r & 0xff);
     return (option_mask32 & FLAG_IGNORE_RETVAL) ? 0 : r;
 }
References argv, bb_info_msg, bb_unsetenv_and_free(), FLAG_IGNORE_RETVAL, G, IFPLUGD_ENV_CURRENT, IFPLUGD_ENV_PREVIOUS, NULL, option_mask32, putenv(), spawn_and_wait(), strstatus(), and xasprintf().
Referenced by ifplugd_main().
set_ifreq_to_ifname()
static void set_ifreq_to_ifname (struct ifreq * ifreq) static
Definition at line 168 of file ifplugd.c.
 {
     memset(ifreq, 0, sizeof(struct ifreq));
     strncpy_IFNAMSIZ(ifreq->ifr_name, G.iface);
 }
References G, memset, and strncpy_IFNAMSIZ().
Referenced by detect_link_ethtool(), detect_link_iff(), detect_link_mii(), detect_link_priv(), ifplugd_main(), maybe_up_new_iface(), and up_iface().
strstatus()
static const char* strstatus (int status) static
Definition at line 317 of file ifplugd.c.
 {
     if (status == IFSTATUS_ERR)
         return "error";
     return "down\0up" + (status * 5);
 }
References IFSTATUS_ERR, and status.
Referenced by ifplugd_main(), and run_script().
up_iface()
static void up_iface (void) static
Definition at line 353 of file ifplugd.c.
 {
     struct ifreq ifrequest;
     if (!G.iface_exists)
         return;
     set_ifreq_to_ifname(&ifrequest);
     if (network_ioctl(SIOCGIFFLAGS, &ifrequest, "getting interface flags") < 0) {
         G.iface_exists = 0;
         return;
     }
     if (!(ifrequest.ifr_flags & IFF_UP)) {
         ifrequest.ifr_flags |= IFF_UP;
         /* Let user know we mess up with interface */
         bb_simple_info_msg("upping interface");
         if (network_ioctl(SIOCSIFFLAGS, &ifrequest, "setting interface flags") < 0) {
             if (errno != ENODEV && errno != EADDRNOTAVAIL)
                 xfunc_die();
             G.iface_exists = 0;
             return;
         }
     }
 #if 0 /* why do we mess with IP addr? It's not our business */
     if (network_ioctl(SIOCGIFADDR, &ifrequest, "can't get interface address") < 0) {
     } else if (ifrequest.ifr_addr.sa_family != AF_INET) {
         bb_perror_msg("the interface is not IP-based");
     } else {
         ((struct sockaddr_in*)(&ifrequest.ifr_addr))->sin_addr.s_addr = INADDR_ANY;
         network_ioctl(SIOCSIFADDR, &ifrequest, "can't set interface address");
     }
     network_ioctl(SIOCGIFFLAGS, &ifrequest, "can't get interface flags");
 #endif
 }
References AF_INET, bb_perror_msg(), bb_simple_info_msg, EADDRNOTAVAIL, ENODEV, errno, G, INADDR_ANY, network_ioctl(), in_addr::s_addr, set_ifreq_to_ifname(), sockaddr_in::sin_addr, SIOCGIFADDR, SIOCGIFFLAGS, SIOCSIFADDR, SIOCSIFFLAGS, and xfunc_die().
Referenced by detect_link(), and maybe_up_new_iface().
Variable Documentation
ALIGN1
const char api_modes [] ALIGN1 = "empwia" static
Definition at line 304 of file ifplugd.c.
const { ... } ALIGN_PTR[]
Initial value:
= {
    { "SIOCETHTOOL"       , &detect_link_ethtool },
    { "SIOCGMIIPHY"       , &detect_link_mii     },
    { "SIOCDEVPRIVATE"    , &detect_link_priv    },
    { "wireless extension", &detect_link_wlan    },
    { "IFF_RUNNING"       , &detect_link_iff     },
}