Fennix: Userspace/mlibc/options/posix/generic/time.cpp File Reference
time.cpp File Reference
#include <ctype.h>
#include <langinfo.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <bits/ensure.h>
#include <mlibc/strings.hpp>
Data Structures
struct anonymous_namespace{time.cpp}::strptime_internal_state
Namespaces
anonymous_namespace{time.cpp}
Functions
int anonymous_namespace{time.cpp}::month_to_day (int month)
int anonymous_namespace{time.cpp}::is_leapyear (int year)
int anonymous_namespace{time.cpp}::month_and_year_to_day_in_year (int month, int year)
int anonymous_namespace{time.cpp}::target_determination (int month)
int anonymous_namespace{time.cpp}::doom_determination (int full_year)
int anonymous_namespace{time.cpp}::day_determination (int day, int month, int year)
char * anonymous_namespace{time.cpp}::strptime_internal (const char *__restrict input, const char *__restrict format, struct tm *__restrict tm, struct strptime_internal_state *__restrict state)
char * strptime (const char *__restrict s, const char *__restrict format, struct tm *__restrict tm)
Data Structure Documentation
anonymous_namespace{time.cpp}::strptime_internal_state
struct anonymous_namespace{time.cpp}::strptime_internal_state
Definition at line 91 of file time.cpp.
Data Fields
int century
size_t format_index
bool full_year_given
bool has_century
bool has_day_of_month
bool has_day_of_week
bool has_day_of_year
bool has_month
bool has_year
size_t input_index
Function Documentation
strptime()
char* strptime (const char *__restrict s, const char *__restrict format, struct tm *__restrict tm)
Definition at line 459 of file time.cpp.
{
     struct strptime_internal_state state = {};
     char *result = strptime_internal(s, format, tm, &state);
     if(result == NULL)
         return NULL;
     if(state.has_century && !state.full_year_given){
         int full_year = state.century * 100;
         if(state.has_year){
             //Compensate for default century-adjustment of `%j` operand
             if(tm->tm_year >= 100)
                 full_year += tm->tm_year - 100;
             else
                 full_year += tm->tm_year;
         }
         tm->tm_year = full_year - 1900;
         state.has_year = true;
     }
     if(state.has_month && !state.has_day_of_year){
         int day = 0;
         if(state.has_year)
             day = month_and_year_to_day_in_year(tm->tm_mon, tm->tm_year);
         else
             day = month_to_day(tm->tm_mon);
         tm->tm_yday = day + tm->tm_mday - 1;
         state.has_day_of_year = true;
     }
     if(state.has_year && !state.has_day_of_week){
         if(!state.has_month && !state.has_day_of_month){
             tm->tm_wday = day_determination(0, 0, tm->tm_year + 1900);
         }
         else if(state.has_month && state.has_day_of_month){
             tm->tm_wday = day_determination(tm->tm_mday, tm->tm_mon, tm->tm_year + 1900);
         }
         state.has_day_of_week = true;
     }
     return result;
 }
References anonymous_namespace{time.cpp}::day_determination(), format, anonymous_namespace{time.cpp}::month_and_year_to_day_in_year(), anonymous_namespace{time.cpp}::month_to_day(), NULL, mlibc::result, state, anonymous_namespace{time.cpp}::strptime_internal(), tm::tm_mday, tm::tm_mon, tm::tm_wday, tm::tm_yday, and tm::tm_year.
Referenced by main().