Fennix Kernel: CrashHandler::CrashKeyboardDriver Class Reference
CrashHandler::CrashKeyboardDriver Class Reference
#include <chfcts.hpp>
Public Member Functions
CrashKeyboardDriver ()
~CrashKeyboardDriver ()
Private Member Functions
void PS2Wait (bool Read)
void OnInterruptReceived (CPU::TrapFrame *Frame)
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 273 of file chfcts.hpp.
Constructor & Destructor Documentation
CrashKeyboardDriver()
CrashHandler::CrashKeyboardDriver::CrashKeyboardDriver ()
Definition at line 117 of file kb_drv.cpp.
                                              : Interrupts::Handler(1) /* IRQ1 */
     {
 #define WaitRead PS2Wait(true)
 #define WaitWrite PS2Wait(false)
         CPU::Interrupts(CPU::Disable);
 #if defined(a86)
         /* Disable Port 1 */
         WaitWrite;
         outb(0x64, 0xAD);
         /* Disable Port 2 */
         WaitWrite;
         outb(0x64, 0xA7);
         /* Flush */
         WaitRead;
         inb(0x60);
         /* Test PS/2 controller */
         WaitWrite;
         outb(0x64, 0xAA);
         WaitRead;
         uint8_t test = inb(0x60);
         if (test != 0x55)
         {
             if (test == 0xFA)
                 warn("PS/2 controller acknowledged? (expected TEST_PASSED = 0x55)");
             else
             {
                 error("PS/2 controller self test failed (%#x)", test);
                 // CPU::Stop();
             }
         }
         /* Enable Port 1 */
         WaitWrite;
         outb(0x64, 0xAE);
         /* Reset Port 1 */
         WaitWrite;
         outb(0x64, 0xFF); /* This may break some keyboards? */
         /* Test Port 1 */
         WaitWrite;
         outb(0x64, 0xAB);
         WaitRead;
         test = inb(0x60);
         if (test != 0x00)
         {
             if (test == 0xFA)
                 warn("PS/2 keyboard acknowledged? (expected TEST_PASSED = 0x00)");
             else
             {
                 error("PS/2 keyboard self test failed (%#x)", test);
                 // CPU::Stop();
             }
         }
         /* Disable Port 1 */
         WaitWrite;
         outb(0x64, 0xAD);
         /* Disable Port 2 */
         WaitWrite;
         outb(0x64, 0xA7);
         /* Flush Port 1 */
         WaitRead;
         inb(0x60);
         /* Read Controller Configuration */
         WaitWrite;
         outb(0x64, 0x20);
         WaitRead;
         uint8_t cfg = inb(0x60);
         /* Enable Port 1 & Port 1 translation */
         cfg |= 0b01000001;
         /* Write Controller Configuration */
         WaitWrite;
         outb(0x64, 0x60);
         WaitWrite;
         outb(0x60, cfg);
         /* Enable Port 1 */
         outb(0x64, 0xAE);
         /* Set scan code set 1 */
         WaitWrite;
         outb(0x60, 0xF0);
         WaitWrite;
         outb(0x60, 0x02);
         /* Check if we have scan code set 1 */
         WaitWrite;
         outb(0x60, 0xF0);
         WaitWrite;
         outb(0x60, 0x00);
         /* Read scan code set */
         WaitRead;
         uint8_t scs = inb(0x60);
         if (scs != 0x41)
         {
             warn("PS/2 keyboard scan code set 1 not supported (%#x)", scs);
         }
 #endif // defined(a86)
         CPU::Interrupts(CPU::Enable);
     }
References CPU::Disable, CPU::Enable, error, CPU::Interrupts(), WaitRead, WaitWrite, and warn.
~CrashKeyboardDriver()
CrashHandler::CrashKeyboardDriver::~CrashKeyboardDriver ()
Definition at line 231 of file kb_drv.cpp.
     {
         error("CrashKeyboardDriver::~CrashKeyboardDriver() called");
     }
References error.
Member Function Documentation
OnInterruptReceived()
SafeFunction void CrashHandler::CrashKeyboardDriver::OnInterruptReceived (CPU::TrapFrame * Frame) private virtual
Reimplemented from Interrupts::Handler.
Definition at line 239 of file kb_drv.cpp.
     {
 #if defined(a86)
         UNUSED(Frame);
         uint8_t scanCode = inb(0x60);
         if (scanCode == KEY_D_TAB ||
             scanCode == KEY_D_LCTRL ||
             scanCode == KEY_D_LALT ||
             scanCode == KEY_U_LCTRL ||
             scanCode == KEY_U_LALT)
             return;
         switch (scanCode)
         {
         case KEY_D_UP:
         case KEY_D_LEFT:
         case KEY_D_RIGHT:
         case KEY_D_DOWN:
             ArrowInput(scanCode);
             break;
         default:
             break;
         }
         int key = GetLetterFromScanCode(scanCode);
         if (key != KEY_INVALID)
         {
             if (key == KEY_D_BACKSPACE)
             {
                 if (BackSpaceLimit > 0)
                 {
                     Display->Print('\b', SBIdx);
                     backspace(UserInputBuffer);
                     BackSpaceLimit--;
                 }
             }
             else if (key == '\n')
             {
                 UserInput(UserInputBuffer);
                 BackSpaceLimit = 0;
                 UserInputBuffer[0] = '\0';
             }
             else
             {
                 append(UserInputBuffer, s_cst(char, key));
                 Display->Print((char)key, SBIdx);
                 BackSpaceLimit++;
             }
             Display->SetBuffer(SBIdx); /* Update as we type. */
         }
 #endif // a64 || a32
     }
References append(), CrashHandler::ArrowInput(), backspace(), CrashHandler::BackSpaceLimit, Display, GetLetterFromScanCode(), KEY_D_BACKSPACE, KEY_D_DOWN, KEY_D_LALT, KEY_D_LCTRL, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_TAB, KEY_D_UP, KEY_INVALID, KEY_U_LALT, KEY_U_LCTRL, Video::Display::Print(), CrashHandler::SBIdx, Video::Display::SetBuffer(), UNUSED, CrashHandler::UserInput(), and CrashHandler::UserInputBuffer.
PS2Wait()
void CrashHandler::CrashKeyboardDriver::PS2Wait (bool Read) private
Definition at line 97 of file kb_drv.cpp.
     {
         int Timeout = 100000;
         uint8_t Status = 0;
         while (Timeout--)
         {
             Status = inb(0x64);
             if (Read)
             {
                 if ((Status & 1) == 1)
                     return;
             }
             else
             {
                 if ((Status & 2) == 0)
                     return;
             }
         }
     }
The documentation for this class was generated from the following files:
Kernel/core/crash/chfcts.hpp
Kernel/core/crash/kb_drv.cpp