Fennix: VirtualFileSystem::USTAR Class Reference
VirtualFileSystem::USTAR Class Reference
#include <ustar.hpp>
Data Structures
struct FileHeader
Public Member Functions
bool TestArchive (uintptr_t Address)
void ReadArchive (uintptr_t Address, Virtual *vfs_ctx)
USTAR ()
~USTAR ()
Private Types
enum FileType {
REGULAR_FILE = '0' , HARDLINK = '1' , SYMLINK = '2' , CHARDEV = '3' ,
BLOCKDEV = '4' , DIRECTORY = '5' , FIFO = '6'
}
Private Member Functions
uint32_t getsize (const char *s)
int string2int (const char *str)
Detailed Description
Definition at line 27 of file ustar.hpp.
Data Structure Documentation
VirtualFileSystem::USTAR::FileHeader
struct VirtualFileSystem::USTAR::FileHeader
Definition at line 40 of file ustar.hpp.
Data Fields
char chksum[8]
char dev_maj[8]
char dev_min[8]
char gid[8]
char group[32]
char link[100]
char mode[8]
char mtime[12]
char name[100]
char owner[32]
char pad[12]
char prefix[155]
char signature[6]
char size[12]
char typeflag[1]
char uid[8]
char version[2]
Member Enumeration Documentation
FileType
enum VirtualFileSystem::USTAR::FileType private
Enumerator
REGULAR_FILE
HARDLINK
SYMLINK
CHARDEV
BLOCKDEV
DIRECTORY
FIFO
Definition at line 29 of file ustar.hpp.
         {
             REGULAR_FILE = '0',
             HARDLINK = '1',
             SYMLINK = '2',
             CHARDEV = '3',
             BLOCKDEV = '4',
             DIRECTORY = '5',
             FIFO = '6'
         };
Constructor & Destructor Documentation
USTAR()
VirtualFileSystem::USTAR::USTAR ()
Definition at line 155 of file ustar.cpp.
 {}
~USTAR()
VirtualFileSystem::USTAR::~USTAR ()
Definition at line 157 of file ustar.cpp.
 {}
Member Function Documentation
getsize()
uint32_t VirtualFileSystem::USTAR::getsize (const char * s) inline private
Definition at line 62 of file ustar.hpp.
         {
             uint32_t ret = 0;
             while (*s)
             {
                 ret *= 8;
                 ret += *s - '0';
                 s++;
             }
             return ret;
         }
References s.
Referenced by ReadArchive().
ReadArchive()
void VirtualFileSystem::USTAR::ReadArchive (uintptr_t Address, Virtual * vfs_ctx)
Definition at line 63 of file ustar.cpp.
     {
         trace("Initializing USTAR with address %#llx", Address);
         if (!this->TestArchive(Address))
             return; /* Check whether the archive is deflated */
         debug("USTAR signature valid! Name:%s Signature:%s Mode:%c Size:%lu",
               ((FileHeader *)Address)->name,
               ((FileHeader *)Address)->signature,
               string2int(((FileHeader *)Address)->mode),
               ((FileHeader *)Address)->size);
         vfs_ctx->CreateRoot("/", &ustar_op);
         for (size_t i = 0;; i++)
         {
             FileHeader *header = (FileHeader *)Address;
             if (memcmp(((FileHeader *)Address)->signature, "ustar", 5) != 0)
                 break;
             memmove(header->name, header->name + 1, strlen(header->name));
             if (header->name[strlen(header->name) - 1] == '/')
                 header->name[strlen(header->name) - 1] = 0;
             size_t size = getsize(header->size);
             Node *node = nullptr;
             // if (!isempty((char *)header->name))
             //     KPrint("Adding file \e88AACC%s\eCCCCCC (\e88AACC%lu \eCCCCCCbytes)", header->name, size);
             // else
             //     goto NextFileAddress;
             if (isempty((char *)header->name))
                 goto NextFileAddress;
             node = vfs_ctx->Create(header->name, NodeFlags::NODE_FLAG_ERROR);
             debug("Added node: %s", node->Name);
             if (node == nullptr)
             {
                 static int ErrorsAllowed = 20;
                 if (ErrorsAllowed > 0)
                 {
                     ErrorsAllowed--;
                     goto NextFileAddress;
                 }
                 else
                 {
                     error("Adding USTAR files failed because too many files were corrupted or invalid.");
                     break;
                 }
             }
             else
             {
                 debug("%s %d KiB, Type:%c", header->name, TO_KiB(size), header->typeflag[0]);
                 node->Mode = string2int(header->mode);
                 node->Address = (Address + 512);
                 node->Length = size;
                 node->GroupIdentifier = getsize(header->gid);
                 node->UserIdentifier = getsize(header->uid);
                 node->IndexNode = i;
                 switch (header->typeflag[0])
                 {
                 case REGULAR_FILE:
                     node->Flags = NodeFlags::FILE;
                     break;
                 case SYMLINK:
                     node->Flags = NodeFlags::SYMLINK;
                     node->Symlink = new char[strlen(header->link) + 1];
                     strncpy((char *)node->Symlink, header->link, strlen(header->link));
                     break;
                 case DIRECTORY:
                     node->Flags = NodeFlags::DIRECTORY;
                     break;
                 case CHARDEV:
                     node->Flags = NodeFlags::CHARDEVICE;
                     break;
                 case BLOCKDEV:
                     node->Flags = NodeFlags::BLOCKDEVICE;
                     break;
                 default:
                     warn("Unknown type: %d", header->typeflag[0]);
                     break;
                 }
             NextFileAddress:
                 Address += ((size / 512) + 1) * 512;
                 if (size % 512)
                     Address += 512;
             }
         }
     }
References Address, BLOCKDEV, VirtualFileSystem::BLOCKDEVICE, CHARDEV, VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), VirtualFileSystem::Virtual::CreateRoot(), debug, VirtualFileSystem::DIRECTORY, DIRECTORY, error, getsize(), i, isempty(), memcmp(), memmove, VirtualFileSystem::NODE_FLAG_ERROR, REGULAR_FILE, signature, size, string2int(), strlen(), strncpy(), VirtualFileSystem::SYMLINK, SYMLINK, TestArchive(), trace, VirtualFileSystem::ustar_op, and warn.
Referenced by Main().
string2int()
int VirtualFileSystem::USTAR::string2int (const char * str) inline private
Definition at line 74 of file ustar.hpp.
         {
             int res = 0;
             for (int i = 0; str[i] != '\0'; ++i)
                 res = res * 10 + str[i] - '0';
             return res;
         }
References i, and str.
Referenced by ReadArchive().
TestArchive()
bool VirtualFileSystem::USTAR::TestArchive (uintptr_t Address)
Definition at line 47 of file ustar.cpp.
     {
         if (!Memory::Virtual().Check((void *)Address))
         {
             error("Address %#lx is not mapped!", Address);
             return false;
         }
         if (memcmp(((FileHeader *)(uintptr_t)Address)->signature, "ustar", 5) != 0)
         {
             error("ustar signature invalid!");
             return false;
         }
         return true;
     }
References Address, CPU::Check, error, memcmp(), and signature.
Referenced by ReadArchive().
The documentation for this class was generated from the following files:
Kernel/include/filesystem/ustar.hpp
Kernel/FileSystem/FS/ustar.cpp