Fennix: Userspace/mlibc/options/lsb/generic/auxv.cpp File Reference
auxv.cpp File Reference
#include <errno.h>
#include <stdint.h>
#include <sys/auxv.h>
#include <bits/ensure.h>
Functions
uintptr_t * __dlapi_entrystack ()
int peekauxval (unsigned long type, unsigned long *out)
unsigned long getauxval (unsigned long type)
Function Documentation
__dlapi_entrystack()
uintptr_t* __dlapi_entrystack ()
Definition at line 398 of file main.cpp.
{
     return entryStack;
 }
References entryStack.
Referenced by peekauxval().
getauxval()
unsigned long getauxval (unsigned long type)
Definition at line 34 of file auxv.cpp.
{
     unsigned long value = 0;
     if(peekauxval(type, &value))
         return 0;
     return value;
 }
References peekauxval(), and value.
peekauxval()
int peekauxval (unsigned long type, unsigned long * out)
Definition at line 10 of file auxv.cpp.
{
     // Find the auxiliary vector by skipping args and environment.
     auto aux = __dlapi_entrystack();
     aux += *aux + 1; // Skip argc and all arguments
     __ensure(!*aux);
     aux++;
     while(*aux) // Now, we skip the environment.
         aux++;
     aux++;
     // Parse the auxiliary vector.
     while(true) {
         auto value = aux + 1;
         if(*aux == AT_NULL) {
             errno = ENOENT;
             return -1;
         }else if(*aux == type) {
             *out = *value;
             return 0;
         }
         aux += 2;
     }
 }
References __dlapi_entrystack(), __ensure, AT_NULL, ENOENT, errno, and value.
Referenced by getauxval().