Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/f_finale.h File Reference
f_finale.h File Reference
#include "doomtype.h"
#include "d_event.h"
Functions
boolean F_Responder (event_t *ev)
void F_Ticker (void)
void F_Drawer (void)
void F_StartFinale (void)
Function Documentation
F_Drawer()
void F_Drawer (void)
Definition at line 702 of file f_finale.c.
 {
     switch (finalestage)
     {
         case F_STAGE_CAST:
             F_CastDrawer();
             break;
         case F_STAGE_TEXT:
             F_TextWrite();
             break;
         case F_STAGE_ARTSCREEN:
             F_ArtScreenDrawer();
             break;
     }
 }
References F_ArtScreenDrawer(), F_CastDrawer(), F_STAGE_ARTSCREEN, F_STAGE_CAST, F_STAGE_TEXT, F_TextWrite(), and finalestage.
Referenced by D_Display().
F_Responder()
boolean F_Responder (event_t * ev)
Definition at line 160 of file f_finale.c.
 {
     if (finalestage == F_STAGE_CAST)
     return F_CastResponder (event);
     return false;
 }
References F_CastResponder(), F_STAGE_CAST, and finalestage.
Referenced by G_Responder().
F_StartFinale()
void F_StartFinale (void)
Definition at line 108 of file f_finale.c.
 {
     size_t i;
     gameaction = ga_nothing;
     gamestate = GS_FINALE;
     viewactive = false;
     automapactive = false;
     if (logical_gamemission == doom)
     {
         S_ChangeMusic(mus_victor, true);
     }
     else
     {
         S_ChangeMusic(mus_read_m, true);
     }
     // Find the right screen and set the text and background
     for (i=0; i<arrlen(textscreens); ++i)
     {
         textscreen_t *screen = &textscreens[i];
         // Hack for Chex Quest
         if (gameversion == exe_chex && screen->mission == doom)
         {
             screen->level = 5;
         }
         if (logical_gamemission == screen->mission
          && (logical_gamemission != doom || gameepisode == screen->episode)
          && gamemap == screen->level)
         {
             finaletext = screen->text;
             finaleflat = screen->background;
         }
     }
     // Do dehacked substitutions of strings
     finaletext = DEH_String(finaletext);
     finaleflat = DEH_String(finaleflat);
     finalestage = F_STAGE_TEXT;
     finalecount = 0;
 }
References arrlen, automapactive, textscreen_t::background, DEH_String, doom, textscreen_t::episode, exe_chex, F_STAGE_TEXT, finalecount, finaleflat, finalestage, finaletext, ga_nothing, gameaction, gameepisode, gamemap, gamestate, gameversion, GS_FINALE, i, textscreen_t::level, logical_gamemission, textscreen_t::mission, mus_read_m, mus_victor, S_ChangeMusic(), textscreen_t::text, textscreens, and viewactive.
Referenced by G_Ticker(), and G_WorldDone().
F_Ticker()
void F_Ticker (void)
Definition at line 172 of file f_finale.c.
 {
     size_t      i;
     // check for skipping
     if ( (gamemode == commercial)
       && ( finalecount > 50) )
     {
       // go on to the next level
       for (i=0 ; i<MAXPLAYERS ; i++)
     if (players[i].cmd.buttons)
       break;
       if (i < MAXPLAYERS)
       {
     if (gamemap == 30)
       F_StartCast ();
     else
       gameaction = ga_worlddone;
       }
     }
     // advance animation
     finalecount++;
     if (finalestage == F_STAGE_CAST)
     {
     F_CastTicker ();
     return;
     }
     if ( gamemode == commercial)
     return;
     if (finalestage == F_STAGE_TEXT
      && finalecount>strlen (finaletext)*TEXTSPEED + TEXTWAIT)
     {
     finalecount = 0;
     finalestage = F_STAGE_ARTSCREEN;
     wipegamestate = -1;     // force a wipe
     if (gameepisode == 3)
         S_StartMusic (mus_bunny);
     }
 }
References commercial, F_CastTicker(), F_STAGE_ARTSCREEN, F_STAGE_CAST, F_STAGE_TEXT, F_StartCast(), finalecount, finalestage, finaletext, ga_worlddone, gameaction, gameepisode, gamemap, gamemode, i, MAXPLAYERS, mus_bunny, players, S_StartMusic(), strlen, TEXTSPEED, TEXTWAIT, and wipegamestate.
Referenced by G_Ticker().