Fennix: Userspace/apps/base/busybox/util-linux/setsid.c File Reference
setsid.c File Reference
#include "libbb.h"
Functions
int setsid_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
setsid_main()
int setsid_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 36 of file setsid.c.
 {
     unsigned opt;
     /* +: stop on first non-opt */
     opt = getopt32(argv, "^+" "c" "\0" "-1"/* at least one arg */);
     argv += optind;
     /* setsid() is allowed only when we are not a process group leader.
      * Otherwise our PID serves as PGID of some existing process group
      * and cannot be used as PGID of a new process group.
      *
      * Example: setsid() below fails when run alone in interactive shell:
      *  $ setsid PROG
      * because shell's child (setsid) is put in a new process group.
      * But doesn't fail if shell is not interactive
      * (and therefore doesn't create process groups for pipes),
      * or if setsid is not the first process in the process group:
      *  $ true | setsid PROG
      * or if setsid is executed in backquotes (`setsid PROG`)...
      */
     if (setsid() < 0) {
         pid_t pid = fork_or_rexec(argv);
         if (pid != 0) {
             /* parent */
             /* TODO:
              * we can waitpid(pid, &status, 0) and then even
              * emulate exitcode, making the behavior consistent
              * in both forked and non forked cases.
              * However, the code is larger and upstream
              * does not do such trick.
              */
             return EXIT_SUCCESS;
         }
         /* child */
         /* now there should be no error: */
         setsid();
     }
     if (opt) {
         /* -c: set (with stealing) controlling tty */
         ioctl(0, TIOCSCTTY, 1);
     }
     BB_EXECVP_or_die(argv);
 }
References argv, BB_EXECVP_or_die(), EXIT_SUCCESS, fork_or_rexec(), getopt32(), ioctl(), opt, optind, pid, setsid(), and TIOCSCTTY.