Fennix: Userspace/musl/src/internal/dynlink.h File Reference
dynlink.h File Reference
#include <features.h>
#include <elf.h>
#include <stdint.h>
#include <stddef.h>
#include <stdarg.h>
#include "reloc.h"
Data Structures
struct fdpic_loadseg
struct fdpic_loadmap
struct fdpic_dummy_loadmap
Macros
#define R_TYPE(x) ((x)&0x7fffffff)
#define R_SYM(x) ((x)>>32)
#define R_INFO ELF64_R_INFO
#define FDPIC_CONSTDISP_FLAG 0
#define DL_FDPIC 0
#define DL_NOMMU_SUPPORT 0
#define IS_RELATIVE(x, s)
#define NEED_MIPS_GOT_RELOCS 0
#define DT_DEBUG_INDIRECT 0
#define DT_DEBUG_INDIRECT_REL 0
#define AUX_CNT 32
#define DYN_CNT 37
Typedefs
typedef Elf64_Ehdr Ehdr
typedef Elf64_Phdr Phdr
typedef Elf64_Sym Sym
typedef void(* stage2_func) (unsigned char *, size_t *)
Enumerations
enum {
REL_NONE = 0 , REL_SYMBOLIC = -100 , REL_USYMBOLIC , REL_GOT ,
REL_PLT , REL_RELATIVE , REL_OFFSET , REL_OFFSET32 ,
REL_COPY , REL_SYM_OR_REL , REL_DTPMOD , REL_DTPOFF ,
REL_TPOFF , REL_TPOFF_NEG , REL_TLSDESC , REL_FUNCDESC ,
REL_FUNCDESC_VAL
}
Functions
hidden void * __dlsym (void *restrict, const char *restrict, void *restrict)
hidden void __dl_seterr (const char *,...)
hidden int __dl_invalid_handle (void *)
hidden void __dl_vseterr (const char *, va_list)
hidden ptrdiff_t __tlsdesc_static ()
hidden ptrdiff_t __tlsdesc_dynamic ()
hidden void __malloc_donate (char *, char *)
hidden int __malloc_allzerop (void *)
Variables
hidden int __malloc_replaced
hidden int __aligned_alloc_replaced
Data Structure Documentation
fdpic_loadseg
struct fdpic_loadseg
Definition at line 48 of file dynlink.h.
Data Fields
uintptr_t addr
uintptr_t p_memsz
uintptr_t p_vaddr
fdpic_loadmap
struct fdpic_loadmap
Definition at line 52 of file dynlink.h.
Data Fields
unsigned short nsegs
struct fdpic_loadseg segs[]
unsigned short version
fdpic_dummy_loadmap
struct fdpic_dummy_loadmap
Definition at line 57 of file dynlink.h.
Data Fields
unsigned short nsegs
struct fdpic_loadseg segs[1]
unsigned short version
Macro Definition Documentation
AUX_CNT
#define AUX_CNT 32
Definition at line 99 of file dynlink.h.
DL_FDPIC
#define DL_FDPIC 0
Definition at line 69 of file dynlink.h.
DL_NOMMU_SUPPORT
#define DL_NOMMU_SUPPORT 0
Definition at line 73 of file dynlink.h.
DT_DEBUG_INDIRECT
#define DT_DEBUG_INDIRECT 0
Definition at line 92 of file dynlink.h.
DT_DEBUG_INDIRECT_REL
#define DT_DEBUG_INDIRECT_REL 0
Definition at line 96 of file dynlink.h.
DYN_CNT
#define DYN_CNT 37
Definition at line 100 of file dynlink.h.
FDPIC_CONSTDISP_FLAG
#define FDPIC_CONSTDISP_FLAG 0
Definition at line 65 of file dynlink.h.
IS_RELATIVE
#define IS_RELATIVE (x, s)
Value:
    ( \
    (R_TYPE(x) == REL_RELATIVE) || \
    (R_TYPE(x) == REL_SYM_OR_REL && !R_SYM(x)) )
Definition at line 77 of file dynlink.h.
NEED_MIPS_GOT_RELOCS
#define NEED_MIPS_GOT_RELOCS 0
Definition at line 88 of file dynlink.h.
R_INFO
#define R_INFO ELF64_R_INFO
Definition at line 23 of file dynlink.h.
R_SYM
#define R_SYM (x) ((x)>>32)
Definition at line 22 of file dynlink.h.
R_TYPE
#define R_TYPE (x) ((x)&0x7fffffff)
Definition at line 21 of file dynlink.h.
Typedef Documentation
Ehdr
typedef Elf64_Ehdr Ehdr
Definition at line 18 of file dynlink.h.
Phdr
typedef Elf64_Phdr Phdr
Definition at line 19 of file dynlink.h.
stage2_func
typedef void(* stage2_func) (unsigned char *, size_t *)
Definition at line 102 of file dynlink.h.
Sym
typedef Elf64_Sym Sym
Definition at line 20 of file dynlink.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
REL_NONE
REL_SYMBOLIC
REL_USYMBOLIC
REL_GOT
REL_PLT
REL_RELATIVE
REL_OFFSET
REL_OFFSET32
REL_COPY
REL_SYM_OR_REL
REL_DTPMOD
REL_DTPOFF
REL_TPOFF
REL_TPOFF_NEG
REL_TLSDESC
REL_FUNCDESC
REL_FUNCDESC_VAL
Definition at line 28 of file dynlink.h.
      {
     REL_NONE = 0,
     REL_SYMBOLIC = -100,
     REL_USYMBOLIC,
     REL_GOT,
     REL_PLT,
     REL_RELATIVE,
     REL_OFFSET,
     REL_OFFSET32,
     REL_COPY,
     REL_SYM_OR_REL,
     REL_DTPMOD,
     REL_DTPOFF,
     REL_TPOFF,
     REL_TPOFF_NEG,
     REL_TLSDESC,
     REL_FUNCDESC,
     REL_FUNCDESC_VAL,
 };
Function Documentation
__dl_invalid_handle()
hidden int __dl_invalid_handle (void * h)
Definition at line 2226 of file dynlink.c.
 {
     struct dso *p;
     for (p=head; p; p=p->next) if (h==p) return 0;
     error("Invalid library handle %p", (void *)h);
     return 1;
 }
References error, head, and p.
Referenced by dlclose(), dlinfo(), and do_dlsym().
__dl_seterr()
hidden void __dl_seterr (const char * fmt, ...)
Definition at line 75 of file dlerror.c.
 {
     va_list ap;
     va_start(ap, fmt);
     __dl_vseterr(fmt, ap);
     va_end(ap);
 }
References __dl_vseterr(), fmt, va_end(), and va_start().
Referenced by dlinfo(), stub_dlopen(), stub_dlsym(), and stub_invalid_handle().
__dl_vseterr()
hidden void __dl_vseterr (const char * fmt, va_list ap)
Definition at line 45 of file dlerror.c.
 {
     void **q;
     do q = freebuf_queue;
     while (q && a_cas_p(&freebuf_queue, q, 0) != q);
     while (q) {
         void **p = *q;
         free(q);
         q = p;
     }
     va_list ap2;
     va_copy(ap2, ap);
     pthread_t self = __pthread_self();
     if (self->dlerror_buf != (void *)-1)
         free(self->dlerror_buf);
     size_t len = vsnprintf(0, 0, fmt, ap2);
     if (len < sizeof(void *)) len = sizeof(void *);
     va_end(ap2);
     char *buf = malloc(len+1);
     if (buf) {
         vsnprintf(buf, len+1, fmt, ap);
     } else {
         buf = (void *)-1;
     }
     self->dlerror_buf = buf;
     self->dlerror_flag = 1;
 }
References __pthread_self, a_cas_p, buf, fmt, free, freebuf_queue, len, malloc, p, va_copy, va_end(), and vsnprintf().
Referenced by __dl_seterr(), and error_impl().
__dlsym()
hidden void* __dlsym (void * restrict, const char * restrict, void * restrict)
__malloc_allzerop()
hidden int __malloc_allzerop (void * p)
Definition at line 347 of file malloc.c.
 {
     return IS_MMAPPED(MEM_TO_CHUNK(p));
 }
References IS_MMAPPED, MEM_TO_CHUNK, and p.
Referenced by calloc().
__malloc_donate()
hidden void __malloc_donate (char * start, char * end)
Definition at line 36 of file donate.c.
 {
     donate((void *)start, end-start);
 }
References __bin_chunk(), c, C_INUSE, donate(), MEM_TO_CHUNK, n, OVERHEAD, SIZE_ALIGN, and start().
Referenced by reclaim().
__tlsdesc_dynamic()
hidden ptrdiff_t __tlsdesc_dynamic ()
Referenced by do_relocs().
__tlsdesc_static()
hidden ptrdiff_t __tlsdesc_static ()
Referenced by do_relocs().
Variable Documentation
__aligned_alloc_replaced
hidden int __aligned_alloc_replaced extern
Definition at line 4 of file replaced.c.
Referenced by __dls3(), and aligned_alloc().
__malloc_replaced
hidden int __malloc_replaced extern
Definition at line 3 of file replaced.c.