Fennix: Userspace/musl/src/fenv/s390x/fenv.c File Reference
fenv.c File Reference
#include <fenv.h>
#include <features.h>
Functions
static unsigned get_fpc (void)
static void set_fpc (unsigned fpc)
int feclearexcept (int mask)
int feraiseexcept (int mask)
int fetestexcept (int mask)
int fegetround (void)
hidden int __fesetround (int r)
int fegetenv (fenv_t *envp)
int fesetenv (const fenv_t *envp)
Function Documentation
__fesetround()
hidden int __fesetround (int r)
Definition at line 40 of file fenv.c.
 {
     set_fpc(get_fpc() & ~3L | r);
     return 0;
 }
References get_fpc(), and set_fpc().
Referenced by fesetround().
feclearexcept()
int feclearexcept (int mask)
Definition at line 16 of file fenv.c.
 {
     mask &= FE_ALL_EXCEPT;
     set_fpc(get_fpc() & ~mask);
     return 0;
 }
References FE_ALL_EXCEPT, get_fpc(), and set_fpc().
Referenced by feholdexcept(), fesetexceptflag(), fmaf(), nearbyint(), nearbyintf(), and nearbyintl().
fegetenv()
int fegetenv (fenv_t * envp)
Definition at line 46 of file fenv.c.
 {
     *envp = get_fpc();
     return 0;
 }
References envp, and get_fpc().
Referenced by feholdexcept().
fegetround()
int fegetround (void)
Definition at line 35 of file fenv.c.
 {
     return get_fpc() & 3;
 }
References FE_TONEAREST, and get_fpc().
Referenced by __flt_rounds(), and fmaf().
feraiseexcept()
int feraiseexcept (int mask)
Definition at line 23 of file fenv.c.
 {
     mask &= FE_ALL_EXCEPT;
     set_fpc(get_fpc() | mask);
     return 0;
 }
References FE_ALL_EXCEPT, get_fpc(), and set_fpc().
Referenced by fesetexceptflag(), feupdateenv(), and fmaf().
fesetenv()
int fesetenv (const fenv_t * envp)
Definition at line 52 of file fenv.c.
 {
     set_fpc(envp != FE_DFL_ENV ? *envp : 0);
     return 0;
 }
References envp, FE_DFL_ENV, and set_fpc().
Referenced by feupdateenv().
fetestexcept()
int fetestexcept (int mask)
Definition at line 30 of file fenv.c.
 {
     return get_fpc() & mask & FE_ALL_EXCEPT;
 }
References FE_ALL_EXCEPT, and get_fpc().
Referenced by fegetexceptflag(), feupdateenv(), fmaf(), nearbyint(), nearbyintf(), and nearbyintl().
get_fpc()
static unsigned get_fpc (void) inline static
Definition at line 4 of file fenv.c.
 {
     unsigned fpc;
     __asm__ __volatile__("efpc %0" : "=r"(fpc));
     return fpc;
 }
References __asm__().
Referenced by __fesetround(), feclearexcept(), fegetenv(), fegetround(), feraiseexcept(), and fetestexcept().
set_fpc()
static void set_fpc (unsigned fpc) inline static
Definition at line 11 of file fenv.c.
 {
     __asm__ __volatile__("sfpc %0" :: "r"(fpc));
 }
References __asm__().
Referenced by __fesetround(), feclearexcept(), feraiseexcept(), and fesetenv().