Fennix: PS2Mouse Namespace Reference
PS2Mouse Namespace Reference
Enumerations
enum Config { READ_CONFIG = 0x20 , WRITE_CONFIG = 0x60 }
enum Ports { DATA = 0x60 , STATUS = 0x64 , COMMAND = 0x64 }
enum State { OUTPUT_FULL = (1 << 0) , INPUT_FULL = (1 << 1) , MOUSE_BYTE = (1 << 5) }
Functions
void WaitRead ()
void WaitWrite ()
uint8_t Read ()
void Write (uint16_t Port, uint8_t Value)
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *)
Variables
KernelAPI KAPI
int MouseX = 0
int MouseY = 0
int MouseZ = 0
int MouseLeft = 0
int MouseMiddle = 0
int MouseRight = 0
uint8_t Packet [4]
bool PacketReady = false
uint8_t Cycle = 0
Enumeration Type Documentation
Config
enum PS2Mouse::Config
Enumerator
READ_CONFIG
WRITE_CONFIG
Definition at line 34 of file mouse.hpp.
     {
         READ_CONFIG = 0x20,
         WRITE_CONFIG = 0x60
     };
Ports
enum PS2Mouse::Ports
Enumerator
DATA
STATUS
COMMAND
Definition at line 40 of file mouse.hpp.
     {
         DATA = 0x60,
         STATUS = 0x64,
         COMMAND = 0x64,
     };
State
enum PS2Mouse::State
Enumerator
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
Definition at line 47 of file mouse.hpp.
     {
         OUTPUT_FULL = (1 << 0),
         INPUT_FULL = (1 << 1),
         MOUSE_BYTE = (1 << 5)
     };
Function Documentation
CallbackHandler()
int PS2Mouse::CallbackHandler (KernelCallback * Data)
Definition at line 77 of file Mouse.cpp.
     {
         switch (Data->Reason)
         {
         case AcknowledgeReason:
         {
             debug("Kernel acknowledged the driver.");
             break;
         }
         case ConfigurationReason:
         {
             outb(COMMAND, 0xA8);
             Write(COMMAND, READ_CONFIG);
             uint8_t Status = Read();
             Status |= 0b10;
             Write(COMMAND, WRITE_CONFIG);
             Write(DATA, Status);
             Write(COMMAND, 0xD4);
             Write(DATA, 0xF6);
             Read();
             Write(COMMAND, 0xD4);
             Write(DATA, 0xF4);
             Read();
             trace("PS/2 mouse configured.");
             break;
         }
         case QueryReason:
         {
             Data->InputCallback.Mouse.X = MouseX;
             Data->InputCallback.Mouse.Y = MouseY;
             Data->InputCallback.Mouse.Z = MouseZ;
             Data->InputCallback.Mouse.Buttons.Left = MouseLeft;
             Data->InputCallback.Mouse.Buttons.Right = MouseRight;
             Data->InputCallback.Mouse.Buttons.Middle = MouseMiddle;
             break;
         }
         case PollWaitReason:
         {
             while (!PacketReady)
                 TaskManager->Yield();
             Data->InputCallback.Mouse.X = MouseX;
             Data->InputCallback.Mouse.Y = MouseY;
             Data->InputCallback.Mouse.Z = MouseZ;
             Data->InputCallback.Mouse.Buttons.Left = MouseLeft;
             Data->InputCallback.Mouse.Buttons.Right = MouseRight;
             Data->InputCallback.Mouse.Buttons.Middle = MouseMiddle;
             break;
         }
         case StopReason:
         {
             outb(COMMAND, 0xA8);
             Write(COMMAND, READ_CONFIG);
             uint8_t Status = Read();
             Status &= ~0b10;
             Write(COMMAND, WRITE_CONFIG);
             Write(DATA, Status);
             Write(COMMAND, 0xD4);
             Write(DATA, 0xF5);
             Read();
             debug("Driver stopped.");
             break;
         }
         default:
         {
             warn("Unknown reason.");
             break;
         }
         }
         return OK;
     }
References AcknowledgeReason, ConfigurationReason, Data, debug, MouseLeft, MouseMiddle, MouseRight, MouseX, MouseY, MouseZ, OK, outb(), PacketReady, PollWaitReason, QueryReason, Read(), READ_CONFIG, Status, StopReason, TaskManager, trace, warn, Write(), WRITE_CONFIG, and Tasking::Task::Yield().
DriverEntry()
int PS2Mouse::DriverEntry (void * Data)
Definition at line 66 of file Mouse.cpp.
     {
         if (!Data)
             return INVALID_KERNEL_API;
         KAPI = *(KernelAPI *)Data;
         if (KAPI.Version.Major < 0 || KAPI.Version.Minor < 0 || KAPI.Version.Patch < 0)
             return KERNEL_API_VERSION_NOT_SUPPORTED;
         return OK;
     }
References Data, INVALID_KERNEL_API, KAPI, KERNEL_API_VERSION_NOT_SUPPORTED, KernelAPI::KAPIVersion::Major, KernelAPI::KAPIVersion::Minor, OK, KernelAPI::KAPIVersion::Patch, and KernelAPI::Version.
Referenced by StartPS2Mouse().
InterruptCallback()
int PS2Mouse::InterruptCallback (CPURegisters *)
Definition at line 151 of file Mouse.cpp.
     {
         uint8_t Data = inb(0x60);
         if (__builtin_expect(!!(PacketReady), 0))
         {
             bool XNegative, YNegative, XOverflow, YOverflow;
             if (Packet[0] & PS2XSign)
                 XNegative = true;
             else
                 XNegative = false;
             if (Packet[0] & PS2YSign)
                 YNegative = true;
             else
                 YNegative = false;
             if (Packet[0] & PS2XOverflow)
                 XOverflow = true;
             else
                 XOverflow = false;
             if (Packet[0] & PS2YOverflow)
                 YOverflow = true;
             else
                 YOverflow = false;
             if (!XNegative)
             {
                 MouseX += Packet[1];
                 if (XOverflow)
                     MouseX += 255;
             }
             else
             {
                 Packet[1] = (uint8_t)(256 - Packet[1]);
                 MouseX -= Packet[1];
                 if (XOverflow)
                     MouseX -= 255;
             }
             if (!YNegative)
             {
                 MouseY -= Packet[2];
                 if (YOverflow)
                     MouseY -= 255;
             }
             else
             {
                 Packet[2] = (uint8_t)(256 - Packet[2]);
                 MouseY += Packet[2];
                 if (YOverflow)
                     MouseY += 255;
             }
             uint32_t Width = KAPI.Display.GetWidth();
             uint32_t Height = KAPI.Display.GetHeight();
             if (MouseX < 0)
                 MouseX = 0;
             if ((uint32_t)MouseX > Width - 1)
                 MouseX = Width - 1;
             if (MouseY < 0)
                 MouseY = 0;
             if ((uint32_t)MouseY > Height - 1)
                 MouseY = Height - 1;
             MouseLeft = 0;
             MouseMiddle = 0;
             MouseRight = 0;
             if (Packet[0] & PS2LeftButton)
                 MouseLeft = 1;
             if (Packet[0] & PS2MiddleButton)
                 MouseMiddle = 1;
             if (Packet[0] & PS2RightButton)
                 MouseRight = 1;
             PacketReady = false;
         }
         switch (Cycle)
         {
         case 0:
         {
             if ((Data & 0b00001000) == 0)
                 break;
             Packet[0] = Data;
             Cycle++;
             break;
         }
         case 1:
         {
             Packet[1] = Data;
             Cycle++;
             break;
         }
         case 2:
         {
             Packet[2] = Data;
             PacketReady = true;
             Cycle = 0;
             break;
         }
         default:
         {
             warn("Unknown cycle %d", Cycle);
             break;
         }
         }
         return OK;
     }
References __builtin_expect, Cycle, Data, KernelAPI::Display, KernelAPI::KAPIDisplay::GetHeight, KernelAPI::KAPIDisplay::GetWidth, inb(), KAPI, MouseLeft, MouseMiddle, MouseRight, MouseX, MouseY, OK, Packet, PacketReady, PS2LeftButton, PS2MiddleButton, PS2RightButton, PS2XOverflow, PS2XSign, PS2YOverflow, PS2YSign, and warn.
Read()
uint8_t PS2Mouse::Read ()
Definition at line 54 of file Mouse.cpp.
     {
         WaitRead();
         return inb(Ports::DATA);
     }
References DATA, inb(), and WaitRead().
Referenced by APIC::APIC::APIC(), CallbackHandler(), and APIC::APIC::WaitForIPI().
WaitRead()
void PS2Mouse::WaitRead ()
Definition at line 38 of file Mouse.cpp.
     {
         uint64_t Timeout = 100000;
         while (Timeout--)
             if (inb(Ports::STATUS) & State::OUTPUT_FULL)
                 return;
     }
References inb(), VMwareMouse::OUTPUT_FULL, and STATUS.
Referenced by Read().
WaitWrite()
void PS2Mouse::WaitWrite ()
Definition at line 46 of file Mouse.cpp.
     {
         uint64_t Timeout = 100000;
         while (Timeout--)
             if ((inb(Ports::STATUS) & State::INPUT_FULL) == 0)
                 return;
     }
References inb(), VMwareMouse::INPUT_FULL, and STATUS.
Referenced by Write().
Write()
void PS2Mouse::Write (uint16_t Port, uint8_t Value)
Definition at line 60 of file Mouse.cpp.
     {
         WaitWrite();
         outb(Port, Value);
     }
References outb(), and WaitWrite().
Referenced by CallbackHandler().
Variable Documentation
Cycle
uint8_t PS2Mouse::Cycle = 0
Definition at line 36 of file Mouse.cpp.
Referenced by InterruptCallback().
KAPI
KernelAPI PS2Mouse::KAPI
Definition at line 29 of file Mouse.cpp.
Referenced by DriverEntry(), and InterruptCallback().
MouseLeft
int PS2Mouse::MouseLeft = 0
Definition at line 32 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseMiddle
int PS2Mouse::MouseMiddle = 0
Definition at line 32 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseRight
int PS2Mouse::MouseRight = 0
Definition at line 32 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseX
int PS2Mouse::MouseX = 0
Definition at line 31 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseY
int PS2Mouse::MouseY = 0
Definition at line 31 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
MouseZ
int PS2Mouse::MouseZ = 0
Definition at line 31 of file Mouse.cpp.
Referenced by CallbackHandler().
Packet
uint8_t PS2Mouse::Packet[4]
Definition at line 34 of file Mouse.cpp.
Referenced by NetworkIPv4::__no_sanitize(), NetworkDHCP::__no_sanitize(), NetworkDHCP::DHCP::GetOption(), InterruptCallback(), NetworkEthernet::EthernetEvents::OnEthernetPacketSent(), NetworkICMPv4::ICMPv4::Receive(), NetworkEthernet::Ethernet::Receive(), NetworkEthernet::Ethernet::Send(), and NetworkIPv4::IPv4::Send().
PacketReady
bool PS2Mouse::PacketReady = false
Definition at line 35 of file Mouse.cpp.
Referenced by CallbackHandler(), and InterruptCallback().