Fennix: anonymous_namespace{pthread-stubs.cpp} Namespace Reference
anonymous_namespace{pthread-stubs.cpp} Namespace Reference
Data Structures
struct key_global_info
Functions
void sigcancel_handler (int signal, siginfo_t *info, void *ucontext)
void rwlock_m_lock (pthread_rwlock_t *rw, bool excl)
int rwlock_m_trylock (pthread_rwlock_t *rw, bool excl)
void rwlock_m_unlock (pthread_rwlock_t *rw)
Variables
constinit frg::array< key_global_info, PTHREAD_KEYS_MAX > key_globals_ {}
FutexLock key_mutex_
Function Documentation
rwlock_m_lock()
void anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock (pthread_rwlock_t * rw, bool excl)
Definition at line 1431 of file pthread-stubs.cpp.
{
         unsigned int m_expected = __atomic_load_n(&rw->__mlibc_m, __ATOMIC_RELAXED);
         while(true) {
             if(m_expected) {
                 __ensure(m_expected & mutex_owner_mask);
                 // Try to set the waiters bit.
                 if(!(m_expected & mutex_waiters_bit)) {
                     unsigned int desired = m_expected | mutex_waiters_bit;
                     if(!__atomic_compare_exchange_n(&rw->__mlibc_m,
                             &m_expected, desired, false, __ATOMIC_RELAXED, __ATOMIC_RELAXED))
                         continue;
                 }
                 // Wait on the futex.
                 mlibc::sys_futex_wait((int *)&rw->__mlibc_m, m_expected | mutex_waiters_bit, nullptr);
                 // Opportunistically try to take the lock after we wake up.
                 m_expected = 0;
             }else{
                 // Try to lock the mutex.
                 unsigned int desired = 1;
                 if(excl)
                     desired |= mutex_excl_bit;
                 if(__atomic_compare_exchange_n(&rw->__mlibc_m,
                         &m_expected, desired, false, __ATOMIC_ACQUIRE, __ATOMIC_RELAXED))
                     break;
             }
         }
     }
References __ensure, __mlibc_fair_rwlock::__mlibc_m, mutex_excl_bit, mutex_owner_mask, mutex_waiters_bit, and mlibc::sys_futex_wait().
Referenced by pthread_rwlock_rdlock(), and pthread_rwlock_wrlock().
rwlock_m_trylock()
int anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock (pthread_rwlock_t * rw, bool excl)
Definition at line 1462 of file pthread-stubs.cpp.
{
         unsigned int m_expected = __atomic_load_n(&rw->__mlibc_m, __ATOMIC_RELAXED);
         if(!m_expected) {
             // Try to lock the mutex.
             unsigned int desired = 1;
             if(excl)
                 desired |= mutex_excl_bit;
             if(__atomic_compare_exchange_n(&rw->__mlibc_m,
                     &m_expected, desired, false, __ATOMIC_ACQUIRE, __ATOMIC_RELAXED))
                 return 0;
         }
         __ensure(m_expected & mutex_owner_mask);
         // POSIX says that this function should never block but also that
         // readers should not be blocked by readers. We implement this by returning EAGAIN
         // (and not EBUSY) if a reader would block a reader.
         if(!excl && !(m_expected & mutex_excl_bit))
             return EAGAIN;
         return EBUSY;
     }
References __ensure, __mlibc_fair_rwlock::__mlibc_m, EAGAIN, EBUSY, mutex_excl_bit, and mutex_owner_mask.
Referenced by pthread_rwlock_tryrdlock(), and pthread_rwlock_trywrlock().
rwlock_m_unlock()
void anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock (pthread_rwlock_t * rw)
Definition at line 1485 of file pthread-stubs.cpp.
{
         auto m = __atomic_exchange_n(&rw->__mlibc_m, 0, __ATOMIC_RELEASE);
         if(m & mutex_waiters_bit)
             mlibc::sys_futex_wake((int *)&rw->__mlibc_m);
     }
References __mlibc_fair_rwlock::__mlibc_m, mutex_waiters_bit, and mlibc::sys_futex_wake().
Referenced by pthread_rwlock_rdlock(), pthread_rwlock_tryrdlock(), pthread_rwlock_trywrlock(), and pthread_rwlock_unlock().
sigcancel_handler()
void anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler (int signal, siginfo_t * info, void * ucontext)
Definition at line 557 of file pthread-stubs.cpp.
{
         ucontext_t *uctx = static_cast<ucontext_t*>(ucontext);
         // The function could be called from other signals, or from another
         // process, in which case we should do nothing.
         if (signal != SIGCANCEL || info->si_pid != getpid() ||
                 info->si_code != SI_TKILL)
             return;
         auto tcb = reinterpret_cast<Tcb*>(mlibc::get_current_tcb());
         int old_value = tcb->cancelBits;
         /*
          * When a thread is marked with deferred cancellation and performs a blocking syscall,
          * the spec mandates that the syscall can get interrupted before it has caused any side
          * effects (e.g. before a read() has read any bytes from disk). If the syscall has
          * already caused side effects it should return its partial work, and set the program
          * counter just after the syscall. If the syscall hasn't caused any side effects, it
          * should fail with EINTR and set the program counter to the syscall instruction.
          *
          *  cancellable_syscall:
          *      test whether_a_cancel_is_queued
          *      je cancel
          *      syscall
          *  end_cancellable_syscall
          *
          * The mlibc::sys_before_cancellable_syscall sysdep should return 1 when the
          * program counter is between the 'canellable_syscall' and 'end_cancellable_syscall' label.
          */
         if (!(old_value & tcbCancelAsyncBit) &&
                 mlibc::sys_before_cancellable_syscall && !mlibc::sys_before_cancellable_syscall(uctx))
             return;
         int bitmask = tcbCancelTriggerBit | tcbCancelingBit;
         while (1) {
             int new_value = old_value | bitmask;
             // Check if we are already cancelled or exiting
             if (old_value == new_value || old_value & tcbExitingBit)
                 return;
             int current_value = old_value;
             if (__atomic_compare_exchange_n(&tcb->cancelBits, &current_value,
                         new_value, true,__ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
                 tcb->returnValue = PTHREAD_CANCELED;
                 // Perform cancellation
                 __mlibc_do_cancel();
                 break;
             }
             old_value = current_value;
         }
     }
References __mlibc_do_cancel(), Tcb::cancelBits, mlibc::get_current_tcb(), getpid(), info, PTHREAD_CANCELED, SI_TKILL, SIGCANCEL, signal(), mlibc::sys_before_cancellable_syscall(), anonymous_namespace{tcb.hpp}::tcbCancelAsyncBit, anonymous_namespace{tcb.hpp}::tcbCancelingBit, anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and anonymous_namespace{tcb.hpp}::tcbExitingBit.
Referenced by mlibc::anonymous_namespace{pthread-stubs.cpp}::PthreadSignalInstaller::PthreadSignalInstaller().
Variable Documentation
key_globals_
constinit frg::array< key_global_info, PTHREAD_KEYS_MAX > anonymous_namespace{pthread-stubs.cpp}::key_globals_ {}
Definition at line 392 of file pthread-stubs.cpp.
Referenced by pthread_exit(), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), and pthread_setspecific().
key_mutex_
FutexLock anonymous_namespace{pthread-stubs.cpp}::key_mutex_
Definition at line 394 of file pthread-stubs.cpp.
Referenced by pthread_exit(), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), and pthread_setspecific().