Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/am_map.h File Reference
am_map.h File Reference
#include "d_event.h"
#include "m_cheat.h"
Macros
#define AM_MSGHEADER (('a'<<24)+('m'<<16))
#define AM_MSGENTERED (AM_MSGHEADER | ('e'<<8))
#define AM_MSGEXITED (AM_MSGHEADER | ('x'<<8))
Functions
boolean AM_Responder (event_t *ev)
void AM_Ticker (void)
void AM_Drawer (void)
void AM_Stop (void)
Variables
cheatseq_t cheat_amap
Macro Definition Documentation
AM_MSGENTERED
#define AM_MSGENTERED (AM_MSGHEADER | ('e'<<8))
Definition at line 27 of file am_map.h.
AM_MSGEXITED
#define AM_MSGEXITED (AM_MSGHEADER | ('x'<<8))
Definition at line 28 of file am_map.h.
AM_MSGHEADER
#define AM_MSGHEADER (('a'<<24)+('m'<<16))
Definition at line 26 of file am_map.h.
Function Documentation
AM_Drawer()
void AM_Drawer (void)
Definition at line 1338 of file am_map.c.
 {
     if (!automapactive) return;
     AM_clearFB(BACKGROUND);
     if (grid)
     AM_drawGrid(GRIDCOLORS);
     AM_drawWalls();
     AM_drawPlayers();
     if (cheating==2)
     AM_drawThings(THINGCOLORS, THINGRANGE);
     AM_drawCrosshair(XHAIRCOLORS);
     AM_drawMarks();
     V_MarkRect(f_x, f_y, f_w, f_h);
 }
References AM_clearFB(), AM_drawCrosshair(), AM_drawGrid(), AM_drawMarks(), AM_drawPlayers(), AM_drawThings(), AM_drawWalls(), automapactive, BACKGROUND, cheating, f_h, f_w, f_x, f_y, grid, GRIDCOLORS, THINGCOLORS, THINGRANGE, V_MarkRect(), and XHAIRCOLORS.
Referenced by D_Display().
AM_Responder()
boolean AM_Responder (event_t * ev)
Definition at line 595 of file am_map.c.
 {
     int rc;
     static int bigstate=0;
     static char buffer[20];
     int key;
     rc = false;
     if (!automapactive)
     {
     if (ev->type == ev_keydown && ev->data1 == key_map_toggle)
     {
         AM_Start ();
         viewactive = false;
         rc = true;
     }
     }
     else if (ev->type == ev_keydown)
     {
     rc = true;
         key = ev->data1;
         if (key == key_map_east)          // pan right
         {
             if (!followplayer) m_paninc.x = FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_west)     // pan left
         {
             if (!followplayer) m_paninc.x = -FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_north)    // pan up
         {
             if (!followplayer) m_paninc.y = FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_south)    // pan down
         {
             if (!followplayer) m_paninc.y = -FTOM(F_PANINC);
             else rc = false;
         }
         else if (key == key_map_zoomout)  // zoom out
         {
             mtof_zoommul = M_ZOOMOUT;
             ftom_zoommul = M_ZOOMIN;
         }
         else if (key == key_map_zoomin)   // zoom in
         {
             mtof_zoommul = M_ZOOMIN;
             ftom_zoommul = M_ZOOMOUT;
         }
         else if (key == key_map_toggle)
         {
             bigstate = 0;
             viewactive = true;
             AM_Stop ();
         }
         else if (key == key_map_maxzoom)
         {
             bigstate = !bigstate;
             if (bigstate)
             {
                 AM_saveScaleAndLoc();
                 AM_minOutWindowScale();
             }
             else AM_restoreScaleAndLoc();
         }
         else if (key == key_map_follow)
         {
             followplayer = !followplayer;
             f_oldloc.x = __INT_MAX__;
             if (followplayer)
                 plr->message = DEH_String(AMSTR_FOLLOWON);
             else
                 plr->message = DEH_String(AMSTR_FOLLOWOFF);
         }
         else if (key == key_map_grid)
         {
             grid = !grid;
             if (grid)
                 plr->message = DEH_String(AMSTR_GRIDON);
             else
                 plr->message = DEH_String(AMSTR_GRIDOFF);
         }
         else if (key == key_map_mark)
         {
             M_snprintf(buffer, sizeof(buffer), "%s %d",
                        DEH_String(AMSTR_MARKEDSPOT), markpointnum);
             plr->message = buffer;
             AM_addMark();
         }
         else if (key == key_map_clearmark)
         {
             AM_clearMarks();
             plr->message = DEH_String(AMSTR_MARKSCLEARED);
         }
         else
         {
             rc = false;
         }
     if (!deathmatch && cht_CheckCheat(&cheat_amap, ev->data2))
     {
         rc = false;
         cheating = (cheating+1) % 3;
     }
     }
     else if (ev->type == ev_keyup)
     {
         rc = false;
         key = ev->data1;
         if (key == key_map_east)
         {
             if (!followplayer) m_paninc.x = 0;
         }
         else if (key == key_map_west)
         {
             if (!followplayer) m_paninc.x = 0;
         }
         else if (key == key_map_north)
         {
             if (!followplayer) m_paninc.y = 0;
         }
         else if (key == key_map_south)
         {
             if (!followplayer) m_paninc.y = 0;
         }
         else if (key == key_map_zoomout || key == key_map_zoomin)
         {
             mtof_zoommul = FRACUNIT;
             ftom_zoommul = FRACUNIT;
         }
     }
     return rc;
 }
References AM_addMark(), AM_clearMarks(), AM_minOutWindowScale(), AM_restoreScaleAndLoc(), AM_saveScaleAndLoc(), AM_Start(), AM_Stop(), AMSTR_FOLLOWOFF, AMSTR_FOLLOWON, AMSTR_GRIDOFF, AMSTR_GRIDON, AMSTR_MARKEDSPOT, AMSTR_MARKSCLEARED, automapactive, buffer, cheat_amap, cheating, cht_CheckCheat(), event_t::data1, event_t::data2, deathmatch, DEH_String, ev_keydown, ev_keyup, f_oldloc, F_PANINC, followplayer, FRACUNIT, FTOM, ftom_zoommul, grid, key_map_clearmark, key_map_east, key_map_follow, key_map_grid, key_map_mark, key_map_maxzoom, key_map_north, key_map_south, key_map_toggle, key_map_west, key_map_zoomin, key_map_zoomout, m_paninc, M_snprintf(), M_ZOOMIN, M_ZOOMOUT, markpointnum, player_s::message, mtof_zoommul, plr, event_t::type, viewactive, mpoint_t::x, and mpoint_t::y.
Referenced by G_Responder().
AM_Stop()
void AM_Stop (void)
Definition at line 541 of file am_map.c.
 {
     static event_t st_notify = { 0, ev_keyup, AM_MSGEXITED, 0 };
     AM_unloadPics();
     automapactive = false;
     ST_Responder(&st_notify);
     stopped = true;
 }
References AM_MSGEXITED, AM_unloadPics(), automapactive, ev_keyup, ST_Responder(), and stopped.
Referenced by AM_Responder(), AM_Start(), G_DoCompleted(), and P_KillMobj().
AM_Ticker()
void AM_Ticker (void)
Definition at line 806 of file am_map.c.
 {
     if (!automapactive)
     return;
     amclock++;
     if (followplayer)
     AM_doFollowPlayer();
     // Change the zoom if necessary
     if (ftom_zoommul != FRACUNIT)
     AM_changeWindowScale();
     // Change x,y location
     if (m_paninc.x || m_paninc.y)
     AM_changeWindowLoc();
     // Update light level
     // AM_updateLightLev();
 }
References AM_changeWindowLoc(), AM_changeWindowScale(), AM_doFollowPlayer(), amclock, automapactive, followplayer, FRACUNIT, ftom_zoommul, m_paninc, mpoint_t::x, and mpoint_t::y.
Referenced by G_Ticker().
Variable Documentation
cheat_amap
cheatseq_t cheat_amap extern
Definition at line 266 of file am_map.c.
Referenced by AM_Responder().