Fennix Userspace: Userspace/apps/base/busybox/procps/pstree.c File Reference
pstree.c File Reference
#include "libbb.h"
Data Structures
struct proc
struct child
struct globals
Macros
#define PROC_BASE "/proc"
#define OPT_PID (1 << 0)
#define COMM_DISP_LEN COMM_LEN
#define empty_2 " "
#define branch_2 "|-"
#define vert_2 "| "
#define last_2 "`-"
#define single_3 "---"
#define first_3 "-+-"
#define G (*ptr_to_globals)
#define INIT_G()
Typedefs
typedef struct proc PROC
typedef struct child CHILD
Functions
static void ensure_buffer_capacity (int bufindex)
static void out_char (char c)
static void out_string (const char *str)
static void out_newline (void)
static PROC * find_proc (pid_t pid)
static PROC * new_proc (const char *comm, pid_t pid, uid_t uid)
static void add_child (PROC *parent, PROC *child)
static void add_proc (const char *comm, pid_t pid, pid_t ppid, uid_t uid)
static int tree_equal (const PROC *a, const PROC *b)
static int out_args (const char *mystr)
static void dump_tree (PROC *current, int level, int rep, int leaf, int last, int closing)
static void dump_by_user (PROC *current, uid_t uid)
static void mread_proc (void)
int pstree_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
proc
struct proc
Definition at line 43 of file pstree.c.
Data Fields
struct child * children
char comm[COMM_DISP_LEN+1]
struct proc * next
struct proc * parent
pid_t pid
uid_t uid
child
struct child
Definition at line 56 of file pstree.c.
Data Fields
PROC * child
struct child * next
Macro Definition Documentation
branch_2
#define branch_2 "|-"
Definition at line 62 of file pstree.c.
COMM_DISP_LEN
#define COMM_DISP_LEN COMM_LEN
Definition at line 40 of file pstree.c.
empty_2
#define empty_2 " "
Definition at line 61 of file pstree.c.
first_3
#define first_3 "-+-"
Definition at line 66 of file pstree.c.
G
#define G (*ptr_to_globals)
Definition at line 82 of file pstree.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 83 of file pstree.c.
last_2
#define last_2 "`-"
Definition at line 64 of file pstree.c.
OPT_PID
#define OPT_PID (1 << 0)
Definition at line 32 of file pstree.c.
PROC_BASE
#define PROC_BASE "/proc"
Definition at line 30 of file pstree.c.
single_3
#define single_3 "---"
Definition at line 65 of file pstree.c.
vert_2
#define vert_2 "| "
Definition at line 63 of file pstree.c.
Typedef Documentation
CHILD
typedef struct child CHILD
PROC
typedef struct proc PROC
Function Documentation
add_child()
static void add_child (PROC * parent, PROC * child) static
Definition at line 155 of file pstree.c.
 {
     CHILD *new, **walk;
     int cmp;
     new = xmalloc(sizeof(*new));
     new->child = child;
     for (walk = &parent->children; *walk; walk = &(*walk)->next) {
         cmp = strcmp((*walk)->child->comm, child->comm);
         if (cmp > 0)
             break;
         if (cmp == 0 && (*walk)->child->uid > child->uid)
             break;
     }
     new->next = *walk;
     *walk = new;
 }
References child(), cmp(), parent, strcmp, walk(), and xmalloc.
Referenced by add_proc().
add_proc()
static void add_proc (const char * comm, pid_t pid, pid_t ppid, uid_t uid) static
Definition at line 174 of file pstree.c.
 {
     PROC *this, *parent;
     this = find_proc(pid);
     if (!this)
         this = new_proc(comm, pid, uid);
     else {
         strcpy(this->comm, comm);
         this->uid = uid;
     }
     if (pid == ppid)
         ppid = 0;
 //  if (isthread)
 //      this->flags |= PFLAG_THREAD;
     parent = find_proc(ppid);
     if (!parent)
         parent = new_proc("?", ppid, 0);
     add_child(parent, this);
     this->parent = parent;
 }
References add_child(), find_proc(), new_proc(), parent, pid, and strcpy().
Referenced by mread_proc().
dump_by_user()
static void dump_by_user (PROC * current, uid_t uid) static
Definition at line 329 of file pstree.c.
 {
     const CHILD *walk;
     if (!current)
         return;
     if (current->uid == uid) {
         if (G.dumped)
             putchar('\n');
         dump_tree(current, 0, 1, 1, 1, 0);
         G.dumped = 1;
         return;
     }
     for (walk = current->children; walk; walk = walk->next)
         dump_by_user(walk->child, uid);
 }
References current, dump_tree(), G, putchar, and walk().
Referenced by pstree_main().
dump_tree()
static void dump_tree (PROC * current, int level, int rep, int leaf, int last, int closing) static
Definition at line 244 of file pstree.c.
 {
     CHILD *walk, *next, **scan;
     int lvl, i, add, offset, count, comm_len, first;
     char tmp[sizeof(int)*3 + 4];
     if (!current)
         return;
     if (!leaf) {
         for (lvl = 0; lvl < level; lvl++) {
             i = G.width[lvl] + 1;
             while (--i >= 0)
                 out_char(' ');
             if (lvl == level - 1) {
                 if (last) {
                     out_string(last_2);
                 } else {
                     out_string(branch_2);
                 }
             } else {
                 if (G.more[lvl + 1]) {
                     out_string(vert_2);
                 } else {
                     out_string(empty_2);
                 }
             }
         }
     }
     add = 0;
     if (rep > 1) {
         add += sprintf(tmp, "%d*[", rep);
         out_string(tmp);
     }
     comm_len = out_args(current->comm);
     if (option_mask32 /*& OPT_PID*/) {
         comm_len += sprintf(tmp, "(%d)", (int)current->pid);
         out_string(tmp);
     }
     offset = G.cur_x;
     if (!current->children) {
         while (closing--)
             out_char(']');
         out_newline();
     }
     ensure_buffer_capacity(level);
     G.more[level] = !last;
     G.width[level] = comm_len + G.cur_x - offset + add;
     if (G.cur_x >= G.output_width) {
         //out_string(first_3); - why? it won't print anything
         //out_char('+');
         out_newline();
         return;
     }
     first = 1;
     for (walk = current->children; walk; walk = next) {
         count = 0;
         next = walk->next;
         scan = &walk->next;
         while (*scan) {
             if (!tree_equal(walk->child, (*scan)->child))
                 scan = &(*scan)->next;
             else {
                 if (next == *scan)
                     next = (*scan)->next;
                 count++;
                 *scan = (*scan)->next;
             }
         }
         if (first) {
             out_string(next ? first_3 : single_3);
             first = 0;
         }
         dump_tree(walk->child, level + 1, count + 1,
                 walk == current->children, !next,
                 closing + (count ? 1 : 0));
     }
 }
References add(), branch_2, count, current, empty_2, ensure_buffer_capacity(), first, first_3, G, i, last, last_2, leaf, child::next, next, offset, option_mask32, out_args(), out_char(), out_newline(), out_string(), single_3, sprintf(), tree_equal(), vert_2, and walk().
Referenced by dump_by_user(), and pstree_main().
ensure_buffer_capacity()
static void ensure_buffer_capacity (int bufindex) static
Definition at line 94 of file pstree.c.
 {
     if (bufindex >= G.capacity) {
         G.capacity += 0x100;
         G.width = xrealloc(G.width, G.capacity * sizeof(G.width[0]));
         G.more = xrealloc(G.more, G.capacity * sizeof(G.more[0]));
     }
 }
References G, and xrealloc.
Referenced by dump_tree().
find_proc()
static PROC* find_proc (pid_t pid) static
Definition at line 131 of file pstree.c.
 {
     PROC *walk;
     for (walk = G.list; walk; walk = walk->next)
         if (walk->pid == pid)
             break;
     return walk;
 }
References G, pid, and walk().
Referenced by add_proc(), and pstree_main().
mread_proc()
static void mread_proc (void) static
Definition at line 356 of file pstree.c.
 {
     procps_status_t *p = NULL;
 #if ENABLE_FEATURE_SHOW_THREADS
     pid_t parent = 0;
 #endif
     int flags = PSSCAN_COMM | PSSCAN_PID | PSSCAN_PPID | PSSCAN_UIDGID | PSSCAN_TASKS;
     while ((p = procps_scan(p, flags)) != NULL) {
 #if ENABLE_FEATURE_SHOW_THREADS
         if (p->pid != p->main_thread_pid)
             handle_thread(p->comm, p->pid, parent, p->uid);
         else
 #endif
         {
             add_proc(p->comm, p->pid, p->ppid, p->uid/*, 0*/);
 #if ENABLE_FEATURE_SHOW_THREADS
             parent = p->pid;
 #endif
         }
     }
 }
References add_proc(), flags, NULL, p, parent, procps_scan(), PSSCAN_COMM, PSSCAN_PID, PSSCAN_PPID, PSSCAN_TASKS, and PSSCAN_UIDGID.
Referenced by pstree_main().
new_proc()
static PROC* new_proc (const char * comm, pid_t pid, uid_t uid) static
Definition at line 142 of file pstree.c.
 {
     PROC *new = xzalloc(sizeof(*new));
     strcpy(new->comm, comm);
     new->pid = pid;
     new->uid = uid;
     new->next = G.list;
     G.list = new;
     return G.list;
 }
References G, pid, strcpy(), and xzalloc().
Referenced by add_proc().
out_args()
static int out_args (const char * mystr) static
Definition at line 220 of file pstree.c.
 {
     const char *here;
     int strcount = 0;
     char tmpstr[5];
     for (here = mystr; *here; here++) {
         if (*here == '\\') {
             out_string("\\\\");
             strcount += 2;
         } else if (*here >= ' ' && *here < 0x7f) {
             out_char(*here);
             strcount++;
         } else {
             sprintf(tmpstr, "\\%03o", (unsigned char) *here);
             out_string(tmpstr);
             strcount += 4;
         }
     }
     return strcount;
 }
References out_char(), out_string(), and sprintf().
Referenced by dump_tree().
out_char()
static void out_char (char c) static
Definition at line 106 of file pstree.c.
 {
     G.cur_x++;
     if (G.cur_x > G.output_width)
         return;
     if (G.cur_x == G.output_width)
         c = '+';
     putchar(c);
 }
References c, G, and putchar.
Referenced by dump_tree(), out_args(), and out_string().
out_newline()
static void out_newline (void) static
Definition at line 125 of file pstree.c.
 {
     putchar('\n');
     G.cur_x = 0;
 }
References G, and putchar.
Referenced by dump_tree().
out_string()
static void out_string (const char * str) static
Definition at line 119 of file pstree.c.
 {
     while (*str)
         out_char(*str++);
 }
References out_char(), and str.
Referenced by dump_tree(), and out_args().
pstree_main()
int pstree_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 380 of file pstree.c.
 {
     pid_t pid = 1;
     long uid = 0;
     INIT_G();
     G.output_width = get_terminal_width(0);
     getopt32(argv, "^" "p" "\0" "?1");
     argv += optind;
     if (argv[0]) {
         if (argv[0][0] >= '0' && argv[0][0] <= '9') {
             pid = xatoi(argv[0]);
         } else {
             uid = xuname2uid(argv[0]);
         }
     }
     mread_proc();
     if (!uid)
         dump_tree(find_proc(pid), 0, 1, 1, 1, 0);
     else {
         dump_by_user(find_proc(1), uid);
         if (!G.dumped) {
             bb_simple_error_msg_and_die("no processes found");
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(G.width);
         free(G.more);
     }
     return 0;
 }
References argv, bb_simple_error_msg_and_die(), dump_by_user(), dump_tree(), find_proc(), free, G, get_terminal_width(), getopt32(), INIT_G, mread_proc(), optind, pid, and xuname2uid().
tree_equal()
static int tree_equal (const PROC * a, const PROC * b) static
Definition at line 200 of file pstree.c.
 {
     const CHILD *walk_a, *walk_b;
     if (strcmp(a->comm, b->comm) != 0)
         return 0;
     if ((option_mask32 /*& OPT_PID*/) && a->pid != b->pid)
         return 0;
     for (walk_a = a->children, walk_b = b->children;
       walk_a && walk_b;
       walk_a = walk_a->next, walk_b = walk_b->next
     ) {
         if (!tree_equal(walk_a->child, walk_b->child))
             return 0;
     }
     return !(walk_a || walk_b);
 }
References child::child, proc::children, proc::comm, child::next, option_mask32, proc::pid, and strcmp.
Referenced by dump_tree().