Fennix: Userspace/musl/src/ldso/dlerror.c File Reference
dlerror.c File Reference
#include <dlfcn.h>
#include <stdlib.h>
#include <stdarg.h>
#include "pthread_impl.h"
#include "dynlink.h"
#include "atomic.h"
Macros
#define malloc __libc_malloc
#define calloc __libc_calloc
#define realloc __libc_realloc
#define free __libc_free
Functions
char * dlerror ()
void __dl_thread_cleanup (void)
hidden void __dl_vseterr (const char *fmt, va_list ap)
hidden void __dl_seterr (const char *fmt,...)
static int stub_invalid_handle (void *h)
weak_alias (stub_invalid_handle, __dl_invalid_handle)
Variables
static void *volatile freebuf_queue
Macro Definition Documentation
calloc
#define calloc __libc_calloc
Definition at line 9 of file dlerror.c.
free
#define free __libc_free
Definition at line 11 of file dlerror.c.
malloc
#define malloc __libc_malloc
Definition at line 8 of file dlerror.c.
realloc
#define realloc __libc_realloc
Definition at line 10 of file dlerror.c.
Function Documentation
__dl_seterr()
hidden void __dl_seterr (const char * fmt, ...)
Definition at line 75 of file dlerror.c.
 {
     va_list ap;
     va_start(ap, fmt);
     __dl_vseterr(fmt, ap);
     va_end(ap);
 }
References __dl_vseterr(), ap, va_end, and va_start.
Referenced by dlinfo(), stub_dlopen(), stub_dlsym(), and stub_invalid_handle().
__dl_thread_cleanup()
void __dl_thread_cleanup (void)
Definition at line 33 of file dlerror.c.
 {
     pthread_t self = __pthread_self();
     if (!self->dlerror_buf || self->dlerror_buf == (void *)-1)
         return;
     void *h;
     do {
         h = freebuf_queue;
         *(void **)self->dlerror_buf = h;
     } while (a_cas_p(&freebuf_queue, h, self->dlerror_buf) != h);
 }
References __pthread_self, a_cas_p, freebuf_queue, and h.
Referenced by __pthread_exit().
__dl_vseterr()
hidden void __dl_vseterr (const char * fmt, va_list ap)
Definition at line 45 of file dlerror.c.
 {
     void **q;
     do q = freebuf_queue;
     while (q && a_cas_p(&freebuf_queue, q, 0) != q);
     while (q) {
         void **p = *q;
         free(q);
         q = p;
     }
     va_list ap2;
     va_copy(ap2, ap);
     pthread_t self = __pthread_self();
     if (self->dlerror_buf != (void *)-1)
         free(self->dlerror_buf);
     size_t len = vsnprintf(0, 0, fmt, ap2);
     if (len < sizeof(void *)) len = sizeof(void *);
     va_end(ap2);
     char *buf = malloc(len+1);
     if (buf) {
         vsnprintf(buf, len+1, fmt, ap);
     } else {
         buf = (void *)-1;
     }
     self->dlerror_buf = buf;
     self->dlerror_flag = 1;
 }
References __pthread_self, a_cas_p, ap, buf, free, freebuf_queue, len, malloc, p, va_copy, va_end, and vsnprintf().
Referenced by __dl_seterr(), and error_impl().
dlerror()
char* dlerror (void)
Definition at line 13 of file dlerror.c.
 {
     pthread_t self = __pthread_self();
     if (!self->dlerror_flag) return 0;
     self->dlerror_flag = 0;
     char *s = self->dlerror_buf;
     if (s == (void *)-1)
         return "Dynamic linker failed to allocate memory for error message";
     else
         return s;
 }
References __pthread_self, and s.
stub_invalid_handle()
static int stub_invalid_handle (void * h) static
Definition at line 83 of file dlerror.c.
 {
     __dl_seterr("Invalid library handle %p", (void *)h);
     return 1;
 }
References __dl_seterr(), and h.
weak_alias()
weak_alias (stub_invalid_handle , __dl_invalid_handle)
Variable Documentation
freebuf_queue
void* volatile freebuf_queue static
Definition at line 31 of file dlerror.c.
Referenced by __dl_thread_cleanup(), and __dl_vseterr().