Fennix: Kernel/Library/cxxabi.cpp File Reference
cxxabi.cpp File Reference
#include <types.h>
#include <memory.hpp>
#include <debug.h>
Data Structures
struct atexit_func_entry_t
struct type_info
struct unexpected_handler
struct terminate_handler
struct _Unwind_Exception
struct __cxa_exception
Macros
#define ATEXIT_MAX_FUNCS 128
Typedefs
typedef unsigned uarch_t
typedef unsigned _Unwind_Ptr __attribute__((__mode__(__pointer__)))
typedef void(* _Unwind_Exception_Cleanup_Fn) (_Unwind_Reason_Code, struct _Unwind_Exception *)
typedef int _Unwind_Action
Enumerations
enum _Unwind_Reason_Code {
_URC_NO_REASON = 0 , _URC_FOREIGN_EXCEPTION_CAUGHT = 1 , _URC_FATAL_PHASE2_ERROR = 2 , _URC_FATAL_PHASE1_ERROR = 3 ,
_URC_NORMAL_STOP = 4 , _URC_END_OF_STACK = 5 , _URC_HANDLER_FOUND = 6 , _URC_INSTALL_CONTEXT = 7 ,
_URC_CONTINUE_UNWIND = 8 , _URC_NO_REASON = 0 , _URC_FOREIGN_EXCEPTION_CAUGHT = 1 , _URC_FATAL_PHASE2_ERROR = 2 ,
_URC_FATAL_PHASE1_ERROR = 3 , _URC_NORMAL_STOP = 4 , _URC_END_OF_STACK = 5 , _URC_HANDLER_FOUND = 6 ,
_URC_INSTALL_CONTEXT = 7 , _URC_CONTINUE_UNWIND = 8
}
Functions
struct _Unwind_Exception __attribute__ ((__aligned__))
int __cxa_atexit (void(*f)(void *), void *objptr, void *dso)
void __cxa_finalize (void *f)
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception *ue_header, _Unwind_Context *context)
void _Unwind_Resume (struct _Unwind_Exception *exc)
static size_t align_exception_allocation_size (size_t s, size_t a)
void unexpected_header_stub ()
void terminate_header_stub ()
void * __cxa_allocate_exception (size_t thrown_size) throw ()
void _Unwind_RaiseException (_Unwind_Exception *exc)
void __cxa_throw (void *thrown_object, void *tinfo, void(*dest)(void *))
void __cxa_rethrow ()
void __cxa_pure_virtual ()
void __cxa_throw_bad_array_new_length ()
void __cxa_free_exception (void *thrown_exception)
void * __cxa_begin_catch (void *e)
void __cxa_end_catch ()
__extension__ typedef int __guard __attribute__ ((mode(__DI__)))
int __cxa_guard_acquire (__guard *g)
void __cxa_guard_release (__guard *g)
void __cxa_guard_abort (__guard *g)
void * _ZTVN10__cxxabiv117__class_type_infoE (void)
void * _ZTVN10__cxxabiv120__si_class_type_infoE (void)
void * _ZTIi (void)
void * _ZTIPh (void)
void * _ZTIPKc (void)
Variables
_Unwind_Exception_Class exception_class
_Unwind_Exception_Cleanup_Fn exception_cleanup
_Unwind_Word private_1
_Unwind_Word private_2
void * __dso_handle = 0
atexit_func_entry_t __atexit_funcs [ATEXIT_MAX_FUNCS]
uarch_t __atexit_func_count = 0
Data Structure Documentation
type_info
struct type_info
Definition at line 44 of file cxxabi.cpp.
Data Fields
const char * name
_Unwind_Exception
struct _Unwind_Exception
Definition at line 59 of file cxxabi.cpp.
Data Fields
_Unwind_Exception_Class exception_class
_Unwind_Exception_Cleanup_Fn exception_cleanup
_Unwind_Word private_1
_Unwind_Word private_2
Macro Definition Documentation
ATEXIT_MAX_FUNCS
#define ATEXIT_MAX_FUNCS 128
Definition at line 9 of file cxxabi.cpp.
Typedef Documentation
__attribute__
__attribute__
Definition at line 38 of file cxxabi.cpp.
_Unwind_Action
typedef int _Unwind_Action
Definition at line 42 of file cxxabi.cpp.
_Unwind_Exception_Cleanup_Fn
typedef void(* _Unwind_Exception_Cleanup_Fn) (_Unwind_Reason_Code, struct _Unwind_Exception *)
Definition at line 41 of file cxxabi.cpp.
uarch_t
typedef unsigned uarch_t
Definition at line 11 of file cxxabi.cpp.
Enumeration Type Documentation
_Unwind_Reason_Code
enum _Unwind_Reason_Code
Enumerator
_URC_NO_REASON
_URC_FOREIGN_EXCEPTION_CAUGHT
_URC_FATAL_PHASE2_ERROR
_URC_FATAL_PHASE1_ERROR
_URC_NORMAL_STOP
_URC_END_OF_STACK
_URC_HANDLER_FOUND
_URC_INSTALL_CONTEXT
_URC_CONTINUE_UNWIND
_URC_NO_REASON
_URC_FOREIGN_EXCEPTION_CAUGHT
_URC_FATAL_PHASE2_ERROR
_URC_FATAL_PHASE1_ERROR
_URC_NORMAL_STOP
_URC_END_OF_STACK
_URC_HANDLER_FOUND
_URC_INSTALL_CONTEXT
_URC_CONTINUE_UNWIND
Definition at line 24 of file cxxabi.cpp.
 {
     _URC_NO_REASON = 0,
     _URC_FOREIGN_EXCEPTION_CAUGHT = 1,
     _URC_FATAL_PHASE2_ERROR = 2,
     _URC_FATAL_PHASE1_ERROR = 3,
     _URC_NORMAL_STOP = 4,
     _URC_END_OF_STACK = 5,
     _URC_HANDLER_FOUND = 6,
     _URC_INSTALL_CONTEXT = 7,
     _URC_CONTINUE_UNWIND = 8
 } _Unwind_Reason_Code;
Function Documentation
__attribute__() [1/2]
struct _Unwind_Exception __attribute__ ((__aligned__))
__attribute__() [2/2]
__extension__ typedef int __guard __attribute__ ((mode(__DI__)))
__cxa_allocate_exception()
void* __cxa_allocate_exception (size_t thrown_size) throw ()
Definition at line 149 of file cxxabi.cpp.
 {
     fixme("__cxa_allocate_exception( %d ) triggered.", thrown_size);
     size_t real_size = align_exception_allocation_size(thrown_size + sizeof(__cxa_exception), alignof(__cxa_exception));
     __cxa_exception *header = (__cxa_exception *)kmalloc(real_size);
     if (!header)
     {
         error("Failed to allocate exception.");
         return nullptr;
     }
     header->referenceCount = 1;
     header->exceptionType = nullptr;
     header->exceptionDestructor = nullptr;
     header->unexpectedHandler = {.unexpected = unexpected_header_stub};
     header->terminateHandler = {.handler = terminate_header_stub};
     header->nextException = nullptr;
     header->handlerCount = -1;
     header->handlerSwitchValue = 0;
     header->actionRecord = nullptr;
     header->languageSpecificData = nullptr;
     header->catchTemp = 0;
     header->adjustedPtr = nullptr;
     return header + 1;
 }
References __cxa_exception::actionRecord, __cxa_exception::adjustedPtr, align_exception_allocation_size(), __cxa_exception::catchTemp, error, __cxa_exception::exceptionDestructor, __cxa_exception::exceptionType, fixme, terminate_handler::handler, __cxa_exception::handlerCount, __cxa_exception::handlerSwitchValue, kmalloc, __cxa_exception::languageSpecificData, __cxa_exception::nextException, __cxa_exception::referenceCount, terminate_header_stub(), __cxa_exception::terminateHandler, unexpected_handler::unexpected, unexpected_header_stub(), and __cxa_exception::unexpectedHandler.
__cxa_atexit()
int __cxa_atexit (void(*)(void *) f, void * objptr, void * dso)
Definition at line 103 of file cxxabi.cpp.
 {
     fixme("__cxa_atexit( %p %p %p ) triggered.", f, objptr, dso);
     if (__atexit_func_count >= ATEXIT_MAX_FUNCS)
         return -1;
     __atexit_funcs[__atexit_func_count].destructor_func = f;
     __atexit_funcs[__atexit_func_count].obj_ptr = objptr;
     __atexit_funcs[__atexit_func_count].dso_handle = dso;
     __atexit_func_count++;
     return 0;
 }
References __atexit_func_count, __atexit_funcs, ATEXIT_MAX_FUNCS, atexit_func_entry_t::destructor_func, atexit_func_entry_t::dso_handle, fixme, and atexit_func_entry_t::obj_ptr.
__cxa_begin_catch()
void* __cxa_begin_catch (void * e)
Definition at line 219 of file cxxabi.cpp.
 {
     fixme("__cxa_begin_catch( %p ) triggered.", e);
     return (void *)0;
 }
References fixme.
__cxa_end_catch()
void __cxa_end_catch ()
Definition at line 226 of file cxxabi.cpp.
 { fixme("__cxa_end_catch() triggered."); }
References fixme.
__cxa_finalize()
void __cxa_finalize (void * f)
Definition at line 115 of file cxxabi.cpp.
 {
     fixme("__cxa_finalize( %p ) triggered.", f);
     uarch_t i = __atexit_func_count;
     if (!f)
     {
         while (i--)
             if (__atexit_funcs[i].destructor_func)
                 (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
         return;
     }
     while (i--)
         if (__atexit_funcs[i].destructor_func == f)
         {
             (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
             __atexit_funcs[i].destructor_func = 0;
         }
 }
References __atexit_func_count, __atexit_funcs, atexit_func_entry_t::destructor_func, fixme, and i.
__cxa_free_exception()
void __cxa_free_exception (void * thrown_exception)
Definition at line 214 of file cxxabi.cpp.
 { fixme("__cxa_free_exception( %p ) triggered.", thrown_exception); }
References fixme.
__cxa_guard_abort()
void __cxa_guard_abort (__guard * g)
Definition at line 242 of file cxxabi.cpp.
 { fixme("__cxa_guard_abort( %p ) triggered.", g); }
References fixme, and g.
__cxa_guard_acquire()
int __cxa_guard_acquire (__guard * g)
Definition at line 230 of file cxxabi.cpp.
 {
     fixme("__cxa_guard_acquire( %p ) triggered.", g);
     return !*(char *)(g);
 }
References fixme, and g.
__cxa_guard_release()
void __cxa_guard_release (__guard * g)
Definition at line 236 of file cxxabi.cpp.
 {
     fixme("__cxa_guard_release( %p ) triggered.", g);
     *(char *)g = 1;
 }
References fixme, and g.
__cxa_pure_virtual()
void __cxa_pure_virtual ()
Definition at line 210 of file cxxabi.cpp.
 { fixme("__cxa_pure_virtual() triggered."); }
References fixme.
__cxa_rethrow()
void __cxa_rethrow ()
Definition at line 208 of file cxxabi.cpp.
 { fixme("__cxa_rethrow() triggered."); }
References fixme.
__cxa_throw()
void __cxa_throw (void * thrown_object, void * tinfo, void(*)(void *) dest)
Definition at line 197 of file cxxabi.cpp.
 {
     fixme("__cxa_throw( %p %p %p ) triggered.", thrown_object, tinfo, dest);
     __cxa_exception *header = ((__cxa_exception *)thrown_object) - 1;
     header->exceptionType = (type_info *)tinfo;
     header->exceptionDestructor = dest;
     _Unwind_RaiseException(&header->unwindHeader);
 }
References _Unwind_RaiseException(), __cxa_exception::exceptionDestructor, __cxa_exception::exceptionType, fixme, and __cxa_exception::unwindHeader.
__cxa_throw_bad_array_new_length()
void __cxa_throw_bad_array_new_length ()
Definition at line 212 of file cxxabi.cpp.
 { fixme("__cxa_throw_bad_array_new_length() triggered."); }
References fixme.
__gxx_personality_v0()
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception * ue_header, _Unwind_Context * context)
Definition at line 136 of file cxxabi.cpp.
 {
     fixme("__gxx_personality_v0( %d %p %p %p %p ) triggered.", version, actions, exception_class, ue_header, context);
     return _URC_NO_REASON;
 }
References _URC_NO_REASON, exception_class, and fixme.
_Unwind_RaiseException()
void _Unwind_RaiseException (_Unwind_Exception * exc)
Definition at line 178 of file cxxabi.cpp.
 {
     fixme("_Unwind_RaiseException( %p ) triggered.", exc);
     __cxa_exception *header = ((__cxa_exception *)exc) - 1;
     if (header->terminateHandler.handler)
     {
         debug("Calling terminate handler.");
         header->terminateHandler.handler();
     }
     else
     {
         error("Unhandled exception.");
         CPU::Stop();
     }
     CPU::Halt(true);
 }
References debug, error, fixme, CPU::Halt(), terminate_handler::handler, CPU::Stop(), and __cxa_exception::terminateHandler.
Referenced by __cxa_throw().
_Unwind_Resume()
void _Unwind_Resume (struct _Unwind_Exception * exc)
Definition at line 142 of file cxxabi.cpp.
 { fixme("_Unwind_Resume( %p ) triggered.", exc); }
References fixme.
_ZTIi()
void* _ZTIi (void)
Definition at line 259 of file cxxabi.cpp.
 {
     fixme("_ZTIi() triggered.");
     return (void *)0;
 }
References fixme.
_ZTIPh()
void* _ZTIPh (void)
Definition at line 266 of file cxxabi.cpp.
 {
     fixme("_ZTIPh() triggered.");
     return (void *)0;
 }
References fixme.
_ZTIPKc()
void* _ZTIPKc (void)
Definition at line 273 of file cxxabi.cpp.
 {
     fixme("_ZTIPKc() triggered.");
     return (void *)0;
 }
References fixme.
_ZTVN10__cxxabiv117__class_type_infoE()
void* _ZTVN10__cxxabiv117__class_type_infoE (void)
Definition at line 245 of file cxxabi.cpp.
 {
     fixme("_ZTVN10__cxxabiv117__class_type_infoE() triggered.");
     return (void *)0;
 }
References fixme.
_ZTVN10__cxxabiv120__si_class_type_infoE()
void* _ZTVN10__cxxabiv120__si_class_type_infoE (void)
Definition at line 252 of file cxxabi.cpp.
 {
     fixme("_ZTVN10__cxxabiv120__si_class_type_infoE() triggered.");
     return (void *)0;
 }
References fixme.
align_exception_allocation_size()
static size_t align_exception_allocation_size (size_t s, size_t a) inline static
Definition at line 144 of file cxxabi.cpp.
 { return (s + a - 1) & ~(a - 1); }
Referenced by __cxa_allocate_exception().
terminate_header_stub()
void terminate_header_stub ()
Definition at line 147 of file cxxabi.cpp.
 { fixme("terminate() called."); }
References fixme.
Referenced by __cxa_allocate_exception().
unexpected_header_stub()
void unexpected_header_stub ()
Definition at line 146 of file cxxabi.cpp.
 { fixme("unexpected() called."); }
References fixme.
Referenced by __cxa_allocate_exception().
Variable Documentation
__atexit_func_count
uarch_t __atexit_func_count = 0
Definition at line 101 of file cxxabi.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__atexit_funcs
atexit_func_entry_t __atexit_funcs[ATEXIT_MAX_FUNCS]
Definition at line 100 of file cxxabi.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__dso_handle
void* __dso_handle = 0
Definition at line 99 of file cxxabi.cpp.
exception_class
_Unwind_Exception_Class exception_class
Definition at line 0 of file cxxabi.cpp.
Referenced by __gxx_personality_v0().
exception_cleanup
_Unwind_Exception_Cleanup_Fn exception_cleanup
Definition at line 1 of file cxxabi.cpp.
private_1
_Unwind_Word private_1
Definition at line 5 of file cxxabi.cpp.
private_2
_Unwind_Word private_2
Definition at line 6 of file cxxabi.cpp.