Fennix Userspace: Userspace/mlibc/tests/rtdl/scope5/test.c File Reference
test.c File Reference
#include <dlfcn.h>
#include <stdio.h>
#include <assert.h>
Macros
#define LIBFOO "libfoo.so"
Functions
void foo ()
void bar ()
int main ()
Macro Definition Documentation
LIBFOO
#define LIBFOO "libfoo.so"
Definition at line 8 of file test.c.
Function Documentation
bar()
void bar ()
Definition at line 13 of file test.c.
 { foo(); }
References foo().
Referenced by main().
foo()
void foo ()
Definition at line 1 of file libfoo.c.
 { return 0; }
References baz().
Referenced by bar(), and main().
main()
int main (void)
Definition at line 15 of file test.c.
            {
     // In this test, we have exec -> foo (where '->' means 'depends on').
     // This means that foo is in the global scope due to DT_NEEDED.
     // We then dlopen it again with RTLD_LOCAL, which should just return
     // the already-loaded object, but used to crash in the mlibc linker instead.
     void *foo = dlopen(LIBFOO, RTLD_LOCAL | RTLD_NOW);
     assert(foo);
     assert(dlsym(foo, "foo"));
     assert(dlsym(RTLD_DEFAULT, "foo"));
     dlclose(foo);
 }
References assert, dlclose(), dlopen(), dlsym(), foo(), LIBFOO, RTLD_DEFAULT, RTLD_LOCAL, and RTLD_NOW.