Fennix Userspace: Userspace/musl/include/fenv.h File Reference
fenv.h File Reference
#include <bits/fenv.h>
Functions
int feclearexcept (int)
int fegetexceptflag (fexcept_t *, int)
int feraiseexcept (int)
int fesetexceptflag (const fexcept_t *, int)
int fetestexcept (int)
int fegetround (void)
int fesetround (int)
int fegetenv (fenv_t *)
int feholdexcept (fenv_t *)
int fesetenv (const fenv_t *)
int feupdateenv (const fenv_t *)
Function Documentation
feclearexcept()
int feclearexcept (int mask)
Definition at line 5 of file fenv.c.
 {
     return 0;
 }
References FE_ALL_EXCEPT, FE_INVALID, get_fpc(), get_fpscr(), set_fpc(), and set_fpscr().
Referenced by feholdexcept(), fesetexceptflag(), fmaf(), nearbyint(), nearbyintf(), and nearbyintl().
fegetenv()
int fegetenv (fenv_t * envp)
Definition at line 30 of file fenv.c.
 {
     return 0;
 }
References get_fpc(), and get_fpscr_f().
Referenced by feholdexcept().
fegetexceptflag()
int fegetexceptflag (fexcept_t * fp, int mask)
Definition at line 3 of file fegetexceptflag.c.
 {
     *fp = fetestexcept(mask);
     return 0;
 }
References fetestexcept().
fegetround()
int fegetround (void)
Definition at line 20 of file fenv.c.
 {
     return FE_TONEAREST;
 }
References FE_TONEAREST, get_fpc(), and get_fpscr().
Referenced by __flt_rounds(), and fmaf().
feholdexcept()
int feholdexcept (fenv_t * envp)
Definition at line 3 of file feholdexcept.c.
 {
     fegetenv(envp);
     feclearexcept(FE_ALL_EXCEPT);
     return 0;
 }
References FE_ALL_EXCEPT, feclearexcept(), and fegetenv().
feraiseexcept()
int feraiseexcept (int mask)
Definition at line 10 of file fenv.c.
 {
     return 0;
 }
References FE_ALL_EXCEPT, FE_INVALID, get_fpc(), get_fpscr(), set_fpc(), and set_fpscr().
Referenced by fesetexceptflag(), feupdateenv(), and fmaf().
fesetenv()
int fesetenv (const fenv_t * envp)
Definition at line 35 of file fenv.c.
 {
     return 0;
 }
References FE_DFL_ENV, set_fpc(), and set_fpscr_f().
Referenced by feupdateenv().
fesetexceptflag()
int fesetexceptflag (const fexcept_t * fp, int mask)
Definition at line 3 of file fesetexceptflag.c.
 {
     feclearexcept(~*fp & mask);
     feraiseexcept(*fp & mask);
     return 0;
 }
References feclearexcept(), and feraiseexcept().
fesetround()
int fesetround (int r)
Definition at line 8 of file fesetround.c.
 {
     if (r != FE_TONEAREST
 #ifdef FE_DOWNWARD
         && r != FE_DOWNWARD
 #endif
 #ifdef FE_UPWARD
         && r != FE_UPWARD
 #endif
 #ifdef FE_TOWARDZERO
         && r != FE_TOWARDZERO
 #endif
     )
         return -1;
     return __fesetround(r);
 }
References __fesetround(), FE_DOWNWARD, FE_TONEAREST, FE_TOWARDZERO, and FE_UPWARD.
fetestexcept()
int fetestexcept (int mask)
Definition at line 15 of file fenv.c.
 {
     return 0;
 }
References FE_ALL_EXCEPT, get_fpc(), and get_fpscr().
Referenced by fegetexceptflag(), feupdateenv(), fmaf(), nearbyint(), nearbyintf(), and nearbyintl().
feupdateenv()
int feupdateenv (const fenv_t * envp)
Definition at line 3 of file feupdateenv.c.
 {
     int ex = fetestexcept(FE_ALL_EXCEPT);
     fesetenv(envp);
     feraiseexcept(ex);
     return 0;
 }
References FE_ALL_EXCEPT, feraiseexcept(), fesetenv(), and fetestexcept().