Fennix: Userspace/apps/base/bash/examples/loadables/csv.c File Reference
csv.c File Reference
#include <config.h>
#include "bashansi.h"
#include <stdio.h>
#include "loadables.h"
Macros
#define CSV_ARRAY_DEFAULT "CSV"
#define NQUOTE 0
#define DQUOTE 1
Functions
static int csvsplit (SHELL_VAR *csv, char *line, char *dstring)
int csv_builtin (WORD_LIST *list)
int csv_builtin_load (char *name)
void csv_builtin_unload (char *name)
Variables
char * csv_doc []
struct builtin csv_struct
Macro Definition Documentation
CSV_ARRAY_DEFAULT
#define CSV_ARRAY_DEFAULT "CSV"
Definition at line 33 of file csv.c.
DQUOTE
#define DQUOTE 1
Definition at line 36 of file csv.c.
NQUOTE
#define NQUOTE 0
Definition at line 35 of file csv.c.
Function Documentation
csv_builtin()
int csv_builtin (WORD_LIST * list)
Definition at line 106 of file csv.c.
 {
   int opt, rval;
   char *array_name, *csvstring;
   SHELL_VAR *v;
   array_name = 0;
   rval = EXECUTION_SUCCESS;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "a:")) != -1)
     {
       switch (opt)
     {
     case 'a':
       array_name = list_optarg;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (array_name == 0)
     array_name = CSV_ARRAY_DEFAULT;
   if (legal_identifier (array_name) == 0)
     {
       sh_invalidid (array_name);
       return (EXECUTION_FAILURE);
     }
   if (list == 0)
     {
       builtin_error ("csv string argument required");
       return (EX_USAGE);
     }
   v = find_or_make_array_variable (array_name, 1);
   if (v == 0 || readonly_p (v) || noassign_p (v))
     {
       if (v && readonly_p (v))
     err_readonly (array_name);
       return (EXECUTION_FAILURE);
     }
   else if (array_p (v) == 0)
     {
       builtin_error ("%s: not an indexed array", array_name);
       return (EXECUTION_FAILURE);
     }
   if (invisible_p (v))
     VUNSETATTR (v, att_invisible);
   array_flush (array_cell (v));
   csvstring = list->word->word;
   if (csvstring == 0 || *csvstring == 0)
     return (EXECUTION_SUCCESS);
   opt = csvsplit (v, csvstring, ",");
   /* Maybe do something with OPT here, it's the number of fields */
   return (rval);
 }
References array_cell, array_p, att_invisible, builtin_error(), builtin_usage(), CASE_HELPOPT, CSV_ARRAY_DEFAULT, csvsplit(), err_readonly(), EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, internal_getopt(), invisible_p, legal_identifier(), list_optarg, loptend, noassign_p, readonly_p, reset_internal_getopt(), sh_invalidid(), VUNSETATTR, word_desc::word, and word_list::word.
csv_builtin_load()
int csv_builtin_load (char * name)
Definition at line 177 of file csv.c.
 {
   return (1);
 }
csv_builtin_unload()
void csv_builtin_unload (char * name)
Definition at line 185 of file csv.c.
 {
 }
csvsplit()
static int csvsplit (SHELL_VAR * csv, char * line, char * dstring) static
Definition at line 42 of file csv.c.
 {
   arrayind_t ind;
   char *field, *prev, *buf, *xbuf;
   int delim, qstate;
   int b, rval;
   xbuf = 0;
   ind = 0;
   field = prev = line;
   do
     {
       if (*prev == '"')
     {
       if (xbuf == 0)
         xbuf = xmalloc (strlen (prev) + 1);
       buf = xbuf;
       b = 0;
       qstate = DQUOTE;
       for (field = ++prev; *field; field++)
         {
           if (qstate == DQUOTE && *field == '"' && field[1] == '"')
         buf[b++] = *field++;    /* skip double quote */
           else if (qstate == DQUOTE && *field == '"')
             qstate = NQUOTE;
           else if (qstate == NQUOTE && *field == *dstring)
         break;
           else
         /* This copies any text between a closing double quote and the
            delimiter. If you want to change that, make sure to do the
            copy only if qstate == DQUOTE. */
         buf[b++] = *field;
         }
       buf[b] = '\0';
     }
       else
     {
       buf = prev;
       field = prev + strcspn (prev, dstring);
     }
       delim = *field;
       *field = '\0';
       bind_array_element (csv, ind, buf, 0);
       ind++;
       *field = delim;
       if (delim == *dstring)
     prev = field + 1;
     }
   while (delim == *dstring);
   if (xbuf)
     free (xbuf);
   return (rval = ind);              /* number of fields */
 }
References b, buf, DQUOTE, field, free, line, NQUOTE, strcspn(), strlen(), and xmalloc.
Referenced by csv_builtin().
Variable Documentation
csv_doc
char* csv_doc[]
Initial value:
= {
    "Read comma-separated fields from a string.",
    "",
    "Parse STRING, a line of comma-separated values, into individual fields,",
    "and store them into the indexed array ARRAYNAME starting at index 0.",
    "If ARRAYNAME is not supplied, \"CSV\" is the default array name.",
    (char *)NULL
}
Definition at line 190 of file csv.c.
csv_struct
struct builtin csv_struct
Initial value:
= {
    "csv",
    csv_builtin,
    BUILTIN_ENABLED,
    csv_doc,
    "csv [-a ARRAY] string",
    0
}
Definition at line 190 of file csv.c.