Fennix: Userspace/apps/base/busybox/miscutils/crontab.c File Reference
crontab.c File Reference
#include "libbb.h"
Macros
#define CRONTABS CONFIG_FEATURE_CROND_DIR "/crontabs"
#define CRONUPDATE "cron.update"
#define user_name DONT_USE_ME_BEYOND_THIS_POINT
Functions
static void edit_file (const struct passwd *pas, const char *file)
int crontab_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CRONTABS
#define CRONTABS CONFIG_FEATURE_CROND_DIR "/crontabs"
Definition at line 38 of file crontab.c.
CRONUPDATE
#define CRONUPDATE "cron.update"
Definition at line 40 of file crontab.c.
user_name
#define user_name DONT_USE_ME_BEYOND_THIS_POINT
Function Documentation
crontab_main()
int crontab_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 72 of file crontab.c.
 {
     const struct passwd *pas;
     const char *crontab_dir = CRONTABS;
     char *tmp_fname;
     char *new_fname;
     char *user_name;  /* -u USER */
     int fd;
     int src_fd;
     int opt_ler;
     /* file [opts]     Replace crontab from file
      * - [opts]        Replace crontab from stdin
      * -u user         User
      * -c dir          Crontab directory
      * -l              List crontab for user
      * -e              Edit crontab for user
      * -r              Delete crontab for user
      * bbox also supports -d == -r, but most other crontab
      * implementations do not. Deprecated.
      */
     enum {
         OPT_u = (1 << 0),
         OPT_c = (1 << 1),
         OPT_l = (1 << 2),
         OPT_e = (1 << 3),
         OPT_r = (1 << 4),
         OPT_ler = OPT_l + OPT_e + OPT_r,
     };
     opt_ler = getopt32(argv, "^" "u:c:lerd" "\0" "?1:dr"/*max one arg; -d implies -r*/,
                 &user_name, &crontab_dir
     );
     argv += optind;
     if (sanitize_env_if_suid()) { /* Clears dangerous stuff, sets PATH */
         /* Run by non-root */
         if (opt_ler & (OPT_u|OPT_c))
             bb_simple_error_msg_and_die(bb_msg_you_must_be_root);
     }
     if (opt_ler & OPT_u) {
         pas = xgetpwnam(user_name);
     } else {
         pas = xgetpwuid(getuid());
     }
 #define user_name DONT_USE_ME_BEYOND_THIS_POINT
     /* From now on, keep only -l, -e, -r bits */
     opt_ler &= OPT_ler;
     if ((opt_ler - 1) & opt_ler) /* more than one bit set? */
         bb_show_usage();
     /* Read replacement file under user's UID/GID/group vector */
     src_fd = STDIN_FILENO;
     if (!opt_ler) { /* Replace? */
         if (!argv[0])
             bb_show_usage();
         if (NOT_LONE_DASH(argv[0])) {
             src_fd = xopen_as_uid_gid(argv[0], O_RDONLY, pas->pw_uid, pas->pw_gid);
         }
     }
     /* cd to our crontab directory */
     xchdir(crontab_dir);
     tmp_fname = NULL;
     /* Handle requested operation */
     switch (opt_ler) {
     default: /* case OPT_r: Delete */
         unlink(pas->pw_name);
         break;
     case OPT_l: /* List */
         {
             char *args[2] = { pas->pw_name, NULL };
             return bb_cat(args);
             /* list exits,
              * the rest go play with cron update file */
         }
     case OPT_e: /* Edit */
         tmp_fname = xasprintf("%s.%u", crontab_dir, (unsigned)getpid());
         /* No O_EXCL: we don't want to be stuck if earlier crontabs
          * were killed, leaving stale temp file behind */
         src_fd = xopen3(tmp_fname, O_RDWR|O_CREAT|O_TRUNC, 0600);
         fchown(src_fd, pas->pw_uid, pas->pw_gid);
         fd = open(pas->pw_name, O_RDONLY);
         if (fd >= 0) {
             bb_copyfd_eof(fd, src_fd);
             close(fd);
             xlseek(src_fd, 0, SEEK_SET);
         }
         close(src_fd);
         edit_file(pas, tmp_fname);
         /* The src_fd needs to be reopened to handle editors that do
          * save the buffer as new file and rename it to tmp_fname (so
          * for example vim). */
         src_fd = xopen3(tmp_fname, O_RDONLY, 0600);
         /* fall through */
     case 0: /* Replace (no -l, -e, or -r were given) */
         new_fname = xasprintf("%s.new", pas->pw_name);
         fd = open(new_fname, O_WRONLY|O_CREAT|O_TRUNC|O_APPEND, 0600);
         if (fd >= 0) {
             bb_copyfd_eof(src_fd, fd);
             close(fd);
             xrename(new_fname, pas->pw_name);
         } else {
             bb_error_msg("can't create %s/%s",
                     crontab_dir, new_fname);
         }
         if (tmp_fname)
             unlink(tmp_fname);
         /*free(tmp_fname);*/
         /*free(new_fname);*/
     } /* switch */
     /* Bump notification file.  Handle window where crond picks file up
      * before we can write our entry out.
      */
     while ((fd = open(CRONUPDATE, O_WRONLY|O_CREAT|O_APPEND, 0600)) >= 0) {
         struct stat st;
         fdprintf(fd, "%s\n", pas->pw_name);
         if (fstat(fd, &st) != 0 || st.st_nlink != 0) {
             /*close(fd);*/
             break;
         }
         /* st.st_nlink == 0:
          * file was deleted, maybe crond missed our notification */
         close(fd);
         /* loop */
     }
     if (fd < 0) {
         bb_error_msg("can't append to %s/%s",
                 crontab_dir, CRONUPDATE);
     }
     return 0;
 }
References argv, bb_cat(), bb_copyfd_eof(), bb_error_msg(), bb_show_usage(), bb_simple_error_msg_and_die(), close(), CRONTABS, CRONUPDATE, edit_file(), fchown(), fd, fdprintf, fstat(), getopt32(), getpid(), getuid, NOT_LONE_DASH, NULL, O_APPEND, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, open(), OPT_c, OPT_e, OPT_l, OPT_r, OPT_u, optind, passwd::pw_gid, passwd::pw_name, passwd::pw_uid, sanitize_env_if_suid(), SEEK_SET, STDIN_FILENO, unlink(), user_name, xasprintf(), xchdir(), xgetpwnam(), xgetpwuid(), xlseek(), xopen3(), xopen_as_uid_gid(), and xrename().
edit_file()
static void edit_file (const struct passwd * pas, const char * file) static
Definition at line 43 of file crontab.c.
 {
     const char *ptr;
     pid_t pid;
     pid = xvfork();
     if (pid) { /* parent */
         wait4pid(pid);
         return;
     }
     /* CHILD - change user and run editor */
     /* initgroups, setgid, setuid */
     change_identity(pas);
     setup_environment(pas->pw_shell,
         SETUP_ENV_CHANGEENV | SETUP_ENV_TO_TMP | SETUP_ENV_CHDIR,
         pas);
     ptr = getenv("VISUAL");
     if (!ptr) {
         ptr = getenv("EDITOR");
         if (!ptr)
             ptr = "vi";
     }
     BB_EXECLP(ptr, ptr, file, NULL);
     bb_perror_msg_and_die("can't execute '%s'", ptr);
 }
References BB_EXECLP, bb_perror_msg_and_die(), change_identity(), getenv, NULL, pid, passwd::pw_shell, SETUP_ENV_CHANGEENV, SETUP_ENV_CHDIR, SETUP_ENV_TO_TMP, setup_environment(), wait4pid(), and xvfork.
Referenced by crontab_main().