Fennix: Userspace/musl/include/iconv.h File Reference
iconv.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define __NEED_size_t
Typedefs
typedef void * iconv_t
Functions
iconv_t iconv_open (const char *, const char *)
size_t iconv (iconv_t, char **__restrict, size_t *__restrict, char **__restrict, size_t *__restrict)
int iconv_close (iconv_t)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file iconv.h.
Typedef Documentation
iconv_t
typedef void* iconv_t
Definition at line 14 of file iconv.h.
Function Documentation
iconv()
size_t iconv (iconv_t , char ** __restrict, size_t * __restrict, char ** __restrict, size_t * __restrict)
Referenced by _nl_find_msg().
iconv_close()
int iconv_close (iconv_t cd)
Definition at line 4 of file iconv_close.c.
 {
     if (!((size_t)cd & 1)) free((void *)cd);
     return 0;
 }
References free.
Referenced by _nl_free_domain_conv().
iconv_open()
iconv_t iconv_open (const char * to, const char * from)
Definition at line 140 of file iconv.c.
 {
     size_t f, t;
     struct stateful_cd *scd;
     if ((t = find_charmap(to))==-1
      || (f = find_charmap(from))==-1
      || (charmaps[t] >= 0330)) {
         errno = EINVAL;
         return (iconv_t)-1;
     }
     iconv_t cd = combine_to_from(t, f);
     switch (charmaps[f]) {
     case UTF_16:
     case UTF_32:
     case UCS2:
     case ISO2022_JP:
         scd = malloc(sizeof *scd);
         if (!scd) return (iconv_t)-1;
         scd->base_cd = cd;
         scd->state = 0;
         cd = (iconv_t)scd;
     }
     return cd;
 }
References stateful_cd::base_cd, charmaps, combine_to_from(), EINVAL, errno, f, find_charmap(), ISO2022_JP, malloc, stateful_cd::state, t, UCS2, UTF_16, and UTF_32.
Referenced by _nl_init_domain_conv().