Fennix: Userspace/apps/base/busybox/util-linux/fbset.c File Reference
fbset.c File Reference
#include "libbb.h"
Data Structures
struct fb_bitfield
struct fb_var_screeninfo
struct cmdoptions_t
Macros
#define DEFAULTFBDEV FB_0
#define DEFAULTFBMODE "/etc/fb.modes"
#define FB_ACTIVATE_ALL 64
Enumerations
enum { FBIOGET_VSCREENINFO = 0x4600 , FBIOPUT_VSCREENINFO = 0x4601 }
enum {
CMD_FB = 1 , CMD_DB = 2 , CMD_GEOMETRY = 3 , CMD_TIMING = 4 ,
CMD_ACCEL = 5 , CMD_HSYNC = 6 , CMD_VSYNC = 7 , CMD_LACED = 8 ,
CMD_DOUBLE = 9 , CMD_ALL = 11 , CMD_INFO = 12 , CMD_SHOW = 13 ,
CMD_CHANGE = 14
}
enum { FB_SYNC_HOR_HIGH_ACT = 1 , FB_SYNC_VERT_HIGH_ACT = 2 }
Functions
static void copy_if_gt0 (uint32_t *src, uint32_t *dst, unsigned cnt)
static NOINLINE void copy_changed_values (struct fb_var_screeninfo *base, struct fb_var_screeninfo *set)
static NOINLINE void showmode (struct fb_var_screeninfo *v)
int fbset_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const struct cmdoptions_t ALIGN1 []
Data Structure Documentation
fb_bitfield
struct fb_bitfield
Definition at line 73 of file fbset.c.
Data Fields
uint32_t length
uint32_t msb_right
uint32_t offset
fb_var_screeninfo
struct fb_var_screeninfo
Definition at line 78 of file fbset.c.
Data Fields
uint32_t accel_flags
uint32_t activate
uint32_t bits_per_pixel
struct fb_bitfield blue
uint32_t grayscale
struct fb_bitfield green
uint32_t height
uint32_t hsync_len
uint32_t left_margin
uint32_t lower_margin
uint32_t nonstd
uint32_t pixclock
struct fb_bitfield red
uint32_t reserved[6]
uint32_t right_margin
uint32_t sync
struct fb_bitfield transp
uint32_t upper_margin
uint32_t vmode
uint32_t vsync_len
uint32_t width
uint32_t xoffset
uint32_t xres
uint32_t xres_virtual
uint32_t yoffset
uint32_t yres
uint32_t yres_virtual
cmdoptions_t
struct cmdoptions_t
Definition at line 192 of file fbset.c.
Data Fields
const unsigned char code
const char name[9]
const unsigned char param_count
Macro Definition Documentation
DEFAULTFBDEV
#define DEFAULTFBDEV FB_0
Definition at line 63 of file fbset.c.
DEFAULTFBMODE
#define DEFAULTFBMODE "/etc/fb.modes"
Definition at line 64 of file fbset.c.
FB_ACTIVATE_ALL
#define FB_ACTIVATE_ALL 64
Definition at line 67 of file fbset.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FBIOGET_VSCREENINFO
FBIOPUT_VSCREENINFO
Definition at line 68 of file fbset.c.
      {
     FBIOGET_VSCREENINFO = 0x4600,
     FBIOPUT_VSCREENINFO = 0x4601
 };
anonymous enum
anonymous enum
Enumerator
CMD_FB
CMD_DB
CMD_GEOMETRY
CMD_TIMING
CMD_ACCEL
CMD_HSYNC
CMD_VSYNC
CMD_LACED
CMD_DOUBLE
CMD_ALL
CMD_INFO
CMD_SHOW
CMD_CHANGE
Definition at line 152 of file fbset.c.
      {
     CMD_FB = 1,
     CMD_DB = 2,
     CMD_GEOMETRY = 3,
     CMD_TIMING = 4,
     CMD_ACCEL = 5,
     CMD_HSYNC = 6,
     CMD_VSYNC = 7,
     CMD_LACED = 8,
     CMD_DOUBLE = 9,
 /*  CMD_XCOMPAT =     10, */
     CMD_ALL = 11,
     CMD_INFO = 12,
     CMD_SHOW = 13,
     CMD_CHANGE = 14,
 #if ENABLE_FEATURE_FBSET_FANCY
     CMD_XRES = 100,
     CMD_YRES = 101,
     CMD_VXRES = 102,
     CMD_VYRES = 103,
     CMD_DEPTH = 104,
     CMD_MATCH = 105,
     CMD_PIXCLOCK = 106,
     CMD_LEFT = 107,
     CMD_RIGHT = 108,
     CMD_UPPER = 109,
     CMD_LOWER = 110,
     CMD_HSLEN = 111,
     CMD_VSLEN = 112,
     CMD_CSYNC = 113,
     CMD_GSYNC = 114,
     CMD_EXTSYNC = 115,
     CMD_BCAST = 116,
     CMD_RGBA = 117,
     CMD_STEP = 118,
     CMD_MOVE = 119,
 #endif
 };
anonymous enum
anonymous enum
Enumerator
FB_SYNC_HOR_HIGH_ACT
FB_SYNC_VERT_HIGH_ACT
Definition at line 240 of file fbset.c.
      {
     FB_SYNC_HOR_HIGH_ACT = 1,       /* horizontal sync high active */
     FB_SYNC_VERT_HIGH_ACT = 2,      /* vertical sync high active */
 #if ENABLE_FEATURE_FBSET_READMODE
     FB_VMODE_INTERLACED = 1,        /* interlaced */
     FB_VMODE_DOUBLE = 2,            /* double scan */
     FB_SYNC_EXT = 4,                /* external sync */
     FB_SYNC_COMP_HIGH_ACT = 8,      /* composite sync high active */
 #endif
 };
Function Documentation
copy_changed_values()
static NOINLINE void copy_changed_values (struct fb_var_screeninfo * base, struct fb_var_screeninfo * set) static
Definition at line 126 of file fbset.c.
 {
     //if ((int32_t) set->xres > 0) base->xres = set->xres;
     //if ((int32_t) set->yres > 0) base->yres = set->yres;
     //if ((int32_t) set->xres_virtual > 0)   base->xres_virtual = set->xres_virtual;
     //if ((int32_t) set->yres_virtual > 0)   base->yres_virtual = set->yres_virtual;
     copy_if_gt0(&set->xres, &base->xres, 4);
     if ((int32_t) set->bits_per_pixel > 0) base->bits_per_pixel = set->bits_per_pixel;
     //copy_if_gt0(&set->bits_per_pixel, &base->bits_per_pixel, 1);
     //if ((int32_t) set->pixclock > 0)       base->pixclock = set->pixclock;
     //if ((int32_t) set->left_margin > 0)    base->left_margin = set->left_margin;
     //if ((int32_t) set->right_margin > 0)   base->right_margin = set->right_margin;
     //if ((int32_t) set->upper_margin > 0)   base->upper_margin = set->upper_margin;
     //if ((int32_t) set->lower_margin > 0)   base->lower_margin = set->lower_margin;
     //if ((int32_t) set->hsync_len > 0) base->hsync_len = set->hsync_len;
     //if ((int32_t) set->vsync_len > 0) base->vsync_len = set->vsync_len;
     //if ((int32_t) set->sync > 0)  base->sync = set->sync;
     //if ((int32_t) set->vmode > 0) base->vmode = set->vmode;
     copy_if_gt0(&set->pixclock, &base->pixclock, 9);
 }
References base, fb_var_screeninfo::bits_per_pixel, copy_if_gt0(), fb_var_screeninfo::pixclock, and fb_var_screeninfo::xres.
Referenced by fbset_main().
copy_if_gt0()
static void copy_if_gt0 (uint32_t * src, uint32_t * dst, unsigned cnt) static
Definition at line 116 of file fbset.c.
 {
     do {
         if ((int32_t) *src > 0)
             *dst = *src;
         src++;
         dst++;
     } while (--cnt);
 }
References cnt, dst, and src.
Referenced by copy_changed_values().
fbset_main()
int fbset_main (int argc, char ** argv)
Definition at line 438 of file fbset.c.
 {
     enum {
         OPT_CHANGE   = (1 << 0),
         OPT_SHOW     = (1 << 1),
         OPT_READMODE = (1 << 2),
         OPT_ALL      = (1 << 3),
     };
     struct fb_var_screeninfo var_old, var_set;
     int fh, i;
     unsigned options = 0;
     const char *fbdev = DEFAULTFBDEV;
     IF_FEATURE_FBSET_READMODE(const char *modefile = DEFAULTFBMODE;)
     char *thisarg;
     char *mode = mode; /* for compiler */
     memset(&var_set, 0xff, sizeof(var_set)); /* set all to -1 */
     /* parse cmd args.... why do they have to make things so difficult? */
     argv++;
     argc--;
     for (; argc > 0 && (thisarg = *argv) != NULL; argc--, argv++) {
         if (thisarg[0] != '-') {
             if (!ENABLE_FEATURE_FBSET_READMODE || argc != 1)
                 bb_show_usage();
             mode = thisarg;
             options |= OPT_READMODE;
             goto contin;
         }
         for (i = 0; i < ARRAY_SIZE(g_cmdoptions); i++) {
             if (strcmp(thisarg + 1, g_cmdoptions[i].name) != 0)
                 continue;
             if (argc <= g_cmdoptions[i].param_count)
                 bb_show_usage();
             switch (g_cmdoptions[i].code) {
             case CMD_FB:
                 fbdev = argv[1];
                 break;
             case CMD_DB:
                 IF_FEATURE_FBSET_READMODE(modefile = argv[1];)
                 break;
             case CMD_ALL:
                 options |= OPT_ALL;
                 break;
             case CMD_SHOW:
                 options |= OPT_SHOW;
                 break;
             case CMD_GEOMETRY:
                 var_set.xres = xatou32(argv[1]);
                 var_set.yres = xatou32(argv[2]);
                 var_set.xres_virtual = xatou32(argv[3]);
                 var_set.yres_virtual = xatou32(argv[4]);
                 var_set.bits_per_pixel = xatou32(argv[5]);
                 break;
             case CMD_TIMING:
                 var_set.pixclock = xatou32(argv[1]);
                 var_set.left_margin = xatou32(argv[2]);
                 var_set.right_margin = xatou32(argv[3]);
                 var_set.upper_margin = xatou32(argv[4]);
                 var_set.lower_margin = xatou32(argv[5]);
                 var_set.hsync_len = xatou32(argv[6]);
                 var_set.vsync_len = xatou32(argv[7]);
                 break;
             case CMD_ACCEL:
                 break;
             case CMD_HSYNC:
                 var_set.sync |= FB_SYNC_HOR_HIGH_ACT;
                 break;
             case CMD_VSYNC:
                 var_set.sync |= FB_SYNC_VERT_HIGH_ACT;
                 break;
 #if ENABLE_FEATURE_FBSET_FANCY
             case CMD_XRES:
                 var_set.xres = xatou32(argv[1]);
                 break;
             case CMD_YRES:
                 var_set.yres = xatou32(argv[1]);
                 break;
             case CMD_DEPTH:
                 var_set.bits_per_pixel = xatou32(argv[1]);
                 break;
             case CMD_PIXCLOCK:
                 var_set.pixclock = xatou32(argv[1]);
                 break;
 #endif
             default:
                 bb_perror_msg_and_die("option '%s' not handled",
                               g_cmdoptions[i].name);
             }
             switch (g_cmdoptions[i].code) {
             case CMD_FB:
             case CMD_DB:
             case CMD_ALL:
             case CMD_SHOW:
                 break;
             default:
                 /* other commands imply changes */
                 options |= OPT_CHANGE;
             }
             argc -= g_cmdoptions[i].param_count;
             argv += g_cmdoptions[i].param_count;
             goto contin;
         }
         bb_show_usage();
  contin: ;
     }
     fh = xopen(fbdev, O_RDONLY);
     xioctl(fh, FBIOGET_VSCREENINFO, &var_old);
     if (options & OPT_READMODE) {
 #if ENABLE_FEATURE_FBSET_READMODE
         if (!read_mode_db(&var_old, modefile, mode)) {
             bb_error_msg_and_die("unknown video mode '%s'", mode);
         }
         options |= OPT_CHANGE;
 #endif
     }
     if (options & OPT_CHANGE) {
         copy_changed_values(&var_old, &var_set);
         if (options & OPT_ALL)
             var_old.activate = FB_ACTIVATE_ALL;
         xioctl(fh, FBIOPUT_VSCREENINFO, &var_old);
     }
     if (options == 0 || (options & OPT_SHOW))
         showmode(&var_old);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fh);
     return EXIT_SUCCESS;
 }
References fb_var_screeninfo::activate, argc, argv, ARRAY_SIZE, bb_error_msg_and_die(), bb_perror_msg_and_die(), bb_show_usage(), fb_var_screeninfo::bits_per_pixel, close(), CMD_ACCEL, CMD_ALL, CMD_DB, CMD_FB, CMD_GEOMETRY, CMD_HSYNC, CMD_SHOW, CMD_TIMING, CMD_VSYNC, code, copy_changed_values(), DEFAULTFBDEV, DEFAULTFBMODE, EXIT_SUCCESS, FB_ACTIVATE_ALL, FB_SYNC_HOR_HIGH_ACT, FB_SYNC_VERT_HIGH_ACT, FBIOGET_VSCREENINFO, FBIOPUT_VSCREENINFO, fb_var_screeninfo::hsync_len, i, fb_var_screeninfo::left_margin, fb_var_screeninfo::lower_margin, memset, NULL, O_RDONLY, OPT_ALL, fb_var_screeninfo::pixclock, fb_var_screeninfo::right_margin, showmode(), strcmp, fb_var_screeninfo::sync, fb_var_screeninfo::upper_margin, fb_var_screeninfo::vsync_len, xatou32(), xioctl, xopen(), fb_var_screeninfo::xres, fb_var_screeninfo::xres_virtual, fb_var_screeninfo::yres, and fb_var_screeninfo::yres_virtual.
showmode()
static NOINLINE void showmode (struct fb_var_screeninfo * v) static
Definition at line 407 of file fbset.c.
 {
     double drate = 0, hrate = 0, vrate = 0;
     if (v->pixclock) {
         drate = 1e12 / v->pixclock;
         hrate = drate / (v->left_margin + v->xres + v->right_margin + v->hsync_len);
         vrate = hrate / (v->upper_margin + v->yres + v->lower_margin + v->vsync_len);
     }
     printf("\nmode \"%ux%u-%u\"\n"
 #if ENABLE_FEATURE_FBSET_FANCY
     "\t# D: %.3f MHz, H: %.3f kHz, V: %.3f Hz\n"
 #endif
     "\tgeometry %u %u %u %u %u\n"
     "\ttimings %u %u %u %u %u %u %u\n"
     "\taccel %s\n"
     "\trgba %u/%u,%u/%u,%u/%u,%u/%u\n"
     "endmode\n\n",
         v->xres, v->yres, (int) (vrate + 0.5),
 #if ENABLE_FEATURE_FBSET_FANCY
         drate / 1e6, hrate / 1e3, vrate,
 #endif
         v->xres, v->yres, v->xres_virtual, v->yres_virtual, v->bits_per_pixel,
         v->pixclock, v->left_margin, v->right_margin, v->upper_margin, v->lower_margin,
             v->hsync_len, v->vsync_len,
         (v->accel_flags > 0 ? "true" : "false"),
         v->red.length, v->red.offset, v->green.length, v->green.offset,
             v->blue.length, v->blue.offset, v->transp.length, v->transp.offset);
 }
References fb_var_screeninfo::accel_flags, fb_var_screeninfo::bits_per_pixel, fb_var_screeninfo::blue, fb_var_screeninfo::green, fb_var_screeninfo::hsync_len, fb_var_screeninfo::left_margin, fb_bitfield::length, fb_var_screeninfo::lower_margin, fb_bitfield::offset, fb_var_screeninfo::pixclock, printf, fb_var_screeninfo::red, fb_var_screeninfo::right_margin, fb_var_screeninfo::transp, fb_var_screeninfo::upper_margin, fb_var_screeninfo::vsync_len, fb_var_screeninfo::xres, fb_var_screeninfo::xres_virtual, fb_var_screeninfo::yres, and fb_var_screeninfo::yres_virtual.
Referenced by fbset_main().
Variable Documentation
ALIGN1
const struct cmdoptions_t ALIGN1[] static