Fennix Userspace: Userspace/apps/base/busybox/editors/diff.c File Reference
diff.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct FILE_and_pos_t
struct globals
struct cand
struct line
union line.__unnamed83__
Macros
#define dbg_error_msg(...) ((void)0)
#define FLAG(x) (1 << FLAG_##x)
#define G (*ptr_to_globals)
#define exit_status (G.exit_status)
#define opt_U_context (G.opt_U_context)
#define label (G.label)
#define stb (G.stb)
#define INIT_G()
#define TOK2CHAR(t) ((t) & CHAR_MASK)
#define l0 ((const struct line*)a)
#define l1 ((const struct line*)b)
#define GETOPT32 getopt32
#define LONGOPTS
Typedefs
typedef struct FILE_and_pos_t FILE_and_pos_t
typedef int token_t
Enumerations
enum { STATUS_SAME , STATUS_DIFFER , STATUS_BINARY }
enum {
FLAG_a , FLAG_b , FLAG_d , FLAG_i ,
FLAG_L , FLAG_N , FLAG_q , FLAG_r ,
FLAG_s , FLAG_S , FLAG_t , FLAG_T ,
FLAG_U , FLAG_w , FLAG_u , FLAG_p ,
FLAG_B , FLAG_E
}
enum {
TOK_EMPTY = 1 << 9 , TOK_EOF = 1 << 10 , TOK_EOL = 1 << 11 , TOK_SPACE = 1 << 12 ,
SHIFT_EOF = (sizeof(token_t)*8 - 8) - 1 , CHAR_MASK = 0x1ff
}
Functions
static void seek_ft (FILE_and_pos_t *ft, off_t pos)
static int read_token (FILE_and_pos_t *ft, token_t tok)
static int search (const int *c, int k, int y, const struct cand *list)
static void stone (const int *a, int n, const int *b, int *J, int pref)
static void equiv (struct line *a, int n, struct line *b, int m, int *c)
static void unsort (const struct line *f, int l, int *b)
static int line_compar (const void *a, const void *b)
static void fetch (FILE_and_pos_t *ft, const off_t *ix, int a, int b, int ch)
static NOINLINE int * create_J (FILE_and_pos_t ft[2], int nlen[2], off_t *ix[2])
static bool diff (FILE *fp[2], char *file[2])
static int diffreg (char *file[2])
static void print_status (int status, char *path[2])
int diff_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
FILE_and_pos_t
struct FILE_and_pos_t
Definition at line 161 of file diff.c.
Data Fields
FILE * ft_fp
off_t ft_pos
cand
struct cand
Definition at line 268 of file diff.c.
Data Fields
int pred
int x
int y
line
struct line
Definition at line 351 of file diff.c.
Data Fields
union line __unnamed__
int count
char * string
unsigned value
line.__unnamed83__
union line.__unnamed83__
Definition at line 355 of file diff.c.
Data Fields
off_t offset
unsigned serial
Macro Definition Documentation
dbg_error_msg
#define dbg_error_msg (...) ((void)0)
Definition at line 129 of file diff.c.
exit_status
#define exit_status (G.exit_status)
Definition at line 174 of file diff.c.
FLAG
#define FLAG (x) (1 << FLAG_##x)
Definition at line 158 of file diff.c.
G
#define G (*ptr_to_globals)
Definition at line 173 of file diff.c.
GETOPT32
#define GETOPT32 getopt32
Definition at line 971 of file diff.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    opt_U_context = 3; \
} while (0)
Definition at line 178 of file diff.c.
l0
#define l0 ((const struct line*)a)
l1
#define l1 ((const struct line*)b)
label
#define label (G.label)
Definition at line 176 of file diff.c.
LONGOPTS
#define LONGOPTS
Definition at line 972 of file diff.c.
opt_U_context
#define opt_U_context (G.opt_U_context)
Definition at line 175 of file diff.c.
stb
#define stb (G.stb)
Definition at line 177 of file diff.c.
TOK2CHAR
#define TOK2CHAR (t) ((t) & CHAR_MASK)
Definition at line 199 of file diff.c.
Typedef Documentation
FILE_and_pos_t
typedef struct FILE_and_pos_t FILE_and_pos_t
token_t
typedef int token_t
Definition at line 183 of file diff.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STATUS_SAME
STATUS_DIFFER
STATUS_BINARY
Definition at line 132 of file diff.c.
      {                  /* print_status() and diffreg() return values */
     STATUS_SAME,    /* files are the same */
     STATUS_DIFFER,  /* files differ */
     STATUS_BINARY,  /* binary files differ */
 };
anonymous enum
anonymous enum
Enumerator
FLAG_a
FLAG_b
FLAG_d
FLAG_i
FLAG_L
FLAG_N
FLAG_q
FLAG_r
FLAG_s
FLAG_S
FLAG_t
FLAG_T
FLAG_U
FLAG_w
FLAG_u
FLAG_p
FLAG_B
FLAG_E
Definition at line 138 of file diff.c.
      {                  /* Commandline flags */
     FLAG_a,
     FLAG_b,
     FLAG_d,
     FLAG_i,
     FLAG_L,         /* never used, handled by getopt32 */
     FLAG_N,
     FLAG_q,
     FLAG_r,
     FLAG_s,
     FLAG_S,         /* never used, handled by getopt32 */
     FLAG_t,
     FLAG_T,
     FLAG_U,         /* never used, handled by getopt32 */
     FLAG_w,
     FLAG_u,         /* ignored, this is the default */
     FLAG_p,         /* not implemented */
     FLAG_B,
     FLAG_E,         /* not implemented */
 };
anonymous enum
anonymous enum
Enumerator
TOK_EMPTY
TOK_EOF
TOK_EOL
TOK_SPACE
SHIFT_EOF
CHAR_MASK
Definition at line 185 of file diff.c.
      {
     /* Public */
     TOK_EMPTY = 1 << 9,  /* Line fully processed, you can proceed to the next */
     TOK_EOF   = 1 << 10, /* File ended */
     /* Private (Only to be used by read_token() */
     TOK_EOL   = 1 << 11, /* we saw EOL (sticky) */
     TOK_SPACE = 1 << 12, /* used -b code, means we are skipping spaces */
     SHIFT_EOF = (sizeof(token_t)*8 - 8) - 1,
     CHAR_MASK = 0x1ff,   /* 8th bit is used to distinguish EOF from 0xff */
 };
Function Documentation
create_J()
static NOINLINE int* create_J (FILE_and_pos_t ft[2], int nlen[2], off_t * ix[2]) static
Definition at line 450 of file diff.c.
 {
     int *J, slen[2], *class, *member;
     struct line *nfile[2], *sfile[2];
     int pref = 0, suff = 0, i, j, delta;
     /* Lines of both files are hashed, and in the process
      * their offsets are stored in the array ix[fileno]
      * where fileno == 0 points to the old file, and
      * fileno == 1 points to the new one.
      */
     for (i = 0; i < 2; i++) {
         unsigned hash;
         token_t tok;
         size_t sz = 100;
         nfile[i] = xmalloc((sz + 3) * sizeof(nfile[i][0]));
         /* ft gets here without the correct position, cant use seek_ft */
         ft[i].ft_pos = 0;
         fseeko(ft[i].ft_fp, 0, SEEK_SET);
         nlen[i] = 0;
         /* We could zalloc nfile, but then zalloc starts showing in gprof at ~1% */
         nfile[i][0].offset = 0;
         goto start; /* saves code */
         while (1) {
             tok = read_token(&ft[i], tok);
             if (!(tok & TOK_EMPTY)) {
                 /* Hash algorithm taken from Robert Sedgewick, Algorithms in C, 3d ed., p 578. */
                 /*hash = hash * 128 - hash + TOK2CHAR(tok);
                  * gcc insists on optimizing above to "hash * 127 + ...", thus... */
                 unsigned o = hash - TOK2CHAR(tok);
                 hash = hash * 128 - o; /* we want SPEED here */
                 continue;
             }
             if (nlen[i]++ == sz) {
                 sz = sz * 3 / 2;
                 nfile[i] = xrealloc(nfile[i], (sz + 3) * sizeof(nfile[i][0]));
             }
             /* line_compar needs hashes fit into positive int */
             nfile[i][nlen[i]].value = hash & INT_MAX;
             /* like ftello(ft[i].ft_fp) but faster (avoids lseek syscall) */
             nfile[i][nlen[i]].offset = ft[i].ft_pos;
             if (tok & TOK_EOF) {
                 /* EOF counts as a token, so we have to adjust it here */
                 nfile[i][nlen[i]].offset++;
                 break;
             }
 start:
             hash = tok = 0;
         }
         /* Exclude lone EOF line from the end of the file, to make fetch()'s job easier */
         if (nfile[i][nlen[i]].offset - nfile[i][nlen[i] - 1].offset == 1)
             nlen[i]--;
         /* Now we copy the line offsets into ix */
         ix[i] = xmalloc((nlen[i] + 2) * sizeof(ix[i][0]));
         for (j = 0; j < nlen[i] + 1; j++)
             ix[i][j] = nfile[i][j].offset;
     }
     /* length of prefix and suffix is calculated */
     for (; pref < nlen[0] && pref < nlen[1] &&
            nfile[0][pref + 1].value == nfile[1][pref + 1].value;
            pref++);
     for (; suff < nlen[0] - pref && suff < nlen[1] - pref &&
            nfile[0][nlen[0] - suff].value == nfile[1][nlen[1] - suff].value;
            suff++);
     /* Arrays are pruned by the suffix and prefix length,
      * the result being sorted and stored in sfile[fileno],
      * and their sizes are stored in slen[fileno]
      */
     for (j = 0; j < 2; j++) {
         sfile[j] = nfile[j] + pref;
         slen[j] = nlen[j] - pref - suff;
         for (i = 0; i <= slen[j]; i++)
             sfile[j][i].serial = i;
         qsort(sfile[j] + 1, slen[j], sizeof(*sfile[j]), line_compar);
     }
     /* nfile arrays are reused to reduce memory pressure
      * The #if zeroed out section performs the same task as the
      * one in the #else section.
      * Peak memory usage is higher, but one array copy is avoided
      * by not using unsort()
      */
 #if 0
     member = xmalloc((slen[1] + 2) * sizeof(member[0]));
     equiv(sfile[0], slen[0], sfile[1], slen[1], member);
     free(nfile[1]);
     class = xmalloc((slen[0] + 1) * sizeof(class[0]));
     for (i = 1; i <= slen[0]; i++) /* Unsorting */
         class[sfile[0][i].serial] = sfile[0][i].value;
     free(nfile[0]);
 #else
     member = (int *)nfile[1];
     equiv(sfile[0], slen[0], sfile[1], slen[1], member);
     member = xrealloc(member, (slen[1] + 2) * sizeof(member[0]));
     class = (int *)nfile[0];
     unsort(sfile[0], slen[0], (int *)nfile[0]);
     class = xrealloc(class, (slen[0] + 2) * sizeof(class[0]));
 #endif
     J = xmalloc((nlen[0] + 2) * sizeof(J[0]));
     /* The elements of J which fall inside the prefix and suffix regions
      * are marked as unchanged, while the ones which fall outside
      * are initialized with 0 (no matches), so that function stone can
      * then assign them their right values
      */
     for (i = 0, delta = nlen[1] - nlen[0]; i <= nlen[0]; i++)
         J[i] = i <= pref            ?  i :
                i > (nlen[0] - suff) ? (i + delta) : 0;
     /* Here the magic is performed */
     stone(class, slen[0], member, J, pref);
     J[nlen[0] + 1] = nlen[1] + 1;
     free(class);
     free(member);
     /* Both files are rescanned, in an effort to find any lines
      * which, due to limitations intrinsic to any hashing algorithm,
      * are different but ended up confounded as the same
      */
     for (i = 1; i <= nlen[0]; i++) {
         if (!J[i])
             continue;
         seek_ft(&ft[0], ix[0][i - 1]);
         seek_ft(&ft[1], ix[1][J[i] - 1]);
         for (j = J[i]; i <= nlen[0] && J[i] == j; i++, j++) {
             token_t tok0 = 0, tok1 = 0;
             do {
                 tok0 = read_token(&ft[0], tok0);
                 tok1 = read_token(&ft[1], tok1);
                 if (((tok0 ^ tok1) & TOK_EMPTY) != 0 /* one is empty (not both) */
                  || (!(tok0 & TOK_EMPTY) && TOK2CHAR(tok0) != TOK2CHAR(tok1))
                 ) {
                     J[i] = 0; /* Break the correspondence */
                 }
             } while (!(tok0 & tok1 & TOK_EMPTY));
         }
     }
     return J;
 }
References equiv(), free, FILE_and_pos_t::ft_pos, i, INT_MAX, j, line_compar(), member, offset, qsort(), read_token(), seek_ft(), SEEK_SET, start, stone(), TOK2CHAR, TOK_EMPTY, TOK_EOF, unsort(), value, xmalloc, and xrealloc.
Referenced by diff().
diff()
static bool diff (FILE * fp[2], char * file[2]) static
Definition at line 596 of file diff.c.
 {
     int nlen[2];
     off_t *ix[2];
     FILE_and_pos_t ft[2];
     typedef struct { int a, b; } vec_t[2];
     vec_t *vec = NULL;
     int i = 1, j, k, idx = -1;
     bool anychange = false;
     int *J;
     ft[0].ft_fp = fp[0];
     ft[1].ft_fp = fp[1];
     /* note that ft[i].ft_pos is unintitalized, create_J()
      * must not assume otherwise */
     J = create_J(ft, nlen, ix);
     do {
         bool nonempty = false;
         while (1) {
             vec_t v;
             for (v[0].a = i; v[0].a <= nlen[0] && J[v[0].a] == J[v[0].a - 1] + 1; v[0].a++)
                 continue;
             v[1].a = J[v[0].a - 1] + 1;
             for (v[0].b = v[0].a - 1; v[0].b < nlen[0] && !J[v[0].b + 1]; v[0].b++)
                 continue;
             v[1].b = J[v[0].b + 1] - 1;
             /*
              * Indicate that there is a difference between lines a and b of the 'from' file
              * to get to lines c to d of the 'to' file. If a is greater than b then there
              * are no lines in the 'from' file involved and this means that there were
              * lines appended (beginning at b).  If c is greater than d then there are
              * lines missing from the 'to' file.
              */
             if (v[0].a <= v[0].b || v[1].a <= v[1].b) {
                 /*
                  * If this change is more than 'context' lines from the
                  * previous change, dump the record and reset it.
                  */
                 int ct = (2 * opt_U_context) + 1;
                 if (idx >= 0
                  && v[0].a > vec[idx][0].b + ct
                  && v[1].a > vec[idx][1].b + ct
                 ) {
                     break;
                 }
                 for (j = 0; j < 2; j++)
                     for (k = v[j].a; k <= v[j].b; k++)
                         nonempty |= (ix[j][k] - ix[j][k - 1] != 1);
                 vec = xrealloc_vector(vec, 6, ++idx);
                 memcpy(vec[idx], v, sizeof(v));
             }
             i = v[0].b + 1;
             if (i > nlen[0])
                 break;
             J[v[0].b] = v[1].b;
         }
         if (idx < 0 || ((option_mask32 & FLAG(B)) && !nonempty))
             goto cont;
         if (!(option_mask32 & FLAG(q))) {
             int lowa;
             vec_t span, *cvp = vec;
             if (!anychange) {
                 /* Print the context/unidiff header first time through */
                 printf("--- %s\n", label[0] ? label[0] : file[0]);
                 printf("+++ %s\n", label[1] ? label[1] : file[1]);
             }
             printf("@@");
             for (j = 0; j < 2; j++) {
                 int a = span[j].a = MAX(1, (*cvp)[j].a - opt_U_context);
                 int b = span[j].b = MIN(nlen[j], vec[idx][j].b + opt_U_context);
                 printf(" %c%d", j ? '+' : '-', MIN(a, b));
                 if (a == b)
                     continue;
                 printf(",%d", (a < b) ? b - a + 1 : 0);
             }
             puts(" @@");
             /*
              * Output changes in "unified" diff format--the old and new lines
              * are printed together.
              */
             for (lowa = span[0].a; ; lowa = (*cvp++)[0].b + 1) {
                 bool end = cvp > &vec[idx];
                 fetch(&ft[0], ix[0], lowa, end ? span[0].b : (*cvp)[0].a - 1, ' ');
                 if (end)
                     break;
                 for (j = 0; j < 2; j++)
                     fetch(&ft[j], ix[j], (*cvp)[j].a, (*cvp)[j].b, j ? '+' : '-');
             }
         }
         anychange = true;
  cont:
         idx = -1;
     } while (i <= nlen[0]);
     free(vec);
     free(ix[0]);
     free(ix[1]);
     free(J);
     return anychange;
 }
References B, create_J(), end, fetch(), FLAG, free, FILE_and_pos_t::ft_fp, i, idx, j, k, label, MAX, memcpy(), MIN, NULL, off_t, opt_U_context, option_mask32, printf(), puts(), and xrealloc_vector.
Referenced by BF_set_key(), diffreg(), FindNearestColor(), I_GetPaletteIndex(), install_special_sighandlers(), iso8601wknum(), jiffies_diff(), malloc(), patch_main(), pause_after_failed_login(), pscan_main(), recv_pack(), rl_delete_text(), show_clock(), udhcpc6_main(), and udhcpc_main().
diff_main()
int diff_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 976 of file diff.c.
 {
     int gotstdin = 0, i;
     char *file[2], *s_start = NULL;
     llist_t *L_arg = NULL;
     INIT_G();
     /* exactly 2 params; collect multiple -L <label>; -U N */
     GETOPT32(argv, "^" "abdiL:*NqrsS:tTU:+wupBE" "\0" "=2"
             LONGOPTS,
             &L_arg, &s_start, &opt_U_context);
     argv += optind;
     while (L_arg)
         label[!!label[0]] = llist_pop(&L_arg);
     /* Compat: "diff file name_which_doesnt_exist" exits with 2 */
     xfunc_error_retval = 2;
     for (i = 0; i < 2; i++) {
         file[i] = argv[i];
         if (LONE_DASH(file[i])) {
             fstat(STDIN_FILENO, &stb[i]);
             gotstdin++;
         } else if (option_mask32 & FLAG(N)) {
             if (stat(file[i], &stb[i]))
                 xstat("/dev/null", &stb[i]);
         } else {
             xstat(file[i], &stb[i]);
         }
     }
     xfunc_error_retval = 1;
     if (gotstdin && (S_ISDIR(stb[0].st_mode) || S_ISDIR(stb[1].st_mode)))
         bb_simple_error_msg_and_die("can't compare stdin to a directory");
     /* Compare metadata to check if the files are the same physical file.
      *
      * Comment from diffutils source says:
      * POSIX says that two files are identical if st_ino and st_dev are
      * the same, but many file systems incorrectly assign the same (device,
      * inode) pair to two distinct files, including:
      * GNU/Linux NFS servers that export all local file systems as a
      * single NFS file system, if a local device number (st_dev) exceeds
      * 255, or if a local inode number (st_ino) exceeds 16777215.
      */
     if (ENABLE_DESKTOP
      && stb[0].st_ino == stb[1].st_ino
      && stb[0].st_dev == stb[1].st_dev
      && stb[0].st_size == stb[1].st_size
      && stb[0].st_mtime == stb[1].st_mtime
      && stb[0].st_ctime == stb[1].st_ctime
      && stb[0].st_mode == stb[1].st_mode
      && stb[0].st_nlink == stb[1].st_nlink
      && stb[0].st_uid == stb[1].st_uid
      && stb[0].st_gid == stb[1].st_gid
     ) {
         /* files are physically the same; no need to compare them */
         return STATUS_SAME;
     }
     if (S_ISDIR(stb[0].st_mode) && S_ISDIR(stb[1].st_mode)) {
 #if ENABLE_FEATURE_DIFF_DIR
         diffdir(file, s_start);
 #else
         bb_simple_error_msg_and_die("no support for directory comparison");
 #endif
     } else {
         bool dirfile = S_ISDIR(stb[0].st_mode) || S_ISDIR(stb[1].st_mode);
         bool dir = S_ISDIR(stb[1].st_mode);
         if (dirfile) {
             const char *slash = strrchr(file[!dir], '/');
             file[dir] = concat_path_file(file[dir], slash ? slash + 1 : file[!dir]);
             xstat(file[dir], &stb[dir]);
         }
         /* diffreg can get non-regular files here */
         print_status(gotstdin > 1 ? STATUS_SAME : diffreg(file), file);
         if (ENABLE_FEATURE_CLEAN_UP && dirfile)
             free(file[dir]);
     }
     return exit_status;
 }
References argv, bb_simple_error_msg_and_die(), concat_path_file(), diffreg(), dir, exit_status, FLAG, free, fstat(), GETOPT32, i, INIT_G, label, llist_pop(), LONE_DASH, LONGOPTS, N, NULL, opt_U_context, optind, option_mask32, print_status(), S_ISDIR, st_ctime, st_mtime, stat(), STATUS_SAME, stb, STDIN_FILENO, strrchr(), xfunc_error_retval, and xstat().
diffreg()
static int diffreg (char * file[2]) static
Definition at line 707 of file diff.c.
 {
     FILE *fp[2];
     bool binary = false, differ = false;
     int status = STATUS_SAME, i;
     fp[0] = stdin;
     fp[1] = stdin;
     for (i = 0; i < 2; i++) {
         int fd = STDIN_FILENO;
         if (!LONE_DASH(file[i])) {
             if (!(option_mask32 & FLAG(N))) {
                 fd = open_or_warn(file[i], O_RDONLY);
                 if (fd == -1)
                     goto out;
             } else {
                 /* -N: if some file does not exist compare it like empty */
                 fd = open(file[i], O_RDONLY);
                 if (fd == -1)
                     fd = xopen("/dev/null", O_RDONLY);
             }
         }
         /* Our diff implementation is using seek.
          * When we meet non-seekable file, we must make a temp copy.
          */
         if (lseek(fd, 0, SEEK_SET) == -1 && errno == ESPIPE) {
             char name[] = "/tmp/difXXXXXX";
             int fd_tmp = xmkstemp(name);
             unlink(name);
             if (bb_copyfd_eof(fd, fd_tmp) < 0)
                 xfunc_die();
             if (fd != STDIN_FILENO)
                 close(fd);
             fd = fd_tmp;
             xlseek(fd, 0, SEEK_SET);
         }
         fp[i] = fdopen(fd, "r");
     }
     setup_common_bufsiz();
     while (1) {
         const size_t sz = COMMON_BUFSIZE / 2;
         char *const buf0 = bb_common_bufsiz1;
         char *const buf1 = buf0 + sz;
         int j, k;
         i = fread(buf0, 1, sz, fp[0]);
         j = fread(buf1, 1, sz, fp[1]);
         if (i != j) {
             differ = true;
             i = MIN(i, j);
         }
         if (i == 0)
             break;
         for (k = 0; k < i; k++) {
             if (!buf0[k] || !buf1[k])
                 binary = true;
             if (buf0[k] != buf1[k])
                 differ = true;
         }
     }
     if (differ) {
         if (binary && !(option_mask32 & FLAG(a)))
             status = STATUS_BINARY;
         else if (diff(fp, file))
             status = STATUS_DIFFER;
     }
     if (status != STATUS_SAME)
         exit_status |= 1;
 out:
     fclose_if_not_stdin(fp[0]);
     fclose_if_not_stdin(fp[1]);
     return status;
 }
References bb_copyfd_eof(), close(), diff(), errno, ESPIPE, exit_status, fclose_if_not_stdin(), fd, FLAG, fread(), i, j, k, LONE_DASH, lseek(), MIN, N, O_RDONLY, open(), open_or_warn(), option_mask32, out(), SEEK_SET, status, STATUS_BINARY, STATUS_DIFFER, STATUS_SAME, stdin, STDIN_FILENO, unlink(), xfunc_die(), xlseek(), xmkstemp(), and xopen().
Referenced by diff_main().
equiv()
static void equiv (struct line * a, int n, struct line * b, int m, int * c) static
Definition at line 362 of file diff.c.
 {
     int i = 1, j = 1;
     while (i <= n && j <= m) {
         if (a[i].value < b[j].value)
             a[i++].value = 0;
         else if (a[i].value == b[j].value)
             a[i++].value = j;
         else
             j++;
     }
     while (i <= n)
         a[i++].value = 0;
     b[m + 1].value = 0;
     j = 0;
     while (++j <= m) {
         c[j] = -b[j].serial;
         while (b[j + 1].value == b[j].value) {
             j++;
             c[j] = b[j].serial;
         }
     }
     c[j] = -1;
 }
References c, i, j, n, line::value, and value.
Referenced by create_J(), and quote_string_for_globbing().
fetch()
static void fetch (FILE_and_pos_t * ft, const off_t * ix, int a, int b, int ch) static
Definition at line 411 of file diff.c.
 {
     int i, j, col;
     for (i = a; i <= b; i++) {
         seek_ft(ft, ix[i - 1]);
         putchar(ch);
         if (option_mask32 & FLAG(T))
             putchar('\t');
         for (j = 0, col = 0; j < ix[i] - ix[i - 1]; j++) {
             int c = fgetc(ft->ft_fp);
             if (c == EOF) {
                 puts("\n\\ No newline at end of file");
                 return;
             }
             ft->ft_pos++;
             if (c == '\t' && (option_mask32 & FLAG(t)))
                 do putchar(' '); while (++col & 7);
             else {
                 putchar(c);
                 col++;
             }
         }
     }
 }
References c, EOF, fgetc, FLAG, FILE_and_pos_t::ft_fp, FILE_and_pos_t::ft_pos, i, j, option_mask32, putchar, puts(), seek_ft(), t, and T.
Referenced by diff().
line_compar()
static int line_compar (const void * a, const void * b) static
Definition at line 399 of file diff.c.
 {
 #define l0 ((const struct line*)a)
 #define l1 ((const struct line*)b)
     int r = l0->value - l1->value;
     if (r)
         return r;
     return l0->serial - l1->serial;
 #undef l0
 #undef l1
 }
References l0, and l1.
Referenced by create_J().
print_status()
static void print_status (int status, char * path[2]) static
Definition at line 783 of file diff.c.
 {
     switch (status) {
     case STATUS_BINARY:
     case STATUS_DIFFER:
         if ((option_mask32 & FLAG(q)) || status == STATUS_BINARY)
             printf("Files %s and %s differ\n", path[0], path[1]);
         break;
     case STATUS_SAME:
         if (option_mask32 & FLAG(s))
             printf("Files %s and %s are identical\n", path[0], path[1]);
         break;
     }
 }
References FLAG, option_mask32, printf(), s, status, STATUS_BINARY, STATUS_DIFFER, and STATUS_SAME.
Referenced by diff_main().
read_token()
static int read_token (FILE_and_pos_t * ft, token_t tok) static
Definition at line 212 of file diff.c.
 {
     tok |= TOK_EMPTY;
     while (!(tok & TOK_EOL)) {
         bool is_space;
         int t;
         t = fgetc(ft->ft_fp);
         if (t != EOF)
             ft->ft_pos++;
         is_space = (t == EOF || isspace(t));
         /* If t == EOF (-1), set both TOK_EOF and TOK_EOL */
         tok |= (t & (TOK_EOF + TOK_EOL));
         /* Only EOL? */
         if (t == '\n')
             tok |= TOK_EOL;
         if (option_mask32 & FLAG(i)) /* Handcoded tolower() */
             t = (t >= 'A' && t <= 'Z') ? t - ('A' - 'a') : t;
         if ((option_mask32 & FLAG(w)) && is_space)
             continue;
         /* Trim char value to low 9 bits */
         t &= CHAR_MASK;
         if (option_mask32 & FLAG(b)) {
             /* Was prev char whitespace? */
             if (tok & TOK_SPACE) { /* yes */
                 if (is_space) /* this one too, ignore it */
                     continue;
                 tok &= ~TOK_SPACE;
             } else if (is_space) {
                 /* 1st whitespace char.
                  * Set TOK_SPACE and replace char by ' ' */
                 t = TOK_SPACE + ' ';
             }
         }
         /* Clear EMPTY */
         tok &= ~(TOK_EMPTY + CHAR_MASK);
         /* Assign char value (low 9 bits) and maybe set TOK_SPACE */
         tok |= t;
         break;
     }
 #if 0
     bb_error_msg("fp:%p tok:%x '%c'%s%s%s%s", fp, tok, tok & 0xff
         , tok & TOK_EOF ? " EOF" : ""
         , tok & TOK_EOL ? " EOL" : ""
         , tok & TOK_EMPTY ? " EMPTY" : ""
         , tok & TOK_SPACE ? " SPACE" : ""
     );
 #endif
     return tok;
 }
References bb_error_msg(), CHAR_MASK, EOF, fgetc, FLAG, FILE_and_pos_t::ft_fp, FILE_and_pos_t::ft_pos, i, isspace, option_mask32, t, TOK_EMPTY, TOK_EOF, TOK_EOL, TOK_SPACE, and w.
Referenced by create_J().
search()
static int search (const int * c, int k, int y, const struct cand * list) static
Definition at line 274 of file diff.c.
 {
     int i, j;
     if (list[c[k]].y < y)  /* quick look for typical case */
         return k + 1;
     for (i = 0, j = k + 1;;) {
         const int l = (i + j) >> 1;
         if (l > i) {
             const int t = list[c[l]].y;
             if (t > y)
                 j = l;
             else if (t < y)
                 i = l;
             else
                 return l;
         } else
             return l + 1;
     }
 }
References c, i, j, k, l, list(), t, and y.
Referenced by __get_resolv_conf(), do_tzset(), find_iface_state(), name_from_dns_search(), rl_do_undo(), and stone().
seek_ft()
static void seek_ft (FILE_and_pos_t * ft, off_t pos) static
Definition at line 201 of file diff.c.
 {
     if (ft->ft_pos != pos) {
         ft->ft_pos = pos;
         fseeko(ft->ft_fp, pos, SEEK_SET);
     }
 }
References FILE_and_pos_t::ft_fp, FILE_and_pos_t::ft_pos, pos, and SEEK_SET.
Referenced by create_J(), and fetch().
stone()
static void stone (const int * a, int n, const int * b, int * J, int pref) static
Definition at line 296 of file diff.c.
 {
     const unsigned isq = isqrt(n);
     const unsigned bound =
         (option_mask32 & FLAG(d)) ? UINT_MAX : MAX(256, isq);
     int clen = 1;
     int clistlen = 100;
     int k = 0;
     struct cand *clist = xzalloc(clistlen * sizeof(clist[0]));
     struct cand cand;
     struct cand *q;
     int *klist = xzalloc((n + 2) * sizeof(klist[0]));
     /*clist[0] = (struct cand){0}; - xzalloc did it */
     /*klist[0] = 0; */
     for (cand.x = 1; cand.x <= n; cand.x++) {
         int j = a[cand.x], oldl = 0;
         unsigned numtries = 0;
         if (j == 0)
             continue;
         cand.y = -b[j];
         cand.pred = klist[0];
         do {
             int l, tc;
             if (cand.y <= clist[cand.pred].y)
                 continue;
             l = search(klist, k, cand.y, clist);
             if (l != oldl + 1)
                 cand.pred = klist[l - 1];
             if (l <= k && clist[klist[l]].y <= cand.y)
                 continue;
             if (clen == clistlen) {
                 clistlen = clistlen * 11 / 10;
                 clist = xrealloc(clist, clistlen * sizeof(clist[0]));
             }
             clist[clen] = cand;
             tc = klist[l];
             klist[l] = clen++;
             if (l <= k) {
                 cand.pred = tc;
                 oldl = l;
                 numtries++;
             } else {
                 k++;
                 break;
             }
         } while ((cand.y = b[++j]) > 0 && numtries < bound);
     }
     /* Unravel */
     for (q = clist + klist[k]; q->y; q = clist + q->pred)
         J[q->x + pref] = q->y + pref;
     free(klist);
     free(clist);
 }
References FLAG, free, isqrt(), j, k, l, MAX, n, option_mask32, cand::pred, search(), tc, UINT_MAX, cand::x, xrealloc, xzalloc(), cand::y, and y.
Referenced by create_J().
unsort()
static void unsort (const struct line * f, int l, int * b) static
Definition at line 388 of file diff.c.
 {
     int i;
     int *a = xmalloc((l + 1) * sizeof(a[0]));
     for (i = 1; i <= l; i++)
         a[f[i].serial] = f[i].value;
     for (i = 1; i <= l; i++)
         b[i] = a[i];
     free(a);
 }
References f, free, i, l, value, and xmalloc.
Referenced by create_J().