Fennix: Userspace/libc/include/dlfcn.h File Reference
dlfcn.h File Reference
#include <types.h>
Functions
void * dlopen (const char *filename, int flags)
void * dlsym (void *handle, const char *symbol)
int dlclose (void *handle)
char * dlerror (void)
Function Documentation
dlclose()
int dlclose (void * handle)
Definition at line 20 of file dlfcn-stubs.cpp.
{
     return __dlapi_close(handle);
 }
References __dlapi_close().
Referenced by main().
dlerror()
char* dlerror (void)
Definition at line 24 of file dlfcn-stubs.cpp.
                     {
     return const_cast<char *>(__dlapi_error());
 }
References __dlapi_error().
dlopen()
void* dlopen (const char * filename, int flags)
Definition at line 29 of file dlfcn-stubs.cpp.
{
     auto ra = __builtin_extract_return_addr(__builtin_return_address(0));
     return __dlapi_open(file, flags, ra);
 }
References __dlapi_open(), and mlibc::flags.
Referenced by main().
dlsym()
void* dlsym (void * handle, const char * symbol)
Referenced by barGetDefault(), barGetNext(), fooGetDefault(), fooGetNext(), and main().