Fennix: Drivers/input/aip/uart.c File Reference
uart.c File Reference
#include "aip.h"
#include <errno.h>
#include <base.h>
#include <fs.h>
#include <input.h>
#include <io.h>
Data Structures
union IER
union IIR
union FCR
union LCR
union MCR
union LSR
union MSR
union UARTs
struct IER.__unnamed1004__
struct IIR.__unnamed1006__
struct FCR.__unnamed1008__
struct LCR.__unnamed1010__
struct MCR.__unnamed1012__
struct LSR.__unnamed1014__
struct MSR.__unnamed1016__
struct UARTs.__unnamed1018__
Macros
#define SERIAL_ENABLE_DLAB 0x80
#define SERIAL_BUFFER_EMPTY 0x20
Enumerations
enum Ports {
COM1 = 0x3F8 , COM2 = 0x2F8 , COM3 = 0x3E8 , COM4 = 0x2E8 ,
COM5 = 0x5F8 , COM6 = 0x4F8 , COM7 = 0x5E8 , COM8 = 0x4E8 ,
LPT1 = 0x378 , LPT2 = 0x278 , LPT3 = 0x3BC
}
enum SerialSpeed {
RATE_50_HI = 0x09 , RATE_50_LO = 0x00 , RATE_300_HI = 0x01 , RATE_300_LO = 0x80 ,
RATE_600_HI = 0x00 , RATE_600_LO = 0xC0 , RATE_2400_HI = 0x00 , RATE_2400_LO = 0x30 ,
RATE_4800_HI = 0x00 , RATE_4800_LO = 0x18 , RATE_9600_HI = 0x00 , RATE_9600_LO = 0x0C ,
RATE_19200_HI = 0x00 , RATE_19200_LO = 0x06 , RATE_38400_HI = 0x00 , RATE_38400_LO = 0x03 ,
RATE_57600_HI = 0x00 , RATE_57600_LO = 0x02 , RATE_115200_HI = 0x00 , RATE_115200_LO = 0x01
}
Functions
bool IsDataReady (uint16_t Port)
bool IsTransmitEmpty (uint16_t Port)
char ReadSerial (uint16_t Port)
void WriteSerial (uint16_t Port, char Character)
void ReportSerialReceived (uint8_t Data)
void UartCOM24 (TrapFrame *)
void UartCOM13 (TrapFrame *)
bool InitializePort (uint16_t Port)
int DetectUART ()
Variables
union UARTs uart
Data Structure Documentation
IER
union IER
Interrupt Enable Register
Definition at line 103 of file uart.c.
Data Fields
struct IER __unnamed__
uint8_t raw
IIR
union IIR
Interrupt Identification Register
Definition at line 132 of file uart.c.
Data Fields
struct IIR __unnamed__
uint8_t raw
FCR
union FCR
First In / First Out Control Register
Definition at line 175 of file uart.c.
Data Fields
struct FCR __unnamed__
uint8_t raw
LCR
union LCR
Line Control Register
Definition at line 213 of file uart.c.
Data Fields
struct LCR __unnamed__
uint8_t raw
MCR
union MCR
Modem Control Register
Definition at line 258 of file uart.c.
Data Fields
struct MCR __unnamed__
uint8_t raw
LSR
union LSR
Line Status Register
Definition at line 287 of file uart.c.
Data Fields
struct LSR __unnamed__
uint8_t raw
MSR
union MSR
Modem Status Register
Definition at line 319 of file uart.c.
Data Fields
struct MSR __unnamed__
uint8_t raw
UARTs
union UARTs
Definition at line 350 of file uart.c.
Data Fields
struct UARTs __unnamed__
uint16_t raw
IER.__unnamed1004__
struct IER.__unnamed1004__
Definition at line 105 of file uart.c.
Data Fields
uint8_t __reserved: 2
uint8_t InterruptOnReceive: 1
uint8_t InterruptOnTransmitter: 1
uint8_t LineStatusInterrupt: 1
uint8_t LowPowerMode: 1
uint8_t ModemStatusInterrupt: 1
uint8_t SleepMode: 1
IIR.__unnamed1006__
struct IIR.__unnamed1006__
Definition at line 134 of file uart.c.
Data Fields
uint8_t __reserved: 1
Reserved
uint8_t FIFO: 2
Enable FIFO
00b = No FIFO 01b = FIFO Enabled but Unusable 11b = FIFO Enabled
uint8_t FIFO64: 1
64 Byte Fifo Enabled (16750 only)
uint8_t InterruptPending: 1
uint8_t InterruptStatus: 2
Interrupt Status
00b = Modem Status Interrupt 01b = Transmitter Holding Register Empty Interrupt 10b = Received Data Available Interrupt 11b = Receiver Line Status Interrupt
uint8_t TimeOutIP: 1
16550 Time-out Interrupt Pending
Note
Reserved on 8250, 16450
FCR.__unnamed1008__
struct FCR.__unnamed1008__
Definition at line 177 of file uart.c.
Data Fields
uint8_t __reserved: 1
Reserved
uint8_t ClearRX: 1
Clear Receive FIFO
uint8_t ClearTX: 1
Clear Transmit FIFO
uint8_t DMAMode: 1
DMA Mode Select.
Change status of RXRDY & TXRDY pins from mode 1 to mode 2.
uint8_t FIFO: 1
Enable FIFO's
uint8_t FIFO64: 1
Enable 64 Byte FIFO (16750 only)
uint8_t TriggerLevel: 2
Interrupt Trigger Level
00b = 1 Byte 01b = 4 Bytes 10b = 8 Bytes 11b = 14 Bytes
LCR.__unnamed1010__
struct LCR.__unnamed1010__
Definition at line 215 of file uart.c.
Data Fields
uint8_t DLAB: 1
Divisor Latch Access
0b = Access to Receiver buffer, Transmitter buffer & Interrupt Enable Register 1b = Divisor Latch Access Bit
uint8_t Parity: 3
Parity Select
0b = No Parity 001b = Odd Parity 011b = Even Parity 101b = High Parity (Sticky) 111b = Low Parity (Sticky)
uint8_t SetBreak: 1
Set Break Enable
uint8_t StopBit: 1
Length of Stop Bit
0b = One Stop Bit 1b = 2 Stop bits for words of length 6,7 or 8 bits or 1.5 Stop Bits for Word lengths of 5 bits.
uint8_t WordLength: 2
Word Length
00b = 5 bits 01b = 6 bits 10b = 7 bits 11b = 8 bits
MCR.__unnamed1012__
struct MCR.__unnamed1012__
Definition at line 260 of file uart.c.
Data Fields
uint8_t __reserved: 2
Reserved
uint8_t Autoflow: 1
Autoflow Control Enabled (16750 only)
uint8_t DataTerminalReady: 1
Force Data Terminal Ready
uint8_t Loopback: 1
Loopback Mode
uint8_t Out1: 1
Auxiliary Output 1
uint8_t Out2: 1
Auxiliary Output 2
uint8_t RequestToSend: 1
Force Request to Send
LSR.__unnamed1014__
struct LSR.__unnamed1014__
Definition at line 289 of file uart.c.
Data Fields
uint8_t BreakInterrupt: 1
Break Interrupt
uint8_t DataReady: 1
Data Ready
uint8_t EmptyDataHolding: 1
Empty Data Holding Registers
uint8_t EmptyTransmitterHolding: 1
Empty Transmitter Holding Register
uint8_t ErrorReceivedFIFO: 1
Error in Received FIFO
uint8_t FramingError: 1
Framing Error
uint8_t OverrunError: 1
Overrun Error
uint8_t ParityError: 1
Parity Error
MSR.__unnamed1016__
struct MSR.__unnamed1016__
Definition at line 321 of file uart.c.
Data Fields
uint8_t CarrierDetect: 1
Carrier Detect
uint8_t ClearToSend: 1
Clear To Send
uint8_t DataSetReady: 1
Data Set Ready
uint8_t DeltaClearToSend: 1
Delta Clear to Send
uint8_t DeltaDataCarrierDetect: 1
Delta Data Carrier Detect
uint8_t DeltaDataSetReady: 1
Delta Data Set Ready
uint8_t RingIndicator: 1
Ring Indicator
uint8_t TrailingEdgeRingIndicator: 1
Trailing Edge Ring Indicator
UARTs.__unnamed1018__
struct UARTs.__unnamed1018__
Definition at line 352 of file uart.c.
Data Fields
uint8_t __reserved: 5
uint8_t com1: 1
uint8_t com2: 1
uint8_t com3: 1
uint8_t com4: 1
uint8_t com5: 1
uint8_t com6: 1
uint8_t com7: 1
uint8_t com8: 1
uint8_t lpt1: 1
uint8_t lpt2: 1
uint8_t lpt3: 1
Macro Definition Documentation
SERIAL_BUFFER_EMPTY
#define SERIAL_BUFFER_EMPTY 0x20
Definition at line 27 of file uart.c.
SERIAL_ENABLE_DLAB
#define SERIAL_ENABLE_DLAB 0x80
Definition at line 26 of file uart.c.
Enumeration Type Documentation
Ports
enum Ports
Enumerator
COM1
COM2
COM3
COM4
COM5
COM6
COM7
COM8
LPT1
LPT2
LPT3
Definition at line 29 of file uart.c.
 {
     COM1 = 0x3F8,
     COM2 = 0x2F8,
     COM3 = 0x3E8,
     COM4 = 0x2E8,
     COM5 = 0x5F8,
     COM6 = 0x4F8,
     COM7 = 0x5E8,
     COM8 = 0x4E8,
     LPT1 = 0x378,
     LPT2 = 0x278,
     LPT3 = 0x3BC
 };
SerialSpeed
enum SerialSpeed
Enumerator
RATE_50_HI
RATE_50_LO
RATE_300_HI
RATE_300_LO
RATE_600_HI
RATE_600_LO
RATE_2400_HI
RATE_2400_LO
RATE_4800_HI
RATE_4800_LO
RATE_9600_HI
RATE_9600_LO
RATE_19200_HI
RATE_19200_LO
RATE_38400_HI
RATE_38400_LO
RATE_57600_HI
RATE_57600_LO
RATE_115200_HI
RATE_115200_LO
Definition at line 45 of file uart.c.
 {
     RATE_50_HI = 0x09,
     RATE_50_LO = 0x00,
     RATE_300_HI = 0x01,
     RATE_300_LO = 0x80,
     RATE_600_HI = 0x00,
     RATE_600_LO = 0xC0,
     RATE_2400_HI = 0x00,
     RATE_2400_LO = 0x30,
     RATE_4800_HI = 0x00,
     RATE_4800_LO = 0x18,
     RATE_9600_HI = 0x00,
     RATE_9600_LO = 0x0C,
     RATE_19200_HI = 0x00,
     RATE_19200_LO = 0x06,
     RATE_38400_HI = 0x00,
     RATE_38400_LO = 0x03,
     RATE_57600_HI = 0x00,
     RATE_57600_LO = 0x02,
     RATE_115200_HI = 0x00,
     RATE_115200_LO = 0x01
 };
Function Documentation
DetectUART()
int DetectUART ()
Definition at line 499 of file uart.c.
 {
     uart.com1 = inb(COM1) != 0xFF ? true : false;
     uart.com2 = inb(COM2) != 0xFF ? true : false;
     uart.com3 = inb(COM3) != 0xFF ? true : false;
     uart.com4 = inb(COM4) != 0xFF ? true : false;
     uart.com5 = inb(COM5) != 0xFF ? true : false;
     uart.com6 = inb(COM6) != 0xFF ? true : false;
     uart.com7 = inb(COM7) != 0xFF ? true : false;
     uart.com8 = inb(COM8) != 0xFF ? true : false;
     uart.lpt1 = inb(LPT1) != 0xFF ? true : false;
     uart.lpt2 = inb(LPT2) != 0xFF ? true : false;
     uart.lpt3 = inb(LPT3) != 0xFF ? true : false;
     if (uart.com1 == true)
         if (InitializePort(COM1) == false)
             uart.com1 = false;
     if (uart.com2 == true)
         if (InitializePort(COM2) == false)
             uart.com1 = false;
     if (uart.com3 == true)
         if (InitializePort(COM3) == false)
             uart.com1 = false;
     if (uart.com4 == true)
         if (InitializePort(COM4) == false)
             uart.com1 = false;
     if (uart.com5 == true)
         if (InitializePort(COM5) == false)
             uart.com1 = false;
     if (uart.com6 == true)
         if (InitializePort(COM6) == false)
             uart.com1 = false;
     if (uart.com7 == true)
         if (InitializePort(COM7) == false)
             uart.com1 = false;
     if (uart.com8 == true)
         if (InitializePort(COM8) == false)
             uart.com1 = false;
     if (uart.lpt1 == true)
         KernelPrint("LPT1 is present");
     if (uart.lpt2 == true)
         KernelPrint("LPT2 is present");
     if (uart.lpt3 == true)
         KernelPrint("LPT3 is present");
     return 0;
 }
References COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, inb(), InitializePort(), KernelPrint(), LPT1, LPT2, LPT3, true, and uart.
Referenced by DriverProbe().
InitializePort()
bool InitializePort (uint16_t Port)
Definition at line 433 of file uart.c.
 {
     ECS;
     LCR lcr = {0};
     IER ier = {0};
     FCR fcr = {0};
     MCR mcr = {0};
     outb(Port + 3, lcr.raw);
     outb(Port + 1, ier.raw);
     lcr.DLAB = 1;
     outb(Port + 3, lcr.raw);
     outb(Port + 0, RATE_115200_LO);
     outb(Port + 1, RATE_115200_HI);
     lcr.DLAB = 0;
     lcr.WordLength = 0b11;
     outb(Port + 3, lcr.raw);
     fcr.FIFO = 1;
     fcr.ClearRX = 1;
     fcr.ClearTX = 1;
     fcr.TriggerLevel = 0b11;
     outb(Port + 2, fcr.raw);
     mcr.DataTerminalReady = 1;
     mcr.RequestToSend = 1;
     mcr.Out2 = 1;
     mcr.Loopback = 1;
     outb(Port + 4, mcr.raw);
     /* Test the serial port */
     outb(Port + 0, 0x48);
     uint8_t result = inb(Port + 0);
     if (result != 0x48)
     {
         /* FIXME: DETECT BAUD RATE
             Do multiple test to check if the output is garbage.
             If so, reduce the baud rate until it works. */
         LCS;
         KernelPrint("Port %#X test failed!", Port);
         return false;
     }
     /* Set normal operation mode */
     mcr.DataTerminalReady = 1;
     mcr.RequestToSend = 1;
     mcr.Out1 = 1;
     mcr.Out2 = 1;
     mcr.Loopback = 0;
     outb(Port + 4, mcr.raw);
     /* Enable interrupts on receive */
     ier.InterruptOnReceive = 1;
     outb(Port + 1, ier.raw);
     RegisterInterruptHandler(3, UartCOM24);
     RegisterInterruptHandler(4, UartCOM13);
     LCS;
     KernelPrint("Port %#X initialized", Port);
     return true;
 }
References ECS, inb(), KernelPrint(), LCS, outb(), RATE_115200_HI, RATE_115200_LO, IER::raw, FCR::raw, LCR::raw, MCR::raw, RegisterInterruptHandler(), UartCOM13(), and UartCOM24().
Referenced by DetectUART().
IsDataReady()
bool IsDataReady (uint16_t Port)
Definition at line 372 of file uart.c.
 {
     LSR lsr;
     lsr.raw = inb(Port + 5);
     return lsr.DataReady;
 }
References inb(), and LSR::raw.
Referenced by ReadSerial().
IsTransmitEmpty()
bool IsTransmitEmpty (uint16_t Port)
Definition at line 379 of file uart.c.
 {
     LSR lsr;
     lsr.raw = inb(Port + 5);
     return lsr.EmptyTransmitterHolding;
 }
References inb(), and LSR::raw.
Referenced by WriteSerial().
ReadSerial()
char ReadSerial (uint16_t Port)
Definition at line 386 of file uart.c.
 {
     while (!IsDataReady(Port))
         Yield();
     return inb(Port);
 }
References inb(), IsDataReady(), and Yield().
ReportSerialReceived()
void ReportSerialReceived (uint8_t Data)
Definition at line 400 of file uart.c.
 {
     DebugLog("%c", Data);
 }
References Data, and DebugLog.
Referenced by UartCOM13(), and UartCOM24().
UartCOM13()
void UartCOM13 (TrapFrame *)
Definition at line 419 of file uart.c.
 {
     LSR lsr1, lsr3;
     do
     {
         lsr1.raw = inb(COM1 + 5);
         if (lsr1.DataReady)
             ReportSerialReceived(inb(COM1));
         lsr3.raw = inb(COM3 + 5);
         if (lsr3.DataReady)
             ReportSerialReceived(inb(COM3));
     } while (lsr1.DataReady || lsr3.DataReady);
 }
References COM1, COM3, inb(), LSR::raw, and ReportSerialReceived().
Referenced by InitializePort().
UartCOM24()
void UartCOM24 (TrapFrame *)
Definition at line 405 of file uart.c.
 {
     LSR lsr2, lsr4;
     do
     {
         lsr2.raw = inb(COM2 + 5);
         if (lsr2.DataReady)
             ReportSerialReceived(inb(COM2));
         lsr4.raw = inb(COM4 + 5);
         if (lsr4.DataReady)
             ReportSerialReceived(inb(COM4));
     } while (lsr2.DataReady || lsr4.DataReady);
 }
References COM2, COM4, inb(), LSR::raw, and ReportSerialReceived().
Referenced by InitializePort().
WriteSerial()
void WriteSerial (uint16_t Port, char Character)
Definition at line 393 of file uart.c.
 {
     while (!IsTransmitEmpty(Port))
         Yield();
     outb(Port, Character);
 }
References IsTransmitEmpty(), outb(), and Yield().
Variable Documentation
uart
union UARTs uart
Referenced by DetectUART(), and DriverProbe().