Fennix Userspace: Userspace/apps/base/busybox/scripts/kconfig/lxdialog/msgbox.c File Reference
msgbox.c File Reference
#include "dialog.h"
Functions
int dialog_msgbox (const char *title, const char *prompt, int height, int width, int pause)
Function Documentation
dialog_msgbox()
int dialog_msgbox (const char * title, const char * prompt, int height, int width, int pause)
Definition at line 28 of file msgbox.c.
 {
     int i, x, y, key = 0;
     WINDOW *dialog;
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 2);
     if (pause) {
         wattrset(dialog, border_attr);
         mvwaddch(dialog, height - 3, 0, ACS_LTEE);
         for (i = 0; i < width - 2; i++)
             waddch(dialog, ACS_HLINE);
         wattrset(dialog, dialog_attr);
         waddch(dialog, ACS_RTEE);
         print_button(dialog, "  Ok  ", height - 2, width / 2 - 4, TRUE);
         wrefresh(dialog);
         while (key != ESC && key != '\n' && key != ' ' &&
                key != 'O' && key != 'o' && key != 'X' && key != 'x')
             key = wgetch(dialog);
     } else {
         key = '\n';
         wrefresh(dialog);
     }
     delwin(dialog);
     return key == ESC ? -1 : 0;
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, dialog_attr, draw_box(), draw_shadow(), ESC, height(), i, pause(), print_autowrap(), print_button(), print_title(), prompt, title, TRUE, width, x, and y.
Referenced by j_infobox(), and j_msgbox().