Fennix: Userspace/apps/base/busybox/coreutils/uniq.c File Reference
uniq.c File Reference
#include "libbb.h"
Functions
int uniq_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
uniq_main()
int uniq_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 44 of file uniq.c.
 {
     const char *input_filename;
     unsigned skip_fields, skip_chars, max_chars;
     unsigned opt;
     char eol;
     char *cur_line;
     const char *cur_compare;
     enum {
         OPT_c = 1 << 0,
         OPT_d = 1 << 1, /* print only dups */
         OPT_u = 1 << 2, /* print only uniq */
         OPT_f = 1 << 3,
         OPT_s = 1 << 4,
         OPT_w = 1 << 5,
         OPT_i = 1 << 6,
         OPT_z = 1 << 7,
     };
     skip_fields = skip_chars = 0;
     max_chars = INT_MAX;
     opt = getopt32(argv, "cduf:+s:+w:+iz", &skip_fields, &skip_chars, &max_chars);
     argv += optind;
     input_filename = argv[0];
     if (input_filename) {
         const char *output;
         if (input_filename[0] != '-' || input_filename[1]) {
             close(STDIN_FILENO); /* == 0 */
             xopen(input_filename, O_RDONLY); /* fd will be 0 */
         }
         output = argv[1];
         if (output) {
             if (argv[2])
                 bb_show_usage();
             if (output[0] != '-' || output[1]) {
                 // Won't work with "uniq - FILE" and closed stdin:
                 //close(STDOUT_FILENO);
                 //xopen(output, O_WRONLY | O_CREAT | O_TRUNC);
                 xmove_fd(xopen(output, O_WRONLY | O_CREAT | O_TRUNC), STDOUT_FILENO);
             }
         }
     }
     cur_compare = cur_line = NULL; /* prime the pump */
     eol = (opt & OPT_z) ? 0 : '\n';
     do {
         unsigned i;
         unsigned long dups;
         char *old_line;
         const char *old_compare;
         old_line = cur_line;
         old_compare = cur_compare;
         dups = 0;
         /* gnu uniq ignores newlines */
         while ((cur_line = xmalloc_fgetline(stdin)) != NULL) {
             cur_compare = cur_line;
             for (i = skip_fields; i; i--) {
                 cur_compare = skip_whitespace(cur_compare);
                 cur_compare = skip_non_whitespace(cur_compare);
             }
             for (i = skip_chars; *cur_compare && i; i--) {
                 ++cur_compare;
             }
             if (!old_line)
                 break;
             if ((opt & OPT_i)
                 ? strncasecmp(old_compare, cur_compare, max_chars)
                 : strncmp(old_compare, cur_compare, max_chars)
             ) {
                 break;
             }
             free(cur_line);
             ++dups;  /* testing for overflow seems excessive */
         }
         if (old_line) {
             if (!(opt & (OPT_d << !!dups))) { /* (if dups, opt & OPT_u) */
                 if (opt & OPT_c) {
                     /* %7lu matches GNU coreutils 6.9 */
                     printf("%7lu ", dups + 1);
                 }
                 printf("%s%c", old_line, eol);
             }
             free(old_line);
         }
     } while (cur_line);
     die_if_ferror(stdin, input_filename);
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, bb_show_usage(), close(), die_if_ferror(), fflush_stdout_and_exit_SUCCESS(), free, getopt32(), i, INT_MAX, NULL, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, opt, OPT_c, OPT_d, OPT_f, OPT_i, OPT_s, OPT_u, OPT_w, OPT_z, optind, output, printf, skip_non_whitespace(), skip_whitespace(), stdin, STDIN_FILENO, STDOUT_FILENO, strncasecmp, strncmp(), xmalloc_fgetline(), xmove_fd(), and xopen().