Fennix: Disk::Manager Class Reference
Disk::Manager Class Reference
#include <disk.hpp>
Public Member Functions
void FetchDisks (unsigned long DriverUID)
Manager ()
~Manager ()
Private Attributes
unsigned char AvailablePorts = 0
int BytesPerSector = 0
Vector< Drive * > drives
Detailed Description
Definition at line 150 of file disk.hpp.
Constructor & Destructor Documentation
Manager()
Disk::Manager::Manager ()
Definition at line 150 of file Disk.cpp.
     {
     }
~Manager()
Disk::Manager::~Manager ()
Definition at line 154 of file Disk.cpp.
     {
     }
Member Function Documentation
FetchDisks()
void Disk::Manager::FetchDisks (unsigned long DriverUID)
Definition at line 12 of file Disk.cpp.
     {
         KernelCallback *callback = (KernelCallback *)KernelAllocator.RequestPages(TO_PAGES(sizeof(KernelCallback)));
         memset(callback, 0, sizeof(KernelCallback));
         callback->Reason = FetchReason;
         DriverManager->IOCB(DriverUID, (void *)callback);
         this->AvailablePorts = callback->DiskCallback.Fetch.Ports;
         this->BytesPerSector = callback->DiskCallback.Fetch.BytesPerSector;
         debug("AvailablePorts:%ld BytesPerSector:%ld", this->AvailablePorts, this->BytesPerSector);
         if (this->AvailablePorts <= 0)
         {
             KernelAllocator.FreePages((void *)callback, TO_PAGES(sizeof(KernelCallback)));
             return;
         }
         uint8_t *RWBuffer = (uint8_t *)KernelAllocator.RequestPages(TO_PAGES(this->BytesPerSector));
         for (unsigned char ItrPort = 0; ItrPort < this->AvailablePorts; ItrPort++)
         {
             Drive *drive = new Drive;
             sprintf(drive->Name, "sd%ld-%d", DriverUID, this->AvailablePorts);
             debug("Drive Name: %s", drive->Name);
             // TODO: Implement disk type detection. Very useful in the future.
             drive->MechanicalDisk = true;
             memset(RWBuffer, 0, this->BytesPerSector);
             memset(callback, 0, sizeof(KernelCallback));
             callback->Reason = ReceiveReason;
             callback->DiskCallback.RW = {
                 .Sector = 0,
                 .SectorCount = 2,
                 .Port = ItrPort,
                 .Buffer = RWBuffer,
                 .Write = false,
             };
             DriverManager->IOCB(DriverUID, (void *)callback);
             memcpy(&drive->Table, RWBuffer, sizeof(PartitionTable));
             /*
             ----> Add to devfs the disk
             */
             if (drive->Table.GPT.Signature == GPT_MAGIC)
             {
                 drive->Style = GPT;
                 uint32_t Entries = 512 / drive->Table.GPT.EntrySize;
                 uint32_t Sectors = drive->Table.GPT.PartCount / Entries;
                 for (uint32_t Block = 0; Block < Sectors; Block++)
                 {
                     memset(RWBuffer, 0, this->BytesPerSector);
                     memset(callback, 0, sizeof(KernelCallback));
                     callback->Reason = ReceiveReason;
                     callback->DiskCallback.RW = {
                         .Sector = 2 + Block,
                         .SectorCount = 1,
                         .Port = ItrPort,
                         .Buffer = RWBuffer,
                         .Write = false,
                     };
                     DriverManager->IOCB(DriverUID, (void *)callback);
                     for (uint32_t e = 0; e < Entries; e++)
                     {
                         GUIDPartitionTablePartition GPTPartition = reinterpret_cast<GUIDPartitionTablePartition *>(RWBuffer)[e];
                         if (GPTPartition.TypeLow || GPTPartition.TypeHigh)
{
                             Partition *partition = new Partition;
                             memcpy(partition->Label, GPTPartition.Label, sizeof(partition->Label));
                             partition->StartLBA = GPTPartition.StartLBA;
                             partition->EndLBA = GPTPartition.EndLBA;
                             partition->Sectors = partition->EndLBA - partition->StartLBA;
                             partition->Port = ItrPort;
                             partition->Flags = Present;
                             partition->Style = GPT;
                             if (GPTPartition.Attributes & 1)
                                 partition->Flags |= EFISystemPartition;
                             partition->Index = drive->Partitions.size();
                             // why there is NUL (\0) between every char?????
                             char PartName[72];
                             memcpy(PartName, GPTPartition.Label, 72);
                             for (int i = 0; i < 72; i++)
                                 if (PartName[i] == '\0')
                                     PartName[i] = ' ';
                             PartName[71] = '\0';
                             trace("GPT partition \"%s\" found with %lld sectors", PartName, partition->Sectors);
                             drive->Partitions.push_back(partition);
                             char *PartitionName = new char[64];
                             sprintf(PartitionName, "sd%ldp%ld", drives.size() - 1, partition->Index);
                             /*
                             ----> Add to devfs the disk
                             */
                             delete[] PartitionName;
                         }
                     }
                 }
                 trace("%d GPT partitions found.", drive->Partitions.size());
             }
             else if (drive->Table.MBR.Signature[0] == MBR_MAGIC0 && drive->Table.MBR.Signature[1] == MBR_MAGIC1)
             {
                 drive->Style = MBR;
                 for (size_t p = 0; p < 4; p++)
                     if (drive->Table.MBR.Partitions[p].LBAFirst != 0)
                     {
                         Partition *partition = new Partition;
                         partition->StartLBA = drive->Table.MBR.Partitions[p].LBAFirst;
                         partition->EndLBA = drive->Table.MBR.Partitions[p].LBAFirst + drive->Table.MBR.Partitions[p].Sectors;
                         partition->Sectors = drive->Table.MBR.Partitions[p].Sectors;
                         partition->Port = ItrPort;
                         partition->Flags = Present;
                         partition->Style = MBR;
                         partition->Index = drive->Partitions.size();
                         trace("Partition \"%#llx\" found with %lld sectors.", drive->Table.MBR.UniqueID, partition->Sectors);
                         drive->Partitions.push_back(partition);
                         char *PartitionName = new char[64];
                         sprintf(PartitionName, "sd%ldp%ld", drives.size() - 1, partition->Index);
                         /*
                         ----> Add to devfs the disk
                         */
                         delete[] PartitionName;
                     }
                 trace("%d MBR partitions found.", drive->Partitions.size());
             }
             else
                 warn("No partition table found on port %d!", ItrPort);
             drives.push_back(drive);
         }
         KernelAllocator.FreePages((void *)callback, TO_PAGES(sizeof(KernelCallback)));
     }
References Disk::GUIDPartitionTablePartition::Attributes, AvailablePorts, BytesPerSector, debug, KernelCallback::DiskCallback, DriverManager, drives, Disk::EFISystemPartition, Disk::GUIDPartitionTablePartition::EndLBA, Disk::Partition::EndLBA, Entries, Disk::GUIDPartitionTable::EntrySize, FetchReason, Disk::Partition::Flags, Disk::GPT, Disk::PartitionTable::GPT, GPT_MAGIC, Disk::Partition::Index, Driver::Driver::IOCB(), KernelAllocator, Disk::GUIDPartitionTablePartition::Label, Disk::Partition::Label, Disk::MasterBootRecordPartition::LBAFirst, Disk::MBR, Disk::PartitionTable::MBR, MBR_MAGIC0, MBR_MAGIC1, Disk::Drive::MechanicalDisk, memcpy, memset, Disk::Drive::Name, Disk::GUIDPartitionTable::PartCount, Disk::MasterBootRecord::Partitions, Disk::Drive::Partitions, Disk::Partition::Port, Disk::Present, KernelCallback::Reason, ReceiveReason, Sectors, Disk::MasterBootRecordPartition::Sectors, Disk::Partition::Sectors, Disk::MasterBootRecord::Signature, Disk::GUIDPartitionTable::Signature, sprintf(), Disk::GUIDPartitionTablePartition::StartLBA, Disk::Partition::StartLBA, Disk::Partition::Style, Disk::Drive::Style, Disk::Drive::Table, TO_PAGES, trace, Disk::GUIDPartitionTablePartition::TypeHigh, Disk::GUIDPartitionTablePartition::TypeLow, Disk::MasterBootRecord::UniqueID, and warn.
Referenced by KernelMainThread().
Field Documentation
AvailablePorts
unsigned char Disk::Manager::AvailablePorts = 0 private
Definition at line 153 of file disk.hpp.
Referenced by FetchDisks().
BytesPerSector
int Disk::Manager::BytesPerSector = 0 private
Definition at line 154 of file disk.hpp.
Referenced by FetchDisks().
drives
Vector<Drive *> Disk::Manager::drives private
Definition at line 156 of file disk.hpp.
Referenced by FetchDisks().
The documentation for this class was generated from the following files:
Kernel/include/disk.hpp
Kernel/Core/Disk.cpp