Fennix Userspace: Userspace/apps/base/busybox/scripts/kconfig/menu.c File Reference
menu.c File Reference
#include <stdlib.h>
#include <string.h>
#include "lkc.h"
Macros
#define LKC_DIRECT_LINK
Functions
static void menu_warn (struct menu *menu, const char *fmt,...)
static void prop_warn (struct property *prop, const char *fmt,...)
void menu_init (void)
void menu_add_entry (struct symbol *sym)
void menu_end_entry (void)
struct menu * menu_add_menu (void)
void menu_end_menu (void)
struct expr * menu_check_dep (struct expr *e)
void menu_add_dep (struct expr *dep)
void menu_set_type (int type)
struct property * menu_add_prop (enum prop_type type, char *prompt, struct expr *expr, struct expr *dep)
struct property * menu_add_prompt (enum prop_type type, char *prompt, struct expr *dep)
void menu_add_expr (enum prop_type type, struct expr *expr, struct expr *dep)
void menu_add_symbol (enum prop_type type, struct symbol *sym, struct expr *dep)
static int menu_range_valid_sym (struct symbol *sym, struct symbol *sym2)
void sym_check_prop (struct symbol *sym)
void menu_finalize (struct menu *parent)
bool menu_is_visible (struct menu *menu)
const char * menu_get_prompt (struct menu *menu)
struct menu * menu_get_root_menu (struct menu *menu)
struct menu * menu_get_parent_menu (struct menu *menu)
Variables
struct menu rootmenu
static struct menu ** last_entry_ptr
struct file * file_list
struct file * current_file
Macro Definition Documentation
LKC_DIRECT_LINK
#define LKC_DIRECT_LINK
Definition at line 9 of file menu.c.
Function Documentation
menu_add_dep()
void menu_add_dep (struct expr * dep)
Definition at line 102 of file menu.c.
 {
     current_entry->dep = expr_alloc_and(current_entry->dep, menu_check_dep(dep));
 }
References expr_alloc_and(), and menu_check_dep().
menu_add_entry()
void menu_add_entry (struct symbol * sym)
Definition at line 44 of file menu.c.
 {
     struct menu *menu;
     menu = malloc(sizeof(*menu));
     memset(menu, 0, sizeof(*menu));
     menu->sym = sym;
     menu->parent = current_menu;
     menu->file = current_file;
     menu->lineno = zconf_lineno();
     *last_entry_ptr = menu;
     last_entry_ptr = &menu->next;
     current_entry = menu;
 }
References current_file, current_menu, menu::file, last_entry_ptr, menu::lineno, malloc, memset(), menu::next, menu::parent, menu::sym, and zconf_lineno().
menu_add_expr()
void menu_add_expr (enum prop_type type, struct expr * expr, struct expr * dep)
Definition at line 145 of file menu.c.
 {
     menu_add_prop(type, NULL, expr, dep);
 }
References menu_add_prop(), NULL, and type.
menu_add_menu()
struct menu* menu_add_menu (void)
Definition at line 64 of file menu.c.
 {
     menu_end_entry();
     last_entry_ptr = &current_entry->list;
     return current_menu = current_entry;
 }
References current_menu, last_entry_ptr, menu::list, and menu_end_entry().
menu_add_prompt()
struct property* menu_add_prompt (enum prop_type type, char * prompt, struct expr * dep)
Definition at line 140 of file menu.c.
 {
     return menu_add_prop(type, prompt, NULL, dep);
 }
References menu_add_prop(), NULL, prompt, and type.
menu_add_prop()
struct property* menu_add_prop (enum prop_type type, char * prompt, struct expr * expr, struct expr * dep)
Definition at line 122 of file menu.c.
 {
     struct property *prop = prop_alloc(type, current_entry->sym);
     prop->menu = current_entry;
     prop->text = prompt;
     prop->expr = expr;
     prop->visible.expr = menu_check_dep(dep);
     if (prompt) {
         if (current_entry->prompt)
             menu_warn(current_entry, "prompt redefined\n");
         current_entry->prompt = prop;
     }
     return prop;
 }
References expr(), expr_value::expr, property::expr, property::menu, menu_check_dep(), menu_warn(), prompt, prop_alloc(), property::text, type, and property::visible.
Referenced by menu_add_expr(), menu_add_prompt(), and menu_add_symbol().
menu_add_symbol()
void menu_add_symbol (enum prop_type type, struct symbol * sym, struct expr * dep)
Definition at line 150 of file menu.c.
 {
     menu_add_prop(type, NULL, expr_alloc_symbol(sym), dep);
 }
References expr_alloc_symbol(), menu_add_prop(), NULL, property::sym, and type.
Referenced by menu_finalize().
menu_check_dep()
struct expr* menu_check_dep (struct expr * e)
Definition at line 77 of file menu.c.
 {
     if (!e)
         return e;
     switch (e->type) {
     case E_NOT:
         e->left.expr = menu_check_dep(e->left.expr);
         break;
     case E_OR:
     case E_AND:
         e->left.expr = menu_check_dep(e->left.expr);
         e->right.expr = menu_check_dep(e->right.expr);
         break;
     case E_SYMBOL:
         /* change 'm' into 'm' && MODULES */
         if (e->left.sym == &symbol_mod)
             return expr_alloc_and(e, expr_alloc_symbol(modules_sym));
         break;
     default:
         break;
     }
     return e;
 }
References E_AND, E_NOT, E_OR, E_SYMBOL, expr_data::expr, expr_alloc_and(), expr_alloc_symbol(), modules_sym, expr::right, symbol_mod, and expr::type.
Referenced by menu_add_dep(), and menu_add_prop().
menu_end_entry()
void menu_end_entry (void)
Definition at line 60 of file menu.c.
 {
 }
Referenced by menu_add_menu().
menu_end_menu()
void menu_end_menu (void)
Definition at line 71 of file menu.c.
 {
     last_entry_ptr = &current_menu->next;
     current_menu = current_menu->parent;
 }
References current_menu, last_entry_ptr, menu::next, and menu::parent.
menu_finalize()
void menu_finalize (struct menu * parent)
Definition at line 205 of file menu.c.
 {
     struct menu *menu, *last_menu;
     struct symbol *sym;
     struct property *prop;
     struct expr *parentdep, *basedep, *dep, *dep2, **ep;
     sym = parent->sym;
     if (parent->list) {
         if (sym && sym_is_choice(sym)) {
             /* find the first choice value and find out choice type */
             for (menu = parent->list; menu; menu = menu->next) {
                 if (menu->sym) {
                     current_entry = parent;
                     menu_set_type(menu->sym->type);
                     current_entry = menu;
                     menu_set_type(sym->type);
                     break;
                 }
             }
             parentdep = expr_alloc_symbol(sym);
         } else if (parent->prompt)
             parentdep = parent->prompt->visible.expr;
         else
             parentdep = parent->dep;
         for (menu = parent->list; menu; menu = menu->next) {
             basedep = expr_transform(menu->dep);
             basedep = expr_alloc_and(expr_copy(parentdep), basedep);
             basedep = expr_eliminate_dups(basedep);
             menu->dep = basedep;
             if (menu->sym)
                 prop = menu->sym->prop;
             else
                 prop = menu->prompt;
             for (; prop; prop = prop->next) {
                 if (prop->menu != menu)
                     continue;
                 dep = expr_transform(prop->visible.expr);
                 dep = expr_alloc_and(expr_copy(basedep), dep);
                 dep = expr_eliminate_dups(dep);
                 if (menu->sym && menu->sym->type != S_TRISTATE)
                     dep = expr_trans_bool(dep);
                 prop->visible.expr = dep;
                 if (prop->type == P_SELECT) {
                     struct symbol *es = prop_get_symbol(prop);
                     es->rev_dep.expr = expr_alloc_or(es->rev_dep.expr,
                             expr_alloc_and(expr_alloc_symbol(menu->sym), expr_copy(dep)));
                 }
             }
         }
         for (menu = parent->list; menu; menu = menu->next)
             menu_finalize(menu);
     } else if (sym) {
         basedep = parent->prompt ? parent->prompt->visible.expr : NULL;
         basedep = expr_trans_compare(basedep, E_UNEQUAL, &symbol_no);
         basedep = expr_eliminate_dups(expr_transform(basedep));
         last_menu = NULL;
         for (menu = parent->next; menu; menu = menu->next) {
             dep = menu->prompt ? menu->prompt->visible.expr : menu->dep;
             if (!expr_contains_symbol(dep, sym))
                 break;
             if (expr_depends_symbol(dep, sym))
                 goto next;
             dep = expr_trans_compare(dep, E_UNEQUAL, &symbol_no);
             dep = expr_eliminate_dups(expr_transform(dep));
             dep2 = expr_copy(basedep);
             expr_eliminate_eq(&dep, &dep2);
             expr_free(dep);
             if (!expr_is_yes(dep2)) {
                 expr_free(dep2);
                 break;
             }
             expr_free(dep2);
         next:
             menu_finalize(menu);
             menu->parent = parent;
             last_menu = menu;
         }
         if (last_menu) {
             parent->list = parent->next;
             parent->next = last_menu->next;
             last_menu->next = NULL;
         }
     }
     for (menu = parent->list; menu; menu = menu->next) {
         if (sym && sym_is_choice(sym) && menu->sym) {
             menu->sym->flags |= SYMBOL_CHOICEVAL;
             if (!menu->prompt)
                 menu_warn(menu, "choice value must have a prompt");
             for (prop = menu->sym->prop; prop; prop = prop->next) {
                 if (prop->type == P_PROMPT && prop->menu != menu) {
                     prop_warn(prop, "choice values "
                         "currently only support a "
                         "single prompt");
                 }
                 if (prop->type == P_DEFAULT)
                     prop_warn(prop, "defaults for choice "
                         "values not supported");
             }
             current_entry = menu;
             menu_set_type(sym->type);
             menu_add_symbol(P_CHOICE, sym, NULL);
             prop = sym_get_choice_prop(sym);
             for (ep = &prop->expr; *ep; ep = &(*ep)->left.expr)
                 ;
             *ep = expr_alloc_one(E_CHOICE, NULL);
             (*ep)->right.sym = menu->sym;
         }
         if (menu->list && (!menu->prompt || !menu->prompt->text)) {
             for (last_menu = menu->list; ; last_menu = last_menu->next) {
                 last_menu->parent = parent;
                 if (!last_menu->next)
                     break;
             }
             last_menu->next = menu->next;
             menu->next = menu->list;
             menu->list = NULL;
         }
     }
     if (sym && !(sym->flags & SYMBOL_WARNED)) {
         if (sym->type == S_UNKNOWN)
             menu_warn(parent, "config symbol defined "
                 "without type\n");
         if (sym_is_choice(sym) && !parent->prompt)
             menu_warn(parent, "choice must have a prompt\n");
         /* Check properties connected to this symbol */
         sym_check_prop(sym);
         sym->flags |= SYMBOL_WARNED;
     }
     if (sym && !sym_is_optional(sym) && parent->prompt) {
         sym->rev_dep.expr = expr_alloc_or(sym->rev_dep.expr,
                 expr_alloc_and(parent->prompt->visible.expr,
                     expr_alloc_symbol(&symbol_mod)));
     }
 }
References symbol::dep, menu::dep, symbol::dep2, E_CHOICE, E_UNEQUAL, expr_value::expr, property::expr, expr_alloc_and(), expr_alloc_one(), expr_alloc_or(), expr_alloc_symbol(), expr_contains_symbol(), expr_copy(), expr_depends_symbol(), expr_eliminate_dups(), expr_eliminate_eq(), expr_free(), expr_is_yes(), expr_trans_bool(), expr_trans_compare(), expr_transform(), symbol::flags, menu::list, property::menu, menu_add_symbol(), menu_finalize(), menu_set_type(), menu_warn(), property::next, menu::next, next, NULL, P_CHOICE, P_DEFAULT, P_PROMPT, P_SELECT, parent, menu::parent, menu::prompt, symbol::prop, prop_get_symbol(), prop_warn(), symbol::rev_dep, S_TRISTATE, S_UNKNOWN, menu::sym, sym_check_prop(), sym_get_choice_prop(), sym_is_choice(), sym_is_optional(), SYMBOL_CHOICEVAL, symbol_mod, symbol_no, SYMBOL_WARNED, property::text, symbol::type, property::type, and property::visible.
Referenced by menu_finalize().
menu_get_parent_menu()
struct menu* menu_get_parent_menu (struct menu * menu)
Definition at line 386 of file menu.c.
 {
     enum prop_type type;
     for (; menu != &rootmenu; menu = menu->parent) {
         type = menu->prompt ? menu->prompt->type : 0;
         if (type == P_MENU)
             break;
     }
     return menu;
 }
References P_MENU, menu::parent, menu::prompt, rootmenu, type, and property::type.
Referenced by check_conf(), and ConfigList::setParentMenu().
menu_get_prompt()
const char* menu_get_prompt (struct menu * menu)
Definition at line 372 of file menu.c.
 {
     if (menu->prompt)
         return _(menu->prompt->text);
     else if (menu->sym)
         return _(menu->sym->name);
     return NULL;
 }
References _, symbol::name, NULL, menu::prompt, menu::sym, and property::text.
Referenced by build_conf(), conf(), conf_choice(), conf_string(), conf_write(), display_tree(), fill_row(), get_prompt_str(), menu_build_message_list(), show_help(), text_insert_help(), update_tree(), and ConfigItem::updateMenu().
menu_get_root_menu()
struct menu* menu_get_root_menu (struct menu * menu)
Definition at line 381 of file menu.c.
 {
     return &rootmenu;
 }
References rootmenu.
Referenced by main().
menu_init()
void menu_init (void)
Definition at line 38 of file menu.c.
 {
     current_entry = current_menu = &rootmenu;
     last_entry_ptr = &rootmenu.list;
 }
References current_menu, last_entry_ptr, menu::list, and rootmenu.
menu_is_visible()
bool menu_is_visible (struct menu * menu)
Definition at line 346 of file menu.c.
 {
     struct menu *child;
     struct symbol *sym;
     tristate visible;
     if (!menu->prompt)
         return false;
     sym = menu->sym;
     if (sym) {
         sym_calc_value(sym);
         visible = menu->prompt->visible.tri;
     } else
         visible = menu->prompt->visible.tri = expr_calc_value(menu->prompt->visible.expr);
     if (visible != no)
         return true;
     if (!sym || sym_get_tristate_value(menu->sym) == no)
         return false;
     for (child = menu->list; child; child = child->next)
         if (menu_is_visible(child))
             return true;
     return false;
 }
References child(), expr_value::expr, expr_calc_value(), menu::list, child::next, no, menu::prompt, menu::sym, sym_calc_value(), sym_get_tristate_value(), expr_value::tri, visible(), and property::visible.
Referenced by build_conf(), check_conf(), conf(), conf_choice(), conf_write(), display_tree(), fill_row(), update_tree(), and ConfigList::updateMenuList().
menu_range_valid_sym()
static int menu_range_valid_sym (struct symbol * sym, struct symbol * sym2) static
Definition at line 155 of file menu.c.
 {
     return sym2->type == S_INT || sym2->type == S_HEX ||
            (sym2->type == S_UNKNOWN && sym_string_valid(sym, sym2->name));
 }
References symbol::name, S_HEX, S_INT, S_UNKNOWN, property::sym, sym_string_valid(), and symbol::type.
Referenced by sym_check_prop().
menu_set_type()
void menu_set_type (int type)
Definition at line 107 of file menu.c.
 {
     struct symbol *sym = current_entry->sym;
     if (sym->type == type)
         return;
     if (sym->type == S_UNKNOWN) {
         sym->type = type;
         return;
     }
     menu_warn(current_entry, "type of '%s' redefined from '%s' to '%s'\n",
         sym->name ? sym->name : "<choice>",
         sym_type_name(sym->type), sym_type_name(type));
 }
References menu_warn(), symbol::name, S_UNKNOWN, sym_type_name(), type, and symbol::type.
Referenced by menu_finalize().
menu_warn()
static void menu_warn (struct menu * menu, const char * fmt, ...) static
Definition at line 18 of file menu.c.
 {
     va_list ap;
     va_start(ap, fmt);
     fprintf(stderr, "%s:%d:warning: ", menu->file->name, menu->lineno);
     vfprintf(stderr, fmt, ap);
     fprintf(stderr, "\n");
     va_end(ap);
 }
References ap, menu::file, fprintf(), menu::lineno, file::name, stderr, va_end, va_start, and vfprintf().
Referenced by menu_add_prop(), menu_finalize(), and menu_set_type().
prop_warn()
static void prop_warn (struct property * prop, const char * fmt, ...) static
Definition at line 28 of file menu.c.
 {
     va_list ap;
     va_start(ap, fmt);
     fprintf(stderr, "%s:%d:warning: ", prop->file->name, prop->lineno);
     vfprintf(stderr, fmt, ap);
     fprintf(stderr, "\n");
     va_end(ap);
 }
References ap, property::file, fprintf(), property::lineno, file::name, stderr, va_end, va_start, and vfprintf().
Referenced by menu_finalize(), and sym_check_prop().
sym_check_prop()
void sym_check_prop (struct symbol * sym)
Definition at line 161 of file menu.c.
 {
     struct property *prop;
     struct symbol *sym2;
     for (prop = sym->prop; prop; prop = prop->next) {
         switch (prop->type) {
         case P_DEFAULT:
             if ((sym->type == S_STRING || sym->type == S_INT || sym->type == S_HEX) &&
                 prop->expr->type != E_SYMBOL)
                 prop_warn(prop,
                     "default for config symbol '%'"
                     " must be a single symbol", sym->name);
             break;
         case P_SELECT:
             sym2 = prop_get_symbol(prop);
             if (sym->type != S_BOOLEAN && sym->type != S_TRISTATE)
                 prop_warn(prop,
                     "config symbol '%s' uses select, but is "
                     "not boolean or tristate", sym->name);
             else if (sym2->type == S_UNKNOWN)
                 prop_warn(prop,
                     "'select' used by config symbol '%s' "
                     "refer to undefined symbol '%s'",
                     sym->name, sym2->name);
             else if (sym2->type != S_BOOLEAN && sym2->type != S_TRISTATE)
                 prop_warn(prop,
                     "'%s' has wrong type. 'select' only "
                     "accept arguments of boolean and "
                     "tristate type", sym2->name);
             break;
         case P_RANGE:
             if (sym->type != S_INT && sym->type != S_HEX)
                 prop_warn(prop, "range is only allowed "
                                 "for int or hex symbols");
             if (!menu_range_valid_sym(sym, prop->expr->left.sym) ||
                 !menu_range_valid_sym(sym, prop->expr->right.sym))
                 prop_warn(prop, "range is invalid");
             break;
         default:
             ;
         }
     }
 }
References E_SYMBOL, property::expr, menu_range_valid_sym(), symbol::name, property::next, P_DEFAULT, P_RANGE, P_SELECT, symbol::prop, prop_get_symbol(), prop_warn(), expr::right, S_BOOLEAN, S_HEX, S_INT, S_STRING, S_TRISTATE, S_UNKNOWN, expr_data::sym, expr::type, symbol::type, and property::type.
Referenced by menu_finalize().
Variable Documentation
current_file
struct file* current_file
Definition at line 16 of file menu.c.
Referenced by menu_add_entry().
file_list
struct file* file_list
Definition at line 15 of file menu.c.
Referenced by create_list(), file_lookup(), and file_write_dep().
last_entry_ptr
struct menu** last_entry_ptr static
Definition at line 13 of file menu.c.
Referenced by menu_add_entry(), menu_add_menu(), menu_end_menu(), and menu_init().
rootmenu
struct menu rootmenu
Definition at line 1 of file menu.c.
Referenced by change_sym_value(), conf(), conf_write(), display_list(), display_tree(), get_prompt_str(), ConfigMainWindow::goBack(), load_filename(), main(), menu_get_parent_menu(), menu_get_root_menu(), menu_init(), on_back_clicked(), on_full_clicked(), on_show_all_options1_activate(), on_show_debug_info1_activate(), on_single_clicked(), renderer_edited(), ConfigList::setParentMenu(), ConfigMainWindow::showFullView(), ConfigMainWindow::showSingleView(), ConfigMainWindow::showSplitView(), toggle_sym_value(), update_tree(), and ConfigList::updateList().