Fennix Userspace: Userspace/musl/src/math/j0.c File Reference
j0.c File Reference
#include "libm.h"
Functions
static double pzero (double)
static double qzero (double)
static double common (uint32_t ix, double x, int y0)
double j0 (double x)
double y0 (double x)
Variables
static const double invsqrtpi = 5.64189583547756279280e-01
static const double tpi = 6.36619772367581382433e-01
static const double R02 = 1.56249999999999947958e-02
static const double R03 = -1.89979294238854721751e-04
static const double R04 = 1.82954049532700665670e-06
static const double R05 = -4.61832688532103189199e-09
static const double S01 = 1.56191029464890010492e-02
static const double S02 = 1.16926784663337450260e-04
static const double S03 = 5.13546550207318111446e-07
static const double S04 = 1.16614003333790000205e-09
static const double u00 = -7.38042951086872317523e-02
static const double u01 = 1.76666452509181115538e-01
static const double u02 = -1.38185671945596898896e-02
static const double u03 = 3.47453432093683650238e-04
static const double u04 = -3.81407053724364161125e-06
static const double u05 = 1.95590137035022920206e-08
static const double u06 = -3.98205194132103398453e-11
static const double v01 = 1.27304834834123699328e-02
static const double v02 = 7.60068627350353253702e-05
static const double v03 = 2.59150851840457805467e-07
static const double v04 = 4.41110311332675467403e-10
static const double pR8 [6]
static const double pS8 [5]
static const double pR5 [6]
static const double pS5 [5]
static const double pR3 [6]
static const double pS3 [5]
static const double pR2 [6]
static const double pS2 [5]
static const double qR8 [6]
static const double qS8 [6]
static const double qR5 [6]
static const double qS5 [6]
static const double qR3 [6]
static const double qS3 [6]
static const double qR2 [6]
static const double qS2 [6]
Function Documentation
common()
static double common (uint32_t ix, double x, int y0) static
Definition at line 66 of file j0.c.
 {
     double s,c,ss,cc,z;
     /*
      * j0(x) = sqrt(2/(pi*x))*(p0(x)*cos(x-pi/4)-q0(x)*sin(x-pi/4))
      * y0(x) = sqrt(2/(pi*x))*(p0(x)*sin(x-pi/4)+q0(x)*cos(x-pi/4))
      *
      * sin(x-pi/4) = (sin(x) - cos(x))/sqrt(2)
      * cos(x-pi/4) = (sin(x) + cos(x))/sqrt(2)
      * sin(x) +- cos(x) = -cos(2x)/(sin(x) -+ cos(x))
      */
     s = sin(x);
     c = cos(x);
     if (y0)
         c = -c;
     cc = s+c;
     /* avoid overflow in 2*x, big ulp error when x>=0x1p1023 */
     if (ix < 0x7fe00000) {
         ss = s-c;
         z = -cos(2*x);
         if (s*c < 0)
             cc = z/ss;
         else
             ss = z/cc;
         if (ix < 0x48000000) {
             if (y0)
                 ss = -ss;
             cc = pzero(x)*cc-qzero(x)*ss;
         }
     }
     return invsqrtpi*cc/sqrt(x);
 }
References c, cos, invsqrtpi, pzero(), qzero(), s, sin, sqrt, x, and y0().
Referenced by __convert_scm_timestamps(), j0(), map_block(), and y0().
j0()
double j0 (double x)
Definition at line 111 of file j0.c.
 {
     double z,r,s;
     uint32_t ix;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     /* j0(+-inf)=0, j0(nan)=nan */
     if (ix >= 0x7ff00000)
         return 1/(x*x);
     x = fabs(x);
     if (ix >= 0x40000000) {  /* |x| >= 2 */
         /* large ulp error near zeros: 2.4, 5.52, 8.6537,.. */
         return common(ix,x,0);
     }
     /* 1 - x*x/4 + x*x*R(x^2)/S(x^2) */
     if (ix >= 0x3f200000) {  /* |x| >= 2**-13 */
         /* up to 4ulp error close to 2 */
         z = x*x;
         r = z*(R02+z*(R03+z*(R04+z*R05)));
         s = 1+z*(S01+z*(S02+z*(S03+z*S04)));
         return (1+x/2)*(1-x/2) + z*(r/s);
     }
     /* 1 - x*x/4 */
     /* prevent underflow */
     /* inexact should be raised when x!=0, this is not done correctly */
     if (ix >= 0x38000000)  /* |x| >= 2**-127 */
         x = 0.25*x*x;
     return 1 - x;
 }
References common(), fabs, GET_HIGH_WORD, R02, R03, R04, R05, s, S01, S02, S03, S04, and x.
Referenced by jn(), and y0().
pzero()
static double pzero (double x) static
Definition at line 263 of file j0.c.
 {
     const double *p,*q;
     double_t z,r,s;
     uint32_t ix;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     if      (ix >= 0x40200000){p = pR8; q = pS8;}
     else if (ix >= 0x40122E8B){p = pR5; q = pS5;}
     else if (ix >= 0x4006DB6D){p = pR3; q = pS3;}
     else /*ix >= 0x40000000*/ {p = pR2; q = pS2;}
     z = 1.0/(x*x);
     r = p[0]+z*(p[1]+z*(p[2]+z*(p[3]+z*(p[4]+z*p[5]))));
     s = 1.0+z*(q[0]+z*(q[1]+z*(q[2]+z*(q[3]+z*q[4]))));
     return 1.0 + r/s;
 }
References GET_HIGH_WORD, p, pR2, pR3, pR5, pR8, pS2, pS3, pS5, pS8, s, and x.
Referenced by common().
qzero()
static double qzero (double x)
Definition at line 359 of file j0.c.
 {
     const double *p,*q;
     double_t s,r,z;
     uint32_t ix;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     if      (ix >= 0x40200000){p = qR8; q = qS8;}
     else if (ix >= 0x40122E8B){p = qR5; q = qS5;}
     else if (ix >= 0x4006DB6D){p = qR3; q = qS3;}
     else /*ix >= 0x40000000*/ {p = qR2; q = qS2;}
     z = 1.0/(x*x);
     r = p[0]+z*(p[1]+z*(p[2]+z*(p[3]+z*(p[4]+z*p[5]))));
     s = 1.0+z*(q[0]+z*(q[1]+z*(q[2]+z*(q[3]+z*(q[4]+z*q[5])))));
     return (-.125 + r/s)/x;
 }
References GET_HIGH_WORD, p, qR2, qR3, qR5, qR8, qS2, qS3, qS5, qS8, s, and x.
Referenced by common().
y0()
double y0 (double x)
Definition at line 159 of file j0.c.
 {
     double z,u,v;
     uint32_t ix,lx;
     EXTRACT_WORDS(ix, lx, x);
     /* y0(nan)=nan, y0(<0)=nan, y0(0)=-inf, y0(inf)=0 */
     if ((ix<<1 | lx) == 0)
         return -1/0.0;
     if (ix>>31)
         return 0/0.0;
     if (ix >= 0x7ff00000)
         return 1/x;
     if (ix >= 0x40000000) {  /* x >= 2 */
         /* large ulp errors near zeros: 3.958, 7.086,.. */
         return common(ix,x,1);
     }
     /* U(x^2)/V(x^2) + (2/pi)*j0(x)*log(x) */
     if (ix >= 0x3e400000) {  /* x >= 2**-27 */
         /* large ulp error near the first zero, x ~= 0.89 */
         z = x*x;
         u = u00+z*(u01+z*(u02+z*(u03+z*(u04+z*(u05+z*u06)))));
         v = 1.0+z*(v01+z*(v02+z*(v03+z*v04)));
         return u/v + tpi*(j0(x)*log(x));
     }
     return u00 + tpi*log(x);
 }
References common(), EXTRACT_WORDS, j0(), log, tpi, u00, u01, u02, u03, u04, u05, u06, v01, v02, v03, v04, and x.
Referenced by common(), log2_inline(), log2f(), logf(), and yn().
Variable Documentation
invsqrtpi
const double invsqrtpi = 5.64189583547756279280e-01 static
Definition at line 62 of file j0.c.
Referenced by common().
pR2
const double pR2[6] static
Initial value:
= {
 -8.87534333032526411254e-08,
 -7.03030995483624743247e-02,
 -1.45073846780952986357e+00,
 -7.63569613823527770791e+00,
 -1.11931668860356747786e+01,
 -3.23364579351335335033e+00,
}
Definition at line 247 of file j0.c.
Referenced by pzero().
pR3
const double pR3[6] static
Initial value:
= {
 -2.54704601771951915620e-09,
 -7.03119616381481654654e-02,
 -2.40903221549529611423e+00,
 -2.19659774734883086467e+01,
 -5.80791704701737572236e+01,
 -3.14479470594888503854e+01,
}
Definition at line 231 of file j0.c.
Referenced by pzero().
pR5
const double pR5[6] static
Initial value:
= {
 -1.14125464691894502584e-11,
 -7.03124940873599280078e-02,
 -4.15961064470587782438e+00,
 -6.76747652265167261021e+01,
 -3.31231299649172967747e+02,
 -3.46433388365604912451e+02,
}
Definition at line 215 of file j0.c.
Referenced by pzero().
pR8
const double pR8[6] static
Initial value:
= {
  0.00000000000000000000e+00,
 -7.03124999999900357484e-02,
 -8.08167041275349795626e+00,
 -2.57063105679704847262e+02,
 -2.48521641009428822144e+03,
 -5.25304380490729545272e+03,
}
Definition at line 199 of file j0.c.
Referenced by pzero().
pS2
const double pS2[5] static
Initial value:
= {
  2.22202997532088808441e+01,
  1.36206794218215208048e+02,
  2.70470278658083486789e+02,
  1.53875394208320329881e+02,
  1.46576176948256193810e+01,
}
Definition at line 255 of file j0.c.
Referenced by pzero().
pS3
const double pS3[5] static
Initial value:
= {
  3.58560338055209726349e+01,
  3.61513983050303863820e+02,
  1.19360783792111533330e+03,
  1.12799679856907414432e+03,
  1.73580930813335754692e+02,
}
Definition at line 239 of file j0.c.
Referenced by pzero().
pS5
const double pS5[5] static
Initial value:
= {
  6.07539382692300335975e+01,
  1.05125230595704579173e+03,
  5.97897094333855784498e+03,
  9.62544514357774460223e+03,
  2.40605815922939109441e+03,
}
Definition at line 223 of file j0.c.
Referenced by pzero().
pS8
const double pS8[5] static
Initial value:
= {
  1.16534364619668181717e+02,
  3.83374475364121826715e+03,
  4.05978572648472545552e+04,
  1.16752972564375915681e+05,
  4.76277284146730962675e+04,
}
Definition at line 207 of file j0.c.
Referenced by pzero().
qR2
const double qR2[6] static
Initial value:
= {
  1.50444444886983272379e-07,
  7.32234265963079278272e-02,
  1.99819174093815998816e+00,
  1.44956029347885735348e+01,
  3.16662317504781540833e+01,
  1.62527075710929267416e+01,
}
Definition at line 342 of file j0.c.
Referenced by qzero().
qR3
const double qR3[6] static
Initial value:
= {
  4.37741014089738620906e-09,
  7.32411180042911447163e-02,
  3.34423137516170720929e+00,
  4.26218440745412650017e+01,
  1.70808091340565596283e+02,
  1.66733948696651168575e+02,
}
Definition at line 325 of file j0.c.
Referenced by qzero().
qR5
const double qR5[6] static
Initial value:
= {
  1.84085963594515531381e-11,
  7.32421766612684765896e-02,
  5.83563508962056953777e+00,
  1.35111577286449829671e+02,
  1.02724376596164097464e+03,
  1.98997785864605384631e+03,
}
Definition at line 308 of file j0.c.
Referenced by qzero().
qR8
const double qR8[6] static
Initial value:
= {
  0.00000000000000000000e+00,
  7.32421874999935051953e-02,
  1.17682064682252693899e+01,
  5.57673380256401856059e+02,
  8.85919720756468632317e+03,
  3.70146267776887834771e+04,
}
Definition at line 291 of file j0.c.
Referenced by qzero().
qS2
const double qS2[6] static
Initial value:
= {
  3.03655848355219184498e+01,
  2.69348118608049844624e+02,
  8.44783757595320139444e+02,
  8.82935845112488550512e+02,
  2.12666388511798828631e+02,
 -5.31095493882666946917e+00,
}
Definition at line 350 of file j0.c.
Referenced by qzero().
qS3
const double qS3[6] static
Initial value:
= {
  4.87588729724587182091e+01,
  7.09689221056606015736e+02,
  3.70414822620111362994e+03,
  6.46042516752568917582e+03,
  2.51633368920368957333e+03,
 -1.49247451836156386662e+02,
}
Definition at line 333 of file j0.c.
Referenced by qzero().
qS5
const double qS5[6] static
Initial value:
= {
  8.27766102236537761883e+01,
  2.07781416421392987104e+03,
  1.88472887785718085070e+04,
  5.67511122894947329769e+04,
  3.59767538425114471465e+04,
 -5.35434275601944773371e+03,
}
Definition at line 316 of file j0.c.
Referenced by qzero().
qS8
const double qS8[6] static
Initial value:
= {
  1.63776026895689824414e+02,
  8.09834494656449805916e+03,
  1.42538291419120476348e+05,
  8.03309257119514397345e+05,
  8.40501579819060512818e+05,
 -3.43899293537866615225e+05,
}
Definition at line 299 of file j0.c.
Referenced by qzero().
R02
const double R02 = 1.56249999999999947958e-02 static
Definition at line 102 of file j0.c.
Referenced by j0().
R03
const double R03 = -1.89979294238854721751e-04 static
Definition at line 103 of file j0.c.
Referenced by j0().
R04
const double R04 = 1.82954049532700665670e-06 static
Definition at line 104 of file j0.c.
Referenced by j0().
R05
const double R05 = -4.61832688532103189199e-09 static
Definition at line 105 of file j0.c.
Referenced by j0().
S01
const double S01 = 1.56191029464890010492e-02 static
Definition at line 106 of file j0.c.
Referenced by j0().
S02
const double S02 = 1.16926784663337450260e-04 static
Definition at line 107 of file j0.c.
Referenced by j0().
S03
const double S03 = 5.13546550207318111446e-07 static
Definition at line 108 of file j0.c.
Referenced by j0().
S04
const double S04 = 1.16614003333790000205e-09 static
Definition at line 109 of file j0.c.
Referenced by j0().
tpi
const double tpi = 6.36619772367581382433e-01 static
Definition at line 63 of file j0.c.
Referenced by y0().
u00
const double u00 = -7.38042951086872317523e-02 static
Definition at line 147 of file j0.c.
Referenced by y0().
u01
const double u01 = 1.76666452509181115538e-01 static
Definition at line 148 of file j0.c.
Referenced by y0().
u02
const double u02 = -1.38185671945596898896e-02 static
Definition at line 149 of file j0.c.
Referenced by y0().
u03
const double u03 = 3.47453432093683650238e-04 static
Definition at line 150 of file j0.c.
Referenced by y0().
u04
const double u04 = -3.81407053724364161125e-06 static
Definition at line 151 of file j0.c.
Referenced by y0().
u05
const double u05 = 1.95590137035022920206e-08 static
Definition at line 152 of file j0.c.
Referenced by y0().
u06
const double u06 = -3.98205194132103398453e-11 static
Definition at line 153 of file j0.c.
Referenced by y0().
v01
const double v01 = 1.27304834834123699328e-02 static
Definition at line 154 of file j0.c.
Referenced by y0().
v02
const double v02 = 7.60068627350353253702e-05 static
Definition at line 155 of file j0.c.
Referenced by y0().
v03
const double v03 = 2.59150851840457805467e-07 static
Definition at line 156 of file j0.c.
Referenced by y0().
v04
const double v04 = 4.41110311332675467403e-10 static
Definition at line 157 of file j0.c.
Referenced by y0().