Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/unpack_ar_archive.c File Reference
unpack_ar_archive.c File Reference
#include "libbb.h"
#include "bb_archive.h"
#include "ar_.h"
Functions
void FAST_FUNC unpack_ar_archive (archive_handle_t *ar_archive)
Function Documentation
unpack_ar_archive()
void FAST_FUNC unpack_ar_archive (archive_handle_t * ar_archive)
Definition at line 9 of file unpack_ar_archive.c.
 {
     char magic[7];
     xread(ar_archive->src_fd, magic, AR_MAGIC_LEN);
     if (!is_prefixed_with(magic, AR_MAGIC)) {
         bb_simple_error_msg_and_die("invalid ar magic");
     }
     ar_archive->offset += AR_MAGIC_LEN;
     while (get_header_ar(ar_archive) == EXIT_SUCCESS)
         continue;
 }
References AR_MAGIC, AR_MAGIC_LEN, bb_simple_error_msg_and_die(), EXIT_SUCCESS, get_header_ar(), is_prefixed_with(), archive_handle_t::offset, archive_handle_t::src_fd, and xread().
Referenced by ar_main(), deb_extract_control_file_to_buffer(), dpkg_deb_main(), and unpack_package().