Fennix Kernel: Tasking::Scheduler::Custom Class Reference
Tasking::Scheduler::Custom Class Reference
#include <scheduler.hpp>
Public Member Functions
bool RemoveThread (TCB *tcb) final
bool RemoveProcess (PCB *pcb) final
PCB * GetProcessByID (TID ID) final
TCB * GetThreadByID (TID ID, PCB *Parent) final
std::vector< PCB * > & GetProcessList () final
void StartIdleProcess () final
void StartScheduler () final
void Yield () final
void PushProcess (PCB *pcb) final
void PopProcess (PCB *pcb) final
std::pair< PCB *, TCB * > GetIdle () final
void OneShot (int TimeSlice)
void UpdateUsage (TaskInfo *Info, TaskExecutionMode Mode, int Core)
bool FindNewProcess (void *CPUDataPointer)
bool GetNextAvailableThread (void *CPUDataPointer)
bool GetNextAvailableProcess (void *CPUDataPointer)
bool SchedulerSearchProcessThread (void *CPUDataPointer)
void UpdateProcessState ()
void WakeUpThreads ()
void CleanupTerminated ()
void Schedule (CPU::SchedulerFrame *Frame)
void OnInterruptReceived (CPU::SchedulerFrame *Frame) final
Custom (Task *ctx)
virtual ~Custom ()
Public Member Functions inherited from Tasking::Scheduler::Base
Base (Task *_ctx)
~Base ()
Public Member Functions inherited from Interrupts::Handler
virtual void OnInterruptReceived (CPU::TrapFrame *Frame)
Data Fields
std::vector< PCB * > ProcessList
PCB * IdleProcess = nullptr
TCB * IdleThread = nullptr
Data Fields inherited from Tasking::Scheduler::Base
Task * ctx = nullptr
std::atomic_size_t SchedulerTicks = 0
std::atomic_size_t LastTaskTicks = 0
std::atomic_int LastCore = 0
std::atomic_bool StopScheduler = false
std::atomic_bool SchedulerUpdateTrapFrame = false
Private Member Functions
NewLock (SchedulerLock)
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 107 of file scheduler.hpp.
Constructor & Destructor Documentation
Custom()
Tasking::Scheduler::Custom::Custom (Task * ctx)
Definition at line 732 of file custom.cpp.
                             : Base(ctx), Interrupts::Handler(16) /* IRQ16 */
     {
 #if defined(a86)
         // Map the IRQ16 to the first CPU.
         ((APIC::APIC *)Interrupts::apic[0])->RedirectIRQ(0, CPU::x86::IRQ16 - CPU::x86::IRQ0, 1);
 #endif
     }
References CPU::x86::IRQ0, and CPU::x86::IRQ16.
~Custom()
Tasking::Scheduler::Custom::~Custom () virtual
Definition at line 740 of file custom.cpp.
     {
         foreach (PCB *Process in ProcessList)
         {
             foreach (TCB *Thread in Process->Threads)
             {
                 if (Thread == GetCurrentCPU()->CurrentThread.load())
                     continue;
                 ctx->KillThread(Thread, KILL_SCHEDULER_DESTRUCTION);
             }
             if (Process == GetCurrentCPU()->CurrentProcess.load())
                 continue;
             ctx->KillProcess(Process, KILL_SCHEDULER_DESTRUCTION);
         }
         debug("Waiting for processes to terminate");
         uint64_t timeout = TimeManager->CalculateTarget(20, Time::Units::Seconds);
         while (this->GetProcessList().size() > 0)
         {
             trace("Waiting for %d processes to terminate", this->GetProcessList().size());
             int NotTerminated = 0;
             foreach (PCB *Process in this->GetProcessList())
             {
                 trace("Process %s(%d) is still running (or waiting to be removed state %#lx)",
                       Process->Name, Process->ID, Process->State);
                 if (Process->State == TaskState::Terminated)
                 {
                     debug("Process %s(%d) terminated", Process->Name, Process->ID);
                     continue;
                 }
                 NotTerminated++;
             }
             if (NotTerminated == 1)
                 break;
             ctx->Sleep(1000);
             debug("Current working process is %s(%d)",
                   ctx->GetCurrentProcess()->Name,
                   ctx->GetCurrentProcess()->ID);
             if (TimeManager->GetCounter() > timeout)
             {
                 error("Timeout waiting for processes to terminate");
                 break;
             }
             this->OneShot(100);
         }
     }
References Time::time::CalculateTarget(), Tasking::Scheduler::Base::ctx, CurrentProcess, CurrentThread, debug, error, Time::time::GetCounter(), GetCurrentCPU(), Tasking::Task::GetCurrentProcess(), GetProcessList(), Tasking::PCB::ID, Tasking::KILL_SCHEDULER_DESTRUCTION, Tasking::Task::KillProcess(), Tasking::Task::KillThread(), Tasking::PCB::Name, OneShot(), ProcessList, Time::Seconds, size, Tasking::Task::Sleep(), Tasking::PCB::State, Tasking::Terminated, Tasking::PCB::Threads, TimeManager, and trace.
Member Function Documentation
CleanupTerminated()
nsa NIF void Tasking::Scheduler::Custom::CleanupTerminated ()
Definition at line 544 of file custom.cpp.
     {
         foreach (auto pcb in ProcessList)
         {
             if (pcb->State.load() == TaskState::Terminated)
             {
                 debug("Found terminated process %s(%d)", pcb->Name, pcb->ID);
                 delete pcb;
                 continue;
             }
             foreach (TCB *tcb in pcb->Threads)
             {
                 if (tcb->State == Terminated)
                     delete tcb;
             }
         }
     }
References debug, pcb, ProcessList, Tasking::TCB::State, and Tasking::Terminated.
Referenced by Schedule().
FindNewProcess()
nsa NIF bool Tasking::Scheduler::Custom::FindNewProcess (void * CPUDataPointer)
Definition at line 300 of file custom.cpp.
     {
         CPUData *CurrentCPU = (CPUData *)CPUDataPointer;
         fnp_schedbg("%d processes", ProcessList.size());
 #ifdef DEBUG_FIND_NEW_PROCESS
         foreach (auto process in ProcessList)
             fnp_schedbg("Process %d %s", process->ID,
                         process->Name);
 #endif
         foreach (auto process in ProcessList)
         {
             switch (process->State.load())
             {
             case TaskState::Ready:
                 fnp_schedbg("Ready process (%s)%d",
                             process->Name, process->ID);
                 break;
             default:
                 fnp_schedbg("Process \"%s\"(%d) status %d",
                             process->Name, process->ID,
                             process->State);
                 /* We don't actually remove the process. RemoveProcess
                    firstly checks if it's terminated, if not, it will
                    loop through Threads and call RemoveThread on
                    terminated threads. */
                 RemoveProcess(process);
                 continue;
             }
             foreach (auto thread in process->Threads)
             {
                 if (thread->State.load() != TaskState::Ready)
                     continue;
                 if (thread->Info.Affinity[CurrentCPU->ID] == false)
                     continue;
                 CurrentCPU->CurrentProcess = process;
                 CurrentCPU->CurrentThread = thread;
                 return true;
             }
         }
         fnp_schedbg("No process to run.");
         return false;
     }
References fnp_schedbg, ProcessList, Tasking::Ready, and RemoveProcess().
Referenced by Schedule().
GetIdle()
std::pair< PCB *, TCB * > Tasking::Scheduler::Custom::GetIdle () final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 264 of file custom.cpp.
     {
         return std::make_pair(IdleProcess, IdleThread);
     }
References IdleProcess, and IdleThread.
GetNextAvailableProcess()
nsa NIF bool Tasking::Scheduler::Custom::GetNextAvailableProcess (void * CPUDataPointer)
Definition at line 396 of file custom.cpp.
     {
         CPUData *CurrentCPU = (CPUData *)CPUDataPointer;
         bool Skip = true;
         foreach (auto process in ProcessList)
         {
             if (process == CurrentCPU->CurrentProcess.load())
             {
                 Skip = false;
                 gnap_schedbg("Found current process %#lx", process);
                 continue;
             }
             if (Skip)
             {
                 gnap_schedbg("Skipping process %#lx", process);
                 continue;
             }
             if (process->State.load() != TaskState::Ready)
             {
                 gnap_schedbg("Process %d is not ready", process->ID);
                 continue;
             }
             foreach (auto thread in process->Threads)
             {
                 if (thread->State.load() != TaskState::Ready)
                 {
                     gnap_schedbg("Thread %d is not ready", thread->ID);
                     continue;
                 }
                 if (thread->Info.Affinity[CurrentCPU->ID] == false)
                     continue;
                 CurrentCPU->CurrentProcess = process;
                 CurrentCPU->CurrentThread = thread;
                 gnap_schedbg("[cur proc+1 -> first thd] Scheduling thread %d %s->%d (Total Procs %d)",
                              thread->ID, thread->Name, process->Threads.size(), ProcessList.size());
                 return true;
             }
         }
         gnap_schedbg("No process to run.");
         return false;
     }
References gnap_schedbg, ProcessList, and Tasking::Ready.
Referenced by Schedule().
GetNextAvailableThread()
nsa NIF bool Tasking::Scheduler::Custom::GetNextAvailableThread (void * CPUDataPointer)
Definition at line 347 of file custom.cpp.
     {
         CPUData *CurrentCPU = (CPUData *)CPUDataPointer;
         size_t ThreadsSize = CurrentCPU->CurrentProcess->Threads.size();
         for (size_t i = 0; i < ThreadsSize; i++)
         {
             if (CurrentCPU->CurrentProcess->Threads[i] == CurrentCPU->CurrentThread.load())
             {
                 size_t TempIndex = i;
             RetryAnotherThread:
                 if (TempIndex + 1 >= ThreadsSize)
                     break;
                 TCB *nextThread = CurrentCPU->CurrentProcess->Threads[TempIndex + 1];
                 gnat_schedbg("\"%s\"(%d) and next thread is \"%s\"(%d)",
                              CurrentCPU->CurrentProcess->Threads[i]->Name,
                              CurrentCPU->CurrentProcess->Threads[i]->ID,
                              nextThread->Name, nextThread->ID);
                 if (nextThread->State.load() != TaskState::Ready)
                 {
                     gnat_schedbg("Thread %d is not ready", nextThread->ID);
                     TempIndex++;
                     goto RetryAnotherThread;
                 }
                 if (nextThread->Info.Affinity[CurrentCPU->ID] == false)
                     continue;
                 CurrentCPU->CurrentThread = nextThread;
                 gnat_schedbg("[thd 0 -> end] Scheduling thread %d parent of %s->%d Procs %d",
                              nextThread->ID, nextThread->Parent->Name,
                              ThreadsSize, ProcessList.size());
                 return true;
             }
 #ifdef DEBUG
             else
             {
                 gnat_schedbg("Thread %d is not the current one",
                              CurrentCPU->CurrentProcess->Threads[i]->ID);
             }
 #endif
         }
         return false;
     }
References Tasking::TaskInfo::Affinity, CPUData::CurrentProcess, CPUData::CurrentThread, gnat_schedbg, CPUData::ID, Tasking::TCB::ID, Tasking::TCB::Info, Tasking::TCB::Name, Tasking::PCB::Name, Tasking::TCB::Parent, ProcessList, Tasking::Ready, and Tasking::TCB::State.
Referenced by Schedule().
GetProcessByID()
PCB * Tasking::Scheduler::Custom::GetProcessByID (TID ID) final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 148 of file custom.cpp.
     {
         foreach (auto p in ProcessList)
         {
             if (p->ID == ID)
                 return p;
         }
         return nullptr;
     }
References ID, and ProcessList.
GetProcessList()
std::vector< PCB * > & Tasking::Scheduler::Custom::GetProcessList () final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 191 of file custom.cpp.
     {
         return ProcessList;
     }
References ProcessList.
Referenced by ~Custom().
GetThreadByID()
TCB * Tasking::Scheduler::Custom::GetThreadByID (TID ID, PCB * Parent) final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 158 of file custom.cpp.
     {
         if (unlikely(Parent == nullptr))
             return nullptr;
         foreach (auto t in Parent->Threads)
         {
             if (t->ID == ID)
                 return t;
         }
         return nullptr;
     }
References ID, and unlikely.
NewLock()
Tasking::Scheduler::Custom::NewLock (SchedulerLock) private
OneShot()
nsa void Tasking::Scheduler::Custom::OneShot (int TimeSlice)
Definition at line 271 of file custom.cpp.
     {
         if (TimeSlice == 0)
             TimeSlice = Tasking::TaskPriority::Normal;
 #ifdef DEBUG
         if (DebuggerIsAttached)
             TimeSlice += 10;
 #endif
 #if defined(a86)
         ((APIC::Timer *)Interrupts::apicTimer[GetCurrentCPU()->ID])->OneShot(CPU::x86::IRQ16, TimeSlice);
 #elif defined(aa64)
 #endif
     }
References DebuggerIsAttached, GetCurrentCPU(), CPUData::ID, CPU::x86::IRQ16, and Tasking::Normal.
Referenced by Schedule(), and ~Custom().
OnInterruptReceived()
nsa NIF void Tasking::Scheduler::Custom::OnInterruptReceived (CPU::SchedulerFrame * Frame) final virtual
Reimplemented from Interrupts::Handler.
Definition at line 726 of file custom.cpp.
     {
         SmartCriticalSection(SchedulerLock);
         this->Schedule(Frame);
     }
References Schedule().
PopProcess()
void Tasking::Scheduler::Custom::PopProcess (PCB * pcb) final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 250 of file custom.cpp.
     {
         auto it = std::find(this->ProcessList.begin(),
                             this->ProcessList.end(), pcb);
         if (it == this->ProcessList.end())
         {
             debug("Process %d not found in the list", pcb->ID);
             return;
         }
         this->ProcessList.erase(it);
     }
References debug, Tasking::PCB::ID, it, pcb, and ProcessList.
PushProcess()
void Tasking::Scheduler::Custom::PushProcess (PCB * pcb) final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 245 of file custom.cpp.
     {
         this->ProcessList.push_back(pcb);
     }
References ProcessList.
RemoveProcess()
bool Tasking::Scheduler::Custom::RemoveProcess (PCB * pcb) final virtual
Note
This function is NOT thread safe
Reimplemented from Tasking::Scheduler::Base.
Definition at line 131 of file custom.cpp.
     {
         if (Process->State == Terminated)
         {
             delete Process;
             return true;
         }
         foreach (TCB *Thread in Process->Threads)
         {
             if (Thread->State == Terminated)
                 RemoveThread(Thread);
         }
         return true;
     }
References RemoveThread(), Tasking::TCB::State, Tasking::PCB::State, and Tasking::Terminated.
Referenced by FindNewProcess().
RemoveThread()
bool Tasking::Scheduler::Custom::RemoveThread (TCB * tcb) final virtual
Remove a thread from the scheduler
Note
This function is NOT thread safe
This function does not check if the thread is valid nor if it has Terminated status
Reimplemented from Tasking::Scheduler::Base.
Definition at line 121 of file custom.cpp.
     {
         debug("Thread \"%s\"(%d) removed from process \"%s\"(%d)",
               Thread->Name, Thread->ID, Thread->Parent->Name,
               Thread->Parent->ID);
         delete Thread;
         return true;
     }
References debug, Tasking::TCB::ID, Tasking::PCB::ID, Tasking::TCB::Name, Tasking::PCB::Name, and Tasking::TCB::Parent.
Referenced by RemoveProcess().
Schedule()
nsa NIF void Tasking::Scheduler::Custom::Schedule (CPU::SchedulerFrame * Frame)
Definition at line 563 of file custom.cpp.
     {
         if (unlikely(StopScheduler))
         {
             warn("Scheduler stopped.");
             return;
         }
         bool ProcessNotChanged = false;
         uint64_t SchedTmpTicks = TimeManager->GetCounter();
         this->LastTaskTicks.store(size_t(SchedTmpTicks - this->SchedulerTicks.load()));
         CPUData *CurrentCPU = GetCurrentCPU();
         this->LastCore.store(CurrentCPU->ID);
         schedbg("Scheduler called on CPU %d.", CurrentCPU->ID);
         if (unlikely(!CurrentCPU->CurrentProcess.load() ||
                      !CurrentCPU->CurrentThread.load()))
         {
             schedbg("Invalid process or thread. Finding a new one.");
             ProcessNotChanged = true;
             if (this->FindNewProcess(CurrentCPU))
                 goto Success;
             else
                 goto Idle;
         }
         else
         {
             CurrentCPU->CurrentThread->Registers = *Frame;
             CPU::x64::fxsave(&CurrentCPU->CurrentThread->FPU);
 #ifdef a64
             CurrentCPU->CurrentThread->ShadowGSBase = CPU::x64::rdmsr(CPU::x64::MSR_SHADOW_GS_BASE);
             CurrentCPU->CurrentThread->GSBase = CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE);
             CurrentCPU->CurrentThread->FSBase = CPU::x64::rdmsr(CPU::x64::MSR_FS_BASE);
 #else
             CurrentCPU->CurrentThread->ShadowGSBase = uintptr_t(CPU::x32::rdmsr(CPU::x32::MSR_SHADOW_GS_BASE));
             CurrentCPU->CurrentThread->GSBase = uintptr_t(CPU::x32::rdmsr(CPU::x32::MSR_GS_BASE));
             CurrentCPU->CurrentThread->FSBase = uintptr_t(CPU::x32::rdmsr(CPU::x32::MSR_FS_BASE));
 #endif
             if (CurrentCPU->CurrentProcess->State.load() == TaskState::Running)
                 CurrentCPU->CurrentProcess->State.store(TaskState::Ready);
             if (CurrentCPU->CurrentThread->State.load() == TaskState::Running)
                 CurrentCPU->CurrentThread->State.store(TaskState::Ready);
             this->CleanupTerminated();
             schedbg("Passed CleanupTerminated");
             this->UpdateProcessState();
             schedbg("Passed UpdateProcessState");
             this->WakeUpThreads();
             schedbg("Passed WakeUpThreads");
             if (this->SchedulerUpdateTrapFrame)
             {
                 debug("Updating trap frame");
                 this->SchedulerUpdateTrapFrame = false;
                 CurrentCPU->CurrentProcess->State.store(TaskState::Running);
                 CurrentCPU->CurrentThread->State.store(TaskState::Running);
                 *Frame = CurrentCPU->CurrentThread->Registers;
                 this->SchedulerTicks.store(size_t(TimeManager->GetCounter() - SchedTmpTicks));
                 return;
             }
             if (this->GetNextAvailableThread(CurrentCPU))
             {
                 ProcessNotChanged = true;
                 goto Success;
             }
             schedbg("Passed GetNextAvailableThread");
             if (this->GetNextAvailableProcess(CurrentCPU))
             {
                 goto Success;
             }
             schedbg("Passed GetNextAvailableProcess");
             if (SchedulerSearchProcessThread(CurrentCPU))
             {
                 schedbg("Passed SchedulerSearchProcessThread");
                 goto Success;
             }
             else
             {
                 schedbg("SchedulerSearchProcessThread failed. Going idle.");
                 goto Idle;
             }
         }
         assert(!"Unwanted code execution");
     Idle:
         ProcessNotChanged = true;
         CurrentCPU->CurrentProcess = IdleProcess;
         CurrentCPU->CurrentThread = IdleThread;
     Success:
         schedbg("Process \"%s\"(%d) Thread \"%s\"(%d) is now running on CPU %d",
                 CurrentCPU->CurrentProcess->Name, CurrentCPU->CurrentProcess->ID,
                 CurrentCPU->CurrentThread->Name, CurrentCPU->CurrentThread->ID, CurrentCPU->ID);
         if (!ProcessNotChanged)
             UpdateUsage(&CurrentCPU->CurrentProcess->Info,
                         CurrentCPU->CurrentProcess->Security.ExecutionMode,
                         CurrentCPU->ID);
         UpdateUsage(&CurrentCPU->CurrentThread->Info,
                     CurrentCPU->CurrentThread->Security.ExecutionMode,
                     CurrentCPU->ID);
         CurrentCPU->CurrentProcess->State.store(TaskState::Running);
         CurrentCPU->CurrentThread->State.store(TaskState::Running);
         if (CurrentCPU->CurrentThread->Registers.cs != GDT_KERNEL_CODE)
             CurrentCPU->CurrentThread->Registers.ppt = (uint64_t)(void *)CurrentCPU->CurrentProcess->PageTable;
         else
             CurrentCPU->CurrentThread->Registers.ppt = (uint64_t)(void *)KernelPageTable;
         // if (!SchedulerUpdateTrapFrame) {} // TODO
         *Frame = CurrentCPU->CurrentThread->Registers;
 #ifdef a64
         GlobalDescriptorTable::SetKernelStack((void *)((uintptr_t)CurrentCPU->CurrentThread->Stack->GetStackTop()));
         CPU::x64::fxrstor(&CurrentCPU->CurrentThread->FPU);
         CPU::x64::wrmsr(CPU::x64::MSR_SHADOW_GS_BASE, CurrentCPU->CurrentThread->ShadowGSBase);
         CPU::x64::wrmsr(CPU::x64::MSR_GS_BASE, CurrentCPU->CurrentThread->GSBase);
         CPU::x64::wrmsr(CPU::x64::MSR_FS_BASE, CurrentCPU->CurrentThread->FSBase);
 #else
         GlobalDescriptorTable::SetKernelStack((void *)((uintptr_t)CurrentCPU->CurrentThread->Stack->GetStackTop()));
         CPU::x32::fxrstor(&CurrentCPU->CurrentThread->FPU);
         CPU::x32::wrmsr(CPU::x32::MSR_SHADOW_GS_BASE, CurrentCPU->CurrentThread->ShadowGSBase);
         CPU::x32::wrmsr(CPU::x32::MSR_GS_BASE, CurrentCPU->CurrentThread->GSBase);
         CPU::x32::wrmsr(CPU::x32::MSR_FS_BASE, CurrentCPU->CurrentThread->FSBase);
 #endif
         CurrentCPU->CurrentProcess->Signals.HandleSignal(Frame, CurrentCPU->CurrentThread.load());
         if (!ProcessNotChanged)
             (&CurrentCPU->CurrentProcess->Info)->LastUpdateTime = TimeManager->GetCounter();
         (&CurrentCPU->CurrentThread->Info)->LastUpdateTime = TimeManager->GetCounter();
         this->OneShot(CurrentCPU->CurrentThread->Info.Priority);
         if (CurrentCPU->CurrentThread->Security.IsDebugEnabled &&
             CurrentCPU->CurrentThread->Security.IsKernelDebugEnabled)
         {
 #ifdef a64
             trace("%s[%ld]: RIP=%#lx  RBP=%#lx  RSP=%#lx",
                   CurrentCPU->CurrentThread->Name, CurrentCPU->CurrentThread->ID,
                   CurrentCPU->CurrentThread->Registers.rip,
                   CurrentCPU->CurrentThread->Registers.rbp,
                   CurrentCPU->CurrentThread->Registers.rsp);
 #else
             trace("%s[%ld]: EIP=%#lx  EBP=%#lx  ESP=%#lx",
                   CurrentCPU->CurrentThread->Name, CurrentCPU->CurrentThread->ID,
                   CurrentCPU->CurrentThread->Registers.eip,
                   CurrentCPU->CurrentThread->Registers.ebp,
                   CurrentCPU->CurrentThread->Registers.esp);
 #endif
         }
         this->SchedulerTicks.store(size_t(TimeManager->GetCounter() - SchedTmpTicks));
     }
References assert, CleanupTerminated(), CPUData::CurrentProcess, CPUData::CurrentThread, debug, FindNewProcess(), CPU::x32::fxrstor(), CPU::x64::fxrstor(), CPU::x64::fxsave(), GDT_KERNEL_CODE, Time::time::GetCounter(), GetCurrentCPU(), GetNextAvailableProcess(), GetNextAvailableThread(), CPUData::ID, Tasking::Idle, IdleProcess, IdleThread, KernelPageTable, Tasking::Scheduler::Base::LastCore, Tasking::Scheduler::Base::LastTaskTicks, CPU::x32::MSR_FS_BASE, CPU::x64::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, CPU::x64::MSR_GS_BASE, CPU::x32::MSR_SHADOW_GS_BASE, CPU::x64::MSR_SHADOW_GS_BASE, OneShot(), Tasking::Ready, Tasking::Running, schedbg, SchedulerSearchProcessThread(), Tasking::Scheduler::Base::SchedulerTicks, Tasking::Scheduler::Base::SchedulerUpdateTrapFrame, GlobalDescriptorTable::SetKernelStack(), Tasking::Scheduler::Base::StopScheduler, TimeManager, trace, unlikely, UpdateProcessState(), UpdateUsage(), WakeUpThreads(), and warn.
Referenced by OnInterruptReceived().
SchedulerSearchProcessThread()
nsa NIF bool Tasking::Scheduler::Custom::SchedulerSearchProcessThread (void * CPUDataPointer)
Definition at line 444 of file custom.cpp.
     {
         CPUData *CurrentCPU = (CPUData *)CPUDataPointer;
         foreach (auto process in ProcessList)
         {
             if (process->State.load() != TaskState::Ready)
             {
                 sspt_schedbg("Process %d is not ready", process->ID);
                 continue;
             }
             foreach (auto thread in process->Threads)
             {
                 if (thread->State.load() != TaskState::Ready)
                 {
                     sspt_schedbg("Thread %d is not ready", thread->ID);
                     continue;
                 }
                 if (thread->Info.Affinity[CurrentCPU->ID] == false)
                     continue;
                 CurrentCPU->CurrentProcess = process;
                 CurrentCPU->CurrentThread = thread;
                 sspt_schedbg("[proc 0 -> end -> first thd] Scheduling thread %d parent of %s->%d (Procs %d)",
                              thread->ID, thread->Parent->Name, process->Threads.size(), ProcessList.size());
                 return true;
             }
         }
         return false;
     }
References ProcessList, Tasking::Ready, and sspt_schedbg.
Referenced by Schedule().
StartIdleProcess()
void Tasking::Scheduler::Custom::StartIdleProcess () final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 171 of file custom.cpp.
     {
         IdleProcess = ctx->CreateProcess(nullptr, (char *)"Idle",
                                          TaskExecutionMode::Kernel, true);
         for (int i = 0; i < SMP::CPUCores; i++)
         {
             TCB *thd = ctx->CreateThread(IdleProcess, IP(__custom_sched_idle_loop));
             char IdleName[16];
             sprintf(IdleName, "Idle Thread %d", i);
             thd->Rename(IdleName);
             thd->SetPriority(Idle);
             for (int j = 0; j < MAX_CPU; j++)
                 thd->Info.Affinity[j] = false;
             thd->Info.Affinity[i] = true;
             if (unlikely(i == 0))
                 IdleThread = thd;
         }
     }
References __custom_sched_idle_loop(), Tasking::TaskInfo::Affinity, SMP::CPUCores, Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), Tasking::Scheduler::Base::ctx, Tasking::Idle, IdleProcess, IdleThread, if(), Tasking::TCB::Info, Tasking::Kernel, MAX_CPU, Tasking::TCB::Rename(), Tasking::TCB::SetPriority(), sprintf(), and unlikely.
StartScheduler()
void Tasking::Scheduler::Custom::StartScheduler () final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 196 of file custom.cpp.
     {
 #if defined(a86)
         if (Interrupts::apicTimer[0])
         {
             ((APIC::Timer *)Interrupts::apicTimer[0])->OneShot(CPU::x86::IRQ16, 100);
             /* FIXME: The kernel is not ready for multi-core tasking. */
             return;
             APIC::InterruptCommandRegister icr{};
             bool x2APIC = ((APIC::APIC *)Interrupts::apic[0])->x2APIC;
             if (likely(x2APIC))
             {
                 icr.x2.VEC = s_cst(uint8_t, CPU::x86::IRQ16);
                 icr.x2.MT = APIC::Fixed;
                 icr.x2.L = APIC::Assert;
                 icr.x2.DES = 0xFFFFFFFF; /* Broadcast IPI to all local APICs. */
                 ((APIC::APIC *)Interrupts::apic[0])->ICR(icr);
             }
             else
             {
                 icr.VEC = s_cst(uint8_t, CPU::x86::IRQ16);
                 icr.MT = APIC::Fixed;
                 icr.L = APIC::Assert;
                 for (int i = 0; i < SMP::CPUCores; i++)
                 {
                     icr.DES = uint8_t(i);
                     ((APIC::APIC *)Interrupts::apic[i])->ICR(icr);
                 }
             }
         }
 #endif
     }
References APIC::Assert, SMP::CPUCores, APIC::Fixed, CPU::x86::IRQ16, and likely.
UpdateProcessState()
nsa NIF void Tasking::Scheduler::Custom::UpdateProcessState ()
Definition at line 477 of file custom.cpp.
     {
         foreach (auto process in ProcessList)
         {
             if (process->State.load() == TaskState::Terminated)
                 continue;
             if (process->Threads.size() == 1)
             {
                 process->State.exchange(process->Threads.front()->State.load());
                 continue;
             }
             bool AllThreadsSleeping = true;
             foreach (auto thread in process->Threads)
             {
                 if (thread->State.load() == TaskState::Terminated)
                     continue;
                 if (thread->State.load() != TaskState::Sleeping)
                 {
                     AllThreadsSleeping = false;
                     break;
                 }
             }
             if (AllThreadsSleeping)
                 process->State.store(TaskState::Sleeping);
             else if (process->State.load() == TaskState::Sleeping)
                 process->State.store(TaskState::Ready);
         }
     }
References ProcessList, Tasking::Ready, Tasking::Sleeping, and Tasking::Terminated.
Referenced by Schedule().
UpdateUsage()
nsa void Tasking::Scheduler::Custom::UpdateUsage (TaskInfo * Info, TaskExecutionMode Mode, int Core)
Definition at line 287 of file custom.cpp.
     {
         UNUSED(Core);
         uint64_t CurrentTime = TimeManager->GetCounter();
         uint64_t TimePassed = Info->LastUpdateTime - CurrentTime;
         Info->LastUpdateTime = CurrentTime;
         if (Mode == TaskExecutionMode::User)
             Info->UserTime += TimePassed;
         else
             Info->KernelTime += TimePassed;
     }
References Time::time::GetCounter(), Tasking::TaskInfo::KernelTime, Tasking::TaskInfo::LastUpdateTime, TimeManager, UNUSED, Tasking::User, and Tasking::TaskInfo::UserTime.
Referenced by Schedule().
WakeUpThreads()
nsa NIF void Tasking::Scheduler::Custom::WakeUpThreads ()
Definition at line 510 of file custom.cpp.
     {
         foreach (auto process in ProcessList)
         {
             Tasking::TaskState pState = process->State.load();
             if (pState != TaskState::Ready &&
                 pState != TaskState::Sleeping &&
                 pState != TaskState::Blocked)
                 continue;
             foreach (auto thread in process->Threads)
             {
                 if (likely(thread->State.load() != TaskState::Sleeping))
                     continue;
                 /* Check if the thread is ready to wake up. */
                 if (unlikely(thread->Info.SleepUntil < TimeManager->GetCounter()))
                 {
                     if (pState == TaskState::Sleeping)
                         process->State.store(TaskState::Ready);
                     thread->State.store(TaskState::Ready);
                     thread->Info.SleepUntil = 0;
                     wut_schedbg("Thread \"%s\"(%d) woke up.", thread->Name, thread->ID);
                 }
                 else
                 {
                     wut_schedbg("Thread \"%s\"(%d) is not ready to wake up. (SleepUntil: %d, Counter: %d)",
                                 thread->Name, thread->ID, thread->Info.SleepUntil, TimeManager->GetCounter());
                 }
             }
         }
     }
References Tasking::Blocked, Time::time::GetCounter(), likely, ProcessList, Tasking::Ready, Tasking::Sleeping, TimeManager, unlikely, and wut_schedbg.
Referenced by Schedule().
Yield()
void Tasking::Scheduler::Custom::Yield () final virtual
Reimplemented from Tasking::Scheduler::Base.
Definition at line 233 of file custom.cpp.
     {
         /* This will trigger the IRQ16
         instantly so we won't execute
         the next instruction */
 #if defined(a86)
         asmv("int $0x30");
 #elif defined(aa64)
         asmv("svc #0x30");
 #endif
     }
References asmv().
Field Documentation
IdleProcess
PCB* Tasking::Scheduler::Custom::IdleProcess = nullptr
Definition at line 116 of file scheduler.hpp.
Referenced by GetIdle(), Schedule(), and StartIdleProcess().
IdleThread
TCB* Tasking::Scheduler::Custom::IdleThread = nullptr
Definition at line 117 of file scheduler.hpp.
Referenced by GetIdle(), Schedule(), and StartIdleProcess().
ProcessList
std::vector<PCB *> Tasking::Scheduler::Custom::ProcessList
Definition at line 114 of file scheduler.hpp.
Referenced by CleanupTerminated(), FindNewProcess(), GetNextAvailableProcess(), GetNextAvailableThread(), GetProcessByID(), GetProcessList(), PopProcess(), PushProcess(), SchedulerSearchProcessThread(), UpdateProcessState(), WakeUpThreads(), and ~Custom().
The documentation for this class was generated from the following files:
Kernel/include/scheduler.hpp
Kernel/tasking/scheduler/custom.cpp