Fennix Kernel: std::list< T > Class Template Reference
std::list< T > Class Template Reference
#include <list.hpp>
Data Structures
class iterator
struct Node
Public Member Functions
list ()
~list ()
list (const list &other)
void push_back (const T &value)
void pop_back ()
void push_front (const T &value)
void pop_front ()
bool empty () const
void clear ()
list & operator= (const list &other)
iterator begin ()
iterator end ()
iterator insert (iterator pos, const T &value)
iterator erase (iterator pos)
Private Attributes
Node * head
Node * tail
size_t size
Detailed Description
template<typename T>
class std::list< T >
Definition at line 10 of file list.hpp.
Constructor & Destructor Documentation
list() [1/2]
template<typename T > std::list< T >::list () inline
Definition at line 28 of file list.hpp.
 : head(nullptr), tail(nullptr), size(0) {}
~list()
template<typename T > std::list< T >::~list () inline
Definition at line 29 of file list.hpp.
 { clear(); }
References std::list< T >::clear().
list() [2/2]
template<typename T > std::list< T >::list (const list< T > & other) inline
Definition at line 30 of file list.hpp.
 : head(nullptr), tail(nullptr), size(0) { *this = other; }
Member Function Documentation
begin()
template<typename T > iterator std::list< T >::begin () inline
Definition at line 168 of file list.hpp.
 { return iterator(head); }
References std::list< T >::head.
Referenced by std::unordered_map< key_type, value_type >::contains(), std::unordered_map< key_type, value_type >::find(), std::unordered_map< key_type, value_type >::insert(), std::list< T >::insert(), and std::unordered_map< key_type, value_type >::operator[]().
clear()
template<typename T > void std::list< T >::clear () inline
Definition at line 108 of file list.hpp.
         {
             while (!empty())
                 pop_back();
         }
References std::list< T >::empty(), and std::list< T >::pop_back().
Referenced by std::list< T >::operator=(), and std::list< T >::~list().
empty()
template<typename T > bool std::list< T >::empty () const inline
Definition at line 106 of file list.hpp.
 { return size == 0; }
References std::list< T >::size.
Referenced by std::list< T >::clear(), std::list< T >::pop_back(), std::list< T >::pop_front(), std::list< T >::push_back(), and std::list< T >::push_front().
end()
template<typename T > iterator std::list< T >::end () inline
Definition at line 169 of file list.hpp.
 { return iterator(nullptr); }
Referenced by std::unordered_map< key_type, value_type >::contains(), std::unordered_map< key_type, value_type >::find(), std::unordered_map< key_type, value_type >::insert(), std::list< T >::insert(), and std::unordered_map< key_type, value_type >::operator[]().
erase()
template<typename T > iterator std::list< T >::erase (iterator pos) inline
Definition at line 194 of file list.hpp.
         {
             Node *p = pos.node;
             iterator next(p->next);
             p->prev->next = p->next;
             p->next->prev = p->prev;
             delete p;
             --size;
             return next;
         }
References std::list< T >::Node::next, std::list< T >::iterator::node, std::list< T >::Node::prev, and std::list< T >::size.
insert()
template<typename T > iterator std::list< T >::insert (iterator pos, const T & value) inline
Definition at line 171 of file list.hpp.
         {
             if (pos == end())
             {
                 push_back(value);
                 return iterator(tail);
             }
             else if (pos == begin())
             {
                 push_front(value);
                 return iterator(head);
             }
             else
             {
                 Node *p = pos.node;
                 Node *new_node = new Node(value, p->prev, p);
                 p->prev->next = new_node;
                 p->prev = new_node;
                 ++size;
                 return iterator(new_node);
             }
         }
References std::list< T >::begin(), std::list< T >::end(), std::list< T >::head, std::list< T >::Node::next, std::list< T >::iterator::node, std::list< T >::Node::prev, std::list< T >::push_back(), std::list< T >::push_front(), std::list< T >::size, and std::list< T >::tail.
operator=()
template<typename T > list& std::list< T >::operator= (const list< T > & other) inline
Definition at line 114 of file list.hpp.
         {
             if (this != &other)
             {
                 clear();
                 for (const T &value : other)
                 {
                     push_back(value);
                 }
             }
             return *this;
         }
References std::list< T >::clear(), and std::list< T >::push_back().
pop_back()
template<typename T > void std::list< T >::pop_back () inline
Definition at line 47 of file list.hpp.
         {
             if (empty())
             {
                 throw std::runtime_error("list is empty");
             }
             else if (head == tail)
             {
                 delete tail;
                 head = tail = nullptr;
                 --size;
             }
             else
             {
                 Node *old_tail = tail;
                 tail = tail->prev;
                 tail->next = nullptr;
                 delete old_tail;
                 --size;
             }
         }
References std::list< T >::empty(), std::list< T >::head, std::list< T >::Node::next, std::list< T >::Node::prev, std::list< T >::size, and std::list< T >::tail.
Referenced by std::list< T >::clear().
pop_front()
template<typename T > void std::list< T >::pop_front () inline
Definition at line 84 of file list.hpp.
         {
             if (empty())
             {
                 throw std::runtime_error("list is empty");
             }
             else if (head == tail)
             {
                 delete head;
                 head = tail = nullptr;
                 --size;
             }
             else
             {
                 Node *old_head = head;
                 head = head->next;
                 head->prev = nullptr;
                 delete old_head;
                 --size;
             }
         }
References std::list< T >::empty(), std::list< T >::head, std::list< T >::Node::next, std::list< T >::Node::prev, std::list< T >::size, and std::list< T >::tail.
push_back()
template<typename T > void std::list< T >::push_back (const T & value) inline
Definition at line 32 of file list.hpp.
         {
             Node *new_node = new Node(value, tail, nullptr);
             if (empty())
             {
                 head = tail = new_node;
             }
             else
             {
                 tail->next = new_node;
                 tail = new_node;
             }
             ++size;
         }
References std::list< T >::empty(), std::list< T >::head, std::list< T >::Node::next, std::list< T >::size, and std::list< T >::tail.
Referenced by std::unordered_map< key_type, value_type >::insert(), std::list< T >::insert(), and std::list< T >::operator=().
push_front()
template<typename T > void std::list< T >::push_front (const T & value) inline
Definition at line 69 of file list.hpp.
         {
             Node *new_node = new Node(value, nullptr, head);
             if (empty())
             {
                 head = tail = new_node;
             }
             else
             {
                 head->prev = new_node;
                 head = new_node;
             }
             ++size;
         }
References std::list< T >::empty(), std::list< T >::head, std::list< T >::Node::prev, std::list< T >::size, and std::list< T >::tail.
Referenced by std::list< T >::insert().
Field Documentation
head
template<typename T > Node* std::list< T >::head private
Definition at line 23 of file list.hpp.
Referenced by std::list< T >::begin(), std::list< T >::insert(), std::list< T >::pop_back(), std::list< T >::pop_front(), std::list< T >::push_back(), and std::list< T >::push_front().
size
template<typename T > size_t std::list< T >::size private
Definition at line 25 of file list.hpp.
Referenced by std::list< T >::empty(), std::list< T >::erase(), std::list< T >::insert(), std::list< T >::pop_back(), std::list< T >::pop_front(), std::list< T >::push_back(), std::list< T >::push_front(), and std::unordered_map< key_type, value_type >::size().
tail
template<typename T > Node* std::list< T >::tail private
Definition at line 24 of file list.hpp.
Referenced by std::list< T >::insert(), std::list< T >::pop_back(), std::list< T >::pop_front(), std::list< T >::push_back(), and std::list< T >::push_front().
The documentation for this class was generated from the following file:
Kernel/include/std/list.hpp