Fennix: VirtualFileSystem::Virtual Class Reference
VirtualFileSystem::Virtual Class Reference
#include <filesystem.hpp>
Public Member Functions
std::shared_ptr< char > GetPathFromNode (Node *node)
Node * GetNodeFromPath (const char *Path, Node *Parent=nullptr)
File ConvertNodeToFILE (Node *node)
Convert a Node to a File.
Node * GetParent (const char *Path, Node *Parent)
Node * GetRootNode ()
Node * AddNewChild (const char *Name, Node *Parent)
Node * GetChild (const char *Name, Node *Parent)
FileStatus RemoveChild (const char *Name, Node *Parent)
std::shared_ptr< char > NormalizePath (const char *Path, Node *Parent=nullptr)
bool PathExists (const char *Path, Node *Parent=nullptr)
Node * CreateRoot (const char *RootName, FileSystemOperations *Operator)
Node * Create (const char *Path, NodeFlags Flag, Node *Parent=nullptr)
FileStatus Delete (const char *Path, bool Recursive=false, Node *Parent=nullptr)
FileStatus Delete (Node *Path, bool Recursive=false, Node *Parent=nullptr)
File Mount (const char *Path, FileSystemOperations *Operator)
FileStatus Unmount (File &File)
size_t Read (File &File, size_t Offset, uint8_t *Buffer, size_t Size)
size_t Write (File &File, size_t Offset, uint8_t *Buffer, size_t Size)
File Open (const char *Path, Node *Parent=nullptr)
FileStatus Close (File &File)
Virtual ()
~Virtual ()
Private Attributes
Node * FileSystemRoot = nullptr
Detailed Description
Definition at line 136 of file filesystem.hpp.
Constructor & Destructor Documentation
Virtual()
Memory::Virtual::Virtual ()
Definition at line 295 of file VirtualMemoryManager.cpp.
     {
         if (Table)
             this->Table = Table;
         else
             this->Table = (PageTable4 *)CPU::PageTable();
     }
References CPU::PageTable().
~Virtual()
Memory::Virtual::~Virtual ()
Definition at line 303 of file VirtualMemoryManager.cpp.
 {}
Member Function Documentation
AddNewChild()
Node * VirtualFileSystem::Virtual::AddNewChild (const char * Name, Node * Parent)
Definition at line 217 of file Filesystem.cpp.
     {
         if (!Parent)
         {
             error("Parent is null!");
             return nullptr;
         }
         vfsdbg("AddNewChild( Name: \"%s\" Parent: \"%s\" )", Name, Parent->Name);
         Node *newNode = new Node;
         newNode->Parent = Parent;
         strcpy(newNode->Name, Name);
         newNode->Operator = Parent->Operator;
         Parent->Children.push_back(newNode);
         vfsdbg("AddNewChild()->\"%s\"", newNode->Name);
         return newNode;
     }
References VirtualFileSystem::Node::Children, error, CPU::Name(), VirtualFileSystem::Node::Name, VirtualFileSystem::Node::Operator, VirtualFileSystem::Node::Parent, strcpy, and vfsdbg.
Referenced by Create().
Close()
FileStatus VirtualFileSystem::Virtual::Close (File & File)
Definition at line 620 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         if (unlikely(!File.node))
             return FileStatus::InvalidHandle;
         vfsdbg("Closing %s", File.Name);
         return FileStatus::OK;
     }
References VirtualFileSystem::InvalidHandle, VirtualFileSystem::File::Name, VirtualFileSystem::File::node, OK, unlikely, and vfsdbg.
Referenced by BootLogoAnimationThread(), Driver::Driver::Driver(), Execute::ELFLoad(), Execute::ELFLoadExec(), Execute::GetBinaryType(), Main(), Recovery::PlayAudio(), Execute::Spawn(), sys_file_close(), sys_file_open(), and sys_kernelctl().
ConvertNodeToFILE()
File VirtualFileSystem::Virtual::ConvertNodeToFILE (Node * node)
Convert a Node to a File.
Parameters
node Node to convert
Returns
Converted node
Definition at line 171 of file Filesystem.cpp.
     {
         File file{};
         file.Status = FileStatus::OK;
         file.node = node;
         return file;
     }
References OK, and VirtualFileSystem::File::Status.
Create()
Node * VirtualFileSystem::Virtual::Create (const char * Path, NodeFlags Flag, Node * Parent = nullptr)
Definition at line 335 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         if (isempty((char *)Path))
             return nullptr;
         Node *RootNode = FileSystemRoot->Children[0];
         Node *CurrentParent = this->GetParent(Path, Parent);
         vfsdbg("Virtual::Create( Path: \"%s\" Parent: \"%s\" )", Path, Parent ? Parent->Name : CurrentParent->Name);
         std::shared_ptr<char> CleanPath = this->NormalizePath(Path, CurrentParent);
         vfsdbg("CleanPath: \"%s\"", CleanPath.get());
         if (PathExists(CleanPath.get(), CurrentParent))
         {
             error("Path %s already exists.", CleanPath.get());
             goto CreatePathError;
         }
         cwk_segment segment;
         if (!cwk_path_get_first_segment(CleanPath.get(), &segment))
         {
             error("Path doesn't have any segments.");
             goto CreatePathError;
         }
         do
         {
             char *SegmentName = new char[segment.end - segment.begin + 1];
             memcpy(SegmentName, segment.begin, segment.end - segment.begin);
             vfsdbg("SegmentName: \"%s\"", SegmentName);
             if (Parent)
                 if (GetChild(SegmentName, RootNode) != nullptr)
                 {
                     RootNode = GetChild(SegmentName, RootNode);
                     delete[] SegmentName;
                     continue;
                 }
             if (GetChild(SegmentName, CurrentParent) == nullptr)
             {
                 CurrentParent = AddNewChild(SegmentName, CurrentParent);
                 CurrentParent->Flags = Flag;
             }
             else
             {
                 CurrentParent = GetChild(SegmentName, CurrentParent);
             }
             delete[] SegmentName;
         } while (cwk_path_get_next_segment(&segment));
         vfsdbg("Virtual::Create()->\"%s\"", CurrentParent->Name);
         vfsdbg("Path created: \"%s\"", GetPathFromNode(CurrentParent).get());
         return CurrentParent;
     CreatePathError:
         vfsdbg("Virtual::Create()->nullptr");
         return nullptr;
     }
References AddNewChild(), cwk_segment::begin, VirtualFileSystem::Node::Children, cwk_path_get_first_segment(), cwk_path_get_next_segment(), cwk_segment::end, error, FileSystemRoot, VirtualFileSystem::Node::Flags, std::shared_ptr< T >::get(), GetChild(), GetParent(), GetPathFromNode(), isempty(), memcpy, VirtualFileSystem::Node::Name, NormalizePath(), PathExists(), and vfsdbg.
Referenced by InterProcessCommunication::IPC::Create(), Tasking::Task::CreateProcess(), InterProcessCommunication::IPC::IPC(), Main(), Mount(), and VirtualFileSystem::USTAR::USTAR().
CreateRoot()
Node * VirtualFileSystem::Virtual::CreateRoot (const char * RootName, FileSystemOperations * Operator)
Definition at line 321 of file Filesystem.cpp.
     {
         if (Operator == nullptr)
             return nullptr;
         vfsdbg("Creating root %s", RootName);
         Node *newNode = new Node;
         strncpy(newNode->Name, RootName, FILENAME_LENGTH);
         newNode->Flags = NodeFlags::DIRECTORY;
         newNode->Operator = Operator;
         FileSystemRoot->Children.push_back(newNode);
         return newNode;
     }
References VirtualFileSystem::Node::Children, VirtualFileSystem::DIRECTORY, FILENAME_LENGTH, FileSystemRoot, VirtualFileSystem::Node::Flags, VirtualFileSystem::Node::Name, VirtualFileSystem::Node::Operator, strncpy(), and vfsdbg.
Referenced by VirtualFileSystem::USTAR::USTAR().
Delete() [1/2]
FileStatus VirtualFileSystem::Virtual::Delete (const char * Path, bool Recursive = false, Node * Parent = nullptr)
Definition at line 398 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         vfsdbg("Virtual::Delete( Path: \"%s\" Parent: \"%s\" )", Path, Parent ? Parent->Name : "(null)");
         if (isempty((char *)Path))
             return InvalidParameter;
         if (Parent == nullptr)
             Parent = FileSystemRoot;
         std::shared_ptr<char> CleanPath = this->NormalizePath(Path, Parent);
         vfsdbg("CleanPath: \"%s\"", CleanPath.get());
         if (!PathExists(CleanPath.get(), Parent))
         {
             vfsdbg("Path %s doesn't exist.", CleanPath.get());
             return InvalidPath;
         }
         Node *NodeToDelete = GetNodeFromPath(CleanPath.get(), Parent);
         Node *ParentNode = GetParent(CleanPath.get(), Parent);
         if (NodeToDelete->Flags == NodeFlags::DIRECTORY)
         {
             if (Recursive)
             {
                 foreach (auto Child in NodeToDelete->Children)
                 {
                     VFSLock.Unlock();
                     FileStatus Status = Delete(GetPathFromNode(Child).get(), true);
                     VFSLock.Lock(__FUNCTION__);
                     if (Status != FileStatus::OK)
                     {
                         vfsdbg("Failed to delete child %s with status %d. (%s)", Child->Name, Status, Path);
                         return PartiallyCompleted;
                     }
                 }
             }
             else if (NodeToDelete->Children.size() > 0)
             {
                 vfsdbg("Directory %s is not empty.", CleanPath.get());
                 return DirectoryNotEmpty;
             }
         }
         if (RemoveChild(NodeToDelete->Name, ParentNode) != FileStatus::OK)
         {
             vfsdbg("Failed to remove child %s from parent %s. (%s)", NodeToDelete->Name, ParentNode->Name, Path);
             return NotFound;
         }
         vfsdbg("Virtual::Delete()->OK");
         return OK;
     }
References VirtualFileSystem::Node::Children, VirtualFileSystem::DIRECTORY, VirtualFileSystem::DirectoryNotEmpty, FileSystemRoot, VirtualFileSystem::Node::Flags, std::shared_ptr< T >::get(), GetNodeFromPath(), GetParent(), GetPathFromNode(), VirtualFileSystem::InvalidParameter, VirtualFileSystem::InvalidPath, isempty(), VirtualFileSystem::Node::Name, NormalizePath(), VirtualFileSystem::NotFound, OK, VirtualFileSystem::OK, VirtualFileSystem::PartiallyCompleted, PathExists(), RemoveChild(), and vfsdbg.
Referenced by Delete(), InterProcessCommunication::IPC::Destroy(), Tasking::Task::RemoveProcess(), and InterProcessCommunication::IPC::~IPC().
Delete() [2/2]
FileStatus VirtualFileSystem::Virtual::Delete (Node * Path, bool Recursive = false, Node * Parent = nullptr)
Definition at line 454 of file Filesystem.cpp.
 { return Delete(GetPathFromNode(Path).get(), Recursive, Parent); }
References Delete(), and GetPathFromNode().
GetChild()
Node * VirtualFileSystem::Virtual::GetChild (const char * Name, Node * Parent)
Definition at line 237 of file Filesystem.cpp.
     {
         vfsdbg("GetChild( Name: \"%s\" Parent: \"%s\" )", Name, Parent->Name);
         if (!Parent)
         {
             vfsdbg("GetChild()->nullptr");
             return nullptr;
         }
         foreach (auto Child in Parent->Children)
             if (strcmp(Child->Name, Name) == 0)
             {
                 vfsdbg("GetChild()->\"%s\"", Child->Name);
                 return Child;
             }
         vfsdbg("GetChild()->nullptr (not found)");
         return nullptr;
     }
References CPU::Name(), VirtualFileSystem::Node::Name, strcmp(), and vfsdbg.
Referenced by Create().
GetNodeFromPath()
Node * VirtualFileSystem::Virtual::GetNodeFromPath (const char * Path, Node * Parent = nullptr)
Definition at line 119 of file Filesystem.cpp.
     {
         vfsdbg("GetNodeFromPath( Path: \"%s\" Parent: \"%s\" )", Path, Parent ? Parent->Name : "(null)");
         Node *ReturnNode = Parent;
         bool IsAbsolutePath = cwk_path_is_absolute(Path);
         if (!ReturnNode)
             ReturnNode = FileSystemRoot->Children[0]; // 0 - filesystem root
         if (IsAbsolutePath)
             ReturnNode = FileSystemRoot->Children[0]; // 0 - filesystem root
         cwk_segment segment;
         if (unlikely(!cwk_path_get_first_segment(Path, &segment)))
         {
             error("Path doesn't have any segments.");
             return nullptr;
         }
         do
         {
             char *SegmentName = new char[segment.end - segment.begin + 1];
             memcpy(SegmentName, segment.begin, segment.end - segment.begin);
             vfsdbg("GetNodeFromPath()->SegmentName: \"%s\"", SegmentName);
         GetNodeFromPathNextParent:
             foreach (auto Child in ReturnNode->Children)
             {
                 vfsdbg("comparing \"%s\" with \"%s\"", Child->Name, SegmentName);
                 if (strcmp(Child->Name, SegmentName) == 0)
                 {
                     ReturnNode = Child;
                     goto GetNodeFromPathNextParent;
                 }
             }
             delete[] SegmentName;
         } while (cwk_path_get_next_segment(&segment));
         const char *basename;
         cwk_path_get_basename(Path, &basename, nullptr);
         vfsdbg("BaseName: \"%s\" NodeName: \"%s\"", basename, ReturnNode->Name);
         if (strcmp(basename, ReturnNode->Name) == 0)
         {
             vfsdbg("GetNodeFromPath()->\"%s\"", ReturnNode->Name);
             return ReturnNode;
         }
         vfsdbg("GetNodeFromPath()->\"(null)\"");
         return nullptr;
     }
References basename, cwk_segment::begin, VirtualFileSystem::Node::Children, cwk_path_get_basename(), cwk_path_get_first_segment(), cwk_path_get_next_segment(), cwk_path_is_absolute(), cwk_segment::end, error, FileSystemRoot, memcpy, VirtualFileSystem::Node::Name, strcmp(), unlikely, and vfsdbg.
Referenced by Delete(), Open(), and PathExists().
GetParent()
Node * VirtualFileSystem::Virtual::GetParent (const char * Path, Node * Parent)
Definition at line 179 of file Filesystem.cpp.
     {
         vfsdbg("GetParent( Path: \"%s\" Parent: \"%s\" )", Path, Parent->Name);
         if (Parent)
         {
             vfsdbg("GetParent()->\"%s\"", Parent->Name);
             return Parent;
         }
         Node *ParentNode = nullptr;
         if (FileSystemRoot->Children.size() >= 1)
         {
             assert(FileSystemRoot->Children[0] != nullptr);
             ParentNode = FileSystemRoot->Children[0]; // 0 - filesystem root
         }
         else
         {
             // TODO: Check if here is a bug or something...
             const char *PathCopy;
             PathCopy = (char *)Path;
             size_t length;
             cwk_path_get_root(PathCopy, &length); // not working?
             if (length > 0)
             {
                 foreach (auto Child in FileSystemRoot->Children)
                 {
                     if (strcmp(Child->Name, PathCopy) == 0)
                     {
                         ParentNode = Child;
                         break;
                     }
                 }
             }
         }
         vfsdbg("GetParent()->\"%s\"", ParentNode->Name);
         return ParentNode;
     }
References assert, VirtualFileSystem::Node::Children, cwk_path_get_root(), FileSystemRoot, VirtualFileSystem::Node::Name, strcmp(), and vfsdbg.
Referenced by Create(), Delete(), and Open().
GetPathFromNode()
std::shared_ptr< char > VirtualFileSystem::Virtual::GetPathFromNode (Node * node)
Definition at line 41 of file Filesystem.cpp.
     {
         vfsdbg("GetPathFromNode( Node: \"%s\" )", node->Name);
         Node *Parent = node;
         char **Path = nullptr;
         size_t Size = 1;
         size_t PathSize = 0;
         // Traverse the filesystem tree and build the path by adding each parent's Name field to the Path array
         while (Parent != FileSystemRoot && Parent != nullptr)
         {
             bool Found = false;
             foreach (const auto &Children in FileSystemRoot->Children)
                 if (Children == Parent)
                 {
                     Found = true;
                     break;
                 }
             if (Found)
                 break;
             if (strlen(Parent->Name) == 0)
                 break;
             char **new_path = new char *[PathSize + 1];
             if (Path != nullptr)
             {
                 memcpy(new_path, Path, sizeof(char *) * PathSize);
                 delete[] Path;
             }
             Path = new_path;
             Path[PathSize] = Parent->Name;
             PathSize++;
             new_path = new char *[PathSize + 1];
             memcpy(new_path, Path, sizeof(char *) * PathSize);
             delete[] Path;
             Path = new_path;
             Path[PathSize] = (char *)"/";
             PathSize++;
             Parent = Parent->Parent;
         }
         // Calculate the total size of the final path string
         for (size_t i = 0; i < PathSize; i++)
         {
             Size += strlen(Path[i]);
         }
         // Allocate a new string for the final path
         std::shared_ptr<char> FinalPath;
         FinalPath.reset(new char[Size]);
         size_t Offset = 0;
         // Concatenate the elements of the Path array into the FinalPath string
         for (size_t i = PathSize - 1; i < PathSize; i--)
         {
             if (Path[i] == nullptr)
             {
                 continue;
             }
             size_t ElementSize = strlen(Path[i]);
             memcpy(FinalPath.get() + Offset, Path[i], ElementSize);
             Offset += ElementSize;
         }
         // Add a null terminator to the final path string
         FinalPath.get()[Size - 1] = '\0';
         // Deallocate the Path array
         delete[] Path, Path = nullptr;
         vfsdbg("GetPathFromNode()->\"%s\"", FinalPath.get());
         return FinalPath;
     }
References VirtualFileSystem::Node::Children, FileSystemRoot, std::shared_ptr< T >::get(), i, memcpy, VirtualFileSystem::Node::Name, VirtualFileSystem::Node::Parent, std::shared_ptr< T >::reset(), Size, strlen(), and vfsdbg.
Referenced by Create(), Delete(), Execute::ELFLoadExec(), NormalizePath(), and Open().
GetRootNode()
Node* VirtualFileSystem::Virtual::GetRootNode () inline
Definition at line 154 of file filesystem.hpp.
 { return FileSystemRoot; }
References FileSystemRoot.
Referenced by KernelMainThread().
Mount()
File VirtualFileSystem::Virtual::Mount (const char * Path, FileSystemOperations * Operator)
Definition at line 457 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         File file{};
         if (unlikely(!Operator))
         {
             file.Status = FileStatus::InvalidOperator;
             return file;
         }
         if (unlikely(isempty((char *)Path)))
         {
             file.Status = FileStatus::InvalidParameter;
             return file;
         }
         vfsdbg("Mounting %s", Path);
         const char *PathCopy;
         cwk_path_get_basename(Path, &PathCopy, 0);
         strcpy(file.Name, PathCopy);
         file.Status = FileStatus::OK;
         file.node = Create(Path, NodeFlags::MOUNTPOINT);
         file.node->Operator = Operator;
         return file;
     }
References Create(), cwk_path_get_basename(), VirtualFileSystem::InvalidOperator, VirtualFileSystem::InvalidParameter, isempty(), VirtualFileSystem::MOUNTPOINT, OK, VirtualFileSystem::File::Status, strcpy, unlikely, and vfsdbg.
NormalizePath()
std::shared_ptr< char > VirtualFileSystem::Virtual::NormalizePath (const char * Path, Node * Parent = nullptr)
Definition at line 273 of file Filesystem.cpp.
     {
         vfsdbg("NormalizePath( Path: \"%s\" Parent: \"%s\" )", Path, Parent->Name);
         char *NormalizedPath = new char[strlen((char *)Path) + 1];
         std::shared_ptr<char> RelativePath;
         cwk_path_normalize(Path, NormalizedPath, strlen((char *)Path) + 1);
         if (cwk_path_is_relative(NormalizedPath))
         {
             std::shared_ptr<char> ParentPath = GetPathFromNode(Parent);
             size_t PathSize = cwk_path_get_absolute(ParentPath.get(), NormalizedPath, nullptr, 0);
             RelativePath.reset(new char[PathSize + 1]);
             cwk_path_get_absolute(ParentPath.get(), NormalizedPath, RelativePath.get(), PathSize + 1);
         }
         else
         {
             RelativePath.reset(new char[strlen(NormalizedPath) + 1]);
             strcpy(RelativePath.get(), NormalizedPath);
         }
         delete[] NormalizedPath;
         vfsdbg("NormalizePath()->\"%s\"", RelativePath.get());
         return RelativePath;
     }
References cwk_path_get_absolute(), cwk_path_is_relative(), cwk_path_normalize(), std::shared_ptr< T >::get(), GetPathFromNode(), VirtualFileSystem::Node::Name, std::shared_ptr< T >::reset(), strcpy, strlen(), and vfsdbg.
Referenced by Create(), Delete(), Open(), and PathExists().
Open()
File VirtualFileSystem::Virtual::Open (const char * Path, Node * Parent = nullptr)
Definition at line 536 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         vfsdbg("Opening %s with parent %s", Path, Parent ? Parent->Name : "(null)");
         const char *basename;
         if (strcmp(Path, "/") == 0)
         {
             File file{};
             file.node = FileSystemRoot;
             strcpy(file.Name, "/");
             return file;
         }
         if (strcmp(Path, ".") == 0)
         {
             File file{};
             file.node = Parent;
             if (unlikely(!file.node))
                 file.Status = FileStatus::NotFound;
             cwk_path_get_basename(GetPathFromNode(Parent).get(), &basename, nullptr);
             strcpy(file.Name, basename);
             return file;
         }
         if (strcmp(Path, "..") == 0)
         {
             File file{};
             if (Parent->Parent != nullptr)
                 file.node = Parent->Parent;
             if (!file.node)
                 file.Status = FileStatus::NotFound;
             cwk_path_get_basename(GetPathFromNode(Parent).get(), &basename, nullptr);
             strcpy(file.Name, basename);
             return file;
         }
         Node *CurrentParent = this->GetParent(Path, Parent);
         std::shared_ptr<char> CleanPath = NormalizePath(Path, CurrentParent);
         File file{};
         /* TODO: Check for other errors */
         if (!PathExists(CleanPath.get(), CurrentParent))
         {
             foreach (auto Child in FileSystemRoot->Children)
             {
                 if (strcmp(Child->Name, CleanPath.get()) == 0)
                 {
                     file.node = Child;
                     if (file.node == nullptr)
                     {
                         file.Status = FileStatus::UnknownFileStatusError;
                         file.node = nullptr;
                         return file;
                     }
                     cwk_path_get_basename(GetPathFromNode(Child).get(), &basename, nullptr);
                     strcpy(file.Name, basename);
                     return file;
                 }
             }
             file.node = GetNodeFromPath(CleanPath.get(), FileSystemRoot->Children[0]);
             if (file.node)
             {
                 cwk_path_get_basename(GetPathFromNode(file.node).get(), &basename, nullptr);
                 strcpy(file.Name, basename);
                 return file;
             }
         }
         else
         {
             file.node = GetNodeFromPath(CleanPath.get(), CurrentParent);
             cwk_path_get_basename(CleanPath.get(), &basename, nullptr);
             strcpy(file.Name, basename);
             return file;
         }
         file.Status = FileStatus::NotFound;
         return file;
     }
References basename, VirtualFileSystem::Node::Children, cwk_path_get_basename(), FileSystemRoot, std::shared_ptr< T >::get(), GetNodeFromPath(), GetParent(), GetPathFromNode(), VirtualFileSystem::Node::Name, VirtualFileSystem::File::node, NormalizePath(), VirtualFileSystem::NotFound, VirtualFileSystem::Node::Parent, PathExists(), strcmp(), strcpy, VirtualFileSystem::UnknownFileStatusError, unlikely, and vfsdbg.
Referenced by BootLogoAnimationThread(), Driver::Driver::Driver(), Execute::ELFLoad(), Execute::ELFLoadExec(), Execute::GetBinaryType(), Execute::LoadELFInterpreter(), Main(), Recovery::PlayAudio(), Execute::Spawn(), sys_file_open(), and sys_kernelctl().
PathExists()
bool VirtualFileSystem::Virtual::PathExists (const char * Path, Node * Parent = nullptr)
Definition at line 298 of file Filesystem.cpp.
     {
         if (isempty((char *)Path))
         {
             vfsdbg("PathExists()->PathIsEmpty");
             return false;
         }
         if (Parent == nullptr)
             Parent = FileSystemRoot;
         vfsdbg("PathExists( Path: \"%s\" Parent: \"%s\" )", Path, Parent->Name);
         if (GetNodeFromPath(NormalizePath(Path, Parent).get(), Parent))
         {
             vfsdbg("PathExists()->OK");
             return true;
         }
         vfsdbg("PathExists()->NotFound");
         return false;
     }
References FileSystemRoot, GetNodeFromPath(), isempty(), VirtualFileSystem::Node::Name, NormalizePath(), and vfsdbg.
Referenced by Create(), Delete(), Main(), and Open().
Read()
size_t VirtualFileSystem::Virtual::Read (File & File, size_t Offset, uint8_t * Buffer, size_t Size)
Definition at line 493 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         if (unlikely(!File.node))
         {
             File.Status = FileStatus::InvalidNode;
             return 0;
         }
         if (unlikely(!File.node->Operator))
         {
             File.Status = FileStatus::InvalidOperator;
             return 0;
         }
         File.Status = FileStatus::OK;
         vfsdbg("Reading %s out->%016x", File.Name, Buffer);
         return File.node->Operator->Read(File.node, Offset, Size, Buffer);
     }
References VirtualFileSystem::InvalidNode, VirtualFileSystem::InvalidOperator, VirtualFileSystem::File::Name, VirtualFileSystem::File::node, OK, VirtualFileSystem::Node::Operator, VirtualFileSystem::FileSystemOperations::Read, Size, VirtualFileSystem::File::Status, unlikely, and vfsdbg.
Referenced by sys_file_read().
RemoveChild()
FileStatus VirtualFileSystem::Virtual::RemoveChild (const char * Name, Node * Parent)
Definition at line 256 of file Filesystem.cpp.
     {
         vfsdbg("RemoveChild( Name: \"%s\" Parent: \"%s\" )", Name, Parent->Name);
         for (size_t i = 0; i < Parent->Children.size(); i++)
         {
             if (strcmp(Parent->Children[i]->Name, Name) == 0)
             {
                 delete Parent->Children[i], Parent->Children[i] = nullptr;
                 Parent->Children.remove(i);
                 vfsdbg("RemoveChild()->OK");
                 return FileStatus::OK;
             }
         }
         vfsdbg("RemoveChild()->NotFound");
         return FileStatus::NotFound;
     }
References VirtualFileSystem::Node::Children, i, CPU::Name(), VirtualFileSystem::Node::Name, VirtualFileSystem::NotFound, OK, strcmp(), and vfsdbg.
Referenced by Delete().
Unmount()
FileStatus VirtualFileSystem::Virtual::Unmount (File & File)
Definition at line 484 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         if (unlikely(!File.node))
             return FileStatus::InvalidParameter;
         fixme("Unmounting %s", File.Name);
         return FileStatus::OK;
     }
References fixme, VirtualFileSystem::InvalidParameter, VirtualFileSystem::File::Name, VirtualFileSystem::File::node, OK, and unlikely.
Write()
size_t VirtualFileSystem::Virtual::Write (File & File, size_t Offset, uint8_t * Buffer, size_t Size)
Definition at line 514 of file Filesystem.cpp.
     {
         SmartLock(VFSLock);
         if (unlikely(!File.node))
         {
             File.Status = FileStatus::InvalidNode;
             return 0;
         }
         if (unlikely(!File.node->Operator))
         {
             File.Status = FileStatus::InvalidOperator;
             return 0;
         }
         File.Status = FileStatus::OK;
         vfsdbg("Writing %s out->%016x", File.Name, Buffer);
         return File.node->Operator->Write(File.node, Offset, Size, Buffer);
     }
References VirtualFileSystem::InvalidNode, VirtualFileSystem::InvalidOperator, VirtualFileSystem::File::Name, VirtualFileSystem::File::node, OK, VirtualFileSystem::Node::Operator, Size, VirtualFileSystem::File::Status, unlikely, vfsdbg, and VirtualFileSystem::FileSystemOperations::Write.
Referenced by sys_file_write().
Field Documentation
FileSystemRoot
Node* VirtualFileSystem::Virtual::FileSystemRoot = nullptr private
Definition at line 139 of file filesystem.hpp.
Referenced by Create(), CreateRoot(), Delete(), GetNodeFromPath(), GetParent(), GetPathFromNode(), GetRootNode(), Open(), and PathExists().
The documentation for this class was generated from the following files:
Kernel/include/filesystem.hpp
Kernel/Core/Memory/VirtualMemoryManager.cpp
Kernel/FileSystem/Filesystem.cpp