Fennix Userspace: Userspace/mlibc/tests/rtdl/rtld_next/libfoo.c File Reference
libfoo.c File Reference
#include <dlfcn.h>
Typedefs
typedef char * charFn(void)
Functions
__attribute__ ((weak))
charFn * fooGetDefault ()
charFn * fooGetNext ()
Typedef Documentation
charFn
typedef char* charFn(void)
Definition at line 3 of file libfoo.c.
Function Documentation
__attribute__()
__attribute__ ((weak))
Definition at line 5 of file libfoo.c.
                       {
     return "foo";
 }
fooGetDefault()
charFn* fooGetDefault (void)
Definition at line 10 of file libfoo.c.
{
     return (charFn *)dlsym(RTLD_DEFAULT, "definedInBoth");
 }
References dlsym(), and RTLD_DEFAULT.
Referenced by main().
fooGetNext()
charFn* fooGetNext (void)
Definition at line 14 of file libfoo.c.
                      {
     return (charFn *)dlsym(RTLD_NEXT, "definedInBoth");
 }
References dlsym(), and RTLD_NEXT.
Referenced by main().