Fennix: Recovery::KernelRecovery Class Reference
Recovery::KernelRecovery Class Reference
#include <recovery.hpp>
Public Member Functions
void RecoveryThread ()
KernelRecovery ()
~KernelRecovery ()
Private Attributes
Memory::MemMgr * mem
Tasking::TCB * guiThread
Tasking::TCB * recoveryThread
Detailed Description
Definition at line 27 of file recovery.hpp.
Constructor & Destructor Documentation
KernelRecovery()
Recovery::KernelRecovery::KernelRecovery ()
Definition at line 322 of file RecoveryMain.cpp.
     {
         // PCB *proc = TaskManager->CreateProcess(TaskManager->GetCurrentProcess(), "Recovery", TaskTrustLevel::Kernel, nullptr);
         gui = new GraphicalUserInterface::GUI;
         guiThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (IP)GUIWrapper);
         guiThread->Rename("GUI Thread");
         guiThread->SetPriority(Tasking::TaskPriority::Critical);
         Rect RecoveryModeWindow;
         RecoveryModeWindow.Width = 460;
         RecoveryModeWindow.Height = 100;
         RecoveryModeWindow.Left = Display->GetBuffer(200)->Width / 2 - RecoveryModeWindow.Width / 2;
         RecoveryModeWindow.Top = Display->GetBuffer(200)->Height / 2 - RecoveryModeWindow.Height / 2;
         Window *RecWin = new Window(gui, RecoveryModeWindow, "Recovery Mode");
         gui->AddWindow(RecWin);
         WidgetCollection *wdgRecWin = new WidgetCollection(RecWin);
         wdgRecWin->CreateLabel({80, 10, 0, 0}, "This is not fully implemented.");
         wdgRecWin->CreateLabel({10, 40, 0, 0}, "All you can do is shutdown/reboot the system.");
         wdgRecWin->CreateButton({10, 70, 90, 20}, "Reboot", (uintptr_t)RebootCommandWrapper);
         wdgRecWin->CreateButton({110, 70, 90, 20}, "Shutdown", (uintptr_t)ShutdownCommandWrapper);
         RecWin->AddWidget(wdgRecWin);
         Rect DebugWindow;
         DebugWindow.Width = 460;
         DebugWindow.Height = 380;
         DebugWindow.Left = 5;
         DebugWindow.Top = 25;
         DbgWin = new Window(gui, DebugWindow, "Debug");
         gui->AddWindow(DbgWin);
         wdgDbgWin = new WidgetCollection(DbgWin);
         Video::Font *NewFont = new Video::Font(&_binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_start, &_binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_end, Video::FontType::PCScreenFont2);
         wdgDbgWin->ReplaceFont(NewFont);
         recoveryThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (IP)RecoveryThreadWrapper);
         recoveryThread->Rename("Recovery Thread");
         recoveryThread->SetPriority(Tasking::TaskPriority::Idle);
     }
References _binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_end, _binary_Files_tamsyn_font_1_11_Tamsyn7x14r_psf_start, GraphicalUserInterface::Window::AddWidget(), GraphicalUserInterface::GUI::AddWindow(), GraphicalUserInterface::WidgetCollection::CreateButton(), GraphicalUserInterface::WidgetCollection::CreateLabel(), Tasking::Task::CreateThread(), Tasking::Critical, Recovery::DbgWin, Display, Tasking::Task::GetCurrentProcess(), Recovery::gui, Recovery::GUIWrapper(), GraphicalUserInterface::Rect::Height, APIC::Idle, GraphicalUserInterface::Rect::Left, Video::PCScreenFont2, Recovery::RebootCommandWrapper(), Recovery::RecoveryThreadWrapper(), Tasking::TCB::Rename(), GraphicalUserInterface::WidgetCollection::ReplaceFont(), Recovery::ShutdownCommandWrapper(), TaskManager, GraphicalUserInterface::Rect::Top, Recovery::wdgDbgWin, and GraphicalUserInterface::Rect::Width.
~KernelRecovery()
Recovery::KernelRecovery::~KernelRecovery ()
Definition at line 363 of file RecoveryMain.cpp.
     {
         debug("Destructor called");
         TaskManager->KillThread(guiThread, 0);
         TaskManager->KillThread(recoveryThread, 0);
         delete gui, gui = nullptr;
     }
References debug, Recovery::gui, Tasking::Task::KillThread(), and TaskManager.
Member Function Documentation
RecoveryThread()
void Recovery::KernelRecovery::RecoveryThread ()
Definition at line 195 of file RecoveryMain.cpp.
     {
         while (wdgDbgWin == nullptr || DbgWin == nullptr)
             TaskManager->Sleep(100);
         wdgDbgWin->CreateLabel({5, 0, 0, 0}, "Scheduler Ticks  /  Last Task Ticks");
         GraphicalUserInterface::Handle SchedLblHnd = wdgDbgWin->CreateLabel({5, 15, 0, 0}, "0000000000000000 / 0000000000000000");
         wdgDbgWin->CreateLabel({5, 40, 0, 0}, "Memory Usage");
         GraphicalUserInterface::Handle MemLblHnd = wdgDbgWin->CreateLabel({5, 55, 0, 0}, "0MB / 0GB (0MB reserved) 0% (0000000000000000 bytes allocated)");
 #ifdef DEBUG
         wdgDbgWin->CreateLabel({5, 95, 0, 0}, "GUI Info");
         wdgDbgWin->CreateLabel({5, 110, 0, 0}, "  Fetch Inputs   /  Paint Desktop   / Paint Widgets");
         GraphicalUserInterface::Handle GUI1LblHnd = wdgDbgWin->CreateLabel({5, 125, 0, 0}, "0000000000000000 / 0000000000000000 / 0000000000000000");
         wdgDbgWin->CreateLabel({5, 140, 0, 0}, "  Paint Windows  /   Paint Cursor   / Memset & Update");
         GraphicalUserInterface::Handle GUI2LblHnd = wdgDbgWin->CreateLabel({5, 155, 0, 0}, "0000000000000000 / 0000000000000000 / 0000000000000000");
 #endif
         wdgDbgWin->CreateLabel({5, 195, 0, 0}, "Audio");
         wdgDbgWin->CreateButton({5, 210, 85, 15}, "Play Audio", (uintptr_t)PlayAudioWrapper);
         wdgDbgWin->CreateLabel({5, 235, 0, 0}, "Sample Rate");
         wdgDbgWin->CreateButton({5, 250, 45, 15}, "8000", (uintptr_t)CSR8000);
         wdgDbgWin->CreateButton({55, 250, 45, 15}, "11025", (uintptr_t)CSR11025);
         wdgDbgWin->CreateButton({105, 250, 45, 15}, "16000", (uintptr_t)CSR16000);
         wdgDbgWin->CreateButton({155, 250, 45, 15}, "22050", (uintptr_t)CSR22050);
         wdgDbgWin->CreateButton({205, 250, 45, 15}, "32000", (uintptr_t)CSR32000);
         wdgDbgWin->CreateButton({255, 250, 45, 15}, "44100", (uintptr_t)CSR44100);
         wdgDbgWin->CreateButton({305, 250, 45, 15}, "48000", (uintptr_t)CSR48000);
         wdgDbgWin->CreateButton({355, 250, 45, 15}, "88200", (uintptr_t)CSR88200);
         wdgDbgWin->CreateButton({405, 250, 45, 15}, "96000", (uintptr_t)CSR96000);
         wdgDbgWin->CreateLabel({5, 265, 0, 0}, "Volume");
         wdgDbgWin->CreateButton({5, 280, 25, 15}, "0%", (uintptr_t)CV0);
         wdgDbgWin->CreateButton({35, 280, 25, 15}, "10%", (uintptr_t)CV10);
         wdgDbgWin->CreateButton({65, 280, 25, 15}, "20%", (uintptr_t)CV20);
         wdgDbgWin->CreateButton({95, 280, 25, 15}, "30%", (uintptr_t)CV30);
         wdgDbgWin->CreateButton({125, 280, 25, 15}, "40%", (uintptr_t)CV40);
         wdgDbgWin->CreateButton({155, 280, 25, 15}, "50%", (uintptr_t)CV50);
         wdgDbgWin->CreateButton({185, 280, 25, 15}, "60%", (uintptr_t)CV60);
         wdgDbgWin->CreateButton({215, 280, 25, 15}, "70%", (uintptr_t)CV70);
         wdgDbgWin->CreateButton({245, 280, 25, 15}, "80%", (uintptr_t)CV80);
         wdgDbgWin->CreateButton({275, 280, 25, 15}, "90%", (uintptr_t)CV90);
         wdgDbgWin->CreateButton({305, 280, 25, 15}, "100%", (uintptr_t)CV100);
         GraphicalUserInterface::Handle wdgDbgCurrentAudioLbl = wdgDbgWin->CreateLabel({5, 295, 0, 0}, "Current Audio: ");
         // wdgDbgWin->CreateButton({5, 310, 85, 15}, "dev_connected.mp3", (uintptr_t)audio_dev_connected);
         // wdgDbgWin->CreateButton({95, 310, 85, 15}, "dev_disconnected.mp3", (uintptr_t)audio_dev_disconnected);
         // wdgDbgWin->CreateButton({185, 310, 85, 15}, "dev_error.mp3", (uintptr_t)audio_dev_error);
         // wdgDbgWin->CreateButton({275, 310, 85, 15}, "error.mp3", (uintptr_t)audio_error);
         // wdgDbgWin->CreateButton({365, 310, 85, 15}, "notification.mp3", (uintptr_t)audio_notification);
         // wdgDbgWin->CreateButton({455, 310, 85, 15}, "warning.mp3", (uintptr_t)audio_warning);
         wdgDbgWin->CreateLabel({5, 325, 0, 0}, "Display Brightness");
         wdgDbgWin->CreateButton({5, 340, 25, 15}, "10%", (uintptr_t)BufBight10);
         wdgDbgWin->CreateButton({35, 340, 25, 15}, "20%", (uintptr_t)BufBight20);
         wdgDbgWin->CreateButton({65, 340, 25, 15}, "30%", (uintptr_t)BufBight30);
         wdgDbgWin->CreateButton({95, 340, 25, 15}, "40%", (uintptr_t)BufBight40);
         wdgDbgWin->CreateButton({125, 340, 25, 15}, "50%", (uintptr_t)BufBight50);
         wdgDbgWin->CreateButton({155, 340, 25, 15}, "60%", (uintptr_t)BufBight60);
         wdgDbgWin->CreateButton({185, 340, 25, 15}, "70%", (uintptr_t)BufBight70);
         wdgDbgWin->CreateButton({215, 340, 25, 15}, "80%", (uintptr_t)BufBight80);
         wdgDbgWin->CreateButton({245, 340, 25, 15}, "90%", (uintptr_t)BufBight90);
         wdgDbgWin->CreateButton({275, 340, 25, 15}, "100%", (uintptr_t)BufBight100);
         GraphicalUserInterface::Handle wdgDbgCurrentCPUSchedCoreLbl = wdgDbgWin->CreateLabel({5, 355, 0, 0}, "CPU Scheduled Core: Unknown");
         DbgWin->AddWidget(wdgDbgWin);
         char TicksText[128];
         uint64_t MemUsed = 0;
         uint64_t MemTotal = 0;
         uint64_t MemReserved = 0;
         while (true)
         {
             sprintf(TicksText, "%016lld / %016lld", TaskManager->GetSchedulerTicks(), TaskManager->GetLastTaskTicks());
             wdgDbgWin->SetText(SchedLblHnd, TicksText);
             sprintf(TicksText, "CPU Scheduled Core: %lld", TaskManager->GetLastCore());
             wdgDbgWin->SetText(wdgDbgCurrentCPUSchedCoreLbl, TicksText);
             static int RefreshMemCounter = 0;
             if (RefreshMemCounter-- == 0)
             {
                 MemUsed = KernelAllocator.GetUsedMemory();
                 MemTotal = KernelAllocator.GetTotalMemory();
                 MemReserved = KernelAllocator.GetReservedMemory();
                 uint64_t MemPercent = (MemUsed * 100) / MemTotal;
                 sprintf(TicksText, "%lldMB / %lldGB (%lldMB reserved) %lld%% (%lld bytes allocated)", TO_MB(MemUsed), TO_GB(MemTotal), TO_MB(MemReserved), MemPercent, MemUsed);
                 wdgDbgWin->SetText(MemLblHnd, TicksText);
                 RefreshMemCounter = 25;
             }
             sprintf(TicksText, "Debug - %ldx%ld", DbgWin->GetPosition().Width, DbgWin->GetPosition().Height);
             DbgWin->SetTitle(TicksText);
             sprintf(TicksText, "Current Audio: %s", AudioFile);
             wdgDbgWin->SetText(wdgDbgCurrentAudioLbl, TicksText);
 #ifdef DEBUG
             static int RefreshGUIDbgCounter = 0;
             if (RefreshGUIDbgCounter-- == 0)
             {
                 sprintf(TicksText, "%016lld / %016lld / %016lld", FIi, PDi, PWi);
                 wdgDbgWin->SetText(GUI1LblHnd, TicksText);
                 sprintf(TicksText, "%016lld / %016lld / %016lld", PWWi, PCi, mmi);
                 wdgDbgWin->SetText(GUI2LblHnd, TicksText);
                 RefreshGUIDbgCounter = 5;
             }
 #endif
             TaskManager->Sleep(100);
         }
     }
References GraphicalUserInterface::Window::AddWidget(), Recovery::AudioFile, Recovery::BufBight10(), Recovery::BufBight100(), Recovery::BufBight20(), Recovery::BufBight30(), Recovery::BufBight40(), Recovery::BufBight50(), Recovery::BufBight60(), Recovery::BufBight70(), Recovery::BufBight80(), Recovery::BufBight90(), GraphicalUserInterface::WidgetCollection::CreateButton(), GraphicalUserInterface::WidgetCollection::CreateLabel(), Recovery::CSR11025(), Recovery::CSR16000(), Recovery::CSR22050(), Recovery::CSR32000(), Recovery::CSR44100(), Recovery::CSR48000(), Recovery::CSR8000(), Recovery::CSR88200(), Recovery::CSR96000(), Recovery::CV0(), Recovery::CV10(), Recovery::CV100(), Recovery::CV20(), Recovery::CV30(), Recovery::CV40(), Recovery::CV50(), Recovery::CV60(), Recovery::CV70(), Recovery::CV80(), Recovery::CV90(), Recovery::DbgWin, Tasking::Task::GetLastCore(), Tasking::Task::GetLastTaskTicks(), GraphicalUserInterface::Window::GetPosition(), Tasking::Task::GetSchedulerTicks(), GraphicalUserInterface::Rect::Height, KernelAllocator, Recovery::PlayAudioWrapper(), GraphicalUserInterface::WidgetCollection::SetText(), GraphicalUserInterface::Window::SetTitle(), Tasking::Task::Sleep(), sprintf(), TaskManager, Recovery::wdgDbgWin, and GraphicalUserInterface::Rect::Width.
Referenced by Recovery::RecoveryThreadWrapper().
Field Documentation
guiThread
Tasking::TCB* Recovery::KernelRecovery::guiThread private
Definition at line 31 of file recovery.hpp.
mem
Memory::MemMgr* Recovery::KernelRecovery::mem private
Definition at line 30 of file recovery.hpp.
recoveryThread
Tasking::TCB* Recovery::KernelRecovery::recoveryThread private
Definition at line 32 of file recovery.hpp.
The documentation for this class was generated from the following files:
Kernel/include/recovery.hpp
Kernel/Recovery/RecoveryMain.cpp