Fennix: CPU::MemBar Namespace Reference
CPU::MemBar Namespace Reference
Functions
static __no_stack_protector void Barrier ()
static __no_stack_protector void Fence ()
static __no_stack_protector void StoreFence ()
static __no_stack_protector void LoadFence ()
Function Documentation
Barrier()
static __no_stack_protector void CPU::MemBar::Barrier () inline static
Definition at line 216 of file cpu.hpp.
         {
 #if defined(__amd64__) || defined(__i386__)
             asmv("" ::
                      : "memory");
 #elif defined(__aarch64__)
             asmv("dmb ish" ::
                      : "memory");
 #endif
         }
References asmv.
Referenced by APIC::APIC::IORead(), APIC::APIC::IOWrite(), APIC::APIC::Read(), and APIC::APIC::Write().
Fence()
static __no_stack_protector void CPU::MemBar::Fence () inline static
Definition at line 227 of file cpu.hpp.
         {
 #if defined(__amd64__) || defined(__i386__)
             asmv("mfence" ::
                      : "memory");
 #elif defined(__aarch64__)
             asmv("dmb ish" ::
                      : "memory");
 #endif
         }
References asmv.
LoadFence()
static __no_stack_protector void CPU::MemBar::LoadFence () inline static
Definition at line 249 of file cpu.hpp.
         {
 #if defined(__amd64__) || defined(__i386__)
             asmv("lfence" ::
                      : "memory");
 #elif defined(__aarch64__)
             asmv("dmb ishld" ::
                      : "memory");
 #endif
         }
References asmv.
StoreFence()
static __no_stack_protector void CPU::MemBar::StoreFence () inline static
Definition at line 238 of file cpu.hpp.
         {
 #if defined(__amd64__) || defined(__i386__)
             asmv("sfence" ::
                      : "memory");
 #elif defined(__aarch64__)
             asmv("dmb ishst" ::
                      : "memory");
 #endif
         }
References asmv.