Fennix: ObjectRepository Struct Reference
ObjectRepository Struct Reference
#include <linker.hpp>
Public Member Functions
ObjectRepository ()
ObjectRepository (const ObjectRepository &)=delete
ObjectRepository & operator= (const ObjectRepository &)=delete
SharedObject * injectObjectFromDts (frg::string_view name, frg::string< MemoryAllocator > path, uintptr_t base_address, Elf64_Dyn *dynamic, uint64_t rts)
SharedObject * injectObjectFromPhdrs (frg::string_view name, frg::string< MemoryAllocator > path, void *phdr_pointer, size_t phdr_entry_size, size_t num_phdrs, void *entry_pointer, uint64_t rts)
SharedObject * injectStaticObject (frg::string_view name, frg::string< MemoryAllocator > path, void *phdr_pointer, size_t phdr_entry_size, size_t num_phdrs, void *entry_pointer, uint64_t rts)
SharedObject * requestObjectWithName (frg::string_view name, SharedObject *origin, Scope *localScope, bool createScope, uint64_t rts)
SharedObject * requestObjectAtPath (frg::string_view path, Scope *localScope, bool createScope, uint64_t rts)
SharedObject * findCaller (void *address)
SharedObject * findLoadedObject (frg::string_view name)
Data Fields
frg::vector< SharedObject *, MemoryAllocator > loadedObjects
Private Member Functions
void _fetchFromPhdrs (SharedObject *object, void *phdr_pointer, size_t phdr_entry_size, size_t num_phdrs, void *entry_pointer)
void _fetchFromFile (SharedObject *object, int fd)
void _parseDynamic (SharedObject *object)
void _discoverDependencies (SharedObject *object, Scope *localScope, uint64_t rts)
void _addLoadedObject (SharedObject *object)
Private Attributes
frg::hash_map< frg::string_view, SharedObject *, frg::hash< frg::string_view >, MemoryAllocator > _nameMap
Detailed Description
Definition at line 26 of file linker.hpp.
Constructor & Destructor Documentation
ObjectRepository() [1/2]
ObjectRepository::ObjectRepository ()
Definition at line 87 of file linker.cpp.
 : loadedObjects{getAllocator()},
     _nameMap{frg::hash<frg::string_view>{}, getAllocator()} {}
ObjectRepository() [2/2]
ObjectRepository::ObjectRepository (const ObjectRepository &) delete
Member Function Documentation
_addLoadedObject()
void ObjectRepository::_addLoadedObject (SharedObject * object) private
Definition at line 720 of file linker.cpp.
{
     _nameMap.insert(object->name, object);
     loadedObjects.push_back(object);
 }
References _nameMap, loadedObjects, and SharedObject::name.
Referenced by injectObjectFromDts(), injectObjectFromPhdrs(), injectStaticObject(), requestObjectAtPath(), and requestObjectWithName().
_discoverDependencies()
void ObjectRepository::_discoverDependencies (SharedObject * object, Scope * localScope, uint64_t rts) private
Definition at line 701 of file linker.cpp.
{
     // Load required dynamic libraries.
     for(size_t i = 0; object->dynamic[i].d_tag != DT_NULL; i++) {
         Elf64_Dyn *dynamic = &object->dynamic[i];
         if(dynamic->d_tag != DT_NEEDED)
             continue;
         const char *library_str = (const char *)(object->baseAddress
                 + object->stringTableOffset + dynamic->d_un.d_val);
         auto library = requestObjectWithName(frg::string_view{library_str},
                 object, localScope, false, rts);
         if(!library)
             mlibc::panicLogger() << "Could not satisfy dependency " << library_str << frg::endlog;
         object->dependencies.push(library);
     }
 }
References SharedObject::baseAddress, DT_NEEDED, DT_NULL, dynamic, i, mlibc::panicLogger, requestObjectWithName(), and SharedObject::stringTableOffset.
Referenced by injectObjectFromDts(), injectObjectFromPhdrs(), requestObjectAtPath(), and requestObjectWithName().
_fetchFromFile()
void ObjectRepository::_fetchFromFile (SharedObject * object, int fd) private
Definition at line 395 of file linker.cpp.
{
     __ensure(!object->isMainObject);
     // read the elf file header
     Elf64_Ehdr ehdr;
     readExactlyOrDie(fd, &ehdr, sizeof(Elf64_Ehdr));
     __ensure(ehdr.e_ident[0] == 0x7F
             && ehdr.e_ident[1] == 'E'
             && ehdr.e_ident[2] == 'L'
             && ehdr.e_ident[3] == 'F');
     __ensure(ehdr.e_type == ET_EXEC || ehdr.e_type == ET_DYN);
     // read the elf program headers
     auto phdr_buffer = (char *)getAllocator().allocate(ehdr.e_phnum * ehdr.e_phentsize);
     seekOrDie(fd, ehdr.e_phoff);
     readExactlyOrDie(fd, phdr_buffer, ehdr.e_phnum * ehdr.e_phentsize);
     object->phdrPointer = phdr_buffer;
     object->phdrCount = ehdr.e_phnum;
     object->phdrEntrySize = ehdr.e_phentsize;
     // Allocate virtual address space for the DSO.
     constexpr size_t hugeSize = 0x200000;
     uintptr_t highest_address = 0;
     for(int i = 0; i < ehdr.e_phnum; i++) {
         auto phdr = (Elf64_Phdr *)(phdr_buffer + i * ehdr.e_phentsize);
         if(phdr->p_type != PT_LOAD)
             continue;
         auto limit = phdr->p_vaddr + phdr->p_memsz;
         if(limit > highest_address)
             highest_address = limit;
     }
     __ensure(!(object->baseAddress & (hugeSize - 1)));
 #if MLIBC_MMAP_ALLOCATE_DSO
     void *mappedAddr = nullptr;
     if (mlibc::sys_vm_map(nullptr,
             highest_address - object->baseAddress, PROT_NONE,
             MAP_PRIVATE | MAP_ANONYMOUS, -1, 0, &mappedAddr)) {
         mlibc::panicLogger() << "sys_vm_map failed when allocating address space for DSO \""
                 << object->name << "\""
                 << ", base " << (void *)object->baseAddress
                 << ", requested " << (highest_address - object->baseAddress) << " bytes"
                 << frg::endlog;
     }
     object->baseAddress = reinterpret_cast<uintptr_t>(mappedAddr);
 #else
     object->baseAddress = libraryBase;
     libraryBase += (highest_address + (hugeSize - 1)) & ~(hugeSize - 1);
 #endif
     if(verbose || logBaseAddresses)
         mlibc::infoLogger() << "rtdl: Loading " << object->name
                 << " at " << (void *)object->baseAddress << frg::endlog;
     // Load all segments.
     constexpr size_t pageSize = 0x1000;
     for(int i = 0; i < ehdr.e_phnum; i++) {
         auto phdr = (Elf64_Phdr *)(phdr_buffer + i * ehdr.e_phentsize);
         if(phdr->p_type == PT_LOAD) {
             size_t misalign = phdr->p_vaddr & (pageSize - 1);
             __ensure(phdr->p_memsz > 0);
             __ensure(phdr->p_memsz >= phdr->p_filesz);
             // If the following condition is violated, we cannot use mmap() the segment;
             // however, GCC only generates ELF files that satisfy this.
             __ensure(misalign == (phdr->p_offset & (pageSize - 1)));
             auto map_address = object->baseAddress + phdr->p_vaddr - misalign;
             auto backed_map_size = (phdr->p_filesz + misalign + pageSize - 1) & ~(pageSize - 1);
             auto total_map_size = (phdr->p_memsz + misalign + pageSize - 1) & ~(pageSize - 1);
             int prot = 0;
             if(phdr->p_flags & PF_R)
                 prot |= PROT_READ;
             if(phdr->p_flags & PF_W)
                 prot |= PROT_WRITE;
             if(phdr->p_flags & PF_X)
                 prot |= PROT_EXEC;
             #if MLIBC_MAP_DSO_SEGMENTS
                 void *map_pointer;
                 if(mlibc::sys_vm_map(reinterpret_cast<void *>(map_address),
                         backed_map_size, prot | PROT_WRITE,
                         MAP_PRIVATE | MAP_FIXED, fd, phdr->p_offset - misalign, &map_pointer))
                     __ensure(!"sys_vm_map failed");
                 if(total_map_size > backed_map_size)
                     if(mlibc::sys_vm_map(reinterpret_cast<void *>(map_address + backed_map_size),
                             total_map_size - backed_map_size, prot | PROT_WRITE,
                             MAP_PRIVATE | MAP_FIXED | MAP_ANONYMOUS, -1, 0, &map_pointer))
                         __ensure(!"sys_vm_map failed");
                 if(mlibc::sys_vm_readahead)
                     if(mlibc::sys_vm_readahead(reinterpret_cast<void *>(map_address),
                             backed_map_size))
                         mlibc::infoLogger() << "mlibc: sys_vm_readahead() failed in ld.so"
                                 << frg::endlog;
                 // Clear the trailing area at the end of the backed mapping.
                 // We do not clear the leading area; programs are not supposed to access it.
                 memset(reinterpret_cast<void *>(map_address + misalign + phdr->p_filesz),
                         0, phdr->p_memsz - phdr->p_filesz);
             #else
                 (void)backed_map_size;
                 void *map_pointer;
                 if(mlibc::sys_vm_map(reinterpret_cast<void *>(map_address),
                         total_map_size, prot | PROT_WRITE,
                         MAP_PRIVATE | MAP_FIXED | MAP_ANONYMOUS, -1, 0, &map_pointer))
                     __ensure(!"sys_vm_map failed");
                 seekOrDie(fd, phdr->p_offset);
                 readExactlyOrDie(fd, reinterpret_cast<char *>(map_address) + misalign,
                         phdr->p_filesz);
             #endif
             // Take care of removing superfluous permissions.
             if(mlibc::sys_vm_protect && ((prot & PROT_WRITE) == 0))
                 if(mlibc::sys_vm_protect(map_pointer, total_map_size, prot))
                     mlibc::infoLogger() << "mlibc: sys_vm_protect() failed in ld.so" << frg::endlog;
         }else if(phdr->p_type == PT_TLS) {
             object->tlsSegmentSize = phdr->p_memsz;
             object->tlsAlignment = phdr->p_align;
             object->tlsImageSize = phdr->p_filesz;
             object->tlsImagePtr = (void *)(object->baseAddress + phdr->p_vaddr);
         }else if(phdr->p_type == PT_DYNAMIC) {
             object->dynamic = (Elf64_Dyn *)(object->baseAddress + phdr->p_vaddr);
         }else if(phdr->p_type == PT_INTERP
                 || phdr->p_type == PT_PHDR
                 || phdr->p_type == PT_NOTE
                 || phdr->p_type == PT_RISCV_ATTRIBUTES
                 || phdr->p_type == PT_GNU_EH_FRAME
                 || phdr->p_type == PT_GNU_RELRO
                 || phdr->p_type == PT_GNU_STACK
                 || phdr->p_type == PT_GNU_PROPERTY) {
             // ignore the phdr
         }else{
             mlibc::panicLogger() << "Unexpected PHDR type 0x"
                     << frg::hex_fmt(phdr->p_type) << " in DSO " << object->name << frg::endlog;
         }
     }
 }
References __ensure, SharedObject::baseAddress, Elf64_Ehdr::e_ident, Elf64_Ehdr::e_phentsize, Elf64_Ehdr::e_phnum, Elf64_Ehdr::e_phoff, Elf64_Ehdr::e_type, ET_DYN, ET_EXEC, fd, getAllocator(), i, mlibc::infoLogger, SharedObject::isMainObject, libraryBase, logBaseAddresses, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, memset, mlibc::panicLogger, PF_R, PF_W, PF_X, mlibc::prot, PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE, PT_DYNAMIC, PT_GNU_EH_FRAME, PT_GNU_PROPERTY, PT_GNU_RELRO, PT_GNU_STACK, PT_INTERP, PT_LOAD, PT_NOTE, PT_PHDR, PT_RISCV_ATTRIBUTES, PT_TLS, readExactlyOrDie(), seekOrDie(), mlibc::sys_vm_map(), mlibc::sys_vm_protect(), mlibc::sys_vm_readahead(), verbose, and Driver::void().
Referenced by requestObjectAtPath(), and requestObjectWithName().
_fetchFromPhdrs()
void ObjectRepository::_fetchFromPhdrs (SharedObject * object, void * phdr_pointer, size_t phdr_entry_size, size_t num_phdrs, void * entry_pointer) private
Definition at line 340 of file linker.cpp.
{
     __ensure(object->isMainObject);
     object->phdrPointer = phdr_pointer;
     object->phdrEntrySize = phdr_entry_size;
     object->phdrCount = phdr_count;
     if(verbose)
         mlibc::infoLogger() << "rtdl: Loading " << object->name << frg::endlog;
     // Note: the entry pointer is absolute and not relative to the base address.
     object->entry = entry_pointer;
     frg::optional<ptrdiff_t> dynamic_offset;
     frg::optional<ptrdiff_t> tls_offset;
     // segments are already mapped, so we just have to find the dynamic section
     for(size_t i = 0; i < phdr_count; i++) {
         auto phdr = (Elf64_Phdr *)((uintptr_t)phdr_pointer + i * phdr_entry_size);
         switch(phdr->p_type) {
         case PT_PHDR:
             // Determine the executable's base address (in the PIE case) by comparing
             // the PHDR segment's load address against it's address in the ELF file.
             object->baseAddress = reinterpret_cast<uintptr_t>(phdr_pointer) - phdr->p_vaddr;
             if(verbose)
                 mlibc::infoLogger() << "rtdl: Executable is loaded at "
                         << (void *)object->baseAddress << frg::endlog;
             break;
         case PT_DYNAMIC:
             dynamic_offset = phdr->p_vaddr;
             break;
         case PT_TLS: {
             object->tlsSegmentSize = phdr->p_memsz;
             object->tlsAlignment = phdr->p_align;
             object->tlsImageSize = phdr->p_filesz;
             tls_offset = phdr->p_vaddr;
             break;
         case PT_INTERP:
             object->interpreterPath = frg::string<MemoryAllocator>{
                 (char*)(object->baseAddress + phdr->p_vaddr),
                     getAllocator()
             };
         } break;
         default:
             //FIXME warn about unknown phdrs
             break;
         }
     }
     if(dynamic_offset)
         object->dynamic = (Elf64_Dyn *)(object->baseAddress + *dynamic_offset);
     if(tls_offset)
         object->tlsImagePtr = (void *)(object->baseAddress + *tls_offset);
 }
References __ensure, SharedObject::baseAddress, getAllocator(), i, mlibc::infoLogger, SharedObject::interpreterPath, SharedObject::isMainObject, PT_DYNAMIC, PT_INTERP, PT_PHDR, PT_TLS, SharedObject::tlsAlignment, SharedObject::tlsImageSize, SharedObject::tlsSegmentSize, and verbose.
Referenced by injectObjectFromPhdrs(), and injectStaticObject().
_parseDynamic()
void ObjectRepository::_parseDynamic (SharedObject * object) private
Definition at line 549 of file linker.cpp.
{
     if(!object->dynamic)
         mlibc::infoLogger() << "ldso: Object '" << object->name
                 << "' does not have a dynamic section" << frg::endlog;
     __ensure(object->dynamic);
     // Fix up these offsets to addresses after the loop, since the
     // addresses depend on the value of DT_STRTAB.
     frg::optional<ptrdiff_t> runpath_offset;
     frg::optional<ptrdiff_t> soname_offset;
     for(size_t i = 0; object->dynamic[i].d_tag != DT_NULL; i++) {
         Elf64_Dyn *dynamic = &object->dynamic[i];
         switch(dynamic->d_tag) {
         // handle hash table, symbol table and string table
         case DT_HASH:
             object->hashStyle = HashStyle::systemV;
             object->hashTableOffset = dynamic->d_un.d_ptr;
             break;
         case DT_GNU_HASH:
             object->hashStyle = HashStyle::gnu;
             object->hashTableOffset = dynamic->d_un.d_ptr;
             break;
         case DT_STRTAB:
             object->stringTableOffset = dynamic->d_un.d_ptr;
             break;
         case DT_STRSZ:
             break; // we don't need the size of the string table
         case DT_SYMTAB:
             object->symbolTableOffset = dynamic->d_un.d_ptr;
             break;
         case DT_SYMENT:
             __ensure(dynamic->d_un.d_val == sizeof(Elf64_Sym));
             break;
         // handle lazy relocation table
         case DT_PLTGOT:
             object->globalOffsetTable = (void **)(object->baseAddress
                     + dynamic->d_un.d_ptr);
             break;
         case DT_JMPREL:
             object->lazyRelocTableOffset = dynamic->d_un.d_ptr;
             break;
         case DT_PLTRELSZ:
             object->lazyTableSize = dynamic->d_un.d_val;
             break;
         case DT_PLTREL:
             if(dynamic->d_un.d_val == DT_RELA) {
                 object->lazyExplicitAddend = true;
             }else{
                 __ensure(dynamic->d_un.d_val == DT_REL);
             }
             break;
         // TODO: Implement this correctly!
         case DT_SYMBOLIC:
             object->symbolicResolution = true;
             break;
         case DT_BIND_NOW:
             object->eagerBinding = true;
             break;
         case DT_FLAGS: {
             if(dynamic->d_un.d_val & DF_SYMBOLIC)
                 object->symbolicResolution = true;
             if(dynamic->d_un.d_val & DF_STATIC_TLS)
                 object->haveStaticTls = true;
             if(dynamic->d_un.d_val & DF_BIND_NOW)
                 object->eagerBinding = true;
             auto ignored = DF_BIND_NOW | DF_SYMBOLIC | DF_STATIC_TLS;
 #ifdef __riscv
             // Work around https://sourceware.org/bugzilla/show_bug.cgi?id=24673.
             ignored |= DF_TEXTREL;
 #endif
             if(dynamic->d_un.d_val & ~ignored)
                 mlibc::infoLogger() << "\e[31mrtdl: DT_FLAGS(" << frg::hex_fmt{dynamic->d_un.d_val & ~ignored}
                         << ") is not implemented correctly!\e[39m"
                         << frg::endlog;
         } break;
         case DT_FLAGS_1:
             if(dynamic->d_un.d_val & DF_1_NOW)
                 object->eagerBinding = true;
             // The DF_1_PIE flag is informational only. It is used by e.g file(1).
             // The DF_1_NODELETE flag has a similar effect to RTLD_NODELETE, both of which we
             // ignore because we don't implement dlclose().
             if(dynamic->d_un.d_val & ~(DF_1_NOW | DF_1_PIE | DF_1_NODELETE))
                 mlibc::infoLogger() << "\e[31mrtdl: DT_FLAGS_1(" << frg::hex_fmt{dynamic->d_un.d_val}
                         << ") is not implemented correctly!\e[39m"
                         << frg::endlog;
             break;
         case DT_RPATH:
             mlibc::infoLogger() << "\e[31mrtdl: RUNPATH not preferred over RPATH properly\e[39m" << frg::endlog;
             [[fallthrough]];
         case DT_RUNPATH:
             runpath_offset = dynamic->d_un.d_val;
             break;
         case DT_INIT:
             if(dynamic->d_un.d_ptr != 0)
                 object->initPtr = (InitFuncPtr)(object->baseAddress + dynamic->d_un.d_ptr);
             break;
         case DT_INIT_ARRAY:
             if(dynamic->d_un.d_ptr != 0)
                 object->initArray = (InitFuncPtr *)(object->baseAddress + dynamic->d_un.d_ptr);
             break;
         case DT_INIT_ARRAYSZ:
             object->initArraySize = dynamic->d_un.d_val;
             break;
         case DT_PREINIT_ARRAY:
             if(dynamic->d_un.d_ptr != 0) {
                 // Only the main object is allowed pre-initializers.
                 __ensure(object->isMainObject);
                 object->preInitArray = (InitFuncPtr *)(object->baseAddress + dynamic->d_un.d_ptr);
             }
             break;
         case DT_PREINIT_ARRAYSZ:
             // Only the main object is allowed pre-initializers.
             __ensure(object->isMainObject);
             object->preInitArraySize = dynamic->d_un.d_val;
             break;
         case DT_DEBUG:
             dynamic->d_un.d_val = reinterpret_cast<Elf64_Xword>(&globalDebugInterface);
             break;
         case DT_SONAME:
             soname_offset = dynamic->d_un.d_val;
             break;
         // ignore unimportant tags
         case DT_NEEDED: // we handle this later
         case DT_FINI: case DT_FINI_ARRAY: case DT_FINI_ARRAYSZ:
         case DT_RELA: case DT_RELASZ: case DT_RELAENT: case DT_RELACOUNT:
         case DT_VERSYM:
         case DT_VERDEF: case DT_VERDEFNUM:
         case DT_VERNEED: case DT_VERNEEDNUM:
 #ifdef __riscv
         case DT_TEXTREL: // Work around https://sourceware.org/bugzilla/show_bug.cgi?id=24673.
 #endif
             break;
         case DT_TLSDESC_PLT: case DT_TLSDESC_GOT:
             break;
         default:
             mlibc::panicLogger() << "Unexpected dynamic entry "
                     << (void *)dynamic->d_tag << " in object" << frg::endlog;
         }
     }
     if(runpath_offset) {
         object->runPath = reinterpret_cast<const char *>(object->baseAddress
                 + object->stringTableOffset + *runpath_offset);
     }
     if(soname_offset) {
         object->soName = reinterpret_cast<const char *>(object->baseAddress
                 + object->stringTableOffset + *soname_offset);
     }
 }
References __ensure, SharedObject::baseAddress, DF_1_NODELETE, DF_1_NOW, DF_1_PIE, DF_BIND_NOW, DF_STATIC_TLS, DF_SYMBOLIC, DF_TEXTREL, DT_BIND_NOW, DT_DEBUG, DT_FINI, DT_FINI_ARRAY, DT_FINI_ARRAYSZ, DT_FLAGS, DT_FLAGS_1, DT_GNU_HASH, DT_HASH, DT_INIT, DT_INIT_ARRAY, DT_INIT_ARRAYSZ, DT_JMPREL, DT_NEEDED, DT_NULL, DT_PLTGOT, DT_PLTREL, DT_PLTRELSZ, DT_PREINIT_ARRAY, DT_PREINIT_ARRAYSZ, DT_REL, DT_RELA, DT_RELACOUNT, DT_RELAENT, DT_RELASZ, DT_RPATH, DT_RUNPATH, DT_SONAME, DT_STRSZ, DT_STRTAB, DT_SYMBOLIC, DT_SYMENT, DT_SYMTAB, DT_TEXTREL, DT_TLSDESC_GOT, DT_TLSDESC_PLT, DT_VERDEF, DT_VERDEFNUM, DT_VERNEED, DT_VERNEEDNUM, DT_VERSYM, dynamic, SharedObject::dynamic, globalDebugInterface, gnu, i, mlibc::infoLogger, SharedObject::isMainObject, mlibc::panicLogger, and systemV.
Referenced by injectObjectFromDts(), injectObjectFromPhdrs(), requestObjectAtPath(), and requestObjectWithName().
findCaller()
SharedObject * ObjectRepository::findCaller (void * address)
Definition at line 302 of file linker.cpp.
{
     uintptr_t target = reinterpret_cast<uintptr_t>(addr);
     for (auto [name, object] : _nameMap) {
         // Search all PT_LOAD segments for the specified address.
         for(size_t j = 0; j < object->phdrCount; j++) {
             auto phdr = (Elf64_Phdr *)((uintptr_t)object->phdrPointer + j * object->phdrEntrySize);
             if (phdr->p_type == PT_LOAD) {
                 uintptr_t start = object->baseAddress + phdr->p_vaddr;
                 uintptr_t end = start + phdr->p_memsz;
                 if (start <= target && target < end)
                     return object;
             }
         }
     }
     return nullptr;
 }
References _nameMap, addr, SharedObject::baseAddress, j, name, and PT_LOAD.
findLoadedObject()
SharedObject * ObjectRepository::findLoadedObject (frg::string_view name)
Definition at line 321 of file linker.cpp.
{
     auto it = _nameMap.get(name);
     if (it)
         return *it;
     for (auto object : loadedObjects) {
         // See if any object has a matching SONAME.
         if (object->soName && name == object->soName)
             return object;
     }
     // TODO: We should also look at the device and inode here as a fallback.
     return nullptr;
 }
References _nameMap, loadedObjects, and name.
Referenced by injectObjectFromDts(), injectObjectFromPhdrs(), injectStaticObject(), requestObjectAtPath(), and requestObjectWithName().
injectObjectFromDts()
SharedObject * ObjectRepository::injectObjectFromDts (frg::string_view name, frg::string< MemoryAllocator > path, uintptr_t base_address, Elf64_Dyn * dynamic, uint64_t rts)
Definition at line 91 of file linker.cpp.
{
     __ensure(!findLoadedObject(name));
     auto object = frg::construct<SharedObject>(getAllocator(),
         name.data(), std::move(path), false, globalScope.get(), rts);
     object->baseAddress = base_address;
     object->dynamic = dynamic;
     _parseDynamic(object);
     _addLoadedObject(object);
     _discoverDependencies(object, globalScope.get(), rts);
     return object;
 }
References __ensure, _addLoadedObject(), _discoverDependencies(), _parseDynamic(), dynamic, findLoadedObject(), getAllocator(), globalScope, and name.
injectObjectFromPhdrs()
SharedObject * ObjectRepository::injectObjectFromPhdrs (frg::string_view name, frg::string< MemoryAllocator > path, void * phdr_pointer, size_t phdr_entry_size, size_t num_phdrs, void * entry_pointer, uint64_t rts)
Definition at line 108 of file linker.cpp.
                       {
     __ensure(!findLoadedObject(name));
     auto object = frg::construct<SharedObject>(getAllocator(),
         name.data(), std::move(path), true, globalScope.get(), rts);
     _fetchFromPhdrs(object, phdr_pointer, phdr_entry_size, num_phdrs, entry_pointer);
     _parseDynamic(object);
     _addLoadedObject(object);
     _discoverDependencies(object, globalScope.get(), rts);
     return object;
 }
References __ensure, _addLoadedObject(), _discoverDependencies(), _fetchFromPhdrs(), _parseDynamic(), findLoadedObject(), getAllocator(), globalScope, and name.
injectStaticObject()
SharedObject * ObjectRepository::injectStaticObject (frg::string_view name, frg::string< MemoryAllocator > path, void * phdr_pointer, size_t phdr_entry_size, size_t num_phdrs, void * entry_pointer, uint64_t rts)
Definition at line 125 of file linker.cpp.
                       {
     __ensure(!findLoadedObject(name));
     auto object = frg::construct<SharedObject>(getAllocator(),
         name.data(), std::move(path), true, globalScope.get(), rts);
     _fetchFromPhdrs(object, phdr_pointer, phdr_entry_size, num_phdrs, entry_pointer);
 #if MLIBC_STATIC_BUILD
     object->initArray = reinterpret_cast<InitFuncPtr*>(__init_array_start);
     object->initArraySize = static_cast<size_t>((uintptr_t)__init_array_end -
             (uintptr_t)__init_array_start);
     object->preInitArray = reinterpret_cast<InitFuncPtr*>(__preinit_array_start);
     object->preInitArraySize = static_cast<size_t>((uintptr_t)__preinit_array_end -
             (uintptr_t)__preinit_array_start);
 #endif
     _addLoadedObject(object);
     return object;
 }
References __ensure, __init_array_end, __init_array_start, __preinit_array_end, __preinit_array_start, _addLoadedObject(), _fetchFromPhdrs(), findLoadedObject(), getAllocator(), globalScope, and name.
operator=()
ObjectRepository& ObjectRepository::operator= (const ObjectRepository &) delete
requestObjectAtPath()
SharedObject * ObjectRepository::requestObjectAtPath (frg::string_view path, Scope * localScope, bool createScope, uint64_t rts)
Definition at line 263 of file linker.cpp.
{
     // TODO: Support SONAME correctly.
     auto lastSlash = path.find_last('/') + 1;
     auto name = path;
     if (!lastSlash) {
         name = name.sub_string(lastSlash, path.size() - lastSlash);
     }
     if (auto obj = findLoadedObject(name))
         return obj;
     if (createScope) {
         __ensure(localScope == nullptr);
         // TODO: Free this when the scope is no longer needed.
         localScope = frg::construct<Scope>(getAllocator());
     }
     __ensure(localScope != nullptr);
     auto object = frg::construct<SharedObject>(getAllocator(),
         name.data(), path.data(), false, localScope, rts);
     frg::string<MemoryAllocator> no_prefix(getAllocator(), path);
     int fd;
     if(mlibc::sys_open((no_prefix + '\0').data(), O_RDONLY, 0, &fd))
         return nullptr; // TODO: Free the SharedObject.
     _fetchFromFile(object, fd);
     closeOrDie(fd);
     _parseDynamic(object);
     _addLoadedObject(object);
     _discoverDependencies(object, localScope, rts);
     return object;
 }
References __ensure, _addLoadedObject(), _discoverDependencies(), _fetchFromFile(), _parseDynamic(), closeOrDie(), fd, findLoadedObject(), getAllocator(), name, O_RDONLY, and mlibc::sys_open().
requestObjectWithName()
SharedObject * ObjectRepository::requestObjectWithName (frg::string_view name, SharedObject * origin, Scope * localScope, bool createScope, uint64_t rts)
Definition at line 148 of file linker.cpp.
{
     if (auto obj = findLoadedObject(name))
         return obj;
     const char *libdirs[4] = {
         "/lib/",
         "/lib64/",
         "/usr/lib/",
         "/usr/lib64/"
     };
     auto tryToOpen = [&] (const char *path) {
         int fd;
         if(auto x = mlibc::sys_open(path, O_RDONLY, 0, &fd); x) {
             return -1;
         }
         return fd;
     };
     // TODO(arsen): this process can probably undergo heavy optimization, by
     // preprocessing the rpath only once on parse
     auto processRpath = [&] (frg::string_view path) {
         frg::string<MemoryAllocator> sPath { getAllocator() };
         if (path.starts_with("$ORIGIN")) {
             frg::string_view dirname = origin->path;
             auto lastsl = dirname.find_last('/');
             if (lastsl != (uint64_t)-1) {
                 dirname = dirname.sub_string(0, lastsl);
             } else {
                 dirname = ".";
             }
             sPath = frg::string<MemoryAllocator>{ getAllocator(), dirname };
             sPath += path.sub_string(7, path.size() - 7);
         } else {
             sPath = frg::string<MemoryAllocator>{ getAllocator(), path };
         }
         if (sPath[sPath.size() - 1] != '/') {
             sPath += '/';
         }
         sPath += name;
         if (logRpath)
             mlibc::infoLogger() << "rtdl: trying in rpath " << sPath << frg::endlog;
         int fd = tryToOpen(sPath.data());
         if (logRpath && fd >= 0)
             mlibc::infoLogger() << "rtdl: found in rpath" << frg::endlog;
         return frg::tuple { fd, std::move(sPath) };
     };
     frg::string<MemoryAllocator> chosenPath { getAllocator() };
     int fd = -1;
     if (origin && origin->runPath) {
         size_t start = 0;
         size_t idx = 0;
         frg::string_view rpath { origin->runPath };
         auto next = [&] () {
             idx = rpath.find_first(':', start);
             if (idx == (size_t)-1)
                 idx = rpath.size();
         };
         for (next(); idx < rpath.size(); next()) {
             auto path = rpath.sub_string(start, idx - start);
             start = idx + 1;
             auto [fd_, fullPath] = processRpath(path);
             if (fd_ != -1) {
                 fd = fd_;
                 chosenPath = std::move(fullPath);
                 break;
             }
         }
         if (fd == -1) {
             auto path = rpath.sub_string(start, rpath.size() - start);
             auto [fd_, fullPath] = processRpath(path);
             if (fd_ != -1) {
                 fd = fd_;
                 chosenPath = std::move(fullPath);
             }
         }
     } else if (logRpath) {
         mlibc::infoLogger() << "rtdl: no rpath set for object" << frg::endlog;
     }
     for(int i = 0; i < 4 && fd == -1; i++) {
         auto path = frg::string<MemoryAllocator>{getAllocator(), libdirs[i]} + name + '\0';
         fd = tryToOpen(path.data());
         if(fd >= 0) {
             chosenPath = std::move(path);
             break;
         }
     }
     if(fd == -1)
         return nullptr;
     if (createScope) {
         __ensure(localScope == nullptr);
         // TODO: Free this when the scope is no longer needed.
         localScope = frg::construct<Scope>(getAllocator());
     }
     __ensure(localScope != nullptr);
     auto object = frg::construct<SharedObject>(getAllocator(),
         name.data(), std::move(chosenPath), false, localScope, rts);
     _fetchFromFile(object, fd);
     closeOrDie(fd);
     _parseDynamic(object);
     _addLoadedObject(object);
     _discoverDependencies(object, localScope, rts);
     return object;
 }
References __ensure, _addLoadedObject(), _discoverDependencies(), _fetchFromFile(), _parseDynamic(), closeOrDie(), dirname(), fd, findLoadedObject(), getAllocator(), i, mlibc::infoLogger, logRpath, name, O_RDONLY, SharedObject::path, SharedObject::runPath, mlibc::sys_open(), and x.
Referenced by _discoverDependencies().
Field Documentation
_nameMap
frg::hash_map<frg::string_view, SharedObject *, frg::hash<frg::string_view>, MemoryAllocator> ObjectRepository::_nameMap private
Definition at line 75 of file linker.hpp.
Referenced by _addLoadedObject(), findCaller(), and findLoadedObject().
loadedObjects
frg::vector<SharedObject *, MemoryAllocator> ObjectRepository::loadedObjects
Definition at line 60 of file linker.hpp.
Referenced by _addLoadedObject(), and findLoadedObject().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/rtdl/generic/linker.hpp
Userspace/mlibc/options/rtdl/generic/linker.cpp