Fennix: anonymous_namespace{search.cpp} Namespace Reference
anonymous_namespace{search.cpp} Namespace Reference
Functions
int height (struct node *node)
int rotate (struct node **nodep, int side)
int balance_tree (struct node **nodep)
Function Documentation
balance_tree()
int anonymous_namespace{search.cpp}::balance_tree (struct node ** nodep)
Definition at line 51 of file search.cpp.
{
         struct node *node = *nodep;
         int height_a = height(static_cast<struct node *>(node->a[0]));
         int height_b = height(static_cast<struct node *>(node->a[1]));
         if (height_a - height_b < 2) {
             int old = node->h;
             node->h = height_a < height_b ? height_b + 1 : height_a + 1;
             return node->h - old;
         }
         return rotate(nodep, height_a < height_b);
     }
References node::a, node::h, height, and rotate().
Referenced by tsearch().
height()
int anonymous_namespace{search.cpp}::height (struct node * node)
Definition at line 17 of file search.cpp.
{
         return node ? node->h : 0;
     }
References node::h.
rotate()
int anonymous_namespace{search.cpp}::rotate (struct node ** nodep, int side)
Definition at line 21 of file search.cpp.
{
         struct node *node = *nodep;
         struct node *x = static_cast<struct node *>(node->a[side]);
         struct node *y = static_cast<struct node *>(x->a[!side]);
         struct node *z = static_cast<struct node *>(x->a[side]);
         int height_node = node->h;
         int height_y = height(y);
         if (height_y > height(z)) {
             // Perform double rotation
             node->a[side] = y->a[!side];
             x->a[!side] = y->a[side];
             y->a[!side] = node;
             y->a[side] = x;
             node->h = height_y;
             x->h = height_y;
             y->h = height_y + 1;
         } else {
             // Perform single rotation
             node->a[side] = y;
             x->a[!side] = node;
             node->h = height_y + 1;
             x->h = height_y + 2;
             y = x;
         }
         *nodep = y;
         return y->h - height_node;
     }
References node::a, node::h, height, x, and y.
Referenced by balance_tree(), R_InitSpriteDefs(), and R_InstallSpriteLump().