Fennix Userspace: Userspace/apps/base/busybox/libbb/fflush_stdout_and_exit.c File Reference
fflush_stdout_and_exit.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC fflush_stdout_and_exit (int retval)
void FAST_FUNC fflush_stdout_and_exit_SUCCESS (void)
Function Documentation
fflush_stdout_and_exit()
void FAST_FUNC fflush_stdout_and_exit (int retval)
Definition at line 14 of file fflush_stdout_and_exit.c.
 {
     if (fflush(stdout))
         bb_simple_perror_msg_and_die(bb_msg_standard_output);
     xfunc_error_retval = retval;
     /* In case we are in NOFORK applet. Do not exit() directly,
      * but use xfunc_die() */
     xfunc_die();
 }
References bb_simple_perror_msg_and_die(), fflush(), retval, stdout, xfunc_die(), and xfunc_error_retval.
Referenced by cat_main(), cksum_main(), cmp_main(), cut_main(), du_main(), expand_main(), expr_main(), fflush_stdout_and_exit_SUCCESS(), fold_main(), head_main(), id_main(), ipcrm_main(), nl_main(), paste_main(), printenv_main(), realpath_main(), rev_main(), rx_main(), strings_main(), tee_main(), time_main(), tsort_main(), tty_main(), and wc_main().
fflush_stdout_and_exit_SUCCESS()
void FAST_FUNC fflush_stdout_and_exit_SUCCESS (void)
Definition at line 24 of file fflush_stdout_and_exit.c.
 {
     fflush_stdout_and_exit(EXIT_SUCCESS);
 }
References EXIT_SUCCESS, and fflush_stdout_and_exit().
Referenced by cal_main(), chrt_main(), env_main(), ipcs_main(), last_main(), logread_main(), nice_main(), readlink_main(), reverse(), route_main(), shuf_main(), sort_main(), uniq_main(), uuencode_main(), and vlock_main().