Fennix: Userspace/mlibc/options/posix/generic/dlfcn-stubs.cpp File Reference
dlfcn-stubs.cpp File Reference
#include <bits/ensure.h>
#include <dlfcn.h>
#include <mlibc/debug.hpp>
Data Structures
struct __dlapi_symbol
Functions
const char * __dlapi_error ()
void * __dlapi_open (const char *, int, void *)
void * __dlapi_resolve (void *, const char *, void *)
int __dlapi_reverse (const void *, __dlapi_symbol *)
int __dlapi_close (void *)
int dlclose (void *handle)
char * dlerror (void)
void * dlopen (const char *file, int flags)
void * dlsym (void *__restrict handle, const char *__restrict string)
void * dlvsym (void *__restrict handle, const char *__restrict string, const char *__restrict version)
int dladdr (const void *ptr, Dl_info *out)
int dlinfo (void *, int, void *)
Data Structure Documentation
__dlapi_symbol
struct __dlapi_symbol
Definition at line 7 of file dlfcn-stubs.cpp.
Data Fields
void * address
void * base
const char * file
const char * symbol
Function Documentation
__dlapi_close()
int __dlapi_close (void *)
Referenced by dlclose().
__dlapi_error()
const char* __dlapi_error ()
Definition at line 403 of file main.cpp.
{
     auto error = lastError;
     lastError = nullptr;
     return error;
 }
References error, and lastError.
Referenced by dlerror().
__dlapi_open()
void* __dlapi_open (const char * , int , void *)
Referenced by dlopen().
__dlapi_resolve()
void* __dlapi_resolve (void * , const char * , void *)
Referenced by dlsym(), and dlvsym().
__dlapi_reverse()
int __dlapi_reverse (const void * , __dlapi_symbol *)
Referenced by dladdr().
dladdr()
int dladdr (const void * ptr, Dl_info * out)
Definition at line 48 of file dlfcn-stubs.cpp.
{
     __dlapi_symbol info;
     if(__dlapi_reverse(ptr, &info))
         return 0;
     out->dli_fname = info.file;
     out->dli_fbase = info.base;
     out->dli_sname = info.symbol;
     out->dli_saddr = info.address;
     return 1;
 }
References __dlapi_reverse(), Dl_info::dli_fbase, Dl_info::dli_fname, Dl_info::dli_saddr, Dl_info::dli_sname, and info.
dlclose()
int dlclose (void * handle)
Definition at line 20 of file dlfcn-stubs.cpp.
{
     return __dlapi_close(handle);
 }
References __dlapi_close().
Referenced by main().
dlerror()
char* dlerror (void)
Definition at line 24 of file dlfcn-stubs.cpp.
                     {
     return const_cast<char *>(__dlapi_error());
 }
References __dlapi_error().
dlinfo()
int dlinfo (void * , int , void *)
Definition at line 60 of file dlfcn-stubs.cpp.
{
     __ensure(!"dlinfo() not implemented");
     __builtin_unreachable();
 }
References __ensure.
dlopen()
void* dlopen (const char * file, int flags)
Definition at line 29 of file dlfcn-stubs.cpp.
{
     auto ra = __builtin_extract_return_addr(__builtin_return_address(0));
     return __dlapi_open(file, flags, ra);
 }
References __dlapi_open(), and mlibc::flags.
Referenced by main().
dlsym()
void* dlsym (void *__restrict handle, const char *__restrict string)
Definition at line 35 of file dlfcn-stubs.cpp.
{
     auto ra = __builtin_extract_return_addr(__builtin_return_address(0));
     return __dlapi_resolve(handle, string, ra);
 }
References __dlapi_resolve().
dlvsym()
void* dlvsym (void *__restrict handle, const char *__restrict string, const char *__restrict version)
Definition at line 41 of file dlfcn-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: dlvsym ignores version " << version << frg::endlog;
     auto ra = __builtin_extract_return_addr(__builtin_return_address(0));
     return __dlapi_resolve(handle, string, ra);
 }
References __dlapi_resolve(), and mlibc::infoLogger.