Fennix Userspace: Userspace/apps/base/bash/builtins/gen-helpfiles.c File Reference
gen-helpfiles.c File Reference
#include <config.h>
#include "../bashtypes.h"
#include "posixstat.h"
#include "filecntl.h"
#include "../bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "stdc.h"
#include "../builtins.h"
#include "tmpbuiltins.h"
Macros
#define whitespace(c) (((c) == ' ') || ((c) == '\t'))
#define BUILTIN_FLAG_SPECIAL 0x01
#define BUILTIN_FLAG_ASSIGNMENT 0x02
#define BUILTIN_FLAG_POSIX_BUILTIN 0x04
#define BASE_INDENT 4
Functions
char * strcpy ()
int write_helpfiles PARAMS ((struct builtin *))
int main (int argc, char **argv)
void write_documentation (FILE *stream, char *documentation, int indentation)
int write_helpfiles (struct builtin *builtins)
Variables
int errno
int separate_helpfiles = 0
int single_longdoc_strings = 1
char * helpfile_directory
Macro Definition Documentation
BASE_INDENT
#define BASE_INDENT 4
Definition at line 86 of file gen-helpfiles.c.
BUILTIN_FLAG_ASSIGNMENT
#define BUILTIN_FLAG_ASSIGNMENT 0x02
Definition at line 83 of file gen-helpfiles.c.
BUILTIN_FLAG_POSIX_BUILTIN
#define BUILTIN_FLAG_POSIX_BUILTIN 0x04
Definition at line 84 of file gen-helpfiles.c.
BUILTIN_FLAG_SPECIAL
#define BUILTIN_FLAG_SPECIAL 0x01
Definition at line 82 of file gen-helpfiles.c.
whitespace
#define whitespace (c) (((c) == ' ') || ((c) == '\t'))
Definition at line 79 of file gen-helpfiles.c.
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 108 of file gen-helpfiles.c.
 {
   int arg_index = 1;
   while (arg_index < argc && argv[arg_index][0] == '-')
     {
       char *arg = argv[arg_index++];
       if (strcmp (arg, "-noproduction") == 0)
     ;
       else if (strcmp (arg, "-H") == 0)
     helpfile_directory = argv[arg_index++];
       else if (strcmp (arg, "-S") == 0)
     single_longdoc_strings = 0;
       else
     {
       fprintf (stderr, "%s: Unknown flag %s.\n", argv[0], arg);
       exit (2);
     }
     }
   write_helpfiles(shell_builtins);
   exit (0);
 }
References argc, argv, exit(), fprintf(), helpfile_directory, shell_builtins, single_longdoc_strings, stderr, strcmp, and write_helpfiles().
Referenced by __libc_start_main(), libc_start_main_stage2(), and M_SaveDefaultsAlternate().
PARAMS()
int write_helpfiles PARAMS ((struct builtin *))
strcpy()
char* strcpy ()
Referenced by __attribute__(), __strxfrm_l(), _hs_append_history_line(), _hs_history_patsearch(), _nl_log_untranslated(), _rl_copy_to_kill_ring(), _rl_isearch_dispatch(), _rl_isearch_init(), _rl_macro_dumper_internal(), _rl_make_prompt_for_search(), _rl_parse_colors(), _rl_savestring(), add_peers(), add_proc(), add_symbols_from(), add_to_ino_dev_hashtable(), assign_bash_argv0(), awk_printf(), awk_split(), awk_sub(), bb_verror_msg(), cal_main(), change_prompt(), chksum_and_xwrite_tar_header(), cmdlookup(), colon(), compute_lcd_of_matches(), conf(), conf_write(), conspy_main(), create_socket(), ctermid(), cttyhack_main(), custom(), date_main(), dbg_print_ptype(), dbg_print_stype(), decode_prompt_string(), dequote_escapes(), dequote_string(), dialog_inputbox(), dns_parse_callback(), do_display(), do_nftw(), do_redirection_internal(), dupstr(), escape_text(), ether_wake_main(), exec_kernel_doc(), expand_prompt(), expand_string_dollar_quote(), fakeidentd_main(), fileAction(), find_export_symbols(), find_user_command_internal(), fixup_rpath(), ftpcmd(), ftpd_main(), fuser_main(), get_bash_name(), get_charset_aliases(), get_drv_info(), get_header_cpio(), get_input_line(), get_node(), getdomainname(), gethostbyname2_r(), getlogin_r(), getnameinfo(), getNum(), glob_dir_to_array(), glob_vector(), glue_prefix_and_suffix(), groupnum(), handle_incoming_and_exit(), hash_find(), hist_error(), history_arg_extract(), history_backupfile(), history_do_write(), history_expand(), history_expand_internal(), history_filename(), history_tempfile(), idle_string(), IF_DESKTOP(), inet_ntop(), INET_rresolve(), init_exec(), last_main(), ll_remember_index(), load_library(), login_main(), long_double_format(), lpqr_main(), mailstat(), main(), make_all_argv_opts(), make_default_mailpath(), make_device(), make_variable_value(), match(), mindist(), mkdirpath(), mkfs_ext2_main(), mkfs_minix_main(), mkfs_reiser_main(), mkfs_vfat_main(), mkptr6(), named_function_string(), nameif_main(), new_init_action(), new_proc(), new_process_module_arguments(), nodeckstrdup(), optimized_assignment(), padvance_magic(), parameter_brace_expand(), parameter_brace_expand_word(), parse_comsub(), parse_conf(), parse_conf_file(), parse_mount_options(), pat_subst(), perform_release(), phash_search(), pid_is_exec(), pos_params_assignment(), posix_spawn_file_actions_addchdir_np(), posix_spawn_file_actions_addopen(), postproc_subst_rhs(), powertop_main(), print_autowrap(), print_filename(), printsome(), process_files(), procps_scan(), ps_main(), read_token_word(), readline_internal_teardown(), readprofile_main(), remove_quoted_escapes(), rl_display_search(), rl_filename_completion_function(), rl_on_new_line_with_prompt(), rl_quote_filename(), rl_replace_line(), rl_username_completion_function(), savestring(), searchLines(), send_select(), sendmail_main(), set_local_var(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), sh_physpath(), sh_stat(), sha_crypt(), shell_ungets(), show_manpage(), status_line_bold(), strcat(), strcreplace(), strduplicate(), strerror(), strftime(), string_quote_removal(), strlist_prefix_suffix(), subCommand(), sym_set_string_value(), tcpudpsvd_main(), tgetent(), tilde_expand(), tmpnam(), top_main(), tree_print(), ubi_tools_main(), ubirename_main(), udhcpc_main(), unix_do_one(), unzip_main(), update_export_env_inplace(), vgetopt32(), which_main(), who_main(), writeheader(), xgetpty(), xll_name_to_index(), xmalloc_follow_symlinks(), xmalloc_realpath_coreutils(), and xmalloc_substitute_string().
write_documentation()
void write_documentation (FILE * stream, char * documentation, int indentation)
Definition at line 141 of file gen-helpfiles.c.
 {
   if (stream == 0)
     return;
   if (documentation)
     fprintf (stream, "%*s%s\n", indentation, " ", documentation);
 }
References fprintf(), and indentation.
Referenced by write_helpfiles().
write_helpfiles()
int write_helpfiles (struct builtin * builtins)
Definition at line 154 of file gen-helpfiles.c.
 {
   char *helpfile, *bname, *fname;
   FILE *helpfp;
   int i, hdlen;
   struct builtin b;
   i = mkdir ("helpfiles", 0777);
   if (i < 0 && errno != EEXIST)
     {
       fprintf (stderr, "write_helpfiles: helpfiles: cannot create directory\n");
       return -1;
     }
   hdlen = strlen ("helpfiles/");
   for (i = 0; i < num_shell_builtins; i++)
     {
       b = builtins[i];
       fname = (char *)b.handle;
       helpfile = (char *)malloc (hdlen + strlen (fname) + 1);
       if (helpfile == 0)
     {
       fprintf (stderr, "gen-helpfiles: cannot allocate memory\n");
       exit (1);
     }
       sprintf (helpfile, "helpfiles/%s", fname);
       helpfp = fopen (helpfile, "w");
       if (helpfp == 0)
     {
       fprintf (stderr, "write_helpfiles: cannot open %s\n", helpfile);
       free (helpfile);
       continue;
     }
       write_documentation (helpfp, b.long_doc[0], 4);
       fflush (helpfp);
       fclose (helpfp);
       free (helpfile);
     }
   return 0;
 }
References EEXIST, errno, exit(), fclose(), fflush(), fname, fopen(), fprintf(), free, builtin::handle, i, builtin::long_doc, malloc, mkdir(), num_shell_builtins, sprintf(), stderr, strlen(), and write_documentation().
Referenced by main().
Variable Documentation
errno
int errno extern
Referenced by write_helpfiles().
helpfile_directory
char* helpfile_directory
Definition at line 98 of file gen-helpfiles.c.
Referenced by main().
separate_helpfiles
int separate_helpfiles = 0
Definition at line 90 of file gen-helpfiles.c.
single_longdoc_strings
int single_longdoc_strings = 1
Definition at line 94 of file gen-helpfiles.c.
Referenced by main().