Fennix Userspace: Userspace/musl/src/conf/legacy.c File Reference
legacy.c File Reference
#include <sys/sysinfo.h>
#include <unistd.h>
Functions
int get_nprocs_conf ()
int get_nprocs ()
long get_phys_pages ()
long get_avphys_pages ()
Function Documentation
get_avphys_pages()
long get_avphys_pages (void)
Definition at line 19 of file legacy.c.
 {
     return sysconf(_SC_AVPHYS_PAGES);
 }
References _SC_AVPHYS_PAGES, and sysconf().
get_nprocs()
int get_nprocs (void)
Definition at line 9 of file legacy.c.
 {
     return sysconf(_SC_NPROCESSORS_ONLN);
 }
References _SC_NPROCESSORS_ONLN, and sysconf().
get_nprocs_conf()
int get_nprocs_conf (void)
Definition at line 4 of file legacy.c.
 {
     return sysconf(_SC_NPROCESSORS_CONF);
 }
References _SC_NPROCESSORS_CONF, and sysconf().
get_phys_pages()
long get_phys_pages (void)
Definition at line 14 of file legacy.c.
 {
     return sysconf(_SC_PHYS_PAGES);
 }
References _SC_PHYS_PAGES, and sysconf().