Fennix Userspace: Userspace/apps/base/busybox/coreutils/env.c File Reference
env.c File Reference
#include "libbb.h"
Functions
int env_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
env_main()
int env_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 55 of file env.c.
 {
     unsigned opts;
     llist_t *unset_env = NULL;
     opts = getopt32long(argv, "+i0u:*",
             "ignore-environment\0" No_argument       "i"
             "null\0"               No_argument       "0"
             "unset\0"              Required_argument "u"
             , &unset_env
     );
     argv += optind;
     if (argv[0] && LONE_DASH(argv[0])) {
         opts |= 1;
         ++argv;
     }
     if (opts & 1) {
         clearenv();
     }
     while (unset_env) {
         char *var = llist_pop(&unset_env);
         /* This does not handle -uVAR=VAL
          * (coreutils _sets_ the variable in that case): */
         /*unsetenv(var);*/
         /* This does, but uses somewhan undocumented feature that
          * putenv("name_without_equal_sign") unsets the variable: */
         putenv(var);
     }
     while (*argv && (strchr(*argv, '=') != NULL)) {
         if (putenv(*argv) < 0) {
             bb_simple_perror_msg_and_die("putenv");
         }
         ++argv;
     }
     if (argv[0]) {
         BB_EXECVP_or_die(argv);
     }
     if (environ) { /* clearenv() may set environ == NULL! */
         char **ep;
         opts = (opts & 2) ? 0 : '\n';
         for (ep = environ; *ep; ep++) {
             printf("%s%c", *ep, opts);
         }
     }
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, BB_EXECVP_or_die(), bb_simple_perror_msg_and_die(), clearenv(), environ, fflush_stdout_and_exit_SUCCESS(), getopt32long, llist_pop(), LONE_DASH, No_argument, NULL, optind, printf(), putenv(), Required_argument, and strchr().