Fennix Kernel: GraphicalUserInterface::WidgetCollection Class Reference
GraphicalUserInterface::WidgetCollection Class Reference
#include <gui.hpp>
Data Structures
struct ButtonObject
struct HandleMeta
struct LabelObject
struct PanelObject
Public Member Functions
void ReplaceFont (Video::Font *NewFont)
Handle CreatePanel (Rect rect, uint32_t Color)
Handle CreateButton (Rect rect, const char *Text, uintptr_t OnClick=(uintptr_t) nullptr)
Handle CreateLabel (Rect rect, const char *Text)
Handle CreateTextBox (Rect rect, const char *Text)
Handle CreateCheckBox (Rect rect, const char *Text)
Handle CreateRadioButton (Rect rect, const char *Text)
Handle CreateComboBox (Rect rect, const char *Text)
Handle CreateListBox (Rect rect, const char *Text)
Handle CreateProgressBar (Rect rect, const char *Text)
Handle CreateContextMenu (Rect rect, const char *Text)
void SetText (Handle handle, const char *Text)
WidgetCollection (void *ParentWindow)
~WidgetCollection ()
void OnMouseMove (Event *e)
void OnMouseClick (Event *e)
void OnMouseDoubleClick (Event *e)
void OnMouseDown (Event *e)
void OnMouseUp (Event *e)
void OnMouseWheel (Event *e)
void OnMouseEnter (Event *e)
void OnMouseLeave (Event *e)
void OnMouseHover (Event *e)
void OnMouseDrag (Event *e)
void OnMouseDragStart (Event *e)
void OnMouseDragEnd (Event *e)
void OnKeyDown (Event *e)
void OnKeyUp (Event *e)
void OnKeyPress (Event *e)
void OnShow (Event *e)
void OnHide (Event *e)
void OnDestroy (Event *e)
void OnPaint (Event *e)
void OnPaintBackground (Event *e)
void OnPaintForeground (Event *e)
Private Attributes
Memory::MemMgr * mem
ScreenBitmap * Buffer
Video::Font * CurrentFont
void * ParentWindow
bool NeedRedraw
std::vector< LabelObject * > Labels
std::vector< PanelObject * > Panels
std::vector< ButtonObject * > Buttons
Detailed Description
Definition at line 201 of file gui.hpp.
Data Structure Documentation
GraphicalUserInterface::WidgetCollection::ButtonObject
struct GraphicalUserInterface::WidgetCollection::ButtonObject
Definition at line 234 of file gui.hpp.
Data Fields
uint32_t BorderColor
int64_t CharCursorX
int64_t CharCursorY
uint32_t Color
HandleMeta Handle
bool Hover
uint32_t HoverColor
uintptr_t OnClick
bool Pressed
uint32_t PressedColor
Rect rect
bool Shadow
uint32_t ShadowColor
char Text[512]
GraphicalUserInterface::WidgetCollection::HandleMeta
struct GraphicalUserInterface::WidgetCollection::HandleMeta
Definition at line 210 of file gui.hpp.
Data Fields
char Type[4]
GraphicalUserInterface::WidgetCollection::LabelObject
struct GraphicalUserInterface::WidgetCollection::LabelObject
Definition at line 215 of file gui.hpp.
Data Fields
int64_t CharCursorX
int64_t CharCursorY
uint32_t Color
HandleMeta Handle
Rect rect
char Text[512]
GraphicalUserInterface::WidgetCollection::PanelObject
struct GraphicalUserInterface::WidgetCollection::PanelObject
Definition at line 224 of file gui.hpp.
Data Fields
uint32_t BorderColor
uint32_t Color
HandleMeta Handle
Rect rect
bool Shadow
uint32_t ShadowColor
Constructor & Destructor Documentation
WidgetCollection()
GraphicalUserInterface::WidgetCollection::WidgetCollection (void * ParentWindow)
Definition at line 112 of file Widgets.cpp.
     {
         if (!ParentWindow)
         {
             error("ParentWindow is null");
             return;
         }
         this->ParentWindow = ParentWindow;
         this->mem = new Memory::MemMgr;
         this->Buffer = new ScreenBitmap;
         this->Buffer->Width = ((Window *)this->ParentWindow)->GetPosition().Width;
         this->Buffer->Height = ((Window *)this->ParentWindow)->GetPosition().Height;
         this->Buffer->BitsPerPixel = Display->GetBitsPerPixel();
         this->Buffer->Pitch = Display->GetPitch();
         this->Buffer->Size = (size_t)(this->Buffer->Pitch * ((Window *)this->ParentWindow)->GetPosition().Height);
         this->Buffer->Data = (uint8_t *)this->mem->RequestPages(TO_PAGES(this->Buffer->Size + 1));
         memset(this->Buffer->Data, 0, this->Buffer->Size);
         this->CurrentFont = new Video::Font(&_binary_Files_tamsyn_font_1_11_Tamsyn10x20r_psf_start, &_binary_Files_tamsyn_font_1_11_Tamsyn10x20r_psf_end, Video::FontType::PCScreenFont2);
     }
References _binary_Files_tamsyn_font_1_11_Tamsyn10x20r_psf_end, _binary_Files_tamsyn_font_1_11_Tamsyn10x20r_psf_start, GraphicalUserInterface::ScreenBitmap::BitsPerPixel, Buffer, CurrentFont, GraphicalUserInterface::ScreenBitmap::Data, Display, error, GraphicalUserInterface::ScreenBitmap::Height, mem, memset(), ParentWindow, Video::PCScreenFont2, GraphicalUserInterface::ScreenBitmap::Pitch, GraphicalUserInterface::ScreenBitmap::Size, and GraphicalUserInterface::ScreenBitmap::Width.
~WidgetCollection()
GraphicalUserInterface::WidgetCollection::~WidgetCollection ()
Definition at line 135 of file Widgets.cpp.
     {
         delete this->mem, this->mem = nullptr;
         delete this->Buffer, this->Buffer = nullptr;
         delete this->CurrentFont, this->CurrentFont = nullptr;
     }
References Buffer, CurrentFont, and mem.
Member Function Documentation
CreateButton()
Handle GraphicalUserInterface::WidgetCollection::CreateButton (Rect rect, const char * Text, uintptr_t OnClick = (uintptr_t) nullptr)
Definition at line 75 of file Widgets.cpp.
     {
         ButtonObject *button = (ButtonObject *)this->mem->RequestPages(TO_PAGES(sizeof(ButtonObject) + 1));
         button->Handle.Type[0] = 'B';
         button->Handle.Type[1] = 'T';
         button->Handle.Type[2] = 'N';
         button->Handle.Type[3] = '\0';
         button->rect = rect;
         strcpy(button->Text, Text);
         button->Color = 0x252525;
         button->HoverColor = 0x353535;
         button->PressedColor = 0x555555;
         button->BorderColor = 0xFF000000;
         button->ShadowColor = 0xFF000000;
         button->Shadow = false;
         button->Hover = false;
         button->Pressed = false;
         button->OnClick = OnClick;
         Buttons.push_back(button);
         this->NeedRedraw = true;
         return (Handle)button;
     }
References GraphicalUserInterface::WidgetCollection::ButtonObject::BorderColor, Buttons, GraphicalUserInterface::WidgetCollection::ButtonObject::Color, GraphicalUserInterface::WidgetCollection::ButtonObject::Handle, GraphicalUserInterface::WidgetCollection::ButtonObject::Hover, GraphicalUserInterface::WidgetCollection::ButtonObject::HoverColor, mem, NeedRedraw, GraphicalUserInterface::WidgetCollection::ButtonObject::OnClick, GraphicalUserInterface::WidgetCollection::ButtonObject::Pressed, GraphicalUserInterface::WidgetCollection::ButtonObject::PressedColor, GraphicalUserInterface::WidgetCollection::ButtonObject::rect, GraphicalUserInterface::WidgetCollection::ButtonObject::Shadow, GraphicalUserInterface::WidgetCollection::ButtonObject::ShadowColor, strcpy, GraphicalUserInterface::WidgetCollection::ButtonObject::Text, and GraphicalUserInterface::WidgetCollection::HandleMeta::Type.
Referenced by Recovery::KernelRecovery::KernelRecovery(), and Recovery::KernelRecovery::RecoveryThread().
CreateCheckBox()
Handle GraphicalUserInterface::WidgetCollection::CreateCheckBox (Rect rect, const char * Text)
CreateComboBox()
Handle GraphicalUserInterface::WidgetCollection::CreateComboBox (Rect rect, const char * Text)
CreateContextMenu()
Handle GraphicalUserInterface::WidgetCollection::CreateContextMenu (Rect rect, const char * Text)
CreateLabel()
Handle GraphicalUserInterface::WidgetCollection::CreateLabel (Rect rect, const char * Text)
Definition at line 55 of file Widgets.cpp.
     {
         LabelObject *label = (LabelObject *)this->mem->RequestPages(TO_PAGES(sizeof(LabelObject) + 1));
         label->Handle.Type[0] = 'L';
         label->Handle.Type[1] = 'B';
         label->Handle.Type[2] = 'L';
         label->Handle.Type[3] = '\0';
         label->rect = rect;
         strcpy(label->Text, Text);
         label->Color = 0xFFFFFF;
         label->CharCursorX = rect.Left;
         label->CharCursorY = rect.Top;
         Labels.push_back(label);
         NeedRedraw = true;
         return (Handle)label;
     }
References GraphicalUserInterface::WidgetCollection::LabelObject::CharCursorX, GraphicalUserInterface::WidgetCollection::LabelObject::CharCursorY, GraphicalUserInterface::WidgetCollection::LabelObject::Color, GraphicalUserInterface::WidgetCollection::LabelObject::Handle, Labels, GraphicalUserInterface::Rect::Left, mem, NeedRedraw, GraphicalUserInterface::WidgetCollection::LabelObject::rect, strcpy, GraphicalUserInterface::WidgetCollection::LabelObject::Text, GraphicalUserInterface::Rect::Top, and GraphicalUserInterface::WidgetCollection::HandleMeta::Type.
Referenced by Recovery::KernelRecovery::KernelRecovery(), and Recovery::KernelRecovery::RecoveryThread().
CreateListBox()
Handle GraphicalUserInterface::WidgetCollection::CreateListBox (Rect rect, const char * Text)
CreatePanel()
Handle GraphicalUserInterface::WidgetCollection::CreatePanel (Rect rect, uint32_t Color)
Definition at line 35 of file Widgets.cpp.
     {
         PanelObject *panel = (PanelObject *)this->mem->RequestPages(TO_PAGES(sizeof(PanelObject) + 1));
         panel->Handle.Type[0] = 'P';
         panel->Handle.Type[1] = 'N';
         panel->Handle.Type[2] = 'L';
         panel->Handle.Type[3] = '\0';
         panel->rect = rect;
         panel->Color = Color;
         panel->BorderColor = 0xFF000000;
         panel->ShadowColor = 0xFF000000;
         panel->Shadow = false;
         Panels.push_back(panel);
         this->NeedRedraw = true;
         return (Handle)panel;
     }
References GraphicalUserInterface::WidgetCollection::PanelObject::BorderColor, GraphicalUserInterface::WidgetCollection::PanelObject::Color, GraphicalUserInterface::WidgetCollection::PanelObject::Handle, mem, NeedRedraw, Panels, GraphicalUserInterface::WidgetCollection::PanelObject::rect, GraphicalUserInterface::WidgetCollection::PanelObject::Shadow, GraphicalUserInterface::WidgetCollection::PanelObject::ShadowColor, and GraphicalUserInterface::WidgetCollection::HandleMeta::Type.
CreateProgressBar()
Handle GraphicalUserInterface::WidgetCollection::CreateProgressBar (Rect rect, const char * Text)
CreateRadioButton()
Handle GraphicalUserInterface::WidgetCollection::CreateRadioButton (Rect rect, const char * Text)
CreateTextBox()
Handle GraphicalUserInterface::WidgetCollection::CreateTextBox (Rect rect, const char * Text)
OnDestroy()
void GraphicalUserInterface::WidgetCollection::OnDestroy (Event * e)
OnHide()
void GraphicalUserInterface::WidgetCollection::OnHide (Event * e)
OnKeyDown()
void GraphicalUserInterface::WidgetCollection::OnKeyDown (Event * e)
OnKeyPress()
void GraphicalUserInterface::WidgetCollection::OnKeyPress (Event * e)
OnKeyUp()
void GraphicalUserInterface::WidgetCollection::OnKeyUp (Event * e)
OnMouseClick()
void GraphicalUserInterface::WidgetCollection::OnMouseClick (Event * e)
OnMouseDoubleClick()
void GraphicalUserInterface::WidgetCollection::OnMouseDoubleClick (Event * e)
OnMouseDown()
void GraphicalUserInterface::WidgetCollection::OnMouseDown (Event * e)
Definition at line 104 of file WidgetEvents.cpp.
     {
         foreach (auto Button in this->Buttons)
         {
             if (Button->rect.Contains(e->MouseDown.X, e->MouseDown.Y))
             {
                 if (e->MouseDown.Left)
                 {
                     debug("Button Hold");
                     Button->Pressed = true;
                     this->NeedRedraw = true;
                 }
             }
         }
     }
References Buttons, debug, and NeedRedraw.
OnMouseDrag()
void GraphicalUserInterface::WidgetCollection::OnMouseDrag (Event * e)
OnMouseDragEnd()
void GraphicalUserInterface::WidgetCollection::OnMouseDragEnd (Event * e)
OnMouseDragStart()
void GraphicalUserInterface::WidgetCollection::OnMouseDragStart (Event * e)
OnMouseEnter()
void GraphicalUserInterface::WidgetCollection::OnMouseEnter (Event * e)
OnMouseHover()
void GraphicalUserInterface::WidgetCollection::OnMouseHover (Event * e)
OnMouseLeave()
void GraphicalUserInterface::WidgetCollection::OnMouseLeave (Event * e)
OnMouseMove()
void GraphicalUserInterface::WidgetCollection::OnMouseMove (Event * e)
Definition at line 143 of file WidgetEvents.cpp.
     {
         foreach (auto Button in this->Buttons)
         {
             if (Button->rect.Contains(e->MouseMove.X, e->MouseMove.Y))
             {
                 Button->Hover = true;
                 this->NeedRedraw = true;
             }
             else
             {
                 Button->Hover = false;
                 this->NeedRedraw = true;
             }
         }
     }
References Buttons, and NeedRedraw.
OnMouseUp()
void GraphicalUserInterface::WidgetCollection::OnMouseUp (Event * e)
Definition at line 120 of file WidgetEvents.cpp.
     {
         foreach (auto Button in this->Buttons)
         {
             if (Button->rect.Contains(e->MouseUp.X, e->MouseUp.Y))
             {
                 if (e->MouseUp.Left)
                 {
                     debug("Button Release");
                     if (Button->Pressed)
                     {
                         debug("Button Clicked");
                         if (Button->OnClick != (uintptr_t) nullptr)
                             ((void (*)(void))Button->OnClick)();
                         Button->Pressed = false;
                         this->NeedRedraw = true;
                     }
                 }
             }
         }
     }
References Buttons, debug, NeedRedraw, and Driver::void().
OnMouseWheel()
void GraphicalUserInterface::WidgetCollection::OnMouseWheel (Event * e)
OnPaint()
void GraphicalUserInterface::WidgetCollection::OnPaint (Event * e)
Definition at line 67 of file WidgetEvents.cpp.
     {
         static size_t LastWidth = 0;
         static size_t LastHeight = 0;
         if (LastWidth != ((Window *)this->ParentWindow)->GetPosition().Width ||
             LastHeight != ((Window *)this->ParentWindow)->GetPosition().Height)
         {
             LastWidth = ((Window *)this->ParentWindow)->GetPosition().Width;
             LastHeight = ((Window *)this->ParentWindow)->GetPosition().Height;
             this->mem->FreePages(this->Buffer->Data, TO_PAGES(this->Buffer->Size + 1));
             this->Buffer->Data = nullptr;
             delete this->Buffer, this->Buffer = nullptr;
             this->Buffer = new ScreenBitmap;
             this->Buffer->Width = LastWidth;
             this->Buffer->Height = LastHeight;
             this->Buffer->BitsPerPixel = Display->GetBitsPerPixel();
             this->Buffer->Pitch = Display->GetPitch();
             this->Buffer->Size = this->Buffer->Pitch * (size_t)LastHeight;
             this->Buffer->Data = (uint8_t *)this->mem->RequestPages(TO_PAGES(this->Buffer->Size + 1));
             memset(this->Buffer->Data, 0, this->Buffer->Size);
             this->NeedRedraw = true;
         }
         if (this->NeedRedraw)
         {
             memset(this->Buffer->Data, 0, this->Buffer->Size);
             this->OnPaintBackground(e);
             this->OnPaintForeground(e);
             this->NeedRedraw = false;
         }
         DrawOverBitmap(((Window *)this->ParentWindow)->GetBuffer(), this->Buffer, 0, 0);
     }
References Buffer, GraphicalUserInterface::ScreenBitmap::Data, Display, GraphicalUserInterface::DrawOverBitmap(), mem, memset(), NeedRedraw, OnPaintBackground(), OnPaintForeground(), ParentWindow, GraphicalUserInterface::ScreenBitmap::Size, and GraphicalUserInterface::ScreenBitmap::Width.
OnPaintBackground()
void GraphicalUserInterface::WidgetCollection::OnPaintBackground (Event * e)
Definition at line 31 of file WidgetEvents.cpp.
     {
         UNUSED(e);
     }
References UNUSED.
Referenced by OnPaint().
OnPaintForeground()
void GraphicalUserInterface::WidgetCollection::OnPaintForeground (Event * e)
Definition at line 36 of file WidgetEvents.cpp.
     {
         UNUSED(e);
         foreach (auto Panel in this->Panels)
         {
             PutRect(this->Buffer, Panel->rect, Panel->Color);
         }
         foreach (auto Label in this->Labels)
         {
             Label->CharCursorX = Label->rect.Left;
             Label->CharCursorY = Label->rect.Top;
             for (uint64_t i = 0; i < strlen(Label->Text); i++)
                 PaintChar(this->CurrentFont, this->Buffer, Label->Text[i], 0xFFFFFF, &Label->CharCursorX, &Label->CharCursorY);
         }
         foreach (auto Button in this->Buttons)
         {
             if (Button->Pressed)
                 PutRect(this->Buffer, Button->rect, Button->PressedColor);
             else if (Button->Hover)
                 PutRect(this->Buffer, Button->rect, Button->HoverColor);
             else
                 PutRect(this->Buffer, Button->rect, Button->Color);
             Button->CharCursorX = Button->rect.Left + (((Button->rect.Width / 2) - (this->CurrentFont->GetInfo().Width * strlen(Button->Text) / 2)));
             Button->CharCursorY = Button->rect.Top + (((Button->rect.Height / 2) - (this->CurrentFont->GetInfo().Height / 2)));
             for (uint64_t i = 0; i < strlen(Button->Text); i++)
                 PaintChar(this->CurrentFont, this->Buffer, Button->Text[i], 0xFFFFFF, &Button->CharCursorX, &Button->CharCursorY);
         }
     }
References Buffer, Buttons, CurrentFont, Video::Font::GetInfo(), Video::FontInfo::Height, Labels, GraphicalUserInterface::PaintChar(), Panels, GraphicalUserInterface::PutRect(), strlen(), UNUSED, and Video::FontInfo::Width.
Referenced by OnPaint().
OnShow()
void GraphicalUserInterface::WidgetCollection::OnShow (Event * e)
ReplaceFont()
void GraphicalUserInterface::WidgetCollection::ReplaceFont (Video::Font * NewFont) inline
Definition at line 256 of file gui.hpp.
         {
             delete this->CurrentFont;
             this->CurrentFont = NewFont;
         }
References CurrentFont.
Referenced by Recovery::KernelRecovery::KernelRecovery().
SetText()
void GraphicalUserInterface::WidgetCollection::SetText (Handle handle, const char * Text)
Definition at line 101 of file Widgets.cpp.
     {
         HandleMeta *meta = (HandleMeta *)handle;
         if (meta->Type[0] == 'L' && meta->Type[1] == 'B' && meta->Type[2] == 'L')
         {
             LabelObject *label = (LabelObject *)handle;
             strcpy(label->Text, Text);
             this->NeedRedraw = true;
         }
     }
References NeedRedraw, strcpy, GraphicalUserInterface::WidgetCollection::LabelObject::Text, and GraphicalUserInterface::WidgetCollection::HandleMeta::Type.
Referenced by Recovery::KernelRecovery::RecoveryThread().
Field Documentation
Buffer
ScreenBitmap* GraphicalUserInterface::WidgetCollection::Buffer private
Definition at line 205 of file gui.hpp.
Referenced by OnPaint(), OnPaintForeground(), WidgetCollection(), and ~WidgetCollection().
Buttons
std::vector<ButtonObject *> GraphicalUserInterface::WidgetCollection::Buttons private
Definition at line 253 of file gui.hpp.
Referenced by CreateButton(), OnMouseDown(), OnMouseMove(), OnMouseUp(), and OnPaintForeground().
CurrentFont
Video::Font* GraphicalUserInterface::WidgetCollection::CurrentFont private
Definition at line 206 of file gui.hpp.
Referenced by OnPaintForeground(), ReplaceFont(), WidgetCollection(), and ~WidgetCollection().
Labels
std::vector<LabelObject *> GraphicalUserInterface::WidgetCollection::Labels private
Definition at line 251 of file gui.hpp.
Referenced by CreateLabel(), and OnPaintForeground().
mem
Memory::MemMgr* GraphicalUserInterface::WidgetCollection::mem private
Definition at line 204 of file gui.hpp.
Referenced by CreateButton(), CreateLabel(), CreatePanel(), OnPaint(), WidgetCollection(), and ~WidgetCollection().
NeedRedraw
bool GraphicalUserInterface::WidgetCollection::NeedRedraw private
Definition at line 208 of file gui.hpp.
Referenced by CreateButton(), CreateLabel(), CreatePanel(), OnMouseDown(), OnMouseMove(), OnMouseUp(), OnPaint(), and SetText().
Panels
std::vector<PanelObject *> GraphicalUserInterface::WidgetCollection::Panels private
Definition at line 252 of file gui.hpp.
Referenced by CreatePanel(), and OnPaintForeground().
ParentWindow
void* GraphicalUserInterface::WidgetCollection::ParentWindow private
Definition at line 207 of file gui.hpp.
Referenced by OnPaint(), and WidgetCollection().
The documentation for this class was generated from the following files:
Kernel/include/gui.hpp
Kernel/GUI/WidgetEvents.cpp
Kernel/GUI/Widgets.cpp