Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_fixed.h File Reference
m_fixed.h File Reference
Macros
#define FRACBITS 16
#define FRACUNIT (1<<FRACBITS)
Typedefs
typedef int fixed_t
Functions
fixed_t FixedMul (fixed_t a, fixed_t b)
fixed_t FixedDiv (fixed_t a, fixed_t b)
Macro Definition Documentation
FRACBITS
#define FRACBITS 16
Definition at line 29 of file m_fixed.h.
FRACUNIT
#define FRACUNIT (1<<FRACBITS)
Definition at line 30 of file m_fixed.h.
Typedef Documentation
fixed_t
typedef int fixed_t
Definition at line 32 of file m_fixed.h.
Function Documentation
FixedDiv()
fixed_t FixedDiv (fixed_t a, fixed_t b)
Definition at line 47 of file m_fixed.c.
 {
     if ((abs(a) >> 14) >= abs(b))
     {
     return (a^b) < 0 ? (-__INT_MAX__ - 1) : __INT_MAX__;
     }
     else
     {
     int64_t result;
     result = ((int64_t) a << 16) / b;
     return (fixed_t) result;
     }
 }
References abs.
Referenced by AM_changeWindowScale(), AM_findMinMaxBoundaries(), AM_getIslope(), AM_LevelInit(), AM_maxOutWindowScale(), AM_minOutWindowScale(), AM_restoreScaleAndLoc(), P_CrossSubsector(), P_InterceptVector(), P_InterceptVector2(), P_LoadLineDefs(), P_PathTraverse(), PTR_AimTraverse(), PTR_ShootTraverse(), R_ClearPlanes(), R_ExecuteSetViewSize(), R_InitLightTables(), R_InitTextureMapping(), R_PointToDist(), R_ProjectSprite(), R_ScaleFromGlobalAngle(), and R_StoreWallRange().
FixedMul()
fixed_t FixedMul (fixed_t a, fixed_t b)
Definition at line 34 of file m_fixed.c.
 {
     return ((int64_t) a * (int64_t) b) >> FRACBITS;
 }
References FRACBITS.
Referenced by A_FatAttack1(), A_FatAttack2(), A_FatAttack3(), A_Fire(), A_PainShootSkull(), A_SkullAttack(), A_Tracer(), A_VileAttack(), A_WeaponReady(), AM_changeWindowScale(), AM_drawLineCharacter(), AM_rotate(), P_CalcHeight(), P_CalcSwing(), P_DamageMobj(), P_HitSlideLine(), P_InterceptVector(), P_InterceptVector2(), P_PathTraverse(), P_PointOnDivlineSide(), P_PointOnLineSide(), P_SlideMove(), P_SpawnMissile(), P_SpawnPlayerMissile(), P_Thrust(), P_XYMovement(), PTR_AimTraverse(), PTR_ShootTraverse(), R_DrawPSprite(), R_DrawVisSprite(), R_InitTextureMapping(), R_MapPlane(), R_PointOnSegSide(), R_PointOnSide(), R_ProjectSprite(), R_RenderMaskedSegRange(), R_RenderSegLoop(), R_ScaleFromGlobalAngle(), R_StoreWallRange(), and S_AdjustSoundParams().