Fennix: Userspace/apps/base/bash/y.tab.h File Reference
y.tab.h File Reference
Data Structures
union YYSTYPE
Macros
#define YYDEBUG 0
#define YYTOKENTYPE
#define YYEMPTY -2
#define YYEOF 0
#define YYerror 256
#define YYUNDEF 257
#define IF 258
#define THEN 259
#define ELSE 260
#define ELIF 261
#define FI 262
#define CASE 263
#define ESAC 264
#define FOR 265
#define SELECT 266
#define WHILE 267
#define UNTIL 268
#define DO 269
#define DONE 270
#define FUNCTION 271
#define COPROC 272
#define COND_START 273
#define COND_END 274
#define COND_ERROR 275
#define IN 276
#define BANG 277
#define TIME 278
#define TIMEOPT 279
#define TIMEIGN 280
#define WORD 281
#define ASSIGNMENT_WORD 282
#define REDIR_WORD 283
#define NUMBER 284
#define ARITH_CMD 285
#define ARITH_FOR_EXPRS 286
#define COND_CMD 287
#define AND_AND 288
#define OR_OR 289
#define GREATER_GREATER 290
#define LESS_LESS 291
#define LESS_AND 292
#define LESS_LESS_LESS 293
#define GREATER_AND 294
#define SEMI_SEMI 295
#define SEMI_AND 296
#define SEMI_SEMI_AND 297
#define LESS_LESS_MINUS 298
#define AND_GREATER 299
#define AND_GREATER_GREATER 300
#define LESS_GREATER 301
#define GREATER_BAR 302
#define BAR_AND 303
#define DOLPAREN 304
#define yacc_EOF 305
#define YYSTYPE_IS_TRIVIAL 1
#define YYSTYPE_IS_DECLARED 1
Typedefs
typedef enum yytokentype yytoken_kind_t
typedef union YYSTYPE YYSTYPE
Enumerations
enum yytokentype {
EQUOP2 = 258 , CMPOP2 = 259 , ADDOP2 = 260 , MULOP2 = 261 ,
NUMBER = 262 , YYEMPTY = -2 , YYEOF = 0 , YYerror = 256 ,
YYUNDEF = 257 , IF = 258 , THEN = 259 , ELSE = 260 ,
ELIF = 261 , FI = 262 , CASE = 263 , ESAC = 264 ,
FOR = 265 , SELECT = 266 , WHILE = 267 , UNTIL = 268 ,
DO = 269 , DONE = 270 , FUNCTION = 271 , COPROC = 272 ,
COND_START = 273 , COND_END = 274 , COND_ERROR = 275 , IN = 276 ,
BANG = 277 , TIME = 278 , TIMEOPT = 279 , TIMEIGN = 280 ,
WORD = 281 , ASSIGNMENT_WORD = 282 , REDIR_WORD = 283 , NUMBER = 284 ,
ARITH_CMD = 285 , ARITH_FOR_EXPRS = 286 , COND_CMD = 287 , AND_AND = 288 ,
OR_OR = 289 , GREATER_GREATER = 290 , LESS_LESS = 291 , LESS_AND = 292 ,
LESS_LESS_LESS = 293 , GREATER_AND = 294 , SEMI_SEMI = 295 , SEMI_AND = 296 ,
SEMI_SEMI_AND = 297 , LESS_LESS_MINUS = 298 , AND_GREATER = 299 , AND_GREATER_GREATER = 300 ,
LESS_GREATER = 301 , GREATER_BAR = 302 , BAR_AND = 303 , DOLPAREN = 304 ,
yacc_EOF = 305 , YYEMPTY = -2 , YYEOF = 0 , YYerror = 256 ,
YYUNDEF = 257 , IF = 258 , THEN = 259 , ELSE = 260 ,
ELIF = 261 , FI = 262 , CASE = 263 , ESAC = 264 ,
FOR = 265 , SELECT = 266 , WHILE = 267 , UNTIL = 268 ,
DO = 269 , DONE = 270 , FUNCTION = 271 , COPROC = 272 ,
COND_START = 273 , COND_END = 274 , COND_ERROR = 275 , IN = 276 ,
BANG = 277 , TIME = 278 , TIMEOPT = 279 , TIMEIGN = 280 ,
WORD = 281 , ASSIGNMENT_WORD = 282 , REDIR_WORD = 283 , NUMBER = 284 ,
ARITH_CMD = 285 , ARITH_FOR_EXPRS = 286 , COND_CMD = 287 , AND_AND = 288 ,
OR_OR = 289 , GREATER_GREATER = 290 , LESS_LESS = 291 , LESS_AND = 292 ,
LESS_LESS_LESS = 293 , GREATER_AND = 294 , SEMI_SEMI = 295 , SEMI_AND = 296 ,
SEMI_SEMI_AND = 297 , LESS_LESS_MINUS = 298 , AND_GREATER = 299 , AND_GREATER_GREATER = 300 ,
LESS_GREATER = 301 , GREATER_BAR = 302 , BAR_AND = 303 , DOLPAREN = 304 ,
yacc_EOF = 305
}
Functions
int yyparse (void)
Variables
YYSTYPE yylval
Data Structure Documentation
YYSTYPE
union YYSTYPE
Definition at line 146 of file plural.c.
Data Fields
COMMAND * command
ELEMENT element
struct expression * exp
unsigned long int num
int number
enum operator op
PATTERN_LIST * pattern
REDIRECT * redirect
WORD_DESC * word
WORD_LIST * word_list
Macro Definition Documentation
AND_AND
#define AND_AND 288
Definition at line 143 of file y.tab.h.
AND_GREATER
#define AND_GREATER 299
Definition at line 154 of file y.tab.h.
AND_GREATER_GREATER
#define AND_GREATER_GREATER 300
Definition at line 155 of file y.tab.h.
ARITH_CMD
#define ARITH_CMD 285
Definition at line 140 of file y.tab.h.
ARITH_FOR_EXPRS
#define ARITH_FOR_EXPRS 286
Definition at line 141 of file y.tab.h.
ASSIGNMENT_WORD
#define ASSIGNMENT_WORD 282
Definition at line 137 of file y.tab.h.
BANG
#define BANG 277
Definition at line 132 of file y.tab.h.
BAR_AND
#define BAR_AND 303
Definition at line 158 of file y.tab.h.
CASE
#define CASE 263
Definition at line 118 of file y.tab.h.
COND_CMD
#define COND_CMD 287
Definition at line 142 of file y.tab.h.
COND_END
#define COND_END 274
Definition at line 129 of file y.tab.h.
COND_ERROR
#define COND_ERROR 275
Definition at line 130 of file y.tab.h.
COND_START
#define COND_START 273
Definition at line 128 of file y.tab.h.
COPROC
#define COPROC 272
Definition at line 127 of file y.tab.h.
DO
#define DO 269
Definition at line 124 of file y.tab.h.
DOLPAREN
#define DOLPAREN 304
Definition at line 159 of file y.tab.h.
DONE
#define DONE 270
Definition at line 125 of file y.tab.h.
ELIF
#define ELIF 261
Definition at line 116 of file y.tab.h.
ELSE
#define ELSE 260
Definition at line 115 of file y.tab.h.
ESAC
#define ESAC 264
Definition at line 119 of file y.tab.h.
FI
#define FI 262
Definition at line 117 of file y.tab.h.
FOR
#define FOR 265
Definition at line 120 of file y.tab.h.
FUNCTION
#define FUNCTION 271
Definition at line 126 of file y.tab.h.
GREATER_AND
#define GREATER_AND 294
Definition at line 149 of file y.tab.h.
GREATER_BAR
#define GREATER_BAR 302
Definition at line 157 of file y.tab.h.
GREATER_GREATER
#define GREATER_GREATER 290
Definition at line 145 of file y.tab.h.
IF
#define IF 258
Definition at line 113 of file y.tab.h.
IN
#define IN 276
Definition at line 131 of file y.tab.h.
LESS_AND
#define LESS_AND 292
Definition at line 147 of file y.tab.h.
LESS_GREATER
#define LESS_GREATER 301
Definition at line 156 of file y.tab.h.
LESS_LESS
#define LESS_LESS 291
Definition at line 146 of file y.tab.h.
LESS_LESS_LESS
#define LESS_LESS_LESS 293
Definition at line 148 of file y.tab.h.
LESS_LESS_MINUS
#define LESS_LESS_MINUS 298
Definition at line 153 of file y.tab.h.
NUMBER
#define NUMBER 284
Definition at line 139 of file y.tab.h.
OR_OR
#define OR_OR 289
Definition at line 144 of file y.tab.h.
REDIR_WORD
#define REDIR_WORD 283
Definition at line 138 of file y.tab.h.
SELECT
#define SELECT 266
Definition at line 121 of file y.tab.h.
SEMI_AND
#define SEMI_AND 296
Definition at line 151 of file y.tab.h.
SEMI_SEMI
#define SEMI_SEMI 295
Definition at line 150 of file y.tab.h.
SEMI_SEMI_AND
#define SEMI_SEMI_AND 297
Definition at line 152 of file y.tab.h.
THEN
#define THEN 259
Definition at line 114 of file y.tab.h.
TIME
#define TIME 278
Definition at line 133 of file y.tab.h.
TIMEIGN
#define TIMEIGN 280
Definition at line 135 of file y.tab.h.
TIMEOPT
#define TIMEOPT 279
Definition at line 134 of file y.tab.h.
UNTIL
#define UNTIL 268
Definition at line 123 of file y.tab.h.
WHILE
#define WHILE 267
Definition at line 122 of file y.tab.h.
WORD
#define WORD 281
Definition at line 136 of file y.tab.h.
yacc_EOF
#define yacc_EOF 305
Definition at line 160 of file y.tab.h.
YYDEBUG
#define YYDEBUG 0
Definition at line 42 of file y.tab.h.
YYEMPTY
#define YYEMPTY -2
Definition at line 109 of file y.tab.h.
YYEOF
#define YYEOF 0
Definition at line 110 of file y.tab.h.
YYerror
#define YYerror 256
Definition at line 111 of file y.tab.h.
YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
Definition at line 181 of file y.tab.h.
YYSTYPE_IS_TRIVIAL
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 180 of file y.tab.h.
YYTOKENTYPE
#define YYTOKENTYPE
Definition at line 50 of file y.tab.h.
YYUNDEF
#define YYUNDEF 257
Definition at line 112 of file y.tab.h.
Typedef Documentation
YYSTYPE
typedef union YYSTYPE YYSTYPE
Definition at line 1 of file y.tab.h.
yytoken_kind_t
typedef enum yytokentype yytoken_kind_t
Definition at line 1 of file y.tab.h.
Enumeration Type Documentation
yytokentype
enum yytokentype
Enumerator
EQUOP2
CMPOP2
ADDOP2
MULOP2
NUMBER
YYEMPTY
YYEOF
YYerror
YYUNDEF
IF
THEN
ELSE
ELIF
FI
CASE
ESAC
FOR
SELECT
WHILE
UNTIL
DO
DONE
FUNCTION
COPROC
COND_START
COND_END
COND_ERROR
IN
BANG
TIME
TIMEOPT
TIMEIGN
WORD
ASSIGNMENT_WORD
REDIR_WORD
NUMBER
ARITH_CMD
ARITH_FOR_EXPRS
COND_CMD
AND_AND
OR_OR
GREATER_GREATER
LESS_LESS
LESS_AND
LESS_LESS_LESS
GREATER_AND
SEMI_SEMI
SEMI_AND
SEMI_SEMI_AND
LESS_LESS_MINUS
AND_GREATER
AND_GREATER_GREATER
LESS_GREATER
GREATER_BAR
BAR_AND
DOLPAREN
yacc_EOF
YYEMPTY
YYEOF
YYerror
YYUNDEF
IF
THEN
ELSE
ELIF
FI
CASE
ESAC
FOR
SELECT
WHILE
UNTIL
DO
DONE
FUNCTION
COPROC
COND_START
COND_END
COND_ERROR
IN
BANG
TIME
TIMEOPT
TIMEIGN
WORD
ASSIGNMENT_WORD
REDIR_WORD
NUMBER
ARITH_CMD
ARITH_FOR_EXPRS
COND_CMD
AND_AND
OR_OR
GREATER_GREATER
LESS_LESS
LESS_AND
LESS_LESS_LESS
GREATER_AND
SEMI_SEMI
SEMI_AND
SEMI_SEMI_AND
LESS_LESS_MINUS
AND_GREATER
AND_GREATER_GREATER
LESS_GREATER
GREATER_BAR
BAR_AND
DOLPAREN
yacc_EOF
Definition at line 51 of file y.tab.h.
   {
     YYEMPTY = -2,
     YYEOF = 0,                     /* "end of file"  */
     YYerror = 256,                 /* error  */
     YYUNDEF = 257,                 /* "invalid token"  */
     IF = 258,                      /* IF  */
     THEN = 259,                    /* THEN  */
     ELSE = 260,                    /* ELSE  */
     ELIF = 261,                    /* ELIF  */
     FI = 262,                      /* FI  */
     CASE = 263,                    /* CASE  */
     ESAC = 264,                    /* ESAC  */
     FOR = 265,                     /* FOR  */
     SELECT = 266,                  /* SELECT  */
     WHILE = 267,                   /* WHILE  */
     UNTIL = 268,                   /* UNTIL  */
     DO = 269,                      /* DO  */
     DONE = 270,                    /* DONE  */
     FUNCTION = 271,                /* FUNCTION  */
     COPROC = 272,                  /* COPROC  */
     COND_START = 273,              /* COND_START  */
     COND_END = 274,                /* COND_END  */
     COND_ERROR = 275,              /* COND_ERROR  */
     IN = 276,                      /* IN  */
     BANG = 277,                    /* BANG  */
     TIME = 278,                    /* TIME  */
     TIMEOPT = 279,                 /* TIMEOPT  */
     TIMEIGN = 280,                 /* TIMEIGN  */
     WORD = 281,                    /* WORD  */
     ASSIGNMENT_WORD = 282,         /* ASSIGNMENT_WORD  */
     REDIR_WORD = 283,              /* REDIR_WORD  */
     NUMBER = 284,                  /* NUMBER  */
     ARITH_CMD = 285,               /* ARITH_CMD  */
     ARITH_FOR_EXPRS = 286,         /* ARITH_FOR_EXPRS  */
     COND_CMD = 287,                /* COND_CMD  */
     AND_AND = 288,                 /* AND_AND  */
     OR_OR = 289,                   /* OR_OR  */
     GREATER_GREATER = 290,         /* GREATER_GREATER  */
     LESS_LESS = 291,               /* LESS_LESS  */
     LESS_AND = 292,                /* LESS_AND  */
     LESS_LESS_LESS = 293,          /* LESS_LESS_LESS  */
     GREATER_AND = 294,             /* GREATER_AND  */
     SEMI_SEMI = 295,               /* SEMI_SEMI  */
     SEMI_AND = 296,                /* SEMI_AND  */
     SEMI_SEMI_AND = 297,           /* SEMI_SEMI_AND  */
     LESS_LESS_MINUS = 298,         /* LESS_LESS_MINUS  */
     AND_GREATER = 299,             /* AND_GREATER  */
     AND_GREATER_GREATER = 300,     /* AND_GREATER_GREATER  */
     LESS_GREATER = 301,            /* LESS_GREATER  */
     GREATER_BAR = 302,             /* GREATER_BAR  */
     BAR_AND = 303,                 /* BAR_AND  */
     DOLPAREN = 304,                /* DOLPAREN  */
     yacc_EOF = 305                 /* yacc_EOF  */
   };
Function Documentation
yyparse()
int yyparse (void)
Definition at line 1700 of file y.tab.c.
 {
     yy_state_fast_t yystate = 0;
     /* Number of tokens to shift before error messages enabled.  */
     int yyerrstatus = 0;
     /* Refer to the stacks through separate pointers, to allow yyoverflow
        to reallocate them elsewhere.  */
     /* Their size.  */
     YYPTRDIFF_T yystacksize = YYINITDEPTH;
     /* The state stack: array, bottom, top.  */
     yy_state_t yyssa[YYINITDEPTH];
     yy_state_t *yyss = yyssa;
     yy_state_t *yyssp = yyss;
     /* The semantic value stack: array, bottom, top.  */
     YYSTYPE yyvsa[YYINITDEPTH];
     YYSTYPE *yyvs = yyvsa;
     YYSTYPE *yyvsp = yyvs;
   int yyn;
   /* The return value of yyparse.  */
   int yyresult;
   /* Lookahead symbol kind.  */
   yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yychar = YYEMPTY; /* Cause a token to be read.  */
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
 yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
 /*--------------------------------------------------------------------.
 | yysetstate -- set current state (the top of the stack) to yystate.  |
 `--------------------------------------------------------------------*/
 yysetstate:
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
   YY_IGNORE_USELESS_CAST_BEGIN
   *yyssp = YY_CAST (yy_state_t, yystate);
   YY_IGNORE_USELESS_CAST_END
   YY_STACK_PRINT (yyss, yyssp);
   if (yyss + yystacksize - 1 <= yyssp)
 #if !defined yyoverflow && !defined YYSTACK_RELOCATE
     YYNOMEM;
 #else
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYPTRDIFF_T yysize = yyssp - yyss + 1;
 # if defined yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         yy_state_t *yyss1 = yyss;
         YYSTYPE *yyvs1 = yyvs;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow (YY_("memory exhausted"),
                     &yyss1, yysize * YYSIZEOF (*yyssp),
                     &yyvs1, yysize * YYSIZEOF (*yyvsp),
                     &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 # else /* defined YYSTACK_RELOCATE */
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         YYNOMEM;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yy_state_t *yyss1 = yyss;
         union yyalloc *yyptr =
           YY_CAST (union yyalloc *,
                    YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
         if (! yyptr)
           YYNOMEM;
         YYSTACK_RELOCATE (yyss_alloc, yyss);
         YYSTACK_RELOCATE (yyvs_alloc, yyvs);
 #  undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE (yyss1);
       }
 # endif
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YY_IGNORE_USELESS_CAST_BEGIN
       YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                   YY_CAST (long, yystacksize)));
       YY_IGNORE_USELESS_CAST_END
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
 #endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yypact_value_is_default (yyn))
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token\n"));
       yychar = yylex ();
     }
   if (yychar <= YYEOF)
     {
       yychar = YYEOF;
       yytoken = YYSYMBOL_YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else if (yychar == YYerror)
     {
       /* The scanner already issued an error message, process directly
          to error recovery.  But do not keep the error token as
          lookahead, it is too special and may lead us to an endless
          loop in error recovery. */
       yychar = YYUNDEF;
       yytoken = YYSYMBOL_YYerror;
       goto yyerrlab1;
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yytable_value_is_error (yyn))
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   yystate = yyn;
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      '$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
   case 2: /* inputunit: simple_list simple_list_terminator  */
 #line 396 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Case of regular command.  Discard the error
                  safety net,and return the command just parsed. */
               global_command = (yyvsp[-1].command);
               eof_encountered = 0;
               /* discard_parser_constructs (0); */
               if (parser_state & PST_CMDSUBST)
                 parser_state |= PST_EOFTOKEN;
               YYACCEPT;
             }
 #line 1954 "y.tab.c"
     break;
   case 3: /* inputunit: comsub  */
 #line 407 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* This is special; look at the production and how
                  parse_comsub sets token_to_read */
               global_command = (yyvsp[0].command);
               eof_encountered = 0;
               YYACCEPT;
             }
 #line 1966 "y.tab.c"
     break;
   case 4: /* inputunit: '\n'  */
 #line 415 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Case of regular command, but not a very
                  interesting one.  Return a NULL command. */
               global_command = (COMMAND *)NULL;
               if (parser_state & PST_CMDSUBST)
                 parser_state |= PST_EOFTOKEN;
               YYACCEPT;
             }
 #line 1979 "y.tab.c"
     break;
   case 5: /* inputunit: error '\n'  */
 #line 424 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Error during parsing.  Return NULL command. */
               global_command = (COMMAND *)NULL;
               eof_encountered = 0;
               /* discard_parser_constructs (1); */
               if (interactive && parse_and_execute_level == 0)
                 {
                   YYACCEPT;
                 }
               else
                 {
                   YYABORT;
                 }
             }
 #line 1998 "y.tab.c"
     break;
   case 6: /* inputunit: error yacc_EOF  */
 #line 439 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* EOF after an error.  Do ignoreeof or not.  Really
                  only interesting in non-interactive shells */
               global_command = (COMMAND *)NULL;
               if (last_command_exit_value == 0)
                 last_command_exit_value = EX_BADUSAGE;  /* force error return */
               if (interactive && parse_and_execute_level == 0)
                 {
                   handle_eof_input_unit ();
                   YYACCEPT;
                 }
               else
                 {
                   YYABORT;
                 }
             }
 #line 2019 "y.tab.c"
     break;
   case 7: /* inputunit: yacc_EOF  */
 #line 456 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Case of EOF seen by itself.  Do ignoreeof or
                  not. */
               global_command = (COMMAND *)NULL;
               handle_eof_input_unit ();
               YYACCEPT;
             }
 #line 2031 "y.tab.c"
     break;
   case 8: /* word_list: WORD  */
 #line 466 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (WORD_LIST *)NULL); }
 #line 2037 "y.tab.c"
     break;
   case 9: /* word_list: word_list WORD  */
 #line 468 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (yyvsp[-1].word_list)); }
 #line 2043 "y.tab.c"
     break;
   case 10: /* redirection: '>' WORD  */
 #line 472 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_direction, redir, 0);
             }
 #line 2053 "y.tab.c"
     break;
   case 11: /* redirection: '<' WORD  */
 #line 478 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_direction, redir, 0);
             }
 #line 2063 "y.tab.c"
     break;
   case 12: /* redirection: NUMBER '>' WORD  */
 #line 484 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_direction, redir, 0);
             }
 #line 2073 "y.tab.c"
     break;
   case 13: /* redirection: NUMBER '<' WORD  */
 #line 490 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_direction, redir, 0);
             }
 #line 2083 "y.tab.c"
     break;
   case 14: /* redirection: REDIR_WORD '>' WORD  */
 #line 496 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_direction, redir, REDIR_VARASSIGN);
             }
 #line 2093 "y.tab.c"
     break;
   case 15: /* redirection: REDIR_WORD '<' WORD  */
 #line 502 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_direction, redir, REDIR_VARASSIGN);
             }
 #line 2103 "y.tab.c"
     break;
   case 16: /* redirection: GREATER_GREATER WORD  */
 #line 508 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_appending_to, redir, 0);
             }
 #line 2113 "y.tab.c"
     break;
   case 17: /* redirection: NUMBER GREATER_GREATER WORD  */
 #line 514 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_appending_to, redir, 0);
             }
 #line 2123 "y.tab.c"
     break;
   case 18: /* redirection: REDIR_WORD GREATER_GREATER WORD  */
 #line 520 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_appending_to, redir, REDIR_VARASSIGN);
             }
 #line 2133 "y.tab.c"
     break;
   case 19: /* redirection: GREATER_BAR WORD  */
 #line 526 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_force, redir, 0);
             }
 #line 2143 "y.tab.c"
     break;
   case 20: /* redirection: NUMBER GREATER_BAR WORD  */
 #line 532 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_force, redir, 0);
             }
 #line 2153 "y.tab.c"
     break;
   case 21: /* redirection: REDIR_WORD GREATER_BAR WORD  */
 #line 538 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_force, redir, REDIR_VARASSIGN);
             }
 #line 2163 "y.tab.c"
     break;
   case 22: /* redirection: LESS_GREATER WORD  */
 #line 544 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_output, redir, 0);
             }
 #line 2173 "y.tab.c"
     break;
   case 23: /* redirection: NUMBER LESS_GREATER WORD  */
 #line 550 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_output, redir, 0);
             }
 #line 2183 "y.tab.c"
     break;
   case 24: /* redirection: REDIR_WORD LESS_GREATER WORD  */
 #line 556 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_output, redir, REDIR_VARASSIGN);
             }
 #line 2193 "y.tab.c"
     break;
   case 25: /* redirection: LESS_LESS WORD  */
 #line 562 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2204 "y.tab.c"
     break;
   case 26: /* redirection: NUMBER LESS_LESS WORD  */
 #line 569 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2215 "y.tab.c"
     break;
   case 27: /* redirection: REDIR_WORD LESS_LESS WORD  */
 #line 576 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_until, redir, REDIR_VARASSIGN);
               push_heredoc ((yyval.redirect));
             }
 #line 2226 "y.tab.c"
     break;
   case 28: /* redirection: LESS_LESS_MINUS WORD  */
 #line 583 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_deblank_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2237 "y.tab.c"
     break;
   case 29: /* redirection: NUMBER LESS_LESS_MINUS WORD  */
 #line 590 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_deblank_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2248 "y.tab.c"
     break;
   case 30: /* redirection: REDIR_WORD LESS_LESS_MINUS WORD  */
 #line 597 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_deblank_reading_until, redir, REDIR_VARASSIGN);
               push_heredoc ((yyval.redirect));
             }
 #line 2259 "y.tab.c"
     break;
   case 31: /* redirection: LESS_LESS_LESS WORD  */
 #line 604 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_string, redir, 0);
             }
 #line 2269 "y.tab.c"
     break;
   case 32: /* redirection: NUMBER LESS_LESS_LESS WORD  */
 #line 610 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_string, redir, 0);
             }
 #line 2279 "y.tab.c"
     break;
   case 33: /* redirection: REDIR_WORD LESS_LESS_LESS WORD  */
 #line 616 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_string, redir, REDIR_VARASSIGN);
             }
 #line 2289 "y.tab.c"
     break;
   case 34: /* redirection: LESS_AND NUMBER  */
 #line 622 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_input, redir, 0);
             }
 #line 2299 "y.tab.c"
     break;
   case 35: /* redirection: NUMBER LESS_AND NUMBER  */
 #line 628 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_input, redir, 0);
             }
 #line 2309 "y.tab.c"
     break;
   case 36: /* redirection: REDIR_WORD LESS_AND NUMBER  */
 #line 634 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_input, redir, REDIR_VARASSIGN);
             }
 #line 2319 "y.tab.c"
     break;
   case 37: /* redirection: GREATER_AND NUMBER  */
 #line 640 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_output, redir, 0);
             }
 #line 2329 "y.tab.c"
     break;
   case 38: /* redirection: NUMBER GREATER_AND NUMBER  */
 #line 646 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_output, redir, 0);
             }
 #line 2339 "y.tab.c"
     break;
   case 39: /* redirection: REDIR_WORD GREATER_AND NUMBER  */
 #line 652 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_output, redir, REDIR_VARASSIGN);
             }
 #line 2349 "y.tab.c"
     break;
   case 40: /* redirection: LESS_AND WORD  */
 #line 658 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_input_word, redir, 0);
             }
 #line 2359 "y.tab.c"
     break;
   case 41: /* redirection: NUMBER LESS_AND WORD  */
 #line 664 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_input_word, redir, 0);
             }
 #line 2369 "y.tab.c"
     break;
   case 42: /* redirection: REDIR_WORD LESS_AND WORD  */
 #line 670 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_input_word, redir, REDIR_VARASSIGN);
             }
 #line 2379 "y.tab.c"
     break;
   case 43: /* redirection: GREATER_AND WORD  */
 #line 676 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_output_word, redir, 0);
             }
 #line 2389 "y.tab.c"
     break;
   case 44: /* redirection: NUMBER GREATER_AND WORD  */
 #line 682 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_output_word, redir, 0);
             }
 #line 2399 "y.tab.c"
     break;
   case 45: /* redirection: REDIR_WORD GREATER_AND WORD  */
 #line 688 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_output_word, redir, REDIR_VARASSIGN);
             }
 #line 2409 "y.tab.c"
     break;
   case 46: /* redirection: GREATER_AND '-'  */
 #line 694 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2419 "y.tab.c"
     break;
   case 47: /* redirection: NUMBER GREATER_AND '-'  */
 #line 700 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2429 "y.tab.c"
     break;
   case 48: /* redirection: REDIR_WORD GREATER_AND '-'  */
 #line 706 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, REDIR_VARASSIGN);
             }
 #line 2439 "y.tab.c"
     break;
   case 49: /* redirection: LESS_AND '-'  */
 #line 712 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2449 "y.tab.c"
     break;
   case 50: /* redirection: NUMBER LESS_AND '-'  */
 #line 718 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2459 "y.tab.c"
     break;
   case 51: /* redirection: REDIR_WORD LESS_AND '-'  */
 #line 724 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, REDIR_VARASSIGN);
             }
 #line 2469 "y.tab.c"
     break;
   case 52: /* redirection: AND_GREATER WORD  */
 #line 730 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_err_and_out, redir, 0);
             }
 #line 2479 "y.tab.c"
     break;
   case 53: /* redirection: AND_GREATER_GREATER WORD  */
 #line 736 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_append_err_and_out, redir, 0);
             }
 #line 2489 "y.tab.c"
     break;
   case 54: /* simple_command_element: WORD  */
 #line 744 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.element).word = (yyvsp[0].word); (yyval.element).redirect = 0; }
 #line 2495 "y.tab.c"
     break;
   case 55: /* simple_command_element: ASSIGNMENT_WORD  */
 #line 746 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.element).word = (yyvsp[0].word); (yyval.element).redirect = 0; }
 #line 2501 "y.tab.c"
     break;
   case 56: /* simple_command_element: redirection  */
 #line 748 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.element).redirect = (yyvsp[0].redirect); (yyval.element).word = 0; }
 #line 2507 "y.tab.c"
     break;
   case 57: /* redirection_list: redirection  */
 #line 752 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.redirect) = (yyvsp[0].redirect);
             }
 #line 2515 "y.tab.c"
     break;
   case 58: /* redirection_list: redirection_list redirection  */
 #line 756 "/usr/local/src/chet/src/bash/src/parse.y"
{
               register REDIRECT *t;
               for (t = (yyvsp[-1].redirect); t->next; t = t->next)
                 ;
               t->next = (yyvsp[0].redirect);
               (yyval.redirect) = (yyvsp[-1].redirect);
             }
 #line 2528 "y.tab.c"
     break;
   case 59: /* simple_command: simple_command_element  */
 #line 767 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_simple_command ((yyvsp[0].element), (COMMAND *)NULL); }
 #line 2534 "y.tab.c"
     break;
   case 60: /* simple_command: simple_command simple_command_element  */
 #line 769 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_simple_command ((yyvsp[0].element), (yyvsp[-1].command)); }
 #line 2540 "y.tab.c"
     break;
   case 61: /* command: simple_command  */
 #line 773 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = clean_simple_command ((yyvsp[0].command)); }
 #line 2546 "y.tab.c"
     break;
   case 62: /* command: shell_command  */
 #line 775 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2552 "y.tab.c"
     break;
   case 63: /* command: shell_command redirection_list  */
 #line 777 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = (yyvsp[-1].command);
             }
 #line 2572 "y.tab.c"
     break;
   case 64: /* command: function_def  */
 #line 793 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2578 "y.tab.c"
     break;
   case 65: /* command: coproc  */
 #line 795 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2584 "y.tab.c"
     break;
   case 66: /* shell_command: for_command  */
 #line 799 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2590 "y.tab.c"
     break;
   case 67: /* shell_command: case_command  */
 #line 801 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2596 "y.tab.c"
     break;
   case 68: /* shell_command: WHILE compound_list DO compound_list DONE  */
 #line 803 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_while_command ((yyvsp[-3].command), (yyvsp[-1].command)); }
 #line 2602 "y.tab.c"
     break;
   case 69: /* shell_command: UNTIL compound_list DO compound_list DONE  */
 #line 805 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_until_command ((yyvsp[-3].command), (yyvsp[-1].command)); }
 #line 2608 "y.tab.c"
     break;
   case 70: /* shell_command: select_command  */
 #line 807 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2614 "y.tab.c"
     break;
   case 71: /* shell_command: if_command  */
 #line 809 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2620 "y.tab.c"
     break;
   case 72: /* shell_command: subshell  */
 #line 811 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2626 "y.tab.c"
     break;
   case 73: /* shell_command: group_command  */
 #line 813 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2632 "y.tab.c"
     break;
   case 74: /* shell_command: arith_command  */
 #line 815 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2638 "y.tab.c"
     break;
   case 75: /* shell_command: cond_command  */
 #line 817 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2644 "y.tab.c"
     break;
   case 76: /* shell_command: arith_for_command  */
 #line 819 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2650 "y.tab.c"
     break;
   case 77: /* for_command: FOR WORD newline_list DO compound_list DONE  */
 #line 823 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2659 "y.tab.c"
     break;
   case 78: /* for_command: FOR WORD newline_list '{' compound_list '}'  */
 #line 828 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2668 "y.tab.c"
     break;
   case 79: /* for_command: FOR WORD ';' newline_list DO compound_list DONE  */
 #line 833 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2677 "y.tab.c"
     break;
   case 80: /* for_command: FOR WORD ';' newline_list '{' compound_list '}'  */
 #line 838 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2686 "y.tab.c"
     break;
   case 81: /* for_command: FOR WORD newline_list IN word_list list_terminator newline_list DO compound_list DONE  */
 #line 843 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2695 "y.tab.c"
     break;
   case 82: /* for_command: FOR WORD newline_list IN word_list list_terminator newline_list '{' compound_list '}'  */
 #line 848 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2704 "y.tab.c"
     break;
   case 83: /* for_command: FOR WORD newline_list IN list_terminator newline_list DO compound_list DONE  */
 #line 853 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2713 "y.tab.c"
     break;
   case 84: /* for_command: FOR WORD newline_list IN list_terminator newline_list '{' compound_list '}'  */
 #line 858 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2722 "y.tab.c"
     break;
   case 85: /* arith_for_command: FOR ARITH_FOR_EXPRS list_terminator newline_list DO compound_list DONE  */
 #line 865 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-5].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2732 "y.tab.c"
     break;
   case 86: /* arith_for_command: FOR ARITH_FOR_EXPRS list_terminator newline_list '{' compound_list '}'  */
 #line 871 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-5].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2742 "y.tab.c"
     break;
   case 87: /* arith_for_command: FOR ARITH_FOR_EXPRS DO compound_list DONE  */
 #line 877 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-3].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2752 "y.tab.c"
     break;
   case 88: /* arith_for_command: FOR ARITH_FOR_EXPRS '{' compound_list '}'  */
 #line 883 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-3].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2762 "y.tab.c"
     break;
   case 89: /* select_command: SELECT WORD newline_list DO compound_list DONE  */
 #line 891 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2771 "y.tab.c"
     break;
   case 90: /* select_command: SELECT WORD newline_list '{' compound_list '}'  */
 #line 896 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2780 "y.tab.c"
     break;
   case 91: /* select_command: SELECT WORD ';' newline_list DO compound_list DONE  */
 #line 901 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2789 "y.tab.c"
     break;
   case 92: /* select_command: SELECT WORD ';' newline_list '{' compound_list '}'  */
 #line 906 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2798 "y.tab.c"
     break;
   case 93: /* select_command: SELECT WORD newline_list IN word_list list_terminator newline_list DO compound_list DONE  */
 #line 911 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2807 "y.tab.c"
     break;
   case 94: /* select_command: SELECT WORD newline_list IN word_list list_terminator newline_list '{' compound_list '}'  */
 #line 916 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2816 "y.tab.c"
     break;
   case 95: /* select_command: SELECT WORD newline_list IN list_terminator newline_list DO compound_list DONE  */
 #line 921 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2825 "y.tab.c"
     break;
   case 96: /* select_command: SELECT WORD newline_list IN list_terminator newline_list '{' compound_list '}'  */
 #line 926 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2834 "y.tab.c"
     break;
   case 97: /* case_command: CASE WORD newline_list IN newline_list ESAC  */
 #line 933 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_case_command ((yyvsp[-4].word), (PATTERN_LIST *)NULL, word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2843 "y.tab.c"
     break;
   case 98: /* case_command: CASE WORD newline_list IN case_clause_sequence newline_list ESAC  */
 #line 938 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_case_command ((yyvsp[-5].word), (yyvsp[-2].pattern), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2852 "y.tab.c"
     break;
   case 99: /* case_command: CASE WORD newline_list IN case_clause ESAC  */
 #line 943 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_case_command ((yyvsp[-4].word), (yyvsp[-1].pattern), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2861 "y.tab.c"
     break;
   case 100: /* function_def: WORD '(' ')' newline_list function_body  */
 #line 950 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-4].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2867 "y.tab.c"
     break;
   case 101: /* function_def: FUNCTION WORD '(' ')' newline_list function_body  */
 #line 952 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-4].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2873 "y.tab.c"
     break;
   case 102: /* function_def: FUNCTION WORD function_body  */
 #line 954 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-1].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2879 "y.tab.c"
     break;
   case 103: /* function_def: FUNCTION WORD '\n' newline_list function_body  */
 #line 956 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-3].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2885 "y.tab.c"
     break;
   case 104: /* function_body: shell_command  */
 #line 960 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2891 "y.tab.c"
     break;
   case 105: /* function_body: shell_command redirection_list  */
 #line 962 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               /* According to Posix.2 3.9.5, redirections
                  specified after the body of a function should
                  be attached to the function and performed when
                  the function is executed, not as part of the
                  function definition command. */
               /* XXX - I don't think it matters, but we might
                  want to change this in the future to avoid
                  problems differentiating between a function
                  definition with a redirection and a function
                  definition containing a single command with a
                  redirection.  The two are semantically equivalent,
                  though -- the only difference is in how the
                  command printing code displays the redirections. */
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = (yyvsp[-1].command);
             }
 #line 2924 "y.tab.c"
     break;
   case 106: /* subshell: '(' compound_list ')'  */
 #line 993 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_subshell_command ((yyvsp[-1].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL;
             }
 #line 2933 "y.tab.c"
     break;
   case 107: /* comsub: DOLPAREN compound_list ')'  */
 #line 1000 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[-1].command);
             }
 #line 2941 "y.tab.c"
     break;
   case 108: /* comsub: DOLPAREN newline_list ')'  */
 #line 1004 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (COMMAND *)NULL;
             }
 #line 2949 "y.tab.c"
     break;
   case 109: /* coproc: COPROC shell_command  */
 #line 1010 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_coproc_command ("COPROC", (yyvsp[0].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 2958 "y.tab.c"
     break;
   case 110: /* coproc: COPROC shell_command redirection_list  */
 #line 1015 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = make_coproc_command ("COPROC", (yyvsp[-1].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 2979 "y.tab.c"
     break;
   case 111: /* coproc: COPROC WORD shell_command  */
 #line 1032 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_coproc_command ((yyvsp[-1].word)->word, (yyvsp[0].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 2988 "y.tab.c"
     break;
   case 112: /* coproc: COPROC WORD shell_command redirection_list  */
 #line 1037 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = make_coproc_command ((yyvsp[-2].word)->word, (yyvsp[-1].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 3009 "y.tab.c"
     break;
   case 113: /* coproc: COPROC simple_command  */
 #line 1054 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_coproc_command ("COPROC", clean_simple_command ((yyvsp[0].command)));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 3018 "y.tab.c"
     break;
   case 114: /* if_command: IF compound_list THEN compound_list FI  */
 #line 1061 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-3].command), (yyvsp[-1].command), (COMMAND *)NULL); }
 #line 3024 "y.tab.c"
     break;
   case 115: /* if_command: IF compound_list THEN compound_list ELSE compound_list FI  */
 #line 1063 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-5].command), (yyvsp[-3].command), (yyvsp[-1].command)); }
 #line 3030 "y.tab.c"
     break;
   case 116: /* if_command: IF compound_list THEN compound_list elif_clause FI  */
 #line 1065 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-4].command), (yyvsp[-2].command), (yyvsp[-1].command)); }
 #line 3036 "y.tab.c"
     break;
   case 117: /* group_command: '{' compound_list '}'  */
 #line 1070 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_group_command ((yyvsp[-1].command)); }
 #line 3042 "y.tab.c"
     break;
   case 118: /* arith_command: ARITH_CMD  */
 #line 1074 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_arith_command ((yyvsp[0].word_list)); }
 #line 3048 "y.tab.c"
     break;
   case 119: /* cond_command: COND_START COND_CMD COND_END  */
 #line 1078 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[-1].command); }
 #line 3054 "y.tab.c"
     break;
   case 120: /* elif_clause: ELIF compound_list THEN compound_list  */
 #line 1082 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-2].command), (yyvsp[0].command), (COMMAND *)NULL); }
 #line 3060 "y.tab.c"
     break;
   case 121: /* elif_clause: ELIF compound_list THEN compound_list ELSE compound_list  */
 #line 1084 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-4].command), (yyvsp[-2].command), (yyvsp[0].command)); }
 #line 3066 "y.tab.c"
     break;
   case 122: /* elif_clause: ELIF compound_list THEN compound_list elif_clause  */
 #line 1086 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-3].command), (yyvsp[-1].command), (yyvsp[0].command)); }
 #line 3072 "y.tab.c"
     break;
   case 124: /* case_clause: case_clause_sequence pattern_list  */
 #line 1091 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[0].pattern)->next = (yyvsp[-1].pattern); (yyval.pattern) = (yyvsp[0].pattern); }
 #line 3078 "y.tab.c"
     break;
   case 125: /* pattern_list: newline_list pattern ')' compound_list  */
 #line 1095 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (yyvsp[0].command)); }
 #line 3084 "y.tab.c"
     break;
   case 126: /* pattern_list: newline_list pattern ')' newline_list  */
 #line 1097 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (COMMAND *)NULL); }
 #line 3090 "y.tab.c"
     break;
   case 127: /* pattern_list: newline_list '(' pattern ')' compound_list  */
 #line 1099 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (yyvsp[0].command)); }
 #line 3096 "y.tab.c"
     break;
   case 128: /* pattern_list: newline_list '(' pattern ')' newline_list  */
 #line 1101 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (COMMAND *)NULL); }
 #line 3102 "y.tab.c"
     break;
   case 129: /* case_clause_sequence: pattern_list SEMI_SEMI  */
 #line 1105 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3108 "y.tab.c"
     break;
   case 130: /* case_clause_sequence: case_clause_sequence pattern_list SEMI_SEMI  */
 #line 1107 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->next = (yyvsp[-2].pattern); (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3114 "y.tab.c"
     break;
   case 131: /* case_clause_sequence: pattern_list SEMI_AND  */
 #line 1109 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_FALLTHROUGH; (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3120 "y.tab.c"
     break;
   case 132: /* case_clause_sequence: case_clause_sequence pattern_list SEMI_AND  */
 #line 1111 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_FALLTHROUGH; (yyvsp[-1].pattern)->next = (yyvsp[-2].pattern); (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3126 "y.tab.c"
     break;
   case 133: /* case_clause_sequence: pattern_list SEMI_SEMI_AND  */
 #line 1113 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_TESTNEXT; (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3132 "y.tab.c"
     break;
   case 134: /* case_clause_sequence: case_clause_sequence pattern_list SEMI_SEMI_AND  */
 #line 1115 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_TESTNEXT; (yyvsp[-1].pattern)->next = (yyvsp[-2].pattern); (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3138 "y.tab.c"
     break;
   case 135: /* pattern: WORD  */
 #line 1119 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (WORD_LIST *)NULL); }
 #line 3144 "y.tab.c"
     break;
   case 136: /* pattern: pattern '|' WORD  */
 #line 1121 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (yyvsp[-2].word_list)); }
 #line 3150 "y.tab.c"
     break;
   case 137: /* compound_list: newline_list list0  */
 #line 1130 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[0].command);
               if (need_here_doc && last_read_token == '\n')
                 gather_here_documents ();
              }
 #line 3160 "y.tab.c"
     break;
   case 138: /* compound_list: newline_list list1  */
 #line 1136 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[0].command);
             }
 #line 3168 "y.tab.c"
     break;
   case 140: /* list0: list1 '&' newline_list  */
 #line 1143 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-2].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-2].command), (COMMAND *)NULL, '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-2].command), (COMMAND *)NULL, '&');
             }
 #line 3179 "y.tab.c"
     break;
   case 142: /* list1: list1 AND_AND newline_list list1  */
 #line 1154 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), AND_AND); }
 #line 3185 "y.tab.c"
     break;
   case 143: /* list1: list1 OR_OR newline_list list1  */
 #line 1156 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), OR_OR); }
 #line 3191 "y.tab.c"
     break;
   case 144: /* list1: list1 '&' newline_list list1  */
 #line 1158 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-3].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-3].command), (yyvsp[0].command), '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '&');
             }
 #line 3202 "y.tab.c"
     break;
   case 145: /* list1: list1 ';' newline_list list1  */
 #line 1165 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), ';'); }
 #line 3208 "y.tab.c"
     break;
   case 146: /* list1: list1 '\n' newline_list list1  */
 #line 1167 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if (parser_state & PST_CMDSUBST)
                 (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '\n');
               else
                 (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), ';');
             }
 #line 3219 "y.tab.c"
     break;
   case 147: /* list1: pipeline_command  */
 #line 1174 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3225 "y.tab.c"
     break;
   case 150: /* list_terminator: '\n'  */
 #line 1182 "/usr/local/src/chet/src/bash/src/parse.y"
                 { (yyval.number) = '\n'; }
 #line 3231 "y.tab.c"
     break;
   case 151: /* list_terminator: ';'  */
 #line 1184 "/usr/local/src/chet/src/bash/src/parse.y"
                 { (yyval.number) = ';'; }
 #line 3237 "y.tab.c"
     break;
   case 152: /* list_terminator: yacc_EOF  */
 #line 1186 "/usr/local/src/chet/src/bash/src/parse.y"
                 { (yyval.number) = yacc_EOF; }
 #line 3243 "y.tab.c"
     break;
   case 155: /* simple_list: simple_list1  */
 #line 1200 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[0].command);
               if (need_here_doc)
                 gather_here_documents ();   /* XXX */
               if ((parser_state & PST_CMDSUBST) && current_token == shell_eof_token)
                 {
 INTERNAL_DEBUG (("LEGACY: parser: command substitution simple_list1 -> simple_list"));
                   global_command = (yyvsp[0].command);
                   eof_encountered = 0;
                   if (bash_input.type == st_string)
                 rewind_input_string ();
                   YYACCEPT;
                 }
             }
 #line 3262 "y.tab.c"
     break;
   case 156: /* simple_list: simple_list1 '&'  */
 #line 1215 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-1].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-1].command), (COMMAND *)NULL, '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-1].command), (COMMAND *)NULL, '&');
               if (need_here_doc)
                 gather_here_documents (); /* XXX */
               if ((parser_state & PST_CMDSUBST) && current_token == shell_eof_token)
                 {
 INTERNAL_DEBUG (("LEGACY: parser: command substitution simple_list1 '&' -> simple_list"));
                   global_command = (yyvsp[-1].command);
                   eof_encountered = 0;
                   if (bash_input.type == st_string)
                 rewind_input_string ();
                   YYACCEPT;
                 }
             }
 #line 3284 "y.tab.c"
     break;
   case 157: /* simple_list: simple_list1 ';'  */
 #line 1233 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[-1].command);
               if (need_here_doc)
                 gather_here_documents ();   /* XXX */
               if ((parser_state & PST_CMDSUBST) && current_token == shell_eof_token)
                 {
 INTERNAL_DEBUG (("LEGACY: parser: command substitution simple_list1 ';' -> simple_list"));
                   global_command = (yyvsp[-1].command);
                   eof_encountered = 0;
                   if (bash_input.type == st_string)
                 rewind_input_string ();
                   YYACCEPT;
                 }
             }
 #line 3303 "y.tab.c"
     break;
   case 158: /* simple_list1: simple_list1 AND_AND newline_list simple_list1  */
 #line 1250 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), AND_AND); }
 #line 3309 "y.tab.c"
     break;
   case 159: /* simple_list1: simple_list1 OR_OR newline_list simple_list1  */
 #line 1252 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), OR_OR); }
 #line 3315 "y.tab.c"
     break;
   case 160: /* simple_list1: simple_list1 '&' simple_list1  */
 #line 1254 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-2].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-2].command), (yyvsp[0].command), '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-2].command), (yyvsp[0].command), '&');
             }
 #line 3326 "y.tab.c"
     break;
   case 161: /* simple_list1: simple_list1 ';' simple_list1  */
 #line 1261 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-2].command), (yyvsp[0].command), ';'); }
 #line 3332 "y.tab.c"
     break;
   case 162: /* simple_list1: pipeline_command  */
 #line 1264 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3338 "y.tab.c"
     break;
   case 163: /* pipeline_command: pipeline  */
 #line 1268 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3344 "y.tab.c"
     break;
   case 164: /* pipeline_command: BANG pipeline_command  */
 #line 1270 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[0].command))
                 (yyvsp[0].command)->flags ^= CMD_INVERT_RETURN; /* toggle */
               (yyval.command) = (yyvsp[0].command);
             }
 #line 3354 "y.tab.c"
     break;
   case 165: /* pipeline_command: timespec pipeline_command  */
 #line 1276 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[0].command))
                 (yyvsp[0].command)->flags |= (yyvsp[-1].number);
               (yyval.command) = (yyvsp[0].command);
             }
 #line 3364 "y.tab.c"
     break;
   case 166: /* pipeline_command: timespec list_terminator  */
 #line 1282 "/usr/local/src/chet/src/bash/src/parse.y"
{
               ELEMENT x;
               /* Boy, this is unclean.  `time' by itself can
                  time a null command.  We cheat and push a
                  newline back if the list_terminator was a newline
                  to avoid the double-newline problem (one to
                  terminate this, one to terminate the command) */
               x.word = 0;
               x.redirect = 0;
               (yyval.command) = make_simple_command (x, (COMMAND *)NULL);
               (yyval.command)->flags |= (yyvsp[-1].number);
               /* XXX - let's cheat and push a newline back */
               if ((yyvsp[0].number) == '\n')
                 token_to_read = '\n';
               else if ((yyvsp[0].number) == ';')
                 token_to_read = ';';
               parser_state &= ~PST_REDIRLIST;   /* make_simple_command sets this */
             }
 #line 3388 "y.tab.c"
     break;
   case 167: /* pipeline_command: BANG list_terminator  */
 #line 1302 "/usr/local/src/chet/src/bash/src/parse.y"
{
               ELEMENT x;
               /* This is just as unclean.  Posix says that `!'
                  by itself should be equivalent to `false'.
                  We cheat and push a
                  newline back if the list_terminator was a newline
                  to avoid the double-newline problem (one to
                  terminate this, one to terminate the command) */
               x.word = 0;
               x.redirect = 0;
               (yyval.command) = make_simple_command (x, (COMMAND *)NULL);
               (yyval.command)->flags |= CMD_INVERT_RETURN;
               /* XXX - let's cheat and push a newline back */
               if ((yyvsp[0].number) == '\n')
                 token_to_read = '\n';
               if ((yyvsp[0].number) == ';')
                 token_to_read = ';';
               parser_state &= ~PST_REDIRLIST;   /* make_simple_command sets this */
             }
 #line 3413 "y.tab.c"
     break;
   case 168: /* pipeline: pipeline '|' newline_list pipeline  */
 #line 1325 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '|'); }
 #line 3419 "y.tab.c"
     break;
   case 169: /* pipeline: pipeline BAR_AND newline_list pipeline  */
 #line 1327 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Make cmd1 |& cmd2 equivalent to cmd1 2>&1 | cmd2 */
               COMMAND *tc;
               REDIRECTEE rd, sd;
               REDIRECT *r;
               tc = (yyvsp[-3].command)->type == cm_simple ? (COMMAND *)(yyvsp[-3].command)->value.Simple : (yyvsp[-3].command);
               sd.dest = 2;
               rd.dest = 1;
               r = make_redirection (sd, r_duplicating_output, rd, 0);
               if (tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = r;
                 }
               else
                 tc->redirects = r;
               (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '|');
             }
 #line 3446 "y.tab.c"
     break;
   case 170: /* pipeline: command  */
 #line 1350 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3452 "y.tab.c"
     break;
   case 171: /* timespec: TIME  */
 #line 1354 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE; }
 #line 3458 "y.tab.c"
     break;
   case 172: /* timespec: TIME TIMEOPT  */
 #line 1356 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE|CMD_TIME_POSIX; }
 #line 3464 "y.tab.c"
     break;
   case 173: /* timespec: TIME TIMEIGN  */
 #line 1358 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE|CMD_TIME_POSIX; }
 #line 3470 "y.tab.c"
     break;
   case 174: /* timespec: TIME TIMEOPT TIMEIGN  */
 #line 1360 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE|CMD_TIME_POSIX; }
 #line 3476 "y.tab.c"
     break;
 #line 3480 "y.tab.c"
       default: break;
     }
   /* User semantic actions sometimes alter yychar, and that requires
      that yytoken be updated with the new translation.  We take the
      approach of translating immediately before every use of yytoken.
      One alternative is translating here after every semantic action,
      but that translation would be missed if the semantic action invokes
      YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
      if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
      incorrect destructor might then be invoked immediately.  In the
      case of YYERROR or YYBACKUP, subsequent parser actions might lead
      to an incorrect destructor call or verbose syntax error message
      before the lookahead is translated.  */
   YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   *++yyvsp = yyval;
   /* Now 'shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   {
     const int yylhs = yyr1[yyn] - YYNTOKENS;
     const int yyi = yypgoto[yylhs] + *yyssp;
     yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
                ? yytable[yyi]
                : yydefgoto[yylhs]);
   }
   goto yynewstate;
 /*--------------------------------------.
 | yyerrlab -- here on detecting error.  |
 `--------------------------------------*/
 yyerrlab:
   /* Make sure we have latest lookahead translation.  See comments at
      user semantic actions for why this is necessary.  */
   yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
       yyerror (YY_("syntax error"));
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
          error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct ("Error: discarding",
                       yytoken, &yylval);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers when the user code never invokes YYERROR and the
      label yyerrorlab therefore never appears in user code.  */
   if (0)
     YYERROR;
   ++yynerrs;
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;      /* Each real token shifted decrements this.  */
   /* Pop stack until we find a state that shifts the error token.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (!yypact_value_is_default (yyn))
         {
           yyn += YYSYMBOL_YYerror;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct ("Error: popping",
                   YY_ACCESSING_SYMBOL (yystate), yyvsp);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturnlab;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturnlab;
 /*-----------------------------------------------------------.
 | yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
 `-----------------------------------------------------------*/
 yyexhaustedlab:
   yyerror (YY_("memory exhausted"));
   yyresult = 2;
   goto yyreturnlab;
 /*----------------------------------------------------------.
 | yyreturnlab -- parsing is finished, clean up and return.  |
 `----------------------------------------------------------*/
 yyreturnlab:
   if (yychar != YYEMPTY)
     {
       /* Make sure we have latest lookahead translation.  See comments at
          user semantic actions for why this is necessary.  */
       yytoken = YYTRANSLATE (yychar);
       yydestruct ("Cleanup: discarding lookahead",
                   yytoken, &yylval);
     }
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
                   YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
   return yyresult;
 }
References add_string_to_list, AND_AND, arith_for_lineno, bash_input, CASEPAT_FALLTHROUGH, CASEPAT_TESTNEXT, clean_simple_command(), cm_connection, cm_simple, CMD_COPROC_SUBSHELL, CMD_INVERT_RETURN, CMD_TIME_PIPELINE, CMD_TIME_POSIX, CMD_WANT_SUBSHELL, YYSTYPE::command, command_connect(), connect_async_list(), current_token, REDIRECTEE::dest, YYSTYPE::element, eof_encountered, EX_BADUSAGE, REDIRECTEE::filename, flags, function_bstart, function_dstart, gather_here_documents(), global_command, handle_eof_input_unit(), interactive, INTERNAL_DEBUG, last_command_exit_value, last_read_token, make_arith_command(), make_arith_for_command(), make_case_command(), make_coproc_command(), make_for_command(), make_function_def(), make_group_command(), make_if_command(), make_pattern_list(), make_redirection(), make_select_command(), make_simple_command(), make_subshell_command(), make_until_command(), make_while_command(), make_word_list(), need_here_doc, next, NULL, number(), YYSTYPE::number, OR_OR, parse_and_execute_level, parser_state, pattern, YYSTYPE::pattern, PST_CMDSUBST, PST_EOFTOKEN, PST_REDIRLIST, push_heredoc(), r_append_err_and_out, r_appending_to, r_close_this, r_deblank_reading_until, r_duplicating_input, r_duplicating_input_word, r_duplicating_output, r_duplicating_output_word, r_err_and_out, r_input_direction, r_input_output, r_output_direction, r_output_force, r_reading_string, r_reading_until, rd, redir, REDIR_VARASSIGN, YYSTYPE::redirect, REVERSE_LIST, rewind_input_string(), shell_eof_token, source, st_string, stderr, t, tc, token_to_read, type, BASH_INPUT::type, value, YYSTYPE::word, word_lineno, YYSTYPE::word_list, word_top, x, yacc_EOF, YY_, YY_ACCESSING_SYMBOL, YY_ASSERT, YY_CAST, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_IGNORE_USELESS_CAST_BEGIN, YY_IGNORE_USELESS_CAST_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, YYerror, YYERROR, yyerror(), YYFINAL, YYINITDEPTH, YYLAST, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNOMEM, YYNSTATES, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, YYPTRDIFF_T, yyr1, yyr2, YYSIZE_T, YYSIZEOF, yyalloc::yyss, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYSYMBOL_YYEMPTY, YYSYMBOL_YYEOF, YYSYMBOL_YYerror, yytable, yytable_value_is_error, YYTRANSLATE, YYUNDEF, yyalloc::yyvs, and yyalloc::yyvs_alloc.
Referenced by parse_comsub().
Variable Documentation
yylval
YYSTYPE yylval extern
Definition at line 1688 of file y.tab.c.
Referenced by error_token_from_token(), parse_compound_assignment(), parse_string_to_word_list(), read_token(), read_token_word(), and yyparse().