Fennix: Userspace/musl/include/time.h File Reference
time.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct tm
Macros
#define NULL ((void*)0)
#define __NEED_size_t
#define __NEED_time_t
#define __NEED_clock_t
#define __NEED_struct_timespec
#define CLOCKS_PER_SEC 1000000L
#define TIME_UTC 1
Functions
clock_t clock (void)
time_t time (time_t *)
double difftime (time_t, time_t)
time_t mktime (struct tm *)
size_t strftime (char *__restrict, size_t, const char *__restrict, const struct tm *__restrict)
struct tm * gmtime (const time_t *)
struct tm * localtime (const time_t *)
char * asctime (const struct tm *)
char * ctime (const time_t *)
int timespec_get (struct timespec *, int)
Data Structure Documentation
tm
struct tm
Definition at line 40 of file time.h.
Data Fields
long __tm_gmtoff
const char * __tm_zone
int tm_hour
int tm_isdst
int tm_mday
int tm_min
int tm_mon
int tm_sec
int tm_wday
int tm_yday
int tm_year
Macro Definition Documentation
__NEED_clock_t
#define __NEED_clock_t
Definition at line 21 of file time.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 19 of file time.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 22 of file time.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 20 of file time.h.
CLOCKS_PER_SEC
#define CLOCKS_PER_SEC 1000000L
Definition at line 65 of file time.h.
NULL
#define NULL ((void*)0)
Definition at line 15 of file time.h.
TIME_UTC
#define TIME_UTC 1
Definition at line 67 of file time.h.
Function Documentation
asctime()
char* asctime (const struct tm * tm)
Definition at line 3 of file asctime.c.
 {
     static char buf[26];
     return __asctime_r(tm, buf);
 }
References __asctime_r(), and buf.
Referenced by ctime().
clock()
clock_t clock (void)
Definition at line 4 of file clock.c.
 {
     struct timespec ts;
     if (__clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts))
         return -1;
     if (ts.tv_sec > LONG_MAX/1000000
      || ts.tv_nsec/1000 > LONG_MAX-1000000*ts.tv_sec)
         return -1;
     return ts.tv_sec*1000000 + ts.tv_nsec/1000;
 }
References __clock_gettime(), LONG_MAX, timespec::tv_nsec, and timespec::tv_sec.
Referenced by __pthread_cond_timedwait(), and print_sig().
ctime()
char* ctime (const time_t * t)
Definition at line 3 of file ctime.c.
 {
     struct tm *tm = localtime(t);
     if (!tm) return 0;
     return asctime(tm);
 }
References asctime(), localtime(), and t.
Referenced by __ctime32(), com_stat(), conf_write(), display_single(), do_msg(), do_sem(), do_shm(), dumpleases_main(), header_verbose_list_ar(), last_main(), print_msg(), print_sem(), print_shm(), printsome(), printst(), rdate_main(), rtcwake_main(), show_clock(), show_entry(), timestamp_and_log(), and who_main().
difftime()
double difftime (time_t t1, time_t t0)
Definition at line 3 of file difftime.c.
 {
     return t1-t0;
 }
References t0, and t1.
Referenced by __difftime32().
gmtime()
struct tm* gmtime (const time_t * t)
Definition at line 4 of file gmtime.c.
 {
     static struct tm tm;
     return __gmtime_r(t, &tm);
 }
References __gmtime_r(), and t.
Referenced by __gmtime32(), collect_tv(), conf_write(), and main().
localtime()
struct tm* localtime (const time_t * t)
Definition at line 3 of file localtime.c.
 {
     static struct tm tm;
     return __localtime_r(t, &tm);
 }
References __localtime_r(), and t.
Referenced by __localtime32(), cal_main(), collect_tv(), conf_write(), ctime(), decode_prompt_string(), display_single(), exec_builtin(), flag_starting_jobs(), human_time(), main(), my_localtime_r(), parse_datestr(), print_login_issue(), print_sig(), ps_main(), set_kernel_timezone_and_clock(), setup_alarm(), show_clock(), stattime(), strftime_builtin(), strftime_fmt(), and uptime_main().
mktime()
time_t mktime (struct tm * tp)
Definition at line 175 of file mktime.c.
 {
 #ifdef _LIBC
   /* POSIX.1 8.1.1 requires that whenever mktime() is called, the
      time zone names contained in the external variable `tzname' shall
      be set as if the tzset() function had been called.  */
   __tzset ();
 #endif
   return __mktime_internal (tp, my_localtime_r, &localtime_offset);
 }
References __mktime_internal(), __secs_to_tm(), __secs_to_zone(), tm::__tm_gmtoff, __tm_to_secs(), tm::__tm_zone, __tzset(), EOVERFLOW, errno, error, localtime_offset, my_localtime_r(), t, tm::tm_isdst, and tp.
Referenced by __mktime32(), do_mktime(), rtc_tm2time(), strftime(), and validate_tm_time().
strftime()
size_t strftime (char * __restrict, size_t maxsize, const char * __restrict, const struct tm * __restrict)
Definition at line 171 of file strftime.c.
 {
     char *endp = s + maxsize;
     char *start = s;
     auto char tbuf[100];
     long off;
     int i, w, oerrno;
     long y;
     static short first = 1;
 #ifdef POSIX_SEMANTICS
     static char *savetz = NULL;
     static int savetzlen = 0;
     char *tz;
 #endif /* POSIX_SEMANTICS */
 #ifndef HAVE_TM_ZONE
 #ifndef HAVE_TM_NAME
 #ifndef HAVE_TZNAME
 #ifndef __CYGWIN__
     extern char *timezone();
     struct timeval tv;
     struct timezone zone;
 #endif /* __CYGWIN__ */
 #endif /* HAVE_TZNAME */
 #endif /* HAVE_TM_NAME */
 #endif /* HAVE_TM_ZONE */
 #ifdef POSIX_2008
     int pad;
     size_t fw;
     char flag;
 #endif /* POSIX_2008 */
     /* various tables, useful in North America */
     static const char *days_a[] = {
         "Sun", "Mon", "Tue", "Wed",
         "Thu", "Fri", "Sat",
     };
     static const char *days_l[] = {
         "Sunday", "Monday", "Tuesday", "Wednesday",
         "Thursday", "Friday", "Saturday",
     };
     static const char *months_a[] = {
         "Jan", "Feb", "Mar", "Apr", "May", "Jun",
         "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
     };
     static const char *months_l[] = {
         "January", "February", "March", "April",
         "May", "June", "July", "August", "September",
         "October", "November", "December",
     };
     static const char *ampm[] = { "AM", "PM", };
     oerrno = errno;
     if (s == NULL || format == NULL || timeptr == NULL || maxsize == 0)
         return 0;
     /* quick check if we even need to bother */
     if (strchr(format, '%') == NULL && strlen(format) + 1 >= maxsize)
         return 0;
 #ifndef POSIX_SEMANTICS
     if (first) {
         tzset();
         first = 0;
     }
 #else   /* POSIX_SEMANTICS */
 #if defined (SHELL)
     tz = get_string_value ("TZ");
 #else
     tz = getenv("TZ");
 #endif
     if (first) {
         if (tz != NULL) {
             int tzlen = strlen(tz);
             savetz = (char *) malloc(tzlen + 1);
             if (savetz != NULL) {
                 savetzlen = tzlen + 1;
                 strcpy(savetz, tz);
             }
         }
         tzset();
         first = 0;
     }
     /* if we have a saved TZ, and it is different, recapture and reset */
     if (tz && savetz && (tz[0] != savetz[0] || strcmp(tz, savetz) != 0)) {
         i = strlen(tz) + 1;
         if (i > savetzlen) {
             savetz = (char *) realloc(savetz, i);
             if (savetz) {
                 savetzlen = i;
                 strcpy(savetz, tz);
             }
         } else
             strcpy(savetz, tz);
         tzset();
     }
 #endif  /* POSIX_SEMANTICS */
     for (; *format && s < endp - 1; format++) {
         tbuf[0] = '\0';
         if (*format != '%') {
             *s++ = *format;
             continue;
         }
 #ifdef POSIX_2008
         pad = '\0';
         fw = 0;
         flag = '\0';
         switch (*++format) {
         case '+':
             flag = '+';
             /* fall through */
         case '0':
             pad = '0';
             format++;
             break;
         case '1':
         case '2':
         case '3':
         case '4':
         case '5':
         case '6':
         case '7':
         case '8':
         case '9':
             break;
         default:
             format--;
             goto again;
         }
         for (; isdigit(*format); format++) {
             fw = fw * 10 + (*format - '0');
         }
         format--;
 #endif /* POSIX_2008 */
     again:
         switch (*++format) {
         case '\0':
             *s++ = '%';
             goto out;
         case '%':
             *s++ = '%';
             continue;
         case 'a':   /* abbreviated weekday name */
             if (timeptr->tm_wday < 0 || timeptr->tm_wday > 6)
                 strcpy(tbuf, "?");
             else
                 strcpy(tbuf, days_a[timeptr->tm_wday]);
             break;
         case 'A':   /* full weekday name */
             if (timeptr->tm_wday < 0 || timeptr->tm_wday > 6)
                 strcpy(tbuf, "?");
             else
                 strcpy(tbuf, days_l[timeptr->tm_wday]);
             break;
         case 'b':   /* abbreviated month name */
         short_month:
             if (timeptr->tm_mon < 0 || timeptr->tm_mon > 11)
                 strcpy(tbuf, "?");
             else
                 strcpy(tbuf, months_a[timeptr->tm_mon]);
             break;
         case 'B':   /* full month name */
             if (timeptr->tm_mon < 0 || timeptr->tm_mon > 11)
                 strcpy(tbuf, "?");
             else
                 strcpy(tbuf, months_l[timeptr->tm_mon]);
             break;
         case 'c':   /* appropriate date and time representation */
             /*
              * This used to be:
              *
              * strftime(tbuf, sizeof tbuf, "%a %b %e %H:%M:%S %Y", timeptr);
              *
              * Now, per the ISO 1999 C standard, it this:
              */
             strftime(tbuf, sizeof tbuf, "%A %B %d %T %Y", timeptr);
             break;
         case 'C':
 #ifdef POSIX_2008
             if (pad != '\0' && fw > 0) {
                 size_t min_fw = (flag ? 3 : 2);
                 fw = max(fw, min_fw);
                 sprintf(tbuf, flag
                         ? "%+0*ld"
                         : "%0*ld", (int) fw,
                         (timeptr->tm_year + 1900L) / 100);
             } else
 #endif /* POSIX_2008 */
         century:
                 sprintf(tbuf, "%02ld", (timeptr->tm_year + 1900L) / 100);
             break;
         case 'd':   /* day of the month, 01 - 31 */
             i = range(1, timeptr->tm_mday, 31);
             sprintf(tbuf, "%02d", i);
             break;
         case 'D':   /* date as %m/%d/%y */
             strftime(tbuf, sizeof tbuf, "%m/%d/%y", timeptr);
             break;
         case 'e':   /* day of month, blank padded */
             sprintf(tbuf, "%2d", range(1, timeptr->tm_mday, 31));
             break;
         case 'E':
             /* POSIX (now C99) locale extensions, ignored for now */
             goto again;
         case 'F':   /* ISO 8601 date representation */
         {
 #ifdef POSIX_2008
             /*
              * Field width for %F is for the whole thing.
              * It must be at least 10.
              */
             char m_d[10];
             strftime(m_d, sizeof m_d, "-%m-%d", timeptr);
             size_t min_fw = 10;
             if (pad != '\0' && fw > 0) {
                 fw = max(fw, min_fw);
             } else {
                 fw = min_fw;
             }
             fw -= 6;    /* -XX-XX at end are invariant */
             iso_8601_2000_year(tbuf, timeptr->tm_year + 1900, fw);
             strcat(tbuf, m_d);
 #else
             strftime(tbuf, sizeof tbuf, "%Y-%m-%d", timeptr);
 #endif /* POSIX_2008 */
         }
             break;
         case 'g':
         case 'G':
             /*
              * Year of ISO week.
              *
              * If it's December but the ISO week number is one,
              * that week is in next year.
              * If it's January but the ISO week number is 52 or
              * 53, that week is in last year.
              * Otherwise, it's this year.
              */
             w = iso8601wknum(timeptr);
             if (timeptr->tm_mon == 11 && w == 1)
                 y = 1900L + timeptr->tm_year + 1;
             else if (timeptr->tm_mon == 0 && w >= 52)
                 y = 1900L + timeptr->tm_year - 1;
             else
                 y = 1900L + timeptr->tm_year;
             if (*format == 'G') {
 #ifdef POSIX_2008
                 if (pad != '\0' && fw > 0) {
                     size_t min_fw = 4;
                     fw = max(fw, min_fw);
                     sprintf(tbuf, flag
                             ? "%+0*ld"
                             : "%0*ld", (int) fw,
                             y);
                 } else
 #endif /* POSIX_2008 */
                     sprintf(tbuf, "%ld", y);
             }
             else
                 sprintf(tbuf, "%02ld", y % 100);
             break;
         case 'h':   /* abbreviated month name */
             goto short_month;
         case 'H':   /* hour, 24-hour clock, 00 - 23 */
             i = range(0, timeptr->tm_hour, 23);
             sprintf(tbuf, "%02d", i);
             break;
         case 'I':   /* hour, 12-hour clock, 01 - 12 */
             i = range(0, timeptr->tm_hour, 23);
             if (i == 0)
                 i = 12;
             else if (i > 12)
                 i -= 12;
             sprintf(tbuf, "%02d", i);
             break;
         case 'j':   /* day of the year, 001 - 366 */
             sprintf(tbuf, "%03d", timeptr->tm_yday + 1);
             break;
         case 'm':   /* month, 01 - 12 */
             i = range(0, timeptr->tm_mon, 11);
             sprintf(tbuf, "%02d", i + 1);
             break;
         case 'M':   /* minute, 00 - 59 */
             i = range(0, timeptr->tm_min, 59);
             sprintf(tbuf, "%02d", i);
             break;
         case 'n':   /* same as \n */
             tbuf[0] = '\n';
             tbuf[1] = '\0';
             break;
         case 'O':
             /* POSIX (now C99) locale extensions, ignored for now */
             goto again;
         case 'p':   /* am or pm based on 12-hour clock */
             i = range(0, timeptr->tm_hour, 23);
             if (i < 12)
                 strcpy(tbuf, ampm[0]);
             else
                 strcpy(tbuf, ampm[1]);
             break;
         case 'r':   /* time as %I:%M:%S %p */
             strftime(tbuf, sizeof tbuf, "%I:%M:%S %p", timeptr);
             break;
         case 'R':   /* time as %H:%M */
             strftime(tbuf, sizeof tbuf, "%H:%M", timeptr);
             break;
 #if defined(HAVE_MKTIME)
         case 's':   /* time as seconds since the Epoch */
         {
             struct tm non_const_timeptr;
             non_const_timeptr = *timeptr;
             sprintf(tbuf, "%ld", mktime(& non_const_timeptr));
             break;
         }
 #endif /* defined(HAVE_MKTIME) */
         case 'S':   /* second, 00 - 60 */
             i = range(0, timeptr->tm_sec, 60);
             sprintf(tbuf, "%02d", i);
             break;
         case 't':   /* same as \t */
             tbuf[0] = '\t';
             tbuf[1] = '\0';
             break;
         case 'T':   /* time as %H:%M:%S */
         the_time:
             strftime(tbuf, sizeof tbuf, "%H:%M:%S", timeptr);
             break;
         case 'u':
         /* ISO 8601: Weekday as a decimal number [1 (Monday) - 7] */
             sprintf(tbuf, "%d", timeptr->tm_wday == 0 ? 7 :
                     timeptr->tm_wday);
             break;
         case 'U':   /* week of year, Sunday is first day of week */
             sprintf(tbuf, "%02d", weeknumber(timeptr, 0));
             break;
         case 'V':   /* week of year according ISO 8601 */
             sprintf(tbuf, "%02d", iso8601wknum(timeptr));
             break;
         case 'w':   /* weekday, Sunday == 0, 0 - 6 */
             i = range(0, timeptr->tm_wday, 6);
             sprintf(tbuf, "%d", i);
             break;
         case 'W':   /* week of year, Monday is first day of week */
             sprintf(tbuf, "%02d", weeknumber(timeptr, 1));
             break;
         case 'x':   /* appropriate date representation */
             strftime(tbuf, sizeof tbuf, "%A %B %d %Y", timeptr);
             break;
         case 'X':   /* appropriate time representation */
             goto the_time;
             break;
         case 'y':   /* year without a century, 00 - 99 */
         year:
             i = timeptr->tm_year % 100;
             sprintf(tbuf, "%02d", i);
             break;
         case 'Y':   /* year with century */
 #ifdef POSIX_2008
             if (pad != '\0' && fw > 0) {
                 size_t min_fw = 4;
                 fw = max(fw, min_fw);
                 sprintf(tbuf, flag
                         ? "%+0*ld"
                         : "%0*ld", (int) fw,
                         1900L + timeptr->tm_year);
             } else
 #endif /* POSIX_2008 */
             sprintf(tbuf, "%ld", 1900L + timeptr->tm_year);
             break;
         /*
          * From: Chip Rosenthal <chip@chinacat.unicom.com>
          * Date: Sun, 19 Mar 1995 00:33:29 -0600 (CST)
          *
          * Warning: the %z [code] is implemented by inspecting the
          * timezone name conditional compile settings, and
          * inferring a method to get timezone offsets. I've tried
          * this code on a couple of machines, but I don't doubt
          * there is some system out there that won't like it.
          * Maybe the easiest thing to do would be to bracket this
          * with an #ifdef that can turn it off. The %z feature
          * would be an admittedly obscure one that most folks can
          * live without, but it would be a great help to those of
          * us that muck around with various message processors.
          */
         case 'z':   /* time zone offset east of GMT e.g. -0600 */
             if (timeptr->tm_isdst < 0)
                 break;
 #ifdef HAVE_TM_NAME
             /*
              * Systems with tm_name probably have tm_tzadj as
              * secs west of GMT.  Convert to mins east of GMT.
              */
             off = -timeptr->tm_tzadj / 60;
 #else /* !HAVE_TM_NAME */
 #ifdef HAVE_TM_ZONE
             /*
              * Systems with tm_zone probably have tm_gmtoff as
              * secs east of GMT.  Convert to mins east of GMT.
              */
             off = timeptr->tm_gmtoff / 60;
 #else /* !HAVE_TM_ZONE */
 #if HAVE_TZNAME
             /*
              * Systems with tzname[] probably have timezone as
              * secs west of GMT.  Convert to mins east of GMT.
              */
 #  if defined(__hpux) || defined (HPUX) || defined(__CYGWIN__)
             off = -timezone / 60;
 #  else
             /* ADR: 4 August 2001, fixed this per gazelle@interaccess.com */
             off = -(daylight ? altzone : timezone) / 60;
 #  endif
 #else /* !HAVE_TZNAME */
             gettimeofday(& tv, & zone);
             off = -zone.tz_minuteswest;
 #endif /* !HAVE_TZNAME */
 #endif /* !HAVE_TM_ZONE */
 #endif /* !HAVE_TM_NAME */
             if (off < 0) {
                 tbuf[0] = '-';
                 off = -off;
             } else {
                 tbuf[0] = '+';
             }
             sprintf(tbuf+1, "%02ld%02ld", off/60, off%60);
             break;
         case 'Z':   /* time zone name or abbreviation */
 #ifdef HAVE_TZNAME
             i = (daylight && timeptr->tm_isdst > 0); /* 0 or 1 */
             strcpy(tbuf, tzname[i]);
 #else
 #ifdef HAVE_TM_ZONE
             strcpy(tbuf, timeptr->tm_zone);
 #else
 #ifdef HAVE_TM_NAME
             strcpy(tbuf, timeptr->tm_name);
 #else
             gettimeofday(& tv, & zone);
             strcpy(tbuf, timezone(zone.tz_minuteswest,
                         timeptr->tm_isdst > 0));
 #endif /* HAVE_TM_NAME */
 #endif /* HAVE_TM_ZONE */
 #endif /* HAVE_TZNAME */
             break;
 #ifdef SUNOS_EXT
         case 'k':   /* hour, 24-hour clock, blank pad */
             sprintf(tbuf, "%2d", range(0, timeptr->tm_hour, 23));
             break;
         case 'l':   /* hour, 12-hour clock, 1 - 12, blank pad */
             i = range(0, timeptr->tm_hour, 23);
             if (i == 0)
                 i = 12;
             else if (i > 12)
                 i -= 12;
             sprintf(tbuf, "%2d", i);
             break;
 #endif
 #ifdef HPUX_EXT
         case 'N':   /* Emperor/Era name */
             /* this is essentially the same as the century */
             goto century;   /* %C */
         case 'o':   /* Emperor/Era year */
             goto year;  /* %y */
 #endif /* HPUX_EXT */
 #ifdef VMS_EXT
         case 'v':   /* date as dd-bbb-YYYY */
             sprintf(tbuf, "%2d-%3.3s-%4ld",
                 range(1, timeptr->tm_mday, 31),
                 months_a[range(0, timeptr->tm_mon, 11)],
                 timeptr->tm_year + 1900L);
             for (i = 3; i < 6; i++)
                 if (islower(tbuf[i]))
                     tbuf[i] = toupper(tbuf[i]);
             break;
 #endif
         default:
             tbuf[0] = '%';
             tbuf[1] = *format;
             tbuf[2] = '\0';
             break;
         }
         i = strlen(tbuf);
         if (i) {
             if (s + i < endp - 1) {
                 strcpy(s, tbuf);
                 s += i;
             } else
                 return 0;
         }
     }
 out:
     if (s < endp && *format == '\0') {
         *s = '\0';
         if (s == start)
             errno = oerrno;
         return (s - start);
     } else
         return 0;
 }
References errno, first, format(), get_string_value(), getenv, gettimeofday(), i, isdigit, islower, iso8601wknum(), iso_8601_2000_year(), malloc, max(), mktime(), NULL, off, out(), pad(), range, realloc, s, sprintf(), start, strcat, strchr(), strcmp, strcpy, strlen(), tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, tm::tm_year, toupper, tzset(), w, weeknumber(), and y.
Referenced by _vsyslog(), cal_main(), conf_write(), date_main(), decode_prompt_string(), display_single(), exec_builtin(), finalize(), human_time(), main(), print_header(), print_login_issue(), print_sig(), print_timestamp(), ps_main(), send_headers(), show_clock(), stattime(), strftime_builtin(), strftime_fmt(), ts_main(), and write_stats().
time()
time_t time (time_t * t)
Definition at line 4 of file time.c.
 {
     struct timespec ts;
     __clock_gettime(CLOCK_REALTIME, &ts);
     if (t) *t = ts.tv_sec;
     return ts.tv_sec;
 }
References __clock_gettime(), t, and timespec::tv_sec.
Referenced by __time32(), _vsyslog(), add_lease(), adduser_main(), askremotedate(), cal_main(), conf_write(), crond_main(), date_main(), decode_prompt_string(), dumpleases_main(), evaluate(), exec_builtin(), execute(), finalize(), get_localtime(), gettimeofday(), hist_inittime(), idle_string(), is_expired_lease(), last_main(), log_locally(), Main(), main(), mkfs_ext2_main(), mkfs_reiser_main(), mkfs_vfat_main(), monotonic_sec(), oldest_expired_lease(), P_StartButton(), pause_after_failed_login(), pipe_progress_main(), print_login_issue(), print_sig(), ps_main(), rdate_main(), read_leases(), read_lines(), rtcwake_main(), runsvdir_main(), script_main(), send_headers(), set_kernel_timezone_and_clock(), sh_mktmpfd(), sh_mktmpname(), strftime_fmt(), times(), timestamp_and_log(), tls_run_copy_loop(), touch_main(), udhcpd_main(), update_passwd(), update_utmp(), uptime_main(), wait_one(), write_leases(), write_new_utmp(), WriteTime(), and xrtnl_open().
timespec_get()
int timespec_get (struct timespec * ts, int base)
Definition at line 5 of file timespec_get.c.
 {
     if (base != TIME_UTC) return 0;
     int ret = __clock_gettime(CLOCK_REALTIME, ts);
     return ret < 0 ? 0 : base;
 }
References __clock_gettime(), base, and TIME_UTC.
Referenced by __timespec_get_time32().