Fennix: Userspace/musl/include/arpa/inet.h File Reference
inet.h File Reference
#include <features.h>
#include <netinet/in.h>
Functions
uint32_t htonl (uint32_t)
uint16_t htons (uint16_t)
uint32_t ntohl (uint32_t)
uint16_t ntohs (uint16_t)
in_addr_t inet_addr (const char *)
in_addr_t inet_network (const char *)
char * inet_ntoa (struct in_addr)
int inet_pton (int, const char *__restrict, void *__restrict)
const char * inet_ntop (int, const void *__restrict, char *__restrict, socklen_t)
int inet_aton (const char *, struct in_addr *)
struct in_addr inet_makeaddr (in_addr_t, in_addr_t)
in_addr_t inet_lnaof (struct in_addr)
in_addr_t inet_netof (struct in_addr)
Function Documentation
htonl()
uint32_t htonl (uint32_t x)
Definition at line 15 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint32_t>::byteswap(x);
 #else
     return x;
 #endif
 }
htons()
uint16_t htons (uint16_t x)
Definition at line 22 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint16_t>::byteswap(x);
 #else
     return x;
 #endif
 }
inet_addr()
in_addr_t inet_addr (const char * p)
Definition at line 47 of file arpa-inet-stubs.cpp.
{
     struct in_addr a;
     if(!inet_aton(p, &a))
         return -1;
     return a.s_addr;
 }
References __inet_aton(), inet_aton(), p, and in_addr::s_addr.
Referenced by accept_builtin(), and inet_makeaddr().
inet_aton()
int inet_aton (const char * string, struct in_addr * dest)
Definition at line 63 of file arpa-inet-stubs.cpp.
{
     int array[4];
     int i = 0;
     char *end;
     for (; i < 4; i++) {
         array[i] = strtoul(string, &end, 0);
         if (*end && *end != '.')
             return 0;
         if (!*end)
             break;
         string = end + 1;
     }
     switch (i) {
         case 0:
             dest->s_addr = htonl(array[0]);
             break;
         case 1:
             if (array[0] > 255 || array[1] > 0xffffff)
                 return 0;
             dest->s_addr = htonl((array[0] << 24) | array[1]);
             break;
         case 2:
             if (array[0] > 255 || array[1] > 255 ||
                     array[2] > 0xffff)
                 return 0;
             dest->s_addr = htonl((array[0] << 24) | (array[1] << 16) |
                 array[2]);
             break;
         case 3:
             if (array[0] > 255 || array[1] > 255 ||
                     array[2] > 255 || array[3] > 255)
                 return 0;
             dest->s_addr = htonl((array[0] << 24) | (array[1] << 16) |
                 (array[2] << 8) | array[3]);
             break;
     }
     return 1;
 }
References htonl(), i, in_addr::s_addr, and strtoul().
Referenced by inet_addr(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), and mlibc::lookup_name_hosts().
inet_lnaof()
in_addr_t inet_lnaof (struct in_addr in)
Definition at line 18 of file inet_legacy.c.
 {
     uint32_t h = in.s_addr;
     if (h>>24 < 128) return h & 0xffffff;
     if (h>>24 < 192) return h & 0xffff;
     return h & 0xff;
 }
References in_addr::s_addr.
inet_makeaddr()
struct in_addr inet_makeaddr (in_addr_t n, in_addr_t h)
Definition at line 5 of file inet_legacy.c.
 {
     if (n < 256) h |= n<<24;
     else if (n < 65536) h |= n<<16;
     else h |= n<<8;
     return (struct in_addr){ h };
 }
References inet_addr(), ntohl(), and p.
inet_netof()
in_addr_t inet_netof (struct in_addr in)
Definition at line 26 of file inet_legacy.c.
 {
     uint32_t h = in.s_addr;
     if (h>>24 < 128) return h >> 24;
     if (h>>24 < 192) return h >> 16;
     return h >> 8;
 }
References in_addr::s_addr.
inet_network()
in_addr_t inet_network (const char * p)
Definition at line 5 of file inet_legacy.c.
 {
     return ntohl(inet_addr(p));
 }
inet_ntoa()
char* inet_ntoa (struct in_addr addr)
Definition at line 53 of file arpa-inet-stubs.cpp.
{
     // string: xxx.yyy.zzz.aaa
     // 4 * 3 + 3 + 1 = 12 + 4 = 16
     thread_local static char buffer[16];
     uint32_t proper = htonl(addr.s_addr);
     snprintf(buffer, sizeof(buffer), "%d.%d.%d.%d",
         (proper >> 24) & 0xff, ((proper >> 16) & 0xff),
         (proper >> 8) & 0xff, proper & 0xff);
     return buffer;
 }
References addr, buf, buffer, htonl(), snprintf(), and thread_local.
Referenced by accept_builtin().
inet_ntop()
const char* inet_ntop (int , const void * __restrict, char * __restrict, socklen_t)
inet_pton()
int inet_pton (int , const char * __restrict, void * __restrict)
ntohl()
uint32_t ntohl (uint32_t x)
Definition at line 29 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint32_t>::byteswap(x);
 #else
     return x;
 #endif
 }
ntohs()
uint16_t ntohs (uint16_t x)
Definition at line 36 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint16_t>::byteswap(x);
 #else
     return x;
 #endif
 }