Fennix Userspace: Userspace/mlibc/options/ansi/generic/time-stubs.cpp File Reference
time-stubs.cpp File Reference
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <limits.h>
#include <wchar.h>
#include <stdlib.h>
#include <ctype.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/file-window.hpp>
#include <mlibc/ansi-sysdeps.hpp>
#include <mlibc/allocator.hpp>
#include <mlibc/lock.hpp>
#include <mlibc/locale.hpp>
#include <mlibc/bitutil.hpp>
#include <mlibc/strings.hpp>
#include <frg/mutex.hpp>
Data Structures
struct anonymous_namespace{time-stubs.cpp}::tzfile
Namespaces
anonymous_namespace{time-stubs.cpp}
Functions
static file_window * get_localtime_window ()
clock_t clock (void)
double difftime (time_t a, time_t b)
time_t mktime (struct tm *tm)
int timespec_get (struct timespec *ts, int base)
char * asctime (const struct tm *ptr)
char * ctime (const time_t *timer)
struct tm * gmtime (const time_t *unix_gmt)
struct tm * localtime (const time_t *unix_gmt)
size_t strftime (char *__restrict dest, size_t max_size, const char *__restrict format, const struct tm *__restrict tm)
size_t wcsftime (wchar_t *__restrict, size_t, const wchar_t *__restrict, const struct tm *__restrict)
void tzset (void)
int nanosleep (const struct timespec *req, struct timespec *)
int clock_getres (clockid_t clockid, struct timespec *res)
int clock_gettime (clockid_t clock, struct timespec *time)
int clock_nanosleep (clockid_t, int, const struct timespec *, struct timespec *)
int clock_settime (clockid_t, const struct timespec *)
time_t time (time_t *out)
void anonymous_namespace{time-stubs.cpp}::civil_from_days (time_t days_since_epoch, int *year, unsigned int *month, unsigned int *day)
void anonymous_namespace{time-stubs.cpp}::weekday_from_days (time_t days_since_epoch, unsigned int *weekday)
void anonymous_namespace{time-stubs.cpp}::yearday_from_date (unsigned int year, unsigned int month, unsigned int day, unsigned int *yday)
int anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt (time_t unix_gmt, time_t *offset, bool *dst, char **tm_zone)
struct tm * gmtime_r (const time_t *unix_gmt, struct tm *res)
struct tm * localtime_r (const time_t *unix_gmt, struct tm *res)
char * asctime_r (const struct tm *tm, char *buf)
char * ctime_r (const time_t *clock, char *buf)
time_t timelocal (struct tm *)
constexpr static int days_from_civil (int y, unsigned m, unsigned d) noexcept
time_t timegm (struct tm *tm)
Variables
const char __utc [] = "UTC"
int daylight
long timezone
char * tzname [2]
static FutexLock __time_lock
unsigned char anonymous_namespace{time-stubs.cpp}::tt_isdst
unsigned char anonymous_namespace{time-stubs.cpp}::tt_abbrind
Data Structure Documentation
anonymous_namespace{time-stubs.cpp}::tzfile
struct anonymous_namespace{time-stubs.cpp}::tzfile
Definition at line 362 of file time-stubs.cpp.
Data Fields
uint8_t magic[4]
uint8_t reserved[15]
uint32_t tzh_charcnt
uint32_t tzh_leapcnt
uint32_t tzh_timecnt
uint32_t tzh_ttisgmtcnt
uint32_t tzh_ttisstdcnt
uint32_t tzh_typecnt
uint8_t version
Function Documentation
asctime()
char* asctime (const struct tm * ptr)
Definition at line 67 of file time-stubs.cpp.
{
     static char buf[26];
     return asctime_r(ptr, buf);
 }
References asctime_r(), and buf.
Referenced by ctime().
asctime_r()
char* asctime_r (const struct tm * tm, char * buf)
Definition at line 674 of file time-stubs.cpp.
{
     static char weekday_names[7][4] =
         { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
     static char month_names[12][4] =
         { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct",
           "Nov", "Dec" };
     sprintf(buf, "%.3s %.3s%3d %.2d:%.2d%.2d %d\n",
                  weekday_names[tm->tm_wday],
                  month_names[tm->tm_mon],
                  tm->tm_mday,
                  tm->tm_hour,
                  tm->tm_min,
                  tm->tm_sec,
                  tm->tm_year + 1900);
     return buf;
 }
References buf, sprintf(), tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, and tm::tm_year.
Referenced by asctime(), and ctime_r().
clock()
clock_t clock (void)
Definition at line 37 of file time-stubs.cpp.
                     {
     struct timespec ts;
     if(clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts))
         return -1;
     if(ts.tv_sec > LONG_MAX / 1000000 || ts.tv_nsec / 1000 > LONG_MAX - 1000000 * ts.tv_sec)
         return -1;
     return ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
 }
References clock_gettime(), CLOCK_PROCESS_CPUTIME_ID, timespec::tv_nsec, and timespec::tv_sec.
Referenced by clock_gettime(), ctime_r(), pthread_cond_init(), pthread_condattr_getclock(), pthread_condattr_setclock(), mlibc::sys_clock_get(), mlibc::sys_clock_getres(), and test_attr().
clock_getres()
int clock_getres (clockid_t clockid, struct timespec * res)
Definition at line 461 of file time-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_clock_getres, -1);
     if(int e = mlibc::sys_clock_getres(clockid, &res->tv_sec, &res->tv_nsec); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_clock_getres(), timespec::tv_nsec, and timespec::tv_sec.
clock_gettime()
int clock_gettime (clockid_t clock, struct timespec * time)
Definition at line 470 of file time-stubs.cpp.
{
     if(int e = mlibc::sys_clock_get(clock, &time->tv_sec, &time->tv_nsec); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References clock(), errno, mlibc::sys_clock_get(), and time().
Referenced by clock(), test_timedwait_timedout(), and timespec_get().
clock_nanosleep()
int clock_nanosleep (clockid_t , int , const struct timespec * , struct timespec *)
Definition at line 478 of file time-stubs.cpp.
{
     __ensure(!"clock_nanosleep() not implemented");
     __builtin_unreachable();
 }
References __ensure.
clock_settime()
int clock_settime (clockid_t , const struct timespec *)
Definition at line 483 of file time-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
ctime()
char* ctime (const time_t * timer)
Definition at line 72 of file time-stubs.cpp.
{
     struct tm *tm = localtime(timer);
     if(!tm) {
         return 0;
     }
     return asctime(tm);
 }
References asctime(), and localtime().
ctime_r()
char* ctime_r (const time_t * clock, char * buf)
Definition at line 691 of file time-stubs.cpp.
{
     return asctime_r(localtime(clock), buf);
 }
References asctime_r(), buf, clock(), and localtime().
days_from_civil()
constexpr static int days_from_civil (int y, unsigned m, unsigned d) static constexpr noexcept
Definition at line 700 of file time-stubs.cpp.
{
     y -= m <= 2;
     const int era = (y >= 0 ? y : y - 399) / 400;
     const unsigned yoe = static_cast<unsigned>(y - era * 400); // [0, 399]
     const unsigned doy = (153 * (m > 2 ? m - 3 : m + 9) + 2) / 5 + d - 1; // [0, 365]
     const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy; // [0, 146096]
     return era * 146097 + static_cast<int>(doe) - 719468;
 }
References y.
Referenced by timegm().
difftime()
double difftime (time_t a, time_t b)
Definition at line 49 of file time-stubs.cpp.
{
     return a - b;
 }
References b.
get_localtime_window()
static file_window* get_localtime_window () static
Definition at line 31 of file time-stubs.cpp.
{
     static file_window window{"/etc/localtime"};
     return &window;
 }
References mlibc::window.
Referenced by tzset(), and anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt().
gmtime()
struct tm* gmtime (const time_t * unix_gmt)
Definition at line 80 of file time-stubs.cpp.
{
     static thread_local struct tm per_thread_tm;
     return gmtime_r(unix_gmt, &per_thread_tm);
 }
References gmtime_r().
gmtime_r()
struct tm* gmtime_r (const time_t * unix_gmt, struct tm * res)
Definition at line 606 of file time-stubs.cpp.
{
     int year;
     unsigned int month;
     unsigned int day;
     unsigned int weekday;
     unsigned int yday;
     time_t unix_local = *unix_gmt;
     int days_since_epoch = unix_local / (60*60*24);
     civil_from_days(days_since_epoch, &year, &month, &day);
     weekday_from_days(days_since_epoch, &weekday);
     yearday_from_date(year, month, day, &yday);
     res->tm_sec = unix_local % 60;
     res->tm_min = (unix_local / 60) % 60;
     res->tm_hour = (unix_local / (60*60)) % 24;
     res->tm_mday = day;
     res->tm_mon = month - 1;
     res->tm_year = year - 1900;
     res->tm_wday = weekday;
     res->tm_yday = yday - 1;
     res->tm_isdst = -1;
     res->tm_zone = __utc;
     res->tm_gmtoff = 0;
     return res;
 }
References __utc, anonymous_namespace{time-stubs.cpp}::civil_from_days(), tm::tm_gmtoff, tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, tm::tm_year, tm::tm_zone, anonymous_namespace{time-stubs.cpp}::weekday_from_days(), and anonymous_namespace{time-stubs.cpp}::yearday_from_date().
Referenced by _vsyslog(), and gmtime().
localtime()
struct tm* localtime (const time_t * unix_gmt)
Definition at line 85 of file time-stubs.cpp.
{
     tzset();
     static thread_local struct tm per_thread_tm;
     return localtime_r(unix_gmt, &per_thread_tm);
 }
References localtime_r(), and tzset().
Referenced by ctime(), and ctime_r().
localtime_r()
struct tm* localtime_r (const time_t * unix_gmt, struct tm * res)
Definition at line 635 of file time-stubs.cpp.
{
     int year;
     unsigned int month;
     unsigned int day;
     unsigned int weekday;
     unsigned int yday;
     time_t offset = 0;
     bool dst;
     char *tm_zone;
     frg::unique_lock<FutexLock> lock(__time_lock);
     // TODO: Set errno if the conversion fails.
     if(unix_local_from_gmt(*unix_gmt, &offset, &dst, &tm_zone)) {
         __ensure(!"Error parsing /etc/localtime");
         __builtin_unreachable();
     }
     time_t unix_local = *unix_gmt + offset;
     int days_since_epoch = unix_local / (60*60*24);
     civil_from_days(days_since_epoch, &year, &month, &day);
     weekday_from_days(days_since_epoch, &weekday);
     yearday_from_date(year, month, day, &yday);
     res->tm_sec = unix_local % 60;
     res->tm_min = (unix_local / 60) % 60;
     res->tm_hour = (unix_local / (60*60)) % 24;
     res->tm_mday = day;
     res->tm_mon = month - 1;
     res->tm_year = year - 1900;
     res->tm_wday = weekday;
     res->tm_yday = yday - 1;
     res->tm_isdst = dst;
     res->tm_zone = tm_zone;
     res->tm_gmtoff = offset;
     return res;
 }
References __ensure, __time_lock, anonymous_namespace{time-stubs.cpp}::civil_from_days(), offset, tm::tm_gmtoff, tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, tm::tm_year, tm::tm_zone, anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt(), anonymous_namespace{time-stubs.cpp}::weekday_from_days(), and anonymous_namespace{time-stubs.cpp}::yearday_from_date().
Referenced by localtime().
mktime()
time_t mktime (struct tm * tm)
Definition at line 53 of file time-stubs.cpp.
{
     return timegm(tm);
 }
References timegm().
nanosleep()
int nanosleep (const struct timespec * req, struct timespec *)
Definition at line 439 of file time-stubs.cpp.
{
     if (req->tv_sec < 0 || req->tv_nsec > 999999999 || req->tv_nsec < 0) {
         errno = EINVAL;
         return -1;
     }
     if(!mlibc::sys_sleep) {
         MLIBC_MISSING_SYSDEP();
         __ensure(!"Cannot continue without sys_sleep()");
     }
     struct timespec tmp = *req;
     int e = mlibc::sys_sleep(&tmp.tv_sec, &tmp.tv_nsec);
     if (!e) {
         return 0;
     } else {
         errno = e;
         return -1;
     }
 }
References __ensure, EINVAL, errno, MLIBC_MISSING_SYSDEP, mlibc::sys_sleep(), timespec::tv_nsec, and timespec::tv_sec.
strftime()
size_t strftime (char *__restrict dest, size_t max_size, const char *__restrict format, const struct tm *__restrict tm)
Definition at line 91 of file time-stubs.cpp.
{
     auto c = format;
     auto p = dest;
     while(*c) {
         int chunk;
         auto space = (dest + max_size) - p;
         __ensure(space >= 0);
         if(*c != '%') {
             if(!space)
                 return 0;
             *p = *c;
             c++;
             p++;
             continue;
         }
         switch(*++c) {
         case 'Y': {
             chunk = snprintf(p, space, "%d", 1900 + tm->tm_year);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'm': {
             chunk = snprintf(p, space, "%.2d", tm->tm_mon + 1);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'd': {
             chunk = snprintf(p, space, "%.2d", tm->tm_mday);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'Z': {
             chunk = snprintf(p, space, "%s", "GMT");
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'H': {
             chunk = snprintf(p, space, "%.2i", tm->tm_hour);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'M': {
             chunk = snprintf(p, space, "%.2i", tm->tm_min);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'S': {
             chunk = snprintf(p, space, "%.2d", tm->tm_sec);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'R': {
             chunk = snprintf(p, space, "%.2i:%.2i", tm->tm_hour, tm->tm_min);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'T': {
             chunk = snprintf(p, space, "%.2i:%.2i:%.2i", tm->tm_hour, tm->tm_min, tm->tm_sec);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'F': {
             chunk = snprintf(p, space, "%d-%.2d-%.2d", 1900 + tm->tm_year, tm->tm_mon + 1,
                     tm->tm_mday);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'D': {
             chunk = snprintf(p, space, "%.2d/%.2d/%.2d", tm->tm_mon + 1, tm->tm_mday, tm->tm_year % 100);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'a': {
             int day = tm->tm_wday;
             if(day < 0 || day > 6)
                 __ensure(!"Day not in bounds.");
             chunk = snprintf(p, space, "%s", mlibc::nl_langinfo(DAY_1 + day));
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'b':
         case 'B':
         case 'h': {
             int mon = tm->tm_mon;
             if(mon < 0 || mon > 11)
                 __ensure(!"Month not in bounds.");
             nl_item item = (*c == 'B') ? MON_1 : ABMON_1;
             chunk = snprintf(p, space, "%s", mlibc::nl_langinfo(item + mon));
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'c': {
             chunk = snprintf(p, space, "%d/%.2d/%.2d %.2d:%.2d:%.2d", 1900 + tm->tm_year,
                     tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'e': {
             chunk = snprintf(p, space, "%2d", tm->tm_mday);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'I': {
             int hour = tm->tm_hour;
             if(!hour)
                 hour = 12;
             if(hour > 12)
                 hour -= 12;
             chunk = snprintf(p, space, "%.2i", hour);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'p': {
             chunk = snprintf(p, space, "%s", mlibc::nl_langinfo((tm->tm_hour < 12) ? AM_STR : PM_STR));
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'C': {
             chunk = snprintf(p, space, "%.2d", (1900 + tm->tm_year) / 100);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'y': {
             chunk = snprintf(p, space, "%.2d", (1900 + tm->tm_year) % 100);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'j': {
             chunk = snprintf(p, space, "%.3d", tm->tm_yday + 1);
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'A': {
             chunk = snprintf(p, space, "%s", mlibc::nl_langinfo(DAY_1 + tm->tm_wday));
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'r': {
             int hour = tm->tm_hour;
             if(!hour)
                 hour = 12;
             if(hour > 12)
                 hour -= 12;
             chunk = snprintf(p, space, "%.2i:%.2i:%.2i %s", hour, tm->tm_min, tm->tm_sec,
                 mlibc::nl_langinfo((tm->tm_hour < 12) ? AM_STR : PM_STR));
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case '%': {
             chunk = snprintf(p, space, "%%");
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 't': {
             chunk = snprintf(p, space, "\t");
             if(chunk >= space)
                 return 0;
             p += chunk;
             c++;
             break;
         }
         case 'x': {
             return strftime(dest, max_size, mlibc::nl_langinfo(D_FMT), tm);
         }
         case 'X': {
             return strftime(dest, max_size, mlibc::nl_langinfo(T_FMT), tm);
         }
         case '\0': {
             chunk = snprintf(p, space, "%%");
             if(chunk >= space)
                 return 0;
             p += chunk;
             break;
         }
         default:
             mlibc::panicLogger() << "mlibc: strftime unknown format type: " << c << frg::endlog;
         }
     }
     auto space = (dest + max_size) - p;
     if(!space)
         return 0;
     *p = '\0';
     return (p - dest);
 }
References __ensure, ABMON_1, AM_STR, c, D_FMT, DAY_1, format, max_size, MON_1, mlibc::nl_langinfo(), p, mlibc::panicLogger, PM_STR, snprintf(), T_FMT, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, and tm::tm_year.
Referenced by _vsyslog(), and main().
time()
time_t time (time_t * out)
Definition at line 488 of file time-stubs.cpp.
{
     time_t secs;
     long nanos;
     if(int e = mlibc::sys_clock_get(CLOCK_REALTIME, &secs, &nanos); e) {
         errno = e;
         return (time_t)-1;
     }
     if(out)
         *out = secs;
     return secs;
 }
References CLOCK_REALTIME, errno, mlibc::nanos, mlibc::secs, and mlibc::sys_clock_get().
Referenced by _vsyslog(), anonymous_namespace{time-stubs.cpp}::civil_from_days(), clock_gettime(), P_StartButton(), utime(), utimes(), and WriteTime().
timegm()
time_t timegm (struct tm * tm)
Definition at line 709 of file time-stubs.cpp.
{
     time_t year = tm->tm_year + 1900;
     time_t month = tm->tm_mon + 1;
     time_t days = days_from_civil(year, month, tm->tm_mday);
     time_t secs = (days * 86400) + (tm->tm_hour * 60 * 60) + (tm->tm_min * 60) + tm->tm_sec;
     return secs;
 }
References days_from_civil(), mlibc::secs, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, and tm::tm_year.
Referenced by main(), and mktime().
timelocal()
time_t timelocal (struct tm *)
Definition at line 695 of file time-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
timespec_get()
int timespec_get (struct timespec * ts, int base)
Definition at line 60 of file time-stubs.cpp.
{
     if(base != TIME_UTC)
         return 0;
     int ret = clock_gettime(CLOCK_REALTIME, ts);
     return ret < 0 ? 0 : base;
 }
References base, clock_gettime(), CLOCK_REALTIME, ret, and TIME_UTC.
tzset()
void tzset (void)
Definition at line 385 of file time-stubs.cpp.
                  {
     frg::unique_lock<FutexLock> lock(__time_lock);
     // TODO(geert): we can probably cache this somehow
     tzfile tzfile_time;
     memcpy(&tzfile_time, reinterpret_cast<char *>(get_localtime_window()->get()), sizeof(tzfile));
     tzfile_time.tzh_ttisgmtcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_ttisgmtcnt);
     tzfile_time.tzh_ttisstdcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_ttisstdcnt);
     tzfile_time.tzh_leapcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_leapcnt);
     tzfile_time.tzh_timecnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_timecnt);
     tzfile_time.tzh_typecnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_typecnt);
     tzfile_time.tzh_charcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_charcnt);
     if(tzfile_time.magic[0] != 'T' || tzfile_time.magic[1] != 'Z' || tzfile_time.magic[2] != 'i'
             || tzfile_time.magic[3] != 'f') {
         mlibc::infoLogger() << "mlibc: /etc/localtime is not a valid TZinfo file" << frg::endlog;
         return;
     }
     if(tzfile_time.version != '\0' && tzfile_time.version != '2' && tzfile_time.version != '3') {
         mlibc::infoLogger() << "mlibc: /etc/localtime has an invalid TZinfo version"
                 << frg::endlog;
         return;
     }
     // There should be at least one entry in the ttinfo table.
     // TODO: If there is not, we might want to fall back to UTC, no DST (?).
     __ensure(tzfile_time.tzh_typecnt);
     char *abbrevs = reinterpret_cast<char *>(get_localtime_window()->get()) + sizeof(tzfile)
         + tzfile_time.tzh_timecnt * sizeof(int32_t)
         + tzfile_time.tzh_timecnt * sizeof(uint8_t)
         + tzfile_time.tzh_typecnt * sizeof(struct ttinfo);
     // start from the last ttinfo entry, this matches the behaviour of glibc and musl
     for (int i = tzfile_time.tzh_typecnt; i > 0; i--) {
         ttinfo time_info;
         memcpy(&time_info, reinterpret_cast<char *>(get_localtime_window()->get()) + sizeof(tzfile)
                 + tzfile_time.tzh_timecnt * sizeof(int32_t)
                 + tzfile_time.tzh_timecnt * sizeof(uint8_t)
                 + i * sizeof(ttinfo), sizeof(ttinfo));
         time_info.tt_gmtoff = mlibc::bit_util<uint32_t>::byteswap(time_info.tt_gmtoff);
         if (!time_info.tt_isdst && !tzname[0]) {
             tzname[0] = abbrevs + time_info.tt_abbrind;
             timezone = -time_info.tt_gmtoff;
         }
         if (time_info.tt_isdst && !tzname[1]) {
             tzname[1] = abbrevs + time_info.tt_abbrind;
             timezone = -time_info.tt_gmtoff;
             daylight = 1;
         }
     }
 }
References __ensure, __time_lock, daylight, file_window::get(), get_localtime_window(), i, mlibc::infoLogger, memcpy(), and tzname.
Referenced by localtime().
wcsftime()
size_t wcsftime (wchar_t * __restrict, size_t , const wchar_t * __restrict, const struct tm * __restrict)
Definition at line 354 of file time-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: wcsftime is a stub" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
Variable Documentation
__time_lock
FutexLock __time_lock static
Definition at line 30 of file time-stubs.cpp.
Referenced by localtime_r(), and tzset().
__utc
const char __utc[] = "UTC"
Definition at line 23 of file time-stubs.cpp.
Referenced by gmtime_r().
daylight
int daylight
Definition at line 26 of file time-stubs.cpp.
Referenced by tzset().
timezone
long timezone
Definition at line 27 of file time-stubs.cpp.
tzname
char* tzname[2]
Definition at line 28 of file time-stubs.cpp.
Referenced by tzset().