Fennix: Userspace/mlibc/options/linux/include/sys/inotify.h File Reference
inotify.h File Reference
#include <stdint.h>
#include <abi-bits/fcntl.h>
#include <abi-bits/inotify.h>
Data Structures
struct inotify_event
Macros
#define IN_ACCESS 0x1
#define IN_ATTRIB 0x4
#define IN_CLOSE_WRITE 0x8
#define IN_CLOSE_NOWRITE 0x10
#define IN_CREATE 0x100
#define IN_DELETE 0x200
#define IN_DELETE_SELF 0x400
#define IN_MODIFY 0x2
#define IN_MOVE_SELF 0x800
#define IN_MOVED_FROM 0x40
#define IN_MOVED_TO 0x80
#define IN_OPEN 0x20
#define IN_MOVE (IN_MOVED_FROM | IN_MOVED_TO)
#define IN_CLOSE (IN_CLOSE_WRITE | IN_CLOSE_NOWRITE)
#define IN_DONT_FOLLOW 0x2000000
#define IN_EXCL_UNLINK 0x4000000
#define IN_MASK_ADD 0x20000000
#define IN_ONESHOT 0x80000000
#define IN_ONLYDIR 0x1000000
#define IN_IGNORED 0x8000
#define IN_ISDIR 0x40000000
#define IN_Q_OVERFLOW 0x4000
#define IN_UNMOUNT 0x2000
#define IN_ALL_EVENTS
Functions
int inotify_init (void)
int inotify_init1 (int)
int inotify_add_watch (int, const char *, uint32_t)
int inotify_rm_watch (int, int)
Data Structure Documentation
inotify_event
struct inotify_event
Definition at line 41 of file inotify.h.
Data Fields
unsigned int cookie
unsigned int len
unsigned int mask
char name[]
int wd
Macro Definition Documentation
IN_ACCESS
#define IN_ACCESS 0x1
Definition at line 12 of file inotify.h.
IN_ALL_EVENTS
#define IN_ALL_EVENTS
Value:
             (IN_ACCESS | IN_MODIFY | IN_ATTRIB | IN_CLOSE_WRITE | \
             IN_CLOSE_NOWRITE | IN_OPEN | IN_MOVED_FROM | \
             IN_MOVED_TO | IN_DELETE | IN_CREATE | IN_DELETE_SELF | \
             IN_MOVE_SELF)
Definition at line 36 of file inotify.h.
IN_ATTRIB
#define IN_ATTRIB 0x4
Definition at line 13 of file inotify.h.
IN_CLOSE
#define IN_CLOSE (IN_CLOSE_WRITE | IN_CLOSE_NOWRITE)
Definition at line 25 of file inotify.h.
IN_CLOSE_NOWRITE
#define IN_CLOSE_NOWRITE 0x10
Definition at line 15 of file inotify.h.
IN_CLOSE_WRITE
#define IN_CLOSE_WRITE 0x8
Definition at line 14 of file inotify.h.
IN_CREATE
#define IN_CREATE 0x100
Definition at line 16 of file inotify.h.
IN_DELETE
#define IN_DELETE 0x200
Definition at line 17 of file inotify.h.
IN_DELETE_SELF
#define IN_DELETE_SELF 0x400
Definition at line 18 of file inotify.h.
IN_DONT_FOLLOW
#define IN_DONT_FOLLOW 0x2000000
Definition at line 26 of file inotify.h.
IN_EXCL_UNLINK
#define IN_EXCL_UNLINK 0x4000000
Definition at line 27 of file inotify.h.
IN_IGNORED
#define IN_IGNORED 0x8000
Definition at line 31 of file inotify.h.
IN_ISDIR
#define IN_ISDIR 0x40000000
Definition at line 32 of file inotify.h.
IN_MASK_ADD
#define IN_MASK_ADD 0x20000000
Definition at line 28 of file inotify.h.
IN_MODIFY
#define IN_MODIFY 0x2
Definition at line 19 of file inotify.h.
IN_MOVE
#define IN_MOVE (IN_MOVED_FROM | IN_MOVED_TO)
Definition at line 24 of file inotify.h.
IN_MOVE_SELF
#define IN_MOVE_SELF 0x800
Definition at line 20 of file inotify.h.
IN_MOVED_FROM
#define IN_MOVED_FROM 0x40
Definition at line 21 of file inotify.h.
IN_MOVED_TO
#define IN_MOVED_TO 0x80
Definition at line 22 of file inotify.h.
IN_ONESHOT
#define IN_ONESHOT 0x80000000
Definition at line 29 of file inotify.h.
IN_ONLYDIR
#define IN_ONLYDIR 0x1000000
Definition at line 30 of file inotify.h.
IN_OPEN
#define IN_OPEN 0x20
Definition at line 23 of file inotify.h.
IN_Q_OVERFLOW
#define IN_Q_OVERFLOW 0x4000
Definition at line 33 of file inotify.h.
IN_UNMOUNT
#define IN_UNMOUNT 0x2000
Definition at line 34 of file inotify.h.
Function Documentation
inotify_add_watch()
int inotify_add_watch (int ifd, const char * path, uint32_t mask)
Definition at line 29 of file sys-inotify-stubs.cpp.
{
     int wd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_add_watch, -1);
     if(int e = mlibc::sys_inotify_add_watch(ifd, path, mask, &wd); e) {
         errno = e;
         return -1;
     }
     return wd;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_add_watch().
inotify_init()
int inotify_init (void)
Definition at line 9 of file sys-inotify-stubs.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_create, -1);
     if(int e = mlibc::sys_inotify_create(0, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_create().
inotify_init1()
int inotify_init1 (int flags)
Definition at line 19 of file sys-inotify-stubs.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_create, -1);
     if(int e = mlibc::sys_inotify_create(flags, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_create().
inotify_rm_watch()
int inotify_rm_watch (int ifd, int wd)
Definition at line 39 of file sys-inotify-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_inotify_rm_watch, -1);
     if(int e = mlibc::sys_inotify_rm_watch(ifd, wd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_inotify_rm_watch().