Fennix: Drivers/audio/hda/main.c File Reference
main.c File Reference
#include <base.h>
#include "hda.hpp"
Functions
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
int DriverProbe ()
DriverInfo ("hda", "Intel High Definition Audio Driver", "EnderIce2", 0, 0, 1, "GPLv3")
Function Documentation
DriverEntry()
int DriverEntry ()
Definition at line 22 of file main.c.
 { return cxx_Initialize(); }
References cxx_Initialize().
DriverFinal()
int DriverFinal ()
Definition at line 23 of file main.c.
 { return cxx_Finalize(); }
References cxx_Finalize().
DriverInfo()
DriverInfo ("hda" , "Intel High Definition Audio Driver" , "EnderIce2" , 0 , 0 , 1 , "GPLv3")
DriverPanic()
int DriverPanic ()
Definition at line 24 of file main.c.
 { return cxx_Panic(); }
References cxx_Panic().
DriverProbe()
int DriverProbe ()
Definition at line 25 of file main.c.
 { return cxx_Probe(); }
References cxx_Probe().