Fennix Userspace: Userspace/apps/base/busybox/libbb/get_cpu_count.c File Reference
get_cpu_count.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC starts_with_cpu (const char *str)
unsigned FAST_FUNC get_cpu_count (void)
Function Documentation
get_cpu_count()
unsigned FAST_FUNC get_cpu_count (void)
Definition at line 22 of file get_cpu_count.c.
 {
     FILE *fp;
     char line[256];
     int proc_nr = -1;
     fp = xfopen_for_read("/proc/stat");
     while (fgets(line, sizeof(line), fp)) {
         if (!starts_with_cpu(line)) {
             if (proc_nr >= 0)
                 break; /* we are past "cpuN..." lines */
             continue;
         }
         if (line[3] != ' ') { /* "cpuN" */
             int num_proc;
             if (sscanf(line + 3, "%u", &num_proc) == 1
              && num_proc > proc_nr
             ) {
                 proc_nr = num_proc;
             }
         }
     }
     fclose(fp);
     return proc_nr + 1;
 }
References fclose(), fgets, sscanf(), starts_with_cpu(), and xfopen_for_read().
Referenced by iostat_main(), mpstat_main(), and powertop_main().
starts_with_cpu()
int FAST_FUNC starts_with_cpu (const char * str)
Definition at line 12 of file get_cpu_count.c.
 {
     return ((str[0] - 'c') | (str[1] - 'p') | (str[2] - 'u')) == 0;
 }
References str.
Referenced by get_cpu_count(), and get_cpu_statistics().