Fennix: ACPI::ACPI Class Reference
ACPI::ACPI Class Reference
#include <acpi.hpp>
Data Structures
struct ACPIHeader
struct BGRTHeader
struct DBG2Device
struct DBG2Header
struct DBGPHeader
struct FADTHeader
struct GenericAddressStructure
struct HESTHeader
struct HPETHeader
struct MADTHeader
struct MCFGHeader
struct SRATHeader
struct SSDTHeader
struct TCPAHeader
struct TPM2Header
struct WAETHeader
Public Types
enum DBG2PortType { TYPE_SERIAL = 0x8000 , TYPE_1394 = 0x8001 , TYPE_USB = 0x8002 , TYPE_NET = 0x8003 }
enum DBG2PortSubtype {
SUBTYPE_SERIAL_16550_COMPATIBLE = 0x0000 , SUBTYPE_SERIAL_16550_SUBSET = 0x0001 , SUBTYPE_SERIAL_MAX311xE_SPI_UART = 0x0002 , SUBTYPE_SERIAL_Arm_PL011_UART = 0x0003 ,
SUBTYPE_SERIAL_MSM8x60 = 0x0004 , SUBTYPE_SERIAL_Nvidia_16550 = 0x0005 , SUBTYPE_SERIAL_TI_OMAP = 0x0006 , SUBTYPE_SERIAL_APM88xxxx = 0x0008 ,
SUBTYPE_SERIAL_MSM8974 = 0x0009 , SUBTYPE_SERIAL_SAM5250 = 0x000A , SUBTYPE_SERIAL_Intel_USIF = 0x000B , SUBTYPE_SERIAL_iMX6 = 0x000C ,
SUBTYPE_SERIAL_Arm_SBSA_UART = 0x000D , SUBTYPE_SERIAL_Arm_SBSA_Generic_UART = 0x000E , SUBTYPE_SERIAL_Arm_DCC = 0x000F , SUBTYPE_SERIAL_BCM2835 = 0x0010 ,
SUBTYPE_SERIAL_SDM845_At_1_8432MHz = 0x0011 , SUBTYPE_SERIAL_16550_With_Generic_Address_Structure = 0x0012 , SUBTYPE_SERIAL_SDM845_At_7_372MHz = 0x0013 , SUBTYPE_SERIAL_Intel_LPSS = 0x0014 ,
SUBTYPE_SERIAL_RISC_V_SBI_Console = 0x0015 , SUBTYPE_1394_IEEE1394_HCI = 0x0000 , SUBTYPE_USB_XHCI = 0x0000 , SUBTYPE_USB_EHCI = 0x0001 ,
SUBTYPE_NET_NNNN = 0x0000
}
Public Member Functions
void * FindTable (ACPIHeader *ACPIHeader, char *Signature)
void SearchTables (ACPIHeader *Header)
ACPI ()
~ACPI ()
Data Fields
struct ACPI::ACPI::ACPIHeader __packed
struct ACPI::ACPI::GenericAddressStructure __packed
struct ACPI::ACPI::DBG2Device __packed
struct ACPI::ACPI::MCFGHeader __packed
struct ACPI::ACPI::HPETHeader __packed
struct ACPI::ACPI::FADTHeader __packed
struct ACPI::ACPI::BGRTHeader __packed
struct ACPI::ACPI::SRATHeader __packed
struct ACPI::ACPI::TPM2Header __packed
struct ACPI::ACPI::TCPAHeader __packed
struct ACPI::ACPI::WAETHeader __packed
struct ACPI::ACPI::HESTHeader __packed
struct ACPI::ACPI::MADTHeader __packed
struct ACPI::ACPI::SSDTHeader __packed
struct ACPI::ACPI::DBGPHeader __packed
struct ACPI::ACPI::DBG2Header __packed
ACPIHeader * XSDT = nullptr
MCFGHeader * MCFG = nullptr
HPETHeader * HPET = nullptr
FADTHeader * FADT = nullptr
BGRTHeader * BGRT = nullptr
SRATHeader * SRAT = nullptr
TPM2Header * TPM2 = nullptr
TCPAHeader * TCPA = nullptr
WAETHeader * WAET = nullptr
MADTHeader * MADT = nullptr
HESTHeader * HEST = nullptr
SSDTHeader * SSDT = nullptr
DBGPHeader * DBGP = nullptr
DBG2Header * DBG2 = nullptr
bool XSDTSupported = false
std::unordered_map< const char *, ACPIHeader * > Tables
Detailed Description
Definition at line 31 of file acpi.hpp.
Data Structure Documentation
ACPI::ACPI::ACPIHeader
struct ACPI::ACPI::ACPIHeader
Definition at line 34 of file acpi.hpp.
Data Fields
uint8_t Checksum
uint32_t CreatorID
uint32_t CreatorRevision
uint32_t Length
uint8_t OEMID[6]
uint32_t OEMRevision
uint8_t OEMTableID[8]
uint8_t Revision
unsigned char Signature[4]
ACPI::ACPI::BGRTHeader
struct ACPI::ACPI::BGRTHeader
Definition at line 193 of file acpi.hpp.
Data Fields
ACPIHeader Header
uint64_t ImageAddress
uint32_t ImageOffsetX
uint32_t ImageOffsetY
uint8_t ImageType
uint8_t Status
uint16_t Version
ACPI::ACPI::DBG2Device
struct ACPI::ACPI::DBG2Device
Definition at line 96 of file acpi.hpp.
Data Fields
uint16_t AddressSizeOffset
uint16_t BaseAddressRegisterOffset
uint16_t Length
uint16_t NamespaceStringLength
uint16_t NamespaceStringOffset
uint8_t NumberofGenericAddressRegisters
uint16_t OemDataLength
uint16_t OemDataOffset
uint16_t PortSubtype
uint16_t PortType
uint16_t Reserved
uint8_t Revision
ACPI::ACPI::DBG2Header
struct ACPI::ACPI::DBG2Header
Definition at line 265 of file acpi.hpp.
Data Fields
ACPIHeader Header
uint32_t NumberDbgDeviceInfo
uint32_t OffsetDbgDeviceInfo
ACPI::ACPI::DBGPHeader
struct ACPI::ACPI::DBGPHeader
Definition at line 253 of file acpi.hpp.
Data Fields
GenericAddressStructure BaseAddress
ACPIHeader Header
uint8_t InterfaceType
0 - 16550 compatible 1 - Subset of 16550
uint8_t Reserved[3]
ACPI::ACPI::FADTHeader
struct ACPI::ACPI::FADTHeader
Definition at line 137 of file acpi.hpp.
Data Fields
uint8_t AcpiDisable
uint8_t AcpiEnable
uint16_t BootArchitectureFlags
uint8_t Century
uint8_t CStateControl
uint8_t DayAlarm
uint32_t Dsdt
uint8_t DutyOffset
uint8_t DutyWidth
uint32_t FirmwareCtrl
uint32_t Flags
uint16_t FlushSize
uint16_t FlushStride
uint32_t GPE0Block
uint8_t GPE0Length
uint8_t GPE1Base
uint32_t GPE1Block
uint8_t GPE1Length
ACPIHeader Header
uint8_t MonthAlarm
uint32_t PM1aControlBlock
uint32_t PM1aEventBlock
uint32_t PM1bControlBlock
uint32_t PM1bEventBlock
uint8_t PM1ControlLength
uint8_t PM1EventLength
uint32_t PM2ControlBlock
uint8_t PM2ControlLength
uint32_t PMTimerBlock
uint8_t PMTimerLength
uint8_t PreferredPowerManagementProfile
uint8_t PSTATE_Control
uint8_t Reserved
uint8_t Reserved2
uint8_t Reserved3[3]
struct GenericAddressStructure ResetReg
uint8_t ResetValue
uint8_t S4BIOS_REQ
uint16_t SCI_Interrupt
uint32_t SMI_CommandPort
uint16_t WorstC2Latency
uint16_t WorstC3Latency
uint64_t X_Dsdt
uint64_t X_FirmwareControl
struct GenericAddressStructure X_GPE0Block
struct GenericAddressStructure X_GPE1Block
struct GenericAddressStructure X_PM1aControlBlock
struct GenericAddressStructure X_PM1aEventBlock
struct GenericAddressStructure X_PM1bControlBlock
struct GenericAddressStructure X_PM1bEventBlock
struct GenericAddressStructure X_PM2ControlBlock
struct GenericAddressStructure X_PMTimerBlock
ACPI::ACPI::GenericAddressStructure
struct ACPI::ACPI::GenericAddressStructure
Definition at line 47 of file acpi.hpp.
Data Fields
uint8_t AccessSize
uint64_t Address
uint8_t AddressSpace
uint8_t BitOffset
uint8_t BitWidth
ACPI::ACPI::HESTHeader
struct ACPI::ACPI::HESTHeader
Definition at line 233 of file acpi.hpp.
Data Fields
uint32_t ErrorSourceCount
ACPIHeader Header
ACPI::ACPI::HPETHeader
struct ACPI::ACPI::HPETHeader
Definition at line 122 of file acpi.hpp.
Data Fields
struct GenericAddressStructure Address
uint8_t ComparatorCount: 5
uint8_t CounterSize: 1
uint8_t HardwareRevID
ACPIHeader Header
uint8_t HPETNumber
uint8_t LegacyReplacement: 1
uint16_t MinimumTick
uint8_t PageProtection
uint16_t PCIVendorID
uint8_t Reserved: 1
ACPI::ACPI::MADTHeader
struct ACPI::ACPI::MADTHeader
Definition at line 239 of file acpi.hpp.
Data Fields
char Entries[]
uint32_t Flags
ACPIHeader Header
uint32_t LocalControllerAddress
ACPI::ACPI::MCFGHeader
struct ACPI::ACPI::MCFGHeader
Definition at line 116 of file acpi.hpp.
Data Fields
struct ACPIHeader Header
uint64_t Reserved
ACPI::ACPI::SRATHeader
struct ACPI::ACPI::SRATHeader
Definition at line 204 of file acpi.hpp.
Data Fields
ACPIHeader Header
uint64_t Reserved
uint32_t TableRevision
ACPI::ACPI::SSDTHeader
struct ACPI::ACPI::SSDTHeader
Definition at line 247 of file acpi.hpp.
Data Fields
char DefinitionBlock[]
ACPIHeader Header
ACPI::ACPI::TCPAHeader
struct ACPI::ACPI::TCPAHeader
Definition at line 219 of file acpi.hpp.
Data Fields
ACPIHeader Header
uint64_t LogAddress
uint32_t MaxLogLength
uint16_t Reserved
ACPI::ACPI::TPM2Header
struct ACPI::ACPI::TPM2Header
Definition at line 211 of file acpi.hpp.
Data Fields
uint64_t ControlAddress
uint32_t Flags
ACPIHeader Header
uint32_t StartMethod
ACPI::ACPI::WAETHeader
struct ACPI::ACPI::WAETHeader
Definition at line 227 of file acpi.hpp.
Data Fields
uint32_t Flags
ACPIHeader Header
Member Enumeration Documentation
DBG2PortSubtype
enum ACPI::ACPI::DBG2PortSubtype
Enumerator
SUBTYPE_SERIAL_16550_COMPATIBLE
SUBTYPE_SERIAL_16550_SUBSET
SUBTYPE_SERIAL_MAX311xE_SPI_UART
SUBTYPE_SERIAL_Arm_PL011_UART
SUBTYPE_SERIAL_MSM8x60
SUBTYPE_SERIAL_Nvidia_16550
SUBTYPE_SERIAL_TI_OMAP
SUBTYPE_SERIAL_APM88xxxx
SUBTYPE_SERIAL_MSM8974
SUBTYPE_SERIAL_SAM5250
SUBTYPE_SERIAL_Intel_USIF
SUBTYPE_SERIAL_iMX6
SUBTYPE_SERIAL_Arm_SBSA_UART
SUBTYPE_SERIAL_Arm_SBSA_Generic_UART
SUBTYPE_SERIAL_Arm_DCC
SUBTYPE_SERIAL_BCM2835
SUBTYPE_SERIAL_SDM845_At_1_8432MHz
SUBTYPE_SERIAL_16550_With_Generic_Address_Structure
SUBTYPE_SERIAL_SDM845_At_7_372MHz
SUBTYPE_SERIAL_Intel_LPSS
SUBTYPE_SERIAL_RISC_V_SBI_Console
SUBTYPE_1394_IEEE1394_HCI
SUBTYPE_USB_XHCI
SUBTYPE_USB_EHCI
SUBTYPE_NET_NNNN
Definition at line 64 of file acpi.hpp.
         {
             SUBTYPE_SERIAL_16550_COMPATIBLE = 0x0000,
             SUBTYPE_SERIAL_16550_SUBSET = 0x0001,
             SUBTYPE_SERIAL_MAX311xE_SPI_UART = 0x0002,
             SUBTYPE_SERIAL_Arm_PL011_UART = 0x0003,
             SUBTYPE_SERIAL_MSM8x60 = 0x0004,
             SUBTYPE_SERIAL_Nvidia_16550 = 0x0005,
             SUBTYPE_SERIAL_TI_OMAP = 0x0006,
             SUBTYPE_SERIAL_APM88xxxx = 0x0008,
             SUBTYPE_SERIAL_MSM8974 = 0x0009,
             SUBTYPE_SERIAL_SAM5250 = 0x000A,
             SUBTYPE_SERIAL_Intel_USIF = 0x000B,
             SUBTYPE_SERIAL_iMX6 = 0x000C,
             SUBTYPE_SERIAL_Arm_SBSA_UART = 0x000D,
             SUBTYPE_SERIAL_Arm_SBSA_Generic_UART = 0x000E,
             SUBTYPE_SERIAL_Arm_DCC = 0x000F,
             SUBTYPE_SERIAL_BCM2835 = 0x0010,
             SUBTYPE_SERIAL_SDM845_At_1_8432MHz = 0x0011,
             SUBTYPE_SERIAL_16550_With_Generic_Address_Structure = 0x0012,
             SUBTYPE_SERIAL_SDM845_At_7_372MHz = 0x0013,
             SUBTYPE_SERIAL_Intel_LPSS = 0x0014,
             SUBTYPE_SERIAL_RISC_V_SBI_Console = 0x0015,
             SUBTYPE_1394_IEEE1394_HCI = 0x0000,
             SUBTYPE_USB_XHCI = 0x0000,
             SUBTYPE_USB_EHCI = 0x0001,
             SUBTYPE_NET_NNNN = 0x0000,
         };
DBG2PortType
enum ACPI::ACPI::DBG2PortType
Enumerator
TYPE_SERIAL
TYPE_1394
TYPE_USB
TYPE_NET
Definition at line 56 of file acpi.hpp.
         {
             TYPE_SERIAL = 0x8000,
             TYPE_1394 = 0x8001,
             TYPE_USB = 0x8002,
             TYPE_NET = 0x8003
         };
Constructor & Destructor Documentation
ACPI()
ACPI::ACPI::ACPI ()
Definition at line 164 of file acpi.cpp.
     {
         trace("Initializing ACPI");
         if (!bInfo.RSDP)
         {
             error("RSDP not found!");
             return;
         }
         if (bInfo.RSDP->Revision >= 2 && bInfo.RSDP->XSDTAddress)
         {
             debug("XSDT supported");
             XSDTSupported = true;
             XSDT = (ACPIHeader *)(bInfo.RSDP->XSDTAddress);
         }
         else
         {
             debug("RSDT supported");
             XSDT = (ACPIHeader *)(uintptr_t)bInfo.RSDP->RSDTAddress;
         }
         if (!Memory::Virtual().Check(XSDT))
         {
             warn("%s is not mapped!",
                  XSDTSupported ? "XSDT" : "RSDT");
             debug("XSDT: %p", XSDT);
             Memory::Virtual().Map(XSDT, XSDT, Memory::RW);
         }
         this->SearchTables(XSDT);
         if (FADT)
         {
             outb(s_cst(uint16_t, FADT->SMI_CommandPort), FADT->AcpiEnable);
             /* TODO: Sleep for ~5 seconds before polling PM1a CB? */
             while (!(inw(s_cst(uint16_t, FADT->PM1aControlBlock)) & 1))
                 CPU::Pause();
         }
     }
References bInfo, Memory::Virtual::Check(), debug, error, inw(), Memory::Virtual::Map(), outb(), CPU::Pause(), Memory::RW, trace, and warn.
~ACPI()
ACPI::ACPI::~ACPI ()
Definition at line 204 of file acpi.cpp.
     {
     }
Member Function Documentation
FindTable()
void* ACPI::ACPI::FindTable (ACPIHeader * ACPIHeader, char * Signature)
SearchTables()
void ACPI::ACPI::SearchTables (ACPIHeader * Header)
Definition at line 68 of file acpi.cpp.
     {
         if (!Header)
             return;
         HPET = (HPETHeader *)FindTable(Header, (char *)"HPET");
         FADT = (FADTHeader *)FindTable(Header, (char *)"FACP");
         MCFG = (MCFGHeader *)FindTable(Header, (char *)"MCFG");
         BGRT = (BGRTHeader *)FindTable(Header, (char *)"BGRT");
         SRAT = (SRATHeader *)FindTable(Header, (char *)"SRAT");
         TPM2 = (TPM2Header *)FindTable(Header, (char *)"TPM2");
         TCPA = (TCPAHeader *)FindTable(Header, (char *)"TCPA");
         WAET = (WAETHeader *)FindTable(Header, (char *)"WAET");
         MADT = (MADTHeader *)FindTable(Header, (char *)"APIC");
         HEST = (HESTHeader *)FindTable(Header, (char *)"HEST");
         SSDT = (SSDTHeader *)FindTable(Header, (char *)"SSDT");
         DBGP = (DBGPHeader *)FindTable(Header, (char *)"DBGP");
         DBG2 = (DBG2Header *)FindTable(Header, (char *)"DBG2");
         FindTable(Header, (char *)"BERT");
         FindTable(Header, (char *)"CPEP");
         FindTable(Header, (char *)"DSDT");
         FindTable(Header, (char *)"ECDT");
         FindTable(Header, (char *)"EINJ");
         FindTable(Header, (char *)"ERST");
         FindTable(Header, (char *)"FACS");
         FindTable(Header, (char *)"MSCT");
         FindTable(Header, (char *)"MPST");
         FindTable(Header, (char *)"OEMx");
         FindTable(Header, (char *)"PMTT");
         FindTable(Header, (char *)"PSDT");
         FindTable(Header, (char *)"RASF");
         FindTable(Header, (char *)"RSDT");
         FindTable(Header, (char *)"SBST");
         FindTable(Header, (char *)"SLIT");
         FindTable(Header, (char *)"XSDT");
         FindTable(Header, (char *)"DRTM");
         FindTable(Header, (char *)"FPDT");
         FindTable(Header, (char *)"GTDT");
         FindTable(Header, (char *)"PCCT");
         FindTable(Header, (char *)"S3PT");
         FindTable(Header, (char *)"MATR");
         FindTable(Header, (char *)"MSDM");
         FindTable(Header, (char *)"WPBT");
         FindTable(Header, (char *)"OSDT");
         FindTable(Header, (char *)"RSDP");
         FindTable(Header, (char *)"NFIT");
         FindTable(Header, (char *)"ASF!");
         FindTable(Header, (char *)"BOOT");
         FindTable(Header, (char *)"CSRT");
         FindTable(Header, (char *)"BDAT");
         FindTable(Header, (char *)"CDAT");
         FindTable(Header, (char *)"DMAR");
         FindTable(Header, (char *)"IBFT");
         FindTable(Header, (char *)"IORT");
         FindTable(Header, (char *)"IVRS");
         FindTable(Header, (char *)"LPIT");
         FindTable(Header, (char *)"MCHI");
         FindTable(Header, (char *)"MTMR");
         FindTable(Header, (char *)"SLIC");
         FindTable(Header, (char *)"SPCR");
         FindTable(Header, (char *)"SPMI");
         FindTable(Header, (char *)"UEFI");
         FindTable(Header, (char *)"VRTC");
         FindTable(Header, (char *)"WDAT");
         FindTable(Header, (char *)"WDDT");
         FindTable(Header, (char *)"WDRT");
         FindTable(Header, (char *)"ATKG");
         FindTable(Header, (char *)"GSCI");
         FindTable(Header, (char *)"IEIT");
         FindTable(Header, (char *)"HMAT");
         FindTable(Header, (char *)"CEDT");
         FindTable(Header, (char *)"AEST");
         FindTable(Header, (char *)"AGDI");
         FindTable(Header, (char *)"APMT");
         FindTable(Header, (char *)"ETDT");
         FindTable(Header, (char *)"MPAM");
         FindTable(Header, (char *)"PDTT");
         FindTable(Header, (char *)"PPTT");
         FindTable(Header, (char *)"RAS2");
         FindTable(Header, (char *)"SDEI");
         FindTable(Header, (char *)"STAO");
         FindTable(Header, (char *)"XENV");
         FindTable(Header, (char *)"PHAT");
         FindTable(Header, (char *)"SVKL");
         FindTable(Header, (char *)"UUID");
         FindTable(Header, (char *)"CCEL");
         FindTable(Header, (char *)"WSMT");
         FindTable(Header, (char *)"PRMT");
         FindTable(Header, (char *)"NBFT");
         FindTable(Header, (char *)"RSD PTR");
         FindTable(Header, (char *)"TDX");
         FindTable(Header, (char *)"CXL");
         FindTable(Header, (char *)"DSD");
         FindTable(Header, (char *)"BSA");
     }
Field Documentation
__packed [1/16]
struct ACPI::ACPI::ACPIHeader ACPI::ACPI::__packed
__packed [2/16]
struct ACPI::ACPI::GenericAddressStructure ACPI::ACPI::__packed
__packed [3/16]
struct ACPI::ACPI::DBG2Device ACPI::ACPI::__packed
__packed [4/16]
struct ACPI::ACPI::MCFGHeader ACPI::ACPI::__packed
__packed [5/16]
struct ACPI::ACPI::HPETHeader ACPI::ACPI::__packed
__packed [6/16]
struct ACPI::ACPI::FADTHeader ACPI::ACPI::__packed
__packed [7/16]
struct ACPI::ACPI::BGRTHeader ACPI::ACPI::__packed
__packed [8/16]
struct ACPI::ACPI::SRATHeader ACPI::ACPI::__packed
__packed [9/16]
struct ACPI::ACPI::TPM2Header ACPI::ACPI::__packed
__packed [10/16]
struct ACPI::ACPI::TCPAHeader ACPI::ACPI::__packed
__packed [11/16]
struct ACPI::ACPI::WAETHeader ACPI::ACPI::__packed
__packed [12/16]
struct ACPI::ACPI::HESTHeader ACPI::ACPI::__packed
__packed [13/16]
struct ACPI::ACPI::MADTHeader ACPI::ACPI::__packed
__packed [14/16]
struct ACPI::ACPI::SSDTHeader ACPI::ACPI::__packed
__packed [15/16]
struct ACPI::ACPI::DBGPHeader ACPI::ACPI::__packed
__packed [16/16]
struct ACPI::ACPI::DBG2Header ACPI::ACPI::__packed
BGRT
BGRTHeader* ACPI::ACPI::BGRT = nullptr
Definition at line 277 of file acpi.hpp.
DBG2
DBG2Header* ACPI::ACPI::DBG2 = nullptr
Definition at line 286 of file acpi.hpp.
DBGP
DBGPHeader* ACPI::ACPI::DBGP = nullptr
Definition at line 285 of file acpi.hpp.
FADT
FADTHeader* ACPI::ACPI::FADT = nullptr
Definition at line 276 of file acpi.hpp.
Referenced by ACPI::DSDT::DSDT(), ACPI::DSDT::OnInterruptReceived(), and ACPI::DSDT::Reboot().
HEST
HESTHeader* ACPI::ACPI::HEST = nullptr
Definition at line 283 of file acpi.hpp.
HPET
HPETHeader* ACPI::ACPI::HPET = nullptr
Definition at line 275 of file acpi.hpp.
MADT
MADTHeader* ACPI::ACPI::MADT = nullptr
Definition at line 282 of file acpi.hpp.
MCFG
MCFGHeader* ACPI::ACPI::MCFG = nullptr
Definition at line 274 of file acpi.hpp.
SRAT
SRATHeader* ACPI::ACPI::SRAT = nullptr
Definition at line 278 of file acpi.hpp.
SSDT
SSDTHeader* ACPI::ACPI::SSDT = nullptr
Definition at line 284 of file acpi.hpp.
Tables
std::unordered_map<const char *, ACPIHeader *> ACPI::ACPI::Tables
Definition at line 289 of file acpi.hpp.
TCPA
TCPAHeader* ACPI::ACPI::TCPA = nullptr
Definition at line 280 of file acpi.hpp.
TPM2
TPM2Header* ACPI::ACPI::TPM2 = nullptr
Definition at line 279 of file acpi.hpp.
WAET
WAETHeader* ACPI::ACPI::WAET = nullptr
Definition at line 281 of file acpi.hpp.
XSDT
ACPIHeader* ACPI::ACPI::XSDT = nullptr
Definition at line 273 of file acpi.hpp.
XSDTSupported
bool ACPI::ACPI::XSDTSupported = false
Definition at line 287 of file acpi.hpp.
Referenced by ACPI::DSDT::DSDT().
The documentation for this class was generated from the following files:
Kernel/include/acpi.hpp
Kernel/core/acpi.cpp