Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/w_merge.h File Reference
w_merge.h File Reference
Macros
#define W_NWT_MERGE_SPRITES 0x1
#define W_NWT_MERGE_FLATS 0x2
Functions
void W_MergeFile (char *filename)
void W_NWTMergeFile (char *filename, int flags)
void W_NWTDashMerge (char *filename)
void W_PrintDirectory (void)
Macro Definition Documentation
W_NWT_MERGE_FLATS
#define W_NWT_MERGE_FLATS 0x2
Definition at line 25 of file w_merge.h.
W_NWT_MERGE_SPRITES
#define W_NWT_MERGE_SPRITES 0x1
Definition at line 24 of file w_merge.h.
Function Documentation
W_MergeFile()
void W_MergeFile (char * filename)
Referenced by W_ParseCommandLine().
W_NWTDashMerge()
void W_NWTDashMerge (char * filename)
Referenced by W_ParseCommandLine().
W_NWTMergeFile()
void W_NWTMergeFile (char * filename, int flags)
Referenced by W_ParseCommandLine().
W_PrintDirectory()
void W_PrintDirectory (void)