Fennix: Userspace/apps/base/bash/lib/sh/eaccess.c File Reference
eaccess.c File Reference
#include <stdio.h>
#include "bashtypes.h"
#include "bashansi.h"
#include <errno.h>
#include "posixstat.h"
#include "filecntl.h"
#include "shell.h"
Macros
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define F_OK 0
Functions
static int path_is_devfd PARAMS ((const char *))
static int sh_stataccess PARAMS ((const char *, int))
static int path_is_devfd (char *path) const
int sh_stat (char *path, struct stat *finfo) const
static int sh_stataccess (char *path, int mode) const
int sh_eaccess (char *path, int mode) const
Variables
int errno
Macro Definition Documentation
F_OK
#define F_OK 0
Definition at line 52 of file eaccess.c.
R_OK
#define R_OK 4
Definition at line 49 of file eaccess.c.
W_OK
#define W_OK 2
Definition at line 50 of file eaccess.c.
X_OK
#define X_OK 1
Definition at line 51 of file eaccess.c.
Function Documentation
PARAMS() [1/2]
static int path_is_devfd PARAMS ((const char *)) static
PARAMS() [2/2]
static int sh_stataccess PARAMS ((const char *, int)) static
path_is_devfd()
static int path_is_devfd (char * path) const static
Definition at line 62 of file eaccess.c.
 {
   if (path[0] == '/' && path[1] == 'd' && strncmp (path, "/dev/fd/", 8) == 0)
     return 1;
   else if (STREQN (path, "/dev/std", 8))
     {
       if (STREQ (path+8, "in") || STREQ (path+8, "out") || STREQ (path+8, "err"))
     return 1;
       else
     return 0;
     }
   else
     return 0;
 }
References STREQ, STREQN, and strncmp().
Referenced by sh_eaccess().
sh_eaccess()
int sh_eaccess (char * path, int mode) const
Definition at line 201 of file eaccess.c.
 {
   int ret;
   if (path_is_devfd (path))
     return (sh_stataccess (path, mode));
 #if (defined (HAVE_FACCESSAT) && defined (AT_EACCESS)) || defined (HAVE_EACCESS)
 #  if defined (HAVE_FACCESSAT) && defined (AT_EACCESS)
   ret = faccessat (AT_FDCWD, path, mode, AT_EACCESS);
 #  else     /* HAVE_EACCESS */  /* FreeBSD */
   ret = eaccess (path, mode);   /* XXX -- not always correct for X_OK */
 #  endif    /* HAVE_EACCESS */
 #  if defined (__FreeBSD__) || defined (SOLARIS) || defined (_AIX)
   if (ret == 0 && current_user.euid == 0 && mode == X_OK)
     return (sh_stataccess (path, mode));
 #  endif    /* __FreeBSD__ || SOLARIS || _AIX */
   return ret;
 #elif defined (EFF_ONLY_OK)     /* SVR4(?), SVR4.2 */
   return access (path, mode|EFF_ONLY_OK);
 #else
   if (mode == F_OK)
     return (sh_stataccess (path, mode));
 #  if HAVE_DECL_SETREGID
   if (current_user.uid != current_user.euid || current_user.gid != current_user.egid)
     return (sh_euidaccess (path, mode));
 #  endif
   if (current_user.uid == current_user.euid && current_user.gid == current_user.egid)
     {
       ret = access (path, mode);
 #if defined (__FreeBSD__) || defined (SOLARIS)
       if (ret == 0 && current_user.euid == 0 && mode == X_OK)
     return (sh_stataccess (path, mode));
 #endif
       return ret;
     }
   return (sh_stataccess (path, mode));
 #endif
 }
References access(), AT_EACCESS, AT_FDCWD, current_user, user_info::egid, user_info::euid, F_OK, faccessat(), user_info::gid, path_is_devfd(), sh_stataccess(), user_info::uid, and X_OK.
Referenced by file_iswdir(), and unary_test().
sh_stat()
int sh_stat (char * path, struct stat * finfo) const
Definition at line 81 of file eaccess.c.
 {
   static char *pbuf = 0;
   if (*path == '\0')
     {
       errno = ENOENT;
       return (-1);
     }
   if (path[0] == '/' && path[1] == 'd' && strncmp (path, "/dev/fd/", 8) == 0)
     {
       /* If stating /dev/fd/n doesn't produce the same results as fstat of
      FD N, then define DEV_FD_STAT_BROKEN */
 #if !defined (HAVE_DEV_FD) || defined (DEV_FD_STAT_BROKEN)
       intmax_t fd;
       int r;
       if (legal_number (path + 8, &fd) && fd == (int)fd)
         {
           r = fstat ((int)fd, finfo);
           if (r == 0 || errno != EBADF)
             return (r);
         }
       errno = ENOENT;
       return (-1);
 #else
   /* If HAVE_DEV_FD is defined, DEV_FD_PREFIX is defined also, and has a
      trailing slash.  Make sure /dev/fd/xx really uses DEV_FD_PREFIX/xx.
      On most systems, with the notable exception of linux, this is
      effectively a no-op. */
       pbuf = xrealloc (pbuf, sizeof (DEV_FD_PREFIX) + strlen (path + 8));
       strcpy (pbuf, DEV_FD_PREFIX);
       strcat (pbuf, path + 8);
       return (stat (pbuf, finfo));
 #endif /* !HAVE_DEV_FD */
     }
 #if !defined (HAVE_DEV_STDIN)
   else if (STREQN (path, "/dev/std", 8))
     {
       if (STREQ (path+8, "in"))
     return (fstat (0, finfo));
       else if (STREQ (path+8, "out"))
     return (fstat (1, finfo));
       else if (STREQ (path+8, "err"))
     return (fstat (2, finfo));
       else
     return (stat (path, finfo));
     }
 #endif /* !HAVE_DEV_STDIN */
   return (stat (path, finfo));
 }
References DEV_FD_PREFIX, EBADF, ENOENT, errno, fd, fstat(), legal_number(), strcat, strcpy, STREQ, STREQN, strlen(), strncmp(), and xrealloc.
Referenced by sh_stataccess(), stat_mtime(), and unary_test().
sh_stataccess()
static int sh_stataccess (char * path, int mode) const static
Definition at line 139 of file eaccess.c.
 {
   struct stat st;
   if (sh_stat (path, &st) < 0)
     return (-1);
   if (current_user.euid == 0)
     {
       /* Root can read or write any file. */
       if ((mode & X_OK) == 0)
     return (0);
       /* Root can execute any file that has any one of the execute
      bits set. */
       if (st.st_mode & S_IXUGO)
     return (0);
     }
   if (st.st_uid == current_user.euid)   /* owner */
     mode <<= 6;
   else if (group_member (st.st_gid))
     mode <<= 3;
   if (st.st_mode & mode)
     return (0);
   errno = EACCES;
   return (-1);
 }
References current_user, EACCES, errno, user_info::euid, group_member(), S_IXUGO, sh_stat(), and X_OK.
Referenced by sh_eaccess().
Variable Documentation
errno
int errno extern
Referenced by sh_stat(), and sh_stataccess().