Fennix: Userspace/apps/base/busybox/libbb/fclose_nonstdin.c File Reference
fclose_nonstdin.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC fclose_if_not_stdin (FILE *f)
Function Documentation
fclose_if_not_stdin()
int FAST_FUNC fclose_if_not_stdin (FILE * f)
Definition at line 15 of file fclose_nonstdin.c.
 {
     /* Some more paranoid applets want ferror() check too */
     int r = ferror(f); /* NB: does NOT set errno! */
     if (r)
         errno = EIO; /* so we'll help it */
     if (f != stdin)
         return (r | fclose(f)); /* fclose does set errno on error */
     return r;
 }
References EIO, errno, f, fclose(), ferror, and stdin.
Referenced by check_and_close(), cut_main(), diffreg(), expand_main(), fold_main(), get_next_line(), grep_main(), head_main(), load_regexes_from_file(), md5_sha1_sum_main(), paste_files(), paste_files_separate(), sed_main(), setfiles_main(), shuf_main(), sort_main(), strings_main(), and wc_main().