Fennix: Drivers/audio/ac97/ac97.cpp File Reference
ac97.cpp File Reference
#include <errno.h>
#include <audio.h>
#include <regs.h>
#include <base.h>
#include <pci.h>
#include <io.h>
#include <fs.h>
Data Structures
struct BufferDescriptorList
class AC97Device
Macros
#define DescriptorListLength 0x20
#define OIR(x) OIR_##x
#define CREATE_OIR(x) void OIR_##x(TrapFrame *f) { Drivers[x]->OnInterruptReceived(f); }
Enumerations
enum AudioVolumeValues { AV_Maximum = 0x0 , AV_Minimum = 0x3F }
enum AudioEncodingValues {
AE_PCMs8 , AE_PCMu8 , AE_PCMs16le , AE_PCMs20le ,
AE_PCMs24le , AE_PCMs32le , AE_PCMu16le , AE_PCMu20le ,
AE_PCMu24le , AE_PCMu32le , AE_PCMs16be , AE_PCMs20be ,
AE_PCMs24be , AE_PCMs32be , AE_PCMu16be , AE_PCMu20be ,
AE_PCMu24be , AE_PCMu32be
}
enum NativeAudioMixerRegisters {
NAM_Reset = 0x00 , NAM_MasterVolume = 0x02 , NAM_MicrophoneVolume = 0x0E , NAM_PCMOutVolume = 0x18 ,
NAM_SelectRecordInput = 0x1A , NAM_RecordGain = 0x1C , NAM_RecordGainMicrophone = 0x1E
}
enum NativeAudioBusMasterRegisters {
NABM_PCMInBox = 0x00 , NABM_PCMOutBox = 0x10 , NABM_MicrophoneBox = 0x20 , NABM_GlobalControl = 0x2C ,
NABM_GlobalStatus = 0x30
}
enum NativeAudioBusMasterBoxOffsets {
NABMBOFF_BufferDescriptorList = 0x00 , NABMBOFF_BufferDescriptorEntry = 0x04 , NABMBOFF_DescriptorEntries = 0x05 , NABMBOFF_Status = 0x06 ,
NABMBOFF_TransferredSamples = 0x08 , NABMBOFF_NextProcessedBufferEntry = 0x0A , NABMBOFF_TransferControl = 0x0B
}
enum OutputPulseCodeModulationRegisters {
PCMOUT_BufferDescriptorList = (int)NABM_PCMOutBox + (int)NABMBOFF_BufferDescriptorList , PCMOUT_BufferDescriptorEntry = (int)NABM_PCMOutBox + (int)NABMBOFF_BufferDescriptorEntry , PCMOUT_DescriptorEntries = (int)NABM_PCMOutBox + (int)NABMBOFF_DescriptorEntries , PCMOUT_Status = (int)NABM_PCMOutBox + (int)NABMBOFF_Status ,
PCMOUT_TransferredSamples = (int)NABM_PCMOutBox + (int)NABMBOFF_TransferredSamples , PCMOUT_NextProcessedBufferEntry = (int)NABM_PCMOutBox + (int)NABMBOFF_NextProcessedBufferEntry , PCMOUT_TransferControl = (int)NABM_PCMOutBox + (int)NABMBOFF_TransferControl
}
enum TransferControlRegisters {
TC_DMAControllerControl = 0x01 , TC_TransferReset = 0x02 , TC_LastBufferEntryInterruptEnable = 0x04 , TC_IOCInterruptEnable = 0x08 ,
TC_FifoERRORInterruptEnable = 0x10
}
enum GlobalControlRegisters {
GC_GlobalInterruptEnable = 0x01 , GC_ColdReset = 0x02 , GC_WarmReset = 0x04 , GC_ShutDown = 0x08 ,
GC_ChannelsForPCMOutput = 0x30 , GC_PCMOutputMode = 0xC0
}
Functions
struct BufferDescriptorList __attribute__ ((packed))
uint16_t MixerVolume (uint8_t Left, uint8_t Right, bool Mute)
CREATE_OIR (0)
CREATE_OIR (1)
CREATE_OIR (2)
CREATE_OIR (3)
int __fs_Open (struct Inode *, int, mode_t)
int __fs_Close (struct Inode *)
ssize_t __fs_Read (struct Inode *, void *, size_t, off_t)
ssize_t __fs_Write (struct Inode *Node, const void *Buffer, size_t Size, off_t)
int __fs_Ioctl (struct Inode *Node, unsigned long Request, void *Argp)
EXTERNC int cxx_Panic ()
EXTERNC int cxx_Probe ()
EXTERNC int cxx_Initialize ()
EXTERNC int cxx_Finalize ()
Variables
uint32_t Address
Physical Address to sound data in memory.
uint16_t SampleCount
Number of samples in this buffer.
uint16_t Flags
Flags.
class AC97Device __attribute__
AC97Device * Drivers [4] = {nullptr}
dev_t AudioID [4] = {(dev_t)-1}
const struct InodeOperations AudioOps
PCIArray * Devices
Data Structure Documentation
BufferDescriptorList
struct BufferDescriptorList
Definition at line 321 of file ac97.cpp.
Data Fields
uint32_t Address Physical Address to sound data in memory.
Note
Length: dword
uint16_t Flags Flags.
Note
Length: word
Bit 15 = Interrupt fired when data from this entry is transferred Bit 14 = Last entry of buffer, stop playing Other bits = Reserved
uint16_t SampleCount Number of samples in this buffer.
Note
Length: word
Macro Definition Documentation
CREATE_OIR
#define CREATE_OIR (x) void OIR_##x(TrapFrame *f) { Drivers[x]->OnInterruptReceived(f); }
Definition at line 696 of file ac97.cpp.
DescriptorListLength
#define DescriptorListLength 0x20
Definition at line 26 of file ac97.cpp.
OIR
#define OIR (x) OIR_##x
Definition at line 695 of file ac97.cpp.
Enumeration Type Documentation
AudioEncodingValues
enum AudioEncodingValues
Enumerator
AE_PCMs8
AE_PCMu8
AE_PCMs16le
AE_PCMs20le
AE_PCMs24le
AE_PCMs32le
AE_PCMu16le
AE_PCMu20le
AE_PCMu24le
AE_PCMu32le
AE_PCMs16be
AE_PCMs20be
AE_PCMs24be
AE_PCMs32be
AE_PCMu16be
AE_PCMu20be
AE_PCMu24be
AE_PCMu32be
Definition at line 34 of file ac97.cpp.
 {
     AE_PCMs8,
     AE_PCMu8,
     AE_PCMs16le,
     AE_PCMs20le,
     AE_PCMs24le,
     AE_PCMs32le,
     AE_PCMu16le,
     AE_PCMu20le,
     AE_PCMu24le,
     AE_PCMu32le,
     AE_PCMs16be,
     AE_PCMs20be,
     AE_PCMs24be,
     AE_PCMs32be,
     AE_PCMu16be,
     AE_PCMu20be,
     AE_PCMu24be,
     AE_PCMu32be,
 };
AudioVolumeValues
enum AudioVolumeValues
Enumerator
AV_Maximum
AV_Minimum
Definition at line 28 of file ac97.cpp.
 {
     AV_Maximum = 0x0,
     AV_Minimum = 0x3F,
 };
GlobalControlRegisters
enum GlobalControlRegisters
Enumerator
GC_GlobalInterruptEnable
Global Interrupt Enable.
0 = Disable Interrupts 1 = Enable Interrupts
GC_ColdReset
Cold reset.
0 = Device is in reset and can not be used 1 = Resume to operational state
GC_WarmReset
Warm reset.
GC_ShutDown
Shut down.
0 = Device is powered 1 = Shut down
GC_ChannelsForPCMOutput
Channels for PCM Output.
00 = 2 channels 01 = 4 channels 10 = 6 channels 11 = Reserved
GC_PCMOutputMode
PCM Output mode.
00 = 16 bit samples 01 = 20 bit samples
Definition at line 271 of file ac97.cpp.
 {
     GC_GlobalInterruptEnable = 0x01,
     GC_ColdReset = 0x02,
     GC_WarmReset = 0x04,
     GC_ShutDown = 0x08,
     GC_ChannelsForPCMOutput = 0x30,
     GC_PCMOutputMode = 0xC0,
 };
NativeAudioBusMasterBoxOffsets
enum NativeAudioBusMasterBoxOffsets
Enumerator
NABMBOFF_BufferDescriptorList
Physical Address of Buffer Descriptor List.
Note
Length: dword
NABMBOFF_BufferDescriptorEntry
Number of Actual Processed Buffer Descriptor Entry.
Note
Length: byte
NABMBOFF_DescriptorEntries
Number of all Descriptor Entries.
Note
Length: byte
NABMBOFF_Status
Status of transferring Data.
Note
Length: word
NABMBOFF_TransferredSamples
Number of transferred Samples in Actual Processed Entry.
Note
Length: word
NABMBOFF_NextProcessedBufferEntry
Number of next processed Buffer Entry.
Note
Length: byte
NABMBOFF_TransferControl
Transfer Control.
Note
Length: byte
Definition at line 138 of file ac97.cpp.
 {
     NABMBOFF_BufferDescriptorList = 0x00,
     NABMBOFF_BufferDescriptorEntry = 0x04,
     NABMBOFF_DescriptorEntries = 0x05,
     NABMBOFF_Status = 0x06,
     NABMBOFF_TransferredSamples = 0x08,
     NABMBOFF_NextProcessedBufferEntry = 0x0A,
     NABMBOFF_TransferControl = 0x0B,
 };
NativeAudioBusMasterRegisters
enum NativeAudioBusMasterRegisters
Enumerator
NABM_PCMInBox
Register box for PCM IN.
Note
Length: below
NABM_PCMOutBox
Register box for PCM OUT.
Note
Length: below
NABM_MicrophoneBox
Register box for Microphone.
Note
Length: below
NABM_GlobalControl
Global Control Register.
Note
Length: dword
NABM_GlobalStatus
Global Status Register.
Note
Length: dword
Definition at line 105 of file ac97.cpp.
 {
     NABM_PCMInBox = 0x00,
     NABM_PCMOutBox = 0x10,
     NABM_MicrophoneBox = 0x20,
     NABM_GlobalControl = 0x2C, /* 0x30 */
     NABM_GlobalStatus = 0x30, /* 0x34 */
 };
NativeAudioMixerRegisters
enum NativeAudioMixerRegisters
Enumerator
NAM_Reset
Reset Register.
Note
Length: word
NAM_MasterVolume
Master Volume Register.
Note
Length: word
NAM_MicrophoneVolume
Microphone Volume Register.
Note
Length: word
NAM_PCMOutVolume
PCM Out Volume Register.
Note
Length: word
NAM_SelectRecordInput
Select Record Input Register.
Note
Length: word
NAM_RecordGain
Record Gain Register.
Note
Length: word
NAM_RecordGainMicrophone
Record Gain Microphone Register.
Note
Length: word
Definition at line 60 of file ac97.cpp.
 {
     NAM_Reset = 0x00,
     NAM_MasterVolume = 0x02,
     NAM_MicrophoneVolume = 0x0E,
     NAM_PCMOutVolume = 0x18,
     NAM_SelectRecordInput = 0x1A,
     NAM_RecordGain = 0x1C,
     NAM_RecordGainMicrophone = 0x1E,
 };
OutputPulseCodeModulationRegisters
enum OutputPulseCodeModulationRegisters
Enumerator
PCMOUT_BufferDescriptorList
Physical Address of Buffer Descriptor List.
Note
Length: dword
PCMOUT_BufferDescriptorEntry
Number of Actual Processed Buffer Descriptor Entry.
Note
Length: byte
PCMOUT_DescriptorEntries
Number of all Descriptor Entries.
Note
Length: byte
PCMOUT_Status
Status of transferring Data.
Note
Length: word
PCMOUT_TransferredSamples
Number of transferred Samples in Actual Processed Entry.
Note
Length: word
PCMOUT_NextProcessedBufferEntry
Number of next processed Buffer Entry.
Note
Length: byte
PCMOUT_TransferControl
Transfer Control.
Note
Length: byte
Definition at line 183 of file ac97.cpp.
 {
     PCMOUT_BufferDescriptorList = (int)NABM_PCMOutBox + (int)NABMBOFF_BufferDescriptorList,
     PCMOUT_BufferDescriptorEntry = (int)NABM_PCMOutBox + (int)NABMBOFF_BufferDescriptorEntry,
     PCMOUT_DescriptorEntries = (int)NABM_PCMOutBox + (int)NABMBOFF_DescriptorEntries,
     PCMOUT_Status = (int)NABM_PCMOutBox + (int)NABMBOFF_Status,
     PCMOUT_TransferredSamples = (int)NABM_PCMOutBox + (int)NABMBOFF_TransferredSamples,
     PCMOUT_NextProcessedBufferEntry = (int)NABM_PCMOutBox + (int)NABMBOFF_NextProcessedBufferEntry,
     PCMOUT_TransferControl = (int)NABM_PCMOutBox + (int)NABMBOFF_TransferControl,
 };
TransferControlRegisters
enum TransferControlRegisters
Enumerator
TC_DMAControllerControl
DMA controller control.
0 = Pause transfer 1 = Transfer sound data
TC_TransferReset
Reset.
0 = Remove reset condition 1 = Reset this NABM register box, this bit is cleared by card when is reset complete
TC_LastBufferEntryInterruptEnable
Last Buffer Entry Interrupt enable.
0 = Disable interrupt 1 = Enable interrupt
TC_IOCInterruptEnable
IOC Interrupt enable.
0 = Disable interrupt 1 = Enable interrupt
TC_FifoERRORInterruptEnable
Fifo ERROR Interrupt enable.
0 = Disable interrupt 1 = Enable interrupt
Definition at line 228 of file ac97.cpp.
 {
     TC_DMAControllerControl = 0x01,
     TC_TransferReset = 0x02,
     TC_LastBufferEntryInterruptEnable = 0x04,
     TC_IOCInterruptEnable = 0x08,
     TC_FifoERRORInterruptEnable = 0x10,
 };
Function Documentation
__attribute__()
struct BufferDescriptorList __attribute__ ((packed))
Definition at line 1 of file mb_64bit_map.cpp.
 {
     struct
     {
         bool Present : 1;            // 0
         bool ReadWrite : 1;          // 1
         bool UserSupervisor : 1;     // 2
         bool WriteThrough : 1;       // 3
         bool CacheDisable : 1;       // 4
         bool Accessed : 1;           // 5
         bool Dirty : 1;              // 6
         bool PageAttributeTable : 1; // 7
         bool Global : 1;             // 8
         uint8_t Available0 : 3;      // 9-11
         uint64_t Address : 40;       // 12-51
         uint32_t Available1 : 7;     // 52-58
         uint8_t ProtectionKey : 4;   // 59-62
         bool ExecuteDisable : 1;     // 63
     };
     uint64_t raw;
     __always_inline inline nsa NIF void SetAddress(uintptr_t _Address)
     {
         _Address &= 0x000000FFFFFFFFFF;
         this->raw &= 0xFFF0000000000FFF;
         this->raw |= (_Address << 12);
     }
     __always_inline inline nsa NIF uintptr_t GetAddress() { return (this->raw & 0x000FFFFFFFFFF000) >> 12; }
 };
__fs_Close()
int __fs_Close (struct Inode *)
Definition at line 705 of file ac97.cpp.
 { return 0; }
__fs_Ioctl()
int __fs_Ioctl (struct Inode * Node, unsigned long Request, void * Argp)
Definition at line 713 of file ac97.cpp.
 {
     return Drivers[AudioID[Node->GetMinor()]]->ioctl((AudioIoctl)Request, Argp);
 }
References AudioID, Drivers, AC97Device::ioctl(), and Driver::Node.
__fs_Open()
int __fs_Open (struct Inode * , int , mode_t)
Definition at line 704 of file ac97.cpp.
 { return 0; }
__fs_Read()
ssize_t __fs_Read (struct Inode * , void * , size_t , off_t)
Definition at line 706 of file ac97.cpp.
 { return 0; }
__fs_Write()
ssize_t __fs_Write (struct Inode * Node, const void * Buffer, size_t Size, off_t)
Definition at line 708 of file ac97.cpp.
 {
     return Drivers[AudioID[Node->GetMinor()]]->write((uint8_t *)Buffer, Size);
 }
References AudioID, Buffer, Drivers, Driver::Node, Driver::Size, and AC97Device::write().
CREATE_OIR() [1/4]
CREATE_OIR (0)
CREATE_OIR() [2/4]
CREATE_OIR (1)
CREATE_OIR() [3/4]
CREATE_OIR (2)
CREATE_OIR() [4/4]
CREATE_OIR (3)
cxx_Finalize()
EXTERNC int cxx_Finalize ()
Definition at line 848 of file ac97.cpp.
 {
     PCIArray *ctx = Devices;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count++ > sizeof(Drivers) / sizeof(AC97Device *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type != 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is not I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         delete Drivers[Count++];
         ctx->Device->Header->Command |= PCI_COMMAND_INTX_DISABLE;
         ctx = (PCIArray *)ctx->Next;
     }
     for (size_t i = 0; i < sizeof(AudioID) / sizeof(dev_t); i++)
     {
         if (AudioID[i] != (dev_t)-1)
             UnregisterDevice(AudioID[i]);
     }
     return 0;
 }
References AudioID, dev_t, Devices, Drivers, i, if(), KernelLog(), PCI_COMMAND_INTX_DISABLE, and v0::UnregisterDevice().
Referenced by DriverFinal().
cxx_Initialize()
EXTERNC int cxx_Initialize ()
Definition at line 797 of file ac97.cpp.
 {
     PCIArray *ctx = Devices;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count > sizeof(Drivers) / sizeof(AC97Device *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type != 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is not I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         InitializePCI(ctx->Device);
         Drivers[Count] = new AC97Device((PCIHeader0 *)ctx->Device->Header);
         /* FIXME: bad code */
         switch (Count)
         {
         case 0:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(0));
             break;
         case 1:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(1));
             break;
         case 2:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(2));
             break;
         case 3:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(3));
             break;
         default:
             break;
         }
         dev_t ret = RegisterDevice(AUDIO_TYPE_PCM, &AudioOps);
         AudioID[Count] = ret;
         Count++;
         ctx = (PCIArray *)ctx->Next;
     }
     return 0;
 }
References AUDIO_TYPE_PCM, AudioID, AudioOps, dev_t, Devices, Drivers, if(), v0::iLine(), v0::InitializePCI(), KernelLog(), OIR, v0::RegisterDevice(), RegisterInterruptHandler(), and ret.
Referenced by DriverEntry().
cxx_Panic()
EXTERNC int cxx_Panic ()
Definition at line 739 of file ac97.cpp.
 {
     PCIArray *ctx = Devices;
     short Count = 0;
     while (ctx != nullptr)
     {
         if (Drivers[Count] != nullptr)
             Drivers[Count]->Panic();
         Count++;
         ctx = (PCIArray *)ctx->Next;
     }
     return 0;
 }
References Devices, Drivers, and AC97Device::Panic().
Referenced by DriverPanic().
cxx_Probe()
EXTERNC int cxx_Probe ()
Definition at line 754 of file ac97.cpp.
 {
     uint16_t VendorIDs[] = {0x8086, PCI_END};
     uint16_t DeviceIDs[] = {0x2415, PCI_END};
     Devices = GetPCIDevices(VendorIDs, DeviceIDs);
     if (Devices == nullptr)
     {
         KernelLog("No AC'97 device found.");
         return -ENODEV;
     }
     PCIArray *ctx = Devices;
     bool Found = false;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count++ > sizeof(Drivers) / sizeof(AC97Device *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type != 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is not I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         Found = true;
         ctx = (PCIArray *)ctx->Next;
     }
     if (!Found)
     {
         KernelLog("No valid AC'97 device found.");
         return -EINVAL;
     }
     return 0;
 }
References Devices, Drivers, EINVAL, ENODEV, v0::GetPCIDevices(), if(), KernelLog(), and PCI_END.
Referenced by DriverProbe().
MixerVolume()
uint16_t MixerVolume (uint8_t Left, uint8_t Right, bool Mute)
Definition at line 346 of file ac97.cpp.
 {
     return ((uint16_t)((Right & 0x3F) |
                        ((Left & 0x3F) << 0x8) |
                        (Mute & 1 << 0xF)));
 }
Referenced by AC97Device::AC97Device(), and AC97Device::~AC97Device().
Variable Documentation
__attribute__
class AC97Device __attribute__
Address
uint32_t Address
Physical Address to sound data in memory.
Note
Length: dword
Definition at line 4 of file ac97.cpp.
Referenced by AC97Device::AC97Device(), and AC97Device::write().
AudioID
dev_t AudioID[4] = {(dev_t)-1}
Definition at line 693 of file ac97.cpp.
Referenced by __fs_Ioctl(), __fs_Write(), cxx_Finalize(), and cxx_Initialize().
AudioOps
const struct InodeOperations AudioOps
Initial value:
= {
    .Lookup = nullptr,
    .Create = nullptr,
    .Remove = nullptr,
    .Rename = nullptr,
    .Read = __fs_Read,
    .Write = __fs_Write,
    .Truncate = nullptr,
    .Open = __fs_Open,
    .Close = __fs_Close,
    .Ioctl = __fs_Ioctl,
    .ReadDir = nullptr,
    .MkDir = nullptr,
    .RmDir = nullptr,
    .SymLink = nullptr,
    .ReadLink = nullptr,
    .Seek = nullptr,
    .Stat = nullptr,
}
Definition at line 713 of file ac97.cpp.
Referenced by cxx_Initialize().
Devices
PCIArray* Devices
Definition at line 738 of file ac97.cpp.
Referenced by cxx_Finalize(), cxx_Initialize(), cxx_Panic(), cxx_Probe(), and v0::GetPCIDevices().
Drivers
AC97Device* Drivers[4] = {nullptr}
Definition at line 692 of file ac97.cpp.
Referenced by __fs_Ioctl(), __fs_Write(), v0::AllocateMemory(), cxx_Finalize(), cxx_Initialize(), cxx_Panic(), cxx_Probe(), v0::FreeMemory(), v0::GetPCIDevices(), Driver::Manager::LoadAllDrivers(), Driver::Manager::Panic(), Driver::Manager::PreloadDrivers(), and Driver::Manager::UnloadAllDrivers().
Flags
uint16_t Flags
Flags.
Note
Length: word
Bit 15 = Interrupt fired when data from this entry is transferred Bit 14 = Last entry of buffer, stop playing Other bits = Reserved
Definition at line 20 of file ac97.cpp.
Referenced by AC97Device::AC97Device().
SampleCount
uint16_t SampleCount
Number of samples in this buffer.
Note
Length: word
Definition at line 10 of file ac97.cpp.
Referenced by AC97Device::AC97Device(), and AC97Device::write().