Fennix: Userspace/apps/base/bash/expr.c File Reference
expr.c File Reference
#include "config.h"
#include <stdio.h>
#include "bashansi.h"
#include "chartypes.h"
#include "bashintl.h"
#include "shell.h"
#include "arrayfunc.h"
#include "execute_cmd.h"
#include "flags.h"
#include "subst.h"
#include "typemax.h"
Data Structures
struct lvalue
struct EXPR_CONTEXT
Macros
#define cr_whitespace(c) (whitespace(c) || ((c) == '\n'))
#define EXPR_STACK_GROW_SIZE 10
#define MAX_EXPR_RECURSION_LEVEL 1024
#define EQEQ 1 /* "==" */
#define NEQ 2 /* "!=" */
#define LEQ 3 /* "<=" */
#define GEQ 4 /* ">=" */
#define STR 5 /* string */
#define NUM 6 /* number */
#define LAND 7 /* "&&" Logical AND */
#define LOR 8 /* "||" Logical OR */
#define LSH 9 /* "<<" Left SHift */
#define RSH 10 /* ">>" Right SHift */
#define OP_ASSIGN 11 /* op= expassign as in Posix.2 */
#define COND 12 /* exp1 ? exp2 : exp3 */
#define POWER 13 /* exp1**exp2 */
#define PREINC 14 /* ++var */
#define PREDEC 15 /* --var */
#define POSTINC 16 /* var++ */
#define POSTDEC 17 /* var-- */
#define EQ '='
#define GT '>'
#define LT '<'
#define PLUS '+'
#define MINUS '-'
#define MUL '*'
#define DIV '/'
#define MOD '%'
#define NOT '!'
#define LPAR '('
#define RPAR ')'
#define BAND '&' /* Bitwise AND */
#define BOR '|' /* Bitwise OR. */
#define BXOR '^' /* Bitwise eXclusive OR. */
#define BNOT '~' /* Bitwise NOT; Two's complement. */
#define QUES '?'
#define COL ':'
#define COMMA ','
#define EXP_LOWEST expcomma
#define MAX_INT_LEN 32
#define SAVETOK(X)
#define RESTORETOK(X)
#define VALID_NUMCHAR(c) (ISALNUM(c) || ((c) == '_') || ((c) == '@'))
Functions
static int _is_arithop PARAMS ((int))
static void readtok PARAMS ((void))
static void init_lvalue PARAMS ((struct lvalue *))
static intmax_t expr_streval PARAMS ((char *, int, struct lvalue *))
static intmax_t strlong PARAMS ((char *))
static void evalerror PARAMS ((const char *))
static void expr_bind_variable PARAMS ((char *, char *))
static void pushexp ()
static void popexp ()
static void expr_unwind ()
static void expr_bind_variable (char *lhs, char *rhs)
intmax_t evalexp (char *expr, int flags, int *validp)
static intmax_t subexpr (char *expr)
static intmax_t expcomma ()
static intmax_t expassign ()
static intmax_t expcond ()
static intmax_t explor ()
static intmax_t expland ()
static intmax_t expbor ()
static intmax_t expbxor ()
static intmax_t expband ()
static intmax_t exp5 ()
static intmax_t exp4 ()
static intmax_t expshift ()
static intmax_t exp3 ()
static intmax_t expmuldiv ()
static intmax_t ipow (intmax_t base, intmax_t exp)
static intmax_t exppower ()
static intmax_t exp1 ()
static intmax_t exp0 ()
static void init_lvalue (struct lvalue *lv)
static struct lvalue * alloc_lvalue ()
static void free_lvalue (struct lvalue *lv)
static intmax_t expr_streval (char *tok, int e, struct lvalue *lvalue)
static int _is_multiop (int c)
static int _is_arithop (int c)
static void readtok ()
static void evalerror (char *msg) const
static intmax_t strlong (char *num)
Variables
static char * expression
static char * tp
static char * lasttp
static int curtok
static int lasttok
static int assigntok
static char * tokstr
static intmax_t tokval
static int noeval
static procenv_t evalbuf
static int already_expanded
static struct lvalue curlval = {0, 0, 0, -1}
static struct lvalue lastlval = {0, 0, 0, -1}
static EXPR_CONTEXT ** expr_stack
static int expr_depth
static int expr_stack_size
Data Structure Documentation
lvalue
struct lvalue
Definition at line 149 of file expr.c.
Data Fields
intmax_t ind
char * tokstr
intmax_t tokval
SHELL_VAR * tokvar
EXPR_CONTEXT
struct EXPR_CONTEXT
Definition at line 158 of file expr.c.
Data Fields
int curtok
char * expression
int lasttok
char * lasttp
struct lvalue lval
int noeval
char * tokstr
intmax_t tokval
char * tp
Macro Definition Documentation
BAND
#define BAND '&' /* Bitwise AND */
Definition at line 133 of file expr.c.
BNOT
#define BNOT '~' /* Bitwise NOT; Two's complement. */
Definition at line 136 of file expr.c.
BOR
#define BOR '|' /* Bitwise OR. */
Definition at line 134 of file expr.c.
BXOR
#define BXOR '^' /* Bitwise eXclusive OR. */
Definition at line 135 of file expr.c.
COL
#define COL ':'
Definition at line 138 of file expr.c.
COMMA
#define COMMA ','
Definition at line 139 of file expr.c.
COND
#define COND 12 /* exp1 ? exp2 : exp3 */
Definition at line 116 of file expr.c.
cr_whitespace
#define cr_whitespace (c) (whitespace(c) || ((c) == '\n'))
Definition at line 93 of file expr.c.
DIV
#define DIV '/'
Definition at line 128 of file expr.c.
EQ
#define EQ '='
Definition at line 122 of file expr.c.
EQEQ
#define EQEQ 1 /* "==" */
Definition at line 105 of file expr.c.
EXP_LOWEST
#define EXP_LOWEST expcomma
Definition at line 143 of file expr.c.
EXPR_STACK_GROW_SIZE
#define EXPR_STACK_GROW_SIZE 10
Definition at line 96 of file expr.c.
GEQ
#define GEQ 4 /* ">=" */
Definition at line 108 of file expr.c.
GT
#define GT '>'
Definition at line 123 of file expr.c.
LAND
#define LAND 7 /* "&&" Logical AND */
Definition at line 111 of file expr.c.
LEQ
#define LEQ 3 /* "<=" */
Definition at line 107 of file expr.c.
LOR
#define LOR 8 /* "||" Logical OR */
Definition at line 112 of file expr.c.
LPAR
#define LPAR '('
Definition at line 131 of file expr.c.
LSH
#define LSH 9 /* "<<" Left SHift */
Definition at line 113 of file expr.c.
LT
#define LT '<'
Definition at line 124 of file expr.c.
MAX_EXPR_RECURSION_LEVEL
#define MAX_EXPR_RECURSION_LEVEL 1024
Definition at line 101 of file expr.c.
MAX_INT_LEN
#define MAX_INT_LEN 32
Definition at line 146 of file expr.c.
MINUS
#define MINUS '-'
Definition at line 126 of file expr.c.
MOD
#define MOD '%'
Definition at line 129 of file expr.c.
MUL
#define MUL '*'
Definition at line 127 of file expr.c.
NEQ
#define NEQ 2 /* "!=" */
Definition at line 106 of file expr.c.
NOT
#define NOT '!'
Definition at line 130 of file expr.c.
NUM
#define NUM 6 /* number */
Definition at line 110 of file expr.c.
OP_ASSIGN
#define OP_ASSIGN 11 /* op= expassign as in Posix.2 */
Definition at line 115 of file expr.c.
PLUS
#define PLUS '+'
Definition at line 125 of file expr.c.
POSTDEC
#define POSTDEC 17 /* var-- */
Definition at line 121 of file expr.c.
POSTINC
#define POSTINC 16 /* var++ */
Definition at line 120 of file expr.c.
POWER
#define POWER 13 /* exp1**exp2 */
Definition at line 117 of file expr.c.
PREDEC
#define PREDEC 15 /* --var */
Definition at line 119 of file expr.c.
PREINC
#define PREINC 14 /* ++var */
Definition at line 118 of file expr.c.
QUES
#define QUES '?'
Definition at line 137 of file expr.c.
RESTORETOK
#define RESTORETOK (X)
Value:
  do { \
    curtok = (X)->curtok; \
    lasttok = (X)->lasttok; \
    tp = (X)->tp; \
    lasttp = (X)->lasttp; \
    tokval = (X)->tokval; \
    tokstr = (X)->tokstr; \
    noeval = (X)->noeval; \
    curlval = (X)->lval; \
  } while (0)
Definition at line 243 of file expr.c.
RPAR
#define RPAR ')'
Definition at line 132 of file expr.c.
RSH
#define RSH 10 /* ">>" Right SHift */
Definition at line 114 of file expr.c.
SAVETOK
#define SAVETOK (X)
Value:
  do { \
    (X)->curtok = curtok; \
    (X)->lasttok = lasttok; \
    (X)->tp = tp; \
    (X)->lasttp = lasttp; \
    (X)->tokval = tokval; \
    (X)->tokstr = tokstr; \
    (X)->noeval = noeval; \
    (X)->lval = curlval; \
  } while (0)
Definition at line 231 of file expr.c.
STR
#define STR 5 /* string */
Definition at line 109 of file expr.c.
VALID_NUMCHAR
#define VALID_NUMCHAR (c) (ISALNUM(c) || ((c) == '_') || ((c) == '@'))
Definition at line 1543 of file expr.c.
Function Documentation
_is_arithop()
static int _is_arithop (int c) static
Definition at line 1276 of file expr.c.
 {
   switch (c)
     {
     case EQ:
     case GT:
     case LT:
     case PLUS:
     case MINUS:
     case MUL:
     case DIV:
     case MOD:
     case NOT:
     case LPAR:
     case RPAR:
     case BAND:
     case BOR:
     case BXOR:
     case BNOT:
       return 1;     /* operator tokens */
     case QUES:
     case COL:
     case COMMA:
       return 1;     /* questionable */
     default:
       return 0;     /* anything else is invalid */
     }
 }
References BAND, BNOT, BOR, BXOR, c, COL, COMMA, DIV, EQ, GT, LPAR, LT, MINUS, MOD, MUL, NOT, PLUS, QUES, and RPAR.
Referenced by readtok().
_is_multiop()
static int _is_multiop (int c) static
Definition at line 1249 of file expr.c.
 {
   switch (c)
     {
     case EQEQ:
     case NEQ:
     case LEQ:
     case GEQ:
     case LAND:
     case LOR:
     case LSH:
     case RSH:
     case OP_ASSIGN:
     case COND:
     case POWER:
     case PREINC:
     case PREDEC:
     case POSTINC:
     case POSTDEC:
       return 1;
     default:
       return 0;
     }
 }
References c, COND, EQEQ, GEQ, LAND, LEQ, LOR, LSH, NEQ, OP_ASSIGN, POSTDEC, POSTINC, POWER, PREDEC, PREINC, and RSH.
Referenced by readtok().
alloc_lvalue()
static struct lvalue* alloc_lvalue () static
Definition at line 1124 of file expr.c.
 {
   struct lvalue *lv;
   lv = xmalloc (sizeof (struct lvalue));
   init_lvalue (lv);
   return (lv);
 }
References init_lvalue(), and xmalloc.
evalerror()
static void evalerror (char * msg) const static
Definition at line 1518 of file expr.c.
 {
   char *name, *t;
   name = this_command_name;
   for (t = expression; t && whitespace (*t); t++)
     ;
   internal_error (_("%s%s%s: %s (error token is \"%s\")"),
            name ? name : "", name ? ": " : "",
            t ? t : "", msg, (lasttp && *lasttp) ? lasttp : "");
   sh_longjmp (evalbuf, 1);
 }
References _, evalbuf, internal_error(), lasttp, sh_longjmp, t, this_command_name, and whitespace.
Referenced by exp0(), expassign(), expcond(), expmuldiv(), exppower(), popexp(), pushexp(), readtok(), strlong(), and subexpr().
evalexp()
intmax_t evalexp (char * expr, int flags, int * validp)
Definition at line 406 of file expr.c.
 {
   intmax_t val;
   int c;
   procenv_t oevalbuf;
   val = 0;
   noeval = 0;
   already_expanded = (flags&EXP_EXPANDED);
   FASTCOPY (evalbuf, oevalbuf, sizeof (evalbuf));
   c = setjmp_nosigs (evalbuf);
   if (c)
     {
       FREE (tokstr);
       FREE (expression);
       tokstr = expression = (char *)NULL;
       expr_unwind ();
       expr_depth = 0;   /* XXX - make sure */
       /* We copy in case we've called evalexp recursively */
       FASTCOPY (oevalbuf, evalbuf, sizeof (evalbuf));
       if (validp)
     *validp = 0;
       return (0);
     }
   val = subexpr (expr);
   if (validp)
     *validp = 1;
   FASTCOPY (oevalbuf, evalbuf, sizeof (evalbuf));
   return (val);
 }
References already_expanded, c, evalbuf, EXP_EXPANDED, expr_depth, expr_unwind(), FASTCOPY, flags, FREE, noeval, NULL, procenv_t, setjmp_nosigs, subexpr(), tokstr, and val.
Referenced by arithcomp(), assign_random(), assign_seconds(), make_variable_value(), param_expand(), and verify_substring_values().
exp0()
static intmax_t exp0 () static
Definition at line 1016 of file expr.c.
 {
   register intmax_t val = 0, v2;
   char *vincdec;
   int stok;
   EXPR_CONTEXT ec;
   /* XXX - might need additional logic here to decide whether or not
        pre-increment or pre-decrement is legal at this point. */
   if (curtok == PREINC || curtok == PREDEC)
     {
       stok = lasttok = curtok;
       readtok ();
       if (curtok != STR)
     /* readtok() catches this */
     evalerror (_("identifier expected after pre-increment or pre-decrement"));
       v2 = tokval + ((stok == PREINC) ? 1 : -1);
       vincdec = itos (v2);
       if (noeval == 0)
     {
 #if defined (ARRAY_VARS)
       if (curlval.ind != -1)
         expr_bind_array_element (curlval.tokstr, curlval.ind, vincdec);
       else
 #endif
         if (tokstr)
           expr_bind_variable (tokstr, vincdec);
     }
       free (vincdec);
       val = v2;
       curtok = NUM; /* make sure --x=7 is flagged as an error */
       readtok ();
     }
   else if (curtok == LPAR)
     {
       /* XXX - save curlval here?  Or entire expression context? */
       readtok ();
       val = EXP_LOWEST ();
       if (curtok != RPAR) /* ( */
     evalerror (_("missing `)'"));
       /* Skip over closing paren. */
       readtok ();
     }
   else if ((curtok == NUM) || (curtok == STR))
     {
       val = tokval;
       if (curtok == STR)
     {
       SAVETOK (&ec);
       tokstr = (char *)NULL;    /* keep it from being freed */
           noeval = 1;
           readtok ();
           stok = curtok;
       /* post-increment or post-decrement */
       if (stok == POSTINC || stok == POSTDEC)
         {
           /* restore certain portions of EC */
           tokstr = ec.tokstr;
           noeval = ec.noeval;
           curlval = ec.lval;
           lasttok = STR;    /* ec.curtok */
           v2 = val + ((stok == POSTINC) ? 1 : -1);
           vincdec = itos (v2);
           if (noeval == 0)
         {
 #if defined (ARRAY_VARS)
           if (curlval.ind != -1)
             expr_bind_array_element (curlval.tokstr, curlval.ind, vincdec);
           else
 #endif
             expr_bind_variable (tokstr, vincdec);
         }
           free (vincdec);
           curtok = NUM; /* make sure x++=7 is flagged as an error */
         }
       else
         {
           /* XXX - watch out for pointer aliasing issues here */
           if (stok == STR)  /* free new tokstr before old one is restored */
         FREE (tokstr);
           RESTORETOK (&ec);
         }
     }
       readtok ();
     }
   else
     evalerror (_("syntax error: operand expected"));
   return (val);
 }
References _, curlval, curtok, evalerror(), EXP_LOWEST, expr_bind_variable(), FREE, free, lvalue::ind, itos(), lasttok, LPAR, EXPR_CONTEXT::lval, EXPR_CONTEXT::noeval, noeval, NULL, NUM, POSTDEC, POSTINC, PREDEC, PREINC, readtok(), RESTORETOK, RPAR, SAVETOK, STR, lvalue::tokstr, EXPR_CONTEXT::tokstr, tokstr, tokval, v2, and val.
Referenced by exp1().
exp1()
static intmax_t exp1 () static
Definition at line 981 of file expr.c.
 {
   register intmax_t val;
   if (curtok == NOT)
     {
       readtok ();
       val = !exp1 ();
       lasttok = NUM;
     }
   else if (curtok == BNOT)
     {
       readtok ();
       val = ~exp1 ();
       lasttok = NUM;
     }
   else if (curtok == MINUS)
     {
       readtok ();
       val = - exp1 ();
       lasttok = NUM;
     }
   else if (curtok == PLUS)
     {
       readtok ();
       val = exp1 ();
       lasttok = NUM;
     }
   else
     val = exp0 ();
   return (val);
 }
References BNOT, curtok, exp0(), lasttok, MINUS, NOT, NUM, PLUS, readtok(), and val.
Referenced by exppower().
exp3()
static intmax_t exp3 () static
Definition at line 860 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = expmuldiv ();
   while ((curtok == PLUS) || (curtok == MINUS))
     {
       int op = curtok;
       readtok ();
       val2 = expmuldiv ();
       if (op == PLUS)
     val1 += val2;
       else if (op == MINUS)
     val1 -= val2;
       lasttok = NUM;
     }
   return (val1);
 }
References curtok, expmuldiv(), lasttok, MINUS, NUM, PLUS, and readtok().
Referenced by expshift().
exp4()
static intmax_t exp4 () static
Definition at line 806 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = expshift ();
   while ((curtok == LEQ) ||
      (curtok == GEQ) ||
      (curtok == LT) ||
      (curtok == GT))
     {
       int op = curtok;
       readtok ();
       val2 = expshift ();
       if (op == LEQ)
     val1 = val1 <= val2;
       else if (op == GEQ)
     val1 = val1 >= val2;
       else if (op == LT)
     val1 = val1 < val2;
       else          /* (op == GT) */
     val1 = val1 > val2;
       lasttok = NUM;
     }
   return (val1);
 }
References curtok, expshift(), GEQ, GT, lasttok, LEQ, LT, NUM, and readtok().
Referenced by exp5().
exp5()
static intmax_t exp5 () static
Definition at line 784 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = exp4 ();
   while ((curtok == EQEQ) || (curtok == NEQ))
     {
       int op = curtok;
       readtok ();
       val2 = exp4 ();
       if (op == EQEQ)
     val1 = (val1 == val2);
       else if (op == NEQ)
     val1 = (val1 != val2);
       lasttok = NUM;
     }
   return (val1);
 }
References curtok, EQEQ, exp4(), lasttok, NEQ, NUM, and readtok().
Referenced by expband().
expassign()
static intmax_t expassign () static
Definition at line 505 of file expr.c.
 {
   register intmax_t value;
   char *lhs, *rhs;
   arrayind_t lind;
 #if defined (HAVE_IMAXDIV)
   imaxdiv_t idiv;
 #endif
   value = expcond ();
   if (curtok == EQ || curtok == OP_ASSIGN)
     {
       int special, op;
       intmax_t lvalue;
       special = curtok == OP_ASSIGN;
       if (lasttok != STR)
     evalerror (_("attempted assignment to non-variable"));
       if (special)
     {
       op = assigntok;       /* a OP= b */
       lvalue = value;
     }
       if (tokstr == 0)
     evalerror (_("syntax error in variable assignment"));
       /* XXX - watch out for pointer aliasing issues here */
       lhs = savestring (tokstr);
       /* save ind in case rhs is string var and evaluation overwrites it */
       lind = curlval.ind;
       readtok ();
       value = expassign ();
       if (special)
     {
       if ((op == DIV || op == MOD) && value == 0)
         {
           if (noeval == 0)
         evalerror (_("division by 0"));
           else
             value = 1;
         }
       switch (op)
         {
         case MUL:
           /* Handle INTMAX_MIN and INTMAX_MAX * -1 specially here? */
           lvalue *= value;
           break;
         case DIV:
         case MOD:
           if (lvalue == INTMAX_MIN && value == -1)
         lvalue = (op == DIV) ? INTMAX_MIN : 0;
           else
 #if HAVE_IMAXDIV
         {
           idiv = imaxdiv (lvalue, value);
           lvalue = (op == DIV) ? idiv.quot : idiv.rem;
         }
 #else
             lvalue = (op == DIV) ? lvalue / value : lvalue % value;
 #endif
           break;
         case PLUS:
           lvalue += value;
           break;
         case MINUS:
           lvalue -= value;
           break;
         case LSH:
           lvalue <<= value;
           break;
         case RSH:
           lvalue >>= value;
           break;
         case BAND:
           lvalue &= value;
           break;
         case BOR:
           lvalue |= value;
           break;
         case BXOR:
           lvalue ^= value;
           break;
         default:
           free (lhs);
           evalerror (_("bug: bad expassign token"));
           break;
         }
       value = lvalue;
     }
       rhs = itos (value);
       if (noeval == 0)
     {
 #if defined (ARRAY_VARS)
       if (lind != -1)
         expr_bind_array_element (lhs, lind, rhs);
       else
 #endif
         expr_bind_variable (lhs, rhs);
     }
       if (curlval.tokstr && curlval.tokstr == tokstr)
     init_lvalue (&curlval);
       free (rhs);
       free (lhs);
       FREE (tokstr);
       tokstr = (char *)NULL;        /* For freeing on errors. */
     }
   return (value);
 }
References _, assigntok, BAND, BOR, BXOR, curlval, curtok, DIV, EQ, evalerror(), expcond(), expr_bind_variable(), FREE, free, imaxdiv(), lvalue::ind, init_lvalue(), INTMAX_MIN, itos(), lasttok, lind, LSH, MINUS, MOD, MUL, noeval, NULL, OP_ASSIGN, PLUS, imaxdiv_t::quot, readtok(), imaxdiv_t::rem, RSH, savestring(), STR, lvalue::tokstr, tokstr, and value.
Referenced by expcomma().
expband()
static intmax_t expband () static
Definition at line 766 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = exp5 ();
   while (curtok == BAND)
     {
       readtok ();
       val2 = exp5 ();
       val1 = val1 & val2;
       lasttok = NUM;
     }
   return (val1);
 }
References BAND, curtok, exp5(), lasttok, NUM, and readtok().
Referenced by expbxor().
expbor()
static intmax_t expbor () static
Definition at line 728 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = expbxor ();
   while (curtok == BOR)
     {
       readtok ();
       val2 = expbxor ();
       val1 = val1 | val2;
       lasttok = NUM;
     }
   return (val1);
 }
References BOR, curtok, expbxor(), lasttok, NUM, and readtok().
Referenced by expland().
expbxor()
static intmax_t expbxor () static
Definition at line 747 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = expband ();
   while (curtok == BXOR)
     {
       readtok ();
       val2 = expband ();
       val1 = val1 ^ val2;
       lasttok = NUM;
     }
   return (val1);
 }
References BXOR, curtok, expband(), lasttok, NUM, and readtok().
Referenced by expbor().
expcomma()
static intmax_t expcomma () static
Definition at line 490 of file expr.c.
 {
   register intmax_t value;
   value = expassign ();
   while (curtok == COMMA)
     {
       readtok ();
       value = expassign ();
     }
   return value;
 }
References COMMA, curtok, expassign(), readtok(), and value.
expcond()
static intmax_t expcond () static
Definition at line 624 of file expr.c.
 {
   intmax_t cval, val1, val2, rval;
   int set_noeval;
   set_noeval = 0;
   rval = cval = explor ();
   if (curtok == QUES)       /* found conditional expr */
     {
       if (cval == 0)
     {
       set_noeval = 1;
       noeval++;
     }
       readtok ();
       if (curtok == 0 || curtok == COL)
     evalerror (_("expression expected"));
       val1 = EXP_LOWEST ();
       if (set_noeval)
     noeval--;
       if (curtok != COL)
     evalerror (_("`:' expected for conditional expression"));
       set_noeval = 0;
       if (cval)
     {
       set_noeval = 1;
       noeval++;
     }
       readtok ();
       if (curtok == 0)
     evalerror (_("expression expected"));
       val2 = expcond ();
       if (set_noeval)
     noeval--;
       rval = cval ? val1 : val2;
       lasttok = COND;
     }
   return rval;
 }
References _, COL, COND, curtok, cval, evalerror(), EXP_LOWEST, explor(), lasttok, noeval, QUES, and readtok().
Referenced by expassign().
expland()
static intmax_t expland () static
Definition at line 700 of file expr.c.
 {
   register intmax_t val1, val2;
   int set_noeval;
   val1 = expbor ();
   while (curtok == LAND)
     {
       set_noeval = 0;
       if (val1 == 0)
     {
       set_noeval = 1;
       noeval++;
     }
       readtok ();
       val2 = expbor ();
       if (set_noeval)
     noeval--;
       val1 = val1 && val2;
       lasttok = LAND;
     }
   return (val1);
 }
References curtok, expbor(), LAND, lasttok, noeval, and readtok().
Referenced by explor().
explor()
static intmax_t explor () static
Definition at line 672 of file expr.c.
 {
   register intmax_t val1, val2;
   int set_noeval;
   val1 = expland ();
   while (curtok == LOR)
     {
       set_noeval = 0;
       if (val1 != 0)
     {
       noeval++;
       set_noeval = 1;
     }
       readtok ();
       val2 = expland ();
       if (set_noeval)
     noeval--;
       val1 = val1 || val2;
       lasttok = LOR;
     }
   return (val1);
 }
References curtok, expland(), lasttok, LOR, noeval, and readtok().
Referenced by expcond().
expmuldiv()
static intmax_t expmuldiv () static
Definition at line 883 of file expr.c.
 {
   register intmax_t val1, val2;
 #if defined (HAVE_IMAXDIV)
   imaxdiv_t idiv;
 #endif
   val1 = exppower ();
   while ((curtok == MUL) ||
      (curtok == DIV) ||
      (curtok == MOD))
     {
       int op = curtok;
       char *stp, *sltp;
       stp = tp;
       readtok ();
       val2 = exppower ();
       /* Handle division by 0 and twos-complement arithmetic overflow */
       if (((op == DIV) || (op == MOD)) && (val2 == 0))
     {
       if (noeval == 0)
         {
           sltp = lasttp;
           lasttp = stp;
           while (lasttp && *lasttp && whitespace (*lasttp))
         lasttp++;
           evalerror (_("division by 0"));
           lasttp = sltp;
         }
       else
         val2 = 1;
     }
       else if (op == MOD && val1 == INTMAX_MIN && val2 == -1)
     {
       val1 = 0;
       continue;
     }
       else if (op == DIV && val1 == INTMAX_MIN && val2 == -1)
     val2 = 1;
       if (op == MUL)
     val1 *= val2;
       else if (op == DIV || op == MOD)
 #if defined (HAVE_IMAXDIV)
     {
       idiv = imaxdiv (val1, val2);
       val1 = (op == DIV) ? idiv.quot : idiv.rem;
     }
 #else
     val1 = (op == DIV) ? val1 / val2 : val1 % val2;
 #endif
       lasttok = NUM;
     }
   return (val1);
 }
References _, curtok, DIV, evalerror(), exppower(), imaxdiv(), INTMAX_MIN, lasttok, lasttp, MOD, MUL, noeval, NUM, imaxdiv_t::quot, readtok(), imaxdiv_t::rem, tp, and whitespace.
Referenced by exp3().
exppower()
static intmax_t exppower () static
Definition at line 961 of file expr.c.
 {
   register intmax_t val1, val2, c;
   val1 = exp1 ();
   while (curtok == POWER)
     {
       readtok ();
       val2 = exppower ();   /* exponentiation is right-associative */
       lasttok = NUM;
       if (val2 == 0)
     return (1);
       if (val2 < 0)
     evalerror (_("exponent less than 0"));
       val1 = ipow (val1, val2);
     }
   return (val1);
 }
References _, c, curtok, evalerror(), exp1(), ipow(), lasttok, NUM, POWER, and readtok().
Referenced by expmuldiv().
expr_bind_variable()
static void expr_bind_variable (char * lhs, char * rhs) static
Definition at line 322 of file expr.c.
 {
   SHELL_VAR *v;
   int aflags;
   if (lhs == 0 || *lhs == 0)
     return;     /* XXX */
 #if defined (ARRAY_VARS)
   aflags = (assoc_expand_once && already_expanded) ? ASS_NOEXPAND : 0;
   aflags |= ASS_ALLOWALLSUB;        /* allow assoc[@]=value */
 #else
   aflags = 0;
 #endif
   v = bind_int_variable (lhs, rhs, aflags);
   if (v && (readonly_p (v) || noassign_p (v)))
     sh_longjmp (evalbuf, 1);    /* variable assignment error */
   stupidly_hack_special_variables (lhs);
 }
References already_expanded, ASS_ALLOWALLSUB, ASS_NOEXPAND, bind_int_variable(), evalbuf, noassign_p, readonly_p, sh_longjmp, and stupidly_hack_special_variables().
Referenced by exp0(), and expassign().
expr_streval()
static intmax_t expr_streval (char * tok, int e, struct lvalue * lvalue) static
Definition at line 1141 of file expr.c.
 {
   SHELL_VAR *v;
   char *value;
   intmax_t tval;
   int initial_depth;
 #if defined (ARRAY_VARS)
   arrayind_t ind;
   int tflag, aflag;
   array_eltstate_t es;
 #endif
 /*itrace("expr_streval: %s: noeval = %d expanded=%d", tok, noeval, already_expanded);*/
   /* If we are suppressing evaluation, just short-circuit here instead of
      going through the rest of the evaluator. */
   if (noeval)
     return (0);
   initial_depth = expr_depth;
 #if defined (ARRAY_VARS)
   tflag = (assoc_expand_once && already_expanded) ? AV_NOEXPAND : 0;    /* for a start */
 #endif
   /* [[[[[ */
 #if defined (ARRAY_VARS)
   aflag = tflag;    /* use a different variable for now */
   if (shell_compatibility_level > 51)
     aflag |= AV_ATSTARKEYS;
   v = (e == ']') ? array_variable_part (tok, tflag, (char **)0, (int *)0) : find_variable (tok);
 #else
   v = find_variable (tok);
 #endif
   if (v == 0 && e != ']')
     v = find_variable_last_nameref (tok, 0);
   if ((v == 0 || invisible_p (v)) && unbound_vars_is_error)
     {
 #if defined (ARRAY_VARS)
       value = (e == ']') ? array_variable_name (tok, tflag, (char **)0, (int *)0) : tok;
 #else
       value = tok;
 #endif
       set_exit_status (EXECUTION_FAILURE);
       err_unboundvar (value);
 #if defined (ARRAY_VARS)
       if (e == ']')
     FREE (value);   /* array_variable_name returns new memory */
 #endif
       if (no_longjmp_on_fatal_error && interactive_shell)
     sh_longjmp (evalbuf, 1);
       if (interactive_shell)
     {
       expr_unwind ();
       top_level_cleanup ();
       jump_to_top_level (DISCARD);
     }
       else
     jump_to_top_level (FORCE_EOF);
     }
 #if defined (ARRAY_VARS)
   init_eltstate (&es);
   es.ind = -1;
   /* If the second argument to get_array_value doesn't include AV_ALLOWALL,
      we don't allow references like array[@].  In this case, get_array_value
      is just like get_variable_value in that it does not return newly-allocated
      memory or quote the results.  AFLAG is set above and is either AV_NOEXPAND
      or 0. */
   value = (e == ']') ? get_array_value (tok, aflag, &es) : get_variable_value (v);
   ind = es.ind;
   flush_eltstate (&es);
 #else
   value = get_variable_value (v);
 #endif
   if (expr_depth < initial_depth)
     {
       if (no_longjmp_on_fatal_error && interactive_shell)
     sh_longjmp (evalbuf, 1);
       return (0);
     }
   tval = (value && *value) ? subexpr (value) : 0;
   if (lvalue)
     {
       lvalue->tokstr = tok; /* XXX */
       lvalue->tokval = tval;
       lvalue->tokvar = v;   /* XXX */
 #if defined (ARRAY_VARS)
       lvalue->ind = ind;
 #else
       lvalue->ind = -1;
 #endif
     }
   return (tval);
 }
References aflag, already_expanded, AV_ATSTARKEYS, AV_NOEXPAND, DISCARD, err_unboundvar(), evalbuf, EXECUTION_FAILURE, expr_depth, expr_unwind(), find_variable(), find_variable_last_nameref(), FORCE_EOF, FREE, get_variable_value(), element_state::ind, lvalue::ind, interactive_shell, invisible_p, jump_to_top_level(), no_longjmp_on_fatal_error, noeval, set_exit_status(), sh_longjmp, shell_compatibility_level, subexpr(), lvalue::tokstr, lvalue::tokval, lvalue::tokvar, top_level_cleanup(), unbound_vars_is_error, and value.
Referenced by readtok().
expr_unwind()
static void expr_unwind () static
Definition at line 303 of file expr.c.
 {
   while (--expr_depth > 0)
     {
       if (expr_stack[expr_depth]->tokstr)
     free (expr_stack[expr_depth]->tokstr);
       if (expr_stack[expr_depth]->expression)
     free (expr_stack[expr_depth]->expression);
       free (expr_stack[expr_depth]);
     }
   if (expr_depth == 0)
     free (expr_stack[expr_depth]);  /* free the allocated EXPR_CONTEXT */
   noeval = 0;   /* XXX */
 }
References expr_depth, expr_stack, free, noeval, and tokstr.
Referenced by evalexp(), and expr_streval().
expshift()
static intmax_t expshift () static
Definition at line 836 of file expr.c.
 {
   register intmax_t val1, val2;
   val1 = exp3 ();
   while ((curtok == LSH) || (curtok == RSH))
     {
       int op = curtok;
       readtok ();
       val2 = exp3 ();
       if (op == LSH)
     val1 = val1 << val2;
       else
     val1 = val1 >> val2;
       lasttok = NUM;
     }
   return (val1);
 }
References curtok, exp3(), lasttok, LSH, NUM, readtok(), and RSH.
Referenced by exp4().
free_lvalue()
static void free_lvalue (struct lvalue * lv) static
Definition at line 1134 of file expr.c.
 {
   free (lv);        /* should be inlined */
 }
References free.
init_lvalue()
static void init_lvalue (struct lvalue * lv) static
Definition at line 1115 of file expr.c.
 {
   lv->tokstr = 0;
   lv->tokvar = 0;
   lv->tokval = lv->ind = -1;
 }
References lvalue::ind, lvalue::tokstr, lvalue::tokval, and lvalue::tokvar.
Referenced by alloc_lvalue(), expassign(), readtok(), and subexpr().
ipow()
static intmax_t ipow (intmax_t base, intmax_t exp) static
Definition at line 944 of file expr.c.
 {
   intmax_t result;
   result = 1;
   while (exp)
     {
       if (exp & 1)
     result *= base;
       exp >>= 1;
       base *= base;
     }
   return result;
 }
References base, and exp.
Referenced by exppower().
PARAMS() [1/7]
static intmax_t strlong PARAMS ((char *)) static
PARAMS() [2/7]
static void expr_bind_variable PARAMS ((char *, char *)) static
PARAMS() [3/7]
static intmax_t expr_streval PARAMS ((char *, int, struct lvalue *)) static
PARAMS() [4/7]
static void evalerror PARAMS ((const char *)) static
PARAMS() [5/7]
static int _is_arithop PARAMS ((int)) static
PARAMS() [6/7]
static void init_lvalue PARAMS ((struct lvalue *)) static
PARAMS() [7/7]
static void readtok PARAMS ((void)) static
popexp()
static void popexp () static
Definition at line 282 of file expr.c.
 {
   EXPR_CONTEXT *context;
   if (expr_depth <= 0)
     {
       /* See the comment at the top of evalexp() for an explanation of why
      this is done. */
       expression = lasttp = 0;
       evalerror (_("recursion stack underflow"));
     }
   context = expr_stack[--expr_depth];
   expression = context->expression;
   RESTORETOK (context);
   free (context);
 }
References _, context, evalerror(), expr_depth, expr_stack, free, lasttp, and RESTORETOK.
Referenced by subexpr().
pushexp()
static void pushexp () static
Definition at line 258 of file expr.c.
 {
   EXPR_CONTEXT *context;
   if (expr_depth >= MAX_EXPR_RECURSION_LEVEL)
     evalerror (_("expression recursion level exceeded"));
   if (expr_depth >= expr_stack_size)
     {
       expr_stack_size += EXPR_STACK_GROW_SIZE;
       expr_stack = (EXPR_CONTEXT **)xrealloc (expr_stack, expr_stack_size * sizeof (EXPR_CONTEXT *));
     }
   context = (EXPR_CONTEXT *)xmalloc (sizeof (EXPR_CONTEXT));
   context->expression = expression;
   SAVETOK(context);
   expr_stack[expr_depth++] = context;
 }
References _, context, evalerror(), expr_depth, expr_stack, EXPR_STACK_GROW_SIZE, expr_stack_size, expression, MAX_EXPR_RECURSION_LEVEL, SAVETOK, xmalloc, and xrealloc.
Referenced by subexpr().
readtok()
static void readtok () static
Definition at line 1311 of file expr.c.
 {
   register char *cp, *xp;
   register unsigned char c, c1;
   register int e;
   struct lvalue lval;
   /* Skip leading whitespace. */
   cp = tp;
   c = e = 0;
   while (cp && (c = *cp) && (cr_whitespace (c)))
     cp++;
   if (c)
     cp++;
   if (c == '\0')
     {
       lasttok = curtok;
       curtok = 0;
       tp = cp;
       return;
     }
   lasttp = tp = cp - 1;
   if (legal_variable_starter (c))
     {
       /* variable names not preceded with a dollar sign are shell variables. */
       char *savecp;
       EXPR_CONTEXT ec;
       int peektok;
       while (legal_variable_char (c))
     c = *cp++;
       c = *--cp;
 #if defined (ARRAY_VARS)
       if (c == '[')
     {
       e = expr_skipsubscript (tp, cp);      /* XXX - was skipsubscript */
       if (cp[e] == ']')
         {
           cp += e + 1;
           c = *cp;
           e = ']';
         }
       else
         evalerror (bash_badsub_errmsg);
     }
 #endif /* ARRAY_VARS */
       *cp = '\0';
       /* XXX - watch out for pointer aliasing issues here */
       if (curlval.tokstr && curlval.tokstr == tokstr)
     init_lvalue (&curlval);
       FREE (tokstr);
       tokstr = savestring (tp);
       *cp = c;
       /* XXX - make peektok part of saved token state? */
       SAVETOK (&ec);
       tokstr = (char *)NULL;    /* keep it from being freed */
       tp = savecp = cp;
       noeval = 1;
       curtok = STR;
       readtok ();
       peektok = curtok;
       if (peektok == STR)   /* free new tokstr before old one is restored */
     FREE (tokstr);
       RESTORETOK (&ec);
       cp = savecp;
       /* The tests for PREINC and PREDEC aren't strictly correct, but they
      preserve old behavior if a construct like --x=9 is given. */
       if (lasttok == PREINC || lasttok == PREDEC || peektok != EQ)
         {
           lastlval = curlval;
       tokval = expr_streval (tokstr, e, &curlval);
         }
       else
     tokval = 0;
       lasttok = curtok;
       curtok = STR;
     }
   else if (DIGIT(c))
     {
       while (ISALNUM (c) || c == '#' || c == '@' || c == '_')
     c = *cp++;
       c = *--cp;
       *cp = '\0';
       tokval = strlong (tp);
       *cp = c;
       lasttok = curtok;
       curtok = NUM;
     }
   else
     {
       c1 = *cp++;
       if ((c == EQ) && (c1 == EQ))
     c = EQEQ;
       else if ((c == NOT) && (c1 == EQ))
     c = NEQ;
       else if ((c == GT) && (c1 == EQ))
     c = GEQ;
       else if ((c == LT) && (c1 == EQ))
     c = LEQ;
       else if ((c == LT) && (c1 == LT))
     {
       if (*cp == '=')   /* a <<= b */
         {
           assigntok = LSH;
           c = OP_ASSIGN;
           cp++;
         }
       else
         c = LSH;
     }
       else if ((c == GT) && (c1 == GT))
     {
       if (*cp == '=')
         {
           assigntok = RSH;  /* a >>= b */
           c = OP_ASSIGN;
           cp++;
         }
       else
         c = RSH;
     }
       else if ((c == BAND) && (c1 == BAND))
     c = LAND;
       else if ((c == BOR) && (c1 == BOR))
     c = LOR;
       else if ((c == '*') && (c1 == '*'))
     c = POWER;
       else if ((c == '-' || c == '+') && c1 == c && curtok == STR)
     c = (c == '-') ? POSTDEC : POSTINC;
 #if STRICT_ARITH_PARSING
       else if ((c == '-' || c == '+') && c1 == c && curtok == NUM)
 #else
       else if ((c == '-' || c == '+') && c1 == c && curtok == NUM && (lasttok == PREINC || lasttok == PREDEC))
 #endif
     {
       /* This catches something like --FOO++ */
       /* TAG:bash-5.3 add gettext calls here or make this a separate function */
       if (c == '-')
         evalerror ("--: assignment requires lvalue");
       else
         evalerror ("++: assignment requires lvalue");
     }
       else if ((c == '-' || c == '+') && c1 == c)
     {
       /* Quickly scan forward to see if this is followed by optional
          whitespace and an identifier. */
       xp = cp;
       while (xp && *xp && cr_whitespace (*xp))
         xp++;
       if (legal_variable_starter ((unsigned char)*xp))
         c = (c == '-') ? PREDEC : PREINC;
       else
         /* Could force parsing as preinc or predec and throw an error */
 #if STRICT_ARITH_PARSING
         {
           /* Posix says unary plus and minus have higher priority than
          preinc and predec. */
           /* This catches something like --4++ */
           if (c == '-')
         evalerror ("--: assignment requires lvalue");
           else
         evalerror ("++: assignment requires lvalue");
         }
 #else
         cp--;   /* not preinc or predec, so unget the character */
 #endif
     }
       else if (c1 == EQ && member (c, "*/%+-&^|"))
     {
       assigntok = c;    /* a OP= b */
       c = OP_ASSIGN;
     }
       else if (_is_arithop (c) == 0)
     {
       cp--;
       /* use curtok, since it hasn't been copied to lasttok yet */
       if (curtok == 0 || _is_arithop (curtok) || _is_multiop (curtok))
         evalerror (_("syntax error: operand expected"));
       else
         evalerror (_("syntax error: invalid arithmetic operator"));
     }
       else
     cp--;           /* `unget' the character */
       /* Should check here to make sure that the current character is one
      of the recognized operators and flag an error if not.  Could create
      a character map the first time through and check it on subsequent
      calls. */
       lasttok = curtok;
       curtok = c;
     }
   tp = cp;
 }
References _, _is_arithop(), _is_multiop(), assigntok, BAND, BOR, c, cr_whitespace, curlval, curtok, DIGIT, EQ, EQEQ, evalerror(), expr_streval(), FREE, GEQ, GT, init_lvalue(), ISALNUM, LAND, lastlval, lasttok, lasttp, legal_variable_char, legal_variable_starter, LEQ, LOR, LSH, LT, member, NEQ, noeval, NOT, NULL, NUM, OP_ASSIGN, POSTDEC, POSTINC, POWER, PREDEC, PREINC, RESTORETOK, RSH, savestring(), SAVETOK, STR, strlong(), lvalue::tokstr, tokstr, tokval, and tp.
Referenced by exp0(), exp1(), exp3(), exp4(), exp5(), expassign(), expband(), expbor(), expbxor(), expcomma(), expcond(), expland(), explor(), expmuldiv(), exppower(), expshift(), and subexpr().
strlong()
static intmax_t strlong (char * num) static
Definition at line 1546 of file expr.c.
 {
   register char *s;
   register unsigned char c;
   int base, foundbase;
   intmax_t val, pval;
   s = num;
   base = 10;
   foundbase = 0;
   if (*s == '0')
     {
       s++;
       if (*s == '\0')
     return 0;
        /* Base 16? */
       if (*s == 'x' || *s == 'X')
     {
       base = 16;
       s++;
 #if STRICT_ARITH_PARSING
       if (*s == 0)
         evalerror (_("invalid number"));
 #endif
     }
       else
     base = 8;
       foundbase++;
     }
   val = 0;
   for (c = *s++; c; c = *s++)
     {
       if (c == '#')
     {
       if (foundbase)
         evalerror (_("invalid number"));
       /* Illegal base specifications raise an evaluation error. */
       if (val < 2 || val > 64)
         evalerror (_("invalid arithmetic base"));
       base = val;
       val = 0;
       foundbase++;
       /* Make sure a base# is followed by a character that can compose a
          valid integer constant. Jeremy Townshend <jeremy.townshend@gmail.com> */
       if (VALID_NUMCHAR (*s) == 0)
         evalerror (_("invalid integer constant"));
     }
       else if (VALID_NUMCHAR (c))
     {
       if (DIGIT(c))
         c = TODIGIT(c);
       else if (c >= 'a' && c <= 'z')
         c -= 'a' - 10;
       else if (c >= 'A' && c <= 'Z')
         c -= 'A' - ((base <= 36) ? 10 : 36);
       else if (c == '@')
         c = 62;
       else if (c == '_')
         c = 63;
       if (c >= base)
         evalerror (_("value too great for base"));
 #ifdef CHECK_OVERFLOW
       pval = val;
       val = (val * base) + c;
       if (val < 0 || val < pval)    /* overflow */
         return INTMAX_MAX;
 #else
       val = (val * base) + c;
 #endif
     }
       else
     break;
     }
   return (val);
 }
References _, base, c, DIGIT, evalerror(), INTMAX_MAX, num, s, TODIGIT, val, and VALID_NUMCHAR.
Referenced by readtok().
subexpr()
static intmax_t subexpr (char * expr) static
Definition at line 451 of file expr.c.
 {
   intmax_t val;
   char *p;
   for (p = expr; p && *p && cr_whitespace (*p); p++)
     ;
   if (p == NULL || *p == '\0')
     return (0);
   pushexp ();
   expression = savestring (expr);
   tp = expression;
   curtok = lasttok = 0;
   tokstr = (char *)NULL;
   tokval = 0;
   init_lvalue (&curlval);
   lastlval = curlval;
   readtok ();
   val = EXP_LOWEST ();
   /*TAG:bash-5.3 make it clear that these are arithmetic syntax errors */
   if (curtok != 0)
     evalerror (_("syntax error in expression"));
   FREE (tokstr);
   FREE (expression);
   popexp ();
   return val;
 }
References _, cr_whitespace, curlval, curtok, evalerror(), EXP_LOWEST, expression, FREE, init_lvalue(), lastlval, lasttok, NULL, p, popexp(), pushexp(), readtok(), savestring(), tokstr, tokval, tp, and val.
Referenced by evalexp(), and expr_streval().
Variable Documentation
already_expanded
int already_expanded static
Definition at line 179 of file expr.c.
Referenced by evalexp(), expr_bind_variable(), and expr_streval().
assigntok
int assigntok static
Definition at line 172 of file expr.c.
Referenced by expassign(), and readtok().
curlval
struct lvalue curlval = {0, 0, 0, -1} static
Definition at line 179 of file expr.c.
Referenced by exp0(), expassign(), readtok(), and subexpr().
curtok
int curtok static
Definition at line 170 of file expr.c.
Referenced by exp0(), exp1(), exp3(), exp4(), exp5(), expassign(), expband(), expbor(), expbxor(), expcomma(), expcond(), expland(), explor(), expmuldiv(), exppower(), expshift(), readtok(), and subexpr().
evalbuf
procenv_t evalbuf static
Definition at line 176 of file expr.c.
Referenced by evalerror(), evalexp(), expr_bind_variable(), and expr_streval().
expr_depth
int expr_depth static
Definition at line 224 of file expr.c.
Referenced by evalexp(), expr_streval(), expr_unwind(), popexp(), and pushexp().
expr_stack
EXPR_CONTEXT** expr_stack static
Definition at line 223 of file expr.c.
Referenced by expr_unwind(), popexp(), and pushexp().
expr_stack_size
int expr_stack_size static
Definition at line 225 of file expr.c.
Referenced by pushexp().
expression
char* expression static
Definition at line 167 of file expr.c.
Referenced by pushexp(), and subexpr().
lastlval
struct lvalue lastlval = {0, 0, 0, -1} static
Definition at line 179 of file expr.c.
Referenced by readtok(), and subexpr().
lasttok
int lasttok static
Definition at line 171 of file expr.c.
Referenced by evaluate_string(), exp0(), exp1(), exp3(), exp4(), exp5(), expassign(), expband(), expbor(), expbxor(), expcond(), expland(), explor(), expmuldiv(), exppower(), expshift(), readtok(), and subexpr().
lasttp
char* lasttp static
Definition at line 169 of file expr.c.
Referenced by evalerror(), expmuldiv(), popexp(), and readtok().
noeval
int noeval static
Definition at line 175 of file expr.c.
Referenced by evalexp(), exp0(), expassign(), expcond(), expland(), explor(), expmuldiv(), expr_streval(), expr_unwind(), and readtok().
tokstr
char* tokstr static
Definition at line 173 of file expr.c.
Referenced by evalexp(), exp0(), expassign(), expr_unwind(), find_reserved_word(), readtok(), special_case_tokens(), and subexpr().
tokval
intmax_t tokval static
Definition at line 174 of file expr.c.
Referenced by exp0(), readtok(), and subexpr().
tp
char* tp static
Definition at line 168 of file expr.c.
Referenced by __ftime32(), __get_tp(), add_cmd(), bb_unsetenv(), clear_traps(), copy_file(), expmuldiv(), ftime(), mktime(), my_localtime_r(), procps_scan(), readtok(), refresh(), separate_out_assignments(), strftime_fmt(), strftime_HHMMSS(), strftime_YYYYMMDDHHMMSS(), subexpr(), sync_cursor(), sysctl_handle_preload_file(), tcsetattr_stdin_TCSANOW(), and ydhms_tm_diff().