Fennix: Driver::Driver Class Reference
Driver::Driver Class Reference
#include <driver.hpp>
Public Member Functions
std::vector< DriverFile > GetDrivers ()
void Panic ()
void UnloadAllDrivers ()
bool UnloadDriver (unsigned long DUID)
int IOCB (unsigned long DUID, void *KCB)
DriverCode LoadDriver (uintptr_t DriverAddress, size_t Size)
DriverCode StartDrivers ()
Driver ()
~Driver ()
Private Member Functions
DriverCode CallDriverEntryPoint (void *fex, void *KAPIAddress)
void MapPCIAddresses (PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCIGeneric (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCIDisplay (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCINetwork (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCIStorage (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCIFileSystem (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCIInput (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode BindPCIAudio (Memory::MemMgr *mem, void *fex, PCI::PCIDeviceHeader *PCIDevice)
DriverCode DriverLoadBindPCI (void *DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf=false)
DriverCode BindInterruptGeneric (Memory::MemMgr *mem, void *fex)
DriverCode BindInterruptDisplay (Memory::MemMgr *mem, void *fex)
DriverCode BindInterruptNetwork (Memory::MemMgr *mem, void *fex)
DriverCode BindInterruptStorage (Memory::MemMgr *mem, void *fex)
DriverCode BindInterruptFileSystem (Memory::MemMgr *mem, void *fex)
DriverCode BindInterruptInput (Memory::MemMgr *mem, void *fex)
DriverCode BindInterruptAudio (Memory::MemMgr *mem, void *fex)
DriverCode DriverLoadBindInterrupt (void *DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf=false)
DriverCode BindInputGeneric (Memory::MemMgr *mem, void *fex)
DriverCode BindInputDisplay (Memory::MemMgr *mem, void *fex)
DriverCode BindInputNetwork (Memory::MemMgr *mem, void *fex)
DriverCode BindInputStorage (Memory::MemMgr *mem, void *fex)
DriverCode BindInputFileSystem (Memory::MemMgr *mem, void *fex)
DriverCode BindInputInput (Memory::MemMgr *mem, void *fex)
DriverCode BindInputAudio (Memory::MemMgr *mem, void *fex)
DriverCode DriverLoadBindInput (void *DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf=false)
DriverCode BindProcessGeneric (Memory::MemMgr *mem, void *fex)
DriverCode BindProcessDisplay (Memory::MemMgr *mem, void *fex)
DriverCode BindProcessNetwork (Memory::MemMgr *mem, void *fex)
DriverCode BindProcessStorage (Memory::MemMgr *mem, void *fex)
DriverCode BindProcessFileSystem (Memory::MemMgr *mem, void *fex)
DriverCode BindProcessInput (Memory::MemMgr *mem, void *fex)
DriverCode BindProcessAudio (Memory::MemMgr *mem, void *fex)
DriverCode DriverLoadBindProcess (void *DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf=false)
Private Attributes
std::vector< DriverFile > Drivers
unsigned long DriverUIDs = 0
Detailed Description
Definition at line 85 of file driver.hpp.
Constructor & Destructor Documentation
Driver()
Driver::Driver::Driver ()
Definition at line 214 of file Driver.cpp.
     {
         SmartCriticalSection(DriverInitLock);
         std::string DriverConfigFile = Config.DriverDirectory;
         DriverConfigFile << "/config.ini";
         fixme("Loading driver config file: %s", DriverConfigFile.c_str());
         VirtualFileSystem::File DriverDirectory = vfs->Open(Config.DriverDirectory);
         if (DriverDirectory.IsOK())
         {
             foreach (auto driver in DriverDirectory.node->Children)
                 if (driver->Flags == VirtualFileSystem::NodeFlags::FILE)
                     if (cwk_path_has_extension(driver->Name))
                     {
                         const char *extension;
                         size_t extension_length;
                         cwk_path_get_extension(driver->Name, &extension, &extension_length);
                         debug("Driver: %s; Extension: %s", driver->Name, extension);
                         if (strcmp(extension, ".fex") == 0 || strcmp(extension, ".elf") == 0)
{
                             uintptr_t ret = this->LoadDriver(driver->Address, driver->Length);
                             char RetString[128];
                             if (ret == DriverCode::OK)
                                 strncpy(RetString, "\e058C19OK", 10);
                             else if (ret == DriverCode::NOT_AVAILABLE)
                                 strncpy(RetString, "\eFF7900NOT AVAILABLE", 21);
                             else
                                 sprintf(RetString, "\eE85230FAILED (%#lx)", ret);
                             KPrint("%s %s", driver->Name, RetString);
                         }
                     }
         }
         else
             KPrint("\eE85230Failed to open driver directory: %s! (Status: %#lx)", Config.DriverDirectory, DriverDirectory.Status);
         vfs->Close(DriverDirectory);
     }
References std::string::c_str(), VirtualFileSystem::Node::Children, VirtualFileSystem::Virtual::Close(), Config, cwk_path_get_extension(), cwk_path_has_extension(), debug, KernelConfig::DriverDirectory, fixme, VirtualFileSystem::File::IsOK(), KPrint(), VirtualFileSystem::File::node, NOT_AVAILABLE, OK, VirtualFileSystem::Virtual::Open(), ret, sprintf(), VirtualFileSystem::File::Status, strcmp(), strncpy(), and vfs.
~Driver()
Driver::Driver::~Driver ()
Definition at line 252 of file Driver.cpp.
     {
         debug("Destructor called");
         this->UnloadAllDrivers();
     }
References debug.
Member Function Documentation
BindInputAudio()
DriverCode Driver::Driver::BindInputAudio (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Audio.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindInputDisplay()
DriverCode Driver::Driver::BindInputDisplay (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Display.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindInputFileSystem()
DriverCode Driver::Driver::BindInputFileSystem (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Filesystem.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindInputGeneric()
DriverCode Driver::Driver::BindInputGeneric (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Generic.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindInputInput()
DriverCode Driver::Driver::BindInputInput (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Input.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         KernelCallback KCallback{};
         fixme("Input driver: %s", fexExtended->Driver.Name);
         KCallback.RawPtr = nullptr;
         KCallback.Reason = CallbackReason::ConfigurationReason;
         int CallbackRet = ((int (*)(KernelCallback *))((uintptr_t)fexExtended->Driver.Callback + (uintptr_t)fex))(&KCallback);
         if (CallbackRet == DriverReturnCode::NOT_IMPLEMENTED)
         {
             delete mem, mem = nullptr;
             error("Driver %s is not implemented", fexExtended->Driver.Name);
             return DriverCode::NOT_IMPLEMENTED;
         }
         else if (CallbackRet != DriverReturnCode::OK)
         {
             delete mem, mem = nullptr;
             error("Driver %s returned error %d", fexExtended->Driver.Name, CallbackRet);
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         fixme("Input driver: %s", fexExtended->Driver.Name);
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .MemTrk = mem,
         };
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References ConfigurationReason, FexExtended::Driver, Driver::DRIVER_RETURNED_ERROR, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, fixme, int, Execute::mem, NOT_IMPLEMENTED, and OK.
BindInputNetwork()
DriverCode Driver::Driver::BindInputNetwork (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Network.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindInputStorage()
DriverCode Driver::Driver::BindInputStorage (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Storage.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindInterruptAudio()
DriverCode Driver::Driver::BindInterruptAudio (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Audio.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Audio driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, and NOT_IMPLEMENTED.
BindInterruptDisplay()
DriverCode Driver::Driver::BindInterruptDisplay (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Display.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Display driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, and NOT_IMPLEMENTED.
BindInterruptFileSystem()
DriverCode Driver::Driver::BindInterruptFileSystem (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Filesystem.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Filesystem driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, and NOT_IMPLEMENTED.
BindInterruptGeneric()
DriverCode Driver::Driver::BindInterruptGeneric (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Generic.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Generic driver: %s", fexExtended->Driver.Name);
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexExtended->Driver.InterruptCallback),
             .MemTrk = mem,
         };
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, and OK.
BindInterruptInput()
DriverCode Driver::Driver::BindInterruptInput (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Input.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         debug("Searching for conflicting drivers...");
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if ((fe->Driver.TypeFlags & FexDriverInputTypes_Mouse &&
                      fexExtended->Driver.TypeFlags & FexDriverInputTypes_Mouse) ||
                     (fe->Driver.TypeFlags & FexDriverInputTypes_Keyboard &&
                      fexExtended->Driver.TypeFlags & FexDriverInputTypes_Keyboard))
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     if (fe->Driver.OverrideOnConflict)
                         return DriverCode::DRIVER_CONFLICT;
                     DriversToRemove.push_back(Drv.DriverUID);
                 }
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if ((fe->Driver.TypeFlags & FexDriverInputTypes_Mouse &&
                      fexExtended->Driver.TypeFlags & FexDriverInputTypes_Mouse) ||
                     (fe->Driver.TypeFlags & FexDriverInputTypes_Keyboard &&
                      fexExtended->Driver.TypeFlags & FexDriverInputTypes_Keyboard))
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     if (fe->Driver.OverrideOnConflict)
                         return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexExtended->Driver.InterruptCallback),
             .MemTrk = mem,
         };
         if (fexExtended->Driver.InterruptCallback)
         {
             for (unsigned long i = 0; i < sizeof(fexExtended->Driver.Bind.Interrupt.Vector) / sizeof(fexExtended->Driver.Bind.Interrupt.Vector[0]); i++)
             {
                 if (fexExtended->Driver.Bind.Interrupt.Vector[i] == 0)
                     break;
                 DrvFile.InterruptHook[i] = new DriverInterruptHook(fexExtended->Driver.Bind.Interrupt.Vector[i], DrvFile);
             }
         }
         KernelCallback KCallback{};
         KCallback.RawPtr = nullptr;
         KCallback.Reason = CallbackReason::ConfigurationReason;
         int CallbackRet = ((int (*)(KernelCallback *))((uintptr_t)fexExtended->Driver.Callback + (uintptr_t)fex))(&KCallback);
         if (CallbackRet == DriverReturnCode::NOT_IMPLEMENTED)
         {
             error("Driver %s is not implemented", fexExtended->Driver.Name);
             delete mem, mem = nullptr;
             return DriverCode::NOT_IMPLEMENTED;
         }
         else if (CallbackRet != DriverReturnCode::OK)
         {
             error("Driver %s returned error %d", fexExtended->Driver.Name, CallbackRet);
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References ConfigurationReason, debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, Driver::DRIVER_RETURNED_ERROR, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, FexDriverInputTypes_Keyboard, FexDriverInputTypes_Mouse, i, int, Driver::DriverFile::InterruptHook, Execute::mem, NOT_IMPLEMENTED, and OK.
BindInterruptNetwork()
DriverCode Driver::Driver::BindInterruptNetwork (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Network.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Network driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, and NOT_IMPLEMENTED.
BindInterruptStorage()
DriverCode Driver::Driver::BindInterruptStorage (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Storage.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexExtended->Driver.InterruptCallback),
             .MemTrk = mem,
         };
         if (fexExtended->Driver.InterruptCallback)
         {
             for (unsigned long i = 0; i < sizeof(fexExtended->Driver.Bind.Interrupt.Vector) / sizeof(fexExtended->Driver.Bind.Interrupt.Vector[0]); i++)
             {
                 if (fexExtended->Driver.Bind.Interrupt.Vector[i] == 0)
                     break;
                 DrvFile.InterruptHook[i] = new DriverInterruptHook(fexExtended->Driver.Bind.Interrupt.Vector[i], DrvFile);
             }
         }
         KernelCallback KCallback{};
         KCallback.RawPtr = nullptr;
         KCallback.Reason = CallbackReason::ConfigurationReason;
         int CallbackRet = ((int (*)(KernelCallback *))((uintptr_t)fexExtended->Driver.Callback + (uintptr_t)fex))(&KCallback);
         if (CallbackRet == DriverReturnCode::NOT_IMPLEMENTED)
         {
             error("Driver %s is not implemented", fexExtended->Driver.Name);
             delete mem, mem = nullptr;
             return DriverCode::NOT_IMPLEMENTED;
         }
         else if (CallbackRet != DriverReturnCode::OK)
         {
             error("Driver %s returned error %d", fexExtended->Driver.Name, CallbackRet);
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References ConfigurationReason, debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, Driver::DRIVER_RETURNED_ERROR, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, i, int, Driver::DriverFile::InterruptHook, Execute::mem, NOT_IMPLEMENTED, and OK.
BindPCIAudio()
DriverCode Driver::Driver::BindPCIAudio (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Audio.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexExtended->Driver.InterruptCallback),
             .MemTrk = mem,
         };
         if (fexExtended->Driver.InterruptCallback)
             DrvFile.InterruptHook[0] = new DriverInterruptHook(((int)((PCI::PCIHeader0 *)PCIDevice)->InterruptLine), DrvFile);
         KernelCallback KCallback{};
         KCallback.RawPtr = PCIDevice;
         KCallback.Reason = CallbackReason::ConfigurationReason;
         int CallbackRet = ((int (*)(KernelCallback *))((uintptr_t)fexExtended->Driver.Callback + (uintptr_t)fex))(&KCallback);
         if (CallbackRet == DriverReturnCode::NOT_IMPLEMENTED)
         {
             error("Driver %s is not implemented", fexExtended->Driver.Name);
             delete mem, mem = nullptr;
             return DriverCode::NOT_IMPLEMENTED;
         }
         else if (CallbackRet == DriverReturnCode::OK)
             trace("Device found for driver: %s", fexExtended->Driver.Name);
         else
         {
             error("Driver %s returned error %d", fexExtended->Driver.Name, CallbackRet);
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References ConfigurationReason, debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, Driver::DRIVER_RETURNED_ERROR, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, int, Driver::DriverFile::InterruptHook, Execute::mem, NOT_IMPLEMENTED, OK, and trace.
BindPCIDisplay()
DriverCode Driver::Driver::BindPCIDisplay (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Display.cpp.
     {
         UNUSED(PCIDevice);
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Display driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindPCIFileSystem()
DriverCode Driver::Driver::BindPCIFileSystem (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Filesystem.cpp.
     {
         UNUSED(PCIDevice);
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Filesystem driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindPCIGeneric()
DriverCode Driver::Driver::BindPCIGeneric (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Generic.cpp.
     {
         UNUSED(PCIDevice);
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Generic driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindPCIInput()
DriverCode Driver::Driver::BindPCIInput (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Input.cpp.
     {
         UNUSED(PCIDevice);
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         fixme("Input driver: %s", fexExtended->Driver.Name);
         delete mem, mem = nullptr;
         return DriverCode::NOT_IMPLEMENTED;
     }
References debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, error, EXTENDED_SECTION_ADDRESS, fixme, Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindPCINetwork()
DriverCode Driver::Driver::BindPCINetwork (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Network.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexExtended->Driver.InterruptCallback),
             .MemTrk = mem,
         };
         if (fexExtended->Driver.InterruptCallback)
             DrvFile.InterruptHook[0] = new DriverInterruptHook(((int)((PCI::PCIHeader0 *)PCIDevice)->InterruptLine), DrvFile);
         KernelCallback KCallback{};
         KCallback.RawPtr = PCIDevice;
         KCallback.Reason = CallbackReason::ConfigurationReason;
         int CallbackRet = ((int (*)(KernelCallback *))((uintptr_t)fexExtended->Driver.Callback + (uintptr_t)fex))(&KCallback);
         if (CallbackRet == DriverReturnCode::NOT_IMPLEMENTED)
         {
             error("Driver %s is not implemented", fexExtended->Driver.Name);
             delete mem, mem = nullptr;
             return DriverCode::NOT_IMPLEMENTED;
         }
         else if (CallbackRet == DriverReturnCode::OK)
             trace("Device found for driver: %s", fexExtended->Driver.Name);
         else
         {
             error("Driver %s returned error %d", fexExtended->Driver.Name, CallbackRet);
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References ConfigurationReason, debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, Driver::DRIVER_RETURNED_ERROR, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, int, Driver::DriverFile::InterruptHook, Execute::mem, NOT_IMPLEMENTED, OK, and trace.
BindPCIStorage()
DriverCode Driver::Driver::BindPCIStorage (Memory::MemMgr * mem, void * fex, PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file Storage.cpp.
     {
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         if (fexExtended->Driver.OverrideOnConflict)
         {
             std::vector<size_t> DriversToRemove = std::vector<size_t>();
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
                 DriversToRemove.push_back(Drv.DriverUID);
             }
             foreach (auto DrvID in DriversToRemove)
             {
                 if (!this->UnloadDriver(DrvID))
                 {
                     error("Failed to unload conflicting driver %d", DrvID);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         else
         {
             foreach (auto Drv in Drivers)
             {
                 FexExtended *fe = ((FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS));
                 if (fe->Driver.OverrideOnConflict)
                 {
                     debug("Driver %s is conflicting with %s", fe->Driver.Name, fexExtended->Driver.Name);
                     return DriverCode::DRIVER_CONFLICT;
                 }
             }
         }
         DriverFile DrvFile = {
             .Enabled = true,
             .DriverUID = this->DriverUIDs - 1,
             .Address = (void *)fex,
             .InterruptCallback = (void *)((uintptr_t)fex + (uintptr_t)fexExtended->Driver.InterruptCallback),
             .MemTrk = mem,
         };
         if (fexExtended->Driver.InterruptCallback)
             DrvFile.InterruptHook[0] = new DriverInterruptHook(((int)((PCI::PCIHeader0 *)PCIDevice)->InterruptLine), DrvFile);
         KernelCallback KCallback{};
         KCallback.RawPtr = PCIDevice;
         KCallback.Reason = CallbackReason::ConfigurationReason;
         int CallbackRet = ((int (*)(KernelCallback *))((uintptr_t)fexExtended->Driver.Callback + (uintptr_t)fex))(&KCallback);
         if (CallbackRet == DriverReturnCode::NOT_IMPLEMENTED)
         {
             error("Driver %s is not implemented", fexExtended->Driver.Name);
             delete mem, mem = nullptr;
             return DriverCode::NOT_IMPLEMENTED;
         }
         else if (CallbackRet == DriverReturnCode::OK)
             trace("Device found for driver: %s", fexExtended->Driver.Name);
         else
         {
             error("Driver %s returned error %d", fexExtended->Driver.Name, CallbackRet);
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         Drivers.push_back(DrvFile);
         return DriverCode::OK;
     }
References ConfigurationReason, debug, FexExtended::Driver, Driver::DRIVER_CONFLICT, Driver::DRIVER_RETURNED_ERROR, Driver::DriverFile::Enabled, error, EXTENDED_SECTION_ADDRESS, int, Driver::DriverFile::InterruptHook, Execute::mem, NOT_IMPLEMENTED, OK, and trace.
BindProcessAudio()
DriverCode Driver::Driver::BindProcessAudio (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Audio.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindProcessDisplay()
DriverCode Driver::Driver::BindProcessDisplay (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Display.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindProcessFileSystem()
DriverCode Driver::Driver::BindProcessFileSystem (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Filesystem.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindProcessGeneric()
DriverCode Driver::Driver::BindProcessGeneric (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Generic.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindProcessInput()
DriverCode Driver::Driver::BindProcessInput (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Input.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindProcessNetwork()
DriverCode Driver::Driver::BindProcessNetwork (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Network.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
BindProcessStorage()
DriverCode Driver::Driver::BindProcessStorage (Memory::MemMgr * mem, void * fex) private
Definition at line 34 of file Storage.cpp.
     {
         UNUSED(mem);
         UNUSED(fex);
         return DriverCode::NOT_IMPLEMENTED;
     }
References Execute::mem, NOT_IMPLEMENTED, and Driver::UNUSED().
CallDriverEntryPoint()
DriverCode Driver::Driver::CallDriverEntryPoint (void * fex, void * KAPIAddress) private
Definition at line 133 of file Driver.cpp.
     {
         memcpy(KAPIAddress, &KernelAPITemplate, sizeof(KernelAPI));
         ((KernelAPI *)KAPIAddress)->Info.Offset = (unsigned long)fex;
         ((KernelAPI *)KAPIAddress)->Info.DriverUID = DriverUIDs++;
         ((KernelAPI *)KAPIAddress)->Info.KernelDebug = DebuggerIsAttached;
 #ifdef DEBUG
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         debug("DRIVER: %s HAS DRIVER ID %ld", fexExtended->Driver.Name, ((KernelAPI *)KAPIAddress)->Info.DriverUID);
 #endif
         debug("Calling driver entry point ( %#lx %ld )", (unsigned long)fex, ((KernelAPI *)KAPIAddress)->Info.DriverUID);
         int ret = ((int (*)(KernelAPI *))((uintptr_t)((Fex *)fex)->EntryPoint + (uintptr_t)fex))(((KernelAPI *)KAPIAddress));
         if (DriverReturnCode::OK != ret)
             return DriverCode::DRIVER_RETURNED_ERROR;
         return DriverCode::OK;
     }
References debug, DebuggerIsAttached, FexExtended::Driver, Driver::DRIVER_RETURNED_ERROR, KAPIInfo::DriverUID, EntryPoint, EXTENDED_SECTION_ADDRESS, Info, int, KernelAPITemplate, memcpy, OK, and ret.
DriverLoadBindInput()
DriverCode Driver::Driver::DriverLoadBindInput (void * DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf = false) private
Definition at line 34 of file BindInput.cpp.
     {
         UNUSED(DrvExtHdr);
         UNUSED(IsElf);
         Memory::MemMgr *mem = new Memory::MemMgr(nullptr, TaskManager->GetCurrentProcess()->memDirectory);
         Fex *fex = (Fex *)mem->RequestPages(TO_PAGES(Size + 1));
         memcpy(fex, (void *)DriverAddress, Size);
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         debug("Driver allocated at %#lx-%#lx", fex, (uintptr_t)fex + Size);
 #ifdef DEBUG
         uint8_t *result = md5File((uint8_t *)fex, Size);
         debug("MD5: %02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
               result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7],
               result[8], result[9], result[10], result[11], result[12], result[13], result[14], result[15]);
         kfree(result);
 #endif
         KernelAPI *KAPI = (KernelAPI *)mem->RequestPages(TO_PAGES(sizeof(KernelAPI) + 1));
         if (CallDriverEntryPoint(fex, KAPI) != DriverCode::OK)
         {
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         debug("Starting driver %s (offset: %#lx)", fexExtended->Driver.Name, fex);
         switch (fexExtended->Driver.Type)
         {
         case FexDriverType::FexDriverType_Input:
             return BindInputInput(mem, fex);
         default:
         {
             warn("Unknown driver type: %d", fexExtended->Driver.Type);
             delete mem, mem = nullptr;
             return DriverCode::UNKNOWN_DRIVER_TYPE;
         }
         }
         return DriverCode::OK;
     }
References debug, FexExtended::Driver, Driver::DRIVER_RETURNED_ERROR, EXTENDED_SECTION_ADDRESS, FexDriverType_Input, Tasking::Task::GetCurrentProcess(), kfree, md5File(), Execute::mem, memcpy, Tasking::PCB::memDirectory, OK, Size, TaskManager, TO_PAGES, Driver::UNKNOWN_DRIVER_TYPE, Driver::UNUSED(), and warn.
DriverLoadBindInterrupt()
DriverCode Driver::Driver::DriverLoadBindInterrupt (void * DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf = false) private
Definition at line 34 of file BindInterrupt.cpp.
     {
         UNUSED(DrvExtHdr);
         UNUSED(IsElf);
         Memory::MemMgr *mem = new Memory::MemMgr(nullptr, TaskManager->GetCurrentProcess()->memDirectory);
         Fex *fex = (Fex *)mem->RequestPages(TO_PAGES(Size + 1));
         memcpy(fex, (void *)DriverAddress, Size);
         FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
         debug("Driver allocated at %#lx-%#lx", fex, (uintptr_t)fex + Size);
 #ifdef DEBUG
         uint8_t *result = md5File((uint8_t *)fex, Size);
         debug("MD5: %02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
               result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7],
               result[8], result[9], result[10], result[11], result[12], result[13], result[14], result[15]);
         kfree(result);
 #endif
         KernelAPI *KAPI = (KernelAPI *)mem->RequestPages(TO_PAGES(sizeof(KernelAPI) + 1));
         if (CallDriverEntryPoint(fex, KAPI) != DriverCode::OK)
         {
             delete mem, mem = nullptr;
             return DriverCode::DRIVER_RETURNED_ERROR;
         }
         debug("Starting driver %s (offset: %#lx)", fexExtended->Driver.Name, fex);
         switch (fexExtended->Driver.Type)
         {
         case FexDriverType::FexDriverType_Generic:
             return BindInterruptGeneric(mem, fex);
         case FexDriverType::FexDriverType_Display:
             return BindInterruptDisplay(mem, fex);
         case FexDriverType::FexDriverType_Network:
             return BindInterruptNetwork(mem, fex);
         case FexDriverType::FexDriverType_Storage:
             return BindInterruptStorage(mem, fex);
         case FexDriverType::FexDriverType_FileSystem:
             return BindInterruptFileSystem(mem, fex);
         case FexDriverType::FexDriverType_Input:
             return BindInterruptInput(mem, fex);
         case FexDriverType::FexDriverType_Audio:
             return BindInterruptAudio(mem, fex);
         default:
         {
             warn("Unknown driver type: %d", fexExtended->Driver.Type);
             delete mem, mem = nullptr;
             return DriverCode::UNKNOWN_DRIVER_TYPE;
         }
         }
         return DriverCode::OK;
     }
References debug, FexExtended::Driver, Driver::DRIVER_RETURNED_ERROR, EXTENDED_SECTION_ADDRESS, FexDriverType_Audio, FexDriverType_Display, FexDriverType_FileSystem, FexDriverType_Generic, FexDriverType_Input, FexDriverType_Network, FexDriverType_Storage, Tasking::Task::GetCurrentProcess(), kfree, md5File(), Execute::mem, memcpy, Tasking::PCB::memDirectory, OK, Size, TaskManager, TO_PAGES, Driver::UNKNOWN_DRIVER_TYPE, Driver::UNUSED(), and warn.
DriverLoadBindPCI()
DriverCode Driver::Driver::DriverLoadBindPCI (void * DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf = false) private
Definition at line 130 of file BindPCI.cpp.
     {
         UNUSED(IsElf);
         for (unsigned long Vidx = 0; Vidx < sizeof(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.VendorID) / sizeof(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.VendorID[0]); Vidx++)
         {
             for (unsigned long Didx = 0; Didx < sizeof(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.DeviceID) / sizeof(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.DeviceID[0]); Didx++)
             {
                 if (Vidx >= sizeof(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.VendorID) && Didx >= sizeof(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.DeviceID))
                     break;
                 if (((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.VendorID[Vidx] == 0 || ((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.DeviceID[Didx] == 0)
                     continue;
                 std::vector<PCI::PCIDeviceHeader *> devices = PCIManager->FindPCIDevice(((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.VendorID[Vidx], ((FexExtended *)DrvExtHdr)->Driver.Bind.PCI.DeviceID[Didx]);
                 if (devices.size() == 0)
                     continue;
                 foreach (auto PCIDevice in devices)
                 {
                     debug("[%ld] VendorID: %#x; DeviceID: %#x", devices.size(), PCIDevice->VendorID, PCIDevice->DeviceID);
                     Memory::MemMgr *mem = new Memory::MemMgr(nullptr, TaskManager->GetCurrentProcess()->memDirectory);
                     Fex *fex = (Fex *)mem->RequestPages(TO_PAGES(Size + 1));
                     memcpy(fex, (void *)DriverAddress, Size);
                     FexExtended *fexExtended = (FexExtended *)((uintptr_t)fex + EXTENDED_SECTION_ADDRESS);
                     debug("Driver allocated at %#lx-%#lx", fex, (uintptr_t)fex + Size);
 #ifdef DEBUG
                     uint8_t *result = md5File((uint8_t *)fex, Size);
                     debug("MD5: %02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
                           result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7],
                           result[8], result[9], result[10], result[11], result[12], result[13], result[14], result[15]);
                     kfree(result);
 #endif
                     KernelAPI *KAPI = (KernelAPI *)mem->RequestPages(TO_PAGES(sizeof(KernelAPI) + 1));
                     if (CallDriverEntryPoint(fex, KAPI) != DriverCode::OK)
                     {
                         delete mem, mem = nullptr;
                         return DriverCode::DRIVER_RETURNED_ERROR;
                     }
                     debug("Starting driver %s", fexExtended->Driver.Name);
                     MapPCIAddresses(PCIDevice);
                     switch (fexExtended->Driver.Type)
                     {
                     case FexDriverType::FexDriverType_Generic:
                         return BindPCIGeneric(mem, fex, PCIDevice);
                     case FexDriverType::FexDriverType_Display:
                         return BindPCIDisplay(mem, fex, PCIDevice);
                     case FexDriverType::FexDriverType_Network:
                         return BindPCINetwork(mem, fex, PCIDevice);
                     case FexDriverType::FexDriverType_Storage:
                         return BindPCIStorage(mem, fex, PCIDevice);
                     case FexDriverType::FexDriverType_FileSystem:
                         return BindPCIFileSystem(mem, fex, PCIDevice);
                     case FexDriverType::FexDriverType_Input:
                         return BindPCIInput(mem, fex, PCIDevice);
                     case FexDriverType::FexDriverType_Audio:
                         return BindPCIAudio(mem, fex, PCIDevice);
                     default:
                     {
                         warn("Unknown driver type: %d", fexExtended->Driver.Type);
                         delete mem, mem = nullptr;
                         return DriverCode::UNKNOWN_DRIVER_TYPE;
                     }
                     }
                 }
             }
         }
         return DriverCode::PCI_DEVICE_NOT_FOUND;
     }
References debug, FexExtended::Driver, Driver::DRIVER_RETURNED_ERROR, EXTENDED_SECTION_ADDRESS, FexDriverType_Audio, FexDriverType_Display, FexDriverType_FileSystem, FexDriverType_Generic, FexDriverType_Input, FexDriverType_Network, FexDriverType_Storage, PCI::PCI::FindPCIDevice(), Tasking::Task::GetCurrentProcess(), kfree, md5File(), Execute::mem, memcpy, Tasking::PCB::memDirectory, OK, Driver::PCI_DEVICE_NOT_FOUND, PCIManager, Size, std::vector< T >::size(), TaskManager, TO_PAGES, Driver::UNKNOWN_DRIVER_TYPE, Driver::UNUSED(), and warn.
DriverLoadBindProcess()
DriverCode Driver::Driver::DriverLoadBindProcess (void * DrvExtHdr, uintptr_t DriverAddress, size_t Size, bool IsElf = false) private
Definition at line 34 of file BindProcess.cpp.
     {
         fixme("Process driver: %s", ((FexExtended *)DrvExtHdr)->Driver.Name);
         UNUSED(Size);
         UNUSED(DriverAddress);
         UNUSED(IsElf);
         return DriverCode::NOT_IMPLEMENTED;
     }
References fixme, NOT_IMPLEMENTED, Size, and Driver::UNUSED().
GetDrivers()
std::vector<DriverFile> Driver::Driver::GetDrivers () inline
Definition at line 130 of file driver.hpp.
 { return Drivers; }
Referenced by Recovery::ChangeSampleRate(), Recovery::ChangeVolume(), GraphicalUserInterface::GUI::FetchInputs(), KernelMainThread(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), and Recovery::PlayAudio().
IOCB()
int Driver::Driver::IOCB (unsigned long DUID, void * KCB)
Definition at line 118 of file Driver.cpp.
     {
         foreach (auto Drv in Drivers)
         {
             if (Drv.DriverUID == DUID)
             {
                 FexExtended *DrvExtHdr = (FexExtended *)((uintptr_t)Drv.Address + EXTENDED_SECTION_ADDRESS);
                 int ret = ((int (*)(void *))((uintptr_t)DrvExtHdr->Driver.Callback + (uintptr_t)Drv.Address))(KCB);
                 __sync;
                 return ret;
             }
         }
         return -1;
     }
References __sync, FexExtended::Driver, EXTENDED_SECTION_ADDRESS, int, and ret.
Referenced by Recovery::ChangeSampleRate(), Recovery::ChangeVolume(), Disk::Manager::FetchDisks(), GraphicalUserInterface::GUI::FetchInputs(), NetworkInterfaceManager::NetworkInterface::FetchNetworkCards(), Panic(), Recovery::PlayAudio(), NetworkInterfaceManager::NetworkInterface::Send(), and UnloadAllDrivers().
LoadDriver()
DriverCode Driver::Driver::LoadDriver (uintptr_t DriverAddress, size_t Size)
Definition at line 154 of file Driver.cpp.
     {
         Fex *DrvHdr = (Fex *)DriverAddress;
         if (DrvHdr->Magic[0] != 'F' || DrvHdr->Magic[1] != 'E' || DrvHdr->Magic[2] != 'X' || DrvHdr->Magic[3] != '\0')
         {
             if (Size > 0x1000)
             {
                 Fex *ElfDrvHdr = (Fex *)(DriverAddress + 0x1000);
                 if (ElfDrvHdr->Magic[0] != 'F' || ElfDrvHdr->Magic[1] != 'E' || ElfDrvHdr->Magic[2] != 'X' || ElfDrvHdr->Magic[3] != '\0')
                     return DriverCode::INVALID_FEX_HEADER;
                 else
                 {
                     debug("Fex Magic: \"%s\"; Type: %d; OS: %d; EntryPoint: %#lx", ElfDrvHdr->Magic, ElfDrvHdr->Type, ElfDrvHdr->OS, ElfDrvHdr->EntryPoint);
                     if (ElfDrvHdr->Type == FexFormatType::FexFormatType_Driver)
                     {
                         FexExtended *ElfDrvExtHdr = (FexExtended *)((uintptr_t)ElfDrvHdr + EXTENDED_SECTION_ADDRESS);
                         debug("Name: \"%s\"; Type: %d; Callback: %#lx", ElfDrvExtHdr->Driver.Name, ElfDrvExtHdr->Driver.Type, ElfDrvExtHdr->Driver.Callback);
                         if (ElfDrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_PCI)
                             return this->DriverLoadBindPCI(ElfDrvExtHdr, DriverAddress, Size, true);
                         else if (ElfDrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_INTERRUPT)
                             return this->DriverLoadBindInterrupt(ElfDrvExtHdr, DriverAddress, Size, true);
                         else if (ElfDrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_PROCESS)
                             return this->DriverLoadBindProcess(ElfDrvExtHdr, DriverAddress, Size, true);
                         else if (ElfDrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_INPUT)
                             return this->DriverLoadBindInput(ElfDrvExtHdr, DriverAddress, Size, true);
                         else
                             error("Unknown driver bind type: %d", ElfDrvExtHdr->Driver.Bind.Type);
                     }
                     else
                         return DriverCode::NOT_DRIVER;
                 }
             }
             else
                 return DriverCode::INVALID_FEX_HEADER;
         }
         debug("Fex Magic: \"%s\"; Type: %d; OS: %d; EntryPoint: %#lx", DrvHdr->Magic, DrvHdr->Type, DrvHdr->OS, DrvHdr->EntryPoint);
         if (DrvHdr->Type == FexFormatType::FexFormatType_Driver)
         {
             FexExtended *DrvExtHdr = (FexExtended *)((uintptr_t)DrvHdr + EXTENDED_SECTION_ADDRESS);
             debug("Name: \"%s\"; Type: %d; Callback: %#lx", DrvExtHdr->Driver.Name, DrvExtHdr->Driver.Type, DrvExtHdr->Driver.Callback);
             if (DrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_PCI)
                 return this->DriverLoadBindPCI(DrvExtHdr, DriverAddress, Size);
             else if (DrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_INTERRUPT)
                 return this->DriverLoadBindInterrupt(DrvExtHdr, DriverAddress, Size);
             else if (DrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_PROCESS)
                 return this->DriverLoadBindProcess(DrvExtHdr, DriverAddress, Size);
             else if (DrvExtHdr->Driver.Bind.Type == DriverBindType::BIND_INPUT)
                 return this->DriverLoadBindInput(DrvExtHdr, DriverAddress, Size);
             else
                 error("Unknown driver bind type: %d", DrvExtHdr->Driver.Bind.Type);
         }
         else
             return DriverCode::NOT_DRIVER;
         return DriverCode::ERROR;
     }
References BIND_INPUT, BIND_INTERRUPT, BIND_PCI, BIND_PROCESS, debug, FexExtended::Driver, Fex::EntryPoint, ERROR, error, EXTENDED_SECTION_ADDRESS, FexFormatType_Driver, Driver::INVALID_FEX_HEADER, Fex::Magic, Driver::NOT_DRIVER, Fex::OS, Size, and Fex::Type.
MapPCIAddresses()
void Driver::Driver::MapPCIAddresses (PCI::PCIDeviceHeader * PCIDevice) private
Definition at line 34 of file BindPCI.cpp.
     {
         debug("Header Type: %d", PCIDevice->HeaderType);
         switch (PCIDevice->HeaderType)
         {
         case 0: // PCI Header 0
         {
             uint32_t BAR[6] = {0};
             size_t BARsSize[6] = {0};
             BAR[0] = ((PCI::PCIHeader0 *)PCIDevice)->BAR0;
             BAR[1] = ((PCI::PCIHeader0 *)PCIDevice)->BAR1;
             BAR[2] = ((PCI::PCIHeader0 *)PCIDevice)->BAR2;
             BAR[3] = ((PCI::PCIHeader0 *)PCIDevice)->BAR3;
             BAR[4] = ((PCI::PCIHeader0 *)PCIDevice)->BAR4;
             BAR[5] = ((PCI::PCIHeader0 *)PCIDevice)->BAR5;
 #ifdef DEBUG
             uintptr_t BAR_Type = BAR[0] & 1;
             uintptr_t BAR_IOBase = BAR[1] & (~3);
             uintptr_t BAR_MemoryBase = BAR[0] & (~15);
             debug("Type: %d; IOBase: %#lx; MemoryBase: %#lx", BAR_Type, BAR_IOBase, BAR_MemoryBase);
 #endif
             /* BARs Size */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 if ((BAR[i] & 1) == 0) // Memory Base
                 {
                     ((PCI::PCIHeader0 *)PCIDevice)->BAR0 = 0xFFFFFFFF;
                     size_t size = ((PCI::PCIHeader0 *)PCIDevice)->BAR0;
                     ((PCI::PCIHeader0 *)PCIDevice)->BAR0 = BAR[i];
                     BARsSize[i] = size & (~15);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFFFFFF;
                     debug("BAR%d %#lx size: %d", i, BAR[i], BARsSize[i]);
                 }
                 else if ((BAR[i] & 1) == 1) // I/O Base
                 {
                     ((PCI::PCIHeader0 *)PCIDevice)->BAR1 = 0xFFFFFFFF;
                     size_t size = ((PCI::PCIHeader0 *)PCIDevice)->BAR1;
                     ((PCI::PCIHeader0 *)PCIDevice)->BAR1 = BAR[i];
                     BARsSize[i] = size & (~3);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFF;
                     debug("BAR%d %#lx size: %d", i, BAR[i], BARsSize[i]);
                 }
             }
             /* Mapping the BARs */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 if ((BAR[i] & 1) == 0) // Memory Base
                 {
                     uintptr_t BARBase = BAR[i] & (~15);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#lx-%#lx", i, BARBase, BARBase + BARSize);
                     Memory::Virtual().Map((void *)BARBase, (void *)BARBase, BARSize, Memory::PTFlag::RW | Memory::PTFlag::PWT);
                 }
                 else if ((BAR[i] & 1) == 1) // I/O Base
                 {
                     uintptr_t BARBase = BAR[i] & (~3);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#x-%#x", i, BARBase, BARBase + BARSize);
                     Memory::Virtual().Map((void *)BARBase, (void *)BARBase, BARSize, Memory::PTFlag::RW | Memory::PTFlag::PWT);
                 }
             }
             break;
         }
         case 1: // PCI Header 1 (PCI-to-PCI Bridge)
         {
             fixme("PCI Header 1 (PCI-to-PCI Bridge) not implemented yet");
             break;
         }
         case 2: // PCI Header 2 (PCI-to-CardBus Bridge)
         {
             fixme("PCI Header 2 (PCI-to-CardBus Bridge) not implemented yet");
             break;
         }
         default:
         {
             error("Unknown header type %d", PCIDevice->HeaderType);
             return;
         }
         }
     }
References debug, error, fixme, PCI::PCIDeviceHeader::HeaderType, i, and size.
Panic()
void Driver::Driver::Panic ()
Definition at line 38 of file Driver.cpp.
     {
 #ifdef DEBUG
         size_t DriversNum = Drivers.size();
         debug("%ld drivers loaded, [DUIDs: %ld]", DriversNum, DriverUIDs);
         debug("driver size %ld", DriversNum);
 #endif
         foreach (auto drv in Drivers)
         {
             KernelCallback callback{};
             callback.Reason = StopReason;
             DriverManager->IOCB(drv.DriverUID, &callback);
             for (size_t j = 0; j < sizeof(drv.InterruptHook) / sizeof(drv.InterruptHook[0]); j++)
             {
                 if (!drv.InterruptHook[j])
                     continue;
                 drv.InterruptHook[j]->Disable();
                 debug("Interrupt hook %#lx disabled", drv.InterruptHook[j]);
             }
         }
     }
References callback(), debug, DriverManager, IOCB(), j, and StopReason.
Referenced by CrashHandler::Handle().
StartDrivers()
DriverCode Driver::Driver::StartDrivers ()
UnloadAllDrivers()
void Driver::Driver::UnloadAllDrivers ()
Definition at line 62 of file Driver.cpp.
     {
 #ifdef DEBUG
         size_t DriversNum = Drivers.size();
         debug("%ld drivers loaded, [DUIDs: %ld]", DriversNum, DriverUIDs);
         debug("driver size %ld", DriversNum);
 #endif
         foreach (auto drv in Drivers)
         {
             KernelCallback callback{};
             callback.Reason = StopReason;
             debug("Stopping & unloading driver %ld [%#lx]", drv.DriverUID, drv.Address);
             DriverManager->IOCB(drv.DriverUID, &callback);
             for (size_t j = 0; j < sizeof(drv.InterruptHook) / sizeof(drv.InterruptHook[0]); j++)
             {
                 if (!drv.InterruptHook[j])
                     continue;
                 debug("Interrupt hook %#lx", drv.InterruptHook[j]);
                 delete drv.InterruptHook[j], drv.InterruptHook[j] = nullptr;
             }
             if (drv.MemTrk)
                 delete drv.MemTrk, drv.MemTrk = nullptr;
         }
         Drivers.clear();
     }
References callback(), debug, DriverManager, IOCB(), j, and StopReason.
UnloadDriver()
bool Driver::Driver::UnloadDriver (unsigned long DUID)
Definition at line 90 of file Driver.cpp.
     {
         debug("Searching for driver %ld", DUID);
         foreach (auto drv in Drivers)
         {
             if (drv.DriverUID == DUID)
             {
                 KernelCallback callback{};
                 callback.Reason = StopReason;
                 debug("Stopping and unloading driver %ld [%#lx]", drv.DriverUID, drv.Address);
                 this->IOCB(drv.DriverUID, &callback);
                 for (size_t j = 0; j < sizeof(drv.InterruptHook) / sizeof(drv.InterruptHook[0]); j++)
                 {
                     if (!drv.InterruptHook[j])
                         continue;
                     debug("Interrupt hook %#lx", drv.InterruptHook[j]);
                     delete drv.InterruptHook[j], drv.InterruptHook[j] = nullptr;
                 }
                 delete drv.MemTrk, drv.MemTrk = nullptr;
                 Drivers.remove(drv);
                 return true;
             }
         }
         return false;
     }
References callback(), debug, j, and StopReason.
Field Documentation
Drivers
std::vector<DriverFile> Driver::Driver::Drivers private
Definition at line 88 of file driver.hpp.
DriverUIDs
unsigned long Driver::Driver::DriverUIDs = 0 private
Definition at line 89 of file driver.hpp.
The documentation for this class was generated from the following files:
Kernel/include/driver.hpp
Kernel/Core/Driver/Driver.cpp
Kernel/Core/Driver/DriverBinding/BindInput.cpp
Kernel/Core/Driver/DriverBinding/BindInterrupt.cpp
Kernel/Core/Driver/DriverBinding/BindPCI.cpp
Kernel/Core/Driver/DriverBinding/BindProcess.cpp
Kernel/Core/Driver/DriverBinding/Input/Audio.cpp
Kernel/Core/Driver/DriverBinding/Input/Display.cpp
Kernel/Core/Driver/DriverBinding/Input/Filesystem.cpp
Kernel/Core/Driver/DriverBinding/Input/Generic.cpp
Kernel/Core/Driver/DriverBinding/Input/Input.cpp
Kernel/Core/Driver/DriverBinding/Input/Network.cpp
Kernel/Core/Driver/DriverBinding/Input/Storage.cpp