Fennix Userspace: Userspace/apps/base/busybox/libbb/xgetcwd.c File Reference
xgetcwd.c File Reference
#include "libbb.h"
Macros
#define PATH_INCR 64
Functions
char *FAST_FUNC xrealloc_getcwd_or_warn (char *cwd)
Macro Definition Documentation
PATH_INCR
#define PATH_INCR 64
Function Documentation
xrealloc_getcwd_or_warn()
char* FAST_FUNC xrealloc_getcwd_or_warn (char * cwd)
Definition at line 19 of file xgetcwd.c.
 {
 #define PATH_INCR 64
     char *ret;
     unsigned path_max;
     path_max = 128; /* 128 + 64 should be enough for 99% of cases */
     while (1) {
         path_max += PATH_INCR;
         cwd = xrealloc(cwd, path_max);
         ret = getcwd(cwd, path_max);
         if (ret == NULL) {
             if (errno == ERANGE)
                 continue;
             free(cwd);
             bb_simple_perror_msg("getcwd");
             return NULL;
         }
         cwd = xrealloc(cwd, strlen(cwd) + 1);
         return cwd;
     }
 }
References bb_simple_perror_msg(), ERANGE, errno, free, getcwd, NULL, PATH_INCR, strlen(), and xrealloc.
Referenced by bb_simplify_path(), get_cwd(), handle_pwd(), httpd_main(), pwd_main(), and xmalloc_realpath_coreutils().