Fennix: Userspace/musl/src/process/system.c File Reference
system.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <sys/wait.h>
#include <spawn.h>
#include <errno.h>
#include "pthread_impl.h"
Functions
int system (const char *cmd)
Variables
char ** __environ
Function Documentation
system()
int system (const char * cmd)
Definition at line 11 of file system.c.
 {
     pid_t pid;
     sigset_t old, reset;
     struct sigaction sa = { .sa_handler = SIG_IGN }, oldint, oldquit;
     int status = -1, ret;
     posix_spawnattr_t attr;
     pthread_testcancel();
     if (!cmd) return 1;
     sigaction(SIGINT, &sa, &oldint);
     sigaction(SIGQUIT, &sa, &oldquit);
     sigaddset(&sa.sa_mask, SIGCHLD);
     sigprocmask(SIG_BLOCK, &sa.sa_mask, &old);
     sigemptyset(&reset);
     if (oldint.sa_handler != SIG_IGN) sigaddset(&reset, SIGINT);
     if (oldquit.sa_handler != SIG_IGN) sigaddset(&reset, SIGQUIT);
     posix_spawnattr_init(&attr);
     posix_spawnattr_setsigmask(&attr, &old);
     posix_spawnattr_setsigdefault(&attr, &reset);
     posix_spawnattr_setflags(&attr, POSIX_SPAWN_SETSIGDEF|POSIX_SPAWN_SETSIGMASK);
     ret = posix_spawn(&pid, "/bin/sh", 0, &attr,
         (char *[]){"sh", "-c", (char *)cmd, 0}, __environ);
     posix_spawnattr_destroy(&attr);
     if (!ret) while (waitpid(pid, &status, 0)<0 && errno == EINTR);
     sigaction(SIGINT, &oldint, NULL);
     sigaction(SIGQUIT, &oldquit, NULL);
     sigprocmask(SIG_SETMASK, &old, NULL);
     if (ret) errno = ret;
     return status;
 }
References __environ, cmd, EINTR, errno, NULL, old, pid, posix_spawn(), POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, posix_spawnattr_destroy(), posix_spawnattr_init(), posix_spawnattr_setflags(), posix_spawnattr_setsigdefault(), posix_spawnattr_setsigmask(), pthread_testcancel(), reset(), SIG_BLOCK, SIG_IGN, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, sigprocmask(), SIGQUIT, status, and waitpid().
Referenced by colon(), com_list(), com_view(), evaluate(), finalize(), Main(), make_device(), run_package_script_or_die(), run_pipe(), slattach_main(), watch_main(), ZenityAvailable(), and ZenityErrorBox().
Variable Documentation
__environ
char** __environ extern
Definition at line 3 of file __environ.c.
Referenced by system().