Fennix: Userspace/apps/base/busybox/libbb/progress.c File Reference
progress.c File Reference
#include "libbb.h"
#include "unicode.h"
Enumerations
enum { STALLTIME = 5 }
Functions
void FAST_FUNC bb_progress_init (bb_progress_t *p, const char *curfile)
int FAST_FUNC bb_progress_update (bb_progress_t *p, uoff_t beg_size, uoff_t transferred, uoff_t totalsize)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STALLTIME
Definition at line 43 of file progress.c.
      {
     /* Seconds when xfer considered "stalled" */
     STALLTIME = 5
 };
Function Documentation
bb_progress_init()
void FAST_FUNC bb_progress_init (bb_progress_t * p, const char * curfile)
Definition at line 48 of file progress.c.
 {
 #if ENABLE_UNICODE_SUPPORT
     init_unicode();
     p->curfile = unicode_conv_to_printable_fixedwidth(/*NULL,*/ curfile, 20);
 #else
     p->curfile = curfile;
 #endif
     p->start_sec = monotonic_sec();
     p->last_update_sec = p->start_sec;
     p->last_change_sec = p->start_sec;
     p->last_size = 0;
 #if 0
     p->last_eta = INT_MAX;
 #endif
 }
References init_unicode, INT_MAX, monotonic_sec(), p, and unicode_conv_to_printable_fixedwidth().
bb_progress_update()
int FAST_FUNC bb_progress_update (bb_progress_t * p, uoff_t beg_size, uoff_t transferred, uoff_t totalsize)
Definition at line 72 of file progress.c.
 {
     char numbuf5[6]; /* 5 + 1 for NUL */
     unsigned since_last_update, elapsed;
     int notty;
     //transferred = 1234; /* use for stall detection testing */
     //totalsize = 0; /* use for unknown size download testing */
     elapsed = monotonic_sec();
     since_last_update = elapsed - p->last_update_sec;
     p->last_update_sec = elapsed;
     if (totalsize != 0 && transferred >= totalsize - beg_size) {
         /* Last call. Do not skip this update */
         transferred = totalsize - beg_size; /* sanitize just in case */
     }
     else if (since_last_update == 0) {
         /*
          * Do not update on every call
          * (we can be called on every network read!)
          */
         return -1;
     }
     /* Before we lose real, unscaled sizes, produce human-readable size string */
     smart_ulltoa5(beg_size + transferred, numbuf5, " kMGTPEZY")[0] = '\0';
     /*
      * Scale sizes down if they are close to overflowing.
      * This allows calculations like (100 * transferred / totalsize)
      * without risking overflow: we guarantee 10 highest bits to be 0.
      * Introduced error is less than 1 / 2^12 ~= 0.025%
      */
     while (totalsize >= (1 << 20)) {
         totalsize >>= 8;
         beg_size >>= 8;
         transferred >>= 8;
     }
     /* If they were huge, now they are scaled down to [1048575,4096] range.
      * (N * totalsize) won't overflow 32 bits for N up to 4096.
      */
 #if ULONG_MAX == 0xffffffff
 /* 32-bit CPU, uoff_t arithmetic is complex on it, cast variables to narrower types */
 # define totalsize   ((unsigned)totalsize)
 # define beg_size    ((unsigned)beg_size)
 # define transferred ((unsigned)transferred)
 #endif
     notty = !isatty(STDERR_FILENO);
     if (ENABLE_UNICODE_SUPPORT)
         fprintf(stderr, "\r%s " + notty, p->curfile);
     else
         fprintf(stderr, "\r%-20.20s " + notty, p->curfile);
     if (totalsize != 0) {
         int barlength;
         unsigned beg_and_transferred; /* does not need uoff_t, see scaling code */
         unsigned ratio;
         beg_and_transferred = beg_size + transferred;
         ratio = 100 * beg_and_transferred / totalsize;
         /* can't overflow ^^^^^^^^^^^^^^^ */
         fprintf(stderr, "%3u%% ", ratio);
         barlength = get_terminal_width(2) - 48;
         /*
          * Must reject barlength <= 0 (terminal too narrow). While at it,
          * also reject: 1-char bar (useless), 2-char bar (ridiculous).
          */
         if (barlength > 2) {
             if (barlength > 999)
                 barlength = 999;
             {
                 /* god bless gcc for variable arrays :) */
                 char buf[barlength + 1];
                 unsigned stars = (unsigned)barlength * beg_and_transferred / totalsize;
                 /* can't overflow ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ */
                 memset(buf, ' ', barlength);
                 buf[barlength] = '\0';
                 memset(buf, '*', stars);
                 fprintf(stderr, "|%s| ", buf);
             }
         }
     }
     fputs(numbuf5, stderr); /* "NNNNk" */
     since_last_update = elapsed - p->last_change_sec;
     if ((unsigned)transferred != p->last_size) {
         p->last_change_sec = elapsed;
         p->last_size = (unsigned)transferred;
         if (since_last_update >= STALLTIME) {
             /* We "cut out" these seconds from elapsed time
              * by adjusting start time */
             p->start_sec += since_last_update;
         }
         since_last_update = 0; /* we are un-stalled now */
     }
     elapsed -= p->start_sec; /* now it's "elapsed since start" */
     if (since_last_update >= STALLTIME) {
         fprintf(stderr, "  - stalled -");
     } else if (!totalsize || !transferred || (int)elapsed < 0) {
         fprintf(stderr, " --:--:-- ETA");
     } else {
         unsigned eta, secs, hours;
         unsigned bytes;
         bytes = totalsize - beg_size;
         /* Estimated remaining time =
          * estimated_sec_to_dl_bytes - elapsed_sec =
          * bytes / average_bytes_sec_so_far - elapsed =
          * bytes / (transferred/elapsed) - elapsed =
          * bytes * elapsed / transferred - elapsed
          */
         eta = (unsigned long)bytes * elapsed / transferred - elapsed;
         /* if 32bit, can overflow ^^^^^^^^^^, but this would only show bad ETA */
         if (eta >= 1000*60*60)
             eta = 1000*60*60 - 1;
 #if 0
         /* To prevent annoying "back-and-forth" estimation jitter,
          * if new ETA is larger than the last just by a few seconds,
          * disregard it, and show last one. The end result is that
          * ETA usually only decreases, unless download slows down a lot.
          */
         if ((unsigned)(eta - p->last_eta) < 10)
             eta = p->last_eta;
         p->last_eta = eta;
 #endif
         secs = eta % 3600;
         hours = eta / 3600;
         fprintf(stderr, "%3u:%02u:%02u ETA", hours, secs / 60, secs % 60);
     }
     if (notty)
         fputc('\n', stderr);
     return notty;
 }
References buf, fprintf(), fputc, fputs, get_terminal_width(), isatty(), memset, monotonic_sec(), p, smart_ulltoa5(), STALLTIME, stderr, and STDERR_FILENO.