Fennix: Userspace/musl/src/stdio/puts.c File Reference
puts.c File Reference
#include "stdio_impl.h"
Functions
int puts (const char *s)
Function Documentation
puts()
int puts (const char * s)
Definition at line 3 of file puts.c.
 {
     int r;
     FLOCK(stdout);
     r = -(fputs(s, stdout) < 0 || putc_unlocked('\n', stdout) < 0);
     FUNLOCK(stdout);
     return r;
 }
References FLOCK, fputc(), fputs, FUNLOCK, i, putc_unlocked(), s, and stdout.
Referenced by ACTF(), add_remove_shell_main(), ask(), builtin_pwd(), cal_main(), check_all(), check_deps(), check_mail(), check_mount(), colon(), cpu_report(), cryptpw_main(), cttyhack_main(), cut_file(), date_main(), diff(), dirname_main(), display_boolean(), display_header(), display_verbose(), do_stop(), doCommands(), doit(), dumpleases_main(), encode_n_base64(), expr_main(), fatattr_main(), fdformat_main(), fdisk_main(), fetch(), fileAction(), findfs_main(), fsck_main(), fsck_minix_main(), get(), get_boot(), get_inode_common(), getenforce_main(), getopt_main(), getsebool_main(), grep_file(), header_list(), hostname_main(), httpd_main(), I_InitSquashTable(), I_InitStretchTables(), I_PrintBanner(), ipcrm_main(), ipneigh_list_or_flush(), kill_main(), list_packages(), list_table(), logical_getcwd(), login_main(), logname_main(), losetup_main(), lpd_main(), main(), makemime_main(), mesg_main(), mktemp_main(), modprobe_main(), new_password(), powertop_main(), preadfd(), print_ascii(), print_closing_wait(), print_host(), print_line(), print_login_issue(), print_matchpathcon(), print_numbered_lines(), print_serial_flags(), print_timestamp(), printenv_main(), printlim(), process_wait_result(), procps_get_maps(), ps_main(), pwd_main(), read_extended(), read_tables(), realpath_main(), recv_pack(), run_parts_main(), run_pipe(), runlevel_main(), scan_request(), sed_main(), show_help(), show_timerstats(), showkey_main(), sysctl_act_on_setting(), tar_main(), tree_print(), trim_trailing_spaces_and_print(), tsort_main(), tty_builtin(), tty_main(), tunctl_main(), uevent_main(), umaskcmd(), unzip_main(), usage(), vlock_main(), warn_geometry(), which_main(), who_main(), whoami_main(), write_block(), and writeline().