Fennix Userspace: Userspace/apps/base/busybox/mailutils/mail.h File Reference
mail.h File Reference
Data Structures
struct globals
Macros
#define G (*ptr_to_globals)
#define INIT_G()
Functions
void launch_helper (const char **argv) FAST_FUNC
void get_cred_or_die (int fd) FAST_FUNC
void send_r_n (const char *s) FAST_FUNC
char * send_mail_command (const char *fmt, const char *param) FAST_FUNC
void printbuf_base64 (const char *buf, unsigned len) FAST_FUNC
void printstr_base64 (const char *buf) FAST_FUNC
void printfile_base64 (const char *fname) FAST_FUNC
Macro Definition Documentation
G
#define G (*ptr_to_globals)
Definition at line 20 of file mail.h.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    G.opt_charset = (char *)CONFIG_FEATURE_MIME_CHARSET; \
} while (0)
Definition at line 21 of file mail.h.
Function Documentation
get_cred_or_die()
void get_cred_or_die (int fd)
Definition at line 190 of file mail.c.
 {
     if (isatty(fd)) {
         G.user = bb_ask_noecho(fd, /* timeout: */ 0, "User: ");
         G.pass = bb_ask_noecho(fd, /* timeout: */ 0, "Password: ");
     } else {
         G.user = xmalloc_reads(fd, /* maxsize: */ NULL);
         G.pass = xmalloc_reads(fd, /* maxsize: */ NULL);
     }
     if (!G.user || !*G.user || !G.pass)
         bb_simple_error_msg_and_die("no username or password");
 }
References bb_ask_noecho(), bb_simple_error_msg_and_die(), fd, G, isatty(), NULL, and xmalloc_reads().
Referenced by popmaildir_main(), and sendmail_main().
launch_helper()
void launch_helper (const char ** argv)
Definition at line 40 of file mail.c.
 {
     pid_t pid;
     struct fd_pair child_out;
     struct fd_pair child_in;
     xpiped_pair(child_out);
     xpiped_pair(child_in);
     // NB: handler must be installed before vfork
     bb_signals(0
         + (1 << SIGCHLD)
         + (1 << SIGALRM)
         , signal_handler);
     fflush_all();
     pid = xvfork();
     if (pid == 0) {
         // child
         close(child_in.wr);
         close(child_out.rd);
         xmove_fd(child_in.rd, STDIN_FILENO);
         xmove_fd(child_out.wr, STDOUT_FILENO);
         // if parent dies, get SIGTERM
 #if defined(PRCTL)
         prctl(PR_SET_PDEATHSIG, SIGTERM, 0, 0, 0);
 #elif defined(PROCCTL)
         {
             int signum = SIGTERM;
             procctl(P_PID, 0, PROC_PDEATHSIG_CTL, &signum);
         }
 #endif
         // try to execute connection helper
         // NB: SIGCHLD & SIGALRM revert to SIG_DFL on exec
         BB_EXECVP_or_die((char**)argv);
     }
     G.helper_pid = pid;
     close(child_out.wr);
     close(child_in.rd);
     xmove_fd(child_out.rd, STDIN_FILENO);
     xmove_fd(child_in.wr, STDOUT_FILENO);
     // parent goes on
 }
References argv, BB_EXECVP_or_die(), bb_signals(), close(), fflush_all(), G, P_PID, pid, PR_SET_PDEATHSIG, prctl(), fd_pair::rd, SIGALRM, SIGCHLD, signal_handler(), SIGTERM, STDIN_FILENO, STDOUT_FILENO, fd_pair::wr, xmove_fd(), xpiped_pair, and xvfork.
Referenced by popmaildir_main(), and sendmail_main().
printbuf_base64()
void printbuf_base64 (const char * buf, unsigned len)
Definition at line 177 of file mail.c.
 {
     encode_n_base64(NULL, text, len);
 }
References encode_n_base64(), NULL, and text.
Referenced by sendmail_main().
printfile_base64()
void printfile_base64 (const char * fname)
Definition at line 182 of file mail.c.
 {
     encode_n_base64(fname, NULL, 0);
 }
References encode_n_base64(), fname, and NULL.
Referenced by makemime_main().
printstr_base64()
void printstr_base64 (const char * buf)
Definition at line 172 of file mail.c.
 {
     encode_n_base64(NULL, text, strlen(text));
 }
References encode_n_base64(), NULL, strlen(), and text.
Referenced by sendmail_main().
send_mail_command()
char* send_mail_command (const char * fmt, const char * param)
Definition at line 92 of file mail.c.
 {
     char *msg;
     if (G.timeout)
         alarm(G.timeout);
     msg = (char*)fmt;
     if (fmt) {
         msg = xasprintf(fmt, param);
         send_r_n(msg);
     }
     fflush_all();
     return msg;
 }
References alarm(), fflush_all(), G, param, send_r_n(), and xasprintf().
Referenced by pop3_checkr(), and smtp_checkp().
send_r_n()
void send_r_n (const char * s)
Definition at line 85 of file mail.c.
 {
     if (G.verbose)
         bb_error_msg("send:'%s'", s);
     printf("%s\r\n", s);
 }
References bb_error_msg(), G, printf(), and s.
Referenced by send_mail_command(), and sendmail_main().