Fennix: Userspace/apps/base/bash/lib/sh/shtty.c File Reference
shtty.c File Reference
#include <shtty.h>
Functions
int ttgetattr (int fd, TTYSTRUCT *ttp)
int ttsetattr (int fd, TTYSTRUCT *ttp)
void ttsave ()
void ttrestore ()
TTYSTRUCT * ttattr (int fd)
int tt_setonechar (TTYSTRUCT *ttp)
int ttfd_onechar (int fd, TTYSTRUCT *ttp)
int ttonechar ()
int tt_setnoecho (TTYSTRUCT *ttp)
int ttfd_noecho (int fd, TTYSTRUCT *ttp)
int ttnoecho ()
int tt_seteightbit (TTYSTRUCT *ttp)
int ttfd_eightbit (int fd, TTYSTRUCT *ttp)
int tteightbit ()
int tt_setnocanon (TTYSTRUCT *ttp)
int ttfd_nocanon (int fd, TTYSTRUCT *ttp)
int ttnocanon ()
int tt_setcbreak (TTYSTRUCT *ttp)
int ttfd_cbreak (int fd, TTYSTRUCT *ttp)
int ttcbreak ()
Variables
static TTYSTRUCT ttin
static TTYSTRUCT ttout
static int ttsaved = 0
Function Documentation
tt_setcbreak()
int tt_setcbreak (TTYSTRUCT * ttp)
Definition at line 300 of file shtty.c.
 {
   if (tt_setonechar (ttp) < 0)
     return -1;
   return (tt_setnoecho (ttp));
 }
References tt_setnoecho(), and tt_setonechar().
Referenced by ttfd_cbreak().
tt_seteightbit()
int tt_seteightbit (TTYSTRUCT * ttp)
Definition at line 220 of file shtty.c.
 {
 #if defined (TERMIOS_TTY_DRIVER) || defined (TERMIO_TTY_DRIVER)
   ttp->c_iflag &= ~ISTRIP;
   ttp->c_cflag |= CS8;
   ttp->c_cflag &= ~PARENB;
 #else
   ttp->sg_flags |= ANYP;
 #endif
   return 0;
 }
References ANYP, CS8, ISTRIP, and PARENB.
Referenced by ttfd_eightbit().
tt_setnocanon()
int tt_setnocanon (TTYSTRUCT * ttp)
Definition at line 262 of file shtty.c.
 {
 #if defined (TERMIOS_TTY_DRIVER) || defined (TERMIO_TTY_DRIVER)
   ttp->c_lflag &= ~ICANON;
 #endif
   return 0;
 }
References ICANON.
Referenced by ttfd_nocanon().
tt_setnoecho()
int tt_setnoecho (TTYSTRUCT * ttp)
Definition at line 180 of file shtty.c.
 {
 #if defined (TERMIOS_TTY_DRIVER) || defined (TERMIO_TTY_DRIVER)
   ttp->c_lflag &= ~(ECHO|ECHOK|ECHONL);
 #else
   ttp->sg_flags &= ~ECHO;
 #endif
   return 0;
 }
References ECHO, ECHOK, and ECHONL.
Referenced by tt_setcbreak(), and ttfd_noecho().
tt_setonechar()
int tt_setonechar (TTYSTRUCT * ttp)
Definition at line 108 of file shtty.c.
 {
 #if defined (TERMIOS_TTY_DRIVER) || defined (TERMIO_TTY_DRIVER)
   /* XXX - might not want this -- it disables erase and kill processing. */
   ttp->c_lflag &= ~ICANON;
   ttp->c_lflag |= ISIG;
 #  ifdef IEXTEN
   ttp->c_lflag |= IEXTEN;
 #  endif
   ttp->c_iflag |= ICRNL;    /* make sure we get CR->NL on input */
   ttp->c_iflag &= ~INLCR;   /* but no NL->CR */
 #  ifdef OPOST
   ttp->c_oflag |= OPOST;
 #  endif
 #  ifdef ONLCR
   ttp->c_oflag |= ONLCR;
 #  endif
 #  ifdef OCRNL
   ttp->c_oflag &= ~OCRNL;
 #  endif
 #  ifdef ONOCR
   ttp->c_oflag &= ~ONOCR;
 #  endif
 #  ifdef ONLRET
   ttp->c_oflag &= ~ONLRET;
 #  endif
   ttp->c_cc[VMIN] = 1;
   ttp->c_cc[VTIME] = 0;
 #else
   ttp->sg_flags |= CBREAK;
 #endif
   return 0;
 }
References ICANON, ICRNL, IEXTEN, INLCR, ISIG, OCRNL, ONLCR, ONLRET, ONOCR, OPOST, VMIN, and VTIME.
Referenced by tt_setcbreak(), and ttfd_onechar().
ttattr()
TTYSTRUCT* ttattr (int fd)
Definition at line 90 of file shtty.c.
 {
   if (ttsaved == 0)
     return ((TTYSTRUCT *)0);
   if (fd == 0)
     return &ttin;
   else if (fd == 1)
     return &ttout;
   else
     return ((TTYSTRUCT *)0);
 }
References fd, ttin, ttout, ttsaved, and TTYSTRUCT.
ttcbreak()
int ttcbreak ()
Definition at line 322 of file shtty.c.
 {
   TTYSTRUCT tt;
   if (ttsaved == 0)
     return -1;
   tt = ttin;
   return (ttfd_cbreak (0, &tt));
 }
References tt, ttfd_cbreak(), ttin, ttsaved, and TTYSTRUCT.
tteightbit()
int tteightbit ()
Definition at line 247 of file shtty.c.
 {
   TTYSTRUCT tt;
   if (ttsaved == 0)
     return -1;
   tt = ttin;
   return (ttfd_eightbit (0, &tt));
 }
References tt, ttfd_eightbit(), ttin, ttsaved, and TTYSTRUCT.
ttfd_cbreak()
int ttfd_cbreak (int fd, TTYSTRUCT * ttp)
Definition at line 311 of file shtty.c.
 {
   if (tt_setcbreak (ttp) < 0)
     return -1;
   return (ttsetattr (fd, ttp));
 }
References fd, tt_setcbreak(), and ttsetattr().
Referenced by ttcbreak().
ttfd_eightbit()
int ttfd_eightbit (int fd, TTYSTRUCT * ttp)
Definition at line 236 of file shtty.c.
 {
   if (tt_seteightbit (ttp) < 0)
     return -1;
   return (ttsetattr (fd, ttp));
 }
References fd, tt_seteightbit(), and ttsetattr().
Referenced by tteightbit().
ttfd_nocanon()
int ttfd_nocanon (int fd, TTYSTRUCT * ttp)
Definition at line 274 of file shtty.c.
 {
   if (tt_setnocanon (ttp) < 0)
     return -1;
   return (ttsetattr (fd, ttp));
 }
References fd, tt_setnocanon(), and ttsetattr().
Referenced by ttnocanon().
ttfd_noecho()
int ttfd_noecho (int fd, TTYSTRUCT * ttp)
Definition at line 194 of file shtty.c.
 {
   if (tt_setnoecho (ttp) < 0)
     return -1;
   return (ttsetattr (fd, ttp));
 }
References fd, tt_setnoecho(), and ttsetattr().
Referenced by ttnoecho().
ttfd_onechar()
int ttfd_onechar (int fd, TTYSTRUCT * ttp)
Definition at line 154 of file shtty.c.
 {
   if (tt_setonechar(ttp) < 0)
     return -1;
   return (ttsetattr (fd, ttp));
 }
References fd, tt_setonechar(), and ttsetattr().
Referenced by ttonechar().
ttgetattr()
int ttgetattr (int fd, TTYSTRUCT * ttp)
Definition at line 37 of file shtty.c.
 {
 #ifdef TERMIOS_TTY_DRIVER
   return tcgetattr(fd, ttp);
 #else
 #  ifdef TERMIO_TTY_DRIVER
   return ioctl(fd, TCGETA, ttp);
 #  else
   return ioctl(fd, TIOCGETP, ttp);
 #  endif
 #endif
 }
References fd, ioctl(), TCGETA, tcgetattr(), and TIOCGETP.
Referenced by get_tty_state(), and ttsave().
ttnocanon()
int ttnocanon ()
Definition at line 285 of file shtty.c.
 {
   TTYSTRUCT tt;
   if (ttsaved == 0)
     return -1;
   tt = ttin;
   return (ttfd_nocanon (0, &tt));
 }
References tt, ttfd_nocanon(), ttin, ttsaved, and TTYSTRUCT.
ttnoecho()
int ttnoecho ()
Definition at line 205 of file shtty.c.
 {
   TTYSTRUCT tt;
   if (ttsaved == 0)
     return -1;
   tt = ttin;
   return (ttfd_noecho (0, &tt));
 }
References tt, ttfd_noecho(), ttin, ttsaved, and TTYSTRUCT.
ttonechar()
int ttonechar ()
Definition at line 165 of file shtty.c.
 {
   TTYSTRUCT tt;
   if (ttsaved == 0)
     return -1;
   tt = ttin;
   return (ttfd_onechar (0, &tt));
 }
References tt, ttfd_onechar(), ttin, ttsaved, and TTYSTRUCT.
ttrestore()
void ttrestore ()
Definition at line 79 of file shtty.c.
 {
   if (ttsaved == 0)
     return;
   ttsetattr (0, &ttin);
   ttsetattr (1, &ttout);
   ttsaved = 0;
 }
References ttin, ttout, ttsaved, and ttsetattr().
ttsave()
void ttsave ()
Definition at line 69 of file shtty.c.
 {
   if (ttsaved)
    return;
   ttgetattr (0, &ttin);
   ttgetattr (1, &ttout);
   ttsaved = 1;
 }
References ttgetattr(), ttin, ttout, and ttsaved.
ttsetattr()
int ttsetattr (int fd, TTYSTRUCT * ttp)
Definition at line 53 of file shtty.c.
 {
 #ifdef TERMIOS_TTY_DRIVER
   return tcsetattr(fd, TCSADRAIN, ttp);
 #else
 #  ifdef TERMIO_TTY_DRIVER
   return ioctl(fd, TCSETAW, ttp);
 #  else
   return ioctl(fd, TIOCSETN, ttp);
 #  endif
 #endif
 }
References fd, ioctl(), TCSADRAIN, tcsetattr(), TCSETAW, and TIOCSETN.
Referenced by set_tty_state(), ttfd_cbreak(), ttfd_eightbit(), ttfd_nocanon(), ttfd_noecho(), ttfd_onechar(), and ttrestore().
Variable Documentation
ttin
TTYSTRUCT ttin static
Definition at line 33 of file shtty.c.
Referenced by ttattr(), ttcbreak(), tteightbit(), ttnocanon(), ttnoecho(), ttonechar(), ttrestore(), and ttsave().
ttout
TTYSTRUCT ttout static
Definition at line 33 of file shtty.c.
Referenced by ttattr(), ttrestore(), and ttsave().
ttsaved
int ttsaved = 0 static
Definition at line 34 of file shtty.c.
Referenced by ttattr(), ttcbreak(), tteightbit(), ttnocanon(), ttnoecho(), ttonechar(), ttrestore(), and ttsave().