Fennix: Userspace/musl/src/linux/brk.c File Reference
brk.c File Reference
#include <unistd.h>
#include <errno.h>
#include "syscall.h"
Macros
#define _BSD_SOURCE
Functions
int brk (void *end)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file brk.c.
Function Documentation
brk()
int brk (void * end)
Definition at line 6 of file brk.c.
 {
     return __syscall_ret(-ENOMEM);
 }
References __syscall_ret(), and ENOMEM.
Referenced by __expand_heap(), __simple_malloc(), alloc_meta(), inet_pton(), and map_library().