Fennix: Userspace/musl/src/network/gethostbyaddr.c File Reference
gethostbyaddr.c File Reference
#include <netdb.h>
#include <errno.h>
#include <stdlib.h>
Macros
#define _GNU_SOURCE
Functions
struct hostent * gethostbyaddr (const void *a, socklen_t l, int af)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file gethostbyaddr.c.
Function Documentation
gethostbyaddr()
struct hostent* gethostbyaddr (const void * a, socklen_t l, int af)
Definition at line 7 of file gethostbyaddr.c.
 {
     static struct hostent *h;
     size_t size = 63;
     struct hostent *res;
     int err;
     do {
         free(h);
         h = malloc(size+=size+1);
         if (!h) {
             h_errno = NO_RECOVERY;
             return 0;
         }
         err = gethostbyaddr_r(a, l, af, h,
             (void *)(h+1), size-sizeof *h, &res, &h_errno);
     } while (err == ERANGE);
     return res;
 }
References ERANGE, err(), free, gethostbyaddr_r(), h, h_errno, l, malloc, and size.
Referenced by ipcalc_main().