Fennix: Userspace/mlibc/options/posix/generic/arpa-inet-stubs.cpp File Reference
arpa-inet-stubs.cpp File Reference
#include <arpa/inet.h>
#include <bits/ensure.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <mlibc/bitutil.hpp>
#include <mlibc/debug.hpp>
Functions
uint32_t htonl (uint32_t x)
uint16_t htons (uint16_t x)
uint32_t ntohl (uint32_t x)
uint16_t ntohs (uint16_t x)
in_addr_t inet_addr (const char *p)
char * inet_ntoa (struct in_addr addr)
int inet_aton (const char *string, struct in_addr *dest)
const char * inet_ntop (int af, const void *__restrict src, char *__restrict dst, socklen_t size)
int inet_pton (int af, const char *__restrict src, void *__restrict dst)
Variables
const struct in6_addr in6addr_any = IN6ADDR_ANY_INIT
const struct in6_addr in6addr_loopback = IN6ADDR_LOOPBACK_INIT
Function Documentation
htonl()
uint32_t htonl (uint32_t x)
Definition at line 15 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint32_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
Referenced by inet_aton(), inet_ntoa(), main(), and socket_setup().
htons()
uint16_t htons (uint16_t x)
Definition at line 22 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint16_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
Referenced by getaddrinfo(), getservbyname(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), main(), and socket_setup().
inet_addr()
in_addr_t inet_addr (const char * p)
Definition at line 47 of file arpa-inet-stubs.cpp.
{
     struct in_addr a;
     if(!inet_aton(p, &a))
         return -1;
     return a.s_addr;
 }
References inet_aton(), p, and in_addr::s_addr.
inet_aton()
int inet_aton (const char * string, struct in_addr * dest)
Definition at line 63 of file arpa-inet-stubs.cpp.
{
     int array[4];
     int i = 0;
     char *end;
     for (; i < 4; i++) {
         array[i] = strtoul(string, &end, 0);
         if (*end && *end != '.')
             return 0;
         if (!*end)
             break;
         string = end + 1;
     }
     switch (i) {
         case 0:
             dest->s_addr = htonl(array[0]);
             break;
         case 1:
             if (array[0] > 255 || array[1] > 0xffffff)
                 return 0;
             dest->s_addr = htonl((array[0] << 24) | array[1]);
             break;
         case 2:
             if (array[0] > 255 || array[1] > 255 ||
                     array[2] > 0xffff)
                 return 0;
             dest->s_addr = htonl((array[0] << 24) | (array[1] << 16) |
                 array[2]);
             break;
         case 3:
             if (array[0] > 255 || array[1] > 255 ||
                     array[2] > 255 || array[3] > 255)
                 return 0;
             dest->s_addr = htonl((array[0] << 24) | (array[1] << 16) |
                 (array[2] << 8) | array[3]);
             break;
     }
     return 1;
 }
References htonl(), i, in_addr::s_addr, and strtoul().
Referenced by inet_addr(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), and mlibc::lookup_name_hosts().
inet_ntoa()
char* inet_ntoa (struct in_addr addr)
Definition at line 53 of file arpa-inet-stubs.cpp.
{
     // string: xxx.yyy.zzz.aaa
     // 4 * 3 + 3 + 1 = 12 + 4 = 16
     thread_local static char buffer[16];
     uint32_t proper = htonl(addr.s_addr);
     snprintf(buffer, sizeof(buffer), "%d.%d.%d.%d",
         (proper >> 24) & 0xff, ((proper >> 16) & 0xff),
         (proper >> 8) & 0xff, proper & 0xff);
     return buffer;
 }
References htonl(), in_addr::s_addr, and snprintf().
inet_ntop()
const char* inet_ntop (int af, const void *__restrict src, char *__restrict dst, socklen_t size)
Definition at line 108 of file arpa-inet-stubs.cpp.
{
     auto source = reinterpret_cast<const struct in_addr*>(src);
     switch (af) {
         case AF_INET:
             if (snprintf(dst, size, "%d.%d.%d.%d",
                         source->s_addr & 0xff,
                         (source->s_addr & 0xffff) >> 8,
                         (source->s_addr & 0xffffff) >> 16,
                         source->s_addr >> 24) < (int)size)
                 return dst;
             break;
         case AF_INET6:
             mlibc::infoLogger() << "inet_pton: ipv6 is not implemented!" << frg::endlog;
             /* fallthrough */
         default:
             errno = EAFNOSUPPORT;
             return NULL;
     }
     errno = ENOSPC;
     return NULL;
 }
References AF_INET, AF_INET6, EAFNOSUPPORT, ENOSPC, errno, mlibc::infoLogger, int, NULL, size, and snprintf().
Referenced by getnameinfo(), mlibc::lookup_addr_dns(), mlibc::lookup_addr_hosts(), and main().
inet_pton()
int inet_pton (int af, const char *__restrict src, void *__restrict dst)
Definition at line 131 of file arpa-inet-stubs.cpp.
{
     switch (af) {
         case AF_INET: {
             uint8_t array[4] = {};
             for (int i = 0; i < 4; i++) {
                 char *end;
                 long int value = strtol(src, &end, 10);
                 if (value > 255)
                     return 0;
                 if (*end != '\0' && *end != '.')
                     return 0;
                 src = end + 1;
                 array[i] = value;
             }
             auto addr = reinterpret_cast<struct in_addr*>(dst);
             memcpy(&addr->s_addr, array, 4);
             break;
         }
         case AF_INET6:
             mlibc::infoLogger() << "inet_pton: ipv6 is not implemented!" << frg::endlog;
             /* fallthrough */
         default:
             errno = EAFNOSUPPORT;
             return -1;
     }
     return 1;
 }
References AF_INET, AF_INET6, EAFNOSUPPORT, errno, i, mlibc::infoLogger, memcpy, strtol(), and value.
Referenced by mlibc::lookup_name_ip(), and main().
ntohl()
uint32_t ntohl (uint32_t x)
Definition at line 29 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint32_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
ntohs()
uint16_t ntohs (uint16_t x)
Definition at line 36 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint16_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
Referenced by getservbyport(), mlibc::lookup_addr_dns(), and mlibc::lookup_name_dns().
Variable Documentation
in6addr_any
const struct in6_addr in6addr_any = IN6ADDR_ANY_INIT
Definition at line 1 of file arpa-inet-stubs.cpp.
in6addr_loopback
const struct in6_addr in6addr_loopback = IN6ADDR_LOOPBACK_INIT
Definition at line 1 of file arpa-inet-stubs.cpp.