Fennix: Userspace/apps/base/bash/lib/readline/histsearch.c File Reference
histsearch.c File Reference
#include <stdio.h>
#include "ansi_stdlib.h"
#include "history.h"
#include "histlib.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define NEXT_LINE() do { if (reverse) i--; else i++; } while (0)
Functions
static int history_search_internal (const char *, int, int)
int _hs_history_patsearch (const char *string, int direction, int flags)
int history_search (const char *string, int direction)
int history_search_prefix (const char *string, int direction)
int history_search_pos (const char *string, int dir, int pos)
Variables
char * history_search_delimiter_chars = (char *)NULL
Macro Definition Documentation
NEXT_LINE
#define NEXT_LINE () do { if (reverse) i--; else i++; } while (0)
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file histsearch.c.
Function Documentation
_hs_history_patsearch()
int _hs_history_patsearch (const char * string, int direction, int flags)
Definition at line 199 of file histsearch.c.
 {
   char *pat;
   size_t len, start;
   int ret, unescaped_backslash;
 #if defined (HAVE_FNMATCH)
   /* Assume that the string passed does not have a leading `^' and any
      anchored search request is captured in FLAGS */
   len = strlen (string);
   ret = len - 1;
   /* fnmatch is required to reject a pattern that ends with an unescaped
      backslash */
   if (unescaped_backslash = (string[ret] == '\\'))
     {
       while (ret > 0 && string[--ret] == '\\')
     unescaped_backslash = 1 - unescaped_backslash;
     }
   if (unescaped_backslash)
     return -1;
   pat = (char *)xmalloc (len + 3);
   /* If the search string is not anchored, we'll be calling fnmatch (assuming
      we have it). Prefix a `*' to the front of the search string so we search
      anywhere in the line. */
   if ((flags & ANCHORED_SEARCH) == 0 && string[0] != '*')
     {
       pat[0] = '*';
       start = 1;
       len++;
     }
   else
     {
       start = 0;
     }
   /* Attempt to reduce the number of searches by tacking a `*' onto the end
      of a pattern that doesn't have one.  Assume a pattern that ends in a
      backslash contains an even number of trailing backslashes; we check
      above */
   strcpy (pat + start, string);
   if (pat[len - 1] != '*')
     {
       pat[len] = '*';       /* XXX */
       pat[len+1] = '\0';
     }
 #else
   pat = string;
 #endif
   ret = history_search_internal (pat, direction, flags|PATTERN_SEARCH);
   if (pat != string)
     xfree (pat);
   return ret;
 }
References ANCHORED_SEARCH, flags, history_search_internal(), len, pat, PATTERN_SEARCH, start, strcpy, string, strlen, xfree, and xmalloc.
Referenced by noninc_search_from_pos().
history_search()
int history_search (const char * string, int direction)
Definition at line 257 of file histsearch.c.
 {
   return (history_search_internal (string, direction, NON_ANCHORED_SEARCH));
 }
References history_search_internal(), and NON_ANCHORED_SEARCH.
Referenced by get_history_event(), history_search_pos(), and noninc_search_from_pos().
history_search_internal()
static int history_search_internal (const char * string, int direction, int flags) static
Definition at line 67 of file histsearch.c.
 {
   register int i, reverse;
   register char *line;
   register int line_index;
   int string_len, anchored, patsearch;
   HIST_ENTRY **the_history;     /* local */
   i = history_offset;
   reverse = (direction < 0);
   anchored = (flags & ANCHORED_SEARCH);
 #if defined (HAVE_FNMATCH)
   patsearch = (flags & PATTERN_SEARCH);
 #else
   patsearch = 0;
 #endif
   /* Take care of trivial cases first. */
   if (string == 0 || *string == '\0')
     return (-1);
   if (!history_length || ((i >= history_length) && !reverse))
     return (-1);
   if (reverse && (i >= history_length))
     i = history_length - 1;
 #define NEXT_LINE() do { if (reverse) i--; else i++; } while (0)
   the_history = history_list ();
   string_len = strlen (string);
   while (1)
     {
       /* Search each line in the history list for STRING. */
       /* At limit for direction? */
       if ((reverse && i < 0) || (!reverse && i == history_length))
     return (-1);
       line = the_history[i]->line;
       line_index = strlen (line);
       /* If STRING is longer than line, no match. */
       if (patsearch == 0 && (string_len > line_index))
     {
       NEXT_LINE ();
       continue;
     }
       /* Handle anchored searches first. */
       if (anchored == ANCHORED_SEARCH)
     {
 #if defined (HAVE_FNMATCH)
       if (patsearch)
         {
           if (fnmatch (string, line, 0) == 0)
         {
           history_offset = i;
           return (0);
         }
         }
       else
 #endif
       if (STREQN (string, line, string_len))
         {
           history_offset = i;
           return (0);
         }
       NEXT_LINE ();
       continue;
     }
       /* Do substring search. */
       if (reverse)
     {
       line_index -= (patsearch == 0) ? string_len : 1;
       while (line_index >= 0)
         {
 #if defined (HAVE_FNMATCH)
           if (patsearch)
         {
           if (fnmatch (string, line + line_index, 0) == 0)
             {
               history_offset = i;
               return (line_index);
             }
         }
           else
 #endif
           if (STREQN (string, line + line_index, string_len))
         {
           history_offset = i;
           return (line_index);
         }
           line_index--;
         }
     }
       else
     {
       register int limit;
       limit = line_index - string_len + 1;
       line_index = 0;
       while (line_index < limit)
         {
 #if defined (HAVE_FNMATCH)
           if (patsearch)
         {
           if (fnmatch (string, line + line_index, 0) == 0)
             {
               history_offset = i;
               return (line_index);
             }
         }
           else
 #endif
           if (STREQN (string, line + line_index, string_len))
         {
           history_offset = i;
           return (line_index);
         }
           line_index++;
         }
     }
       NEXT_LINE ();
     }
 }
References ANCHORED_SEARCH, flags, fnmatch(), history_length, history_list(), history_offset, i, limit(), _hist_entry::line, line, NEXT_LINE, PATTERN_SEARCH, reverse(), STREQN, strlen, and the_history.
Referenced by _hs_history_patsearch(), history_search(), and history_search_prefix().
history_search_pos()
int history_search_pos (const char * string, int dir, int pos)
Definition at line 273 of file histsearch.c.
 {
   int ret, old;
   old = where_history ();
   history_set_pos (pos);
   if (history_search (string, dir) == -1)
     {
       history_set_pos (old);
       return (-1);
     }
   ret = where_history ();
   history_set_pos (old);
   return ret;
 }
References dir, history_search(), history_set_pos(), old, pos, and where_history().
history_search_prefix()
int history_search_prefix (const char * string, int direction)
Definition at line 264 of file histsearch.c.
 {
   return (history_search_internal (string, direction, ANCHORED_SEARCH));
 }
References ANCHORED_SEARCH, and history_search_internal().
Referenced by get_history_event(), and noninc_search_from_pos().
Variable Documentation
history_search_delimiter_chars
char* history_search_delimiter_chars = (char *)NULL
Definition at line 52 of file histsearch.c.
Referenced by get_history_event().