Fennix: Userspace/apps/base/busybox/coreutils/od_bloaty.c File Reference
od_bloaty.c File Reference
#include "common_bufsiz.h"
Data Structures
struct tspec
struct ERR_width_bytes_has_bad_size
struct globals
Macros
#define assert(a) ((void)0)
#define OD_GETOPT32()
#define ISPRINT(c) (((c) >= ' ') && (c) < 0x7f)
#define xstrtooff_sfx xstrtoul_sfx
#define DEFAULT_BYTES_PER_BLOCK 16
#define FLT_DIG 7
#define DBL_DIG 15
#define LDBL_DIG DBL_DIG
#define address_base_char G.address_fmt[sizeof(G.address_fmt)-3]
#define address_pad_len_char G.address_fmt[2]
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define MAX_INTEGRAL_TYPE_SIZE sizeof(ulonglong_t)
#define MAX_FP_TYPE_SIZE sizeof(longdouble_t)
#define print_long print_int
#define print_long_long print_long
#define ISPEC_TO_FORMAT(Spec, Min_format, Long_format, Max_format)
#define FMT_BYTES_ALLOCATED 9
Typedefs
typedef long double longdouble_t
typedef unsigned long long ulonglong_t
typedef long long llong
typedef void FN_format_address(off_t address, char c)
Enumerations
enum {
OPT_A = 1 << 0 , OPT_N = 1 << 1 , OPT_a = 1 << 2 , OPT_b = 1 << 3 ,
OPT_c = 1 << 4 , OPT_d = 1 << 5 , OPT_f = 1 << 6 , OPT_h = 1 << 7 ,
OPT_i = 1 << 8 , OPT_j = 1 << 9 , OPT_l = 1 << 10 , OPT_o = 1 << 11 ,
OPT_t = 1 << 12 , OPT_v = 1 << 13 , OPT_x = 1 << 14 , OPT_s = 1 << 15 ,
OPT_S = 1 << 16 , OPT_w = 1 << 17 , OPT_traditional = (1 << 18) * ENABLE_LONG_OPTS
}
enum size_spec {
NO_SIZE , CHAR , SHORT , INT ,
LONG , LONG_LONG , FLOAT_SINGLE , FLOAT_DOUBLE ,
FLOAT_LONG_DOUBLE , N_SIZE_SPECS
}
enum output_format {
SIGNED_DECIMAL , UNSIGNED_DECIMAL , OCTAL , HEXADECIMAL ,
FLOATING_POINT , NAMED_CHARACTER , CHARACTER
}
enum { G_pseudo_offset = 0 }
Functions
static unsigned gcd (unsigned u, unsigned v)
static unsigned lcm (unsigned u, unsigned v)
static void print_s_char (size_t n_bytes, const char *block, const char *fmt_string)
static void print_char (size_t n_bytes, const char *block, const char *fmt_string)
static void print_s_short (size_t n_bytes, const char *block, const char *fmt_string)
static void print_short (size_t n_bytes, const char *block, const char *fmt_string)
static void print_int (size_t n_bytes, const char *block, const char *fmt_string)
static void print_float (size_t n_bytes, const char *block, const char *fmt_string)
static void print_double (size_t n_bytes, const char *block, const char *fmt_string)
static void print_long_double (size_t n_bytes, const char *block, const char *fmt_string)
static void print_named_ascii (size_t n_bytes, const char *block, const char *unused_fmt_string UNUSED_PARAM)
static void print_ascii (size_t n_bytes, const char *block, const char *unused_fmt_string UNUSED_PARAM)
static void open_next_file (void)
static void check_and_close (void)
static NOINLINE const char * decode_one_format (const char *s_orig, const char *s, struct tspec *tspec)
static void decode_format_string (const char *s)
static void skip (off_t n_skip)
static void format_address_none (off_t address UNUSED_PARAM, char c UNUSED_PARAM)
static void format_address_std (off_t address, char c)
static void dump_hexl_mode_trailer (size_t n_bytes, const char *block)
static void write_block (off_t current_offset, size_t n_bytes, const char *prev_block, const char *curr_block)
static void read_block (size_t n, char *block, size_t *n_bytes_in_buffer)
static int get_lcm (void)
static void dump (off_t current_offset, off_t end_offset)
static void dump_strings (off_t address, off_t end_offset)
int od_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const uint8_t bytes_to_oct_digits[] ALIGN1
struct globals FIX_ALIASING
Data Structure Documentation
ERR_width_bytes_has_bad_size
struct ERR_width_bytes_has_bad_size
Definition at line 174 of file od_bloaty.c.
Data Fields
char ERR_width_bytes_has_bad_size[ARRAY_SIZE(width_bytes)==N_SIZE_SPECS ? 1 :-1]
Macro Definition Documentation
address_base_char
#define address_base_char G.address_fmt[sizeof(G.address_fmt)-3]
Definition at line 218 of file od_bloaty.c.
address_pad_len_char
#define address_pad_len_char G.address_fmt[2]
Definition at line 220 of file od_bloaty.c.
assert
#define assert (a) ((void)0)
Definition at line 24 of file od_bloaty.c.
DBL_DIG
#define DBL_DIG 15
Definition at line 96 of file od_bloaty.c.
DEFAULT_BYTES_PER_BLOCK
#define DEFAULT_BYTES_PER_BLOCK 16
Definition at line 87 of file od_bloaty.c.
FLT_DIG
#define FLT_DIG 7
Definition at line 91 of file od_bloaty.c.
FMT_BYTES_ALLOCATED
#define FMT_BYTES_ALLOCATED 9
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 225 of file od_bloaty.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    BUILD_BUG_ON(sizeof(G) > COMMON_BUFSIZE); \
    G.bytes_per_block = 32; \
    strcpy(G.address_fmt, "%0n"OFF_FMT"xc"); \
} while (0)
Definition at line 226 of file od_bloaty.c.
ISPEC_TO_FORMAT
#define ISPEC_TO_FORMAT (Spec, Min_format, Long_format, Max_format)
Value:
    ((Spec) == LONG_LONG ? (Max_format) \
    : ((Spec) == LONG ? (Long_format) : (Min_format)))
ISPRINT
#define ISPRINT (c) (((c) >= ' ') && (c) < 0x7f)
Definition at line 74 of file od_bloaty.c.
LDBL_DIG
#define LDBL_DIG DBL_DIG
Definition at line 101 of file od_bloaty.c.
MAX_FP_TYPE_SIZE
#define MAX_FP_TYPE_SIZE sizeof(longdouble_t)
Definition at line 251 of file od_bloaty.c.
MAX_INTEGRAL_TYPE_SIZE
#define MAX_INTEGRAL_TYPE_SIZE sizeof(ulonglong_t)
Definition at line 234 of file od_bloaty.c.
OD_GETOPT32
#define OD_GETOPT32 ()
Value:
    getopt32long(argv, \
    "A:N:abcdfhij:lot:*vxsS:w:+:", od_longopts, \
    /* -w with optional param */ \
    /* -S was -s and also had optional parameter */ \
    /* but in coreutils 6.3 it was renamed and now has */ \
    /* _mandatory_ parameter */ \
    &str_A, &str_N, &str_j, &lst_t, &str_S, &G.bytes_per_block)
Definition at line 64 of file od_bloaty.c.
print_long
#define print_long print_int
Definition at line 335 of file od_bloaty.c.
print_long_long
#define print_long_long print_long
Definition at line 350 of file od_bloaty.c.
xstrtooff_sfx
#define xstrtooff_sfx xstrtoul_sfx
Definition at line 83 of file od_bloaty.c.
Typedef Documentation
FN_format_address
typedef void FN_format_address(off_t address, char c)
Definition at line 848 of file od_bloaty.c.
llong
typedef long long llong
Definition at line 78 of file od_bloaty.c.
longdouble_t
typedef long double longdouble_t
Definition at line 76 of file od_bloaty.c.
ulonglong_t
typedef unsigned long long ulonglong_t
Definition at line 77 of file od_bloaty.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_A
OPT_N
OPT_a
OPT_b
OPT_c
OPT_d
OPT_f
OPT_h
OPT_i
OPT_j
OPT_l
OPT_o
OPT_t
OPT_v
OPT_x
OPT_s
OPT_S
OPT_w
OPT_traditional
Definition at line 39 of file od_bloaty.c.
      {
     OPT_A = 1 << 0,
     OPT_N = 1 << 1,
     OPT_a = 1 << 2,
     OPT_b = 1 << 3,
     OPT_c = 1 << 4,
     OPT_d = 1 << 5,
     OPT_f = 1 << 6,
     OPT_h = 1 << 7,
     OPT_i = 1 << 8,
     OPT_j = 1 << 9,
     OPT_l = 1 << 10,
     OPT_o = 1 << 11,
     OPT_t = 1 << 12,
     /* When zero and two or more consecutive blocks are equal, format
        only the first block and output an asterisk alone on the following
        line to indicate that identical blocks have been elided: */
     OPT_v = 1 << 13,
     OPT_x = 1 << 14,
     OPT_s = 1 << 15,
     OPT_S = 1 << 16,
     OPT_w = 1 << 17,
     OPT_traditional = (1 << 18) * ENABLE_LONG_OPTS,
 };
anonymous enum
anonymous enum
Enumerator
G_pseudo_offset
Definition at line 223 of file od_bloaty.c.
 { G_pseudo_offset = 0 };
output_format
enum output_format
Enumerator
SIGNED_DECIMAL
UNSIGNED_DECIMAL
OCTAL
HEXADECIMAL
FLOATING_POINT
NAMED_CHARACTER
CHARACTER
Definition at line 117 of file od_bloaty.c.
                    {
     SIGNED_DECIMAL,
     UNSIGNED_DECIMAL,
     OCTAL,
     HEXADECIMAL,
     FLOATING_POINT,
     NAMED_CHARACTER,
     CHARACTER
 };
size_spec
enum size_spec
Enumerator
NO_SIZE
CHAR
SHORT
INT
LONG
LONG_LONG
FLOAT_SINGLE
FLOAT_DOUBLE
FLOAT_LONG_DOUBLE
N_SIZE_SPECS
Definition at line 104 of file od_bloaty.c.
                {
     NO_SIZE,
     CHAR,
     SHORT,
     INT,
     LONG,
     LONG_LONG,
     FLOAT_SINGLE,
     FLOAT_DOUBLE,
     FLOAT_LONG_DOUBLE,
     N_SIZE_SPECS
 };
Function Documentation
check_and_close()
static void check_and_close (void) static
Definition at line 524 of file od_bloaty.c.
 {
     if (G.in_stream) {
         if (ferror(G.in_stream))    {
             bb_error_msg("%s: read error", (G.in_stream == stdin)
                     ? bb_msg_standard_input
                     : G.file_list[-1]
             );
             G.exit_code = 1;
         }
         fclose_if_not_stdin(G.in_stream);
         G.in_stream = NULL;
     }
     if (ferror(stdout)) {
         bb_simple_error_msg_and_die(bb_msg_write_error);
     }
 }
References bb_error_msg(), bb_msg_write_error, bb_simple_error_msg_and_die(), fclose_if_not_stdin(), ferror, G, NULL, stdin, and stdout.
Referenced by dump(), dump_strings(), read_block(), and skip().
decode_format_string()
static void decode_format_string (const char * s) static
Definition at line 760 of file od_bloaty.c.
 {
     const char *s_orig = s;
     while (*s != '\0') {
         struct tspec tspec;
         const char *next;
         next = decode_one_format(s_orig, s, &tspec);
         assert(s != next);
         s = next;
         G.spec = xrealloc_vector(G.spec, 4, G.n_specs);
         memcpy(&G.spec[G.n_specs], &tspec, sizeof(G.spec[0]));
         G.n_specs++;
     }
 }
References assert, decode_one_format(), G, memcpy, next, s, and xrealloc_vector.
decode_one_format()
static NOINLINE const char* decode_one_format (const char * s_orig, const char * s, struct tspec * tspec) static
Definition at line 558 of file od_bloaty.c.
 {
     enum size_spec size_spec;
     unsigned size;
     enum output_format fmt;
     const char *p;
     char *end;
     char *fmt_string = NULL;
     void (*print_function) (size_t, const char *, const char *);
     unsigned c;
     unsigned field_width = 0;
     int pos;
     switch (*s) {
     case 'd':
     case 'o':
     case 'u':
     case 'x': {
         static const char CSIL[] ALIGN1 = "CSIL";
         c = *s++;
         p = strchr(CSIL, *s);
         /* if *s == NUL, p != NULL! Testcase: "od -tx" */
         if (!p || *p == '\0') {
             size = sizeof(int);
             if (isdigit(s[0])) {
                 size = bb_strtou(s, &end, 0);
                 if (errno == ERANGE
                  || MAX_INTEGRAL_TYPE_SIZE < size
                  || integral_type_size[size] == NO_SIZE
                 ) {
                     bb_error_msg_and_die("invalid type string '%s'; "
                         "%u-byte %s type is not supported",
                         s_orig, size, "integral");
                 }
                 s = end;
             }
         } else {
             static const uint8_t CSIL_sizeof[4] = {
                 sizeof(char),
                 sizeof(short),
                 sizeof(int),
                 sizeof(long),
             };
             size = CSIL_sizeof[p - CSIL];
             s++; /* skip C/S/I/L */
         }
 #define ISPEC_TO_FORMAT(Spec, Min_format, Long_format, Max_format) \
     ((Spec) == LONG_LONG ? (Max_format) \
     : ((Spec) == LONG ? (Long_format) : (Min_format)))
 #define FMT_BYTES_ALLOCATED 9
         size_spec = integral_type_size[size];
         {
             static const char doux[] ALIGN1 = "doux";
             static const char doux_fmt_letter[][4] = {
                 "lld", "llo", "llu", "llx"
             };
             static const enum output_format doux_fmt[] = {
                 SIGNED_DECIMAL,
                 OCTAL,
                 UNSIGNED_DECIMAL,
                 HEXADECIMAL,
             };
             static const uint8_t *const doux_bytes_to_XXX[] = {
                 bytes_to_signed_dec_digits,
                 bytes_to_oct_digits,
                 bytes_to_unsigned_dec_digits,
                 bytes_to_hex_digits,
             };
             static const char doux_fmtstring[][sizeof(" %%0%u%s")] ALIGN1 = {
                 " %%%u%s",
                 " %%0%u%s",
                 " %%%u%s",
                 " %%0%u%s",
             };
             pos = strchr(doux, c) - doux;
             fmt = doux_fmt[pos];
             field_width = doux_bytes_to_XXX[pos][size];
             p = doux_fmt_letter[pos] + 2;
             if (size_spec == LONG) p--;
             if (size_spec == LONG_LONG) p -= 2;
             fmt_string = xasprintf(doux_fmtstring[pos], field_width, p);
         }
         switch (size_spec) {
         case CHAR:
             print_function = (fmt == SIGNED_DECIMAL
                     ? print_s_char
                     : print_char);
             break;
         case SHORT:
             print_function = (fmt == SIGNED_DECIMAL
                     ? print_s_short
                     : print_short);
             break;
         case INT:
             print_function = print_int;
             break;
         case LONG:
             print_function = print_long;
             break;
         default: /* case LONG_LONG: */
             print_function = print_long_long;
             break;
         }
         break;
     }
     case 'f': {
         static const char FDL[] ALIGN1 = "FDL";
         fmt = FLOATING_POINT;
         ++s;
         p = strchr(FDL, *s);
         if (!p || *p == '\0') {
             size = sizeof(double);
             if (isdigit(s[0])) {
                 size = bb_strtou(s, &end, 0);
                 if (errno == ERANGE || size > MAX_FP_TYPE_SIZE
                  || fp_type_size[size] == NO_SIZE
                 ) {
                     bb_error_msg_and_die("invalid type string '%s'; "
                         "%u-byte %s type is not supported",
                         s_orig, size, "floating point");
                 }
                 s = end;
             }
         } else {
             static const uint8_t FDL_sizeof[] = {
                 sizeof(float),
                 sizeof(double),
                 sizeof(longdouble_t),
             };
             size = FDL_sizeof[p - FDL];
             s++; /* skip F/D/L */
         }
         size_spec = fp_type_size[size];
         switch (size_spec) {
         case FLOAT_SINGLE:
             print_function = print_float;
             field_width = FLT_DIG + 8;
             /* Don't use %#e; not all systems support it.  */
             fmt_string = xasprintf(" %%%d.%de", field_width, FLT_DIG);
             break;
         case FLOAT_DOUBLE:
             print_function = print_double;
             field_width = DBL_DIG + 8;
             fmt_string = xasprintf(" %%%d.%de", field_width, DBL_DIG);
             break;
         default: /* case FLOAT_LONG_DOUBLE: */
             print_function = print_long_double;
             field_width = LDBL_DIG + 8;
             fmt_string = xasprintf(" %%%d.%dLe", field_width, LDBL_DIG);
             break;
         }
         break;
     }
     case 'a':
         ++s;
         fmt = NAMED_CHARACTER;
         size_spec = CHAR;
         print_function = print_named_ascii;
         field_width = 3;
         break;
     case 'c':
         ++s;
         fmt = CHARACTER;
         size_spec = CHAR;
         print_function = print_ascii;
         field_width = 3;
         break;
     default:
         bb_error_msg_and_die("invalid character '%c' "
                 "in type string '%s'", *s, s_orig);
     }
     tspec->size = size_spec;
     tspec->fmt = fmt;
     tspec->print_function = print_function;
     tspec->fmt_string = fmt_string;
     tspec->field_width = field_width;
     tspec->hexl_mode_trailer = (*s == 'z');
     if (tspec->hexl_mode_trailer)
         s++;
     return s;
 }
References ALIGN1, bb_error_msg_and_die(), bb_strtou(), c, CHAR, CHARACTER, DBL_DIG, end, ERANGE, errno, tspec::field_width, FLOAT_DOUBLE, FLOAT_SINGLE, FLOATING_POINT, FLT_DIG, tspec::fmt, tspec::fmt_string, HEXADECIMAL, tspec::hexl_mode_trailer, INT, isdigit, LDBL_DIG, LONG, LONG_LONG, MAX_FP_TYPE_SIZE, MAX_INTEGRAL_TYPE_SIZE, NAMED_CHARACTER, NO_SIZE, NULL, OCTAL, p, pos, print_ascii(), print_char(), print_double(), print_float(), tspec::print_function, print_int(), print_long, print_long_double(), print_long_long, print_named_ascii(), print_s_char(), print_s_short(), print_short(), s, SHORT, SIGNED_DECIMAL, size, tspec::size, strchr(), UNSIGNED_DECIMAL, Module::void(), and xasprintf().
Referenced by decode_format_string().
dump()
static void dump (off_t current_offset, off_t end_offset) static
Definition at line 994 of file od_bloaty.c.
 {
     char *block[2];
     int idx;
     size_t n_bytes_read;
     block[0] = xmalloc(2 * G.bytes_per_block);
     block[1] = block[0] + G.bytes_per_block;
     idx = 0;
     if (option_mask32 & OPT_N) {
         while (1) {
             size_t n_needed;
             if (current_offset >= end_offset) {
                 n_bytes_read = 0;
                 break;
             }
             n_needed = MIN(end_offset - current_offset, (off_t) G.bytes_per_block);
             read_block(n_needed, block[idx], &n_bytes_read);
             if (n_bytes_read < G.bytes_per_block)
                 break;
             assert(n_bytes_read == G.bytes_per_block);
             write_block(current_offset, n_bytes_read, block[idx ^ 1], block[idx]);
             current_offset += n_bytes_read;
             idx ^= 1;
         }
     } else {
         while (1) {
             read_block(G.bytes_per_block, block[idx], &n_bytes_read);
             if (n_bytes_read < G.bytes_per_block)
                 break;
             assert(n_bytes_read == G.bytes_per_block);
             write_block(current_offset, n_bytes_read, block[idx ^ 1], block[idx]);
             current_offset += n_bytes_read;
             idx ^= 1;
         }
     }
     if (n_bytes_read > 0) {
         int l_c_m;
         size_t bytes_to_write;
         l_c_m = get_lcm();
         /* Make bytes_to_write the smallest multiple of l_c_m that
            is at least as large as n_bytes_read.  */
         bytes_to_write = l_c_m * ((n_bytes_read + l_c_m - 1) / l_c_m);
         memset(block[idx] + n_bytes_read, 0, bytes_to_write - n_bytes_read);
         write_block(current_offset, bytes_to_write,
                 block[idx ^ 1], block[idx]);
         current_offset += n_bytes_read;
     }
     G.format_address(current_offset, '\n');
     if ((option_mask32 & OPT_N) && current_offset >= end_offset)
         check_and_close();
     free(block[0]);
 }
References assert, check_and_close(), free, G, get_lcm(), idx, memset, MIN, off_t, OPT_N, option_mask32, read_block(), write_block(), and xmalloc.
Referenced by sendmail_main(), and setpriv_main().
dump_hexl_mode_trailer()
static void dump_hexl_mode_trailer (size_t n_bytes, const char * block) static
Definition at line 882 of file od_bloaty.c.
 {
     fputs_stdout("  >");
     while (n_bytes--) {
         unsigned c = *(unsigned char *) block++;
         c = (ISPRINT(c) ? c : '.');
         putchar(c);
     }
     putchar('<');
 }
References c, fputs_stdout(), ISPRINT, and putchar.
Referenced by write_block().
dump_strings()
static void dump_strings (off_t address, off_t end_offset) static
Definition at line 1077 of file od_bloaty.c.
 {
     unsigned bufsize = MAX(100, G.string_min);
     unsigned char *buf = xmalloc(bufsize);
     while (1) {
         size_t i;
         int c;
         /* See if the next 'G.string_min' chars are all printing chars.  */
  tryline:
         if ((option_mask32 & OPT_N) && (end_offset - G.string_min <= address))
             break;
         i = 0;
         while (!(option_mask32 & OPT_N) || address < end_offset) {
             if (i == bufsize) {
                 bufsize += bufsize/8;
                 buf = xrealloc(buf, bufsize);
             }
             while (G.in_stream) { /* !EOF */
                 c = fgetc(G.in_stream);
                 if (c != EOF)
                     goto got_char;
                 check_and_close();
                 open_next_file();
             }
             /* EOF */
             goto ret;
  got_char:
             address++;
             if (!c)
                 break;
             if (!ISPRINT(c))
                 goto tryline;   /* It isn't; give up on this string.  */
             buf[i++] = c;       /* String continues; store it all.  */
         }
         if (i < G.string_min)       /* Too short! */
             goto tryline;
         /* If we get here, the string is all printable and NUL-terminated */
         buf[i] = 0;
         G.format_address(address - i - 1, ' ');
         for (i = 0; (c = buf[i]); i++) {
             switch (c) {
             case '\007': fputs_stdout("\\a"); break;
             case '\b': fputs_stdout("\\b"); break;
             case '\f': fputs_stdout("\\f"); break;
             case '\n': fputs_stdout("\\n"); break;
             case '\r': fputs_stdout("\\r"); break;
             case '\t': fputs_stdout("\\t"); break;
             case '\v': fputs_stdout("\\v"); break;
             default: putchar(c);
             }
         }
         putchar('\n');
     }
     /* We reach this point only if we search through
        (max_bytes_to_format - G.string_min) bytes before reaching EOF.  */
     check_and_close();
  ret:
     free(buf);
 }
References buf, c, check_and_close(), EOF, fgetc, fputs_stdout(), free, G, i, ISPRINT, MAX, open_next_file(), OPT_N, option_mask32, putchar, xmalloc, and xrealloc.
format_address_none()
static void format_address_none (off_t address UNUSED_PARAM, char c UNUSED_PARAM) static
Definition at line 851 of file od_bloaty.c.
 {
 }
format_address_std()
static void format_address_std (off_t address, char c) static
Definition at line 856 of file od_bloaty.c.
 {
     /* Corresponds to 'c' */
     G.address_fmt[sizeof(G.address_fmt)-2] = c;
     printf(G.address_fmt, address);
 }
References c, G, and printf.
gcd()
static unsigned gcd (unsigned u, unsigned v) static
Definition at line 261 of file od_bloaty.c.
 {
     unsigned t;
     while (v != 0) {
         t = u % v;
         u = v;
         v = t;
     }
     return u;
 }
References t.
Referenced by lcm().
get_lcm()
static int get_lcm (void) static
Definition at line 973 of file od_bloaty.c.
 {
     size_t i;
     int l_c_m = 1;
     for (i = 0; i < G.n_specs; i++)
         l_c_m = lcm(l_c_m, width_bytes[(int) G.spec[i].size]);
     return l_c_m;
 }
References G, i, and lcm().
Referenced by dump().
lcm()
static unsigned lcm (unsigned u, unsigned v) static
Definition at line 274 of file od_bloaty.c.
{
     unsigned t = gcd(u, v);
     if (t == 0)
         return 0;
     return u * v / t;
 }
References gcd(), and t.
Referenced by get_lcm().
od_main()
int od_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1182 of file od_bloaty.c.
 {
 #if ENABLE_LONG_OPTS
     static const char od_longopts[] ALIGN1 =
         "skip-bytes\0"        Required_argument "j"
         "address-radix\0"     Required_argument "A"
         "read-bytes\0"        Required_argument "N"
         "format\0"            Required_argument "t"
         "output-duplicates\0" No_argument       "v"
         /* Yes, it's true: -S NUM, but --strings[=NUM]!
          * that is, NUM is mandatory for -S but optional for --strings!
          */
         "strings\0"           Optional_argument "S"
         "width\0"             Optional_argument "w"
         "traditional\0"       No_argument       "\xff"
         ;
 #endif
     const char *str_A, *str_N, *str_j, *str_S = "3";
     llist_t *lst_t = NULL;
     unsigned opt;
     int l_c_m;
     /* The number of input bytes to skip before formatting and writing.  */
     off_t n_bytes_to_skip = 0;
     /* The offset of the first byte after the last byte to be formatted.  */
     off_t end_offset = 0;
     /* The maximum number of bytes that will be formatted.  */
     off_t max_bytes_to_format = 0;
     INIT_G();
     /*G.spec = NULL; - already is */
     G.format_address = format_address_std;
     address_base_char = 'o';
     address_pad_len_char = '7';
     /* Parse command line */
     opt = OD_GETOPT32();
     argv += optind;
     if (opt & OPT_A) {
         static const char doxn[] ALIGN1 = "doxn";
         static const char doxn_address_base_char[] ALIGN1 = {
             'u', 'o', 'x', /* '?' fourth one is not important */
         };
         static const uint8_t doxn_address_pad_len_char[] ALIGN1 = {
             '7', '7', '6', /* '?' */
         };
         char *p;
         int pos;
         p = strchr(doxn, str_A[0]);
         if (!p)
             bb_error_msg_and_die("bad output address radix "
                 "'%c' (must be [doxn])", str_A[0]);
         pos = p - doxn;
         if (pos == 3) G.format_address = format_address_none;
         address_base_char = doxn_address_base_char[pos];
         address_pad_len_char = doxn_address_pad_len_char[pos];
     }
     if (opt & OPT_N) {
         max_bytes_to_format = xstrtooff_sfx(str_N, 0, bkm_suffixes);
     }
     if (opt & OPT_a) decode_format_string("a");
     if (opt & OPT_b) decode_format_string("oC");
     if (opt & OPT_c) decode_format_string("c");
     if (opt & OPT_d) decode_format_string("u2");
     if (opt & OPT_f) decode_format_string("fF");
     if (opt & OPT_h) decode_format_string("x2");
     if (opt & OPT_i) decode_format_string("d2");
     if (opt & OPT_j) n_bytes_to_skip = xstrtooff_sfx(str_j, 0, bkm_suffixes);
     if (opt & OPT_l) decode_format_string("d4");
     if (opt & OPT_o) decode_format_string("o2");
     while (lst_t) {
         decode_format_string(llist_pop(&lst_t));
     }
     if (opt & OPT_x) decode_format_string("x2");
     if (opt & OPT_s) decode_format_string("d2");
     if (opt & OPT_S) {
         G.string_min = xstrtou_sfx(str_S, 0, bkm_suffixes);
     }
     // Bloat:
     //if ((option_mask32 & OPT_S) && G.n_specs > 0)
     //  bb_error_msg_and_die("no type may be specified when dumping strings");
     /* If the --traditional option is used, there may be from
      * 0 to 3 remaining command line arguments;  handle each case
      * separately.
      * od [FILE] [[+]OFFSET[.][b] [[+]LABEL[.][b]]]
      * The offset and pseudo_start have the same syntax.
      *
      * FIXME: POSIX 1003.1-2001 with XSI requires support for the
      * traditional syntax even if --traditional is not given.  */
 #if ENABLE_LONG_OPTS
     if (opt & OPT_traditional) {
         if (argv[0]) {
             off_t pseudo_start = -1;
             off_t o1, o2;
             if (!argv[1]) { /* one arg */
                 if (parse_old_offset(argv[0], &o1)) {
                     /* od --traditional OFFSET */
                     n_bytes_to_skip = o1;
                     argv++;
                 }
                 /* od --traditional FILE */
             } else if (!argv[2]) { /* two args */
                 if (parse_old_offset(argv[0], &o1)
                  && parse_old_offset(argv[1], &o2)
                 ) {
                     /* od --traditional OFFSET LABEL */
                     n_bytes_to_skip = o1;
                     pseudo_start = o2;
                     argv += 2;
                 } else if (parse_old_offset(argv[1], &o2)) {
                     /* od --traditional FILE OFFSET */
                     n_bytes_to_skip = o2;
                     argv[1] = NULL;
                 } else {
                     bb_error_msg_and_die("invalid second argument '%s'", argv[1]);
                 }
             } else if (!argv[3]) { /* three args */
                 if (parse_old_offset(argv[1], &o1)
                  && parse_old_offset(argv[2], &o2)
                 ) {
                     /* od --traditional FILE OFFSET LABEL */
                     n_bytes_to_skip = o1;
                     pseudo_start = o2;
                     argv[1] = NULL;
                 } else {
                     bb_simple_error_msg_and_die("the last two arguments must be offsets");
                 }
             } else { /* >3 args */
                 bb_simple_error_msg_and_die("too many arguments");
             }
             if (pseudo_start >= 0) {
                 if (G.format_address == format_address_none) {
                     address_base_char = 'o';
                     address_pad_len_char = '7';
                     G.format_address = format_address_paren;
                 } else {
                     G.format_address = format_address_label;
                 }
                 G_pseudo_offset = pseudo_start - n_bytes_to_skip;
             }
         }
         /* else: od --traditional (without args) */
     }
 #endif
     if (option_mask32 & OPT_N) {
         end_offset = n_bytes_to_skip + max_bytes_to_format;
         if (end_offset < n_bytes_to_skip)
             bb_simple_error_msg_and_die("SKIP + SIZE is too large");
     }
     if (G.n_specs == 0) {
         decode_format_string("o2");
         /*G.n_specs = 1; - done by decode_format_string */
     }
     /* If no files were listed on the command line,
        set the global pointer FILE_LIST so that it
        references the null-terminated list of one name: "-".  */
     G.file_list = bb_argv_dash;
     if (argv[0]) {
         /* Set the global pointer FILE_LIST so that it
            references the first file-argument on the command-line.  */
         G.file_list = (char const *const *) argv;
     }
     /* Open the first input file */
     open_next_file();
     /* Skip over any unwanted header bytes */
     skip(n_bytes_to_skip);
     if (!G.in_stream)
         return EXIT_FAILURE;
     /* Compute output block length */
     l_c_m = get_lcm();
     if (opt & OPT_w) { /* -w: width */
         if (!G.bytes_per_block || G.bytes_per_block % l_c_m != 0) {
             bb_error_msg("warning: invalid width %u; using %d instead",
                     (unsigned)G.bytes_per_block, l_c_m);
             G.bytes_per_block = l_c_m;
         }
     } else {
         G.bytes_per_block = l_c_m;
         if (l_c_m < DEFAULT_BYTES_PER_BLOCK)
             G.bytes_per_block *= DEFAULT_BYTES_PER_BLOCK / l_c_m;
     }
 #ifdef DEBUG
     {
         int i;
         for (i = 0; i < G.n_specs; i++) {
             printf("%d: fmt='%s' width=%d\n",
                 i, G.spec[i].fmt_string,
                 width_bytes[G.spec[i].size]);
         }
     }
 #endif
     if (option_mask32 & OPT_S)
         dump_strings(n_bytes_to_skip, end_offset);
     else
         dump(n_bytes_to_skip, end_offset);
     if (fclose(stdin))
         bb_simple_perror_msg_and_die(bb_msg_standard_input);
     return G.exit_code;
 }
open_next_file()
static void open_next_file (void) static
Definition at line 500 of file od_bloaty.c.
 {
     while (1) {
         if (!*G.file_list)
             return;
         G.in_stream = fopen_or_warn_stdin(*G.file_list++);
         if (G.in_stream) {
             break;
         }
         G.exit_code = 1;
     }
     if ((option_mask32 & (OPT_N|OPT_S)) == OPT_N)
         setbuf(G.in_stream, NULL);
 }
References fopen_or_warn_stdin(), G, NULL, OPT_N, OPT_S, option_mask32, and setbuf().
Referenced by dump_strings(), read_block(), and skip().
print_ascii()
static void print_ascii (size_t n_bytes, const char * block, const char *unused_fmt_string UNUSED_PARAM) static
Definition at line 442 of file od_bloaty.c.
 {
     // buf[N] pos:  01234 56789
     char buf[12] = "   x\0 xxx\0";
     while (n_bytes--) {
         const char *s;
         unsigned c = *(unsigned char *) block++;
         if (ISPRINT(c)) {
             buf[3] = c;
             fputs_stdout(buf);
             continue;
         }
         switch (c) {
         case '\0':
             s = "  \\0";
             break;
         case '\007':
             s = "  \\a";
             break;
         case '\b':
             s = "  \\b";
             break;
         case '\f':
             s = "  \\f";
             break;
         case '\n':
             s = "  \\n";
             break;
         case '\r':
             s = "  \\r";
             break;
         case '\t':
             s = "  \\t";
             break;
         case '\v':
             s = "  \\v";
             break;
         default:
             buf[6] = (c >> 6 & 3) + '0';
             buf[7] = (c >> 3 & 7) + '0';
             buf[8] = (c & 7) + '0';
             s = buf + 5;
         }
         fputs_stdout(s);
     }
 }
References buf, c, fputs_stdout(), ISPRINT, and s.
Referenced by decode_one_format().
print_char()
static void print_char (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 292 of file od_bloaty.c.
 {
     while (n_bytes--) {
         unsigned tmp = *(unsigned char *) block;
         printf(fmt_string, tmp);
         block += sizeof(unsigned char);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_double()
static void print_double (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 376 of file od_bloaty.c.
 {
     n_bytes /= sizeof(double);
     while (n_bytes--) {
         double tmp = *(double *) block;
         printf(fmt_string, tmp);
         block += sizeof(double);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_float()
static void print_float (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 365 of file od_bloaty.c.
 {
     n_bytes /= sizeof(float);
     while (n_bytes--) {
         float tmp = *(float *) block;
         printf(fmt_string, tmp);
         block += sizeof(float);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_int()
static void print_int (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 324 of file od_bloaty.c.
 {
     n_bytes /= sizeof(unsigned);
     while (n_bytes--) {
         unsigned tmp = *(unsigned *) block;
         printf(fmt_string, tmp);
         block += sizeof(unsigned);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_long_double()
static void print_long_double (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 387 of file od_bloaty.c.
 {
     n_bytes /= sizeof(longdouble_t);
     while (n_bytes--) {
         longdouble_t tmp = *(longdouble_t *) block;
         printf(fmt_string, tmp);
         block += sizeof(longdouble_t);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_named_ascii()
static void print_named_ascii (size_t n_bytes, const char * block, const char *unused_fmt_string UNUSED_PARAM) static
Definition at line 402 of file od_bloaty.c.
 {
     /* Names for some non-printing characters.  */
     static const char charname[33][3] ALIGN1 = {
         "nul", "soh", "stx", "etx", "eot", "enq", "ack", "bel",
         " bs", " ht", " nl", " vt", " ff", " cr", " so", " si",
         "dle", "dc1", "dc2", "dc3", "dc4", "nak", "syn", "etb",
         "can", " em", "sub", "esc", " fs", " gs", " rs", " us",
         " sp"
     };
     // buf[N] pos:  01234 56789
     char buf[12] = "   x\0 xxx\0";
     // [12] because we take three 32bit stack slots anyway, and
     // gcc is too dumb to initialize with constant stores,
     // it copies initializer from rodata. Oh well.
     // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65410
     while (n_bytes--) {
         unsigned masked_c = *(unsigned char *) block++;
         masked_c &= 0x7f;
         if (masked_c == 0x7f) {
             fputs_stdout(" del");
             continue;
         }
         if (masked_c > ' ') {
             buf[3] = masked_c;
             fputs_stdout(buf);
             continue;
         }
         /* Why? Because printf(" %3.3s") is much slower... */
         buf[6] = charname[masked_c][0];
         buf[7] = charname[masked_c][1];
         buf[8] = charname[masked_c][2];
         fputs_stdout(buf+5);
     }
 }
References ALIGN1, buf, and fputs_stdout().
Referenced by decode_one_format().
print_s_char()
static void print_s_char (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 282 of file od_bloaty.c.
 {
     while (n_bytes--) {
         int tmp = *(signed char *) block;
         printf(fmt_string, tmp);
         block += sizeof(unsigned char);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_s_short()
static void print_s_short (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 302 of file od_bloaty.c.
 {
     n_bytes /= sizeof(signed short);
     while (n_bytes--) {
         int tmp = *(signed short *) block;
         printf(fmt_string, tmp);
         block += sizeof(unsigned short);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
print_short()
static void print_short (size_t n_bytes, const char * block, const char * fmt_string) static
Definition at line 313 of file od_bloaty.c.
 {
     n_bytes /= sizeof(unsigned short);
     while (n_bytes--) {
         unsigned tmp = *(unsigned short *) block;
         printf(fmt_string, tmp);
         block += sizeof(unsigned short);
     }
 }
References tspec::fmt_string, and printf.
Referenced by decode_one_format().
read_block()
static void read_block (size_t n, char * block, size_t * n_bytes_in_buffer) static
Definition at line 945 of file od_bloaty.c.
 {
     assert(0 < n && n <= G.bytes_per_block);
     *n_bytes_in_buffer = 0;
     if (n == 0)
         return;
     while (G.in_stream != NULL) { /* EOF.  */
         size_t n_needed;
         size_t n_read;
         n_needed = n - *n_bytes_in_buffer;
         n_read = fread(block + *n_bytes_in_buffer, 1, n_needed, G.in_stream);
         *n_bytes_in_buffer += n_read;
         if (n_read == n_needed)
             break;
         /* error check is done in check_and_close */
         check_and_close();
         open_next_file();
     }
 }
References assert, check_and_close(), fread(), G, n, NULL, and open_next_file().
Referenced by dump().
skip()
static void skip (off_t n_skip) static
Definition at line 786 of file od_bloaty.c.
 {
     if (n_skip == 0)
         return;
     while (G.in_stream) { /* !EOF */
         struct stat file_stats;
         /* First try seeking.  For large offsets, this extra work is
            worthwhile.  If the offset is below some threshold it may be
            more efficient to move the pointer by reading.  There are two
            issues when trying to seek:
             - the file must be seekable.
             - before seeking to the specified position, make sure
               that the new position is in the current file.
               Try to do that by getting file's size using fstat.
               But that will work only for regular files.  */
             /* The st_size field is valid only for regular files
                (and for symbolic links, which cannot occur here).
                If the number of bytes left to skip is at least
                as large as the size of the current file, we can
                decrement n_skip and go on to the next file.  */
         if (fstat(fileno(G.in_stream), &file_stats) == 0
          && S_ISREG(file_stats.st_mode) && file_stats.st_size > 0
         ) {
             if (file_stats.st_size < n_skip) {
                 n_skip -= file_stats.st_size;
                 /* take "check & close / open_next" route */
             } else {
                 if (fseeko(G.in_stream, n_skip, SEEK_CUR) != 0)
                     G.exit_code = 1;
                 return;
             }
         } else {
             /* If it's not a regular file with positive size,
                position the file pointer by reading.  */
             char buf[1024];
             size_t n_bytes_to_read = 1024;
             size_t n_bytes_read;
             while (n_skip > 0) {
                 if (n_skip < n_bytes_to_read)
                     n_bytes_to_read = n_skip;
                 n_bytes_read = fread(buf, 1, n_bytes_to_read, G.in_stream);
                 n_skip -= n_bytes_read;
                 if (n_bytes_read != n_bytes_to_read)
                     break; /* EOF on this file or error */
             }
         }
         if (n_skip == 0)
             return;
         check_and_close();
         open_next_file();
     }
     if (n_skip)
         bb_simple_error_msg_and_die("can't skip past end of combined input");
 }
References bb_simple_error_msg_and_die(), buf, check_and_close(), fileno(), fread(), fstat(), G, open_next_file(), S_ISREG, SEEK_CUR, stat::st_mode, and stat::st_size.
write_block()
static void write_block (off_t current_offset, size_t n_bytes, const char * prev_block, const char * curr_block) static
Definition at line 905 of file od_bloaty.c.
 {
     unsigned i;
     if (!(option_mask32 & OPT_v)
      && G.not_first
      && n_bytes == G.bytes_per_block
      && memcmp(prev_block, curr_block, G.bytes_per_block) == 0
     ) {
         if (G.prev_pair_equal) {
             /* The two preceding blocks were equal, and the current
                block is the same as the last one, so print nothing.  */
         } else {
             puts("*");
             G.prev_pair_equal = 1;
         }
     } else {
         G.not_first = 1;
         G.prev_pair_equal = 0;
         for (i = 0; i < G.n_specs; i++) {
             if (i == 0)
                 G.format_address(current_offset, '\0');
             else
                 printf("%*s", address_pad_len_char - '0', "");
             (*G.spec[i].print_function) (n_bytes, curr_block, G.spec[i].fmt_string);
             if (G.spec[i].hexl_mode_trailer) {
                 /* space-pad out to full line width, then dump the trailer */
                 unsigned datum_width = width_bytes[G.spec[i].size];
                 unsigned blank_fields = (G.bytes_per_block - n_bytes) / datum_width;
                 unsigned field_width = G.spec[i].field_width + 1;
                 printf("%*s", blank_fields * field_width, "");
                 dump_hexl_mode_trailer(n_bytes, curr_block);
             }
             putchar('\n');
         }
     }
 }
References address_pad_len_char, dump_hexl_mode_trailer(), G, i, memcmp(), OPT_v, option_mask32, printf, putchar, and puts().
Referenced by dump().
Variable Documentation
ALIGN1
const unsigned char fp_type_size [MAX_FP_TYPE_SIZE + 1] ALIGN1 static
Initial value:
=
{0, 3, 6, 8, 11, 14, 16, 19, 22, 25, 27, 30, 32, 35, 38, 41, 43}
Definition at line 148 of file od_bloaty.c.
Referenced by decode_one_format(), and print_named_ascii().
FIX_ALIASING
struct globals FIX_ALIASING