Fennix Userspace: Userspace/musl/include/ifaddrs.h File Reference
ifaddrs.h File Reference
#include <features.h>
#include <netinet/in.h>
#include <sys/socket.h>
Data Structures
struct ifaddrs
union ifaddrs.ifa_ifu
Macros
#define ifa_broadaddr ifa_ifu.ifu_broadaddr
#define ifa_dstaddr ifa_ifu.ifu_dstaddr
Functions
void freeifaddrs (struct ifaddrs *)
int getifaddrs (struct ifaddrs **)
Data Structure Documentation
ifaddrs
struct ifaddrs
Definition at line 13 of file ifaddrs.h.
Data Fields
struct sockaddr * ifa_addr
struct sockaddr * ifa_broadaddr
void * ifa_data
struct sockaddr * ifa_dstaddr
unsigned ifa_flags
union ifaddrs ifa_ifu
char * ifa_name
struct sockaddr * ifa_netmask
struct ifaddrs * ifa_next
ifaddrs.ifa_ifu
union ifaddrs.ifa_ifu
Definition at line 18 of file ifaddrs.h.
Data Fields
struct sockaddr * ifu_broadaddr
struct sockaddr * ifu_dstaddr
Macro Definition Documentation
ifa_broadaddr
#define ifa_broadaddr ifa_ifu.ifu_broadaddr
Definition at line 24 of file ifaddrs.h.
ifa_dstaddr
#define ifa_dstaddr ifa_ifu.ifu_dstaddr
Definition at line 25 of file ifaddrs.h.
Function Documentation
freeifaddrs()
void freeifaddrs (struct ifaddrs * ifp)
Definition at line 12 of file ifaddrs.cpp.
{
     mlibc::infoLogger() << "mlibc: freeifaddrs is a stub!" << frg::endlog;
     return;
 }
References free, ifaddrs::ifa_next, mlibc::infoLogger, and n.
Referenced by getifaddrs().
getifaddrs()
int getifaddrs (struct ifaddrs ** ifap)
Definition at line 6 of file ifaddrs.cpp.
{
     mlibc::infoLogger() << "mlibc: getifaddrs fails unconditionally!" << frg::endlog;
     errno = ENOSYS;
     return -1;
 }
References __rtnetlink_enumerate(), AF_UNSPEC, ENOSYS, errno, freeifaddrs(), mlibc::infoLogger, memset(), netlink_msg_to_ifaddr(), and r.