Fennix: Userspace/apps/base/bash/y.tab.c File Reference
y.tab.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "bashansi.h"
#include "filecntl.h"
#include <stdio.h>
#include "chartypes.h"
#include <signal.h>
#include "memalloc.h"
#include "bashintl.h"
#include "shell.h"
#include "execute_cmd.h"
#include "typemax.h"
#include "trap.h"
#include "flags.h"
#include "parser.h"
#include "mailcheck.h"
#include "test.h"
#include "builtins.h"
#include "builtins/common.h"
#include "builtins/builtext.h"
#include "shmbutil.h"
#include <limits.h>
Data Structures
union YYSTYPE
union yyalloc
struct stream_saver
struct string_saver
Macros
#define YYBISON 30802
#define YYBISON_VERSION "3.8.2"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define NEED_STRFTIME_DECL /* used in externs.h */
#define RE_READ_TOKEN -99
#define NO_EXPANSION -100
#define END_ALIAS -2
#define YYDEBUG 0
#define last_shell_getc_is_singlebyte 1
#define MBTEST(x) ((x))
#define EXTEND_SHELL_INPUT_LINE_PROPERTY()
#define set_line_mbstate()
#define MAX_CASE_NEST 128
#define YY_CAST(Type, Val) ((Type) (Val))
#define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#define YY_NULLPTR ((void*)0)
#define YY_YY_Y_TAB_H_INCLUDED
#define YYTOKENTYPE
#define YYEMPTY -2
#define YYEOF 0
#define YYerror 256
#define YYUNDEF 257
#define IF 258
#define THEN 259
#define ELSE 260
#define ELIF 261
#define FI 262
#define CASE 263
#define ESAC 264
#define FOR 265
#define SELECT 266
#define WHILE 267
#define UNTIL 268
#define DO 269
#define DONE 270
#define FUNCTION 271
#define COPROC 272
#define COND_START 273
#define COND_END 274
#define COND_ERROR 275
#define IN 276
#define BANG 277
#define TIME 278
#define TIMEOPT 279
#define TIMEIGN 280
#define WORD 281
#define ASSIGNMENT_WORD 282
#define REDIR_WORD 283
#define NUMBER 284
#define ARITH_CMD 285
#define ARITH_FOR_EXPRS 286
#define COND_CMD 287
#define AND_AND 288
#define OR_OR 289
#define GREATER_GREATER 290
#define LESS_LESS 291
#define LESS_AND 292
#define LESS_LESS_LESS 293
#define GREATER_AND 294
#define SEMI_SEMI 295
#define SEMI_AND 296
#define SEMI_SEMI_AND 297
#define LESS_LESS_MINUS 298
#define AND_GREATER 299
#define AND_GREATER_GREATER 300
#define LESS_GREATER 301
#define GREATER_BAR 302
#define BAR_AND 303
#define DOLPAREN 304
#define yacc_EOF 305
#define YYSTYPE_IS_TRIVIAL 1
#define YYSTYPE_IS_DECLARED 1
#define YYPTRDIFF_T long
#define YYPTRDIFF_MAXIMUM LONG_MAX
#define YYSIZE_T unsigned
#define YYSIZE_MAXIMUM
#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))
#define YY_(Msgid) Msgid
#define YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_UNUSED
#define YY_USE(E) ((void) (E))
#define YY_INITIAL_VALUE(Value) Value
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_USELESS_CAST_BEGIN
#define YY_IGNORE_USELESS_CAST_END
#define YY_ASSERT(E) ((void) (0 && (E)))
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC malloc
#define YYFREE free
#define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(Dst, Src, Count)
#define YYFINAL 121
#define YYLAST 740
#define YYNTOKENS 62
#define YYNNTS 38
#define YYNRULES 174
#define YYNSTATES 349
#define YYMAXUTOK 305
#define YYTRANSLATE(YYX)
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])
#define YYPACT_NINF (-152)
#define yypact_value_is_default(Yyn) ((Yyn) == YYPACT_NINF)
#define YYTABLE_NINF (-1)
#define yytable_value_is_error(Yyn) 0
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYNOMEM goto yyexhaustedlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYERRCODE YYUNDEF
#define YYDPRINTF(Args) ((void) 0)
#define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define TOKEN_DEFAULT_INITIAL_SIZE 496
#define TOKEN_DEFAULT_GROW_SIZE 512
#define SHOULD_PROMPT() (interactive && (bash_input.type == st_stdin || bash_input.type == st_stream))
#define expanding_alias() 0
#define END_OF_ALIAS 0
#define PSH_ALIAS 0x01
#define PSH_DPAREN 0x02
#define PSH_SOURCE 0x04
#define PSH_ARRAY 0x08
#define current_delimiter(ds) (ds.delimiter_depth ? ds.delimiters[ds.delimiter_depth - 1] : 0)
#define push_delimiter(ds, character)
#define pop_delimiter(ds) ds.delimiter_depth--
#define READ 0
#define RESET 1
#define prompt_is_ps1 (!prompt_string_pointer || prompt_string_pointer == &ps1_prompt)
#define parsing_redirection(token)
#define command_token_position(token)
#define assignment_acceptable(token) (command_token_position(token) && ((parser_state & PST_CASEPAT) == 0))
#define CHECK_FOR_RESERVED_WORD(tok)
#define P_FIRSTCLOSE 0x0001
#define P_ALLOWESC 0x0002
#define P_DQUOTE 0x0004
#define P_COMMAND 0x0008 /* parsing a command, so look for comments */
#define P_BACKQUOTE 0x0010 /* parsing a backquoted command substitution */
#define P_ARRAYSUB 0x0020 /* parsing a [...] array subscript for assignment */
#define P_DOLBRACE 0x0040 /* parsing a ${...} construct */
#define P_ARITH 0x0080 /* parsing a $(()) arithmetic expansion */
#define LEX_WASDOL 0x0001
#define LEX_CKCOMMENT 0x0002
#define LEX_INCOMMENT 0x0004
#define LEX_PASSNEXT 0x0008
#define LEX_RESWDOK 0x0010
#define LEX_CKCASE 0x0020
#define LEX_INCASE 0x0040
#define LEX_INHEREDOC 0x0080
#define LEX_HEREDELIM 0x0100 /* reading here-doc delimiter */
#define LEX_STRIPDOC 0x0200 /* <<- strip tabs from here doc delim */
#define LEX_QUOTEDDOC 0x0400 /* here doc with quoted delim */
#define LEX_INWORD 0x0800
#define LEX_GTLT 0x1000
#define LEX_CKESAC 0x2000 /* check esac after in -- for later */
#define LEX_CASEWD 0x4000 /* word after case */
#define LEX_PATLIST 0x8000 /* case statement pattern list */
#define COMSUB_META(ch) ((ch) == ';' || (ch) == '&' || (ch) == '|')
#define CHECK_NESTRET_ERROR()
#define APPEND_NESTRET()
#define PROMPT_GROWTH 48
Typedefs
typedef void * alias_t
typedef enum yytokentype yytoken_kind_t
typedef union YYSTYPE YYSTYPE
typedef enum yysymbol_kind_t yysymbol_kind_t
typedef signed char yytype_int8
typedef short yytype_int16
typedef unsigned char yytype_uint8
typedef unsigned short yytype_uint16
typedef yytype_int16 yy_state_t
typedef int yy_state_fast_t
typedef struct stream_saver STREAM_SAVER
typedef struct string_saver STRING_SAVER
Enumerations
enum yytokentype {
EQUOP2 = 258 , CMPOP2 = 259 , ADDOP2 = 260 , MULOP2 = 261 ,
NUMBER = 262 , YYEMPTY = -2 , YYEOF = 0 , YYerror = 256 ,
YYUNDEF = 257 , IF = 258 , THEN = 259 , ELSE = 260 ,
ELIF = 261 , FI = 262 , CASE = 263 , ESAC = 264 ,
FOR = 265 , SELECT = 266 , WHILE = 267 , UNTIL = 268 ,
DO = 269 , DONE = 270 , FUNCTION = 271 , COPROC = 272 ,
COND_START = 273 , COND_END = 274 , COND_ERROR = 275 , IN = 276 ,
BANG = 277 , TIME = 278 , TIMEOPT = 279 , TIMEIGN = 280 ,
WORD = 281 , ASSIGNMENT_WORD = 282 , REDIR_WORD = 283 , NUMBER = 284 ,
ARITH_CMD = 285 , ARITH_FOR_EXPRS = 286 , COND_CMD = 287 , AND_AND = 288 ,
OR_OR = 289 , GREATER_GREATER = 290 , LESS_LESS = 291 , LESS_AND = 292 ,
LESS_LESS_LESS = 293 , GREATER_AND = 294 , SEMI_SEMI = 295 , SEMI_AND = 296 ,
SEMI_SEMI_AND = 297 , LESS_LESS_MINUS = 298 , AND_GREATER = 299 , AND_GREATER_GREATER = 300 ,
LESS_GREATER = 301 , GREATER_BAR = 302 , BAR_AND = 303 , DOLPAREN = 304 ,
yacc_EOF = 305 , YYEMPTY = -2 , YYEOF = 0 , YYerror = 256 ,
YYUNDEF = 257 , IF = 258 , THEN = 259 , ELSE = 260 ,
ELIF = 261 , FI = 262 , CASE = 263 , ESAC = 264 ,
FOR = 265 , SELECT = 266 , WHILE = 267 , UNTIL = 268 ,
DO = 269 , DONE = 270 , FUNCTION = 271 , COPROC = 272 ,
COND_START = 273 , COND_END = 274 , COND_ERROR = 275 , IN = 276 ,
BANG = 277 , TIME = 278 , TIMEOPT = 279 , TIMEIGN = 280 ,
WORD = 281 , ASSIGNMENT_WORD = 282 , REDIR_WORD = 283 , NUMBER = 284 ,
ARITH_CMD = 285 , ARITH_FOR_EXPRS = 286 , COND_CMD = 287 , AND_AND = 288 ,
OR_OR = 289 , GREATER_GREATER = 290 , LESS_LESS = 291 , LESS_AND = 292 ,
LESS_LESS_LESS = 293 , GREATER_AND = 294 , SEMI_SEMI = 295 , SEMI_AND = 296 ,
SEMI_SEMI_AND = 297 , LESS_LESS_MINUS = 298 , AND_GREATER = 299 , AND_GREATER_GREATER = 300 ,
LESS_GREATER = 301 , GREATER_BAR = 302 , BAR_AND = 303 , DOLPAREN = 304 ,
yacc_EOF = 305
}
enum yysymbol_kind_t {
YYSYMBOL_YYEMPTY = -2 , YYSYMBOL_YYEOF = 0 , YYSYMBOL_YYerror = 1 , YYSYMBOL_YYUNDEF = 2 ,
YYSYMBOL_IF = 3 , YYSYMBOL_THEN = 4 , YYSYMBOL_ELSE = 5 , YYSYMBOL_ELIF = 6 ,
YYSYMBOL_FI = 7 , YYSYMBOL_CASE = 8 , YYSYMBOL_ESAC = 9 , YYSYMBOL_FOR = 10 ,
YYSYMBOL_SELECT = 11 , YYSYMBOL_WHILE = 12 , YYSYMBOL_UNTIL = 13 , YYSYMBOL_DO = 14 ,
YYSYMBOL_DONE = 15 , YYSYMBOL_FUNCTION = 16 , YYSYMBOL_COPROC = 17 , YYSYMBOL_COND_START = 18 ,
YYSYMBOL_COND_END = 19 , YYSYMBOL_COND_ERROR = 20 , YYSYMBOL_IN = 21 , YYSYMBOL_BANG = 22 ,
YYSYMBOL_TIME = 23 , YYSYMBOL_TIMEOPT = 24 , YYSYMBOL_TIMEIGN = 25 , YYSYMBOL_WORD = 26 ,
YYSYMBOL_ASSIGNMENT_WORD = 27 , YYSYMBOL_REDIR_WORD = 28 , YYSYMBOL_NUMBER = 29 , YYSYMBOL_ARITH_CMD = 30 ,
YYSYMBOL_ARITH_FOR_EXPRS = 31 , YYSYMBOL_COND_CMD = 32 , YYSYMBOL_AND_AND = 33 , YYSYMBOL_OR_OR = 34 ,
YYSYMBOL_GREATER_GREATER = 35 , YYSYMBOL_LESS_LESS = 36 , YYSYMBOL_LESS_AND = 37 , YYSYMBOL_LESS_LESS_LESS = 38 ,
YYSYMBOL_GREATER_AND = 39 , YYSYMBOL_SEMI_SEMI = 40 , YYSYMBOL_SEMI_AND = 41 , YYSYMBOL_SEMI_SEMI_AND = 42 ,
YYSYMBOL_LESS_LESS_MINUS = 43 , YYSYMBOL_AND_GREATER = 44 , YYSYMBOL_AND_GREATER_GREATER = 45 , YYSYMBOL_LESS_GREATER = 46 ,
YYSYMBOL_GREATER_BAR = 47 , YYSYMBOL_BAR_AND = 48 , YYSYMBOL_DOLPAREN = 49 , YYSYMBOL_50_ = 50 ,
YYSYMBOL_51_ = 51 , YYSYMBOL_52_n_ = 52 , YYSYMBOL_yacc_EOF = 53 , YYSYMBOL_54_ = 54 ,
YYSYMBOL_55_ = 55 , YYSYMBOL_56_ = 56 , YYSYMBOL_57_ = 57 , YYSYMBOL_58_ = 58 ,
YYSYMBOL_59_ = 59 , YYSYMBOL_60_ = 60 , YYSYMBOL_61_ = 61 , YYSYMBOL_YYACCEPT = 62 ,
YYSYMBOL_inputunit = 63 , YYSYMBOL_word_list = 64 , YYSYMBOL_redirection = 65 , YYSYMBOL_simple_command_element = 66 ,
YYSYMBOL_redirection_list = 67 , YYSYMBOL_simple_command = 68 , YYSYMBOL_command = 69 , YYSYMBOL_shell_command = 70 ,
YYSYMBOL_for_command = 71 , YYSYMBOL_arith_for_command = 72 , YYSYMBOL_select_command = 73 , YYSYMBOL_case_command = 74 ,
YYSYMBOL_function_def = 75 , YYSYMBOL_function_body = 76 , YYSYMBOL_subshell = 77 , YYSYMBOL_comsub = 78 ,
YYSYMBOL_coproc = 79 , YYSYMBOL_if_command = 80 , YYSYMBOL_group_command = 81 , YYSYMBOL_arith_command = 82 ,
YYSYMBOL_cond_command = 83 , YYSYMBOL_elif_clause = 84 , YYSYMBOL_case_clause = 85 , YYSYMBOL_pattern_list = 86 ,
YYSYMBOL_case_clause_sequence = 87 , YYSYMBOL_pattern = 88 , YYSYMBOL_compound_list = 89 , YYSYMBOL_list0 = 90 ,
YYSYMBOL_list1 = 91 , YYSYMBOL_simple_list_terminator = 92 , YYSYMBOL_list_terminator = 93 , YYSYMBOL_newline_list = 94 ,
YYSYMBOL_simple_list = 95 , YYSYMBOL_simple_list1 = 96 , YYSYMBOL_pipeline_command = 97 , YYSYMBOL_pipeline = 98 ,
YYSYMBOL_timespec = 99
}
enum { YYENOMEM = -2 }
Functions
int cleanup_dead_jobs PARAMS ((void))
static int yy_ungetc PARAMS ((int))
static void push_string PARAMS ((char *, int, alias_t *))
static void push_heredoc PARAMS ((REDIRECT *))
static char *mk_alexpansion PARAMS ((char *))
static char *parse_matched_pair PARAMS ((int, int, int, int *, int))
int yyerror PARAMS ((const char *))
int yyparse (void)
void * malloc (YYSIZE_T)
void free (void *)
The standard function.
static void yydestruct (const char *yymsg, yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
int return_EOF ()
void initialize_bash_input ()
void init_yy_io (sh_cget_func_t *get, sh_cunget_func_t *unget, enum stream_type type, const char *name, INPUT_STREAM location)
char * yy_input_name ()
static int yy_getc ()
static int yy_ungetc (int c)
void with_input_from_stdin ()
static int yy_string_get ()
static int yy_string_unget (int c)
void with_input_from_string (char *string, const char *name)
void rewind_input_string ()
static int yy_stream_get ()
static int yy_stream_unget (int c)
void with_input_from_stream (FILE *stream, const char *name)
void push_stream (int reset_lineno)
void pop_stream ()
int stream_on_stack (enum stream_type type)
int * save_token_state ()
void restore_token_state (int *ts)
static void push_string (char *s, int expand, alias_t *ap)
static void pop_string ()
static void free_string_list ()
void free_pushed_string_input ()
int parser_expanding_alias ()
void parser_save_alias ()
void parser_restore_alias ()
void clear_shell_input_line ()
static char * read_a_line (int remove_quoted_newline)
char * read_secondary_line (int remove_quoted_newline)
static int shell_getc (int remove_quoted_newline)
static void shell_ungetc (int c)
void shell_ungets (char *s)
char * parser_remaining_input ()
static void discard_until (int character)
void execute_variable_command (char *command, char *vname)
void push_token (int x)
static int yylex ()
static void push_heredoc (REDIRECT *r)
void gather_here_documents ()
static int time_command_acceptable ()
static int special_case_tokens (char *tokstr)
void reset_parser ()
void reset_readahead_token ()
static int read_token (int command)
static char * parse_matched_pair (int qc, int open, int close, int *lenp, int flags)
static char * parse_comsub (int qc, int open, int close, int *lenp, int flags)
char * xparse_dolparen (char *base, char *string, int *indp, int flags)
COMMAND * parse_string_to_command (char *string, int flags)
static int read_token_word (int character)
static int reserved_word_acceptable (int toksym)
int find_reserved_word (char *tokstr)
int parser_in_command_position ()
static void prompt_again (int force)
int get_current_prompt_level ()
void set_current_prompt_level (int x)
static void print_prompt ()
char * decode_prompt_string (char *string)
int yyerror (char *msg) const
static char * error_token_from_token (int tok)
static char * error_token_from_text ()
static void print_offending_line ()
static void report_syntax_error (char *message)
static void discard_parser_constructs (int error_p)
static void handle_eof_input_unit ()
WORD_LIST * parse_string_to_word_list (char *s, int flags, const char *whom)
static char * parse_compound_assignment (int *retlenp)
sh_parser_state_t * save_parser_state (sh_parser_state_t *ps)
void restore_parser_state (sh_parser_state_t *ps)
sh_input_line_state_t * save_input_line_state (sh_input_line_state_t *ls)
void restore_input_line_state (sh_input_line_state_t *ls)
Variables
int errno
char * primary_prompt = PPROMPT
char * secondary_prompt = SPROMPT
char * ps1_prompt
char * ps2_prompt
char * ps0_prompt
char ** prompt_string_pointer = (char **)NULL
char * current_prompt_string
int expand_aliases = 0
int promptvars = 1
int extended_quote = 1
int current_command_line_count
int saved_command_line_count
int shell_eof_token
int current_token
int parser_state
static REDIRECT * redir_stack [HEREDOC_MAX]
int need_here_doc
static char * shell_input_line = (char *)NULL
static size_t shell_input_line_index
static size_t shell_input_line_size
static size_t shell_input_line_len
static int shell_input_line_terminator
static int function_dstart
static int function_bstart
static int arith_for_lineno
static char * current_decoded_prompt
static int last_read_token
static int token_before_that
static int two_tokens_ago
static int global_extglob
static int word_lineno [MAX_CASE_NEST+1]
static int word_top = -1
static int token_to_read
static WORD_DESC * word_desc_to_read
static REDIRECTEE source
static REDIRECTEE redir
static FILE * yyoutstream
static FILE * yyerrstream
YYSTYPE yylval
static const yytype_int8 yytranslate []
static const yytype_int16 yypact []
static const yytype_uint8 yydefact []
static const yytype_int16 yypgoto []
static const yytype_int16 yydefgoto []
static const yytype_int16 yytable []
static const yytype_int16 yycheck []
static const yytype_int8 yystos []
static const yytype_int8 yyr1 []
static const yytype_int8 yyr2 []
int yychar
int yynerrs
int EOF_Reached = 0
BASH_INPUT bash_input
int line_number = 0
int line_number_base = 0
STREAM_SAVER * stream_list = (STREAM_SAVER *)NULL
STRING_SAVER * pushed_string_list = (STRING_SAVER *)NULL
STRING_INT_ALIST word_token_alist []
STRING_INT_ALIST other_token_alist []
struct dstack dstack = { (char *)NULL, 0, 0 }
static struct dstack temp_dstack = { (char *)NULL, 0, 0 }
static int eol_ungetc_lookahead = 0
static int unquoted_backslash = 0
static char * token = (char *)NULL
static size_t token_buffer_size
static int esacs_needed_count
static int expecting_in_token
static int open_brace_count
static char matched_pair_error
int ignoreeof = 0
int eof_encountered = 0
int eof_encountered_limit = 10
static WORD_LIST parse_string_error
Data Structure Documentation
YYSTYPE
union YYSTYPE
Definition at line 146 of file plural.c.
Data Fields
COMMAND * command
ELEMENT element
struct expression * exp
unsigned long int num
int number
enum operator op
PATTERN_LIST * pattern
REDIRECT * redirect
WORD_DESC * word
WORD_LIST * word_list
yyalloc
union yyalloc
Definition at line 304 of file plural.c.
Data Fields
short int yyss
yy_state_t yyss_alloc
YYSTYPE yyvs
YYSTYPE yyvs_alloc
stream_saver
struct stream_saver
Definition at line 4035 of file y.tab.c.
Data Fields
BASH_INPUT bash_input
int line
struct stream_saver * next
string_saver
struct string_saver
Definition at line 4193 of file y.tab.c.
Data Fields
int expand_alias
int flags
struct string_saver * next
char * saved_line
size_t saved_line_index
size_t saved_line_len
size_t saved_line_size
int saved_line_terminator
Macro Definition Documentation
AND_AND
#define AND_AND 288
Definition at line 517 of file y.tab.c.
AND_GREATER
#define AND_GREATER 299
Definition at line 528 of file y.tab.c.
AND_GREATER_GREATER
#define AND_GREATER_GREATER 300
Definition at line 529 of file y.tab.c.
APPEND_NESTRET
#define APPEND_NESTRET ()
Value:
  do { \
    if (nestlen) \
      { \
    RESIZE_MALLOCED_BUFFER (ret, retind, nestlen, retsize, 64); \
    strcpy (ret + retind, nestret); \
    retind += nestlen; \
      } \
  } while (0)
Definition at line 5957 of file y.tab.c.
ARITH_CMD
#define ARITH_CMD 285
Definition at line 514 of file y.tab.c.
ARITH_FOR_EXPRS
#define ARITH_FOR_EXPRS 286
Definition at line 515 of file y.tab.c.
assignment_acceptable
#define assignment_acceptable (token) (command_token_position(token) && ((parser_state & PST_CASEPAT) == 0))
Definition at line 5285 of file y.tab.c.
ASSIGNMENT_WORD
#define ASSIGNMENT_WORD 282
Definition at line 511 of file y.tab.c.
BANG
#define BANG 277
Definition at line 506 of file y.tab.c.
BAR_AND
#define BAR_AND 303
Definition at line 532 of file y.tab.c.
CASE
#define CASE 263
Definition at line 492 of file y.tab.c.
CHECK_FOR_RESERVED_WORD
#define CHECK_FOR_RESERVED_WORD (tok)
Definition at line 5290 of file y.tab.c.
CHECK_NESTRET_ERROR
#define CHECK_NESTRET_ERROR ()
Value:
  do { \
    if (nestret == &matched_pair_error) \
      { \
    free (ret); \
    return &matched_pair_error; \
      } \
  } while (0)
Definition at line 5948 of file y.tab.c.
command_token_position
#define command_token_position (token)
Value:
  (((token) == ASSIGNMENT_WORD) || \
   ((parser_state&PST_REDIRLIST) && parsing_redirection(token) == 0) || \
   ((token) != SEMI_SEMI && (token) != SEMI_AND && (token) != SEMI_SEMI_AND && reserved_word_acceptable(token)))
Definition at line 5279 of file y.tab.c.
COMSUB_META
#define COMSUB_META (ch) ((ch) == ';' || (ch) == '&' || (ch) == '|')
Definition at line 5946 of file y.tab.c.
COND_CMD
#define COND_CMD 287
Definition at line 516 of file y.tab.c.
COND_END
#define COND_END 274
Definition at line 503 of file y.tab.c.
COND_ERROR
#define COND_ERROR 275
Definition at line 504 of file y.tab.c.
COND_START
#define COND_START 273
Definition at line 502 of file y.tab.c.
COPROC
#define COPROC 272
Definition at line 501 of file y.tab.c.
current_delimiter
#define current_delimiter (ds) (ds.delimiter_depth ? ds.delimiters[ds.delimiter_depth - 1] : 0)
Definition at line 4594 of file y.tab.c.
DO
#define DO 269
Definition at line 498 of file y.tab.c.
DOLPAREN
#define DOLPAREN 304
Definition at line 533 of file y.tab.c.
DONE
#define DONE 270
Definition at line 499 of file y.tab.c.
ELIF
#define ELIF 261
Definition at line 490 of file y.tab.c.
ELSE
#define ELSE 260
Definition at line 489 of file y.tab.c.
END_ALIAS
#define END_ALIAS -2
Definition at line 148 of file y.tab.c.
END_OF_ALIAS
#define END_OF_ALIAS 0
Definition at line 4177 of file y.tab.c.
ESAC
#define ESAC 264
Definition at line 493 of file y.tab.c.
expanding_alias
#define expanding_alias () 0
Definition at line 3687 of file y.tab.c.
EXTEND_SHELL_INPUT_LINE_PROPERTY
#define EXTEND_SHELL_INPUT_LINE_PROPERTY ()
Value:
do { \
    if (shell_input_line_len + 2 > shell_input_line_propsize) \
      { \
    shell_input_line_propsize = shell_input_line_len + 2; \
    shell_input_line_property = (char *)xrealloc (shell_input_line_property, \
                    shell_input_line_propsize); \
      } \
} while (0)
Definition at line 167 of file y.tab.c.
FI
#define FI 262
Definition at line 491 of file y.tab.c.
FOR
#define FOR 265
Definition at line 494 of file y.tab.c.
FUNCTION
#define FUNCTION 271
Definition at line 500 of file y.tab.c.
GREATER_AND
#define GREATER_AND 294
Definition at line 523 of file y.tab.c.
GREATER_BAR
#define GREATER_BAR 302
Definition at line 531 of file y.tab.c.
GREATER_GREATER
#define GREATER_GREATER 290
Definition at line 519 of file y.tab.c.
IF
#define IF 258
Definition at line 487 of file y.tab.c.
IN
#define IN 276
Definition at line 505 of file y.tab.c.
last_shell_getc_is_singlebyte
#define last_shell_getc_is_singlebyte 1
Definition at line 163 of file y.tab.c.
LESS_AND
#define LESS_AND 292
Definition at line 521 of file y.tab.c.
LESS_GREATER
#define LESS_GREATER 301
Definition at line 530 of file y.tab.c.
LESS_LESS
#define LESS_LESS 291
Definition at line 520 of file y.tab.c.
LESS_LESS_LESS
#define LESS_LESS_LESS 293
Definition at line 522 of file y.tab.c.
LESS_LESS_MINUS
#define LESS_LESS_MINUS 298
Definition at line 527 of file y.tab.c.
LEX_CASEWD
#define LEX_CASEWD 0x4000 /* word after case */
Definition at line 5943 of file y.tab.c.
LEX_CKCASE
#define LEX_CKCASE 0x0020
Definition at line 5934 of file y.tab.c.
LEX_CKCOMMENT
#define LEX_CKCOMMENT 0x0002
Definition at line 5930 of file y.tab.c.
LEX_CKESAC
#define LEX_CKESAC 0x2000 /* check esac after in -- for later */
Definition at line 5942 of file y.tab.c.
LEX_GTLT
#define LEX_GTLT 0x1000
Definition at line 5941 of file y.tab.c.
LEX_HEREDELIM
#define LEX_HEREDELIM 0x0100 /* reading here-doc delimiter */
Definition at line 5937 of file y.tab.c.
LEX_INCASE
#define LEX_INCASE 0x0040
Definition at line 5935 of file y.tab.c.
LEX_INCOMMENT
#define LEX_INCOMMENT 0x0004
Definition at line 5931 of file y.tab.c.
LEX_INHEREDOC
#define LEX_INHEREDOC 0x0080
Definition at line 5936 of file y.tab.c.
LEX_INWORD
#define LEX_INWORD 0x0800
Definition at line 5940 of file y.tab.c.
LEX_PASSNEXT
#define LEX_PASSNEXT 0x0008
Definition at line 5932 of file y.tab.c.
LEX_PATLIST
#define LEX_PATLIST 0x8000 /* case statement pattern list */
Definition at line 5944 of file y.tab.c.
LEX_QUOTEDDOC
#define LEX_QUOTEDDOC 0x0400 /* here doc with quoted delim */
Definition at line 5939 of file y.tab.c.
LEX_RESWDOK
#define LEX_RESWDOK 0x0010
Definition at line 5933 of file y.tab.c.
LEX_STRIPDOC
#define LEX_STRIPDOC 0x0200 /* <<- strip tabs from here doc delim */
Definition at line 5938 of file y.tab.c.
LEX_WASDOL
#define LEX_WASDOL 0x0001
Definition at line 5929 of file y.tab.c.
MAX_CASE_NEST
#define MAX_CASE_NEST 128
Definition at line 370 of file y.tab.c.
MBTEST
#define MBTEST (x) ((x))
Definition at line 164 of file y.tab.c.
NEED_STRFTIME_DECL
#define NEED_STRFTIME_DECL /* used in externs.h */
Definition at line 95 of file y.tab.c.
NO_EXPANSION
#define NO_EXPANSION -100
Definition at line 146 of file y.tab.c.
NUMBER
#define NUMBER 284
Definition at line 513 of file y.tab.c.
OR_OR
#define OR_OR 289
Definition at line 518 of file y.tab.c.
P_ALLOWESC
#define P_ALLOWESC 0x0002
Definition at line 5920 of file y.tab.c.
P_ARITH
#define P_ARITH 0x0080 /* parsing a $(()) arithmetic expansion */
Definition at line 5926 of file y.tab.c.
P_ARRAYSUB
#define P_ARRAYSUB 0x0020 /* parsing a [...] array subscript for assignment */
Definition at line 5924 of file y.tab.c.
P_BACKQUOTE
#define P_BACKQUOTE 0x0010 /* parsing a backquoted command substitution */
Definition at line 5923 of file y.tab.c.
P_COMMAND
#define P_COMMAND 0x0008 /* parsing a command, so look for comments */
Definition at line 5922 of file y.tab.c.
P_DOLBRACE
#define P_DOLBRACE 0x0040 /* parsing a ${...} construct */
Definition at line 5925 of file y.tab.c.
P_DQUOTE
#define P_DQUOTE 0x0004
Definition at line 5921 of file y.tab.c.
P_FIRSTCLOSE
#define P_FIRSTCLOSE 0x0001
Definition at line 5919 of file y.tab.c.
parsing_redirection
#define parsing_redirection (token)
Value:
  (token == '<' || token == '>' || \
   token == GREATER_GREATER || token == GREATER_BAR || \
   token == LESS_GREATER || token == LESS_LESS_MINUS || \
   token == LESS_LESS || token == LESS_LESS_LESS || \
   token == LESS_AND || token == GREATER_AND || token == AND_GREATER)
Definition at line 5269 of file y.tab.c.
pop_delimiter
#define pop_delimiter (ds) ds.delimiter_depth--
Definition at line 4608 of file y.tab.c.
PROMPT_GROWTH
#define PROMPT_GROWTH 48
Definition at line 7990 of file y.tab.c.
prompt_is_ps1
#define prompt_is_ps1 (!prompt_string_pointer || prompt_string_pointer == &ps1_prompt)
Definition at line 5172 of file y.tab.c.
PSH_ALIAS
#define PSH_ALIAS 0x01
Definition at line 4188 of file y.tab.c.
PSH_ARRAY
#define PSH_ARRAY 0x08
Definition at line 4191 of file y.tab.c.
PSH_DPAREN
#define PSH_DPAREN 0x02
Definition at line 4189 of file y.tab.c.
PSH_SOURCE
#define PSH_SOURCE 0x04
Definition at line 4190 of file y.tab.c.
push_delimiter
#define push_delimiter (ds, character)
Value:
  do \
    { \
      if (ds.delimiter_depth + 2 > ds.delimiter_space) \
    ds.delimiters = (char *)xrealloc \
      (ds.delimiters, (ds.delimiter_space += 10) * sizeof (char)); \
      ds.delimiters[ds.delimiter_depth] = character; \
      ds.delimiter_depth++; \
    } \
  while (0)
Definition at line 4597 of file y.tab.c.
RE_READ_TOKEN
#define RE_READ_TOKEN -99
Definition at line 145 of file y.tab.c.
READ
#define READ 0
Definition at line 5170 of file y.tab.c.
REDIR_WORD
#define REDIR_WORD 283
Definition at line 512 of file y.tab.c.
RESET
#define RESET 1
Definition at line 5171 of file y.tab.c.
SELECT
#define SELECT 266
Definition at line 495 of file y.tab.c.
SEMI_AND
#define SEMI_AND 296
Definition at line 525 of file y.tab.c.
SEMI_SEMI
#define SEMI_SEMI 295
Definition at line 524 of file y.tab.c.
SEMI_SEMI_AND
#define SEMI_SEMI_AND 297
Definition at line 526 of file y.tab.c.
set_line_mbstate
#define set_line_mbstate ()
Definition at line 274 of file y.tab.c.
SHOULD_PROMPT
#define SHOULD_PROMPT () (interactive && (bash_input.type == st_stdin || bash_input.type == st_stream))
Definition at line 3681 of file y.tab.c.
THEN
#define THEN 259
Definition at line 488 of file y.tab.c.
TIME
#define TIME 278
Definition at line 507 of file y.tab.c.
TIMEIGN
#define TIMEIGN 280
Definition at line 509 of file y.tab.c.
TIMEOPT
#define TIMEOPT 279
Definition at line 508 of file y.tab.c.
TOKEN_DEFAULT_GROW_SIZE
#define TOKEN_DEFAULT_GROW_SIZE 512
Definition at line 3678 of file y.tab.c.
TOKEN_DEFAULT_INITIAL_SIZE
#define TOKEN_DEFAULT_INITIAL_SIZE 496
Definition at line 3677 of file y.tab.c.
UNTIL
#define UNTIL 268
Definition at line 497 of file y.tab.c.
WHILE
#define WHILE 267
Definition at line 496 of file y.tab.c.
WORD
#define WORD 281
Definition at line 510 of file y.tab.c.
yacc_EOF
#define yacc_EOF 305
Definition at line 534 of file y.tab.c.
YY_
#define YY_ (Msgid) Msgid
Definition at line 799 of file y.tab.c.
YY_ACCESSING_SYMBOL
#define YY_ACCESSING_SYMBOL (State) YY_CAST (yysymbol_kind_t, yystos[State])
Accessing symbol of state STATE.
Definition at line 1082 of file y.tab.c.
YY_ASSERT
#define YY_ASSERT (E) ((void) (0 && (E)))
Definition at line 865 of file y.tab.c.
YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_PURE
Definition at line 808 of file y.tab.c.
YY_ATTRIBUTE_UNUSED
#define YY_ATTRIBUTE_UNUSED
Definition at line 816 of file y.tab.c.
YY_CAST
#define YY_CAST (Type, Val) ((Type) (Val))
Definition at line 394 of file y.tab.c.
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
Definition at line 845 of file y.tab.c.
YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
Definition at line 846 of file y.tab.c.
YY_IGNORE_USELESS_CAST_BEGIN
#define YY_IGNORE_USELESS_CAST_BEGIN
Definition at line 860 of file y.tab.c.
YY_IGNORE_USELESS_CAST_END
#define YY_IGNORE_USELESS_CAST_END
Definition at line 861 of file y.tab.c.
YY_INITIAL_VALUE
#define YY_INITIAL_VALUE (Value) Value
Definition at line 842 of file y.tab.c.
YY_NULLPTR
#define YY_NULLPTR ((void*)0)
Definition at line 406 of file y.tab.c.
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
Definition at line 1640 of file y.tab.c.
YY_REINTERPRET_CAST
#define YY_REINTERPRET_CAST (Type, Val) ((Type) (Val))
Definition at line 395 of file y.tab.c.
YY_STACK_PRINT
#define YY_STACK_PRINT (Bottom, Top)
Definition at line 1639 of file y.tab.c.
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Kind, Value, Location)
Definition at line 1638 of file y.tab.c.
YY_USE
#define YY_USE (E) ((void) (E))
Definition at line 822 of file y.tab.c.
YY_YY_Y_TAB_H_INCLUDED
#define YY_YY_Y_TAB_H_INCLUDED
Definition at line 413 of file y.tab.c.
YYABORT
#define YYABORT goto yyabortlab
Definition at line 1488 of file y.tab.c.
YYACCEPT
#define YYACCEPT goto yyacceptlab
Definition at line 1487 of file y.tab.c.
YYBACKUP
#define YYBACKUP (Token, Value)
Value:
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)
Definition at line 1495 of file y.tab.c.
YYBISON
#define YYBISON 30802
Definition at line 49 of file y.tab.c.
YYBISON_VERSION
#define YYBISON_VERSION "3.8.2"
Definition at line 52 of file y.tab.c.
yyclearin
#define yyclearin (yychar = YYEMPTY)
Definition at line 1485 of file y.tab.c.
YYCOPY
#define YYCOPY (Dst, Src, Count)
Value:
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
Definition at line 982 of file y.tab.c.
YYCOPY_NEEDED
#define YYCOPY_NEEDED 1
Definition at line 954 of file y.tab.c.
YYDEBUG
#define YYDEBUG 0
Definition at line 153 of file y.tab.c.
YYDPRINTF
#define YYDPRINTF (Args) ((void) 0)
Definition at line 1637 of file y.tab.c.
YYEMPTY
#define YYEMPTY -2
Definition at line 483 of file y.tab.c.
YYEOF
#define YYEOF 0
Definition at line 484 of file y.tab.c.
YYERRCODE
#define YYERRCODE YYUNDEF
Definition at line 1514 of file y.tab.c.
yyerrok
#define yyerrok (yyerrstatus = 0)
Definition at line 1484 of file y.tab.c.
YYerror
#define YYerror 256
Definition at line 485 of file y.tab.c.
YYERROR
#define YYERROR goto yyerrorlab
Definition at line 1489 of file y.tab.c.
YYFINAL
#define YYFINAL 121
Definition at line 995 of file y.tab.c.
YYFREE
#define YYFREE free
Definition at line 926 of file y.tab.c.
YYINITDEPTH
#define YYINITDEPTH 200
Definition at line 1646 of file y.tab.c.
YYLAST
#define YYLAST 740
Definition at line 997 of file y.tab.c.
YYMALLOC
#define YYMALLOC malloc
Definition at line 920 of file y.tab.c.
YYMAXDEPTH
#define YYMAXDEPTH 10000
Definition at line 1657 of file y.tab.c.
YYMAXUTOK
#define YYMAXUTOK 305
Definition at line 1009 of file y.tab.c.
YYNNTS
#define YYNNTS 38
Definition at line 1002 of file y.tab.c.
YYNOMEM
#define YYNOMEM goto yyexhaustedlab
Definition at line 1490 of file y.tab.c.
YYNRULES
#define YYNRULES 174
Definition at line 1004 of file y.tab.c.
YYNSTATES
#define YYNSTATES 349
Definition at line 1006 of file y.tab.c.
YYNTOKENS
#define YYNTOKENS 62
Definition at line 1000 of file y.tab.c.
YYPACT_NINF
#define YYPACT_NINF (-152)
Definition at line 1122 of file y.tab.c.
yypact_value_is_default
#define yypact_value_is_default (Yyn) ((Yyn) == YYPACT_NINF)
Definition at line 1124 of file y.tab.c.
YYPOPSTACK
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
YYPTRDIFF_MAXIMUM
#define YYPTRDIFF_MAXIMUM LONG_MAX
Definition at line 759 of file y.tab.c.
YYPTRDIFF_T
#define YYPTRDIFF_T long
Definition at line 758 of file y.tab.c.
YYPULL
#define YYPULL 1
Definition at line 64 of file y.tab.c.
YYPURE
#define YYPURE 0
Definition at line 58 of file y.tab.c.
YYPUSH
#define YYPUSH 0
Definition at line 61 of file y.tab.c.
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 1493 of file y.tab.c.
YYSIZE_MAXIMUM
#define YYSIZE_MAXIMUM
Value:
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))
Definition at line 776 of file y.tab.c.
YYSIZE_T
#define YYSIZE_T unsigned
Definition at line 772 of file y.tab.c.
YYSIZEOF
#define YYSIZEOF (X) YY_CAST (YYPTRDIFF_T, sizeof (X))
Definition at line 782 of file y.tab.c.
YYSKELETON_NAME
#define YYSKELETON_NAME "yacc.c"
Definition at line 55 of file y.tab.c.
YYSTACK_ALLOC
#define YYSTACK_ALLOC YYMALLOC
Definition at line 906 of file y.tab.c.
YYSTACK_ALLOC_MAXIMUM
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 909 of file y.tab.c.
YYSTACK_BYTES
#define YYSTACK_BYTES (N)
Value:
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 950 of file y.tab.c.
YYSTACK_FREE
#define YYSTACK_FREE YYFREE
Definition at line 907 of file y.tab.c.
YYSTACK_GAP_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)
Definition at line 946 of file y.tab.c.
YYSTACK_RELOCATE
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)
Definition at line 961 of file y.tab.c.
YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
Definition at line 555 of file y.tab.c.
YYSTYPE_IS_TRIVIAL
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 554 of file y.tab.c.
YYTABLE_NINF
#define YYTABLE_NINF (-1)
Definition at line 1127 of file y.tab.c.
yytable_value_is_error
#define yytable_value_is_error (Yyn) 0
Definition at line 1129 of file y.tab.c.
YYTOKENTYPE
#define YYTOKENTYPE
Definition at line 424 of file y.tab.c.
YYTRANSLATE
#define YYTRANSLATE (YYX)
Value:
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)
Definition at line 1014 of file y.tab.c.
YYUNDEF
#define YYUNDEF 257
Definition at line 486 of file y.tab.c.
Typedef Documentation
alias_t
typedef void* alias_t
Definition at line 130 of file y.tab.c.
STREAM_SAVER
typedef struct stream_saver STREAM_SAVER
STRING_SAVER
typedef struct string_saver STRING_SAVER
yy_state_fast_t
typedef int yy_state_fast_t
Definition at line 789 of file y.tab.c.
yy_state_t
typedef yytype_int16 yy_state_t
Definition at line 786 of file y.tab.c.
YYSTYPE
typedef union YYSTYPE YYSTYPE
Definition at line 385 of file y.tab.c.
yysymbol_kind_t
typedef enum yysymbol_kind_t yysymbol_kind_t
Definition at line 562 of file y.tab.c.
yytoken_kind_t
typedef enum yytokentype yytoken_kind_t
Definition at line 385 of file y.tab.c.
yytype_int16
typedef short yytype_int16
Definition at line 710 of file y.tab.c.
yytype_int8
typedef signed char yytype_int8
Definition at line 702 of file y.tab.c.
yytype_uint16
typedef unsigned short yytype_uint16
Definition at line 742 of file y.tab.c.
yytype_uint8
typedef unsigned char yytype_uint8
Definition at line 731 of file y.tab.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
YYENOMEM
Definition at line 1482 of file y.tab.c.
 { YYENOMEM = -2 };
yysymbol_kind_t
enum yysymbol_kind_t
Enumerator
YYSYMBOL_YYEMPTY
YYSYMBOL_YYEOF
YYSYMBOL_YYerror
YYSYMBOL_YYUNDEF
YYSYMBOL_IF
YYSYMBOL_THEN
YYSYMBOL_ELSE
YYSYMBOL_ELIF
YYSYMBOL_FI
YYSYMBOL_CASE
YYSYMBOL_ESAC
YYSYMBOL_FOR
YYSYMBOL_SELECT
YYSYMBOL_WHILE
YYSYMBOL_UNTIL
YYSYMBOL_DO
YYSYMBOL_DONE
YYSYMBOL_FUNCTION
YYSYMBOL_COPROC
YYSYMBOL_COND_START
YYSYMBOL_COND_END
YYSYMBOL_COND_ERROR
YYSYMBOL_IN
YYSYMBOL_BANG
YYSYMBOL_TIME
YYSYMBOL_TIMEOPT
YYSYMBOL_TIMEIGN
YYSYMBOL_WORD
YYSYMBOL_ASSIGNMENT_WORD
YYSYMBOL_REDIR_WORD
YYSYMBOL_NUMBER
YYSYMBOL_ARITH_CMD
YYSYMBOL_ARITH_FOR_EXPRS
YYSYMBOL_COND_CMD
YYSYMBOL_AND_AND
YYSYMBOL_OR_OR
YYSYMBOL_GREATER_GREATER
YYSYMBOL_LESS_LESS
YYSYMBOL_LESS_AND
YYSYMBOL_LESS_LESS_LESS
YYSYMBOL_GREATER_AND
YYSYMBOL_SEMI_SEMI
YYSYMBOL_SEMI_AND
YYSYMBOL_SEMI_SEMI_AND
YYSYMBOL_LESS_LESS_MINUS
YYSYMBOL_AND_GREATER
YYSYMBOL_AND_GREATER_GREATER
YYSYMBOL_LESS_GREATER
YYSYMBOL_GREATER_BAR
YYSYMBOL_BAR_AND
YYSYMBOL_DOLPAREN
YYSYMBOL_50_
YYSYMBOL_51_
YYSYMBOL_52_n_
YYSYMBOL_yacc_EOF
YYSYMBOL_54_
YYSYMBOL_55_
YYSYMBOL_56_
YYSYMBOL_57_
YYSYMBOL_58_
YYSYMBOL_59_
YYSYMBOL_60_
YYSYMBOL_61_
YYSYMBOL_YYACCEPT
YYSYMBOL_inputunit
YYSYMBOL_word_list
YYSYMBOL_redirection
YYSYMBOL_simple_command_element
YYSYMBOL_redirection_list
YYSYMBOL_simple_command
YYSYMBOL_command
YYSYMBOL_shell_command
YYSYMBOL_for_command
YYSYMBOL_arith_for_command
YYSYMBOL_select_command
YYSYMBOL_case_command
YYSYMBOL_function_def
YYSYMBOL_function_body
YYSYMBOL_subshell
YYSYMBOL_comsub
YYSYMBOL_coproc
YYSYMBOL_if_command
YYSYMBOL_group_command
YYSYMBOL_arith_command
YYSYMBOL_cond_command
YYSYMBOL_elif_clause
YYSYMBOL_case_clause
YYSYMBOL_pattern_list
YYSYMBOL_case_clause_sequence
YYSYMBOL_pattern
YYSYMBOL_compound_list
YYSYMBOL_list0
YYSYMBOL_list1
YYSYMBOL_simple_list_terminator
YYSYMBOL_list_terminator
YYSYMBOL_newline_list
YYSYMBOL_simple_list
YYSYMBOL_simple_list1
YYSYMBOL_pipeline_command
YYSYMBOL_pipeline
YYSYMBOL_timespec
Definition at line 567 of file y.tab.c.
 {
   YYSYMBOL_YYEMPTY = -2,
   YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
   YYSYMBOL_YYerror = 1,                    /* error  */
   YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
   YYSYMBOL_IF = 3,                         /* IF  */
   YYSYMBOL_THEN = 4,                       /* THEN  */
   YYSYMBOL_ELSE = 5,                       /* ELSE  */
   YYSYMBOL_ELIF = 6,                       /* ELIF  */
   YYSYMBOL_FI = 7,                         /* FI  */
   YYSYMBOL_CASE = 8,                       /* CASE  */
   YYSYMBOL_ESAC = 9,                       /* ESAC  */
   YYSYMBOL_FOR = 10,                       /* FOR  */
   YYSYMBOL_SELECT = 11,                    /* SELECT  */
   YYSYMBOL_WHILE = 12,                     /* WHILE  */
   YYSYMBOL_UNTIL = 13,                     /* UNTIL  */
   YYSYMBOL_DO = 14,                        /* DO  */
   YYSYMBOL_DONE = 15,                      /* DONE  */
   YYSYMBOL_FUNCTION = 16,                  /* FUNCTION  */
   YYSYMBOL_COPROC = 17,                    /* COPROC  */
   YYSYMBOL_COND_START = 18,                /* COND_START  */
   YYSYMBOL_COND_END = 19,                  /* COND_END  */
   YYSYMBOL_COND_ERROR = 20,                /* COND_ERROR  */
   YYSYMBOL_IN = 21,                        /* IN  */
   YYSYMBOL_BANG = 22,                      /* BANG  */
   YYSYMBOL_TIME = 23,                      /* TIME  */
   YYSYMBOL_TIMEOPT = 24,                   /* TIMEOPT  */
   YYSYMBOL_TIMEIGN = 25,                   /* TIMEIGN  */
   YYSYMBOL_WORD = 26,                      /* WORD  */
   YYSYMBOL_ASSIGNMENT_WORD = 27,           /* ASSIGNMENT_WORD  */
   YYSYMBOL_REDIR_WORD = 28,                /* REDIR_WORD  */
   YYSYMBOL_NUMBER = 29,                    /* NUMBER  */
   YYSYMBOL_ARITH_CMD = 30,                 /* ARITH_CMD  */
   YYSYMBOL_ARITH_FOR_EXPRS = 31,           /* ARITH_FOR_EXPRS  */
   YYSYMBOL_COND_CMD = 32,                  /* COND_CMD  */
   YYSYMBOL_AND_AND = 33,                   /* AND_AND  */
   YYSYMBOL_OR_OR = 34,                     /* OR_OR  */
   YYSYMBOL_GREATER_GREATER = 35,           /* GREATER_GREATER  */
   YYSYMBOL_LESS_LESS = 36,                 /* LESS_LESS  */
   YYSYMBOL_LESS_AND = 37,                  /* LESS_AND  */
   YYSYMBOL_LESS_LESS_LESS = 38,            /* LESS_LESS_LESS  */
   YYSYMBOL_GREATER_AND = 39,               /* GREATER_AND  */
   YYSYMBOL_SEMI_SEMI = 40,                 /* SEMI_SEMI  */
   YYSYMBOL_SEMI_AND = 41,                  /* SEMI_AND  */
   YYSYMBOL_SEMI_SEMI_AND = 42,             /* SEMI_SEMI_AND  */
   YYSYMBOL_LESS_LESS_MINUS = 43,           /* LESS_LESS_MINUS  */
   YYSYMBOL_AND_GREATER = 44,               /* AND_GREATER  */
   YYSYMBOL_AND_GREATER_GREATER = 45,       /* AND_GREATER_GREATER  */
   YYSYMBOL_LESS_GREATER = 46,              /* LESS_GREATER  */
   YYSYMBOL_GREATER_BAR = 47,               /* GREATER_BAR  */
   YYSYMBOL_BAR_AND = 48,                   /* BAR_AND  */
   YYSYMBOL_DOLPAREN = 49,                  /* DOLPAREN  */
   YYSYMBOL_50_ = 50,                       /* '&'  */
   YYSYMBOL_51_ = 51,                       /* ';'  */
   YYSYMBOL_52_n_ = 52,                     /* '\n'  */
   YYSYMBOL_yacc_EOF = 53,                  /* yacc_EOF  */
   YYSYMBOL_54_ = 54,                       /* '|'  */
   YYSYMBOL_55_ = 55,                       /* '>'  */
   YYSYMBOL_56_ = 56,                       /* '<'  */
   YYSYMBOL_57_ = 57,                       /* '-'  */
   YYSYMBOL_58_ = 58,                       /* '{'  */
   YYSYMBOL_59_ = 59,                       /* '}'  */
   YYSYMBOL_60_ = 60,                       /* '('  */
   YYSYMBOL_61_ = 61,                       /* ')'  */
   YYSYMBOL_YYACCEPT = 62,                  /* $accept  */
   YYSYMBOL_inputunit = 63,                 /* inputunit  */
   YYSYMBOL_word_list = 64,                 /* word_list  */
   YYSYMBOL_redirection = 65,               /* redirection  */
   YYSYMBOL_simple_command_element = 66,    /* simple_command_element  */
   YYSYMBOL_redirection_list = 67,          /* redirection_list  */
   YYSYMBOL_simple_command = 68,            /* simple_command  */
   YYSYMBOL_command = 69,                   /* command  */
   YYSYMBOL_shell_command = 70,             /* shell_command  */
   YYSYMBOL_for_command = 71,               /* for_command  */
   YYSYMBOL_arith_for_command = 72,         /* arith_for_command  */
   YYSYMBOL_select_command = 73,            /* select_command  */
   YYSYMBOL_case_command = 74,              /* case_command  */
   YYSYMBOL_function_def = 75,              /* function_def  */
   YYSYMBOL_function_body = 76,             /* function_body  */
   YYSYMBOL_subshell = 77,                  /* subshell  */
   YYSYMBOL_comsub = 78,                    /* comsub  */
   YYSYMBOL_coproc = 79,                    /* coproc  */
   YYSYMBOL_if_command = 80,                /* if_command  */
   YYSYMBOL_group_command = 81,             /* group_command  */
   YYSYMBOL_arith_command = 82,             /* arith_command  */
   YYSYMBOL_cond_command = 83,              /* cond_command  */
   YYSYMBOL_elif_clause = 84,               /* elif_clause  */
   YYSYMBOL_case_clause = 85,               /* case_clause  */
   YYSYMBOL_pattern_list = 86,              /* pattern_list  */
   YYSYMBOL_case_clause_sequence = 87,      /* case_clause_sequence  */
   YYSYMBOL_pattern = 88,                   /* pattern  */
   YYSYMBOL_compound_list = 89,             /* compound_list  */
   YYSYMBOL_list0 = 90,                     /* list0  */
   YYSYMBOL_list1 = 91,                     /* list1  */
   YYSYMBOL_simple_list_terminator = 92,    /* simple_list_terminator  */
   YYSYMBOL_list_terminator = 93,           /* list_terminator  */
   YYSYMBOL_newline_list = 94,              /* newline_list  */
   YYSYMBOL_simple_list = 95,               /* simple_list  */
   YYSYMBOL_simple_list1 = 96,              /* simple_list1  */
   YYSYMBOL_pipeline_command = 97,          /* pipeline_command  */
   YYSYMBOL_pipeline = 98,                  /* pipeline  */
   YYSYMBOL_timespec = 99                   /* timespec  */
 };
yytokentype
enum yytokentype
Enumerator
EQUOP2
CMPOP2
ADDOP2
MULOP2
NUMBER
YYEMPTY
YYEOF
YYerror
YYUNDEF
IF
THEN
ELSE
ELIF
FI
CASE
ESAC
FOR
SELECT
WHILE
UNTIL
DO
DONE
FUNCTION
COPROC
COND_START
COND_END
COND_ERROR
IN
BANG
TIME
TIMEOPT
TIMEIGN
WORD
ASSIGNMENT_WORD
REDIR_WORD
NUMBER
ARITH_CMD
ARITH_FOR_EXPRS
COND_CMD
AND_AND
OR_OR
GREATER_GREATER
LESS_LESS
LESS_AND
LESS_LESS_LESS
GREATER_AND
SEMI_SEMI
SEMI_AND
SEMI_SEMI_AND
LESS_LESS_MINUS
AND_GREATER
AND_GREATER_GREATER
LESS_GREATER
GREATER_BAR
BAR_AND
DOLPAREN
yacc_EOF
YYEMPTY
YYEOF
YYerror
YYUNDEF
IF
THEN
ELSE
ELIF
FI
CASE
ESAC
FOR
SELECT
WHILE
UNTIL
DO
DONE
FUNCTION
COPROC
COND_START
COND_END
COND_ERROR
IN
BANG
TIME
TIMEOPT
TIMEIGN
WORD
ASSIGNMENT_WORD
REDIR_WORD
NUMBER
ARITH_CMD
ARITH_FOR_EXPRS
COND_CMD
AND_AND
OR_OR
GREATER_GREATER
LESS_LESS
LESS_AND
LESS_LESS_LESS
GREATER_AND
SEMI_SEMI
SEMI_AND
SEMI_SEMI_AND
LESS_LESS_MINUS
AND_GREATER
AND_GREATER_GREATER
LESS_GREATER
GREATER_BAR
BAR_AND
DOLPAREN
yacc_EOF
Definition at line 425 of file y.tab.c.
   {
     YYEMPTY = -2,
     YYEOF = 0,                     /* "end of file"  */
     YYerror = 256,                 /* error  */
     YYUNDEF = 257,                 /* "invalid token"  */
     IF = 258,                      /* IF  */
     THEN = 259,                    /* THEN  */
     ELSE = 260,                    /* ELSE  */
     ELIF = 261,                    /* ELIF  */
     FI = 262,                      /* FI  */
     CASE = 263,                    /* CASE  */
     ESAC = 264,                    /* ESAC  */
     FOR = 265,                     /* FOR  */
     SELECT = 266,                  /* SELECT  */
     WHILE = 267,                   /* WHILE  */
     UNTIL = 268,                   /* UNTIL  */
     DO = 269,                      /* DO  */
     DONE = 270,                    /* DONE  */
     FUNCTION = 271,                /* FUNCTION  */
     COPROC = 272,                  /* COPROC  */
     COND_START = 273,              /* COND_START  */
     COND_END = 274,                /* COND_END  */
     COND_ERROR = 275,              /* COND_ERROR  */
     IN = 276,                      /* IN  */
     BANG = 277,                    /* BANG  */
     TIME = 278,                    /* TIME  */
     TIMEOPT = 279,                 /* TIMEOPT  */
     TIMEIGN = 280,                 /* TIMEIGN  */
     WORD = 281,                    /* WORD  */
     ASSIGNMENT_WORD = 282,         /* ASSIGNMENT_WORD  */
     REDIR_WORD = 283,              /* REDIR_WORD  */
     NUMBER = 284,                  /* NUMBER  */
     ARITH_CMD = 285,               /* ARITH_CMD  */
     ARITH_FOR_EXPRS = 286,         /* ARITH_FOR_EXPRS  */
     COND_CMD = 287,                /* COND_CMD  */
     AND_AND = 288,                 /* AND_AND  */
     OR_OR = 289,                   /* OR_OR  */
     GREATER_GREATER = 290,         /* GREATER_GREATER  */
     LESS_LESS = 291,               /* LESS_LESS  */
     LESS_AND = 292,                /* LESS_AND  */
     LESS_LESS_LESS = 293,          /* LESS_LESS_LESS  */
     GREATER_AND = 294,             /* GREATER_AND  */
     SEMI_SEMI = 295,               /* SEMI_SEMI  */
     SEMI_AND = 296,                /* SEMI_AND  */
     SEMI_SEMI_AND = 297,           /* SEMI_SEMI_AND  */
     LESS_LESS_MINUS = 298,         /* LESS_LESS_MINUS  */
     AND_GREATER = 299,             /* AND_GREATER  */
     AND_GREATER_GREATER = 300,     /* AND_GREATER_GREATER  */
     LESS_GREATER = 301,            /* LESS_GREATER  */
     GREATER_BAR = 302,             /* GREATER_BAR  */
     BAR_AND = 303,                 /* BAR_AND  */
     DOLPAREN = 304,                /* DOLPAREN  */
     yacc_EOF = 305                 /* yacc_EOF  */
   };
Function Documentation
clear_shell_input_line()
void clear_shell_input_line ()
Definition at line 4365 of file y.tab.c.
 {
   if (shell_input_line)
     shell_input_line[shell_input_line_index = 0] = '\0';
 }
References shell_input_line, and shell_input_line_index.
Referenced by parse_and_execute(), parse_string_to_command(), and xparse_dolparen().
decode_prompt_string()
char* decode_prompt_string (char * string)
Definition at line 7992 of file y.tab.c.
 {
   WORD_LIST *list;
   char *result, *t, *orig_string;
   struct dstack save_dstack;
   int last_exit_value, last_comsub_pid;
 #if defined (PROMPT_STRING_DECODE)
   size_t result_size;
   size_t result_index;
   int c, n, i;
   char *temp, *t_host, octal_string[4];
   struct tm *tm;
   time_t the_time;
   char timebuf[128];
   char *timefmt;
   result = (char *)xmalloc (result_size = PROMPT_GROWTH);
   result[result_index = 0] = 0;
   temp = (char *)NULL;
   orig_string = string;
   while (c = *string++)
     {
       if (posixly_correct && c == '!')
     {
       if (*string == '!')
         {
           temp = savestring ("!");
           goto add_string;
         }
       else
         {
 #if !defined (HISTORY)
         temp = savestring ("1");
 #else /* HISTORY */
         temp = itos (prompt_history_number (orig_string));
 #endif /* HISTORY */
         string--;   /* add_string increments string again. */
         goto add_string;
         }
     }
       if (c == '\\')
     {
       c = *string;
       switch (c)
         {
         case '0':
         case '1':
         case '2':
         case '3':
         case '4':
         case '5':
         case '6':
         case '7':
           strncpy (octal_string, string, 3);
           octal_string[3] = '\0';
           n = read_octal (octal_string);
           temp = (char *)xmalloc (3);
           if (n == CTLESC || n == CTLNUL)
         {
           temp[0] = CTLESC;
           temp[1] = n;
           temp[2] = '\0';
         }
           else if (n == -1)
         {
           temp[0] = '\\';
           temp[1] = '\0';
         }
           else
         {
           temp[0] = n;
           temp[1] = '\0';
         }
           for (c = 0; n != -1 && c < 3 && ISOCTAL (*string); c++)
         string++;
           c = 0;        /* tested at add_string: */
           goto add_string;
         case 'd':
         case 't':
         case 'T':
         case '@':
         case 'A':
           /* Make the current time/date into a string. */
           (void) time (&the_time);
 #if defined (HAVE_TZSET)
           sv_tz ("TZ");     /* XXX -- just make sure */
 #endif
           tm = localtime (&the_time);
           if (c == 'd')
         n = strftime (timebuf, sizeof (timebuf), "%a %b %d", tm);
           else if (c == 't')
         n = strftime (timebuf, sizeof (timebuf), "%H:%M:%S", tm);
           else if (c == 'T')
         n = strftime (timebuf, sizeof (timebuf), "%I:%M:%S", tm);
           else if (c == '@')
         n = strftime (timebuf, sizeof (timebuf), "%I:%M %p", tm);
           else if (c == 'A')
         n = strftime (timebuf, sizeof (timebuf), "%H:%M", tm);
           if (n == 0)
         timebuf[0] = '\0';
           else
         timebuf[sizeof(timebuf) - 1] = '\0';
           temp = savestring (timebuf);
           goto add_string;
         case 'D':       /* strftime format */
           if (string[1] != '{')     /* } */
         goto not_escape;
           (void) time (&the_time);
           tm = localtime (&the_time);
           string += 2;          /* skip { */
           timefmt = xmalloc (strlen (string) + 3);
           for (t = timefmt; *string && *string != '}'; )
         *t++ = *string++;
           *t = '\0';
           c = *string;  /* tested at add_string */
           if (timefmt[0] == '\0')
         {
           timefmt[0] = '%';
           timefmt[1] = 'X'; /* locale-specific current time */
           timefmt[2] = '\0';
         }
           n = strftime (timebuf, sizeof (timebuf), timefmt, tm);
           free (timefmt);
           if (n == 0)
         timebuf[0] = '\0';
           else
         timebuf[sizeof(timebuf) - 1] = '\0';
           if (promptvars || posixly_correct)
         /* Make sure that expand_prompt_string is called with a
            second argument of Q_DOUBLE_QUOTES if we use this
            function here. */
         temp = sh_backslash_quote_for_double_quotes (timebuf, 0);
           else
         temp = savestring (timebuf);
           goto add_string;
         case 'n':
           temp = (char *)xmalloc (3);
           temp[0] = no_line_editing ? '\n' : '\r';
           temp[1] = no_line_editing ? '\0' : '\n';
           temp[2] = '\0';
           goto add_string;
         case 's':
           temp = base_pathname (shell_name);
           /* Try to quote anything the user can set in the file system */
           if (promptvars || posixly_correct)
         {
           char *t;
           t = sh_strvis (temp);
           temp = sh_backslash_quote_for_double_quotes (t, 0);
           free (t);
         }
           else
         temp = sh_strvis (temp);
           goto add_string;
         case 'v':
         case 'V':
           temp = (char *)xmalloc (16);
           if (c == 'v')
         strcpy (temp, dist_version);
           else
         sprintf (temp, "%s.%d", dist_version, patch_level);
           goto add_string;
         case 'w':
         case 'W':
           {
         /* Use the value of PWD because it is much more efficient. */
         char t_string[PATH_MAX];
         int tlen;
         temp = get_string_value ("PWD");
         if (temp == 0)
           {
             if (getcwd (t_string, sizeof(t_string)) == 0)
               {
             t_string[0] = '.';
             tlen = 1;
               }
             else
               tlen = strlen (t_string);
           }
         else
           {
             tlen = sizeof (t_string) - 1;
             strncpy (t_string, temp, tlen);
           }
         t_string[tlen] = '\0';
 #if defined (MACOSX)
         /* Convert from "fs" format to "input" format */
         temp = fnx_fromfs (t_string, strlen (t_string));
         if (temp != t_string)
           strcpy (t_string, temp);
 #endif
 #define ROOT_PATH(x)    ((x)[0] == '/' && (x)[1] == 0)
 #define DOUBLE_SLASH_ROOT(x)    ((x)[0] == '/' && (x)[1] == '/' && (x)[2] == 0)
         /* Abbreviate \W as ~ if $PWD == $HOME */
         if (c == 'W' && (((t = get_string_value ("HOME")) == 0) || STREQ (t, t_string) == 0))
           {
             if (ROOT_PATH (t_string) == 0 && DOUBLE_SLASH_ROOT (t_string) == 0)
               {
             t = strrchr (t_string, '/');
             if (t)
               memmove (t_string, t + 1, strlen (t));    /* strlen(t) to copy NULL */
               }
           }
 #undef ROOT_PATH
 #undef DOUBLE_SLASH_ROOT
         else
           {
             /* polite_directory_format is guaranteed to return a string
                no longer than PATH_MAX - 1 characters. */
             temp = polite_directory_format (t_string);
             if (temp != t_string)
               strcpy (t_string, temp);
           }
         temp = trim_pathname (t_string, PATH_MAX - 1);
         /* If we're going to be expanding the prompt string later,
            quote the directory name. */
         if (promptvars || posixly_correct)
           /* Make sure that expand_prompt_string is called with a
              second argument of Q_DOUBLE_QUOTES if we use this
              function here. */
           {
             char *t;
             t = sh_strvis (t_string);
             temp = sh_backslash_quote_for_double_quotes (t, 0);
             free (t);
           }
         else
           temp = sh_strvis (t_string);
         goto add_string;
           }
         case 'u':
           if (current_user.user_name == 0)
         get_current_user_info ();
           temp = savestring (current_user.user_name);
           goto add_string;
         case 'h':
         case 'H':
           t_host = savestring (current_host_name);
           if (c == 'h' && (t = (char *)strchr (t_host, '.')))
         *t = '\0';
           if (promptvars || posixly_correct)
         /* Make sure that expand_prompt_string is called with a
            second argument of Q_DOUBLE_QUOTES if we use this
            function here. */
         temp = sh_backslash_quote_for_double_quotes (t_host, 0);
           else
         temp = savestring (t_host);
           free (t_host);
           goto add_string;
         case '#':
           n = current_command_number;
           /* If we have already incremented current_command_number (PS4,
          ${var@P}), compensate */
           if (orig_string != ps0_prompt && orig_string != ps1_prompt && orig_string != ps2_prompt)
         n--;
           temp = itos (n);
           goto add_string;
         case '!':
 #if !defined (HISTORY)
           temp = savestring ("1");
 #else /* HISTORY */
           temp = itos (prompt_history_number (orig_string));
 #endif /* HISTORY */
           goto add_string;
         case '$':
           t = temp = (char *)xmalloc (3);
           if ((promptvars || posixly_correct) && (current_user.euid != 0))
         *t++ = '\\';
           *t++ = current_user.euid == 0 ? '#' : '$';
           *t = '\0';
           goto add_string;
         case 'j':
           temp = itos (count_all_jobs ());
           goto add_string;
         case 'l':
 #if defined (HAVE_TTYNAME)
           temp = (char *)ttyname (fileno (stdin));
           t = temp ? base_pathname (temp) : "tty";
           temp = savestring (t);
 #else
           temp = savestring ("tty");
 #endif /* !HAVE_TTYNAME */
           goto add_string;
 #if defined (READLINE)
         case '[':
         case ']':
           if (no_line_editing)
         {
           string++;
           break;
         }
           temp = (char *)xmalloc (3);
           n = (c == '[') ? RL_PROMPT_START_IGNORE : RL_PROMPT_END_IGNORE;
           i = 0;
           if (n == CTLESC || n == CTLNUL)
         temp[i++] = CTLESC;
           temp[i++] = n;
           temp[i] = '\0';
           goto add_string;
 #endif /* READLINE */
         case '\\':
         case 'a':
         case 'e':
         case 'r':
           temp = (char *)xmalloc (2);
           if (c == 'a')
         temp[0] = '\07';
           else if (c == 'e')
         temp[0] = '\033';
           else if (c == 'r')
         temp[0] = '\r';
           else          /* (c == '\\') */
             temp[0] = c;
           temp[1] = '\0';
           goto add_string;
         default:
 not_escape:
           temp = (char *)xmalloc (3);
           temp[0] = '\\';
           temp[1] = c;
           temp[2] = '\0';
         add_string:
           if (c)
         string++;
           result =
         sub_append_string (temp, result, &result_index, &result_size);
           temp = (char *)NULL; /* Freed in sub_append_string (). */
           result[result_index] = '\0';
           break;
         }
     }
       else
     {
       RESIZE_MALLOCED_BUFFER (result, result_index, 3, result_size, PROMPT_GROWTH);
       /* dequote_string should take care of removing this if we are not
          performing the rest of the word expansions. */
       if (c == CTLESC || c == CTLNUL)
         result[result_index++] = CTLESC;
       result[result_index++] = c;
       result[result_index] = '\0';
     }
     }
 #else /* !PROMPT_STRING_DECODE */
   result = savestring (string);
 #endif /* !PROMPT_STRING_DECODE */
   /* Save the delimiter stack and point `dstack' to temp space so any
      command substitutions in the prompt string won't result in screwing
      up the parser's quoting state. */
   save_dstack = dstack;
   dstack = temp_dstack;
   dstack.delimiter_depth = 0;
   /* Perform variable and parameter expansion and command substitution on
      the prompt string. */
   if (promptvars || posixly_correct)
     {
       last_exit_value = last_command_exit_value;
       last_comsub_pid = last_command_subst_pid;
       list = expand_prompt_string (result, Q_DOUBLE_QUOTES, 0);
       free (result);
       result = string_list (list);
       dispose_words (list);
       last_command_exit_value = last_exit_value;
       last_command_subst_pid = last_comsub_pid;
     }
   else
     {
       t = dequote_string (result);
       free (result);
       result = t;
     }
   dstack = save_dstack;
   return (result);
 }
References base_pathname(), c, count_all_jobs(), CTLESC, CTLNUL, current_command_number, current_host_name, current_user, dstack::delimiter_depth, dequote_string(), dispose_words(), dist_version, dstack, user_info::euid, expand_prompt_string(), fileno(), fnx_fromfs(), free(), get_current_user_info(), get_string_value(), getcwd, i, ISOCTAL, itos(), last_command_exit_value, last_command_subst_pid, list(), localtime(), memmove, n, no_line_editing, NULL, patch_level, PATH_MAX, polite_directory_format(), posixly_correct, PROMPT_GROWTH, promptvars, ps0_prompt, ps1_prompt, ps2_prompt, Q_DOUBLE_QUOTES, read_octal(), RESIZE_MALLOCED_BUFFER, RL_PROMPT_END_IGNORE, RL_PROMPT_START_IGNORE, savestring(), sh_strvis(), shell_name, sprintf(), stdin, strchr(), strcpy, STREQ, strftime(), string, string_list(), strlen(), strncpy(), strrchr(), sub_append_string(), t, t_string, temp_dstack, time(), timebuf, trim_pathname(), ttyname(), user_info::user_name, Driver::void(), and xmalloc.
Referenced by indirection_level_string(), prompt_again(), reader_loop(), and string_transform().
discard_parser_constructs()
static void discard_parser_constructs (int error_p) static
Definition at line 8606 of file y.tab.c.
 {
 }
discard_until()
static void discard_until (int character) static
Definition at line 5117 of file y.tab.c.
 {
   int c;
   while ((c = shell_getc (0)) != EOF && c != character)
     ;
   if (c != EOF)
     shell_ungetc (c);
 }
References c, EOF, shell_getc(), and shell_ungetc().
Referenced by read_token().
error_token_from_text()
static char* error_token_from_text () static
Definition at line 8465 of file y.tab.c.
 {
   char *msg, *t;
   int token_end, i;
   t = shell_input_line;
   i = shell_input_line_index;
   token_end = 0;
   msg = (char *)NULL;
   if (i && t[i] == '\0')
     i--;
   while (i && (whitespace (t[i]) || t[i] == '\n'))
     i--;
   if (i)
     token_end = i + 1;
   while (i && (member (t[i], " \n\t;|&") == 0))
     i--;
   while (i != token_end && (whitespace (t[i]) || t[i] == '\n'))
     i++;
   /* Return our idea of the offending token. */
   if (token_end || (i == 0 && token_end == 0))
     {
       if (token_end)
     msg = substring (t, i, token_end);
       else  /* one-character token */
     {
       msg = (char *)xmalloc (2);
       msg[0] = t[i];
       msg[1] = '\0';
     }
     }
   return (msg);
 }
References i, member, NULL, shell_input_line, shell_input_line_index, substring(), t, whitespace, and xmalloc.
Referenced by report_syntax_error().
error_token_from_token()
static char* error_token_from_token (int tok) static
Definition at line 8425 of file y.tab.c.
 {
   char *t;
   if (t = find_token_in_alist (tok, word_token_alist, 0))
     return t;
   if (t = find_token_in_alist (tok, other_token_alist, 0))
     return t;
   t = (char *)NULL;
   /* This stuff is dicy and needs closer inspection */
   switch (current_token)
     {
     case WORD:
     case ASSIGNMENT_WORD:
       if (yylval.word)
     t = savestring (yylval.word->word);
       break;
     case NUMBER:
       t = itos (yylval.number);
       break;
     case ARITH_CMD:
       if (yylval.word_list)
         t = string_list (yylval.word_list);
       break;
     case ARITH_FOR_EXPRS:
       if (yylval.word_list)
     t = string_list_internal (yylval.word_list, " ; ");
       break;
     case COND_CMD:
       t = (char *)NULL;     /* punt */
       break;
     }
   return t;
 }
References ARITH_CMD, ARITH_FOR_EXPRS, ASSIGNMENT_WORD, COND_CMD, current_token, find_token_in_alist(), itos(), NULL, NUMBER, YYSTYPE::number, other_token_alist, savestring(), string_list(), string_list_internal(), t, word_desc::word, WORD, YYSTYPE::word, YYSTYPE::word_list, word_token_alist, and yylval.
Referenced by report_syntax_error().
execute_variable_command()
void execute_variable_command (char * command, char * vname)
Definition at line 5130 of file y.tab.c.
 {
   char *last_lastarg;
   sh_parser_state_t ps;
   save_parser_state (&ps);
   last_lastarg = get_string_value ("_");
   if (last_lastarg)
     last_lastarg = savestring (last_lastarg);
   parse_and_execute (savestring (command), vname, SEVAL_NONINT|SEVAL_NOHIST|SEVAL_NOOPTIMIZE);
   restore_parser_state (&ps);
   bind_variable ("_", last_lastarg, 0);
   FREE (last_lastarg);
   if (token_to_read == '\n')    /* reset_parser was called */
     token_to_read = 0;
 }
References bind_variable(), FREE, get_string_value(), parse_and_execute(), restore_parser_state(), save_parser_state(), savestring(), SEVAL_NOHIST, SEVAL_NONINT, SEVAL_NOOPTIMIZE, and token_to_read.
Referenced by execute_prompt_command().
find_reserved_word()
int find_reserved_word (char * tokstr)
Definition at line 7713 of file y.tab.c.
 {
   int i;
   for (i = 0; word_token_alist[i].word; i++)
     if (STREQ (tokstr, word_token_alist[i].word))
       return i;
   return -1;
 }
References i, STREQ, tokstr, STRING_INT_ALIST::word, and word_token_alist.
Referenced by named_function_string().
free_pushed_string_input()
void free_pushed_string_input ()
Definition at line 4312 of file y.tab.c.
 {
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   free_string_list ();
 #endif
 }
References free_string_list().
Referenced by command_substitute().
free_string_list()
static void free_string_list () static
Definition at line 4293 of file y.tab.c.
 {
   register STRING_SAVER *t, *t1;
   for (t = pushed_string_list; t; )
     {
       t1 = t->next;
       FREE (t->saved_line);
 #if defined (ALIAS)
       if (t->expander)
     t->expander->flags &= ~AL_BEINGEXPANDED;
 #endif
       free ((char *)t);
       t = t1;
     }
   pushed_string_list = (STRING_SAVER *)NULL;
 }
References AL_BEINGEXPANDED, FREE, free(), NULL, pushed_string_list, t, and t1.
Referenced by free_pushed_string_input(), and reset_parser().
gather_here_documents()
void gather_here_documents ()
Definition at line 5243 of file y.tab.c.
 {
   int r;
   r = 0;
   here_doc_first_line = 1;
   while (need_here_doc > 0)
     {
       parser_state |= PST_HEREDOC;
       make_here_document (redir_stack[r++], line_number);
       parser_state &= ~PST_HEREDOC;
       need_here_doc--;
       redir_stack[r - 1] = 0;       /* XXX */
     }
   here_doc_first_line = 0;      /* just in case */
 }
References here_doc_first_line, line_number, make_here_document(), need_here_doc, parser_state, PST_HEREDOC, and redir_stack.
Referenced by parse_command(), parse_comsub(), read_token(), and yyparse().
get_current_prompt_level()
int get_current_prompt_level ()
Definition at line 7914 of file y.tab.c.
 {
   return ((current_prompt_string && current_prompt_string == ps2_prompt) ? 2 : 1);
 }
References current_prompt_string, and ps2_prompt.
Referenced by parse_prologue().
handle_eof_input_unit()
static void handle_eof_input_unit () static
Definition at line 8635 of file y.tab.c.
 {
   if (interactive)
     {
       /* shell.c may use this to decide whether or not to write out the
      history, among other things.  We use it only for error reporting
      in this file. */
       if (EOF_Reached)
     EOF_Reached = 0;
       /* If the user wants to "ignore" eof, then let her do so, kind of. */
       if (ignoreeof)
     {
       if (eof_encountered < eof_encountered_limit)
         {
           fprintf (stderr, _("Use \"%s\" to leave the shell.\n"),
                login_shell ? "logout" : "exit");
           eof_encountered++;
           /* Reset the parsing state. */
           last_read_token = current_token = '\n';
           /* Reset the prompt string to be $PS1. */
           prompt_string_pointer = (char **)NULL;
           prompt_again (0);
           return;
         }
     }
       /* In this case EOF should exit the shell.  Do it now. */
       reset_parser ();
       last_shell_builtin = this_shell_builtin;
       this_shell_builtin = exit_builtin;
       exit_builtin ((WORD_LIST *)NULL);
     }
   else
     {
       /* We don't write history files, etc., for non-interactive shells. */
       EOF_Reached = 1;
     }
 }
References _, current_token, eof_encountered, eof_encountered_limit, EOF_Reached, fprintf(), ignoreeof, interactive, last_read_token, last_shell_builtin, login_shell, NULL, prompt_again(), prompt_string_pointer, reset_parser(), stderr, and this_shell_builtin.
Referenced by yyparse().
init_yy_io()
void init_yy_io (sh_cget_func_t * get, sh_cunget_func_t * unget, enum stream_type type, const char * name, INPUT_STREAM location)
Definition at line 3742 of file y.tab.c.
 {
   bash_input.type = type;
   FREE (bash_input.name);
   bash_input.name = name ? savestring (name) : (char *)NULL;
   /* XXX */
 #if defined (CRAY)
   memcpy((char *)&bash_input.location.string, (char *)&location.string, sizeof(location));
 #else
   bash_input.location = location;
 #endif
   bash_input.getter = get;
   bash_input.ungetter = unget;
 }
References bash_input, FREE, get(), BASH_INPUT::getter, BASH_INPUT::location, memcpy, BASH_INPUT::name, NULL, savestring(), INPUT_STREAM::string, BASH_INPUT::type, type, and BASH_INPUT::ungetter.
Referenced by pop_stream(), with_input_from_stream(), and with_input_from_string().
initialize_bash_input()
void initialize_bash_input ()
Definition at line 3728 of file y.tab.c.
 {
   bash_input.type = st_none;
   FREE (bash_input.name);
   bash_input.name = (char *)NULL;
   bash_input.location.file = (FILE *)NULL;
   bash_input.location.string = (char *)NULL;
   bash_input.getter = (sh_cget_func_t *)NULL;
   bash_input.ungetter = (sh_cunget_func_t *)NULL;
 }
References bash_input, INPUT_STREAM::file, FREE, BASH_INPUT::getter, BASH_INPUT::location, BASH_INPUT::name, NULL, st_none, INPUT_STREAM::string, BASH_INPUT::type, and BASH_INPUT::ungetter.
Referenced by shell_initialize().
malloc()
void* malloc (YYSIZE_T)
PARAMS() [1/7]
static char* mk_alexpansion PARAMS ((char *)) static
PARAMS() [2/7]
static void push_string PARAMS ((char *, int, alias_t *)) static
PARAMS() [3/7]
int yyerror PARAMS ((const char *))
PARAMS() [4/7]
static int yy_ungetc PARAMS ((int)) static
PARAMS() [5/7]
static char* parse_matched_pair PARAMS ((int, int, int, int *, int)) static
PARAMS() [6/7]
static void push_heredoc PARAMS ((REDIRECT *)) static
PARAMS() [7/7]
int cleanup_dead_jobs PARAMS ((void))
parse_compound_assignment()
static char* parse_compound_assignment (int * retlenp) static
Definition at line 8776 of file y.tab.c.
 {
   WORD_LIST *wl, *rl;
   int tok, orig_line_number, assignok;
   sh_parser_state_t ps;
   char *ret;
   orig_line_number = line_number;
   save_parser_state (&ps);
   /* WORD to avoid parsing reserved words as themselves and just parse them as
      WORDs. Plus it means we won't be in a command position and so alias
      expansion won't happen. */
   last_read_token = WORD;
   token = (char *)NULL;
   token_buffer_size = 0;
   wl = (WORD_LIST *)NULL;   /* ( */
   assignok = parser_state&PST_ASSIGNOK;     /* XXX */
   /* State flags we don't want to persist into compound assignments. */
   parser_state &= ~(PST_NOEXPAND|PST_CONDCMD|PST_CONDEXPR|PST_REGEXP|PST_EXTPAT);
   /* State flags we want to set for this run through the tokenizer. */
   parser_state |= PST_COMPASSIGN;
   esacs_needed_count = expecting_in_token = 0;
   while ((tok = read_token (READ)) != ')')
     {
       if (tok == '\n')          /* Allow newlines in compound assignments */
     {
       if (SHOULD_PROMPT ())
         prompt_again (0);
       continue;
     }
       if (tok != WORD && tok != ASSIGNMENT_WORD)
     {
       current_token = tok;  /* for error reporting */
       if (tok == yacc_EOF)  /* ( */
         parser_error (orig_line_number, _("unexpected EOF while looking for matching `)'"));
       else
         yyerror(NULL);  /* does the right thing */
       if (wl)
         dispose_words (wl);
       wl = &parse_string_error;
       break;
     }
       wl = make_word_list (yylval.word, wl);
     }
   restore_parser_state (&ps);
   if (wl == &parse_string_error)
     {
       set_exit_status (EXECUTION_FAILURE);
       last_read_token = '\n';   /* XXX */
       if (interactive_shell == 0 && posixly_correct)
     jump_to_top_level (FORCE_EOF);
       else
     jump_to_top_level (DISCARD);
     }
   if (wl)
     {
       rl = REVERSE_LIST (wl, WORD_LIST *);
       ret = string_list (rl);
       dispose_words (rl);
     }
   else
     ret = (char *)NULL;
   if (retlenp)
     *retlenp = (ret && *ret) ? strlen (ret) : 0;
   if (assignok)
     parser_state |= PST_ASSIGNOK;
   return ret;
 }
References _, ASSIGNMENT_WORD, current_token, DISCARD, dispose_words(), esacs_needed_count, EXECUTION_FAILURE, expecting_in_token, FORCE_EOF, interactive_shell, jump_to_top_level(), last_read_token, line_number, make_word_list(), NULL, parse_string_error, parser_error(), parser_state, posixly_correct, prompt_again(), PST_ASSIGNOK, PST_COMPASSIGN, PST_CONDCMD, PST_CONDEXPR, PST_EXTPAT, PST_NOEXPAND, PST_REGEXP, READ, read_token(), restore_parser_state(), REVERSE_LIST, save_parser_state(), set_exit_status(), SHOULD_PROMPT, string_list(), strlen(), token_buffer_size, WORD, YYSTYPE::word, yacc_EOF, yyerror(), and yylval.
Referenced by read_token_word().
parse_comsub()
static char* parse_comsub (int qc, int open, int close, int * lenp, int flags) static
Definition at line 6377 of file y.tab.c.
 {
   int peekc, r;
   int start_lineno, local_extglob, was_extpat;
   char *ret, *tcmd;
   int retlen;
   sh_parser_state_t ps;
   STRING_SAVER *saved_strings;
   COMMAND *saved_global, *parsed_command;
   /* Posix interp 217 says arithmetic expressions have precedence, so
      assume $(( introduces arithmetic expansion and parse accordingly. */
   if (open == '(')      /*)*/
     {
       peekc = shell_getc (1);
       shell_ungetc (peekc);
       if (peekc == '(')     /*)*/
     return (parse_matched_pair (qc, open, close, lenp, P_ARITH));
     }
 /*itrace("parse_comsub: qc = `%c' open = %c close = %c", qc, open, close);*/
   /*debug_parser(1);*/
   start_lineno = line_number;
   save_parser_state (&ps);
   was_extpat = (parser_state & PST_EXTPAT);
   /* State flags we don't want to persist into command substitutions. */
   parser_state &= ~(PST_REGEXP|PST_EXTPAT|PST_CONDCMD|PST_CONDEXPR|PST_COMPASSIGN);
   /* Could do PST_CASESTMT too, but that also affects history. Setting
      expecting_in_token below should take care of the parsing requirements.
      Unsetting PST_REDIRLIST isn't strictly necessary because of how we set
      token_to_read below, but we do it anyway. */
   parser_state &= ~(PST_CASEPAT|PST_ALEXPNEXT|PST_SUBSHELL|PST_REDIRLIST);
   /* State flags we want to set for this run through the parser. */
   parser_state |= PST_CMDSUBST|PST_EOFTOKEN|PST_NOEXPAND;
   /* leave pushed_string_list alone, since we might need to consume characters
      from it to satisfy this command substitution (in some perverse case). */
   shell_eof_token = close;
   saved_global = global_command;        /* might not be necessary */
   global_command = (COMMAND *)NULL;
   /* These are reset by reset_parser() */
   need_here_doc = 0;
   esacs_needed_count = expecting_in_token = 0;
   /* We want to expand aliases on this pass if we're in posix mode, since the
      standard says you have to take aliases into account when looking for the
      terminating right paren. Otherwise, we defer until execution time for
      backwards compatibility. */
   if (expand_aliases)
     expand_aliases = posixly_correct != 0;
 #if defined (EXTENDED_GLOB)
   /* If (parser_state & PST_EXTPAT), we're parsing an extended pattern for a
      conditional command and have already set extended_glob appropriately. */
   if (shell_compatibility_level <= 51 && was_extpat == 0)
     {
       local_extglob = extended_glob;
       extended_glob = 1;
     }
 #endif
   current_token = '\n';             /* XXX */
   token_to_read = DOLPAREN;         /* let's trick the parser */
   r = yyparse ();
   if (need_here_doc > 0)
     {
       internal_warning ("command substitution: %d unterminated here-document%s", need_here_doc, (need_here_doc == 1) ? "" : "s");
       gather_here_documents (); /* XXX check compatibility level? */
     }
 #if defined (EXTENDED_GLOB)
   if (shell_compatibility_level <= 51 && was_extpat == 0)
     extended_glob = local_extglob;
 #endif
   parsed_command = global_command;
   if (EOF_Reached)
     {
       shell_eof_token = ps.eof_token;
       expand_aliases = ps.expand_aliases;
       /* yyparse() has already called yyerror() and reset_parser() */
       return (&matched_pair_error);
     }
   else if (r != 0)
     {
       /* parser_error (start_lineno, _("could not parse command substitution")); */
       /* Non-interactive shells exit on parse error in a command substitution. */
       if (last_command_exit_value == 0)
     last_command_exit_value = EXECUTION_FAILURE;
       set_exit_status (last_command_exit_value);
       if (interactive_shell == 0)
     jump_to_top_level (FORCE_EOF);  /* This is like reader_loop() */
       else
     {
       shell_eof_token = ps.eof_token;
       expand_aliases = ps.expand_aliases;
       jump_to_top_level (DISCARD);  /* XXX - return (&matched_pair_error)? */
     }
     }
   if (current_token != shell_eof_token)
     {
 INTERNAL_DEBUG(("current_token (%d) != shell_eof_token (%c)", current_token, shell_eof_token));
       token_to_read = current_token;
       /* If we get here we can check eof_encountered and if it's 1 but the
      previous EOF_Reached test didn't succeed, we can assume that the shell
      is interactive and ignoreeof is set. We might want to restore the
      parser state in this case. */
       shell_eof_token = ps.eof_token;
       expand_aliases = ps.expand_aliases;
       return (&matched_pair_error);
     }
   /* We don't want to restore the old pushed string list, since we might have
      used it to consume additional input from an alias while parsing this
      command substitution. */
   saved_strings = pushed_string_list;
   restore_parser_state (&ps);
   pushed_string_list = saved_strings;
   tcmd = print_comsub (parsed_command);     /* returns static memory */
   retlen = strlen (tcmd);
   if (tcmd[0] == '(')           /* ) need a space to prevent arithmetic expansion */
     retlen++;
   ret = xmalloc (retlen + 2);
   if (tcmd[0] == '(')           /* ) */
     {
       ret[0] = ' ';
       strcpy (ret + 1, tcmd);
     }
   else
     strcpy (ret, tcmd);
   ret[retlen++] = ')';
   ret[retlen] = '\0';
   dispose_command (parsed_command);
   global_command = saved_global;
   if (lenp)
     *lenp = retlen;
 /*itrace("parse_comsub:%d: returning `%s'", line_number, ret);*/
   return ret;
 }
References close(), current_token, DISCARD, dispose_command(), DOLPAREN, EOF_Reached, _sh_parser_state_t::eof_token, esacs_needed_count, EXECUTION_FAILURE, _sh_parser_state_t::expand_aliases, expand_aliases, expecting_in_token, extended_glob, FORCE_EOF, gather_here_documents(), global_command, interactive_shell, INTERNAL_DEBUG, internal_warning(), jump_to_top_level(), last_command_exit_value, line_number, matched_pair_error, need_here_doc, NULL, open(), P_ARITH, parse_matched_pair(), parser_state, posixly_correct, print_comsub(), PST_ALEXPNEXT, PST_CASEPAT, PST_CMDSUBST, PST_COMPASSIGN, PST_CONDCMD, PST_CONDEXPR, PST_EOFTOKEN, PST_EXTPAT, PST_NOEXPAND, PST_REDIRLIST, PST_REGEXP, PST_SUBSHELL, pushed_string_list, restore_parser_state(), retlen, save_parser_state(), set_exit_status(), shell_compatibility_level, shell_eof_token, shell_getc(), shell_ungetc(), strcpy, strlen(), token_to_read, xmalloc, and yyparse().
Referenced by parse_matched_pair(), and read_token_word().
parse_matched_pair()
static char* parse_matched_pair (int qc, int open, int close, int * lenp, int flags) static
Definition at line 5970 of file y.tab.c.
 {
   int count, ch, prevch, tflags;
   int nestlen, ttranslen, start_lineno;
   char *ret, *nestret, *ttrans;
   int retind, retsize, rflags;
   int dolbrace_state;
   dolbrace_state = (flags & P_DOLBRACE) ? DOLBRACE_PARAM : 0;
 /*itrace("parse_matched_pair[%d]: open = %c close = %c flags = %d", line_number, open, close, flags);*/
   count = 1;
   tflags = 0;
   if ((flags & P_COMMAND) && qc != '`' && qc != '\'' && qc != '"' && (flags & P_DQUOTE) == 0)
     tflags |= LEX_CKCOMMENT;
   /* RFLAGS is the set of flags we want to pass to recursive calls. */
   rflags = (qc == '"') ? P_DQUOTE : (flags & P_DQUOTE);
   ret = (char *)xmalloc (retsize = 64);
   retind = 0;
   start_lineno = line_number;
   ch = EOF;     /* just in case */
   while (count)
     {
       prevch = ch;
       ch = shell_getc (qc != '\'' && (tflags & (LEX_PASSNEXT)) == 0);
       if (ch == EOF)
     {
       free (ret);
       parser_error (start_lineno, _("unexpected EOF while looking for matching `%c'"), close);
       EOF_Reached = 1;  /* XXX */
       return (&matched_pair_error);
     }
       /* Possible reprompting. */
       if MBTEST(ch == '\n' && SHOULD_PROMPT ())
     prompt_again (0);
       /* Don't bother counting parens or doing anything else if in a comment
      or part of a case statement */
       if (tflags & LEX_INCOMMENT)
     {
       /* Add this character. */
       RESIZE_MALLOCED_BUFFER (ret, retind, 1, retsize, 64);
       ret[retind++] = ch;
       if MBTEST(ch == '\n')
         tflags &= ~LEX_INCOMMENT;
       continue;
     }
       /* Not exactly right yet, should handle shell metacharacters, too.  If
      any changes are made to this test, make analogous changes to subst.c:
      extract_delimited_string(). */
       else if MBTEST((tflags & LEX_CKCOMMENT) && (tflags & LEX_INCOMMENT) == 0 && ch == '#' && (retind == 0 || ret[retind-1] == '\n' || shellblank (ret[retind - 1])))
     tflags |= LEX_INCOMMENT;
       if (tflags & LEX_PASSNEXT)        /* last char was backslash */
     {
       tflags &= ~LEX_PASSNEXT;
       /* XXX - PST_NOEXPAND? */
       if MBTEST(qc != '\'' && ch == '\n')   /* double-quoted <newline> disappears. */
         {
           if (retind > 0)
         retind--;   /* swallow previously-added backslash */
           continue;
         }
       RESIZE_MALLOCED_BUFFER (ret, retind, 2, retsize, 64);
       if MBTEST(ch == CTLESC)
         ret[retind++] = CTLESC;
       ret[retind++] = ch;
       continue;
     }
       /* If we're reparsing the input (e.g., from parse_string_to_word_list),
      we've already prepended CTLESC to single-quoted results of $'...'.
      We may want to do this for other CTLESC-quoted characters in
      reparse, too. */
       else if MBTEST((parser_state & PST_REPARSE) && open == '\'' && (ch == CTLESC || ch == CTLNUL))
     {
       RESIZE_MALLOCED_BUFFER (ret, retind, 1, retsize, 64);
       ret[retind++] = ch;
       continue;
     }
       else if MBTEST(ch == CTLESC || ch == CTLNUL)  /* special shell escapes */
     {
       RESIZE_MALLOCED_BUFFER (ret, retind, 2, retsize, 64);
       ret[retind++] = CTLESC;
       ret[retind++] = ch;
       continue;
     }
       else if MBTEST(ch == close)       /* ending delimiter */
     count--;
       /* handle nested ${...} specially. */
       else if MBTEST(open != close && (tflags & LEX_WASDOL) && open == '{' && ch == open) /* } */
     count++;
       else if MBTEST(((flags & P_FIRSTCLOSE) == 0) && ch == open)   /* nested begin */
     count++;
       /* Add this character. */
       RESIZE_MALLOCED_BUFFER (ret, retind, 1, retsize, 64);
       ret[retind++] = ch;
       /* If we just read the ending character, don't bother continuing. */
       if (count == 0)
     break;
       if (open == '\'')         /* '' inside grouping construct */
     {
       if MBTEST((flags & P_ALLOWESC) && ch == '\\')
         tflags |= LEX_PASSNEXT;
       continue;
     }
       if MBTEST(ch == '\\')         /* backslashes */
     tflags |= LEX_PASSNEXT;
       /* Based on which dolstate is currently in (param, op, or word),
      decide what the op is.  We're really only concerned if it's % or
      #, so we can turn on a flag that says whether or not we should
      treat single quotes as special when inside a double-quoted
      ${...}. This logic must agree with subst.c:extract_dollar_brace_string
      since they share the same defines. */
       /* FLAG POSIX INTERP 221 */
       if (flags & P_DOLBRACE)
         {
           /* ${param%[%]word} */
       if MBTEST(dolbrace_state == DOLBRACE_PARAM && ch == '%' && retind > 1)
         dolbrace_state = DOLBRACE_QUOTE;
           /* ${param#[#]word} */
       else if MBTEST(dolbrace_state == DOLBRACE_PARAM && ch == '#' && retind > 1)
         dolbrace_state = DOLBRACE_QUOTE;
           /* ${param/[/]pat/rep} */
       else if MBTEST(dolbrace_state == DOLBRACE_PARAM && ch == '/' && retind > 1)
         dolbrace_state = DOLBRACE_QUOTE2;   /* XXX */
           /* ${param^[^]pat} */
       else if MBTEST(dolbrace_state == DOLBRACE_PARAM && ch == '^' && retind > 1)
         dolbrace_state = DOLBRACE_QUOTE;
           /* ${param,[,]pat} */
       else if MBTEST(dolbrace_state == DOLBRACE_PARAM && ch == ',' && retind > 1)
         dolbrace_state = DOLBRACE_QUOTE;
       else if MBTEST(dolbrace_state == DOLBRACE_PARAM && strchr ("#%^,~:-=?+/", ch) != 0)
         dolbrace_state = DOLBRACE_OP;
       else if MBTEST(dolbrace_state == DOLBRACE_OP && strchr ("#%^,~:-=?+/", ch) == 0)
         dolbrace_state = DOLBRACE_WORD;
         }
       /* The big hammer.  Single quotes aren't special in double quotes.  The
          problem is that Posix used to say the single quotes are semi-special:
          within a double-quoted ${...} construct "an even number of
          unescaped double-quotes or single-quotes, if any, shall occur." */
       /* This was changed in Austin Group Interp 221 */
       if MBTEST(posixly_correct && shell_compatibility_level > 41 && dolbrace_state != DOLBRACE_QUOTE && dolbrace_state != DOLBRACE_QUOTE2 && (flags & P_DQUOTE) && (flags & P_DOLBRACE) && ch == '\'')
     continue;
       /* Could also check open == '`' if we want to parse grouping constructs
      inside old-style command substitution. */
       if (open != close)        /* a grouping construct */
     {
       if MBTEST(shellquote (ch))
         {
           /* '', ``, or "" inside $(...) or other grouping construct. */
           push_delimiter (dstack, ch);
           if MBTEST((tflags & LEX_WASDOL) && ch == '\'')    /* $'...' inside group */
         nestret = parse_matched_pair (ch, ch, ch, &nestlen, P_ALLOWESC|rflags);
           else
         nestret = parse_matched_pair (ch, ch, ch, &nestlen, rflags);
           pop_delimiter (dstack);
           CHECK_NESTRET_ERROR ();
           if MBTEST((tflags & LEX_WASDOL) && ch == '\'' && (extended_quote || (rflags & P_DQUOTE) == 0 || dolbrace_state == DOLBRACE_QUOTE || dolbrace_state == DOLBRACE_QUOTE2))
         {
           /* Translate $'...' here. */
           /* PST_NOEXPAND */
           ttrans = ansiexpand (nestret, 0, nestlen - 1, &ttranslen);
           free (nestret);
           /* If we're parsing a double-quoted brace expansion and we are
              not in a place where single quotes are treated specially,
              make sure we single-quote the results of the ansi
              expansion because quote removal should remove them later */
           /* FLAG POSIX INTERP 221 */
           if ((shell_compatibility_level > 42) && (rflags & P_DQUOTE) && (dolbrace_state == DOLBRACE_QUOTE2 || dolbrace_state == DOLBRACE_QUOTE) && (flags & P_DOLBRACE))
             {
               nestret = sh_single_quote (ttrans);
               free (ttrans);
               nestlen = strlen (nestret);
             }
 #if 0 /* TAG:bash-5.3 */
           /* This single-quotes PARAM in ${PARAM OP WORD} when PARAM
              contains a $'...' even when extended_quote is set. */
           else if ((rflags & P_DQUOTE) && (dolbrace_state == DOLBRACE_PARAM) && (flags & P_DOLBRACE))
             {
               nestret = sh_single_quote (ttrans);
               free (ttrans);
               nestlen = strlen (nestret);
             }
 #endif
           else if ((rflags & P_DQUOTE) == 0)
             {
               nestret = sh_single_quote (ttrans);
               free (ttrans);
               nestlen = strlen (nestret);
             }
           else
             {
               /* Should we quote CTLESC here? */
               nestret = ttrans;
               nestlen = ttranslen;
             }
           retind -= 2;      /* back up before the $' */
         }
 #if defined (TRANSLATABLE_STRINGS)
           else if MBTEST((tflags & LEX_WASDOL) && ch == '"' && (extended_quote || (rflags & P_DQUOTE) == 0))
         {
           /* Locale expand $"..." here. */
           /* PST_NOEXPAND */
           ttrans = locale_expand (nestret, 0, nestlen - 1, start_lineno, &ttranslen);
           free (nestret);
           /* If we're supposed to single-quote translated strings,
              check whether the translated result is different from
              the original and single-quote the string if it is. */
           if (singlequote_translations &&
                 ((nestlen - 1) != ttranslen || STREQN (nestret, ttrans, ttranslen) == 0))
             {
               if ((rflags & P_DQUOTE) == 0)
             nestret = sh_single_quote (ttrans);
               else if ((rflags & P_DQUOTE) && (dolbrace_state == DOLBRACE_QUOTE2) && (flags & P_DOLBRACE))
             nestret = sh_single_quote (ttrans);
               else
             /* single quotes aren't special, use backslash instead */
             nestret = sh_backslash_quote_for_double_quotes (ttrans, 0);
             }
           else
             nestret = sh_mkdoublequoted (ttrans, ttranslen, 0);
           free (ttrans);
           nestlen = strlen (nestret);
           retind -= 2;      /* back up before the $" */
         }
 #endif /* TRANSLATABLE_STRINGS */
           APPEND_NESTRET ();
           FREE (nestret);
         }
       else if ((flags & (P_ARRAYSUB|P_DOLBRACE)) && (tflags & LEX_WASDOL) && (ch == '(' || ch == '{' || ch == '[')) /* ) } ] */
         goto parse_dollar_word;
       else if ((flags & P_ARITH) && (tflags & LEX_WASDOL) && ch == '(') /*)*/
         /* $() inside $(( ))/$[ ] */
         goto parse_dollar_word;
 #if defined (PROCESS_SUBSTITUTION)
       /* XXX - technically this should only be recognized at the start of
          a word */
       else if ((flags & (P_ARRAYSUB|P_DOLBRACE)) && (tflags & LEX_GTLT) && (ch == '(')) /* ) */
         goto parse_dollar_word;
 #endif
     }
       /* Parse an old-style command substitution within double quotes as a
      single word. */
       /* XXX - sh and ksh93 don't do this - XXX */
       else if MBTEST(open == '"' && ch == '`')
     {
       nestret = parse_matched_pair (0, '`', '`', &nestlen, rflags);
       CHECK_NESTRET_ERROR ();
       APPEND_NESTRET ();
       FREE (nestret);
     }
       else if MBTEST(open != '`' && (tflags & LEX_WASDOL) && (ch == '(' || ch == '{' || ch == '[')) /* ) } ] */
     /* check for $(), $[], or ${} inside quoted string. */
     {
 parse_dollar_word:
       if (open == ch)   /* undo previous increment */
         count--;
       if (ch == '(')        /* ) */
         nestret = parse_comsub (0, '(', ')', &nestlen, (rflags|P_COMMAND) & ~P_DQUOTE);
       else if (ch == '{')       /* } */
         nestret = parse_matched_pair (0, '{', '}', &nestlen, P_FIRSTCLOSE|P_DOLBRACE|rflags);
       else if (ch == '[')       /* ] */
         nestret = parse_matched_pair (0, '[', ']', &nestlen, rflags|P_ARITH);
       CHECK_NESTRET_ERROR ();
       APPEND_NESTRET ();
       FREE (nestret);
     }
 #if defined (PROCESS_SUBSTITUTION)
       if MBTEST((ch == '<' || ch == '>') && (tflags & LEX_GTLT) == 0)
     tflags |= LEX_GTLT;
       else
     tflags &= ~LEX_GTLT;
 #endif
       if MBTEST(ch == '$' && (tflags & LEX_WASDOL) == 0)
     tflags |= LEX_WASDOL;
       else
     tflags &= ~LEX_WASDOL;
     }
   ret[retind] = '\0';
   if (lenp)
     *lenp = retind;
 /*itrace("parse_matched_pair[%d]: returning %s", line_number, ret);*/
   return ret;
 }
References _, ansiexpand(), APPEND_NESTRET, CHECK_NESTRET_ERROR, close(), count, CTLESC, CTLNUL, DOLBRACE_OP, DOLBRACE_PARAM, DOLBRACE_QUOTE, DOLBRACE_QUOTE2, DOLBRACE_WORD, EOF, EOF_Reached, extended_quote, flags, FREE, free(), LEX_CKCOMMENT, LEX_GTLT, LEX_INCOMMENT, LEX_PASSNEXT, LEX_WASDOL, line_number, matched_pair_error, MBTEST, open(), P_ALLOWESC, P_ARITH, P_ARRAYSUB, P_COMMAND, P_DOLBRACE, P_DQUOTE, P_FIRSTCLOSE, parse_comsub(), parser_error(), parser_state, pop_delimiter, posixly_correct, prompt_again(), PST_REPARSE, push_delimiter, RESIZE_MALLOCED_BUFFER, sh_mkdoublequoted(), sh_single_quote(), shell_compatibility_level, shell_getc(), shellblank, shellquote, SHOULD_PROMPT, singlequote_translations, strchr(), STREQN, strlen(), and xmalloc.
Referenced by parse_comsub(), and read_token_word().
parse_string_to_command()
COMMAND* parse_string_to_command (char * string, int flags)
Definition at line 6679 of file y.tab.c.
 {
   sh_parser_state_t ps;
   sh_input_line_state_t ls;
   int nc, sflags;
   size_t slen;
   char *ret, *ep;
   COMMAND *cmd;
   if (*string == 0)
     return (COMMAND *)NULL;
   ep = string;
   slen = STRLEN (string);
 /*itrace("parse_string_to_command: size = %d shell_input_line = `%s' string=`%s'", shell_input_line_size, shell_input_line, string);*/
   sflags = SEVAL_NONINT|SEVAL_NOHIST|SEVAL_NOFREE;
   if (flags & SX_NOLONGJMP)
     sflags |= SEVAL_NOLONGJMP;
   save_parser_state (&ps);
   save_input_line_state (&ls);
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   pushed_string_list = (STRING_SAVER *)NULL;
 #endif
   if (flags & SX_COMPLETE)
     parser_state |= PST_NOERROR;
   parser_state |= PST_STRING;
   expand_aliases = 0;
   cmd = 0;
   nc = parse_string (string, "command substitution", sflags, &cmd, &ep);
   reset_parser ();
   /* reset_parser() clears shell_input_line and associated variables, including
      parser_state, so we want to reset things, then restore what we need. */
   restore_input_line_state (&ls);
   restore_parser_state (&ps);
   /* If parse_string returns < 0, we need to jump to top level with the
      negative of the return value. We abandon the rest of this input line
      first */
   if (nc < 0)
     {
       clear_shell_input_line ();    /* XXX */
       if ((flags & SX_NOLONGJMP) == 0)
         jump_to_top_level (-nc);    /* XXX */
     }
   /* Need to check how many characters parse_string() consumed, make sure it's
      the entire string. */
   if (nc < slen)
     {
       dispose_command (cmd);
       return (COMMAND *)NULL;
     }
   return cmd;
 }
References clear_shell_input_line(), cmd, dispose_command(), expand_aliases, flags, jump_to_top_level(), NULL, parse_string(), parser_state, PST_NOERROR, PST_STRING, pushed_string_list, reset_parser(), restore_input_line_state(), restore_parser_state(), save_input_line_state(), save_parser_state(), SEVAL_NOFREE, SEVAL_NOHIST, SEVAL_NOLONGJMP, SEVAL_NONINT, string, STRLEN, SX_COMPLETE, and SX_NOLONGJMP.
Referenced by command_substitute().
parse_string_to_word_list()
WORD_LIST* parse_string_to_word_list (char * s, int flags, const char * whom)
Definition at line 8690 of file y.tab.c.
 {
   WORD_LIST *wl;
   int tok, orig_current_token, orig_line_number;
   int orig_parser_state;
   sh_parser_state_t ps;
   int ea;
   orig_line_number = line_number;
   save_parser_state (&ps);
 #if defined (HISTORY)
   bash_history_disable ();
 #endif
   push_stream (1);
   if (ea = expanding_alias ())
     parser_save_alias ();
   /* WORD to avoid parsing reserved words as themselves and just parse them as
      WORDs. */
   last_read_token = WORD;
   current_command_line_count = 0;
   echo_input_at_read = expand_aliases = 0;
   with_input_from_string (s, whom);
   wl = (WORD_LIST *)NULL;
   if (flags & 1)
     {
       orig_parser_state = parser_state;     /* XXX - not needed? */
       /* State flags we don't want to persist into compound assignments. */
       parser_state &= ~PST_NOEXPAND;    /* parse_comsub sentinel */
       /* State flags we want to set for this run through the tokenizer. */
       parser_state |= PST_COMPASSIGN|PST_REPARSE|PST_STRING;
     }
   while ((tok = read_token (READ)) != yacc_EOF)
     {
       if (tok == '\n' && *bash_input.location.string == '\0')
     break;
       if (tok == '\n')      /* Allow newlines in compound assignments */
     continue;
       if (tok != WORD && tok != ASSIGNMENT_WORD)
     {
       line_number = orig_line_number + line_number - 1;
       orig_current_token = current_token;
       current_token = tok;
       yyerror (NULL);   /* does the right thing */
       current_token = orig_current_token;
       if (wl)
         dispose_words (wl);
       wl = &parse_string_error;
       break;
     }
       wl = make_word_list (yylval.word, wl);
     }
   last_read_token = '\n';
   pop_stream ();
   if (ea)
     parser_restore_alias ();
   restore_parser_state (&ps);
   if (flags & 1)
     parser_state = orig_parser_state;   /* XXX - not needed? */
   if (wl == &parse_string_error)
     {
       set_exit_status (EXECUTION_FAILURE);
       if (interactive_shell == 0 && posixly_correct)
     jump_to_top_level (FORCE_EOF);
       else
     jump_to_top_level (DISCARD);
     }
   return (REVERSE_LIST (wl, WORD_LIST *));
 }
References ASSIGNMENT_WORD, bash_input, current_command_line_count, current_token, DISCARD, dispose_words(), echo_input_at_read, EXECUTION_FAILURE, expand_aliases, expanding_alias, flags, FORCE_EOF, interactive_shell, jump_to_top_level(), last_read_token, line_number, BASH_INPUT::location, make_word_list(), NULL, parse_string_error, parser_restore_alias(), parser_save_alias(), parser_state, pop_stream(), posixly_correct, PST_COMPASSIGN, PST_NOEXPAND, PST_REPARSE, PST_STRING, push_stream(), READ, read_token(), restore_parser_state(), REVERSE_LIST, s, save_parser_state(), set_exit_status(), INPUT_STREAM::string, with_input_from_string(), WORD, YYSTYPE::word, yacc_EOF, yyerror(), and yylval.
parser_expanding_alias()
int parser_expanding_alias ()
Definition at line 4320 of file y.tab.c.
 {
   return (expanding_alias ());
 }
References expanding_alias.
Referenced by can_optimize_connection(), optimize_subshell_command(), parse_and_execute(), parse_command(), parse_prologue(), parse_string(), and should_suppress_fork().
parser_in_command_position()
int parser_in_command_position ()
Definition at line 7726 of file y.tab.c.
 {
   return (command_token_position (last_read_token));
 }
References command_token_position, and last_read_token.
parser_remaining_input()
char* parser_remaining_input ()
Definition at line 5095 of file y.tab.c.
 {
   if (shell_input_line == 0)
     return 0;
   if ((int)shell_input_line_index < 0 || shell_input_line_index >= shell_input_line_len)
     return "";  /* XXX */
   return (shell_input_line + shell_input_line_index);
 }
References shell_input_line, shell_input_line_index, and shell_input_line_len.
Referenced by parse_and_execute().
parser_restore_alias()
void parser_restore_alias ()
Definition at line 4337 of file y.tab.c.
 {
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   if (pushed_string_list)
     pop_string ();
 #else
   ;
 #endif
 }
References pop_string(), and pushed_string_list.
Referenced by parse_prologue(), and parse_string_to_word_list().
parser_save_alias()
void parser_save_alias ()
Definition at line 4326 of file y.tab.c.
 {
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   push_string ((char *)NULL, 0, (alias_t *)NULL);
   pushed_string_list->flags = PSH_SOURCE;   /* XXX - for now */
 #else
   ;
 #endif
 }
References string_saver::flags, NULL, PSH_SOURCE, push_string(), and pushed_string_list.
Referenced by parse_and_execute(), parse_string(), and parse_string_to_word_list().
pop_stream()
void pop_stream ()
Definition at line 4083 of file y.tab.c.
 {
   if (!stream_list)
     EOF_Reached = 1;
   else
     {
       STREAM_SAVER *saver = stream_list;
       EOF_Reached = 0;
       stream_list = stream_list->next;
       init_yy_io (saver->bash_input.getter,
           saver->bash_input.ungetter,
           saver->bash_input.type,
           saver->bash_input.name,
           saver->bash_input.location);
 #if defined (BUFFERED_INPUT)
       /* If we have a buffered stream, restore buffers[fd]. */
       /* If the input file descriptor was changed while this was on the
      save stack, update the buffered fd to the new file descriptor and
      re-establish the buffer <-> bash_input fd correspondence. */
       if (bash_input.type == st_bstream && bash_input.location.buffered_fd >= 0)
     {
       if (bash_input_fd_changed)
         {
           bash_input_fd_changed = 0;
           if (default_buffered_input >= 0)
         {
           bash_input.location.buffered_fd = default_buffered_input;
           saver->bstream->b_fd = default_buffered_input;
           SET_CLOSE_ON_EXEC (default_buffered_input);
         }
         }
       /* XXX could free buffered stream returned as result here. */
       set_buffered_stream (bash_input.location.buffered_fd, saver->bstream);
     }
 #endif /* BUFFERED_INPUT */
       line_number = saver->line;
       FREE (saver->bash_input.name);
       free (saver);
     }
 }
References bash_input, stream_saver::bash_input, EOF_Reached, FREE, free(), BASH_INPUT::getter, init_yy_io(), stream_saver::line, line_number, BASH_INPUT::location, BASH_INPUT::name, stream_saver::next, SET_CLOSE_ON_EXEC, st_bstream, stream_list, BASH_INPUT::type, and BASH_INPUT::ungetter.
Referenced by parse_prologue(), and parse_string_to_word_list().
pop_string()
static void pop_string () static
Definition at line 4261 of file y.tab.c.
 {
   STRING_SAVER *t;
   FREE (shell_input_line);
   shell_input_line = pushed_string_list->saved_line;
   shell_input_line_index = pushed_string_list->saved_line_index;
   shell_input_line_size = pushed_string_list->saved_line_size;
   shell_input_line_len = pushed_string_list->saved_line_len;
   shell_input_line_terminator = pushed_string_list->saved_line_terminator;
 #if defined (ALIAS)
   if (pushed_string_list->expand_alias)
     parser_state |= PST_ALEXPNEXT;
   else
     parser_state &= ~PST_ALEXPNEXT;
 #endif
   t = pushed_string_list;
   pushed_string_list = pushed_string_list->next;
 #if defined (ALIAS)
   if (t->expander)
     t->expander->flags &= ~AL_BEINGEXPANDED;
 #endif
   free ((char *)t);
   set_line_mbstate ();
 }
References AL_BEINGEXPANDED, string_saver::expand_alias, FREE, free(), string_saver::next, parser_state, PST_ALEXPNEXT, pushed_string_list, string_saver::saved_line, string_saver::saved_line_index, string_saver::saved_line_len, string_saver::saved_line_size, string_saver::saved_line_terminator, set_line_mbstate, shell_input_line, shell_input_line_index, shell_input_line_len, shell_input_line_size, shell_input_line_terminator, and t.
Referenced by parser_restore_alias(), and shell_getc().
print_offending_line()
static void print_offending_line () static
Definition at line 8507 of file y.tab.c.
 {
   char *msg;
   int token_end;
   msg = savestring (shell_input_line);
   token_end = strlen (msg);
   while (token_end && msg[token_end - 1] == '\n')
     msg[--token_end] = '\0';
   parser_error (line_number, "`%s'", msg);
   free (msg);
 }
References free(), line_number, parser_error(), savestring(), shell_input_line, and strlen().
Referenced by report_syntax_error().
print_prompt()
static void print_prompt () static
Definition at line 7928 of file y.tab.c.
 {
   fprintf (stderr, "%s", current_decoded_prompt);
   fflush (stderr);
 }
References current_decoded_prompt, fflush(), fprintf(), and stderr.
Referenced by read_a_line(), and shell_getc().
prompt_again()
static void prompt_again (int force) static
Definition at line 7870 of file y.tab.c.
 {
   char *temp_prompt;
   if (interactive == 0 || expanding_alias ())   /* XXX */
     return;
   ps1_prompt = get_string_value ("PS1");
   ps2_prompt = get_string_value ("PS2");
   ps0_prompt = get_string_value ("PS0");
   if (!prompt_string_pointer)
     prompt_string_pointer = &ps1_prompt;
   temp_prompt = *prompt_string_pointer
             ? decode_prompt_string (*prompt_string_pointer)
             : (char *)NULL;
   if (temp_prompt == 0)
     {
       temp_prompt = (char *)xmalloc (1);
       temp_prompt[0] = '\0';
     }
   current_prompt_string = *prompt_string_pointer;
   prompt_string_pointer = &ps2_prompt;
 #if defined (READLINE)
   if (!no_line_editing)
     {
       FREE (current_readline_prompt);
       current_readline_prompt = temp_prompt;
     }
   else
 #endif  /* READLINE */
     {
       FREE (current_decoded_prompt);
       current_decoded_prompt = temp_prompt;
     }
 }
References current_decoded_prompt, current_prompt_string, decode_prompt_string(), expanding_alias, FREE, get_string_value(), interactive, no_line_editing, NULL, prompt_string_pointer, ps0_prompt, ps1_prompt, ps2_prompt, and xmalloc.
Referenced by handle_eof_input_unit(), parse_compound_assignment(), parse_matched_pair(), read_secondary_line(), read_token_word(), shell_getc(), and yylex().
push_heredoc()
static void push_heredoc (REDIRECT * r) static
Definition at line 5228 of file y.tab.c.
 {
   if (need_here_doc >= HEREDOC_MAX)
     {
       last_command_exit_value = EX_BADUSAGE;
       need_here_doc = 0;
       report_syntax_error (_("maximum here-document count exceeded"));
       reset_parser ();
       exit_shell (last_command_exit_value);
     }
   redir_stack[need_here_doc++] = r;
 }
References _, EX_BADUSAGE, exit_shell(), HEREDOC_MAX, last_command_exit_value, need_here_doc, redir_stack, report_syntax_error(), and reset_parser().
Referenced by yyparse().
push_stream()
void push_stream (int reset_lineno)
Definition at line 4058 of file y.tab.c.
 {
   STREAM_SAVER *saver = (STREAM_SAVER *)xmalloc (sizeof (STREAM_SAVER));
   xbcopy ((char *)&bash_input, (char *)&(saver->bash_input), sizeof (BASH_INPUT));
 #if defined (BUFFERED_INPUT)
   saver->bstream = (BUFFERED_STREAM *)NULL;
   /* If we have a buffered stream, clear out buffers[fd]. */
   if (bash_input.type == st_bstream && bash_input.location.buffered_fd >= 0)
     saver->bstream = set_buffered_stream (bash_input.location.buffered_fd,
                           (BUFFERED_STREAM *)NULL);
 #endif /* BUFFERED_INPUT */
   saver->line = line_number;
   bash_input.name = (char *)NULL;
   saver->next = stream_list;
   stream_list = saver;
   EOF_Reached = 0;
   if (reset_lineno)
     line_number = 0;
 }
References bash_input, stream_saver::bash_input, EOF_Reached, stream_saver::line, line_number, BASH_INPUT::location, BASH_INPUT::name, stream_saver::next, NULL, st_bstream, stream_list, BASH_INPUT::type, xbcopy(), and xmalloc.
Referenced by parse_and_execute(), parse_string(), and parse_string_to_word_list().
push_string()
static void push_string (char * s, int expand, alias_t * ap) static
Definition at line 4216 of file y.tab.c.
 {
   STRING_SAVER *temp = (STRING_SAVER *)xmalloc (sizeof (STRING_SAVER));
   temp->expand_alias = expand;
   temp->saved_line = shell_input_line;
   temp->saved_line_size = shell_input_line_size;
   temp->saved_line_len = shell_input_line_len;
   temp->saved_line_index = shell_input_line_index;
   temp->saved_line_terminator = shell_input_line_terminator;
   temp->flags = 0;
 #if defined (ALIAS)
   temp->expander = ap;
   if (ap)
     temp->flags = PSH_ALIAS;
 #endif
   temp->next = pushed_string_list;
   pushed_string_list = temp;
 #if defined (ALIAS)
   if (ap)
     ap->flags |= AL_BEINGEXPANDED;
 #endif
   shell_input_line = s;
   shell_input_line_size = shell_input_line_len = STRLEN (s);
   shell_input_line_index = 0;
   shell_input_line_terminator = '\0';
 #if 0
   parser_state &= ~PST_ALEXPNEXT;   /* XXX */
 #endif
   set_line_mbstate ();
 }
References AL_BEINGEXPANDED, ap, expand(), string_saver::expand_alias, string_saver::flags, string_saver::next, parser_state, PSH_ALIAS, PST_ALEXPNEXT, pushed_string_list, s, string_saver::saved_line, string_saver::saved_line_index, string_saver::saved_line_len, string_saver::saved_line_size, string_saver::saved_line_terminator, set_line_mbstate, shell_input_line, shell_input_line_index, shell_input_line_len, shell_input_line_size, shell_input_line_terminator, STRLEN, and xmalloc.
Referenced by parser_save_alias(), and shell_ungets().
push_token()
void push_token (int x)
Definition at line 5152 of file y.tab.c.
 {
   two_tokens_ago = token_before_that;
   token_before_that = last_read_token;
   last_read_token = current_token;
   current_token = x;
 }
References current_token, last_read_token, token_before_that, two_tokens_ago, and x.
Referenced by _evalfile().
read_a_line()
static char* read_a_line (int remove_quoted_newline) static
Definition at line 4376 of file y.tab.c.
 {
   static char *line_buffer = (char *)NULL;
   static int buffer_size = 0;
   int indx, c, peekc, pass_next;
 #if defined (READLINE)
   if (no_line_editing && SHOULD_PROMPT ())
 #else
   if (SHOULD_PROMPT ())
 #endif
     print_prompt ();
   pass_next = indx = 0;
   while (1)
     {
       /* Allow immediate exit if interrupted during input. */
       QUIT;
       c = yy_getc ();
       /* Ignore null bytes in input. */
       if (c == 0)
     continue;
       /* If there is no more input, then we return NULL. */
       if (c == EOF)
     {
       if (interactive && bash_input.type == st_stream)
         clearerr (stdin);
       if (indx == 0)
         return ((char *)NULL);
       c = '\n';
     }
       /* `+2' in case the final character in the buffer is a newline or we
      have to handle CTLESC or CTLNUL. */
       RESIZE_MALLOCED_BUFFER (line_buffer, indx, 2, buffer_size, 128);
       /* IF REMOVE_QUOTED_NEWLINES is non-zero, we are reading a
      here document with an unquoted delimiter.  In this case,
      the line will be expanded as if it were in double quotes.
      We allow a backslash to escape the next character, but we
      need to treat the backslash specially only if a backslash
      quoting a backslash-newline pair appears in the line. */
       if (pass_next)
     {
       line_buffer[indx++] = c;
       pass_next = 0;
     }
       else if (c == '\\' && remove_quoted_newline)
     {
       QUIT;
       peekc = yy_getc ();
       if (peekc == '\n')
         {
           line_number++;
           continue; /* Make the unquoted <newline> pair disappear. */
         }
       else
         {
           yy_ungetc (peekc);
           pass_next = 1;
           line_buffer[indx++] = c;      /* Preserve the backslash. */
         }
     }
       else
     {
       /* remove_quoted_newline is non-zero if the here-document delimiter
          is unquoted. In this case, we will be expanding the lines and
          need to make sure CTLESC and CTLNUL in the input are quoted. */
       if (remove_quoted_newline && (c == CTLESC || c == CTLNUL))
         line_buffer[indx++] = CTLESC;
       line_buffer[indx++] = c;
     }
       if (c == '\n')
     {
       line_buffer[indx] = '\0';
       return (line_buffer);
     }
     }
 }
References bash_input, c, clearerr(), CTLESC, CTLNUL, EOF, interactive, line_buffer, line_number, no_line_editing, NULL, print_prompt(), QUIT, RESIZE_MALLOCED_BUFFER, SHOULD_PROMPT, st_stream, stdin, BASH_INPUT::type, yy_getc(), and yy_ungetc().
Referenced by read_secondary_line().
read_secondary_line()
char* read_secondary_line (int remove_quoted_newline)
Definition at line 4467 of file y.tab.c.
 {
   char *ret;
   int n, c;
   prompt_string_pointer = &ps2_prompt;
   if (SHOULD_PROMPT ())
     prompt_again (0);
   ret = read_a_line (remove_quoted_newline);
 #if defined (HISTORY)
   if (ret && remember_on_history && (parser_state & PST_HEREDOC))
     {
       /* To make adding the here-document body right, we need to rely on
      history_delimiting_chars() returning \n for the first line of the
      here-document body and the null string for the second and subsequent
      lines, so we avoid double newlines.
      current_command_line_count == 2 for the first line of the body. */
       current_command_line_count++;
       maybe_add_history (ret);
     }
 #endif /* HISTORY */
   return ret;
 }
References c, current_command_line_count, n, parser_state, prompt_again(), prompt_string_pointer, ps2_prompt, PST_HEREDOC, read_a_line(), remember_on_history, and SHOULD_PROMPT.
Referenced by make_here_document().
read_token()
static int read_token (int command) static
Definition at line 5664 of file y.tab.c.
 {
   int character;        /* Current character. */
   int peek_char;        /* Temporary look-ahead character. */
   int result;           /* The thing to return. */
   if (command == RESET)
     {
       reset_parser ();
       return ('\n');
     }
   if (token_to_read)
     {
       result = token_to_read;
       if (token_to_read == WORD || token_to_read == ASSIGNMENT_WORD)
     {
       yylval.word = word_desc_to_read;
       word_desc_to_read = (WORD_DESC *)NULL;
     }
       token_to_read = 0;
       return (result);
     }
 #if defined (COND_COMMAND)
   if ((parser_state & (PST_CONDCMD|PST_CONDEXPR)) == PST_CONDCMD)
     {
       cond_lineno = line_number;
       parser_state |= PST_CONDEXPR;
       yylval.command = parse_cond_command ();
       if (cond_token != COND_END)
     {
       cond_error ();
       return (-1);
     }
       token_to_read = COND_END;
       parser_state &= ~(PST_CONDEXPR|PST_CONDCMD);
       return (COND_CMD);
     }
 #endif
 #if defined (ALIAS)
   /* This is a place to jump back to once we have successfully expanded a
      token with an alias and pushed the string with push_string () */
  re_read_token:
 #endif /* ALIAS */
   /* Read a single word from input.  Start by skipping blanks. */
   while ((character = shell_getc (1)) != EOF && shellblank (character))
     ;
   if (character == EOF)
     {
       EOF_Reached = 1;
       return (yacc_EOF);
     }
   /* If we hit the end of the string and we're not expanding an alias (e.g.,
      we are eval'ing a string that is an incomplete command), return EOF */
   if (character == '\0' && bash_input.type == st_string && expanding_alias() == 0)
     {
       INTERNAL_DEBUG (("shell_getc: bash_input.location.string = `%s'", bash_input.location.string));
       EOF_Reached = 1;
       return (yacc_EOF);
     }
   if MBTEST(character == '#' && (!interactive || interactive_comments))
     {
       /* A comment.  Discard until EOL or EOF, and then return a newline. */
       parser_state |= PST_COMMENT;
       discard_until ('\n');
       shell_getc (0);
       parser_state &= ~PST_COMMENT;
       character = '\n'; /* this will take the next if statement and return. */
     }
   if MBTEST(character == '\n')
     {
       /* If we're about to return an unquoted newline, we can go and collect
      the text of any pending here document. */
       if (need_here_doc)
     gather_here_documents ();
 #if defined (ALIAS)
       parser_state &= ~PST_ALEXPNEXT;
 #endif /* ALIAS */
       parser_state &= ~PST_ASSIGNOK;
       return (character);
     }
   if (parser_state & PST_REGEXP)
     goto tokword;
   /* Shell meta-characters. */
   if MBTEST(shellmeta (character))
     {
 #if defined (ALIAS)
       /* Turn off alias tokenization iff this character sequence would
      not leave us ready to read a command. */
       if (character == '<' || character == '>')
     parser_state &= ~PST_ALEXPNEXT;
 #endif /* ALIAS */
       parser_state &= ~PST_ASSIGNOK;
       /* If we are parsing a command substitution and we have read a character
      that marks the end of it, don't bother to skip over quoted newlines
      when we read the next token. We're just interested in a character
      that will turn this into a two-character token, so we let the higher
      layers deal with quoted newlines following the command substitution. */
       if ((parser_state & PST_CMDSUBST) && character == shell_eof_token)
     peek_char = shell_getc (0);
       else
     peek_char = shell_getc (1);
       if MBTEST(character == peek_char)
     {
       switch (character)
         {
         case '<':
           /* If '<' then we could be at "<<" or at "<<-".  We have to
          look ahead one more character. */
           peek_char = shell_getc (1);
           if MBTEST(peek_char == '-')
         return (LESS_LESS_MINUS);
           else if MBTEST(peek_char == '<')
         return (LESS_LESS_LESS);
           else
         {
           shell_ungetc (peek_char);
           return (LESS_LESS);
         }
         case '>':
           return (GREATER_GREATER);
         case ';':
           parser_state |= PST_CASEPAT;
 #if defined (ALIAS)
           parser_state &= ~PST_ALEXPNEXT;
 #endif /* ALIAS */
           peek_char = shell_getc (1);
           if MBTEST(peek_char == '&')
         return (SEMI_SEMI_AND);
           else
         {
           shell_ungetc (peek_char);
           return (SEMI_SEMI);
         }
         case '&':
           return (AND_AND);
         case '|':
           return (OR_OR);
 #if defined (DPAREN_ARITHMETIC) || defined (ARITH_FOR_COMMAND)
         case '(':       /* ) */
           result = parse_dparen (character);
           if (result == -2)
             break;
           else
             return result;
 #endif
         }
     }
       else if MBTEST(character == '<' && peek_char == '&')
     return (LESS_AND);
       else if MBTEST(character == '>' && peek_char == '&')
     return (GREATER_AND);
       else if MBTEST(character == '<' && peek_char == '>')
     return (LESS_GREATER);
       else if MBTEST(character == '>' && peek_char == '|')
     return (GREATER_BAR);
       else if MBTEST(character == '&' && peek_char == '>')
     {
       peek_char = shell_getc (1);
       if MBTEST(peek_char == '>')
         return (AND_GREATER_GREATER);
       else
         {
           shell_ungetc (peek_char);
           return (AND_GREATER);
         }
     }
       else if MBTEST(character == '|' && peek_char == '&')
     return (BAR_AND);
       else if MBTEST(character == ';' && peek_char == '&')
     {
       parser_state |= PST_CASEPAT;
 #if defined (ALIAS)
       parser_state &= ~PST_ALEXPNEXT;
 #endif /* ALIAS */
       return (SEMI_AND);
     }
       shell_ungetc (peek_char);
       /* If we look like we are reading the start of a function
      definition, then let the reader know about it so that
      we will do the right thing with `{'. */
       if MBTEST(character == ')' && last_read_token == '(' && token_before_that == WORD)
     {
       parser_state |= PST_ALLOWOPNBRC;
 #if defined (ALIAS)
       parser_state &= ~PST_ALEXPNEXT;
 #endif /* ALIAS */
       function_dstart = line_number;
     }
       /* case pattern lists may be preceded by an optional left paren.  If
      we're not trying to parse a case pattern list, the left paren
      indicates a subshell. */
       if MBTEST(character == '(' && (parser_state & PST_CASEPAT) == 0) /* ) */
     parser_state |= PST_SUBSHELL;
       /*(*/
       else if MBTEST((parser_state & PST_CASEPAT) && character == ')')
     parser_state &= ~PST_CASEPAT;
       /*(*/
       else if MBTEST((parser_state & PST_SUBSHELL) && character == ')')
     parser_state &= ~PST_SUBSHELL;
 #if defined (PROCESS_SUBSTITUTION)
       /* Check for the constructs which introduce process substitution.
      Shells running in `posix mode' don't do process substitution. */
       if MBTEST((character != '>' && character != '<') || peek_char != '(') /*)*/
 #endif /* PROCESS_SUBSTITUTION */
     return (character);
     }
   /* Hack <&- (close stdin) case.  Also <&N- (dup and close). */
   if MBTEST(character == '-' && (last_read_token == LESS_AND || last_read_token == GREATER_AND))
     return (character);
 tokword:
   /* Okay, if we got this far, we have to read a word.  Read one,
      and then check it against the known ones. */
   result = read_token_word (character);
 #if defined (ALIAS)
   if (result == RE_READ_TOKEN)
     goto re_read_token;
 #endif
   return result;
 }
References AND_AND, AND_GREATER, AND_GREATER_GREATER, ASSIGNMENT_WORD, BAR_AND, bash_input, YYSTYPE::command, COND_CMD, COND_END, discard_until(), EOF, EOF_Reached, expanding_alias, function_dstart, gather_here_documents(), GREATER_AND, GREATER_BAR, GREATER_GREATER, interactive, interactive_comments, INTERNAL_DEBUG, last_read_token, LESS_AND, LESS_GREATER, LESS_LESS, LESS_LESS_LESS, LESS_LESS_MINUS, line_number, BASH_INPUT::location, MBTEST, need_here_doc, NULL, OR_OR, parser_state, PST_ALEXPNEXT, PST_ALLOWOPNBRC, PST_ASSIGNOK, PST_CASEPAT, PST_CMDSUBST, PST_COMMENT, PST_CONDCMD, PST_CONDEXPR, PST_REGEXP, PST_SUBSHELL, RE_READ_TOKEN, read_token_word(), RESET, reset_parser(), SEMI_AND, SEMI_SEMI, SEMI_SEMI_AND, shell_eof_token, shell_getc(), shell_ungetc(), shellblank, shellmeta, st_string, INPUT_STREAM::string, token_before_that, token_to_read, BASH_INPUT::type, YYSTYPE::word, word_desc_to_read, yacc_EOF, and yylval.
Referenced by parse_compound_assignment(), parse_string_to_word_list(), and yylex().
read_token_word()
static int read_token_word (int character) static
Definition at line 7155 of file y.tab.c.
 {
   /* The value for YYLVAL when a WORD is read. */
   WORD_DESC *the_word;
   /* Index into the token that we are building. */
   int token_index;
   /* ALL_DIGITS becomes zero when we see a non-digit. */
   int all_digit_token;
   /* DOLLAR_PRESENT becomes non-zero if we see a `$'. */
   int dollar_present;
   /* COMPOUND_ASSIGNMENT becomes non-zero if we are parsing a compound
      assignment. */
   int compound_assignment;
   /* QUOTED becomes non-zero if we see one of ("), ('), (`), or (\‍). */
   int quoted;
   /* Non-zero means to ignore the value of the next character, and just
      to add it no matter what. */
   int pass_next_character;
   /* The current delimiting character. */
   int cd;
   int result, peek_char;
   char *ttok, *ttrans;
   int ttoklen, ttranslen;
   intmax_t lvalue;
   if (token_buffer_size < TOKEN_DEFAULT_INITIAL_SIZE)
     token = (char *)xrealloc (token, token_buffer_size = TOKEN_DEFAULT_INITIAL_SIZE);
   token_index = 0;
   all_digit_token = DIGIT (character);
   dollar_present = quoted = pass_next_character = compound_assignment = 0;
   for (;;)
     {
       if (character == EOF)
     goto got_token;
       if (pass_next_character)
     {
       pass_next_character = 0;
       goto got_escaped_character;
     }
       cd = current_delimiter (dstack);
       /* Handle backslashes.  Quote lots of things when not inside of
      double-quotes, quote some things inside of double-quotes. */
       if MBTEST(character == '\\')
     {
       if (parser_state & PST_NOEXPAND)
         {
           pass_next_character++;
           quoted = 1;
           goto got_character;
         }
       peek_char = shell_getc (0);
       /* Backslash-newline is ignored in all cases except
          when quoted with single quotes. */
       if MBTEST(peek_char == '\n')
         {
           character = '\n';
           goto next_character;
         }
       else
         {
           shell_ungetc (peek_char);
           /* If the next character is to be quoted, note it now. */
           if MBTEST(cd == 0 || cd == '`' ||
           (cd == '"' && peek_char >= 0 && (sh_syntaxtab[peek_char] & CBSDQUOTE)))
         pass_next_character++;
           quoted = 1;
           goto got_character;
         }
     }
       /* Parse a matched pair of quote characters. */
       if MBTEST(shellquote (character))
     {
       push_delimiter (dstack, character);
       ttok = parse_matched_pair (character, character, character, &ttoklen, (character == '`') ? P_COMMAND : 0);
       pop_delimiter (dstack);
       if (ttok == &matched_pair_error)
         return -1;      /* Bail immediately. */
       RESIZE_MALLOCED_BUFFER (token, token_index, ttoklen + 2,
                   token_buffer_size, TOKEN_DEFAULT_GROW_SIZE);
       token[token_index++] = character;
       strcpy (token + token_index, ttok);
       token_index += ttoklen;
       all_digit_token = 0;
       if (character != '`')
         quoted = 1;
       dollar_present |= (character == '"' && strchr (ttok, '$') != 0);
       FREE (ttok);
       goto next_character;
     }
 #ifdef COND_REGEXP
       /* When parsing a regexp as a single word inside a conditional command,
      we need to special-case characters special to both the shell and
      regular expressions.  Right now, that is only '(' and '|'. */ /*)*/
       if MBTEST((parser_state & PST_REGEXP) && (character == '(' || character == '|'))      /*)*/
     {
       if (character == '|')
         goto got_character;
       push_delimiter (dstack, character);
       ttok = parse_matched_pair (cd, '(', ')', &ttoklen, 0);
       pop_delimiter (dstack);
       if (ttok == &matched_pair_error)
         return -1;      /* Bail immediately. */
       RESIZE_MALLOCED_BUFFER (token, token_index, ttoklen + 2,
                   token_buffer_size, TOKEN_DEFAULT_GROW_SIZE);
       token[token_index++] = character;
       strcpy (token + token_index, ttok);
       token_index += ttoklen;
       FREE (ttok);
       dollar_present = all_digit_token = 0;
       goto next_character;
     }
 #endif /* COND_REGEXP */
 #ifdef EXTENDED_GLOB
       /* Parse a ksh-style extended pattern matching specification. */
       if MBTEST(extended_glob && PATTERN_CHAR (character))
     {
       peek_char = shell_getc (1);
       if MBTEST(peek_char == '(')       /* ) */
         {
           push_delimiter (dstack, peek_char);
           ttok = parse_matched_pair (cd, '(', ')', &ttoklen, 0);
           pop_delimiter (dstack);
           if (ttok == &matched_pair_error)
         return -1;      /* Bail immediately. */
           RESIZE_MALLOCED_BUFFER (token, token_index, ttoklen + 3,
                       token_buffer_size,
                       TOKEN_DEFAULT_GROW_SIZE);
           token[token_index++] = character;
           token[token_index++] = peek_char;
           strcpy (token + token_index, ttok);
           token_index += ttoklen;
           FREE (ttok);
           dollar_present = all_digit_token = 0;
           goto next_character;
         }
       else
         shell_ungetc (peek_char);
     }
 #endif /* EXTENDED_GLOB */
       /* If the delimiter character is not single quote, parse some of
      the shell expansions that must be read as a single word. */
       if MBTEST(shellexp (character))
     {
       peek_char = shell_getc (1);
       /* $(...), <(...), >(...), $((...)), ${...}, and $[...] constructs */
       if MBTEST(peek_char == '(' ||
         ((peek_char == '{' || peek_char == '[') && character == '$'))   /* ) ] } */
         {
           if (peek_char == '{')     /* } */
         ttok = parse_matched_pair (cd, '{', '}', &ttoklen, P_FIRSTCLOSE|P_DOLBRACE);
           else if (peek_char == '(')        /* ) */
         {
           /* XXX - push and pop the `(' as a delimiter for use by
              the command-oriented-history code.  This way newlines
              appearing in the $(...) string get added to the
              history literally rather than causing a possibly-
              incorrect `;' to be added. ) */
           push_delimiter (dstack, peek_char);
           ttok = parse_comsub (cd, '(', ')', &ttoklen, P_COMMAND);
           pop_delimiter (dstack);
         }
           else
         ttok = parse_matched_pair (cd, '[', ']', &ttoklen, P_ARITH);
           if (ttok == &matched_pair_error)
         return -1;      /* Bail immediately. */
           RESIZE_MALLOCED_BUFFER (token, token_index, ttoklen + 3,
                       token_buffer_size,
                       TOKEN_DEFAULT_GROW_SIZE);
           token[token_index++] = character;
           token[token_index++] = peek_char;
           strcpy (token + token_index, ttok);
           token_index += ttoklen;
           FREE (ttok);
           dollar_present = 1;
           all_digit_token = 0;
           goto next_character;
         }
       /* This handles $'...' and $"..." new-style quoted strings. */
 #if defined (TRANSLATABLE_STRINGS)
       else if MBTEST(character == '$' && (peek_char == '\'' || peek_char == '"'))
 #else
       else if MBTEST(character == '$' && peek_char == '\'')
 #endif
         {
           int first_line;
           first_line = line_number;
           push_delimiter (dstack, peek_char);
           ttok = parse_matched_pair (peek_char, peek_char, peek_char,
                      &ttoklen,
                      (peek_char == '\'') ? P_ALLOWESC : 0);
           pop_delimiter (dstack);
           if (ttok == &matched_pair_error)
         return -1;
           if (peek_char == '\'')
         {
           /* PST_NOEXPAND */
           ttrans = ansiexpand (ttok, 0, ttoklen - 1, &ttranslen);
           free (ttok);
           /* Insert the single quotes and correctly quote any
              embedded single quotes (allowed because P_ALLOWESC was
              passed to parse_matched_pair). */
           ttok = sh_single_quote (ttrans);
           free (ttrans);
           ttranslen = strlen (ttok);
           ttrans = ttok;
         }
 #if defined (TRANSLATABLE_STRINGS)
           else
         {
           /* PST_NOEXPAND */
           /* Try to locale-expand the converted string. */
           ttrans = locale_expand (ttok, 0, ttoklen - 1, first_line, &ttranslen);
           free (ttok);
           /* Add the double quotes back (or single quotes if the user
              has set that option). */
           if (singlequote_translations &&
                 ((ttoklen - 1) != ttranslen || STREQN (ttok, ttrans, ttranslen) == 0))
             ttok = sh_single_quote (ttrans);
           else
             ttok = sh_mkdoublequoted (ttrans, ttranslen, 0);
           free (ttrans);
           ttrans = ttok;
           ttranslen = strlen (ttrans);
         }
 #endif /* TRANSLATABLE_STRINGS */
           RESIZE_MALLOCED_BUFFER (token, token_index, ttranslen + 1,
                       token_buffer_size,
                       TOKEN_DEFAULT_GROW_SIZE);
           strcpy (token + token_index, ttrans);
           token_index += ttranslen;
           FREE (ttrans);
           quoted = 1;
           all_digit_token = 0;
           goto next_character;
         }
       /* This could eventually be extended to recognize all of the
          shell's single-character parameter expansions, and set flags.*/
       else if MBTEST(character == '$' && peek_char == '$')
         {
           RESIZE_MALLOCED_BUFFER (token, token_index, 3,
                       token_buffer_size,
                       TOKEN_DEFAULT_GROW_SIZE);
           token[token_index++] = '$';
           token[token_index++] = peek_char;
           dollar_present = 1;
           all_digit_token = 0;
           goto next_character;
         }
       else
         shell_ungetc (peek_char);
     }
 #if defined (ARRAY_VARS)
       /* Identify possible array subscript assignment; match [...].  If
      parser_state&PST_COMPASSIGN, we need to parse [sub]=words treating
      `sub' as if it were enclosed in double quotes. */
       else if MBTEST(character == '[' &&        /* ] */
              ((token_index > 0 && assignment_acceptable (last_read_token) && token_is_ident (token, token_index)) ||
               (token_index == 0 && (parser_state&PST_COMPASSIGN))))
         {
       ttok = parse_matched_pair (cd, '[', ']', &ttoklen, P_ARRAYSUB);
       if (ttok == &matched_pair_error)
         return -1;      /* Bail immediately. */
       RESIZE_MALLOCED_BUFFER (token, token_index, ttoklen + 2,
                   token_buffer_size,
                   TOKEN_DEFAULT_GROW_SIZE);
       token[token_index++] = character;
       strcpy (token + token_index, ttok);
       token_index += ttoklen;
       FREE (ttok);
       all_digit_token = 0;
       goto next_character;
         }
       /* Identify possible compound array variable assignment. */
       else if MBTEST(character == '=' && token_index > 0 && (assignment_acceptable (last_read_token) || (parser_state & PST_ASSIGNOK)) && token_is_assignment (token, token_index))
     {
       peek_char = shell_getc (1);
       if MBTEST(peek_char == '(')       /* ) */
         {
           ttok = parse_compound_assignment (&ttoklen);
           RESIZE_MALLOCED_BUFFER (token, token_index, ttoklen + 4,
                       token_buffer_size,
                       TOKEN_DEFAULT_GROW_SIZE);
           token[token_index++] = '=';
           token[token_index++] = '(';
           if (ttok)
         {
           strcpy (token + token_index, ttok);
           token_index += ttoklen;
         }
           token[token_index++] = ')';
           FREE (ttok);
           all_digit_token = 0;
           compound_assignment = 1;
 #if 1
           goto next_character;
 #else
           goto got_token;       /* ksh93 seems to do this */
 #endif
         }
       else
         shell_ungetc (peek_char);
     }
 #endif
       /* When not parsing a multi-character word construct, shell meta-
      characters break words. */
       if MBTEST(shellbreak (character))
     {
       shell_ungetc (character);
       goto got_token;
     }
 got_character:
       if MBTEST(character == CTLESC || character == CTLNUL)
     {
       RESIZE_MALLOCED_BUFFER (token, token_index, 2, token_buffer_size,
                   TOKEN_DEFAULT_GROW_SIZE);
       token[token_index++] = CTLESC;
     }
       else
 got_escaped_character:
     RESIZE_MALLOCED_BUFFER (token, token_index, 1, token_buffer_size,
                 TOKEN_DEFAULT_GROW_SIZE);
       token[token_index++] = character;
       all_digit_token &= DIGIT (character);
       dollar_present |= character == '$';
     next_character:
       if (character == '\n' && SHOULD_PROMPT ())
     prompt_again (0);
       /* We want to remove quoted newlines (that is, a <newline> pair)
      unless we are within single quotes or pass_next_character is
      set (the shell equivalent of literal-next). */
       cd = current_delimiter (dstack);
       character = shell_getc (cd != '\'' && pass_next_character == 0);
     }   /* end for (;;) */
 got_token:
   /* Calls to RESIZE_MALLOCED_BUFFER ensure there is sufficient room. */
   token[token_index] = '\0';
   /* Check to see what thing we should return.  If the last_read_token
      is a `<', or a `&', or the character which ended this token is
      a '>' or '<', then, and ONLY then, is this input token a NUMBER.
      Otherwise, it is just a word, and should be returned as such. */
   if MBTEST(all_digit_token && (character == '<' || character == '>' ||
             last_read_token == LESS_AND ||
             last_read_token == GREATER_AND))
       {
     if (legal_number (token, &lvalue) && (int)lvalue == lvalue)
       {
         yylval.number = lvalue;
         return (NUMBER);
       }
       }
   /* Check for special case tokens. */
   result = (last_shell_getc_is_singlebyte) ? special_case_tokens (token) : -1;
   if (result >= 0)
     return result;
 #if defined (ALIAS)
   /* Posix.2 does not allow reserved words to be aliased, so check for all
      of them, including special cases, before expanding the current token
      as an alias. */
   if MBTEST(posixly_correct)
     CHECK_FOR_RESERVED_WORD (token);
   /* Aliases are expanded iff EXPAND_ALIASES is non-zero, and quoting
      inhibits alias expansion. */
   if (expand_aliases && quoted == 0)
     {
       result = alias_expand_token (token);
       if (result == RE_READ_TOKEN)
     return (RE_READ_TOKEN);
       else if (result == NO_EXPANSION)
     parser_state &= ~PST_ALEXPNEXT;
     }
   /* If not in Posix.2 mode, check for reserved words after alias
      expansion. */
   if MBTEST(posixly_correct == 0)
 #endif
     CHECK_FOR_RESERVED_WORD (token);
   the_word = alloc_word_desc ();
   the_word->word = (char *)xmalloc (1 + token_index);
   the_word->flags = 0;
   strcpy (the_word->word, token);
   if (dollar_present)
     the_word->flags |= W_HASDOLLAR;
   if (quoted)
     the_word->flags |= W_QUOTED;        /*(*/
   if (compound_assignment && token[token_index-1] == ')')
     the_word->flags |= W_COMPASSIGN;
   /* A word is an assignment if it appears at the beginning of a
      simple command, or after another assignment word.  This is
      context-dependent, so it cannot be handled in the grammar. */
   if (assignment (token, (parser_state & PST_COMPASSIGN) != 0))
     {
       the_word->flags |= W_ASSIGNMENT;
       /* Don't perform word splitting on assignment statements. */
       if (assignment_acceptable (last_read_token) || (parser_state & PST_COMPASSIGN) != 0)
     {
       the_word->flags |= W_NOSPLIT;
       if (parser_state & PST_COMPASSIGN)
         the_word->flags |= W_NOGLOB;    /* XXX - W_NOBRACE? */
     }
     }
   if (command_token_position (last_read_token))
     {
       struct builtin *b;
       b = builtin_address_internal (token, 0);
       if (b && (b->flags & ASSIGNMENT_BUILTIN))
     parser_state |= PST_ASSIGNOK;
       else if (STREQ (token, "eval") || STREQ (token, "let"))
     parser_state |= PST_ASSIGNOK;
     }
   yylval.word = the_word;
   /* should we check that quoted == 0 as well? */
   if MBTEST(token[0] == '{' && token[token_index-1] == '}' &&
       (character == '<' || character == '>'))
     {
       /* can use token; already copied to the_word */
       token[token_index-1] = '\0';
 #if defined (ARRAY_VARS)
       if (legal_identifier (token+1) || valid_array_reference (token+1, 0))
 #else
       if (legal_identifier (token+1))
 #endif
     {
       strcpy (the_word->word, token+1);
 /* itrace("read_token_word: returning REDIR_WORD for %s", the_word->word); */
       yylval.word = the_word;   /* accommodate recursive call */
       return (REDIR_WORD);
     }
       else
         /* valid_array_reference can call the parser recursively; need to
        make sure that yylval.word doesn't change if we are going to
        return WORD or ASSIGNMENT_WORD */
         yylval.word = the_word;
     }
   result = ((the_word->flags & (W_ASSIGNMENT|W_NOSPLIT)) == (W_ASSIGNMENT|W_NOSPLIT))
         ? ASSIGNMENT_WORD : WORD;
   switch (last_read_token)
     {
     case FUNCTION:
       parser_state |= PST_ALLOWOPNBRC;
       function_dstart = line_number;
       break;
     case CASE:
     case SELECT:
     case FOR:
       if (word_top < MAX_CASE_NEST)
     word_top++;
       word_lineno[word_top] = line_number;
       expecting_in_token++;
       break;
     }
   return (result);
 }
References alloc_word_desc(), ansiexpand(), assignment(), assignment_acceptable, ASSIGNMENT_BUILTIN, ASSIGNMENT_WORD, builtin_address_internal(), CASE, CBSDQUOTE, CHECK_FOR_RESERVED_WORD, command_token_position, CTLESC, CTLNUL, current_delimiter, DIGIT, EOF, expand_aliases, expecting_in_token, extended_glob, builtin::flags, word_desc::flags, FOR, FREE, free(), FUNCTION, function_dstart, GREATER_AND, last_read_token, last_shell_getc_is_singlebyte, legal_identifier(), legal_number(), LESS_AND, line_number, matched_pair_error, MAX_CASE_NEST, MBTEST, NO_EXPANSION, NUMBER, YYSTYPE::number, P_ALLOWESC, P_ARITH, P_ARRAYSUB, P_COMMAND, P_DOLBRACE, P_FIRSTCLOSE, parse_compound_assignment(), parse_comsub(), parse_matched_pair(), parser_state, PATTERN_CHAR, pop_delimiter, posixly_correct, prompt_again(), PST_ALEXPNEXT, PST_ALLOWOPNBRC, PST_ASSIGNOK, PST_COMPASSIGN, PST_NOEXPAND, PST_REGEXP, push_delimiter, RE_READ_TOKEN, REDIR_WORD, RESIZE_MALLOCED_BUFFER, SELECT, sh_mkdoublequoted(), sh_single_quote(), sh_syntaxtab, shell_getc(), shell_ungetc(), shellbreak, shellexp, shellquote, SHOULD_PROMPT, singlequote_translations, special_case_tokens(), strchr(), strcpy, STREQ, STREQN, strlen(), token_buffer_size, TOKEN_DEFAULT_GROW_SIZE, TOKEN_DEFAULT_INITIAL_SIZE, W_ASSIGNMENT, W_COMPASSIGN, W_HASDOLLAR, W_NOGLOB, W_NOSPLIT, W_QUOTED, word_desc::word, WORD, YYSTYPE::word, word_lineno, word_top, xmalloc, xrealloc, and yylval.
Referenced by read_token().
report_syntax_error()
static void report_syntax_error (char * message) static
Definition at line 8526 of file y.tab.c.
 {
   char *msg, *p;
   if (message)
     {
       parser_error (line_number, "%s", message);
       if (interactive && EOF_Reached)
     EOF_Reached = 0;
       last_command_exit_value = (executing_builtin && parse_and_execute_level) ? EX_BADSYNTAX : EX_BADUSAGE;
       set_pipestatus_from_exit (last_command_exit_value);
       return;
     }
   /* If the line of input we're reading is not null, try to find the
      objectionable token.  First, try to figure out what token the
      parser's complaining about by looking at current_token. */
   if (current_token != 0 && EOF_Reached == 0 && (msg = error_token_from_token (current_token)))
     {
       if (ansic_shouldquote (msg))
     {
       p = ansic_quote (msg, 0, NULL);
       free (msg);
       msg = p;
     }
       parser_error (line_number, _("syntax error near unexpected token `%s'"), msg);
       free (msg);
       if (interactive == 0)
     print_offending_line ();
       last_command_exit_value = (executing_builtin && parse_and_execute_level) ? EX_BADSYNTAX : EX_BADUSAGE;
       set_pipestatus_from_exit (last_command_exit_value);
       return;
     }
   /* If looking at the current token doesn't prove fruitful, try to find the
      offending token by analyzing the text of the input line near the current
      input line index and report what we find. */
   if (shell_input_line && *shell_input_line)
     {
       msg = error_token_from_text ();
       if (msg)
     {
       parser_error (line_number, _("syntax error near `%s'"), msg);
       free (msg);
     }
       /* If not interactive, print the line containing the error. */
       if (interactive == 0)
         print_offending_line ();
     }
   else
     {
       if (EOF_Reached && shell_eof_token && current_token != shell_eof_token)
     parser_error (line_number, _("unexpected EOF while looking for matching `%c'"), shell_eof_token);
       else
     {
       msg = EOF_Reached ? _("syntax error: unexpected end of file") : _("syntax error");
       parser_error (line_number, "%s", msg);
     }
       /* When the shell is interactive, this file uses EOF_Reached
      only for error reporting.  Other mechanisms are used to
      decide whether or not to exit. */
       if (interactive && EOF_Reached)
     EOF_Reached = 0;
     }
   last_command_exit_value = (executing_builtin && parse_and_execute_level) ? EX_BADSYNTAX : EX_BADUSAGE;
   set_pipestatus_from_exit (last_command_exit_value);
 }
References _, ansic_quote(), ansic_shouldquote(), current_token, EOF_Reached, error_token_from_text(), error_token_from_token(), EX_BADSYNTAX, EX_BADUSAGE, executing_builtin, free(), interactive, last_command_exit_value, line_number, NULL, p, parse_and_execute_level, parser_error(), print_offending_line(), set_pipestatus_from_exit(), shell_eof_token, and shell_input_line.
Referenced by push_heredoc(), and yyerror().
reserved_word_acceptable()
static int reserved_word_acceptable (int toksym) static
Definition at line 7660 of file y.tab.c.
 {
   switch (toksym)
     {
     case '\n':
     case ';':
     case '(':
     case ')':
     case '|':
     case '&':
     case '{':
     case '}':       /* XXX */
     case AND_AND:
     case ARITH_CMD:
     case BANG:
     case BAR_AND:
     case COND_END:
     case DO:
     case DONE:
     case ELIF:
     case ELSE:
     case ESAC:
     case FI:
     case IF:
     case OR_OR:
     case SEMI_SEMI:
     case SEMI_AND:
     case SEMI_SEMI_AND:
     case THEN:
     case TIME:
     case TIMEOPT:
     case TIMEIGN:
     case COPROC:
     case UNTIL:
     case WHILE:
     case 0:
     case DOLPAREN:
       return 1;
     default:
 #if defined (COPROCESS_SUPPORT)
       if (last_read_token == WORD && token_before_that == COPROC)
     return 1;
 #endif
       if (last_read_token == WORD && token_before_that == FUNCTION)
     return 1;
       return 0;
     }
 }
References AND_AND, ARITH_CMD, BANG, BAR_AND, COND_END, COPROC, DO, DOLPAREN, DONE, ELIF, ELSE, ESAC, FI, FUNCTION, IF, last_read_token, OR_OR, SEMI_AND, SEMI_SEMI, SEMI_SEMI_AND, THEN, TIME, TIMEIGN, TIMEOPT, token_before_that, UNTIL, and WHILE.
Referenced by special_case_tokens().
reset_parser()
void reset_parser ()
Definition at line 5610 of file y.tab.c.
 {
   dstack.delimiter_depth = 0;   /* No delimiters found so far. */
   open_brace_count = 0;
 #if defined (EXTENDED_GLOB)
   /* Reset to global value of extended glob */
   if (parser_state & (PST_EXTPAT|PST_CMDSUBST))
     extended_glob = extglob_flag;
 #endif
   if (parser_state & (PST_CMDSUBST|PST_STRING))
     expand_aliases = expaliases_flag;
   parser_state = 0;
   here_doc_first_line = 0;
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   if (pushed_string_list)
     free_string_list ();
 #endif /* ALIAS || DPAREN_ARITHMETIC */
   /* This is where we resynchronize to the next newline on error/reset */
   if (shell_input_line)
     {
       free (shell_input_line);
       shell_input_line = (char *)NULL;
       shell_input_line_size = shell_input_line_index = 0;
     }
   FREE (word_desc_to_read);
   word_desc_to_read = (WORD_DESC *)NULL;
   eol_ungetc_lookahead = 0;
   /* added post-bash-5.1 */
   need_here_doc = 0;
   redir_stack[0] = 0;
   esacs_needed_count = expecting_in_token = 0;
   current_token = '\n';     /* XXX */
   last_read_token = '\n';
   token_to_read = '\n';
 }
References current_token, dstack::delimiter_depth, eol_ungetc_lookahead, esacs_needed_count, expaliases_flag, expand_aliases, expecting_in_token, extended_glob, FREE, free(), free_string_list(), here_doc_first_line, last_read_token, need_here_doc, NULL, open_brace_count, parser_state, PST_CMDSUBST, PST_EXTPAT, PST_STRING, pushed_string_list, redir_stack, shell_input_line, shell_input_line_index, shell_input_line_size, token_to_read, and word_desc_to_read.
Referenced by handle_eof_input_unit(), parse_and_execute(), parse_string(), parse_string_to_command(), push_heredoc(), read_token(), run_exit_trap(), shell_execve(), throw_to_top_level(), xparse_dolparen(), and yyerror().
reset_readahead_token()
void reset_readahead_token ()
Definition at line 5655 of file y.tab.c.
 {
   if (token_to_read == '\n')
     token_to_read = 0;
 }
References token_to_read.
Referenced by reader_loop().
restore_input_line_state()
void restore_input_line_state (sh_input_line_state_t * ls)
Definition at line 9025 of file y.tab.c.
 {
   FREE (shell_input_line);
   shell_input_line = ls->input_line;
   shell_input_line_size = ls->input_line_size;
   shell_input_line_len = ls->input_line_len;
   shell_input_line_index = ls->input_line_index;
 #if defined (HANDLE_MULTIBYTE)
   FREE (shell_input_line_property);
   shell_input_line_property = ls->input_property;
   shell_input_line_propsize = ls->input_propsize;
 #endif
 #if 0
   set_line_mbstate ();
 #endif
 }
References FREE, _sh_input_line_state_t::input_line, _sh_input_line_state_t::input_line_index, _sh_input_line_state_t::input_line_len, _sh_input_line_state_t::input_line_size, set_line_mbstate, shell_input_line, shell_input_line_index, shell_input_line_len, and shell_input_line_size.
Referenced by parse_string_to_command(), and xparse_dolparen().
restore_parser_state()
void restore_parser_state (sh_parser_state_t * ps)
Definition at line 8927 of file y.tab.c.
 {
   int i;
   if (ps == 0)
     return;
   parser_state = ps->parser_state;
   if (ps->token_state)
     {
       restore_token_state (ps->token_state);
       free (ps->token_state);
     }
   shell_input_line_terminator = ps->input_line_terminator;
   eof_encountered = ps->eof_encountered;
   eol_ungetc_lookahead = ps->eol_lookahead;
   prompt_string_pointer = ps->prompt_string_pointer;
   current_command_line_count = ps->current_command_line_count;
 #if defined (HISTORY)
   remember_on_history = ps->remember_on_history;
 #  if defined (BANG_HISTORY)
   history_expansion_inhibited = ps->history_expansion_inhibited;
 #  endif
 #endif
   last_command_exit_value = ps->last_command_exit_value;
 #if defined (ARRAY_VARS)
   restore_pipestatus_array (ps->pipestatus);
 #endif
   last_shell_builtin = ps->last_shell_builtin;
   this_shell_builtin = ps->this_shell_builtin;
   expand_aliases = ps->expand_aliases;
   echo_input_at_read = ps->echo_input_at_read;
   need_here_doc = ps->need_here_doc;
   here_doc_first_line = ps->here_doc_first_line;
   esacs_needed_count = ps->esacs_needed;
   expecting_in_token = ps->expecting_in;
 #if 0
   for (i = 0; i < HEREDOC_MAX; i++)
     redir_stack[i] = ps->redir_stack[i];
 #else
   if (need_here_doc == 0)
     redir_stack[0] = 0;
   else
     memcpy (redir_stack, ps->redir_stack, sizeof (redir_stack[0]) * HEREDOC_MAX);
 #endif
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   pushed_string_list = (STRING_SAVER *)ps->pushed_strings;
 #endif
   FREE (token);
   token = ps->token;
   token_buffer_size = ps->token_buffer_size;
   shell_eof_token = ps->eof_token;
 }
References _sh_parser_state_t::current_command_line_count, current_command_line_count, echo_input_at_read, _sh_parser_state_t::echo_input_at_read, _sh_parser_state_t::eof_encountered, eof_encountered, _sh_parser_state_t::eof_token, _sh_parser_state_t::eol_lookahead, eol_ungetc_lookahead, _sh_parser_state_t::esacs_needed, esacs_needed_count, _sh_parser_state_t::expand_aliases, expand_aliases, _sh_parser_state_t::expecting_in, expecting_in_token, FREE, free(), here_doc_first_line, _sh_parser_state_t::here_doc_first_line, HEREDOC_MAX, i, if(), _sh_parser_state_t::input_line_terminator, last_command_exit_value, _sh_parser_state_t::last_command_exit_value, last_shell_builtin, _sh_parser_state_t::last_shell_builtin, memcpy, _sh_parser_state_t::need_here_doc, need_here_doc, _sh_parser_state_t::parser_state, parser_state, _sh_parser_state_t::prompt_string_pointer, prompt_string_pointer, pushed_string_list, _sh_parser_state_t::pushed_strings, _sh_parser_state_t::redir_stack, redir_stack, remember_on_history, restore_token_state(), shell_eof_token, shell_input_line_terminator, this_shell_builtin, _sh_parser_state_t::this_shell_builtin, _sh_parser_state_t::token, _sh_parser_state_t::token_buffer_size, token_buffer_size, and _sh_parser_state_t::token_state.
Referenced by _run_trap_internal(), execute_variable_command(), parse_compound_assignment(), parse_comsub(), parse_string_to_command(), parse_string_to_word_list(), run_pending_traps(), and xparse_dolparen().
restore_token_state()
void restore_token_state (int * ts)
Definition at line 4157 of file y.tab.c.
 {
   if (ts == 0)
     return;
   last_read_token = ts[0];
   token_before_that = ts[1];
   two_tokens_ago = ts[2];
   current_token = ts[3];
 }
References current_token, last_read_token, token_before_that, and two_tokens_ago.
Referenced by restore_parser_state().
return_EOF()
int return_EOF ()
Definition at line 3716 of file y.tab.c.
 {
   return (EOF);
 }
References EOF.
rewind_input_string()
void rewind_input_string ()
Definition at line 3969 of file y.tab.c.
 {
   int xchars;
   /* number of unconsumed characters in the input -- XXX need to take newlines
      into account, e.g., $(...\n) */
   xchars = shell_input_line_len - shell_input_line_index;
   if (bash_input.location.string[-1] == '\n')
     xchars++;
   /* XXX - how to reflect bash_input.location.string back to string passed to
      parse_and_execute or xparse_dolparen? xparse_dolparen needs to know how
      far into the string we parsed.  parse_and_execute knows where bash_input.
      location.string is, and how far from orig_string that is -- that's the
      number of characters the command consumed. */
   /* bash_input.location.string - xchars should be where we parsed to */
   /* need to do more validation on xchars value for sanity -- test cases. */
   bash_input.location.string -= xchars;
 }
References bash_input, BASH_INPUT::location, shell_input_line_index, shell_input_line_len, and INPUT_STREAM::string.
Referenced by parse_string(), and yyparse().
save_input_line_state()
sh_input_line_state_t* save_input_line_state (sh_input_line_state_t * ls)
Definition at line 8994 of file y.tab.c.
 {
   if (ls == 0)
     ls = (sh_input_line_state_t *)xmalloc (sizeof (sh_input_line_state_t));
   if (ls == 0)
     return ((sh_input_line_state_t *)NULL);
   ls->input_line = shell_input_line;
   ls->input_line_size = shell_input_line_size;
   ls->input_line_len = shell_input_line_len;
   ls->input_line_index = shell_input_line_index;
 #if defined (HANDLE_MULTIBYTE)
   ls->input_property = shell_input_line_property;
   ls->input_propsize = shell_input_line_propsize;
 #endif
   /* force reallocation */
   shell_input_line = 0;
   shell_input_line_size = shell_input_line_len = shell_input_line_index = 0;
 #if defined (HANDLE_MULTIBYTE)
   shell_input_line_property = 0;
   shell_input_line_propsize = 0;
 #endif
   return ls;
 }
References _sh_input_line_state_t::input_line, _sh_input_line_state_t::input_line_index, _sh_input_line_state_t::input_line_len, _sh_input_line_state_t::input_line_size, NULL, shell_input_line, shell_input_line_index, shell_input_line_len, shell_input_line_size, and xmalloc.
Referenced by parse_string_to_command(), and xparse_dolparen().
save_parser_state()
sh_parser_state_t* save_parser_state (sh_parser_state_t * ps)
Definition at line 8865 of file y.tab.c.
 {
   if (ps == 0)
     ps = (sh_parser_state_t *)xmalloc (sizeof (sh_parser_state_t));
   if (ps == 0)
     return ((sh_parser_state_t *)NULL);
   ps->parser_state = parser_state;
   ps->token_state = save_token_state ();
   ps->input_line_terminator = shell_input_line_terminator;
   ps->eof_encountered = eof_encountered;
   ps->eol_lookahead = eol_ungetc_lookahead;
   ps->prompt_string_pointer = prompt_string_pointer;
   ps->current_command_line_count = current_command_line_count;
 #if defined (HISTORY)
   ps->remember_on_history = remember_on_history;
 #  if defined (BANG_HISTORY)
   ps->history_expansion_inhibited = history_expansion_inhibited;
 #  endif
 #endif
   ps->last_command_exit_value = last_command_exit_value;
 #if defined (ARRAY_VARS)
   ps->pipestatus = save_pipestatus_array ();
 #endif
   ps->last_shell_builtin = last_shell_builtin;
   ps->this_shell_builtin = this_shell_builtin;
   ps->expand_aliases = expand_aliases;
   ps->echo_input_at_read = echo_input_at_read;
   ps->need_here_doc = need_here_doc;
   ps->here_doc_first_line = here_doc_first_line;
   ps->esacs_needed = esacs_needed_count;
   ps->expecting_in = expecting_in_token;
   if (need_here_doc == 0)
     ps->redir_stack[0] = 0;
   else
     memcpy (ps->redir_stack, redir_stack, sizeof (redir_stack[0]) * HEREDOC_MAX);
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   ps->pushed_strings = pushed_string_list;
 #endif
   ps->eof_token = shell_eof_token;
   ps->token = token;
   ps->token_buffer_size = token_buffer_size;
   /* Force reallocation on next call to read_token_word */
   token = 0;
   token_buffer_size = 0;
   return (ps);
 }
References _sh_parser_state_t::current_command_line_count, current_command_line_count, echo_input_at_read, _sh_parser_state_t::echo_input_at_read, _sh_parser_state_t::eof_encountered, eof_encountered, _sh_parser_state_t::eof_token, _sh_parser_state_t::eol_lookahead, eol_ungetc_lookahead, _sh_parser_state_t::esacs_needed, esacs_needed_count, _sh_parser_state_t::expand_aliases, expand_aliases, _sh_parser_state_t::expecting_in, expecting_in_token, here_doc_first_line, _sh_parser_state_t::here_doc_first_line, HEREDOC_MAX, _sh_parser_state_t::input_line_terminator, last_command_exit_value, _sh_parser_state_t::last_command_exit_value, last_shell_builtin, _sh_parser_state_t::last_shell_builtin, memcpy, _sh_parser_state_t::need_here_doc, need_here_doc, NULL, _sh_parser_state_t::parser_state, parser_state, _sh_parser_state_t::prompt_string_pointer, prompt_string_pointer, pushed_string_list, _sh_parser_state_t::pushed_strings, _sh_parser_state_t::redir_stack, redir_stack, remember_on_history, save_token_state(), shell_eof_token, shell_input_line_terminator, this_shell_builtin, _sh_parser_state_t::this_shell_builtin, _sh_parser_state_t::token, token, _sh_parser_state_t::token_buffer_size, token_buffer_size, _sh_parser_state_t::token_state, and xmalloc.
Referenced by _run_trap_internal(), execute_variable_command(), parse_compound_assignment(), parse_comsub(), parse_string_to_command(), parse_string_to_word_list(), run_pending_traps(), and xparse_dolparen().
save_token_state()
int* save_token_state ()
Definition at line 4144 of file y.tab.c.
 {
   int *ret;
   ret = (int *)xmalloc (4 * sizeof (int));
   ret[0] = last_read_token;
   ret[1] = token_before_that;
   ret[2] = two_tokens_ago;
   ret[3] = current_token;
   return ret;
 }
References current_token, last_read_token, token_before_that, two_tokens_ago, and xmalloc.
Referenced by save_parser_state().
set_current_prompt_level()
void set_current_prompt_level (int x)
Definition at line 7920 of file y.tab.c.
 {
   prompt_string_pointer = (x == 2) ? &ps2_prompt : &ps1_prompt;
   current_prompt_string = *prompt_string_pointer;
 }
References current_prompt_string, prompt_string_pointer, ps1_prompt, ps2_prompt, and x.
Referenced by parse_prologue(), and read_command().
shell_getc()
static int shell_getc (int remove_quoted_newline) static
Definition at line 4623 of file y.tab.c.
 {
   register int i;
   int c, truncating, last_was_backslash;
   unsigned char uc;
   QUIT;
   last_was_backslash = 0;
   if (sigwinch_received)
     {
       sigwinch_received = 0;
       get_new_window_size (0, (int *)0, (int *)0);
     }
   if (eol_ungetc_lookahead)
     {
       c = eol_ungetc_lookahead;
       eol_ungetc_lookahead = 0;
       return (c);
     }
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   /* If shell_input_line[shell_input_line_index] == 0, but there is
      something on the pushed list of strings, then we don't want to go
      off and get another line.  We let the code down below handle it. */
   if (!shell_input_line || ((!shell_input_line[shell_input_line_index]) &&
                 (pushed_string_list == (STRING_SAVER *)NULL)))
 #else /* !ALIAS && !DPAREN_ARITHMETIC */
   if (!shell_input_line || !shell_input_line[shell_input_line_index])
 #endif /* !ALIAS && !DPAREN_ARITHMETIC */
     {
       line_number++;
       /* Let's not let one really really long line blow up memory allocation */
       if (shell_input_line && shell_input_line_size >= 32768)
     {
       free (shell_input_line);
       shell_input_line = 0;
       shell_input_line_size = 0;
     }
     restart_read:
       /* Allow immediate exit if interrupted during input. */
       QUIT;
       i = truncating = 0;
       shell_input_line_terminator = 0;
       /* If the shell is interactive, but not currently printing a prompt
          (interactive_shell && interactive == 0), we don't want to print
          notifies or cleanup the jobs -- we want to defer it until we do
          print the next prompt. */
       if (interactive_shell == 0 || SHOULD_PROMPT())
     {
 #if defined (JOB_CONTROL)
       /* This can cause a problem when reading a command as the result
      of a trap, when the trap is called from flush_child.  This call
      had better not cause jobs to disappear from the job table in
      that case, or we will have big trouble. */
       notify_and_cleanup ();
 #else /* !JOB_CONTROL */
       cleanup_dead_jobs ();
 #endif /* !JOB_CONTROL */
     }
 #if defined (READLINE)
       if (no_line_editing && SHOULD_PROMPT())
 #else
       if (SHOULD_PROMPT())
 #endif
     print_prompt ();
       if (bash_input.type == st_stream)
     clearerr (stdin);
       while (1)
     {
       c = yy_getc ();
       /* Allow immediate exit if interrupted during input. */
       QUIT;
       if (c == '\0')
         {
           /* If we get EOS while parsing a string, treat it as EOF so we
          don't just keep looping. Happens very rarely */
           if (bash_input.type == st_string)
         {
           if (i == 0)
             shell_input_line_terminator = EOF;
           shell_input_line[i] = '\0';
           c = EOF;
           break;
         }
           continue;
         }
       /* Theoretical overflow */
       /* If we can't put 256 bytes more into the buffer, allocate
          everything we can and fill it as full as we can. */
       /* XXX - we ignore rest of line using `truncating' flag */
       if (shell_input_line_size > (SIZE_MAX - 256))
         {
           size_t n;
           n = SIZE_MAX - i; /* how much more can we put into the buffer? */
           if (n <= 2)   /* we have to save 1 for the newline added below */
         {
           if (truncating == 0)
             internal_warning(_("shell_getc: shell_input_line_size (%zu) exceeds SIZE_MAX (%lu): line truncated"), shell_input_line_size, (unsigned long)SIZE_MAX);
           shell_input_line[i] = '\0';
           truncating = 1;
         }
           if (shell_input_line_size < SIZE_MAX)
         {
           shell_input_line_size = SIZE_MAX;
           shell_input_line = xrealloc (shell_input_line, shell_input_line_size);
         }
         }
       else
         RESIZE_MALLOCED_BUFFER (shell_input_line, i, 2, shell_input_line_size, 256);
       if (c == EOF)
         {
           if (bash_input.type == st_stream)
         clearerr (stdin);
           if (i == 0)
         shell_input_line_terminator = EOF;
           shell_input_line[i] = '\0';
           break;
         }
       if (truncating == 0 || c == '\n')
         shell_input_line[i++] = c;
       if (c == '\n')
         {
           shell_input_line[--i] = '\0';
           current_command_line_count++;
           break;
         }
       last_was_backslash = last_was_backslash == 0 && c == '\\';
     }
       shell_input_line_index = 0;
       shell_input_line_len = i;     /* == strlen (shell_input_line) */
       set_line_mbstate ();
 #if defined (HISTORY)
       if (remember_on_history && shell_input_line && shell_input_line[0])
     {
       char *expansions;
 #  if defined (BANG_HISTORY)
       /* If the current delimiter is a single quote, we should not be
          performing history expansion, even if we're on a different
          line from the original single quote. */
       if (current_delimiter (dstack) == '\'')
         history_quoting_state = '\'';
       else if (current_delimiter (dstack) == '"')
         history_quoting_state = '"';
       else
         history_quoting_state = 0;
 #  endif
       /* Calling with a third argument of 1 allows remember_on_history to
          determine whether or not the line is saved to the history list */
       expansions = pre_process_line (shell_input_line, 1, 1);
 #  if defined (BANG_HISTORY)
       history_quoting_state = 0;
 #  endif
       if (expansions != shell_input_line)
         {
           free (shell_input_line);
           shell_input_line = expansions;
           shell_input_line_len = shell_input_line ?
                     strlen (shell_input_line) : 0;
           if (shell_input_line_len == 0)
         current_command_line_count--;
           /* We have to force the xrealloc below because we don't know
          the true allocated size of shell_input_line anymore. */
           shell_input_line_size = shell_input_line_len;
           set_line_mbstate ();
         }
     }
       /* Try to do something intelligent with blank lines encountered while
      entering multi-line commands.  XXX - this is grotesque */
       else if (remember_on_history && shell_input_line &&
            shell_input_line[0] == '\0' &&
            current_command_line_count > 1)
     {
       if (current_delimiter (dstack))
         /* We know shell_input_line[0] == 0 and we're reading some sort of
            quoted string.  This means we've got a line consisting of only
            a newline in a quoted string.  We want to make sure this line
            gets added to the history. */
         maybe_add_history (shell_input_line);
       else
         {
           char *hdcs;
           hdcs = history_delimiting_chars (shell_input_line);
           if (hdcs && hdcs[0] == ';')
         maybe_add_history (shell_input_line);
         }
     }
 #endif /* HISTORY */
       if (shell_input_line)
     {
       /* Lines that signify the end of the shell's input should not be
          echoed.  We should not echo lines while parsing command
          substitutions with recursive calls into the parsing engine; those
          should only be echoed once when we read the word.  That is the
          reason for the test against shell_eof_token, which is set to a
          right paren when parsing the contents of command substitutions. */
       if (echo_input_at_read && (shell_input_line[0] ||
                        shell_input_line_terminator != EOF) &&
                      shell_eof_token == 0)
         fprintf (stderr, "%s\n", shell_input_line);
     }
       else
     {
       shell_input_line_size = 0;
       prompt_string_pointer = &current_prompt_string;
       if (SHOULD_PROMPT ())
         prompt_again (0);
       goto restart_read;
     }
       /* Add the newline to the end of this string, iff the string does
      not already end in an EOF character.  */
       if (shell_input_line_terminator != EOF)
     {
       if (shell_input_line_size < SIZE_MAX-3 && (shell_input_line_len+3 > shell_input_line_size))
         shell_input_line = (char *)xrealloc (shell_input_line,
                     1 + (shell_input_line_size += 2));
       /* Don't add a newline to a string that ends with a backslash if we're
          going to be removing quoted newlines, since that will eat the
          backslash.  Add another backslash instead (will be removed by
          word expansion). */
       if (bash_input.type == st_string && expanding_alias() == 0 && last_was_backslash && c == EOF && remove_quoted_newline)
         shell_input_line[shell_input_line_len] = '\\';
       else
         shell_input_line[shell_input_line_len] = '\n';
       shell_input_line[shell_input_line_len + 1] = '\0';
 #if defined (HANDLE_MULTIBYTE)
       /* This is kind of an abstraction violation, but there's no need to
          go through the entire shell_input_line again with a call to
          set_line_mbstate(). */
       EXTEND_SHELL_INPUT_LINE_PROPERTY();
       shell_input_line_property[shell_input_line_len] = 1;
 #endif
     }
     }
 next_alias_char:
   if (shell_input_line_index == 0)
     unquoted_backslash = 0;
   uc = shell_input_line[shell_input_line_index];
   if (uc)
     {
       unquoted_backslash = unquoted_backslash == 0 && uc == '\\';
       shell_input_line_index++;
     }
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   /* If UC is NULL, we have reached the end of the current input string.  If
      pushed_string_list is non-empty, it's time to pop to the previous string
      because we have fully consumed the result of the last alias expansion.
      Do it transparently; just return the next character of the string popped
      to. */
   /* If pushed_string_list != 0 but pushed_string_list->expander == 0 (not
      currently tested) and the flags value is not PSH_SOURCE, we are not
      parsing an alias, we have just saved one (push_string, when called by
      the parse_dparen code) In this case, just go on as well.  The PSH_SOURCE
      case is handled below. */
   /* If we're at the end of an alias expansion add a space to make sure that
      the alias remains marked as being in use while we expand its last word.
      This makes sure that pop_string doesn't mark the alias as not in use
      before the string resulting from the alias expansion is tokenized and
      checked for alias expansion, preventing recursion.  At this point, the
      last character in shell_input_line is the last character of the alias
      expansion.  We test that last character to determine whether or not to
      return the space that will delimit the token and postpone the pop_string.
      This set of conditions duplicates what used to be in mk_alexpansion ()
      below, with the addition that we don't add a space if we're currently
      reading a quoted string or in a shell comment. */
 #ifndef OLD_ALIAS_HACK
   if (uc == 0 && pushed_string_list && pushed_string_list->flags != PSH_SOURCE &&
       pushed_string_list->flags != PSH_DPAREN &&
       (parser_state & PST_COMMENT) == 0 &&
       (parser_state & PST_ENDALIAS) == 0 && /* only once */
       shell_input_line_index > 0 &&
       shellblank (shell_input_line[shell_input_line_index-1]) == 0 &&
       shell_input_line[shell_input_line_index-1] != '\n' &&
       unquoted_backslash == 0 &&
       shellmeta (shell_input_line[shell_input_line_index-1]) == 0 &&
       (current_delimiter (dstack) != '\'' && current_delimiter (dstack) != '"'))
     {
       parser_state |= PST_ENDALIAS;
       /* We need to do this to make sure last_shell_getc_is_singlebyte returns
      true, since we are returning a single-byte space. */
       if (shell_input_line_index == shell_input_line_len && last_shell_getc_is_singlebyte == 0)
     {
 #if 0
       EXTEND_SHELL_INPUT_LINE_PROPERTY();
       shell_input_line_property[shell_input_line_len++] = 1;
       /* extend shell_input_line to accommodate the shell_ungetc that
          read_token_word() will perform, since we're extending the index */
       RESIZE_MALLOCED_BUFFER (shell_input_line, shell_input_line_index, 2, shell_input_line_size, 16);
           shell_input_line[++shell_input_line_index] = '\0';    /* XXX */
 #else
       shell_input_line_property[shell_input_line_index - 1] = 1;
 #endif
     }
       return ' ';   /* END_ALIAS */
     }
 #endif
 pop_alias:
 #endif /* ALIAS || DPAREN_ARITHMETIC */
   /* This case works for PSH_DPAREN as well as the shell_ungets() case that uses
      push_string */
   if (uc == 0 && pushed_string_list && pushed_string_list->flags != PSH_SOURCE)
     {
       parser_state &= ~PST_ENDALIAS;
       pop_string ();
       uc = shell_input_line[shell_input_line_index];
       if (uc)
     shell_input_line_index++;
     }
   if MBTEST(uc == '\\' && remove_quoted_newline && shell_input_line[shell_input_line_index] == '\n')
     {
     if (SHOULD_PROMPT ())
       prompt_again (0);
     line_number++;
     /* What do we do here if we're expanding an alias whose definition
        includes an escaped newline?  If that's the last character in the
        alias expansion, we just pop the pushed string list (recall that
        we inhibit the appending of a space if newline is the last
        character).  If it's not the last character, we need to consume the
        quoted newline and move to the next character in the expansion. */
 #if defined (ALIAS)
     if (expanding_alias () && shell_input_line[shell_input_line_index+1] == '\0')
       {
         uc = 0;
         goto pop_alias;
       }
     else if (expanding_alias () && shell_input_line[shell_input_line_index+1] != '\0')
       {
         shell_input_line_index++;   /* skip newline */
         goto next_alias_char;   /* and get next character */
       }
     else
 #endif
       goto restart_read;
     }
   if (uc == 0 && shell_input_line_terminator == EOF)
     return ((shell_input_line_index != 0) ? '\n' : EOF);
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   /* We already know that we are not parsing an alias expansion because of the
      check for expanding_alias() above.  This knows how parse_and_execute
      handles switching to st_string input while an alias is being expanded,
      hence the check for pushed_string_list without pushed_string_list->expander
      and the check for PSH_SOURCE as pushed_string_list->flags.
      parse_and_execute and parse_string both change the input type to st_string
      and place the string to be parsed and executed into location.string, so
      we should not stop reading that until the pointer is '\0'.
      The check for shell_input_line_terminator may be superfluous.
      This solves the problem of `.' inside a multi-line alias with embedded
      newlines executing things out of order. */
   if (uc == 0 && bash_input.type == st_string && *bash_input.location.string &&
       pushed_string_list && pushed_string_list->flags == PSH_SOURCE &&
       shell_input_line_terminator == 0)
     {
       shell_input_line_index = 0;
       goto restart_read;
     }
 #endif
   return (uc);
 }
References _, bash_input, c, cleanup_dead_jobs(), clearerr(), current_command_line_count, current_delimiter, current_prompt_string, echo_input_at_read, EOF, eol_ungetc_lookahead, expanding_alias, EXTEND_SHELL_INPUT_LINE_PROPERTY, string_saver::flags, fprintf(), free(), get_new_window_size(), history_quoting_state, i, interactive_shell, internal_warning(), last_shell_getc_is_singlebyte, line_number, BASH_INPUT::location, MBTEST, n, no_line_editing, notify_and_cleanup(), NULL, parser_state, pop_string(), print_prompt(), prompt_again(), prompt_string_pointer, PSH_DPAREN, PSH_SOURCE, PST_COMMENT, PST_ENDALIAS, pushed_string_list, QUIT, remember_on_history, RESIZE_MALLOCED_BUFFER, set_line_mbstate, shell_eof_token, shell_input_line, shell_input_line_index, shell_input_line_len, shell_input_line_size, shell_input_line_terminator, shellblank, shellmeta, SHOULD_PROMPT, sigwinch_received, SIZE_MAX, st_stream, st_string, stderr, stdin, INPUT_STREAM::string, strlen(), BASH_INPUT::type, unquoted_backslash, xrealloc, and yy_getc().
Referenced by discard_until(), parse_comsub(), parse_matched_pair(), read_token(), and read_token_word().
shell_ungetc()
static void shell_ungetc (int c) static
Definition at line 5031 of file y.tab.c.
 {
   if (shell_input_line && shell_input_line_index)
     shell_input_line[--shell_input_line_index] = c;
   else
     eol_ungetc_lookahead = c;
 }
References c, eol_ungetc_lookahead, shell_input_line, and shell_input_line_index.
Referenced by discard_until(), parse_comsub(), read_token(), and read_token_word().
shell_ungets()
void shell_ungets (char * s)
Definition at line 5042 of file y.tab.c.
 {
   size_t slen, chars_left;
   slen = strlen (s);
   if (shell_input_line[shell_input_line_index] == '\0')
     {
       /* Easy, just overwrite shell_input_line. This is preferred because it
      saves on set_line_mbstate () and other overhead like push_string */
       if (shell_input_line_size <= slen)
     RESIZE_MALLOCED_BUFFER (shell_input_line, shell_input_line_index, slen + 1, shell_input_line_size, 64);
       strcpy (shell_input_line, s);
       shell_input_line_index = 0;
       shell_input_line_len = slen;
       shell_input_line_terminator = 0;
     }
   else if (shell_input_line_index >= slen)
     {
       /* Just as easy, just back up shell_input_line_index, but it means we
      will re-process some characters in set_line_mbstate(). Need to
      watch pushing back newlines here. */
       while (slen > 0)
         shell_input_line[--shell_input_line_index] = s[--slen];
     }
   else if (s[slen - 1] == '\n')
     {
       push_string (savestring (s), 0, (alias_t *)NULL);
       /* push_string does set_line_mbstate () */
       return;
     }
   else
     {
       /* Harder case: pushing back input string that's longer than what we've
      consumed from shell_input_line so far. */
       INTERNAL_DEBUG (("shell_ungets: not at end of shell_input_line"));
       chars_left = shell_input_line_len - shell_input_line_index;
       if (shell_input_line_size <= (slen + chars_left))
     RESIZE_MALLOCED_BUFFER (shell_input_line, shell_input_line_index, chars_left + slen + 1, shell_input_line_size, 64);
       memmove (shell_input_line + slen, shell_input_line + shell_input_line_index, shell_input_line_len - shell_input_line_index);
       strcpy (shell_input_line, s);
       shell_input_line_index = 0;
       shell_input_line_len = strlen (shell_input_line); /* chars_left + slen? */
     }
 #if defined (HANDLE_MULTIBYTE)
   set_line_mbstate ();  /* XXX */
 #endif
 }
References INTERNAL_DEBUG, memmove, NULL, push_string(), RESIZE_MALLOCED_BUFFER, s, savestring(), set_line_mbstate, shell_input_line, shell_input_line_index, shell_input_line_len, shell_input_line_size, shell_input_line_terminator, strcpy, and strlen().
Referenced by make_here_document().
special_case_tokens()
static int special_case_tokens (char * tokstr) static
Definition at line 5485 of file y.tab.c.
 {
   /* Posix grammar rule 6 */
   if ((last_read_token == WORD) &&
 #if defined (SELECT_COMMAND)
       ((token_before_that == FOR) || (token_before_that == CASE) || (token_before_that == SELECT)) &&
 #else
       ((token_before_that == FOR) || (token_before_that == CASE)) &&
 #endif
       (tokstr[0] == 'i' && tokstr[1] == 'n' && tokstr[2] == 0))
     {
       if (token_before_that == CASE)
     {
       parser_state |= PST_CASEPAT;
       esacs_needed_count++;
     }
       if (expecting_in_token)
     expecting_in_token--;
       return (IN);
     }
   /* XXX - leaving above code intact for now, but it should eventually be
      removed in favor of this clause. */
   /* Posix grammar rule 6 */
   if (expecting_in_token && (last_read_token == WORD || last_read_token == '\n') &&
       (tokstr[0] == 'i' && tokstr[1] == 'n' && tokstr[2] == 0))
     {
       if (parser_state & PST_CASESTMT)
     {
       parser_state |= PST_CASEPAT;
       esacs_needed_count++;
     }
       expecting_in_token--;
       return (IN);
     }
   /* Posix grammar rule 6, third word in FOR: for i; do command-list; done */
   else if (expecting_in_token && (last_read_token == '\n' || last_read_token == ';') &&
     (tokstr[0] == 'd' && tokstr[1] == 'o' && tokstr[2] == '\0'))
     {
       expecting_in_token--;
       return (DO);
     }
   /* for i do; command-list; done */
   if (last_read_token == WORD &&
 #if defined (SELECT_COMMAND)
       (token_before_that == FOR || token_before_that == SELECT) &&
 #else
       (token_before_that == FOR) &&
 #endif
       (tokstr[0] == 'd' && tokstr[1] == 'o' && tokstr[2] == '\0'))
     {
       if (expecting_in_token)
     expecting_in_token--;
       return (DO);
     }
   /* Ditto for ESAC in the CASE case.
      Specifically, this handles "case word in esac", which is a legal
      construct, certainly because someone will pass an empty arg to the
      case construct, and we don't want it to barf.  Of course, we should
      insist that the case construct has at least one pattern in it, but
      the designers disagree. */
   if (esacs_needed_count)
     {
       if (last_read_token == IN && STREQ (tokstr, "esac"))
     {
       esacs_needed_count--;
       parser_state &= ~PST_CASEPAT;
       return (ESAC);
     }
     }
   /* The start of a shell function definition. */
   if (parser_state & PST_ALLOWOPNBRC)
     {
       parser_state &= ~PST_ALLOWOPNBRC;
       if (tokstr[0] == '{' && tokstr[1] == '\0')        /* } */
     {
       open_brace_count++;
       function_bstart = line_number;
       return ('{');                 /* } */
     }
     }
   /* We allow a `do' after a for ((...)) without an intervening
      list_terminator */
   if (last_read_token == ARITH_FOR_EXPRS && tokstr[0] == 'd' && tokstr[1] == 'o' && !tokstr[2])
     return (DO);
   if (last_read_token == ARITH_FOR_EXPRS && tokstr[0] == '{' && tokstr[1] == '\0')  /* } */
     {
       open_brace_count++;
       return ('{');         /* } */
     }
   if (open_brace_count && reserved_word_acceptable (last_read_token) && tokstr[0] == '}' && !tokstr[1])
     {
       open_brace_count--;       /* { */
       return ('}');
     }
 #if defined (COMMAND_TIMING)
   /* Handle -p after `time'. */
   if (last_read_token == TIME && tokstr[0] == '-' && tokstr[1] == 'p' && !tokstr[2])
     return (TIMEOPT);
   /* Handle -- after `time'. */
   if (last_read_token == TIME && tokstr[0] == '-' && tokstr[1] == '-' && !tokstr[2])
     return (TIMEIGN);
   /* Handle -- after `time -p'. */
   if (last_read_token == TIMEOPT && tokstr[0] == '-' && tokstr[1] == '-' && !tokstr[2])
     return (TIMEIGN);
 #endif
 #if defined (COND_COMMAND) /* [[ */
   if ((parser_state & PST_CONDEXPR) && tokstr[0] == ']' && tokstr[1] == ']' && tokstr[2] == '\0')
     return (COND_END);
 #endif
   return (-1);
 }
References ARITH_FOR_EXPRS, CASE, COND_END, DO, ESAC, esacs_needed_count, expecting_in_token, FOR, function_bstart, IN, last_read_token, line_number, open_brace_count, parser_state, PST_ALLOWOPNBRC, PST_CASEPAT, PST_CASESTMT, PST_CONDEXPR, reserved_word_acceptable(), SELECT, STREQ, TIME, TIMEIGN, TIMEOPT, token_before_that, and tokstr.
Referenced by read_token_word().
stream_on_stack()
int stream_on_stack (enum stream_type type)
Definition at line 4131 of file y.tab.c.
 {
   register STREAM_SAVER *s;
   for (s = stream_list; s; s = s->next)
     if (s->bash_input.type == type)
       return 1;
   return 0;
 }
References s, stream_list, and type.
time_command_acceptable()
static int time_command_acceptable () static
Definition at line 5407 of file y.tab.c.
 {
 #if defined (COMMAND_TIMING)
   int i;
   if (posixly_correct && shell_compatibility_level > 41)
     {
       /* Quick check of the rest of the line to find the next token.  If it
      begins with a `-', Posix says to not return `time' as the token.
      This was interp 267. */
       i = shell_input_line_index;
       while (i < shell_input_line_len && (shell_input_line[i] == ' ' || shell_input_line[i] == '\t'))
         i++;
       if (shell_input_line[i] == '-')
     return 0;
     }
   switch (last_read_token)
     {
     case 0:
     case ';':
     case '\n':
       if (token_before_that == '|')
     return (0);
       /* FALLTHROUGH */
     case AND_AND:
     case OR_OR:
     case '&':
     case WHILE:
     case DO:
     case UNTIL:
     case IF:
     case THEN:
     case ELIF:
     case ELSE:
     case '{':       /* } */
     case '(':       /* )( */
     case ')':       /* only valid in case statement */
     case BANG:      /* ! time pipeline */
     case TIME:      /* time time pipeline */
     case TIMEOPT:   /* time -p time pipeline */
     case TIMEIGN:   /* time -p -- ... */
       return 1;
     default:
       return 0;
     }
 #else
   return 0;
 #endif /* COMMAND_TIMING */
 }
References AND_AND, BANG, DO, ELIF, ELSE, i, IF, last_read_token, OR_OR, posixly_correct, shell_compatibility_level, shell_input_line, shell_input_line_index, shell_input_line_len, THEN, TIME, TIMEIGN, TIMEOPT, token_before_that, UNTIL, and WHILE.
with_input_from_stdin()
void with_input_from_stdin ()
Definition at line 3913 of file y.tab.c.
 {
   with_input_from_stream (stdin, "stdin");
 }
References stdin, and with_input_from_stream().
Referenced by set_bash_input().
with_input_from_stream()
void with_input_from_stream (FILE * stream, const char * name)
Definition at line 4025 of file y.tab.c.
 {
   INPUT_STREAM location;
   location.file = stream;
   init_yy_io (yy_stream_get, yy_stream_unget, st_stream, name, location);
 }
References INPUT_STREAM::file, init_yy_io(), st_stream, yy_stream_get(), and yy_stream_unget().
Referenced by set_bash_input(), and with_input_from_stdin().
with_input_from_string()
void with_input_from_string (char * string, const char * name)
Definition at line 3953 of file y.tab.c.
 {
   INPUT_STREAM location;
   location.string = string;
   init_yy_io (yy_string_get, yy_string_unget, st_string, name, location);
 }
References init_yy_io(), st_string, INPUT_STREAM::string, string, yy_string_get(), and yy_string_unget().
Referenced by main(), parse_and_execute(), parse_string(), and parse_string_to_word_list().
xparse_dolparen()
char* xparse_dolparen (char * base, char * string, int * indp, int flags)
Definition at line 6541 of file y.tab.c.
 {
   sh_parser_state_t ps;
   sh_input_line_state_t ls;
   int orig_ind, nc, sflags, start_lineno, local_extglob;
   char *ret, *ep, *ostring;
 /*debug_parser(1);*/
   orig_ind = *indp;
   ostring = string;
   start_lineno = line_number;
   if (*string == 0)
     {
       if (flags & SX_NOALLOC)
     return (char *)NULL;
       ret = xmalloc (1);
       ret[0] = '\0';
       return ret;
     }
 /*itrace("xparse_dolparen: size = %d shell_input_line = `%s' string=`%s'", shell_input_line_size, shell_input_line, string);*/
   sflags = SEVAL_NONINT|SEVAL_NOHIST|SEVAL_NOFREE;
   if (flags & SX_NOLONGJMP)
     sflags |= SEVAL_NOLONGJMP;
   save_parser_state (&ps);
   save_input_line_state (&ls);
 #if defined (ALIAS) || defined (DPAREN_ARITHMETIC)
   pushed_string_list = (STRING_SAVER *)NULL;
 #endif
   /*(*/
   parser_state |= PST_CMDSUBST|PST_EOFTOKEN;    /* allow instant ')' */ /*(*/
   shell_eof_token = ')';
   if (flags & SX_COMPLETE)
     parser_state |= PST_NOERROR;
   /* Don't expand aliases on this pass at all. Either parse_comsub() does it
      at parse time, in which case this string already has aliases expanded,
      or command_substitute() does it in the child process executing the
      command substitution and we want to defer it completely until then. The
      old value will be restored by restore_parser_state(). */
   expand_aliases = 0;
 #if defined (EXTENDED_GLOB)
   local_extglob = extended_glob;
 #endif
   token_to_read = DOLPAREN;         /* let's trick the parser */
   nc = parse_string (string, "command substitution", sflags, (COMMAND **)NULL, &ep);
   /* Should we save and restore the bison/yacc lookahead token (yychar) here?
      Or only if it's not YYEMPTY? */
   if (current_token == shell_eof_token)
     yyclearin;      /* might want to clear lookahead token unconditionally */
   reset_parser ();  /* resets extended_glob too */
   /* reset_parser() clears shell_input_line and associated variables, including
      parser_state, so we want to reset things, then restore what we need. */
   restore_input_line_state (&ls);
   restore_parser_state (&ps);
 #if defined (EXTENDED_GLOB)
   extended_glob = local_extglob;
 #endif
   token_to_read = 0;
   /* If parse_string returns < 0, we need to jump to top level with the
      negative of the return value. We abandon the rest of this input line
      first */
   if (nc < 0)
     {
       clear_shell_input_line ();    /* XXX */
       if (bash_input.type != st_string) /* paranoia */
     parser_state &= ~(PST_CMDSUBST|PST_EOFTOKEN);
       if ((flags & SX_NOLONGJMP) == 0)
     jump_to_top_level (-nc);    /* XXX */
     }
   /* Need to find how many characters parse_string() consumed, update
      *indp, if flags != 0, copy the portion of the string parsed into RET
      and return it.  If flags & 1 (SX_NOALLOC) we can return NULL. */
   /*(*/
   if (ep[-1] != ')')
     {
 #if 0
       if (ep[-1] != '\n')
     itrace("xparse_dolparen:%d: ep[-1] != RPAREN (%d), ep = `%s'", line_number, ep[-1], ep);
 #endif
       while (ep > ostring && ep[-1] == '\n') ep--;
     }
   nc = ep - ostring;
   *indp = ep - base - 1;
   /*((*/
 #if 0
   if (base[*indp] != ')')
     itrace("xparse_dolparen:%d: base[%d] != RPAREN (%d), base = `%s'", line_number, *indp, base[*indp], base);
   if (*indp < orig_ind)
     itrace("xparse_dolparen:%d: *indp (%d) < orig_ind (%d), orig_string = `%s'", line_number, *indp, orig_ind, ostring);
 #endif
   if (base[*indp] != ')' && (flags & SX_NOLONGJMP) == 0)
     {
       /*(*/
       if ((flags & SX_NOERROR) == 0)
     parser_error (start_lineno, _("unexpected EOF while looking for matching `%c'"), ')');
       jump_to_top_level (DISCARD);
     }
   if (flags & SX_NOALLOC)
     return (char *)NULL;
   if (nc == 0)
     {
       ret = xmalloc (1);
       ret[0] = '\0';
     }
   else
     ret = substring (ostring, 0, nc - 1);
   return ret;
 }
References _, base, bash_input, clear_shell_input_line(), current_token, DISCARD, DOLPAREN, expand_aliases, extended_glob, flags, jump_to_top_level(), line_number, NULL, parse_string(), parser_error(), parser_state, PST_CMDSUBST, PST_EOFTOKEN, PST_NOERROR, pushed_string_list, reset_parser(), restore_input_line_state(), restore_parser_state(), save_input_line_state(), save_parser_state(), SEVAL_NOFREE, SEVAL_NOHIST, SEVAL_NOLONGJMP, SEVAL_NONINT, shell_eof_token, st_string, string, substring(), SX_COMPLETE, SX_NOALLOC, SX_NOERROR, SX_NOLONGJMP, token_to_read, BASH_INPUT::type, xmalloc, and yyclearin.
Referenced by extract_command_subst().
yy_getc()
static int yy_getc () static
Definition at line 3771 of file y.tab.c.
 {
   return (*(bash_input.getter)) ();
 }
References bash_input, and BASH_INPUT::getter.
Referenced by read_a_line(), and shell_getc().
yy_input_name()
char* yy_input_name ()
Definition at line 3764 of file y.tab.c.
 {
   return (bash_input.name ? bash_input.name : "stdin");
 }
References bash_input, and BASH_INPUT::name.
Referenced by parser_error().
yy_stream_get()
static int yy_stream_get () static
Definition at line 4003 of file y.tab.c.
 {
   int result;
   result = EOF;
   if (bash_input.location.file)
     {
       /* XXX - don't need terminate_immediately; getc_with_restart checks
      for terminating signals itself if read returns < 0 */
       result = getc_with_restart (bash_input.location.file);
     }
   return (result);
 }
References bash_input, EOF, INPUT_STREAM::file, getc_with_restart(), and BASH_INPUT::location.
Referenced by with_input_from_stream().
yy_stream_unget()
static int yy_stream_unget (int c) static
Definition at line 4018 of file y.tab.c.
 {
   return (ungetc_with_restart (c, bash_input.location.file));
 }
References bash_input, c, INPUT_STREAM::file, BASH_INPUT::location, and ungetc_with_restart().
Referenced by with_input_from_stream().
yy_string_get()
static int yy_string_get () static
Definition at line 3926 of file y.tab.c.
 {
   register char *string;
   register unsigned char c;
   string = bash_input.location.string;
   /* If the string doesn't exist, or is empty, EOF found. */
   if (string && *string)
     {
       c = *string++;
       bash_input.location.string = string;
       return (c);
     }
   else
     return (EOF);
 }
References bash_input, c, EOF, BASH_INPUT::location, INPUT_STREAM::string, and string.
Referenced by with_input_from_string().
yy_string_unget()
static int yy_string_unget (int c) static
Definition at line 3945 of file y.tab.c.
 {
   *(--bash_input.location.string) = c;
   return (c);
 }
References bash_input, c, BASH_INPUT::location, and INPUT_STREAM::string.
Referenced by with_input_from_string().
yy_ungetc()
static int yy_ungetc (int c) static
Definition at line 3779 of file y.tab.c.
 {
   return (*(bash_input.ungetter)) (c);
 }
References bash_input, c, and BASH_INPUT::ungetter.
Referenced by read_a_line().
yydestruct()
static void yydestruct (const char * yymsg, yysymbol_kind_t yykind, YYSTYPE * yyvaluep) static
Definition at line 1670 of file y.tab.c.
 {
   YY_USE (yyvaluep);
   if (!yymsg)
     yymsg = "Deleting";
   YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   YY_USE (yykind);
   YY_IGNORE_MAYBE_UNINITIALIZED_END
 }
References YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_SYMBOL_PRINT, and YY_USE.
Referenced by yyparse().
yyerror()
int yyerror (char * msg) const
Definition at line 8415 of file y.tab.c.
 {
   if ((parser_state & PST_NOERROR) == 0)
     report_syntax_error ((char *)NULL);
   reset_parser ();
   return (0);
 }
References NULL, parser_state, PST_NOERROR, report_syntax_error(), and reset_parser().
Referenced by parse_compound_assignment(), parse_string_to_word_list(), and yyparse().
yylex()
static int yylex () static
Definition at line 5178 of file y.tab.c.
 {
   if (interactive && (current_token == 0 || current_token == '\n'))
     {
       /* Before we print a prompt, we might have to check mailboxes.
      We do this only if it is time to do so. Notice that only here
      is the mail alarm reset; nothing takes place in check_mail ()
      except the checking of mail.  Please don't change this. */
       if (prompt_is_ps1 && parse_and_execute_level == 0 && time_to_check_mail ())
     {
       check_mail ();
       reset_mail_timer ();
     }
       /* Avoid printing a prompt if we're not going to read anything, e.g.
      after resetting the parser with read_token (RESET). */
       if (token_to_read == 0 && SHOULD_PROMPT ())
     prompt_again (0);
     }
   two_tokens_ago = token_before_that;
   token_before_that = last_read_token;
   last_read_token = current_token;
   current_token = read_token (READ);
   if ((parser_state & PST_EOFTOKEN) && current_token == shell_eof_token)
     {
       /* placeholder for any special handling. */
       return (current_token);
     }
   if (current_token < 0)
 #if defined (YYERRCODE) && !defined (YYUNDEF)
     current_token = YYERRCODE;
 #else
     current_token = YYerror;
 #endif
   return (current_token);
 }
References check_mail(), current_token, interactive, last_read_token, parse_and_execute_level, parser_state, prompt_again(), prompt_is_ps1, PST_EOFTOKEN, READ, read_token(), reset_mail_timer(), shell_eof_token, SHOULD_PROMPT, time_to_check_mail(), token_before_that, token_to_read, two_tokens_ago, YYERRCODE, and YYerror.
Referenced by yyparse().
yyparse()
int yyparse (void)
Definition at line 1700 of file y.tab.c.
 {
     yy_state_fast_t yystate = 0;
     /* Number of tokens to shift before error messages enabled.  */
     int yyerrstatus = 0;
     /* Refer to the stacks through separate pointers, to allow yyoverflow
        to reallocate them elsewhere.  */
     /* Their size.  */
     YYPTRDIFF_T yystacksize = YYINITDEPTH;
     /* The state stack: array, bottom, top.  */
     yy_state_t yyssa[YYINITDEPTH];
     yy_state_t *yyss = yyssa;
     yy_state_t *yyssp = yyss;
     /* The semantic value stack: array, bottom, top.  */
     YYSTYPE yyvsa[YYINITDEPTH];
     YYSTYPE *yyvs = yyvsa;
     YYSTYPE *yyvsp = yyvs;
   int yyn;
   /* The return value of yyparse.  */
   int yyresult;
   /* Lookahead symbol kind.  */
   yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yychar = YYEMPTY; /* Cause a token to be read.  */
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
 yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
 /*--------------------------------------------------------------------.
 | yysetstate -- set current state (the top of the stack) to yystate.  |
 `--------------------------------------------------------------------*/
 yysetstate:
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
   YY_IGNORE_USELESS_CAST_BEGIN
   *yyssp = YY_CAST (yy_state_t, yystate);
   YY_IGNORE_USELESS_CAST_END
   YY_STACK_PRINT (yyss, yyssp);
   if (yyss + yystacksize - 1 <= yyssp)
 #if !defined yyoverflow && !defined YYSTACK_RELOCATE
     YYNOMEM;
 #else
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYPTRDIFF_T yysize = yyssp - yyss + 1;
 # if defined yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         yy_state_t *yyss1 = yyss;
         YYSTYPE *yyvs1 = yyvs;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow (YY_("memory exhausted"),
                     &yyss1, yysize * YYSIZEOF (*yyssp),
                     &yyvs1, yysize * YYSIZEOF (*yyvsp),
                     &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 # else /* defined YYSTACK_RELOCATE */
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         YYNOMEM;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yy_state_t *yyss1 = yyss;
         union yyalloc *yyptr =
           YY_CAST (union yyalloc *,
                    YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
         if (! yyptr)
           YYNOMEM;
         YYSTACK_RELOCATE (yyss_alloc, yyss);
         YYSTACK_RELOCATE (yyvs_alloc, yyvs);
 #  undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE (yyss1);
       }
 # endif
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YY_IGNORE_USELESS_CAST_BEGIN
       YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                   YY_CAST (long, yystacksize)));
       YY_IGNORE_USELESS_CAST_END
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
 #endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yypact_value_is_default (yyn))
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token\n"));
       yychar = yylex ();
     }
   if (yychar <= YYEOF)
     {
       yychar = YYEOF;
       yytoken = YYSYMBOL_YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else if (yychar == YYerror)
     {
       /* The scanner already issued an error message, process directly
          to error recovery.  But do not keep the error token as
          lookahead, it is too special and may lead us to an endless
          loop in error recovery. */
       yychar = YYUNDEF;
       yytoken = YYSYMBOL_YYerror;
       goto yyerrlab1;
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yytable_value_is_error (yyn))
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   yystate = yyn;
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      '$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
   case 2: /* inputunit: simple_list simple_list_terminator  */
 #line 396 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Case of regular command.  Discard the error
                  safety net,and return the command just parsed. */
               global_command = (yyvsp[-1].command);
               eof_encountered = 0;
               /* discard_parser_constructs (0); */
               if (parser_state & PST_CMDSUBST)
                 parser_state |= PST_EOFTOKEN;
               YYACCEPT;
             }
 #line 1954 "y.tab.c"
     break;
   case 3: /* inputunit: comsub  */
 #line 407 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* This is special; look at the production and how
                  parse_comsub sets token_to_read */
               global_command = (yyvsp[0].command);
               eof_encountered = 0;
               YYACCEPT;
             }
 #line 1966 "y.tab.c"
     break;
   case 4: /* inputunit: '\n'  */
 #line 415 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Case of regular command, but not a very
                  interesting one.  Return a NULL command. */
               global_command = (COMMAND *)NULL;
               if (parser_state & PST_CMDSUBST)
                 parser_state |= PST_EOFTOKEN;
               YYACCEPT;
             }
 #line 1979 "y.tab.c"
     break;
   case 5: /* inputunit: error '\n'  */
 #line 424 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Error during parsing.  Return NULL command. */
               global_command = (COMMAND *)NULL;
               eof_encountered = 0;
               /* discard_parser_constructs (1); */
               if (interactive && parse_and_execute_level == 0)
                 {
                   YYACCEPT;
                 }
               else
                 {
                   YYABORT;
                 }
             }
 #line 1998 "y.tab.c"
     break;
   case 6: /* inputunit: error yacc_EOF  */
 #line 439 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* EOF after an error.  Do ignoreeof or not.  Really
                  only interesting in non-interactive shells */
               global_command = (COMMAND *)NULL;
               if (last_command_exit_value == 0)
                 last_command_exit_value = EX_BADUSAGE;  /* force error return */
               if (interactive && parse_and_execute_level == 0)
                 {
                   handle_eof_input_unit ();
                   YYACCEPT;
                 }
               else
                 {
                   YYABORT;
                 }
             }
 #line 2019 "y.tab.c"
     break;
   case 7: /* inputunit: yacc_EOF  */
 #line 456 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Case of EOF seen by itself.  Do ignoreeof or
                  not. */
               global_command = (COMMAND *)NULL;
               handle_eof_input_unit ();
               YYACCEPT;
             }
 #line 2031 "y.tab.c"
     break;
   case 8: /* word_list: WORD  */
 #line 466 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (WORD_LIST *)NULL); }
 #line 2037 "y.tab.c"
     break;
   case 9: /* word_list: word_list WORD  */
 #line 468 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (yyvsp[-1].word_list)); }
 #line 2043 "y.tab.c"
     break;
   case 10: /* redirection: '>' WORD  */
 #line 472 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_direction, redir, 0);
             }
 #line 2053 "y.tab.c"
     break;
   case 11: /* redirection: '<' WORD  */
 #line 478 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_direction, redir, 0);
             }
 #line 2063 "y.tab.c"
     break;
   case 12: /* redirection: NUMBER '>' WORD  */
 #line 484 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_direction, redir, 0);
             }
 #line 2073 "y.tab.c"
     break;
   case 13: /* redirection: NUMBER '<' WORD  */
 #line 490 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_direction, redir, 0);
             }
 #line 2083 "y.tab.c"
     break;
   case 14: /* redirection: REDIR_WORD '>' WORD  */
 #line 496 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_direction, redir, REDIR_VARASSIGN);
             }
 #line 2093 "y.tab.c"
     break;
   case 15: /* redirection: REDIR_WORD '<' WORD  */
 #line 502 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_direction, redir, REDIR_VARASSIGN);
             }
 #line 2103 "y.tab.c"
     break;
   case 16: /* redirection: GREATER_GREATER WORD  */
 #line 508 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_appending_to, redir, 0);
             }
 #line 2113 "y.tab.c"
     break;
   case 17: /* redirection: NUMBER GREATER_GREATER WORD  */
 #line 514 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_appending_to, redir, 0);
             }
 #line 2123 "y.tab.c"
     break;
   case 18: /* redirection: REDIR_WORD GREATER_GREATER WORD  */
 #line 520 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_appending_to, redir, REDIR_VARASSIGN);
             }
 #line 2133 "y.tab.c"
     break;
   case 19: /* redirection: GREATER_BAR WORD  */
 #line 526 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_force, redir, 0);
             }
 #line 2143 "y.tab.c"
     break;
   case 20: /* redirection: NUMBER GREATER_BAR WORD  */
 #line 532 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_force, redir, 0);
             }
 #line 2153 "y.tab.c"
     break;
   case 21: /* redirection: REDIR_WORD GREATER_BAR WORD  */
 #line 538 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_output_force, redir, REDIR_VARASSIGN);
             }
 #line 2163 "y.tab.c"
     break;
   case 22: /* redirection: LESS_GREATER WORD  */
 #line 544 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_output, redir, 0);
             }
 #line 2173 "y.tab.c"
     break;
   case 23: /* redirection: NUMBER LESS_GREATER WORD  */
 #line 550 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_output, redir, 0);
             }
 #line 2183 "y.tab.c"
     break;
   case 24: /* redirection: REDIR_WORD LESS_GREATER WORD  */
 #line 556 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_input_output, redir, REDIR_VARASSIGN);
             }
 #line 2193 "y.tab.c"
     break;
   case 25: /* redirection: LESS_LESS WORD  */
 #line 562 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2204 "y.tab.c"
     break;
   case 26: /* redirection: NUMBER LESS_LESS WORD  */
 #line 569 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2215 "y.tab.c"
     break;
   case 27: /* redirection: REDIR_WORD LESS_LESS WORD  */
 #line 576 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_until, redir, REDIR_VARASSIGN);
               push_heredoc ((yyval.redirect));
             }
 #line 2226 "y.tab.c"
     break;
   case 28: /* redirection: LESS_LESS_MINUS WORD  */
 #line 583 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_deblank_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2237 "y.tab.c"
     break;
   case 29: /* redirection: NUMBER LESS_LESS_MINUS WORD  */
 #line 590 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_deblank_reading_until, redir, 0);
               push_heredoc ((yyval.redirect));
             }
 #line 2248 "y.tab.c"
     break;
   case 30: /* redirection: REDIR_WORD LESS_LESS_MINUS WORD  */
 #line 597 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_deblank_reading_until, redir, REDIR_VARASSIGN);
               push_heredoc ((yyval.redirect));
             }
 #line 2259 "y.tab.c"
     break;
   case 31: /* redirection: LESS_LESS_LESS WORD  */
 #line 604 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_string, redir, 0);
             }
 #line 2269 "y.tab.c"
     break;
   case 32: /* redirection: NUMBER LESS_LESS_LESS WORD  */
 #line 610 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_string, redir, 0);
             }
 #line 2279 "y.tab.c"
     break;
   case 33: /* redirection: REDIR_WORD LESS_LESS_LESS WORD  */
 #line 616 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_reading_string, redir, REDIR_VARASSIGN);
             }
 #line 2289 "y.tab.c"
     break;
   case 34: /* redirection: LESS_AND NUMBER  */
 #line 622 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_input, redir, 0);
             }
 #line 2299 "y.tab.c"
     break;
   case 35: /* redirection: NUMBER LESS_AND NUMBER  */
 #line 628 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_input, redir, 0);
             }
 #line 2309 "y.tab.c"
     break;
   case 36: /* redirection: REDIR_WORD LESS_AND NUMBER  */
 #line 634 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_input, redir, REDIR_VARASSIGN);
             }
 #line 2319 "y.tab.c"
     break;
   case 37: /* redirection: GREATER_AND NUMBER  */
 #line 640 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_output, redir, 0);
             }
 #line 2329 "y.tab.c"
     break;
   case 38: /* redirection: NUMBER GREATER_AND NUMBER  */
 #line 646 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_output, redir, 0);
             }
 #line 2339 "y.tab.c"
     break;
   case 39: /* redirection: REDIR_WORD GREATER_AND NUMBER  */
 #line 652 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = (yyvsp[0].number);
               (yyval.redirect) = make_redirection (source, r_duplicating_output, redir, REDIR_VARASSIGN);
             }
 #line 2349 "y.tab.c"
     break;
   case 40: /* redirection: LESS_AND WORD  */
 #line 658 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_input_word, redir, 0);
             }
 #line 2359 "y.tab.c"
     break;
   case 41: /* redirection: NUMBER LESS_AND WORD  */
 #line 664 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_input_word, redir, 0);
             }
 #line 2369 "y.tab.c"
     break;
   case 42: /* redirection: REDIR_WORD LESS_AND WORD  */
 #line 670 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_input_word, redir, REDIR_VARASSIGN);
             }
 #line 2379 "y.tab.c"
     break;
   case 43: /* redirection: GREATER_AND WORD  */
 #line 676 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_output_word, redir, 0);
             }
 #line 2389 "y.tab.c"
     break;
   case 44: /* redirection: NUMBER GREATER_AND WORD  */
 #line 682 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_output_word, redir, 0);
             }
 #line 2399 "y.tab.c"
     break;
   case 45: /* redirection: REDIR_WORD GREATER_AND WORD  */
 #line 688 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_duplicating_output_word, redir, REDIR_VARASSIGN);
             }
 #line 2409 "y.tab.c"
     break;
   case 46: /* redirection: GREATER_AND '-'  */
 #line 694 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2419 "y.tab.c"
     break;
   case 47: /* redirection: NUMBER GREATER_AND '-'  */
 #line 700 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2429 "y.tab.c"
     break;
   case 48: /* redirection: REDIR_WORD GREATER_AND '-'  */
 #line 706 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, REDIR_VARASSIGN);
             }
 #line 2439 "y.tab.c"
     break;
   case 49: /* redirection: LESS_AND '-'  */
 #line 712 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 0;
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2449 "y.tab.c"
     break;
   case 50: /* redirection: NUMBER LESS_AND '-'  */
 #line 718 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = (yyvsp[-2].number);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, 0);
             }
 #line 2459 "y.tab.c"
     break;
   case 51: /* redirection: REDIR_WORD LESS_AND '-'  */
 #line 724 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.filename = (yyvsp[-2].word);
               redir.dest = 0;
               (yyval.redirect) = make_redirection (source, r_close_this, redir, REDIR_VARASSIGN);
             }
 #line 2469 "y.tab.c"
     break;
   case 52: /* redirection: AND_GREATER WORD  */
 #line 730 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_err_and_out, redir, 0);
             }
 #line 2479 "y.tab.c"
     break;
   case 53: /* redirection: AND_GREATER_GREATER WORD  */
 #line 736 "/usr/local/src/chet/src/bash/src/parse.y"
{
               source.dest = 1;
               redir.filename = (yyvsp[0].word);
               (yyval.redirect) = make_redirection (source, r_append_err_and_out, redir, 0);
             }
 #line 2489 "y.tab.c"
     break;
   case 54: /* simple_command_element: WORD  */
 #line 744 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.element).word = (yyvsp[0].word); (yyval.element).redirect = 0; }
 #line 2495 "y.tab.c"
     break;
   case 55: /* simple_command_element: ASSIGNMENT_WORD  */
 #line 746 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.element).word = (yyvsp[0].word); (yyval.element).redirect = 0; }
 #line 2501 "y.tab.c"
     break;
   case 56: /* simple_command_element: redirection  */
 #line 748 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.element).redirect = (yyvsp[0].redirect); (yyval.element).word = 0; }
 #line 2507 "y.tab.c"
     break;
   case 57: /* redirection_list: redirection  */
 #line 752 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.redirect) = (yyvsp[0].redirect);
             }
 #line 2515 "y.tab.c"
     break;
   case 58: /* redirection_list: redirection_list redirection  */
 #line 756 "/usr/local/src/chet/src/bash/src/parse.y"
{
               register REDIRECT *t;
               for (t = (yyvsp[-1].redirect); t->next; t = t->next)
                 ;
               t->next = (yyvsp[0].redirect);
               (yyval.redirect) = (yyvsp[-1].redirect);
             }
 #line 2528 "y.tab.c"
     break;
   case 59: /* simple_command: simple_command_element  */
 #line 767 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_simple_command ((yyvsp[0].element), (COMMAND *)NULL); }
 #line 2534 "y.tab.c"
     break;
   case 60: /* simple_command: simple_command simple_command_element  */
 #line 769 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_simple_command ((yyvsp[0].element), (yyvsp[-1].command)); }
 #line 2540 "y.tab.c"
     break;
   case 61: /* command: simple_command  */
 #line 773 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = clean_simple_command ((yyvsp[0].command)); }
 #line 2546 "y.tab.c"
     break;
   case 62: /* command: shell_command  */
 #line 775 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2552 "y.tab.c"
     break;
   case 63: /* command: shell_command redirection_list  */
 #line 777 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = (yyvsp[-1].command);
             }
 #line 2572 "y.tab.c"
     break;
   case 64: /* command: function_def  */
 #line 793 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2578 "y.tab.c"
     break;
   case 65: /* command: coproc  */
 #line 795 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2584 "y.tab.c"
     break;
   case 66: /* shell_command: for_command  */
 #line 799 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2590 "y.tab.c"
     break;
   case 67: /* shell_command: case_command  */
 #line 801 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2596 "y.tab.c"
     break;
   case 68: /* shell_command: WHILE compound_list DO compound_list DONE  */
 #line 803 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_while_command ((yyvsp[-3].command), (yyvsp[-1].command)); }
 #line 2602 "y.tab.c"
     break;
   case 69: /* shell_command: UNTIL compound_list DO compound_list DONE  */
 #line 805 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_until_command ((yyvsp[-3].command), (yyvsp[-1].command)); }
 #line 2608 "y.tab.c"
     break;
   case 70: /* shell_command: select_command  */
 #line 807 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2614 "y.tab.c"
     break;
   case 71: /* shell_command: if_command  */
 #line 809 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2620 "y.tab.c"
     break;
   case 72: /* shell_command: subshell  */
 #line 811 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2626 "y.tab.c"
     break;
   case 73: /* shell_command: group_command  */
 #line 813 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2632 "y.tab.c"
     break;
   case 74: /* shell_command: arith_command  */
 #line 815 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2638 "y.tab.c"
     break;
   case 75: /* shell_command: cond_command  */
 #line 817 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2644 "y.tab.c"
     break;
   case 76: /* shell_command: arith_for_command  */
 #line 819 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2650 "y.tab.c"
     break;
   case 77: /* for_command: FOR WORD newline_list DO compound_list DONE  */
 #line 823 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2659 "y.tab.c"
     break;
   case 78: /* for_command: FOR WORD newline_list '{' compound_list '}'  */
 #line 828 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2668 "y.tab.c"
     break;
   case 79: /* for_command: FOR WORD ';' newline_list DO compound_list DONE  */
 #line 833 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2677 "y.tab.c"
     break;
   case 80: /* for_command: FOR WORD ';' newline_list '{' compound_list '}'  */
 #line 838 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2686 "y.tab.c"
     break;
   case 81: /* for_command: FOR WORD newline_list IN word_list list_terminator newline_list DO compound_list DONE  */
 #line 843 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2695 "y.tab.c"
     break;
   case 82: /* for_command: FOR WORD newline_list IN word_list list_terminator newline_list '{' compound_list '}'  */
 #line 848 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2704 "y.tab.c"
     break;
   case 83: /* for_command: FOR WORD newline_list IN list_terminator newline_list DO compound_list DONE  */
 #line 853 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2713 "y.tab.c"
     break;
   case 84: /* for_command: FOR WORD newline_list IN list_terminator newline_list '{' compound_list '}'  */
 #line 858 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_for_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2722 "y.tab.c"
     break;
   case 85: /* arith_for_command: FOR ARITH_FOR_EXPRS list_terminator newline_list DO compound_list DONE  */
 #line 865 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-5].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2732 "y.tab.c"
     break;
   case 86: /* arith_for_command: FOR ARITH_FOR_EXPRS list_terminator newline_list '{' compound_list '}'  */
 #line 871 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-5].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2742 "y.tab.c"
     break;
   case 87: /* arith_for_command: FOR ARITH_FOR_EXPRS DO compound_list DONE  */
 #line 877 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-3].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2752 "y.tab.c"
     break;
   case 88: /* arith_for_command: FOR ARITH_FOR_EXPRS '{' compound_list '}'  */
 #line 883 "/usr/local/src/chet/src/bash/src/parse.y"
{
                   (yyval.command) = make_arith_for_command ((yyvsp[-3].word_list), (yyvsp[-1].command), arith_for_lineno);
                   if ((yyval.command) == 0) YYERROR;
                   if (word_top > 0) word_top--;
                 }
 #line 2762 "y.tab.c"
     break;
   case 89: /* select_command: SELECT WORD newline_list DO compound_list DONE  */
 #line 891 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2771 "y.tab.c"
     break;
   case 90: /* select_command: SELECT WORD newline_list '{' compound_list '}'  */
 #line 896 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-4].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2780 "y.tab.c"
     break;
   case 91: /* select_command: SELECT WORD ';' newline_list DO compound_list DONE  */
 #line 901 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2789 "y.tab.c"
     break;
   case 92: /* select_command: SELECT WORD ';' newline_list '{' compound_list '}'  */
 #line 906 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-5].word), add_string_to_list ("\"$@\"", (WORD_LIST *)NULL), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2798 "y.tab.c"
     break;
   case 93: /* select_command: SELECT WORD newline_list IN word_list list_terminator newline_list DO compound_list DONE  */
 #line 911 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2807 "y.tab.c"
     break;
   case 94: /* select_command: SELECT WORD newline_list IN word_list list_terminator newline_list '{' compound_list '}'  */
 #line 916 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-8].word), REVERSE_LIST ((yyvsp[-5].word_list), WORD_LIST *), (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2816 "y.tab.c"
     break;
   case 95: /* select_command: SELECT WORD newline_list IN list_terminator newline_list DO compound_list DONE  */
 #line 921 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2825 "y.tab.c"
     break;
   case 96: /* select_command: SELECT WORD newline_list IN list_terminator newline_list '{' compound_list '}'  */
 #line 926 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_select_command ((yyvsp[-7].word), (WORD_LIST *)NULL, (yyvsp[-1].command), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2834 "y.tab.c"
     break;
   case 97: /* case_command: CASE WORD newline_list IN newline_list ESAC  */
 #line 933 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_case_command ((yyvsp[-4].word), (PATTERN_LIST *)NULL, word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2843 "y.tab.c"
     break;
   case 98: /* case_command: CASE WORD newline_list IN case_clause_sequence newline_list ESAC  */
 #line 938 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_case_command ((yyvsp[-5].word), (yyvsp[-2].pattern), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2852 "y.tab.c"
     break;
   case 99: /* case_command: CASE WORD newline_list IN case_clause ESAC  */
 #line 943 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_case_command ((yyvsp[-4].word), (yyvsp[-1].pattern), word_lineno[word_top]);
               if (word_top > 0) word_top--;
             }
 #line 2861 "y.tab.c"
     break;
   case 100: /* function_def: WORD '(' ')' newline_list function_body  */
 #line 950 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-4].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2867 "y.tab.c"
     break;
   case 101: /* function_def: FUNCTION WORD '(' ')' newline_list function_body  */
 #line 952 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-4].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2873 "y.tab.c"
     break;
   case 102: /* function_def: FUNCTION WORD function_body  */
 #line 954 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-1].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2879 "y.tab.c"
     break;
   case 103: /* function_def: FUNCTION WORD '\n' newline_list function_body  */
 #line 956 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_function_def ((yyvsp[-3].word), (yyvsp[0].command), function_dstart, function_bstart); }
 #line 2885 "y.tab.c"
     break;
   case 104: /* function_body: shell_command  */
 #line 960 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 2891 "y.tab.c"
     break;
   case 105: /* function_body: shell_command redirection_list  */
 #line 962 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               /* According to Posix.2 3.9.5, redirections
                  specified after the body of a function should
                  be attached to the function and performed when
                  the function is executed, not as part of the
                  function definition command. */
               /* XXX - I don't think it matters, but we might
                  want to change this in the future to avoid
                  problems differentiating between a function
                  definition with a redirection and a function
                  definition containing a single command with a
                  redirection.  The two are semantically equivalent,
                  though -- the only difference is in how the
                  command printing code displays the redirections. */
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = (yyvsp[-1].command);
             }
 #line 2924 "y.tab.c"
     break;
   case 106: /* subshell: '(' compound_list ')'  */
 #line 993 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_subshell_command ((yyvsp[-1].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL;
             }
 #line 2933 "y.tab.c"
     break;
   case 107: /* comsub: DOLPAREN compound_list ')'  */
 #line 1000 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[-1].command);
             }
 #line 2941 "y.tab.c"
     break;
   case 108: /* comsub: DOLPAREN newline_list ')'  */
 #line 1004 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (COMMAND *)NULL;
             }
 #line 2949 "y.tab.c"
     break;
   case 109: /* coproc: COPROC shell_command  */
 #line 1010 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_coproc_command ("COPROC", (yyvsp[0].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 2958 "y.tab.c"
     break;
   case 110: /* coproc: COPROC shell_command redirection_list  */
 #line 1015 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = make_coproc_command ("COPROC", (yyvsp[-1].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 2979 "y.tab.c"
     break;
   case 111: /* coproc: COPROC WORD shell_command  */
 #line 1032 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_coproc_command ((yyvsp[-1].word)->word, (yyvsp[0].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 2988 "y.tab.c"
     break;
   case 112: /* coproc: COPROC WORD shell_command redirection_list  */
 #line 1037 "/usr/local/src/chet/src/bash/src/parse.y"
{
               COMMAND *tc;
               tc = (yyvsp[-1].command);
               if (tc && tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = (yyvsp[0].redirect);
                 }
               else if (tc)
                 tc->redirects = (yyvsp[0].redirect);
               (yyval.command) = make_coproc_command ((yyvsp[-2].word)->word, (yyvsp[-1].command));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 3009 "y.tab.c"
     break;
   case 113: /* coproc: COPROC simple_command  */
 #line 1054 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = make_coproc_command ("COPROC", clean_simple_command ((yyvsp[0].command)));
               (yyval.command)->flags |= CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
             }
 #line 3018 "y.tab.c"
     break;
   case 114: /* if_command: IF compound_list THEN compound_list FI  */
 #line 1061 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-3].command), (yyvsp[-1].command), (COMMAND *)NULL); }
 #line 3024 "y.tab.c"
     break;
   case 115: /* if_command: IF compound_list THEN compound_list ELSE compound_list FI  */
 #line 1063 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-5].command), (yyvsp[-3].command), (yyvsp[-1].command)); }
 #line 3030 "y.tab.c"
     break;
   case 116: /* if_command: IF compound_list THEN compound_list elif_clause FI  */
 #line 1065 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-4].command), (yyvsp[-2].command), (yyvsp[-1].command)); }
 #line 3036 "y.tab.c"
     break;
   case 117: /* group_command: '{' compound_list '}'  */
 #line 1070 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_group_command ((yyvsp[-1].command)); }
 #line 3042 "y.tab.c"
     break;
   case 118: /* arith_command: ARITH_CMD  */
 #line 1074 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_arith_command ((yyvsp[0].word_list)); }
 #line 3048 "y.tab.c"
     break;
   case 119: /* cond_command: COND_START COND_CMD COND_END  */
 #line 1078 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[-1].command); }
 #line 3054 "y.tab.c"
     break;
   case 120: /* elif_clause: ELIF compound_list THEN compound_list  */
 #line 1082 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-2].command), (yyvsp[0].command), (COMMAND *)NULL); }
 #line 3060 "y.tab.c"
     break;
   case 121: /* elif_clause: ELIF compound_list THEN compound_list ELSE compound_list  */
 #line 1084 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-4].command), (yyvsp[-2].command), (yyvsp[0].command)); }
 #line 3066 "y.tab.c"
     break;
   case 122: /* elif_clause: ELIF compound_list THEN compound_list elif_clause  */
 #line 1086 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = make_if_command ((yyvsp[-3].command), (yyvsp[-1].command), (yyvsp[0].command)); }
 #line 3072 "y.tab.c"
     break;
   case 124: /* case_clause: case_clause_sequence pattern_list  */
 #line 1091 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[0].pattern)->next = (yyvsp[-1].pattern); (yyval.pattern) = (yyvsp[0].pattern); }
 #line 3078 "y.tab.c"
     break;
   case 125: /* pattern_list: newline_list pattern ')' compound_list  */
 #line 1095 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (yyvsp[0].command)); }
 #line 3084 "y.tab.c"
     break;
   case 126: /* pattern_list: newline_list pattern ')' newline_list  */
 #line 1097 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (COMMAND *)NULL); }
 #line 3090 "y.tab.c"
     break;
   case 127: /* pattern_list: newline_list '(' pattern ')' compound_list  */
 #line 1099 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (yyvsp[0].command)); }
 #line 3096 "y.tab.c"
     break;
   case 128: /* pattern_list: newline_list '(' pattern ')' newline_list  */
 #line 1101 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = make_pattern_list ((yyvsp[-2].word_list), (COMMAND *)NULL); }
 #line 3102 "y.tab.c"
     break;
   case 129: /* case_clause_sequence: pattern_list SEMI_SEMI  */
 #line 1105 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3108 "y.tab.c"
     break;
   case 130: /* case_clause_sequence: case_clause_sequence pattern_list SEMI_SEMI  */
 #line 1107 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->next = (yyvsp[-2].pattern); (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3114 "y.tab.c"
     break;
   case 131: /* case_clause_sequence: pattern_list SEMI_AND  */
 #line 1109 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_FALLTHROUGH; (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3120 "y.tab.c"
     break;
   case 132: /* case_clause_sequence: case_clause_sequence pattern_list SEMI_AND  */
 #line 1111 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_FALLTHROUGH; (yyvsp[-1].pattern)->next = (yyvsp[-2].pattern); (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3126 "y.tab.c"
     break;
   case 133: /* case_clause_sequence: pattern_list SEMI_SEMI_AND  */
 #line 1113 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_TESTNEXT; (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3132 "y.tab.c"
     break;
   case 134: /* case_clause_sequence: case_clause_sequence pattern_list SEMI_SEMI_AND  */
 #line 1115 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyvsp[-1].pattern)->flags |= CASEPAT_TESTNEXT; (yyvsp[-1].pattern)->next = (yyvsp[-2].pattern); (yyval.pattern) = (yyvsp[-1].pattern); }
 #line 3138 "y.tab.c"
     break;
   case 135: /* pattern: WORD  */
 #line 1119 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (WORD_LIST *)NULL); }
 #line 3144 "y.tab.c"
     break;
   case 136: /* pattern: pattern '|' WORD  */
 #line 1121 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.word_list) = make_word_list ((yyvsp[0].word), (yyvsp[-2].word_list)); }
 #line 3150 "y.tab.c"
     break;
   case 137: /* compound_list: newline_list list0  */
 #line 1130 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[0].command);
               if (need_here_doc && last_read_token == '\n')
                 gather_here_documents ();
              }
 #line 3160 "y.tab.c"
     break;
   case 138: /* compound_list: newline_list list1  */
 #line 1136 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[0].command);
             }
 #line 3168 "y.tab.c"
     break;
   case 140: /* list0: list1 '&' newline_list  */
 #line 1143 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-2].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-2].command), (COMMAND *)NULL, '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-2].command), (COMMAND *)NULL, '&');
             }
 #line 3179 "y.tab.c"
     break;
   case 142: /* list1: list1 AND_AND newline_list list1  */
 #line 1154 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), AND_AND); }
 #line 3185 "y.tab.c"
     break;
   case 143: /* list1: list1 OR_OR newline_list list1  */
 #line 1156 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), OR_OR); }
 #line 3191 "y.tab.c"
     break;
   case 144: /* list1: list1 '&' newline_list list1  */
 #line 1158 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-3].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-3].command), (yyvsp[0].command), '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '&');
             }
 #line 3202 "y.tab.c"
     break;
   case 145: /* list1: list1 ';' newline_list list1  */
 #line 1165 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), ';'); }
 #line 3208 "y.tab.c"
     break;
   case 146: /* list1: list1 '\n' newline_list list1  */
 #line 1167 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if (parser_state & PST_CMDSUBST)
                 (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '\n');
               else
                 (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), ';');
             }
 #line 3219 "y.tab.c"
     break;
   case 147: /* list1: pipeline_command  */
 #line 1174 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3225 "y.tab.c"
     break;
   case 150: /* list_terminator: '\n'  */
 #line 1182 "/usr/local/src/chet/src/bash/src/parse.y"
                 { (yyval.number) = '\n'; }
 #line 3231 "y.tab.c"
     break;
   case 151: /* list_terminator: ';'  */
 #line 1184 "/usr/local/src/chet/src/bash/src/parse.y"
                 { (yyval.number) = ';'; }
 #line 3237 "y.tab.c"
     break;
   case 152: /* list_terminator: yacc_EOF  */
 #line 1186 "/usr/local/src/chet/src/bash/src/parse.y"
                 { (yyval.number) = yacc_EOF; }
 #line 3243 "y.tab.c"
     break;
   case 155: /* simple_list: simple_list1  */
 #line 1200 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[0].command);
               if (need_here_doc)
                 gather_here_documents ();   /* XXX */
               if ((parser_state & PST_CMDSUBST) && current_token == shell_eof_token)
                 {
 INTERNAL_DEBUG (("LEGACY: parser: command substitution simple_list1 -> simple_list"));
                   global_command = (yyvsp[0].command);
                   eof_encountered = 0;
                   if (bash_input.type == st_string)
                 rewind_input_string ();
                   YYACCEPT;
                 }
             }
 #line 3262 "y.tab.c"
     break;
   case 156: /* simple_list: simple_list1 '&'  */
 #line 1215 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-1].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-1].command), (COMMAND *)NULL, '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-1].command), (COMMAND *)NULL, '&');
               if (need_here_doc)
                 gather_here_documents (); /* XXX */
               if ((parser_state & PST_CMDSUBST) && current_token == shell_eof_token)
                 {
 INTERNAL_DEBUG (("LEGACY: parser: command substitution simple_list1 '&' -> simple_list"));
                   global_command = (yyvsp[-1].command);
                   eof_encountered = 0;
                   if (bash_input.type == st_string)
                 rewind_input_string ();
                   YYACCEPT;
                 }
             }
 #line 3284 "y.tab.c"
     break;
   case 157: /* simple_list: simple_list1 ';'  */
 #line 1233 "/usr/local/src/chet/src/bash/src/parse.y"
{
               (yyval.command) = (yyvsp[-1].command);
               if (need_here_doc)
                 gather_here_documents ();   /* XXX */
               if ((parser_state & PST_CMDSUBST) && current_token == shell_eof_token)
                 {
 INTERNAL_DEBUG (("LEGACY: parser: command substitution simple_list1 ';' -> simple_list"));
                   global_command = (yyvsp[-1].command);
                   eof_encountered = 0;
                   if (bash_input.type == st_string)
                 rewind_input_string ();
                   YYACCEPT;
                 }
             }
 #line 3303 "y.tab.c"
     break;
   case 158: /* simple_list1: simple_list1 AND_AND newline_list simple_list1  */
 #line 1250 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), AND_AND); }
 #line 3309 "y.tab.c"
     break;
   case 159: /* simple_list1: simple_list1 OR_OR newline_list simple_list1  */
 #line 1252 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), OR_OR); }
 #line 3315 "y.tab.c"
     break;
   case 160: /* simple_list1: simple_list1 '&' simple_list1  */
 #line 1254 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[-2].command)->type == cm_connection)
                 (yyval.command) = connect_async_list ((yyvsp[-2].command), (yyvsp[0].command), '&');
               else
                 (yyval.command) = command_connect ((yyvsp[-2].command), (yyvsp[0].command), '&');
             }
 #line 3326 "y.tab.c"
     break;
   case 161: /* simple_list1: simple_list1 ';' simple_list1  */
 #line 1261 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-2].command), (yyvsp[0].command), ';'); }
 #line 3332 "y.tab.c"
     break;
   case 162: /* simple_list1: pipeline_command  */
 #line 1264 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3338 "y.tab.c"
     break;
   case 163: /* pipeline_command: pipeline  */
 #line 1268 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3344 "y.tab.c"
     break;
   case 164: /* pipeline_command: BANG pipeline_command  */
 #line 1270 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[0].command))
                 (yyvsp[0].command)->flags ^= CMD_INVERT_RETURN; /* toggle */
               (yyval.command) = (yyvsp[0].command);
             }
 #line 3354 "y.tab.c"
     break;
   case 165: /* pipeline_command: timespec pipeline_command  */
 #line 1276 "/usr/local/src/chet/src/bash/src/parse.y"
{
               if ((yyvsp[0].command))
                 (yyvsp[0].command)->flags |= (yyvsp[-1].number);
               (yyval.command) = (yyvsp[0].command);
             }
 #line 3364 "y.tab.c"
     break;
   case 166: /* pipeline_command: timespec list_terminator  */
 #line 1282 "/usr/local/src/chet/src/bash/src/parse.y"
{
               ELEMENT x;
               /* Boy, this is unclean.  `time' by itself can
                  time a null command.  We cheat and push a
                  newline back if the list_terminator was a newline
                  to avoid the double-newline problem (one to
                  terminate this, one to terminate the command) */
               x.word = 0;
               x.redirect = 0;
               (yyval.command) = make_simple_command (x, (COMMAND *)NULL);
               (yyval.command)->flags |= (yyvsp[-1].number);
               /* XXX - let's cheat and push a newline back */
               if ((yyvsp[0].number) == '\n')
                 token_to_read = '\n';
               else if ((yyvsp[0].number) == ';')
                 token_to_read = ';';
               parser_state &= ~PST_REDIRLIST;   /* make_simple_command sets this */
             }
 #line 3388 "y.tab.c"
     break;
   case 167: /* pipeline_command: BANG list_terminator  */
 #line 1302 "/usr/local/src/chet/src/bash/src/parse.y"
{
               ELEMENT x;
               /* This is just as unclean.  Posix says that `!'
                  by itself should be equivalent to `false'.
                  We cheat and push a
                  newline back if the list_terminator was a newline
                  to avoid the double-newline problem (one to
                  terminate this, one to terminate the command) */
               x.word = 0;
               x.redirect = 0;
               (yyval.command) = make_simple_command (x, (COMMAND *)NULL);
               (yyval.command)->flags |= CMD_INVERT_RETURN;
               /* XXX - let's cheat and push a newline back */
               if ((yyvsp[0].number) == '\n')
                 token_to_read = '\n';
               if ((yyvsp[0].number) == ';')
                 token_to_read = ';';
               parser_state &= ~PST_REDIRLIST;   /* make_simple_command sets this */
             }
 #line 3413 "y.tab.c"
     break;
   case 168: /* pipeline: pipeline '|' newline_list pipeline  */
 #line 1325 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '|'); }
 #line 3419 "y.tab.c"
     break;
   case 169: /* pipeline: pipeline BAR_AND newline_list pipeline  */
 #line 1327 "/usr/local/src/chet/src/bash/src/parse.y"
{
               /* Make cmd1 |& cmd2 equivalent to cmd1 2>&1 | cmd2 */
               COMMAND *tc;
               REDIRECTEE rd, sd;
               REDIRECT *r;
               tc = (yyvsp[-3].command)->type == cm_simple ? (COMMAND *)(yyvsp[-3].command)->value.Simple : (yyvsp[-3].command);
               sd.dest = 2;
               rd.dest = 1;
               r = make_redirection (sd, r_duplicating_output, rd, 0);
               if (tc->redirects)
                 {
                   register REDIRECT *t;
                   for (t = tc->redirects; t->next; t = t->next)
                 ;
                   t->next = r;
                 }
               else
                 tc->redirects = r;
               (yyval.command) = command_connect ((yyvsp[-3].command), (yyvsp[0].command), '|');
             }
 #line 3446 "y.tab.c"
     break;
   case 170: /* pipeline: command  */
 #line 1350 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.command) = (yyvsp[0].command); }
 #line 3452 "y.tab.c"
     break;
   case 171: /* timespec: TIME  */
 #line 1354 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE; }
 #line 3458 "y.tab.c"
     break;
   case 172: /* timespec: TIME TIMEOPT  */
 #line 1356 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE|CMD_TIME_POSIX; }
 #line 3464 "y.tab.c"
     break;
   case 173: /* timespec: TIME TIMEIGN  */
 #line 1358 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE|CMD_TIME_POSIX; }
 #line 3470 "y.tab.c"
     break;
   case 174: /* timespec: TIME TIMEOPT TIMEIGN  */
 #line 1360 "/usr/local/src/chet/src/bash/src/parse.y"
                         { (yyval.number) = CMD_TIME_PIPELINE|CMD_TIME_POSIX; }
 #line 3476 "y.tab.c"
     break;
 #line 3480 "y.tab.c"
       default: break;
     }
   /* User semantic actions sometimes alter yychar, and that requires
      that yytoken be updated with the new translation.  We take the
      approach of translating immediately before every use of yytoken.
      One alternative is translating here after every semantic action,
      but that translation would be missed if the semantic action invokes
      YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
      if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
      incorrect destructor might then be invoked immediately.  In the
      case of YYERROR or YYBACKUP, subsequent parser actions might lead
      to an incorrect destructor call or verbose syntax error message
      before the lookahead is translated.  */
   YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   *++yyvsp = yyval;
   /* Now 'shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   {
     const int yylhs = yyr1[yyn] - YYNTOKENS;
     const int yyi = yypgoto[yylhs] + *yyssp;
     yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
                ? yytable[yyi]
                : yydefgoto[yylhs]);
   }
   goto yynewstate;
 /*--------------------------------------.
 | yyerrlab -- here on detecting error.  |
 `--------------------------------------*/
 yyerrlab:
   /* Make sure we have latest lookahead translation.  See comments at
      user semantic actions for why this is necessary.  */
   yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
       yyerror (YY_("syntax error"));
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
          error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct ("Error: discarding",
                       yytoken, &yylval);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers when the user code never invokes YYERROR and the
      label yyerrorlab therefore never appears in user code.  */
   if (0)
     YYERROR;
   ++yynerrs;
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;      /* Each real token shifted decrements this.  */
   /* Pop stack until we find a state that shifts the error token.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (!yypact_value_is_default (yyn))
         {
           yyn += YYSYMBOL_YYerror;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct ("Error: popping",
                   YY_ACCESSING_SYMBOL (yystate), yyvsp);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturnlab;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturnlab;
 /*-----------------------------------------------------------.
 | yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
 `-----------------------------------------------------------*/
 yyexhaustedlab:
   yyerror (YY_("memory exhausted"));
   yyresult = 2;
   goto yyreturnlab;
 /*----------------------------------------------------------.
 | yyreturnlab -- parsing is finished, clean up and return.  |
 `----------------------------------------------------------*/
 yyreturnlab:
   if (yychar != YYEMPTY)
     {
       /* Make sure we have latest lookahead translation.  See comments at
          user semantic actions for why this is necessary.  */
       yytoken = YYTRANSLATE (yychar);
       yydestruct ("Cleanup: discarding lookahead",
                   yytoken, &yylval);
     }
   /* Do not reclaim the symbols of the rule whose action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
                   YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
   return yyresult;
 }
References add_string_to_list, AND_AND, arith_for_lineno, bash_input, CASEPAT_FALLTHROUGH, CASEPAT_TESTNEXT, clean_simple_command(), cm_connection, cm_simple, CMD_COPROC_SUBSHELL, CMD_INVERT_RETURN, CMD_TIME_PIPELINE, CMD_TIME_POSIX, CMD_WANT_SUBSHELL, YYSTYPE::command, command_connect(), connect_async_list(), current_token, REDIRECTEE::dest, YYSTYPE::element, eof_encountered, EX_BADUSAGE, REDIRECTEE::filename, flags, function_bstart, function_dstart, gather_here_documents(), global_command, handle_eof_input_unit(), interactive, INTERNAL_DEBUG, last_command_exit_value, last_read_token, make_arith_command(), make_arith_for_command(), make_case_command(), make_coproc_command(), make_for_command(), make_function_def(), make_group_command(), make_if_command(), make_pattern_list(), make_redirection(), make_select_command(), make_simple_command(), make_subshell_command(), make_until_command(), make_while_command(), make_word_list(), need_here_doc, next, NULL, number(), YYSTYPE::number, OR_OR, parse_and_execute_level, parser_state, pattern, YYSTYPE::pattern, PST_CMDSUBST, PST_EOFTOKEN, PST_REDIRLIST, push_heredoc(), r_append_err_and_out, r_appending_to, r_close_this, r_deblank_reading_until, r_duplicating_input, r_duplicating_input_word, r_duplicating_output, r_duplicating_output_word, r_err_and_out, r_input_direction, r_input_output, r_output_direction, r_output_force, r_reading_string, r_reading_until, rd, redir, REDIR_VARASSIGN, YYSTYPE::redirect, REVERSE_LIST, rewind_input_string(), shell_eof_token, source, st_string, stderr, t, tc, token_to_read, BASH_INPUT::type, type, value, YYSTYPE::word, word_lineno, YYSTYPE::word_list, word_top, x, yacc_EOF, YY_, YY_ACCESSING_SYMBOL, YY_ASSERT, YY_CAST, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_IGNORE_USELESS_CAST_BEGIN, YY_IGNORE_USELESS_CAST_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, YYerror, YYERROR, yyerror(), YYFINAL, YYINITDEPTH, YYLAST, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNOMEM, YYNSTATES, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, YYPTRDIFF_T, yyr1, yyr2, YYSIZE_T, YYSIZEOF, yyalloc::yyss, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYSYMBOL_YYEMPTY, YYSYMBOL_YYEOF, YYSYMBOL_YYerror, yytable, yytable_value_is_error, YYTRANSLATE, YYUNDEF, yyalloc::yyvs, and yyalloc::yyvs_alloc.
Referenced by parse_comsub().
Variable Documentation
arith_for_lineno
int arith_for_lineno static
Definition at line 349 of file y.tab.c.
Referenced by yyparse().
bash_input
BASH_INPUT bash_input
Definition at line 3723 of file y.tab.c.
Referenced by can_optimize_connection(), init_yy_io(), initialize_bash_input(), parse_and_execute(), parse_command(), parse_string(), parse_string_to_word_list(), pop_stream(), push_stream(), read_a_line(), read_token(), rewind_input_string(), shell_getc(), should_suppress_fork(), unset_bash_input(), xparse_dolparen(), yy_getc(), yy_input_name(), yy_stream_get(), yy_stream_unget(), yy_string_get(), yy_string_unget(), yy_ungetc(), and yyparse().
current_command_line_count
int current_command_line_count
Definition at line 313 of file y.tab.c.
Referenced by parse_command(), parse_string_to_word_list(), read_command(), read_secondary_line(), restore_parser_state(), save_parser_state(), and shell_getc().
current_decoded_prompt
char* current_decoded_prompt static
Definition at line 353 of file y.tab.c.
Referenced by print_prompt(), and prompt_again().
current_prompt_string
char* current_prompt_string
Definition at line 296 of file y.tab.c.
Referenced by get_current_prompt_level(), prompt_again(), set_current_prompt_level(), and shell_getc().
current_token
int current_token
Definition at line 322 of file y.tab.c.
Referenced by _evalfile(), error_token_from_token(), handle_eof_input_unit(), parse_and_execute(), parse_compound_assignment(), parse_comsub(), parse_string(), parse_string_to_word_list(), push_token(), report_syntax_error(), reset_parser(), restore_token_state(), save_token_state(), xparse_dolparen(), yylex(), and yyparse().
dstack
struct dstack dstack = { (char *)NULL, 0, 0 }
Definition at line 4536 of file y.tab.c.
Referenced by decode_prompt_string().
eof_encountered
int eof_encountered = 0
Definition at line 8625 of file y.tab.c.
Referenced by handle_eof_input_unit(), restore_parser_state(), save_parser_state(), sv_ignoreeof(), and yyparse().
eof_encountered_limit
int eof_encountered_limit = 10
Definition at line 8628 of file y.tab.c.
Referenced by handle_eof_input_unit(), and sv_ignoreeof().
EOF_Reached
int EOF_Reached = 0
Definition at line 3691 of file y.tab.c.
Referenced by handle_eof_input_unit(), parse_comsub(), parse_matched_pair(), pop_stream(), pretty_print_loop(), push_stream(), read_token(), reader_loop(), and report_syntax_error().
eol_ungetc_lookahead
int eol_ungetc_lookahead = 0 static
Definition at line 4618 of file y.tab.c.
Referenced by reset_parser(), restore_parser_state(), save_parser_state(), shell_getc(), and shell_ungetc().
errno
int errno extern
esacs_needed_count
int esacs_needed_count static
Definition at line 5221 of file y.tab.c.
Referenced by parse_compound_assignment(), parse_comsub(), reset_parser(), restore_parser_state(), save_parser_state(), and special_case_tokens().
expand_aliases
int expand_aliases = 0
Definition at line 299 of file y.tab.c.
Referenced by command_substitute(), execute_in_subshell(), init_interactive(), init_interactive_script(), init_noninteractive(), main(), parse_and_execute(), parse_comsub(), parse_string_to_command(), parse_string_to_word_list(), posix_initialize(), read_token_word(), reset_parser(), restore_parser_state(), save_parser_state(), shell_reinitialize(), and xparse_dolparen().
expecting_in_token
int expecting_in_token static
Definition at line 5225 of file y.tab.c.
Referenced by parse_compound_assignment(), parse_comsub(), read_token_word(), reset_parser(), restore_parser_state(), save_parser_state(), and special_case_tokens().
extended_quote
int extended_quote = 1
Definition at line 310 of file y.tab.c.
Referenced by extract_heredoc_dolbrace_string(), and parse_matched_pair().
function_bstart
int function_bstart static
Definition at line 346 of file y.tab.c.
Referenced by special_case_tokens(), and yyparse().
function_dstart
int function_dstart static
Definition at line 343 of file y.tab.c.
Referenced by read_token(), read_token_word(), and yyparse().
global_extglob
int global_extglob static
Definition at line 365 of file y.tab.c.
ignoreeof
int ignoreeof = 0
Definition at line 8620 of file y.tab.c.
Referenced by handle_eof_input_unit(), and sv_ignoreeof().
last_read_token
int last_read_token static
Definition at line 357 of file y.tab.c.
Referenced by handle_eof_input_unit(), parse_compound_assignment(), parse_string_to_word_list(), parser_in_command_position(), push_token(), read_token(), read_token_word(), reserved_word_acceptable(), reset_parser(), restore_token_state(), save_token_state(), special_case_tokens(), time_command_acceptable(), yylex(), and yyparse().
line_number
int line_number = 0
Definition at line 4045 of file y.tab.c.
Referenced by assign_lineno(), execute_case_command(), execute_command_internal(), execute_connection(), execute_for_command(), execute_function(), execute_if_command(), execute_simple_command(), executing_line_number(), extract_heredoc_dolbrace_string(), gather_here_documents(), make_arith_command(), make_bare_simple_command(), make_here_document(), make_subshell_command(), notify_of_job_status(), parse_and_execute(), parse_compound_assignment(), parse_comsub(), parse_matched_pair(), parse_prologue(), parse_string_to_word_list(), pop_stream(), print_offending_line(), push_stream(), read_a_line(), read_token(), read_token_word(), report_syntax_error(), shell_getc(), shell_reinitialize(), special_case_tokens(), and xparse_dolparen().
line_number_base
int line_number_base = 0
Definition at line 4048 of file y.tab.c.
matched_pair_error
char matched_pair_error static
Definition at line 5967 of file y.tab.c.
Referenced by parse_comsub(), parse_matched_pair(), and read_token_word().
need_here_doc
int need_here_doc
Definition at line 330 of file y.tab.c.
Referenced by gather_here_documents(), parse_command(), parse_comsub(), push_heredoc(), read_token(), reset_parser(), restore_parser_state(), save_parser_state(), and yyparse().
open_brace_count
int open_brace_count static
Definition at line 5262 of file y.tab.c.
Referenced by reset_parser(), and special_case_tokens().
other_token_alist
STRING_INT_ALIST other_token_alist[]
Definition at line 4536 of file y.tab.c.
Referenced by error_token_from_token().
parse_string_error
WORD_LIST parse_string_error static
Definition at line 8685 of file y.tab.c.
Referenced by parse_compound_assignment(), and parse_string_to_word_list().
parser_state
int parser_state
Definition at line 325 of file y.tab.c.
Referenced by clean_simple_command(), gather_here_documents(), make_here_document(), make_simple_command(), parse_compound_assignment(), parse_comsub(), parse_matched_pair(), parse_string_to_command(), parse_string_to_word_list(), pop_string(), push_string(), read_secondary_line(), read_token(), read_token_word(), reset_parser(), restore_parser_state(), save_parser_state(), shell_getc(), special_case_tokens(), xparse_dolparen(), yyerror(), yylex(), and yyparse().
primary_prompt
char* primary_prompt = PPROMPT
Definition at line 284 of file y.tab.c.
Referenced by initialize_shell_variables(), and shell_reinitialize().
prompt_string_pointer
char** prompt_string_pointer = (char **)NULL
Definition at line 295 of file y.tab.c.
Referenced by handle_eof_input_unit(), prompt_again(), read_secondary_line(), restore_parser_state(), save_parser_state(), set_current_prompt_level(), and shell_getc().
promptvars
int promptvars = 1
Definition at line 305 of file y.tab.c.
Referenced by decode_prompt_string().
ps0_prompt
char* ps0_prompt
Definition at line 291 of file y.tab.c.
Referenced by decode_prompt_string(), prompt_again(), and reader_loop().
ps1_prompt
char* ps1_prompt
Definition at line 288 of file y.tab.c.
Referenced by decode_prompt_string(), prompt_again(), and set_current_prompt_level().
ps2_prompt
char * ps2_prompt
Definition at line 288 of file y.tab.c.
Referenced by decode_prompt_string(), get_current_prompt_level(), prompt_again(), read_secondary_line(), and set_current_prompt_level().
pushed_string_list
STRING_SAVER* pushed_string_list = (STRING_SAVER *)NULL
Definition at line 4205 of file y.tab.c.
Referenced by free_string_list(), parse_comsub(), parse_string_to_command(), parser_restore_alias(), parser_save_alias(), pop_string(), push_string(), reset_parser(), restore_parser_state(), save_parser_state(), shell_getc(), and xparse_dolparen().
redir
REDIRECTEE redir static
Definition at line 382 of file y.tab.c.
Referenced by __dlsym_redir_time64(), do_wordexp(), expredir(), fetch_heredocs(), openhere(), openredirect(), parse_command(), parse_redirect(), pushredir(), query(), recursive_query(), redir_varassign(), redir_varvalue(), redirect(), redirectsafe(), setup_heredoc(), setup_redirects(), simplecmd(), and yyparse().
redir_stack
REDIRECT* redir_stack[HEREDOC_MAX] static
Definition at line 329 of file y.tab.c.
Referenced by gather_here_documents(), push_heredoc(), reset_parser(), restore_parser_state(), and save_parser_state().
saved_command_line_count
int saved_command_line_count
Definition at line 316 of file y.tab.c.
secondary_prompt
char* secondary_prompt = SPROMPT
Definition at line 285 of file y.tab.c.
Referenced by initialize_shell_variables(), and shell_reinitialize().
shell_eof_token
int shell_eof_token
Definition at line 319 of file y.tab.c.
Referenced by make_here_document(), parse_comsub(), parse_string(), read_token(), report_syntax_error(), restore_parser_state(), save_parser_state(), shell_getc(), xparse_dolparen(), yylex(), and yyparse().
shell_input_line
char* shell_input_line = (char *)NULL static
Definition at line 334 of file y.tab.c.
Referenced by clear_shell_input_line(), error_token_from_text(), parser_remaining_input(), pop_string(), print_offending_line(), push_string(), report_syntax_error(), reset_parser(), restore_input_line_state(), save_input_line_state(), shell_getc(), shell_ungetc(), shell_ungets(), and time_command_acceptable().
shell_input_line_index
size_t shell_input_line_index static
Definition at line 335 of file y.tab.c.
Referenced by clear_shell_input_line(), error_token_from_text(), parser_remaining_input(), pop_string(), push_string(), reset_parser(), restore_input_line_state(), rewind_input_string(), save_input_line_state(), shell_getc(), shell_ungetc(), shell_ungets(), and time_command_acceptable().
shell_input_line_len
size_t shell_input_line_len static
Definition at line 337 of file y.tab.c.
Referenced by parser_remaining_input(), pop_string(), push_string(), restore_input_line_state(), rewind_input_string(), save_input_line_state(), shell_getc(), shell_ungets(), and time_command_acceptable().
shell_input_line_size
size_t shell_input_line_size static
Definition at line 336 of file y.tab.c.
Referenced by pop_string(), push_string(), reset_parser(), restore_input_line_state(), save_input_line_state(), shell_getc(), and shell_ungets().
shell_input_line_terminator
int shell_input_line_terminator static
Definition at line 340 of file y.tab.c.
Referenced by pop_string(), push_string(), restore_parser_state(), save_parser_state(), shell_getc(), and shell_ungets().
source
REDIRECTEE source static
Definition at line 381 of file y.tab.c.
Referenced by action_copy(), copy_file(), F_DrawPatchCol(), M_WriteFile(), make_redirection(), mount_or_die(), P_DamageMobj(), P_KillMobj(), P_RadiusAttack(), P_SpawnMissile(), P_SpawnPlayerMissile(), R_DrawColumnInCache(), S_AdjustSoundParams(), sort_index(), strcat_unsafe(), strcpy_unsafe(), strncpy(), sub_append_string(), traceroute_init(), V_CopyRect(), V_DrawAltTLPatch(), V_DrawPatch(), V_DrawPatchFlipped(), V_DrawShadowedPatch(), V_DrawTLPatch(), V_DrawXlaPatch(), and yyparse().
stream_list
STREAM_SAVER* stream_list = (STREAM_SAVER *)NULL
Definition at line 4055 of file y.tab.c.
Referenced by pop_stream(), push_stream(), and stream_on_stack().
temp_dstack
struct dstack temp_dstack = { (char *)NULL, 0, 0 } static
Definition at line 4536 of file y.tab.c.
Referenced by decode_prompt_string().
token
char* token = (char *)NULL static
Definition at line 5164 of file y.tab.c.
Referenced by save_parser_state().
token_before_that
int token_before_that static
Definition at line 360 of file y.tab.c.
Referenced by push_token(), read_token(), reserved_word_acceptable(), restore_token_state(), save_token_state(), special_case_tokens(), time_command_acceptable(), and yylex().
token_buffer_size
size_t token_buffer_size static
Definition at line 5167 of file y.tab.c.
Referenced by parse_compound_assignment(), read_token_word(), restore_parser_state(), and save_parser_state().
token_to_read
int token_to_read static
Definition at line 378 of file y.tab.c.
Referenced by execute_variable_command(), parse_comsub(), read_token(), reset_parser(), reset_readahead_token(), xparse_dolparen(), yylex(), and yyparse().
two_tokens_ago
int two_tokens_ago static
Definition at line 363 of file y.tab.c.
Referenced by push_token(), restore_token_state(), save_token_state(), and yylex().
unquoted_backslash
int unquoted_backslash = 0 static
Definition at line 4620 of file y.tab.c.
Referenced by shell_getc().
word_desc_to_read
WORD_DESC* word_desc_to_read static
Definition at line 379 of file y.tab.c.
Referenced by read_token(), and reset_parser().
word_lineno
int word_lineno[MAX_CASE_NEST+1] static
Definition at line 371 of file y.tab.c.
Referenced by read_token_word(), and yyparse().
word_token_alist
STRING_INT_ALIST word_token_alist[]
Definition at line 4501 of file y.tab.c.
Referenced by error_token_from_token(), and find_reserved_word().
word_top
int word_top = -1 static
Definition at line 372 of file y.tab.c.
Referenced by read_token_word(), and yyparse().
yychar
int yychar
Definition at line 1685 of file y.tab.c.
Referenced by yyparse().
yycheck
const yytype_int16 yycheck[] static
Definition at line 1315 of file y.tab.c.
Referenced by yyparse().
yydefact
const yytype_uint8 yydefact[] static
Definition at line 1176 of file y.tab.c.
Referenced by yyparse().
yydefgoto
const yytype_int16 yydefgoto[] static
Initial value:
=
{
       0,    35,   246,    36,    37,   125,    38,    39,    40,    41,
      42,    43,    44,    45,   155,    46,    47,    48,    49,    50,
      51,    52,   232,   238,   239,   240,   281,   120,   139,   140,
     128,    76,    61,    53,    54,   141,    56,    57
}
Definition at line 1225 of file y.tab.c.
Referenced by yyparse().
yyerrstream
FILE* yyerrstream static
Definition at line 385 of file y.tab.c.
yylval
YYSTYPE yylval
Definition at line 1688 of file y.tab.c.
Referenced by error_token_from_token(), parse_compound_assignment(), parse_string_to_word_list(), read_token(), read_token_word(), and yyparse().
yynerrs
int yynerrs
Definition at line 1690 of file y.tab.c.
Referenced by yyparse().
yyoutstream
FILE* yyoutstream static
Definition at line 384 of file y.tab.c.
yypact
const yytype_int16 yypact[] static
Definition at line 1134 of file y.tab.c.
Referenced by yyparse().
yypgoto
const yytype_int16 yypgoto[] static
Initial value:
=
{
    -152,  -152,   112,   -29,   -14,   -64,   360,  -152,    -8,  -152,
    -152,  -152,  -152,  -152,  -151,  -152,  -152,  -152,  -152,  -152,
    -152,  -152,    13,  -152,   136,  -152,    98,    -2,  -152,    30,
    -152,   -54,   -26,  -152,  -123,     6,    78,  -152
}
Definition at line 1216 of file y.tab.c.
Referenced by yyparse().
yyr1
const yytype_int8 yyr1[] static
Initial value:
=
{
       0,    62,    63,    63,    63,    63,    63,    63,    64,    64,
      65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    65,    65,    66,    66,    66,    67,    67,    68,
      68,    69,    69,    69,    69,    69,    70,    70,    70,    70,
      70,    70,    70,    70,    70,    70,    70,    71,    71,    71,
      71,    71,    71,    71,    71,    72,    72,    72,    72,    73,
      73,    73,    73,    73,    73,    73,    73,    74,    74,    74,
      75,    75,    75,    75,    76,    76,    77,    78,    78,    79,
      79,    79,    79,    79,    80,    80,    80,    81,    82,    83,
      84,    84,    84,    85,    85,    86,    86,    86,    86,    87,
      87,    87,    87,    87,    87,    88,    88,    89,    89,    90,
      90,    90,    91,    91,    91,    91,    91,    91,    92,    92,
      93,    93,    93,    94,    94,    95,    95,    95,    96,    96,
      96,    96,    96,    97,    97,    97,    97,    97,    98,    98,
      98,    99,    99,    99,    99
}
Definition at line 1436 of file y.tab.c.
Referenced by yyparse().
yyr2
const yytype_int8 yyr2[] static
Initial value:
=
{
       0,     2,     2,     1,     1,     2,     2,     1,     1,     2,
       2,     2,     3,     3,     3,     3,     2,     3,     3,     2,
       3,     3,     2,     3,     3,     2,     3,     3,     2,     3,
       3,     2,     3,     3,     2,     3,     3,     2,     3,     3,
       2,     3,     3,     2,     3,     3,     2,     3,     3,     2,
       3,     3,     2,     2,     1,     1,     1,     1,     2,     1,
       2,     1,     1,     2,     1,     1,     1,     1,     5,     5,
       1,     1,     1,     1,     1,     1,     1,     6,     6,     7,
       7,    10,    10,     9,     9,     7,     7,     5,     5,     6,
       6,     7,     7,    10,    10,     9,     9,     6,     7,     6,
       5,     6,     3,     5,     1,     2,     3,     3,     3,     2,
       3,     3,     4,     2,     5,     7,     6,     3,     1,     3,
       4,     6,     5,     1,     2,     4,     4,     5,     5,     2,
       3,     2,     3,     2,     3,     1,     3,     2,     2,     3,
       3,     3,     4,     4,     4,     4,     4,     1,     1,     1,
       1,     1,     1,     0,     2,     1,     2,     2,     4,     4,
       3,     3,     1,     1,     2,     2,     2,     2,     4,     4,
       1,     1,     2,     2,     3
}
Definition at line 1459 of file y.tab.c.
Referenced by yyparse().
yystos
const yytype_int8 yystos[] static
Definition at line 1396 of file y.tab.c.
yytable
const yytype_int16 yytable[] static
Definition at line 1236 of file y.tab.c.
Referenced by yyparse().
yytranslate
const yytype_int8 yytranslate[] static
Definition at line 1021 of file y.tab.c.