Fennix: Kernel/include/convert.h File Reference
convert.h File Reference
#include <types.h>
Data Structures
struct mbstate_t
Macros
#define NAN (__builtin_nanf(""))
#define memcpy(dest, src, n) __memcpy_chk(dest, src, n, __builtin_object_size(dest, 0))
#define memset(dest, c, n) __memset_chk(dest, c, n, __builtin_object_size(dest, 0))
#define memmove(dest, src, n) __memmove_chk(dest, src, n, __builtin_object_size(dest, 0))
#define strcat(dest, src) __strcat_chk(dest, src, __builtin_object_size(dest, 0))
#define strcpy(dest, src) __strcpy_chk(dest, src, __builtin_object_size(dest, 0))
Typedefs
typedef struct mbstate_t mbstate_t
Functions
int isdigit (int c)
int isspace (int c)
int isempty (char *str)
int isalpha (int c)
int isupper (int c)
unsigned int isdelim (char c, const char *delim)
long abs (long i)
void swap (char *x, char *y)
char * reverse (char *Buffer, int i, int j)
float sqrtf (float x)
double clamp (double x, double low, double high)
float lerp (float a, float b, float t)
float smoothstep (float a, float b, float t)
float cubicInterpolate (float a, float b, float t)
void backspace (char s[])
void append (char s[], char n)
int atoi (const char *String)
double atof (const char *String)
char * itoa (int Value, char *Buffer, int Base)
char * ltoa (long Value, char *Buffer, int Base)
char * ultoa (unsigned long Value, char *Buffer, int Base)
unsigned long int strtoul (const char *str, char **endptr, int base)
void * memcpy_unsafe (void *dest, const void *src, size_t n)
void * memset_unsafe (void *dest, int c, size_t n)
void * memmove_unsafe (void *dest, const void *src, size_t n)
int memcmp (const void *vl, const void *vr, size_t n)
void * memcpy_sse (void *dest, const void *src, size_t n)
void * memcpy_sse2 (void *dest, const void *src, size_t n)
void * memcpy_sse3 (void *dest, const void *src, size_t n)
void * memcpy_ssse3 (void *dest, const void *src, size_t n)
void * memcpy_sse4_1 (void *dest, const void *src, size_t n)
void * memcpy_sse4_2 (void *dest, const void *src, size_t n)
void * memset_sse (void *dest, int c, size_t n)
void * memset_sse2 (void *dest, int c, size_t n)
void * memset_sse3 (void *dest, int c, size_t n)
void * memset_ssse3 (void *dest, int c, size_t n)
void * memset_sse4_1 (void *dest, int c, size_t n)
void * memset_sse4_2 (void *dest, int c, size_t n)
void * memmove_sse (void *dest, const void *src, size_t n)
void * memmove_sse2 (void *dest, const void *src, size_t n)
void * memmove_sse3 (void *dest, const void *src, size_t n)
void * memmove_ssse3 (void *dest, const void *src, size_t n)
void * memmove_sse4_1 (void *dest, const void *src, size_t n)
void * memmove_sse4_2 (void *dest, const void *src, size_t n)
long unsigned strlen (const char s[])
int strncmp (const char *s1, const char *s2, unsigned long n)
char * strcat_unsafe (char *destination, const char *source)
char * strcpy_unsafe (char *destination, const char *source)
char * strncpy (char *destination, const char *source, unsigned long num)
int strcmp (const char *l, const char *r)
char * strstr (const char *haystack, const char *needle)
char * strdup (const char *String)
char * strchr (const char *String, int Char)
char * strrchr (const char *String, int Char)
int strncasecmp (const char *lhs, const char *rhs, long unsigned int Count)
int strcasecmp (const char *s1, const char *s2)
char * strtok (char *src, const char *delim)
long int strtol (const char *str, char **endptr, int base)
size_t wcslen (const wchar_t *s)
size_t wcsrtombs (char *dst, const wchar_t **src, size_t len, mbstate_t *ps)
int log2 (unsigned int n)
void * __memcpy_chk (void *dest, const void *src, size_t len, size_t slen)
void * __memset_chk (void *dest, int val, size_t len, size_t slen)
void * __memmove_chk (void *dest, const void *src, size_t len, size_t slen)
char * __strcat_chk (char *dest, const char *src, size_t slen)
char * __strcpy_chk (char *dest, const char *src, size_t slen)
Data Structure Documentation
mbstate_t
struct mbstate_t
Definition at line 26 of file convert.h.
Data Fields
int count
unsigned int value
Macro Definition Documentation
memcpy
#define memcpy (dest, src, n) __memcpy_chk(dest, src, n, __builtin_object_size(dest, 0))
Definition at line 116 of file convert.h.
memmove
#define memmove (dest, src, n) __memmove_chk(dest, src, n, __builtin_object_size(dest, 0))
Definition at line 124 of file convert.h.
memset
#define memset (dest, c, n) __memset_chk(dest, c, n, __builtin_object_size(dest, 0))
Definition at line 120 of file convert.h.
NAN
#define NAN (__builtin_nanf(""))
Definition at line 32 of file convert.h.
strcat
#define strcat (dest, src) __strcat_chk(dest, src, __builtin_object_size(dest, 0))
Definition at line 128 of file convert.h.
strcpy
#define strcpy (dest, src) __strcpy_chk(dest, src, __builtin_object_size(dest, 0))
Definition at line 132 of file convert.h.
Typedef Documentation
mbstate_t
typedef struct mbstate_t mbstate_t
Function Documentation
__memcpy_chk()
void* __memcpy_chk (void * dest, const void * src, size_t len, size_t slen)
Definition at line 767 of file Convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx len:%llu slen:%llu )",
           dest, src, len, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len == 0))
     {
         error("len is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len > slen))
         __chk_fail();
     void *ret = nullptr;
     if (0) /* FIXME */
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             ret = memcpy_sse4_2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             ret = memcpy_sse4_1(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             ret = memcpy_ssse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             ret = memcpy_sse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             ret = memcpy_sse2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             ret = memcpy_sse(dest, src, len);
         else
             ret = memcpy_unsafe(dest, src, len);
     }
     else
     {
         static int once = 0;
         if (!once++)
             fixme("SIMD memcpy disabled");
         ret = memcpy_unsafe(dest, src, len);
     }
     return ret;
 }
References __chk_fail(), __convert_chk_fail(), CPU::CheckSIMD(), debug, error, fixme, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelSymbolTable, len, memcpy_sse(), memcpy_sse2(), memcpy_sse3(), memcpy_sse4_1(), memcpy_sse4_2(), memcpy_ssse3(), memcpy_unsafe(), NULL, CPU::SIMD_SSE, CPU::SIMD_SSE2, CPU::SIMD_SSE3, CPU::SIMD_SSE41, CPU::SIMD_SSE42, CPU::SIMD_SSSE3, src, and unlikely.
Referenced by memcpy().
__memmove_chk()
void* __memmove_chk (void * dest, const void * src, size_t len, size_t slen)
Definition at line 905 of file Convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx len:%llu slen:%llu )",
           dest, src, len, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len == 0))
     {
         error("len is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len > slen))
         __chk_fail();
     void *ret = nullptr;
     if (0) /* FIXME */
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             ret = memmove_sse4_2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             ret = memmove_sse4_1(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             ret = memmove_ssse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             ret = memmove_sse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             ret = memmove_sse2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             ret = memmove_sse(dest, src, len);
         else
             ret = memmove_unsafe(dest, src, len);
     }
     else
     {
         static int once = 0;
         if (!once++)
             fixme("SIMD memmove disabled");
         ret = memmove_unsafe(dest, src, len);
     }
     return ret;
 }
References __chk_fail(), __convert_chk_fail(), CPU::CheckSIMD(), debug, error, fixme, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelSymbolTable, len, memmove_sse(), memmove_sse2(), memmove_sse3(), memmove_sse4_1(), memmove_sse4_2(), memmove_ssse3(), memmove_unsafe(), NULL, CPU::SIMD_SSE, CPU::SIMD_SSE2, CPU::SIMD_SSE3, CPU::SIMD_SSE41, CPU::SIMD_SSE42, CPU::SIMD_SSSE3, src, and unlikely.
__memset_chk()
void* __memset_chk (void * dest, int val, size_t len, size_t slen)
Definition at line 841 of file Convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx val:%#x len:%llu slen:%llu )", dest, val, len, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len == 0))
     {
         error("len is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len > slen))
         __chk_fail();
     void *ret = nullptr;
     if (0) /* FIXME */
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             ret = memset_sse4_2(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             ret = memset_sse4_1(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             ret = memset_ssse3(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             ret = memset_sse3(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             ret = memset_sse2(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             ret = memset_sse(dest, val, len);
         else
             ret = memset_unsafe(dest, val, len);
     }
     else
     {
         static int once = 0;
         if (!once++)
             fixme("SIMD memset disabled");
         ret = memset_unsafe(dest, val, len);
     }
     return ret;
 }
References __chk_fail(), __convert_chk_fail(), CPU::CheckSIMD(), debug, error, fixme, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelSymbolTable, len, memset_sse(), memset_sse2(), memset_sse3(), memset_sse4_1(), memset_sse4_2(), memset_ssse3(), memset_unsafe(), NULL, CPU::SIMD_SSE, CPU::SIMD_SSE2, CPU::SIMD_SSE3, CPU::SIMD_SSE41, CPU::SIMD_SSE42, CPU::SIMD_SSSE3, unlikely, and val.
Referenced by memset().
__strcat_chk()
char* __strcat_chk (char * dest, const char * src, size_t slen)
Definition at line 979 of file Convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx slen:%llu )",
           dest, src, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     size_t dest_len = strlen(dest);
     if (unlikely(dest_len + strlen(src) + 1 > slen))
         __chk_fail();
     return strcat_unsafe(dest, src);
 }
References __chk_fail(), __convert_chk_fail(), debug, error, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelSymbolTable, NULL, src, strcat_unsafe(), strlen(), and unlikely.
__strcpy_chk()
char* __strcpy_chk (char * dest, const char * src, size_t slen)
Definition at line 1018 of file Convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx slen:%llu )",
           dest, src, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     size_t len = strlen(src);
     if (unlikely(len >= slen))
         __chk_fail();
     return strcpy_unsafe(dest, src);
 }
References __chk_fail(), __convert_chk_fail(), debug, error, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelSymbolTable, len, NULL, src, strcpy_unsafe(), strlen(), and unlikely.
abs()
long abs (long i)
Definition at line 339 of file Convert.cpp.
 { return i < 0 ? -i : i; }
References i.
Referenced by itoa(), and ltoa().
append()
void append (char s[], char n)
Definition at line 44 of file Convert.cpp.
 {
     int len = s_cst(int, strlen(s));
     s[len] = n;
     s[len + 1] = '\0';
 }
References len, n, s, and strlen().
Referenced by _rl_copy_to_kill_ring(), awk_printf(), display_single(), escape_text(), expr_print_help(), gather_options_str(), new_init_action(), and tee_builtin().
atof()
double atof (const char * String)
Definition at line 553 of file Convert.cpp.
 {
     // Originally from https://github.com/GaloisInc/minlibc/blob/master/atof.c
     /*
     Copyright (c) 2014 Galois Inc.
     All rights reserved.
     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:
       * Redistributions of source code must retain the above copyright
         notice, this list of conditions and the following disclaimer.
       * Redistributions in binary form must reproduce the above copyright
         notice, this list of conditions and the following disclaimer in
         the documentation and/or other materials provided with the
         distribution.
       * Neither the name of Galois, Inc. nor the names of its contributors
         may be used to endorse or promote products derived from this
         software without specific prior written permission.
     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
     TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
     PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
     OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     */
     double a = 0.0;
     int e = 0;
     int c;
     while ((c = *String++) != '\0' && isdigit(c))
     {
         a = a * 10.0 + (c - '0');
     }
     if (c == '.')
     {
         while ((c = *String++) != '\0' && isdigit(c))
         {
             a = a * 10.0 + (c - '0');
             e = e - 1;
         }
     }
     if (c == 'e' || c == 'E')
     {
         int sign = 1;
         int i = 0;
         c = *String++;
         if (c == '+')
             c = *String++;
         else if (c == '-')
         {
             c = *String++;
             sign = -1;
         }
         while (isdigit(c))
         {
             i = i * 10 + (c - '0');
             c = *String++;
         }
         e += i * sign;
     }
     while (e > 0)
     {
         a *= 10.0;
         e--;
     }
     while (e < 0)
     {
         a *= 0.1;
         e++;
     }
     return a;
 }
References c, i, and isdigit().
Referenced by bootchartd_main(), compare_keys(), scriptreplay_main(), and SetVariable().
atoi()
int atoi (const char * String)
Definition at line 540 of file Convert.cpp.
 {
     uint64_t Length = strlen((char *)String);
     int OutBuffer = 0;
     int Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (String[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References i, Length, and strlen().
Referenced by _rl_get_screen_size(), action_compat(), bb_dump_add(), bb_dump_size(), chat_main(), cmd_kill(), compare_keys(), complete_get_screenwidth(), conf_choice(), D_DoomMain(), D_StartNetGame(), decode(), default_columns(), download_one_url(), ecvt(), evalcommand(), fbsplash_main(), G_RecordDemo(), get_linux_version_code(), get_old_name(), get_uid_gid(), getjob(), head_builtin(), I_InitGraphics(), I_ZoneBase(), init(), init_wsize(), j_infobox(), j_inputbox(), j_menu(), j_msgbox(), j_radiolist(), j_textbox(), j_yesno(), main(), number(), parse_conf(), ParseConfig(), ParseLine(), patch_main(), popmaildir_main(), preadfd(), read_command(), readtoken1(), rewrite(), sendmail_main(), smtp_checkp(), sv_compquery(), sv_compwidth(), sv_dispprefix(), sv_histsize(), sv_ignoreeof(), sv_opterr(), sv_optind(), sv_seqtimeout(), tgetnum(), CrashHandler::UserInput(), varvalue(), version_compare(), and wh_helper().
backspace()
void backspace (char s[])
Definition at line 38 of file Convert.cpp.
 {
     int len = s_cst(int, strlen(s));
     s[len - 1] = '\0';
 }
References len, s, and strlen().
clamp()
double clamp (double x, double low, double high)
Definition at line 377 of file Convert.cpp.
 {
     if (x < low)
         return low;
     else if (x > high)
         return high;
     else
         return x;
 }
References x.
Referenced by smoothstep().
cubicInterpolate()
float cubicInterpolate (float a, float b, float t)
Definition at line 401 of file Convert.cpp.
 {
     float t2 = t * t;
     float t3 = t2 * t;
     return a + (-2 * t3 + 3 * t2) * b;
 }
References t, t2, and t3.
isalpha()
int isalpha (int c)
Definition at line 165 of file Convert.cpp.
 {
     return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
 }
References c.
isdelim()
unsigned int isdelim (char c, const char * delim)
Definition at line 328 of file Convert.cpp.
 {
     while (*delim != '\0')
     {
         if (c == *delim)
             return 1;
         delim++;
     }
     return 0;
 }
References c.
Referenced by strtok().
isdigit()
int isdigit (int c)
Definition at line 305 of file Convert.cpp.
 {
     return c >= '0' && c <= '9';
 }
References c.
isempty()
int isempty (char * str)
Definition at line 315 of file Convert.cpp.
 {
     if (strlen(str) == 0)
         return 1;
     while (*str != '\0')
     {
         if (!isspace(*str))
             return 0;
         str++;
     }
     return 1;
 }
References isspace(), str, and strlen().
Referenced by VirtualFileSystem::Virtual::Create(), VirtualFileSystem::Virtual::Delete(), VirtualFileSystem::Virtual::Mount(), VirtualFileSystem::Virtual::PathExists(), and VirtualFileSystem::USTAR::ReadArchive().
isspace()
int isspace (int c)
Definition at line 310 of file Convert.cpp.
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f' || c == '\v';
 }
References c.
isupper()
int isupper (int c)
Definition at line 170 of file Convert.cpp.
 {
     return (c >= 'A' && c <= 'Z');
 }
References c.
itoa()
char* itoa (int Value, char * Buffer, int Base)
Definition at line 635 of file Convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     int n = s_cst(int, abs(Value));
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), i, n, and reverse().
lerp()
float lerp (float a, float b, float t)
Definition at line 387 of file Convert.cpp.
 {
     return (1 - t) * a + t * b;
 }
References t.
Referenced by smoothstep().
log2()
int log2 (unsigned int n)
Definition at line 716 of file Convert.cpp.
 {
     if (n == 0)
     {
         error("log2(0) is undefined.");
         return -1;
     }
     int log = 0;
     if ((n & 0xFFFF0000) != 0)
     {
         n >>= 16;
         log = 16;
     }
     if (n >= 256)
     {
         n >>= 8;
         log += 8;
     }
     if (n >= 16)
     {
         n >>= 4;
         log += 4;
     }
     if (n >= 4)
     {
         n >>= 2;
         log += 2;
     }
     return log + (n >> 1);
 }
References error, log, and n.
ltoa()
char* ltoa (long Value, char * Buffer, int Base)
Definition at line 663 of file Convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     long n = abs(Value);
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), i, n, and reverse().
memcmp()
int memcmp (const void * vl, const void * vr, size_t n)
Definition at line 30 of file Convert.cpp.
 {
     const unsigned char *l = (unsigned char *)vl, *r = (unsigned char *)vr;
     for (; n && *l == *r; n--, l++, r++)
         ;
     return n ? *l - *r : 0;
 }
References l, and n.
Referenced by __crypt_blowfish(), __crypt_md5(), __crypt_sha256(), __crypt_sha512(), __dls3(), __mkostemps(), __res_msend_rc(), _rl_move_cursor_relative(), argstr(), arpping(), bcmp(), chat_main(), check_magic(), clear_leases(), common_traceroute_main(), conf_read_simple(), do_newlocale(), do_syslogd(), do_tzset(), dolisten(), ACPI::DSDT::DSDT(), Disk::Manager::FetchDisks(), find_key_in_der_cert(), find_lease_by_mac(), findString(), flashcp_main(), get(), get_header_tar(), get_static_nip_by_mac(), getnameinfo(), handle_port(), inet_addr_match(), inet_ntop(), is_defined_config(), match(), mkdtemp(), mktemp(), nameif_main(), nbdclient_main(), netlink_msg_to_nameindex(), parse_args(), parse_config_file(), policyof(), print_addrinfo(), pthread_setattr_default_np(), VirtualFileSystem::USTAR::ReadArchive(), recv_pack(), reread_config_file(), reverse_hosts(), strrcmp(), stty_main(), sym_calc_value(), VirtualFileSystem::USTAR::TestArchive(), tls_handshake(), twoway_memmem(), twoway_strstr(), udhcpc_main(), update_line(), volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_exfat(), volume_id_probe_hpfs(), volume_id_probe_intel_software_raid(), volume_id_probe_iso9660(), volume_id_probe_jfs(), volume_id_probe_lfs(), volume_id_probe_linux_swap(), volume_id_probe_lsi_mega_raid(), volume_id_probe_luks(), volume_id_probe_lvm2(), volume_id_probe_mac_partition_map(), volume_id_probe_ntfs(), volume_id_probe_nvidia_raid(), volume_id_probe_ocfs2(), volume_id_probe_promise_fasttrack_raid(), volume_id_probe_reiserfs(), volume_id_probe_romfs(), volume_id_probe_udf(), volume_id_probe_vfat(), volume_id_probe_xfs(), write_block(), and xmalloc_fgets_internal().
memcpy_sse()
void* memcpy_sse (void * dest, const void * src, size_t n)
Definition at line 30 of file MemoryCopySIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     const char *s = (const char *)src;
     if ((((uintptr_t)d | (uintptr_t)s) & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movaps (%0), %%xmm0\n"
                  "movaps %%xmm0, (%1)\n"
                  :
                  : "r"(s), "r"(d)
                  : "xmm0");
             d += 16;
             s += 16;
         }
         n -= num_vectors * 16;
     }
     memcpy_unsafe(d, s, n);
 #endif // defined(a64)
     return dest;
 }
References asmv(), i, memcpy_unsafe(), n, s, and src.
Referenced by __memcpy_chk().
memcpy_sse2()
void* memcpy_sse2 (void * dest, const void * src, size_t n)
Definition at line 57 of file MemoryCopySIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     const char *s = (const char *)src;
     if ((((uintptr_t)d | (uintptr_t)s) & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movdqa (%0), %%xmm0\n"
                  "movdqa %%xmm0, (%1)\n"
                  :
                  : "r"(s), "r"(d)
                  : "xmm0");
             d += 16;
             s += 16;
         }
         n -= num_vectors * 16;
     }
     memcpy_unsafe(d, s, n);
 #endif // defined(a64)
     return dest;
 }
References asmv(), i, memcpy_unsafe(), n, s, and src.
Referenced by __memcpy_chk().
memcpy_sse3()
void* memcpy_sse3 (void * dest, const void * src, size_t n)
Definition at line 84 of file MemoryCopySIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     const char *s = (const char *)src;
     if ((((uintptr_t)d | (uintptr_t)s) & 0x7) == 0)
     {
         size_t num_vectors = n / 8;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movq (%0), %%xmm0\n"
                  "movddup %%xmm0, %%xmm1\n"
                  "movq %%xmm1, (%1)\n"
                  :
                  : "r"(s), "r"(d)
                  : "xmm0", "xmm1");
             d += 8;
             s += 8;
         }
         n -= num_vectors * 8;
     }
     memcpy_unsafe(d, s, n);
 #endif // defined(a64)
     return dest;
 }
References asmv(), i, memcpy_unsafe(), n, s, and src.
Referenced by __memcpy_chk().
memcpy_sse4_1()
void* memcpy_sse4_1 (void * dest, const void * src, size_t n)
Definition at line 141 of file MemoryCopySIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     const char *s = (const char *)src;
     if ((((uintptr_t)d | (uintptr_t)s) & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             // movntdqa
             asmv("movdqa (%0), %%xmm0\n"
                  "movdqa %%xmm0, (%1)\n"
                  :
                  : "r"(s), "r"(d)
                  : "xmm0");
             d += 16;
             s += 16;
         }
         n -= num_vectors * 16;
     }
     memcpy_unsafe(d, s, n);
 #endif // defined(a64)
     return dest;
 }
References asmv(), i, memcpy_unsafe(), n, s, and src.
Referenced by __memcpy_chk().
memcpy_sse4_2()
void* memcpy_sse4_2 (void * dest, const void * src, size_t n)
Definition at line 169 of file MemoryCopySIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     const char *s = (const char *)src;
     if ((((uintptr_t)d | (uintptr_t)s) & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movdqa (%0), %%xmm0\n"
                  "pcmpistri $0, (%0), %%xmm0\n"
                  "movdqa %%xmm0, (%1)\n"
                  :
                  : "r"(s), "r"(d)
                  : "xmm0");
             d += 16;
             s += 16;
         }
         n -= num_vectors * 16;
     }
     memcpy_unsafe(d, s, n);
 #endif // defined(a64)
     return dest;
 }
References asmv(), i, memcpy_unsafe(), n, s, and src.
Referenced by __memcpy_chk().
memcpy_ssse3()
void* memcpy_ssse3 (void * dest, const void * src, size_t n)
Definition at line 112 of file MemoryCopySIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     const char *s = (const char *)src;
     if ((((uintptr_t)d | (uintptr_t)s) & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movdqa (%0), %%xmm0\n"
                  "movdqa 16(%0), %%xmm1\n"
                  "palignr $8, %%xmm0, %%xmm1\n"
                  "movdqa %%xmm1, (%1)\n"
                  :
                  : "r"(s), "r"(d)
                  : "xmm0", "xmm1");
             d += 16;
             s += 16;
         }
         n -= num_vectors * 16;
     }
     memcpy_unsafe(d, s, n);
 #endif // defined(a64)
     return dest;
 }
References asmv(), i, memcpy_unsafe(), n, s, and src.
Referenced by __memcpy_chk().
memcpy_unsafe()
void* memcpy_unsafe (void * dest, const void * src, size_t n)
Definition at line 35 of file MemOp.c.
 {
     unsigned char *d = dest;
     const unsigned char *s = src;
 #ifdef __GNUC__
 #if __BYTE_ORDER == __LITTLE_ENDIAN
 #define LS >>
 #define RS <<
 #else
 #define LS <<
 #define RS >>
 #endif
     typedef uint32_t __attribute__((__may_alias__)) u32;
     uint32_t w, x;
     for (; (uintptr_t)s % 4 && n; n--)
         *d++ = *s++;
     if ((uintptr_t)d % 4 == 0)
     {
         for (; n >= 16; s += 16, d += 16, n -= 16)
         {
             *(u32 *)(d + 0) = *(u32 *)(s + 0);
             *(u32 *)(d + 4) = *(u32 *)(s + 4);
             *(u32 *)(d + 8) = *(u32 *)(s + 8);
             *(u32 *)(d + 12) = *(u32 *)(s + 12);
         }
         if (n & 8)
         {
             *(u32 *)(d + 0) = *(u32 *)(s + 0);
             *(u32 *)(d + 4) = *(u32 *)(s + 4);
             d += 8;
             s += 8;
         }
         if (n & 4)
         {
             *(u32 *)(d + 0) = *(u32 *)(s + 0);
             d += 4;
             s += 4;
         }
         if (n & 2)
         {
             *d++ = *s++;
             *d++ = *s++;
         }
         if (n & 1)
         {
             *d = *s;
         }
         return dest;
     }
     if (n >= 32)
     {
         switch ((uintptr_t)d % 4)
         {
         case 1:
         {
             w = *(u32 *)s;
             *d++ = *s++;
             *d++ = *s++;
             *d++ = *s++;
             n -= 3;
             for (; n >= 17; s += 16, d += 16, n -= 16)
             {
                 x = *(u32 *)(s + 1);
                 *(u32 *)(d + 0) = (w LS 24) | (x RS 8);
                 w = *(u32 *)(s + 5);
                 *(u32 *)(d + 4) = (x LS 24) | (w RS 8);
                 x = *(u32 *)(s + 9);
                 *(u32 *)(d + 8) = (w LS 24) | (x RS 8);
                 w = *(u32 *)(s + 13);
                 *(u32 *)(d + 12) = (x LS 24) | (w RS 8);
             }
             break;
         }
         case 2:
         {
             w = *(u32 *)s;
             *d++ = *s++;
             *d++ = *s++;
             n -= 2;
             for (; n >= 18; s += 16, d += 16, n -= 16)
             {
                 x = *(u32 *)(s + 2);
                 *(u32 *)(d + 0) = (w LS 16) | (x RS 16);
                 w = *(u32 *)(s + 6);
                 *(u32 *)(d + 4) = (x LS 16) | (w RS 16);
                 x = *(u32 *)(s + 10);
                 *(u32 *)(d + 8) = (w LS 16) | (x RS 16);
                 w = *(u32 *)(s + 14);
                 *(u32 *)(d + 12) = (x LS 16) | (w RS 16);
             }
             break;
         }
         case 3:
         {
             w = *(u32 *)s;
             *d++ = *s++;
             n -= 1;
             for (; n >= 19; s += 16, d += 16, n -= 16)
             {
                 x = *(u32 *)(s + 3);
                 *(u32 *)(d + 0) = (w LS 8) | (x RS 24);
                 w = *(u32 *)(s + 7);
                 *(u32 *)(d + 4) = (x LS 8) | (w RS 24);
                 x = *(u32 *)(s + 11);
                 *(u32 *)(d + 8) = (w LS 8) | (x RS 24);
                 w = *(u32 *)(s + 15);
                 *(u32 *)(d + 12) = (x LS 8) | (w RS 24);
             }
             break;
         }
         default:
             break;
         }
     }
     if (n & 16)
     {
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
     }
     if (n & 8)
     {
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
     }
     if (n & 4)
     {
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
         *d++ = *s++;
     }
     if (n & 2)
     {
         *d++ = *s++;
         *d++ = *s++;
     }
     if (n & 1)
     {
         *d = *s;
     }
     return dest;
 #endif
     for (; n; n--)
         *d++ = *s++;
     return dest;
 }
References __attribute__, n, RS, s, src, w, and x.
Referenced by __memcpy_chk(), memcpy_sse(), memcpy_sse2(), memcpy_sse3(), memcpy_sse4_1(), memcpy_sse4_2(), and memcpy_ssse3().
memmove_sse()
void* memmove_sse (void * dest, const void * src, size_t n)
Definition at line 32 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe(), n, and src.
Referenced by __memmove_chk().
memmove_sse2()
void* memmove_sse2 (void * dest, const void * src, size_t n)
Definition at line 37 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe(), n, and src.
Referenced by __memmove_chk().
memmove_sse3()
void* memmove_sse3 (void * dest, const void * src, size_t n)
Definition at line 42 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe(), n, and src.
Referenced by __memmove_chk().
memmove_sse4_1()
void* memmove_sse4_1 (void * dest, const void * src, size_t n)
Definition at line 52 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe(), n, and src.
Referenced by __memmove_chk().
memmove_sse4_2()
void* memmove_sse4_2 (void * dest, const void * src, size_t n)
Definition at line 57 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe(), n, and src.
Referenced by __memmove_chk().
memmove_ssse3()
void* memmove_ssse3 (void * dest, const void * src, size_t n)
Definition at line 47 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe(), n, and src.
Referenced by __memmove_chk().
memmove_unsafe()
void* memmove_unsafe (void * dest, const void * src, size_t n)
Definition at line 295 of file MemOp.c.
 {
 #ifdef __GNUC__
     typedef __attribute__((__may_alias__)) size_t WT;
 #define WS (sizeof(WT))
 #endif
     char *d = dest;
     const char *s = src;
     if (d == s)
         return d;
     if ((uintptr_t)s - (uintptr_t)d - n <= -2 * n)
         return memcpy(d, s, n);
     if (d < s)
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)d % WS)
             {
                 if (!n--)
                     return dest;
                 *d++ = *s++;
             }
             for (; n >= WS; n -= WS, d += WS, s += WS)
                 *(WT *)d = *(WT *)s;
         }
 #endif
         for (; n; n--)
             *d++ = *s++;
     }
     else
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)(d + n) % WS)
             {
                 if (!n--)
                     return dest;
                 d[n] = s[n];
             }
             while (n >= WS)
                 n -= WS, *(WT *)(d + n) = *(WT *)(s + n);
         }
 #endif
         while (n)
             n--, d[n] = s[n];
     }
     return dest;
 }
References __attribute__, memcpy, n, s, and src.
Referenced by __memmove_chk(), memmove_sse(), memmove_sse2(), memmove_sse3(), memmove_sse4_1(), memmove_sse4_2(), and memmove_ssse3().
memset_sse()
void* memset_sse (void * dest, int c, size_t n)
Definition at line 32 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References c, memset_unsafe(), and n.
Referenced by __memset_chk().
memset_sse2()
void* memset_sse2 (void * dest, int c, size_t n)
Definition at line 37 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References c, memset_unsafe(), and n.
Referenced by __memset_chk().
memset_sse3()
void* memset_sse3 (void * dest, int c, size_t n)
Definition at line 42 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References c, memset_unsafe(), and n.
Referenced by __memset_chk().
memset_sse4_1()
void* memset_sse4_1 (void * dest, int c, size_t n)
Definition at line 52 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References c, memset_unsafe(), and n.
Referenced by __memset_chk().
memset_sse4_2()
void* memset_sse4_2 (void * dest, int c, size_t n)
Definition at line 57 of file MemorySetSIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     if (((uintptr_t)d & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movd %0, %%xmm0\n"
                  "pshufd $0, %%xmm0, %%xmm0\n"
                  "movdqa %%xmm0, (%1)\n"
                  :
                  : "r"(c), "r"(d)
                  : "xmm0");
             d += 16;
         }
         n -= num_vectors * 16;
     }
     memset_unsafe(d, c, n);
 #endif
     return dest;
 }
References asmv(), c, i, memset_unsafe(), and n.
Referenced by __memset_chk().
memset_ssse3()
void* memset_ssse3 (void * dest, int c, size_t n)
Definition at line 47 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References c, memset_unsafe(), and n.
Referenced by __memset_chk().
memset_unsafe()
void* memset_unsafe (void * dest, int c, size_t n)
Definition at line 214 of file MemOp.c.
 {
     unsigned char *s = dest;
     size_t k;
     if (!n)
         return dest;
     s[0] = c;
     s[n - 1] = c;
     if (n <= 2)
         return dest;
     s[1] = c;
     s[2] = c;
     s[n - 2] = c;
     s[n - 3] = c;
     if (n <= 6)
         return dest;
     s[3] = c;
     s[n - 4] = c;
     if (n <= 8)
         return dest;
     k = -(uintptr_t)s & 3;
     s += k;
     n -= k;
     n &= -4;
 #ifdef __GNUC__
     typedef uint32_t __attribute__((__may_alias__)) u32;
     typedef uint64_t __attribute__((__may_alias__)) u64;
     u32 c32 = ((u32)-1) / 255 * (unsigned char)c;
     *(u32 *)(s + 0) = c32;
     *(u32 *)(s + n - 4) = c32;
     if (n <= 8)
         return dest;
     *(u32 *)(s + 4) = c32;
     *(u32 *)(s + 8) = c32;
     *(u32 *)(s + n - 12) = c32;
     *(u32 *)(s + n - 8) = c32;
     if (n <= 24)
         return dest;
     *(u32 *)(s + 12) = c32;
     *(u32 *)(s + 16) = c32;
     *(u32 *)(s + 20) = c32;
     *(u32 *)(s + 24) = c32;
     *(u32 *)(s + n - 28) = c32;
     *(u32 *)(s + n - 24) = c32;
     *(u32 *)(s + n - 20) = c32;
     *(u32 *)(s + n - 16) = c32;
     k = 24 + ((uintptr_t)s & 4);
     s += k;
     n -= k;
     u64 c64 = c32 | ((u64)c32 << 32);
     for (; n >= 32; n -= 32, s += 32)
     {
         *(u64 *)(s + 0) = c64;
         *(u64 *)(s + 8) = c64;
         *(u64 *)(s + 16) = c64;
         *(u64 *)(s + 24) = c64;
     }
 #else
     for (; n; n--, s++)
         *s = c;
 #endif
     return dest;
 }
References __attribute__, c, k, n, and s.
Referenced by __memset_chk(), memset_sse(), memset_sse2(), memset_sse3(), memset_sse4_1(), memset_sse4_2(), and memset_ssse3().
reverse()
char* reverse (char * Buffer, int i, int j)
Definition at line 348 of file Convert.cpp.
 {
     while (i < j)
         swap(&Buffer[i++], &Buffer[j--]);
     return Buffer;
 }
References i, j, and swap().
Referenced by apply_one_hunk(), history_search_internal(), and patch_main().
smoothstep()
float smoothstep (float a, float b, float t)
Definition at line 392 of file Convert.cpp.
 {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wfloat-conversion"
     t = clamp(s_cst(double, t), 0.0, 1.0);
 #pragma GCC diagnostic pop
     return lerp(a, b, t * t * (3 - 2 * t));
 }
References clamp(), lerp(), and t.
sqrtf()
float sqrtf (float x)
Definition at line 355 of file Convert.cpp.
 {
     if (x < 0.0f)
         return NAN;
     if (x < 1e-7f)
         return 0.0f;
     float guess = x / 2.0f;
     for (short i = 0; i < 10; i++)
     {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wfloat-equal"
         if (guess == 0.0f)
             return 0.0f;
 #pragma GCC diagnostic pop
         guess = (guess + x / guess) / 2.0f;
     }
     return guess;
 }
References i, NAN, and x.
Referenced by acosf(), acoshf(), asinhf(), common(), ctanhf(), and hypotf().
strcasecmp()
int strcasecmp (const char * s1, const char * s2)
Definition at line 448 of file Convert.cpp.
 {
     const unsigned char *p1 = (const unsigned char *)s1;
     const unsigned char *p2 = (const unsigned char *)s2;
     int result;
     if (p1 == p2)
         return 0;
     while ((result = std::tolower(*p1) - std::tolower(*p2++)) == 0)
         if (*p1++ == '\0')
             break;
     return result;
 }
References s1, s2, and std::tolower().
strcat_unsafe()
char* strcat_unsafe (char * destination, const char * source)
Definition at line 73 of file Convert.cpp.
 {
     if ((destination == NULL) || (source == NULL))
         return NULL;
     char *start = destination;
     while (*start != '\0')
         start++;
     while (*source != '\0')
         *start++ = *source++;
     *start = '\0';
     return destination;
 }
References NULL, source, and start.
Referenced by __strcat_chk().
strchr()
char* strchr (const char * String, int Char)
Definition at line 148 of file Convert.cpp.
 {
     while (*String != (char)Char)
     {
         if (!*String++)
             return 0;
     }
     return (char *)String;
 }
Referenced by __execvpe(), __fdopen(), __fmodeflags(), __get_resolv_conf(), __getgrent_a(), __getpwent_a(), __lookup_ipliteral(), __lookup_serv(), __parsespent(), _nl_explode_name(), _nl_init_domain_conv(), _rl_find_completion_word(), _rl_isearch_dispatch(), a64l(), add_cmd_block(), add_links(), add_MANPATH(), add_split_dependencies(), append_mount_options(), argz_next__(), awk_getline(), awk_main(), awk_printf(), bb_dump_size(), bb_unsetenv(), bpad(), builtin_arrayref_flags(), builtin_source(), cag_option_find_by_letter(), catopen(), char_insert(), chmod_main(), chpasswd_main(), cmdio_get_cmd_and_arg(), compile_fs_type(), conf_expand_value(), conf_read_simple(), config_read(), ConvertFileFlags(), create_fs_device(), data_extract_all(), date_main(), dcngettext(), dd_main(), decode_one_format(), decode_prompt_string(), dequote_escapes(), dequote_string(), dialog_menu(), display_single(), do_cmd(), do_glob(), do_logging(), do_tunnels_list(), do_tzset(), dsvsplit(), dump_procs(), edir(), edit_file(), encode_string(), encode_then_append_var_plusminus(), env_main(), escape(), EscapeShellString(), evalvar(), execute_intern_function(), expand_on_ifs(), expand_one_var(), expand_string_to_string(), expand_vars_to_list(), exportcmd(), extract_dollar_brace_string(), extract_filename(), extract_heredoc_dolbrace_string(), find_command(), find_dot_file(), find_executable(), find_pair(), find_range(), first_alpha(), fix_assignment_words(), fixup_rpath(), fmemopen(), fmt_num(), fmt_url(), fmtmsg(), fopen(), fopencookie(), fsck_device(), fsck_main(), fstype_matches(), generate_output(), get_addr_1(), get_flag(), get_irqs_from_interrupts(), get_linux_version_code(), get_modinfo_value(), get_prefix_1(), get_rt_realms(), get_uidgid(), get_username_or_die(), getmntent_r(), getNum(), getprec(), getspnam_r(), getsubopt(), handle_incoming_and_exit(), hasmeta(), hexdump_main(), hush_main(), ifconfig_main(), ifplugd_main(), ifsbreakup(), ifupdown_main(), index(), INET_setroute(), init(), inotifyd_main(), internal_getopt(), iprule_modify(), ll_addr_a2n(), load_library(), locale_charset(), logdir_open(), lpd_main(), lpqr_main(), lsscsi_main(), main(), make_here_document(), make_path(), make_quoted_replacement(), man_main(), match_opt(), mbschr(), md5_sha1_sum_main(), mklocal(), mknod_main(), name_from_hosts(), name_to_dev_t(), nfsmount(), nmeter_main(), ntp_init(), o_addqchr(), o_addQchr(), obscure_msg(), od_main(), only_changed_user(), parse(), parse_and_add_kcmdline_module_options(), parse_args(), parse_chown_usergroup_or_die(), parse_conf(), parse_datestr(), parse_dollar(), parse_matched_pair(), parse_meminfo(), parse_mount_options(), parse_one_line(), parse_stream(), parse_url(), ParseDMXConfig(), pid_is_name(), plural_lookup(), popen(), popen_ls(), popmaildir_main(), print_autowrap(), print_direc(), print_formatted(), process_config_line(), process_files(), process_includes(), process_irq_counts(), process_timer_stats(), procps_scan(), pseudo_exec_argv(), read_after_slash(), read_alias_file(), read_token_word(), readtoken1(), remove_quoted_nulls(), renice_main(), rescan_crontab_dir(), reverse_hosts(), reverse_services(), rewrite(), rl_alphabetic(), run_pipe(), sane_address(), scan_request(), sendmail_main(), set_local_var(), set_vars_and_save_old(), sh_getopt(), shell_builtin_read(), shellexec(), show_shell_usage(), shuf_main(), singlemount(), sleep_builtin(), sockaddr2str(), sort_main(), stat_char(), str2sockaddr(), strcreplace(), strftime(), strip_ipv6_scope_id(), strstr(), subCommand(), subevalvar(), sysctl_act_on_setting(), sysctl_act_recursive(), tar_main(), targp_parse(), tilde_expand(), udhcp_str2optset(), uevent_main(), update_passwd(), validate_path(), version_compare(), vi_change_dispatch(), vi_delete_dispatch(), vi_yank_dispatch(), which_main(), and xxreadtoken().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 123 of file Convert.cpp.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
References l.
strcpy_unsafe()
char* strcpy_unsafe (char * destination, const char * source)
Definition at line 89 of file Convert.cpp.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source != '\0')
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
References NULL, and source.
Referenced by __strcpy_chk().
strdup()
char* strdup (const char * String)
Definition at line 158 of file Convert.cpp.
 {
     char *OutBuffer = (char *)kmalloc(strlen((char *)String) + 1);
     strncpy(OutBuffer, String, strlen(String) + 1);
     return OutBuffer;
 }
References kmalloc, strlen(), and strncpy().
Referenced by _nl_find_domain(), add_new_file(), add_new_symbol(), CheckDirectoryHasIWAD(), conf_read_simple(), D_FindWADByName(), file_lookup(), get_current_dir_name(), getcwd(), glob(), if(), M_GetSaveGameDir(), M_StringDuplicate(), main(), message__new(), mitos(), ParseLine(), process_includes(), realpath(), set_binding_values(), SetVariable(), sym_lookup(), sym_validate_range(), tempnam(), vasprintf(), wstrdup(), and xstrdup().
strlen()
long unsigned strlen (const char s[])
Definition at line 64 of file Convert.cpp.
 {
     long unsigned i = 0;
     if (s)
         while (s[i] != '\0')
             ++i;
     return i;
 }
References i, and s.
Referenced by __attribute__(), __dls3(), __get_resolv_conf(), __getopt_long_core(), __getopt_msg(), __lookup_serv(), __mkostemps(), NetworkDHCP::__no_sanitize(), SymbolResolver::__no_sanitize(), Tasking::__no_sanitize(), __nscd_query(), __strcat_chk(), __strchrnul(), __strcpy_chk(), __strftime_fmt_1(), __strxfrm_l(), _evalfile(), _hs_append_history_line(), _hs_history_patsearch(), _nl_find_domain(), _nl_find_msg(), _nl_init_domain_conv(), _nl_load_domain(), _nl_log_untranslated(), _nl_make_l10nflist(), _remove_directory(), _rl_copy_to_kill_ring(), _rl_custom_readline_prefix(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_isearch_init(), _rl_macro_dumper_internal(), _rl_make_prompt_for_search(), _rl_print_color_indicator(), _rl_reset_region_color(), _rl_savestring(), _rl_strindex(), _rl_untranslate_macro_value(), _rl_vi_replace_insert(), acpid_main(), add_cmd(), add_exclude(), add_links(), add_peers(), add_symbols_from(), add_to_ino_dev_hashtable(), VirtualFileSystem::Virtual::AddNewChild(), adjtimex_main(), alrm_catcher(), ansic_quote(), append(), argz_count__(), argz_stringify__(), atof(), atoi(), awk_printf(), awk_split(), awk_sub(), backspace(), basename(), basename_builtin(), basename_main(), bb_verror_msg(), bbunpack(), buffer_pwrite(), builtin_arrayref_flags(), builtin_eval(), cag_option_get_print_indention(), cal_main(), calcsize(), cat_main(), catopen(), center(), change_to_size(), chat_main(), chcon_main(), check_existence_through_netlink(), cht_CheckCheat(), cmdlookup(), colon(), comm_match(), command_generator(), compare_keys(), compute_lcd_of_matches(), conf_choice(), conf_get_default_confname(), conf_read_simple(), conf_string(), convert_dname(), convert_to_struct(), count_strstr(), cprintf(), create_links_from_list(), csvsplit(), cut_file(), cut_out_ull_opt(), cutbytes(), cutchars(), cwk_path_change_extension(), cwk_path_change_root(), cwk_path_change_segment(), cwk_path_output(), data_extract_all_prefix(), dbg_print_flags(), dcngettext(), de_backslash(), decode_prompt_string(), dequote_escapes(), dialog_checklist(), dialog_inputbox(), die(), DirIsFile(), dirname(), dirname_builtin(), dirspell(), dname_dec(), do_add_or_delete(), do_cmd(), do_glob(), do_nftw(), do_redirection_internal(), do_set(), do_sethostname(), do_tzset(), download_one_url(), DriverDisplayPrint(), dsvsplit(), dupstr(), echo_main(), escape(), escape_input(), escape_text(), EscapeShellString(), eval6(), evaluate(), evaluate_string(), exec_builtin(), exec_kernel_doc(), expand_arith_string(), expand_one_var(), expand_prompt(), expand_string_dollar_quote(), expand_string_if_necessary(), expand_variable(), expand_word_internal(), exponent(), expr_print_file_helper(), extract_colon_unit(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), F_Ticker(), fcopy(), fileAction(), fill_package_struct(), filter_rename_config(), find_block_device_in_dir(), find_charmap(), find_codeset(), find_export_symbols(), find_user_command_in_path(), find_user_command_internal(), finish_oldfile(), first_alpha(), fixup_rpath(), floating(), fmt_str(), fnprint(), fnwidth(), fputs(), full_write1_str(), full_write2_str(), G_RecordDemo(), gather_options_str(), get_bash_name(), get_charset_aliases(), get_input_line(), get_local_var_value(), get_mode(), get_modinfo_value(), get_node(), get_tmpdir(), getaddrinfo(), getdomainname(), getenv(), GetGameName(), gethostbyname2_r(), getlogin_r(), getmntent_r(), getnameinfo(), VirtualFileSystem::Virtual::GetPathFromNode(), getprotoent(), getspnam_r(), getsubopt(), glob(), glob_dir_to_array(), glob_filename(), glob_vector(), glue_prefix_and_suffix(), grep_file(), groupnum(), handle_dir_common(), handle_incoming_and_exit(), handle_special(), hash_find(), hash_remove(), history_arg_extract(), history_backupfile(), history_do_write(), history_expand(), history_expand_internal(), history_filename(), history_search_internal(), history_tempfile(), hush_main(), I_Error(), I_PrintBanner(), if(), if_redefined(), ife_print(), index_in_strings_case_insensitive(), index_in_substrings(), indirection_level_string(), inet_ntop(), INET_rresolve(), init_exec(), init_main(), initialize_shell_variables(), initialize_siglist(), InitLimineAfterStack(), insert_match(), ipaddr_modify(), iprule_modify(), is_prefixed_with(), is_section_name(), is_suffixed_with(), is_whole_disk(), isempty(), isolate_tilde_prefix(), kill_main(), kw_lookup(), list_table(), ll_proto_a2n(), ll_type_n2a(), load_library(), LoadDefaultCollection(), locale_charset(), log_locally(), logger_main(), logmatch(), logread_main(), lpqr_main(), lsmod_main(), M_Drawer(), M_ExtractFileBase(), M_SaveSelect(), M_StrCaseStr(), M_StringConcat(), M_StringCopy(), M_StringDuplicate(), M_StringEndsWith(), M_StringHeight(), M_StringJoin(), M_StringReplace(), M_StringStartsWith(), M_StringWidth(), mailstat(), main(), make_all_argv_opts(), make_default_mailpath(), make_device(), make_hash(), make_here_document(), make_redirection(), make_tempdir(), make_word_flags(), match(), mbschr(), mbsrtowcs(), md5_crypt(), md5String(), mk_env_string(), mkdirpath(), mkdtemp(), mktemp(), modinfo(), mount_it_now(), multiboot_main(), name_from_hosts(), named_function_string(), nbdclient_main(), new_get_kernel_symbols(), new_init_action(), next_file(), nftw(), nl_main(), nmeter_main(), nodeckstrdup(), noninc_dosearch(), normalize(), VirtualFileSystem::Virtual::NormalizePath(), nproc_main(), number(), o_addQstr(), o_addstr(), o_addstr_with_NUL(), obj_elf_hash(), obj_load_order_prio(), obj_string_patch(), obscure_msg(), openhere(), std::string::operator=(), opt_in_list(), P_SaveGameFile(), padvance_magic(), param_expand(), parameter_brace_expand(), parameter_brace_expand_word(), parse(), parse_cmd_args(), parse_common(), parse_compound_assignment(), parse_comsub(), parse_conf(), parse_conf_file(), parse_escapes(), parse_group(), parse_matched_pair(), parse_module(), parse_mount_options(), parse_one_line(), parse_subst_cmd(), ParseConfig(), parser_if(), partname(), pat_subst(), Tasking::PCB::PCB(), perror(), pgrep_main(), phash_search(), pid_is_name(), pointer(), polite_directory_format(), pop3_checkr(), popmaildir_main(), pos_params_assignment(), posix_spawn_file_actions_addchdir_np(), posix_spawn_file_actions_addopen(), prepend_new_eth_table(), prf_hmac_sha256(), print_addrinfo(), print_autowrap(), print_e2flags_long(), print_filename(), print_flags_separated(), print_line(), print_offending_line(), print_title(), printargs(), PrintDehackedBanners(), printstr_base64(), process_config_line(), process_files(), process_packet(), process_stdin(), purge_package(), pushstring(), quote_escapes_internal(), quote_globbing_chars(), quote_string(), quote_string_for_globbing(), quote_string_for_repl(), rdval(), read_alias_file(), read_base64(), read_cmdline(), read_cstate_counts(), read_line_input(), read_lines(), read_token_word(), VirtualFileSystem::USTAR::ReadArchive(), realpath(), redraw_prompt(), regerror(), remove_package(), remove_pattern(), remove_quoted_ifs(), remove_quoted_nulls(), remove_trailing_whitespace(), Tasking::TCB::Rename(), Tasking::PCB::Rename(), std::string::replace(), replace_tempfile(), rev_main(), rl_bind_keyseq_if_unbound_in_map(), rl_complete_internal(), rl_display_match_list(), rl_display_search(), rl_expand_prompt(), rl_filename_completion_function(), rl_function_of_keyseq(), rl_generic_bind(), rl_insert_comment(), rl_insert_text(), rl_invoking_keyseqs_in_map(), rl_macro_bind(), rl_menu_complete(), rl_message(), rl_on_new_line_with_prompt(), rl_parse_and_bind(), rl_quote_filename(), rl_redisplay(), rl_replace_line(), rl_username_completion_function(), rl_vi_yank_pop(), rl_yank_pop(), rmescapes(), rmoldest(), rpm_getstr(), rtc_xopen(), run_pipe(), runsvdir_main(), sanitize_env_if_suid(), savestring(), say(), scan_and_match(), scan_inet_proc_line(), scan_proc_net_or_maps(), scan_request(), scan_troff(), scanright(), searchLines(), send_file_and_exit(), sendmail_main(), seq_main(), service(), set_binding_values(), set_mode(), setenv(), setfattr_main(), setfiles_main(), setinputstring(), setlocale(), setup_heredoc(), setup_ignore_patterns(), setvar(), sh_backslash_quote(), sh_canonpath(), sh_double_quote(), sh_makepath(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), sh_modcase(), sh_physpath(), sh_single_quote(), sh_stat(), sh_strvis(), sh_un_double_quote(), SHA1_UpdateString(), sha_crypt(), shell_builtin_ulimit(), shell_execve(), shell_getc(), shell_ungets(), show_status_line(), show_textbox(), skip_matched_pair(), skip_to_delim(), smtp_checkp(), sort_main(), split_main(), SplitLine(), sstrdup(), st_expr_expand(), stack_putstr(), start_stop_daemon_main(), StartKernelShell(), str_append(), strcasestr(), strcat(), strcreplace(), strdup(), strduplicate(), strerror_r(), strftime(), strftime_builtin(), strgrow(), std::string::string(), string_checker(), string_extract(), string_extract_double_quoted(), string_extract_single_quoted(), string_list_internal(), string_option_to_env(), string_quote_removal(), string_to_llist(), string_transform(), string_var_assignment(), strings(), strip(), stripwhite(), strlcat(), strlcpy(), strmaxcat(), strmaxcpy(), strncat(), strptime(), strrchr(), strrcmp(), strrstr(), strsep(), strsub(), strtodest(), subCommand(), subevalvar(), sv_emacs_modestr(), sv_isrchterm(), sv_vicmd_modestr(), sv_viins_modestr(), sym_re_search(), sym_set_string_value(), sys_kernelctl(), table_lookup(), targp_parse(), Tasking::TCB::TCB(), tcpudpsvd_main(), tempnam(), textdomain(), tgetent(), tilde_expand(), tilde_find_prefix(), tilde_find_suffix(), tparam1(), trim(), trim_pathname(), CrashHandler::TrimWhiteSpace(), udhcp_option_idx(), udhcpc_main(), uevent_main(), unescape(), unicode_strlen(), unquoted_glob_pattern_p(), unzip_main(), update_line(), update_passwd(), updatepwd(), user_command_matches(), CrashHandler::UserInput(), validate_path(), vgetopt32(), volume_id_probe_romfs(), W_AddFile(), wget_main(), write_helpfiles(), write_longdocs(), write_new_utmp(), xargs_main(), xmalloc_fgets_internal(), xmalloc_follow_symlinks(), xmalloc_optname_optval(), xmalloc_realpath_coreutils(), xmalloc_substitute_string(), xrealloc_getcwd_or_warn(), xwrite_str(), and ZenityErrorBox().
strncasecmp()
int strncasecmp (const char * lhs, const char * rhs, long unsigned int Count)
strncmp()
int strncmp (const char * s1, const char * s2, unsigned long n)
Referenced by __dls3(), __get_resolv_conf(), __lookup_serv(), __putenv(), _rl_print_color_indicator(), add_or_supercede_exported_var(), add_split_dependencies(), append_mount_options(), bb_init_module_24(), cag_option_find_by_name(), check_existence_through_netlink(), colon(), comm_match(), command_generator(), complete_fncmp(), compute_lcd_of_matches(), conf_read_simple(), cwk_path_is_string_equal(), D_DoomMain(), dcngettext(), exclude(), extract_filename(), fixup_rpath(), get_local_var_value(), get_modinfo_value(), get_ptr_to_local_var(), getconf_one(), getenv(), getspnam_r(), getstat(), getsubopt(), handle_incoming_and_exit(), index_in_substrings(), is_colored(), is_prefixed_with(), last_main(), load_library(), M_StringReplace(), M_StringStartsWith(), main(), match(), match_opt(), md5crypt(), name_to_dev_t(), next_token(), ntp_init(), parse(), parse_one_line(), patch_main(), path_is_devfd(), polite_directory_format(), process_includes(), rdval_diskstats(), read_cmdline(), reverse_services(), scan_expression(), scan_request(), scan_table(), set_local_var(), sh_stat(), sha256crypt(), sha512crypt(), sha_crypt(), StartKernelShell(), subevalvar(), tilde_find_prefix(), tilde_find_suffix(), tre_tnfa_run_backtrack(), uniq_main(), unsetenv(), CrashHandler::UserInput(), utf8locale(), uuidcache_check_device(), and W_AddFile().
strncpy()
char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 106 of file Convert.cpp.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
References NULL, and source.
Referenced by _rl_get_string_variable_value(), _rl_insert_char(), _rl_vi_callback_change_char(), add_server_options(), VirtualFileSystem::Virtual::AddNewChild(), bash_tilde_find_word(), cal_main(), compute_lcd_of_matches(), decode_prompt_string(), dfallback(), do_print_item(), expand_char(), expand_regexp(), expand_string_dollar_quote(), extract_delimited_string(), extract_heredoc_dolbrace_string(), extract_info(), fakeidentd_main(), fmtulong(), get_history_event(), gethostname(), hist_error(), history_expand(), history_expand_internal(), history_substring(), if_indextoname(), if_nametoindex(), init_main(), InitLimineAfterStack(), M_StringCopy(), main(), make_device(), multiboot_main(), ParseConfig(), pat_subst(), polite_directory_format(), printable_job_status(), rdval_diskstats(), VirtualFileSystem::USTAR::ReadArchive(), rl_change_case(), rl_copy_text(), rl_history_search_reinit(), rl_insert_text(), rl_tilde_expand(), rl_vi_change_char(), safe_strncpy(), scan_request(), sh_modcase(), sh_realpath(), stats_dev_find_or_new(), strmaxcat(), strmaxcpy(), strncpy_IFNAMSIZ(), tilde_expand(), vi_save_insert_buffer(), W_AddFile(), and write_new_utmp().
strrchr()
char* strrchr (const char * String, int Char)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
References c, len, NULL, pos, s, and strlen().
Referenced by angle_address(), base_pathname(), bb_basename(), bb_get_last_path_component_nostrip(), build_alias(), conf_write(), cttyhack_main(), d6_listen_socket(), data_extract_all(), decode_prompt_string(), diff_main(), dolink(), fileAction(), filter_accept_list_reassign(), fixup_rpath(), glob_filename(), glob_name_is_acceptable(), handle_incoming_and_exit(), handle_port(), history_expand_internal(), IdentifyIWADByName(), load_library(), M_GetExecutableName(), main(), make_device(), make_new_name_lzop(), man_main(), match(), mktemp_builtin(), nbdclient_main(), parse_datestr(), parse_one_line(), parse_pasv_epsv(), parse_url(), patch_main(), phash_search(), pid_is_name(), printable_part(), process_includes(), procps_scan(), rindex(), rl_display_match_list(), rl_filename_completion_function(), run_pipe(), scan_request(), send_file_and_exit(), show_manpage(), stat_char(), str2sockaddr(), udhcp_listen_socket(), update_passwd(), version_compare(), and xmalloc_realpath_coreutils().
strstr()
char* strstr (const char * haystack, const char * needle)
Definition at line 131 of file Convert.cpp.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
References NULL.
Referenced by __get_resolv_conf(), __lookup_serv(), _nl_init_domain_conv(), add_links(), awk_getline(), count_strstr(), create_or_remember_link(), cut_out_ull_opt(), DetectByHPET(), dump_procs(), exec_builtin(), find_action(), find_export_symbols(), get_irqs_from_interrupts(), getjob(), grep_file(), handle_incoming_and_exit(), hasmntopt(), index_status_file(), is_hpet_irq(), is_section_name(), M_StringReplace(), main(), make_device(), name_from_hosts(), nmeter_main(), nproc_main(), opt_in_list(), parse_url(), print_direc(), process_includes(), procnetdev_version(), rdval(), read_cstate_counts(), rl_history_search_internal(), scan_request(), scan_table(), send_file_and_exit(), singlemount(), strip_unsafe_prefix(), strrstr(), update_passwd(), wget_main(), write_status_file(), and xmalloc_substitute_string().
strtok()
char* strtok (char * src, const char * delim)
Definition at line 408 of file Convert.cpp.
 {
     static char *src1;
     if (!src)
         src = src1;
     if (!src)
         return NULL;
     while (1)
     {
         if (isdelim(*src, (char *)delim))
         {
             src++;
             continue;
         }
         if (*src == '\0')
             return NULL;
         break;
     }
     char *ret = src;
     while (1)
     {
         if (*src == '\0')
         {
             src1 = src;
             return ret;
         }
         if (isdelim(*src, (char *)delim))
         {
             *src = '\0';
             src1 = src + 1;
             return ret;
         }
         src++;
     }
     return NULL;
 }
References isdelim(), NULL, and src.
Referenced by parseflags(), targp_parse(), and CrashHandler::UserInput().
strtol()
long int strtol (const char * str, char ** endptr, int base)
Definition at line 175 of file Convert.cpp.
 {
     const char *s;
     long acc, cutoff;
     int c;
     int neg, any, cutlim;
     s = str;
     do
     {
         c = *s++;
     } while (isspace(c));
     if (c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else
     {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     cutoff = neg ? LONG_MIN : LONG_MAX;
     cutlim = s_cst(int, cutoff % base);
     cutoff /= base;
     for (acc = 0, any = 0;; c = *s++)
     {
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else
         {
             any = 1;
             acc *= base;
             acc += c;
         }
     }
     if (any < 0)
     {
         acc = neg ? LONG_MIN : LONG_MAX;
     }
     else if (neg)
         acc = -acc;
     if (endptr != 0)
         *endptr = (char *)(any ? s - 1 : str);
     return (acc);
 }
References base, c, isalpha(), isdigit(), isspace(), isupper(), LONG_MAX, LONG_MIN, s, and str.
Referenced by add_cmd(), check_operator(), get_address(), getservbyport_r(), history_get_time(), main(), odoffset(), parse_subst_cmd(), ParseField(), patch_main(), strtod(), strtoimax(), sv_xtracefd(), sym_get_range_val(), sym_string_within_range(), sym_validate_range(), and CrashHandler::UserInput().
strtoul()
unsigned long int strtoul (const char * str, char ** endptr, int base)
Definition at line 240 of file Convert.cpp.
 {
     const char *s;
     unsigned long acc, cutoff;
     int c;
     int neg, any, cutlim;
     s = str;
     do
     {
         c = *s++;
     } while (isspace(c));
     if (c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else
     {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     cutoff = neg ? LONG_MIN : LONG_MAX;
     cutlim = s_cst(int, cutoff % base);
     cutoff /= base;
     for (acc = 0, any = 0;; c = *s++)
     {
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else
         {
             any = 1;
             acc *= base;
             acc += c;
         }
     }
     if (any < 0)
     {
         acc = neg ? LONG_MIN : LONG_MAX;
     }
     else if (neg)
         acc = -acc;
     if (endptr != 0)
         *endptr = (char *)(any ? s - 1 : str);
     return (acc);
 }
References base, c, isalpha(), isdigit(), isspace(), isupper(), LONG_MAX, LONG_MIN, s, and str.
Referenced by __get_resolv_conf(), __inet_aton(), __lookup_serv(), __strftime_l(), bb_parse_mode(), dcngettext(), ether_aton_r(), evalprim(), get_irqs_from_interrupts(), get_mode(), get_qdisc_handle(), get_tc_classid(), get_u16(), get_u32(), get_unsigned(), getservbyname_r(), ifconfig_main(), init_cpu(), klogd_main(), new_process_module_arguments(), parse_meminfo(), process_irq_counts(), read_key(), reverse_services(), rtnl_rtntype_a2n(), sha256crypt(), sha512crypt(), strptime(), strtoumax(), and CrashHandler::UserInput().
swap()
void swap (char * x, char * y)
Definition at line 341 of file Convert.cpp.
 {
     char t = *x;
     *x = *y;
     *y = t;
 }
References t, x, and y.
Referenced by __getgr_a(), __nscd_query(), and getgrouplist().
ultoa()
char* ultoa (unsigned long Value, char * Buffer, int Base)
Definition at line 691 of file Convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     unsigned long n = Value;
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References i, n, and reverse().
wcslen()
size_t wcslen (const wchar_t * s)
Definition at line 461 of file Convert.cpp.
 {
     size_t len = 0;
     while (s[len] != L'\0')
     {
         if (s[++len] == L'\0')
             return len;
         if (s[++len] == L'\0')
             return len;
         if (s[++len] == L'\0')
             return len;
         ++len;
     }
     return len;
 }
References L, len, and s.
Referenced by __wcsxfrm_l(), wcpcpy(), wcscat(), wcschr(), wcscspn(), wcsdup(), wcsncat(), and wcsrchr().
wcsrtombs()
size_t wcsrtombs (char * dst, const wchar_t ** src, size_t len, mbstate_t * ps)
Definition at line 479 of file Convert.cpp.
 {
     UNUSED(ps);
     size_t count = 0;
     while (len > 0)
     {
         wchar_t wc = **src;
         if (wc == L'\0')
             break;
         if (wc < 0x80)
         {
             if (dst)
                 *dst++ = (char)wc;
             count++;
             len--;
         }
         else if (wc < 0x800)
         {
             if (dst)
             {
                 *dst++ = (char)(0xC0 | (wc >> 6));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 2;
             len -= 2;
         }
         else if (wc < 0x10000)
         {
             if (dst)
             {
                 *dst++ = (char)(0xE0 | (wc >> 12));
                 *dst++ = (char)(0x80 | ((wc >> 6) & 0x3F));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 3;
             len -= 3;
         }
         else
         {
             if (dst)
             {
                 *dst++ = (char)(0xF0 | (wc >> 18));
                 *dst++ = (char)(0x80 | ((wc >> 12) & 0x3F));
                 *dst++ = (char)(0x80 | ((wc >> 6) & 0x3F));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 4;
             len -= 4;
         }
         (*src)++;
     }
     if (dst)
         *dst = '\0';
     return count;
 }
References count, dst, L, len, src, and UNUSED.
Referenced by fputws(), remove_pattern(), wcstombs(), and wstring_read().