Fennix: Userspace/apps/base/bash/locale.c File Reference
locale.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "bashintl.h"
#include "bashansi.h"
#include <stdio.h>
#include "chartypes.h"
#include <errno.h>
#include "shell.h"
#include "input.h"
Functions
static int reset_locale_vars PARAMS ((void))
static int locale_isutf8 PARAMS ((char *))
void set_default_locale ()
void set_default_locale_vars ()
int set_locale_var (char *var, char *value)
int set_lang (char *var, char *value)
void set_default_lang ()
char * get_locale_var (char *var)
static int reset_locale_vars ()
static void locale_setblanks ()
static int locale_isutf8 (char *lspec)
int locale_decpoint ()
Variables
int errno
int locale_utf8locale
int locale_mb_cur_max
int locale_shiftstates = 0
int singlequote_translations = 0
int dump_translatable_strings
int dump_po_strings
static char * default_locale
static char * default_domain
static char * default_dir
static char * lc_all
static char * lang
Function Documentation
get_locale_var()
char* get_locale_var (char * var)
Definition at line 339 of file locale.c.
 {
   char *locale;
   locale = lc_all;
   if (locale == 0 || *locale == 0)
     locale = get_string_value (var);    /* XXX - no mem leak */
   if (locale == 0 || *locale == 0)
     locale = lang;
   if (locale == 0 || *locale == 0)
 #if 0
     locale = default_locale;    /* system-dependent; not really portable.  should it be "C"? */
 #else
     locale = "";
 #endif
   return (locale);
 }
References default_locale, get_string_value(), lang, and lc_all.
Referenced by reset_locale_vars(), and set_locale_var().
locale_decpoint()
int locale_decpoint ()
Definition at line 641 of file locale.c.
 {
   return '.';
 }
Referenced by get_epochrealtime(), seq_builtin(), and strtod().
locale_isutf8()
static int locale_isutf8 (char * lspec) static
Definition at line 598 of file locale.c.
 {
   char *cp, *encoding;
 #if HAVE_LANGINFO_CODESET
   cp = nl_langinfo (CODESET);
   return (STREQ (cp, "UTF-8") || STREQ (cp, "utf8"));
 #elif HAVE_LOCALE_CHARSET
   cp = locale_charset ();
   return (STREQ (cp, "UTF-8") || STREQ (cp, "utf8"));
 #else
   /* Take a shot */
   for (cp = lspec; *cp && *cp != '@' && *cp != '+' && *cp != ','; cp++)
     {
       if (*cp == '.')
     {
       for (encoding = ++cp; *cp && *cp != '@' && *cp != '+' && *cp != ','; cp++)
         ;
       /* The encoding (codeset) is the substring between encoding and cp */
       if ((cp - encoding == 5 && STREQN (encoding, "UTF-8", 5)) ||
           (cp - encoding == 4 && STREQN (encoding, "utf8", 4)))
         return 1;
       else
         return 0;
     }
     }
   return 0;
 #endif
 }
References CODESET, locale_charset(), nl_langinfo(), STREQ, and STREQN.
Referenced by reset_locale_vars(), set_default_locale(), set_default_locale_vars(), and set_locale_var().
locale_setblanks()
static void locale_setblanks () static
Definition at line 576 of file locale.c.
 {
   int x;
   for (x = 0; x < sh_syntabsiz; x++)
     {
       if (isblank ((unsigned char)x))
     sh_syntaxtab[x] |= CSHBRK|CBLANK;
       else if (member (x, shell_break_chars))
     {
       sh_syntaxtab[x] |= CSHBRK;
       sh_syntaxtab[x] &= ~CBLANK;
     }
       else
     sh_syntaxtab[x] &= ~(CSHBRK|CBLANK);
     }
 }
References CBLANK, CSHBRK, isblank, member, sh_syntabsiz, sh_syntaxtab, shell_break_chars, and x.
Referenced by reset_locale_vars(), set_default_locale_vars(), and set_locale_var().
PARAMS() [1/2]
static int locale_isutf8 PARAMS ((char *)) static
PARAMS() [2/2]
static int reset_locale_vars PARAMS ((void)) static
reset_locale_vars()
static int reset_locale_vars () static
Definition at line 363 of file locale.c.
 {
   char *t, *x;
 #if defined (HAVE_SETLOCALE)
   if (lang == 0 || *lang == '\0')
     maybe_make_export_env ();       /* trust that this will change environment for setlocale */
   if (setlocale (LC_ALL, lang ? lang : "") == 0)
     return 0;
   x = 0;
 #  if defined (LC_CTYPE)
   x = setlocale (LC_CTYPE, get_locale_var ("LC_CTYPE"));
 #  endif
 #  if defined (LC_COLLATE)
   t = setlocale (LC_COLLATE, get_locale_var ("LC_COLLATE"));
 #  endif
 #  if defined (LC_MESSAGES)
   t = setlocale (LC_MESSAGES, get_locale_var ("LC_MESSAGES"));
 #  endif
 #  if defined (LC_NUMERIC)
   t = setlocale (LC_NUMERIC, get_locale_var ("LC_NUMERIC"));
 #  endif
 #  if defined (LC_TIME)
   t = setlocale (LC_TIME, get_locale_var ("LC_TIME"));
 #  endif
   locale_setblanks ();
   locale_mb_cur_max = MB_CUR_MAX;
   if (x)
     locale_utf8locale = locale_isutf8 (x);
 #  if defined (HANDLE_MULTIBYTE)
   locale_shiftstates = mblen ((char *)NULL, 0);
 #  else
   locale_shiftstates = 0;
 #  endif
   u32reset ();
 #endif
   return 1;
 }
References get_locale_var(), lang, LC_ALL, LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_NUMERIC, LC_TIME, locale_isutf8(), locale_mb_cur_max, locale_setblanks(), locale_shiftstates, locale_utf8locale, maybe_make_export_env(), MB_CUR_MAX, mblen(), NULL, setlocale, t, u32reset(), and x.
Referenced by set_lang(), and set_locale_var().
set_default_lang()
void set_default_lang ()
Definition at line 324 of file locale.c.
 {
   char *v;
   v = get_string_value ("LC_ALL");
   set_locale_var ("LC_ALL", v);
   v = get_string_value ("LANG");
   set_lang ("LANG", v);
 }
References get_string_value(), set_lang(), and set_locale_var().
Referenced by main().
set_default_locale()
void set_default_locale ()
Definition at line 79 of file locale.c.
 {
 #if defined (HAVE_SETLOCALE)
   default_locale = setlocale (LC_ALL, "");
   if (default_locale)
     default_locale = savestring (default_locale);
 #else
   default_locale = savestring ("C");
 #endif /* HAVE_SETLOCALE */
   bindtextdomain (PACKAGE, LOCALEDIR);
   textdomain (PACKAGE);
   locale_mb_cur_max = MB_CUR_MAX;
   locale_utf8locale = locale_isutf8 (default_locale);
 #if defined (HANDLE_MULTIBYTE)
   locale_shiftstates = mblen ((char *)NULL, 0);
 #else
   locale_shiftstates = 0;
 #endif
 }
References bindtextdomain, default_locale, LC_ALL, locale_isutf8(), locale_mb_cur_max, locale_shiftstates, locale_utf8locale, LOCALEDIR, MB_CUR_MAX, mblen(), NULL, PACKAGE, savestring(), setlocale, and textdomain.
Referenced by main().
set_default_locale_vars()
void set_default_locale_vars ()
Definition at line 104 of file locale.c.
 {
   char *val;
 #if defined (HAVE_SETLOCALE)
 #  if defined (LC_CTYPE)
   val = get_string_value ("LC_CTYPE");
   if (val == 0 && lc_all && *lc_all)
     {
       setlocale (LC_CTYPE, lc_all);
       locale_setblanks ();
       locale_mb_cur_max = MB_CUR_MAX;
       locale_utf8locale = locale_isutf8 (lc_all);
 #    if defined (HANDLE_MULTIBYTE)
       locale_shiftstates = mblen ((char *)NULL, 0);
 #    else
       locale_shiftstates = 0;
 #    endif
       u32reset ();
     }
 #  endif
 #  if defined (LC_COLLATE)
   val = get_string_value ("LC_COLLATE");
   if (val == 0 && lc_all && *lc_all)
     setlocale (LC_COLLATE, lc_all);
 #  endif /* LC_COLLATE */
 #  if defined (LC_MESSAGES)
   val = get_string_value ("LC_MESSAGES");
   if (val == 0 && lc_all && *lc_all)
     setlocale (LC_MESSAGES, lc_all);
 #  endif /* LC_MESSAGES */
 #  if defined (LC_NUMERIC)
   val = get_string_value ("LC_NUMERIC");
   if (val == 0 && lc_all && *lc_all)
     setlocale (LC_NUMERIC, lc_all);
 #  endif /* LC_NUMERIC */
 #  if defined (LC_TIME)
   val = get_string_value ("LC_TIME");
   if (val == 0 && lc_all && *lc_all)
     setlocale (LC_TIME, lc_all);
 #  endif /* LC_TIME */
 #endif /* HAVE_SETLOCALE */
   val = get_string_value ("TEXTDOMAIN");
   if (val && *val)
     {
       FREE (default_domain);
       default_domain = savestring (val);
       if (default_dir && *default_dir)
     bindtextdomain (default_domain, default_dir);
     }
   val = get_string_value ("TEXTDOMAINDIR");
   if (val && *val)
     {
       FREE (default_dir);
       default_dir = savestring (val);
       if (default_domain && *default_domain)
     bindtextdomain (default_domain, default_dir);
     }
 }
References bindtextdomain, default_dir, default_domain, FREE, get_string_value(), lc_all, LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_NUMERIC, LC_TIME, locale_isutf8(), locale_mb_cur_max, locale_setblanks(), locale_shiftstates, locale_utf8locale, MB_CUR_MAX, mblen(), NULL, savestring(), setlocale, u32reset(), and val.
Referenced by main().
set_lang()
int set_lang (char * var, char * value)
Definition at line 306 of file locale.c.
 {
   FREE (lang);
   if (value)
     lang = savestring (value);
   else
     {
       lang = (char *)xmalloc (1);
       lang[0] = '\0';
     }
   return ((lc_all == 0 || *lc_all == 0) ? reset_locale_vars () : 0);
 }
References FREE, lang, lc_all, reset_locale_vars(), savestring(), value, and xmalloc.
Referenced by set_default_lang(), and sv_locale().
set_locale_var()
int set_locale_var (char * var, char * value)
Definition at line 177 of file locale.c.
 {
   int r;
   char *x;
   x = "";
   errno = 0;
   if (var[0] == 'T' && var[10] == 0)        /* TEXTDOMAIN */
     {
       FREE (default_domain);
       default_domain = value ? savestring (value) : (char *)NULL;
       if (default_dir && *default_dir)
     bindtextdomain (default_domain, default_dir);
       return (1);
     }
   else if (var[0] == 'T')           /* TEXTDOMAINDIR */
     {
       FREE (default_dir);
       default_dir = value ? savestring (value) : (char *)NULL;
       if (default_domain && *default_domain)
     bindtextdomain (default_domain, default_dir);
       return (1);
     }
   /* var[0] == 'L' && var[1] == 'C' && var[2] == '_' */
   else if (var[3] == 'A')           /* LC_ALL */
     {
       FREE (lc_all);
       if (value)
     lc_all = savestring (value);
       else
     {
       lc_all = (char *)xmalloc (1);
       lc_all[0] = '\0';
     }
 #if defined (HAVE_SETLOCALE)
       r = *lc_all ? ((x = setlocale (LC_ALL, lc_all)) != 0) : reset_locale_vars ();
       if (x == 0)
     {
       if (errno == 0)
         internal_warning(_("setlocale: LC_ALL: cannot change locale (%s)"), lc_all);
       else
         internal_warning(_("setlocale: LC_ALL: cannot change locale (%s): %s"), lc_all, strerror (errno));
     }
       locale_setblanks ();
       locale_mb_cur_max = MB_CUR_MAX;
       /* if LC_ALL == "", reset_locale_vars has already called this */
       if (*lc_all && x)
     locale_utf8locale = locale_isutf8 (lc_all);
 #  if defined (HANDLE_MULTIBYTE)
       locale_shiftstates = mblen ((char *)NULL, 0);
 #  else
       locale_shiftstates = 0;
 #  endif
       u32reset ();
       return r;
 #else
       return (1);
 #endif
     }
 #if defined (HAVE_SETLOCALE)
   else if (var[3] == 'C' && var[4] == 'T')  /* LC_CTYPE */
     {
 #  if defined (LC_CTYPE)
       if (lc_all == 0 || *lc_all == '\0')
     {
       x = setlocale (LC_CTYPE, get_locale_var ("LC_CTYPE"));
       locale_setblanks ();
       locale_mb_cur_max = MB_CUR_MAX;
       /* if setlocale() returns NULL, the locale is not changed */
       if (x)
         locale_utf8locale = locale_isutf8 (x);
 #if defined (HANDLE_MULTIBYTE)
       locale_shiftstates = mblen ((char *)NULL, 0);
 #else
       locale_shiftstates = 0;
 #endif
       u32reset ();
     }
 #  endif
     }
   else if (var[3] == 'C' && var[4] == 'O')  /* LC_COLLATE */
     {
 #  if defined (LC_COLLATE)
       if (lc_all == 0 || *lc_all == '\0')
     x = setlocale (LC_COLLATE, get_locale_var ("LC_COLLATE"));
 #  endif /* LC_COLLATE */
     }
   else if (var[3] == 'M' && var[4] == 'E')  /* LC_MESSAGES */
     {
 #  if defined (LC_MESSAGES)
       if (lc_all == 0 || *lc_all == '\0')
     x = setlocale (LC_MESSAGES, get_locale_var ("LC_MESSAGES"));
 #  endif /* LC_MESSAGES */
     }
   else if (var[3] == 'N' && var[4] == 'U')  /* LC_NUMERIC */
     {
 #  if defined (LC_NUMERIC)
       if (lc_all == 0 || *lc_all == '\0')
     x = setlocale (LC_NUMERIC, get_locale_var ("LC_NUMERIC"));
 #  endif /* LC_NUMERIC */
     }
   else if (var[3] == 'T' && var[4] == 'I')  /* LC_TIME */
     {
 #  if defined (LC_TIME)
       if (lc_all == 0 || *lc_all == '\0')
     x = setlocale (LC_TIME, get_locale_var ("LC_TIME"));
 #  endif /* LC_TIME */
     }
 #endif /* HAVE_SETLOCALE */
   if (x == 0)
     {
       if (errno == 0)
     internal_warning(_("setlocale: %s: cannot change locale (%s)"), var, get_locale_var (var));
       else
     internal_warning(_("setlocale: %s: cannot change locale (%s): %s"), var, get_locale_var (var), strerror (errno));
     }
   return (x != 0);
 }
References _, bindtextdomain, default_dir, default_domain, errno, FREE, get_locale_var(), internal_warning(), lc_all, LC_ALL, LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_NUMERIC, LC_TIME, locale_isutf8(), locale_mb_cur_max, locale_setblanks(), locale_shiftstates, locale_utf8locale, MB_CUR_MAX, mblen(), NULL, reset_locale_vars(), savestring(), setlocale, strerror(), u32reset(), value, x, and xmalloc.
Referenced by set_default_lang(), and sv_locale().
Variable Documentation
default_dir
char* default_dir static
Definition at line 59 of file locale.c.
Referenced by set_default_locale_vars(), and set_locale_var().
default_domain
char* default_domain static
Definition at line 58 of file locale.c.
Referenced by set_default_locale_vars(), and set_locale_var().
default_locale
char* default_locale static
Definition at line 55 of file locale.c.
Referenced by __loc_is_allocated(), do_newlocale(), get_locale_var(), and set_default_locale().
dump_po_strings
int dump_po_strings
Definition at line 52 of file locale.c.
Referenced by main().
dump_translatable_strings
int dump_translatable_strings extern
Referenced by main(), and parse_shell_options().
errno
int errno extern
Referenced by set_locale_var().
lang
char* lang static
Definition at line 67 of file locale.c.
Referenced by catopen(), get_locale_var(), reset_locale_vars(), and set_lang().
lc_all
char* lc_all static
Definition at line 63 of file locale.c.
Referenced by get_locale_var(), set_default_locale_vars(), set_lang(), and set_locale_var().
locale_mb_cur_max
int locale_mb_cur_max
Definition at line 47 of file locale.c.
Referenced by expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), mbschr(), pat_subst(), reset_locale_vars(), set_default_locale(), set_default_locale_vars(), set_locale_var(), and sh_charvis().
locale_shiftstates
int locale_shiftstates = 0
Definition at line 48 of file locale.c.
Referenced by reset_locale_vars(), set_default_locale(), set_default_locale_vars(), and set_locale_var().
locale_utf8locale
int locale_utf8locale
Definition at line 46 of file locale.c.
Referenced by ansicstr(), cutchars(), mbschr(), read_comsub(), reset_locale_vars(), set_default_locale(), set_default_locale_vars(), set_locale_var(), setifs(), sh_backslash_quote(), sh_charvis(), sh_double_quote(), sh_mkdoublequoted(), and string_extract_verbatim().
singlequote_translations
int singlequote_translations = 0
Definition at line 50 of file locale.c.
Referenced by expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), parse_matched_pair(), and read_token_word().