Fennix Userspace: Userspace/mlibc/options/posix/generic/posix-file-io.cpp File Reference
posix-file-io.cpp File Reference
#include <mlibc/posix-file-io.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
#include <errno.h>
Namespaces
mlibc
Functions
FILE * fdopen (int fd, const char *mode)
Function Documentation
fdopen()
FILE* fdopen (int fd, const char * mode)
Definition at line 82 of file posix-file-io.cpp.
{
     int flags = mlibc::fd_file::parse_modestring(mode);
     flags &= ~O_TRUNC; // 'w' should not truncate the file
     if (flags & O_APPEND) {
         int cur_flags = fcntl(fd, F_GETFL, 0);
         if (cur_flags < 0) {
             errno = EINVAL;
             return nullptr;
         } else if (!(cur_flags & O_APPEND)) {
             if (fcntl(fd, F_SETFL, cur_flags | O_APPEND)) {
                 errno = EINVAL;
                 return nullptr;
             }
         }
     }
     if (flags & O_CLOEXEC) {
         if (fcntl(fd, F_SETFD, FD_CLOEXEC)) {
             errno = EINVAL;
             return nullptr;
         }
     }
     // TODO: We may need to activate line buffered mode for terminals.
     return frg::construct<mlibc::fd_file>(getAllocator(), fd,
             mlibc::file_dispose_cb<mlibc::fd_file>);
 }
References EINVAL, errno, F_GETFL, F_SETFD, F_SETFL, fcntl(), fd, FD_CLOEXEC, mlibc::flags, getAllocator(), O_APPEND, O_CLOEXEC, O_TRUNC, and mlibc::fd_file::parse_modestring().
Referenced by getspnam_r(), and main().