Fennix: Kernel/storage/kernel_io.cpp File Reference
kernel_io.cpp File Reference
#include <filesystem.hpp>
#include <errno.h>
#include "../kernel.h"
Functions
static bool CheckForScheduler ()
int fopen (const char *pathname, const char *mode)
int creat (const char *pathname, mode_t mode)
ssize_t fread (int fd, void *buf, size_t count)
ssize_t fwrite (int fd, const void *buf, size_t count)
int fclose (int fd)
off_t lseek (int fd, off_t offset, int whence)
int stat (const char *pathname, struct stat *statbuf)
int fstat (int fd, struct stat *statbuf)
int lstat (const char *pathname, struct stat *statbuf)
Function Documentation
CheckForScheduler()
static bool CheckForScheduler () static
Definition at line 26 of file kernel_io.cpp.
 {
     if (TaskManager == nullptr)
         return false;
     return true;
 }
References TaskManager.
Referenced by creat(), fclose(), fopen(), fread(), fstat(), fwrite(), lseek(), lstat(), and stat().
creat()
int creat (const char * pathname, mode_t mode)
Definition at line 44 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_creat(pathname, mode);
     return fd;
 }
fclose()
int fclose (int fd)
Definition at line 77 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_close(fd);
     return ret;
 }
References vfs::FileDescriptorTable::_close(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), _nl_log_untranslated(), add_remove_shell_main(), append_control_file_to_llist(), arp_show(), bb_displayroutes(), bb_dump_addfile(), cleanup(), cmd_cat(), comm_main(), conf_read_simple(), conf_write(), config_close(), convert(), create_file(), create_list(), dialog_menu(), do_all_in_proc_swaps(), do_disk_statistics(), do_info(), do_pidfile(), do_wordexp(), download_one_url(), dprintf(), Execute::ELFObject::ELFObject(), encode_n_base64(), endgrent(), endmntent(), endpwent(), endusershell(), evaluate(), expand_main(), extract_info(), fb_drawimage(), fclose_if_not_stdin(), file_action_grep(), file_write_dep(), finalize(), find_export_symbols(), freopen(), G_DoLoadGame(), G_DoSaveGame(), get_block_backed_filesystems(), get_charset_aliases(), get_cpu_count(), get_cpu_statistics(), get_hz(), get_irqcpu_nr(), get_irqs_from_interrupts(), get_irqs_from_stat(), get_smp_uptime(), get_uptime(), Execute::GetBinaryType(), getdate(), getgrouplist(), getgrouplist_internal(), handle_dir_common(), head_builtin(), if_readlist_proc(), ifupdown_main(), index_status_file(), is_hpet_irq(), is_ide_cdrom_or_tape(), klogd_setloglevel(), list_devs_in_proc_partititons(), LoadDefaultCollection(), Driver::Manager::LoadDriverFile(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), LoadResponseFile(), logdir_close(), M_FileExists(), M_ReadFile(), M_ReadSaveStrings(), M_WriteFile(), main(), more_main(), next_input_file(), open_shell_script(), parse(), parse_conf(), parse_file(), parse_meminfo(), patch_main(), pclose(), popen(), popmaildir_main(), print_builtin(), print_login_issue(), print_numbered_lines(), process_cron_update_file(), process_files(), process_includes(), process_irq_counts(), process_timer_stats(), procps_scan(), query(), read_alias_file(), read_config_file(), read_cstate_counts(), read_iface_state(), read_interfaces(), read_man_page(), readprofile_main(), rev_main(), rotate(), rpmalloc_initialize_config(), rtc_adjtime_is_utc(), save_input_to_file(), SaveDefaultCollection(), scan_proc_net_or_maps(), scriptreplay_main(), sed_main(), sendmail_main(), setfiles_main(), setgrent(), setpwent(), Execute::Spawn(), StatDump(), stdcat(), test_file(), unpack_package(), unset_bash_input(), update_passwd(), W_StdC_CloseFile(), write_helpfiles(), write_status_file(), write_str_to_file(), WriteTimidityConfig(), xprint_and_close_file(), and xtrace_reset().
fopen()
int fopen (const char * pathname, const char * mode)
Definition at line 33 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_open(pathname, ConvertFileFlags(mode), 0666);
     return fd;
 }
fread()
ssize_t fread (int fd, void * buf, size_t count)
Definition at line 55 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_read(fd, buf, count);
     return ret;
 }
References vfs::FileDescriptorTable::_read(), buf, CheckForScheduler(), count, ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), cmd_cat(), diffreg(), Execute::ELFGetDynamicTag_x86_64(), Execute::ELFGetSections_x86_64(), Execute::ELFGetSymbolType_x86_64(), Execute::ELFLookupSymbol(), Execute::ELFObject::ELFObject(), encode_n_base64(), fb_drawimage(), get(), Execute::GetBinaryType(), getgrouplist(), getw(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), Execute::ELFObject::LoadInterpreter(), Execute::ELFObject::LoadPhdrs_x86_64(), LoadResponseFile(), M_ReadFile(), M_ReadSaveStrings(), read_block(), read_man_page(), retrieve_file_data(), saveg_read8(), skip(), Execute::Spawn(), StartKernelShell(), and W_StdC_Read().
fstat()
int fstat (int fd, struct stat * statbuf)
Definition at line 110 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_fstat(fd, statbuf);
     return ret;
 }
References vfs::FileDescriptorTable::_fstat(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __fstat_time32(), __fxstat(), _evalfile(), _nl_load_domain(), _rl_read_file(), archivefile(), cmd_cat(), copy_tempfile(), crontab_main(), dd_main(), diff_main(), do_config_file(), fdopendir(), file_insert(), flash_eraseall_main(), flashcp_main(), getspnam_r(), getstat(), handle_retr(), here_document_to_fd(), history_truncate_file(), IF_DESKTOP(), isnetconn(), last_main(), load_crontab(), load_library(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), log_locally(), lpqr_main(), main(), more_main(), noclobber_open(), open_shell_script(), openredirect(), patch_main(), print_deps(), read_history_range(), scan_proc_net_or_maps(), sem_open(), send_file_and_exit(), sh_stat(), shred_main(), skip(), Execute::Spawn(), tail_main(), ttyname_r(), update_passwd(), uuencode_main(), write_pidfile(), xfstat(), and xmalloc_read_with_initial_buf().
fwrite()
ssize_t fwrite (int fd, const void * buf, size_t count)
Definition at line 66 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_write(fd, buf, count);
     return ret;
 }
References vfs::FileDescriptorTable::_write(), buf, CheckForScheduler(), count, ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getopt_msg(), _rl_output_some_chars(), _rl_put_indicator(), buffer_pwrite(), conf_write(), encode_n_base64(), evaluate(), expr_print_file_helper(), fnprint(), fputs(), M_WriteFile(), perror(), print_line(), putw(), read_base64(), refresh(), saveg_write8(), svlogd_main(), tee_main(), write2stdout(), and write_zeros().
lseek()
off_t lseek (int fd, off_t offset, int whence)
Definition at line 88 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     off_t ret = fdt->_lseek(fd, offset, whence);
     return ret;
 }
References vfs::FileDescriptorTable::_lseek(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, offset, and thisProcess.
Referenced by back_lines(), bb_BLKGETSIZE_sectors(), cutfile(), dd_main(), dialog_textbox(), diffreg(), Execute::ELFGetDynamicTag_x86_64(), Execute::ELFGetSections_x86_64(), Execute::ELFGetSymbolType_x86_64(), Execute::ELFLookupSymbol(), fd_ispipe(), get_header_ar(), get_header_tar(), get_line(), get_volume_size_in_bytes(), Execute::GetBinaryType(), history_do_write(), io_thread_func(), last_main(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), Execute::ELFObject::LoadPhdrs_x86_64(), mmap_fixed(), open_shell_script(), print_position(), retrieve_file_data(), rewinddir(), scan_file(), seek_by_jump(), seek_sector(), seekdir(), send_file_and_exit(), tail_main(), unzip_skip(), volume_id_get_buffer(), xlseek(), and zsyncfd().
lstat()
int lstat (const char * pathname, struct stat * statbuf)
Definition at line 121 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_lstat(pathname, statbuf);
     return ret;
 }
References vfs::FileDescriptorTable::_lstat(), CheckForScheduler(), ENOSYS, Tasking::PCB::FileDescriptors, and thisProcess.
stat()
int stat (const char * pathname, struct stat * statbuf)
Definition at line 99 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_stat(pathname, statbuf);
     return ret;
 }
References vfs::FileDescriptorTable::_stat(), CheckForScheduler(), ENOSYS, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __stat_time32(), __xstat(), _path_isdir(), _rl_print_color_indicator(), action_permissions(), append_to_match(), bb_make_directory(), bbunpack(), binop(), cdcmd(), colon(), conf(), conf_choice(), conf_get_default_confname(), conf_load(), conf_save(), conf_string(), conf_write(), crond_main(), custom(), deluser_main(), diff_main(), display_single(), do_glob(), do_nftw(), do_rescan(), du(), exec_conf(), fchmodat(), file_action_grep(), file_is_executable(), fileAction(), filstat(), find_command(), find_dot_file(), find_main(), find_mount_point(), ftok(), get_current_dir_name(), getstat(), glob_testdir(), grep_main(), handle_incoming_and_exit(), history_do_write(), init(), install_main(), is_directory(), is_ide_cdrom_or_tape(), ln_builtin(), ln_main(), logdir_open(), logical_getcwd(), mailstat(), main(), mktemp(), mountpoint_main(), mv_main(), my_stat(), name_to_dev_t(), noclobber_open(), open_control(), openredirect(), patch_main(), pid_is_user(), process_event(), procps_scan(), read_config_file(), read_man_page(), realpath_builtin(), recursive_action1(), rotate(), runsv_main(), runsvdir_main(), scan_recursive(), scan_request(), search_conf(), sed_main(), set_loop(), sh_mktmpname(), singlemount(), stat_char(), swap_enable_disable(), switch_root_main(), sysctl_act_recursive(), tail_main(), ttyname_r(), vi_main(), who_main(), xgetpty(), xmkpath(), and xstat().