Fennix Userspace: Userspace/apps/base/busybox/coreutils/logname.c File Reference
logname.c File Reference
#include "libbb.h"
Functions
int logname_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int logname_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
logname_main() [1/2]
int logname_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 45 of file logname.c.
 {
     char buf[64];
     if (argv[1]) {
         bb_show_usage();
     }
     /* Using _r function - avoid pulling in static buffer from libc */
     if (getlogin_r(buf, sizeof(buf)) == 0) {
         puts(buf);
         return fflush_all();
     }
     bb_simple_perror_msg_and_die("getlogin");
 }
References argv, bb_show_usage(), bb_simple_perror_msg_and_die(), buf, fflush_all(), getlogin_r(), and puts().
logname_main() [2/2]
int logname_main (int argc, char ** argv)