Fennix: Userspace/musl/include/sys/mman.h File Reference
mman.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/mman.h>
Macros
#define __NEED_mode_t
#define __NEED_size_t
#define __NEED_off_t
#define MAP_FAILED ((void *) -1)
#define MAP_SHARED 0x01
#define MAP_PRIVATE 0x02
#define MAP_SHARED_VALIDATE 0x03
#define MAP_TYPE 0x0f
#define MAP_FIXED 0x10
#define MAP_ANON 0x20
#define MAP_ANONYMOUS MAP_ANON
#define MAP_NORESERVE 0x4000
#define MAP_GROWSDOWN 0x0100
#define MAP_DENYWRITE 0x0800
#define MAP_EXECUTABLE 0x1000
#define MAP_LOCKED 0x2000
#define MAP_POPULATE 0x8000
#define MAP_NONBLOCK 0x10000
#define MAP_STACK 0x20000
#define MAP_HUGETLB 0x40000
#define MAP_SYNC 0x80000
#define MAP_FIXED_NOREPLACE 0x100000
#define MAP_FILE 0
#define MAP_HUGE_SHIFT 26
#define MAP_HUGE_MASK 0x3f
#define MAP_HUGE_16KB (14 << 26)
#define MAP_HUGE_64KB (16 << 26)
#define MAP_HUGE_512KB (19 << 26)
#define MAP_HUGE_1MB (20 << 26)
#define MAP_HUGE_2MB (21 << 26)
#define MAP_HUGE_8MB (23 << 26)
#define MAP_HUGE_16MB (24 << 26)
#define MAP_HUGE_32MB (25 << 26)
#define MAP_HUGE_256MB (28 << 26)
#define MAP_HUGE_512MB (29 << 26)
#define MAP_HUGE_1GB (30 << 26)
#define MAP_HUGE_2GB (31 << 26)
#define MAP_HUGE_16GB (34U << 26)
#define PROT_NONE 0
#define PROT_READ 1
#define PROT_WRITE 2
#define PROT_EXEC 4
#define PROT_GROWSDOWN 0x01000000
#define PROT_GROWSUP 0x02000000
#define MS_ASYNC 1
#define MS_INVALIDATE 2
#define MS_SYNC 4
#define MCL_CURRENT 1
#define MCL_FUTURE 2
#define MCL_ONFAULT 4
#define POSIX_MADV_NORMAL 0
#define POSIX_MADV_RANDOM 1
#define POSIX_MADV_SEQUENTIAL 2
#define POSIX_MADV_WILLNEED 3
#define POSIX_MADV_DONTNEED 4
Functions
void * mmap (void *, size_t, int, int, int, off_t)
int munmap (void *, size_t)
int mprotect (void *, size_t, int)
int msync (void *, size_t, int)
int posix_madvise (void *, size_t, int)
int mlock (const void *, size_t)
int munlock (const void *, size_t)
int mlockall (int)
int munlockall (void)
int shm_open (const char *, int, mode_t)
int shm_unlink (const char *)
Macro Definition Documentation
__NEED_mode_t
#define __NEED_mode_t
Definition at line 9 of file mman.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 11 of file mman.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file mman.h.
MAP_ANON
#define MAP_ANON 0x20
Definition at line 26 of file mman.h.
MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
Definition at line 27 of file mman.h.
MAP_DENYWRITE
#define MAP_DENYWRITE 0x0800
Definition at line 30 of file mman.h.
MAP_EXECUTABLE
#define MAP_EXECUTABLE 0x1000
Definition at line 31 of file mman.h.
MAP_FAILED
#define MAP_FAILED ((void *) -1)
Definition at line 19 of file mman.h.
MAP_FILE
#define MAP_FILE 0
Definition at line 39 of file mman.h.
MAP_FIXED
#define MAP_FIXED 0x10
Definition at line 25 of file mman.h.
MAP_FIXED_NOREPLACE
#define MAP_FIXED_NOREPLACE 0x100000
Definition at line 38 of file mman.h.
MAP_GROWSDOWN
#define MAP_GROWSDOWN 0x0100
Definition at line 29 of file mman.h.
MAP_HUGE_16GB
#define MAP_HUGE_16GB (34U << 26)
Definition at line 55 of file mman.h.
MAP_HUGE_16KB
#define MAP_HUGE_16KB (14 << 26)
Definition at line 43 of file mman.h.
MAP_HUGE_16MB
#define MAP_HUGE_16MB (24 << 26)
Definition at line 49 of file mman.h.
MAP_HUGE_1GB
#define MAP_HUGE_1GB (30 << 26)
Definition at line 53 of file mman.h.
MAP_HUGE_1MB
#define MAP_HUGE_1MB (20 << 26)
Definition at line 46 of file mman.h.
MAP_HUGE_256MB
#define MAP_HUGE_256MB (28 << 26)
Definition at line 51 of file mman.h.
MAP_HUGE_2GB
#define MAP_HUGE_2GB (31 << 26)
Definition at line 54 of file mman.h.
MAP_HUGE_2MB
#define MAP_HUGE_2MB (21 << 26)
Definition at line 47 of file mman.h.
MAP_HUGE_32MB
#define MAP_HUGE_32MB (25 << 26)
Definition at line 50 of file mman.h.
MAP_HUGE_512KB
#define MAP_HUGE_512KB (19 << 26)
Definition at line 45 of file mman.h.
MAP_HUGE_512MB
#define MAP_HUGE_512MB (29 << 26)
Definition at line 52 of file mman.h.
MAP_HUGE_64KB
#define MAP_HUGE_64KB (16 << 26)
Definition at line 44 of file mman.h.
MAP_HUGE_8MB
#define MAP_HUGE_8MB (23 << 26)
Definition at line 48 of file mman.h.
MAP_HUGE_MASK
#define MAP_HUGE_MASK 0x3f
Definition at line 42 of file mman.h.
MAP_HUGE_SHIFT
#define MAP_HUGE_SHIFT 26
Definition at line 41 of file mman.h.
MAP_HUGETLB
#define MAP_HUGETLB 0x40000
Definition at line 36 of file mman.h.
MAP_LOCKED
#define MAP_LOCKED 0x2000
Definition at line 32 of file mman.h.
MAP_NONBLOCK
#define MAP_NONBLOCK 0x10000
Definition at line 34 of file mman.h.
MAP_NORESERVE
#define MAP_NORESERVE 0x4000
Definition at line 28 of file mman.h.
MAP_POPULATE
#define MAP_POPULATE 0x8000
Definition at line 33 of file mman.h.
MAP_PRIVATE
#define MAP_PRIVATE 0x02
Definition at line 22 of file mman.h.
MAP_SHARED
#define MAP_SHARED 0x01
Definition at line 21 of file mman.h.
MAP_SHARED_VALIDATE
#define MAP_SHARED_VALIDATE 0x03
Definition at line 23 of file mman.h.
MAP_STACK
#define MAP_STACK 0x20000
Definition at line 35 of file mman.h.
MAP_SYNC
#define MAP_SYNC 0x80000
Definition at line 37 of file mman.h.
MAP_TYPE
#define MAP_TYPE 0x0f
Definition at line 24 of file mman.h.
MCL_CURRENT
#define MCL_CURRENT 1
Definition at line 68 of file mman.h.
MCL_FUTURE
#define MCL_FUTURE 2
Definition at line 69 of file mman.h.
MCL_ONFAULT
#define MCL_ONFAULT 4
Definition at line 70 of file mman.h.
MS_ASYNC
#define MS_ASYNC 1
Definition at line 64 of file mman.h.
MS_INVALIDATE
#define MS_INVALIDATE 2
Definition at line 65 of file mman.h.
MS_SYNC
#define MS_SYNC 4
Definition at line 66 of file mman.h.
POSIX_MADV_DONTNEED
#define POSIX_MADV_DONTNEED 4
Definition at line 76 of file mman.h.
POSIX_MADV_NORMAL
#define POSIX_MADV_NORMAL 0
Definition at line 72 of file mman.h.
POSIX_MADV_RANDOM
#define POSIX_MADV_RANDOM 1
Definition at line 73 of file mman.h.
POSIX_MADV_SEQUENTIAL
#define POSIX_MADV_SEQUENTIAL 2
Definition at line 74 of file mman.h.
POSIX_MADV_WILLNEED
#define POSIX_MADV_WILLNEED 3
Definition at line 75 of file mman.h.
PROT_EXEC
#define PROT_EXEC 4
Definition at line 60 of file mman.h.
PROT_GROWSDOWN
#define PROT_GROWSDOWN 0x01000000
Definition at line 61 of file mman.h.
PROT_GROWSUP
#define PROT_GROWSUP 0x02000000
Definition at line 62 of file mman.h.
PROT_NONE
#define PROT_NONE 0
Definition at line 57 of file mman.h.
PROT_READ
#define PROT_READ 1
Definition at line 58 of file mman.h.
PROT_WRITE
#define PROT_WRITE 2
Definition at line 59 of file mman.h.
Function Documentation
mlock()
int mlock (const void * addr, size_t len)
Definition at line 21 of file sys-mman-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, addr, len, and syscall().
Referenced by mlock2().
mlockall()
int mlockall (int flags)
Definition at line 26 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mlockall, -1);
     if(int e = mlibc::sys_mlockall(flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, flags, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_mlockall(), and syscall().
mmap()
void* mmap (void * hint, size_t size, int prot, int flags, int fd, off_t offset)
Definition at line 78 of file sys-mman-stubs.cpp.
{
     void *window;
     if(int e = mlibc::sys_vm_map(hint, size, prot, flags, fd, offset, &window); e) {
         errno = e;
         return (void *)-1;
     }
     return window;
 }
References errno, flags, offset, size, and mlibc::sys_vm_map().
mprotect()
int mprotect (void * pointer, size_t size, int prot)
Definition at line 12 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_vm_protect, -1);
     if(int e = mlibc::sys_vm_protect(pointer, size, prot); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_vm_protect().
Referenced by alloc_meta(), and map_library().
msync()
int msync (void * addr, size_t length, int flags)
Definition at line 52 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msync, -1);
     if(int e = mlibc::sys_msync(addr, length, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References addr, errno, flags, len, mlibc::length, MLIBC_CHECK_OR_ENOSYS, start(), mlibc::sys_msync(), and syscall_cp.
Referenced by history_do_write().
munlock()
int munlock (const void * addr, size_t len)
Definition at line 35 of file sys-mman-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, addr, len, and syscall().
munlockall()
int munlockall (void)
Definition at line 40 of file sys-mman-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, and syscall().
munmap()
int munmap (void * pointer, size_t size)
Definition at line 87 of file sys-mman-stubs.cpp.
{
     if(int e = mlibc::sys_vm_unmap(pointer, size); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, size, and mlibc::sys_vm_unmap().
Referenced by _nl_load_domain(), catclose(), do_catopen(), free(), history_do_write(), malloc(), read_history_range(), sem_close(), sem_open(), and unmap_library().
posix_madvise()
int posix_madvise (void * addr, size_t len, int advice)
Definition at line 46 of file sys-mman-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31m" "mlibc: posix_madvise() fails unconditionally" "\e[39m"
             << frg::endlog;
     return ENOSYS;
 }
References __syscall, addr, ENOSYS, mlibc::infoLogger, len, and MADV_DONTNEED.
shm_open()
int shm_open (const char * name, int flags, mode_t mode)
Definition at line 116 of file sys-mman-stubs.cpp.
{
     int cs;
     char buf[NAME_MAX + 10];
     if(!(name = shm_mapname(name, buf)))
         return -1;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     int fd = open(name, flags | O_NOFOLLOW | O_CLOEXEC | O_NONBLOCK, mode);
     pthread_setcancelstate(cs, 0);
     return fd;
 }
References __shm_mapname(), buf, flags, name, NAME_MAX, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, open(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname().
shm_unlink()
int shm_unlink (const char * name)
Definition at line 127 of file sys-mman-stubs.cpp.
{
     char buf[NAME_MAX + 10];
     if(!(name = shm_mapname(name, buf)))
         return -1;
     return unlink(name);
 }
References __shm_mapname(), buf, name, NAME_MAX, anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname(), and unlink().
Referenced by sem_unlink().