Fennix Userspace: Userspace/apps/base/busybox/coreutils/whoami.c File Reference
whoami.c File Reference
#include "libbb.h"
Functions
int whoami_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int whoami_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
whoami_main() [1/2]
int whoami_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 30 of file whoami.c.
 {
     if (argv[1])
         bb_show_usage();
     /* Will complain and die if username not found */
     puts(xuid2uname(geteuid()));
     return fflush_all();
 }
References argv, bb_show_usage(), fflush_all(), geteuid, puts(), and xuid2uname().
whoami_main() [2/2]
int whoami_main (int argc, char ** argv)