Fennix: Userspace/apps/base/busybox/coreutils/nohup.c File Reference
nohup.c File Reference
#include "libbb.h"
Functions
int nohup_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
nohup_main()
int nohup_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 53 of file nohup.c.
 {
     const char *nohupout;
     char *home;
     xfunc_error_retval = 127;
     if (!argv[1]) {
         bb_show_usage();
     }
     /* If stdin is a tty, detach from it. */
     if (isatty(STDIN_FILENO)) {
         /* bb_error_msg("ignoring input"); */
         close(STDIN_FILENO);
         xopen(bb_dev_null, O_RDONLY); /* will be fd 0 (STDIN_FILENO) */
     }
     nohupout = "nohup.out";
     /* Redirect stdout to nohup.out, either in "." or in "$HOME". */
     if (isatty(STDOUT_FILENO)) {
         close(STDOUT_FILENO);
         if (open(nohupout, O_CREAT|O_WRONLY|O_APPEND, S_IRUSR|S_IWUSR) < 0) {
             home = getenv("HOME");
             if (home) {
                 nohupout = concat_path_file(home, nohupout);
                 xopen3(nohupout, O_CREAT|O_WRONLY|O_APPEND, S_IRUSR|S_IWUSR);
             } else {
                 xopen(bb_dev_null, O_RDONLY); /* will be fd 1 */
             }
         }
         bb_error_msg("appending output to %s", nohupout);
     }
     /* If we have a tty on stderr, redirect to stdout. */
     if (isatty(STDERR_FILENO)) {
         /* if (stdout_wasnt_a_tty)
             bb_error_msg("redirecting stderr to stdout"); */
         dup2(STDOUT_FILENO, STDERR_FILENO);
     }
     signal(SIGHUP, SIG_IGN);
     argv++;
     BB_EXECVP_or_die(argv);
 }
References argv, bb_dev_null, bb_error_msg(), BB_EXECVP_or_die(), bb_show_usage(), close(), concat_path_file(), dup2(), getenv, isatty(), O_APPEND, O_CREAT, O_RDONLY, O_WRONLY, open(), S_IRUSR, S_IWUSR, SIG_IGN, SIGHUP, signal, STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, xfunc_error_retval, xopen(), and xopen3().