Fennix: Userspace/musl/src/network/send.c File Reference
send.c File Reference
#include <sys/socket.h>
Functions
ssize_t send (int fd, const void *buf, size_t len, int flags)
Function Documentation
send()
ssize_t send (int fd, const void * buf, size_t len, int flags)
Definition at line 3 of file send.c.
 {
     return sendto(fd, buf, len, flags, 0, 0);
 }
References buf, fd, flags, len, and sendto().
Referenced by __netlink_enumerate(), _vsyslog(), dequote_escapes(), dequote_string(), expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), pat_subst(), quote_escapes_internal(), quote_globbing_chars(), quote_string(), quote_string_for_repl(), remove_quoted_ifs(), sh_backslash_quote(), sh_charvis(), sh_double_quote(), sh_mkdoublequoted(), string_extract_double_quoted(), string_quote_removal(), tcpudpsvd_main(), and unquoted_glob_pattern_p().