Fennix: Userspace/apps/base/busybox/coreutils/du.c File Reference
du.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Enumerations
enum {
OPT_a_files_too = (1 << 0) , OPT_H_follow_links = (1 << 1) , OPT_k_kbytes = (1 << 2) , OPT_L_follow_links = (1 << 3) ,
OPT_s_total_norecurse = (1 << 4) , OPT_x_one_FS = (1 << 5) , OPT_d_maxdepth = (1 << 6) , OPT_l_hardlinks = (1 << 7) ,
OPT_c_total = (1 << 8) , OPT_b = (1 << 9) , OPT_h_for_humans = (1 << 10) , OPT_m_mbytes = (1 << 11)
}
Functions
static void print (unsigned long long size, const char *filename)
static unsigned long long du (const char *filename)
int du_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 105 of file du.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 106 of file du.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_a_files_too
OPT_H_follow_links
OPT_k_kbytes
OPT_L_follow_links
OPT_s_total_norecurse
OPT_x_one_FS
OPT_d_maxdepth
OPT_l_hardlinks
OPT_c_total
OPT_b
OPT_h_for_humans
OPT_m_mbytes
Definition at line 78 of file du.c.
      {
     OPT_a_files_too    = (1 << 0),
     OPT_H_follow_links = (1 << 1),
     OPT_k_kbytes       = (1 << 2),
     OPT_L_follow_links = (1 << 3),
     OPT_s_total_norecurse = (1 << 4),
     OPT_x_one_FS       = (1 << 5),
     OPT_d_maxdepth     = (1 << 6),
     OPT_l_hardlinks    = (1 << 7),
     OPT_c_total        = (1 << 8),
     OPT_b              = (1 << 9),
     OPT_h_for_humans   = (1 << 10),
     OPT_m_mbytes       = (1 << 11),
 };
Function Documentation
du()
static unsigned long long du (const char * filename) static
Definition at line 145 of file du.c.
 {
     struct stat statbuf;
     unsigned long long sum;
     if (lstat(filename, &statbuf) != 0) {
         bb_simple_perror_msg(filename);
         G.status = EXIT_FAILURE;
         return 0;
     }
     if (option_mask32 & OPT_x_one_FS) {
         if (G.du_depth == 0) {
             G.dir_dev = statbuf.st_dev;
         } else if (G.dir_dev != statbuf.st_dev) {
             return 0;
         }
     }
     sum = ((option_mask32 & OPT_b) ? statbuf.st_size : statbuf.st_blocks);
     if (S_ISLNK(statbuf.st_mode)) {
         if (G.slink_depth > G.du_depth) { /* -H or -L */
             if (stat(filename, &statbuf) != 0) {
                 bb_simple_perror_msg(filename);
                 G.status = EXIT_FAILURE;
                 return 0;
             }
             sum = ((option_mask32 & OPT_b) ? statbuf.st_size : statbuf.st_blocks);
             if (G.slink_depth == 1) {
                 /* Convert -H to -L */
                 G.slink_depth = INT_MAX;
             }
         }
     }
     if (!(option_mask32 & OPT_l_hardlinks)
      && statbuf.st_nlink > 1
     ) {
         /* Add files/directories with links only once */
         if (is_in_ino_dev_hashtable(&statbuf)) {
             return 0;
         }
         add_to_ino_dev_hashtable(&statbuf, NULL);
     }
     if (S_ISDIR(statbuf.st_mode)) {
         DIR *dir;
         struct dirent *entry;
         char *newfile;
         dir = warn_opendir(filename);
         if (!dir) {
             G.status = EXIT_FAILURE;
             return sum;
         }
         while ((entry = readdir(dir))) {
             newfile = concat_subpath_file(filename, entry->d_name);
             if (newfile == NULL)
                 continue;
             ++G.du_depth;
             sum += du(newfile);
             --G.du_depth;
             free(newfile);
         }
         closedir(dir);
     } else {
         if (!(option_mask32 & OPT_a_files_too) && G.du_depth != 0)
             return sum;
     }
     if (G.du_depth <= G.max_print_depth) {
         print(sum, filename);
     }
     return sum;
 }
References add_to_ino_dev_hashtable(), bb_simple_perror_msg(), closedir(), concat_subpath_file(), dir, EXIT_FAILURE, filename, free, G, INT_MAX, is_in_ino_dev_hashtable(), lstat, newfile, NULL, OPT_a_files_too, OPT_b, OPT_l_hardlinks, OPT_x_one_FS, option_mask32, print(), readdir(), S_ISDIR, S_ISLNK, stat::st_blocks, stat::st_dev, stat::st_mode, stat::st_nlink, stat::st_size, stat(), and warn_opendir().
Referenced by du_main().
du_main()
int du_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 223 of file du.c.
 {
     unsigned long long total;
     int slink_depth_save;
     unsigned opt;
     INIT_G();
 #if ENABLE_FEATURE_HUMAN_READABLE
     IF_FEATURE_DU_DEFAULT_BLOCKSIZE_1K(G.disp_unit = 1024;)
     IF_NOT_FEATURE_DU_DEFAULT_BLOCKSIZE_1K(G.disp_unit = 512;)
     if (getenv("POSIXLY_CORRECT"))  /* TODO - a new libbb function? */
         G.disp_unit = 512;
 #else
     IF_FEATURE_DU_DEFAULT_BLOCKSIZE_1K(G.disp_k = 1;)
     /* IF_NOT_FEATURE_DU_DEFAULT_BLOCKSIZE_1K(G.disp_k = 0;) - G is pre-zeroed */
 #endif
     G.max_print_depth = INT_MAX;
     /* Note: SUSv3 specifies that -a and -s options cannot be used together
      * in strictly conforming applications.  However, it also says that some
      * du implementations may produce output when -a and -s are used together.
      * gnu du exits with an error code in this case.  We choose to simply
      * ignore -a.  This is consistent with -s being equivalent to -d 0.
      */
 #if ENABLE_FEATURE_HUMAN_READABLE
     opt = getopt32(argv, "^"
             "aHkLsxd:+lcbhm"
             "\0" "h-km:k-hm:m-hk:H-L:L-H:s-d:d-s",
             &G.max_print_depth
     );
     argv += optind;
     if (opt & OPT_b) {
         G.disp_unit = 1;
     }
     if (opt & OPT_h_for_humans) {
         G.disp_unit = 0;
     }
     if (opt & OPT_m_mbytes) {
         G.disp_unit = 1024*1024;
     }
     if (opt & OPT_k_kbytes) {
         G.disp_unit = 1024;
     }
 #else
     opt = getopt32(argv, "^"
             "aHkLsxd:+lcb"
             "\0" "H-L:L-H:s-d:d-s",
             &G.max_print_depth
     );
     argv += optind;
 # if !ENABLE_FEATURE_DU_DEFAULT_BLOCKSIZE_1K
     if (opt & OPT_k_kbytes) {
         G.disp_k = 1;
     }
 # endif
 #endif
     if (opt & OPT_H_follow_links) {
         G.slink_depth = 1;
     }
     if (opt & OPT_L_follow_links) {
         G.slink_depth = INT_MAX;
     }
     if (opt & OPT_s_total_norecurse) {
         G.max_print_depth = 0;
     }
     /* go through remaining args (if any) */
     if (!*argv) {
         *--argv = (char*)".";
         if (G.slink_depth == 1) {
             G.slink_depth = 0;
         }
     }
     slink_depth_save = G.slink_depth;
     total = 0;
     do {
         total += du(*argv);
         G.slink_depth = slink_depth_save;
     } while (*++argv);
     if (ENABLE_FEATURE_CLEAN_UP)
         reset_ino_dev_hashtable();
     if (opt & OPT_c_total)
         print(total, "total");
     fflush_stdout_and_exit(G.status);
 }
References argv, du(), fflush_stdout_and_exit(), G, getenv, getopt32(), INIT_G, INT_MAX, opt, OPT_b, OPT_c_total, OPT_H_follow_links, OPT_h_for_humans, OPT_k_kbytes, OPT_L_follow_links, OPT_m_mbytes, OPT_s_total_norecurse, optind, print(), reset_ino_dev_hashtable(), and total.
print()
static void print (unsigned long long size, const char * filename) static
Definition at line 109 of file du.c.
 {
     /* TODO - May not want to defer error checking here. */
 #if ENABLE_FEATURE_HUMAN_READABLE
 # if ENABLE_DESKTOP
     /* ~30 bytes of code for extra compat:
      * coreutils' du rounds sizes up:
      * for example,  1025k file is shown as "2" by du -m.
      * We round to nearest if human-readable [too hard to fix],
      * else (fixed scale such as -m), we round up. To that end,
      * add yet another half of the unit before displaying:
      */
     if (G.disp_unit)
         size += (G.disp_unit-1) / (unsigned)(512 * 2);
 # endif
     printf("%s\t%s\n",
             /* size x 512 / G.disp_unit.
              * If G.disp_unit == 0, show one fractional
              * and use suffixes
              */
             make_human_readable_str(size, (option_mask32 & OPT_b) ? 1 : 512, G.disp_unit),
             filename);
 #else
     if (G.disp_k) {
         if (!(option_mask32 & OPT_b)) {
             size++;
             size >>= 1;
         } else {
             size >>= 10;
         }
     }
     printf("%llu\t%s\n", size, filename);
 #endif
 }
References filename, G, make_human_readable_str(), OPT_b, option_mask32, printf, and size.
Referenced by du(), and du_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING