Fennix: Kernel/SystemCalls/Native.cpp File Reference
Native.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../syscalls.h"
#include "../kernel.h"
#include "../../Userspace/libs/include/libsys/base.h"
#include "../ipc.h"
Functions
static bool CheckTrust (int TrustLevel)
static int sys_exit (SyscallsFrame *Frame, int code)
static int sys_print (SyscallsFrame *Frame, char Char, int Index)
static uintptr_t sys_request_pages (SyscallsFrame *Frame, size_t Count)
static int sys_free_pages (SyscallsFrame *Frame, uintptr_t Address, size_t Count)
static int sys_detach_address (SyscallsFrame *Frame, uintptr_t Address)
static uintptr_t sys_kernelctl (SyscallsFrame *Frame, enum KCtl Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
static int sys_ipc (SyscallsFrame *Frame, enum IPCCommand Command, enum IPCType Type, int ID, int Flags, void *Buffer, size_t Size)
static uint64_t sys_file_open (SyscallsFrame *Frame, const char *Path, uint64_t Flags)
static int sys_file_close (SyscallsFrame *Frame, void *KernelPrivate)
static uint64_t sys_file_read (SyscallsFrame *Frame, void *KernelPrivate, uint64_t Offset, uint8_t *Buffer, uint64_t Size)
static uint64_t sys_file_write (SyscallsFrame *Frame, void *KernelPrivate, uint64_t Offset, uint8_t *Buffer, uint64_t Size)
static uint64_t sys_file_seek (SyscallsFrame *Frame, void *KernelPrivate, uint64_t Offset, int Whence)
static int sys_file_status (SyscallsFrame *Frame)
static int sys_sleep (SyscallsFrame *Frame, uint64_t Milliseconds)
static int sys_fork (SyscallsFrame *Frame)
static int sys_wait (SyscallsFrame *Frame)
static int sys_kill (SyscallsFrame *Frame)
static int sys_spawn (SyscallsFrame *Frame)
static int sys_spawn_thread (SyscallsFrame *Frame, uint64_t InstructionPointer)
static int sys_get_thread_list_of_process (SyscallsFrame *Frame)
static int sys_get_current_process (SyscallsFrame *Frame)
static int sys_get_current_thread (SyscallsFrame *Frame)
static int sys_get_current_process_id (SyscallsFrame *Frame)
static int sys_get_current_thread_id (SyscallsFrame *Frame)
static int sys_get_process_by_pid (SyscallsFrame *Frame)
static int sys_get_thread_by_tid (SyscallsFrame *Frame)
static int sys_kill_process (SyscallsFrame *Frame)
static int sys_kill_thread (SyscallsFrame *Frame)
static int sys_sys_reserved_create_process (SyscallsFrame *Frame)
static int sys_sys_reserved_create_thread (SyscallsFrame *Frame)
uintptr_t HandleNativeSyscalls (SyscallsFrame *Frame)
Variables
static int _ChildPID = 0
static void * NativeSyscallsTable []
Function Documentation
CheckTrust()
static bool CheckTrust (int TrustLevel) inline static
Definition at line 41 of file Native.cpp.
 {
     // SmartTimeoutLock(SyscallsLock, 10000); - This is already done in the caller
     Token token = TaskManager->GetCurrentThread()->Security.UniqueToken;
     if (TaskManager->GetSecurityManager()->IsTokenTrusted(token, TrustLevel))
         return true;
     warn("Thread %s(%lld) tried to access a system call \"%s\" with insufficient trust level",
          TaskManager->GetCurrentThread()->Name, TaskManager->GetCurrentThread()->ID,
          KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_extract_return_addr(__builtin_return_address(0))));
     debug("Token: token=%#lx, trust=%d", token, TaskManager->GetSecurityManager()->GetTokenTrustLevel(token));
     return false;
 }
References debug, Tasking::Task::GetCurrentThread(), Tasking::Task::GetSecurityManager(), SymbolResolver::Symbols::GetSymbolFromAddress(), Tasking::Security::GetTokenTrustLevel(), Tasking::TCB::ID, Tasking::Security::IsTokenTrusted(), KernelSymbolTable, Tasking::TCB::Name, Tasking::TCB::Security, TaskManager, Tasking::TaskSecurity::UniqueToken, and warn.
Referenced by sys_detach_address(), sys_exit(), sys_fork(), sys_free_pages(), sys_ipc(), sys_kernelctl(), sys_print(), sys_request_pages(), and sys_sleep().
HandleNativeSyscalls()
uintptr_t HandleNativeSyscalls (SyscallsFrame * Frame)
Definition at line 568 of file Native.cpp.
 {
 #if defined(a64)
     if (Frame->rax > sizeof(NativeSyscallsTable))
     {
         fixme("Syscall %ld not implemented", Frame->rax);
         return SYSCALL_NOT_IMPLEMENTED;
     }
     uintptr_t (*call)(uintptr_t, ...) = reinterpret_cast<uintptr_t (*)(uintptr_t, ...)>(NativeSyscallsTable[Frame->rax]);
     if (!call)
     {
         error("Syscall %#lx failed.", Frame->rax);
         return SYSCALL_INTERNAL_ERROR;
     }
     // debug("[%#lx]->( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
     //       Frame->rax,
     //       Frame->rdi, Frame->rsi, Frame->rdx, Frame->rcx, Frame->r8, Frame->r9);
     uintptr_t ret = call((uintptr_t)Frame, Frame->rdi, Frame->rsi, Frame->rdx, Frame->r10, Frame->r8, Frame->r9);
     Frame->rax = ret;
     return ret;
 #elif defined(a32)
     if (Frame->eax > sizeof(NativeSyscallsTable))
     {
         fixme("Syscall %ld not implemented", Frame->eax);
         return SYSCALL_NOT_IMPLEMENTED;
     }
     /* ... */
     return SYSCALL_INTERNAL_ERROR;
 #elif defined(aa64)
     return SYSCALL_INTERNAL_ERROR;
 #endif
 }
References error, fixme, NativeSyscallsTable, ret, SYSCALL_INTERNAL_ERROR, and SYSCALL_NOT_IMPLEMENTED.
Referenced by SystemCallsHandler().
sys_detach_address()
static int sys_detach_address (SyscallsFrame * Frame, uintptr_t Address) static
Definition at line 105 of file Native.cpp.
 {
     /* Only trusted threads can detach allocated addresses */
     if (!CheckTrust(TrustedByKernel | Trusted))
         return SYSCALL_ACCESS_DENIED;
     TaskManager->GetCurrentThread()->Memory->DetachAddress((void *)Address);
     UNUSED(Frame);
     return SYSCALL_OK;
 }
References Address, CheckTrust(), Tasking::Task::GetCurrentThread(), Tasking::TCB::Memory, SYSCALL_ACCESS_DENIED, SYSCALL_OK, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, and UNUSED.
sys_exit()
static int sys_exit (SyscallsFrame * Frame, int code) static
Definition at line 55 of file Native.cpp.
 {
     /* Allow everyone to exit */
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted | UnknownTrustLevel))
         return SYSCALL_ACCESS_DENIED;
     trace("Userspace thread %s(%lld) exited with code %#llx", TaskManager->GetCurrentThread()->Name, TaskManager->GetCurrentThread()->ID, code);
     TaskManager->GetCurrentThread()->ExitCode = code;
     TaskManager->GetCurrentThread()->Status = Tasking::TaskStatus::Terminated;
     UNUSED(Frame);
     return SYSCALL_OK;
 }
References CheckTrust(), Tasking::TCB::ExitCode, Tasking::Task::GetCurrentThread(), Tasking::TCB::ID, Tasking::TCB::Name, Tasking::TCB::Status, SYSCALL_ACCESS_DENIED, SYSCALL_OK, TaskManager, Tasking::Terminated, trace, Tasking::Trusted, Tasking::TrustedByKernel, Tasking::UnknownTrustLevel, Tasking::Untrusted, and UNUSED.
sys_file_close()
static int sys_file_close (SyscallsFrame * Frame, void * KernelPrivate) static
Definition at line 275 of file Native.cpp.
 {
     debug("(KernelPrivate: %#lx)", KernelPrivate);
     if (KernelPrivate)
     {
         VirtualFileSystem::File KPObj = *(VirtualFileSystem::File *)KernelPrivate;
         debug("Closed file %s (%d)", KPObj.Name, KPObj.Status);
         vfs->Close(KPObj);
         TaskManager->GetCurrentThread()->Memory->FreePages(KernelPrivate, TO_PAGES(sizeof(VirtualFileSystem::File)));
         return SYSCALL_OK;
     }
     return SYSCALL_INVALID_ARGUMENT;
     UNUSED(Frame);
 }
References VirtualFileSystem::Virtual::Close(), debug, Tasking::Task::GetCurrentThread(), Tasking::TCB::Memory, VirtualFileSystem::File::Name, VirtualFileSystem::File::Status, SYSCALL_INVALID_ARGUMENT, SYSCALL_OK, TaskManager, TO_PAGES, UNUSED, and vfs.
sys_file_open()
static uint64_t sys_file_open (SyscallsFrame * Frame, const char * Path, uint64_t Flags) static
Definition at line 250 of file Native.cpp.
 {
     debug("(Path: %s, Flags: %#lx)", Path, Flags);
     VirtualFileSystem::Node *cwd = nullptr;
     if (vfs->PathIsRelative(Path))
         cwd = TaskManager->GetCurrentProcess()->CurrentWorkingDirectory;
     else
         cwd = vfs->GetRootNode();
     VirtualFileSystem::File KPObj = vfs->Open(Path, cwd);
     if (!KPObj.IsOK())
     {
         debug("Failed to open file %s (%d)", Path, KPObj.Status);
         vfs->Close(KPObj);
         return SYSCALL_INTERNAL_ERROR;
     }
     VirtualFileSystem::File *KernelPrivate = (VirtualFileSystem::File *)TaskManager->GetCurrentThread()->Memory->RequestPages(TO_PAGES(sizeof(VirtualFileSystem::File)));
     *KernelPrivate = KPObj;
     debug("Opened file %s (%d)", KPObj.Name, KPObj.Status);
     return (uint64_t)KernelPrivate;
     UNUSED(Frame);
     UNUSED(Flags);
 }
References VirtualFileSystem::Virtual::Close(), Tasking::PCB::CurrentWorkingDirectory, debug, Flags, Tasking::Task::GetCurrentProcess(), Tasking::Task::GetCurrentThread(), VirtualFileSystem::Virtual::GetRootNode(), VirtualFileSystem::File::IsOK(), Tasking::TCB::Memory, VirtualFileSystem::File::Name, VirtualFileSystem::Virtual::Open(), VirtualFileSystem::Virtual::PathIsRelative(), VirtualFileSystem::File::Status, SYSCALL_INTERNAL_ERROR, TaskManager, TO_PAGES, UNUSED, and vfs.
sys_file_read()
static uint64_t sys_file_read (SyscallsFrame * Frame, void * KernelPrivate, uint64_t Offset, uint8_t * Buffer, uint64_t Size) static
Definition at line 291 of file Native.cpp.
 {
     if (KernelPrivate == nullptr)
         return 0;
     debug("(KernelPrivate: %#lx, Offset: %#lx, Buffer: %#lx, Size: %#lx)", KernelPrivate, Offset, Buffer, Size);
     return vfs->Read(*(VirtualFileSystem::File *)KernelPrivate, (size_t)Offset, Buffer, (size_t)Size);
     UNUSED(Frame);
 }
References debug, VirtualFileSystem::Virtual::Read(), Size, UNUSED, and vfs.
sys_file_seek()
static uint64_t sys_file_seek (SyscallsFrame * Frame, void * KernelPrivate, uint64_t Offset, int Whence) static
Definition at line 311 of file Native.cpp.
 {
     if (KernelPrivate == nullptr)
         return 0;
     debug("(KernelPrivate: %#lx, Offset: %#lx, Whence: %d)", KernelPrivate, Offset, Whence);
     VirtualFileSystem::File *KPObj = (VirtualFileSystem::File *)KernelPrivate;
     if (KPObj->node->Operator->Seek == nullptr)
         return SYSCALL_INTERNAL_ERROR;
     uint64_t ret = KPObj->node->Operator->Seek(KPObj->node, (size_t)Offset, (uint8_t)Whence);
     debug("Seek %s %ld", KPObj->Name, ret);
     return ret;
     UNUSED(Frame);
 }
References debug, VirtualFileSystem::File::Name, VirtualFileSystem::File::node, VirtualFileSystem::Node::Operator, ret, VirtualFileSystem::FileSystemOperations::Seek, SYSCALL_INTERNAL_ERROR, and UNUSED.
sys_file_status()
static int sys_file_status (SyscallsFrame * Frame) static
Definition at line 328 of file Native.cpp.
 {
     fixme("sys_file_status: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_file_write()
static uint64_t sys_file_write (SyscallsFrame * Frame, void * KernelPrivate, uint64_t Offset, uint8_t * Buffer, uint64_t Size) static
Definition at line 301 of file Native.cpp.
 {
     if (KernelPrivate == nullptr)
         return 0;
     debug("(KernelPrivate: %#lx, Offset: %#lx, Buffer: %#lx, Size: %#lx)", KernelPrivate, Offset, Buffer, Size);
     return vfs->Write(*(VirtualFileSystem::File *)KernelPrivate, (size_t)Offset, Buffer, (size_t)Size);
     UNUSED(Frame);
 }
References debug, Size, UNUSED, vfs, and VirtualFileSystem::Virtual::Write().
sys_fork()
static int sys_fork (SyscallsFrame * Frame) static
Definition at line 345 of file Native.cpp.
 {
     UNUSED(Frame);
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted))
         return SYSCALL_ACCESS_DENIED;
     fixme("sys_fork: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
     Tasking::PCB *Parent = TaskManager->GetCurrentThread()->Parent;
     Tasking::TCB *Thread = TaskManager->GetCurrentThread();
     Tasking::PCB *NewProcess = TaskManager->CreateProcess(Parent,
                                                           Parent->Name,
                                                           Parent->Security.TrustLevel,
                                                           Parent->ELFSymbolTable ? Parent->ELFSymbolTable->GetImage() : nullptr);
     if (!NewProcess)
     {
         error("Failed to create process for fork");
         return SYSCALL_ERROR;
     }
     strncpy(NewProcess->Name, Parent->Name, sizeof(NewProcess->Name));
     NewProcess->IPC->Fork(Parent->IPC); // FIXME: Do we need to do this?
     Tasking::TCB *NewThread = TaskManager->CreateThread(NewProcess,
                                                         0,
                                                         nullptr,
                                                         nullptr,
                                                         std::vector<AuxiliaryVector>(),
                                                         0,
                                                         Thread->Info.Architecture,
                                                         Thread->Info.Compatibility,
                                                         true);
     if (!NewThread)
     {
         error("Failed to create thread for fork");
         return SYSCALL_ERROR;
     }
     _ChildPID = (int)NewThread->ID;
     memcpy(NewThread->FPU, Thread->FPU, sizeof(CPU::x64::FXState));
     NewThread->Stack->Fork(Thread->Stack);
     strncpy(NewThread->Name, Thread->Name, sizeof(Thread->Name));
     NewThread->Info = Thread->Info;
 #ifdef a86
     NewThread->ShadowGSBase = Thread->ShadowGSBase;
     NewThread->GSBase = Thread->GSBase;
     NewThread->FSBase = Thread->FSBase;
 #endif
     CPU::Interrupts(CPU::Disable);
     static int RetChild = 0;
     static uint64_t ReturnAddress = 0;
     static uint64_t ChildStackPointer = 0;
 #if defined(a86)
     asmv("int $0x30"); /* This will trigger the IRQ16 instantly so we won't execute the next instruction */
 #elif defined(aa64)
     asmv("svc #0x30"); /* This will trigger the IRQ16 instantly so we won't execute the next instruction */
 #endif
     if (RetChild--)
     {
         /* We can't just return 0; because the CPUData->SystemCallStack is no longer valid */
         asmv("movq %0, %%rcx\n"
              :
              : "r"(ReturnAddress));
         asmv("movq $0, %rax\n"); // Return 0 to the child
         asmv("mov %0, %%rsp\n"
              :
              : "r"(ChildStackPointer));
         asmv("mov %0, %%rbp\n"
              :
              : "r"(ChildStackPointer));
         asmv("swapgs\n");  // Swap GS back to the user GS
         asmv("sti\n");     // Enable interrupts
         asmv("sysretq\n"); // Return to rcx address in user mode
     }
     RetChild = 1;
     ReturnAddress = Frame->ReturnAddress;
     ChildStackPointer = Frame->StackPointer;
     NewThread->Registers = Thread->Registers;
     debug("Forked thread \"%s\"(%d) to \"%s\"(%d)", Thread->Name, Thread->ID, NewThread->Name, NewThread->ID);
     NewThread->Status = Tasking::TaskStatus::Ready;
     if (_ChildPID == (int)TaskManager->GetCurrentThread()->ID)
         return 0;
     return (int)NewThread->ID;
 }
References _ChildPID, asmv(), CheckTrust(), Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), debug, CPU::Disable, Tasking::PCB::ELFSymbolTable, error, fixme, InterProcessCommunication::IPC::Fork(), Tasking::TCB::FPU, Tasking::Task::GetCurrentThread(), SymbolResolver::Symbols::GetImage(), Tasking::TCB::ID, Thread::ID, Tasking::TCB::Info, int, CPU::Interrupts(), Tasking::PCB::IPC, memcpy, Tasking::TCB::Name, Tasking::PCB::Name, Thread::Name, Tasking::TCB::Parent, Tasking::Ready, Tasking::PCB::Security, Tasking::TCB::Stack, Tasking::TCB::Status, strncpy(), SYSCALL_ACCESS_DENIED, SYSCALL_ERROR, SYSCALL_NOT_IMPLEMENTED, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, Tasking::TaskSecurity::TrustLevel, Tasking::Untrusted, and UNUSED.
sys_free_pages()
static int sys_free_pages (SyscallsFrame * Frame, uintptr_t Address, size_t Count) static
Definition at line 95 of file Native.cpp.
 {
     /* Allow everyone to free pages */
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted))
         return SYSCALL_ACCESS_DENIED;
     TaskManager->GetCurrentThread()->Memory->FreePages((void *)Address, Count + 1);
     UNUSED(Frame);
     return SYSCALL_OK;
 }
References Address, CheckTrust(), Tasking::Task::GetCurrentThread(), Tasking::TCB::Memory, SYSCALL_ACCESS_DENIED, SYSCALL_OK, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, Tasking::Untrusted, and UNUSED.
sys_get_current_process()
static int sys_get_current_process (SyscallsFrame * Frame) static
Definition at line 473 of file Native.cpp.
 {
     fixme("sys_get_current_process: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_get_current_process_id()
static int sys_get_current_process_id (SyscallsFrame * Frame) static
Definition at line 485 of file Native.cpp.
 {
     return (int)TaskManager->GetCurrentProcess()->ID;
 }
References Tasking::Task::GetCurrentProcess(), Tasking::PCB::ID, and TaskManager.
sys_get_current_thread()
static int sys_get_current_thread (SyscallsFrame * Frame) static
Definition at line 479 of file Native.cpp.
 {
     fixme("sys_get_current_thread: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_get_current_thread_id()
static int sys_get_current_thread_id (SyscallsFrame * Frame) static
Definition at line 490 of file Native.cpp.
 {
     return (int)TaskManager->GetCurrentThread()->ID;
 }
References Tasking::Task::GetCurrentThread(), Tasking::TCB::ID, and TaskManager.
sys_get_process_by_pid()
static int sys_get_process_by_pid (SyscallsFrame * Frame) static
Definition at line 495 of file Native.cpp.
 {
     fixme("sys_get_process_by_pid: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_get_thread_by_tid()
static int sys_get_thread_by_tid (SyscallsFrame * Frame) static
Definition at line 501 of file Native.cpp.
 {
     fixme("sys_get_thread_by_tid: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_get_thread_list_of_process()
static int sys_get_thread_list_of_process (SyscallsFrame * Frame) static
Definition at line 467 of file Native.cpp.
 {
     fixme("sys_get_thread_list_of_process: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_ipc()
static int sys_ipc (SyscallsFrame * Frame, enum IPCCommand Command, enum IPCType Type, int ID, int Flags, void * Buffer, size_t Size) static
Definition at line 241 of file Native.cpp.
 {
     /* Allow everyone to use IPC */
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted))
         return SYSCALL_ACCESS_DENIED;
     UNUSED(Frame);
     return TaskManager->GetCurrentProcess()->IPC->HandleSyscall(Command, Type, ID, Flags, Buffer, Size);
 }
References CheckTrust(), Command, Flags, Tasking::Task::GetCurrentProcess(), InterProcessCommunication::IPC::HandleSyscall(), ID, Tasking::PCB::IPC, Size, SYSCALL_ACCESS_DENIED, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, Type, Tasking::Untrusted, and UNUSED.
sys_kernelctl()
static uintptr_t sys_kernelctl (SyscallsFrame * Frame, enum KCtl Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4) static
Definition at line 115 of file Native.cpp.
 {
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted))
         return SYSCALL_ACCESS_DENIED;
     switch (Command)
     {
     case KCTL_GET_PID:
         return TaskManager->GetCurrentThread()->Parent->ID;
     case KCTL_GET_TID:
         return TaskManager->GetCurrentThread()->ID;
     case KCTL_GET_PAGE_SIZE:
         return PAGE_SIZE;
     case KCTL_IS_CRITICAL:
         return TaskManager->GetCurrentThread()->Security.IsCritical;
     case KCTL_REGISTER_ELF_LIB:
     {
         if (!CheckTrust(TrustedByKernel | Trusted))
             return SYSCALL_ACCESS_DENIED;
         char *Identifier = (char *)Arg1;
         const char *Path = (const char *)Arg2;
         if (!Identifier || !Path)
             return SYSCALL_INVALID_ARGUMENT;
         std::string FullPath = Path;
         int retries = 0;
     RetryReadPath:
         debug("KCTL_REGISTER_ELF_LIB: Trying to open %s", FullPath.c_str());
         VirtualFileSystem::File f = vfs->Open(FullPath.c_str());
         if (!f.IsOK())
         {
             FullPath.clear();
             switch (retries)
             {
             case 0:
                 FullPath = "/lib/";
                 break;
             case 1:
                 FullPath = "/usr/lib/";
                 break;
             case 2:
                 FullPath = "/";
                 break;
             case 3:
             {
                 // TODO: Check process binary path
                 break;
             }
             default:
             {
                 vfs->Close(f);
                 return SYSCALL_INVALID_ARGUMENT;
             }
             }
             FullPath += Path;
             vfs->Close(f);
             retries++;
             goto RetryReadPath;
         }
         vfs->Close(f);
         if (Execute::AddLibrary(Identifier, (void *)f.node->Address, f.node->Length))
             return SYSCALL_OK;
         else
             return SYSCALL_INTERNAL_ERROR;
     }
     case KCTL_GET_ELF_LIB_FILE:
     {
         if (!CheckTrust(TrustedByKernel | Trusted))
             return SYSCALL_ACCESS_DENIED;
         char *Identifier = (char *)Arg1;
         if (!Identifier)
             return 0;
         Execute::SharedLibraries lib = Execute::GetLibrary(Identifier);
         if (!lib.Address)
         {
             debug("Failed to get library address %#lx", (uintptr_t)lib.Address);
         }
         debug("Returning library address %#lx (%s)", (uintptr_t)lib.Address, Identifier);
         return (uintptr_t)lib.Address;
     }
     case KCTL_GET_ELF_LIB_MEMORY_IMAGE:
     {
         if (!CheckTrust(TrustedByKernel | Trusted))
             return SYSCALL_ACCESS_DENIED;
         char *Identifier = (char *)Arg1;
         if (!Identifier)
             return 0;
         Execute::SharedLibraries lib = Execute::GetLibrary(Identifier);
         if (!lib.MemoryImage)
         {
             debug("Failed to get library memory image %#lx", (uintptr_t)lib.MemoryImage);
         }
         debug("Returning memory image %#lx (%s)", (uintptr_t)lib.MemoryImage, Identifier);
         return (uintptr_t)lib.MemoryImage;
     }
     case KCTL_GET_FRAMEBUFFER_BUFFER:
         return r_cst(uint64_t, Display->GetBuffer(0)->Buffer);
     case KCTL_GET_FRAMEBUFFER_WIDTH:
         return Display->GetBuffer(0)->Width;
     case KCTL_GET_FRAMEBUFFER_HEIGHT:
         return Display->GetBuffer(0)->Height;
     case KCTL_GET_FRAMEBUFFER_SIZE:
         return Display->GetBuffer(0)->Size;
     default:
     {
         warn("KernelCTL: Unknown command: %lld", Command);
         return SYSCALL_INVALID_ARGUMENT;
     }
     }
     UNUSED(Arg1);
     UNUSED(Arg2);
     UNUSED(Arg3);
     UNUSED(Arg4);
     UNUSED(Frame);
 }
References Execute::AddLibrary(), Execute::SharedLibraries::Address, VirtualFileSystem::Node::Address, std::string::c_str(), CheckTrust(), std::string::clear(), VirtualFileSystem::Virtual::Close(), Command, debug, Display, Tasking::Task::GetCurrentThread(), Execute::GetLibrary(), Tasking::TCB::ID, Tasking::PCB::ID, Tasking::TaskSecurity::IsCritical, VirtualFileSystem::File::IsOK(), KCTL_GET_ELF_LIB_FILE, KCTL_GET_ELF_LIB_MEMORY_IMAGE, KCTL_GET_FRAMEBUFFER_BUFFER, KCTL_GET_FRAMEBUFFER_HEIGHT, KCTL_GET_FRAMEBUFFER_SIZE, KCTL_GET_FRAMEBUFFER_WIDTH, KCTL_GET_PAGE_SIZE, KCTL_GET_PID, KCTL_GET_TID, KCTL_IS_CRITICAL, KCTL_REGISTER_ELF_LIB, VirtualFileSystem::Node::Length, Execute::SharedLibraries::MemoryImage, VirtualFileSystem::File::node, VirtualFileSystem::Virtual::Open(), PAGE_SIZE, Tasking::TCB::Parent, Tasking::TCB::Security, SYSCALL_ACCESS_DENIED, SYSCALL_INTERNAL_ERROR, SYSCALL_INVALID_ARGUMENT, SYSCALL_OK, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, Tasking::Untrusted, UNUSED, vfs, and warn.
sys_kill()
static int sys_kill (SyscallsFrame * Frame) static
Definition at line 447 of file Native.cpp.
 {
     fixme("sys_kill: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_kill_process()
static int sys_kill_process (SyscallsFrame * Frame) static
Definition at line 507 of file Native.cpp.
 {
     fixme("sys_kill_process: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_kill_thread()
static int sys_kill_thread (SyscallsFrame * Frame) static
Definition at line 513 of file Native.cpp.
 {
     fixme("sys_kill_thread: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_print()
static int sys_print (SyscallsFrame * Frame, char Char, int Index) static
Definition at line 68 of file Native.cpp.
 {
     /* Only trusted threads can write to the kernel console */
     if (!CheckTrust(TrustedByKernel | Trusted))
         return SYSCALL_ACCESS_DENIED;
     char ret = Display->Print(Char, Index, true);
     if (!Config.BootAnimation && Index == 0)
 #ifdef DEBUG
         Display->SetBuffer(Index);
 #else
         if (Char == '\n')
             Display->SetBuffer(Index);
 #endif
     UNUSED(Frame);
     return ret;
 }
References KernelConfig::BootAnimation, CheckTrust(), Config, Display, ret, SYSCALL_ACCESS_DENIED, Tasking::Trusted, Tasking::TrustedByKernel, and UNUSED.
sys_request_pages()
static uintptr_t sys_request_pages (SyscallsFrame * Frame, size_t Count) static
Definition at line 86 of file Native.cpp.
 {
     /* Allow everyone to request pages */
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted))
         return SYSCALL_ACCESS_DENIED;
     UNUSED(Frame);
     return (uintptr_t)TaskManager->GetCurrentThread()->Memory->RequestPages(Count + 1, true);
 }
References CheckTrust(), Tasking::Task::GetCurrentThread(), Tasking::TCB::Memory, SYSCALL_ACCESS_DENIED, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, Tasking::Untrusted, and UNUSED.
sys_sleep()
static int sys_sleep (SyscallsFrame * Frame, uint64_t Milliseconds) static
Definition at line 334 of file Native.cpp.
 {
     UNUSED(Frame);
     if (!CheckTrust(TrustedByKernel | Trusted | Untrusted))
         return SYSCALL_ACCESS_DENIED;
     TaskManager->Sleep(Milliseconds);
     return 0;
 }
References CheckTrust(), Time::Milliseconds, Tasking::Task::Sleep(), SYSCALL_ACCESS_DENIED, TaskManager, Tasking::Trusted, Tasking::TrustedByKernel, Tasking::Untrusted, and UNUSED.
sys_spawn()
static int sys_spawn (SyscallsFrame * Frame) static
Definition at line 453 of file Native.cpp.
 {
     fixme("sys_spawn: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_spawn_thread()
static int sys_spawn_thread (SyscallsFrame * Frame, uint64_t InstructionPointer) static
Definition at line 459 of file Native.cpp.
 {
     Tasking::TCB *thread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (Tasking::IP)InstructionPointer);
     if (thread)
         return (int)thread->ID;
     return SYSCALL_ERROR;
 }
References Tasking::Task::CreateThread(), Tasking::Task::GetCurrentProcess(), Tasking::TCB::ID, SYSCALL_ERROR, and TaskManager.
sys_sys_reserved_create_process()
static int sys_sys_reserved_create_process (SyscallsFrame * Frame) static
Definition at line 519 of file Native.cpp.
 {
     fixme("sys_sys_reserved_create_process: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_sys_reserved_create_thread()
static int sys_sys_reserved_create_thread (SyscallsFrame * Frame) static
Definition at line 525 of file Native.cpp.
 {
     fixme("sys_sys_reserved_create_thread: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
sys_wait()
static int sys_wait (SyscallsFrame * Frame) static
Definition at line 441 of file Native.cpp.
 {
     fixme("sys_wait: %#lx", Frame);
     return SYSCALL_NOT_IMPLEMENTED;
 }
References fixme, and SYSCALL_NOT_IMPLEMENTED.
Variable Documentation
_ChildPID
int _ChildPID = 0 static
Definition at line 343 of file Native.cpp.
Referenced by sys_fork().
NativeSyscallsTable
void* NativeSyscallsTable[] static
Definition at line 531 of file Native.cpp.
Referenced by HandleNativeSyscalls().