Fennix Userspace: Userspace/musl/include/aio.h File Reference
aio.h File Reference
#include <features.h>
#include <signal.h>
#include <time.h>
#include <bits/alltypes.h>
Data Structures
struct aiocb
Macros
#define __NEED_ssize_t
#define __NEED_off_t
#define AIO_CANCELED 0
#define AIO_NOTCANCELED 1
#define AIO_ALLDONE 2
#define LIO_READ 0
#define LIO_WRITE 1
#define LIO_NOP 2
#define LIO_WAIT 0
#define LIO_NOWAIT 1
Functions
int aio_read (struct aiocb *)
int aio_write (struct aiocb *)
int aio_error (const struct aiocb *)
ssize_t aio_return (struct aiocb *)
int aio_cancel (int, struct aiocb *)
int aio_suspend (const struct aiocb *const [], int, const struct timespec *)
int aio_fsync (int, struct aiocb *)
int lio_listio (int, struct aiocb *__restrict const *__restrict, int, struct sigevent *__restrict)
Data Structure Documentation
aiocb
struct aiocb
Definition at line 17 of file aio.h.
Data Fields
char __dummy4[32-2 *sizeof(void *)]
volatile int __err
int __lock[2]
void * __next
void * __prev
ssize_t __ret
void * __td
volatile void * aio_buf
int aio_fildes
int aio_lio_opcode
size_t aio_nbytes
off_t aio_offset
int aio_reqprio
struct sigevent aio_sigevent
Macro Definition Documentation
__NEED_off_t
#define __NEED_off_t
Definition at line 13 of file aio.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 12 of file aio.h.
AIO_ALLDONE
#define AIO_ALLDONE 2
Definition at line 33 of file aio.h.
AIO_CANCELED
#define AIO_CANCELED 0
Definition at line 31 of file aio.h.
AIO_NOTCANCELED
#define AIO_NOTCANCELED 1
Definition at line 32 of file aio.h.
LIO_NOP
#define LIO_NOP 2
Definition at line 37 of file aio.h.
LIO_NOWAIT
#define LIO_NOWAIT 1
Definition at line 40 of file aio.h.
LIO_READ
#define LIO_READ 0
Definition at line 35 of file aio.h.
LIO_WAIT
#define LIO_WAIT 0
Definition at line 39 of file aio.h.
LIO_WRITE
#define LIO_WRITE 1
Definition at line 36 of file aio.h.
Function Documentation
aio_cancel()
int aio_cancel (int fd, struct aiocb * cb)
Definition at line 360 of file aio.c.
 {
     sigset_t allmask, origmask;
     int ret = AIO_ALLDONE;
     struct aio_thread *p;
     struct aio_queue *q;
     /* Unspecified behavior case. Report an error. */
     if (cb && fd != cb->aio_fildes) {
         errno = EINVAL;
         return -1;
     }
     sigfillset(&allmask);
     pthread_sigmask(SIG_BLOCK, &allmask, &origmask);
     errno = ENOENT;
     if (!(q = __aio_get_queue(fd, 0))) {
         if (errno == EBADF) ret = -1;
         goto done;
     }
     for (p = q->head; p; p = p->next) {
         if (cb && cb != p->cb) continue;
         /* Transition target from running to running-with-waiters */
         if (a_cas(&p->running, 1, -1)) {
             pthread_cancel(p->td);
             __wait(&p->running, 0, -1, 1);
             if (p->err == ECANCELED) ret = AIO_CANCELED;
         }
     }
     pthread_mutex_unlock(&q->lock);
 done:
     pthread_sigmask(SIG_SETMASK, &origmask, 0);
     return ret;
 }
References __aio_get_queue(), __wait(), a_cas, AIO_ALLDONE, AIO_CANCELED, aiocb::aio_fildes, done, EBADF, ECANCELED, EINVAL, ENOENT, errno, fd, aio_queue::head, aio_queue::lock, p, pthread_cancel(), pthread_mutex_unlock(), pthread_sigmask(), SIG_BLOCK, SIG_SETMASK, and sigfillset().
Referenced by __aio_close().
aio_error()
int aio_error (const struct aiocb * cb)
Definition at line 354 of file aio.c.
 {
     a_barrier();
     return cb->__err & 0x7fffffff;
 }
References aiocb::__err, a_barrier, and aio_args::cb.
Referenced by aio_suspend(), and lio_wait().
aio_fsync()
int aio_fsync (int op, struct aiocb * cb)
Definition at line 340 of file aio.c.
 {
     if (op != O_SYNC && op != O_DSYNC) {
         errno = EINVAL;
         return -1;
     }
     return submit(cb, op);
 }
References aio_args::cb, EINVAL, errno, O_DSYNC, O_SYNC, and submit().
aio_read()
int aio_read (struct aiocb * cb)
Definition at line 330 of file aio.c.
 {
     return submit(cb, LIO_READ);
 }
References aio_args::cb, LIO_READ, and submit().
Referenced by lio_listio().
aio_return()
ssize_t aio_return (struct aiocb * cb)
Definition at line 349 of file aio.c.
 {
     return cb->__ret;
 }
References aiocb::__ret, and aio_args::cb.
aio_suspend()
int aio_suspend (const struct aiocb * const cbs[], int cnt, const struct timespec * ts)
Definition at line 8 of file aio_suspend.c.
 {
     int i, tid = 0, ret, expect = 0;
     struct timespec at;
     volatile int dummy_fut = 0, *pfut;
     int nzcnt = 0;
     const struct aiocb *cb = 0;
     pthread_testcancel();
     if (cnt<0) {
         errno = EINVAL;
         return -1;
     }
     for (i=0; i<cnt; i++) if (cbs[i]) {
         if (aio_error(cbs[i]) != EINPROGRESS) return 0;
         nzcnt++;
         cb = cbs[i];
     }
     if (ts) {
         clock_gettime(CLOCK_MONOTONIC, &at);
         at.tv_sec += ts->tv_sec;
         if ((at.tv_nsec += ts->tv_nsec) >= 1000000000) {
             at.tv_nsec -= 1000000000;
             at.tv_sec++;
         }
     }
     for (;;) {
         for (i=0; i<cnt; i++)
             if (cbs[i] && aio_error(cbs[i]) != EINPROGRESS)
                 return 0;
         switch (nzcnt) {
         case 0:
             pfut = &dummy_fut;
             break;
         case 1:
             pfut = (void *)&cb->__err;
             expect = EINPROGRESS | 0x80000000;
             a_cas(pfut, EINPROGRESS, expect);
             break;
         default:
             pfut = &__aio_fut;
             if (!tid) tid = __pthread_self()->tid;
             expect = a_cas(pfut, 0, tid);
             if (!expect) expect = tid;
             /* Need to recheck the predicate before waiting. */
             for (i=0; i<cnt; i++)
                 if (cbs[i] && aio_error(cbs[i]) != EINPROGRESS)
                     return 0;
             break;
         }
         ret = __timedwait_cp(pfut, expect, CLOCK_MONOTONIC, ts?&at:0, 1);
         switch (ret) {
         case ETIMEDOUT:
             ret = EAGAIN;
         case ECANCELED:
         case EINTR:
             errno = ret;
             return -1;
         }
     }
 }
References __aio_fut, aiocb::__err, __pthread_self, __timedwait_cp(), a_cas, aio_error(), cnt, EAGAIN, ECANCELED, EINPROGRESS, EINTR, EINVAL, errno, ETIMEDOUT, i, pthread_testcancel(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by __aio_suspend_time32(), and lio_wait().
aio_write()
int aio_write (struct aiocb * cb)
Definition at line 335 of file aio.c.
 {
     return submit(cb, LIO_WRITE);
 }
References aio_args::cb, LIO_WRITE, and submit().
Referenced by lio_listio().
lio_listio()
int lio_listio (int , struct aiocb *__restrict const * __restrict, int , struct sigevent * __restrict)