Fennix Userspace: Userspace/apps/base/bash/lib/readline/examples/rlcat.c File Reference
rlcat.c File Reference
#include <sys/types.h>
#include "posixstat.h"
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <errno.h>
#include <readline/readline.h>
#include <readline/history.h>
Functions
void exit ()
static int stdcat ()
static void usage ()
int main (int argc, char **argv)
static int fcopy (FILE *fp)
int stdcat (int argc, char **argv)
Variables
int errno
int optind
char * optarg
static char * progname
static int vflag
Function Documentation
exit()
void exit ()
Referenced by main().
fcopy()
static int fcopy (FILE * fp) static
Definition at line 137 of file rlcat.c.
 {
   int c;
   char *x;
   while ((c = getc(fp)) != EOF)
     {
       if (vflag && isascii ((unsigned char)c) && isprint((unsigned char)c) == 0)
     {
       x = rl_untranslate_keyseq (c);
       if (fputs (x, stdout) == EOF)
         return 1;
     }
       else if (putchar (c) == EOF)
         return 1;
     }
   return (ferror (stdout));
 }
References c, EOF, ferror, fputs, getc, isascii(), isprint, putchar, rl_untranslate_keyseq(), stdout, vflag, and x.
Referenced by stdcat().
main()
int main (int argc , char ** argv)
Definition at line 79 of file rlcat.c.
 {
   char *temp;
   int opt, Vflag, Nflag;
 #ifdef HAVE_SETLOCALE
   setlocale (LC_ALL, ""):
 #endif
   progname = strrchr(argv[0], '/');
   if (progname == 0)
     progname = argv[0];
   else
     progname++;
   vflag = Vflag = Nflag = 0;
   while ((opt = getopt(argc, argv, "vEVN")) != EOF)
     {
       switch (opt)
     {
     case 'v':
       vflag = 1;
       break;
     case 'V':
       Vflag = 1;
       break;
     case 'E':
       Vflag = 0;
       break;
     case 'N':
       Nflag = 1;
       break;
     default:
       usage ();
       exit (2);
     }
     }
   argc -= optind;
   argv += optind;
   if (isatty(0) == 0 || argc || Nflag)
     return stdcat(argc, argv);
   rl_variable_bind ("editing-mode", Vflag ? "vi" : "emacs");
   while (temp = readline (""))
     {
       if (*temp)
         add_history (temp);
       printf ("%s\n", temp);
     }
   return (ferror (stdout));
 }
References add_history(), argc, argv, EOF, exit(), ferror, getopt(), isatty(), LC_ALL, opt, optind, printf(), progname, readline(), rl_variable_bind(), setlocale, stdcat(), stdout, strrchr(), usage(), and vflag.
stdcat() [1/2]
static int stdcat () static
Referenced by main().
stdcat() [2/2]
int stdcat (int argc, char ** argv)
Definition at line 158 of file rlcat.c.
 {
   int  i, fd, r;
   char *s;
   FILE *fp;
   if (argc == 0)
     return (fcopy(stdin));
   for (i = 0, r = 1; i < argc; i++)
     {
       if (*argv[i] == '-' && argv[i][1] == 0)
     fp = stdin;
       else
     {
       fp = fopen (argv[i], "r");
       if (fp == 0)
         {
           fprintf (stderr, "%s: %s: cannot open: %s\n", progname, argv[i], strerror(errno));
           continue;
         }
         }
       r = fcopy (fp);
       if (fp != stdin)
     fclose(fp);
     }
   return r;
 }
References argc, argv, errno, fclose(), fcopy(), fd, fopen(), fprintf(), i, progname, s, stderr, stdin, and strerror().
usage()
static void usage (void) static
Definition at line 73 of file rlcat.c.
 {
   fprintf (stderr, "%s: usage: %s [-vEVN] [filename]\n", progname, progname);
 }
References fprintf(), progname, and stderr.
Referenced by main().
Variable Documentation
errno
int errno extern
Referenced by stdcat().
optarg
char* optarg extern
Definition at line 10 of file getopt.c.
optind
int optind extern
Definition at line 11 of file getopt.c.
Referenced by main().
progname
char* progname static
Definition at line 69 of file rlcat.c.
Referenced by main(), stdcat(), and usage().
vflag
int vflag static
Definition at line 70 of file rlcat.c.
Referenced by fcopy(), and main().