Fennix: Userspace/apps/base/busybox/util-linux/wall.c File Reference
wall.c File Reference
#include "libbb.h"
Functions
int wall_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
wall_main()
int wall_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 32 of file wall.c.
 {
     struct utmpx *ut;
     char *msg;
     int fd;
     fd = STDIN_FILENO;
     if (argv[1]) {
         /* The applet is setuid.
          * Access to the file must be under user's uid/gid.
          */
         fd = xopen_as_uid_gid(argv[1], O_RDONLY, getuid(), getgid());
     }
     msg = xmalloc_read(fd, NULL);
     if (ENABLE_FEATURE_CLEAN_UP && argv[1])
         close(fd);
     setutxent();
     while ((ut = getutxent()) != NULL) {
         char *line;
         if (ut->ut_type != USER_PROCESS)
             continue;
         line = concat_path_file("/dev", ut->ut_line);
         xopen_xwrite_close(line, msg);
         free(line);
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         endutxent();
         free(msg);
     }
     return EXIT_SUCCESS;
 }
References argv, close(), concat_path_file(), endutxent(), EXIT_SUCCESS, fd, free, getgid, getuid, getutxent(), line, NULL, O_RDONLY, setutxent(), STDIN_FILENO, USER_PROCESS, utmpx::ut_line, utmpx::ut_type, xmalloc_read(), xopen_as_uid_gid(), and xopen_xwrite_close().