Fennix: Userspace/apps/base/busybox/networking/inetd.c File Reference
inetd.c File Reference
#include <syslog.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/un.h>
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct servtab_t
struct globals
Macros
#define ENABLE_FEATURE_INETD_SUPPORT_BUILTIN_CHARGEN 0
#define CNT_INTERVAL 60 /* servers in CNT_INTERVAL sec. */
#define RETRYTIME 60 /* retry after bind or server fail */
#define RLIMIT_NOFILE RLIMIT_OFILE
#define OPEN_MAX 64
#define FD_MARGIN 8
#define is_rpc_service(sep) 0
#define MAXARGV 20
#define G (*(struct globals*)bb_common_bufsiz1)
#define rlim_ofile_cur (G.rlim_ofile_cur)
#define rlim_ofile (G.rlim_ofile)
#define serv_list (G.serv_list)
#define global_queuelen (G.global_queuelen)
#define maxsock (G.maxsock)
#define prev_maxsock (G.prev_maxsock)
#define max_concurrency (G.max_concurrency)
#define alarm_armed (G.alarm_armed)
#define real_uid (G.real_uid)
#define config_filename (G.config_filename)
#define parser (G.parser)
#define default_local_hostname (G.default_local_hostname)
#define first_ps_byte (G.first_ps_byte)
#define last_ps_byte (G.last_ps_byte)
#define end_ring (G.end_ring)
#define ring_pos (G.ring_pos)
#define ring (G.ring)
#define allsock (G.allsock)
#define line (G.line)
#define INIT_G()
#define dbg(...) ((void)0)
#define SWAP(type, a, b) do { type c = (type)a; a = (type)b; b = (type)c; } while (0)
Typedefs
typedef struct servtab_t servtab_t
Enumerations
enum { LINE_SIZE = COMMON_BUFSIZE - offsetof(struct globals, line) }
Functions
static void maybe_close (int fd)
static len_and_sockaddr * xzalloc_lsa (int family)
static void rearm_alarm (void)
static void block_CHLD_HUP_ALRM (sigset_t *m)
static void restore_sigmask (sigset_t *m)
static void bump_nofile (void)
static void remove_fd_from_set (int fd)
static void add_fd_to_set (int fd)
static void recalculate_maxsock (void)
static void prepare_socket_fd (servtab_t *sep)
static int reopen_config_file (void)
static void close_config_file (void)
static void free_servtab_strings (servtab_t *cp)
static servtab_t * new_servtab (void)
static servtab_t * dup_servtab (servtab_t *sep)
static NOINLINE servtab_t * parse_one_line (void)
static servtab_t * insert_in_servlist (servtab_t *cp)
static int same_serv_addr_proto (servtab_t *old, servtab_t *new)
static void reread_config_file (int sig UNUSED_PARAM)
static void reap_child (int sig UNUSED_PARAM)
static void retry_network_setup (int sig UNUSED_PARAM)
static void clean_up_and_exit (int sig UNUSED_PARAM)
int inetd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Data Structure Documentation
servtab_t
struct servtab_t
Definition at line 290 of file inetd.c.
Data Fields
char * se_argv[MAXARGV+1]
smallint se_checked
unsigned se_count
family_t se_family
int se_fd
char * se_group
char * se_local_hostname
len_and_sockaddr * se_lsa
unsigned se_max
struct servtab_t * se_next
char * se_program
char * se_proto
smallint se_proto_no
char * se_service
socktype_t se_socktype
unsigned se_time
char * se_user
pid_t se_wait
Macro Definition Documentation
alarm_armed
#define alarm_armed (G.alarm_armed)
Definition at line 416 of file inetd.c.
allsock
#define allsock (G.allsock)
Definition at line 426 of file inetd.c.
CNT_INTERVAL
#define CNT_INTERVAL 60 /* servers in CNT_INTERVAL sec. */
Definition at line 266 of file inetd.c.
config_filename
#define config_filename (G.config_filename)
Definition at line 418 of file inetd.c.
dbg
#define dbg (...) ((void)0)
Definition at line 437 of file inetd.c.
default_local_hostname
#define default_local_hostname (G.default_local_hostname)
Definition at line 420 of file inetd.c.
ENABLE_FEATURE_INETD_SUPPORT_BUILTIN_CHARGEN
#define ENABLE_FEATURE_INETD_SUPPORT_BUILTIN_CHARGEN 0
Definition at line 263 of file inetd.c.
end_ring
#define end_ring (G.end_ring)
Definition at line 423 of file inetd.c.
FD_MARGIN
#define FD_MARGIN 8
Definition at line 280 of file inetd.c.
first_ps_byte
#define first_ps_byte (G.first_ps_byte)
Definition at line 421 of file inetd.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 407 of file inetd.c.
global_queuelen
#define global_queuelen (G.global_queuelen)
Definition at line 412 of file inetd.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    BUILD_BUG_ON(sizeof(G) > COMMON_BUFSIZE); \
    rlim_ofile_cur = OPEN_MAX; \
    global_queuelen = 128; \
    config_filename = "/etc/inetd.conf"; \
} while (0)
Definition at line 428 of file inetd.c.
is_rpc_service
#define is_rpc_service (sep) 0
Definition at line 305 of file inetd.c.
last_ps_byte
#define last_ps_byte (G.last_ps_byte)
Definition at line 422 of file inetd.c.
line
#define line (G.line)
Definition at line 427 of file inetd.c.
max_concurrency
#define max_concurrency (G.max_concurrency)
Definition at line 415 of file inetd.c.
MAXARGV
#define MAXARGV 20
Definition at line 325 of file inetd.c.
maxsock
#define maxsock (G.maxsock)
Definition at line 413 of file inetd.c.
OPEN_MAX
#define OPEN_MAX 64
Definition at line 276 of file inetd.c.
parser
#define parser (G.parser)
Definition at line 419 of file inetd.c.
prev_maxsock
#define prev_maxsock (G.prev_maxsock)
Definition at line 414 of file inetd.c.
real_uid
#define real_uid (G.real_uid)
Definition at line 417 of file inetd.c.
RETRYTIME
#define RETRYTIME 60 /* retry after bind or server fail */
Definition at line 267 of file inetd.c.
ring
#define ring (G.ring)
Definition at line 425 of file inetd.c.
ring_pos
#define ring_pos (G.ring_pos)
Definition at line 424 of file inetd.c.
rlim_ofile
#define rlim_ofile (G.rlim_ofile)
Definition at line 410 of file inetd.c.
rlim_ofile_cur
#define rlim_ofile_cur (G.rlim_ofile_cur)
Definition at line 409 of file inetd.c.
RLIMIT_NOFILE
#define RLIMIT_NOFILE RLIMIT_OFILE
Definition at line 272 of file inetd.c.
serv_list
#define serv_list (G.serv_list)
Definition at line 411 of file inetd.c.
SWAP
#define SWAP (type, a, b) do { type c = (type)a; a = (type)b; b = (type)c; } while (0)
Typedef Documentation
servtab_t
typedef struct servtab_t servtab_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LINE_SIZE
Definition at line 408 of file inetd.c.
 { LINE_SIZE = COMMON_BUFSIZE - offsetof(struct globals, line) };
Function Documentation
add_fd_to_set()
static void add_fd_to_set (int fd) static
Definition at line 564 of file inetd.c.
 {
     if (fd >= 0) {
         FD_SET(fd, &allsock);
         dbg("started listening on fd:%d\n", fd);
         if (maxsock >= 0 && fd > maxsock) {
             prev_maxsock = maxsock = fd;
             dbg("maxsock:%d\n", maxsock);
             if ((rlim_t)fd > rlim_ofile_cur - FD_MARGIN)
                 bump_nofile();
         }
     }
 }
References allsock, bump_nofile(), dbg, fd, FD_MARGIN, FD_SET, maxsock, prev_maxsock, and rlim_ofile_cur.
Referenced by prepare_socket_fd(), reap_child(), and reread_config_file().
block_CHLD_HUP_ALRM()
static void block_CHLD_HUP_ALRM (sigset_t * m) static
Definition at line 485 of file inetd.c.
 {
     sigemptyset(m);
     sigaddset(m, SIGCHLD);
     sigaddset(m, SIGHUP);
     sigaddset(m, SIGALRM);
     sigprocmask2(SIG_BLOCK, m); /* old sigmask is stored in m */
 }
References SIG_BLOCK, sigaddset(), SIGALRM, SIGCHLD, sigemptyset(), SIGHUP, and sigprocmask2().
Referenced by inetd_main(), insert_in_servlist(), and reread_config_file().
bump_nofile()
static void bump_nofile (void) static
Definition at line 531 of file inetd.c.
 {
     enum { FD_CHUNK = 32 };
     struct rlimit rl;
     /* Never fails under Linux (except if you pass it bad arguments) */
     getrlimit(RLIMIT_NOFILE, &rl);
     rl.rlim_cur = MIN(rl.rlim_max, rl.rlim_cur + FD_CHUNK);
     rl.rlim_cur = MIN(FD_SETSIZE, rl.rlim_cur + FD_CHUNK);
     if (rl.rlim_cur <= rlim_ofile_cur) {
         bb_error_msg("can't extend file limit, max = %d",
                         (int) rl.rlim_cur);
         return;
     }
     if (setrlimit(RLIMIT_NOFILE, &rl) < 0) {
         bb_simple_perror_msg("setrlimit");
         return;
     }
     rlim_ofile_cur = rl.rlim_cur;
 }
References bb_error_msg(), bb_simple_perror_msg(), FD_SETSIZE, getrlimit(), MIN, rlimit::rlim_cur, rlimit::rlim_max, rlim_ofile_cur, RLIMIT_NOFILE, and setrlimit().
Referenced by add_fd_to_set(), and recalculate_maxsock().
clean_up_and_exit()
static void clean_up_and_exit (int sig UNUSED_PARAM) static
Definition at line 1187 of file inetd.c.
 {
     servtab_t *sep;
     /* XXX signal race walking sep list */
     for (sep = serv_list; sep; sep = sep->se_next) {
         if (sep->se_fd == -1)
             continue;
         switch (sep->se_family) {
         case AF_UNIX:
             unlink(sep->se_service);
             break;
         default: /* case AF_INET, AF_INET6 */
 #if ENABLE_FEATURE_INETD_RPC
             if (sep->se_wait == 1 && is_rpc_service(sep))
                 unregister_rpc(sep);   /* XXX signal race */
 #endif
             break;
         }
         if (ENABLE_FEATURE_CLEAN_UP)
             close(sep->se_fd);
     }
     remove_pidfile_std_path_and_ext("inetd");
     exit_SUCCESS();
 }
References AF_UNIX, close(), exit_SUCCESS(), is_rpc_service, remove_pidfile_std_path_and_ext(), servtab_t::se_family, servtab_t::se_fd, servtab_t::se_next, servtab_t::se_service, servtab_t::se_wait, serv_list, and unlink().
Referenced by inetd_main().
close_config_file()
static void close_config_file (void) static
Definition at line 670 of file inetd.c.
 {
     if (parser) {
         config_close(parser);
         parser = NULL;
     }
 }
References config_close(), NULL, and parser.
Referenced by reread_config_file().
dup_servtab()
static servtab_t* dup_servtab (servtab_t * sep) static
Definition at line 700 of file inetd.c.
 {
     servtab_t *newtab;
     int argc;
     newtab = new_servtab();
     *newtab = *sep; /* struct copy */
     /* deep-copying strings */
     newtab->se_service = xstrdup(newtab->se_service);
     newtab->se_proto = xstrdup(newtab->se_proto);
     newtab->se_user = xstrdup(newtab->se_user);
     newtab->se_group = xstrdup(newtab->se_group);
     newtab->se_program = xstrdup(newtab->se_program);
     for (argc = 0; argc <= MAXARGV; argc++)
         newtab->se_argv[argc] = xstrdup(newtab->se_argv[argc]);
     /* NB: se_fd, se_hostaddr and se_next are always
      * overwrittend by callers, so we don't bother resetting them
      * to NULL/0/-1 etc */
     return newtab;
 }
References argc, MAXARGV, new_servtab(), servtab_t::se_argv, servtab_t::se_group, servtab_t::se_program, servtab_t::se_proto, servtab_t::se_service, servtab_t::se_user, and xstrdup().
Referenced by parse_one_line().
free_servtab_strings()
static void free_servtab_strings (servtab_t * cp) static
Definition at line 678 of file inetd.c.
 {
     int i;
     free(cp->se_local_hostname);
     free(cp->se_service);
     free(cp->se_proto);
     free(cp->se_user);
     free(cp->se_group);
     free(cp->se_lsa); /* not a string in fact */
     free(cp->se_program);
     for (i = 0; i < MAXARGV; i++)
         free(cp->se_argv[i]);
 }
References free, i, MAXARGV, servtab_t::se_argv, servtab_t::se_group, servtab_t::se_local_hostname, servtab_t::se_lsa, servtab_t::se_program, servtab_t::se_proto, servtab_t::se_service, and servtab_t::se_user.
Referenced by parse_one_line(), and reread_config_file().
inetd_main()
int inetd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1215 of file inetd.c.
 {
     struct sigaction sa, saved_pipe_handler;
     servtab_t *sep, *sep2;
     struct passwd *pwd;
     struct group *grp = grp; /* for compiler */
     int opt;
     pid_t pid;
     sigset_t omask;
     INIT_G();
     real_uid = getuid();
     if (real_uid != 0) /* run by non-root user */
         config_filename = NULL;
     /* -q N, -R N */
     opt = getopt32(argv, "R:+feq:+", &max_concurrency, &global_queuelen);
     argv += optind;
     //argc -= optind;
     if (argv[0])
         config_filename = argv[0];
     if (config_filename == NULL)
         bb_simple_error_msg_and_die("non-root must specify config file");
     if (!(opt & 2))
         bb_daemonize_or_rexec(0, argv - optind);
     else
         bb_sanitize_stdio();
     if (!(opt & 4)) {
         /* LOG_NDELAY: connect to syslog daemon NOW.
          * Otherwise, we may open syslog socket
          * in vforked child, making opened fds and syslog()
          * internal state inconsistent.
          * This was observed to leak file descriptors. */
         openlog(applet_name, LOG_PID | LOG_NDELAY, LOG_DAEMON);
         logmode = LOGMODE_SYSLOG;
     }
     if (real_uid == 0) {
         /* run by root, ensure groups vector gets trashed */
         gid_t gid = getgid();
         setgroups(1, &gid);
     }
     write_pidfile_std_path_and_ext("inetd");
     /* never fails under Linux (except if you pass it bad arguments) */
     getrlimit(RLIMIT_NOFILE, &rlim_ofile);
     rlim_ofile_cur = rlim_ofile.rlim_cur;
     if (rlim_ofile_cur == RLIM_INFINITY)    /* ! */
         rlim_ofile_cur = OPEN_MAX;
     memset(&sa, 0, sizeof(sa));
     /*sigemptyset(&sa.sa_mask); - memset did it */
     sigaddset(&sa.sa_mask, SIGALRM);
     sigaddset(&sa.sa_mask, SIGCHLD);
     sigaddset(&sa.sa_mask, SIGHUP);
 //FIXME: explain why no SA_RESTART
 //FIXME: retry_network_setup is unsafe to run in signal handler (many reasons)!
     sa.sa_handler = retry_network_setup;
     sigaction_set(SIGALRM, &sa);
 //FIXME: reread_config_file is unsafe to run in signal handler(many reasons)!
     sa.sa_handler = reread_config_file;
     sigaction_set(SIGHUP, &sa);
 //FIXME: reap_child is unsafe to run in signal handler (uses stdio)!
     sa.sa_handler = reap_child;
     sigaction_set(SIGCHLD, &sa);
 //FIXME: clean_up_and_exit is unsafe to run in signal handler (uses stdio)!
     sa.sa_handler = clean_up_and_exit;
     sigaction_set(SIGTERM, &sa);
     sa.sa_handler = clean_up_and_exit;
     sigaction_set(SIGINT, &sa);
     sa.sa_handler = SIG_IGN;
     sigaction(SIGPIPE, &sa, &saved_pipe_handler);
     reread_config_file(SIGHUP); /* load config from file */
     for (;;) {
         int ready_fd_cnt;
         int ctrl, accepted_fd, new_udp_fd;
         fd_set readable;
         if (maxsock < 0)
             recalculate_maxsock();
         readable = allsock; /* struct copy */
         /* if there are no fds to wait on, we will block
          * until signal wakes us up (maxsock == 0, but readable
          * never contains fds 0 and 1...) */
         ready_fd_cnt = select(maxsock + 1, &readable, NULL, NULL, NULL);
         if (ready_fd_cnt < 0) {
             if (errno != EINTR) {
                 bb_simple_perror_msg("select");
                 sleep1();
             }
             continue;
         }
         dbg("ready_fd_cnt:%d\n", ready_fd_cnt);
         for (sep = serv_list; ready_fd_cnt && sep; sep = sep->se_next) {
             if (sep->se_fd == -1 || !FD_ISSET(sep->se_fd, &readable))
                 continue;
             dbg("ready fd:%d\n", sep->se_fd);
             ready_fd_cnt--;
             ctrl = sep->se_fd;
             accepted_fd = -1;
             new_udp_fd = -1;
             if (!sep->se_wait) {
                 if (sep->se_socktype == SOCK_STREAM) {
                     ctrl = accepted_fd = accept(sep->se_fd, NULL, NULL);
                     dbg("accepted_fd:%d\n", accepted_fd);
                     if (ctrl < 0) {
                         if (errno != EINTR)
                             bb_perror_msg("accept (for %s)", sep->se_service);
                         continue;
                     }
                 }
                 /* "nowait" udp */
                 if (sep->se_socktype == SOCK_DGRAM
                  && sep->se_family != AF_UNIX
                 ) {
 /* How udp "nowait" works:
  * child peeks at (received and buffered by kernel) UDP packet,
  * performs connect() on the socket so that it is linked only
  * to this peer. But this also affects parent, because descriptors
  * are shared after fork() a-la dup(). When parent performs
  * select(), it will see this descriptor connected to the peer (!)
  * and still readable, will act on it and mess things up
  * (can create many copies of same child, etc).
  * Parent must create and use new socket instead. */
                     new_udp_fd = socket(sep->se_family, SOCK_DGRAM, 0);
                     dbg("new_udp_fd:%d\n", new_udp_fd);
                     if (new_udp_fd < 0) { /* error: eat packet, forget about it */
  udp_err:
                         recv(sep->se_fd, line, LINE_SIZE, MSG_DONTWAIT);
                         continue;
                     }
                     setsockopt_reuseaddr(new_udp_fd);
                     /* TODO: better do bind after fork in parent,
                      * so that we don't have two wildcard bound sockets
                      * even for a brief moment? */
                     if (bind(new_udp_fd, &sep->se_lsa->u.sa, sep->se_lsa->len) < 0) {
                         dbg("bind(new_udp_fd) failed\n");
                         close(new_udp_fd);
                         goto udp_err;
                     }
                     dbg("bind(new_udp_fd) succeeded\n");
                 }
             }
             block_CHLD_HUP_ALRM(&omask);
             pid = 0;
 #ifdef INETD_BUILTINS_ENABLED
             /* do we need to fork? */
             if (sep->se_builtin == NULL
              || (sep->se_socktype == SOCK_STREAM
                  && sep->se_builtin->bi_fork))
 #endif
             {
                 if (sep->se_max != 0) {
                     if (++sep->se_count == 1)
                         sep->se_time = monotonic_sec();
                     else if (sep->se_count >= sep->se_max) {
                         unsigned now = monotonic_sec();
                         /* did we accumulate se_max connects too quickly? */
                         if (now - sep->se_time <= CNT_INTERVAL) {
                             bb_error_msg("%s/%s: too many connections, pausing",
                                     sep->se_service, sep->se_proto);
                             remove_fd_from_set(sep->se_fd);
                             close(sep->se_fd);
                             sep->se_fd = -1;
                             sep->se_count = 0;
                             rearm_alarm(); /* will revive it in RETRYTIME sec */
                             restore_sigmask(&omask);
                             maybe_close(new_udp_fd);
                             maybe_close(accepted_fd);
                             continue; /* -> check next fd in fd set */
                         }
                         sep->se_count = 0;
                     }
                 }
                 /* on NOMMU, streamed chargen
                  * builtin wouldn't work, but it is
                  * not allowed on NOMMU (ifdefed out) */
 #ifdef INETD_BUILTINS_ENABLED
                 if (BB_MMU && sep->se_builtin)
                     pid = fork();
                 else
 #endif
                     pid = vfork();
                 if (pid < 0) { /* fork error */
                     bb_simple_perror_msg("vfork"+1);
                     sleep1();
                     restore_sigmask(&omask);
                     maybe_close(new_udp_fd);
                     maybe_close(accepted_fd);
                     continue; /* -> check next fd in fd set */
                 }
                 if (pid == 0)
                     pid--; /* -1: "we did fork and we are child" */
             }
             /* if pid == 0 here, we didn't fork */
             if (pid > 0) { /* parent */
                 if (sep->se_wait) {
                     /* wait: we passed socket to child,
                      * will wait for child to terminate */
                     sep->se_wait = pid;
                     remove_fd_from_set(sep->se_fd);
                 }
                 if (new_udp_fd >= 0) {
                     /* udp nowait: child connected the socket,
                      * we created and will use new, unconnected one */
                     xmove_fd(new_udp_fd, sep->se_fd);
                     dbg("moved new_udp_fd:%d to sep->se_fd:%d\n", new_udp_fd, sep->se_fd);
                 }
                 restore_sigmask(&omask);
                 maybe_close(accepted_fd);
                 continue; /* -> check next fd in fd set */
             }
             /* we are either child or didn't fork at all */
 #ifdef INETD_BUILTINS_ENABLED
             if (sep->se_builtin) {
                 if (pid) { /* "pid" is -1: we did fork */
                     close(sep->se_fd); /* listening socket */
                     dbg("closed sep->se_fd:%d\n", sep->se_fd);
                     logmode = LOGMODE_NONE; /* make xwrite etc silent */
                 }
                 restore_sigmask(&omask);
                 if (sep->se_socktype == SOCK_STREAM)
                     sep->se_builtin->bi_stream_fn(ctrl, sep);
                 else
                     sep->se_builtin->bi_dgram_fn(ctrl, sep);
                 if (pid) /* we did fork */
                     _exit(EXIT_FAILURE);
                 maybe_close(accepted_fd);
                 continue; /* -> check next fd in fd set */
             }
 #endif
             /* child */
             setsid();
             /* "nowait" udp */
             if (new_udp_fd >= 0) {
                 len_and_sockaddr *lsa;
                 int r;
                 close(new_udp_fd);
                 dbg("closed new_udp_fd:%d\n", new_udp_fd);
                 lsa = xzalloc_lsa(sep->se_family);
                 /* peek at the packet and remember peer addr */
                 r = recvfrom(ctrl, NULL, 0, MSG_PEEK|MSG_DONTWAIT,
                     &lsa->u.sa, &lsa->len);
                 if (r < 0)
                     goto do_exit1;
                 /* make this socket "connected" to peer addr:
                  * only packets from this peer will be recv'ed,
                  * and bare write()/send() will work on it */
                 connect(ctrl, &lsa->u.sa, lsa->len);
                 dbg("connected ctrl:%d to remote peer\n", ctrl);
                 free(lsa);
             }
             /* prepare env and exec program */
             pwd = getpwnam(sep->se_user);
             if (pwd == NULL) {
                 bb_error_msg("%s: no such %s", sep->se_user, "user");
                 goto do_exit1;
             }
             if (sep->se_group && (grp = getgrnam(sep->se_group)) == NULL) {
                 bb_error_msg("%s: no such %s", sep->se_group, "group");
                 goto do_exit1;
             }
             if (real_uid != 0 && real_uid != pwd->pw_uid) {
                 /* a user running private inetd */
                 bb_simple_error_msg("non-root must run services as himself");
                 goto do_exit1;
             }
             if (pwd->pw_uid != real_uid) {
                 if (sep->se_group)
                     pwd->pw_gid = grp->gr_gid;
                 /* initgroups, setgid, setuid: */
                 change_identity(pwd);
             } else if (sep->se_group) {
                 xsetgid(grp->gr_gid);
                 setgroups(1, &grp->gr_gid);
             }
             if (rlim_ofile.rlim_cur != rlim_ofile_cur)
                 if (setrlimit(RLIMIT_NOFILE, &rlim_ofile) < 0)
                     bb_simple_perror_msg("setrlimit");
             /* closelog(); - WRONG. we are after vfork,
              * this may confuse syslog() internal state.
              * Let's hope libc sets syslog fd to CLOEXEC...
              */
             xmove_fd(ctrl, STDIN_FILENO);
             xdup2(STDIN_FILENO, STDOUT_FILENO);
             dbg("moved ctrl:%d to fd 0,1[,2]\n", ctrl);
             /* manpages of inetd I managed to find either say
              * that stderr is also redirected to the network,
              * or do not talk about redirection at all (!) */
             if (!sep->se_wait) /* only for usual "tcp nowait" */
                 xdup2(STDIN_FILENO, STDERR_FILENO);
             /* NB: among others, this loop closes listening sockets
              * for nowait stream children */
             for (sep2 = serv_list; sep2; sep2 = sep2->se_next)
                 if (sep2->se_fd != ctrl)
                     maybe_close(sep2->se_fd);
             sigaction_set(SIGPIPE, &saved_pipe_handler);
             restore_sigmask(&omask);
             dbg("execing:'%s'\n", sep->se_program);
             BB_EXECVP(sep->se_program, sep->se_argv);
             bb_perror_msg("can't execute '%s'", sep->se_program);
  do_exit1:
             /* eat packet in udp case */
             if (sep->se_socktype != SOCK_STREAM)
                 recv(0, line, LINE_SIZE, MSG_DONTWAIT);
             _exit(EXIT_FAILURE);
         } /* for (sep = servtab...) */
     } /* for (;;) */
 }
References _exit(), accept(), AF_UNIX, allsock, applet_name, argv, bb_daemonize_or_rexec, bb_error_msg(), BB_EXECVP, BB_MMU, bb_perror_msg(), bb_sanitize_stdio(), bb_simple_error_msg(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), bind(), block_CHLD_HUP_ALRM(), change_identity(), clean_up_and_exit(), close(), CNT_INTERVAL, config_filename, connect(), ctrl(), dbg, EINTR, errno, EXIT_FAILURE, FD_ISSET, fork(), free, getgid, getgrnam, getopt32(), getpwnam, getrlimit(), getuid, global_queuelen, group::gr_gid, INIT_G, LINE_SIZE, LOG_DAEMON, LOG_NDELAY, LOG_PID, logmode, LOGMODE_NONE, LOGMODE_SYSLOG, lsa, max_concurrency, maxsock, maybe_close(), memset, monotonic_sec(), MSG_DONTWAIT, MSG_PEEK, NULL, OPEN_MAX, openlog(), opt, optind, pid, passwd::pw_gid, passwd::pw_uid, real_uid, reap_child(), rearm_alarm(), recalculate_maxsock(), recv(), recvfrom(), remove_fd_from_set(), reread_config_file(), restore_sigmask(), retry_network_setup(), RLIM_INFINITY, rlim_ofile, rlim_ofile_cur, RLIMIT_NOFILE, select(), serv_list, setgroups(), setrlimit(), setsid(), setsockopt_reuseaddr(), SIG_IGN, sigaction_set(), sigaddset(), SIGALRM, SIGCHLD, SIGHUP, SIGINT, SIGPIPE, SIGTERM, sleep1(), SOCK_DGRAM, SOCK_STREAM, socket(), STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, vfork(), write_pidfile_std_path_and_ext(), xdup2(), xmove_fd(), xsetgid(), and xzalloc_lsa().
insert_in_servlist()
static servtab_t* insert_in_servlist (servtab_t * cp) static
Definition at line 938 of file inetd.c.
 {
     servtab_t *sep;
     sigset_t omask;
     sep = new_servtab();
     *sep = *cp; /* struct copy */
     sep->se_fd = -1;
 #if ENABLE_FEATURE_INETD_RPC
     sep->se_rpcprog = -1;
 #endif
     block_CHLD_HUP_ALRM(&omask);
     sep->se_next = serv_list;
     serv_list = sep;
     restore_sigmask(&omask);
     return sep;
 }
References block_CHLD_HUP_ALRM(), new_servtab(), restore_sigmask(), servtab_t::se_fd, servtab_t::se_next, and serv_list.
Referenced by reread_config_file().
maybe_close()
static void maybe_close (int fd) static
Definition at line 450 of file inetd.c.
 {
     if (fd >= 0) {
         close(fd);
         dbg("closed fd:%d\n", fd);
     }
 }
References close(), dbg, and fd.
Referenced by inetd_main(), and reread_config_file().
new_servtab()
static servtab_t* new_servtab (void) static
Definition at line 693 of file inetd.c.
 {
     servtab_t *newtab = xzalloc(sizeof(servtab_t));
     newtab->se_fd = -1; /* paranoia */
     return newtab;
 }
References servtab_t::se_fd, and xzalloc().
Referenced by dup_servtab(), insert_in_servlist(), and parse_one_line().
parse_one_line()
static NOINLINE servtab_t* parse_one_line (void) static
Definition at line 723 of file inetd.c.
 {
     int argc;
     char *token[6+MAXARGV];
     char *p, *arg;
     char *hostdelim;
     servtab_t *sep;
     servtab_t *nsep;
  new:
     sep = new_servtab();
  more:
     argc = config_read(parser, token, 6+MAXARGV, 1, "# \t", PARSE_NORMAL);
     if (!argc) {
         free(sep);
         return NULL;
     }
     /* [host:]service socktype proto wait user[:group] prog [args] */
     /* Check for "host:...." line */
     arg = token[0];
     hostdelim = strrchr(arg, ':');
     if (hostdelim) {
         *hostdelim = '\0';
         sep->se_local_hostname = xstrdup(arg);
         arg = hostdelim + 1;
         if (*arg == '\0' && argc == 1) {
             /* Line has just "host:", change the
              * default host for the following lines. */
             free(default_local_hostname);
             default_local_hostname = sep->se_local_hostname;
             /*sep->se_local_hostname = NULL; - redundant */
             /* (we'll overwrite this field anyway) */
             goto more;
         }
     } else
         sep->se_local_hostname = xstrdup(default_local_hostname);
     /* service socktype proto wait user[:group] prog [args] */
     sep->se_service = xstrdup(arg);
     /* socktype proto wait user[:group] prog [args] */
     if (argc < 6) {
  parse_err:
         bb_error_msg("parse error on line %u, line is ignored",
                 parser->lineno);
         /* Just "goto more" can make sep to carry over e.g.
          * "rpc"-ness (by having se_rpcver_lo != 0).
          * We will be more paranoid: */
         free_servtab_strings(sep);
         free(sep);
         goto new;
     }
     {
         static const int8_t SOCK_xxx[] ALIGN1 = {
             -1,
             SOCK_STREAM, SOCK_DGRAM, SOCK_RDM,
             SOCK_SEQPACKET, SOCK_RAW
         };
         sep->se_socktype = SOCK_xxx[1 + index_in_strings(
             "stream""\0" "dgram""\0" "rdm""\0"
             "seqpacket""\0" "raw""\0"
             , token[1])];
     }
     /* {unix,[rpc/]{tcp,udp}[6]} wait user[:group] prog [args] */
     sep->se_proto = arg = xstrdup(token[2]);
     if (strcmp(arg, "unix") == 0) {
         sep->se_family = AF_UNIX;
     } else {
         char *six;
         sep->se_family = AF_INET;
         six = last_char_is(arg, '6');
         if (six) {
 #if ENABLE_FEATURE_IPV6
             *six = '\0';
             sep->se_family = AF_INET6;
 #else
             bb_error_msg("%s: no support for IPv6", sep->se_proto);
             goto parse_err;
 #endif
         }
         if (is_prefixed_with(arg, "rpc/")) {
 #if ENABLE_FEATURE_INETD_RPC
             unsigned n;
             arg += 4;
             p = strchr(sep->se_service, '/');
             if (p == NULL) {
                 bb_error_msg("no rpc version: '%s'", sep->se_service);
                 goto parse_err;
             }
             *p++ = '\0';
             n = bb_strtou(p, &p, 10);
             if (n > INT_MAX) {
  bad_ver_spec:
                 bb_simple_error_msg("bad rpc version");
                 goto parse_err;
             }
             sep->se_rpcver_lo = sep->se_rpcver_hi = n;
             if (*p == '-') {
                 p++;
                 n = bb_strtou(p, &p, 10);
                 if (n > INT_MAX || (int)n < sep->se_rpcver_lo)
                     goto bad_ver_spec;
                 sep->se_rpcver_hi = n;
             }
             if (*p != '\0')
                 goto bad_ver_spec;
 #else
             bb_simple_error_msg("no support for rpc services");
             goto parse_err;
 #endif
         }
         /* we don't really need getprotobyname()! */
         if (strcmp(arg, "tcp") == 0)
             sep->se_proto_no = IPPROTO_TCP; /* = 6 */
         if (strcmp(arg, "udp") == 0)
             sep->se_proto_no = IPPROTO_UDP; /* = 17 */
         if (six)
             *six = '6';
         if (!sep->se_proto_no) /* not tcp/udp?? */
             goto parse_err;
     }
     /* [no]wait[.max] user[:group] prog [args] */
     arg = token[3];
     sep->se_max = max_concurrency;
     p = strchr(arg, '.');
     if (p) {
         *p++ = '\0';
         sep->se_max = bb_strtou(p, NULL, 10);
         if (errno)
             goto parse_err;
     }
     sep->se_wait = (arg[0] != 'n' || arg[1] != 'o');
     if (!sep->se_wait) /* "no" seen */
         arg += 2;
     if (strcmp(arg, "wait") != 0)
         goto parse_err;
     /* user[:group] prog [args] */
     sep->se_user = xstrdup(token[4]);
     arg = strchr(sep->se_user, '.');
     if (arg == NULL)
         arg = strchr(sep->se_user, ':');
     if (arg) {
         *arg++ = '\0';
         sep->se_group = xstrdup(arg);
     }
     /* prog [args] */
     sep->se_program = xstrdup(token[5]);
 #ifdef INETD_BUILTINS_ENABLED
     if (strcmp(sep->se_program, "internal") == 0
      && strlen(sep->se_service) <= 7
      && (sep->se_socktype == SOCK_STREAM
          || sep->se_socktype == SOCK_DGRAM)
     ) {
         unsigned i;
         for (i = 0; i < ARRAY_SIZE(builtins); i++)
             if (strncmp(builtins[i].bi_service7, sep->se_service, 7) == 0)
                 goto found_bi;
         bb_error_msg("unknown internal service %s", sep->se_service);
         goto parse_err;
  found_bi:
         sep->se_builtin = &builtins[i];
         /* stream builtins must be "nowait", dgram must be "wait" */
         if (sep->se_wait != (sep->se_socktype == SOCK_DGRAM))
             goto parse_err;
     }
 #endif
     argc = 0;
     while (argc < MAXARGV && (arg = token[6+argc]) != NULL)
         sep->se_argv[argc++] = xstrdup(arg);
     /* Some inetd.conf files have no argv's, not even argv[0].
      * Fix them up.
      * (Technically, programs can be execed with argv[0] = NULL,
      * but many programs do not like that at all) */
     if (argc == 0)
         sep->se_argv[0] = xstrdup(sep->se_program);
     /* catch mixups. "<service> stream udp ..." == wtf */
     if (sep->se_socktype == SOCK_STREAM) {
         if (sep->se_proto_no == IPPROTO_UDP)
             goto parse_err;
     }
     if (sep->se_socktype == SOCK_DGRAM) {
         if (sep->se_proto_no == IPPROTO_TCP)
             goto parse_err;
     }
     //bb_error_msg(
     //  "ENTRY[%s][%s][%s][%d][%d][%d][%d][%d][%s][%s][%s]",
     //  sep->se_local_hostname, sep->se_service, sep->se_proto, sep->se_wait, sep->se_proto_no,
     //  sep->se_max, sep->se_count, sep->se_time, sep->se_user, sep->se_group, sep->se_program);
     /* check if the hostname specifier is a comma separated list
      * of hostnames. we'll make new entries for each address. */
     while ((hostdelim = strrchr(sep->se_local_hostname, ',')) != NULL) {
         nsep = dup_servtab(sep);
         /* NUL terminate the hostname field of the existing entry,
          * and make a dup for the new entry. */
         *hostdelim++ = '\0';
         nsep->se_local_hostname = xstrdup(hostdelim);
         nsep->se_next = sep->se_next;
         sep->se_next = nsep;
     }
     /* was doing it here: */
     /* DNS resolution, create copies for each IP address */
     /* IPv6-ization destroyed it :( */
     return sep;
 }
References AF_INET, AF_INET6, AF_UNIX, ALIGN1, argc, ARRAY_SIZE, bb_error_msg(), bb_simple_error_msg(), bb_strtou(), config_read, default_local_hostname, dup_servtab(), errno, free, free_servtab_strings(), i, index_in_strings(), INT_MAX, IPPROTO_TCP, IPPROTO_UDP, is_prefixed_with(), last_char_is(), max_concurrency, MAXARGV, n, new_servtab(), NULL, p, PARSE_NORMAL, parser, servtab_t::se_argv, servtab_t::se_family, servtab_t::se_group, servtab_t::se_local_hostname, servtab_t::se_max, servtab_t::se_next, servtab_t::se_program, servtab_t::se_proto, servtab_t::se_proto_no, servtab_t::se_service, servtab_t::se_socktype, servtab_t::se_user, servtab_t::se_wait, SOCK_DGRAM, SOCK_RAW, SOCK_RDM, SOCK_SEQPACKET, SOCK_STREAM, strchr(), strcmp, strlen(), strncmp(), strrchr(), and xstrdup().
Referenced by reread_config_file().
prepare_socket_fd()
static void prepare_socket_fd (servtab_t * sep) static
Definition at line 596 of file inetd.c.
 {
     int r, fd;
     fd = socket(sep->se_family, sep->se_socktype, 0);
     if (fd < 0) {
         bb_simple_perror_msg("socket");
         return;
     }
     setsockopt_reuseaddr(fd);
 #if ENABLE_FEATURE_INETD_RPC
     if (is_rpc_service(sep)) {
         struct passwd *pwd;
         /* zero out the port for all RPC services; let bind()
          * find one. */
         set_nport(&sep->se_lsa->u.sa, 0);
         /* for RPC services, attempt to use a reserved port
          * if they are going to be running as root. */
         if (real_uid == 0 && sep->se_family == AF_INET
          && (pwd = getpwnam(sep->se_user)) != NULL
          && pwd->pw_uid == 0
         ) {
             r = bindresvport(fd, &sep->se_lsa->u.sin);
         } else {
             r = bind(fd, &sep->se_lsa->u.sa, sep->se_lsa->len);
         }
         if (r == 0) {
             int saveerrno = errno;
             /* update lsa with port# */
             getsockname(fd, &sep->se_lsa->u.sa, &sep->se_lsa->len);
             errno = saveerrno;
         }
     } else
 #endif
     {
         if (sep->se_family == AF_UNIX) {
             struct sockaddr_un *sun;
             sun = (struct sockaddr_un*)&(sep->se_lsa->u.sa);
             unlink(sun->sun_path);
         }
         r = bind(fd, &sep->se_lsa->u.sa, sep->se_lsa->len);
     }
     if (r < 0) {
         bb_perror_msg("%s/%s: bind",
                 sep->se_service, sep->se_proto);
         close(fd);
         rearm_alarm();
         return;
     }
     if (sep->se_socktype == SOCK_STREAM) {
         listen(fd, global_queuelen);
         dbg("new sep->se_fd:%d (stream)\n", fd);
     } else {
         dbg("new sep->se_fd:%d (!stream)\n", fd);
     }
     add_fd_to_set(fd);
     sep->se_fd = fd;
 }
References add_fd_to_set(), AF_INET, AF_UNIX, bb_perror_msg(), bb_simple_perror_msg(), bind(), close(), dbg, errno, fd, getpwnam, getsockname(), global_queuelen, is_rpc_service, len_and_sockaddr::len, listen(), NULL, passwd::pw_uid, real_uid, rearm_alarm(), servtab_t::se_family, servtab_t::se_fd, servtab_t::se_lsa, servtab_t::se_proto, servtab_t::se_service, servtab_t::se_socktype, servtab_t::se_user, set_nport(), setsockopt_reuseaddr(), SOCK_STREAM, socket(), sockaddr_un::sun_path, len_and_sockaddr::u, and unlink().
Referenced by reread_config_file(), and retry_network_setup().
reap_child()
static void reap_child (int sig UNUSED_PARAM) static
Definition at line 1140 of file inetd.c.
 {
     pid_t pid;
     int status;
     servtab_t *sep;
     int save_errno = errno;
     for (;;) {
         pid = wait_any_nohang(&status);
         if (pid <= 0)
             break;
         for (sep = serv_list; sep; sep = sep->se_next) {
             if (sep->se_wait != pid)
                 continue;
             /* One of our "wait" services */
             if (WIFEXITED(status) && WEXITSTATUS(status))
                 bb_error_msg("%s: exit status %u",
                         sep->se_program, WEXITSTATUS(status));
             else if (WIFSIGNALED(status))
                 bb_error_msg("%s: exit signal %u",
                         sep->se_program, WTERMSIG(status));
             sep->se_wait = 1;
             add_fd_to_set(sep->se_fd);
             break;
         }
     }
     errno = save_errno;
 }
References add_fd_to_set(), bb_error_msg(), errno, pid, servtab_t::se_fd, servtab_t::se_next, servtab_t::se_program, servtab_t::se_wait, serv_list, status, wait_any_nohang(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by inetd_main().
rearm_alarm()
static void rearm_alarm (void) static
Definition at line 477 of file inetd.c.
 {
     if (!alarm_armed) {
         alarm_armed = 1;
         alarm(RETRYTIME);
     }
 }
References alarm(), alarm_armed, and RETRYTIME.
Referenced by inetd_main(), and prepare_socket_fd().
recalculate_maxsock()
static void recalculate_maxsock (void) static
Definition at line 578 of file inetd.c.
 {
     int fd = 0;
     /* We may have no services, in this case maxsock should still be >= 0
      * (code elsewhere is not happy with maxsock == -1) */
     maxsock = 0;
     while (fd <= prev_maxsock) {
         if (FD_ISSET(fd, &allsock))
             maxsock = fd;
         fd++;
     }
     dbg("recalculated maxsock:%d\n", maxsock);
     prev_maxsock = maxsock;
     if ((rlim_t)maxsock > rlim_ofile_cur - FD_MARGIN)
         bump_nofile();
 }
References allsock, bump_nofile(), dbg, fd, FD_ISSET, FD_MARGIN, maxsock, prev_maxsock, and rlim_ofile_cur.
Referenced by inetd_main().
remove_fd_from_set()
static void remove_fd_from_set (int fd) static
Definition at line 554 of file inetd.c.
 {
     if (fd >= 0) {
         FD_CLR(fd, &allsock);
         dbg("stopped listening on fd:%d\n", fd);
         maxsock = -1;
         dbg("maxsock:%d\n", maxsock);
     }
 }
References allsock, dbg, fd, FD_CLR, and maxsock.
Referenced by inetd_main(), and reread_config_file().
reopen_config_file()
static int reopen_config_file (void) static
Definition at line 660 of file inetd.c.
 {
     free(default_local_hostname);
     default_local_hostname = xstrdup("*");
     if (parser != NULL)
         config_close(parser);
     parser = config_open(config_filename);
     return (parser != NULL);
 }
References config_close(), config_filename, config_open(), default_local_hostname, free, NULL, parser, and xstrdup().
Referenced by reread_config_file().
reread_config_file()
static void reread_config_file (int sig UNUSED_PARAM) static
Definition at line 967 of file inetd.c.
 {
     servtab_t *sep, *cp, **sepp;
     len_and_sockaddr *lsa;
     sigset_t omask;
     unsigned n;
     uint16_t port;
     int save_errno = errno;
     if (!reopen_config_file())
         goto ret;
     for (sep = serv_list; sep; sep = sep->se_next)
         sep->se_checked = 0;
     goto first_line;
     while (1) {
         if (cp == NULL) {
  first_line:
             cp = parse_one_line();
             if (cp == NULL)
                 break;
         }
         for (sep = serv_list; sep; sep = sep->se_next)
             if (same_serv_addr_proto(sep, cp))
                 goto equal_servtab;
         /* not an "equal" servtab */
         sep = insert_in_servlist(cp);
         goto after_check;
  equal_servtab:
         {
             int i;
             block_CHLD_HUP_ALRM(&omask);
 #if ENABLE_FEATURE_INETD_RPC
             if (is_rpc_service(sep))
                 unregister_rpc(sep);
             sep->se_rpcver_lo = cp->se_rpcver_lo;
             sep->se_rpcver_hi = cp->se_rpcver_hi;
 #endif
             if (cp->se_wait == 0) {
                 /* New config says "nowait". If old one
                  * was "wait", we currently may be waiting
                  * for a child (and not accepting connects).
                  * Stop waiting, start listening again.
                  * (if it's not true, this op is harmless) */
                 add_fd_to_set(sep->se_fd);
             }
             sep->se_wait = cp->se_wait;
             sep->se_max = cp->se_max;
             /* string fields need more love - we don't want to leak them */
 #define SWAP(type, a, b) do { type c = (type)a; a = (type)b; b = (type)c; } while (0)
             SWAP(char*, sep->se_user, cp->se_user);
             SWAP(char*, sep->se_group, cp->se_group);
             SWAP(char*, sep->se_program, cp->se_program);
             for (i = 0; i < MAXARGV; i++)
                 SWAP(char*, sep->se_argv[i], cp->se_argv[i]);
 #undef SWAP
             restore_sigmask(&omask);
             free_servtab_strings(cp);
         }
  after_check:
         /* cp->string_fields are consumed by insert_in_servlist()
          * or freed at this point, cp itself is not yet freed. */
         sep->se_checked = 1;
         /* create new len_and_sockaddr */
         switch (sep->se_family) {
             struct sockaddr_un *sun;
         case AF_UNIX:
             lsa = xzalloc_lsa(AF_UNIX);
             sun = (struct sockaddr_un*)&lsa->u.sa;
             safe_strncpy(sun->sun_path, sep->se_service, sizeof(sun->sun_path));
             break;
         default: /* case AF_INET, case AF_INET6 */
             n = bb_strtou(sep->se_service, NULL, 10);
 #if ENABLE_FEATURE_INETD_RPC
             if (is_rpc_service(sep)) {
                 sep->se_rpcprog = n;
                 if (errno) { /* se_service is not numeric */
                     struct rpcent *rp = getrpcbyname(sep->se_service);
                     if (rp == NULL) {
                         bb_error_msg("%s: unknown rpc service", sep->se_service);
                         goto next_cp;
                     }
                     sep->se_rpcprog = rp->r_number;
                 }
                 if (sep->se_fd == -1)
                     prepare_socket_fd(sep);
                 if (sep->se_fd != -1)
                     register_rpc(sep);
                 goto next_cp;
             }
 #endif
             /* what port to listen on? */
             port = htons(n);
             if (errno || n > 0xffff) { /* se_service is not numeric */
                 char protoname[4];
                 struct servent *sp;
                 /* can result only in "tcp" or "udp": */
                 safe_strncpy(protoname, sep->se_proto, 4);
                 sp = getservbyname(sep->se_service, protoname);
                 if (sp == NULL) {
                     bb_error_msg("%s/%s: unknown service",
                             sep->se_service, sep->se_proto);
                     goto next_cp;
                 }
                 port = sp->s_port;
             }
             if (LONE_CHAR(sep->se_local_hostname, '*')) {
                 lsa = xzalloc_lsa(sep->se_family);
                 set_nport(&lsa->u.sa, port);
             } else {
                 lsa = host_and_af2sockaddr(sep->se_local_hostname,
                         ntohs(port), sep->se_family);
                 if (!lsa) {
                     bb_error_msg("%s/%s: unknown host '%s'",
                         sep->se_service, sep->se_proto,
                         sep->se_local_hostname);
                     goto next_cp;
                 }
             }
             break;
         } /* end of "switch (sep->se_family)" */
         /* did lsa change? Then close/open */
         if (sep->se_lsa == NULL
          || lsa->len != sep->se_lsa->len
          || memcmp(&lsa->u.sa, &sep->se_lsa->u.sa, lsa->len) != 0
         ) {
             remove_fd_from_set(sep->se_fd);
             maybe_close(sep->se_fd);
             free(sep->se_lsa);
             sep->se_lsa = lsa;
             sep->se_fd = -1;
         } else {
             free(lsa);
         }
         if (sep->se_fd == -1)
             prepare_socket_fd(sep);
  next_cp:
         sep = cp->se_next;
         free(cp);
         cp = sep;
     } /* end of "while (1) parse lines" */
     close_config_file();
     /* Purge anything not looked at above - these are stale entries,
      * new config file doesnt have them. */
     block_CHLD_HUP_ALRM(&omask);
     sepp = &serv_list;
     while ((sep = *sepp) != NULL) {
         if (sep->se_checked) {
             sepp = &sep->se_next;
             continue;
         }
         *sepp = sep->se_next;
         remove_fd_from_set(sep->se_fd);
         maybe_close(sep->se_fd);
 #if ENABLE_FEATURE_INETD_RPC
         if (is_rpc_service(sep))
             unregister_rpc(sep);
 #endif
         if (sep->se_family == AF_UNIX)
             unlink(sep->se_service);
         free_servtab_strings(sep);
         free(sep);
     }
     restore_sigmask(&omask);
  ret:
     errno = save_errno;
 }
References add_fd_to_set(), AF_UNIX, bb_error_msg(), bb_strtou(), block_CHLD_HUP_ALRM(), close_config_file(), errno, free, free_servtab_strings(), getservbyname(), host_and_af2sockaddr, htons(), i, insert_in_servlist(), is_rpc_service, len_and_sockaddr::len, LONE_CHAR, lsa, MAXARGV, maybe_close(), memcmp(), n, ntohs(), NULL, parse_one_line(), port, prepare_socket_fd(), remove_fd_from_set(), reopen_config_file(), restore_sigmask(), safe_strncpy(), same_serv_addr_proto(), servtab_t::se_argv, servtab_t::se_checked, servtab_t::se_family, servtab_t::se_fd, servtab_t::se_group, servtab_t::se_local_hostname, servtab_t::se_lsa, servtab_t::se_max, servtab_t::se_next, servtab_t::se_program, servtab_t::se_proto, servtab_t::se_service, servtab_t::se_user, servtab_t::se_wait, serv_list, set_nport(), sp, sockaddr_un::sun_path, SWAP, len_and_sockaddr::u, unlink(), while(), and xzalloc_lsa().
Referenced by inetd_main().
restore_sigmask()
static void restore_sigmask (sigset_t * m) static
Definition at line 494 of file inetd.c.
 {
     sigprocmask(SIG_SETMASK, m, NULL);
 }
References NULL, SIG_SETMASK, and sigprocmask().
Referenced by inetd_main(), insert_in_servlist(), and reread_config_file().
retry_network_setup()
static void retry_network_setup (int sig UNUSED_PARAM) static
Definition at line 1169 of file inetd.c.
 {
     int save_errno = errno;
     servtab_t *sep;
     alarm_armed = 0;
     for (sep = serv_list; sep; sep = sep->se_next) {
         if (sep->se_fd == -1) {
             prepare_socket_fd(sep);
 #if ENABLE_FEATURE_INETD_RPC
             if (sep->se_fd != -1 && is_rpc_service(sep))
                 register_rpc(sep);
 #endif
         }
     }
     errno = save_errno;
 }
References alarm_armed, errno, is_rpc_service, prepare_socket_fd(), servtab_t::se_fd, servtab_t::se_next, and serv_list.
Referenced by inetd_main().
same_serv_addr_proto()
static int same_serv_addr_proto (servtab_t * old, servtab_t * new) static
Definition at line 956 of file inetd.c.
 {
     if (strcmp(old->se_local_hostname, new->se_local_hostname) != 0)
         return 0;
     if (strcmp(old->se_service, new->se_service) != 0)
         return 0;
     if (strcmp(old->se_proto, new->se_proto) != 0)
         return 0;
     return 1;
 }
References old, and strcmp.
Referenced by reread_config_file().
xzalloc_lsa()
static len_and_sockaddr* xzalloc_lsa (int family) static
Definition at line 459 of file inetd.c.
 {
     len_and_sockaddr *lsa;
     int sz;
     sz = sizeof(struct sockaddr_in);
     if (family == AF_UNIX)
         sz = sizeof(struct sockaddr_un);
 #if ENABLE_FEATURE_IPV6
     if (family == AF_INET6)
         sz = sizeof(struct sockaddr_in6);
 #endif
     lsa = xzalloc(LSA_LEN_SIZE + sz);
     lsa->len = sz;
     lsa->u.sa.sa_family = family;
     return lsa;
 }
References AF_INET6, AF_UNIX, lsa, LSA_LEN_SIZE, and xzalloc().
Referenced by inetd_main(), and reread_config_file().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING