Fennix: Userspace/apps/base/bash/lib/readline/shell.c File Reference
shell.c File Reference
#include <sys/types.h>
#include "ansi_stdlib.h"
#include <strings.h>
#include <stdio.h>
#include "rlstdc.h"
#include "rlshell.h"
#include "rldefs.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define NULL 0
#define CHAR_BIT 8
#define TYPE_SIGNED(t) (! ((t) 0 < (t) -1))
#define INT_STRLEN_BOUND(t)
Functions
char * sh_single_quote (char *string)
void sh_set_lines_and_columns (int lines, int cols)
char * sh_get_env_value (const char *varname)
char * sh_get_home_dir (void)
int sh_unset_nodelay_mode (int fd)
Variables
static char setenv_buf [INT_STRLEN_BOUND(int)+1]
static char putenv_buf1 [INT_STRLEN_BOUND(int)+6+1]
static char putenv_buf2 [INT_STRLEN_BOUND(int)+8+1]
Macro Definition Documentation
CHAR_BIT
#define CHAR_BIT 8
Definition at line 75 of file shell.c.
INT_STRLEN_BOUND
#define INT_STRLEN_BOUND (t)
Value:
  ((sizeof (t) * CHAR_BIT - TYPE_SIGNED (t)) * 302 / 1000 \
   + 1 + TYPE_SIGNED (t))
Definition at line 86 of file shell.c.
NULL
#define NULL 0
Definition at line 71 of file shell.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 23 of file shell.c.
TYPE_SIGNED
#define TYPE_SIGNED (t) (! ((t) 0 < (t) -1))
Definition at line 79 of file shell.c.
Function Documentation
sh_get_env_value()
char* sh_get_env_value (const char * varname)
Definition at line 149 of file shell.c.
 {
   return ((char *)getenv (varname));
 }
References getenv.
Referenced by _rl_get_locale_var(), _rl_get_screen_size(), _rl_init_terminal_io(), _rl_parse_colors(), history_filename(), readline_initialize_everything(), rl_read_init_file(), and tilde_expand_word().
sh_get_home_dir()
char* sh_get_home_dir (void)
Definition at line 155 of file shell.c.
 {
   static char *home_dir = (char *)NULL;
   struct passwd *entry;
   if (home_dir)
     return (home_dir);
   home_dir = (char *)NULL;
 #if defined (HAVE_GETPWUID)
 #  if defined (__TANDEM)
   entry = getpwnam (getlogin ());
 #  else
   entry = getpwuid (getuid ());
 #  endif
   if (entry)
     home_dir = savestring (entry->pw_dir);
 #endif
 #if defined (HAVE_GETPWENT)
   endpwent ();      /* some systems need this */
 #endif
   return (home_dir);
 }
sh_set_lines_and_columns()
void sh_set_lines_and_columns (int lines, int cols)
Definition at line 129 of file shell.c.
 {
 #if defined (HAVE_SETENV)
   sprintf (setenv_buf, "%d", lines);
   setenv ("LINES", setenv_buf, 1);
   sprintf (setenv_buf, "%d", cols);
   setenv ("COLUMNS", setenv_buf, 1);
 #else /* !HAVE_SETENV */
 #  if defined (HAVE_PUTENV)
   sprintf (putenv_buf1, "LINES=%d", lines);
   putenv (putenv_buf1);
   sprintf (putenv_buf2, "COLUMNS=%d", cols);
   putenv (putenv_buf2);
 #  endif /* HAVE_PUTENV */
 #endif /* !HAVE_SETENV */
 }
sh_single_quote()
char* sh_single_quote (char * string)
Definition at line 95 of file shell.c.
 {
   register int c;
   char *result, *r, *s;
   result = (char *)xmalloc (3 + (4 * strlen (string)));
   r = result;
   *r++ = '\'';
   for (s = string; s && (c = *s); s++)
     {
       *r++ = c;
       if (c == '\'')
     {
       *r++ = '\\';  /* insert escaped single quote */
       *r++ = '\'';
       *r++ = '\'';  /* start new quoted string */
     }
     }
   *r++ = '\'';
   *r = '\0';
   return (result);
 }
References c, s, strlen, and xmalloc.
Referenced by expand_string_dollar_quote(), extract_heredoc_dolbrace_string(), history_expand_internal(), parse_matched_pair(), print_heredoc_header(), print_var_value(), printable_filename(), read_token_word(), xtrace_print_assignment(), and xtrace_print_word_list().
sh_unset_nodelay_mode()
int sh_unset_nodelay_mode (int fd)
Definition at line 188 of file shell.c.
 {
 #if defined (HAVE_FCNTL)
   int flags, bflags;
   if ((flags = fcntl (fd, F_GETFL, 0)) < 0)
     return -1;
   bflags = 0;
 #ifdef O_NONBLOCK
   bflags |= O_NONBLOCK;
 #endif
 #ifdef O_NDELAY
   bflags |= O_NDELAY;
 #endif
   if (flags & bflags)
     {
       flags &= ~bflags;
       return (fcntl (fd, F_SETFL, flags));
     }
 #endif
   return 0;
 }
References F_GETFL, F_SETFL, fcntl(), fd, flags, O_NDELAY, and O_NONBLOCK.
Referenced by set_bash_input().
Variable Documentation
putenv_buf1
char putenv_buf1[INT_STRLEN_BOUND(int)+6+1] static
Definition at line 125 of file shell.c.
Referenced by sh_set_lines_and_columns().
putenv_buf2
char putenv_buf2[INT_STRLEN_BOUND(int)+8+1] static
Definition at line 126 of file shell.c.
Referenced by sh_set_lines_and_columns().
setenv_buf
char setenv_buf[INT_STRLEN_BOUND(int)+1] static
Definition at line 124 of file shell.c.
Referenced by sh_set_lines_and_columns().