Fennix: Userspace/apps/base/busybox/procps/nmeter.c File Reference
nmeter.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct proc_file
struct globals
Macros
#define first_proc_file proc_stat
#define G (*ptr_to_globals)
#define gen (G.gen)
#define is26 (G.is26)
#define need_seconds (G.need_seconds)
#define cur_outbuf (G.cur_outbuf)
#define proc_stat (G.proc_stat)
#define proc_loadavg (G.proc_loadavg)
#define proc_net_dev (G.proc_net_dev)
#define proc_meminfo (G.proc_meminfo)
#define proc_diskstats (G.proc_diskstats)
#define proc_sys_fs_filenr (G.proc_sys_fs_filenr)
#define outbuf bb_common_bufsiz1
#define INIT_G()
#define S_STAT(a)
#define S_STAT_END(a) } a;
Typedefs
typedef unsigned long long ullong
typedef struct proc_file proc_file
typedef s_stat * init_func(const char *param)
Enumerations
enum { PROC_MIN_FILE_SIZE = 256 , PROC_MAX_FILE_SIZE = 16 * 1024 }
enum conv_type { conv_decimal = 0 , conv_slash = 1 }
enum { CPU_FIELDCNT = 7 }
Functions
static void reset_outbuf (void)
static void print_outbuf (void)
static void put (const char *s)
static void put_c (char c)
static void put_question_marks (int count)
static void readfile_z (proc_file *pf, const char *fname)
static const char * get_file (proc_file *pf)
static ullong read_after_slash (const char *p)
static int rdval (const char *p, const char *key, ullong *vec, long posbits)
static int rdval_loadavg (const char *p, ullong *vec, long posbits)
static int rdval_diskstats (const char *p, ullong *vec)
static void scale (ullong ul)
static void FAST_FUNC collect_literal (s_stat *s UNUSED_PARAM)
static s_stat * init_literal (void)
static s_stat * init_cr (const char *param UNUSED_PARAM)
static void FAST_FUNC collect_cpu (cpu_stat *s)
static s_stat * init_cpu (const char *param)
static void FAST_FUNC collect_int (int_stat *s)
static s_stat * init_int (const char *param)
static void FAST_FUNC collect_ctx (ctx_stat *s)
static s_stat * init_ctx (const char *param UNUSED_PARAM)
static void FAST_FUNC collect_blk (blk_stat *s)
static s_stat * init_blk (const char *param UNUSED_PARAM)
static void FAST_FUNC collect_thread_nr (fork_stat *s UNUSED_PARAM)
static void FAST_FUNC collect_fork (fork_stat *s)
static s_stat * init_fork (const char *param)
static void FAST_FUNC collect_if (if_stat *s)
static s_stat * init_if (const char *device)
static void FAST_FUNC collect_mem (mem_stat *s)
static s_stat * init_mem (const char *param)
static void FAST_FUNC collect_swp (swp_stat *s UNUSED_PARAM)
static s_stat * init_swp (const char *param UNUSED_PARAM)
static void FAST_FUNC collect_fd (fd_stat *s UNUSED_PARAM)
static s_stat * init_fd (const char *param UNUSED_PARAM)
static void FAST_FUNC collect_tv (time_stat *s, struct timeval *tv, int local)
static void FAST_FUNC collect_time (time_stat *s)
static void FAST_FUNC collect_monotonic (time_stat *s)
static s_stat * init_time (const char *param)
static s_stat * init_monotonic (const char *param)
static void FAST_FUNC collect_info (s_stat *s)
int nmeter_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char *const proc_name[] ALIGN_PTR
ullong old [CPU_FIELDCNT]
unsigned bar_sz
char bar [1]
int no
const char * lookfor
const char * device
char * device_colon
char opt
unsigned prec
unsigned scale
static const char options[] ALIGN1 = "ncmsfixptTbr"
Data Structure Documentation
proc_file
struct proc_file
Definition at line 67 of file nmeter.c.
Data Fields
char * file
int file_sz
smallint last_gen
Macro Definition Documentation
cur_outbuf
#define cur_outbuf (G.cur_outbuf)
Definition at line 107 of file nmeter.c.
first_proc_file
#define first_proc_file proc_stat
Definition at line 95 of file nmeter.c.
G
#define G (*ptr_to_globals)
Definition at line 103 of file nmeter.c.
gen
#define gen (G.gen)
Definition at line 104 of file nmeter.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    cur_outbuf = outbuf; \
    G.final_char = '\n'; \
    G.deltanz = G.delta = 1000000; \
} while (0)
Definition at line 115 of file nmeter.c.
is26
#define is26 (G.is26)
Definition at line 105 of file nmeter.c.
need_seconds
#define need_seconds (G.need_seconds)
Definition at line 106 of file nmeter.c.
outbuf
#define outbuf bb_common_bufsiz1
Definition at line 114 of file nmeter.c.
proc_diskstats
#define proc_diskstats (G.proc_diskstats)
Definition at line 112 of file nmeter.c.
proc_loadavg
#define proc_loadavg (G.proc_loadavg)
Definition at line 109 of file nmeter.c.
proc_meminfo
#define proc_meminfo (G.proc_meminfo)
Definition at line 111 of file nmeter.c.
proc_net_dev
#define proc_net_dev (G.proc_net_dev)
Definition at line 110 of file nmeter.c.
proc_stat
#define proc_stat (G.proc_stat)
Definition at line 108 of file nmeter.c.
proc_sys_fs_filenr
#define proc_sys_fs_filenr (G.proc_sys_fs_filenr)
Definition at line 113 of file nmeter.c.
S_STAT
#define S_STAT (a)
Value:
typedef struct a { \
    struct s_stat *next; \
    void (*collect)(struct a *s) FAST_FUNC; \
    const char *label;
Definition at line 319 of file nmeter.c.
S_STAT_END
#define S_STAT_END (a) } a;
Definition at line 324 of file nmeter.c.
Typedef Documentation
init_func
typedef s_stat* init_func(const char *param)
Definition at line 862 of file nmeter.c.
proc_file
typedef struct proc_file proc_file
ullong
typedef unsigned long long ullong
Definition at line 60 of file nmeter.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROC_MIN_FILE_SIZE
PROC_MAX_FILE_SIZE
Definition at line 62 of file nmeter.c.
      {  /* Preferably use powers of 2 */
     PROC_MIN_FILE_SIZE = 256,
     PROC_MAX_FILE_SIZE = 16 * 1024,
 };
anonymous enum
anonymous enum
Enumerator
CPU_FIELDCNT
Definition at line 349 of file nmeter.c.
 { CPU_FIELDCNT = 7 };
conv_type
enum conv_type
Enumerator
conv_decimal
conv_slash
Definition at line 205 of file nmeter.c.
                {
     conv_decimal = 0,
     conv_slash = 1
 };
Function Documentation
collect_blk()
static void FAST_FUNC collect_blk (blk_stat * s) static
Definition at line 497 of file nmeter.c.
 {
     ullong data[2];
     int i;
     if (is26) {
         i = rdval_diskstats(get_file(&proc_diskstats), data);
     } else {
         i = rdval(get_file(&proc_stat), s->lookfor, data, 0
                 | (1 << 1)
                 | (1 << 2)
         );
         // Linux 2.4 reports bio in Kbytes, convert to sectors:
         data[0] *= 2;
         data[1] *= 2;
     }
     if (i) {
         put_question_marks(9);
         return;
     }
     for (i = 0; i < 2; i++) {
         ullong old = s->old[i];
         if (data[i] < old) old = data[i];       //sanitize
         s->old[i] = data[i];
         data[i] -= old;
     }
     scale(data[0]*512); // TODO: *sectorsize
     put_c(' ');
     scale(data[1]*512);
 }
References get_file(), i, is26, old, proc_diskstats, proc_stat, put_c(), put_question_marks(), rdval(), rdval_diskstats(), s, and scale.
Referenced by init_blk().
collect_cpu()
static void FAST_FUNC collect_cpu (cpu_stat * s) static
Definition at line 356 of file nmeter.c.
 {
     ullong data[CPU_FIELDCNT] = { 0, 0, 0, 0, 0, 0, 0 };
     unsigned frac[CPU_FIELDCNT] = { 0, 0, 0, 0, 0, 0, 0 };
     ullong all = 0;
     unsigned norm_all = 0;
     unsigned bar_sz = s->bar_sz;
     char *bar = s->bar;
     int i;
     if (rdval(get_file(&proc_stat), "cpu ", data, 0
         | (1 << 1)
         | (1 << 2)
         | (1 << 3)
         | (1 << 4)
         | (1 << 5)
         | (1 << 6)
         | (1 << 7))
     ) {
         put_question_marks(bar_sz);
         return;
     }
     for (i = 0; i < CPU_FIELDCNT; i++) {
         ullong old = s->old[i];
         if (data[i] < old) old = data[i];       //sanitize
         s->old[i] = data[i];
         all += (data[i] -= old);
     }
     if (all) {
         for (i = 0; i < CPU_FIELDCNT; i++) {
             ullong t = bar_sz * data[i];
             norm_all += data[i] = t / all;
             frac[i] = t % all;
         }
         while (norm_all < bar_sz) {
             unsigned max = frac[0];
             int pos = 0;
             for (i = 1; i < CPU_FIELDCNT; i++) {
                 if (frac[i] > max) max = frac[i], pos = i;
             }
             frac[pos] = 0;  //avoid bumping up same value twice
             data[pos]++;
             norm_all++;
         }
         memset(bar, '.', bar_sz);
         memset(bar, 'S', data[2]); bar += data[2]; //sys
         memset(bar, 'U', data[0]); bar += data[0]; //usr
         memset(bar, 'N', data[1]); bar += data[1]; //nice
         memset(bar, 'D', data[4]); bar += data[4]; //iowait
         memset(bar, 'I', data[5]); bar += data[5]; //irq
         memset(bar, 'i', data[6]); bar += data[6]; //softirq
     } else {
         memset(bar, '?', bar_sz);
     }
     put(s->bar);
 }
References bar, bar_sz, CPU_FIELDCNT, get_file(), i, max, memset, old, pos, proc_stat, put(), put_question_marks(), rdval(), s, and t.
Referenced by init_cpu().
collect_ctx()
static void FAST_FUNC collect_ctx (ctx_stat * s) static
Definition at line 469 of file nmeter.c.
 {
     ullong data[1];
     ullong old;
     if (rdval(get_file(&proc_stat), "ctxt", data, 1 << 1)) {
         put_question_marks(4);
         return;
     }
     old = s->old;
     if (data[0] < old) old = data[0];       //sanitize
     s->old = data[0];
     scale(data[0] - old);
 }
References get_file(), old, proc_stat, put_question_marks(), rdval(), s, and scale.
Referenced by init_ctx().
collect_fd()
static void FAST_FUNC collect_fd (fd_stat *s UNUSED_PARAM) static
Definition at line 755 of file nmeter.c.
 {
     ullong data[2];
     if (rdval(get_file(&proc_sys_fs_filenr), "", data, 0
         | (1 << 1)
         | (1 << 2))
     ) {
         put_question_marks(4);
         return;
     }
     scale(data[0] - data[1]);
 }
References get_file(), proc_sys_fs_filenr, put_question_marks(), rdval(), and scale.
Referenced by init_fd().
collect_fork()
static void FAST_FUNC collect_fork (fork_stat * s) static
Definition at line 552 of file nmeter.c.
 {
     ullong data[1];
     ullong old;
     if (rdval(get_file(&proc_stat), "processes", data, 1 << 1)) {
         put_question_marks(4);
         return;
     }
     old = s->old;
     if (data[0] < old) old = data[0];   //sanitize
     s->old = data[0];
     scale(data[0] - old);
 }
References get_file(), old, proc_stat, put_question_marks(), rdval(), s, and scale.
Referenced by init_fork().
collect_if()
static void FAST_FUNC collect_if (if_stat * s) static
Definition at line 585 of file nmeter.c.
 {
     ullong data[4];
     int i;
     if (rdval(get_file(&proc_net_dev), s->device_colon, data, 0
         | (1 << 1)
         | (1 << 3)
         | (1 << 9)
         | (1 << 11))
     ) {
         put_question_marks(10);
         return;
     }
     for (i = 0; i < 4; i++) {
         ullong old = s->old[i];
         if (data[i] < old) old = data[i];       //sanitize
         s->old[i] = data[i];
         data[i] -= old;
     }
     put_c(data[1] ? '*' : ' ');
     scale(data[0]);
     put_c(data[3] ? '*' : ' ');
     scale(data[2]);
 }
References get_file(), i, old, proc_net_dev, put_c(), put_question_marks(), rdval(), s, and scale.
Referenced by init_if().
collect_info()
static void FAST_FUNC collect_info (s_stat * s) static
Definition at line 852 of file nmeter.c.
 {
     gen ^= 1;
     while (s) {
         put(s->label);
         s->collect(s);
         s = s->next;
     }
 }
References gen, put(), and s.
Referenced by nmeter_main().
collect_int()
static void FAST_FUNC collect_int (int_stat * s) static
Definition at line 436 of file nmeter.c.
 {
     ullong data[1];
     ullong old;
     if (rdval(get_file(&proc_stat), "intr", data, 1 << s->no)) {
         put_question_marks(4);
         return;
     }
     old = s->old;
     if (data[0] < old) old = data[0];       //sanitize
     s->old = data[0];
     scale(data[0] - old);
 }
References get_file(), old, proc_stat, put_question_marks(), rdval(), s, and scale.
Referenced by init_int().
collect_literal()
static void FAST_FUNC collect_literal (s_stat *s UNUSED_PARAM) static
Definition at line 329 of file nmeter.c.
 {
 }
Referenced by init_literal().
collect_mem()
static void FAST_FUNC collect_mem (mem_stat * s) static
Definition at line 664 of file nmeter.c.
 {
     ullong m_total;
     ullong m_free;
     ullong m_bufs;
     ullong m_cached;
     ullong m_slab;
     const char *meminfo = get_file(&proc_meminfo);
     if (s->opt == 'd' /* dirty page cache */
      || s->opt == 'w' /* under writeback */
     ) {
         m_total = 0; /* temporary reuse m_total */
         if (rdval(meminfo,
                 (s->opt == 'd' ? "Dirty:" : "Writeback:"),
                 &m_total, 1 << 1)
         ) {
             put_question_marks(4);
             return;
         }
         scale(m_total << 10);
         return;
     }
     m_total = 0;
     if (rdval(meminfo, "MemTotal:", &m_total, 1 << 1)) {
         put_question_marks(4);
         return;
     }
     if (s->opt == 't') {
         scale(m_total << 10);
         return;
     }
     m_free = 0;
     m_bufs = 0;
     m_cached = 0;
     m_slab = 0;
     if (rdval(meminfo, "MemFree:", &m_free  , 1 << 1)
      || rdval(meminfo, "Buffers:", &m_bufs  , 1 << 1)
      || rdval(meminfo, "Cached:",  &m_cached, 1 << 1)
      || rdval(meminfo, "Slab:",    &m_slab  , 1 << 1)
     ) {
         put_question_marks(4);
         return;
     }
     m_free += m_bufs + m_cached + m_slab;
     switch (s->opt) {
     case 'f':
         scale(m_free << 10); break;
     default:
         scale((m_total - m_free) << 10); break;
     }
 }
References get_file(), proc_meminfo, put_question_marks(), rdval(), s, and scale.
Referenced by init_mem().
collect_monotonic()
static void FAST_FUNC collect_monotonic (time_stat * s) static
Definition at line 809 of file nmeter.c.
 {
     struct timeval tv_mono;
     tv_mono.tv_sec = G.tv.tv_sec - G.start.tv_sec;
 #if 0 /* Do we want this? */
     if (tv_mono.tv_sec < 0) {
         /* Time went backwards, reset start time to "now" */
         tv_mono.tv_sec = 0;
         G.start = G.tv;
     }
 #endif
     tv_mono.tv_usec = G.tv.tv_usec - G.start.tv_usec;
     if ((int32_t)tv_mono.tv_usec < 0) {
         tv_mono.tv_usec += 1000000;
         tv_mono.tv_sec--;
     }
     collect_tv(s, &tv_mono, /*local:*/ 0);
 }
References collect_tv(), G, s, timeval::tv_sec, and timeval::tv_usec.
Referenced by init_monotonic().
collect_swp()
static void FAST_FUNC collect_swp (swp_stat *s UNUSED_PARAM) static
Definition at line 732 of file nmeter.c.
 {
     ullong s_total[1];
     ullong s_free[1];
     if (rdval(get_file(&proc_meminfo), "SwapTotal:", s_total, 1 << 1)
      || rdval(proc_meminfo.file,       "SwapFree:" , s_free,  1 << 1)
     ) {
         put_question_marks(4);
         return;
     }
     scale((s_total[0]-s_free[0]) << 10);
 }
References get_file(), proc_meminfo, put_question_marks(), rdval(), and scale.
Referenced by init_swp().
collect_thread_nr()
static void FAST_FUNC collect_thread_nr (fork_stat *s UNUSED_PARAM) static
Definition at line 541 of file nmeter.c.
 {
     ullong data[1];
     if (rdval_loadavg(get_file(&proc_loadavg), data, 1 << 4)) {
         put_question_marks(4);
         return;
     }
     scale(data[0]);
 }
References get_file(), proc_loadavg, put_question_marks(), rdval_loadavg(), and scale.
Referenced by init_fork().
collect_time()
static void FAST_FUNC collect_time (time_stat * s) static
Definition at line 804 of file nmeter.c.
 {
     collect_tv(s, &G.tv, /*local:*/ 1);
 }
References collect_tv(), G, and s.
Referenced by init_time().
collect_tv()
static void FAST_FUNC collect_tv (time_stat * s, struct timeval * tv, int local) static
Definition at line 782 of file nmeter.c.
 {
     char buf[sizeof("12:34:56.123456")];
     struct tm* tm;
     unsigned us = tv->tv_usec + s->scale/2;
     time_t t = tv->tv_sec;
     if (us >= 1000000) {
         t++;
         us -= 1000000;
     }
     if (local)
         tm = localtime(&t);
     else
         tm = gmtime(&t);
     sprintf(buf, "%02u:%02u:%02u", tm->tm_hour, tm->tm_min, tm->tm_sec);
     if (s->prec)
         sprintf(buf+8, ".%0*u", s->prec, us / s->scale);
     put(buf);
 }
References buf, gmtime(), local, localtime(), put(), s, sprintf(), t, tm::tm_hour, tm::tm_min, and tm::tm_sec.
Referenced by collect_monotonic(), and collect_time().
get_file()
static const char* get_file (proc_file * pf) static
Definition at line 189 of file nmeter.c.
 {
     if (pf->last_gen != gen) {
         pf->last_gen = gen;
         readfile_z(pf, proc_name[pf - &first_proc_file]);
     }
     return pf->file;
 }
References proc_file::file, first_proc_file, gen, proc_file::last_gen, and readfile_z().
Referenced by collect_blk(), collect_cpu(), collect_ctx(), collect_fd(), collect_fork(), collect_if(), collect_int(), collect_mem(), collect_swp(), and collect_thread_nr().
init_blk()
static s_stat* init_blk (const char *param UNUSED_PARAM) static
Definition at line 529 of file nmeter.c.
 {
     blk_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_blk;
     s->lookfor = "page";
     return (s_stat*)s;
 }
References collect_blk(), s, and xzalloc().
init_cpu()
static s_stat* init_cpu (const char * param) static
Definition at line 417 of file nmeter.c.
 {
     int sz;
     cpu_stat *s;
     sz = param[0] ? strtoul(param, NULL, 0) : 10;
     if (sz <= 0) sz = 1;
     if (sz > 1000) sz = 1000;
     s = xzalloc(sizeof(*s) + sz);
     /*s->bar[sz] = '\0'; - xzalloc did it */
     s->bar_sz = sz;
     s->collect = collect_cpu;
     return (s_stat*)s;
 }
References collect_cpu(), NULL, param, s, strtoul(), and xzalloc().
init_cr()
static s_stat* init_cr (const char *param UNUSED_PARAM) static
Definition at line 340 of file nmeter.c.
 {
     G.final_char = '\r';
     return NULL;
 }
References G, and NULL.
init_ctx()
static s_stat* init_ctx (const char *param UNUSED_PARAM) static
Definition at line 485 of file nmeter.c.
 {
     ctx_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_ctx;
     return (s_stat*)s;
 }
References collect_ctx(), s, and xzalloc().
init_fd()
static s_stat* init_fd (const char *param UNUSED_PARAM) static
Definition at line 770 of file nmeter.c.
 {
     fd_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_fd;
     return (s_stat*)s;
 }
References collect_fd(), s, and xzalloc().
init_fork()
static s_stat* init_fork (const char * param) static
Definition at line 568 of file nmeter.c.
 {
     fork_stat *s = xzalloc(sizeof(*s));
     if (*param == 'n') {
         s->collect = collect_thread_nr;
     } else {
         s->collect = collect_fork;
     }
     return (s_stat*)s;
 }
References collect_fork(), collect_thread_nr(), param, s, and xzalloc().
init_if()
static s_stat* init_if (const char * device) static
Definition at line 612 of file nmeter.c.
 {
     if_stat *s = xzalloc(sizeof(*s));
     if (!device || !device[0])
         bb_show_usage();
     s->collect = collect_if;
     s->device = device;
     s->device_colon = xasprintf("%s:", device);
     return (s_stat*)s;
 }
References bb_show_usage(), collect_if(), device, s, xasprintf(), and xzalloc().
init_int()
static s_stat* init_int (const char * param) static
Definition at line 452 of file nmeter.c.
 {
     int_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_int;
     if (param[0] == '\0') {
         s->no = 1;
     } else {
         int n = xatoi_positive(param);
         s->no = n + 2;
     }
     return (s_stat*)s;
 }
References collect_int(), n, param, s, xatoi_positive(), and xzalloc().
init_literal()
static s_stat* init_literal (void) static
Definition at line 333 of file nmeter.c.
 {
     s_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_literal;
     return (s_stat*)s;
 }
References collect_literal(), s, and xzalloc().
Referenced by nmeter_main().
init_mem()
static s_stat* init_mem (const char * param) static
Definition at line 721 of file nmeter.c.
 {
     mem_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_mem;
     s->opt = param[0];
     return (s_stat*)s;
 }
References collect_mem(), param, s, and xzalloc().
init_monotonic()
static s_stat* init_monotonic (const char * param) static
Definition at line 845 of file nmeter.c.
 {
     time_stat *s = (void*)init_time(param);
     s->collect = collect_monotonic;
     return (s_stat*)s;
 }
References collect_monotonic(), init_time(), param, and s.
init_swp()
static s_stat* init_swp (const char *param UNUSED_PARAM) static
Definition at line 745 of file nmeter.c.
 {
     swp_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_swp;
     return (s_stat*)s;
 }
References collect_swp(), s, and xzalloc().
init_time()
static s_stat* init_time (const char * param) static
Definition at line 829 of file nmeter.c.
 {
     int prec;
     time_stat *s = xzalloc(sizeof(*s));
     s->collect = collect_time;
     prec = param[0] - '0';
     if (prec < 0) prec = 0;
     else if (prec > 6) prec = 6;
     s->prec = prec;
     s->scale = 1;
     while (prec++ < 6)
         s->scale *= 10;
     return (s_stat*)s;
 }
References collect_time(), param, prec, s, and xzalloc().
Referenced by init_monotonic().
nmeter_main()
int nmeter_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 881 of file nmeter.c.
 {
     char buf[32];
     s_stat *first = NULL;
     s_stat *last = NULL;
     s_stat *s;
     char *opt_d;
     char *cur, *prev;
     INIT_G();
     xchdir("/proc");
     if (open_read_close("version", buf, sizeof(buf)-1) > 0) {
         buf[sizeof(buf)-1] = '\0';
         is26 = (strstr(buf, " 2.4.") == NULL);
     }
     if (getopt32(argv, "d:", &opt_d)) {
         G.delta = xatoi(opt_d) * 1000;
         G.deltanz = G.delta > 0 ? G.delta : 1;
         need_seconds = (1000000 % G.deltanz) != 0;
     }
     argv += optind;
     if (!argv[0])
         bb_show_usage();
     // Can use argv[0] directly, but this will mess up
     // parameters as seen by e.g. ps. Making a copy...
     cur = xstrdup(argv[0]);
     while (1) {
         char *param, *p;
         prev = cur;
  again:
         cur = strchr(cur, '%');
         if (!cur)
             break;
         if (cur[1] == '%') {    // %%
             overlapping_strcpy(cur, cur + 1);
             cur++;
             goto again;
         }
         *cur++ = '\0';      // overwrite %
         if (cur[0] == '[') {
             // format: %[foptstring]
             cur++;
             p = strchr(options, cur[0]);
             param = cur+1;
             while (cur[0] != ']') {
                 if (!cur[0])
                     bb_show_usage();
                 cur++;
             }
             *cur++ = '\0';  // overwrite [
         } else {
             // format: %NNNNNNf
             param = cur;
             while (cur[0] >= '0' && cur[0] <= '9')
                 cur++;
             if (!cur[0])
                 bb_show_usage();
             p = strchr(options, cur[0]);
             *cur++ = '\0';  // overwrite format char
         }
         if (!p)
             bb_show_usage();
         s = init_functions[p-options](param);
         if (s) {
             s->label = prev;
             /*s->next = NULL; - all initXXX funcs use xzalloc */
             if (!first)
                 first = s;
             else
                 last->next = s;
             last = s;
         } else {
             // %r option. remove it from string
             overlapping_strcpy(prev + strlen(prev), cur);
             cur = prev;
         }
     }
     if (prev[0]) {
         s = init_literal();
         s->label = prev;
         /*s->next = NULL; - all initXXX funcs use xzalloc */
         if (!first)
             first = s;
         else
             last->next = s;
         last = s;
     }
     // Generate first samples but do not print them, they're bogus
     collect_info(first);
     reset_outbuf();
     if (G.delta >= 0) {
         xgettimeofday(&G.tv);
         usleep(G.delta > 1000000 ? 1000000 : G.delta - G.tv.tv_usec % G.deltanz);
     }
     xgettimeofday(&G.start);
     G.tv = G.start;
     while (1) {
         collect_info(first);
         put_c(G.final_char);
         print_outbuf();
         // Negative delta -> no usleep at all
         // This will hog the CPU but you can have REALLY GOOD
         // time resolution ;)
         // TODO: detect and avoid useless updates
         // (like: nothing happens except time)
         if (G.delta >= 0) {
             int rem;
             // can be commented out, will sacrifice sleep time precision a bit
             xgettimeofday(&G.tv);
             if (need_seconds)
                 rem = G.delta - ((ullong)G.tv.tv_sec*1000000 + G.tv.tv_usec) % G.deltanz;
             else
                 rem = G.delta - (unsigned)G.tv.tv_usec % G.deltanz;
             // Sometimes kernel wakes us up just a tiny bit earlier than asked
             // Do not go to very short sleep in this case
             if (rem < (unsigned)G.delta / 128) {
                 rem += G.delta;
             }
             usleep(rem);
         }
         xgettimeofday(&G.tv);
     }
     /*return 0;*/
 }
References argv, bb_show_usage(), buf, collect_info(), cur, first, G, getopt32(), if(), INIT_G, init_literal(), is26, last, need_seconds, NULL, open_read_close(), optind, options, overlapping_strcpy(), p, param, print_outbuf(), put_c(), reset_outbuf(), s, strchr(), strlen(), strstr(), usleep(), xchdir(), xgettimeofday(), and xstrdup().
print_outbuf()
static void print_outbuf (void) static
Definition at line 128 of file nmeter.c.
 {
     int sz = cur_outbuf - outbuf;
     if (sz > 0) {
         xwrite(STDOUT_FILENO, outbuf, sz);
         cur_outbuf = outbuf;
     }
 }
References cur_outbuf, outbuf, STDOUT_FILENO, and xwrite().
Referenced by nmeter_main().
put()
static void put (const char * s) static
Definition at line 137 of file nmeter.c.
 {
     char *p = cur_outbuf;
     int sz = outbuf + COMMON_BUFSIZE - p;
     while (*s && --sz >= 0)
         *p++ = *s++;
     cur_outbuf = p;
 }
References cur_outbuf, outbuf, p, and s.
Referenced by collect_cpu(), collect_info(), collect_tv(), scale(), and shell_builtin_read().
put_c()
static void put_c (char c) static
Definition at line 146 of file nmeter.c.
 {
     if (cur_outbuf < outbuf + COMMON_BUFSIZE)
         *cur_outbuf++ = c;
 }
References c, cur_outbuf, and outbuf.
Referenced by collect_blk(), collect_if(), nmeter_main(), and put_question_marks().
put_question_marks()
static void put_question_marks (int count) static
Definition at line 152 of file nmeter.c.
 {
     while (count--)
         put_c('?');
 }
References count, and put_c().
Referenced by collect_blk(), collect_cpu(), collect_ctx(), collect_fd(), collect_fork(), collect_if(), collect_int(), collect_mem(), collect_swp(), and collect_thread_nr().
rdval()
static int rdval (const char * p, const char * key, ullong * vec, long posbits) static
Definition at line 216 of file nmeter.c.
 {
     unsigned curpos;
     p = strstr(p, key);
     if (!p) return 1;
     p += strlen(key);
     curpos = 1 << 1;
     while (1) {
         while (*p == ' ' || *p == '\t') p++;
         if (*p == '\n' || *p == '\0') break;
         if (curpos & posbits) { // read this value
             *vec++ = (posbits & 1) == conv_decimal ?
                 strtoull(p, NULL, 10) :
                 read_after_slash(p);
             posbits -= curpos;
             if (posbits <= 1)
                 return 0;
         }
         while (*p > ' ') // skip over the value
             p++;
         curpos <<= 1;
     }
     return 0;
 }
References conv_decimal, curpos, NULL, p, read_after_slash(), strlen(), strstr(), and strtoull().
Referenced by collect_blk(), collect_cpu(), collect_ctx(), collect_fd(), collect_fork(), collect_if(), collect_int(), collect_mem(), collect_swp(), and rdval_loadavg().
rdval_diskstats()
static int rdval_diskstats (const char * p, ullong * vec) static
Definition at line 258 of file nmeter.c.
 {
     char devname[32];
     unsigned devname_len = 0;
     int value_idx = 0;
     vec[0] = 0;
     vec[1] = 0;
     while (1) {
         value_idx++;
         while (*p == ' ' || *p == '\t')
             p++;
         if (*p == '\0')
             break;
         if (*p == '\n') {
             value_idx = 0;
             p++;
             continue;
         }
         if (value_idx == 3) {
             char *end = strchrnul(p, ' ');
             /* If this a hda1-like device (same prefix as last one + digit)? */
             if (devname_len && strncmp(devname, p, devname_len) == 0 && isdigit(p[devname_len])) {
                 p = end;
                 goto skip_line; /* skip entire line */
             }
             /* It is not. Remember the name for future checks */
             devname_len = end - p;
             if (devname_len > sizeof(devname)-1)
                 devname_len = sizeof(devname)-1;
             strncpy(devname, p, devname_len);
             /* devname[devname_len] = '\0'; - not really needed */
             p = end;
         } else
         if (value_idx == 6) {
             // TODO: *sectorsize (don't know how to find out sectorsize)
             vec[0] += strtoull(p, NULL, 10);
         } else
         if (value_idx == 10) {
             // TODO: *sectorsize (don't know how to find out sectorsize)
             vec[1] += strtoull(p, NULL, 10);
  skip_line:
             while (*p != '\n' && *p != '\0')
                 p++;
             continue;
         }
         while ((unsigned char)(*p) > ' ') // skip over value
             p++;
     }
     return 0;
 }
References end, isdigit, NULL, p, strchrnul(), strncmp(), strncpy(), and strtoull().
Referenced by collect_blk().
rdval_loadavg()
static int rdval_loadavg (const char * p, ullong * vec, long posbits) static
Definition at line 245 of file nmeter.c.
 {
     int result;
     result = rdval(p, "", vec, posbits | conv_slash);
     return result;
 }
References conv_slash, p, and rdval().
Referenced by collect_thread_nr().
read_after_slash()
static ullong read_after_slash (const char * p) static
Definition at line 198 of file nmeter.c.
 {
     p = strchr(p, '/');
     if (!p) return 0;
     return strtoull(p+1, NULL, 10);
 }
References NULL, p, strchr(), and strtoull().
Referenced by rdval().
readfile_z()
static void readfile_z (proc_file * pf, const char * fname) static
Definition at line 158 of file nmeter.c.
 {
 // open_read_close() will do two reads in order to be sure we are at EOF,
 // and we don't need/want that.
     int fd;
     int sz, rdsz;
     char *buf;
     sz = pf->file_sz;
     buf = pf->file;
     if (!buf) {
         buf = xmalloc(PROC_MIN_FILE_SIZE);
         sz = PROC_MIN_FILE_SIZE;
     }
  again:
     fd = xopen(fname, O_RDONLY);
     buf[0] = '\0';
     rdsz = read(fd, buf, sz-1);
     close(fd);
     if (rdsz > 0) {
         if (rdsz == sz-1 && sz < PROC_MAX_FILE_SIZE) {
             sz *= 2;
             buf = xrealloc(buf, sz);
             goto again;
         }
         buf[rdsz] = '\0';
     }
     pf->file_sz = sz;
     pf->file = buf;
 }
References buf, close(), fd, proc_file::file, proc_file::file_sz, fname, O_RDONLY, PROC_MAX_FILE_SIZE, PROC_MIN_FILE_SIZE, read(), xmalloc, xopen(), and xrealloc.
Referenced by get_file().
reset_outbuf()
static void reset_outbuf (void) inline static
Definition at line 123 of file nmeter.c.
 {
     cur_outbuf = outbuf;
 }
References cur_outbuf, and outbuf.
Referenced by nmeter_main().
scale()
static void scale (ullong ul) static
Definition at line 310 of file nmeter.c.
 {
     char buf[5];
     /* see http://en.wikipedia.org/wiki/Tera */
     smart_ulltoa4(ul, buf, " kmgtpezy")[0] = '\0';
     put(buf);
 }
References buf, put(), and smart_ulltoa4().
Variable Documentation
ALIGN1
const char options [] ALIGN1 = "ncmsfixptTbr" static
Definition at line 864 of file nmeter.c.
ALIGN_PTR
init_func* const init_functions [] ALIGN_PTR static
Initial value:
= {
    "stat",
    "loadavg",
    "net/dev",
    "meminfo",
    "diskstats",
    "sys/fs/file-nr"
}
Definition at line 73 of file nmeter.c.
bar
char bar[1]
Definition at line 353 of file nmeter.c.
Referenced by collect_cpu(), and tree_print().
bar_sz
unsigned bar_sz
Definition at line 352 of file nmeter.c.
Referenced by collect_cpu().
device
const char* device
Definition at line 581 of file nmeter.c.
Referenced by add_to_uuid_cache(), base_device(), create_fs_device(), del_loop(), device_already_active(), device_open(), df_main(), eject_main(), execute(), init_if(), is_ide_cdrom_or_tape(), nbdclient_main(), open_list_and_close(), query_loop(), serial_get(), set_loop(), setconsole_main(), SndDeviceInList(), swap_enable_disable(), traceroute_init(), umount_main(), uuidcache_addentry(), uuidcache_check_device(), volname_main(), watchdog_open(), and xset1().
device_colon
char* device_colon
Definition at line 582 of file nmeter.c.
lookfor
const char* lookfor
Definition at line 493 of file nmeter.c.
no
int no
Definition at line 433 of file nmeter.c.
Referenced by build_conf(), change_sym_value(), ConfigList::changeValue(), conf(), conf_askvalue(), conf_choice(), conf_read(), conf_read_simple(), conf_sym(), conf_write(), ConfigList::contentsMouseReleaseEvent(), expr_calc_value(), fill_row(), ConfigList::keyPressEvent(), menu_is_visible(), P_LoadNodes(), ConfigList::setValue(), sym_calc_choice(), sym_calc_value(), sym_calc_visibility(), sym_get_default_prop(), sym_get_range_prop(), sym_get_string_value(), sym_set_string_value(), sym_set_tristate_value(), sym_string_within_range(), sym_toggle_tristate_value(), sym_tristate_within_range(), and ConfigItem::updateMenu().
old
ullong old
Definition at line 351 of file nmeter.c.
Referenced by __dup3(), __duplocale(), __env_rm_add(), __getitimer_time32(), __libc_sigaction(), __pthread_mutex_trylock_owner(), __pthread_mutex_unlock(), __pthread_setcancelstate(), __setitimer_time32(), __sigaction(), __sys_dup2(), __timer_gettime32(), __timer_settime32(), __timerfd_gettime32(), __timerfd_settime32(), __tsearch_balance(), __uselocale(), _hs_replace_history_data(), _nl_find_msg(), _rl_copy_to_kill_ring(), a_cas(), a_cas_p(), a_fetch_add(), a_fetch_and(), a_fetch_or(), a_swap(), alarm(), alloc_pid_list(), collect_blk(), collect_cpu(), collect_ctx(), collect_fork(), collect_if(), collect_int(), conspy_main(), convert_ioctl_struct(), copy_function_def_contents(), dup2(), get_interval(), getitimer(), getty_main(), grep_file(), heredoc_expand(), history_rename(), history_search_pos(), indirection_level_string(), initstate(), jiffies_diff(), malloc_set_register(), malloc_set_trace(), mq_setattr(), next_file(), noninc_search_from_pos(), obscure(), pivot_root(), pthread_mutex_consistent(), pthread_setcanceltype(), pthread_sigmask(), redirection_expand(), rename(), renameat(), reset_job_indices(), same_serv_addr_proto(), save_irq_count(), set_job_control(), setitimer(), setstate(), sigaltstack(), sigprocmask(), strgrow(), system(), timer_settime(), timerfd_settime(), traverses_stack_p(), trim(), update_line(), and xmkpath().
opt
char opt
Definition at line 626 of file nmeter.c.
Referenced by __dls3(), __getopt_long_core(), accept_builtin(), add_shopt_to_alist(), adjtimex_main(), ar_main(), asort_builtin(), awk_main(), bzip2_main(), cbq_print_opt(), chpasswd_main(), chpst_main(), chrt_main(), cmp_main(), csv_builtin(), cut_internal(), cut_main(), cut_out_ull_opt(), d6_copy_option(), date_main(), decode_arg(), df_main(), display_opt(), display_single(), dpkg_deb_main(), dpkg_main(), dsv_builtin(), du_main(), dumpleases_main(), execute_all(), expand_main(), exportcmd(), fakeidentd_main(), fdflags_builtin(), fdisk_main(), finfo_main(), flock_main(), generate_output(), getconf_builtin(), getopt32(), getopt_main(), getopt_mk_fifo_nod(), getsebool_main(), getsubopt(), gzip_main(), hasmntopt(), head_builtin(), head_main(), httpd_main(), hush_main(), hwclock_main(), id_builtin(), id_main(), inetd_main(), invarg_1_to_2(), ionice_main(), iostat_main(), ip_parse_common_args(), ipcalc_main(), ipcs_main(), kbd_mode_main(), klogd_main(), last_main(), legal_pathopt(), ln_builtin(), logger_main(), login_main(), losetup_main(), ls_main(), main(), man_main(), mdev_main(), mkdir_builtin(), mkdir_main(), mkfifo_builtin(), mkfs_minix_main(), mktemp_builtin(), modprobe_main(), mount_main(), mountpoint_main(), mpstat_main(), nbdclient_main(), nc_main(), netstat_main(), no_options(), openlog(), opt_in_list(), parse_mount_options(), passwd_main(), paste_main(), patch_main(), pathchk_builtin(), pgrep_main(), pidof_main(), popen_ls(), print_smaprec(), printenv_builtin(), prio_print_opt(), procps_get_maps(), pscan_main(), push_builtin(), pwd_main(), readlink_main(), readprofile_main(), realpath_builtin(), reverse(), rm_builtin(), rm_main(), route_main(), rtcwake_main(), script_main(), sed_main(), seq_builtin(), seq_main(), set_environ(), setfattr_main(), setsid_main(), shred_main(), slattach_main(), split_main(), ssl_client_main(), start_stop_daemon_main(), stat_builtin(), svlogd_main(), sysctl_main(), tail_main(), tar_main(), tee_builtin(), telnetd_main(), template_builtin(), time_main(), ts_main(), tty_builtin(), udhcp_str2optset(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), umount_main(), uname_builtin(), uniq_main(), watch_main(), who_main(), whoami_builtin(), xargs_main(), and xxd_main().
prec
unsigned prec
Definition at line 778 of file nmeter.c.
Referenced by __floatscan(), __rem_pio2_large(), bb_dump_size(), evalbinop(), evaluate_string(), genformat(), init_time(), is_assign_op(), is_right_associative(), rewrite(), strtox(), and wcstox().
scale
unsigned scale
Definition at line 779 of file nmeter.c.
Referenced by __expo2(), __expo2f(), AM_drawLineCharacter(), collect_blk(), collect_ctx(), collect_fd(), collect_fork(), collect_if(), collect_int(), collect_mem(), collect_swp(), collect_thread_nr(), csqrt(), D_DoomMain(), date_main(), do_tzset(), exp(), exp2(), exp_inline(), hexfloat(), R_DrawSprite(), R_InitLightTables(), R_ScaleFromGlobalAngle(), scan_trans(), smart_ulltoa4(), smart_ulltoa5(), and specialcase().