Fennix: Userspace/musl/src/signal/sigprocmask.c File Reference
sigprocmask.c File Reference
#include <signal.h>
#include <errno.h>
Functions
int sigprocmask (int how, const sigset_t *restrict set, sigset_t *restrict old)
Function Documentation
sigprocmask()
int sigprocmask (int how, const sigset_t *restrict set, sigset_t *restrict old)
Definition at line 4 of file sigprocmask.c.
 {
     int r = pthread_sigmask(how, set, old);
     if (!r) return r;
     errno = r;
     return -1;
 }
References errno, and pthread_sigmask().
Referenced by __sig_mask_all(), __sig_mask_test(), sighold(), sigpause(), sigrelse(), system(), and test_signal().