Fennix: Userspace/apps/base/busybox/util-linux/volume_id/unused_msdos.c File Reference
unused_msdos.c File Reference
#include "volume_id_internal.h"
Data Structures
struct msdos_partition_entry
Macros
#define MSDOS_PARTTABLE_OFFSET 0x1be
#define MSDOS_SIG_OFF 0x1fe
#define BSIZE 0x200
#define DOS_EXTENDED_PARTITION 0x05
#define LINUX_EXTENDED_PARTITION 0x85
#define WIN98_EXTENDED_PARTITION 0x0f
#define LINUX_RAID_PARTITION 0xfd
#define is_extended(type)
#define is_raid(type) (type == LINUX_RAID_PARTITION)
Functions
int FAST_FUNC volume_id_probe_msdos_part_table (struct volume_id *id, uint64_t off)
Variables
struct msdos_partition_entry PACKED
Data Structure Documentation
msdos_partition_entry
struct msdos_partition_entry
Definition at line 29 of file unused_msdos.c.
Data Fields
uint8_t boot_ind
uint8_t cyl
uint8_t end_cyl
uint8_t end_head
uint8_t end_sector
uint8_t head
uint32_t nr_sects
uint8_t sector
uint32_t start_sect
uint8_t sys_ind
Macro Definition Documentation
BSIZE
#define BSIZE 0x200
Definition at line 44 of file unused_msdos.c.
DOS_EXTENDED_PARTITION
#define DOS_EXTENDED_PARTITION 0x05
Definition at line 45 of file unused_msdos.c.
is_extended
#define is_extended (type)
Value:
    (type == DOS_EXTENDED_PARTITION ||  \
     type == WIN98_EXTENDED_PARTITION ||    \
     type == LINUX_EXTENDED_PARTITION)
Definition at line 49 of file unused_msdos.c.
is_raid
#define is_raid (type) (type == LINUX_RAID_PARTITION)
Definition at line 53 of file unused_msdos.c.
LINUX_EXTENDED_PARTITION
#define LINUX_EXTENDED_PARTITION 0x85
Definition at line 46 of file unused_msdos.c.
LINUX_RAID_PARTITION
#define LINUX_RAID_PARTITION 0xfd
Definition at line 48 of file unused_msdos.c.
MSDOS_PARTTABLE_OFFSET
#define MSDOS_PARTTABLE_OFFSET 0x1be
Definition at line 42 of file unused_msdos.c.
MSDOS_SIG_OFF
#define MSDOS_SIG_OFF 0x1fe
Definition at line 43 of file unused_msdos.c.
WIN98_EXTENDED_PARTITION
#define WIN98_EXTENDED_PARTITION 0x0f
Definition at line 47 of file unused_msdos.c.
Function Documentation
volume_id_probe_msdos_part_table()
int FAST_FUNC volume_id_probe_msdos_part_table (struct volume_id * id, uint64_t off)
Definition at line 56 of file unused_msdos.c.
 {
     const uint8_t *buf;
     int i;
     uint64_t poff;
     uint64_t plen;
     uint64_t extended = 0;
     uint64_t current;
     uint64_t next;
     int limit;
     int empty = 1;
     struct msdos_partition_entry *part;
     struct volume_id_partition *p;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     buf = volume_id_get_buffer(id, off, 0x200);
     if (buf == NULL)
         return -1;
     if (buf[MSDOS_SIG_OFF] != 0x55 || buf[MSDOS_SIG_OFF + 1] != 0xaa)
         return -1;
     /* check flags on all entries for a valid partition table */
     part = (struct msdos_partition_entry*) &buf[MSDOS_PARTTABLE_OFFSET];
     for (i = 0; i < 4; i++) {
         if (part[i].boot_ind != 0
          && part[i].boot_ind != 0x80
         ) {
             return -1;
         }
         if (part[i].nr_sects != 0)
             empty = 0;
     }
     if (empty == 1)
         return -1;
     if (id->partitions != NULL)
         free(id->partitions);
     id->partitions = xzalloc(VOLUME_ID_PARTITIONS_MAX *
                 sizeof(struct volume_id_partition));
     for (i = 0; i < 4; i++) {
         poff = (uint64_t) le32_to_cpu(part[i].start_sect) * BSIZE;
         plen = (uint64_t) le32_to_cpu(part[i].nr_sects) * BSIZE;
         if (plen == 0)
             continue;
         p = &id->partitions[i];
 //      p->pt_type_raw = part[i].sys_ind;
         if (is_extended(part[i].sys_ind)) {
             dbg("found extended partition at 0x%llx", (unsigned long long) poff);
 //          volume_id_set_usage_part(p, VOLUME_ID_PARTITIONTABLE);
 //          p->type = "msdos_extended_partition";
             if (extended == 0)
                 extended = off + poff;
         } else {
             dbg("found 0x%x data partition at 0x%llx, len 0x%llx",
                 part[i].sys_ind, (unsigned long long) poff, (unsigned long long) plen);
 //          if (is_raid(part[i].sys_ind))
 //              volume_id_set_usage_part(p, VOLUME_ID_RAID);
 //          else
 //              volume_id_set_usage_part(p, VOLUME_ID_UNPROBED);
         }
 //      p->pt_off = off + poff;
 //      p->pt_len = plen;
         id->partition_count = i+1;
     }
     next = extended;
     current = extended;
     limit = 50;
     /* follow extended partition chain and add data partitions */
     while (next != 0) {
         if (limit-- == 0) {
             dbg("extended chain limit reached");
             break;
         }
         buf = volume_id_get_buffer(id, current, 0x200);
         if (buf == NULL)
             break;
         part = (struct msdos_partition_entry*) &buf[MSDOS_PARTTABLE_OFFSET];
         if (buf[MSDOS_SIG_OFF] != 0x55 || buf[MSDOS_SIG_OFF + 1] != 0xaa)
             break;
         next = 0;
         for (i = 0; i < 4; i++) {
             poff = (uint64_t) le32_to_cpu(part[i].start_sect) * BSIZE;
             plen = (uint64_t) le32_to_cpu(part[i].nr_sects) * BSIZE;
             if (plen == 0)
                 continue;
             if (is_extended(part[i].sys_ind)) {
                 dbg("found extended partition at 0x%llx", (unsigned long long) poff);
                 if (next == 0)
                     next = extended + poff;
             } else {
                 dbg("found 0x%x data partition at 0x%llx, len 0x%llx",
                     part[i].sys_ind, (unsigned long long) poff, (unsigned long long) plen);
                 /* we always start at the 5th entry */
 //              while (id->partition_count < 4)
 //                  volume_id_set_usage_part(&id->partitions[id->partition_count++], VOLUME_ID_UNUSED);
                 if (id->partition_count < 4)
                     id->partition_count = 4;
 //              p = &id->partitions[id->partition_count];
 //              if (is_raid(part[i].sys_ind))
 //                  volume_id_set_usage_part(p, VOLUME_ID_RAID);
 //              else
 //                  volume_id_set_usage_part(p, VOLUME_ID_UNPROBED);
 //              p->pt_off = current + poff;
 //              p->pt_len = plen;
                 id->partition_count++;
 //              p->pt_type_raw = part[i].sys_ind;
                 if (id->partition_count >= VOLUME_ID_PARTITIONS_MAX) {
                     dbg("too many partitions");
                     next = 0;
                 }
             }
         }
         current = next;
     }
 //  volume_id_set_usage(id, VOLUME_ID_PARTITIONTABLE);
 //  id->type = "msdos_partition_table";
     return 0;
 }
References msdos_partition_entry::boot_ind, BSIZE, buf, current, dbg, free, i, is_extended, le32_to_cpu, limit(), MSDOS_PARTTABLE_OFFSET, MSDOS_SIG_OFF, next, msdos_partition_entry::nr_sects, NULL, off, p, msdos_partition_entry::start_sect, msdos_partition_entry::sys_ind, volume_id_get_buffer(), VOLUME_ID_PARTITIONS_MAX, and xzalloc().
Variable Documentation
PACKED
struct msdos_partition_entry PACKED