Fennix: Kernel/Library/MemoryMoveSIMD.cpp File Reference
MemoryMoveSIMD.cpp File Reference
#include <convert.h>
#include <memory.hpp>
#include <limits.h>
#include <debug.h>
#include <cpu.hpp>
Functions
EXTERNC void * memmove_sse (void *dest, const void *src, size_t n)
EXTERNC void * memmove_sse2 (void *dest, const void *src, size_t n)
EXTERNC void * memmove_sse3 (void *dest, const void *src, size_t n)
EXTERNC void * memmove_ssse3 (void *dest, const void *src, size_t n)
EXTERNC void * memmove_sse4_1 (void *dest, const void *src, size_t n)
EXTERNC void * memmove_sse4_2 (void *dest, const void *src, size_t n)
Function Documentation
memmove_sse()
EXTERNC void* memmove_sse (void * dest, const void * src, size_t n)
Definition at line 15 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe().
Referenced by __memmove_chk().
memmove_sse2()
EXTERNC void* memmove_sse2 (void * dest, const void * src, size_t n)
Definition at line 20 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe().
Referenced by __memmove_chk().
memmove_sse3()
EXTERNC void* memmove_sse3 (void * dest, const void * src, size_t n)
Definition at line 25 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe().
Referenced by __memmove_chk().
memmove_sse4_1()
EXTERNC void* memmove_sse4_1 (void * dest, const void * src, size_t n)
Definition at line 35 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe().
Referenced by __memmove_chk().
memmove_sse4_2()
EXTERNC void* memmove_sse4_2 (void * dest, const void * src, size_t n)
Definition at line 40 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe().
Referenced by __memmove_chk().
memmove_ssse3()
EXTERNC void* memmove_ssse3 (void * dest, const void * src, size_t n)
Definition at line 30 of file MemoryMoveSIMD.cpp.
 {
     return memmove_unsafe(dest, src, n);
 }
References memmove_unsafe().
Referenced by __memmove_chk().