Fennix: Userspace/apps/base/busybox/libbb/safe_poll.c File Reference
safe_poll.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC safe_poll (struct pollfd *ufds, nfds_t nfds, int timeout)
Function Documentation
safe_poll()
int FAST_FUNC safe_poll (struct pollfd * ufds, nfds_t nfds, int timeout)
Definition at line 14 of file safe_poll.c.
 {
     while (1) {
         int n = poll(ufds, nfds, timeout);
         if (n >= 0)
             return n;
         /* Make sure we inch towards completion */
         if (timeout > 0)
             timeout--;
         /* E.g. strace causes poll to return this */
         if (errno == EINTR)
             continue;
         /* Kernel is very low on memory. Retry. */
         /* I doubt many callers would handle this correctly! */
         if (errno == ENOMEM)
             continue;
         bb_simple_perror_msg("poll");
         return n;
     }
 }
References bb_simple_perror_msg(), EINTR, ENOMEM, errno, n, poll(), and timeout().
Referenced by acpid_main(), arpping(), getch_nowait(), microcom_main(), mysleep(), nc_main(), nonblock_immune_read(), powertop_main(), read_key(), retrieve_file_data(), tls_run_copy_loop(), and wait_for_reply().