Fennix Userspace: Userspace/mlibc/options/posix/generic/semaphore-stubs.cpp File Reference
semaphore-stubs.cpp File Reference
#include <semaphore.h>
#include <errno.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Functions
int sem_init (sem_t *sem, int pshared, unsigned int initial_count)
int sem_destroy (sem_t *)
int sem_wait (sem_t *sem)
int sem_timedwait (sem_t *sem, const struct timespec *)
int sem_post (sem_t *sem)
sem_t * sem_open (const char *, int,...)
int sem_close (sem_t *)
int sem_getvalue (sem_t *, int *)
int sem_unlink (const char *)
int sem_trywait (sem_t *)
Variables
static constexpr unsigned int semaphoreHasWaiters = static_cast<uint32_t>(1 << 31)
static constexpr unsigned int semaphoreCountMask = static_cast<uint32_t>(1 << 31) - 1
Function Documentation
sem_close()
int sem_close (sem_t * sem)
Definition at line 85 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sem_destroy()
int sem_destroy (sem_t * sem)
Definition at line 28 of file semaphore-stubs.cpp.
{
     return 0;
 }
sem_getvalue()
int sem_getvalue (sem_t * sem, int * sval)
Definition at line 90 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sem_init()
int sem_init (sem_t * sem, int pshared, unsigned int initial_count)
Definition at line 11 of file semaphore-stubs.cpp.
{
     if (pshared) {
         mlibc::infoLogger() << "mlibc: shared semaphores are unsuppored" << frg::endlog;
         errno = ENOSYS;
         return -1;
     }
     if (initial_count > SEM_VALUE_MAX) {
         errno = EINVAL;
         return -1;
     }
     sem->__mlibc_count = initial_count;
     return 0;
 }
References sem_::__mlibc_count, EINVAL, ENOSYS, errno, mlibc::infoLogger, and SEM_VALUE_MAX.
sem_open()
sem_t* sem_open (const char * , int , ...)
Definition at line 80 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sem_post()
int sem_post (sem_t * sem)
Definition at line 63 of file semaphore-stubs.cpp.
{
     auto old_count = __atomic_load_n(&sem->__mlibc_count, __ATOMIC_RELAXED) & semaphoreCountMask;
     if (old_count + 1 > SEM_VALUE_MAX) {
         errno = EOVERFLOW;
         return -1;
     }
     auto state = __atomic_exchange_n(&sem->__mlibc_count, old_count + 1, __ATOMIC_RELEASE);
     if (state & semaphoreHasWaiters)
         if (int e = mlibc::sys_futex_wake((int *)&sem->__mlibc_count); e)
             __ensure(!"sys_futex_wake() failed");
     return 0;
 }
References __ensure, sem_::__mlibc_count, EOVERFLOW, errno, SEM_VALUE_MAX, semaphoreCountMask, semaphoreHasWaiters, state, and mlibc::sys_futex_wake().
sem_timedwait()
int sem_timedwait (sem_t * sem, const struct timespec * abstime)
Definition at line 58 of file semaphore-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31mmlibc: sem_timedwait is implemented as sem_wait\e[0m" << frg::endlog;
     return sem_wait(sem);
 }
References mlibc::infoLogger, and sem_wait().
sem_trywait()
int sem_trywait (sem_t * sem)
Definition at line 100 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sem_unlink()
int sem_unlink (const char *)
Definition at line 95 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sem_wait()
int sem_wait (sem_t * sem)
Definition at line 32 of file semaphore-stubs.cpp.
{
     unsigned int state = 0;
     while (1) {
         if (!(state & semaphoreCountMask)) {
             if (__atomic_compare_exchange_n(&sem->__mlibc_count, &state, semaphoreHasWaiters,
                         false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
                 int e = mlibc::sys_futex_wait((int *)&sem->__mlibc_count, state, nullptr);
                 if (e == 0 || e == EAGAIN) {
                     continue;
                 } else if (e == EINTR) {
                     errno = EINTR;
                     return -1;
                 } else {
                     mlibc::panicLogger() << "sys_futex_wait() failed with error code " << e << frg::endlog;
                 }
             }
         } else {
             unsigned int desired = (state - 1);
             if (__atomic_compare_exchange_n(&sem->__mlibc_count, &state, desired, false,
                         __ATOMIC_RELAXED, __ATOMIC_RELAXED))
                 return 0;
         }
     }
 }
References sem_::__mlibc_count, EAGAIN, EINTR, errno, mlibc::panicLogger, semaphoreCountMask, semaphoreHasWaiters, state, and mlibc::sys_futex_wait().
Referenced by sem_timedwait().
Variable Documentation
semaphoreCountMask
constexpr unsigned int semaphoreCountMask = static_cast<uint32_t>(1 << 31) - 1 static constexpr
Definition at line 9 of file semaphore-stubs.cpp.
Referenced by sem_post(), and sem_wait().
semaphoreHasWaiters
constexpr unsigned int semaphoreHasWaiters = static_cast<uint32_t>(1 << 31) static constexpr
Definition at line 8 of file semaphore-stubs.cpp.
Referenced by sem_post(), and sem_wait().