Fennix: Userspace/mlibc/tests/posix/pthread_cleanup.c File Reference
pthread_cleanup.c File Reference
#include <stdint.h>
#include <assert.h>
#include <pthread.h>
Functions
static void cleanup (void *arg)
static void * worker (void *arg)
int main ()
Variables
_Atomic uintptr_t cleanup_val = 0
Function Documentation
cleanup()
static void cleanup (void * arg) static
Definition at line 7 of file pthread_cleanup.c.
{
     cleanup_val = (uintptr_t)arg;
 }
References mlibc::arg, and cleanup_val.
Referenced by worker().
main()
int main (void)
Definition at line 33 of file pthread_cleanup.c.
            {
     pthread_t thread;
     assert(!pthread_create(&thread, NULL, &worker, NULL));
     assert(!pthread_join(thread, NULL));
     assert(cleanup_val == 1);
     return 0;
 }
References assert, cleanup_val, NULL, pthread_create(), pthread_join(), and worker().
worker()
static void* worker (void * arg) static
Definition at line 11 of file pthread_cleanup.c.
{
     (void)arg;
     pthread_cleanup_push(cleanup, (void *)1);
     pthread_cleanup_push(cleanup, (void *)2);
     pthread_cleanup_push(cleanup, (void *)3);
     pthread_cleanup_push(cleanup, (void *)4);
     pthread_cleanup_pop(1);
     assert(cleanup_val == 4);
     pthread_cleanup_pop(0);
     assert(cleanup_val == 4);
     pthread_exit(NULL);
     pthread_cleanup_pop(0);
     pthread_cleanup_pop(0);
     return NULL;
 }
References mlibc::arg, assert, cleanup(), cleanup_val, NULL, pthread_cleanup_pop(), pthread_cleanup_push(), pthread_exit(), and Driver::void().
Referenced by main().
Variable Documentation
cleanup_val
_Atomic uintptr_t cleanup_val = 0
Definition at line 5 of file pthread_cleanup.c.
Referenced by cleanup(), main(), and worker().