Fennix: Userspace/apps/base/bash/lib/readline/bind.c File Reference
bind.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <fcntl.h>
#include "ansi_stdlib.h"
#include <errno.h>
#include "posixstat.h"
#include "rldefs.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "rlshell.h"
#include "xmalloc.h"
Data Structures
struct assoc_list
struct name_and_keymap
Macros
#define READLINE_LIBRARY
#define OP_EQ 1
#define OP_NE 2
#define OP_GT 3
#define OP_GE 4
#define OP_LT 5
#define OP_LE 6
#define OPSTART(c) ((c) == '=' || (c) == '!' || (c) == '<' || (c) == '>')
#define CMPSTART(c) ((c) == '=' || (c) == '!')
#define V_SPECIAL 0x1
#define V_BELLSTYLE 0
#define V_COMBEGIN 1
#define V_EDITMODE 2
#define V_ISRCHTERM 3
#define V_KEYMAP 4
#define V_STRING 1
#define V_INT 2
#define NUM_BUILTIN_KEYMAPS (sizeof (builtin_keymap_names) / sizeof (builtin_keymap_names[0]) - 1)
Typedefs
typedef int _rl_parser_func_t(char *)
typedef int _rl_sv_func_t(const char *)
Functions
char * strchr ()
char * strrchr ()
static int _rl_skip_to_delim (char *, int, int)
static void _rl_init_file_error ()
static rl_command_func_t * _rl_function_of_keyseq_internal (const char *, size_t, Keymap, int *)
static char * _rl_read_file (char *, size_t *)
static int _rl_read_init_file (const char *, int)
static int glean_key_from_name (char *)
static int find_boolean_var (const char *)
static int find_string_var (const char *)
static const char * boolean_varname (int)
static const char * string_varname (int)
static char * _rl_get_string_variable_value (const char *)
static int substring_member_of_array (const char *, const char *const *)
static int _rl_get_keymap_by_name (const char *)
static int _rl_get_keymap_by_map (Keymap)
int rl_add_defun (const char *name, rl_command_func_t *function, int key)
int rl_bind_key (int key, rl_command_func_t *function)
int rl_bind_key_in_map (int key, rl_command_func_t *function, Keymap map)
int rl_bind_key_if_unbound_in_map (int key, rl_command_func_t *default_func, Keymap kmap)
int rl_bind_key_if_unbound (int key, rl_command_func_t *default_func)
int rl_unbind_key (int key)
int rl_unbind_key_in_map (int key, Keymap map)
int rl_unbind_function_in_map (rl_command_func_t *func, Keymap map)
int rl_unbind_command_in_map (const char *command, Keymap map)
int rl_bind_keyseq (const char *keyseq, rl_command_func_t *function)
int rl_bind_keyseq_in_map (const char *keyseq, rl_command_func_t *function, Keymap map)
int rl_set_key (const char *keyseq, rl_command_func_t *function, Keymap map)
int rl_bind_keyseq_if_unbound_in_map (const char *keyseq, rl_command_func_t *default_func, Keymap kmap)
int rl_bind_keyseq_if_unbound (const char *keyseq, rl_command_func_t *default_func)
int rl_macro_bind (const char *keyseq, const char *macro, Keymap map)
int rl_generic_bind (int type, const char *keyseq, char *data, Keymap map)
int rl_translate_keyseq (const char *seq, char *array, int *len)
static int _rl_isescape (int c)
static int _rl_escchar (int c)
char * rl_untranslate_keyseq (int seq)
char * _rl_untranslate_macro_value (char *seq, int use_escapes)
rl_command_func_t * rl_named_function (const char *string)
rl_command_func_t * rl_function_of_keyseq (const char *keyseq, Keymap map, int *type)
rl_command_func_t * rl_function_of_keyseq_len (const char *keyseq, size_t len, Keymap map, int *type)
int rl_trim_arg_from_keyseq (const char *keyseq, size_t len, Keymap map)
int rl_re_read_init_file (int count, int ignore)
int rl_read_init_file (const char *filename)
static void _rl_init_file_error (va_alist)
static int parse_comparison_op (char *s, int *indp) const
static int parser_if (char *)
static int parser_else (char *)
static int parser_endif (char *)
static int parser_include (char *)
static int handle_parser_directive (char *statement)
int rl_parse_and_bind (char *string)
static void hack_special_boolean_var (int i)
static int sv_region_start_color (const char *)
static int sv_region_end_color (const char *)
static int sv_bell_style (const char *)
static int sv_combegin (const char *)
static int sv_dispprefix (const char *)
static int sv_compquery (const char *)
static int sv_compwidth (const char *)
static int sv_editmode (const char *)
static int sv_emacs_modestr (const char *)
static int sv_histsize (const char *)
static int sv_isrchterm (const char *)
static int sv_keymap (const char *)
static int sv_seqtimeout (const char *)
static int sv_viins_modestr (const char *)
static int sv_vicmd_modestr (const char *)
static int bool_to_int (const char *value)
char * rl_variable_value (const char *name)
int rl_variable_bind (const char *name, const char *value)
Keymap rl_get_keymap_by_name (const char *name)
char * rl_get_keymap_name (Keymap map)
int rl_set_keymap_name (const char *name, Keymap map)
void rl_set_keymap (Keymap map)
Keymap rl_get_keymap (void)
void rl_set_keymap_from_edit_mode (void)
char * rl_get_keymap_name_from_edit_mode (void)
void rl_list_funmap_names (void)
static char * _rl_get_keyname (int key)
char ** rl_invoking_keyseqs_in_map (rl_command_func_t *function, Keymap map)
char ** rl_invoking_keyseqs (rl_command_func_t *function)
void rl_function_dumper (int print_readably)
int rl_dump_functions (int count, int key)
static void _rl_macro_dumper_internal (int print_readably, Keymap map, char *prefix)
void rl_macro_dumper (int print_readably)
int rl_dump_macros (int count, int key)
void rl_variable_dumper (int print_readably)
int rl_dump_variables (int count, int key)
Variables
int errno
Keymap rl_binding_keymap
static int currently_reading_init_file
static int _rl_prefer_visible_bell = 1
static char * last_readline_init_file = (char *)NULL
static const char * current_readline_init_file
static int current_readline_init_include_level
static int current_readline_init_lineno
const char *const _rl_possible_control_prefixes []
const char *const _rl_possible_meta_prefixes []
const char * rl_readline_name = "other"
static unsigned char * if_stack = (unsigned char *)NULL
static int if_stack_depth
static int if_stack_size
struct {
const char *const name
_rl_parser_func_t * function
} parser_directives []
struct {
const char *const name
int * value
int flags
} boolean_varlist []
struct {
const char *const name
int flags
_rl_sv_func_t * set_func
} string_varlist []
char * _rl_emacs_mode_str
static const assoc_list name_key_alist []
static struct name_and_keymap builtin_keymap_names []
static struct name_and_keymap * keymap_names = builtin_keymap_names
Data Structure Documentation
assoc_list
struct assoc_list
Definition at line 2379 of file bind.c.
Data Fields
const char *const name
int value
name_and_keymap
struct name_and_keymap
Definition at line 2412 of file bind.c.
Data Fields
Keymap map
char * name
Macro Definition Documentation
CMPSTART
#define CMPSTART (c) ((c) == '=' || (c) == '!')
Definition at line 114 of file bind.c.
NUM_BUILTIN_KEYMAPS
#define NUM_BUILTIN_KEYMAPS (sizeof (builtin_keymap_names) / sizeof (builtin_keymap_names[0]) - 1)
Definition at line 2432 of file bind.c.
OP_EQ
#define OP_EQ 1
Definition at line 106 of file bind.c.
OP_GE
#define OP_GE 4
Definition at line 109 of file bind.c.
OP_GT
#define OP_GT 3
Definition at line 108 of file bind.c.
OP_LE
#define OP_LE 6
Definition at line 111 of file bind.c.
OP_LT
#define OP_LT 5
Definition at line 110 of file bind.c.
OP_NE
#define OP_NE 2
Definition at line 107 of file bind.c.
OPSTART
#define OPSTART (c) ((c) == '=' || (c) == '!' || (c) == '<' || (c) == '>')
Definition at line 113 of file bind.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file bind.c.
V_BELLSTYLE
#define V_BELLSTYLE 0
Definition at line 1976 of file bind.c.
V_COMBEGIN
#define V_COMBEGIN 1
Definition at line 1977 of file bind.c.
V_EDITMODE
#define V_EDITMODE 2
Definition at line 1978 of file bind.c.
V_INT
#define V_INT 2
Definition at line 1983 of file bind.c.
V_ISRCHTERM
#define V_ISRCHTERM 3
Definition at line 1979 of file bind.c.
V_KEYMAP
#define V_KEYMAP 4
Definition at line 1980 of file bind.c.
V_SPECIAL
#define V_SPECIAL 0x1
Definition at line 1882 of file bind.c.
V_STRING
#define V_STRING 1
Definition at line 1982 of file bind.c.
Typedef Documentation
_rl_parser_func_t
typedef int _rl_parser_func_t(char *)
Definition at line 1225 of file bind.c.
_rl_sv_func_t
typedef int _rl_sv_func_t(const char *)
Definition at line 1972 of file bind.c.
Function Documentation
_rl_escchar()
static int _rl_escchar (int c) static
Definition at line 669 of file bind.c.
 {
   switch (c)
     {
     case '\007':  return ('a');
     case '\b':  return ('b');
     case '\f':  return ('f');
     case '\n':  return ('n');
     case '\r':  return ('r');
     case TAB:  return ('t');
     case 0x0b:  return ('v');
     default: return (c);
     }
 }
References c, and TAB.
Referenced by _rl_untranslate_macro_value().
_rl_function_of_keyseq_internal()
static rl_command_func_t * _rl_function_of_keyseq_internal (const char * keyseq, size_t len, Keymap map, int * type) static
Definition at line 812 of file bind.c.
 {
   register int i;
   if (map == 0)
     map = _rl_keymap;
   for (i = 0; keyseq && i < len; i++)
     {
       unsigned char ic = keyseq[i];
       if (META_CHAR (ic) && _rl_convert_meta_chars_to_ascii)
     {
       if (map[ESC].type == ISKMAP)
         {
           map = FUNCTION_TO_KEYMAP (map, ESC);
           ic = UNMETA (ic);
         }
       /* XXX - should we just return NULL here, since this obviously
          doesn't match? */
       else
         {
           if (type)
         *type = map[ESC].type;
           return (map[ESC].function);
         }
     }
       if (map[ic].type == ISKMAP)
     {
       /* If this is the last key in the key sequence, return the
          map. */
       if (i + 1 == len)
         {
           if (type)
         *type = ISKMAP;
           return (map[ic].function);
         }
       else
         map = FUNCTION_TO_KEYMAP (map, ic);
     }
       /* If we're not at the end of the key sequence, and the current key
      is bound to something other than a keymap, then the entire key
      sequence is not bound. */
       else if (map[ic].type != ISKMAP && i+1 < len)
     return ((rl_command_func_t *)NULL);
       else  /* map[ic].type != ISKMAP && i+1 == len */
     {
       if (type)
         *type = map[ic].type;
       return (map[ic].function);
     }
     }
   return ((rl_command_func_t *) NULL);
 }
References _rl_convert_meta_chars_to_ascii, _rl_keymap, ESC, FUNCTION_TO_KEYMAP, i, ISKMAP, len, map, META_CHAR, NULL, type, and UNMETA.
Referenced by rl_function_of_keyseq(), and rl_function_of_keyseq_len().
_rl_get_keymap_by_map()
static int _rl_get_keymap_by_map (Keymap map) static
Definition at line 2457 of file bind.c.
 {
   register int i;
   for (i = 0; keymap_names[i].name; i++)
     if (map == keymap_names[i].map)
       return (i);
   return -1;
 }
References i, keymap_names, map, and name_and_keymap::name.
Referenced by rl_get_keymap_name(), and rl_set_keymap_name().
_rl_get_keymap_by_name()
static int _rl_get_keymap_by_name (const char * name) static
Definition at line 2437 of file bind.c.
 {
   register int i;
   for (i = 0; keymap_names[i].name; i++)
     if (_rl_stricmp (name, keymap_names[i].name) == 0)
       return (i);
   return -1;
 }
References _rl_stricmp(), i, keymap_names, and name_and_keymap::name.
Referenced by rl_get_keymap_by_name(), and rl_set_keymap_name().
_rl_get_keyname()
static char* _rl_get_keyname (int key) static
Definition at line 2593 of file bind.c.
 {
   char *keyname;
   int i, c;
   keyname = (char *)xmalloc (8);
   c = key;
   /* Since this is going to be used to write out keysequence-function
      pairs for possible inclusion in an inputrc file, we don't want to
      do any special meta processing on KEY. */
 #if 1
   /* XXX - Experimental */
   /* We might want to do this, but the old version of the code did not. */
   /* If this is an escape character, we don't want to do any more processing.
      Just add the special ESC key sequence and return. */
   if (c == ESC)
     {
       keyname[0] = '\\';
       keyname[1] = 'e';
       keyname[2] = '\0';
       return keyname;
     }
 #endif
   /* RUBOUT is translated directly into \C-? */
   if (key == RUBOUT)
     {
       keyname[0] = '\\';
       keyname[1] = 'C';
       keyname[2] = '-';
       keyname[3] = '?';
       keyname[4] = '\0';
       return keyname;
     }
   i = 0;
   /* Now add special prefixes needed for control characters.  This can
      potentially change C. */
   if (CTRL_CHAR (c))
     {
       keyname[i++] = '\\';
       keyname[i++] = 'C';
       keyname[i++] = '-';
       c = _rl_to_lower (UNCTRL (c));
     }
   /* XXX experimental code.  Turn the characters that are not ASCII or
      ISO Latin 1 (128 - 159) into octal escape sequences (\200 - \237).
      This changes C. */
   if (c >= 128 && c <= 159)
     {
       keyname[i++] = '\\';
       keyname[i++] = '2';
       c -= 128;
       keyname[i++] = (c / 8) + '0';
       c = (c % 8) + '0';
     }
   /* These characters are valid UTF-8; convert them into octal escape
      sequences as well. This changes C. */
   else if (c >= 160)
     {
       keyname[i++] = '\\';
       keyname[i++] = '0' + ((((unsigned char)c) >> 6) & 0x07);
       keyname[i++] = '0' + ((((unsigned char)c) >> 3) & 0x07);
       c = (c % 8) + '0';
     }
   /* Now, if the character needs to be quoted with a backslash, do that. */
   if (c == '\\' || c == '"')
     keyname[i++] = '\\';
   /* Now add the key, terminate the string, and return it. */
   keyname[i++] = (char) c;
   keyname[i] = '\0';
   return keyname;
 }
References _rl_to_lower(), c, CTRL_CHAR, ESC, i, RUBOUT, UNCTRL, and xmalloc.
Referenced by _rl_macro_dumper_internal(), and rl_invoking_keyseqs_in_map().
_rl_get_string_variable_value()
static char * _rl_get_string_variable_value (const char * name) static
Definition at line 2951 of file bind.c.
 {
   static char numbuf[32];
   char *ret;
   if (_rl_stricmp (name, "bell-style") == 0)
     {
       switch (_rl_bell_preference)
     {
       case NO_BELL:
         return "none";
       case VISIBLE_BELL:
         return "visible";
       case AUDIBLE_BELL:
       default:
         return "audible";
     }
     }
   else if (_rl_stricmp (name, "comment-begin") == 0)
     return (_rl_comment_begin ? _rl_comment_begin : RL_COMMENT_BEGIN_DEFAULT);
   else if (_rl_stricmp (name, "completion-display-width") == 0)
     {
       sprintf (numbuf, "%d", _rl_completion_columns);
       return (numbuf);
     }
   else if (_rl_stricmp (name, "completion-prefix-display-length") == 0)
     {
       sprintf (numbuf, "%d", _rl_completion_prefix_display_length);
       return (numbuf);
     }
   else if (_rl_stricmp (name, "completion-query-items") == 0)
     {
       sprintf (numbuf, "%d", rl_completion_query_items);
       return (numbuf);
     }
   else if (_rl_stricmp (name, "editing-mode") == 0)
     return (rl_get_keymap_name_from_edit_mode ());
   else if (_rl_stricmp (name, "history-size") == 0)
     {
       sprintf (numbuf, "%d", history_is_stifled() ? history_max_entries : 0);
       return (numbuf);
     }
   else if (_rl_stricmp (name, "isearch-terminators") == 0)
     {
       if (_rl_isearch_terminators == 0)
     return 0;
       ret = _rl_untranslate_macro_value (_rl_isearch_terminators, 0);
       if (ret)
     {
       strncpy (numbuf, ret, sizeof (numbuf) - 1);
       xfree (ret);
       numbuf[sizeof(numbuf) - 1] = '\0';
     }
       else
     numbuf[0] = '\0';
       return numbuf;
     }
   else if (_rl_stricmp (name, "keymap") == 0)
     {
       ret = rl_get_keymap_name (_rl_keymap);
       if (ret == 0)
     ret = rl_get_keymap_name_from_edit_mode ();
       return (ret ? ret : "none");
     }
   else if (_rl_stricmp (name, "keyseq-timeout") == 0)
     {
       sprintf (numbuf, "%d", _rl_keyseq_timeout);
       return (numbuf);
     }
   else if (_rl_stricmp (name, "emacs-mode-string") == 0)
     return (_rl_emacs_mode_str ? _rl_emacs_mode_str : RL_EMACS_MODESTR_DEFAULT);
   else if (_rl_stricmp (name, "vi-cmd-mode-string") == 0)
     return (_rl_vi_cmd_mode_str ? _rl_vi_cmd_mode_str : RL_VI_CMD_MODESTR_DEFAULT);
   else if (_rl_stricmp (name, "vi-ins-mode-string") == 0)
     return (_rl_vi_ins_mode_str ? _rl_vi_ins_mode_str : RL_VI_INS_MODESTR_DEFAULT);
   else
     return (0);
 }
References _rl_bell_preference, _rl_comment_begin, _rl_completion_columns, _rl_completion_prefix_display_length, _rl_emacs_mode_str, _rl_isearch_terminators, _rl_keymap, _rl_keyseq_timeout, _rl_stricmp(), _rl_untranslate_macro_value(), _rl_vi_cmd_mode_str, _rl_vi_ins_mode_str, AUDIBLE_BELL, history_is_stifled(), history_max_entries, name_and_keymap::name, NO_BELL, RL_COMMENT_BEGIN_DEFAULT, rl_completion_query_items, RL_EMACS_MODESTR_DEFAULT, rl_get_keymap_name(), rl_get_keymap_name_from_edit_mode(), RL_VI_CMD_MODESTR_DEFAULT, RL_VI_INS_MODESTR_DEFAULT, sprintf(), strncpy(), VISIBLE_BELL, and xfree.
Referenced by rl_variable_dumper(), and rl_variable_value().
_rl_init_file_error() [1/2]
static void _rl_init_file_error () static
Referenced by handle_parser_directive(), parser_else(), parser_endif(), parser_if(), rl_parse_and_bind(), and rl_variable_bind().
_rl_init_file_error() [2/2]
static void _rl_init_file_error (va_alist) static
Definition at line 1135 of file bind.c.
 {
   va_list args;
 #if defined (PREFER_VARARGS)
   char *format;
 #endif
 #if defined (PREFER_STDARG)
   va_start (args, format);
 #else
   va_start (args);
   format = va_arg (args, char *);
 #endif
   fprintf (stderr, "readline: ");
   if (currently_reading_init_file)
     fprintf (stderr, "%s: line %d: ", current_readline_init_file,
              current_readline_init_lineno);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   fflush (stderr);
   va_end (args);
 }
References args, current_readline_init_file, current_readline_init_lineno, currently_reading_init_file, fflush(), format(), fprintf(), stderr, va_arg, va_end, va_start, and vfprintf().
_rl_isescape()
static int _rl_isescape (int c) static
Definition at line 653 of file bind.c.
 {
   switch (c)
     {
     case '\007':
     case '\b':
     case '\f':
     case '\n':
     case '\r':
     case TAB:
     case 0x0b:  return (1);
     default: return (0);
     }
 }
References c, and TAB.
Referenced by _rl_untranslate_macro_value().
_rl_macro_dumper_internal()
static void _rl_macro_dumper_internal (int print_readably, Keymap map, char * prefix) static
Definition at line 2876 of file bind.c.
 {
   register int key;
   char *keyname, *out;
   int prefix_len;
   for (key = 0; key < KEYMAP_SIZE; key++)
     {
       switch (map[key].type)
     {
     case ISMACR:
       keyname = _rl_get_keyname (key);
       out = _rl_untranslate_macro_value ((char *)map[key].function, 0);
       if (print_readably)
         fprintf (rl_outstream, "\"%s%s\": \"%s\"\n", prefix ? prefix : "",
                                  keyname,
                                  out ? out : "");
       else
         fprintf (rl_outstream, "%s%s outputs %s\n", prefix ? prefix : "",
                             keyname,
                             out ? out : "");
       xfree (keyname);
       xfree (out);
       break;
     case ISFUNC:
       break;
     case ISKMAP:
       prefix_len = prefix ? strlen (prefix) : 0;
       if (key == ESC)
         {
           keyname = (char *)xmalloc (3 + prefix_len);
           if (prefix)
         strcpy (keyname, prefix);
           keyname[prefix_len] = '\\';
           keyname[prefix_len + 1] = 'e';
           keyname[prefix_len + 2] = '\0';
         }
       else
         {
           keyname = _rl_get_keyname (key);
           if (prefix)
         {
           out = (char *)xmalloc (strlen (keyname) + prefix_len + 1);
           strcpy (out, prefix);
           strcpy (out + prefix_len, keyname);
           xfree (keyname);
           keyname = out;
         }
         }
       _rl_macro_dumper_internal (print_readably, FUNCTION_TO_KEYMAP (map, key), keyname);
       xfree (keyname);
       break;
     }
     }
 }
References _rl_get_keyname(), _rl_untranslate_macro_value(), ESC, fprintf(), FUNCTION_TO_KEYMAP, ISFUNC, ISKMAP, ISMACR, KEYMAP_SIZE, map, out(), prefix(), rl_outstream, strcpy, strlen(), type, xfree, and xmalloc.
Referenced by rl_macro_dumper().
_rl_read_file()
static char * _rl_read_file (char * filename, size_t * sizep) static
Definition at line 974 of file bind.c.
 {
   struct stat finfo;
   size_t file_size;
   char *buffer;
   int i, file;
   file = -1;
   if (((file = open (filename, O_RDONLY, 0666)) < 0) || (fstat (file, &finfo) < 0))
     {
       if (file >= 0)
     close (file);
       return ((char *)NULL);
     }
   file_size = (size_t)finfo.st_size;
   /* check for overflow on very large files */
   if (file_size != finfo.st_size || file_size + 1 < file_size)
     {
       if (file >= 0)
     close (file);
 #if defined (EFBIG)
       errno = EFBIG;
 #endif
       return ((char *)NULL);
     }
   /* Read the file into BUFFER. */
   buffer = (char *)xmalloc (file_size + 1);
   i = read (file, buffer, file_size);
   close (file);
   if (i < 0)
     {
       xfree (buffer);
       return ((char *)NULL);
     }
   RL_CHECK_SIGNALS ();
   buffer[i] = '\0';
   if (sizep)
     *sizep = i;
   return (buffer);
 }
References buffer, close(), EFBIG, errno, file_size, filename, fstat(), i, if(), NULL, O_RDONLY, open(), read(), RL_CHECK_SIGNALS, stat::st_size, xfree, and xmalloc.
Referenced by _rl_read_init_file().
_rl_read_init_file()
static int _rl_read_init_file (const char * filename, int include_level) static
Definition at line 1066 of file bind.c.
 {
   register int i;
   char *buffer, *openname, *line, *end;
   size_t file_size;
   current_readline_init_file = filename;
   current_readline_init_include_level = include_level;
   openname = tilde_expand (filename);
   buffer = _rl_read_file (openname, &file_size);
   xfree (openname);
   RL_CHECK_SIGNALS ();
   if (buffer == 0)
     return (errno);
   if (include_level == 0 && filename != last_readline_init_file)
     {
       FREE (last_readline_init_file);
       last_readline_init_file = savestring (filename);
     }
   currently_reading_init_file = 1;
   /* Loop over the lines in the file.  Lines that start with `#' are
      comments; all other lines are commands for readline initialization. */
   current_readline_init_lineno = 1;
   line = buffer;
   end = buffer + file_size;
   while (line < end)
     {
       /* Find the end of this line. */
       for (i = 0; line + i != end && line[i] != '\n'; i++);
 #if defined (__CYGWIN__)
       /* ``Be liberal in what you accept.'' */
       if (line[i] == '\n' && line[i-1] == '\r')
     line[i - 1] = '\0';
 #endif
       /* Mark end of line. */
       line[i] = '\0';
       /* Skip leading whitespace. */
       while (*line && whitespace (*line))
         {
       line++;
       i--;
         }
       /* If the line is not a comment, then parse it. */
       if (*line && *line != '#')
     rl_parse_and_bind (line);
       /* Move to the next line. */
       line += i + 1;
       current_readline_init_lineno++;
     }
   xfree (buffer);
   currently_reading_init_file = 0;
   return (0);
 }
References _rl_read_file(), buffer, current_readline_init_file, current_readline_init_include_level, current_readline_init_lineno, currently_reading_init_file, end, errno, file_size, filename, FREE, i, last_readline_init_file, line, RL_CHECK_SIGNALS, rl_parse_and_bind(), savestring(), tilde_expand(), whitespace, and xfree.
Referenced by parser_include(), and rl_read_init_file().
_rl_skip_to_delim()
static int _rl_skip_to_delim (char * string, int start, int delim) static
Definition at line 1577 of file bind.c.
 {
   int i, c, passc;
   for (i = start,passc = 0; c = string[i]; i++)
     {
       if (passc)
     {
       passc = 0;
       if (c == 0)
         break;
       continue;
     }
       if (c == '\\')
     {
       passc = 1;
       continue;
     }
       if (c == delim)
     break;
     }
   return i;
 }
References c, i, and start.
Referenced by rl_parse_and_bind().
_rl_untranslate_macro_value()
char* _rl_untranslate_macro_value (char * seq, int use_escapes)
Definition at line 735 of file bind.c.
 {
   char *ret, *r, *s;
   int c;
   r = ret = (char *)xmalloc (7 * strlen (seq) + 1);
   for (s = seq; *s; s++)
     {
       c = *s;
       if (META_CHAR (c))
     {
       *r++ = '\\';
       *r++ = 'M';
       *r++ = '-';
       c = UNMETA (c);
     }
       else if (c == ESC)
     {
       *r++ = '\\';
       c = 'e';
     }
       else if (CTRL_CHAR (c))
     {
       *r++ = '\\';
       if (use_escapes && _rl_isescape (c))
         c = _rl_escchar (c);
       else
         {
           *r++ = 'C';
           *r++ = '-';
           c = _rl_to_lower (UNCTRL (c));
         }
     }
       else if (c == RUBOUT)
     {
       *r++ = '\\';
       *r++ = 'C';
       *r++ = '-';
       c = '?';
     }
       if (c == ESC)
     {
       *r++ = '\\';
       c = 'e';
     }
       else if (c == '\\' || c == '"')
     *r++ = '\\';
       *r++ = (unsigned char)c;
     }
   *r = '\0';
   return ret;
 }
References _rl_escchar(), _rl_isescape(), _rl_to_lower(), c, CTRL_CHAR, ESC, META_CHAR, RUBOUT, s, seq, strlen(), UNCTRL, UNMETA, and xmalloc.
Referenced by _rl_get_string_variable_value(), _rl_macro_dumper_internal(), and rl_print_last_kbd_macro().
bool_to_int()
static int bool_to_int (const char * value) static
Definition at line 2046 of file bind.c.
 {
   return (value == 0 || *value == '\0' ||
         (_rl_stricmp (value, "on") == 0) ||
         (value[0] == '1' && value[1] == '\0'));
 }
References _rl_stricmp(), and value.
Referenced by rl_variable_bind().
boolean_varname()
static const char * boolean_varname (int i) static
Definition at line 1942 of file bind.c.
 {
   return ((i >= 0) ? boolean_varlist[i].name : (char *)NULL);
 }
References boolean_varlist, i, and NULL.
Referenced by parser_if().
find_boolean_var()
static int find_boolean_var (const char * name) static
Definition at line 1931 of file bind.c.
 {
   register int i;
   for (i = 0; boolean_varlist[i].name; i++)
     if (_rl_stricmp (name, boolean_varlist[i].name) == 0)
       return i;
   return -1;
 }
References _rl_stricmp(), boolean_varlist, and i.
Referenced by parser_if(), rl_parse_and_bind(), rl_variable_bind(), and rl_variable_value().
find_string_var()
static int find_string_var (const char * name) static
Definition at line 2026 of file bind.c.
 {
   register int i;
   for (i = 0; string_varlist[i].name; i++)
     if (_rl_stricmp (name, string_varlist[i].name) == 0)
       return i;
   return -1;
 }
References _rl_stricmp(), i, and string_varlist.
Referenced by parser_if(), rl_parse_and_bind(), rl_variable_bind(), and rl_variable_value().
glean_key_from_name()
static int glean_key_from_name (char * name) static
Definition at line 2400 of file bind.c.
 {
   register int i;
   for (i = 0; name_key_alist[i].name; i++)
     if (_rl_stricmp (name, name_key_alist[i].name) == 0)
       return (name_key_alist[i].value);
   return (*(unsigned char *)name);  /* XXX was return (*name) */
 }
Referenced by rl_parse_and_bind().
hack_special_boolean_var()
static void hack_special_boolean_var (int i) static
Definition at line 1951 of file bind.c.
 {
   const char *name;
   name = boolean_varlist[i].name;
   if (_rl_stricmp (name, "blink-matching-paren") == 0)
     _rl_enable_paren_matching (rl_blink_matching_paren);
   else if (_rl_stricmp (name, "prefer-visible-bell") == 0)
     {
       if (_rl_prefer_visible_bell)
     _rl_bell_preference = VISIBLE_BELL;
       else
     _rl_bell_preference = AUDIBLE_BELL;
     }
   else if (_rl_stricmp (name, "show-mode-in-prompt") == 0)
     _rl_reset_prompt ();
   else if (_rl_stricmp (name, "enable-bracketed-paste") == 0)
     _rl_enable_active_region = _rl_enable_bracketed_paste;
 }
References _rl_bell_preference, _rl_enable_active_region, _rl_enable_bracketed_paste, _rl_enable_paren_matching(), _rl_prefer_visible_bell, _rl_reset_prompt(), _rl_stricmp(), AUDIBLE_BELL, boolean_varlist, i, rl_blink_matching_paren, and VISIBLE_BELL.
Referenced by rl_variable_bind().
handle_parser_directive()
static int handle_parser_directive (char * statement) static
Definition at line 1540 of file bind.c.
 {
   register int i;
   char *directive, *args;
   /* Isolate the actual directive. */
   /* Skip whitespace. */
   for (i = 0; whitespace (statement[i]); i++);
   directive = &statement[i];
   for (; statement[i] && !whitespace (statement[i]); i++);
   if (statement[i])
     statement[i++] = '\0';
   for (; statement[i] && whitespace (statement[i]); i++);
   args = &statement[i];
   /* Lookup the command, and act on it. */
   for (i = 0; parser_directives[i].name; i++)
     if (_rl_stricmp (directive, parser_directives[i].name) == 0)
       {
     (*parser_directives[i].function) (args);
     return (0);
       }
   /* display an error message about the unknown parser directive */
   _rl_init_file_error ("%s: unknown parser directive", directive);
   return (1);
 }
References _rl_init_file_error(), _rl_stricmp(), args, i, parser_directives, and whitespace.
Referenced by rl_parse_and_bind().
parse_comparison_op()
static int parse_comparison_op (char * s, int * indp) const static
Definition at line 1170 of file bind.c.
 {
   int i, peekc, op;
   if (OPSTART (s[*indp]) == 0)
     return -1;
   i = *indp;
   peekc = s[i] ? s[i+1] : 0;
   op = -1;
   if (s[i] == '=')
     {
       op = OP_EQ;
       if (peekc == '=')
         i++;
       i++;
     }
   else if (s[i] == '!' && peekc == '=')
     {
       op = OP_NE;
       i += 2;
     }
   else if (s[i] == '<' && peekc == '=')
     {
       op = OP_LE;
       i += 2;
     }
   else if (s[i] == '>' && peekc == '=')
     {
       op = OP_GE;
       i += 2;
     }
   else if (s[i] == '<')
     {
       op = OP_LT;
       i += 1;
     }
   else if (s[i] == '>')
     {
       op = OP_GT;
       i += 1;
     }
   *indp = i;
   return op;
 }
References i, OP_EQ, OP_GE, OP_GT, OP_LE, OP_LT, OP_NE, OPSTART, and s.
Referenced by parser_if().
parser_else()
static int parser_else (char * args) static
Definition at line 1460 of file bind.c.
 {
   register int i;
   if (if_stack_depth == 0)
     {
       _rl_init_file_error ("$else found without matching $if");
       return 0;
     }
 #if 0
   /* Check the previous (n - 1) levels of the stack to make sure that
      we haven't previously turned off parsing. */
   for (i = 0; i < if_stack_depth - 1; i++)
 #else
   /* Check the previous (n) levels of the stack to make sure that
      we haven't previously turned off parsing. */
   for (i = 0; i < if_stack_depth; i++)
 #endif
     if (if_stack[i] == 1)
       return 0;
   /* Invert the state of parsing if at top level. */
   _rl_parsing_conditionalized_out = !_rl_parsing_conditionalized_out;
   return 0;
 }
References _rl_init_file_error(), _rl_parsing_conditionalized_out, i, if_stack, and if_stack_depth.
parser_endif()
static int parser_endif (char * args) static
Definition at line 1490 of file bind.c.
 {
   if (if_stack_depth)
     _rl_parsing_conditionalized_out = if_stack[--if_stack_depth];
   else
     _rl_init_file_error ("$endif without matching $if");
   return 0;
 }
References _rl_init_file_error(), _rl_parsing_conditionalized_out, if_stack, and if_stack_depth.
parser_if()
static int parser_if (char * args) static
Definition at line 1255 of file bind.c.
 {
   int i, llen, boolvar, strvar;
   boolvar = strvar = -1;
   /* Push parser state. */
   if (if_stack_depth + 1 >= if_stack_size)
     {
       if (!if_stack)
     if_stack = (unsigned char *)xmalloc (if_stack_size = 20);
       else
     if_stack = (unsigned char *)xrealloc (if_stack, if_stack_size += 20);
     }
   if_stack[if_stack_depth++] = _rl_parsing_conditionalized_out;
   /* If parsing is turned off, then nothing can turn it back on except
      for finding the matching endif.  In that case, return right now. */
   if (_rl_parsing_conditionalized_out)
     return 0;
   llen = strlen (args);
   /* Isolate first argument. */
   for (i = 0; args[i] && !whitespace (args[i]); i++);
   if (args[i])
     args[i++] = '\0';
   /* Handle "$if term=foo" and "$if mode=emacs" constructs.  If this
      isn't term=foo, or mode=emacs, then check to see if the first
      word in ARGS is the same as the value stored in rl_readline_name. */
   if (rl_terminal_name && _rl_strnicmp (args, "term=", 5) == 0)
     {
       char *tem, *tname;
       /* Terminals like "aaa-60" are equivalent to "aaa". */
       tname = savestring (rl_terminal_name);
       tem = strchr (tname, '-');
       if (tem)
     *tem = '\0';
       /* Test the `long' and `short' forms of the terminal name so that
      if someone has a `sun-cmd' and does not want to have bindings
      that will be executed if the terminal is a `sun', they can put
      `$if term=sun-cmd' into their .inputrc. */
       _rl_parsing_conditionalized_out = _rl_stricmp (args + 5, tname) &&
                     _rl_stricmp (args + 5, rl_terminal_name);
       xfree (tname);
     }
 #if defined (VI_MODE)
   else if (_rl_strnicmp (args, "mode=", 5) == 0)
     {
       int mode;
       if (_rl_stricmp (args + 5, "emacs") == 0)
     mode = emacs_mode;
       else if (_rl_stricmp (args + 5, "vi") == 0)
     mode = vi_mode;
       else
     mode = no_mode;
       _rl_parsing_conditionalized_out = mode != rl_editing_mode;
     }
 #endif /* VI_MODE */
   else if (_rl_strnicmp (args, "version", 7) == 0)
     {
       int rlversion, versionarg, op, previ, major, minor, opresult;
       _rl_parsing_conditionalized_out = 1;
       rlversion = RL_VERSION_MAJOR*10 + RL_VERSION_MINOR;
       /* if "version" is separated from the operator by whitespace, or the
          operand is separated from the operator by whitespace, restore it.
          We're more liberal with allowed whitespace for this variable. */
       if (i > 0 && i <= llen && args[i-1] == '\0')
         args[i-1] = ' ';
       args[llen] = '\0';        /* just in case */
       for (i = 7; whitespace (args[i]); i++)
     ;
       if (OPSTART(args[i]) == 0)
     {
       _rl_init_file_error ("comparison operator expected, found `%s'", args[i] ? args + i : "end-of-line");
       return 0;
     }
       previ = i;
       op = parse_comparison_op (args, &i);
       if (op <= 0)
     {
       _rl_init_file_error ("comparison operator expected, found `%s'", args+previ);
       return 0;
     }
       for ( ; args[i] && whitespace (args[i]); i++)
     ;
       if (args[i] == 0 || _rl_digit_p (args[i]) == 0)
     {
       _rl_init_file_error ("numeric argument expected, found `%s'", args+i);
       return 0;
     }
       major = minor = 0;
       previ = i;
       for ( ; args[i] && _rl_digit_p (args[i]); i++)
     major = major*10 + _rl_digit_value (args[i]);
       if (args[i] == '.')
     {
       if (args[i + 1] && _rl_digit_p (args [i + 1]) == 0)
         {
           _rl_init_file_error ("numeric argument expected, found `%s'", args+previ);
           return 0;
         }
       for (++i; args[i] && _rl_digit_p (args[i]); i++)
         minor = minor*10 + _rl_digit_value (args[i]);
     }
       /* optional - check for trailing garbage on the line, allow whitespace
      and a trailing comment */
       previ = i;
       for ( ; args[i] && whitespace (args[i]); i++)
     ;
       if (args[i] && args[i] != '#')
     {
       _rl_init_file_error ("trailing garbage on line: `%s'", args+previ);
       return 0;
     }
       versionarg = major*10 + minor;
       switch (op)
     {
     case OP_EQ:
       opresult = rlversion == versionarg;
       break;
     case OP_NE:
       opresult = rlversion != versionarg;
       break;
     case OP_GT:
       opresult = rlversion > versionarg;
       break;
     case OP_GE:
       opresult = rlversion >= versionarg;
       break;
     case OP_LT:
       opresult = rlversion < versionarg;
       break;
     case OP_LE:
       opresult = rlversion <= versionarg;
       break;
     }
       _rl_parsing_conditionalized_out = 1 - opresult;
     }
   /* Check to see if the first word in ARGS is the same as the
      value stored in rl_readline_name. */
   else if (_rl_stricmp (args, rl_readline_name) == 0)
     _rl_parsing_conditionalized_out = 0;
   else if ((boolvar = find_boolean_var (args)) >= 0 || (strvar = find_string_var (args)) >= 0)
     {
       int op, previ;
       size_t vlen;
       const char *vname;
       char *valuearg, *vval, prevc;
       _rl_parsing_conditionalized_out = 1;
       vname = (boolvar >= 0) ? boolean_varname (boolvar) : string_varname (strvar);
       vlen = strlen (vname);
       if (i > 0 && i <= llen && args[i-1] == '\0')
         args[i-1] = ' ';
       args[llen] = '\0';        /* just in case */
       for (i = vlen; whitespace (args[i]); i++)
     ;
       if (CMPSTART(args[i]) == 0)
     {
       _rl_init_file_error ("equality comparison operator expected, found `%s'", args[i] ? args + i : "end-of-line");
       return 0;
     }
       previ = i;
       op = parse_comparison_op (args, &i);
       if (op != OP_EQ && op != OP_NE)
     {
       _rl_init_file_error ("equality comparison operator expected, found `%s'", args+previ);
       return 0;
     }
       for ( ; args[i] && whitespace (args[i]); i++)
     ;
       if (args[i] == 0)
     {
       _rl_init_file_error ("argument expected, found `%s'", args+i);
       return 0;
     }
       previ = i;
       valuearg = args + i;
       for ( ; args[i] && whitespace (args[i]) == 0; i++)
     ;
       prevc = args[i];
       args[i] = '\0';       /* null-terminate valuearg */
       vval = rl_variable_value (vname);
       if (op == OP_EQ)
         _rl_parsing_conditionalized_out = _rl_stricmp (vval, valuearg) != 0;
       else if (op == OP_NE)
         _rl_parsing_conditionalized_out = _rl_stricmp (vval, valuearg) == 0;
       args[i] = prevc;
     }
   else
     _rl_parsing_conditionalized_out = 1;
   return 0;
 }
References _rl_digit_p(), _rl_digit_value(), _rl_init_file_error(), _rl_parsing_conditionalized_out, _rl_stricmp(), _rl_strnicmp(), boolean_varname(), CMPSTART, emacs_mode, find_boolean_var(), find_string_var(), i, if_stack, if_stack_depth, if_stack_size, major, minor, no_mode, OP_EQ, OP_GE, OP_GT, OP_LE, OP_LT, OP_NE, OPSTART, parse_comparison_op(), rl_editing_mode, rl_readline_name, rl_terminal_name, rl_variable_value(), RL_VERSION_MAJOR, RL_VERSION_MINOR, savestring(), strchr(), string_varname(), strlen(), vi_mode, whitespace, xfree, xmalloc, and xrealloc.
parser_include()
static int parser_include (char * args) static
Definition at line 1500 of file bind.c.
 {
   const char *old_init_file;
   char *e;
   int old_line_number, old_include_level, r;
   if (_rl_parsing_conditionalized_out)
     return (0);
   old_init_file = current_readline_init_file;
   old_line_number = current_readline_init_lineno;
   old_include_level = current_readline_init_include_level;
   e = strchr (args, '\n');
   if (e)
     *e = '\0';
   r = _rl_read_init_file ((const char *)args, old_include_level + 1);
   current_readline_init_file = old_init_file;
   current_readline_init_lineno = old_line_number;
   current_readline_init_include_level = old_include_level;
   return r;
 }
References _rl_parsing_conditionalized_out, _rl_read_init_file(), current_readline_init_file, current_readline_init_include_level, current_readline_init_lineno, and strchr().
rl_add_defun()
int rl_add_defun (const char * name, rl_command_func_t * function, int key)
Definition at line 126 of file bind.c.
 {
   if (key != -1)
     rl_bind_key (key, function);
   rl_add_funmap_entry (name, function);
   return 0;
 }
References rl_add_funmap_entry(), and rl_bind_key().
Referenced by main().
rl_bind_key()
int rl_bind_key (int key, rl_command_func_t * function)
Definition at line 136 of file bind.c.
 {
   char keyseq[4];
   int l;
   if (key < 0 || key > largest_char)
     return (key);
   /* Want to make this a multi-character key sequence with an ESC prefix */
   if (META_CHAR (key) && _rl_convert_meta_chars_to_ascii)
     {
       if (_rl_keymap[ESC].type == ISKMAP)
     {
       Keymap escmap;
       escmap = FUNCTION_TO_KEYMAP (_rl_keymap, ESC);
       key = UNMETA (key);
       escmap[key].type = ISFUNC;
       escmap[key].function = function;
       return (0);
     }
       /* Otherwise, let's just let rl_generic_bind handle the key sequence.
      We start it off with ESC here and let the code below add the rest
      of the sequence. */
       keyseq[0] = ESC;
       l = 1;
       key = UNMETA(key);
       goto bind_keyseq;
     }
   /* If it's bound to a function or macro, just overwrite.  Otherwise we have
      to treat it as a key sequence so rl_generic_bind handles shadow keymaps
      for us.  If we are binding '\' or \C-@ (NUL) make sure to escape it so
      it makes it through the call to rl_translate_keyseq. */
   if (_rl_keymap[key].type != ISKMAP)
     {
       if (_rl_keymap[key].type == ISMACR)
     xfree ((char *)_rl_keymap[key].function);
       _rl_keymap[key].type = ISFUNC;
       _rl_keymap[key].function = function;
     }
   else
     {
       l = 0;
 bind_keyseq:
       if (key == '\\')
     {
       keyseq[l++] = '\\';
       keyseq[l++] = '\\';
     }
       else if (key == '\0')
     {
       keyseq[l++] = '\\';
       keyseq[l++] = '0';
     }
       else
     keyseq[l++] = key;
       keyseq[l] = '\0';
       rl_bind_keyseq (keyseq, function);
     }
   rl_binding_keymap = _rl_keymap;
   return (0);
 }
References _rl_convert_meta_chars_to_ascii, _rl_keymap, ESC, _keymap_entry::function, FUNCTION_TO_KEYMAP, ISFUNC, ISKMAP, ISMACR, l, largest_char, META_CHAR, rl_bind_keyseq(), rl_binding_keymap, type, _keymap_entry::type, UNMETA, and xfree.
Referenced by prepare_terminal_settings(), rl_add_defun(), rl_bind_key_in_map(), rl_parse_and_bind(), and rl_unbind_key().
rl_bind_key_if_unbound()
int rl_bind_key_if_unbound (int key, rl_command_func_t * default_func)
Definition at line 228 of file bind.c.
 {
   char *keyseq;
   keyseq = rl_untranslate_keyseq ((unsigned char)key);
   return (rl_bind_keyseq_if_unbound_in_map (keyseq, default_func, _rl_keymap));
 }
References _rl_keymap, rl_bind_keyseq_if_unbound_in_map(), and rl_untranslate_keyseq().
rl_bind_key_if_unbound_in_map()
int rl_bind_key_if_unbound_in_map (int key, rl_command_func_t * default_func, Keymap kmap)
Definition at line 219 of file bind.c.
 {
   char *keyseq;
   keyseq = rl_untranslate_keyseq ((unsigned char)key);
   return (rl_bind_keyseq_if_unbound_in_map (keyseq, default_func, kmap));
 }
References rl_bind_keyseq_if_unbound_in_map(), and rl_untranslate_keyseq().
rl_bind_key_in_map()
int rl_bind_key_in_map (int key, rl_command_func_t * function, Keymap map)
Definition at line 204 of file bind.c.
 {
   int result;
   Keymap oldmap;
   oldmap = _rl_keymap;
   _rl_keymap = map;
   result = rl_bind_key (key, function);
   _rl_keymap = oldmap;
   return (result);
 }
References _rl_keymap, map, and rl_bind_key().
Referenced by _rl_enable_paren_matching(), and rl_unbind_key_in_map().
rl_bind_keyseq()
int rl_bind_keyseq (const char * keyseq, rl_command_func_t * function)
Definition at line 292 of file bind.c.
 {
   return (rl_generic_bind (ISFUNC, keyseq, (char *)function, _rl_keymap));
 }
References _rl_keymap, ISFUNC, and rl_generic_bind().
Referenced by rl_bind_key(), and rl_parse_and_bind().
rl_bind_keyseq_if_unbound()
int rl_bind_keyseq_if_unbound (const char * keyseq, rl_command_func_t * default_func)
Definition at line 348 of file bind.c.
 {
   return (rl_bind_keyseq_if_unbound_in_map (keyseq, default_func, _rl_keymap));
 }
References _rl_keymap, and rl_bind_keyseq_if_unbound_in_map().
Referenced by bind_arrow_keys_internal(), bind_bracketed_paste_prefix(), bind_termcap_arrow_keys(), and rl_vi_replace().
rl_bind_keyseq_if_unbound_in_map()
int rl_bind_keyseq_if_unbound_in_map (const char * keyseq, rl_command_func_t * default_func, Keymap kmap)
Definition at line 317 of file bind.c.
 {
   rl_command_func_t *func;
   char *keys;
   int keys_len;
   if (keyseq)
     {
       /* Handle key sequences that require translations and `raw' ones that
      don't. This might be a problem with backslashes. */
       keys = (char *)xmalloc (1 + (2 * strlen (keyseq)));
       if (rl_translate_keyseq (keyseq, keys, &keys_len))
     {
       xfree (keys);
       return -1;
     }
       func = rl_function_of_keyseq_len (keys, keys_len, kmap, (int *)NULL);
       xfree (keys);
 #if defined (VI_MODE)
       if (!func || func == rl_do_lowercase_version || func == rl_vi_movement_mode)
 #else
       if (!func || func == rl_do_lowercase_version)
 #endif
     return (rl_bind_keyseq_in_map (keyseq, default_func, kmap));
       else
     return 1;
     }
   return 0;
 }
References keys, NULL, rl_bind_keyseq_in_map(), rl_do_lowercase_version(), rl_function_of_keyseq_len(), rl_translate_keyseq(), rl_vi_movement_mode(), strlen(), xfree, and xmalloc.
Referenced by rl_bind_key_if_unbound(), rl_bind_key_if_unbound_in_map(), and rl_bind_keyseq_if_unbound().
rl_bind_keyseq_in_map()
int rl_bind_keyseq_in_map (const char * keyseq, rl_command_func_t * function, Keymap map)
Definition at line 301 of file bind.c.
 {
   return (rl_generic_bind (ISFUNC, keyseq, (char *)function, map));
 }
References ISFUNC, map, and rl_generic_bind().
Referenced by bind_arrow_keys(), and rl_bind_keyseq_if_unbound_in_map().
rl_dump_functions()
int rl_dump_functions (int count, int key)
Definition at line 2866 of file bind.c.
 {
   if (rl_dispatching)
     fprintf (rl_outstream, "\r\n");
   rl_function_dumper (rl_explicit_arg);
   rl_on_new_line ();
   return (0);
 }
References fprintf(), rl_dispatching, rl_explicit_arg, rl_function_dumper(), rl_on_new_line(), and rl_outstream.
rl_dump_macros()
int rl_dump_macros (int count, int key)
Definition at line 2941 of file bind.c.
 {
   if (rl_dispatching)
     fprintf (rl_outstream, "\r\n");
   rl_macro_dumper (rl_explicit_arg);
   rl_on_new_line ();
   return (0);
 }
References fprintf(), rl_dispatching, rl_explicit_arg, rl_macro_dumper(), rl_on_new_line(), and rl_outstream.
rl_dump_variables()
int rl_dump_variables (int count, int key)
Definition at line 3062 of file bind.c.
 {
   if (rl_dispatching)
     fprintf (rl_outstream, "\r\n");
   rl_variable_dumper (rl_explicit_arg);
   rl_on_new_line ();
   return (0);
 }
References fprintf(), rl_dispatching, rl_explicit_arg, rl_on_new_line(), rl_outstream, and rl_variable_dumper().
rl_function_dumper()
void rl_function_dumper (int print_readably)
Definition at line 2795 of file bind.c.
 {
   register int i;
   const char **names;
   const char *name;
   names = rl_funmap_names ();
   fprintf (rl_outstream, "\n");
   for (i = 0; name = names[i]; i++)
     {
       rl_command_func_t *function;
       char **invokers;
       function = rl_named_function (name);
       invokers = rl_invoking_keyseqs_in_map (function, _rl_keymap);
       if (print_readably)
     {
       if (!invokers)
         fprintf (rl_outstream, "# %s (not bound)\n", name);
       else
         {
           register int j;
           for (j = 0; invokers[j]; j++)
         {
           fprintf (rl_outstream, "\"%s\": %s\n",
                invokers[j], name);
           xfree (invokers[j]);
         }
           xfree (invokers);
         }
     }
       else
     {
       if (!invokers)
         fprintf (rl_outstream, "%s is not bound to any keys\n",
              name);
       else
         {
           register int j;
           fprintf (rl_outstream, "%s can be found on ", name);
           for (j = 0; invokers[j] && j < 5; j++)
         {
           fprintf (rl_outstream, "\"%s\"%s", invokers[j],
                invokers[j + 1] ? ", " : ".\n");
         }
           if (j == 5 && invokers[j])
         fprintf (rl_outstream, "...\n");
           for (j = 0; invokers[j]; j++)
         xfree (invokers[j]);
           xfree (invokers);
         }
     }
     }
   xfree (names);
 }
References _rl_keymap, fprintf(), i, j, name_and_keymap::name, names, rl_funmap_names(), rl_invoking_keyseqs_in_map(), rl_named_function(), rl_outstream, and xfree.
Referenced by rl_dump_functions().
rl_function_of_keyseq()
rl_command_func_t* rl_function_of_keyseq (const char * keyseq, Keymap map, int * type)
Definition at line 872 of file bind.c.
 {
   return _rl_function_of_keyseq_internal (keyseq, strlen (keyseq), map, type);
 }
References _rl_function_of_keyseq_internal(), map, strlen(), and type.
Referenced by _rl_isearch_dispatch().
rl_function_of_keyseq_len()
rl_command_func_t* rl_function_of_keyseq_len (const char * keyseq, size_t len, Keymap map, int * type)
Definition at line 878 of file bind.c.
 {
   return _rl_function_of_keyseq_internal (keyseq, len, map, type);
 }
References _rl_function_of_keyseq_internal(), len, map, and type.
Referenced by rl_bind_keyseq_if_unbound_in_map().
rl_generic_bind()
int rl_generic_bind (int type, const char * keyseq, char * data, Keymap map)
Definition at line 379 of file bind.c.
 {
   char *keys;
   int keys_len, prevkey, ic;
   register int i;
   KEYMAP_ENTRY k;
   Keymap prevmap;
   k.function = 0;
   /* If no keys to bind to, exit right away. */
   if (keyseq == 0 || *keyseq == 0)
     {
       if (type == ISMACR)
     xfree (data);
       return -1;
     }
   keys = (char *)xmalloc (1 + (2 * strlen (keyseq)));
   /* Translate the ASCII representation of KEYSEQ into an array of
      characters.  Stuff the characters into KEYS, and the length of
      KEYS into KEYS_LEN. */
   if (rl_translate_keyseq (keyseq, keys, &keys_len))
     {
       xfree (keys);
       return -1;
     }
   prevmap = map;
   prevkey = keys[0];
   /* Bind keys, making new keymaps as necessary. */
   for (i = 0; i < keys_len; i++)
     {
       unsigned char uc = keys[i];
       if (i > 0)
     prevkey = ic;
       ic = uc;
       if (ic < 0 || ic >= KEYMAP_SIZE)
         {
           xfree (keys);
       return -1;
         }
       /* We now rely on rl_translate_keyseq to do this conversion, so this
      check is superfluous. */
 #if 0
       if (META_CHAR (ic) && _rl_convert_meta_chars_to_ascii)
     {
       ic = UNMETA (ic);
       if (map[ESC].type == ISKMAP)
         {
           prevmap = map;
           map = FUNCTION_TO_KEYMAP (map, ESC);
         }
     }
 #endif
       if ((i + 1) < keys_len)
     {
       if (map[ic].type != ISKMAP)
         {
           /* We allow subsequences of keys.  If a keymap is being
          created that will `shadow' an existing function or macro
          key binding, we save that keybinding into the ANYOTHERKEY
          index in the new map.  The dispatch code will look there
          to find the function to execute if the subsequence is not
          matched.  ANYOTHERKEY was chosen to be greater than
          UCHAR_MAX. */
           k = map[ic];
           map[ic].type = ISKMAP;
           map[ic].function = KEYMAP_TO_FUNCTION (rl_make_bare_keymap());
         }
       prevmap = map;
       map = FUNCTION_TO_KEYMAP (map, ic);
       /* The dispatch code will return this function if no matching
          key sequence is found in the keymap.  This (with a little
          help from the dispatch code in readline.c) allows `a' to be
          mapped to something, `abc' to be mapped to something else,
          and the function bound  to `a' to be executed when the user
          types `abx', leaving `bx' in the input queue. */
       if (k.function && ((k.type == ISFUNC && k.function != rl_do_lowercase_version) || k.type == ISMACR))
         {
           map[ANYOTHERKEY] = k;
           k.function = 0;
         }
     }
       else
     {
       if (map[ic].type == ISKMAP)
         {
           prevmap = map;
           map = FUNCTION_TO_KEYMAP (map, ic);
           ic = ANYOTHERKEY;
           /* If we're trying to override a keymap with a null function
          (e.g., trying to unbind it), we can't use a null pointer
          here because that's indistinguishable from having not been
          overridden.  We use a special bindable function that does
          nothing. */
           if (type == ISFUNC && data == 0)
         data = (char *)_rl_null_function;
         }
       if (map[ic].type == ISMACR)
         xfree ((char *)map[ic].function);
       map[ic].function = KEYMAP_TO_FUNCTION (data);
       map[ic].type = type;
     }
       rl_binding_keymap = map;
     }
   /* If we unbound a key (type == ISFUNC, data == 0), and the prev keymap
      points to the keymap where we unbound the key (sanity check), and the
      current binding keymap is empty (rl_empty_keymap() returns non-zero),
      and the binding keymap has ANYOTHERKEY set with type == ISFUNC
      (overridden function), delete the now-empty keymap, take the previously-
      overridden function and remove the override. */
   /* Right now, this only works one level back. */
   if (type == ISFUNC && data == 0 &&
       prevmap[prevkey].type == ISKMAP &&
       (FUNCTION_TO_KEYMAP(prevmap, prevkey) == rl_binding_keymap) &&
       rl_binding_keymap[ANYOTHERKEY].type == ISFUNC &&
       rl_empty_keymap (rl_binding_keymap))
     {
       prevmap[prevkey].type = rl_binding_keymap[ANYOTHERKEY].type;
       prevmap[prevkey].function = rl_binding_keymap[ANYOTHERKEY].function;
       rl_discard_keymap (rl_binding_keymap);
       rl_binding_keymap = prevmap;
     }
   xfree (keys);
   return 0;
 }
References _rl_convert_meta_chars_to_ascii, _rl_null_function(), ANYOTHERKEY, ESC, _keymap_entry::function, FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, ISMACR, k, KEYMAP_SIZE, KEYMAP_TO_FUNCTION, keys, map, META_CHAR, rl_binding_keymap, rl_discard_keymap(), rl_do_lowercase_version(), rl_empty_keymap(), rl_make_bare_keymap(), rl_translate_keyseq(), strlen(), type, _keymap_entry::type, UNMETA, xfree, and xmalloc.
Referenced by rl_bind_keyseq(), rl_bind_keyseq_in_map(), rl_macro_bind(), rl_parse_and_bind(), and rl_set_key().
rl_get_keymap()
Keymap rl_get_keymap (void)
Definition at line 2534 of file bind.c.
 {
   return (_rl_keymap);
 }
References _rl_keymap.
rl_get_keymap_by_name()
Keymap rl_get_keymap_by_name (const char * name)
Definition at line 2448 of file bind.c.
 {
   int i;
   i = _rl_get_keymap_by_name (name);
   return ((i >= 0) ? keymap_names[i].map : (Keymap) NULL);
 }
References _rl_get_keymap_by_name(), i, keymap_names, map, name_and_keymap::name, and NULL.
Referenced by sv_keymap().
rl_get_keymap_name()
char* rl_get_keymap_name (Keymap map)
Definition at line 2468 of file bind.c.
 {
   int i;
   i = _rl_get_keymap_by_map (map);
   return ((i >= 0) ? keymap_names[i].name : (char *)NULL);
 }
References _rl_get_keymap_by_map(), i, keymap_names, map, name_and_keymap::name, and NULL.
Referenced by _rl_get_string_variable_value().
rl_get_keymap_name_from_edit_mode()
char* rl_get_keymap_name_from_edit_mode (void)
Definition at line 2551 of file bind.c.
 {
   if (rl_editing_mode == emacs_mode)
     return "emacs";
 #if defined (VI_MODE)
   else if (rl_editing_mode == vi_mode)
     return "vi";
 #endif /* VI_MODE */
   else
     return "none";
 }
References emacs_mode, rl_editing_mode, and vi_mode.
Referenced by _rl_get_string_variable_value().
rl_invoking_keyseqs()
char** rl_invoking_keyseqs (rl_command_func_t * function)
Definition at line 2786 of file bind.c.
 {
   return (rl_invoking_keyseqs_in_map (function, _rl_keymap));
 }
References _rl_keymap, and rl_invoking_keyseqs_in_map().
rl_invoking_keyseqs_in_map()
char** rl_invoking_keyseqs_in_map (rl_command_func_t * function, Keymap map)
Definition at line 2677 of file bind.c.
 {
   register int key;
   char **result;
   int result_index, result_size;
   result = (char **)NULL;
   result_index = result_size = 0;
   for (key = 0; key < KEYMAP_SIZE; key++)
     {
       switch (map[key].type)
     {
     case ISMACR:
       /* Macros match, if, and only if, the pointers are identical.
          Thus, they are treated exactly like functions in here. */
     case ISFUNC:
       /* If the function in the keymap is the one we are looking for,
          then add the current KEY to the list of invoking keys. */
       if (map[key].function == function)
         {
           char *keyname;
           keyname = _rl_get_keyname (key);
           if (result_index + 2 > result_size)
             {
               result_size += 10;
           result = (char **)xrealloc (result, result_size * sizeof (char *));
             }
           result[result_index++] = keyname;
           result[result_index] = (char *)NULL;
         }
       break;
     case ISKMAP:
       {
         char **seqs;
         register int i;
         /* Find the list of keyseqs in this map which have FUNCTION as
            their target.  Add the key sequences found to RESULT. */
         if (map[key].function)
           seqs =
             rl_invoking_keyseqs_in_map (function, FUNCTION_TO_KEYMAP (map, key));
         else
           break;
         if (seqs == 0)
           break;
         for (i = 0; seqs[i]; i++)
           {
         char *keyname = (char *)xmalloc (6 + strlen (seqs[i]));
         if (key == ESC)
           {
             /* If ESC is the meta prefix and we're converting chars
                with the eighth bit set to ESC-prefixed sequences, then
                we can use \M-.  Otherwise we need to use the sequence
                for ESC. */
             if (_rl_convert_meta_chars_to_ascii && map[ESC].type == ISKMAP)
               sprintf (keyname, "\\M-");
             else
               sprintf (keyname, "\\e");
           }
         else
           {
             int c = key, l = 0;
             if (CTRL_CHAR (c) || c == RUBOUT)
               {
             keyname[l++] = '\\';
             keyname[l++] = 'C';
             keyname[l++] = '-';
             c = (c == RUBOUT) ? '?' : _rl_to_lower (UNCTRL (c));
               }
             if (c == '\\' || c == '"')
               keyname[l++] = '\\';
             keyname[l++] = (char) c;
             keyname[l++] = '\0';
           }
         strcat (keyname, seqs[i]);
         xfree (seqs[i]);
         if (result_index + 2 > result_size)
           {
             result_size += 10;
             result = (char **)xrealloc (result, result_size * sizeof (char *));
           }
         result[result_index++] = keyname;
         result[result_index] = (char *)NULL;
           }
         xfree (seqs);
       }
       break;
     }
     }
   return (result);
 }
References _rl_convert_meta_chars_to_ascii, _rl_get_keyname(), _rl_to_lower(), c, CTRL_CHAR, ESC, FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, ISMACR, KEYMAP_SIZE, l, map, NULL, RUBOUT, sprintf(), strcat, strlen(), type, UNCTRL, xfree, xmalloc, and xrealloc.
Referenced by rl_function_dumper(), and rl_invoking_keyseqs().
rl_list_funmap_names()
void rl_list_funmap_names (void)
Definition at line 2576 of file bind.c.
 {
   register int i;
   const char **funmap_names;
   funmap_names = rl_funmap_names ();
   if (!funmap_names)
     return;
   for (i = 0; funmap_names[i]; i++)
     fprintf (rl_outstream, "%s\n", funmap_names[i]);
   xfree (funmap_names);
 }
References fprintf(), i, rl_funmap_names(), rl_outstream, and xfree.
rl_macro_bind()
int rl_macro_bind (const char * keyseq, const char * macro, Keymap map)
Definition at line 357 of file bind.c.
 {
   char *macro_keys;
   int macro_keys_len;
   macro_keys = (char *)xmalloc ((2 * strlen (macro)) + 1);
   if (rl_translate_keyseq (macro, macro_keys, &macro_keys_len))
     {
       xfree (macro_keys);
       return -1;
     }
   rl_generic_bind (ISMACR, keyseq, macro_keys, map);
   return 0;
 }
References ISMACR, map, rl_generic_bind(), rl_translate_keyseq(), strlen(), xfree, and xmalloc.
Referenced by rl_parse_and_bind().
rl_macro_dumper()
void rl_macro_dumper (int print_readably)
Definition at line 2935 of file bind.c.
 {
   _rl_macro_dumper_internal (print_readably, _rl_keymap, (char *)NULL);
 }
References _rl_keymap, _rl_macro_dumper_internal(), and NULL.
Referenced by rl_dump_macros().
rl_named_function()
rl_command_func_t* rl_named_function (const char * string)
Definition at line 794 of file bind.c.
 {
   register int i;
   rl_initialize_funmap ();
   for (i = 0; funmap[i]; i++)
     if (_rl_stricmp (funmap[i]->name, string) == 0)
       return (funmap[i]->function);
   return ((rl_command_func_t *)NULL);
 }
References _rl_stricmp(), funmap, i, NULL, and rl_initialize_funmap().
Referenced by rl_function_dumper(), rl_parse_and_bind(), and rl_unbind_command_in_map().
rl_parse_and_bind()
int rl_parse_and_bind (char * string)
Definition at line 1609 of file bind.c.
 {
   char *funname, *kname;
   register int c, i;
   int key, equivalency, foundmod, foundsep;
   while (string && whitespace (*string))
     string++;
   if (string == 0 || *string == 0 || *string == '#')
     return 0;
   /* If this is a parser directive, act on it. */
   if (*string == '$')
     {
       handle_parser_directive (&string[1]);
       return 0;
     }
   /* If we aren't supposed to be parsing right now, then we're done. */
   if (_rl_parsing_conditionalized_out)
     return 0;
   i = 0;
   /* If this keyname is a complex key expression surrounded by quotes,
      advance to after the matching close quote.  This code allows the
      backslash to quote characters in the key expression. */
   if (*string == '"')
     {
       i = _rl_skip_to_delim (string, 1, '"');
       /* If we didn't find a closing quote, abort the line. */
       if (string[i] == '\0')
         {
           _rl_init_file_error ("%s: no closing `\"' in key binding", string);
           return 1;
         }
       else
         i++;    /* skip past closing double quote */
     }
   /* Advance to the colon (:) or whitespace which separates the two objects. */
   for (; (c = string[i]) && c != ':' && c != ' ' && c != '\t'; i++ );
   if (i == 0)
     {
       _rl_init_file_error ("`%s': invalid key binding: missing key sequence", string);
       return 1;
     }
   equivalency = (c == ':' && string[i + 1] == '=');
   foundsep = c != 0;
   /* Mark the end of the command (or keyname). */
   if (string[i])
     string[i++] = '\0';
   /* If doing assignment, skip the '=' sign as well. */
   if (equivalency)
     string[i++] = '\0';
   /* If this is a command to set a variable, then do that. */
   if (_rl_stricmp (string, "set") == 0)
     {
       char *var, *value, *e;
       int s;
       var = string + i;
       /* Make VAR point to start of variable name. */
       while (*var && whitespace (*var)) var++;
       /* Make VALUE point to start of value string. */
       value = var;
       while (*value && whitespace (*value) == 0) value++;
       if (*value)
     *value++ = '\0';
       while (*value && whitespace (*value)) value++;
       /* Strip trailing whitespace from values of boolean variables. */
       if (find_boolean_var (var) >= 0)
     {
       /* just read a whitespace-delimited word or empty string */
       for (e = value; *e && whitespace (*e) == 0; e++)
         ;
       if (e > value)
         *e = '\0';      /* cut off everything trailing */
     }
       else if ((i = find_string_var (var)) >= 0)
     {
       /* Allow quoted strings in variable values */
       if (*value == '"')
         {
           i = _rl_skip_to_delim (value, 1, *value);
           value[i] = '\0';
           value++;  /* skip past the quote */
         }
       else
         {
           /* remove trailing whitespace */
           e = value + strlen (value) - 1;
           while (e >= value && whitespace (*e))
         e--;
           e++;      /* skip back to whitespace or EOS */
           if (*e && e >= value)
         *e = '\0';
         }
     }
       else
     {
       /* avoid calling rl_variable_bind just to find this out */
       _rl_init_file_error ("%s: unknown variable name", var);
       return 1;
     }
       rl_variable_bind (var, value);
       return 0;
     }
   /* Skip any whitespace between keyname and funname. */
   for (; string[i] && whitespace (string[i]); i++);
   funname = &string[i];
   /* Now isolate funname.
      For straight function names just look for whitespace, since
      that will signify the end of the string.  But this could be a
      macro definition.  In that case, the string is quoted, so skip
      to the matching delimiter.  We allow the backslash to quote the
      delimiter characters in the macro body. */
   /* This code exists to allow whitespace in macro expansions, which
      would otherwise be gobbled up by the next `for' loop.*/
   /* XXX - it may be desirable to allow backslash quoting only if " is
      the quoted string delimiter, like the shell. */
   if (*funname == '\'' || *funname == '"')
     {
       i = _rl_skip_to_delim (string, i+1, *funname);
       if (string[i])
     i++;
       else
     {
       _rl_init_file_error ("`%s': missing closing quote for macro", funname);
       return 1;
     }
     }
   /* Advance to the end of the string.  */
   for (; string[i] && whitespace (string[i]) == 0; i++);
   /* No extra whitespace at the end of the string. */
   string[i] = '\0';
   /* Handle equivalency bindings here.  Make the left-hand side be exactly
      whatever the right-hand evaluates to, including keymaps. */
   if (equivalency)
     {
       return 0;
     }
   if (foundsep == 0)
     {
       _rl_init_file_error ("%s: no key sequence terminator", string);
       return 1;
     }
   /* If this is a new-style key-binding, then do the binding with
      rl_bind_keyseq ().  Otherwise, let the older code deal with it. */
   if (*string == '"')
     {
       char *seq;
       register int j, k, passc;
       seq = (char *)xmalloc (1 + strlen (string));
       for (j = 1, k = passc = 0; string[j]; j++)
     {
       /* Allow backslash to quote characters, but leave them in place.
          This allows a string to end with a backslash quoting another
          backslash, or with a backslash quoting a double quote.  The
          backslashes are left in place for rl_translate_keyseq (). */
       if (passc || (string[j] == '\\'))
         {
           seq[k++] = string[j];
           passc = !passc;
           continue;
         }
       if (string[j] == '"')
         break;
       seq[k++] = string[j];
     }
       seq[k] = '\0';
       /* Binding macro? */
       if (*funname == '\'' || *funname == '"')
     {
       j = strlen (funname);
       /* Remove the delimiting quotes from each end of FUNNAME. */
       if (j && funname[j - 1] == *funname)
         funname[j - 1] = '\0';
       rl_macro_bind (seq, &funname[1], _rl_keymap);
     }
       else
     rl_bind_keyseq (seq, rl_named_function (funname));
       xfree (seq);
       return 0;
     }
   /* Get the actual character we want to deal with. */
   kname = strrchr (string, '-');
   if (kname == 0)
     kname = string;
   else
     kname++;
   key = glean_key_from_name (kname);
   /* Add in control and meta bits. */
   foundmod = 0;
   if (substring_member_of_array (string, _rl_possible_control_prefixes))
     {
       key = CTRL (_rl_to_upper (key));
       foundmod = 1;
     }
   if (substring_member_of_array (string, _rl_possible_meta_prefixes))
     {
       key = META (key);
       foundmod = 1;
     }
   if (foundmod == 0 && kname != string)
     {
       _rl_init_file_error ("%s: unknown key modifier", string);
       return 1;
     }
   /* Temporary.  Handle old-style keyname with macro-binding. */
   if (*funname == '\'' || *funname == '"')
     {
       char useq[2];
       int fl = strlen (funname);
       useq[0] = key; useq[1] = '\0';
       if (fl && funname[fl - 1] == *funname)
     funname[fl - 1] = '\0';
       rl_macro_bind (useq, &funname[1], _rl_keymap);
     }
 #if defined (PREFIX_META_HACK)
   /* Ugly, but working hack to keep prefix-meta around. */
   else if (_rl_stricmp (funname, "prefix-meta") == 0)
     {
       char seq[2];
       seq[0] = key;
       seq[1] = '\0';
       rl_generic_bind (ISKMAP, seq, (char *)emacs_meta_keymap, _rl_keymap);
     }
 #endif /* PREFIX_META_HACK */
   else
     rl_bind_key (key, rl_named_function (funname));
   return 0;
 }
References _rl_init_file_error(), _rl_keymap, _rl_parsing_conditionalized_out, _rl_possible_control_prefixes, _rl_possible_meta_prefixes, _rl_skip_to_delim(), _rl_stricmp(), _rl_to_upper(), c, CTRL, emacs_meta_keymap, find_boolean_var(), find_string_var(), glean_key_from_name(), handle_parser_directive(), i, ISKMAP, j, k, META, rl_bind_key(), rl_bind_keyseq(), rl_generic_bind(), rl_macro_bind(), rl_named_function(), rl_variable_bind(), s, seq, string, strlen(), strrchr(), substring_member_of_array(), value, whitespace, xfree, and xmalloc.
Referenced by _rl_read_init_file().
rl_re_read_init_file()
int rl_re_read_init_file (int count, int ignore)
Definition at line 1024 of file bind.c.
 {
   int r;
   r = rl_read_init_file ((const char *)NULL);
   rl_set_keymap_from_edit_mode ();
   return r;
 }
References NULL, rl_read_init_file(), and rl_set_keymap_from_edit_mode().
rl_read_init_file()
int rl_read_init_file (const char * filename)
Definition at line 1041 of file bind.c.
 {
   /* Default the filename. */
   if (filename == 0)
     filename = last_readline_init_file;
   if (filename == 0)
     filename = sh_get_env_value ("INPUTRC");
   if (filename == 0 || *filename == 0)
     {
       filename = DEFAULT_INPUTRC;
       /* Try to read DEFAULT_INPUTRC; fall back to SYS_INPUTRC on failure */
       if (_rl_read_init_file (filename, 0) == 0)
     return 0;
       filename = SYS_INPUTRC;
     }
 #if defined (__MSDOS__)
   if (_rl_read_init_file (filename, 0) == 0)
     return 0;
   filename = "~/_inputrc";
 #endif
   return (_rl_read_init_file (filename, 0));
 }
References _rl_read_init_file(), DEFAULT_INPUTRC, filename, last_readline_init_file, sh_get_env_value(), and SYS_INPUTRC.
Referenced by readline_initialize_everything(), and rl_re_read_init_file().
rl_set_key()
int rl_set_key (const char * keyseq, rl_command_func_t * function, Keymap map)
Definition at line 308 of file bind.c.
 {
   return (rl_generic_bind (ISFUNC, keyseq, (char *)function, map));
 }
References ISFUNC, map, and rl_generic_bind().
rl_set_keymap()
void rl_set_keymap (Keymap map)
Definition at line 2527 of file bind.c.
 {
   if (map)
     _rl_keymap = map;
 }
References _rl_keymap, and map.
Referenced by sv_keymap().
rl_set_keymap_from_edit_mode()
void rl_set_keymap_from_edit_mode (void)
Definition at line 2540 of file bind.c.
 {
   if (rl_editing_mode == emacs_mode)
     _rl_keymap = emacs_standard_keymap;
 #if defined (VI_MODE)
   else if (rl_editing_mode == vi_mode)
     _rl_keymap = vi_insertion_keymap;
 #endif /* VI_MODE */
 }
References _rl_keymap, emacs_mode, emacs_standard_keymap, rl_editing_mode, vi_insertion_keymap, and vi_mode.
Referenced by readline_initialize_everything(), and rl_re_read_init_file().
rl_set_keymap_name()
int rl_set_keymap_name (const char * name, Keymap map)
Definition at line 2477 of file bind.c.
 {
   int i, ni, mi;
   /* First check whether or not we're trying to rename a builtin keymap */
   mi = _rl_get_keymap_by_map (map);
   if (mi >= 0 && mi < NUM_BUILTIN_KEYMAPS)
     return -1;
   /* Then reject attempts to set one of the builtin names to a new map */
   ni = _rl_get_keymap_by_name (name);
   if (ni >= 0 && ni < NUM_BUILTIN_KEYMAPS)
     return -1;
   /* Renaming a keymap we already added */
   if (mi >= 0)  /* XXX - could be >= NUM_BUILTIN_KEYMAPS */
     {
       xfree (keymap_names[mi].name);
       keymap_names[mi].name = savestring (name);
       return mi;
     }
   /* Associating new keymap with existing name */
   if (ni >= 0)
     {
       keymap_names[ni].map = map;
       return ni;
     }
   for (i = 0; keymap_names[i].name; i++)
     ;
   if (keymap_names == builtin_keymap_names)
     {
       keymap_names = xmalloc ((i + 2) * sizeof (struct name_and_keymap));
       memcpy (keymap_names, builtin_keymap_names, i * sizeof (struct name_and_keymap));
     }
   else
     keymap_names = xrealloc (keymap_names, (i + 2) * sizeof (struct name_and_keymap));
   keymap_names[i].name = savestring (name);
   keymap_names[i].map = map;
   keymap_names[i+1].name = NULL;
   keymap_names[i+1].map = NULL;
   return i;
 }
References _rl_get_keymap_by_map(), _rl_get_keymap_by_name(), builtin_keymap_names, i, keymap_names, name_and_keymap::map, map, memcpy, name_and_keymap::name, NULL, NUM_BUILTIN_KEYMAPS, savestring(), xfree, xmalloc, and xrealloc.
rl_translate_keyseq()
int rl_translate_keyseq (const char * seq, char * array, int * len)
Definition at line 523 of file bind.c.
 {
   register int i, l, temp;
   int has_control, has_meta;
   unsigned char c;
   has_control = 0;
   has_meta = 0;
   /* When there are incomplete prefixes \C- or \M- (has_control || has_meta)
      without base character at the end of SEQ, they are processed as the
      prefixes for '\0'.
   */
   for (i = l = 0; (c = seq[i]) || has_control || has_meta; i++)
     {
       /* Only backslashes followed by a non-null character are handled
      specially.  Trailing backslash (backslash followed by '\0') is
      processed as a normal character.
       */
       if (c == '\\' && seq[i + 1] != '\0')
     {
       c = seq[++i];
       /* Handle \C- and \M- prefixes. */
       if (c == 'C' && seq[i + 1] == '-')
         {
           i++;
           has_control = 1;
           continue;
         }
       else if (c == 'M' && seq[i + 1] == '-')
         {
           i++;
           has_meta = 1;
           continue;
         }
       /* Translate other backslash-escaped characters.  These are the
          same escape sequences that bash's `echo' and `printf' builtins
          handle, with the addition of \d -> RUBOUT.  A backslash
          preceding a character that is not special is stripped. */
       switch (c)
         {
         case 'a':
           c = '\007';
           break;
         case 'b':
           c = '\b';
           break;
         case 'd':
           c = RUBOUT;   /* readline-specific */
           break;
         case 'e':
           c = ESC;
           break;
         case 'f':
           c = '\f';
           break;
         case 'n':
           c = NEWLINE;
           break;
         case 'r':
           c = RETURN;
           break;
         case 't':
           c = TAB;
           break;
         case 'v':
           c = 0x0B;
           break;
         case '\\':
           c = '\\';
           break;
         case '0': case '1': case '2': case '3':
         case '4': case '5': case '6': case '7':
           i++;
           for (temp = 2, c -= '0'; ISOCTAL ((unsigned char)seq[i]) && temp--; i++)
             c = (c * 8) + OCTVALUE (seq[i]);
           i--;  /* auto-increment in for loop */
           c &= largest_char;
           break;
         case 'x':
           i++;
           for (temp = 2, c = 0; ISXDIGIT ((unsigned char)seq[i]) && temp--; i++)
             c = (c * 16) + HEXVALUE (seq[i]);
           if (temp == 2)
             c = 'x';
           i--;  /* auto-increment in for loop */
           c &= largest_char;
           break;
         default:    /* backslashes before non-special chars just add the char */
           c &= largest_char;
           break;    /* the backslash is stripped */
         }
     }
       /* Process \C- and \M- flags */
       if (has_control)
     {
       /* Special treatment for C-? */
       c = (c == '?') ? RUBOUT : CTRL (_rl_to_upper (c));
       has_control = 0;
     }
       if (has_meta)
     {
       c = META (c);
       has_meta = 0;
     }
       /* If convert-meta is turned on, convert a meta char to a key sequence  */
       if (META_CHAR (c) && _rl_convert_meta_chars_to_ascii)
     {
       array[l++] = ESC; /* ESC is meta-prefix */
       array[l++] = UNMETA (c);
     }
       else
     array[l++] = (c);
       /* Null characters may be processed for incomplete prefixes at the end of
      sequence */
       if (seq[i] == '\0')
     break;
     }
   *len = l;
   array[l] = '\0';
   return (0);
 }
References _rl_convert_meta_chars_to_ascii, _rl_to_upper(), c, CTRL, ESC, HEXVALUE, i, ISOCTAL, ISXDIGIT, l, largest_char, len, META, META_CHAR, NEWLINE, OCTVALUE, RETURN, RUBOUT, seq, TAB, and UNMETA.
Referenced by _rl_reset_region_color(), rl_bind_keyseq_if_unbound_in_map(), rl_generic_bind(), rl_macro_bind(), sv_emacs_modestr(), sv_isrchterm(), sv_vicmd_modestr(), and sv_viins_modestr().
rl_trim_arg_from_keyseq()
int rl_trim_arg_from_keyseq (const char * keyseq, size_t len, Keymap map)
Definition at line 889 of file bind.c.
 {
   register int i, j, parsing_digits;
   unsigned char ic;
   Keymap map0;
   if (map == 0)
     map = _rl_keymap;
   map0 = map;
   /* The digits following the initial one (e.g., the binding to digit-argument)
     or the optional `-' in a binding to digit-argument or universal-argument
     are not added to rl_executing_keyseq. This is basically everything read by
     rl_digit_loop. The parsing_digits logic is here in case they ever are. */
   for (i = j = parsing_digits = 0; keyseq && i < len; i++)
     {
       ic = keyseq[i];
       if (parsing_digits)
     {
       if (_rl_digit_p (ic))
         {
           j = i + 1;
           continue;
         }
       parsing_digits = 0;
     }
       if (map[ic].type == ISKMAP)
     {
       if (i + 1 == len)
         return -1;
       map = FUNCTION_TO_KEYMAP (map, ic);
       continue;
     }
       if (map[ic].type == ISFUNC)
     {
 #if defined (VI_MODE)
       if (map[ic].function != rl_digit_argument && map[ic].function != rl_universal_argument && map[ic].function != rl_vi_arg_digit)
 #else
       if (map[ic].function != rl_digit_argument && map[ic].function != rl_universal_argument)
 #endif
         return (j);
       /* We don't bother with a keyseq that is only a numeric argument */
       if (i + 1 == len)
         return -1;
       parsing_digits = 1;
       /* This logic should be identical to rl_digit_loop */
       /* We accept M-- as equivalent to M--1, C-u- as equivalent to C-u-1
          but set parsing_digits to 2 to note that we saw `-' */
       if (map[ic].function == rl_universal_argument && (i + 1 == '-'))
         {
           i++;
           parsing_digits = 2;
         }
       if (map[ic].function == rl_digit_argument && ic == '-')
         {
           parsing_digits = 2;
         }
       map = map0;
       j = i + 1;
     }
     }
   /* If we're still parsing digits by the time we get here, we don't allow a
      key sequence that consists solely of a numeric argument */
   return -1;
 }
References _rl_digit_p(), _rl_keymap, FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, j, len, map, rl_digit_argument(), rl_universal_argument(), rl_vi_arg_digit(), and type.
rl_unbind_command_in_map()
int rl_unbind_command_in_map (const char * command, Keymap map)
Definition at line 278 of file bind.c.
 {
   rl_command_func_t *func;
   func = rl_named_function (command);
   if (func == 0)
     return 0;
   return (rl_unbind_function_in_map (func, map));
 }
References map, rl_named_function(), and rl_unbind_function_in_map().
rl_unbind_function_in_map()
int rl_unbind_function_in_map (rl_command_func_t * func, Keymap map)
Definition at line 254 of file bind.c.
 {
   register int i, rval;
   for (i = rval = 0; i < KEYMAP_SIZE; i++)
     {
       if (map[i].type == ISFUNC && map[i].function == func)
     {
       map[i].function = (rl_command_func_t *)NULL;
       rval = 1;
     }
       else if (map[i].type == ISKMAP)       /* TAG:readline-8.1 */
     {
       int r;
       r = rl_unbind_function_in_map (func, FUNCTION_TO_KEYMAP (map, i));
       if (r == 1)
         rval = 1;
     }
     }
   return rval;
 }
References FUNCTION_TO_KEYMAP, i, ISFUNC, ISKMAP, KEYMAP_SIZE, map, NULL, and type.
Referenced by rl_unbind_command_in_map().
rl_unbind_key()
int rl_unbind_key (int key)
Definition at line 240 of file bind.c.
 {
   return (rl_bind_key (key, (rl_command_func_t *)NULL));
 }
References NULL, and rl_bind_key().
rl_unbind_key_in_map()
int rl_unbind_key_in_map (int key, Keymap map)
Definition at line 247 of file bind.c.
 {
   return (rl_bind_key_in_map (key, (rl_command_func_t *)NULL, map));
 }
References map, NULL, and rl_bind_key_in_map().
rl_untranslate_keyseq()
char* rl_untranslate_keyseq (int seq)
Definition at line 685 of file bind.c.
 {
   static char kseq[16];
   int i, c;
   i = 0;
   c = seq;
   if (META_CHAR (c))
     {
       kseq[i++] = '\\';
       kseq[i++] = 'M';
       kseq[i++] = '-';
       c = UNMETA (c);
     }
   else if (c == ESC)
     {
       kseq[i++] = '\\';
       c = 'e';
     }
   else if (CTRL_CHAR (c))
     {
       kseq[i++] = '\\';
       kseq[i++] = 'C';
       kseq[i++] = '-';
       c = _rl_to_lower (UNCTRL (c));
     }
   else if (c == RUBOUT)
     {
       kseq[i++] = '\\';
       kseq[i++] = 'C';
       kseq[i++] = '-';
       c = '?';
     }
   if (c == ESC)
     {
       kseq[i++] = '\\';
       c = 'e';
     }
   else if (c == '\\' || c == '"')
     {
       kseq[i++] = '\\';
     }
   kseq[i++] = (unsigned char) c;
   kseq[i] = '\0';
   return kseq;
 }
References _rl_to_lower(), c, CTRL_CHAR, ESC, i, META_CHAR, RUBOUT, seq, UNCTRL, and UNMETA.
Referenced by fcopy(), rl_bind_key_if_unbound(), and rl_bind_key_if_unbound_in_map().
rl_variable_bind()
int rl_variable_bind (const char * name, const char * value)
Definition at line 2072 of file bind.c.
 {
   register int i;
   int   v;
   /* Check for simple variables first. */
   i = find_boolean_var (name);
   if (i >= 0)
     {
       *boolean_varlist[i].value = bool_to_int (value);
       if (boolean_varlist[i].flags & V_SPECIAL)
     hack_special_boolean_var (i);
       return 0;
     }
   i = find_string_var (name);
   /* For the time being, string names without a handler function are simply
      ignored. */
   if (i < 0 || string_varlist[i].set_func == 0)
     {
       if (i < 0)
     _rl_init_file_error ("%s: unknown variable name", name);
       return 0;
     }
   v = (*string_varlist[i].set_func) (value);
   if (v != 0)
     _rl_init_file_error ("%s: could not set value to `%s'", name, value);
   return v;
 }
References _rl_init_file_error(), bool_to_int(), boolean_varlist, find_boolean_var(), find_string_var(), flags, hack_special_boolean_var(), i, string_varlist, V_SPECIAL, and value.
Referenced by main(), and rl_parse_and_bind().
rl_variable_dumper()
void rl_variable_dumper (int print_readably)
Definition at line 3031 of file bind.c.
 {
   int i;
   char *v;
   for (i = 0; boolean_varlist[i].name; i++)
     {
       if (print_readably)
         fprintf (rl_outstream, "set %s %s\n", boolean_varlist[i].name,
                    *boolean_varlist[i].value ? "on" : "off");
       else
         fprintf (rl_outstream, "%s is set to `%s'\n", boolean_varlist[i].name,
                    *boolean_varlist[i].value ? "on" : "off");
     }
   for (i = 0; string_varlist[i].name; i++)
     {
       v = _rl_get_string_variable_value (string_varlist[i].name);
       if (v == 0)   /* _rl_isearch_terminators can be NULL */
     continue;
       if (print_readably)
         fprintf (rl_outstream, "set %s %s\n", string_varlist[i].name, v);
       else
         fprintf (rl_outstream, "%s is set to `%s'\n", string_varlist[i].name, v);
     }
 }
References _rl_get_string_variable_value(), boolean_varlist, fprintf(), i, name_and_keymap::name, rl_outstream, string_varlist, and value.
Referenced by rl_dump_variables().
rl_variable_value()
char* rl_variable_value (const char * name)
Definition at line 2054 of file bind.c.
 {
   register int i;
   /* Check for simple variables first. */
   i = find_boolean_var (name);
   if (i >= 0)
     return (*boolean_varlist[i].value ? "on" : "off");
   i = find_string_var (name);
   if (i >= 0)
     return (_rl_get_string_variable_value (string_varlist[i].name));
   /* Unknown variable names return NULL. */
   return (char *)NULL;
 }
References _rl_get_string_variable_value(), boolean_varlist, find_boolean_var(), find_string_var(), i, NULL, string_varlist, and value.
Referenced by parser_if().
strchr()
char* strchr ()
Referenced by parser_if(), and parser_include().
string_varname()
static const char * string_varname (int i) static
Definition at line 2037 of file bind.c.
 {
   return ((i >= 0) ? string_varlist[i].name : (char *)NULL);
 }
References i, NULL, and string_varlist.
Referenced by parser_if().
strrchr()
char * strrchr ()
Referenced by rl_parse_and_bind().
substring_member_of_array()
static int substring_member_of_array (const char * string, const char *const * array) static
Definition at line 3073 of file bind.c.
 {
   while (*array)
     {
       if (_rl_strindex (string, *array))
     return (1);
       array++;
     }
   return (0);
 }
References _rl_strindex().
Referenced by rl_parse_and_bind().
sv_bell_style()
static int sv_bell_style (const char * value) static
Definition at line 2240 of file bind.c.
 {
   if (value == 0 || *value == '\0')
     _rl_bell_preference = AUDIBLE_BELL;
   else if (_rl_stricmp (value, "none") == 0 || _rl_stricmp (value, "off") == 0)
     _rl_bell_preference = NO_BELL;
   else if (_rl_stricmp (value, "audible") == 0 || _rl_stricmp (value, "on") == 0)
     _rl_bell_preference = AUDIBLE_BELL;
   else if (_rl_stricmp (value, "visible") == 0)
     _rl_bell_preference = VISIBLE_BELL;
   else
     return 1;
   return 0;
 }
References _rl_bell_preference, _rl_stricmp(), AUDIBLE_BELL, NO_BELL, value, and VISIBLE_BELL.
sv_combegin()
static int sv_combegin (const char * value) static
Definition at line 2125 of file bind.c.
 {
   if (value && *value)
     {
       FREE (_rl_comment_begin);
       _rl_comment_begin = savestring (value);
       return 0;
     }
   return 1;
 }
References _rl_comment_begin, FREE, savestring(), and value.
sv_compquery()
static int sv_compquery (const char * value) static
Definition at line 2152 of file bind.c.
 {
   int nval = 100;
   if (value && *value)
     {
       nval = atoi (value);
       if (nval < 0)
     nval = 0;
     }
   rl_completion_query_items = nval;
   return 0;
 }
References atoi(), rl_completion_query_items, and value.
sv_compwidth()
static int sv_compwidth (const char * value) static
Definition at line 2167 of file bind.c.
 {
   int nval = -1;
   if (value && *value)
     nval = atoi (value);
   _rl_completion_columns = nval;
   return 0;
 }
References _rl_completion_columns, atoi(), and value.
sv_dispprefix()
static int sv_dispprefix (const char * value) static
Definition at line 2137 of file bind.c.
 {
   int nval = 0;
   if (value && *value)
     {
       nval = atoi (value);
       if (nval < 0)
     nval = 0;
     }
   _rl_completion_prefix_display_length = nval;
   return 0;
 }
References _rl_completion_prefix_display_length, atoi(), and value.
sv_editmode()
static int sv_editmode (const char * value) static
Definition at line 2105 of file bind.c.
 {
   if (_rl_strnicmp (value, "vi", 2) == 0)
     {
 #if defined (VI_MODE)
       _rl_keymap = vi_insertion_keymap;
       rl_editing_mode = vi_mode;
 #endif /* VI_MODE */
       return 0;
     }
   else if (_rl_strnicmp (value, "emacs", 5) == 0)
     {
       _rl_keymap = emacs_standard_keymap;
       rl_editing_mode = emacs_mode;
       return 0;
     }
   return 1;
 }
References _rl_keymap, _rl_strnicmp(), emacs_mode, emacs_standard_keymap, rl_editing_mode, value, vi_insertion_keymap, and vi_mode.
sv_emacs_modestr()
static int sv_emacs_modestr (const char * value) static
Definition at line 2293 of file bind.c.
 {
   if (value && *value)
     {
       FREE (_rl_emacs_mode_str);
       _rl_emacs_mode_str = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_emacs_mode_str, &_rl_emacs_modestr_len);
       _rl_emacs_mode_str[_rl_emacs_modestr_len] = '\0';
       return 0;
     }
   else if (value)
     {
       FREE (_rl_emacs_mode_str);
       _rl_emacs_mode_str = (char *)xmalloc (1);
       _rl_emacs_mode_str[_rl_emacs_modestr_len = 0] = '\0';
       return 0;
     }
   else if (value == 0)
     {
       FREE (_rl_emacs_mode_str);
       _rl_emacs_mode_str = 0;   /* prompt_modestr does the right thing */
       _rl_emacs_modestr_len = 0;
       return 0;
     }
   return 1;
 }
References _rl_emacs_mode_str, _rl_emacs_modestr_len, FREE, rl_translate_keyseq(), strlen(), value, and xmalloc.
sv_histsize()
static int sv_histsize (const char * value) static
Definition at line 2179 of file bind.c.
 {
   int nval;
   nval = 500;
   if (value && *value)
     {
       nval = atoi (value);
       if (nval < 0)
     {
       unstifle_history ();
       return 0;
     }
     }
   stifle_history (nval);
   return 0;
 }
References atoi(), stifle_history(), unstifle_history(), and value.
sv_isrchterm()
static int sv_isrchterm (const char * value) static
Definition at line 2256 of file bind.c.
 {
   int beg, end, delim;
   char *v;
   if (value == 0)
     return 1;
   /* Isolate the value and translate it into a character string. */
   v = savestring (value);
   FREE (_rl_isearch_terminators);
   if (v[0] == '"' || v[0] == '\'')
     {
       delim = v[0];
       for (beg = end = 1; v[end] && v[end] != delim; end++)
     ;
     }
   else
     {
       for (beg = end = 0; v[end] && whitespace (v[end]) == 0; end++)
     ;
     }
   v[end] = '\0';
   /* The value starts at v + beg.  Translate it into a character string. */
   _rl_isearch_terminators = (char *)xmalloc (2 * strlen (v) + 1);
   rl_translate_keyseq (v + beg, _rl_isearch_terminators, &end);
   _rl_isearch_terminators[end] = '\0';
   xfree (v);
   return 0;
 }
References _rl_isearch_terminators, end, FREE, rl_translate_keyseq(), savestring(), strlen(), value, whitespace, xfree, and xmalloc.
sv_keymap()
static int sv_keymap (const char * value) static
Definition at line 2198 of file bind.c.
 {
   Keymap kmap;
   kmap = rl_get_keymap_by_name (value);
   if (kmap)
     {
       rl_set_keymap (kmap);
       return 0;
     }
   return 1;
 }
References rl_get_keymap_by_name(), rl_set_keymap(), and value.
sv_region_end_color()
static int sv_region_end_color (const char * value) static
Definition at line 2234 of file bind.c.
 {
   return (_rl_reset_region_color (1, value));
 }
References _rl_reset_region_color(), and value.
sv_region_start_color()
static int sv_region_start_color (const char * value) static
Definition at line 2228 of file bind.c.
 {
   return (_rl_reset_region_color (0, value));
 }
References _rl_reset_region_color(), and value.
sv_seqtimeout()
static int sv_seqtimeout (const char * value) static
Definition at line 2212 of file bind.c.
 {
   int nval;
   nval = 0;
   if (value && *value)
     {
       nval = atoi (value);
       if (nval < 0)
     nval = 0;
     }
   _rl_keyseq_timeout = nval;
   return 0;
 }
References _rl_keyseq_timeout, atoi(), and value.
sv_vicmd_modestr()
static int sv_vicmd_modestr (const char * value) static
Definition at line 2349 of file bind.c.
 {
   if (value && *value)
     {
       FREE (_rl_vi_cmd_mode_str);
       _rl_vi_cmd_mode_str = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_vi_cmd_mode_str, &_rl_vi_cmd_modestr_len);
       _rl_vi_cmd_mode_str[_rl_vi_cmd_modestr_len] = '\0';
       return 0;
     }
   else if (value)
     {
       FREE (_rl_vi_cmd_mode_str);
       _rl_vi_cmd_mode_str = (char *)xmalloc (1);
       _rl_vi_cmd_mode_str[_rl_vi_cmd_modestr_len = 0] = '\0';
       return 0;
     }
   else if (value == 0)
     {
       FREE (_rl_vi_cmd_mode_str);
       _rl_vi_cmd_mode_str = 0;  /* prompt_modestr does the right thing */
       _rl_vi_cmd_modestr_len = 0;
       return 0;
     }
   return 1;
 }
References _rl_vi_cmd_mode_str, _rl_vi_cmd_modestr_len, FREE, rl_translate_keyseq(), strlen(), value, and xmalloc.
sv_viins_modestr()
static int sv_viins_modestr (const char * value) static
Definition at line 2321 of file bind.c.
 {
   if (value && *value)
     {
       FREE (_rl_vi_ins_mode_str);
       _rl_vi_ins_mode_str = (char *)xmalloc (2 * strlen (value) + 1);
       rl_translate_keyseq (value, _rl_vi_ins_mode_str, &_rl_vi_ins_modestr_len);
       _rl_vi_ins_mode_str[_rl_vi_ins_modestr_len] = '\0';
       return 0;
     }
   else if (value)
     {
       FREE (_rl_vi_ins_mode_str);
       _rl_vi_ins_mode_str = (char *)xmalloc (1);
       _rl_vi_ins_mode_str[_rl_vi_ins_modestr_len = 0] = '\0';
       return 0;
     }
   else if (value == 0)
     {
       FREE (_rl_vi_ins_mode_str);
       _rl_vi_ins_mode_str = 0;  /* prompt_modestr does the right thing */
       _rl_vi_ins_modestr_len = 0;
       return 0;
     }
   return 1;
 }
References _rl_vi_ins_mode_str, _rl_vi_ins_modestr_len, FREE, rl_translate_keyseq(), strlen(), value, and xmalloc.
Variable Documentation
_rl_emacs_mode_str
char* _rl_emacs_mode_str extern
Definition at line 180 of file display.c.
Referenced by _rl_get_string_variable_value(), and sv_emacs_modestr().
_rl_possible_control_prefixes
const char* const _rl_possible_control_prefixes[]
Initial value:
= {
  "Control-", "C-", "CTRL-", (const char *)NULL
}
Definition at line 1228 of file bind.c.
Referenced by rl_parse_and_bind().
_rl_possible_meta_prefixes
const char* const _rl_possible_meta_prefixes[]
Initial value:
= {
  "Meta", "M-", (const char *)NULL
}
Definition at line 1232 of file bind.c.
Referenced by rl_parse_and_bind().
_rl_prefer_visible_bell
int _rl_prefer_visible_bell = 1 static
Definition at line 104 of file bind.c.
Referenced by hack_special_boolean_var().
const { ... } boolean_varlist[]
Referenced by boolean_varname(), find_boolean_var(), hack_special_boolean_var(), rl_variable_bind(), rl_variable_dumper(), and rl_variable_value().
builtin_keymap_names
struct name_and_keymap builtin_keymap_names[] static
Initial value:
= {
  { "emacs", emacs_standard_keymap },
  { "emacs-standard", emacs_standard_keymap },
  { "emacs-meta", emacs_meta_keymap },
  { "emacs-ctlx", emacs_ctlx_keymap },
  { "vi", vi_movement_keymap },
  { "vi-move", vi_movement_keymap },
  { "vi-command", vi_movement_keymap },
  { "vi-insert", vi_insertion_keymap },
  { (char *)0x0, (Keymap)0x0 }
}
Definition at line 2400 of file bind.c.
Referenced by rl_set_keymap_name().
current_readline_init_file
const char* current_readline_init_file static
Definition at line 966 of file bind.c.
Referenced by _rl_init_file_error(), _rl_read_init_file(), and parser_include().
current_readline_init_include_level
int current_readline_init_include_level static
Definition at line 967 of file bind.c.
Referenced by _rl_read_init_file(), and parser_include().
current_readline_init_lineno
int current_readline_init_lineno static
Definition at line 968 of file bind.c.
Referenced by _rl_init_file_error(), _rl_read_init_file(), and parser_include().
currently_reading_init_file
int currently_reading_init_file static
Definition at line 101 of file bind.c.
Referenced by _rl_init_file_error(), and _rl_read_init_file().
errno
int errno extern
Referenced by _rl_read_file(), and _rl_read_init_file().
if_stack
unsigned char* if_stack = (unsigned char *)NULL static
Definition at line 1248 of file bind.c.
Referenced by parser_else(), parser_endif(), and parser_if().
if_stack_depth
int if_stack_depth static
Definition at line 1249 of file bind.c.
Referenced by parser_else(), parser_endif(), and parser_if().
if_stack_size
int if_stack_size static
Definition at line 1250 of file bind.c.
Referenced by parser_if().
keymap_names
struct name_and_keymap* keymap_names = builtin_keymap_names static
Definition at line 2434 of file bind.c.
Referenced by _rl_get_keymap_by_map(), _rl_get_keymap_by_name(), rl_get_keymap_by_name(), rl_get_keymap_name(), and rl_set_keymap_name().
last_readline_init_file
char* last_readline_init_file = (char *)NULL static
Definition at line 963 of file bind.c.
Referenced by _rl_read_init_file(), and rl_read_init_file().
name_key_alist
const assoc_list name_key_alist[] static
Initial value:
= {
  { "DEL", 0x7f },
  { "ESC", '\033' },
  { "Escape", '\033' },
  { "LFD", '\n' },
  { "Newline", '\n' },
  { "RET", '\r' },
  { "Return", '\r' },
  { "Rubout", 0x7f },
  { "SPC", ' ' },
  { "Space", ' ' },
  { "Tab", 0x09 },
  { (char *)0x0, 0 }
}
Definition at line 2384 of file bind.c.
const { ... } parser_directives[]
Initial value:
= {
  { "if", parser_if },
  { "endif", parser_endif },
  { "else", parser_else },
  { "include", parser_include },
  { (char *)0x0, (_rl_parser_func_t *)0x0 }
}
Referenced by handle_parser_directive().
rl_binding_keymap
Keymap rl_binding_keymap
Definition at line 73 of file bind.c.
Referenced by rl_bind_key(), and rl_generic_bind().
rl_readline_name
const char* rl_readline_name = "other"
Definition at line 1245 of file bind.c.
Referenced by initialize_readline(), and parser_if().
const { ... } string_varlist[]
Initial value:
= {
  { "active-region-end-color", V_STRING, sv_region_end_color },
  { "active-region-start-color", V_STRING, sv_region_start_color },
  { "bell-style",   V_STRING,   sv_bell_style },
  { "comment-begin",    V_STRING,   sv_combegin },
  { "completion-display-width", V_INT,  sv_compwidth },
  { "completion-prefix-display-length", V_INT,  sv_dispprefix },
  { "completion-query-items", V_INT,    sv_compquery },
  { "editing-mode", V_STRING,   sv_editmode },
  { "emacs-mode-string", V_STRING,  sv_emacs_modestr },
  { "history-size", V_INT,      sv_histsize },
  { "isearch-terminators", V_STRING,    sv_isrchterm },
  { "keymap",       V_STRING,   sv_keymap },
  { "keyseq-timeout",   V_INT,      sv_seqtimeout },
  { "vi-cmd-mode-string", V_STRING, sv_vicmd_modestr },
  { "vi-ins-mode-string", V_STRING, sv_viins_modestr },
  { (char *)NULL,   0, (_rl_sv_func_t *)0 }
}
Referenced by find_string_var(), rl_variable_bind(), rl_variable_dumper(), rl_variable_value(), and string_varname().