Fennix: Userspace/apps/base/bash/lib/readline/colors.h File Reference
colors.h File Reference
#include <stdio.h>
Data Structures
struct bin_str
struct _color_ext_type
Macros
#define bool _rl_bool_t
#define true 1
#define false 0
#define FILETYPE_INDICATORS
#define S_IXUGO (S_IXUSR | S_IXGRP | S_IXOTH)
#define C_PREFIX C_SOCK
Typedefs
typedef int _rl_bool_t
typedef struct _color_ext_type COLOR_EXT_TYPE
Enumerations
enum indicator_no {
C_LEFT , C_RIGHT , C_END , C_RESET ,
C_NORM , C_FILE , C_DIR , C_LINK ,
C_FIFO , C_SOCK , C_BLK , C_CHR ,
C_MISSING , C_ORPHAN , C_EXEC , C_DOOR ,
C_SETUID , C_SETGID , C_STICKY , C_OTHER_WRITABLE ,
C_STICKY_OTHER_WRITABLE , C_CAP , C_MULTIHARDLINK , C_CLR_TO_EOL
}
enum filetype {
unknown , fifo , chardev , directory ,
blockdev , normal , symbolic_link , sock ,
whiteout , arg_directory
}
Functions
void _rl_put_indicator (const struct bin_str *ind)
void _rl_set_normal_color (void)
bool _rl_print_prefix_color (void)
bool _rl_print_color_indicator (const char *f)
void _rl_prep_non_filename_text (void)
Variables
struct bin_str _rl_color_indicator []
COLOR_EXT_TYPE * _rl_color_ext_list
Data Structure Documentation
bin_str
struct bin_str
Definition at line 56 of file colors.h.
Data Fields
size_t len
const char * string
_color_ext_type
struct _color_ext_type
Definition at line 68 of file colors.h.
Data Fields
struct bin_str ext
struct _color_ext_type * next
struct bin_str seq
Macro Definition Documentation
bool
#define bool _rl_bool_t
Definition at line 44 of file colors.h.
C_PREFIX
#define C_PREFIX C_SOCK
Definition at line 118 of file colors.h.
false
#define false 0
Definition at line 48 of file colors.h.
FILETYPE_INDICATORS
#define FILETYPE_INDICATORS
Value:
  {                         \
    C_ORPHAN, C_FIFO, C_CHR, C_DIR, C_BLK, C_FILE,  \
    C_LINK, C_SOCK, C_FILE, C_DIR           \
  }
Definition at line 79 of file colors.h.
S_IXUGO
#define S_IXUGO (S_IXUSR | S_IXGRP | S_IXOTH)
Definition at line 100 of file colors.h.
true
#define true 1
Definition at line 47 of file colors.h.
Typedef Documentation
_rl_bool_t
typedef int _rl_bool_t
Definition at line 39 of file colors.h.
COLOR_EXT_TYPE
typedef struct _color_ext_type COLOR_EXT_TYPE
Enumeration Type Documentation
filetype
enum filetype
Enumerator
unknown
fifo
chardev
directory
blockdev
normal
symbolic_link
sock
whiteout
arg_directory
Definition at line 103 of file colors.h.
   {
     unknown,
     fifo,
     chardev,
     directory,
     blockdev,
     normal,
     symbolic_link,
     sock,
     whiteout,
     arg_directory
   };
indicator_no
enum indicator_no
Enumerator
C_LEFT
C_RIGHT
C_END
C_RESET
C_NORM
C_FILE
C_DIR
C_LINK
C_FIFO
C_SOCK
C_BLK
C_CHR
C_MISSING
C_ORPHAN
C_EXEC
C_DOOR
C_SETUID
C_SETGID
C_STICKY
C_OTHER_WRITABLE
C_STICKY_OTHER_WRITABLE
C_CAP
C_MULTIHARDLINK
C_CLR_TO_EOL
Definition at line 89 of file colors.h.
   {
     C_LEFT, C_RIGHT, C_END, C_RESET, C_NORM, C_FILE, C_DIR, C_LINK,
     C_FIFO, C_SOCK,
     C_BLK, C_CHR, C_MISSING, C_ORPHAN, C_EXEC, C_DOOR, C_SETUID, C_SETGID,
     C_STICKY, C_OTHER_WRITABLE, C_STICKY_OTHER_WRITABLE, C_CAP, C_MULTIHARDLINK,
     C_CLR_TO_EOL
   };
Function Documentation
_rl_prep_non_filename_text()
void _rl_prep_non_filename_text (void)
Definition at line 309 of file colors.c.
 {
   if (_rl_color_indicator[C_END].string != NULL)
     _rl_put_indicator (&_rl_color_indicator[C_END]);
   else
     {
       _rl_put_indicator (&_rl_color_indicator[C_LEFT]);
       _rl_put_indicator (&_rl_color_indicator[C_RESET]);
       _rl_put_indicator (&_rl_color_indicator[C_RIGHT]);
     }
 }
References _rl_color_indicator, _rl_put_indicator(), C_END, C_LEFT, C_RESET, C_RIGHT, and NULL.
Referenced by colored_stat_end().
_rl_print_color_indicator()
bool _rl_print_color_indicator (const char * f)
Definition at line 152 of file colors.c.
 {
   enum indicator_no colored_filetype;
   COLOR_EXT_TYPE *ext;  /* Color extension */
   size_t len;       /* Length of name */
   const char* name;
   char *filename;
   struct stat astat, linkstat;
   mode_t mode;
   int linkok;   /* 1 == ok, 0 == dangling symlink, -1 == missing */
   int stat_ok;
   name = f;
   /* This should already have undergone tilde expansion */
   filename = 0;
   if (rl_filename_stat_hook)
     {
       filename = savestring (f);
       (*rl_filename_stat_hook) (&filename);
       name = filename;
     }
 #if defined (HAVE_LSTAT)
   stat_ok = lstat(name, &astat);
 #else
   stat_ok = stat(name, &astat);
 #endif
   if (stat_ok == 0)
     {
       mode = astat.st_mode;
 #if defined (HAVE_LSTAT)
       if (S_ISLNK (mode))
     {
       linkok = stat (name, &linkstat) == 0;
       if (linkok && strncmp (_rl_color_indicator[C_LINK].string, "target", 6) == 0)
         mode = linkstat.st_mode;
     }
       else
 #endif
     linkok = 1;
     }
   else
     linkok = -1;
   /* Is this a nonexistent file?  If so, linkok == -1.  */
   if (linkok == -1 && _rl_color_indicator[C_MISSING].string != NULL)
     colored_filetype = C_MISSING;
   else if (linkok == 0 && _rl_color_indicator[C_ORPHAN].string != NULL)
     colored_filetype = C_ORPHAN;    /* dangling symlink */
   else if(stat_ok != 0)
     {
       static enum indicator_no filetype_indicator[] = FILETYPE_INDICATORS;
       colored_filetype = filetype_indicator[normal]; //f->filetype];
     }
   else
     {
       if (S_ISREG (mode))
         {
           colored_filetype = C_FILE;
 #if defined (S_ISUID)
           if ((mode & S_ISUID) != 0 && is_colored (C_SETUID))
             colored_filetype = C_SETUID;
           else
 #endif
 #if defined (S_ISGID)
           if ((mode & S_ISGID) != 0 && is_colored (C_SETGID))
             colored_filetype = C_SETGID;
           else
 #endif
           if (is_colored (C_CAP) && 0) //f->has_capability)
             colored_filetype = C_CAP;
           else if ((mode & S_IXUGO) != 0 && is_colored (C_EXEC))
             colored_filetype = C_EXEC;
           else if ((1 < astat.st_nlink) && is_colored (C_MULTIHARDLINK))
             colored_filetype = C_MULTIHARDLINK;
         }
       else if (S_ISDIR (mode))
         {
           colored_filetype = C_DIR;
 #if defined (S_ISVTX)
           if ((mode & S_ISVTX) && (mode & S_IWOTH)
               && is_colored (C_STICKY_OTHER_WRITABLE))
             colored_filetype = C_STICKY_OTHER_WRITABLE;
           else
 #endif
           if ((mode & S_IWOTH) != 0 && is_colored (C_OTHER_WRITABLE))
             colored_filetype = C_OTHER_WRITABLE;
 #if defined (S_ISVTX)
           else if ((mode & S_ISVTX) != 0 && is_colored (C_STICKY))
             colored_filetype = C_STICKY;
 #endif
         }
 #if defined (S_ISLNK)
       else if (S_ISLNK (mode))
         colored_filetype = C_LINK;
 #endif
       else if (S_ISFIFO (mode))
         colored_filetype = C_FIFO;
 #if defined (S_ISSOCK)
       else if (S_ISSOCK (mode))
         colored_filetype = C_SOCK;
 #endif
 #if defined (S_ISBLK)
       else if (S_ISBLK (mode))
         colored_filetype = C_BLK;
 #endif
       else if (S_ISCHR (mode))
         colored_filetype = C_CHR;
       else
         {
           /* Classify a file of some other type as C_ORPHAN.  */
           colored_filetype = C_ORPHAN;
         }
     }
   /* Check the file's suffix only if still classified as C_FILE.  */
   ext = NULL;
   if (colored_filetype == C_FILE)
     {
       /* Test if NAME has a recognized suffix.  */
       len = strlen (name);
       name += len;      /* Pointer to final \0.  */
       for (ext = _rl_color_ext_list; ext != NULL; ext = ext->next)
         {
           if (ext->ext.len <= len
               && strncmp (name - ext->ext.len, ext->ext.string,
                           ext->ext.len) == 0)
             break;
         }
     }
   free (filename);  /* NULL or savestring return value */
   {
     const struct bin_str *const s
       = ext ? &(ext->seq) : &_rl_color_indicator[colored_filetype];
     if (s->string != NULL)
       {
         /* Need to reset so not dealing with attribute combinations */
         if (is_colored (C_NORM))
       restore_default_color ();
         _rl_put_indicator (&_rl_color_indicator[C_LEFT]);
         _rl_put_indicator (s);
         _rl_put_indicator (&_rl_color_indicator[C_RIGHT]);
         return 0;
       }
     else
       return 1;
   }
 }
References _rl_color_ext_list, _rl_color_indicator, _rl_put_indicator(), C_BLK, C_CAP, C_CHR, C_DIR, C_EXEC, C_FIFO, C_FILE, C_LEFT, C_LINK, C_MISSING, C_MULTIHARDLINK, C_NORM, C_ORPHAN, C_OTHER_WRITABLE, C_RIGHT, C_SETGID, C_SETUID, C_SOCK, C_STICKY, C_STICKY_OTHER_WRITABLE, _color_ext_type::ext, f, filename, FILETYPE_INDICATORS, free, is_colored(), len, bin_str::len, lstat, mode_t, _color_ext_type::next, normal, NULL, restore_default_color(), rl_filename_stat_hook, s, S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISGID, S_ISLNK, S_ISREG, S_ISSOCK, S_ISUID, S_ISVTX, S_IWOTH, S_IXUGO, savestring(), _color_ext_type::seq, stat::st_mode, stat::st_nlink, stat(), bin_str::string, strlen(), and strncmp().
Referenced by colored_stat_start().
_rl_print_prefix_color()
bool _rl_print_prefix_color (void)
Definition at line 129 of file colors.c.
 {
   struct bin_str *s;
   /* What do we want to use for the prefix? Let's try cyan first, see colors.h */
   s = _rl_custom_readline_prefix ();
   if (s == 0)
     s = &_rl_color_indicator[C_PREFIX];
   if (s->string != NULL)
     {
       if (is_colored (C_NORM))
     restore_default_color ();
       _rl_put_indicator (&_rl_color_indicator[C_LEFT]);
       _rl_put_indicator (s);
       _rl_put_indicator (&_rl_color_indicator[C_RIGHT]);
       return 0;
     }
   else
     return 1;
 }
References _rl_color_indicator, _rl_custom_readline_prefix(), _rl_put_indicator(), C_LEFT, C_NORM, C_PREFIX, C_RIGHT, is_colored(), NULL, restore_default_color(), and s.
Referenced by colored_prefix_start().
_rl_put_indicator()
void _rl_put_indicator (const struct bin_str * ind)
Definition at line 82 of file colors.c.
 {
   fwrite (ind->string, ind->len, 1, rl_outstream);
 }
References fwrite(), bin_str::len, rl_outstream, and bin_str::string.
Referenced by _rl_prep_non_filename_text(), _rl_print_color_indicator(), _rl_print_prefix_color(), _rl_set_normal_color(), colored_stat_end(), and restore_default_color().
_rl_set_normal_color()
void _rl_set_normal_color (void)
Definition at line 105 of file colors.c.
 {
   if (is_colored (C_NORM))
     {
       _rl_put_indicator (&_rl_color_indicator[C_LEFT]);
       _rl_put_indicator (&_rl_color_indicator[C_NORM]);
       _rl_put_indicator (&_rl_color_indicator[C_RIGHT]);
     }
 }
References _rl_color_indicator, _rl_put_indicator(), C_LEFT, C_NORM, C_RIGHT, and is_colored().
Referenced by colored_prefix_start(), and colored_stat_start().
Variable Documentation
_rl_color_ext_list
COLOR_EXT_TYPE* _rl_color_ext_list extern
Definition at line 78 of file colors.c.
Referenced by _rl_custom_readline_prefix(), _rl_parse_colors(), and _rl_print_color_indicator().
_rl_color_indicator
struct bin_str _rl_color_indicator[] extern
Definition at line 60 of file parse-colors.c.
Referenced by _rl_parse_colors(), _rl_prep_non_filename_text(), _rl_print_color_indicator(), _rl_print_prefix_color(), _rl_set_normal_color(), colored_stat_end(), is_colored(), and restore_default_color().