Fennix: Userspace/apps/base/busybox/util-linux/volume_id/exfat.c File Reference
exfat.c File Reference
#include "volume_id_internal.h"
Data Structures
struct exfat_super_block
struct exfat_dir_entry
union exfat_dir_entry.type
struct volume_label.type.label
struct volume_guid.type.guid
Macros
#define EXFAT_SB_OFFSET 0
#define EXFAT_DIR_ENTRY_SZ 32
#define EXFAT_MAX_DIR_ENTRIES 100
Functions
int FAST_FUNC volume_id_probe_exfat (struct volume_id *id)
Variables
struct exfat_super_block PACKED
Data Structure Documentation
exfat_super_block
struct exfat_super_block
Definition at line 37 of file exfat.c.
Data Fields
uint8_t boot_jump[3]
uint8_t bytes_per_sector
uint32_t cluster_count
uint32_t cluster_heap_offset
uint32_t fat_offset
uint32_t fat_size
uint8_t fs_name[8]
uint16_t fs_revision
uint8_t must_be_zero[53]
uint8_t nr_of_fats
uint64_t partition_offset
uint32_t root_dir
uint8_t sectors_per_cluster
uint16_t vol_flags
uint8_t vol_serial_nr[4]
uint64_t volume_length
exfat_dir_entry
struct exfat_dir_entry
Definition at line 57 of file exfat.c.
Data Fields
uint8_t entry_type
union exfat_dir_entry type
exfat_dir_entry.type
union exfat_dir_entry.type
Definition at line 59 of file exfat.c.
Data Fields
type guid
type label
exfat_dir_entry::volume_label.type.label
struct exfat_dir_entry::volume_label.type.label
Definition at line 60 of file exfat.c.
Data Fields
uint8_t char_count
uint8_t reserved[8]
uint16_t vol_label[11]
exfat_dir_entry::volume_guid.type.guid
struct exfat_dir_entry::volume_guid.type.guid
Definition at line 65 of file exfat.c.
Data Fields
uint16_t flags
uint8_t reserved[10]
uint8_t sec_count
uint16_t set_checksum
uint8_t vol_guid[16]
Macro Definition Documentation
EXFAT_DIR_ENTRY_SZ
#define EXFAT_DIR_ENTRY_SZ 32
Definition at line 34 of file exfat.c.
EXFAT_MAX_DIR_ENTRIES
#define EXFAT_MAX_DIR_ENTRIES 100
Definition at line 35 of file exfat.c.
EXFAT_SB_OFFSET
#define EXFAT_SB_OFFSET 0
Definition at line 33 of file exfat.c.
Function Documentation
volume_id_probe_exfat()
int FAST_FUNC volume_id_probe_exfat (struct volume_id * id)
Definition at line 75 of file exfat.c.
 {
     struct exfat_super_block *sb;
     struct exfat_dir_entry *de;
     unsigned    sector_sz;
     unsigned    cluster_sz;
     uint64_t    root_dir_off;
     unsigned    count;
     unsigned    need_lbl_guid;
     // Primary super block
     dbg("exFAT: probing at offset 0x%x", EXFAT_SB_OFFSET);
     sb = volume_id_get_buffer(id, EXFAT_SB_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (memcmp(sb->fs_name, "EXFAT   ", 8) != 0)
         return -1;
     sector_sz = 1 << sb->bytes_per_sector;
     cluster_sz = sector_sz << sb->sectors_per_cluster;
     // There are no clusters 0 and 1, so the first cluster is 2.
     root_dir_off = (uint64_t)EXFAT_SB_OFFSET +
         // Hmm... should we cast sector_sz/cluster_sz to uint64_t?
         (le32_to_cpu(sb->cluster_heap_offset)) * sector_sz +
         (le32_to_cpu(sb->root_dir) - 2) * cluster_sz;
     dbg("exFAT: sector size 0x%x bytes", sector_sz);
     dbg("exFAT: cluster size 0x%x bytes", cluster_sz);
     dbg("exFAT: root dir is at 0x%llx", (long long)root_dir_off);
     // Use DOS uuid as fallback, if no GUID set
     volume_id_set_uuid(id, sb->vol_serial_nr, UUID_DOS);
     // EXFAT_MAX_DIR_ENTRIES is used as a safety belt.
     // The Root Directory may hold an unlimited number of entries,
     // so we do not want to check all. Usually label and GUID
     // are in the beginning, but there are no guarantees.
     need_lbl_guid = (1 << 0) | (1 << 1);
     for (count = 0; count < EXFAT_MAX_DIR_ENTRIES; count++) {
         de = volume_id_get_buffer(id, root_dir_off + (count * EXFAT_DIR_ENTRY_SZ), EXFAT_DIR_ENTRY_SZ);
         if (de == NULL)
             break;
         if (de->entry_type == 0x00) {
             // End of Directory Marker
             dbg("exFAT: End of root directory reached after %u entries", count);
             break;
         }
         if (de->entry_type == 0x83) {
             // Volume Label Directory Entry
             volume_id_set_label_unicode16(id, (uint8_t *)de->type.label.vol_label,
                         LE, 2 * de->type.label.char_count);
             need_lbl_guid &= ~(1 << 0);
         }
         if (de->entry_type == 0xA0) {
             // Volume GUID Directory Entry
             volume_id_set_uuid(id, de->type.guid.vol_guid, UUID_DCE);
             need_lbl_guid &= ~(1 << 1);
         }
         if (!need_lbl_guid)
             break;
     }
     IF_FEATURE_BLKID_TYPE(id->type = "exfat";)
     return 0;
 }
References exfat_super_block::bytes_per_sector, exfat_super_block::cluster_heap_offset, count, dbg, exfat_dir_entry::entry_type, EXFAT_DIR_ENTRY_SZ, EXFAT_MAX_DIR_ENTRIES, EXFAT_SB_OFFSET, exfat_super_block::fs_name, LE, le32_to_cpu, memcmp(), NULL, exfat_super_block::root_dir, exfat_super_block::sectors_per_cluster, exfat_dir_entry::type, UUID_DCE, UUID_DOS, exfat_super_block::vol_serial_nr, volume_id_get_buffer(), volume_id_set_label_unicode16(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct exfat_dir_entry PACKED