Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/btrfs.c File Reference
btrfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct btrfs_dev_item
struct btrfs_super_block
Macros
#define BTRFS_UUID_SIZE 16
#define BTRFS_LABEL_SIZE 256
#define BTRFS_CSUM_SIZE 32
#define BTRFS_FSID_SIZE 16
#define BTRFS_MAGIC "_BHRfS_M"
Functions
int FAST_FUNC volume_id_probe_btrfs (struct volume_id *id)
Variables
struct btrfs_dev_item PACKED
Data Structure Documentation
btrfs_dev_item
struct btrfs_dev_item
Definition at line 37 of file btrfs.c.
Data Fields
uint8_t bandwidth
uint64_t bytes_used
uint32_t dev_group
uint64_t devid
uint8_t fsid[BTRFS_UUID_SIZE]
uint64_t generation
uint32_t io_align
uint32_t io_width
uint32_t sector_size
uint8_t seek_speed
uint64_t start_offset
uint64_t total_bytes
uint64_t type
uint8_t uuid[BTRFS_UUID_SIZE]
btrfs_super_block
struct btrfs_super_block
Definition at line 54 of file btrfs.c.
Data Fields
uint64_t bytenr
uint64_t bytes_used
uint64_t chunk_root
uint64_t chunk_root_generation
uint8_t chunk_root_level
uint64_t compat_flags
uint64_t compat_ro_flags
uint8_t csum[BTRFS_CSUM_SIZE]
uint16_t csum_type
struct btrfs_dev_item dev_item
uint64_t flags
uint8_t fsid[BTRFS_FSID_SIZE]
uint64_t generation
uint64_t incompat_flags
uint8_t label[BTRFS_LABEL_SIZE]
uint32_t leafsize
uint64_t log_root
uint8_t log_root_level
uint64_t log_root_transid
uint8_t magic[8]
uint32_t nodesize
uint64_t num_devices
uint64_t root
uint64_t root_dir_objectid
uint8_t root_level
uint32_t sectorsize
uint32_t stripesize
uint32_t sys_chunk_array_size
uint64_t total_bytes
Macro Definition Documentation
BTRFS_CSUM_SIZE
#define BTRFS_CSUM_SIZE 32
Definition at line 32 of file btrfs.c.
BTRFS_FSID_SIZE
#define BTRFS_FSID_SIZE 16
Definition at line 33 of file btrfs.c.
BTRFS_LABEL_SIZE
#define BTRFS_LABEL_SIZE 256
Definition at line 31 of file btrfs.c.
BTRFS_MAGIC
#define BTRFS_MAGIC "_BHRfS_M"
Definition at line 35 of file btrfs.c.
BTRFS_UUID_SIZE
#define BTRFS_UUID_SIZE 16
Definition at line 30 of file btrfs.c.
Function Documentation
volume_id_probe_btrfs()
int FAST_FUNC volume_id_probe_btrfs (struct volume_id * id)
Definition at line 87 of file btrfs.c.
 {
     // btrfs has superblocks at 64K, 64M and 256G
     // minimum btrfs size is 256M
     // so we never step out the device if we analyze
     // the first and the second superblocks
     struct btrfs_super_block *sb;
     unsigned off = 64;
     while (off < 64*1024*1024) {
         off *= 1024;
         dbg("btrfs: probing at offset 0x%x", off);
         sb = volume_id_get_buffer(id, off, sizeof(*sb));
         if (sb == NULL)
             return -1;
         if (memcmp(sb->magic, BTRFS_MAGIC, 8) != 0)
             return -1;
     }
     // N.B.: btrfs natively supports 256 (>VOLUME_ID_LABEL_SIZE) size labels
     volume_id_set_label_string(id, sb->label, VOLUME_ID_LABEL_SIZE);
     volume_id_set_uuid(id, sb->fsid, UUID_DCE);
     IF_FEATURE_BLKID_TYPE(id->type = "btrfs";)
     return 0;
 }
References BTRFS_MAGIC, dbg, btrfs_super_block::fsid, btrfs_super_block::label, btrfs_super_block::magic, memcmp(), NULL, off, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct btrfs_super_block PACKED