Fennix: Userspace/apps/base/busybox/libbb/setup_environment.c File Reference
setup_environment.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC setup_environment (const char *shell, int flags, const struct passwd *pw)
Function Documentation
setup_environment()
void FAST_FUNC setup_environment (const char * shell, int flags, const struct passwd * pw)
Definition at line 32 of file setup_environment.c.
 {
     if (!shell || !shell[0])
         shell = DEFAULT_SHELL;
     /* Change the current working directory to be the home directory
      * of the user */
     if (flags & SETUP_ENV_CHDIR) {
         if (chdir_or_warn(pw->pw_dir) != 0) {
             xchdir((flags & SETUP_ENV_TO_TMP) ? "/tmp" : "/");
         }
     }
     if (flags & SETUP_ENV_CLEARENV) {
         const char *term;
         /* Leave TERM unchanged. Set HOME, SHELL, USER, LOGNAME, PATH.
          * Unset all other environment variables.  */
         term = getenv("TERM");
         clearenv();
         if (term)
             xsetenv("TERM", term);
         xsetenv("PATH", (pw->pw_uid ? bb_default_path : bb_default_root_path));
         goto shortcut;
         // No, gcc (4.2.1) is not clever enough to do it itself.
         //xsetenv("USER",    pw->pw_name);
         //xsetenv("LOGNAME", pw->pw_name);
         //xsetenv("HOME",    pw->pw_dir);
         //xsetenv("SHELL",   shell);
     } else
     if (flags & (SETUP_ENV_CHANGEENV|SETUP_ENV_CHANGEENV_LOGNAME)) {
         /* Set HOME, SHELL, and if not becoming a super-user
          * or if SETUP_ENV_CHANGEENV_LOGNAME, USER and LOGNAME.  */
         if ((flags & SETUP_ENV_CHANGEENV_LOGNAME) || pw->pw_uid != 0) {
  shortcut:
             xsetenv("USER",    pw->pw_name);
             xsetenv("LOGNAME", pw->pw_name);
         }
         xsetenv("HOME",    pw->pw_dir);
         xsetenv("SHELL",   shell);
     }
 }
References bb_default_path, bb_default_root_path, chdir_or_warn(), clearenv(), DEFAULT_SHELL, flags, getenv, pw, passwd::pw_dir, passwd::pw_name, passwd::pw_uid, SETUP_ENV_CHANGEENV, SETUP_ENV_CHANGEENV_LOGNAME, SETUP_ENV_CHDIR, SETUP_ENV_CLEARENV, SETUP_ENV_TO_TMP, term, xchdir(), and xsetenv().
Referenced by edit_file(), login_main(), su_main(), and sulogin_main().