Fennix Userspace: Userspace/mlibc/tests/posix/dprintf.c File Reference
dprintf.c File Reference
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <assert.h>
#include <errno.h>
Macros
#define TEST_FILE "dprintf.tmp"
Functions
int main ()
Macro Definition Documentation
TEST_FILE
#define TEST_FILE "dprintf.tmp"
Definition at line 10 of file dprintf.c.
Function Documentation
main()
int main (void)
Definition at line 13 of file dprintf.c.
            {
     int fd = open(TEST_FILE, O_RDWR | O_CREAT, 0666);
     assert(fd > -1);
     int ret = dprintf(fd, "aaa");
     assert(ret == 3);
     // Check if we can read back the same things.
     // Also checks to see if the fd is still open,
     // which is issue #199.
     off_t seek = lseek(fd, 0, SEEK_SET);
     assert(seek == 0);
     char buf[3];
     ssize_t num_read = read(fd, buf, 3);
     assert(num_read == 3);
     assert(buf[0] == 'a'
         && buf[1] == 'a'
         && buf[2] == 'a');
     // All the tests pass, now we can unlink the file.
     ret = unlink(TEST_FILE);
     assert(ret == 0);
     return 0;
 }
References assert, buf, dprintf(), fd, lseek(), O_CREAT, O_RDWR, open(), read(), ret, SEEK_SET, TEST_FILE, and unlink().