Fennix: Userspace/apps/base/busybox/editors/patch_toybox.c File Reference
patch_toybox.c File Reference
#include "libbb.h"
Data Structures
struct double_list
struct globals
Macros
#define TT (*ptr_to_globals)
#define INIT_TT()
#define FLAG_STR "Rup:i:x"
#define FLAG_REVERSE (1 << 0)
#define FLAG_u (1 << 1)
#define FLAG_PATHLEN (1 << 2)
#define FLAG_INPUT (1 << 3)
#define FLAG_DEBUG (1 << 4)
#define PATCH_DEBUG (option_mask32 & FLAG_DEBUG)
Functions
static void * TOY_llist_pop (void *list)
static void TOY_llist_free (void *list, void(*freeit)(void *data))
static struct double_list * dlist_add (struct double_list **list, char *data)
static void xmkpath (char *path, int mode)
static char * get_rawline (int fd, long *plen, char end)
static char * get_line (int fd)
static void xsendfile (int in, int out)
static void replace_tempfile (int fdin, int fdout, char **tempname)
static int copy_tempfile (int fdin, char *name, char **tempname)
static void delete_tempfile (int fdin, int fdout, char **tempname)
static void do_line (void *data)
static void finish_oldfile (void)
static void fail_hunk (void)
static int apply_one_hunk (void)
int patch_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
double_list
struct double_list
Definition at line 56 of file patch.c.
Data Fields
char * data
struct double_list * next
struct double_list * prev
Macro Definition Documentation
FLAG_DEBUG
#define FLAG_DEBUG (1 << 4)
Definition at line 251 of file patch_toybox.c.
FLAG_INPUT
#define FLAG_INPUT (1 << 3)
Definition at line 249 of file patch_toybox.c.
FLAG_PATHLEN
#define FLAG_PATHLEN (1 << 2)
Definition at line 248 of file patch_toybox.c.
FLAG_REVERSE
#define FLAG_REVERSE (1 << 0)
Definition at line 246 of file patch_toybox.c.
FLAG_STR
#define FLAG_STR "Rup:i:x"
Definition at line 244 of file patch_toybox.c.
FLAG_u
#define FLAG_u (1 << 1)
Definition at line 247 of file patch_toybox.c.
INIT_TT
#define INIT_TT ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(TT))); \
} while (0)
Definition at line 238 of file patch_toybox.c.
PATCH_DEBUG
#define PATCH_DEBUG (option_mask32 & FLAG_DEBUG)
Definition at line 260 of file patch_toybox.c.
TT
#define TT (*ptr_to_globals)
Definition at line 237 of file patch_toybox.c.
Function Documentation
apply_one_hunk()
static int apply_one_hunk (void) static
Definition at line 307 of file patch_toybox.c.
 {
     struct double_list *plist, *buf = NULL, *check;
     int matcheof = 0, reverse = option_mask32 & FLAG_REVERSE, backwarn = 0;
     // Break doubly linked list so we can use singly linked traversal function.
     TT.current_hunk->prev->next = NULL;
     // Match EOF if there aren't as many ending context lines as beginning
     for (plist = TT.current_hunk; plist; plist = plist->next) {
         if (plist->data[0] == ' ') matcheof++;
         else matcheof = 0;
         if (PATCH_DEBUG) fdprintf(2, "HUNK:%s\n", plist->data);
     }
     matcheof = matcheof < TT.context;
     if (PATCH_DEBUG) fdprintf(2,"MATCHEOF=%c\n", matcheof ? 'Y' : 'N');
     // Loop through input data searching for this hunk.  Match all context
     // lines and all lines to be removed until we've found the end of a
     // complete hunk.
     plist = TT.current_hunk;
     buf = NULL;
     if (TT.context) for (;;) {
         char *data = get_line(TT.filein);
         TT.linenum++;
         // Figure out which line of hunk to compare with next.  (Skip lines
         // of the hunk we'd be adding.)
         while (plist && *plist->data == "+-"[reverse]) {
             if (data && strcmp(data, plist->data+1) == 0) {
                 if (!backwarn) {
                     fdprintf(2,"Possibly reversed hunk %d at %ld\n",
                         TT.hunknum, TT.linenum);
                     backwarn++;
                 }
             }
             plist = plist->next;
         }
         // Is this EOF?
         if (!data) {
             if (PATCH_DEBUG) fdprintf(2, "INEOF\n");
             // Does this hunk need to match EOF?
             if (!plist && matcheof) break;
             // File ended before we found a place for this hunk.
             fail_hunk();
             goto done;
         } else if (PATCH_DEBUG) fdprintf(2, "IN: %s\n", data);
         check = dlist_add(&buf, data);
         // Compare this line with next expected line of hunk.
         // todo: teach the strcmp() to ignore whitespace.
         // A match can fail because the next line doesn't match, or because
         // we hit the end of a hunk that needed EOF, and this isn't EOF.
         // If match failed, flush first line of buffered data and
         // recheck buffered data for a new match until we find one or run
         // out of buffer.
         for (;;) {
             if (!plist || strcmp(check->data, plist->data+1)) {
                 // Match failed.  Write out first line of buffered data and
                 // recheck remaining buffered data for a new match.
                 if (PATCH_DEBUG)
                     fdprintf(2, "NOT: %s\n", plist->data);
                 TT.state = 3;
                 check = TOY_llist_pop(&buf);
                 check->prev->next = buf;
                 buf->prev = check->prev;
                 do_line(check);
                 plist = TT.current_hunk;
                 // If we've reached the end of the buffer without confirming a
                 // match, read more lines.
                 if (check == buf) {
                     buf = 0;
                     break;
                 }
                 check = buf;
             } else {
                 if (PATCH_DEBUG)
                     fdprintf(2, "MAYBE: %s\n", plist->data);
                 // This line matches.  Advance plist, detect successful match.
                 plist = plist->next;
                 if (!plist && !matcheof) goto out;
                 check = check->next;
                 if (check == buf) break;
             }
         }
     }
 out:
     // We have a match.  Emit changed data.
     TT.state = "-+"[reverse];
     TOY_llist_free(TT.current_hunk, do_line);
     TT.current_hunk = NULL;
     TT.state = 1;
 done:
     if (buf) {
         buf->prev->next = NULL;
         TOY_llist_free(buf, do_line);
     }
     return TT.state;
 }
References buf, check(), double_list::data, dlist_add(), do_line(), done, fail_hunk(), fdprintf, FLAG_REVERSE, get_line(), double_list::next, NULL, option_mask32, out(), PATCH_DEBUG, reverse(), strcmp, TOY_llist_free(), TOY_llist_pop(), and TT.
Referenced by patch_main().
copy_tempfile()
static int copy_tempfile (int fdin, char * name, char ** tempname) static
Definition at line 196 of file patch_toybox.c.
 {
     struct stat statbuf;
     int fd;
     *tempname = xasprintf("%sXXXXXX", name);
     fd = mkstemp(*tempname);
     if(-1 == fd) bb_simple_perror_msg_and_die("no temp file");
     // Set permissions of output file
     fstat(fdin, &statbuf);
     fchmod(fd, statbuf.st_mode);
     return fd;
 }
References bb_simple_perror_msg_and_die(), fchmod(), fd, fstat(), mkstemp(), stat::st_mode, and xasprintf().
Referenced by patch_main().
delete_tempfile()
static void delete_tempfile (int fdin, int fdout, char ** tempname) static
Definition at line 214 of file patch_toybox.c.
 {
     close(fdin);
     close(fdout);
     unlink(*tempname);
     free(*tempname);
     *tempname = NULL;
 }
References close(), free, NULL, and unlink().
Referenced by fail_hunk().
dlist_add()
static struct double_list* dlist_add (struct double_list ** list, char * data) static
Definition at line 88 of file patch_toybox.c.
 {
     struct double_list *line = xmalloc(sizeof(struct double_list));
     line->data = data;
     if (*list) {
         line->next = *list;
         line->prev = (*list)->prev;
         (*list)->prev->next = line;
         (*list)->prev = line;
     } else *list = line->next = line->prev = line;
     return line;
 }
References double_list::data, line, list(), and xmalloc.
Referenced by apply_one_hunk(), and patch_main().
do_line()
static void do_line (void * data) static
Definition at line 262 of file patch_toybox.c.
 {
     struct double_list *dlist = (struct double_list *)data;
     if (TT.state > 1 && *dlist->data != TT.state)
         fdprintf(TT.state == 2 ? 2 : TT.fileout,
             "%s\n", dlist->data + (TT.state > 3 ? 1 : 0));
     if (PATCH_DEBUG) fdprintf(2, "DO %d: %s\n", TT.state, dlist->data);
     free(dlist->data);
     free(data);
 }
References double_list::data, fdprintf, free, PATCH_DEBUG, and TT.
Referenced by apply_one_hunk(), and fail_hunk().
fail_hunk()
static void fail_hunk (void) static
Definition at line 282 of file patch_toybox.c.
 {
     if (!TT.current_hunk) return;
     TT.current_hunk->prev->next = 0;
     fdprintf(2, "Hunk %d FAILED %ld/%ld.\n", TT.hunknum, TT.oldline, TT.newline);
     TT.exitval = 1;
     // If we got to this point, we've seeked to the end.  Discard changes to
     // this file and advance to next file.
     TT.state = 2;
     TOY_llist_free(TT.current_hunk, do_line);
     TT.current_hunk = NULL;
     delete_tempfile(TT.filein, TT.fileout, &TT.tempname);
     TT.state = 0;
 }
References delete_tempfile(), do_line(), fdprintf, NULL, TOY_llist_free(), and TT.
Referenced by apply_one_hunk(), and patch_main().
finish_oldfile()
static void finish_oldfile (void) static
Definition at line 276 of file patch_toybox.c.
 {
     if (TT.tempname) replace_tempfile(TT.filein, TT.fileout, &TT.tempname);
     TT.fileout = TT.filein = -1;
 }
References replace_tempfile(), and TT.
Referenced by patch_main().
get_line()
static char* get_line (int fd) static
Definition at line 151 of file patch_toybox.c.
 {
     long len;
     char *buf = get_rawline(fd, &len, '\n');
     if (buf && buf[--len] == '\n') buf[len] = 0;
     return buf;
 }
References buf, fd, get_rawline(), and len.
Referenced by apply_one_hunk(), and patch_main().
get_rawline()
static char* get_rawline (int fd, long * plen, char end) static
Definition at line 134 of file patch_toybox.c.
 {
     char c, *buf = NULL;
     long len = 0;
     for (;;) {
         if (1 > read(fd, &c, 1)) break;
         if (!(len & 63)) buf=xrealloc(buf, len+65);
         if ((buf[len++] = c) == end) break;
     }
     if (buf) buf[len] = 0;
     if (plen) *plen = len;
     return buf;
 }
References buf, c, end, fd, len, NULL, read(), and xrealloc.
Referenced by get_line().
patch_main()
int patch_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 428 of file patch_toybox.c.
 {
     int opts;
     int reverse, state = 0;
     char *oldname = NULL, *newname = NULL;
     char *opt_p, *opt_i;
     INIT_TT();
     opts = getopt32(argv, FLAG_STR, &opt_p, &opt_i);
     reverse = opts & FLAG_REVERSE;
     TT.prefix = (opts & FLAG_PATHLEN) ? xatoi(opt_p) : 0; // can be negative!
     if (opts & FLAG_INPUT) TT.filepatch = xopen(opt_i, O_RDONLY);
     TT.filein = TT.fileout = -1;
     // Loop through the lines in the patch
     for (;;) {
         char *patchline;
         patchline = get_line(TT.filepatch);
         if (!patchline) break;
         // Other versions of patch accept damaged patches,
         // so we need to also.
         if (!*patchline) {
             free(patchline);
             patchline = xstrdup(" ");
         }
         // Are we assembling a hunk?
         if (state >= 2) {
             if (*patchline == ' ' || *patchline == '+' || *patchline == '-') {
                 dlist_add(&TT.current_hunk, patchline);
                 if (*patchline != '+') TT.oldlen--;
                 if (*patchline != '-') TT.newlen--;
                 // Context line?
                 if (*patchline == ' ' && state == 2) TT.context++;
                 else state = 3;
                 // If we've consumed all expected hunk lines, apply the hunk.
                 if (!TT.oldlen && !TT.newlen) state = apply_one_hunk();
                 continue;
             }
             fail_hunk();
             state = 0;
             continue;
         }
         // Open a new file?
         if (!strncmp("--- ", patchline, 4) || !strncmp("+++ ", patchline, 4)) {
             char *s, **name = reverse ? &newname : &oldname;
             int i;
             if (*patchline == '+') {
                 name = reverse ? &oldname : &newname;
                 state = 1;
             }
             free(*name);
             finish_oldfile();
             // Trim date from end of filename (if any).  We don't care.
             for (s = patchline+4; *s && *s!='\t'; s++)
                 if (*s == '\\' && s[1]) s++;
             i = atoi(s);
             if (i > 1900 && i <= 1970)
                 *name = xstrdup("/dev/null");
             else {
                 *s = 0;
                 *name = xstrdup(patchline+4);
             }
             // We defer actually opening the file because svn produces broken
             // patches that don't signal they want to create a new file the
             // way the patch man page says, so you have to read the first hunk
             // and _guess_.
         // Start a new hunk?
         } else if (state == 1 && !strncmp("@@ -", patchline, 4)) {
             int i;
             i = sscanf(patchline+4, "%ld,%ld +%ld,%ld", &TT.oldline,
                         &TT.oldlen, &TT.newline, &TT.newlen);
             if (i != 4)
                 bb_error_msg_and_die("corrupt hunk %d at %ld", TT.hunknum, TT.linenum);
             TT.context = 0;
             state = 2;
             // If this is the first hunk, open the file.
             if (TT.filein == -1) {
                 int oldsum, newsum, del = 0;
                 char *s, *name;
                 oldsum = TT.oldline + TT.oldlen;
                 newsum = TT.newline + TT.newlen;
                 name = reverse ? oldname : newname;
                 // We're deleting oldname if new file is /dev/null (before -p)
                 // or if new hunk is empty (zero context) after patching
                 if (strcmp(name, "/dev/null") == 0 || !(reverse ? oldsum : newsum)) {
                     name = reverse ? newname : oldname;
                     del++;
                 }
                 // handle -p path truncation.
                 for (i=0, s = name; *s;) {
                     if ((option_mask32 & FLAG_PATHLEN) && TT.prefix == i) break;
                     if (*(s++) == '/') {
                         name = s;
                         i++;
                     }
                 }
                 if (del) {
                     printf("removing %s\n", name);
                     xunlink(name);
                     state = 0;
                 // If we've got a file to open, do so.
                 } else if (!(option_mask32 & FLAG_PATHLEN) || i <= TT.prefix) {
                     // If the old file was null, we're creating a new one.
                     if (strcmp(oldname, "/dev/null") == 0 || !oldsum) {
                         printf("creating %s\n", name);
                         s = strrchr(name, '/');
                         if (s) {
                             *s = 0;
                             xmkpath(name, -1);
                             *s = '/';
                         }
                         TT.filein = xopen(name, O_CREAT|O_EXCL|O_RDWR);
                     } else {
                         printf("patching file %s\n", name);
                         TT.filein = xopen(name, O_RDWR);
                     }
                     TT.fileout = copy_tempfile(TT.filein, name, &TT.tempname);
                     TT.linenum = 0;
                     TT.hunknum = 0;
                 }
             }
             TT.hunknum++;
             continue;
         }
         // If we didn't continue above, discard this line.
         free(patchline);
     }
     finish_oldfile();
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(TT.filepatch);
         free(oldname);
         free(newname);
     }
     return TT.exitval;
 }
References apply_one_hunk(), argv, atoi(), bb_error_msg_and_die(), close(), copy_tempfile(), dlist_add(), fail_hunk(), finish_oldfile(), FLAG_INPUT, FLAG_PATHLEN, FLAG_REVERSE, FLAG_STR, free, get_line(), getopt32(), i, INIT_TT, NULL, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, option_mask32, printf, reverse(), s, sscanf(), state, strcmp, strncmp(), strrchr(), TT, xmkpath(), xopen(), xstrdup(), and xunlink().
replace_tempfile()
static void replace_tempfile (int fdin, int fdout, char ** tempname) static
Definition at line 178 of file patch_toybox.c.
 {
     char *temp = xstrdup(*tempname);
     temp[strlen(temp)-6] = 0;
     if (fdin != -1) {
         xsendfile(fdin, fdout);
         xclose(fdin);
     }
     xclose(fdout);
     rename(*tempname, temp);
     free(*tempname);
     free(temp);
     *tempname = NULL;
 }
References free, NULL, rename(), strlen(), xclose(), xsendfile(), and xstrdup().
Referenced by finish_oldfile().
TOY_llist_free()
static void TOY_llist_free (void * list, void(*)(void *data) freeit) static
Definition at line 74 of file patch_toybox.c.
 {
     while (list) {
         void *pop = TOY_llist_pop(&list);
         if (freeit) freeit(pop);
         else free(pop);
         // End doubly linked list too.
         if (list == pop) break;
     }
 }
References free, list(), pop(), and TOY_llist_pop().
Referenced by apply_one_hunk(), and fail_hunk().
TOY_llist_pop()
static void* TOY_llist_pop (void * list) static
Definition at line 59 of file patch_toybox.c.
 {
     // I'd use a void ** for the argument, and even accept the typecast in all
     // callers as documentation you need the &, except the stupid compiler
     // would then scream about type-punned pointers.  Screw it.
     void **llist = (void **)list;
     void **next = (void **)*llist;
     *llist = *next;
     return (void *)next;
 }
References list(), and next.
Referenced by apply_one_hunk(), and TOY_llist_free().
xmkpath()
static void xmkpath (char * path, int mode) static
Definition at line 107 of file patch_toybox.c.
 {
     char *p, old;
     mode_t mask;
     int rc;
     struct stat st;
     for (p = path; ; p++) {
         if (!*p || *p == '/') {
             old = *p;
             *p = rc = 0;
             if (stat(path, &st) || !S_ISDIR(st.st_mode)) {
                 if (mode != -1) {
                     mask = umask(0);
                     rc = mkdir(path, mode);
                     umask(mask);
                 } else rc = mkdir(path, 0777);
             }
             *p = old;
             if(rc) bb_perror_msg_and_die("mkpath '%s'", path);
         }
         if (!*p) break;
     }
 }
References bb_perror_msg_and_die(), mkdir(), mode_t, old, p, rc, S_ISDIR, stat(), and umask().
Referenced by patch_main().
xsendfile()
static void xsendfile (int in, int out) static
Definition at line 163 of file patch_toybox.c.
 {
     long len;
     char buf[4096];
     if (in < 0) return;
     for (;;) {
         len = safe_read(in, buf, 4096);
         if (len < 1) break;
         xwrite(out, buf, len);
     }
 }
References buf, len, out(), safe_read(), and xwrite().
Referenced by replace_tempfile().