Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/net_query.h File Reference
net_query.h File Reference
#include "net_defs.h"
Typedefs
typedef void(* net_query_callback_t) (net_addr_t *addr, net_querydata_t *querydata, unsigned int ping_time, void *user_data)
Functions
int NET_StartLANQuery (void)
int NET_StartMasterQuery (void)
void NET_LANQuery (void)
void NET_MasterQuery (void)
void NET_QueryAddress (char *addr)
net_addr_t * NET_FindLANServer (void)
int NET_Query_Poll (net_query_callback_t callback, void *user_data)
net_addr_t * NET_Query_ResolveMaster (net_context_t *context)
void NET_Query_AddToMaster (net_addr_t *master_addr)
boolean NET_Query_CheckAddedToMaster (boolean *result)
void NET_Query_MasterResponse (net_packet_t *packet)
Typedef Documentation
net_query_callback_t
typedef void(* net_query_callback_t) (net_addr_t *addr, net_querydata_t *querydata, unsigned int ping_time, void *user_data)
Definition at line 23 of file net_query.h.
Function Documentation
NET_FindLANServer()
net_addr_t* NET_FindLANServer (void)
Referenced by D_InitNetGame().
NET_LANQuery()
void NET_LANQuery (void)
Referenced by D_DoomMain().
NET_MasterQuery()
void NET_MasterQuery (void)
Referenced by D_DoomMain().
NET_Query_AddToMaster()
void NET_Query_AddToMaster (net_addr_t * master_addr)
NET_Query_CheckAddedToMaster()
boolean NET_Query_CheckAddedToMaster (boolean * result)
NET_Query_MasterResponse()
void NET_Query_MasterResponse (net_packet_t * packet)
NET_Query_Poll()
int NET_Query_Poll (net_query_callback_t callback, void * user_data)
NET_Query_ResolveMaster()
net_addr_t* NET_Query_ResolveMaster (net_context_t * context)
NET_QueryAddress()
void NET_QueryAddress (char * addr)
Referenced by D_DoomMain().
NET_StartLANQuery()
int NET_StartLANQuery (void)
NET_StartMasterQuery()
int NET_StartMasterQuery (void)