Fennix: Userspace/apps/base/busybox/examples/shutdown-1.0/script/hardshutdown.c File Reference
hardshutdown.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
Macros
#define LINUX_REBOOT_MAGIC1 0xfee1dead
#define LINUX_REBOOT_MAGIC2 672274793
#define LINUX_REBOOT_MAGIC2A 85072278
#define LINUX_REBOOT_MAGIC2B 369367448
#define LINUX_REBOOT_CMD_RESTART 0x01234567
#define LINUX_REBOOT_CMD_HALT 0xCDEF0123
#define LINUX_REBOOT_CMD_CAD_ON 0x89ABCDEF
#define LINUX_REBOOT_CMD_CAD_OFF 0x00000000
#define LINUX_REBOOT_CMD_POWER_OFF 0x4321FEDC
#define LINUX_REBOOT_CMD_RESTART2 0xA1B2C3D4
#define USE_LIBC
#define REBOOT(cmd) reboot(LINUX_REBOOT_MAGIC1,LINUX_REBOOT_MAGIC2,(cmd))
Enumerations
enum action_t { SHUTDOWN , HALT , POWEROFF , REBOOT }
Functions
int reboot (int, int, int)
static int my_reboot (int cmd)
static void do_reboot (void)
static void do_poweroff (void)
static void do_halt (void)
static void usage (void)
int main (int argc, char **argv)
Macro Definition Documentation
LINUX_REBOOT_CMD_CAD_OFF
#define LINUX_REBOOT_CMD_CAD_OFF 0x00000000
Definition at line 33 of file hardshutdown.c.
LINUX_REBOOT_CMD_CAD_ON
#define LINUX_REBOOT_CMD_CAD_ON 0x89ABCDEF
Definition at line 32 of file hardshutdown.c.
LINUX_REBOOT_CMD_HALT
#define LINUX_REBOOT_CMD_HALT 0xCDEF0123
Definition at line 31 of file hardshutdown.c.
LINUX_REBOOT_CMD_POWER_OFF
#define LINUX_REBOOT_CMD_POWER_OFF 0x4321FEDC
Definition at line 34 of file hardshutdown.c.
LINUX_REBOOT_CMD_RESTART
#define LINUX_REBOOT_CMD_RESTART 0x01234567
Definition at line 30 of file hardshutdown.c.
LINUX_REBOOT_CMD_RESTART2
#define LINUX_REBOOT_CMD_RESTART2 0xA1B2C3D4
Definition at line 35 of file hardshutdown.c.
LINUX_REBOOT_MAGIC1
#define LINUX_REBOOT_MAGIC1 0xfee1dead
Definition at line 16 of file hardshutdown.c.
LINUX_REBOOT_MAGIC2
#define LINUX_REBOOT_MAGIC2 672274793
Definition at line 17 of file hardshutdown.c.
LINUX_REBOOT_MAGIC2A
#define LINUX_REBOOT_MAGIC2A 85072278
Definition at line 18 of file hardshutdown.c.
LINUX_REBOOT_MAGIC2B
#define LINUX_REBOOT_MAGIC2B 369367448
Definition at line 19 of file hardshutdown.c.
REBOOT
#define REBOOT (cmd) reboot(LINUX_REBOOT_MAGIC1,LINUX_REBOOT_MAGIC2,(cmd))
Definition at line 48 of file hardshutdown.c.
USE_LIBC
#define USE_LIBC
Definition at line 38 of file hardshutdown.c.
Enumeration Type Documentation
action_t
enum action_t
Enumerator
SHUTDOWN
HALT
POWEROFF
REBOOT
Definition at line 98 of file hardshutdown.c.
               {
     SHUTDOWN,   // do nothing
     HALT,
     POWEROFF,
     REBOOT
 };
Function Documentation
do_halt()
static void do_halt (void) static
Definition at line 84 of file hardshutdown.c.
 {
     my_reboot(LINUX_REBOOT_CMD_HALT);
 }
References LINUX_REBOOT_CMD_HALT, and my_reboot().
Referenced by main().
do_poweroff()
static void do_poweroff (void) static
Definition at line 80 of file hardshutdown.c.
 {
     my_reboot(LINUX_REBOOT_CMD_POWER_OFF);
 }
References LINUX_REBOOT_CMD_POWER_OFF, and my_reboot().
Referenced by main().
do_reboot()
static void do_reboot (void) static
Definition at line 76 of file hardshutdown.c.
 {
     my_reboot(LINUX_REBOOT_CMD_RESTART);
 }
References LINUX_REBOOT_CMD_RESTART, and my_reboot().
Referenced by main().
main()
int main (int argc , char ** argv)
Definition at line 105 of file hardshutdown.c.
 {
     struct timespec t = {0,0};
     enum action_t action = SHUTDOWN;
     int c, i;
     char *prog, *ptr;
     //if (*argv[0] == '-') argv[0]++; /* allow shutdown as login shell */
     prog = argv[0];
     ptr = strrchr(prog,'/');
     if (ptr)
         prog = ptr+1;
     for (c = 1; c < argc; c++) {
         if (argv[c][0] >= '0' && argv[c][0] <= '9') {
             t.tv_sec = strtol(argv[c], NULL, 10);
             continue;
         }
         if (argv[c][0] != '-') {
             usage();
             return 1;
         }
         for (i = 1; argv[c][i]; i++) {
             switch (argv[c][i]) {
             case 'h':
                 action = HALT;
                 break;
             case 'p':
                 action = POWEROFF;
                 break;
             case 'r':
                 action = REBOOT;
                 break;
             default:
                 usage();
                 return 1;
             }
         }
     }
     if (action==SHUTDOWN) {
         usage();
         return 1;
     }
     chdir("/");
     while (nanosleep(&t,&t)<0)
         if (errno!=EINTR) break;
     switch (action) {
     case HALT:
         do_halt();
         break;
     case POWEROFF:
         do_poweroff();
         break;
     case REBOOT:
         do_reboot();
         break;
     default: /* SHUTDOWN */
         break;
     }
     return 1;
 }
References argc, argv, c, chdir(), do_halt(), do_poweroff(), do_reboot(), EINTR, errno, HALT, i, nanosleep(), NULL, POWEROFF, prog, REBOOT, SHUTDOWN, strrchr(), strtol(), t, and usage().
my_reboot()
static int my_reboot (int cmd) static
Definition at line 51 of file hardshutdown.c.
 {
     return REBOOT(cmd);
 }
References cmd, and REBOOT.
Referenced by do_halt(), do_poweroff(), and do_reboot().
reboot()
int reboot (int , int , int)
Referenced by exec_restart_action(), halt_main(), init_main(), pause_and_low_level_reboot(), reboot_linux(), and shutdown_linux().
usage()
static void usage (void) static
Definition at line 89 of file hardshutdown.c.
 {
     puts(
         "Usage: hardshutdown -h|-r|-p [NN]\n"
         "   NN - seconds to sleep before requested action"
     );
     exit(1);
 }
References exit(), and puts().
Referenced by main().