Fennix: Userspace/mlibc/options/ansi/musl-generic-math/__rem_pio2_large.c File Reference
__rem_pio2_large.c File Reference
#include "libm.h"
Functions
int __rem_pio2_large (double *x, double *y, int e0, int nx, int prec)
Variables
static const int init_jk [] = {3,4,4,6}
static const int32_t ipio2 []
static const double PIo2 []
Function Documentation
__rem_pio2_large()
int __rem_pio2_large (double * x, double * y, int e0, int nx, int prec)
Definition at line 273 of file __rem_pio2_large.c.
 {
     int32_t jz,jx,jv,jp,jk,carry,n,iq[20],i,j,k,m,q0,ih;
     double z,fw,f[20],fq[20],q[20];
     /* initialize jk*/
     jk = init_jk[prec];
     jp = jk;
     /* determine jx,jv,q0, note that 3>q0 */
     jx = nx-1;
     jv = (e0-3)/24;  if(jv<0) jv=0;
     q0 = e0-24*(jv+1);
     /* set up f[0] to f[jx+jk] where f[jx+jk] = ipio2[jv+jk] */
     j = jv-jx; m = jx+jk;
     for (i=0; i<=m; i++,j++)
         f[i] = j<0 ? 0.0 : (double)ipio2[j];
     /* compute q[0],q[1],...q[jk] */
     for (i=0; i<=jk; i++) {
         for (j=0,fw=0.0; j<=jx; j++)
             fw += x[j]*f[jx+i-j];
         q[i] = fw;
     }
     jz = jk;
 recompute:
     /* distill q[] into iq[] reversingly */
     for (i=0,j=jz,z=q[jz]; j>0; i++,j--) {
         fw    = (double)(int32_t)(0x1p-24*z);
         iq[i] = (int32_t)(z - 0x1p24*fw);
         z     = q[j-1]+fw;
     }
     /* compute n */
     z  = scalbn(z,q0);       /* actual value of z */
     z -= 8.0*floor(z*0.125); /* trim off integer >= 8 */
     n  = (int32_t)z;
     z -= (double)n;
     ih = 0;
     if (q0 > 0) {  /* need iq[jz-1] to determine n */
         i  = iq[jz-1]>>(24-q0); n += i;
         iq[jz-1] -= i<<(24-q0);
         ih = iq[jz-1]>>(23-q0);
     }
     else if (q0 == 0) ih = iq[jz-1]>>23;
     else if (z >= 0.5) ih = 2;
     if (ih > 0) {  /* q > 0.5 */
         n += 1; carry = 0;
         for (i=0; i<jz; i++) {  /* compute 1-q */
             j = iq[i];
             if (carry == 0) {
                 if (j != 0) {
                     carry = 1;
                     iq[i] = 0x1000000 - j;
                 }
             } else
                 iq[i] = 0xffffff - j;
         }
         if (q0 > 0) {  /* rare case: chance is 1 in 12 */
             switch(q0) {
             case 1:
                 iq[jz-1] &= 0x7fffff; break;
             case 2:
                 iq[jz-1] &= 0x3fffff; break;
             }
         }
         if (ih == 2) {
             z = 1.0 - z;
             if (carry != 0)
                 z -= scalbn(1.0,q0);
         }
     }
     /* check if recomputation is needed */
     if (z == 0.0) {
         j = 0;
         for (i=jz-1; i>=jk; i--) j |= iq[i];
         if (j == 0) {  /* need recomputation */
             for (k=1; iq[jk-k]==0; k++);  /* k = no. of terms needed */
             for (i=jz+1; i<=jz+k; i++) {  /* add q[jz+1] to q[jz+k] */
                 f[jx+i] = (double)ipio2[jv+i];
                 for (j=0,fw=0.0; j<=jx; j++)
                     fw += x[j]*f[jx+i-j];
                 q[i] = fw;
             }
             jz += k;
             goto recompute;
         }
     }
     /* chop off zero terms */
     if (z == 0.0) {
         jz -= 1;
         q0 -= 24;
         while (iq[jz] == 0) {
             jz--;
             q0 -= 24;
         }
     } else { /* break z into 24-bit if necessary */
         z = scalbn(z,-q0);
         if (z >= 0x1p24) {
             fw = (double)(int32_t)(0x1p-24*z);
             iq[jz] = (int32_t)(z - 0x1p24*fw);
             jz += 1;
             q0 += 24;
             iq[jz] = (int32_t)fw;
         } else
             iq[jz] = (int32_t)z;
     }
     /* convert integer "bit" chunk to floating-point value */
     fw = scalbn(1.0,q0);
     for (i=jz; i>=0; i--) {
         q[i] = fw*(double)iq[i];
         fw *= 0x1p-24;
     }
     /* compute PIo2[0,...,jp]*q[jz,...,0] */
     for(i=jz; i>=0; i--) {
         for (fw=0.0,k=0; k<=jp && k<=jz-i; k++)
             fw += PIo2[k]*q[i+k];
         fq[jz-i] = fw;
     }
     /* compress fq[] into y[] */
     switch(prec) {
     case 0:
         fw = 0.0;
         for (i=jz; i>=0; i--)
             fw += fq[i];
         y[0] = ih==0 ? fw : -fw;
         break;
     case 1:
     case 2:
         fw = 0.0;
         for (i=jz; i>=0; i--)
             fw += fq[i];
         // TODO: drop excess precision here once double_t is used
         fw = (double)fw;
         y[0] = ih==0 ? fw : -fw;
         fw = fq[0]-fw;
         for (i=1; i<=jz; i++)
             fw += fq[i];
         y[1] = ih==0 ? fw : -fw;
         break;
     case 3:  /* painful */
         for (i=jz; i>0; i--) {
             fw      = fq[i-1]+fq[i];
             fq[i]  += fq[i-1]-fw;
             fq[i-1] = fw;
         }
         for (i=jz; i>1; i--) {
             fw      = fq[i-1]+fq[i];
             fq[i]  += fq[i-1]-fw;
             fq[i-1] = fw;
         }
         for (fw=0.0,i=jz; i>=2; i--)
             fw += fq[i];
         if (ih==0) {
             y[0] =  fq[0]; y[1] =  fq[1]; y[2] =  fw;
         } else {
             y[0] = -fq[0]; y[1] = -fq[1]; y[2] = -fw;
         }
     }
     return n&7;
 }
References floor(), i, init_jk, ipio2, j, k, n, PIo2, scalbn(), x, and y.
Referenced by __rem_pio2(), and __rem_pio2f().
Variable Documentation
init_jk
const int init_jk[] = {3,4,4,6} static
Definition at line 127 of file __rem_pio2_large.c.
Referenced by __rem_pio2_large().
ipio2
const int32_t ipio2[] static
Definition at line 141 of file __rem_pio2_large.c.
Referenced by __rem_pio2_large().
PIo2
const double PIo2[] static
Initial value:
= {
  1.57079625129699707031e+00,
  7.54978941586159635335e-08,
  5.39030252995776476554e-15,
  3.28200341580791294123e-22,
  1.27065575308067607349e-29,
  1.22933308981111328932e-36,
  2.73370053816464559624e-44,
  2.16741683877804819444e-51,
}
Definition at line 262 of file __rem_pio2_large.c.
Referenced by __rem_pio2_large().