Fennix: ElementHandle Struct Reference
ElementHandle Struct Reference
#include <posix-pipe.hpp>
Public Member Functions
ElementHandle ()
ElementHandle (Queue *queue, int n, void *data)
ElementHandle (const ElementHandle &other)
ElementHandle (ElementHandle &&other)
~ElementHandle ()
ElementHandle & operator= (ElementHandle other)
void * data ()
void advance (size_t size)
Private Attributes
Queue * _queue
int _n
void * _data
Friends
void swap (ElementHandle &u, ElementHandle &v)
Detailed Description
Definition at line 28 of file posix-pipe.hpp.
Constructor & Destructor Documentation
ElementHandle() [1/4]
ElementHandle::ElementHandle () inline
Definition at line 36 of file posix-pipe.hpp.
     : _queue{nullptr}, _n{-1}, _data{nullptr} { }
ElementHandle() [2/4]
ElementHandle::ElementHandle (Queue * queue, int n, void * data) inline
Definition at line 39 of file posix-pipe.hpp.
     : _queue{queue}, _n{n}, _data{data} { }
ElementHandle() [3/4]
ElementHandle::ElementHandle (const ElementHandle & other) inline
Definition at line 238 of file posix-pipe.hpp.
{
     _queue = other._queue;
     _n = other._n;
     _data = other._data;
     _queue->reference(_n);
 }
References _data, _n, _queue, and Queue::reference().
ElementHandle() [4/4]
ElementHandle::ElementHandle (ElementHandle && other) inline
Definition at line 44 of file posix-pipe.hpp.
     : ElementHandle{} {
         swap(*this, other);
     }
References swap.
~ElementHandle()
ElementHandle::~ElementHandle () inline
Definition at line 233 of file posix-pipe.hpp.
{
     if(_queue)
         _queue->retire(_n);
 }
References _n, _queue, and Queue::retire().
Member Function Documentation
advance()
void ElementHandle::advance (size_t size) inline
Definition at line 60 of file posix-pipe.hpp.
{
         _data = reinterpret_cast<char *>(_data) + size;
     }
References _data, and size.
Referenced by parseHandle(), parseInline(), parseLength(), and parseSimple().
data()
void* ElementHandle::data () inline
Definition at line 56 of file posix-pipe.hpp.
                  {
         return _data;
     }
References _data.
Referenced by exchangeMsgsSync(), parseHandle(), parseInline(), parseLength(), and parseSimple().
operator=()
ElementHandle& ElementHandle::operator= (ElementHandle other) inline
Definition at line 51 of file posix-pipe.hpp.
{
         swap(*this, other);
         return *this;
     }
References swap.
Friends And Related Function Documentation
swap
void swap (ElementHandle & u, ElementHandle & v) friend
Definition at line 29 of file posix-pipe.hpp.
{
         using std::swap;
         swap(u._queue, v._queue);
         swap(u._n, v._n);
         swap(u._data, v._data);
     }
Referenced by ElementHandle(), and operator=().
Field Documentation
_data
void* ElementHandle::_data private
Definition at line 67 of file posix-pipe.hpp.
Referenced by advance(), data(), and ElementHandle().
_n
int ElementHandle::_n private
Definition at line 66 of file posix-pipe.hpp.
Referenced by ElementHandle(), and ~ElementHandle().
_queue
Queue* ElementHandle::_queue private
Definition at line 65 of file posix-pipe.hpp.
Referenced by ElementHandle(), and ~ElementHandle().
The documentation for this struct was generated from the following file:
Userspace/mlibc/sysdeps/managarm/include/mlibc/posix-pipe.hpp