Fennix: Userspace/apps/base/busybox/networking/isrv_identd.c File Reference
isrv_identd.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <syslog.h>
#include "isrv.h"
Data Structures
struct identd_buf_t
Macros
#define bogouser bb_common_bufsiz1
Typedefs
typedef struct identd_buf_t identd_buf_t
Enumerations
enum { TIMEOUT = 20 }
Functions
static int new_peer (isrv_state_t *state, int fd)
static int do_rd (int fd, void **paramp)
static int do_timeout (void **paramp UNUSED_PARAM)
static void inetd_mode (void)
int fakeidentd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
identd_buf_t
struct identd_buf_t
Definition at line 38 of file isrv_identd.c.
Data Fields
char buf[64 - sizeof(int)]
int pos
Macro Definition Documentation
bogouser
#define bogouser bb_common_bufsiz1
Definition at line 43 of file isrv_identd.c.
Typedef Documentation
identd_buf_t
typedef struct identd_buf_t identd_buf_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TIMEOUT
Definition at line 36 of file isrv_identd.c.
 { TIMEOUT = 20 };
Function Documentation
do_rd()
static int do_rd (int fd, void ** paramp) static
Definition at line 61 of file isrv_identd.c.
 {
     identd_buf_t *buf = *paramp;
     char *cur, *p;
     int sz;
     cur = buf->buf + buf->pos;
     sz = safe_read(fd, cur, sizeof(buf->buf) - 1 - buf->pos);
     if (sz < 0) {
         if (errno != EAGAIN)
             goto term;
         return 0; /* "session is ok" */
     }
     buf->pos += sz;
     buf->buf[buf->pos] = '\0';
     p = strpbrk(cur, "\r\n");
     if (p)
         *p = '\0';
     if (!p && sz)
         return 0;  /* "session is ok" */
     /* Terminate session. If we are in server mode, then
      * fd is still in nonblocking mode - we never block here */
     if (fd == 0)
         fd++; /* inetd mode? then write to fd 1 */
     fdprintf(fd, "%s : USERID : UNIX : %s\r\n", buf->buf, bogouser);
     /*
      * Why bother if we are going to close fd now anyway?
      * if (server)
      *  ndelay_off(fd);
      */
  term:
     free(buf);
     return 1; /* "terminate" */
 }
References bogouser, buf, cur, EAGAIN, errno, fd, fdprintf, free, p, safe_read(), strpbrk(), and term.
Referenced by fakeidentd_main(), inetd_mode(), and isrv_run().
do_timeout()
static int do_timeout (void **paramp UNUSED_PARAM) static
Definition at line 100 of file isrv_identd.c.
 {
     return 1; /* terminate session */
 }
Referenced by fakeidentd_main(), handle_timeout(), and isrv_run().
fakeidentd_main()
int fakeidentd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 116 of file isrv_identd.c.
 {
     enum {
         OPT_foreground = 0x1,
         OPT_inetd      = 0x2,
         OPT_inetdwait  = 0x4,
         OPT_fiw        = 0x7,
         OPT_bindaddr   = 0x8,
     };
     const char *bind_address = NULL;
     unsigned opt;
     int fd;
     setup_common_bufsiz();
     opt = getopt32(argv, "fiwb:", &bind_address);
     strcpy(bogouser, "nobody");
     if (argv[optind])
         strncpy(bogouser, argv[optind], COMMON_BUFSIZE - 1);
     /* Daemonize if no -f and no -i and no -w */
     if (!(opt & OPT_fiw))
         bb_daemonize_or_rexec(0, argv);
     /* Where to log in inetd modes? "Classic" inetd
      * probably has its stderr /dev/null'ed (we need log to syslog?),
      * but daemontools-like utilities usually expect that children
      * log to stderr. I like daemontools more. Go their way.
      * (Or maybe we need yet another option "log to syslog") */
     if (!(opt & OPT_fiw) /* || (opt & OPT_syslog) */) {
         openlog(applet_name, LOG_PID, LOG_DAEMON);
         logmode = LOGMODE_SYSLOG;
     }
     if (opt & OPT_inetd) {
         inetd_mode();
         return 0;
     }
     /* Ignore closed connections when writing */
     signal(SIGPIPE, SIG_IGN);
     fd = 0;
     if (!(opt & OPT_inetdwait)) {
         fd = create_and_bind_stream_or_die(bind_address,
                 bb_lookup_std_port("identd", "tcp", 113));
         xlisten(fd, 5);
     }
     isrv_run(fd, new_peer, do_rd, /*do_wr:*/ NULL, do_timeout,
             TIMEOUT, (opt & OPT_inetdwait) ? TIMEOUT : 0);
     return 0;
 }
References applet_name, argv, bb_daemonize_or_rexec, bb_lookup_std_port, bogouser, create_and_bind_stream_or_die(), do_rd(), do_timeout(), fd, getopt32(), inetd_mode(), isrv_run(), LOG_DAEMON, LOG_PID, logmode, LOGMODE_SYSLOG, new_peer(), NULL, openlog(), opt, optind, SIG_IGN, signal, SIGPIPE, strcpy, strncpy(), TIMEOUT, and xlisten().
inetd_mode()
static void inetd_mode (void) static
Definition at line 105 of file isrv_identd.c.
 {
     identd_buf_t *buf = xzalloc(sizeof(*buf));
     /* buf->pos = 0; - xzalloc did it */
     do
         alarm(TIMEOUT);
         /* Note: we do NOT want nonblocking I/O here! */
     while (do_rd(0, (void*)&buf) == 0);
 }
References alarm(), buf, do_rd(), TIMEOUT, and xzalloc().
Referenced by fakeidentd_main().
new_peer()
static int new_peer (isrv_state_t * state, int fd) static
Definition at line 45 of file isrv_identd.c.
 {
     int peer;
     identd_buf_t *buf = xzalloc(sizeof(*buf));
     peer = isrv_register_peer(state, buf);
     if (peer < 0)
         return 0; /* failure */
     if (isrv_register_fd(state, peer, fd) < 0)
         return peer; /* failure, unregister peer */
     ndelay_on(fd);
     isrv_want_rd(state, fd);
     return 0;
 }
References buf, fd, isrv_register_fd(), isrv_register_peer(), isrv_want_rd(), ndelay_on(), peer, state, and xzalloc().
Referenced by fakeidentd_main(), and isrv_run().