Fennix Userspace: Userspace/apps/base/busybox/coreutils/readlink.c File Reference
readlink.c File Reference
#include "libbb.h"
Functions
int readlink_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
readlink_main()
int readlink_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 66 of file readlink.c.
 {
     char *buf;
     char *fname;
     IF_FEATURE_READLINK_FOLLOW(
         unsigned opt;
         /* We need exactly one non-option argument.  */
         opt = getopt32(argv, "^" "fnvsq" "\0" "=1");
         fname = argv[optind];
     )
     IF_NOT_FEATURE_READLINK_FOLLOW(
         const unsigned opt = 0;
         if (argc != 2) bb_show_usage();
         fname = argv[1];
     )
     /* compat: coreutils readlink reports errors silently via exit code */
     if (!(opt & 4)) /* not -v */
         logmode = LOGMODE_NONE;
     /* NOFORK: only one alloc is allowed; must free */
     if (opt & 1) { /* -f */
         buf = xmalloc_realpath_coreutils(fname);
     } else {
         buf = xmalloc_readlink_or_warn(fname);
     }
     if (!buf)
         return EXIT_FAILURE;
     printf((opt & 2) ? "%s" : "%s\n", buf);
     free(buf);
     fflush_stdout_and_exit_SUCCESS();
 }
References argc, argv, bb_show_usage(), buf, EXIT_FAILURE, fflush_stdout_and_exit_SUCCESS(), fname, free, getopt32(), logmode, LOGMODE_NONE, opt, optind, printf(), xmalloc_readlink_or_warn(), and xmalloc_realpath_coreutils().