Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/st_lib.h File Reference
st_lib.h File Reference
#include "r_defs.h"
Data Structures
struct st_number_t
struct st_percent_t
struct st_multicon_t
struct st_binicon_t
Functions
void STlib_init (void)
void STlib_initNum (st_number_t *n, int x, int y, patch_t **pl, int *num, boolean *on, int width)
void STlib_updateNum (st_number_t *n, boolean refresh)
void STlib_initPercent (st_percent_t *p, int x, int y, patch_t **pl, int *num, boolean *on, patch_t *percent)
void STlib_updatePercent (st_percent_t *per, int refresh)
void STlib_initMultIcon (st_multicon_t *mi, int x, int y, patch_t **il, int *inum, boolean *on)
void STlib_updateMultIcon (st_multicon_t *mi, boolean refresh)
void STlib_initBinIcon (st_binicon_t *b, int x, int y, patch_t *i, boolean *val, boolean *on)
void STlib_updateBinIcon (st_binicon_t *bi, boolean refresh)
Data Structure Documentation
st_number_t
struct st_number_t
Definition at line 32 of file st_lib.h.
Data Fields
int data
int * num
int oldnum
boolean * on
patch_t ** p
int width
int x
int y
st_percent_t
struct st_percent_t
Definition at line 64 of file st_lib.h.
Data Fields
st_number_t n
patch_t * p
st_multicon_t
struct st_multicon_t
Definition at line 77 of file st_lib.h.
Data Fields
int data
int * inum
int oldinum
boolean * on
patch_t ** p
int x
int y
st_binicon_t
struct st_binicon_t
Definition at line 106 of file st_lib.h.
Data Fields
int data
boolean oldval
boolean * on
patch_t * p
boolean * val
int x
int y
Function Documentation
STlib_init()
void STlib_init (void)
Definition at line 51 of file st_lib.c.
 {
     sttminus = (patch_t *) W_CacheLumpName(DEH_String("STTMINUS"), PU_STATIC);
 }
References DEH_String, PU_STATIC, sttminus, and W_CacheLumpName().
Referenced by ST_initData().
STlib_initBinIcon()
void STlib_initBinIcon (st_binicon_t * b, int x, int y, patch_t * i, boolean * val, boolean * on)
Definition at line 236 of file st_lib.c.
 {
     b->x    = x;
     b->y    = y;
     b->oldval   = false;
     b->val  = val;
     b->on   = on;
     b->p    = i;
 }
References b, i, x, and y.
Referenced by ST_createWidgets().
STlib_initMultIcon()
void STlib_initMultIcon (st_multicon_t * mi, int x, int y, patch_t ** il, int * inum, boolean * on)
Definition at line 186 of file st_lib.c.
 {
     i->x    = x;
     i->y    = y;
     i->oldinum  = -1;
     i->inum = inum;
     i->on   = on;
     i->p    = il;
 }
References i, x, and y.
Referenced by ST_createWidgets().
STlib_initNum()
void STlib_initNum (st_number_t * n, int x, int y, patch_t ** pl, int * num, boolean * on, int width)
Definition at line 59 of file st_lib.c.
 {
     n->x    = x;
     n->y    = y;
     n->oldnum   = 0;
     n->width    = width;
     n->num  = num;
     n->on   = on;
     n->p    = pl;
 }
References n, num, x, and y.
Referenced by ST_createWidgets(), and STlib_initPercent().
STlib_initPercent()
void STlib_initPercent (st_percent_t * p, int x, int y, patch_t ** pl, int * num, boolean * on, patch_t * percent)
Definition at line 156 of file st_lib.c.
 {
     STlib_initNum(&p->n, x, y, pl, num, on, 3);
     p->p = percent;
 }
References p, percent, STlib_initNum(), x, and y.
Referenced by ST_createWidgets().
STlib_updateBinIcon()
void STlib_updateBinIcon (st_binicon_t * bi, boolean refresh)
Definition at line 255 of file st_lib.c.
 {
     int         x;
     int         y;
     int         w;
     int         h;
     if (*bi->on
      && (bi->oldval != *bi->val || refresh))
     {
     x = bi->x - SHORT(bi->p->leftoffset);
     y = bi->y - SHORT(bi->p->topoffset);
     w = SHORT(bi->p->width);
     h = SHORT(bi->p->height);
     if (y - ST_Y < 0)
         I_Error("updateBinIcon: y - ST_Y < 0");
     if (*bi->val)
         V_DrawPatch(bi->x, bi->y, bi->p);
     else
         V_CopyRect(x, y-ST_Y, st_backing_screen, w, h, x, y);
     bi->oldval = *bi->val;
     }
 }
References I_Error(), st_binicon_t::oldval, st_binicon_t::on, st_binicon_t::p, st_backing_screen, ST_Y, V_CopyRect(), V_DrawPatch(), st_binicon_t::val, st_binicon_t::x, x, y, and st_binicon_t::y.
Referenced by ST_drawWidgets().
STlib_updateMultIcon()
void STlib_updateMultIcon (st_multicon_t * mi, boolean refresh)
Definition at line 205 of file st_lib.c.
 {
     int         w;
     int         h;
     int         x;
     int         y;
     if (*mi->on && (mi->oldinum != *mi->inum || refresh) && (*mi->inum != -1))
     {
     if (mi->oldinum != -1)
     {
         x = mi->x - SHORT(mi->p[mi->oldinum]->leftoffset);
         y = mi->y - SHORT(mi->p[mi->oldinum]->topoffset);
         w = SHORT(mi->p[mi->oldinum]->width);
         h = SHORT(mi->p[mi->oldinum]->height);
         if (y - ST_Y < 0)
         I_Error("updateMultIcon: y - ST_Y < 0");
         V_CopyRect(x, y-ST_Y, st_backing_screen, w, h, x, y);
     }
     V_DrawPatch(mi->x, mi->y, mi->p[*mi->inum]);
     mi->oldinum = *mi->inum;
     }
 }
References I_Error(), st_multicon_t::inum, st_multicon_t::oldinum, st_multicon_t::on, st_multicon_t::p, st_backing_screen, ST_Y, V_CopyRect(), V_DrawPatch(), st_multicon_t::x, x, y, and st_multicon_t::y.
Referenced by ST_drawWidgets().
STlib_updateNum()
void STlib_updateNum (st_number_t * n, boolean refresh)
Definition at line 146 of file st_lib.c.
 {
     if (*n->on) STlib_drawNum(n, refresh);
 }
References n, and STlib_drawNum().
Referenced by ST_drawWidgets(), and STlib_updatePercent().
STlib_updatePercent()
void STlib_updatePercent (st_percent_t * per, int refresh)
Definition at line 173 of file st_lib.c.
 {
     if (refresh && *per->n.on)
     V_DrawPatch(per->n.x, per->n.y, per->p);
     STlib_updateNum(&per->n, refresh);
 }
References st_percent_t::n, st_number_t::on, st_percent_t::p, STlib_updateNum(), V_DrawPatch(), st_number_t::x, and st_number_t::y.
Referenced by ST_drawWidgets().