Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/m_random.h File Reference
m_random.h File Reference
#include "doomtype.h"
Functions
int M_Random (void)
int P_Random (void)
void M_ClearRandom (void)
Function Documentation
M_ClearRandom()
void M_ClearRandom (void)
Definition at line 62 of file m_random.c.
 {
     rndindex = prndindex = 0;
 }
References prndindex, and rndindex.
Referenced by G_InitNew().
M_Random()
int M_Random (void)
Definition at line 56 of file m_random.c.
 {
     rndindex = (rndindex+1)&0xff;
     return rndtable[rndindex];
 }
References rndindex, and rndtable.
Referenced by ST_Ticker(), WI_initAnimatedBack(), WI_updateAnimatedBack(), and wipe_initMelt().
P_Random()
int P_Random (void)
Definition at line 50 of file m_random.c.
 {
     prndindex = (prndindex+1)&0xff;
     return rndtable[prndindex];
 }
References prndindex, and rndtable.
Referenced by A_BFGSpray(), A_BrainExplode(), A_BrainScream(), A_BruisAttack(), A_Chase(), A_CPosAttack(), A_CPosRefire(), A_FaceTarget(), A_FirePlasma(), A_FireShotgun2(), A_HeadAttack(), A_Look(), A_PosAttack(), A_Punch(), A_SargAttack(), A_Saw(), A_Scream(), A_SkelFist(), A_SpawnFly(), A_SpidRefire(), A_SPosAttack(), A_Tracer(), A_TroopAttack(), EV_DoPlat(), G_DeathMatchSpawnPlayer(), P_CheckMissileRange(), P_CheckMissileSpawn(), P_DamageMobj(), P_ExplodeMissile(), P_GunShot(), P_KillMobj(), P_MobjThinker(), P_NewChaseDir(), P_PlayerInSpecialSector(), P_SpawnBlood(), P_SpawnLightFlash(), P_SpawnMapThing(), P_SpawnMissile(), P_SpawnMobj(), P_SpawnPuff(), P_SpawnStrobeFlash(), P_TryWalk(), PIT_ChangeSector(), PIT_CheckThing(), T_FireFlicker(), and T_LightFlash().