Fennix Userspace: Userspace/mlibc/options/posix/include/strings.h File Reference
strings.h File Reference
#include <bits/size_t.h>
Functions
char * index (const char *s, int c)
char * rindex (const char *s, int c)
int ffs (int word)
int strcasecmp (const char *a, const char *b)
int strncasecmp (const char *a, const char *b, size_t size)
Function Documentation
ffs()
int ffs (int word)
Definition at line 44 of file strings-stubs.cpp.
                {
 #ifdef __mlibc_ffs
     return __mlibc_ffs(i);
 #else
     return ffs_generic<int>(i);
 #endif
 }
References i.
Referenced by main().
index()
char* index (const char * s, int c)
Definition at line 9 of file strings-stubs.cpp.
{
     return strchr(s, c);
 }
References c, and strchr().
Referenced by Queue::_numberOf(), if_indextoname(), InterceptsMemoryOverrun(), main(), P_InitSwitchList(), R_MapPlane(), R_ProjectSprite(), R_RenderMaskedSegRange(), R_RenderSegLoop(), resolveInObject(), mlibc::sys_if_indextoname(), mlibc::sys_ptsname(), and anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt().
rindex()
char* rindex (const char * s, int c)
Definition at line 13 of file strings-stubs.cpp.
{
     return strrchr(s, c);
 }
References c, and strrchr().
Referenced by main().
strcasecmp()
int strcasecmp (const char * a, const char * b)
Definition at line 34 of file string.c.
 {
     const unsigned char *p1 = (const unsigned char *)s1;
     const unsigned char *p2 = (const unsigned char *)s2;
     int result;
     if (p1 == p2)
         return 0;
     while ((result = tolower(*p1) - tolower(*p2++)) == 0)
         if (*p1++ == '\0')
             break;
     return result;
 }
References b, i, and tolower.
strncasecmp()
int strncasecmp (const char * a, const char * b, size_t size)
Definition at line 47 of file string.c.
 {
     if (count)
     {
         const unsigned char *s1 = (const unsigned char *)string1;
         const unsigned char *s2 = (const unsigned char *)string2;
         int result;
         do
         {
             if ((result = tolower(*s1) - tolower(*s2++)) != 0 || !*s1++)
                 break;
         } while (--count);
         return result;
     }
     return 0;
 }
References b, size, and mlibc::strncasecmp().