Fennix Userspace: Userspace/musl/compat/time32/fstat_time32.c File Reference
fstat_time32.c File Reference
#include "time32.h"
#include <time.h>
#include <string.h>
#include <sys/stat.h>
#include <stddef.h>
Functions
int __fstat_time32 (int fd, struct stat32 *restrict st32)
Function Documentation
__fstat_time32()
int __fstat_time32 (int fd, struct stat32 *restrict st32)
Definition at line 9 of file fstat_time32.c.
 {
     struct stat st;
     int r = fstat(fd, &st);
     if (!r) memcpy(st32, &st, offsetof(struct stat, st_atim));
     return r;
 }
References fstat(), memcpy(), offsetof, and stat::st_atim.
Referenced by __fxstat().