Fennix Userspace: Userspace/musl/include/shadow.h File Reference
shadow.h File Reference
#include <bits/alltypes.h>
Data Structures
struct spwd
Macros
#define __NEED_FILE
#define __NEED_size_t
#define SHADOW "/etc/shadow"
Functions
void setspent (void)
void endspent (void)
struct spwd * getspent (void)
struct spwd * fgetspent (FILE *)
struct spwd * sgetspent (const char *)
int putspent (const struct spwd *, FILE *)
struct spwd * getspnam (const char *)
int getspnam_r (const char *, struct spwd *, char *, size_t, struct spwd **)
int lckpwdf (void)
int ulckpwdf (void)
Data Structure Documentation
spwd
struct spwd
Definition at line 15 of file shadow.h.
Data Fields
long sp_expire
unsigned long sp_flag
long sp_inact
long sp_lstchg
long sp_max
long sp_min
char * sp_namp
char * sp_pwdp
long sp_warn
Macro Definition Documentation
__NEED_FILE
#define __NEED_FILE
Definition at line 8 of file shadow.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 9 of file shadow.h.
SHADOW
#define SHADOW "/etc/shadow"
Definition at line 13 of file shadow.h.
Function Documentation
endspent()
void endspent (void)
Definition at line 7 of file getspent.c.
 {
 }
fgetspent()
struct spwd* fgetspent (FILE * f)
Definition at line 4 of file fgetspent.c.
 {
     static char *line;
     static struct spwd sp;
     size_t size = 0;
     struct spwd *res = 0;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (getline(&line, &size, f) >= 0 && __parsespent(line, &sp) >= 0) res = &sp;
     pthread_setcancelstate(cs, 0);
     return res;
 }
References __parsespent(), f, getline(), line, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and size.
getspent()
struct spwd* getspent (void)
Definition at line 11 of file getspent.c.
 {
     return 0;
 }
getspnam()
struct spwd* getspnam (const char * name)
Definition at line 5 of file getspnam.c.
 {
     static struct spwd sp;
     static char *line;
     struct spwd *res;
     int e;
     int orig_errno = errno;
     if (!line) line = malloc(LINE_LIM);
     if (!line) return 0;
     e = getspnam_r(name, &sp, line, LINE_LIM, &res);
     errno = e ? e : orig_errno;
     return res;
 }
References errno, getspnam_r(), line, LINE_LIM, and malloc.
getspnam_r()
int getspnam_r (const char * name, struct spwd * sp, char * buf, size_t size, struct spwd ** res)
Definition at line 61 of file getspnam_r.c.
 {
     char path[20+NAME_MAX];
     FILE *f = 0;
     int rv = 0;
     int fd;
     size_t k, l = strlen(name);
     int skip = 0;
     int cs;
     int orig_errno = errno;
     *res = 0;
     /* Disallow potentially-malicious user names */
     if (*name=='.' || strchr(name, '/') || !l)
         return errno = EINVAL;
     /* Buffer size must at least be able to hold name, plus some.. */
     if (size < l+100)
         return errno = ERANGE;
     /* Protect against truncation */
     if (snprintf(path, sizeof path, "/etc/tcb/%s/shadow", name) >= sizeof path)
         return errno = EINVAL;
     fd = open(path, O_RDONLY|O_NOFOLLOW|O_NONBLOCK|O_CLOEXEC);
     if (fd >= 0) {
         struct stat st = { 0 };
         errno = EINVAL;
         if (fstat(fd, &st) || !S_ISREG(st.st_mode) || !(f = fdopen(fd, "rb"))) {
             pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
             close(fd);
             pthread_setcancelstate(cs, 0);
             return errno;
         }
     } else {
         if (errno != ENOENT && errno != ENOTDIR)
             return errno;
         f = fopen("/etc/shadow", "rbe");
         if (!f) {
             if (errno != ENOENT && errno != ENOTDIR)
                 return errno;
             return 0;
         }
     }
     pthread_cleanup_push(cleanup, f);
     while (fgets(buf, size, f) && (k=strlen(buf))>0) {
         if (skip || strncmp(name, buf, l) || buf[l]!=':') {
             skip = buf[k-1] != '\n';
             continue;
         }
         if (buf[k-1] != '\n') {
             rv = ERANGE;
             break;
         }
         if (__parsespent(buf, sp) < 0) continue;
         *res = sp;
         break;
     }
     pthread_cleanup_pop(1);
     errno = rv ? rv : orig_errno;
     return rv;
 }
References __parsespent(), buf, cleanup(), close(), EINVAL, ENOENT, ENOTDIR, ERANGE, errno, f, fgets(), fopen(), fstat(), k, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, O_RDONLY, open(), PTHREAD_CANCEL_DISABLE, pthread_cleanup_pop, pthread_cleanup_push, pthread_setcancelstate(), S_ISREG, size, snprintf(), strchr(), strlen(), and strncmp().
Referenced by getspnam().
lckpwdf()
int lckpwdf (void)
Definition at line 3 of file lckpwdf.c.
 {
     return 0;
 }
putspent()
int putspent (const struct spwd * sp, FILE * f)
Definition at line 7 of file putspent.c.
 {
     return fprintf(f, "%s:%s:%.*ld:%.*ld:%.*ld:%.*ld:%.*ld:%.*ld:%.*lu\n",
         STR(sp->sp_namp), STR(sp->sp_pwdp), NUM(sp->sp_lstchg),
         NUM(sp->sp_min), NUM(sp->sp_max), NUM(sp->sp_warn),
         NUM(sp->sp_inact), NUM(sp->sp_expire), NUM(sp->sp_flag)) < 0 ? -1 : 0;
 }
References f, fprintf(), NUM, spwd::sp_expire, spwd::sp_flag, spwd::sp_inact, spwd::sp_lstchg, spwd::sp_max, spwd::sp_min, spwd::sp_namp, spwd::sp_pwdp, spwd::sp_warn, and STR.
setspent()
void setspent (void)
Definition at line 3 of file getspent.c.
 {
 }
sgetspent()
struct spwd* sgetspent (const char *)
ulckpwdf()
int ulckpwdf (void)
Definition at line 8 of file lckpwdf.c.
 {
     return 0;
 }