Fennix Userspace: Userspace/mlibc/sysdeps/linux/include/mlibc/thread-entry.hpp File Reference
thread-entry.hpp File Reference
#include <mlibc/tcb.hpp>
Namespaces
mlibc
Functions
int __mlibc_spawn_thread (int flags, void *stack, void *pid_out, void *child_tid, void *tcb)
void __mlibc_enter_thread (void *entry, void *user_arg)
void * mlibc::prepare_stack (void *entry, void *user_arg)
Function Documentation
__mlibc_enter_thread()
void __mlibc_enter_thread (void * entry, void * user_arg)
Definition at line 10 of file thread.cpp.
{
     // The linux kernel already sets the TCB in sys_clone().
     auto tcb = mlibc::get_current_tcb();
     // Wait until our parent sets up the TID.
     while(!__atomic_load_n(&tcb->tid, __ATOMIC_RELAXED))
         mlibc::sys_futex_wait(&tcb->tid, 0, nullptr);
     void *(*func)(void *) = reinterpret_cast<void *(*)(void *)>(entry);
     auto result = func(user_arg);
     tcb->returnValue = result;
     __atomic_store_n(&tcb->didExit, 1, __ATOMIC_RELEASE);
     mlibc::sys_futex_wake(&tcb->didExit);
     mlibc::sys_thread_exit();
 }
References mlibc::get_current_tcb(), mlibc::sys_futex_wait(), mlibc::sys_futex_wake(), and mlibc::sys_thread_exit().
__mlibc_spawn_thread()
int __mlibc_spawn_thread (int flags, void * stack, void * pid_out, void * child_tid, void * tcb)