Fennix: Userspace/apps/base/busybox/archival/libarchive/seek_by_jump.c File Reference
seek_by_jump.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
void FAST_FUNC seek_by_jump (int fd, off_t amount)
Function Documentation
seek_by_jump()
void FAST_FUNC seek_by_jump (int fd, off_t amount)
Definition at line 8 of file seek_by_jump.c.
 {
     if (amount
      && lseek(fd, amount, SEEK_CUR) == (off_t) -1
     ) {
         if (errno == ESPIPE)
             seek_by_read(fd, amount);
         else
             bb_simple_perror_msg_and_die("seek failure");
     }
 }
References bb_simple_perror_msg_and_die(), errno, ESPIPE, fd, lseek(), off_t, seek_by_read(), and SEEK_CUR.
Referenced by init_handle().