Fennix: Userspace/musl/src/string/strchr.c File Reference
strchr.c File Reference
#include <string.h>
Functions
char * strchr (const char *s, int c)
Function Documentation
strchr()
char* strchr (const char * s, int c)
Definition at line 3 of file strchr.c.
 {
     char *r = __strchrnul(s, c);
     return *(unsigned char *)r == (unsigned char)c ? r : 0;
 }
References __strchrnul(), c, and s.
Referenced by __execvpe(), __fdopen(), __fmodeflags(), __get_resolv_conf(), __getgrent_a(), __getpwent_a(), __lookup_ipliteral(), __lookup_serv(), __parsespent(), _nl_explode_name(), _nl_init_domain_conv(), _rl_find_completion_word(), _rl_isearch_dispatch(), a64l(), add_cmd_block(), add_links(), add_MANPATH(), add_split_dependencies(), append_mount_options(), argz_next__(), awk_getline(), awk_main(), awk_printf(), bb_dump_size(), bb_unsetenv(), bpad(), builtin_arrayref_flags(), builtin_source(), cag_option_find_by_letter(), catopen(), char_insert(), chmod_main(), chpasswd_main(), cmdio_get_cmd_and_arg(), compile_fs_type(), conf_expand_value(), conf_read_simple(), config_read(), ConvertFileFlags(), create_fs_device(), data_extract_all(), date_main(), dcngettext(), dd_main(), decode_one_format(), decode_prompt_string(), dequote_escapes(), dequote_string(), dialog_menu(), display_single(), do_cmd(), do_glob(), do_logging(), do_tunnels_list(), do_tzset(), dsvsplit(), dump_procs(), edir(), edit_file(), encode_string(), encode_then_append_var_plusminus(), env_main(), escape(), EscapeShellString(), evalvar(), execute_intern_function(), expand_on_ifs(), expand_one_var(), expand_string_to_string(), expand_vars_to_list(), exportcmd(), extract_dollar_brace_string(), extract_filename(), extract_heredoc_dolbrace_string(), find_command(), find_dot_file(), find_executable(), find_pair(), find_range(), first_alpha(), fix_assignment_words(), fixup_rpath(), fmemopen(), fmt_num(), fmt_url(), fmtmsg(), fopen(), fopencookie(), fsck_device(), fsck_main(), fstype_matches(), generate_output(), get_addr_1(), get_flag(), get_irqs_from_interrupts(), get_linux_version_code(), get_modinfo_value(), get_prefix_1(), get_rt_realms(), get_uidgid(), get_username_or_die(), getmntent_r(), getNum(), getprec(), getspnam_r(), getsubopt(), handle_incoming_and_exit(), hasmeta(), hexdump_main(), hush_main(), ifconfig_main(), ifplugd_main(), ifsbreakup(), ifupdown_main(), index(), INET_setroute(), init(), inotifyd_main(), internal_getopt(), iprule_modify(), ll_addr_a2n(), load_library(), locale_charset(), logdir_open(), lpd_main(), lpqr_main(), lsscsi_main(), main(), make_here_document(), make_path(), make_quoted_replacement(), man_main(), match_opt(), mbschr(), md5_sha1_sum_main(), mklocal(), mknod_main(), name_from_hosts(), name_to_dev_t(), nfsmount(), nmeter_main(), ntp_init(), o_addqchr(), o_addQchr(), obscure_msg(), od_main(), only_changed_user(), parse(), parse_and_add_kcmdline_module_options(), parse_args(), parse_chown_usergroup_or_die(), parse_conf(), parse_datestr(), parse_dollar(), parse_matched_pair(), parse_meminfo(), parse_mount_options(), parse_one_line(), parse_stream(), parse_url(), ParseDMXConfig(), pid_is_name(), plural_lookup(), popen(), popen_ls(), popmaildir_main(), print_autowrap(), print_direc(), print_formatted(), process_config_line(), process_files(), process_includes(), process_irq_counts(), process_timer_stats(), procps_scan(), pseudo_exec_argv(), read_after_slash(), read_alias_file(), read_token_word(), readtoken1(), remove_quoted_nulls(), renice_main(), rescan_crontab_dir(), reverse_hosts(), reverse_services(), rewrite(), rl_alphabetic(), run_pipe(), sane_address(), scan_request(), sendmail_main(), set_local_var(), set_vars_and_save_old(), sh_getopt(), shell_builtin_read(), shellexec(), show_shell_usage(), shuf_main(), singlemount(), sleep_builtin(), sockaddr2str(), sort_main(), stat_char(), str2sockaddr(), strcreplace(), strftime(), strip_ipv6_scope_id(), strstr(), subCommand(), subevalvar(), sysctl_act_on_setting(), sysctl_act_recursive(), tar_main(), targp_parse(), tilde_expand(), udhcp_str2optset(), uevent_main(), update_passwd(), validate_path(), version_compare(), vi_change_dispatch(), vi_delete_dispatch(), vi_yank_dispatch(), which_main(), and xxreadtoken().