Fennix Userspace: Userspace/apps/base/bash/lib/sh/strpbrk.c File Reference
strpbrk.c File Reference
#include <stdc.h>
Functions
char * strpbrk (const char *s, const char *accept)
Function Documentation
strpbrk()
char* strpbrk (const char * s, const char * accept)
Definition at line 34 of file strpbrk.c.
 {
   while (*s != '\0')
     {
       const char *a = accept;
       while (*a != '\0')
     if (*a++ == *s)
       return (char *) s;
       ++s;
     }
   return 0;
 }
References accept(), and s.
Referenced by add_cmd(), awk_split(), conf_read_simple(), do_rd(), fix_assignment_words(), hasmeta(), init_exec(), rmescapes(), sleep_builtin(), strsep(), and subevalvar().