Fennix: Userspace/musl/src/internal/libc.h File Reference
libc.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <limits.h>
Data Structures
struct __locale_struct
struct tls_module
struct __libc
Macros
#define PAGE_SIZE libc.page_size
#define libc __libc
Functions
hidden void __init_libc (char **, char *)
hidden void __init_tls (size_t *)
hidden void __init_ssp (void *)
hidden void __libc_start_init (void)
hidden void __funcs_on_exit (void)
hidden void __funcs_on_quick_exit (void)
hidden void __libc_exit_fini (void)
hidden void __fork_handler (int)
hidden void __synccall (void(*)(void *), void *)
hidden int __setxid (int, int, int, int)
Variables
hidden struct __libc __libc
hidden size_t __hwcap
hidden size_t __sysinfo
char * __progname
char * __progname_full
hidden const char __libc_version []
Data Structure Documentation
__locale_struct
struct __locale_struct
Definition at line 10 of file libc.h.
Data Fields
const struct __locale_map * cat[6]
tls_module
struct tls_module
Definition at line 14 of file libc.h.
Data Fields
size_t align
void * image
size_t len
struct tls_module * next
size_t offset
size_t size
__libc
struct __libc
Definition at line 20 of file libc.h.
Data Fields
size_t * auxv
char can_do_threads
struct __locale_struct global_locale
volatile signed char need_locks
size_t page_size
char secure
char threaded
int threads_minus_1
size_t tls_align
size_t tls_cnt
struct tls_module * tls_head
size_t tls_size
Macro Definition Documentation
libc
#define libc __libc
Definition at line 38 of file libc.h.
PAGE_SIZE
#define PAGE_SIZE libc.page_size
Definition at line 34 of file libc.h.
Function Documentation
__fork_handler()
hidden void __fork_handler (int who)
Definition at line 20 of file pthread_atfork.c.
 {
     struct atfork_funcs *p;
     if (!funcs) return;
     if (who < 0) {
         LOCK(lock);
         for (p=funcs; p; p = p->next) {
             if (p->prepare) p->prepare();
             funcs = p;
         }
     } else {
         for (p=funcs; p; p = p->prev) {
             if (!who && p->parent) p->parent();
             else if (who && p->child) p->child();
             funcs = p;
         }
         UNLOCK(lock);
     }
 }
References funcs, LOCK, lock, p, and UNLOCK.
Referenced by fork().
__funcs_on_exit()
hidden void __funcs_on_exit (void)
Definition at line 26 of file atexit.c.
 {
     void (*func)(void *), *arg;
     LOCK(lock);
     for (; head; head=head->next, slot=COUNT) while(slot-->0) {
         func = head->f[slot];
         arg = head->a[slot];
         UNLOCK(lock);
         func(arg);
         LOCK(lock);
     }
 }
References fl::a, COUNT, fl::f, head, LOCK, lock, fl::next, slot, UNLOCK, and Driver::void().
Referenced by exit().
__funcs_on_quick_exit()
hidden void __funcs_on_quick_exit (void)
Definition at line 13 of file at_quick_exit.c.
 {
     void (*func)(void);
     LOCK(lock);
     while (count > 0) {
         func = funcs[--count];
         UNLOCK(lock);
         func();
         LOCK(lock);
     }
 }
References count, funcs, LOCK, lock, UNLOCK, and Driver::void().
Referenced by quick_exit().
__init_libc()
hidden void __init_libc (char ** envp, char * pn)
Definition at line 23 of file __libc_start_main.c.
 {
     size_t i, *auxv, aux[AUX_CNT] = { 0 };
     __environ = envp;
     for (i=0; envp[i]; i++);
     libc.auxv = auxv = (void *)(envp+i+1);
     for (i=0; auxv[i]; i+=2) if (auxv[i]<AUX_CNT) aux[auxv[i]] = auxv[i+1];
     __hwcap = aux[AT_HWCAP];
     if (aux[AT_SYSINFO]) __sysinfo = aux[AT_SYSINFO];
     libc.page_size = aux[AT_PAGESZ];
     if (!pn) pn = (void*)aux[AT_EXECFN];
     if (!pn) pn = "";
     __progname = __progname_full = pn;
     for (i=0; pn[i]; i++) if (pn[i]=='/') __progname = pn+i+1;
     __init_tls(aux);
     __init_ssp((void *)aux[AT_RANDOM]);
     if (aux[AT_UID]==aux[AT_EUID] && aux[AT_GID]==aux[AT_EGID]
         && !aux[AT_SECURE]) return;
     struct pollfd pfd[3] = { {.fd=0}, {.fd=1}, {.fd=2} };
     int r =
 #ifdef SYS_poll
     __syscall(SYS_poll, pfd, 3, 0);
 #else
     __syscall(SYS_ppoll, pfd, 3, &(struct timespec){0}, 0, _NSIG/8);
 #endif
     if (r<0) a_crash();
     for (i=0; i<3; i++) if (pfd[i].revents&POLLNVAL)
         if (__sys_open("/dev/null", O_RDWR)<0)
             a_crash();
     libc.secure = 1;
 }
References __environ, __hwcap, __init_ssp(), __init_tls(), __progname, __progname_full, __sys_open, __syscall, __sysinfo, _NSIG, a_crash, AT_EGID, AT_EUID, AT_EXECFN, AT_GID, AT_HWCAP, AT_PAGESZ, AT_RANDOM, AT_SECURE, AT_SYSINFO, AT_UID, AUX_CNT, i, libc, O_RDWR, pfd, POLLNVAL, pollfd::revents, and SYS_ppoll.
Referenced by __libc_start_main().
__init_ssp()
hidden void __init_ssp (void * entropy)
Definition at line 7 of file __stack_chk_fail.c.
 {
     if (entropy) memcpy(&__stack_chk_guard, entropy, sizeof(uintptr_t));
     else __stack_chk_guard = (uintptr_t)&__stack_chk_guard * 1103515245;
 #if UINTPTR_MAX >= 0xffffffffffffffff
     /* Sacrifice 8 bits of entropy on 64bit to prevent leaking/
      * overwriting the canary via string-manipulation functions.
      * The NULL byte is on the second byte so that off-by-ones can
      * still be detected. Endianness is taken care of
      * automatically. */
     ((char *)&__stack_chk_guard)[1] = 0;
 #endif
     __pthread_self()->canary = __stack_chk_guard;
 }
References __pthread_self, __stack_chk_guard, and memcpy.
Referenced by __init_libc().
__init_tls()
hidden void __init_tls (size_t * auxv)
Definition at line 1631 of file dynlink.c.
 {
 }
Referenced by __init_libc().
__libc_exit_fini()
hidden void __libc_exit_fini (void)
Definition at line 1467 of file dynlink.c.
 {
     struct dso *p;
     size_t dyn[DYN_CNT];
     pthread_t self = __pthread_self();
     /* Take both locks before setting shutting_down, so that
      * either lock is sufficient to read its value. The lock
      * order matches that in dlopen to avoid deadlock. */
     pthread_rwlock_wrlock(&lock);
     pthread_mutex_lock(&init_fini_lock);
     shutting_down = 1;
     pthread_rwlock_unlock(&lock);
     for (p=fini_head; p; p=p->fini_next) {
         while (p->ctor_visitor && p->ctor_visitor!=self)
             pthread_cond_wait(&ctor_cond, &init_fini_lock);
         if (!p->constructed) continue;
         decode_vec(p->dynv, dyn, DYN_CNT);
         if (dyn[0] & (1<<DT_FINI_ARRAY)) {
             size_t n = dyn[DT_FINI_ARRAYSZ]/sizeof(size_t);
             size_t *fn = (size_t *)laddr(p, dyn[DT_FINI_ARRAY])+n;
             while (n--) ((void (*)(void))*--fn)();
         }
 #ifndef NO_LEGACY_INITFINI
         if ((dyn[0] & (1<<DT_FINI)) && dyn[DT_FINI])
             fpaddr(p, dyn[DT_FINI])();
 #endif
     }
 }
References __pthread_self, ctor_cond, decode_vec(), DT_FINI, DT_FINI_ARRAY, DT_FINI_ARRAYSZ, DYN_CNT, fini_head, fpaddr, init_fini_lock, laddr, lock, n, p, pthread_cond_wait(), pthread_mutex_lock(), pthread_rwlock_unlock(), pthread_rwlock_wrlock(), shutting_down, and Driver::void().
Referenced by exit().
__libc_start_init()
hidden void __libc_start_init (void)
Definition at line 1617 of file dynlink.c.
 {
     do_init_fini(main_ctor_queue);
     if (!__malloc_replaced && main_ctor_queue != builtin_ctor_queue)
         free(main_ctor_queue);
     main_ctor_queue = 0;
 }
References __malloc_replaced, builtin_ctor_queue, do_init_fini(), free, and main_ctor_queue.
Referenced by libc_start_main_stage2().
__setxid()
hidden int __setxid (int nr, int id, int eid, int sid)
Definition at line 27 of file setxid.c.
 {
     /* ret is initially nonzero so that failure of the first thread does not
      * trigger the safety kill above. */
     struct ctx c = { .nr = nr, .id = id, .eid = eid, .sid = sid, .ret = 1 };
     __synccall(do_setxid, &c);
     return __syscall_ret(c.ret);
 }
References __synccall(), __syscall_ret(), c, do_setxid(), ctx::eid, ctx::id, ctx::nr, and ctx::sid.
Referenced by setegid(), seteuid(), setgid(), setregid(), setresgid(), setresuid(), setreuid(), and setuid().
__synccall()
hidden void __synccall (void(*)(void *) func, void * ctx)
Definition at line 44 of file synccall.c.
 {
     sigset_t oldmask;
     int cs, i, r;
     struct sigaction sa = { .sa_flags = SA_RESTART | SA_ONSTACK, .sa_handler = handler };
     pthread_t self = __pthread_self(), td;
     int count = 0;
     /* Blocking signals in two steps, first only app-level signals
      * before taking the lock, then all signals after taking the lock,
      * is necessary to achieve AS-safety. Blocking them all first would
      * deadlock if multiple threads called __synccall. Waiting to block
      * any until after the lock would allow re-entry in the same thread
      * with the lock already held. */
     __block_app_sigs(&oldmask);
     __tl_lock();
     __block_all_sigs(0);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     sem_init(&target_sem, 0, 0);
     sem_init(&caller_sem, 0, 0);
     if (!libc.threads_minus_1 || __syscall(SYS_gettid) != self->tid)
         goto single_threaded;
     callback = func;
     context = ctx;
     /* Block even implementation-internal signals, so that nothing
      * interrupts the SIGSYNCCALL handlers. The main possible source
      * of trouble is asynchronous cancellation. */
     memset(&sa.sa_mask, -1, sizeof sa.sa_mask);
     __libc_sigaction(SIGSYNCCALL, &sa, 0);
     for (td=self->next; td!=self; td=td->next) {
         target_tid = td->tid;
         while ((r = -__syscall(SYS_tkill, td->tid, SIGSYNCCALL)) == EAGAIN);
         if (r) {
             /* If we failed to signal any thread, nop out the
              * callback to abort the synccall and just release
              * any threads already caught. */
             callback = func = dummy;
             break;
         }
         sem_wait(&caller_sem);
         count++;
     }
     target_tid = 0;
     /* Serialize execution of callback in caught threads, or just
      * release them all if synccall is being aborted. */
     for (i=0; i<count; i++) {
         sem_post(&target_sem);
         sem_wait(&caller_sem);
     }
     sa.sa_handler = SIG_IGN;
     __libc_sigaction(SIGSYNCCALL, &sa, 0);
 single_threaded:
     func(ctx);
     /* Only release the caught threads once all threads, including the
      * caller, have returned from the callback function. */
     for (i=0; i<count; i++)
         sem_post(&target_sem);
     for (i=0; i<count; i++)
         sem_wait(&caller_sem);
     sem_destroy(&caller_sem);
     sem_destroy(&target_sem);
     pthread_setcancelstate(cs, 0);
     __tl_unlock();
     __restore_sigs(&oldmask);
 }
References __block_all_sigs(), __block_app_sigs(), __libc_sigaction(), __pthread_self, __restore_sigs(), __syscall, __tl_lock(), __tl_unlock(), callback, caller_sem, context, count, ctx, dummy(), EAGAIN, handler(), i, libc, memset, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), SA_RESTART, sem_destroy(), sem_init(), sem_post(), sem_wait(), SIG_IGN, SIGSYNCCALL, target_sem, target_tid, and td.
Referenced by __setxid(), setgroups(), and setrlimit().
Variable Documentation
__hwcap
hidden size_t __hwcap extern
Definition at line 5 of file libc.c.
Referenced by __dls2b(), __init_libc(), and __set_thread_area().
__libc
hidden struct __libc __libc extern
Definition at line 1 of file libc.c.
__libc_version
hidden const char __libc_version[] extern
Definition at line 4 of file version.c.
Referenced by __dls3().
__progname
char* __progname extern
Definition at line 6 of file libc.c.
__progname_full
char * __progname_full
Definition at line 51 of file libc.h.
__sysinfo
hidden size_t __sysinfo extern
Definition at line 3 of file defsysinfo.c.
Referenced by __dls3(), __init_libc(), and __init_tp().