Fennix Userspace: Userspace/musl/include/sys/xattr.h File Reference
xattr.h File Reference
#include <bits/alltypes.h>
Macros
#define __NEED_ssize_t
#define __NEED_size_t
#define XATTR_CREATE 1
#define XATTR_REPLACE 2
#define __UAPI_DEF_XATTR 0
Functions
ssize_t getxattr (const char *, const char *, void *, size_t)
ssize_t lgetxattr (const char *, const char *, void *, size_t)
ssize_t fgetxattr (int, const char *, void *, size_t)
ssize_t listxattr (const char *, char *, size_t)
ssize_t llistxattr (const char *, char *, size_t)
ssize_t flistxattr (int, char *, size_t)
int setxattr (const char *, const char *, const void *, size_t, int)
int lsetxattr (const char *, const char *, const void *, size_t, int)
int fsetxattr (int, const char *, const void *, size_t, int)
int removexattr (const char *, const char *)
int lremovexattr (const char *, const char *)
int fremovexattr (int, const char *)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 8 of file xattr.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 7 of file xattr.h.
__UAPI_DEF_XATTR
#define __UAPI_DEF_XATTR 0
Definition at line 27 of file xattr.h.
XATTR_CREATE
#define XATTR_CREATE 1
Definition at line 11 of file xattr.h.
XATTR_REPLACE
#define XATTR_REPLACE 2
Definition at line 12 of file xattr.h.
Function Documentation
fgetxattr()
ssize_t fgetxattr (int filedes, const char * name, void * value, size_t size)
Definition at line 14 of file xattr.c.
 {
     return syscall(SYS_fgetxattr, filedes, name, value, size);
 }
References size, syscall(), and value.
flistxattr()
ssize_t flistxattr (int filedes, char * list, size_t size)
Definition at line 29 of file xattr.c.
 {
     return syscall(SYS_flistxattr, filedes, list, size);
 }
References list(), size, and syscall().
fremovexattr()
int fremovexattr (int fd, const char * name)
Definition at line 59 of file xattr.c.
 {
     return syscall(SYS_fremovexattr, fd, name);
 }
References fd, and syscall().
fsetxattr()
int fsetxattr (int filedes, const char * name, const void * value, size_t size, int flags)
Definition at line 44 of file xattr.c.
 {
     return syscall(SYS_fsetxattr, filedes, name, value, size, flags);
 }
References flags, size, syscall(), and value.
getxattr()
ssize_t getxattr (const char * path, const char * name, void * value, size_t size)
Definition at line 4 of file xattr.c.
 {
     return syscall(SYS_getxattr, path, name, value, size);
 }
References size, syscall(), and value.
lgetxattr()
ssize_t lgetxattr (const char * path, const char * name, void * value, size_t size)
Definition at line 9 of file xattr.c.
 {
     return syscall(SYS_lgetxattr, path, name, value, size);
 }
References size, syscall(), and value.
listxattr()
ssize_t listxattr (const char * path, char * list, size_t size)
Definition at line 19 of file xattr.c.
 {
     return syscall(SYS_listxattr, path, list, size);
 }
References list(), size, and syscall().
llistxattr()
ssize_t llistxattr (const char * path, char * list, size_t size)
Definition at line 24 of file xattr.c.
 {
     return syscall(SYS_llistxattr, path, list, size);
 }
References list(), size, and syscall().
lremovexattr()
int lremovexattr (const char * path, const char * name)
Definition at line 54 of file xattr.c.
 {
     return syscall(SYS_lremovexattr, path, name);
 }
References syscall().
Referenced by setfattr_main().
lsetxattr()
int lsetxattr (const char * path, const char * name, const void * value, size_t size, int flags)
Definition at line 39 of file xattr.c.
 {
     return syscall(SYS_lsetxattr, path, name, value, size, flags);
 }
References flags, size, syscall(), and value.
Referenced by setfattr_main().
removexattr()
int removexattr (const char * path, const char * name)
Definition at line 49 of file xattr.c.
 {
     return syscall(SYS_removexattr, path, name);
 }
References syscall().
Referenced by setfattr_main().
setxattr()
int setxattr (const char * path, const char * name, const void * value, size_t size, int flags)
Definition at line 34 of file xattr.c.
 {
     return syscall(SYS_setxattr, path, name, value, size, flags);
 }
References flags, size, syscall(), and value.
Referenced by setfattr_main().