Fennix: Kernel/syscalls.h File Reference
syscalls.h File Reference
#include <stddef.h>
Macros
#define LTS_SET_GS 0x1
#define LTS_SET_FS 0x2
#define LTS_GET_FS 0x3
#define LTS_GET_GS 0x4
#define LTS_SET_CPUID 0x5
#define LTS_GET_CPUID 0x6
Enumerations
enum MemoryMapFlags { MAP_PRESENT = 1 << 0 , MAP_WRITABLE = 1 << 1 , MAP_USER = 1 << 2 }
enum FileSeekMode { SYSCALL_SEEK_SET = 0 , SYSCALL_SEEK_CUR = 1 , SYSCALL_SEEK_END = 2 }
enum KCtl { KCTL_PRINT = 0 , KCTL_GET_PAGE_SIZE , KCTL_IS_CRITICAL }
enum NativeSyscalls {
sys_Exit = 0 , sys_RequestPages , sys_FreePages , sys_DetachAddress ,
sys_MemoryMap , sys_MemoryUnmap , sys_KernelCTL , sys_FileOpen ,
sys_FileClose , sys_FileRead , sys_FileWrite , sys_FileSeek ,
sys_FileStatus , sys_IPC , sys_LocalThreadState , sys_Sleep ,
sys_Fork , sys_Wait , sys_Kill , sys_Spawn ,
sys_SpawnThread , sys_GetThreadListOfProcess , sys_GetCurrentProcess , sys_GetCurrentThread ,
sys_GetCurrentProcessID , sys_GetCurrentThreadID , sys_GetProcessByPID , sys_GetThreadByTID ,
sys_KillProcess , sys_KillThread , sys_SysReservedCreateProcess , sys_SysReservedCreateThread ,
sys_MaxSyscall
}
Functions
static long syscall0 (long syscall)
static long syscall1 (long syscall, long arg1)
static long syscall2 (long syscall, long arg1, long arg2)
static long syscall3 (long syscall, long arg1, long arg2, long arg3)
static long syscall4 (long syscall, long arg1, long arg2, long arg3, long arg4)
static long syscall5 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5)
static long syscall6 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6)
Macro Definition Documentation
LTS_GET_CPUID
#define LTS_GET_CPUID 0x6
Definition at line 43 of file syscalls.h.
LTS_GET_FS
#define LTS_GET_FS 0x3
Definition at line 40 of file syscalls.h.
LTS_GET_GS
#define LTS_GET_GS 0x4
Definition at line 41 of file syscalls.h.
LTS_SET_CPUID
#define LTS_SET_CPUID 0x5
Definition at line 42 of file syscalls.h.
LTS_SET_FS
#define LTS_SET_FS 0x2
Definition at line 39 of file syscalls.h.
LTS_SET_GS
#define LTS_SET_GS 0x1
Definition at line 38 of file syscalls.h.
Enumeration Type Documentation
FileSeekMode
enum FileSeekMode
Enumerator
SYSCALL_SEEK_SET
SYSCALL_SEEK_CUR
SYSCALL_SEEK_END
Definition at line 52 of file syscalls.h.
 {
     SYSCALL_SEEK_SET = 0,
     SYSCALL_SEEK_CUR = 1,
     SYSCALL_SEEK_END = 2
 } FileSeekMode;
KCtl
enum KCtl
Enumerator
KCTL_PRINT
Print a string to the screen using KPrint
The uptime is prepended to the string before printing.
Arguments: Arg1 - String to print Arg2 - Length of string
KCTL_GET_PAGE_SIZE
Get the page size
KCTL_IS_CRITICAL
Check whether the current thread is critical
Definition at line 59 of file syscalls.h.
 {
     KCTL_PRINT = 0,
     KCTL_GET_PAGE_SIZE,
     KCTL_IS_CRITICAL,
 } KCtl;
MemoryMapFlags
enum MemoryMapFlags
Enumerator
MAP_PRESENT
MAP_WRITABLE
MAP_USER
Definition at line 45 of file syscalls.h.
 {
     MAP_PRESENT = 1 << 0,
     MAP_WRITABLE = 1 << 1,
     MAP_USER = 1 << 2,
 } MemoryMapFlags;
NativeSyscalls
enum NativeSyscalls
Enumeration of all the native syscalls available in the kernel
Enumerator
sys_Exit
Basic syscalls This syscall is used to exit the current process with the provided exit code.
Parameters
Code The exit code
Returns
This syscall does not return
Note
No permissions are required to call this syscall
sys_RequestPages
Memory syscalls This syscall is used to request a specific number of pages of memory from the kernel.
Parameters
Count The number of pages to request
Returns
The address of the first page of memory that was requested
Note
No permissions are required to call this syscall
sys_FreePages
This syscall is used to free a specific number of pages of memory that were previously requested.
Parameters
Address The address of the first page of memory to free
Count The number of pages to free
Returns
0 on success, errno on failure
Note
No permissions are required to call this syscall
sys_DetachAddress
This syscall is used to detach a specific memory address from the current process. This means that the address will no longer be freed when the process exits.
Parameters
Address The address to detach
Returns
0 on success, errno on failure
Note
The process must be trusted by the kernel to call this syscall
sys_MemoryMap
This syscall is used to map a specific memory address to the current process.
Parameters
VirtualAddress The virtual address to map
PhysicalAddress The physical address to map
Size The size of the memory region to map
Flags The flags to use when mapping the memory region (see MemoryMapFlags)
Returns
0 on success, errno on failure
Note
The process must be trusted by the kernel to call this syscall
sys_MemoryUnmap
This syscall is used to unmap a specific memory address from the current process.
Parameters
VirtualAddress The virtual address to unmap
Size The size of the memory region to unmap
Returns
0 on success, errno on failure
Note
The process must be trusted by the kernel to call this syscall
sys_KernelCTL
Kernel Control syscalls Kernel Control
This syscall is used to control certain aspects of the kernel or get information about it.
Parameters
Command The command to execute
Arg1 The first argument
Arg2 The second argument
Arg3 The third argument
Arg4 The fourth argument
Returns
The result of the command, or errno on failure
Note
No permissions are required to call this syscall
sys_FileOpen
File syscalls This syscall is used to open a file with the provided path and flags.
Parameters
Path The path to the file to open
Flags The flags to use when opening the file
Mode The mode to use when opening the file
Returns
The file descriptor of the opened file, or errno on failure
Note
No permissions are required to call this syscall
sys_FileClose
This syscall is used to close a file that was previously opened.
Parameters
FileDescriptor The file descriptor of the file to close
Note
No permissions are required to call this syscall
sys_FileRead
This syscall is used to read a specific number of bytes from a file at a specific offset.
Parameters
FileDescriptor The file descriptor of the file to read from
Buffer The buffer to read into
Count The number of bytes to read
Returns
The number of bytes read, or errno on failure
Note
No permissions are required to call this syscall
sys_FileWrite
This syscall is used to write a specific number of bytes to a file at a specific offset.
Parameters
FileDescriptor The file descriptor of the file to write to
Buffer The buffer to write from
Count The number of bytes to write
Returns
The number of bytes written, or errno on failure
Note
No permissions are required to call this syscall
sys_FileSeek
This syscall is used to change the current offset in a file.
Parameters
FileDescriptor The file descriptor of the file to seek in
Offset The offset to seek to
Whence The seek mode (see FileSeekMode)
Returns
The new offset, or errno on failure
Note
No permissions are required to call this syscall
sys_FileStatus
This syscall is used to retrieve information about a file such as its size, permissions, etc.
Parameters
FileDescriptor The file descriptor of the file to get information about
StatBuffer The buffer to store the information in
Returns
0 on success, errno on failure
Note
No permissions are required to call this syscall
sys_IPC
sys_LocalThreadState
sys_Sleep
sys_Fork
sys_Wait
sys_Kill
sys_Spawn
sys_SpawnThread
sys_GetThreadListOfProcess
sys_GetCurrentProcess
sys_GetCurrentThread
sys_GetCurrentProcessID
sys_GetCurrentThreadID
sys_GetProcessByPID
sys_GetThreadByTID
sys_KillProcess
sys_KillThread
sys_SysReservedCreateProcess
Reserved syscall
sys_SysReservedCreateThread
Reserved syscall
sys_MaxSyscall
Not a real syscall
Definition at line 89 of file syscalls.h.
 {
     sys_Exit = 0,
     sys_RequestPages,
     sys_FreePages,
     sys_DetachAddress,
     sys_MemoryMap,
     sys_MemoryUnmap,
     sys_KernelCTL,
     sys_FileOpen,
     sys_FileClose,
     sys_FileRead,
     sys_FileWrite,
     sys_FileSeek,
     sys_FileStatus,
     sys_IPC,
     sys_LocalThreadState,
     sys_Sleep,
     sys_Fork,
     sys_Wait,
     sys_Kill,
     sys_Spawn,
     sys_SpawnThread,
     sys_GetThreadListOfProcess,
     sys_GetCurrentProcess,
     sys_GetCurrentThread,
     sys_GetCurrentProcessID,
     sys_GetCurrentThreadID,
     sys_GetProcessByPID,
     sys_GetThreadByTID,
     sys_KillProcess,
     sys_KillThread,
     sys_SysReservedCreateProcess,
     sys_SysReservedCreateThread,
     sys_MaxSyscall
 } NativeSyscalls;
Function Documentation
syscall0()
static long syscall0 (long syscall) inline static
Definition at line 475 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
Referenced by fork(), and mlibc::sys_gettid().
syscall1()
static long syscall1 (long syscall, long arg1) inline static
Definition at line 487 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), arg1, ret, and syscall().
Referenced by _exit(), abort(), DG_SleepMs(), ELFLookupSymbol(), fclose(), ld_main(), liballoc_alloc(), RequestPages(), sleep(), and usleep().
syscall2()
static long syscall2 (long syscall, long arg1, long arg2) inline static
Definition at line 499 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), arg1, arg2, ret, and syscall().
Referenced by ELFLookupSymbol(), fopen(), FreePages(), and liballoc_free().
syscall3()
static long syscall3 (long syscall, long arg1, long arg2, long arg3) inline static
Definition at line 511 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), arg1, arg2, arg3, ret, and syscall().
Referenced by ELFLookupSymbol(), fputc(), fread(), fseek(), and fwrite().
syscall4()
static long syscall4 (long syscall, long arg1, long arg2, long arg3, long arg4) inline static
Definition at line 523 of file syscalls.h.
 {
     long ret;
     register long r10 __asm__("r10") = arg4;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3), "r"(r10)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), arg1, arg2, arg3, arg4, ret, and syscall().
syscall5()
static long syscall5 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5) inline static
Definition at line 536 of file syscalls.h.
 {
     long ret;
     register long r10 __asm__("r10") = arg4;
     register long r8 __asm__("r8") = arg5;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3), "r"(r10), "r"(r8)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), arg1, arg2, arg3, arg4, arg5, ret, and syscall().
Referenced by KernelCTL().
syscall6()
static long syscall6 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6) inline static
Definition at line 550 of file syscalls.h.
 {
     long ret;
     register long r10 __asm__("r10") = arg4;
     register long r8 __asm__("r8") = arg5;
     register long r9 __asm__("r9") = arg6;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3), "r"(r10), "r"(r8), "r"(r9)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), arg1, arg2, arg3, arg4, arg5, ret, and syscall().
Referenced by IPC().