Fennix: Userspace/apps/base/bash/eval.c File Reference
eval.c File Reference
#include "config.h"
#include "bashansi.h"
#include <stdio.h>
#include <signal.h>
#include "bashintl.h"
#include "shell.h"
#include "parser.h"
#include "flags.h"
#include "trap.h"
#include "builtins/common.h"
#include "input.h"
#include "execute_cmd.h"
Functions
static void send_pwd_to_eterm PARAMS ((void))
static sighandler alrm_catcher PARAMS ((int))
int reader_loop ()
int pretty_print_loop ()
static sighandler alrm_catcher (int i)
static void send_pwd_to_eterm ()
static void execute_prompt_command ()
int parse_command ()
int read_command ()
Function Documentation
alrm_catcher()
static sighandler alrm_catcher (int i) static
Definition at line 238 of file eval.c.
 {
   char *msg;
   msg = _("\007timed out waiting for input: auto-logout\n");
   write (1, msg, strlen (msg));
   bash_logout ();   /* run ~/.bash_logout if this is a login shell */
   jump_to_top_level (EXITPROG);
   SIGRETURN (0);
 }
References _, EXITPROG, jump_to_top_level(), SIGRETURN, strlen(), and write().
Referenced by read_command().
execute_prompt_command()
static void execute_prompt_command () static
Definition at line 291 of file eval.c.
 {
   char *command_to_execute;
   SHELL_VAR *pcv;
 #if defined (ARRAY_VARS)
   ARRAY *pcmds;
 #endif
   pcv = find_variable ("PROMPT_COMMAND");
   if (pcv  == 0 || var_isset (pcv) == 0 || invisible_p (pcv))
     return;
 #if defined (ARRAY_VARS)
   if (array_p (pcv))
     {
       if ((pcmds = array_cell (pcv)) && array_num_elements (pcmds) > 0)
     execute_array_command (pcmds, "PROMPT_COMMAND");
       return;
     }
   else if (assoc_p (pcv))
     return; /* currently don't allow associative arrays here */
 #endif
   command_to_execute = value_cell (pcv);
   if (command_to_execute && *command_to_execute)
     execute_variable_command (command_to_execute, "PROMPT_COMMAND");
 }
References array_cell, array_num_elements, array_p, assoc_p, execute_variable_command(), find_variable(), invisible_p, value_cell, and var_isset.
Referenced by parse_command().
PARAMS() [1/2]
static sighandler alrm_catcher PARAMS ((int)) static
PARAMS() [2/2]
static void send_pwd_to_eterm PARAMS ((void)) static
parse_command()
static union node * parse_command (void)
Definition at line 323 of file eval.c.
 {
   int r;
   need_here_doc = 0;
   run_pending_traps ();
   /* Allow the execution of a random command just before the printing
      of each primary prompt.  If the shell variable PROMPT_COMMAND
      is set then its value (array or string) is the command(s) to execute. */
   /* The tests are a combination of SHOULD_PROMPT() and prompt_again()
      from parse.y, which are the conditions under which the prompt is
      actually printed. */
   if (interactive && bash_input.type != st_string && parser_expanding_alias() == 0)
     {
 #if defined (READLINE)
       if (no_line_editing || (bash_input.type == st_stdin && parser_will_prompt ()))
 #endif
         execute_prompt_command ();
       if (running_under_emacs == 2)
     send_pwd_to_eterm ();   /* Yuck */
     }
   current_command_line_count = 0;
   r = yyparse ();
   if (need_here_doc)
     gather_here_documents ();
   return (r);
 }
References bash_input, current_command_line_count, execute_prompt_command(), gather_here_documents(), interactive, need_here_doc, no_line_editing, parser_expanding_alias(), run_pending_traps(), running_under_emacs, send_pwd_to_eterm(), st_stdin, st_string, BASH_INPUT::type, and yyparse.
Referenced by parse_and_execute(), parse_string(), and read_command().
pretty_print_loop()
int pretty_print_loop ()
Definition at line 198 of file eval.c.
 {
   COMMAND *current_command;
   char *command_to_print;
   int code;
   int global_posix_mode, last_was_newline;
   global_posix_mode = posixly_correct;
   last_was_newline = 0;
   while (EOF_Reached == 0)
     {
       code = setjmp_nosigs (top_level);
       if (code)
         return (EXECUTION_FAILURE);
       if (read_command() == 0)
     {
       current_command = global_command;
       global_command = 0;
       posixly_correct = 1;          /* print posix-conformant */
       if (current_command && (command_to_print = make_command_string (current_command)))
         {
           printf ("%s\n", command_to_print);    /* for now */
           last_was_newline = 0;
         }
       else if (last_was_newline == 0)
         {
            printf ("\n");
            last_was_newline = 1;
         }
       posixly_correct = global_posix_mode;
       dispose_command (current_command);
     }
       else
     return (EXECUTION_FAILURE);
     }
   return (EXECUTION_SUCCESS);
 }
References code, dispose_command(), EOF_Reached, EXECUTION_FAILURE, EXECUTION_SUCCESS, global_command, make_command_string(), posixly_correct, printf, read_command(), setjmp_nosigs, and top_level.
Referenced by main().
read_command()
int read_command ()
Definition at line 360 of file eval.c.
 {
   SHELL_VAR *tmout_var;
   int tmout_len, result;
   SigHandler *old_alrm;
   set_current_prompt_level (1);
   global_command = (COMMAND *)NULL;
   /* Only do timeouts if interactive. */
   tmout_var = (SHELL_VAR *)NULL;
   tmout_len = 0;
   old_alrm = (SigHandler *)NULL;
   if (interactive)
     {
       tmout_var = find_variable ("TMOUT");
       if (tmout_var && var_isset (tmout_var))
     {
       tmout_len = atoi (value_cell (tmout_var));
       if (tmout_len > 0)
         {
           old_alrm = set_signal_handler (SIGALRM, alrm_catcher);
           alarm (tmout_len);
         }
     }
     }
   QUIT;
   current_command_line_count = 0;
   result = parse_command ();
   if (interactive && tmout_var && (tmout_len > 0))
     {
       alarm(0);
       set_signal_handler (SIGALRM, old_alrm);
     }
   return (result);
 }
References alarm(), alrm_catcher(), atoi(), current_command_line_count, find_variable(), global_command, interactive, NULL, old_alrm, parse_command(), QUIT, set_current_prompt_level(), set_signal_handler, SIGALRM, value_cell, and var_isset.
Referenced by pretty_print_loop(), and reader_loop().
reader_loop()
int reader_loop ()
Definition at line 57 of file eval.c.
 {
   int our_indirection_level;
   COMMAND * volatile current_command;
   USE_VAR(current_command);
   current_command = (COMMAND *)NULL;
   our_indirection_level = ++indirection_level;
   if (just_one_command)
     reset_readahead_token ();
   while (EOF_Reached == 0)
     {
       int code;
       code = setjmp_nosigs (top_level);
 #if defined (PROCESS_SUBSTITUTION)
       unlink_fifo_list ();
 #endif /* PROCESS_SUBSTITUTION */
       /* XXX - why do we set this every time through the loop?  And why do
      it if SIGINT is trapped in an interactive shell? */
       if (interactive_shell && signal_is_ignored (SIGINT) == 0 && signal_is_trapped (SIGINT) == 0)
     set_signal_handler (SIGINT, sigint_sighandler);
       if (code != NOT_JUMPED)
     {
       indirection_level = our_indirection_level;
       switch (code)
         {
           /* Some kind of throw to top_level has occurred. */
         case ERREXIT:
           if (exit_immediately_on_error)
         reset_local_contexts ();    /* not in a function */
         case FORCE_EOF:
         case EXITPROG:
         case EXITBLTIN:
           current_command = (COMMAND *)NULL;
           EOF_Reached = EOF;
           goto exec_done;
         case DISCARD:
           /* Make sure the exit status is reset to a non-zero value, but
          leave existing non-zero values (e.g., > 128 on signal)
          alone. */
           if (last_command_exit_value == 0)
         set_exit_status (EXECUTION_FAILURE);
           if (subshell_environment)
         {
           current_command = (COMMAND *)NULL;
           EOF_Reached = EOF;
           goto exec_done;
         }
           /* Obstack free command elements, etc. */
           if (current_command)
         {
           dispose_command (current_command);
           current_command = (COMMAND *)NULL;
         }
           restore_sigmask ();
           break;
         default:
           command_error ("reader_loop", CMDERR_BADJUMP, code, 0);
         }
     }
       executing = 0;
       if (temporary_env)
     dispose_used_env_vars ();
 #if (defined (ultrix) && defined (mips)) || defined (C_ALLOCA)
       /* Attempt to reclaim memory allocated with alloca (). */
       (void) alloca (0);
 #endif
       if (read_command () == 0)
     {
       if (interactive_shell == 0 && read_but_dont_execute)
         {
           set_exit_status (last_command_exit_value);
           dispose_command (global_command);
           global_command = (COMMAND *)NULL;
         }
       else if (current_command = global_command)
         {
           global_command = (COMMAND *)NULL;
           /* If the shell is interactive, expand and display $PS0 after reading a
          command (possibly a list or pipeline) and before executing it. */
           if (interactive && ps0_prompt)
         {
           char *ps0_string;
           ps0_string = decode_prompt_string (ps0_prompt);
           if (ps0_string && *ps0_string)
             {
               fprintf (stderr, "%s", ps0_string);
               fflush (stderr);
             }
           free (ps0_string);
         }
           current_command_number++;
           executing = 1;
           stdin_redir = 0;
           execute_command (current_command);
         exec_done:
           QUIT;
           if (current_command)
         {
           dispose_command (current_command);
           current_command = (COMMAND *)NULL;
         }
         }
     }
       else
     {
       /* Parse error, maybe discard rest of stream if not interactive. */
       if (interactive == 0)
         EOF_Reached = EOF;
     }
       if (just_one_command)
     EOF_Reached = EOF;
     }
   indirection_level--;
   return (last_command_exit_value);
 }
References alloca, CMDERR_BADJUMP, code, command_error(), current_command_number, decode_prompt_string(), DISCARD, dispose_command(), dispose_used_env_vars(), EOF, EOF_Reached, ERREXIT, execute_command(), executing, EXECUTION_FAILURE, exit_immediately_on_error, EXITBLTIN, EXITPROG, fflush(), FORCE_EOF, fprintf(), free, global_command, indirection_level, interactive, interactive_shell, just_one_command, last_command_exit_value, NOT_JUMPED, NULL, ps0_prompt, QUIT, read_but_dont_execute, read_command(), reset_local_contexts(), reset_readahead_token(), restore_sigmask(), set_exit_status(), set_signal_handler, setjmp_nosigs, SIGINT, sigint_sighandler(), signal_is_ignored(), signal_is_trapped(), stderr, stdin_redir, subshell_environment, temporary_env, top_level, USE_VAR, and Module::void().
Referenced by main(), and push_builtin().
send_pwd_to_eterm()
static void send_pwd_to_eterm () static
Definition at line 254 of file eval.c.
 {
   char *pwd, *f;
   f = 0;
   pwd = get_string_value ("PWD");
   if (pwd == 0)
     f = pwd = get_working_directory ("eterm");
   fprintf (stderr, "\032/%s\n", pwd);
   free (f);
 }
References f, fprintf(), free, get_string_value(), get_working_directory(), and stderr.
Referenced by parse_command().