Fennix: Drivers/input/aip/aip.h File Reference
aip.h File Reference
#include <types.h>
#include <aip.h>
#include <regs.h>
Functions
void PS2KbdInterruptHandler (TrapFrame *)
int InitializeKeyboard ()
int FinalizeKeyboard ()
int DetectPS2Keyboard ()
void PS2MouseInterruptHandler (TrapFrame *)
int InitializeMouse ()
int FinalizeMouse ()
int DetectPS2Mouse ()
int DetectUART ()
Variables
uint8_t Device1ID []
uint8_t Device2ID []
Function Documentation
DetectPS2Keyboard()
int DetectPS2Keyboard ()
Definition at line 301 of file keyboard.c.
 {
     PS2WriteData(PS2_KBD_CMD_DISABLE_SCANNING);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to disable scanning");
     PS2WriteData(PS2_KBD_CMD_IDENTIFY);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to identify");
     uint8_t recByte;
     int timeout = 1000000;
     while (timeout--)
     {
         recByte = PS2ReadData();
         if (recByte != PS2_ACK)
             break;
     }
     Device1ID[0] = recByte;
     timeout = 1000000;
     while (timeout--)
     {
         recByte = PS2ReadData();
         if (recByte != PS2_ACK)
             break;
     }
     if (timeout == 0)
         KernelLog("PS/2 keyboard second byte timed out");
     else
         Device1ID[1] = recByte;
     KernelLog("PS2 Keyboard Device: 0x%X 0x%X", Device1ID[0], Device1ID[1]);
     return 0;
 }
References Device1ID, KernelLog(), PS2_ACK, PS2_KBD_CMD_DISABLE_SCANNING, PS2_KBD_CMD_IDENTIFY, v0::PS2ACKTimeout(), v0::PS2ReadData(), and v0::PS2WriteData().
Referenced by DriverProbe().
DetectPS2Mouse()
int DetectPS2Mouse ()
Definition at line 211 of file mouse.c.
 {
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_DISABLE_DATA_REPORTING);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 mouse failed to disable data reporting!");
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_READ_ID);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 mouse failed to read ID!");
     uint8_t recByte;
     int timeout = 1000000;
     while (timeout--)
     {
         recByte = PS2ReadData();
         if (recByte != PS2_ACK)
             break;
     }
     Device2ID[0] = recByte;
     timeout = 1000000;
     while (timeout--)
     {
         recByte = PS2ReadData();
         if (recByte != PS2_ACK)
             break;
     }
     Device2ID[1] = recByte;
     KernelLog("PS2 Mouse Device: 0x%X 0x%X", Device2ID[0], Device2ID[1]);
     return 0;
 }
References Device2ID, KernelLog(), PS2_ACK, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, PS2_MOUSE_CMD_READ_ID, v0::PS2ACKTimeout(), v0::PS2ReadData(), v0::PS2WriteCommand(), and v0::PS2WriteData().
Referenced by DriverProbe().
DetectUART()
int DetectUART ()
Definition at line 499 of file uart.c.
 {
     uart.com1 = inb(COM1) != 0xFF ? true : false;
     uart.com2 = inb(COM2) != 0xFF ? true : false;
     uart.com3 = inb(COM3) != 0xFF ? true : false;
     uart.com4 = inb(COM4) != 0xFF ? true : false;
     uart.com5 = inb(COM5) != 0xFF ? true : false;
     uart.com6 = inb(COM6) != 0xFF ? true : false;
     uart.com7 = inb(COM7) != 0xFF ? true : false;
     uart.com8 = inb(COM8) != 0xFF ? true : false;
     uart.lpt1 = inb(LPT1) != 0xFF ? true : false;
     uart.lpt2 = inb(LPT2) != 0xFF ? true : false;
     uart.lpt3 = inb(LPT3) != 0xFF ? true : false;
     if (uart.com1 == true)
         if (InitializePort(COM1) == false)
             uart.com1 = false;
     if (uart.com2 == true)
         if (InitializePort(COM2) == false)
             uart.com1 = false;
     if (uart.com3 == true)
         if (InitializePort(COM3) == false)
             uart.com1 = false;
     if (uart.com4 == true)
         if (InitializePort(COM4) == false)
             uart.com1 = false;
     if (uart.com5 == true)
         if (InitializePort(COM5) == false)
             uart.com1 = false;
     if (uart.com6 == true)
         if (InitializePort(COM6) == false)
             uart.com1 = false;
     if (uart.com7 == true)
         if (InitializePort(COM7) == false)
             uart.com1 = false;
     if (uart.com8 == true)
         if (InitializePort(COM8) == false)
             uart.com1 = false;
     if (uart.lpt1 == true)
         KernelPrint("LPT1 is present");
     if (uart.lpt2 == true)
         KernelPrint("LPT2 is present");
     if (uart.lpt3 == true)
         KernelPrint("LPT3 is present");
     return 0;
 }
References COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, inb(), InitializePort(), KernelPrint(), LPT1, LPT2, LPT3, true, and uart.
Referenced by DriverProbe().
FinalizeKeyboard()
int FinalizeKeyboard ()
Definition at line 291 of file keyboard.c.
 {
     PS2WriteData(PS2_KBD_CMD_DISABLE_SCANNING);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to disable scanning");
     UnregisterDevice(KeyboardDevID);
     return 0;
 }
References KernelLog(), KeyboardDevID, PS2_KBD_CMD_DISABLE_SCANNING, v0::PS2ACKTimeout(), v0::PS2WriteData(), and v0::UnregisterDevice().
Referenced by DriverFinal().
FinalizeMouse()
int FinalizeMouse ()
Definition at line 202 of file mouse.c.
 {
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_DISABLE_DATA_REPORTING);
     UnregisterDevice(MouseDevID);
     return 0;
 }
References MouseDevID, PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_DISABLE_DATA_REPORTING, v0::PS2WriteCommand(), v0::PS2WriteData(), and v0::UnregisterDevice().
Referenced by DriverFinal().
InitializeKeyboard()
int InitializeKeyboard ()
Definition at line 247 of file keyboard.c.
 {
     // PS2WriteData(PS2_KBD_CMD_RESET);
     // uint8_t test = PS2ReadData();
     // if (test != PS2_KBD_RESP_TEST_PASSED &&
     //  test != PS2_KBD_RESP_ACK)
     // {
     //  KernelLog("PS/2 keyboard reset failed (%#x)", test);
     //  return -EFAULT;
     // }
     PS2WriteData(PS2_KBD_CMD_DEFAULTS);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set defaults");
     PS2WriteData(PS2_KBD_CMD_SCAN_CODE_SET);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set scan code set");
     /* We want Scan Code Set 1 */
     PS2WriteData(PS2_KBD_SCAN_CODE_SET_2); /* It will set to 1 but with translation? */
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set scan code set 2");
     PS2WriteData(PS2_KBD_CMD_SCAN_CODE_SET);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set scan code set");
     PS2WriteData(PS2_KBD_SCAN_CODE_GET_CURRENT);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to get current scan code set");
     KeyboardScanCodeSet = PS2ReadAfterACK();
     KernelLog("PS/2 Keyboard Scan Code Set: 0x%X", KeyboardScanCodeSet);
     PS2ClearOutputBuffer();
     PS2WriteData(PS2_KBD_CMD_ENABLE_SCANNING);
     RegisterInterruptHandler(1, PS2KbdInterruptHandler);
     KeyboardDevID = RegisterDevice(INPUT_TYPE_KEYBOARD, &KbdOps);
     return 0;
 }
References INPUT_TYPE_KEYBOARD, KbdOps, KernelLog(), KeyboardDevID, KeyboardScanCodeSet, PS2_KBD_CMD_DEFAULTS, PS2_KBD_CMD_ENABLE_SCANNING, PS2_KBD_CMD_SCAN_CODE_SET, PS2_KBD_SCAN_CODE_GET_CURRENT, PS2_KBD_SCAN_CODE_SET_2, v0::PS2ACKTimeout(), v0::PS2ClearOutputBuffer(), PS2KbdInterruptHandler(), v0::PS2ReadAfterACK(), v0::PS2WriteData(), v0::RegisterDevice(), and RegisterInterruptHandler().
Referenced by DriverEntry().
InitializeMouse()
int InitializeMouse ()
Definition at line 153 of file mouse.c.
 {
     PS2WriteData(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_RESET);
     uint8_t test = PS2ReadData();
     if (test != PS2_MOUSE_RESP_TEST_PASSED &&
         test != PS2_MOUSE_RESP_ACK)
     {
         KernelLog("PS/2 mouse reset failed! (%#x)", test);
         return -EFAULT;
     }
     RegisterInterruptHandler(12, PS2MouseInterruptHandler);
     MouseDevID = RegisterDevice(INPUT_TYPE_MOUSE, &MouseOps);
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_SET_DEFAULTS);
     PS2ReadData();
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_ENABLE_DATA_REPORTING);
     MouseSampleRate(200);
     MouseSampleRate(100);
     MouseSampleRate(80);
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_READ_ID);
     uint8_t Device2ID = PS2ReadData();
     KernelLog("PS/2 Mouse ID: %#x", Device2ID);
     MouseSampleRate(200);
     MouseSampleRate(200);
     MouseSampleRate(80);
     PS2WriteCommand(PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT);
     PS2WriteData(PS2_MOUSE_CMD_READ_ID);
     Device2ID = PS2ReadData();
     KernelLog("PS/2 Mouse ID: %#x", Device2ID);
     if (Device2ID >= 3 && Device2ID <= 4)
         FourPackets = true;
     if (Device2ID == 4)
         MouseButton45 = true;
     return 0;
 }
References Device2ID, EFAULT, FourPackets, INPUT_TYPE_MOUSE, KernelLog(), MouseButton45, MouseDevID, MouseOps, MouseSampleRate(), PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT, PS2_MOUSE_CMD_ENABLE_DATA_REPORTING, PS2_MOUSE_CMD_READ_ID, PS2_MOUSE_CMD_RESET, PS2_MOUSE_CMD_SET_DEFAULTS, PS2_MOUSE_RESP_ACK, PS2_MOUSE_RESP_TEST_PASSED, PS2MouseInterruptHandler(), v0::PS2ReadData(), v0::PS2WriteCommand(), v0::PS2WriteData(), v0::RegisterDevice(), RegisterInterruptHandler(), and test.
Referenced by DriverEntry().
PS2KbdInterruptHandler()
void PS2KbdInterruptHandler (TrapFrame *)
Definition at line 178 of file keyboard.c.
 {
     uint8_t sc = inb(PS2_DATA);
     if (sc == PS2_KBD_RESP_ACK ||
         sc == PS2_KBD_RESP_ECHO ||
         sc == PS2_KBD_RESP_RESEND)
         return;
     if (sc == 0xE0)
     {
         IsE0 = true;
         return;
     }
     if (sc == 0xE1)
     {
         IsE1 = true;
         return;
     }
     switch (KeyboardScanCodeSet)
     {
     case PS2_KBD_SC_SET_1:
     case PS2_KBD_SC_SET_2:
     {
         if (IsE0)
         {
             IsE0 = false;
             ReportKeyboardEvent(KeyboardDevID, ScanCodeSet1mm[sc], sc < 0x90);
             return;
         }
         else
         {
             bool released = sc & 0x80;
             uint8_t scFinal = released ? sc & 0x7F : sc;
             ReportKeyboardEvent(KeyboardDevID, ScanCodeSet1[scFinal], !released);
             return;
         }
     }
     /* FIXME: https://wiki.osdev.org/PS/2_Keyboard */
     // case PS2_KBD_SC_SET_2:
     // {
     //  break;
     // }
     case PS2_KBD_SC_SET_3:
     {
         ReportKeyboardEvent(KeyboardDevID, ScanCodeSet3[sc], true);
         ReportKeyboardEvent(KeyboardDevID, ScanCodeSet3[sc], false);
         break;
     }
     default:
     {
         if (IsE0)
             IsE0 = false;
         KernelLog("Unknown PS/2 Keyboard Scan Code Set: %#x", KeyboardScanCodeSet);
         break;
     }
     }
 }
References inb(), IsE0, IsE1, KernelLog(), KeyboardDevID, KeyboardScanCodeSet, PS2_DATA, PS2_KBD_RESP_ACK, PS2_KBD_RESP_ECHO, PS2_KBD_RESP_RESEND, PS2_KBD_SC_SET_1, PS2_KBD_SC_SET_2, PS2_KBD_SC_SET_3, ReportKeyboardEvent(), ScanCodeSet1, ScanCodeSet1mm, and ScanCodeSet3.
Referenced by InitializeKeyboard().
PS2MouseInterruptHandler()
void PS2MouseInterruptHandler (TrapFrame *)
Definition at line 33 of file mouse.c.
 {
     uint8_t data = PS2ReadData();
     if (data == PS2_MOUSE_RESP_ACK ||
         data == PS2_MOUSE_RESP_RESEND)
         return;
     if (!PacketReady)
     {
         switch (Cycle)
         {
         case 0:
         {
             if ((data & 0b00001000 /* Always 1 */) == 0)
                 return;
             Packet.Base.Raw = data;
             Cycle++;
             break;
         }
         case 1:
         {
             Packet.XMovement = data;
             Cycle++;
             break;
         }
         case 2:
         {
             Packet.YMovement = data;
             if (FourPackets)
                 Cycle++;
             else
             {
                 Cycle = 0;
                 PacketReady = true;
             }
             break;
         }
         case 3:
         {
             Packet.ZMovement.Raw = data;
             Cycle = 0;
             PacketReady = true;
             break;
         }
         default:
             break;
         }
         return;
     }
 /* https://stackoverflow.com/a/3208376/9352057 */
 #define BYTE_TO_BINARY_PATTERN "%c%c%c%c%c%c%c%c"
 #define BYTE_TO_BINARY(byte)         \
     ((byte) & 0x80 ? '1' : '0'),     \
         ((byte) & 0x40 ? '1' : '0'), \
         ((byte) & 0x20 ? '1' : '0'), \
         ((byte) & 0x10 ? '1' : '0'), \
         ((byte) & 0x08 ? '1' : '0'), \
         ((byte) & 0x04 ? '1' : '0'), \
         ((byte) & 0x02 ? '1' : '0'), \
         ((byte) & 0x01 ? '1' : '0')
     DebugLog("PS/2 Mouse Packet: [" BYTE_TO_BINARY_PATTERN ":" BYTE_TO_BINARY_PATTERN ":" BYTE_TO_BINARY_PATTERN ":" BYTE_TO_BINARY_PATTERN "] LB:%d RB:%d MB:%d A1:%d XS:%d YS:%d XO:%d YO:%d | X:%03d Y:%03d | Z:%d B4:%d B5:%d A0:%d A0:%d",
              BYTE_TO_BINARY(Packet.Base.Raw),
              BYTE_TO_BINARY(Packet.XMovement),
              BYTE_TO_BINARY(Packet.YMovement),
              BYTE_TO_BINARY(Packet.ZMovement.Raw),
              Packet.Base.LeftButton, Packet.Base.RightButton, Packet.Base.MiddleButton,
              Packet.Base.Always1,
              Packet.Base.XSign, Packet.Base.YSign,
              Packet.Base.XOverflow, Packet.Base.YOverflow,
              Packet.XMovement, Packet.YMovement,
              Packet.ZMovement.Z, Packet.ZMovement.Button4, Packet.ZMovement.Button5,
              Packet.ZMovement.Always0, Packet.ZMovement.Always0_2);
     int X, Y;
     X = Packet.XMovement - (Packet.Base.XSign ? 256 : 0);
     Y = Packet.YMovement - (Packet.Base.YSign ? 256 : 0);
     if (Packet.Base.XOverflow)
         X = 0;
     if (Packet.Base.YOverflow)
         Y = 0;
     mir.Type = INPUT_TYPE_MOUSE;
     mir.Device = MouseDevID;
     mir.Mouse.LeftButton = Packet.Base.LeftButton;
     mir.Mouse.RightButton = Packet.Base.RightButton;
     mir.Mouse.MiddleButton = Packet.Base.MiddleButton;
     mir.Mouse.Button4 = Packet.ZMovement.Button4;
     mir.Mouse.Button5 = Packet.ZMovement.Button5;
     mir.Mouse.X = X;
     mir.Mouse.Y = -Y;
     mir.Mouse.Z = Packet.ZMovement.Z;
     ReportInputEvent(&mir);
     PacketReady = false;
 }
References PS2_MOUSE_PACKET::Base, BYTE_TO_BINARY, BYTE_TO_BINARY_PATTERN, Cycle, DebugLog, InputReport::Device, FourPackets, INPUT_TYPE_MOUSE, mir, MouseDevID, Packet, PacketReady, PS2_MOUSE_RESP_ACK, PS2_MOUSE_RESP_RESEND, v0::PS2ReadData(), v0::ReportInputEvent(), InputReport::Type, X, PS2_MOUSE_PACKET::XMovement, PS2_MOUSE_PACKET::YMovement, and PS2_MOUSE_PACKET::ZMovement.
Referenced by InitializeMouse().
Variable Documentation
Device1ID
uint8_t Device1ID[] extern
Definition at line 92 of file main.c.
Referenced by DetectPS2Keyboard(), and DriverProbe().
Device2ID
uint8_t Device2ID[] extern
Definition at line 93 of file main.c.
Referenced by DetectPS2Mouse(), DriverProbe(), and InitializeMouse().