Fennix: Userspace/apps/base/bash/lib/readline/kill.c File Reference
kill.c File Reference
#include <sys/types.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define DEFAULT_MAX_KILLS 10
Functions
static int _rl_copy_to_kill_ring (char *, int)
static int region_kill_internal (int)
static int _rl_copy_word_as_kill (int, int)
static int rl_yank_nth_arg_internal (int, int, int)
int rl_set_retained_kills (int num)
int rl_kill_text (int from, int to)
int rl_kill_word (int count, int key)
int rl_backward_kill_word (int count, int key)
int rl_kill_line (int direction, int key)
int rl_backward_kill_line (int direction, int key)
int rl_kill_full_line (int count, int key)
int rl_unix_word_rubout (int count, int key)
int rl_unix_filename_rubout (int count, int key)
int rl_unix_line_discard (int count, int key)
int rl_copy_region_to_kill (int count, int key)
int rl_kill_region (int count, int key)
int rl_copy_forward_word (int count, int key)
int rl_copy_backward_word (int count, int key)
int rl_yank (int count, int key)
int rl_yank_pop (int count, int key)
int rl_vi_yank_pop (int count, int key)
int rl_yank_nth_arg (int count, int key)
int rl_yank_last_arg (int count, int key)
char * _rl_bracketed_text (size_t *lenp)
int rl_bracketed_paste_begin (int count, int key)
int _rl_read_bracketed_paste_prefix (int c)
int _rl_bracketed_read_key ()
int _rl_bracketed_read_mbstring (char *mb, int mlen)
Variables
static int rl_max_kills = DEFAULT_MAX_KILLS
static char ** rl_kill_ring = (char **)NULL
static int rl_kill_index
static int rl_kill_ring_length
Macro Definition Documentation
DEFAULT_MAX_KILLS
#define DEFAULT_MAX_KILLS 10
Definition at line 59 of file kill.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file kill.c.
Function Documentation
_rl_bracketed_read_key()
int _rl_bracketed_read_key (void)
Definition at line 809 of file kill.c.
 {
   int c, r;
   char *pbuf;
   size_t pblen;
   RL_SETSTATE(RL_STATE_MOREINPUT);
   c = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   if (c < 0)
     return -1;
   /* read pasted data with bracketed-paste mode enabled. */
   if (_rl_enable_bracketed_paste && c == ESC && (r = _rl_read_bracketed_paste_prefix (c)) == 1)
     {
       pbuf = _rl_bracketed_text (&pblen);
       if (pblen == 0)
     {
       xfree (pbuf);
       return 0;     /* XXX */
     }
       c = (unsigned char)pbuf[0];
       if (pblen > 1)
     {
       while (--pblen > 0)
         _rl_unget_char ((unsigned char)pbuf[pblen]);
     }
       xfree (pbuf);
     }
   return c;
 }
References _rl_bracketed_text(), _rl_enable_bracketed_paste, _rl_read_bracketed_paste_prefix(), _rl_unget_char(), c, ESC, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, RL_UNSETSTATE, and xfree.
Referenced by _rl_arg_dispatch(), _rl_bracketed_read_mbstring(), _rl_char_search(), and rl_vi_domove_getchar().
_rl_bracketed_read_mbstring()
int _rl_bracketed_read_mbstring (char * mb, int mlen)
Definition at line 847 of file kill.c.
 {
   int c, r;
   c = _rl_bracketed_read_key ();
   if (c < 0)
     return -1;
 #if defined (HANDLE_MULTIBYTE)
   if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     c = _rl_read_mbstring (c, mb, mlen);
   else
 #endif
     mb[0] = c;
   mb[mlen] = '\0';      /* just in case */
   return c;
 }
References _rl_bracketed_read_key(), c, MB_CUR_MAX, and rl_byte_oriented.
Referenced by _rl_vi_callback_getchar().
_rl_bracketed_text()
char* _rl_bracketed_text (size_t * lenp)
Definition at line 708 of file kill.c.
 {
   int c;
   size_t len, cap;
   char *buf;
   len = 0;
   buf = xmalloc (cap = 64);
   buf[0] = '\0';
   RL_SETSTATE (RL_STATE_MOREINPUT);
   while ((c = rl_read_key ()) >= 0)
     {
       if (RL_ISSTATE (RL_STATE_MACRODEF))
     _rl_add_macro_char (c);
       if (c == '\r')        /* XXX */
     c = '\n';
       if (len == cap)
     buf = xrealloc (buf, cap *= 2);
       buf[len++] = c;
       if (len >= BRACK_PASTE_SLEN && c == BRACK_PASTE_LAST &&
       STREQN (buf + len - BRACK_PASTE_SLEN, BRACK_PASTE_SUFF, BRACK_PASTE_SLEN))
     {
       len -= BRACK_PASTE_SLEN;
       break;
     }
     }
   RL_UNSETSTATE (RL_STATE_MOREINPUT);
   if (c >= 0)
     {
       if (len == cap)
     buf = xrealloc (buf, cap + 1);
       buf[len] = '\0';
     }
   if (lenp)
     *lenp = len;
   return (buf);
 }
References _rl_add_macro_char(), BRACK_PASTE_LAST, BRACK_PASTE_SLEN, BRACK_PASTE_SUFF, buf, c, len, RL_ISSTATE, rl_read_key(), RL_SETSTATE, RL_STATE_MACRODEF, RL_STATE_MOREINPUT, RL_UNSETSTATE, STREQN, xmalloc, and xrealloc.
Referenced by _rl_bracketed_read_key(), _rl_isearch_dispatch(), rl_bracketed_paste_begin(), and rl_vi_overstrike_bracketed_paste().
_rl_copy_to_kill_ring()
static int _rl_copy_to_kill_ring (char * text, int append) static
Definition at line 91 of file kill.c.
 {
   char *old, *new;
   int slot;
   /* First, find the slot to work with. */
   if (_rl_last_command_was_kill == 0 || rl_kill_ring == 0)
     {
       /* Get a new slot.  */
       if (rl_kill_ring == 0)
     {
       /* If we don't have any defined, then make one. */
       rl_kill_ring = (char **)
         xmalloc (((rl_kill_ring_length = 1) + 1) * sizeof (char *));
       rl_kill_ring[slot = 0] = (char *)NULL;
     }
       else
     {
       /* We have to add a new slot on the end, unless we have
          exceeded the max limit for remembering kills. */
       slot = rl_kill_ring_length;
       if (slot == rl_max_kills)
         {
           register int i;
           xfree (rl_kill_ring[0]);
           for (i = 0; i < slot; i++)
         rl_kill_ring[i] = rl_kill_ring[i + 1];
         }
       else
         {
           slot = rl_kill_ring_length += 1;
           rl_kill_ring = (char **)xrealloc (rl_kill_ring, (slot + 1) * sizeof (char *));
         }
       rl_kill_ring[--slot] = (char *)NULL;
     }
     }
   else
     slot = rl_kill_ring_length - 1;
   /* If the last command was a kill, prepend or append. */
   if (_rl_last_command_was_kill && rl_kill_ring[slot] && rl_editing_mode != vi_mode)
     {
       old = rl_kill_ring[slot];
       new = (char *)xmalloc (1 + strlen (old) + strlen (text));
       if (append)
     {
       strcpy (new, old);
       strcat (new, text);
     }
       else
     {
       strcpy (new, text);
       strcat (new, old);
     }
       xfree (old);
       xfree (text);
       rl_kill_ring[slot] = new;
     }
   else
     rl_kill_ring[slot] = text;
   rl_kill_index = slot;
   return 0;
 }
References _rl_last_command_was_kill, append(), i, NULL, old, rl_editing_mode, rl_kill_index, rl_kill_ring, rl_kill_ring_length, rl_max_kills, slot, strcat, strcpy, strlen(), text, vi_mode, xfree, xmalloc, and xrealloc.
Referenced by region_kill_internal(), and rl_kill_text().
_rl_copy_word_as_kill()
static int _rl_copy_word_as_kill (int count, int dir) static
Definition at line 463 of file kill.c.
 {
   int om, op, r;
   om = rl_mark;
   op = rl_point;
   if (dir > 0)
     rl_forward_word (count, 0);
   else
     rl_backward_word (count, 0);
   rl_mark = rl_point;
   if (dir > 0)
     rl_backward_word (count, 0);
   else
     rl_forward_word (count, 0);
   r = region_kill_internal (0);
   rl_mark = om;
   rl_point = op;
   return r;
 }
References count, dir, region_kill_internal(), rl_backward_word(), rl_forward_word(), rl_mark, and rl_point.
Referenced by rl_copy_backward_word(), and rl_copy_forward_word().
_rl_read_bracketed_paste_prefix()
int _rl_read_bracketed_paste_prefix (int c)
Definition at line 774 of file kill.c.
 {
   char pbuf[BRACK_PASTE_SLEN+1], *pbpref;
   int key, ind, j;
   pbpref = BRACK_PASTE_PREF;        /* XXX - debugging */
   if (c != pbpref[0])
     return (0);
   pbuf[ind = 0] = c;
   while (ind < BRACK_PASTE_SLEN-1 &&
      (RL_ISSTATE (RL_STATE_INPUTPENDING|RL_STATE_MACROINPUT) == 0) &&
          _rl_pushed_input_available () == 0 &&
          _rl_input_queued (0))
     {
       key = rl_read_key ();     /* XXX - for now */
       if (key < 0)
     break;
       pbuf[++ind] = key;
       if (pbuf[ind] != pbpref[ind])
         break;
     }
   if (ind < BRACK_PASTE_SLEN-1)     /* read incomplete sequence */
     {
       while (ind >= 0)
     _rl_unget_char (pbuf[ind--]);
       return (key < 0 ? key : 0);
     }
   return (key < 0 ? key : 1);
 }
References _rl_input_queued(), _rl_pushed_input_available(), _rl_unget_char(), BRACK_PASTE_PREF, BRACK_PASTE_SLEN, c, j, RL_ISSTATE, rl_read_key(), RL_STATE_INPUTPENDING, and RL_STATE_MACROINPUT.
Referenced by _rl_bracketed_read_key(), _rl_isearch_dispatch(), and _rl_nsearch_dispatch().
region_kill_internal()
static int region_kill_internal (int delete) static
Definition at line 423 of file kill.c.
 {
   char *text;
   if (rl_mark != rl_point)
     {
       text = rl_copy_text (rl_point, rl_mark);
       if (delete)
     rl_delete_text (rl_point, rl_mark);
       _rl_copy_to_kill_ring (text, rl_point < rl_mark);
     }
   _rl_fix_point (1);
   _rl_last_command_was_kill++;
   return 0;
 }
References _rl_copy_to_kill_ring(), _rl_fix_point(), _rl_last_command_was_kill, rl_copy_text(), rl_delete_text(), rl_mark, rl_point, and text.
Referenced by _rl_copy_word_as_kill(), rl_copy_region_to_kill(), and rl_kill_region().
rl_backward_kill_line()
int rl_backward_kill_line (int direction, int key)
Definition at line 265 of file kill.c.
 {
   int orig_point;
   if (direction < 0)
     return (rl_kill_line (1, key));
   else
     {
       if (rl_point == 0)
     rl_ding ();
       else
     {
       orig_point = rl_point;
       rl_beg_of_line (1, key);
       if (rl_point != orig_point)
         rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
         rl_mark = rl_point;
     }
     }
   return 0;
 }
References emacs_mode, rl_beg_of_line(), rl_ding(), rl_editing_mode, rl_kill_line(), rl_kill_text(), rl_mark, and rl_point.
Referenced by rl_kill_line().
rl_backward_kill_word()
int rl_backward_kill_word (int count, int key)
Definition at line 220 of file kill.c.
 {
   int orig_point;
   if (count < 0)
     return (rl_kill_word (-count, key));
   else
     {
       orig_point = rl_point;
       rl_backward_word (count, key);
       if (rl_point != orig_point)
     rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References count, emacs_mode, rl_backward_word(), rl_editing_mode, rl_kill_text(), rl_kill_word(), rl_mark, and rl_point.
Referenced by rl_kill_word().
rl_bracketed_paste_begin()
int rl_bracketed_paste_begin (int count, int key)
Definition at line 757 of file kill.c.
 {
   int retval, c;
   size_t len, cap;
   char *buf;
   buf = _rl_bracketed_text (&len);
   rl_mark = rl_point;
   retval = rl_insert_text (buf) == len ? 0 : 1;
   if (_rl_enable_active_region)
     rl_activate_mark ();
   xfree (buf);
   return (retval);
 }
References _rl_bracketed_text(), _rl_enable_active_region, buf, c, len, retval, rl_activate_mark(), rl_insert_text(), rl_mark, rl_point, and xfree.
Referenced by _rl_isearch_dispatch(), _rl_nsearch_dispatch(), and bind_bracketed_paste_prefix().
rl_copy_backward_word()
int rl_copy_backward_word (int count, int key)
Definition at line 500 of file kill.c.
 {
   if (count < 0)
     return (rl_copy_forward_word (-count, key));
   return (_rl_copy_word_as_kill (count, -1));
 }
References _rl_copy_word_as_kill(), count, and rl_copy_forward_word().
Referenced by rl_copy_forward_word().
rl_copy_forward_word()
int rl_copy_forward_word (int count, int key)
Definition at line 491 of file kill.c.
 {
   if (count < 0)
     return (rl_copy_backward_word (-count, key));
   return (_rl_copy_word_as_kill (count, 1));
 }
References _rl_copy_word_as_kill(), count, and rl_copy_backward_word().
Referenced by rl_copy_backward_word().
rl_copy_region_to_kill()
int rl_copy_region_to_kill (int count, int key)
Definition at line 442 of file kill.c.
 {
   return (region_kill_internal (0));
 }
References region_kill_internal().
rl_kill_full_line()
int rl_kill_full_line (int count, int key)
Definition at line 290 of file kill.c.
 {
   rl_begin_undo_group ();
   rl_point = 0;
   rl_kill_text (rl_point, rl_end);
   rl_mark = 0;
   rl_end_undo_group ();
   return 0;
 }
References rl_begin_undo_group(), rl_end, rl_end_undo_group(), rl_kill_text(), rl_mark, and rl_point.
rl_kill_line()
int rl_kill_line (int direction, int key)
Definition at line 243 of file kill.c.
 {
   int orig_point;
   if (direction < 0)
     return (rl_backward_kill_line (1, key));
   else
     {
       orig_point = rl_point;
       rl_end_of_line (1, key);
       if (orig_point != rl_point)
     rl_kill_text (orig_point, rl_point);
       rl_point = orig_point;
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References emacs_mode, rl_backward_kill_line(), rl_editing_mode, rl_end_of_line(), rl_kill_text(), rl_mark, and rl_point.
Referenced by rl_backward_kill_line().
rl_kill_region()
int rl_kill_region (int count, int key)
Definition at line 449 of file kill.c.
 {
   int r, npoint;
   npoint = (rl_point < rl_mark) ? rl_point : rl_mark;
   r = region_kill_internal (1);
   rl_point = npoint;
   _rl_fix_point (1);
   return r;
 }
References _rl_fix_point(), region_kill_internal(), rl_mark, and rl_point.
rl_kill_text()
int rl_kill_text (int from, int to)
Definition at line 163 of file kill.c.
 {
   char *text;
   /* Is there anything to kill? */
   if (from == to)
     {
       _rl_last_command_was_kill++;
       return 0;
     }
   text = rl_copy_text (from, to);
   /* Delete the copied text from the line. */
   rl_delete_text (from, to);
   _rl_copy_to_kill_ring (text, from < to);
   _rl_last_command_was_kill++;
   return 0;
 }
References _rl_copy_to_kill_ring(), _rl_last_command_was_kill, rl_copy_text(), rl_delete_text(), and text.
Referenced by _rl_overwrite_rubout(), _rl_rubout_char(), rl_backward_kill_line(), rl_backward_kill_word(), rl_delete(), rl_kill_full_line(), rl_kill_line(), rl_kill_word(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_delete(), rl_vi_rubout(), rl_vi_unix_word_rubout(), vi_change_dispatch(), vi_delete_dispatch(), and vi_yank_dispatch().
rl_kill_word()
int rl_kill_word (int count, int key)
Definition at line 197 of file kill.c.
 {
   int orig_point;
   if (count < 0)
     return (rl_backward_kill_word (-count, key));
   else
     {
       orig_point = rl_point;
       rl_forward_word (count, key);
       if (rl_point != orig_point)
     rl_kill_text (orig_point, rl_point);
       rl_point = orig_point;
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References count, emacs_mode, rl_backward_kill_word(), rl_editing_mode, rl_forward_word(), rl_kill_text(), rl_mark, and rl_point.
Referenced by bind_arrow_keys_internal(), and rl_backward_kill_word().
rl_set_retained_kills()
int rl_set_retained_kills (int num)
Definition at line 81 of file kill.c.
 {
   return 0;
 }
rl_unix_filename_rubout()
int rl_unix_filename_rubout (int count, int key)
Definition at line 339 of file kill.c.
 {
   int orig_point, c;
   if (rl_point == 0)
     rl_ding ();
   else
     {
       orig_point = rl_point;
       if (count <= 0)
     count = 1;
       while (count--)
     {
       c = rl_line_buffer[rl_point - 1];
       /* First move backwards through whitespace */
       while (rl_point && whitespace (c))
         {
           rl_point--;
           c = rl_line_buffer[rl_point - 1];
         }
       /* Consume one or more slashes. */
       if (c == '/')
         {
           int i;
           i = rl_point - 1;
           while (i > 0 && c == '/')
         c = rl_line_buffer[--i];
           if (i == 0 || whitespace (c))
         {
           rl_point = i + whitespace (c);
           continue; /* slashes only */
         }
           c = '/';
         }
       while (rl_point && (whitespace (c) || c == '/'))
         {
           rl_point--;
           c = rl_line_buffer[rl_point - 1];
         }
       while (rl_point && (whitespace (c) == 0) && c != '/')
         {
           rl_point--;   /* XXX - multibyte? */
           c = rl_line_buffer[rl_point - 1];
         }
     }
       rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References c, count, emacs_mode, i, rl_ding(), rl_editing_mode, rl_kill_text(), rl_line_buffer, rl_mark, rl_point, and whitespace.
rl_unix_line_discard()
int rl_unix_line_discard (int count, int key)
Definition at line 406 of file kill.c.
 {
   if (rl_point == 0)
     rl_ding ();
   else
     {
       rl_kill_text (rl_point, 0);
       rl_point = 0;
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References emacs_mode, rl_ding(), rl_editing_mode, rl_kill_text(), rl_mark, and rl_point.
Referenced by _rl_bind_tty_special_chars(), _rl_nsearch_dispatch(), rl_vi_overstrike_kill_line(), and rl_vi_replace().
rl_unix_word_rubout()
int rl_unix_word_rubout (int count, int key)
Definition at line 307 of file kill.c.
 {
   int orig_point;
   if (rl_point == 0)
     rl_ding ();
   else
     {
       orig_point = rl_point;
       if (count <= 0)
     count = 1;
       while (count--)
     {
       while (rl_point && whitespace (rl_line_buffer[rl_point - 1]))
         rl_point--;
       while (rl_point && (whitespace (rl_line_buffer[rl_point - 1]) == 0))
         rl_point--;     /* XXX - multibyte? */
     }
       rl_kill_text (orig_point, rl_point);
       if (rl_editing_mode == emacs_mode)
     rl_mark = rl_point;
     }
   return 0;
 }
References count, emacs_mode, rl_ding(), rl_editing_mode, rl_kill_text(), rl_line_buffer, rl_mark, rl_point, and whitespace.
Referenced by _rl_bind_tty_special_chars(), _rl_isearch_dispatch(), and _rl_nsearch_dispatch().
rl_vi_yank_pop()
int rl_vi_yank_pop (int count, int key)
Definition at line 560 of file kill.c.
 {
   int l, n, origpoint;
   if (((rl_last_func != rl_vi_yank_pop) && (rl_last_func != rl_vi_put)) ||
       !rl_kill_ring)
     {
       _rl_abort_internal ();
       return 1;
     }
   l = strlen (rl_kill_ring[rl_kill_index]);
 #if 0 /* TAG:readline-8.3 8/29/2022 matteopaolini1995@gmail.com */
   origpoint = rl_point;
   n = rl_point - l + 1;
 #else
   n = rl_point - l;
 #endif
   if (n >= 0 && STREQN (rl_line_buffer + n, rl_kill_ring[rl_kill_index], l))
     {
 #if 0 /* TAG:readline-8.3 */
       rl_delete_text (n, n + l);        /* remember vi cursor positioning */
       rl_point = origpoint - l;
 #else
       rl_delete_text (n, rl_point);
       rl_point = n;
 #endif
       rl_kill_index--;
       if (rl_kill_index < 0)
     rl_kill_index = rl_kill_ring_length - 1;
       rl_vi_put (1, 'p');
       return 0;
     }
   else
     {
       _rl_abort_internal ();
       return 1;
     }
 }
References _rl_abort_internal(), l, n, rl_delete_text(), rl_kill_index, rl_kill_ring, rl_kill_ring_length, rl_last_func, rl_line_buffer, rl_point, rl_vi_put(), STREQN, and strlen().
rl_yank()
int rl_yank (int count, int key)
Definition at line 510 of file kill.c.
 {
   if (rl_kill_ring == 0)
     {
       _rl_abort_internal ();
       return 1;
     }
   _rl_set_mark_at_pos (rl_point);
   rl_insert_text (rl_kill_ring[rl_kill_index]);
   return 0;
 }
References _rl_abort_internal(), _rl_set_mark_at_pos(), rl_insert_text(), rl_kill_index, rl_kill_ring, and rl_point.
Referenced by _rl_isearch_dispatch(), rl_vi_overstrike_yank(), rl_vi_put(), rl_vi_replace(), and rl_yank_pop().
rl_yank_last_arg()
int rl_yank_last_arg (int count, int key)
Definition at line 668 of file kill.c.
 {
   static int history_skip = 0;
   static int explicit_arg_p = 0;
   static int count_passed = 1;
   static int direction = 1;
   static int undo_needed = 0;
   int retval;
   if (rl_last_func != rl_yank_last_arg)
     {
       history_skip = 0;
       explicit_arg_p = rl_explicit_arg;
       count_passed = count;
       direction = 1;
     }
   else
     {
       if (undo_needed)
     rl_do_undo ();
       if (count < 0)        /* XXX - was < 1 */
         direction = -direction;
       history_skip += direction;
       if (history_skip < 0)
     history_skip = 0;
     }
   if (explicit_arg_p)
     retval = rl_yank_nth_arg_internal (count_passed, key, history_skip);
   else
     retval = rl_yank_nth_arg_internal ('$', key, history_skip);
   undo_needed = retval == 0;
   return retval;
 }
References count, retval, rl_do_undo(), rl_explicit_arg, rl_last_func, and rl_yank_nth_arg_internal().
rl_yank_nth_arg()
int rl_yank_nth_arg (int count, int key)
Definition at line 659 of file kill.c.
 {
   return (rl_yank_nth_arg_internal (count, key, 0));
 }
References count, and rl_yank_nth_arg_internal().
Referenced by rl_vi_yank_arg().
rl_yank_nth_arg_internal()
static int rl_yank_nth_arg_internal (int count, int key, int history_skip) static
Definition at line 604 of file kill.c.
 {
   register HIST_ENTRY *entry;
   char *arg;
   int i, pos;
   pos = where_history ();
   if (history_skip)
     {
       for (i = 0; i < history_skip; i++)
     entry = previous_history ();
     }
   entry = previous_history ();
   history_set_pos (pos);
   if (entry == 0)
     {
       rl_ding ();
       return 1;
     }
   arg = history_arg_extract (count, count, entry->line);
   if (!arg || !*arg)
     {
       rl_ding ();
       FREE (arg);
       return 1;
     }
   rl_begin_undo_group ();
   _rl_set_mark_at_pos (rl_point);
 #if defined (VI_MODE)
   /* Vi mode always inserts a space before yanking the argument, and it
      inserts it right *after* rl_point. */
   if (rl_editing_mode == vi_mode && _rl_keymap == vi_movement_keymap)
     {
       rl_vi_append_mode (1, key);
       rl_insert_text (" ");
     }
 #endif /* VI_MODE */
   rl_insert_text (arg);
   xfree (arg);
   rl_end_undo_group ();
   return 0;
 }
References _rl_keymap, _rl_set_mark_at_pos(), count, FREE, history_arg_extract(), history_set_pos(), i, pos, previous_history(), rl_begin_undo_group(), rl_ding(), rl_editing_mode, rl_end_undo_group(), rl_insert_text(), rl_point, rl_vi_append_mode(), vi_mode, vi_movement_keymap, where_history(), and xfree.
Referenced by rl_yank_last_arg(), and rl_yank_nth_arg().
rl_yank_pop()
int rl_yank_pop (int count, int key)
Definition at line 528 of file kill.c.
 {
   int l, n;
   if (((rl_last_func != rl_yank_pop) && (rl_last_func != rl_yank)) ||
       !rl_kill_ring)
     {
       _rl_abort_internal ();
       return 1;
     }
   l = strlen (rl_kill_ring[rl_kill_index]);
   n = rl_point - l;
   if (n >= 0 && STREQN (rl_line_buffer + n, rl_kill_ring[rl_kill_index], l))
     {
       rl_delete_text (n, rl_point);
       rl_point = n;
       rl_kill_index--;
       if (rl_kill_index < 0)
     rl_kill_index = rl_kill_ring_length - 1;
       rl_yank (1, 0);
       return 0;
     }
   else
     {
       _rl_abort_internal ();
       return 1;
     }
 }
References _rl_abort_internal(), l, n, rl_delete_text(), rl_kill_index, rl_kill_ring, rl_kill_ring_length, rl_last_func, rl_line_buffer, rl_point, rl_yank(), STREQN, and strlen().
Variable Documentation
rl_kill_index
int rl_kill_index static
Definition at line 68 of file kill.c.
Referenced by _rl_copy_to_kill_ring(), rl_vi_yank_pop(), rl_yank(), and rl_yank_pop().
rl_kill_ring
char** rl_kill_ring = (char **)NULL static
Definition at line 65 of file kill.c.
Referenced by _rl_copy_to_kill_ring(), rl_vi_yank_pop(), rl_yank(), and rl_yank_pop().
rl_kill_ring_length
int rl_kill_ring_length static
Definition at line 71 of file kill.c.
Referenced by _rl_copy_to_kill_ring(), rl_vi_yank_pop(), and rl_yank_pop().
rl_max_kills
int rl_max_kills = DEFAULT_MAX_KILLS static
Definition at line 62 of file kill.c.
Referenced by _rl_copy_to_kill_ring().