Fennix: Drivers/storage/ata/main.c File Reference
main.c File Reference
#include <errno.h>
#include <regs.h>
#include <base.h>
#include <io.h>
Functions
bool IsATAPresent ()
void MasterInterruptHandler (TrapFrame *)
void SlaveInterruptHandler (TrapFrame *)
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
int DriverProbe ()
DriverInfo ("ata", "Advanced Technology Attachment Driver", "EnderIce2", 0, 0, 1, "GPLv3")
Function Documentation
DriverEntry()
int DriverEntry ()
A device may fail, but if the other one works, we can still use it.
This is the main function of the driver. This function should be used to initialize the PCI device and allocate resources.
If we have another driver using the PS/2 mouse, we need to override its interrupt handler.
Definition at line 43 of file main.c.
 {
     RegisterInterruptHandler(14, MasterInterruptHandler);
     RegisterInterruptHandler(15, SlaveInterruptHandler);
     return 0;
 }
References MasterInterruptHandler(), RegisterInterruptHandler(), and SlaveInterruptHandler().
DriverFinal()
int DriverFinal ()
This function is called when the driver is unloaded. This function should be used to stop the PCI device and free any resources.
Definition at line 51 of file main.c.
 {
     UnregisterInterruptHandler(14, MasterInterruptHandler);
     UnregisterInterruptHandler(15, SlaveInterruptHandler);
     return 0;
 }
References MasterInterruptHandler(), SlaveInterruptHandler(), and UnregisterInterruptHandler().
Referenced by _final().
DriverInfo()
DriverInfo ("ata" , "Advanced Technology Attachment Driver" , "EnderIce2" , 0 , 0 , 1 , "GPLv3")
DriverPanic()
int DriverPanic ()
This function is called when the kernel panics. This function should be used to stop the driver from sending interrupts or anything else that is not safe to do when the kernel panics.
Definition at line 59 of file main.c.
 {
     return 0;
 }
DriverProbe()
int DriverProbe ()
This is the first function that is called when the driver is loaded.
This function is to test if the driver is compatible with the hardware. Example: Like if there is a PCI device that the driver is for, or a CPU feature that etc.
Return 0 if the driver is compatible with the hardware. Otherwise, return a value that is not 0.
Note: In this function you cannot use variables that have constructors or destructors. Before DriverEntry, the constructors are called and after DriverFinalize, the destructors are called.
Definition at line 64 of file main.c.
 {
     if (!IsATAPresent())
         return -ENODEV;
     return 0;
 }
References ENODEV, and IsATAPresent().
IsATAPresent()
bool IsATAPresent ()
Definition at line 23 of file main.c.
 {
     outb(0x1F0 + 2, 0);
     outb(0x1F0 + 3, 0);
     outb(0x1F0 + 4, 0);
     outb(0x1F0 + 5, 0);
     outb(0x1F0 + 7, 0xEC);
     if (inb(0x1F0 + 7) == 0 || inb(0x1F0 + 1) != 0)
         return false;
     return true;
 }
References inb(), and outb().
Referenced by DriverProbe().
MasterInterruptHandler()
void MasterInterruptHandler (TrapFrame *)
Definition at line 35 of file main.c.
 {
 }
Referenced by DriverEntry(), and DriverFinal().
SlaveInterruptHandler()
void SlaveInterruptHandler (TrapFrame *)
Definition at line 39 of file main.c.
 {
 }
Referenced by DriverEntry(), and DriverFinal().