Fennix Userspace: Userspace/musl/src/stdio/vsnprintf.c File Reference
vsnprintf.c File Reference
#include "stdio_impl.h"
#include <limits.h>
#include <string.h>
#include <errno.h>
#include <stdint.h>
Data Structures
struct cookie
Macros
#define MIN(a, b) ((a) < (b) ? (a) : (b))
Functions
static size_t sn_write (FILE *f, const unsigned char *s, size_t l)
int vsnprintf (char *restrict s, size_t n, const char *restrict fmt, va_list ap)
Data Structure Documentation
cookie
struct cookie
Definition at line 9 of file fmemopen.c.
Data Fields
unsigned char * buf
char * buf
wchar_t * buf
char ** bufp
wchar_t ** bufp
size_t l
size_t len
mbstate_t mbs
int mode
size_t n
size_t pos
char * s
size_t size
size_t * sizep
size_t space
wchar_t * ws
Macro Definition Documentation
MIN
#define MIN (a, b) ((a) < (b) ? (a) : (b))
Definition at line 12 of file vsnprintf.c.
Function Documentation
sn_write()
static size_t sn_write (FILE * f, const unsigned char * s, size_t l) static
Definition at line 14 of file vsnprintf.c.
 {
     struct cookie *c = f->cookie;
     size_t k = MIN(c->n, f->wpos - f->wbase);
     if (k) {
         memcpy(c->s, f->wbase, k);
         c->s += k;
         c->n -= k;
     }
     k = MIN(c->n, l);
     if (k) {
         memcpy(c->s, s, k);
         c->s += k;
         c->n -= k;
     }
     *c->s = 0;
     f->wpos = f->wbase = f->buf;
     /* pretend to succeed, even if we discarded extra data */
     return l;
 }
References _IO_FILE::buf, c, _IO_FILE::cookie, f, k, l, memcpy(), MIN, s, _IO_FILE::wbase, and _IO_FILE::wpos.
Referenced by vsnprintf().
vsnprintf()
int vsnprintf (char *restrict s, size_t n, const char *restrict fmt, va_list ap)
Definition at line 35 of file vsnprintf.c.
 {
     unsigned char buf[1];
     char dummy[1];
     struct cookie c = { .s = n ? s : dummy, .n = n ? n-1 : 0 };
     FILE f = {
         .lbf = EOF,
         .write = sn_write,
         .lock = -1,
         .buf = buf,
         .cookie = &c,
     };
     if (n > INT_MAX) {
         errno = EOVERFLOW;
         return -1;
     }
     *c.s = 0;
     return vfprintf(&f, fmt, ap);
 }
References ap, buf, c, EOF, EOVERFLOW, errno, f, INT_MAX, _IO_FILE::lbf, n, s, sn_write(), and vfprintf().