Fennix: Userspace/mlibc/options/posix/include/sys/time.h File Reference
time.h File Reference
#include <abi-bits/time.h>
#include <abi-bits/signal.h>
#include <abi-bits/clockid_t.h>
#include <bits/ansi/time_t.h>
#include <abi-bits/suseconds_t.h>
#include <bits/posix/timer_t.h>
#include <bits/posix/timeval.h>
#include <sys/select.h>
Data Structures
struct timezone
Macros
#define timercmp(s, t, op)
#define TIMEVAL_TO_TIMESPEC(tv, ts)
#define TIMESPEC_TO_TIMEVAL(tv, ts)
Functions
int gettimeofday (struct timeval *__restrict result, void *__restrict unused)
void timeradd (const struct timeval *a, const struct timeval *b, struct timeval *res)
void timersub (const struct timeval *a, const struct timeval *b, struct timeval *res)
void timerclear (struct timeval *tvp)
int timerisset (struct timeval *tvp)
int getitimer (int which, struct itimerval *curr_value)
int setitimer (int which, const struct itimerval *new_value, struct itimerval *old_value)
int timer_create (clockid_t clockid, struct sigevent *__restrict sevp, timer_t *__restrict timerid)
int timer_settime (timer_t timerid, int flags, const struct itimerspec *__restrict new_value, struct itimerspec *__restrict old_value)
int timer_gettime (timer_t timerid, struct itimerspec *curr_value)
int timer_delete (timer_t timerid)
Data Structure Documentation
timezone
struct timezone
Definition at line 18 of file time.h.
Data Fields
int tz_dsttime
int tz_minuteswest
Macro Definition Documentation
timercmp
#define timercmp (s, t, op)
Value:
    ((s)->tv_sec == (t)->tv_sec ? \
    (s)->tv_usec op (t)->tv_usec : (s)->tv_sec op (t)->tv_sec)
Definition at line 32 of file time.h.
TIMESPEC_TO_TIMEVAL
#define TIMESPEC_TO_TIMEVAL (tv, ts)
Value:
    ( \
    (tv)->tv_sec = (ts)->tv_sec, \
    (tv)->tv_usec = (ts)->tv_nsec / 1000, \
    (void)0 )
Definition at line 50 of file time.h.
TIMEVAL_TO_TIMESPEC
#define TIMEVAL_TO_TIMESPEC (tv, ts)
Value:
    ( \
    (ts)->tv_sec = (tv)->tv_sec, \
    (ts)->tv_nsec = (tv)->tv_usec * 1000, \
    (void)0 )
Definition at line 46 of file time.h.
Function Documentation
getitimer()
int getitimer (int which, struct itimerval * curr_value)
Definition at line 54 of file sys-time-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getitimer, -1);
     if(int e = mlibc::sys_getitimer(which, curr_value); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getitimer().
gettimeofday()
int gettimeofday (struct timeval *__restrict result, void *__restrict unused)
Definition at line 10 of file sys-time-stubs.cpp.
{
     (void)unused; // Linux just ignores gettimeofday().
     if(result) {
         long nanos;
         if(int e = mlibc::sys_clock_get(CLOCK_REALTIME, &result->tv_sec, &nanos); e) {
             errno = e;
             return -1;
         }
         result->tv_usec = nanos / 1000;
     }
     return 0;
 }
References CLOCK_REALTIME, errno, mlibc::nanos, mlibc::sys_clock_get(), and Driver::void().
setitimer()
int setitimer (int which, const struct itimerval * new_value, struct itimerval * old_value)
Definition at line 63 of file sys-time-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setitimer, -1);
     if(int e = mlibc::sys_setitimer(which, new_value, old_value); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setitimer().
Referenced by alarm().
timer_create()
int timer_create (clockid_t clockid, struct sigevent *__restrict sevp, timer_t *__restrict timerid)
timer_delete()
int timer_delete (timer_t timerid)
Definition at line 87 of file sys-time-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
timer_gettime()
int timer_gettime (timer_t timerid, struct itimerspec * curr_value)
Definition at line 82 of file sys-time-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
timer_settime()
int timer_settime (timer_t timerid, int flags, const struct itimerspec *__restrict new_value, struct itimerspec *__restrict old_value)
timeradd()
void timeradd (const struct timeval * a, const struct timeval * b, struct timeval * res)
Definition at line 24 of file sys-time-stubs.cpp.
{
     res->tv_sec = a->tv_sec + b->tv_sec;
     res->tv_usec = a->tv_usec + b->tv_usec;
     while(res->tv_usec > 999999) {
         res->tv_usec -= 1000000;
         res->tv_sec += 1;
     }
 }
References b, timeval::tv_sec, and timeval::tv_usec.
Referenced by main().
timerclear()
void timerclear (struct timeval * tvp)
Definition at line 42 of file sys-time-stubs.cpp.
{
     tvp->tv_sec = 0;
     tvp->tv_usec = 0;
 }
References timeval::tv_sec, and timeval::tv_usec.
Referenced by main().
timerisset()
int timerisset (struct timeval * tvp)
Definition at line 47 of file sys-time-stubs.cpp.
{
     if(tvp->tv_sec != 0 || tvp->tv_usec != 0) {
         return 1;
     }
     return 0;
 }
References timeval::tv_sec, and timeval::tv_usec.
Referenced by main().
timersub()
void timersub (const struct timeval * a, const struct timeval * b, struct timeval * res)
Definition at line 33 of file sys-time-stubs.cpp.
{
     res->tv_sec = a->tv_sec - b->tv_sec;
     res->tv_usec = a->tv_usec - b->tv_usec;
     while(res->tv_usec < 0) {
         res->tv_usec += 1000000;
         res->tv_sec -= 1;
     }
 }
References b, timeval::tv_sec, and timeval::tv_usec.
Referenced by main().