Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/r_things.c File Reference
r_things.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "deh_main.h"
#include "doomdef.h"
#include "i_swap.h"
#include "i_system.h"
#include "z_zone.h"
#include "w_wad.h"
#include "r_local.h"
#include "doomstat.h"
Data Structures
struct maskdraw_t
Macros
#define MINZ (FRACUNIT*4)
#define BASEYCENTER 100
Functions
void R_InstallSpriteLump (int lump, unsigned frame, unsigned rotation, boolean flipped)
void R_InitSpriteDefs (char **namelist)
void R_InitSprites (char **namelist)
void R_ClearSprites (void)
vissprite_t * R_NewVisSprite (void)
void R_DrawMaskedColumn (column_t *column)
void R_DrawVisSprite (vissprite_t *vis, int x1, int x2)
void R_ProjectSprite (mobj_t *thing)
void R_AddSprites (sector_t *sec)
void R_DrawPSprite (pspdef_t *psp)
void R_DrawPlayerSprites (void)
void R_SortVisSprites (void)
void R_DrawSprite (vissprite_t *spr)
void R_DrawMasked (void)
Variables
fixed_t pspritescale
fixed_t pspriteiscale
lighttable_t ** spritelights
short negonearray [SCREENWIDTH]
short screenheightarray [SCREENWIDTH]
spritedef_t * sprites
int numsprites
spriteframe_t sprtemp [29]
int maxframe
char * spritename
vissprite_t vissprites [MAXVISSPRITES]
vissprite_t * vissprite_p
int newvissprite
vissprite_t overflowsprite
short * mfloorclip
short * mceilingclip
fixed_t spryscale
fixed_t sprtopscreen
vissprite_t vsprsortedhead
static short clipbot [SCREENWIDTH]
static short cliptop [SCREENWIDTH]
Data Structure Documentation
maskdraw_t
struct maskdraw_t
Definition at line 48 of file r_things.c.
Data Fields
int bottomclip
int column
int topclip
int x1
int x2
Macro Definition Documentation
BASEYCENTER
#define BASEYCENTER 100
Definition at line 41 of file r_things.c.
MINZ
#define MINZ (FRACUNIT*4)
Definition at line 40 of file r_things.c.
Function Documentation
R_AddSprites()
void R_AddSprites (sector_t * sec)
Definition at line 605 of file r_things.c.
 {
     mobj_t*     thing;
     int         lightnum;
     // BSP is traversed by subsector.
     // A sector might have been split into several
     //  subsectors during BSP building.
     // Thus we check whether its already added.
     if (sec->validcount == validcount)
     return;
     // Well, now it will be done.
     sec->validcount = validcount;
     lightnum = (sec->lightlevel >> LIGHTSEGSHIFT)+extralight;
     if (lightnum < 0)
     spritelights = scalelight[0];
     else if (lightnum >= LIGHTLEVELS)
     spritelights = scalelight[LIGHTLEVELS-1];
     else
     spritelights = scalelight[lightnum];
     // Handle all things in sector.
     for (thing = sec->thinglist ; thing ; thing = thing->snext)
     R_ProjectSprite (thing);
 }
References extralight, sector_t::lightlevel, LIGHTLEVELS, LIGHTSEGSHIFT, R_ProjectSprite(), scalelight, mobj_s::snext, spritelights, sector_t::thinglist, sector_t::validcount, and validcount.
Referenced by R_Subsector().
R_ClearSprites()
void R_ClearSprites (void)
Definition at line 309 of file r_things.c.
 {
     vissprite_p = vissprites;
 }
References vissprite_p, and vissprites.
Referenced by R_RenderPlayerView().
R_DrawMasked()
void R_DrawMasked (void)
Definition at line 951 of file r_things.c.
 {
     vissprite_t*    spr;
     drawseg_t*      ds;
     R_SortVisSprites ();
     if (vissprite_p > vissprites)
     {
     // draw all vissprites back to front
     for (spr = vsprsortedhead.next ;
          spr != &vsprsortedhead ;
          spr=spr->next)
     {
         R_DrawSprite (spr);
     }
     }
     // render any remaining masked mid textures
     for (ds=ds_p-1 ; ds >= drawsegs ; ds--)
     if (ds->maskedtexturecol)
         R_RenderMaskedSegRange (ds, ds->x1, ds->x2);
     // draw the psprites on top of everything
     //  but does not draw on side views
     if (!viewangleoffset)
     R_DrawPlayerSprites ();
 }
References drawsegs, ds_p, drawseg_s::maskedtexturecol, vissprite_s::next, R_DrawPlayerSprites(), R_DrawSprite(), R_RenderMaskedSegRange(), R_SortVisSprites(), viewangleoffset, vissprite_p, vissprites, vsprsortedhead, drawseg_s::x1, and drawseg_s::x2.
Referenced by R_RenderPlayerView().
R_DrawMaskedColumn()
void R_DrawMaskedColumn (column_t * column)
Definition at line 343 of file r_things.c.
 {
     int     topscreen;
     int     bottomscreen;
     fixed_t basetexturemid;
     basetexturemid = dc_texturemid;
     for ( ; column->topdelta != 0xff ; )
     {
     // calculate unclipped screen coordinates
     //  for post
     topscreen = sprtopscreen + spryscale*column->topdelta;
     bottomscreen = topscreen + spryscale*column->length;
     dc_yl = (topscreen+FRACUNIT-1)>>FRACBITS;
     dc_yh = (bottomscreen-1)>>FRACBITS;
     if (dc_yh >= mfloorclip[dc_x])
         dc_yh = mfloorclip[dc_x]-1;
     if (dc_yl <= mceilingclip[dc_x])
         dc_yl = mceilingclip[dc_x]+1;
     if (dc_yl <= dc_yh)
     {
         dc_source = (byte *)column + 3;
         dc_texturemid = basetexturemid - (column->topdelta<<FRACBITS);
         // dc_source = (byte *)column + 3 - column->topdelta;
         // Drawn by either R_DrawColumn
         //  or (SHADOW) R_DrawFuzzColumn.
         colfunc ();
     }
     column = (column_t *)(  (byte *)column + column->length + 4);
     }
     dc_texturemid = basetexturemid;
 }
References colfunc, dc_source, dc_texturemid, dc_x, dc_yh, dc_yl, FRACBITS, FRACUNIT, mceilingclip, mfloorclip, sprtopscreen, and spryscale.
Referenced by R_DrawVisSprite(), and R_RenderMaskedSegRange().
R_DrawPlayerSprites()
void R_DrawPlayerSprites (void)
Definition at line 738 of file r_things.c.
 {
     int     i;
     int     lightnum;
     pspdef_t*   psp;
     // get light level
     lightnum =
     (viewplayer->mo->subsector->sector->lightlevel >> LIGHTSEGSHIFT)
     +extralight;
     if (lightnum < 0)
     spritelights = scalelight[0];
     else if (lightnum >= LIGHTLEVELS)
     spritelights = scalelight[LIGHTLEVELS-1];
     else
     spritelights = scalelight[lightnum];
     // clip to screen bounds
     mfloorclip = screenheightarray;
     mceilingclip = negonearray;
     // add all active psprites
     for (i=0, psp=viewplayer->psprites;
      i<NUMPSPRITES;
      i++,psp++)
     {
     if (psp->state)
         R_DrawPSprite (psp);
     }
 }
References extralight, i, sector_t::lightlevel, LIGHTLEVELS, LIGHTSEGSHIFT, mceilingclip, mfloorclip, player_s::mo, negonearray, NUMPSPRITES, player_s::psprites, R_DrawPSprite(), scalelight, screenheightarray, subsector_s::sector, spritelights, pspdef_t::state, mobj_s::subsector, and viewplayer.
Referenced by R_DrawMasked().
R_DrawPSprite()
void R_DrawPSprite (pspdef_t * psp)
Definition at line 638 of file r_things.c.
 {
     fixed_t     tx;
     int         x1;
     int         x2;
     spritedef_t*    sprdef;
     spriteframe_t*  sprframe;
     int         lump;
     boolean     flip;
     vissprite_t*    vis;
     vissprite_t     avis;
     // decide which patch to use
 #ifdef RANGECHECK
     if ( (unsigned)psp->state->sprite >= (unsigned int) numsprites)
     I_Error ("R_ProjectSprite: invalid sprite number %i ",
          psp->state->sprite);
 #endif
     sprdef = &sprites[psp->state->sprite];
 #ifdef RANGECHECK
     if ( (psp->state->frame & FF_FRAMEMASK)  >= sprdef->numframes)
     I_Error ("R_ProjectSprite: invalid sprite frame %i : %i ",
          psp->state->sprite, psp->state->frame);
 #endif
     sprframe = &sprdef->spriteframes[ psp->state->frame & FF_FRAMEMASK ];
     lump = sprframe->lump[0];
     flip = (boolean)sprframe->flip[0];
     // calculate edges of the shape
     tx = psp->sx-160*FRACUNIT;
     tx -= spriteoffset[lump];
     x1 = (centerxfrac + FixedMul (tx,pspritescale) ) >>FRACBITS;
     // off the right side
     if (x1 > viewwidth)
     return;
     tx +=  spritewidth[lump];
     x2 = ((centerxfrac + FixedMul (tx, pspritescale) ) >>FRACBITS) - 1;
     // off the left side
     if (x2 < 0)
     return;
     // store information in a vissprite
     vis = &avis;
     vis->mobjflags = 0;
     vis->texturemid = (BASEYCENTER<<FRACBITS)+FRACUNIT/2-(psp->sy-spritetopoffset[lump]);
     vis->x1 = x1 < 0 ? 0 : x1;
     vis->x2 = x2 >= viewwidth ? viewwidth-1 : x2;
     vis->scale = pspritescale<<detailshift;
     if (flip)
     {
     vis->xiscale = -pspriteiscale;
     vis->startfrac = spritewidth[lump]-1;
     }
     else
     {
     vis->xiscale = pspriteiscale;
     vis->startfrac = 0;
     }
     if (vis->x1 > x1)
     vis->startfrac += vis->xiscale*(vis->x1-x1);
     vis->patch = lump;
     if (viewplayer->powers[pw_invisibility] > 4*32
     || viewplayer->powers[pw_invisibility] & 8)
     {
     // shadow draw
     vis->colormap = NULL;
     }
     else if (fixedcolormap)
     {
     // fixed color
     vis->colormap = fixedcolormap;
     }
     else if (psp->state->frame & FF_FULLBRIGHT)
     {
     // full bright
     vis->colormap = colormaps;
     }
     else
     {
     // local light
     vis->colormap = spritelights[MAXLIGHTSCALE-1];
     }
     R_DrawVisSprite (vis, vis->x1, vis->x2);
 }
References BASEYCENTER, centerxfrac, vissprite_s::colormap, colormaps, detailshift, FF_FRAMEMASK, FF_FULLBRIGHT, fixedcolormap, FixedMul(), spriteframe_t::flip, FRACBITS, FRACUNIT, state_t::frame, I_Error(), spriteframe_t::lump, MAXLIGHTSCALE, vissprite_s::mobjflags, NULL, spritedef_t::numframes, numsprites, vissprite_s::patch, player_s::powers, pspriteiscale, pspritescale, pw_invisibility, R_DrawVisSprite(), vissprite_s::scale, state_t::sprite, spritedef_t::spriteframes, spritelights, spriteoffset, sprites, spritetopoffset, spritewidth, vissprite_s::startfrac, pspdef_t::state, pspdef_t::sx, pspdef_t::sy, vissprite_s::texturemid, viewplayer, viewwidth, vissprite_s::x1, vissprite_s::x2, and vissprite_s::xiscale.
Referenced by R_DrawPlayerSprites().
R_DrawSprite()
void R_DrawSprite (vissprite_t * spr)
Definition at line 837 of file r_things.c.
 {
     drawseg_t*      ds;
     int         x;
     int         r1;
     int         r2;
     fixed_t     scale;
     fixed_t     lowscale;
     int         silhouette;
     for (x = spr->x1 ; x<=spr->x2 ; x++)
     clipbot[x] = cliptop[x] = -2;
     // Scan drawsegs from end to start for obscuring segs.
     // The first drawseg that has a greater scale
     //  is the clip seg.
     for (ds=ds_p-1 ; ds >= drawsegs ; ds--)
     {
     // determine if the drawseg obscures the sprite
     if (ds->x1 > spr->x2
         || ds->x2 < spr->x1
         || (!ds->silhouette
         && !ds->maskedtexturecol) )
     {
         // does not cover sprite
         continue;
     }
     r1 = ds->x1 < spr->x1 ? spr->x1 : ds->x1;
     r2 = ds->x2 > spr->x2 ? spr->x2 : ds->x2;
     if (ds->scale1 > ds->scale2)
     {
         lowscale = ds->scale2;
         scale = ds->scale1;
     }
     else
     {
         lowscale = ds->scale1;
         scale = ds->scale2;
     }
     if (scale < spr->scale
         || ( lowscale < spr->scale
          && !R_PointOnSegSide (spr->gx, spr->gy, ds->curline) ) )
     {
         // masked mid texture?
         if (ds->maskedtexturecol)
         R_RenderMaskedSegRange (ds, r1, r2);
         // seg is behind sprite
         continue;
     }
     // clip this piece of the sprite
     silhouette = ds->silhouette;
     if (spr->gz >= ds->bsilheight)
         silhouette &= ~SIL_BOTTOM;
     if (spr->gzt <= ds->tsilheight)
         silhouette &= ~SIL_TOP;
     if (silhouette == 1)
     {
         // bottom sil
         for (x=r1 ; x<=r2 ; x++)
         if (clipbot[x] == -2)
             clipbot[x] = ds->sprbottomclip[x];
     }
     else if (silhouette == 2)
     {
         // top sil
         for (x=r1 ; x<=r2 ; x++)
         if (cliptop[x] == -2)
             cliptop[x] = ds->sprtopclip[x];
     }
     else if (silhouette == 3)
     {
         // both
         for (x=r1 ; x<=r2 ; x++)
         {
         if (clipbot[x] == -2)
             clipbot[x] = ds->sprbottomclip[x];
         if (cliptop[x] == -2)
             cliptop[x] = ds->sprtopclip[x];
         }
     }
     }
     // all clipping has been performed, so draw the sprite
     // check for unclipped columns
     for (x = spr->x1 ; x<=spr->x2 ; x++)
     {
     if (clipbot[x] == -2)
         clipbot[x] = viewheight;
     if (cliptop[x] == -2)
         cliptop[x] = -1;
     }
     mfloorclip = clipbot;
     mceilingclip = cliptop;
     R_DrawVisSprite (spr, spr->x1, spr->x2);
 }
References drawseg_s::bsilheight, clipbot, cliptop, drawseg_s::curline, drawsegs, ds_p, vissprite_s::gx, vissprite_s::gy, vissprite_s::gz, vissprite_s::gzt, drawseg_s::maskedtexturecol, mceilingclip, mfloorclip, r1, r2, R_DrawVisSprite(), R_PointOnSegSide(), R_RenderMaskedSegRange(), scale, drawseg_s::scale1, drawseg_s::scale2, SIL_BOTTOM, SIL_TOP, drawseg_s::silhouette, drawseg_s::sprbottomclip, drawseg_s::sprtopclip, drawseg_s::tsilheight, viewheight, x, drawseg_s::x1, vissprite_s::x1, drawseg_s::x2, and vissprite_s::x2.
Referenced by R_DrawMasked().
R_DrawVisSprite()
void R_DrawVisSprite (vissprite_t * vis, int x1, int x2)
Definition at line 389 of file r_things.c.
 {
     column_t*       column;
     int         texturecolumn;
     fixed_t     frac;
     patch_t*        patch;
     patch = W_CacheLumpNum (vis->patch+firstspritelump, PU_CACHE);
     dc_colormap = vis->colormap;
     if (!dc_colormap)
     {
     // NULL colormap = shadow draw
     colfunc = fuzzcolfunc;
     }
     else if (vis->mobjflags & MF_TRANSLATION)
     {
     colfunc = transcolfunc;
     dc_translation = translationtables - 256 +
         ( (vis->mobjflags & MF_TRANSLATION) >> (MF_TRANSSHIFT-8) );
     }
     dc_iscale = abs(vis->xiscale)>>detailshift;
     dc_texturemid = vis->texturemid;
     frac = vis->startfrac;
     spryscale = vis->scale;
     sprtopscreen = centeryfrac - FixedMul(dc_texturemid,spryscale);
     for (dc_x=vis->x1 ; dc_x<=vis->x2 ; dc_x++, frac += vis->xiscale)
     {
     texturecolumn = frac>>FRACBITS;
 #ifdef RANGECHECK
     if (texturecolumn < 0 || texturecolumn >= SHORT(patch->width))
         I_Error ("R_DrawSpriteRange: bad texturecolumn");
 #endif
     column = (column_t *) ((byte *)patch +
                    LONG(patch->columnofs[texturecolumn]));
     R_DrawMaskedColumn (column);
     }
     colfunc = basecolfunc;
 }
References abs, basecolfunc, centeryfrac, colfunc, vissprite_s::colormap, dc_colormap, dc_iscale, dc_texturemid, dc_translation, dc_x, detailshift, firstspritelump, FixedMul(), FRACBITS, fuzzcolfunc, I_Error(), LONG, MF_TRANSLATION, MF_TRANSSHIFT, vissprite_s::mobjflags, vissprite_s::patch, PU_CACHE, R_DrawMaskedColumn(), vissprite_s::scale, SHORT, sprtopscreen, spryscale, vissprite_s::startfrac, vissprite_s::texturemid, transcolfunc, translationtables, W_CacheLumpNum(), vissprite_s::x1, and vissprite_s::xiscale.
Referenced by R_DrawPSprite(), and R_DrawSprite().
R_InitSpriteDefs()
void R_InitSpriteDefs (char ** namelist)
Definition at line 171 of file r_things.c.
 {
     char**  check;
     int     i;
     int     l;
     int     frame;
     int     rotation;
     int     start;
     int     end;
     int     patched;
     // count the number of sprite names
     check = namelist;
     while (*check != NULL)
     check++;
     numsprites = check-namelist;
     if (!numsprites)
     return;
     sprites = Z_Malloc(numsprites *sizeof(*sprites), PU_STATIC, NULL);
     start = firstspritelump-1;
     end = lastspritelump+1;
     // scan all the lump names for each of the names,
     //  noting the highest frame letter.
     // Just compare 4 characters as ints
     for (i=0 ; i<numsprites ; i++)
     {
     spritename = DEH_String(namelist[i]);
     memset (sprtemp,-1, sizeof(sprtemp));
     maxframe = -1;
     // scan the lumps,
     //  filling in the frames for whatever is found
     for (l=start+1 ; l<end ; l++)
     {
         if (!strncasecmp(lumpinfo[l].name, spritename, 4))
         {
         frame = lumpinfo[l].name[4] - 'A';
         rotation = lumpinfo[l].name[5] - '0';
         if (modifiedgame)
             patched = W_GetNumForName (lumpinfo[l].name);
         else
             patched = l;
         R_InstallSpriteLump (patched, frame, rotation, false);
         if (lumpinfo[l].name[6])
         {
             frame = lumpinfo[l].name[6] - 'A';
             rotation = lumpinfo[l].name[7] - '0';
             R_InstallSpriteLump (l, frame, rotation, true);
         }
         }
     }
     // check the frames that were found for completeness
     if (maxframe == -1)
     {
         sprites[i].numframes = 0;
         continue;
     }
     maxframe++;
     for (frame = 0 ; frame < maxframe ; frame++)
     {
         switch ((int)sprtemp[frame].rotate)
         {
           case -1:
         // no rotations were found for that frame at all
         I_Error ("R_InitSprites: No patches found "
              "for %s frame %c", spritename, frame+'A');
         break;
           case 0:
         // only the first rotation is needed
         break;
           case 1:
         // must have all 8 frames
         for (rotation=0 ; rotation<8 ; rotation++)
             if (sprtemp[frame].lump[rotation] == -1)
             I_Error ("R_InitSprites: Sprite %s frame %c "
                  "is missing rotations",
                  spritename, frame+'A');
         break;
         }
     }
     // allocate space for the frames present and copy sprtemp to it
     sprites[i].numframes = maxframe;
     sprites[i].spriteframes =
         Z_Malloc (maxframe * sizeof(spriteframe_t), PU_STATIC, NULL);
     memcpy (sprites[i].spriteframes, sprtemp, maxframe*sizeof(spriteframe_t));
     }
 }
References check(), DEH_String, end, firstspritelump, i, I_Error(), l, lastspritelump, lumpinfo, maxframe, memcpy, memset, modifiedgame, lumpinfo_s::name, NULL, spritedef_t::numframes, numsprites, PU_STATIC, R_InstallSpriteLump(), rotate(), spritedef_t::spriteframes, spritename, sprites, sprtemp, start, strncasecmp, W_GetNumForName(), and Z_Malloc().
Referenced by R_InitSprites().
R_InitSprites()
void R_InitSprites (char ** namelist)
Definition at line 291 of file r_things.c.
 {
     int     i;
     for (i=0 ; i<SCREENWIDTH ; i++)
     {
     negonearray[i] = -1;
     }
     R_InitSpriteDefs (namelist);
 }
References i, negonearray, R_InitSpriteDefs(), and SCREENWIDTH.
Referenced by P_Init().
R_InstallSpriteLump()
void R_InstallSpriteLump (int lump, unsigned frame, unsigned rotation, boolean flipped)
Definition at line 100 of file r_things.c.
 {
     int     r;
     if (frame >= 29 || rotation > 8)
     I_Error("R_InstallSpriteLump: "
         "Bad frame characters in lump %i", lump);
     if ((int)frame > maxframe)
     maxframe = frame;
     if (rotation == 0)
     {
     // the lump should be used for all rotations
     if (sprtemp[frame].rotate == false)
         I_Error ("R_InitSprites: Sprite %s frame %c has "
              "multip rot=0 lump", spritename, 'A'+frame);
     if (sprtemp[frame].rotate == true)
         I_Error ("R_InitSprites: Sprite %s frame %c has rotations "
              "and a rot=0 lump", spritename, 'A'+frame);
     sprtemp[frame].rotate = false;
     for (r=0 ; r<8 ; r++)
     {
         sprtemp[frame].lump[r] = lump - firstspritelump;
         sprtemp[frame].flip[r] = (byte)flipped;
     }
     return;
     }
     // the lump is only used for one rotation
     if (sprtemp[frame].rotate == false)
     I_Error ("R_InitSprites: Sprite %s frame %c has rotations "
          "and a rot=0 lump", spritename, 'A'+frame);
     sprtemp[frame].rotate = true;
     // make 0 based
     rotation--;
     if (sprtemp[frame].lump[rotation] != -1)
     I_Error ("R_InitSprites: Sprite %s : %c : %c "
          "has two lumps mapped to it",
          spritename, 'A'+frame, '1'+rotation);
     sprtemp[frame].lump[rotation] = lump - firstspritelump;
     sprtemp[frame].flip[rotation] = (byte)flipped;
 }
References firstspritelump, spriteframe_t::flip, I_Error(), spriteframe_t::lump, maxframe, rotate(), spriteframe_t::rotate, spritename, and sprtemp.
Referenced by R_InitSpriteDefs().
R_NewVisSprite()
vissprite_t* R_NewVisSprite (void)
Definition at line 320 of file r_things.c.
 {
     if (vissprite_p == &vissprites[MAXVISSPRITES])
     return &overflowsprite;
     vissprite_p++;
     return vissprite_p-1;
 }
References MAXVISSPRITES, overflowsprite, vissprite_p, and vissprites.
Referenced by R_ProjectSprite().
R_ProjectSprite()
void R_ProjectSprite (mobj_t * thing)
Definition at line 444 of file r_things.c.
 {
     fixed_t     tr_x;
     fixed_t     tr_y;
     fixed_t     gxt;
     fixed_t     gyt;
     fixed_t     tx;
     fixed_t     tz;
     fixed_t     xscale;
     int         x1;
     int         x2;
     spritedef_t*    sprdef;
     spriteframe_t*  sprframe;
     int         lump;
     unsigned        rot;
     boolean     flip;
     int         index;
     vissprite_t*    vis;
     angle_t     ang;
     fixed_t     iscale;
     // transform the origin point
     tr_x = thing->x - viewx;
     tr_y = thing->y - viewy;
     gxt = FixedMul(tr_x,viewcos);
     gyt = -FixedMul(tr_y,viewsin);
     tz = gxt-gyt;
     // thing is behind view plane?
     if (tz < MINZ)
     return;
     xscale = FixedDiv(projection, tz);
     gxt = -FixedMul(tr_x,viewsin);
     gyt = FixedMul(tr_y,viewcos);
     tx = -(gyt+gxt);
     // too far off the side?
     if (abs(tx)>(tz<<2))
     return;
     // decide which patch to use for sprite relative to player
 #ifdef RANGECHECK
     if ((unsigned int) thing->sprite >= (unsigned int) numsprites)
     I_Error ("R_ProjectSprite: invalid sprite number %i ",
          thing->sprite);
 #endif
     sprdef = &sprites[thing->sprite];
 #ifdef RANGECHECK
     if ( (thing->frame&FF_FRAMEMASK) >= sprdef->numframes )
     I_Error ("R_ProjectSprite: invalid sprite frame %i : %i ",
          thing->sprite, thing->frame);
 #endif
     sprframe = &sprdef->spriteframes[ thing->frame & FF_FRAMEMASK];
     if (sprframe->rotate)
     {
     // choose a different rotation based on player view
     ang = R_PointToAngle (thing->x, thing->y);
     rot = (ang-thing->angle+(unsigned)(ANG45/2)*9)>>29;
     lump = sprframe->lump[rot];
     flip = (boolean)sprframe->flip[rot];
     }
     else
     {
     // use single rotation for all views
     lump = sprframe->lump[0];
     flip = (boolean)sprframe->flip[0];
     }
     // calculate edges of the shape
     tx -= spriteoffset[lump];
     x1 = (centerxfrac + FixedMul (tx,xscale) ) >>FRACBITS;
     // off the right side?
     if (x1 > viewwidth)
     return;
     tx +=  spritewidth[lump];
     x2 = ((centerxfrac + FixedMul (tx,xscale) ) >>FRACBITS) - 1;
     // off the left side
     if (x2 < 0)
     return;
     // store information in a vissprite
     vis = R_NewVisSprite ();
     vis->mobjflags = thing->flags;
     vis->scale = xscale<<detailshift;
     vis->gx = thing->x;
     vis->gy = thing->y;
     vis->gz = thing->z;
     vis->gzt = thing->z + spritetopoffset[lump];
     vis->texturemid = vis->gzt - viewz;
     vis->x1 = x1 < 0 ? 0 : x1;
     vis->x2 = x2 >= viewwidth ? viewwidth-1 : x2;
     iscale = FixedDiv (FRACUNIT, xscale);
     if (flip)
     {
     vis->startfrac = spritewidth[lump]-1;
     vis->xiscale = -iscale;
     }
     else
     {
     vis->startfrac = 0;
     vis->xiscale = iscale;
     }
     if (vis->x1 > x1)
     vis->startfrac += vis->xiscale*(vis->x1-x1);
     vis->patch = lump;
     // get light level
     if (thing->flags & MF_SHADOW)
     {
     // shadow draw
     vis->colormap = NULL;
     }
     else if (fixedcolormap)
     {
     // fixed map
     vis->colormap = fixedcolormap;
     }
     else if (thing->frame & FF_FULLBRIGHT)
     {
     // full bright
     vis->colormap = colormaps;
     }
     else
     {
     // diminished light
     index = xscale>>(LIGHTSCALESHIFT-detailshift);
     if (index >= MAXLIGHTSCALE)
         index = MAXLIGHTSCALE-1;
     vis->colormap = spritelights[index];
     }
 }
References abs, ANG45, mobj_s::angle, centerxfrac, vissprite_s::colormap, colormaps, detailshift, FF_FRAMEMASK, FF_FULLBRIGHT, fixedcolormap, FixedDiv(), FixedMul(), mobj_s::flags, spriteframe_t::flip, FRACBITS, FRACUNIT, mobj_s::frame, vissprite_s::gx, vissprite_s::gy, vissprite_s::gz, vissprite_s::gzt, I_Error(), index(), LIGHTSCALESHIFT, spriteframe_t::lump, MAXLIGHTSCALE, MF_SHADOW, MINZ, vissprite_s::mobjflags, NULL, spritedef_t::numframes, numsprites, vissprite_s::patch, projection, R_NewVisSprite(), R_PointToAngle(), rot(), spriteframe_t::rotate, vissprite_s::scale, mobj_s::sprite, spritedef_t::spriteframes, spritelights, spriteoffset, sprites, spritetopoffset, spritewidth, vissprite_s::startfrac, vissprite_s::texturemid, viewcos, viewsin, viewwidth, viewx, viewy, viewz, mobj_s::x, vissprite_s::x1, vissprite_s::x2, vissprite_s::xiscale, mobj_s::y, and mobj_s::z.
Referenced by R_AddSprites().
R_SortVisSprites()
void R_SortVisSprites (void)
Definition at line 779 of file r_things.c.
 {
     int         i;
     int         count;
     vissprite_t*    ds;
     vissprite_t*    best;
     vissprite_t     unsorted;
     fixed_t     bestscale;
     count = vissprite_p - vissprites;
     unsorted.next = unsorted.prev = &unsorted;
     if (!count)
     return;
     for (ds=vissprites ; ds<vissprite_p ; ds++)
     {
     ds->next = ds+1;
     ds->prev = ds-1;
     }
     vissprites[0].prev = &unsorted;
     unsorted.next = &vissprites[0];
     (vissprite_p-1)->next = &unsorted;
     unsorted.prev = vissprite_p-1;
     // pull the vissprites out by scale
     vsprsortedhead.next = vsprsortedhead.prev = &vsprsortedhead;
     for (i=0 ; i<count ; i++)
     {
     bestscale = __INT_MAX__;
         best = unsorted.next;
     for (ds=unsorted.next ; ds!= &unsorted ; ds=ds->next)
     {
         if (ds->scale < bestscale)
         {
         bestscale = ds->scale;
         best = ds;
         }
     }
     best->next->prev = best->prev;
     best->prev->next = best->next;
     best->next = &vsprsortedhead;
     best->prev = vsprsortedhead.prev;
     vsprsortedhead.prev->next = best;
     vsprsortedhead.prev = best;
     }
 }
References count, i, next, vissprite_s::next, vissprite_s::prev, vissprite_s::scale, vissprite_p, vissprites, and vsprsortedhead.
Referenced by R_DrawMasked().
Variable Documentation
clipbot
short clipbot[SCREENWIDTH] static
Definition at line 835 of file r_things.c.
Referenced by R_DrawSprite().
cliptop
short cliptop[SCREENWIDTH] static
Definition at line 836 of file r_things.c.
Referenced by R_DrawSprite().
maxframe
int maxframe
Definition at line 89 of file r_things.c.
Referenced by R_InitSpriteDefs(), and R_InstallSpriteLump().
mceilingclip
short* mceilingclip
Definition at line 338 of file r_things.c.
Referenced by R_DrawMaskedColumn(), R_DrawPlayerSprites(), R_DrawSprite(), and R_RenderMaskedSegRange().
mfloorclip
short* mfloorclip
Definition at line 337 of file r_things.c.
Referenced by R_DrawMaskedColumn(), R_DrawPlayerSprites(), R_DrawSprite(), and R_RenderMaskedSegRange().
negonearray
short negonearray[SCREENWIDTH]
Definition at line 75 of file r_things.c.
Referenced by R_DrawPlayerSprites(), R_InitSprites(), and R_StoreWallRange().
newvissprite
int newvissprite
Definition at line 283 of file r_things.c.
numsprites
int numsprites
Definition at line 86 of file r_things.c.
Referenced by R_DrawPSprite(), R_InitSpriteDefs(), R_PrecacheLevel(), and R_ProjectSprite().
overflowsprite
vissprite_t overflowsprite
Definition at line 318 of file r_things.c.
Referenced by R_NewVisSprite().
pspriteiscale
fixed_t pspriteiscale
Definition at line 69 of file r_things.c.
Referenced by R_DrawPlanes(), R_DrawPSprite(), and R_ExecuteSetViewSize().
pspritescale
fixed_t pspritescale
Definition at line 68 of file r_things.c.
Referenced by R_DrawPSprite(), and R_ExecuteSetViewSize().
screenheightarray
short screenheightarray[SCREENWIDTH]
Definition at line 76 of file r_things.c.
Referenced by R_DrawPlayerSprites(), R_ExecuteSetViewSize(), and R_StoreWallRange().
spritelights
lighttable_t** spritelights
Definition at line 71 of file r_things.c.
Referenced by R_AddSprites(), R_DrawPlayerSprites(), R_DrawPSprite(), and R_ProjectSprite().
spritename
char* spritename
Definition at line 90 of file r_things.c.
Referenced by R_InitSpriteDefs(), and R_InstallSpriteLump().
sprites
spritedef_t* sprites
Definition at line 85 of file r_things.c.
Referenced by F_CastDrawer(), R_DrawPSprite(), R_InitSpriteDefs(), R_PrecacheLevel(), and R_ProjectSprite().
sprtemp
spriteframe_t sprtemp[29]
Definition at line 88 of file r_things.c.
Referenced by R_InitSpriteDefs(), and R_InstallSpriteLump().
sprtopscreen
fixed_t sprtopscreen
Definition at line 341 of file r_things.c.
Referenced by R_DrawMaskedColumn(), R_DrawVisSprite(), and R_RenderMaskedSegRange().
spryscale
fixed_t spryscale
Definition at line 340 of file r_things.c.
Referenced by R_DrawMaskedColumn(), R_DrawVisSprite(), and R_RenderMaskedSegRange().
vissprite_p
vissprite_t* vissprite_p
Definition at line 282 of file r_things.c.
Referenced by R_ClearSprites(), R_DrawMasked(), R_NewVisSprite(), and R_SortVisSprites().
vissprites
vissprite_t vissprites[MAXVISSPRITES]
Definition at line 281 of file r_things.c.
Referenced by R_ClearSprites(), R_DrawMasked(), R_NewVisSprite(), and R_SortVisSprites().
vsprsortedhead
vissprite_t vsprsortedhead
Definition at line 776 of file r_things.c.
Referenced by R_DrawMasked(), and R_SortVisSprites().