Fennix Userspace: Userspace/musl/include/sys/inotify.h File Reference
inotify.h File Reference
#include <stdint.h>
#include <fcntl.h>
Data Structures
struct inotify_event
Macros
#define IN_CLOEXEC O_CLOEXEC
#define IN_NONBLOCK O_NONBLOCK
#define IN_ACCESS 0x00000001
#define IN_MODIFY 0x00000002
#define IN_ATTRIB 0x00000004
#define IN_CLOSE_WRITE 0x00000008
#define IN_CLOSE_NOWRITE 0x00000010
#define IN_CLOSE (IN_CLOSE_WRITE | IN_CLOSE_NOWRITE)
#define IN_OPEN 0x00000020
#define IN_MOVED_FROM 0x00000040
#define IN_MOVED_TO 0x00000080
#define IN_MOVE (IN_MOVED_FROM | IN_MOVED_TO)
#define IN_CREATE 0x00000100
#define IN_DELETE 0x00000200
#define IN_DELETE_SELF 0x00000400
#define IN_MOVE_SELF 0x00000800
#define IN_ALL_EVENTS 0x00000fff
#define IN_UNMOUNT 0x00002000
#define IN_Q_OVERFLOW 0x00004000
#define IN_IGNORED 0x00008000
#define IN_ONLYDIR 0x01000000
#define IN_DONT_FOLLOW 0x02000000
#define IN_EXCL_UNLINK 0x04000000
#define IN_MASK_CREATE 0x10000000
#define IN_MASK_ADD 0x20000000
#define IN_ISDIR 0x40000000
#define IN_ONESHOT 0x80000000
Functions
int inotify_init (void)
int inotify_init1 (int)
int inotify_add_watch (int, const char *, uint32_t)
int inotify_rm_watch (int, int)
Data Structure Documentation
inotify_event
struct inotify_event
Definition at line 11 of file inotify.h.
Data Fields
uint32_t cookie
uint32_t len
uint32_t mask
char name[]
int wd
Macro Definition Documentation
IN_ACCESS
#define IN_ACCESS 0x00000001
Definition at line 20 of file inotify.h.
IN_ALL_EVENTS
#define IN_ALL_EVENTS 0x00000fff
Definition at line 34 of file inotify.h.
IN_ATTRIB
#define IN_ATTRIB 0x00000004
Definition at line 22 of file inotify.h.
IN_CLOEXEC
#define IN_CLOEXEC O_CLOEXEC
Definition at line 17 of file inotify.h.
IN_CLOSE
#define IN_CLOSE (IN_CLOSE_WRITE | IN_CLOSE_NOWRITE)
Definition at line 25 of file inotify.h.
IN_CLOSE_NOWRITE
#define IN_CLOSE_NOWRITE 0x00000010
Definition at line 24 of file inotify.h.
IN_CLOSE_WRITE
#define IN_CLOSE_WRITE 0x00000008
Definition at line 23 of file inotify.h.
IN_CREATE
#define IN_CREATE 0x00000100
Definition at line 30 of file inotify.h.
IN_DELETE
#define IN_DELETE 0x00000200
Definition at line 31 of file inotify.h.
IN_DELETE_SELF
#define IN_DELETE_SELF 0x00000400
Definition at line 32 of file inotify.h.
IN_DONT_FOLLOW
#define IN_DONT_FOLLOW 0x02000000
Definition at line 41 of file inotify.h.
IN_EXCL_UNLINK
#define IN_EXCL_UNLINK 0x04000000
Definition at line 42 of file inotify.h.
IN_IGNORED
#define IN_IGNORED 0x00008000
Definition at line 38 of file inotify.h.
IN_ISDIR
#define IN_ISDIR 0x40000000
Definition at line 46 of file inotify.h.
IN_MASK_ADD
#define IN_MASK_ADD 0x20000000
Definition at line 44 of file inotify.h.
IN_MASK_CREATE
#define IN_MASK_CREATE 0x10000000
Definition at line 43 of file inotify.h.
IN_MODIFY
#define IN_MODIFY 0x00000002
Definition at line 21 of file inotify.h.
IN_MOVE
#define IN_MOVE (IN_MOVED_FROM | IN_MOVED_TO)
Definition at line 29 of file inotify.h.
IN_MOVE_SELF
#define IN_MOVE_SELF 0x00000800
Definition at line 33 of file inotify.h.
IN_MOVED_FROM
#define IN_MOVED_FROM 0x00000040
Definition at line 27 of file inotify.h.
IN_MOVED_TO
#define IN_MOVED_TO 0x00000080
Definition at line 28 of file inotify.h.
IN_NONBLOCK
#define IN_NONBLOCK O_NONBLOCK
Definition at line 18 of file inotify.h.
IN_ONESHOT
#define IN_ONESHOT 0x80000000
Definition at line 47 of file inotify.h.
IN_ONLYDIR
#define IN_ONLYDIR 0x01000000
Definition at line 40 of file inotify.h.
IN_OPEN
#define IN_OPEN 0x00000020
Definition at line 26 of file inotify.h.
IN_Q_OVERFLOW
#define IN_Q_OVERFLOW 0x00004000
Definition at line 37 of file inotify.h.
IN_UNMOUNT
#define IN_UNMOUNT 0x00002000
Definition at line 36 of file inotify.h.
Function Documentation
inotify_add_watch()
int inotify_add_watch (int fd, const char * pathname, uint32_t mask)
Definition at line 18 of file inotify.c.
 {
     return syscall(SYS_inotify_add_watch, fd, pathname, mask);
 }
References syscall().
Referenced by test_watch_directory(), and test_watch_file().
inotify_init()
int inotify_init (void)
Definition at line 5 of file inotify.c.
 {
     return inotify_init1(0);
 }
References inotify_init1().
Referenced by test_watch_directory(), and test_watch_file().
inotify_init1()
int inotify_init1 (int flags)
Definition at line 9 of file inotify.c.
 {
     int r = __syscall(SYS_inotify_init1, flags);
 #ifdef SYS_inotify_init
     if (r==-ENOSYS && !flags) r = __syscall(SYS_inotify_init);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), and ENOSYS.
Referenced by inotify_init().
inotify_rm_watch()
int inotify_rm_watch (int fd, int wd)
Definition at line 23 of file inotify.c.
 {
     return syscall(SYS_inotify_rm_watch, fd, wd);
 }
References syscall().
Referenced by test_watch_directory(), and test_watch_file().