Fennix: Userspace/mlibc/options/linux/generic/pty-stubs.cpp File Reference
pty-stubs.cpp File Reference
#include <asm/ioctls.h>
#include <bits/ensure.h>
#include <errno.h>
#include <fcntl.h>
#include <pty.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <stdlib.h>
#include <mlibc/debug.hpp>
#include <mlibc/linux-sysdeps.hpp>
Functions
int openpty (int *mfd, int *sfd, char *name, const struct termios *ios, const struct winsize *win)
int login_tty (int fd)
int forkpty (int *mfd, char *name, const struct termios *ios, const struct winsize *win)
Function Documentation
forkpty()
int forkpty (int * mfd, char * name, const struct termios * ios, const struct winsize * win)
Definition at line 74 of file pty-stubs.cpp.
{
     int sfd;
     if(openpty(mfd, &sfd, name, ios, win))
         return -1;
     pid_t child;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fork, -1);
     if(int e = mlibc::sys_fork(&child); e) {
         errno = e;
         return -1;
     }
     if(!child) {
         if(login_tty(sfd))
             mlibc::panicLogger() << "mlibc: TTY login fail in forkpty() child" << frg::endlog;
     }else{
         if(int e = mlibc::sys_close(sfd); e) {
             errno = e;
             return -1;
         }
     }
     return child;
 }
References child, errno, login_tty(), MLIBC_CHECK_OR_ENOSYS, name, openpty(), mlibc::panicLogger, mlibc::sys_close(), and mlibc::sys_fork().
login_tty()
int login_tty (int fd)
Definition at line 47 of file pty-stubs.cpp.
                       {
     if(setsid() == -1)
         return -1;
     if(ioctl(fd, TIOCSCTTY, 0))
         return -1;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_dup2, -1);
     if(int e = mlibc::sys_dup2(fd, 0, STDIN_FILENO); e) {
         errno = e;
         return -1;
     }
     if(int e = mlibc::sys_dup2(fd, 0, STDOUT_FILENO); e) {
         errno = e;
         return -1;
     }
     if(int e = mlibc::sys_dup2(fd, 0, STDERR_FILENO); e) {
         errno = e;
         return -1;
     }
     if(int e = mlibc::sys_close(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, ioctl(), MLIBC_CHECK_OR_ENOSYS, setsid(), STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, mlibc::sys_close(), and mlibc::sys_dup2().
Referenced by forkpty().
openpty()
int openpty (int * mfd, int * sfd, char * name, const struct termios * ios, const struct winsize * win)
Definition at line 15 of file pty-stubs.cpp.
{
     __ensure(!ios);
     if (win) {
         mlibc::infoLogger() << "mlibc: openpty ignores win argument" << frg::endlog;
     }
     // FIXME: Close the master FD if the slave open fails.
     int ptmx_fd;
     if(int e = mlibc::sys_open("/dev/ptmx", O_RDWR | O_NOCTTY, 0, &ptmx_fd); e) {
         errno = e;
         return -1;
     }
     char spath[32];
     if(!name)
         name = spath;
     if(ptsname_r(ptmx_fd, name, 32))
         return -1;
     int pts_fd;
     if(int e = mlibc::sys_open(name, O_RDWR | O_NOCTTY, 0, &pts_fd); e) {
         errno = e;
         return -1;
     }
     *mfd = ptmx_fd;
     *sfd = pts_fd;
     return 0;
 }
References __ensure, errno, mlibc::infoLogger, name, O_NOCTTY, O_RDWR, ptsname_r(), and mlibc::sys_open().
Referenced by forkpty().