Fennix Userspace: Userspace/apps/base/busybox/loginutils/deluser.c File Reference
deluser.c File Reference
#include "libbb.h"
Functions
int deluser_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
deluser_main()
int deluser_main (int argc, char ** argv)
Definition at line 53 of file deluser.c.
 {
     /* User or group name */
     char *name;
     /* Username (non-NULL only in "delgroup USER GROUP" case) */
     char *member;
     /* Name of passwd or group file */
     const char *pfile;
     /* Name of shadow or gshadow file */
     const char *sfile;
     /* Are we deluser or delgroup? */
     int do_deluser = (ENABLE_DELUSER && (!ENABLE_DELGROUP || applet_name[3] == 'u'));
 #if !ENABLE_LONG_OPTS
     const int opt_delhome = 0;
 #else
     int opt_delhome = 0;
     if (do_deluser) {
         opt_delhome = getopt32long(argv, "",
                 "remove-home\0" No_argument "\xff");
         argv += opt_delhome;
         argc -= opt_delhome;
     }
 #endif
     if (geteuid() != 0)
         bb_simple_error_msg_and_die(bb_msg_perm_denied_are_you_root);
     name = argv[1];
     member = NULL;
     switch (argc) {
     case 3:
         if (!ENABLE_FEATURE_DEL_USER_FROM_GROUP || do_deluser)
             break;
         /* It's "delgroup USER GROUP" */
         member = name;
         name = argv[2];
         /* Fallthrough */
     case 2:
         if (do_deluser) {
             /* "deluser USER" */
             struct passwd *pw;
             pw = xgetpwnam(name); /* bail out if USER is wrong */
             pfile = bb_path_passwd_file;
             if (ENABLE_FEATURE_SHADOWPASSWDS)
                 sfile = bb_path_shadow_file;
             if (opt_delhome) {
                 struct stat st;
                 /* Make sure home is an actual directory before
                  * removing it (e.g. users with /dev/null as home) */
                 if (stat(pw->pw_dir, &st) == 0 && S_ISDIR(st.st_mode))
                     remove_file(pw->pw_dir, FILEUTILS_RECUR);
             }
         } else {
             struct group *gr;
  do_delgroup:
             /* "delgroup GROUP" or "delgroup USER GROUP" */
             if (do_deluser < 0) { /* delgroup after deluser? */
                 gr = getgrnam(name);
                 if (!gr)
                     return EXIT_SUCCESS;
             } else {
                 gr = xgetgrnam(name); /* bail out if GROUP is wrong */
             }
             if (!member) {
                 /* "delgroup GROUP" */
                 struct passwd *pw;
                 /* Check if the group is in use */
                 while ((pw = getpwent()) != NULL) {
                     if (pw->pw_gid == gr->gr_gid)
                         bb_error_msg_and_die("'%s' still has '%s' as their primary group!",
                             pw->pw_name, name);
                 }
                 //endpwent();
             }
             pfile = bb_path_group_file;
             if (ENABLE_FEATURE_SHADOWPASSWDS)
                 sfile = bb_path_gshadow_file;
         }
         /* Modify pfile, then sfile */
         do {
             if (update_passwd(pfile, name, NULL, member) == -1)
                 return EXIT_FAILURE;
             if (ENABLE_FEATURE_SHADOWPASSWDS) {
                 pfile = sfile;
                 sfile = NULL;
             }
         } while (ENABLE_FEATURE_SHADOWPASSWDS && pfile);
         if (do_deluser > 0) {
             /* Delete user from all groups */
             if (update_passwd(bb_path_group_file, NULL, NULL, name) == -1)
                 return EXIT_FAILURE;
             if (ENABLE_DELGROUP) {
                 /* "deluser USER" also should try to delete
                  * same-named group. IOW: do "delgroup USER"
                  */
 // On debian deluser is a perl script that calls userdel.
 // From man userdel:
 //  If USERGROUPS_ENAB is defined to yes in /etc/login.defs, userdel will
 //  delete the group with the same name as the user.
                 do_deluser = -1;
                 goto do_delgroup;
             }
         }
         return EXIT_SUCCESS;
     }
     /* Reached only if number of command line args is wrong */
     bb_show_usage();
 }
References applet_name, argc, argv, bb_error_msg_and_die(), bb_path_group_file, bb_path_gshadow_file, bb_path_passwd_file, bb_path_shadow_file, bb_show_usage(), bb_simple_error_msg_and_die(), EXIT_FAILURE, EXIT_SUCCESS, FILEUTILS_RECUR, geteuid, getgrnam, getopt32long, getpwent, gr, group::gr_gid, member, No_argument, NULL, pw, passwd::pw_dir, passwd::pw_gid, passwd::pw_name, remove_file(), S_ISDIR, stat(), update_passwd, xgetgrnam(), and xgetpwnam().