Fennix: Userspace/mlibc/options/posix/generic/sys-socket-stubs.cpp File Reference
sys-socket-stubs.cpp File Reference
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <sys/socket.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Functions
int accept (int fd, struct sockaddr *__restrict addr_ptr, socklen_t *__restrict addr_length)
int accept4 (int fd, struct sockaddr *__restrict addr_ptr, socklen_t *__restrict addr_length, int flags)
int bind (int fd, const struct sockaddr *addr_ptr, socklen_t addr_len)
int connect (int fd, const struct sockaddr *addr_ptr, socklen_t addr_len)
int getpeername (int fd, struct sockaddr *addr_ptr, socklen_t *__restrict addr_length)
int getsockname (int fd, struct sockaddr *__restrict addr_ptr, socklen_t *__restrict addr_length)
int getsockopt (int fd, int layer, int number, void *__restrict buffer, socklen_t *__restrict size)
int listen (int fd, int backlog)
ssize_t recv (int sockfd, void *__restrict buf, size_t len, int flags)
ssize_t recvfrom (int sockfd, void *__restrict buf, size_t len, int flags, struct sockaddr *__restrict src_addr, socklen_t *__restrict addrlen)
ssize_t recvmsg (int fd, struct msghdr *hdr, int flags)
int recvmmsg (int, struct mmsghdr *, unsigned int, int, struct timespec *)
ssize_t send (int fd, const void *buffer, size_t size, int flags)
ssize_t sendto (int fd, const void *buffer, size_t size, int flags, const struct sockaddr *sock_addr, socklen_t addr_length)
ssize_t sendmsg (int fd, const struct msghdr *hdr, int flags)
int sendmmsg (int, struct mmsghdr *, unsigned int, int)
int setsockopt (int fd, int layer, int number, const void *buffer, socklen_t size)
int shutdown (int, int)
int sockatmark (int)
int socket (int family, int type, int protocol)
int socketpair (int domain, int type, int protocol, int sv[2])
Function Documentation
accept()
int accept (int fd, struct sockaddr *__restrict addr_ptr, socklen_t *__restrict addr_length)
Definition at line 11 of file sys-socket-stubs.cpp.
{
     int newfd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_accept, -1);
     if(int e = mlibc::sys_accept(fd, &newfd, addr_ptr, addr_length); e) {
         errno = e;
         return -1;
     }
     return newfd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_accept().
accept4()
int accept4 (int fd, struct sockaddr *__restrict addr_ptr, socklen_t *__restrict addr_length, int flags)
Definition at line 21 of file sys-socket-stubs.cpp.
{
     int newfd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_accept, -1);
     if(int e = mlibc::sys_accept(fd, &newfd, addr_ptr, addr_length); e) {
         errno = e;
         return -1;
     }
     if(flags & SOCK_NONBLOCK) {
         fcntl(newfd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK);
     }
     if(flags & SOCK_CLOEXEC) {
         fcntl(newfd, F_SETFD, flags | FD_CLOEXEC);
     }
     return newfd;
 }
References errno, F_GETFL, F_SETFD, F_SETFL, fcntl(), fd, FD_CLOEXEC, flags, MLIBC_CHECK_OR_ENOSYS, O_NONBLOCK, SOCK_CLOEXEC, SOCK_NONBLOCK, and mlibc::sys_accept().
Referenced by run_test().
bind()
int bind (int fd, const struct sockaddr * addr_ptr, socklen_t addr_len)
Definition at line 40 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_bind, -1);
     if(int e = mlibc::sys_bind(fd, addr_ptr, addr_len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_bind().
Referenced by ELF32_ST_INFO(), ELF64_ST_INFO(), resolveInObject(), socket_setup(), and ObjectSymbol::virtualAddress().
connect()
int connect (int fd, const struct sockaddr * addr_ptr, socklen_t addr_len)
Definition at line 49 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_connect, -1);
     if(int e = mlibc::sys_connect(fd, addr_ptr, addr_len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_connect().
Referenced by __openlog(), _vsyslog(), and run_test().
getpeername()
int getpeername (int fd, struct sockaddr * addr_ptr, socklen_t *__restrict addr_length)
Definition at line 58 of file sys-socket-stubs.cpp.
{
     socklen_t actual_length;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_peername, -1);
     if(int e = mlibc::sys_peername(fd, addr_ptr, *addr_length, &actual_length); e) {
         errno = e;
         return -1;
     }
     *addr_length = actual_length;
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_peername().
getsockname()
int getsockname (int fd, struct sockaddr *__restrict addr_ptr, socklen_t *__restrict addr_length)
Definition at line 69 of file sys-socket-stubs.cpp.
{
     socklen_t actual_length;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sockname, -1);
     if(int e = mlibc::sys_sockname(fd, addr_ptr, *addr_length, &actual_length); e) {
         errno = e;
         return -1;
     }
     *addr_length = actual_length;
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_sockname().
getsockopt()
int getsockopt (int fd, int layer, int number, void *__restrict buffer, socklen_t *__restrict size)
Definition at line 80 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getsockopt, -1);
     return mlibc::sys_getsockopt(fd, layer, number, buffer, size);
 }
References fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_getsockopt().
listen()
int listen (int fd, int backlog)
Definition at line 86 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_listen, -1);
     if(int e = mlibc::sys_listen(fd, backlog); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_listen().
Referenced by socket_setup().
recv()
ssize_t recv (int sockfd, void *__restrict buf, size_t len, int flags)
Definition at line 95 of file sys-socket-stubs.cpp.
{
     return recvfrom(sockfd, buf, len, flags, NULL, NULL);
 }
References buf, flags, NULL, and recvfrom().
recvfrom()
ssize_t recvfrom (int sockfd, void *__restrict buf, size_t len, int flags, struct sockaddr *__restrict src_addr, socklen_t *__restrict addrlen)
Definition at line 99 of file sys-socket-stubs.cpp.
{
     struct iovec iov = {};
     iov.iov_base = buf;
     iov.iov_len = len;
     struct msghdr hdr = {};
     hdr.msg_name = src_addr;
     if (addrlen) {
         hdr.msg_namelen = *addrlen;
     }
     hdr.msg_iov = &iov;
     hdr.msg_iovlen = 1;
     int ret = recvmsg(sockfd, &hdr, flags);
     if (ret < 0)
         return ret;
     if(addrlen)
         *addrlen = hdr.msg_namelen;
     return ret;
 }
References buf, flags, iovec::iov_base, iovec::iov_len, msghdr::msg_iov, msghdr::msg_iovlen, msghdr::msg_name, msghdr::msg_namelen, recvmsg(), and ret.
Referenced by mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), and recv().
recvmmsg()
int recvmmsg (int sockfd, struct mmsghdr * msgvec, unsigned int vlen, int flags, struct timespec * timeout)
Definition at line 132 of file sys-socket-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
recvmsg()
ssize_t recvmsg (int fd, struct msghdr * hdr, int flags)
Definition at line 122 of file sys-socket-stubs.cpp.
{
     ssize_t length;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msg_recv, -1);
     if(int e = mlibc::sys_msg_recv(fd, hdr, flags, &length); e) {
         errno = e;
         return -1;
     }
     return length;
 }
References errno, fd, flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_msg_recv().
Referenced by recvfrom().
send()
ssize_t send (int fd, const void * buffer, size_t size, int flags)
Definition at line 137 of file sys-socket-stubs.cpp.
{
     return sendto(fd, buffer, size, flags, nullptr, 0);
 }
References fd, flags, sendto(), and size.
Referenced by _vsyslog().
sendmmsg()
int sendmmsg (int sockfd, struct mmsghdr * msgvec, unsigned int vlen, int flags)
Definition at line 169 of file sys-socket-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sendmsg()
ssize_t sendmsg (int fd, const struct msghdr * hdr, int flags)
Definition at line 156 of file sys-socket-stubs.cpp.
{
     if(hdr->msg_iovlen > IOV_MAX)
         return EMSGSIZE;
     ssize_t length;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msg_send, -1);
     if(int e = mlibc::sys_msg_send(fd, hdr, flags, &length); e) {
         errno = e;
         return -1;
     }
     return length;
 }
References EMSGSIZE, errno, fd, flags, IOV_MAX, MLIBC_CHECK_OR_ENOSYS, msghdr::msg_iovlen, and mlibc::sys_msg_send().
Referenced by sendto().
sendto()
ssize_t sendto (int fd, const void * buffer, size_t size, int flags, const struct sockaddr * sock_addr, socklen_t addr_length)
Definition at line 141 of file sys-socket-stubs.cpp.
{
     struct iovec iov = {};
     iov.iov_base = const_cast<void *>(buffer);
     iov.iov_len = size;
     struct msghdr hdr = {};
     hdr.msg_name = const_cast<struct sockaddr *>(sock_addr);
     hdr.msg_namelen = addr_length;
     hdr.msg_iov = &iov;
     hdr.msg_iovlen = 1;
     return sendmsg(fd, &hdr, flags);
 }
References fd, flags, iovec::iov_base, iovec::iov_len, msghdr::msg_iov, msghdr::msg_iovlen, msghdr::msg_name, msghdr::msg_namelen, sendmsg(), and size.
Referenced by mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), and send().
setsockopt()
int setsockopt (int fd, int layer, int number, const void * buffer, socklen_t size)
Definition at line 174 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setsockopt, -1);
     return mlibc::sys_setsockopt(fd, layer, number, buffer, size);
 }
References fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_setsockopt().
Referenced by socket_setup().
shutdown()
int shutdown (int , int)
Definition at line 180 of file sys-socket-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: shutdown() is a no-op!" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
sockatmark()
int sockatmark (int)
Definition at line 185 of file sys-socket-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
socket()
int socket (int family, int type, int protocol)
Definition at line 190 of file sys-socket-stubs.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_socket, -1);
     if(int e = mlibc::sys_socket(family, type, protocol, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_socket().
Referenced by __openlog(), NetworkUDP::UDP::Connect(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), run_test(), and socket_setup().
socketpair()
int socketpair (int domain, int type, int protocol, int sv[2])
Definition at line 200 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_socketpair, -1);
     if(int e = mlibc::sys_socketpair(domain, type, protocol, sv); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_socketpair().