Fennix Userspace: Userspace/apps/base/busybox/networking/udhcp/dhcprelay.c File Reference
dhcprelay.c File Reference
#include "common.h"
Data Structures
struct xid_item
Macros
#define SERVER_PORT 67
#define MAX_LIFETIME 2*60
#define SELECT_TIMEOUT (MAX_LIFETIME / 8)
#define dhcprelay_xid_list (*(struct xid_item*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Functions
static struct xid_item * xid_add (uint32_t xid, struct sockaddr_in *ip, unsigned iface_no)
static void xid_expire (void)
static struct xid_item * xid_find (uint32_t xid)
static void xid_del (uint32_t xid)
static int get_dhcp_packet_type (struct dhcp_packet *p)
static char ** make_iface_list (char **client_and_server_ifaces, unsigned *client_number)
static unsigned init_sockets (char **iface_list, unsigned num_clients, int *fds)
static int sendto_ip4 (int sock, const void *msg, int msg_len, struct sockaddr_in *to)
static void pass_to_server (struct dhcp_packet *p, int packet_len, unsigned from_iface_no, int *fds, struct sockaddr_in *client_addr, struct sockaddr_in *server_addr)
static void pass_to_client (struct dhcp_packet *p, int packet_len, int *fds)
int dhcprelay_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct xid_item FIX_ALIASING
Data Structure Documentation
xid_item
struct xid_item
Definition at line 33 of file dhcprelay.c.
Data Fields
unsigned iface_no
struct sockaddr_in ip
struct xid_item * next
unsigned timestamp
uint32_t xid
Macro Definition Documentation
dhcprelay_xid_list
#define dhcprelay_xid_list (*(struct xid_item*)bb_common_bufsiz1)
Definition at line 41 of file dhcprelay.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 42 of file dhcprelay.c.
MAX_LIFETIME
#define MAX_LIFETIME 2*60
Definition at line 28 of file dhcprelay.c.
SELECT_TIMEOUT
#define SELECT_TIMEOUT (MAX_LIFETIME / 8)
Definition at line 30 of file dhcprelay.c.
SERVER_PORT
#define SERVER_PORT 67
Definition at line 25 of file dhcprelay.c.
Function Documentation
dhcprelay_main()
int dhcprelay_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 267 of file dhcprelay.c.
 {
     struct sockaddr_in server_addr;
     char **iface_list;
     int *fds;
     unsigned num_sockets, max_socket;
     uint32_t our_nip;
     INIT_G();
     server_addr.sin_family = AF_INET;
     server_addr.sin_addr.s_addr = htonl(INADDR_BROADCAST);
     server_addr.sin_port = htons(SERVER_PORT);
     /* dhcprelay CLIENT_IFACE1[,CLIENT_IFACE2...] SERVER_IFACE [SERVER_IP] */
     if (!argv[1] || !argv[2])
         bb_show_usage();
     if (argv[3]) {
         if (!inet_aton(argv[3], &server_addr.sin_addr))
             bb_simple_perror_msg_and_die("bad server IP");
     }
     iface_list = make_iface_list(argv + 1, &num_sockets);
     fds = xmalloc(num_sockets * sizeof(fds[0]));
     /* Create sockets and bind one to every iface */
     max_socket = init_sockets(iface_list, num_sockets, fds);
     /* Get our IP on server_iface */
     if (udhcp_read_interface(argv[2], NULL, &our_nip, NULL))
         return 1;
     /* Main loop */
     while (1) {
 // reinit stuff from time to time? go back to make_iface_list
 // every N minutes?
         fd_set rfds;
         struct timeval tv;
         unsigned i;
         FD_ZERO(&rfds);
         for (i = 0; i < num_sockets; i++)
             FD_SET(fds[i], &rfds);
         tv.tv_sec = SELECT_TIMEOUT;
         tv.tv_usec = 0;
         if (select(max_socket + 1, &rfds, NULL, NULL, &tv) > 0) {
             int packlen;
             struct dhcp_packet dhcp_msg;
             /* from server */
             if (FD_ISSET(fds[0], &rfds)) {
                 packlen = udhcp_recv_kernel_packet(&dhcp_msg, fds[0]);
 //NB: we do not check source port here. Should we?
 //It should be SERVER_PORT.
                 if (packlen > 0) {
                     pass_to_client(&dhcp_msg, packlen, fds);
                 }
             }
             /* from clients */
             for (i = 1; i < num_sockets; i++) {
                 struct sockaddr_in client_addr;
                 socklen_t addr_size;
                 if (!FD_ISSET(fds[i], &rfds))
                     continue;
                 addr_size = sizeof(client_addr);
                 packlen = recvfrom(fds[i], &dhcp_msg, sizeof(dhcp_msg), 0,
                         (struct sockaddr *)(&client_addr), &addr_size);
                 if (packlen <= 0)
                     continue;
 //NB: we do not check source port here. Should we?
 //It should be CLIENT_PORT for clients.
 //It can be SERVER_PORT for relay agents (in which case giaddr must be != 0.0.0.0),
 //but is it even supported to chain relay agents like this?
 //(we still copy client_addr.port and use it to reply to the port we got request from)
                 /* Get our IP on corresponding client_iface */
 // RFC 1542
 // 4.1 General BOOTP Processing for Relay Agents
 // 4.1.1 BOOTREQUEST Messages
 //   If the relay agent does decide to relay the request, it MUST examine
 //   the 'giaddr' ("gateway" IP address) field.  If this field is zero,
 //   the relay agent MUST fill this field with the IP address of the
 //   interface on which the request was received.  If the interface has
 //   more than one IP address logically associated with it, the relay
 //   agent SHOULD choose one IP address associated with that interface and
 //   use it consistently for all BOOTP messages it relays.  If the
 //   'giaddr' field contains some non-zero value, the 'giaddr' field MUST
 //   NOT be modified.  The relay agent MUST NOT, under any circumstances,
 //   fill the 'giaddr' field with a broadcast address as is suggested in
 //   [1] (Section 8, sixth paragraph).
 // but why? what if server can't route such IP? Client ifaces may be, say, NATed!
 // 4.1.2 BOOTREPLY Messages
 //   BOOTP relay agents relay BOOTREPLY messages only to BOOTP clients.
 //   It is the responsibility of BOOTP servers to send BOOTREPLY messages
 //   directly to the relay agent identified in the 'giaddr' field.
 // (yeah right, unless it is impossible... see comment above)
 //   Therefore, a relay agent may assume that all BOOTREPLY messages it
 //   receives are intended for BOOTP clients on its directly-connected
 //   networks.
 //
 //   When a relay agent receives a BOOTREPLY message, it should examine
 //   the BOOTP 'giaddr', 'yiaddr', 'chaddr', 'htype', and 'hlen' fields.
 //   These fields should provide adequate information for the relay agent
 //   to deliver the BOOTREPLY message to the client.
 //
 //   The 'giaddr' field can be used to identify the logical interface from
 //   which the reply must be sent (i.e., the host or router interface
 //   connected to the same network as the BOOTP client).  If the content
 //   of the 'giaddr' field does not match one of the relay agent's
 //   directly-connected logical interfaces, the BOOTREPLY message MUST be
 //   silently discarded.
                 if (udhcp_read_interface(iface_list[i], NULL, &dhcp_msg.gateway_nip, NULL)) {
                     /* Fall back to our IP on server iface */
 // this makes more sense!
                     dhcp_msg.gateway_nip = our_nip;
                 }
 // maybe dhcp_msg.hops++? drop packets with too many hops (RFC 1542 says 4 or 16)?
                 pass_to_server(&dhcp_msg, packlen, i, fds, &client_addr, &server_addr);
             }
         }
         xid_expire();
     } /* while (1) */
     /* return 0; - not reached */
 }
References AF_INET, argv, bb_show_usage(), bb_simple_perror_msg_and_die(), FD_ISSET, FD_SET, FD_ZERO, dhcp_packet::gateway_nip, htonl(), htons(), i, INADDR_BROADCAST, inet_aton(), INIT_G, init_sockets(), make_iface_list(), NULL, packlen, pass_to_client(), pass_to_server(), recvfrom(), in_addr::s_addr, select(), SELECT_TIMEOUT, SERVER_PORT, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, timeval::tv_sec, timeval::tv_usec, udhcp_read_interface(), udhcp_recv_kernel_packet(), xid_expire(), and xmalloc.
get_dhcp_packet_type()
static int get_dhcp_packet_type (struct dhcp_packet * p) static
get_dhcp_packet_type - gets the message type of a dhcp packet p - pointer to the dhcp packet returns the message type on success, -1 otherwise
Definition at line 113 of file dhcprelay.c.
 {
     uint8_t *op;
     /* it must be either a BOOTREQUEST or a BOOTREPLY */
     if (p->op != BOOTREQUEST && p->op != BOOTREPLY)
         return -1;
     /* get message type option */
     op = udhcp_get_option(p, DHCP_MESSAGE_TYPE);
     if (op != NULL)
         return op[0];
     return -1;
 }
References BOOTREPLY, BOOTREQUEST, DHCP_MESSAGE_TYPE, NULL, p, and udhcp_get_option().
Referenced by pass_to_client(), and pass_to_server().
init_sockets()
static unsigned init_sockets (char ** iface_list, unsigned num_clients, int * fds) static
Definition at line 169 of file dhcprelay.c.
 {
     unsigned i, n;
     n = 0;
     for (i = 0; i < num_clients; i++) {
         fds[i] = udhcp_listen_socket(/*INADDR_ANY,*/ SERVER_PORT, iface_list[i]);
         if (n < fds[i])
             n = fds[i];
     }
     return n;
 }
References i, n, SERVER_PORT, and udhcp_listen_socket().
Referenced by dhcprelay_main().
make_iface_list()
static char** make_iface_list (char ** client_and_server_ifaces, unsigned * client_number) static
make_iface_list - parses client/server interface names returns array
Definition at line 131 of file dhcprelay.c.
 {
     char *s, **iface_list;
     unsigned i, cn;
     /* get number of items */
     cn = 2; /* 1 server iface + at least 1 client one */
     s = client_and_server_ifaces[0]; /* list of client ifaces */
     while (*s) {
         if (*s == ',')
             cn++;
         s++;
     }
     *client_number = cn;
     /* create vector of pointers */
     iface_list = xzalloc(cn * sizeof(iface_list[0]));
     iface_list[0] = client_and_server_ifaces[1]; /* server iface */
     i = 1;
     s = xstrdup(client_and_server_ifaces[0]); /* list of client ifaces */
     goto store_client_iface_name;
     while (i < cn) {
         if (*s++ == ',') {
             s[-1] = '\0';
  store_client_iface_name:
             iface_list[i++] = s;
         }
     }
     return iface_list;
 }
References i, s, xstrdup(), and xzalloc().
Referenced by dhcprelay_main().
pass_to_client()
static void pass_to_client (struct dhcp_packet * p, int packet_len, int * fds) static
pass_to_client() - forwards dhcp packets from server to client p - packet to send
Definition at line 232 of file dhcprelay.c.
 {
     int type;
     struct xid_item *item;
     /* check packet type */
     type = get_dhcp_packet_type(p);
 //FIXME: the above does not consider packet_len!
     if (type != DHCPOFFER && type != DHCPACK && type != DHCPNAK) {
         return;
     }
     /* check xid */
     item = xid_find(p->xid);
     if (!item) {
         return;
     }
 //NB: RFC 1542 section 4.1 seems to envision the logic that
 //relay agents use giaddr (dhcp_msg.gateway_nip in our code)
 //to find out on which interface to reply.
 //(server is meant to copy giaddr from our request packet to its reply).
 //Above, we don't use that logic, instead we use xid as a key.
 //TODO: also do it if (p->flags & htons(BROADCAST_FLAG)) is set!
     if (item->ip.sin_addr.s_addr == htonl(INADDR_ANY))
         item->ip.sin_addr.s_addr = htonl(INADDR_BROADCAST);
     sendto_ip4(fds[item->iface_no], p, packet_len, &item->ip);
     /* ^^^ if send error occurred, we can't do much, hence no check */
     /* remove xid entry */
     xid_del(p->xid);
 }
References DHCPACK, DHCPNAK, DHCPOFFER, get_dhcp_packet_type(), htonl(), xid_item::iface_no, INADDR_ANY, INADDR_BROADCAST, xid_item::ip, p, in_addr::s_addr, sendto_ip4(), sockaddr_in::sin_addr, type, xid_del(), and xid_find().
Referenced by dhcprelay_main().
pass_to_server()
static void pass_to_server (struct dhcp_packet * p, int packet_len, unsigned from_iface_no, int * fds, struct sockaddr_in * client_addr, struct sockaddr_in * server_addr) static
pass_to_server() - forwards dhcp packets from client to server p - packet to send client - number of the client
Definition at line 199 of file dhcprelay.c.
 {
     int type;
     /* check packet_type */
     type = get_dhcp_packet_type(p);
 //FIXME: the above does not consider packet_len!
     if (type != DHCPDISCOVER && type != DHCPREQUEST
      && type != DHCPDECLINE && type != DHCPRELEASE
      && type != DHCPINFORM
     ) {
         return;
     }
     /* create new xid entry */
     xid_add(p->xid, client_addr, from_iface_no);
 //TODO: since we key request/reply pairs on xid values, shouldn't we drop new requests
 //with xid accidentally matching a xid of one of requests we currently hold
 //waiting for their replies?
     /* forward request to server */
     /* note that we send from fds[0] which is bound to SERVER_PORT (67).
      * IOW: we send _from_ SERVER_PORT! Although this may look strange,
      * RFC 1542 not only allows, but prescribes this for BOOTP relays.
      */
     sendto_ip4(fds[0], p, packet_len, server_addr);
 }
References DHCPDECLINE, DHCPDISCOVER, DHCPINFORM, DHCPRELEASE, DHCPREQUEST, get_dhcp_packet_type(), p, sendto_ip4(), type, and xid_add().
Referenced by dhcprelay_main().
sendto_ip4()
static int sendto_ip4 (int sock, const void * msg, int msg_len, struct sockaddr_in * to) static
Definition at line 182 of file dhcprelay.c.
 {
     int err;
     errno = 0;
     err = sendto(sock, msg, msg_len, 0, (struct sockaddr*) to, sizeof(*to));
     err -= msg_len;
     if (err)
         bb_simple_perror_msg("sendto");
     return err;
 }
References bb_simple_perror_msg(), err(), errno, sendto(), and sock.
Referenced by pass_to_client(), and pass_to_server().
xid_add()
static struct xid_item* xid_add (uint32_t xid, struct sockaddr_in * ip, unsigned iface_no) static
Definition at line 44 of file dhcprelay.c.
 {
     struct xid_item *item;
     /* create new xid entry */
     item = xmalloc(sizeof(struct xid_item));
     /* add xid entry */
     item->ip = *ip;
     item->xid = xid;
     item->iface_no = iface_no;
     item->timestamp = monotonic_sec();
     item->next = dhcprelay_xid_list.next;
     dhcprelay_xid_list.next = item;
     return item;
 }
References dhcprelay_xid_list, xid_item::iface_no, xid_item::ip, monotonic_sec(), xid_item::next, xid_item::timestamp, xid_item::xid, and xmalloc.
Referenced by pass_to_server().
xid_del()
static void xid_del (uint32_t xid) static
Definition at line 92 of file dhcprelay.c.
 {
     struct xid_item *item = dhcprelay_xid_list.next;
     struct xid_item *last = &dhcprelay_xid_list;
     while (item != NULL) {
         if (item->xid == xid) {
             last->next = item->next;
             free(item);
             item = last->next;
         } else {
             last = item;
             item = item->next;
         }
     }
 }
References dhcprelay_xid_list, free, last, xid_item::next, NULL, and xid_item::xid.
Referenced by pass_to_client().
xid_expire()
static void xid_expire (void) static
Definition at line 62 of file dhcprelay.c.
 {
     struct xid_item *item = dhcprelay_xid_list.next;
     struct xid_item *last = &dhcprelay_xid_list;
     unsigned current_time = monotonic_sec();
     while (item != NULL) {
         if ((current_time - item->timestamp) > MAX_LIFETIME) {
             last->next = item->next;
             free(item);
             item = last->next;
         } else {
             last = item;
             item = item->next;
         }
     }
 }
References dhcprelay_xid_list, free, last, MAX_LIFETIME, monotonic_sec(), xid_item::next, NULL, and xid_item::timestamp.
Referenced by dhcprelay_main().
xid_find()
static struct xid_item* xid_find (uint32_t xid) static
Definition at line 80 of file dhcprelay.c.
 {
     struct xid_item *item = dhcprelay_xid_list.next;
     while (item != NULL) {
         if (item->xid == xid) {
             break;
         }
         item = item->next;
     }
     return item;
 }
References dhcprelay_xid_list, xid_item::next, NULL, and xid_item::xid.
Referenced by pass_to_client().
Variable Documentation
FIX_ALIASING
struct xid_item FIX_ALIASING