Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/d_net.c File Reference
d_net.c File Reference
#include <stdlib.h>
#include "doomfeatures.h"
#include "d_main.h"
#include "m_argv.h"
#include "m_menu.h"
#include "m_misc.h"
#include "i_system.h"
#include "i_timer.h"
#include "i_video.h"
#include "g_game.h"
#include "doomdef.h"
#include "doomstat.h"
#include "w_checksum.h"
#include "w_wad.h"
#include "deh_main.h"
#include "d_loop.h"
Functions
static void PlayerQuitGame (player_t *player)
static void RunTic (ticcmd_t *cmds, boolean *ingame)
static void LoadGameSettings (net_gamesettings_t *settings)
static void SaveGameSettings (net_gamesettings_t *settings)
static void InitConnectData (net_connect_data_t *connect_data)
void D_ConnectNetGame (void)
void D_CheckNetGame (void)
Variables
ticcmd_t * netcmds
static loop_interface_t doom_loop_interface
Function Documentation
D_CheckNetGame()
void D_CheckNetGame (void)
Definition at line 240 of file d_net.c.
 {
     net_gamesettings_t settings;
     if (netgame)
     {
         autostart = true;
     }
     D_RegisterLoopCallbacks(&doom_loop_interface);
     SaveGameSettings(&settings);
     D_StartNetGame(&settings, NULL);
     LoadGameSettings(&settings);
     DEH_printf("startskill %i  deathmatch: %i  startmap: %i  startepisode: %i\n",
                startskill, deathmatch, startmap, startepisode);
     DEH_printf("player %i of %i (%i nodes)\n",
                consoleplayer+1, settings.num_players, settings.num_players);
     // Show players here; the server might have specified a time limit
     if (timelimit > 0 && deathmatch)
     {
         // Gross hack to work like Vanilla:
         if (timelimit == 20 && M_CheckParm("-avg"))
         {
             DEH_printf("Austin Virtual Gaming: Levels will end "
                            "after 20 minutes\n");
         }
         else
         {
             DEH_printf("Levels will end after %d minute", timelimit);
             if (timelimit > 1)
                 printf("s");
             printf(".\n");
         }
     }
 }
References autostart, consoleplayer, D_RegisterLoopCallbacks(), D_StartNetGame(), deathmatch, DEH_printf, doom_loop_interface, LoadGameSettings(), M_CheckParm(), netgame, NULL, net_gamesettings_t::num_players, printf(), SaveGameSettings(), startepisode, startmap, startskill, and timelimit.
Referenced by D_DoomMain().
D_ConnectNetGame()
void D_ConnectNetGame (void)
Definition at line 215 of file d_net.c.
 {
     net_connect_data_t connect_data;
     InitConnectData(&connect_data);
     netgame = D_InitNetGame(&connect_data);
     // @category net
     //
     // Start the game playing as though in a netgame with a single
     // player.  This can also be used to play back single player netgame
     // demos.
     //
     if (M_CheckParm("-solo-net") > 0)
     {
         netgame = true;
     }
 }
References D_InitNetGame(), InitConnectData(), M_CheckParm(), and netgame.
Referenced by D_DoomMain().
InitConnectData()
static void InitConnectData (net_connect_data_t * connect_data) static
Definition at line 159 of file d_net.c.
 {
     connect_data->max_players = MAXPLAYERS;
     connect_data->drone = false;
     // @category net
     //
     // Run as the left screen in three screen mode.
     //
     if (M_CheckParm("-left") > 0)
     {
         viewangleoffset = ANG90;
         connect_data->drone = true;
     }
     // @category net
     //
     // Run as the right screen in three screen mode.
     //
     if (M_CheckParm("-right") > 0)
     {
         viewangleoffset = ANG270;
         connect_data->drone = true;
     }
     //
     // Connect data
     //
     // Game type fields:
     connect_data->gamemode = gamemode;
     connect_data->gamemission = gamemission;
     // Are we recording a demo? Possibly set lowres turn mode
     connect_data->lowres_turn = M_CheckParm("-record") > 0
                              && M_CheckParm("-longtics") == 0;
     // Read checksums of our WAD directory and dehacked information
     W_Checksum(connect_data->wad_sha1sum);
 #if ORIGCODE
     DEH_Checksum(connect_data->deh_sha1sum);
 #endif
     // Are we playing with the Freedoom IWAD?
     connect_data->is_freedoom = W_CheckNumForName("FREEDOOM") >= 0;
 }
References ANG270, ANG90, DEH_Checksum(), net_connect_data_t::deh_sha1sum, net_connect_data_t::drone, gamemission, net_connect_data_t::gamemission, gamemode, net_connect_data_t::gamemode, net_connect_data_t::is_freedoom, net_connect_data_t::lowres_turn, M_CheckParm(), net_connect_data_t::max_players, MAXPLAYERS, viewangleoffset, W_CheckNumForName(), W_Checksum(), and net_connect_data_t::wad_sha1sum.
Referenced by D_ConnectNetGame().
LoadGameSettings()
static void LoadGameSettings (net_gamesettings_t * settings) static
Definition at line 108 of file d_net.c.
 {
     unsigned int i;
     deathmatch = settings->deathmatch;
     startepisode = settings->episode;
     startmap = settings->map;
     startskill = settings->skill;
     startloadgame = settings->loadgame;
     lowres_turn = settings->lowres_turn;
     nomonsters = settings->nomonsters;
     fastparm = settings->fast_monsters;
     respawnparm = settings->respawn_monsters;
     timelimit = settings->timelimit;
     consoleplayer = settings->consoleplayer;
     if (lowres_turn)
     {
         printf("NOTE: Turning resolution is reduced; this is probably "
                "because there is a client recording a Vanilla demo.\n");
     }
     for (i = 0; i < MAXPLAYERS; ++i)
     {
         playeringame[i] = i < settings->num_players;
     }
 }
References consoleplayer, net_gamesettings_t::consoleplayer, deathmatch, net_gamesettings_t::deathmatch, net_gamesettings_t::episode, net_gamesettings_t::fast_monsters, fastparm, i, net_gamesettings_t::loadgame, lowres_turn, net_gamesettings_t::lowres_turn, net_gamesettings_t::map, MAXPLAYERS, nomonsters, net_gamesettings_t::nomonsters, net_gamesettings_t::num_players, playeringame, printf(), net_gamesettings_t::respawn_monsters, respawnparm, net_gamesettings_t::skill, startepisode, startloadgame, startmap, startskill, timelimit, and net_gamesettings_t::timelimit.
Referenced by D_CheckNetGame().
PlayerQuitGame()
static void PlayerQuitGame (player_t * player) static
Definition at line 45 of file d_net.c.
 {
     static char exitmsg[80];
     unsigned int player_num;
     player_num = player - players;
     // Do this the same way as Vanilla Doom does, to allow dehacked
     // replacements of this message
     M_StringCopy(exitmsg, DEH_String("Player 1 left the game"),
                  sizeof(exitmsg));
     exitmsg[7] += player_num;
     playeringame[player_num] = false;
     players[consoleplayer].message = exitmsg;
     // TODO: check if it is sensible to do this:
     if (demorecording)
     {
         G_CheckDemoStatus ();
     }
 }
References consoleplayer, DEH_String, demorecording, G_CheckDemoStatus(), M_StringCopy(), player_s::message, playeringame, and players.
Referenced by RunTic().
RunTic()
static void RunTic (ticcmd_t * cmds, boolean * ingame) static
Definition at line 71 of file d_net.c.
 {
     extern boolean advancedemo;
     unsigned int i;
     // Check for player quits.
     for (i = 0; i < MAXPLAYERS; ++i)
     {
         if (!demoplayback && playeringame[i] && !ingame[i])
         {
             PlayerQuitGame(&players[i]);
         }
     }
     netcmds = cmds;
     // check that there are players in the game.  if not, we cannot
     // run a tic.
     if (advancedemo)
         D_DoAdvanceDemo ();
     G_Ticker ();
 }
References advancedemo, D_DoAdvanceDemo(), demoplayback, G_Ticker(), i, MAXPLAYERS, netcmds, playeringame, PlayerQuitGame(), and players.
SaveGameSettings()
static void SaveGameSettings (net_gamesettings_t * settings) static
Definition at line 139 of file d_net.c.
 {
     // Fill in game settings structure with appropriate parameters
     // for the new game
     settings->deathmatch = deathmatch;
     settings->episode = startepisode;
     settings->map = startmap;
     settings->skill = startskill;
     settings->loadgame = startloadgame;
     settings->gameversion = gameversion;
     settings->nomonsters = nomonsters;
     settings->fast_monsters = fastparm;
     settings->respawn_monsters = respawnparm;
     settings->timelimit = timelimit;
     settings->lowres_turn = M_CheckParm("-record") > 0
                          && M_CheckParm("-longtics") == 0;
 }
References deathmatch, net_gamesettings_t::deathmatch, net_gamesettings_t::episode, net_gamesettings_t::fast_monsters, fastparm, gameversion, net_gamesettings_t::gameversion, net_gamesettings_t::loadgame, net_gamesettings_t::lowres_turn, M_CheckParm(), net_gamesettings_t::map, nomonsters, net_gamesettings_t::nomonsters, net_gamesettings_t::respawn_monsters, respawnparm, net_gamesettings_t::skill, startepisode, startloadgame, startmap, startskill, timelimit, and net_gamesettings_t::timelimit.
Referenced by D_CheckNetGame().
Variable Documentation
doom_loop_interface
loop_interface_t doom_loop_interface static
Initial value:
= {
    D_ProcessEvents,
    G_BuildTiccmd,
    RunTic,
    M_Ticker
}
Definition at line 97 of file d_net.c.
Referenced by D_CheckNetGame().
netcmds
ticcmd_t* netcmds
Definition at line 41 of file d_net.c.
Referenced by G_Ticker(), and RunTic().