Fennix Kernel: Random Namespace Reference
Random Namespace Reference
Functions
uint16_t rand16 ()
uint32_t rand32 ()
uint64_t rand64 ()
void ChangeSeed (uint64_t CustomSeed)
Variables
static uint64_t Seed = 0xdeadbeef
Function Documentation
ChangeSeed()
void Random::ChangeSeed (uint64_t CustomSeed)
Definition at line 155 of file Random.cpp.
 { Seed = CustomSeed; }
References Seed.
rand16()
uint16_t Random::rand16 ()
Definition at line 8 of file Random.cpp.
     {
         int RDRANDFlag = 0;
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
 #if defined(__amd64__)
             CPU::x64::AMD::CPUID0x1 cpuid1amd;
 #elif defined(__i386__)
             CPU::x32::AMD::CPUID0x1 cpuid1amd;
 #endif
 #if defined(__amd64__) || defined(__i386__)
             asmv("cpuid"
                  : "=a"(cpuid1amd.EAX.raw), "=b"(cpuid1amd.EBX.raw), "=c"(cpuid1amd.ECX.raw), "=d"(cpuid1amd.EDX.raw)
                  : "a"(0x1));
 #endif
             RDRANDFlag = cpuid1amd.ECX.RDRAND;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
 #if defined(__amd64__)
             CPU::x64::Intel::CPUID0x1 cpuid1intel;
 #elif defined(__i386__)
             CPU::x32::Intel::CPUID0x1 cpuid1intel;
 #endif
 #if defined(__amd64__) || defined(__i386__)
             asmv("cpuid"
                  : "=a"(cpuid1intel.EAX.raw), "=b"(cpuid1intel.EBX.raw), "=c"(cpuid1intel.ECX.raw), "=d"(cpuid1intel.EDX.raw)
                  : "a"(0x1));
 #endif
             RDRANDFlag = cpuid1intel.ECX.RDRAND;
         }
         if (strcmp(CPU::Hypervisor(), x86_CPUID_VENDOR_TCG) == 0)
             RDRANDFlag = 0;
 #if defined(__amd64__) || defined(__i386__)
         if (RDRANDFlag)
         {
             uint16_t RDRANDValue = 0;
             asmv("1: rdrand %0; jnc 1b"
                  : "=r"(RDRANDValue));
             return RDRANDValue;
         }
 #endif
         Seed = Seed * 1103515245 + 12345;
         return (uint16_t)(Seed / 65536) % __UINT16_MAX__;
     }
References asmv, CPU::x64::AMD::CPUID0x1::EAX, CPU::x64::Intel::CPUID0x1::EAX, CPU::x64::AMD::CPUID0x1::EBX, CPU::x64::Intel::CPUID0x1::EBX, CPU::x64::AMD::CPUID0x1::ECX, CPU::x64::Intel::CPUID0x1::ECX, CPU::x64::AMD::CPUID0x1::EDX, CPU::x64::Intel::CPUID0x1::EDX, CPU::Hypervisor(), Seed, strcmp(), CPU::Vendor(), x86_CPUID_VENDOR_AMD, x86_CPUID_VENDOR_INTEL, and x86_CPUID_VENDOR_TCG.
rand32()
uint32_t Random::rand32 ()
Definition at line 57 of file Random.cpp.
     {
         int RDRANDFlag = 0;
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
 #if defined(__amd64__)
             CPU::x64::AMD::CPUID0x1 cpuid1amd;
 #elif defined(__i386__)
             CPU::x32::AMD::CPUID0x1 cpuid1amd;
 #endif
 #if defined(__amd64__) || defined(__i386__)
             asmv("cpuid"
                  : "=a"(cpuid1amd.EAX.raw), "=b"(cpuid1amd.EBX.raw), "=c"(cpuid1amd.ECX.raw), "=d"(cpuid1amd.EDX.raw)
                  : "a"(0x1));
 #endif
             RDRANDFlag = cpuid1amd.ECX.RDRAND;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
 #if defined(__amd64__)
             CPU::x64::Intel::CPUID0x1 cpuid1intel;
 #elif defined(__i386__)
             CPU::x32::Intel::CPUID0x1 cpuid1intel;
 #endif
 #if defined(__amd64__) || defined(__i386__)
             asmv("cpuid"
                  : "=a"(cpuid1intel.EAX.raw), "=b"(cpuid1intel.EBX.raw), "=c"(cpuid1intel.ECX.raw), "=d"(cpuid1intel.EDX.raw)
                  : "a"(0x1));
 #endif
             RDRANDFlag = cpuid1intel.ECX.RDRAND;
         }
         if (strcmp(CPU::Hypervisor(), x86_CPUID_VENDOR_TCG) == 0)
             RDRANDFlag = 0;
 #if defined(__amd64__) || defined(__i386__)
         if (RDRANDFlag)
         {
             uint32_t RDRANDValue = 0;
             asmv("1: rdrand %0; jnc 1b"
                  : "=r"(RDRANDValue));
             return RDRANDValue;
         }
 #endif
         Seed = Seed * 1103515245 + 12345;
         return (uint32_t)(Seed / 65536) % __UINT16_MAX__;
     }
References asmv, CPU::x64::AMD::CPUID0x1::EAX, CPU::x64::Intel::CPUID0x1::EAX, CPU::x64::AMD::CPUID0x1::EBX, CPU::x64::Intel::CPUID0x1::EBX, CPU::x64::AMD::CPUID0x1::ECX, CPU::x64::Intel::CPUID0x1::ECX, CPU::x64::AMD::CPUID0x1::EDX, CPU::x64::Intel::CPUID0x1::EDX, CPU::Hypervisor(), Seed, strcmp(), CPU::Vendor(), x86_CPUID_VENDOR_AMD, x86_CPUID_VENDOR_INTEL, and x86_CPUID_VENDOR_TCG.
Referenced by __attribute__(), and CrashHandler::DisplayTopOverlay().
rand64()
uint64_t Random::rand64 ()
Definition at line 106 of file Random.cpp.
     {
         int RDRANDFlag = 0;
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
 #if defined(__amd64__)
             CPU::x64::AMD::CPUID0x1 cpuid1amd;
 #elif defined(__i386__)
             CPU::x32::AMD::CPUID0x1 cpuid1amd;
 #endif
 #if defined(__amd64__) || defined(__i386__)
             asmv("cpuid"
                  : "=a"(cpuid1amd.EAX.raw), "=b"(cpuid1amd.EBX.raw), "=c"(cpuid1amd.ECX.raw), "=d"(cpuid1amd.EDX.raw)
                  : "a"(0x1));
 #endif
             RDRANDFlag = cpuid1amd.ECX.RDRAND;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
 #if defined(__amd64__)
             CPU::x64::Intel::CPUID0x1 cpuid1intel;
 #elif defined(__i386__)
             CPU::x32::Intel::CPUID0x1 cpuid1intel;
 #endif
 #if defined(__amd64__) || defined(__i386__)
             asmv("cpuid"
                  : "=a"(cpuid1intel.EAX.raw), "=b"(cpuid1intel.EBX.raw), "=c"(cpuid1intel.ECX.raw), "=d"(cpuid1intel.EDX.raw)
                  : "a"(0x1));
 #endif
             RDRANDFlag = cpuid1intel.ECX.RDRAND;
         }
         if (strcmp(CPU::Hypervisor(), x86_CPUID_VENDOR_TCG) == 0)
             RDRANDFlag = 0;
 #if defined(__amd64__) || defined(__i386__)
         if (RDRANDFlag)
         {
             uint64_t RDRANDValue = 0;
             asmv("1: rdrand %0; jnc 1b"
                  : "=r"(RDRANDValue));
             return RDRANDValue;
         }
 #endif
         Seed = Seed * 1103515245 + 12345;
         return (uint64_t)(Seed / 65536) % __UINT16_MAX__;
     }
References asmv, CPU::x64::AMD::CPUID0x1::EAX, CPU::x64::Intel::CPUID0x1::EAX, CPU::x64::AMD::CPUID0x1::EBX, CPU::x64::Intel::CPUID0x1::EBX, CPU::x64::AMD::CPUID0x1::ECX, CPU::x64::Intel::CPUID0x1::ECX, CPU::x64::AMD::CPUID0x1::EDX, CPU::x64::Intel::CPUID0x1::EDX, CPU::Hypervisor(), Seed, strcmp(), CPU::Vendor(), x86_CPUID_VENDOR_AMD, x86_CPUID_VENDOR_INTEL, and x86_CPUID_VENDOR_TCG.
Referenced by __attribute__(), and Tasking::Security::CreateToken().
Variable Documentation
Seed
uint64_t Random::Seed = 0xdeadbeef static
Definition at line 6 of file Random.cpp.
Referenced by ChangeSeed(), rand16(), rand32(), and rand64().