Fennix Userspace: Userspace/apps/base/busybox/scripts/kconfig/lxdialog/dialog.h File Reference
dialog.h File Reference
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
Macros
#define OLD_NCURSES 0
#define TR(params) _tracef params
#define ESC 27
#define TAB 9
#define MAX_LEN 2048
#define BUF_SIZE (10*1024)
#define MIN(x, y) (x < y ? x : y)
#define MAX(x, y) (x > y ? x : y)
#define ACS_ULCORNER '+'
#define ACS_LLCORNER '+'
#define ACS_URCORNER '+'
#define ACS_LRCORNER '+'
#define ACS_HLINE '-'
#define ACS_VLINE '|'
#define ACS_LTEE '+'
#define ACS_RTEE '+'
#define ACS_UARROW '^'
#define ACS_DARROW 'v'
#define screen_attr attributes[0]
#define shadow_attr attributes[1]
#define dialog_attr attributes[2]
#define title_attr attributes[3]
#define border_attr attributes[4]
#define button_active_attr attributes[5]
#define button_inactive_attr attributes[6]
#define button_key_active_attr attributes[7]
#define button_key_inactive_attr attributes[8]
#define button_label_active_attr attributes[9]
#define button_label_inactive_attr attributes[10]
#define inputbox_attr attributes[11]
#define inputbox_border_attr attributes[12]
#define searchbox_attr attributes[13]
#define searchbox_title_attr attributes[14]
#define searchbox_border_attr attributes[15]
#define position_indicator_attr attributes[16]
#define menubox_attr attributes[17]
#define menubox_border_attr attributes[18]
#define item_attr attributes[19]
#define item_selected_attr attributes[20]
#define tag_attr attributes[21]
#define tag_selected_attr attributes[22]
#define tag_key_attr attributes[23]
#define tag_key_selected_attr attributes[24]
#define check_attr attributes[25]
#define check_selected_attr attributes[26]
#define uarrow_attr attributes[27]
#define darrow_attr attributes[28]
#define ATTRIBUTE_COUNT 29
#define M_EVENT (KEY_MAX+1)
Functions
void create_rc (const char *filename)
int parse_rc (void)
void init_dialog (void)
void end_dialog (void)
void attr_clear (WINDOW *win, int height, int width, chtype attr)
void dialog_clear (void)
void color_setup (void)
void print_autowrap (WINDOW *win, const char *prompt, int width, int y, int x)
void print_button (WINDOW *win, const char *label, int y, int x, int selected)
void print_title (WINDOW *dialog, const char *title, int width)
void draw_box (WINDOW *win, int y, int x, int height, int width, chtype box, chtype border)
void draw_shadow (WINDOW *win, int y, int x, int height, int width)
int first_alpha (const char *string, const char *exempt)
int dialog_yesno (const char *title, const char *prompt, int height, int width)
int dialog_msgbox (const char *title, const char *prompt, int height, int width, int pause)
int dialog_textbox (const char *title, const char *file, int height, int width)
int dialog_menu (const char *title, const char *prompt, int height, int width, int menu_height, const char *choice, int item_no, const char *const *items)
int dialog_checklist (const char *title, const char *prompt, int height, int width, int list_height, int item_no, const char *const *items)
int dialog_inputbox (const char *title, const char *prompt, int height, int width, const char *init)
Variables
bool use_colors
bool use_shadow
chtype attributes []
const char * backtitle
char dialog_input_result []
Macro Definition Documentation
ACS_DARROW
#define ACS_DARROW 'v'
Definition at line 86 of file dialog.h.
ACS_HLINE
#define ACS_HLINE '-'
Definition at line 71 of file dialog.h.
ACS_LLCORNER
#define ACS_LLCORNER '+'
Definition at line 62 of file dialog.h.
ACS_LRCORNER
#define ACS_LRCORNER '+'
Definition at line 68 of file dialog.h.
ACS_LTEE
#define ACS_LTEE '+'
Definition at line 77 of file dialog.h.
ACS_RTEE
#define ACS_RTEE '+'
Definition at line 80 of file dialog.h.
ACS_UARROW
#define ACS_UARROW '^'
Definition at line 83 of file dialog.h.
ACS_ULCORNER
#define ACS_ULCORNER '+'
Definition at line 59 of file dialog.h.
ACS_URCORNER
#define ACS_URCORNER '+'
Definition at line 65 of file dialog.h.
ACS_VLINE
#define ACS_VLINE '|'
Definition at line 74 of file dialog.h.
ATTRIBUTE_COUNT
#define ATTRIBUTE_COUNT 29
Definition at line 123 of file dialog.h.
border_attr
#define border_attr attributes[4]
Definition at line 96 of file dialog.h.
BUF_SIZE
#define BUF_SIZE (10*1024)
Definition at line 54 of file dialog.h.
button_active_attr
#define button_active_attr attributes[5]
Definition at line 97 of file dialog.h.
button_inactive_attr
#define button_inactive_attr attributes[6]
Definition at line 98 of file dialog.h.
button_key_active_attr
#define button_key_active_attr attributes[7]
Definition at line 99 of file dialog.h.
button_key_inactive_attr
#define button_key_inactive_attr attributes[8]
Definition at line 100 of file dialog.h.
button_label_active_attr
#define button_label_active_attr attributes[9]
Definition at line 101 of file dialog.h.
button_label_inactive_attr
#define button_label_inactive_attr attributes[10]
Definition at line 102 of file dialog.h.
check_attr
#define check_attr attributes[25]
Definition at line 117 of file dialog.h.
check_selected_attr
#define check_selected_attr attributes[26]
Definition at line 118 of file dialog.h.
darrow_attr
#define darrow_attr attributes[28]
Definition at line 120 of file dialog.h.
dialog_attr
#define dialog_attr attributes[2]
Definition at line 94 of file dialog.h.
ESC
#define ESC 27
Definition at line 51 of file dialog.h.
inputbox_attr
#define inputbox_attr attributes[11]
Definition at line 103 of file dialog.h.
inputbox_border_attr
#define inputbox_border_attr attributes[12]
Definition at line 104 of file dialog.h.
item_attr
#define item_attr attributes[19]
Definition at line 111 of file dialog.h.
item_selected_attr
#define item_selected_attr attributes[20]
Definition at line 112 of file dialog.h.
M_EVENT
#define M_EVENT (KEY_MAX+1)
Definition at line 177 of file dialog.h.
MAX
#define MAX (x, y) (x > y ? x : y)
Definition at line 56 of file dialog.h.
MAX_LEN
#define MAX_LEN 2048
Definition at line 53 of file dialog.h.
menubox_attr
#define menubox_attr attributes[17]
Definition at line 109 of file dialog.h.
menubox_border_attr
#define menubox_border_attr attributes[18]
Definition at line 110 of file dialog.h.
MIN
#define MIN (x, y) (x < y ? x : y)
Definition at line 55 of file dialog.h.
OLD_NCURSES
#define OLD_NCURSES 0
Definition at line 46 of file dialog.h.
position_indicator_attr
#define position_indicator_attr attributes[16]
Definition at line 108 of file dialog.h.
screen_attr
#define screen_attr attributes[0]
Definition at line 92 of file dialog.h.
searchbox_attr
#define searchbox_attr attributes[13]
Definition at line 105 of file dialog.h.
searchbox_border_attr
#define searchbox_border_attr attributes[15]
Definition at line 107 of file dialog.h.
searchbox_title_attr
#define searchbox_title_attr attributes[14]
Definition at line 106 of file dialog.h.
shadow_attr
#define shadow_attr attributes[1]
Definition at line 93 of file dialog.h.
TAB
#define TAB 9
Definition at line 52 of file dialog.h.
tag_attr
#define tag_attr attributes[21]
Definition at line 113 of file dialog.h.
tag_key_attr
#define tag_key_attr attributes[23]
Definition at line 115 of file dialog.h.
tag_key_selected_attr
#define tag_key_selected_attr attributes[24]
Definition at line 116 of file dialog.h.
tag_selected_attr
#define tag_selected_attr attributes[22]
Definition at line 114 of file dialog.h.
title_attr
#define title_attr attributes[3]
Definition at line 95 of file dialog.h.
TR
#define TR (params) _tracef params
Definition at line 49 of file dialog.h.
uarrow_attr
#define uarrow_attr attributes[27]
Definition at line 119 of file dialog.h.
Function Documentation
attr_clear()
void attr_clear (WINDOW * win, int height, int width, chtype attr)
Definition at line 107 of file util.c.
 {
     int i, j;
     wattrset(win, attr);
     for (i = 0; i < height; i++) {
         wmove(win, i, 0);
         for (j = 0; j < width; j++)
             waddch(win, ' ');
     }
     touchwin(win);
 }
References height(), i, j, and width.
Referenced by dialog_clear(), dialog_textbox(), and main().
color_setup()
void color_setup (void)
Definition at line 155 of file util.c.
 {
     int i;
     if (has_colors()) { /* Terminal supports color? */
         start_color();
         /* Initialize color pairs */
         for (i = 0; i < ATTRIBUTE_COUNT; i++)
             init_pair(i + 1, color_table[i][0], color_table[i][1]);
         /* Setup color attributes */
         for (i = 0; i < ATTRIBUTE_COUNT; i++)
             attributes[i] = C_ATTR(color_table[i][2], i + 1);
     }
 }
References ATTRIBUTE_COUNT, attributes, C_ATTR, color_table, and i.
Referenced by init_dialog().
create_rc()
void create_rc (const char * filename)
dialog_checklist()
int dialog_checklist (const char * title, const char * prompt, int height, int width, int list_height, int item_no, const char *const * items)
Definition at line 111 of file checklist.c.
 {
     int i, x, y, box_x, box_y;
     int key = 0, button = 0, choice = 0, scroll = 0, max_choice, *status;
     WINDOW *dialog, *list;
     /* Allocate space for storing item on/off status */
     if ((status = malloc(sizeof(int) * item_no)) == NULL) {
         endwin();
         fprintf(stderr,
             "\nCan't allocate memory in dialog_checklist().\n");
         exit(-1);
     }
     /* Initializes status */
     for (i = 0; i < item_no; i++) {
         status[i] = !strcasecmp(items[i * 3 + 2], "on");
         if ((!choice && status[i])
             || !strcasecmp(items[i * 3 + 2], "selected"))
             choice = i + 1;
     }
     if (choice)
         choice--;
     max_choice = MIN(list_height, item_no);
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     wattrset(dialog, border_attr);
     mvwaddch(dialog, height - 3, 0, ACS_LTEE);
     for (i = 0; i < width - 2; i++)
         waddch(dialog, ACS_HLINE);
     wattrset(dialog, dialog_attr);
     waddch(dialog, ACS_RTEE);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 3);
     list_width = width - 6;
     box_y = height - list_height - 5;
     box_x = (width - list_width) / 2 - 1;
     /* create new window for the list */
     list = subwin(dialog, list_height, list_width, y + box_y + 1,
                   x + box_x + 1);
     keypad(list, TRUE);
     /* draw a box around the list items */
     draw_box(dialog, box_y, box_x, list_height + 2, list_width + 2,
              menubox_border_attr, menubox_attr);
     /* Find length of longest item in order to center checklist */
     check_x = 0;
     for (i = 0; i < item_no; i++)
         check_x = MAX(check_x, +strlen(items[i * 3 + 1]) + 4);
     check_x = (list_width - check_x) / 2;
     item_x = check_x + 4;
     if (choice >= list_height) {
         scroll = choice - list_height + 1;
         choice -= scroll;
     }
     /* Print the list */
     for (i = 0; i < max_choice; i++) {
         print_item(list, items[(scroll + i) * 3 + 1],
                status[i + scroll], i, i == choice);
     }
     print_arrows(dialog, choice, item_no, scroll,
              box_y, box_x + check_x + 5, list_height);
     print_buttons(dialog, height, width, 0);
     wnoutrefresh(dialog);
     wnoutrefresh(list);
     doupdate();
     while (key != ESC) {
         key = wgetch(dialog);
         for (i = 0; i < max_choice; i++)
             if (toupper(key) ==
                 toupper(items[(scroll + i) * 3 + 1][0]))
                 break;
         if (i < max_choice || key == KEY_UP || key == KEY_DOWN ||
             key == '+' || key == '-') {
             if (key == KEY_UP || key == '-') {
                 if (!choice) {
                     if (!scroll)
                         continue;
                     /* Scroll list down */
                     if (list_height > 1) {
                         /* De-highlight current first item */
                         print_item(list, items[scroll * 3 + 1],
                                status[scroll], 0, FALSE);
                         scrollok(list, TRUE);
                         wscrl(list, -1);
                         scrollok(list, FALSE);
                     }
                     scroll--;
                     print_item(list, items[scroll * 3 + 1], status[scroll], 0, TRUE);
                     print_arrows(dialog, choice, item_no,
                              scroll, box_y, box_x + check_x + 5, list_height);
                     wnoutrefresh(dialog);
                     wrefresh(list);
                     continue;   /* wait for another key press */
                 } else
                     i = choice - 1;
             } else if (key == KEY_DOWN || key == '+') {
                 if (choice == max_choice - 1) {
                     if (scroll + choice >= item_no - 1)
                         continue;
                     /* Scroll list up */
                     if (list_height > 1) {
                         /* De-highlight current last item before scrolling up */
                         print_item(list, items[(scroll + max_choice - 1) * 3 + 1],
                                status[scroll + max_choice - 1],
                                max_choice - 1, FALSE);
                         scrollok(list, TRUE);
                         wscrl(list, 1);
                         scrollok(list, FALSE);
                     }
                     scroll++;
                     print_item(list, items[(scroll + max_choice - 1) * 3 + 1],
                            status[scroll + max_choice - 1], max_choice - 1, TRUE);
                     print_arrows(dialog, choice, item_no,
                              scroll, box_y, box_x + check_x + 5, list_height);
                     wnoutrefresh(dialog);
                     wrefresh(list);
                     continue;   /* wait for another key press */
                 } else
                     i = choice + 1;
             }
             if (i != choice) {
                 /* De-highlight current item */
                 print_item(list, items[(scroll + choice) * 3 + 1],
                        status[scroll + choice], choice, FALSE);
                 /* Highlight new item */
                 choice = i;
                 print_item(list, items[(scroll + choice) * 3 + 1],
                        status[scroll + choice], choice, TRUE);
                 wnoutrefresh(dialog);
                 wrefresh(list);
             }
             continue;   /* wait for another key press */
         }
         switch (key) {
         case 'H':
         case 'h':
         case '?':
             fprintf(stderr, "%s", items[(scroll + choice) * 3]);
             delwin(dialog);
             free(status);
             return 1;
         case TAB:
         case KEY_LEFT:
         case KEY_RIGHT:
             button = ((key == KEY_LEFT ? --button : ++button) < 0)
                 ? 1 : (button > 1 ? 0 : button);
             print_buttons(dialog, height, width, button);
             wrefresh(dialog);
             break;
         case 'S':
         case 's':
         case ' ':
         case '\n':
             if (!button) {
                 if (!status[scroll + choice]) {
                     for (i = 0; i < item_no; i++)
                         status[i] = 0;
                     status[scroll + choice] = 1;
                     for (i = 0; i < max_choice; i++)
                         print_item(list, items[(scroll + i) * 3 + 1],
                                status[scroll + i], i, i == choice);
                 }
                 wnoutrefresh(dialog);
                 wrefresh(list);
                 for (i = 0; i < item_no; i++)
                     if (status[i])
                         fprintf(stderr, "%s", items[i * 3]);
             } else
                 fprintf(stderr, "%s", items[(scroll + choice) * 3]);
             delwin(dialog);
             free(status);
             return button;
         case 'X':
         case 'x':
             key = ESC;
         case ESC:
             break;
         }
         /* Now, update everything... */
         doupdate();
     }
     delwin(dialog);
     free(status);
     return -1;      /* ESC pressed */
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, check_x, dialog_attr, draw_box(), draw_shadow(), ESC, exit(), FALSE, fprintf(), free, height(), i, item_x, items, list(), list_width, malloc, MAX, menubox_attr, menubox_border_attr, MIN, NULL, print_arrows(), print_autowrap(), print_buttons(), print_item(), print_title(), prompt, status, stderr, strcasecmp, strlen(), TAB, title, toupper, TRUE, width, x, and y.
Referenced by j_radiolist().
dialog_clear()
void dialog_clear (void)
Definition at line 120 of file util.c.
 {
     attr_clear(stdscr, LINES, COLS, screen_attr);
     /* Display background title if it exists ... - SLH */
     if (backtitle != NULL) {
         int i;
         wattrset(stdscr, screen_attr);
         mvwaddstr(stdscr, 0, 1, (char *)backtitle);
         wmove(stdscr, 1, 1);
         for (i = 1; i < COLS - 1; i++)
             waddch(stdscr, ACS_HLINE);
     }
     wnoutrefresh(stdscr);
 }
References ACS_HLINE, attr_clear(), backtitle, i, NULL, and screen_attr.
Referenced by init_dialog().
dialog_inputbox()
int dialog_inputbox (const char * title, const char * prompt, int height, int width, const char * init)
Definition at line 44 of file inputbox.c.
 {
     int i, x, y, box_y, box_x, box_width;
     int input_x = 0, scroll = 0, key = 0, button = -1;
     char *instr = dialog_input_result;
     WINDOW *dialog;
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     wattrset(dialog, border_attr);
     mvwaddch(dialog, height - 3, 0, ACS_LTEE);
     for (i = 0; i < width - 2; i++)
         waddch(dialog, ACS_HLINE);
     wattrset(dialog, dialog_attr);
     waddch(dialog, ACS_RTEE);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 3);
     /* Draw the input field box */
     box_width = width - 6;
     getyx(dialog, y, x);
     box_y = y + 2;
     box_x = (width - box_width) / 2;
     draw_box(dialog, y + 1, box_x - 1, 3, box_width + 2, border_attr, dialog_attr);
     print_buttons(dialog, height, width, 0);
     /* Set up the initial value */
     wmove(dialog, box_y, box_x);
     wattrset(dialog, inputbox_attr);
     if (!init)
         instr[0] = '\0';
     else
         strcpy(instr, init);
     input_x = strlen(instr);
     if (input_x >= box_width) {
         scroll = input_x - box_width + 1;
         input_x = box_width - 1;
         for (i = 0; i < box_width - 1; i++)
             waddch(dialog, instr[scroll + i]);
     } else {
         waddstr(dialog, instr);
     }
     wmove(dialog, box_y, box_x + input_x);
     wrefresh(dialog);
     while (key != ESC) {
         key = wgetch(dialog);
         if (button == -1) { /* Input box selected */
             switch (key) {
             case TAB:
             case KEY_UP:
             case KEY_DOWN:
                 break;
             case KEY_LEFT:
                 continue;
             case KEY_RIGHT:
                 continue;
             case KEY_BACKSPACE:
             case 127:
                 if (input_x || scroll) {
                     wattrset(dialog, inputbox_attr);
                     if (!input_x) {
                         scroll = scroll < box_width - 1 ? 0 : scroll - (box_width - 1);
                         wmove(dialog, box_y, box_x);
                         for (i = 0; i < box_width; i++)
                             waddch(dialog,
                                    instr[scroll + input_x + i] ?
                                    instr[scroll + input_x + i] : ' ');
                         input_x = strlen(instr) - scroll;
                     } else
                         input_x--;
                     instr[scroll + input_x] = '\0';
                     mvwaddch(dialog, box_y, input_x + box_x, ' ');
                     wmove(dialog, box_y, input_x + box_x);
                     wrefresh(dialog);
                 }
                 continue;
             default:
                 if (key < 0x100 && isprint(key)) {
                     if (scroll + input_x < MAX_LEN) {
                         wattrset(dialog, inputbox_attr);
                         instr[scroll + input_x] = key;
                         instr[scroll + input_x + 1] = '\0';
                         if (input_x == box_width - 1) {
                             scroll++;
                             wmove(dialog, box_y, box_x);
                             for (i = 0; i < box_width - 1; i++)
                                 waddch(dialog, instr [scroll + i]);
                         } else {
                             wmove(dialog, box_y, input_x++ + box_x);
                             waddch(dialog, key);
                         }
                         wrefresh(dialog);
                     } else
                         flash();    /* Alarm user about overflow */
                     continue;
                 }
             }
         }
         switch (key) {
         case 'O':
         case 'o':
             delwin(dialog);
             return 0;
         case 'H':
         case 'h':
             delwin(dialog);
             return 1;
         case KEY_UP:
         case KEY_LEFT:
             switch (button) {
             case -1:
                 button = 1; /* Indicates "Cancel" button is selected */
                 print_buttons(dialog, height, width, 1);
                 break;
             case 0:
                 button = -1;    /* Indicates input box is selected */
                 print_buttons(dialog, height, width, 0);
                 wmove(dialog, box_y, box_x + input_x);
                 wrefresh(dialog);
                 break;
             case 1:
                 button = 0; /* Indicates "OK" button is selected */
                 print_buttons(dialog, height, width, 0);
                 break;
             }
             break;
         case TAB:
         case KEY_DOWN:
         case KEY_RIGHT:
             switch (button) {
             case -1:
                 button = 0; /* Indicates "OK" button is selected */
                 print_buttons(dialog, height, width, 0);
                 break;
             case 0:
                 button = 1; /* Indicates "Cancel" button is selected */
                 print_buttons(dialog, height, width, 1);
                 break;
             case 1:
                 button = -1;    /* Indicates input box is selected */
                 print_buttons(dialog, height, width, 0);
                 wmove(dialog, box_y, box_x + input_x);
                 wrefresh(dialog);
                 break;
             }
             break;
         case ' ':
         case '\n':
             delwin(dialog);
             return (button == -1 ? 0 : button);
         case 'X':
         case 'x':
             key = ESC;
         case ESC:
             break;
         }
     }
     delwin(dialog);
     return -1;      /* ESC pressed */
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, dialog_attr, dialog_input_result, draw_box(), draw_shadow(), ESC, flash(), height(), i, init, inputbox_attr, isprint, KEY_BACKSPACE, MAX_LEN, print_autowrap(), print_buttons(), print_title(), prompt, strcpy(), strlen(), TAB, title, TRUE, width, x, and y.
Referenced by j_inputbox().
dialog_menu()
int dialog_menu (const char * title, const char * prompt, int height, int width, int menu_height, const char * choice, int item_no, const char *const * items)
Definition at line 181 of file menubox.c.
 {
     int i, j, x, y, box_x, box_y;
     int key = 0, button = 0, scroll = 0, choice = 0;
     int first_item =  0, max_choice;
     WINDOW *dialog, *menu;
     FILE *f;
     max_choice = MIN(menu_height, item_no);
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     wattrset(dialog, border_attr);
     mvwaddch(dialog, height - 3, 0, ACS_LTEE);
     for (i = 0; i < width - 2; i++)
         waddch(dialog, ACS_HLINE);
     wattrset(dialog, dialog_attr);
     wbkgdset(dialog, dialog_attr & A_COLOR);
     waddch(dialog, ACS_RTEE);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 3);
     menu_width = width - 6;
     box_y = height - menu_height - 5;
     box_x = (width - menu_width) / 2 - 1;
     /* create new window for the menu */
     menu = subwin(dialog, menu_height, menu_width,
               y + box_y + 1, x + box_x + 1);
     keypad(menu, TRUE);
     /* draw a box around the menu items */
     draw_box(dialog, box_y, box_x, menu_height + 2, menu_width + 2,
          menubox_border_attr, menubox_attr);
     item_x = (menu_width - 70) / 2;
     /* Set choice to default item */
     for (i = 0; i < item_no; i++)
         if (strcmp(current, items[i * 2]) == 0)
             choice = i;
     /* get the scroll info from the temp file */
     if ((f = fopen("lxdialog.scrltmp", "r")) != NULL) {
         if ((fscanf(f, "%d\n", &scroll) == 1) && (scroll <= choice) &&
             (scroll + max_choice > choice) && (scroll >= 0) &&
             (scroll + max_choice <= item_no)) {
             first_item = scroll;
             choice = choice - scroll;
             fclose(f);
         } else {
             scroll = 0;
             remove("lxdialog.scrltmp");
             fclose(f);
             f = NULL;
         }
     }
     if ((choice >= max_choice) || (f == NULL && choice >= max_choice / 2)) {
         if (choice >= item_no - max_choice / 2)
             scroll = first_item = item_no - max_choice;
         else
             scroll = first_item = choice - max_choice / 2;
         choice = choice - scroll;
     }
     /* Print the menu */
     for (i = 0; i < max_choice; i++) {
         print_item(first_item + i, i, i == choice);
     }
     wnoutrefresh(menu);
     print_arrows(dialog, item_no, scroll,
              box_y, box_x + item_x + 1, menu_height);
     print_buttons(dialog, height, width, 0);
     wmove(menu, choice, item_x + 1);
     wrefresh(menu);
     while (key != ESC) {
         key = wgetch(menu);
         if (key < 256 && isalpha(key))
             key = tolower(key);
         if (strchr("ynmh", key))
             i = max_choice;
         else {
             for (i = choice + 1; i < max_choice; i++) {
                 j = first_alpha(items[(scroll + i) * 2 + 1], "YyNnMmHh");
                 if (key == tolower(items[(scroll + i) * 2 + 1][j]))
                     break;
             }
             if (i == max_choice)
                 for (i = 0; i < max_choice; i++) {
                     j = first_alpha(items [(scroll + i) * 2 + 1], "YyNnMmHh");
                     if (key == tolower(items[(scroll + i) * 2 + 1][j]))
                         break;
                 }
         }
         if (i < max_choice ||
             key == KEY_UP || key == KEY_DOWN ||
             key == '-' || key == '+' ||
             key == KEY_PPAGE || key == KEY_NPAGE) {
             /* Remove highligt of current item */
             print_item(scroll + choice, choice, FALSE);
             if (key == KEY_UP || key == '-') {
                 if (choice < 2 && scroll) {
                     /* Scroll menu down */
                     do_scroll(menu, &scroll, -1);
                     print_item(scroll, 0, FALSE);
                 } else
                     choice = MAX(choice - 1, 0);
             } else if (key == KEY_DOWN || key == '+') {
                 print_item(scroll+choice, choice, FALSE);
                 if ((choice > max_choice - 3) &&
                     (scroll + max_choice < item_no)) {
                     /* Scroll menu up */
                     do_scroll(menu, &scroll, 1);
                     print_item(scroll+max_choice - 1,
                            max_choice - 1, FALSE);
                 } else
                     choice = MIN(choice + 1, max_choice - 1);
             } else if (key == KEY_PPAGE) {
                 scrollok(menu, TRUE);
                 for (i = 0; (i < max_choice); i++) {
                     if (scroll > 0) {
                         do_scroll(menu, &scroll, -1);
                         print_item(scroll, 0, FALSE);
                     } else {
                         if (choice > 0)
                             choice--;
                     }
                 }
             } else if (key == KEY_NPAGE) {
                 for (i = 0; (i < max_choice); i++) {
                     if (scroll + max_choice < item_no) {
                         do_scroll(menu, &scroll, 1);
                         print_item(scroll+max_choice-1,
                                max_choice - 1, FALSE);
                     } else {
                         if (choice + 1 < max_choice)
                             choice++;
                     }
                 }
             } else
                 choice = i;
             print_item(scroll + choice, choice, TRUE);
             print_arrows(dialog, item_no, scroll,
                      box_y, box_x + item_x + 1, menu_height);
             wnoutrefresh(dialog);
             wrefresh(menu);
             continue;   /* wait for another key press */
         }
         switch (key) {
         case KEY_LEFT:
         case TAB:
         case KEY_RIGHT:
             button = ((key == KEY_LEFT ? --button : ++button) < 0)
                 ? 2 : (button > 2 ? 0 : button);
             print_buttons(dialog, height, width, button);
             wrefresh(menu);
             break;
         case ' ':
         case 's':
         case 'y':
         case 'n':
         case 'm':
         case '/':
             /* save scroll info */
             if ((f = fopen("lxdialog.scrltmp", "w")) != NULL) {
                 fprintf(f, "%d\n", scroll);
                 fclose(f);
             }
             delwin(dialog);
             fprintf(stderr, "%s\n", items[(scroll + choice) * 2]);
             switch (key) {
             case 's':
                 return 3;
             case 'y':
                 return 3;
             case 'n':
                 return 4;
             case 'm':
                 return 5;
             case ' ':
                 return 6;
             case '/':
                 return 7;
             }
             return 0;
         case 'h':
         case '?':
             button = 2;
         case '\n':
             delwin(dialog);
             if (button == 2)
                 fprintf(stderr, "%s \"%s\"\n",
                     items[(scroll + choice) * 2],
                     items[(scroll + choice) * 2 + 1] +
                     first_alpha(items [(scroll + choice) * 2 + 1], ""));
             else
                 fprintf(stderr, "%s\n",
                     items[(scroll + choice) * 2]);
             remove("lxdialog.scrltmp");
             return button;
         case 'e':
         case 'x':
             key = ESC;
         case ESC:
             break;
         }
     }
     delwin(dialog);
     remove("lxdialog.scrltmp");
     return -1;      /* ESC pressed */
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, current, dialog_attr, do_scroll(), draw_box(), draw_shadow(), ESC, f, FALSE, fclose(), first_alpha(), fopen(), fprintf(), fscanf(), height(), i, isalpha, item_x, items, j, MAX, menu_width, menubox_attr, menubox_border_attr, MIN, NULL, print_arrows(), print_autowrap(), print_buttons(), print_item, print_title(), prompt, remove(), stderr, strchr(), strcmp, TAB, title, tolower, TRUE, width, x, and y.
Referenced by j_menu().
dialog_msgbox()
int dialog_msgbox (const char * title, const char * prompt, int height, int width, int pause)
Definition at line 28 of file msgbox.c.
 {
     int i, x, y, key = 0;
     WINDOW *dialog;
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 2);
     if (pause) {
         wattrset(dialog, border_attr);
         mvwaddch(dialog, height - 3, 0, ACS_LTEE);
         for (i = 0; i < width - 2; i++)
             waddch(dialog, ACS_HLINE);
         wattrset(dialog, dialog_attr);
         waddch(dialog, ACS_RTEE);
         print_button(dialog, "  Ok  ", height - 2, width / 2 - 4, TRUE);
         wrefresh(dialog);
         while (key != ESC && key != '\n' && key != ' ' &&
                key != 'O' && key != 'o' && key != 'X' && key != 'x')
             key = wgetch(dialog);
     } else {
         key = '\n';
         wrefresh(dialog);
     }
     delwin(dialog);
     return key == ESC ? -1 : 0;
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, dialog_attr, draw_box(), draw_shadow(), ESC, height(), i, pause(), print_autowrap(), print_button(), print_title(), prompt, title, TRUE, width, x, and y.
Referenced by j_infobox(), and j_msgbox().
dialog_textbox()
int dialog_textbox (const char * title, const char * file, int height, int width)
Definition at line 37 of file textbox.c.
 {
     int i, x, y, cur_x, cur_y, fpos, key = 0;
     int passed_end;
     WINDOW *dialog, *text;
     /* Open input file for reading */
     if ((fd = open(file, O_RDONLY)) == -1) {
         endwin();
         fprintf(stderr, "\nCan't open input file in dialog_textbox().\n");
         exit(-1);
     }
     /* Get file size. Actually, 'file_size' is the real file size - 1,
        since it's only the last byte offset from the beginning */
     if ((file_size = lseek(fd, 0, SEEK_END)) == -1) {
         endwin();
         fprintf(stderr, "\nError getting file size in dialog_textbox().\n");
         exit(-1);
     }
     /* Restore file pointer to beginning of file after getting file size */
     if (lseek(fd, 0, SEEK_SET) == -1) {
         endwin();
         fprintf(stderr, "\nError moving file pointer in dialog_textbox().\n");
         exit(-1);
     }
     /* Allocate space for read buffer */
     if ((buf = malloc(BUF_SIZE + 1)) == NULL) {
         endwin();
         fprintf(stderr, "\nCan't allocate memory in dialog_textbox().\n");
         exit(-1);
     }
     if ((bytes_read = read(fd, buf, BUF_SIZE)) == -1) {
         endwin();
         fprintf(stderr, "\nError reading file in dialog_textbox().\n");
         exit(-1);
     }
     buf[bytes_read] = '\0'; /* mark end of valid data */
     page = buf;     /* page is pointer to start of page to be displayed */
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     /* Create window for text region, used for scrolling text */
     text = subwin(dialog, height - 4, width - 2, y + 1, x + 1);
     wattrset(text, dialog_attr);
     wbkgdset(text, dialog_attr & A_COLOR);
     keypad(text, TRUE);
     /* register the new window, along with its borders */
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     wattrset(dialog, border_attr);
     mvwaddch(dialog, height - 3, 0, ACS_LTEE);
     for (i = 0; i < width - 2; i++)
         waddch(dialog, ACS_HLINE);
     wattrset(dialog, dialog_attr);
     wbkgdset(dialog, dialog_attr & A_COLOR);
     waddch(dialog, ACS_RTEE);
     print_title(dialog, title, width);
     print_button(dialog, " Exit ", height - 2, width / 2 - 4, TRUE);
     wnoutrefresh(dialog);
     getyx(dialog, cur_y, cur_x);    /* Save cursor position */
     /* Print first page of text */
     attr_clear(text, height - 4, width - 2, dialog_attr);
     print_page(text, height - 4, width - 2);
     print_position(dialog, height, width);
     wmove(dialog, cur_y, cur_x);    /* Restore cursor position */
     wrefresh(dialog);
     while ((key != ESC) && (key != '\n')) {
         key = wgetch(dialog);
         switch (key) {
         case 'E':   /* Exit */
         case 'e':
         case 'X':
         case 'x':
             delwin(dialog);
             free(buf);
             close(fd);
             return 0;
         case 'g':   /* First page */
         case KEY_HOME:
             if (!begin_reached) {
                 begin_reached = 1;
                 /* First page not in buffer? */
                 if ((fpos = lseek(fd, 0, SEEK_CUR)) == -1) {
                     endwin();
                     fprintf(stderr, "\nError moving file pointer in dialog_textbox().\n");
                     exit(-1);
                 }
                 if (fpos > bytes_read) {    /* Yes, we have to read it in */
                     if (lseek(fd, 0, SEEK_SET) == -1) {
                         endwin();
                         fprintf(stderr, "\nError moving file pointer in "
                                     "dialog_textbox().\n");
                         exit(-1);
                     }
                     if ((bytes_read =
                          read(fd, buf, BUF_SIZE)) == -1) {
                         endwin();
                         fprintf(stderr, "\nError reading file in dialog_textbox().\n");
                         exit(-1);
                     }
                     buf[bytes_read] = '\0';
                 }
                 page = buf;
                 print_page(text, height - 4, width - 2);
                 print_position(dialog, height, width);
                 wmove(dialog, cur_y, cur_x);    /* Restore cursor position */
                 wrefresh(dialog);
             }
             break;
         case 'G':   /* Last page */
         case KEY_END:
             end_reached = 1;
             /* Last page not in buffer? */
             if ((fpos = lseek(fd, 0, SEEK_CUR)) == -1) {
                 endwin();
                 fprintf(stderr, "\nError moving file pointer in dialog_textbox().\n");
                 exit(-1);
             }
             if (fpos < file_size) { /* Yes, we have to read it in */
                 if (lseek(fd, -BUF_SIZE, SEEK_END) == -1) {
                     endwin();
                     fprintf(stderr, "\nError moving file pointer in dialog_textbox().\n");
                     exit(-1);
                 }
                 if ((bytes_read =
                      read(fd, buf, BUF_SIZE)) == -1) {
                     endwin();
                     fprintf(stderr, "\nError reading file in dialog_textbox().\n");
                     exit(-1);
                 }
                 buf[bytes_read] = '\0';
             }
             page = buf + bytes_read;
             back_lines(height - 4);
             print_page(text, height - 4, width - 2);
             print_position(dialog, height, width);
             wmove(dialog, cur_y, cur_x);    /* Restore cursor position */
             wrefresh(dialog);
             break;
         case 'K':   /* Previous line */
         case 'k':
         case KEY_UP:
             if (!begin_reached) {
                 back_lines(page_length + 1);
                 /* We don't call print_page() here but use scrolling to ensure
                    faster screen update. However, 'end_reached' and
                    'page_length' should still be updated, and 'page' should
                    point to start of next page. This is done by calling
                    get_line() in the following 'for' loop. */
                 scrollok(text, TRUE);
                 wscrl(text, -1);    /* Scroll text region down one line */
                 scrollok(text, FALSE);
                 page_length = 0;
                 passed_end = 0;
                 for (i = 0; i < height - 4; i++) {
                     if (!i) {
                         /* print first line of page */
                         print_line(text, 0, width - 2);
                         wnoutrefresh(text);
                     } else
                         /* Called to update 'end_reached' and 'page' */
                         get_line();
                     if (!passed_end)
                         page_length++;
                     if (end_reached && !passed_end)
                         passed_end = 1;
                 }
                 print_position(dialog, height, width);
                 wmove(dialog, cur_y, cur_x);    /* Restore cursor position */
                 wrefresh(dialog);
             }
             break;
         case 'B':   /* Previous page */
         case 'b':
         case KEY_PPAGE:
             if (begin_reached)
                 break;
             back_lines(page_length + height - 4);
             print_page(text, height - 4, width - 2);
             print_position(dialog, height, width);
             wmove(dialog, cur_y, cur_x);
             wrefresh(dialog);
             break;
         case 'J':   /* Next line */
         case 'j':
         case KEY_DOWN:
             if (!end_reached) {
                 begin_reached = 0;
                 scrollok(text, TRUE);
                 scroll(text);   /* Scroll text region up one line */
                 scrollok(text, FALSE);
                 print_line(text, height - 5, width - 2);
                 wnoutrefresh(text);
                 print_position(dialog, height, width);
                 wmove(dialog, cur_y, cur_x);    /* Restore cursor position */
                 wrefresh(dialog);
             }
             break;
         case KEY_NPAGE: /* Next page */
         case ' ':
             if (end_reached)
                 break;
             begin_reached = 0;
             print_page(text, height - 4, width - 2);
             print_position(dialog, height, width);
             wmove(dialog, cur_y, cur_x);
             wrefresh(dialog);
             break;
         case '0':   /* Beginning of line */
         case 'H':   /* Scroll left */
         case 'h':
         case KEY_LEFT:
             if (hscroll <= 0)
                 break;
             if (key == '0')
                 hscroll = 0;
             else
                 hscroll--;
             /* Reprint current page to scroll horizontally */
             back_lines(page_length);
             print_page(text, height - 4, width - 2);
             wmove(dialog, cur_y, cur_x);
             wrefresh(dialog);
             break;
         case 'L':   /* Scroll right */
         case 'l':
         case KEY_RIGHT:
             if (hscroll >= MAX_LEN)
                 break;
             hscroll++;
             /* Reprint current page to scroll horizontally */
             back_lines(page_length);
             print_page(text, height - 4, width - 2);
             wmove(dialog, cur_y, cur_x);
             wrefresh(dialog);
             break;
         case ESC:
             break;
         }
     }
     delwin(dialog);
     free(buf);
     close(fd);
     return -1;      /* ESC pressed */
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, attr_clear(), back_lines(), begin_reached, border_attr, buf, BUF_SIZE, bytes_read, close(), dialog_attr, draw_box(), draw_shadow(), end_reached, ESC, exit(), FALSE, fd, file_size, fprintf(), free, get_line(), height(), hscroll, i, KEY_END, KEY_HOME, lseek(), malloc, MAX_LEN, NULL, O_RDONLY, open(), page, page_length, print_button(), print_line(), print_page(), print_position(), print_title(), read(), SEEK_CUR, SEEK_END, SEEK_SET, stderr, text, title, TRUE, width, x, and y.
Referenced by j_textbox().
dialog_yesno()
int dialog_yesno (const char * title, const char * prompt, int height, int width)
Definition at line 42 of file yesno.c.
 {
     int i, x, y, key = 0, button = 0;
     WINDOW *dialog;
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     wattrset(dialog, border_attr);
     mvwaddch(dialog, height - 3, 0, ACS_LTEE);
     for (i = 0; i < width - 2; i++)
         waddch(dialog, ACS_HLINE);
     wattrset(dialog, dialog_attr);
     waddch(dialog, ACS_RTEE);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 3);
     print_buttons(dialog, height, width, 0);
     while (key != ESC) {
         key = wgetch(dialog);
         switch (key) {
         case 'Y':
         case 'y':
             delwin(dialog);
             return 0;
         case 'N':
         case 'n':
             delwin(dialog);
             return 1;
         case TAB:
         case KEY_LEFT:
         case KEY_RIGHT:
             button = ((key == KEY_LEFT ? --button : ++button) < 0) ? 1 : (button > 1 ? 0 : button);
             print_buttons(dialog, height, width, button);
             wrefresh(dialog);
             break;
         case ' ':
         case '\n':
             delwin(dialog);
             return button;
         case ESC:
             break;
         }
     }
     delwin(dialog);
     return -1;      /* ESC pressed */
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, dialog_attr, draw_box(), draw_shadow(), ESC, height(), i, print_autowrap(), print_buttons(), print_title(), prompt, TAB, title, TRUE, width, x, and y.
Referenced by j_yesno().
draw_box()
void draw_box (WINDOW * win, int y, int x, int height, int width, chtype box, chtype border)
Definition at line 290 of file util.c.
 {
     int i, j;
     wattrset(win, 0);
     for (i = 0; i < height; i++) {
         wmove(win, y + i, x);
         for (j = 0; j < width; j++)
             if (!i && !j)
                 waddch(win, border | ACS_ULCORNER);
             else if (i == height - 1 && !j)
                 waddch(win, border | ACS_LLCORNER);
             else if (!i && j == width - 1)
                 waddch(win, box | ACS_URCORNER);
             else if (i == height - 1 && j == width - 1)
                 waddch(win, box | ACS_LRCORNER);
             else if (!i)
                 waddch(win, border | ACS_HLINE);
             else if (i == height - 1)
                 waddch(win, box | ACS_HLINE);
             else if (!j)
                 waddch(win, border | ACS_VLINE);
             else if (j == width - 1)
                 waddch(win, box | ACS_VLINE);
             else
                 waddch(win, box | ' ');
     }
 }
References ACS_HLINE, ACS_LLCORNER, ACS_LRCORNER, ACS_ULCORNER, ACS_URCORNER, ACS_VLINE, height(), i, j, width, x, and y.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), and dialog_yesno().
draw_shadow()
void draw_shadow (WINDOW * win, int y, int x, int height, int width)
Definition at line 324 of file util.c.
 {
     int i;
     if (has_colors()) { /* Whether terminal supports color? */
         wattrset(win, shadow_attr);
         wmove(win, y + height, x + 2);
         for (i = 0; i < width; i++)
             waddch(win, winch(win) & A_CHARTEXT);
         for (i = y + 1; i < y + height + 1; i++) {
             wmove(win, i, x + width);
             waddch(win, winch(win) & A_CHARTEXT);
             waddch(win, winch(win) & A_CHARTEXT);
         }
         wnoutrefresh(win);
     }
 }
References height(), i, shadow_attr, width, x, and y.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), and dialog_yesno().
end_dialog()
void end_dialog (void)
Definition at line 175 of file util.c.
 {
     endwin();
 }
Referenced by main().
first_alpha()
int first_alpha (const char * string, const char * exempt)
Definition at line 345 of file util.c.
 {
     int i, in_paren = 0, c;
     for (i = 0; i < strlen(string); i++) {
         c = tolower(string[i]);
         if (strchr("<[(", c))
             ++in_paren;
         if (strchr(">])", c) && in_paren > 0)
             --in_paren;
         if ((!in_paren) && isalpha(c) && strchr(exempt, c) == 0)
             return i;
     }
     return 0;
 }
References c, i, isalpha, strchr(), strlen(), and tolower.
Referenced by dialog_menu(), and do_print_item().
init_dialog()
void init_dialog (void)
Definition at line 139 of file util.c.
 {
     initscr();      /* Init curses */
     keypad(stdscr, TRUE);
     cbreak();
     noecho();
     if (use_colors)     /* Set up colors */
         color_setup();
     dialog_clear();
 }
References color_setup(), dialog_clear(), TRUE, and use_colors.
Referenced by main().
parse_rc()
int parse_rc (void)
print_autowrap()
void print_autowrap (WINDOW * win, const char * prompt, int width, int y, int x)
Definition at line 200 of file util.c.
 {
     int newl, cur_x, cur_y;
     int i, prompt_len, room, wlen;
     char tempstr[MAX_LEN + 1], *word, *sp, *sp2;
     strcpy(tempstr, prompt);
     prompt_len = strlen(tempstr);
     /*
      * Remove newlines
      */
     for (i = 0; i < prompt_len; i++) {
         if (tempstr[i] == '\n')
             tempstr[i] = ' ';
     }
     if (prompt_len <= width - x * 2) {  /* If prompt is short */
         wmove(win, y, (width - prompt_len) / 2);
         waddstr(win, tempstr);
     } else {
         cur_x = x;
         cur_y = y;
         newl = 1;
         word = tempstr;
         while (word && *word) {
             sp = strchr(word, ' ');
             if (sp)
                 *sp++ = 0;
             /* Wrap to next line if either the word does not fit,
                or it is the first word of a new sentence, and it is
                short, and the next word does not fit. */
             room = width - cur_x;
             wlen = strlen(word);
             if (wlen > room ||
                 (newl && wlen < 4 && sp
                  && wlen + 1 + strlen(sp) > room
                  && (!(sp2 = strchr(sp, ' '))
                  || wlen + 1 + (sp2 - sp) > room))) {
                 cur_y++;
                 cur_x = x;
             }
             wmove(win, cur_y, cur_x);
             waddstr(win, word);
             getyx(win, cur_y, cur_x);
             cur_x++;
             if (sp && *sp == ' ') {
                 cur_x++;    /* double space */
                 while (*++sp == ' ') ;
                 newl = 1;
             } else
                 newl = 0;
             word = sp;
         }
     }
 }
References i, MAX_LEN, prompt, sp, strchr(), strcpy(), strlen(), width, x, and y.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), and dialog_yesno().
print_button()
void print_button (WINDOW * win, const char * label, int y, int x, int selected)
Definition at line 262 of file util.c.
 {
     int i, temp;
     wmove(win, y, x);
     wattrset(win, selected ? button_active_attr : button_inactive_attr);
     waddstr(win, "<");
     temp = strspn(label, " ");
     label += temp;
     wattrset(win, selected ? button_label_active_attr
          : button_label_inactive_attr);
     for (i = 0; i < temp; i++)
         waddch(win, ' ');
     wattrset(win, selected ? button_key_active_attr
          : button_key_inactive_attr);
     waddch(win, label[0]);
     wattrset(win, selected ? button_label_active_attr
          : button_label_inactive_attr);
     waddstr(win, (char *)label + 1);
     wattrset(win, selected ? button_active_attr : button_inactive_attr);
     waddstr(win, ">");
     wmove(win, y, x + temp + 1);
 }
References button_active_attr, button_inactive_attr, button_key_active_attr, button_key_inactive_attr, button_label_active_attr, button_label_inactive_attr, i, label, strspn(), x, and y.
Referenced by dialog_msgbox(), dialog_textbox(), and print_buttons().
print_title()
void print_title (WINDOW * dialog, const char * title, int width)
Definition at line 183 of file util.c.
 {
     if (title) {
         int tlen = MIN(width - 2, strlen(title));
         wattrset(dialog, title_attr);
         mvwaddch(dialog, 0, (width - tlen) / 2 - 1, ' ');
         mvwaddnstr(dialog, 0, (width - tlen)/2, title, tlen);
         waddch(dialog, ' ');
     }
 }
References MIN, strlen(), title, title_attr, and width.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), and dialog_yesno().
Variable Documentation
attributes
chtype attributes[] extern
Definition at line 32 of file util.c.
Referenced by checkjobs(), color_setup(), and mk_env_string().
backtitle
const char* backtitle extern
Definition at line 27 of file util.c.
Referenced by dialog_clear(), and main().
dialog_input_result
char dialog_input_result[] extern
Definition at line 24 of file inputbox.c.
Referenced by dialog_inputbox(), and j_inputbox().
use_colors
bool use_colors extern
Definition at line 25 of file util.c.
Referenced by init_dialog().
use_shadow
bool use_shadow extern