Fennix: Userspace/apps/base/busybox/networking/arp.c File Reference
arp.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "inet_common.h"
#include <arpa/inet.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <netinet/ether.h>
#include <netpacket/packet.h>
Data Structures
struct globals
Macros
#define DEBUG 0
#define DFLT_AF "inet"
#define DFLT_HW "ether"
#define G (*(struct globals*)bb_common_bufsiz1)
#define ap (G.ap)
#define hw (G.hw)
#define device (G.device)
#define hw_set (G.hw_set)
#define INIT_G()
Enumerations
enum {
ARP_OPT_A = (1 << 0) , ARP_OPT_p = (1 << 1) , ARP_OPT_H = (1 << 2) , ARP_OPT_t = (1 << 3) ,
ARP_OPT_i = (1 << 4) , ARP_OPT_a = (1 << 5) , ARP_OPT_d = (1 << 6) , ARP_OPT_n = (1 << 7) ,
ARP_OPT_D = (1 << 8) , ARP_OPT_s = (1 << 9) , ARP_OPT_v = (1 << 10) * DEBUG
}
enum { sockfd = 3 }
Functions
static int arp_del (char **args)
static void arp_getdevhw (char *ifname, struct sockaddr *sa)
static int arp_set (char **args)
static void arp_disp (const char *name, char *ip, int type, int arp_flags, char *hwa, char *mask, char *dev)
static int arp_show (char *name)
int arp_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
static const char options[] ALIGN1
Macro Definition Documentation
ap
#define ap (G.ap)
Definition at line 83 of file arp.c.
DEBUG
#define DEBUG 0
Definition at line 53 of file arp.c.
device
#define device (G.device)
Definition at line 85 of file arp.c.
DFLT_AF
#define DFLT_AF "inet"
Definition at line 55 of file arp.c.
DFLT_HW
#define DFLT_HW "ether"
Definition at line 56 of file arp.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 82 of file arp.c.
hw
#define hw (G.hw)
Definition at line 84 of file arp.c.
hw_set
#define hw_set (G.hw_set)
Definition at line 86 of file arp.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    device = ""; \
} while (0)
Definition at line 87 of file arp.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARP_OPT_A
ARP_OPT_p
ARP_OPT_H
ARP_OPT_t
ARP_OPT_i
ARP_OPT_a
ARP_OPT_d
ARP_OPT_n
ARP_OPT_D
ARP_OPT_s
ARP_OPT_v
Definition at line 58 of file arp.c.
      {
     ARP_OPT_A = (1 << 0),
     ARP_OPT_p = (1 << 1),
     ARP_OPT_H = (1 << 2),
     ARP_OPT_t = (1 << 3),
     ARP_OPT_i = (1 << 4),
     ARP_OPT_a = (1 << 5),
     ARP_OPT_d = (1 << 6),
     ARP_OPT_n = (1 << 7), /* do not resolve addresses */
     ARP_OPT_D = (1 << 8), /* HW-address is devicename */
     ARP_OPT_s = (1 << 9),
     ARP_OPT_v = (1 << 10) * DEBUG, /* debugging output flag */
 };
anonymous enum
anonymous enum
Enumerator
sockfd
Definition at line 72 of file arp.c.
      {
     sockfd = 3, /* active socket descriptor */
 };
Function Documentation
arp_del()
static int arp_del (char ** args) static
Definition at line 105 of file arp.c.
 {
     char *host;
     struct arpreq req;
     struct sockaddr sa;
     int flags = 0;
     int err;
     memset(&req, 0, sizeof(req));
     /* Resolve the host name. */
     host = *args;
     if (ap->input(host, &sa) < 0) {
         bb_simple_herror_msg_and_die(host);
     }
     /* If a host has more than one address, use the correct one! */
     memcpy(&req.arp_pa, &sa, sizeof(struct sockaddr));
     if (hw_set)
         req.arp_ha.sa_family = hw->type;
     req.arp_flags = ATF_PERM;
     args++;
     while (*args != NULL) {
         switch (index_in_strings(options, *args)) {
         case 0: /* "pub" */
             flags |= 1;
             args++;
             break;
         case 1: /* "priv" */
             flags |= 2;
             args++;
             break;
         case 2: /* "temp" */
             req.arp_flags &= ~ATF_PERM;
             args++;
             break;
         case 3: /* "trail" */
             req.arp_flags |= ATF_USETRAILERS;
             args++;
             break;
         case 4: /* "dontpub" */
 #ifdef HAVE_ATF_DONTPUB
             req.arp_flags |= ATF_DONTPUB;
 #else
             bb_simple_error_msg("feature ATF_DONTPUB is not supported");
 #endif
             args++;
             break;
         case 5: /* "auto" */
 #ifdef HAVE_ATF_MAGIC
             req.arp_flags |= ATF_MAGIC;
 #else
             bb_simple_error_msg("feature ATF_MAGIC is not supported");
 #endif
             args++;
             break;
         case 6: /* "dev" */
             if (*++args == NULL)
                 bb_show_usage();
             device = *args;
             args++;
             break;
         case 7: /* "netmask" */
             if (*++args == NULL)
                 bb_show_usage();
             if (strcmp(*args, "255.255.255.255") != 0) {
                 host = *args;
                 if (ap->input(host, &sa) < 0) {
                     bb_simple_herror_msg_and_die(host);
                 }
                 memcpy(&req.arp_netmask, &sa, sizeof(struct sockaddr));
                 req.arp_flags |= ATF_NETMASK;
             }
             args++;
             break;
         default:
             bb_show_usage();
             break;
         }
     }
     if (flags == 0)
         flags = 3;
     strncpy_IFNAMSIZ(req.arp_dev, device);
     err = -1;
     /* Call the kernel. */
     if (flags & 2) {
         if (option_mask32 & ARP_OPT_v)
             bb_simple_error_msg("SIOCDARP(nopub)");
         err = ioctl(sockfd, SIOCDARP, &req);
         if (err < 0) {
             if (errno == ENXIO) {
                 if (flags & 1)
                     goto nopub;
                 printf("No ARP entry for %s\n", host);
                 return -1;
             }
             bb_simple_perror_msg_and_die("SIOCDARP(priv)");
         }
     }
     if ((flags & 1) && err) {
  nopub:
         req.arp_flags |= ATF_PUBL;
         if (option_mask32 & ARP_OPT_v)
             bb_simple_error_msg("SIOCDARP(pub)");
         if (ioctl(sockfd, SIOCDARP, &req) < 0) {
             if (errno == ENXIO) {
                 printf("No ARP entry for %s\n", host);
                 return -1;
             }
             bb_simple_perror_msg_and_die("SIOCDARP(pub)");
         }
     }
     return 0;
 }
References ap, args, arpreq::arp_dev, arpreq::arp_flags, arpreq::arp_ha, arpreq::arp_netmask, ARP_OPT_v, arpreq::arp_pa, ATF_DONTPUB, ATF_MAGIC, ATF_NETMASK, ATF_PERM, ATF_PUBL, ATF_USETRAILERS, bb_show_usage(), bb_simple_error_msg(), bb_simple_herror_msg_and_die(), bb_simple_perror_msg_and_die(), device, ENXIO, err(), errno, flags, hw, hw_set, index_in_strings(), ioctl(), memcpy, memset, NULL, option_mask32, printf, sockaddr::sa_family, SIOCDARP, sockfd, strcmp, and strncpy_IFNAMSIZ().
Referenced by arp_main().
arp_disp()
static void arp_disp (const char * name, char * ip, int type, int arp_flags, char * hwa, char * mask, char * dev) static
Definition at line 356 of file arp.c.
 {
     static const int arp_masks[] = {
         ATF_PERM, ATF_PUBL,
 #ifdef HAVE_ATF_MAGIC
         ATF_MAGIC,
 #endif
 #ifdef HAVE_ATF_DONTPUB
         ATF_DONTPUB,
 #endif
         ATF_USETRAILERS,
     };
     static const char arp_labels[] ALIGN1 = "PERM\0""PUP\0"
 #ifdef HAVE_ATF_MAGIC
         "AUTO\0"
 #endif
 #ifdef HAVE_ATF_DONTPUB
         "DONTPUB\0"
 #endif
         "TRAIL\0"
     ;
     const struct hwtype *xhw;
     xhw = get_hwntype(type);
     if (xhw == NULL)
         xhw = get_hwtype(DFLT_HW);
     printf("%s (%s) at ", name, ip);
     if (!(arp_flags & ATF_COM)) {
         if (arp_flags & ATF_PUBL)
             printf("* ");
         else
             printf("<incomplete> ");
     } else {
         printf("%s [%s] ", hwa, xhw->name);
     }
     if (arp_flags & ATF_NETMASK)
         printf("netmask %s ", mask);
     print_flags_separated(arp_masks, arp_labels, arp_flags, " ");
     printf(" on %s\n", dev);
 }
References ALIGN1, ATF_COM, ATF_DONTPUB, ATF_MAGIC, ATF_NETMASK, ATF_PERM, ATF_PUBL, ATF_USETRAILERS, DFLT_HW, get_hwntype(), get_hwtype(), hwtype::name, NULL, print_flags_separated(), printf, and type.
Referenced by arp_show().
arp_getdevhw()
static void arp_getdevhw (char * ifname, struct sockaddr * sa) static
Definition at line 226 of file arp.c.
 {
     struct ifreq ifr;
     const struct hwtype *xhw;
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     ioctl_or_perror_and_die(sockfd, SIOCGIFHWADDR, &ifr,
                     "can't get HW-Address for '%s'", ifname);
     if (hw_set && (ifr.ifr_hwaddr.sa_family != hw->type)) {
         bb_simple_error_msg_and_die("protocol type mismatch");
     }
     memcpy(sa, &(ifr.ifr_hwaddr), sizeof(struct sockaddr));
     if (option_mask32 & ARP_OPT_v) {
         xhw = get_hwntype(ifr.ifr_hwaddr.sa_family);
         if (!xhw || !xhw->print) {
             xhw = get_hwntype(-1);
         }
         bb_error_msg("device '%s' has HW address %s '%s'",
                 ifname, xhw->name,
                 xhw->print((unsigned char *) &ifr.ifr_hwaddr.sa_data));
     }
 }
References ARP_OPT_v, bb_error_msg(), bb_simple_error_msg_and_die(), get_hwntype(), hw, hw_set, ifr, ioctl_or_perror_and_die(), memcpy, hwtype::name, option_mask32, hwtype::print, SIOCGIFHWADDR, sockfd, and strncpy_IFNAMSIZ().
Referenced by arp_set().
arp_main()
int arp_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 487 of file arp.c.
 {
     const char *hw_type;
     const char *protocol;
     unsigned opts;
     INIT_G();
     xmove_fd(xsocket(AF_INET, SOCK_DGRAM, 0), sockfd);
     ap = get_aftype(DFLT_AF);
     /* Defaults are always supported */
     //if (!ap)
     //  bb_error_msg_and_die("%s: %s not supported", DFLT_AF, "address family");
     hw = get_hwtype(DFLT_HW);
     //if (!hw)
     //  bb_error_msg_and_die("%s: %s not supported", DFLT_HW, "hardware type");
     opts = getopt32(argv, "A:p:H:t:i:adnDsv", &protocol, &protocol,
                  &hw_type, &hw_type, &device);
     argv += optind;
     if (opts & (ARP_OPT_A | ARP_OPT_p)) {
         ap = get_aftype(protocol);
         if (!ap)
             bb_error_msg_and_die("%s: unknown %s", protocol, "address family");
     }
     if (opts & (ARP_OPT_H | ARP_OPT_t)) {
         hw = get_hwtype(hw_type);
         if (!hw)
             bb_error_msg_and_die("%s: unknown %s", hw_type, "hardware type");
         hw_set = 1;
     }
     //if (opts & ARP_OPT_i)... -i
     if (ap->af != AF_INET) {
         bb_error_msg_and_die("%s: kernel only supports 'inet'", ap->name);
     }
     if (hw->alen <= 0) {
         bb_error_msg_and_die("%s: %s without ARP support",
                 hw->name, "hardware type");
     }
     /* Now see what we have to do here... */
     if (opts & (ARP_OPT_d | ARP_OPT_s)) {
         if (argv[0] == NULL)
             bb_simple_error_msg_and_die("need host name");
         if (opts & ARP_OPT_s)
             return arp_set(argv);
         return arp_del(argv);
     }
     //if (opts & ARP_OPT_a) - default
     return arp_show(argv[0]);
 }
References AF_INET, ap, argv, arp_del(), ARP_OPT_A, ARP_OPT_d, ARP_OPT_H, ARP_OPT_p, ARP_OPT_s, ARP_OPT_t, arp_set(), arp_show(), bb_error_msg_and_die(), bb_simple_error_msg_and_die(), device, DFLT_AF, DFLT_HW, get_aftype(), get_hwtype(), getopt32(), hw, hw_set, INIT_G, NULL, optind, SOCK_DGRAM, sockfd, xmove_fd(), and xsocket().
arp_set()
static int arp_set (char ** args) static
Definition at line 252 of file arp.c.
 {
     char *host;
     struct arpreq req;
     struct sockaddr sa;
     int flags;
     memset(&req, 0, sizeof(req));
     host = *args++;
     if (ap->input(host, &sa) < 0) {
         bb_simple_herror_msg_and_die(host);
     }
     /* If a host has more than one address, use the correct one! */
     memcpy(&req.arp_pa, &sa, sizeof(struct sockaddr));
     /* Fetch the hardware address. */
     if (*args == NULL) {
         bb_simple_error_msg_and_die("need hardware address");
     }
     if (option_mask32 & ARP_OPT_D) {
         arp_getdevhw(*args++, &req.arp_ha);
     } else {
         if (hw->input(*args++, &req.arp_ha) < 0) {
             bb_simple_error_msg_and_die("invalid hardware address");
         }
     }
     /* Check out any modifiers. */
     flags = ATF_PERM | ATF_COM;
     while (*args != NULL) {
         switch (index_in_strings(options, *args)) {
         case 0: /* "pub" */
             flags |= ATF_PUBL;
             args++;
             break;
         case 1: /* "priv" */
             flags &= ~ATF_PUBL;
             args++;
             break;
         case 2: /* "temp" */
             flags &= ~ATF_PERM;
             args++;
             break;
         case 3: /* "trail" */
             flags |= ATF_USETRAILERS;
             args++;
             break;
         case 4: /* "dontpub" */
 #ifdef HAVE_ATF_DONTPUB
             flags |= ATF_DONTPUB;
 #else
             bb_simple_error_msg("feature ATF_DONTPUB is not supported");
 #endif
             args++;
             break;
         case 5: /* "auto" */
 #ifdef HAVE_ATF_MAGIC
             flags |= ATF_MAGIC;
 #else
             bb_simple_error_msg("feature ATF_MAGIC is not supported");
 #endif
             args++;
             break;
         case 6: /* "dev" */
             if (*++args == NULL)
                 bb_show_usage();
             device = *args;
             args++;
             break;
         case 7: /* "netmask" */
             if (*++args == NULL)
                 bb_show_usage();
             if (strcmp(*args, "255.255.255.255") != 0) {
                 host = *args;
                 if (ap->input(host, &sa) < 0) {
                     bb_simple_herror_msg_and_die(host);
                 }
                 memcpy(&req.arp_netmask, &sa, sizeof(struct sockaddr));
                 flags |= ATF_NETMASK;
             }
             args++;
             break;
         default:
             bb_show_usage();
             break;
         }
     }
     /* Fill in the remainder of the request. */
     req.arp_flags = flags;
     strncpy_IFNAMSIZ(req.arp_dev, device);
     /* Call the kernel. */
     if (option_mask32 & ARP_OPT_v)
         bb_simple_error_msg("SIOCSARP()");
     xioctl(sockfd, SIOCSARP, &req);
     return 0;
 }
References ap, args, arpreq::arp_dev, arpreq::arp_flags, arp_getdevhw(), arpreq::arp_ha, arpreq::arp_netmask, ARP_OPT_D, ARP_OPT_v, arpreq::arp_pa, ATF_COM, ATF_DONTPUB, ATF_MAGIC, ATF_NETMASK, ATF_PERM, ATF_PUBL, ATF_USETRAILERS, bb_show_usage(), bb_simple_error_msg(), bb_simple_error_msg_and_die(), bb_simple_herror_msg_and_die(), device, flags, hw, index_in_strings(), memcpy, memset, NULL, option_mask32, SIOCSARP, sockfd, strcmp, strncpy_IFNAMSIZ(), and xioctl.
Referenced by arp_main().
arp_show()
static int arp_show (char * name) static
Definition at line 405 of file arp.c.
 {
     const char *host;
     const char *hostname;
     FILE *fp;
     struct sockaddr sa;
     int type, flags;
     int num;
     unsigned entries = 0, shown = 0;
     char ip[128];
     char hwa[128];
     char mask[128];
     char line[128];
     char dev[128];
     host = NULL;
     if (name != NULL) {
         /* Resolve the host name. */
         if (ap->input(name, &sa) < 0) {
             bb_simple_herror_msg_and_die(name);
         }
         host = xstrdup(ap->sprint(&sa, 1));
     }
     fp = xfopen_for_read("/proc/net/arp");
     /* Bypass header -- read one line */
     fgets(line, sizeof(line), fp);
     /* Read the ARP cache entries. */
     while (fgets(line, sizeof(line), fp)) {
         mask[0] = '-'; mask[1] = '\0';
         dev[0] = '-'; dev[1] = '\0';
         /* All these strings can't overflow
          * because fgets above reads limited amount of data */
         num = sscanf(line, "%s 0x%x 0x%x %s %s %s\n",
                     ip, &type, &flags, hwa, mask, dev);
         if (num < 4)
             break;
         entries++;
         /* if the user specified hw-type differs, skip it */
         if (hw_set && (type != hw->type))
             continue;
         /* if the user specified address differs, skip it */
         if (host && strcmp(ip, host) != 0)
             continue;
         /* if the user specified device differs, skip it */
         if (device[0] && strcmp(dev, device) != 0)
             continue;
         shown++;
         /* This IS ugly but it works -be */
         hostname = "?";
         if (!(option_mask32 & ARP_OPT_n)) {
             if (ap->input(ip, &sa) < 0)
                 hostname = ip;
             else
                 hostname = ap->sprint(&sa, (option_mask32 & ARP_OPT_n) | 0x8000);
             if (strcmp(hostname, ip) == 0)
                 hostname = "?";
         }
         arp_disp(hostname, ip, type, flags, hwa, mask, dev);
     }
     if (option_mask32 & ARP_OPT_v)
         printf("Entries: %u\tSkipped: %u\tFound: %u\n",
                 entries, entries - shown, shown);
     if (!shown) {
         if (hw_set || host || device[0])
             printf("No match found in %u entries\n", entries);
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         free((char*)host);
         fclose(fp);
     }
     return 0;
 }
References ap, arp_disp(), ARP_OPT_n, ARP_OPT_v, bb_simple_herror_msg_and_die(), device, fclose(), fgets, flags, free, hw, hw_set, NULL, num, option_mask32, printf, sscanf(), strcmp, type, xfopen_for_read(), and xstrdup().
Referenced by arp_main().
Variable Documentation
ALIGN1
const char options [] ALIGN1 static
Initial value:
=
    "pub\0"
    "priv\0"
    "temp\0"
    "trail\0"
    "dontpub\0"
    "auto\0"
    "dev\0"
    "netmask\0"
Definition at line 93 of file arp.c.
Referenced by arp_disp().
FIX_ALIASING
struct globals FIX_ALIASING