Fennix Userspace: Userspace/apps/base/busybox/miscutils/seedrng.c File Reference
seedrng.c File Reference
#include "libbb.h"
#include <linux/random.h>
#include <sys/random.h>
#include <sys/file.h>
Macros
#define GRND_INSECURE 0x0004 /* Apparently some headers don't ship with this yet. */
#define DEFAULT_SEED_DIR "/var/lib/seedrng"
#define CREDITABLE_SEED_NAME "seed.credit"
#define NON_CREDITABLE_SEED_NAME "seed.no-credit"
Enumerations
enum { MIN_SEED_LEN = SHA256_OUTSIZE , MAX_SEED_LEN = 256 }
Functions
static size_t determine_optimal_seed_len (void)
static bool read_new_seed (uint8_t *seed, size_t len)
static void seed_from_file_if_exists (const char *filename, int dfd, bool credit, sha256_ctx_t *hash)
int seedrng_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CREDITABLE_SEED_NAME
#define CREDITABLE_SEED_NAME "seed.credit"
Definition at line 53 of file seedrng.c.
DEFAULT_SEED_DIR
#define DEFAULT_SEED_DIR "/var/lib/seedrng"
Definition at line 52 of file seedrng.c.
GRND_INSECURE
#define GRND_INSECURE 0x0004 /* Apparently some headers don't ship with this yet. */
Definition at line 49 of file seedrng.c.
NON_CREDITABLE_SEED_NAME
#define NON_CREDITABLE_SEED_NAME "seed.no-credit"
Definition at line 54 of file seedrng.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MIN_SEED_LEN
MAX_SEED_LEN
Definition at line 56 of file seedrng.c.
      {
     MIN_SEED_LEN = SHA256_OUTSIZE,
     /* kernels < 5.18 could return short reads from getrandom()
      * if signal is pending and length is > 256.
      * Let's limit our reads to 256 bytes.
      */
     MAX_SEED_LEN = 256,
 };
Function Documentation
determine_optimal_seed_len()
static size_t determine_optimal_seed_len (void) static
Definition at line 65 of file seedrng.c.
 {
     char poolsize_str[12];
     unsigned poolsize;
     int n;
     n = open_read_close("/proc/sys/kernel/random/poolsize", poolsize_str, sizeof(poolsize_str) - 1);
     if (n < 0) {
         bb_perror_msg("can't determine pool size, assuming %u bits", MIN_SEED_LEN * 8);
         return MIN_SEED_LEN;
     }
     poolsize_str[n] = '\0';
     poolsize = (bb_strtou(poolsize_str, NULL, 10) + 7) / 8;
     return MAX(MIN(poolsize, MAX_SEED_LEN), MIN_SEED_LEN);
 }
References bb_perror_msg(), bb_strtou(), MAX, MAX_SEED_LEN, MIN, MIN_SEED_LEN, n, NULL, and open_read_close().
Referenced by seedrng_main().
read_new_seed()
static bool read_new_seed (uint8_t * seed, size_t len) static
Definition at line 81 of file seedrng.c.
 {
     bool is_creditable;
     ssize_t ret;
     ret = getrandom(seed, len, GRND_NONBLOCK);
     if (ret == (ssize_t)len) {
         return true;
     }
     if (ret < 0 && errno == ENOSYS) {
         int fd = xopen("/dev/random", O_RDONLY);
         struct pollfd random_fd;
         random_fd.fd = fd;
         random_fd.events = POLLIN;
         is_creditable = poll(&random_fd, 1, 0) == 1;
 //This is racy. is_creditable can be set to true here, but other process
 //can consume "good" random data from /dev/urandom before we do it below.
         close(fd);
     } else {
         if (getrandom(seed, len, GRND_INSECURE) == (ssize_t)len)
             return false;
         is_creditable = false;
     }
     /* Either getrandom() is not implemented, or
      * getrandom(GRND_INSECURE) did not give us LEN bytes.
      * Fallback to reading /dev/urandom.
      */
     errno = 0;
     if (open_read_close("/dev/urandom", seed, len) != (ssize_t)len)
         bb_perror_msg_and_die("can't read '%s'", "/dev/urandom");
     return is_creditable;
 }
References bb_perror_msg_and_die(), close(), ENOSYS, errno, pollfd::events, fd, pollfd::fd, getrandom(), GRND_INSECURE, GRND_NONBLOCK, O_RDONLY, open_read_close(), poll(), POLLIN, seed, and xopen().
Referenced by seedrng_main().
seed_from_file_if_exists()
static void seed_from_file_if_exists (const char * filename, int dfd, bool credit, sha256_ctx_t * hash) static
Definition at line 115 of file seedrng.c.
 {
     struct {
         int entropy_count;
         int buf_size;
         uint8_t buf[MAX_SEED_LEN];
     } req;
     ssize_t seed_len;
     seed_len = open_read_close(filename, req.buf, sizeof(req.buf));
     if (seed_len < 0) {
         if (errno != ENOENT)
             bb_perror_msg_and_die("can't read '%s'", filename);
         return;
     }
     xunlink(filename);
     if (seed_len != 0) {
         int fd;
         /* We are going to use this data to seed the RNG:
          * we believe it to genuinely containing entropy.
          * If this just-unlinked file survives
          * (if machine crashes before deletion is recorded on disk)
          * and we reuse it after reboot, this assumption
          * would be violated, and RNG may end up generating
          * the same data. fsync the directory
          * to make sure file is gone:
          */
         if (fsync(dfd) != 0)
             bb_simple_perror_msg_and_die("I/O error");
 //Length is not random, and taking its address spills variable to stack
 //      sha256_hash(hash, &seed_len, sizeof(seed_len));
         sha256_hash(hash, req.buf, seed_len);
         req.buf_size = seed_len;
         seed_len *= 8;
         req.entropy_count = credit ? seed_len : 0;
         printf("Seeding %u bits %s crediting\n",
                 (unsigned)seed_len, credit ? "and" : "without");
         fd = xopen("/dev/urandom", O_RDONLY);
         xioctl(fd, RNDADDENTROPY, &req);
         if (ENABLE_FEATURE_CLEAN_UP)
             close(fd);
     }
 }
References bb_perror_msg_and_die(), bb_simple_perror_msg_and_die(), buf, close(), ENOENT, errno, fd, filename, fsync(), MAX_SEED_LEN, O_RDONLY, open_read_close(), printf(), sha256_hash, xioctl, xopen(), and xunlink().
Referenced by seedrng_main().
seedrng_main()
int seedrng_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 163 of file seedrng.c.
 {
     const char *seed_dir;
     int fd, dfd;
     int i;
     unsigned opts;
     uint8_t new_seed[MAX_SEED_LEN];
     size_t new_seed_len;
     bool new_seed_creditable;
     struct timespec timestamp[2];
     sha256_ctx_t hash;
     enum {
         OPT_n = (1 << 0), /* must be 1 */
         OPT_d = (1 << 1),
     };
 #if ENABLE_LONG_OPTS
     static const char longopts[] ALIGN1 =
         "skip-credit\0" No_argument       "n"
         "seed-dir\0"    Required_argument "d"
         ;
 #endif
     seed_dir = DEFAULT_SEED_DIR;
     opts = getopt32long(argv, "nd:", longopts, &seed_dir);
     umask(0077);
     if (getuid() != 0)
         bb_simple_error_msg_and_die(bb_msg_you_must_be_root);
     if (mkdir(seed_dir, 0700) < 0 && errno != EEXIST)
         bb_perror_msg_and_die("can't create directory '%s'", seed_dir);
     dfd = xopen(seed_dir, O_DIRECTORY | O_RDONLY);
     xfchdir(dfd);
     /* Concurrent runs of this tool might feed the same data to RNG twice.
      * Avoid concurrent runs by taking a blocking lock on the directory.
      * Not checking for errors. Looking at manpage,
      * ENOLCK "The kernel ran out of memory for allocating lock records"
      * seems to be the only one which is possible - and if that happens,
      * machine is OOMing (much worse problem than inability to lock...).
      * Also, typically configured Linux machines do not fail GFP_KERNEL
      * allocations (they trigger memory reclaim instead).
      */
     flock(dfd, LOCK_EX); /* blocks while another instance runs */
     sha256_begin(&hash);
 //Hashing in a constant string doesn't add any entropy
 //  sha256_hash(&hash, "SeedRNG v1 Old+New Prefix", 25);
     clock_gettime(CLOCK_REALTIME, &timestamp[0]);
     clock_gettime(CLOCK_BOOTTIME, &timestamp[1]);
     sha256_hash(&hash, timestamp, sizeof(timestamp));
     for (i = 0; i <= 1; i++) {
         seed_from_file_if_exists(
             i == 0 ? NON_CREDITABLE_SEED_NAME : CREDITABLE_SEED_NAME,
             dfd,
             /*credit?*/ (opts ^ OPT_n) & i, /* 0, then 1 unless -n */
             &hash);
     }
     new_seed_len = determine_optimal_seed_len();
     new_seed_creditable = read_new_seed(new_seed, new_seed_len);
 //Length is not random, and taking its address spills variable to stack
 //  sha256_hash(&hash, &new_seed_len, sizeof(new_seed_len));
     sha256_hash(&hash, new_seed, new_seed_len);
     sha256_end(&hash, new_seed + new_seed_len - SHA256_OUTSIZE);
     printf("Saving %u bits of %screditable seed for next boot\n",
         (unsigned)new_seed_len * 8, new_seed_creditable ? "" : "non-");
     fd = xopen3(NON_CREDITABLE_SEED_NAME, O_WRONLY | O_CREAT | O_TRUNC, 0400);
     xwrite(fd, new_seed, new_seed_len);
     if (new_seed_creditable) {
         /* More paranoia when we create a file which we believe contains
          * genuine entropy: make sure disk is not full, quota isn't exceeded, etc:
          */
         if (fsync(fd) < 0)
             bb_perror_msg_and_die("can't write '%s'", NON_CREDITABLE_SEED_NAME);
         xrename(NON_CREDITABLE_SEED_NAME, CREDITABLE_SEED_NAME);
     }
     return EXIT_SUCCESS;
 }
References ALIGN1, argv, bb_perror_msg_and_die(), bb_simple_error_msg_and_die(), CREDITABLE_SEED_NAME, DEFAULT_SEED_DIR, determine_optimal_seed_len(), EEXIST, errno, EXIT_SUCCESS, fd, flock(), fsync(), getopt32long, getuid, i, LOCK_EX, MAX_SEED_LEN, mkdir(), No_argument, NON_CREDITABLE_SEED_NAME, O_CREAT, O_DIRECTORY, O_RDONLY, O_TRUNC, O_WRONLY, OPT_d, OPT_n, printf(), read_new_seed(), Required_argument, seed_from_file_if_exists(), sha256_begin(), sha256_end, sha256_hash, SHA256_OUTSIZE, umask(), xfchdir(), xopen(), xopen3(), xrename(), and xwrite().