Fennix: Userspace/mlibc/options/ansi/generic/complex/cprojf.c File Reference
cprojf.c File Reference
#include <complex.h>
#include <math.h>
#include "fdlibm.h"
Functions
float complex cprojf (float complex z)
Function Documentation
cprojf()
float complex cprojf (float complex z)
Definition at line 53 of file cprojf.c.
 {
     float_complex w = { .z = z };
     if (isinf(crealf(z)) || isinf(cimagf(z))) {
 #ifdef __INFINITY
         REAL_PART(w) = __INFINITY;
 #else
         REAL_PART(w) = INFINITY;
 #endif
         IMAG_PART(w) = copysignf(0.0, cimagf(z));
     }
     return (w.z);
 }
References cimagf(), copysignf(), crealf(), IMAG_PART, INFINITY, isinf, REAL_PART, and float_complex::z.