Fennix: Userspace/musl/src/mq/mq_timedsend.c File Reference
mq_timedsend.c File Reference
#include <mqueue.h>
#include <errno.h>
#include "syscall.h"
Macros
#define IS32BIT(x) !((x)+0x80000000ULL>>32)
#define CLAMP(x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Functions
int mq_timedsend (mqd_t mqd, const char *msg, size_t len, unsigned prio, const struct timespec *at)
Macro Definition Documentation
CLAMP
#define CLAMP (x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Definition at line 6 of file mq_timedsend.c.
IS32BIT
#define IS32BIT (x) !((x)+0x80000000ULL>>32)
Definition at line 5 of file mq_timedsend.c.
Function Documentation
mq_timedsend()
int mq_timedsend (mqd_t mqd, const char * msg, size_t len, unsigned prio, const struct timespec * at)
Definition at line 8 of file mq_timedsend.c.
 {
 #ifdef SYS_mq_timedsend_time64
     time_t s = at ? at->tv_sec : 0;
     long ns = at ? at->tv_nsec : 0;
     long r = -ENOSYS;
     if (SYS_mq_timedsend == SYS_mq_timedsend_time64 || !IS32BIT(s))
         r = __syscall_cp(SYS_mq_timedsend_time64, mqd, msg, len, prio,
             at ? ((long long []){at->tv_sec, at->tv_nsec}) : 0);
     if (SYS_mq_timedsend == SYS_mq_timedsend_time64 || r != -ENOSYS)
         return __syscall_ret(r);
     return syscall_cp(SYS_mq_timedsend, mqd, msg, len, prio,
         at ? ((long[]){CLAMP(s), ns}) : 0);
 #else
     return syscall_cp(SYS_mq_timedsend, mqd, msg, len, prio, at);
 #endif
 }
References __syscall_cp, __syscall_ret(), CLAMP, ENOSYS, IS32BIT, len, s, SYS_mq_timedsend, SYS_mq_timedsend_time64, syscall_cp, timespec::tv_nsec, and timespec::tv_sec.
Referenced by __mq_timedsend_time32(), and mq_send().