Fennix Userspace: Userspace/apps/base/busybox/libbb/skip_whitespace.c File Reference
skip_whitespace.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC skip_whitespace (const char *s)
char *FAST_FUNC skip_non_whitespace (const char *s)
char *FAST_FUNC skip_dev_pfx (const char *tty_name)
Function Documentation
skip_dev_pfx()
char* FAST_FUNC skip_dev_pfx (const char * tty_name)
Definition at line 33 of file skip_whitespace.c.
 {
     char *unprefixed = is_prefixed_with(tty_name, "/dev/");
     return unprefixed ? unprefixed : (char*)tty_name;
 }
References is_prefixed_with().
Referenced by base_device(), iostat_main(), login_main(), may_wakeup(), open_tty(), parse_inittab(), su_main(), update_utmp(), and write_new_utmp().
skip_non_whitespace()
char* FAST_FUNC skip_non_whitespace (const char * s)
Definition at line 25 of file skip_whitespace.c.
 {
     while (*s != '\0' && *s != ' ' && (unsigned char)(*s - 9) > (13 - 9))
         s++;
     return (char *) s;
 }
References s.
Referenced by colon(), display_process_list(), download_one_url(), factor_main(), get_cpu_statistics(), load_crontab(), nameif_parse_selector(), process_cron_update_file(), process_timer_stats(), run_pipe(), tsort_main(), and uniq_main().
skip_whitespace()
char* FAST_FUNC skip_whitespace (const char * s)
Definition at line 11 of file skip_whitespace.c.
 {
     /* In POSIX/C locale (the only locale we care about: do we REALLY want
      * to allow Unicode whitespace in, say, .conf files? nuts!)
      * isspace is only these chars: "\t\n\v\f\r" and space.
      * "\t\n\v\f\r" happen to have ASCII codes 9,10,11,12,13.
      * Use that.
      */
     while (*s == ' ' || (unsigned char)(*s - 9) <= (13 - 9))
         s++;
     return (char *) s;
 }
References s.
Referenced by add_cmd(), awk_split(), bb_dump_add(), bb_dump_addfile(), check_operator(), colon(), compare_keys(), config_read(), doCommands(), download_one_url(), evaluate_string(), factor_main(), get_block_backed_filesystems(), get_cpu_statistics(), get_name(), get_sanitized_hdr(), getNum(), handle_incoming_and_exit(), if_redefined(), load_crontab(), nameif_parse_selector(), new_process_module_arguments(), next_arg(), next_word(), parse_cmd_args(), parse_file_cmd(), print_direc(), process_irq_counts(), process_timer_stats(), query(), read_config_file(), read_interfaces(), reverse(), run_pipe(), stack_machine(), tokenize(), trim(), tsort_main(), uniq_main(), and write_irqcpu_stats().