Fennix Userspace: Userspace/mlibc/options/ansi/generic/inttypes-stubs.cpp File Reference
inttypes-stubs.cpp File Reference
#include <ctype.h>
#include <inttypes.h>
#include <string.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
Functions
intmax_t imaxabs (intmax_t num)
imaxdiv_t imaxdiv (intmax_t number, intmax_t denom)
template<class T >
T strtoxmax (const char *it, char **out, int base)
intmax_t strtoimax (const char *it, char **out, int base)
uintmax_t strtoumax (const char *it, char **out, int base)
intmax_t wcstoimax (const wchar_t *__restrict, wchar_t **__restrict, int)
uintmax_t wcstoumax (const wchar_t *__restrict, wchar_t **__restrict, int)
Variables
static const char * __mlibc_digits = "0123456789abcdefghijklmnopqrstuvwxyz"
Function Documentation
imaxabs()
intmax_t imaxabs (intmax_t num)
Definition at line 11 of file inttypes-stubs.cpp.
{
     return num < 0 ? -num : num;
 }
References num.
imaxdiv()
imaxdiv_t imaxdiv (intmax_t number, intmax_t denom)
Definition at line 14 of file inttypes-stubs.cpp.
{
     imaxdiv_t r;
     r.quot = number / denom;
     r.rem = number % denom;
     return r;
 }
References number, and r.
Referenced by expassign(), and expmuldiv().
strtoimax()
intmax_t strtoimax (const char * it, char ** out, int base)
Definition at line 86 of file inttypes-stubs.cpp.
{
     // TODO: This function has to check for overflow!
     return strtoxmax<intmax_t>(it, out, base);
 }
References base, and out().
strtoumax()
uintmax_t strtoumax (const char * it, char ** out, int base)
Definition at line 90 of file inttypes-stubs.cpp.
{
     return strtoxmax<uintmax_t>(it, out, base);
 }
References base, and out().
strtoxmax()
template<class T > T strtoxmax (const char * it, char ** out, int base)
Definition at line 21 of file inttypes-stubs.cpp.
{
     T v = 0;
     bool negate = false;
     const unsigned char *s = (const unsigned char *)it;
     int c;
     if(std::is_signed<T>::value) {
         if(*s == '+') {
             s++;
         }else if(*s == '-') {
             negate = true;
             s++;
         }
     }
     do {
         c = *s++;
     } while (isspace(c));
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X')) {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     if(base == 8) {
         if(*it != 0)
             goto parse_digits;
         it++;
     }else if(base == 16) {
         if(*it != 0)
             goto parse_digits;
         it++;
         if(*it != 'x' && *it != 'X')
             goto parse_digits;
         it++;
     }
 parse_digits:
     while(*it) {
         if(isspace(*it)) {
             it++;
             continue;
         }
         __ensure(base <= 10); // TODO: For base > 10 we need to implement tolower().
         //auto c = strchr(__mlibc_digits, tolower(*it));
         auto c = strchr(__mlibc_digits, *it);
         if(!c || (c - __mlibc_digits) >= base)
             break;
         v = v * base + (c - __mlibc_digits);
         it++;
     }
     if(std::is_signed<T>::value) {
         if(negate)
             v = -v;
     }
     if(out)
         *out = const_cast<char *>(it);
     return v;
 }
References __ensure, __mlibc_digits, base, c, isspace, out(), strchr(), T, and value.
wcstoimax()
intmax_t wcstoimax (const wchar_t * __restrict, wchar_t ** __restrict, int)
Definition at line 93 of file inttypes-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
wcstoumax()
uintmax_t wcstoumax (const wchar_t * __restrict, wchar_t ** __restrict, int)
Definition at line 97 of file inttypes-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Variable Documentation
__mlibc_digits
const char* __mlibc_digits = "0123456789abcdefghijklmnopqrstuvwxyz" static
Definition at line 9 of file inttypes-stubs.cpp.
Referenced by strtoxmax().