Fennix: Userspace/apps/base/busybox/networking/libiproute/utils.h File Reference
utils.h File Reference
#include "libnetlink.h"
#include "ll_map.h"
#include "rtm_map.h"
Data Structures
struct inet_prefix
struct dn_naddr
struct ipx_addr
Macros
#define IPPROTO_ESP 50
#define IPPROTO_AH 51
#define SPRINT_BSIZE 64
#define SPRINT_BUF(x) char x[SPRINT_BSIZE]
#define PREFIXLEN_SPECIFIED 1
#define DN_MAXADDL 20
#define AF_DECnet 12
#define IPX_NODE_LEN 6
#define NEXT_ARG() do { argv = next_arg(argv); } while (0)
#define format_host(af, len, addr) rt_addr_n2a(af, addr)
Functions
char ** next_arg (char **argv) FAST_FUNC
uint32_t get_addr32 (char *name) FAST_FUNC
int get_addr_1 (inet_prefix *dst, char *arg, int family) FAST_FUNC
int get_addr (inet_prefix *dst, char *arg, int family) FAST_FUNC
void get_prefix (inet_prefix *dst, char *arg, int family) FAST_FUNC
unsigned get_unsigned (char *arg, const char *errmsg) FAST_FUNC
uint32_t get_u32 (char *arg, const char *errmsg) FAST_FUNC
uint16_t get_u16 (char *arg, const char *errmsg) FAST_FUNC
const char * rt_addr_n2a (int af, void *addr) FAST_FUNC
void invarg_1_to_2 (const char *, const char *) FAST_FUNC NORETURN
void duparg (const char *, const char *) FAST_FUNC NORETURN
void duparg2 (const char *, const char *) FAST_FUNC NORETURN
int inet_addr_match (const inet_prefix *a, const inet_prefix *b, int bits) FAST_FUNC
unsigned get_hz (void) FAST_FUNC
Variables
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN family_t preferred_family
smallint show_stats
smallint show_details
smallint show_raw
smallint resolve_hosts
smallint oneline
char _SL_
Data Structure Documentation
inet_prefix
struct inet_prefix
Definition at line 29 of file utils.h.
Data Fields
int16_t bitlen
uint8_t bytelen
uint32_t data[4]
uint8_t family
dn_naddr
struct dn_naddr
Definition at line 43 of file utils.h.
Data Fields
unsigned char a_addr[DN_MAXADDL]
unsigned short a_len
ipx_addr
struct ipx_addr
Definition at line 50 of file utils.h.
Data Fields
uint32_t ipx_net
uint8_t ipx_node[IPX_NODE_LEN]
Macro Definition Documentation
AF_DECnet
#define AF_DECnet 12
Definition at line 40 of file utils.h.
DN_MAXADDL
#define DN_MAXADDL 20
Definition at line 38 of file utils.h.
format_host
#define format_host (af, len, addr) rt_addr_n2a(af, addr)
Definition at line 72 of file utils.h.
IPPROTO_AH
#define IPPROTO_AH 51
Definition at line 23 of file utils.h.
IPPROTO_ESP
#define IPPROTO_ESP 50
Definition at line 20 of file utils.h.
IPX_NODE_LEN
#define IPX_NODE_LEN 6
Definition at line 48 of file utils.h.
NEXT_ARG
#define NEXT_ARG () do { argv = next_arg(argv); } while (0)
Definition at line 56 of file utils.h.
PREFIXLEN_SPECIFIED
#define PREFIXLEN_SPECIFIED 1
Definition at line 36 of file utils.h.
SPRINT_BSIZE
#define SPRINT_BSIZE 64
Definition at line 26 of file utils.h.
SPRINT_BUF
#define SPRINT_BUF (x) char x[SPRINT_BSIZE]
Definition at line 27 of file utils.h.
Function Documentation
duparg()
void duparg (const char * key, const char * arg)
Definition at line 242 of file utils.c.
 {
     bb_error_msg_and_die("duplicate \"%s\": \"%s\" is the second value", key, arg);
 }
References bb_error_msg_and_die().
Referenced by do_add_or_delete(), do_set(), ipaddr_modify(), and tc_main().
duparg2()
void duparg2 (const char * key, const char * arg)
Definition at line 247 of file utils.c.
 {
     bb_error_msg_and_die("either \"%s\" is duplicate, or \"%s\" is garbage", key, arg);
 }
References bb_error_msg_and_die().
Referenced by do_set(), ipaddr_list_or_flush(), ipaddr_modify(), iproute_modify(), parse_args(), and tc_main().
get_addr()
int get_addr (inet_prefix * dst, char * arg, int family)
Definition at line 201 of file utils.c.
 {
     if (family == AF_PACKET) {
         bb_error_msg_and_die("\"%s\" may be inet %s, but it is not allowed in this context", arg, "address");
     }
     if (get_addr_1(dst, arg, family)) {
         bb_error_msg_and_die("an %s %s is expected rather than \"%s\"", "inet", "address", arg);
     }
     return 0;
 }
References AF_PACKET, bb_error_msg_and_die(), dst, and get_addr_1().
Referenced by ipaddr_modify(), and iproute_modify().
get_addr32()
uint32_t get_addr32 (char * name)
Definition at line 220 of file utils.c.
 {
     inet_prefix addr;
     if (get_addr_1(&addr, name, AF_INET)) {
         bb_error_msg_and_die("an %s %s is expected rather than \"%s\"", "IP", "address", name);
     }
     return addr.data[0];
 }
References addr, AF_INET, bb_error_msg_and_die(), and get_addr_1().
Referenced by iprule_modify(), and parse_args().
get_addr_1()
int get_addr_1 (inet_prefix * dst, char * arg, int family)
Definition at line 82 of file utils.c.
 {
     memset(addr, 0, sizeof(*addr));
     if (strcmp(name, "default") == 0
      || strcmp(name, "all") == 0
      || strcmp(name, "any") == 0
     ) {
         addr->family = family;
         addr->bytelen = (family == AF_INET6 ? 16 : 4);
         addr->bitlen = -1;
         return 0;
     }
     if (strchr(name, ':')) {
         addr->family = AF_INET6;
         if (family != AF_UNSPEC && family != AF_INET6)
             return -1;
         if (inet_pton(AF_INET6, name, addr->data) <= 0)
             return -1;
         addr->bytelen = 16;
         addr->bitlen = -1;
         return 0;
     }
     if (family != AF_UNSPEC && family != AF_INET)
         return -1;
     /* Try to parse it as IPv4 */
     addr->family = AF_INET;
 #if 0 /* Doesn't handle e.g. "10.10", for example, "ip r l root 10.10/16" */
     if (inet_pton(AF_INET, name, addr->data) <= 0)
         return -1;
 #else
     {
         unsigned i = 0;
         unsigned n = 0;
         const char *cp = name - 1;
         while (*++cp) {
             if ((unsigned char)(*cp - '0') <= 9) {
                 n = 10 * n + (unsigned char)(*cp - '0');
                 if (n >= 256)
                     return -1;
                 ((uint8_t*)addr->data)[i] = n;
                 continue;
             }
             if (*cp == '.' && ++i <= 3) {
                 n = 0;
                 continue;
             }
             return -1;
         }
     }
 #endif
     addr->bytelen = 4;
     addr->bitlen = -1;
     return 0;
 }
References addr, AF_INET, AF_INET6, AF_UNSPEC, i, inet_pton(), memset, n, strchr(), and strcmp.
Referenced by get_addr(), get_addr32(), get_prefix_1(), and ll_addr_a2n().
get_hz()
unsigned get_hz (void)
Definition at line 15 of file utils.c.
 {
     static unsigned hz_internal;
     FILE *fp;
     if (hz_internal)
         return hz_internal;
     fp = fopen_for_read("/proc/net/psched");
     if (fp) {
         unsigned nom, denom;
         if (fscanf(fp, "%*08x%*08x%08x%08x", &nom, &denom) == 2)
             if (nom == 1000000)
                 hz_internal = denom;
         fclose(fp);
     }
     if (!hz_internal)
         hz_internal = bb_clk_tck();
     return hz_internal;
 }
References bb_clk_tck(), fclose(), fopen_for_read(), and fscanf().
Referenced by print_neigh(), and print_route().
get_prefix()
void get_prefix (inet_prefix * dst, char * arg, int family)
Definition at line 212 of file utils.c.
 {
     if (family == AF_PACKET) {
         bb_error_msg_and_die("\"%s\" may be inet %s, but it is not allowed in this context", arg, "prefix");
     }
     get_prefix_1(dst, arg, family);
 }
References AF_PACKET, bb_error_msg_and_die(), dst, and get_prefix_1().
get_u16()
uint16_t get_u16 (char * arg, const char * errmsg)
Definition at line 67 of file utils.c.
 {
     unsigned long res;
     char *ptr;
     if (*arg) {
         res = strtoul(arg, &ptr, 0);
 //FIXME: "" will be accepted too, is it correct?!
         if (!*ptr && res <= 0xFFFF) {
             return res;
         }
     }
     invarg_1_to_2(arg, errmsg); /* does not return */
 }
References errmsg(), invarg_1_to_2(), and strtoul().
Referenced by vlan_parse_opt().
get_u32()
uint32_t get_u32 (char * arg, const char * errmsg)
Definition at line 52 of file utils.c.
 {
     unsigned long res;
     char *ptr;
     if (*arg) {
         res = strtoul(arg, &ptr, 0);
 //FIXME: "" will be accepted too, is it correct?!
         if (!*ptr && res <= 0xFFFFFFFFUL) {
             return res;
         }
     }
     invarg_1_to_2(arg, errmsg); /* does not return */
 }
References errmsg(), invarg_1_to_2(), and strtoul().
Referenced by iproute_modify(), iprule_modify(), set_lifetime(), tc_main(), and vrf_parse_opt().
get_unsigned()
unsigned get_unsigned (char * arg, const char * errmsg)
Definition at line 37 of file utils.c.
 {
     unsigned long res;
     char *ptr;
     if (*arg) {
         res = strtoul(arg, &ptr, 0);
 //FIXME: "" will be accepted too, is it correct?!
         if (!*ptr && res <= UINT_MAX) {
             return res;
         }
     }
     invarg_1_to_2(arg, errmsg); /* does not return */
 }
References errmsg(), invarg_1_to_2(), strtoul(), and UINT_MAX.
Referenced by do_set(), iproute_modify(), and parse_args().
inet_addr_match()
int inet_addr_match (const inet_prefix * a, const inet_prefix * b, int bits)
Definition at line 252 of file utils.c.
 {
     const uint32_t *a1 = a->data;
     const uint32_t *a2 = b->data;
     int words = bits >> 5;
     bits &= 0x1f;
     if (words)
         if (memcmp(a1, a2, words << 2))
             return -1;
     if (bits) {
         uint32_t w1, w2;
         uint32_t mask;
         w1 = a1[words];
         w2 = a2[words];
         mask = htonl((0xffffffff) << (0x20 - bits));
         if ((w1 ^ w2) & mask)
             return 1;
     }
     return 0;
 }
References a1, a2, inet_prefix::data, htonl(), memcmp(), w1, and w2.
Referenced by ipaddr_list_or_flush(), print_addrinfo(), print_neigh(), and print_route().
invarg_1_to_2()
void invarg_1_to_2 (const char * arg, const char * opt)
Definition at line 237 of file utils.c.
 {
     bb_error_msg_and_die(bb_msg_invalid_arg_to, arg, opt);
 }
References bb_error_msg_and_die(), and opt.
Referenced by do_add_or_delete(), do_ipaddr(), do_iplink(), do_ipneigh(), do_iproute(), do_iprule(), do_iptunnel(), do_set(), get_u16(), get_u32(), get_unsigned(), ip_parse_common_args(), ipaddr_list_or_flush(), ipaddr_modify(), iproute_list_or_flush(), iproute_modify(), iprule_modify(), parse_args(), slattach_main(), tc_main(), vlan_parse_opt(), and vrf_parse_opt().
next_arg()
char** next_arg (char ** argv)
Definition at line 230 of file utils.c.
 {
     if (!*++argv)
         bb_simple_error_msg_and_die("command line is not complete, try \"help\"");
     return argv;
 }
References argv, and bb_simple_error_msg_and_die().
rt_addr_n2a()
const char* rt_addr_n2a (int af, void * addr)
Definition at line 280 of file utils.c.
 {
     switch (af) {
     case AF_INET:
     case AF_INET6:
         return inet_ntop(af, addr,
             auto_string(xzalloc(INET6_ADDRSTRLEN)), INET6_ADDRSTRLEN
         );
     default:
         return "???";
     }
 }
References addr, AF_INET, AF_INET6, auto_string(), INET6_ADDRSTRLEN, inet_ntop(), and xzalloc().
Referenced by print_addrinfo(), print_route(), and print_rule().
Variable Documentation
_SL_
char _SL_ extern
Definition at line 19 of file ip_parse_common_args.c.
Referenced by ip_parse_common_args(), print_addrinfo(), print_linkinfo(), print_route(), and print_tunnel().
oneline
smallint oneline extern
Definition at line 18 of file ip_parse_common_args.c.
Referenced by ip_parse_common_args(), and ipaddr_list_or_flush().
preferred_family
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN family_t preferred_family extern
Definition at line 17 of file ip_parse_common_args.c.
Referenced by do_add_or_delete(), ip_parse_common_args(), ipaddr_list_link(), ipaddr_list_or_flush(), ipaddr_modify(), ipneigh_list_or_flush(), iproute_get(), iproute_list_or_flush(), iproute_modify(), iprule_list(), iprule_modify(), set_master(), and set_netns().
resolve_hosts
smallint resolve_hosts extern
show_details
smallint show_details extern
show_raw
smallint show_raw extern
show_stats
smallint show_stats extern