Fennix: Userspace/apps/base/busybox/util-linux/hexdump.c File Reference
hexdump.c File Reference
#include "libbb.h"
#include "dump.h"
Functions
static void bb_dump_addfile (dumper_t *dumper, char *name)
int hexdump_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char *const add_strings[] ALIGN_PTR
static const char add_first[] ALIGN1 = "\"%07.7_Ax\n\""
Function Documentation
bb_dump_addfile()
static void bb_dump_addfile (dumper_t * dumper, char * name) static
Definition at line 57 of file hexdump.c.
 {
     char *p;
     FILE *fp;
     char *buf;
     fp = xfopen_for_read(name);
     while ((buf = xmalloc_fgetline(fp)) != NULL) {
         p = skip_whitespace(buf);
         if (*p && (*p != '#')) {
             bb_dump_add(dumper, p);
         }
         free(buf);
     }
     fclose(fp);
 }
References bb_dump_add(), buf, dumper, fclose(), free, NULL, p, skip_whitespace(), xfopen_for_read(), and xmalloc_fgetline().
Referenced by hexdump_main().
hexdump_main()
int hexdump_main (int argc, char ** argv)
Definition at line 87 of file hexdump.c.
 {
     dumper_t *dumper = alloc_dumper();
     const char *p;
     int ch;
     if (ENABLE_HD
      && (!ENABLE_HEXDUMP || !applet_name[2])
     ) { /* we are "hd" */
         ch = 'C';
         goto hd_applet;
     }
     /* We cannot use getopt32: in hexdump options are cumulative.
      * E.g. "hexdump -C -C file" should dump each line twice */
     while ((ch = getopt(argc, argv, hexdump_opts)) > 0) {
         p = strchr(hexdump_opts, ch);
         if (!p)
             bb_show_usage();
         if ((p - hexdump_opts) < 5) {
             bb_dump_add(dumper, add_first);
             bb_dump_add(dumper, add_strings[(int)(p - hexdump_opts)]);
         }
         /* Save a little bit of space below by omitting the 'else's. */
         if (ch == 'C') {
  hd_applet:
             bb_dump_add(dumper, "\"%08.8_Ax\n\""); // final address line after dump
             //------------------- "address  "   8 * "xx "    "  "  8 * "xx "
             bb_dump_add(dumper, "\"%08.8_ax  \"8/1 \"%02x \"\"  \"8/1 \"%02x \"");
             //------------------- "  |ASCII...........|\n"
             bb_dump_add(dumper, "\"  |\"16/1 \"%_p\"\"|\n\"");
         }
         if (ch == 'e') {
             bb_dump_add(dumper, optarg);
         } /* else */
         if (ch == 'f') {
             bb_dump_addfile(dumper, optarg);
         } /* else */
         if (ch == 'n') {
             dumper->dump_length = xatoi_positive(optarg);
         } /* else */
         if (ch == 's') { /* compat: -s accepts hex numbers too */
             dumper->dump_skip = xstrtoull_range_sfx(
                 optarg,
                 /*base:*/ 0,
                 /*lo:*/ 0, /*hi:*/ OFF_T_MAX,
                 bkm_suffixes
             );
         } /* else */
         if (ch == 'v') {
             dumper->dump_vflag = ALL;
         }
     }
     if (!dumper->fshead) {
         bb_dump_add(dumper, add_first);
         bb_dump_add(dumper, "\"%07.7_ax \"8/2 \"%04x \"\"\n\"");
     }
     argv += optind;
     return bb_dump_dump(dumper, argv);
 }
References ALL, alloc_dumper(), applet_name, argc, argv, bb_dump_add(), bb_dump_addfile(), bb_dump_dump(), bb_show_usage(), bkm_suffixes, dumper, getopt(), OFF_T_MAX, optarg, optind, p, strchr(), and xatoi_positive().
Variable Documentation
ALIGN1
const char hexdump_opts [] ALIGN1 = "\"%07.7_Ax\n\"" static
Definition at line 82 of file hexdump.c.
ALIGN_PTR
const char* const add_strings [] ALIGN_PTR static
Initial value:
= {
    "\"%07.7_ax \"16/1 \"%03o \"\"\n\"",
    "\"%07.7_ax \"16/1 \"%3_c \"\"\n\"",
    "\"%07.7_ax \"8/2 \"  %05u \"\"\n\"",
    "\"%07.7_ax \"8/2 \" %06o \"\"\n\"",
    "\"%07.7_ax \"8/2 \"   %04x \"\"\n\"",
}
Definition at line 74 of file hexdump.c.