Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/seek_by_read.c File Reference
seek_by_read.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
void FAST_FUNC seek_by_read (int fd, off_t amount)
Function Documentation
seek_by_read()
void FAST_FUNC seek_by_read (int fd, off_t amount)
Definition at line 11 of file seek_by_read.c.
 {
     if (amount)
         bb_copyfd_exact_size(fd, -1, amount);
 }
References bb_copyfd_exact_size(), and fd.
Referenced by get_header_tar_bz2(), get_header_tar_gz(), get_header_tar_lzma(), get_header_tar_xz(), process_pax_hdr(), seek_by_jump(), and tar_main().