Fennix Userspace: Userspace/apps/base/busybox/libbb/platform.c File Reference
platform.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC strchrnul (const char *s, int c)
int FAST_FUNC usleep (unsigned usec)
int FAST_FUNC vasprintf (char **string_ptr, const char *format, va_list p)
int dprintf (int fd, const char *format,...)
void *FAST_FUNC memrchr (const void *s, int c, size_t n)
char *FAST_FUNC mkdtemp (char *template)
char *FAST_FUNC strcasestr (const char *s, const char *pattern)
char *FAST_FUNC strsep (char **stringp, const char *delim)
char *FAST_FUNC stpcpy (char *p, const char *to_add)
char *FAST_FUNC stpncpy (char *p, const char *to_add, size_t n)
ssize_t FAST_FUNC getline (char **lineptr, size_t *n, FILE *stream)
int ttyname_r (int fd, char *buf, size_t buflen)
Function Documentation
dprintf()
int dprintf (int fd, const char * format, ...)
Definition at line 66 of file platform.c.
 {
     va_list p;
     int r;
     char *string_ptr;
     va_start(p, format);
     r = vasprintf(&string_ptr, format, p);
     va_end(p);
     if (r >= 0) {
         r = full_write(fd, string_ptr, r);
         free(string_ptr);
     }
     return r;
 }
References fd, format(), free, full_write(), p, va_end, va_start, and vasprintf().
getline()
ssize_t FAST_FUNC getline (char ** lineptr, size_t * n, FILE * stream)
Definition at line 182 of file platform.c.
 {
     int ch;
     char *line = *lineptr;
     size_t alloced = *n;
     size_t len = 0;
     do {
         ch = fgetc(stream);
         if (ch == EOF)
             break;
         if (len + 1 >= alloced) {
             alloced += alloced/4 + 64;
             line = xrealloc(line, alloced);
         }
         line[len++] = ch;
     } while (ch != '\n');
     if (len == 0)
         return -1;
     line[len] = '\0';
     *lineptr = line;
     *n = alloced;
     return len;
 }
References EOF, fgetc, line, n, and xrealloc.
Referenced by __getgrent_a(), __getpwent_a(), fgetln(), fgetspent(), get_line_with_continuation(), getmntent_r(), getusershell(), setfiles_main(), and tsort_main().
memrchr()
void* FAST_FUNC memrchr (const void * s, int c, size_t n)
Definition at line 89 of file platform.c.
 {
     const char *start = s, *end = s;
     end += n - 1;
     while (end >= start) {
         if (*end == (char)c)
             return (void *) end;
         end--;
     }
     return NULL;
 }
References c, end, n, NULL, s, and start.
Referenced by begin_line(), and svlogd_main().
mkdtemp()
char* FAST_FUNC mkdtemp (char * template)
Definition at line 107 of file platform.c.
 {
     /* NB: on error, mktemp returns an empty string, not NULL */
     if (mktemp(template)[0] == '\0' || mkdir(template, 0700) != 0)
         return NULL;
     return template;
 }
References mkdir(), mktemp(), and NULL.
Referenced by make_tempdir(), mktemp_main(), and sh_mktmpdir().
stpcpy()
char* FAST_FUNC stpcpy (char * p, const char * to_add)
Definition at line 159 of file platform.c.
 {
     while ((*p = *to_add) != '\0') {
         p++;
         to_add++;
     }
     return p;
 }
References p.
stpncpy()
char* FAST_FUNC stpncpy (char * p, const char * to_add, size_t n)
Definition at line 170 of file platform.c.
 {
     while (n != 0 && (*p = *to_add) != '\0') {
         p++;
         to_add++;
         n--;
     }
     return p;
 }
References n, and p.
Referenced by sprint_status48().
strcasestr()
char* FAST_FUNC strcasestr (const char * s, const char * pattern)
Definition at line 118 of file platform.c.
 {
     int length = strlen(pattern);
     while (*s) {
         if (strncasecmp(s, pattern, length) == 0)
             return (char *)s;
         s++;
     }
     return 0;
 }
References pattern, s, strlen(), and strncasecmp.
strchrnul()
char* FAST_FUNC strchrnul (const char * s, int c)
Definition at line 12 of file platform.c.
 {
     while (*s != '\0' && *s != c)
         s++;
     return (char*)s;
 }
References c, and s.
strsep()
char* FAST_FUNC strsep (char ** stringp, const char * delim)
Definition at line 133 of file platform.c.
 {
     char *start = *stringp;
     char *ptr;
     if (!start)
         return NULL;
     if (!*delim)
         ptr = start + strlen(start);
     else {
         ptr = strpbrk(start, delim);
         if (!ptr) {
             *stringp = NULL;
             return start;
         }
     }
     *ptr = '\0';
     *stringp = ptr + 1;
     return start;
 }
References NULL, start, strlen(), and strpbrk().
Referenced by cut_main(), cutfields(), getlist(), init_exec(), load_pattern_list(), modprobe_main(), parse_speeds(), string_to_llist(), and update_passwd().
ttyname_r()
int ttyname_r (int fd, char * buf, size_t buflen)
Definition at line 211 of file platform.c.
 {
     int r;
     char path[sizeof("/proc/self/fd/%d") + sizeof(int)*3];
     if (!isatty(fd))
         return errno == EINVAL ? ENOTTY : errno;
     sprintf(path, "/proc/self/fd/%d", fd);
     r = readlink(path, buf, buflen);
     if (r < 0)
         return errno;
     if (r >= buflen)
         return ERANGE;
     buf[r] = '\0';
     return 0;
 }
References buf, buflen, EINVAL, ENOTTY, ERANGE, errno, fd, isatty(), readlink(), and sprintf().
Referenced by ttyname(), and xmalloc_ttyname().
usleep()
int FAST_FUNC usleep (unsigned usec)
Definition at line 21 of file platform.c.
 {
     struct timespec ts;
     ts.tv_sec = usec / 1000000u;
     ts.tv_nsec = (usec % 1000000u) * 1000u;
     /*
      * If a signal has non-default handler, nanosleep returns early.
      * Our version of usleep doesn't return early
      * if interrupted by such signals:
      */
     while (nanosleep(&ts, &ts) != 0)
         continue;
     return 0;
 }
References nanosleep(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by do_logging(), flashcp_main(), from_sys_clock(), get_logname(), msleep(), nmeter_main(), open_loop_on_busy(), pscan_main(), rtcwake_main(), runsvdir_main(), scriptreplay_main(), telnetd_main(), top_main(), and update_passwd().
vasprintf()
int FAST_FUNC vasprintf (char ** string_ptr, const char * format, va_list p)
Definition at line 38 of file platform.c.
 {
     int r;
     va_list p2;
     char buf[128];
     va_copy(p2, p);
     r = vsnprintf(buf, 128, format, p);
     va_end(p);
     /* Note: can't use xstrdup/xmalloc, they call vasprintf (us) on failure! */
     if (r < 128) {
         va_end(p2);
         *string_ptr = strdup(buf);
         return (*string_ptr ? r : -1);
     }
     *string_ptr = malloc(r+1);
     r = (*string_ptr ? vsnprintf(*string_ptr, r+1, format, p2) : -1);
     va_end(p2);
     return r;
 }
References buf, format(), malloc, p, strdup(), va_copy, va_end, and vsnprintf().
Referenced by dprintf().