Fennix Userspace: Userspace/musl/src/math/sinhf.c File Reference
sinhf.c File Reference
#include "libm.h"
Functions
float sinhf (float x)
Function Documentation
sinhf()
float sinhf (float x)
Definition at line 3 of file sinhf.c.
 {
     union {float f; uint32_t i;} u = {.f = x};
     uint32_t w;
     float t, h, absx;
     h = 0.5;
     if (u.i >> 31)
         h = -h;
     /* |x| */
     u.i &= 0x7fffffff;
     absx = u.f;
     w = u.i;
     /* |x| < log(FLT_MAX) */
     if (w < 0x42b17217) {
         t = expm1f(absx);
         if (w < 0x3f800000) {
             if (w < 0x3f800000 - (12<<23))
                 return x;
             return h*(2*t - t*t/(t+1));
         }
         return h*(t + t/(t+1));
     }
     /* |x| > logf(FLT_MAX) or nan */
     t = __expo2f(absx, 2*h);
     return t;
 }
References __expo2f(), expm1f(), f, h, i, t, w, and x.
Referenced by ccoshf(), csinhf(), and ctanhf().