Fennix: Userspace/apps/base/bash/lib/sh/pathcanon.c File Reference
pathcanon.c File Reference
#include <config.h>
#include <bashtypes.h>
#include <posixstat.h>
#include <filecntl.h>
#include <bashansi.h>
#include <stdio.h>
#include <chartypes.h>
#include <errno.h>
#include "shell.h"
Macros
#define DOUBLE_SLASH(p) ((p[0] == '/') && (p[1] == '/') && p[2] != '/')
Functions
static int _path_isdir (char *path)
char * sh_canonpath (char *path, int flags)
Variables
int errno
Macro Definition Documentation
DOUBLE_SLASH
#define DOUBLE_SLASH (p) ((p[0] == '/') && (p[1] == '/') && p[2] != '/')
Definition at line 101 of file pathcanon.c.
Function Documentation
_path_isdir()
static int _path_isdir (char * path) static
Definition at line 75 of file pathcanon.c.
 {
   int l;
   struct stat sb;
   /* This should leave errno set to the correct value. */
   errno = 0;
   l = stat (path, &sb) == 0 && S_ISDIR (sb.st_mode);
 #if defined (__CYGWIN__)
   if (l == 0)
     l = _is_cygdrive (path);
 #endif
   return l;
 }
References errno, l, S_ISDIR, stat::st_mode, and stat().
Referenced by sh_canonpath().
sh_canonpath()
char* sh_canonpath (char * path, int flags)
Definition at line 104 of file pathcanon.c.
 {
   char stub_char;
   char *result, *p, *q, *base, *dotdot;
   int rooted, double_slash_path;
   /* The result cannot be larger than the input PATH. */
   result = (flags & PATH_NOALLOC) ? path : savestring (path);
   /* POSIX.2 says to leave a leading `//' alone.  On cygwin, we skip over any
      leading `x:' (dos drive name). */
   if (rooted = ROOTEDPATH(path))
     {
       stub_char = DIRSEP;
 #if defined (__CYGWIN__)
       base = (ISALPHA((unsigned char)result[0]) && result[1] == ':') ? result + 3 : result + 1;
 #else
       base = result + 1;
 #endif
       double_slash_path = DOUBLE_SLASH (path);
       base += double_slash_path;
     }
   else
     {
       stub_char = '.';
 #if defined (__CYGWIN__)
       base = (ISALPHA((unsigned char)result[0]) && result[1] == ':') ? result + 2 : result;
 #else
       base = result;
 #endif
       double_slash_path = 0;
     }
   /*
    * invariants:
    *      base points to the portion of the path we want to modify
    *      p points at beginning of path element we're considering.
    *      q points just past the last path element we wrote (no slash).
    *      dotdot points just past the point where .. cannot backtrack
    *      any further (no slash).
    */
   p = q = dotdot = base;
   while (*p)
     {
       if (ISDIRSEP(p[0])) /* null element */
     p++;
       else if(p[0] == '.' && PATHSEP(p[1])) /* . and ./ */
     p += 1;     /* don't count the separator in case it is nul */
       else if (p[0] == '.' && p[1] == '.' && PATHSEP(p[2])) /* .. and ../ */
     {
       p += 2; /* skip `..' */
       if (q > dotdot)   /* can backtrack */
         {
           if (flags & PATH_CHECKDOTDOT)
         {
           char c;
           /* Make sure what we have so far corresponds to a valid
              path before we chop some of it off. */
           c = *q;
           *q = '\0';
           if (_path_isdir (result) == 0)
             {
               if ((flags & PATH_NOALLOC) == 0)
             free (result);
               return ((char *)NULL);
             }
           *q = c;
         }
           while (--q > dotdot && ISDIRSEP(*q) == 0)
         ;
         }
       else if (rooted == 0)
         {
           /* /.. is / but ./../ is .. */
           if (q != base)
         *q++ = DIRSEP;
           *q++ = '.';
           *q++ = '.';
           dotdot = q;
         }
     }
       else  /* real path element */
     {
       /* add separator if not at start of work portion of result */
       if (q != base)
         *q++ = DIRSEP;
       while (*p && (ISDIRSEP(*p) == 0))
         *q++ = *p++;
       /* Check here for a valid directory with _path_isdir. */
       if (flags & PATH_CHECKEXISTS)
         {
           char c;
           /* Make sure what we have so far corresponds to a valid
          path before we chop some of it off. */
           c = *q;
           *q = '\0';
           if (_path_isdir (result) == 0)
         {
           if ((flags & PATH_NOALLOC) == 0)
             free (result);
           return ((char *)NULL);
         }
           *q = c;
         }
     }
     }
   /* Empty string is really ``.'' or `/', depending on what we started with. */
   if (q == result)
     *q++ = stub_char;
   *q = '\0';
   /* If the result starts with `//', but the original path does not, we
      can turn the // into /.  Because of how we set `base', this should never
      be true, but it's a sanity check. */
   if (DOUBLE_SLASH(result) && double_slash_path == 0)
     {
       if (result[2] == '\0')    /* short-circuit for bare `//' */
     result[1] = '\0';
       else
     memmove (result, result + 1, strlen (result + 1) + 1);
     }
   return (result);
 }
References _path_isdir(), base, c, DIRSEP, DOUBLE_SLASH, flags, free, ISALPHA, ISDIRSEP, memmove, NULL, p, PATH_CHECKDOTDOT, PATH_CHECKEXISTS, PATH_NOALLOC, PATHSEP, ROOTEDPATH, savestring(), and strlen().
Referenced by get_bash_name(), realpath_builtin(), and set_pwd().
Variable Documentation
errno
int errno extern
Referenced by _path_isdir().