Fennix: Userspace/mlibc/tests/rtdl/scope1/libbar.c File Reference
libbar.c File Reference
Functions
char * foo (void)
char * foo_global (void)
char * bar ()
char * bar_calls_foo ()
char * bar_calls_foo_global ()
Function Documentation
bar()
char* bar ()
Definition at line 4 of file libbar.c.
             {
     return "bar";
 }
bar_calls_foo()
char* bar_calls_foo ()
Definition at line 8 of file libbar.c.
                       {
     return foo();
 }
References foo().
bar_calls_foo_global()
char* bar_calls_foo_global ()
Definition at line 12 of file libbar.c.
{
     return foo_global();
 }
References foo_global().
foo()
char* foo (void)
Definition at line 1 of file libfoo.c.
 { return 0; }
foo_global()
char* foo_global (void)
Definition at line 7 of file libfoo.c.
                    {
     return global;
 }
References global.
Referenced by bar_calls_foo_global().