Fennix: Userspace/mlibc/sysdeps/linux/generic/cxx-syscall.hpp File Reference
cxx-syscall.hpp File Reference
#include <errno.h>
#include <mlibc/tcb.hpp>
#include <mlibc/thread.hpp>
#include <mlibc-config.h>
#include <utility>
#include <sys/syscall.h>
#include <bits/syscall.h>
Namespaces
mlibc
Typedefs
using sc_word_t = __sc_word_t
Enumerations
enum class mlibc::sc_result_t : sc_word_t
Functions
sc_word_t __mlibc_do_asm_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6)
void __mlibc_do_cancel ()
sc_word_t mlibc::do_nargs_syscall (int sc)
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1)
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2)
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3)
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4)
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5)
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6)
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1)
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2)
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3)
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4)
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5)
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6)
sc_word_t mlibc::sc_cast (long x)
sc_word_t mlibc::sc_cast (const void *x)
template<typename... T>
sc_result_t mlibc::do_syscall (int sc, T... args)
int mlibc::sc_error (sc_result_t ret)
template<typename... T>
sc_result_t mlibc::do_cp_syscall (int sc, T... args)
template<typename T >
T mlibc::sc_int_result (sc_result_t ret)
template<typename T >
T * mlibc::sc_ptr_result (sc_result_t ret)
Typedef Documentation
sc_word_t
using sc_word_t = __sc_word_t
Definition at line 12 of file cxx-syscall.hpp.
Function Documentation
__mlibc_do_asm_cp_syscall()
sc_word_t __mlibc_do_asm_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6)
Referenced by mlibc::do_nargs_cp_syscall().
__mlibc_do_cancel()
void __mlibc_do_cancel ()
Definition at line 526 of file pthread-stubs.cpp.
{
     //TODO(geert): for now the same as pthread_exit()
     pthread_exit(PTHREAD_CANCELED);
 }
References PTHREAD_CANCELED, and pthread_exit().
Referenced by mlibc::do_cp_syscall(), pthread_setcancelstate(), pthread_setcanceltype(), pthread_testcancel(), and anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler().