Fennix Userspace: Userspace/apps/base/busybox/miscutils/i2c_tools.c File Reference
i2c_tools.c File Reference
#include "libbb.h"
#include <linux/i2c.h>
Data Structures
struct i2c_smbus_ioctl_data
struct i2c_rdwr_ioctl_data
Macros
#define I2CDUMP_NUM_REGS 256
#define I2CDETECT_MODE_AUTO 0
#define I2CDETECT_MODE_QUICK 1
#define I2CDETECT_MODE_READ 2
#define I2C_SLAVE 0x0703
#define I2C_SLAVE_FORCE 0x0706
#define I2C_FUNCS 0x0705
#define I2C_PEC 0x0708
#define I2C_SMBUS 0x0720
#define I2C_RDWR 0x0707
#define I2C_RDWR_IOCTL_MAX_MSGS 42
#define I2C_RDWR_IOCTL_MAX_MSGS_STR "42"
Functions
static ALWAYS_INLINE void * itoptr (int i)
static int32_t i2c_smbus_access (int fd, char read_write, uint8_t cmd, int size, union i2c_smbus_data *data)
static int i2c_bus_lookup (const char *bus_str)
static int i2c_dev_open (int i2cbus)
static void get_funcs_matrix (int fd, unsigned long *funcs)
static void confirm_or_abort (void)
static void confirm_action (int bus_addr, int mode, int data_addr, int pec)
Data Structure Documentation
i2c_smbus_ioctl_data
struct i2c_smbus_ioctl_data
Definition at line 90 of file i2c_tools.c.
Data Fields
__u8 command
union i2c_smbus_data * data
__u8 read_write
__u32 size
i2c_rdwr_ioctl_data
struct i2c_rdwr_ioctl_data
Definition at line 96 of file i2c_tools.c.
Data Fields
struct i2c_msg * msgs
__u32 nmsgs
Macro Definition Documentation
I2C_FUNCS
#define I2C_FUNCS 0x0705
Definition at line 84 of file i2c_tools.c.
I2C_PEC
#define I2C_PEC 0x0708
Definition at line 85 of file i2c_tools.c.
I2C_RDWR
#define I2C_RDWR 0x0707
Definition at line 87 of file i2c_tools.c.
I2C_RDWR_IOCTL_MAX_MSGS
#define I2C_RDWR_IOCTL_MAX_MSGS 42
Definition at line 88 of file i2c_tools.c.
I2C_RDWR_IOCTL_MAX_MSGS_STR
#define I2C_RDWR_IOCTL_MAX_MSGS_STR "42"
Definition at line 89 of file i2c_tools.c.
I2C_SLAVE
#define I2C_SLAVE 0x0703
Definition at line 82 of file i2c_tools.c.
I2C_SLAVE_FORCE
#define I2C_SLAVE_FORCE 0x0706
Definition at line 83 of file i2c_tools.c.
I2C_SMBUS
#define I2C_SMBUS 0x0720
Definition at line 86 of file i2c_tools.c.
I2CDETECT_MODE_AUTO
#define I2CDETECT_MODE_AUTO 0
Definition at line 72 of file i2c_tools.c.
I2CDETECT_MODE_QUICK
#define I2CDETECT_MODE_QUICK 1
Definition at line 73 of file i2c_tools.c.
I2CDETECT_MODE_READ
#define I2CDETECT_MODE_READ 2
Definition at line 74 of file i2c_tools.c.
I2CDUMP_NUM_REGS
#define I2CDUMP_NUM_REGS 256
Definition at line 70 of file i2c_tools.c.
Function Documentation
confirm_action()
static void confirm_action (int bus_addr, int mode, int data_addr, int pec) static
Definition at line 449 of file i2c_tools.c.
 {
     bb_simple_error_msg("WARNING! This program can confuse your I2C bus");
     /* Don't let the user break his/her EEPROMs */
     if (bus_addr >= 0x50 && bus_addr <= 0x57 && pec) {
         bb_simple_error_msg_and_die("this is I2C not smbus - using PEC on I2C "
             "devices may result in data loss, aborting");
     }
     if (mode == I2C_SMBUS_BYTE && data_addr >= 0 && pec)
         bb_simple_error_msg("WARNING! May interpret a write byte command "
             "with PEC as a write byte data command");
     if (pec)
         bb_simple_error_msg("PEC checking enabled");
     confirm_or_abort();
 }
References bb_simple_error_msg(), bb_simple_error_msg_and_die(), and confirm_or_abort().
confirm_or_abort()
static void confirm_or_abort (void) static
Definition at line 436 of file i2c_tools.c.
 {
     fprintf(stderr, "Continue? [y/N] ");
     if (!bb_ask_y_confirmation())
         bb_simple_error_msg_and_die("aborting");
 }
References bb_ask_y_confirmation(), bb_simple_error_msg_and_die(), fprintf(), and stderr.
Referenced by confirm_action().
get_funcs_matrix()
static void get_funcs_matrix (int fd, unsigned long * funcs) static
Definition at line 336 of file i2c_tools.c.
 {
     ioctl_or_perror_and_die(fd, I2C_FUNCS, funcs,
             "can't get adapter functionality matrix");
 }
References fd, funcs, I2C_FUNCS, and ioctl_or_perror_and_die().
i2c_bus_lookup()
static int i2c_bus_lookup (const char * bus_str) static
Definition at line 273 of file i2c_tools.c.
 {
     return xstrtou_range(bus_str, 10, 0, 0xfffff);
 }
i2c_dev_open()
static int i2c_dev_open (int i2cbus) static
Definition at line 316 of file i2c_tools.c.
 {
     char filename[sizeof("/dev/i2c-%d") + sizeof(int)*3];
     int fd;
     sprintf(filename, "/dev/i2c-%d", i2cbus);
     fd = open(filename, O_RDWR);
     if (fd < 0) {
         if (errno == ENOENT) {
             filename[8] = '/'; /* change to "/dev/i2c/%d" */
             fd = xopen(filename, O_RDWR);
         } else {
             bb_perror_msg_and_die("can't open '%s'", filename);
         }
     }
     return fd;
 }
References bb_perror_msg_and_die(), ENOENT, errno, fd, filename, O_RDWR, open(), sprintf(), and xopen().
i2c_smbus_access()
static int32_t i2c_smbus_access (int fd, char read_write, uint8_t cmd, int size, union i2c_smbus_data * data) static
Definition at line 110 of file i2c_tools.c.
 {
     struct i2c_smbus_ioctl_data args;
     args.read_write = read_write;
     args.command = cmd;
     args.size = size;
     args.data = data;
     return ioctl(fd, I2C_SMBUS, &args);
 }
References cmd, i2c_smbus_ioctl_data::data, fd, I2C_SMBUS, ioctl(), i2c_smbus_ioctl_data::read_write, and size.
itoptr()
static ALWAYS_INLINE void* itoptr (int i) static
Definition at line 105 of file i2c_tools.c.
 {
     return (void*)(intptr_t)i;
 }
References i.