Fennix Userspace: Userspace/apps/base/busybox/miscutils/inotifyd.c File Reference
inotifyd.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <sys/inotify.h>
Macros
#define eventbuf bb_common_bufsiz1
Enumerations
enum { MASK_BITS = sizeof(mask_names) - 1 }
Functions
int inotifyd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char mask_names[] ALIGN1
Macro Definition Documentation
eventbuf
#define eventbuf bb_common_bufsiz1
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MASK_BITS
Definition at line 91 of file inotifyd.c.
      {
     MASK_BITS = sizeof(mask_names) - 1
 };
Function Documentation
inotifyd_main()
int inotifyd_main (int argc, char ** argv)
Definition at line 96 of file inotifyd.c.
 {
     int n;
     unsigned mask;
     struct pollfd pfd;
     char **watches; // names of files being watched
     const char *args[5];
     // sanity check: agent and at least one watch must be given
     if (!argv[1] || !argv[2])
         bb_show_usage();
     argv++;
     // inotify_add_watch will number watched files
     // starting from 1, thus watches[0] is unimportant,
     // and 1st file name is watches[1].
     watches = argv;
     args[0] = *argv;
     args[4] = NULL;
     argc -= 2; // number of files we watch
     // open inotify
     pfd.fd = inotify_init();
     if (pfd.fd < 0)
         bb_simple_perror_msg_and_die("no kernel support");
     // setup watches
     while (*++argv) {
         char *path = *argv;
         char *masks = strchr(path, ':');
         mask = 0x0fff; // assuming we want all non-kernel events
         // if mask is specified ->
         if (masks) {
             *masks = '\0'; // split path and mask
             // convert mask names to mask bitset
             mask = 0;
             while (*++masks) {
                 const char *found;
                 found = memchr(mask_names, *masks, MASK_BITS);
                 if (found)
                     mask |= (1 << (found - mask_names));
             }
         }
         // add watch
         n = inotify_add_watch(pfd.fd, path, mask);
         if (n < 0)
             bb_perror_msg_and_die("add watch (%s) failed", path);
         //bb_error_msg("added %d [%s]:%4X", n, path, mask);
     }
     // setup signals
     bb_signals(BB_FATAL_SIGS, record_signo);
     // do watch
     pfd.events = POLLIN;
     while (1) {
         int len;
         void *buf;
         struct inotify_event *ie;
  again:
         if (bb_got_signal)
             break;
         n = poll(&pfd, 1, -1);
         // Signal interrupted us?
         if (n < 0 && errno == EINTR)
             goto again;
         // Under Linux, above if() is not necessary.
         // Non-fatal signals, e.g. SIGCHLD, when set to SIG_DFL,
         // are not interrupting poll().
         // Thus we can just break if n <= 0 (see below),
         // because EINTR will happen only on SIGTERM et al.
         // But this might be not true under other Unixes,
         // and is generally way too subtle to depend on.
         if (n <= 0) // strange error?
             break;
         // read out all pending events
         // (NB: len must be int, not ssize_t or long!)
 #define eventbuf bb_common_bufsiz1
         setup_common_bufsiz();
         xioctl(pfd.fd, FIONREAD, &len);
         ie = buf = (len <= COMMON_BUFSIZE) ? eventbuf : xmalloc(len);
         len = full_read(pfd.fd, buf, len);
         // process events. N.B. events may vary in length
         while (len > 0) {
             int i;
             // cache relevant events mask
             unsigned m = ie->mask & ((1 << MASK_BITS) - 1);
             if (m) {
                 char events[MASK_BITS + 1];
                 char *s = events;
                 for (i = 0; i < MASK_BITS; ++i, m >>= 1) {
                     if ((m & 1) && (mask_names[i] != '\0'))
                         *s++ = mask_names[i];
                 }
                 *s = '\0';
                 if (LONE_CHAR(args[0], '-')) {
                     /* "inotifyd - FILE": built-in echo */
                     printf(ie->len ? "%s\t%s\t%s\n" : "%s\t%s\n", events,
                             watches[ie->wd],
                             ie->name);
                     fflush(stdout);
                 } else {
 //                  bb_error_msg("exec %s %08X\t%s\t%s\t%s", args[0],
 //                      ie->mask, events, watches[ie->wd], ie->len ? ie->name : "");
                     args[1] = events;
                     args[2] = watches[ie->wd];
                     args[3] = ie->len ? ie->name : NULL;
                     spawn_and_wait((char **)args);
                 }
                 // we are done if all files got final x event
                 if (ie->mask & 0x8000) {
                     if (--argc <= 0)
                         goto done;
                     inotify_rm_watch(pfd.fd, ie->wd);
                 }
             }
             // next event
             i = sizeof(struct inotify_event) + ie->len;
             len -= i;
             ie = (void*)((char*)ie + i);
         }
         if (eventbuf != buf)
             free(buf);
     } // while (1)
  done:
     return bb_got_signal;
 }
References argc, argv, BB_FATAL_SIGS, bb_got_signal, bb_perror_msg_and_die(), bb_show_usage(), bb_signals(), bb_simple_perror_msg_and_die(), buf, done, EINTR, errno, eventbuf, events, fflush(), FIONREAD, found, free, full_read(), i, inotify_add_watch(), inotify_init(), inotify_rm_watch(), inotify_event::len, LONE_CHAR, inotify_event::mask, MASK_BITS, memchr(), n, inotify_event::name, NULL, pfd, poll(), POLLIN, printf(), record_signo(), s, spawn_and_wait(), stdout, strchr(), inotify_event::wd, xioctl, and xmalloc.
Variable Documentation
ALIGN1
const char mask_names [] ALIGN1 static
Initial value:
=
    "a"
    "c"
    "e"
    "w"
    "0"
    "r"
    "m"
    "y"
    "n"
    "d"
    "D"
    "M"
    "\0"
    "u"
    "o"
    "x"
Definition at line 72 of file inotifyd.c.