Fennix Userspace: Userspace/apps/base/busybox/miscutils/runlevel.c File Reference
runlevel.c File Reference
#include "libbb.h"
Functions
int runlevel_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
runlevel_main()
int runlevel_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 43 of file runlevel.c.
 {
     struct utmpx *ut;
     char prev;
     if (argv[1]) utmpxname(argv[1]);
     setutxent();
     while ((ut = getutxent()) != NULL) {
         if (ut->ut_type == RUN_LVL) {
             prev = ut->ut_pid / 256;
             if (prev == 0) prev = 'N';
             printf("%c %c\n", prev, ut->ut_pid % 256);
             if (ENABLE_FEATURE_CLEAN_UP)
                 endutxent();
             return 0;
         }
     }
     puts("unknown");
     if (ENABLE_FEATURE_CLEAN_UP)
         endutxent();
     return 1;
 }
References argv, endutxent(), getutxent(), NULL, printf(), puts(), RUN_LVL, setutxent(), utmpx::ut_pid, and utmpx::ut_type.