Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/d_event.c File Reference
d_event.c File Reference
#include <stdlib.h>
#include "d_event.h"
Macros
#define MAXEVENTS 64
Functions
void D_PostEvent (event_t *ev)
event_t * D_PopEvent (void)
Variables
static event_t events [MAXEVENTS]
static int eventhead
static int eventtail
Macro Definition Documentation
MAXEVENTS
#define MAXEVENTS 64
Definition at line 25 of file d_event.c.
Function Documentation
D_PopEvent()
event_t* D_PopEvent (void)
Definition at line 43 of file d_event.c.
 {
     event_t *result;
     // No more events waiting.
     if (eventtail == eventhead)
     {
         return NULL;
     }
     result = &events[eventtail];
     // Advance to the next event in the queue.
     eventtail = (eventtail + 1) % MAXEVENTS;
     return result;
 }
References eventhead, events, eventtail, MAXEVENTS, and NULL.
Referenced by D_ProcessEvents().
D_PostEvent()
void D_PostEvent (event_t * ev)
Definition at line 35 of file d_event.c.
 {
     events[eventhead] = *ev;
     eventhead = (eventhead + 1) % MAXEVENTS;
 }
References eventhead, events, and MAXEVENTS.
Referenced by I_GetEvent(), and I_UpdateJoystick().
Variable Documentation
eventhead
int eventhead static
Definition at line 28 of file d_event.c.
Referenced by D_PopEvent(), and D_PostEvent().
events
event_t events[MAXEVENTS] static
Definition at line 27 of file d_event.c.
Referenced by D_PopEvent(), D_PostEvent(), and inotifyd_main().
eventtail
int eventtail static
Definition at line 29 of file d_event.c.
Referenced by D_PopEvent().