Fennix Userspace: Userspace/apps/base/busybox/procps/watch.c File Reference
watch.c File Reference
#include "libbb.h"
Macros
#define ESC "\033"
Functions
int watch_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
ESC
#define ESC "\033"
Definition at line 39 of file watch.c.
Function Documentation
watch_main()
int watch_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 52 of file watch.c.
 {
     duration_t period;
     char *period_str = (char*) "2";
     unsigned opt;
     unsigned width, new_width;
     char *header;
     char *cmd;
 #if 0 // maybe ENABLE_DESKTOP?
     // procps3 compat - "echo TEST | watch cat" doesn't show TEST:
     close(STDIN_FILENO);
     xopen("/dev/null", O_RDONLY);
 #endif
     // "+": stop at first non-option (procps 3.x only); -n NUM
     // at least one param
     opt = getopt32(argv, "^+" "dtn:" "\0" "-1", &period_str);
     argv += optind;
     // watch from both procps 2.x and 3.x does concatenation. Example:
     // watch ls -l "a /tmp" "2>&1" - ls won't see "a /tmp" as one param
     cmd = *argv;
     while (*++argv)
         cmd = xasprintf("%s %s", cmd, *argv); // leaks cmd
     period = parse_duration_str(period_str);
     width = (unsigned)-1; // make sure first time new_width != width
     header = NULL;
     while (1) {
         /* home; clear to the end of screen */
         printf(ESC"[H" ESC"[J");
         if (!(opt & 0x2)) { // no -t
             const unsigned time_len = sizeof("1234-67-90 23:56:89");
             // STDERR_FILENO is procps3 compat:
             // "watch ls 2>/dev/null" does not detect tty size
             new_width = get_terminal_width(STDERR_FILENO);
             if (new_width != width) {
                 width = new_width;
                 free(header);
                 header = xasprintf("Every"
                     " %"IF_FLOAT_DURATION(".1")DURATION_FMT"s:"
                     " %-*s",
                     period,
                     (int)width, cmd
                 );
             }
             if (time_len < width) {
                 strftime_YYYYMMDDHHMMSS(
                     header + width - time_len,
                     time_len,
                     /*time_t*:*/ NULL
                 );
             }
             // compat: empty line between header and cmd output
             printf("%s\n\n", header);
         }
         fflush_all();
         // TODO: 'real' watch pipes cmd's output to itself
         // and does not allow it to overflow the screen
         // (taking into account linewrap!)
         system(cmd);
         sleep_for_duration(period);
     }
     return 0; // gcc thinks we can reach this :)
 }
References argv, close(), cmd, DURATION_FMT, ESC, fflush_all(), free, get_terminal_width(), getopt32(), NULL, O_RDONLY, opt, optind, parse_duration_str(), printf(), sleep_for_duration, STDERR_FILENO, STDIN_FILENO, strftime_YYYYMMDDHHMMSS(), system(), width, xasprintf(), and xopen().