Fennix: Kernel/include_std/stdio.h File Reference
stdio.h File Reference
#include <types.h>
Data Structures
struct FILE
Macros
#define FILENAME_MAX 4096
#define stdin stdin
#define stdout stdout
#define stderr stderr
Functions
int printf (const char *format,...) __attribute__((format(__printf__
int int vprintf (const char *format, va_list arg) __attribute__((format(__printf__
int int int sprintf (char *s, const char *format,...) __attribute__((format(__printf__
int int int int vsprintf (char *s, const char *format, va_list arg) __attribute__((format(__printf__
int int int int int snprintf (char *s, size_t count, const char *format,...) __attribute__((format(__printf__
int int int int int int vsnprintf (char *s, size_t count, const char *format, va_list arg) __attribute__((format(__printf__
int int int int int int int asprintf (char **strp, const char *fmt,...) __attribute__((format(__printf__
int int int int int int int int vasprintf (char **strp, const char *fmt, va_list ap) __attribute__((format(__printf__
int int int int int int int int int fprintf (FILE *stream, const char *format,...) __attribute__((format(__printf__
int int int int int int int int int int fputs (const char *s, FILE *stream)
Variables
FILE * stdin
FILE * stdout
FILE * stderr
Data Structure Documentation
FILE
struct FILE
Definition at line 27 of file stdio.h.
Data Fields
int st
Macro Definition Documentation
FILENAME_MAX
#define FILENAME_MAX 4096
Definition at line 25 of file stdio.h.
stderr
#define stderr stderr
Definition at line 38 of file stdio.h.
stdin
#define stdin stdin
Definition at line 36 of file stdio.h.
stdout
#define stdout stdout
Definition at line 37 of file stdio.h.
Function Documentation
asprintf()
int int int int int int int asprintf (char ** strp, const char * fmt, ...)
fprintf()
int int int int int int int int int fprintf (FILE * stream, const char * format, ...)
Referenced by __assert_fail(), addmntent(), cag_option_print(), cag_option_print_letters(), cag_option_print_name(), cag_option_print_value(), DonutOverrun(), EV_DoDonut(), EV_VerticalDoor(), herror(), I_CDMusPrintStartup(), I_Error(), M_Episode(), pad(), PadRejectArray(), psignal(), putgrent(), putpwent(), putspent(), rpmalloc_dump_statistics(), SaveDefaultCollection(), saveg_read8(), saveg_write8(), SpechitOverrun(), vwarn(), vwarnx(), wprintf_core(), WriteTimidityConfig(), and Z_FileDumpHeap().
fputs()
int int int int int int int int int int fputs (const char * s, FILE * stream)
Definition at line 95 of file stdio.cpp.
 {
     for (const char *c = s; *c; c++)
         uart_wrapper(*c, NULL);
     return 0;
 }
References NULL, and uart_wrapper().
Referenced by __getopt_msg(), cag_option_print(), puts(), and vwarn().
printf()
int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
snprintf()
int int int int int snprintf (char * s, size_t count, const char * format, ...)
An implementation of the C standard's snprintf/vsnprintf
Parameters
s An array in which to store the formatted string. It must be large enough to fit either the entire formatted output, or at least n characters. Alternatively, it can be NULL, in which case nothing will be printed, and only the number of characters which could have been printed is tallied and returned.
n The maximum number of characters to write to the array, including a terminating null character
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters that COULD have been written into s, not counting the terminating null character. A value equal or larger than n indicates truncation. Only when the returned value is non-negative and less than n, the null-terminated string has been fully and successfully printed.
sprintf()
int int int sprintf (char * s, const char * format, ...)
An implementation of the C standard's sprintf/vsprintf
Note
For security considerations (the potential for exceeding the buffer bounds), please consider using the size-constrained variant, snprintf / vsnprintf , instead.
Parameters
s An array in which to store the formatted string. It must be large enough to fit the formatted output!
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters written into s, not counting the terminating null character
vasprintf()
int int int int int int int int vasprintf (char ** strp, const char * fmt, va_list ap)
Referenced by asprintf().
vprintf()
int int vprintf (const char * format, va_list arg)
vsnprintf()
int int int int int int vsnprintf (char * s, size_t count, const char * format, va_list arg)
vsprintf()
int int int int vsprintf (char * s, const char * format, va_list arg)
Variable Documentation
stderr
FILE* stderr extern
Definition at line 28 of file stdio.cpp.
stdin
FILE* stdin extern
Definition at line 26 of file stdio.cpp.
stdout
FILE* stdout extern
Definition at line 27 of file stdio.cpp.