Fennix: Userspace/apps/base/busybox/procps/pgrep.c File Reference
pgrep.c File Reference
#include "libbb.h"
#include "xregex.h"
Macros
#define pgrep (ENABLE_PGREP && (!ENABLE_PKILL || applet_name[1] == 'g'))
#define pkill (ENABLE_PKILL && (!ENABLE_PGREP || applet_name[1] == 'k'))
#define OPT_INVERT (opt & (1 << OPTBIT_V))
#define OPT_LIST (opt & (1 << OPTBIT_L))
#define OPT_LISTFULL (opt & (1 << OPTBIT_A))
#define OPT_FULL (opt & (1 << OPTBIT_F))
#define OPT_ANCHOR (opt & (1 << OPTBIT_X))
#define OPT_FIRST (opt & (1 << OPTBIT_O))
#define OPT_LAST (opt & (1 << OPTBIT_N))
#define OPT_ECHO (opt & (1 << OPTBIT_E))
#define OPT_SID (opt & (1 << OPTBIT_S))
#define OPT_PPID (opt & (1 << OPTBIT_P))
#define re_buffer (Z.re_buffer)
#define re_match (Z.re_match)
Enumerations
enum {
OPTBIT_V = 0 , OPTBIT_L , OPTBIT_A , OPTBIT_F ,
OPTBIT_X , OPTBIT_O , OPTBIT_N , OPTBIT_E ,
OPTBIT_S , OPTBIT_P
}
Functions
static void act (unsigned pid, char *cmd, int signo)
int pgrep_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPT_ANCHOR
#define OPT_ANCHOR (opt & (1 << OPTBIT_X))
Definition at line 85 of file pgrep.c.
OPT_ECHO
#define OPT_ECHO (opt & (1 << OPTBIT_E))
Definition at line 88 of file pgrep.c.
OPT_FIRST
#define OPT_FIRST (opt & (1 << OPTBIT_O))
Definition at line 86 of file pgrep.c.
OPT_FULL
#define OPT_FULL (opt & (1 << OPTBIT_F))
Definition at line 84 of file pgrep.c.
OPT_INVERT
#define OPT_INVERT (opt & (1 << OPTBIT_V))
Definition at line 81 of file pgrep.c.
OPT_LAST
#define OPT_LAST (opt & (1 << OPTBIT_N))
Definition at line 87 of file pgrep.c.
OPT_LIST
#define OPT_LIST (opt & (1 << OPTBIT_L))
Definition at line 82 of file pgrep.c.
OPT_LISTFULL
#define OPT_LISTFULL (opt & (1 << OPTBIT_A))
Definition at line 83 of file pgrep.c.
OPT_PPID
#define OPT_PPID (opt & (1 << OPTBIT_P))
Definition at line 90 of file pgrep.c.
OPT_SID
#define OPT_SID (opt & (1 << OPTBIT_S))
Definition at line 89 of file pgrep.c.
pgrep
#define pgrep (ENABLE_PGREP && (!ENABLE_PKILL || applet_name[1] == 'g'))
Definition at line 64 of file pgrep.c.
pkill
#define pkill (ENABLE_PKILL && (!ENABLE_PGREP || applet_name[1] == 'k'))
Definition at line 65 of file pgrep.c.
re_buffer
#define re_buffer (Z.re_buffer)
re_match
#define re_match (Z.re_match)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTBIT_V
OPTBIT_L
OPTBIT_A
OPTBIT_F
OPTBIT_X
OPTBIT_O
OPTBIT_N
OPTBIT_E
OPTBIT_S
OPTBIT_P
Definition at line 67 of file pgrep.c.
      {
     /* "vlafxones:+P:+" */
     OPTBIT_V = 0, /* must be first, we need OPT_INVERT = 0/1 */
     OPTBIT_L,
     OPTBIT_A,
     OPTBIT_F,
     OPTBIT_X,
     OPTBIT_O,
     OPTBIT_N,
     OPTBIT_E, /* should be pkill-only, do we care? */
     OPTBIT_S,
     OPTBIT_P,
 };
Function Documentation
act()
static void act (unsigned pid, char * cmd, int signo) static
Definition at line 92 of file pgrep.c.
 {
     if (pgrep) {
         if (option_mask32 & ((1 << OPTBIT_L)|(1 << OPTBIT_A))) /* -l or -a */
             printf("%u %s\n", pid, cmd);
         else
             printf("%u\n", pid);
     } else {
         kill(pid, signo);
         if (option_mask32 & (1 << OPTBIT_E)) {
             printf("%s killed (pid %u)\n", cmd, pid);
         }
     }
 }
References cmd, kill(), OPTBIT_A, OPTBIT_E, OPTBIT_L, option_mask32, pgrep, pid, and printf.
Referenced by pgrep_main().
pgrep_main()
int pgrep_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 108 of file pgrep.c.
 {
     unsigned pid;
     int signo;
     unsigned opt;
     int scan_mask;
     int matched_pid;
     int sid2match, ppid2match;
     char *cmd_last;
     procps_status_t *proc;
     /* These are initialized to 0 */
     struct {
         regex_t re_buffer;
         regmatch_t re_match[1];
     } Z;
 #define re_buffer (Z.re_buffer)
 #define re_match  (Z.re_match )
     memset(&Z, 0, sizeof(Z));
     /* Parse -SIGNAL for pkill. Must be first option, if present */
     signo = SIGTERM;
     if (pkill && argv[1] && argv[1][0] == '-') {
         int temp = get_signum(argv[1]+1);
         if (temp != -1) {
             signo = temp;
             argv++;
         }
     }
     /* Parse remaining options */
     ppid2match = -1;
     sid2match = -1;
     opt = getopt32(argv, "vlafxones:+P:+", &sid2match, &ppid2match);
     argv += optind;
     if (pkill && OPT_LIST) { /* -l: print the whole signal list */
         print_signames();
         return 0;
     }
     pid = getpid();
     if (sid2match == 0)
         sid2match = getsid(pid);
     scan_mask = PSSCAN_COMM | PSSCAN_ARGV0;
     if (OPT_FULL)
         scan_mask |= PSSCAN_ARGVN;
     /* One pattern is required, if no -s and no -P */
     if ((sid2match & ppid2match) < 0 && (!argv[0] || argv[1]))
         bb_show_usage();
     if (argv[0])
         xregcomp(&re_buffer, argv[0], OPT_ANCHOR ? REG_EXTENDED : (REG_EXTENDED|REG_NOSUB));
     matched_pid = 0;
     cmd_last = NULL;
     proc = NULL;
     while ((proc = procps_scan(proc, scan_mask)) != NULL) {
         char *cmd;
         int cmdlen, match;
         if (proc->pid == pid)
             continue;
         if (!OPT_INVERT) {
             /* Quickly reject -sN -PN mismatches... unless -v */
             if (ppid2match >= 0 && ppid2match != proc->ppid)
                 continue;
             if (sid2match >= 0 && sid2match != proc->sid)
                 continue;
         }
         cmdlen = -1;
         cmd = proc->argv0;
         if (!cmd) {
             cmd = proc->comm;
         } else {
             int i = proc->argv_len;
             if (!OPT_LISTFULL)
                 cmdlen = strlen(cmd); /* not -a: find first NUL */
             /*
              * "sleep 11" looks like "sleep""\0""11""\0" in argv0.
              * Make sure last "\0" does not get converted to " ":
              */
             if (i && cmd[i-1] == '\0')
                 i--;
             while (--i >= 0) {
                 if ((unsigned char)cmd[i] < ' ')
                     cmd[i] = ' ';
             }
         }
         if (OPT_INVERT) {
             /* "pgrep -v -P1 firefox" means "not (ppid=1 AND name=firefox)"
              * or equivalently "ppid!=1 OR name!=firefox".
              * Check the first condition and if true, skip matching.
              */
             if (ppid2match >= 0 && ppid2match != proc->ppid)
                 goto got_it;
             if (sid2match >= 0 && sid2match != proc->sid)
                 goto got_it;
         }
         match = !argv[0]; /* if no PATTERN, then it's a match, else... */
         if (!match) {
  again:
             match = (regexec(&re_buffer, cmd, 1, re_match, 0) == 0);
             if (!match && cmd != proc->comm) {
                 /* if argv[] did not match, try comm */
                 cmdlen = -1;
                 cmd = proc->comm;
                 goto again;
             }
             if (match && OPT_ANCHOR) {
                 /* -x requires full string match */
                 match = (re_match[0].rm_so == 0 && cmd[re_match[0].rm_eo] == '\0');
             }
         }
         /* NB: OPT_INVERT is always 0 or 1 */
         if (match ^ OPT_INVERT) {
  got_it:
             matched_pid = proc->pid;
             if (OPT_LAST) {
                 free(cmd_last);
                 cmd_last = xstrdup(cmd);
                 continue;
             }
             if (cmdlen >= 0)
                 cmd[cmdlen] = '\0';
             act(proc->pid, cmd, signo);
             if (OPT_FIRST)
                 break;
         }
     }
     if (cmd_last) {
         act(matched_pid, cmd_last, signo);
         if (ENABLE_FEATURE_CLEAN_UP)
             free(cmd_last);
     }
     return matched_pid == 0; /* return 1 if no processes listed/signaled */
 }
References act(), argv, bb_show_usage(), cmd, proc::comm, free, get_signum(), getopt32(), getpid(), getsid(), i, match(), memset, NULL, opt, OPT_ANCHOR, OPT_FIRST, OPT_FULL, OPT_INVERT, OPT_LAST, OPT_LIST, OPT_LISTFULL, optind, proc::pid, pid, pkill, print_signames(), procps_scan(), PSSCAN_ARGV0, PSSCAN_ARGVN, PSSCAN_COMM, re_buffer, re_match, REG_EXTENDED, REG_NOSUB, regexec, SIGTERM, strlen(), xregcomp, and xstrdup().