Fennix: Userspace/musl/include/utmpx.h File Reference
utmpx.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct utmpx
struct utmpx.ut_exit
Macros
#define __NEED_pid_t
#define __NEED_time_t
#define __NEED_suseconds_t
#define __NEED_struct_timeval
#define EMPTY 0
#define RUN_LVL 1
#define BOOT_TIME 2
#define NEW_TIME 3
#define OLD_TIME 4
#define INIT_PROCESS 5
#define LOGIN_PROCESS 6
#define USER_PROCESS 7
#define DEAD_PROCESS 8
Functions
void endutxent (void)
struct utmpx * getutxent (void)
struct utmpx * getutxid (const struct utmpx *)
struct utmpx * getutxline (const struct utmpx *)
struct utmpx * pututxline (const struct utmpx *)
void setutxent (void)
Data Structure Documentation
utmpx
struct utmpx
Definition at line 17 of file utmpx.h.
Data Fields
char __unused[20]
short __ut_pad1
int __ut_pad2
unsigned ut_addr_v6[4]
struct utmpx ut_exit
char ut_host[256]
char ut_id[4]
char ut_line[32]
pid_t ut_pid
int ut_session
struct timeval ut_tv
short ut_type
char ut_user[32]
utmpx.ut_exit
struct utmpx.ut_exit
Definition at line 25 of file utmpx.h.
Data Fields
short __e_exit
short __e_termination
Macro Definition Documentation
__NEED_pid_t
#define __NEED_pid_t
Definition at line 10 of file utmpx.h.
__NEED_struct_timeval
#define __NEED_struct_timeval
Definition at line 13 of file utmpx.h.
__NEED_suseconds_t
#define __NEED_suseconds_t
Definition at line 12 of file utmpx.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 11 of file utmpx.h.
BOOT_TIME
#define BOOT_TIME 2
Definition at line 55 of file utmpx.h.
DEAD_PROCESS
#define DEAD_PROCESS 8
Definition at line 61 of file utmpx.h.
EMPTY
#define EMPTY 0
Definition at line 53 of file utmpx.h.
INIT_PROCESS
#define INIT_PROCESS 5
Definition at line 58 of file utmpx.h.
LOGIN_PROCESS
#define LOGIN_PROCESS 6
Definition at line 59 of file utmpx.h.
NEW_TIME
#define NEW_TIME 3
Definition at line 56 of file utmpx.h.
OLD_TIME
#define OLD_TIME 4
Definition at line 57 of file utmpx.h.
RUN_LVL
#define RUN_LVL 1
Definition at line 54 of file utmpx.h.
USER_PROCESS
#define USER_PROCESS 7
Definition at line 60 of file utmpx.h.
Function Documentation
endutxent()
void endutxent (void)
Definition at line 6 of file utmpx.c.
 {
 }
Referenced by runlevel_main(), update_utmp(), wall_main(), who_main(), and write_new_utmp().
getutxent()
struct utmpx* getutxent (void)
Definition at line 14 of file utmpx.c.
 {
     return NULL;
 }
References NULL.
Referenced by runlevel_main(), update_utmp(), uptime_main(), wall_main(), and who_main().
getutxid()
struct utmpx* getutxid (const struct utmpx * ut)
Definition at line 19 of file utmpx.c.
 {
     return NULL;
 }
References NULL.
getutxline()
struct utmpx* getutxline (const struct utmpx * ut)
Definition at line 24 of file utmpx.c.
 {
     return NULL;
 }
References NULL.
pututxline()
struct utmpx* pututxline (const struct utmpx * ut)
Definition at line 29 of file utmpx.c.
 {
     return NULL;
 }
References NULL.
Referenced by update_utmp(), and write_new_utmp().
setutxent()
void setutxent (void)
Definition at line 10 of file utmpx.c.
 {
 }
Referenced by runlevel_main(), update_utmp(), wall_main(), who_main(), and write_new_utmp().