Fennix: Userspace/apps/base/bash/CWRU/misc/errlist.c File Reference
errlist.c File Reference
#include <stdio.h>
#include <errno.h>
Functions
char * strerror ()
int main (int c, char **v)
programming_error (char *a, int b)
fatal_error ()
Variables
int sys_nerr
Function Documentation
fatal_error()
fatal_error ()
Definition at line 55 of file errlist.c.
 {
 }
Referenced by allocerr().
main()
int main (int c, char ** v)
Definition at line 31 of file errlist.c.
 {
     int i, n;
     if (c == 1) {
         for (i = 1; i < sys_nerr; i++)
             printf("%d --> %s\n", i, strerror(i));
     } else {
         for (i = 1; i < c; i++) {
             n = atoi(v[i]);
             printf("%d --> %s\n", n, strerror(n));
         }
     }
     exit (0);
 }
References atoi(), c, exit(), i, n, printf, strerror(), and sys_nerr.
programming_error()
programming_error (char * a, int b)
Definition at line 49 of file errlist.c.
 {
 }
Referenced by cprintf(), describe_pid(), main(), make_redirection(), notify_of_job_status(), trap_handler(), and wait_for().
strerror()
char* strerror ()
Referenced by __dls3(), _remove_directory(), accept_builtin(), async_redirect_stdin(), dolink(), fdflags_builtin(), file_error(), file_head(), get_working_directory(), getconf_print(), getflags(), getfloatmax(), getstat(), head_builtin(), logname_builtin(), main(), make_path(), mkdir_builtin(), mkfifo_builtin(), PrintfAgent< F >::operator()(), perror(), printf_core(), printsome(), push_builtin(), realpath_builtin(), redirection_error(), rm_file(), rmdir_builtin(), run_cmd(), run_test(), set_locale_var(), setone(), setpgid_builtin(), sh_ttyerror(), sh_wrerror(), shell_execve(), socket_setup(), stat_builtin(), stdcat(), strerror_r(), sys_error(), uname_builtin(), unlink_builtin(), wait_for(), and wprintf_core().
Variable Documentation
sys_nerr
int sys_nerr extern
Referenced by main(), and strerror().