Fennix: Userspace/musl/src/fenv/feupdateenv.c File Reference
feupdateenv.c File Reference
#include <fenv.h>
Functions
int feupdateenv (const fenv_t *envp)
Function Documentation
feupdateenv()
int feupdateenv (const fenv_t * envp)
Definition at line 3 of file feupdateenv.c.
 {
     int ex = fetestexcept(FE_ALL_EXCEPT);
     fesetenv(envp);
     feraiseexcept(ex);
     return 0;
 }
References envp, FE_ALL_EXCEPT, feraiseexcept(), fesetenv(), and fetestexcept().