Fennix: Userspace/musl/include/sys/statvfs.h File Reference
statvfs.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct statvfs
Macros
#define __NEED_fsblkcnt_t
#define __NEED_fsfilcnt_t
#define ST_RDONLY 1
#define ST_NOSUID 2
#define ST_NODEV 4
#define ST_NOEXEC 8
#define ST_SYNCHRONOUS 16
#define ST_MANDLOCK 64
#define ST_WRITE 128
#define ST_APPEND 256
#define ST_IMMUTABLE 512
#define ST_NOATIME 1024
#define ST_NODIRATIME 2048
#define ST_RELATIME 4096
Functions
int statvfs (const char *__restrict, struct statvfs *__restrict)
int fstatvfs (int, struct statvfs *)
Data Structure Documentation
statvfs
struct statvfs
Definition at line 11 of file statvfs.h.
Data Fields
unsigned __pad0__:8*(2*sizeof(int)-sizeof(long))
int __reserved[6]
fsblkcnt_t f_bavail
fsblkcnt_t f_bfree
fsblkcnt_t f_blocks
unsigned long f_bsize
fsfilcnt_t f_favail
fsfilcnt_t f_ffree
fsfilcnt_t f_files
unsigned long f_flag
unsigned long f_frsize
unsigned long f_fsid
unsigned long f_namemax
Macro Definition Documentation
__NEED_fsblkcnt_t
#define __NEED_fsblkcnt_t
Definition at line 10 of file statvfs.h.
__NEED_fsfilcnt_t
#define __NEED_fsfilcnt_t
Definition at line 11 of file statvfs.h.
ST_APPEND
#define ST_APPEND 256
Definition at line 39 of file statvfs.h.
ST_IMMUTABLE
#define ST_IMMUTABLE 512
Definition at line 40 of file statvfs.h.
ST_MANDLOCK
#define ST_MANDLOCK 64
Definition at line 37 of file statvfs.h.
ST_NOATIME
#define ST_NOATIME 1024
Definition at line 41 of file statvfs.h.
ST_NODEV
#define ST_NODEV 4
Definition at line 34 of file statvfs.h.
ST_NODIRATIME
#define ST_NODIRATIME 2048
Definition at line 42 of file statvfs.h.
ST_NOEXEC
#define ST_NOEXEC 8
Definition at line 35 of file statvfs.h.
ST_NOSUID
#define ST_NOSUID 2
Definition at line 33 of file statvfs.h.
ST_RDONLY
#define ST_RDONLY 1
Definition at line 32 of file statvfs.h.
ST_RELATIME
#define ST_RELATIME 4096
Definition at line 43 of file statvfs.h.
ST_SYNCHRONOUS
#define ST_SYNCHRONOUS 16
Definition at line 36 of file statvfs.h.
ST_WRITE
#define ST_WRITE 128
Definition at line 38 of file statvfs.h.
Function Documentation
fstatvfs()
int fstatvfs (int fd, struct statvfs * out)
Definition at line 16 of file sys-statvfs-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fstatvfs, -1);
     if(int e = mlibc::sys_fstatvfs(fd, out); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __fstatfs(), buf, errno, fixup(), MLIBC_CHECK_OR_ENOSYS, out(), and mlibc::sys_fstatvfs().
statvfs()
int statvfs (const char * __restrict, struct statvfs * __restrict)
Definition at line 7 of file sys-statvfs-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_statvfs, -1);
     if(int e = mlibc::sys_statvfs(path, out); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, out(), and mlibc::sys_statvfs().