Fennix: Userspace/apps/base/busybox/networking/traceroute.c File Reference
traceroute.c File Reference
#include <net/if.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <netinet/udp.h>
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#include "libbb.h"
#include "inet_common.h"
Data Structures
struct outdata_t
struct globals
Macros
#define TRACEROUTE_SO_DEBUG 0
#define IPPROTO_ICMP 1
#define IPPROTO_IP 0
#define SOL_RAW IPPROTO_RAW
#define OPT_STRING
#define verbose 0
#define G_ipv6 0
#define G (*ptr_to_globals)
#define outip (G.outip)
#define outdata (G.outdata)
#define dest_lsa (G.dest_lsa)
#define packlen (G.packlen)
#define pmtu (G.pmtu)
#define ident (G.ident)
#define port (G.port)
#define waittime (G.waittime)
#define recv_pkt (G.recv_pkt)
#define INIT_G()
#define outudp ((struct udphdr *)(outip + 1))
#define outudp6 ((struct udphdr *)(((struct ip6_hdr*)outip) + 1))
#define outicmp ((struct icmp *)(outip + 1))
#define outicmp6 ((struct icmp *)(((struct ip6_hdr*)outip) + 1))
#define hexdump_if_verbose(...) 0
#define packet_ok(read_len, seq) packet4_ok(read_len, seq)
#define print(len) print()
Enumerations
enum {
OPT_DONT_FRAGMNT = (1 << 0) , OPT_USE_ICMP = (1 << 1) * ENABLE_FEATURE_TRACEROUTE_USE_ICMP , OPT_TTL_FLAG = (1 << 2) , OPT_ADDR_NUM = (1 << 3) ,
OPT_BYPASS_ROUTE = (1 << 4) , OPT_DEBUG = (1 << 5) , OPT_VERBOSE = (1 << 6) * ENABLE_FEATURE_TRACEROUTE_VERBOSE , OPT_TOS = (1 << 7) ,
OPT_DEVICE = (1 << 8) , OPT_MAX_TTL = (1 << 9) , OPT_PORT = (1 << 10) , OPT_NPROBES = (1 << 11) ,
OPT_SOURCE = (1 << 12) , OPT_WAITTIME = (1 << 13) , OPT_PAUSE_MS = (1 << 14) , OPT_FIRST_TTL = (1 << 15) ,
OPT_IPV4 = (1 << 16) , OPT_IPV6 = (1 << 17) * ENABLE_TRACEROUTE6
}
enum { SIZEOF_ICMP_HDR = 8 , rcvsock = 3 , sndsock = 4 }
Functions
static int wait_for_reply (unsigned *timestamp_us, int *left_ms)
static void send_probe (int seq, int ttl)
static int packet4_ok (int read_len, int seq)
static void print (void)
static void print_delta_ms (unsigned t1p, unsigned t2p)
static NOINLINE void traceroute_init (int op, char **argv)
static int common_traceroute_main (int op, char **argv)
Data Structure Documentation
outdata_t
struct outdata_t
Definition at line 379 of file traceroute.c.
Data Fields
struct timeval tv_UNUSED PACKED
unsigned char seq
unsigned char ttl
Macro Definition Documentation
dest_lsa
#define dest_lsa (G.dest_lsa)
Definition at line 425 of file traceroute.c.
G
#define G (*ptr_to_globals)
Definition at line 422 of file traceroute.c.
G_ipv6
#define G_ipv6 0
Definition at line 410 of file traceroute.c.
hexdump_if_verbose
#define hexdump_if_verbose (...) 0
Definition at line 646 of file traceroute.c.
ident
#define ident (G.ident)
Definition at line 428 of file traceroute.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 432 of file traceroute.c.
IPPROTO_ICMP
#define IPPROTO_ICMP 1
Definition at line 329 of file traceroute.c.
IPPROTO_IP
#define IPPROTO_IP 0
Definition at line 332 of file traceroute.c.
OPT_STRING
#define OPT_STRING
Value:
    "FIlnrdvt:i:m:p:q:s:w:z:f:" \
    "4" IF_TRACEROUTE6("6")
Definition at line 343 of file traceroute.c.
outdata
#define outdata (G.outdata)
Definition at line 424 of file traceroute.c.
outicmp
#define outicmp ((struct icmp *)(outip + 1))
Definition at line 438 of file traceroute.c.
outicmp6
#define outicmp6 ((struct icmp *)(((struct ip6_hdr*)outip) + 1))
Definition at line 439 of file traceroute.c.
outip
#define outip (G.outip)
Definition at line 423 of file traceroute.c.
outudp
#define outudp ((struct udphdr *)(outip + 1))
Definition at line 436 of file traceroute.c.
outudp6
#define outudp6 ((struct udphdr *)(((struct ip6_hdr*)outip) + 1))
Definition at line 437 of file traceroute.c.
packet_ok
#define packet_ok (read_len, seq) packet4_ok(read_len, seq)
Definition at line 813 of file traceroute.c.
packlen
#define packlen (G.packlen)
Definition at line 426 of file traceroute.c.
pmtu
#define pmtu (G.pmtu)
Definition at line 427 of file traceroute.c.
port
#define port (G.port)
Definition at line 429 of file traceroute.c.
print
#define print (len) print()
recv_pkt
#define recv_pkt (G.recv_pkt)
Definition at line 431 of file traceroute.c.
SOL_RAW
#define SOL_RAW IPPROTO_RAW
Definition at line 339 of file traceroute.c.
TRACEROUTE_SO_DEBUG
#define TRACEROUTE_SO_DEBUG 0
Definition at line 306 of file traceroute.c.
verbose
#define verbose 0
Definition at line 369 of file traceroute.c.
waittime
#define waittime (G.waittime)
Definition at line 430 of file traceroute.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_DONT_FRAGMNT
OPT_USE_ICMP
OPT_TTL_FLAG
OPT_ADDR_NUM
OPT_BYPASS_ROUTE
OPT_DEBUG
OPT_VERBOSE
OPT_TOS
OPT_DEVICE
OPT_MAX_TTL
OPT_PORT
OPT_NPROBES
OPT_SOURCE
OPT_WAITTIME
OPT_PAUSE_MS
OPT_FIRST_TTL
OPT_IPV4
OPT_IPV6
Definition at line 346 of file traceroute.c.
      {
     OPT_DONT_FRAGMNT = (1 << 0),    /* F */
     OPT_USE_ICMP     = (1 << 1) * ENABLE_FEATURE_TRACEROUTE_USE_ICMP, /* I */
     OPT_TTL_FLAG     = (1 << 2),    /* l */
     OPT_ADDR_NUM     = (1 << 3),    /* n */
     OPT_BYPASS_ROUTE = (1 << 4),    /* r */
     OPT_DEBUG        = (1 << 5),    /* d */
     OPT_VERBOSE      = (1 << 6) * ENABLE_FEATURE_TRACEROUTE_VERBOSE, /* v */
     OPT_TOS          = (1 << 7),    /* t */
     OPT_DEVICE       = (1 << 8),    /* i */
     OPT_MAX_TTL      = (1 << 9),    /* m */
     OPT_PORT         = (1 << 10),   /* p */
     OPT_NPROBES      = (1 << 11),   /* q */
     OPT_SOURCE       = (1 << 12),   /* s */
     OPT_WAITTIME     = (1 << 13),   /* w */
     OPT_PAUSE_MS     = (1 << 14),   /* z */
     OPT_FIRST_TTL    = (1 << 15),   /* f */
     OPT_IPV4         = (1 << 16),   /* 4 */
     OPT_IPV6         = (1 << 17) * ENABLE_TRACEROUTE6, /* 6 */
 };
anonymous enum
anonymous enum
Enumerator
SIZEOF_ICMP_HDR
rcvsock
sndsock
Definition at line 372 of file traceroute.c.
      {
     SIZEOF_ICMP_HDR = 8,
     rcvsock = 3, /* receive (icmp) socket file descriptor */
     sndsock = 4, /* send (udp/icmp) socket file descriptor */
 };
Function Documentation
common_traceroute_main()
static int common_traceroute_main (int op, char ** argv) static
Definition at line 1117 of file traceroute.c.
 {
     int ttl;
     int seq;
     struct sockaddr *lastaddr;
     traceroute_init(op, argv);
     lastaddr = xzalloc(dest_lsa->len);
     seq = 0;
     for (ttl = G.first_ttl; ttl <= G.max_ttl; ++ttl) {
         int probe;
         int unreachable = 0; /* counter */
         int got_there = 0;
         printf("%2d", ttl);
         for (probe = 0; probe < G.nprobes; ++probe) {
             unsigned t1;
             unsigned t2;
             int left_ms;
             int read_len;
             int icmp_code;
             fflush_all();
             if (probe != 0)
                 msleep(G.pausemsecs);
             send_probe(++seq, ttl);
             t2 = t1 = monotonic_us();
             left_ms = waittime * 1000;
             for (;;) {
                 /* NB: wait_for_reply() fills "G.from_lsa" and "G.to" with
                  * "where it came from" and "what local address it arrived to"
                  * addresses. Sets t2 = monotonic_us(), updates left_ms.
                  */
                 read_len = wait_for_reply(&t2, &left_ms);
                 if (read_len == 0) { /* there was no packet at all? */
                     printf("  *");
                     goto next_probe;
                 }
                 icmp_code = packet_ok(read_len, seq);
                 if (icmp_code != 0)
                     break; /* got a good response */
                 /* unrecognized type/code or too short, back to recv */
             }
             if (probe == 0
              || (memcmp(lastaddr, &G.from_lsa->u.sa, G.from_lsa->len) != 0)
             ) {
                 print(read_len);
                 memcpy(lastaddr, &G.from_lsa->u.sa, G.from_lsa->len);
             }
             print_delta_ms(t1, t2);
             if (!G_ipv6) {
                 if (op & OPT_TTL_FLAG) {
                     struct ip *ip = (struct ip *)recv_pkt;
                     printf(" (%d)", ip->ip_ttl);
                 }
             }
             /* Got a "time exceeded in transit" icmp message? */
             if (icmp_code == -1)
                 continue;
             icmp_code--;
             switch (icmp_code) {
 #if ENABLE_TRACEROUTE6
             case ICMP6_DST_UNREACH_NOPORT << 8:
                 got_there = 1;
                 break;
 #endif
             case ICMP_UNREACH_PORT: {
                 struct ip *ip = (struct ip *)recv_pkt;
                 if (ip->ip_ttl <= 1)
                     printf(" !");
                 got_there = 1;
                 break;
             }
             case ICMP_UNREACH_NET:
 #if ENABLE_TRACEROUTE6 && (ICMP6_DST_UNREACH_NOROUTE != ICMP_UNREACH_NET)
             case ICMP6_DST_UNREACH_NOROUTE << 8:
 #endif
                 printf(" !N");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_HOST:
 #if ENABLE_TRACEROUTE6
             case ICMP6_DST_UNREACH_ADDR << 8:
 #endif
                 printf(" !H");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_PROTOCOL:
                 printf(" !P");
                 got_there = 1;
                 break;
             case ICMP_UNREACH_NEEDFRAG:
                 printf(" !F-%d", pmtu);
                 ++unreachable;
                 break;
             case ICMP_UNREACH_SRCFAIL:
 #if ENABLE_TRACEROUTE6
             case ICMP6_DST_UNREACH_ADMIN << 8:
 #endif
                 printf(" !S");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_FILTER_PROHIB:
             case ICMP_UNREACH_NET_PROHIB:   /* misuse */
                 printf(" !A");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_HOST_PROHIB:
                 printf(" !C");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_HOST_PRECEDENCE:
                 printf(" !V");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_PRECEDENCE_CUTOFF:
                 printf(" !C");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_NET_UNKNOWN:
             case ICMP_UNREACH_HOST_UNKNOWN:
                 printf(" !U");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_ISOLATED:
                 printf(" !I");
                 ++unreachable;
                 break;
             case ICMP_UNREACH_TOSNET:
             case ICMP_UNREACH_TOSHOST:
                 printf(" !T");
                 ++unreachable;
                 break;
             default:
                 printf(" !<%d>", icmp_code);
                 ++unreachable;
                 break;
             }
  next_probe: ;
         } /* for (nprobes) */
         bb_putchar('\n');
         if (got_there
          || (unreachable > 0 && unreachable >= G.nprobes - 1)
         ) {
             break;
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
 #if ENABLE_FEATURE_TRACEROUTE_VERBOSE
         free(G.to);
 #endif
         free(lastaddr);
         free(G.from_lsa);
     }
     return 0;
 }
References argv, bb_putchar(), dest_lsa, fflush_all(), free, G, G_ipv6, ICMP6_DST_UNREACH_ADDR, ICMP6_DST_UNREACH_ADMIN, ICMP6_DST_UNREACH_NOPORT, ICMP6_DST_UNREACH_NOROUTE, ICMP_UNREACH_FILTER_PROHIB, ICMP_UNREACH_HOST, ICMP_UNREACH_HOST_PRECEDENCE, ICMP_UNREACH_HOST_PROHIB, ICMP_UNREACH_HOST_UNKNOWN, ICMP_UNREACH_ISOLATED, ICMP_UNREACH_NEEDFRAG, ICMP_UNREACH_NET, ICMP_UNREACH_NET_PROHIB, ICMP_UNREACH_NET_UNKNOWN, ICMP_UNREACH_PORT, ICMP_UNREACH_PRECEDENCE_CUTOFF, ICMP_UNREACH_PROTOCOL, ICMP_UNREACH_SRCFAIL, ICMP_UNREACH_TOSHOST, ICMP_UNREACH_TOSNET, ip::ip_ttl, memcmp(), memcpy, monotonic_us(), msleep(), OPT_TTL_FLAG, packet_ok, pmtu, print, print_delta_ms(), printf, recv_pkt, send_probe(), seq, t1, t2, traceroute_init(), wait_for_reply(), waittime, and xzalloc().
packet4_ok()
static int packet4_ok (int read_len, int seq) static
Definition at line 650 of file traceroute.c.
 {
     const struct icmp *icp;
     unsigned char type, code;
     int hlen;
     const struct ip *ip;
     /* NB: reads from (AF_INET, SOCK_RAW, IPPROTO_ICMP) socket
      * return the entire IP packet (IOW: they do not strip IP header).
      * This differs from (AF_INET6, SOCK_RAW, IPPROTO_ICMPV6) sockets!?
      */
     ip = (struct ip *) recv_pkt;
     hlen = ip->ip_hl << 2;
     if (read_len < hlen + ICMP_MINLEN) {
         if (verbose)
             printf("packet too short (%d bytes) from %s\n", read_len,
                 inet_ntoa(G.from_lsa->u.sin.sin_addr));
         return 0;
     }
     read_len -= hlen;
     icp = (struct icmp *)(recv_pkt + hlen);
     type = icp->icmp_type;
     code = icp->icmp_code;
     /* Path MTU Discovery (RFC1191) */
     pmtu = 0;
     if (code == ICMP_UNREACH_NEEDFRAG)
         pmtu = ntohs(icp->icmp_nextmtu);
     if ((option_mask32 & OPT_USE_ICMP)
      && type == ICMP_ECHOREPLY
      && icp->icmp_seq == htons(seq)
     ) {
         if (icp->icmp_id != ident)
             /* reply to another ping/traceroute from this box? */
             return 0; /* ignore, silently */
         /* In UDP mode, when we reach the machine, we (usually)
          * would get "port unreachable" - in ICMP we got "echo reply".
          * Simulate "port unreachable" for caller:
          */
         return ICMP_UNREACH_PORT+1;
     }
     if ((type == ICMP_TIMXCEED && code == ICMP_TIMXCEED_INTRANS)
      || type == ICMP_UNREACH
     ) {
         const struct ip *hip;
         const struct udphdr *up;
         hip = &icp->icmp_ip;
         hlen = hip->ip_hl << 2;
         if (option_mask32 & OPT_USE_ICMP) {
             struct icmp *hicmp;
             hicmp = (struct icmp *)((unsigned char *)hip + hlen);
             if (hlen + SIZEOF_ICMP_HDR <= read_len
              && hip->ip_p == IPPROTO_ICMP
              && hicmp->icmp_id == ident
              && hicmp->icmp_seq == htons(seq)
             ) {
                 return (type == ICMP_TIMXCEED ? -1 : code + 1);
             }
         } else {
             up = (struct udphdr *)((char *)hip + hlen);
             if (hlen + 12 <= read_len
              && hip->ip_p == IPPROTO_UDP
 #if !defined(__FreeBSD__)
 // Disabled source check: since we do not form the entire IP packet,
 // but defer it to kernel, we can't set source port,
 // and thus can't check it here in the reply
             /* && up->source == ident */
              && up->dest == htons(port + seq)
 #else
             /* && up->uh_sport == ident */
              && up->uh_dport == htons(port + seq)
 #endif
             ) {
                 return (type == ICMP_TIMXCEED ? -1 : code + 1);
             }
         }
     }
     /* testcase: traceroute -vI 127.0.0.1 (sees its own echo requests) */
     return hexdump_if_verbose(icp, read_len);
 }
References code, G, hexdump_if_verbose, htons(), icmp::icmp_code, ICMP_ECHOREPLY, ICMP_MINLEN, ICMP_TIMXCEED, ICMP_TIMXCEED_INTRANS, icmp::icmp_type, ICMP_UNREACH, ICMP_UNREACH_NEEDFRAG, ICMP_UNREACH_PORT, ident, inet_ntoa(), ip::ip_hl, ip::ip_p, IPPROTO_ICMP, IPPROTO_UDP, ntohs(), OPT_USE_ICMP, option_mask32, pmtu, port, printf, recv_pkt, seq, SIZEOF_ICMP_HDR, type, up, and verbose.
print()
static void print (void) static
Definition at line 819 of file traceroute.c.
 {
     char *ina = auto_string(xmalloc_sockaddr2dotted_noport(&G.from_lsa->u.sa));
     if (option_mask32 & OPT_ADDR_NUM) {
         printf("  %s", ina);
     } else {
         char *n = NULL;
         if (G_ipv6
          || G.from_lsa->u.sin.sin_addr.s_addr != INADDR_ANY
         ) {
             /* Reverse resolve if IPV6 or not 0.0.0.0 */
             n = auto_string(xmalloc_sockaddr2host_noport(&G.from_lsa->u.sa));
         }
         printf("  %s (%s)", (n ? n : ina), ina);
     }
 #if ENABLE_FEATURE_TRACEROUTE_VERBOSE
     if (verbose) {
 # if ENABLE_TRACEROUTE6
         /* NB: reads from (AF_INET, SOCK_RAW, IPPROTO_ICMP) socket
          * return the entire IP packet (IOW: they do not strip IP header).
          * Reads from (AF_INET6, SOCK_RAW, IPPROTO_ICMPV6) do strip IPv6
          * header and return only ICMP6 packet. Weird.
          */
         if (G_ipv6) {
             /* read_len -= sizeof(struct ip6_hdr); - WRONG! */
         } else
 # endif
         {
             struct ip *ip4packet = (struct ip*)recv_pkt;
             read_len -= ip4packet->ip_hl << 2;
         }
         printf(" %d bytes to %s", read_len,
             auto_string(xmalloc_sockaddr2dotted_noport(G.to))
         );
     }
 #endif
 }
References auto_string(), G, G_ipv6, INADDR_ANY, ip::ip_hl, n, NULL, OPT_ADDR_NUM, option_mask32, printf, recv_pkt, verbose, xmalloc_sockaddr2dotted_noport(), and xmalloc_sockaddr2host_noport().
print_delta_ms()
static void print_delta_ms (unsigned t1p, unsigned t2p) static
Definition at line 864 of file traceroute.c.
 {
     unsigned tt = t2p - t1p;
     printf("  %u.%03u ms", tt / 1000, tt % 1000);
 }
References printf, and tt.
Referenced by common_traceroute_main().
send_probe()
static void send_probe (int seq, int ttl) static
Definition at line 496 of file traceroute.c.
 {
     int len, res;
     void *out;
     struct icmp *icp;
     /* Payload */
 #if ENABLE_TRACEROUTE6
     if (G_ipv6) {
         struct outdata6_t *pkt = (void *) outdata;
         pkt->ident6 = ident;
         pkt->seq6   = htonl(seq);
         /*xgettimeofday(&pkt->tv);*/
         icp = outicmp6;
     } else
 #endif
     {
         outdata->seq = seq;
         outdata->ttl = ttl;
 // UNUSED: was storing gettimeofday's result there, but never ever checked it
         /*memcpy(&outdata->tv, tp, sizeof(outdata->tv));*/
         icp = outicmp;
     }
     out = outdata;
     if (option_mask32 & OPT_USE_ICMP) {
         out = icp;
         /*icp->icmp_type = ICMP[6]_ECHO; - already set */
         /*icp->icmp_code = 0; - already set */
         /*icp->icmp_id = ident; - already set */
         icp->icmp_seq = htons(seq);
         /* Always calculate checksum for icmp packets */
         icp->icmp_cksum = 0;
         icp->icmp_cksum = inet_cksum(
                 icp,
                 ((char*)outip + packlen) - (char*)icp
         );
         if (icp->icmp_cksum == 0)
             icp->icmp_cksum = 0xffff;
     }
 //BUG! verbose is (x & OPT_VERBOSE), not a counter!
 #if 0 //ENABLE_FEATURE_TRACEROUTE_VERBOSE
     /* XXX undocumented debugging hack */
     if (verbose > 1) {
         const uint16_t *sp;
         int nshorts, i;
         sp = (uint16_t *)outip;
         nshorts = (unsigned)packlen / sizeof(uint16_t);
         i = 0;
         printf("[ %d bytes", packlen);
         while (--nshorts >= 0) {
             if ((i++ % 8) == 0)
                 printf("\n\t");
             printf(" %04x", ntohs(*sp));
             sp++;
         }
         if (packlen & 1) {
             if ((i % 8) == 0)
                 printf("\n\t");
             printf(" %02x", *(unsigned char *)sp);
         }
         printf("]\n");
     }
 #endif
 #if ENABLE_TRACEROUTE6
     if (G_ipv6) {
         res = setsockopt_int(sndsock, SOL_IPV6, IPV6_UNICAST_HOPS, ttl);
         if (res != 0)
             bb_perror_msg_and_die("setsockopt(%s) %d", "UNICAST_HOPS", ttl);
     } else
 #endif
     {
 #if defined IP_TTL
         res = setsockopt_int(sndsock, IPPROTO_IP, IP_TTL, ttl);
         if (res != 0)
             bb_perror_msg_and_die("setsockopt(%s) %d", "TTL", ttl);
 #endif
     }
     if (!(option_mask32 & OPT_USE_ICMP)) {
         set_nport(&dest_lsa->u.sa, htons(port + seq));
     }
     len = ((char*)outip + packlen) - (char*)out;
     res = xsendto(sndsock, out, len, &dest_lsa->u.sa, dest_lsa->len);
     if (res != len)
         bb_error_msg("sent %d octets, ret=%d", len, res);
 }
References bb_error_msg(), bb_perror_msg_and_die(), dest_lsa, G_ipv6, htonl(), htons(), i, icmp::icmp_cksum, ident, inet_cksum(), IP_TTL, IPPROTO_IP, IPV6_UNICAST_HOPS, len, ntohs(), OPT_USE_ICMP, option_mask32, out(), outdata, outicmp, outicmp6, outip, packlen, port, printf, seq, set_nport(), setsockopt_int(), sndsock, SOL_IPV6, sp, verbose, and xsendto().
Referenced by common_traceroute_main().
traceroute_init()
static NOINLINE void traceroute_init (int op, char ** argv) static
Definition at line 874 of file traceroute.c.
 {
     char *source;
     char *device;
     char *tos_str;
     char *max_ttl_str;
     char *port_str;
     char *nprobes_str;
     char *waittime_str;
     char *pausemsecs_str;
     char *first_ttl_str;
     char *dest_str;
 #if ENABLE_TRACEROUTE6
     sa_family_t af;
 #else
     enum { af = AF_INET };
 #endif
     /* Ensure the socket fds won't be 0, 1 or 2 */
     bb_sanitize_stdio();
     INIT_G();
     port = 33434;
     waittime = 5;
     G.first_ttl = 1;
     G.nprobes = 3;
     G.max_ttl = 30;
     op |= getopt32(argv, "^"
         OPT_STRING
         "\0" "-1" /* minimum 1 arg */
         , &tos_str, &device, &max_ttl_str, &port_str, &nprobes_str
         , &source, &waittime_str, &pausemsecs_str, &first_ttl_str
     );
     argv += optind;
     if (op & OPT_MAX_TTL)
         G.max_ttl = xatou_range(max_ttl_str, 1, 255);
     if (op & OPT_PORT)
         port = xatou16(port_str);
     if (op & OPT_NPROBES)
         G.nprobes = xatou_range(nprobes_str, 1, INT_MAX);
     if (op & OPT_WAITTIME)
         waittime = xatou_range(waittime_str, 1, 24 * 60 * 60);
     if (op & OPT_PAUSE_MS)
         G.pausemsecs = xatou_range(pausemsecs_str, 0, 60 * 60 * 1000);
     if (op & OPT_FIRST_TTL)
         G.first_ttl = xatou_range(first_ttl_str, 1, G.max_ttl);
     /* Process destination and optional packet size */
     packlen = sizeof(struct ip)
             + sizeof(struct udphdr)
             + sizeof(struct outdata_t);
     if (op & OPT_USE_ICMP) {
         packlen = sizeof(struct ip)
             + SIZEOF_ICMP_HDR
             + sizeof(struct outdata_t);
         port = 0; /* on ICMP6 sockets, sendto(ipv6.nonzero_port) throws EINVAL! */
     }
 #if ENABLE_TRACEROUTE6
     af = AF_UNSPEC;
     if (op & OPT_IPV4)
         af = AF_INET;
     if (op & OPT_IPV6)
         af = AF_INET6;
     dest_lsa = xhost_and_af2sockaddr(argv[0], port, af);
     af = dest_lsa->u.sa.sa_family;
 //TODO: make sure af == AF_INET[6]? (FEATURE_UNIX_LOCAL=y allows "local:/PATH" to be translated to AF_UNIX)
     if (af == AF_INET6) {
         G_ipv6 = 1;
         packlen = sizeof(struct ip6_hdr)
                 + sizeof(struct udphdr)
                 + sizeof(struct outdata6_t);
         if (op & OPT_USE_ICMP)
             packlen = sizeof(struct ip6_hdr)
                 + SIZEOF_ICMP_HDR
                 + sizeof(struct outdata6_t);
     }
 #else
     /* accept only IPv4 addresses */
     dest_lsa = xhost_and_af2sockaddr(argv[0], port, AF_INET);
 #endif
     G.from_lsa = xmemdup(dest_lsa, LSA_LEN_SIZE + dest_lsa->len);
 #if ENABLE_FEATURE_TRACEROUTE_VERBOSE
     G.to = xzalloc(dest_lsa->len);
 #endif
     if (argv[1])
         packlen = xatoul_range(argv[1], packlen, 32 * 1024);
     if (af == AF_INET) {
         xmove_fd(xsocket(AF_INET, SOCK_RAW, IPPROTO_ICMP), rcvsock);
 #if ENABLE_FEATURE_TRACEROUTE_VERBOSE
         /* want recvmsg to report target local address (for -v) */
         setsockopt_1(rcvsock, IPPROTO_IP, IP_PKTINFO);
 #endif
     }
 #if ENABLE_TRACEROUTE6
     else {
         xmove_fd(xsocket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6), rcvsock);
 # if ENABLE_FEATURE_TRACEROUTE_VERBOSE
         /* want recvmsg to report target local address (for -v) */
         setsockopt_1(rcvsock, SOL_IPV6, IPV6_RECVPKTINFO);
 # endif
     }
 #endif
 #if TRACEROUTE_SO_DEBUG
     if (op & OPT_DEBUG)
         setsockopt_SOL_SOCKET_1(rcvsock, SO_DEBUG);
 #endif
     {
         int snd;
         if (af == AF_INET) {
             if (op & OPT_USE_ICMP)
                 snd = xsocket(AF_INET, SOCK_RAW, IPPROTO_ICMP);
             else
                 snd = xsocket(AF_INET, SOCK_DGRAM, 0);
         }
 #if ENABLE_TRACEROUTE6
 # if defined(__FreeBSD__)
 #  define SOL_V6_OPTION SOL_IPV6
 # else
 #  define SOL_V6_OPTION SOL_RAW
 # endif
         else {
             if (setsockopt_int(rcvsock, SOL_V6_OPTION, IPV6_CHECKSUM, 2) != 0)
                 bb_perror_msg_and_die("setsockopt(%s)", "IPV6_CHECKSUM");
             if (op & OPT_USE_ICMP)
                 snd = xsocket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6);
             else
                 snd = xsocket(AF_INET6, SOCK_DGRAM, 0);
         }
 #endif
         xmove_fd(snd, sndsock);
     }
 #ifdef SO_SNDBUF
     if (setsockopt_SOL_SOCKET_int(sndsock, SO_SNDBUF, packlen) != 0) {
         bb_perror_msg_and_die("setsockopt(%s)", "SO_SNDBUF");
     }
 #endif
 #ifdef IP_TOS
     if (op & OPT_TOS) {
         int tos = xatou_range(tos_str, 0, 255);
         if (setsockopt_int(sndsock, IPPROTO_IP, IP_TOS, tos) != 0)
             bb_perror_msg_and_die("setsockopt(%s,%d)", "TOS", tos);
     }
 #endif
 #ifdef IP_DONTFRAG
     if (op & OPT_DONT_FRAGMNT)
         setsockopt_1(sndsock, IPPROTO_IP, IP_DONTFRAG);
 #endif
 #if TRACEROUTE_SO_DEBUG
     if (op & OPT_DEBUG)
         setsockopt_SOL_SOCKET_1(sndsock, SO_DEBUG);
 #endif
     if (op & OPT_BYPASS_ROUTE)
         setsockopt_SOL_SOCKET_1(sndsock, SO_DONTROUTE);
     outip = xzalloc(packlen);
     ident = getpid();
     /* we can use native-endian ident, but other Unix ping/traceroute
      * utils use *big-endian pid*, and e.g. ping on our machine may be
      * *not* from busybox, idents may collide. Follow the convention:
      */
     ident = htons(ident);
     outdata = (void*)(outudp + 1);
     if (af == AF_INET) {
         if (op & OPT_USE_ICMP) {
             outicmp->icmp_type = ICMP_ECHO;
             /*outicmp->icmp_code = 0; - set by xzalloc */
             outicmp->icmp_id = ident;
             outdata = (void*)((char *)outicmp + SIZEOF_ICMP_HDR);
         }
     }
 #if ENABLE_TRACEROUTE6
     else {
         outdata = (void*)(outudp6 + 1);
         if (op & OPT_USE_ICMP) {
             outicmp6->icmp_type = ICMP6_ECHO_REQUEST;
             /*outicmp->icmp_code = 0; - set by xzalloc */
             outicmp6->icmp_id = ident;
             outdata = (void*)((char *)outicmp6 + SIZEOF_ICMP_HDR);
         }
     }
 #endif
     if (op & OPT_DEVICE) /* hmm, do we need error check? */
         setsockopt_bindtodevice(sndsock, device);
     if (op & OPT_SOURCE) {
 #if ENABLE_TRACEROUTE6
 // TODO: need xdotted_and_af2sockaddr?
         len_and_sockaddr *source_lsa = xhost_and_af2sockaddr(source, 0, af);
 #else
         len_and_sockaddr *source_lsa = xdotted2sockaddr(source, 0);
 #endif
         if (getuid() != 0)
             bb_simple_error_msg_and_die(bb_msg_you_must_be_root);
         /* Ping4 does this (why?) */
         if (af == AF_INET)
             if (setsockopt(sndsock, IPPROTO_IP, IP_MULTICAST_IF,
                     &source_lsa->u.sa, source_lsa->len))
                 bb_simple_error_msg_and_die("can't set multicast source interface");
 //TODO: we can query source port we bound to,
 // and check it in replies... if we care enough
         xbind(sndsock, &source_lsa->u.sa, source_lsa->len);
         if (ENABLE_FEATURE_CLEAN_UP)
             free(source_lsa);
     } else {
         len_and_sockaddr *source_lsa;
         set_nport(&dest_lsa->u.sa, htons(port));
         /* Connect makes kernel pick source IP (and port if UDP) */
         xconnect(sndsock, &dest_lsa->u.sa, dest_lsa->len);
         /* Read IP and port */
         source_lsa = get_sock_lsa(sndsock);
         if (source_lsa == NULL)
             bb_simple_perror_msg_and_die("getsockname");
         /* bind our recv ICMP socket to this IP (but not port, ICMP has no ports) */
         //set_nport(&source_lsa->u.sa, 0); - paranoia, seems to work without this for both ipv4 and ipv6
         xbind(rcvsock, &source_lsa->u.sa, source_lsa->len);
         if (ENABLE_FEATURE_CLEAN_UP)
             free(source_lsa);
     }
     /* Revert to non-privileged user after opening sockets */
     xsetgid(getgid());
     xsetuid(getuid());
     dest_str = xmalloc_sockaddr2dotted_noport(&dest_lsa->u.sa);
     printf("traceroute to %s (%s)", argv[0], dest_str);
     if (ENABLE_FEATURE_CLEAN_UP)
         free(dest_str);
     if (op & OPT_SOURCE)
         printf(" from %s", source);
     printf(", %d hops max, %d byte packets\n", G.max_ttl, packlen);
 }
References AF_INET, AF_INET6, AF_UNSPEC, argv, bb_perror_msg_and_die(), bb_sanitize_stdio(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), dest_lsa, device, free, G, G_ipv6, get_sock_lsa(), getgid, getopt32(), getpid(), getuid, htons(), ICMP6_ECHO_REQUEST, ICMP_ECHO, ident, INIT_G, INT_MAX, IP_MULTICAST_IF, IP_PKTINFO, IP_TOS, IPPROTO_ICMP, IPPROTO_ICMPV6, IPPROTO_IP, IPV6_CHECKSUM, IPV6_RECVPKTINFO, len_and_sockaddr::len, LSA_LEN_SIZE, NULL, OPT_BYPASS_ROUTE, OPT_DEBUG, OPT_DEVICE, OPT_DONT_FRAGMNT, OPT_FIRST_TTL, OPT_IPV4, OPT_IPV6, OPT_MAX_TTL, OPT_NPROBES, OPT_PAUSE_MS, OPT_PORT, OPT_SOURCE, OPT_STRING, OPT_TOS, OPT_USE_ICMP, OPT_WAITTIME, optind, outdata, outicmp, outicmp6, outip, outudp, outudp6, packlen, port, printf, rcvsock, set_nport(), setsockopt(), setsockopt_1(), setsockopt_bindtodevice(), setsockopt_int(), setsockopt_SOL_SOCKET_1(), setsockopt_SOL_SOCKET_int(), SIZEOF_ICMP_HDR, sndsock, SO_DEBUG, SO_DONTROUTE, SO_SNDBUF, SOCK_DGRAM, SOCK_RAW, SOL_IPV6, source, len_and_sockaddr::u, waittime, xatou16(), xbind(), xconnect(), xdotted2sockaddr(), xhost_and_af2sockaddr, xmalloc_sockaddr2dotted_noport(), xmemdup(), xmove_fd(), xsetgid(), xsetuid(), xsocket(), and xzalloc().
Referenced by common_traceroute_main().
wait_for_reply()
static int wait_for_reply (unsigned * timestamp_us, int * left_ms) static
Definition at line 464 of file traceroute.c.
 {
     struct pollfd pfd[1];
     int read_len = 0;
     pfd[0].fd = rcvsock;
     pfd[0].events = POLLIN;
     if (*left_ms >= 0 && safe_poll(pfd, 1, *left_ms) > 0) {
         unsigned t;
 #if ENABLE_FEATURE_TRACEROUTE_VERBOSE
         read_len = recv_from_to(rcvsock,
                 recv_pkt, sizeof(recv_pkt),
                 /*flags:*/ MSG_DONTWAIT,
                 &G.from_lsa->u.sa, G.to, G.from_lsa->len);
 #else
         read_len = recvfrom(rcvsock,
                 recv_pkt, sizeof(recv_pkt),
                 /*flags:*/ MSG_DONTWAIT,
                 &G.from_lsa->u.sa, &G.from_lsa->len);
 #endif
         if (read_len < 0)
             bb_simple_perror_msg_and_die("recv");
         t = monotonic_us();
         *left_ms -= (t - *timestamp_us) / 1000;
         *timestamp_us = t;
     }
     return read_len;
 }
References bb_simple_perror_msg_and_die(), G, monotonic_us(), MSG_DONTWAIT, pfd, POLLIN, rcvsock, recv_from_to(), recv_pkt, recvfrom(), safe_poll(), and t.
Referenced by common_traceroute_main().