Fennix: Userspace/mlibc/options/posix/include/sys/wait.h File Reference
wait.h File Reference
#include <bits/posix/id_t.h>
#include <abi-bits/pid_t.h>
#include <abi-bits/signal.h>
#include <abi-bits/wait.h>
Enumerations
enum idtype_t {
P_ALL , P_PID , P_PGID , P_ALL ,
P_PID , P_PGID , P_ALL = 0 , P_PID = 1 ,
P_PGID = 2 , P_PIDFD = 3
}
Functions
pid_t wait (int *status)
int waitid (idtype_t idtype, id_t id, siginfo_t *siginfo, int flags)
pid_t waitpid (pid_t pid, int *status, int flags)
pid_t wait3 (int *, int, struct rusage *)
pid_t wait4 (pid_t pid, int *status, int options, struct rusage *ru)
Enumeration Type Documentation
idtype_t
enum idtype_t
Enumerator
P_ALL
P_PID
P_PGID
P_ALL
P_PID
P_PGID
P_ALL
P_PID
P_PGID
P_PIDFD
Definition at line 19 of file wait.h.
              {
     P_ALL, P_PID, P_PGID
 } idtype_t;
Function Documentation
wait()
pid_t wait (int * status)
Definition at line 3 of file wait.c.
 {
     return waitpid(-1, &wstatus, 0);
 }
wait3()
pid_t wait3 (int * status, int options, struct rusage * rusage)
Definition at line 29 of file sys-wait-stubs.cpp.
{
     (void) rusage;
     mlibc::infoLogger() << "\e[31mmlibc: wait3() is not implemented correctly\e[39m"
         << frg::endlog;
     return waitpid(-1, status, options);
 }
References mlibc::infoLogger, options, mlibc::status, usage(), Driver::void(), wait4(), and waitpid().
Referenced by __wait3_time32().
wait4()
pid_t wait4 (pid_t pid, int * status, int options, struct rusage * ru)
Definition at line 36 of file sys-wait-stubs.cpp.
{
     pid_t ret;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_waitpid, -1);
     if(int e = mlibc::sys_waitpid(pid, status, options, ru, &ret); e) {
         errno = e;
         return -1;
     }
     return ret;
 }
References __syscall, __syscall_ret(), ENOSYS, errno, for(), i, memcpy, MLIBC_CHECK_OR_ENOSYS, options, r, ret, mlibc::ru, rusage::ru_maxrss, rusage::ru_stime, rusage::ru_utime, mlibc::status, SYS_wait4_time64, mlibc::sys_waitpid(), and timeval::tv_sec.
Referenced by __wait4_time32(), and wait3().
waitid()
int waitid (idtype_t idtype, id_t id, siginfo_t * siginfo, int flags)
Definition at line 12 of file wait.c.
 {
 }
References __ensure, info, options, syscall_cp, and type.
waitpid()
pid_t waitpid (pid_t pid, int * status, int flags)
Definition at line 8 of file wait.c.
 {
 }