Fennix Userspace: Userspace/apps/base/busybox/miscutils/volname.c File Reference
volname.c File Reference
#include "libbb.h"
Functions
int volname_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
volname_main()
int volname_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 48 of file volname.c.
 {
     int fd;
     char buffer[32];
     const char *device;
     device = "/dev/cdrom";
     if (argv[1]) {
         device = argv[1];
         if (argv[2])
             bb_show_usage();
     }
     fd = xopen(device, O_RDONLY);
     xlseek(fd, 32808, SEEK_SET);
     xread(fd, buffer, 32);
     printf("%32.32s\n", buffer);
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(fd);
     }
     return 0;
 }
References argv, bb_show_usage(), close(), device, fd, O_RDONLY, printf(), SEEK_SET, xlseek(), xopen(), and xread().