Fennix Userspace: Userspace/apps/base/busybox/util-linux/mkswap.c File Reference
mkswap.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct swap_header_v1
struct BUG_sizes
Macros
#define mkswap_selinux_setcontext(fd, path) ((void)0)
#define NWORDS 129
#define hdr ((struct swap_header_v1*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Functions
int mkswap_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct swap_header_v1 FIX_ALIASING
static const char SWAPSPACE2[sizeof("SWAPSPACE2") -1] ALIGN1 = "SWAPSPACE2"
Data Structure Documentation
swap_header_v1
struct swap_header_v1
Definition at line 89 of file mkswap.c.
Data Fields
uint32_t badpages[1]
uint32_t last_page
uint32_t nr_badpages
uint32_t padding[117]
char sws_uuid[16]
char sws_volume[16]
uint32_t version
BUG_sizes
struct BUG_sizes
Definition at line 105 of file mkswap.c.
Data Fields
char bufsiz1_is_too_small[COMMON_BUFSIZE<(NWORDS *4) ? -1 :1]
char swap_header_v1_wrong[sizeof(*hdr) !=(NWORDS *4) ? -1 :1]
Macro Definition Documentation
hdr
#define hdr ((struct swap_header_v1*)bb_common_bufsiz1)
Definition at line 102 of file mkswap.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 103 of file mkswap.c.
mkswap_selinux_setcontext
#define mkswap_selinux_setcontext (fd, path) ((void)0)
Definition at line 81 of file mkswap.c.
NWORDS
#define NWORDS 129
Definition at line 101 of file mkswap.c.
Function Documentation
mkswap_main()
int mkswap_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 114 of file mkswap.c.
 {
     int fd;
     unsigned pagesize;
     off_t len;
     const char *label = "";
     INIT_G();
     /* TODO: -p PAGESZ, -U UUID */
     getopt32(argv, "^" "L:" "\0" "-1"/*at least one arg*/, &label);
     argv += optind;
     fd = xopen(argv[0], O_WRONLY);
     /* Figure out how big the device is */
     len = get_volume_size_in_bytes(fd, argv[1], 1024, /*extend:*/ 1);
     pagesize = bb_getpagesize();
     len -= pagesize;
     /* Announce our intentions */
     printf("Setting up swapspace version 1, size = %"OFF_FMT"u bytes\n", len);
     mkswap_selinux_setcontext(fd, argv[0]);
     /* hdr is zero-filled so far. Clear the first kbyte, or else
      * mkswap-ing former FAT partition does NOT erase its signature.
      *
      * util-linux-ng 2.17.2 claims to erase it only if it does not see
      * a partition table and is not run on whole disk. -f forces it.
      */
     xwrite(fd, hdr, 1024);
     /* Fill the header. */
     hdr->version = 1;
     hdr->last_page = (uoff_t)len / pagesize;
     if (ENABLE_FEATURE_MKSWAP_UUID) {
         char uuid_string[32];
         generate_uuid((void*)hdr->sws_uuid);
         bin2hex(uuid_string, hdr->sws_uuid, 16);
         /* f.e. UUID=dfd9c173-be52-4d27-99a5-c34c6c2ff55f */
         printf("UUID=%.8s"  "-%.4s-%.4s-%.4s-%.12s\n",
             uuid_string,
             uuid_string+8,
             uuid_string+8+4,
             uuid_string+8+4+4,
             uuid_string+8+4+4+4
         );
     }
     safe_strncpy(hdr->sws_volume, label, 16);
     /* Write the header.  Sync to disk because some kernel versions check
      * signature on disk (not in cache) during swapon. */
     xwrite(fd, hdr, NWORDS * 4);
     xlseek(fd, pagesize - 10, SEEK_SET);
     xwrite(fd, SWAPSPACE2, 10);
     fsync(fd);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     return 0;
 }
References argv, bb_getpagesize, bin2hex(), close(), fd, fsync(), generate_uuid(), get_volume_size_in_bytes(), getopt32(), INIT_G, label, mkswap_selinux_setcontext, NWORDS, O_WRONLY, OFF_FMT, off_t, optind, printf(), safe_strncpy(), SEEK_SET, xlseek(), xopen(), and xwrite().
Variable Documentation
ALIGN1
const char SWAPSPACE2 [sizeof("SWAPSPACE2")-1] ALIGN1 = "SWAPSPACE2" static
Definition at line 111 of file mkswap.c.
FIX_ALIASING
struct swap_header_v1 FIX_ALIASING