Fennix: Userspace/apps/base/busybox/archival/libarchive/data_extract_to_stdout.c File Reference
data_extract_to_stdout.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
void FAST_FUNC data_extract_to_stdout (archive_handle_t *archive_handle)
Function Documentation
data_extract_to_stdout()
void FAST_FUNC data_extract_to_stdout (archive_handle_t * archive_handle)
Definition at line 8 of file data_extract_to_stdout.c.
 {
     bb_copyfd_exact_size(archive_handle->src_fd,
             STDOUT_FILENO,
             archive_handle->file_header->size);
 }
References bb_copyfd_exact_size(), archive_handle_t::file_header, file_header_t::size, archive_handle_t::src_fd, and STDOUT_FILENO.
Referenced by ar_main(), dpkg_deb_main(), and tar_main().