Fennix: Userspace/apps/base/bash/examples/loadables/getconf.c File Reference
getconf.c File Reference
#include <config.h>
#include <unistd.h>
#include <errno.h>
#include <error.h>
#include <libintl.h>
#include <locale.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "typemax.h"
#include "loadables.h"
#include "getconf.h"
Data Structures
struct conf
Macros
#define VAL_LLONG_MIN -1000
#define VAL_LLONG_MAX -1001
#define VAL_ULLONG_MAX -1002
#define VAL_ULONG_MAX -1003
#define VAL_SSIZE_MAX -1004
#define VAL_SIZE_MAX -1005
Functions
static int getconf_print (const struct conf *, const char *, int)
static int getconf_all (void)
static int getconf_one (WORD_LIST *)
static int getconf_internal (const struct conf *, int)
int getconf_builtin (WORD_LIST *list)
Variables
int errno
static const struct conf vars []
static char * getconf_doc []
struct builtin getconf_struct
Macro Definition Documentation
VAL_LLONG_MAX
#define VAL_LLONG_MAX -1001
Definition at line 40 of file getconf.c.
VAL_LLONG_MIN
#define VAL_LLONG_MIN -1000
Definition at line 39 of file getconf.c.
VAL_SIZE_MAX
#define VAL_SIZE_MAX -1005
Definition at line 44 of file getconf.c.
VAL_SSIZE_MAX
#define VAL_SSIZE_MAX -1004
Definition at line 43 of file getconf.c.
VAL_ULLONG_MAX
#define VAL_ULLONG_MAX -1002
Definition at line 41 of file getconf.c.
VAL_ULONG_MAX
#define VAL_ULONG_MAX -1003
Definition at line 42 of file getconf.c.
Function Documentation
getconf_all()
static int getconf_all (void) static
Definition at line 984 of file getconf.c.
 {
   const struct conf *c;
   char *path;
   int r;
   r = EXECUTION_SUCCESS;
   for (c = vars; c->name != NULL; ++c)
     {
       printf("%-35s", c->name);
       path = "/";       /* XXX for now */
       if (getconf_print (c, path, 1) == EXECUTION_FAILURE)
         r = EXECUTION_FAILURE;
     }
   return (r);
 }
References c, EXECUTION_FAILURE, EXECUTION_SUCCESS, getconf_print(), NULL, printf, and vars.
Referenced by getconf_builtin().
getconf_builtin()
int getconf_builtin (WORD_LIST * list)
Definition at line 1109 of file getconf.c.
 {
   const struct conf *c;
   int r, opt, aflag, vflag;
   char *varg;
   aflag = vflag = 0;
   varg = 0;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "ahv:")) != -1)
     {
       switch (opt)
     {
     case 'a':
       aflag = 1;
       break;
     CASE_HELPOPT;
     case 'h':
       builtin_help ();
       return (EX_USAGE);
     case 'v':
       return (EX_DISKFALLBACK);
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if ((aflag == 0 && list == 0) || (aflag && list) || list_length(list) > 2)
     {
       builtin_usage();
       return (EX_USAGE);
     }
   r = aflag ? getconf_all () : getconf_one (list);
   return r;
 }
References aflag, builtin_help(), builtin_usage(), c, CASE_HELPOPT, EX_DISKFALLBACK, EX_USAGE, getconf_all(), getconf_one(), internal_getopt(), list(), list_length(), loptend, opt, reset_internal_getopt(), and vflag.
getconf_internal()
static int getconf_internal (const struct conf * c, int all) static
Definition at line 920 of file getconf.c.
 {
   long l, val;
   intmax_t v;
   uintmax_t uv;
   unsigned long ul;
 #if HAVE_LONG_LONG_INT
   unsigned long long ull;
   long long ll;
 #endif
   int r;
   val = c->call_name;
   r = EXECUTION_SUCCESS;
   if (val == VAL_ULONG_MAX)
     {
       ul = ULONG_MAX;
       printf ("%lu", ul);
     }
 #if HAVE_LONG_LONG_INT
   else if (val == VAL_ULLONG_MAX)
     {
       ull = ULLONG_MAX;
       printf ("%llu", ull);
     }
   else if (val == VAL_LLONG_MIN || val == VAL_LLONG_MAX)
     {
       ll = (val == VAL_LLONG_MIN) ? LLONG_MIN : LLONG_MAX;
       printf ("%lld", ll);
     }
 #endif
 #if HAVE_LONG_LONG_INT
   else if (val == VAL_SSIZE_MAX)
     {
       ll = SSIZE_MAX;
       printf ("%lld", ll);
     }
   else if (val == VAL_SIZE_MAX)
     {
       ul = SIZE_MAX;
       printf ("%lu", ul);
     }
 #else
   else if (val == VAL_SSIZE_MAX)
     {
       v = SSIZE_MAX;
       printf ("%jd", v);
     }
   else if (val == VAL_SIZE_MAX)
     {
       uv = SIZE_MAX;
       printf ("%ju", uv);
     }
 #endif
   else
     printf ("%ld", val);
   if (r == EXECUTION_SUCCESS)
     printf ("\n");
   return (r);
 }
References c, EXECUTION_SUCCESS, l, LLONG_MAX, LLONG_MIN, printf, SIZE_MAX, SSIZE_MAX, ULLONG_MAX, ULONG_MAX, val, VAL_LLONG_MAX, VAL_LLONG_MIN, VAL_SIZE_MAX, VAL_SSIZE_MAX, VAL_ULLONG_MAX, and VAL_ULONG_MAX.
Referenced by getconf_print().
getconf_one()
static int getconf_one (WORD_LIST * list) static
Definition at line 1002 of file getconf.c.
 {
   const struct conf *c;
   char *vname, *vpath;
   vname = list->word->word;
   vpath = (list->next && list->next->word) ? list->next->word->word : 0;
   for (c = vars; c->name != NULL; ++c)
     {
       if (strcmp (c->name, vname) == 0 || (strncmp (c->name, "_POSIX_", 7) == 0 &&
                       strcmp (c->name + 7, vname) == 0))
     break;
     }
   if (c->name == NULL)
     {
       builtin_error ("%s: unknown variable", vname);
       return (EXECUTION_FAILURE);
     }
   if (c->call_name == PATHCONF && list->next == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   else if (c->call_name != PATHCONF && list->next)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   return (getconf_print (c, vpath, 0));
 }
References builtin_error(), builtin_usage(), c, EX_USAGE, EXECUTION_FAILURE, for(), getconf_print(), list(), node::next, NULL, conf::PATHCONF, strcmp, strncmp(), vars, and vpath.
Referenced by getconf_builtin().
getconf_print()
static int getconf_print (const struct conf * c, const char * vpath, int all) static
Definition at line 1037 of file getconf.c.
 {
   long value;
   size_t clen;
   char *cvalue;
   int cn;
   cn = c->call_name;
   switch (c->call)
     {
     case PATHCONF:
       errno = 0;
       value = pathconf (vpath, cn);
       if (value == -1L)
     {
       if (errno)
         builtin_error ("pathconf %s: %s: %s", c->name, vpath, strerror (errno));
       printf ("undefined\n");
       return (EXECUTION_FAILURE);
     }
       else
         printf ("%ld\n", value);
       return (EXECUTION_SUCCESS);
     case SYSCONF:
       errno = 0;
       value = sysconf (cn);
       if (value == -1L)
     {
       if (errno)
         builtin_error ("%s: %s", c->name, strerror (errno));
       printf ("undefined\n");
       return (EXECUTION_FAILURE);
     }
       else
     printf ("%ld\n", value);
       return (EXECUTION_SUCCESS);
     case CONFSTR:
       errno = 0;
       clen = confstr (cn, (char *) NULL, 0);
       cvalue = (char *) malloc (clen);
       if (cvalue == NULL)
         {
           builtin_error ("memory allocation failure");
           return (EXECUTION_FAILURE);
         }
       if (confstr (c->call_name, cvalue, clen) != clen)
     {
       if (errno != 0)
         builtin_error ("%s: confstr: %s", c->name, strerror (errno));
       printf ("undefined\n");
       return (EXECUTION_FAILURE);
     }
       else
     printf ("%.*s\n", (int) clen, cvalue);
       free (cvalue);
       return (EXECUTION_SUCCESS);
     case CONSTANT:
       return (getconf_internal (c, all));
     case UNDEFINED:
       builtin_error ("%s: undefined", c->name);
       return (EXECUTION_FAILURE);
     }
   /* NOTREACHED */
   return (EX_USAGE);
 }
References builtin_error(), c, conf::CONFSTR, confstr(), conf::CONSTANT, errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, free, getconf_internal(), malloc, NULL, conf::PATHCONF, pathconf(), printf, strerror(), conf::SYSCONF, sysconf(), conf::UNDEFINED, value, and vpath.
Referenced by getconf_all(), and getconf_one().
Variable Documentation
errno
int errno extern
Referenced by getconf_print().
getconf_doc
char* getconf_doc[] static
Initial value:
= {
    "Display values of system limits and options.",
    "",
    "getconf writes the current value of a configurable system limit or",
    "option variable to the standard output.",
    (char *)NULL
}
Definition at line 1148 of file getconf.c.
getconf_struct
struct builtin getconf_struct
Initial value:
= {
    "getconf",
    getconf_builtin,
    BUILTIN_ENABLED,
    getconf_doc,
    "getconf -[ah] or getconf [-v spec] sysvar or getconf [-v spec] pathvar pathname",
    0
}
Definition at line 1148 of file getconf.c.
vars
const struct conf vars[] static
Definition at line 35 of file getconf.c.
Referenced by getconf_all(), getconf_one(), make_env_array_from_var_list(), make_func_export_array(), make_var_export_array(), and simplecmd().