Fennix: Userspace/apps/base/busybox/networking/libiproute/ipneigh.c File Reference
ipneigh.c File Reference
#include "ip_common.h"
#include "common_bufsiz.h"
#include "rt_names.h"
#include "utils.h"
#include <linux/neighbour.h>
#include <net/if_arp.h>
Data Structures
struct filter_t
Macros
#define RTAX_RTTVAR RTAX_HOPS
#define G_filter (*(filter_t*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define NDA_RTA(r) ((struct rtattr*)(((char*)(r)) + NLMSG_ALIGN(sizeof(struct ndmsg))))
#define PRINT_FLAG(f)
#define MAX_ROUNDS 10
Typedefs
typedef struct filter_t filter_t
Enumerations
enum { xshow_stats = 3 }
Functions
static uint32_t rta_getattr_u32 (const struct rtattr *rta)
static int flush_update (void)
static unsigned nud_state_a2n (char *arg)
static int FAST_FUNC print_neigh (const struct sockaddr_nl *who UNUSED_PARAM, struct nlmsghdr *n, void *arg UNUSED_PARAM)
static void ipneigh_reset_filter (void)
static int FAST_FUNC ipneigh_list_or_flush (char **argv, int flush)
int FAST_FUNC do_ipneigh (char **argv)
Variables
struct filter_t FIX_ALIASING
Data Structure Documentation
filter_t
struct filter_t
Definition at line 35 of file ipaddress.c.
Data Fields
family_t family
int family
int flagmask
int flags
char * flushb
int flushe
smallint flushed
int flushed
int flushp
int ifindex
int iif
int index
char * label
inet_prefix mdst
inet_prefix msrc
int oif
smallint oneline
inet_prefix pfx
inet_prefix rdst
inet_prefix rsrc
struct rtnl_handle * rth
inet_prefix rvia
int scope
int scopemask
smallint showqueue
int state
int tb
int unused_only
smallint up
Macro Definition Documentation
G_filter
#define G_filter (*(filter_t*)bb_common_bufsiz1)
Definition at line 46 of file ipneigh.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 47 of file ipneigh.c.
MAX_ROUNDS
#define MAX_ROUNDS 10
Definition at line 225 of file ipneigh.c.
NDA_RTA
#define NDA_RTA (r) ((struct rtattr*)(((char*)(r)) + NLMSG_ALIGN(sizeof(struct ndmsg))))
Definition at line 87 of file ipneigh.c.
PRINT_FLAG
#define PRINT_FLAG (f)
Value:
        if (nud & NUD_##f) { \
            printf("%c"#f, c); \
            c = ','; \
        }
RTAX_RTTVAR
#define RTAX_RTTVAR RTAX_HOPS
Definition at line 25 of file ipneigh.c.
Typedef Documentation
filter_t
typedef struct filter_t filter_t
Definition at line 19 of file ipneigh.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
xshow_stats
Definition at line 17 of file ipneigh.c.
 { xshow_stats = 3 };
Function Documentation
do_ipneigh()
int FAST_FUNC do_ipneigh (char ** argv)
Definition at line 339 of file ipneigh.c.
 {
     static const char ip_neigh_commands[] ALIGN1 =
         /*0-1*/ "show\0"  "flush\0";
     int command_num;
     INIT_G();
     if (!*argv)
         return ipneigh_list_or_flush(argv, 0);
     command_num = index_in_substrings(ip_neigh_commands, *argv);
     switch (command_num) {
         case 0: /* show */
             return ipneigh_list_or_flush(argv + 1, 0);
         case 1: /* flush */
             return ipneigh_list_or_flush(argv + 1, 1);
     }
     invarg_1_to_2(*argv, applet_name);
     return 1;
 }
References ALIGN1, applet_name, argv, index_in_substrings(), INIT_G, invarg_1_to_2(), and ipneigh_list_or_flush().
flush_update()
static int flush_update (void) static
Definition at line 49 of file ipneigh.c.
 {
     if (rtnl_send_check(G_filter.rth, G_filter.flushb, G_filter.flushp) < 0) {
         bb_simple_perror_msg("can't send flush request");
         return -1;
     }
     G_filter.flushp = 0;
     return 0;
 }
References bb_simple_perror_msg(), G_filter, and rtnl_send_check().
Referenced by ipneigh_list_or_flush(), and print_neigh().
ipneigh_list_or_flush()
static int FAST_FUNC ipneigh_list_or_flush (char ** argv, int flush) static
Definition at line 227 of file ipneigh.c.
 {
     static const char keywords[] ALIGN1 =
         /* "ip neigh show/flush" parameters: */
         "to\0" "dev\0"   "nud\0";
     enum {
         KW_to, KW_dev, KW_nud,
     };
     struct rtnl_handle rth;
     struct ndmsg ndm = { 0 };
     char *filter_dev = NULL;
     int state_given = 0;
     int arg;
     ipneigh_reset_filter();
     if (flush && !*argv)
         bb_error_msg_and_die(bb_msg_requires_arg, "\"ip neigh flush\"");
     if (!G_filter.family)
         G_filter.family = preferred_family;
     G_filter.state = (flush) ?
         ~(NUD_PERMANENT|NUD_NOARP) : 0xFF & ~NUD_NOARP;
     while (*argv) {
         arg = index_in_substrings(keywords, *argv);
         if (arg == KW_dev) {
             NEXT_ARG();
             filter_dev = *argv;
         } else if (arg == KW_nud) {
             unsigned state;
             NEXT_ARG();
             if (!state_given) {
                 state_given = 1;
                 G_filter.state = 0;
             }
             if (strcmp(*argv, "all") == 0) {
                 state = ~0;
                 if (flush)
                     state &= ~NUD_NOARP;
             } else {
                 state = nud_state_a2n(*argv);
             }
             if (state == 0)
                 state = 0x100;
             G_filter.state |= state;
         } else {
             if (arg == KW_to) {
                 NEXT_ARG();
             }
             get_prefix(&G_filter.pfx, *argv, G_filter.family);
             if (G_filter.family == AF_UNSPEC)
                 G_filter.family = G_filter.pfx.family;
         }
         argv++;
     }
     xrtnl_open(&rth);
     ll_init_map(&rth);
     if (filter_dev)  {
         G_filter.index = xll_name_to_index(filter_dev);
         if (G_filter.index == 0) {
             bb_error_msg_and_die("can't find device '%s'", filter_dev);
         }
     }
     if (flush) {
         int round = 0;
         char flushb[4096-512];
         G_filter.flushb = flushb;
         G_filter.flushp = 0;
         G_filter.flushe = sizeof(flushb);
         G_filter.state &= ~NUD_FAILED;
         G_filter.rth = &rth;
         while (round < MAX_ROUNDS) {
             xrtnl_wilddump_request(&rth, G_filter.family, RTM_GETNEIGH);
             G_filter.flushed = 0;
             if (xrtnl_dump_filter(&rth, print_neigh, NULL) < 0) {
                 bb_simple_perror_msg_and_die("flush terminated");
             }
             if (G_filter.flushed == 0) {
                 if (round == 0)
                     puts("Nothing to flush");
                 else
                     printf("*** Flush is complete after %d round(s) ***\n", round);
                 return 0;
             }
             round++;
             if (flush_update() < 0)
                 xfunc_die();
             printf("\n*** Round %d, deleting %d entries ***\n", round, G_filter.flushed);
         }
         bb_error_msg_and_die("*** Flush not complete bailing out after %d rounds", MAX_ROUNDS);
     }
     ndm.ndm_family = G_filter.family;
     if (rtnl_dump_request(&rth, RTM_GETNEIGH, &ndm, sizeof(struct ndmsg)) < 0) {
         bb_simple_perror_msg_and_die("can't send dump request");
     }
     if (xrtnl_dump_filter(&rth, print_neigh, NULL) < 0) {
         bb_simple_error_msg_and_die("dump terminated");
     }
     return 0;
 }
References AF_UNSPEC, ALIGN1, argv, bb_error_msg_and_die(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), flush(), flush_update(), G_filter, get_prefix(), index_in_substrings(), ipneigh_reset_filter(), ll_init_map(), MAX_ROUNDS, NEXT_ARG, nud_state_a2n(), NULL, preferred_family, print_neigh(), printf, puts(), round, rtnl_dump_request(), state, strcmp, xfunc_die(), xll_name_to_index(), xrtnl_dump_filter(), xrtnl_open(), and xrtnl_wilddump_request().
Referenced by do_ipneigh().
ipneigh_reset_filter()
static void ipneigh_reset_filter (void) static
Definition at line 219 of file ipneigh.c.
 {
     memset(&G_filter, 0, sizeof(G_filter));
     G_filter.state = ~0;
 }
References G_filter, and memset.
Referenced by ipneigh_list_or_flush().
nud_state_a2n()
static unsigned nud_state_a2n (char * arg) static
Definition at line 59 of file ipneigh.c.
 {
     static const char keywords[] ALIGN1 =
         /* "ip neigh show/flush" parameters: */
         "permanent\0" "reachable\0"   "noarp\0"  "none\0"
         "stale\0"     "incomplete\0"  "delay\0"  "probe\0"
         "failed\0"
         ;
     static uint8_t nuds[] ALIGN1 = {
         NUD_PERMANENT,NUD_REACHABLE, NUD_NOARP,NUD_NONE,
         NUD_STALE,    NUD_INCOMPLETE,NUD_DELAY,NUD_PROBE,
         NUD_FAILED
     };
     int id;
     BUILD_BUG_ON(
         (NUD_PERMANENT|NUD_REACHABLE| NUD_NOARP|NUD_NONE|
         NUD_STALE|    NUD_INCOMPLETE|NUD_DELAY|NUD_PROBE|
         NUD_FAILED) > 0xff
     );
     id = index_in_substrings(keywords, arg);
     if (id < 0)
         bb_error_msg_and_die(bb_msg_invalid_arg_to, arg, "nud state");
     return nuds[id];
 }
References ALIGN1, bb_error_msg_and_die(), BUILD_BUG_ON, and index_in_substrings().
Referenced by ipneigh_list_or_flush().
print_neigh()
static int FAST_FUNC print_neigh (const struct sockaddr_nl *who UNUSED_PARAM, struct nlmsghdr * n, void *arg UNUSED_PARAM) static
Definition at line 92 of file ipneigh.c.
 {
     struct ndmsg *r = NLMSG_DATA(n);
     int len = n->nlmsg_len;
     struct rtattr *tb[NDA_MAX+1];
     if (n->nlmsg_type != RTM_NEWNEIGH && n->nlmsg_type != RTM_DELNEIGH) {
         bb_error_msg_and_die("not RTM_NEWNEIGH: %08x %08x %08x",
                      n->nlmsg_len, n->nlmsg_type,
                      n->nlmsg_flags);
     }
     len -= NLMSG_LENGTH(sizeof(*r));
     if (len < 0) {
         bb_error_msg_and_die("BUG: wrong nlmsg len %d", len);
     }
     if (G_filter.flushb && n->nlmsg_type != RTM_NEWNEIGH)
         return 0;
     if (G_filter.family && G_filter.family != r->ndm_family)
         return 0;
     if (G_filter.index && G_filter.index != r->ndm_ifindex)
         return 0;
     if (!(G_filter.state&r->ndm_state)
      && !(r->ndm_flags & NTF_PROXY)
      && (r->ndm_state || !(G_filter.state & 0x100))
      && (r->ndm_family != AF_DECnet)
     ) {
         return 0;
     }
     parse_rtattr(tb, NDA_MAX, NDA_RTA(r), n->nlmsg_len - NLMSG_LENGTH(sizeof(*r)));
     if (tb[NDA_DST]) {
         if (G_filter.pfx.family) {
             inet_prefix dst;
             memset(&dst, 0, sizeof(dst));
             dst.family = r->ndm_family;
             memcpy(&dst.data, RTA_DATA(tb[NDA_DST]), RTA_PAYLOAD(tb[NDA_DST]));
             if (inet_addr_match(&dst, &G_filter.pfx, G_filter.pfx.bitlen))
                 return 0;
         }
     }
     if (G_filter.unused_only && tb[NDA_CACHEINFO]) {
         struct nda_cacheinfo *ci = RTA_DATA(tb[NDA_CACHEINFO]);
         if (ci->ndm_refcnt)
             return 0;
     }
     if (G_filter.flushb) {
         struct nlmsghdr *fn;
         if (NLMSG_ALIGN(G_filter.flushp) + n->nlmsg_len > G_filter.flushe) {
             if (flush_update())
                 return -1;
         }
         fn = (struct nlmsghdr*)(G_filter.flushb + NLMSG_ALIGN(G_filter.flushp));
         memcpy(fn, n, n->nlmsg_len);
         fn->nlmsg_type = RTM_DELNEIGH;
         fn->nlmsg_flags = NLM_F_REQUEST;
         fn->nlmsg_seq = ++(G_filter.rth->seq);
         G_filter.flushp = (((char*)fn) + n->nlmsg_len) - G_filter.flushb;
         G_filter.flushed++;
         if (xshow_stats < 2)
             return 0;
     }
     if (tb[NDA_DST]) {
         printf("%s ",
                format_host(r->ndm_family,
                    RTA_PAYLOAD(tb[NDA_DST]),
                    RTA_DATA(tb[NDA_DST]))
         );
     }
     if (!G_filter.index && r->ndm_ifindex)
         printf("dev %s ", ll_index_to_name(r->ndm_ifindex));
     if (tb[NDA_LLADDR]) {
         SPRINT_BUF(b1);
         printf("lladdr %s", ll_addr_n2a(RTA_DATA(tb[NDA_LLADDR]),
                         RTA_PAYLOAD(tb[NDA_LLADDR]),
                         ARPHRD_ETHER,
                         b1, sizeof(b1)));
     }
     if (r->ndm_flags & NTF_ROUTER) {
         printf(" router");
     }
     if (r->ndm_flags & NTF_PROXY) {
         printf(" proxy");
     }
     if (tb[NDA_CACHEINFO] && xshow_stats) {
         struct nda_cacheinfo *ci = RTA_DATA(tb[NDA_CACHEINFO]);
         int hz = get_hz();
         if (ci->ndm_refcnt)
             printf(" ref %d", ci->ndm_refcnt);
         printf(" used %d/%d/%d", ci->ndm_used/hz,
                ci->ndm_confirmed/hz, ci->ndm_updated/hz);
     }
     if (tb[NDA_PROBES] && xshow_stats) {
         uint32_t p = rta_getattr_u32(tb[NDA_PROBES]);
         printf(" probes %u", p);
     }
     /*if (r->ndm_state)*/ {
         int nud = r->ndm_state;
         char c = ' ';
 #define PRINT_FLAG(f) \
         if (nud & NUD_##f) { \
             printf("%c"#f, c); \
             c = ','; \
         }
         PRINT_FLAG(INCOMPLETE);
         PRINT_FLAG(REACHABLE);
         PRINT_FLAG(STALE);
         PRINT_FLAG(DELAY);
         PRINT_FLAG(PROBE);
         PRINT_FLAG(FAILED);
         PRINT_FLAG(NOARP);
         PRINT_FLAG(PERMANENT);
 #undef PRINT_FLAG
     }
     bb_putchar('\n');
     return 0;
 }
References AF_DECnet, ARPHRD_ETHER, bb_error_msg_and_die(), bb_putchar(), c, DELAY, dst, flush_update(), format_host, G_filter, get_hz(), if(), INCOMPLETE, inet_addr_match(), len, ll_addr_n2a(), ll_index_to_name(), memcpy, memset, n, NDA_RTA, NLM_F_REQUEST, NLMSG_DATA, nlmsghdr::nlmsg_flags, nlmsghdr::nlmsg_seq, nlmsghdr::nlmsg_type, p, parse_rtattr(), PRINT_FLAG, printf, PROBE, RTA_DATA, rta_getattr_u32(), SPRINT_BUF, and xshow_stats.
Referenced by ipneigh_list_or_flush().
rta_getattr_u32()
static uint32_t rta_getattr_u32 (const struct rtattr * rta) inline static
Definition at line 19 of file ipneigh.c.
 {
     return *(uint32_t *)RTA_DATA(rta);
 }
Referenced by print_neigh().
Variable Documentation
FIX_ALIASING
struct filter_t FIX_ALIASING