Fennix: Userspace/apps/base/bash/examples/loadables/rm.c File Reference
rm.c File Reference
#include "config.h"
#include <stdio.h>
#include <errno.h>
#include <dirent.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
#include "bashgetopt.h"
Functions
static int rm_file (const char *fname)
static int _remove_directory (const char *dirname)
int rm_builtin (WORD_LIST *list)
Variables
int errno
static int force
static int recursive
char * rm_doc []
struct builtin rm_struct
Function Documentation
_remove_directory()
static int _remove_directory (const char * dirname) static
Definition at line 42 of file rm.c.
 {
   DIR *dir;
   struct dirent *dp;
   size_t dirlen;
   int err;
   dirlen = strlen (dirname);
   err = 0;
   if ((dir = opendir(dirname)))
     {
       while ((dp = readdir(dir)))
     {
 #ifdef __GNUC__
       char fname[dirlen + 1 + strlen (dp->d_name) + 1];
 #else
       char *fname;
       int fnsize;
 #endif
       QUIT;
           if (*dp->d_name == '.' && (dp->d_name[1] == 0 || (dp->d_name[1] == '.' && dp->d_name[2] == 0)))
             continue;
 #ifdef __GNUC__
       snprintf(fname, sizeof (fname), "%s/%s", dirname, dp->d_name);
 #else
       fnsize = dirlen + 1 + strlen (dp->d_name) + 1;
           fname = xmalloc (fnsize);
       snprintf(fname, fnsize, "%s/%s", dirname, dp->d_name);
 #endif
            if (rm_file (fname) && force == 0)
              err = 1;
 #ifndef __GNUC__
            free (fname);
 #endif
        QUIT;
         }
       closedir(dir);
       if (err == 0 && rmdir (dirname) && force == 0)
         err = 1;
     }
   else if (force == 0)
     err = 1;
   if (err)
     builtin_error ("%s: %s", dirname, strerror (errno));
   return err;
 }
References builtin_error(), closedir(), dirent::d_name, dir, dirname, err(), errno, fname, force, free, opendir(), QUIT, readdir(), rm_file(), rmdir(), snprintf(), strerror(), strlen(), and xmalloc.
Referenced by rm_file().
rm_builtin()
int rm_builtin (WORD_LIST * list)
Definition at line 117 of file rm.c.
 {
   const char *name;
   WORD_LIST *l;
   int rval, opt;
   recursive = force = 0;
   rval = EXECUTION_SUCCESS;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "Rrfi")) != -1)
     {
       switch (opt)
     {
     case 'R':
     case 'r':
       recursive = 1;
       break;
     case 'f':
       force = 1;
       break;
     case 'i':
       return (EX_DISKFALLBACK);
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list == 0)
     {
       if (force == 0)
     {
           builtin_usage ();
           return (EXECUTION_FAILURE);
     }
       return (EXECUTION_SUCCESS);
     }
   for (l = list; l; l = l->next)
     {
       QUIT;
       if (rm_file(l->word->word) && force == 0)
     rval = EXECUTION_FAILURE;
     }
   return rval;
 }
References builtin_usage(), CASE_HELPOPT, EX_DISKFALLBACK, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, force, internal_getopt(), l, list(), loptend, opt, QUIT, recursive, reset_internal_getopt(), and rm_file().
rm_file()
static int rm_file (const char * fname) static
Definition at line 98 of file rm.c.
 {
   if (unlink (fname) == 0)
     return 0;
   QUIT;
   /* If FNAME is a directory glibc returns EISDIR but correct POSIX value
      would be EPERM.  If we get that error and FNAME is a directory and -r
      was supplied, recursively remove the directory and its contents */
   if ((errno == EISDIR || errno == EPERM) && recursive && file_isdir (fname))
     return _remove_directory(fname);
   else if (force)
     return 0;
   builtin_error ("%s: %s", fname, strerror (errno));
   return 1;
 }
References _remove_directory(), builtin_error(), EISDIR, EPERM, errno, file_isdir(), fname, force, QUIT, recursive, strerror(), and unlink().
Referenced by _remove_directory(), and rm_builtin().
Variable Documentation
errno
int errno extern
Referenced by _remove_directory(), and rm_file().
force
int force static
Definition at line 39 of file rm.c.
Referenced by _remove_directory(), _rl_set_cursor(), _rl_set_insert_mode(), _rl_set_localevars(), get_cwd(), give_terminal_to(), initialize_job_control(), mark_dead_jobs_as_notified(), rm_builtin(), and rm_file().
recursive
int recursive static
Definition at line 39 of file rm.c.
Referenced by rm_builtin(), and rm_file().
rm_doc
char* rm_doc[]
Initial value:
= {
    "Remove files.",
    "",
    "rm removes the files specified as arguments.",
    (char *)NULL
}
Definition at line 169 of file rm.c.
rm_struct
struct builtin rm_struct
Initial value:
= {
    "rm",
    rm_builtin,
    BUILTIN_ENABLED,
    rm_doc,
    "rm [-rf] file ...",
    0
}
Definition at line 169 of file rm.c.