Fennix Userspace: Userspace/musl/src/stdlib/wcstol.c File Reference
wcstol.c File Reference
#include "stdio_impl.h"
#include "intscan.h"
#include "shgetc.h"
#include <inttypes.h>
#include <limits.h>
#include <wctype.h>
#include <wchar.h>
Functions
static size_t do_read (FILE *f, unsigned char *buf, size_t len)
static unsigned long long wcstox (const wchar_t *s, wchar_t **p, int base, unsigned long long lim)
unsigned long long wcstoull (const wchar_t *restrict s, wchar_t **restrict p, int base)
long long wcstoll (const wchar_t *restrict s, wchar_t **restrict p, int base)
unsigned long wcstoul (const wchar_t *restrict s, wchar_t **restrict p, int base)
long wcstol (const wchar_t *restrict s, wchar_t **restrict p, int base)
intmax_t wcstoimax (const wchar_t *restrict s, wchar_t **restrict p, int base)
uintmax_t wcstoumax (const wchar_t *restrict s, wchar_t **restrict p, int base)
Function Documentation
do_read()
static size_t do_read (FILE * f, unsigned char * buf, size_t len) static
Definition at line 13 of file wcstol.c.
 {
     size_t i;
     const wchar_t *wcs = f->cookie;
     if (!wcs[0]) wcs=L"@";
     for (i=0; i<f->buf_size && wcs[i]; i++)
         f->buf[i] = wcs[i] < 128 ? wcs[i] : '@';
     f->rpos = f->buf;
     f->rend = f->buf + i;
     f->cookie = (void *)(wcs+i);
     if (i && len) {
         *buf = *f->rpos++;
         return 1;
     }
     return 0;
 }
References _IO_FILE::buf, buf, _IO_FILE::buf_size, _IO_FILE::cookie, f, i, _IO_FILE::rend, and _IO_FILE::rpos.
Referenced by wcstox().
wcstoimax()
intmax_t wcstoimax (const wchar_t *restrict s, wchar_t **restrict p, int base)
Definition at line 73 of file wcstol.c.
 {
     return wcstoll(s, p, base);
 }
References p, and wcstoll().
wcstol()
long wcstol (const wchar_t *restrict s, wchar_t **restrict p, int base)
Definition at line 68 of file wcstol.c.
 {
     return wcstox(s, p, base, 0UL+LONG_MIN);
 }
References LONG_MIN, p, and wcstox().
wcstoll()
long long wcstoll (const wchar_t *restrict s, wchar_t **restrict p, int base)
Definition at line 58 of file wcstol.c.
 {
     return wcstox(s, p, base, LLONG_MIN);
 }
References LLONG_MIN, p, and wcstox().
Referenced by wcstoimax().
wcstoul()
unsigned long wcstoul (const wchar_t *restrict s, wchar_t **restrict p, int base)
Definition at line 63 of file wcstol.c.
 {
     return wcstox(s, p, base, ULONG_MAX);
 }
References p, ULONG_MAX, and wcstox().
wcstoull()
unsigned long long wcstoull (const wchar_t *restrict s, wchar_t **restrict p, int base)
Definition at line 53 of file wcstol.c.
 {
     return wcstox(s, p, base, ULLONG_MAX);
 }
References p, ULLONG_MAX, and wcstox().
Referenced by wcstoumax().
wcstoumax()
uintmax_t wcstoumax (const wchar_t *restrict s, wchar_t **restrict p, int base)
Definition at line 78 of file wcstol.c.
 {
     return wcstoull(s, p, base);
 }
References p, and wcstoull().
wcstox()
static unsigned long long wcstox (const wchar_t * s, wchar_t ** p, int base, unsigned long long lim) static
Definition at line 32 of file wcstol.c.
 {
     wchar_t *t = (wchar_t *)s;
     unsigned char buf[64];
     FILE f = {0};
     f.flags = 0;
     f.rpos = f.rend = f.buf = buf + 4;
     f.buf_size = sizeof buf - 4;
     f.lock = -1;
     f.read = do_read;
     while (iswspace(*t)) t++;
     f.cookie = (void *)t;
     shlim(&f, 0);
     unsigned long long y = __intscan(&f, base, 1, lim);
     if (p) {
         size_t cnt = shcnt(&f);
         *p = cnt ? t + cnt : (wchar_t *)s;
     }
     return y;
 }
References __intscan(), _IO_FILE::buf, buf, _IO_FILE::buf_size, cnt, _IO_FILE::cookie, do_read(), f, _IO_FILE::flags, iswspace(), _IO_FILE::lock, p, _IO_FILE::read, _IO_FILE::rend, _IO_FILE::rpos, shcnt, shlim, and y.
Referenced by wcstol(), wcstoll(), wcstoul(), and wcstoull().