Fennix: Userspace/musl/src/stdio/fopencookie.c File Reference
fopencookie.c File Reference
#include "stdio_impl.h"
#include <stdlib.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
Data Structures
struct fcookie
struct cookie_FILE
Macros
#define _GNU_SOURCE
Functions
static size_t cookieread (FILE *f, unsigned char *buf, size_t len)
static size_t cookiewrite (FILE *f, const unsigned char *buf, size_t len)
static off_t cookieseek (FILE *f, off_t off, int whence)
static int cookieclose (FILE *f)
FILE * fopencookie (void *cookie, const char *mode, cookie_io_functions_t iofuncs)
Data Structure Documentation
fcookie
struct fcookie
Definition at line 9 of file fopencookie.c.
Data Fields
void * cookie
cookie_io_functions_t iofuncs
cookie_FILE
struct cookie_FILE
Definition at line 14 of file fopencookie.c.
Data Fields
unsigned char buf[UNGET+BUFSIZ]
FILE f
struct fcookie fc
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file fopencookie.c.
Function Documentation
cookieclose()
static int cookieclose (FILE * f) static
Definition at line 91 of file fopencookie.c.
 {
     struct fcookie *fc = f->cookie;
     if (fc->iofuncs.close) return fc->iofuncs.close(fc->cookie);
     return 0;
 }
References fcookie::cookie, f, and fcookie::iofuncs.
Referenced by fopencookie().
cookieread()
static size_t cookieread (FILE * f, unsigned char * buf, size_t len) static
Definition at line 20 of file fopencookie.c.
 {
     struct fcookie *fc = f->cookie;
     ssize_t ret = -1;
     size_t remain = len, readlen = 0;
     size_t len2 = len - !!f->buf_size;
     if (!fc->iofuncs.read) goto bail;
     if (len2) {
         ret = fc->iofuncs.read(fc->cookie, (char *) buf, len2);
         if (ret <= 0) goto bail;
         readlen += ret;
         remain -= ret;
     }
     if (!f->buf_size || remain > !!f->buf_size) return readlen;
     f->rpos = f->buf;
     ret = fc->iofuncs.read(fc->cookie, (char *) f->rpos, f->buf_size);
     if (ret <= 0) goto bail;
     f->rend = f->rpos + ret;
     buf[readlen++] = *f->rpos++;
     return readlen;
 bail:
     f->flags |= ret == 0 ? F_EOF : F_ERR;
     f->rpos = f->rend = f->buf;
     return readlen;
 }
References buf, fcookie::cookie, f, F_EOF, F_ERR, fcookie::iofuncs, and len.
Referenced by fopencookie().
cookieseek()
static off_t cookieseek (FILE * f, off_t off, int whence) static
Definition at line 73 of file fopencookie.c.
 {
     struct fcookie *fc = f->cookie;
     int res;
     if (whence > 2U) {
         errno = EINVAL;
         return -1;
     }
     if (!fc->iofuncs.seek) {
         errno = ENOTSUP;
         return -1;
     }
     res = fc->iofuncs.seek(fc->cookie, &off, whence);
     if (res < 0)
         return res;
     return off;
 }
References fcookie::cookie, EINVAL, ENOTSUP, errno, f, fcookie::iofuncs, and off.
Referenced by fopencookie().
cookiewrite()
static size_t cookiewrite (FILE * f, const unsigned char * buf, size_t len) static
Definition at line 54 of file fopencookie.c.
 {
     struct fcookie *fc = f->cookie;
     ssize_t ret;
     size_t len2 = f->wpos - f->wbase;
     if (!fc->iofuncs.write) return len;
     if (len2) {
         f->wpos = f->wbase;
         if (cookiewrite(f, f->wpos, len2) < len2) return 0;
     }
     ret = fc->iofuncs.write(fc->cookie, (const char *) buf, len);
     if (ret < 0) {
         f->wpos = f->wbase = f->wend = 0;
         f->flags |= F_ERR;
         return 0;
     }
     return ret;
 }
References buf, fcookie::cookie, f, F_ERR, fcookie::iofuncs, and len.
Referenced by fopencookie().
fopencookie()
FILE* fopencookie (void * cookie, const char * mode, cookie_io_functions_t iofuncs)
Definition at line 98 of file fopencookie.c.
 {
     struct cookie_FILE *f;
     /* Check for valid initial mode character */
     if (!strchr("rwa", *mode)) {
         errno = EINVAL;
         return 0;
     }
     /* Allocate FILE+fcookie+buffer or fail */
     if (!(f=malloc(sizeof *f))) return 0;
     /* Zero-fill only the struct, not the buffer */
     memset(&f->f, 0, sizeof f->f);
     /* Impose mode restrictions */
     if (!strchr(mode, '+')) f->f.flags = (*mode == 'r') ? F_NOWR : F_NORD;
     /* Set up our fcookie */
     f->fc.cookie = cookie;
     f->fc.iofuncs = iofuncs;
     f->f.fd = -1;
     f->f.cookie = &f->fc;
     f->f.buf = f->buf + UNGET;
     f->f.buf_size = sizeof f->buf - UNGET;
     f->f.lbf = EOF;
     /* Initialize op ptrs. No problem if some are unneeded. */
     f->f.read = cookieread;
     f->f.write = cookiewrite;
     f->f.seek = cookieseek;
     f->f.close = cookieclose;
     /* Add new FILE to open file list */
     return __ofl_add(&f->f);
 }
References __ofl_add(), cookieclose(), cookieread(), cookieseek(), cookiewrite(), EINVAL, EOF, errno, f, F_NORD, F_NOWR, malloc, memset, strchr(), and UNGET.