Fennix Userspace: sigaction Struct Reference
sigaction Struct Reference
#include <signal.h>
Data Fields
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
} __sa_handler
sigset_t sa_mask
int sa_flags
void(* sa_restorer)(void)
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
};
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
} __sa_handler
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
} __sa_handler
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
} __sa_handler
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
} __sa_handler
union {
void(* sa_handler)(int)
void(* sa_sigaction)(int, siginfo_t *, void *)
};
Detailed Description
Definition at line 218 of file signal.h.
Field Documentation
union { ... }
union { ... }
[1/5]
union { ... } sigaction::__sa_handler
[2/5]
union { ... } sigaction::__sa_handler
[3/5]
union { ... } sigaction::__sa_handler
[4/5]
union { ... } sigaction::__sa_handler
[5/5]
union { ... } sigaction::__sa_handler
sa_flags
int sigaction::sa_flags
Definition at line 224 of file signal.h.
Referenced by __membarrier(), __synccall(), abort(), init_cancellation(), initialize_terminating_signals(), main(), popen(), mlibc::anonymous_namespace{pthread-stubs.cpp}::PthreadSignalInstaller::PthreadSignalInstaller(), reset_terminating_signals(), rl_set_sighandler(), sigignore(), siginterrupt(), signal(), signal_handler(), system(), and worker().
sa_handler
void(* sigaction::sa_handler)(int)
Definition at line 156 of file signal.h.
Referenced by __membarrier(), __synccall(), abort(), child(), initialize_terminating_signals(), popen(), reset_terminating_signals(), rl_set_sighandler(), sigignore(), signal(), signal_handler(), sigstat(), and system().
sa_mask
sigset_t sigaction::sa_mask
Definition at line 223 of file signal.h.
Referenced by __membarrier(), __synccall(), abort(), init_cancellation(), initialize_terminating_signals(), main(), popen(), reset_terminating_signals(), rl_set_sighandler(), sigignore(), signal(), signal_handler(), system(), and worker().
sa_restorer
void(* sigaction::sa_restorer)(void) (void)
Definition at line 225 of file signal.h.
sa_sigaction
void(* sigaction::sa_sigaction)(int, siginfo_t *, void *)
Definition at line 159 of file signal.h.
Referenced by main(), mlibc::anonymous_namespace{pthread-stubs.cpp}::PthreadSignalInstaller::PthreadSignalInstaller(), and worker().
The documentation for this struct was generated from the following file:
Userspace/mlibc/abis/linux/signal.h