Fennix: Userspace/apps/base/busybox/libbb/uuencode.c File Reference
uuencode.c File Reference
#include "libbb.h"
Macros
#define exit_char ((int)(signed char)flags)
#define uu_style_end (flags & BASE64_FLAG_UU_STOP)
#define base32 (flags & BASE64_32)
Functions
void FAST_FUNC bb_uuencode (char *p, const void *src, int length, const char *tbl)
char *FAST_FUNC decode_base64 (char *dst, const char **pp_src)
void FAST_FUNC read_base64 (FILE *src_stream, FILE *dst_stream, int flags)
Variables
const char bb_uuenc_tbl_base64[] ALIGN1
Macro Definition Documentation
base32
#define base32 (flags & BASE64_32)
exit_char
#define exit_char ((int)(signed char)flags)
uu_style_end
#define uu_style_end (flags & BASE64_FLAG_UU_STOP)
Function Documentation
bb_uuencode()
void FAST_FUNC bb_uuencode (char * p, const void * src, int length, const char * tbl)
Definition at line 51 of file uuencode.c.
 {
     const unsigned char *s = src;
     /* Transform the 3x8 bits to 4x6 bits */
     while (length > 0) {
         unsigned s1, s2;
         /* Are s[1], s[2] valid or should be assumed 0? */
         s1 = s2 = 0;
         length -= 3; /* can be >=0, -1, -2 */
         if (length >= -1) {
             s1 = s[1];
             if (length >= 0)
                 s2 = s[2];
         }
         *p++ = tbl[s[0] >> 2];
         *p++ = tbl[((s[0] & 3) << 4) + (s1 >> 4)];
         *p++ = tbl[((s1 & 0xf) << 2) + (s2 >> 6)];
         *p++ = tbl[s2 & 0x3f];
         s += 3;
     }
     /* Zero-terminate */
     *p = '\0';
     /* If length is -2 or -1, pad last char or two */
     while (length) {
         *--p = tbl[64];
         length++;
     }
 }
References p, s, s1, s2, and src.
Referenced by encode_n_base64(), and uuencode_main().
decode_base64()
char* FAST_FUNC decode_base64 (char * dst, const char ** pp_src)
Definition at line 90 of file uuencode.c.
 {
     const char *src = pp_src ? *pp_src : dst; /* for httpd.c, support NULL 2nd param */
     unsigned ch = 0;
     unsigned t;
     int i = 0;
     while ((t = (unsigned char)*src) != '\0') {
         src++;
         /* "if" forest is faster than strchr(bb_uuenc_tbl_base64, t) */
         if (t >= '0' && t <= '9')
             t = t - '0' + 52;
         else if (t >= 'A' && t <= 'Z')
             t = t - 'A';
         else if (t >= 'a' && t <= 'z')
             t = t - 'a' + 26;
         else if (t == '+')
             t = 62;
         else if (t == '/')
             t = 63;
         else if (t == '=' && (i == 3 || (i == 2 && *src == '=')))
             /* the above disallows "==AA", "A===", "AA=A" etc */
             t = 0x1000000;
         else
 //TODO: add BASE64_FLAG_foo to die on bad char?
             continue;
         ch = (ch << 6) | t;
         i = (i + 1) & 3;
         if (i == 0) {
             *dst++ = (char) (ch >> 16);
             *dst++ = (char) (ch >> 8);
             *dst++ = (char) ch;
             if (ch & 0x1000000) { /* was last input char '='? */
                 dst--;
                 if (ch & (0x1000000 << 6)) /* was it "=="? */
                     dst--;
                 break;
             }
             ch = 0;
         }
     }
     /* i is zero here if full 4-char block was decoded */
     if (pp_src)
         *pp_src = src - i; /* -i signals truncation: e.g. "MQ" and "MQ=" (correct encoding is "MQ==" -> "1") */
     return dst;
 }
References dst, i, src, and t.
Referenced by read_base64().
read_base64()
void FAST_FUNC read_base64 (FILE * src_stream, FILE * dst_stream, int flags)
Definition at line 207 of file uuencode.c.
 {
 /* Note that EOF _can_ be passed as exit_char too */
 #define exit_char    ((int)(signed char)flags)
 #define uu_style_end (flags & BASE64_FLAG_UU_STOP)
 #define base32       (flags & BASE64_32)
     /* uuencoded files have 61 byte lines.
      * base32/64 have 76 byte lines by default.
      * Use 80 byte buffer to process one line at a time.
      */
     enum { BUFFER_SIZE = 80 };
     /* decoded data is shorter than input, can use single buffer for both */
     char buf[BUFFER_SIZE + 2];
     int term_seen = 0;
     int in_count = 0;
     while (1) {
         char *out_tail;
         const char *in_tail;
         while (in_count < BUFFER_SIZE) {
             int ch = fgetc(src_stream);
             if (ch == exit_char) {
                 if (in_count == 0)
                     return;
                 term_seen = 1;
                 break;
             }
             if (ch == EOF) {
                 term_seen = 1;
                 break;
             }
             /* Prevent "====" line to be split: stop if we see '\n'.
              * We can also skip other whitespace and skirt the problem
              * of files with NULs by stopping on any control char or space:
              */
             if (ch <= ' ')
                 break;
             buf[in_count++] = ch;
         }
         buf[in_count] = '\0';
         /* Did we encounter "====" line? */
         if (uu_style_end && strcmp(buf, "====") == 0)
             return;
         in_tail = buf;
 #if ENABLE_BASE32
         if (base32)
             out_tail = decode_base32(buf, &in_tail);
         else
 #endif
             out_tail = decode_base64(buf, &in_tail);
         fwrite(buf, (out_tail - buf), 1, dst_stream);
         if (term_seen) {
             /* Did we consume ALL characters? */
             if (*in_tail == '\0')
                 return;
             /* No */
             bb_simple_error_msg_and_die("truncated input");
         }
         /* It was partial decode */
         in_count = strlen(in_tail);
         memmove(buf, in_tail, in_count);
     }
 }
References base32, bb_simple_error_msg_and_die(), buf, BUFFER_SIZE, decode_base32(), decode_base64(), EOF, exit_char, fgetc, fwrite(), memmove, strcmp, strlen(), and uu_style_end.
Referenced by parse().
Variable Documentation
ALIGN1
const char bb_uuenc_tbl_std [] ALIGN1
Initial value:
= {
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
    'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
    'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
    'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
    'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
    'w', 'x', 'y', 'z', '0', '1', '2', '3',
    '4', '5', '6', '7', '8', '9', '+', '/',
    '='
}
Definition at line 22 of file uuencode.c.