Fennix: Userspace/apps/base/bash/examples/loadables/head.c File Reference
head.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixstat.h"
#include "filecntl.h"
#include "bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "chartypes.h"
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Functions
static void munge_list (WORD_LIST *list)
static int file_head (FILE *fp, int cnt)
int head_builtin (WORD_LIST *list)
Variables
int errno
char * head_doc []
struct builtin head_struct
Function Documentation
file_head()
static int file_head (FILE * fp, int cnt) static
Definition at line 72 of file head.c.
 {
   int ch;
   while (cnt--)
     {
       while ((ch = getc (fp)) != EOF)
     {
       QUIT;
       if (putchar (ch) == EOF)
         {
           builtin_error ("write error: %s", strerror (errno));
           return EXECUTION_FAILURE;
         }
       QUIT;
       if (ch == '\n')
         break;
     }
     }
   return (EXECUTION_SUCCESS);
 }
References builtin_error(), cnt, EOF, errno, EXECUTION_FAILURE, EXECUTION_SUCCESS, getc(), putchar(), QUIT, and strerror().
Referenced by head_builtin().
head_builtin()
int head_builtin (WORD_LIST * list)
Definition at line 97 of file head.c.
 {
   int nline, opt, rval;
   WORD_LIST *l;
   FILE *fp;
   char *t;
   munge_list (list);    /* change -num into -n num */
   reset_internal_getopt ();
   nline = 10;
   while ((opt = internal_getopt (list, "n:")) != -1)
     {
       switch (opt)
     {
     case 'n':
       nline = atoi (list_optarg);
       if (nline <= 0)
         {
           builtin_error ("bad line count: %s", list_optarg);
           return (EX_USAGE);
         }
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list == 0)
     return (file_head (stdin, nline));
   for (rval = EXECUTION_SUCCESS, opt = 1, l = list; l; l = l->next)
     {
       fp = fopen (l->word->word, "r");
       if (fp == NULL)
     {
       builtin_error ("%s: %s", l->word->word, strerror (errno));
       continue;
     }
       if (list->next)   /* more than one file */
     {
       printf ("%s==> %s <==\n", opt ? "" : "\n", l->word->word);
       opt = 0;
     }
       QUIT;
       rval = file_head (fp, nline);
       fclose (fp);
     }
   return (rval);
 }
References atoi(), builtin_error(), builtin_usage(), CASE_HELPOPT, errno, EX_USAGE, EXECUTION_SUCCESS, fclose(), file_head(), fopen(), internal_getopt(), list_optarg, loptend, munge_list(), word_list::next, NULL, printf, QUIT, reset_internal_getopt(), stdin, strerror(), t, word_desc::word, and word_list::word.
munge_list()
static void munge_list (WORD_LIST * list) static
Definition at line 49 of file head.c.
 {
   WORD_LIST *l, *nl;
   WORD_DESC *wd;
   char *arg;
   for (l = list; l; l = l->next)
     {
       arg = l->word->word;
       if (arg[0] != '-' || arg[1] == '-' || (DIGIT(arg[1]) == 0))
         return;
       /* We have -[0-9]* */
       wd = make_bare_word (arg+1);
       nl = make_word_list (wd, l->next);
       l->word->word[1] = 'n';
       l->word->word[2] = '\0';
       l->next = nl;
       l = nl;   /* skip over new argument */
     }
 }
References DIGIT, make_bare_word(), make_word_list(), word_list::next, word_desc::word, and word_list::word.
Referenced by head_builtin().
Variable Documentation
errno
int errno extern
Referenced by file_head(), and head_builtin().
head_doc
char* head_doc[]
Initial value:
= {
    "Display lines from beginning of file.",
    "",
    "Copy the first N lines from the input files to the standard output.",
    "N is supplied as an argument to the `-n' option.  If N is not given,",
    "the first ten lines are copied.",
    (char *)NULL
}
Definition at line 154 of file head.c.
head_struct
struct builtin head_struct
Initial value:
= {
    "head",
    head_builtin,
    BUILTIN_ENABLED,
    head_doc,
    "head [-n num] [file ...]",
    0
}
Definition at line 154 of file head.c.