Fennix: Userspace/apps/base/busybox/miscutils/strings.c File Reference
strings.c File Reference
#include "libbb.h"
Macros
#define WHOLE_FILE 1
#define PRINT_NAME 2
#define PRINT_OFFSET 4
#define SIZE 8
#define PRINT_RADIX 16
Functions
int strings_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
PRINT_NAME
#define PRINT_NAME 2
Definition at line 35 of file strings.c.
PRINT_OFFSET
#define PRINT_OFFSET 4
Definition at line 36 of file strings.c.
PRINT_RADIX
#define PRINT_RADIX 16
Definition at line 38 of file strings.c.
SIZE
#define SIZE 8
Definition at line 37 of file strings.c.
WHOLE_FILE
#define WHOLE_FILE 1
Definition at line 34 of file strings.c.
Function Documentation
strings_main()
int strings_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 41 of file strings.c.
 {
     int n, c, status = EXIT_SUCCESS;
     unsigned count;
     off_t offset;
     FILE *file;
     char *string;
     const char *fmt = "%s: ";
     const char *n_arg = "4";
     /* default for -o */
     const char *radix = "o";
     char *radix_fmt;
     getopt32(argv, "afon:t:", &n_arg, &radix);
     /* -a is our default behaviour */
     /*argc -= optind;*/
     argv += optind;
     n = xatou_range(n_arg, 1, INT_MAX);
     string = xzalloc(n + 1);
     n--;
     if ((radix[0] != 'd' && radix[0] != 'o' && radix[0] != 'x') || radix[1] != 0)
         bb_show_usage();
     radix_fmt = xasprintf("%%7"OFF_FMT"%s ", radix);
     if (!*argv) {
         fmt = "{%s}: ";
         *--argv = (char *)bb_msg_standard_input;
     }
     do {
         file = fopen_or_warn_stdin(*argv);
         if (!file) {
             status = EXIT_FAILURE;
             continue;
         }
         offset = 0;
         count = 0;
         do {
             c = fgetc(file);
             if (isprint_asciionly(c) || c == '\t') {
                 if (count > n) {
                     bb_putchar(c);
                 } else {
                     string[count] = c;
                     if (count == n) {
                         if (option_mask32 & PRINT_NAME) {
                             printf(fmt, *argv);
                         }
                         if (option_mask32 & (PRINT_OFFSET | PRINT_RADIX)) {
                             printf(radix_fmt, offset - n);
                         }
                         fputs_stdout(string);
                     }
                     count++;
                 }
             } else {
                 if (count > n) {
                     bb_putchar('\n');
                 }
                 count = 0;
             }
             offset++;
         } while (c != EOF);
         fclose_if_not_stdin(file);
     } while (*++argv);
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(string);
         free(radix_fmt);
     }
     fflush_stdout_and_exit(status);
 }
References argv, bb_putchar(), bb_show_usage(), c, count, EOF, EXIT_FAILURE, EXIT_SUCCESS, fclose_if_not_stdin(), fflush_stdout_and_exit(), fgetc, fopen_or_warn_stdin(), fputs_stdout(), free, getopt32(), INT_MAX, isprint_asciionly, n, OFF_FMT, offset, optind, option_mask32, PRINT_NAME, PRINT_OFFSET, PRINT_RADIX, printf, status, string, xasprintf(), and xzalloc().