Fennix: Userspace/musl/src/thread/__wait.c File Reference
__wait.c File Reference
#include "pthread_impl.h"
Functions
void __wait (volatile int *addr, volatile int *waiters, int val, int priv)
Function Documentation
__wait()
void __wait (volatile int * addr, volatile int * waiters, int val, int priv)
Definition at line 3 of file __wait.c.
 {
     int spins=100;
     if (priv) priv = FUTEX_PRIVATE;
     while (spins-- && (!waiters || !*waiters)) {
         if (*addr==val) a_spin();
         else return;
     }
     if (waiters) a_inc(waiters);
     while (*addr==val) {
         __syscall(SYS_futex, addr, FUTEX_WAIT|priv, val, 0) != -ENOSYS
         || __syscall(SYS_futex, addr, FUTEX_WAIT, val, 0);
     }
     if (waiters) a_dec(waiters);
 }
References __syscall, a_dec, a_inc, a_spin, addr, ENOSYS, FUTEX_PRIVATE, FUTEX_WAIT, SYS_futex, and val.
Referenced by __private_cond_signal(), __pthread_create(), __pthread_once_full(), __tl_lock(), __tl_sync(), __vm_wait(), aio_cancel(), lock(), pshared_barrier_wait(), pthread_barrier_destroy(), pthread_barrier_wait(), pthread_cond_destroy(), and start().