Fennix: Userspace/musl/src/network/res_send.c File Reference
res_send.c File Reference
#include <resolv.h>
#include <string.h>
Functions
int __res_send (const unsigned char *msg, int msglen, unsigned char *answer, int anslen)
weak_alias (__res_send, res_send)
Function Documentation
__res_send()
int __res_send (const unsigned char * msg, int msglen, unsigned char * answer, int anslen)
Definition at line 4 of file res_send.c.
 {
     int r;
     if (anslen < 512) {
         unsigned char buf[512];
         r = __res_send(msg, msglen, buf, sizeof buf);
         if (r >= 0) memcpy(answer, buf, r < anslen ? r : anslen);
         return r;
     }
     r = __res_msend(1, &msg, &msglen, &answer, &anslen, anslen);
     return r<0 || !anslen ? -1 : anslen;
 }
References __res_msend(), __res_send(), buf, and memcpy.
Referenced by __res_send(), getnameinfo(), and res_query().
weak_alias()
weak_alias (__res_send , res_send)