Fennix: Userspace/apps/base/busybox/networking/isrv.h File Reference
isrv.h File Reference
Typedefs
typedef struct isrv_state_t isrv_state_t
Functions
void isrv_want_rd (isrv_state_t *state, int fd)
void isrv_want_wr (isrv_state_t *state, int fd)
void isrv_dont_want_rd (isrv_state_t *state, int fd)
void isrv_dont_want_wr (isrv_state_t *state, int fd)
int isrv_register_fd (isrv_state_t *state, int peer, int fd)
void isrv_close_fd (isrv_state_t *state, int fd)
int isrv_register_peer (isrv_state_t *state, void *param)
void isrv_run (int listen_fd, int(*new_peer)(isrv_state_t *state, int fd), int(*do_rd)(int fd, void **), int(*do_wr)(int fd, void **), int(*do_timeout)(void **), int timeout, int linger_timeout)
Typedef Documentation
isrv_state_t
typedef struct isrv_state_t isrv_state_t
Definition at line 11 of file isrv.h.
Function Documentation
isrv_close_fd()
void isrv_close_fd (isrv_state_t * state, int fd)
Definition at line 104 of file isrv.c.
 {
     DPRINTF("close_fd(%d)", fd);
     close(fd);
     isrv_dont_want_rd(state, fd);
     if (WR_COUNT) isrv_dont_want_wr(state, fd);
     FD2PEER[fd] = -1;
     if (fd == FD_COUNT-1) {
         do fd--; while (fd >= 0 && FD2PEER[fd] == -1);
         FD_COUNT = fd + 1;
         DPRINTF("close_fd: FD_COUNT %d", FD_COUNT);
         FD2PEER = xrealloc(FD2PEER, FD_COUNT * sizeof(FD2PEER[0]));
     }
 }
References close(), DPRINTF, fd, FD2PEER, FD_COUNT, isrv_dont_want_rd(), isrv_dont_want_wr(), state, WR_COUNT, and xrealloc.
Referenced by remove_peer().
isrv_dont_want_rd()
void isrv_dont_want_rd (isrv_state_t * state, int fd)
Definition at line 65 of file isrv.c.
 {
     FD_CLR(fd, &state->rd);
 }
References fd, FD_CLR, and state.
Referenced by isrv_close_fd().
isrv_dont_want_wr()
void isrv_dont_want_wr (isrv_state_t * state, int fd)
Definition at line 71 of file isrv.c.
 {
     if (FD_ISSET(fd, &state->wr)) {
         WR_COUNT--;
         FD_CLR(fd, &state->wr);
     }
 }
References fd, FD_CLR, FD_ISSET, state, and WR_COUNT.
Referenced by isrv_close_fd().
isrv_register_fd()
int isrv_register_fd (isrv_state_t * state, int peer, int fd)
Definition at line 80 of file isrv.c.
 {
     int n;
     DPRINTF("register_fd(peer:%d,fd:%d)", peer, fd);
     if (FD_COUNT >= FD_SETSIZE) return -1;
     if (FD_COUNT <= fd) {
         n = FD_COUNT;
         FD_COUNT = fd + 1;
         DPRINTF("register_fd: FD_COUNT %d", FD_COUNT);
         FD2PEER = xrealloc(FD2PEER, FD_COUNT * sizeof(FD2PEER[0]));
         while (n < fd) FD2PEER[n++] = -1;
     }
     DPRINTF("register_fd: FD2PEER[%d] = %d", fd, peer);
     FD2PEER[fd] = peer;
     return 0;
 }
References DPRINTF, fd, FD2PEER, FD_COUNT, FD_SETSIZE, n, peer, and xrealloc.
Referenced by isrv_run(), and new_peer().
isrv_register_peer()
int isrv_register_peer (isrv_state_t * state, void * param)
Definition at line 124 of file isrv.c.
 {
     int n;
     if (PEER_COUNT >= FD_SETSIZE) return -1;
     n = PEER_COUNT++;
     DPRINTF("register_peer: PEER_COUNT %d", PEER_COUNT);
     PARAM_TBL = xrealloc(PARAM_TBL, PEER_COUNT * sizeof(PARAM_TBL[0]));
     PARAM_TBL[n] = param;
     if (TIMEOUT) {
         TIMEO_TBL = xrealloc(TIMEO_TBL, PEER_COUNT * sizeof(TIMEO_TBL[0]));
         TIMEO_TBL[n] = CURTIME;
     }
     return n;
 }
References CURTIME, DPRINTF, FD_SETSIZE, n, param, PARAM_TBL, PEER_COUNT, TIMEO_TBL, TIMEOUT, and xrealloc.
Referenced by isrv_run(), and new_peer().
isrv_run()
void isrv_run (int listen_fd, int(*)(isrv_state_t *state, int fd) new_peer, int(*)(int fd, void **) do_rd, int(*)(int fd, void **) do_wr, int(*)(void **) do_timeout, int timeout, int linger_timeout)
Definition at line 269 of file isrv.c.
 {
     isrv_state_t *state = xzalloc(sizeof(*state));
     state->new_peer = new_peer;
     state->timeout  = timeout;
     /* register "peer" #0 - it will accept new connections */
     isrv_register_peer(state, NULL);
     isrv_register_fd(state, /*peer:*/ 0, listen_fd);
     isrv_want_rd(state, listen_fd);
     /* remember flags to make blocking<->nonblocking switch faster */
     /* (suppress gcc warning "cast from ptr to int of different size") */
     PARAM_TBL[0] = (void*)(ptrdiff_t)(fcntl(listen_fd, F_GETFL));
     while (1) {
         struct timeval tv;
         fd_set rd;
         fd_set wr;
         fd_set *wrp = NULL;
         int n;
         tv.tv_sec = timeout;
         if (PEER_COUNT <= 1)
             tv.tv_sec = linger_timeout;
         tv.tv_usec = 0;
         rd = state->rd;
         if (WR_COUNT) {
             wr = state->wr;
             wrp = &wr;
         }
         DPRINTF("run: select(FD_COUNT:%d,timeout:%d)...",
                 FD_COUNT, (int)tv.tv_sec);
         n = select(FD_COUNT, &rd, wrp, NULL, tv.tv_sec ? &tv : NULL);
         DPRINTF("run: ...select:%d", n);
         if (n < 0) {
             if (errno != EINTR)
                 bb_simple_perror_msg("select");
             continue;
         }
         if (n == 0 && linger_timeout && PEER_COUNT <= 1)
             break;
         if (timeout) {
             time_t t = monotonic_sec();
             if (t != CURTIME) {
                 CURTIME = t;
                 handle_timeout(state, do_timeout);
             }
         }
         if (n > 0) {
             handle_fd_set(state, &rd, do_rd);
             if (wrp)
                 handle_fd_set(state, wrp, do_wr);
         }
     }
     DPRINTF("run: bailout");
     /* NB: accept socket is not closed. Caller is to decide what to do */
 }
References bb_simple_perror_msg(), CURTIME, do_rd(), do_timeout(), DPRINTF, EINTR, errno, F_GETFL, fcntl(), FD_COUNT, handle_fd_set(), handle_timeout(), isrv_register_fd(), isrv_register_peer(), isrv_want_rd(), monotonic_sec(), n, new_peer(), NULL, PARAM_TBL, PEER_COUNT, rd, select(), state, t, timeout(), timeval::tv_sec, timeval::tv_usec, WR_COUNT, and xzalloc().
Referenced by fakeidentd_main().
isrv_want_rd()
void isrv_want_rd (isrv_state_t * state, int fd)
Definition at line 50 of file isrv.c.
 {
     FD_SET(fd, &state->rd);
 }
References fd, FD_SET, and state.
Referenced by isrv_run(), and new_peer().
isrv_want_wr()
void isrv_want_wr (isrv_state_t * state, int fd)
Definition at line 56 of file isrv.c.
 {
     if (!FD_ISSET(fd, &state->wr)) {
         WR_COUNT++;
         FD_SET(fd, &state->wr);
     }
 }
References fd, FD_ISSET, FD_SET, state, and WR_COUNT.