Fennix: Userspace/mlibc/options/glibc/include/getopt.h File Reference
getopt.h File Reference
Data Structures
struct option
Macros
#define no_argument 0
#define required_argument 1
#define optional_argument 2
Functions
int getopt (int, char *const [], const char *)
int getopt_long (int, char *const[], const char *, const struct option *, int *)
int getopt_long_only (int, char *const[], const char *, const struct option *, int *)
Variables
char ** environ
char * optarg
int optind
int opterr
int optopt
Data Structure Documentation
option
struct option
Definition at line 9 of file getopt.h.
Data Fields
int * flag
int has_arg
const char * name
int val
Macro Definition Documentation
no_argument
#define no_argument 0
Definition at line 26 of file getopt.h.
optional_argument
#define optional_argument 2
Definition at line 28 of file getopt.h.
required_argument
#define required_argument 1
Definition at line 27 of file getopt.h.
Function Documentation
getopt()
int getopt (int argc, char * const argv[], const char * optstring)
Definition at line 340 of file unistd-stubs.cpp.
{
     char c;
     char *place;
     optarg = NULL;
     if (!scan || *scan == '\0') {
         if (optind == 0)
             optind++;
         if (optind >= argc || argv[optind][0] != '-' || argv[optind][1] == '\0')
             return EOF;
         if (argv[optind][1] == '-' && argv[optind][2] == '\0') {
             optind++;
             return EOF;
         }
         scan = argv[optind]+1;
         optind++;
     }
     c = *scan++;
     place = strchr(optstring, c);
     if (!place || c == ':') {
         fprintf(stderr, "%s: unknown option -%c\n", argv[0], c);
         return '?';
     }
     place++;
     if (*place == ':') {
         if (*scan != '\0') {
             optarg = scan;
             scan = NULL;
         } else if( optind < argc ) {
             optarg = argv[optind];
             optind++;
         } else {
             fprintf(stderr, "%s: option requires argument -%c\n", argv[0], c);
             return ':';
         }
     }
     return c;
 }
References argc, argv, c, EOF, fprintf(), NULL, optarg, optind, scan, stderr, and strchr().
Referenced by __getopt_long_core(), and main().
getopt_long()
int getopt_long (int argc, char * const argv[], const char * optstring, const struct option * longopts, int * longindex)
Definition at line 21 of file getopt-stubs.cpp.
{
     bool colon = optstring[0] == ':';
     bool stop_at_first_nonarg = (optstring[0] == '+' || getenv("POSIXLY_CORRECT"));
     // glibc extension: Setting optind to zero causes a full reset.
     // TODO: Should we really reset opterr and the other flags?
     if(!optind) {
         optarg = nullptr;
         optind = 1;
         opterr = 1;
         optopt = 0;
         __optpos = 1;
     }
     auto isOptionArg = [](char *arg){
         // If the first character of arg '-', and the arg is not exactly
         // equal to "-" or "--", then the arg is an option argument.
         return arg[0] == '-' && strcmp(arg, "-") && strcmp(arg, "--");
     };
     while(optind < argc) {
         char *arg = argv[optind];
         if(!isOptionArg(arg)) {
             if(stop_at_first_nonarg) {
                 return -1;
             }
             bool further_options = false;
             int skip = optind;
             for(; skip < argc; ++skip) {
                 if(isOptionArg(argv[skip])) {
                     further_options = true;
                     break;
                 }
             }
             if(further_options) {
                 optind += skip - optind;
                 continue;
             } else {
                 optarg = nullptr;
                 return -1;
             }
         }
         if(arg[1] == '-') {
             arg += 2;
             // Determine the end of the option name (vs. the start of the argument).
             auto s = strchr(arg, '=');
             size_t n = s ? (s - arg) : strlen(arg);
             int k = -1;
             for(int i = 0; longopts[i].name; i++) {
                 if(strncmp(arg, longopts[i].name, n) || longopts[i].name[n])
                     continue;
                 if(k >= 0) {
                     if(opterr)
                         fprintf(stderr, "Multiple option declaration detected: %s\n", arg);
                     return '?';
                 }
                 k = i;
             }
             if(k == -1) {
                 if(opterr)
                     fprintf(stderr, "--%s is not a valid option.\n", arg);
                 return '?';
             }
             if(longindex)
                 *longindex = k;
             // Consume the option and its argument.
             if(longopts[k].has_arg == required_argument) {
                 if(s) {
                     // Consume the long option and its argument.
                     optarg = s + 1;
                     optind++;
                 }else if(argv[optind + 1]) {
                     // Consume the long option.
                     optind++;
                     // Consume the option's argument.
                     optarg = argv[optind];
                     optind++;
                 }else{
                     /*  If an error was detected, and the first character of optstring is not a colon,
                         and the external variable opterr is nonzero (which is the default),
                         getopt() prints an error message. */
                     if(!colon && opterr)
                         fprintf(stderr, "--%s requires an argument.\n", arg);
                     /*  If the first character of optstring is a colon (':'), then getopt()
                         returns ':' instead of '?' to indicate a missing option argument. */
                     return colon ? ':' : '?';
                 }
             }else if(longopts[k].has_arg == optional_argument) {
                 if(s) {
                     // Consume the long option and its argument.
                     optarg = s + 1;
                     optind++;
                 }else{
                     // Consume the long option.
                     optarg = nullptr;
                     optind++;
                 }
             }else{
                 __ensure(longopts[k].has_arg == no_argument);
                 // Consume the long option.
                 optind++;
             }
             if(!longopts[k].flag) {
                 return longopts[k].val;
             }else{
                 *longopts[k].flag = longopts[k].val;
                 return 0;
             }
         }else{
             /* handle short options, i.e. options with only one dash prefixed; e.g. `program -s` */
             unsigned int i = __optpos;
             while(true) {
                 auto opt = strchr(optstring, arg[i]);
                 if(opt) {
                     if(opt[1] == ':') {
                         bool required = (opt[2] != ':');
                         if(arg[i+1]) {
                             optarg = arg + i + 1;
                         } else if(optind + 1 < argc && argv[optind + 1] && (required || argv[optind + 1][0] != '-')) {
                             /* there is an argument to this short option, separated by a space */
                             optarg = argv[optind + 1];
                             optind++;
                             __optpos = 1;
                         } else if(!required) {
                             optarg = nullptr;
                         } else {
                             __optpos = 1;
                             optopt = arg[i];
                             return colon ? ':' : '?';
                         }
                         optind++;
                     } else {
                         if(arg[i+1]) {
                             __optpos++;
                         } else if(arg[i]) {
                             optind++;
                         } else {
                             return -1;
                         }
                     }
                     return arg[i];
                 } else {
                     /*  If getopt() does not recognize an option character, it prints an error message to stderr,
                         stores the character in optopt, and returns '?'. The calling program may prevent
                         the error message by setting opterr to 0. */
                     optopt = arg[1];
                     if(opterr)
                         fprintf(stderr, "%s is not a valid option.\n", arg);
                     return '?';
                 }
             }
         }
     }
     return -1;
 }
References __ensure, anonymous_namespace{getopt-stubs.cpp}::__optpos, argc, argv, colon, option::flag, fprintf(), getenv, i, k, n, option::name, name, no_argument, optarg, opterr, optind, optional_argument, optopt, required_argument, stderr, strchr(), strcmp, strlen(), strncmp(), and option::val.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), and test7().
getopt_long_only()
int getopt_long_only (int , char * const [], const char * , const struct option * , int *)
Definition at line 193 of file getopt-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31mmlibc: getopt_long_only() is only a stub\e[39m" << frg::endlog;
     return -1;
 }
References mlibc::infoLogger.
Variable Documentation
environ
char** environ extern
Definition at line 42 of file lib.c.
optarg
char* optarg extern
Definition at line 12 of file getopt-stubs.cpp.
opterr
int opterr extern
Definition at line 14 of file getopt-stubs.cpp.
optind
int optind extern
Definition at line 13 of file getopt-stubs.cpp.
optopt
int optopt extern
Definition at line 15 of file getopt-stubs.cpp.