Fennix: Userspace/apps/base/busybox/scripts/kconfig/lkc.h File Reference
lkc.h File Reference
#include "expr.h"
#include <libintl.h>
#include "lkc_proto.h"
Data Structures
struct kconf_id
struct gstr
Macros
#define P(name, type, arg) extern type name arg
#define SRCTREE "srctree"
#define PACKAGE "linux"
#define LOCALEDIR "/usr/share/locale"
#define _(text) gettext(text)
#define N_(text) (text)
#define TF_COMMAND 0x0001
#define TF_PARAM 0x0002
Functions
int zconfparse (void)
void zconfdump (FILE *out)
void zconf_starthelp (void)
FILE * zconf_fopen (const char *name)
void zconf_initscan (const char *name)
void zconf_nextfile (const char *name)
int zconf_lineno (void)
char * zconf_curname (void)
char * conf_get_default_confname (void)
void kconfig_load (void)
void menu_init (void)
struct menu * menu_add_menu (void)
void menu_end_menu (void)
void menu_add_entry (struct symbol *sym)
void menu_end_entry (void)
void menu_add_dep (struct expr *dep)
struct property * menu_add_prop (enum prop_type type, char *prompt, struct expr *expr, struct expr *dep)
struct property * menu_add_prompt (enum prop_type type, char *prompt, struct expr *dep)
void menu_add_expr (enum prop_type type, struct expr *expr, struct expr *dep)
void menu_add_symbol (enum prop_type type, struct symbol *sym, struct expr *dep)
void menu_finalize (struct menu *parent)
void menu_set_type (int type)
struct file * file_lookup (const char *name)
int file_write_dep (const char *name)
struct gstr str_new (void)
struct gstr str_assign (const char *s)
void str_free (struct gstr *gs)
void str_append (struct gstr *gs, const char *s)
void str_printf (struct gstr *gs, const char *fmt,...)
const char * str_get (struct gstr *gs)
void sym_init (void)
void sym_clear_all_valid (void)
void sym_set_changed (struct symbol *sym)
struct symbol * sym_check_deps (struct symbol *sym)
struct property * prop_alloc (enum prop_type type, struct symbol *sym)
struct symbol * prop_get_symbol (struct property *prop)
static tristate sym_get_tristate_value (struct symbol *sym)
static struct symbol * sym_get_choice_value (struct symbol *sym)
static bool sym_set_choice_value (struct symbol *ch, struct symbol *chval)
static bool sym_is_choice (struct symbol *sym)
static bool sym_is_choice_value (struct symbol *sym)
static bool sym_is_optional (struct symbol *sym)
static bool sym_has_value (struct symbol *sym)
Variables
int zconfdebug
const char conf_def_filename []
Data Structure Documentation
kconf_id
struct kconf_id
Definition at line 44 of file lkc.h.
Data Fields
unsigned int flags
int name
enum symbol_type stype
int token
gstr
struct gstr
Definition at line 88 of file lkc.h.
Data Fields
size_t len
char * s
Macro Definition Documentation
_
#define _ (text) gettext(text)
Definition at line 37 of file lkc.h.
LOCALEDIR
#define LOCALEDIR "/usr/share/locale"
Definition at line 35 of file lkc.h.
N_
#define N_ (text) (text)
Definition at line 38 of file lkc.h.
P
#define P (name, type, arg) extern type name arg
Definition at line 24 of file lkc.h.
PACKAGE
#define PACKAGE "linux"
Definition at line 34 of file lkc.h.
SRCTREE
#define SRCTREE "srctree"
Definition at line 32 of file lkc.h.
TF_COMMAND
#define TF_COMMAND 0x0001
Definition at line 41 of file lkc.h.
TF_PARAM
#define TF_PARAM 0x0002
Definition at line 42 of file lkc.h.
Function Documentation
conf_get_default_confname()
char* conf_get_default_confname (void)
Definition at line 70 of file confdata.c.
 {
     struct stat buf;
     static char *fullname = NULL;
     char *env, *name;
     name = conf_expand_value(conf_defname);
     env = getenv(SRCTREE);
     if (env) {
         fullname = realloc(fullname, strlen(env) + strlen(name) + 2);
         sprintf(fullname, "%s/%s", env, name);
         if (!stat(fullname, &buf))
             return fullname;
     }
     return name;
 }
References buf, conf_defname, conf_expand_value(), env, getenv, NULL, realloc, sprintf(), SRCTREE, stat(), and strlen().
Referenced by main().
file_lookup()
struct file* file_lookup (const char * name)
Definition at line 12 of file util.c.
 {
     struct file *file;
     for (file = file_list; file; file = file->next) {
         if (!strcmp(name, file->name))
             return file;
     }
     file = malloc(sizeof(*file));
     memset(file, 0, sizeof(*file));
     file->name = strdup(name);
     file->next = file_list;
     file_list = file;
     return file;
 }
References file_list, malloc, memset, file::name, file::next, strcmp, and strdup().
file_write_dep()
int file_write_dep (const char * name)
Definition at line 30 of file util.c.
 {
     struct file *file;
     FILE *out;
     if (!name)
         name = ".kconfig.d";
     out = fopen("..config.tmp", "w");
     if (!out)
         return 1;
     fprintf(out, "deps_config := \\\n");
     for (file = file_list; file; file = file->next) {
         if (file->next)
             fprintf(out, "\t%s \\\n", file->name);
         else
             fprintf(out, "\t%s\n", file->name);
     }
     fprintf(out,
         "\n"
         ".config include/autoconf.h: $(deps_config)\n"
         "\n"
         "include/autoconf.h: .config\n" /* bbox */
         "\n"
         "$(deps_config):\n");
     fclose(out);
     rename("..config.tmp", name);
     return 0;
 }
References fclose(), file_list, fopen(), fprintf(), file::name, file::next, out(), and rename().
Referenced by conf_write().
kconfig_load()
void kconfig_load (void)
Definition at line 11 of file kconfig_load.c.
 {
     void *handle;
     char *error;
     handle = dlopen("./libkconfig.so", RTLD_LAZY);
     if (!handle) {
         handle = dlopen("./scripts/kconfig/libkconfig.so", RTLD_LAZY);
         if (!handle) {
             fprintf(stderr, "%s\n", dlerror());
             exit(1);
         }
     }
 #define P(name,type,arg)            \
 {                       \
     name ## _p = dlsym(handle, #name);  \
     if ((error = dlerror()))  {     \
         fprintf(stderr, "%s\n", error); \
         exit(1);            \
     }                   \
 }
 #include "lkc_proto.h"
 #undef P
 }
References dlerror, dlopen, error, exit(), fprintf(), RTLD_LAZY, and stderr.
Referenced by main().
menu_add_dep()
void menu_add_dep (struct expr * dep)
Definition at line 102 of file menu.c.
 {
     current_entry->dep = expr_alloc_and(current_entry->dep, menu_check_dep(dep));
 }
References expr_alloc_and(), and menu_check_dep().
menu_add_entry()
void menu_add_entry (struct symbol * sym)
Definition at line 44 of file menu.c.
 {
     struct menu *menu;
     menu = malloc(sizeof(*menu));
     memset(menu, 0, sizeof(*menu));
     menu->sym = sym;
     menu->parent = current_menu;
     menu->file = current_file;
     menu->lineno = zconf_lineno();
     *last_entry_ptr = menu;
     last_entry_ptr = &menu->next;
     current_entry = menu;
 }
References current_file, current_menu, menu::file, last_entry_ptr, menu::lineno, malloc, memset, menu::next, menu::parent, menu::sym, and zconf_lineno().
menu_add_expr()
void menu_add_expr (enum prop_type type, struct expr * expr, struct expr * dep)
Definition at line 145 of file menu.c.
 {
     menu_add_prop(type, NULL, expr, dep);
 }
References menu_add_prop(), NULL, and type.
menu_add_menu()
struct menu* menu_add_menu (void)
Definition at line 64 of file menu.c.
 {
     menu_end_entry();
     last_entry_ptr = &current_entry->list;
     return current_menu = current_entry;
 }
References current_menu, last_entry_ptr, menu::list, and menu_end_entry().
menu_add_prompt()
struct property* menu_add_prompt (enum prop_type type, char * prompt, struct expr * dep)
Definition at line 140 of file menu.c.
 {
     return menu_add_prop(type, prompt, NULL, dep);
 }
References menu_add_prop(), NULL, prompt, and type.
menu_add_prop()
struct property* menu_add_prop (enum prop_type type, char * prompt, struct expr * expr, struct expr * dep)
Definition at line 122 of file menu.c.
 {
     struct property *prop = prop_alloc(type, current_entry->sym);
     prop->menu = current_entry;
     prop->text = prompt;
     prop->expr = expr;
     prop->visible.expr = menu_check_dep(dep);
     if (prompt) {
         if (current_entry->prompt)
             menu_warn(current_entry, "prompt redefined\n");
         current_entry->prompt = prop;
     }
     return prop;
 }
References expr(), expr_value::expr, property::expr, property::menu, menu_check_dep(), menu_warn(), prompt, prop_alloc(), property::text, type, and property::visible.
Referenced by menu_add_expr(), menu_add_prompt(), and menu_add_symbol().
menu_add_symbol()
void menu_add_symbol (enum prop_type type, struct symbol * sym, struct expr * dep)
Definition at line 150 of file menu.c.
 {
     menu_add_prop(type, NULL, expr_alloc_symbol(sym), dep);
 }
References expr_alloc_symbol(), menu_add_prop(), NULL, property::sym, and type.
Referenced by menu_finalize().
menu_end_entry()
void menu_end_entry (void)
Definition at line 60 of file menu.c.
 {
 }
Referenced by menu_add_menu().
menu_end_menu()
void menu_end_menu (void)
Definition at line 71 of file menu.c.
 {
     last_entry_ptr = &current_menu->next;
     current_menu = current_menu->parent;
 }
References current_menu, last_entry_ptr, menu::next, and menu::parent.
menu_finalize()
void menu_finalize (struct menu * parent)
Definition at line 205 of file menu.c.
 {
     struct menu *menu, *last_menu;
     struct symbol *sym;
     struct property *prop;
     struct expr *parentdep, *basedep, *dep, *dep2, **ep;
     sym = parent->sym;
     if (parent->list) {
         if (sym && sym_is_choice(sym)) {
             /* find the first choice value and find out choice type */
             for (menu = parent->list; menu; menu = menu->next) {
                 if (menu->sym) {
                     current_entry = parent;
                     menu_set_type(menu->sym->type);
                     current_entry = menu;
                     menu_set_type(sym->type);
                     break;
                 }
             }
             parentdep = expr_alloc_symbol(sym);
         } else if (parent->prompt)
             parentdep = parent->prompt->visible.expr;
         else
             parentdep = parent->dep;
         for (menu = parent->list; menu; menu = menu->next) {
             basedep = expr_transform(menu->dep);
             basedep = expr_alloc_and(expr_copy(parentdep), basedep);
             basedep = expr_eliminate_dups(basedep);
             menu->dep = basedep;
             if (menu->sym)
                 prop = menu->sym->prop;
             else
                 prop = menu->prompt;
             for (; prop; prop = prop->next) {
                 if (prop->menu != menu)
                     continue;
                 dep = expr_transform(prop->visible.expr);
                 dep = expr_alloc_and(expr_copy(basedep), dep);
                 dep = expr_eliminate_dups(dep);
                 if (menu->sym && menu->sym->type != S_TRISTATE)
                     dep = expr_trans_bool(dep);
                 prop->visible.expr = dep;
                 if (prop->type == P_SELECT) {
                     struct symbol *es = prop_get_symbol(prop);
                     es->rev_dep.expr = expr_alloc_or(es->rev_dep.expr,
                             expr_alloc_and(expr_alloc_symbol(menu->sym), expr_copy(dep)));
                 }
             }
         }
         for (menu = parent->list; menu; menu = menu->next)
             menu_finalize(menu);
     } else if (sym) {
         basedep = parent->prompt ? parent->prompt->visible.expr : NULL;
         basedep = expr_trans_compare(basedep, E_UNEQUAL, &symbol_no);
         basedep = expr_eliminate_dups(expr_transform(basedep));
         last_menu = NULL;
         for (menu = parent->next; menu; menu = menu->next) {
             dep = menu->prompt ? menu->prompt->visible.expr : menu->dep;
             if (!expr_contains_symbol(dep, sym))
                 break;
             if (expr_depends_symbol(dep, sym))
                 goto next;
             dep = expr_trans_compare(dep, E_UNEQUAL, &symbol_no);
             dep = expr_eliminate_dups(expr_transform(dep));
             dep2 = expr_copy(basedep);
             expr_eliminate_eq(&dep, &dep2);
             expr_free(dep);
             if (!expr_is_yes(dep2)) {
                 expr_free(dep2);
                 break;
             }
             expr_free(dep2);
         next:
             menu_finalize(menu);
             menu->parent = parent;
             last_menu = menu;
         }
         if (last_menu) {
             parent->list = parent->next;
             parent->next = last_menu->next;
             last_menu->next = NULL;
         }
     }
     for (menu = parent->list; menu; menu = menu->next) {
         if (sym && sym_is_choice(sym) && menu->sym) {
             menu->sym->flags |= SYMBOL_CHOICEVAL;
             if (!menu->prompt)
                 menu_warn(menu, "choice value must have a prompt");
             for (prop = menu->sym->prop; prop; prop = prop->next) {
                 if (prop->type == P_PROMPT && prop->menu != menu) {
                     prop_warn(prop, "choice values "
                         "currently only support a "
                         "single prompt");
                 }
                 if (prop->type == P_DEFAULT)
                     prop_warn(prop, "defaults for choice "
                         "values not supported");
             }
             current_entry = menu;
             menu_set_type(sym->type);
             menu_add_symbol(P_CHOICE, sym, NULL);
             prop = sym_get_choice_prop(sym);
             for (ep = &prop->expr; *ep; ep = &(*ep)->left.expr)
                 ;
             *ep = expr_alloc_one(E_CHOICE, NULL);
             (*ep)->right.sym = menu->sym;
         }
         if (menu->list && (!menu->prompt || !menu->prompt->text)) {
             for (last_menu = menu->list; ; last_menu = last_menu->next) {
                 last_menu->parent = parent;
                 if (!last_menu->next)
                     break;
             }
             last_menu->next = menu->next;
             menu->next = menu->list;
             menu->list = NULL;
         }
     }
     if (sym && !(sym->flags & SYMBOL_WARNED)) {
         if (sym->type == S_UNKNOWN)
             menu_warn(parent, "config symbol defined "
                 "without type\n");
         if (sym_is_choice(sym) && !parent->prompt)
             menu_warn(parent, "choice must have a prompt\n");
         /* Check properties connected to this symbol */
         sym_check_prop(sym);
         sym->flags |= SYMBOL_WARNED;
     }
     if (sym && !sym_is_optional(sym) && parent->prompt) {
         sym->rev_dep.expr = expr_alloc_or(sym->rev_dep.expr,
                 expr_alloc_and(parent->prompt->visible.expr,
                     expr_alloc_symbol(&symbol_mod)));
     }
 }
References symbol::dep, menu::dep, symbol::dep2, E_CHOICE, E_UNEQUAL, expr_value::expr, property::expr, expr_alloc_and(), expr_alloc_one(), expr_alloc_or(), expr_alloc_symbol(), expr_contains_symbol(), expr_copy(), expr_depends_symbol(), expr_eliminate_dups(), expr_eliminate_eq(), expr_free(), expr_is_yes(), expr_trans_bool(), expr_trans_compare(), expr_transform(), symbol::flags, menu::list, property::menu, menu_add_symbol(), menu_finalize(), menu_set_type(), menu_warn(), property::next, menu::next, next, NULL, P_CHOICE, P_DEFAULT, P_PROMPT, P_SELECT, parent, menu::parent, menu::prompt, symbol::prop, prop_get_symbol(), prop_warn(), symbol::rev_dep, S_TRISTATE, S_UNKNOWN, menu::sym, sym_check_prop(), sym_get_choice_prop(), sym_is_choice(), sym_is_optional(), SYMBOL_CHOICEVAL, symbol_mod, symbol_no, SYMBOL_WARNED, property::text, symbol::type, property::type, and property::visible.
Referenced by menu_finalize().
menu_init()
void menu_init (void)
Definition at line 38 of file menu.c.
 {
     current_entry = current_menu = &rootmenu;
     last_entry_ptr = &rootmenu.list;
 }
References current_menu, last_entry_ptr, menu::list, and rootmenu.
menu_set_type()
void menu_set_type (int type)
Definition at line 107 of file menu.c.
 {
     struct symbol *sym = current_entry->sym;
     if (sym->type == type)
         return;
     if (sym->type == S_UNKNOWN) {
         sym->type = type;
         return;
     }
     menu_warn(current_entry, "type of '%s' redefined from '%s' to '%s'\n",
         sym->name ? sym->name : "<choice>",
         sym_type_name(sym->type), sym_type_name(type));
 }
References menu_warn(), symbol::name, S_UNKNOWN, sym_type_name(), type, and symbol::type.
Referenced by menu_finalize().
prop_alloc()
struct property* prop_alloc (enum prop_type type, struct symbol * sym)
Definition at line 831 of file symbol.c.
 {
     struct property *prop;
     struct property **propp;
     prop = malloc(sizeof(*prop));
     memset(prop, 0, sizeof(*prop));
     prop->type = type;
     prop->sym = sym;
     prop->file = current_file;
     prop->lineno = zconf_lineno();
     /* append property to the prop list of symbol */
     if (sym) {
         for (propp = &sym->prop; *propp; propp = &(*propp)->next)
             ;
         *propp = prop;
     }
     return prop;
 }
References current_file, property::file, property::lineno, malloc, memset, property::next, symbol::prop, property::sym, type, property::type, and zconf_lineno().
Referenced by menu_add_prop(), and sym_add_default().
prop_get_symbol()
struct symbol* prop_get_symbol (struct property * prop)
Definition at line 853 of file symbol.c.
 {
     if (prop->expr && (prop->expr->type == E_SYMBOL ||
                prop->expr->type == E_CHOICE))
         return prop->expr->left.sym;
     return NULL;
 }
References E_CHOICE, E_SYMBOL, property::expr, NULL, symbol::prop, and expr::type.
Referenced by conf_read_simple(), menu_finalize(), sym_calc_choice(), sym_calc_value(), sym_check_prop(), and sym_set_tristate_value().
str_append()
void str_append (struct gstr * gs, const char * s)
Definition at line 88 of file util.c.
 {
     size_t l = strlen(gs->s) + strlen(s) + 1;
     if (l > gs->len) {
         gs->s   = realloc(gs->s, l);
         gs->len = l;
     }
     strcat(gs->s, s);
 }
References l, gstr::len, realloc, s, gstr::s, strcat, and strlen().
Referenced by expr_print_gstr_helper(), get_prompt_str(), get_relations_str(), show_help(), and str_printf().
str_assign()
struct gstr str_assign (const char * s)
Definition at line 30 of file util.c.
 {
     struct gstr gs;
     gs.s = strdup(s);
     gs.len = strlen(s) + 1;
     return gs;
 }
str_free()
void str_free (struct gstr * gs)
Definition at line 80 of file util.c.
 {
     free(gs->s);
     gs->s = NULL;
     gs->len = 0;
 }
References free, gstr::len, NULL, and gstr::s.
Referenced by search_conf(), and show_help().
str_get()
const char* str_get (struct gstr * gs)
Definition at line 110 of file util.c.
 {
     return gs->s;
 }
References gstr::s.
Referenced by search_conf(), and show_help().
str_new()
struct gstr str_new (void)
Definition at line 30 of file util.c.
 {
     struct gstr gs;
     gs.s = malloc(sizeof(char) * 64);
     gs.len = 16;
     strcpy(gs.s, "\0");
     return gs;
 }
Referenced by show_help().
str_printf()
void str_printf (struct gstr * gs, const char * fmt, ...)
Definition at line 99 of file util.c.
 {
     va_list ap;
     char s[10000]; /* big enough... */
     va_start(ap, fmt);
     vsnprintf(s, sizeof(s), fmt, ap);
     str_append(gs, s);
     va_end(ap);
 }
References ap, s, str_append(), va_end, va_start, and vsnprintf().
Referenced by get_prompt_str(), get_relations_str(), and show_help().
sym_check_deps()
struct symbol * sym_check_deps (struct symbol * sym)
Definition at line 790 of file symbol.c.
 {
     struct symbol *sym2;
     struct property *prop;
     if (sym->flags & SYMBOL_CHECK) {
         printf("Warning! Found recursive dependency: %s", sym->name);
         return sym;
     }
     if (sym->flags & SYMBOL_CHECKED)
         return NULL;
     sym->flags |= (SYMBOL_CHECK | SYMBOL_CHECKED);
     sym2 = sym_check_expr_deps(sym->rev_dep.expr);
     if (sym2)
         goto out;
     for (prop = sym->prop; prop; prop = prop->next) {
         if (prop->type == P_CHOICE || prop->type == P_SELECT)
             continue;
         sym2 = sym_check_expr_deps(prop->visible.expr);
         if (sym2)
             goto out;
         if (prop->type != P_DEFAULT || sym_is_choice(sym))
             continue;
         sym2 = sym_check_expr_deps(prop->expr);
         if (sym2)
             goto out;
     }
 out:
     if (sym2) {
         printf(" %s", sym->name);
         if (sym2 == sym) {
             printf("\n");
             sym2 = NULL;
         }
     }
     sym->flags &= ~SYMBOL_CHECK;
     return sym2;
 }
References expr_value::expr, property::expr, symbol::flags, symbol::name, property::next, NULL, out(), P_CHOICE, P_DEFAULT, P_SELECT, printf, symbol::prop, symbol::rev_dep, property::sym, sym_check_expr_deps(), sym_is_choice(), SYMBOL_CHECK, SYMBOL_CHECKED, property::type, and property::visible.
Referenced by sym_check_expr_deps().
sym_clear_all_valid()
void sym_clear_all_valid (void)
Definition at line 371 of file symbol.c.
 {
     struct symbol *sym;
     int i;
     for_all_symbols(i, sym)
         sym->flags &= ~SYMBOL_VALID;
     sym_change_count++;
     if (modules_sym)
         sym_calc_value(modules_sym);
 }
References symbol::flags, for_all_symbols, i, modules_sym, sym_calc_value(), sym_change_count, and SYMBOL_VALID.
Referenced by conf_write(), sym_set_string_value(), and sym_set_tristate_value().
sym_get_choice_value()
static struct symbol* sym_get_choice_value (struct symbol * sym) inline static
Definition at line 113 of file lkc.h.
 {
     return (struct symbol *)sym->curr.val;
 }
Referenced by build_conf(), conf_choice(), and fill_row().
sym_get_tristate_value()
static tristate sym_get_tristate_value (struct symbol * sym) inline static
Definition at line 107 of file lkc.h.
 {
     return sym->curr.tri;
 }
Referenced by build_conf(), change_sym_value(), ConfigList::changeValue(), check_conf(), conf(), conf_choice(), conf_read(), conf_sym(), conf_write(), fill_row(), menu_is_visible(), ConfigList::setValue(), sym_get_string_value(), sym_set_tristate_value(), sym_toggle_tristate_value(), and ConfigItem::updateMenu().
sym_has_value()
static bool sym_has_value (struct symbol * sym) inline static
Definition at line 138 of file lkc.h.
 {
     return sym->flags & SYMBOL_NEW ? false : true;
 }
References false, symbol::flags, and SYMBOL_NEW.
Referenced by build_conf(), check_conf(), conf_askvalue(), conf_choice(), conf_read(), sym_calc_value(), and ConfigItem::updateMenu().
sym_init()
void sym_init (void)
Definition at line 44 of file symbol.c.
 {
     struct symbol *sym;
     struct utsname uts;
     char *p;
     static bool inited = false;
     if (inited)
         return;
     inited = true;
     uname(&uts);
     sym = sym_lookup("ARCH", 0);
     sym->type = S_STRING;
     sym->flags |= SYMBOL_AUTO;
     p = getenv("ARCH");
     if (p)
         sym_add_default(sym, p);
     sym = sym_lookup("KERNELVERSION", 0);
     sym->type = S_STRING;
     sym->flags |= SYMBOL_AUTO;
     p = getenv("KERNELVERSION");
     if (p)
         sym_add_default(sym, p);
     sym = sym_lookup("UNAME_RELEASE", 0);
     sym->type = S_STRING;
     sym->flags |= SYMBOL_AUTO;
     sym_add_default(sym, uts.release);
 }
sym_is_choice()
static bool sym_is_choice (struct symbol * sym) inline static
Definition at line 123 of file lkc.h.
 {
     return sym->flags & SYMBOL_CHOICE ? true : false;
 }
References symbol::flags, SYMBOL_CHOICE, and true.
Referenced by build_conf(), check_conf(), conf(), conf_read(), conf_read_simple(), fill_row(), menu_finalize(), ConfigMainWindow::setHelp(), sym_calc_value(), and sym_check_deps().
sym_is_choice_value()
static bool sym_is_choice_value (struct symbol * sym) inline static
Definition at line 128 of file lkc.h.
 {
     return sym->flags & SYMBOL_CHOICEVAL ? true : false;
 }
References symbol::flags, SYMBOL_CHOICEVAL, and true.
Referenced by build_conf(), conf_read(), conf_read_simple(), sym_calc_value(), sym_calc_visibility(), sym_set_tristate_value(), sym_tristate_within_range(), and ConfigItem::updateMenu().
sym_is_optional()
static bool sym_is_optional (struct symbol * sym) inline static
Definition at line 133 of file lkc.h.
 {
     return sym->flags & SYMBOL_OPTIONAL ? true : false;
 }
References symbol::flags, SYMBOL_OPTIONAL, and true.
Referenced by menu_finalize().
sym_set_changed()
void sym_set_changed (struct symbol * sym)
Definition at line 383 of file symbol.c.
 {
     struct property *prop;
     sym->flags |= SYMBOL_CHANGED;
     for (prop = sym->prop; prop; prop = prop->next) {
         if (prop->menu)
             prop->menu->flags |= MENU_CHANGED;
     }
 }
References symbol::flags, menu::flags, property::menu, MENU_CHANGED, property::next, symbol::prop, property::sym, and SYMBOL_CHANGED.
Referenced by sym_calc_value(), sym_calc_visibility(), sym_set_all_changed(), sym_set_string_value(), and sym_set_tristate_value().
sym_set_choice_value()
static bool sym_set_choice_value (struct symbol * ch, struct symbol * chval) inline static
Definition at line 118 of file lkc.h.
 {
     return sym_set_tristate_value(chval, yes);
 }
References sym_set_tristate_value(), and yes.
Referenced by conf_choice().
zconf_curname()
char* zconf_curname (void)
zconf_fopen()
FILE* zconf_fopen (const char * name)
Referenced by conf_read_simple().
zconf_initscan()
void zconf_initscan (const char * name)
zconf_lineno()
int zconf_lineno (void)
Referenced by menu_add_entry(), and prop_alloc().
zconf_nextfile()
void zconf_nextfile (const char * name)
zconf_starthelp()
void zconf_starthelp (void)
zconfdump()
void zconfdump (FILE * out)
zconfparse()
int zconfparse (void)
Variable Documentation
conf_def_filename
const char conf_def_filename[] extern
Definition at line 23 of file confdata.c.
Referenced by conf_write().
zconfdebug
int zconfdebug extern