Fennix: Userspace/apps/base/busybox/libbb/single_argv.c File Reference
single_argv.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC single_argv (char **argv)
Function Documentation
single_argv()
char* FAST_FUNC single_argv (char ** argv)
Definition at line 11 of file single_argv.c.
 {
     if (argv[1] && strcmp(argv[1], "--") == 0)
         argv++;
     if (!argv[1] || argv[2])
         bb_show_usage();
     return argv[1];
 }
References argv, bb_show_usage(), and strcmp.
Referenced by chvt_main(), dirname_main(), freeramdisk_main(), raidautorun_main(), runsv_main(), and rx_main().