Fennix: Userspace/apps/base/bash/lib/readline/histfile.c File Reference
histfile.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include "posixstat.h"
#include <fcntl.h>
#include "ansi_stdlib.h"
#include <ctype.h>
#include <errno.h>
#include "history.h"
#include "histlib.h"
#include "rlshell.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define O_BINARY 0
#define PATH_MAX 1024 /* default */
#define HIST_TIMESTAMP_START(s) (*(s) == history_comment_char && isdigit ((unsigned char)(s)[1]))
#define SHOULD_CHOWN(finfo, nfinfo) (finfo.st_uid != nfinfo.st_uid || finfo.st_gid != nfinfo.st_gid)
Functions
static char * history_backupfile (const char *)
static char * history_tempfile (const char *)
static int histfile_backup (const char *, const char *)
static int histfile_restore (const char *, const char *)
static int history_rename (const char *, const char *)
static char * history_filename (const char *filename)
int read_history (const char *filename)
int read_history_range (const char *filename, int from, int to)
int history_truncate_file (const char *fname, int lines)
static int history_do_write (const char *filename, int nelements, int overwrite)
int append_history (int nelements, const char *filename)
int write_history (const char *filename)
Variables
int errno
int history_file_version = 1
int history_write_timestamps = 0
int history_multiline_entries = 0
int history_lines_read_from_file = 0
int history_lines_written_to_file = 0
Macro Definition Documentation
HIST_TIMESTAMP_START
#define HIST_TIMESTAMP_START (s) (*(s) == history_comment_char && isdigit ((unsigned char)(s)[1]))
Definition at line 140 of file histfile.c.
O_BINARY
#define O_BINARY 0
Definition at line 99 of file histfile.c.
PATH_MAX
#define PATH_MAX 1024 /* default */
Definition at line 114 of file histfile.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 26 of file histfile.c.
SHOULD_CHOWN
#define SHOULD_CHOWN (finfo, nfinfo) (finfo.st_uid != nfinfo.st_uid || finfo.st_gid != nfinfo.st_gid)
Definition at line 511 of file histfile.c.
Function Documentation
append_history()
int append_history (int nelements, const char * filename)
Definition at line 821 of file histfile.c.
 {
   return (history_do_write (filename, nelements, HISTORY_APPEND));
 }
References HISTORY_APPEND, and history_do_write().
histfile_backup()
static int histfile_backup (const char * filename, const char * back) static
Definition at line 473 of file histfile.c.
 {
 #if defined (HAVE_READLINK)
   char linkbuf[PATH_MAX+1];
   ssize_t n;
   /* Follow to target of symlink to avoid renaming symlink itself */
   if ((n = readlink (filename, linkbuf, sizeof (linkbuf) - 1)) > 0)
     {
       linkbuf[n] = '\0';
       return (history_rename (linkbuf, back));
     }
 #endif
   return (history_rename (filename, back));
 }
References history_rename(), n, PATH_MAX, and readlink().
histfile_restore()
static int histfile_restore (const char * backup, const char * orig) static
Definition at line 492 of file histfile.c.
 {
 #if defined (HAVE_READLINK)
   char linkbuf[PATH_MAX+1];
   ssize_t n;
   /* Follow to target of symlink to avoid renaming symlink itself */
   if ((n = readlink (orig, linkbuf, sizeof (linkbuf) - 1)) > 0)
     {
       linkbuf[n] = '\0';
       return (history_rename (backup, linkbuf));
     }
 #endif
   return (history_rename (backup, orig));
 }
References history_rename(), n, PATH_MAX, and readlink().
Referenced by history_do_write(), and history_truncate_file().
history_backupfile()
static char * history_backupfile (const char * filename) static
Definition at line 187 of file histfile.c.
 {
   const char *fn;
   char *ret, linkbuf[PATH_MAX+1];
   size_t len;
   ssize_t n;
   struct stat fs;
   fn = filename;
 #if defined (HAVE_READLINK)
   /* Follow symlink to avoid backing up symlink itself; call will fail if
      not a symlink */
   if ((n = readlink (filename, linkbuf, sizeof (linkbuf) - 1)) > 0)
     {
       linkbuf[n] = '\0';
       fn = linkbuf;
     }
 #endif
   len = strlen (fn);
   ret = xmalloc (len + 2);
   strcpy (ret, fn);
   ret[len] = '-';
   ret[len+1] = '\0';
   return ret;
 }
References len, n, PATH_MAX, readlink(), ret, strcpy, strlen(), and xmalloc.
history_do_write()
static int history_do_write (const char * filename, int nelements, int overwrite) static
Definition at line 678 of file histfile.c.
 {
   register int i;
   char *output, *tempname, *histname;
   int file, mode, rv, exists;
   struct stat finfo, nfinfo;
 #ifdef HISTORY_USE_MMAP
   size_t cursize;
   history_lines_written_to_file = 0;
   mode = overwrite ? O_RDWR|O_CREAT|O_TRUNC|O_BINARY : O_RDWR|O_APPEND|O_BINARY;
 #else
   mode = overwrite ? O_WRONLY|O_CREAT|O_TRUNC|O_BINARY : O_WRONLY|O_APPEND|O_BINARY;
 #endif
   histname = history_filename (filename);
   exists = histname ? (stat (histname, &finfo) == 0) : 0;
   tempname = (overwrite && exists && S_ISREG (finfo.st_mode)) ? history_tempfile (histname) : 0;
   output = tempname ? tempname : histname;
   file = output ? open (output, mode, 0600) : -1;
   rv = 0;
   if (file == -1)
     {
       rv = errno;
       FREE (histname);
       FREE (tempname);
       return (rv);
     }
 #ifdef HISTORY_USE_MMAP
   cursize = overwrite ? 0 : lseek (file, 0, SEEK_END);
 #endif
   if (nelements > history_length)
     nelements = history_length;
   /* Build a buffer of all the lines to write, and write them in one syscall.
      Suggested by Peter Ho (peter@robosts.oxford.ac.uk). */
   {
     HIST_ENTRY **the_history;   /* local */
     register int j;
     int buffer_size;
     char *buffer;
     the_history = history_list ();
     /* Calculate the total number of bytes to write. */
     for (buffer_size = 0, i = history_length - nelements; i < history_length; i++)
       {
     if (history_write_timestamps && the_history[i]->timestamp && the_history[i]->timestamp[0])
       buffer_size += strlen (the_history[i]->timestamp) + 1;
     buffer_size += strlen (the_history[i]->line) + 1;
       }
     /* Allocate the buffer, and fill it. */
 #ifdef HISTORY_USE_MMAP
     if (ftruncate (file, buffer_size+cursize) == -1)
       goto mmap_error;
     buffer = (char *)mmap (0, buffer_size, PROT_READ|PROT_WRITE, MAP_WFLAGS, file, cursize);
     if ((void *)buffer == MAP_FAILED)
       {
 mmap_error:
     rv = errno;
     close (file);
     if (tempname)
       unlink (tempname);
     FREE (histname);
     FREE (tempname);
     return rv;
       }
 #else
     buffer = (char *)malloc (buffer_size);
     if (buffer == 0)
       {
         rv = errno;
     close (file);
     if (tempname)
       unlink (tempname);
     FREE (histname);
     FREE (tempname);
     return rv;
       }
 #endif
     for (j = 0, i = history_length - nelements; i < history_length; i++)
       {
     if (history_write_timestamps && the_history[i]->timestamp && the_history[i]->timestamp[0])
       {
         strcpy (buffer + j, the_history[i]->timestamp);
         j += strlen (the_history[i]->timestamp);
         buffer[j++] = '\n';
       }
     strcpy (buffer + j, the_history[i]->line);
     j += strlen (the_history[i]->line);
     buffer[j++] = '\n';
       }
 #ifdef HISTORY_USE_MMAP
     if (msync (buffer, buffer_size, MS_ASYNC) != 0 || munmap (buffer, buffer_size) != 0)
       rv = errno;
 #else
     if (write (file, buffer, buffer_size) < 0)
       rv = errno;
     xfree (buffer);
 #endif
   }
   history_lines_written_to_file = nelements;
   if (close (file) < 0 && rv == 0)
     rv = errno;
   if (rv == 0 && histname && tempname)
     rv = histfile_restore (tempname, histname);
   if (rv != 0)
     {
       rv = errno;
       if (tempname)
     unlink (tempname);
       history_lines_written_to_file = 0;
     }
 #if defined (HAVE_CHOWN)
   /* Make sure the new filename is owned by the same user as the old.  If one
      user is running this, it's a no-op.  If the shell is running after sudo
      with a shared history file, we don't want to leave the history file
      owned by root. */
   if (rv == 0 && exists)
     mode = chown (histname, finfo.st_uid, finfo.st_gid);
 #endif
   FREE (histname);
   FREE (tempname);
   return (rv);
 }
References buffer, chown(), close(), errno, FREE, ftruncate(), histfile_restore(), history_filename(), history_length, history_lines_written_to_file, history_list(), history_tempfile(), history_write_timestamps, i, j, line, lseek(), malloc, MAP_FAILED, mmap, MS_ASYNC, msync(), munmap(), O_APPEND, O_BINARY, O_CREAT, O_RDWR, O_TRUNC, O_WRONLY, open(), PROT_READ, PROT_WRITE, S_ISREG, SEEK_END, stat::st_gid, stat::st_mode, stat::st_uid, stat(), strcpy, strlen(), the_history, unlink(), write(), and xfree.
Referenced by append_history(), and write_history().
history_filename()
static char* history_filename (const char * filename) static
Definition at line 152 of file histfile.c.
 {
   char *return_val;
   const char *home;
   int home_len;
   return_val = filename ? savestring (filename) : (char *)NULL;
   if (return_val)
     return (return_val);
   home = sh_get_env_value ("HOME");
 #if defined (_WIN32)
   if (home == 0)
     home = sh_get_env_value ("APPDATA");
 #endif
   if (home == 0)
     return (NULL);
   else
     home_len = strlen (home);
   return_val = (char *)xmalloc (2 + home_len + 8); /* strlen(".history") == 8 */
   strcpy (return_val, home);
   return_val[home_len] = '/';
 #if defined (__MSDOS__)
   strcpy (return_val + home_len + 1, "_history");
 #else
   strcpy (return_val + home_len + 1, ".history");
 #endif
   return (return_val);
 }
References NULL, savestring(), sh_get_env_value(), strcpy, strlen(), and xmalloc.
Referenced by history_do_write(), history_truncate_file(), and read_history_range().
history_rename()
static int history_rename (const char * old, const char * new) static
Definition at line 461 of file histfile.c.
 {
 #if defined (_WIN32)
   return (MoveFileEx (old, new, MOVEFILE_REPLACE_EXISTING) == 0 ? -1 : 0);
 #else
   return (rename (old, new));
 #endif
 }
References rename().
Referenced by histfile_backup(), and histfile_restore().
history_tempfile()
static char * history_tempfile (const char * filename) static
Definition at line 215 of file histfile.c.
 {
   const char *fn;
   char *ret, linkbuf[PATH_MAX+1];
   size_t len;
   ssize_t n;
   struct stat fs;
   int pid;
   fn = filename;
 #if defined (HAVE_READLINK)
   /* Follow symlink so tempfile created in the same directory as any symlinked
      history file; call will fail if not a symlink */
   if ((n = readlink (filename, linkbuf, sizeof (linkbuf) - 1)) > 0)
     {
       linkbuf[n] = '\0';
       fn = linkbuf;
     }
 #endif
   len = strlen (fn);
   ret = xmalloc (len + 11);
   strcpy (ret, fn);
   pid = (int)getpid ();
   /* filename-PID.tmp */
   ret[len] = '-';
   ret[len+1] = (pid / 10000 % 10) + '0';
   ret[len+2] = (pid / 1000 % 10) + '0';
   ret[len+3] = (pid / 100 % 10) + '0';
   ret[len+4] = (pid / 10 % 10) + '0';
   ret[len+5] = (pid % 10) + '0';
   strcpy (ret + len + 6, ".tmp");
   return ret;
 }
References getpid(), int, len, n, PATH_MAX, readlink(), ret, strcpy, strlen(), and xmalloc.
Referenced by history_do_write(), and history_truncate_file().
history_truncate_file()
int history_truncate_file (const char * fname, int lines)
Definition at line 518 of file histfile.c.
 {
   char *buffer, *filename, *tempname, *bp, *bp1;        /* bp1 == bp+1 */
   int file, chars_read, rv, orig_lines, exists, r;
   struct stat finfo, nfinfo;
   size_t file_size;
   history_lines_written_to_file = 0;
   buffer = (char *)NULL;
   filename = history_filename (fname);
   tempname = 0;
   file = filename ? open (filename, O_RDONLY|O_BINARY, 0666) : -1;
   rv = exists = 0;
   /* Don't try to truncate non-regular files. */
   if (file == -1 || fstat (file, &finfo) == -1)
     {
       rv = errno;
       if (file != -1)
     close (file);
       goto truncate_exit;
     }
   exists = 1;
   nfinfo.st_uid = finfo.st_uid;
   nfinfo.st_gid = finfo.st_gid;
   if (S_ISREG (finfo.st_mode) == 0)
     {
       close (file);
 #ifdef EFTYPE
       rv = EFTYPE;
 #else
       rv = EINVAL;
 #endif
       goto truncate_exit;
     }
   file_size = (size_t)finfo.st_size;
   /* check for overflow on very large files */
   if (file_size != finfo.st_size || file_size + 1 < file_size)
     {
       close (file);
 #if defined (EFBIG)
       rv = errno = EFBIG;
 #elif defined (EOVERFLOW)
       rv = errno = EOVERFLOW;
 #else
       rv = errno = EINVAL;
 #endif
       goto truncate_exit;
     }
   buffer = (char *)malloc (file_size + 1);
   if (buffer == 0)
     {
       rv = errno;
       close (file);
       goto truncate_exit;
     }
   chars_read = read (file, buffer, file_size);
   close (file);
   if (chars_read <= 0)
     {
       rv = (chars_read < 0) ? errno : 0;
       goto truncate_exit;
     }
   orig_lines = lines;
   /* Count backwards from the end of buffer until we have passed
      LINES lines.  bp1 is set funny initially.  But since bp[1] can't
      be a comment character (since it's off the end) and *bp can't be
      both a newline and the history comment character, it should be OK. */
   for (bp1 = bp = buffer + chars_read - 1; lines && bp > buffer; bp--)
     {
       if (*bp == '\n' && HIST_TIMESTAMP_START(bp1) == 0)
     lines--;
       bp1 = bp;
     }
   /* If this is the first line, then the file contains exactly the
      number of lines we want to truncate to, so we don't need to do
      anything.  It's the first line if we don't find a newline between
      the current value of i and 0.  Otherwise, write from the start of
      this line until the end of the buffer. */
   for ( ; bp > buffer; bp--)
     {
       if (*bp == '\n' && HIST_TIMESTAMP_START(bp1) == 0)
         {
       bp++;
       break;
         }
       bp1 = bp;
     }
   /* Write only if there are more lines in the file than we want to
      truncate to. */
   if (bp <= buffer)
     {
       rv = 0;
       /* No-op if LINES == 0 at this point */
       history_lines_written_to_file = orig_lines - lines;
       goto truncate_exit;
     }
   tempname = history_tempfile (filename);
   if ((file = open (tempname, O_WRONLY|O_CREAT|O_TRUNC|O_BINARY, 0600)) != -1)
     {
       if (write (file, bp, chars_read - (bp - buffer)) < 0)
     rv = errno;
       if (fstat (file, &nfinfo) < 0 && rv == 0)
     rv = errno;
       if (close (file) < 0 && rv == 0)
     rv = errno;
     }
   else
     rv = errno;
  truncate_exit:
   FREE (buffer);
   history_lines_written_to_file = orig_lines - lines;
   if (rv == 0 && filename && tempname)
     rv = histfile_restore (tempname, filename);
   if (rv != 0)
     {
       rv = errno;
       if (tempname)
     unlink (tempname);
       history_lines_written_to_file = 0;
     }
 #if defined (HAVE_CHOWN)
   /* Make sure the new filename is owned by the same user as the old.  If one
      user is running this, it's a no-op.  If the shell is running after sudo
      with a shared history file, we don't want to leave the history file
      owned by root. */
   if (rv == 0 && exists && SHOULD_CHOWN (finfo, nfinfo))
     r = chown (filename, finfo.st_uid, finfo.st_gid);
 #endif
   xfree (filename);
   FREE (tempname);
   return rv;
 }
References bp, buffer, chown(), close(), EFBIG, EFTYPE, EINVAL, EOVERFLOW, errno, fname, FREE, fstat(), HIST_TIMESTAMP_START, histfile_restore(), history_filename(), history_lines_written_to_file, history_tempfile(), if(), lines, malloc, NULL, O_BINARY, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), r, read(), S_ISREG, SHOULD_CHOWN, stat::st_gid, stat::st_mode, stat::st_size, stat::st_uid, unlink(), write(), and xfree.
read_history()
int read_history (const char * filename)
Definition at line 257 of file histfile.c.
 {
   return (read_history_range (filename, 0, -1));
 }
References read_history_range().
Referenced by main().
read_history_range()
int read_history_range (const char * filename, int from, int to)
Definition at line 268 of file histfile.c.
 {
   register char *line_start, *line_end, *p;
   char *input, *buffer, *bufend, *last_ts;
   int file, current_line, chars_read, has_timestamps, reset_comment_char;
   struct stat finfo;
   size_t file_size;
 #if defined (EFBIG)
   int overflow_errno = EFBIG;
 #elif defined (EOVERFLOW)
   int overflow_errno = EOVERFLOW;
 #else
   int overflow_errno = EIO;
 #endif
   history_lines_read_from_file = 0;
   buffer = last_ts = (char *)NULL;
   input = history_filename (filename);
   file = input ? open (input, O_RDONLY|O_BINARY, 0666) : -1;
   if ((file < 0) || (fstat (file, &finfo) == -1))
     goto error_and_exit;
   if (S_ISREG (finfo.st_mode) == 0)
     {
 #ifdef EFTYPE
       errno = EFTYPE;
 #else
       errno = EINVAL;
 #endif
       goto error_and_exit;
     }
   file_size = (size_t)finfo.st_size;
   /* check for overflow on very large files */
   if (file_size != finfo.st_size || file_size + 1 < file_size)
     {
       errno = overflow_errno;
       goto error_and_exit;
     }
   if (file_size == 0)
     {
       xfree (input);
       close (file);
       return 0; /* don't waste time if we don't have to */
     }
 #ifdef HISTORY_USE_MMAP
   /* We map read/write and private so we can change newlines to NULs without
      affecting the underlying object. */
   buffer = (char *)mmap (0, file_size, PROT_READ|PROT_WRITE, MAP_RFLAGS, file, 0);
   if ((void *)buffer == MAP_FAILED)
     {
       errno = overflow_errno;
       goto error_and_exit;
     }
   chars_read = file_size;
 #else
   buffer = (char *)malloc (file_size + 1);
   if (buffer == 0)
     {
       errno = overflow_errno;
       goto error_and_exit;
     }
   chars_read = read (file, buffer, file_size);
 #endif
   if (chars_read < 0)
     {
   error_and_exit:
       if (errno != 0)
     chars_read = errno;
       else
     chars_read = EIO;
       if (file >= 0)
     close (file);
       FREE (input);
 #ifndef HISTORY_USE_MMAP
       FREE (buffer);
 #endif
       return (chars_read);
     }
   close (file);
   /* Set TO to larger than end of file if negative. */
   if (to < 0)
     to = chars_read;
   /* Start at beginning of file, work to end. */
   bufend = buffer + chars_read;
   *bufend = '\0';       /* null-terminate buffer for timestamp checks */
   current_line = 0;
   /* Heuristic: the history comment character rarely changes, so assume we
      have timestamps if the buffer starts with `#[:digit:]' and temporarily
      set history_comment_char so timestamp parsing works right */
   reset_comment_char = 0;
   if (history_comment_char == '\0' && buffer[0] == '#' && isdigit ((unsigned char)buffer[1]))
     {
       history_comment_char = '#';
       reset_comment_char = 1;
     }
   has_timestamps = HIST_TIMESTAMP_START (buffer);
   history_multiline_entries += has_timestamps && history_write_timestamps;
   /* Skip lines until we are at FROM. */
   if (has_timestamps)
     last_ts = buffer;
   for (line_start = line_end = buffer; line_end < bufend && current_line < from; line_end++)
     if (*line_end == '\n')
       {
         p = line_end + 1;
         /* If we see something we think is a timestamp, continue with this
        line.  We should check more extensively here... */
     if (HIST_TIMESTAMP_START(p) == 0)
       current_line++;
     else
       last_ts = p;
     line_start = p;
     /* If we are at the last line (current_line == from) but we have
        timestamps (has_timestamps), then line_start points to the
        text of the last command, and we need to skip to its end. */
     if (current_line >= from && has_timestamps)
       {
         for (line_end = p; line_end < bufend && *line_end != '\n'; line_end++)
           ;
         line_start = (*line_end == '\n') ? line_end + 1 : line_end;
       }
       }
   /* If there are lines left to gobble, then gobble them now. */
   for (line_end = line_start; line_end < bufend; line_end++)
     if (*line_end == '\n')
       {
     /* Change to allow Windows-like \r\n end of line delimiter. */
     if (line_end > line_start && line_end[-1] == '\r')
       line_end[-1] = '\0';
     else
       *line_end = '\0';
     if (*line_start)
       {
         if (HIST_TIMESTAMP_START(line_start) == 0)
           {
             if (last_ts == NULL && history_length > 0 && history_multiline_entries)
           _hs_append_history_line (history_length - 1, line_start);
         else
           add_history (line_start);
         if (last_ts)
           {
             add_history_time (last_ts);
             last_ts = NULL;
           }
           }
         else
           {
         last_ts = line_start;
         current_line--;
           }
       }
     current_line++;
     if (current_line >= to)
       break;
     line_start = line_end + 1;
       }
   history_lines_read_from_file = current_line;
   if (reset_comment_char)
     history_comment_char = '\0';
   FREE (input);
 #ifndef HISTORY_USE_MMAP
   FREE (buffer);
 #else
   munmap (buffer, file_size);
 #endif
   return (0);
 }
References _hs_append_history_line(), add_history(), add_history_time(), buffer, close(), EFBIG, EFTYPE, EINVAL, EIO, EOVERFLOW, errno, FREE, fstat(), HIST_TIMESTAMP_START, history_comment_char, history_filename(), history_length, history_lines_read_from_file, history_multiline_entries, history_write_timestamps, if(), isdigit, malloc, MAP_FAILED, mmap, munmap(), NULL, O_BINARY, O_RDONLY, open(), p, PROT_READ, PROT_WRITE, read(), S_ISREG, stat::st_mode, stat::st_size, and xfree.
Referenced by read_history().
write_history()
int write_history (const char * filename)
Definition at line 830 of file histfile.c.
 {
   return (history_do_write (filename, history_length, HISTORY_OVERWRITE));
 }
References history_do_write(), history_length, and HISTORY_OVERWRITE.
Referenced by main().
Variable Documentation
errno
int errno extern
Referenced by history_do_write(), history_truncate_file(), and read_history_range().
history_file_version
int history_file_version = 1
Definition at line 118 of file histfile.c.
history_lines_read_from_file
int history_lines_read_from_file = 0
Definition at line 131 of file histfile.c.
Referenced by read_history_range().
history_lines_written_to_file
int history_lines_written_to_file = 0
Definition at line 136 of file histfile.c.
Referenced by history_do_write(), and history_truncate_file().
history_multiline_entries
int history_multiline_entries = 0
Definition at line 126 of file histfile.c.
Referenced by read_history_range().
history_write_timestamps
int history_write_timestamps = 0
Definition at line 121 of file histfile.c.
Referenced by history_do_write(), and read_history_range().