Fennix Kernel: std::vector< T > Class Template Reference
std::vector< T > Class Template Reference
#include <vector.hpp>
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
NIF vector ()
NIF vector (size_t Size)
NIF vector (size_t Size, const T &Initial)
NIF vector (const vector< T > &vector)
NIF ~vector ()
NIF void remove (size_t Position)
NIF void remove (const T &Value)
NIF T & null_elem ()
NIF bool null_elem (size_t Index)
NIF T & next (size_t Position)
NIF T & prev (size_t Position)
NIF T & next (const T &Value)
NIF T & prev (const T &Value)
NIF size_t capacity () const
NIF size_t size () const
NIF bool empty () const
NIF iterator begin ()
NIF iterator end ()
NIF T & front ()
NIF T & back ()
NIF void push_back (const T &Value)
NIF void pop_back ()
NIF void reverse ()
NIF void reserve (size_t Capacity)
NIF void resize (size_t Size)
NIF void clear ()
NIF T * data ()
NIF T & operator[] (size_t Index)
NIF vector< T > & operator= (const vector< T > &vector)
Private Attributes
size_t VectorSize = 0
size_t VectorCapacity = 0
T * VectorBuffer = nullptr
Detailed Description
template<class T>
class std::vector< T >
Definition at line 11 of file vector.hpp.
Member Typedef Documentation
const_iterator
template<class T > typedef const T* std::vector< T >::const_iterator
Definition at line 20 of file vector.hpp.
iterator
template<class T > typedef T* std::vector< T >::iterator
Definition at line 19 of file vector.hpp.
Constructor & Destructor Documentation
vector() [1/4]
template<class T > NIF std::vector< T >::vector () inline
Definition at line 22 of file vector.hpp.
         {
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR INIT: vector( )");
 #endif
             VectorCapacity = 0;
             VectorSize = 0;
             VectorBuffer = 0;
         }
References debug, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
vector() [2/4]
template<class T > NIF std::vector< T >::vector (size_t Size) inline
Definition at line 32 of file vector.hpp.
         {
             VectorCapacity = Size;
             VectorSize = Size;
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR INIT: vector( %lld )", Size);
 #endif
             VectorBuffer = new T[Size];
         }
References debug, Size, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
vector() [3/4]
template<class T > NIF std::vector< T >::vector (size_t Size, const T & Initial) inline
Definition at line 42 of file vector.hpp.
         {
             VectorSize = Size;
             VectorCapacity = Size;
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR INIT: vector( %lld %llx )", Size, Initial);
 #endif
             assert(Size > 0);
             VectorBuffer = new T[Size];
             for (size_t i = 0; i < Size; i++)
                 VectorBuffer[i] = Initial;
         }
References assert, debug, Size, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
vector() [4/4]
template<class T > NIF std::vector< T >::vector (const vector< T > & vector) inline
Definition at line 55 of file vector.hpp.
         {
             VectorSize = vector.VectorSize;
             VectorCapacity = vector.VectorCapacity;
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR INIT: vector( <vector> )->Size: %lld", VectorSize);
 #endif
             assert(VectorSize > 0);
             VectorBuffer = new T[VectorSize];
             for (size_t i = 0; i < VectorSize; i++)
                 VectorBuffer[i] = vector.VectorBuffer[i];
         }
References assert, debug, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
~vector()
template<class T > NIF std::vector< T >::~vector () inline
Definition at line 68 of file vector.hpp.
         {
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR INIT: ~vector( ~%lx )", VectorBuffer);
 #endif
             VectorSize = 0;
             VectorCapacity = 0;
             if (VectorBuffer != nullptr)
             {
                 delete[] VectorBuffer, VectorBuffer = nullptr;
             }
         }
References debug, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
Member Function Documentation
back()
template<class T > NIF T& std::vector< T >::back () inline
Definition at line 178 of file vector.hpp.
 { return VectorBuffer[VectorSize - 1]; }
References std::vector< T >::VectorBuffer, and std::vector< T >::VectorSize.
begin()
template<class T > NIF iterator std::vector< T >::begin () inline
Definition at line 172 of file vector.hpp.
 { return VectorBuffer; }
References std::vector< T >::VectorBuffer.
capacity()
template<class T > NIF size_t std::vector< T >::capacity () const inline
Definition at line 166 of file vector.hpp.
 { return VectorCapacity; }
References std::vector< T >::VectorCapacity.
clear()
template<class T > NIF void std::vector< T >::clear () inline
Definition at line 229 of file vector.hpp.
         {
             VectorCapacity = 0;
             VectorSize = 0;
             if (VectorBuffer != nullptr)
             {
                 delete[] VectorBuffer, VectorBuffer = nullptr;
             }
         }
References std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
data()
template<class T > NIF T* std::vector< T >::data () inline
Definition at line 239 of file vector.hpp.
 { return VectorBuffer; }
References std::vector< T >::VectorBuffer.
empty()
template<class T > NIF bool std::vector< T >::empty () const
end()
template<class T > NIF iterator std::vector< T >::end () inline
Definition at line 174 of file vector.hpp.
 { return VectorBuffer + size(); }
References std::vector< T >::size(), and std::vector< T >::VectorBuffer.
front()
template<class T > NIF T& std::vector< T >::front () inline
Definition at line 176 of file vector.hpp.
 { return VectorBuffer[0]; }
References std::vector< T >::VectorBuffer.
next() [1/2]
template<class T > NIF T& std::vector< T >::next (const T & Value) inline
Definition at line 134 of file vector.hpp.
         {
             for (size_t i = 0; i < VectorSize; i++)
             {
                 if (VectorBuffer[i] == Value)
                 {
                     if (i + 1 < VectorSize && reinterpret_cast<uintptr_t>(&VectorBuffer[i + 1]))
                         return VectorBuffer[i + 1];
                     else
                         break;
                 }
             }
             warn("next( %#lx ) is null (requested by %#lx)", Value, __builtin_return_address(0));
             return this->null_elem();
         }
References std::vector< T >::null_elem(), std::vector< T >::VectorBuffer, std::vector< T >::VectorSize, and warn.
next() [2/2]
template<class T > NIF T& std::vector< T >::next (size_t Position) inline
Definition at line 118 of file vector.hpp.
         {
             if (Position + 1 < VectorSize && reinterpret_cast<uintptr_t>(&VectorBuffer[Position + 1]))
                 return VectorBuffer[Position + 1];
             warn("next( %lld ) is null (requested by %#lx)", Position, __builtin_return_address(0));
             return this->null_elem();
         }
References std::vector< T >::null_elem(), std::vector< T >::VectorBuffer, std::vector< T >::VectorSize, and warn.
null_elem() [1/2]
template<class T > NIF T& std::vector< T >::null_elem () inline
Definition at line 105 of file vector.hpp.
         {
             static T null_elem;
             return null_elem;
         }
Referenced by std::vector< T >::next(), std::vector< T >::operator[](), and std::vector< T >::prev().
null_elem() [2/2]
template<class T > NIF bool std::vector< T >::null_elem (size_t Index) inline
Definition at line 111 of file vector.hpp.
         {
             if (!reinterpret_cast<uintptr_t>(&VectorBuffer[Index]))
                 return false;
             return true;
         }
References std::vector< T >::VectorBuffer.
operator=()
template<class T > NIF vector<T>& std::vector< T >::operator= (const vector< T > & vector) inline
Definition at line 251 of file vector.hpp.
         {
             delete[] VectorBuffer;
             VectorSize = vector.VectorSize;
             VectorCapacity = vector.VectorCapacity;
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR ALLOCATION: operator=( <vector> )->Size:%lld", VectorSize);
 #endif
             VectorBuffer = new T[VectorSize];
             for (size_t i = 0; i < VectorSize; i++)
                 VectorBuffer[i] = vector.VectorBuffer[i];
             return *this;
         }
References debug, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
operator[]()
template<class T > NIF T& std::vector< T >::operator[] (size_t Index) inline
Definition at line 241 of file vector.hpp.
         {
             if (!reinterpret_cast<uintptr_t>(&VectorBuffer[Index]))
             {
                 warn("operator[]( %lld ) is null (requested by %#lx)", Index, __builtin_return_address(0));
                 return this->null_elem();
             }
             return VectorBuffer[Index];
         }
References std::vector< T >::null_elem(), std::vector< T >::VectorBuffer, and warn.
pop_back()
template<class T > NIF void std::vector< T >::pop_back () inline
Definition at line 187 of file vector.hpp.
 { VectorSize--; }
References std::vector< T >::VectorSize.
prev() [1/2]
template<class T > NIF T& std::vector< T >::prev (const T & Value) inline
Definition at line 150 of file vector.hpp.
         {
             for (size_t i = 0; i < VectorSize; i++)
             {
                 if (VectorBuffer[i] == Value)
                 {
                     if (i > 0 && reinterpret_cast<uintptr_t>(&VectorBuffer[i - 1]))
                         return VectorBuffer[i - 1];
                     else
                         break;
                 }
             }
             warn("prev( %#lx ) is null (requested by %#lx)", Value, __builtin_return_address(0));
             return this->null_elem();
         }
References std::vector< T >::null_elem(), std::vector< T >::VectorBuffer, std::vector< T >::VectorSize, and warn.
prev() [2/2]
template<class T > NIF T& std::vector< T >::prev (size_t Position) inline
Definition at line 126 of file vector.hpp.
         {
             if (Position > 0 && reinterpret_cast<uintptr_t>(&VectorBuffer[Position - 1]))
                 return VectorBuffer[Position - 1];
             warn("prev( %lld ) is null (requested by %#lx)", Position, __builtin_return_address(0));
             return this->null_elem();
         }
References std::vector< T >::null_elem(), std::vector< T >::VectorBuffer, and warn.
push_back()
template<class T > NIF void std::vector< T >::push_back (const T & Value) inline
Definition at line 180 of file vector.hpp.
         {
             if (VectorSize >= VectorCapacity)
                 reserve(VectorCapacity + 5);
             VectorBuffer[VectorSize++] = Value;
         }
References std::vector< T >::reserve(), std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
Referenced by Tasking::Task::CreateThread(), Execute::ELFLoadExec(), NetworkEthernet::EthernetEvents::EthernetEvents(), PCI::PCI::FindPCIDevice(), and NetworkARP::ARP::ManageDiscoveredAddresses().
remove() [1/2]
template<class T > NIF void std::vector< T >::remove (const T & Value) inline
Definition at line 93 of file vector.hpp.
         {
             for (size_t i = 0; i < VectorSize; i++)
             {
                 if (VectorBuffer[i] == Value)
                 {
                     remove(i);
                     return;
                 }
             }
         }
References std::vector< T >::remove(), std::vector< T >::VectorBuffer, and std::vector< T >::VectorSize.
remove() [2/2]
template<class T > NIF void std::vector< T >::remove (size_t Position) inline
Definition at line 81 of file vector.hpp.
         {
             if (Position >= VectorSize)
                 return;
             memset(&*(VectorBuffer + Position), 0, sizeof(T));
             for (size_t i = 0; i < VectorSize - 1; i++)
             {
                 *(VectorBuffer + Position + i) = *(VectorBuffer + Position + i + 1);
             }
             VectorSize--;
         }
References memset(), std::vector< T >::VectorBuffer, and std::vector< T >::VectorSize.
Referenced by NetworkARP::ARP::ManageDiscoveredAddresses(), and std::vector< T >::remove().
reserve()
template<class T > NIF void std::vector< T >::reserve (size_t Capacity) inline
Definition at line 201 of file vector.hpp.
         {
             if (VectorBuffer == 0)
             {
                 VectorSize = 0;
                 VectorCapacity = 0;
             }
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR ALLOCATION: reverse( %lld )", Capacity);
 #endif
             T *NewBuffer = new T[Capacity];
             size_t _Size = Capacity < VectorSize ? Capacity : VectorSize;
             for (size_t i = 0; i < _Size; i++)
                 NewBuffer[i] = VectorBuffer[i];
             VectorCapacity = Capacity;
 #ifdef DEBUG_MEM_ALLOCATION
             debug("VECTOR ALLOCATION: reverse( <Capacity> )->Buffer:~%lld", VectorBuffer);
 #endif
             delete[] VectorBuffer;
             VectorBuffer = NewBuffer;
         }
References debug, std::vector< T >::VectorBuffer, std::vector< T >::VectorCapacity, and std::vector< T >::VectorSize.
Referenced by std::vector< T >::push_back(), and std::vector< T >::resize().
resize()
template<class T > NIF void std::vector< T >::resize (size_t Size) inline
Definition at line 223 of file vector.hpp.
         {
             reserve(Size);
             VectorSize = Size;
         }
References std::vector< T >::reserve(), Size, and std::vector< T >::VectorSize.
reverse()
template<class T > NIF void std::vector< T >::reverse () inline
Definition at line 189 of file vector.hpp.
         {
             if (VectorSize <= 1)
                 return;
             for (size_t i = 0, j = VectorSize - 1; i < j; i++, j--)
             {
                 T c = *(VectorBuffer + i);
                 *(VectorBuffer + i) = *(VectorBuffer + j);
                 *(VectorBuffer + j) = c;
             }
         }
References std::vector< T >::VectorBuffer, and std::vector< T >::VectorSize.
size()
template<class T > NIF size_t std::vector< T >::size () const inline
Definition at line 168 of file vector.hpp.
 { return VectorSize; }
References std::vector< T >::VectorSize.
Referenced by Tasking::Task::CreateThread(), CrashHandler::DisplayTasksScreen(), Driver::Driver::DriverLoadBindPCI(), Execute::ELFInterpreterIPCThread(), std::vector< T >::end(), and NetworkARP::ARP::ManageDiscoveredAddresses().
Field Documentation
VectorBuffer
template<class T > T* std::vector< T >::VectorBuffer = nullptr private
Definition at line 16 of file vector.hpp.
Referenced by std::vector< T >::back(), std::vector< T >::begin(), std::vector< T >::clear(), std::vector< T >::data(), std::vector< T >::end(), std::vector< T >::front(), std::vector< T >::next(), std::vector< T >::null_elem(), std::vector< T >::operator=(), std::vector< T >::operator[](), std::vector< T >::prev(), std::vector< T >::push_back(), std::vector< T >::remove(), std::vector< T >::reserve(), std::vector< T >::reverse(), std::vector< T >::vector(), and std::vector< T >::~vector().
VectorCapacity
template<class T > size_t std::vector< T >::VectorCapacity = 0 private
Definition at line 15 of file vector.hpp.
Referenced by std::vector< T >::capacity(), std::vector< T >::clear(), std::vector< T >::operator=(), std::vector< T >::push_back(), std::vector< T >::reserve(), std::vector< T >::vector(), and std::vector< T >::~vector().
VectorSize
template<class T > size_t std::vector< T >::VectorSize = 0 private
Definition at line 14 of file vector.hpp.
Referenced by std::vector< T >::back(), std::vector< T >::clear(), std::vector< T >::next(), std::vector< T >::operator=(), std::vector< T >::pop_back(), std::vector< T >::prev(), std::vector< T >::push_back(), std::vector< T >::remove(), std::vector< T >::reserve(), std::vector< T >::resize(), std::vector< T >::reverse(), std::vector< T >::size(), std::vector< T >::vector(), and std::vector< T >::~vector().
The documentation for this class was generated from the following file:
Kernel/include/std/vector.hpp