Fennix: Userspace/musl/include/ifaddrs.h File Reference
ifaddrs.h File Reference
#include <features.h>
#include <netinet/in.h>
#include <sys/socket.h>
Data Structures
struct ifaddrs
union ifaddrs.ifa_ifu
Macros
#define ifa_broadaddr ifa_ifu.ifu_broadaddr
#define ifa_dstaddr ifa_ifu.ifu_dstaddr
Functions
void freeifaddrs (struct ifaddrs *)
int getifaddrs (struct ifaddrs **)
Data Structure Documentation
ifaddrs
struct ifaddrs
Definition at line 12 of file ifaddrs.h.
Data Fields
struct sockaddr * ifa_addr
void * ifa_data
unsigned ifa_flags
union ifaddrs ifa_ifu
char * ifa_name
struct sockaddr * ifa_netmask
struct ifaddrs * ifa_next
ifaddrs.ifa_ifu
union ifaddrs.ifa_ifu
Definition at line 18 of file ifaddrs.h.
Data Fields
struct sockaddr * ifu_broadaddr
struct sockaddr * ifu_dstaddr
Macro Definition Documentation
ifa_broadaddr
#define ifa_broadaddr ifa_ifu.ifu_broadaddr
Definition at line 24 of file ifaddrs.h.
ifa_dstaddr
#define ifa_dstaddr ifa_ifu.ifu_dstaddr
Definition at line 25 of file ifaddrs.h.
Function Documentation
freeifaddrs()
void freeifaddrs (struct ifaddrs * ifp)
Definition at line 47 of file getifaddrs.c.
 {
     struct ifaddrs *n;
     while (ifp) {
         n = ifp->ifa_next;
         free(ifp);
         ifp = n;
     }
 }
References free, ifaddrs::ifa_next, and n.
Referenced by d6_read_interface(), and getifaddrs().
getifaddrs()
int getifaddrs (struct ifaddrs ** ifap)
Definition at line 207 of file getifaddrs.c.
 {
     struct ifaddrs_ctx _ctx, *ctx = &_ctx;
     int r;
     memset(ctx, 0, sizeof *ctx);
     r = __rtnetlink_enumerate(AF_UNSPEC, AF_UNSPEC, netlink_msg_to_ifaddr, ctx);
     if (r == 0) *ifap = ctx->first;
     else freeifaddrs(ctx->first);
     return r;
 }
References __rtnetlink_enumerate(), AF_UNSPEC, freeifaddrs(), memset, and netlink_msg_to_ifaddr().
Referenced by d6_read_interface().