Fennix Kernel: Tasking::ThreadSignal Class Reference
Tasking::ThreadSignal Class Reference
#include <signal.hpp>
Public Member Functions
sigset_t Block (sigset_t sig)
sigset_t Unblock (sigset_t sig)
sigset_t SetMask (sigset_t sig)
sigset_t GetMask ()
ThreadSignal (Signal &sig)
Data Fields
std::bitset< 64 > Mask = 0
Private Attributes
Signal & pSig
Detailed Description
Definition at line 473 of file signal.hpp.
Constructor & Destructor Documentation
ThreadSignal()
Tasking::ThreadSignal::ThreadSignal (Signal & sig) inline
Definition at line 486 of file signal.hpp.
 : pSig(sig) {}
Member Function Documentation
Block()
sigset_t Tasking::ThreadSignal::Block (sigset_t sig)
Definition at line 743 of file signal.cpp.
     {
         sigset_t oldMask = Mask.to_ulong();
         Mask |= sig;
         debug("%#lx -> %#lx", oldMask, Mask);
         return oldMask;
     }
References debug, and Mask.
Referenced by linux_sigprocmask().
GetMask()
sigset_t Tasking::ThreadSignal::GetMask ()
Definition at line 767 of file signal.cpp.
     {
         return Mask.to_ulong();
     }
References Mask.
Referenced by linux_sigprocmask().
SetMask()
sigset_t Tasking::ThreadSignal::SetMask (sigset_t sig)
Definition at line 759 of file signal.cpp.
     {
         sigset_t oldMask = Mask.to_ulong();
         Mask = sig;
         debug("%#lx -> %#lx", oldMask, Mask);
         return oldMask;
     }
References debug, and Mask.
Referenced by linux_sigprocmask().
Unblock()
sigset_t Tasking::ThreadSignal::Unblock (sigset_t sig)
Definition at line 751 of file signal.cpp.
     {
         sigset_t oldMask = Mask.to_ulong();
         Mask &= ~sig;
         debug("%#lx -> %#lx", oldMask, Mask);
         return oldMask;
     }
References debug, and Mask.
Referenced by linux_sigprocmask().
Field Documentation
Mask
std::bitset<64> Tasking::ThreadSignal::Mask = 0
Definition at line 479 of file signal.hpp.
Referenced by Block(), GetMask(), SetMask(), and Unblock().
pSig
Signal& Tasking::ThreadSignal::pSig private
Definition at line 476 of file signal.hpp.
The documentation for this class was generated from the following files:
Kernel/include/signal.hpp
Kernel/tasking/signal.cpp