Fennix: VirtualFileSystem::FileDescriptorTable Class Reference
VirtualFileSystem::FileDescriptorTable Class Reference
#include <filesystem.hpp>
Data Structures
struct DupFildes
struct Fildes
struct winsize
Public Member Functions
std::string GetAbsolutePath (int FileDescriptor)
std::vector< Fildes > & GetFileDescriptors ()
int _open (const char *pathname, int flags, mode_t mode)
int _creat (const char *pathname, mode_t mode)
ssize_t _read (int fd, void *buf, size_t count)
ssize_t _write (int fd, const void *buf, size_t count)
int _close (int fd)
off_t _lseek (int fd, off_t offset, int whence)
int _stat (const char *pathname, struct stat *statbuf)
int _fstat (int fd, struct stat *statbuf)
int _lstat (const char *pathname, struct stat *statbuf)
int _dup (int oldfd)
int _dup2 (int oldfd, int newfd)
int _ioctl (int fd, unsigned long request, void *argp)
FileDescriptorTable (void *Owner)
~FileDescriptorTable ()
Private Member Functions
Fildes GetFileDescriptor (int FileDescriptor)
FileDescriptorTable::DupFildes GetDupFildes (int FileDescriptor)
int ProbeMode (mode_t Mode, int Flags)
int AddFileDescriptor (const char *AbsolutePath, mode_t Mode, int Flags)
int RemoveFileDescriptor (int FileDescriptor)
int GetFreeFileDescriptor ()
Private Attributes
std::vector< Fildes > FileDescriptors
std::vector< DupFildes > FildesDuplicates
VirtualFileSystem::Node * fdDir = nullptr
Detailed Description
Definition at line 357 of file filesystem.hpp.
Data Structure Documentation
VirtualFileSystem::FileDescriptorTable::DupFildes
struct VirtualFileSystem::FileDescriptorTable::DupFildes
Definition at line 376 of file filesystem.hpp.
Data Fields
int Descriptor
int Flags
RefNode * Handle
mode_t Mode
VirtualFileSystem::FileDescriptorTable::Fildes
struct VirtualFileSystem::FileDescriptorTable::Fildes
Definition at line 368 of file filesystem.hpp.
Data Fields
int Descriptor
int Flags
RefNode * Handle
mode_t Mode
VirtualFileSystem::FileDescriptorTable::winsize
struct VirtualFileSystem::FileDescriptorTable::winsize
Definition at line 360 of file filesystem.hpp.
Data Fields
unsigned short ws_col
unsigned short ws_row
unsigned short ws_xpixel
unsigned short ws_ypixel
Constructor & Destructor Documentation
FileDescriptorTable()
VirtualFileSystem::FileDescriptorTable::FileDescriptorTable (void * Owner)
Definition at line 639 of file FileDescriptor.cpp.
     {
         this->fdDir = vfs->Create("fd", VirtualFileSystem::NodeFlags::DIRECTORY,
                                   ((Tasking::PCB *)Owner)->ProcessDirectory);
     }
References VirtualFileSystem::Virtual::Create(), VirtualFileSystem::DIRECTORY, fdDir, and vfs.
~FileDescriptorTable()
VirtualFileSystem::FileDescriptorTable::~FileDescriptorTable ()
Definition at line 645 of file FileDescriptor.cpp.
     {
         foreach (auto var in FileDescriptors)
         {
             this->RemoveFileDescriptor(var.Descriptor);
             delete var.Handle;
         }
     }
References FileDescriptors, and RemoveFileDescriptor().
Member Function Documentation
_close()
int VirtualFileSystem::FileDescriptorTable::_close (int fd)
Definition at line 358 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(fd);
         DupFildes dfdesc = this->GetDupFildes(fd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         if (RemoveFileDescriptor(fd) < 0)
         {
             errno = EBADF;
             return -1;
         }
         /* If the file descriptor is a duplicate,
             we don't need to close the handle,
             because it's a duplicate of another
             file descriptor. */
         bool Found = false;
         RefNode *hnd = nullptr;
         if (fdesc.Descriptor != -1)
             hnd = fdesc.Handle;
         else
             hnd = dfdesc.Handle;
         foreach (auto dfd in FileDescriptors)
         {
             if (dfd.Handle == hnd)
             {
                 Found = true;
                 break;
             }
         }
         foreach (auto dfd in FildesDuplicates)
         {
             if (dfd.Handle == hnd)
             {
                 Found = true;
                 break;
             }
         }
         if (!Found)
             delete hnd;
         return 0;
     }
References VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, errno, fd, FildesDuplicates, FileDescriptors, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, RefNode, and RemoveFileDescriptor().
Referenced by _dup2(), fclose(), sys_close(), and sys_file_close().
_creat()
int VirtualFileSystem::FileDescriptorTable::_creat (const char * pathname, mode_t mode)
Definition at line 312 of file FileDescriptor.cpp.
     {
         return _open(pathname, O_WRONLY | O_CREAT | O_TRUNC, mode);
     }
References _open(), O_CREAT, O_TRUNC, and O_WRONLY.
Referenced by creat(), and sys_creat().
_dup()
int VirtualFileSystem::FileDescriptorTable::_dup (int oldfd)
Definition at line 534 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(oldfd);
         DupFildes dfdesc = this->GetDupFildes(oldfd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         int newfd = this->GetFreeFileDescriptor();
         if (newfd < 0)
         {
             errno = EMFILE;
             return -1;
         }
         DupFildes new_dfd{};
         if (fdesc.Descriptor != -1)
         {
             new_dfd.Handle = fdesc.Handle;
             new_dfd.Mode = fdesc.Mode;
         }
         else
         {
             new_dfd.Handle = dfdesc.Handle;
             new_dfd.Mode = dfdesc.Mode;
         }
         new_dfd.Descriptor = newfd;
         this->FildesDuplicates.push_back(new_dfd);
         debug("Duplicated file descriptor %d to %d",
               oldfd, newfd);
         return newfd;
     }
References debug, VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, EMFILE, errno, FildesDuplicates, GetDupFildes(), GetFileDescriptor(), GetFreeFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, VirtualFileSystem::FileDescriptorTable::Fildes::Mode, and VirtualFileSystem::FileDescriptorTable::DupFildes::Mode.
Referenced by sys_dup().
_dup2()
int VirtualFileSystem::FileDescriptorTable::_dup2 (int oldfd, int newfd)
Definition at line 572 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(oldfd);
         DupFildes dfdesc = this->GetDupFildes(oldfd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         if (newfd < 0)
         {
             errno = EBADF;
             return -1;
         }
         if (newfd == oldfd)
             return newfd;
         /* Even if it's not valid
             we ignore it. */
         this->_close(newfd);
         DupFildes new_dfd{};
         if (fdesc.Descriptor != -1)
         {
             new_dfd.Handle = fdesc.Handle;
             new_dfd.Mode = fdesc.Mode;
         }
         else
         {
             new_dfd.Handle = dfdesc.Handle;
             new_dfd.Mode = dfdesc.Mode;
         }
         new_dfd.Descriptor = newfd;
         this->FildesDuplicates.push_back(new_dfd);
         debug("Duplicated file descriptor %d to %d",
               oldfd, newfd);
         return newfd;
     }
References _close(), debug, VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, errno, FildesDuplicates, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, VirtualFileSystem::FileDescriptorTable::Fildes::Mode, and VirtualFileSystem::FileDescriptorTable::DupFildes::Mode.
Referenced by sys_dup2().
_fstat()
int VirtualFileSystem::FileDescriptorTable::_fstat (int fd, struct stat * statbuf)
Definition at line 467 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(fd);
         DupFildes dfdesc = this->GetDupFildes(fd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         RefNode *hnd = nullptr;
         if (fdesc.Descriptor != -1)
             hnd = fdesc.Handle;
         else
             hnd = dfdesc.Handle;
         Node *node = hnd->node;
         statbuf->st_dev = 0; /* FIXME: stub */
         statbuf->st_ino = node->IndexNode;
         statbuf->st_mode = node->Flags | node->Mode;
         statbuf->st_nlink = 0; /* FIXME: stub */
         statbuf->st_uid = node->UserIdentifier;
         statbuf->st_gid = node->GroupIdentifier;
         statbuf->st_rdev = 0; /* FIXME: stub */
         statbuf->st_size = node->Length;
         statbuf->st_blksize = 0; /* FIXME: stub */
         statbuf->st_blocks = 0;  /* FIXME: stub */
         statbuf->st_attr = 0;    /* FIXME: stub */
         return 0;
     }
References VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, errno, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, RefNode, stat::st_attr, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, and stat::st_uid.
Referenced by fstat(), sys_file_status(), and sys_fstat().
_ioctl()
int VirtualFileSystem::FileDescriptorTable::_ioctl (int fd, unsigned long request, void * argp)
Definition at line 616 of file FileDescriptor.cpp.
     {
         struct winsize *ws = (struct winsize *)argp;
         Video::ScreenBuffer *sb = Display->GetBuffer(0);
         Video::FontInfo fi = Display->GetCurrentFont()->GetInfo();
         switch (request)
         {
         case TIOCGWINSZ:
             fixme("TIOCGWINSZ: stub");
             ws->ws_xpixel = uint16_t(sb->Width);
             ws->ws_ypixel = uint16_t(sb->Height);
             ws->ws_col = uint16_t(sb->Width / fi.Width);
             ws->ws_row = uint16_t(sb->Height / fi.Height);
             break;
         default:
             fixme("Unknown request %#lx", request);
             errno = ENOSYS;
             return -1;
         }
         return 0;
     }
References Display, ENOSYS, errno, fixme, Video::FontInfo::Height, Video::ScreenBuffer::Height, TIOCGWINSZ, Video::FontInfo::Width, Video::ScreenBuffer::Width, VirtualFileSystem::FileDescriptorTable::winsize::ws_col, VirtualFileSystem::FileDescriptorTable::winsize::ws_row, VirtualFileSystem::FileDescriptorTable::winsize::ws_xpixel, and VirtualFileSystem::FileDescriptorTable::winsize::ws_ypixel.
Referenced by sys_ioctl().
_lseek()
off_t VirtualFileSystem::FileDescriptorTable::_lseek (int fd, off_t offset, int whence)
Definition at line 412 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(fd);
         DupFildes dfdesc = this->GetDupFildes(fd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         RefNode *hnd = nullptr;
         if (fdesc.Descriptor != -1)
             hnd = fdesc.Handle;
         else
             hnd = dfdesc.Handle;
         return hnd->Seek(offset, whence);
     }
References VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, errno, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, offset, and RefNode.
Referenced by lseek(), sys_file_seek(), and sys_lseek().
_lstat()
int VirtualFileSystem::FileDescriptorTable::_lstat (const char * pathname, struct stat * statbuf)
Definition at line 500 of file FileDescriptor.cpp.
     {
         if (pathname == nullptr)
         {
             errno = EINVAL;
             return -1;
         }
         RefNode *file = vfs->Open(pathname,
                                   thisProcess->CurrentWorkingDirectory);
         if (!file)
         {
             error("Failed to open file %s: %d",
                   pathname, errno);
             return -1;
         }
         Node *node = file->node;
         statbuf->st_dev = 0; /* FIXME: stub */
         statbuf->st_ino = node->IndexNode;
         statbuf->st_mode = node->Flags | node->Mode;
         statbuf->st_nlink = 0; /* FIXME: stub */
         statbuf->st_uid = node->UserIdentifier;
         statbuf->st_gid = node->GroupIdentifier;
         statbuf->st_rdev = 0; /* FIXME: stub */
         statbuf->st_size = node->Length;
         statbuf->st_blksize = 0; /* FIXME: stub */
         statbuf->st_blocks = 0;  /* FIXME: stub */
         statbuf->st_attr = 0;    /* FIXME: stub */
         return 0;
     }
References EINVAL, errno, error, VirtualFileSystem::Virtual::Open(), RefNode, stat::st_attr, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, thisProcess, and vfs.
Referenced by lstat(), and sys_lstat().
_open()
int VirtualFileSystem::FileDescriptorTable::_open (const char * pathname, int flags, mode_t mode)
Definition at line 300 of file FileDescriptor.cpp.
     {
         if (pathname == nullptr)
         {
             errno = EFAULT;
             return -1;
         }
         return AddFileDescriptor(pathname, mode, flags);
     }
References AddFileDescriptor(), EFAULT, errno, and flags.
Referenced by _creat(), fopen(), sys_file_open(), and sys_open().
_read()
ssize_t VirtualFileSystem::FileDescriptorTable::_read (int fd, void * buf, size_t count)
Definition at line 317 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(fd);
         DupFildes dfdesc = this->GetDupFildes(fd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         RefNode *hnd = nullptr;
         if (fdesc.Descriptor != -1)
             hnd = fdesc.Handle;
         else
             hnd = dfdesc.Handle;
         return hnd->Read((uint8_t *)buf, count);
     }
References buf, count, VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, errno, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, and RefNode.
Referenced by fread(), sys_file_read(), and sys_read().
_stat()
int VirtualFileSystem::FileDescriptorTable::_stat (const char * pathname, struct stat * statbuf)
Definition at line 433 of file FileDescriptor.cpp.
     {
         if (pathname == nullptr)
         {
             errno = EINVAL;
             return -1;
         }
         RefNode *file = vfs->Open(pathname,
                                   thisProcess->CurrentWorkingDirectory);
         if (!file)
         {
             error("Failed to open file %s: %d",
                   pathname, errno);
             return -1;
         }
         Node *node = file->node;
         statbuf->st_dev = 0; /* FIXME: stub */
         statbuf->st_ino = node->IndexNode;
         statbuf->st_mode = node->Flags | node->Mode;
         statbuf->st_nlink = 0; /* FIXME: stub */
         statbuf->st_uid = node->UserIdentifier;
         statbuf->st_gid = node->GroupIdentifier;
         statbuf->st_rdev = 0; /* FIXME: stub */
         statbuf->st_size = node->Length;
         statbuf->st_blksize = 0; /* FIXME: stub */
         statbuf->st_blocks = 0;  /* FIXME: stub */
         statbuf->st_attr = 0;    /* FIXME: stub */
         return 0;
     }
References EINVAL, errno, error, VirtualFileSystem::Virtual::Open(), RefNode, stat::st_attr, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, thisProcess, and vfs.
Referenced by stat(), and sys_stat().
_write()
ssize_t VirtualFileSystem::FileDescriptorTable::_write (int fd, const void * buf, size_t count)
Definition at line 337 of file FileDescriptor.cpp.
     {
         Fildes fdesc = this->GetFileDescriptor(fd);
         DupFildes dfdesc = this->GetDupFildes(fd);
         if (fdesc.Descriptor < 0 &&
             dfdesc.Descriptor < 0)
         {
             errno = EBADF;
             return -1;
         }
         RefNode *hnd = nullptr;
         if (fdesc.Descriptor != -1)
             hnd = fdesc.Handle;
         else
             hnd = dfdesc.Handle;
         return hnd->Write((uint8_t *)buf, count);
     }
References buf, count, VirtualFileSystem::FileDescriptorTable::Fildes::Descriptor, VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, EBADF, errno, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::FileDescriptorTable::Fildes::Handle, VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, and RefNode.
Referenced by fwrite(), sys_file_write(), and sys_write().
AddFileDescriptor()
int VirtualFileSystem::FileDescriptorTable::AddFileDescriptor (const char * AbsolutePath, mode_t Mode, int Flags) private
Definition at line 120 of file FileDescriptor.cpp.
     {
         Tasking::PCB *pcb = thisProcess;
         if (ProbeMode(Mode, Flags) < 0)
         {
             errno = EACCES;
             return -1;
         }
         if (Flags & O_CREAT)
         {
             Node *n = vfs->Create(AbsolutePath,
                                   NodeFlags::FILE,
                                   pcb->CurrentWorkingDirectory);
             if (!n)
             {
                 debug("%s: File already exists, continuing...",
                       AbsolutePath);
             }
         }
         if (Flags & O_EXCL)
         {
             RefNode *File = vfs->Open(AbsolutePath,
                                       pcb->CurrentWorkingDirectory);
             if (!File)
             {
                 errno = EEXIST;
                 error("Failed to open file %s: %d",
                       AbsolutePath, errno);
                 return -1;
             }
         }
         if (Flags & O_TRUNC)
         {
             fixme("O_TRUNC");
         }
         if (Flags & O_APPEND)
         {
             fixme("O_APPEND");
         }
         if (Flags & O_CLOEXEC)
         {
             fixme("O_CLOEXEC");
         }
         RefNode *File = vfs->Open(AbsolutePath,
                                   pcb->CurrentWorkingDirectory);
         if (!File)
         {
             error("Failed to open file %s: %d",
                   AbsolutePath, errno);
             return -1;
         }
         Fildes fd = {.Descriptor = GetFreeFileDescriptor()};
         if (fd.Descriptor < 0)
         {
             errno = EMFILE;
             return -1;
         }
         fd.Mode = Mode;
         fd.Flags = Flags;
         fd.Handle = File;
         FileDescriptors.push_back(fd);
         char FileName[64];
         sprintf(FileName, "%d", fd.Descriptor);
         VirtualFileSystem::Node *n = vfs->Create(FileName, VirtualFileSystem::NodeFlags::FILE, this->fdDir);
         if (n)
         {
             /* FIXME: Implement proper file descriptors */
             n->Address = (uintptr_t)0xdeadbeef;
             n->Length = File->FileSize;
             n->Operator = &fd_op;
         }
         return fd.Descriptor;
     }
References VirtualFileSystem::Virtual::Create(), Tasking::PCB::CurrentWorkingDirectory, debug, EACCES, EEXIST, EMFILE, errno, error, fd, VirtualFileSystem::fd_op, fdDir, FileDescriptors, fixme, Flags, GetFreeFileDescriptor(), n, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_TRUNC, VirtualFileSystem::Virtual::Open(), ProbeMode(), RefNode, sprintf(), thisProcess, and vfs.
Referenced by _open().
GetAbsolutePath()
std::string VirtualFileSystem::FileDescriptorTable::GetAbsolutePath (int FileDescriptor)
Definition at line 279 of file FileDescriptor.cpp.
     {
         Fildes fd = this->GetFileDescriptor(FileDescriptor);
         DupFildes dfd = this->GetDupFildes(FileDescriptor);
         if (fd.Descriptor == -1 &&
             dfd.Descriptor == -1)
             return "";
         RefNode *hnd = nullptr;
         if (fd.Descriptor != -1)
             hnd = fd.Handle;
         else
             hnd = dfd.Handle;
         Node *node = hnd->node;
         std::string absolutePath = vfs->GetPathFromNode(node);
         std::string path = absolutePath.c_str();
         return path;
     }
References std::string::c_str(), VirtualFileSystem::FileDescriptorTable::DupFildes::Descriptor, fd, GetDupFildes(), GetFileDescriptor(), VirtualFileSystem::Virtual::GetPathFromNode(), VirtualFileSystem::FileDescriptorTable::DupFildes::Handle, RefNode, and vfs.
GetDupFildes()
FileDescriptorTable::DupFildes VirtualFileSystem::FileDescriptorTable::GetDupFildes (int FileDescriptor) private
Definition at line 83 of file FileDescriptor.cpp.
     {
         foreach (auto fd in FildesDuplicates)
         {
             if (fd.Descriptor == FileDescriptor)
             {
                 debug("Found duplicated file descriptor %d", FileDescriptor);
                 return fd;
             }
         }
         return {};
     }
References debug, fd, and FildesDuplicates.
Referenced by _close(), _dup(), _dup2(), _fstat(), _lseek(), _read(), _write(), and GetAbsolutePath().
GetFileDescriptor()
FileDescriptorTable::Fildes VirtualFileSystem::FileDescriptorTable::GetFileDescriptor (int FileDescriptor) private
Definition at line 69 of file FileDescriptor.cpp.
     {
         foreach (auto fd in FileDescriptors)
         {
             if (fd.Descriptor == FileDescriptor)
             {
                 debug("Found file descriptor %d", FileDescriptor);
                 return fd;
             }
         }
         return {};
     }
References debug, fd, and FileDescriptors.
Referenced by _close(), _dup(), _dup2(), _fstat(), _lseek(), _read(), _write(), and GetAbsolutePath().
GetFileDescriptors()
std::vector<Fildes>& VirtualFileSystem::FileDescriptorTable::GetFileDescriptors () inline
Definition at line 399 of file filesystem.hpp.
 { return FileDescriptors; }
References FileDescriptors.
GetFreeFileDescriptor()
int VirtualFileSystem::FileDescriptorTable::GetFreeFileDescriptor () private
Definition at line 243 of file FileDescriptor.cpp.
     {
         int i = 0;
         while (true)
         {
             bool Found = false;
             foreach (auto fd in FileDescriptors)
             {
                 if (fd.Descriptor == i)
                 {
                     Found = true;
                     break;
                 }
             }
             if (!Found)
             {
                 foreach (auto fd in FildesDuplicates)
                 {
                     if (fd.Descriptor == i)
                     {
                         Found = true;
                         break;
                     }
                 }
             }
             if (!Found)
                 return i;
             i++;
         }
         errno = EMFILE;
         return -1;
     }
References EMFILE, errno, fd, FildesDuplicates, FileDescriptors, and i.
Referenced by _dup(), and AddFileDescriptor().
ProbeMode()
int VirtualFileSystem::FileDescriptorTable::ProbeMode (mode_t Mode, int Flags) private
Definition at line 96 of file FileDescriptor.cpp.
     {
         if (Flags & O_RDONLY)
         {
             if (!(Mode & S_IRUSR))
                 return -EACCES;
         }
         if (Flags & O_WRONLY)
         {
             if (!(Mode & S_IWUSR))
                 return -EACCES;
         }
         if (Flags & O_RDWR)
         {
             if (!(Mode & S_IRUSR) ||
                 !(Mode & S_IWUSR))
                 return -EACCES;
         }
         return 0;
     }
References EACCES, Flags, O_RDONLY, O_RDWR, O_WRONLY, S_IRUSR, and S_IWUSR.
Referenced by AddFileDescriptor().
RemoveFileDescriptor()
int VirtualFileSystem::FileDescriptorTable::RemoveFileDescriptor (int FileDescriptor) private
Definition at line 211 of file FileDescriptor.cpp.
     {
         forItr(itr, FileDescriptors)
         {
             if (itr->Descriptor == FileDescriptor)
             {
                 FileDescriptors.erase(itr);
                 char FileName[64];
                 sprintf(FileName, "%d", FileDescriptor);
                 vfs->Delete(FileName, false, this->fdDir);
                 return 0;
             }
         }
         forItr(itr, FildesDuplicates)
         {
             if (itr->Descriptor == FileDescriptor)
             {
                 FildesDuplicates.erase(itr);
                 char FileName[64];
                 sprintf(FileName, "%d", FileDescriptor);
                 vfs->Delete(FileName, false, this->fdDir);
                 return 0;
             }
         }
         errno = EBADF;
         return -1;
     }
References VirtualFileSystem::Virtual::Delete(), EBADF, errno, fdDir, FildesDuplicates, FileDescriptors, sprintf(), and vfs.
Referenced by _close(), and ~FileDescriptorTable().
Field Documentation
fdDir
VirtualFileSystem::Node* VirtualFileSystem::FileDescriptorTable::fdDir = nullptr private
Definition at line 387 of file filesystem.hpp.
Referenced by AddFileDescriptor(), FileDescriptorTable(), and RemoveFileDescriptor().
FildesDuplicates
std::vector<DupFildes> VirtualFileSystem::FileDescriptorTable::FildesDuplicates private
Definition at line 386 of file filesystem.hpp.
Referenced by _close(), _dup(), _dup2(), GetDupFildes(), GetFreeFileDescriptor(), and RemoveFileDescriptor().
FileDescriptors
std::vector<Fildes> VirtualFileSystem::FileDescriptorTable::FileDescriptors private
Definition at line 385 of file filesystem.hpp.
Referenced by _close(), AddFileDescriptor(), GetFileDescriptor(), GetFileDescriptors(), GetFreeFileDescriptor(), RemoveFileDescriptor(), and ~FileDescriptorTable().
The documentation for this class was generated from the following files:
Kernel/include/filesystem.hpp
Kernel/FileSystem/FileDescriptor.cpp