Fennix: Userspace/musl/src/malloc/mallocng/glue.h File Reference
glue.h File Reference
#include <stdint.h>
#include <sys/mman.h>
#include <pthread.h>
#include <unistd.h>
#include <elf.h>
#include <string.h>
#include "atomic.h"
#include "syscall.h"
#include "libc.h"
#include "lock.h"
#include "dynlink.h"
Macros
#define size_classes __malloc_size_classes
#define ctx __malloc_context
#define alloc_meta __malloc_alloc_meta
#define is_allzero __malloc_allzerop
#define dump_heap __dump_heap
#define malloc __libc_malloc_impl
#define realloc __libc_realloc
#define free __libc_free
#define USE_MADV_FREE 0
#define assert(x) do { if (!(x)) a_crash(); } while(0)
#define brk(p) ((uintptr_t)__syscall(SYS_brk, p))
#define mmap __mmap
#define madvise __madvise
#define mremap __mremap
#define DISABLE_ALIGNED_ALLOC (__malloc_replaced && !__aligned_alloc_replaced)
#define PAGESIZE PAGE_SIZE
#define MT (libc.need_locks)
#define RDLOCK_IS_EXCLUSIVE 1
#define LOCK_OBJ_DEF
Functions
static uint64_t get_random_secret ()
__attribute__ ((__visibility__("hidden"))) extern int __malloc_lock[1]
static void rdlock ()
static void wrlock ()
static void unlock ()
static void upgradelock ()
static void resetlock ()
static void malloc_atfork (int who)
Macro Definition Documentation
alloc_meta
#define alloc_meta (void) __malloc_alloc_meta
Definition at line 19 of file glue.h.
assert
#define assert (x) do { if (!(x)) a_crash(); } while(0)
Definition at line 33 of file glue.h.
brk
#define brk (p) ((uintptr_t)__syscall(SYS_brk, p))
Definition at line 36 of file glue.h.
ctx
#define ctx __malloc_context
Definition at line 18 of file glue.h.
DISABLE_ALIGNED_ALLOC
#define DISABLE_ALIGNED_ALLOC (__malloc_replaced && !__aligned_alloc_replaced)
Definition at line 42 of file glue.h.
dump_heap
#define dump_heap __dump_heap
Definition at line 21 of file glue.h.
free
#define free __libc_free
Definition at line 25 of file glue.h.
is_allzero
#define is_allzero __malloc_allzerop
Definition at line 20 of file glue.h.
LOCK_OBJ_DEF
#define LOCK_OBJ_DEF
Value:
int __malloc_lock[1]; \
void __malloc_atfork(int who) { malloc_atfork(who); }
Definition at line 64 of file glue.h.
madvise
#define madvise __madvise
Definition at line 39 of file glue.h.
malloc
#define malloc __libc_malloc_impl
Definition at line 23 of file glue.h.
mmap
#define mmap __mmap
Definition at line 38 of file glue.h.
mremap
#define mremap __mremap
Definition at line 40 of file glue.h.
MT
#define MT (libc.need_locks)
Definition at line 57 of file glue.h.
PAGESIZE
#define PAGESIZE PAGE_SIZE
Definition at line 54 of file glue.h.
RDLOCK_IS_EXCLUSIVE
#define RDLOCK_IS_EXCLUSIVE 1
Definition at line 59 of file glue.h.
realloc
#define realloc __libc_realloc
Definition at line 24 of file glue.h.
size_classes
#define size_classes __malloc_size_classes
Definition at line 17 of file glue.h.
USE_MADV_FREE
#define USE_MADV_FREE 0
Definition at line 27 of file glue.h.
Function Documentation
__attribute__()
__attribute__ ((__visibility__("hidden")))
get_random_secret()
static uint64_t get_random_secret () inline static
Definition at line 44 of file glue.h.
 {
     uint64_t secret = (uintptr_t)&secret * 1103515245;
     for (size_t i=0; libc.auxv[i]; i+=2)
         if (libc.auxv[i]==AT_RANDOM)
             memcpy(&secret, (char *)libc.auxv[i+1]+8, sizeof secret);
     return secret;
 }
References AT_RANDOM, i, libc, memcpy, and secret.
Referenced by alloc_meta().
malloc_atfork()
static void malloc_atfork (int who) inline static
Definition at line 88 of file glue.h.
 {
     if (who<0) rdlock();
     else if (who>0) resetlock();
     else unlock();
 }
References rdlock(), resetlock(), and unlock().
rdlock()
static void rdlock () inline static
Definition at line 68 of file glue.h.
 {
     if (MT) LOCK(__malloc_lock);
 }
References LOCK, and MT.
Referenced by malloc(), and malloc_atfork().
resetlock()
static void resetlock () inline static
Definition at line 83 of file glue.h.
 {
     __malloc_lock[0] = 0;
 }
Referenced by malloc_atfork().
unlock()
static void unlock () inline static
Definition at line 76 of file glue.h.
 {
     UNLOCK(__malloc_lock);
 }
References UNLOCK.
Referenced by free(), malloc_atfork(), and unlockpt().
upgradelock()
static void upgradelock () inline static
Definition at line 80 of file glue.h.
 {
 }
Referenced by malloc().
wrlock()
static void wrlock () inline static
Definition at line 72 of file glue.h.
 {
     if (MT) LOCK(__malloc_lock);
 }
References LOCK, and MT.
Referenced by free(), and malloc().