Fennix Kernel: Driver Namespace Reference
Driver Namespace Reference
Data Structures
struct DriverHandlers
struct DriverObject
class Manager
struct DriverObject.Version
Functions
int __fs_Lookup (struct Inode *_Parent, const char *Name, struct Inode **Result)
int __fs_Create (struct Inode *_Parent, const char *Name, mode_t Mode, struct Inode **Result)
ssize_t __fs_Read (struct Inode *Node, void *Buffer, size_t Size, off_t Offset)
ssize_t __fs_Write (struct Inode *Node, const void *Buffer, size_t Size, off_t Offset)
int __fs_Open (struct Inode *Node, int Flags, mode_t Mode)
int __fs_Close (struct Inode *Node)
int __fs_Ioctl (struct Inode *Node, unsigned long Request, void *Argp)
__no_sanitize ("alignment") ssize_t __fs_Readdir(struct Inode *_Node
if (Offset==0)
if (Offset<=1)
if (!S_ISDIR(Node->Node.Mode)) return -ENOTDIR
if ((Offset >=2 ?(Offset - 2) :Offset) >(off_t) Node->Children.size()) return -EINVAL
for (const auto &var :Node->Children)
if (totalSize+sizeof(struct kdirent) >=Size) return totalSize
void ManagerDaemonWrapper ()
char GetScanCode (uint8_t ScanCode, bool Upper)
bool IsValidChar (uint8_t ScanCode)
Variables
TTY::PTMXDevice * ptmx = nullptr
struct kdirent * Buffer
struct kdirent size_t Size
struct kdirent size_t off_t Offset
struct kdirent size_t off_t off_t Entries
auto Node = (Manager::DeviceInode *)_Node
off_t realOffset = Offset
size_t totalSize = 0
uint16_t reclen = 0
struct kdirent * ent = nullptr
off_t entries = 0
ent d_ino = 0
ent d_off = 0
ent d_reclen = 0
ent d_type = DT_UNKNOWN
ent d_name [0] = '\0'
Data Structure Documentation
Driver::DriverHandlers
struct Driver::DriverHandlers
Definition at line 46 of file driver.hpp.
Data Fields
RingBuffer< InputReport > * InputReports
struct Inode * Node
const InodeOperations * Ops
Driver::DriverObject.Version
struct Driver::DriverObject.Version
Definition at line 68 of file driver.hpp.
Data Fields
int Major
int Minor
int Patch
Function Documentation
__fs_Close()
int Driver::__fs_Close (struct Inode * Node)
Definition at line 367 of file daemon.cpp.
     {
         func("%#lx", Node);
         switch (Node->GetMajor())
         {
         case 0:
         {
             switch (Node->GetMinor())
             {
             case 2: /* /dev/null */
             case 3: /* /dev/zero */
             case 4: /* /dev/random */
             case 5: /* /dev/mem */
                 return -ENOSYS;
             case 6: /* /dev/kcon */
                 return KernelConsole::CurrentTerminal.load()->Close();
             case 7: /* /dev/tty */
             {
                 TTY::TeletypeDriver *tty = (TTY::TeletypeDriver *)thisProcess->tty;
                 if (tty == nullptr)
                     return -ENOTTY;
                 return tty->Close();
             }
             case 8: /* /dev/ptmx */
                 return ptmx->Close();
             default:
                 return -ENOENT;
             };
         }
         case 1:
         {
             switch (Node->GetMinor())
             {
             case 0: /* /dev/input/keyboard */
             case 1: /* /dev/input/mouse */
                 return -ENOTSUP;
             default:
                 return -ENOENT;
             };
         }
         default:
         {
             std::unordered_map<dev_t, Driver::DriverObject> &drivers =
                 DriverManager->GetDrivers();
             const auto it = drivers.find(Node->GetMajor());
             if (it == drivers.end())
                 ReturnLogError(-EINVAL, "Driver %d not found", Node->GetMajor());
             const Driver::DriverObject *drv = &it->second;
             auto dop = drv->DeviceOperations;
             auto dOps = dop->find(Node->GetMinor());
             if (dOps == dop->end())
                 ReturnLogError(-EINVAL, "Device %d not found", Node->GetMinor());
             AssertReturnError(dOps->second.Ops, -ENOTSUP);
             AssertReturnError(dOps->second.Ops->Close, -ENOTSUP);
             return dOps->second.Ops->Close(Node);
         }
         }
     }
References AssertReturnError, TTY::TeletypeDriver::Close(), TTY::PTMXDevice::Close(), KernelConsole::CurrentTerminal, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, ENOENT, ENOSYS, ENOTSUP, ENOTTY, func(), Driver::Manager::GetDrivers(), vfs::if(), it, vfs::Node, ptmx, ReturnLogError, and thisProcess.
Referenced by Driver::Manager::InitializeDaemonFS().
__fs_Create()
int Driver::__fs_Create (struct Inode * _Parent, const char * Name, mode_t Mode, struct Inode ** Result)
Definition at line 90 of file daemon.cpp.
     {
         func("%#lx %s %d", _Parent, Name, Mode);
         assert(_Parent != nullptr);
         /* We expect to be /dev or children of it */
         auto Parent = (Manager::DeviceInode *)_Parent;
         auto _dev = new Manager::DeviceInode;
         _dev->Parent = nullptr;
         _dev->ParentInode = _Parent;
         _dev->Name = Name;
         _dev->Node.Mode = Mode;
         _dev->Node.Index = Parent->Node.Index + Parent->Children.size();
         Parent->Children.push_back(_dev);
         *Result = &_dev->Node;
         return 0;
     }
References assert, func(), Name, and Driver::Manager::DeviceInode::Parent.
Referenced by Driver::Manager::InitializeDaemonFS().
__fs_Ioctl()
int Driver::__fs_Ioctl (struct Inode * Node, unsigned long Request, void * Argp)
Definition at line 428 of file daemon.cpp.
     {
         func("%#lx %lu %#lx", Node, Request, Argp);
         switch (Node->GetMajor())
         {
         case 0:
         {
             switch (Node->GetMinor())
             {
             case 2: /* /dev/null */
             case 3: /* /dev/zero */
             case 4: /* /dev/random */
             case 5: /* /dev/mem */
                 return -ENOSYS;
             case 6: /* /dev/kcon */
                 return KernelConsole::CurrentTerminal.load()->Ioctl(Request, Argp);
             case 7: /* /dev/tty */
             {
                 TTY::TeletypeDriver *tty = (TTY::TeletypeDriver *)thisProcess->tty;
                 if (tty == nullptr)
                     return -ENOTTY;
                 return tty->Ioctl(Request, Argp);
             }
             case 8: /* /dev/ptmx */
                 return -ENOSYS;
             default:
                 return -ENOENT;
             };
             break;
         }
         case 1:
         {
             switch (Node->GetMinor())
             {
             case 0: /* /dev/input/keyboard */
             case 1: /* /dev/input/mouse */
                 return -ENOSYS;
             default:
                 return -ENOENT;
             };
         }
         default:
         {
             std::unordered_map<dev_t, Driver::DriverObject> &drivers =
                 DriverManager->GetDrivers();
             const auto it = drivers.find(Node->GetMajor());
             if (it == drivers.end())
                 ReturnLogError(-EINVAL, "Driver %d not found", Node->GetMajor());
             const Driver::DriverObject *drv = &it->second;
             auto dop = drv->DeviceOperations;
             auto dOps = dop->find(Node->GetMinor());
             if (dOps == dop->end())
                 ReturnLogError(-EINVAL, "Device %d not found", Node->GetMinor());
             AssertReturnError(dOps->second.Ops, -ENOTSUP);
             AssertReturnError(dOps->second.Ops->Ioctl, -ENOTSUP);
             return dOps->second.Ops->Ioctl(Node, Request, Argp);
         }
         }
     }
References AssertReturnError, KernelConsole::CurrentTerminal, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, ENOENT, ENOSYS, ENOTSUP, ENOTTY, func(), Driver::Manager::GetDrivers(), vfs::if(), TTY::TeletypeDriver::Ioctl(), it, vfs::Node, ReturnLogError, and thisProcess.
Referenced by Driver::Manager::InitializeDaemonFS().
__fs_Lookup()
int Driver::__fs_Lookup (struct Inode * _Parent, const char * Name, struct Inode ** Result)
Definition at line 60 of file daemon.cpp.
     {
         func("%#lx %s %#lx", _Parent, Name, Result);
         assert(_Parent != nullptr);
         const char *basename;
         size_t length;
         cwk_path_get_basename(Name, &basename, &length);
         if (basename == NULL)
         {
             error("Invalid name %s", Name);
             return -EINVAL;
         }
         auto Parent = (Manager::DeviceInode *)_Parent;
         for (const auto &child : Parent->Children)
         {
             debug("Comparing %s with %s", basename, child->Name.c_str());
             if (strcmp(child->Name.c_str(), basename) != 0)
                 continue;
             *Result = &child->Node;
             return 0;
         }
         debug("Not found %s", Name);
         return -ENOENT;
     }
References assert, cwk_path_get_basename(), debug, EINVAL, ENOENT, error, func(), Name, NULL, and strcmp().
Referenced by Driver::Manager::InitializeDaemonFS().
__fs_Open()
int Driver::__fs_Open (struct Inode * Node, int Flags, mode_t Mode)
Definition at line 306 of file daemon.cpp.
     {
         func("%#lx %d %d", Node, Flags, Mode);
         switch (Node->GetMajor())
         {
         case 0:
         {
             switch (Node->GetMinor())
             {
             case 2: /* /dev/null */
             case 3: /* /dev/zero */
             case 4: /* /dev/random */
             case 5: /* /dev/mem */
                 return -ENOSYS;
             case 6: /* /dev/kcon */
                 return KernelConsole::CurrentTerminal.load()->Open(Flags, Mode);
             case 7: /* /dev/tty */
             {
                 TTY::TeletypeDriver *tty = (TTY::TeletypeDriver *)thisProcess->tty;
                 if (tty == nullptr)
                     return -ENOTTY;
                 return tty->Open(Flags, Mode);
             }
             case 8: /* /dev/ptmx */
                 return ptmx->Open();
             default:
                 return -ENOENT;
             };
         }
         case 1:
         {
             switch (Node->GetMinor())
             {
             case 0: /* /dev/input/keyboard */
             case 1: /* /dev/input/mouse */
                 return -ENOTSUP;
             default:
                 return -ENOENT;
             };
         }
         default:
         {
             std::unordered_map<dev_t, Driver::DriverObject> &drivers =
                 DriverManager->GetDrivers();
             const auto it = drivers.find(Node->GetMajor());
             if (it == drivers.end())
                 ReturnLogError(-EINVAL, "Driver %d not found", Node->GetMajor());
             const Driver::DriverObject *drv = &it->second;
             auto dop = drv->DeviceOperations;
             auto dOps = dop->find(Node->GetMinor());
             if (dOps == dop->end())
                 ReturnLogError(-EINVAL, "Device %d not found", Node->GetMinor());
             AssertReturnError(dOps->second.Ops, -ENOTSUP);
             AssertReturnError(dOps->second.Ops->Open, -ENOTSUP);
             return dOps->second.Ops->Open(Node, Flags, Mode);
         }
         }
     }
References AssertReturnError, KernelConsole::CurrentTerminal, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, ENOENT, ENOSYS, ENOTSUP, ENOTTY, Flags, func(), Driver::Manager::GetDrivers(), vfs::if(), it, vfs::Node, TTY::PTMXDevice::Open(), TTY::TeletypeDriver::Open(), ptmx, ReturnLogError, and thisProcess.
Referenced by Driver::Manager::InitializeDaemonFS().
__fs_Read()
ssize_t Driver::__fs_Read (struct Inode * Node, void * Buffer, size_t Size, off_t Offset)
Definition at line 110 of file daemon.cpp.
     {
         func("%#lx %d %d", Node, Size, Offset);
         switch (Node->GetMajor())
         {
         case 0:
         {
             switch (Node->GetMinor())
             {
             case 2: /* /dev/null */
             {
                 return 0;
             }
             case 3: /* /dev/zero */
             {
                 if (Size <= 0)
                     return 0;
                 memset(Buffer, 0, Size);
                 return Size;
             }
             case 4: /* /dev/random */
             {
                 if (Size <= 0)
                     return 0;
                 if (Size < sizeof(uint64_t))
                 {
                     uint8_t *buf = (uint8_t *)Buffer;
                     for (size_t i = 0; i < Size; i++)
                         buf[i] = (uint8_t)(Random::rand16() & 0xFF);
                     return Size;
                 }
                 uint64_t *buf = (uint64_t *)Buffer;
                 for (size_t i = 0; i < Size / sizeof(uint64_t); i++)
                     buf[i] = Random::rand64();
                 return Size;
             }
             case 5: /* /dev/mem */
             {
                 stub;
                 return 0;
             }
             case 6: /* /dev/kcon */
                 return KernelConsole::CurrentTerminal.load()->Read(Buffer, Size, Offset);
             case 7: /* /dev/tty */
             {
                 TTY::TeletypeDriver *tty = (TTY::TeletypeDriver *)thisProcess->tty;
                 if (tty == nullptr)
                     return -ENOTTY;
                 return tty->Read(Buffer, Size, Offset);
             }
             case 8: /* /dev/ptmx */
                 return -ENOSYS;
             default:
                 return -ENOENT;
             };
             break;
         }
         case 1:
         {
             switch (Node->GetMinor())
             {
             case 0: /* /dev/input/keyboard */
             {
                 if (Size < sizeof(KeyboardReport))
                     return -EINVAL;
                 size_t nReads = Size / sizeof(KeyboardReport);
                 KeyboardReport *report = (KeyboardReport *)Buffer;
                 while (DriverManager->GlobalKeyboardInputReports.Count() == 0)
                     TaskManager->Yield();
                 DriverManager->GlobalKeyboardInputReports.Read(report, nReads);
                 return sizeof(KeyboardReport) * nReads;
             }
             case 1: /* /dev/input/mouse */
             {
                 if (Size < sizeof(MouseReport))
                     return -EINVAL;
                 size_t nReads = Size / sizeof(MouseReport);
                 MouseReport *report = (MouseReport *)Buffer;
                 while (DriverManager->GlobalMouseInputReports.Count() == 0)
                     TaskManager->Yield();
                 DriverManager->GlobalMouseInputReports.Read(report, nReads);
                 return sizeof(MouseReport) * nReads;
             }
             default:
                 return -ENOENT;
             };
         }
         default:
         {
             std::unordered_map<dev_t, Driver::DriverObject> &drivers =
                 DriverManager->GetDrivers();
             const auto it = drivers.find(Node->GetMajor());
             if (it == drivers.end())
                 ReturnLogError(-EINVAL, "Driver %d not found", Node->GetMajor());
             const Driver::DriverObject *drv = &it->second;
             auto dop = drv->DeviceOperations;
             auto dOps = dop->find(Node->GetMinor());
             if (dOps == dop->end())
                 ReturnLogError(-EINVAL, "Device %d not found", Node->GetMinor());
             AssertReturnError(dOps->second.Ops, -ENOTSUP);
             AssertReturnError(dOps->second.Ops->Read, -ENOTSUP);
             return dOps->second.Ops->Read(Node, Buffer, Size, Offset);
         }
         }
     }
References AssertReturnError, vfs::Buffer, RingBuffer< T >::Count(), KernelConsole::CurrentTerminal, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, ENOENT, ENOSYS, ENOTSUP, ENOTTY, func(), Driver::Manager::GetDrivers(), Driver::Manager::GlobalKeyboardInputReports, Driver::Manager::GlobalMouseInputReports, vfs::if(), it, memset(), vfs::Node, vfs::Offset, Random::rand16(), Random::rand64(), RingBuffer< T >::Read(), TTY::TeletypeDriver::Read(), ReturnLogError, vfs::Size, stub, TaskManager, thisProcess, and Tasking::Task::Yield().
Referenced by Driver::Manager::InitializeDaemonFS().
__fs_Write()
ssize_t Driver::__fs_Write (struct Inode * Node, const void * Buffer, size_t Size, off_t Offset)
Definition at line 228 of file daemon.cpp.
     {
         func("%#lx %p %d %d", Node, Buffer, Size, Offset);
         switch (Node->GetMajor())
         {
         case 0:
         {
             switch (Node->GetMinor())
             {
             case 2: /* /dev/null */
             {
                 return Size;
             }
             case 3: /* /dev/zero */
             {
                 return Size;
             }
             case 4: /* /dev/random */
             {
                 return Size;
             }
             case 5: /* /dev/mem */
             {
                 stub;
                 return 0;
             }
             case 6: /* /dev/kcon */
                 return KernelConsole::CurrentTerminal.load()->Write(Buffer, Size, Offset);
             case 7: /* /dev/tty */
             {
                 TTY::TeletypeDriver *tty = (TTY::TeletypeDriver *)thisProcess->tty;
                 if (tty == nullptr)
                     return -ENOTTY;
                 return tty->Write(Buffer, Size, Offset);
             }
             case 8: /* /dev/ptmx */
                 return -ENOSYS;
             default:
                 return -ENOENT;
             };
         }
         case 1:
         {
             switch (Node->GetMinor())
             {
             case 0: /* /dev/input/keyboard */
             {
                 return -ENOTSUP;
             }
             case 1: /* /dev/input/mouse */
             {
                 return -ENOTSUP;
             }
             default:
                 return -ENOENT;
             };
         }
         default:
         {
             std::unordered_map<dev_t, Driver::DriverObject> &drivers =
                 DriverManager->GetDrivers();
             const auto it = drivers.find(Node->GetMajor());
             if (it == drivers.end())
                 ReturnLogError(-EINVAL, "Driver %d not found", Node->GetMajor());
             const Driver::DriverObject *drv = &it->second;
             auto dop = drv->DeviceOperations;
             auto dOps = dop->find(Node->GetMinor());
             if (dOps == dop->end())
                 ReturnLogError(-EINVAL, "Device %d not found", Node->GetMinor());
             AssertReturnError(dOps->second.Ops, -ENOTSUP);
             AssertReturnError(dOps->second.Ops->Write, -ENOTSUP);
             return dOps->second.Ops->Write(Node, Buffer, Size, Offset);
         }
         }
     }
References AssertReturnError, vfs::Buffer, KernelConsole::CurrentTerminal, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, ENOENT, ENOSYS, ENOTSUP, ENOTTY, func(), Driver::Manager::GetDrivers(), vfs::if(), it, vfs::Node, vfs::Offset, ReturnLogError, vfs::Size, stub, thisProcess, and TTY::TeletypeDriver::Write().
Referenced by Driver::Manager::InitializeDaemonFS().
__no_sanitize()
Driver::__no_sanitize ("alignment")
for()
Driver::for (const auto &var :Node-> Children)
Definition at line 553 of file daemon.cpp.
                              : Node->Children)
         {
             debug("iterating \"%s\" inside \"%s\"", var->Name.c_str(), Node->Name.c_str());
             if (var->Node.Offset < realOffset)
             {
                 debug("skipping \"%s\" (%d < %d)", var->Name.c_str(), var->Node.Offset, Offset);
                 continue;
             }
             if (entries >= Entries)
                 break;
             reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen(var->Name.c_str()) + 1);
             if (totalSize + reclen >= Size)
                 break;
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             ent->d_ino = var->Node.Index;
             ent->d_off = var->Node.Offset;
             ent->d_reclen = reclen;
             ent->d_type = IFTODT(var->Node.Mode);
             strncpy(ent->d_name, var->Name.c_str(), strlen(var->Name.c_str()));
             totalSize += reclen;
             entries++;
         }
References vfs::Buffer, kdirent::d_ino, vfs::d_name, kdirent::d_name, kdirent::d_off, kdirent::d_reclen, kdirent::d_type, debug, vfs::ent, vfs::Entries, vfs::entries, IFTODT, vfs::vfsInode::Name, vfs::Node, vfs::Offset, offsetof, realOffset, reclen, vfs::Size, strlen(), strncpy(), and vfs::totalSize.
Referenced by SMBIOS::__no_sanitize(), and Memory::__no_sanitize().
GetScanCode()
char Driver::GetScanCode (uint8_t ScanCode, bool Upper)
Definition at line 319 of file scancode.cpp.
     {
         ScanCode &= 0x7F; /* Remove KEY_PRESSED bit */
         if (ScanCode >= sizeof(ScanCodeConversionTableLower))
         {
             warn("Unknown scancode %x", ScanCode);
             return 0x00;
         }
         // debug("Scancode %x (%s)", ScanCode, ScanCodeDebugNames[ScanCode]);
         return Upper
                    ? ScanCodeConversionTableUpper[ScanCode]
                    : ScanCodeConversionTableLower[ScanCode];
     }
References ScanCodeConversionTableLower, ScanCodeConversionTableUpper, and warn.
Referenced by KShellThread(), and KernelConsole::VirtualTerminal::Read().
if() [1/5]
Driver::if (! S_ISDIRNode->Node.Mode)
if() [2/5]
Driver::if ((Offset >=2 ?(Offset - 2) :Offset) , (off_t) Node->Children.size())
if() [3/5]
Driver::if (Offset<= 1)
Definition at line 518 of file daemon.cpp.
         {
             reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen("..") + 1);
             if (totalSize + reclen >= Size)
             {
                 if (realOffset == 1)
                     return -EINVAL;
                 return totalSize;
             }
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             if (Node->Parent)
                 ent->d_ino = Node->Parent->Node->Index;
             else if (Node->ParentInode)
                 ent->d_ino = Node->ParentInode->Index;
             else
             {
                 warn("Parent is null for %s", Node->Name.c_str());
                 ent->d_ino = Node->Node.Index;
             }
             ent->d_off = Offset++;
             ent->d_reclen = reclen;
             ent->d_type = DT_DIR;
             strcpy(ent->d_name, "..");
             totalSize += reclen;
         }
References vfs::Buffer, kdirent::d_ino, vfs::d_name, kdirent::d_name, kdirent::d_off, kdirent::d_reclen, kdirent::d_type, DT_DIR, EINVAL, vfs::ent, Inode::Index, vfs::vfsInode::Name, vfs::vfsInode::Node, vfs::Node, vfs::Offset, offsetof, realOffset, reclen, vfs::Size, strcpy, strlen(), vfs::totalSize, and warn.
if() [4/5]
Driver::if (Offset = = 0)
Definition at line 503 of file daemon.cpp.
         {
             reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen(".") + 1);
             if (totalSize + reclen >= Size)
                 return -EINVAL;
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             ent->d_ino = Node->Node.Index;
             ent->d_off = Offset++;
             ent->d_reclen = reclen;
             ent->d_type = DT_DIR;
             strcpy(ent->d_name, ".");
             totalSize += reclen;
         }
References vfs::Buffer, kdirent::d_ino, vfs::d_name, kdirent::d_name, kdirent::d_off, kdirent::d_reclen, kdirent::d_type, DT_DIR, EINVAL, vfs::ent, Inode::Index, vfs::vfsInode::Node, vfs::Node, vfs::Offset, offsetof, reclen, vfs::Size, strcpy, strlen(), and vfs::totalSize.
if() [5/5]
Driver::if (totalSize+sizeof(struct kdirent) >= Size)
IsValidChar()
bool Driver::IsValidChar (uint8_t ScanCode)
Definition at line 334 of file scancode.cpp.
     {
         ScanCode &= 0x7F; /* Remove KEY_PRESSED bit */
         if (ScanCode >= sizeof(ScanCodeConversionTableLower))
             return false;
         if (ScanCode > KEY_M)
         {
             if (ScanCode < KEYPAD_7)
                 return false; /* F1 - F12 */
             switch (ScanCode)
             {
             case KEY_MINUS:
             case KEY_EQUAL:
             case KEY_LEFT_BRACKET:
             case KEY_RIGHT_BRACKET:
             case KEY_RETURN:
             case KEY_SEMICOLON:
             case KEY_APOSTROPHE:
             case KEY_BACK_TICK:
             case KEY_BACKSLASH:
             case KEY_COMMA:
             case KEY_PERIOD:
             case KEY_SLASH:
             case KEY_SPACE:
                 return true;
             default:
                 return false;
             }
         }
         return true;
     }
References KEY_APOSTROPHE, KEY_BACK_TICK, KEY_BACKSLASH, KEY_COMMA, KEY_EQUAL, KEY_LEFT_BRACKET, KEY_M, KEY_MINUS, KEY_PERIOD, KEY_RETURN, KEY_RIGHT_BRACKET, KEY_SEMICOLON, KEY_SLASH, KEY_SPACE, KEYPAD_7, and ScanCodeConversionTableLower.
Referenced by KShellThread(), and KernelConsole::VirtualTerminal::Read().
ManagerDaemonWrapper()
void Driver::ManagerDaemonWrapper ()
Definition at line 593 of file daemon.cpp.
 { DriverManager->Daemon(); }
References Driver::Manager::Daemon(), and DriverManager.
Referenced by KernelMainThread().
Variable Documentation
Buffer
struct kdirent* Driver::Buffer
Definition at line 491 of file daemon.cpp.
Referenced by Video::__no_sanitize(), __ustar_Read(), __ustar_Readdir(), __ustar_ReadLink(), crc32(), DumpData(), Execute::ELFLoadRel(), ExDumpData(), itoa(), ltoa(), operator delete(), FileNode::Read(), Disk::Partition::Read(), TTY::PTYDevice::PTYMaster::Read(), TTY::PTYDevice::PTYSlave::Read(), TTY::PTYDevice::Read(), TTY::TeletypeDriver::Read(), KernelConsole::VirtualTerminal::Read(), FileNode::ReadDir(), FileNode::ReadLink(), reverse(), MediaAccessControl::ToString(), InternetProtocol::Version4::ToStringBigEndian(), InternetProtocol::Version6::ToStringBigEndian(), InternetProtocol::Version4::ToStringLittleEndian(), InternetProtocol::Version6::ToStringLittleEndian(), PCI::Descriptors::u32ToHexString(), PCI::Descriptors::u8ToHexString(), ultoa(), FileNode::Write(), TTY::PTYDevice::PTYMaster::Write(), TTY::PTYDevice::PTYSlave::Write(), TTY::PTYDevice::Write(), TTY::TeletypeDriver::Write(), KernelConsole::VirtualTerminal::Write(), and Disk::Partition::Write().
d_ino
ent Driver::d_ino = 0
Definition at line 585 of file daemon.cpp.
d_name
ent Driver::d_name[0] = '\0'
Definition at line 589 of file daemon.cpp.
d_off
ent Driver::d_off = 0
Definition at line 586 of file daemon.cpp.
d_reclen
ent Driver::d_reclen = 0
Definition at line 587 of file daemon.cpp.
d_type
ent Driver::d_type = DT_UNKNOWN
Definition at line 588 of file daemon.cpp.
ent
Driver::ent = nullptr
Definition at line 501 of file daemon.cpp.
Entries
struct kdirent size_t off_t off_t Driver::Entries
Initial value:
{
        func("%#lx %#lx %d %d %d", _Node, Buffer, Size, Offset, Entries)
Definition at line 491 of file daemon.cpp.
entries
off_t Driver::entries = 0
Definition at line 552 of file daemon.cpp.
Node
auto Driver::Node = (Manager::DeviceInode *)_Node
Definition at line 495 of file daemon.cpp.
Referenced by __ustar_DestroyInode(), __ustar_Read(), __ustar_Readdir(), __ustar_ReadLink(), __ustar_Stat(), and Execute::GetBinaryType().
Offset
struct kdirent size_t off_t Driver::Offset
Definition at line 491 of file daemon.cpp.
Referenced by __ustar_Read(), __ustar_Readdir(), __cxxabiv1::adjust_pointer(), Execute::ELFLookupString(), PCI::Manager::EnumerateBus(), PCI::Manager::EnumerateDevice(), PCI::Manager::EnumerateFunction(), FileNode::Read(), Disk::Partition::Read(), Disk::Drive::Read(), TTY::TeletypeDriver::Read(), FileNode::ReadDir(), FileNode::Seek(), FileNode::Write(), TTY::TeletypeDriver::Write(), Disk::Partition::Write(), and Disk::Drive::Write().
ptmx
TTY::PTMXDevice* Driver::ptmx = nullptr
maj = 0 min: 0 - <ROOT> 1 - /proc/self 2 - /dev/null 3 - /dev/zero 4 - /dev/random 5 - /dev/mem 6 - /dev/kcon 7 - /dev/tty 8 - /dev/ptmx
maj = 1 min: 0 - /dev/input/keyboard 1 - /dev/input/mouse ..- /dev/input/eventX
Definition at line 58 of file daemon.cpp.
Referenced by __fs_Close(), __fs_Open(), and Driver::Manager::InitializeDaemonFS().
realOffset
off_t Driver::realOffset = Offset
Definition at line 497 of file daemon.cpp.
Referenced by vfs::__no_sanitize(), for(), and if().
reclen
uint16_t Driver::reclen = 0
Definition at line 500 of file daemon.cpp.
Referenced by vfs::__no_sanitize(), for(), vfs::foreach(), and if().
Size
struct kdirent size_t Driver::Size
Definition at line 491 of file daemon.cpp.
totalSize
return Driver::totalSize = 0
Definition at line 499 of file daemon.cpp.