Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/deh_main.h File Reference
deh_main.h File Reference
#include "doomtype.h"
#include "doomfeatures.h"
#include "deh_str.h"
#include "sha1.h"
Macros
#define DEH_VANILLA_NUMSTATES 966
#define DEH_VANILLA_NUMSFX 107
Functions
void DEH_ParseCommandLine (void)
int DEH_LoadFile (char *filename)
int DEH_LoadLump (int lumpnum, boolean allow_long, boolean allow_error)
int DEH_LoadLumpByName (char *name, boolean allow_long, boolean allow_error)
boolean DEH_ParseAssignment (char *line, char **variable_name, char **value)
void DEH_Checksum (sha1_digest_t digest)
Variables
boolean deh_allow_extended_strings
boolean deh_allow_long_strings
boolean deh_allow_long_cheats
boolean deh_apply_cheats
Macro Definition Documentation
DEH_VANILLA_NUMSFX
#define DEH_VANILLA_NUMSFX 107
Definition at line 31 of file deh_main.h.
DEH_VANILLA_NUMSTATES
#define DEH_VANILLA_NUMSTATES 966
Definition at line 30 of file deh_main.h.
Function Documentation
DEH_Checksum()
void DEH_Checksum (sha1_digest_t digest)
Referenced by InitConnectData().
DEH_LoadFile()
int DEH_LoadFile (char * filename)
DEH_LoadLump()
int DEH_LoadLump (int lumpnum, boolean allow_long, boolean allow_error)
Referenced by D_DoomMain().
DEH_LoadLumpByName()
int DEH_LoadLumpByName (char * name, boolean allow_long, boolean allow_error)
DEH_ParseAssignment()
boolean DEH_ParseAssignment (char * line, char ** variable_name, char ** value)
DEH_ParseCommandLine()
void DEH_ParseCommandLine (void)
Referenced by D_DoomMain().
Variable Documentation
deh_allow_extended_strings
boolean deh_allow_extended_strings extern
deh_allow_long_cheats
boolean deh_allow_long_cheats extern
deh_allow_long_strings
boolean deh_allow_long_strings extern
deh_apply_cheats
boolean deh_apply_cheats extern