Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/get_devname.c File Reference
get_devname.c File Reference
#include <sys/mount.h>
#include "volume_id_internal.h"
Data Structures
struct uuidCache_s
Macros
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
#define get_label_uuid(fd, label, uuid, type) get_label_uuid(fd, label, uuid)
#define uuidcache_addentry(device, label, uuid, type) uuidcache_addentry(device, label, uuid)
#define UUID 1
#define VOL 2
Functions
static int get_label_uuid (int fd, char **label, char **uuid, const char **type)
static void uuidcache_addentry (char *device, char *label, char *uuid, const char *type)
static int FAST_FUNC uuidcache_check_device (struct recursive_state *state UNUSED_PARAM, const char *device, struct stat *statbuf)
static struct uuidCache_s * uuidcache_init (int scan_devices)
void display_uuid_cache (int scan_devices)
int add_to_uuid_cache (const char *device)
char * get_devname_from_label (const char *spec)
char * get_devname_from_uuid (const char *spec)
int resolve_mount_spec (char **fsname)
Variables
static struct uuidCache_s * uuidCache
Data Structure Documentation
uuidCache_s
struct uuidCache_s
Definition at line 22 of file get_devname.c.
Data Fields
char * device
char * label
struct uuidCache_s * next
char * uc_uuid
Macro Definition Documentation
BLKGETSIZE64
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
Definition at line 18 of file get_devname.c.
get_label_uuid
#define get_label_uuid (fd, label, uuid, type) get_label_uuid(fd, label, uuid)
Definition at line 32 of file get_devname.c.
UUID
#define UUID 1
Definition at line 158 of file get_devname.c.
uuidcache_addentry
#define uuidcache_addentry (device, label, uuid, type) uuidcache_addentry(device, label, uuid)
Definition at line 34 of file get_devname.c.
VOL
#define VOL 2
Definition at line 159 of file get_devname.c.
Function Documentation
add_to_uuid_cache()
int add_to_uuid_cache (const char * device)
Definition at line 252 of file get_devname.c.
 {
     char *uuid = uuid; /* for compiler */
     char *label = label;
 #if ENABLE_FEATURE_BLKID_TYPE
     const char *type = type;
 #endif
     int fd;
     fd = open(device, O_RDONLY);
     if (fd < 0)
         return 0;
     /* get_label_uuid() closes fd in all cases (success & failure) */
     if (get_label_uuid(fd, &label, &uuid, &type) == 0) {
         /* uuidcache_addentry() takes ownership of all four params */
         uuidcache_addentry(xstrdup(device), /*ma, mi,*/ label, uuid, type);
         return 1;
     }
     return 0;
 }
References device, fd, get_label_uuid, label, O_RDONLY, open(), type, uuidcache_addentry, and xstrdup().
Referenced by blkid_main(), and uuidcache_check_device().
display_uuid_cache()
void display_uuid_cache (int scan_devices)
Definition at line 232 of file get_devname.c.
 {
     struct uuidCache_s *uc;
     uc = uuidcache_init(scan_devices);
     while (uc) {
         printf("%s:", uc->device);
         if (uc->label[0])
             printf(" LABEL=\"%s\"", uc->label);
         if (uc->uc_uuid[0])
             printf(" UUID=\"%s\"", uc->uc_uuid);
 #if ENABLE_FEATURE_BLKID_TYPE
     if (uc->type)
         printf(" TYPE=\"%s\"", uc->type);
 #endif
         bb_putchar('\n');
         uc = uc->next;
     }
 }
References bb_putchar(), uuidCache_s::device, uuidCache_s::label, uuidCache_s::next, printf(), uuidCache_s::uc_uuid, and uuidcache_init().
Referenced by blkid_main().
get_devname_from_label()
char* get_devname_from_label (const char * spec)
Definition at line 277 of file get_devname.c.
 {
     struct uuidCache_s *uc;
     uc = uuidcache_init(/*scan_devices:*/ 1);
     while (uc) {
         if (uc->label[0] && strcmp(spec, uc->label) == 0) {
             return xstrdup(uc->device);
         }
         uc = uc->next;
     }
     return NULL;
 }
References uuidCache_s::device, uuidCache_s::label, uuidCache_s::next, NULL, strcmp, uuidcache_init(), and xstrdup().
Referenced by resolve_mount_spec().
get_devname_from_uuid()
char* get_devname_from_uuid (const char * spec)
Definition at line 291 of file get_devname.c.
 {
     struct uuidCache_s *uc;
     uc = uuidcache_init(/*scan_devices:*/ 1);
     while (uc) {
         /* case of hex numbers doesn't matter */
         if (strcasecmp(spec, uc->uc_uuid) == 0) {
             return xstrdup(uc->device);
         }
         uc = uc->next;
     }
     return NULL;
 }
References uuidCache_s::device, uuidCache_s::next, NULL, strcasecmp, uuidCache_s::uc_uuid, uuidcache_init(), and xstrdup().
Referenced by resolve_mount_spec().
get_label_uuid()
static int get_label_uuid (int fd, char ** label, char ** uuid, const char ** type) static
Definition at line 43 of file get_devname.c.
 {
     int rv = 1;
     uint64_t size;
     struct volume_id *vid;
     /* fd is owned by vid now */
     vid = volume_id_open_node(fd);
     if (ioctl(/*vid->*/fd, BLKGETSIZE64, &size) != 0)
         size = 0;
     if (volume_id_probe_all(vid, /*0,*/ size) != 0)
         goto ret;
     if (vid->label[0] != '\0' || vid->uuid[0] != '\0'
 #if ENABLE_FEATURE_BLKID_TYPE
      || vid->type != NULL
 #endif
     ) {
         *label = xstrndup(vid->label, sizeof(vid->label));
         *uuid  = xstrndup(vid->uuid, sizeof(vid->uuid));
 #if ENABLE_FEATURE_BLKID_TYPE
         *type = vid->type;
         dbg("found label '%s', uuid '%s', type '%s'", *label, *uuid, *type);
 #else
         dbg("found label '%s', uuid '%s'", *label, *uuid);
 #endif
         rv = 0;
     }
  ret:
     free_volume_id(vid); /* also closes fd */
     return rv;
 }
References BLKGETSIZE64, dbg, fd, free_volume_id(), ioctl(), label, volume_id::label, NULL, size, type, volume_id::uuid, volume_id_open_node(), volume_id_probe_all(), and xstrndup().
resolve_mount_spec()
int resolve_mount_spec (char ** fsname)
Definition at line 306 of file get_devname.c.
 {
     char *tmp = *fsname;
     if (is_prefixed_with(*fsname, "UUID="))
         tmp = get_devname_from_uuid(*fsname + 5);
     else if (is_prefixed_with(*fsname, "LABEL="))
         tmp = get_devname_from_label(*fsname + 6);
     if (tmp == *fsname)
         return 0; /* no UUID= or LABEL= prefix found */
     if (tmp)
         *fsname = tmp;
     return 1;
 }
References get_devname_from_label(), get_devname_from_uuid(), and is_prefixed_with().
uuidcache_addentry()
static void uuidcache_addentry (char * device, char * label, char * uuid, const char * type) static
Definition at line 80 of file get_devname.c.
 {
     struct uuidCache_s *last;
     if (!uuidCache) {
         last = uuidCache = xzalloc(sizeof(*uuidCache));
     } else {
         for (last = uuidCache; last->next; last = last->next)
             continue;
         last->next = xzalloc(sizeof(*uuidCache));
         last = last->next;
     }
     /*last->next = NULL; - xzalloc did it*/
 //  last->major = major;
 //  last->minor = minor;
     last->device = device;
     last->label = label;
     last->uc_uuid = uuid;
     IF_FEATURE_BLKID_TYPE(last->type = type;)
 }
References device, label, last, type, uuidCache, and xzalloc().
uuidcache_check_device()
static int FAST_FUNC uuidcache_check_device (struct recursive_state *state UNUSED_PARAM, const char * device, struct stat * statbuf) static
Definition at line 105 of file get_devname.c.
 {
     /* note: this check rejects links to devices, among other nodes */
     if (!S_ISBLK(statbuf->st_mode)
 #if ENABLE_FEATURE_VOLUMEID_UBIFS
      && !(S_ISCHR(statbuf->st_mode) && strncmp(bb_basename(device), "ubi", 3) == 0)
 #endif
     )
         return TRUE;
     /* Users report that mucking with floppies (especially non-present
      * ones) is significant PITA. This is a horribly dirty hack,
      * but it is very useful in real world.
      * If this will ever need to be enabled, consider using O_NONBLOCK.
      */
     if (major(statbuf->st_rdev) == 2)
         return TRUE;
     add_to_uuid_cache(device);
     return TRUE;
 }
References add_to_uuid_cache(), bb_basename(), device, major, S_ISBLK, S_ISCHR, stat::st_mode, stat::st_rdev, strncmp(), and TRUE.
Referenced by uuidcache_init().
uuidcache_init()
static struct uuidCache_s* uuidcache_init (int scan_devices) static
Definition at line 131 of file get_devname.c.
 {
     dbg("DBG: uuidCache=%x, uuidCache");
     if (uuidCache)
         return uuidCache;
     /* We were scanning /proc/partitions
      * and /proc/sys/dev/cdrom/info here.
      * Missed volume managers. I see that "standard" blkid uses these:
      * /dev/mapper/control
      * /proc/devices
      * /proc/evms/volumes
      * /proc/lvm/VGs
      * This is unacceptably complex. Let's just scan /dev.
      * (Maybe add scanning of /sys/block/XXX/dev for devices
      * somehow not having their /dev/XXX entries created?) */
     if (scan_devices) {
         recursive_action("/dev", ACTION_RECURSE,
             uuidcache_check_device, /* file_action */
             NULL, /* dir_action */
             NULL /* userData */
         );
     }
     return uuidCache;
 }
References ACTION_RECURSE, dbg, NULL, recursive_action(), uuidCache, and uuidcache_check_device().
Referenced by display_uuid_cache(), get_devname_from_label(), and get_devname_from_uuid().
Variable Documentation
uuidCache
struct uuidCache_s * uuidCache static
Referenced by uuidcache_addentry(), and uuidcache_init().