Fennix: Bitmap Class Reference
Bitmap Class Reference
#include <bitmap.hpp>
Public Member Functions
bool operator[] (uint64_t index)
bool Set (uint64_t index, bool value)
bool Get (uint64_t index)
bool operator[] (uint64_t index)
bool Set (uint64_t index, bool value)
bool Get (uint64_t index)
Data Fields
size_t Size
uint8_t * Buffer
Detailed Description
Definition at line 23 of file bitmap.hpp.
Member Function Documentation
Get() [1/2]
bool Bitmap::Get (uint64_t index)
Definition at line 22 of file Bitmap.cpp.
 {
     if (index > Size * 8)
         return false;
     uint64_t byteIndex = index / 8;
     uint8_t bitIndex = index % 8;
     uint8_t bitIndexer = 0b10000000 >> bitIndex;
     if ((Buffer[byteIndex] & bitIndexer) > 0)
         return true;
     return false;
 }
References Buffer, index(), and Size.
Referenced by operator[](), and CrashHandler::UserInput().
Get() [2/2]
bool Bitmap::Get (uint64_t index)
operator[]() [1/2]
bool Bitmap::operator[] (uint64_t index)
Definition at line 20 of file Bitmap.cpp.
 { return Get(index); }
References Get(), and index().
operator[]() [2/2]
bool Bitmap::operator[] (uint64_t index)
Set() [1/2]
bool Bitmap::Set (uint64_t index, bool value)
Definition at line 34 of file Bitmap.cpp.
 {
     if (index > Size * 8)
         return false;
     uint64_t byteIndex = index / 8;
     uint8_t bitIndex = index % 8;
     uint8_t bitIndexer = 0b10000000 >> bitIndex;
     Buffer[byteIndex] &= ~bitIndexer;
     if (value)
         Buffer[byteIndex] |= bitIndexer;
     return true;
 }
References Buffer, index(), Size, and value.
Referenced by Memory32::Physical::FreePage(), Memory32::Physical::LockPage(), Memory32::Physical::ReservePage(), Memory32::Physical::ReservePages(), Memory32::Physical::UnreservePage(), and Memory32::Physical::UnreservePages().
Set() [2/2]
bool Bitmap::Set (uint64_t index, bool value)
Field Documentation
Buffer
uint8_t * Bitmap::Buffer
Definition at line 27 of file bitmap.hpp.
Referenced by Get(), Memory32::Physical::Init(), Memory64::Physical::Init(), and Set().
Size
size_t Bitmap::Size
Definition at line 26 of file bitmap.hpp.
Referenced by Get(), Memory32::Physical::Init(), Memory64::Physical::Init(), Memory32::Physical::RequestPage(), Memory32::Physical::RequestPages(), Set(), and CrashHandler::UserInput().
The documentation for this class was generated from the following files:
Kernel/include/bitmap.hpp
Kernel/Library/Bitmap.cpp