Fennix: Userspace/apps/base/busybox/archival/libarchive/unsafe_prefix.c File Reference
unsafe_prefix.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
const char *FAST_FUNC strip_unsafe_prefix (const char *str)
Function Documentation
strip_unsafe_prefix()
const char* FAST_FUNC strip_unsafe_prefix (const char * str)
Definition at line 8 of file unsafe_prefix.c.
 {
     const char *cp = str;
     while (1) {
         char *cp2;
         if (*cp == '/') {
             cp++;
             continue;
         }
         if (is_prefixed_with(cp, "/../"+1)) {
             cp += 3;
             continue;
         }
         cp2 = strstr(cp, "/../");
         if (!cp2)
             break;
         cp = cp2 + 4;
     }
     if (cp != str) {
         static smallint warned = 0;
         if (!warned) {
             warned = 1;
             bb_error_msg("removing leading '%.*s' from member names",
                 (int)(cp - str), str);
         }
     }
     return cp;
 }
References bb_error_msg(), is_prefixed_with(), str, and strstr().
Referenced by get_header_tar(), and unzip_main().