Fennix Kernel: Kernel/kshell/commands/tree.cpp File Reference
tree.cpp File Reference
#include "../cmds.hpp"
#include <filesystem.hpp>
#include "../../kernel.h"
Functions
void tree_loop (Node *rootNode, int depth=0)
void cmd_tree (const char *args)
Function Documentation
cmd_tree()
void cmd_tree (const char * args)
Definition at line 50 of file tree.cpp.
 {
     Node *rootNode = thisProcess->CurrentWorkingDirectory;
     if (args[0] == '\0')
     {
         if (rootNode == nullptr)
             rootNode = fs->GetRootNode()->Children[0];
     }
     else
     {
         rootNode = fs->GetNodeFromPath(args, thisProcess->CurrentWorkingDirectory);
         if (rootNode == nullptr)
         {
             printf("ls: %s: No such file or directory\n", args);
             return;
         }
         if (rootNode->Type != NodeType::DIRECTORY)
         {
             printf("%s\n", rootNode->Name);
             return;
         }
     }
     printf("%s\n", rootNode->Name);
     tree_loop(rootNode);
 }
References vfs::Node::Children, vfs::DIRECTORY, fs, vfs::Virtual::GetNodeFromPath(), vfs::Virtual::GetRootNode(), vfs::Node::Name, printf, thisProcess, tree_loop(), and vfs::Node::Type.
tree_loop()
void tree_loop (Node * rootNode, int depth = 0)
Definition at line 26 of file tree.cpp.
 {
     foreach (auto Child in rootNode->Children)
     {
         Display->SetBuffer(0);
         if (Child->Type == NodeType::DIRECTORY ||
             Child->Type == NodeType::MOUNTPOINT)
         {
             printf("%*s%*s%*s|- %s\n",
                    depth, "",
                    depth, "",
                    depth, "",
                    Child->Name);
             tree_loop(Child, depth + 1);
         }
         else
             printf("%*s%*s%*s|- %s\n",
                    depth, "",
                    depth, "",
                    depth, "",
                    Child->Name);
     }
 }
References vfs::DIRECTORY, Display, vfs::MOUNTPOINT, printf, and Video::Display::SetBuffer().
Referenced by cmd_tree().