Fennix Userspace: Userspace/apps/base/busybox/miscutils/ubirename.c File Reference
ubirename.c File Reference
#include "libbb.h"
#include <mtd/mtd-user.h>
Data Structures
struct ubi_rnvol_req
struct ubi_rnvol_req.ents
Macros
#define __packed __attribute__((packed))
#define UBI_MAX_VOLUME_NAME 127
#define UBI_MAX_VOLUMES 128
#define UBI_IOC_MAGIC 'o'
#define UBI_IOCRNVOL _IOW(UBI_IOC_MAGIC, 3, struct ubi_rnvol_req)
#define UBI_MAX_RNVOL 32
Functions
int ubirename_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct ubi_rnvol_req __packed
Data Structure Documentation
ubi_rnvol_req
struct ubi_rnvol_req
Definition at line 47 of file ubirename.c.
Data Fields
int32_t count
struct ubi_rnvol_req ents[UBI_MAX_RNVOL]
int8_t padding1[12]
ubi_rnvol_req.ents
struct ubi_rnvol_req.ents
Definition at line 50 of file ubirename.c.
Data Fields
char name[UBI_MAX_VOLUME_NAME+1]
int16_t name_len
int8_t padding2[2]
int32_t vol_id
Macro Definition Documentation
__packed
#define __packed __attribute__((packed))
Definition at line 29 of file ubirename.c.
UBI_IOC_MAGIC
#define UBI_IOC_MAGIC 'o'
Definition at line 39 of file ubirename.c.
UBI_IOCRNVOL
#define UBI_IOCRNVOL _IOW(UBI_IOC_MAGIC, 3, struct ubi_rnvol_req)
Definition at line 42 of file ubirename.c.
UBI_MAX_RNVOL
#define UBI_MAX_RNVOL 32
Definition at line 45 of file ubirename.c.
UBI_MAX_VOLUME_NAME
#define UBI_MAX_VOLUME_NAME 127
Definition at line 33 of file ubirename.c.
UBI_MAX_VOLUMES
#define UBI_MAX_VOLUMES 128
Definition at line 34 of file ubirename.c.
Function Documentation
ubirename_main()
int ubirename_main (int argc, char ** argv)
Definition at line 60 of file ubirename.c.
 {
     struct ubi_rnvol_req *rnvol;
     const char *ubi_devname;
     unsigned ubi_devnum;
     unsigned n;
     /* argc can be 4, 6, 8, ... */
     if ((argc & 1) || (argc >>= 1) < 2)
         bb_show_usage();
     rnvol = xzalloc(sizeof(*rnvol));
     rnvol->count = --argc;
     if (argc > ARRAY_SIZE(rnvol->ents))
         bb_simple_error_msg_and_die("too many renames requested");
     ubi_devname = argv[1];
     ubi_devnum = ubi_devnum_from_devname(ubi_devname);
     n = 0;
     argv += 2;
     while (argv[0]) {
         rnvol->ents[n].vol_id = ubi_get_volid_by_name(ubi_devnum, argv[0]);
         /* strnlen avoids overflow of 16-bit field (paranoia) */
         rnvol->ents[n].name_len = strnlen(argv[1], sizeof(rnvol->ents[n].name));
         if (rnvol->ents[n].name_len >= sizeof(rnvol->ents[n].name))
             bb_error_msg_and_die("new name '%s' is too long", argv[1]);
         strcpy(rnvol->ents[n].name, argv[1]);
         n++;
         argv += 2;
     }
     xioctl(xopen(ubi_devname, O_RDONLY), UBI_IOCRNVOL, rnvol);
     return 0;
 }
References argc, argv, ARRAY_SIZE, bb_error_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), ubi_rnvol_req::count, ubi_rnvol_req::ents, n, O_RDONLY, strcpy(), strnlen(), ubi_devnum_from_devname(), ubi_get_volid_by_name(), UBI_IOCRNVOL, xioctl, xopen(), and xzalloc().
Variable Documentation
__packed
struct ubi_rnvol_req __packed