Fennix Userspace: Userspace/apps/base/busybox/libbb/kernel_version.c File Reference
kernel_version.c File Reference
#include "libbb.h"
#include <sys/utsname.h>
Functions
int FAST_FUNC get_linux_version_code (void)
Function Documentation
get_linux_version_code()
int FAST_FUNC get_linux_version_code (void)
Definition at line 18 of file kernel_version.c.
 {
     struct utsname name;
     char *t;
     int r;
     uname(&name); /* never fails */
     t = name.release - 1;
     r = 1;
     do {
         r <<= 8;
         if (t) {
             r += atoi(++t);
             t = strchr(t, '.');
         }
     } while (r < 0x1000000);
     return r - 0x1000000;
 }
References atoi(), utsname::release, strchr(), t, and uname().
Referenced by bb_init_module(), lsmod_main(), and rmmod_main().