Fennix: Drivers/include/vm.h File Reference
vm.h File Reference
#include <types.h>
Functions
bool IsVMwareBackdoorAvailable ()
Function Documentation
IsVMwareBackdoorAvailable()
bool IsVMwareBackdoorAvailable ()
Definition at line 62 of file detect.cpp.
 {
     struct
     {
         union
         {
             uint32_t ax;
             uint32_t magic;
         };
         union
         {
             uint32_t bx;
             size_t size;
         };
         union
         {
             uint32_t cx;
             uint16_t command;
         };
         union
         {
             uint32_t dx;
             uint16_t port;
         };
         uint32_t si;
         uint32_t di;
     } cmd{};
 #define VMWARE_MAGIC 0x564D5868 /* hXMV */
 #define VMWARE_PORT 0x5658
 #define CMD_GETVERSION 0xA
     cmd.bx = ~VMWARE_MAGIC;
     cmd.command = CMD_GETVERSION;
     cmd.magic = VMWARE_MAGIC;
     cmd.port = VMWARE_PORT;
     asmv("in %%dx, %0"
          : "+a"(cmd.ax),
            "+b"(cmd.bx),
            "+c"(cmd.cx),
            "+d"(cmd.dx),
            "+S"(cmd.si),
            "+D"(cmd.di));
     if (cmd.bx != VMWARE_MAGIC || cmd.ax == 0xFFFFFFFF)
         return false;
     debug("VMware backdoor version: %d.%d.%d",
           cmd.ax >> 16,
           (cmd.ax >> 8) & 0xFF,
           cmd.ax & 0xFF);
     return true;
 }
References __CheckHypervisorBit(), __VMwareBackdoorHypervisors(), asmv(), cmd, CMD_GETVERSION, debug, port, size, VMWARE_MAGIC, and VMWARE_PORT.
Referenced by DriverProbe(), and IsVirtualizedEnvironment().