Fennix: Recovery Namespace Reference
Recovery Namespace Reference
Data Structures
class KernelRecovery
Functions
void PlayAudio ()
void PlayAudioWrapper ()
void ChangeSampleRate (char SR)
void CSR8000 ()
void CSR11025 ()
void CSR16000 ()
void CSR22050 ()
void CSR32000 ()
void CSR44100 ()
void CSR48000 ()
void CSR88200 ()
void CSR96000 ()
void ChangeVolume (int percentage)
void CV0 ()
void CV10 ()
void CV20 ()
void CV30 ()
void CV40 ()
void CV50 ()
void CV60 ()
void CV70 ()
void CV80 ()
void CV90 ()
void CV100 ()
void BufBight10 ()
void BufBight20 ()
void BufBight30 ()
void BufBight40 ()
void BufBight50 ()
void BufBight60 ()
void BufBight70 ()
void BufBight80 ()
void BufBight90 ()
void BufBight100 ()
void RecoveryThreadWrapper ()
void RebootCommandThread ()
void ShutdownCommandThread ()
void RebootCommandWrapper ()
void ShutdownCommandWrapper ()
void GUIWrapper ()
Variables
WidgetCollection * wdgDbgWin = nullptr
Window * DbgWin = nullptr
char * AudioFile = (char *)"/home/default/Music/pcm/FurElise48000.pcm"
GraphicalUserInterface::GUI * gui = nullptr
Function Documentation
BufBight10()
void Recovery::BufBight10 ()
Definition at line 158 of file RecoveryMain.cpp.
 { Display->SetBrightness(10, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight100()
void Recovery::BufBight100 ()
Definition at line 167 of file RecoveryMain.cpp.
 { Display->SetBrightness(100, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight20()
void Recovery::BufBight20 ()
Definition at line 159 of file RecoveryMain.cpp.
 { Display->SetBrightness(20, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight30()
void Recovery::BufBight30 ()
Definition at line 160 of file RecoveryMain.cpp.
 { Display->SetBrightness(30, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight40()
void Recovery::BufBight40 ()
Definition at line 161 of file RecoveryMain.cpp.
 { Display->SetBrightness(40, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight50()
void Recovery::BufBight50 ()
Definition at line 162 of file RecoveryMain.cpp.
 { Display->SetBrightness(50, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight60()
void Recovery::BufBight60 ()
Definition at line 163 of file RecoveryMain.cpp.
 { Display->SetBrightness(60, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight70()
void Recovery::BufBight70 ()
Definition at line 164 of file RecoveryMain.cpp.
 { Display->SetBrightness(70, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight80()
void Recovery::BufBight80 ()
Definition at line 165 of file RecoveryMain.cpp.
 { Display->SetBrightness(80, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
BufBight90()
void Recovery::BufBight90 ()
Definition at line 166 of file RecoveryMain.cpp.
 { Display->SetBrightness(90, 200); }
References Display.
Referenced by Recovery::KernelRecovery::RecoveryThread().
ChangeSampleRate()
void Recovery::ChangeSampleRate (char SR)
Definition at line 80 of file RecoveryMain.cpp.
     {
         Driver::DriverFile *AudioDrv = nullptr;
         foreach (auto Driver in DriverManager->GetDrivers())
         {
             if (((FexExtended *)((uintptr_t)Driver->Address + EXTENDED_SECTION_ADDRESS))->Driver.Type == FexDriverType::FexDriverType_Audio)
             {
                 AudioDrv = Driver;
                 break;
             }
         }
         if (AudioDrv == nullptr)
         {
             error("No audio drivers found! Cannot play audio!");
             return;
         }
         KernelCallback callback;
         memset(&callback, 0, sizeof(KernelCallback));
         callback.Reason = AdjustReason;
         callback.AudioCallback.Adjust._SampleRate = true;
         callback.AudioCallback.Adjust.SampleRate = SR;
         int status = DriverManager->IOCB(AudioDrv->DriverUID, (void *)&callback);
         debug("Sample rate changed! %d", status);
     }
References AdjustReason, callback(), debug, Driver, DriverManager, error, EXTENDED_SECTION_ADDRESS, FexDriverType_Audio, Driver::Driver::GetDrivers(), Driver::Driver::IOCB(), memset, and mlibc::status.
Referenced by CSR11025(), CSR16000(), CSR22050(), CSR32000(), CSR44100(), CSR48000(), CSR8000(), CSR88200(), and CSR96000().
ChangeVolume()
void Recovery::ChangeVolume (int percentage)
Definition at line 118 of file RecoveryMain.cpp.
     {
         Driver::DriverFile *AudioDrv = nullptr;
         foreach (auto Driver in DriverManager->GetDrivers())
         {
             if (((FexExtended *)((uintptr_t)Driver->Address + EXTENDED_SECTION_ADDRESS))->Driver.Type == FexDriverType::FexDriverType_Audio)
             {
                 AudioDrv = Driver;
                 break;
             }
         }
         if (AudioDrv == nullptr)
         {
             error("No audio drivers found! Cannot play audio!");
             return;
         }
         KernelCallback callback;
         memset(&callback, 0, sizeof(KernelCallback));
         callback.Reason = AdjustReason;
         callback.AudioCallback.Adjust._Volume = true;
         callback.AudioCallback.Adjust.Volume = percentage;
         int status = DriverManager->IOCB(AudioDrv->DriverUID, (void *)&callback);
         debug("Volume changed! %d", status);
     }
References AdjustReason, callback(), debug, Driver, DriverManager, error, EXTENDED_SECTION_ADDRESS, FexDriverType_Audio, Driver::Driver::GetDrivers(), Driver::Driver::IOCB(), memset, and mlibc::status.
Referenced by CV0(), CV10(), CV100(), CV20(), CV30(), CV40(), CV50(), CV60(), CV70(), CV80(), and CV90().
CSR11025()
void Recovery::CSR11025 ()
Definition at line 109 of file RecoveryMain.cpp.
 { ChangeSampleRate(1); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR16000()
void Recovery::CSR16000 ()
Definition at line 110 of file RecoveryMain.cpp.
 { ChangeSampleRate(2); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR22050()
void Recovery::CSR22050 ()
Definition at line 111 of file RecoveryMain.cpp.
 { ChangeSampleRate(3); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR32000()
void Recovery::CSR32000 ()
Definition at line 112 of file RecoveryMain.cpp.
 { ChangeSampleRate(4); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR44100()
void Recovery::CSR44100 ()
Definition at line 113 of file RecoveryMain.cpp.
 { ChangeSampleRate(5); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR48000()
void Recovery::CSR48000 ()
Definition at line 114 of file RecoveryMain.cpp.
 { ChangeSampleRate(6); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR8000()
void Recovery::CSR8000 ()
Definition at line 108 of file RecoveryMain.cpp.
 { ChangeSampleRate(0); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR88200()
void Recovery::CSR88200 ()
Definition at line 115 of file RecoveryMain.cpp.
 { ChangeSampleRate(7); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CSR96000()
void Recovery::CSR96000 ()
Definition at line 116 of file RecoveryMain.cpp.
 { ChangeSampleRate(8); }
References ChangeSampleRate().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV0()
void Recovery::CV0 ()
Definition at line 146 of file RecoveryMain.cpp.
 { ChangeVolume(0); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV10()
void Recovery::CV10 ()
Definition at line 147 of file RecoveryMain.cpp.
 { ChangeVolume(10); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV100()
void Recovery::CV100 ()
Definition at line 156 of file RecoveryMain.cpp.
 { ChangeVolume(100); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV20()
void Recovery::CV20 ()
Definition at line 148 of file RecoveryMain.cpp.
 { ChangeVolume(20); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV30()
void Recovery::CV30 ()
Definition at line 149 of file RecoveryMain.cpp.
 { ChangeVolume(30); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV40()
void Recovery::CV40 ()
Definition at line 150 of file RecoveryMain.cpp.
 { ChangeVolume(40); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV50()
void Recovery::CV50 ()
Definition at line 151 of file RecoveryMain.cpp.
 { ChangeVolume(50); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV60()
void Recovery::CV60 ()
Definition at line 152 of file RecoveryMain.cpp.
 { ChangeVolume(60); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV70()
void Recovery::CV70 ()
Definition at line 153 of file RecoveryMain.cpp.
 { ChangeVolume(70); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV80()
void Recovery::CV80 ()
Definition at line 154 of file RecoveryMain.cpp.
 { ChangeVolume(80); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
CV90()
void Recovery::CV90 ()
Definition at line 155 of file RecoveryMain.cpp.
 { ChangeVolume(90); }
References ChangeVolume().
Referenced by Recovery::KernelRecovery::RecoveryThread().
GUIWrapper()
void Recovery::GUIWrapper ()
Definition at line 304 of file RecoveryMain.cpp.
 { gui->Loop(); }
References gui, and GraphicalUserInterface::GUI::Loop().
Referenced by Recovery::KernelRecovery::KernelRecovery().
PlayAudio()
void Recovery::PlayAudio ()
Definition at line 35 of file RecoveryMain.cpp.
     {
         SmartLock(PlayAudioLock);
         Driver::DriverFile *AudioDrv = nullptr;
         foreach (auto Driver in DriverManager->GetDrivers())
         {
             if (((FexExtended *)((uintptr_t)Driver->Address + EXTENDED_SECTION_ADDRESS))->Driver.Type == FexDriverType::FexDriverType_Audio)
             {
                 AudioDrv = Driver;
                 break;
             }
         }
         if (AudioDrv == nullptr)
         {
             error("No audio drivers found! Cannot play audio!");
             return;
         }
         std::shared_ptr<VirtualFileSystem::File> pcm = vfs->Open(AudioFile);
         if (pcm->Status != FileStatus::OK)
         {
             error("Cannot open audio file! Cannot play audio!");
             return;
         }
         void *PCMRaw = KernelAllocator.RequestPages(TO_PAGES(pcm->node->Length));
         memcpy(PCMRaw, (void *)pcm->node->Address, pcm->node->Length);
         KernelCallback callback;
         memset(&callback, 0, sizeof(KernelCallback));
         callback.Reason = SendReason;
         callback.AudioCallback.Send.Data = (uint8_t *)PCMRaw;
         callback.AudioCallback.Send.Length = pcm->node->Length;
         debug("Playing audio...");
         int status = DriverManager->IOCB(AudioDrv->DriverUID, (void *)&callback);
         debug("Audio played! %d", status);
         KernelAllocator.FreePages((void *)PCMRaw, TO_PAGES(pcm->node->Length));
         vfs->Close(pcm);
     }
References AudioFile, callback(), VirtualFileSystem::Virtual::Close(), debug, Driver, DriverManager, error, EXTENDED_SECTION_ADDRESS, FexDriverType_Audio, Driver::Driver::GetDrivers(), Driver::Driver::IOCB(), KernelAllocator, memcpy, memset, OK, VirtualFileSystem::Virtual::Open(), SendReason, mlibc::status, TO_PAGES, and vfs.
Referenced by PlayAudioWrapper().
PlayAudioWrapper()
void Recovery::PlayAudioWrapper ()
Definition at line 78 of file RecoveryMain.cpp.
 { TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (IP)PlayAudio)->SetPriority(Tasking::TaskPriority::Idle); }
References Tasking::Task::CreateThread(), Tasking::Task::GetCurrentProcess(), APIC::Idle, PlayAudio(), Tasking::TCB::SetPriority(), and TaskManager.
Referenced by Recovery::KernelRecovery::RecoveryThread().
RebootCommandThread()
void Recovery::RebootCommandThread ()
Definition at line 288 of file RecoveryMain.cpp.
     {
         CriticalSection cs;
         PowerManager->Reboot();
     }
References PowerManager, and Power::Power::Reboot().
Referenced by RebootCommandWrapper().
RebootCommandWrapper()
void Recovery::RebootCommandWrapper ()
Definition at line 300 of file RecoveryMain.cpp.
 { TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (IP)RebootCommandThread); }
References Tasking::Task::CreateThread(), Tasking::Task::GetCurrentProcess(), RebootCommandThread(), and TaskManager.
Referenced by Recovery::KernelRecovery::KernelRecovery().
RecoveryThreadWrapper()
void Recovery::RecoveryThreadWrapper ()
Definition at line 281 of file RecoveryMain.cpp.
     {
         while (!RecoveryScreen)
             CPU::Pause();
         RecoveryScreen->RecoveryThread();
     }
References CPU::Pause(), RecoveryScreen, and Recovery::KernelRecovery::RecoveryThread().
Referenced by Recovery::KernelRecovery::KernelRecovery().
ShutdownCommandThread()
void Recovery::ShutdownCommandThread ()
Definition at line 294 of file RecoveryMain.cpp.
     {
         CriticalSection cs;
         PowerManager->Shutdown();
     }
References PowerManager, and Power::Power::Shutdown().
Referenced by ShutdownCommandWrapper().
ShutdownCommandWrapper()
void Recovery::ShutdownCommandWrapper ()
Definition at line 301 of file RecoveryMain.cpp.
 { TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (IP)ShutdownCommandThread); }
References Tasking::Task::CreateThread(), Tasking::Task::GetCurrentProcess(), ShutdownCommandThread(), and TaskManager.
Referenced by Recovery::KernelRecovery::KernelRecovery().
Variable Documentation
AudioFile
char* Recovery::AudioFile = (char *)"/home/default/Music/pcm/FurElise48000.pcm"
Definition at line 33 of file RecoveryMain.cpp.
Referenced by PlayAudio(), and Recovery::KernelRecovery::RecoveryThread().
DbgWin
Window* Recovery::DbgWin = nullptr
Definition at line 31 of file RecoveryMain.cpp.
Referenced by Recovery::KernelRecovery::KernelRecovery(), and Recovery::KernelRecovery::RecoveryThread().
gui
GraphicalUserInterface::GUI* Recovery::gui = nullptr
Definition at line 303 of file RecoveryMain.cpp.
Referenced by GUIWrapper(), Recovery::KernelRecovery::KernelRecovery(), and Recovery::KernelRecovery::~KernelRecovery().
wdgDbgWin
WidgetCollection* Recovery::wdgDbgWin = nullptr
Definition at line 30 of file RecoveryMain.cpp.
Referenced by Recovery::KernelRecovery::KernelRecovery(), and Recovery::KernelRecovery::RecoveryThread().