Fennix Userspace: Userspace/musl/src/thread/pthread_atfork.c File Reference
pthread_atfork.c File Reference
#include <pthread.h>
#include <errno.h>
#include "libc.h"
#include "lock.h"
Data Structures
struct atfork_funcs
Macros
#define malloc __libc_malloc
#define calloc undef
#define realloc undef
#define free undef
Functions
void __fork_handler (int who)
int pthread_atfork (void(*prepare)(void), void(*parent)(void), void(*child)(void))
Variables
static struct atfork_funcs * funcs
static volatile int lock [1]
Macro Definition Documentation
calloc
#define calloc undef
Definition at line 7 of file pthread_atfork.c.
free
#define free undef
Definition at line 9 of file pthread_atfork.c.
malloc
#define malloc __libc_malloc
Definition at line 6 of file pthread_atfork.c.
realloc
#define realloc undef
Definition at line 8 of file pthread_atfork.c.
Function Documentation
__fork_handler()
void __fork_handler (int who)
Definition at line 20 of file pthread_atfork.c.
 {
     struct atfork_funcs *p;
     if (!funcs) return;
     if (who < 0) {
         LOCK(lock);
         for (p=funcs; p; p = p->next) {
             if (p->prepare) p->prepare();
             funcs = p;
         }
     } else {
         for (p=funcs; p; p = p->prev) {
             if (!who && p->parent) p->parent();
             else if (who && p->child) p->child();
             funcs = p;
         }
         UNLOCK(lock);
     }
 }
References funcs, LOCK, lock, p, and UNLOCK.
Referenced by fork().
pthread_atfork()
int pthread_atfork (void(*)(void) prepare, void(*)(void) parent, void(*)(void) child)
Definition at line 40 of file pthread_atfork.c.
 {
     struct atfork_funcs *new = malloc(sizeof *new);
     if (!new) return ENOMEM;
     LOCK(lock);
     new->next = funcs;
     new->prev = 0;
     new->prepare = prepare;
     new->parent = parent;
     new->child = child;
     if (funcs) funcs->prev = new;
     funcs = new;
     UNLOCK(lock);
     return 0;
 }
References child(), ENOMEM, funcs, LOCK, lock, malloc, atfork_funcs::parent, prepare(), atfork_funcs::prepare, atfork_funcs::prev, and UNLOCK.
Referenced by main().
Variable Documentation
funcs
struct atfork_funcs * funcs static
Referenced by __fork_handler(), and pthread_atfork().
lock
volatile int lock[1] static
Definition at line 18 of file pthread_atfork.c.
Referenced by __fork_handler(), and pthread_atfork().