Fennix: Userspace/mlibc/tests/posix/sigtimedwait.c File Reference
sigtimedwait.c File Reference
#include <stdio.h>
#include <assert.h>
#include <signal.h>
#include <unistd.h>
#include <sys/wait.h>
#include <errno.h>
Functions
void parent_fn ()
void child_fn ()
int main ()
Variables
pid_t parent
pid_t child
int fds [2]
Function Documentation
child_fn()
void child_fn ()
Definition at line 59 of file sigtimedwait.c.
                 {
     int res;
     char c;
     res = read(fds[0], &c, 1);
     assert(res == 1);
     kill(parent, SIGUSR2);
     res = read(fds[0], &c, 1);
     assert(res == 1);
     kill(parent, SIGUSR2);
     res = read(fds[0], &c, 1);
     assert(res == 1);
     kill(parent, SIGUSR2);
     res = read(fds[0], &c, 1);
     assert(res == 1);
 }
References assert, c, fds, kill(), parent, read(), and SIGUSR2.
Referenced by main().
main()
int main (void)
Definition at line 76 of file sigtimedwait.c.
            {
     int res;
     parent = getpid();
     assert(parent > 0);
     res = pipe(fds);
     assert(res == 0);
     child = fork();
     assert(child >= 0);
     if (child)
         parent_fn();
     else
         child_fn();
 }
References assert, child, child_fn(), fds, fork(), getpid(), parent, parent_fn(), and pipe().
parent_fn()
void parent_fn ()
Definition at line 14 of file sigtimedwait.c.
                  {
     int res;
     sigset_t set;
     sigemptyset(&set);
     sigaddset(&set, SIGUSR2);
     sigprocmask(SIG_BLOCK, &set, NULL);
     res = write(fds[1], "!", 1);
     assert(res == 1);
     siginfo_t info;
     res = sigwaitinfo(&set, &info);
     assert(res == SIGUSR2);
     assert(info.si_signo == SIGUSR2);
     res = write(fds[1], "!", 1);
     assert(res == 1);
     // XXX: This may not be long enough to get scheduled
     struct timespec tout = {1, 0};
     res = sigtimedwait(&set, &info, &tout);
     assert(res == SIGUSR2);
     assert(info.si_signo == SIGUSR2);
     res = write(fds[1], "!", 1);
     assert(res == 1);
     int sig;
     res = sigwait(&set, &sig);
     assert(res == 0);
     assert(sig == SIGUSR2);
     res = write(fds[1], "!", 1);
     assert(res == 1);
     res = sigtimedwait(&set, &info, &tout);
     assert(res < 0);
     assert(errno == EAGAIN);
     int wsts;
     res = waitpid(child, &wsts, 0);
     assert(res >= 0);
 }
References assert, child, EAGAIN, errno, fds, info, NULL, SIG_BLOCK, sigaddset(), sigemptyset(), sigprocmask(), sigtimedwait(), SIGUSR2, sigwait(), sigwaitinfo(), waitpid(), and write().
Referenced by main().
Variable Documentation
child
pid_t child
Definition at line 10 of file sigtimedwait.c.
Referenced by fork(), forkpty(), main(), parent_fn(), popen(), pthread_atfork(), mlibc::sys_fork(), mlibc::sys_inotify_create(), system(), and vfork().
fds
int fds[2]
Definition at line 12 of file sigtimedwait.c.
Referenced by child_fn(), mlibc::for(), mlibc::if(), main(), parent_fn(), pipe(), pipe2(), poll(), popen(), ppoll(), mlibc::sys_pipe(), mlibc::sys_poll(), mlibc::sys_ppoll(), and mlibc::sys_socketpair().
parent
pid_t parent
Definition at line 9 of file sigtimedwait.c.
Referenced by child_fn(), main(), and pthread_atfork().