Fennix Kernel: Kernel/kernel.h File Reference
kernel.h File Reference
#include <types.h>
#include <boot/binfo.h>
Functions
EXTERNC void putchar (char c)
EXTERNC void KPrint (const char *format,...)
EXTERNC void Entry (struct BootInfo *Info)
EXTERNC void BeforeShutdown (bool Reboot)
EXTERNC void TaskingPanic ()
EXTERNC void BootLogoAnimationThread ()
EXTERNC void ExitLogoAnimationThread ()
EXTERNC void KernelMainThread ()
EXTERNC void KernelShutdownThread (bool Reboot)
EXTERNC void KST_Reboot ()
EXTERNC void KST_Shutdown ()
Variables
struct BootInfo bInfo
struct KernelConfig Config
bool DebuggerIsAttached
Function Documentation
BeforeShutdown()
EXTERNC void BeforeShutdown (bool Reboot)
Definition at line 467 of file kernel.cpp.
 {
     /* TODO: Announce shutdown */
     trace("\n\n\n#################### SYSTEM SHUTTING DOWN ####################\n\n");
     KPrint("%s...", Reboot ? "Rebooting" : "Shutting down");
     if (NIManager)
         delete NIManager, NIManager = nullptr;
     if (DiskManager)
         delete DiskManager, DiskManager = nullptr;
     if (ModuleManager)
         delete ModuleManager, ModuleManager = nullptr;
     if (TaskManager && !TaskManager->IsPanic())
     {
         TaskManager->SignalShutdown();
         delete TaskManager, TaskManager = nullptr;
     }
     if (fs)
         delete fs, fs = nullptr;
     if (TimeManager)
         delete TimeManager, TimeManager = nullptr;
     // if (Display)
     //  delete Display, Display = nullptr;
     // PowerManager should not be called
     // https://wiki.osdev.org/Calling_Global_Constructors
     debug("Calling destructors...");
     for (CallPtr *func = __fini_array_start; func != __fini_array_end; func++)
         (*func)();
     __cxa_finalize(nullptr);
     debug("Done.");
 }
References __cxa_finalize(), __fini_array_end, __fini_array_start, debug, DiskManager, fs, Tasking::Task::IsPanic(), KPrint(), ModuleManager, NIManager, Tasking::Task::SignalShutdown(), TaskManager, TimeManager, and trace.
Referenced by KernelShutdownThread().
BootLogoAnimationThread()
EXTERNC void BootLogoAnimationThread ()
Definition at line 47 of file boot_logo.cpp.
 {
     char BootAnimPath[16];
     while (FrameCount < 27)
     {
         sprintf(BootAnimPath, "/etc/boot/%ld.tga", FrameCount);
         RefNode *frame = fs->Open(BootAnimPath);
         if (!frame)
         {
             debug("Failed to load boot animation frame %s", BootAnimPath);
             break;
         }
         FrameSizes[FrameCount] = s_cst(uint32_t, frame->Size);
         Frames[FrameCount] = new uint8_t[frame->Size];
         frame->read(Frames[FrameCount], frame->Size);
         delete frame;
         FrameCount++;
     }
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = 1; i < FrameCount; i++)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i],
                                    &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i],
                                              FrameSizes[i], &x, &y,
                                              &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY,
                               (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
         TaskManager->Sleep(50);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
         TaskManager->Sleep(5);
     }
 }
References debug, Display, FrameCount, Frames, FrameSizes, free(), fs, Video::Display::GetBuffer(), Video::ScreenBuffer::Height, NULL, vfs::Virtual::Open(), vfs::RefNode::read(), Video::Display::SetBrightness(), Video::Display::SetBuffer(), Video::Display::SetPixel(), vfs::RefNode::Size, Tasking::Task::Sleep(), sprintf(), stbi_info_from_memory(), stbi_load_from_memory(), STBI_rgb_alpha, TaskManager, and Video::ScreenBuffer::Width.
Referenced by KernelMainThread().
Entry()
EXTERNC void Entry (struct BootInfo * Info)
Definition at line 358 of file kernel.cpp.
 {
     trace("Hello, World!");
     if (strcmp(CPU::Hypervisor(), x86_CPUID_VENDOR_TCG) == 0)
     {
         debug("\n\n----------------------------------------\nDEBUGGER DETECTED\n----------------------------------------\n\n");
         DebuggerIsAttached = true;
     }
     memcpy(&bInfo, Info, sizeof(BootInfo));
     debug("BootInfo structure is at %p", &bInfo);
     // https://wiki.osdev.org/Calling_Global_Constructors
     trace("There are %d constructors to call",
           __init_array_end - __init_array_start);
     for (CallPtr *func = __init_array_start; func != __init_array_end; func++)
         (*func)();
 #ifdef a86
     if (!bInfo.SMBIOSPtr)
     {
         trace("SMBIOS was not provided by the bootloader. Trying to find it manually.");
         for (uintptr_t i = 0xF0000; i < 0x100000; i += 16)
         {
             if (memcmp((void *)i, "_SM_", 4) == 0 ||
                 memcmp((void *)i, "_SM3_", 5) == 0)
             {
                 bInfo.SMBIOSPtr = (void *)i;
                 trace("Found SMBIOS at %#lx", i);
             }
         }
     }
     if (!bInfo.RSDP)
     {
         trace("RSDP was not provided by the bootloader. Trying to find it manually.");
         /* FIXME: Not always shifting by 4 will work. */
         uintptr_t EBDABase = (uintptr_t)mminw((void *)0x40E) << 4;
         for (uintptr_t ptr = EBDABase;
              ptr < 0x100000; /* 1MB */
              ptr += 16)
         {
             if (unlikely(ptr == EBDABase + 0x400))
             {
                 trace("EBDA is full. Trying to find RSDP in the BIOS area.");
                 break;
             }
             BootInfo::RSDPInfo *rsdp = (BootInfo::RSDPInfo *)ptr;
             if (memcmp(rsdp->Signature, "RSD PTR ", 8) == 0)
             {
                 bInfo.RSDP = (BootInfo::RSDPInfo *)rsdp;
                 trace("Found RSDP at %#lx", rsdp);
             }
         }
         for (uintptr_t ptr = 0xE0000;
              ptr < 0x100000; /* 1MB */
              ptr += 16)
         {
             BootInfo::RSDPInfo *rsdp = (BootInfo::RSDPInfo *)ptr;
             if (memcmp(rsdp->Signature, "RSD PTR ", 8) == 0)
             {
                 bInfo.RSDP = (BootInfo::RSDPInfo *)rsdp;
                 trace("Found RSDP at %#lx", rsdp);
             }
         }
     }
 #endif
     InitializeMemoryManagement();
     void *KernelStackAddress = KernelAllocator.RequestPages(TO_PAGES(STACK_SIZE));
     uintptr_t KernelStack = (uintptr_t)KernelStackAddress + STACK_SIZE - 0x10;
     debug("Kernel stack: %#lx-%#lx", KernelStackAddress, KernelStack);
 #if defined(a64)
     asmv("mov %0, %%rsp"
          :
          : "r"(KernelStack)
          : "memory");
     asmv("mov $0, %rbp");
 #elif defined(a32)
     asmv("mov %0, %%esp"
          :
          : "r"(KernelStack)
          : "memory");
     asmv("mov $0, %ebp");
 #elif defined(aa64)
 #warning "Kernel stack is not set!"
 #endif
 #ifdef DEBUG
     /* I had to do this because KernelAllocator
      * is a global constructor but we need
      * memory management to be initialized first.
      */
     TestMemoryAllocation();
     TestString();
     Test_std();
 #endif
     EnableProfiler = true;
     Main();
 }
References __init_array_end, __init_array_start, asmv(), bInfo, debug, DebuggerIsAttached, EnableProfiler, CPU::Hypervisor(), Info, InitializeMemoryManagement(), KernelAllocator, Main(), memcmp(), memcpy(), BootInfo::RSDPInfo::Signature, BootInfo::SMBIOSPtr, STACK_SIZE, strcmp(), TO_PAGES, trace, unlikely, and x86_CPUID_VENDOR_TCG.
Referenced by InitLimineAfterStack(), multiboot2_parse(), multiboot_parse(), and APIC::APIC::RawRedirectIRQ().
ExitLogoAnimationThread()
EXTERNC void ExitLogoAnimationThread ()
Definition at line 122 of file boot_logo.cpp.
 {
     Display->SetBrightness(100, 1);
     Display->SetBuffer(1);
     /* Files: 26.tga 25.tga ... 1.tga */
     uint32_t DispX = Display->GetBuffer(1)->Width;
     uint32_t DispY = Display->GetBuffer(1)->Height;
     for (size_t i = FrameCount - 1; i > 0; i--)
     {
         int x, y, channels;
         if (!stbi_info_from_memory((uint8_t *)Frames[i], FrameSizes[i],
                                    &x, &y, &channels))
             continue;
         uint8_t *img = stbi_load_from_memory((uint8_t *)Frames[i],
                                              FrameSizes[i], &x, &y,
                                              &channels, STBI_rgb_alpha);
         if (img == NULL)
             continue;
         int offsetX = DispX / 2 - x / 2;
         int offsetY = DispY / 2 - y / 2;
         for (int i = 0; i < x * y; i++)
         {
             uint32_t pixel = ((uint32_t *)img)[i];
             int r = (pixel >> 16) & 0xFF;
             int g = (pixel >> 8) & 0xFF;
             int b = (pixel >> 0) & 0xFF;
             int a = (pixel >> 24) & 0xFF;
             if (a != 0xFF)
             {
                 r = (r * a) / 0xFF;
                 g = (g * a) / 0xFF;
                 b = (b * a) / 0xFF;
             }
             Display->SetPixel((i % x) + offsetX, (i / x) + offsetY,
                               (r << 16) | (g << 8) | (b << 0), 1);
         }
         free(img);
         Display->SetBuffer(1);
         TaskManager->Sleep(50);
     }
     int brightness = 100;
     while (brightness >= 0)
     {
         brightness -= 10;
         Display->SetBrightness(brightness, 1);
         Display->SetBuffer(1);
         TaskManager->Sleep(5);
     }
 }
References Display, FrameCount, Frames, FrameSizes, free(), Video::Display::GetBuffer(), Video::ScreenBuffer::Height, NULL, Video::Display::SetBrightness(), Video::Display::SetBuffer(), Video::Display::SetPixel(), Tasking::Task::Sleep(), stbi_info_from_memory(), stbi_load_from_memory(), STBI_rgb_alpha, TaskManager, and Video::ScreenBuffer::Width.
Referenced by KernelShutdownThread().
KernelMainThread()
EXTERNC void KernelMainThread ()
Definition at line 69 of file kernel_thread.cpp.
 {
     Tasking::TCB *clnThd =
         TaskManager->CreateThread(thisProcess,
                                   Tasking::IP(CleanupProcessesThreadWrapper));
     clnThd->SetPriority(Tasking::Idle);
     TaskManager->SetCleanupThread(clnThd);
     thisThread->SetPriority(Tasking::Critical);
     Tasking::TCB *blaThread = nullptr;
     if (Config.BootAnimation)
     {
         blaThread =
             TaskManager->CreateThread(thisProcess,
                                       Tasking::IP(BootLogoAnimationThread));
         blaThread->Rename("Logo Animation");
     }
 #ifdef DEBUG
     // TaskManager->CreateThread(thisProcess, Tasking::IP(tasking_test_fb));
     // TaskManager->CreateThread(thisProcess, Tasking::IP(tasking_test_mutex));
     // ilp;
     TaskManager->CreateThread(thisProcess, Tasking::IP(TaskMgr));
     TaskManager->CreateThread(thisProcess, Tasking::IP(lsof));
     TreeFS(fs->GetRootNode(), 0);
 #endif
     KPrint("Kernel Compiled at: %s %s with C++ Standard: %d",
            __DATE__, __TIME__, CPP_LANGUAGE_STANDARD);
     KPrint("C++ Language Version (__cplusplus): %ld", __cplusplus);
     if (IsVirtualizedEnvironment())
         KPrint("Running in a virtualized environment");
     KPrint("Initializing Disk Manager...");
     DiskManager = new Disk::Manager;
     KPrint("Loading Modules...");
     ModuleManager = new Module::Module;
     ModuleManager->LoadModules();
     KPrint("Fetching Disks...");
     if (ModuleManager->GetModules().size() > 0)
     {
         foreach (auto mod in ModuleManager->GetModules())
             if (((FexExtended *)mod.ExtendedHeaderAddress)->Module.Type == FexModuleType::FexModuleType_Storage)
                 DiskManager->FetchDisks(mod.modUniqueID);
     }
     else
         KPrint("\eE85230No disk modules found! Cannot fetch disks!");
     KPrint("Initializing Network Interface Manager...");
     NIManager = new NetworkInterfaceManager::NetworkInterface;
     KPrint("Starting Network Interface Manager...");
     NIManager->StartService();
     KPrint("Setting up userspace");
     int ExitCode = -1;
     Tasking::TCB *initThread = nullptr;
     int tid = SpawnInit();
     if (tid < 0)
     {
         KPrint("\eE85230Failed to start %s! Code: %d", Config.InitPath, tid);
         goto Exit;
     }
     KPrint("Waiting for \e22AAFF%s\eCCCCCC to start...", Config.InitPath);
     thisThread->SetPriority(Tasking::Idle);
     initThread = TaskManager->GetThreadByID(tid);
     initThread->KeepInMemory = true;
     TaskManager->WaitForThread(initThread);
     ExitCode = initThread->GetExitCode();
 Exit:
     if (ExitCode == 0)
     {
         KPrint("\eFF7900%s process exited with code %d and it didn't invoked the shutdown function.",
                Config.InitPath, ExitCode);
         KPrint("System Halted");
         CPU::Halt(true);
     }
     KPrint("\eE85230Userspace process exited with code %d (%#x)",
            ExitCode, ExitCode < 0 ? -ExitCode : ExitCode);
     KPrint("Dropping to kernel shell...");
     TaskManager->Sleep(1000);
     TaskManager->WaitForThread(blaThread);
     TaskManager->CreateThread(thisProcess,
                               Tasking::IP(KShellThread))
         ->Rename("Kernel Shell");
     if (initThread)
         initThread->KeepInMemory = false;
     CPU::Halt(true);
 }
References BootLogoAnimationThread(), CleanupProcessesThreadWrapper(), Tasking::Task::CreateThread(), Tasking::Critical, DiskManager, Disk::Manager::FetchDisks(), FexModuleType_Storage, fs, Tasking::TCB::GetExitCode(), Module::Module::GetModules(), vfs::Virtual::GetRootNode(), Tasking::Task::GetThreadByID(), Halt(), Tasking::Idle, IsVirtualizedEnvironment(), Tasking::TCB::KeepInMemory, KPrint(), KShellThread(), Module::Module::LoadModules(), Module, ModuleManager, NIManager, Tasking::TCB::Rename(), Tasking::Task::SetCleanupThread(), Tasking::TCB::SetPriority(), Tasking::Task::Sleep(), SpawnInit(), NetworkInterfaceManager::NetworkInterface::StartService(), TaskManager, thisProcess, thisThread, and Tasking::Task::WaitForThread().
Referenced by Main().
KernelShutdownThread()
EXTERNC void KernelShutdownThread (bool Reboot)
Definition at line 168 of file kernel_thread.cpp.
 {
     SmartLock(ShutdownLock);
     debug("KernelShutdownThread(%s)", Reboot ? "true" : "false");
     if (Config.BootAnimation && TaskManager)
     {
         Tasking::TCB *elaThread =
             TaskManager->CreateThread(thisProcess,
                                       Tasking::IP(ExitLogoAnimationThread));
         elaThread->Rename("Logo Animation");
         TaskManager->WaitForThread(elaThread);
     }
     BeforeShutdown(Reboot);
     trace("%s...", Reboot ? "Rebooting" : "Shutting down");
     if (Reboot)
         PowerManager->Reboot();
     else
         PowerManager->Shutdown();
     CPU::Stop();
 }
References BeforeShutdown(), Tasking::Task::CreateThread(), debug, ExitLogoAnimationThread(), PowerManager, Power::Power::Reboot(), Tasking::TCB::Rename(), Power::Power::Shutdown(), TaskManager, thisProcess, trace, and Tasking::Task::WaitForThread().
Referenced by cmd_exit(), cmd_reboot(), cmd_shutdown(), KST_Reboot(), and KST_Shutdown().
KPrint()
EXTERNC void KPrint (const char * format, ...)
Definition at line 81 of file kernel.cpp.
 {
     SmartLock(KernelLock);
     if (TimeManager)
     {
         uint64_t Nanoseconds = TimeManager->GetNanosecondsSinceClassCreation();
         if (Nanoseconds != 0)
         {
 #if defined(a64)
             printf("\eCCCCCC[\e00AEFF%lu.%07lu\eCCCCCC] ",
                    Nanoseconds / 10000000, Nanoseconds % 10000000);
 #elif defined(a32)
             printf("\eCCCCCC[\e00AEFF%llu.%07llu\eCCCCCC] ",
                    Nanoseconds / 10000000, Nanoseconds % 10000000);
 #elif defined(aa64)
             printf("\eCCCCCC[\e00AEFF%lu.%07lu\eCCCCCC] ",
                    Nanoseconds / 10000000, Nanoseconds % 10000000);
 #endif
         }
     }
     va_list args;
     va_start(args, Format);
     vprintf(Format, args);
     va_end(args);
     printf("\eCCCCCC\n");
     if (!Config.BootAnimation && Display)
         Display->SetBuffer(0);
 }
References KernelConfig::BootAnimation, Config, Display, Time::time::GetNanosecondsSinceClassCreation(), Time::Nanoseconds, printf, Video::Display::SetBuffer(), TimeManager, va_end, va_start, and vprintf().
Referenced by __chk_fail(), __stack_chk_fail(), BeforeShutdown(), Time::time::FindTimers(), InterruptDescriptorTable::Init(), Interrupts::Initialize(), CPU::InitializeFeatures(), KernelMainThread(), Module::Module::LoadModules(), ACPI::MADT::MADT(), Main(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), ParseConfig(), Memory::Physical::RequestPage(), Memory::Physical::RequestPages(), StartCPU(), Tasking::Task::Task(), and APIC::Timer::Timer().
KST_Reboot()
EXTERNC void KST_Reboot ()
Definition at line 191 of file kernel_thread.cpp.
 { KernelShutdownThread(true); }
References KernelShutdownThread().
KST_Shutdown()
EXTERNC void KST_Shutdown ()
Definition at line 192 of file kernel_thread.cpp.
 { KernelShutdownThread(false); }
References KernelShutdownThread().
putchar()
EXTERNC void putchar (char c)
Definition at line 73 of file kernel.cpp.
 {
     if (Display)
         Display->Print(c, PutCharBufferIndex);
     else
         UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write(c);
 }
TaskingPanic()
EXTERNC void TaskingPanic ()
Definition at line 509 of file kernel.cpp.
 {
     if (TaskManager)
         TaskManager->Panic();
 }
References Tasking::Task::Panic(), and TaskManager.
Referenced by __chk_fail(), and __stack_chk_fail().
Variable Documentation
bInfo
struct BootInfo bInfo extern
Referenced by Memory::__no_sanitize(), ACPI::ACPI::ACPI(), SMBIOS::CheckSMBIOS(), Entry(), SMBIOS::GetSMBIOSEntryPoint(), Memory::Physical::Init(), InitializeMemoryManagement(), Main(), MapFramebuffer(), MapFromZero(), and MapKernel().
Config
struct KernelConfig Config extern
Definition at line 43 of file kernel.cpp.
Referenced by KPrint(), and Main().
DebuggerIsAttached
bool DebuggerIsAttached extern
Definition at line 36 of file kernel.cpp.
Referenced by __stack_chk_fail(), Module::Module::CallModuleEntryPoint(), Entry(), InterruptDescriptorTable::Init(), and Main().