Fennix: LimitedPrinter Struct Reference
LimitedPrinter Struct Reference
Public Member Functions
LimitedPrinter (char *buffer, size_t limit)
void append (char c)
void append (const char *str)
void append (const char *str, size_t n)
Data Fields
char * buffer
size_t limit
size_t count
Detailed Description
Definition at line 143 of file stdio-stubs.cpp.
Constructor & Destructor Documentation
LimitedPrinter()
LimitedPrinter::LimitedPrinter (char * buffer, size_t limit) inline
Definition at line 144 of file stdio-stubs.cpp.
     : buffer(buffer), limit(limit), count(0) { }
Member Function Documentation
append() [1/3]
void LimitedPrinter::append (char c) inline
Definition at line 147 of file stdio-stubs.cpp.
{
         if(count < limit)
             buffer[count] = c;
         count++;
     }
References buffer, c, count, and limit.
Referenced by append().
append() [2/3]
void LimitedPrinter::append (const char * str) inline
Definition at line 153 of file stdio-stubs.cpp.
{
         // TODO: use strcat
         for(size_t i = 0; str[i]; i++)
             append(str[i]);
     }
References append(), and i.
append() [3/3]
void LimitedPrinter::append (const char * str, size_t n) inline
Definition at line 159 of file stdio-stubs.cpp.
{
         // TODO: use strcat
         for(size_t i = 0; i < n; i++)
             append(str[i]);
     }
References append(), i, and n.
Field Documentation
buffer
char* LimitedPrinter::buffer
Definition at line 165 of file stdio-stubs.cpp.
Referenced by append().
count
size_t LimitedPrinter::count
Definition at line 167 of file stdio-stubs.cpp.
Referenced by append().
limit
size_t LimitedPrinter::limit
Definition at line 166 of file stdio-stubs.cpp.
Referenced by append().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/ansi/generic/stdio-stubs.cpp