Fennix Userspace: Userspace/mlibc/sysdeps/lyre/generic/mntent.cpp File Reference
mntent.cpp File Reference
#include <errno.h>
#include <mntent.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>
#include <bits/ensure.h>
Namespaces
anonymous_namespace{mntent.cpp}
Macros
#define SENTINEL (char *)&internal_buf
Functions
FILE * setmntent (const char *name, const char *mode)
struct mntent * getmntent (FILE *f)
int addmntent (FILE *f, const struct mntent *mnt)
int endmntent (FILE *f)
char * hasmntopt (const struct mntent *mnt, const char *opt)
struct mntent * getmntent_r (FILE *f, struct mntent *mnt, char *linebuf, int buflen)
Variables
char * anonymous_namespace{mntent.cpp}::internal_buf
size_t anonymous_namespace{mntent.cpp}::internal_bufsize
Macro Definition Documentation
SENTINEL
#define SENTINEL (char *)&internal_buf
Definition at line 15 of file mntent.cpp.
Function Documentation
addmntent()
int addmntent (FILE * f, const struct mntent * mnt)
Definition at line 26 of file mntent.cpp.
{
     if(fseek(f, 0, SEEK_END)) {
         return 1;
     }
     return fprintf(f, "%s\t%s\t%s\t%s\t%d\t%d\n",
         mnt->mnt_fsname, mnt->mnt_dir, mnt->mnt_type, mnt->mnt_opts,
         mnt->mnt_freq, mnt->mnt_passno) < 0;
 }
References fprintf(), fseek(), mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, and SEEK_END.
endmntent()
int endmntent (FILE * f)
Definition at line 35 of file mntent.cpp.
{
     if(f) {
         fclose(f);
     }
     return 1;
 }
References fclose().
getmntent()
struct mntent* getmntent (FILE * f)
Definition at line 21 of file mntent.cpp.
{
     static struct mntent mnt;
     return getmntent_r(f, &mnt, SENTINEL, 0);
 }
References getmntent_r(), and SENTINEL.
getmntent_r()
struct mntent* getmntent_r (FILE * f, struct mntent * mnt, char * linebuf, int buflen)
Definition at line 47 of file mntent.cpp.
{
     int n[8];
     bool use_internal = (linebuf == SENTINEL);
     int len;
     size_t i;
     mnt->mnt_freq = 0;
     mnt->mnt_passno = 0;
     do {
         if(use_internal) {
             getline(&internal_buf, &internal_bufsize, f);
             linebuf = internal_buf;
         } else {
             fgets(linebuf, buflen, f);
         }
         if(feof(f) || ferror(f)) {
             return 0;
         }
         if(!strchr(linebuf, '\n')) {
             fscanf(f, "%*[^\n]%*[\n]");
             errno = ERANGE;
             return 0;
         }
         len = strlen(linebuf);
         if(len > INT_MAX) {
             continue;
         }
         for(i = 0; i < sizeof n / sizeof *n; i++) {
             n[i] = len;
         }
         sscanf(linebuf, " %n%*s%n %n%*s%n %n%*s%n %n%*s%n %d %d",
             n, n + 1, n + 2, n + 3, n + 4, n + 5, n + 6, n + 7,
             &mnt->mnt_freq, &mnt->mnt_passno);
     } while(linebuf[n[0]] == '#' || n[1] == len);
     linebuf[n[1]] = 0;
     linebuf[n[3]] = 0;
     linebuf[n[5]] = 0;
     linebuf[n[7]] = 0;
     mnt->mnt_fsname = linebuf + n[0];
     mnt->mnt_dir = linebuf + n[2];
     mnt->mnt_type = linebuf + n[4];
     mnt->mnt_opts = linebuf + n[6];
     return mnt;
 }
References ERANGE, errno, feof(), ferror(), fgets(), fscanf(), getline(), i, INT_MAX, anonymous_namespace{mntent.cpp}::internal_buf, anonymous_namespace{mntent.cpp}::internal_bufsize, mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, n, SENTINEL, sscanf(), strchr(), and strlen().
Referenced by getmntent().
hasmntopt()
char* hasmntopt (const struct mntent * mnt, const char * opt)
Definition at line 42 of file mntent.cpp.
{
     return strstr(mnt->mnt_opts, opt);
 }
References mntent::mnt_opts, and strstr().
setmntent()
FILE* setmntent (const char * name, const char * mode)
Definition at line 17 of file mntent.cpp.
{
     return fopen(name, mode);
 }
References fopen(), and name.