Fennix: Userspace/musl/include/sys/epoll.h File Reference
epoll.h File Reference
#include <stdint.h>
#include <sys/types.h>
#include <fcntl.h>
#include <bits/alltypes.h>
Data Structures
union epoll_data
struct epoll_event
Macros
#define __NEED_sigset_t
#define EPOLL_CLOEXEC O_CLOEXEC
#define EPOLL_NONBLOCK O_NONBLOCK
#define EPOLLIN 0x001
#define EPOLLPRI 0x002
#define EPOLLOUT 0x004
#define EPOLLRDNORM 0x040
#define EPOLLNVAL 0x020
#define EPOLLRDBAND 0x080
#define EPOLLWRNORM 0x100
#define EPOLLWRBAND 0x200
#define EPOLLMSG 0x400
#define EPOLLERR 0x008
#define EPOLLHUP 0x010
#define EPOLLRDHUP 0x2000
#define EPOLLEXCLUSIVE (1U<<28)
#define EPOLLWAKEUP (1U<<29)
#define EPOLLONESHOT (1U<<30)
#define EPOLLET (1U<<31)
#define EPOLL_CTL_ADD 1
#define EPOLL_CTL_DEL 2
#define EPOLL_CTL_MOD 3
Typedefs
typedef union epoll_data epoll_data_t
Enumerations
enum EPOLL_EVENTS { __EPOLL_DUMMY }
Functions
int epoll_create (int)
int epoll_create1 (int)
int epoll_ctl (int, int, int, struct epoll_event *)
int epoll_wait (int, struct epoll_event *, int, int)
int epoll_pwait (int, struct epoll_event *, int, int, const sigset_t *)
Data Structure Documentation
epoll_data
union epoll_data
Definition at line 41 of file epoll.h.
Data Fields
int fd
void * ptr
uint32_t u32
uint64_t u64
epoll_event
struct epoll_event
Definition at line 48 of file epoll.h.
Data Fields
epoll_data_t data
uint32_t events
Macro Definition Documentation
__NEED_sigset_t
#define __NEED_sigset_t
Definition at line 12 of file epoll.h.
EPOLL_CLOEXEC
#define EPOLL_CLOEXEC O_CLOEXEC
Definition at line 16 of file epoll.h.
EPOLL_CTL_ADD
#define EPOLL_CTL_ADD 1
Definition at line 37 of file epoll.h.
EPOLL_CTL_DEL
#define EPOLL_CTL_DEL 2
Definition at line 38 of file epoll.h.
EPOLL_CTL_MOD
#define EPOLL_CTL_MOD 3
Definition at line 39 of file epoll.h.
EPOLL_NONBLOCK
#define EPOLL_NONBLOCK O_NONBLOCK
Definition at line 17 of file epoll.h.
EPOLLERR
#define EPOLLERR 0x008
Definition at line 29 of file epoll.h.
EPOLLET
#define EPOLLET (1U<<31)
Definition at line 35 of file epoll.h.
EPOLLEXCLUSIVE
#define EPOLLEXCLUSIVE (1U<<28)
Definition at line 32 of file epoll.h.
EPOLLHUP
#define EPOLLHUP 0x010
Definition at line 30 of file epoll.h.
EPOLLIN
#define EPOLLIN 0x001
Definition at line 20 of file epoll.h.
EPOLLMSG
#define EPOLLMSG 0x400
Definition at line 28 of file epoll.h.
EPOLLNVAL
#define EPOLLNVAL 0x020
Definition at line 24 of file epoll.h.
EPOLLONESHOT
#define EPOLLONESHOT (1U<<30)
Definition at line 34 of file epoll.h.
EPOLLOUT
#define EPOLLOUT 0x004
Definition at line 22 of file epoll.h.
EPOLLPRI
#define EPOLLPRI 0x002
Definition at line 21 of file epoll.h.
EPOLLRDBAND
#define EPOLLRDBAND 0x080
Definition at line 25 of file epoll.h.
EPOLLRDHUP
#define EPOLLRDHUP 0x2000
Definition at line 31 of file epoll.h.
EPOLLRDNORM
#define EPOLLRDNORM 0x040
Definition at line 23 of file epoll.h.
EPOLLWAKEUP
#define EPOLLWAKEUP (1U<<29)
Definition at line 33 of file epoll.h.
EPOLLWRBAND
#define EPOLLWRBAND 0x200
Definition at line 27 of file epoll.h.
EPOLLWRNORM
#define EPOLLWRNORM 0x100
Definition at line 26 of file epoll.h.
Typedef Documentation
epoll_data_t
typedef union epoll_data epoll_data_t
Enumeration Type Documentation
EPOLL_EVENTS
enum EPOLL_EVENTS
Enumerator
__EPOLL_DUMMY
Definition at line 19 of file epoll.h.
 { __EPOLL_DUMMY };
Function Documentation
epoll_create()
int epoll_create (int size)
Definition at line 6 of file epoll.c.
 {
     if (size<=0) return __syscall_ret(-EINVAL);
     return epoll_create1(0);
 }
References __syscall_ret(), EINVAL, epoll_create1(), and size.
epoll_create1()
int epoll_create1 (int flags)
Definition at line 12 of file epoll.c.
 {
     int r = __syscall(SYS_epoll_create1, flags);
 #ifdef SYS_epoll_create
     if (r==-ENOSYS && !flags) r = __syscall(SYS_epoll_create, 1);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ENOSYS, and flags.
Referenced by epoll_create().
epoll_ctl()
int epoll_ctl (int fd, int op, int fd2, struct epoll_event * ev)
Definition at line 21 of file epoll.c.
 {
     return syscall(SYS_epoll_ctl, fd, op, fd2, ev);
 }
References fd, and syscall().
epoll_pwait()
int epoll_pwait (int fd, struct epoll_event * ev, int cnt, int to, const sigset_t * sigs)
Definition at line 26 of file epoll.c.
 {
     int r = __syscall_cp(SYS_epoll_pwait, fd, ev, cnt, to, sigs, _NSIG/8);
 #ifdef SYS_epoll_wait
     if (r==-ENOSYS && !sigs) r = __syscall_cp(SYS_epoll_wait, fd, ev, cnt, to);
 #endif
     return __syscall_ret(r);
 }
References __syscall_cp, __syscall_ret(), _NSIG, cnt, ENOSYS, and fd.
Referenced by epoll_wait().
epoll_wait()
int epoll_wait (int fd, struct epoll_event * ev, int cnt, int to)
Definition at line 35 of file epoll.c.
 {
     return epoll_pwait(fd, ev, cnt, to, 0);
 }
References cnt, epoll_pwait(), and fd.