Fennix: Userspace/apps/base/bash/examples/loadables/necho.c File Reference
necho.c File Reference
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
Functions
int necho_builtin (WORD_LIST *list)
Variables
char * necho_doc []
struct builtin necho_struct
Function Documentation
necho_builtin()
int necho_builtin (WORD_LIST * list)
Definition at line 29 of file necho.c.
 {
     print_word_list (list, " ");
     printf("\n");
     fflush (stdout);
     return (EXECUTION_SUCCESS);
 }
References EXECUTION_SUCCESS, fflush(), list(), print_word_list(), printf, and stdout.
Variable Documentation
necho_doc
char* necho_doc[]
Initial value:
= {
    "Display arguments.",
    "",
    "Print the arguments to the standard output separated",
    "by space characters and terminated with a newline.",
    (char *)NULL
}
Definition at line 38 of file necho.c.
necho_struct
struct builtin necho_struct
Initial value:
= {
    "echo",
    necho_builtin,
    BUILTIN_ENABLED,
    necho_doc,
    "echo [args]",
    0
}
Definition at line 38 of file necho.c.