Fennix: Userspace/musl/src/thread/pthread_join.c File Reference
pthread_join.c File Reference
#include "pthread_impl.h"
#include <sys/mman.h>
Macros
#define _GNU_SOURCE
Functions
static void dummy1 (pthread_t t)
weak_alias (dummy1, __tl_sync)
static int __pthread_timedjoin_np (pthread_t t, void **res, const struct timespec *at)
int __pthread_join (pthread_t t, void **res)
static int __pthread_tryjoin_np (pthread_t t, void **res)
weak_alias (__pthread_tryjoin_np, pthread_tryjoin_np)
weak_alias (__pthread_timedjoin_np, pthread_timedjoin_np)
weak_alias (__pthread_join, pthread_join)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file pthread_join.c.
Function Documentation
__pthread_join()
int __pthread_join (pthread_t t, void ** res)
Definition at line 28 of file pthread_join.c.
 {
     return __pthread_timedjoin_np(t, res, 0);
 }
References __pthread_timedjoin_np(), and t.
Referenced by __pthread_detach(), __pthread_tryjoin_np(), and thrd_join().
__pthread_timedjoin_np()
static int __pthread_timedjoin_np (pthread_t t, void ** res, const struct timespec * at) static
Definition at line 10 of file pthread_join.c.
 {
     int state, cs, r = 0;
     __pthread_testcancel();
     __pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (cs == PTHREAD_CANCEL_ENABLE) __pthread_setcancelstate(cs, 0);
     while ((state = t->detach_state) && r != ETIMEDOUT && r != EINVAL) {
         if (state >= DT_DETACHED) a_crash();
         r = __timedwait_cp(&t->detach_state, state, CLOCK_REALTIME, at, 1);
     }
     __pthread_setcancelstate(cs, 0);
     if (r == ETIMEDOUT || r == EINVAL) return r;
     __tl_sync(t);
     if (res) *res = t->result;
     if (t->map_base) __munmap(t->map_base, t->map_size);
     return 0;
 }
References __munmap(), __pthread_setcancelstate(), __pthread_testcancel(), __timedwait_cp(), __tl_sync(), a_crash, CLOCK_REALTIME, DT_DETACHED, EINVAL, ETIMEDOUT, PTHREAD_CANCEL_DISABLE, PTHREAD_CANCEL_ENABLE, state, and t.
Referenced by __pthread_join().
__pthread_tryjoin_np()
static int __pthread_tryjoin_np (pthread_t t, void ** res) static
Definition at line 33 of file pthread_join.c.
 {
     return t->detach_state==DT_JOINABLE ? EBUSY : __pthread_join(t, res);
 }
References __pthread_join(), DT_JOINABLE, EBUSY, and t.
dummy1()
static void dummy1 (pthread_t t) static
Definition at line 5 of file pthread_join.c.
 {
 }
weak_alias() [1/4]
weak_alias (__pthread_join , pthread_join)
weak_alias() [2/4]
weak_alias (__pthread_timedjoin_np , pthread_timedjoin_np)
weak_alias() [3/4]
weak_alias (__pthread_tryjoin_np , pthread_tryjoin_np)
weak_alias() [4/4]
weak_alias (dummy1 , __tl_sync)