Fennix: Userspace/apps/base/busybox/miscutils/crond.c File Reference
crond.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <syslog.h>
Data Structures
struct CronFile
struct CronLine
struct globals
Macros
#define SETENV_LEAKS 1
#define CRON_DIR CONFIG_FEATURE_CROND_DIR
#define CRONTABS CONFIG_FEATURE_CROND_DIR "/crontabs"
#define CRON_REBOOT CONFIG_PID_FILE_PATH "/crond.reboot"
#define SENDMAIL "sendmail"
#define SENDMAIL_ARGS "-ti"
#define CRONUPDATE "cron.update"
#define MAXLINES 256 /* max lines in non-root crontabs */
#define START_ME_REBOOT -2
#define START_ME_NORMAL -1
#define DAEMON_UID 0
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define process_finished_job(user, line) ((line)->cl_pid = 0)
Typedefs
typedef struct CronFile CronFile
typedef struct CronLine CronLine
Enumerations
enum {
OPT_l = (1 << 0) , OPT_L = (1 << 1) , OPT_f = (1 << 2) , OPT_b = (1 << 3) ,
OPT_S = (1 << 4) , OPT_c = (1 << 5) , OPT_d = (1 << 6) * ENABLE_FEATURE_CROND_D
}
Functions
static void crondlog (unsigned level, const char *msg, va_list va)
static void log5 (const char *msg,...)
static void log7 (const char *msg,...)
static void log8 (const char *msg,...)
static void ParseField (char *user, char *ary, int modvalue, int off, const char *names, char *ptr)
static void FixDayDow (CronLine *line)
static void delete_cronfile (const char *userName)
static void load_crontab (const char *fileName)
static void process_cron_update_file (void)
static void rescan_crontab_dir (void)
static void safe_setenv (char **pvar_val, const char *var, const char *val)
static void set_env_vars (struct passwd *pas, const char *shell, const char *path)
static void change_user (struct passwd *pas)
static pid_t start_one_job (const char *user, CronLine *line)
static void flag_starting_jobs (time_t t1, time_t t2)
static void start_jobs (int wants_start)
static int check_completions (void)
static void reopen_logfile_to_stderr (void)
int crond_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
static const char DowAry[] ALIGN1
Data Structure Documentation
CronFile
struct CronFile
Definition at line 108 of file crond.c.
Data Fields
smallint cf_deleted
smallint cf_has_running
struct CronLine * cf_lines
struct CronFile * cf_next
char * cf_username
smallint cf_wants_starting
CronLine
struct CronLine
Definition at line 117 of file crond.c.
Data Fields
char * cl_cmd
char cl_Days[32]
char cl_Dow[7]
char cl_Hrs[24]
char cl_Mins[60]
char cl_Mons[12]
struct CronLine * cl_next
char * cl_path
pid_t cl_pid
char * cl_shell
Macro Definition Documentation
CRON_DIR
#define CRON_DIR CONFIG_FEATURE_CROND_DIR
Definition at line 91 of file crond.c.
CRON_REBOOT
#define CRON_REBOOT CONFIG_PID_FILE_PATH "/crond.reboot"
Definition at line 93 of file crond.c.
CRONTABS
#define CRONTABS CONFIG_FEATURE_CROND_DIR "/crontabs"
Definition at line 92 of file crond.c.
CRONUPDATE
#define CRONUPDATE "cron.update"
Definition at line 101 of file crond.c.
DAEMON_UID
#define DAEMON_UID 0
Definition at line 138 of file crond.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 165 of file crond.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    G.log_level = 8; \
    G.crontab_dir_name = CRONTABS; \
} while (0)
Definition at line 166 of file crond.c.
MAXLINES
#define MAXLINES 256 /* max lines in non-root crontabs */
Definition at line 104 of file crond.c.
process_finished_job
#define process_finished_job (user, line) ((line)->cl_pid = 0)
Definition at line 880 of file crond.c.
SENDMAIL
#define SENDMAIL "sendmail"
Definition at line 95 of file crond.c.
SENDMAIL_ARGS
#define SENDMAIL_ARGS "-ti"
Definition at line 98 of file crond.c.
SETENV_LEAKS
#define SETENV_LEAKS 1
Definition at line 87 of file crond.c.
START_ME_NORMAL
#define START_ME_NORMAL -1
Definition at line 122 of file crond.c.
START_ME_REBOOT
#define START_ME_REBOOT -2
Definition at line 121 of file crond.c.
Typedef Documentation
CronFile
typedef struct CronFile CronFile
CronLine
typedef struct CronLine CronLine
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_l
OPT_L
OPT_f
OPT_b
OPT_S
OPT_c
OPT_d
Definition at line 141 of file crond.c.
      {
     OPT_l = (1 << 0),
     OPT_L = (1 << 1),
     OPT_f = (1 << 2),
     OPT_b = (1 << 3),
     OPT_S = (1 << 4),
     OPT_c = (1 << 5),
     OPT_d = (1 << 6) * ENABLE_FEATURE_CROND_D,
 };
Function Documentation
change_user()
static void change_user (struct passwd * pas) static
Definition at line 683 of file crond.c.
 {
     /* careful: we're after vfork! */
     change_identity(pas); /* - initgroups, setgid, setuid */
     if (chdir_or_warn(pas->pw_dir) != 0) {
         xchdir(CRON_DIR);
     }
 }
References change_identity(), chdir_or_warn(), CRON_DIR, passwd::pw_dir, and xchdir().
Referenced by start_one_job().
check_completions()
static int check_completions (void) static
Definition at line 975 of file crond.c.
 {
     CronFile *file;
     CronLine *line;
     int num_still_running = 0;
     for (file = G.cron_files; file; file = file->cf_next) {
         if (!file->cf_has_running)
             continue;
         file->cf_has_running = 0;
         for (line = file->cf_lines; line; line = line->cl_next) {
             int r;
             if (line->cl_pid <= 0)
                 continue;
             r = waitpid(line->cl_pid, NULL, WNOHANG);
             if (r < 0 || r == line->cl_pid) {
                 process_finished_job(file->cf_username, line);
                 if (line->cl_pid == 0) {
                     /* sendmail was not started for it */
                     continue;
                 }
                 /* else: sendmail was started, job is still running, fall thru */
             }
             /* else: r == 0: "process is still running" */
             file->cf_has_running = 1;
         }
 //FIXME: if !file->cf_has_running && file->deleted: delete it!
 //otherwise deleted entries will stay forever, right?
         num_still_running += file->cf_has_running;
     }
     return num_still_running;
 }
References G, line, NULL, process_finished_job, waitpid(), and WNOHANG.
Referenced by crond_main().
crond_main()
int crond_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1021 of file crond.c.
 {
     time_t t2;
     unsigned rescan;
     unsigned sleep_time;
     unsigned opts;
     INIT_G();
     opts = getopt32(argv, "^"
             "l:L:fbSc:" IF_FEATURE_CROND_D("d:")
             "\0"
             /* "-b after -f is ignored", and so on for every pair a-b */
             "f-b:b-f:S-L:L-S" IF_FEATURE_CROND_D(":d-l")
             /* -l and -d have numeric param */
             ":l+" IF_FEATURE_CROND_D(":d+")
             ,
             &G.log_level, &G.log_filename, &G.crontab_dir_name
             IF_FEATURE_CROND_D(,&G.log_level)
     );
     /* both -d N and -l N set the same variable: G.log_level */
     if (!(opts & OPT_f)) {
         /* close stdin, stdout, stderr.
          * close unused descriptors - don't need them. */
         bb_daemonize_or_rexec(DAEMON_CLOSE_EXTRA_FDS, argv);
     }
     if (!(opts & OPT_d) && G.log_filename == NULL) {
         /* logging to syslog */
         openlog(applet_name, LOG_CONS | LOG_PID, LOG_CRON);
         logmode = LOGMODE_SYSLOG;
     }
     //signal(SIGHUP, SIG_IGN); /* ? original crond dies on HUP... */
     reopen_logfile_to_stderr();
     xchdir(G.crontab_dir_name);
     /* $SHELL, or current UID's shell, or DEFAULT_SHELL */
     /* Useful on Android where DEFAULT_SHELL /bin/sh may not exist */
     G.default_shell = xstrdup(get_shell_name());
     log8("crond (busybox "BB_VER") started, log level %d", G.log_level);
     rescan_crontab_dir();
     write_pidfile_std_path_and_ext("crond");
 #if ENABLE_FEATURE_CROND_SPECIAL_TIMES
     if (touch_reboot_file())
         start_jobs(START_ME_REBOOT); /* start @reboot entries, if any */
 #endif
     /* Main loop */
     t2 = time(NULL);
     rescan = 60;
     sleep_time = 60;
     for (;;) {
         struct stat sbuf;
         time_t t1;
         long dt;
         /* Synchronize to 1 minute, minimum 1 second */
         t1 = t2;
         sleep(sleep_time - (time(NULL) % sleep_time));
         t2 = time(NULL);
         dt = (long)t2 - (long)t1;
         reopen_logfile_to_stderr();
         /*
          * The file 'cron.update' is checked to determine new cron
          * jobs.  The directory is rescanned once an hour to deal
          * with any screwups.
          *
          * Check for time jump.  Disparities over an hour either way
          * result in resynchronization.  A negative disparity
          * less than an hour causes us to effectively sleep until we
          * match the original time (i.e. no re-execution of jobs that
          * have just been run).  A positive disparity less than
          * an hour causes intermediate jobs to be run, but only once
          * in the worst case.
          *
          * When running jobs, the inequality used is greater but not
          * equal to t1, and less then or equal to t2.
          */
         if (stat(G.crontab_dir_name, &sbuf) != 0)
             sbuf.st_mtime = 0; /* force update (once) if dir was deleted */
         if (G.crontab_dir_mtime != sbuf.st_mtime) {
             G.crontab_dir_mtime = sbuf.st_mtime;
             rescan = 1;
         }
         if (--rescan == 0) {
             rescan = 60;
             rescan_crontab_dir();
         }
         process_cron_update_file();
         log5("wakeup dt=%ld", dt);
         if (dt < -60 * 60 || dt > 60 * 60) {
             bb_info_msg("time disparity of %ld minutes detected", dt / 60);
             /* and we do not run any jobs in this case */
         } else if (dt > 0) {
             /* Usual case: time advances forward, as expected */
             flag_starting_jobs(t1, t2);
             start_jobs(START_ME_NORMAL);
             sleep_time = 60;
             if (check_completions() > 0) {
                 /* some jobs are still running */
                 sleep_time = 10;
             }
         }
         /* else: time jumped back, do not run any jobs */
     } /* for (;;) */
     return 0; /* not reached */
 }
References applet_name, argv, bb_daemonize_or_rexec, bb_info_msg, check_completions(), DAEMON_CLOSE_EXTRA_FDS, flag_starting_jobs(), G, get_shell_name(), getopt32(), INIT_G, log5(), log8(), LOG_CONS, LOG_CRON, LOG_PID, logmode, LOGMODE_SYSLOG, NULL, openlog(), OPT_d, OPT_f, process_cron_update_file(), reopen_logfile_to_stderr(), rescan_crontab_dir(), sleep(), stat::st_mtime, start_jobs(), START_ME_NORMAL, START_ME_REBOOT, stat(), t1, t2, time(), write_pidfile_std_path_and_ext(), xchdir(), and xstrdup().
crondlog()
static void crondlog (unsigned level, const char * msg, va_list va) static
Definition at line 176 of file crond.c.
 {
     if (level >= G.log_level) {
         /*
          * We are called only for info meesages.
          * Warnings/errors use plain bb_[p]error_msg's, which
          * need not touch syslog_level
          * (they are ok with LOG_ERR default).
          */
         bb_vinfo_msg(msg, va);
     }
 }
References bb_vinfo_msg, and G.
Referenced by log5(), log7(), and log8().
delete_cronfile()
static void delete_cronfile (const char * userName) static
Definition at line 381 of file crond.c.
 {
     CronFile **pfile = &G.cron_files;
     CronFile *file;
     while ((file = *pfile) != NULL) {
         if (strcmp(userName, file->cf_username) == 0) {
             CronLine **pline = &file->cf_lines;
             CronLine *line;
             file->cf_has_running = 0;
             file->cf_deleted = 1;
             while ((line = *pline) != NULL) {
                 if (line->cl_pid > 0) {
                     file->cf_has_running = 1;
                     pline = &line->cl_next;
                 } else {
                     *pline = line->cl_next;
                     free(line->cl_cmd);
                     free(line);
                 }
             }
             if (file->cf_has_running == 0) {
                 *pfile = file->cf_next;
                 free(file->cf_username);
                 free(file);
                 continue;
             }
         }
         pfile = &file->cf_next;
     }
 }
References free, G, line, NULL, and strcmp.
Referenced by load_crontab(), and rescan_crontab_dir().
FixDayDow()
static void FixDayDow (CronLine * line) static
Definition at line 336 of file crond.c.
 {
     unsigned i;
     int weekUsed = 0;
     int daysUsed = 0;
     for (i = 0; i < ARRAY_SIZE(line->cl_Dow); ++i) {
         if (line->cl_Dow[i] == 0) {
             weekUsed = 1;
             break;
         }
     }
     for (i = 0; i < ARRAY_SIZE(line->cl_Days); ++i) {
         if (line->cl_Days[i] == 0) {
             daysUsed = 1;
             break;
         }
     }
     if (weekUsed != daysUsed) {
         if (weekUsed)
             memset(line->cl_Days, 0, sizeof(line->cl_Days));
         else /* daysUsed */
             memset(line->cl_Dow, 0, sizeof(line->cl_Dow));
     }
 }
References ARRAY_SIZE, i, and memset.
Referenced by load_crontab().
flag_starting_jobs()
static void flag_starting_jobs (time_t t1, time_t t2) static
Definition at line 889 of file crond.c.
 {
     time_t t;
     /* Find jobs > t1 and <= t2 */
     for (t = t1 - t1 % 60; t <= t2; t += 60) {
         struct tm *ptm;
         CronFile *file;
         CronLine *line;
         if (t <= t1)
             continue;
         ptm = localtime(&t);
         for (file = G.cron_files; file; file = file->cf_next) {
             log5("file %s:", file->cf_username);
             if (file->cf_deleted)
                 continue;
             for (line = file->cf_lines; line; line = line->cl_next) {
                 log5(" line %s", line->cl_cmd);
                 if (line->cl_Mins[ptm->tm_min]
                  && line->cl_Hrs[ptm->tm_hour]
                  && (line->cl_Days[ptm->tm_mday] || line->cl_Dow[ptm->tm_wday])
                  && line->cl_Mons[ptm->tm_mon]
                 ) {
                     log5(" job: %d %s",
                             (int)line->cl_pid, line->cl_cmd);
                     if (line->cl_pid > 0) {
                         log8("user %s: process already running: %s",
                             file->cf_username, line->cl_cmd);
                     } else if (line->cl_pid == 0) {
                         line->cl_pid = START_ME_NORMAL;
                         file->cf_wants_starting = 1;
                     }
                 }
             }
         }
     }
 }
References G, line, localtime(), log5(), log8(), START_ME_NORMAL, t, t1, t2, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, and tm::tm_wday.
Referenced by crond_main().
load_crontab()
static void load_crontab (const char * fileName) static
Definition at line 415 of file crond.c.
 {
     struct parser_t *parser;
     struct stat sbuf;
     int maxLines;
     char *tokens[6];
 #if ENABLE_FEATURE_CROND_CALL_SENDMAIL
     char *mailTo = NULL;
 #endif
     char *shell = NULL;
     char *path = NULL;
     delete_cronfile(fileName);
     if (!getpwnam(fileName)) {
         log7("ignoring file '%s' (no such user)", fileName);
         return;
     }
     parser = config_open(fileName);
     if (!parser)
         return;
     maxLines = (strcmp(fileName, "root") == 0) ? 65535 : MAXLINES;
     if (fstat(fileno(parser->fp), &sbuf) == 0 && sbuf.st_uid == DAEMON_UID) {
         CronFile *file = xzalloc(sizeof(CronFile));
         CronLine **pline;
         int n;
         file->cf_username = xstrdup(fileName);
         pline = &file->cf_lines;
         while (1) {
             CronLine *line;
             if (!--maxLines) {
                 bb_error_msg("user %s: too many lines", fileName);
                 break;
             }
             n = config_read(parser, tokens, 6, 1, "# \t", PARSE_NORMAL | PARSE_KEEP_COPY);
             if (!n)
                 break;
             log5("user:%s entry:%s", fileName, parser->data);
             /* check if line is setting MAILTO= */
             if (is_prefixed_with(tokens[0], "MAILTO=")) {
 #if ENABLE_FEATURE_CROND_CALL_SENDMAIL
                 free(mailTo);
                 mailTo = (tokens[0][7]) ? xstrdup(&tokens[0][7]) : NULL;
 #endif /* otherwise just ignore such lines */
                 continue;
             }
             if (is_prefixed_with(tokens[0], "SHELL=")) {
                 free(shell);
                 shell = xstrdup(&tokens[0][6]);
                 continue;
             }
             if (is_prefixed_with(tokens[0], "PATH=")) {
                 free(path);
                 path = xstrdup(&tokens[0][5]);
                 continue;
             }
 //TODO: handle HOME= too? Better yet, handle arbitrary ENVVARs? "man crontab" says:
 //name = value
 //
 //where the spaces around the equal-sign (=) are optional, and any subsequent
 //non-leading spaces in value will be part of the value assigned to name.
 //The value string may be placed in quotes (single or double, but matching)
 //to preserve leading or trailing blanks.
 //
 //Several environment variables are set up automatically by the cron(8) daemon.
 //SHELL is set to /bin/sh, and LOGNAME and HOME are set from the /etc/passwd
 //line of the crontab's owner.  HOME, SHELL, and PATH may be overridden by
 //settings in the crontab; LOGNAME may not.
 #if ENABLE_FEATURE_CROND_SPECIAL_TIMES
             if (tokens[0][0] == '@') {
                 /*
                  * "@daily /a/script/to/run PARAM1 PARAM2..."
                  */
                 typedef struct SpecialEntry {
                     const char *name;
                     const char tokens[8];
                 } SpecialEntry;
                 static const SpecialEntry SpecAry[] ALIGN8 = {
                     /*              hour  day   month weekday */
                     { "yearly",     "0\0" "1\0" "1\0" "*" },
                     { "annually",   "0\0" "1\0" "1\0" "*" },
                     { "monthly",    "0\0" "1\0" "*\0" "*" },
                     { "weekly",     "0\0" "*\0" "*\0" "0" },
                     { "daily",      "0\0" "*\0" "*\0" "*" },
                     { "midnight",   "0\0" "*\0" "*\0" "*" },
                     { "hourly",     "*\0" "*\0" "*\0" "*" },
                     { "reboot",     ""                    },
                 };
                 const SpecialEntry *e = SpecAry;
                 if (n < 2)
                     continue;
                 for (;;) {
                     if (strcmp(e->name, tokens[0] + 1) == 0) {
                         /*
                          * tokens[1] is only the first word of command,
                          * can'r use it.
                          * find the entire command in unmodified string:
                          */
                         tokens[5] = skip_whitespace(
                             skip_non_whitespace(
                             skip_whitespace(parser->data)));
                         if (e->tokens[0]) {
                             char *et = (char*)e->tokens;
                             /* minute is "0" for all specials */
                             tokens[0] = (char*)"0";
                             tokens[1] = et;
                             tokens[2] = et + 2;
                             tokens[3] = et + 4;
                             tokens[4] = et + 6;
                         }
                         goto got_it;
                     }
                     if (!e->tokens[0])
                         break;
                     e++;
                 }
                 continue; /* bad line (unrecognized '@foo') */
             }
 #endif
             /* check if a minimum of tokens is specified */
             if (n < 6)
                 continue;
  IF_FEATURE_CROND_SPECIAL_TIMES(
   got_it:
  )
             *pline = line = xzalloc(sizeof(*line));
 #if ENABLE_FEATURE_CROND_SPECIAL_TIMES
             if (tokens[0][0] == '@') { /* "@reboot" line */
                 file->cf_wants_starting = 1;
                 line->cl_pid = START_ME_REBOOT; /* wants to start */
                 /* line->cl_Mins/Hrs/etc stay zero: never match any time */
             } else
 #endif
             {
                 /* parse date ranges */
                 ParseField(file->cf_username, line->cl_Mins, 60, 0, NULL, tokens[0]);
                 ParseField(file->cf_username, line->cl_Hrs, 24, 0, NULL, tokens[1]);
                 ParseField(file->cf_username, line->cl_Days, 32, 0, NULL, tokens[2]);
                 ParseField(file->cf_username, line->cl_Mons, 12, -1, MonAry, tokens[3]);
                 ParseField(file->cf_username, line->cl_Dow, 7, 0, DowAry, tokens[4]);
                 /*
                  * fix days and dow - if one is not "*" and the other
                  * is "*", the other is set to 0, and vise-versa
                  */
                 FixDayDow(line);
             }
 #if ENABLE_FEATURE_CROND_CALL_SENDMAIL
             /* copy mailto (can be NULL) */
             line->cl_mailto = xstrdup(mailTo);
 #endif
             line->cl_shell = xstrdup(shell);
             line->cl_path = xstrdup(path);
             /* copy command */
             line->cl_cmd = xstrdup(tokens[5]);
             pline = &line->cl_next;
 //bb_error_msg("M[%s]F[%s][%s][%s][%s][%s][%s]", mailTo, tokens[0], tokens[1], tokens[2], tokens[3], tokens[4], tokens[5]);
         }
         *pline = NULL;
         file->cf_next = G.cron_files;
         G.cron_files = file;
     }
     config_close(parser);
 #if ENABLE_FEATURE_CROND_CALL_SENDMAIL
     free(mailTo);
 #endif
     free(shell);
 }
References ALIGN8, bb_error_msg(), config_close(), config_open(), config_read, DAEMON_UID, delete_cronfile(), fileName, fileno(), FixDayDow(), free, fstat(), G, getpwnam, is_prefixed_with(), line, log5(), log7(), MAXLINES, n, NULL, PARSE_KEEP_COPY, PARSE_NORMAL, ParseField(), parser, skip_non_whitespace(), skip_whitespace(), stat::st_uid, START_ME_REBOOT, strcmp, xstrdup(), and xzalloc().
Referenced by process_cron_update_file(), and rescan_crontab_dir().
log5()
static void log5 (const char * msg, ...) static
Definition at line 189 of file crond.c.
 {
     va_list va;
     va_start(va, msg);
     crondlog(4, msg, va);
     va_end(va);
 }
References crondlog(), va_end, and va_start.
Referenced by crond_main(), flag_starting_jobs(), load_crontab(), and start_one_job().
log7()
static void log7 (const char * msg, ...) static
Definition at line 197 of file crond.c.
 {
     va_list va;
     va_start(va, msg);
     crondlog(7, msg, va);
     va_end(va);
 }
References crondlog(), va_end, and va_start.
Referenced by load_crontab().
log8()
static void log8 (const char * msg, ...) static
Definition at line 205 of file crond.c.
 {
     va_list va;
     va_start(va, msg);
     crondlog(8, msg, va);
     va_end(va);
 }
References crondlog(), va_end, and va_start.
Referenced by crond_main(), flag_starting_jobs(), and start_jobs().
ParseField()
static void ParseField (char * user, char * ary, int modvalue, int off, const char * names, char * ptr) static
Definition at line 222 of file crond.c.
 {
     char *base = ptr;
     int n1 = -1;
     int n2 = -1;
     // this can't happen due to config_read()
     /*if (base == NULL)
         return;*/
     while (1) {
         int skip = 0;
         /* Handle numeric digit or symbol or '*' */
         if (*ptr == '*') {
             n1 = 0;  /* everything will be filled */
             n2 = modvalue - 1;
             skip = 1;
             ++ptr;
         } else if (isdigit(*ptr)) {
             char *endp;
             if (n1 < 0) {
                 n1 = strtol(ptr, &endp, 10) + off;
             } else {
                 n2 = strtol(ptr, &endp, 10) + off;
             }
             ptr = endp; /* gcc likes temp var for &endp */
             skip = 1;
         } else if (names) {
             int i;
             for (i = 0; names[i]; i += 3) {
                 /* was using strncmp before... */
                 if (strncasecmp(ptr, &names[i], 3) == 0) {
                     ptr += 3;
                     if (n1 < 0) {
                         n1 = i / 3;
                     } else {
                         n2 = i / 3;
                     }
                     skip = 1;
                     break;
                 }
             }
         }
         /* handle optional range '-' */
         if (skip == 0) {
             goto err;
         }
         if (*ptr == '-' && n2 < 0) {
             ++ptr;
             continue;
         }
         /*
          * collapse single-value ranges, handle skipmark, and fill
          * in the character array appropriately.
          */
         if (n2 < 0) {
             n2 = n1;
         }
         if (*ptr == '/') {
             char *endp;
             skip = strtol(ptr + 1, &endp, 10);
             ptr = endp; /* gcc likes temp var for &endp */
         }
         /*
          * fill array, using a failsafe is the easiest way to prevent
          * an endless loop
          */
         {
             int s0 = 1;
             int failsafe = 1024;
             --n1;
             do {
                 n1 = (n1 + 1) % modvalue;
                 if (--s0 == 0) {
                     ary[n1 % modvalue] = 1;
                     s0 = skip;
                 }
                 if (--failsafe == 0) {
                     goto err;
                 }
             } while (n1 != n2);
         }
         if (*ptr != ',') {
             break;
         }
         ++ptr;
         n1 = -1;
         n2 = -1;
     }
     if (*ptr) {
  err:
         bb_error_msg("user %s: parse error at %s", user, base);
         return;
     }
     /* can't use log5 (it inserts newlines), open-coding it */
     if (G.log_level <= 5 && logmode != LOGMODE_SYSLOG) {
         int i;
         for (i = 0; i < modvalue; ++i)
             fprintf(stderr, "%d", (unsigned char)ary[i]);
         bb_putchar_stderr('\n');
     }
 }
References base, bb_error_msg(), bb_putchar_stderr(), err(), fprintf(), G, i, isdigit, logmode, LOGMODE_SYSLOG, names, off, s0, skip, stderr, strncasecmp, and strtol().
Referenced by load_crontab().
process_cron_update_file()
static void process_cron_update_file (void) static
Definition at line 595 of file crond.c.
 {
     FILE *fi;
     char buf[256];
     fi = fopen_for_read(CRONUPDATE);
     if (fi != NULL) {
         unlink(CRONUPDATE);
         while (fgets(buf, sizeof(buf), fi) != NULL) {
             /* use first word only */
             skip_non_whitespace(buf)[0] = '\0';
             load_crontab(buf);
         }
         fclose(fi);
     }
 }
References buf, CRONUPDATE, fclose(), fgets, fopen_for_read(), load_crontab(), NULL, skip_non_whitespace(), and unlink().
Referenced by crond_main().
reopen_logfile_to_stderr()
static void reopen_logfile_to_stderr (void) static
Definition at line 1011 of file crond.c.
 {
     if (G.log_filename) {
         int logfd = open_or_warn(G.log_filename, O_WRONLY | O_CREAT | O_APPEND);
         if (logfd >= 0)
             xmove_fd(logfd, STDERR_FILENO);
     }
 }
References G, O_APPEND, O_CREAT, O_WRONLY, open_or_warn(), STDERR_FILENO, and xmove_fd().
Referenced by crond_main().
rescan_crontab_dir()
static void rescan_crontab_dir (void) static
Definition at line 612 of file crond.c.
 {
     CronFile *file;
     /* Delete all files until we only have ones with running jobs (or none) */
  again:
     for (file = G.cron_files; file; file = file->cf_next) {
         if (!file->cf_deleted) {
             delete_cronfile(file->cf_username);
             goto again;
         }
     }
     /* Remove cron update file */
     unlink(CRONUPDATE);
     /* Re-chdir, in case directory was renamed & deleted */
     xchdir(G.crontab_dir_name);
     /* Scan directory and add associated users */
     {
         DIR *dir = opendir(".");
         struct dirent *den;
         /* xopendir exists, but "can't open '.'" is not informative */
         if (!dir)
             bb_error_msg_and_die("can't open '%s'", G.crontab_dir_name);
         while ((den = readdir(dir)) != NULL) {
             if (strchr(den->d_name, '.') != NULL) {
                 continue;
             }
             load_crontab(den->d_name);
         }
         closedir(dir);
     }
 }
References bb_error_msg_and_die(), closedir(), CRONUPDATE, dirent::d_name, delete_cronfile(), dir, G, load_crontab(), NULL, opendir(), readdir(), strchr(), unlink(), and xchdir().
Referenced by crond_main().
safe_setenv()
static void safe_setenv (char ** pvar_val, const char * var, const char * val) static
Definition at line 652 of file crond.c.
 {
     char *var_val = *pvar_val;
     if (var_val) {
         bb_unsetenv_and_free(var_val);
     }
     *pvar_val = xasprintf("%s=%s", var, val);
     putenv(*pvar_val);
 }
References bb_unsetenv_and_free(), putenv(), val, and xasprintf().
Referenced by set_env_vars().
set_env_vars()
static void set_env_vars (struct passwd * pas, const char * shell, const char * path) static
Definition at line 664 of file crond.c.
 {
     /* POSIX requires crond to set up at least HOME, LOGNAME, PATH, SHELL.
      */
 #if SETENV_LEAKS
     safe_setenv(&G.env_var_logname, "LOGNAME", pas->pw_name);
     safe_setenv(&G.env_var_user, "USER", pas->pw_name);
     safe_setenv(&G.env_var_home, "HOME", pas->pw_dir);
     safe_setenv(&G.env_var_shell, "SHELL", shell);
     if (path) safe_setenv(&G.env_var_shell, "PATH", path);
 #else
     xsetenv("LOGNAME", pas->pw_name);
     xsetenv("USER", pas->pw_name);
     xsetenv("HOME", pas->pw_dir);
     xsetenv("SHELL", shell);
     if (path) xsetenv("PATH", path);
 #endif
 }
References G, passwd::pw_dir, passwd::pw_name, safe_setenv(), and xsetenv().
Referenced by start_one_job().
start_jobs()
static void start_jobs (int wants_start) static
Definition at line 943 of file crond.c.
 {
     CronFile *file;
     CronLine *line;
     for (file = G.cron_files; file; file = file->cf_next) {
         if (!file->cf_wants_starting)
             continue;
         file->cf_wants_starting = 0;
         for (line = file->cf_lines; line; line = line->cl_next) {
             pid_t pid;
             if (line->cl_pid != wants_start)
                 continue;
             pid = start_one_job(file->cf_username, line);
             log8("USER %s pid %3d cmd %s",
                 file->cf_username, (int)pid, line->cl_cmd);
             if (pid < 0) {
                 file->cf_wants_starting = 1;
             }
             if (pid > 0) {
                 file->cf_has_running = 1;
             }
         }
     }
 }
References G, line, log8(), pid, and start_one_job().
Referenced by crond_main().
start_one_job()
static pid_t start_one_job (const char * user, CronLine * line) static
Definition at line 843 of file crond.c.
 {
     const char *shell;
     struct passwd *pas;
     pid_t pid;
     pas = getpwnam(user);
     if (!pas) {
         bb_error_msg("can't get uid for %s", user);
         goto err;
     }
     /* Prepare things before vfork */
     shell = line->cl_shell ? line->cl_shell : G.default_shell;
     set_env_vars(pas, shell, line->cl_path);
     /* Fork as the user in question and run program */
     pid = vfork();
     if (pid == 0) {
         /* CHILD */
         /* initgroups, setgid, setuid, and chdir to home or CRON_DIR */
         change_user(pas);
         log5("child running %s", shell);
         /* crond 3.0pl1-100 puts tasks in separate process groups */
         bb_setpgrp();
         execl(shell, shell, "-c", line->cl_cmd, (char *) NULL);
         bb_error_msg_and_die("can't execute '%s' for user %s", shell, user);
     }
     if (pid < 0) {
         bb_simple_perror_msg("vfork");
  err:
         pid = 0;
     }
     line->cl_pid = pid;
     return pid;
 }
References bb_error_msg(), bb_error_msg_and_die(), bb_setpgrp, bb_simple_perror_msg(), change_user(), err(), execl(), G, getpwnam, log5(), NULL, pid, set_env_vars(), and vfork().
Referenced by start_jobs().
Variable Documentation
ALIGN1
const char MonAry [] ALIGN1 static
Initial value:
=
    "sun""mon""tue""wed""thu""fri""sat"
Definition at line 214 of file crond.c.
FIX_ALIASING
struct globals FIX_ALIASING