Fennix: Userspace/apps/base/busybox/selinux/chcon.c File Reference
chcon.c File Reference
#include <selinux/context.h>
#include "libbb.h"
Macros
#define OPT_RECURSIVE (1<<0) /* 'R' */
#define OPT_CHANHES (1<<1) /* 'c' */
#define OPT_NODEREFERENCE (1<<2) /* 'h' */
#define OPT_QUIET (1<<3) /* 'f' */
#define OPT_USER (1<<4) /* 'u' */
#define OPT_ROLE (1<<5) /* 'r' */
#define OPT_TYPE (1<<6) /* 't' */
#define OPT_RANGE (1<<7) /* 'l' */
#define OPT_VERBOSE (1<<8) /* 'v' */
#define OPT_REFERENCE ((1<<9) * ENABLE_LONG_OPTS)
#define OPT_COMPONENT_SPECIFIED (OPT_USER | OPT_ROLE | OPT_TYPE | OPT_RANGE)
Functions
static int FAST_FUNC change_filedir_context (struct recursive_state *state UNUSED_PARAM, const char *fname, struct stat *stbuf UNUSED_PARAM)
int chcon_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static char * user = NULL
static char * role = NULL
static char * type = NULL
static char * range = NULL
static char * specified_context = NULL
Macro Definition Documentation
OPT_CHANHES
#define OPT_CHANHES (1<<1) /* 'c' */
Definition at line 48 of file chcon.c.
OPT_COMPONENT_SPECIFIED
#define OPT_COMPONENT_SPECIFIED (OPT_USER | OPT_ROLE | OPT_TYPE | OPT_RANGE)
Definition at line 57 of file chcon.c.
OPT_NODEREFERENCE
#define OPT_NODEREFERENCE (1<<2) /* 'h' */
Definition at line 49 of file chcon.c.
OPT_QUIET
#define OPT_QUIET (1<<3) /* 'f' */
Definition at line 50 of file chcon.c.
OPT_RANGE
#define OPT_RANGE (1<<7) /* 'l' */
Definition at line 54 of file chcon.c.
OPT_RECURSIVE
#define OPT_RECURSIVE (1<<0) /* 'R' */
Definition at line 47 of file chcon.c.
OPT_REFERENCE
#define OPT_REFERENCE ((1<<9) * ENABLE_LONG_OPTS)
Definition at line 56 of file chcon.c.
OPT_ROLE
#define OPT_ROLE (1<<5) /* 'r' */
Definition at line 52 of file chcon.c.
OPT_TYPE
#define OPT_TYPE (1<<6) /* 't' */
Definition at line 53 of file chcon.c.
OPT_USER
#define OPT_USER (1<<4) /* 'u' */
Definition at line 51 of file chcon.c.
OPT_VERBOSE
#define OPT_VERBOSE (1<<8) /* 'v' */
Definition at line 55 of file chcon.c.
Function Documentation
change_filedir_context()
static int FAST_FUNC change_filedir_context (struct recursive_state *state UNUSED_PARAM, const char * fname, struct stat *stbuf UNUSED_PARAM) static
Definition at line 65 of file chcon.c.
 {
     context_t context = NULL;
     security_context_t file_context = NULL;
     security_context_t context_string;
     int rc = FALSE;
     int status = 0;
     if (option_mask32 & OPT_NODEREFERENCE) {
         status = lgetfilecon(fname, &file_context);
     } else {
         status = getfilecon(fname, &file_context);
     }
     if (status < 0 && errno != ENODATA) {
         if ((option_mask32 & OPT_QUIET) == 0)
             bb_error_msg("can't obtain security context: %s", fname);
         goto skip;
     }
     if (file_context == NULL && specified_context == NULL) {
         bb_error_msg("can't apply partial context to unlabeled file %s", fname);
         goto skip;
     }
     if (specified_context == NULL) {
         context = set_security_context_component(file_context,
                             user, role, type, range);
         if (!context) {
             bb_error_msg("can't compute security context from %s", file_context);
             goto skip;
         }
     } else {
         context = context_new(specified_context);
         if (!context) {
             bb_error_msg("invalid context: %s", specified_context);
             goto skip;
         }
     }
     context_string = context_str(context);
     if (!context_string) {
         bb_simple_error_msg("can't obtain security context in text expression");
         goto skip;
     }
     if (file_context == NULL || strcmp(context_string, file_context) != 0) {
         int fail;
         if (option_mask32 & OPT_NODEREFERENCE) {
             fail = lsetfilecon(fname, context_string);
         } else {
             fail = setfilecon(fname, context_string);
         }
         if ((option_mask32 & OPT_VERBOSE) || ((option_mask32 & OPT_CHANHES) && !fail)) {
             printf(!fail
                 ? "context of %s changed to %s\n"
                 : "can't change context of %s to %s\n",
                 fname, context_string);
         }
         if (!fail) {
             rc = TRUE;
         } else if ((option_mask32 & OPT_QUIET) == 0) {
             bb_error_msg("can't change context of %s to %s",
                     fname, context_string);
         }
     } else {
         if (option_mask32 & OPT_VERBOSE) {
             printf("context of %s retained as %s\n", fname, context_string);
         }
         rc = TRUE;
     }
 skip:
     context_free(context);
     freecon(file_context);
     return rc;
 }
References bb_error_msg(), bb_simple_error_msg(), context, ENODATA, errno, FALSE, fname, NULL, OPT_CHANHES, OPT_NODEREFERENCE, OPT_QUIET, OPT_VERBOSE, option_mask32, printf, range, rc, role, set_security_context_component(), skip, specified_context, status, strcmp, TRUE, and type.
Referenced by chcon_main().
chcon_main()
int chcon_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 162 of file chcon.c.
 {
     char *reference_file;
     char *fname;
     int i, errors = 0;
     getopt32long(argv, "^"
         "Rchfu:r:t:l:v"
         "\0"
         "-1" /* at least 1 arg */
         ":?" /* error if exclusivity constraints are violated */
 #if ENABLE_LONG_OPTS
         ":\xff--urtl:u--\xff:r--\xff:t--\xff:l--\xff"
 #endif
         ":f--v:v--f"  /* 'verbose' and 'quiet' are exclusive */
         , chcon_longopts,
         &user, &role, &type, &range, &reference_file
     );
     argv += optind;
 #if ENABLE_LONG_OPTS
     if (option_mask32 & OPT_REFERENCE) {
         /* FIXME: lgetfilecon() should be used when '-h' is specified.
          * But current implementation follows the original one. */
         if (getfilecon(reference_file, &specified_context) < 0)
             bb_perror_msg_and_die("getfilecon('%s') failed", reference_file);
     } else
 #endif
     if ((option_mask32 & OPT_COMPONENT_SPECIFIED) == 0) {
         specified_context = *argv++;
         /* specified_context is never NULL -
          * "-1" in opt_complementary prevents this. */
         if (!argv[0])
             bb_simple_error_msg_and_die("too few arguments");
     }
     for (i = 0; (fname = argv[i]) != NULL; i++) {
         int fname_len = strlen(fname);
         while (fname_len > 1 && fname[fname_len - 1] == '/')
             fname_len--;
         fname[fname_len] = '\0';
         if (recursive_action(fname,
                     ((option_mask32 & OPT_RECURSIVE) ? ACTION_RECURSE : 0),
                     change_filedir_context,
                     change_filedir_context,
                     NULL) != TRUE)
             errors = 1;
     }
     return errors;
 }
References ACTION_RECURSE, argv, bb_perror_msg_and_die(), bb_simple_error_msg_and_die(), change_filedir_context(), errors, fname, getopt32long, i, NULL, OPT_COMPONENT_SPECIFIED, OPT_RECURSIVE, OPT_REFERENCE, optind, option_mask32, range, recursive_action(), reference_file, role, specified_context, strlen, TRUE, and type.
Variable Documentation
range
char* range = NULL static
Definition at line 62 of file chcon.c.
Referenced by change_filedir_context(), and chcon_main().
role
char* role = NULL static
Definition at line 60 of file chcon.c.
Referenced by change_filedir_context(), chcon_main(), runcon_compute_new_context(), runcon_main(), and set_security_context_component().
specified_context
char* specified_context = NULL static
Definition at line 63 of file chcon.c.
Referenced by change_filedir_context(), and chcon_main().
type
char* type = NULL static
Definition at line 61 of file chcon.c.
Referenced by change_filedir_context(), and chcon_main().
user
char* user = NULL static
Definition at line 59 of file chcon.c.