Fennix Userspace: Userspace/apps/base/busybox/include/rtc_.h File Reference
rtc_.h File Reference
#include "libbb.h"
Data Structures
struct linux_rtc_time
struct linux_rtc_wkalrm
Macros
#define ADJTIME_PATH "/etc/adjtime"
#define RTC_AIE_ON _IO('p', 0x01) /* Alarm int. enable on */
#define RTC_AIE_OFF _IO('p', 0x02) /* ... off */
#define RTC_UIE_ON _IO('p', 0x03) /* Update int. enable on */
#define RTC_UIE_OFF _IO('p', 0x04) /* ... off */
#define RTC_PIE_ON _IO('p', 0x05) /* Periodic int. enable on */
#define RTC_PIE_OFF _IO('p', 0x06) /* ... off */
#define RTC_WIE_ON _IO('p', 0x0f) /* Watchdog int. enable on */
#define RTC_WIE_OFF _IO('p', 0x10) /* ... off */
#define RTC_ALM_SET _IOW('p', 0x07, struct linux_rtc_time) /* Set alarm time */
#define RTC_ALM_READ _IOR('p', 0x08, struct linux_rtc_time) /* Read alarm time */
#define RTC_RD_TIME _IOR('p', 0x09, struct linux_rtc_time) /* Read RTC time */
#define RTC_SET_TIME _IOW('p', 0x0a, struct linux_rtc_time) /* Set RTC time */
#define RTC_IRQP_READ _IOR('p', 0x0b, unsigned long) /* Read IRQ rate */
#define RTC_IRQP_SET _IOW('p', 0x0c, unsigned long) /* Set IRQ rate */
#define RTC_EPOCH_READ _IOR('p', 0x0d, unsigned long) /* Read epoch */
#define RTC_EPOCH_SET _IOW('p', 0x0e, unsigned long) /* Set epoch */
#define RTC_WKALM_SET _IOW('p', 0x0f, struct linux_rtc_wkalrm)/* Set wakeup alarm*/
#define RTC_WKALM_RD _IOR('p', 0x10, struct linux_rtc_wkalrm)/* Get wakeup alarm*/
#define RTC_IRQF 0x80 /* any of the following is active */
#define RTC_PF 0x40
#define RTC_AF 0x20
#define RTC_UF 0x10
Functions
int rtc_adjtime_is_utc (void) FAST_FUNC
int rtc_xopen (const char **default_rtc, int flags) FAST_FUNC
void rtc_read_tm (struct tm *ptm, int fd) FAST_FUNC
time_t rtc_tm2time (struct tm *ptm, int utc) FAST_FUNC
Data Structure Documentation
linux_rtc_time
struct linux_rtc_time
Definition at line 31 of file rtc_.h.
Data Fields
int tm_hour
int tm_isdst
int tm_mday
int tm_min
int tm_mon
int tm_sec
int tm_wday
int tm_yday
int tm_year
linux_rtc_wkalrm
struct linux_rtc_wkalrm
Definition at line 43 of file rtc_.h.
Data Fields
unsigned char enabled
unsigned char pending
struct linux_rtc_time time
Macro Definition Documentation
ADJTIME_PATH
#define ADJTIME_PATH "/etc/adjtime"
Definition at line 17 of file rtc_.h.
RTC_AF
#define RTC_AF 0x20
Definition at line 77 of file rtc_.h.
RTC_AIE_OFF
#define RTC_AIE_OFF _IO('p', 0x02) /* ... off */
Definition at line 54 of file rtc_.h.
RTC_AIE_ON
#define RTC_AIE_ON _IO('p', 0x01) /* Alarm int. enable on */
Definition at line 53 of file rtc_.h.
RTC_ALM_READ
#define RTC_ALM_READ _IOR('p', 0x08, struct linux_rtc_time) /* Read alarm time */
Definition at line 63 of file rtc_.h.
RTC_ALM_SET
#define RTC_ALM_SET _IOW('p', 0x07, struct linux_rtc_time) /* Set alarm time */
Definition at line 62 of file rtc_.h.
RTC_EPOCH_READ
#define RTC_EPOCH_READ _IOR('p', 0x0d, unsigned long) /* Read epoch */
Definition at line 68 of file rtc_.h.
RTC_EPOCH_SET
#define RTC_EPOCH_SET _IOW('p', 0x0e, unsigned long) /* Set epoch */
Definition at line 69 of file rtc_.h.
RTC_IRQF
#define RTC_IRQF 0x80 /* any of the following is active */
Definition at line 75 of file rtc_.h.
RTC_IRQP_READ
#define RTC_IRQP_READ _IOR('p', 0x0b, unsigned long) /* Read IRQ rate */
Definition at line 66 of file rtc_.h.
RTC_IRQP_SET
#define RTC_IRQP_SET _IOW('p', 0x0c, unsigned long) /* Set IRQ rate */
Definition at line 67 of file rtc_.h.
RTC_PF
#define RTC_PF 0x40
Definition at line 76 of file rtc_.h.
RTC_PIE_OFF
#define RTC_PIE_OFF _IO('p', 0x06) /* ... off */
Definition at line 58 of file rtc_.h.
RTC_PIE_ON
#define RTC_PIE_ON _IO('p', 0x05) /* Periodic int. enable on */
Definition at line 57 of file rtc_.h.
RTC_RD_TIME
#define RTC_RD_TIME _IOR('p', 0x09, struct linux_rtc_time) /* Read RTC time */
Definition at line 64 of file rtc_.h.
RTC_SET_TIME
#define RTC_SET_TIME _IOW('p', 0x0a, struct linux_rtc_time) /* Set RTC time */
Definition at line 65 of file rtc_.h.
RTC_UF
#define RTC_UF 0x10
Definition at line 78 of file rtc_.h.
RTC_UIE_OFF
#define RTC_UIE_OFF _IO('p', 0x04) /* ... off */
Definition at line 56 of file rtc_.h.
RTC_UIE_ON
#define RTC_UIE_ON _IO('p', 0x03) /* Update int. enable on */
Definition at line 55 of file rtc_.h.
RTC_WIE_OFF
#define RTC_WIE_OFF _IO('p', 0x10) /* ... off */
Definition at line 60 of file rtc_.h.
RTC_WIE_ON
#define RTC_WIE_ON _IO('p', 0x0f) /* Watchdog int. enable on */
Definition at line 59 of file rtc_.h.
RTC_WKALM_RD
#define RTC_WKALM_RD _IOR('p', 0x10, struct linux_rtc_wkalrm)/* Get wakeup alarm*/
Definition at line 72 of file rtc_.h.
RTC_WKALM_SET
#define RTC_WKALM_SET _IOW('p', 0x0f, struct linux_rtc_wkalrm)/* Set wakeup alarm*/
Definition at line 71 of file rtc_.h.
Function Documentation
rtc_adjtime_is_utc()
int rtc_adjtime_is_utc (void)
Definition at line 10 of file rtc.c.
 {
     int utc = 0;
     FILE *f = fopen_for_read(ADJTIME_PATH);
     if (f) {
         char buffer[128];
         while (fgets(buffer, sizeof(buffer), f)) {
             if (is_prefixed_with(buffer, "UTC")) {
                 utc = 1;
                 break;
             }
         }
         fclose(f);
     }
     return utc;
 }
References ADJTIME_PATH, f, fclose(), fgets, fopen_for_read(), and is_prefixed_with().
Referenced by hwclock_main(), and rtcwake_main().
rtc_read_tm()
void rtc_read_tm (struct tm * ptm, int fd)
Definition at line 81 of file rtc.c.
 {
     memset(ptm, 0, sizeof(*ptm));
     xioctl(fd, RTC_RD_TIME, ptm);
     ptm->tm_isdst = -1; /* "not known" */
 }
References fd, memset(), RTC_RD_TIME, tm::tm_isdst, and xioctl.
Referenced by read_rtc(), and rtcwake_main().
rtc_tm2time()
time_t rtc_tm2time (struct tm * ptm, int utc)
Definition at line 88 of file rtc.c.
 {
     char *oldtz = oldtz; /* for compiler */
     time_t t;
     if (utc) {
         oldtz = getenv("TZ");
         putenv((char*)"TZ=UTC0");
         tzset();
     }
     t = mktime(ptm);
     if (utc) {
         unsetenv("TZ");
         if (oldtz)
             putenv(oldtz - 3);
         tzset();
     }
     return t;
 }
References getenv, mktime(), putenv(), t, tzset(), and unsetenv().
Referenced by read_rtc(), and rtcwake_main().
rtc_xopen()
int rtc_xopen (const char ** default_rtc, int flags)
Definition at line 57 of file rtc.c.
 {
     int rtc;
     const char *name =
         "/dev/rtc""\0"
         "/dev/rtc0""\0"
         "/dev/misc/rtc""\0";
     if (!*default_rtc)
         goto try_name;
     name = ""; /*else: we have rtc name, don't try other names */
     for (;;) {
         rtc = open_loop_on_busy(*default_rtc, flags);
         if (rtc >= 0)
             return rtc;
         if (!name[0])
             return xopen(*default_rtc, flags);
  try_name:
         *default_rtc = name;
         name += strlen(name) + 1;
     }
 }
References flags, open_loop_on_busy(), strlen(), and xopen().
Referenced by from_sys_clock(), read_rtc(), and rtcwake_main().