Fennix: Drivers/library/base.c File Reference
base.c File Reference
#include <base.h>
#include <driver.h>
#include <errno.h>
Functions
int RegisterInterruptHandler (uint8_t IRQ, void *Handler)
Register an interrupt handler.
int OverrideInterruptHandler (uint8_t IRQ, void *Handler)
Override an interrupt handler.
int UnregisterInterruptHandler (uint8_t IRQ, void *Handler)
Unregister an interrupt handler.
int UnregisterAllInterruptHandlers (void *Handler)
Unregister all interrupt handlers for a given handler.
void * AllocateMemory (size_t Pages)
Allocate an amount of memory pages.
void FreeMemory (void *Pointer, size_t Pages)
Free an amount of memory pages.
void AppendMapFlag (void *Address, PageMapFlags Flag)
Append a flag to a page.
void RemoveMapFlag (void *Address, PageMapFlags Flag)
Remove a flag from a page.
void MapPages (void *PhysicalAddress, void *VirtualAddress, size_t Pages, uint32_t Flags)
Map pages.
void UnmapPages (void *VirtualAddress, size_t Pages)
Unmap pages.
void KPrint (const char *Format,...)
Print to the screen.
void Log (const char *Format,...)
Print to the kernel logger.
CriticalState EnterCriticalSection ()
Enter a critical section.
void LeaveCriticalSection (CriticalState PreviousState)
Leave a critical section.
Variables
__driverAPI * API = NULL
Function Documentation
AllocateMemory()
void* AllocateMemory (size_t Pages)
Allocate an amount of memory pages.
Parameters
Pages The amount of pages to allocate
Returns
A pointer to the allocated memory, NULL if failed
Definition at line 64 of file base.c.
 {
     if (Pages == 0)
         return NULL;
     return API->RequestPages(API->MajorID,
                              Pages);
 }
References API, __driverAPI::MajorID, NULL, and __driverAPI::RequestPages.
Referenced by AC97Device::AC97Device(), Port::Configure(), DisplayScaleThread(), E1000Device::InitializeRX(), E1000Device::InitializeTX(), MessageReceive(), Port::Port(), and RTL8139Device::RTL8139Device().
AppendMapFlag()
void AppendMapFlag (void * Address, PageMapFlags Flag)
Append a flag to a page.
Parameters
Address The address of the page
Flag The flag to append
Definition at line 83 of file base.c.
 {
     API->AppendMapFlag(API->MajorID,
                        Address,
                        Flag);
 }
References Address, API, __driverAPI::AppendMapFlag, and __driverAPI::MajorID.
EnterCriticalSection()
CriticalState EnterCriticalSection ()
Enter a critical section.
Returns
The previous interrupt state
This function will disable interrupts and return the previous interrupt state.
Definition at line 137 of file base.c.
 {
     CriticalState cs;
 #if defined(__i386__) || defined(__x86_64__)
     uintptr_t Flags;
 #if defined(__x86_64__)
     asmv("pushfq");
     asmv("popq %0"
          : "=r"(Flags));
 #else
     asmv("pushfl");
     asmv("popl %0"
          : "=r"(Flags));
 #endif
     cs = Flags & (1 << 9);
     asmv("cli");
 #elif defined(__arm__) || defined(__aarch64__)
     uintptr_t Flags;
     asmv("mrs %0, cpsr"
          : "=r"(Flags));
     cs = Flags & (1 << 7);
     asmv("cpsid i");
 #endif
     return cs;
 }
References asmv(), and Flags.
FreeMemory()
void FreeMemory (void * Pointer, size_t Pages)
Free an amount of memory pages.
Parameters
Pointer The pointer to the memory to free
Pages The amount of pages to free
Note
If the pointer is invalid, the error is ignored and the function returns
Definition at line 73 of file base.c.
 {
     if (Pointer == NULL || Pages == 0)
         return;
     API->FreePages(API->MajorID,
                    Pointer,
                    Pages);
 }
References API, __driverAPI::FreePages, __driverAPI::MajorID, and NULL.
Referenced by DriverFinal(), MessageReceive(), and Port::~Port().
KPrint()
void KPrint (const char * Format, ...)
Print to the screen.
Parameters
Format The format string
... The arguments to the format string
Note
The newline character is automatically appended
Definition at line 113 of file base.c.
 {
     va_list Args;
     va_start(Args, Format);
     API->KPrint(API->MajorID,
                 Format,
                 Args);
     va_end(Args);
 }
References API, __driverAPI::KPrint, __driverAPI::MajorID, va_end, and va_start.
LeaveCriticalSection()
void LeaveCriticalSection (CriticalState PreviousState)
Leave a critical section.
Parameters
PreviousState The previous interrupt state
This function will restore the previous interrupt state.
Definition at line 169 of file base.c.
 {
 #if defined(__i386__) || defined(__x86_64__)
     if (PreviousState)
         asmv("sti");
 #elif defined(__arm__) || defined(__aarch64__)
     if (PreviousState)
         asmv("cpsie i");
 #endif
 }
References asmv().
Log()
void Log (const char * Format, ...)
Print to the kernel logger.
Parameters
Format The format string
... The arguments to the format string
Definition at line 125 of file base.c.
 {
     va_list Args;
     va_start(Args, Format);
     API->KernelLog(API->MajorID,
                    Format,
                    Args);
     va_end(Args);
 }
References API, __driverAPI::KernelLog, __driverAPI::MajorID, va_end, and va_start.
Referenced by Port::Configure(), cxx_Finalize(), cxx_Initialize(), cxx_Probe(), DetectPS2Keyboard(), DetectPS2Mouse(), DisplayGetSize(), DisplayScaleThread(), DriverEntry(), DriverProbe(), E1000Device::E1000Device(), E1000Device::GetMAC(), HDADevice::HDADevice(), Port::Identify(), InitializeKeyboard(), InitializeMouse(), InterruptHandler(), MessageReceive(), MessageSend(), AC97Device::OnInterruptReceived(), OpenMessageChannel(), PS2KbdInterruptHandler(), PS2Wait(), Port::ReadWrite(), SendRPCI(), AC97Device::write(), and E1000Device::~E1000Device().
MapPages()
void MapPages (void * PhysicalAddress, void * VirtualAddress, size_t Pages, uint32_t Flags)
Map pages.
Parameters
PhysicalAddress The physical address to map
VirtualAddress The virtual address to map to
Pages The amount of pages to map
Flags The flags to map the pages with
Definition at line 97 of file base.c.
 {
     API->MapPages(API->MajorID,
                   PhysicalAddress,
                   VirtualAddress,
                   Pages,
                   Flags);
 }
References API, Flags, __driverAPI::MajorID, __driverAPI::MapPages, and PhysicalAddress.
OverrideInterruptHandler()
int OverrideInterruptHandler (uint8_t IRQ, void * Handler)
Override an interrupt handler.
This function will check all registered handlers (by the drivers) for the given IRQ and remove them. Then it will register the new handler.
Parameters
IRQ The IRQ to override the handler for (IRQ0 != 0x32 but 0)
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 35 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->OverrideInterruptHandler(API->MajorID,
                                          IRQ,
                                          Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::OverrideInterruptHandler.
RegisterInterruptHandler()
int RegisterInterruptHandler (uint8_t IRQ, void * Handler)
Register an interrupt handler.
Parameters
IRQ The IRQ to register the handler for (IRQ0 != 0x32 but 0)
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 25 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->RegisterInterruptHandler(API->MajorID,
                                          IRQ,
                                          Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::RegisterInterruptHandler.
RemoveMapFlag()
void RemoveMapFlag (void * Address, PageMapFlags Flag)
Remove a flag from a page.
Parameters
Address The address of the page
Flag The flag to remove
Definition at line 90 of file base.c.
 {
     API->RemoveMapFlag(API->MajorID,
                        Address,
                        Flag);
 }
References Address, API, __driverAPI::MajorID, and __driverAPI::RemoveMapFlag.
UnmapPages()
void UnmapPages (void * VirtualAddress, size_t Pages)
Unmap pages.
Parameters
VirtualAddress The virtual address to unmap
Pages The amount of pages to unmap
Definition at line 106 of file base.c.
 {
     API->UnmapPages(API->MajorID,
                     VirtualAddress,
                     Pages);
 }
References API, __driverAPI::MajorID, and __driverAPI::UnmapPages.
UnregisterAllInterruptHandlers()
int UnregisterAllInterruptHandlers (void * Handler)
Unregister all interrupt handlers for a given handler.
Parameters
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 55 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->UnregisterAllInterruptHandlers(API->MajorID,
                                                Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::UnregisterAllInterruptHandlers.
UnregisterInterruptHandler()
int UnregisterInterruptHandler (uint8_t IRQ, void * Handler)
Unregister an interrupt handler.
Parameters
IRQ The IRQ to unregister the handler for (IRQ0 != 0x32 but 0)
Handler Function pointer to the handler
Returns
0 on success, errno on failure
Definition at line 45 of file base.c.
 {
     if (Handler == NULL)
         return -EINVAL;
     return API->UnregisterInterruptHandler(API->MajorID,
                                            IRQ,
                                            Handler);
 }
References API, EINVAL, __driverAPI::MajorID, NULL, and __driverAPI::UnregisterInterruptHandler.
Variable Documentation
API
__driverAPI* API = NULL
Definition at line 23 of file base.c.
Referenced by __delete_alloc_page(), __new_alloc_page(), _start(), AllocateMemory(), AppendMapFlag(), CreateKernelProcess(), CreateKernelThread(), FindPCIDevices(), FreeMemory(), GetBAR(), InitializePCI(), KillProcess(), KillThread(), KPrint(), Log(), MapPages(), MemoryCopy(), MemoryMove(), MemorySet(), OverrideInterruptHandler(), Driver::PopulateDriverAPI(), RegisterAudioDevice(), RegisterBlockDevice(), RegisterInputDevice(), RegisterInterruptHandler(), RegisterNetDevice(), RemoveMapFlag(), ReportAbsoluteMouseEvent(), ReportKeyboardEvent(), ReportNetworkPacket(), ReportRelativeMouseEvent(), Sleep(), StringLength(), strstr(), UnmapPages(), UnregisterAllInterruptHandlers(), UnregisterAudioDevice(), UnregisterBlockDevice(), UnregisterInputDevice(), UnregisterInterruptHandler(), UnregisterNetDevice(), and Yield().