Fennix Userspace: Userspace/apps/base/busybox/console-tools/loadfont.c File Reference
loadfont.c File Reference
#include "libbb.h"
#include <sys/kd.h>
Data Structures
struct console_font_op
struct psf1_header
Macros
#define KDFONTOP 0x4B72
#define KD_FONT_OP_SET 0 /* Set font */
#define KD_FONT_OP_GET 1 /* Get font */
#define KD_FONT_OP_SET_DEFAULT 2 /* Set font to default, data points to name / NULL */
#define KD_FONT_OP_COPY 3 /* Copy from another console */
#define KD_FONT_FLAG_OLD 0x80000000 /* Invoked via old interface */
#define KD_FONT_FLAG_DONT_RECALC 1 /* Don't call adjust_height() */
#define psf1h(x) ((struct psf1_header*)(x))
#define PSF1_MAGIC_OK(x)
#define do_loadtable(fd, inbuf, tailsz, fontsize, psf2) do_loadtable(fd, inbuf, tailsz, fontsize)
#define psf2 0 /* +0 bytes */
Enumerations
enum {
PSF1_MAGIC0 = 0x36 , PSF1_MAGIC1 = 0x04 , PSF1_MODE512 = 0x01 , PSF1_MODEHASTAB = 0x02 ,
PSF1_MODEHASSEQ = 0x04 , PSF1_MAXMODE = 0x05 , PSF1_STARTSEQ = 0xfffe , PSF1_SEPARATOR = 0xffff
}
Functions
static void do_loadfont (int fd, unsigned char *inbuf, int height, int width, int charsize, int fontsize)
static void do_loadtable (int fd, unsigned char *inbuf, int tailsz, int fontsize, int psf2)
static void do_load (int fd, unsigned char *buffer, size_t len)
Data Structure Documentation
console_font_op
struct console_font_op
Definition at line 63 of file loadfont.c.
Data Fields
unsigned charcount
unsigned char * data
unsigned flags
unsigned height
unsigned op
unsigned width
psf1_header
struct psf1_header
Definition at line 91 of file loadfont.c.
Data Fields
unsigned char charsize
unsigned char magic[2]
unsigned char mode
Macro Definition Documentation
do_loadtable
#define do_loadtable (fd, inbuf, tailsz, fontsize, psf2) do_loadtable(fd, inbuf, tailsz, fontsize)
Definition at line 190 of file loadfont.c.
KD_FONT_FLAG_DONT_RECALC
#define KD_FONT_FLAG_DONT_RECALC 1 /* Don't call adjust_height() */
Definition at line 75 of file loadfont.c.
KD_FONT_FLAG_OLD
#define KD_FONT_FLAG_OLD 0x80000000 /* Invoked via old interface */
Definition at line 74 of file loadfont.c.
KD_FONT_OP_COPY
#define KD_FONT_OP_COPY 3 /* Copy from another console */
Definition at line 73 of file loadfont.c.
KD_FONT_OP_GET
#define KD_FONT_OP_GET 1 /* Get font */
Definition at line 71 of file loadfont.c.
KD_FONT_OP_SET
#define KD_FONT_OP_SET 0 /* Set font */
Definition at line 70 of file loadfont.c.
KD_FONT_OP_SET_DEFAULT
#define KD_FONT_OP_SET_DEFAULT 2 /* Set font to default, data points to name / NULL */
Definition at line 72 of file loadfont.c.
KDFONTOP
#define KDFONTOP 0x4B72
Definition at line 62 of file loadfont.c.
PSF1_MAGIC_OK
#define PSF1_MAGIC_OK (x)
Value:
     ( \
     (x)->magic[0] == PSF1_MAGIC0 \
  && (x)->magic[1] == PSF1_MAGIC1 \
)
Definition at line 99 of file loadfont.c.
psf1h
#define psf1h (x) ((struct psf1_header*)(x))
Definition at line 97 of file loadfont.c.
psf2
#define psf2 0 /* +0 bytes */
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PSF1_MAGIC0
PSF1_MAGIC1
PSF1_MODE512
PSF1_MODEHASTAB
PSF1_MODEHASSEQ
PSF1_MAXMODE
PSF1_STARTSEQ
PSF1_SEPARATOR
Definition at line 80 of file loadfont.c.
      {
     PSF1_MAGIC0 = 0x36,
     PSF1_MAGIC1 = 0x04,
     PSF1_MODE512 = 0x01,
     PSF1_MODEHASTAB = 0x02,
     PSF1_MODEHASSEQ = 0x04,
     PSF1_MAXMODE = 0x05,
     PSF1_STARTSEQ = 0xfffe,
     PSF1_SEPARATOR = 0xffff,
 };
Function Documentation
do_load()
static void do_load (int fd, unsigned char * buffer, size_t len) static
Definition at line 270 of file loadfont.c.
 {
     int height;
     int width = 8;
     int charsize;
     int fontsize = 256;
     int has_table = 0;
     unsigned char *font = buffer;
     unsigned char *table;
     if (len >= sizeof(struct psf1_header) && PSF1_MAGIC_OK(psf1h(buffer))) {
         if (psf1h(buffer)->mode > PSF1_MAXMODE)
             bb_simple_error_msg_and_die("unsupported psf file mode");
         if (psf1h(buffer)->mode & PSF1_MODE512)
             fontsize = 512;
         if (psf1h(buffer)->mode & PSF1_MODEHASTAB)
             has_table = 1;
         height = charsize = psf1h(buffer)->charsize;
         font += sizeof(struct psf1_header);
     } else
 #if ENABLE_FEATURE_LOADFONT_PSF2
     if (len >= sizeof(struct psf2_header) && PSF2_MAGIC_OK(psf2h(buffer))) {
         if (psf2h(buffer)->version > PSF2_MAXVERSION)
             bb_simple_error_msg_and_die("unsupported psf file version");
         fontsize = psf2h(buffer)->length;
         if (psf2h(buffer)->flags & PSF2_HAS_UNICODE_TABLE)
             has_table = 2;
         charsize = psf2h(buffer)->charsize;
         height = psf2h(buffer)->height;
         width = psf2h(buffer)->width;
         font += psf2h(buffer)->headersize;
     } else
 #endif
 #if ENABLE_FEATURE_LOADFONT_RAW
     if (len == 9780) {  /* file with three code pages? */
         charsize = height = 16;
         font += 40;
     } else if ((len & 0377) == 0) {  /* bare font */
         charsize = height = len / 256;
     } else
 #endif
     {
         bb_simple_error_msg_and_die("input file: bad length or unsupported font type");
     }
 #if !defined(PIO_FONTX) || defined(__sparc__)
     if (fontsize != 256)
         bb_simple_error_msg_and_die("only fontsize 256 supported");
 #endif
     table = font + fontsize * charsize;
     buffer += len;
     if (table > buffer || (!has_table && table != buffer))
         bb_simple_error_msg_and_die("input file: bad length");
     do_loadfont(fd, font, height, width, charsize, fontsize);
     if (has_table)
         do_loadtable(fd, table, buffer - table, fontsize, has_table - 1);
 }
References bb_simple_error_msg_and_die(), buffer, psf1_header::charsize, do_loadfont(), do_loadtable, fd, flags, height(), PSF1_MAGIC_OK, PSF1_MAXMODE, PSF1_MODE512, PSF1_MODEHASTAB, psf1h, table, and width.
do_loadfont()
static void do_loadfont (int fd, unsigned char * inbuf, int height, int width, int charsize, int fontsize) static
Definition at line 138 of file loadfont.c.
 {
     unsigned char *buf;
     int charwidth = 32 * ((width+7)/8);
     int i;
     if (height < 1 || height > 32 || width < 1 || width > 32)
         bb_error_msg_and_die("bad character size %dx%d", height, width);
     buf = xzalloc(charwidth * ((fontsize < 128) ? 128 : fontsize));
     for (i = 0; i < fontsize; i++)
         memcpy(buf + (i*charwidth), inbuf + (i*charsize), charsize);
     { /* KDFONTOP */
         struct console_font_op cfo;
         cfo.op = KD_FONT_OP_SET;
         cfo.flags = 0;
         cfo.width = width;
         cfo.height = height;
         cfo.charcount = fontsize;
         cfo.data = buf;
         xioctl(fd, KDFONTOP, &cfo);
     }
     free(buf);
 }
References bb_error_msg_and_die(), buf, console_font_op::charcount, console_font_op::data, fd, console_font_op::flags, free, console_font_op::height, height(), i, inbuf, KD_FONT_OP_SET, KDFONTOP, memcpy(), console_font_op::op, console_font_op::width, width, xioctl, and xzalloc().
Referenced by do_load().
do_loadtable()
static void do_loadtable (int fd, unsigned char * inbuf, int tailsz, int fontsize, int psf2) static
Definition at line 193 of file loadfont.c.
 {
 #if !ENABLE_FEATURE_LOADFONT_PSF2
 /* gcc 4.3.1 code size: */
 # define psf2 0 /* +0 bytes */
 //  const int psf2 = 0; /* +8 bytes */
 //  enum { psf2 = 0 }; /* +13 bytes */
 #endif
     struct unimapinit advice;
     struct unimapdesc ud;
     struct unipair *up;
     int ct = 0, maxct;
     int glyph;
     uint16_t unicode;
     maxct = tailsz; /* more than enough */
     up = xmalloc(maxct * sizeof(*up));
     for (glyph = 0; glyph < fontsize; glyph++) {
         while (tailsz > 0) {
             if (!psf2) { /* PSF1 */
                 unicode = (((uint16_t) inbuf[1]) << 8) + inbuf[0];
                 tailsz -= 2;
                 inbuf += 2;
                 if (unicode == PSF1_SEPARATOR)
                     break;
             } else { /* PSF2 */
 #if ENABLE_FEATURE_LOADFONT_PSF2
                 --tailsz;
                 unicode = *inbuf++;
                 if (unicode == PSF2_SEPARATOR) {
                     break;
                 } else if (unicode == PSF2_STARTSEQ) {
                     bb_simple_error_msg_and_die("unicode sequences not implemented");
                 } else if (unicode >= 0xC0) {
                     if (unicode >= 0xFC)
                         unicode &= 0x01, maxct = 5;
                     else if (unicode >= 0xF8)
                         unicode &= 0x03, maxct = 4;
                     else if (unicode >= 0xF0)
                         unicode &= 0x07, maxct = 3;
                     else if (unicode >= 0xE0)
                         unicode &= 0x0F, maxct = 2;
                     else
                         unicode &= 0x1F, maxct = 1;
                     do {
                         if (tailsz <= 0 || *inbuf < 0x80 || *inbuf > 0xBF)
                             bb_simple_error_msg_and_die("illegal UTF-8 character");
                         --tailsz;
                         unicode = (unicode << 6) + (*inbuf++ & 0x3F);
                     } while (--maxct > 0);
                 } else if (unicode >= 0x80) {
                     bb_simple_error_msg_and_die("illegal UTF-8 character");
                 }
 #else
                 return;
 #endif
             }
             up[ct].unicode = unicode;
             up[ct].fontpos = glyph;
             ct++;
         }
     }
     /* Note: after PIO_UNIMAPCLR and before PIO_UNIMAP
      * this printf did not work on many kernels */
     advice.advised_hashsize = 0;
     advice.advised_hashstep = 0;
     advice.advised_hashlevel = 0;
     xioctl(fd, PIO_UNIMAPCLR, &advice);
     ud.entry_ct = ct;
     ud.entries = up;
     xioctl(fd, PIO_UNIMAP, &ud);
 #undef psf2
 }
References bb_simple_error_msg_and_die(), fd, inbuf, PSF1_SEPARATOR, psf2, up, xioctl, and xmalloc.