Fennix: Userspace/musl/src/math/__sin.c File Reference
__sin.c File Reference
#include "libm.h"
Functions
double __sin (double x, double y, int iy)
Variables
static const double S1 = -1.66666666666666324348e-01
static const double S2 = 8.33333333332248946124e-03
static const double S3 = -1.98412698298579493134e-04
static const double S4 = 2.75573137070700676789e-06
static const double S5 = -2.50507602534068634195e-08
static const double S6 = 1.58969099521155010221e-10
Function Documentation
__sin()
double __sin (double x, double y, int iy)
Definition at line 52 of file __sin.c.
 {
     double_t z,r,v,w;
     z = x*x;
     w = z*z;
     r = S2 + z*(S3 + z*S4) + z*w*(S5 + z*S6);
     v = z*x;
     if (iy == 0)
         return x + v*(S1 + z*r);
     else
         return x - ((z*(0.5*y - v*r) - y) - v*S1);
 }
References S1, S2, S3, S4, S5, S6, w, x, and y.
Referenced by cos(), sin(), sin_pi(), sincos(), and sinpi().
Variable Documentation
S1
const double S1 = -1.66666666666666324348e-01 static
Definition at line 45 of file __sin.c.
Referenced by __sin().
S2
const double S2 = 8.33333333332248946124e-03 static
Definition at line 46 of file __sin.c.
Referenced by __sin().
S3
const double S3 = -1.98412698298579493134e-04 static
Definition at line 47 of file __sin.c.
Referenced by __sin().
S4
const double S4 = 2.75573137070700676789e-06 static
Definition at line 48 of file __sin.c.
Referenced by __sin().
S5
const double S5 = -2.50507602534068634195e-08 static
Definition at line 49 of file __sin.c.
Referenced by __sin().
S6
const double S6 = 1.58969099521155010221e-10 static
Definition at line 50 of file __sin.c.
Referenced by __sin().