Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/net_client.h File Reference
net_client.h File Reference
#include "doomtype.h"
#include "d_ticcmd.h"
#include "sha1.h"
#include "net_defs.h"
Functions
boolean NET_CL_Connect (net_addr_t *addr, net_connect_data_t *data)
void NET_CL_Disconnect (void)
void NET_CL_Run (void)
void NET_CL_Init (void)
void NET_CL_LaunchGame (void)
void NET_CL_StartGame (net_gamesettings_t *settings)
void NET_CL_SendTiccmd (ticcmd_t *ticcmd, int maketic)
boolean NET_CL_GetSettings (net_gamesettings_t *_settings)
void NET_Init (void)
void NET_BindVariables (void)
Variables
boolean net_client_connected
boolean net_client_received_wait_data
net_waitdata_t net_client_wait_data
boolean net_waiting_for_launch
char * net_player_name
sha1_digest_t net_server_wad_sha1sum
sha1_digest_t net_server_deh_sha1sum
unsigned int net_server_is_freedoom
sha1_digest_t net_local_wad_sha1sum
sha1_digest_t net_local_deh_sha1sum
unsigned int net_local_is_freedoom
boolean drone
Function Documentation
NET_BindVariables()
void NET_BindVariables (void)
Referenced by D_BindVariables().
NET_CL_Connect()
boolean NET_CL_Connect (net_addr_t * addr, net_connect_data_t * data)
Referenced by D_InitNetGame().
NET_CL_Disconnect()
void NET_CL_Disconnect (void)
Referenced by D_QuitNetGame().
NET_CL_GetSettings()
boolean NET_CL_GetSettings (net_gamesettings_t * _settings)
Referenced by D_StartNetGame().
NET_CL_Init()
void NET_CL_Init (void)
NET_CL_LaunchGame()
void NET_CL_LaunchGame (void)
NET_CL_Run()
void NET_CL_Run (void)
Referenced by NetUpdate().
NET_CL_SendTiccmd()
void NET_CL_SendTiccmd (ticcmd_t * ticcmd, int maketic)
Referenced by BuildNewTic().
NET_CL_StartGame()
void NET_CL_StartGame (net_gamesettings_t * settings)
Referenced by D_StartNetGame().
NET_Init()
void NET_Init (void)
Referenced by D_DoomMain().
Variable Documentation
drone
boolean drone extern
Definition at line 29 of file dummy.c.
Referenced by BuildNewTic(), D_Disconnected(), D_GrabMouseCallback(), D_ReceiveTic(), D_StartNetGame(), GetLowTic(), and PlayersInGame().
net_client_connected
boolean net_client_connected extern
Definition at line 27 of file dummy.c.
Referenced by BuildNewTic(), D_StartNetGame(), GetLowTic(), PlayersInGame(), and TryRunTics().
net_client_received_wait_data
boolean net_client_received_wait_data extern
net_client_wait_data
net_waitdata_t net_client_wait_data extern
net_local_deh_sha1sum
sha1_digest_t net_local_deh_sha1sum extern
net_local_is_freedoom
unsigned int net_local_is_freedoom extern
net_local_wad_sha1sum
sha1_digest_t net_local_wad_sha1sum extern
net_player_name
char* net_player_name extern
net_server_deh_sha1sum
sha1_digest_t net_server_deh_sha1sum extern
net_server_is_freedoom
unsigned int net_server_is_freedoom extern
net_server_wad_sha1sum
sha1_digest_t net_server_wad_sha1sum extern
net_waiting_for_launch
boolean net_waiting_for_launch extern