Fennix: Userspace/musl/src/stdio/ftrylockfile.c File Reference
ftrylockfile.c File Reference
#include "stdio_impl.h"
#include "pthread_impl.h"
#include <limits.h>
Functions
void __do_orphaned_stdio_locks ()
void __unlist_locked_file (FILE *f)
void __register_locked_file (FILE *f, pthread_t self)
int ftrylockfile (FILE *f)
Function Documentation
__do_orphaned_stdio_locks()
void __do_orphaned_stdio_locks (void)
Definition at line 5 of file ftrylockfile.c.
 {
     FILE *f;
     for (f=__pthread_self()->stdio_locks; f; f=f->next_locked)
         a_store(&f->lock, 0x40000000);
 }
References __pthread_self, a_store, and f.
Referenced by __pthread_exit().
__register_locked_file()
void __register_locked_file (FILE * f, pthread_t self)
Definition at line 21 of file ftrylockfile.c.
 {
     f->lockcount = 1;
     f->prev_locked = 0;
     f->next_locked = self->stdio_locks;
     if (f->next_locked) f->next_locked->prev_locked = f;
     self->stdio_locks = f;
 }
References f.
Referenced by ftrylockfile().
__unlist_locked_file()
void __unlist_locked_file (FILE * f)
Definition at line 12 of file ftrylockfile.c.
 {
     if (f->lockcount) {
         if (f->next_locked) f->next_locked->prev_locked = f->prev_locked;
         if (f->prev_locked) f->prev_locked->next_locked = f->next_locked;
         else __pthread_self()->stdio_locks = f->next_locked;
     }
 }
References __pthread_self, and f.
Referenced by fclose(), and funlockfile().
ftrylockfile()
int ftrylockfile (FILE * f)
Definition at line 30 of file ftrylockfile.c.
 {
     pthread_t self = __pthread_self();
     int tid = self->tid;
     int owner = f->lock;
     if ((owner & ~MAYBE_WAITERS) == tid) {
         if (f->lockcount == LONG_MAX)
             return -1;
         f->lockcount++;
         return 0;
     }
     if (owner < 0) f->lock = owner = 0;
     if (owner || a_cas(&f->lock, 0, tid))
         return -1;
     __register_locked_file(f, self);
     return 0;
 }
References __pthread_self, __register_locked_file(), a_cas, f, LONG_MAX, and MAYBE_WAITERS.