Fennix: Userspace/musl/src/thread/synccall.c File Reference
synccall.c File Reference
#include "pthread_impl.h"
#include <semaphore.h>
#include <string.h>
Functions
static void dummy_0 (void)
weak_alias (dummy_0, __tl_lock)
weak_alias (dummy_0, __tl_unlock)
static void dummy (void *p)
static void handler (int sig)
void __synccall (void(*func)(void *), void *ctx)
Variables
static int target_tid
static void(* callback)(void *)
static void(*) context)
static sem_t target_sem
static sem_t caller_sem
Function Documentation
__synccall()
void __synccall (void(*)(void *) func, void * ctx)
Definition at line 44 of file synccall.c.
 {
     sigset_t oldmask;
     int cs, i, r;
     struct sigaction sa = { .sa_flags = SA_RESTART | SA_ONSTACK, .sa_handler = handler };
     pthread_t self = __pthread_self(), td;
     int count = 0;
     /* Blocking signals in two steps, first only app-level signals
      * before taking the lock, then all signals after taking the lock,
      * is necessary to achieve AS-safety. Blocking them all first would
      * deadlock if multiple threads called __synccall. Waiting to block
      * any until after the lock would allow re-entry in the same thread
      * with the lock already held. */
     __block_app_sigs(&oldmask);
     __tl_lock();
     __block_all_sigs(0);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     sem_init(&target_sem, 0, 0);
     sem_init(&caller_sem, 0, 0);
     if (!libc.threads_minus_1 || __syscall(SYS_gettid) != self->tid)
         goto single_threaded;
     callback = func;
     context = ctx;
     /* Block even implementation-internal signals, so that nothing
      * interrupts the SIGSYNCCALL handlers. The main possible source
      * of trouble is asynchronous cancellation. */
     memset(&sa.sa_mask, -1, sizeof sa.sa_mask);
     __libc_sigaction(SIGSYNCCALL, &sa, 0);
     for (td=self->next; td!=self; td=td->next) {
         target_tid = td->tid;
         while ((r = -__syscall(SYS_tkill, td->tid, SIGSYNCCALL)) == EAGAIN);
         if (r) {
             /* If we failed to signal any thread, nop out the
              * callback to abort the synccall and just release
              * any threads already caught. */
             callback = func = dummy;
             break;
         }
         sem_wait(&caller_sem);
         count++;
     }
     target_tid = 0;
     /* Serialize execution of callback in caught threads, or just
      * release them all if synccall is being aborted. */
     for (i=0; i<count; i++) {
         sem_post(&target_sem);
         sem_wait(&caller_sem);
     }
     sa.sa_handler = SIG_IGN;
     __libc_sigaction(SIGSYNCCALL, &sa, 0);
 single_threaded:
     func(ctx);
     /* Only release the caught threads once all threads, including the
      * caller, have returned from the callback function. */
     for (i=0; i<count; i++)
         sem_post(&target_sem);
     for (i=0; i<count; i++)
         sem_wait(&caller_sem);
     sem_destroy(&caller_sem);
     sem_destroy(&target_sem);
     pthread_setcancelstate(cs, 0);
     __tl_unlock();
     __restore_sigs(&oldmask);
 }
References __block_all_sigs(), __block_app_sigs(), __libc_sigaction(), __pthread_self, __restore_sigs(), __syscall, __tl_lock(), __tl_unlock(), callback, caller_sem, context, count, ctx, dummy(), EAGAIN, func(), handler(), i, libc, memset, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), SA_ONSTACK, SA_RESTART, sem_destroy(), sem_init(), sem_post(), sem_wait(), SIG_IGN, SIGSYNCCALL, target_sem, and target_tid.
Referenced by __setxid(), setgroups(), and setrlimit().
dummy()
static void dummy (void * p) static
Definition at line 16 of file synccall.c.
 {
 }
Referenced by __synccall().
dummy_0()
static void dummy_0 (void) static
Definition at line 5 of file synccall.c.
 {
 }
handler()
static void handler (int sig) static
Definition at line 20 of file synccall.c.
 {
     if (__pthread_self()->tid != target_tid) return;
     int old_errno = errno;
     /* Inform caller we have received signal and wait for
      * the caller to let us make the callback. */
     sem_post(&caller_sem);
     sem_wait(&target_sem);
     callback(context);
     /* Inform caller we've complered the callback and wait
      * for the caller to release us to return. */
     sem_post(&caller_sem);
     sem_wait(&target_sem);
     /* Inform caller we are returning and state is destroyable. */
     sem_post(&caller_sem);
     errno = old_errno;
 }
References __pthread_self, callback, caller_sem, context, errno, sem_post(), sem_wait(), target_sem, and target_tid.
Referenced by __synccall().
weak_alias() [1/2]
weak_alias (dummy_0 , __tl_lock)
weak_alias() [2/2]
weak_alias (dummy_0 , __tl_unlock)
Variable Documentation
callback
void(* callback) (void *) (void *) static
Definition at line 13 of file synccall.c.
Referenced by __dns_parse(), __synccall(), D_StartNetGame(), dl_iterate_phdr(), handler(), ST_loadUnloadGraphics(), static_dl_iterate_phdr(), and WI_loadUnloadData().
caller_sem
sem_t caller_sem static
Definition at line 14 of file synccall.c.
Referenced by __synccall(), and handler().
context
void(*) context)
Definition at line 13 of file synccall.c.
Referenced by __gxx_personality_v0(), __synccall(), cag_option_fetch(), cag_option_find_by_letter(), cag_option_find_by_name(), cag_option_find_next(), cag_option_get(), cag_option_get_index(), cag_option_get_value(), cag_option_parse_access_letter(), cag_option_parse_access_name(), cag_option_parse_value(), cag_option_prepare(), cag_option_shift(), handler(), Tasking::Signal::HandleSignal(), ParseConfig(), SHA1_UpdateInt32(), and SHA1_UpdateString().
target_sem
sem_t target_sem static
Definition at line 14 of file synccall.c.
Referenced by __synccall(), and handler().
target_tid
int target_tid static
Definition at line 12 of file synccall.c.
Referenced by __synccall(), and handler().