Fennix: Userspace/apps/base/busybox/util-linux/fallocate.c File Reference
fallocate.c File Reference
#include "libbb.h"
Functions
int fallocate_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
fallocate_main()
int fallocate_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 75 of file fallocate.c.
 {
     const char *str_l;
     const char *str_o = "0";
     off_t ofs, len;
     unsigned opts;
     int fd;
     /* exactly one non-option arg */
     opts = getopt32(argv, "^" "l:o:" "\0" "=1", &str_l, &str_o);
     if (!(opts & 1))
         bb_show_usage();
     ofs = xatoull_sfx(str_o, kmg_i_suffixes);
     len = xatoull_sfx(str_l, kmg_i_suffixes);
     argv += optind;
     fd = xopen3(*argv, O_RDWR | O_CREAT, 0666);
     /* posix_fallocate has unusual method of returning error */
     /* maybe use Linux-specific fallocate(int fd, int mode, off_t offset, off_t len) instead? */
     if ((errno = posix_fallocate(fd, ofs, len)) != 0)
         bb_perror_msg_and_die("fallocate '%s'", *argv);
     /* util-linux also performs fsync(fd); */
     return EXIT_SUCCESS;
 }
References argv, bb_perror_msg_and_die(), bb_show_usage(), errno, EXIT_SUCCESS, fd, getopt32(), kmg_i_suffixes, len, O_CREAT, O_RDWR, off_t, optind, posix_fallocate(), and xopen3().