Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/m_config.h File Reference
m_config.h File Reference
#include "doomtype.h"
Functions
void M_LoadDefaults (void)
void M_SaveDefaults (void)
void M_SaveDefaultsAlternate (char *main, char *extra)
void M_SetConfigDir (char *dir)
void M_BindVariable (char *name, void *variable)
boolean M_SetVariable (char *name, char *value)
int M_GetIntVariable (char *name)
const char * M_GetStrVariable (char *name)
float M_GetFloatVariable (char *name)
void M_SetConfigFilenames (char *main_config, char *extra_config)
char * M_GetSaveGameDir (char *iwadname)
Variables
char * configdir
Function Documentation
M_BindVariable()
void M_BindVariable (char * name, void * variable)
Definition at line 1964 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     variable->location = location;
     variable->bound = true;
 }
References default_t::bound, GetDefaultForName(), and default_t::location.
Referenced by D_BindVariables(), I_BindJoystickVariables(), I_BindSoundVariables(), M_BindBaseControls(), M_BindChatControls(), M_BindHereticControls(), M_BindHexenControls(), M_BindMapControls(), M_BindMenuControls(), M_BindStrifeControls(), and M_BindWeaponControls().
M_GetFloatVariable()
float M_GetFloatVariable (char * name)
Definition at line 2025 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound
      || variable->type != DEFAULT_FLOAT)
     {
         return 0;
     }
     return *((float *) variable->location);
 }
References default_t::bound, DEFAULT_FLOAT, GetDefaultForName(), default_t::location, NULL, and default_t::type.
M_GetIntVariable()
int M_GetIntVariable (char * name)
Definition at line 1995 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound
      || (variable->type != DEFAULT_INT && variable->type != DEFAULT_INT_HEX))
     {
         return 0;
     }
     return *((int *) variable->location);
 }
References default_t::bound, DEFAULT_INT, DEFAULT_INT_HEX, GetDefaultForName(), default_t::location, NULL, and default_t::type.
M_GetSaveGameDir()
char* M_GetSaveGameDir (char * iwadname)
Definition at line 2087 of file m_config.c.
 {
     char *savegamedir;
 #if ORIGCODE
     char *topdir;
 #endif
     // If not "doing" a configuration directory (Windows), don't "do"
     // a savegame directory, either.
     if (!strcmp(configdir, ""))
     {
         savegamedir = strdup("");
     }
     else
     {
 #if ORIGCODE
         // ~/.chocolate-doom/savegames
         topdir = M_StringJoin(configdir, "savegame", NULL);
         M_MakeDirectory(topdir);
         // eg. ~/.chocolate-doom/savegames/doom2.wad/
         savegamedir = M_StringJoin(topdir, DIR_SEPARATOR_S, iwadname,
                                    DIR_SEPARATOR_S, NULL);
         M_MakeDirectory(savegamedir);
         free(topdir);
 #else
         savegamedir = M_StringJoin(configdir, DIR_SEPARATOR_S, ".savegame/", NULL);
         M_MakeDirectory(savegamedir);
         printf ("Using %s for savegames\n", savegamedir);
 #endif
     }
     return savegamedir;
 }
References configdir, DIR_SEPARATOR_S, free, M_MakeDirectory(), M_StringJoin(), NULL, printf, savegamedir, strcmp, and strdup().
Referenced by D_DoomMain().
M_GetStrVariable()
const char* M_GetStrVariable (char * name)
Definition at line 2010 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound
      || variable->type != DEFAULT_STRING)
     {
         return NULL;
     }
     return *((const char **) variable->location);
 }
References default_t::bound, DEFAULT_STRING, GetDefaultForName(), default_t::location, NULL, and default_t::type.
M_LoadDefaults()
void M_LoadDefaults (void)
Definition at line 1881 of file m_config.c.
 {
     int i;
     // check for a custom default file
     // @arg <file>
     // @vanilla
     //
     // Load main configuration from the specified file, instead of the
     // default.
     //
     i = M_CheckParmWithArgs("-config", 1);
     if (i)
     {
     doom_defaults.filename = myargv[i+1];
     printf ("   default file: %s\n",doom_defaults.filename);
     }
     else
     {
         doom_defaults.filename
             = M_StringJoin(configdir, default_main_config, NULL);
     }
     printf("saving config in %s\n", doom_defaults.filename);
     // @arg <file>
     //
     // Load additional configuration from the specified file, instead of
     // the default.
     //
     i = M_CheckParmWithArgs("-extraconfig", 1);
     if (i)
     {
         extra_defaults.filename = myargv[i+1];
         printf("        extra configuration file: %s\n",
                extra_defaults.filename);
     }
     else
     {
         extra_defaults.filename
             = M_StringJoin(configdir, default_extra_config, NULL);
     }
     LoadDefaultCollection(&doom_defaults);
     LoadDefaultCollection(&extra_defaults);
 }
References configdir, default_extra_config, default_main_config, doom_defaults, extra_defaults, default_collection_t::filename, i, LoadDefaultCollection(), M_CheckParmWithArgs(), M_StringJoin(), myargv, NULL, and printf.
Referenced by D_DoomMain().
M_SaveDefaults()
void M_SaveDefaults (void)
Definition at line 1846 of file m_config.c.
 {
     SaveDefaultCollection(&doom_defaults);
     SaveDefaultCollection(&extra_defaults);
 }
References doom_defaults, extra_defaults, and SaveDefaultCollection().
Referenced by D_DoomMain(), and M_SaveDefaultsAlternate().
M_SaveDefaultsAlternate()
void M_SaveDefaultsAlternate (char * main, char * extra)
Definition at line 1856 of file m_config.c.
 {
     char *orig_main;
     char *orig_extra;
     // Temporarily change the filenames
     orig_main = doom_defaults.filename;
     orig_extra = extra_defaults.filename;
     doom_defaults.filename = main;
     extra_defaults.filename = extra;
     M_SaveDefaults();
     // Restore normal filenames
     doom_defaults.filename = orig_main;
     extra_defaults.filename = orig_extra;
 }
References doom_defaults, extra_defaults, default_collection_t::filename, M_SaveDefaults(), and main().
M_SetConfigDir()
void M_SetConfigDir (char * dir)
Definition at line 2059 of file m_config.c.
 {
     // Use the directory that was passed, or find the default.
     if (dir != NULL)
     {
         configdir = dir;
     }
     else
     {
         configdir = GetDefaultConfigDir();
     }
     if (strcmp(configdir, "") != 0)
     {
         printf("Using %s for configuration and saves\n", configdir);
     }
     // Make the directory if it doesn't already exist:
     M_MakeDirectory(configdir);
 }
References configdir, GetDefaultConfigDir(), M_MakeDirectory(), NULL, printf, and strcmp.
Referenced by D_DoomMain().
M_SetConfigFilenames()
void M_SetConfigFilenames (char * main_config, char * extra_config)
Definition at line 1836 of file m_config.c.
 {
     default_main_config = main_config;
     default_extra_config = extra_config;
 }
References default_extra_config, and default_main_config.
Referenced by D_DoomMain().
M_SetVariable()
boolean M_SetVariable (char * name, char * value)
Definition at line 1977 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound)
     {
         return false;
     }
     SetVariable(variable, value);
     return true;
 }
References default_t::bound, GetDefaultForName(), NULL, SetVariable(), and value.
Variable Documentation
configdir
char* configdir extern
Definition at line 45 of file m_config.c.
Referenced by D_DoomMain(), M_GetSaveGameDir(), M_LoadDefaults(), and M_SetConfigDir().