Fennix: Userspace/musl/include/sys/shm.h File Reference
shm.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <sys/ipc.h>
#include <bits/shm.h>
Macros
#define __NEED_time_t
#define __NEED_size_t
#define __NEED_pid_t
#define SHM_R 0400
#define SHM_W 0200
#define SHM_RDONLY 010000
#define SHM_RND 020000
#define SHM_REMAP 040000
#define SHM_EXEC 0100000
#define SHM_LOCK 11
#define SHM_UNLOCK 12
#define SHM_STAT (13 | (IPC_STAT & 0x100))
#define SHM_INFO 14
#define SHM_STAT_ANY (15 | (IPC_STAT & 0x100))
#define SHM_DEST 01000
#define SHM_LOCKED 02000
#define SHM_HUGETLB 04000
#define SHM_NORESERVE 010000
#define SHM_HUGE_SHIFT 26
#define SHM_HUGE_MASK 0x3f
#define SHM_HUGE_64KB (16 << 26)
#define SHM_HUGE_512KB (19 << 26)
#define SHM_HUGE_1MB (20 << 26)
#define SHM_HUGE_2MB (21 << 26)
#define SHM_HUGE_8MB (23 << 26)
#define SHM_HUGE_16MB (24 << 26)
#define SHM_HUGE_32MB (25 << 26)
#define SHM_HUGE_256MB (28 << 26)
#define SHM_HUGE_512MB (29 << 26)
#define SHM_HUGE_1GB (30 << 26)
#define SHM_HUGE_2GB (31 << 26)
#define SHM_HUGE_16GB (34U << 26)
Typedefs
typedef unsigned long shmatt_t
Functions
void * shmat (int, const void *, int)
int shmctl (int, int, struct shmid_ds *)
int shmdt (const void *)
int shmget (key_t, size_t, int)
Macro Definition Documentation
__NEED_pid_t
#define __NEED_pid_t
Definition at line 12 of file shm.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 11 of file shm.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 10 of file shm.h.
SHM_DEST
#define SHM_DEST 01000
Definition at line 39 of file shm.h.
SHM_EXEC
#define SHM_EXEC 0100000
Definition at line 32 of file shm.h.
SHM_HUGE_16GB
#define SHM_HUGE_16GB (34U << 26)
Definition at line 57 of file shm.h.
SHM_HUGE_16MB
#define SHM_HUGE_16MB (24 << 26)
Definition at line 51 of file shm.h.
SHM_HUGE_1GB
#define SHM_HUGE_1GB (30 << 26)
Definition at line 55 of file shm.h.
SHM_HUGE_1MB
#define SHM_HUGE_1MB (20 << 26)
Definition at line 48 of file shm.h.
SHM_HUGE_256MB
#define SHM_HUGE_256MB (28 << 26)
Definition at line 53 of file shm.h.
SHM_HUGE_2GB
#define SHM_HUGE_2GB (31 << 26)
Definition at line 56 of file shm.h.
SHM_HUGE_2MB
#define SHM_HUGE_2MB (21 << 26)
Definition at line 49 of file shm.h.
SHM_HUGE_32MB
#define SHM_HUGE_32MB (25 << 26)
Definition at line 52 of file shm.h.
SHM_HUGE_512KB
#define SHM_HUGE_512KB (19 << 26)
Definition at line 47 of file shm.h.
SHM_HUGE_512MB
#define SHM_HUGE_512MB (29 << 26)
Definition at line 54 of file shm.h.
SHM_HUGE_64KB
#define SHM_HUGE_64KB (16 << 26)
Definition at line 46 of file shm.h.
SHM_HUGE_8MB
#define SHM_HUGE_8MB (23 << 26)
Definition at line 50 of file shm.h.
SHM_HUGE_MASK
#define SHM_HUGE_MASK 0x3f
Definition at line 45 of file shm.h.
SHM_HUGE_SHIFT
#define SHM_HUGE_SHIFT 26
Definition at line 44 of file shm.h.
SHM_HUGETLB
#define SHM_HUGETLB 04000
Definition at line 41 of file shm.h.
SHM_INFO
#define SHM_INFO 14
Definition at line 37 of file shm.h.
SHM_LOCK
#define SHM_LOCK 11
Definition at line 34 of file shm.h.
SHM_LOCKED
#define SHM_LOCKED 02000
Definition at line 40 of file shm.h.
SHM_NORESERVE
#define SHM_NORESERVE 010000
Definition at line 42 of file shm.h.
SHM_R
#define SHM_R 0400
Definition at line 26 of file shm.h.
SHM_RDONLY
#define SHM_RDONLY 010000
Definition at line 29 of file shm.h.
SHM_REMAP
#define SHM_REMAP 040000
Definition at line 31 of file shm.h.
SHM_RND
#define SHM_RND 020000
Definition at line 30 of file shm.h.
SHM_STAT
#define SHM_STAT (13 | (IPC_STAT & 0x100))
Definition at line 36 of file shm.h.
SHM_STAT_ANY
#define SHM_STAT_ANY (15 | (IPC_STAT & 0x100))
Definition at line 38 of file shm.h.
SHM_UNLOCK
#define SHM_UNLOCK 12
Definition at line 35 of file shm.h.
SHM_W
#define SHM_W 0200
Definition at line 27 of file shm.h.
Typedef Documentation
shmatt_t
typedef unsigned long shmatt_t
Definition at line 59 of file shm.h.
Function Documentation
shmat()
void* shmat (int id, const void * addr, int flag)
Definition at line 6 of file shmat.c.
 {
     return (void *)syscall(SYS_shmat, id, addr, flag);
 }
References addr, and syscall().
shmctl()
int shmctl (int id, int cmd, struct shmid_ds * buf)
Definition at line 10 of file shmctl.c.
 {
 #if IPC_TIME64
     struct shmid_ds out, *orig;
     if (cmd&IPC_TIME64) {
         out = (struct shmid_ds){0};
         orig = buf;
         buf = &out;
     }
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     struct shmid_ds tmp;
     if (cmd == IPC_SET) {
         tmp = *buf;
         tmp.shm_perm.mode *= 0x10000U;
         buf = &tmp;
     }
 #endif
 #ifndef SYS_ipc
     int r = __syscall(SYS_shmctl, id, IPC_CMD(cmd), buf);
 #else
     int r = __syscall(SYS_ipc, IPCOP_shmctl, id, IPC_CMD(cmd), 0, buf, 0);
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     if (r >= 0) switch (cmd | IPC_TIME64) {
     case IPC_STAT:
     case SHM_STAT:
     case SHM_STAT_ANY:
         buf->shm_perm.mode >>= 16;
     }
 #endif
 #if IPC_TIME64
     if (r >= 0 && (cmd&IPC_TIME64)) {
         buf = orig;
         *buf = out;
         IPC_HILO(buf, shm_atime);
         IPC_HILO(buf, shm_dtime);
         IPC_HILO(buf, shm_ctime);
     }
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), buf, IPC_CMD, IPC_HILO, IPC_SET, IPC_STAT, IPC_TIME64, IPCOP_shmctl, ipc_perm::mode, out(), shmid_ds::shm_atime, shmid_ds::shm_ctime, shmid_ds::shm_dtime, shmid_ds::shm_perm, SHM_STAT, and SHM_STAT_ANY.
shmdt()
int shmdt (const void * addr)
Definition at line 5 of file shmdt.c.
 {
 #ifndef SYS_ipc
     return syscall(SYS_shmdt, addr);
 #else
     return syscall(SYS_ipc, IPCOP_shmdt, 0, 0, 0, addr);
 #endif
 }
References addr, IPCOP_shmdt, and syscall().
shmget()
int shmget (key_t key, size_t size, int flag)
Definition at line 6 of file shmget.c.
 {
     if (size > PTRDIFF_MAX) size = SIZE_MAX;
 #ifndef SYS_ipc
     return syscall(SYS_shmget, key, size, flag);
 #else
     return syscall(SYS_ipc, IPCOP_shmget, key, size, flag);
 #endif
 }
References IPCOP_shmget, PTRDIFF_MAX, size, SIZE_MAX, and syscall().