Fennix Userspace: Userspace/apps/base/busybox/libbb/bb_pwd.c File Reference
bb_pwd.c File Reference
#include "libbb.h"
Functions
struct passwd *FAST_FUNC xgetpwnam (const char *name)
struct group *FAST_FUNC xgetgrnam (const char *name)
struct passwd *FAST_FUNC xgetpwuid (uid_t uid)
struct group *FAST_FUNC xgetgrgid (gid_t gid)
char *FAST_FUNC xuid2uname (uid_t uid)
char *FAST_FUNC xgid2group (gid_t gid)
char *FAST_FUNC uid2uname (uid_t uid)
char *FAST_FUNC gid2group (gid_t gid)
char *FAST_FUNC uid2uname_utoa (uid_t uid)
char *FAST_FUNC gid2group_utoa (gid_t gid)
long FAST_FUNC xuname2uid (const char *name)
long FAST_FUNC xgroup2gid (const char *name)
unsigned long FAST_FUNC get_ug_id (const char *s, long FAST_FUNC(*xname2id)(const char *))
Function Documentation
get_ug_id()
unsigned long FAST_FUNC get_ug_id (const char * s, long FAST_FUNC(*)(const char *) xname2id)
Definition at line 103 of file bb_pwd.c.
 {
     unsigned long r;
     r = bb_strtoul(s, NULL, 10);
     if (errno)
         return xname2id(s);
     return r;
 }
References bb_strtoul(), errno, NULL, and s.
Referenced by install_main(), and parse_chown_usergroup_or_die().
gid2group()
char* FAST_FUNC gid2group (gid_t gid)
Definition at line 69 of file bb_pwd.c.
 {
     struct group *gr = getgrgid(gid);
     return (gr) ? gr->gr_name : NULL;
 }
References getgrgid, gr, group::gr_name, and NULL.
Referenced by gid2group_utoa(), and print_group().
gid2group_utoa()
char* FAST_FUNC gid2group_utoa (gid_t gid)
Definition at line 81 of file bb_pwd.c.
 {
     char *name = gid2group(gid);
     return (name) ? name : utoa(gid);
 }
References gid2group(), and utoa().
Referenced by get_cached_groupname().
uid2uname()
char* FAST_FUNC uid2uname (uid_t uid)
Definition at line 63 of file bb_pwd.c.
 {
     struct passwd *pw = getpwuid(uid);
     return (pw) ? pw->pw_name : NULL;
 }
References getpwuid, NULL, pw, and passwd::pw_name.
Referenced by print_user(), and uid2uname_utoa().
uid2uname_utoa()
char* FAST_FUNC uid2uname_utoa (uid_t uid)
Definition at line 75 of file bb_pwd.c.
 {
     char *name = uid2uname(uid);
     return (name) ? name : utoa(uid);
 }
References uid2uname(), and utoa().
Referenced by get_cached_username(), and logger_main().
xgetgrgid()
struct group* FAST_FUNC xgetgrgid (gid_t gid)
Definition at line 42 of file bb_pwd.c.
 {
     struct group *gr = getgrgid(gid);
     if (!gr)
         bb_error_msg_and_die("unknown gid %u", (unsigned)gid);
     return gr;
 }
References bb_error_msg_and_die(), getgrgid, and gr.
Referenced by xgid2group().
xgetgrnam()
struct group* FAST_FUNC xgetgrnam (const char * name)
Definition at line 25 of file bb_pwd.c.
 {
     struct group *gr = getgrnam(name);
     if (!gr)
         bb_error_msg_and_die("unknown group %s", name);
     return gr;
 }
References bb_error_msg_and_die(), getgrnam, and gr.
Referenced by addgroup_main(), deluser_main(), and xgroup2gid().
xgetpwnam()
struct passwd* FAST_FUNC xgetpwnam (const char * name)
Definition at line 17 of file bb_pwd.c.
 {
     struct passwd *pw = getpwnam(name);
     if (!pw)
         bb_error_msg_and_die("unknown user %s", name);
     return pw;
 }
References bb_error_msg_and_die(), getpwnam, and pw.
Referenced by crontab_main(), deluser_main(), id_main(), passwd_main(), su_main(), and xuname2uid().
xgetpwuid()
struct passwd* FAST_FUNC xgetpwuid (uid_t uid)
Definition at line 33 of file bb_pwd.c.
 {
     /* Note: used in nofork applets (whoami), be careful not to leak anything */
     struct passwd *pw = getpwuid(uid);
     if (!pw)
         bb_error_msg_and_die("unknown uid %u", (unsigned)uid);
     return pw;
 }
References bb_error_msg_and_die(), getpwuid, and pw.
Referenced by crontab_main(), start_stop_daemon_main(), vlock_main(), and xuid2uname().
xgid2group()
char* FAST_FUNC xgid2group (gid_t gid)
Definition at line 57 of file bb_pwd.c.
 {
     struct group *gr = xgetgrgid(gid);
     return gr->gr_name;
 }
References gr, group::gr_name, and xgetgrgid().
xgroup2gid()
long FAST_FUNC xgroup2gid (const char * name)
Definition at line 95 of file bb_pwd.c.
 {
     struct group *mygroup;
     mygroup = xgetgrnam(name);
     return mygroup->gr_gid;
 }
References group::gr_gid, and xgetgrnam().
Referenced by adduser_main(), install_main(), parse_chown_usergroup_or_die(), parse_params(), and tunctl_main().
xuid2uname()
char* FAST_FUNC xuid2uname (uid_t uid)
Definition at line 50 of file bb_pwd.c.
 {
     /* Note: used in nofork applets (whoami), be careful not to leak anything */
     struct passwd *pw = xgetpwuid(uid);
     return pw->pw_name;
 }
References pw, passwd::pw_name, and xgetpwuid().
Referenced by lpqr_main(), passwd_main(), sendmail_main(), and whoami_main().
xuname2uid()
long FAST_FUNC xuname2uid (const char * name)
Definition at line 87 of file bb_pwd.c.
 {
     struct passwd *myuser;
     myuser = xgetpwnam(name);
     return myuser->pw_uid;
 }
References passwd::pw_uid, and xgetpwnam().
Referenced by addgroup_main(), chpasswd_main(), install_main(), parse_chown_usergroup_or_die(), parse_params(), pstree_main(), start_stop_daemon_main(), and tunctl_main().