Fennix: Userspace/apps/base/bash/execute_cmd.c File Reference
execute_cmd.c File Reference
#include "config.h"
#include <stdio.h>
#include "chartypes.h"
#include "bashtypes.h"
#include "filecntl.h"
#include "posixstat.h"
#include <signal.h>
#include "posixtime.h"
#include <errno.h>
#include "bashansi.h"
#include "bashintl.h"
#include "memalloc.h"
#include "shell.h"
#include <y.tab.h>
#include "parser.h"
#include "flags.h"
#include "builtins.h"
#include "hashlib.h"
#include "jobs.h"
#include "execute_cmd.h"
#include "findcmd.h"
#include "redir.h"
#include "trap.h"
#include "pathexp.h"
#include "hashcmd.h"
#include "builtins/common.h"
#include "builtins/builtext.h"
#include "builtins/getopt.h"
#include <glob/strmatch.h>
#include <tilde/tilde.h>
Macros
#define NEED_FPURGE_DECL
#define NEED_SH_SETLINEBUF_DECL
#define SET_LINE_NUMBER(v)
#define GET_LINE_NUMBER()
#define FD_BITMAP_DEFAULT_SIZE 32
#define DESCRIBE_PID(pid) do { if (interactive) describe_pid (pid); } while (0)
#define REAP()
#define EXIT_CASE() goto exit_case_command
#define CMD_WHILE 0
#define CMD_UNTIL 1
#define RETURN_NOT_COMMAND() do { if (typep) *typep = 0; return words; } while (0)
#define NOTFOUND_HOOK "command_not_found_handle"
#define STRINGCHAR(ind) (ind < sample_len && !whitespace (sample[ind]) && sample[ind] != '\n')
#define WHITECHAR(ind) (ind < sample_len && whitespace (sample[ind]))
#define SETOSTYPE(x)
#define HASH_BANG_BUFSIZ 128
#define READ_SAMPLE_BUF(file, buf, len)
Functions
int close PARAMS ((int))
static void close_pipes PARAMS ((int, int))
static void bind_lastarg PARAMS ((char *))
static int shell_control_structure PARAMS ((enum command_type))
static void cleanup_redirects PARAMS ((REDIRECT *))
static int execute_for_command PARAMS ((FOR_COM *))
static int execute_case_command PARAMS ((CASE_COM *))
static int execute_while_command PARAMS ((WHILE_COM *))
static int execute_while_or_until PARAMS ((WHILE_COM *, int))
static int execute_if_command PARAMS ((IF_COM *))
static int execute_null_command PARAMS ((REDIRECT *, int, int, int))
static void fix_assignment_words PARAMS ((WORD_LIST *))
static int execute_simple_command PARAMS ((SIMPLE_COM *, int, int, int, struct fd_bitmap *))
static int execute_builtin PARAMS ((sh_builtin_func_t *, WORD_LIST *, int, int))
static int execute_function PARAMS ((SHELL_VAR *, WORD_LIST *, int, struct fd_bitmap *, int, int))
static int execute_builtin_or_function PARAMS ((WORD_LIST *, sh_builtin_func_t *, SHELL_VAR *, REDIRECT *, struct fd_bitmap *, int))
static void execute_subshell_builtin_or_function PARAMS ((WORD_LIST *, REDIRECT *, sh_builtin_func_t *, SHELL_VAR *, int, int, int, struct fd_bitmap *, int))
static int execute_disk_command PARAMS ((WORD_LIST *, REDIRECT *, char *, int, int, int, struct fd_bitmap *, int))
static char *getinterp PARAMS ((char *, int, int *))
static void initialize_subshell PARAMS ((void))
static int execute_in_subshell PARAMS ((COMMAND *, int, int, int, struct fd_bitmap *))
static int execute_intern_function PARAMS ((WORD_DESC *, FUNCTION_DEF *))
struct fd_bitmap * new_fd_bitmap (int size)
void dispose_fd_bitmap (struct fd_bitmap *fdbp)
void close_fd_bitmap (struct fd_bitmap *fdbp)
int executing_line_number ()
int execute_command (COMMAND *command)
static int shell_control_structure (enum command_type type)
static void cleanup_redirects (REDIRECT *list)
void undo_partial_redirects ()
void dispose_exec_redirects ()
void dispose_partial_redirects ()
void async_redirect_stdin ()
int execute_command_internal (COMMAND *command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap *fds_to_close)
static int execute_in_subshell (COMMAND *command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap *fds_to_close)
static void restore_stdin (int s)
static void lastpipe_cleanup (int s)
static int execute_pipeline (COMMAND *command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap *fds_to_close)
static int execute_connection (COMMAND *command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap *fds_to_close)
static int execute_for_command (FOR_COM *for_command)
static int execute_case_command (CASE_COM *case_command)
static int execute_while_command (WHILE_COM *while_command)
static int execute_until_command (WHILE_COM *while_command)
static int execute_while_or_until (WHILE_COM *while_command, int type)
static int execute_if_command (IF_COM *if_command)
static void bind_lastarg (char *arg)
static int execute_null_command (REDIRECT *redirects, int pipe_in, int pipe_out, int async)
static void fix_assignment_words (WORD_LIST *words)
static WORD_LIST * check_command_builtin (WORD_LIST *words, int *typep)
static int is_dirname (char *pathname)
static int execute_simple_command (SIMPLE_COM *simple_command, int pipe_in, int pipe_out, int async, struct fd_bitmap *fds_to_close)
static int builtin_status (int result)
static int execute_builtin (sh_builtin_func_t *builtin, WORD_LIST *words, int flags, int subshell)
static void maybe_restore_getopt_state (sh_getopt_state_t *gs)
static int execute_function (SHELL_VAR *var, WORD_LIST *words, int flags, struct fd_bitmap *fds_to_close, int async, int subshell)
int execute_shell_function (SHELL_VAR *var, WORD_LIST *words)
static void execute_subshell_builtin_or_function (WORD_LIST *words, REDIRECT *redirects, sh_builtin_func_t *builtin, SHELL_VAR *var, int pipe_in, int pipe_out, int async, struct fd_bitmap *fds_to_close, int flags)
static int execute_builtin_or_function (WORD_LIST *words, sh_builtin_func_t *builtin, SHELL_VAR *var, REDIRECT *redirects, struct fd_bitmap *fds_to_close, int flags)
void setup_async_signals ()
static int execute_disk_command (WORD_LIST *words, REDIRECT *redirects, char *command_line, int pipe_in, int pipe_out, int async, struct fd_bitmap *fds_to_close, int cmdflags)
static char * getinterp (char *sample, int sample_len, int *endp)
static int execute_shell_script (char *sample, int sample_len, char *command, char **args, char **env)
static void initialize_subshell ()
int shell_execve (char *command, char **args, char **env)
static int execute_intern_function (WORD_DESC *name, FUNCTION_DEF *funcdef)
static void close_pipes (int in, int out)
static void dup_error (int oldd, int newd)
static void do_piping (int pipe_in, int pipe_out)
Variables
int errno
int command_string_index
char * the_printed_command
time_t shell_start_time
int stdin_redir
char * this_command_name
char * the_printed_command_except_trap
int return_catch_flag
int return_catch_value
procenv_t return_catch
volatile int last_command_exit_value
int last_command_exit_signal
int builtin_ignoring_errexit = 0
REDIRECT * redirection_undo_list = (REDIRECT *)NULL
REDIRECT * exec_redirection_undo_list = (REDIRECT *)NULL
int executing_builtin = 0
int executing_list = 0
int comsub_ignore_return = 0
int subshell_environment
int subshell_level = 0
SHELL_VAR * this_shell_function
int match_ignore_case = 0
int executing_command_builtin = 0
struct stat SB
static int special_builtin_failed
static COMMAND * currently_executing_command
static int function_line_number
static int showing_function_line
static int connection_count
int line_number_for_err_trap
int funcnest = 0
int funcnest_max = 0
int evalnest = 0
int evalnest_max = EVALNEST_MAX
int sourcenest = 0
int sourcenest_max = SOURCENEST_MAX
volatile int from_return_trap = 0
int lastpipe_opt = 0
struct fd_bitmap * current_fds_to_close = (struct fd_bitmap *)NULL
Macro Definition Documentation
CMD_UNTIL
#define CMD_UNTIL 1
Definition at line 3657 of file execute_cmd.c.
CMD_WHILE
#define CMD_WHILE 0
Definition at line 3656 of file execute_cmd.c.
DESCRIBE_PID
#define DESCRIBE_PID (pid) do { if (interactive) describe_pid (pid); } while (0)
Definition at line 558 of file execute_cmd.c.
EXIT_CASE
#define EXIT_CASE () goto exit_case_command
FD_BITMAP_DEFAULT_SIZE
#define FD_BITMAP_DEFAULT_SIZE 32
Definition at line 316 of file execute_cmd.c.
GET_LINE_NUMBER
#define GET_LINE_NUMBER ()
Value:
  (signal_in_progress (ERROR_TRAP) && running_trap == ERROR_TRAP+1) \
    ? line_number_for_err_trap \
    : executing_line_number ()
Definition at line 295 of file execute_cmd.c.
HASH_BANG_BUFSIZ
#define HASH_BANG_BUFSIZ 128
Definition at line 5929 of file execute_cmd.c.
NEED_FPURGE_DECL
#define NEED_FPURGE_DECL
Definition at line 60 of file execute_cmd.c.
NEED_SH_SETLINEBUF_DECL
#define NEED_SH_SETLINEBUF_DECL
Definition at line 61 of file execute_cmd.c.
NOTFOUND_HOOK
#define NOTFOUND_HOOK "command_not_found_handle"
Definition at line 5582 of file execute_cmd.c.
READ_SAMPLE_BUF
#define READ_SAMPLE_BUF (file, buf, len)
Value:
  do \
    { \
      fd = open(file, O_RDONLY); \
      if (fd >= 0) \
    { \
      len = read (fd, buf, HASH_BANG_BUFSIZ); \
      close (fd); \
    } \
      else \
    len = -1; \
    } \
  while (0)
Definition at line 5931 of file execute_cmd.c.
REAP
#define REAP ()
Value:
  do \
    { \
      if (job_control == 0 || interactive_shell == 0) \
    reap_dead_jobs (); \
    } \
  while (0)
Definition at line 2858 of file execute_cmd.c.
RETURN_NOT_COMMAND
#define RETURN_NOT_COMMAND () do { if (typep) *typep = 0; return words; } while (0)
Definition at line 4294 of file execute_cmd.c.
SET_LINE_NUMBER
#define SET_LINE_NUMBER (v)
Value:
do { \
  line_number = v; \
  if (signal_in_progress (ERROR_TRAP) == 0 && running_trap != (ERROR_TRAP + 1)) \
    line_number_for_err_trap = line_number; \
} while (0)
Definition at line 285 of file execute_cmd.c.
SETOSTYPE
#define SETOSTYPE (x)
Definition at line 5926 of file execute_cmd.c.
STRINGCHAR
#define STRINGCHAR (ind) (ind < sample_len && !whitespace (sample[ind]) && sample[ind] != '\n')
Definition at line 5775 of file execute_cmd.c.
WHITECHAR
#define WHITECHAR (ind) (ind < sample_len && whitespace (sample[ind]))
Definition at line 5777 of file execute_cmd.c.
Function Documentation
async_redirect_stdin()
void async_redirect_stdin ()
Definition at line 544 of file execute_cmd.c.
 {
   int fd;
   fd = open ("/dev/null", O_RDONLY);
   if (fd > 0)
     {
       dup2 (fd, 0);
       close (fd);
     }
   else if (fd < 0)
     internal_error (_("cannot redirect standard input from /dev/null: %s"), strerror (errno));
 }
References _, close(), dup2(), errno, fd, internal_error(), O_RDONLY, open(), and strerror().
Referenced by execute_disk_command(), execute_in_subshell(), and execute_simple_command().
bind_lastarg()
static void bind_lastarg (char * arg) static
Definition at line 4071 of file execute_cmd.c.
 {
   SHELL_VAR *var;
   if (arg == 0)
     arg = "";
   var = bind_variable ("_", arg, 0);
   if (var)
     VUNSETATTR (var, att_exported);
 }
References att_exported, bind_variable(), and VUNSETATTR.
Referenced by execute_simple_command().
builtin_status()
static int builtin_status (int result) static
Definition at line 4832 of file execute_cmd.c.
 {
   int r;
   switch (result)
     {
     case EX_USAGE:
     case EX_BADSYNTAX:
       r = EX_BADUSAGE;
       break;
     case EX_REDIRFAIL:
     case EX_BADASSIGN:
     case EX_EXPFAIL:
       r = EXECUTION_FAILURE;
       break;
     default:
       /* other special exit statuses not yet defined */
       r = (result > EX_SHERRBASE) ? EXECUTION_FAILURE : EXECUTION_SUCCESS;
       break;
     }
   return (r);
 }
References EX_BADASSIGN, EX_BADSYNTAX, EX_BADUSAGE, EX_EXPFAIL, EX_REDIRFAIL, EX_SHERRBASE, EX_USAGE, EXECUTION_FAILURE, and EXECUTION_SUCCESS.
Referenced by execute_simple_command().
check_command_builtin()
static WORD_LIST* check_command_builtin (WORD_LIST * words, int * typep) static
Definition at line 4303 of file execute_cmd.c.
 {
   int type;
   WORD_LIST *w;
   w = words->next;
   type = 1;
   if (w && ISOPTION (w->word->word, 'p'))   /* command -p */
     {
 #if defined (RESTRICTED_SHELL)
       if (restricted)
         RETURN_NOT_COMMAND();
 #endif
       w = w->next;
       type = 2;
     }
   if (w && ISOPTION (w->word->word, '-'))   /* command [-p] -- */
     w = w->next;
   else if (w && w->word->word[0] == '-')    /* any other option */
     RETURN_NOT_COMMAND();
   if (w == 0 || w->word->word == 0)     /* must have a command_name */
     RETURN_NOT_COMMAND();
   if (typep)
     *typep = type;
   return w;
 }
References ISOPTION, word_list::next, RETURN_NOT_COMMAND, type, and w.
Referenced by execute_simple_command().
cleanup_redirects()
static void cleanup_redirects (REDIRECT * list) static
Definition at line 465 of file execute_cmd.c.
 {
   do_redirections (list, RX_ACTIVE);
   dispose_redirects (list);
 }
References dispose_redirects(), do_redirections(), list(), and RX_ACTIVE.
Referenced by execute_builtin_or_function(), execute_command_internal(), execute_null_command(), and undo_partial_redirects().
close_fd_bitmap()
void close_fd_bitmap (struct fd_bitmap * fdbp)
Definition at line 350 of file execute_cmd.c.
 {
   register int i;
   if (fdbp)
     {
       for (i = 0; i < fdbp->size; i++)
     if (fdbp->bitmap[i])
       {
         close (i);
         fdbp->bitmap[i] = 0;
       }
     }
 }
References fd_bitmap::bitmap, close(), i, and fd_bitmap::size.
Referenced by execute_disk_command(), execute_in_subshell(), execute_pipeline(), execute_simple_command(), and execute_subshell_builtin_or_function().
close_pipes()
static void close_pipes (int in, int out) static
Definition at line 6175 of file execute_cmd.c.
 {
   if (in >= 0)
     close (in);
   if (out >= 0)
     close (out);
 }
References close(), and out().
Referenced by execute_command_internal(), execute_disk_command(), execute_null_command(), and execute_simple_command().
dispose_exec_redirects()
void dispose_exec_redirects ()
Definition at line 493 of file execute_cmd.c.
 {
   if (exec_redirection_undo_list)
     {
       dispose_redirects (exec_redirection_undo_list);
       exec_redirection_undo_list = (REDIRECT *)NULL;
     }
 }
References dispose_redirects(), exec_redirection_undo_list, and NULL.
Referenced by do_redirections(), execute_builtin_or_function(), and execute_command_internal().
dispose_fd_bitmap()
void dispose_fd_bitmap (struct fd_bitmap * fdbp)
Definition at line 342 of file execute_cmd.c.
 {
   FREE (fdbp->bitmap);
   free (fdbp);
 }
References fd_bitmap::bitmap, FREE, and free.
Referenced by execute_command(), execute_pipeline(), execute_shell_function(), and parse_and_execute().
dispose_partial_redirects()
void dispose_partial_redirects ()
Definition at line 503 of file execute_cmd.c.
 {
   if (redirection_undo_list)
     {
       dispose_redirects (redirection_undo_list);
       redirection_undo_list = (REDIRECT *)NULL;
     }
 }
References dispose_redirects(), NULL, and redirection_undo_list.
do_piping()
static void do_piping (int pipe_in, int pipe_out) static
Definition at line 6194 of file execute_cmd.c.
 {
   if (pipe_in != NO_PIPE)
     {
       if (dup2 (pipe_in, 0) < 0)
     dup_error (pipe_in, 0);
       if (pipe_in > 0)
     close (pipe_in);
 #ifdef __CYGWIN__
       /* Let stdio know the fd may have changed from text to binary mode. */
       freopen (NULL, "r", stdin);
 #endif /* __CYGWIN__ */
     }
   if (pipe_out != NO_PIPE)
     {
       if (pipe_out != REDIRECT_BOTH)
     {
       if (dup2 (pipe_out, 1) < 0)
         dup_error (pipe_out, 1);
       if (pipe_out == 0 || pipe_out > 1)
         close (pipe_out);
     }
       else
     {
       if (dup2 (1, 2) < 0)
         dup_error (1, 2);
     }
 #ifdef __CYGWIN__
       /* Let stdio know the fd may have changed from text to binary mode, and
      make sure to preserve stdout line buffering. */
       freopen (NULL, "w", stdout);
       sh_setlinebuf (stdout);
 #endif /* __CYGWIN__ */
     }
 }
References close(), dup2(), dup_error(), freopen(), NO_PIPE, NULL, REDIRECT_BOTH, sh_setlinebuf(), stdin, and stdout.
Referenced by execute_disk_command(), execute_in_subshell(), execute_null_command(), execute_pipeline(), execute_simple_command(), and execute_subshell_builtin_or_function().
dup_error()
static void dup_error (int oldd, int newd) static
Definition at line 6185 of file execute_cmd.c.
 {
   sys_error (_("cannot duplicate fd %d to fd %d"), oldd, newd);
 }
References _, and sys_error().
Referenced by do_piping().
execute_builtin()
static int execute_builtin (sh_builtin_func_t * builtin, WORD_LIST * words, int flags, int subshell) static
Definition at line 4857 of file execute_cmd.c.
 {
   int result, eval_unwind, ignexit_flag;
   int isbltinenv, should_keep;
   char *error_trap;
   error_trap = 0;
   should_keep = 0;
   /* The eval builtin calls parse_and_execute, which does not know about
      the setting of flags, and always calls the execution functions with
      flags that will exit the shell on an error if -e is set.  If the
      eval builtin is being called, and we're supposed to ignore the exit
      value of the command, we turn the -e flag off ourselves and disable
      the ERR trap, then restore them when the command completes.  This is
      also a problem (as below) for the command and source/. builtins. */
   if (subshell == 0 && (flags & CMD_IGNORE_RETURN) &&
     (builtin == eval_builtin || (flags & CMD_COMMAND_BUILTIN) || builtin == source_builtin))
     {
       begin_unwind_frame ("eval_builtin");
       unwind_protect_int (exit_immediately_on_error);
       unwind_protect_int (builtin_ignoring_errexit);
       error_trap = TRAP_STRING (ERROR_TRAP);
       if (error_trap)
     {
       error_trap = savestring (error_trap);
       add_unwind_protect (xfree, error_trap);
       add_unwind_protect (set_error_trap, error_trap);
       restore_default_signal (ERROR_TRAP);
     }
       exit_immediately_on_error = 0;
       ignexit_flag = builtin_ignoring_errexit;
       builtin_ignoring_errexit = 1;
       eval_unwind = 1;
     }
   else
     eval_unwind = 0;
   /* The temporary environment for a builtin is supposed to apply to
      all commands executed by that builtin.  Currently, this is a
      problem only with the `unset', `source' and `eval' builtins.
      `mapfile' is a special case because it uses evalstring (same as
      eval or source) to run its callbacks. */
   /* SHOULD_KEEP is for the pop_scope call below; it only matters when
      posixly_correct is set, but we should propagate the temporary environment
      to the enclosing environment only for special builtins. */
   isbltinenv = (builtin == source_builtin || builtin == eval_builtin || builtin == unset_builtin || builtin == mapfile_builtin);
   should_keep = isbltinenv && builtin != mapfile_builtin;
 #if defined (HISTORY) && defined (READLINE)
   if (builtin == fc_builtin || builtin == read_builtin)
     {
       isbltinenv = 1;
       should_keep = 0;
     }
 #endif
   if (isbltinenv)
     {
       if (subshell == 0)
     begin_unwind_frame ("builtin_env");
       if (temporary_env)
     {
       push_scope (VC_BLTNENV, temporary_env);
       if (flags & CMD_COMMAND_BUILTIN)
         should_keep = 0;
       if (subshell == 0)
         add_unwind_protect (pop_scope, should_keep ? "1" : 0);
           temporary_env = (HASH_TABLE *)NULL;
     }
     }
   if (subshell == 0 && builtin == eval_builtin)
     {
       if (evalnest_max > 0 && evalnest >= evalnest_max)
     {
       internal_error (_("eval: maximum eval nesting level exceeded (%d)"), evalnest);
       evalnest = 0;
       jump_to_top_level (DISCARD);
     }
       unwind_protect_int (evalnest);
       /* The test for subshell == 0 above doesn't make a difference */
       evalnest++;   /* execute_subshell_builtin_or_function sets this to 0 */
     }
   else if (subshell == 0 && builtin == source_builtin)
     {
       if (sourcenest_max > 0 && sourcenest >= sourcenest_max)
     {
       internal_error (_("%s: maximum source nesting level exceeded (%d)"), this_command_name, sourcenest);
       sourcenest = 0;
       jump_to_top_level (DISCARD);
     }
       unwind_protect_int (sourcenest);
       /* The test for subshell == 0 above doesn't make a difference */
       sourcenest++; /* execute_subshell_builtin_or_function sets this to 0 */
     }
   /* `return' does a longjmp() back to a saved environment in execute_function.
      If a variable assignment list preceded the command, and the shell is
      running in POSIX mode, we need to merge that into the shell_variables
      table, since `return' is a POSIX special builtin. We don't do this if
      it's being run by the `command' builtin, since that's supposed to inhibit
      the special builtin properties. */
   if (posixly_correct && subshell == 0 && builtin == return_builtin && (flags & CMD_COMMAND_BUILTIN) == 0 && temporary_env)
     {
       begin_unwind_frame ("return_temp_env");
       add_unwind_protect (merge_temporary_env, (char *)NULL);
     }
   executing_builtin++;
   executing_command_builtin |= builtin == command_builtin;
   result = ((*builtin) (words->next));
   /* This shouldn't happen, but in case `return' comes back instead of
      longjmp'ing, we need to unwind. */
   if (posixly_correct && subshell == 0 && builtin == return_builtin && temporary_env)
     discard_unwind_frame ("return_temp_env");
   if (subshell == 0 && isbltinenv)
     run_unwind_frame ("builtin_env");
   if (eval_unwind)
     {
       builtin_ignoring_errexit = ignexit_flag;
       exit_immediately_on_error = builtin_ignoring_errexit ? 0 : errexit_flag;
       if (error_trap)
     {
       set_error_trap (error_trap);
       free (error_trap);
     }
       discard_unwind_frame ("eval_builtin");
     }
   return (result);
 }
References _, add_unwind_protect(), begin_unwind_frame(), builtin_ignoring_errexit, CMD_COMMAND_BUILTIN, CMD_IGNORE_RETURN, DISCARD, discard_unwind_frame(), errexit_flag, ERROR_TRAP, evalnest, evalnest_max, executing_builtin, executing_command_builtin, exit_immediately_on_error, flags, free, internal_error(), jump_to_top_level(), merge_temporary_env(), word_list::next, NULL, pop_scope(), posixly_correct, push_scope(), restore_default_signal(), run_unwind_frame(), savestring(), set_error_trap(), sourcenest, sourcenest_max, temporary_env, this_command_name, TRAP_STRING, unwind_protect_int, VC_BLTNENV, and xfree.
Referenced by execute_builtin_or_function(), and execute_subshell_builtin_or_function().
execute_builtin_or_function()
static int execute_builtin_or_function (WORD_LIST * words, sh_builtin_func_t * builtin, SHELL_VAR * var, REDIRECT * redirects, struct fd_bitmap * fds_to_close, int flags) static
Definition at line 5428 of file execute_cmd.c.
 {
   int result;
   REDIRECT *saved_undo_list;
 #if defined (PROCESS_SUBSTITUTION)
   int ofifo, nfifo, osize;
   void *ofifo_list;
 #endif
 #if defined (PROCESS_SUBSTITUTION)
   begin_unwind_frame ("saved_fifos");
   /* If we return, we longjmp and don't get a chance to restore the old
      fifo list, so we add an unwind protect to free it */
   ofifo = num_fifos ();
   ofifo_list = copy_fifo_list (&osize);
   if (ofifo_list)
     add_unwind_protect (xfree, ofifo_list);
 #endif
   if (do_redirections (redirects, RX_ACTIVE|RX_UNDOABLE) != 0)
     {
       undo_partial_redirects ();
       dispose_exec_redirects ();
 #if defined (PROCESS_SUBSTITUTION)
       free (ofifo_list);
 #endif
       return (EX_REDIRFAIL);    /* was EXECUTION_FAILURE */
     }
   saved_undo_list = redirection_undo_list;
   /* Calling the "exec" builtin changes redirections forever. */
   if (builtin == exec_builtin)
     {
       dispose_redirects (saved_undo_list);
       saved_undo_list = exec_redirection_undo_list;
       exec_redirection_undo_list = (REDIRECT *)NULL;
     }
   else
     dispose_exec_redirects ();
   if (saved_undo_list)
     {
       begin_unwind_frame ("saved-redirects");
       add_unwind_protect (cleanup_redirects, (char *)saved_undo_list);
     }
   redirection_undo_list = (REDIRECT *)NULL;
   if (builtin)
     result = execute_builtin (builtin, words, flags, 0);
   else
     result = execute_function (var, words, flags, fds_to_close, 0, 0);
   /* We do this before undoing the effects of any redirections. */
   fflush (stdout);
   fpurge (stdout);
   if (ferror (stdout))
     clearerr (stdout);
   /* If we are executing the `command' builtin, but this_shell_builtin is
      set to `exec_builtin', we know that we have something like
      `command exec [redirection]', since otherwise `exec' would have
      overwritten the shell and we wouldn't get here.  In this case, we
      want to behave as if the `command' builtin had not been specified
      and preserve the redirections. */
   if (builtin == command_builtin && this_shell_builtin == exec_builtin)
     {
       int discard;
       discard = 0;
       if (saved_undo_list)
     {
       dispose_redirects (saved_undo_list);
       discard = 1;
     }
       redirection_undo_list = exec_redirection_undo_list;
       saved_undo_list = exec_redirection_undo_list = (REDIRECT *)NULL;
       if (discard)
     discard_unwind_frame ("saved-redirects");
     }
   if (saved_undo_list)
     {
       redirection_undo_list = saved_undo_list;
       discard_unwind_frame ("saved-redirects");
     }
   undo_partial_redirects ();
 #if defined (PROCESS_SUBSTITUTION)
   /* Close any FIFOs created by this builtin or function. */
   nfifo = num_fifos ();
   if (nfifo > ofifo)
     close_new_fifos (ofifo_list, osize);
   if (ofifo_list)
     free (ofifo_list);
   discard_unwind_frame ("saved_fifos");
 #endif
   return (result);
 }
References add_unwind_protect(), begin_unwind_frame(), cleanup_redirects(), clearerr(), discard_unwind_frame(), dispose_exec_redirects(), dispose_redirects(), do_redirections(), EX_REDIRFAIL, exec_builtin, exec_redirection_undo_list, execute_builtin(), execute_function(), ferror, fflush(), flags, fpurge(), free, NULL, redirection_undo_list, RX_ACTIVE, RX_UNDOABLE, stdout, this_shell_builtin, undo_partial_redirects(), and xfree.
Referenced by execute_simple_command().
execute_case_command()
static int execute_case_command (CASE_COM * case_command) static
Definition at line 3532 of file execute_cmd.c.
 {
   register WORD_LIST *list;
   WORD_LIST *wlist, *es;
   PATTERN_LIST *clauses;
   char *word, *pattern;
   int retval, match, ignore_return, save_line_number, qflags;
   save_line_number = line_number;
   line_number = case_command->line;
   command_string_index = 0;
   print_case_command_head (case_command);
   if (echo_command_at_execute)
     xtrace_print_case_command_head (case_command);
 #if 0
   if (signal_in_progress (DEBUG_TRAP) == 0 && (this_command_name == 0 || (STREQ (this_command_name, "trap") == 0)))
 #else
   if (signal_in_progress (DEBUG_TRAP) == 0 && running_trap == 0)
 #endif
     {
       FREE (the_printed_command_except_trap);
       the_printed_command_except_trap = savestring (the_printed_command);
     }
   retval = run_debug_trap();
 #if defined (DEBUGGER)
   /* In debugging mode, if the DEBUG trap returns a non-zero status, we
      skip the command. */
   if (debugging_mode && retval != EXECUTION_SUCCESS)
     {
       line_number = save_line_number;
       return (EXECUTION_SUCCESS);
     }
 #endif
   /* Use the same expansions (the ones POSIX specifies) as the patterns;
      dequote the resulting string (as POSIX specifies) since the quotes in
      patterns are handled specially below. We have to do it in this order
      because we're not supposed to perform word splitting. */
   wlist = expand_word_leave_quoted (case_command->word, 0);
   if (wlist)
     {
       char *t;
       t = string_list (wlist);
       word = dequote_string (t);
       free (t);
     }
   else
     word = savestring ("");
   dispose_words (wlist);
   retval = EXECUTION_SUCCESS;
   ignore_return = case_command->flags & CMD_IGNORE_RETURN;
   begin_unwind_frame ("case");
   add_unwind_protect (xfree, word);
 #define EXIT_CASE()  goto exit_case_command
   for (clauses = case_command->clauses; clauses; clauses = clauses->next)
     {
       QUIT;
       for (list = clauses->patterns; list; list = list->next)
     {
       es = expand_word_leave_quoted (list->word, 0);
       if (es && es->word && es->word->word && *(es->word->word))
         {
           /* Convert quoted null strings into empty strings. */
           qflags = QGLOB_CVTNULL;
           /* We left CTLESC in place quoting CTLESC and CTLNUL after the
              call to expand_word_leave_quoted; tell quote_string_for_globbing
              to remove those here. This works for both unquoted portions of
          the word (which call quote_escapes) and quoted portions
          (which call quote_string). */
           qflags |= QGLOB_CTLESC;
           pattern = quote_string_for_globbing (es->word->word, qflags);
         }
       else
         {
           pattern = (char *)xmalloc (1);
           pattern[0] = '\0';
         }
       /* Since the pattern does not undergo quote removal (as per
          Posix.2, section 3.9.4.3), the strmatch () call must be able
          to recognize backslashes as escape characters. */
       match = strmatch (pattern, word, FNMATCH_EXTFLAG|FNMATCH_IGNCASE) != FNM_NOMATCH;
       free (pattern);
       dispose_words (es);
       QUIT;
       if (match)
         {
           do
         {
           if (clauses->action && ignore_return)
             clauses->action->flags |= CMD_IGNORE_RETURN;
           retval = execute_command (clauses->action);
         }
           while ((clauses->flags & CASEPAT_FALLTHROUGH) && (clauses = clauses->next));
           if (clauses == 0 || (clauses->flags & CASEPAT_TESTNEXT) == 0)
         EXIT_CASE ();
           else
         break;
         }
       QUIT;
     }
     }
 exit_case_command:
   free (word);
   discard_unwind_frame ("case");
   line_number = save_line_number;
   return (retval);
 }
References pattern_list::action, add_unwind_protect(), begin_unwind_frame(), CASEPAT_FALLTHROUGH, CASEPAT_TESTNEXT, case_com::clauses, CMD_IGNORE_RETURN, command_string_index, DEBUG_TRAP, debugging_mode, dequote_string(), discard_unwind_frame(), dispose_words(), echo_command_at_execute, execute_command(), EXECUTION_SUCCESS, EXIT_CASE, expand_word_leave_quoted(), pattern_list::flags, case_com::flags, FNM_NOMATCH, FNMATCH_EXTFLAG, FNMATCH_IGNCASE, FREE, free, case_com::line, line_number, list(), match(), pattern_list::next, node::next, pattern, pattern_list::patterns, print_case_command_head(), QGLOB_CTLESC, QGLOB_CVTNULL, QUIT, quote_string_for_globbing(), retval, run_debug_trap(), running_trap, savestring(), signal_in_progress(), STREQ, string_list(), strmatch(), t, the_printed_command, the_printed_command_except_trap, this_command_name, word_desc::word, word_list::word, case_com::word, xfree, xmalloc, and xtrace_print_case_command_head().
Referenced by execute_command_internal().
execute_command()
int execute_command (COMMAND * command)
Definition at line 401 of file execute_cmd.c.
 {
   struct fd_bitmap *bitmap;
   int result;
   current_fds_to_close = (struct fd_bitmap *)NULL;
   bitmap = new_fd_bitmap (FD_BITMAP_DEFAULT_SIZE);
   begin_unwind_frame ("execute-command");
   add_unwind_protect (dispose_fd_bitmap, (char *)bitmap);
   /* Just do the command, but not asynchronously. */
   result = execute_command_internal (command, 0, NO_PIPE, NO_PIPE, bitmap);
   dispose_fd_bitmap (bitmap);
   discard_unwind_frame ("execute-command");
 #if defined (PROCESS_SUBSTITUTION)
   /* don't unlink fifos if we're in a shell function; wait until the function
      returns. */
   if (variable_context == 0 && executing_list == 0)
     unlink_fifo_list ();
 #endif /* PROCESS_SUBSTITUTION */
   QUIT;
   return (result);
 }
References add_unwind_protect(), begin_unwind_frame(), fd_bitmap::bitmap, current_fds_to_close, discard_unwind_frame(), dispose_fd_bitmap(), execute_command_internal(), executing_list, FD_BITMAP_DEFAULT_SIZE, new_fd_bitmap(), NO_PIPE, NULL, QUIT, and variable_context.
Referenced by execute_case_command(), execute_connection(), execute_for_command(), execute_if_command(), execute_while_or_until(), and reader_loop().
execute_command_internal()
int execute_command_internal (COMMAND * command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap * fds_to_close)
Definition at line 573 of file execute_cmd.c.
 {
   int exec_result, user_subshell, invert, ignore_return, was_error_trap, fork_flags;
   REDIRECT *my_undo_list, *exec_undo_list;
   char *tcmd;
   volatile int save_line_number;
 #if defined (PROCESS_SUBSTITUTION)
   volatile int ofifo, nfifo, osize, saved_fifo;
   volatile void *ofifo_list;
 #endif
   if (breaking || continuing)
     return (last_command_exit_value);
   if (read_but_dont_execute)
     return (last_command_exit_value);
   if (command == 0)
     return (EXECUTION_SUCCESS);
   QUIT;
   run_pending_traps ();
 #if 0
   if (running_trap == 0)
 #endif
     currently_executing_command = command;
   invert = (command->flags & CMD_INVERT_RETURN) != 0;
   /* If we're inverting the return value and `set -e' has been executed,
      we don't want a failing command to inadvertently cause the shell
      to exit. */
   if (exit_immediately_on_error && invert)  /* XXX */
     command->flags |= CMD_IGNORE_RETURN;    /* XXX */
   exec_result = EXECUTION_SUCCESS;
   /* If a command was being explicitly run in a subshell, or if it is
      a shell control-structure, and it has a pipe, then we do the command
      in a subshell. */
   if (command->type == cm_subshell && (command->flags & CMD_NO_FORK))
     return (execute_in_subshell (command, asynchronous, pipe_in, pipe_out, fds_to_close));
 #if defined (COPROCESS_SUPPORT)
   if (command->type == cm_coproc)
     return (last_command_exit_value = execute_coproc (command, pipe_in, pipe_out, fds_to_close));
 #endif
   user_subshell = command->type == cm_subshell || ((command->flags & CMD_WANT_SUBSHELL) != 0);
 #if defined (TIME_BEFORE_SUBSHELL)
   if ((command->flags & CMD_TIME_PIPELINE) && user_subshell && asynchronous == 0)
     {
       command->flags |= CMD_FORCE_SUBSHELL;
       exec_result = time_command (command, asynchronous, pipe_in, pipe_out, fds_to_close);
       currently_executing_command = (COMMAND *)NULL;
       return (exec_result);
     }
 #endif
   if (command->type == cm_subshell ||
       (command->flags & (CMD_WANT_SUBSHELL|CMD_FORCE_SUBSHELL)) ||
       (shell_control_structure (command->type) &&
        (pipe_out != NO_PIPE || pipe_in != NO_PIPE || asynchronous)))
     {
       pid_t paren_pid;
       int s;
       char *p;
       /* Fork a subshell, turn off the subshell bit, turn off job
      control and call execute_command () on the command again. */
       save_line_number = line_number;
       if (command->type == cm_subshell)
     SET_LINE_NUMBER (command->value.Subshell->line);    /* XXX - save value? */
     /* Otherwise we defer setting line_number */
       tcmd = make_command_string (command);
       fork_flags = asynchronous ? FORK_ASYNC : 0;
       paren_pid = make_child (p = savestring (tcmd), fork_flags);
       if (user_subshell && signal_is_trapped (ERROR_TRAP) &&
       signal_in_progress (DEBUG_TRAP) == 0 && running_trap == 0)
     {
       FREE (the_printed_command_except_trap);
       the_printed_command_except_trap = savestring (the_printed_command);
     }
       if (paren_pid == 0)
         {
 #if defined (JOB_CONTROL)
       FREE (p);     /* child doesn't use pointer */
 #endif
       /* We want to run the exit trap for forced {} subshells, and we
          want to note this before execute_in_subshell modifies the
          COMMAND struct.  Need to keep in mind that execute_in_subshell
          runs the exit trap for () subshells itself. */
       /* This handles { command; } & */
       s = user_subshell == 0 && command->type == cm_group && pipe_in == NO_PIPE && pipe_out == NO_PIPE && asynchronous;
       /* run exit trap for : | { ...; } and { ...; } | : */
       /* run exit trap for : | ( ...; ) and ( ...; ) | : */
       s += user_subshell == 0 && command->type == cm_group && (pipe_in != NO_PIPE || pipe_out != NO_PIPE) && asynchronous == 0;
       last_command_exit_value = execute_in_subshell (command, asynchronous, pipe_in, pipe_out, fds_to_close);
       if (s)
         subshell_exit (last_command_exit_value);
       else
         sh_exit (last_command_exit_value);
       /* NOTREACHED */
         }
       else
     {
       close_pipes (pipe_in, pipe_out);
 #if defined (PROCESS_SUBSTITUTION) && defined (HAVE_DEV_FD)
       if (variable_context == 0)    /* wait until shell function completes */
         unlink_fifo_list ();
 #endif
       /* If we are part of a pipeline, and not the end of the pipeline,
          then we should simply return and let the last command in the
          pipe be waited for.  If we are not in a pipeline, or are the
          last command in the pipeline, then we wait for the subshell
          and return its exit status as usual. */
       if (pipe_out != NO_PIPE)
         return (EXECUTION_SUCCESS);
       stop_pipeline (asynchronous, (COMMAND *)NULL);
       line_number = save_line_number;
       if (asynchronous == 0)
         {
           was_error_trap = signal_is_trapped (ERROR_TRAP) && signal_is_ignored (ERROR_TRAP) == 0;
           invert = (command->flags & CMD_INVERT_RETURN) != 0;
           ignore_return = (command->flags & CMD_IGNORE_RETURN) != 0;
           exec_result = wait_for (paren_pid, 0);
           /* If we have to, invert the return value. */
           if (invert)
         exec_result = ((exec_result == EXECUTION_SUCCESS)
                 ? EXECUTION_FAILURE
                 : EXECUTION_SUCCESS);
           last_command_exit_value = exec_result;
           if (user_subshell && was_error_trap && ignore_return == 0 && invert == 0 && exec_result != EXECUTION_SUCCESS)
         {
           save_line_number = line_number;
           line_number = line_number_for_err_trap;
           run_error_trap ();
           line_number = save_line_number;
         }
           if (user_subshell && ignore_return == 0 && invert == 0 && exit_immediately_on_error && exec_result != EXECUTION_SUCCESS)
         {
           run_pending_traps ();
           jump_to_top_level (ERREXIT);
         }
           return (last_command_exit_value);
         }
       else
         {
           DESCRIBE_PID (paren_pid);
           run_pending_traps ();
           /* Posix 2013 2.9.3.1: "the exit status of an asynchronous list
          shall be zero." */
           last_command_exit_value = 0;
           return (EXECUTION_SUCCESS);
         }
     }
     }
 #if defined (COMMAND_TIMING)
   if (command->flags & CMD_TIME_PIPELINE)
     {
       if (asynchronous)
     {
       command->flags |= CMD_FORCE_SUBSHELL;
       exec_result = execute_command_internal (command, 1, pipe_in, pipe_out, fds_to_close);
     }
       else
     {
       exec_result = time_command (command, asynchronous, pipe_in, pipe_out, fds_to_close);
 #if 0
       if (running_trap == 0)
 #endif
         currently_executing_command = (COMMAND *)NULL;
     }
       return (exec_result);
     }
 #endif /* COMMAND_TIMING */
   if (shell_control_structure (command->type) && command->redirects)
     stdin_redir = stdin_redirects (command->redirects);
 #if defined (PROCESS_SUBSTITUTION)
 #  if !defined (HAVE_DEV_FD)
   reap_procsubs ();
 #  endif
   /* XXX - also if sourcelevel != 0? */
   if (variable_context != 0 || executing_list)
     {
       ofifo = num_fifos ();
       ofifo_list = copy_fifo_list ((int *)&osize);
       begin_unwind_frame ("internal_fifos");
       if (ofifo_list)
     add_unwind_protect (xfree, ofifo_list);
       saved_fifo = 1;
     }
   else
     saved_fifo = 0;
 #endif
   /* Handle WHILE FOR CASE etc. with redirections.  (Also '&' input
      redirection.)  */
   was_error_trap = signal_is_trapped (ERROR_TRAP) && signal_is_ignored (ERROR_TRAP) == 0;
   ignore_return = (command->flags & CMD_IGNORE_RETURN) != 0;
   if (do_redirections (command->redirects, RX_ACTIVE|RX_UNDOABLE) != 0)
     {
       undo_partial_redirects ();
       dispose_exec_redirects ();
 #if defined (PROCESS_SUBSTITUTION)
       if (saved_fifo)
     {
       free ((void *)ofifo_list);
           discard_unwind_frame ("internal_fifos");
     }
 #endif
       /* Handle redirection error as command failure if errexit set. */
       last_command_exit_value = EXECUTION_FAILURE;
       if (ignore_return == 0 && invert == 0 && pipe_in == NO_PIPE && pipe_out == NO_PIPE)
     {
       if (was_error_trap)
         {
           save_line_number = line_number;
           line_number = line_number_for_err_trap;
           run_error_trap ();
           line_number = save_line_number;
         }
       if (exit_immediately_on_error)
         {
           run_pending_traps ();
           jump_to_top_level (ERREXIT);
         }
     }
       return (last_command_exit_value);
     }
   my_undo_list = redirection_undo_list;
   redirection_undo_list = (REDIRECT *)NULL;
   exec_undo_list = exec_redirection_undo_list;
   exec_redirection_undo_list = (REDIRECT *)NULL;
   if (my_undo_list || exec_undo_list)
     begin_unwind_frame ("loop_redirections");
   if (my_undo_list)
     add_unwind_protect ((Function *)cleanup_redirects, my_undo_list);
   if (exec_undo_list)
     add_unwind_protect ((Function *)dispose_redirects, exec_undo_list);
   QUIT;
   switch (command->type)
     {
     case cm_simple:
       {
     save_line_number = line_number;
     /* We can't rely on variables retaining their values across a
        call to execute_simple_command if a longjmp occurs as the
        result of a `return' builtin.  This is true for sure with gcc. */
 #if defined (RECYCLES_PIDS)
     last_made_pid = NO_PID;
 #endif
     was_error_trap = signal_is_trapped (ERROR_TRAP) && signal_is_ignored (ERROR_TRAP) == 0;
     if (ignore_return && command->value.Simple)
       command->value.Simple->flags |= CMD_IGNORE_RETURN;
     if (command->flags & CMD_STDIN_REDIR)
       command->value.Simple->flags |= CMD_STDIN_REDIR;
     SET_LINE_NUMBER (command->value.Simple->line);
     exec_result =
       execute_simple_command (command->value.Simple, pipe_in, pipe_out,
                   asynchronous, fds_to_close);
     line_number = save_line_number;
     /* The temporary environment should be used for only the simple
        command immediately following its definition. */
     dispose_used_env_vars ();
 #if (defined (ultrix) && defined (mips)) || defined (C_ALLOCA)
     /* Reclaim memory allocated with alloca () on machines which
        may be using the alloca emulation code. */
     (void) alloca (0);
 #endif /* (ultrix && mips) || C_ALLOCA */
     /* If we forked to do the command, then we must wait_for ()
        the child. */
     /* XXX - this is something to watch out for if there are problems
        when the shell is compiled without job control.  Don't worry about
        whether or not last_made_pid == last_pid; already_making_children
        tells us whether or not there are unwaited-for children to wait
        for and reap. */
     if (already_making_children && pipe_out == NO_PIPE)
       {
         stop_pipeline (asynchronous, (COMMAND *)NULL);
         if (asynchronous)
           {
         DESCRIBE_PID (last_made_pid);
         exec_result = EXECUTION_SUCCESS;
         invert = 0;     /* async commands always succeed */
           }
         else
 #if !defined (JOB_CONTROL)
           /* Do not wait for asynchronous processes started from
          startup files. */
         if (last_made_pid != NO_PID && last_made_pid != last_asynchronous_pid)
 #else
         if (last_made_pid != NO_PID)
 #endif
         /* When executing a shell function that executes other
            commands, this causes the last simple command in
            the function to be waited for twice.  This also causes
            subshells forked to execute builtin commands (e.g., in
            pipelines) to be waited for twice. */
           exec_result = wait_for (last_made_pid, 0);
       }
       }
       /* 2009/02/13 -- pipeline failure is processed elsewhere.  This handles
      only the failure of a simple command. We don't want to run the error
      trap if the command run by the `command' builtin fails; we want to
      defer that until the command builtin itself returns failure. */
       /* 2020/07/14 -- this changes with how the command builtin is handled */
       if (was_error_trap && ignore_return == 0 && invert == 0 &&
         pipe_in == NO_PIPE && pipe_out == NO_PIPE &&
         (command->value.Simple->flags & CMD_COMMAND_BUILTIN) == 0 &&
         exec_result != EXECUTION_SUCCESS)
     {
       last_command_exit_value = exec_result;
       line_number = line_number_for_err_trap;
       run_error_trap ();
       line_number = save_line_number;
     }
       if (ignore_return == 0 && invert == 0 &&
       ((posixly_correct && interactive == 0 && special_builtin_failed) ||
        (exit_immediately_on_error && pipe_in == NO_PIPE && pipe_out == NO_PIPE && exec_result != EXECUTION_SUCCESS)))
     {
       last_command_exit_value = exec_result;
       run_pending_traps ();
       /* Undo redirections before running exit trap on the way out of
          set -e. Report by Mark Farrell 5/19/2014 */
       if (exit_immediately_on_error && signal_is_trapped (0) &&
         unwind_protect_tag_on_stack ("saved-redirects"))
         run_unwind_frame ("saved-redirects");
       jump_to_top_level (ERREXIT);
     }
       break;
     case cm_for:
       if (ignore_return)
     command->value.For->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_for_command (command->value.For);
       break;
 #if defined (ARITH_FOR_COMMAND)
     case cm_arith_for:
       if (ignore_return)
     command->value.ArithFor->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_arith_for_command (command->value.ArithFor);
       break;
 #endif
 #if defined (SELECT_COMMAND)
     case cm_select:
       if (ignore_return)
     command->value.Select->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_select_command (command->value.Select);
       break;
 #endif
     case cm_case:
       if (ignore_return)
     command->value.Case->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_case_command (command->value.Case);
       break;
     case cm_while:
       if (ignore_return)
     command->value.While->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_while_command (command->value.While);
       break;
     case cm_until:
       if (ignore_return)
     command->value.While->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_until_command (command->value.While);
       break;
     case cm_if:
       if (ignore_return)
     command->value.If->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_if_command (command->value.If);
       break;
     case cm_group:
       /* This code can be executed from either of two paths: an explicit
      '{}' command, or via a function call.  If we are executed via a
      function call, we have already taken care of the function being
      executed in the background (down there in execute_simple_command ()),
      and this command should *not* be marked as asynchronous.  If we
      are executing a regular '{}' group command, and asynchronous == 1,
      we must want to execute the whole command in the background, so we
      need a subshell, and we want the stuff executed in that subshell
      (this group command) to be executed in the foreground of that
      subshell (i.e. there will not be *another* subshell forked).
      What we do is to force a subshell if asynchronous, and then call
      execute_command_internal again with asynchronous still set to 1,
      but with the original group command, so the printed command will
      look right.
      The code above that handles forking off subshells will note that
      both subshell and async are on, and turn off async in the child
      after forking the subshell (but leave async set in the parent, so
      the normal call to describe_pid is made).  This turning off
      async is *crucial*; if it is not done, this will fall into an
      infinite loop of executions through this spot in subshell after
      subshell until the process limit is exhausted. */
       if (asynchronous)
     {
       command->flags |= CMD_FORCE_SUBSHELL;
       exec_result =
         execute_command_internal (command, 1, pipe_in, pipe_out,
                       fds_to_close);
     }
       else
     {
       if (ignore_return && command->value.Group->command)
         command->value.Group->command->flags |= CMD_IGNORE_RETURN;
       exec_result =
         execute_command_internal (command->value.Group->command,
                       asynchronous, pipe_in, pipe_out,
                       fds_to_close);
     }
       break;
     case cm_connection:
       exec_result = execute_connection (command, asynchronous,
                     pipe_in, pipe_out, fds_to_close);
       if (asynchronous)
     invert = 0;     /* XXX */
       break;
 #if defined (DPAREN_ARITHMETIC)
     case cm_arith:
 #endif
 #if defined (COND_COMMAND)
     case cm_cond:
 #endif
     case cm_function_def:
       was_error_trap = signal_is_trapped (ERROR_TRAP) && signal_is_ignored (ERROR_TRAP) == 0;
 #if defined (DPAREN_ARITHMETIC)
       if (ignore_return && command->type == cm_arith)
     command->value.Arith->flags |= CMD_IGNORE_RETURN;
 #endif
 #if defined (COND_COMMAND)
       if (ignore_return && command->type == cm_cond)
     command->value.Cond->flags |= CMD_IGNORE_RETURN;
 #endif
       line_number_for_err_trap = save_line_number = line_number;    /* XXX */
 #if defined (DPAREN_ARITHMETIC)
       if (command->type == cm_arith)
     exec_result = execute_arith_command (command->value.Arith);
       else
 #endif
 #if defined (COND_COMMAND)
       if (command->type == cm_cond)
     exec_result = execute_cond_command (command->value.Cond);
       else
 #endif
       if (command->type == cm_function_def)
     exec_result = execute_intern_function (command->value.Function_def->name,
                            command->value.Function_def);
       line_number = save_line_number;
       if (was_error_trap && ignore_return == 0 && invert == 0 && exec_result != EXECUTION_SUCCESS)
     {
       last_command_exit_value = exec_result;
       save_line_number = line_number;
       line_number = line_number_for_err_trap;
       run_error_trap ();
       line_number = save_line_number;
     }
       if (ignore_return == 0 && invert == 0 && exit_immediately_on_error && exec_result != EXECUTION_SUCCESS)
     {
       last_command_exit_value = exec_result;
       run_pending_traps ();
       jump_to_top_level (ERREXIT);
     }
       break;
     default:
       command_error ("execute_command", CMDERR_BADTYPE, command->type, 0);
     }
   if (my_undo_list)
     cleanup_redirects (my_undo_list);
   if (exec_undo_list)
     dispose_redirects (exec_undo_list);
   if (my_undo_list || exec_undo_list)
     discard_unwind_frame ("loop_redirections");
 #if defined (PROCESS_SUBSTITUTION)
   if (saved_fifo)
     {
       nfifo = num_fifos ();
       if (nfifo > ofifo)
     close_new_fifos ((void *)ofifo_list, osize);
       free ((void *)ofifo_list);
       discard_unwind_frame ("internal_fifos");
     }
 #endif
   /* Invert the return value if we have to */
   if (invert)
     exec_result = (exec_result == EXECUTION_SUCCESS)
             ? EXECUTION_FAILURE
             : EXECUTION_SUCCESS;
 #if defined (DPAREN_ARITHMETIC) || defined (COND_COMMAND)
   /* This is where we set PIPESTATUS from the exit status of the appropriate
      compound commands (the ones that look enough like simple commands to
      cause confusion).  We might be able to optimize by not doing this if
      subshell_environment != 0. */
   switch (command->type)
     {
 #  if defined (DPAREN_ARITHMETIC)
     case cm_arith:
 #  endif
 #  if defined (COND_COMMAND)
     case cm_cond:
 #  endif
       set_pipestatus_from_exit (exec_result);
       break;
     default:
       break;
     }
 #endif
   last_command_exit_value = exec_result;
   run_pending_traps ();
   currently_executing_command = (COMMAND *)NULL;
   return (last_command_exit_value);
 }
References add_unwind_protect(), alloca, already_making_children, begin_unwind_frame(), breaking, cleanup_redirects(), close_pipes(), cm_arith, cm_arith_for, cm_case, cm_cond, cm_connection, cm_coproc, cm_for, cm_function_def, cm_group, cm_if, cm_select, cm_simple, cm_subshell, cm_until, cm_while, CMD_COMMAND_BUILTIN, CMD_FORCE_SUBSHELL, CMD_IGNORE_RETURN, CMD_INVERT_RETURN, CMD_NO_FORK, CMD_STDIN_REDIR, CMD_TIME_PIPELINE, CMD_WANT_SUBSHELL, CMDERR_BADTYPE, command_error(), continuing, currently_executing_command, DEBUG_TRAP, DESCRIBE_PID, discard_unwind_frame(), dispose_exec_redirects(), dispose_redirects(), dispose_used_env_vars(), do_redirections(), ERREXIT, ERROR_TRAP, exec_redirection_undo_list, execute_case_command(), execute_connection(), execute_for_command(), execute_if_command(), execute_in_subshell(), execute_intern_function(), execute_simple_command(), execute_until_command(), execute_while_command(), executing_list, EXECUTION_FAILURE, EXECUTION_SUCCESS, exit_immediately_on_error, command::flags, FORK_ASYNC, FREE, free, interactive, jump_to_top_level(), last_asynchronous_pid, last_command_exit_value, last_made_pid, command::line, line_number, line_number_for_err_trap, make_child(), make_command_string(), NO_PID, NO_PIPE, NULL, p, posixly_correct, QUIT, read_but_dont_execute, redirection_undo_list, command::redirects, run_error_trap(), run_pending_traps(), run_unwind_frame(), running_trap, RX_ACTIVE, RX_UNDOABLE, s, savestring(), SET_LINE_NUMBER, set_pipestatus_from_exit(), sh_exit(), shell_control_structure(), signal_in_progress(), signal_is_ignored(), signal_is_trapped(), special_builtin_failed, stdin_redir, stdin_redirects(), stop_pipeline(), subshell_exit(), the_printed_command, the_printed_command_except_trap, command::type, undo_partial_redirects(), unwind_protect_tag_on_stack(), command::value, variable_context, Driver::void(), wait_for(), and xfree.
Referenced by execute_command(), execute_connection(), execute_function(), execute_in_subshell(), execute_pipeline(), and parse_and_execute().
execute_connection()
static int execute_connection (COMMAND * command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap * fds_to_close) static
Definition at line 2689 of file execute_cmd.c.
 {
   COMMAND *tc, *second;
   int ignore_return, exec_result, was_error_trap, invert;
   volatile int save_line_number;
   ignore_return = (command->flags & CMD_IGNORE_RETURN) != 0;
   switch (command->value.Connection->connector)
     {
     /* Do the first command asynchronously. */
     case '&':
       tc = command->value.Connection->first;
       if (tc == 0)
     return (EXECUTION_SUCCESS);
       if (ignore_return)
     tc->flags |= CMD_IGNORE_RETURN;
       tc->flags |= CMD_AMPERSAND;
       /* If this shell was compiled without job control support,
      if we are currently in a subshell via `( xxx )', or if job
      control is not active then the standard input for an
      asynchronous command is forced to /dev/null. */
 #if defined (JOB_CONTROL)
       if ((subshell_environment || !job_control) && !stdin_redir)
 #else
       if (!stdin_redir)
 #endif /* JOB_CONTROL */
     tc->flags |= CMD_STDIN_REDIR;
       exec_result = execute_command_internal (tc, 1, pipe_in, pipe_out, fds_to_close);
       QUIT;
       if (tc->flags & CMD_STDIN_REDIR)
     tc->flags &= ~CMD_STDIN_REDIR;
       second = command->value.Connection->second;
       if (second)
     {
       if (ignore_return)
         second->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_command_internal (second, asynchronous, pipe_in, pipe_out, fds_to_close);
     }
       break;
     /* Just call execute command on both sides. */
     case ';':
     case '\n':      /* special case, happens in command substitutions */
       if (ignore_return)
     {
       if (command->value.Connection->first)
         command->value.Connection->first->flags |= CMD_IGNORE_RETURN;
       if (command->value.Connection->second)
         command->value.Connection->second->flags |= CMD_IGNORE_RETURN;
     }
       executing_list++;
       QUIT;
 #if 1
       execute_command (command->value.Connection->first);
 #else
       execute_command_internal (command->value.Connection->first,
                   asynchronous, pipe_in, pipe_out,
                   fds_to_close);
 #endif
       QUIT;
       optimize_connection_fork (command);           /* XXX */
       exec_result = execute_command_internal (command->value.Connection->second,
                       asynchronous, pipe_in, pipe_out,
                       fds_to_close);
       executing_list--;
       break;
     case '|':
       was_error_trap = signal_is_trapped (ERROR_TRAP) && signal_is_ignored (ERROR_TRAP) == 0;
       invert = (command->flags & CMD_INVERT_RETURN) != 0;
       ignore_return = (command->flags & CMD_IGNORE_RETURN) != 0;
       SET_LINE_NUMBER (line_number);    /* XXX - save value? */
       exec_result = execute_pipeline (command, asynchronous, pipe_in, pipe_out, fds_to_close);
       if (asynchronous)
     {
       exec_result = EXECUTION_SUCCESS;
       invert = 0;
     }
       if (was_error_trap && ignore_return == 0 && invert == 0 && exec_result != EXECUTION_SUCCESS)
     {
       last_command_exit_value = exec_result;
       save_line_number = line_number;
       line_number = line_number_for_err_trap;
       run_error_trap ();
       line_number = save_line_number;
     }
       if (ignore_return == 0 && invert == 0 && exit_immediately_on_error && exec_result != EXECUTION_SUCCESS)
     {
       last_command_exit_value = exec_result;
       run_pending_traps ();
       jump_to_top_level (ERREXIT);
     }
       break;
     case AND_AND:
     case OR_OR:
       if (asynchronous)
     {
       /* If we have something like `a && b &' or `a || b &', run the
          && or || stuff in a subshell.  Force a subshell and just call
          execute_command_internal again.  Leave asynchronous on
          so that we get a report from the parent shell about the
          background job. */
       command->flags |= CMD_FORCE_SUBSHELL;
       exec_result = execute_command_internal (command, 1, pipe_in, pipe_out, fds_to_close);
       break;
     }
       /* Execute the first command.  If the result of that is successful
      and the connector is AND_AND, or the result is not successful
      and the connector is OR_OR, then execute the second command,
      otherwise return. */
       executing_list++;
       if (command->value.Connection->first)
     command->value.Connection->first->flags |= CMD_IGNORE_RETURN;
 #if 1
       exec_result = execute_command (command->value.Connection->first);
 #else
       exec_result = execute_command_internal (command->value.Connection->first, 0, NO_PIPE, NO_PIPE, fds_to_close);
 #endif
       QUIT;
       if (((command->value.Connection->connector == AND_AND) &&
        (exec_result == EXECUTION_SUCCESS)) ||
       ((command->value.Connection->connector == OR_OR) &&
        (exec_result != EXECUTION_SUCCESS)))
     {
       optimize_connection_fork (command);
       second = command->value.Connection->second;
       if (ignore_return && second)
         second->flags |= CMD_IGNORE_RETURN;
       exec_result = execute_command (second);
     }
       executing_list--;
       break;
     default:
       command_error ("execute_connection", CMDERR_BADCONN, command->value.Connection->connector, 0);
       jump_to_top_level (DISCARD);
       exec_result = EXECUTION_FAILURE;
     }
   return exec_result;
 }
References AND_AND, CMD_AMPERSAND, CMD_FORCE_SUBSHELL, CMD_IGNORE_RETURN, CMD_INVERT_RETURN, CMD_STDIN_REDIR, CMDERR_BADCONN, command_error(), DISCARD, ERREXIT, ERROR_TRAP, execute_command(), execute_command_internal(), execute_pipeline(), executing_list, EXECUTION_FAILURE, EXECUTION_SUCCESS, exit_immediately_on_error, command::flags, job_control, jump_to_top_level(), last_command_exit_value, line_number, line_number_for_err_trap, NO_PIPE, optimize_connection_fork(), OR_OR, QUIT, run_error_trap(), run_pending_traps(), SET_LINE_NUMBER, signal_is_ignored(), signal_is_trapped(), stdin_redir, subshell_environment, tc, and command::value.
Referenced by execute_command_internal().
execute_disk_command()
static int execute_disk_command (WORD_LIST * words, REDIRECT * redirects, char * command_line, int pipe_in, int pipe_out, int async, struct fd_bitmap * fds_to_close, int cmdflags) static
Definition at line 5586 of file execute_cmd.c.
 {
   char *pathname, *command, **args, *p;
   int nofork, stdpath, result, fork_flags;
   pid_t pid;
   SHELL_VAR *hookf;
   WORD_LIST *wl;
   stdpath = (cmdflags & CMD_STDPATH);   /* use command -p path */
   nofork = (cmdflags & CMD_NO_FORK);    /* Don't fork, just exec, if no pipes */
   pathname = words->word->word;
   p = 0;
   result = EXECUTION_SUCCESS;
 #if defined (RESTRICTED_SHELL)
   command = (char *)NULL;
   if (restricted && mbschr (pathname, '/'))
     {
       internal_error (_("%s: restricted: cannot specify `/' in command names"),
             pathname);
       result = last_command_exit_value = EXECUTION_FAILURE;
       /* If we're not going to fork below, we must already be in a child
          process or a context in which it's safe to call exit(2).  */
       if (nofork && pipe_in == NO_PIPE && pipe_out == NO_PIPE)
     exit (last_command_exit_value);
       else
     goto parent_return;
     }
 #endif /* RESTRICTED_SHELL */
   /* If we want to change this so `command -p' (CMD_STDPATH) does not insert
      any pathname it finds into the hash table, it should read
      command = search_for_command (pathname, stdpath ? CMDSRCH_STDPATH : CMDSRCH_HASH);
   */
   command = search_for_command (pathname, CMDSRCH_HASH|(stdpath ? CMDSRCH_STDPATH : 0));
   QUIT;
   if (command)
     {
       /* If we're optimizing out the fork (implicit `exec'), decrement the
      shell level like `exec' would do. Don't do this if we are already
      in a pipeline environment, assuming it's already been done. */
       if (nofork && pipe_in == NO_PIPE && pipe_out == NO_PIPE && (subshell_environment & SUBSHELL_PIPE) == 0)
     adjust_shell_level (-1);
       maybe_make_export_env ();
       put_command_name_into_env (command);
     }
   /* We have to make the child before we check for the non-existence
      of COMMAND, since we want the error messages to be redirected. */
   /* If we can get away without forking and there are no pipes to deal with,
      don't bother to fork, just directly exec the command. */
   if (nofork && pipe_in == NO_PIPE && pipe_out == NO_PIPE)
     pid = 0;
   else
     {
       fork_flags = async ? FORK_ASYNC : 0;
       pid = make_child (p = savestring (command_line), fork_flags);
     }
   if (pid == 0)
     {
       int old_interactive;
       reset_terminating_signals (); /* XXX */
       /* Cancel traps, in trap.c. */
       restore_original_signals ();
       subshell_environment &= ~SUBSHELL_IGNTRAP;
 #if defined (JOB_CONTROL)
       FREE (p);
 #endif
       /* restore_original_signals may have undone the work done
      by make_child to ensure that SIGINT and SIGQUIT are ignored
      in asynchronous children. */
       if (async)
     {
       if ((cmdflags & CMD_STDIN_REDIR) &&
         pipe_in == NO_PIPE &&
         (stdin_redirects (redirects) == 0))
         async_redirect_stdin ();
       setup_async_signals ();
     }
       /* This functionality is now provided by close-on-exec of the
      file descriptors manipulated by redirection and piping.
      Some file descriptors still need to be closed in all children
      because of the way bash does pipes; fds_to_close is a
      bitmap of all such file descriptors. */
       if (fds_to_close)
     close_fd_bitmap (fds_to_close);
       do_piping (pipe_in, pipe_out);
       old_interactive = interactive;
       if (async)
     interactive = 0;
       subshell_environment |= SUBSHELL_FORK;    /* XXX - was just = */
 #if defined (PROCESS_SUBSTITUTION) && !defined (HAVE_DEV_FD)
       clear_fifo_list ();   /* XXX - we haven't created any FIFOs */
 #endif
       /* reset shell_pgrp to pipeline_pgrp here for word expansions performed
          by the redirections here? */
       if (redirects && (do_redirections (redirects, RX_ACTIVE) != 0))
     {
 #if defined (PROCESS_SUBSTITUTION)
       /* Try to remove named pipes that may have been created as the
          result of redirections. */
       unlink_all_fifos ();
 #endif /* PROCESS_SUBSTITUTION */
       exit (EXECUTION_FAILURE);
     }
 #if defined (PROCESS_SUBSTITUTION) && !defined (HAVE_DEV_FD)
       /* This should only contain FIFOs created as part of redirection
      expansion. */
       unlink_all_fifos ();
 #endif
       if (async)
     interactive = old_interactive;
       if (command == 0)
     {
       hookf = find_function (NOTFOUND_HOOK);
       if (hookf == 0)
         {
           /* Make sure filenames are displayed using printable characters */
           pathname = printable_filename (pathname, 0);
           internal_error (_("%s: command not found"), pathname);
           exit (EX_NOTFOUND);   /* Posix.2 says the exit status is 127 */
         }
       /* We don't want to manage process groups for processes we start
          from here, so we turn off job control and don't attempt to
          manipulate the terminal's process group. */
       without_job_control ();
 #if defined (JOB_CONTROL)
       set_sigchld_handler ();
 #endif
       wl = make_word_list (make_word (NOTFOUND_HOOK), words);
       exit (execute_shell_function (hookf, wl));
     }
       /* Execve expects the command name to be in args[0].  So we
      leave it there, in the same format that the user used to
      type it in. */
       args = strvec_from_word_list (words, 0, 0, (int *)NULL);
       exit (shell_execve (command, args, export_env));
     }
   else
     {
 parent_return:
       QUIT;
       /* Make sure that the pipes are closed in the parent. */
       close_pipes (pipe_in, pipe_out);
 #if defined (PROCESS_SUBSTITUTION) && defined (HAVE_DEV_FD)
 #if 0
       if (variable_context == 0)
         unlink_fifo_list ();
 #endif
 #endif
       FREE (command);
       return (result);
     }
 }
References _, adjust_shell_level(), args, async_redirect_stdin(), close_fd_bitmap(), close_pipes(), CMD_NO_FORK, CMD_STDIN_REDIR, CMD_STDPATH, CMDSRCH_HASH, CMDSRCH_STDPATH, do_piping(), do_redirections(), EX_NOTFOUND, execute_shell_function(), EXECUTION_FAILURE, EXECUTION_SUCCESS, exit(), export_env, find_function(), FORK_ASYNC, FREE, interactive, internal_error(), last_command_exit_value, make_child(), make_word(), make_word_list(), maybe_make_export_env(), mbschr(), NO_PIPE, NOTFOUND_HOOK, NULL, p, pid, printable_filename(), put_command_name_into_env(), QUIT, reset_terminating_signals(), restore_original_signals(), RX_ACTIVE, savestring(), search_for_command(), set_sigchld_handler(), setup_async_signals(), shell_execve(), stdin_redirects(), strvec_from_word_list(), subshell_environment, SUBSHELL_FORK, SUBSHELL_IGNTRAP, SUBSHELL_PIPE, variable_context, without_job_control(), word_desc::word, and word_list::word.
Referenced by execute_simple_command(), and execute_subshell_builtin_or_function().
execute_for_command()
static int execute_for_command (FOR_COM * for_command) static
Definition at line 2869 of file execute_cmd.c.
 {
   register WORD_LIST *releaser, *list;
   SHELL_VAR *v;
   char *identifier;
   int retval, save_line_number;
 #if 0
   SHELL_VAR *old_value = (SHELL_VAR *)NULL; /* Remember the old value of x. */
 #endif
   save_line_number = line_number;
   if (check_identifier (for_command->name, 1) == 0)
     {
       if (posixly_correct && interactive_shell == 0)
     {
       last_command_exit_value = EX_BADUSAGE;
       jump_to_top_level (ERREXIT);
     }
       return (EXECUTION_FAILURE);
     }
   loop_level++;
   identifier = for_command->name->word;
   line_number = for_command->line;  /* for expansion error messages */
   list = releaser = expand_words_no_vars (for_command->map_list);
   begin_unwind_frame ("for");
   add_unwind_protect (dispose_words, releaser);
 #if 0
   if (lexical_scoping)
     {
       old_value = copy_variable (find_variable (identifier));
       if (old_value)
     add_unwind_protect (dispose_variable, old_value);
     }
 #endif
   if (for_command->flags & CMD_IGNORE_RETURN)
     for_command->action->flags |= CMD_IGNORE_RETURN;
   for (retval = EXECUTION_SUCCESS; list; list = list->next)
     {
       QUIT;
       line_number = for_command->line;
       /* Remember what this command looks like, for debugger. */
       command_string_index = 0;
       print_for_command_head (for_command);
       if (echo_command_at_execute)
     xtrace_print_for_command_head (for_command);
       /* Save this command unless it's a trap command and we're not running
      a debug trap. */
       if (signal_in_progress (DEBUG_TRAP) == 0 && running_trap == 0)
     {
       FREE (the_printed_command_except_trap);
       the_printed_command_except_trap = savestring (the_printed_command);
     }
       retval = run_debug_trap ();
 #if defined (DEBUGGER)
       /* In debugging mode, if the DEBUG trap returns a non-zero status, we
      skip the command. */
       if (debugging_mode && retval != EXECUTION_SUCCESS)
         continue;
 #endif
       this_command_name = (char *)NULL;
       /* XXX - special ksh93 for command index variable handling */
       v = find_variable_last_nameref (identifier, 1);
       if (v && nameref_p (v))
     {
       if (valid_nameref_value (list->word->word, 1) == 0)
         {
           sh_invalidid (list->word->word);
           v = 0;
         }
       else if (readonly_p (v))
         err_readonly (name_cell (v));
       else
         v = bind_variable_value (v, list->word->word, ASS_NAMEREF);
     }
       else
     v = bind_variable (identifier, list->word->word, 0);
       if (v == 0 || readonly_p (v) || noassign_p (v))
     {
       line_number = save_line_number;
       if (v && readonly_p (v) && interactive_shell == 0 && posixly_correct)
         {
           last_command_exit_value = EXECUTION_FAILURE;
           jump_to_top_level (FORCE_EOF);
         }
       else
         {
           dispose_words (releaser);
           discard_unwind_frame ("for");
           loop_level--;
           return (EXECUTION_FAILURE);
         }
     }
       if (ifsname (identifier))
     setifs (v);
       else
     stupidly_hack_special_variables (identifier);
       retval = execute_command (for_command->action);
       REAP ();
       QUIT;
       if (breaking)
     {
       breaking--;
       break;
     }
       if (continuing)
     {
       continuing--;
       if (continuing)
         break;
     }
     }
   loop_level--;
   line_number = save_line_number;
 #if 0
   if (lexical_scoping)
     {
       if (!old_value)
         unbind_variable (identifier);
       else
     {
       SHELL_VAR *new_value;
       new_value = bind_variable (identifier, value_cell (old_value), 0);
       new_value->attributes = old_value->attributes;
       dispose_variable (old_value);
     }
     }
 #endif
   dispose_words (releaser);
   discard_unwind_frame ("for");
   return (retval);
 }
References for_com::action, add_unwind_protect(), ASS_NAMEREF, variable::attributes, begin_unwind_frame(), bind_variable(), bind_variable_value(), breaking, check_identifier(), CMD_IGNORE_RETURN, command_string_index, continuing, DEBUG_TRAP, debugging_mode, discard_unwind_frame(), dispose_variable(), dispose_words(), echo_command_at_execute, err_readonly(), ERREXIT, EX_BADUSAGE, execute_command(), EXECUTION_FAILURE, EXECUTION_SUCCESS, expand_words_no_vars(), find_variable(), find_variable_last_nameref(), for_com::flags, FORCE_EOF, FREE, ifsname, interactive_shell, jump_to_top_level(), last_command_exit_value, for_com::line, line_number, list(), loop_level, for_com::map_list, for_com::name, name_cell, nameref_p, node::next, noassign_p, NULL, posixly_correct, print_for_command_head(), QUIT, readonly_p, REAP, retval, run_debug_trap(), running_trap, savestring(), setifs(), sh_invalidid(), signal_in_progress(), stupidly_hack_special_variables(), the_printed_command, the_printed_command_except_trap, this_command_name, unbind_variable(), valid_nameref_value(), value_cell, word_desc::word, and xtrace_print_for_command_head().
Referenced by execute_command_internal().
execute_function()
static int execute_function (SHELL_VAR * var, WORD_LIST * words, int flags, struct fd_bitmap * fds_to_close, int async, int subshell) static
Definition at line 5030 of file execute_cmd.c.
 {
   int return_val, result, lineno;
   COMMAND *tc, *fc, *save_current;
   char *debug_trap, *error_trap, *return_trap;
 #if defined (ARRAY_VARS)
   SHELL_VAR *funcname_v, *bash_source_v, *bash_lineno_v;
   ARRAY *funcname_a;
   volatile ARRAY *bash_source_a;
   volatile ARRAY *bash_lineno_a;
   struct func_array_state *fa;
 #endif
   FUNCTION_DEF *shell_fn;
   char *sfile, *t;
   sh_getopt_state_t *gs;
   SHELL_VAR *gv;
   USE_VAR(fc);
   if (funcnest_max > 0 && funcnest >= funcnest_max)
     {
       internal_error (_("%s: maximum function nesting level exceeded (%d)"), var->name, funcnest);
       funcnest = 0; /* XXX - should we reset it somewhere else? */
       jump_to_top_level (DISCARD);
     }
 #if defined (ARRAY_VARS)
   GET_ARRAY_FROM_VAR ("FUNCNAME", funcname_v, funcname_a);
   GET_ARRAY_FROM_VAR ("BASH_SOURCE", bash_source_v, bash_source_a);
   GET_ARRAY_FROM_VAR ("BASH_LINENO", bash_lineno_v, bash_lineno_a);
 #endif
   tc = (COMMAND *)copy_command (function_cell (var));
   if (tc && (flags & CMD_IGNORE_RETURN))
     tc->flags |= CMD_IGNORE_RETURN;
   /* A limited attempt at optimization: shell functions at the end of command
      substitutions that are already marked NO_FORK. */
   if (tc && (flags & CMD_NO_FORK) && (subshell_environment & SUBSHELL_COMSUB))
     optimize_shell_function (tc);
   gs = sh_getopt_save_istate ();
   if (subshell == 0)
     {
       begin_unwind_frame ("function_calling");
       /* If the shell is in posix mode, this will push the variables in
      the temporary environment to the "current shell environment" (the
      global scope), and dispose the temporary env before setting it to
      NULL later. This behavior has disappeared from the latest edition
      of the standard, so I will eventually remove it from variables.c:
      push_var_context. */
       push_context (var->name, subshell, temporary_env);
       /* This has to be before the pop_context(), because the unwinding of
      local variables may cause the restore of a local declaration of
      OPTIND to force a getopts state reset. */
       add_unwind_protect (maybe_restore_getopt_state, gs);
       add_unwind_protect (pop_context, (char *)NULL);
       unwind_protect_int (line_number);
       unwind_protect_int (line_number_for_err_trap);
       unwind_protect_int (function_line_number);
       unwind_protect_int (return_catch_flag);
       unwind_protect_jmp_buf (return_catch);
       add_unwind_protect (dispose_command, (char *)tc);
       unwind_protect_pointer (this_shell_function);
       unwind_protect_int (funcnest);
       unwind_protect_int (loop_level);
     }
   else
     push_context (var->name, subshell, temporary_env);  /* don't unwind-protect for subshells */
   temporary_env = (HASH_TABLE *)NULL;
   this_shell_function = var;
   make_funcname_visible (1);
   debug_trap = TRAP_STRING(DEBUG_TRAP);
   error_trap = TRAP_STRING(ERROR_TRAP);
   return_trap = TRAP_STRING(RETURN_TRAP);
   /* The order of the unwind protects for debug_trap, error_trap and
      return_trap is important here!  unwind-protect commands are run
      in reverse order of registration.  If this causes problems, take
      out the xfree unwind-protect calls and live with the small memory leak. */
   /* function_trace_mode != 0 means that all functions inherit the DEBUG trap.
      if the function has the trace attribute set, it inherits the DEBUG trap */
   if (debug_trap && ((trace_p (var) == 0) && function_trace_mode == 0))
     {
       if (subshell == 0)
     {
       debug_trap = savestring (debug_trap);
       add_unwind_protect (xfree, debug_trap);
       add_unwind_protect (maybe_set_debug_trap, debug_trap);
     }
       restore_default_signal (DEBUG_TRAP);
     }
   /* error_trace_mode != 0 means that functions inherit the ERR trap. */
   if (error_trap && error_trace_mode == 0)
     {
       if (subshell == 0)
     {
       error_trap = savestring (error_trap);
       add_unwind_protect (xfree, error_trap);
       add_unwind_protect (maybe_set_error_trap, error_trap);
     }
       restore_default_signal (ERROR_TRAP);
     }
   /* Shell functions inherit the RETURN trap if function tracing is on
      globally or on individually for this function. */
   if (return_trap && (signal_in_progress (DEBUG_TRAP) || ((trace_p (var) == 0) && function_trace_mode == 0)))
     {
       if (subshell == 0)
     {
       return_trap = savestring (return_trap);
       add_unwind_protect (xfree, return_trap);
       add_unwind_protect (maybe_set_return_trap, return_trap);
     }
       restore_default_signal (RETURN_TRAP);
     }
   funcnest++;
 #if defined (ARRAY_VARS)
   /* This is quite similar to the code in shell.c and elsewhere. */
   shell_fn = find_function_def (this_shell_function->name);
   sfile = shell_fn ? shell_fn->source_file : "";
   array_push ((ARRAY *)funcname_a, this_shell_function->name);
   array_push ((ARRAY *)bash_source_a, sfile);
   lineno = GET_LINE_NUMBER ();
   t = itos (lineno);
   array_push ((ARRAY *)bash_lineno_a, t);
   free (t);
 #endif
 #if defined (ARRAY_VARS)
   fa = (struct func_array_state *)xmalloc (sizeof (struct func_array_state));
   fa->source_a = (ARRAY *)bash_source_a;
   fa->source_v = bash_source_v;
   fa->lineno_a = (ARRAY *)bash_lineno_a;
   fa->lineno_v = bash_lineno_v;
   fa->funcname_a = (ARRAY *)funcname_a;
   fa->funcname_v = funcname_v;
   if (subshell == 0)
     add_unwind_protect (restore_funcarray_state, fa);
 #endif
   /* The temporary environment for a function is supposed to apply to
      all commands executed within the function body. */
   /* Initialize BASH_ARGC and BASH_ARGV before we blow away the positional
      parameters */
   if (debugging_mode || shell_compatibility_level <= 44)
     init_bash_argv ();
   remember_args (words->next, 1);
   /* Update BASH_ARGV and BASH_ARGC */
   if (debugging_mode)
     {
       push_args (words->next);
       if (subshell == 0)
     add_unwind_protect (pop_args, 0);
     }
   /* Number of the line on which the function body starts. */
   line_number = function_line_number = tc->line;
 #if defined (JOB_CONTROL)
   if (subshell)
     stop_pipeline (async, (COMMAND *)NULL);
 #endif
   if (shell_compatibility_level > 43)
     loop_level = 0;
   fc = tc;
   from_return_trap = 0;
   return_catch_flag++;
   return_val = setjmp_nosigs (return_catch);
   if (return_val)
     {
       result = return_catch_value;
       /* Run the RETURN trap in the function's context. */
       save_current = currently_executing_command;
       if (from_return_trap == 0)
     run_return_trap ();
       currently_executing_command = save_current;
     }
   else
     {
       /* Run the debug trap here so we can trap at the start of a function's
      execution rather than the execution of the body's first command. */
       showing_function_line = 1;
       save_current = currently_executing_command;
       result = run_debug_trap ();
 #if defined (DEBUGGER)
       /* In debugging mode, if the DEBUG trap returns a non-zero status, we
      skip the command. */
       if (debugging_mode == 0 || result == EXECUTION_SUCCESS)
     {
       showing_function_line = 0;
       currently_executing_command = save_current;
       result = execute_command_internal (fc, 0, NO_PIPE, NO_PIPE, fds_to_close);
       /* Run the RETURN trap in the function's context */
       save_current = currently_executing_command;
       run_return_trap ();
       currently_executing_command = save_current;
     }
 #else
       result = execute_command_internal (fc, 0, NO_PIPE, NO_PIPE, fds_to_close);
       save_current = currently_executing_command;
       run_return_trap ();
       currently_executing_command = save_current;
 #endif
       showing_function_line = 0;
     }
   /* If we have a local copy of OPTIND, note it in the saved getopts state. */
   gv = find_variable ("OPTIND");
   if (gv && gv->context == variable_context)
     gs->gs_flags |= 1;
   if (subshell == 0)
     run_unwind_frame ("function_calling");
 #if defined (ARRAY_VARS)
   else
     {
       restore_funcarray_state (fa);
       /* Restore BASH_ARGC and BASH_ARGV */
       if (debugging_mode)
     pop_args ();
     }
 #endif
   if (variable_context == 0 || this_shell_function == 0)
     {
       make_funcname_visible (0);
 #if defined (PROCESS_SUBSTITUTION)
       unlink_fifo_list ();
 #endif
     }
   return (result);
 }
References _, add_unwind_protect(), array_push, begin_unwind_frame(), CMD_IGNORE_RETURN, CMD_NO_FORK, variable::context, copy_command(), currently_executing_command, DEBUG_TRAP, debugging_mode, DISCARD, dispose_command(), error_trace_mode, ERROR_TRAP, execute_command_internal(), EXECUTION_SUCCESS, find_function_def(), find_variable(), flags, free, from_return_trap, funcnest, funcnest_max, function_cell, function_line_number, function_trace_mode, GET_ARRAY_FROM_VAR, GET_LINE_NUMBER, sh_getopt_state::gs_flags, if(), init_bash_argv(), internal_error(), itos(), jump_to_top_level(), line_number, line_number_for_err_trap, lineno, loop_level, make_funcname_visible(), maybe_restore_getopt_state(), maybe_set_debug_trap(), maybe_set_error_trap(), maybe_set_return_trap(), variable::name, word_list::next, NO_PIPE, NULL, optimize_shell_function(), pop_args(), pop_context(), push_args(), push_context(), remember_args(), restore_default_signal(), return_catch, return_catch_flag, return_catch_value, RETURN_TRAP, run_debug_trap(), run_return_trap(), run_unwind_frame(), savestring(), setjmp_nosigs, sh_getopt_save_istate(), shell_compatibility_level, showing_function_line, signal_in_progress(), function_def::source_file, stop_pipeline(), SUBSHELL_COMSUB, subshell_environment, t, tc, temporary_env, this_shell_function, trace_p, TRAP_STRING, unwind_protect_int, unwind_protect_jmp_buf, unwind_protect_pointer, USE_VAR, variable_context, xfree, and xmalloc.
Referenced by execute_builtin_or_function(), execute_shell_function(), and execute_subshell_builtin_or_function().
execute_if_command()
static int execute_if_command (IF_COM * if_command) static
Definition at line 3750 of file execute_cmd.c.
 {
   int return_value, save_line_number;
   save_line_number = line_number;
   if_command->test->flags |= CMD_IGNORE_RETURN;
   return_value = execute_command (if_command->test);
   line_number = save_line_number;
   if (return_value == EXECUTION_SUCCESS)
     {
       QUIT;
       if (if_command->true_case && (if_command->flags & CMD_IGNORE_RETURN))
     if_command->true_case->flags |= CMD_IGNORE_RETURN;
       return (execute_command (if_command->true_case));
     }
   else
     {
       QUIT;
       if (if_command->false_case && (if_command->flags & CMD_IGNORE_RETURN))
     if_command->false_case->flags |= CMD_IGNORE_RETURN;
       return (execute_command (if_command->false_case));
     }
 }
References CMD_IGNORE_RETURN, execute_command(), EXECUTION_SUCCESS, if_com::false_case, if_com::flags, line_number, QUIT, if_com::test, and if_com::true_case.
Referenced by execute_command_internal().
execute_in_subshell()
static int execute_in_subshell (COMMAND * command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap * fds_to_close) static
Definition at line 1477 of file execute_cmd.c.
 {
   volatile int user_subshell, user_coproc, invert;
   int return_code, function_value, should_redir_stdin, ois, result;
   volatile COMMAND *tcom;
   USE_VAR(user_subshell);
   USE_VAR(user_coproc);
   USE_VAR(invert);
   USE_VAR(tcom);
   USE_VAR(asynchronous);
   subshell_level++;
   should_redir_stdin = (asynchronous && (command->flags & CMD_STDIN_REDIR) &&
               pipe_in == NO_PIPE &&
               stdin_redirects (command->redirects) == 0);
   invert = (command->flags & CMD_INVERT_RETURN) != 0;
   user_subshell = command->type == cm_subshell || ((command->flags & CMD_WANT_SUBSHELL) != 0);
   user_coproc = command->type == cm_coproc;
   command->flags &= ~(CMD_FORCE_SUBSHELL | CMD_WANT_SUBSHELL | CMD_INVERT_RETURN);
   /* If a command is asynchronous in a subshell (like ( foo ) & or
      the special case of an asynchronous GROUP command where the
      the subshell bit is turned on down in case cm_group: below),
      turn off `asynchronous', so that two subshells aren't spawned.
      XXX - asynchronous used to be set to 0 in this block, but that
      means that setup_async_signals was never run.  Now it's set to
      0 after subshell_environment is set appropriately and setup_async_signals
      is run.
      This seems semantically correct to me.  For example,
      ( foo ) & seems to say ``do the command `foo' in a subshell
      environment, but don't wait for that subshell to finish'',
      and "{ foo ; bar ; } &" seems to me to be like functions or
      builtins in the background, which executed in a subshell
      environment.  I just don't see the need to fork two subshells. */
   /* Don't fork again, we are already in a subshell.  A `doubly
      async' shell is not interactive, however. */
   if (asynchronous)
     {
 #if defined (JOB_CONTROL)
       /* If a construct like ( exec xxx yyy ) & is given while job
      control is active, we want to prevent exec from putting the
      subshell back into the original process group, carefully
      undoing all the work we just did in make_child. */
       original_pgrp = -1;
 #endif /* JOB_CONTROL */
       ois = interactive_shell;
       interactive_shell = 0;
       /* This test is to prevent alias expansion by interactive shells that
      run `(command) &' but to allow scripts that have enabled alias
      expansion with `shopt -s expand_alias' to continue to expand
      aliases. */
       if (ois != interactive_shell)
     expand_aliases = expaliases_flag = 0;
     }
   /* Subshells are neither login nor interactive. */
   login_shell = interactive = 0;
   /* And we're no longer in a loop. See Posix interp 842 (we are not in the
      "same execution environment"). */
   if (shell_compatibility_level > 44)
     loop_level = 0;
   if (user_subshell)
     {
       subshell_environment = SUBSHELL_PAREN;    /* XXX */
       if (asynchronous)
     subshell_environment |= SUBSHELL_ASYNC;
     }
   else
     {
       subshell_environment = 0;         /* XXX */
       if (asynchronous)
     subshell_environment |= SUBSHELL_ASYNC;
       if (pipe_in != NO_PIPE || pipe_out != NO_PIPE)
     subshell_environment |= SUBSHELL_PIPE;
       if (user_coproc)
     subshell_environment |= SUBSHELL_COPROC;
     }
   QUIT;
   CHECK_TERMSIG;
   reset_terminating_signals ();     /* in sig.c */
   /* Cancel traps, in trap.c. */
   /* Reset the signal handlers in the child, but don't free the
      trap strings.  Set a flag noting that we have to free the
      trap strings if we run trap to change a signal disposition. */
   clear_pending_traps ();
   reset_signal_handlers ();
   subshell_environment |= SUBSHELL_RESETTRAP;
   /* Note that signal handlers have been reset, so we should no longer
     reset the handler and resend trapped signals to ourselves. */
   subshell_environment &= ~SUBSHELL_IGNTRAP;
   /* We are in a subshell, so forget that we are running a trap handler or
      that the signal handler has changed (we haven't changed it!) */
   /* XXX - maybe do this for `real' signals and not ERR/DEBUG/RETURN/EXIT
      traps? */
   if (running_trap > 0)
     {
       run_trap_cleanup (running_trap - 1);
       running_trap = 0;     /* XXX - maybe leave this */
     }
   /* Make sure restore_original_signals doesn't undo the work done by
      make_child to ensure that asynchronous children are immune to SIGINT
      and SIGQUIT.  Turn off asynchronous to make sure more subshells are
      not spawned. */
   if (asynchronous)
     {
       setup_async_signals ();
       asynchronous = 0;
     }
   else
     set_sigint_handler ();
 #if defined (JOB_CONTROL)
   set_sigchld_handler ();
 #endif /* JOB_CONTROL */
   /* Delete all traces that there were any jobs running.  This is
      only for subshells. */
   without_job_control ();
   if (fds_to_close)
     close_fd_bitmap (fds_to_close);
   do_piping (pipe_in, pipe_out);
 #if defined (COPROCESS_SUPPORT)
   coproc_closeall ();
 #endif
 #if defined (PROCESS_SUBSTITUTION)
   clear_fifo_list ();       /* XXX- we haven't created any FIFOs */
 #endif
   /* If this is a user subshell, set a flag if stdin was redirected.
      This is used later to decide whether to redirect fd 0 to
      /dev/null for async commands in the subshell.  This adds more
      sh compatibility, but I'm not sure it's the right thing to do.
      Note that an input pipe to a compound command suffices to inhibit
      the implicit /dev/null redirection for asynchronous commands
      executed as part of that compound command. */
   if (user_subshell)
     {
       stdin_redir = stdin_redirects (command->redirects) || pipe_in != NO_PIPE;
 #if 0
       restore_default_signal (EXIT_TRAP);   /* XXX - reset_signal_handlers above */
 #endif
     }
   else if (shell_control_structure (command->type) && pipe_in != NO_PIPE)
     stdin_redir = 1;
   /* If this is an asynchronous command (command &), we want to
      redirect the standard input from /dev/null in the absence of
      any specific redirection involving stdin. */
   if (should_redir_stdin && stdin_redir == 0)
     async_redirect_stdin ();
 #if defined (BUFFERED_INPUT)
   /* In any case, we are not reading our command input from stdin. */
   default_buffered_input = -1;
 #endif
   /* We can't optimize away forks if one of the commands executed by the
      subshell sets an exit trap, so we set CMD_NO_FORK for simple commands
      and set CMD_TRY_OPTIMIZING for simple commands on the right side of an
      and-or or `;' list to test for optimizing forks when they are executed. */
   if (user_subshell && command->type == cm_subshell &&
       (command->flags & (CMD_TIME_PIPELINE|CMD_INVERT_RETURN)) == 0)
     optimize_subshell_command (command->value.Subshell->command);
   /* Do redirections, then dispose of them before recursive call. */
   if (command->redirects)
     {
       if (do_redirections (command->redirects, RX_ACTIVE) != 0)
     exit (invert ? EXECUTION_SUCCESS : EXECUTION_FAILURE);
       dispose_redirects (command->redirects);
       command->redirects = (REDIRECT *)NULL;
     }
   if (command->type == cm_subshell)
     tcom = command->value.Subshell->command;
   else if (user_coproc)
     tcom = command->value.Coproc->command;
   else
     tcom = command;
   if (command->flags & CMD_TIME_PIPELINE)
     tcom->flags |= CMD_TIME_PIPELINE;
   if (command->flags & CMD_TIME_POSIX)
     tcom->flags |= CMD_TIME_POSIX;
   /* Make sure the subshell inherits any CMD_IGNORE_RETURN flag. */
   if ((command->flags & CMD_IGNORE_RETURN) && tcom != command)
     tcom->flags |= CMD_IGNORE_RETURN;
   /* If this is a simple command, tell execute_disk_command that it
      might be able to get away without forking and simply exec.
      This means things like ( sleep 10 ) will only cause one fork.
      If we're timing the command or inverting its return value, however,
      we cannot do this optimization. */
   if ((user_subshell || user_coproc) && (tcom->type == cm_simple || tcom->type == cm_subshell) &&
       ((tcom->flags & CMD_TIME_PIPELINE) == 0) &&
       ((tcom->flags & CMD_INVERT_RETURN) == 0))
     {
       tcom->flags |= CMD_NO_FORK;
       if (tcom->type == cm_simple)
     tcom->value.Simple->flags |= CMD_NO_FORK;
     }
   invert = (tcom->flags & CMD_INVERT_RETURN) != 0;
   tcom->flags &= ~CMD_INVERT_RETURN;
   result = setjmp_nosigs (top_level);
   /* If we're inside a function while executing this subshell, we
      need to handle a possible `return'. */
   function_value = 0;
   if (return_catch_flag)
     function_value = setjmp_nosigs (return_catch);
   /* If we're going to exit the shell, we don't want to invert the return
      status. */
   if (result == EXITPROG || result == EXITBLTIN)
     invert = 0, return_code = last_command_exit_value;
   else if (result)
     return_code = (last_command_exit_value == EXECUTION_SUCCESS) ? EXECUTION_FAILURE : last_command_exit_value;
   else if (function_value)
     return_code = return_catch_value;
   else
     return_code = execute_command_internal ((COMMAND *)tcom, asynchronous, NO_PIPE, NO_PIPE, fds_to_close);
   /* If we are asked to, invert the return value. */
   if (invert)
     return_code = (return_code == EXECUTION_SUCCESS) ? EXECUTION_FAILURE
                              : EXECUTION_SUCCESS;
   /* If we were explicitly placed in a subshell with (), we need
      to do the `shell cleanup' things, such as running traps[0]. */
   if (user_subshell && signal_is_trapped (0))
     {
       last_command_exit_value = return_code;
       return_code = run_exit_trap ();
     }
 #if 0
   subshell_level--;     /* don't bother, caller will just exit */
 #endif
   return (return_code);
   /* NOTREACHED */
 }
References async_redirect_stdin(), CHECK_TERMSIG, clear_pending_traps(), close_fd_bitmap(), cm_coproc, cm_simple, cm_subshell, CMD_FORCE_SUBSHELL, CMD_IGNORE_RETURN, CMD_INVERT_RETURN, CMD_NO_FORK, CMD_STDIN_REDIR, CMD_TIME_PIPELINE, CMD_TIME_POSIX, CMD_WANT_SUBSHELL, dispose_redirects(), do_piping(), do_redirections(), execute_command_internal(), EXECUTION_FAILURE, EXECUTION_SUCCESS, exit(), EXIT_TRAP, EXITBLTIN, EXITPROG, expaliases_flag, expand_aliases, command::flags, if(), interactive, interactive_shell, last_command_exit_value, login_shell, loop_level, NO_PIPE, NULL, optimize_subshell_command(), original_pgrp, QUIT, command::redirects, reset_signal_handlers(), reset_terminating_signals(), restore_default_signal(), return_catch, return_catch_flag, return_catch_value, run_exit_trap(), run_trap_cleanup(), running_trap, RX_ACTIVE, set_sigchld_handler(), set_sigint_handler(), setjmp_nosigs, setup_async_signals(), shell_compatibility_level, shell_control_structure(), signal_is_trapped(), stdin_redir, stdin_redirects(), SUBSHELL_ASYNC, SUBSHELL_COPROC, subshell_environment, SUBSHELL_IGNTRAP, subshell_level, SUBSHELL_PAREN, SUBSHELL_PIPE, SUBSHELL_RESETTRAP, top_level, command::type, USE_VAR, command::value, and without_job_control().
Referenced by execute_command_internal().
execute_intern_function()
static int execute_intern_function (WORD_DESC * name, FUNCTION_DEF * funcdef) static
Definition at line 6109 of file execute_cmd.c.
 {
   SHELL_VAR *var;
   char *t;
   if (check_identifier (name, posixly_correct) == 0)
     {
       if (posixly_correct && interactive_shell == 0)
     {
       last_command_exit_value = EX_BADUSAGE;
       jump_to_top_level (ERREXIT);
     }
       return (EXECUTION_FAILURE);
     }
   if (strchr (name->word, CTLESC))  /* WHY? */
     {
       t = dequote_escapes (name->word);
       free (name->word);
       name->word = t;
     }
   /* Posix interpretation 383 */
   if (posixly_correct && find_special_builtin (name->word))
     {
       internal_error (_("`%s': is a special builtin"), name->word);
       last_command_exit_value = EX_BADUSAGE;
       jump_to_top_level (interactive_shell ? DISCARD : ERREXIT);
     }
   var = find_function (name->word);
   if (var && (readonly_p (var) || noassign_p (var)))
     {
       if (readonly_p (var))
     internal_error (_("%s: readonly function"), var->name);
       return (EXECUTION_FAILURE);
     }
 #if defined (DEBUGGER)
   bind_function_def (name->word, funcdef, 1);
 #endif
   bind_function (name->word, funcdef->command);
   return (EXECUTION_SUCCESS);
 }
References _, bind_function(), check_identifier(), function_def::command, CTLESC, dequote_escapes(), DISCARD, ERREXIT, EX_BADUSAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, find_function(), find_special_builtin(), free, interactive_shell, internal_error(), jump_to_top_level(), last_command_exit_value, noassign_p, posixly_correct, readonly_p, strchr(), t, and word_desc::word.
Referenced by execute_command_internal().
execute_null_command()
static int execute_null_command (REDIRECT * redirects, int pipe_in, int pipe_out, int async) static
Definition at line 4087 of file execute_cmd.c.
 {
   int r;
   int forcefork, fork_flags;
   REDIRECT *rd;
   for (forcefork = 0, rd = redirects; rd; rd = rd->next)
     {
       forcefork += rd->rflags & REDIR_VARASSIGN;
       /* Safety */
       forcefork += (rd->redirector.dest == 0 || fd_is_bash_input (rd->redirector.dest)) && (INPUT_REDIRECT (rd->instruction) || TRANSLATE_REDIRECT (rd->instruction) || rd->instruction == r_close_this);
     }
   if (forcefork || pipe_in != NO_PIPE || pipe_out != NO_PIPE || async)
     {
       /* We have a null command, but we really want a subshell to take
      care of it.  Just fork, do piping and redirections, and exit. */
       fork_flags = async ? FORK_ASYNC : 0;
       if (make_child ((char *)NULL, fork_flags) == 0)
     {
       /* Cancel traps, in trap.c. */
       restore_original_signals ();      /* XXX */
       do_piping (pipe_in, pipe_out);
 #if defined (COPROCESS_SUPPORT)
       coproc_closeall ();
 #endif
       interactive = 0;          /* XXX */
       subshell_environment = 0;
       if (async)
         subshell_environment |= SUBSHELL_ASYNC;
       if (pipe_in != NO_PIPE || pipe_out != NO_PIPE)
         subshell_environment |= SUBSHELL_PIPE;
       if (do_redirections (redirects, RX_ACTIVE) == 0)
         exit (EXECUTION_SUCCESS);
       else
         exit (EXECUTION_FAILURE);
     }
       else
     {
       close_pipes (pipe_in, pipe_out);
 #if defined (PROCESS_SUBSTITUTION) && defined (HAVE_DEV_FD)
       if (pipe_out == NO_PIPE)
         unlink_fifo_list ();
 #endif
       return (EXECUTION_SUCCESS);
     }
     }
   else
     {
       /* Even if there aren't any command names, pretend to do the
      redirections that are specified.  The user expects the side
      effects to take place.  If the redirections fail, then return
      failure.  Otherwise, if a command substitution took place while
      expanding the command or a redirection, return the value of that
      substitution.  Otherwise, return EXECUTION_SUCCESS. */
       r = do_redirections (redirects, RX_ACTIVE|RX_UNDOABLE);
       cleanup_redirects (redirection_undo_list);
       redirection_undo_list = (REDIRECT *)NULL;
       if (r != 0)
     return (EXECUTION_FAILURE);
       else if (last_command_subst_pid != NO_PID)
     return (last_command_exit_value);
       else
     return (EXECUTION_SUCCESS);
     }
 }
References cleanup_redirects(), close_pipes(), REDIRECTEE::dest, do_piping(), do_redirections(), EXECUTION_FAILURE, EXECUTION_SUCCESS, exit(), FORK_ASYNC, INPUT_REDIRECT, interactive, last_command_exit_value, last_command_subst_pid, make_child(), NO_PID, NO_PIPE, NULL, r_close_this, rd, REDIR_VARASSIGN, redirection_undo_list, restore_original_signals(), RX_ACTIVE, RX_UNDOABLE, SUBSHELL_ASYNC, subshell_environment, SUBSHELL_PIPE, and TRANSLATE_REDIRECT.
Referenced by execute_simple_command().
execute_pipeline()
static int execute_pipeline (COMMAND * command, int asynchronous, int pipe_in, int pipe_out, struct fd_bitmap * fds_to_close) static
Definition at line 2496 of file execute_cmd.c.
 {
   int prev, fildes[2], new_bitmap_size, dummyfd, ignore_return, exec_result;
   int lstdin, lastpipe_flag, lastpipe_jid, old_frozen, stdin_valid;
   COMMAND *cmd;
   struct fd_bitmap *fd_bitmap;
   pid_t lastpid;
 #if defined (JOB_CONTROL)
   sigset_t set, oset;
   BLOCK_CHILD (set, oset);
 #endif /* JOB_CONTROL */
   ignore_return = (command->flags & CMD_IGNORE_RETURN) != 0;
   stdin_valid = sh_validfd (0);
   prev = pipe_in;
   cmd = command;
   while (cmd && cmd->type == cm_connection &&
      cmd->value.Connection && cmd->value.Connection->connector == '|')
     {
       /* Make a pipeline between the two commands. */
       if (pipe (fildes) < 0)
     {
       sys_error (_("pipe error"));
 #if defined (JOB_CONTROL)
       terminate_current_pipeline ();
       kill_current_pipeline ();
       UNBLOCK_CHILD (oset);
 #endif /* JOB_CONTROL */
       last_command_exit_value = EXECUTION_FAILURE;
       /* The unwind-protects installed below will take care
          of closing all of the open file descriptors. */
       throw_to_top_level ();
       return (EXECUTION_FAILURE);   /* XXX */
     }
       /* Here is a problem: with the new file close-on-exec
      code, the read end of the pipe (fildes[0]) stays open
      in the first process, so that process will never get a
      SIGPIPE.  There is no way to signal the first process
      that it should close fildes[0] after forking, so it
      remains open.  No SIGPIPE is ever sent because there
      is still a file descriptor open for reading connected
      to the pipe.  We take care of that here.  This passes
      around a bitmap of file descriptors that must be
      closed after making a child process in execute_simple_command. */
       /* We need fd_bitmap to be at least as big as fildes[0].
      If fildes[0] is less than fds_to_close->size, then
      use fds_to_close->size. */
       new_bitmap_size = (fildes[0] < fds_to_close->size)
                 ? fds_to_close->size
                 : fildes[0] + 8;
       fd_bitmap = new_fd_bitmap (new_bitmap_size);
       /* Now copy the old information into the new bitmap. */
       xbcopy ((char *)fds_to_close->bitmap, (char *)fd_bitmap->bitmap, fds_to_close->size);
       /* And mark the pipe file descriptors to be closed. */
       fd_bitmap->bitmap[fildes[0]] = 1;
       /* In case there are pipe or out-of-processes errors, we
      want all these file descriptors to be closed when
      unwind-protects are run, and the storage used for the
      bitmaps freed up. */
       begin_unwind_frame ("pipe-file-descriptors");
       add_unwind_protect (dispose_fd_bitmap, fd_bitmap);
       add_unwind_protect (close_fd_bitmap, fd_bitmap);
       if (prev >= 0)
     add_unwind_protect (close, prev);
       dummyfd = fildes[1];
       add_unwind_protect (close, dummyfd);
 #if defined (JOB_CONTROL)
       add_unwind_protect (restore_signal_mask, &oset);
 #endif /* JOB_CONTROL */
       if (ignore_return && cmd->value.Connection->first)
     cmd->value.Connection->first->flags |= CMD_IGNORE_RETURN;
       execute_command_internal (cmd->value.Connection->first, asynchronous,
                 prev, fildes[1], fd_bitmap);
       if (prev >= 0)
     close (prev);
       prev = fildes[0];
       close (fildes[1]);
       dispose_fd_bitmap (fd_bitmap);
       discard_unwind_frame ("pipe-file-descriptors");
       cmd = cmd->value.Connection->second;
     }
   lastpid = last_made_pid;
   /* Now execute the rightmost command in the pipeline.  */
   if (ignore_return && cmd)
     cmd->flags |= CMD_IGNORE_RETURN;
   lastpipe_flag = 0;
   begin_unwind_frame ("lastpipe-exec");
   lstdin = -2;      /* -1 is special, meaning fd 0 is closed */
   /* If the `lastpipe' option is set with shopt, and job control is not
      enabled, execute the last element of non-async pipelines in the
      current shell environment. */
   /* prev can be 0 if fd 0 was closed when this function was executed. prev
      will never be 0 at this point if fd 0 was valid when this function was
      executed (though we check above). */
   if (lastpipe_opt && job_control == 0 && asynchronous == 0 && pipe_out == NO_PIPE && prev >= 0)
     {
       /* -1 is a special value meaning to close stdin */
       lstdin = (prev > 0 && stdin_valid) ? move_to_high_fd (0, 1, -1) : -1;
       if (lstdin > 0 || lstdin == -1)
     {
       do_piping (prev, pipe_out);
       prev = NO_PIPE;
       add_unwind_protect (restore_stdin, lstdin);
       lastpipe_flag = 1;
       old_frozen = freeze_jobs_list ();
       lastpipe_jid = stop_pipeline (0, (COMMAND *)NULL);    /* XXX */
       add_unwind_protect (lastpipe_cleanup, old_frozen);
 #if defined (JOB_CONTROL)
       UNBLOCK_CHILD (oset);     /* XXX */
 #endif
     }
       if (cmd)
     cmd->flags |= CMD_LASTPIPE;
     }
   if (prev >= 0)
     add_unwind_protect (close, prev);
   exec_result = execute_command_internal (cmd, asynchronous, prev, pipe_out, fds_to_close);
   if (prev >= 0)
     close (prev);
   if (lstdin > 0 || lstdin == -1)
     restore_stdin (lstdin);
 #if defined (JOB_CONTROL)
   UNBLOCK_CHILD (oset);
 #endif
   QUIT;
   if (lastpipe_flag)
     {
 #if defined (JOB_CONTROL)
       if (INVALID_JOB (lastpipe_jid) == 0)
         {
           append_process (savestring (the_printed_command_except_trap), dollar_dollar_pid, exec_result, lastpipe_jid);
           lstdin = wait_for (lastpid, 0);
         }
       else
     {
       lstdin = wait_for_single_pid (lastpid, 0);        /* checks bgpids list */
       if (lstdin > 256)     /* error sentinel */
         lstdin = 127;
     }
 #else
       lstdin = wait_for (lastpid, 0);
 #endif
 #if defined (JOB_CONTROL)
       /* If wait_for removes the job from the jobs table, use result of last
      command as pipeline's exit status as usual.  The jobs list can get
      frozen and unfrozen at inconvenient times if there are multiple pipelines
      running simultaneously. */
       if (INVALID_JOB (lastpipe_jid) == 0)
     exec_result = job_exit_status (lastpipe_jid);
       else if (pipefail_opt)
     exec_result = exec_result | lstdin; /* XXX */
       /* otherwise we use exec_result */
 #endif
       set_jobs_list_frozen (old_frozen);
     }
   discard_unwind_frame ("lastpipe-exec");
   return (exec_result);
 }
References _, add_unwind_protect(), append_process(), begin_unwind_frame(), fd_bitmap::bitmap, BLOCK_CHILD, close(), close_fd_bitmap(), cm_connection, cmd, CMD_IGNORE_RETURN, CMD_LASTPIPE, discard_unwind_frame(), dispose_fd_bitmap(), do_piping(), dollar_dollar_pid, execute_command_internal(), EXECUTION_FAILURE, command::flags, freeze_jobs_list(), INVALID_JOB, job_control, job_exit_status(), kill_current_pipeline(), last_command_exit_value, last_made_pid, lastpipe_cleanup(), lastpipe_opt, move_to_high_fd(), new_fd_bitmap(), NO_PIPE, NULL, pipefail_opt, QUIT, restore_stdin(), savestring(), set_jobs_list_frozen(), sh_validfd(), fd_bitmap::size, stop_pipeline(), sys_error(), terminate_current_pipeline(), the_printed_command_except_trap, throw_to_top_level(), UNBLOCK_CHILD, wait_for(), wait_for_single_pid(), and xbcopy().
Referenced by execute_connection().
execute_shell_function()
int execute_shell_function (SHELL_VAR * var, WORD_LIST * words)
Definition at line 5290 of file execute_cmd.c.
 {
   int ret;
   struct fd_bitmap *bitmap;
   bitmap = new_fd_bitmap (FD_BITMAP_DEFAULT_SIZE);
   begin_unwind_frame ("execute-shell-function");
   add_unwind_protect (dispose_fd_bitmap, (char *)bitmap);
   ret = execute_function (var, words, 0, bitmap, 0, 0);
   dispose_fd_bitmap (bitmap);
   discard_unwind_frame ("execute-shell-function");
   return ret;
 }
References add_unwind_protect(), begin_unwind_frame(), fd_bitmap::bitmap, discard_unwind_frame(), dispose_fd_bitmap(), execute_function(), FD_BITMAP_DEFAULT_SIZE, and new_fd_bitmap().
Referenced by execute_disk_command().
execute_shell_script()
static int execute_shell_script (char * sample, int sample_len, char * command, char ** args, char ** env) static
Definition at line 5821 of file execute_cmd.c.
 {
   char *execname, *firstarg;
   int i, start, size_increment, larry;
   /* Find the name of the interpreter to exec. */
   execname = getinterp (sample, sample_len, &i);
   size_increment = 1;
   /* Now the argument, if any. */
   for (firstarg = (char *)NULL, start = i; WHITECHAR(i); i++)
     ;
   /* If there is more text on the line, then it is an argument for the
      interpreter. */
   if (STRINGCHAR(i))
     {
       for (start = i; STRINGCHAR(i); i++)
     ;
       firstarg = substring ((char *)sample, start, i);
       size_increment = 2;
     }
   larry = strvec_len (args) + size_increment;
   args = strvec_resize (args, larry + 1);
   for (i = larry - 1; i; i--)
     args[i] = args[i - size_increment];
   args[0] = execname;
   if (firstarg)
     {
       args[1] = firstarg;
       args[2] = command;
     }
   else
     args[1] = command;
   args[larry] = (char *)NULL;
   return (shell_execve (execname, args, env));
 }
References env, execname, getinterp(), i, NULL, shell_execve(), start, STRINGCHAR, strvec_len(), strvec_resize(), substring(), and WHITECHAR.
Referenced by shell_execve().
execute_simple_command()
static int execute_simple_command (SIMPLE_COM * simple_command, int pipe_in, int pipe_out, int async, struct fd_bitmap * fds_to_close) static
Definition at line 4355 of file execute_cmd.c.
 {
   WORD_LIST *words, *lastword;
   char *command_line, *lastarg, *temp;
   int first_word_quoted, result, builtin_is_special, already_forked, dofork;
   int fork_flags, cmdflags;
   pid_t old_last_async_pid;
   sh_builtin_func_t *builtin;
   SHELL_VAR *func;
   volatile int old_builtin, old_command_builtin;
   result = EXECUTION_SUCCESS;
   special_builtin_failed = builtin_is_special = 0;
   command_line = (char *)0;
   QUIT;
   /* If we're in a function, update the line number information. */
   if (variable_context && interactive_shell && sourcelevel == 0)
     {
       /* line numbers in a function start at 1 */
       line_number -= function_line_number - 1;
       if (line_number <= 0)
     line_number = 1;
     }
   /* Remember what this command line looks like at invocation. */
   command_string_index = 0;
   print_simple_command (simple_command);
 #if 0
   if (signal_in_progress (DEBUG_TRAP) == 0 && (this_command_name == 0 || (STREQ (this_command_name, "trap") == 0)))
 #else
   if (signal_in_progress (DEBUG_TRAP) == 0 && running_trap == 0)
 #endif
     {
       FREE (the_printed_command_except_trap);
       the_printed_command_except_trap = the_printed_command ? savestring (the_printed_command) : (char *)0;
     }
   /* Run the debug trap before each simple command, but do it after we
      update the line number information. */
   result = run_debug_trap ();
 #if defined (DEBUGGER)
   /* In debugging mode, if the DEBUG trap returns a non-zero status, we
      skip the command. */
   if (debugging_mode && result != EXECUTION_SUCCESS)
     return (EXECUTION_SUCCESS);
 #endif
   cmdflags = simple_command->flags;
   first_word_quoted =
     simple_command->words ? (simple_command->words->word->flags & W_QUOTED) : 0;
   last_command_subst_pid = NO_PID;
   old_last_async_pid = last_asynchronous_pid;
   already_forked = 0;
   /* If we're in a pipeline or run in the background, set DOFORK so we
      make the child early, before word expansion.  This keeps assignment
      statements from affecting the parent shell's environment when they
      should not. */
   dofork = pipe_in != NO_PIPE || pipe_out != NO_PIPE || async;
   /* Something like `%2 &' should restart job 2 in the background, not cause
      the shell to fork here. */
   if (dofork && pipe_in == NO_PIPE && pipe_out == NO_PIPE &&
     simple_command->words && simple_command->words->word &&
     simple_command->words->word->word &&
     (simple_command->words->word->word[0] == '%'))
     dofork = 0;
   if (dofork)
     {
       char *p;
       /* Do this now, because execute_disk_command will do it anyway in the
      vast majority of cases. */
       maybe_make_export_env ();
       /* Don't let a DEBUG trap overwrite the command string to be saved with
      the process/job associated with this child. */
       fork_flags = async ? FORK_ASYNC : 0;
       if (make_child (p = savestring (the_printed_command_except_trap), fork_flags) == 0)
     {
       already_forked = 1;
       cmdflags |= CMD_NO_FORK;
       /* We redo some of what make_child() does with SUBSHELL_IGNTRAP */
       subshell_environment = SUBSHELL_FORK|SUBSHELL_IGNTRAP;    /* XXX */
       if (pipe_in != NO_PIPE || pipe_out != NO_PIPE)
         subshell_environment |= SUBSHELL_PIPE;
       if (async)
         subshell_environment |= SUBSHELL_ASYNC;
       /* We need to do this before piping to handle some really
          pathological cases where one of the pipe file descriptors
          is < 2. */
       if (fds_to_close)
         close_fd_bitmap (fds_to_close);
       /* If we fork because of an input pipe, note input pipe for later to
          inhibit async commands from redirecting stdin from /dev/null */
       stdin_redir |= pipe_in != NO_PIPE;
       do_piping (pipe_in, pipe_out);
       pipe_in = pipe_out = NO_PIPE;
 #if defined (COPROCESS_SUPPORT)
       coproc_closeall ();
 #endif
       last_asynchronous_pid = old_last_async_pid;
       if (async)
         subshell_level++;       /* not for pipes yet */
 #if defined (JOB_CONTROL)
       FREE (p);         /* child doesn't use pointer */
 #endif
     }
       else
     {
       /* Don't let simple commands that aren't the last command in a
          pipeline change $? for the rest of the pipeline (or at all). */
       if (pipe_out != NO_PIPE)
         result = last_command_exit_value;
       close_pipes (pipe_in, pipe_out);
       command_line = (char *)NULL;      /* don't free this. */
       return (result);
     }
     }
   QUIT;     /* XXX */
   /* If we are re-running this as the result of executing the `command'
      builtin, do not expand the command words a second time. */
   if ((cmdflags & CMD_INHIBIT_EXPANSION) == 0)
     {
       current_fds_to_close = fds_to_close;
       fix_assignment_words (simple_command->words);
 #if defined (ARRAY_VARS)
       fix_arrayref_words (simple_command->words);
 #endif
       /* Pass the ignore return flag down to command substitutions */
       if (cmdflags & CMD_IGNORE_RETURN) /* XXX */
     comsub_ignore_return++;
       words = expand_words (simple_command->words);
       if (cmdflags & CMD_IGNORE_RETURN)
     comsub_ignore_return--;
       current_fds_to_close = (struct fd_bitmap *)NULL;
     }
   else
     words = copy_word_list (simple_command->words);
   /* It is possible for WORDS not to have anything left in it.
      Perhaps all the words consisted of `$foo', and there was
      no variable `$foo'. */
   if (words == 0)
     {
       this_command_name = 0;
       result = execute_null_command (simple_command->redirects,
                      pipe_in, pipe_out,
                      already_forked ? 0 : async);
       if (already_forked)
     sh_exit (result);
       else
     {
       bind_lastarg ((char *)NULL);
       set_pipestatus_from_exit (result);
       return (result);
     }
     }
   lastarg = (char *)NULL;
   begin_unwind_frame ("simple-command");
   if (echo_command_at_execute && (cmdflags & CMD_COMMAND_BUILTIN) == 0)
     xtrace_print_word_list (words, 1);
   builtin = (sh_builtin_func_t *)NULL;
   func = (SHELL_VAR *)NULL;
   /* This test is still here in case we want to change the command builtin
      handler code below to recursively call execute_simple_command (after
      modifying the simple_command struct). */
   if ((cmdflags & CMD_NO_FUNCTIONS) == 0)
     {
       /* Posix.2 says special builtins are found before functions.  We
      don't set builtin_is_special anywhere other than here, because
      this path is followed only when the `command' builtin is *not*
      being used, and we don't want to exit the shell if a special
      builtin executed with `command builtin' fails.  `command' is not
      a special builtin. */
       if (posixly_correct)
     {
       builtin = find_special_builtin (words->word->word);
       if (builtin)
         builtin_is_special = 1;
     }
       if (builtin == 0)
     func = find_function (words->word->word);
     }
   /* What happens in posix mode when an assignment preceding a command name
      fails.  This should agree with the code in execute_cmd.c:
      do_assignment_statements(), even though I don't think it's executed any
      more. */
   if (posixly_correct && tempenv_assign_error)
     {
 #if defined (DEBUG)
       /* I don't know if this clause is ever executed, so let's check */
 itrace("execute_simple_command: posix mode tempenv assignment error");
 #endif
       last_command_exit_value = EXECUTION_FAILURE;
 #if defined (STRICT_POSIX)
       jump_to_top_level ((interactive_shell == 0) ? FORCE_EOF : DISCARD);
 #else
       if (interactive_shell == 0 && builtin_is_special)
     jump_to_top_level (FORCE_EOF);
       else if (interactive_shell == 0)
     jump_to_top_level (DISCARD);    /* XXX - maybe change later */
       else
     jump_to_top_level (DISCARD);
 #endif
     }
   tempenv_assign_error = 0; /* don't care about this any more */
   /* This is where we handle the command builtin as a pseudo-reserved word
      prefix. This allows us to optimize away forks if we can. */
   old_command_builtin = -1;
   if (builtin == 0 && func == 0)
     {
       WORD_LIST *disposer, *l;
       int cmdtype;
       builtin = find_shell_builtin (words->word->word);
       while (builtin == command_builtin)
     {
       disposer = words;
       cmdtype = 0;
       words = check_command_builtin (words, &cmdtype);
       if (cmdtype > 0)  /* command -p [--] words */
         {
           for (l = disposer; l->next != words; l = l->next)
         ;
           l->next = 0;
           dispose_words (disposer);
           cmdflags |= CMD_COMMAND_BUILTIN | CMD_NO_FUNCTIONS;
           if (cmdtype == 2)
         cmdflags |= CMD_STDPATH;
           builtin = find_shell_builtin (words->word->word);
         }
       else
         break;
     }
       if (cmdflags & CMD_COMMAND_BUILTIN)
     {
       old_command_builtin = executing_command_builtin;
       unwind_protect_int (executing_command_builtin);
       executing_command_builtin |= 1;
     }
       builtin = 0;
     }
   add_unwind_protect (dispose_words, words);
   QUIT;
   /* Bind the last word in this command to "$_" after execution. */
   for (lastword = words; lastword->next; lastword = lastword->next)
     ;
   lastarg = lastword->word->word;
 #if defined (JOB_CONTROL)
   /* Is this command a job control related thing? */
   if (words->word->word[0] == '%' && already_forked == 0)
     {
       this_command_name = async ? "bg" : "fg";
       last_shell_builtin = this_shell_builtin;
       this_shell_builtin = builtin_address (this_command_name);
       result = (*this_shell_builtin) (words);
       goto return_result;
     }
   /* One other possibililty.  The user may want to resume an existing job.
      If they do, find out whether this word is a candidate for a running
      job. */
   if (job_control && already_forked == 0 && async == 0 &&
     !first_word_quoted &&
     !words->next &&
     words->word->word[0] &&
     !simple_command->redirects &&
     pipe_in == NO_PIPE &&
     pipe_out == NO_PIPE &&
     (temp = get_string_value ("auto_resume")))
     {
       int job, jflags, started_status;
       jflags = JM_STOPPED|JM_FIRSTMATCH;
       if (STREQ (temp, "exact"))
     jflags |= JM_EXACT;
       else if (STREQ (temp, "substring"))
     jflags |= JM_SUBSTRING;
       else
     jflags |= JM_PREFIX;
       job = get_job_by_name (words->word->word, jflags);
       if (job != NO_JOB)
     {
       run_unwind_frame ("simple-command");
       this_command_name = "fg";
       last_shell_builtin = this_shell_builtin;
       this_shell_builtin = builtin_address ("fg");
       started_status = start_job (job, 1);
       return ((started_status < 0) ? EXECUTION_FAILURE : started_status);
     }
     }
 #endif /* JOB_CONTROL */
 run_builtin:
   /* Remember the name of this command globally. */
   this_command_name = words->word->word;
   QUIT;
   /* This command could be a shell builtin or a user-defined function.
      We have already found special builtins by this time, so we do not
      set builtin_is_special.  If this is a function or builtin, and we
      have pipes, then fork a subshell in here.  Otherwise, just execute
      the command directly. */
   if (func == 0 && builtin == 0)
     builtin = find_shell_builtin (this_command_name);
   last_shell_builtin = this_shell_builtin;
   this_shell_builtin = builtin;
   if (builtin || func)
     {
       if (builtin)
         {
       old_builtin = executing_builtin;
       unwind_protect_int (executing_builtin);   /* modified in execute_builtin */
       if (old_command_builtin == -1)    /* sentinel, can be set above */
         {
           old_command_builtin = executing_command_builtin;
           unwind_protect_int (executing_command_builtin);   /* ditto and set above */
         }
         }
       if (already_forked)
     {
       /* reset_terminating_signals (); */   /* XXX */
       /* Reset the signal handlers in the child, but don't free the
          trap strings.  Set a flag noting that we have to free the
          trap strings if we run trap to change a signal disposition. */
       reset_signal_handlers ();
       subshell_environment |= SUBSHELL_RESETTRAP;
       subshell_environment &= ~SUBSHELL_IGNTRAP;
       if (async)
         {
           if ((cmdflags & CMD_STDIN_REDIR) &&
             pipe_in == NO_PIPE &&
             (stdin_redirects (simple_command->redirects) == 0))
         async_redirect_stdin ();
           setup_async_signals ();
         }
       if (async == 0)
         subshell_level++;
       execute_subshell_builtin_or_function
         (words, simple_command->redirects, builtin, func,
          pipe_in, pipe_out, async, fds_to_close,
          cmdflags);
       subshell_level--;
     }
       else
     {
       result = execute_builtin_or_function
         (words, builtin, func, simple_command->redirects, fds_to_close,
          cmdflags);
       if (builtin)
         {
           if (result > EX_SHERRBASE)
         {
           switch (result)
             {
             case EX_REDIRFAIL:
             case EX_BADASSIGN:
             case EX_EXPFAIL:
               /* These errors cause non-interactive posix mode shells to exit */
               if (posixly_correct && builtin_is_special && interactive_shell == 0)
             {
               last_command_exit_value = EXECUTION_FAILURE;
               jump_to_top_level (ERREXIT);
             }
               break;
             case EX_DISKFALLBACK:
               /* XXX - experimental */
               executing_builtin = old_builtin;
               executing_command_builtin = old_command_builtin;
               builtin = 0;
               /* The redirections have already been `undone', so this
              will have to do them again. But piping is forever. */
               pipe_in = pipe_out = -1;
               goto execute_from_filesystem;
             }
           result = builtin_status (result);
           if (builtin_is_special)
             special_builtin_failed = 1; /* XXX - take command builtin into account? */
         }
           /* In POSIX mode, if there are assignment statements preceding
          a special builtin, they persist after the builtin
          completes. */
           if (posixly_correct && builtin_is_special && temporary_env)
         merge_temporary_env ();
         }
       else      /* function */
         {
           if (result == EX_USAGE)
         result = EX_BADUSAGE;
           else if (result > EX_SHERRBASE)
         result = builtin_status (result);
         }
       set_pipestatus_from_exit (result);
       goto return_result;
     }
     }
   if (autocd && interactive && words->word && is_dirname (words->word->word))
     {
       words = make_word_list (make_word ("--"), words);
       words = make_word_list (make_word ("cd"), words);
       xtrace_print_word_list (words, 0);
       func = find_function ("cd");
       goto run_builtin;
     }
 execute_from_filesystem:
   if (command_line == 0)
     command_line = savestring (the_printed_command_except_trap ? the_printed_command_except_trap : "");
 #if defined (PROCESS_SUBSTITUTION)
   /* The old code did not test already_forked and only did this if
      subshell_environment&SUBSHELL_COMSUB != 0 (comsubs and procsubs). Other
      uses of the no-fork optimization left FIFOs in $TMPDIR */
   if (already_forked == 0 && (cmdflags & CMD_NO_FORK) && fifos_pending() > 0)
     cmdflags &= ~CMD_NO_FORK;
 #endif
   result = execute_disk_command (words, simple_command->redirects, command_line,
             pipe_in, pipe_out, async, fds_to_close,
             cmdflags);
  return_result:
   bind_lastarg (lastarg);
   FREE (command_line);
   dispose_words (words);
   if (builtin)
     {
       executing_builtin = old_builtin;
       executing_command_builtin = old_command_builtin;
     }
   discard_unwind_frame ("simple-command");
   this_command_name = (char *)NULL; /* points to freed memory now */
   return (result);
 }
References add_unwind_protect(), async_redirect_stdin(), autocd, begin_unwind_frame(), bind_lastarg(), builtin, builtin_address(), builtin_status(), check_command_builtin(), close_fd_bitmap(), close_pipes(), CMD_COMMAND_BUILTIN, CMD_IGNORE_RETURN, CMD_INHIBIT_EXPANSION, CMD_NO_FORK, CMD_NO_FUNCTIONS, CMD_STDIN_REDIR, CMD_STDPATH, command_string_index, comsub_ignore_return, copy_word_list(), current_fds_to_close, DEBUG_TRAP, debugging_mode, DISCARD, discard_unwind_frame(), dispose_words(), do_piping(), echo_command_at_execute, ERREXIT, EX_BADASSIGN, EX_BADUSAGE, EX_DISKFALLBACK, EX_EXPFAIL, EX_REDIRFAIL, EX_SHERRBASE, EX_USAGE, execute_builtin_or_function(), execute_disk_command(), execute_null_command(), execute_subshell_builtin_or_function(), executing_builtin, executing_command_builtin, EXECUTION_FAILURE, EXECUTION_SUCCESS, expand_words(), find_function(), find_shell_builtin(), find_special_builtin(), fix_assignment_words(), word_desc::flags, simple_com::flags, FORCE_EOF, FORK_ASYNC, FREE, function_line_number, get_string_value(), interactive, interactive_shell, is_dirname(), JM_EXACT, JM_FIRSTMATCH, JM_PREFIX, JM_STOPPED, JM_SUBSTRING, job_control, jump_to_top_level(), l, last_asynchronous_pid, last_command_exit_value, last_command_subst_pid, last_shell_builtin, line_number, make_child(), make_word(), make_word_list(), maybe_make_export_env(), merge_temporary_env(), word_list::next, NO_JOB, NO_PID, NO_PIPE, NULL, p, posixly_correct, print_simple_command(), QUIT, simple_com::redirects, reset_signal_handlers(), run_debug_trap(), run_unwind_frame(), running_trap, savestring(), set_pipestatus_from_exit(), setup_async_signals(), sh_exit(), signal_in_progress(), sourcelevel, special_builtin_failed, start_job(), stdin_redir, stdin_redirects(), STREQ, SUBSHELL_ASYNC, subshell_environment, SUBSHELL_FORK, SUBSHELL_IGNTRAP, subshell_level, SUBSHELL_PIPE, SUBSHELL_RESETTRAP, tempenv_assign_error, temporary_env, the_printed_command, the_printed_command_except_trap, this_command_name, this_shell_builtin, unwind_protect_int, variable_context, W_QUOTED, word_desc::word, word_list::word, simple_com::words, and xtrace_print_word_list().
Referenced by execute_command_internal().
execute_subshell_builtin_or_function()
static void execute_subshell_builtin_or_function (WORD_LIST * words, REDIRECT * redirects, sh_builtin_func_t * builtin, SHELL_VAR * var, int pipe_in, int pipe_out, int async, struct fd_bitmap * fds_to_close, int flags) static
Definition at line 5316 of file execute_cmd.c.
 {
   int result, r, funcvalue;
 #if defined (JOB_CONTROL)
   int jobs_hack;
   jobs_hack = (builtin == jobs_builtin) &&
         ((subshell_environment & SUBSHELL_ASYNC) == 0 || pipe_out != NO_PIPE);
 #endif
   /* A subshell is neither a login shell nor interactive. */
   login_shell = interactive = 0;
   if (builtin == eval_builtin)
     evalnest = 0;
   else if (builtin == source_builtin)
     sourcenest = 0;
   if (async)
     subshell_environment |= SUBSHELL_ASYNC;
   if (pipe_in != NO_PIPE || pipe_out != NO_PIPE)
     subshell_environment |= SUBSHELL_PIPE;
   maybe_make_export_env (); /* XXX - is this needed? */
 #if defined (JOB_CONTROL)
   /* Eradicate all traces of job control after we fork the subshell, so
      all jobs begun by this subshell are in the same process group as
      the shell itself. */
   /* Allow the output of `jobs' to be piped. */
   if (jobs_hack)
     kill_current_pipeline ();
   else
     without_job_control ();
   set_sigchld_handler ();
 #else
   without_job_control ();
 #endif /* JOB_CONTROL */
   set_sigint_handler ();
   if (fds_to_close)
     close_fd_bitmap (fds_to_close);
   do_piping (pipe_in, pipe_out);
   if (do_redirections (redirects, RX_ACTIVE) != 0)
     exit (EXECUTION_FAILURE);
   if (builtin)
     {
       /* Give builtins a place to jump back to on failure,
      so we don't go back up to main(). */
       result = setjmp_nosigs (top_level);
       /* Give the return builtin a place to jump to when executed in a subshell
          or pipeline */
       funcvalue = 0;
       if (return_catch_flag && builtin == return_builtin)
         funcvalue = setjmp_nosigs (return_catch);
       if (result == EXITPROG || result == EXITBLTIN)
     subshell_exit (last_command_exit_value);
       else if (result)
     subshell_exit (EXECUTION_FAILURE);
       else if (funcvalue)
     subshell_exit (return_catch_value);
       else
     {
       r = execute_builtin (builtin, words, flags, 1);
       fflush (stdout);
       if (r == EX_USAGE)
         r = EX_BADUSAGE;
       /* XXX - experimental */
       else if (r == EX_DISKFALLBACK)
         {
           char *command_line;
           command_line = savestring (the_printed_command_except_trap ? the_printed_command_except_trap : "");
           r = execute_disk_command (words, (REDIRECT *)0, command_line,
           -1, -1, async, (struct fd_bitmap *)0, flags|CMD_NO_FORK);
         }
       subshell_exit (r);
     }
     }
   else
     {
       r = execute_function (var, words, flags, fds_to_close, async, 1);
       fflush (stdout);
       subshell_exit (r);
     }
 }
References close_fd_bitmap(), CMD_NO_FORK, do_piping(), do_redirections(), evalnest, EX_BADUSAGE, EX_DISKFALLBACK, EX_USAGE, execute_builtin(), execute_disk_command(), execute_function(), EXECUTION_FAILURE, exit(), EXITBLTIN, EXITPROG, fflush(), flags, interactive, kill_current_pipeline(), last_command_exit_value, login_shell, maybe_make_export_env(), NO_PIPE, return_catch, return_catch_flag, return_catch_value, RX_ACTIVE, savestring(), set_sigchld_handler(), set_sigint_handler(), setjmp_nosigs, sourcenest, stdout, SUBSHELL_ASYNC, subshell_environment, subshell_exit(), SUBSHELL_PIPE, the_printed_command_except_trap, top_level, and without_job_control().
Referenced by execute_simple_command().
execute_until_command()
static int execute_until_command (WHILE_COM * while_command) static
Definition at line 3671 of file execute_cmd.c.
 {
   return (execute_while_or_until (while_command, CMD_UNTIL));
 }
References CMD_UNTIL, and execute_while_or_until().
Referenced by execute_command_internal().
execute_while_command()
static int execute_while_command (WHILE_COM * while_command) static
Definition at line 3663 of file execute_cmd.c.
 {
   return (execute_while_or_until (while_command, CMD_WHILE));
 }
References CMD_WHILE, and execute_while_or_until().
Referenced by execute_command_internal().
execute_while_or_until()
static int execute_while_or_until (WHILE_COM * while_command, int type) static
Definition at line 3683 of file execute_cmd.c.
 {
   int return_value, body_status;
   body_status = EXECUTION_SUCCESS;
   loop_level++;
   while_command->test->flags |= CMD_IGNORE_RETURN;
   if (while_command->flags & CMD_IGNORE_RETURN)
     while_command->action->flags |= CMD_IGNORE_RETURN;
   while (1)
     {
       return_value = execute_command (while_command->test);
       REAP ();
       /* Need to handle `break' in the test when we would break out of the
          loop.  The job control code will set `breaking' to loop_level
          when a job in a loop is stopped with SIGTSTP.  If the stopped job
          is in the loop test, `breaking' will not be reset unless we do
          this, and the shell will cease to execute commands.  The same holds
          true for `continue'. */
       if (type == CMD_WHILE && return_value != EXECUTION_SUCCESS)
     {
       if (breaking)
         breaking--;
       if (continuing)
         continuing--;
       break;
     }
       if (type == CMD_UNTIL && return_value == EXECUTION_SUCCESS)
     {
       if (breaking)
         breaking--;
       if (continuing)
         continuing--;
       break;
     }
       QUIT;
       body_status = execute_command (while_command->action);
       QUIT;
       if (breaking)
     {
       breaking--;
       break;
     }
       if (continuing)
     {
       continuing--;
       if (continuing)
         break;
     }
     }
   loop_level--;
   return (body_status);
 }
References while_com::action, breaking, CMD_IGNORE_RETURN, CMD_UNTIL, CMD_WHILE, continuing, execute_command(), EXECUTION_SUCCESS, while_com::flags, loop_level, QUIT, REAP, while_com::test, and type.
Referenced by execute_until_command(), and execute_while_command().
executing_line_number()
int executing_line_number ()
Definition at line 368 of file execute_cmd.c.
 {
   if (executing && showing_function_line == 0 &&
       (variable_context == 0 || interactive_shell == 0) &&
       currently_executing_command)
     {
 #if defined (COND_COMMAND)
       if (currently_executing_command->type == cm_cond)
     return currently_executing_command->value.Cond->line;
 #endif
 #if defined (DPAREN_ARITHMETIC)
       if (currently_executing_command->type == cm_arith)
     return currently_executing_command->value.Arith->line;
 #endif
 #if defined (ARITH_FOR_COMMAND)
       if (currently_executing_command->type == cm_arith_for)
     return currently_executing_command->value.ArithFor->line;
 #endif
       return line_number;
     }
   else
     return line_number;
 }
References cm_arith, cm_arith_for, cm_cond, currently_executing_command, executing, interactive_shell, line_number, showing_function_line, and variable_context.
Referenced by _evalfile(), builtin_error_prolog(), error_prolog(), get_lineno(), and open_shell_script().
fix_assignment_words()
static void fix_assignment_words (WORD_LIST * words) static
Definition at line 4166 of file execute_cmd.c.
 {
   WORD_LIST *w, *wcmd;
   struct builtin *b;
   int assoc, global, array, integer;
   if (words == 0)
     return;
   b = 0;
   assoc = global = array = integer = 0;
   /* Skip over assignment statements preceding a command name */
   wcmd = words;
   for (wcmd = words; wcmd; wcmd = wcmd->next)
     if ((wcmd->word->flags & W_ASSIGNMENT) == 0)
       break;
   /* Posix (post-2008) says that `command' doesn't change whether
      or not the builtin it shadows is a `declaration command', even
      though it removes other special builtin properties.  In Posix
      mode, we skip over one or more instances of `command' and
      deal with the next word as the assignment builtin. */
   while (posixly_correct && wcmd && wcmd->word && wcmd->word->word && STREQ (wcmd->word->word, "command"))
     wcmd = wcmd->next;
   for (w = wcmd; w; w = w->next)
     if (w->word->flags & W_ASSIGNMENT)
       {
         /* Lazy builtin lookup, only do it if we find an assignment */
     if (b == 0)
       {
         b = builtin_address_internal (wcmd->word->word, 0);
         if (b == 0 || (b->flags & ASSIGNMENT_BUILTIN) == 0)
           return;
         else if (b && (b->flags & ASSIGNMENT_BUILTIN))
           wcmd->word->flags |= W_ASSNBLTIN;
       }
     w->word->flags |= (W_NOSPLIT|W_NOGLOB|W_TILDEEXP|W_ASSIGNARG);
 #if defined (ARRAY_VARS)
     if (assoc)
       w->word->flags |= W_ASSIGNASSOC;
     if (array)
       w->word->flags |= W_ASSIGNARRAY;
 #endif
     if (global)
       w->word->flags |= W_ASSNGLOBAL;
     /* If we have an assignment builtin that does not create local variables,
        make sure we create global variables even if we internally call
        `declare'.  The CHKLOCAL flag means to set attributes or values on
        an existing local variable, if there is one. */
     if (b && ((b->flags & (ASSIGNMENT_BUILTIN|LOCALVAR_BUILTIN)) == ASSIGNMENT_BUILTIN))
       w->word->flags |= W_ASSNGLOBAL|W_CHKLOCAL;
     else if (b && (b->flags & ASSIGNMENT_BUILTIN) && (b->flags & LOCALVAR_BUILTIN) && variable_context)
       w->word->flags |= W_FORCELOCAL;
       }
 #if defined (ARRAY_VARS)
     /* Note that we saw an associative array option to a builtin that takes
        assignment statements.  This is a bit of a kludge. */
     else if (w->word->word[0] == '-' && (strpbrk (w->word->word+1, "Aag") != 0))
 #else
     else if (w->word->word[0] == '-' && strchr (w->word->word+1, 'g'))
 #endif
       {
     if (b == 0)
       {
         b = builtin_address_internal (wcmd->word->word, 0);
         if (b == 0 || (b->flags & ASSIGNMENT_BUILTIN) == 0)
           return;
         else if (b && (b->flags & ASSIGNMENT_BUILTIN))
           wcmd->word->flags |= W_ASSNBLTIN;
       }
     if ((wcmd->word->flags & W_ASSNBLTIN) && strchr (w->word->word+1, 'A'))
       assoc = 1;
     else if ((wcmd->word->flags & W_ASSNBLTIN) && strchr (w->word->word+1, 'a'))
       array = 1;
     if ((wcmd->word->flags & W_ASSNBLTIN) && strchr (w->word->word+1, 'g'))
       global = 1;
       }
 }
References ASSIGNMENT_BUILTIN, builtin_address_internal(), builtin::flags, word_desc::flags, if(), LOCALVAR_BUILTIN, word_list::next, posixly_correct, strchr(), STREQ, strpbrk(), variable_context, w, W_ASSIGNARG, W_ASSIGNARRAY, W_ASSIGNASSOC, W_ASSIGNMENT, W_ASSNBLTIN, W_ASSNGLOBAL, W_CHKLOCAL, W_FORCELOCAL, W_NOGLOB, W_NOSPLIT, W_TILDEEXP, word_desc::word, and word_list::word.
Referenced by execute_simple_command().
getinterp()
static char* getinterp (char * sample, int sample_len, int * endp) static
Definition at line 5787 of file execute_cmd.c.
 {
   register int i;
   char *execname;
   int start;
   /* Find the name of the interpreter to exec. */
   for (i = 2; i < sample_len && whitespace (sample[i]); i++)
     ;
   for (start = i; STRINGCHAR(i); i++)
     ;
   execname = substring (sample, start, i);
   if (endp)
     *endp = i;
   return execname;
 }
References execname, i, start, STRINGCHAR, substring(), and whitespace.
Referenced by execute_shell_script(), and shell_execve().
initialize_subshell()
static void initialize_subshell () static
Definition at line 5874 of file execute_cmd.c.
 {
 #if defined (ALIAS)
   /* Forget about any aliases that we knew of.  We are in a subshell. */
   delete_all_aliases ();
 #endif /* ALIAS */
 #if defined (HISTORY)
   /* Forget about the history lines we have read.  This is a non-interactive
      subshell. */
   history_lines_this_session = 0;
 #endif
   /* Forget about the way job control was working. We are in a subshell. */
   without_job_control ();
 #if defined (JOB_CONTROL)
   set_sigchld_handler ();
   init_job_stats ();
 #endif /* JOB_CONTROL */
   /* Reset the values of the shell flags and options. */
   reset_shell_flags ();
   reset_shell_options ();
   reset_shopt_options ();
   /* Zero out builtin_env, since this could be a shell script run from a
      sourced file with a temporary environment supplied to the `source/.'
      builtin.  Such variables are not supposed to be exported (empirical
      testing with sh and ksh).  Just throw it away; don't worry about a
      memory leak. */
   if (vc_isbltnenv (shell_variables))
     shell_variables = shell_variables->down;
   clear_unwind_protect_list (0);
   /* XXX -- are there other things we should be resetting here? */
   parse_and_execute_level = 0;      /* nothing left to restore it */
   /* We're no longer inside a shell function. */
   variable_context = return_catch_flag = funcnest = evalnest = sourcenest = 0;
   executing_list = 0;       /* XXX */
   /* If we're not interactive, close the file descriptor from which we're
      reading the current shell script. */
   if (interactive_shell == 0)
     unset_bash_input (0);
 }
References clear_unwind_protect_list(), var_context::down, evalnest, executing_list, funcnest, history_lines_this_session, init_job_stats(), interactive_shell, parse_and_execute_level, reset_shell_flags(), return_catch_flag, set_sigchld_handler(), shell_variables, sourcenest, unset_bash_input(), variable_context, vc_isbltnenv, and without_job_control().
Referenced by shell_execve().
is_dirname()
static int is_dirname (char * pathname) static
Definition at line 4339 of file execute_cmd.c.
 {
   char *temp;
   int ret;
   temp = search_for_command (pathname, 0);
   ret = temp ? file_isdir (temp) : file_isdir (pathname);
   free (temp);
   return ret;
 }
References file_isdir(), free, and search_for_command().
Referenced by execute_simple_command().
lastpipe_cleanup()
static void lastpipe_cleanup (int s) static
Definition at line 2489 of file execute_cmd.c.
 {
   set_jobs_list_frozen (s);
 }
References s, and set_jobs_list_frozen().
Referenced by execute_pipeline().
maybe_restore_getopt_state()
static void maybe_restore_getopt_state (sh_getopt_state_t * gs) static
Definition at line 4997 of file execute_cmd.c.
 {
   /* If we have a local copy of OPTIND and it's at the right (current)
      context, then we restore getopt's internal state.  If not, we just
      let it go.  We know there is a local OPTIND if gs->gs_flags & 1.
      This is set below in execute_function() before the context is run. */
   if (gs->gs_flags & 1)
     sh_getopt_restore_istate (gs);
   else
     free (gs);
 }
References free, sh_getopt_state::gs_flags, and sh_getopt_restore_istate().
Referenced by execute_function().
new_fd_bitmap()
struct fd_bitmap* new_fd_bitmap (int size)
Definition at line 322 of file execute_cmd.c.
 {
   struct fd_bitmap *ret;
   ret = (struct fd_bitmap *)xmalloc (sizeof (struct fd_bitmap));
   ret->size = size;
   if (size)
     {
       ret->bitmap = (char *)xmalloc (size);
       memset (ret->bitmap, '\0', size);
     }
   else
     ret->bitmap = (char *)NULL;
   return (ret);
 }
References fd_bitmap::bitmap, memset, NULL, size, fd_bitmap::size, and xmalloc.
Referenced by execute_command(), execute_pipeline(), execute_shell_function(), and parse_and_execute().
PARAMS() [1/22]
static int execute_case_command PARAMS ((CASE_COM *)) static
PARAMS() [2/22]
static void bind_lastarg PARAMS ((char *)) static
PARAMS() [3/22]
static char* getinterp PARAMS ((char *, int, int *)) static
PARAMS() [4/22]
static int execute_in_subshell PARAMS ((COMMAND *, int, int, int, struct fd_bitmap *)) static
PARAMS() [5/22]
static int shell_control_structure PARAMS ((enum command_type)) static
PARAMS() [6/22]
static int execute_for_command PARAMS ((FOR_COM *)) static
PARAMS() [7/22]
static int execute_if_command PARAMS ((IF_COM *)) static
PARAMS() [8/22]
int close PARAMS ((int))
PARAMS() [9/22]
static void close_pipes PARAMS ((int, int)) static
PARAMS() [10/22]
static void cleanup_redirects PARAMS ((REDIRECT *)) static
PARAMS() [11/22]
static int execute_null_command PARAMS ((REDIRECT *, int, int, int)) static
PARAMS() [12/22]
static int execute_builtin PARAMS ((sh_builtin_func_t *, WORD_LIST *, int, int)) static
PARAMS() [13/22]
static int execute_function PARAMS ((SHELL_VAR *, WORD_LIST *, int, struct fd_bitmap *, int, int)) static
PARAMS() [14/22]
static int execute_simple_command PARAMS ((SIMPLE_COM *, int, int, int, struct fd_bitmap *)) static
PARAMS() [15/22]
static void initialize_subshell PARAMS ((void)) static
PARAMS() [16/22]
static int execute_while_command PARAMS ((WHILE_COM *)) static
PARAMS() [17/22]
static int execute_while_or_until PARAMS ((WHILE_COM *, int)) static
PARAMS() [18/22]
static int execute_intern_function PARAMS ((WORD_DESC *, FUNCTION_DEF *)) static
PARAMS() [19/22]
static void fix_assignment_words PARAMS ((WORD_LIST *)) static
PARAMS() [20/22]
static int execute_disk_command PARAMS ((WORD_LIST *, REDIRECT *, char *, int, int, int, struct fd_bitmap *, int)) static
PARAMS() [21/22]
static void execute_subshell_builtin_or_function PARAMS ((WORD_LIST *, REDIRECT *, sh_builtin_func_t *, SHELL_VAR *, int, int, int, struct fd_bitmap *, int)) static
PARAMS() [22/22]
static int execute_builtin_or_function PARAMS ((WORD_LIST *, sh_builtin_func_t *, SHELL_VAR *, REDIRECT *, struct fd_bitmap *, int)) static
restore_stdin()
static void restore_stdin (int s) static
Definition at line 2475 of file execute_cmd.c.
 {
   if (s == -1)
     close (0);
   else
     {
       dup2 (s, 0);
       close (s);
     }
 }
References close(), dup2(), and s.
Referenced by execute_pipeline().
setup_async_signals()
void setup_async_signals ()
Definition at line 5539 of file execute_cmd.c.
 {
 #if defined (__BEOS__)
   set_signal_handler (SIGHUP, SIG_IGN); /* they want csh-like behavior */
 #endif
 #if defined (JOB_CONTROL)
   if (job_control == 0)
 #endif
     {
       /* Make sure we get the original signal dispositions now so we don't
      confuse the trap builtin later if the subshell tries to use it to
      reset SIGINT/SIGQUIT.  Don't call set_signal_ignored; that sets
      the value of original_signals to SIG_IGN. Posix interpretation 751. */
       get_original_signal (SIGINT);
       set_signal_handler (SIGINT, SIG_IGN);
       get_original_signal (SIGQUIT);
       set_signal_handler (SIGQUIT, SIG_IGN);
     }
 }
References get_original_signal(), job_control, set_signal_handler, SIG_IGN, SIGHUP, SIGINT, and SIGQUIT.
Referenced by execute_disk_command(), execute_in_subshell(), and execute_simple_command().
shell_control_structure()
static int shell_control_structure (enum command_type type) static
Definition at line 431 of file execute_cmd.c.
 {
   switch (type)
     {
 #if defined (ARITH_FOR_COMMAND)
     case cm_arith_for:
 #endif
 #if defined (SELECT_COMMAND)
     case cm_select:
 #endif
 #if defined (DPAREN_ARITHMETIC)
     case cm_arith:
 #endif
 #if defined (COND_COMMAND)
     case cm_cond:
 #endif
     case cm_case:
     case cm_while:
     case cm_until:
     case cm_if:
     case cm_for:
     case cm_group:
     case cm_function_def:
       return (1);
     default:
       return (0);
     }
 }
References cm_arith, cm_arith_for, cm_case, cm_cond, cm_for, cm_function_def, cm_group, cm_if, cm_select, cm_until, cm_while, and type.
Referenced by execute_command_internal(), and execute_in_subshell().
shell_execve()
int shell_execve (char * command, char ** args, char ** env)
Definition at line 5948 of file execute_cmd.c.
 {
   int larray, i, fd;
   char sample[HASH_BANG_BUFSIZ];
   int sample_len;
   SETOSTYPE (0);        /* Some systems use for USG/POSIX semantics */
   execve (command, args, env);
   i = errno;            /* error from execve() */
   CHECK_TERMSIG;
   SETOSTYPE (1);
   /* If we get to this point, then start checking out the file.
      Maybe it is something we can hack ourselves. */
   if (i != ENOEXEC)
     {
       /* make sure this is set correctly for file_error/report_error */
       last_command_exit_value = (i == ENOENT) ?  EX_NOTFOUND : EX_NOEXEC; /* XXX Posix.2 says that exit status is 126 */
       if (file_isdir (command))
 #if defined (EISDIR)
     internal_error (_("%s: %s"), command, strerror (EISDIR));
 #else
     internal_error (_("%s: is a directory"), command);
 #endif
       else if (executable_file (command) == 0)
     {
       errno = i;
       file_error (command);
     }
       /* errors not involving the path argument to execve. */
       else if (i == E2BIG || i == ENOMEM)
     {
       errno = i;
       file_error (command);
     }
       else if (i == ENOENT)
     {
       errno = i;
       internal_error (_("%s: cannot execute: required file not found"), command);
     }
       else
     {
       /* The file has the execute bits set, but the kernel refuses to
          run it for some reason.  See why. */
 #if defined (HAVE_HASH_BANG_EXEC)
       READ_SAMPLE_BUF (command, sample, sample_len);
       if (sample_len > 0)
         sample[sample_len - 1] = '\0';
       if (sample_len > 2 && sample[0] == '#' && sample[1] == '!')
         {
           char *interp;
           int ilen;
           interp = getinterp (sample, sample_len, (int *)NULL);
           ilen = strlen (interp);
           errno = i;
           if (interp[ilen - 1] == '\r')
         {
           interp = xrealloc (interp, ilen + 2);
           interp[ilen - 1] = '^';
           interp[ilen] = 'M';
           interp[ilen + 1] = '\0';
         }
           sys_error (_("%s: %s: bad interpreter"), command, interp ? interp : "");
           FREE (interp);
           return (EX_NOEXEC);
         }
 #endif
       errno = i;
       file_error (command);
     }
       return (last_command_exit_value);
     }
   /* This file is executable.
      If it begins with #!, then help out people with losing operating
      systems.  Otherwise, check to see if it is a binary file by seeing
      if the contents of the first line (or up to 80 characters) are in the
      ASCII set.  If it's a text file, execute the contents as shell commands,
      otherwise return 126 (EX_BINARY_FILE). */
   READ_SAMPLE_BUF (command, sample, sample_len);
   if (sample_len == 0)
     return (EXECUTION_SUCCESS);
   /* Is this supposed to be an executable script?
      If so, the format of the line is "#! interpreter [argument]".
      A single argument is allowed.  The BSD kernel restricts
      the length of the entire line to 32 characters (32 bytes
      being the size of the BSD exec header), but we allow up to 128
      characters. */
   if (sample_len > 0)
     {
 #if !defined (HAVE_HASH_BANG_EXEC)
       if (sample_len > 2 && sample[0] == '#' && sample[1] == '!')
     return (execute_shell_script (sample, sample_len, command, args, env));
       else
 #endif
       if (check_binary_file (sample, sample_len))
     {
       internal_error (_("%s: cannot execute binary file: %s"), command, strerror (i));
       errno = i;
       return (EX_BINARY_FILE);
     }
     }
   /* We have committed to attempting to execute the contents of this file
      as shell commands. */
   reset_parser ();
   initialize_subshell ();
   set_sigint_handler ();
   /* Insert the name of this shell into the argument list. */
   larray = strvec_len (args) + 1;
   args = strvec_resize (args, larray + 1);
   for (i = larray - 1; i; i--)
     args[i] = args[i - 1];
   args[0] = shell_name;
   args[1] = command;
   args[larray] = (char *)NULL;
   if (args[0][0] == '-')
     args[0]++;
 #if defined (RESTRICTED_SHELL)
   if (restricted)
     change_flag ('r', FLAG_OFF);
 #endif
   if (subshell_argv)
     {
       /* Can't free subshell_argv[0]; that is shell_name. */
       for (i = 1; i < subshell_argc; i++)
     free (subshell_argv[i]);
       free (subshell_argv);
     }
   dispose_command (currently_executing_command);    /* XXX */
   currently_executing_command = (COMMAND *)NULL;
   subshell_argc = larray;
   subshell_argv = args;
   subshell_envp = env;
   unbind_args ();   /* remove the positional parameters */
 #if defined (PROCESS_SUBSTITUTION) && defined (HAVE_DEV_FD)
   clear_fifo_list ();   /* pipe fds are what they are now */
 #endif
   sh_longjmp (subshell_top_level, 1);
   /*NOTREACHED*/
 }
References _, args, change_flag(), check_binary_file(), CHECK_TERMSIG, currently_executing_command, dispose_command(), E2BIG, EISDIR, ENOENT, ENOEXEC, ENOMEM, env, errno, EX_BINARY_FILE, EX_NOEXEC, EX_NOTFOUND, executable_file(), execute_shell_script(), EXECUTION_SUCCESS, execve(), fd, file_error(), file_isdir(), FLAG_OFF, FREE, free, getinterp(), HASH_BANG_BUFSIZ, i, initialize_subshell(), internal_error(), last_command_exit_value, NULL, READ_SAMPLE_BUF, reset_parser(), set_sigint_handler(), SETOSTYPE, sh_longjmp, shell_name, strerror(), strlen(), strvec_len(), strvec_resize(), subshell_argc, subshell_argv, subshell_envp, subshell_top_level, sys_error(), unbind_args(), and xrealloc.
Referenced by execute_disk_command(), and execute_shell_script().
undo_partial_redirects()
void undo_partial_redirects ()
Definition at line 473 of file execute_cmd.c.
 {
   if (redirection_undo_list)
     {
       cleanup_redirects (redirection_undo_list);
       redirection_undo_list = (REDIRECT *)NULL;
     }
 }
References cleanup_redirects(), NULL, and redirection_undo_list.
Referenced by execute_builtin_or_function(), execute_command_internal(), and exp_jump_to_top_level().
Variable Documentation
builtin_ignoring_errexit
int builtin_ignoring_errexit = 0
Definition at line 225 of file execute_cmd.c.
Referenced by change_flag(), command_substitute(), and execute_builtin().
command_string_index
int command_string_index extern
Definition at line 111 of file print_cmd.c.
Referenced by cprintf(), execute_case_command(), execute_for_command(), execute_simple_command(), make_command_string(), named_function_string(), print_command(), semicolon(), and the_printed_command_resize().
comsub_ignore_return
int comsub_ignore_return = 0
Definition at line 246 of file execute_cmd.c.
Referenced by execute_simple_command(), parse_and_execute(), parse_prologue(), termsig_handler(), throw_to_top_level(), and top_level_cleanup().
connection_count
int connection_count static
Definition at line 277 of file execute_cmd.c.
current_fds_to_close
struct fd_bitmap* current_fds_to_close = (struct fd_bitmap *)NULL
Definition at line 314 of file execute_cmd.c.
Referenced by execute_command(), and execute_simple_command().
currently_executing_command
COMMAND* currently_executing_command static
Definition at line 267 of file execute_cmd.c.
Referenced by execute_command_internal(), execute_function(), executing_line_number(), and shell_execve().
errno
int errno extern
Referenced by async_redirect_stdin(), and shell_execve().
evalnest
int evalnest = 0
Definition at line 304 of file execute_cmd.c.
Referenced by _run_trap_internal(), execute_builtin(), execute_subshell_builtin_or_function(), initialize_subshell(), and run_pending_traps().
evalnest_max
int evalnest_max = EVALNEST_MAX
Definition at line 305 of file execute_cmd.c.
Referenced by execute_builtin(), and run_pending_traps().
exec_redirection_undo_list
REDIRECT* exec_redirection_undo_list = (REDIRECT *)NULL
Definition at line 234 of file execute_cmd.c.
Referenced by add_exec_redirect(), dispose_exec_redirects(), do_redirections(), execute_builtin_or_function(), and execute_command_internal().
executing_builtin
int executing_builtin = 0
Definition at line 238 of file execute_cmd.c.
Referenced by execute_builtin(), execute_simple_command(), find_variable(), find_variable_for_assignment(), find_variable_last_nameref(), find_variable_nameref(), find_variable_no_invisible(), find_variable_noref(), heredoc_expand(), redirection_expand(), report_syntax_error(), waitchld(), and zread().
executing_command_builtin
int executing_command_builtin = 0
Definition at line 261 of file execute_cmd.c.
Referenced by do_assignment_statements(), execute_builtin(), execute_simple_command(), parse_and_execute(), and source_file().
executing_list
int executing_list = 0
Definition at line 241 of file execute_cmd.c.
Referenced by execute_command(), execute_command_internal(), execute_connection(), initialize_subshell(), parse_prologue(), termsig_handler(), throw_to_top_level(), top_level_cleanup(), and wait_for().
from_return_trap
volatile int from_return_trap = 0
Definition at line 310 of file execute_cmd.c.
Referenced by _run_trap_internal(), and execute_function().
funcnest
int funcnest = 0
Definition at line 301 of file execute_cmd.c.
Referenced by execute_function(), initialize_subshell(), termsig_handler(), throw_to_top_level(), and top_level_cleanup().
funcnest_max
int funcnest_max = 0
Definition at line 302 of file execute_cmd.c.
Referenced by execute_function(), and sv_funcnest().
function_line_number
int function_line_number static
Definition at line 270 of file execute_cmd.c.
Referenced by execute_function(), and execute_simple_command().
last_command_exit_signal
int last_command_exit_signal
Definition at line 221 of file execute_cmd.c.
Referenced by command_substitute(), run_sigchld_trap(), throw_to_top_level(), wait_for(), and wait_for_single_pid().
last_command_exit_value
volatile int last_command_exit_value
Definition at line 217 of file execute_cmd.c.
Referenced by _evalfile(), _run_trap_internal(), call_expand_word_internal(), command_substitute(), decode_prompt_string(), do_assignment_statements(), execute_command_internal(), execute_connection(), execute_disk_command(), execute_for_command(), execute_in_subshell(), execute_intern_function(), execute_null_command(), execute_pipeline(), execute_simple_command(), execute_subshell_builtin_or_function(), exp_jump_to_top_level(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), get_exitstat(), glob_expand_word_list(), initialize_shell_variables(), main(), make_child(), param_expand(), parameter_brace_expand_length(), parameter_brace_expand_rhs(), parse_and_execute(), parse_comsub(), parser_error(), push_builtin(), push_heredoc(), reader_loop(), report_error(), report_syntax_error(), restore_parser_state(), run_exit_trap(), run_pending_traps(), run_return_trap(), run_sigchld_trap(), save_parser_state(), set_exit_status(), set_job_status_and_cleanup(), shell_execve(), shell_expand_word_list(), shell_reinitialize(), sigint_sighandler(), subshell_exit(), throw_to_top_level(), wait_for(), wait_sigint_handler(), and yyparse().
lastpipe_opt
int lastpipe_opt = 0
Definition at line 312 of file execute_cmd.c.
Referenced by execute_pipeline().
line_number_for_err_trap
int line_number_for_err_trap
Definition at line 281 of file execute_cmd.c.
Referenced by execute_command_internal(), execute_connection(), execute_function(), and parse_prologue().
match_ignore_case
int match_ignore_case = 0
Definition at line 259 of file execute_cmd.c.
redirection_undo_list
REDIRECT* redirection_undo_list = (REDIRECT *)NULL
Definition at line 229 of file execute_cmd.c.
Referenced by add_undo_close_redirect(), add_undo_redirect(), dispose_partial_redirects(), do_redirections(), execute_builtin_or_function(), execute_command_internal(), execute_null_command(), and undo_partial_redirects().
return_catch
procenv_t return_catch
Definition at line 214 of file execute_cmd.c.
Referenced by _evalfile(), _run_trap_internal(), command_substitute(), evalstring(), execute_function(), execute_in_subshell(), execute_subshell_builtin_or_function(), run_debug_trap(), run_exit_trap(), and run_pending_traps().
return_catch_flag
int return_catch_flag
Definition at line 212 of file execute_cmd.c.
Referenced by _evalfile(), _run_trap_internal(), command_substitute(), evalstring(), execute_function(), execute_in_subshell(), execute_subshell_builtin_or_function(), initialize_subshell(), run_debug_trap(), run_exit_trap(), run_pending_traps(), termsig_handler(), throw_to_top_level(), and top_level_cleanup().
return_catch_value
int return_catch_value
Definition at line 213 of file execute_cmd.c.
Referenced by _evalfile(), _run_trap_internal(), command_substitute(), evalstring(), execute_function(), execute_in_subshell(), execute_subshell_builtin_or_function(), run_debug_trap(), run_exit_trap(), and run_pending_traps().
SB
struct stat SB
Definition at line 261 of file execute_cmd.c.
Referenced by handle_net_input(), mbrtowc(), mbsrtowcs(), mbtowc(), and safe_write_to_pty_decode_iac().
shell_start_time
time_t shell_start_time extern
Definition at line 183 of file shell.c.
showing_function_line
int showing_function_line static
Definition at line 275 of file execute_cmd.c.
Referenced by execute_function(), and executing_line_number().
sourcenest
int sourcenest = 0
Definition at line 307 of file execute_cmd.c.
Referenced by execute_builtin(), execute_subshell_builtin_or_function(), and initialize_subshell().
sourcenest_max
int sourcenest_max = SOURCENEST_MAX
Definition at line 308 of file execute_cmd.c.
Referenced by execute_builtin().
special_builtin_failed
int special_builtin_failed static
Definition at line 265 of file execute_cmd.c.
Referenced by execute_command_internal(), and execute_simple_command().
stdin_redir
int stdin_redir
Definition at line 200 of file execute_cmd.c.
Referenced by execute_command_internal(), execute_connection(), execute_in_subshell(), execute_simple_command(), and reader_loop().
subshell_environment
int subshell_environment
Definition at line 250 of file execute_cmd.c.
Referenced by assign_random(), command_substitute(), delete_job(), do_redirection_internal(), execute_connection(), execute_disk_command(), execute_function(), execute_in_subshell(), execute_null_command(), execute_simple_command(), execute_subshell_builtin_or_function(), exit_shell(), find_variable_internal(), get_random_number(), get_urandom32(), make_child(), notify_of_job_status(), optimize_connection_fork(), parse_and_execute(), reader_loop(), run_debug_trap(), sh_exit(), shell_reinitialize(), should_suppress_fork(), start_job(), stop_pipeline(), termsig_handler(), trap_handler(), wait_for(), and waitchld().
subshell_level
int subshell_level = 0
Definition at line 253 of file execute_cmd.c.
Referenced by assign_subshell(), command_substitute(), execute_in_subshell(), execute_simple_command(), and get_subshell().
the_printed_command
char* the_printed_command extern
Definition at line 109 of file print_cmd.c.
Referenced by cprintf(), execute_case_command(), execute_command_internal(), execute_for_command(), execute_simple_command(), make_command_string(), named_function_string(), semicolon(), and the_printed_command_resize().
the_printed_command_except_trap
char* the_printed_command_except_trap
Definition at line 209 of file execute_cmd.c.
Referenced by execute_case_command(), execute_command_internal(), execute_for_command(), execute_pipeline(), execute_simple_command(), execute_subshell_builtin_or_function(), get_bash_command(), parse_prologue(), and restore_lastcom().
this_command_name
char* this_command_name
Definition at line 204 of file execute_cmd.c.
Referenced by builtin_error_prolog(), builtin_help(), builtin_usage(), do_assignment_statements(), evalerror(), execute_builtin(), execute_case_command(), execute_for_command(), execute_simple_command(), main(), make_builtin_argv(), param_expand(), parameter_brace_casemod(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), parameter_brace_transform(), and start_job().
this_shell_function
SHELL_VAR* this_shell_function
Definition at line 256 of file execute_cmd.c.
Referenced by execute_function(), and get_funcname().