Fennix: Userspace/mlibc/options/linux/generic/sys-eventfd.cpp File Reference
sys-eventfd.cpp File Reference
#include <sys/eventfd.h>
#include <errno.h>
#include <bits/ensure.h>
#include <mlibc/linux-sysdeps.hpp>
Functions
int eventfd (unsigned int initval, int flags)
int eventfd_read (int fd, eventfd_t *value)
int eventfd_write (int fd, eventfd_t value)
Function Documentation
eventfd()
int eventfd (unsigned int initval, int flags)
Definition at line 7 of file sys-eventfd.cpp.
{
     int fd = 0;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_eventfd_create, -1);
     if (int e = mlibc::sys_eventfd_create(initval, flags, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_eventfd_create().
eventfd_read()
int eventfd_read (int fd, eventfd_t * value)
Definition at line 19 of file sys-eventfd.cpp.
{
     ssize_t bytes_read;
     if (int e = mlibc::sys_read(fd, value, 8, &bytes_read); e) {
         errno = e;
         return -1;
     }
     if (bytes_read != 8) {
         return -1;
     }
     return 0;
 }
References errno, fd, mlibc::sys_read(), and value.
eventfd_write()
int eventfd_write (int fd, eventfd_t value)
Definition at line 33 of file sys-eventfd.cpp.
{
     ssize_t bytes_written;
     if (int e = mlibc::sys_write(fd, &value, 8, &bytes_written); e) {
         errno = e;
         return -1;
     }
     if (bytes_written != 8) {
         return -1;
     }
     return 0;
 }
References errno, fd, mlibc::sys_write(), and value.