Fennix: Userspace/apps/base/busybox/networking/ifenslave.c File Reference
ifenslave.c File Reference
#include "libbb.h"
#include <linux/if.h>
#include <linux/if_bonding.h>
#include <linux/sockios.h>
#include "fix_u32.h"
#include <linux/ethtool.h>
Data Structures
struct dev_data
struct globals
Macros
#define BOND_ABI_VERSION 2
#define IFNAMSIZ 16
#define G (*ptr_to_globals)
#define abi_ver (G.abi_ver)
#define hwaddr_set (G.hwaddr_set)
#define master (G.master)
#define slave (G.slave)
#define INIT_G()
#define INT uint16_t
Enumerations
enum { skfd = 3 }
Functions
static int ioctl_on_skfd (unsigned request, struct ifreq *ifr)
static int set_ifrname_and_do_ioctl (unsigned request, struct ifreq *ifr, const char *ifname)
static int get_if_settings (char *ifname, struct dev_data *dd)
static int get_slave_flags (char *slave_ifname)
static int set_hwaddr (char *ifname, struct sockaddr *hwaddr)
static int set_mtu (char *ifname, int mtu)
static int set_if_flags (char *ifname, int flags)
static int set_if_up (char *ifname, int flags)
static int set_if_down (char *ifname, int flags)
static int clear_if_addr (char *ifname)
static int set_if_addr (char *master_ifname, char *slave_ifname)
static void change_active (char *master_ifname, char *slave_ifname)
static NOINLINE int enslave (char *master_ifname, char *slave_ifname)
static int release (char *master_ifname, char *slave_ifname)
static NOINLINE void get_drv_info (char *master_ifname)
int ifenslave_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
dev_data
struct dev_data
Definition at line 154 of file ifenslave.c.
Data Fields
struct ifreq mtu flags hwaddr
Macro Definition Documentation
abi_ver
#define abi_ver (G.abi_ver)
Definition at line 167 of file ifenslave.c.
BOND_ABI_VERSION
#define BOND_ABI_VERSION 2
Definition at line 147 of file ifenslave.c.
G
#define G (*ptr_to_globals)
Definition at line 166 of file ifenslave.c.
hwaddr_set
#define hwaddr_set (G.hwaddr_set)
Definition at line 168 of file ifenslave.c.
IFNAMSIZ
#define IFNAMSIZ 16
Definition at line 150 of file ifenslave.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 171 of file ifenslave.c.
INT
#define INT uint16_t
master
#define master (G.master)
Definition at line 169 of file ifenslave.c.
slave
#define slave (G.slave)
Definition at line 170 of file ifenslave.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
skfd
Definition at line 159 of file ifenslave.c.
 { skfd = 3 };      /* AF_INET socket for ioctl() calls. */
Function Documentation
change_active()
static void change_active (char * master_ifname, char * slave_ifname) static
Definition at line 294 of file ifenslave.c.
 {
     struct ifreq ifr;
     if (!(slave.flags.ifr_flags & IFF_SLAVE)) {
         bb_error_msg_and_die("%s is not a slave", slave_ifname);
     }
     strncpy_IFNAMSIZ(ifr.ifr_slave, slave_ifname);
     if (set_ifrname_and_do_ioctl(SIOCBONDCHANGEACTIVE, &ifr, master_ifname)
      && ioctl_on_skfd(BOND_CHANGE_ACTIVE_OLD, &ifr)
     ) {
         bb_perror_msg_and_die(
             "master %s, slave %s: can't "
             "change active",
             master_ifname, slave_ifname);
     }
 }
References bb_error_msg_and_die(), bb_perror_msg_and_die(), ifr, ioctl_on_skfd(), set_ifrname_and_do_ioctl(), slave, and strncpy_IFNAMSIZ().
clear_if_addr()
static int clear_if_addr (char * ifname) static
Definition at line 245 of file ifenslave.c.
 {
     struct ifreq ifr;
     ifr.ifr_addr.sa_family = AF_INET;
     memset(ifr.ifr_addr.sa_data, 0, sizeof(ifr.ifr_addr.sa_data));
     return set_ifrname_and_do_ioctl(SIOCSIFADDR, &ifr, ifname);
 }
References AF_INET, ifr, memset, set_ifrname_and_do_ioctl(), and SIOCSIFADDR.
Referenced by enslave().
enslave()
static NOINLINE int enslave (char * master_ifname, char * slave_ifname) static
Definition at line 313 of file ifenslave.c.
 {
     struct ifreq ifr;
     int res;
     if (slave.flags.ifr_flags & IFF_SLAVE) {
         bb_error_msg(
             "%s is already a slave",
             slave_ifname);
         return 1;
     }
     res = set_if_down(slave_ifname, slave.flags.ifr_flags);
     if (res)
         return res;
     if (abi_ver < 2) {
         /* Older bonding versions would panic if the slave has no IP
          * address, so get the IP setting from the master.
          */
         res = set_if_addr(master_ifname, slave_ifname);
         if (res) {
             bb_perror_msg("%s: can't set address", slave_ifname);
             return res;
         }
     } else {
         res = clear_if_addr(slave_ifname);
         if (res) {
             bb_perror_msg("%s: can't clear address", slave_ifname);
             return res;
         }
     }
     if (master.mtu.ifr_mtu != slave.mtu.ifr_mtu) {
         res = set_mtu(slave_ifname, master.mtu.ifr_mtu);
         if (res) {
             bb_perror_msg("%s: can't set MTU", slave_ifname);
             return res;
         }
     }
     if (hwaddr_set) {
         /* Master already has an hwaddr
          * so set it's hwaddr to the slave
          */
         if (abi_ver < 1) {
             /* The driver is using an old ABI, so
              * the application sets the slave's
              * hwaddr
              */
             if (set_hwaddr(slave_ifname, &(master.hwaddr.ifr_hwaddr))) {
                 bb_perror_msg("%s: can't set hw address",
                         slave_ifname);
                 goto undo_mtu;
             }
             /* For old ABI the application needs to bring the
              * slave back up
              */
             if (set_if_up(slave_ifname, slave.flags.ifr_flags))
                 goto undo_slave_mac;
         }
         /* The driver is using a new ABI,
          * so the driver takes care of setting
          * the slave's hwaddr and bringing
          * it up again
          */
     } else {
         /* No hwaddr for master yet, so
          * set the slave's hwaddr to it
          */
         if (abi_ver < 1) {
             /* For old ABI, the master needs to be
              * down before setting it's hwaddr
              */
             if (set_if_down(master_ifname, master.flags.ifr_flags))
                 goto undo_mtu;
         }
         if (set_hwaddr(master_ifname, &(slave.hwaddr.ifr_hwaddr))) {
             bb_error_msg("%s: can't set hw address",
                 master_ifname);
             goto undo_mtu;
         }
         if (abi_ver < 1) {
             /* For old ABI, bring the master
              * back up
              */
             if (set_if_up(master_ifname, master.flags.ifr_flags))
                 goto undo_master_mac;
         }
         hwaddr_set = 1;
     }
     /* Do the real thing */
     strncpy_IFNAMSIZ(ifr.ifr_slave, slave_ifname);
     if (set_ifrname_and_do_ioctl(SIOCBONDENSLAVE, &ifr, master_ifname)
      && ioctl_on_skfd(BOND_ENSLAVE_OLD, &ifr)
     ) {
         goto undo_master_mac;
     }
     return 0;
 /* rollback (best effort) */
  undo_master_mac:
     set_hwaddr(master_ifname, &(master.hwaddr.ifr_hwaddr));
     hwaddr_set = 0;
     goto undo_mtu;
  undo_slave_mac:
     set_hwaddr(slave_ifname, &(slave.hwaddr.ifr_hwaddr));
  undo_mtu:
     set_mtu(slave_ifname, slave.mtu.ifr_mtu);
     return 1;
 }
References abi_ver, bb_error_msg(), bb_perror_msg(), clear_if_addr(), hwaddr_set, ifr, ioctl_on_skfd(), master, set_hwaddr(), set_if_addr(), set_if_down(), set_if_up(), set_ifrname_and_do_ioctl(), set_mtu(), slave, and strncpy_IFNAMSIZ().
get_drv_info()
static NOINLINE void get_drv_info (char * master_ifname) static
Definition at line 461 of file ifenslave.c.
 {
     struct ifreq ifr;
     struct ethtool_drvinfo info;
     memset(&ifr, 0, sizeof(ifr));
     ifr.ifr_data = (caddr_t)&info;
     info.cmd = ETHTOOL_GDRVINFO;
     /* both fields are 32 bytes long (long enough) */
     strcpy(info.driver, "ifenslave");
     strcpy(info.fw_version, utoa(BOND_ABI_VERSION));
     if (set_ifrname_and_do_ioctl(SIOCETHTOOL, &ifr, master_ifname) < 0) {
         if (errno == EOPNOTSUPP)
             return;
         bb_perror_msg_and_die("%s: SIOCETHTOOL error", master_ifname);
     }
     abi_ver = bb_strtou(info.fw_version, NULL, 0);
     if (errno)
         bb_error_msg_and_die("%s: SIOCETHTOOL error", master_ifname);
 }
References abi_ver, bb_error_msg_and_die(), bb_perror_msg_and_die(), bb_strtou(), BOND_ABI_VERSION, EOPNOTSUPP, errno, ifr, info, memset, NULL, set_ifrname_and_do_ioctl(), strcpy, and utoa().
get_if_settings()
static int get_if_settings (char * ifname, struct dev_data * dd) static
Definition at line 189 of file ifenslave.c.
 {
     int res;
     res = set_ifrname_and_do_ioctl(SIOCGIFMTU, &dd->mtu, ifname);
     res |= set_ifrname_and_do_ioctl(SIOCGIFFLAGS, &dd->flags, ifname);
     res |= set_ifrname_and_do_ioctl(SIOCGIFHWADDR, &dd->hwaddr, ifname);
     return res;
 }
References dd, set_ifrname_and_do_ioctl(), SIOCGIFFLAGS, SIOCGIFHWADDR, and SIOCGIFMTU.
get_slave_flags()
static int get_slave_flags (char * slave_ifname) static
Definition at line 200 of file ifenslave.c.
 {
     return set_ifrname_and_do_ioctl(SIOCGIFFLAGS, &slave.flags, slave_ifname);
 }
References set_ifrname_and_do_ioctl(), SIOCGIFFLAGS, and slave.
ifenslave_main()
int ifenslave_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 484 of file ifenslave.c.
 {
     char *master_ifname, *slave_ifname;
     int rv;
     int res;
     unsigned opt;
     enum {
         OPT_c = (1 << 0),
         OPT_d = (1 << 1),
         OPT_f = (1 << 2),
     };
     INIT_G();
     opt = getopt32long(argv, "cdfa",
         "change-active\0"  No_argument "c"
         "detach\0"         No_argument "d"
         "force\0"          No_argument "f"
         /* "all-interfaces\0" No_argument "a" */
     );
     argv += optind;
     if (opt & (opt-1)) /* Only one option can be given */
         bb_show_usage();
     master_ifname = *argv++;
     /* No interface names - show all interfaces. */
     if (!master_ifname) {
         display_interfaces(NULL);
         return EXIT_SUCCESS;
     }
     /* Open a basic socket */
     xmove_fd(xsocket(AF_INET, SOCK_DGRAM, 0), skfd);
     /* Exchange abi version with bonding module */
     get_drv_info(master_ifname);
     slave_ifname = *argv++;
     if (!slave_ifname) {
         if (opt & (OPT_d|OPT_c)) {
             /* --change or --detach, and no slaves given -
              * show all interfaces. */
             display_interfaces(slave_ifname /* == NULL */);
             return 2; /* why 2? */
         }
         /* A single arg means show the
          * configuration for this interface
          */
         display_interfaces(master_ifname);
         return EXIT_SUCCESS;
     }
     if (get_if_settings(master_ifname, &master)) {
         /* Probably a good reason not to go on */
         bb_perror_msg_and_die("%s: can't get settings", master_ifname);
     }
     /* Check if master is indeed a master;
      * if not then fail any operation
      */
     if (!(master.flags.ifr_flags & IFF_MASTER))
         bb_error_msg_and_die("%s is not a master", master_ifname);
     /* Check if master is up; if not then fail any operation */
     if (!(master.flags.ifr_flags & IFF_UP))
         bb_error_msg_and_die("%s is not up", master_ifname);
 #ifdef WHY_BOTHER
     /* Neither -c[hange] nor -d[etach] -> it's "enslave" then;
      * and -f[orce] is not there too. Check that it's ethernet. */
     if (!(opt & (OPT_d|OPT_c|OPT_f))) {
         /* The family '1' is ARPHRD_ETHER for ethernet. */
         if (master.hwaddr.ifr_hwaddr.sa_family != 1) {
             bb_error_msg_and_die(
                 "%s is not ethernet-like (-f overrides)",
                 master_ifname);
         }
     }
 #endif
     /* Accepts only one slave */
     if (opt & OPT_c) {
         /* Change active slave */
         if (get_slave_flags(slave_ifname)) {
             bb_perror_msg_and_die(
                 "%s: can't get flags", slave_ifname);
         }
         change_active(master_ifname, slave_ifname);
         return EXIT_SUCCESS;
     }
     /* Accepts multiple slaves */
     res = 0;
     do {
         if (opt & OPT_d) {
             /* Detach a slave interface from the master */
             rv = get_slave_flags(slave_ifname);
             if (rv) {
                 /* Can't work with this slave, */
                 /* remember the error and skip it */
                 bb_perror_msg(
                     "skipping %s: can't get %s",
                     slave_ifname, "flags");
                 res = rv;
                 continue;
             }
             rv = release(master_ifname, slave_ifname);
             if (rv) {
                 bb_perror_msg("can't release %s from %s",
                     slave_ifname, master_ifname);
                 res = rv;
             }
         } else {
             /* Attach a slave interface to the master */
             rv = get_if_settings(slave_ifname, &slave);
             if (rv) {
                 /* Can't work with this slave, */
                 /* remember the error and skip it */
                 bb_perror_msg(
                     "skipping %s: can't get %s",
                     slave_ifname, "settings");
                 res = rv;
                 continue;
             }
             rv = enslave(master_ifname, slave_ifname);
             if (rv) {
                 bb_perror_msg("can't enslave %s to %s",
                     slave_ifname, master_ifname);
                 res = rv;
             }
         }
     } while ((slave_ifname = *argv++) != NULL);
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(skfd);
     }
     return res;
 }
ioctl_on_skfd()
static int ioctl_on_skfd (unsigned request, struct ifreq * ifr) static
Definition at line 178 of file ifenslave.c.
 {
     return ioctl(skfd, request, ifr);
 }
References ifr, ioctl(), and skfd.
Referenced by change_active(), enslave(), release(), and set_ifrname_and_do_ioctl().
release()
static int release (char * master_ifname, char * slave_ifname) static
Definition at line 432 of file ifenslave.c.
 {
     struct ifreq ifr;
     int res = 0;
     if (!(slave.flags.ifr_flags & IFF_SLAVE)) {
         bb_error_msg("%s is not a slave", slave_ifname);
         return 1;
     }
     strncpy_IFNAMSIZ(ifr.ifr_slave, slave_ifname);
     if (set_ifrname_and_do_ioctl(SIOCBONDRELEASE, &ifr, master_ifname) < 0
      && ioctl_on_skfd(BOND_RELEASE_OLD, &ifr) < 0
     ) {
         return 1;
     }
     if (abi_ver < 1) {
         /* The driver is using an old ABI, so we'll set the interface
          * down to avoid any conflicts due to same MAC/IP
          */
         res = set_if_down(slave_ifname, slave.flags.ifr_flags);
     }
     /* set to default mtu */
     set_mtu(slave_ifname, 1500);
     return res;
 }
References abi_ver, bb_error_msg(), ifr, ioctl_on_skfd(), set_if_down(), set_ifrname_and_do_ioctl(), set_mtu(), slave, and strncpy_IFNAMSIZ().
Referenced by _rl_free_undo_list(), rl_do_undo(), and rl_free_undo_list().
set_hwaddr()
static int set_hwaddr (char * ifname, struct sockaddr * hwaddr) static
Definition at line 205 of file ifenslave.c.
 {
     struct ifreq ifr;
     memcpy(&(ifr.ifr_hwaddr), hwaddr, sizeof(*hwaddr));
     return set_ifrname_and_do_ioctl(SIOCSIFHWADDR, &ifr, ifname);
 }
References ifr, memcpy, set_ifrname_and_do_ioctl(), and SIOCSIFHWADDR.
Referenced by enslave().
set_if_addr()
static int set_if_addr (char * master_ifname, char * slave_ifname) static
Definition at line 254 of file ifenslave.c.
 {
 #if (SIOCGIFADDR | SIOCSIFADDR \
   | SIOCGIFDSTADDR | SIOCSIFDSTADDR \
   | SIOCGIFBRDADDR | SIOCSIFBRDADDR \
   | SIOCGIFNETMASK | SIOCSIFNETMASK) <= 0xffff
 #define INT uint16_t
 #else
 #define INT int
 #endif
     static const struct {
         INT g_ioctl;
         INT s_ioctl;
     } ifra[] = {
         { SIOCGIFADDR,    SIOCSIFADDR    },
         { SIOCGIFDSTADDR, SIOCSIFDSTADDR },
         { SIOCGIFBRDADDR, SIOCSIFBRDADDR },
         { SIOCGIFNETMASK, SIOCSIFNETMASK },
     };
     struct ifreq ifr;
     int res;
     unsigned i;
     for (i = 0; i < ARRAY_SIZE(ifra); i++) {
         res = set_ifrname_and_do_ioctl(ifra[i].g_ioctl, &ifr, master_ifname);
         if (res < 0) {
             ifr.ifr_addr.sa_family = AF_INET;
             memset(ifr.ifr_addr.sa_data, 0,
                 sizeof(ifr.ifr_addr.sa_data));
         }
         res = set_ifrname_and_do_ioctl(ifra[i].s_ioctl, &ifr, slave_ifname);
         if (res < 0)
             return res;
     }
     return 0;
 }
References AF_INET, ARRAY_SIZE, i, ifr, memset, set_ifrname_and_do_ioctl(), SIOCGIFADDR, SIOCGIFBRDADDR, SIOCGIFDSTADDR, SIOCGIFNETMASK, SIOCSIFADDR, SIOCSIFBRDADDR, SIOCSIFDSTADDR, and SIOCSIFNETMASK.
Referenced by enslave().
set_if_down()
static int set_if_down (char * ifname, int flags) static
Definition at line 237 of file ifenslave.c.
 {
     int res = set_if_flags(ifname, flags & ~IFF_UP);
     if (res)
         bb_perror_msg("%s: can't down", ifname);
     return res;
 }
References bb_perror_msg(), flags, and set_if_flags().
Referenced by enslave(), and release().
set_if_flags()
static int set_if_flags (char * ifname, int flags) static
Definition at line 221 of file ifenslave.c.
 {
     struct ifreq ifr;
     ifr.ifr_flags = flags;
     return set_ifrname_and_do_ioctl(SIOCSIFFLAGS, &ifr, ifname);
 }
References flags, ifr, set_ifrname_and_do_ioctl(), and SIOCSIFFLAGS.
Referenced by set_if_down(), and set_if_up().
set_if_up()
static int set_if_up (char * ifname, int flags) static
Definition at line 229 of file ifenslave.c.
 {
     int res = set_if_flags(ifname, flags | IFF_UP);
     if (res)
         bb_perror_msg("%s: can't up", ifname);
     return res;
 }
References bb_perror_msg(), flags, and set_if_flags().
Referenced by enslave().
set_ifrname_and_do_ioctl()
static int set_ifrname_and_do_ioctl (unsigned request, struct ifreq * ifr, const char * ifname) static
Definition at line 183 of file ifenslave.c.
 {
     strncpy_IFNAMSIZ(ifr->ifr_name, ifname);
     return ioctl_on_skfd(request, ifr);
 }
References ifr, ioctl_on_skfd(), and strncpy_IFNAMSIZ().
Referenced by change_active(), clear_if_addr(), enslave(), get_drv_info(), get_if_settings(), get_slave_flags(), release(), set_hwaddr(), set_if_addr(), set_if_flags(), and set_mtu().
set_mtu()
static int set_mtu (char * ifname, int mtu) static
Definition at line 213 of file ifenslave.c.
 {
     struct ifreq ifr;
     ifr.ifr_mtu = mtu;
     return set_ifrname_and_do_ioctl(SIOCSIFMTU, &ifr, ifname);
 }
References ifr, set_ifrname_and_do_ioctl(), and SIOCSIFMTU.
Referenced by enslave(), and release().