Fennix Userspace: Userspace/libc/src/std/spawn.c File Reference
spawn.c File Reference
#include <spawn.h>
Functions
int posix_spawn (pid_t *pid, const char *path, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *attrp, char *const argv[], char *const envp[])
int posix_spawnp (pid_t *pid, const char *file, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *attrp, char *const argv[], char *const envp[])
Function Documentation
posix_spawn()
int posix_spawn (pid_t * pid, const char * path, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t * attrp, char *const argv[], char *const envp[])
Definition at line 3 of file spawn.c.
 {
 }
Referenced by popen(), posix_spawnp(), and system().
posix_spawnp()
int posix_spawnp (pid_t * pid, const char * file, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t * attrp, char *const argv[], char *const envp[])
Definition at line 11 of file spawn.c.
 {
 }