Fennix Userspace: Userspace/musl/include/locale.h File Reference
locale.h File Reference
#include <features.h>
Data Structures
struct lconv
Macros
#define NULL ((void*)0)
#define LC_CTYPE 0
#define LC_NUMERIC 1
#define LC_TIME 2
#define LC_COLLATE 3
#define LC_MONETARY 4
#define LC_MESSAGES 5
#define LC_ALL 6
Functions
char * setlocale (int, const char *)
struct lconv * localeconv (void)
Data Structure Documentation
lconv
struct lconv
Definition at line 26 of file locale.h.
Data Fields
char * currency_symbol
char * decimal_point
char frac_digits
char * grouping
char * int_curr_symbol
char int_frac_digits
char int_n_cs_precedes
char int_n_sep_by_space
char int_n_sign_posn
char int_p_cs_precedes
char int_p_sep_by_space
char int_p_sign_posn
char * mon_decimal_point
char * mon_grouping
char * mon_thousands_sep
char n_cs_precedes
char n_sep_by_space
char n_sign_posn
char * negative_sign
char p_cs_precedes
char p_sep_by_space
char p_sign_posn
char * positive_sign
char * thousands_sep
Macro Definition Documentation
LC_ALL
#define LC_ALL 6
Definition at line 24 of file locale.h.
LC_COLLATE
#define LC_COLLATE 3
Definition at line 21 of file locale.h.
LC_CTYPE
#define LC_CTYPE 0
Definition at line 18 of file locale.h.
LC_MESSAGES
#define LC_MESSAGES 5
Definition at line 23 of file locale.h.
LC_MONETARY
#define LC_MONETARY 4
Definition at line 22 of file locale.h.
LC_NUMERIC
#define LC_NUMERIC 1
Definition at line 19 of file locale.h.
LC_TIME
#define LC_TIME 2
Definition at line 20 of file locale.h.
NULL
#define NULL ((void*)0)
Definition at line 15 of file locale.h.
Function Documentation
localeconv()
struct lconv* localeconv (void)
Definition at line 31 of file localeconv.c.
 {
     return (void *)&posix_lconv;
 }
References posix_lconv.
setlocale()
char* setlocale (int cat, const char * name)
Definition at line 10 of file setlocale.c.
 {
     const struct __locale_map *lm;
     if ((unsigned)cat > LC_ALL) return 0;
     LOCK(__locale_lock);
     /* For LC_ALL, setlocale is required to return a string which
      * encodes the current setting for all categories. The format of
      * this string is unspecified, and only the following code, which
      * performs both the serialization and deserialization, depends
      * on the format, so it can easily be changed if needed. */
     if (cat == LC_ALL) {
         int i;
         if (name) {
             struct __locale_struct tmp_locale;
             char part[LOCALE_NAME_MAX+1] = "C.UTF-8";
             const char *p = name;
             for (i=0; i<LC_ALL; i++) {
                 const char *z = __strchrnul(p, ';');
                 if (z-p <= LOCALE_NAME_MAX) {
                     memcpy(part, p, z-p);
                     part[z-p] = 0;
                     if (*z) p = z+1;
                 }
                 lm = __get_locale(i, part);
                 if (lm == LOC_MAP_FAILED) {
                     UNLOCK(__locale_lock);
                     return 0;
                 }
                 tmp_locale.cat[i] = lm;
             }
             libc.global_locale = tmp_locale;
         }
         char *s = buf;
         const char *part;
         int same = 0;
         for (i=0; i<LC_ALL; i++) {
             const struct __locale_map *lm =
                 libc.global_locale.cat[i];
             if (lm == libc.global_locale.cat[0]) same++;
             part = lm ? lm->name : "C";
             size_t l = strlen(part);
             memcpy(s, part, l);
             s[l] = ';';
             s += l+1;
         }
         *--s = 0;
         UNLOCK(__locale_lock);
         return same==LC_ALL ? (char *)part : buf;
     }
     if (name) {
         lm = __get_locale(cat, name);
         if (lm == LOC_MAP_FAILED) {
             UNLOCK(__locale_lock);
             return 0;
         }
         libc.global_locale.cat[cat] = lm;
     } else {
         lm = libc.global_locale.cat[cat];
     }
     char *ret = lm ? (char *)lm->name : "C";
     UNLOCK(__locale_lock);
     return ret;
 }
References __get_locale(), __locale_lock, __strchrnul(), buf, __locale_struct::cat, i, l, LC_ALL, libc, LOC_MAP_FAILED, LOCALE_NAME_MAX, LOCK, memcpy(), __locale_map::name, p, s, strlen(), and UNLOCK.