Fennix: Userspace/musl/src/linux/clone.c File Reference
clone.c File Reference
#include <stdarg.h>
#include <unistd.h>
#include <sched.h>
#include "pthread_impl.h"
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
int clone (int(*func)(void *), void *stack, int flags, void *arg,...)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file clone.c.
Function Documentation
clone()
int clone (int(*)(void *) func, void * stack, int flags, void * arg, ...)
Definition at line 8 of file clone.c.
 {
     va_list ap;
     pid_t *ptid, *ctid;
     void  *tls;
     va_start(ap, arg);
     ptid = va_arg(ap, pid_t *);
     tls  = va_arg(ap, void *);
     ctid = va_arg(ap, pid_t *);
     va_end(ap);
     return __syscall_ret(__clone(func, stack, flags, arg, ptid, tls, ctid));
 }
References __clone(), __syscall_ret(), flags, mlibc::stack, va_arg, va_end(), and va_start().