Fennix: Userspace/musl/src/include/pthread.h File Reference
pthread.h File Reference
#include "../../include/pthread.h"
Functions
hidden int __pthread_once (pthread_once_t *, void(*)(void))
hidden void __pthread_testcancel (void)
hidden int __pthread_setcancelstate (int, int *)
hidden int __pthread_create (pthread_t *restrict, const pthread_attr_t *restrict, void *(*)(void *), void *restrict)
hidden _Noreturn void __pthread_exit (void *)
hidden int __pthread_join (pthread_t, void **)
hidden int __pthread_mutex_lock (pthread_mutex_t *)
hidden int __pthread_mutex_trylock (pthread_mutex_t *)
hidden int __pthread_mutex_trylock_owner (pthread_mutex_t *)
hidden int __pthread_mutex_timedlock (pthread_mutex_t *restrict, const struct timespec *restrict)
hidden int __pthread_mutex_unlock (pthread_mutex_t *)
hidden int __private_cond_signal (pthread_cond_t *, int)
hidden int __pthread_cond_timedwait (pthread_cond_t *restrict, pthread_mutex_t *restrict, const struct timespec *restrict)
hidden int __pthread_key_create (pthread_key_t *, void(*)(void *))
hidden int __pthread_key_delete (pthread_key_t)
hidden int __pthread_rwlock_rdlock (pthread_rwlock_t *)
hidden int __pthread_rwlock_tryrdlock (pthread_rwlock_t *)
hidden int __pthread_rwlock_timedrdlock (pthread_rwlock_t *__restrict, const struct timespec *__restrict)
hidden int __pthread_rwlock_wrlock (pthread_rwlock_t *)
hidden int __pthread_rwlock_trywrlock (pthread_rwlock_t *)
hidden int __pthread_rwlock_timedwrlock (pthread_rwlock_t *__restrict, const struct timespec *__restrict)
hidden int __pthread_rwlock_unlock (pthread_rwlock_t *)
Function Documentation
__private_cond_signal()
hidden int __private_cond_signal (pthread_cond_t * c, int n)
Definition at line 176 of file pthread_cond_timedwait.c.
 {
     struct waiter *p, *first=0;
     volatile int ref = 0;
     int cur;
     lock(&c->_c_lock);
     for (p=c->_c_tail; n && p; p=p->prev) {
         if (a_cas(&p->state, WAITING, SIGNALED) != WAITING) {
             ref++;
             p->notify = &ref;
         } else {
             n--;
             if (!first) first=p;
         }
     }
     /* Split the list, leaving any remainder on the cv. */
     if (p) {
         if (p->next) p->next->prev = 0;
         p->next = 0;
     } else {
         c->_c_head = 0;
     }
     c->_c_tail = p;
     unlock(&c->_c_lock);
     /* Wait for any waiters in the LEAVING state to remove
      * themselves from the list before returning or allowing
      * signaled threads to proceed. */
     while ((cur = ref)) __wait(&ref, 0, cur, 1);
     /* Allow first signaled waiter, if any, to proceed. */
     if (first) unlock(&first->barrier);
     return 0;
 }
References __wait(), a_cas, c, cur, first, lock(), n, p, SIGNALED, unlock(), and WAITING.
Referenced by cnd_broadcast(), cnd_signal(), pthread_cond_broadcast(), and pthread_cond_signal().
__pthread_cond_timedwait()
hidden int __pthread_cond_timedwait (pthread_cond_t * restrict, pthread_mutex_t * restrict, const struct timespec * restrict)
Referenced by cnd_timedwait().
__pthread_create()
hidden int __pthread_create (pthread_t * restrict, const pthread_attr_t * restrict, void * *)(void *, void * restrict)
Referenced by thrd_create().
__pthread_exit()
hidden _Noreturn void __pthread_exit (void * result)
Definition at line 54 of file pthread_create.c.
 {
     pthread_t self = __pthread_self();
     sigset_t set;
     self->canceldisable = 1;
     self->cancelasync = 0;
     self->result = result;
     while (self->cancelbuf) {
         void (*f)(void *) = self->cancelbuf->__f;
         void *x = self->cancelbuf->__x;
         self->cancelbuf = self->cancelbuf->__next;
         f(x);
     }
     __pthread_tsd_run_dtors();
     __block_app_sigs(&set);
     /* This atomic potentially competes with a concurrent pthread_detach
      * call; the loser is responsible for freeing thread resources. */
     int state = a_cas(&self->detach_state, DT_JOINABLE, DT_EXITING);
     if (state==DT_DETACHED && self->map_base) {
         /* Since __unmapself bypasses the normal munmap code path,
          * explicitly wait for vmlock holders first. This must be
          * done before any locks are taken, to avoid lock ordering
          * issues that could lead to deadlock. */
         __vm_wait();
     }
     /* Access to target the exiting thread with syscalls that use
      * its kernel tid is controlled by killlock. For detached threads,
      * any use past this point would have undefined behavior, but for
      * joinable threads it's a valid usage that must be handled.
      * Signals must be blocked since pthread_kill must be AS-safe. */
     LOCK(self->killlock);
     /* The thread list lock must be AS-safe, and thus depends on
      * application signals being blocked above. */
     __tl_lock();
     /* If this is the only thread in the list, don't proceed with
      * termination of the thread, but restore the previous lock and
      * signal state to prepare for exit to call atexit handlers. */
     if (self->next == self) {
         __tl_unlock();
         UNLOCK(self->killlock);
         self->detach_state = state;
         __restore_sigs(&set);
         exit(0);
     }
     /* At this point we are committed to thread termination. */
     /* After the kernel thread exits, its tid may be reused. Clear it
      * to prevent inadvertent use and inform functions that would use
      * it that it's no longer available. At this point the killlock
      * may be released, since functions that use it will consistently
      * see the thread as having exited. Release it now so that no
      * remaining locks (except thread list) are held if we end up
      * resetting need_locks below. */
     self->tid = 0;
     UNLOCK(self->killlock);
     /* Process robust list in userspace to handle non-pshared mutexes
      * and the detached thread case where the robust list head will
      * be invalid when the kernel would process it. */
     __vm_lock();
     volatile void *volatile *rp;
     while ((rp=self->robust_list.head) && rp != &self->robust_list.head) {
         pthread_mutex_t *m = (void *)((char *)rp
             - offsetof(pthread_mutex_t, _m_next));
         int waiters = m->_m_waiters;
         int priv = (m->_m_type & 128) ^ 128;
         self->robust_list.pending = rp;
         self->robust_list.head = *rp;
         int cont = a_swap(&m->_m_lock, 0x40000000);
         self->robust_list.pending = 0;
         if (cont < 0 || waiters)
             __wake(&m->_m_lock, 1, priv);
     }
     __vm_unlock();
     __do_orphaned_stdio_locks();
     __dl_thread_cleanup();
     /* Last, unlink thread from the list. This change will not be visible
      * until the lock is released, which only happens after SYS_exit
      * has been called, via the exit futex address pointing at the lock.
      * This needs to happen after any possible calls to LOCK() that might
      * skip locking if process appears single-threaded. */
     if (!--libc.threads_minus_1) libc.need_locks = -1;
     self->next->prev = self->prev;
     self->prev->next = self->next;
     self->prev = self->next = self;
     if (state==DT_DETACHED && self->map_base) {
         /* Detached threads must block even implementation-internal
          * signals, since they will not have a stack in their last
          * moments of existence. */
         __block_all_sigs(&set);
         /* Robust list will no longer be valid, and was already
          * processed above, so unregister it with the kernel. */
         if (self->robust_list.off)
             __syscall(SYS_set_robust_list, 0, 3*sizeof(long));
         /* The following call unmaps the thread's stack mapping
          * and then exits without touching the stack. */
         __unmapself(self->map_base, self->map_size);
     }
     /* Wake any joiner. */
     a_store(&self->detach_state, DT_EXITED);
     __wake(&self->detach_state, 1, 1);
     for (;;) __syscall(SYS_exit, 0);
 }
References __block_all_sigs(), __block_app_sigs(), __dl_thread_cleanup(), __do_orphaned_stdio_locks(), __pthread_self, __pthread_tsd_run_dtors(), __restore_sigs(), __syscall, __tl_lock(), __tl_unlock(), __unmapself, __vm_lock(), __vm_unlock(), __vm_wait(), __wake(), _m_next, a_cas, a_store, a_swap, DT_DETACHED, DT_EXITED, DT_EXITING, DT_JOINABLE, exit(), f, libc, LOCK, offsetof, state, UNLOCK, Module::void(), and x.
Referenced by start(), start_c11(), and thrd_exit().
__pthread_join()
hidden int __pthread_join (pthread_t t, void ** res)
Definition at line 28 of file pthread_join.c.
 {
     return __pthread_timedjoin_np(t, res, 0);
 }
References __pthread_timedjoin_np(), and t.
Referenced by __pthread_detach(), __pthread_tryjoin_np(), and thrd_join().
__pthread_key_create()
hidden int __pthread_key_create (pthread_key_t * k, void(*)(void *) dtor)
Definition at line 31 of file pthread_key_create.c.
 {
     pthread_t self = __pthread_self();
     /* This can only happen in the main thread before
      * pthread_create has been called. */
     if (!self->tsd) self->tsd = __pthread_tsd_main;
     /* Purely a sentinel value since null means slot is free. */
     if (!dtor) dtor = nodtor;
     __pthread_rwlock_wrlock(&key_lock);
     pthread_key_t j = next_key;
     do {
         if (!keys[j]) {
             keys[next_key = *k = j] = dtor;
             __pthread_rwlock_unlock(&key_lock);
             return 0;
         }
     } while ((j=(j+1)%PTHREAD_KEYS_MAX) != next_key);
     __pthread_rwlock_unlock(&key_lock);
     return EAGAIN;
 }
References __pthread_rwlock_unlock(), __pthread_rwlock_wrlock(), __pthread_self, __pthread_tsd_main, EAGAIN, j, k, key_lock, keys, next_key, and nodtor().
Referenced by tss_create().
__pthread_key_delete()
hidden int __pthread_key_delete (pthread_key_t k)
Definition at line 56 of file pthread_key_create.c.
 {
     sigset_t set;
     pthread_t self = __pthread_self(), td=self;
     __block_app_sigs(&set);
     __pthread_rwlock_wrlock(&key_lock);
     __tl_lock();
     do td->tsd[k] = 0;
     while ((td=td->next)!=self);
     __tl_unlock();
     keys[k] = 0;
     __pthread_rwlock_unlock(&key_lock);
     __restore_sigs(&set);
     return 0;
 }
References __block_app_sigs(), __pthread_rwlock_unlock(), __pthread_rwlock_wrlock(), __pthread_self, __restore_sigs(), __tl_lock(), __tl_unlock(), k, key_lock, keys, and td.
Referenced by tss_delete().
__pthread_mutex_lock()
hidden int __pthread_mutex_lock (pthread_mutex_t * m)
Definition at line 3 of file pthread_mutex_lock.c.
 {
     if ((m->_m_type&15) == PTHREAD_MUTEX_NORMAL
         && !a_cas(&m->_m_lock, 0, EBUSY))
         return 0;
     return __pthread_mutex_timedlock(m, 0);
 }
References __pthread_mutex_timedlock(), a_cas, EBUSY, and PTHREAD_MUTEX_NORMAL.
__pthread_mutex_timedlock()
hidden int __pthread_mutex_timedlock (pthread_mutex_t * restrict, const struct timespec * restrict)
Referenced by __pthread_mutex_lock(), and mtx_timedlock().
__pthread_mutex_trylock()
hidden int __pthread_mutex_trylock (pthread_mutex_t * m)
Definition at line 67 of file pthread_mutex_trylock.c.
 {
     if ((m->_m_type&15) == PTHREAD_MUTEX_NORMAL)
         return a_cas(&m->_m_lock, 0, EBUSY) & EBUSY;
     return __pthread_mutex_trylock_owner(m);
 }
References __pthread_mutex_trylock_owner(), a_cas, EBUSY, and PTHREAD_MUTEX_NORMAL.
Referenced by __pthread_mutex_timedlock(), mtx_trylock(), and pthread_mutex_timedlock_pi().
__pthread_mutex_trylock_owner()
hidden int __pthread_mutex_trylock_owner (pthread_mutex_t * m)
Definition at line 3 of file pthread_mutex_trylock.c.
 {
     int old, own;
     int type = m->_m_type;
     pthread_t self = __pthread_self();
     int tid = self->tid;
     old = m->_m_lock;
     own = old & 0x3fffffff;
     if (own == tid) {
         if ((type&8) && m->_m_count<0) {
             old &= 0x40000000;
             m->_m_count = 0;
             goto success;
         }
         if ((type&3) == PTHREAD_MUTEX_RECURSIVE) {
             if ((unsigned)m->_m_count >= INT_MAX) return EAGAIN;
             m->_m_count++;
             return 0;
         }
     }
     if (own == 0x3fffffff) return ENOTRECOVERABLE;
     if (own || (old && !(type & 4))) return EBUSY;
     if (type & 128) {
         if (!self->robust_list.off) {
             self->robust_list.off = (char*)&m->_m_lock-(char *)&m->_m_next;
             __syscall(SYS_set_robust_list, &self->robust_list, 3*sizeof(long));
         }
         if (m->_m_waiters) tid |= 0x80000000;
         self->robust_list.pending = &m->_m_next;
     }
     tid |= old & 0x40000000;
     if (a_cas(&m->_m_lock, old, tid) != old) {
         self->robust_list.pending = 0;
         if ((type&12)==12 && m->_m_waiters) return ENOTRECOVERABLE;
         return EBUSY;
     }
 success:
     if ((type&8) && m->_m_waiters) {
         int priv = (type & 128) ^ 128;
         __syscall(SYS_futex, &m->_m_lock, FUTEX_UNLOCK_PI|priv);
         self->robust_list.pending = 0;
         return (type&4) ? ENOTRECOVERABLE : EBUSY;
     }
     volatile void *next = self->robust_list.head;
     m->_m_next = next;
     m->_m_prev = &self->robust_list.head;
     if (next != &self->robust_list.head) *(volatile void *volatile *)
         ((char *)next - sizeof(void *)) = &m->_m_next;
     self->robust_list.head = &m->_m_next;
     self->robust_list.pending = 0;
     if (old) {
         m->_m_count = 0;
         return EOWNERDEAD;
     }
     return 0;
 }
References __pthread_self, __syscall, a_cas, EAGAIN, EBUSY, ENOTRECOVERABLE, EOWNERDEAD, FUTEX_UNLOCK_PI, INT_MAX, next, old, PTHREAD_MUTEX_RECURSIVE, SYS_futex, and type.
Referenced by __pthread_mutex_trylock().
__pthread_mutex_unlock()
hidden int __pthread_mutex_unlock (pthread_mutex_t * m)
Definition at line 3 of file pthread_mutex_unlock.c.
 {
     pthread_t self;
     int waiters = m->_m_waiters;
     int cont;
     int type = m->_m_type & 15;
     int priv = (m->_m_type & 128) ^ 128;
     int new = 0;
     int old;
     if (type != PTHREAD_MUTEX_NORMAL) {
         self = __pthread_self();
         old = m->_m_lock;
         int own = old & 0x3fffffff;
         if (own != self->tid)
             return EPERM;
         if ((type&3) == PTHREAD_MUTEX_RECURSIVE && m->_m_count)
             return m->_m_count--, 0;
         if ((type&4) && (old&0x40000000))
             new = 0x7fffffff;
         if (!priv) {
             self->robust_list.pending = &m->_m_next;
             __vm_lock();
         }
         volatile void *prev = m->_m_prev;
         volatile void *next = m->_m_next;
         *(volatile void *volatile *)prev = next;
         if (next != &self->robust_list.head) *(volatile void *volatile *)
             ((char *)next - sizeof(void *)) = prev;
     }
     if (type&8) {
         if (old<0 || a_cas(&m->_m_lock, old, new)!=old) {
             if (new) a_store(&m->_m_waiters, -1);
             __syscall(SYS_futex, &m->_m_lock, FUTEX_UNLOCK_PI|priv);
         }
         cont = 0;
         waiters = 0;
     } else {
         cont = a_swap(&m->_m_lock, new);
     }
     if (type != PTHREAD_MUTEX_NORMAL && !priv) {
         self->robust_list.pending = 0;
         __vm_unlock();
     }
     if (waiters || cont<0)
         __wake(&m->_m_lock, 1, priv);
     return 0;
 }
References __pthread_self, __syscall, __vm_lock(), __vm_unlock(), __wake(), a_cas, a_store, a_swap, EPERM, FUTEX_UNLOCK_PI, next, old, PTHREAD_MUTEX_NORMAL, PTHREAD_MUTEX_RECURSIVE, SYS_futex, and type.
Referenced by __pthread_cond_timedwait(), and mtx_unlock().
__pthread_once()
hidden int __pthread_once (pthread_once_t * control, void(*)(void) init)
Definition at line 39 of file pthread_once.c.
 {
     /* Return immediately if init finished before, but ensure that
      * effects of the init routine are visible to the caller. */
     if (*(volatile int *)control == 2) {
         a_barrier();
         return 0;
     }
     return __pthread_once_full(control, init);
 }
References __pthread_once_full(), a_barrier, control, and init.
Referenced by call_once().
__pthread_rwlock_rdlock()
hidden int __pthread_rwlock_rdlock (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_rdlock.c.
 {
     return __pthread_rwlock_timedrdlock(rw, 0);
 }
References __pthread_rwlock_timedrdlock().
Referenced by __pthread_key_atfork(), and __pthread_tsd_run_dtors().
__pthread_rwlock_timedrdlock()
hidden int __pthread_rwlock_timedrdlock (pthread_rwlock_t * __restrict, const struct timespec * __restrict)
Referenced by __pthread_rwlock_rdlock().
__pthread_rwlock_timedwrlock()
hidden int __pthread_rwlock_timedwrlock (pthread_rwlock_t * __restrict, const struct timespec * __restrict)
Referenced by __pthread_rwlock_wrlock().
__pthread_rwlock_tryrdlock()
hidden int __pthread_rwlock_tryrdlock (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_tryrdlock.c.
 {
     int val, cnt;
     do {
         val = rw->_rw_lock;
         cnt = val & 0x7fffffff;
         if (cnt == 0x7fffffff) return EBUSY;
         if (cnt == 0x7ffffffe) return EAGAIN;
     } while (a_cas(&rw->_rw_lock, val, val+1) != val);
     return 0;
 }
References a_cas, cnt, EAGAIN, EBUSY, and val.
Referenced by __pthread_rwlock_timedrdlock().
__pthread_rwlock_trywrlock()
hidden int __pthread_rwlock_trywrlock (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_trywrlock.c.
 {
     if (a_cas(&rw->_rw_lock, 0, 0x7fffffff)) return EBUSY;
     return 0;
 }
References a_cas, and EBUSY.
Referenced by __pthread_rwlock_timedwrlock().
__pthread_rwlock_unlock()
hidden int __pthread_rwlock_unlock (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_unlock.c.
 {
     int val, cnt, waiters, new, priv = rw->_rw_shared^128;
     do {
         val = rw->_rw_lock;
         cnt = val & 0x7fffffff;
         waiters = rw->_rw_waiters;
         new = (cnt == 0x7fffffff || cnt == 1) ? 0 : val-1;
     } while (a_cas(&rw->_rw_lock, val, new) != val);
     if (!new && (waiters || val<0))
         __wake(&rw->_rw_lock, cnt, priv);
     return 0;
 }
References __wake(), a_cas, cnt, and val.
Referenced by __pthread_key_atfork(), __pthread_key_create(), __pthread_key_delete(), and __pthread_tsd_run_dtors().
__pthread_rwlock_wrlock()
hidden int __pthread_rwlock_wrlock (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_wrlock.c.
 {
     return __pthread_rwlock_timedwrlock(rw, 0);
 }
References __pthread_rwlock_timedwrlock().
Referenced by __pthread_key_create(), and __pthread_key_delete().
__pthread_setcancelstate()
hidden int __pthread_setcancelstate (int new, int * old)
Definition at line 3 of file pthread_setcancelstate.c.
 {
     if (new > 2U) return EINVAL;
     struct pthread *self = __pthread_self();
     if (old) *old = self->canceldisable;
     self->canceldisable = new;
     return 0;
 }
References __pthread_self, EINVAL, and old.
Referenced by __pthread_cond_timedwait(), __pthread_detach(), __pthread_timedjoin_np(), and __timedwait().
__pthread_testcancel()
hidden void __pthread_testcancel (void)
Definition at line 9 of file pthread_testcancel.c.
 {
     __testcancel();
 }
References __testcancel().
Referenced by __pthread_cond_timedwait(), and __pthread_timedjoin_np().