Fennix Userspace: Userspace/apps/base/bash/lib/sh/spell.c File Reference
spell.c File Reference
#include <config.h>
#include <bashtypes.h>
#include <posixdir.h>
#include <posixstat.h>
#include <stdio.h>
#include <bashansi.h>
#include <maxpath.h>
#include <stdc.h>
Functions
static int mindist PARAMS ((char *, char *, char *))
static int spdist PARAMS ((char *, char *))
int spname (char *oldname, char *newname)
static int mindist (char *dir, char *guess, char *best)
static int spdist (char *cur, char *new)
char * dirspell (char *dirname)
Function Documentation
dirspell()
char* dirspell (char * dirname)
Definition at line 191 of file spell.c.
 {
   int n;
   char *guess;
   n = (strlen (dirname) * 3 + 1) / 2 + 1;
   guess = (char *)malloc (n);
   if (guess == 0)
     return 0;
   switch (spname (dirname, guess))
     {
     case -1:
     default:
       free (guess);
       return (char *)NULL;
     case 0:
     case 1:
       return guess;
     }
 }
References dirname, free, malloc, n, NULL, spname(), and strlen().
mindist()
static int mindist (char * dir, char * guess, char * best) static
Definition at line 107 of file spell.c.
 {
   DIR *fd;
   struct dirent *dp;
   int dist, x;
   dist = 3;    /* Worst distance */
   if (*dir == '\0')
     dir = ".";
   if ((fd = opendir(dir)) == NULL)
     return dist;
   while ((dp = readdir(fd)) != NULL)
     {
       /*
        *  Look for a better guess.  If the new guess is as
        *  good as the current one, we take it.  This way,
        *  any single character match will be a better match
        *  than ".".
        */
       x = spdist(dp->d_name, guess);
       if (x <= dist && x != 3)
     {
       strcpy(best, dp->d_name);
       dist = x;
       if (dist == 0)    /* Exact match */
         break;
     }
     }
   (void)closedir(fd);
   /* Don't return `.' */
   if (best[0] == '.' && best[1] == '\0')
     dist = 3;
   return dist;
 }
References closedir(), dirent::d_name, NULL, opendir(), readdir(), spdist(), strcpy(), and x.
Referenced by spname().
PARAMS() [1/2]
static int spdist PARAMS ((char *, char *)) static
PARAMS() [2/2]
static int mindist PARAMS ((char *, char *, char *)) static
spdist()
static int spdist (char * cur, char * new) static
Definition at line 158 of file spell.c.
 {
   while (*cur == *new)
     {
       if (*cur == '\0')
     return 0;    /* Exact match */
       cur++;
       new++;
     }
   if (*cur)
     {
       if (*new)
     {
       if (cur[1] && new[1] && cur[0] == new[1] && cur[1] == new[0] && strcmp (cur + 2, new + 2) == 0)
         return 1;  /* Transposition */
       if (strcmp (cur + 1, new + 1) == 0)
         return 2;  /* One character mismatch */
     }
       if (strcmp(&cur[1], &new[0]) == 0)
     return 2;    /* Extra character */
     }
   if (*new && strcmp(cur, new + 1) == 0)
     return 2;      /* Missing character */
   return 3;
 }
References strcmp.
Referenced by mindist().
spname()
int spname (char * oldname, char * newname)
Definition at line 62 of file spell.c.
 {
   char *op, *np, *p;
   char guess[PATH_MAX + 1], best[PATH_MAX + 1];
   op = oldname;
   np = newname;
   for (;;)
     {
       while (*op == '/')    /* Skip slashes */
     *np++ = *op++;
       *np = '\0';
       if (*op == '\0')    /* Exact or corrected */
     {
       /* `.' is rarely the right thing. */
       if (oldname[1] == '\0' && newname[1] == '\0' &&
         oldname[0] != '.' && newname[0] == '.')
         return -1;
       return strcmp(oldname, newname) != 0;
     }
       /* Copy next component into guess */
       for (p = guess; *op != '/' && *op != '\0'; op++)
     if (p < guess + PATH_MAX)
       *p++ = *op;
       *p = '\0';
       if (mindist(newname, guess, best) >= 3)
     return -1;  /* Hopeless */
       /*
        *  Add to end of newname
        */
       for (p = best; *np = *p++; np++)
     ;
     }
 }
References mindist(), p, PATH_MAX, and strcmp.
Referenced by dirspell().