Fennix Lynx Bootloader: Lynx/FennixLoader/Memory/Memory.cpp File Reference
Memory.cpp File Reference
#include <memory.hpp>
Functions
void InitializeMemoryManagement (BootInfo *Info, bool is32)
Variables
Memory32::Physical KernelAllocator32 {}
Memory32::PageTable * KernelPageTable32 = nullptr
Memory64::Physical KernelAllocator64 {}
Memory64::PageTable * KernelPageTable64 = nullptr
Function Documentation
InitializeMemoryManagement()
void InitializeMemoryManagement (BootInfo * Info, bool is32)
Definition at line 9 of file Memory.cpp.
 {
     if (is32)
     {
         trace("Initializing Physical Memory Manager");
         // KernelAllocator32 = Physical(); <- Already called in the constructor
         KernelAllocator32.Init(Info);
         info("Memory Info: %lldMB / %lldMB (%lldMB reserved)",
               TO_MB(KernelAllocator32.UsedMemory),
               TO_MB(KernelAllocator32.TotalMemory),
               TO_MB(KernelAllocator32.ReservedMemory));
         trace("Initializing Virtual Memory Manager");
         KernelPageTable32 = (Memory32::PageTable *)KernelAllocator32.RequestPages(TO_PAGES(PAGE_SIZE + 1));
         memset(KernelPageTable32, 0, PAGE_SIZE);
         {
             Memory32::Virtual va = Memory32::Virtual(KernelPageTable32);
             debug("Mapping from 0x0 to %#llx", Info->Memory.Size);
             size_t MemSize = Info->Memory.Size;
             va.Map((void *)0, (void *)0, MemSize, PTFlag::RW);
             debug("Mapping Framebuffer");
             int itrfb = 0;
             while (true)
             {
                 if (!Info->Framebuffer[itrfb].BaseAddress)
                     break;
                 va.Map((void *)Info->Framebuffer[itrfb].BaseAddress,
                        (void *)Info->Framebuffer[itrfb].BaseAddress,
                        Info->Framebuffer[itrfb].Pitch * Info->Framebuffer[itrfb].Height,
                        PTFlag::RW | PTFlag::US | PTFlag::G);
                 itrfb++;
             }
         }
         trace("Applying new page table from address %#lx", KernelPageTable32);
         asmv("mov %0, %%cr3" ::"r"(KernelPageTable32));
     }
 }
References asmv, BootInfo::FramebufferInfo::BaseAddress, debug, BootInfo::Framebuffer, G, BootInfo::FramebufferInfo::Height, info, Memory32::Physical::Init(), KernelAllocator32, KernelPageTable32, Memory32::Virtual::Map(), BootInfo::Memory, memset(), PAGE_SIZE, BootInfo::FramebufferInfo::Pitch, Memory32::Physical::RequestPages(), Memory32::Physical::ReservedMemory, RW, BootInfo::MemoryInfo::Size, TO_MB, TO_PAGES, Memory32::Physical::TotalMemory, trace, US, and Memory32::Physical::UsedMemory.
Referenced by efi_main(), and loader_main().
Variable Documentation
KernelAllocator32
Memory32::Physical KernelAllocator32 {}
Definition at line 3 of file Memory.cpp.
Referenced by __cxa_allocate_exception(), InitializeMemoryManagement(), LoadElfInMemory(), and Memory32::Virtual::Map().
KernelAllocator64
Memory64::Physical KernelAllocator64 {}
Definition at line 6 of file Memory.cpp.
Referenced by Memory64::Virtual::Map().
KernelPageTable32
Memory32::PageTable* KernelPageTable32 = nullptr
Definition at line 4 of file Memory.cpp.
Referenced by InitializeMemoryManagement().
KernelPageTable64
Memory64::PageTable* KernelPageTable64 = nullptr
Definition at line 7 of file Memory.cpp.