Fennix: Userspace/apps/base/busybox/coreutils/split.c File Reference
split.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define read_buffer bb_common_bufsiz1
#define SPLIT_OPT_l (1<<0)
#define SPLIT_OPT_b (1<<1)
#define SPLIT_OPT_a (1<<2)
Enumerations
enum { READ_BUFFER_SIZE = COMMON_BUFSIZE - 1 }
Functions
static char * next_file (char *old, unsigned suffix_len)
int split_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
read_buffer
#define read_buffer bb_common_bufsiz1
Definition at line 81 of file split.c.
SPLIT_OPT_a
#define SPLIT_OPT_a (1<<2)
Definition at line 86 of file split.c.
SPLIT_OPT_b
#define SPLIT_OPT_b (1<<1)
Definition at line 85 of file split.c.
SPLIT_OPT_l
#define SPLIT_OPT_l (1<<0)
Definition at line 84 of file split.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
READ_BUFFER_SIZE
Definition at line 82 of file split.c.
 { READ_BUFFER_SIZE = COMMON_BUFSIZE - 1 };
Function Documentation
next_file()
static char* next_file (char * old, unsigned suffix_len) static
Definition at line 59 of file split.c.
 {
     size_t end = strlen(old);
     unsigned i = 1;
     char *curr;
     while (1) {
         curr = old + end - i;
         if (*curr < 'z') {
             *curr += 1;
             break;
         }
         i++;
         if (i > suffix_len) {
             return NULL;
         }
         *curr = 'a';
     }
     return old;
 }
References end, i, NULL, old, and strlen().
Referenced by split_main().
split_main()
int split_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 89 of file split.c.
 {
     unsigned suffix_len = 2;
     char *pfx;
     char *count_p;
     const char *sfx;
     off_t cnt = 1000;
     off_t remaining = 0;
     unsigned opt;
     ssize_t bytes_read, to_write;
     char *src;
     setup_common_bufsiz();
     opt = getopt32(argv, "^"
             "l:b:a:+" /* -a N */
             "\0" "?2"/*max 2 args*/,
             &count_p, &count_p, &suffix_len
     );
     if (opt & SPLIT_OPT_l)
         cnt = XATOOFF(count_p);
     if (opt & SPLIT_OPT_b) // FIXME: also needs XATOOFF
         cnt = xatoull_sfx(count_p,
                 IF_FEATURE_SPLIT_FANCY(split_suffixes)
                 IF_NOT_FEATURE_SPLIT_FANCY(km_suffixes)
         );
     sfx = "x";
     argv += optind;
     if (argv[0]) {
         int fd;
         if (argv[1])
             sfx = argv[1];
         fd = xopen_stdin(argv[0]);
         xmove_fd(fd, STDIN_FILENO);
     } else {
         argv[0] = (char *) bb_msg_standard_input;
     }
     if (NAME_MAX < strlen(sfx) + suffix_len)
         bb_simple_error_msg_and_die("suffix too long");
     {
         char *char_p = xzalloc(suffix_len + 1);
         memset(char_p, 'a', suffix_len);
         pfx = xasprintf("%s%s", sfx, char_p);
         if (ENABLE_FEATURE_CLEAN_UP)
             free(char_p);
     }
     while (1) {
         bytes_read = safe_read(STDIN_FILENO, read_buffer, READ_BUFFER_SIZE);
         if (!bytes_read)
             break;
         if (bytes_read < 0)
             bb_simple_perror_msg_and_die(argv[0]);
         src = read_buffer;
         do {
             if (!remaining) {
                 if (!pfx)
                     bb_simple_error_msg_and_die("suffixes exhausted");
                 xmove_fd(xopen(pfx, O_WRONLY | O_CREAT | O_TRUNC), 1);
                 pfx = next_file(pfx, suffix_len);
                 remaining = cnt;
             }
             if (opt & SPLIT_OPT_b) {
                 /* split by bytes */
                 to_write = (bytes_read < remaining) ? bytes_read : remaining;
                 remaining -= to_write;
             } else {
                 /* split by lines */
                 /* can be sped up by using _memrchr_
                  * and writing many lines at once... */
                 char *end = memchr(src, '\n', bytes_read);
                 if (end) {
                     --remaining;
                     to_write = end - src + 1;
                 } else {
                     to_write = bytes_read;
                 }
             }
             xwrite(STDOUT_FILENO, src, to_write);
             bytes_read -= to_write;
             src += to_write;
         } while (bytes_read);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), bytes_read, cnt, end, EXIT_SUCCESS, fd, free, getopt32(), km_suffixes, memchr(), memset, NAME_MAX, next_file(), O_CREAT, O_TRUNC, O_WRONLY, off_t, opt, optind, read_buffer, READ_BUFFER_SIZE, safe_read(), SPLIT_OPT_b, SPLIT_OPT_l, src, STDIN_FILENO, STDOUT_FILENO, strlen(), xasprintf(), XATOOFF, xmove_fd(), xopen(), xopen_stdin(), xwrite(), and xzalloc().