Fennix: Userspace/libs/include/libinit/init.h File Reference
init.h File Reference
#include <stddef.h>
#include <stdarg.h>
Functions
int printf_libinit (const char *format,...)
int vprintf_libinit (const char *format, va_list arg)
int sprintf_libinit (char *s, const char *format,...)
int vsprintf_libinit (char *s, const char *format, va_list arg)
int snprintf_libinit (char *s, size_t count, const char *format,...)
int vsnprintf_libinit (char *s, size_t count, const char *format, va_list arg)
__attribute__ ((visibility("default"))) void init_log(const char *fmt
Function Documentation
__attribute__()
__attribute__ ((visibility("default"))) const
printf_libinit()
int printf_libinit (const char * format, ...)
Definition at line 1558 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vprintf_libinit(format, args);
     va_end(args);
     return ret;
 }
References args, format, ret, va_end(), va_start(), and vprintf_libinit().
snprintf_libinit()
int snprintf_libinit (char * s, size_t count, const char * format, ...)
An implementation of the C standard's snprintf/vsnprintf
Parameters
s An array in which to store the formatted string. It must be large enough to fit either the entire formatted output, or at least n characters. Alternatively, it can be NULL, in which case nothing will be printed, and only the number of characters which could have been printed is tallied and returned.
n The maximum number of characters to write to the array, including a terminating null character
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters that COULD have been written into s, not counting the terminating null character. A value equal or larger than n indicates truncation. Only when the returned value is non-negative and less than n, the null-terminated string has been fully and successfully printed.
Definition at line 1576 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsnprintf_libinit(s, n, format, args);
     va_end(args);
     return ret;
 }
References args, format, n, ret, va_end(), va_start(), and vsnprintf_libinit().
sprintf_libinit()
int sprintf_libinit (char * s, const char * format, ...)
An implementation of the C standard's sprintf/vsprintf
Note
For security considerations (the potential for exceeding the buffer bounds), please consider using the size-constrained variant, snprintf / vsnprintf , instead.
Parameters
s An array in which to store the formatted string. It must be large enough to fit the formatted output!
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 1567 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsprintf_libinit(s, format, args);
     va_end(args);
     return ret;
 }
References args, format, ret, va_end(), va_start(), and vsprintf_libinit().
vprintf_libinit()
int vprintf_libinit (const char * format, va_list arg)
Definition at line 1535 of file printf.c.
 {
     output_gadget_t gadget = extern_putchar_gadget_libint();
     return vsnprintf_impl_libint(&gadget, format, arg);
 }
References extern_putchar_gadget_libint(), format, and vsnprintf_impl_libint().
vsnprintf_libinit()
int vsnprintf_libinit (char * s, size_t count, const char * format, va_list arg)
Definition at line 1541 of file printf.c.
 {
     output_gadget_t gadget = buffer_gadget_libint(s, n);
     return vsnprintf_impl_libint(&gadget, format, arg);
 }
References buffer_gadget_libint(), format, n, and vsnprintf_impl_libint().
vsprintf_libinit()
int vsprintf_libinit (char * s, const char * format, va_list arg)
Definition at line 1547 of file printf.c.
 {
     return vsnprintf_libinit(s, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, format, arg);
 }
References format, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, and vsnprintf_libinit().