Fennix: Userspace/musl/include/nl_types.h File Reference
nl_types.h File Reference
Macros
#define NL_SETD 1
#define NL_CAT_LOCALE 1
Typedefs
typedef int nl_item
typedef void * nl_catd
Functions
nl_catd catopen (const char *, int)
char * catgets (nl_catd, int, int, const char *)
int catclose (nl_catd)
Macro Definition Documentation
NL_CAT_LOCALE
#define NL_CAT_LOCALE 1
Definition at line 9 of file nl_types.h.
NL_SETD
#define NL_SETD 1
Definition at line 8 of file nl_types.h.
Typedef Documentation
nl_catd
typedef void* nl_catd
Definition at line 12 of file nl_types.h.
nl_item
typedef int nl_item
Definition at line 11 of file nl_types.h.
Function Documentation
catclose()
int catclose (nl_catd catd)
Definition at line 9 of file catclose.c.
 {
     char *map = (char *)catd;
     munmap(map, V(map+8)+20);
     return 0;
 }
References map, munmap(), and V.
catgets()
char* catgets (nl_catd catd, int set_id, int msg_id, const char * s)
Definition at line 16 of file catgets.c.
 {
     const char *map = (const char *)catd;
     uint32_t nsets = V(map+4);
     const char *sets = map+20;
     const char *msgs = map+20+V(map+12);
     const char *strings = map+20+V(map+16);
     uint32_t set_id_be = htobe32(set_id);
     uint32_t msg_id_be = htobe32(msg_id);
     const char *set = bsearch(&set_id_be, sets, nsets, 12, cmp);
     if (!set) {
         errno = ENOMSG;
         return (char *)s;
     }
     uint32_t nmsgs = V(set+4);
     msgs += 12*V(set+8);
     const char *msg = bsearch(&msg_id_be, msgs, nmsgs, 12, cmp);
     if (!msg) {
         errno = ENOMSG;
         return (char *)s;
     }
     return (char *)(strings + V(msg+8));
 }
References bsearch(), cmp(), ENOMSG, errno, htobe32, map, msgs, s, strings, and V.
catopen()
nl_catd catopen (const char * name, int oflag)
Definition at line 28 of file catopen.c.
 {
     nl_catd catd;
     if (strchr(name, '/')) return do_catopen(name);
     char buf[PATH_MAX];
     size_t i;
     const char *path, *lang, *p, *z;
     if (libc.secure || !(path = getenv("NLSPATH"))) {
         errno = ENOENT;
         return (nl_catd)-1;
     }
     lang = oflag ? nl_langinfo(_NL_LOCALE_NAME(LC_MESSAGES)) : getenv("LANG");
     if (!lang) lang = "";
     for (p=path; *p; p=z) {
         i = 0;
         z = __strchrnul(p, ':');
         for (; p<z; p++) {
             const char *v;
             size_t l;
             if (*p!='%') v=p, l=1;
             else switch (*++p) {
             case 'N': v=name; l=strlen(v); break;
             case 'L': v=lang; l=strlen(v); break;
             case 'l': v=lang; l=strcspn(v,"_.@"); break;
             case 't':
                 v=__strchrnul(lang,'_');
                 if (*v) v++;
                 l=strcspn(v,".@");
                 break;
             case 'c': v="UTF-8"; l=5; break;
             case '%': v="%"; l=1; break;
             default: v=0;
             }
             if (!v || l >= sizeof buf - i) {
                 break;
             }
             memcpy(buf+i, v, l);
             i += l;
         }
         if (!*z && (p<z || !i)) break;
         if (p<z) continue;
         if (*z) z++;
         buf[i] = 0;
         /* Leading : or :: in NLSPATH is same as %N */
         catd = do_catopen(i ? buf : name);
         if (catd != (nl_catd)-1) return catd;
     }
     errno = ENOENT;
     return (nl_catd)-1;
 }
References __strchrnul(), _NL_LOCALE_NAME, buf, do_catopen(), ENOENT, errno, getenv, i, l, lang, LC_MESSAGES, libc, memcpy, nl_langinfo(), p, PATH_MAX, strchr(), strcspn(), and strlen().