Fennix: Userspace/mlibc/options/posix/include/sys/poll.h File Reference
poll.h File Reference
#include <bits/types.h>
#include <abi-bits/poll.h>
#include <abi-bits/signal.h>
Data Structures
struct pollfd
Typedefs
typedef __mlibc_size nfds_t
Functions
int poll (struct pollfd *, nfds_t, int)
int ppoll (struct pollfd *fds, nfds_t nfds, const struct timespec *timeout_ts, const sigset_t *sigmask)
Data Structure Documentation
pollfd
struct pollfd
Definition at line 14 of file poll.h.
Data Fields
short events
int fd
short revents
Typedef Documentation
nfds_t
typedef __mlibc_size nfds_t
Definition at line 8 of file poll.h.
Function Documentation
poll()
int poll (struct pollfd * fds, nfds_t count, int timeout)
Definition at line 9 of file poll.cpp.
{
     int num_events;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_poll, -1);
     if(int e = mlibc::sys_poll(fds, count, timeout, &num_events); e) {
         errno = e;
         return -1;
     }
     return num_events;
 }
References mlibc::count, errno, fds, MLIBC_CHECK_OR_ENOSYS, mlibc::num_events, mlibc::sys_poll(), and mlibc::timeout.
Referenced by ppoll().
ppoll()
int ppoll (struct pollfd * fds, nfds_t nfds, const struct timespec * timeout_ts, const sigset_t * sigmask)
Definition at line 19 of file poll.cpp.
{
     sigset_t origmask;
     int timeout = (timeout_ts == NULL) ? -1 : (timeout_ts->tv_sec * 1000 + timeout_ts->tv_nsec / 1000000);
     sigprocmask(SIG_SETMASK, sigmask, &origmask);
     int ready = poll(fds, nfds, timeout);
     sigprocmask(SIG_SETMASK, &origmask, NULL);
     return ready;
 }
References fds, NULL, poll(), SIG_SETMASK, mlibc::sigmask, sigprocmask(), mlibc::timeout, timespec::tv_nsec, and timespec::tv_sec.