Fennix: Userspace/apps/base/busybox/util-linux/eject.c File Reference
eject.c File Reference
#include <sys/mount.h>
#include "libbb.h"
Macros
#define dev_fd 3
#define eject_scsi(dev) ((void)0)
#define CDROMCLOSETRAY 0x5319 /* pendant of CDROMEJECT */
#define CDROMEJECT 0x5309 /* Ejects the cdrom media */
#define CDROM_DRIVE_STATUS 0x5326 /* Get tray position, etc. */
#define CDS_TRAY_OPEN 2
#define FLAG_CLOSE 1
#define FLAG_SMART 2
#define FLAG_SCSI 4
Functions
static void eject_cdrom (unsigned flags, const char *dev)
int eject_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CDROM_DRIVE_STATUS
#define CDROM_DRIVE_STATUS 0x5326 /* Get tray position, etc. */
Definition at line 99 of file eject.c.
CDROMCLOSETRAY
#define CDROMCLOSETRAY 0x5319 /* pendant of CDROMEJECT */
Definition at line 97 of file eject.c.
CDROMEJECT
#define CDROMEJECT 0x5309 /* Ejects the cdrom media */
Definition at line 98 of file eject.c.
CDS_TRAY_OPEN
#define CDS_TRAY_OPEN 2
Definition at line 101 of file eject.c.
dev_fd
#define dev_fd 3
Definition at line 52 of file eject.c.
eject_scsi
#define eject_scsi (dev) ((void)0)
Definition at line 93 of file eject.c.
FLAG_CLOSE
#define FLAG_CLOSE 1
Definition at line 103 of file eject.c.
FLAG_SCSI
#define FLAG_SCSI 4
Definition at line 105 of file eject.c.
FLAG_SMART
#define FLAG_SMART 2
Definition at line 104 of file eject.c.
Function Documentation
eject_cdrom()
static void eject_cdrom (unsigned flags, const char * dev) static
Definition at line 107 of file eject.c.
 {
     int cmd = CDROMEJECT;
     if (flags & FLAG_CLOSE
      || ((flags & FLAG_SMART) && ioctl(dev_fd, CDROM_DRIVE_STATUS) == CDS_TRAY_OPEN)
     ) {
         cmd = CDROMCLOSETRAY;
     }
     ioctl_or_perror_and_die(dev_fd, cmd, NULL, "%s", dev);
 }
References CDROM_DRIVE_STATUS, CDROMCLOSETRAY, CDROMEJECT, CDS_TRAY_OPEN, cmd, dev_fd, FLAG_CLOSE, FLAG_SMART, flags, ioctl(), ioctl_or_perror_and_die(), and NULL.
Referenced by eject_main().
eject_main()
int eject_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 121 of file eject.c.
 {
     unsigned flags;
     const char *device;
     flags = getopt32(argv, "^" "tT"IF_FEATURE_EJECT_SCSI("s")
             "\0" "?1:t--T:T--t"
     );
     device = argv[optind] ? argv[optind] : "/dev/cdrom";
     /* We used to do "umount <device>" here, but it was buggy
        if something was mounted OVER cdrom and
        if cdrom is mounted many times.
        This works equally well (or better):
        #!/bin/sh
        umount /dev/cdrom
        eject /dev/cdrom
     */
     xmove_fd(xopen_nonblocking(device), dev_fd);
     if (ENABLE_FEATURE_EJECT_SCSI && (flags & FLAG_SCSI))
         eject_scsi(device);
     else
         eject_cdrom(flags, device);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(dev_fd);
     return EXIT_SUCCESS;
 }
References argv, close(), dev_fd, device, eject_cdrom(), eject_scsi, EXIT_SUCCESS, FLAG_SCSI, flags, getopt32(), optind, xmove_fd(), and xopen_nonblocking().