Fennix: Userspace/musl/src/unistd/ttyname_r.c File Reference
ttyname_r.c File Reference
#include <unistd.h>
#include <errno.h>
#include <sys/stat.h>
#include "syscall.h"
Functions
int ttyname_r (int fd, char *name, size_t size)
Function Documentation
ttyname_r()
int ttyname_r (int fd, char * name, size_t size)
Definition at line 6 of file ttyname_r.c.
 {
     struct stat st1, st2;
     char procname[sizeof "/proc/self/fd/" + 3*sizeof(int) + 2];
     ssize_t l;
     if (!isatty(fd)) return errno;
     __procfdname(procname, fd);
     l = readlink(procname, name, size);
     if (l < 0) return errno;
     else if (l == size) return ERANGE;
     name[l] = 0;
     if (stat(name, &st1) || fstat(fd, &st2))
         return errno;
     if (st1.st_dev != st2.st_dev || st1.st_ino != st2.st_ino)
         return ENODEV;
     return 0;
 }
References __procfdname(), ENODEV, ERANGE, errno, fstat(), int, isatty(), name, readlink(), size, stat::st_dev, stat::st_ino, and stat().