Fennix Userspace: Userspace/libs/libinit/libinit.c File Reference
libinit.c File Reference
#include <libinit/init.h>
#include <unistd.h>
#include <features.h>
#include "printf.h"
Macros
#define cprintf printf
#define cvprintf vprintf
Functions
void init_log (const char *fmt,...)
Macro Definition Documentation
cprintf
#define cprintf printf
Definition at line 10 of file libinit.c.
cvprintf
#define cvprintf vprintf
Definition at line 11 of file libinit.c.
Function Documentation
init_log()
void init_log (const char * fmt, ...)
Definition at line 14 of file libinit.c.
 {
     static short log_lock = 0;
     while (log_lock)
         usleep(1);
     __sync_synchronize();
     log_lock = 1;
     cprintf("\eCCCCCC[\e0088FFinit\eCCCCCC] \eAAAAAA");
     va_list args;
     va_start(args, fmt);
     cvprintf(fmt, args);
     va_end(args);
     cprintf("\eCCCCCC");
     log_lock = 0;
     __sync_synchronize();
 }
References args, cprintf, cvprintf, fmt, usleep(), va_end(), and va_start().