Fennix Userspace: Userspace/apps/base/bash/examples/loadables/realpath.c File Reference
realpath.c File Reference
#include "config.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include "bashansi.h"
#include <maxpath.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Functions
char * sh_realpath ()
int realpath_builtin (WORD_LIST *list)
Variables
int errno
char * realpath_doc []
struct builtin realpath_struct
Function Documentation
realpath_builtin()
int realpath_builtin (WORD_LIST * list)
Definition at line 67 of file realpath.c.
 {
     int opt, cflag, vflag, qflag, sflag, aflag, es;
     char    *r, realbuf[PATH_MAX], *p, *newpath;
     struct stat sb;
 #if defined (ARRAY_VARS)
     arrayind_t  ind;
     char    *aname;
     SHELL_VAR   *v;
 #endif
     if (list == 0) {
         builtin_usage();
         return (EX_USAGE);
     }
     vflag = cflag = qflag = aflag = sflag = 0;
 #if defined (ARRAY_VARS)
     aname = NULL;
     v = NULL;
     ind = 0;
 #endif
     reset_internal_getopt();
     while ((opt = internal_getopt (list, "a:cqsv")) != -1) {
         switch (opt) {
 #if defined (ARRAY_VARS)
         case 'a':
             aflag = 1;
             aname = list_optarg;
             break;
 #endif
         case 'c':
             cflag = 1;
             break;
         case 'q':
             qflag = 1;
             break;
         case 's':
             sflag = 1;
             break;
         case 'v':
             vflag = 1;
             break;
         CASE_HELPOPT;
         default:
             builtin_usage();
             return (EX_USAGE);
         }
     }
     list = loptend;
     if (list == 0) {
         builtin_usage();
         return (EX_USAGE);
     }
 #if defined (ARRAY_VARS)
     if (aflag && legal_identifier (aname) == 0) {
         sh_invalidid(aname);
         return (EXECUTION_FAILURE);
     }
     if (aname && builtin_unbind_variable (aname) == -2)
         return (EXECUTION_FAILURE);
     if (aname) {
         v = find_or_make_array_variable (aname, 1);
         if (v == 0 || readonly_p (v) || noassign_p (v)) {
             if (v && readonly_p (v))
                 err_readonly (aname);
             return (EXECUTION_FAILURE);
         } else if (array_p (v) == 0) {
             builtin_error ("%s: not an indexed array", aname);
             return (EXECUTION_FAILURE);
         }
         if (invisible_p (v))
             VUNSETATTR (v, att_invisible);
         array_flush (array_cell (v));
     }
 #endif
     for (es = EXECUTION_SUCCESS; list; list = list->next) {
         p = list->word->word;
         if (sflag) {
             /* sh_canonpath doesn't convert to absolute pathnames */
             newpath = make_absolute(p, get_string_value("PWD"));
             r = sh_canonpath(newpath, PATH_CHECKDOTDOT|PATH_CHECKEXISTS);
             free(newpath);
         } else
             r = sh_realpath(p, realbuf);
         if (r == 0) {
             es = EXECUTION_FAILURE;
             if (qflag == 0)
                 builtin_error("%s: cannot resolve: %s", p, strerror(errno));
             continue;
         }
         if (cflag && (stat(r, &sb) < 0)) {
             es = EXECUTION_FAILURE;
             if (qflag == 0)
                 builtin_error("%s: %s", p, strerror(errno));
             continue;
         }
         if (aflag) {
             bind_array_element (v, ind, r, 0);
             ind++;
         }
         if (qflag == 0) {
             if (vflag)
                 printf ("%s -> ", p);
             printf("%s\n", r);
         }
         if (sflag)
             free (r);
     }
     return es;
 }
References aflag, array_cell, array_p, att_invisible, builtin_error(), builtin_unbind_variable(), builtin_usage(), CASE_HELPOPT, cflag, err_readonly(), errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, free, get_string_value(), internal_getopt(), invisible_p, legal_identifier(), list(), list_optarg, loptend, make_absolute(), node::next, noassign_p, NULL, opt, p, PATH_CHECKDOTDOT, PATH_CHECKEXISTS, PATH_MAX, printf(), readonly_p, reset_internal_getopt(), sflag, sh_canonpath(), sh_invalidid(), sh_realpath(), stat(), strerror(), vflag, and VUNSETATTR.
sh_realpath()
char* sh_realpath ()
Referenced by realpath_builtin().
Variable Documentation
errno
int errno extern
Referenced by realpath(), and realpath_builtin().
realpath_doc
char* realpath_doc[]
Initial value:
= {
    "Display pathname in canonical form.",
    "",
    "Display the canonicalized version of each PATHNAME argument, resolving",
    "symbolic links.",
    "The -a option stores each canonicalized PATHNAME argument into the indexed",
    "array VARNAME.",
    "The -c option checks whether or not each resolved name exists.",
    "The -q option produces no output; the exit status determines the",
    "validity of each PATHNAME, but any array assignment is still performed.",
    "If the -s option is supplied, canonicalize . and .. pathname components",
    "without resolving symbolic links.",
    "The -v option produces verbose output.",
    "The exit status is 0 if each PATHNAME was resolved; non-zero otherwise.",
    (char *)NULL
}
Definition at line 183 of file realpath.c.
realpath_struct
struct builtin realpath_struct
Initial value:
= {
    "realpath",
    realpath_builtin,
    BUILTIN_ENABLED,
    realpath_doc,
    "realpath [-a varname] [-cqsv] pathname [pathname...]",
    0
}
Definition at line 183 of file realpath.c.