Fennix: std::shared_ptr< T > Class Template Reference
std::shared_ptr< T > Class Template Reference
#include <smart_ptr.hpp>
Data Structures
class counter
Public Member Functions
shared_ptr (T *Pointer=nullptr)
shared_ptr (shared_ptr< T > &SPtr)
~shared_ptr ()
unsigned int get_count ()
T * get ()
T & operator* ()
T * operator-> ()
void reset (T *Pointer=nullptr)
void reset ()
void swap (shared_ptr< T > &Other)
Private Attributes
counter * m_ReferenceCounter
T * m_RealPointer
Detailed Description
template<typename T>
class std::shared_ptr< T >
Definition at line 84 of file smart_ptr.hpp.
Constructor & Destructor Documentation
shared_ptr() [1/2]
template<typename T > std::shared_ptr< T >::shared_ptr (T * Pointer = nullptr) inline explicit
Definition at line 138 of file smart_ptr.hpp.
         {
             m_RealPointer = Pointer;
             m_ReferenceCounter = new counter();
             spdbg("[%#lx] Shared pointer created (ptr=%#lx, ref=%#lx)", this, Pointer, m_ReferenceCounter);
             if (Pointer)
                 (*m_ReferenceCounter)++;
         }
References counter, std::shared_ptr< T >::m_RealPointer, std::shared_ptr< T >::m_ReferenceCounter, and spdbg.
shared_ptr() [2/2]
template<typename T > std::shared_ptr< T >::shared_ptr (shared_ptr< T > & SPtr) inline
Definition at line 147 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer copied (ptr=%#lx, ref=%#lx)", this, SPtr.m_RealPointer, SPtr.m_ReferenceCounter);
             m_RealPointer = SPtr.m_RealPointer;
             m_ReferenceCounter = SPtr.m_ReferenceCounter;
             (*m_ReferenceCounter)++;
         }
References std::shared_ptr< T >::m_RealPointer, std::shared_ptr< T >::m_ReferenceCounter, and spdbg.
~shared_ptr()
template<typename T > std::shared_ptr< T >::~shared_ptr () inline
Definition at line 155 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer destructor called", this);
             (*m_ReferenceCounter)--;
             if (m_ReferenceCounter->get() == 0)
             {
                 spdbg("[%#lx] Shared pointer deleted (ptr=%#lx, ref=%#lx)", this, m_RealPointer, m_ReferenceCounter);
                 delete m_ReferenceCounter, m_ReferenceCounter = nullptr;
                 delete m_RealPointer, m_RealPointer = nullptr;
             }
         }
References std::shared_ptr< T >::counter::get(), std::shared_ptr< T >::m_RealPointer, std::shared_ptr< T >::m_ReferenceCounter, and spdbg.
Member Function Documentation
get()
template<typename T > T* std::shared_ptr< T >::get () inline
Definition at line 173 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer get (%#lx)", this, m_RealPointer);
             return m_RealPointer;
         }
References std::shared_ptr< T >::m_RealPointer, and spdbg.
Referenced by VirtualFileSystem::Virtual::Create(), VirtualFileSystem::Virtual::Delete(), Execute::ELFLoad(), VirtualFileSystem::Virtual::GetPathFromNode(), VirtualFileSystem::Virtual::NormalizePath(), and VirtualFileSystem::Virtual::Open().
get_count()
template<typename T > unsigned int std::shared_ptr< T >::get_count () inline
Definition at line 167 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer count (%d)", this, m_ReferenceCounter->get());
             return m_ReferenceCounter->get();
         }
References std::shared_ptr< T >::counter::get(), std::shared_ptr< T >::m_ReferenceCounter, and spdbg.
operator*()
template<typename T > T& std::shared_ptr< T >::operator* () inline
Definition at line 179 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer dereference (ptr*=%#lx)", this, *m_RealPointer);
             return *m_RealPointer;
         }
References std::shared_ptr< T >::m_RealPointer, and spdbg.
operator->()
template<typename T > T* std::shared_ptr< T >::operator-> () inline
Definition at line 185 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer dereference (ptr->%#lx)", this, m_RealPointer);
             return m_RealPointer;
         }
References std::shared_ptr< T >::m_RealPointer, and spdbg.
reset() [1/2]
template<typename T > void std::shared_ptr< T >::reset () inline
Definition at line 208 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer reset (ptr=%#lx, ref=%#lx)", this, m_RealPointer, m_ReferenceCounter);
             if (m_ReferenceCounter->get() == 1)
             {
                 delete m_RealPointer, m_RealPointer = nullptr;
                 delete m_ReferenceCounter, m_ReferenceCounter = nullptr;
             }
             else
             {
                 (*m_ReferenceCounter)--;
             }
         }
References std::shared_ptr< T >::counter::get(), std::shared_ptr< T >::m_RealPointer, std::shared_ptr< T >::m_ReferenceCounter, and spdbg.
reset() [2/2]
template<typename T > void std::shared_ptr< T >::reset (T * Pointer = nullptr) inline
Definition at line 191 of file smart_ptr.hpp.
         {
             if (m_RealPointer == Pointer)
                 return;
             spdbg("[%#lx] Shared pointer reset (ptr=%#lx, ref=%#lx)", this, Pointer, m_ReferenceCounter);
             (*m_ReferenceCounter)--;
             if (m_ReferenceCounter->get() == 0)
             {
                 delete m_RealPointer;
                 delete m_ReferenceCounter;
             }
             m_RealPointer = Pointer;
             m_ReferenceCounter = new counter();
             if (Pointer)
                 (*m_ReferenceCounter)++;
         }
References counter, std::shared_ptr< T >::counter::get(), std::shared_ptr< T >::m_RealPointer, std::shared_ptr< T >::m_ReferenceCounter, and spdbg.
Referenced by VirtualFileSystem::Virtual::GetPathFromNode(), and VirtualFileSystem::Virtual::NormalizePath().
swap()
template<typename T > void std::shared_ptr< T >::swap (shared_ptr< T > & Other) inline
Definition at line 222 of file smart_ptr.hpp.
         {
             spdbg("[%#lx] Shared pointer swap (ptr=%#lx, ref=%#lx <=> ptr=%#lx, ref=%#lx)",
                   this, m_RealPointer, m_ReferenceCounter, Other.m_RealPointer, Other.m_ReferenceCounter);
             T *tempRealPointer = m_RealPointer;
             counter *tempReferenceCounter = m_ReferenceCounter;
             m_RealPointer = Other.m_RealPointer;
             m_ReferenceCounter = Other.m_ReferenceCounter;
             Other.m_RealPointer = tempRealPointer;
             Other.m_ReferenceCounter = tempReferenceCounter;
         }
References std::shared_ptr< T >::m_RealPointer, std::shared_ptr< T >::m_ReferenceCounter, spdbg, and T.
Field Documentation
m_RealPointer
template<typename T > T* std::shared_ptr< T >::m_RealPointer private
Definition at line 135 of file smart_ptr.hpp.
Referenced by std::shared_ptr< T >::get(), std::shared_ptr< T >::operator*(), std::shared_ptr< T >::operator->(), std::shared_ptr< T >::reset(), std::shared_ptr< T >::shared_ptr(), std::shared_ptr< T >::swap(), and std::shared_ptr< T >::~shared_ptr().
m_ReferenceCounter
template<typename T > counter* std::shared_ptr< T >::m_ReferenceCounter private
Definition at line 134 of file smart_ptr.hpp.
Referenced by std::shared_ptr< T >::get_count(), std::shared_ptr< T >::reset(), std::shared_ptr< T >::shared_ptr(), std::shared_ptr< T >::swap(), and std::shared_ptr< T >::~shared_ptr().
The documentation for this class was generated from the following file:
Kernel/include/std/smart_ptr.hpp