Fennix Userspace: StreamPrinter Struct Reference
StreamPrinter Struct Reference
Public Member Functions
StreamPrinter (FILE *stream)
void append (char c)
void append (const char *str)
void append (const char *str, size_t n)
Data Fields
FILE * stream
size_t count
Detailed Description
Definition at line 91 of file stdio-stubs.cpp.
Constructor & Destructor Documentation
StreamPrinter()
StreamPrinter::StreamPrinter (FILE * stream) inline
Definition at line 92 of file stdio-stubs.cpp.
     : stream(stream), count(0) { }
Member Function Documentation
append() [1/3]
void StreamPrinter::append (char c) inline
Definition at line 95 of file stdio-stubs.cpp.
{
         fwrite_unlocked(&c, 1, 1, stream);
         count++;
     }
References c, count, fwrite_unlocked(), and stream.
append() [2/3]
void StreamPrinter::append (const char * str) inline
Definition at line 100 of file stdio-stubs.cpp.
{
         fwrite_unlocked(str, strlen(str), 1, stream);
         count += strlen(str);
     }
References count, fwrite_unlocked(), stream, and strlen().
append() [3/3]
void StreamPrinter::append (const char * str, size_t n) inline
Definition at line 105 of file stdio-stubs.cpp.
{
         fwrite_unlocked(str, n, 1, stream);
         count += n;
     }
References count, fwrite_unlocked(), n, and stream.
Field Documentation
count
size_t StreamPrinter::count
Definition at line 111 of file stdio-stubs.cpp.
Referenced by append().
stream
FILE* StreamPrinter::stream
Definition at line 110 of file stdio-stubs.cpp.
Referenced by append().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/ansi/generic/stdio-stubs.cpp