Fennix Userspace: Userspace/musl/src/network/setsockopt.c File Reference
setsockopt.c File Reference
#include <sys/socket.h>
#include <sys/time.h>
#include <errno.h>
#include "syscall.h"
Macros
#define IS32BIT(x) !((x)+0x80000000ULL>>32)
#define CLAMP(x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Functions
int setsockopt (int fd, int level, int optname, const void *optval, socklen_t optlen)
Macro Definition Documentation
CLAMP
#define CLAMP (x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Definition at line 7 of file setsockopt.c.
IS32BIT
#define IS32BIT (x) !((x)+0x80000000ULL>>32)
Definition at line 6 of file setsockopt.c.
Function Documentation
setsockopt()
int setsockopt (int fd, int level, int optname, const void * optval, socklen_t optlen)
Definition at line 9 of file setsockopt.c.
 {
     const struct timeval *tv;
     time_t s;
     suseconds_t us;
     int r = __socketcall(setsockopt, fd, level, optname, optval, optlen, 0);
     if (r==-ENOPROTOOPT) switch (level) {
     case SOL_SOCKET:
         switch (optname) {
         case SO_RCVTIMEO:
         case SO_SNDTIMEO:
             if (SO_RCVTIMEO == SO_RCVTIMEO_OLD) break;
             if (optlen < sizeof *tv) return __syscall_ret(-EINVAL);
             tv = optval;
             s = tv->tv_sec;
             us = tv->tv_usec;
             if (!IS32BIT(s)) return __syscall_ret(-ENOTSUP);
             if (optname==SO_RCVTIMEO) optname=SO_RCVTIMEO_OLD;
             if (optname==SO_SNDTIMEO) optname=SO_SNDTIMEO_OLD;
             r = __socketcall(setsockopt, fd, level, optname,
                 ((long[]){s, CLAMP(us)}), 2*sizeof(long), 0);
             break;
         case SO_TIMESTAMP:
         case SO_TIMESTAMPNS:
             if (SO_TIMESTAMP == SO_TIMESTAMP_OLD) break;
             if (optname==SO_TIMESTAMP) optname=SO_TIMESTAMP_OLD;
             if (optname==SO_TIMESTAMPNS) optname=SO_TIMESTAMPNS_OLD;
             r = __socketcall(setsockopt, fd, level,
                 optname, optval, optlen, 0);
             break;
         }
     }
     return __syscall_ret(r);
 }
References __socketcall, __syscall_ret(), CLAMP, EINVAL, ENOPROTOOPT, ENOTSUP, fd, IS32BIT, s, setsockopt(), SO_RCVTIMEO, SO_RCVTIMEO_OLD, SO_SNDTIMEO, SO_SNDTIMEO_OLD, SO_TIMESTAMP, SO_TIMESTAMP_OLD, SO_TIMESTAMPNS, SO_TIMESTAMPNS_OLD, SOL_SOCKET, timeval::tv_sec, and timeval::tv_usec.
Referenced by __res_msend_rc(), accept_builtin(), d6_raw_socket(), setsockopt(), setsockopt_int(), start_tcp(), traceroute_init(), and udhcp_raw_socket().