Fennix: Userspace/mlibc/options/posix/include/sys/socket.h File Reference
socket.h File Reference
#include <abi-bits/gid_t.h>
#include <abi-bits/pid_t.h>
#include <bits/size_t.h>
#include <abi-bits/socklen_t.h>
#include <bits/ssize_t.h>
#include <abi-bits/uid_t.h>
#include <bits/posix/iovec.h>
#include <abi-bits/socket.h>
#include <bits/ansi/time_t.h>
#include <bits/ansi/timespec.h>
#include <stddef.h>
Data Structures
struct sockaddr
struct linger
struct ucred
Macros
#define CMSG_ALIGN(s)
#define CMSG_LEN(s) (CMSG_ALIGN(sizeof(struct cmsghdr)) + (s))
#define CMSG_SPACE(s) (CMSG_ALIGN(sizeof(struct cmsghdr)) + CMSG_ALIGN(s))
#define CMSG_DATA(c) ((char *)(c) + CMSG_ALIGN(sizeof(struct cmsghdr)))
#define __MLIBC_CMSG_NEXT(c) ((char *)(c) + CMSG_ALIGN((c)->cmsg_len))
#define __MLIBC_MHDR_LIMIT(m) ((char *)(m)->msg_control + (m)->msg_controllen)
#define CMSG_FIRSTHDR(m)
#define CMSG_NXTHDR(m, c)
Functions
int accept (int, struct sockaddr *__restrict, socklen_t *__restrict)
int accept4 (int, struct sockaddr *__restrict, socklen_t *__restrict, int)
int bind (int, const struct sockaddr *, socklen_t)
int connect (int, const struct sockaddr *, socklen_t)
int getpeername (int, struct sockaddr *__restrict, socklen_t *__restrict)
int getsockname (int, struct sockaddr *__restrict, socklen_t *__restrict)
int getsockopt (int, int, int, void *__restrict, socklen_t *__restrict)
int listen (int, int)
ssize_t recv (int, void *, size_t, int)
ssize_t recvfrom (int, void *__restrict, size_t, int, struct sockaddr *__restrict, socklen_t *__restrict)
ssize_t recvmsg (int, struct msghdr *, int)
ssize_t send (int, const void *, size_t, int)
ssize_t sendmsg (int, const struct msghdr *, int)
ssize_t sendto (int, const void *, size_t, int, const struct sockaddr *, socklen_t)
int recvmmsg (int sockfd, struct mmsghdr *msgvec, unsigned int vlen, int flags, struct timespec *timeout)
int sendmmsg (int sockfd, struct mmsghdr *msgvec, unsigned int vlen, int flags)
int setsockopt (int, int, int, const void *, socklen_t)
int shutdown (int, int)
int sockatmark (int)
int socket (int, int, int)
int socketpair (int, int, int, int[2])
Data Structure Documentation
sockaddr
struct sockaddr
Definition at line 22 of file socket.h.
Data Fields
char sa_data[14]
sa_family_t sa_family
linger
struct linger
Definition at line 63 of file socket.h.
Data Fields
int l_linger
int l_onoff
ucred
struct ucred
Definition at line 68 of file socket.h.
Data Fields
gid_t gid
pid_t pid
uid_t uid
Macro Definition Documentation
__MLIBC_CMSG_NEXT
#define __MLIBC_CMSG_NEXT (c) ((char *)(c) + CMSG_ALIGN((c)->cmsg_len))
Definition at line 47 of file socket.h.
__MLIBC_MHDR_LIMIT
#define __MLIBC_MHDR_LIMIT (m) ((char *)(m)->msg_control + (m)->msg_controllen)
Definition at line 48 of file socket.h.
CMSG_ALIGN
#define CMSG_ALIGN (s)
Value:
        (((s) + __alignof__(size_t) - 1) & \
        ~(__alignof__(size_t) - 1))
Definition at line 37 of file socket.h.
CMSG_DATA
#define CMSG_DATA (c) ((char *)(c) + CMSG_ALIGN(sizeof(struct cmsghdr)))
Definition at line 45 of file socket.h.
CMSG_FIRSTHDR
#define CMSG_FIRSTHDR (m)
Value:
    ((size_t)(m)->msg_controllen <= sizeof(struct cmsghdr) \
    ? (struct cmsghdr *)0 : (struct cmsghdr *) (m)->msg_control)
Definition at line 52 of file socket.h.
CMSG_LEN
#define CMSG_LEN (s) (CMSG_ALIGN(sizeof(struct cmsghdr)) + (s))
Definition at line 41 of file socket.h.
CMSG_NXTHDR
#define CMSG_NXTHDR (m, c)
Value:
    ((c)->cmsg_len < sizeof(struct cmsghdr) || \
        (ptrdiff_t)(sizeof(struct cmsghdr) + CMSG_ALIGN((c)->cmsg_len)) \
            >= __MLIBC_MHDR_LIMIT(m) - (char *)(c) \
    ? (struct cmsghdr *)0 : (struct cmsghdr *)__MLIBC_CMSG_NEXT(c))
Definition at line 57 of file socket.h.
CMSG_SPACE
#define CMSG_SPACE (s) (CMSG_ALIGN(sizeof(struct cmsghdr)) + CMSG_ALIGN(s))
Definition at line 42 of file socket.h.
Function Documentation
accept()
int accept (int , struct sockaddr * __restrict, socklen_t * __restrict)
accept4()
int accept4 (int , struct sockaddr * __restrict, socklen_t * __restrict, int)
bind()
int bind (int fd, const struct sockaddr * addr_ptr, socklen_t addr_len)
Definition at line 40 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_bind, -1);
     if(int e = mlibc::sys_bind(fd, addr_ptr, addr_len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_bind().
Referenced by ELF32_ST_INFO(), ELF64_ST_INFO(), resolveInObject(), socket_setup(), and ObjectSymbol::virtualAddress().
connect()
int connect (int fd, const struct sockaddr * addr_ptr, socklen_t addr_len)
Definition at line 49 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_connect, -1);
     if(int e = mlibc::sys_connect(fd, addr_ptr, addr_len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_connect().
Referenced by __openlog(), _vsyslog(), and run_test().
getpeername()
int getpeername (int , struct sockaddr * __restrict, socklen_t * __restrict)
getsockname()
int getsockname (int , struct sockaddr * __restrict, socklen_t * __restrict)
getsockopt()
int getsockopt (int , int , int , void * __restrict, socklen_t * __restrict)
listen()
int listen (int fd, int backlog)
Definition at line 86 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_listen, -1);
     if(int e = mlibc::sys_listen(fd, backlog); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_listen().
Referenced by socket_setup().
recv()
ssize_t recv (int , void * , size_t , int)
recvfrom()
ssize_t recvfrom (int , void * __restrict, size_t , int , struct sockaddr * __restrict, socklen_t * __restrict)
recvmmsg()
int recvmmsg (int sockfd, struct mmsghdr * msgvec, unsigned int vlen, int flags, struct timespec * timeout)
Definition at line 132 of file sys-socket-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
recvmsg()
ssize_t recvmsg (int fd, struct msghdr * hdr, int flags)
Definition at line 122 of file sys-socket-stubs.cpp.
{
     ssize_t length;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msg_recv, -1);
     if(int e = mlibc::sys_msg_recv(fd, hdr, flags, &length); e) {
         errno = e;
         return -1;
     }
     return length;
 }
References errno, fd, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_msg_recv().
Referenced by recvfrom().
send()
ssize_t send (int fd, const void * buffer, size_t size, int flags)
Definition at line 137 of file sys-socket-stubs.cpp.
{
     return sendto(fd, buffer, size, flags, nullptr, 0);
 }
References fd, mlibc::flags, sendto(), and size.
Referenced by _vsyslog().
sendmmsg()
int sendmmsg (int sockfd, struct mmsghdr * msgvec, unsigned int vlen, int flags)
Definition at line 169 of file sys-socket-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sendmsg()
ssize_t sendmsg (int fd, const struct msghdr * hdr, int flags)
Definition at line 156 of file sys-socket-stubs.cpp.
{
     if(hdr->msg_iovlen > IOV_MAX)
         return EMSGSIZE;
     ssize_t length;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msg_send, -1);
     if(int e = mlibc::sys_msg_send(fd, hdr, flags, &length); e) {
         errno = e;
         return -1;
     }
     return length;
 }
References EMSGSIZE, errno, fd, mlibc::flags, IOV_MAX, MLIBC_CHECK_OR_ENOSYS, msghdr::msg_iovlen, and mlibc::sys_msg_send().
Referenced by sendto().
sendto()
ssize_t sendto (int fd, const void * buffer, size_t size, int flags, const struct sockaddr * sock_addr, socklen_t addr_length)
Definition at line 141 of file sys-socket-stubs.cpp.
{
     struct iovec iov = {};
     iov.iov_base = const_cast<void *>(buffer);
     iov.iov_len = size;
     struct msghdr hdr = {};
     hdr.msg_name = const_cast<struct sockaddr *>(sock_addr);
     hdr.msg_namelen = addr_length;
     hdr.msg_iov = &iov;
     hdr.msg_iovlen = 1;
     return sendmsg(fd, &hdr, flags);
 }
References fd, mlibc::flags, iovec::iov_base, iovec::iov_len, msghdr::msg_iov, msghdr::msg_iovlen, msghdr::msg_name, msghdr::msg_namelen, sendmsg(), and size.
Referenced by mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), and send().
setsockopt()
int setsockopt (int fd, int layer, int number, const void * buffer, socklen_t size)
Definition at line 174 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setsockopt, -1);
     return mlibc::sys_setsockopt(fd, layer, number, buffer, size);
 }
References fd, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_setsockopt().
Referenced by socket_setup().
shutdown()
int shutdown (int , int)
Definition at line 180 of file sys-socket-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: shutdown() is a no-op!" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
sockatmark()
int sockatmark (int)
Definition at line 185 of file sys-socket-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
socket()
int socket (int family, int type, int protocol)
Definition at line 190 of file sys-socket-stubs.cpp.
{
     int fd;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_socket, -1);
     if(int e = mlibc::sys_socket(family, type, protocol, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_socket(), and type.
Referenced by __openlog(), NetworkUDP::UDP::Connect(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), run_test(), and socket_setup().
socketpair()
int socketpair (int domain, int type, int protocol, int sv[2])
Definition at line 200 of file sys-socket-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_socketpair, -1);
     if(int e = mlibc::sys_socketpair(domain, type, protocol, sv); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_socketpair(), and type.