Fennix Userspace: Userspace/apps/base/busybox/networking/tcpudp.c File Reference
tcpudp.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "tcpudp_perhost.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define verbose (G.verbose)
#define max_per_host (G.max_per_host)
#define cur_per_host (G.cur_per_host)
#define cnum (G.cnum)
#define cmax (G.cmax)
#define env_cur (G.env_cur)
#define env_var (G.env_var)
#define INIT_G()
Enumerations
enum {
OPT_c = (1 << 0) , OPT_C = (1 << 1) , OPT_i = (1 << 2) , OPT_x = (1 << 3) ,
OPT_u = (1 << 4) , OPT_l = (1 << 5) , OPT_E = (1 << 6) , OPT_b = (1 << 7) ,
OPT_h = (1 << 8) , OPT_p = (1 << 9) , OPT_t = (1 << 10) , OPT_v = (1 << 11) ,
OPT_V = (1 << 12) , OPT_U = (1 << 13) , OPT_slash = (1 << 14) , OPT_Z = (1 << 15) ,
OPT_K = (1 << 16)
}
Functions
static void xsetenv_plain (const char *n, const char *v)
static void xsetenv_proto (const char *proto, const char *n, const char *v)
static void undo_xsetenv (void)
static void sig_term_handler (int sig)
static void print_waitstat (unsigned pid, int wstat)
static void if_verbose_print_connection_status (void)
static void sig_child_handler (int sig UNUSED_PARAM)
int tcpudpsvd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
cmax
#define cmax (G.cmax)
Definition at line 139 of file tcpudp.c.
cnum
#define cnum (G.cnum)
Definition at line 138 of file tcpudp.c.
cur_per_host
#define cur_per_host (G.cur_per_host)
Definition at line 137 of file tcpudp.c.
env_cur
#define env_cur (G.env_cur)
Definition at line 140 of file tcpudp.c.
env_var
#define env_var (G.env_var)
Definition at line 141 of file tcpudp.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 134 of file tcpudp.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    cmax = 30; \
    env_cur = &env_var[0]; \
} while (0)
Definition at line 142 of file tcpudp.c.
max_per_host
#define max_per_host (G.max_per_host)
Definition at line 136 of file tcpudp.c.
verbose
#define verbose (G.verbose)
Definition at line 135 of file tcpudp.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_c
OPT_C
OPT_i
OPT_x
OPT_u
OPT_l
OPT_E
OPT_b
OPT_h
OPT_p
OPT_t
OPT_v
OPT_V
OPT_U
OPT_slash
OPT_Z
OPT_K
Definition at line 199 of file tcpudp.c.
      {
     OPT_c = (1 << 0),
     OPT_C = (1 << 1),
     OPT_i = (1 << 2),
     OPT_x = (1 << 3),
     OPT_u = (1 << 4),
     OPT_l = (1 << 5),
     OPT_E = (1 << 6),
     OPT_b = (1 << 7),
     OPT_h = (1 << 8),
     OPT_p = (1 << 9),
     OPT_t = (1 << 10),
     OPT_v = (1 << 11),
     OPT_V = (1 << 12),
     OPT_U = (1 << 13), /* from here: sslsvd only */
     OPT_slash = (1 << 14),
     OPT_Z = (1 << 15),
     OPT_K = (1 << 16),
 };
Function Documentation
if_verbose_print_connection_status()
static void if_verbose_print_connection_status (void) static
Definition at line 219 of file tcpudp.c.
 {
     if (verbose) {
         /* "only 1 client max" desn't need this */
         if (cmax > 1)
             bb_error_msg("status %u/%u", cnum, cmax);
     }
 }
References bb_error_msg(), cmax, cnum, and verbose.
Referenced by sig_child_handler(), and tcpudpsvd_main().
print_waitstat()
static void print_waitstat (unsigned pid, int wstat) static
Definition at line 183 of file tcpudp.c.
 {
     unsigned e = 0;
     const char *cause = "?exit";
     if (WIFEXITED(wstat)) {
         cause++;
         e = WEXITSTATUS(wstat);
     } else if (WIFSIGNALED(wstat)) {
         cause = "signal";
         e = WTERMSIG(wstat);
     }
     bb_error_msg("end %d %s %d", pid, cause, e);
 }
References bb_error_msg(), pid, WEXITSTATUS, WIFEXITED, WIFSIGNALED, wstat, and WTERMSIG.
Referenced by sig_child_handler().
sig_child_handler()
static void sig_child_handler (int sig UNUSED_PARAM) static
Definition at line 233 of file tcpudp.c.
 {
     int wstat;
     pid_t pid;
     int sv_errno = errno;
     while ((pid = wait_any_nohang(&wstat)) > 0) {
         if (max_per_host)
             ipsvd_perhost_remove(G.cc, pid);
         if (cnum)
             cnum--;
         if (verbose)
             print_waitstat(pid, wstat);
     }
     if_verbose_print_connection_status();
     errno = sv_errno;
 }
References cnum, errno, G, if_verbose_print_connection_status(), ipsvd_perhost_remove(), max_per_host, pid, print_waitstat(), verbose, wait_any_nohang(), and wstat.
Referenced by tcpudpsvd_main().
sig_term_handler()
static void sig_term_handler (int sig) static
Definition at line 174 of file tcpudp.c.
 {
     if (verbose)
         bb_error_msg("got signal %u, exit", sig);
     kill_myself_with_sig(sig);
 }
References bb_error_msg(), kill_myself_with_sig(), and verbose.
Referenced by tcpudpsvd_main().
tcpudpsvd_main()
int tcpudpsvd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 252 of file tcpudp.c.
 {
     char *str_C, *str_t;
     char *user;
     struct hcc *hccp;
     const char *instructs;
     char *msg_per_host = NULL;
     unsigned len_per_host = len_per_host; /* gcc */
 #ifndef SSLSVD
     struct bb_uidgid_t ugid;
 #endif
     bool tcp;
     uint16_t local_port;
     char *preset_local_hostname = NULL;
     char *remote_hostname = remote_hostname; /* for compiler */
     char *remote_addr = remote_addr; /* for compiler */
     len_and_sockaddr *lsa;
     len_and_sockaddr local, remote;
     socklen_t sa_len;
     int pid;
     int sock;
     int conn;
     unsigned backlog = 20;
     unsigned opts;
     INIT_G();
     tcp = (applet_name[0] == 't');
     /* "+": stop on first non-option */
 #ifdef SSLSVD
     opts = getopt32(argv, "^+"
         "c:+C:i:x:u:l:Eb:+hpt:vU:/:Z:K:" /* -c NUM, -b NUM */
         "\0"
         /* 3+ args, -i at most once, -p implies -h, -v is a counter */
         "-3:i--i:ph:vv",
         &cmax, &str_C, &instructs, &instructs, &user, &preset_local_hostname,
         &backlog, &str_t, &ssluser, &root, &cert, &key, &verbose
     );
 #else
     opts = getopt32(argv, "^+"
         "c:+C:i:x:u:l:Eb:+hpt:v" /* -c NUM, -b NUM */
         "\0"
         /* 3+ args, -i at most once, -p implies -h, -v is a counter */
         "-3:i--i:ph:vv",
         &cmax, &str_C, &instructs, &instructs, &user, &preset_local_hostname,
         &backlog, &str_t, &verbose
     );
 #endif
     if (opts & OPT_C) { /* -C n[:message] */
         max_per_host = bb_strtou(str_C, &str_C, 10);
         if (str_C[0]) {
             if (str_C[0] != ':')
                 bb_show_usage();
             msg_per_host = str_C + 1;
             len_per_host = strlen(msg_per_host);
         }
     }
     if (max_per_host > cmax)
         max_per_host = cmax;
     if (opts & OPT_u) {
         xget_uidgid(&ugid, user);
     }
 #ifdef SSLSVD
     if (opts & OPT_U) ssluser = optarg;
     if (opts & OPT_slash) root = optarg;
     if (opts & OPT_Z) cert = optarg;
     if (opts & OPT_K) key = optarg;
 #endif
     argv += optind;
     if (!argv[0][0] || LONE_CHAR(argv[0], '0'))
         argv[0] = (char*)"0.0.0.0";
     /* Per-IP flood protection is not thought-out for UDP */
     if (!tcp)
         max_per_host = 0;
     bb_sanitize_stdio(); /* fd# 0,1,2 must be opened */
 #ifdef SSLSVD
     sslser = user;
     client = 0;
     if ((getuid() == 0) && !(opts & OPT_u)) {
         xfunc_error_retval = 100;
         bb_simple_error_msg_and_die(bb_msg_you_must_be_root);
     }
     if (opts & OPT_u)
         if (!uidgid_get(&sslugid, ssluser, 1)) {
             if (errno) {
                 bb_perror_msg_and_die("can't get user/group: %s", ssluser);
             }
             bb_error_msg_and_die("unknown user/group %s", ssluser);
         }
     if (!cert) cert = "./cert.pem";
     if (!key) key = cert;
     if (matrixSslOpen() < 0)
         fatal("can't initialize ssl");
     if (matrixSslReadKeys(&keys, cert, key, 0, ca) < 0) {
         if (client)
             fatal("can't read cert, key, or ca file");
         fatal("can't read cert or key file");
     }
     if (matrixSslNewSession(&ssl, keys, 0, SSL_FLAGS_SERVER) < 0)
         fatal("can't create ssl session");
 #endif
     sig_block(SIGCHLD);
     signal(SIGCHLD, sig_child_handler);
     bb_signals(BB_FATAL_SIGS, sig_term_handler);
     signal(SIGPIPE, SIG_IGN);
     if (max_per_host)
         G.cc = ipsvd_perhost_init(cmax);
     local_port = bb_lookup_port(argv[1], tcp ? "tcp" : "udp", 0);
     lsa = xhost2sockaddr(argv[0], local_port);
     argv += 2;
     sock = xsocket(lsa->u.sa.sa_family, tcp ? SOCK_STREAM : SOCK_DGRAM, 0);
     setsockopt_reuseaddr(sock);
     sa_len = lsa->len; /* I presume sockaddr len stays the same */
     xbind(sock, &lsa->u.sa, sa_len);
     if (tcp) {
         xlisten(sock, backlog);
         close_on_exec_on(sock);
     } else { /* udp: needed for recv_from_to to work: */
         socket_want_pktinfo(sock);
     }
     /* ndelay_off(sock); - it is the default I think? */
 #ifndef SSLSVD
     if (opts & OPT_u) {
         /* drop permissions */
         xsetgid(ugid.gid);
         xsetuid(ugid.uid);
     }
 #endif
     if (verbose) {
         char *addr = xmalloc_sockaddr2dotted(&lsa->u.sa);
         if (opts & OPT_u)
             bb_error_msg("listening on %s, starting, uid %u, gid %u", addr,
                 (unsigned)ugid.uid, (unsigned)ugid.gid);
         else
             bb_error_msg("listening on %s, starting", addr);
         free(addr);
     }
     /* Main accept() loop */
  again:
     hccp = NULL;
  again1:
     close(0);
     /* It's important to close(0) _before_ wait loop:
      * fd#0 can be a shared connection fd.
      * If kept open by us, peer can't detect PROG closing it.
      */
     while (cnum >= cmax)
         wait_for_any_sig(); /* expecting SIGCHLD */
  again2:
     sig_unblock(SIGCHLD);
     local.len = remote.len = sa_len;
     if (tcp) {
         /* Accept a connection to fd #0 */
         conn = accept(sock, &remote.u.sa, &remote.len);
     } else {
         /* In case recv_from_to won't be able to recover local addr.
          * Also sets port - recv_from_to is unable to do it. */
         local = *lsa;
         conn = recv_from_to(sock, NULL, 0, MSG_PEEK,
                 &remote.u.sa, &local.u.sa, sa_len);
     }
     sig_block(SIGCHLD);
     if (conn < 0) {
         if (errno != EINTR)
             bb_simple_perror_msg(tcp ? "accept" : "recv");
         goto again2;
     }
     xmove_fd(tcp ? conn : sock, 0);
     if (max_per_host) {
         /* Drop connection immediately if cur_per_host > max_per_host
          * (minimizing load under SYN flood) */
         remote_addr = xmalloc_sockaddr2dotted_noport(&remote.u.sa);
         cur_per_host = ipsvd_perhost_add(G.cc, remote_addr, max_per_host, &hccp);
         if (cur_per_host > max_per_host) {
             /* ipsvd_perhost_add detected that max is exceeded
              * (and did not store ip in connection table) */
             free(remote_addr);
             if (msg_per_host) {
                 /* don't block or test for errors */
                 send(0, msg_per_host, len_per_host, MSG_DONTWAIT);
             }
             goto again1;
         }
         /* NB: remote_addr is not leaked, it is stored in conn table */
     }
     if (!tcp) {
         /* Voodoo magic: making udp sockets each receive its own
          * packets is not trivial, and I still not sure
          * I do it 100% right.
          * 1) we have to do it before fork()
          * 2) order is important - is it right now? */
         /* Open new non-connected UDP socket for further clients... */
         sock = xsocket(lsa->u.sa.sa_family, SOCK_DGRAM, 0);
         setsockopt_reuseaddr(sock);
         /* Make plain write/send work for old socket by supplying default
          * destination address. This also restricts incoming packets
          * to ones coming from this remote IP. */
         xconnect(0, &remote.u.sa, sa_len);
     /* hole? at this point we have no wildcard udp socket...
      * can this cause clients to get "port unreachable" icmp?
      * Yup, time window is very small, but it exists (does it?) */
         /* ..."open new socket", continued */
         xbind(sock, &lsa->u.sa, sa_len);
         socket_want_pktinfo(sock);
         /* Doesn't work:
          * we cannot replace fd #0 - we will lose pending packet
          * which is already buffered for us! And we cannot use fd #1
          * instead - it will "intercept" all following packets, but child
          * does not expect data coming *from fd #1*! */
 #if 0
         /* Make it so that local addr is fixed to localp->u.sa
          * and we don't accidentally accept packets to other local IPs. */
         /* NB: we possibly bind to the _very_ same_ address & port as the one
          * already bound in parent! This seems to work in Linux.
          * (otherwise we can move socket to fd #0 only if bind succeeds) */
         close(0);
         set_nport(&localp->u.sa, htons(local_port));
         xmove_fd(xsocket(localp->u.sa.sa_family, SOCK_DGRAM, 0), 0);
         setsockopt_reuseaddr(0); /* crucial */
         xbind(0, &localp->u.sa, localp->len);
 #endif
     }
     pid = vfork();
     if (pid == -1) {
         bb_simple_perror_msg("vfork");
         goto again;
     }
     if (pid != 0) {
         /* Parent */
         cnum++;
         if_verbose_print_connection_status();
         if (hccp)
             hccp->pid = pid;
         /* clean up changes done by vforked child */
         undo_xsetenv();
         goto again;
     }
     /* Child: prepare env, log, and exec prog */
     { /* vfork alert! every xmalloc in this block should be freed! */
         char *local_hostname = local_hostname; /* for compiler */
         char *local_addr = NULL;
         char *free_me0 = NULL;
         char *free_me1 = NULL;
         char *free_me2 = NULL;
         if (verbose || !(opts & OPT_E)) {
             if (!max_per_host) /* remote_addr is not yet known */
                 free_me0 = remote_addr = xmalloc_sockaddr2dotted(&remote.u.sa);
             if (opts & OPT_h) {
                 free_me1 = remote_hostname = xmalloc_sockaddr2host_noport(&remote.u.sa);
                 if (!remote_hostname) {
                     bb_error_msg("can't look up hostname for %s", remote_addr);
                     remote_hostname = remote_addr;
                 }
             }
             /* Find out local IP peer connected to.
              * Errors ignored (I'm not paranoid enough to imagine kernel
              * which doesn't know local IP). */
             if (tcp)
                 getsockname(0, &local.u.sa, &local.len);
             /* else: for UDP it is done earlier by parent */
             local_addr = xmalloc_sockaddr2dotted(&local.u.sa);
             if (opts & OPT_h) {
                 local_hostname = preset_local_hostname;
                 if (!local_hostname) {
                     free_me2 = local_hostname = xmalloc_sockaddr2host_noport(&local.u.sa);
                     if (!local_hostname)
                         bb_error_msg_and_die("can't look up hostname for %s", local_addr);
                 }
                 /* else: local_hostname is not NULL, but is NOT malloced! */
             }
         }
         if (verbose) {
             pid = getpid();
             if (max_per_host) {
                 bb_error_msg("concurrency %s %u/%u",
                     remote_addr,
                     cur_per_host, max_per_host);
             }
             bb_error_msg((opts & OPT_h)
                 ? "start %u %s-%s (%s-%s)"
                 : "start %u %s-%s",
                 pid,
                 local_addr, remote_addr,
                 local_hostname, remote_hostname);
         }
         if (!(opts & OPT_E)) {
             /* setup ucspi env */
             const char *proto = tcp ? "TCP" : "UDP";
 #ifdef SO_ORIGINAL_DST
             /* Extract "original" destination addr:port
              * from Linux firewall. Useful when you redirect
              * an outbond connection to local handler, and it needs
              * to know where it originally tried to connect */
             if (tcp && getsockopt(0, SOL_IP, SO_ORIGINAL_DST, &local.u.sa, &local.len) == 0) {
                 char *addr = xmalloc_sockaddr2dotted(&local.u.sa);
                 xsetenv_plain("TCPORIGDSTADDR", addr);
                 free(addr);
             }
 #endif
             xsetenv_plain("PROTO", proto);
             xsetenv_proto(proto, "LOCALADDR", local_addr);
             xsetenv_proto(proto, "REMOTEADDR", remote_addr);
             if (opts & OPT_h) {
                 xsetenv_proto(proto, "LOCALHOST", local_hostname);
                 xsetenv_proto(proto, "REMOTEHOST", remote_hostname);
             }
             //compat? xsetenv_proto(proto, "REMOTEINFO", "");
             /* additional */
             if (cur_per_host > 0) /* can not be true for udp */
                 xsetenv_plain("TCPCONCURRENCY", utoa(cur_per_host));
         }
         free(local_addr);
         free(free_me0);
         free(free_me1);
         free(free_me2);
     }
     xdup2(0, 1);
     /* Restore signal handling for the to-be-execed process */
     signal(SIGPIPE, SIG_DFL); /* this one was SIG_IGNed */
     /* Non-ignored signals revert to SIG_DFL on exec anyway
      * But we can get signals BEFORE execvp(), this is unlikely
      * but it would invoke sig_child_handler(), which would
      * check waitpid(WNOHANG), then print "status N/M" if verbose.
      * I guess we can live with that possibility.
      */
     /*signal(SIGCHLD, SIG_DFL);*/
     sig_unblock(SIGCHLD);
 #ifdef SSLSVD
     strcpy(id, utoa(pid));
     ssl_io(0, argv);
     bb_perror_msg_and_die("can't execute '%s'", argv[0]);
 #else
     BB_EXECVP_or_die(argv);
 #endif
 }
References accept(), addr, applet_name, argv, bb_error_msg(), bb_error_msg_and_die(), BB_EXECVP_or_die(), BB_FATAL_SIGS, bb_lookup_port(), bb_perror_msg_and_die(), bb_sanitize_stdio(), bb_show_usage(), bb_signals(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), bb_strtou(), close(), close_on_exec_on(), cmax, cnum, cur_per_host, EINTR, errno, free, G, getopt32(), getpid(), getsockname(), getsockopt(), getuid, bb_uidgid_t::gid, htons(), if_verbose_print_connection_status(), INIT_G, ipsvd_perhost_add(), ipsvd_perhost_init(), keys, len_and_sockaddr::len, local, LONE_CHAR, lsa, max_per_host, MSG_DONTWAIT, MSG_PEEK, NULL, OPT_C, OPT_E, OPT_h, OPT_K, OPT_slash, OPT_u, OPT_U, OPT_Z, optarg, optind, hcc::pid, pid, recv_from_to(), send(), set_nport(), setsockopt_reuseaddr(), sig_block(), sig_child_handler(), SIG_DFL, SIG_IGN, sig_term_handler(), sig_unblock(), SIGCHLD, signal, SIGPIPE, sock, SOCK_DGRAM, SOCK_STREAM, socket_want_pktinfo(), SOL_IP, strcpy(), strlen(), len_and_sockaddr::u, bb_uidgid_t::uid, undo_xsetenv(), user, utoa(), verbose, vfork(), wait_for_any_sig(), xbind(), xconnect(), xdup2(), xfunc_error_retval, xget_uidgid(), xhost2sockaddr(), xlisten(), xmalloc_sockaddr2dotted(), xmalloc_sockaddr2dotted_noport(), xmalloc_sockaddr2host_noport(), xmove_fd(), xsetenv_plain(), xsetenv_proto(), xsetgid(), xsetuid(), and xsocket().
undo_xsetenv()
static void undo_xsetenv (void) static
Definition at line 164 of file tcpudp.c.
 {
     char **pp = env_cur = &env_var[0];
     while (*pp) {
         char *var = *pp;
         bb_unsetenv_and_free(var);
         *pp++ = NULL;
     }
 }
References bb_unsetenv_and_free(), env_cur, env_var, and NULL.
Referenced by tcpudpsvd_main().
xsetenv_plain()
static void xsetenv_plain (const char * n, const char * v) static
Definition at line 150 of file tcpudp.c.
 {
     char *var = xasprintf("%s=%s", n, v);
     *env_cur++ = var;
     putenv(var);
 }
References env_cur, n, putenv(), and xasprintf().
Referenced by tcpudpsvd_main().
xsetenv_proto()
static void xsetenv_proto (const char * proto, const char * n, const char * v) static
Definition at line 157 of file tcpudp.c.
 {
     char *var = xasprintf("%s%s=%s", proto, n, v);
     *env_cur++ = var;
     putenv(var);
 }
References env_cur, n, putenv(), and xasprintf().
Referenced by tcpudpsvd_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING