Fennix Userspace: Userspace/apps/base/bash/lib/sh/strchrnul.c File Reference
strchrnul.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
Functions
char * strchrnul (char *s, int c_in) const
Function Documentation
strchrnul()
char* strchrnul (char * s, int c_in) const
Definition at line 25 of file strchrnul.c.
 {
   char c;
   register char *s1;
   for (c = c_in, s1 = (char *)s; s1 && *s1 && *s1 != c; s1++)
     ;
   return (s1);
 }
References c, s, and s1.
Referenced by append_mount_options(), bb_init_module_24(), cmdio_get_cmd_and_arg(), compile_fs_type(), config_read(), devmem_main(), display_header(), do_all_in_proc_swaps(), download_one_url(), dump_procs(), escape_text(), evalcommand(), fb_drawimage(), fgets_trim_sanitize(), find_in_path(), hostname_main(), klogd_main(), main(), make_device(), man_main(), match_opt(), padvance_magic(), parse_cmd_args(), parse_datestr(), parse_file_cmd(), process_pid_str(), rdval_diskstats(), read_cmdline(), run_pipe(), seq_main(), set_output_base(), setvar(), setvareq(), sha_crypt(), shell_builtin_ulimit(), single_quote(), singlemount(), smtp_checkp(), strsep_quotes(), sysctl_dots_to_slashes(), syslogd_main(), ubi_get_volid_by_name(), unbackslash(), and update_passwd().