Fennix Userspace: Userspace/musl/include/wchar.h File Reference
wchar.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define __NEED_FILE
#define __NEED___isoc_va_list
#define __NEED_size_t
#define __NEED_wchar_t
#define __NEED_wint_t
#define __NEED_mbstate_t
#define __NEED_struct__IO_FILE
#define WCHAR_MAX (0x7fffffff+L'\0')
#define WCHAR_MIN (-1-0x7fffffff+L'\0')
#define NULL ((void*)0)
#define WEOF 0xffffffffU
Functions
wchar_t * wcscpy (wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcsncpy (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wcscat (wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcsncat (wchar_t *__restrict, const wchar_t *__restrict, size_t)
int wcscmp (const wchar_t *, const wchar_t *)
int wcsncmp (const wchar_t *, const wchar_t *, size_t)
int wcscoll (const wchar_t *, const wchar_t *)
size_t wcsxfrm (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wcschr (const wchar_t *, wchar_t)
wchar_t * wcsrchr (const wchar_t *, wchar_t)
size_t wcscspn (const wchar_t *, const wchar_t *)
size_t wcsspn (const wchar_t *, const wchar_t *)
wchar_t * wcspbrk (const wchar_t *, const wchar_t *)
wchar_t * wcstok (wchar_t *__restrict, const wchar_t *__restrict, wchar_t **__restrict)
size_t wcslen (const wchar_t *)
wchar_t * wcsstr (const wchar_t *__restrict, const wchar_t *__restrict)
wchar_t * wcswcs (const wchar_t *, const wchar_t *)
wchar_t * wmemchr (const wchar_t *, wchar_t, size_t)
int wmemcmp (const wchar_t *, const wchar_t *, size_t)
wchar_t * wmemcpy (wchar_t *__restrict, const wchar_t *__restrict, size_t)
wchar_t * wmemmove (wchar_t *, const wchar_t *, size_t)
wchar_t * wmemset (wchar_t *, wchar_t, size_t)
wint_t btowc (int)
int wctob (wint_t)
int mbsinit (const mbstate_t *)
size_t mbrtowc (wchar_t *__restrict, const char *__restrict, size_t, mbstate_t *__restrict)
size_t wcrtomb (char *__restrict, wchar_t, mbstate_t *__restrict)
size_t mbrlen (const char *__restrict, size_t, mbstate_t *__restrict)
size_t mbsrtowcs (wchar_t *__restrict, const char **__restrict, size_t, mbstate_t *__restrict)
size_t wcsrtombs (char *__restrict, const wchar_t **__restrict, size_t, mbstate_t *__restrict)
float wcstof (const wchar_t *__restrict, wchar_t **__restrict)
double wcstod (const wchar_t *__restrict, wchar_t **__restrict)
long double wcstold (const wchar_t *__restrict, wchar_t **__restrict)
long wcstol (const wchar_t *__restrict, wchar_t **__restrict, int)
unsigned long wcstoul (const wchar_t *__restrict, wchar_t **__restrict, int)
long long wcstoll (const wchar_t *__restrict, wchar_t **__restrict, int)
unsigned long long wcstoull (const wchar_t *__restrict, wchar_t **__restrict, int)
int fwide (FILE *, int)
int wprintf (const wchar_t *__restrict,...)
int fwprintf (FILE *__restrict, const wchar_t *__restrict,...)
int swprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict,...)
int vwprintf (const wchar_t *__restrict, __isoc_va_list)
int vfwprintf (FILE *__restrict, const wchar_t *__restrict, __isoc_va_list)
int vswprintf (wchar_t *__restrict, size_t, const wchar_t *__restrict, __isoc_va_list)
int wscanf (const wchar_t *__restrict,...)
int fwscanf (FILE *__restrict, const wchar_t *__restrict,...)
int swscanf (const wchar_t *__restrict, const wchar_t *__restrict,...)
int vwscanf (const wchar_t *__restrict, __isoc_va_list)
int vfwscanf (FILE *__restrict, const wchar_t *__restrict, __isoc_va_list)
int vswscanf (const wchar_t *__restrict, const wchar_t *__restrict, __isoc_va_list)
wint_t fgetwc (FILE *)
wint_t getwc (FILE *)
wint_t getwchar (void)
wint_t fputwc (wchar_t, FILE *)
wint_t putwc (wchar_t, FILE *)
wint_t putwchar (wchar_t)
wchar_t * fgetws (wchar_t *__restrict, int, FILE *__restrict)
int fputws (const wchar_t *__restrict, FILE *__restrict)
wint_t ungetwc (wint_t, FILE *)
size_t wcsftime (wchar_t *__restrict, size_t, const wchar_t *__restrict, const struct tm *__restrict)
Macro Definition Documentation
__NEED___isoc_va_list
#define __NEED___isoc_va_list
Definition at line 11 of file wchar.h.
__NEED_FILE
#define __NEED_FILE
Definition at line 10 of file wchar.h.
__NEED_mbstate_t
#define __NEED_mbstate_t
Definition at line 15 of file wchar.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 12 of file wchar.h.
__NEED_struct__IO_FILE
#define __NEED_struct__IO_FILE
Definition at line 18 of file wchar.h.
__NEED_wchar_t
#define __NEED_wchar_t
Definition at line 13 of file wchar.h.
__NEED_wint_t
#define __NEED_wint_t
Definition at line 14 of file wchar.h.
NULL
#define NULL ((void*)0)
Definition at line 46 of file wchar.h.
WCHAR_MAX
#define WCHAR_MAX (0x7fffffff+L'\0')
Definition at line 37 of file wchar.h.
WCHAR_MIN
#define WCHAR_MIN (-1-0x7fffffff+L'\0')
Definition at line 38 of file wchar.h.
WEOF
#define WEOF 0xffffffffU
Definition at line 50 of file wchar.h.
Function Documentation
btowc()
wint_t btowc (int c)
Definition at line 21 of file wchar-stubs.cpp.
                     {
     if(c == EOF)
         return WEOF;
     char nc = c;
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     if(auto e = cc->promote_wtranscode(nc, wc); e != mlibc::charcode_error::null)
         return WEOF;
     return wc;
 }
References b, c, CODEUNIT, mlibc::current_charcode(), EOF, MB_CUR_MAX, mlibc::null, and WEOF.
Referenced by wprintf_core().
fgetwc()
wint_t fgetwc (FILE * f)
Definition at line 58 of file fgetwc.c.
 {
     wint_t c;
     FLOCK(f);
     c = __fgetwc_unlocked(f);
     FUNLOCK(f);
     return c;
 }
Referenced by getwc(), and getwchar().
fgetws()
wchar_t* fgetws (wchar_t * __restrict, int , FILE * __restrict)
fputwc()
wint_t fputwc (wchar_t c, FILE * f)
Definition at line 31 of file fputwc.c.
 {
     FLOCK(f);
     c = __fputwc_unlocked(c, f);
     FUNLOCK(f);
     return c;
 }
fputws()
int fputws (const wchar_t * __restrict, FILE * __restrict)
fwide()
int fwide (FILE * f, int mode)
Definition at line 5 of file fwide.c.
 {
     FLOCK(f);
     if (mode) {
         if (!f->locale) f->locale = MB_CUR_MAX==1
             ? C_LOCALE : UTF8_LOCALE;
         if (!f->mode) f->mode = mode>0 ? 1 : -1;
     }
     mode = f->mode;
     FUNLOCK(f);
     return mode;
 }
Referenced by __fgetwc_unlocked(), __fputwc_unlocked(), fputws(), open_wmemstream(), ungetwc(), vfwprintf(), and vfwscanf().
fwprintf()
int fwprintf (FILE * __restrict, const wchar_t * __restrict, ...)
fwscanf()
int fwscanf (FILE * __restrict, const wchar_t * __restrict, ...)
getwc()
wint_t getwc (FILE * f)
Definition at line 4 of file getwc.c.
 {
     return fgetwc(f);
 }
getwchar()
wint_t getwchar (void)
Definition at line 4 of file getwchar.c.
 {
     return fgetwc(stdin);
 }
mbrlen()
size_t mbrlen (const char * __restrict, size_t mb_limit, mbstate_t * __restrict)
Definition at line 44 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     if(!stp)
         stp = &mbrlen_state;
     if(!mbs) {
         *stp = __MLIBC_MBSTATE_INITIALIZER;
         return 0;
     }
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{&wc, &wc + 1};
     if(auto e = cc->decode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null)
         __ensure(!"decode_wtranscode() errors are not handled");
     return nseq.it - mbs;
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{wchar-stubs.cpp}::mbrlen_state, and mlibc::null.
Referenced by mbschr().
mbrtowc()
size_t mbrtowc (wchar_t * __restrict, const char * __restrict, size_t mb_limit, mbstate_t * __restrict)
Definition at line 62 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     if(!stp)
         stp = &mbrtowc_state;
     if(!mbs) {
         *stp = __MLIBC_MBSTATE_INITIALIZER;
         return 0;
     }
     wchar_t temp = 0;
     if(!wcp)
         wcp = &temp;
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{wcp, wcp + 1};
     if(auto e = cc->decode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         if(e == mlibc::charcode_error::input_underflow)
             return static_cast<size_t>(-2);
         __ensure(e == mlibc::charcode_error::illegal_input);
         errno = EILSEQ;
         return static_cast<size_t>(-1);
     }else{
         if (*mbs) {
             return nseq.it - mbs;
         } else {
             *stp = __MLIBC_MBSTATE_INITIALIZER;
             *wcp = 0;
             return 0;
         }
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), EILSEQ, errno, mlibc::illegal_input, mlibc::input_underflow, anonymous_namespace{wchar-stubs.cpp}::mbrtowc_state, and mlibc::null.
Referenced by __fgetwc_unlocked_internal(), ansic_quote(), ansicstr(), mbrlen(), mbrtoc16(), mbrtoc32(), mbsnrtowcs(), read_comsub(), sh_modcase(), verify_decode(), and vfscanf().
mbsinit()
int mbsinit (const mbstate_t * stp)
Definition at line 38 of file wchar-stubs.cpp.
{
     if(!stp)
         return -1;
     return !stp->__progress && !stp->__shift;
 }
References __mlibc_mbstate::__progress, and __mlibc_mbstate::__shift.
Referenced by vfscanf().
mbsrtowcs()
size_t mbsrtowcs (wchar_t * __restrict, const char ** __restrict, size_t wc_limit, mbstate_t * __restrict)
Definition at line 117 of file wchar-stubs.cpp.
{
     __ensure(mbsp);
     auto cc = mlibc::current_charcode();
     __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
     mlibc::code_seq<const char> nseq{*mbsp, nullptr};
     mlibc::code_seq<wchar_t> wseq{wcs, wcs + wc_limit};
     if(!stp)
         stp = &mbsrtowcs_state;
     if(!wcs) {
         size_t size;
         if(auto e = cc->decode_wtranscode_length(nseq, &size, st); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->decode_wtranscode(nseq, wseq, st); e != mlibc::charcode_error::null) {
         __ensure(!"decode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = wseq.it - wcs;
         if(n < wc_limit) // Null-terminate resulting wide string.
             wcs[n] = 0;
         *mbsp = nullptr;
         return n;
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{wchar-stubs.cpp}::mbsrtowcs_state, n, mlibc::null, and size.
Referenced by mbsnrtowcs(), and mbstowcs().
putwc()
wint_t putwc (wchar_t c, FILE * f)
Definition at line 4 of file putwc.c.
 {
     return fputwc(c, f);
 }
putwchar()
wint_t putwchar (wchar_t c)
Definition at line 4 of file putwchar.c.
 {
     return fputwc(c, stdout);
 }
swprintf()
int swprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, ...)
swscanf()
int swscanf (const wchar_t * __restrict, const wchar_t * __restrict, ...)
ungetwc()
wint_t ungetwc (wint_t c, FILE * f)
Definition at line 8 of file ungetwc.c.
 {
     unsigned char mbc[MB_LEN_MAX];
     int l;
     locale_t *ploc = &CURRENT_LOCALE, loc = *ploc;
     FLOCK(f);
     if (f->mode <= 0) fwide(f, 1);
     *ploc = f->locale;
     if (!f->rpos) __toread(f);
     if (!f->rpos || c == WEOF || (l = wcrtomb((void *)mbc, c, 0)) < 0 ||
         f->rpos < f->buf - UNGET + l) {
         FUNLOCK(f);
         *ploc = loc;
         return WEOF;
     }
     if (isascii(c)) *--f->rpos = c;
     else memcpy(f->rpos -= l, mbc, l);
     f->flags &= ~F_EOF;
     FUNLOCK(f);
     *ploc = loc;
     return c;
 }
vfwprintf()
int vfwprintf (FILE * __restrict, const wchar_t * __restrict, __isoc_va_list)
vfwscanf()
int vfwscanf (FILE * __restrict, const wchar_t * __restrict, __isoc_va_list)
vswprintf()
int vswprintf (wchar_t * __restrict, size_t , const wchar_t * __restrict, __isoc_va_list)
vswscanf()
int vswscanf (const wchar_t * __restrict, const wchar_t * __restrict, __isoc_va_list)
vwprintf()
int vwprintf (const wchar_t * __restrict, __isoc_va_list)
vwscanf()
int vwscanf (const wchar_t * __restrict, __isoc_va_list)
wcrtomb()
size_t wcrtomb (char * __restrict, wchar_t wc, mbstate_t * __restrict)
Definition at line 95 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     // wcrtomb() always takes a mbstate_t.
     __ensure(stp);
     // TODO: Implement the following case:
     __ensure(mbs);
     mlibc::code_seq<const wchar_t> wseq{&wc, &wc + 1};
     mlibc::code_seq<char> nseq{mbs, mbs + 4}; // TODO: Replace 4 by some named constant.
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = nseq.it - mbs;
         if(!n) // Null-terminate resulting wide string.
             *mbs = 0;
         return n;
     }
 }
References __ensure, mlibc::current_charcode(), n, and mlibc::null.
Referenced by c16rtomb(), c32rtomb(), PrintfAgent< F >::operator()(), sh_modcase(), ungetwc(), wcsnrtombs(), wcsrtombs(), and wctomb().
wcscat()
wchar_t* wcscat (wchar_t * __restrict, const wchar_t * __restrict)
wcschr()
wchar_t* wcschr (const wchar_t * s, wchar_t c)
Definition at line 297 of file string-stubs.cpp.
{
     if(!c)
         return (wchar_t *)s + wcslen(s);
     for(; *s && *s != c; s++);
     return *s ? (wchar_t *)s : 0;
 }
References c, and wcslen().
Referenced by iswspace(), string_extract_verbatim(), wcscspn(), wcsspn(), and wcsstr().
wcscmp()
int wcscmp (const wchar_t * l, const wchar_t * r)
Definition at line 3 of file wcscmp.c.
 {
     for (; *l==*r && *l && *r; l++, r++);
     return *l < *r ? -1 : *l > *r;
 }
wcscoll()
int wcscoll (const wchar_t * l, const wchar_t * r)
Definition at line 11 of file wcscoll.c.
 {
     return __wcscoll_l(l, r, CURRENT_LOCALE);
 }
wcscpy()
wchar_t* wcscpy (wchar_t * __restrict, const wchar_t * __restrict)
wcscspn()
size_t wcscspn (const wchar_t * s, const wchar_t * c)
Definition at line 3 of file wcscspn.c.
 {
     const wchar_t *a;
     if (!c[0]) return wcslen(s);
     if (!c[1]) return (s=wcschr(a=s, *c)) ? s-a : wcslen(a);
     for (a=s; *s && !wcschr(c, *s); s++);
     return s-a;
 }
wcsftime()
size_t wcsftime (wchar_t * __restrict, size_t , const wchar_t * __restrict, const struct tm * __restrict)
Definition at line 348 of file time-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: wcsftime is a stub" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
wcslen()
size_t wcslen (const wchar_t * s)
Definition at line 325 of file string-stubs.cpp.
{
     const wchar_t *a;
     for(a = s; *s; s++);
     return s-a;
 }
Referenced by __wcsxfrm_l(), main(), wcpcpy(), wcscat(), wcschr(), wcscspn(), wcsdup(), wcsncat(), and wcsrchr().
wcsncat()
wchar_t* wcsncat (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wcsncmp()
int wcsncmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 3 of file wcsncmp.c.
 {
     for (; n && *l==*r && *l && *r; n--, l++, r++);
     return n ? (*l < *r ? -1 : *l > *r) : 0;
 }
wcsncpy()
wchar_t* wcsncpy (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wcspbrk()
wchar_t* wcspbrk (const wchar_t * s, const wchar_t * b)
Definition at line 3 of file wcspbrk.c.
 {
     s += wcscspn(s, b);
     return *s ? (wchar_t *)s : NULL;
 }
wcsrchr()
wchar_t* wcsrchr (const wchar_t * s, wchar_t c)
Definition at line 307 of file string-stubs.cpp.
{
     const wchar_t *p;
     for(p = s + wcslen(s); p >= s && *p != c; p--);
     return p >= s ? (wchar_t *)p : 0;
 }
References c, p, and wcslen().
wcsrtombs()
size_t wcsrtombs (char * __restrict, const wchar_t ** __restrict, size_t mb_limit, mbstate_t * __restrict)
Definition at line 177 of file wchar-stubs.cpp.
{
     __ensure(wcsp && "wcsrtombs() with null input");
     auto cc = mlibc::current_charcode();
     mlibc::code_seq<char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<const wchar_t> wseq{*wcsp, nullptr};
     if(!stp)
         stp = &wcsrtombs_state;
     if(!mbs) {
         size_t size;
         if(auto e = cc->encode_wtranscode_length(wseq, &size, *stp); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         *wcsp = wseq.it;
         size_t n = nseq.it - mbs;
         if(n < mb_limit) // Null-terminate resulting narrow string.
             mbs[n] = 0;
         return n;
     }
 }
References __ensure, mlibc::current_charcode(), n, mlibc::null, size, and anonymous_namespace{wchar-stubs.cpp}::wcsrtombs_state.
Referenced by fputws(), remove_pattern(), wcstombs(), and wstring_read().
wcsspn()
size_t wcsspn (const wchar_t * s, const wchar_t * c)
Definition at line 3 of file wcsspn.c.
 {
     const wchar_t *a;
     for (a=s; *s && wcschr(c, *s); s++);
     return s-a;
 }
wcsstr()
wchar_t* wcsstr (const wchar_t * __restrict, const wchar_t * __restrict)
wcstod()
double wcstod (const wchar_t * __restrict, wchar_t ** __restrict)
wcstof()
float wcstof (const wchar_t * __restrict, wchar_t ** __restrict)
wcstok()
wchar_t* wcstok (wchar_t * __restrict, const wchar_t * __restrict, wchar_t ** __restrict)
wcstol()
long wcstol (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstold()
long double wcstold (const wchar_t * __restrict, wchar_t ** __restrict)
wcstoll()
long long wcstoll (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstoul()
unsigned long wcstoul (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcstoull()
unsigned long long wcstoull (const wchar_t * __restrict, wchar_t ** __restrict, int)
wcswcs()
wchar_t* wcswcs (const wchar_t * haystack, const wchar_t * needle)
Definition at line 3 of file wcswcs.c.
 {
     return wcsstr(haystack, needle);
 }
References wcsstr().
wcsxfrm()
size_t wcsxfrm (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wctob()
int wctob (wint_t wc)
Definition at line 33 of file wchar-stubs.cpp.
                      {
     // TODO: Revisit this once we have character encoding functions.
     return wc;
 }
References c, EOF, IS_CODEUNIT, and MB_CUR_MAX.
wmemchr()
wchar_t* wmemchr (const wchar_t * s, wchar_t c, size_t n)
Definition at line 3 of file wmemchr.c.
 {
     for (; n && *s != c; n--, s++);
     return n ? (wchar_t *)s : 0;
 }
wmemcmp()
int wmemcmp (const wchar_t * l, const wchar_t * r, size_t n)
Definition at line 3 of file wmemcmp.c.
 {
     for (; n && *l==*r; n--, l++, r++);
     return n ? (*l < *r ? -1 : *l > *r) : 0;
 }
Referenced by main().
wmemcpy()
wchar_t* wmemcpy (wchar_t * __restrict, const wchar_t * __restrict, size_t)
wmemmove()
wchar_t* wmemmove (wchar_t * dest, const wchar_t * src, size_t n)
Definition at line 264 of file string-stubs.cpp.
{
     memmove(dest, src, n * sizeof(wchar_t));
     return dest;
 }
References memmove(), and n.
wmemset()
wchar_t* wmemset (wchar_t * d, wchar_t c, size_t n)
Definition at line 331 of file string-stubs.cpp.
{
     wchar_t *ret = d;
     while(n--)
         *d++ = c;
     return ret;
 }
References c, n, and ret.
Referenced by wcsncpy().
wprintf()
int wprintf (const wchar_t * __restrict, ...)
wscanf()
int wscanf (const wchar_t * __restrict, ...)