Fennix: Userspace/mlibc/options/posix/generic/posix_ctype.cpp File Reference
posix_ctype.cpp File Reference
#include <ctype.h>
#include <wctype.h>
#include <bits/ensure.h>
Functions
int isalnum_l (int c, locale_t)
int isalpha_l (int c, locale_t)
int isblank_l (int c, locale_t)
int iscntrl_l (int c, locale_t)
int isdigit_l (int c, locale_t)
int isgraph_l (int c, locale_t)
int islower_l (int c, locale_t)
int isprint_l (int c, locale_t)
int ispunct_l (int c, locale_t)
int isspace_l (int c, locale_t)
int isupper_l (int c, locale_t)
int isxdigit_l (int c, locale_t)
int isascii_l (int c, locale_t)
int tolower_l (int c, locale_t)
int toupper_l (int c, locale_t)
int iswalnum_l (wint_t c, locale_t)
int iswblank_l (wint_t c, locale_t)
int iswcntrl_l (wint_t c, locale_t)
int iswdigit_l (wint_t c, locale_t)
int iswgraph_l (wint_t c, locale_t)
int iswlower_l (wint_t c, locale_t)
int iswprint_l (wint_t c, locale_t)
int iswpunct_l (wint_t c, locale_t)
int iswspace_l (wint_t c, locale_t)
int iswupper_l (wint_t c, locale_t)
int iswxdigit_l (wint_t c, locale_t)
int iswalpha_l (wint_t c, locale_t)
wctype_t wctype_l (const char *p, locale_t)
int iswctype_l (wint_t w, wctype_t t, locale_t)
wint_t towlower_l (wint_t c, locale_t)
wint_t towupper_l (wint_t c, locale_t)
wctrans_t wctrans_l (const char *c, locale_t)
wint_t towctrans_l (wint_t c, wctrans_t desc, locale_t)
Function Documentation
isalnum_l()
int isalnum_l (int c, locale_t loc)
Definition at line 6 of file posix_ctype.cpp.
{
     return isalnum(c);
 }
References c, and isalnum().
isalpha_l()
int isalpha_l (int c, locale_t loc)
Definition at line 10 of file posix_ctype.cpp.
{
     return isalpha(c);
 }
References c, and isalpha().
isascii_l()
int isascii_l (int c, locale_t loc)
Definition at line 54 of file posix_ctype.cpp.
{
     return isascii(c);
 }
References c, and isascii().
isblank_l()
int isblank_l (int c, locale_t loc)
Definition at line 14 of file posix_ctype.cpp.
{
     return isblank(c);
 }
References c, and isblank().
iscntrl_l()
int iscntrl_l (int c, locale_t loc)
Definition at line 18 of file posix_ctype.cpp.
{
     return iscntrl(c);
 }
References c, and iscntrl().
isdigit_l()
int isdigit_l (int c, locale_t loc)
Definition at line 22 of file posix_ctype.cpp.
{
     return isdigit(c);
 }
References c, and isdigit().
isgraph_l()
int isgraph_l (int c, locale_t loc)
Definition at line 26 of file posix_ctype.cpp.
{
     return isgraph(c);
 }
References c, and isgraph().
islower_l()
int islower_l (int c, locale_t loc)
Definition at line 30 of file posix_ctype.cpp.
{
     return islower(c);
 }
References c, and islower().
isprint_l()
int isprint_l (int c, locale_t loc)
Definition at line 34 of file posix_ctype.cpp.
{
     return isprint(c);
 }
References c, and isprint().
ispunct_l()
int ispunct_l (int c, locale_t loc)
Definition at line 38 of file posix_ctype.cpp.
{
     return ispunct(c);
 }
References c, and ispunct().
isspace_l()
int isspace_l (int c, locale_t loc)
Definition at line 42 of file posix_ctype.cpp.
{
     return isspace(c);
 }
References c, and isspace().
isupper_l()
int isupper_l (int c, locale_t loc)
Definition at line 46 of file posix_ctype.cpp.
{
     return isupper(c);
 }
References c, and isupper().
iswalnum_l()
int iswalnum_l (wint_t c, locale_t)
Definition at line 66 of file posix_ctype.cpp.
{
     return iswalnum(c);
 }
References c, and iswalnum().
iswalpha_l()
int iswalpha_l (wint_t c, locale_t)
Definition at line 110 of file posix_ctype.cpp.
{
     return iswalpha(c);
 }
References c, and iswalpha().
iswblank_l()
int iswblank_l (wint_t c, locale_t)
Definition at line 70 of file posix_ctype.cpp.
{
     return iswblank(c);
 }
References c, and iswblank().
iswcntrl_l()
int iswcntrl_l (wint_t c, locale_t)
Definition at line 74 of file posix_ctype.cpp.
{
     return iswcntrl(c);
 }
References c, and iswcntrl().
iswctype_l()
int iswctype_l (wint_t w, wctype_t t, locale_t)
Definition at line 118 of file posix_ctype.cpp.
{
     return iswctype(w, t);
 }
References iswctype().
iswdigit_l()
int iswdigit_l (wint_t c, locale_t)
Definition at line 78 of file posix_ctype.cpp.
{
     return iswdigit(c);
 }
References c, and iswdigit().
iswgraph_l()
int iswgraph_l (wint_t c, locale_t)
Definition at line 82 of file posix_ctype.cpp.
{
     return iswgraph(c);
 }
References c, and iswgraph().
iswlower_l()
int iswlower_l (wint_t c, locale_t)
Definition at line 86 of file posix_ctype.cpp.
{
     return iswlower(c);
 }
References c, and iswlower().
iswprint_l()
int iswprint_l (wint_t c, locale_t)
Definition at line 90 of file posix_ctype.cpp.
{
     return iswprint(c);
 }
References c, and iswprint().
iswpunct_l()
int iswpunct_l (wint_t c, locale_t)
Definition at line 94 of file posix_ctype.cpp.
{
     return iswpunct(c);
 }
References c, and iswpunct().
iswspace_l()
int iswspace_l (wint_t c, locale_t)
Definition at line 98 of file posix_ctype.cpp.
{
     return iswspace(c);
 }
References c, and iswspace().
iswupper_l()
int iswupper_l (wint_t c, locale_t)
Definition at line 102 of file posix_ctype.cpp.
{
     return iswupper(c);
 }
References c, and iswupper().
iswxdigit_l()
int iswxdigit_l (wint_t c, locale_t)
Definition at line 106 of file posix_ctype.cpp.
{
     return iswxdigit(c);
 }
References c, and iswxdigit().
isxdigit_l()
int isxdigit_l (int c, locale_t loc)
Definition at line 50 of file posix_ctype.cpp.
{
     return isxdigit(c);
 }
References c, and isxdigit().
tolower_l()
int tolower_l (int c, locale_t loc)
Definition at line 58 of file posix_ctype.cpp.
{
     return tolower(c);
 }
References c, and tolower.
toupper_l()
int toupper_l (int c, locale_t loc)
Definition at line 62 of file posix_ctype.cpp.
{
     return toupper(c);
 }
References c, and toupper.
towctrans_l()
wint_t towctrans_l (wint_t c, wctrans_t desc, locale_t)
Definition at line 134 of file posix_ctype.cpp.
{
     return towctrans(c, desc);
 }
References c, and towctrans().
towlower_l()
wint_t towlower_l (wint_t c, locale_t)
Definition at line 122 of file posix_ctype.cpp.
{
     return towlower(c);
 }
References c, and towlower().
towupper_l()
wint_t towupper_l (wint_t c, locale_t)
Definition at line 126 of file posix_ctype.cpp.
{
     return towupper(c);
 }
References c, and towupper().
wctrans_l()
wctrans_t wctrans_l (const char * c, locale_t)
Definition at line 130 of file posix_ctype.cpp.
{
     return wctrans(c);
 }
References c, and wctrans().
wctype_l()
wctype_t wctype_l (const char * p, locale_t)
Definition at line 114 of file posix_ctype.cpp.
{
     return wctype(p);
 }
References p, and wctype().