Fennix Userspace: Userspace/musl/src/stdio/open_memstream.c File Reference
open_memstream.c File Reference
#include "stdio_impl.h"
#include <errno.h>
#include <limits.h>
#include <string.h>
#include <stdlib.h>
#include "libc.h"
Data Structures
struct cookie
struct ms_FILE
Functions
static off_t ms_seek (FILE *f, off_t off, int whence)
static size_t ms_write (FILE *f, const unsigned char *buf, size_t len)
static int ms_close (FILE *f)
FILE * open_memstream (char **bufp, size_t *sizep)
Data Structure Documentation
cookie
struct cookie
Definition at line 9 of file fmemopen.c.
Data Fields
unsigned char * buf
char * buf
wchar_t * buf
char ** bufp
wchar_t ** bufp
size_t l
size_t len
mbstate_t mbs
int mode
size_t n
size_t pos
char * s
size_t size
size_t * sizep
size_t space
wchar_t * ws
ms_FILE
struct ms_FILE
Definition at line 17 of file open_memstream.c.
Data Fields
unsigned char buf[BUFSIZ]
struct cookie c
FILE f
Function Documentation
ms_close()
static int ms_close (FILE * f) static
Definition at line 61 of file open_memstream.c.
 {
     return 0;
 }
Referenced by open_memstream().
ms_seek()
static off_t ms_seek (FILE * f, off_t off, int whence) static
Definition at line 23 of file open_memstream.c.
 {
     ssize_t base;
     struct cookie *c = f->cookie;
     if (whence>2U) {
 fail:
         errno = EINVAL;
         return -1;
     }
     base = (size_t [3]){0, c->pos, c->len}[whence];
     if (off < -base || off > SSIZE_MAX-base) goto fail;
     return c->pos = base+off;
 }
References base, c, _IO_FILE::cookie, EINVAL, errno, f, off, and SSIZE_MAX.
Referenced by open_memstream().
ms_write()
static size_t ms_write (FILE * f, const unsigned char * buf, size_t len) static
Definition at line 37 of file open_memstream.c.
 {
     struct cookie *c = f->cookie;
     size_t len2 = f->wpos - f->wbase;
     char *newbuf;
     if (len2) {
         f->wpos = f->wbase;
         if (ms_write(f, f->wbase, len2) < len2) return 0;
     }
     if (len + c->pos >= c->space) {
         len2 = 2*c->space+1 | c->pos+len+1;
         newbuf = realloc(c->buf, len2);
         if (!newbuf) return 0;
         *c->bufp = c->buf = newbuf;
         memset(c->buf + c->space, 0, len2 - c->space);
         c->space = len2;
     }
     memcpy(c->buf+c->pos, buf, len);
     c->pos += len;
     if (c->pos >= c->len) c->len = c->pos;
     *c->sizep = c->pos;
     return len;
 }
References buf, c, _IO_FILE::cookie, f, cookie::len, memcpy(), memset(), realloc, _IO_FILE::wbase, and _IO_FILE::wpos.
Referenced by open_memstream().
open_memstream()
FILE* open_memstream (char ** bufp, size_t * sizep)
Definition at line 66 of file open_memstream.c.
 {
     struct ms_FILE *f;
     char *buf;
     if (!(f=malloc(sizeof *f))) return 0;
     if (!(buf=malloc(sizeof *buf))) {
         free(f);
         return 0;
     }
     memset(&f->f, 0, sizeof f->f);
     memset(&f->c, 0, sizeof f->c);
     f->f.cookie = &f->c;
     f->c.bufp = bufp;
     f->c.sizep = sizep;
     f->c.pos = f->c.len = f->c.space = *sizep = 0;
     f->c.buf = *bufp = buf;
     *buf = 0;
     f->f.flags = F_NORD;
     f->f.fd = -1;
     f->f.buf = f->buf;
     f->f.buf_size = sizeof f->buf;
     f->f.lbf = EOF;
     f->f.write = ms_write;
     f->f.seek = ms_seek;
     f->f.close = ms_close;
     f->f.mode = -1;
     if (!libc.threaded) f->f.lock = -1;
     return __ofl_add(&f->f);
 }
References __ofl_add(), buf, _IO_FILE::buf, _IO_FILE::buf_size, _IO_FILE::close, _IO_FILE::cookie, EOF, f, F_NORD, _IO_FILE::fd, _IO_FILE::flags, free, _IO_FILE::lbf, libc, _IO_FILE::lock, malloc, memset(), _IO_FILE::mode, ms_close(), ms_seek(), ms_write(), _IO_FILE::seek, and _IO_FILE::write.