Fennix: Userspace/apps/base/bash/examples/loadables/tty.c File Reference
tty.c File Reference
#include "config.h"
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Functions
char * ttyname ()
int tty_builtin (WORD_LIST *list)
Variables
char * tty_doc []
struct builtin tty_struct
Function Documentation
tty_builtin()
int tty_builtin (WORD_LIST * list)
Definition at line 34 of file tty.c.
 {
   int opt, sflag;
   char *t;
   reset_internal_getopt ();
   sflag = 0;
   while ((opt = internal_getopt (list, "s")) != -1)
     {
       switch (opt)
     {
     case 's':
       sflag = 1;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   t = ttyname (0);
   QUIT;
   if (sflag == 0)
     puts (t ? t : "not a tty");
   return (t ? EXECUTION_SUCCESS : EXECUTION_FAILURE);
 }
References builtin_usage(), CASE_HELPOPT, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, internal_getopt(), list(), loptend, opt, puts(), QUIT, reset_internal_getopt(), sflag, t, and ttyname().
ttyname()
char* ttyname ()
Referenced by check_dev_tty(), decode_prompt_string(), and tty_builtin().
Variable Documentation
tty_doc
char* tty_doc[]
Initial value:
= {
    "Display terminal name.",
    "",
    "tty writes the name of the terminal that is opened for standard",
    "input to standard output.  If the `-s' option is supplied, nothing",
    "is written; the exit status determines whether or not the standard",
    "input is connected to a tty.",
    (char *)NULL
}
Definition at line 64 of file tty.c.
tty_struct
struct builtin tty_struct
Initial value:
= {
    "tty",
    tty_builtin,
    BUILTIN_ENABLED,
    tty_doc,
    "tty [-s]",
    0
}
Definition at line 64 of file tty.c.