Fennix Userspace: Userspace/apps/base/bash/lib/tilde/shell.c File Reference
shell.c File Reference
#include "ansi_stdlib.h"
#include <strings.h>
#include <pwd.h>
Functions
struct passwd * getpwuid ()
char * get_env_value (char *varname)
char * get_home_dir (void)
Function Documentation
get_env_value()
char* get_env_value (char * varname)
Definition at line 52 of file shell.c.
 {
   return ((char *)getenv (varname));
 }
References getenv.
get_home_dir()
char* get_home_dir (void)
Definition at line 60 of file shell.c.
 {
   static char *home_dir = (char *)NULL;
   struct passwd *entry;
   if (home_dir)
     return (home_dir);
 #if defined (HAVE_GETPWUID)
   entry = getpwuid (getuid ());
   if (entry)
     home_dir = savestring (entry->pw_dir);
 #endif
 #if defined (HAVE_GETPWENT)
   endpwent ();      /* some systems need this */
 #endif
   return (home_dir);
 }
References endpwent(), getpwuid(), getuid, NULL, and savestring().
getpwuid()
struct passwd* getpwuid ()
Referenced by get_current_user_info(), get_home_dir(), and sh_get_home_dir().