Fennix: Userspace/musl/src/mman/munmap.c File Reference
munmap.c File Reference
#include <sys/mman.h>
#include "syscall.h"
Functions
static void dummy (void)
weak_alias (dummy, __vm_wait)
int __munmap (void *start, size_t len)
weak_alias (__munmap, munmap)
Function Documentation
__munmap()
int __munmap (void * start, size_t len)
Definition at line 7 of file munmap.c.
 {
     __vm_wait();
     return syscall(SYS_munmap, start, len);
 }
References __vm_wait(), len, start, and syscall().
Referenced by __get_locale(), __pthread_create(), __pthread_timedjoin_np(), dcngettext(), do_tzset(), and unmap_chunk().
dummy()
static void dummy (void) static
Definition at line 4 of file munmap.c.
 { }
weak_alias() [1/2]
weak_alias (__munmap , munmap)
weak_alias() [2/2]
weak_alias (dummy , __vm_wait)