Fennix: Userspace/musl/include/sys/sem.h File Reference
sem.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <sys/ipc.h>
#include <bits/sem.h>
Data Structures
struct seminfo
struct sembuf
Macros
#define __NEED_size_t
#define __NEED_pid_t
#define __NEED_time_t
#define SEM_UNDO 0x1000
#define GETPID 11
#define GETVAL 12
#define GETALL 13
#define GETNCNT 14
#define GETZCNT 15
#define SETVAL 16
#define SETALL 17
#define _SEM_SEMUN_UNDEFINED 1
#define SEM_STAT (18 | (IPC_STAT & 0x100))
#define SEM_INFO 19
#define SEM_STAT_ANY (20 | (IPC_STAT & 0x100))
Functions
int semctl (int, int, int,...)
int semget (key_t, int, int)
int semop (int, struct sembuf *, size_t)
Data Structure Documentation
seminfo
struct seminfo
Definition at line 36 of file sem.h.
Data Fields
int semaem
int semmap
int semmni
int semmns
int semmnu
int semmsl
int semopm
int semume
int semusz
int semvmx
sembuf
struct sembuf
Definition at line 49 of file sem.h.
Data Fields
short sem_flg
unsigned short sem_num
short sem_op
Macro Definition Documentation
__NEED_pid_t
#define __NEED_pid_t
Definition at line 10 of file sem.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 9 of file sem.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 11 of file sem.h.
_SEM_SEMUN_UNDEFINED
#define _SEM_SEMUN_UNDEFINED 1
Definition at line 30 of file sem.h.
GETALL
#define GETALL 13
Definition at line 22 of file sem.h.
GETNCNT
#define GETNCNT 14
Definition at line 23 of file sem.h.
GETPID
#define GETPID 11
Definition at line 20 of file sem.h.
GETVAL
#define GETVAL 12
Definition at line 21 of file sem.h.
GETZCNT
#define GETZCNT 15
Definition at line 24 of file sem.h.
SEM_INFO
#define SEM_INFO 19
Definition at line 33 of file sem.h.
SEM_STAT
#define SEM_STAT (18 | (IPC_STAT & 0x100))
Definition at line 32 of file sem.h.
SEM_STAT_ANY
#define SEM_STAT_ANY (20 | (IPC_STAT & 0x100))
Definition at line 34 of file sem.h.
SEM_UNDO
#define SEM_UNDO 0x1000
Definition at line 19 of file sem.h.
SETALL
#define SETALL 17
Definition at line 26 of file sem.h.
SETVAL
#define SETVAL 16
Definition at line 25 of file sem.h.
Function Documentation
semctl()
int semctl (int id, int num, int cmd, ...)
Definition at line 17 of file semctl.c.
 {
     union semun arg = {0};
     va_list ap;
     switch (cmd & ~IPC_TIME64) {
     case SETVAL: case GETALL: case SETALL: case IPC_SET:
     case IPC_INFO: case SEM_INFO:
     case IPC_STAT & ~IPC_TIME64:
     case SEM_STAT & ~IPC_TIME64:
     case SEM_STAT_ANY & ~IPC_TIME64:
         va_start(ap, cmd);
         arg = va_arg(ap, union semun);
         va_end(ap);
     }
 #if IPC_TIME64
     struct semid_ds out, *orig;
     if (cmd&IPC_TIME64) {
         out = (struct semid_ds){0};
         orig = arg.buf;
         arg.buf = &out;
     }
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     struct semid_ds tmp;
     if (cmd == IPC_SET) {
         tmp = *arg.buf;
         tmp.sem_perm.mode *= 0x10000U;
         arg.buf = &tmp;
     }
 #endif
 #ifndef SYS_ipc
     int r = __syscall(SYS_semctl, id, num, IPC_CMD(cmd), arg.buf);
 #else
     int r = __syscall(SYS_ipc, IPCOP_semctl, id, num, IPC_CMD(cmd), &arg.buf);
 #endif
 #ifdef SYSCALL_IPC_BROKEN_MODE
     if (r >= 0) switch (cmd | IPC_TIME64) {
     case IPC_STAT:
     case SEM_STAT:
     case SEM_STAT_ANY:
         arg.buf->sem_perm.mode >>= 16;
     }
 #endif
 #if IPC_TIME64
     if (r >= 0 && (cmd&IPC_TIME64)) {
         arg.buf = orig;
         *arg.buf = out;
         IPC_HILO(arg.buf, sem_otime);
         IPC_HILO(arg.buf, sem_ctime);
     }
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), ap, cmd, GETALL, IPC_CMD, IPC_HILO, IPC_INFO, IPC_SET, IPC_STAT, IPC_TIME64, IPCOP_semctl, ipc_perm::mode, out(), semid_ds::sem_ctime, SEM_INFO, semid_ds::sem_otime, semid_ds::sem_perm, SEM_STAT, SEM_STAT_ANY, SETALL, SETVAL, va_arg, va_end, and va_start.
Referenced by do_sem(), ipcrm_main(), print_sem(), and remove_ids().
semget()
int semget (key_t key, int n, int fl)
Definition at line 7 of file semget.c.
 {
     /* The kernel uses the wrong type for the sem_nsems member
      * of struct semid_ds, and thus might not check that the
      * n fits in the correct (per POSIX) userspace type, so
      * we have to check here. */
     if (n > USHRT_MAX) return __syscall_ret(-EINVAL);
 #ifndef SYS_ipc
     return syscall(SYS_semget, key, n, fl);
 #else
     return syscall(SYS_ipc, IPCOP_semget, key, n, fl);
 #endif
 }
References __syscall_ret(), EINVAL, IPCOP_semget, n, syscall(), and USHRT_MAX.
Referenced by ipcrm_main(), and logread_main().
semop()
int semop (int id, struct sembuf * buf, size_t n)
Definition at line 5 of file semop.c.
 {
 #ifndef SYS_ipc
     return syscall(SYS_semop, id, buf, n);
 #else
     return syscall(SYS_ipc, IPCOP_semop, id, n, 0, buf);
 #endif
 }
References buf, IPCOP_semop, n, and syscall().
Referenced by logread_main(), and sem_up().