Fennix: Drivers/input/aip/keyboard.c File Reference
keyboard.c File Reference
#include "aip.h"
#include <driver.h>
#include <errno.h>
#include <fs.h>
#include <input.h>
#include <base.h>
#include <io.h>
Functions
int ReportKeyboardEvent (dev_t Device, KeyScanCodes ScanCode, uint8_t Pressed)
void PS2KbdInterruptHandler (TrapFrame *)
int __fs_kb_Ioctl (struct Inode *, unsigned long, void *)
int InitializeKeyboard ()
int FinalizeKeyboard ()
int DetectPS2Keyboard ()
Variables
uint8_t KeyboardScanCodeSet = 0
dev_t KeyboardDevID = -1
const unsigned short ScanCodeSet1 []
const unsigned short ScanCodeSet1mm []
const unsigned short ScanCodeSet3 []
InputReport kir = {0}
bool IsE0 = false
bool IsE1 = false
const struct InodeOperations KbdOps
Function Documentation
__fs_kb_Ioctl()
int __fs_kb_Ioctl (struct Inode * , unsigned long , void *)
Definition at line 238 of file keyboard.c.
 {
     return 0;
 }
DetectPS2Keyboard()
int DetectPS2Keyboard ()
Definition at line 301 of file keyboard.c.
 {
     PS2WriteData(PS2_KBD_CMD_DISABLE_SCANNING);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to disable scanning");
     PS2WriteData(PS2_KBD_CMD_IDENTIFY);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to identify");
     uint8_t recByte;
     int timeout = 1000000;
     while (timeout--)
     {
         recByte = PS2ReadData();
         if (recByte != PS2_ACK)
             break;
     }
     Device1ID[0] = recByte;
     timeout = 1000000;
     while (timeout--)
     {
         recByte = PS2ReadData();
         if (recByte != PS2_ACK)
             break;
     }
     if (timeout == 0)
         KernelLog("PS/2 keyboard second byte timed out");
     else
         Device1ID[1] = recByte;
     KernelLog("PS2 Keyboard Device: 0x%X 0x%X", Device1ID[0], Device1ID[1]);
     return 0;
 }
References Device1ID, KernelLog(), PS2_ACK, PS2_KBD_CMD_DISABLE_SCANNING, PS2_KBD_CMD_IDENTIFY, v0::PS2ACKTimeout(), v0::PS2ReadData(), and v0::PS2WriteData().
Referenced by DriverProbe().
FinalizeKeyboard()
int FinalizeKeyboard ()
Definition at line 291 of file keyboard.c.
 {
     PS2WriteData(PS2_KBD_CMD_DISABLE_SCANNING);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to disable scanning");
     UnregisterDevice(KeyboardDevID);
     return 0;
 }
References KernelLog(), KeyboardDevID, PS2_KBD_CMD_DISABLE_SCANNING, v0::PS2ACKTimeout(), v0::PS2WriteData(), and v0::UnregisterDevice().
Referenced by DriverFinal().
InitializeKeyboard()
int InitializeKeyboard ()
Definition at line 247 of file keyboard.c.
 {
     // PS2WriteData(PS2_KBD_CMD_RESET);
     // uint8_t test = PS2ReadData();
     // if (test != PS2_KBD_RESP_TEST_PASSED &&
     //  test != PS2_KBD_RESP_ACK)
     // {
     //  KernelLog("PS/2 keyboard reset failed (%#x)", test);
     //  return -EFAULT;
     // }
     PS2WriteData(PS2_KBD_CMD_DEFAULTS);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set defaults");
     PS2WriteData(PS2_KBD_CMD_SCAN_CODE_SET);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set scan code set");
     /* We want Scan Code Set 1 */
     PS2WriteData(PS2_KBD_SCAN_CODE_SET_2); /* It will set to 1 but with translation? */
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set scan code set 2");
     PS2WriteData(PS2_KBD_CMD_SCAN_CODE_SET);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to set scan code set");
     PS2WriteData(PS2_KBD_SCAN_CODE_GET_CURRENT);
     if (PS2ACKTimeout() != 0)
         KernelLog("PS/2 keyboard failed to get current scan code set");
     KeyboardScanCodeSet = PS2ReadAfterACK();
     KernelLog("PS/2 Keyboard Scan Code Set: 0x%X", KeyboardScanCodeSet);
     PS2ClearOutputBuffer();
     PS2WriteData(PS2_KBD_CMD_ENABLE_SCANNING);
     RegisterInterruptHandler(1, PS2KbdInterruptHandler);
     KeyboardDevID = RegisterDevice(INPUT_TYPE_KEYBOARD, &KbdOps);
     return 0;
 }
References INPUT_TYPE_KEYBOARD, KbdOps, KernelLog(), KeyboardDevID, KeyboardScanCodeSet, PS2_KBD_CMD_DEFAULTS, PS2_KBD_CMD_ENABLE_SCANNING, PS2_KBD_CMD_SCAN_CODE_SET, PS2_KBD_SCAN_CODE_GET_CURRENT, PS2_KBD_SCAN_CODE_SET_2, v0::PS2ACKTimeout(), v0::PS2ClearOutputBuffer(), PS2KbdInterruptHandler(), v0::PS2ReadAfterACK(), v0::PS2WriteData(), v0::RegisterDevice(), and RegisterInterruptHandler().
Referenced by DriverEntry().
PS2KbdInterruptHandler()
void PS2KbdInterruptHandler (TrapFrame *)
Definition at line 178 of file keyboard.c.
 {
     uint8_t sc = inb(PS2_DATA);
     if (sc == PS2_KBD_RESP_ACK ||
         sc == PS2_KBD_RESP_ECHO ||
         sc == PS2_KBD_RESP_RESEND)
         return;
     if (sc == 0xE0)
     {
         IsE0 = true;
         return;
     }
     if (sc == 0xE1)
     {
         IsE1 = true;
         return;
     }
     switch (KeyboardScanCodeSet)
     {
     case PS2_KBD_SC_SET_1:
     case PS2_KBD_SC_SET_2:
     {
         if (IsE0)
         {
             IsE0 = false;
             ReportKeyboardEvent(KeyboardDevID, ScanCodeSet1mm[sc], sc < 0x90);
             return;
         }
         else
         {
             bool released = sc & 0x80;
             uint8_t scFinal = released ? sc & 0x7F : sc;
             ReportKeyboardEvent(KeyboardDevID, ScanCodeSet1[scFinal], !released);
             return;
         }
     }
     /* FIXME: https://wiki.osdev.org/PS/2_Keyboard */
     // case PS2_KBD_SC_SET_2:
     // {
     //  break;
     // }
     case PS2_KBD_SC_SET_3:
     {
         ReportKeyboardEvent(KeyboardDevID, ScanCodeSet3[sc], true);
         ReportKeyboardEvent(KeyboardDevID, ScanCodeSet3[sc], false);
         break;
     }
     default:
     {
         if (IsE0)
             IsE0 = false;
         KernelLog("Unknown PS/2 Keyboard Scan Code Set: %#x", KeyboardScanCodeSet);
         break;
     }
     }
 }
References inb(), IsE0, IsE1, KernelLog(), KeyboardDevID, KeyboardScanCodeSet, PS2_DATA, PS2_KBD_RESP_ACK, PS2_KBD_RESP_ECHO, PS2_KBD_RESP_RESEND, PS2_KBD_SC_SET_1, PS2_KBD_SC_SET_2, PS2_KBD_SC_SET_3, ReportKeyboardEvent(), ScanCodeSet1, ScanCodeSet1mm, and ScanCodeSet3.
Referenced by InitializeKeyboard().
ReportKeyboardEvent()
int ReportKeyboardEvent (dev_t Device, KeyScanCodes ScanCode, uint8_t Pressed)
Definition at line 166 of file keyboard.c.
 {
     kir.Type = INPUT_TYPE_KEYBOARD;
     kir.Device = Device;
     kir.Keyboard.Key = ScanCode;
     kir.Keyboard.Key |= Pressed ? KEY_PRESSED : 0;
     ReportInputEvent(&kir);
     return 0;
 }
References InputReport::Device, INPUT_TYPE_KEYBOARD, KEY_PRESSED, kir, v0::ReportInputEvent(), and InputReport::Type.
Referenced by PS2KbdInterruptHandler().
Variable Documentation
IsE0
bool IsE0 = false
Definition at line 176 of file keyboard.c.
Referenced by PS2KbdInterruptHandler().
IsE1
bool IsE1 = false
Definition at line 177 of file keyboard.c.
Referenced by PS2KbdInterruptHandler().
KbdOps
const struct InodeOperations KbdOps
Initial value:
= {
    .Ioctl = __fs_kb_Ioctl,
}
Definition at line 238 of file keyboard.c.
Referenced by InitializeKeyboard().
KeyboardDevID
dev_t KeyboardDevID = -1
Definition at line 28 of file keyboard.c.
Referenced by FinalizeKeyboard(), InitializeKeyboard(), and PS2KbdInterruptHandler().
KeyboardScanCodeSet
uint8_t KeyboardScanCodeSet = 0
Definition at line 27 of file keyboard.c.
Referenced by InitializeKeyboard(), and PS2KbdInterruptHandler().
kir
InputReport kir = {0}
Definition at line 165 of file keyboard.c.
Referenced by ReportKeyboardEvent().
ScanCodeSet1
const unsigned short ScanCodeSet1[]
Initial value:
=
    {KEY_NULL, KEY_ESCAPE,
     KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
     KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_TAB,
     KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
     KEY_LEFT_BRACKET, KEY_RIGHT_BRACKET, KEY_RETURN, KEY_LEFT_CTRL,
     KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
     KEY_SEMICOLON, KEY_APOSTROPHE, KEY_BACK_TICK, KEY_LEFT_SHIFT, KEY_BACKSLASH,
     KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M,
     KEY_COMMA, KEY_PERIOD, KEY_SLASH, KEY_RIGHT_SHIFT,
     KEYPAD_ASTERISK, KEY_LEFT_ALT, KEY_SPACE, KEY_CAPS_LOCK,
     KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
     KEY_NUM_LOCK, KEY_SCROLL_LOCK,
     KEYPAD_7, KEYPAD_8, KEYPAD_9, KEYPAD_MINUS,
     KEYPAD_4, KEYPAD_5, KEYPAD_6, KEYPAD_PLUS,
     KEYPAD_1, KEYPAD_2, KEYPAD_3, KEYPAD_0, KEYPAD_PERIOD,
     KEY_NULL, KEY_NULL, KEY_NULL,
     KEY_F11, KEY_F12}
Definition at line 30 of file keyboard.c.
Referenced by PS2KbdInterruptHandler().
ScanCodeSet1mm
const unsigned short ScanCodeSet1mm[]
Definition at line 49 of file keyboard.c.
Referenced by PS2KbdInterruptHandler().
ScanCodeSet3
const unsigned short ScanCodeSet3[]
Initial value:
= {
    [0x15] = KEY_Q,
    [0x1A] = KEY_Z,
    [0x1B] = KEY_S,
    [0x1C] = KEY_A,
    [0x1D] = KEY_W,
    [0x21] = KEY_C,
    [0x22] = KEY_X,
    [0x23] = KEY_D,
    [0x24] = KEY_E,
    [0x2A] = KEY_V,
    [0x2B] = KEY_F,
    [0x2C] = KEY_T,
    [0x2D] = KEY_R,
    [0x31] = KEY_N,
    [0x32] = KEY_B,
    [0x33] = KEY_H,
    [0x34] = KEY_G,
    [0x35] = KEY_Y,
    [0x3A] = KEY_M,
    [0x3B] = KEY_J,
    [0x3C] = KEY_U,
    [0x42] = KEY_K,
    [0x43] = KEY_I,
    [0x44] = KEY_O,
    [0x4B] = KEY_L,
    [0x4D] = KEY_P}
Definition at line 134 of file keyboard.c.
Referenced by PS2KbdInterruptHandler().