Fennix Userspace: Userspace/musl/src/env/clearenv.c File Reference
clearenv.c File Reference
#include <stdlib.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE
Functions
static void dummy (char *old, char *new)
weak_alias (dummy, __env_rm_add)
int clearenv ()
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file clearenv.c.
Function Documentation
clearenv()
int clearenv ()
Definition at line 8 of file clearenv.c.
 {
     char **e = __environ;
     __environ = 0;
     if (e) while (*e) __env_rm_add(*e++, 0);
     return 0;
 }
References __env_rm_add(), and __environ.
Referenced by env_main(), httpd_main(), setup_environment(), and tryexec().
dummy()
static void dummy (char * old, char * new) static
Definition at line 5 of file clearenv.c.
 {}
weak_alias()
weak_alias (dummy , __env_rm_add)