Fennix: Userspace/apps/base/bash/lib/sh/casemod.c File Reference
casemod.c File Reference
#include <stdc.h>
#include <bashansi.h>
#include <bashintl.h>
#include <bashtypes.h>
#include <stdio.h>
#include <ctype.h>
#include <xmalloc.h>
#include <shmbchar.h>
#include <shmbutil.h>
#include <chartypes.h>
#include <typemax.h>
#include <glob/strmatch.h>
Macros
#define _to_wupper(wc) (iswlower (wc) ? towupper (wc) : (wc))
#define _to_wlower(wc) (iswupper (wc) ? towlower (wc) : (wc))
#define cval(s, i, l) ((s)[(i)])
#define iswalnum(c) (isalnum(c))
#define TOGGLE(x) (ISUPPER (x) ? tolower ((unsigned char)x) : (TOUPPER (x)))
#define CASE_NOOP 0x0000
#define CASE_LOWER 0x0001
#define CASE_UPPER 0x0002
#define CASE_CAPITALIZE 0x0004
#define CASE_UNCAP 0x0008
#define CASE_TOGGLE 0x0010
#define CASE_TOGGLEALL 0x0020
#define CASE_UPFIRST 0x0040
#define CASE_LOWFIRST 0x0080
#define CASE_USEWORDS 0x1000 /* modify behavior to act on words in passed string */
#define UCHAR_MAX TYPE_MAXIMUM(unsigned char)
Functions
char *substring PARAMS ((char *, int, int))
char * sh_modcase (char *string, char *pat, int flags) const
Macro Definition Documentation
_to_wlower
#define _to_wlower (wc) (iswupper (wc) ? towlower (wc) : (wc))
Definition at line 47 of file casemod.c.
_to_wupper
#define _to_wupper (wc) (iswlower (wc) ? towupper (wc) : (wc))
Definition at line 46 of file casemod.c.
CASE_CAPITALIZE
#define CASE_CAPITALIZE 0x0004
Definition at line 61 of file casemod.c.
CASE_LOWER
#define CASE_LOWER 0x0001
Definition at line 59 of file casemod.c.
CASE_LOWFIRST
#define CASE_LOWFIRST 0x0080
Definition at line 66 of file casemod.c.
CASE_NOOP
#define CASE_NOOP 0x0000
Definition at line 58 of file casemod.c.
CASE_TOGGLE
#define CASE_TOGGLE 0x0010
Definition at line 63 of file casemod.c.
CASE_TOGGLEALL
#define CASE_TOGGLEALL 0x0020
Definition at line 64 of file casemod.c.
CASE_UNCAP
#define CASE_UNCAP 0x0008
Definition at line 62 of file casemod.c.
CASE_UPFIRST
#define CASE_UPFIRST 0x0040
Definition at line 65 of file casemod.c.
CASE_UPPER
#define CASE_UPPER 0x0002
Definition at line 60 of file casemod.c.
CASE_USEWORDS
#define CASE_USEWORDS 0x1000 /* modify behavior to act on words in passed string */
Definition at line 68 of file casemod.c.
cval
#define cval (s, i, l) ((s)[(i)])
Definition at line 50 of file casemod.c.
iswalnum
#define iswalnum (c) (isalnum(c))
Definition at line 51 of file casemod.c.
TOGGLE
#define TOGGLE (x) (ISUPPER (x) ? tolower ((unsigned char)x) : (TOUPPER (x)))
Definition at line 52 of file casemod.c.
UCHAR_MAX
#define UCHAR_MAX TYPE_MAXIMUM(unsigned char)
Definition at line 73 of file casemod.c.
Function Documentation
PARAMS()
char* substring PARAMS ((char *, int, int))
sh_modcase()
char* sh_modcase (char * string, char * pat, int flags) const
Definition at line 101 of file casemod.c.
 {
   int start, next, end, retind;
   int inword, c, nc, nop, match, usewords;
   char *ret, *s;
   wchar_t wc;
   int mb_cur_max;
 #if defined (HANDLE_MULTIBYTE)
   wchar_t nwc;
   char mb[MB_LEN_MAX+1];
   int mlen;
   size_t m;
   mbstate_t state;
 #endif
   if (string == 0 || *string == 0)
     {
       ret = (char *)xmalloc (1);
       ret[0] = '\0';
       return ret;
     }
 #if defined (HANDLE_MULTIBYTE)
   memset (&state, 0, sizeof (mbstate_t));
 #endif
   start = 0;
   end = strlen (string);
   mb_cur_max = MB_CUR_MAX;
   ret = (char *)xmalloc (2*end + 1);
   retind = 0;
   /* See if we are supposed to split on alphanumerics and operate on each word */
   usewords = (flags & CASE_USEWORDS);
   flags &= ~CASE_USEWORDS;
   inword = 0;
   while (start < end)
     {
       wc = cval ((char *)string, start, end);
       if (iswalnum (wc) == 0)
     inword = 0;
       if (pat)
     {
       next = start;
       ADVANCE_CHAR (string, end, next);
       s = substring ((char *)string, start, next);
       match = strmatch (pat, s, FNM_EXTMATCH) != FNM_NOMATCH;
       free (s);
       if (match == 0)
             {
               /* copy unmatched portion */
               memcpy (ret + retind, string + start, next - start);
               retind += next - start;
               start = next;
               inword = 1;
               continue;
             }
     }
       /* XXX - for now, the toggling operators work on the individual
      words in the string, breaking on alphanumerics.  Should I
      leave the capitalization operators to do that also? */
       if (flags == CASE_CAPITALIZE)
     {
       if (usewords)
         nop = inword ? CASE_LOWER : CASE_UPPER;
       else
         nop = (start > 0) ? CASE_LOWER : CASE_UPPER;
       inword = 1;
     }
       else if (flags == CASE_UNCAP)
     {
       if (usewords)
         nop = inword ? CASE_UPPER : CASE_LOWER;
       else
         nop = (start > 0) ? CASE_UPPER : CASE_LOWER;
       inword = 1;
     }
       else if (flags == CASE_UPFIRST)
     {
       if (usewords)
         nop = inword ? CASE_NOOP : CASE_UPPER;
       else
         nop = (start > 0) ? CASE_NOOP : CASE_UPPER;
       inword = 1;
     }
       else if (flags == CASE_LOWFIRST)
     {
       if (usewords)
         nop = inword ? CASE_NOOP : CASE_LOWER;
       else
         nop = (start > 0) ? CASE_NOOP : CASE_LOWER;
       inword = 1;
     }
       else if (flags == CASE_TOGGLE)
     {
       nop = inword ? CASE_NOOP : CASE_TOGGLE;
       inword = 1;
     }
       else
     nop = flags;
       /* Can't short-circuit, some locales have multibyte upper and lower
      case equivalents of single-byte ascii characters (e.g., Turkish) */
       if (mb_cur_max == 1)
     {
 singlebyte:
       switch (nop)
         {
         default:
         case CASE_NOOP:  nc = wc; break;
         case CASE_UPPER:  nc = TOUPPER (wc); break;
         case CASE_LOWER:  nc = TOLOWER (wc); break;
         case CASE_TOGGLEALL:
         case CASE_TOGGLE: nc = TOGGLE (wc); break;
         }
       ret[retind++] = nc;
     }
 #if defined (HANDLE_MULTIBYTE)
       else
     {
       m = mbrtowc (&wc, string + start, end - start, &state);
       /* Have to go through wide case conversion even for single-byte
          chars, to accommodate single-byte characters where the
          corresponding upper or lower case equivalent is multibyte. */
       if (MB_INVALIDCH (m))
         {
           wc = (unsigned char)string[start];
           goto singlebyte;
         }
       else if (MB_NULLWCH (m))
         wc = L'\0';
       switch (nop)
         {
         default:
         case CASE_NOOP:  nwc = wc; break;
         case CASE_UPPER:  nwc = _to_wupper (wc); break;
         case CASE_LOWER:  nwc = _to_wlower (wc); break;
         case CASE_TOGGLEALL:
         case CASE_TOGGLE: nwc = TOGGLE (wc); break;
         }
       /* We don't have to convert `wide' characters that are in the
          unsigned char range back to single-byte `multibyte' characters. */
       if ((int)nwc <= UCHAR_MAX && is_basic ((int)nwc))
         ret[retind++] = nwc;
       else
         {
           mlen = wcrtomb (mb, nwc, &state);
           if (mlen > 0)
         mb[mlen] = '\0';
           /* Don't assume the same width */
           strncpy (ret + retind, mb, mlen);
           retind += mlen;
         }
     }
 #endif
       ADVANCE_CHAR (string, end, start);
     }
   ret[retind] = '\0';
   return ret;
 }
References _to_wlower, _to_wupper, ADVANCE_CHAR, c, CASE_CAPITALIZE, CASE_LOWER, CASE_LOWFIRST, CASE_NOOP, CASE_TOGGLE, CASE_TOGGLEALL, CASE_UNCAP, CASE_UPFIRST, CASE_UPPER, CASE_USEWORDS, cval, end, flags, FNM_EXTMATCH, FNM_NOMATCH, free, iswalnum, L, match(), MB_CUR_MAX, MB_INVALIDCH, MB_LEN_MAX, MB_NULLWCH, mbrtowc(), memcpy, memset, next, pat, s, start, state, strlen, strmatch(), strncpy(), substring(), TOGGLE, TOLOWER, TOUPPER, UCHAR_MAX, wcrtomb(), and xmalloc.
Referenced by make_variable_value(), parameter_brace_casemod(), pos_params_modcase(), and string_transform().