Fennix: Userspace/apps/base/bash/nojobs.c File Reference
nojobs.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "filecntl.h"
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include "shtty.h"
#include "bashintl.h"
#include "shell.h"
#include "jobs.h"
#include "execute_cmd.h"
#include "trap.h"
#include "builtins/builtext.h"
#include "builtins/common.h"
Data Structures
struct proc_status
Macros
#define DEFAULT_CHILD_MAX 4096
#define killpg(pg, sig) kill(-(pg),(sig))
#define siginterrupt(sig, code)
#define WAITPID(pid, statusp, options) wait (statusp)
#define input_tty() (shell_tty != -1) ? shell_tty : fileno (stderr)
#define PROC_RUNNING 0x01
#define PROC_NOTIFIED 0x02
#define PROC_ASYNC 0x04
#define PROC_SIGNALED 0x10
#define PROC_BAD -1
#define PROC_STILL_ALIVE -2
#define INVALID_SIGNAL_HANDLER (SigHandler *)wait_for_background_pids
#define REPORTSIG(x) ((x) != SIGINT)
Functions
void set_original_signal PARAMS ((int, SigHandler *))
static void alloc_pid_list PARAMS ((void))
static int find_proc_slot PARAMS ((pid_t))
static int process_exit_status PARAMS ((WAIT))
static void set_pid_status PARAMS ((pid_t, WAIT))
static void set_pid_flags PARAMS ((pid_t, int))
static void alloc_pid_list ()
static int find_proc_slot (pid_t pid)
static int find_index_by_pid (pid_t pid)
static int find_status_by_pid (pid_t pid)
static int process_exit_status (WAIT status)
static int find_termsig_by_pid (pid_t pid)
static int get_termsig (WAIT status)
static void set_pid_status (pid_t pid, WAIT status)
static void set_pid_flags (pid_t pid, int flags)
static void unset_pid_flags (pid_t pid, int flags)
static int get_pid_flags (pid_t pid)
static void add_pid (pid_t pid, int async)
static void mark_dead_jobs_as_notified (int force)
int cleanup_dead_jobs ()
void reap_dead_jobs ()
int initialize_job_control (int force)
void initialize_job_signals ()
pid_t make_child (char *command, int flags)
void ignore_tty_job_signals ()
void default_tty_job_signals ()
void get_original_tty_job_signals ()
int wait_for_single_pid (pid_t pid, int flags)
int wait_for_background_pids (struct procstat *ps)
void wait_sigint_cleanup ()
static void restore_sigint_handler ()
static sighandler wait_sigint_handler (int sig)
static char * j_strsignal (int s)
int wait_for (pid_t pid, int flags)
int kill_pid (pid_t pid, int signal, int group)
int get_tty_state ()
int set_tty_state ()
int give_terminal_to (pid_t pgrp, int force)
int stop_pipeline (int async, COMMAND *ignore)
void start_pipeline ()
void stop_making_children ()
void without_job_control ()
int get_job_by_pid (pid_t pid, int block, PROCESS **ignore)
void describe_pid (pid_t pid)
int freeze_jobs_list ()
void unfreeze_jobs_list ()
void set_jobs_list_frozen (int s)
int count_all_jobs ()
Variables
int errno
volatile pid_t last_made_pid = NO_PID
volatile pid_t last_asynchronous_pid = NO_PID
static int queue_sigchld
int waiting_for_child
int already_making_children = 0
int shell_tty = -1
int check_window_size = CHECKWINSIZE_DEFAULT
int job_control = 0
int running_in_background = 0
static struct proc_status * pid_list = (struct proc_status *)NULL
static int pid_list_size
static int wait_sigint_received
static long child_max = -1L
static SigHandler * old_sigint_handler = INVALID_SIGNAL_HANDLER
static TTYSTRUCT shell_tty_info
static int got_tty_state
Data Structure Documentation
proc_status
struct proc_status
Definition at line 102 of file nojobs.c.
Data Fields
int flags
pid_t pid
int status
Macro Definition Documentation
DEFAULT_CHILD_MAX
#define DEFAULT_CHILD_MAX 4096
Definition at line 54 of file nojobs.c.
input_tty
#define input_tty () (shell_tty != -1) ? shell_tty : fileno (stderr)
Definition at line 71 of file nojobs.c.
INVALID_SIGNAL_HANDLER
#define INVALID_SIGNAL_HANDLER (SigHandler *)wait_for_background_pids
Definition at line 765 of file nojobs.c.
killpg
#define killpg (pg, sig) kill(-(pg),(sig))
Definition at line 57 of file nojobs.c.
PROC_ASYNC
#define PROC_ASYNC 0x04
Definition at line 111 of file nojobs.c.
PROC_BAD
#define PROC_BAD -1
Definition at line 115 of file nojobs.c.
PROC_NOTIFIED
#define PROC_NOTIFIED 0x02
Definition at line 110 of file nojobs.c.
PROC_RUNNING
#define PROC_RUNNING 0x01
Definition at line 109 of file nojobs.c.
PROC_SIGNALED
#define PROC_SIGNALED 0x10
Definition at line 112 of file nojobs.c.
PROC_STILL_ALIVE
#define PROC_STILL_ALIVE -2
Definition at line 116 of file nojobs.c.
REPORTSIG
#define REPORTSIG (x) ((x) != SIGINT)
siginterrupt
#define siginterrupt (sig, code)
Definition at line 61 of file nojobs.c.
WAITPID
#define WAITPID (pid, statusp, options) wait (statusp)
Definition at line 67 of file nojobs.c.
Function Documentation
add_pid()
static void add_pid (pid_t pid, int async) static
Definition at line 334 of file nojobs.c.
 {
   int slot;
   slot = find_proc_slot (pid);
   pid_list[slot].pid = pid;
   pid_list[slot].status = -1;
   pid_list[slot].flags = PROC_RUNNING;
   if (async)
     pid_list[slot].flags |= PROC_ASYNC;
 }
References find_proc_slot(), proc_status::flags, proc_status::pid, pid_list, PROC_ASYNC, PROC_RUNNING, slot, and proc_status::status.
Referenced by make_child().
alloc_pid_list()
static void alloc_pid_list () static
Definition at line 153 of file nojobs.c.
 {
   register int i;
   int old = pid_list_size;
   pid_list_size += 10;
   pid_list = (struct proc_status *)xrealloc (pid_list, pid_list_size * sizeof (struct proc_status));
   /* None of the newly allocated slots have process id's yet. */
   for (i = old; i < pid_list_size; i++)
     {
       pid_list[i].pid = NO_PID;
       pid_list[i].status = pid_list[i].flags = 0;
     }
 }
References proc_status::flags, i, NO_PID, proc_status::pid, pid_list, pid_list_size, proc_status::status, and xrealloc.
Referenced by find_proc_slot().
cleanup_dead_jobs()
int cleanup_dead_jobs ()
Definition at line 391 of file nojobs.c.
 {
   register int i;
 #if defined (HAVE_WAITPID)
   reap_zombie_children ();
 #endif
   for (i = 0; i < pid_list_size; i++)
     {
       if (pid_list[i].pid != NO_PID &&
         (pid_list[i].flags & PROC_RUNNING) == 0 &&
         (pid_list[i].flags & PROC_NOTIFIED))
     pid_list[i].pid = NO_PID;
     }
 #if defined (COPROCESS_SUPPORT)
   coproc_reap ();
 #endif
   return 0;
 }
References flags, i, NO_PID, proc_status::pid, pid_list, pid_list_size, PROC_NOTIFIED, and PROC_RUNNING.
Referenced by reap_dead_jobs(), shell_getc(), and wait_for_background_pids().
count_all_jobs()
int count_all_jobs ()
Definition at line 1074 of file nojobs.c.
 {
   return 0;
 }
default_tty_job_signals()
void default_tty_job_signals ()
Definition at line 607 of file nojobs.c.
 {
 #if defined (SIGTSTP)
   if (signal_is_trapped (SIGTSTP) == 0 && signal_is_hard_ignored (SIGTSTP))
     set_signal_handler (SIGTSTP, SIG_IGN);
   else
     set_signal_handler (SIGTSTP, SIG_DFL);
   if (signal_is_trapped (SIGTTIN) == 0 && signal_is_hard_ignored (SIGTTIN))
     set_signal_handler (SIGTTIN, SIG_IGN);
   else
     set_signal_handler (SIGTTIN, SIG_DFL);
   if (signal_is_trapped (SIGTTOU) == 0 && signal_is_hard_ignored (SIGTTOU))
     set_signal_handler (SIGTTOU, SIG_IGN);
   else
     set_signal_handler (SIGTTOU, SIG_DFL);
 #endif
 }
References set_signal_handler, SIG_DFL, SIG_IGN, signal_is_hard_ignored(), signal_is_trapped(), SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by make_child().
describe_pid()
void describe_pid (pid_t pid)
Definition at line 1050 of file nojobs.c.
 {
   fprintf (stderr, "%ld\n", (long) pid);
 }
References fprintf(), procstat::pid, and stderr.
find_index_by_pid()
static int find_index_by_pid (pid_t pid) static
Definition at line 190 of file nojobs.c.
 {
   register int i;
   for (i = 0; i < pid_list_size; i++)
     if (pid_list[i].pid == pid)
       return (i);
   return (NO_PID);
 }
References i, NO_PID, proc_status::pid, pid_list, and pid_list_size.
Referenced by find_status_by_pid(), find_termsig_by_pid(), get_job_by_pid(), get_pid_flags(), set_pid_flags(), set_pid_status(), and unset_pid_flags().
find_proc_slot()
static int find_proc_slot (pid_t pid) static
Definition at line 172 of file nojobs.c.
 {
   register int i;
   for (i = 0; i < pid_list_size; i++)
     if (pid_list[i].pid == NO_PID || pid_list[i].pid == pid)
       return (i);
   if (i == pid_list_size)
     alloc_pid_list ();
   return (i);
 }
References alloc_pid_list(), i, NO_PID, proc_status::pid, pid_list, and pid_list_size.
Referenced by add_pid().
find_status_by_pid()
static int find_status_by_pid (pid_t pid) static
Definition at line 205 of file nojobs.c.
 {
   int i;
   i = find_index_by_pid (pid);
   if (i == NO_PID)
     return (PROC_BAD);
   if (pid_list[i].flags & PROC_RUNNING)
     return (PROC_STILL_ALIVE);
   return (pid_list[i].status);
 }
References find_index_by_pid(), flags, i, NO_PID, proc_status::pid, pid_list, PROC_BAD, PROC_RUNNING, PROC_STILL_ALIVE, and mlibc::status.
Referenced by wait_for(), and wait_for_single_pid().
find_termsig_by_pid()
static int find_termsig_by_pid (pid_t pid) static
Definition at line 231 of file nojobs.c.
 {
   int i;
   i = find_index_by_pid (pid);
   if (i == NO_PID)
     return (0);
   if (pid_list[i].flags & PROC_RUNNING)
     return (0);
   return (get_termsig ((WAIT)pid_list[i].status));
 }
References find_index_by_pid(), flags, get_termsig(), i, NO_PID, proc_status::pid, pid_list, PROC_RUNNING, and mlibc::status.
Referenced by wait_for(), and wait_for_single_pid().
freeze_jobs_list()
int freeze_jobs_list ()
Definition at line 1057 of file nojobs.c.
 {
   return 0;
 }
get_job_by_pid()
int get_job_by_pid (pid_t pid, int block, PROCESS ** ignore)
Definition at line 1037 of file nojobs.c.
 {
   int i;
   i = find_index_by_pid (pid);
   return ((i == NO_PID) ? PROC_BAD : i);
 }
References find_index_by_pid(), i, NO_PID, procstat::pid, and PROC_BAD.
get_original_tty_job_signals()
void get_original_tty_job_signals ()
Definition at line 627 of file nojobs.c.
 {
   static int fetched = 0;
   if (fetched == 0)
     {
 #if defined (SIGTSTP)
       if (interactive_shell)
     {
       set_original_signal (SIGTSTP, SIG_DFL);
       set_original_signal (SIGTTIN, SIG_DFL);
       set_original_signal (SIGTTOU, SIG_DFL);
     }
       else
     {
       get_original_signal (SIGTSTP);
       get_original_signal (SIGTTIN);
       get_original_signal (SIGTTOU);
     }
 #endif
       fetched = 1;
     }
 }
References get_original_signal(), interactive_shell, set_original_signal(), SIG_DFL, SIGTSTP, SIGTTIN, and SIGTTOU.
get_pid_flags()
static int get_pid_flags (pid_t pid) static
Definition at line 321 of file nojobs.c.
 {
   int slot;
   slot = find_index_by_pid (pid);
   if (slot == NO_PID)
     return 0;
   return (pid_list[slot].flags);
 }
References find_index_by_pid(), flags, NO_PID, proc_status::pid, pid_list, and slot.
get_termsig()
static int get_termsig (WAIT status) static
Definition at line 248 of file nojobs.c.
 {
   if (WIFSTOPPED (status) == 0 && WIFSIGNALED (status))
     return (WTERMSIG (status));
   else
     return (0);
 }
References mlibc::status, WIFSIGNALED, WIFSTOPPED, and WTERMSIG.
Referenced by find_termsig_by_pid(), and wait_for().
get_tty_state()
int get_tty_state ()
Definition at line 966 of file nojobs.c.
 {
   int tty;
   tty = input_tty ();
   if (tty != -1)
     {
       ttgetattr (tty, &shell_tty_info);
       got_tty_state = 1;
       if (check_window_size)
     get_new_window_size (0, (int *)0, (int *)0);
     }
   return 0;
 }
References check_window_size, get_new_window_size(), got_tty_state, input_tty, shell_tty_info, and ttgetattr().
Referenced by initialize_job_control(), and wait_for().
give_terminal_to()
int give_terminal_to (pid_t pgrp, int force)
Definition at line 999 of file nojobs.c.
 {
   return 0;
 }
ignore_tty_job_signals()
void ignore_tty_job_signals ()
Definition at line 597 of file nojobs.c.
 {
 #if defined (SIGTSTP)
   set_signal_handler (SIGTSTP, SIG_IGN);
   set_signal_handler (SIGTTIN, SIG_IGN);
   set_signal_handler (SIGTTOU, SIG_IGN);
 #endif
 }
References set_signal_handler, SIG_IGN, SIGTSTP, SIGTTIN, and SIGTTOU.
Referenced by initialize_job_signals().
initialize_job_control()
int initialize_job_control (int force)
Definition at line 423 of file nojobs.c.
 {
   shell_tty = fileno (stderr);
   if (interactive)
     get_tty_state ();
   return 0;
 }
References fileno(), get_tty_state(), interactive, shell_tty, and stderr.
initialize_job_signals()
void initialize_job_signals ()
Definition at line 435 of file nojobs.c.
 {
   set_signal_handler (SIGINT, sigint_sighandler);
   /* If this is a login shell we don't wish to be disturbed by
      stop signals. */
   if (login_shell)
     ignore_tty_job_signals ();
 }
References ignore_tty_job_signals(), login_shell, set_signal_handler, SIGINT, and sigint_sighandler().
j_strsignal()
static char* j_strsignal (int s) static
Definition at line 806 of file nojobs.c.
 {
   static char retcode_name_buffer[64] = { '\0' };
   char *x;
   x = strsignal (s);
   if (x == 0)
     {
       x = retcode_name_buffer;
       sprintf (x, "Signal %d", s);
     }
   return x;
 }
References retcode_name_buffer, sprintf(), strsignal, and x.
Referenced by wait_for().
kill_pid()
int kill_pid (pid_t pid, int signal, int group)
Definition at line 946 of file nojobs.c.
 {
   int result;
   if (pid < -1)
     {
       pid = -pid;
       group = 1;
     }
   result = group ? killpg (pid, signal) : kill (pid, signal);
   return (result);
 }
References kill(), killpg, procstat::pid, and signal.
make_child()
pid_t make_child (char * command, int flags)
Definition at line 493 of file nojobs.c.
 {
   pid_t pid;
   int async_p, forksleep;
   sigset_t set, oset;
   /* Discard saved memory. */
   if (command)
     free (command);
   async_p = (flags & FORK_ASYNC);
   start_pipeline ();
 #if defined (BUFFERED_INPUT)
   /* If default_buffered_input is active, we are reading a script.  If
      the command is asynchronous, we have already duplicated /dev/null
      as fd 0, but have not changed the buffered stream corresponding to
      the old fd 0.  We don't want to sync the stream in this case. */
   if (default_buffered_input != -1 && (!async_p || default_buffered_input > 0))
     sync_buffered_stream (default_buffered_input);
 #endif /* BUFFERED_INPUT */
   /* Block SIGTERM here and unblock in child after fork resets the
      set of pending signals */
   if (interactive_shell)
     {
       sigemptyset (&set);
       sigaddset (&set, SIGTERM);
       sigemptyset (&oset);
       sigprocmask (SIG_BLOCK, &set, &oset);
       set_signal_handler (SIGTERM, SIG_DFL);
     }
   /* Create the child, handle severe errors.  Retry on EAGAIN. */
   forksleep = 1;
   while ((pid = fork ()) < 0 && errno == EAGAIN && forksleep < FORKSLEEP_MAX)
     {
       sys_error ("fork: retry");
 #if defined (HAVE_WAITPID)
       /* Posix systems with a non-blocking waitpid () system call available
      get another chance after zombies are reaped. */
       reap_zombie_children ();
       if (forksleep > 1 && sleep (forksleep) != 0)
         break;
 #else
       if (sleep (forksleep) != 0)
     break;
 #endif /* HAVE_WAITPID */
       forksleep <<= 1;
     }
   if (pid != 0)
     if (interactive_shell)
       {
     set_signal_handler (SIGTERM, SIG_IGN);
     sigprocmask (SIG_SETMASK, &oset, (sigset_t *)NULL);
       }
   if (pid < 0)
     {
       sys_error ("fork");
       last_command_exit_value = EX_NOEXEC;
       throw_to_top_level ();
     }
   if (pid == 0)
     {
 #if defined (BUFFERED_INPUT)
       unset_bash_input (0);
 #endif /* BUFFERED_INPUT */
       CLRINTERRUPT; /* XXX - children have their own interrupt state */
       /* Restore top-level signal mask. */
       restore_sigmask ();
 #if 0
       /* Ignore INT and QUIT in asynchronous children. */
       if (async_p)
     last_asynchronous_pid = getpid ();
 #endif
       subshell_environment |= SUBSHELL_IGNTRAP;
       default_tty_job_signals ();
     }
   else
     {
       /* In the parent. */
       last_made_pid = pid;
       if (async_p)
     last_asynchronous_pid = pid;
       add_pid (pid, async_p);
     }
   return (pid);
 }
References add_pid(), CLRINTERRUPT, default_tty_job_signals(), EAGAIN, errno, EX_NOEXEC, flags, fork(), FORK_ASYNC, FORKSLEEP_MAX, free, getpid(), interactive_shell, last_asynchronous_pid, last_command_exit_value, last_made_pid, NULL, restore_sigmask(), set_signal_handler, SIG_BLOCK, SIG_DFL, SIG_IGN, SIG_SETMASK, sigaddset, sigemptyset, sigprocmask(), SIGTERM, sleep(), start_pipeline(), subshell_environment, SUBSHELL_IGNTRAP, sys_error(), throw_to_top_level(), and unset_bash_input().
mark_dead_jobs_as_notified()
static void mark_dead_jobs_as_notified (int force) static
Definition at line 350 of file nojobs.c.
 {
   register int i, ndead;
   /* first, count the number of non-running async jobs if FORCE == 0 */
   for (i = ndead = 0; force == 0 && i < pid_list_size; i++)
     {
       if (pid_list[i].pid == NO_PID)
     continue;
       if (((pid_list[i].flags & PROC_RUNNING) == 0) &&
        (pid_list[i].flags & PROC_ASYNC))
     ndead++;
     }
   if (child_max < 0)
     child_max = getmaxchild ();
   if (child_max < 0)
     child_max = DEFAULT_CHILD_MAX;
   if (force == 0 && ndead <= child_max)
     return;
   /* If FORCE == 0, we just mark as many non-running async jobs as notified
      to bring us under the CHILD_MAX limit. */
   for (i = 0; i < pid_list_size; i++)
     {
       if (pid_list[i].pid == NO_PID)
     continue;
       if (((pid_list[i].flags & PROC_RUNNING) == 0) &&
        pid_list[i].pid != last_asynchronous_pid)
     {
       pid_list[i].flags |= PROC_NOTIFIED;
       if (force == 0 && (pid_list[i].flags & PROC_ASYNC) && --ndead <= child_max)
         break;
     }
     }
 }
References child_max, DEFAULT_CHILD_MAX, flags, proc_status::flags, force, getmaxchild(), i, last_asynchronous_pid, NO_PID, proc_status::pid, pid_list, pid_list_size, PROC_ASYNC, PROC_NOTIFIED, and PROC_RUNNING.
Referenced by reap_dead_jobs(), and wait_for_background_pids().
PARAMS() [1/6]
void set_original_signal PARAMS ((int, SigHandler *))
PARAMS() [2/6]
static int find_proc_slot PARAMS ((pid_t)) static
PARAMS() [3/6]
static void set_pid_flags PARAMS ((pid_t, int)) static
PARAMS() [4/6]
static void set_pid_status PARAMS ((pid_t, WAIT)) static
PARAMS() [5/6]
static void alloc_pid_list PARAMS ((void)) static
PARAMS() [6/6]
static int process_exit_status PARAMS ((WAIT)) static
process_exit_status()
static int process_exit_status (WAIT status) static
Definition at line 219 of file nojobs.c.
 {
   if (WIFSIGNALED (status))
     return (128 + WTERMSIG (status));
   else
     return (WEXITSTATUS (status));
 }
References mlibc::status, WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
Referenced by set_pid_status(), wait_for(), wait_for_background_pids(), and wait_for_single_pid().
reap_dead_jobs()
void reap_dead_jobs ()
Definition at line 415 of file nojobs.c.
 {
   mark_dead_jobs_as_notified (0);
   cleanup_dead_jobs ();
 }
References cleanup_dead_jobs(), and mark_dead_jobs_as_notified().
restore_sigint_handler()
static void restore_sigint_handler () static
Definition at line 769 of file nojobs.c.
 {
   if (old_sigint_handler != INVALID_SIGNAL_HANDLER)
     {
       set_signal_handler (SIGINT, old_sigint_handler);
       old_sigint_handler = INVALID_SIGNAL_HANDLER;
     }
 }
References INVALID_SIGNAL_HANDLER, old_sigint_handler, set_signal_handler, and SIGINT.
Referenced by wait_for(), and wait_sigint_handler().
set_jobs_list_frozen()
void set_jobs_list_frozen (int s)
Definition at line 1068 of file nojobs.c.
 {
 }
set_pid_flags()
static void set_pid_flags (pid_t pid, int flags) static
Definition at line 291 of file nojobs.c.
 {
   int slot;
   slot = find_index_by_pid (pid);
   if (slot == NO_PID)
     return;
   pid_list[slot].flags |= flags;
 }
References find_index_by_pid(), flags, proc_status::flags, NO_PID, proc_status::pid, pid_list, and slot.
Referenced by wait_for_single_pid().
set_pid_status()
static void set_pid_status (pid_t pid, WAIT status) static
Definition at line 259 of file nojobs.c.
 {
   int slot;
 #if defined (COPROCESS_SUPPORT)
   coproc_pidchk (pid, status);
 #endif
 #if defined (PROCESS_SUBSTITUTION)
   if ((slot = find_procsub_child (pid)) >= 0)
     set_procsub_status (slot, pid, WSTATUS (status));
     /* XXX - also saving in list below */
 #endif
   slot = find_index_by_pid (pid);
   if (slot == NO_PID)
     return;
   pid_list[slot].status = process_exit_status (status);
   pid_list[slot].flags &= ~PROC_RUNNING;
   if (WIFSIGNALED (status))
     pid_list[slot].flags |= PROC_SIGNALED;
   /* If it's not a background process, mark it as notified so it gets
      cleaned up. */
   if ((pid_list[slot].flags & PROC_ASYNC) == 0)
     pid_list[slot].flags |= PROC_NOTIFIED;
 }
References find_index_by_pid(), flags, proc_status::flags, NO_PID, proc_status::pid, pid_list, PROC_ASYNC, PROC_NOTIFIED, PROC_RUNNING, PROC_SIGNALED, process_exit_status(), slot, proc_status::status, mlibc::status, WIFSIGNALED, and WSTATUS.
Referenced by wait_for(), wait_for_background_pids(), and wait_for_single_pid().
set_tty_state()
int set_tty_state ()
Definition at line 983 of file nojobs.c.
 {
   int tty;
   tty = input_tty ();
   if (tty != -1)
     {
       if (got_tty_state == 0)
     return 0;
       ttsetattr (tty, &shell_tty_info);
     }
   return 0;
 }
References got_tty_state, input_tty, shell_tty_info, and ttsetattr().
Referenced by wait_for().
start_pipeline()
void start_pipeline ()
Definition at line 1017 of file nojobs.c.
 {
   already_making_children = 1;
 }
References already_making_children.
Referenced by make_child().
stop_making_children()
void stop_making_children ()
Definition at line 1023 of file nojobs.c.
 {
   already_making_children = 0;
 }
References already_making_children.
Referenced by without_job_control().
stop_pipeline()
int stop_pipeline (int async, COMMAND * ignore)
Definition at line 1008 of file nojobs.c.
 {
   already_making_children = 0;
   return 0;
 }
References already_making_children.
unfreeze_jobs_list()
void unfreeze_jobs_list ()
Definition at line 1063 of file nojobs.c.
 {
 }
unset_pid_flags()
static void unset_pid_flags (pid_t pid, int flags) static
Definition at line 306 of file nojobs.c.
 {
   int slot;
   slot = find_index_by_pid (pid);
   if (slot == NO_PID)
     return;
   pid_list[slot].flags &= ~flags;
 }
References find_index_by_pid(), flags, proc_status::flags, NO_PID, proc_status::pid, pid_list, and slot.
wait_for()
int wait_for (pid_t pid, int flags)
Definition at line 824 of file nojobs.c.
 {
   int return_val, pstatus;
   pid_t got_pid;
   WAIT status;
   pstatus = find_status_by_pid (pid);
   if (pstatus == PROC_BAD)
     return (0);
   if (pstatus != PROC_STILL_ALIVE)
     {
       if (pstatus > 128)
     last_command_exit_signal = find_termsig_by_pid (pid);
       return (pstatus);
     }
   /* If we are running a script, ignore SIGINT while we're waiting for
      a child to exit.  The loop below does some of this, but not all. */
   wait_sigint_received = 0;
   if (interactive_shell == 0)
     old_sigint_handler = set_signal_handler (SIGINT, wait_sigint_handler);
   waiting_for_child = 1;
   CHECK_WAIT_INTR;
   while ((got_pid = WAITPID (-1, &status, 0)) != pid) /* XXX was pid now -1 */
     {
       waiting_for_child = 0;
       CHECK_TERMSIG;
       CHECK_WAIT_INTR;
       if (got_pid < 0 && errno == ECHILD)
     {
 #if !defined (_POSIX_VERSION)
       status.w_termsig = status.w_retcode = 0;
 #else
       status = 0;
 #endif /* _POSIX_VERSION */
       break;
     }
       else if (got_pid < 0 && errno != EINTR)
     programming_error ("wait_for(%ld): %s", (long)pid, strerror(errno));
       else if (got_pid > 0)
     set_pid_status (got_pid, status);
       waiting_for_child = 1;
     }
   waiting_for_child = 0;
   if (got_pid > 0)
     set_pid_status (got_pid, status);
 #if defined (HAVE_WAITPID)
   if (got_pid >= 0)
     reap_zombie_children ();
 #endif /* HAVE_WAITPID */
   CHECK_TERMSIG;
   CHECK_WAIT_INTR;
   if (interactive_shell == 0)
     {
       SigHandler *temp_handler;
       temp_handler = old_sigint_handler;
       restore_sigint_handler ();
       /* If the job exited because of SIGINT, make sure the shell acts as if
      it had received one also. */
       if (WIFSIGNALED (status) && (WTERMSIG (status) == SIGINT))
     {
       if (maybe_call_trap_handler (SIGINT) == 0)
         {
           if (temp_handler == SIG_DFL)
         termsig_handler (SIGINT);
           else if (temp_handler != INVALID_SIGNAL_HANDLER && temp_handler != SIG_IGN)
         (*temp_handler) (SIGINT);
         }
     }
     }
   /* Default return value. */
   /* ``a full 8 bits of status is returned'' */
   return_val = process_exit_status (status);
   last_command_exit_signal = get_termsig (status);
 #if defined (DONT_REPORT_SIGPIPE) && defined (DONT_REPORT_SIGTERM)
 #  define REPORTSIG(x) ((x) != SIGINT && (x) != SIGPIPE && (x) != SIGTERM)
 #elif !defined (DONT_REPORT_SIGPIPE) && !defined (DONT_REPORT_SIGTERM)
 #  define REPORTSIG(x) ((x) != SIGINT)
 #elif defined (DONT_REPORT_SIGPIPE)
 #  define REPORTSIG(x) ((x) != SIGINT && (x) != SIGPIPE)
 #else
 #  define REPORTSIG(x) ((x) != SIGINT && (x) != SIGTERM)
 #endif
   if ((WIFSTOPPED (status) == 0) && WIFSIGNALED (status) && REPORTSIG(WTERMSIG (status)))
     {
       fprintf (stderr, "%s", j_strsignal (WTERMSIG (status)));
       if (WIFCORED (status))
     fprintf (stderr, _(" (core dumped)"));
       fprintf (stderr, "\n");
     }
   if (interactive_shell && subshell_environment == 0)
     {
       if (WIFSIGNALED (status) || WIFSTOPPED (status))
     set_tty_state ();
       else
     get_tty_state ();
     }
   else if (interactive_shell == 0 && subshell_environment == 0 && check_window_size)
     get_new_window_size (0, (int *)0, (int *)0);
   return (return_val);
 }
References _, CHECK_TERMSIG, CHECK_WAIT_INTR, check_window_size, ECHILD, EINTR, errno, find_status_by_pid(), find_termsig_by_pid(), fprintf(), get_new_window_size(), get_termsig(), get_tty_state(), interactive_shell, INVALID_SIGNAL_HANDLER, j_strsignal(), last_command_exit_signal, maybe_call_trap_handler(), old_sigint_handler, procstat::pid, PROC_BAD, PROC_STILL_ALIVE, process_exit_status(), programming_error(), REPORTSIG, restore_sigint_handler(), set_pid_status(), set_signal_handler, set_tty_state(), SIG_DFL, SIG_IGN, SIGINT, mlibc::status, stderr, strerror(), subshell_environment, termsig_handler(), wait_sigint_handler(), wait_sigint_received, waiting_for_child, WAITPID, WIFCORED, WIFSIGNALED, WIFSTOPPED, and WTERMSIG.
wait_for_background_pids()
int wait_for_background_pids (struct procstat * ps)
Definition at line 711 of file nojobs.c.
 {
   pid_t got_pid;
   WAIT status;
   int njobs;
   /* If we aren't using job control, we let the kernel take care of the
      bookkeeping for us.  wait () will return -1 and set errno to ECHILD
      when there are no more unwaited-for child processes on both
      4.2 BSD-based and System V-based systems. */
   njobs = 0;
   siginterrupt (SIGINT, 1);
   /* Wait for ECHILD */
   waiting_for_child = 1;
   while ((got_pid = WAITPID (-1, &status, 0)) != -1)
     {
       waiting_for_child = 0;
       njobs++;
       set_pid_status (got_pid, status);
       if (ps)
     {
       ps->pid = got_pid;
       ps->status = process_exit_status (status);
     }
       waiting_for_child = 1;
       CHECK_WAIT_INTR;
     }
   waiting_for_child = 0;
   if (errno != EINTR && errno != ECHILD)
     {
       siginterrupt (SIGINT, 0);
       sys_error("wait");
     }
   siginterrupt (SIGINT, 0);
   QUIT;
   CHECK_WAIT_INTR;
   mark_dead_jobs_as_notified (1);
   cleanup_dead_jobs ();
   return njobs;
 }
References CHECK_WAIT_INTR, cleanup_dead_jobs(), ECHILD, EINTR, errno, mark_dead_jobs_as_notified(), procstat::pid, process_exit_status(), QUIT, set_pid_status(), SIGINT, siginterrupt, procstat::status, mlibc::status, sys_error(), waiting_for_child, and WAITPID.
wait_for_single_pid()
int wait_for_single_pid (pid_t pid, int flags)
Definition at line 654 of file nojobs.c.
 {
   pid_t got_pid;
   WAIT status;
   int pstatus;
   pstatus = find_status_by_pid (pid);
   if (pstatus == PROC_BAD)
     {
       internal_error (_("wait: pid %ld is not a child of this shell"), (long)pid);
       return (257);
     }
   if (pstatus != PROC_STILL_ALIVE)
     {
       if (pstatus > 128)
     last_command_exit_signal = find_termsig_by_pid (pid);
       return (pstatus);
     }
   siginterrupt (SIGINT, 1);
   while ((got_pid = WAITPID (pid, &status, 0)) != pid)
     {
       CHECK_TERMSIG;
       CHECK_WAIT_INTR;
       if (got_pid < 0)
     {
       if (errno != EINTR && errno != ECHILD)
         {
           siginterrupt (SIGINT, 0);
           sys_error ("wait");
         }
       break;
     }
       else if (got_pid > 0)
     set_pid_status (got_pid, status);
     }
   if (got_pid > 0)
     {
       set_pid_status (got_pid, status);
       set_pid_flags (got_pid, PROC_NOTIFIED);
     }
   siginterrupt (SIGINT, 0);
   QUIT;
   CHECK_WAIT_INTR;
   return (got_pid > 0 ? process_exit_status (status) : -1);
 }
References _, CHECK_TERMSIG, CHECK_WAIT_INTR, ECHILD, EINTR, errno, find_status_by_pid(), find_termsig_by_pid(), internal_error(), last_command_exit_signal, PROC_BAD, PROC_NOTIFIED, PROC_STILL_ALIVE, process_exit_status(), QUIT, set_pid_flags(), set_pid_status(), SIGINT, siginterrupt, mlibc::status, sys_error(), and WAITPID.
wait_sigint_cleanup()
void wait_sigint_cleanup ()
Definition at line 760 of file nojobs.c.
 {
 }
wait_sigint_handler()
static sighandler wait_sigint_handler (int sig) static
Definition at line 782 of file nojobs.c.
 {
   SigHandler *sigint_handler;
   /* If we got a SIGINT while in `wait', and SIGINT is trapped, do
      what POSIX.2 says (see builtins/wait.def for more info). */
   if (this_shell_builtin && this_shell_builtin == wait_builtin &&
       signal_is_trapped (SIGINT) &&
       ((sigint_handler = trap_to_sighandler (SIGINT)) == trap_handler))
     {
       last_command_exit_value = 128+SIGINT;
       restore_sigint_handler ();
       trap_handler (SIGINT);    /* set pending_traps[SIGINT] */
       wait_signal_received = SIGINT;
       SIGRETURN (0);
     }
   wait_sigint_received = 1;
   SIGRETURN (0);
 }
References last_command_exit_value, restore_sigint_handler(), SIGINT, signal_is_trapped(), SIGRETURN, this_shell_builtin, trap_handler(), trap_to_sighandler(), wait_sigint_received, and wait_signal_received.
Referenced by wait_for().
without_job_control()
void without_job_control ()
Definition at line 1030 of file nojobs.c.
 {
   stop_making_children ();
   last_made_pid = NO_PID;   /* XXX */
 }
References last_made_pid, NO_PID, and stop_making_children().
Variable Documentation
already_making_children
int already_making_children = 0
Definition at line 86 of file nojobs.c.
Referenced by start_pipeline(), stop_making_children(), and stop_pipeline().
check_window_size
int check_window_size = CHECKWINSIZE_DEFAULT
Definition at line 93 of file nojobs.c.
Referenced by get_tty_state(), and wait_for().
child_max
long child_max = -1L static
Definition at line 122 of file nojobs.c.
Referenced by mark_dead_jobs_as_notified().
errno
int errno extern
Referenced by make_child(), wait_for(), wait_for_background_pids(), and wait_for_single_pid().
got_tty_state
int got_tty_state static
Definition at line 962 of file nojobs.c.
Referenced by get_tty_state(), and set_tty_state().
job_control
int job_control = 0
Definition at line 96 of file nojobs.c.
last_asynchronous_pid
volatile pid_t last_asynchronous_pid = NO_PID
Definition at line 80 of file nojobs.c.
Referenced by make_child(), and mark_dead_jobs_as_notified().
last_made_pid
volatile pid_t last_made_pid = NO_PID
Definition at line 79 of file nojobs.c.
Referenced by make_child(), and without_job_control().
old_sigint_handler
SigHandler* old_sigint_handler = INVALID_SIGNAL_HANDLER static
Definition at line 766 of file nojobs.c.
Referenced by restore_sigint_handler(), and wait_for().
pid_list
struct proc_status* pid_list = (struct proc_status *)NULL static
Definition at line 118 of file nojobs.c.
Referenced by add_pid(), alloc_pid_list(), cleanup_dead_jobs(), find_index_by_pid(), find_proc_slot(), find_status_by_pid(), find_termsig_by_pid(), get_pid_flags(), mark_dead_jobs_as_notified(), set_pid_flags(), set_pid_status(), and unset_pid_flags().
pid_list_size
int pid_list_size static
Definition at line 119 of file nojobs.c.
Referenced by alloc_pid_list(), cleanup_dead_jobs(), find_index_by_pid(), find_proc_slot(), and mark_dead_jobs_as_notified().
queue_sigchld
int queue_sigchld static
Definition at line 82 of file nojobs.c.
running_in_background
int running_in_background = 0
Definition at line 98 of file nojobs.c.
Referenced by shell_reinitialize().
shell_tty
int shell_tty = -1
Definition at line 89 of file nojobs.c.
Referenced by initialize_job_control().
shell_tty_info
TTYSTRUCT shell_tty_info static
Definition at line 961 of file nojobs.c.
Referenced by get_tty_state(), and set_tty_state().
wait_sigint_received
int wait_sigint_received static
Definition at line 120 of file nojobs.c.
Referenced by wait_for(), and wait_sigint_handler().
waiting_for_child
int waiting_for_child
Definition at line 83 of file nojobs.c.
Referenced by trap_handler(), wait_for(), and wait_for_background_pids().