Fennix Userspace: Userspace/musl/src/stdio/vdprintf.c File Reference
vdprintf.c File Reference
#include "stdio_impl.h"
Functions
int vdprintf (int fd, const char *restrict fmt, va_list ap)
Function Documentation
vdprintf()
int vdprintf (int fd, const char *restrict fmt, va_list ap)
Definition at line 3 of file vdprintf.c.
 {
     FILE f = {
         .fd = fd, .lbf = EOF, .write = __stdio_write,
         .buf = (void *)fmt, .buf_size = 0,
         .lock = -1
     };
     return vfprintf(&f, fmt, ap);
 }
References __stdio_write(), ap, EOF, f, fd, _IO_FILE::fd, lock, and vfprintf().
Referenced by dprintf(), and error_impl().