Fennix: Userspace/apps/base/bash/lib/sh/random.c File Reference
random.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "filecntl.h"
#include <stdio.h>
#include "bashansi.h"
#include "shell.h"
Macros
#define BASH_RAND_MAX 32767 /* 0x7fff - 16 bits */
#define BASH_RAND32_MAX 0x7fffffff /* 32 bits */
#define GRND_NONBLOCK 1
#define GRND_RANDOM 2
Functions
static u_bits32_t intrand32 PARAMS ((u_bits32_t))
static u_bits32_t genseed PARAMS ((void))
static u_bits32_t intrand32 (u_bits32_t last)
static u_bits32_t genseed ()
int brand ()
void sbrand (unsigned long seed)
void seedrand ()
static u_bits32_t brand32 ()
static void sbrand32 (u_bits32_t seed)
void seedrand32 ()
static void perturb_rand32 ()
void urandom_close ()
static ssize_t getrandom (void *buf, size_t len, unsigned int flags)
u_bits32_t get_urandom32 ()
Variables
time_t shell_start_time
int last_random_value
static u_bits32_t rseed = 1
static u_bits32_t rseed32 = 1073741823
static int last_rand32
static int urandfd = -1
Macro Definition Documentation
BASH_RAND32_MAX
#define BASH_RAND32_MAX 0x7fffffff /* 32 bits */
Definition at line 137 of file random.c.
BASH_RAND_MAX
#define BASH_RAND_MAX 32767 /* 0x7fff - 16 bits */
Definition at line 98 of file random.c.
GRND_NONBLOCK
#define GRND_NONBLOCK 1
Definition at line 183 of file random.c.
GRND_RANDOM
#define GRND_RANDOM 2
Definition at line 184 of file random.c.
Function Documentation
brand()
int brand ()
Definition at line 102 of file random.c.
 {
   unsigned int ret;
   rseed = intrand32 (rseed);
   if (shell_compatibility_level > 50)
     ret = (rseed >> 16) ^ (rseed & 65535);
   else
     ret = rseed;
   return (ret & BASH_RAND_MAX);
 }
References BASH_RAND_MAX, intrand32(), rseed, and shell_compatibility_level.
Referenced by get_random_number().
brand32()
static u_bits32_t brand32 () static
Definition at line 141 of file random.c.
 {
   u_bits32_t ret;
   rseed32 = intrand32 (rseed32);
   return (rseed32 & BASH_RAND32_MAX);
 }
References BASH_RAND32_MAX, intrand32(), and rseed32.
Referenced by get_urandom32().
genseed()
static u_bits32_t genseed () static
Definition at line 87 of file random.c.
 {
   struct timeval tv;
   u_bits32_t iv;
   gettimeofday (&tv, NULL);
   iv = (u_bits32_t)seedrand;        /* let the compiler truncate */
   iv = tv.tv_sec ^ tv.tv_usec ^ getpid () ^ getppid () ^ current_user.uid ^ iv;
   return (iv);
 }
References current_user, getpid(), getppid(), gettimeofday(), NULL, seedrand(), timeval::tv_sec, timeval::tv_usec, and user_info::uid.
Referenced by perturb_rand32(), seedrand(), and seedrand32().
get_urandom32()
u_bits32_t get_urandom32 ()
Definition at line 223 of file random.c.
 {
   u_bits32_t ret;
   if (getrandom ((void *)&ret, sizeof (ret), GRND_NONBLOCK) == sizeof (ret))
     return (last_rand32 = ret);
 #if defined (HAVE_ARC4RANDOM)
   ret = arc4random ();
 #else
   if (subshell_environment)
     perturb_rand32 ();
   do
     ret = brand32 ();
   while (ret == last_rand32);
 #endif
   return (last_rand32 = ret);
 }
References brand32(), getrandom(), GRND_NONBLOCK, last_rand32, perturb_rand32(), and subshell_environment.
Referenced by get_urandom().
getrandom()
static ssize_t getrandom (void * buf, size_t len, unsigned int flags) static
Definition at line 188 of file random.c.
 {
   int oflags;
   ssize_t r;
   static int urand_unavail = 0;
 #if HAVE_GETENTROPY
   r = getentropy (buf, len);
   return (r == 0) ? len : -1;
 #endif
   if (urandfd == -1 && urand_unavail == 0)
     {
       oflags = O_RDONLY;
       if (flags & GRND_NONBLOCK)
     oflags |= O_NONBLOCK;
       urandfd = open ("/dev/urandom", oflags, 0);
       if (urandfd >= 0)
     SET_CLOSE_ON_EXEC (urandfd);
       else
     {
       urand_unavail = 1;
       return -1;
     }
     }
   if (urandfd >= 0 && (r = read (urandfd, buf, len)) == len)
     return (r);
   return -1;
 }
References buf, flags, getentropy(), GRND_NONBLOCK, len, O_NONBLOCK, O_RDONLY, open(), read(), SET_CLOSE_ON_EXEC, and urandfd.
Referenced by get_urandom32(), getentropy(), and read_new_seed().
intrand32()
static u_bits32_t intrand32 (u_bits32_t last) static
Definition at line 55 of file random.c.
 {
   /* Minimal Standard generator from
      "Random number generators: good ones are hard to find",
      Park and Miller, Communications of the ACM, vol. 31, no. 10,
      October 1988, p. 1195. Filtered through FreeBSD.
      x(n+1) = 16807 * x(n) mod (m).
      We split up the calculations to avoid overflow.
      h = last / q; l = x - h * q; t = a * l - h * r
      m = 2147483647, a = 16807, q = 127773, r = 2836
      There are lots of other combinations of constants to use; look at
      https://www.gnu.org/software/gsl/manual/html_node/Other-random-number-generators.html#Other-random-number-generators */
   bits32_t h, l, t;
   u_bits32_t ret;
   /* Can't seed with 0. */
   ret = (last == 0) ? 123459876 : last;
   h = ret / 127773;
   l = ret - (127773 * h);
   t = 16807 * l - 2836 * h;
   ret = (t < 0) ? t + 0x7fffffff : t;
   return (ret);
 }
References h, l, last, and t.
Referenced by brand(), and brand32().
PARAMS() [1/2]
static u_bits32_t intrand32 PARAMS ((u_bits32_t)) static
PARAMS() [2/2]
static u_bits32_t genseed PARAMS ((void)) static
perturb_rand32()
static void perturb_rand32 () static
Definition at line 166 of file random.c.
 {
   rseed32 ^= genseed ();
 }
References genseed(), and rseed32.
Referenced by get_urandom32().
sbrand()
void sbrand (unsigned long seed)
Definition at line 116 of file random.c.
 {
   rseed = seed;
   last_random_value = 0;
 }
References last_random_value, rseed, and seed.
Referenced by assign_random(), and seedrand().
sbrand32()
static void sbrand32 (u_bits32_t seed) static
Definition at line 150 of file random.c.
 {
   last_rand32 = rseed32 = seed;
 }
References last_rand32, rseed32, and seed.
Referenced by seedrand32().
seedrand()
void seedrand ()
Definition at line 124 of file random.c.
 {
   u_bits32_t iv;
   iv = genseed ();
   sbrand (iv);
 }
References genseed(), and sbrand().
Referenced by genseed(), get_random_number(), and initialize_shell_variables().
seedrand32()
void seedrand32 ()
Definition at line 157 of file random.c.
 {
   u_bits32_t iv;
   iv = genseed ();
   sbrand32 (iv);
 }
References genseed(), and sbrand32().
Referenced by initialize_shell_variables().
urandom_close()
void urandom_close ()
Definition at line 173 of file random.c.
 {
   if (urandfd >= 0)
     close (urandfd);
   urandfd = -1;
 }
References close(), and urandfd.
Variable Documentation
last_rand32
int last_rand32 static
Definition at line 133 of file random.c.
Referenced by get_urandom32(), and sbrand32().
last_random_value
int last_random_value extern
Definition at line 1397 of file variables.c.
Referenced by get_random_number(), and sbrand().
rseed
u_bits32_t rseed = 1 static
Definition at line 51 of file random.c.
Referenced by brand(), and sbrand().
rseed32
u_bits32_t rseed32 = 1073741823 static
Definition at line 132 of file random.c.
Referenced by brand32(), perturb_rand32(), and sbrand32().
shell_start_time
time_t shell_start_time extern
Definition at line 183 of file shell.c.
urandfd
int urandfd = -1 static
Definition at line 135 of file random.c.
Referenced by getrandom(), and urandom_close().