Fennix Userspace: Userspace/libc/include/unistd.h File Reference
unistd.h File Reference
#include <sys/types.h>
Functions
int execv (const char *, char *const[])
int execve (const char *, char *const[], char *const[])
int execvp (const char *, char *const[])
pid_t fork (void)
Function Documentation
execv()
int execv (const char * path, char * const argv[])
Definition at line 137 of file unistd-stubs.cpp.
{
     return execve(path, argv, environ);
 }
References environ, and execve().
execve()
int execve (const char * path, char * const argv[], char * const envp[])
Definition at line 1014 of file unistd-stubs.cpp.
{
     char *null_list[] = {
         nullptr
     };
     if(!argv)
         argv = null_list;
     if(!envp)
         envp = null_list;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_execve, -1);
     int e = mlibc::sys_execve(path, argv, envp);
     __ensure(e && "sys_execve() is expected to fail if it returns");
     errno = e;
     return -1;
 }
References __ensure, errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_execve().
Referenced by child().
execvp()
int execvp (const char * file, char * const argv[])
Definition at line 141 of file unistd-stubs.cpp.
{
     return execvpe(file, argv, environ);
 }
References environ, and execvpe().
fork()
pid_t fork (void)
Definition at line 949 of file unistd-stubs.cpp.
                  {
     auto self = mlibc::get_current_tcb();
     pid_t child;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fork, -1);
     auto hand = self->atforkEnd;
     while (hand) {
         if (hand->prepare)
             hand->prepare();
         hand = hand->prev;
     }
     if(int e = mlibc::sys_fork(&child); e) {
         errno = e;
         return -1;
     }
     hand = self->atforkBegin;
     while (hand) {
         if (!child) {
             if (hand->child)
                 hand->child();
         } else {
             if (hand->parent)
                 hand->parent();
         }
         hand = hand->next;
     }
     return child;
 }
References child, errno, mlibc::get_current_tcb(), MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fork().
Referenced by main(), posix_spawn(), and we_askshell().