Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_pspr.c File Reference
p_pspr.c File Reference
#include "doomdef.h"
#include "d_event.h"
#include "deh_misc.h"
#include "m_random.h"
#include "p_local.h"
#include "s_sound.h"
#include "doomstat.h"
#include "sounds.h"
#include "p_pspr.h"
Macros
#define LOWERSPEED FRACUNIT*6
#define RAISESPEED FRACUNIT*6
#define WEAPONBOTTOM 128*FRACUNIT
#define WEAPONTOP 32*FRACUNIT
Functions
void P_SetPsprite (player_t *player, int position, statenum_t stnum)
void P_CalcSwing (player_t *player)
void P_BringUpWeapon (player_t *player)
boolean P_CheckAmmo (player_t *player)
void P_FireWeapon (player_t *player)
void P_DropWeapon (player_t *player)
void A_WeaponReady (player_t *player, pspdef_t *psp)
void A_ReFire (player_t *player, pspdef_t *psp)
void A_CheckReload (player_t *player, pspdef_t *psp)
void A_Lower (player_t *player, pspdef_t *psp)
void A_Raise (player_t *player, pspdef_t *psp)
void A_GunFlash (player_t *player, pspdef_t *psp)
void A_Punch (player_t *player, pspdef_t *psp)
void A_Saw (player_t *player, pspdef_t *psp)
static void DecreaseAmmo (player_t *player, int ammonum, int amount)
void A_FireMissile (player_t *player, pspdef_t *psp)
void A_FireBFG (player_t *player, pspdef_t *psp)
void A_FirePlasma (player_t *player, pspdef_t *psp)
void P_BulletSlope (mobj_t *mo)
void P_GunShot (mobj_t *mo, boolean accurate)
void A_FirePistol (player_t *player, pspdef_t *psp)
void A_FireShotgun (player_t *player, pspdef_t *psp)
void A_FireShotgun2 (player_t *player, pspdef_t *psp)
void A_FireCGun (player_t *player, pspdef_t *psp)
void A_Light0 (player_t *player, pspdef_t *psp)
void A_Light1 (player_t *player, pspdef_t *psp)
void A_Light2 (player_t *player, pspdef_t *psp)
void A_BFGSpray (mobj_t *mo)
void A_BFGsound (player_t *player, pspdef_t *psp)
void P_SetupPsprites (player_t *player)
void P_MovePsprites (player_t *player)
Variables
fixed_t swingx
fixed_t swingy
fixed_t bulletslope
Macro Definition Documentation
LOWERSPEED
#define LOWERSPEED FRACUNIT*6
Definition at line 38 of file p_pspr.c.
RAISESPEED
#define RAISESPEED FRACUNIT*6
Definition at line 39 of file p_pspr.c.
WEAPONBOTTOM
#define WEAPONBOTTOM 128*FRACUNIT
Definition at line 41 of file p_pspr.c.
WEAPONTOP
#define WEAPONTOP 32*FRACUNIT
Definition at line 42 of file p_pspr.c.
Function Documentation
A_BFGsound()
void A_BFGsound (player_t * player, pspdef_t * psp)
Definition at line 827 of file p_pspr.c.
 {
     S_StartSound (player->mo, sfx_bfg);
 }
References player_s::mo, S_StartSound(), and sfx_bfg.
A_BFGSpray()
void A_BFGSpray (mobj_t * mo)
Definition at line 790 of file p_pspr.c.
 {
     int         i;
     int         j;
     int         damage;
     angle_t     an;
     // offset angles from its attack angle
     for (i=0 ; i<40 ; i++)
     {
     an = mo->angle - ANG90/2 + ANG90/40*i;
     // mo->target is the originator (player)
     //  of the missile
     P_AimLineAttack (mo->target, an, 16*64*FRACUNIT);
     if (!linetarget)
         continue;
     P_SpawnMobj (linetarget->x,
              linetarget->y,
              linetarget->z + (linetarget->height>>2),
              MT_EXTRABFG);
     damage = 0;
     for (j=0;j<15;j++)
         damage += (P_Random()&7) + 1;
     P_DamageMobj (linetarget, mo->target,mo->target, damage);
     }
 }
References ANG90, mobj_s::angle, FRACUNIT, mobj_s::height, i, j, linetarget, MT_EXTRABFG, P_AimLineAttack(), P_DamageMobj(), P_Random(), P_SpawnMobj(), mobj_s::target, mobj_s::x, mobj_s::y, and mobj_s::z.
A_CheckReload()
void A_CheckReload (player_t * player, pspdef_t * psp)
Definition at line 357 of file p_pspr.c.
 {
     P_CheckAmmo (player);
 #if 0
     if (player->ammo[am_shell]<2)
     P_SetPsprite (player, ps_weapon, S_DSNR1);
 #endif
 }
References am_shell, player_s::ammo, P_CheckAmmo(), P_SetPsprite(), ps_weapon, and S_DSNR1.
A_FireBFG()
void A_FireBFG (player_t * player, pspdef_t * psp)
Definition at line 572 of file p_pspr.c.
 {
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo,
                  deh_bfg_cells_per_shot);
     P_SpawnPlayerMissile (player->mo, MT_BFG);
 }
References weaponinfo_t::ammo, DecreaseAmmo(), deh_bfg_cells_per_shot, player_s::mo, MT_BFG, P_SpawnPlayerMissile(), player_s::readyweapon, and weaponinfo.
A_FireCGun()
void A_FireCGun (player_t * player, pspdef_t * psp)
Definition at line 742 of file p_pspr.c.
 {
     S_StartSound (player->mo, sfx_pistol);
     if (!player->ammo[weaponinfo[player->readyweapon].ammo])
     return;
     P_SetMobjState (player->mo, S_PLAY_ATK2);
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo, 1);
     P_SetPsprite (player,
           ps_flash,
           weaponinfo[player->readyweapon].flashstate
           + psp->state
           - &states[S_CHAIN1] );
     P_BulletSlope (player->mo);
     P_GunShot (player->mo, !player->refire);
 }
References weaponinfo_t::ammo, player_s::ammo, DecreaseAmmo(), weaponinfo_t::flashstate, player_s::mo, P_BulletSlope(), P_GunShot(), P_SetMobjState(), P_SetPsprite(), ps_flash, player_s::readyweapon, player_s::refire, S_CHAIN1, S_PLAY_ATK2, S_StartSound(), sfx_pistol, pspdef_t::state, states, and weaponinfo.
A_FireMissile()
void A_FireMissile (player_t * player, pspdef_t * psp)
Definition at line 559 of file p_pspr.c.
 {
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo, 1);
     P_SpawnPlayerMissile (player->mo, MT_ROCKET);
 }
References weaponinfo_t::ammo, DecreaseAmmo(), player_s::mo, MT_ROCKET, P_SpawnPlayerMissile(), player_s::readyweapon, and weaponinfo.
A_FirePistol()
void A_FirePistol (player_t * player, pspdef_t * psp)
Definition at line 656 of file p_pspr.c.
 {
     S_StartSound (player->mo, sfx_pistol);
     P_SetMobjState (player->mo, S_PLAY_ATK2);
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo, 1);
     P_SetPsprite (player,
           ps_flash,
           weaponinfo[player->readyweapon].flashstate);
     P_BulletSlope (player->mo);
     P_GunShot (player->mo, !player->refire);
 }
References weaponinfo_t::ammo, DecreaseAmmo(), weaponinfo_t::flashstate, player_s::mo, P_BulletSlope(), P_GunShot(), P_SetMobjState(), P_SetPsprite(), ps_flash, player_s::readyweapon, player_s::refire, S_PLAY_ATK2, S_StartSound(), sfx_pistol, and weaponinfo.
A_FirePlasma()
void A_FirePlasma (player_t * player, pspdef_t * psp)
Definition at line 587 of file p_pspr.c.
 {
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo, 1);
     P_SetPsprite (player,
           ps_flash,
           weaponinfo[player->readyweapon].flashstate+(P_Random ()&1) );
     P_SpawnPlayerMissile (player->mo, MT_PLASMA);
 }
References weaponinfo_t::ammo, DecreaseAmmo(), weaponinfo_t::flashstate, player_s::mo, MT_PLASMA, P_Random(), P_SetPsprite(), P_SpawnPlayerMissile(), ps_flash, player_s::readyweapon, and weaponinfo.
A_FireShotgun()
void A_FireShotgun (player_t * player, pspdef_t * psp)
Definition at line 678 of file p_pspr.c.
 {
     int     i;
     S_StartSound (player->mo, sfx_shotgn);
     P_SetMobjState (player->mo, S_PLAY_ATK2);
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo, 1);
     P_SetPsprite (player,
           ps_flash,
           weaponinfo[player->readyweapon].flashstate);
     P_BulletSlope (player->mo);
     for (i=0 ; i<7 ; i++)
     P_GunShot (player->mo, false);
 }
References weaponinfo_t::ammo, DecreaseAmmo(), weaponinfo_t::flashstate, i, player_s::mo, P_BulletSlope(), P_GunShot(), P_SetMobjState(), P_SetPsprite(), ps_flash, player_s::readyweapon, S_PLAY_ATK2, S_StartSound(), sfx_shotgn, and weaponinfo.
A_FireShotgun2()
void A_FireShotgun2 (player_t * player, pspdef_t * psp)
Definition at line 705 of file p_pspr.c.
 {
     int     i;
     angle_t angle;
     int     damage;
     S_StartSound (player->mo, sfx_dshtgn);
     P_SetMobjState (player->mo, S_PLAY_ATK2);
     DecreaseAmmo(player, weaponinfo[player->readyweapon].ammo, 2);
     P_SetPsprite (player,
           ps_flash,
           weaponinfo[player->readyweapon].flashstate);
     P_BulletSlope (player->mo);
     for (i=0 ; i<20 ; i++)
     {
     damage = 5*(P_Random ()%3+1);
     angle = player->mo->angle;
     angle += (P_Random()-P_Random())<<19;
     P_LineAttack (player->mo,
               angle,
               MISSILERANGE,
               bulletslope + ((P_Random()-P_Random())<<5), damage);
     }
 }
References weaponinfo_t::ammo, mobj_s::angle, bulletslope, DecreaseAmmo(), weaponinfo_t::flashstate, i, MISSILERANGE, player_s::mo, P_BulletSlope(), P_LineAttack(), P_Random(), P_SetMobjState(), P_SetPsprite(), ps_flash, player_s::readyweapon, S_PLAY_ATK2, S_StartSound(), sfx_dshtgn, and weaponinfo.
A_GunFlash()
void A_GunFlash (player_t * player, pspdef_t * psp)
Definition at line 440 of file p_pspr.c.
 {
     P_SetMobjState (player->mo, S_PLAY_ATK2);
     P_SetPsprite (player,ps_flash,weaponinfo[player->readyweapon].flashstate);
 }
References weaponinfo_t::flashstate, player_s::mo, P_SetMobjState(), P_SetPsprite(), ps_flash, player_s::readyweapon, S_PLAY_ATK2, and weaponinfo.
A_Light0()
void A_Light0 (player_t * player, pspdef_t * psp)
Definition at line 770 of file p_pspr.c.
 {
     player->extralight = 0;
 }
References player_s::extralight.
A_Light1()
void A_Light1 (player_t * player, pspdef_t * psp)
Definition at line 775 of file p_pspr.c.
 {
     player->extralight = 1;
 }
References player_s::extralight.
A_Light2()
void A_Light2 (player_t * player, pspdef_t * psp)
Definition at line 780 of file p_pspr.c.
 {
     player->extralight = 2;
 }
References player_s::extralight.
A_Lower()
void A_Lower (player_t * player, pspdef_t * psp)
Definition at line 376 of file p_pspr.c.
 {
     psp->sy += LOWERSPEED;
     // Is already down.
     if (psp->sy < WEAPONBOTTOM )
     return;
     // Player is dead.
     if (player->playerstate == PST_DEAD)
     {
     psp->sy = WEAPONBOTTOM;
     // don't bring weapon back up
     return;
     }
     // The old weapon has been lowered off the screen,
     // so change the weapon and start raising it
     if (!player->health)
     {
     // Player is dead, so keep the weapon off screen.
     P_SetPsprite (player,  ps_weapon, S_NULL);
     return;
     }
     player->readyweapon = player->pendingweapon;
     P_BringUpWeapon (player);
 }
References player_s::health, LOWERSPEED, P_BringUpWeapon(), P_SetPsprite(), player_s::pendingweapon, player_s::playerstate, ps_weapon, PST_DEAD, player_s::readyweapon, S_NULL, pspdef_t::sy, and WEAPONBOTTOM.
A_Punch()
void A_Punch (player_t * player, pspdef_t * psp)
Definition at line 459 of file p_pspr.c.
 {
     angle_t angle;
     int     damage;
     int     slope;
     damage = (P_Random ()%10+1)<<1;
     if (player->powers[pw_strength])
     damage *= 10;
     angle = player->mo->angle;
     angle += (P_Random()-P_Random())<<18;
     slope = P_AimLineAttack (player->mo, angle, MELEERANGE);
     P_LineAttack (player->mo, angle, MELEERANGE, slope, damage);
     // turn to face target
     if (linetarget)
     {
     S_StartSound (player->mo, sfx_punch);
     player->mo->angle = R_PointToAngle2 (player->mo->x,
                          player->mo->y,
                          linetarget->x,
                          linetarget->y);
     }
 }
References mobj_s::angle, linetarget, MELEERANGE, player_s::mo, P_AimLineAttack(), P_LineAttack(), P_Random(), player_s::powers, pw_strength, R_PointToAngle2(), S_StartSound(), sfx_punch, mobj_s::x, and mobj_s::y.
A_Raise()
void A_Raise (player_t * player, pspdef_t * psp)
Definition at line 414 of file p_pspr.c.
 {
     statenum_t  newstate;
     psp->sy -= RAISESPEED;
     if (psp->sy > WEAPONTOP )
     return;
     psp->sy = WEAPONTOP;
     // The weapon has been raised all the way,
     //  so change to the ready state.
     newstate = weaponinfo[player->readyweapon].readystate;
     P_SetPsprite (player, ps_weapon, newstate);
 }
References P_SetPsprite(), ps_weapon, RAISESPEED, weaponinfo_t::readystate, player_s::readyweapon, pspdef_t::sy, weaponinfo, and WEAPONTOP.
A_ReFire()
void A_ReFire (player_t * player, pspdef_t * psp)
Definition at line 334 of file p_pspr.c.
 {
     // check for fire
     //  (if a weaponchange is pending, let it go through instead)
     if ( (player->cmd.buttons & BT_ATTACK)
      && player->pendingweapon == wp_nochange
      && player->health)
     {
     player->refire++;
     P_FireWeapon (player);
     }
     else
     {
     player->refire = 0;
     P_CheckAmmo (player);
     }
 }
References BT_ATTACK, ticcmd_t::buttons, player_s::cmd, player_s::health, P_CheckAmmo(), P_FireWeapon(), player_s::pendingweapon, player_s::refire, and wp_nochange.
Referenced by A_CloseShotgun2().
A_Saw()
void A_Saw (player_t * player, pspdef_t * psp)
Definition at line 493 of file p_pspr.c.
 {
     angle_t angle;
     int     damage;
     int     slope;
     damage = 2*(P_Random ()%10+1);
     angle = player->mo->angle;
     angle += (P_Random()-P_Random())<<18;
     // use meleerange + 1 se the puff doesn't skip the flash
     slope = P_AimLineAttack (player->mo, angle, MELEERANGE+1);
     P_LineAttack (player->mo, angle, MELEERANGE+1, slope, damage);
     if (!linetarget)
     {
     S_StartSound (player->mo, sfx_sawful);
     return;
     }
     S_StartSound (player->mo, sfx_sawhit);
     // turn to face target
     angle = R_PointToAngle2 (player->mo->x, player->mo->y,
                  linetarget->x, linetarget->y);
     if (angle - player->mo->angle > ANG180)
     {
     if ((signed int) (angle - player->mo->angle) < -ANG90/20)
         player->mo->angle = angle + ANG90/21;
     else
         player->mo->angle -= ANG90/20;
     }
     else
     {
     if (angle - player->mo->angle > ANG90/20)
         player->mo->angle = angle - ANG90/21;
     else
         player->mo->angle += ANG90/20;
     }
     player->mo->flags |= MF_JUSTATTACKED;
 }
References ANG180, ANG90, mobj_s::angle, mobj_s::flags, linetarget, MELEERANGE, MF_JUSTATTACKED, player_s::mo, P_AimLineAttack(), P_LineAttack(), P_Random(), R_PointToAngle2(), S_StartSound(), sfx_sawful, sfx_sawhit, mobj_s::x, and mobj_s::y.
A_WeaponReady()
void A_WeaponReady (player_t * player, pspdef_t * psp)
Definition at line 273 of file p_pspr.c.
 {
     statenum_t  newstate;
     int     angle;
     // get out of attack state
     if (player->mo->state == &states[S_PLAY_ATK1]
     || player->mo->state == &states[S_PLAY_ATK2] )
     {
     P_SetMobjState (player->mo, S_PLAY);
     }
     if (player->readyweapon == wp_chainsaw
     && psp->state == &states[S_SAW])
     {
     S_StartSound (player->mo, sfx_sawidl);
     }
     // check for change
     //  if player is dead, put the weapon away
     if (player->pendingweapon != wp_nochange || !player->health)
     {
     // change weapon
     //  (pending weapon should allready be validated)
     newstate = weaponinfo[player->readyweapon].downstate;
     P_SetPsprite (player, ps_weapon, newstate);
     return;
     }
     // check for fire
     //  the missile launcher and bfg do not auto fire
     if (player->cmd.buttons & BT_ATTACK)
     {
     if ( !player->attackdown
          || (player->readyweapon != wp_missile
          && player->readyweapon != wp_bfg) )
     {
         player->attackdown = true;
         P_FireWeapon (player);
         return;
     }
     }
     else
     player->attackdown = false;
     // bob the weapon based on movement speed
     angle = (128*leveltime)&FINEMASK;
     psp->sx = FRACUNIT + FixedMul (player->bob, finecosine[angle]);
     angle &= FINEANGLES/2-1;
     psp->sy = WEAPONTOP + FixedMul (player->bob, finesine[angle]);
 }
References player_s::attackdown, player_s::bob, BT_ATTACK, ticcmd_t::buttons, player_s::cmd, weaponinfo_t::downstate, FINEANGLES, finecosine, FINEMASK, finesine, FixedMul(), FRACUNIT, player_s::health, leveltime, player_s::mo, P_FireWeapon(), P_SetMobjState(), P_SetPsprite(), player_s::pendingweapon, ps_weapon, player_s::readyweapon, S_PLAY, S_PLAY_ATK1, S_PLAY_ATK2, S_SAW, S_StartSound(), sfx_sawidl, mobj_s::state, pspdef_t::state, states, pspdef_t::sx, pspdef_t::sy, weaponinfo, WEAPONTOP, wp_bfg, wp_chainsaw, wp_missile, and wp_nochange.
DecreaseAmmo()
static void DecreaseAmmo (player_t * player, int ammonum, int amount) static
Definition at line 542 of file p_pspr.c.
 {
     if (ammonum < NUMAMMO)
     {
         player->ammo[ammonum] -= amount;
     }
     else
     {
         player->maxammo[ammonum - NUMAMMO] -= amount;
     }
 }
References player_s::ammo, player_s::maxammo, and NUMAMMO.
Referenced by A_FireBFG(), A_FireCGun(), A_FireMissile(), A_FirePistol(), A_FirePlasma(), A_FireShotgun(), and A_FireShotgun2().
P_BringUpWeapon()
void P_BringUpWeapon (player_t * player)
Definition at line 129 of file p_pspr.c.
 {
     statenum_t  newstate;
     if (player->pendingweapon == wp_nochange)
     player->pendingweapon = player->readyweapon;
     if (player->pendingweapon == wp_chainsaw)
     S_StartSound (player->mo, sfx_sawup);
     newstate = weaponinfo[player->pendingweapon].upstate;
     player->pendingweapon = wp_nochange;
     player->psprites[ps_weapon].sy = WEAPONBOTTOM;
     P_SetPsprite (player, ps_weapon, newstate);
 }
References player_s::mo, P_SetPsprite(), player_s::pendingweapon, ps_weapon, player_s::psprites, player_s::readyweapon, S_StartSound(), sfx_sawup, pspdef_t::sy, weaponinfo_t::upstate, WEAPONBOTTOM, weaponinfo, wp_chainsaw, and wp_nochange.
Referenced by A_Lower(), and P_SetupPsprites().
P_BulletSlope()
void P_BulletSlope (mobj_t * mo)
Definition at line 610 of file p_pspr.c.
 {
     angle_t an;
     // see which target is to be aimed at
     an = mo->angle;
     bulletslope = P_AimLineAttack (mo, an, 16*64*FRACUNIT);
     if (!linetarget)
     {
     an += 1<<26;
     bulletslope = P_AimLineAttack (mo, an, 16*64*FRACUNIT);
     if (!linetarget)
     {
         an -= 2<<26;
         bulletslope = P_AimLineAttack (mo, an, 16*64*FRACUNIT);
     }
     }
 }
References mobj_s::angle, bulletslope, FRACUNIT, linetarget, and P_AimLineAttack().
Referenced by A_FireCGun(), A_FirePistol(), A_FireShotgun(), and A_FireShotgun2().
P_CalcSwing()
void P_CalcSwing (player_t * player)
Definition at line 103 of file p_pspr.c.
 {
     fixed_t swing;
     int     angle;
     // OPTIMIZE: tablify this.
     // A LUT would allow for different modes,
     //  and add flexibility.
     swing = player->bob;
     angle = (FINEANGLES/70*leveltime)&FINEMASK;
     swingx = FixedMul ( swing, finesine[angle]);
     angle = (FINEANGLES/70*leveltime+FINEANGLES/2)&FINEMASK;
     swingy = -FixedMul ( swingx, finesine[angle]);
 }
References player_s::bob, FINEANGLES, FINEMASK, finesine, FixedMul(), leveltime, swingx, and swingy.
P_CheckAmmo()
boolean P_CheckAmmo (player_t * player)
Definition at line 152 of file p_pspr.c.
 {
     ammotype_t      ammo;
     int         count;
     ammo = weaponinfo[player->readyweapon].ammo;
     // Minimal amount for one shot varies.
     if (player->readyweapon == wp_bfg)
     count = deh_bfg_cells_per_shot;
     else if (player->readyweapon == wp_supershotgun)
     count = 2;  // Double barrel.
     else
     count = 1;  // Regular.
     // Some do not need ammunition anyway.
     // Return if current ammunition sufficient.
     if (ammo == am_noammo || player->ammo[ammo] >= count)
     return true;
     // Out of ammo, pick a weapon to change to.
     // Preferences are set here.
     do
     {
     if (player->weaponowned[wp_plasma]
         && player->ammo[am_cell]
         && (gamemode != shareware) )
     {
         player->pendingweapon = wp_plasma;
     }
     else if (player->weaponowned[wp_supershotgun]
          && player->ammo[am_shell]>2
          && (gamemode == commercial) )
     {
         player->pendingweapon = wp_supershotgun;
     }
     else if (player->weaponowned[wp_chaingun]
          && player->ammo[am_clip])
     {
         player->pendingweapon = wp_chaingun;
     }
     else if (player->weaponowned[wp_shotgun]
          && player->ammo[am_shell])
     {
         player->pendingweapon = wp_shotgun;
     }
     else if (player->ammo[am_clip])
     {
         player->pendingweapon = wp_pistol;
     }
     else if (player->weaponowned[wp_chainsaw])
     {
         player->pendingweapon = wp_chainsaw;
     }
     else if (player->weaponowned[wp_missile]
          && player->ammo[am_misl])
     {
         player->pendingweapon = wp_missile;
     }
     else if (player->weaponowned[wp_bfg]
          && player->ammo[am_cell]>40
          && (gamemode != shareware) )
     {
         player->pendingweapon = wp_bfg;
     }
     else
     {
         // If everything fails.
         player->pendingweapon = wp_fist;
     }
     } while (player->pendingweapon == wp_nochange);
     // Now set appropriate weapon overlay.
     P_SetPsprite (player,
           ps_weapon,
           weaponinfo[player->readyweapon].downstate);
     return false;
 }
References am_cell, am_clip, am_misl, am_noammo, am_shell, weaponinfo_t::ammo, player_s::ammo, commercial, count, deh_bfg_cells_per_shot, weaponinfo_t::downstate, gamemode, P_SetPsprite(), player_s::pendingweapon, ps_weapon, player_s::readyweapon, shareware, weaponinfo, player_s::weaponowned, wp_bfg, wp_chaingun, wp_chainsaw, wp_fist, wp_missile, wp_nochange, wp_pistol, wp_plasma, wp_shotgun, and wp_supershotgun.
Referenced by A_CheckReload(), A_ReFire(), and P_FireWeapon().
P_DropWeapon()
void P_DropWeapon (player_t * player)
Definition at line 256 of file p_pspr.c.
 {
     P_SetPsprite (player,
           ps_weapon,
           weaponinfo[player->readyweapon].downstate);
 }
References weaponinfo_t::downstate, P_SetPsprite(), ps_weapon, player_s::readyweapon, and weaponinfo.
Referenced by P_KillMobj().
P_FireWeapon()
void P_FireWeapon (player_t * player)
Definition at line 237 of file p_pspr.c.
 {
     statenum_t  newstate;
     if (!P_CheckAmmo (player))
     return;
     P_SetMobjState (player->mo, S_PLAY_ATK1);
     newstate = weaponinfo[player->readyweapon].atkstate;
     P_SetPsprite (player, ps_weapon, newstate);
     P_NoiseAlert (player->mo, player->mo);
 }
References weaponinfo_t::atkstate, player_s::mo, P_CheckAmmo(), P_NoiseAlert(), P_SetMobjState(), P_SetPsprite(), ps_weapon, player_s::readyweapon, S_PLAY_ATK1, and weaponinfo.
Referenced by A_ReFire(), and A_WeaponReady().
P_GunShot()
void P_GunShot (mobj_t * mo, boolean accurate)
Definition at line 635 of file p_pspr.c.
 {
     angle_t angle;
     int     damage;
     damage = 5*(P_Random ()%3+1);
     angle = mo->angle;
     if (!accurate)
     angle += (P_Random()-P_Random())<<18;
     P_LineAttack (mo, angle, MISSILERANGE, bulletslope, damage);
 }
References mobj_s::angle, bulletslope, MISSILERANGE, P_LineAttack(), and P_Random().
Referenced by A_FireCGun(), A_FirePistol(), and A_FireShotgun().
P_MovePsprites()
void P_MovePsprites (player_t * player)
Definition at line 860 of file p_pspr.c.
 {
     int     i;
     pspdef_t*   psp;
     state_t*    state;
     psp = &player->psprites[0];
     for (i=0 ; i<NUMPSPRITES ; i++, psp++)
     {
     // a null state means not active
     if ( (state = psp->state) )
     {
         // drop tic count and possibly change state
         // a -1 tic count never changes
         if (psp->tics != -1)
         {
         psp->tics--;
         if (!psp->tics)
             P_SetPsprite (player, i, psp->state->nextstate);
         }
     }
     }
     player->psprites[ps_flash].sx = player->psprites[ps_weapon].sx;
     player->psprites[ps_flash].sy = player->psprites[ps_weapon].sy;
 }
References i, state_t::nextstate, NUMPSPRITES, P_SetPsprite(), ps_flash, ps_weapon, player_s::psprites, pspdef_t::state, state, pspdef_t::sx, pspdef_t::sy, and pspdef_t::tics.
Referenced by P_DeathThink(), and P_PlayerThink().
P_SetPsprite()
void P_SetPsprite (player_t * player, int position, statenum_t stnum)
Definition at line 50 of file p_pspr.c.
 {
     pspdef_t*   psp;
     state_t*    state;
     psp = &player->psprites[position];
     do
     {
     if (!stnum)
     {
         // object removed itself
         psp->state = NULL;
         break;
     }
     state = &states[stnum];
     psp->state = state;
     psp->tics = state->tics;    // could be 0
     if (state->misc1)
     {
         // coordinate set
         psp->sx = state->misc1 << FRACBITS;
         psp->sy = state->misc2 << FRACBITS;
     }
     // Call action routine.
     // Modified handling.
     if (state->action.acp2)
     {
         state->action.acp2(player, psp);
         if (!psp->state)
         break;
     }
     stnum = psp->state->nextstate;
     } while (!psp->tics);
     // an initial state of 0 could cycle through
 }
References FRACBITS, state_t::nextstate, NULL, player_s::psprites, pspdef_t::state, state, states, pspdef_t::sx, pspdef_t::sy, and pspdef_t::tics.
Referenced by A_CheckReload(), A_FireCGun(), A_FirePistol(), A_FirePlasma(), A_FireShotgun(), A_FireShotgun2(), A_GunFlash(), A_Lower(), A_Raise(), A_WeaponReady(), P_BringUpWeapon(), P_CheckAmmo(), P_DropWeapon(), P_FireWeapon(), and P_MovePsprites().
P_SetupPsprites()
void P_SetupPsprites (player_t * player)
Definition at line 840 of file p_pspr.c.
 {
     int i;
     // remove all psprites
     for (i=0 ; i<NUMPSPRITES ; i++)
     player->psprites[i].state = NULL;
     // spawn the gun
     player->pendingweapon = player->readyweapon;
     P_BringUpWeapon (player);
 }
References i, NULL, NUMPSPRITES, P_BringUpWeapon(), player_s::pendingweapon, player_s::psprites, player_s::readyweapon, and pspdef_t::state.
Referenced by P_SpawnPlayer().
Variable Documentation
bulletslope
fixed_t bulletslope
Definition at line 607 of file p_pspr.c.
Referenced by A_FireShotgun2(), P_BulletSlope(), and P_GunShot().
swingx
fixed_t swingx
Definition at line 100 of file p_pspr.c.
Referenced by P_CalcSwing().
swingy
fixed_t swingy
Definition at line 101 of file p_pspr.c.
Referenced by P_CalcSwing().