Fennix Userspace: Userspace/mlibc/options/ansi/musl-generic-math/sincosf.c File Reference
sincosf.c File Reference
#include "libm.h"
Macros
#define _GNU_SOURCE
Functions
void sincosf (float x, float *sin, float *cos)
Variables
static const double s1pio2 = 1*M_PI_2
static const double s2pio2 = 2*M_PI_2
static const double s3pio2 = 3*M_PI_2
static const double s4pio2 = 4*M_PI_2
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 17 of file sincosf.c.
Function Documentation
sincosf()
void sincosf (float x, float * sin, float * cos)
Definition at line 27 of file sincosf.c.
 {
     double y;
     float_t s, c;
     uint32_t ix;
     unsigned n, sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     /* |x| ~<= pi/4 */
     if (ix <= 0x3f490fda) {
         /* |x| < 2**-12 */
         if (ix < 0x39800000) {
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00100000 ? x/0x1p120f : x+0x1p120f);
             *sin = x;
             *cos = 1.0f;
             return;
         }
         *sin = __sindf(x);
         *cos = __cosdf(x);
         return;
     }
     /* |x| ~<= 5*pi/4 */
     if (ix <= 0x407b53d1) {
         if (ix <= 0x4016cbe3) {  /* |x| ~<= 3pi/4 */
             if (sign) {
                 *sin = -__cosdf(x + s1pio2);
                 *cos = __sindf(x + s1pio2);
             } else {
                 *sin = __cosdf(s1pio2 - x);
                 *cos = __sindf(s1pio2 - x);
             }
             return;
         }
         /* -sin(x+c) is not correct if x+c could be 0: -0 vs +0 */
         *sin = -__sindf(sign ? x + s2pio2 : x - s2pio2);
         *cos = -__cosdf(sign ? x + s2pio2 : x - s2pio2);
         return;
     }
     /* |x| ~<= 9*pi/4 */
     if (ix <= 0x40e231d5) {
         if (ix <= 0x40afeddf) {  /* |x| ~<= 7*pi/4 */
             if (sign) {
                 *sin = __cosdf(x + s3pio2);
                 *cos = -__sindf(x + s3pio2);
             } else {
                 *sin = -__cosdf(x - s3pio2);
                 *cos = __sindf(x - s3pio2);
             }
             return;
         }
         *sin = __sindf(sign ? x + s4pio2 : x - s4pio2);
         *cos = __cosdf(sign ? x + s4pio2 : x - s4pio2);
         return;
     }
     /* sin(Inf or NaN) is NaN */
     if (ix >= 0x7f800000) {
         *sin = *cos = x - x;
         return;
     }
     /* general argument reduction needed */
     n = __rem_pio2f(x, &y);
     s = __sindf(y);
     c = __cosdf(y);
     switch (n&3) {
     case 0:
         *sin = s;
         *cos = c;
         break;
     case 1:
         *sin = c;
         *cos = -s;
         break;
     case 2:
         *sin = -s;
         *cos = -c;
         break;
     case 3:
     default:
         *sin = -c;
         *cos = s;
         break;
     }
 }
References __cosdf(), __rem_pio2f(), __sindf(), c, cos(), FORCE_EVAL, GET_FLOAT_WORD, n, s1pio2, s2pio2, s3pio2, s4pio2, sin(), x, and y.
Variable Documentation
s1pio2
const double s1pio2 = 1*M_PI_2 static
Definition at line 22 of file sincosf.c.
Referenced by sincosf().
s2pio2
const double s2pio2 = 2*M_PI_2 static
Definition at line 23 of file sincosf.c.
Referenced by sincosf().
s3pio2
const double s3pio2 = 3*M_PI_2 static
Definition at line 24 of file sincosf.c.
Referenced by sincosf().
s4pio2
const double s4pio2 = 4*M_PI_2 static
Definition at line 25 of file sincosf.c.
Referenced by sincosf().