Fennix: Userspace/apps/base/bash/lib/malloc/xmalloc.c File Reference
xmalloc.c File Reference
#include <stdio.h>
#include "ansi_stdlib.h"
Macros
#define PTR_T char *
Functions
static void memory_error_and_abort (char *fname)
PTR_T xmalloc (size_t bytes)
PTR_T xrealloc (PTR_T pointer, size_t bytes)
void xfree (PTR_T string)
Macro Definition Documentation
PTR_T
#define PTR_T char *
Definition at line 40 of file xmalloc.c.
Function Documentation
memory_error_and_abort()
static void memory_error_and_abort (char * fname) static
Definition at line 52 of file xmalloc.c.
 {
   fprintf (stderr, "%s: out of virtual memory\n", fname);
   exit (2);
 }
References exit(), fname, fprintf(), and stderr.
Referenced by xmalloc(), and xrealloc().
xfree()
void xfree (PTR_T string)
Definition at line 89 of file xmalloc.c.
 {
   if (string)
     free (string);
 }
References free.
xmalloc()
PTR_T xmalloc (size_t bytes)
Definition at line 63 of file xmalloc.c.
 {
   PTR_T temp;
   temp = malloc (bytes);
   if (temp == 0)
     memory_error_and_abort ("xmalloc");
   return (temp);
 }
References malloc, memory_error_and_abort(), and PTR_T.
xrealloc()
PTR_T xrealloc (PTR_T pointer, size_t bytes)
Definition at line 75 of file xmalloc.c.
 {
   PTR_T temp;
   temp = pointer ? realloc (pointer, bytes) : malloc (bytes);
   if (temp == 0)
     memory_error_and_abort ("xrealloc");
   return (temp);
 }
References malloc, memory_error_and_abort(), PTR_T, and realloc.