Fennix: Userspace/musl/src/unistd/x32/lseek.c File Reference
lseek.c File Reference
#include <unistd.h>
#include "syscall.h"
Functions
off_t __lseek (int fd, off_t offset, int whence)
weak_alias (__lseek, lseek)
Function Documentation
__lseek()
off_t __lseek (int fd, off_t offset, int whence)
Definition at line 4 of file lseek.c.
 {
     off_t ret;
     __asm__ __volatile__ ("syscall"
         : "=a"(ret)
         : "a"(SYS_lseek), "D"(fd), "S"(offset), "d"(whence)
         : "rcx", "r11", "memory");
     return ret < 0 ? __syscall_ret(ret) : ret;
 }
References __asm__(), __syscall_ret(), fd, offset, and syscall().
Referenced by __stdio_seek().
weak_alias()
weak_alias (__lseek , lseek)