Fennix: Userspace/musl/src/legacy/futimes.c File Reference
futimes.c File Reference
#include <sys/stat.h>
#include <sys/time.h>
Macros
#define _GNU_SOURCE
Functions
int futimes (int fd, const struct timeval tv[2])
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file futimes.c.
Function Documentation
futimes()
int futimes (int fd, const struct timeval tv[2])
Definition at line 5 of file futimes.c.
 {
     struct timespec times[2];
     if (!tv) return futimens(fd, 0);
     times[0].tv_sec  = tv[0].tv_sec;
     times[0].tv_nsec = tv[0].tv_usec * 1000;
     times[1].tv_sec  = tv[1].tv_sec;
     times[1].tv_nsec = tv[1].tv_usec * 1000;
     return futimens(fd, times);
 }
References fd, futimens(), times(), timeval::tv_sec, and timeval::tv_usec.
Referenced by __futimes_time32().