Fennix Userspace: Userspace/mlibc/options/ansi/generic/wchar-stubs.cpp File Reference
wchar-stubs.cpp File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <wchar.h>
#include <wctype.h>
#include <bits/ensure.h>
#include <mlibc/charcode.hpp>
#include <mlibc/debug.hpp>
Data Structures
struct anonymous_namespace{wchar-stubs.cpp}::width_interval
Namespaces
anonymous_namespace{wchar-stubs.cpp}
Functions
wint_t btowc (int c)
int wctob (wint_t wc)
int mbsinit (const mbstate_t *stp)
size_t mbrlen (const char *mbs, size_t mb_limit, mbstate_t *stp)
size_t mbrtowc (wchar_t *wcp, const char *mbs, size_t mb_limit, mbstate_t *stp)
size_t wcrtomb (char *mbs, wchar_t wc, mbstate_t *stp)
size_t mbsrtowcs (wchar_t *wcs, const char **mbsp, size_t wc_limit, mbstate_t *stp)
size_t mbsnrtowcs (wchar_t *wcs, const char **mbsp, size_t mb_limit, size_t wc_limit, mbstate_t *stp)
size_t wcsrtombs (char *mbs, const wchar_t **wcsp, size_t mb_limit, mbstate_t *stp)
size_t wcsnrtombs (char *mbs, const wchar_t **wcsp, size_t wc_limit, size_t mb_limit, mbstate_t *stp)
bool anonymous_namespace{wchar-stubs.cpp}::intable (struct width_interval *table, int table_length, int c)
int wcwidth (wchar_t ucs)
int wcswidth (const wchar_t *wcs, size_t n)
wchar_t * wcsdup (const wchar_t *s)
int wcsncasecmp (const wchar_t *s1, const wchar_t *s2, size_t n)
Variables
__mlibc_mbstate anonymous_namespace{wchar-stubs.cpp}::mbrlen_state = __MLIBC_MBSTATE_INITIALIZER
__mlibc_mbstate anonymous_namespace{wchar-stubs.cpp}::mbrtowc_state = __MLIBC_MBSTATE_INITIALIZER
__mlibc_mbstate anonymous_namespace{wchar-stubs.cpp}::mbsrtowcs_state = __MLIBC_MBSTATE_INITIALIZER
__mlibc_mbstate anonymous_namespace{wchar-stubs.cpp}::wcsrtombs_state = __MLIBC_MBSTATE_INITIALIZER
struct width_interval anonymous_namespace{wchar-stubs.cpp}::ZERO_WIDTH []
struct width_interval anonymous_namespace{wchar-stubs.cpp}::WIDE_EASTASIAN []
Data Structure Documentation
anonymous_namespace{wchar-stubs.cpp}::width_interval
struct anonymous_namespace{wchar-stubs.cpp}::width_interval
Definition at line 249 of file wchar-stubs.cpp.
Data Fields
int end
int start
Function Documentation
btowc()
wint_t btowc (int c)
Definition at line 21 of file wchar-stubs.cpp.
                     {
     if(c == EOF)
         return WEOF;
     char nc = c;
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     if(auto e = cc->promote_wtranscode(nc, wc); e != mlibc::charcode_error::null)
         return WEOF;
     return wc;
 }
References c, mlibc::current_charcode(), EOF, mlibc::null, and WEOF.
mbrlen()
size_t mbrlen (const char * mbs, size_t mb_limit, mbstate_t * stp)
Definition at line 44 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     if(!stp)
         stp = &mbrlen_state;
     if(!mbs) {
         *stp = __MLIBC_MBSTATE_INITIALIZER;
         return 0;
     }
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{&wc, &wc + 1};
     if(auto e = cc->decode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null)
         __ensure(!"decode_wtranscode() errors are not handled");
     return nseq.it - mbs;
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{wchar-stubs.cpp}::mbrlen_state, and mlibc::null.
mbrtowc()
size_t mbrtowc (wchar_t * wcp, const char * mbs, size_t mb_limit, mbstate_t * stp)
Definition at line 62 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     if(!stp)
         stp = &mbrtowc_state;
     if(!mbs) {
         *stp = __MLIBC_MBSTATE_INITIALIZER;
         return 0;
     }
     wchar_t temp = 0;
     if(!wcp)
         wcp = &temp;
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{wcp, wcp + 1};
     if(auto e = cc->decode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         if(e == mlibc::charcode_error::input_underflow)
             return static_cast<size_t>(-2);
         __ensure(e == mlibc::charcode_error::illegal_input);
         errno = EILSEQ;
         return static_cast<size_t>(-1);
     }else{
         if (*mbs) {
             return nseq.it - mbs;
         } else {
             *stp = __MLIBC_MBSTATE_INITIALIZER;
             *wcp = 0;
             return 0;
         }
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), EILSEQ, errno, mlibc::illegal_input, mlibc::input_underflow, anonymous_namespace{wchar-stubs.cpp}::mbrtowc_state, and mlibc::null.
Referenced by verify_decode().
mbsinit()
int mbsinit (const mbstate_t * stp)
Definition at line 38 of file wchar-stubs.cpp.
{
     if(!stp)
         return -1;
     return !stp->__progress && !stp->__shift;
 }
References __mlibc_mbstate::__progress, and __mlibc_mbstate::__shift.
mbsnrtowcs()
size_t mbsnrtowcs (wchar_t * wcs, const char ** mbsp, size_t mb_limit, size_t wc_limit, mbstate_t * stp)
Definition at line 147 of file wchar-stubs.cpp.
{
     __ensure(mbsp);
     auto cc = mlibc::current_charcode();
     __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
     mlibc::code_seq<const char> nseq{*mbsp, (*mbsp) + mb_limit};
     mlibc::code_seq<wchar_t> wseq{wcs, wcs + wc_limit};
     if(!stp)
         stp = &mbsrtowcs_state;
     if(!wcs) {
         size_t size;
         if(auto e = cc->decode_wtranscode_length(nseq, &size, st); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->decode_wtranscode(nseq, wseq, st); e != mlibc::charcode_error::null) {
         __ensure(!"decode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = wseq.it - wcs;
         if(n < wc_limit) // Null-terminate resulting wide string.
             wcs[n] = 0;
         *mbsp = nullptr;
         return n;
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{wchar-stubs.cpp}::mbsrtowcs_state, n, mlibc::null, and size.
mbsrtowcs()
size_t mbsrtowcs (wchar_t * wcs, const char ** mbsp, size_t wc_limit, mbstate_t * stp)
Definition at line 117 of file wchar-stubs.cpp.
{
     __ensure(mbsp);
     auto cc = mlibc::current_charcode();
     __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
     mlibc::code_seq<const char> nseq{*mbsp, nullptr};
     mlibc::code_seq<wchar_t> wseq{wcs, wcs + wc_limit};
     if(!stp)
         stp = &mbsrtowcs_state;
     if(!wcs) {
         size_t size;
         if(auto e = cc->decode_wtranscode_length(nseq, &size, st); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->decode_wtranscode(nseq, wseq, st); e != mlibc::charcode_error::null) {
         __ensure(!"decode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = wseq.it - wcs;
         if(n < wc_limit) // Null-terminate resulting wide string.
             wcs[n] = 0;
         *mbsp = nullptr;
         return n;
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{wchar-stubs.cpp}::mbsrtowcs_state, n, mlibc::null, and size.
wcrtomb()
size_t wcrtomb (char * mbs, wchar_t wc, mbstate_t * stp)
Definition at line 95 of file wchar-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     // wcrtomb() always takes a mbstate_t.
     __ensure(stp);
     // TODO: Implement the following case:
     __ensure(mbs);
     mlibc::code_seq<const wchar_t> wseq{&wc, &wc + 1};
     mlibc::code_seq<char> nseq{mbs, mbs + 4}; // TODO: Replace 4 by some named constant.
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         size_t n = nseq.it - mbs;
         if(!n) // Null-terminate resulting wide string.
             *mbs = 0;
         return n;
     }
 }
References __ensure, mlibc::current_charcode(), n, and mlibc::null.
Referenced by PrintfAgent< F >::operator()().
wcsdup()
wchar_t* wcsdup (const wchar_t * s)
Definition at line 757 of file wchar-stubs.cpp.
{
     size_t len = wcslen(s);
     wchar_t *ret = (wchar_t *) malloc(sizeof(wchar_t) * (len + 1));
     if(!ret)
         return NULL;
     wmemcpy(ret, s, len + 1);
     return ret;
 }
References malloc(), NULL, ret, wcslen(), and wmemcpy().
Referenced by main().
wcsncasecmp()
int wcsncasecmp (const wchar_t * s1, const wchar_t * s2, size_t n)
Definition at line 766 of file wchar-stubs.cpp.
{
     for(size_t i = 0; i < n; i++) {
         wint_t c1 = towlower(s1[i]);
         wint_t c2 = towlower(s2[i]);
         if(c1 == L'\0' && c2 == L'\0')
             return 0;
         if(c1 < c2)
             return -1;
         if(c1 > c2)
             return 1;
     }
     return 0;
 }
References i, n, s1, s2, and towlower().
Referenced by main().
wcsnrtombs()
size_t wcsnrtombs (char * mbs, const wchar_t ** wcsp, size_t wc_limit, size_t mb_limit, mbstate_t * stp)
Definition at line 205 of file wchar-stubs.cpp.
{
     __ensure(wcsp && "wcsrtombs() with null input");
     auto cc = mlibc::current_charcode();
     mlibc::code_seq<char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<const wchar_t> wseq{*wcsp, (*wcsp) + wc_limit};
     if(!stp)
         stp = &wcsrtombs_state;
     if(!mbs) {
         size_t size;
         if(auto e = cc->encode_wtranscode_length(wseq, &size, *stp); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         *wcsp = wseq.it;
         size_t n = nseq.it - mbs;
         if(n < mb_limit) // Null-terminate resulting narrow string.
             mbs[n] = 0;
         return n;
     }
 }
References __ensure, mlibc::current_charcode(), n, mlibc::null, size, and anonymous_namespace{wchar-stubs.cpp}::wcsrtombs_state.
wcsrtombs()
size_t wcsrtombs (char * mbs, const wchar_t ** wcsp, size_t mb_limit, mbstate_t * stp)
Definition at line 177 of file wchar-stubs.cpp.
{
     __ensure(wcsp && "wcsrtombs() with null input");
     auto cc = mlibc::current_charcode();
     mlibc::code_seq<char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<const wchar_t> wseq{*wcsp, nullptr};
     if(!stp)
         stp = &wcsrtombs_state;
     if(!mbs) {
         size_t size;
         if(auto e = cc->encode_wtranscode_length(wseq, &size, *stp); e != mlibc::charcode_error::null)
             __ensure(!"decode_wtranscode() errors are not handled");
         return size;
     }
     if(auto e = cc->encode_wtranscode(nseq, wseq, *stp); e != mlibc::charcode_error::null) {
         __ensure(!"encode_wtranscode() errors are not handled");
         __builtin_unreachable();
     }else{
         *wcsp = wseq.it;
         size_t n = nseq.it - mbs;
         if(n < mb_limit) // Null-terminate resulting narrow string.
             mbs[n] = 0;
         return n;
     }
 }
References __ensure, mlibc::current_charcode(), n, mlibc::null, size, and anonymous_namespace{wchar-stubs.cpp}::wcsrtombs_state.
Referenced by main(), and wcstombs().
wcswidth()
int wcswidth (const wchar_t * wcs, size_t n)
Definition at line 745 of file wchar-stubs.cpp.
{
     int ret = 0;
     for(size_t i = 0; i < n && wcs[i]; i++) {
         int cols = wcwidth(wcs[i]);
         if (cols < 0)
             return -1;
         ret += cols;
     }
     return ret;
 }
References i, n, ret, and wcwidth().
wctob()
int wctob (wint_t wc)
Definition at line 33 of file wchar-stubs.cpp.
                      {
     // TODO: Revisit this once we have character encoding functions.
     return wc;
 }
wcwidth()
int wcwidth (wchar_t ucs)
Definition at line 726 of file wchar-stubs.cpp.
{
     // NOTE: created by hand, there isn't anything identifiable other than
     // general Cf category code to identify these, and some characters in Cf
     // category code are of non-zero width.
     if (ucs == 0 || ucs == 0x034F || (0x200B <= ucs && ucs <= 0x200F) ||
         ucs == 0x2028 || ucs == 0x2029 || (0x202A <= ucs && ucs <= 0x202E) ||
         (0x2060 <= ucs && ucs <= 0x2063)) {
         return 0;
     }
     // C0/C1 control characters.
     if (ucs < 32 || (0x07F <= ucs && ucs < 0x0A0)) return -1;
     // Combining characters with zero width.
     if (intable(ZERO_WIDTH, sizeof(ZERO_WIDTH) / sizeof(struct width_interval), ucs)) return 0;
     return intable(WIDE_EASTASIAN, sizeof(WIDE_EASTASIAN) / sizeof(struct width_interval), ucs) ? 2 : 1;
 }
References anonymous_namespace{wchar-stubs.cpp}::intable(), anonymous_namespace{wchar-stubs.cpp}::WIDE_EASTASIAN, and anonymous_namespace{wchar-stubs.cpp}::ZERO_WIDTH.
Referenced by assertWidthIs(), and wcswidth().