Fennix Userspace: Userspace/mlibc/options/glibc/include/bits/glibc/glibc_assert.h File Reference
glibc_assert.h File Reference
Macros
#define assert_perror(errno)
Functions
void __assert_fail_perror (int errno, const char *file, unsigned int line, const char *function)
Macro Definition Documentation
assert_perror
#define assert_perror (errno)
Value:
        (!(errno) \
        || (__assert_fail_perror((errno), __FILE__, __LINE__, __func__), 0))
Definition at line 29 of file glibc_assert.h.
Function Documentation
__assert_fail_perror()
void __assert_fail_perror (int errno, const char * file, unsigned int line, const char * function)
Definition at line 8 of file glibc-assert.cpp.
{
     char *errormsg = strerror(errno);
     fprintf(stderr, "In function %s, file %s:%d: Errno '%s' failed!\n",
             function, file, line, errormsg);
     abort();
 }
References abort(), errno, fprintf(), stderr, and strerror().