Fennix: Userspace/musl/src/stat/umask.c File Reference
umask.c File Reference
#include <sys/stat.h>
#include "syscall.h"
Functions
mode_t umask (mode_t mode)
Function Documentation
umask()
mode_t umask (mode_t mode)
Definition at line 4 of file umask.c.
 {
     return syscall(SYS_umask, mode);
 }
References syscall().
Referenced by adduser_main(), bb_make_directory(), bb_parse_mode(), copy_file(), devfsd_main(), getopt_mk_fifo_nod(), make_path(), mdev_main(), mkdir_builtin(), mkdir_recursive(), mkfifo_builtin(), passwd_main(), run_parts_main(), seedrng_main(), umaskcmd(), uuencode_main(), and xmkpath().