Fennix Userspace: Userspace/musl/src/thread/pthread_once.c File Reference
pthread_once.c File Reference
#include "pthread_impl.h"
Functions
static void undo (void *control)
hidden int __pthread_once_full (pthread_once_t *control, void(*init)(void))
int __pthread_once (pthread_once_t *control, void(*init)(void))
weak_alias (__pthread_once, pthread_once)
Function Documentation
__pthread_once()
int __pthread_once (pthread_once_t * control, void(*)(void) init)
Definition at line 39 of file pthread_once.c.
 {
     /* Return immediately if init finished before, but ensure that
      * effects of the init routine are visible to the caller. */
     if (*(volatile int *)control == 2) {
         a_barrier();
         return 0;
     }
     return __pthread_once_full(control, init);
 }
References __pthread_once_full(), a_barrier, and init.
Referenced by call_once().
__pthread_once_full()
hidden int __pthread_once_full (pthread_once_t * control, void(*)(void) init)
Definition at line 11 of file pthread_once.c.
 {
     /* Try to enter initializing state. Four possibilities:
      *  0 - we're the first or the other cancelled; run init
      *  1 - another thread is running init; wait
      *  2 - another thread finished running init; just return
      *  3 - another thread is running init, waiters present; wait */
     for (;;) switch (a_cas(control, 0, 1)) {
     case 0:
         pthread_cleanup_push(undo, control);
         init();
         pthread_cleanup_pop(0);
         if (a_swap(control, 2) == 3)
             __wake(control, -1, 1);
         return 0;
     case 1:
         /* If this fails, so will __wait. */
         a_cas(control, 1, 3);
     case 3:
         __wait(control, 0, 3, 1);
         continue;
     case 2:
         return 0;
     }
 }
References __wait(), __wake(), a_cas, a_swap, init, pthread_cleanup_pop, pthread_cleanup_push, and undo().
Referenced by __pthread_once().
undo()
static void undo (void * control) static
Definition at line 3 of file pthread_once.c.
 {
     /* Wake all waiters, since the waiter status is lost when
      * resetting control to the initial state. */
     if (a_swap(control, 0) == 3)
         __wake(control, -1, 1);
 }
References __wake(), and a_swap.
Referenced by __pthread_once_full().
weak_alias()
weak_alias (__pthread_once , pthread_once)