Fennix: Userspace/mlibc/options/ansi/generic/ctype-stubs.cpp File Reference
ctype-stubs.cpp File Reference
#include <ctype.h>
#include <wctype.h>
#include <bits/ensure.h>
#include <mlibc/charset.hpp>
Namespaces
anonymous_namespace{ctype-stubs.cpp}
Enumerations
enum {
anonymous_namespace{ctype-stubs.cpp}::ct_null , anonymous_namespace{ctype-stubs.cpp}::ct_alnum , anonymous_namespace{ctype-stubs.cpp}::ct_alpha , anonymous_namespace{ctype-stubs.cpp}::ct_blank ,
anonymous_namespace{ctype-stubs.cpp}::ct_cntrl , anonymous_namespace{ctype-stubs.cpp}::ct_digit , anonymous_namespace{ctype-stubs.cpp}::ct_graph , anonymous_namespace{ctype-stubs.cpp}::ct_lower ,
anonymous_namespace{ctype-stubs.cpp}::ct_print , anonymous_namespace{ctype-stubs.cpp}::ct_punct , anonymous_namespace{ctype-stubs.cpp}::ct_space , anonymous_namespace{ctype-stubs.cpp}::ct_upper ,
anonymous_namespace{ctype-stubs.cpp}::ct_xdigit , anonymous_namespace{ctype-stubs.cpp}::ct_count
}
Functions
int isalpha (int nc)
int isdigit (int nc)
int isxdigit (int nc)
int isalnum (int nc)
int ispunct (int nc)
int isgraph (int nc)
int isblank (int nc)
int isspace (int nc)
int isprint (int nc)
int islower (int nc)
int isupper (int nc)
int iscntrl (int nc)
int isascii (int nc)
int iswalpha (wint_t nc)
int iswdigit (wint_t nc)
int iswxdigit (wint_t nc)
int iswalnum (wint_t nc)
int iswpunct (wint_t nc)
int iswgraph (wint_t nc)
int iswblank (wint_t nc)
int iswspace (wint_t nc)
int iswprint (wint_t nc)
int iswlower (wint_t nc)
int iswupper (wint_t nc)
int iswcntrl (wint_t nc)
wctype_t wctype (const char *cs)
int iswctype (wint_t, wctype_t)
int tolower (int nc)
int toupper (int nc)
wint_t towlower (wint_t wc)
wint_t towupper (wint_t wc)
Function Documentation
isalnum()
int isalnum (int nc)
Definition at line 36 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alnum(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_alnum(), and mlibc::null.
Referenced by isalnum_l().
isalpha()
int isalpha (int nc)
Definition at line 12 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alpha(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_alpha(), and mlibc::null.
Referenced by isalpha_l(), and mlibc::lookup_serv_file_port().
isascii()
int isascii (int nc)
Definition at line 108 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return cp <= 0x7F;
 }
References cp, mlibc::current_charcode(), and mlibc::null.
Referenced by isascii_l().
isblank()
int isblank (int nc)
Definition at line 60 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_blank(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_blank(), and mlibc::null.
Referenced by isblank_l().
iscntrl()
int iscntrl (int nc)
Definition at line 100 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::generic_is_control(cp);
 }
References cp, mlibc::current_charcode(), mlibc::generic_is_control(), and mlibc::null.
Referenced by iscntrl_l().
isdigit()
int isdigit (int nc)
Definition at line 20 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_digit(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_digit(), and mlibc::null.
Referenced by do_scanf(), mlibc::char_detail< char >::isDigit(), isdigit_l(), parse_dup_count(), mlibc::strtofp(), and strverscmp().
isgraph()
int isgraph (int nc)
Definition at line 52 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_graph(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_graph(), and mlibc::null.
Referenced by isgraph_l().
islower()
int islower (int nc)
Definition at line 84 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_lower(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_lower(), and mlibc::null.
Referenced by mlibc::char_detail< char >::isLower(), and islower_l().
isprint()
int isprint (int nc)
Definition at line 76 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_print(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_print(), and mlibc::null.
Referenced by isprint_l(), and LoadDefaultCollection().
ispunct()
int ispunct (int nc)
Definition at line 44 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_punct(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_punct(), and mlibc::null.
Referenced by ispunct_l().
isspace()
int isspace (int nc)
Definition at line 68 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_space(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_space(), and mlibc::null.
Referenced by do_scanf(), mlibc::get_nameserver(), GetGameName(), mlibc::char_detail< char >::isSpace(), isspace_l(), LoadResponseFile(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), SplitLine(), anonymous_namespace{time.cpp}::strptime_internal(), and strtoxmax().
isupper()
int isupper (int nc)
Definition at line 92 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_upper(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_upper(), and mlibc::null.
Referenced by mlibc::char_detail< char >::isUpper(), and isupper_l().
iswalnum()
int iswalnum (wint_t nc)
Definition at line 144 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alnum(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_alnum(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswalnum_l().
iswalpha()
int iswalpha (wint_t nc)
Definition at line 120 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alpha(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_alpha(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswalpha_l().
iswblank()
int iswblank (wint_t nc)
Definition at line 168 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_blank(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_blank(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswblank_l().
iswcntrl()
int iswcntrl (wint_t nc)
Definition at line 208 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::generic_is_control(cp);
 }
References cp, mlibc::generic_is_control(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswcntrl_l().
iswctype()
int iswctype (wint_t , wctype_t)
Definition at line 257 of file ctype-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by iswctype_l(), and match_bracket().
iswdigit()
int iswdigit (wint_t nc)
Definition at line 128 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_digit(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_digit(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by mlibc::char_detail< wchar_t >::isDigit(), and iswdigit_l().
iswgraph()
int iswgraph (wint_t nc)
Definition at line 160 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_graph(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_graph(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswgraph_l().
iswlower()
int iswlower (wint_t nc)
Definition at line 192 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_lower(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_lower(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by mlibc::char_detail< wchar_t >::isLower(), and iswlower_l().
iswprint()
int iswprint (wint_t nc)
Definition at line 184 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_print(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_print(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswprint_l().
iswpunct()
int iswpunct (wint_t nc)
Definition at line 152 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_punct(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_punct(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by iswpunct_l().
iswspace()
int iswspace (wint_t nc)
Definition at line 176 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_space(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_space(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by mlibc::char_detail< wchar_t >::isSpace(), and iswspace_l().
iswupper()
int iswupper (wint_t nc)
Definition at line 200 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_upper(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_upper(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by mlibc::char_detail< wchar_t >::isUpper(), and iswupper_l().
iswxdigit()
int iswxdigit (wint_t nc)
Definition at line 136 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_xdigit(cp);
 }
References cp, mlibc::current_charset(), mlibc::charset::is_xdigit(), mlibc::null, and mlibc::platform_wide_charcode().
Referenced by mlibc::char_detail< wchar_t >::isHexDigit(), and iswxdigit_l().
isxdigit()
int isxdigit (int nc)
Definition at line 28 of file ctype-stubs.cpp.
                      {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_xdigit(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_xdigit(), and mlibc::null.
Referenced by mlibc::char_detail< char >::isHexDigit(), and isxdigit_l().
tolower()
int tolower (int nc)
Definition at line 266 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return nc;
     return mlibc::current_charset()->to_lower(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::null, and mlibc::charset::to_lower().
toupper()
int toupper (int nc)
Definition at line 274 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return nc;
     return mlibc::current_charset()->to_upper(cp);
 }
References cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::null, and mlibc::charset::to_upper().
towlower()
wint_t towlower (wint_t wc)
Definition at line 286 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(wc, cp); e != mlibc::charcode_error::null)
         return wc;
     return mlibc::current_charset()->to_lower(cp);
 }
References cp, mlibc::current_charset(), mlibc::null, mlibc::platform_wide_charcode(), and mlibc::charset::to_lower().
Referenced by casefold(), towlower_l(), and wcsncasecmp().
towupper()
wint_t towupper (wint_t wc)
Definition at line 294 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(wc, cp); e != mlibc::charcode_error::null)
         return wc;
     return mlibc::current_charset()->to_upper(cp);
 }
References cp, mlibc::current_charset(), mlibc::null, mlibc::platform_wide_charcode(), and mlibc::charset::to_upper().
Referenced by casefold(), and towupper_l().
wctype()
wctype_t wctype (const char * cs)
Definition at line 239 of file ctype-stubs.cpp.
{
     frg::string_view s{cs};
     if(s == "alnum") return ct_alnum;
     if(s == "alpha") return ct_alpha;
     if(s == "blank") return ct_blank;
     if(s == "cntrl") return ct_cntrl;
     if(s == "digit") return ct_digit;
     if(s == "graph") return ct_graph;
     if(s == "lower") return ct_lower;
     if(s == "print") return ct_print;
     if(s == "punct") return ct_punct;
     if(s == "space") return ct_space;
     if(s == "upper") return ct_upper;
     if(s == "xdigit") return ct_xdigit;
     mlibc::infoLogger() << "mlibc: wctype(\"" << cs << "\") is not supported" << frg::endlog;
     return ct_null;
 }
References anonymous_namespace{ctype-stubs.cpp}::ct_alnum, anonymous_namespace{ctype-stubs.cpp}::ct_alpha, anonymous_namespace{ctype-stubs.cpp}::ct_blank, anonymous_namespace{ctype-stubs.cpp}::ct_cntrl, anonymous_namespace{ctype-stubs.cpp}::ct_digit, anonymous_namespace{ctype-stubs.cpp}::ct_graph, anonymous_namespace{ctype-stubs.cpp}::ct_lower, anonymous_namespace{ctype-stubs.cpp}::ct_null, anonymous_namespace{ctype-stubs.cpp}::ct_print, anonymous_namespace{ctype-stubs.cpp}::ct_punct, anonymous_namespace{ctype-stubs.cpp}::ct_space, anonymous_namespace{ctype-stubs.cpp}::ct_upper, anonymous_namespace{ctype-stubs.cpp}::ct_xdigit, and mlibc::infoLogger.
Referenced by match_bracket(), and wctype_l().