Fennix Kernel: SymbolResolver Namespace Reference
SymbolResolver Namespace Reference
Data Structures
class Symbols
Functions
__no_sanitize ("alignment") void Symbols
Function Documentation
__no_sanitize()
SymbolResolver::__no_sanitize ("alignment")
Definition at line 101 of file symbols.cpp.
     {
         char *sections = r_cst(char *, Sections);
         Elf_Sym *Symbols = nullptr;
         uint8_t *StringAddress = nullptr;
 #if defined(a64) || defined(aa64)
         Elf64_Xword SymbolSize = 0;
         // Elf64_Xword StringSize = 0;
 #elif defined(a32)
         Elf32_Word SymbolSize = 0;
         // Elf32_Word StringSize = 0;
 #endif
         size_t TotalEntries = 0;
         for (size_t i = 0; i < Num; ++i)
         {
             Elf_Shdr *sym = (Elf_Shdr *)&sections[EntSize * i];
             Elf_Shdr *str = (Elf_Shdr *)&sections[EntSize * sym->sh_link];
             if (sym->sh_type == SHT_SYMTAB &&
                 str->sh_type == SHT_STRTAB)
             {
                 Symbols = (Elf_Sym *)sym->sh_addr;
                 StringAddress = (uint8_t *)str->sh_addr;
                 SymbolSize = (int)sym->sh_size;
                 // StringSize = (int)str->sh_size;
                 // TotalEntries = Section.sh_size / sizeof(Elf64_Sym)
                 TotalEntries = sym->sh_size / sym->sh_entsize;
                 trace("Symbol table found, %d entries",
                       SymbolSize / sym->sh_entsize);
                 UNUSED(SymbolSize);
                 break;
             }
         }
         if (Symbols != nullptr && StringAddress != nullptr)
         {
             size_t Index, MinimumIndex;
             for (size_t i = 0; i < TotalEntries - 1; i++)
             {
                 MinimumIndex = i;
                 for (Index = i + 1; Index < TotalEntries; Index++)
                     if (Symbols[Index].st_value < Symbols[MinimumIndex].st_value)
                         MinimumIndex = Index;
                 Elf_Sym tmp = Symbols[MinimumIndex];
                 Symbols[MinimumIndex] = Symbols[i];
                 Symbols[i] = tmp;
             }
             while (Symbols[0].st_value == 0)
             {
                 if (TotalEntries <= 0)
                     break;
                 Symbols++;
                 TotalEntries--;
             }
             if (TotalEntries <= 0)
             {
                 error("Symbol table is empty");
                 return;
             }
             trace("Symbol table loaded, %d entries (%ld KiB)",
                   TotalEntries, TO_KiB(TotalEntries * sizeof(SymbolTable)));
             Elf_Sym *sym;
             const char *name;
             Memory::Virtual vmm;
             for (size_t i = 0, g = TotalEntries; i < g; i++)
             {
                 sym = &Symbols[i];
                 if (!vmm.Check(sym))
                 {
                     error("Symbol %d has invalid address %#lx!",
                           i, sym);
                     debug("Base: %#lx, Symbols[%d]: %#lx, Symbols[%d]: %#lx",
                           Symbols,
                           i - 1, &Symbols[i - 1],
                           i + 1, &Symbols[i + 1]);
                     continue;
                 }
                 name = (const char *)&StringAddress[Symbols[i].st_name];
                 if (!vmm.Check((void *)name))
                 {
                     error("String %d has invalid address %#lx!",
                           i, name);
                     debug("st_name: %d, st_info: %d, st_other: %d, st_shndx: %d, st_value: %d, st_size: %d",
                           sym->st_name, sym->st_info, sym->st_other,
                           sym->st_shndx, sym->st_value, sym->st_size);
                     continue;
                 }
                 if (strlen(name) == 0)
                     continue;
                 SymbolTable tbl{};
                 tbl.Address = sym->st_value;
                 tbl.FunctionName = new char[strlen(name) + 1];
                 strcpy(tbl.FunctionName, name);
                 this->SymTable.push_back(tbl);
                 this->SymbolTableExists = true;
                 // debug("Symbol %d: %#lx %s(%#lx)",
                 //    i, tbl.Address,
                 //    tbl.FunctionName,
                 //    name);
             }
         }
     }
References Memory::Virtual::Check(), debug, error, if(), SHT_STRTAB, SHT_SYMTAB, strcpy, strlen(), TO_KiB, trace, and UNUSED.