Fennix Userspace: Userspace/mlibc/options/glibc/include/err.h File Reference
err.h File Reference
#include <stdarg.h>
Functions
void warn (const char *,...)
void vwarn (const char *, va_list)
void warnx (const char *,...)
void vwarnx (const char *, va_list)
__attribute__ ((__noreturn__)) void err(int
Variables
const char const char va_list
Function Documentation
__attribute__()
__attribute__ ((__noreturn__))
vwarn()
void vwarn (const char * fmt, va_list params)
Definition at line 9 of file err.cpp.
{
     fprintf(stderr, "%s: ", program_invocation_short_name);
     if (fmt) {
         vfprintf(stderr, fmt, params);
                 fwrite(": ", 1, 2, stderr);
     }
     perror(NULL);
 }
References fmt, fprintf(), fwrite(), NULL, params, perror(), program_invocation_short_name, stderr, and vfprintf().
Referenced by __attribute__(), and warn().
vwarnx()
void vwarnx (const char * fmt, va_list params)
Definition at line 18 of file err.cpp.
{
     fprintf(stderr, "%s: ", program_invocation_short_name);
     if (fmt) {
         vfprintf(stderr, fmt, params);
     }
     putc('\n', stderr);
 }
References fmt, fprintf(), params, program_invocation_short_name, putc(), stderr, and vfprintf().
Referenced by warnx().
warn()
void warn (const char * fmt, ...)
Definition at line 38 of file err.cpp.
{
     va_list params;
     va_start(params, fmt);
     vwarn(fmt, params);
     va_end(params);
 }
References fmt, params, va_end(), va_start(), and vwarn().
warnx()
void warnx (const char * fmt, ...)
Definition at line 45 of file err.cpp.
{
     va_list params;
     va_start(params, fmt);
     vwarnx(fmt, params);
     va_end(params);
 }
References fmt, params, va_end(), va_start(), and vwarnx().
Variable Documentation
va_list
const char const char va_list
Definition at line 18 of file err.h.