Fennix: Userspace/musl/src/stdio/__stdio_close.c File Reference
__stdio_close.c File Reference
#include "stdio_impl.h"
#include "aio_impl.h"
Functions
static int dummy (int fd)
weak_alias (dummy, __aio_close)
int __stdio_close (FILE *f)
Function Documentation
__stdio_close()
int __stdio_close (FILE * f)
Definition at line 11 of file __stdio_close.c.
 {
     return syscall(SYS_close, __aio_close(f->fd));
 }
References __aio_close(), f, and syscall().
Referenced by __fdopen(), and __fopen_rb_ca().
dummy()
static int dummy (int fd) static
Definition at line 4 of file __stdio_close.c.
 {
     return fd;
 }
References fd.
weak_alias()
weak_alias (dummy , __aio_close)