Fennix Userspace: Userspace/musl/arch/riscv64/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x) (x)
#define __SYSCALL_LL_O(x) (x)
#define __asm_syscall(...)
#define VDSO_USEFUL
#define IPC_64 0
Functions
static long __syscall0 (long n)
static long __syscall1 (long n, long a)
static long __syscall2 (long n, long a, long b)
static long __syscall3 (long n, long a, long b, long c)
static long __syscall4 (long n, long a, long b, long c, long d)
static long __syscall5 (long n, long a, long b, long c, long d, long e)
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f)
Macro Definition Documentation
__asm_syscall
#define __asm_syscall (...)
Value:
    __asm__ __volatile__ ("ecall\n\t" \
    : "=r"(a0) : __VA_ARGS__ : "memory"); \
    return a0; \
Definition at line 4 of file syscall_arch.h.
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x) (x)
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) (x)
Definition at line 2 of file syscall_arch.h.
IPC_64
#define IPC_64 0
Definition at line 78 of file syscall_arch.h.
VDSO_USEFUL
#define VDSO_USEFUL
Definition at line 73 of file syscall_arch.h.
Function Documentation
__syscall0()
static long __syscall0 (long n) inline static
Definition at line 9 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0");
     __asm_syscall("r"(a7))
 }
References __asm__(), __asm_syscall, a0, a7, and n.
__syscall1()
static long __syscall1 (long n, long a) inline static
Definition at line 16 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0") = a;
     __asm_syscall("r"(a7), "0"(a0))
 }
References __asm__(), __asm_syscall, a0, a7, and n.
__syscall2()
static long __syscall2 (long n, long a, long b) inline static
Definition at line 23 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0") = a;
     register long a1 __asm__("a1") = b;
     __asm_syscall("r"(a7), "0"(a0), "r"(a1))
 }
References __asm__(), __asm_syscall, a0, a1, a7, and n.
__syscall3()
static long __syscall3 (long n, long a, long b, long c) inline static
Definition at line 31 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0") = a;
     register long a1 __asm__("a1") = b;
     register long a2 __asm__("a2") = c;
     __asm_syscall("r"(a7), "0"(a0), "r"(a1), "r"(a2))
 }
References __asm__(), __asm_syscall, a0, a1, a2, a7, c, and n.
__syscall4()
static long __syscall4 (long n, long a, long b, long c, long d) inline static
Definition at line 40 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0") = a;
     register long a1 __asm__("a1") = b;
     register long a2 __asm__("a2") = c;
     register long a3 __asm__("a3") = d;
     __asm_syscall("r"(a7), "0"(a0), "r"(a1), "r"(a2), "r"(a3))
 }
References __asm__(), __asm_syscall, a0, a1, a2, a3, a7, c, and n.
__syscall5()
static long __syscall5 (long n, long a, long b, long c, long d, long e) inline static
Definition at line 50 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0") = a;
     register long a1 __asm__("a1") = b;
     register long a2 __asm__("a2") = c;
     register long a3 __asm__("a3") = d;
     register long a4 __asm__("a4") = e;
     __asm_syscall("r"(a7), "0"(a0), "r"(a1), "r"(a2), "r"(a3), "r"(a4))
 }
References __asm__(), __asm_syscall, a0, a1, a2, a3, a4, a7, c, and n.
__syscall6()
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f) inline static
Definition at line 61 of file syscall_arch.h.
 {
     register long a7 __asm__("a7") = n;
     register long a0 __asm__("a0") = a;
     register long a1 __asm__("a1") = b;
     register long a2 __asm__("a2") = c;
     register long a3 __asm__("a3") = d;
     register long a4 __asm__("a4") = e;
     register long a5 __asm__("a5") = f;
     __asm_syscall("r"(a7), "0"(a0), "r"(a1), "r"(a2), "r"(a3), "r"(a4), "r"(a5))
 }
References __asm__(), __asm_syscall, a0, a1, a2, a3, a4, a5, a7, c, f, and n.