Fennix Kernel: Kernel/kshell/shell.cpp File Reference
shell.cpp File Reference
#include <kshell.hpp>
#include <filesystem.hpp>
#include <module.hpp>
#include <lock.hpp>
#include <debug.h>
#include "../modules/PersonalSystem2/keyboard.hpp"
#include "../kernel.h"
#include "../Fex.hpp"
#include "../mapi.hpp"
#include "cmds.hpp"
Data Structures
struct Command
Functions
NewLock (ShellLock)
char GetLetterFromScanCode (uint8_t ScanCode)
int GetChar ()
void StartKernelShell ()
void KShellThread ()
Variables
const char sc_ascii_low []
const char sc_ascii_high []
static int LowerCase = true
static Command commands []
Function Documentation
GetChar()
int GetChar ()
Definition at line 93 of file shell.cpp.
 {
     return 0;
 }
GetLetterFromScanCode()
char GetLetterFromScanCode (uint8_t ScanCode)
Definition at line 49 of file shell.cpp.
 {
     if (ScanCode & 0x80)
     {
         switch (ScanCode)
         {
         case KEY_U_LSHIFT:
             LowerCase = true;
             return 0;
         case KEY_U_RSHIFT:
             LowerCase = true;
             return 0;
         default:
             return 0;
         }
     }
     else
     {
         switch (ScanCode)
         {
         case KEY_D_RETURN:
             return '\n';
         case KEY_D_LSHIFT:
             LowerCase = false;
             return 0;
         case KEY_D_RSHIFT:
             LowerCase = false;
             return 0;
         case KEY_D_BACKSPACE:
             return ScanCode;
         default:
         {
             if (ScanCode > 0x39)
                 break;
             if (LowerCase)
                 return sc_ascii_low[ScanCode];
             else
                 return sc_ascii_high[ScanCode];
         }
         }
     }
     return 0;
 }
References PS2Keyboard::KEY_D_BACKSPACE, PS2Keyboard::KEY_D_LSHIFT, PS2Keyboard::KEY_D_RETURN, PS2Keyboard::KEY_D_RSHIFT, PS2Keyboard::KEY_U_LSHIFT, PS2Keyboard::KEY_U_RSHIFT, LowerCase, sc_ascii_high, sc_ascii_low, and PS2Keyboard::ScanCode.
Referenced by StartKernelShell().
KShellThread()
void KShellThread ()
Definition at line 418 of file shell.cpp.
 {
     StartKernelShell();
     inf_loop;
 }
References inf_loop, and StartKernelShell().
Referenced by KernelMainThread().
NewLock()
NewLock (ShellLock)
StartKernelShell()
void StartKernelShell ()
Definition at line 141 of file shell.cpp.
 {
     SmartLock(ShellLock);
     debug("Starting kernel shell...");
     printf("Starting kernel shell...\n");
     thisThread->SetPriority(Tasking::TaskPriority::High);
     Display->SetBuffer(0);
     Module::ModuleFile KeyboardModule;
     if (likely(ModuleManager->GetModules().size() > 0))
     {
         foreach (auto Module in ModuleManager->GetModules())
         {
             if (((FexExtended *)Module.ExtendedHeaderAddress)->Module.Type == FexModuleType::FexModuleType_Input &&
                 ((FexExtended *)Module.ExtendedHeaderAddress)->Module.TypeFlags & FexDriverInputTypes::FexDriverInputTypes_Keyboard)
             {
                 KeyboardModule = Module;
                 printf("Using driver \eCA21F6%s\eCCCCCC for keyboard input.\n",
                        ((FexExtended *)Module.ExtendedHeaderAddress)->Module.Name);
                 break;
             }
         }
     }
     Display->SetBuffer(0);
     std::string Buffer;
     std::vector<std::string *> History;
     size_t HistoryIndex = 0;
     bool CtrlDown = false;
     bool TabDoublePress = false;
     while (true)
     {
         size_t BackspaceCount = 0;
         Buffer.clear();
         vfs::Node *cwd = thisProcess->CurrentWorkingDirectory;
         if (!cwd)
             cwd = fs->GetNodeFromPath("/");
         printf("\e34C6EB%s@%s:%s$ \eCCCCCC",
                "kernel",
                "fennix",
                cwd->FullPath);
         Display->SetBuffer(0);
         while (true)
         {
             KernelCallback callback{};
             callback.Reason = PollWaitReason;
             ModuleManager->IOCB(KeyboardModule.modUniqueID, &callback);
             char c = GetLetterFromScanCode(callback.InputCallback.Keyboard.Key);
             switch (callback.InputCallback.Keyboard.Key)
             {
             case KEY_D_LCTRL:
             {
                 CtrlDown = true;
                 continue;
             }
             case KEY_U_LCTRL:
             {
                 CtrlDown = false;
                 continue;
             }
             case KEY_D_BACKSPACE:
             {
                 if (BackspaceCount == 0)
                     continue;
                 Display->Print('\b', 0);
                 Buffer.pop_back();
                 BackspaceCount--;
                 Display->SetBuffer(0);
                 continue;
             }
             case KEY_D_UP:
             {
                 if (History.size() == 0 ||
                     HistoryIndex == 0)
                     continue;
                 HistoryIndex--;
                 for (size_t i = 0; i < Buffer.size(); i++)
                     Display->Print('\b', 0);
                 Display->SetBuffer(0);
                 Buffer = History[HistoryIndex]->c_str();
                 for (size_t i = 0; i < strlen(Buffer.c_str()); i++)
                     Display->Print(Buffer[i], 0);
                 BackspaceCount = Buffer.size();
                 Display->SetBuffer(0);
                 continue;
             }
             case KEY_D_DOWN:
             {
                 if (History.size() == 0 ||
                     HistoryIndex == History.size())
                     continue;
                 if (HistoryIndex == History.size() - 1)
                 {
                     HistoryIndex++;
                     for (size_t i = 0; i < Buffer.size(); i++)
                         Display->Print('\b', 0);
                     BackspaceCount = Buffer.size();
                     Display->SetBuffer(0);
                     continue;
                 }
                 for (size_t i = 0; i < Buffer.size(); i++)
                     Display->Print('\b', 0);
                 Display->SetBuffer(0);
                 HistoryIndex++;
                 Buffer = History[HistoryIndex]->c_str();
                 for (size_t i = 0; i < strlen(Buffer.c_str()); i++)
                     Display->Print(Buffer[i], 0);
                 BackspaceCount = Buffer.size();
                 Display->SetBuffer(0);
                 continue;
             }
             case KEY_D_TAB:
             {
                 if (!TabDoublePress)
                 {
                     TabDoublePress = true;
                     continue;
                 }
                 TabDoublePress = false;
                 if (Buffer.size() == 0)
                 {
                     for (size_t i = 0; i < sizeof(commands) / sizeof(commands[0]); i++)
                     {
                         printf("%s ", commands[i].Name);
                         Display->SetBuffer(0);
                     }
                     Display->Print('\n', 0);
                     Display->SetBuffer(0);
                     goto SecLoopEnd;
                 }
                 for (size_t i = 0; i < Buffer.size(); i++)
                     Display->Print('\b', 0);
                 Display->SetBuffer(0);
                 for (size_t i = 0; i < sizeof(commands) / sizeof(commands[0]); i++)
                 {
                     if (strncmp(Buffer.c_str(), commands[i].Name, Buffer.size()) == 0)
                     {
                         Buffer = commands[i].Name;
                         for (size_t i = 0; i < strlen(Buffer.c_str()); i++)
                             Display->Print(Buffer[i], 0);
                         BackspaceCount = Buffer.size();
                         Display->SetBuffer(0);
                         break;
                     }
                 }
                 continue;
             }
             default:
                 break;
             }
             if (c == 0)
                 continue;
             if (CtrlDown)
             {
                 switch (std::toupper((char)c))
                 {
                 case 'C':
                 {
                     Display->Print('^', 0);
                     Display->Print('C', 0);
                     Display->Print('\n', 0);
                     fixme("No SIGINT handler yet.");
                     Display->SetBuffer(0);
                     goto SecLoopEnd;
                 }
                 case 'D':
                 {
                     Display->Print('^', 0);
                     Display->Print('D', 0);
                     Display->Print('\n', 0);
                     fixme("No SIGKILL handler yet.");
                     Display->SetBuffer(0);
                     goto SecLoopEnd;
                 }
                 default:
                     continue;
                 }
             }
             Display->Print(c, 0);
             if (c == '\n')
             {
                 if (Buffer.length() > 0)
                 {
                     std::string *hBuff = new std::string(Buffer.c_str());
                     History.push_back(hBuff);
                     HistoryIndex = History.size();
                 }
                 break;
             }
             Buffer += c;
             BackspaceCount++;
             Display->SetBuffer(0);
         }
     SecLoopEnd:
         if (Buffer.length() == 0)
             continue;
         bool Found = false;
         for (size_t i = 0; i < sizeof(commands) / sizeof(Command); i++)
         {
             std::string cmd_extracted;
             for (size_t i = 0; i < Buffer.length(); i++)
             {
                 if (Buffer[i] == ' ')
                     break;
                 cmd_extracted += Buffer[i];
             }
             debug("cmd: %s, array[%d]: %s", cmd_extracted.c_str(), i, commands[i].Name);
             if (strncmp(commands[i].Name, cmd_extracted.c_str(), cmd_extracted.size()) == 0)
             {
                 if (strlen(commands[i].Name) != cmd_extracted.size())
                     continue;
                 Found = true;
                 std::string arg_only;
                 const char *cmd_name = commands[i].Name;
                 for (size_t i = strlen(cmd_name) + 1; i < Buffer.length(); i++)
                     arg_only += Buffer[i];
                 if (commands[i].Function)
                     commands[i].Function(arg_only.c_str());
                 else
                 {
                     std::string cmd_only;
                     for (size_t i = 0; i < Buffer.length(); i++)
                     {
                         if (Buffer[i] == ' ')
                             break;
                         cmd_only += Buffer[i];
                     }
                     printf("%s: command not implemented\n",
                            cmd_only.c_str());
                 }
                 break;
             }
         }
         if (!Found)
         {
             std::string cmd_only;
             for (size_t i = 0; i < Buffer.length(); i++)
             {
                 if (Buffer[i] == ' ')
                     break;
                 cmd_only += Buffer[i];
             }
             printf("%s: command not found\n",
                    cmd_only.c_str());
         }
     }
 }
References std::string::c_str(), std::string::clear(), commands, debug, Display, FexDriverInputTypes_Keyboard, FexModuleType_Input, fixme, fs, vfs::Node::FullPath, Command::Function, GetLetterFromScanCode(), Module::Module::GetModules(), vfs::Virtual::GetNodeFromPath(), Tasking::High, Module::Module::IOCB(), PS2Keyboard::KEY_D_BACKSPACE, PS2Keyboard::KEY_D_DOWN, PS2Keyboard::KEY_D_LCTRL, PS2Keyboard::KEY_D_TAB, PS2Keyboard::KEY_D_UP, PS2Keyboard::KEY_U_LCTRL, std::string::length(), likely, Module, ModuleManager, Module::ModuleFile::modUniqueID, CPU::Name(), Command::Name, PollWaitReason, std::string::pop_back(), Video::Display::Print(), printf, Video::Display::SetBuffer(), std::string::size(), strlen(), strncmp(), thisProcess, thisThread, and std::toupper().
Referenced by KShellThread().
Variable Documentation
commands
Command commands[] static
Definition at line 104 of file shell.cpp.
Referenced by StartKernelShell().
LowerCase
int LowerCase = true static
Definition at line 47 of file shell.cpp.
Referenced by GetLetterFromScanCode().
sc_ascii_high
const char sc_ascii_high[]
Initial value:
= {'?', '?', '!', '@', '#', '$', '%', '^',
                              '&', '*', '(', ')', '_', '+', '?', '?', 'Q', 'W', 'E', 'R', 'T', 'Y',
                              'U', 'I', 'O', 'P', '{', '}', '?', '?', 'A', 'S', 'D', 'F', 'G',
                              'H', 'J', 'K', 'L', ':', '\"', '~', '?', '|', 'Z', 'X', 'C', 'V',
                              'B', 'N', 'M', '<', '>', '?', '?', '?', '?', ' '}
Definition at line 41 of file shell.cpp.
Referenced by GetLetterFromScanCode().
sc_ascii_low
const char sc_ascii_low[]
Initial value:
= {'?', '?', '1', '2', '3', '4', '5', '6',
                             '7', '8', '9', '0', '-', '=', '?', '?', 'q', 'w', 'e', 'r', 't', 'y',
                             'u', 'i', 'o', 'p', '[', ']', '?', '?', 'a', 's', 'd', 'f', 'g',
                             'h', 'j', 'k', 'l', ';', '\'', '`', '?', '\\', 'z', 'x', 'c', 'v',
                             'b', 'n', 'm', ',', '.', '/', '?', '?', '?', ' '}
Definition at line 35 of file shell.cpp.
Referenced by GetLetterFromScanCode().