Fennix: Drivers/audio/hda/hda.cpp File Reference
hda.cpp File Reference
#include <errno.h>
#include <audio.h>
#include <regs.h>
#include <base.h>
#include <pci.h>
#include <io.h>
#include <fs.h>
#include "hda.hpp"
Data Structures
class HDADevice
Macros
#define OIR(x) OIR_##x
#define CREATE_OIR(x) void OIR_##x(TrapFrame *f) { Drivers[x]->OnInterruptReceived(f); }
Functions
CREATE_OIR (0)
CREATE_OIR (1)
CREATE_OIR (2)
CREATE_OIR (3)
int __fs_Open (struct Inode *, int, mode_t)
int __fs_Close (struct Inode *)
ssize_t __fs_Read (struct Inode *, void *, size_t, off_t)
ssize_t __fs_Write (struct Inode *Node, const void *Buffer, size_t Size, off_t)
int __fs_Ioctl (struct Inode *Node, unsigned long Request, void *Argp)
EXTERNC int cxx_Panic ()
EXTERNC int cxx_Probe ()
EXTERNC int cxx_Initialize ()
EXTERNC int cxx_Finalize ()
Variables
HDADevice * Drivers [4] = {nullptr}
dev_t AudioID [4] = {(dev_t)-1}
const struct InodeOperations AudioOps
PCIArray * Devices
Macro Definition Documentation
CREATE_OIR
#define CREATE_OIR (x) void OIR_##x(TrapFrame *f) { Drivers[x]->OnInterruptReceived(f); }
Definition at line 82 of file hda.cpp.
OIR
#define OIR (x) OIR_##x
Definition at line 81 of file hda.cpp.
Function Documentation
__fs_Close()
int __fs_Close (struct Inode *)
Definition at line 91 of file hda.cpp.
 { return 0; }
__fs_Ioctl()
int __fs_Ioctl (struct Inode * Node, unsigned long Request, void * Argp)
Definition at line 99 of file hda.cpp.
 {
     return Drivers[AudioID[Node->GetMinor()]]->ioctl((AudioIoctl)Request, Argp);
 }
References AudioID, Drivers, HDADevice::ioctl(), and Driver::Node.
__fs_Open()
int __fs_Open (struct Inode * , int , mode_t)
Definition at line 90 of file hda.cpp.
 { return 0; }
__fs_Read()
ssize_t __fs_Read (struct Inode * , void * , size_t , off_t)
Definition at line 92 of file hda.cpp.
 { return 0; }
__fs_Write()
ssize_t __fs_Write (struct Inode * Node, const void * Buffer, size_t Size, off_t)
Definition at line 94 of file hda.cpp.
 {
     return Drivers[AudioID[Node->GetMinor()]]->write((uint8_t *)Buffer, Size);
 }
References AudioID, Buffer, Drivers, Driver::Node, Driver::Size, and HDADevice::write().
CREATE_OIR() [1/4]
CREATE_OIR (0)
CREATE_OIR() [2/4]
CREATE_OIR (1)
CREATE_OIR() [3/4]
CREATE_OIR (2)
CREATE_OIR() [4/4]
CREATE_OIR (3)
cxx_Finalize()
EXTERNC int cxx_Finalize ()
Definition at line 231 of file hda.cpp.
 {
     PCIArray *ctx = Devices;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count++ > sizeof(Drivers) / sizeof(HDADevice *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type == 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         delete Drivers[Count++];
         ctx = (PCIArray *)ctx->Next;
     }
     for (size_t i = 0; i < sizeof(AudioID) / sizeof(dev_t); i++)
     {
         if (AudioID[i] != (dev_t)-1)
             UnregisterDevice(AudioID[i]);
     }
     return 0;
 }
References AudioID, dev_t, Devices, Drivers, i, if(), KernelLog(), and v0::UnregisterDevice().
cxx_Initialize()
EXTERNC int cxx_Initialize ()
Definition at line 188 of file hda.cpp.
 {
     PCIArray *ctx = Devices;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count > sizeof(Drivers) / sizeof(HDADevice *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type == 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         InitializePCI(ctx->Device);
         Drivers[Count] = new HDADevice((PCIHeader0 *)ctx->Device->Header);
         if (Drivers[Count]->IsInitialized())
         {
             dev_t ret = RegisterDevice(AUDIO_TYPE_PCM, &AudioOps);
             AudioID[Count] = ret;
             Count++;
         }
         ctx = (PCIArray *)ctx->Next;
     }
     if (Count == 0)
     {
         KernelLog("No valid HDA device found.");
         return -EINVAL;
     }
     return 0;
 }
References AUDIO_TYPE_PCM, AudioID, AudioOps, dev_t, Devices, Drivers, EINVAL, if(), v0::InitializePCI(), KernelLog(), v0::RegisterDevice(), and ret.
cxx_Panic()
EXTERNC int cxx_Panic ()
Definition at line 125 of file hda.cpp.
 {
     PCIArray *ctx = Devices;
     short Count = 0;
     while (ctx != nullptr)
     {
         if (Drivers[Count] != nullptr)
             Drivers[Count]->Panic();
         Count++;
         ctx = (PCIArray *)ctx->Next;
     }
     return 0;
 }
References Devices, Drivers, and HDADevice::Panic().
cxx_Probe()
EXTERNC int cxx_Probe ()
Definition at line 140 of file hda.cpp.
 {
     uint16_t VendorIDs[] = {0x8086, /* Intel */
                             0x15AD, /* VMware */
                             PCI_END};
     uint16_t DeviceIDs[] = {0x9D71 /* Sunrise Point-LP HD Audio */,
                             0x2668 /* ICH6 */,
                             0x293E /* ICH9 */,
                             PCI_END};
     Devices = GetPCIDevices(VendorIDs, DeviceIDs);
     if (Devices == nullptr)
     {
         KernelLog("No HDA device found.");
         return -ENODEV;
     }
     PCIArray *ctx = Devices;
     bool Found = false;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count++ > sizeof(Drivers) / sizeof(HDADevice *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type == 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         Found = true;
         ctx = (PCIArray *)ctx->Next;
     }
     if (!Found)
     {
         KernelLog("No valid HDA device found.");
         return -EINVAL;
     }
     return 0;
 }
References Devices, Drivers, EINVAL, ENODEV, v0::GetPCIDevices(), if(), KernelLog(), and PCI_END.
Variable Documentation
AudioID
dev_t AudioID[4] = {(dev_t)-1}
Definition at line 79 of file hda.cpp.
Referenced by __fs_Ioctl(), __fs_Write(), cxx_Finalize(), and cxx_Initialize().
AudioOps
const struct InodeOperations AudioOps
Initial value:
= {
    .Lookup = nullptr,
    .Create = nullptr,
    .Remove = nullptr,
    .Rename = nullptr,
    .Read = __fs_Read,
    .Write = __fs_Write,
    .Truncate = nullptr,
    .Open = __fs_Open,
    .Close = __fs_Close,
    .Ioctl = __fs_Ioctl,
    .ReadDir = nullptr,
    .MkDir = nullptr,
    .RmDir = nullptr,
    .SymLink = nullptr,
    .ReadLink = nullptr,
    .Seek = nullptr,
    .Stat = nullptr,
}
Definition at line 99 of file hda.cpp.
Referenced by cxx_Initialize().
Devices
PCIArray* Devices
Definition at line 124 of file hda.cpp.
Referenced by cxx_Finalize(), cxx_Initialize(), cxx_Panic(), and cxx_Probe().
Drivers
HDADevice* Drivers[4] = {nullptr}
Definition at line 78 of file hda.cpp.
Referenced by __fs_Ioctl(), __fs_Write(), cxx_Finalize(), cxx_Initialize(), cxx_Panic(), and cxx_Probe().