Fennix Userspace: Userspace/musl/src/termios/tcsetattr.c File Reference
tcsetattr.c File Reference
#include <termios.h>
#include <sys/ioctl.h>
#include <errno.h>
Functions
int tcsetattr (int fd, int act, const struct termios *tio)
Function Documentation
tcsetattr()
int tcsetattr (int fd, int act, const struct termios * tio)
Definition at line 5 of file tcsetattr.c.
 {
     if (act < 0 || act > 2) {
         errno = EINVAL;
         return -1;
     }
     return ioctl(fd, TCSETS+act, tio);
 }
References act(), EINVAL, errno, fd, ioctl(), TCSETS, and tio.
Referenced by bb_ask_noecho(), chat_main(), cleanup(), conf_cleanup(), cookmode(), DisableInputBuffering(), EnableInputBuffering(), getch_nowait(), getpass(), main(), microcom_main(), onintr(), openpty(), process_line(), rawmode(), resize_main(), rx_main(), script_main(), set_new_line_discipline(), set_termios_to_raw(), set_tty_cooked(), set_tty_state(), shell_builtin_read(), stty_main(), tcsetattr_serial_or_warn(), tcsetattr_stdin_TCSANOW(), tcsetattr_tty_TCSANOW(), ttsetattr(), and xset1().