Fennix: Userspace/apps/base/busybox/util-linux/volume_id/volume_id.c File Reference
volume_id.c File Reference
#include "volume_id_internal.h"
Macros
#define ENABLE_FEATURE_VOLUMEID_MAC 0
#define ENABLE_FEATURE_VOLUMEID_HIGHPOINTRAID 0
#define ENABLE_FEATURE_VOLUMEID_ISWRAID 0
#define ENABLE_FEATURE_VOLUMEID_LSIRAID 0
#define ENABLE_FEATURE_VOLUMEID_LVM 0
#define ENABLE_FEATURE_VOLUMEID_NVIDIARAID 0
#define ENABLE_FEATURE_VOLUMEID_PROMISERAID 0
#define ENABLE_FEATURE_VOLUMEID_SILICONRAID 0
#define ENABLE_FEATURE_VOLUMEID_VIARAID 0
#define ENABLE_FEATURE_VOLUMEID_HPFS 0
#define ENABLE_FEATURE_VOLUMEID_UFS 0
Typedefs
typedef int FAST_FUNC(* raid_probe_fptr) (struct volume_id *id, uint64_t size)
typedef int FAST_FUNC(* probe_fptr) (struct volume_id *id)
Functions
int FAST_FUNC volume_id_probe_all (struct volume_id *id, uint64_t size)
struct volume_id *FAST_FUNC volume_id_open_node (int fd)
void FAST_FUNC free_volume_id (struct volume_id *id)
Variables
static const raid_probe_fptr raid1[] ALIGN_PTR
Macro Definition Documentation
ENABLE_FEATURE_VOLUMEID_HIGHPOINTRAID
#define ENABLE_FEATURE_VOLUMEID_HIGHPOINTRAID 0
Definition at line 35 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_HPFS
#define ENABLE_FEATURE_VOLUMEID_HPFS 0
Definition at line 45 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_ISWRAID
#define ENABLE_FEATURE_VOLUMEID_ISWRAID 0
Definition at line 36 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_LSIRAID
#define ENABLE_FEATURE_VOLUMEID_LSIRAID 0
Definition at line 37 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_LVM
#define ENABLE_FEATURE_VOLUMEID_LVM 0
Definition at line 38 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_MAC
#define ENABLE_FEATURE_VOLUMEID_MAC 0
Definition at line 30 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_NVIDIARAID
#define ENABLE_FEATURE_VOLUMEID_NVIDIARAID 0
Definition at line 39 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_PROMISERAID
#define ENABLE_FEATURE_VOLUMEID_PROMISERAID 0
Definition at line 40 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_SILICONRAID
#define ENABLE_FEATURE_VOLUMEID_SILICONRAID 0
Definition at line 41 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_UFS
#define ENABLE_FEATURE_VOLUMEID_UFS 0
Definition at line 46 of file volume_id.c.
ENABLE_FEATURE_VOLUMEID_VIARAID
#define ENABLE_FEATURE_VOLUMEID_VIARAID 0
Definition at line 42 of file volume_id.c.
Typedef Documentation
probe_fptr
typedef int FAST_FUNC(* probe_fptr) (struct volume_id *id)
Definition at line 50 of file volume_id.c.
raid_probe_fptr
typedef int FAST_FUNC(* raid_probe_fptr) (struct volume_id *id, uint64_t size)
Definition at line 49 of file volume_id.c.
Function Documentation
free_volume_id()
void FAST_FUNC free_volume_id (struct volume_id * id)
Definition at line 259 of file volume_id.c.
 {
     if (id == NULL)
         return;
     //if (id->fd_close != 0) - always true
         close(id->fd);
     volume_id_free_buffer(id);
 #ifdef UNUSED_PARTITION_CODE
     free(id->partitions);
 #endif
     free(id);
 }
References close(), volume_id::fd, free, NULL, and volume_id_free_buffer().
Referenced by get_label_uuid().
volume_id_open_node()
struct volume_id* FAST_FUNC volume_id_open_node (int fd)
close fd on device close *‍/
Definition at line 226 of file volume_id.c.
 {
     struct volume_id *id;
     id = xzalloc(sizeof(struct volume_id));
     id->fd = fd;
     //id->fd_close = 1;
     return id;
 }
References fd, and xzalloc().
Referenced by get_label_uuid().
volume_id_probe_all()
int FAST_FUNC volume_id_probe_all (struct volume_id * id, uint64_t size)
Definition at line 181 of file volume_id.c.
 {
     unsigned i;
     /* probe for raid first, cause fs probes may be successful on raid members */
     if (size) {
         for (i = 0; i < ARRAY_SIZE(raid1); i++) {
             if (raid1[i](id, /*off,*/ size) == 0)
                 goto ret;
             if (id->error)
                 goto ret;
         }
     }
     for (i = 0; i < ARRAY_SIZE(raid2); i++) {
         if (raid2[i](id /*,off*/) == 0)
             goto ret;
         if (id->error)
             goto ret;
     }
     /* signature in the first block, only small buffer needed */
     for (i = 0; i < ARRAY_SIZE(fs1); i++) {
         if (fs1[i](id /*,off*/) == 0)
             goto ret;
         if (id->error)
             goto ret;
     }
     /* fill buffer with maximum */
     volume_id_get_buffer(id, 0, SB_BUFFER_SIZE);
     for (i = 0; i < ARRAY_SIZE(fs2); i++) {
         if (fs2[i](id /*,off*/) == 0)
             goto ret;
         if (id->error)
             goto ret;
     }
  ret:
     volume_id_free_buffer(id);
     return (- id->error); /* 0 or -1 */
 }
References ARRAY_SIZE, volume_id::error, i, SB_BUFFER_SIZE, size, volume_id_free_buffer(), and volume_id_get_buffer().
Referenced by get_label_uuid().
Variable Documentation
ALIGN_PTR
const probe_fptr fs2 [] ALIGN_PTR static
Initial value:
= {
}
Definition at line 52 of file volume_id.c.