Fennix: Userspace/apps/base/bash/examples/loadables/cat.c File Reference
cat.c File Reference
#include <fcntl.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
Functions
char * strerror ()
char ** make_builtin_argv ()
static int fcopy (int fd, char *fn)
int cat_main (int argc, char **argv)
int cat_builtin (WORD_LIST *list)
Variables
int errno
char * cat_doc []
struct builtin cat_struct
Function Documentation
cat_builtin()
int cat_builtin (WORD_LIST * list)
Definition at line 108 of file cat.c.
 {
     char    **v;
     int c, r;
     v = make_builtin_argv(list, &c);
     QUIT;
     r = cat_main(c, v);
     free(v);
     return r;
 }
References c, cat_main(), free, make_builtin_argv(), QUIT, and r.
cat_main()
int cat_main (int argc, char ** argv)
Definition at line 73 of file cat.c.
 {
     int i, fd, r;
     char    *s;
     if (argc == 1)
         return (fcopy(0, "standard input"));
     for (i = r = 1; i < argc; i++) {
         QUIT;
         if (argv[i][0] == '-' && argv[i][1] == '\0')
             fd = 0;
         else {
             fd = open(argv[i], O_RDONLY, 0666);
             if (fd < 0) {
                 s = strerror(errno);
                 write(2, "cat: cannot open ", 17);
                 write(2, argv[i], strlen(argv[i]));
                 write(2, ": ", 2);
                 write(2, s, strlen(s));
                 write(2, "\n", 1);
                 continue;
             }
         }
         r = fcopy(fd, argv[i]);
         if (fd != 0)
             close(fd);
     }
     QUIT;
     return (r);
 }
References argc, argv, close(), errno, fcopy(), i, O_RDONLY, open(), QUIT, r, strerror(), strlen(), and write().
Referenced by cat_builtin().
fcopy()
static int fcopy (int fd, char * fn) static
Definition at line 39 of file cat.c.
 {
     char    buf[4096], *s;
     int n, w, e;
     while (n = read(fd, buf, sizeof (buf))) {
         if (n < 0) {
             e = errno;
             write(2, "cat: read error: ", 18);
             write(2, fn, strlen(fn));
             write(2, ": ", 2);
             s = strerror(e);
             write(2, s, strlen(s));
             write(2, "\n", 1);
             return 1;
         }
         QUIT;
         w = write(1, buf, n);
         if (w != n) {
             e = errno;
             write(2, "cat: write error: ", 18);
             s = strerror(e);
             write(2, s, strlen(s));
             write(2, "\n", 1);
             return 1;
         }
         QUIT;
     }
     return 0;
 }
References buf, errno, n, QUIT, read(), strerror(), strlen(), and write().
Referenced by cat_main().
make_builtin_argv()
char** make_builtin_argv ()
Referenced by cat_builtin().
strerror()
char* strerror ()
Referenced by cat_main(), and fcopy().
Variable Documentation
cat_doc
char* cat_doc[]
Initial value:
= {
    "Display files.",
    "",
    "Read each FILE and display it on the standard output.   If any",
    "FILE is `-' or if no FILE argument is given, the standard input",
    "is read.",
    (char *)0
}
Definition at line 122 of file cat.c.
cat_struct
struct builtin cat_struct
Initial value:
= {
    "cat",
    cat_builtin,
    BUILTIN_ENABLED,
    cat_doc,
    "cat [-] [file ...]",
    0
}
Definition at line 122 of file cat.c.
errno
int errno extern
Referenced by cat_main(), and fcopy().