Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/z_zone.c File Reference
z_zone.c File Reference
#include "z_zone.h"
#include "i_system.h"
#include "doomtype.h"
Data Structures
struct memblock_s
struct memzone_t
Macros
#define MEM_ALIGN sizeof(void *)
#define ZONEID 0x1d4a11
#define MINFRAGMENT 64
Typedefs
typedef struct memblock_s memblock_t
Functions
void Z_ClearZone (memzone_t *zone)
void Z_Init (void)
void Z_Free (void *ptr)
void * Z_Malloc (int size, int tag, void *user)
void Z_FreeTags (int lowtag, int hightag)
void Z_DumpHeap (int lowtag, int hightag)
void Z_FileDumpHeap (FILE *f)
void Z_CheckHeap (void)
void Z_ChangeTag2 (void *ptr, int tag, char *file, int line)
void Z_ChangeUser (void *ptr, void **user)
int Z_FreeMemory (void)
unsigned int Z_ZoneSize (void)
Variables
memzone_t * mainzone
Data Structure Documentation
memblock_s
struct memblock_s
Definition at line 39 of file z_zone.c.
Data Fields
int id
struct memblock_s * next
struct memblock_s * prev
int size
int tag
void ** user
memzone_t
struct memzone_t
Definition at line 50 of file z_zone.c.
Data Fields
memblock_t blocklist
memblock_t * rover
int size
Macro Definition Documentation
MEM_ALIGN
#define MEM_ALIGN sizeof(void *)
Definition at line 36 of file z_zone.c.
MINFRAGMENT
#define MINFRAGMENT 64
Definition at line 181 of file z_zone.c.
ZONEID
#define ZONEID 0x1d4a11
Definition at line 37 of file z_zone.c.
Typedef Documentation
memblock_t
typedef struct memblock_s memblock_t
Function Documentation
Z_ChangeTag2()
void Z_ChangeTag2 (void * ptr, int tag, char * file, int line)
Definition at line 429 of file z_zone.c.
 {
     memblock_t* block;
     block = (memblock_t *) ((byte *)ptr - sizeof(memblock_t));
     if (block->id != ZONEID)
         I_Error("%s:%i: Z_ChangeTag: block without a ZONEID!",
                 file, line);
     if (tag >= PU_PURGELEVEL && block->user == NULL)
         I_Error("%s:%i: Z_ChangeTag: an owner is required "
                 "for purgable blocks", file, line);
     block->tag = tag;
 }
References I_Error(), memblock_s::id, NULL, PU_PURGELEVEL, memblock_s::tag, memblock_s::user, and ZONEID.
Z_ChangeUser()
void Z_ChangeUser (void * ptr, void ** user)
Definition at line 446 of file z_zone.c.
 {
     memblock_t* block;
     block = (memblock_t *) ((byte *)ptr - sizeof(memblock_t));
     if (block->id != ZONEID)
     {
         I_Error("Z_ChangeUser: Tried to change user for invalid block!");
     }
     block->user = user;
     *user = ptr;
 }
References I_Error(), memblock_s::id, memblock_s::user, and ZONEID.
Referenced by ExtendLumpInfo().
Z_CheckHeap()
void Z_CheckHeap (void)
Definition at line 400 of file z_zone.c.
 {
     memblock_t* block;
     for (block = mainzone->blocklist.next ; ; block = block->next)
     {
     if (block->next == &mainzone->blocklist)
     {
         // all blocks have been hit
         break;
     }
     if ( (byte *)block + block->size != (byte *)block->next)
         I_Error ("Z_CheckHeap: block size does not touch the next block\n");
     if ( block->next->prev != block)
         I_Error ("Z_CheckHeap: next block doesn't have proper back link\n");
     if (block->tag == PU_FREE && block->next->tag == PU_FREE)
         I_Error ("Z_CheckHeap: two consecutive free blocks\n");
     }
 }
References memzone_t::blocklist, I_Error(), mainzone, memblock_s::next, memblock_s::prev, PU_FREE, memblock_s::size, and memblock_s::tag.
Referenced by G_DoLoadLevel().
Z_ClearZone()
void Z_ClearZone (memzone_t * zone)
Definition at line 71 of file z_zone.c.
 {
     memblock_t*     block;
     // set the entire zone to one free block
     zone->blocklist.next =
     zone->blocklist.prev =
     block = (memblock_t *)( (byte *)zone + sizeof(memzone_t) );
     zone->blocklist.user = (void *)zone;
     zone->blocklist.tag = PU_STATIC;
     zone->rover = block;
     block->prev = block->next = &zone->blocklist;
     // a free block.
     block->tag = PU_FREE;
     block->size = zone->size - sizeof(memzone_t);
 }
References memzone_t::blocklist, memblock_s::next, memblock_s::prev, PU_FREE, PU_STATIC, memzone_t::rover, memblock_s::size, memzone_t::size, memblock_s::tag, and memblock_s::user.
Z_DumpHeap()
void Z_DumpHeap (int lowtag, int hightag)
Definition at line 328 of file z_zone.c.
 {
     memblock_t* block;
     printf ("zone size: %i  location: %p\n",
         mainzone->size,mainzone);
     printf ("tag range: %i to %i\n",
         lowtag, hightag);
     for (block = mainzone->blocklist.next ; ; block = block->next)
     {
     if (block->tag >= lowtag && block->tag <= hightag)
         printf ("block:%p    size:%7i    user:%p    tag:%3i\n",
             block, block->size, block->user, block->tag);
     if (block->next == &mainzone->blocklist)
     {
         // all blocks have been hit
         break;
     }
     if ( (byte *)block + block->size != (byte *)block->next)
         printf ("ERROR: block size does not touch the next block\n");
     if ( block->next->prev != block)
         printf ("ERROR: next block doesn't have proper back link\n");
     if (block->tag == PU_FREE && block->next->tag == PU_FREE)
         printf ("ERROR: two consecutive free blocks\n");
     }
 }
References memzone_t::blocklist, mainzone, memblock_s::next, memblock_s::prev, printf, PU_FREE, memblock_s::size, memzone_t::size, memblock_s::tag, and memblock_s::user.
Z_FileDumpHeap()
void Z_FileDumpHeap (FILE * f)
Definition at line 367 of file z_zone.c.
 {
     memblock_t* block;
     fprintf (f,"zone size: %i  location: %p\n",mainzone->size,mainzone);
     for (block = mainzone->blocklist.next ; ; block = block->next)
     {
     fprintf (f,"block:%p    size:%7i    user:%p    tag:%3i\n",
          block, block->size, block->user, block->tag);
     if (block->next == &mainzone->blocklist)
     {
         // all blocks have been hit
         break;
     }
     if ( (byte *)block + block->size != (byte *)block->next)
         fprintf (f,"ERROR: block size does not touch the next block\n");
     if ( block->next->prev != block)
         fprintf (f,"ERROR: next block doesn't have proper back link\n");
     if (block->tag == PU_FREE && block->next->tag == PU_FREE)
         fprintf (f,"ERROR: two consecutive free blocks\n");
     }
 }
References memzone_t::blocklist, fprintf(), mainzone, memblock_s::next, memblock_s::prev, PU_FREE, memblock_s::size, memzone_t::size, memblock_s::tag, and memblock_s::user.
Z_Free()
void Z_Free (void * ptr)
Definition at line 126 of file z_zone.c.
 {
     memblock_t*     block;
     memblock_t*     other;
     block = (memblock_t *) ( (byte *)ptr - sizeof(memblock_t));
     if (block->id != ZONEID)
     I_Error ("Z_Free: freed a pointer without ZONEID");
     if (block->tag != PU_FREE && block->user != NULL)
     {
         // clear the user's mark
         *block->user = 0;
     }
     // mark as free
     block->tag = PU_FREE;
     block->user = NULL;
     block->id = 0;
     other = block->prev;
     if (other->tag == PU_FREE)
     {
         // merge with previous free block
         other->size += block->size;
         other->next = block->next;
         other->next->prev = other;
         if (block == mainzone->rover)
             mainzone->rover = other;
         block = other;
     }
     other = block->next;
     if (other->tag == PU_FREE)
     {
         // merge the next free block onto the end
         block->size += other->size;
         block->next = other->next;
         block->next->prev = block;
         if (other == mainzone->rover)
             mainzone->rover = block;
     }
 }
References I_Error(), memblock_s::id, mainzone, memblock_s::next, NULL, memblock_s::prev, PU_FREE, memzone_t::rover, memblock_s::size, memblock_s::tag, memblock_s::user, and ZONEID.
Referenced by G_CheckDemoStatus(), GUS_WriteConfig(), I_ResetScaleTables(), I_ShutdownGraphics(), IncreaseDemoBuffer(), mem_fclose(), mem_fwrite(), P_RunThinkers(), P_UnArchiveThinkers(), R_FillBackScreen(), R_GenerateLookup(), R_InitTextures(), R_PrecacheLevel(), W_AddFile(), W_GenerateHashTable(), W_StdC_CloseFile(), wipe_exitMelt(), wipe_shittyColMajorXform(), WritePCXfile(), Z_FreeTags(), and Z_Malloc().
Z_FreeMemory()
int Z_FreeMemory (void)
Definition at line 466 of file z_zone.c.
 {
     memblock_t*     block;
     int         free;
     free = 0;
     for (block = mainzone->blocklist.next ;
          block != &mainzone->blocklist;
          block = block->next)
     {
         if (block->tag == PU_FREE || block->tag >= PU_PURGELEVEL)
             free += block->size;
     }
     return free;
 }
References memzone_t::blocklist, free(), mainzone, memblock_s::next, PU_FREE, PU_PURGELEVEL, memblock_s::size, and memblock_s::tag.
Z_FreeTags()
void Z_FreeTags (int lowtag, int hightag)
Definition at line 298 of file z_zone.c.
 {
     memblock_t* block;
     memblock_t* next;
     for (block = mainzone->blocklist.next ;
      block != &mainzone->blocklist ;
      block = next)
     {
     // get link before freeing
     next = block->next;
     // free block?
     if (block->tag == PU_FREE)
         continue;
     if (block->tag >= lowtag && block->tag <= hightag)
         Z_Free ( (byte *)block+sizeof(memblock_t));
     }
 }
References memzone_t::blocklist, mainzone, memblock_s::next, PU_FREE, memblock_s::tag, and Z_Free().
Referenced by P_SetupLevel().
Z_Init()
void Z_Init (void)
Definition at line 97 of file z_zone.c.
 {
     memblock_t* block;
     int     size;
     mainzone = (memzone_t *)I_ZoneBase (&size);
     mainzone->size = size;
     // set the entire zone to one free block
     mainzone->blocklist.next =
     mainzone->blocklist.prev =
     block = (memblock_t *)( (byte *)mainzone + sizeof(memzone_t) );
     mainzone->blocklist.user = (void *)mainzone;
     mainzone->blocklist.tag = PU_STATIC;
     mainzone->rover = block;
     block->prev = block->next = &mainzone->blocklist;
     // free block
     block->tag = PU_FREE;
     block->size = mainzone->size - sizeof(memzone_t);
 }
References memzone_t::blocklist, I_ZoneBase(), mainzone, memblock_s::next, memblock_s::prev, PU_FREE, PU_STATIC, memzone_t::rover, memblock_s::size, memzone_t::size, size, memblock_s::tag, and memblock_s::user.
Referenced by D_DoomMain().
Z_Malloc()
void* Z_Malloc (int size, int tag, void * user)
Definition at line 185 of file z_zone.c.
 {
     int     extra;
     memblock_t* start;
     memblock_t* rover;
     memblock_t* newblock;
     memblock_t* base;
     void *result;
     size = (size + MEM_ALIGN - 1) & ~(MEM_ALIGN - 1);
     // scan through the block list,
     // looking for the first free block
     // of sufficient size,
     // throwing out any purgable blocks along the way.
     // account for size of block header
     size += sizeof(memblock_t);
     // if there is a free block behind the rover,
     //  back up over them
     base = mainzone->rover;
     if (base->prev->tag == PU_FREE)
         base = base->prev;
     rover = base;
     start = base->prev;
     do
     {
         if (rover == start)
         {
             // scanned all the way around the list
             I_Error ("Z_Malloc: failed on allocation of %i bytes", size);
         }
         if (rover->tag != PU_FREE)
         {
             if (rover->tag < PU_PURGELEVEL)
             {
                 // hit a block that can't be purged,
                 // so move base past it
                 base = rover = rover->next;
             }
             else
             {
                 // free the rover block (adding the size to base)
                 // the rover can be the base block
                 base = base->prev;
                 Z_Free ((byte *)rover+sizeof(memblock_t));
                 base = base->next;
                 rover = base->next;
             }
         }
         else
         {
             rover = rover->next;
         }
     } while (base->tag != PU_FREE || base->size < size);
     // found a block big enough
     extra = base->size - size;
     if (extra >  MINFRAGMENT)
     {
         // there will be a free fragment after the allocated block
         newblock = (memblock_t *) ((byte *)base + size );
         newblock->size = extra;
         newblock->tag = PU_FREE;
         newblock->user = NULL;
         newblock->prev = base;
         newblock->next = base->next;
         newblock->next->prev = newblock;
         base->next = newblock;
         base->size = size;
     }
     if (user == NULL && tag >= PU_PURGELEVEL)
         I_Error ("Z_Malloc: an owner is required for purgable blocks");
     base->user = user;
     base->tag = tag;
     result  = (void *) ((byte *)base + sizeof(memblock_t));
     if (base->user)
     {
         *base->user = result;
     }
     // next allocation will start looking here
     mainzone->rover = base->next;
     base->id = ZONEID;
     return result;
 }
References base, I_Error(), mainzone, MEM_ALIGN, MINFRAGMENT, memblock_s::next, NULL, memblock_s::prev, PU_FREE, PU_PURGELEVEL, mlibc::result, memzone_t::rover, memblock_s::size, size, memblock_s::tag, memblock_s::user, Z_Free(), and ZONEID.
Referenced by EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), EV_VerticalDoor(), G_RecordDemo(), GenerateStretchTable(), GenerateTextureHashTable(), GetGameName(), I_InitGraphics(), IncreaseDemoBuffer(), M_ReadFile(), mem_fopen_read(), mem_fopen_write(), mem_fwrite(), P_GroupLines(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadNodes(), P_LoadReject(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_LoadVertexes(), P_SpawnDoorCloseIn30(), P_SpawnDoorRaiseIn5Mins(), P_SpawnFireFlicker(), P_SpawnGlowingLight(), P_SpawnLightFlash(), P_SpawnMobj(), P_SpawnStrobeFlash(), P_UnArchiveSpecials(), P_UnArchiveThinkers(), R_FillBackScreen(), R_GenerateComposite(), R_GenerateLookup(), R_InitFlats(), R_InitSpriteDefs(), R_InitSpriteLumps(), R_InitTextures(), R_InitTranslationTables(), R_PrecacheLevel(), ReadDMXConfig(), S_Init(), ST_Init(), W_AddFile(), W_CacheLumpNum(), W_GenerateHashTable(), W_StdC_OpenFile(), WI_loadData(), wipe_EndScreen(), wipe_initMelt(), wipe_shittyColMajorXform(), wipe_StartScreen(), and WritePCXfile().
Z_ZoneSize()
unsigned int Z_ZoneSize (void)
Definition at line 484 of file z_zone.c.
 {
     return mainzone->size;
 }
References mainzone, and memzone_t::size.
Variable Documentation
mainzone
memzone_t* mainzone
Definition at line 64 of file z_zone.c.
Referenced by Z_CheckHeap(), Z_DumpHeap(), Z_FileDumpHeap(), Z_Free(), Z_FreeMemory(), Z_FreeTags(), Z_Init(), Z_Malloc(), and Z_ZoneSize().