Fennix Userspace: Userspace/musl/src/stdlib/bsearch.c File Reference
bsearch.c File Reference
#include <stdlib.h>
Functions
void * bsearch (const void *key, const void *base, size_t nel, size_t width, int(*cmp)(const void *, const void *))
Function Documentation
bsearch()
void* bsearch (const void * key, const void * base, size_t nel, size_t width, int(*)(const void *, const void *) cmp)
Definition at line 3 of file bsearch.c.
 {
     void *try;
     int sign;
     while (nel > 0) {
         try = (char *)base + width*(nel/2);
         sign = cmp(key, try);
         if (sign < 0) {
             nel /= 2;
         } else if (sign > 0) {
             base = (char *)try + width;
             nel -= nel/2+1;
         } else {
             return try;
         }
     }
     return NULL;
 }
References base, cmp(), NULL, and width.
Referenced by catgets(), find_builtin(), findkwd(), and rpm_getstr().