Fennix: Userspace/apps/base/busybox/util-linux/losetup.c File Reference
losetup.c File Reference
#include "libbb.h"
Macros
#define MAX_LOOP_NUM 1023
#define LOOP_SET_CAPACITY 0x4C07
Functions
int losetup_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
LOOP_SET_CAPACITY
#define LOOP_SET_CAPACITY 0x4C07
MAX_LOOP_NUM
#define MAX_LOOP_NUM 1023
Definition at line 46 of file losetup.c.
Function Documentation
losetup_main()
int losetup_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 49 of file losetup.c.
 {
     unsigned opt;
     char *opt_o;
     char dev[LOOP_NAMESIZE];
     enum {
         OPT_c = (1 << 0),
         OPT_d = (1 << 1),
         OPT_P = (1 << 2),
         OPT_o = (1 << 3),
         OPT_f = (1 << 4),
         OPT_a = (1 << 5),
         OPT_r = (1 << 6),
     };
     opt = getopt32(argv, "^" "cdPo:far" "\0" "?2:d--Pofar:a--Pofr", &opt_o);
     argv += optind;
     /* LOOPDEV */
     if (!opt && argv[0] && !argv[1]) {
         char *s;
         s = query_loop(argv[0]);
         if (!s)
             bb_simple_perror_msg_and_die(argv[0]);
         printf("%s: %s\n", argv[0], s);
         if (ENABLE_FEATURE_CLEAN_UP)
             free(s);
         return EXIT_SUCCESS;
     }
     /* -c LOOPDEV */
     if (opt == OPT_c && argv[0]) {
         int fd = xopen(argv[0], O_RDONLY);
 #ifndef LOOP_SET_CAPACITY
 # define LOOP_SET_CAPACITY 0x4C07
 #endif
         xioctl(fd, LOOP_SET_CAPACITY, /*ignored:*/0);
         return EXIT_SUCCESS;
     }
     /* -d LOOPDEV */
     if (opt == OPT_d && argv[0]) {
         if (del_loop(argv[0]))
             bb_simple_perror_msg_and_die(argv[0]);
         return EXIT_SUCCESS;
     }
     /* -a */
     if (opt == OPT_a) {
         int n;
         for (n = 0; n < MAX_LOOP_NUM; n++) {
             char *s;
             sprintf(dev, LOOP_FORMAT, n);
             s = query_loop(dev);
             if (s) {
                 printf("%s: %s\n", dev, s);
                 free(s);
             }
         }
         return EXIT_SUCCESS;
     }
     /* contains -f */
     if (opt & OPT_f) {
         char *s;
         int n;
         n = get_free_loop();
         if (n == -1)
             bb_simple_error_msg_and_die("no free loop devices");
         if (n < 0) /* n == -2: no /dev/loop-control, use legacy method */
             n = 0;
         /* or: n >= 0: the number of next free loopdev, just verify it */
         do {
             if (n > MAX_LOOP_NUM)
                 bb_simple_error_msg_and_die("no free loop devices");
             sprintf(dev, LOOP_FORMAT, n++);
             s = query_loop(dev);
             free(s);
         } while (s);
         /* now: dev is next free "/dev/loopN" */
         if ((opt == OPT_f) && !argv[0]) {
             puts(dev);
             return EXIT_SUCCESS;
         }
     }
     /* [-rP] [-o OFS] {-f|LOOPDEV} FILE */
     if (argv[0] && ((opt & OPT_f) || argv[1])) {
         unsigned long long offset = 0;
         char *d = dev;
         if (opt & OPT_o)
             offset = xatoull(opt_o);
         if (!(opt & OPT_f))
             d = *argv++;
         if (argv[0]) {
             unsigned flags = (opt & OPT_r) ? BB_LO_FLAGS_READ_ONLY : 0;
             if (opt & OPT_P) {
                 flags |= BB_LO_FLAGS_PARTSCAN;
             }
             if (set_loop(&d, argv[0], offset, 0, flags) < 0)
                 bb_simple_perror_msg_and_die(argv[0]);
             return EXIT_SUCCESS;
         }
     }
     /* TODO: util-linux 2.28 shows this when run w/o params:
      * NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE     DIO
      * /dev/loop0         0      0         1  0 /PATH/TO/FILE   0
      *
      * implemented by reading /sys:
      *
      * open("/sys/block", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
      * newfstatat(3, "loop0/loop/backing_file", {st_mode=S_IFREG|0444, st_size=4096, ...}, 0) = 0
      * stat("/dev/loop0", {st_mode=S_IFBLK|0660, st_rdev=makedev(7, 0), ...}) = 0
      * open("/sys/dev/block/7:0/loop/offset", O_RDONLY|O_CLOEXEC) = 5
      * read(5, "0\n", 4096)                    = 2
      * open("/sys/dev/block/7:0/loop/sizelimit", O_RDONLY|O_CLOEXEC) = 5
      * read(5, "0\n", 4096)                    = 2
      * open("/sys/dev/block/7:0/loop/offset", O_RDONLY|O_CLOEXEC) = 5
      * read(5, "0\n", 4096)                    = 2
      * open("/sys/dev/block/7:0/loop/autoclear", O_RDONLY|O_CLOEXEC) = 5
      * read(5, "1\n", 4096)                    = 2
      * open("/sys/dev/block/7:0/ro", O_RDONLY|O_CLOEXEC)     = 5
      * read(5, "0\n", 4096)                    = 2
      * open("/sys/dev/block/7:0/loop/backing_file", O_RDONLY|O_CLOEXEC) = 5
      * read(5, "/PATH/TO/FILE", 4096) = 37
      * open("/sys/dev/block/7:0/loop/dio", O_RDONLY|O_CLOEXEC) = 5
      * read(5, "0\n", 4096)                    = 2
      */
     bb_show_usage(); /* does not return */
     /*return EXIT_FAILURE;*/
 }
References argv, BB_LO_FLAGS_PARTSCAN, BB_LO_FLAGS_READ_ONLY, bb_show_usage(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), del_loop(), EXIT_SUCCESS, fd, flags, free, get_free_loop(), getopt32(), LOOP_FORMAT, LOOP_NAMESIZE, LOOP_SET_CAPACITY, MAX_LOOP_NUM, n, O_RDONLY, offset, opt, OPT_a, OPT_c, OPT_d, OPT_f, OPT_o, OPT_P, OPT_r, optind, printf, puts(), query_loop(), s, set_loop(), sprintf(), xioctl, and xopen().