Fennix: Kernel/include/kconfig.hpp File Reference
kconfig.hpp File Reference
#include <types.h>
#include <memory.hpp>
Data Structures
struct KernelConfig
Enumerations
enum KCSchedType { Mono = 0 , Multi = 1 }
Functions
void ParseConfig (char *ConfigString, KernelConfig *ModConfig)
Data Structure Documentation
KernelConfig
struct KernelConfig
Definition at line 30 of file kconfig.hpp.
Data Fields
MemoryAllocatorType AllocatorType
bool BootAnimation
int Cores
char InitPath[256]
bool InterruptsOnCrash
int IOAPICInterruptCore
char ModuleDirectory[256]
bool SchedulerType
bool SIMD
bool UnlockDeadLock
bool UseLinuxSyscalls
Enumeration Type Documentation
KCSchedType
enum KCSchedType
Enumerator
Mono
Multi
Definition at line 24 of file kconfig.hpp.
 {
     Mono = 0,
     Multi = 1,
 };
Function Documentation
ParseConfig()
void ParseConfig (char * ConfigString, KernelConfig * ModConfig)
Definition at line 117 of file kernel_config.cpp.
 {
     if (ConfigString == NULL ||
         strlen(ConfigString) == 0)
     {
         KPrint("Empty kernel parameters!");
         return;
     }
     if (ModConfig == NULL)
     {
         KPrint("ModConfig is NULL!");
         return;
     }
     KPrint("Kernel parameters: %s", ConfigString);
     debug("Kernel parameters: %s", ConfigString);
     char *argv[32];
     int argc = 0;
     /* Not sure if the quotes are being parsed correctly. */
     targp_parse(ConfigString, argv, &argc);
 #ifdef DEBUG
     for (int i = 0; i < argc; i++)
         debug("argv[%d] = %s", i, argv[i]);
     debug("argc = %d", argc);
 #endif
     char identifier;
     const char *value;
     cag_option_context context;
     cag_option_prepare(&context, ConfigOptions,
                        CAG_ARRAY_SIZE(ConfigOptions), argc, argv);
     while (cag_option_fetch(&context))
     {
         identifier = cag_option_get(&context);
         switch (identifier)
         {
         case 'a':
         {
             value = cag_option_get_value(&context);
             if (strcmp(value, "xallocv1") == 0)
             {
                 KPrint("\eAAFFAAUsing XallocV1 as memory allocator");
                 ModConfig->AllocatorType = Memory::XallocV1;
             }
             else if (strcmp(value, "xallocv2") == 0)
             {
                 KPrint("\eAAFFAAUsing XallocV2 as memory allocator");
                 ModConfig->AllocatorType = Memory::XallocV2;
             }
             else if (strcmp(value, "liballoc11") == 0)
             {
                 KPrint("\eAAFFAAUsing Liballoc11 as memory allocator");
                 ModConfig->AllocatorType = Memory::liballoc11;
             }
             else if (strcmp(value, "pages") == 0)
             {
                 KPrint("\eAAFFAAUsing Pages as memory allocator");
                 ModConfig->AllocatorType = Memory::Pages;
             }
             break;
         }
         case 'c':
         {
             value = cag_option_get_value(&context);
             KPrint("\eAAFFAAUsing %s cores", atoi(value) ? value : "all");
             ModConfig->Cores = atoi(value);
             break;
         }
         case 'p':
         {
             value = cag_option_get_value(&context);
             KPrint("\eAAFFAARedirecting I/O APIC interrupts to %s%s",
                    atoi(value) ? "core " : "", atoi(value) ? value : "BSP");
             ModConfig->IOAPICInterruptCore = atoi(value);
             break;
         }
         case 't':
         {
             value = cag_option_get_value(&context);
             if (strcmp(value, "multi") == 0)
             {
                 KPrint("\eAAFFAAUsing Multi-Tasking Scheduler");
                 ModConfig->SchedulerType = Multi;
             }
             else if (strcmp(value, "single") == 0)
             {
                 KPrint("\eAAFFAAUsing Single-Tasking Scheduler");
                 ModConfig->SchedulerType = Mono;
             }
             else
             {
                 KPrint("\eAAFFAAUnknown scheduler: %s", value);
                 ModConfig->SchedulerType = Multi;
             }
             break;
         }
         case 'd':
         {
             value = cag_option_get_value(&context);
             strncpy(ModConfig->ModuleDirectory, value, strlen(value));
             KPrint("\eAAFFAAUsing %s as module directory", value);
             break;
         }
         case 'i':
         {
             value = cag_option_get_value(&context);
             strncpy(ModConfig->InitPath, value, strlen(value));
             KPrint("\eAAFFAAUsing %s as init program", value);
             break;
         }
         case 'y':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0
                 ? ModConfig->UseLinuxSyscalls = true
                 : ModConfig->UseLinuxSyscalls = false;
             KPrint("\eAAFFAAUse Linux syscalls by default: %s", value);
             break;
         }
         case 'o':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0
                 ? ModConfig->InterruptsOnCrash = true
                 : ModConfig->InterruptsOnCrash = false;
             KPrint("\eAAFFAAInterrupts on crash: %s", value);
             break;
         }
         case 'l':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0
                 ? ModConfig->UnlockDeadLock = true
                 : ModConfig->UnlockDeadLock = false;
             KPrint("\eAAFFAAUnlocking the deadlock after 10 retries");
             break;
         }
         case 's':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->SIMD = true
                                        : ModConfig->SIMD = false;
             KPrint("\eAAFFAASingle Instruction, Multiple Data (SIMD): %s", value);
             break;
         }
         case 'b':
         {
             value = cag_option_get_value(&context);
             strcmp(value, "true") == 0 ? ModConfig->BootAnimation = true
                                        : ModConfig->BootAnimation = false;
             KPrint("\eAAFFAABoot animation: %s", value);
             break;
         }
         case 'h':
         {
             KPrint("\n---------------------------------------------------------------------------\nUsage: kernel.fsys [OPTION]...\nKernel configuration.");
             cag_option_print(ConfigOptions, CAG_ARRAY_SIZE(ConfigOptions),
                              nullptr);
             KPrint("\eFF2200System Halted.");
             CPU::Stop();
         }
         default:
         {
             KPrint("\eFF2200Unknown option: %c", identifier);
             break;
         }
         }
     }
     debug("Config loaded");
 }
References KernelConfig::AllocatorType, argc, argv, atoi(), KernelConfig::BootAnimation, CAG_ARRAY_SIZE, cag_option_fetch(), cag_option_get(), cag_option_get_value(), cag_option_prepare(), cag_option_print(), ConfigOptions, context, KernelConfig::Cores, debug, i, cag_option::identifier, KernelConfig::InitPath, KernelConfig::InterruptsOnCrash, KernelConfig::IOAPICInterruptCore, KPrint(), KernelConfig::ModuleDirectory, Mono, Multi, NULL, KernelConfig::SchedulerType, KernelConfig::SIMD, strcmp, strlen(), strncpy(), targp_parse(), true, KernelConfig::UnlockDeadLock, KernelConfig::UseLinuxSyscalls, and value.
Referenced by Main().