Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/w_checksum.c File Reference
w_checksum.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "m_misc.h"
#include "sha1.h"
#include "w_checksum.h"
#include "w_wad.h"
Functions
static int GetFileNumber (wad_file_t *handle)
static void ChecksumAddLump (sha1_context_t *sha1_context, lumpinfo_t *lump)
void W_Checksum (sha1_digest_t digest)
Variables
static wad_file_t ** open_wadfiles = NULL
static int num_open_wadfiles = 0
Function Documentation
ChecksumAddLump()
static void ChecksumAddLump (sha1_context_t * sha1_context, lumpinfo_t * lump) static
Definition at line 57 of file w_checksum.c.
 {
     char buf[9];
     M_StringCopy(buf, lump->name, sizeof(buf));
     SHA1_UpdateString(sha1_context, buf);
     SHA1_UpdateInt32(sha1_context, GetFileNumber(lump->wad_file));
     SHA1_UpdateInt32(sha1_context, lump->position);
     SHA1_UpdateInt32(sha1_context, lump->size);
 }
References buf, GetFileNumber(), M_StringCopy(), lumpinfo_s::name, lumpinfo_s::position, SHA1_UpdateInt32(), SHA1_UpdateString(), lumpinfo_s::size, and lumpinfo_s::wad_file.
Referenced by W_Checksum().
GetFileNumber()
static int GetFileNumber (wad_file_t * handle) static
Definition at line 31 of file w_checksum.c.
 {
     int i;
     int result;
     for (i=0; i<num_open_wadfiles; ++i)
     {
         if (open_wadfiles[i] == handle)
         {
             return i;
         }
     }
     // Not found in list.  This is a new file we haven't seen yet.
     // Allocate another slot for this file.
     open_wadfiles = realloc(open_wadfiles,
                             sizeof(wad_file_t *) * (num_open_wadfiles + 1));
     open_wadfiles[num_open_wadfiles] = handle;
     result = num_open_wadfiles;
     ++num_open_wadfiles;
     return result;
 }
References i, num_open_wadfiles, open_wadfiles, realloc(), and mlibc::result.
Referenced by ChecksumAddLump().
W_Checksum()
void W_Checksum (sha1_digest_t digest)
Definition at line 68 of file w_checksum.c.
 {
     sha1_context_t sha1_context;
     unsigned int i;
     SHA1_Init(&sha1_context);
     num_open_wadfiles = 0;
     // Go through each entry in the WAD directory, adding information
     // about each entry to the SHA1 hash.
     for (i=0; i<numlumps; ++i)
     {
         ChecksumAddLump(&sha1_context, &lumpinfo[i]);
     }
     SHA1_Final(digest, &sha1_context);
 }
References ChecksumAddLump(), i, lumpinfo, num_open_wadfiles, numlumps, SHA1_Final(), and SHA1_Init().
Referenced by InitConnectData().
Variable Documentation
num_open_wadfiles
int num_open_wadfiles = 0 static
Definition at line 29 of file w_checksum.c.
Referenced by GetFileNumber(), and W_Checksum().
open_wadfiles
wad_file_t** open_wadfiles = NULL static
Definition at line 28 of file w_checksum.c.
Referenced by GetFileNumber().