Fennix: Userspace/apps/base/bash/lib/sh/input_avail.c File Reference
input_avail.c File Reference
#include <sys/types.h>
#include <fcntl.h>
#include "bashansi.h"
#include "posixselect.h"
#include <stdio.h>
#include <errno.h>
Functions
int input_avail (int fd)
int nchars_avail (int fd, int nchars)
Variables
int errno
Function Documentation
input_avail()
int input_avail (int fd)
Definition at line 66 of file input_avail.c.
 {
   int result, chars_avail;
 #if defined(HAVE_SELECT)
   fd_set readfds, exceptfds;
   struct timeval timeout;
 #endif
   if (fd < 0)
     return -1;
   chars_avail = 0;
 #if defined (HAVE_SELECT)
   FD_ZERO (&readfds);
   FD_ZERO (&exceptfds);
   FD_SET (fd, &readfds);
   FD_SET (fd, &exceptfds);
   timeout.tv_sec = 0;
   timeout.tv_usec = 0;
   result = select (fd + 1, &readfds, (fd_set *)NULL, &exceptfds, &timeout);
   return ((result <= 0) ? 0 : 1);
 #endif
 #if defined (FIONREAD)
   errno = 0;
   result = ioctl (fd, FIONREAD, &chars_avail);
   if (result == -1 && errno == EIO)
     return -1;
   return (chars_avail);
 #endif
   return 0;
 }
References EIO, errno, fd, FD_SET, FD_ZERO, FIONREAD, ioctl(), NULL, select(), and timeout().
Referenced by nchars_avail().
nchars_avail()
int nchars_avail (int fd, int nchars)
Definition at line 105 of file input_avail.c.
 {
   int result, chars_avail;
 #if defined(HAVE_SELECT)
   fd_set readfds, exceptfds;
 #endif
 #if defined (HAVE_PSELECT) || defined (HAVE_SELECT)
   sigset_t set, oset;
 #endif
   if (fd < 0 || nchars < 0)
     return -1;
   if (nchars == 0)
     return (input_avail (fd));
   chars_avail = 0;
 #if defined (HAVE_SELECT)
   FD_ZERO (&readfds);
   FD_ZERO (&exceptfds);
   FD_SET (fd, &readfds);
   FD_SET (fd, &exceptfds);
 #endif
 #if defined (HAVE_SELECT) || defined (HAVE_PSELECT)
   sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &set);
 #  ifdef SIGCHLD
   sigaddset (&set, SIGCHLD);
 #  endif
   sigemptyset (&oset);
 #endif
   while (1)
     {
       result = 0;
 #if defined (HAVE_PSELECT)
       /* XXX - use pselect(2) to block SIGCHLD atomically */
       result = pselect (fd + 1, &readfds, (fd_set *)NULL, &exceptfds, (struct timespec *)NULL, &set);
 #elif defined (HAVE_SELECT)
       sigprocmask (SIG_BLOCK, &set, &oset);
       result = select (fd + 1, &readfds, (fd_set *)NULL, &exceptfds, (struct timeval *)NULL);
       sigprocmask (SIG_BLOCK, &oset, (sigset_t *)NULL);
 #endif
       if (result < 0)
         return -1;
 #if defined (FIONREAD)
       errno = 0;
       result = ioctl (fd, FIONREAD, &chars_avail);
       if (result == -1 && errno == EIO)
         return -1;
       if (chars_avail >= nchars)
         break;
 #else
       break;
 #endif
     }
   return 0;
 }
References EIO, errno, fd, FD_SET, FD_ZERO, FIONREAD, input_avail(), ioctl(), NULL, pselect(), select(), SIG_BLOCK, sigaddset(), SIGCHLD, sigemptyset(), and sigprocmask().
Variable Documentation
errno
int errno extern
Referenced by input_avail(), and nchars_avail().