Fennix Userspace: Userspace/apps/base/busybox/libbb/capability.c File Reference
capability.c File Reference
#include <linux/capability.h>
#include "libbb.h"
Functions
int capset (cap_user_header_t header, cap_user_data_t data)
int capget (cap_user_header_t header, const cap_user_data_t data)
unsigned FAST_FUNC cap_name_to_number (const char *cap)
void FAST_FUNC printf_cap (const char *pfx, unsigned cap_no)
void FAST_FUNC getcaps (void *arg)
Variables
static const char *const capabilities[] ALIGN_PTR
DEFINE_STRUCT_CAPS
Function Documentation
cap_name_to_number()
unsigned FAST_FUNC cap_name_to_number (const char * cap)
Definition at line 61 of file capability.c.
 {
     unsigned i, n;
     if ((sscanf(cap, "cap_%u", &n)) == 1) {
         i = n;
         goto found;
     }
     for (i = 0; i < ARRAY_SIZE(capabilities); i++) {
         if (strcasecmp(capabilities[i], cap) == 0)
             goto found;
     }
     bb_error_msg_and_die("unknown capability '%s'", cap);
  found:
     if (!cap_valid(i))
         bb_error_msg_and_die("unknown capability '%s'", cap);
     return i;
 }
References ARRAY_SIZE, bb_error_msg_and_die(), found, i, n, sscanf(), and strcasecmp.
capget()
int capget (cap_user_header_t header, const cap_user_data_t data)
Referenced by getcaps().
capset()
int capset (cap_user_header_t header, cap_user_data_t data)
getcaps()
void FAST_FUNC getcaps (void * arg)
Definition at line 92 of file capability.c.
 {
     static const uint8_t versions[] = {
         _LINUX_CAPABILITY_U32S_3, /* = 2 (fits into byte) */
         _LINUX_CAPABILITY_U32S_2, /* = 2 */
         _LINUX_CAPABILITY_U32S_1, /* = 1 */
     };
     int i;
     struct caps *caps = arg;
     caps->header.pid = 0;
     for (i = 0; i < ARRAY_SIZE(versions); i++) {
         caps->header.version = versions[i];
         if (capget(&caps->header, NULL) == 0)
             goto got_it;
     }
     bb_simple_perror_msg_and_die("capget");
  got_it:
     switch (caps->header.version) {
         case _LINUX_CAPABILITY_VERSION_1:
             caps->u32s = _LINUX_CAPABILITY_U32S_1;
             break;
         case _LINUX_CAPABILITY_VERSION_2:
             caps->u32s = _LINUX_CAPABILITY_U32S_2;
             break;
         case _LINUX_CAPABILITY_VERSION_3:
             caps->u32s = _LINUX_CAPABILITY_U32S_3;
             break;
         default:
             bb_simple_error_msg_and_die("unsupported capability version");
     }
     if (capget(&caps->header, caps->data) != 0)
         bb_simple_perror_msg_and_die("capget");
 }
References ARRAY_SIZE, bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), capget(), i, and NULL.
printf_cap()
void FAST_FUNC printf_cap (const char * pfx, unsigned cap_no)
Definition at line 81 of file capability.c.
 {
     if (cap_no < ARRAY_SIZE(capabilities)) {
         printf("%s%s", pfx, capabilities[cap_no]);
         return;
     }
     printf("%scap_%u", pfx, cap_no);
 }
References ARRAY_SIZE, and printf().
Variable Documentation
ALIGN_PTR
const char* const capabilities [] ALIGN_PTR static
Definition at line 20 of file capability.c.
DEFINE_STRUCT_CAPS
DEFINE_STRUCT_CAPS
Definition at line 90 of file capability.c.