Fennix: Userspace/apps/base/bash/hashcmd.c File Reference
hashcmd.c File Reference
#include <config.h>
#include "bashtypes.h"
#include "posixstat.h"
#include "bashansi.h"
#include "shell.h"
#include "flags.h"
#include "findcmd.h"
#include "hashcmd.h"
Functions
static void phash_freedata PARAMS ((PTR_T))
void phash_create ()
static void phash_freedata (PTR_T data)
void phash_flush ()
int phash_remove (char *filename) const
void phash_insert (char *filename, char *full_path, int check_dot, int found)
char * phash_search (char *filename) const
Variables
HASH_TABLE * hashed_filenames = (HASH_TABLE *)NULL
Function Documentation
PARAMS()
static void phash_freedata PARAMS ((PTR_T)) static
phash_create()
void phash_create ()
Definition at line 43 of file hashcmd.c.
 {
   if (hashed_filenames == 0)
     hashed_filenames = hash_create (FILENAME_HASH_BUCKETS);
 }
References FILENAME_HASH_BUCKETS, hash_create(), and hashed_filenames.
Referenced by phash_insert().
phash_flush()
void phash_flush ()
Definition at line 58 of file hashcmd.c.
 {
   if (hashed_filenames)
     hash_flush (hashed_filenames, phash_freedata);
 }
References hash_flush(), hashed_filenames, and phash_freedata().
Referenced by sv_path().
phash_freedata()
static void phash_freedata (PTR_T data) static
Definition at line 50 of file hashcmd.c.
 {
   free (((PATH_DATA *)data)->path);
   free (data);
 }
References free.
Referenced by phash_flush(), and phash_remove().
phash_insert()
void phash_insert (char * filename, char * full_path, int check_dot, int found)
Definition at line 92 of file hashcmd.c.
 {
   register BUCKET_CONTENTS *item;
   if (hashing_enabled == 0)
     return;
   if (hashed_filenames == 0)
     phash_create ();
   item = hash_insert (filename, hashed_filenames, 0);
   if (item->data)
     free (pathdata(item)->path);
   else
     {
       item->key = savestring (filename);
       item->data = xmalloc (sizeof (PATH_DATA));
     }
   pathdata(item)->path = savestring (full_path);
   pathdata(item)->flags = 0;
   if (check_dot)
     pathdata(item)->flags |= HASH_CHKDOT;
   if (*full_path != '/')
     pathdata(item)->flags |= HASH_RELPATH;
   item->times_found = found;
 }
References bucket_contents::data, free, HASH_CHKDOT, hash_insert(), HASH_RELPATH, hashed_filenames, hashing_enabled, bucket_contents::key, pathdata, phash_create(), savestring(), bucket_contents::times_found, and xmalloc.
Referenced by search_for_command().
phash_remove()
int phash_remove (char * filename) const
Definition at line 66 of file hashcmd.c.
 {
   register BUCKET_CONTENTS *item;
   if (hashing_enabled == 0 || hashed_filenames == 0)
     return 0;
   item = hash_remove (filename, hashed_filenames, 0);
   if (item)
     {
       if (item->data)
     phash_freedata (item->data);
       free (item->key);
       free (item);
       return 0;
     }
   return 1;
 }
References bucket_contents::data, free, hash_remove(), hashed_filenames, hashing_enabled, bucket_contents::key, and phash_freedata().
Referenced by search_for_command().
phash_search()
char* phash_search (char * filename) const
Definition at line 127 of file hashcmd.c.
 {
   register BUCKET_CONTENTS *item;
   char *path, *dotted_filename, *tail;
   int same;
   if (hashing_enabled == 0 || hashed_filenames == 0)
     return ((char *)NULL);
   item = hash_search (filename, hashed_filenames, 0);
   if (item == NULL)
     return ((char *)NULL);
   /* If this filename is hashed, but `.' comes before it in the path,
      see if ./filename is executable.  If the hashed value is not an
      absolute pathname, see if ./`hashed-value' exists. */
   path = pathdata(item)->path;
   if (pathdata(item)->flags & (HASH_CHKDOT|HASH_RELPATH))
     {
       tail = (pathdata(item)->flags & HASH_RELPATH) ? path : (char *)filename;  /* XXX - fix const later */
       /* If the pathname does not start with a `./', add a `./' to it. */
       if (tail[0] != '.' || tail[1] != '/')
     {
       dotted_filename = (char *)xmalloc (3 + strlen (tail));
       dotted_filename[0] = '.'; dotted_filename[1] = '/';
       strcpy (dotted_filename + 2, tail);
     }
       else
     dotted_filename = savestring (tail);
       if (executable_file (dotted_filename))
     return (dotted_filename);
       free (dotted_filename);
 #if 0
       if (pathdata(item)->flags & HASH_RELPATH)
     return ((char *)NULL);
 #endif
       /* Watch out.  If this file was hashed to "./filename", and
      "./filename" is not executable, then return NULL. */
       /* Since we already know "./filename" is not executable, what
      we're really interested in is whether or not the `path'
      portion of the hashed filename is equivalent to the current
      directory, but only if it starts with a `.'.  (This catches
      ./. and so on.)  same_file () tests general Unix file
      equivalence -- same device and inode. */
       if (*path == '.')
     {
       same = 0;
       tail = (char *)strrchr (path, '/');
       if (tail)
         {
           *tail = '\0';
           same = same_file (".", path, (struct stat *)NULL, (struct stat *)NULL);
           *tail = '/';
         }
       return same ? (char *)NULL : savestring (path);
     }
     }
   return (savestring (path));
 }
References executable_file(), flags, free, HASH_CHKDOT, HASH_RELPATH, hash_search(), hashed_filenames, hashing_enabled, NULL, pathdata, same_file(), savestring(), strcpy, strlen(), strrchr(), tail, and xmalloc.
Referenced by search_for_command().
Variable Documentation
hashed_filenames
HASH_TABLE* hashed_filenames = (HASH_TABLE *)NULL
Definition at line 38 of file hashcmd.c.
Referenced by phash_create(), phash_flush(), phash_insert(), phash_remove(), and phash_search().