Fennix: Userspace/apps/base/busybox/console-tools/reset.c File Reference
reset.c File Reference
#include "libbb.h"
Macros
#define ESC "\033"
Functions
int reset_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int reset_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Macro Definition Documentation
ESC
#define ESC "\033"
Definition at line 30 of file reset.c.
Function Documentation
reset_main() [1/2]
int reset_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 37 of file reset.c.
 {
     static const char *const args[] ALIGN_PTR = {
         "stty", "sane", NULL
     };
     /* no options, no getopt */
     if (/*isatty(STDIN_FILENO) &&*/ isatty(STDOUT_FILENO)) {
         /* See 'man 4 console_codes' for details:
          * "ESC c"        -- Reset
          * "ESC ( B"      -- Select G0 Character Set (B = US)
          * "ESC [ m"      -- Reset all display attributes
          * "ESC [ J"      -- Erase to the end of screen
          * "ESC [ ? 25 h" -- Make cursor visible
          */
         printf(ESC"c" ESC"(B" ESC"[m" ESC"[J" ESC"[?25h");
         /* http://bugs.busybox.net/view.php?id=1414:
          * people want it to reset echo etc: */
 #if ENABLE_STTY
         return stty_main(2, (char**)args);
 #else
         /* Make sure stdout gets drained before we execvp */
         fflush_all();
         execvp("stty", (char**)args);
 #endif
     }
     return EXIT_SUCCESS;
 }
References ALIGN_PTR, ESC, execvp(), EXIT_SUCCESS, fflush_all(), isatty(), NULL, printf, STDOUT_FILENO, and stty_main().
reset_main() [2/2]
int reset_main (int argc, char ** argv)