Fennix Userspace: ConfigList Class Reference
ConfigList Class Reference
#include <qconf.h>
Public Slots
void setRootMenu (struct menu *menu)
void updateList (ConfigItem *item)
void setValue (ConfigItem *item, tristate val)
void changeValue (ConfigItem *item)
void updateSelection (void)
Signals
void menuSelected (struct menu *menu)
void parentSelected (void)
void gotFocus (void)
Public Member Functions
ConfigList (ConfigView *p, ConfigMainWindow *cview, ConfigSettings *configSettings)
void reinit (void)
ConfigView * parent (void) const
void updateListAll (void)
ConfigList * listView ()
ConfigItem * firstChild () const
int mapIdx (colIdx idx)
void addColumn (colIdx idx, const QString &label)
void removeColumn (colIdx idx)
void setAllOpen (bool open)
void setParentMenu (void)
template<class P >
void updateMenuList (P *, struct menu *)
Data Fields
bool updateAll
QPixmap symbolYesPix
QPixmap symbolModPix
QPixmap symbolNoPix
QPixmap choiceYesPix
QPixmap choiceNoPix
QPixmap menuPix
QPixmap menuInvPix
QPixmap menuBackPix
QPixmap voidPix
bool showAll
bool showName
bool showRange
bool showData
enum listMode mode
struct menu * rootEntry
QColorGroup disabledColorGroup
QColorGroup inactivedColorGroup
Protected Member Functions
void keyPressEvent (QKeyEvent *e)
void contentsMousePressEvent (QMouseEvent *e)
void contentsMouseReleaseEvent (QMouseEvent *e)
void contentsMouseMoveEvent (QMouseEvent *e)
void contentsMouseDoubleClickEvent (QMouseEvent *e)
void focusInEvent (QFocusEvent *e)
Protected Attributes
ConfigMainWindow * cview
Private Types
typedef class QListView Parent
Private Attributes
int colMap [colNr]
int colRevMap [colNr]
Detailed Description
Definition at line 59 of file qconf.h.
Member Typedef Documentation
Parent
typedef class QListView ConfigList::Parent private
Definition at line 49 of file qconf.h.
Constructor & Destructor Documentation
ConfigList()
ConfigList::ConfigList (ConfigView * p, ConfigMainWindow * cview, ConfigSettings * configSettings)
Definition at line 388 of file qconf.cc.
     : Parent(p), cview(cv),
       updateAll(false),
       symbolYesPix(xpm_symbol_yes), symbolModPix(xpm_symbol_mod), symbolNoPix(xpm_symbol_no),
       choiceYesPix(xpm_choice_yes), choiceNoPix(xpm_choice_no),
       menuPix(xpm_menu), menuInvPix(xpm_menu_inv), menuBackPix(xpm_menuback), voidPix(xpm_void),
       showAll(false), showName(false), showRange(false), showData(false),
       rootEntry(0)
 {
     int i;
     setSorting(-1);
     setRootIsDecorated(TRUE);
     disabledColorGroup = palette().active();
     disabledColorGroup.setColor(QColorGroup::Text, palette().disabled().text());
     inactivedColorGroup = palette().active();
     inactivedColorGroup.setColor(QColorGroup::Highlight, palette().disabled().highlight());
     connect(this, SIGNAL(selectionChanged(void)),
         SLOT(updateSelection(void)));
     if (configSettings) {
         showAll = configSettings->showAll;
         showName = configSettings->showName;
         showRange = configSettings->showRange;
         showData = configSettings->showData;
     }
     for (i = 0; i < colNr; i++)
         colMap[i] = colRevMap[i] = -1;
     addColumn(promptColIdx, "Option");
     reinit();
 }
References addColumn(), colMap, colNr, colRevMap, connect(), disabledColorGroup, i, inactivedColorGroup, promptColIdx, reinit(), ConfigSettings::showAll, showAll, ConfigSettings::showData, showData, ConfigSettings::showName, showName, ConfigSettings::showRange, showRange, text, TRUE, and updateSelection().
Member Function Documentation
addColumn()
void ConfigList::addColumn (colIdx idx, const QString & label) inline
Definition at line 110 of file qconf.h.
     {
         colMap[idx] = Parent::addColumn(label);
         colRevMap[colMap[idx]] = idx;
     }
References colMap, colRevMap, idx, and label.
Referenced by ConfigList(), and reinit().
changeValue
void ConfigList::changeValue (ConfigItem * item) slot
Definition at line 527 of file qconf.cc.
 {
     struct symbol* sym;
     struct menu* menu;
     int type, oldexpr, newexpr;
     menu = item->menu;
     if (!menu)
         return;
     sym = menu->sym;
     if (!sym) {
         if (item->menu->list)
             item->setOpen(!item->isOpen());
         return;
     }
     type = sym_get_type(sym);
     switch (type) {
     case S_BOOLEAN:
     case S_TRISTATE:
         oldexpr = sym_get_tristate_value(sym);
         newexpr = sym_toggle_tristate_value(sym);
         if (item->menu->list) {
             if (oldexpr == newexpr)
                 item->setOpen(!item->isOpen());
             else if (oldexpr == no)
                 item->setOpen(TRUE);
         }
         if (oldexpr != newexpr)
             parent()->updateList(item);
         break;
     case S_INT:
     case S_HEX:
     case S_STRING:
 #if QT_VERSION >= 300
         if (colMap[dataColIdx] >= 0)
             item->startRename(colMap[dataColIdx]);
         else
 #endif
             parent()->lineEdit->show(item);
         break;
     }
 }
References colMap, dataColIdx, ConfigView::lineEdit, menu::list, ConfigItem::menu, no, parent(), S_BOOLEAN, S_HEX, S_INT, S_STRING, S_TRISTATE, ConfigLineEdit::show(), menu::sym, sym_get_tristate_value(), sym_get_type(), sym_toggle_tristate_value(), TRUE, type, and ConfigView::updateList().
Referenced by contentsMouseDoubleClickEvent(), contentsMouseReleaseEvent(), and keyPressEvent().
contentsMouseDoubleClickEvent()
void ConfigList::contentsMouseDoubleClickEvent (QMouseEvent * e) protected
Definition at line 729 of file qconf.cc.
 {
     QPoint p(contentsToViewport(e->pos()));
     ConfigItem* item = (ConfigItem*)itemAt(p);
     struct menu *menu;
     enum prop_type ptype;
     if (!item)
         goto skip;
     if (item->goParent) {
         emit parentSelected();
         goto skip;
     }
     menu = item->menu;
     if (!menu)
         goto skip;
     ptype = menu->prompt ? menu->prompt->type : P_UNKNOWN;
     if (ptype == P_MENU && (mode == singleMode || mode == symbolMode))
         emit menuSelected(menu);
     else if (menu->sym)
         changeValue(item);
 skip:
     //printf("contentsMouseDoubleClickEvent: %d,%d\n", p.x(), p.y());
     Parent::contentsMouseDoubleClickEvent(e);
 }
References changeValue(), ConfigItem::goParent, ConfigItem::menu, menuSelected(), mode, p, P_MENU, P_UNKNOWN, parentSelected(), menu::prompt, singleMode, skip, menu::sym, symbolMode, and property::type.
contentsMouseMoveEvent()
void ConfigList::contentsMouseMoveEvent (QMouseEvent * e) protected
Definition at line 722 of file qconf.cc.
 {
     //QPoint p(contentsToViewport(e->pos()));
     //printf("contentsMouseMoveEvent: %d,%d\n", p.x(), p.y());
     Parent::contentsMouseMoveEvent(e);
 }
contentsMousePressEvent()
void ConfigList::contentsMousePressEvent (QMouseEvent * e) protected
Definition at line 660 of file qconf.cc.
 {
     //QPoint p(contentsToViewport(e->pos()));
     //printf("contentsMousePressEvent: %d,%d\n", p.x(), p.y());
     Parent::contentsMousePressEvent(e);
 }
contentsMouseReleaseEvent()
void ConfigList::contentsMouseReleaseEvent (QMouseEvent * e) protected
Definition at line 667 of file qconf.cc.
 {
     QPoint p(contentsToViewport(e->pos()));
     ConfigItem* item = (ConfigItem*)itemAt(p);
     struct menu *menu;
     enum prop_type ptype;
     const QPixmap* pm;
     int idx, x;
     if (!item)
         goto skip;
     menu = item->menu;
     x = header()->offset() + p.x();
     idx = colRevMap[header()->sectionAt(x)];
     switch (idx) {
     case promptColIdx:
         pm = item->pixmap(promptColIdx);
         if (pm) {
             int off = header()->sectionPos(0) + itemMargin() +
                 treeStepSize() * (item->depth() + (rootIsDecorated() ? 1 : 0));
             if (x >= off && x < off + pm->width()) {
                 if (item->goParent) {
                     emit parentSelected();
                     break;
                 } else if (!menu)
                     break;
                 ptype = menu->prompt ? menu->prompt->type : P_UNKNOWN;
                 if (ptype == P_MENU && rootEntry != menu &&
                     mode != fullMode && mode != menuMode)
                     emit menuSelected(menu);
                 else
                     changeValue(item);
             }
         }
         break;
     case noColIdx:
         setValue(item, no);
         break;
     case modColIdx:
         setValue(item, mod);
         break;
     case yesColIdx:
         setValue(item, yes);
         break;
     case dataColIdx:
         changeValue(item);
         break;
     }
 skip:
     //printf("contentsMouseReleaseEvent: %d,%d\n", p.x(), p.y());
     Parent::contentsMouseReleaseEvent(e);
 }
References changeValue(), colRevMap, dataColIdx, fullMode, ConfigItem::goParent, idx, ConfigItem::menu, menuMode, menuSelected(), mod, modColIdx, mode, no, noColIdx, off, p, P_MENU, P_UNKNOWN, parentSelected(), ConfigItem::pixmap(), menu::prompt, promptColIdx, rootEntry, setValue(), skip, property::type, width, x, yes, and yesColIdx.
firstChild()
ConfigItem* ConfigList::firstChild () const inline
Definition at line 102 of file qconf.h.
     {
         return (ConfigItem *)Parent::firstChild();
     }
Referenced by updateList().
focusInEvent()
void ConfigList::focusInEvent (QFocusEvent * e) protected
Definition at line 756 of file qconf.cc.
 {
     Parent::focusInEvent(e);
     QListViewItem* item = currentItem();
     if (!item)
         return;
     setSelected(item, TRUE);
     emit gotFocus();
 }
References gotFocus(), and TRUE.
gotFocus
void ConfigList::gotFocus (void) signal
Referenced by focusInEvent().
keyPressEvent()
void ConfigList::keyPressEvent (QKeyEvent * e) protected
Definition at line 606 of file qconf.cc.
 {
     QListViewItem* i = currentItem();
     ConfigItem* item;
     struct menu *menu;
     enum prop_type type;
     if (ev->key() == Key_Escape && mode != fullMode) {
         emit parentSelected();
         ev->accept();
         return;
     }
     if (!i) {
         Parent::keyPressEvent(ev);
         return;
     }
     item = (ConfigItem*)i;
     switch (ev->key()) {
     case Key_Return:
     case Key_Enter:
         if (item->goParent) {
             emit parentSelected();
             break;
         }
         menu = item->menu;
         if (!menu)
             break;
         type = menu->prompt ? menu->prompt->type : P_UNKNOWN;
         if (type == P_MENU && rootEntry != menu &&
             mode != fullMode && mode != menuMode) {
             emit menuSelected(menu);
             break;
         }
     case Key_Space:
         changeValue(item);
         break;
     case Key_N:
         setValue(item, no);
         break;
     case Key_M:
         setValue(item, mod);
         break;
     case Key_Y:
         setValue(item, yes);
         break;
     default:
         Parent::keyPressEvent(ev);
         return;
     }
     ev->accept();
 }
References changeValue(), fullMode, ConfigItem::goParent, i, ConfigItem::menu, menuMode, menuSelected(), mod, mode, no, P_MENU, P_UNKNOWN, parentSelected(), menu::prompt, rootEntry, setValue(), type, property::type, and yes.
listView()
ConfigList* ConfigList::listView () inline
Definition at line 98 of file qconf.h.
     {
         return this;
     }
mapIdx()
int ConfigList::mapIdx (colIdx idx) inline
Definition at line 106 of file qconf.h.
     {
         return colMap[idx];
     }
References colMap, and idx.
menuSelected
void ConfigList::menuSelected (struct menu * menu) signal
Referenced by contentsMouseDoubleClickEvent(), contentsMouseReleaseEvent(), keyPressEvent(), and updateSelection().
parent()
ConfigView* ConfigList::parent (void) const inline
Definition at line 65 of file qconf.h.
     {
         return (ConfigView*)Parent::parent();
     }
References parent.
Referenced by changeValue(), ConfigMainWindow::setHelp(), setValue(), and updateMenuList().
parentSelected
void ConfigList::parentSelected (void) signal
Referenced by contentsMouseDoubleClickEvent(), contentsMouseReleaseEvent(), and keyPressEvent().
reinit()
void ConfigList::reinit (void)
Definition at line 423 of file qconf.cc.
 {
     removeColumn(dataColIdx);
     removeColumn(yesColIdx);
     removeColumn(modColIdx);
     removeColumn(noColIdx);
     removeColumn(nameColIdx);
     if (showName)
         addColumn(nameColIdx, "Name");
     if (showRange) {
         addColumn(noColIdx, "N");
         addColumn(modColIdx, "M");
         addColumn(yesColIdx, "Y");
     }
     if (showData)
         addColumn(dataColIdx, "Value");
     updateListAll();
 }
References addColumn(), dataColIdx, modColIdx, nameColIdx, noColIdx, removeColumn(), showData, showName, showRange, updateListAll(), and yesColIdx.
Referenced by ConfigList(), ConfigMainWindow::setShowData(), ConfigMainWindow::setShowName(), and ConfigMainWindow::setShowRange().
removeColumn()
void ConfigList::removeColumn (colIdx idx) inline
Definition at line 115 of file qconf.h.
     {
         int col = colMap[idx];
         if (col >= 0) {
             Parent::removeColumn(col);
             colRevMap[col] = colMap[idx] = -1;
         }
     }
References colMap, colRevMap, and idx.
Referenced by reinit().
setAllOpen()
void ConfigList::setAllOpen (bool open)
Definition at line 494 of file qconf.cc.
 {
     QListViewItemIterator it(this);
     for (; it.current(); it++)
         it.current()->setOpen(open);
 }
References open().
Referenced by ConfigMainWindow::showFullView(), ConfigMainWindow::showSingleView(), and ConfigMainWindow::showSplitView().
setParentMenu()
void ConfigList::setParentMenu (void)
Definition at line 586 of file qconf.cc.
 {
     ConfigItem* item;
     struct menu *oldroot;
     oldroot = rootEntry;
     if (rootEntry == &rootmenu)
         return;
     setRootMenu(menu_get_parent_menu(rootEntry->parent));
     QListViewItemIterator it(this);
     for (; (item = (ConfigItem*)it.current()); it++) {
         if (item->menu == oldroot) {
             setCurrentItem(item);
             ensureItemVisible(item);
             break;
         }
     }
 }
References ConfigItem::menu, menu_get_parent_menu(), menu::parent, rootEntry, rootmenu, and setRootMenu().
Referenced by ConfigMainWindow::goBack().
setRootMenu
void ConfigList::setRootMenu (struct menu * menu) slot
Definition at line 571 of file qconf.cc.
 {
     enum prop_type type;
     if (rootEntry == menu)
         return;
     type = menu && menu->prompt ? menu->prompt->type : P_UNKNOWN;
     if (type != P_MENU)
         return;
     updateMenuList(this, 0);
     rootEntry = menu;
     updateListAll();
     setSelected(currentItem(), hasFocus());
 }
References P_MENU, P_UNKNOWN, menu::prompt, rootEntry, type, property::type, updateListAll(), and updateMenuList().
Referenced by ConfigMainWindow::changeMenu(), setParentMenu(), ConfigMainWindow::showFullView(), ConfigMainWindow::showSingleView(), and ConfigMainWindow::showSplitView().
setValue
void ConfigList::setValue (ConfigItem * item, tristate val) slot
Definition at line 502 of file qconf.cc.
 {
     struct symbol* sym;
     int type;
     tristate oldval;
     sym = item->menu ? item->menu->sym : 0;
     if (!sym)
         return;
     type = sym_get_type(sym);
     switch (type) {
     case S_BOOLEAN:
     case S_TRISTATE:
         oldval = sym_get_tristate_value(sym);
         if (!sym_set_tristate_value(sym, val))
             return;
         if (oldval == no && item->menu->list)
             item->setOpen(TRUE);
         parent()->updateList(item);
         break;
     }
 }
References menu::list, ConfigItem::menu, no, parent(), S_BOOLEAN, S_TRISTATE, menu::sym, sym_get_tristate_value(), sym_get_type(), sym_set_tristate_value(), TRUE, type, ConfigView::updateList(), and val.
Referenced by contentsMouseReleaseEvent(), and keyPressEvent().
updateList
void ConfigList::updateList (ConfigItem * item) slot
Definition at line 463 of file qconf.cc.
 {
     ConfigItem* last = 0;
     if (!rootEntry)
         goto update;
     if (rootEntry != &rootmenu && (mode == singleMode ||
         (mode == symbolMode && rootEntry->parent != &rootmenu))) {
         item = firstChild();
         if (!item)
             item = new ConfigItem(this, 0, true);
         last = item;
     }
     if ((mode == singleMode || (mode == symbolMode && !(rootEntry->flags & MENU_ROOT))) &&
         rootEntry->sym && rootEntry->prompt) {
         item = last ? last->nextSibling() : firstChild();
         if (!item)
             item = new ConfigItem(this, last, rootEntry, true);
         else
             item->testUpdateMenu(true);
         updateMenuList(item, rootEntry);
         triggerUpdate();
         return;
     }
 update:
     updateMenuList(this, rootEntry);
     triggerUpdate();
 }
References firstChild(), menu::flags, last, MENU_ROOT, mode, menu::parent, menu::prompt, rootEntry, rootmenu, singleMode, menu::sym, symbolMode, ConfigItem::testUpdateMenu(), and updateMenuList().
Referenced by ConfigView::updateList(), and updateListAll().
updateListAll()
void ConfigList::updateListAll (void) inline
Definition at line 92 of file qconf.h.
     {
         updateAll = true;
         updateList(NULL);
         updateAll = false;
     }
References NULL, updateAll, and updateList().
Referenced by reinit(), setRootMenu(), ConfigMainWindow::setShowAll(), ConfigMainWindow::showFullView(), ConfigMainWindow::showSingleView(), ConfigMainWindow::showSplitView(), and ConfigView::updateListAll().
updateMenuList()
template<class P > void ConfigList::updateMenuList (P * parent, struct menu * menu)
Definition at line 102 of file qconf.cc.
 {
     struct menu* child;
     ConfigItem* item;
     ConfigItem* last;
     bool visible;
     enum prop_type type;
     if (!menu) {
         while ((item = parent->firstChild()))
             delete item;
         return;
     }
     last = parent->firstChild();
     if (last && !last->goParent)
         last = 0;
     for (child = menu->list; child; child = child->next) {
         item = last ? last->nextSibling() : parent->firstChild();
         type = child->prompt ? child->prompt->type : P_UNKNOWN;
         switch (mode) {
         case menuMode:
             if (!(child->flags & MENU_ROOT))
                 goto hide;
             break;
         case symbolMode:
             if (child->flags & MENU_ROOT)
                 goto hide;
             break;
         default:
             break;
         }
         visible = menu_is_visible(child);
         if (showAll || visible) {
             if (!item || item->menu != child)
                 item = new ConfigItem(parent, last, child, visible);
             else
                 item->testUpdateMenu(visible);
             if (mode == fullMode || mode == menuMode || type != P_MENU)
                 updateMenuList(item, child);
             else
                 updateMenuList(item, 0);
             last = item;
             continue;
         }
     hide:
         if (item && item->menu == child) {
             last = parent->firstChild();
             if (last == item)
                 last = 0;
             else while (last->nextSibling() != item)
                 last = last->nextSibling();
             delete item;
         }
     }
 }
References child(), fullMode, last, menu::list, ConfigItem::menu, menu_is_visible(), MENU_ROOT, menuMode, mode, child::next, P_MENU, P_UNKNOWN, parent(), showAll, symbolMode, ConfigItem::testUpdateMenu(), type, and visible().
Referenced by setRootMenu(), and updateList().
updateSelection
void ConfigList::updateSelection (void) slot
Definition at line 444 of file qconf.cc.
 {
     struct menu *menu;
     enum prop_type type;
     ConfigItem* item = (ConfigItem*)selectedItem();
     if (!item)
         return;
     cview->setHelp(item);
     menu = item->menu;
     if (!menu)
         return;
     type = menu->prompt ? menu->prompt->type : P_UNKNOWN;
     if (mode == menuMode && type == P_MENU)
         emit menuSelected(menu);
 }
References cview, ConfigItem::menu, menuMode, menuSelected(), mode, P_MENU, P_UNKNOWN, menu::prompt, ConfigMainWindow::setHelp(), type, and property::type.
Referenced by ConfigList().
Field Documentation
choiceNoPix
QPixmap ConfigList::choiceNoPix
Definition at line 132 of file qconf.h.
choiceYesPix
QPixmap ConfigList::choiceYesPix
Definition at line 132 of file qconf.h.
colMap
int ConfigList::colMap[colNr] private
Definition at line 142 of file qconf.h.
Referenced by addColumn(), changeValue(), ConfigList(), mapIdx(), and removeColumn().
colRevMap
int ConfigList::colRevMap[colNr] private
Definition at line 143 of file qconf.h.
Referenced by addColumn(), ConfigList(), contentsMouseReleaseEvent(), and removeColumn().
cview
ConfigMainWindow* ConfigList::cview protected
Definition at line 71 of file qconf.h.
Referenced by updateSelection().
disabledColorGroup
QColorGroup ConfigList::disabledColorGroup
Definition at line 138 of file qconf.h.
Referenced by ConfigList().
inactivedColorGroup
QColorGroup ConfigList::inactivedColorGroup
Definition at line 139 of file qconf.h.
Referenced by ConfigList().
menuBackPix
QPixmap ConfigList::menuBackPix
Definition at line 133 of file qconf.h.
menuInvPix
QPixmap ConfigList::menuInvPix
Definition at line 133 of file qconf.h.
menuPix
QPixmap ConfigList::menuPix
Definition at line 133 of file qconf.h.
mode
enum listMode ConfigList::mode
Definition at line 135 of file qconf.h.
Referenced by contentsMouseDoubleClickEvent(), contentsMouseReleaseEvent(), keyPressEvent(), ConfigMainWindow::listFocusChanged(), ConfigMainWindow::saveSettings(), ConfigMainWindow::showFullView(), ConfigMainWindow::showSingleView(), ConfigMainWindow::showSplitView(), updateList(), updateMenuList(), and updateSelection().
rootEntry
struct menu* ConfigList::rootEntry
Definition at line 137 of file qconf.h.
Referenced by contentsMouseReleaseEvent(), ConfigMainWindow::goBack(), keyPressEvent(), setParentMenu(), setRootMenu(), ConfigMainWindow::showFullView(), ConfigMainWindow::showSingleView(), ConfigMainWindow::showSplitView(), and updateList().
showAll
bool ConfigList::showAll
Definition at line 135 of file qconf.h.
Referenced by ConfigList(), ConfigMainWindow::ConfigMainWindow(), ConfigMainWindow::saveSettings(), ConfigMainWindow::setShowAll(), and updateMenuList().
showData
bool ConfigList::showData
Definition at line 135 of file qconf.h.
Referenced by ConfigList(), ConfigMainWindow::ConfigMainWindow(), reinit(), ConfigMainWindow::saveSettings(), and ConfigMainWindow::setShowData().
showName
bool ConfigList::showName
Definition at line 135 of file qconf.h.
Referenced by ConfigList(), ConfigMainWindow::ConfigMainWindow(), reinit(), ConfigMainWindow::saveSettings(), and ConfigMainWindow::setShowName().
showRange
bool ConfigList::showRange
Definition at line 135 of file qconf.h.
Referenced by ConfigList(), ConfigMainWindow::ConfigMainWindow(), reinit(), ConfigMainWindow::saveSettings(), and ConfigMainWindow::setShowRange().
symbolModPix
QPixmap ConfigList::symbolModPix
Definition at line 131 of file qconf.h.
symbolNoPix
QPixmap ConfigList::symbolNoPix
Definition at line 131 of file qconf.h.
symbolYesPix
QPixmap ConfigList::symbolYesPix
Definition at line 131 of file qconf.h.
updateAll
bool ConfigList::updateAll
Definition at line 129 of file qconf.h.
Referenced by updateListAll().
voidPix
QPixmap ConfigList::voidPix
Definition at line 133 of file qconf.h.
The documentation for this class was generated from the following files:
Userspace/apps/base/busybox/scripts/kconfig/qconf.h
Userspace/apps/base/busybox/scripts/kconfig/qconf.cc