Fennix Userspace: Userspace/musl/src/complex/clogl.c File Reference
clogl.c File Reference
#include "complex_impl.h"
Functions
long double complex clogl (long double complex z)
Function Documentation
clogl()
long double complex clogl (long double complex z)
Definition at line 10 of file clogl.c.
 {
     long double r, phi;
     r = cabsl(z);
     phi = cargl(z);
     return CMPLXL(logl(r), phi);
 }
References cabsl(), cargl(), CMPLXL, logl(), and r.
Referenced by casinl(), and cpowl().