Fennix: Userspace/musl/src/linux/setgroups.c File Reference
setgroups.c File Reference
#include <unistd.h>
#include <signal.h>
#include "syscall.h"
#include "libc.h"
Data Structures
struct ctx
Macros
#define _GNU_SOURCE
Functions
static void do_setgroups (void *p)
int setgroups (size_t count, const gid_t list[])
Data Structure Documentation
ctx
struct ctx
Definition at line 7 of file setgroups.c.
Data Fields
int amode
size_t count
int eid
int err
int fd
const char * filename
int id
unsigned long lim[2]
const gid_t * list
int nr
int p
int res
int ret
int sid
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file setgroups.c.
Function Documentation
do_setgroups()
static void do_setgroups (void * p) static
Definition at line 13 of file setgroups.c.
 {
     struct ctx *c = p;
     if (c->ret<0) return;
     int ret = __syscall(SYS_setgroups, c->count, c->list);
     if (ret && !c->ret) {
         /* If one thread fails to set groups after another has already
          * succeeded, forcibly killing the process is the only safe
          * thing to do. State is inconsistent and dangerous. Use
          * SIGKILL because it is uncatchable. */
         __block_all_sigs(0);
         __syscall(SYS_kill, __syscall(SYS_getpid), SIGKILL);
     }
     c->ret = ret;
 }
References __block_all_sigs(), __syscall, c, p, ctx::ret, and SIGKILL.
Referenced by setgroups().
setgroups()
int setgroups (size_t count, const gid_t list[])
Definition at line 29 of file setgroups.c.
 {
     /* ret is initially nonzero so that failure of the first thread does not
      * trigger the safety kill above. */
     struct ctx c = { .count = count, .list = list, .ret = 1 };
     __synccall(do_setgroups, &c);
     return __syscall_ret(c.ret);
 }
References __synccall(), __syscall_ret(), c, count, do_setgroups(), and list().
Referenced by chpst_main(), httpd_main(), inetd_main(), initgroups(), nsenter_main(), and start_stop_daemon_main().