Fennix: Userspace/apps/base/busybox/archival/ar.c File Reference
ar.c File Reference
#include "libbb.h"
#include "bb_archive.h"
#include "ar_.h"
Functions
static void FAST_FUNC header_verbose_list_ar (const file_header_t *file_header)
int ar_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
ar_main()
int ar_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 228 of file ar.c.
 {
     archive_handle_t *archive_handle;
     unsigned opt, t;
     enum {
         OPT_VERBOSE       = (1 << 0),
         OPT_PRESERVE_DATE = (1 << 1),
         /* "ar r" implies create, but warns about it. c suppresses warning.
          * bbox accepts but ignores it: */
         OPT_CREATE        = (1 << 2),
         CMD_PRINT         = (1 << 3),
         FIRST_CMD         = CMD_PRINT,
         CMD_LIST          = (1 << 4),
         CMD_EXTRACT       = (1 << 5),
         CMD_INSERT        = ((1 << 6) * ENABLE_FEATURE_AR_CREATE),
     };
     archive_handle = init_handle();
     /* prepend '-' to the first argument if required */
     if (argv[1] && argv[1][0] != '-' && argv[1][0] != '\0')
         argv[1] = xasprintf("-%s", argv[1]);
     opt = getopt32(argv, "^"
         "voc""ptx"IF_FEATURE_AR_CREATE("r")
         "\0"
         /* -1: at least one arg is reqd */
         /* one of p,t,x[,r] is required */
         "-1:p:t:x"IF_FEATURE_AR_CREATE(":r")
     );
     argv += optind;
     t = opt / FIRST_CMD;
     if (t & (t-1)) /* more than one of p,t,x[,r] are specified */
         bb_show_usage();
     if (opt & CMD_PRINT) {
         archive_handle->action_data = data_extract_to_stdout;
     }
     if (opt & CMD_LIST) {
         archive_handle->action_header = header_list;
     }
     if (opt & CMD_EXTRACT) {
         archive_handle->action_data = data_extract_all;
     }
     if (opt & OPT_PRESERVE_DATE) {
         archive_handle->ah_flags |= ARCHIVE_RESTORE_DATE;
     }
     if (opt & OPT_VERBOSE) {
         archive_handle->action_header = header_verbose_list_ar;
     }
 #if ENABLE_FEATURE_AR_CREATE
     archive_handle->ar__name = *argv;
 #endif
     archive_handle->src_fd = xopen(*argv++,
             (opt & CMD_INSERT)
                 ? O_RDWR | O_CREAT
                 : O_RDONLY
     );
     if (*argv)
         archive_handle->filter = filter_accept_list;
     while (*argv) {
         llist_add_to_end(&archive_handle->accept, *argv++);
     }
 #if ENABLE_FEATURE_AR_CREATE
     if (opt & CMD_INSERT)
         return write_ar_archive(archive_handle);
 #endif
     unpack_ar_archive(archive_handle);
     return EXIT_SUCCESS;
 }
References archive_handle_t::accept, archive_handle_t::action_data, archive_handle_t::action_header, archive_handle_t::ah_flags, ARCHIVE_RESTORE_DATE, argv, bb_show_usage(), data_extract_all(), data_extract_to_stdout(), EXIT_SUCCESS, archive_handle_t::filter, filter_accept_list(), getopt32(), header_list(), header_verbose_list_ar(), init_handle(), llist_add_to_end(), O_CREAT, O_RDONLY, O_RDWR, opt, OPT_CREATE, OPT_VERBOSE, optind, archive_handle_t::src_fd, t, unpack_ar_archive(), xasprintf(), and xopen().
header_verbose_list_ar()
static void FAST_FUNC header_verbose_list_ar (const file_header_t * file_header) static
Definition at line 197 of file ar.c.
 {
     char mode[12];
     char *mtime;
     bb_mode_string(mode, file_header->mode);
     mtime = ctime(&file_header->mtime);
     mtime[16] = ' ';
     memmove(&mtime[17], &mtime[20], 4);
     mtime[21] = '\0';
     printf("%s %u/%u%7"OFF_FMT"u %s %s\n", &mode[1],
             (int)file_header->uid, (int)file_header->gid,
             file_header->size,
             &mtime[4], file_header->name
     );
 }
References bb_mode_string(), ctime(), file_header_t::gid, memmove, file_header_t::mode, mtime, file_header_t::mtime, file_header_t::name, OFF_FMT, printf, file_header_t::size, and file_header_t::uid.
Referenced by ar_main().