Fennix: Userspace/apps/base/bash/lib/readline/compat.c File Reference
compat.c File Reference
#include <stdio.h>
#include "rlstdc.h"
#include "rltypedefs.h"
Macros
#define READLINE_LIBRARY
Functions
void rl_free_undo_list (void)
int rl_maybe_save_line (void)
int rl_maybe_unsave_line (void)
int rl_maybe_replace_line (void)
int rl_crlf (void)
int rl_ding (void)
int rl_alphabetic (int)
char ** rl_completion_matches (const char *, rl_compentry_func_t *)
char * rl_username_completion_function (const char *, int)
char * rl_filename_completion_function (const char *, int)
void free_undo_list (void)
int maybe_replace_line (void)
int maybe_save_line (void)
int maybe_unsave_line (void)
int ding (void)
int crlf (void)
int alphabetic (int c)
char ** completion_matches (const char *s, rl_compentry_func_t *f)
char * username_completion_function (const char *s, int i)
char * filename_completion_function (const char *s, int i)
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file compat.c.
Function Documentation
alphabetic()
int alphabetic (int c)
Definition at line 85 of file compat.c.
 {
   return rl_alphabetic (c);
 }
References c, and rl_alphabetic().
completion_matches()
char** completion_matches (const char * s, rl_compentry_func_t * f)
Definition at line 91 of file compat.c.
 {
   return rl_completion_matches (s, f);
 }
References f, and rl_completion_matches().
crlf()
int crlf (void)
Definition at line 79 of file compat.c.
 {
   return rl_crlf ();
 }
References rl_crlf().
ding()
int ding (void)
Definition at line 73 of file compat.c.
 {
   return rl_ding ();
 }
References rl_ding().
filename_completion_function()
char* filename_completion_function (const char * s, int i)
Definition at line 103 of file compat.c.
 {
   return rl_filename_completion_function (s, i);
 }
References i, and rl_filename_completion_function().
free_undo_list()
void free_undo_list (void)
Definition at line 49 of file compat.c.
 {
   rl_free_undo_list ();
 }
References rl_free_undo_list().
maybe_replace_line()
int maybe_replace_line (void)
Definition at line 55 of file compat.c.
 {
   return rl_maybe_replace_line ();
 }
References rl_maybe_replace_line().
maybe_save_line()
int maybe_save_line (void)
Definition at line 61 of file compat.c.
 {
   return rl_maybe_save_line ();
 }
References rl_maybe_save_line().
maybe_unsave_line()
int maybe_unsave_line (void)
Definition at line 67 of file compat.c.
 {
   return rl_maybe_unsave_line ();
 }
References rl_maybe_unsave_line().
rl_alphabetic()
int rl_alphabetic (int c)
Definition at line 73 of file util.c.
 {
   if (_rl_alphabetic_p (c))
     return (1);
   return (_rl_allow_pathname_alphabetic_chars &&
         strchr (pathname_alphabetic_chars, c) != NULL);
 }
References _rl_allow_pathname_alphabetic_chars, _rl_alphabetic_p, c, NULL, pathname_alphabetic_chars, and strchr().
Referenced by alphabetic().
rl_completion_matches()
char** rl_completion_matches (const char * text, rl_compentry_func_t * entry_function)
Definition at line 2198 of file complete.c.
 {
   register int i;
   /* Number of slots in match_list. */
   int match_list_size;
   /* The list of matches. */
   char **match_list;
   /* Number of matches actually found. */
   int matches;
   /* Temporary string binder. */
   char *string;
   matches = 0;
   match_list_size = 10;
   match_list = (char **)xmalloc ((match_list_size + 1) * sizeof (char *));
   match_list[1] = (char *)NULL;
   while (string = (*entry_function) (text, matches))
     {
       if (RL_SIG_RECEIVED ())
     {
       /* Start at 1 because we don't set matches[0] in this function.
          Only free the list members if we're building match list from
          rl_filename_completion_function, since we know that doesn't
          free the strings it returns. */
       if (entry_function == rl_filename_completion_function)
         {
           for (i = 1; match_list[i]; i++)
         xfree (match_list[i]);
         }
       xfree (match_list);
       match_list = 0;
       match_list_size = 0;
       matches = 0;
       RL_CHECK_SIGNALS ();
     }
       if (matches + 1 >= match_list_size)
     match_list = (char **)xrealloc
       (match_list, ((match_list_size += 10) + 1) * sizeof (char *));
       if (match_list == 0)
     return (match_list);
       match_list[++matches] = string;
       match_list[matches + 1] = (char *)NULL;
     }
   /* If there were any matches, then look through them finding out the
      lowest common denominator.  That then becomes match_list[0]. */
   if (matches)
     compute_lcd_of_matches (match_list, matches, text);
   else              /* There were no matches. */
     {
       xfree (match_list);
       match_list = (char **)NULL;
     }
   return (match_list);
 }
References compute_lcd_of_matches(), i, NULL, RL_CHECK_SIGNALS, rl_filename_completion_function(), RL_SIG_RECEIVED, string, xfree, xmalloc, and xrealloc.
Referenced by completion_matches(), and fileman_completion().
rl_crlf()
int rl_crlf (void)
Definition at line 734 of file terminal.c.
 {
 #if defined (NEW_TTY_DRIVER) || defined (__MINT__)
   if (_rl_term_cr)
     tputs (_rl_term_cr, 1, _rl_output_character_function);
 #endif /* NEW_TTY_DRIVER || __MINT__ */
   putc ('\n', _rl_out_stream);
   return 0;
 }
References _rl_out_stream, _rl_output_character_function(), _rl_term_cr, putc(), and tputs().
Referenced by _rl_clear_screen(), _rl_redisplay_after_sigwinch(), _rl_update_final(), crlf(), display_matches(), rl_display_match_list(), and rl_print_last_kbd_macro().
rl_ding()
int rl_ding (void)
Definition at line 756 of file terminal.c.
 {
   if (_rl_echoing_p)
     {
       switch (_rl_bell_preference)
         {
     case NO_BELL:
     default:
       break;
     case VISIBLE_BELL:
       if (_rl_visible_bell)
         {
 #ifdef __DJGPP__
           ScreenVisualBell ();
 #else
           tputs (_rl_visible_bell, 1, _rl_output_character_function);
 #endif
           break;
         }
       /* FALLTHROUGH */
     case AUDIBLE_BELL:
       fprintf (stderr, "\007");
       fflush (stderr);
       break;
         }
       return (0);
     }
   return (-1);
 }
References _rl_bell_preference, _rl_echoing_p, _rl_output_character_function(), _rl_visible_bell, AUDIBLE_BELL, fflush(), fprintf(), NO_BELL, stderr, tputs(), and VISIBLE_BELL.
Referenced by _rl_abort_internal(), _rl_arg_overflow(), _rl_char_search_internal(), _rl_dispatch_subseq(), _rl_isearch_dispatch(), _rl_nsearch_dispatch(), _rl_nsearch_dosearch(), _rl_overwrite_rubout(), _rl_rubout_char(), _rl_vi_goto_mark(), _rl_vi_set_mark(), ding(), get_y_or_n(), noninc_dosearch(), rl_arrow_keys(), rl_backward_byte(), rl_backward_kill_line(), rl_call_last_kbd_macro(), rl_change_case(), rl_complete_internal(), rl_delete(), rl_discard_argument(), rl_do_undo(), rl_exchange_point_and_mark(), rl_fetch_history(), rl_forward_byte(), rl_get_previous_history(), rl_history_search_internal(), rl_maybe_unsave_line(), rl_menu_complete(), rl_noninc_forward_search_again(), rl_noninc_reverse_search_again(), rl_old_menu_complete(), rl_print_last_kbd_macro(), rl_revert_line(), rl_rubout(), rl_transpose_chars(), rl_transpose_words(), rl_tty_status(), rl_undo_command(), rl_unix_filename_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), rl_vi_change_to(), rl_vi_delete(), rl_vi_delete_to(), rl_vi_end_word(), rl_vi_match(), rl_vi_next_word(), rl_vi_overstrike_delete(), rl_vi_prev_word(), rl_vi_redo(), rl_vi_rubout(), rl_vi_search(), rl_vi_unix_word_rubout(), rl_vi_yank_to(), and rl_yank_nth_arg_internal().
rl_filename_completion_function()
char* rl_filename_completion_function (const char * text, int state)
Definition at line 2456 of file complete.c.
 {
   static DIR *directory = (DIR *)NULL;
   static char *filename = (char *)NULL;
   static char *dirname = (char *)NULL;
   static char *users_dirname = (char *)NULL;
   static int filename_len;
   char *temp, *dentry, *convfn;
   int dirlen, dentlen, convlen;
   int tilde_dirname;
   struct dirent *entry;
   /* If we don't have any state, then do some initialization. */
   if (state == 0)
     {
       /* If we were interrupted before closing the directory or reading
      all of its contents, close it. */
       if (directory)
     {
       closedir (directory);
       directory = (DIR *)NULL;
     }
       FREE (dirname);
       FREE (filename);
       FREE (users_dirname);
       filename = savestring (text);
       if (*text == 0)
     text = ".";
       dirname = savestring (text);
       temp = strrchr (dirname, '/');
 #if defined (__MSDOS__) || defined (_WIN32)
       /* special hack for //X/... */
       if (dirname[0] == '/' && dirname[1] == '/' && ISALPHA ((unsigned char)dirname[2]) && dirname[3] == '/')
         temp = strrchr (dirname + 3, '/');
 #endif
       if (temp)
     {
       strcpy (filename, ++temp);
       *temp = '\0';
     }
 #if defined (__MSDOS__) || (defined (_WIN32) && !defined (__CYGWIN__))
       /* searches from current directory on the drive */
       else if (ISALPHA ((unsigned char)dirname[0]) && dirname[1] == ':')
         {
           strcpy (filename, dirname + 2);
           dirname[2] = '\0';
         }
 #endif
       else
     {
       dirname[0] = '.';
       dirname[1] = '\0';
     }
       /* We aren't done yet.  We also support the "~user" syntax. */
       /* Save the version of the directory that the user typed, dequoting
      it if necessary. */
       if (rl_completion_found_quote && rl_filename_dequoting_function)
     users_dirname = (*rl_filename_dequoting_function) (dirname, rl_completion_quote_character);
       else
     users_dirname = savestring (dirname);
       tilde_dirname = 0;
       if (*dirname == '~')
     {
       temp = tilde_expand (dirname);
       xfree (dirname);
       dirname = temp;
       tilde_dirname = 1;
     }
       /* We have saved the possibly-dequoted version of the directory name
      the user typed.  Now transform the directory name we're going to
      pass to opendir(2).  The directory rewrite hook modifies only the
      directory name; the directory completion hook modifies both the
      directory name passed to opendir(2) and the version the user
      typed.  Both the directory completion and rewrite hooks should perform
      any necessary dequoting.  The hook functions return 1 if they modify
      the directory name argument.  If either hook returns 0, it should
      not modify the directory name pointer passed as an argument. */
       if (rl_directory_rewrite_hook)
     (*rl_directory_rewrite_hook) (&dirname);
       else if (rl_directory_completion_hook && (*rl_directory_completion_hook) (&dirname))
     {
       xfree (users_dirname);
       users_dirname = savestring (dirname);
     }
       else if (tilde_dirname == 0 && rl_completion_found_quote && rl_filename_dequoting_function)
     {
       /* delete single and double quotes */
       xfree (dirname);
       dirname = savestring (users_dirname);
     }
       directory = opendir (dirname);
       /* Now dequote a non-null filename.  FILENAME will not be NULL, but may
      be empty. */
       if (*filename && rl_completion_found_quote && rl_filename_dequoting_function)
     {
       /* delete single and double quotes */
       temp = (*rl_filename_dequoting_function) (filename, rl_completion_quote_character);
       xfree (filename);
       filename = temp;
     }
       filename_len = strlen (filename);
       rl_filename_completion_desired = 1;
     }
   /* At this point we should entertain the possibility of hacking wildcarded
      filenames, like /usr/man/man<WILD>/te<TAB>.  If the directory name
      contains globbing characters, then build an array of directories, and
      then map over that list while completing. */
   /* *** UNIMPLEMENTED *** */
   /* Now that we have some state, we can read the directory. */
   entry = (struct dirent *)NULL;
   while (directory && (entry = readdir (directory)))
     {
       convfn = dentry = entry->d_name;
       convlen = dentlen = D_NAMLEN (entry);
       if (rl_filename_rewrite_hook)
     {
       convfn = (*rl_filename_rewrite_hook) (dentry, dentlen);
       convlen = (convfn == dentry) ? dentlen : strlen (convfn);
     }
       /* Special case for no filename.  If the user has disabled the
          `match-hidden-files' variable, skip filenames beginning with `.'.
      All other entries except "." and ".." match. */
       if (filename_len == 0)
     {
       if (_rl_match_hidden_files == 0 && HIDDEN_FILE (convfn))
         continue;
       if (convfn[0] != '.' ||
            (convfn[1] && (convfn[1] != '.' || convfn[2])))
         break;
     }
       else
     {
       if (complete_fncmp (convfn, convlen, filename, filename_len))
         break;
     }
     }
   if (entry == 0)
     {
       if (directory)
     {
       closedir (directory);
       directory = (DIR *)NULL;
     }
       if (dirname)
     {
       xfree (dirname);
       dirname = (char *)NULL;
     }
       if (filename)
     {
       xfree (filename);
       filename = (char *)NULL;
     }
       if (users_dirname)
     {
       xfree (users_dirname);
       users_dirname = (char *)NULL;
     }
       return (char *)NULL;
     }
   else
     {
       /* dirname && (strcmp (dirname, ".") != 0) */
       if (dirname && (dirname[0] != '.' || dirname[1]))
     {
       if (rl_complete_with_tilde_expansion && *users_dirname == '~')
         {
           dirlen = strlen (dirname);
           temp = (char *)xmalloc (2 + dirlen + D_NAMLEN (entry));
           strcpy (temp, dirname);
           /* Canonicalization cuts off any final slash present.  We
          may need to add it back. */
           if (dirname[dirlen - 1] != '/')
             {
               temp[dirlen++] = '/';
               temp[dirlen] = '\0';
             }
         }
       else
         {
           dirlen = strlen (users_dirname);
           temp = (char *)xmalloc (2 + dirlen + D_NAMLEN (entry));
           strcpy (temp, users_dirname);
           /* Make sure that temp has a trailing slash here. */
           if (users_dirname[dirlen - 1] != '/')
         temp[dirlen++] = '/';
         }
       strcpy (temp + dirlen, convfn);
     }
       else
     temp = savestring (convfn);
       if (convfn != dentry)
     xfree (convfn);
       return (temp);
     }
 }
References _rl_match_hidden_files, closedir(), complete_fncmp(), D_NAMLEN, directory, dirname, FREE, HIDDEN_FILE, ISALPHA, NULL, opendir(), readdir(), rl_complete_with_tilde_expansion, rl_completion_found_quote, rl_completion_quote_character, rl_directory_completion_hook, rl_directory_rewrite_hook, rl_filename_completion_desired, rl_filename_dequoting_function, rl_filename_rewrite_hook, savestring(), state, strcpy, strlen(), strrchr(), tilde_expand(), xfree, and xmalloc.
Referenced by filename_completion_function().
rl_free_undo_list()
void rl_free_undo_list (void)
Definition at line 117 of file undo.c.
 {
   UNDO_LIST *release, *orig_list;
   orig_list = rl_undo_list;
   _rl_free_undo_list (rl_undo_list);
   rl_undo_list = (UNDO_LIST *)NULL;
   _hs_replace_history_data (-1, (histdata_t *)orig_list, (histdata_t *)NULL);
 }
References _hs_replace_history_data(), _rl_free_undo_list(), NULL, and rl_undo_list.
Referenced by _rl_nsearch_dosearch(), free_undo_list(), make_history_line_current(), readline_internal_teardown(), rl_free_line_state(), rl_replace_line(), and rl_vi_movement_mode().
rl_maybe_replace_line()
int rl_maybe_replace_line (void)
Definition at line 330 of file misc.c.
 {
   HIST_ENTRY *temp;
   temp = current_history ();
   /* If the current line has changed, save the changes. */
   if (temp && ((UNDO_LIST *)(temp->data) != rl_undo_list))
     {
       temp = replace_history_entry (where_history (), rl_line_buffer, (histdata_t)rl_undo_list);
       xfree (temp->line);
       FREE (temp->timestamp);
       xfree (temp);
     }
   return 0;
 }
References current_history(), _hist_entry::data, FREE, _hist_entry::line, replace_history_entry(), rl_line_buffer, rl_undo_list, _hist_entry::timestamp, where_history(), and xfree.
Referenced by _rl_isearch_init(), and maybe_replace_line().
rl_maybe_save_line()
int rl_maybe_save_line (void)
Definition at line 369 of file misc.c.
 {
   if (_rl_saved_line_for_history == 0)
     {
       _rl_saved_line_for_history = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
       _rl_saved_line_for_history->line = savestring (rl_line_buffer);
       _rl_saved_line_for_history->timestamp = (char *)NULL;
       _rl_saved_line_for_history->data = (char *)rl_undo_list;
     }
   return 0;
 }
References _rl_saved_line_for_history, _hist_entry::data, _hist_entry::line, NULL, rl_line_buffer, rl_undo_list, savestring(), _hist_entry::timestamp, and xmalloc.
Referenced by _rl_nsearch_init(), maybe_save_line(), and rl_history_search_internal().
rl_maybe_unsave_line()
int rl_maybe_unsave_line (void)
Definition at line 348 of file misc.c.
 {
   if (_rl_saved_line_for_history)
     {
       /* Can't call with `1' because rl_undo_list might point to an undo
      list from a history entry, as in rl_replace_from_history() below. */
       rl_replace_line (_rl_saved_line_for_history->line, 0);
       rl_undo_list = (UNDO_LIST *)_rl_saved_line_for_history->data;
       /* Doesn't free `data'. */
       _rl_free_history_entry (_rl_saved_line_for_history);
       _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
       rl_point = rl_end;    /* rl_replace_line sets rl_end */
     }
   else
     rl_ding ();
   return 0;
 }
References _rl_free_history_entry(), _rl_saved_line_for_history, _hist_entry::data, _hist_entry::line, NULL, rl_ding(), rl_end, rl_point, rl_replace_line(), and rl_undo_list.
Referenced by _rl_nsearch_abort(), maybe_unsave_line(), noninc_dosearch(), and rl_history_search_internal().
rl_username_completion_function()
char* rl_username_completion_function (const char * text, int state)
Definition at line 2266 of file complete.c.
 {
 #if defined (__WIN32__) || defined (__OPENNT)
   return (char *)NULL;
 #else /* !__WIN32__ && !__OPENNT) */
   static char *username = (char *)NULL;
   static struct passwd *entry;
   static int namelen, first_char, first_char_loc;
   char *value;
   if (state == 0)
     {
       FREE (username);
       first_char = *text;
       first_char_loc = first_char == '~';
       username = savestring (&text[first_char_loc]);
       namelen = strlen (username);
 #if defined (HAVE_GETPWENT)
       setpwent ();
 #endif
     }
 #if defined (HAVE_GETPWENT)
   while (entry = getpwent ())
     {
       /* Null usernames should result in all users as possible completions. */
       if (namelen == 0 || (STREQN (username, entry->pw_name, namelen)))
     break;
     }
 #endif
   if (entry == 0)
     {
 #if defined (HAVE_GETPWENT)
       endpwent ();
 #endif
       return ((char *)NULL);
     }
   else
     {
       value = (char *)xmalloc (2 + strlen (entry->pw_name));
       *value = *text;
       strcpy (value + first_char_loc, entry->pw_name);
       if (first_char == '~')
     rl_filename_completion_desired = 1;
       return (value);
     }
 #endif /* !__WIN32__ && !__OPENNT */
 }
References endpwent(), FREE, getpwent(), NULL, rl_filename_completion_desired, savestring(), setpwent(), state, strcpy, STREQN, strlen(), value, and xmalloc.
Referenced by username_completion_function().
username_completion_function()
char* username_completion_function (const char * s, int i)
Definition at line 97 of file compat.c.
 {
   return rl_username_completion_function (s, i);
 }
References i, and rl_username_completion_function().