Fennix Userspace: Userspace/apps/base/busybox/archival/dpkg_deb.c File Reference
dpkg_deb.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Macros
#define DPKG_DEB_OPT_CONTENTS 1
#define DPKG_DEB_OPT_CONTROL 2
#define DPKG_DEB_OPT_FIELD 4
#define DPKG_DEB_OPT_EXTRACT_VERBOSE 8
#define DPKG_DEB_OPT_EXTRACT 16
Functions
int dpkg_deb_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
DPKG_DEB_OPT_CONTENTS
#define DPKG_DEB_OPT_CONTENTS 1
Definition at line 39 of file dpkg_deb.c.
DPKG_DEB_OPT_CONTROL
#define DPKG_DEB_OPT_CONTROL 2
Definition at line 40 of file dpkg_deb.c.
DPKG_DEB_OPT_EXTRACT
#define DPKG_DEB_OPT_EXTRACT 16
Definition at line 43 of file dpkg_deb.c.
DPKG_DEB_OPT_EXTRACT_VERBOSE
#define DPKG_DEB_OPT_EXTRACT_VERBOSE 8
Definition at line 42 of file dpkg_deb.c.
DPKG_DEB_OPT_FIELD
#define DPKG_DEB_OPT_FIELD 4
Definition at line 41 of file dpkg_deb.c.
Function Documentation
dpkg_deb_main()
int dpkg_deb_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 46 of file dpkg_deb.c.
 {
     archive_handle_t *ar_archive;
     archive_handle_t *tar_archive;
     llist_t *control_tar_llist = NULL;
     unsigned opt;
     const char *extract_dir;
     /* Setup the tar archive handle */
     tar_archive = init_handle();
     /* Setup an ar archive handle that refers to the gzip sub archive */
     ar_archive = init_handle();
     ar_archive->dpkg__sub_archive = tar_archive;
     ar_archive->filter = filter_accept_list_reassign;
     llist_add_to(&ar_archive->accept, (char*)"data.tar");
     llist_add_to(&control_tar_llist, (char*)"control.tar");
 #if ENABLE_FEATURE_SEAMLESS_GZ
     llist_add_to(&ar_archive->accept, (char*)"data.tar.gz");
     llist_add_to(&control_tar_llist, (char*)"control.tar.gz");
 #endif
 #if ENABLE_FEATURE_SEAMLESS_BZ2
     llist_add_to(&ar_archive->accept, (char*)"data.tar.bz2");
     llist_add_to(&control_tar_llist, (char*)"control.tar.bz2");
 #endif
 #if ENABLE_FEATURE_SEAMLESS_LZMA
     llist_add_to(&ar_archive->accept, (char*)"data.tar.lzma");
     llist_add_to(&control_tar_llist, (char*)"control.tar.lzma");
 #endif
 #if ENABLE_FEATURE_SEAMLESS_XZ
     llist_add_to(&ar_archive->accept, (char*)"data.tar.xz");
     llist_add_to(&control_tar_llist, (char*)"control.tar.xz");
 #endif
     /* Must have 1 or 2 args */
     opt = getopt32(argv, "^" "cefXx"
             "\0" "-1:?2:c--efXx:e--cfXx:f--ceXx:X--cefx:x--cefX"
     );
     argv += optind;
     //argc -= optind;
     extract_dir = argv[1];
     if (opt & DPKG_DEB_OPT_CONTENTS) { // -c
         tar_archive->action_header = header_verbose_list;
         if (extract_dir)
             bb_show_usage();
     }
     if (opt & DPKG_DEB_OPT_FIELD) { // -f
         /* Print the entire control file */
 //TODO: standard tool accepts an optional list of fields to print
         ar_archive->accept = control_tar_llist;
         llist_add_to(&(tar_archive->accept), (char*)"./control");
         tar_archive->filter = filter_accept_list;
         tar_archive->action_data = data_extract_to_stdout;
         if (extract_dir)
             bb_show_usage();
     }
     if (opt & DPKG_DEB_OPT_CONTROL) { // -e
         ar_archive->accept = control_tar_llist;
         tar_archive->action_data = data_extract_all;
         if (!extract_dir)
             extract_dir = "./DEBIAN";
     }
     if (opt & (DPKG_DEB_OPT_EXTRACT_VERBOSE | DPKG_DEB_OPT_EXTRACT)) { // -Xx
         if (opt & DPKG_DEB_OPT_EXTRACT_VERBOSE)
             tar_archive->action_header = header_list;
         tar_archive->action_data = data_extract_all;
         if (!extract_dir)
             bb_show_usage();
     }
     /* Standard tool supports "-" */
     tar_archive->src_fd = ar_archive->src_fd = xopen_stdin(argv[0]);
     if (extract_dir) {
         mkdir(extract_dir, 0777); /* bb_make_directory(extract_dir, 0777, 0) */
         xchdir(extract_dir);
     }
     /* Do it */
     unpack_ar_archive(ar_archive);
     /* Cleanup */
     if (ENABLE_FEATURE_CLEAN_UP)
         close(ar_archive->src_fd);
     return EXIT_SUCCESS;
 }
References archive_handle_t::accept, archive_handle_t::action_data, archive_handle_t::action_header, argv, bb_show_usage(), close(), data_extract_all(), data_extract_to_stdout(), DPKG_DEB_OPT_CONTENTS, DPKG_DEB_OPT_CONTROL, DPKG_DEB_OPT_EXTRACT, DPKG_DEB_OPT_EXTRACT_VERBOSE, DPKG_DEB_OPT_FIELD, EXIT_SUCCESS, archive_handle_t::filter, filter_accept_list(), filter_accept_list_reassign(), getopt32(), header_list(), header_verbose_list(), init_handle(), llist_add_to(), mkdir(), NULL, opt, optind, archive_handle_t::src_fd, unpack_ar_archive(), xchdir(), and xopen_stdin().