Fennix: Userspace/mlibc/options/ansi/include/stdio.h File Reference
stdio.h File Reference
#include <abi-bits/seek-whence.h>
#include <bits/null.h>
#include <bits/size_t.h>
#include <mlibc-config.h>
#include <bits/ssize_t.h>
#include <stdarg.h>
Data Structures
struct __mlibc_file_base
Macros
#define __need___va_list
#define __MLIBC_EOF_BIT 1
#define __MLIBC_ERROR_BIT 2
#define _IOFBF 1
#define _IOLBF 2
#define _IONBF 3
#define BUFSIZ 512
#define EOF (-1)
#define FOPEN_MAX 1024
#define FILENAME_MAX 256
#define L_tmpnam 256
#define TMP_MAX 1024
Typedefs
typedef struct __mlibc_file_base FILE
typedef size_t fpos_t
Functions
int remove (const char *filename)
int rename (const char *old_path, const char *new_path)
int renameat (int olddirfd, const char *old_path, int newdirfd, const char *new_path)
FILE * tmpfile (void)
char * tmpnam (char *buffer)
int fclose (FILE *stream)
int fflush (FILE *stream)
FILE * fopen (const char *__restrict filename, const char *__restrict mode)
FILE * freopen (const char *__restrict filename, const char *__restrict mode, FILE *__restrict stream)
void setbuf (FILE *__restrict stream, char *__restrict buffer)
int setvbuf (FILE *__restrict stream, char *__restrict buffer, int mode, size_t size)
void setlinebuf (FILE *stream)
void setbuffer (FILE *, char *, size_t)
__attribute__ ((format(gnu_printf, 2, 3))) int fprintf(FILE *__restrict stream
const char *__restrict __attribute__ ((format(gnu_scanf, 2, 3))) int fscanf(FILE *__restrict stream
const char *__restrict const char *__restrict __attribute__ ((format(gnu_printf, 1, 2))) int printf(const char *__restrict format
const char *__restrict const char *__restrict __attribute__ ((format(gnu_scanf, 1, 2))) int scanf(const char *__restrict format
const char *__restrict const char *__restrict __attribute__ ((format(gnu_printf, 3, 4))) int snprintf(char *__restrict buffer
const char *__restrict const char *__restrict size_t const char *__restrict const char *__restrict const char *__restrict __attribute__ ((format(gnu_printf, 2, 0))) int vfprintf(FILE *__restrict stream
__attribute__ ((format(gnu_scanf, 2, 0))) int vfscanf(FILE *__restrict stream
__attribute__ ((format(gnu_printf, 1, 0))) int vprintf(const char *__restrict format
__attribute__ ((format(gnu_scanf, 1, 0))) int vscanf(const char *__restrict format
__attribute__ ((format(gnu_printf, 3, 0))) int vsnprintf(char *__restrict buffer
int fgetc (FILE *stream)
char * fgets (char *__restrict buffer, size_t max_size, FILE *__restrict stream)
int fputc (int c, FILE *stream)
int fputs (const char *__restrict string, FILE *__restrict stream)
char * gets (char *s)
int getc (FILE *stream)
int getchar (void)
int putc (int c, FILE *stream)
int putchar (int c)
int puts (const char *string)
int ungetc (int c, FILE *stream)
size_t fread (void *__restrict buffer, size_t size, size_t count, FILE *__restrict stream)
size_t fwrite (const void *__restrict buffer, size_t size, size_t count, FILE *__restrict stream)
int fgetpos (FILE *__restrict stream, fpos_t *__restrict position)
int fseek (FILE *stream, long offset, int whence)
int fsetpos (FILE *stream, const fpos_t *position)
long ftell (FILE *stream)
void rewind (FILE *stream)
void clearerr (FILE *stream)
int feof (FILE *stream)
int ferror (FILE *stream)
void perror (const char *string)
int getc_unlocked (FILE *)
int getchar_unlocked (void)
int putc_unlocked (int, FILE *)
int putchar_unlocked (int)
ssize_t getline (char **, size_t *, FILE *)
ssize_t getdelim (char **, size_t *, int, FILE *)
int asprintf (char **, const char *,...)
void flockfile (FILE *)
void funlockfile (FILE *)
int ftrylockfile (FILE *)
void clearerr_unlocked (FILE *)
int feof_unlocked (FILE *)
int ferror_unlocked (FILE *)
int fileno_unlocked (FILE *)
int fflush_unlocked (FILE *)
int fgetc_unlocked (FILE *)
int fputc_unlocked (int, FILE *)
size_t fread_unlocked (void *__restrict, size_t, size_t, FILE *__restrict)
size_t fwrite_unlocked (const void *__restrict, size_t, size_t, FILE *__restrict)
char * fgets_unlocked (char *, int, FILE *)
int fputs_unlocked (const char *, FILE *)
Variables
FILE * stderr
FILE * stdin
FILE * stdout
const char *__restrict format
const char *__restrict const char *__restrict size_t max_size
const char *__restrict const char *__restrict size_t const char *__restrict const char *__restrict const char *__restrict const char *__restrict __gnuc_va_list args
const char __gnuc_va_list
Macro Definition Documentation
__MLIBC_EOF_BIT
#define __MLIBC_EOF_BIT 1
Definition at line 24 of file stdio.h.
__MLIBC_ERROR_BIT
#define __MLIBC_ERROR_BIT 2
Definition at line 25 of file stdio.h.
__need___va_list
#define __need___va_list
Definition at line 19 of file stdio.h.
_IOFBF
#define _IOFBF 1
Definition at line 68 of file stdio.h.
_IOLBF
#define _IOLBF 2
Definition at line 69 of file stdio.h.
_IONBF
#define _IONBF 3
Definition at line 70 of file stdio.h.
BUFSIZ
#define BUFSIZ 512
Definition at line 72 of file stdio.h.
EOF
#define EOF (-1)
Definition at line 74 of file stdio.h.
FILENAME_MAX
#define FILENAME_MAX 256
Definition at line 77 of file stdio.h.
FOPEN_MAX
#define FOPEN_MAX 1024
Definition at line 76 of file stdio.h.
L_tmpnam
#define L_tmpnam 256
Definition at line 78 of file stdio.h.
TMP_MAX
#define TMP_MAX 1024
Definition at line 80 of file stdio.h.
Typedef Documentation
FILE
typedef struct __mlibc_file_base FILE
Definition at line 1 of file stdio.h.
fpos_t
typedef size_t fpos_t
Definition at line 64 of file stdio.h.
Function Documentation
__attribute__() [1/10]
__attribute__ ((format(gnu_printf, 1, 0))) const
__attribute__() [2/10]
const char* __restrict const char* __restrict __attribute__ ((format(gnu_printf, 1, 2))) const
__attribute__() [3/10]
const char* __restrict const char* __restrict size_t const char* __restrict const char* __restrict const char* __restrict __attribute__ ((format(gnu_printf, 2, 0)))
__attribute__() [4/10]
__attribute__ ((format(gnu_printf, 2, 3)))
__attribute__() [5/10]
__attribute__ ((format(gnu_printf, 3, 0)))
__attribute__() [6/10]
const char* __restrict const char* __restrict __attribute__ ((format(gnu_printf, 3, 4)))
__attribute__() [7/10]
__attribute__ ((format(gnu_scanf, 1, 0))) const
__attribute__() [8/10]
const char* __restrict const char* __restrict __attribute__ ((format(gnu_scanf, 1, 2))) const
__attribute__() [9/10]
__attribute__ ((format(gnu_scanf, 2, 0)))
__attribute__() [10/10]
const char* __restrict __attribute__ ((format(gnu_scanf, 2, 3)))
asprintf()
int asprintf (char ** out, const char * format, ...)
Definition at line 1096 of file stdio-stubs.cpp.
{
     va_list args;
     va_start(args, format);
     int result = vasprintf(out, format, args);
     va_end(args);
     return result;
 }
References args, fmt, format, out(), ret, va_end(), va_start(), and vasprintf().
clearerr()
void clearerr (FILE * stream)
Definition at line 1013 of file stdio-stubs.cpp.
{
     file_base->__status_bits = 0;
 }
clearerr_unlocked()
void clearerr_unlocked (FILE * file_base)
Definition at line 1135 of file stdio-stubs.cpp.
{
     file_base->__status_bits = 0;
 }
fclose()
int fclose (FILE * stream)
Definition at line 48 of file file.c.
 {
     if (fp == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     return syscall1(sys_FileClose, fp->_fileno);
 }
feof()
int feof (FILE * stream)
Definition at line 1017 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_EOF_BIT;
 }
feof_unlocked()
int feof_unlocked (FILE * file_base)
Definition at line 1139 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_EOF_BIT;
 }
References __MLIBC_EOF_BIT.
ferror()
int ferror (FILE * stream)
Definition at line 1021 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_ERROR_BIT;
 }
ferror_unlocked()
int ferror_unlocked (FILE * file_base)
Definition at line 1143 of file stdio-stubs.cpp.
{
     return file_base->__status_bits & __MLIBC_ERROR_BIT;
 }
References __MLIBC_ERROR_BIT.
fflush()
int fflush (FILE * stream)
Definition at line 79 of file file.c.
 {
     if (stream == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     errno = ENOSYS;
     return EOF;
 }
fflush_unlocked()
int fflush_unlocked (FILE * file_base)
Definition at line 636 of file file-io.cpp.
{
     if(file_base == NULL) {
         // Only flush the files but do not close them.
         for(auto it : mlibc::global_file_list()) {
             if(int e = it->flush(); e)
                 mlibc::infoLogger() << "mlibc warning: Failed to flush file"
                     << frg::endlog;
         }
         return 0;
     }
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(file->flush())
         return EOF;
     return 0;
 }
References EOF, mlibc::anonymous_namespace{file-io.cpp}::global_file_list(), mlibc::infoLogger, and NULL.
fgetc()
int fgetc (FILE * stream)
Definition at line 835 of file stdio-stubs.cpp.
{
     char c;
     auto bytes_read = fread(&c, 1, 1, stream);
     if(bytes_read != 1)
         return EOF;
     return c;
 }
fgetc_unlocked()
int fgetc_unlocked (FILE * stream)
Definition at line 1147 of file stdio-stubs.cpp.
{
     unsigned char d;
     if(fread_unlocked(&d, 1, 1, stream) != 1)
         return EOF;
     return (int)d;
 }
References EOF, and fread_unlocked().
Referenced by fgets(), getc_unlocked(), getchar_unlocked(), and getdelim().
fgetpos()
int fgetpos (FILE *__restrict stream, fpos_t *__restrict position)
fgets()
char* fgets (char *__restrict buffer, size_t max_size, FILE *__restrict stream)
Definition at line 843 of file stdio-stubs.cpp.
{
     __ensure(max_size > 0);
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     for(size_t i = 0; ; i++) {
         if (i == max_size - 1) {
             buffer[i] = 0;
             return buffer;
         }
         auto c = fgetc_unlocked(stream);
         // If fgetc() fails, there is either an EOF or an I/O error.
         if(c == EOF) {
 //          if(ferror(stream)) {
 //              // Technically, we do not have to terminate the buffer in this case;
 //              // do it anyway to avoid UB if apps do not check our result.
 //              buffer[i] = 0;
 //              return nullptr;
 //          }
             // EOF is only an error if no chars have been read yet.
             //__ensure(feof(stream));
             if(i) {
                 buffer[i] = 0;
                 return buffer;
             }else{
                 // In this case, the buffer is not changed.
                 return nullptr;
             }
         }else{
             buffer[i] = c;
         }
         if(c == '\n') {
             buffer[i + 1] = 0;
             return buffer;
         }
     }
 }
References __ensure, buffer, c, EOF, fgetc_unlocked(), i, lock, and max_size.
Referenced by __get_resolv_conf(), __lookup_serv(), mlibc::get_nameserver(), anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo(), getdate(), getgrent(), getmntent_r(), getpwent(), getpwnam(), getpwnam_r(), getpwuid(), getpwuid_r(), gets(), getspnam_r(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), main(), name_from_hosts(), reverse_hosts(), reverse_services(), and anonymous_namespace{grp-stubs.cpp}::walk_file().
fgets_unlocked()
char* fgets_unlocked (char * , int , FILE *)
Definition at line 1260 of file stdio-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fileno_unlocked()
int fileno_unlocked (FILE * file_base)
Definition at line 580 of file file-io.cpp.
{
     auto file = static_cast<mlibc::fd_file *>(file_base);
     return file->fd();
 }
References mlibc::fd_file::fd().
Referenced by fileno().
flockfile()
void flockfile (FILE * file_base)
Definition at line 1122 of file stdio-stubs.cpp.
{
     static_cast<mlibc::abstract_file *>(file_base)->_lock.lock();
 }
References __lockfile(), __pthread_self, __register_locked_file(), f, and ftrylockfile().
Referenced by main(), putgrent(), and worker().
fopen()
FILE* fopen (const char *__restrict filename, const char *__restrict mode)
fputc()
int fputc (int c, FILE * stream)
Definition at line 7 of file put.c.
 {
     // FIXME
     // if (stream == NULL)
     // {
     //     errno = EBADF;
     //     return EOF;
     // }
     char str[2] = {c, '\0'};
     return syscall3(sys_KernelCTL, KCTL_PRINT, str, 0);
 }
fputc_unlocked()
int fputc_unlocked (int c, FILE * stream)
Definition at line 884 of file stdio-stubs.cpp.
{
     char d = c;
     if(fwrite_unlocked(&d, 1, 1, stream) != 1)
         return EOF;
     return 1;
 }
References c, EOF, and fwrite_unlocked().
Referenced by fputc().
fputs()
int fputs (const char *__restrict string, FILE *__restrict stream)
Definition at line 903 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     return fputs_unlocked(string, stream);
 }
References fputs_unlocked(), and lock.
fputs_unlocked()
int fputs_unlocked (const char * , FILE *)
fread()
size_t fread (void *__restrict buffer, size_t size, size_t count, FILE *__restrict stream)
fread_unlocked()
size_t fread_unlocked (void * __restrict, size_t size, size_t count, FILE * __restrict)
Definition at line 1154 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(!size || !count)
         return 0;
     // Distinguish two cases here: If the object size is one, we perform byte-wise reads.
     // Otherwise, we try to read each object individually.
     if(size == 1) {
         size_t progress = 0;
         while(progress < count) {
             size_t chunk;
             if(file->read((char *)buffer + progress,
                     count - progress, &chunk)) {
                 // TODO: Handle I/O errors.
                 mlibc::infoLogger() << "mlibc: fread() I/O errors are not handled"
                         << frg::endlog;
                 break;
             }else if(!chunk) {
                 // TODO: Handle eof.
                 break;
             }
             progress += chunk;
         }
         return progress;
     }else{
         for(size_t i = 0; i < count; i++) {
             size_t progress = 0;
             while(progress < size) {
                 size_t chunk;
                 if(file->read((char *)buffer + i * size + progress,
                         size - progress, &chunk)) {
                     // TODO: Handle I/O errors.
                     mlibc::infoLogger() << "mlibc: fread() I/O errors are not handled"
                             << frg::endlog;
                     break;
                 }else if(!chunk) {
                     // TODO: Handle eof.
                     break;
                 }
                 progress += chunk;
             }
             if(progress < size)
                 return i;
         }
         return count;
     }
 }
References count, i, mlibc::infoLogger, and size.
Referenced by fgetc_unlocked(), and fread().
freopen()
FILE* freopen (const char *__restrict filename, const char *__restrict mode, FILE *__restrict stream)
fseek()
int fseek (FILE * stream, long offset, int whence)
Definition at line 59 of file file.c.
 {
     if (stream == NULL || whence < 0 || whence > 2)
     {
         errno = EINVAL;
         return -1;
     }
     off_t new_offset = syscall3(sys_FileSeek, stream->_fileno, offset, whence);
     if (new_offset < 0)
         return -1;
     stream->_offset = new_offset;
     return new_offset;
 }
fsetpos()
int fsetpos (FILE * stream, const fpos_t * position)
Definition at line 1007 of file stdio-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
ftell()
long ftell (FILE * stream)
Definition at line 74 of file file.c.
 {
     return stream->_offset;
 }
ftrylockfile()
int ftrylockfile (FILE * file_base)
Definition at line 1130 of file stdio-stubs.cpp.
{
     static_cast<mlibc::abstract_file *>(file_base)->_lock.try_lock();
     return 0;
 }
References __pthread_self, __register_locked_file(), a_cas, f, LONG_MAX, and MAYBE_WAITERS.
Referenced by flockfile(), and main().
funlockfile()
void funlockfile (FILE * file_base)
Definition at line 1126 of file stdio-stubs.cpp.
{
     static_cast<mlibc::abstract_file *>(file_base)->_lock.unlock();
 }
References __unlist_locked_file(), __unlockfile(), and f.
Referenced by main(), putgrent(), and worker().
fwrite()
size_t fwrite (const void *__restrict buffer, size_t size, size_t count, FILE *__restrict stream)
fwrite_unlocked()
size_t fwrite_unlocked (const void * __restrict, size_t size, size_t count, FILE * __restrict)
Definition at line 1207 of file stdio-stubs.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     if(!size || !count)
         return 0;
     // Distinguish two cases here: If the object size is one, we perform byte-wise writes.
     // Otherwise, we try to write each object individually.
     if(size == 1) {
         size_t progress = 0;
         while(progress < count) {
             size_t chunk;
             if(file->write((const char *)buffer + progress,
                     count - progress, &chunk)) {
                 // TODO: Handle I/O errors.
                 mlibc::infoLogger() << "mlibc: fwrite() I/O errors are not handled"
                         << frg::endlog;
                 break;
             }else if(!chunk) {
                 // TODO: Handle eof.
                 break;
             }
             progress += chunk;
         }
         return progress;
     }else{
         for(size_t i = 0; i < count; i++) {
             size_t progress = 0;
             while(progress < size) {
                 size_t chunk;
                 if(file->write((const char *)buffer + i * size + progress,
                         size - progress, &chunk)) {
                     // TODO: Handle I/O errors.
                     mlibc::infoLogger() << "mlibc: fwrite() I/O errors are not handled"
                             << frg::endlog;
                     break;
                 }else if(!chunk) {
                     // TODO: Handle eof.
                     break;
                 }
                 progress += chunk;
             }
             if(progress < size)
                 return i;
         }
         return count;
     }
 }
References count, i, mlibc::infoLogger, and size.
Referenced by StreamPrinter::append(), fputc_unlocked(), fputs_unlocked(), fwrite(), and putc_unlocked().
getc()
int getc (FILE * stream)
Definition at line 913 of file stdio-stubs.cpp.
{
     return fgetc(stream);
 }
getc_unlocked()
int getc_unlocked (FILE * stream)
Definition at line 909 of file stdio-stubs.cpp.
{
     return fgetc_unlocked(stream);
 }
References f, and fgetc_unlocked().
getchar()
int getchar (void)
Definition at line 921 of file stdio-stubs.cpp.
                   {
     return fgetc(stdin);
 }
getchar_unlocked()
int getchar_unlocked (void)
Definition at line 917 of file stdio-stubs.cpp.
{
     return fgetc_unlocked(stdin);
 }
References fgetc_unlocked(), getc_unlocked, and stdin.
getdelim()
ssize_t getdelim (char ** line, size_t * n, int delim, FILE * stream)
Definition at line 1039 of file stdio-stubs.cpp.
{
     // Otherwise, we cannot store the buffer / size.
     if(!line || !n) {
         errno = EINVAL;
         return -1;
     }
     char *buffer = *line;
     /* set the starting capacity to 512 if buffer = NULL */
     size_t capacity = (!buffer) ? 512 : *n;
     size_t nwritten = 0;
     auto file = static_cast<mlibc::abstract_file *>(stream);
     frg::unique_lock lock(file->_lock);
     // Avoid allocating if we've already hit the end
     auto c = fgetc_unlocked(stream);
     if (c == EOF || ferror(stream)) {
         return -1;
     } else {
         file->unget(c);
     }
     while (true) {
         // Fill the buffer
         while (buffer && capacity > 0 && nwritten < capacity - 1) {
             auto c = fgetc_unlocked(stream);
             if (ferror(stream)) {
                 return -1;
             } else if (c == EOF) {
                 buffer[nwritten] = 0;
                 return nwritten;
             }
             buffer[nwritten++] = c;
             if (c == delim) {
                 buffer[nwritten] = 0;
                 return nwritten;
             }
         }
         // Double the size of the buffer (but make sure it's at least 1024)
         capacity = (capacity >= 1024) ? capacity * 2 : 1024;
         buffer = reinterpret_cast<char *>(getAllocator().reallocate(*line, capacity));
         if (!buffer) {
             errno = ENOMEM;
             return -1;
         }
         *line = buffer;
         *n = capacity;
     }
 }
References buffer, c, EINVAL, ENOMEM, EOF, errno, ferror(), fgetc_unlocked(), getAllocator(), line, lock, and n.
Referenced by getline(), and getword().
getline()
ssize_t getline (char ** line, size_t * n, FILE * stream)
Definition at line 1035 of file stdio-stubs.cpp.
{
     return getdelim(line, n, '\n', stream);
 }
References getdelim(), line, and n.
Referenced by __getgrent_a(), __getpwent_a(), fgetln(), fgetspent(), getmntent_r(), getusershell(), and main().
gets()
char* gets (char * s)
Definition at line 925 of file stdio-stubs.cpp.
                    {
     return fgets(s, SIZE_MAX, stdin);
 }
perror()
void perror (const char * string)
Definition at line 34 of file put.c.
 { fputs(s, stderr); }
putc()
int putc (int c, FILE * stream)
Definition at line 19 of file put.c.
 { return fputc(c, stream); }
putc_unlocked()
int putc_unlocked (int c, FILE * stream)
Definition at line 929 of file stdio-stubs.cpp.
{
     char d = c;
     if(fwrite_unlocked(&d, 1, 1, stream) != 1)
         return EOF;
     return c;
 }
References c, EOF, f, and fwrite_unlocked().
Referenced by putc(), and putchar_unlocked().
putchar()
int putchar (int c)
Definition at line 33 of file put.c.
 { return fputc(c, stdout); }
putchar_unlocked()
int putchar_unlocked (int c)
Definition at line 942 of file stdio-stubs.cpp.
{
     return putc_unlocked(c, stdout);
 }
References c, putc_unlocked(), and stdout.
Referenced by putchar().
puts()
int puts (const char * string)
Definition at line 27 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stdout);
 }
remove()
int remove (const char * filename)
Definition at line 10 of file sys_stat.c.
 {
     return 0;
 }
rename()
int rename (const char * old_path, const char * new_path)
Definition at line 15 of file sys_stat.c.
 {
     return 0;
 }
renameat()
int renameat (int olddirfd, const char * old_path, int newdirfd, const char * new_path)
Definition at line 235 of file stdio-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_renameat, -1);
     if(int e = mlibc::sys_renameat(olddirfd, old_path, newdirfd, new_path); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_renameat(), and syscall().
rewind()
void rewind (FILE * stream)
Definition at line 696 of file file-io.cpp.
{
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     file->seek(0, SEEK_SET);
     file_base->__status_bits &= ~(__MLIBC_EOF_BIT | __MLIBC_ERROR_BIT);
 }
setbuf()
void setbuf (FILE *__restrict stream, char *__restrict buffer)
Definition at line 261 of file stdio-stubs.cpp.
{
     setvbuf(stream, buffer, buffer ? _IOFBF : _IONBF, BUFSIZ);
 }
References _IOFBF, _IONBF, BUFSIZ, and setvbuf().
setbuffer()
void setbuffer (FILE * f, char * buf, size_t size)
Definition at line 270 of file stdio-stubs.cpp.
{
     setvbuf(f, buf, buf ? _IOFBF : _IONBF, size);
 }
References _IOFBF, _IONBF, buf, f, setvbuf(), and size.
setlinebuf()
void setlinebuf (FILE * stream)
Definition at line 266 of file stdio-stubs.cpp.
{
     setvbuf(stream, NULL, _IOLBF, 0);
 }
References _IOLBF, f, NULL, and setvbuf().
Referenced by sh_setlinebuf().
setvbuf()
int setvbuf (FILE *__restrict stream, char *__restrict buffer, int mode, size_t size)
tmpfile()
FILE* tmpfile (void)
Definition at line 244 of file stdio-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
tmpnam()
char* tmpnam (char * buffer)
Definition at line 249 of file stdio-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
ungetc()
int ungetc (int c, FILE * stream)
Definition at line 703 of file file-io.cpp.
{
     if (c == EOF)
         return EOF;
     auto file = static_cast<mlibc::abstract_file *>(file_base);
     frg::unique_lock lock(file->_lock);
     return file->unget(c);
 }
Variable Documentation
__gnuc_va_list
const char __gnuc_va_list
Definition at line 152 of file stdio.h.
args
const char *__restrict __gnuc_va_list args
Definition at line 129 of file stdio.h.
Referenced by _rl_init_file_error(), asprintf(), bind_args(), builtin_error(), builtin_warning(), cprintf(), dprintf(), Driversprintf(), CrashHandler::EHPrint(), execl(), execute_disk_command(), fatal_error(), fcntl(), fctprintf(), fctprintf_libinit(), fprintf(), fscanf(), handle_parser_directive(), init_log(), internal_debug(), internal_error(), internal_inform(), internal_warning(), ioctl(), KPrint(), list_rest_of_args(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), M_snprintf(), M_StringJoin(), open(), openat(), parser_error(), printf(), printf_(), printf_libinit(), programming_error(), report_error(), scanf(), shell_execve(), snprintf(), snprintf_(), snprintf_libinit(), sprintf(), sprintf_(), sprintf_libinit(), sscanf(), sys_error(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), SysDbg::Write(), SysDbg::WriteLine(), and WriteRaw().
format
const char *__restrict format
Definition at line 108 of file stdio.h.
Referenced by _rl_errmsg(), _rl_init_file_error(), _rl_ttymsg(), _vsnprintf(), asprintf(), builtin_error(), builtin_warning(), dprintf(), fatal_error(), fctprintf(), fctprintf_libinit(), update-syscall-list::fetch_kernel(), format_string_loop(), format_string_loop_libint(), fprintf(), fscanf(), init_data(), internal_debug(), internal_error(), internal_inform(), internal_warning(), line_error(), list_all_jobs(), list_one_job(), list_running_jobs(), list_stopped_jobs(), update-syscall-list::main(), parse_flags(), parse_flags_libint(), parser_error(), pretty_print_job(), print_job(), print_pipeline(), printable_job_status(), printf(), printf_(), printf_libinit(), programming_error(), report_error(), rl_message(), update-syscall-list::run_harness(), scanf(), snprintf(), snprintf_(), snprintf_libinit(), sprintf(), sprintf_(), sprintf_libinit(), sscanf(), strftime(), strftime_builtin(), strptime(), anonymous_namespace{time.cpp}::strptime_internal(), sys_error(), syslog(), V_ScreenShot(), vasprintf(), vdprintf(), vfctprintf(), vfctprintf_libinit(), vfprintf(), vfscanf(), vprintf(), vprintf_(), vprintf_dumper(), vprintf_libinit(), vsnprintf(), vsnprintf_(), vsnprintf_impl(), vsnprintf_impl_libint(), vsnprintf_internal(), vsnprintf_libinit(), vsprintf(), vsprintf_(), vsprintf_libinit(), vsscanf(), WriteRaw(), and xprintf().
max_size
size_t max_size
Definition at line 120 of file stdio.h.
Referenced by fgets(), getrandom(), mbtowc(), readlink(), snprintf(), strftime(), strncat(), strncmp(), strncpy(), strndup(), tre_stack_new(), vsnprintf(), and wcstombs().
stderr
FILE* stderr extern
Definition at line 11 of file file.c.
stdin
FILE* stdin extern
Definition at line 9 of file file.c.
stdout
FILE* stdout extern
Definition at line 10 of file file.c.