Fennix Userspace: Userspace/musl/src/unistd/unlink.c File Reference
unlink.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include "syscall.h"
Functions
int unlink (const char *path)
Function Documentation
unlink()
int unlink (const char * path)
Definition at line 5 of file unlink.c.
 {
 #ifdef SYS_unlink
     return syscall(SYS_unlink, path);
 #else
     return syscall(SYS_unlinkat, AT_FDCWD, path, 0);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by action_compat(), ask_and_unlink(), bbunpack(), buffer_pwrite(), clean_up_and_exit(), cleanup_outname(), conf(), conf_cleanup(), convert(), copy_inode(), create_socket(), crontab_main(), data_extract_all(), delete_contents(), delete_tempfile(), diffreg(), dolink(), fail_hunk(), finalize(), here_document_to_fd(), history_do_write(), history_truncate_file(), ln_main(), log_locally(), lpd_main(), lpqr_main(), make_device(), microcom_main(), mktemp_builtin(), mv_main(), patch_main(), prepare_socket_fd(), process_cron_update_file(), processorstop(), remove_file(), remove_file_array(), remove_pidfile_std_path_and_ext(), rename(), reread_config_file(), rescan_crontab_dir(), rm_file(), rmoldest(), sem_open(), shm_unlink(), show_textbox(), unlink_builtin(), update_passwd(), update_status(), and xunlink().