Fennix Userspace: Userspace/musl/crt/rcrt1.c File Reference
rcrt1.c File Reference
#include "../ldso/dlstart.c"
Macros
#define START "_start"
#define _dlstart_c _start_c
Functions
int main ()
weak void _init ()
weak void _fini ()
int __libc_start_main (int(*)(), int, char **, void(*)(), void(*)(), void(*)())
hidden void __dls2 (unsigned char *base, size_t *sp)
Macro Definition Documentation
_dlstart_c
#define _dlstart_c _start_c
Definition at line 2 of file rcrt1.c.
START
#define START "_start"
Definition at line 1 of file rcrt1.c.
Function Documentation
__dls2()
hidden void __dls2 (unsigned char * base, size_t * sp)
Definition at line 11 of file rcrt1.c.
 {
     __libc_start_main(main, *sp, (void *)(sp+1), _init, _fini, 0);
 }
References __libc_start_main(), _fini(), _init(), main(), and sp.
Referenced by _dlstart_c().
__libc_start_main()
int __libc_start_main (int(*)() , int , char ** , void(*)() , void(*)() , void(*)())
Referenced by __dls2().
_fini()
weak void _fini ()
Referenced by __dls2().
_init()
weak void _init ()
Referenced by __dls2().
main()
int main ()
Definition at line 30 of file open-files.c.
 {
     register int    i;
     for (i = 0; i < getdtablesize(); i++) {
         if (fcntl(i, F_GETFD, 0) != -1)
             fprintf(stderr, "fd %d: open\n", i);
     }
     exit(0);
 }
References _exit(), _SC_GETGR_R_SIZE_MAX, _SC_GETPW_R_SIZE_MAX, abort(), abs(), access(), add_history(), addr, AF_INET, AF_UNSPEC, addrinfo::ai_family, addrinfo::ai_flags, AI_NUMERICHOST, addrinfo::ai_protocol, addrinfo::ai_socktype, alarm(), alarms_fired, aligned_alloc(), asprintf(), assert, assertWidthIs(), b, bar(), barGetDefault(), barGetNext(), barrier, buf, BUF_SIZE, c, termios::c_cc, termios::c_lflag, callback(), calloc, change_prompt(), CHAR_BIT, check_counter(), check_key(), check_result(), check_root_group(), child1(), child2(), child_order, cleanup(), cleanup_val, close(), compare(), count, counter, CTRL, dl_iterate_phdr(), dlclose, dlopen, dlsym, DO_ERR_TEST, DO_ERR_TESTL, do_jump(), DO_TEST, DO_TESTL, done, dprintf(), dtors_entered, EAGAIN, EAI_NONAME, EINTR, EINVAL, endgrent(), env, ERANGE, errno, ESRCH, exit(), EXIT_SUCCESS, F_GETFD, F_OK, fclose(), fcntl(), FD_ISSET, FD_SET, FD_SETSIZE, FD_ZERO, fdopen(), feof, ferror, fflush(), ffs(), ffsl(), ffsll(), fileno(), flockfile(), foo(), fooGetDefault(), fooGetNext(), fopen(), fork(), result::found_bar, result::found_foo, result::found_ldso, result::found_self, fprintf(), fputc(), fputs(), fread(), free, free_key(), freeaddrinfo(), fseek(), ftrylockfile(), funlockfile(), fwrite(), get_prompt(), getaddrinfo(), getcwd(), getdelim(), getdtablesize(), getenv, getgrent(), getgrgid(), getgrgid_r(), getgrnam(), getgrnam_r(), getline(), getnameinfo(), getpid(), getpriority(), getpwent(), getpwnam(), getpwnam_r(), getpwuid(), getpwuid_r(), getrlimit(), getservbyname(), getservbyport(), group::gr_gid, group::gr_name, group::gr_passwd, handler(), handler_ready, history_list(), hitBarrierCount, htonl(), htons(), i, ICANON, INADDR_LOOPBACK, index(), INET_ADDRSTRLEN, inet_ntop(), inet_pton(), INFINITY, INT_MAX, INT_MIN, IPPROTO_TCP, isFooDone(), j, kill(), L, labs(), LC_ALL, LC_CTYPE, LC_TIME, LIBBAR, LIBFOO, line, listen_fd, llabs(), LLONG_MAX, LLONG_MIN, LONG_MAX, LONG_MIN, lseek(), main_ready, mainDone, malloc, mbstowcs(), memchr(), memcmp(), memmem(), memrchr(), memset(), NAN, noop(), ns_get16(), ns_get32(), ns_put16(), ns_put32(), NULL, O_CREAT, O_RDONLY, O_RDWR, old_lflag, old_vtime, open(), open_memstream(), p, parent1(), parent2(), parent_order, pastBarrierCount, PATH_MAX, pattern, pause(), pclose(), permutations, perror(), popen(), posix_memalign(), prepare(), prepare1(), prepare2(), prepare_order, prevent_atforks(), printf(), PRIO_PROCESS, process_line(), prompt, pthread_atfork(), pthread_barrier_destroy(), pthread_barrier_init(), pthread_barrier_wait(), pthread_barrierattr_destroy(), pthread_barrierattr_getpshared(), pthread_barrierattr_init(), pthread_barrierattr_setpshared(), pthread_cancel(), pthread_create(), pthread_getspecific(), pthread_join(), pthread_key_create(), pthread_key_delete(), PTHREAD_KEYS_MAX, pthread_kill(), PTHREAD_PROCESS_PRIVATE, PTHREAD_PROCESS_SHARED, pthread_setspecific(), pw, passwd::pw_dir, passwd::pw_gecos, passwd::pw_gid, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, R_OK, read(), readline(), reallocarray(), realpath(), regcomp(), regexec(), regfree(), ret, rindex(), rl_add_defun(), rl_callback_handler_install(), rl_callback_read_char(), rlimit::rlim_cur, rlimit::rlim_max, RLIMIT_NOFILE, RTLD_GLOBAL, RTLD_LOCAL, RTLD_NOW, run_cmd(), run_test(), sigaction::sa_flags, sigaction::sa_mask, SA_ONSTACK, sigaction::sa_sigaction, SA_SIGINFO, SEEK_CUR, SEEK_END, SEEK_SET, select(), setgrent(), setjmp, setlocale, setpriority(), setpwent(), setrlimit(), sig_handler(), SIGABRT, sigaction(), SIGALRM, sigalrm_handler(), sigaltstack(), sigemptyset, SIGKILL, signal, signal_handler(), SIGSEGV, sigStack, SIGSTKSZ, SIGUSR1, size, sleep(), snprintf(), SOCK_STREAM, socket_setup(), sprintf(), __stack::ss_flags, __stack::ss_size, __stack::ss_sp, sscanf(), mlibc::status, stderr, stdin, STDIN_FILENO, stdout, stpcpy(), stpncpy(), str, strchr(), strcmp, strdup(), strerror(), strftime(), strlcat(), strlcpy(), strlen(), strncmp(), strptime(), strrchr(), strstr(), strtol(), strtoll(), strtoul(), strtoull(), strverscmp(), syscall(), sysconf(), system(), tcgetattr(), TCSANOW, tcsetattr(), term, test(), test1(), test2(), test3(), test4(), test5(), test6(), test7(), test_affinity(), test_attr(), TEST_BASE, test_broadcast_wakes_all(), test_cases, test_detachstate(), test_failures, TEST_FILE, test_getattrnp(), test_guardsize(), test_inheritsched(), TEST_PORT, test_read_allows_read(), test_read_lock_unlock(), test_read_prevents_write(), test_read_trylock_unlock(), test_schedparam(), test_schedpolicy(), test_scope(), test_sigmask(), test_stack(), test_stackaddr(), test_stacksize(), test_string, TEST_STRING1, TEST_STRING1_LEN, TEST_STRING2, TEST_STRING2_LEN, test_timedwait_timedout(), test_write_lock_unlock(), test_write_prevents_read(), test_write_prevents_write(), test_write_trylock_unlock(), testAttr(), testNormal(), testRecursive(), tests_run, tfind(), thread_signal_ran, timegm(), timeradd(), timerclear, timerisset, timersub(), tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, tm::tm_year, token, tsearch(), timeval::tv_sec, timeval::tv_usec, ULONG_MAX, uninitialized, unlink(), usleep(), verify_decode, vfork(), VTIME, W_OK, wait(), waitpid(), wchar_t, wcsdup(), wcslen(), wcsncasecmp(), wcsrtombs(), wcstol(), wcstoll(), wcstoul(), wcstoull(), wordexp_t::we_wordc, wordexp_t::we_wordv, WEXITSTATUS, WIFEXITED, WIFSIGNALED, wmemcmp(), WNOHANG, wordexp(), wordexp_return_stringify(), wordfree(), worker(), worker1(), worker2(), worker3(), worker4(), worker5(), worker_ready, WRDE_REUSE, write(), WRITE_NO, WTERMSIG, x, X_OK, and y.
Referenced by __dls2().