Fennix Kernel: Kernel/library/md5.c File Reference
md5.c File Reference
#include <md5.h>
#include <memory.hpp>
#include <convert.h>
Macros
#define A 0x67452301
#define B 0xefcdab89
#define C 0x98badcfe
#define D 0x10325476
#define F(X, Y, Z) ((X & Y) | (~X & Z))
#define G(X, Y, Z) ((X & Z) | (Y & ~Z))
#define H(X, Y, Z) (X ^ Y ^ Z)
#define I(X, Y, Z) (Y ^ (X | ~Z))
Functions
void md5Init (MD5Context *ctx)
void md5Update (MD5Context *ctx, uint8_t *input_buffer, size_t input_len)
void md5Finalize (MD5Context *ctx)
void md5Step (uint32_t *buffer, uint32_t *input)
uint8_t * md5String (char *input)
uint8_t * md5File (uint8_t *buffer, size_t input_len)
uint32_t rotateLeft (uint32_t x, uint32_t n)
Variables
static uint32_t S []
static uint32_t K []
static uint8_t PADDING []
Macro Definition Documentation
A
#define A 0x67452301
Definition at line 14 of file md5.c.
B
#define B 0xefcdab89
Definition at line 15 of file md5.c.
C
#define C 0x98badcfe
Definition at line 16 of file md5.c.
D
#define D 0x10325476
Definition at line 17 of file md5.c.
F
#define F (X, Y, Z) ((X & Y) | (~X & Z))
Definition at line 44 of file md5.c.
G
#define G (X, Y, Z) ((X & Z) | (Y & ~Z))
Definition at line 45 of file md5.c.
H
#define H (X, Y, Z) (X ^ Y ^ Z)
Definition at line 46 of file md5.c.
I
#define I (X, Y, Z) (Y ^ (X | ~Z))
Definition at line 47 of file md5.c.
Function Documentation
md5File()
uint8_t* md5File (uint8_t * buffer, size_t input_len)
Definition at line 221 of file md5.c.
 {
     char *input_buffer = (char *)buffer;
     size_t input_size = input_len;
     MD5Context ctx;
     md5Init(&ctx);
     while (input_size > 0)
     {
         size_t chunk_size = input_size > 1024 ? 1024 : input_size;
         md5Update(&ctx, (uint8_t *)input_buffer, chunk_size);
         input_buffer += chunk_size;
         input_size -= chunk_size;
     }
     // while ((input_size = fread(input_buffer, 1, 1024, file)) > 0)
     // {
     //     md5Update(&ctx, (uint8_t *)input_buffer, input_size);
     // }
     md5Finalize(&ctx);
     uint8_t *result = kmalloc(16);
     if (result == NULL)
         return (uint8_t *)"error";
     memcpy(result, ctx.digest, 16);
     return result;
 }
References ctx, kmalloc, md5Finalize(), md5Init(), md5Update(), memcpy(), and NULL.
Referenced by DumpData().
md5Finalize()
void md5Finalize (MD5Context * ctx)
Definition at line 117 of file md5.c.
 {
     uint32_t input[16];
     unsigned int offset = ctx->size % 64;
     unsigned int padding_length = offset < 56 ? 56 - offset : (56 + 64) - offset;
     // Fill in the padding and do the changes to size that resulted from the update
     md5Update(ctx, PADDING, padding_length);
     ctx->size -= (uint64_t)padding_length;
     // Do a final update (internal to this function)
     // Last two 32-bit words are the two halves of the size (converted from bytes to bits)
     for (unsigned int j = 0; j < 14; ++j)
     {
         input[j] = (uint32_t)(ctx->input[(j * 4) + 3]) << 24 |
                    (uint32_t)(ctx->input[(j * 4) + 2]) << 16 |
                    (uint32_t)(ctx->input[(j * 4) + 1]) << 8 |
                    (uint32_t)(ctx->input[(j * 4)]);
     }
     input[14] = (uint32_t)(ctx->size * 8);
 #ifdef a32
     input[15] = (uint32_t)((uint64_t)(((uint64_t)ctx->size >> 32) | ((uint64_t)ctx->size << 32)) >> 32);
 #else
     input[15] = (uint32_t)((ctx->size * 8) >> 32);
 #endif
     md5Step(ctx->buffer, input);
     // Move the result into digest (convert from little-endian)
     for (unsigned int i = 0; i < 4; ++i)
     {
         ctx->digest[(i * 4) + 0] = (uint8_t)((ctx->buffer[i] & 0x000000FF));
         ctx->digest[(i * 4) + 1] = (uint8_t)((ctx->buffer[i] & 0x0000FF00) >> 8);
         ctx->digest[(i * 4) + 2] = (uint8_t)((ctx->buffer[i] & 0x00FF0000) >> 16);
         ctx->digest[(i * 4) + 3] = (uint8_t)((ctx->buffer[i] & 0xFF000000) >> 24);
     }
 }
References ctx, md5Step(), md5Update(), and PADDING.
Referenced by md5File(), and md5String().
md5Init()
void md5Init (MD5Context * ctx)
Definition at line 64 of file md5.c.
 {
     ctx->size = (uint64_t)0;
     ctx->buffer[0] = (uint32_t)A;
     ctx->buffer[1] = (uint32_t)B;
     ctx->buffer[2] = (uint32_t)C;
     ctx->buffer[3] = (uint32_t)D;
 }
References A, B, C, ctx, and D.
Referenced by md5File(), and md5String().
md5Step()
void md5Step (uint32_t * buffer, uint32_t * input)
Definition at line 158 of file md5.c.
 {
     uint32_t AA = buffer[0];
     uint32_t BB = buffer[1];
     uint32_t CC = buffer[2];
     uint32_t DD = buffer[3];
     uint32_t E;
     unsigned int j;
     for (unsigned int i = 0; i < 64; ++i)
     {
         switch (i / 16)
         {
         case 0:
             E = F(BB, CC, DD);
             j = i;
             break;
         case 1:
             E = G(BB, CC, DD);
             j = ((i * 5) + 1) % 16;
             break;
         case 2:
             E = H(BB, CC, DD);
             j = ((i * 3) + 5) % 16;
             break;
         default:
             E = I(BB, CC, DD);
             j = (i * 7) % 16;
             break;
         }
         uint32_t temp = DD;
         DD = CC;
         CC = BB;
         BB = BB + rotateLeft(AA + E + K[i] + input[j], S[i]);
         AA = temp;
     }
     buffer[0] += AA;
     buffer[1] += BB;
     buffer[2] += CC;
     buffer[3] += DD;
 }
References Gigabit::DD, F, G, H, I, K, rotateLeft(), and S.
Referenced by md5Finalize(), and md5Update().
md5String()
uint8_t* md5String (char * input)
Definition at line 207 of file md5.c.
 {
     MD5Context ctx;
     md5Init(&ctx);
     md5Update(&ctx, (uint8_t *)input, strlen(input));
     md5Finalize(&ctx);
     uint8_t *result = kmalloc(16);
     if (result == NULL)
         return (uint8_t *)"error";
     memcpy(result, ctx.digest, 16);
     return result;
 }
References ctx, kmalloc, md5Finalize(), md5Init(), md5Update(), memcpy(), NULL, and strlen().
md5Update()
void md5Update (MD5Context * ctx, uint8_t * input_buffer, size_t input_len)
Definition at line 80 of file md5.c.
 {
     uint32_t input[16];
     unsigned int offset = ctx->size % 64;
     ctx->size += (uint64_t)input_len;
     // Copy each byte in input_buffer into the next space in our context input
     for (unsigned int i = 0; i < input_len; ++i)
     {
         ctx->input[offset++] = (uint8_t) * (input_buffer + i);
         // If we've filled our context input, copy it into our local array input
         // then reset the offset to 0 and fill in a new buffer.
         // Every time we fill out a chunk, we run it through the algorithm
         // to enable some back and forth between cpu and i/o
         if (offset % 64 == 0)
         {
             for (unsigned int j = 0; j < 16; ++j)
             {
                 // Convert to little-endian
                 // The local variable `input` our 512-bit chunk separated into 32-bit words
                 // we can use in calculations
                 input[j] = (uint32_t)(ctx->input[(j * 4) + 3]) << 24 |
                            (uint32_t)(ctx->input[(j * 4) + 2]) << 16 |
                            (uint32_t)(ctx->input[(j * 4) + 1]) << 8 |
                            (uint32_t)(ctx->input[(j * 4)]);
             }
             md5Step(ctx->buffer, input);
             offset = 0;
         }
     }
 }
References ctx, and md5Step().
Referenced by md5File(), md5Finalize(), and md5String().
rotateLeft()
uint32_t rotateLeft (uint32_t x, uint32_t n)
Definition at line 254 of file md5.c.
 {
     return (x << n) | (x >> (32 - n));
 }
Referenced by md5Step().
Variable Documentation
K
uint32_t K[] static
Initial value:
= {0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
                       0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
                       0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
                       0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
                       0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
                       0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
                       0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
                       0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
                       0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
                       0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
                       0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
                       0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
                       0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
                       0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
                       0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
                       0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391}
Definition at line 24 of file md5.c.
Referenced by HashMap< K, V >::AddNode(), HashMap< K, V >::Get(), and md5Step().
PADDING
uint8_t PADDING[] static
Initial value:
= {0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
Definition at line 52 of file md5.c.
Referenced by md5Finalize().
S
uint32_t S[] static
Initial value:
= {7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22,
                       5, 9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20,
                       4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23,
                       6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21}
Definition at line 19 of file md5.c.
Referenced by md5Step().