Fennix Userspace: Userspace/musl/include/sched.h File Reference
sched.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct sched_param
struct sched_param.__reserved2
Macros
#define __NEED_struct_timespec
#define __NEED_pid_t
#define __NEED_time_t
#define SCHED_OTHER 0
#define SCHED_FIFO 1
#define SCHED_RR 2
#define SCHED_BATCH 3
#define SCHED_IDLE 5
#define SCHED_DEADLINE 6
#define SCHED_RESET_ON_FORK 0x40000000
Functions
int sched_get_priority_max (int)
int sched_get_priority_min (int)
int sched_getparam (pid_t, struct sched_param *)
int sched_getscheduler (pid_t)
int sched_rr_get_interval (pid_t, struct timespec *)
int sched_setparam (pid_t, const struct sched_param *)
int sched_setscheduler (pid_t, int, const struct sched_param *)
int sched_yield (void)
Data Structure Documentation
sched_param
struct sched_param
Definition at line 4 of file struct_sched_param.h.
Data Fields
int __reserved1
struct sched_param __reserved2[2]
int __reserved3
int sched_priority
sched_param.__reserved2
struct sched_param.__reserved2
Definition at line 25 of file sched.h.
Data Fields
time_t __reserved1
long __reserved2
Macro Definition Documentation
__NEED_pid_t
#define __NEED_pid_t
Definition at line 10 of file sched.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 9 of file sched.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 11 of file sched.h.
SCHED_BATCH
#define SCHED_BATCH 3
Definition at line 45 of file sched.h.
SCHED_DEADLINE
#define SCHED_DEADLINE 6
Definition at line 47 of file sched.h.
SCHED_FIFO
#define SCHED_FIFO 1
Definition at line 43 of file sched.h.
SCHED_IDLE
#define SCHED_IDLE 5
Definition at line 46 of file sched.h.
SCHED_OTHER
#define SCHED_OTHER 0
Definition at line 42 of file sched.h.
SCHED_RESET_ON_FORK
#define SCHED_RESET_ON_FORK 0x40000000
Definition at line 48 of file sched.h.
SCHED_RR
#define SCHED_RR 2
Definition at line 44 of file sched.h.
Function Documentation
sched_get_priority_max()
int sched_get_priority_max (int policy)
Definition at line 4 of file sched_get_priority_max.c.
 {
     return syscall(SYS_sched_get_priority_max, policy);
 }
References syscall().
Referenced by chrt_main(), and show_min_max().
sched_get_priority_min()
int sched_get_priority_min (int policy)
Definition at line 9 of file sched_get_priority_max.c.
 {
     return syscall(SYS_sched_get_priority_min, policy);
 }
References syscall().
Referenced by chrt_main(), and show_min_max().
sched_getparam()
int sched_getparam (pid_t pid, struct sched_param * param)
Definition at line 5 of file sched_getparam.c.
 {
     return __syscall_ret(-ENOSYS);
 }
References __syscall_ret(), and ENOSYS.
Referenced by chrt_main().
sched_getscheduler()
int sched_getscheduler (pid_t pid)
Definition at line 5 of file sched_getscheduler.c.
 {
     return __syscall_ret(-ENOSYS);
 }
References __syscall_ret(), and ENOSYS.
Referenced by chrt_main().
sched_rr_get_interval()
int sched_rr_get_interval (pid_t pid, struct timespec * ts)
Definition at line 4 of file sched_rr_get_interval.c.
 {
 #ifdef SYS_sched_rr_get_interval_time64
     /* On a 32-bit arch, use the old syscall if it exists. */
     if (SYS_sched_rr_get_interval != SYS_sched_rr_get_interval_time64) {
         long ts32[2];
         int r = __syscall(SYS_sched_rr_get_interval, pid, ts32);
         if (!r) {
             ts->tv_sec = ts32[0];
             ts->tv_nsec = ts32[1];
         }
         return __syscall_ret(r);
     }
 #endif
     /* If reaching this point, it's a 64-bit arch or time64-only
      * 32-bit arch and we can get result directly into timespec. */
     return syscall(SYS_sched_rr_get_interval, pid, ts);
 }
References __syscall, __syscall_ret(), pid, SYS_sched_rr_get_interval, SYS_sched_rr_get_interval_time64, syscall(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by __sched_rr_get_interval_time32().
sched_setparam()
int sched_setparam (pid_t pid, const struct sched_param * param)
Definition at line 5 of file sched_setparam.c.
 {
     return __syscall_ret(-ENOSYS);
 }
References __syscall_ret(), and ENOSYS.
sched_setscheduler()
int sched_setscheduler (pid_t pid, int sched, const struct sched_param * param)
Definition at line 5 of file sched_setscheduler.c.
 {
     return __syscall_ret(-ENOSYS);
 }
References __syscall_ret(), and ENOSYS.
Referenced by chrt_main().
sched_yield()
int sched_yield (void)
Definition at line 4 of file sched_yield.c.
 {
     return syscall(SYS_sched_yield);
 }
References syscall().
Referenced by read_lines().