Fennix: GraphicalUserInterface Namespace Reference
GraphicalUserInterface Namespace Reference
Data Structures
struct MouseData
struct ScreenBitmap
struct Rect
struct Event
class WidgetCollection
class Window
class GUI
struct Event.Resize
struct Event.MouseDown
struct Event.MouseUp
struct Event.MouseMove
Typedefs
typedef uintptr_t Handle
Enumerations
enum CursorType {
Visible = 0 , Hidden , Arrow , Hand ,
Wait , IBeam , ResizeHorizontal , ResizeVertical ,
ResizeDiagonalLeft , ResizeDiagonalRight , ResizeAll , Cross ,
Help , No , AppStarting
}
Functions
Ofast void InlineSetPixel (ScreenBitmap *Bitmap, int64_t X, int64_t Y, uint32_t Color)
void SetPixel (ScreenBitmap *Bitmap, size_t X, size_t Y, uint32_t Color)
uint32_t GetPixel (ScreenBitmap *Bitmap, int64_t X, int64_t Y)
Ofast void DrawOverBitmap (ScreenBitmap *DestinationBitmap, ScreenBitmap *SourceBitmap, int64_t Top, int64_t Left, bool IgnoreZero)
Ofast void PutRect (ScreenBitmap *Bitmap, Rect rect, uint32_t Color)
void PutBorder (ScreenBitmap *Bitmap, Rect rect, uint32_t Color)
uint32_t BlendColors (uint32_t c1, uint32_t c2, float t)
void PutBorderWithShadow (ScreenBitmap *Bitmap, Rect rect, uint32_t Color)
void DrawShadow (ScreenBitmap *Bitmap, Rect rect)
void PaintChar (Video::Font *font, ScreenBitmap *Bitmap, char c, uint32_t Color, int64_t *CharCursorX, int64_t *CharCursorY)
void DrawString (ScreenBitmap *Bitmap, Rect rect, const char *Text, uint32_t Color)
Data Structure Documentation
GraphicalUserInterface::MouseData
struct GraphicalUserInterface::MouseData
Definition at line 31 of file gui.hpp.
Data Fields
bool Left
bool Middle
bool Right
size_t X
size_t Y
size_t Z
GraphicalUserInterface::ScreenBitmap
struct GraphicalUserInterface::ScreenBitmap
Definition at line 41 of file gui.hpp.
Data Fields
uint64_t BitsPerPixel
uint8_t * Data
size_t Height
size_t Pitch
size_t Size
size_t Width
GraphicalUserInterface::Event
struct GraphicalUserInterface::Event
Definition at line 94 of file gui.hpp.
Data Fields
struct Event MouseDown
struct Event MouseMove
struct Event MouseUp
struct Event Resize
GraphicalUserInterface::Event.Resize
struct GraphicalUserInterface::Event.Resize
Definition at line 96 of file gui.hpp.
Data Fields
size_t Height
size_t Width
GraphicalUserInterface::Event.MouseDown
struct GraphicalUserInterface::Event.MouseDown
Definition at line 102 of file gui.hpp.
Data Fields
bool Left
bool Middle
bool Right
size_t X
size_t Y
GraphicalUserInterface::Event.MouseUp
struct GraphicalUserInterface::Event.MouseUp
Definition at line 111 of file gui.hpp.
Data Fields
bool Left
bool Middle
bool Right
size_t X
size_t Y
GraphicalUserInterface::Event.MouseMove
struct GraphicalUserInterface::Event.MouseMove
Definition at line 120 of file gui.hpp.
Data Fields
bool Left
bool Middle
bool Right
size_t X
size_t Y
Typedef Documentation
Handle
typedef uintptr_t GraphicalUserInterface::Handle
Definition at line 29 of file gui.hpp.
Enumeration Type Documentation
CursorType
enum GraphicalUserInterface::CursorType
Enumerator
Visible
Hidden
Arrow
Hand
Wait
IBeam
ResizeHorizontal
ResizeVertical
ResizeDiagonalLeft
ResizeDiagonalRight
ResizeAll
Cross
No
AppStarting
Definition at line 75 of file gui.hpp.
     {
         Visible = 0,
         Hidden,
         Arrow,
         Hand,
         Wait,
         IBeam,
         ResizeHorizontal,
         ResizeVertical,
         ResizeDiagonalLeft,
         ResizeDiagonalRight,
         ResizeAll,
         Cross,
         Help,
         No,
         AppStarting,
     };
Function Documentation
BlendColors()
uint32_t GraphicalUserInterface::BlendColors (uint32_t c1, uint32_t c2, float t)
Definition at line 130 of file GUITools.cpp.
     {
         uint8_t r1 = (c1 >> 16) & 0xFF;
         uint8_t g1 = (c1 >> 8) & 0xFF;
         uint8_t b1 = c1 & 0xFF;
         uint8_t r2 = (c2 >> 16) & 0xFF;
         uint8_t g2 = (c2 >> 8) & 0xFF;
         uint8_t b2 = c2 & 0xFF;
         uint8_t r = (uint8_t)(r1 + t * (r2 - r1));
         uint8_t g = (uint8_t)(g1 + t * (g2 - g1));
         uint8_t b = (uint8_t)(b1 + t * (b2 - b1));
         return (r << 16) | (g << 8) | b;
     }
References b, g, r, r1, and r2.
DrawOverBitmap()
void GraphicalUserInterface::DrawOverBitmap (ScreenBitmap * DestinationBitmap, ScreenBitmap * SourceBitmap, int64_t Top, int64_t Left, bool IgnoreZero)
Definition at line 60 of file GUITools.cpp.
     {
         if (unlikely(!SourceBitmap) || unlikely(!SourceBitmap->Data) ||
             unlikely(!DestinationBitmap) || unlikely(!DestinationBitmap->Data))
             return;
         // for (uint32_t i = 0; i < SourceBitmap->Width; i++)
         //     for (uint32_t j = 0; j < SourceBitmap->Height; j++)
         //     {
         //         uint32_t *Pixel = (uint32_t *)((uintptr_t)SourceBitmap->Data + (j * SourceBitmap->Width + i) * (SourceBitmap->BitsPerPixel / 8));
         //         if (IgnoreZero && (*Pixel != 0x000000))
         //             InlineSetPixel(DestinationBitmap, Left + i, Top + j, *Pixel);
         //     }
         for (uint32_t j = 0; j < SourceBitmap->Height; j++)
         {
             uint32_t *Pixel = (uint32_t *)((uintptr_t)SourceBitmap->Data + j * SourceBitmap->Width * (SourceBitmap->BitsPerPixel / 8));
             if (IgnoreZero)
             {
                 for (uint32_t i = 0; i < SourceBitmap->Width; i++)
                 {
                     if (Pixel[i] != 0x000000)
                         InlineSetPixel(DestinationBitmap, Left + i, Top + j, Pixel[i]);
                 }
             }
             else
             {
                 memcpy((void *)((uintptr_t)DestinationBitmap->Data + (Top + j) * DestinationBitmap->Width * (DestinationBitmap->BitsPerPixel / 8) + Left * (DestinationBitmap->BitsPerPixel / 8)),
                        (void *)((uintptr_t)SourceBitmap->Data + j * SourceBitmap->Width * (SourceBitmap->BitsPerPixel / 8)),
                        (size_t)(SourceBitmap->Width * (SourceBitmap->BitsPerPixel / 8)));
             }
         }
     }
References GraphicalUserInterface::ScreenBitmap::BitsPerPixel, GraphicalUserInterface::ScreenBitmap::Data, GraphicalUserInterface::ScreenBitmap::Height, i, InlineSetPixel(), j, memcpy, unlikely, and GraphicalUserInterface::ScreenBitmap::Width.
Referenced by GraphicalUserInterface::WidgetCollection::OnPaint(), GraphicalUserInterface::GUI::PaintCursor(), and GraphicalUserInterface::GUI::PaintWindows().
DrawShadow()
void GraphicalUserInterface::DrawShadow (ScreenBitmap * Bitmap, Rect rect)
Definition at line 155 of file GUITools.cpp.
     {
         UNUSED(Bitmap);
         UNUSED(rect);
     }
References UNUSED.
Referenced by GraphicalUserInterface::GUI::PaintWindows().
DrawString()
void GraphicalUserInterface::DrawString (ScreenBitmap * Bitmap, Rect rect, const char * Text, uint32_t Color)
Definition at line 211 of file GUITools.cpp.
     {
         UNUSED(Bitmap);
         UNUSED(rect);
         UNUSED(Text);
         UNUSED(Color);
     }
References UNUSED.
GetPixel()
uint32_t GraphicalUserInterface::GetPixel (ScreenBitmap * Bitmap, int64_t X, int64_t Y)
Definition at line 45 of file GUITools.cpp.
     {
         if (unlikely(!Bitmap))
             return 0;
         if (unlikely(!Bitmap->Data))
             return 0;
         if (unlikely(X < 0 || Y < 0 || X >= (int64_t)Bitmap->Width || Y >= (int64_t)Bitmap->Height))
             return 0;
         uint32_t *Pixel = (uint32_t *)((uintptr_t)Bitmap->Data + (Y * Bitmap->Width + X) * (Bitmap->BitsPerPixel / 8));
         return *Pixel;
     }
References unlikely, and X.
InlineSetPixel()
Ofast void GraphicalUserInterface::InlineSetPixel (ScreenBitmap * Bitmap, int64_t X, int64_t Y, uint32_t Color) inline
Definition at line 24 of file GUITools.cpp.
     {
         if (unlikely(X < 0 || Y < 0 || X >= (int64_t)Bitmap->Width || Y >= (int64_t)Bitmap->Height))
             return;
         uint32_t *Pixel = (uint32_t *)((uintptr_t)Bitmap->Data + (Y * Bitmap->Width + X) * (Bitmap->BitsPerPixel / 8));
         *Pixel = Color;
         // Bitmap->Data[Y * Bitmap->Width + X] = Color;
     }
References unlikely, and X.
Referenced by DrawOverBitmap(), PaintChar(), PutBorder(), PutRect(), and SetPixel().
PaintChar()
void GraphicalUserInterface::PaintChar (Video::Font * font, ScreenBitmap * Bitmap, char c, uint32_t Color, int64_t * CharCursorX, int64_t * CharCursorY)
Definition at line 163 of file GUITools.cpp.
     {
         switch (font->GetInfo().Type)
         {
         case Video::FontType::PCScreenFont1:
         {
             // uint32_t *PixelPtr = (uint32_t *)Bitmap->Data;
             char *FontPtr = (char *)font->GetInfo().PSF1Font->GlyphBuffer + (c * font->GetInfo().PSF1Font->Header->charsize);
             for (int64_t Y = *CharCursorY; Y < *CharCursorY + 16; Y++)
             {
                 for (int64_t X = *CharCursorX; X < *CharCursorX + 8; X++)
                     if ((*FontPtr & (0b10000000 >> (X - *CharCursorX))) > 0)
                         InlineSetPixel(Bitmap, X, Y, Color);
                 FontPtr++;
             }
             *CharCursorX += 8;
             break;
         }
         case Video::FontType::PCScreenFont2:
         {
             // if (font->PSF2Font->GlyphBuffer == (uint16_t *)0x01) // HAS UNICODE TABLE
             //     Char = font->PSF2Font->GlyphBuffer[Char];
             int BytesPerLine = (font->GetInfo().PSF2Font->Header->width + 7) / 8;
             char *FontPtr = (char *)font->GetInfo().StartAddress +
                             font->GetInfo().PSF2Font->Header->headersize +
                             (c > 0 && (unsigned char)c < font->GetInfo().PSF2Font->Header->length ? c : 0) *
                                 font->GetInfo().PSF2Font->Header->charsize;
             uint32_t fonthdrWidth = font->GetInfo().PSF2Font->Header->width;
             uint32_t fonthdrHeight = font->GetInfo().PSF2Font->Header->height;
             for (int64_t Y = *CharCursorY; Y < *CharCursorY + fonthdrHeight; Y++)
             {
                 for (int64_t X = *CharCursorX; X < *CharCursorX + fonthdrWidth; X++)
                     if ((*FontPtr & (0b10000000 >> (X - *CharCursorX))) > 0)
                         InlineSetPixel(Bitmap, X, Y, Color);
                 FontPtr += BytesPerLine;
             }
             *CharCursorX += fonthdrWidth;
             break;
         }
         default:
             warn("Unsupported font type");
             break;
         }
     }
References c, Video::PSF1_HEADER::charsize, Video::PSF2_HEADER::charsize, Video::Font::GetInfo(), Video::_PSF1_FONT::GlyphBuffer, Video::_PSF1_FONT::Header, Video::_PSF2_FONT::Header, Video::PSF2_HEADER::headersize, Video::PSF2_HEADER::height, InlineSetPixel(), Video::PCScreenFont1, Video::PCScreenFont2, Video::FontInfo::PSF1Font, Video::FontInfo::PSF2Font, Video::FontInfo::StartAddress, Video::FontInfo::Type, warn, Video::PSF2_HEADER::width, and X.
Referenced by GraphicalUserInterface::WidgetCollection::OnPaintForeground(), and GraphicalUserInterface::GUI::PaintWindows().
PutBorder()
void GraphicalUserInterface::PutBorder (ScreenBitmap * Bitmap, Rect rect, uint32_t Color)
Definition at line 110 of file GUITools.cpp.
     {
         if (unlikely(!Bitmap))
             return;
         if (unlikely(!Bitmap->Data))
             return;
         for (uint32_t i = 0; i < rect.Width; i++)
         {
             InlineSetPixel(Bitmap, rect.Left + i, rect.Top, Color);
             InlineSetPixel(Bitmap, rect.Left + i, rect.Top + rect.Height - 1, Color);
         }
         for (uint32_t i = 0; i < rect.Height; i++)
         {
             InlineSetPixel(Bitmap, rect.Left, rect.Top + i, Color);
             InlineSetPixel(Bitmap, rect.Left + rect.Width - 1, rect.Top + i, Color);
         }
     }
References GraphicalUserInterface::Rect::Height, i, InlineSetPixel(), GraphicalUserInterface::Rect::Left, GraphicalUserInterface::Rect::Top, unlikely, and GraphicalUserInterface::Rect::Width.
Referenced by GraphicalUserInterface::GUI::PaintWindows().
PutBorderWithShadow()
void GraphicalUserInterface::PutBorderWithShadow (ScreenBitmap * Bitmap, Rect rect, uint32_t Color)
Definition at line 146 of file GUITools.cpp.
     {
         UNUSED(Bitmap);
         UNUSED(rect);
         UNUSED(Color);
     }
References UNUSED.
PutRect()
void GraphicalUserInterface::PutRect (ScreenBitmap * Bitmap, Rect rect, uint32_t Color)
Definition at line 97 of file GUITools.cpp.
     {
         if (unlikely(!Bitmap))
             return;
         if (unlikely(!Bitmap->Data))
             return;
         for (uint32_t i = 0; i < rect.Width; i++)
             for (uint32_t j = 0; j < rect.Height; j++)
                 InlineSetPixel(Bitmap, rect.Left + i, rect.Top + j, Color);
     }
References GraphicalUserInterface::Rect::Height, i, InlineSetPixel(), j, GraphicalUserInterface::Rect::Left, GraphicalUserInterface::Rect::Top, unlikely, and GraphicalUserInterface::Rect::Width.
Referenced by GraphicalUserInterface::Window::OnPaintBackground(), GraphicalUserInterface::WidgetCollection::OnPaintForeground(), and GraphicalUserInterface::GUI::PaintWindows().
SetPixel()
void GraphicalUserInterface::SetPixel (ScreenBitmap * Bitmap, size_t X, size_t Y, uint32_t Color)
Definition at line 34 of file GUITools.cpp.
     {
         if (unlikely(!Bitmap))
             return;
         if (unlikely(!Bitmap->Data))
             return;
         InlineSetPixel(Bitmap, X, Y, Color);
     }
References InlineSetPixel(), unlikely, and X.
Referenced by GraphicalUserInterface::GUI::PaintCursor(), and GraphicalUserInterface::GUI::PaintWindows().